v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit > Class Template Reference
#include <small-map.h>
Classes
class const_iterator
class iterator
Public Types
typedef NormalMap::key_type key_type
typedef NormalMap::mapped_type data_type
typedef NormalMap::mapped_type mapped_type
typedef NormalMap::value_type value_type
typedef EqualKey key_equal
Public Member Functions
SmallMap ()
SmallMap (const MapInit &functor)
SmallMap (const SmallMap &src) V8_NOEXCEPT
void operator= (const SmallMap &src) V8_NOEXCEPT
~SmallMap ()
iterator find (const key_type &key)
const_iterator find (const key_type &key) const
data_type & operator[] (const key_type &key)
std::pair< iterator, bool > insert (const value_type &x)
template<class InputIterator >
void insert (InputIterator f, InputIterator l)
template<typename... Args>
std::pair< iterator, bool > emplace (Args &&... args)
template<typename... Args>
std::pair< iterator, bool > try_emplace (const key_type &key, Args &&... args)
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
void clear ()
iterator erase (const iterator &position)
size_t erase (const key_type &key)
size_t count (const key_type &key) const
size_t size () const
bool empty () const
bool UsingFullMap () const
NormalMap * map ()
const NormalMap * map () const
Private Member Functions
V8_NOINLINE V8_PRESERVE_MOST void ConvertToRealMap ()
void InitFrom (const SmallMap &src)
void Destroy ()
Private Attributes
size_t size_
MapInit functor_
xx xx xx xx xx xx xx xx xx
union {
 value_type array_ [kArraySize]
 NormalMap map_
};
Static Private Attributes
static constexpr size_t kUsingFullMapSentinel
Detailed Description
template<typename NormalMap, size_t kArraySize = 4, typename EqualKey = typename internal::select_equal_key< NormalMap, internal::has_key_equal<NormalMap>::value>::equal_key, typename MapInit = internal::SmallMapDefaultInit<NormalMap>>
class v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >
Definition at line 141 of file small-map.h.
Member Typedef Documentation
data_type
template<typename NormalMap , size_t kArraySize = 4, typename EqualKey = typename internal::select_equal_key< NormalMap, internal::has_key_equal<NormalMap>::value>::equal_key, typename MapInit = internal::SmallMapDefaultInit<NormalMap>>
typedef NormalMap::mapped_type v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::data_type
Definition at line 151 of file small-map.h.
key_equal
template<typename NormalMap , size_t kArraySize = 4, typename EqualKey = typename internal::select_equal_key< NormalMap, internal::has_key_equal<NormalMap>::value>::equal_key, typename MapInit = internal::SmallMapDefaultInit<NormalMap>>
typedef EqualKey v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::key_equal
Definition at line 154 of file small-map.h.
key_type
template<typename NormalMap , size_t kArraySize = 4, typename EqualKey = typename internal::select_equal_key< NormalMap, internal::has_key_equal<NormalMap>::value>::equal_key, typename MapInit = internal::SmallMapDefaultInit<NormalMap>>
typedef NormalMap::key_type v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::key_type
Definition at line 150 of file small-map.h.
mapped_type
template<typename NormalMap , size_t kArraySize = 4, typename EqualKey = typename internal::select_equal_key< NormalMap, internal::has_key_equal<NormalMap>::value>::equal_key, typename MapInit = internal::SmallMapDefaultInit<NormalMap>>
typedef NormalMap::mapped_type v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::mapped_type
Definition at line 152 of file small-map.h.
value_type
template<typename NormalMap , size_t kArraySize = 4, typename EqualKey = typename internal::select_equal_key< NormalMap, internal::has_key_equal<NormalMap>::value>::equal_key, typename MapInit = internal::SmallMapDefaultInit<NormalMap>>
typedef NormalMap::value_type v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::value_type
Definition at line 153 of file small-map.h.
Constructor & Destructor Documentation
SmallMap() [1/3]
template<typename NormalMap , size_t kArraySize = 4, typename EqualKey = typename internal::select_equal_key< NormalMap, internal::has_key_equal<NormalMap>::value>::equal_key, typename MapInit = internal::SmallMapDefaultInit<NormalMap>>
v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::SmallMap () [inline]
Definition at line 156 of file small-map.h.
: size_(0), functor_(MapInit()) {}
SmallMap() [2/3]
template<typename NormalMap , size_t kArraySize = 4, typename EqualKey = typename internal::select_equal_key< NormalMap, internal::has_key_equal<NormalMap>::value>::equal_key, typename MapInit = internal::SmallMapDefaultInit<NormalMap>>
v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::SmallMap (const MapInit & functor) [inline], [explicit]
Definition at line 158 of file small-map.h.
: size_(0), functor_(functor) {}
SmallMap() [3/3]
template<typename NormalMap , size_t kArraySize = 4, typename EqualKey = typename internal::select_equal_key< NormalMap, internal::has_key_equal<NormalMap>::value>::equal_key, typename MapInit = internal::SmallMapDefaultInit<NormalMap>>
v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::SmallMap (const SmallMap< NormalMap, kArraySize, EqualKey, MapInit > & src) [inline]
Definition at line 161 of file small-map.h.
                                            {
    // size_ and functor_ are initted in InitFrom()
    InitFrom(src);
  }
References v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::InitFrom().
 SmallMap()
template<typename NormalMap , size_t kArraySize = 4, typename EqualKey = typename internal::select_equal_key< NormalMap, internal::has_key_equal<NormalMap>::value>::equal_key, typename MapInit = internal::SmallMapDefaultInit<NormalMap>>
v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::~SmallMap () [inline]
Definition at line 177 of file small-map.h.
{ Destroy(); }
References v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::Destroy().
Member Function Documentation
begin() [1/2]
template<typename NormalMap , size_t kArraySize = 4, typename EqualKey = typename internal::select_equal_key< NormalMap, internal::has_key_equal<NormalMap>::value>::equal_key, typename MapInit = internal::SmallMapDefaultInit<NormalMap>>
iterator v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::begin () [inline]
Definition at line 471 of file small-map.h.
                   {
    return UsingFullMap() ? iterator(map_.begin()) : iterator(array_);
  }
References v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::array_, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::map_, and v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::UsingFullMap().
Referenced by v8::internal::compiler::MoveOptimizer::MigrateMoves(), and v8::internal::compiler::MoveOptimizer::OptimizeMerge().
begin() [2/2]
template<typename NormalMap , size_t kArraySize = 4, typename EqualKey = typename internal::select_equal_key< NormalMap, internal::has_key_equal<NormalMap>::value>::equal_key, typename MapInit = internal::SmallMapDefaultInit<NormalMap>>
const_iterator v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::begin () const [inline]
Definition at line 475 of file small-map.h.
                               {
    return UsingFullMap() ? const_iterator(map_.begin())
                          : const_iterator(array_);
  }
References v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::array_, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::map_, and v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::UsingFullMap().
clear()
template<typename NormalMap , size_t kArraySize = 4, typename EqualKey = typename internal::select_equal_key< NormalMap, internal::has_key_equal<NormalMap>::value>::equal_key, typename MapInit = internal::SmallMapDefaultInit<NormalMap>>
void v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::clear () [inline]
Definition at line 489 of file small-map.h.
               {
    if (UsingFullMap()) {
      map_.~NormalMap();
    } else {
      for (size_t i = 0; i < size_; ++i) {
        array_[i].~value_type();
      }
    }
    size_ = 0;
  }
References v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::array_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::map_, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::size_, and v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::UsingFullMap().
ConvertToRealMap()
template<typename NormalMap , size_t kArraySize = 4, typename EqualKey = typename internal::select_equal_key< NormalMap, internal::has_key_equal<NormalMap>::value>::equal_key, typename MapInit = internal::SmallMapDefaultInit<NormalMap>>
V8_NOINLINE V8_PRESERVE_MOST void v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::ConvertToRealMap () [inline], [private]
Definition at line 567 of file small-map.h.
                                                       {
    // Storage for the elements in the temporary array. This is intentionally
    // declared as a union to avoid having to default-construct |kArraySize|
    // elements, only to move construct over them in the initial loop.
    union Storage {
      Storage() {}
      ~Storage() {}
      value_type array[kArraySize];
    } temp;
    // Move the current elements into a temporary array.
    for (size_t i = 0; i < kArraySize; ++i) {
      new (&temp.array[i]) value_type(std::move(array_[i]));
      array_[i].~value_type();
    }
    // Initialize the map.
    size_ = kUsingFullMapSentinel;
    functor_(&map_);
    // Insert elements into it.
    for (size_t i = 0; i < kArraySize; ++i) {
      map_.insert(std::move(temp.array[i]));
      temp.array[i].~value_type();
    }
  }
References v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::array_, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::functor_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::kUsingFullMapSentinel, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::map_, and v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::size_.
Referenced by v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::emplace(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::insert(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::operator[](), and v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::try_emplace().
count()
template<typename NormalMap , size_t kArraySize = 4, typename EqualKey = typename internal::select_equal_key< NormalMap, internal::has_key_equal<NormalMap>::value>::equal_key, typename MapInit = internal::SmallMapDefaultInit<NormalMap>>
size_t v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::count (const key_type & key) const [inline]
Definition at line 529 of file small-map.h.
                                          {
    return (find(key) == end()) ? 0 : 1;
  }
References v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::end(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::find(), and v8::internal::key.
Destroy()
template<typename NormalMap , size_t kArraySize = 4, typename EqualKey = typename internal::select_equal_key< NormalMap, internal::has_key_equal<NormalMap>::value>::equal_key, typename MapInit = internal::SmallMapDefaultInit<NormalMap>>
void v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::Destroy () [inline], [private]
Definition at line 608 of file small-map.h.
                 {
    if (UsingFullMap()) {
      map_.~NormalMap();
    } else {
      for (size_t i = 0; i < size_; ++i) {
        array_[i].~value_type();
      }
    }
  }
References v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::array_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::map_, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::size_, and v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::UsingFullMap().
Referenced by v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::operator=(), and v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::~SmallMap().
emplace()
template<typename NormalMap , size_t kArraySize = 4, typename EqualKey = typename internal::select_equal_key< NormalMap, internal::has_key_equal<NormalMap>::value>::equal_key, typename MapInit = internal::SmallMapDefaultInit<NormalMap>>
template<typename... Args>
std::pair<iterator, bool> v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::emplace (Args &&... args) [inline]
Definition at line 414 of file small-map.h.
                                                  {
    key_equal compare;
    if (UsingFullMap()) {
      std::pair<typename NormalMap::iterator, bool> ret =
          map_.emplace(std::forward<Args>(args)...);
      return std::make_pair(iterator(ret.first), ret.second);
    }
    value_type x(std::forward<Args>(args)...);
    for (size_t i = 0; i < size_; ++i) {
      if (compare(array_[i].first, x.first)) {
        return std::make_pair(iterator(array_ + i), false);
      }
    }
    if (V8_UNLIKELY(size_ == kArraySize)) {
      ConvertToRealMap(); // Invalidates all iterators!
      std::pair<typename NormalMap::iterator, bool> ret =
          map_.emplace(std::move(x));
      return std::make_pair(iterator(ret.first), ret.second);
    }
    DCHECK(size_ < kArraySize);
    new (&array_[size_]) value_type(std::move(x));
    return std::make_pair(iterator(array_ + size_++), true);
  }
References v8::base::args, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::array_, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::ConvertToRealMap(), DCHECK, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::map_, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::size_, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::UsingFullMap(), and V8_UNLIKELY.
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), v8::internal::compiler::LinearScanAllocator::ChooseOneOfTwoPredecessorStates(), v8::internal::compiler::LinearScanAllocator::ComputeStateFromManyPredecessors(), v8::internal::compiler::MoveOptimizer::MigrateMoves(), and v8::internal::compiler::MoveOptimizer::OptimizeMerge().
empty()
template<typename NormalMap , size_t kArraySize = 4, typename EqualKey = typename internal::select_equal_key< NormalMap, internal::has_key_equal<NormalMap>::value>::equal_key, typename MapInit = internal::SmallMapDefaultInit<NormalMap>>
bool v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::empty () const [inline]
Definition at line 535 of file small-map.h.
{ return UsingFullMap() ? map_.empty() : size_ == 0; }
References v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::map_, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::size_, and v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::UsingFullMap().
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), v8::internal::compiler::LinearScanAllocator::ComputeStateFromManyPredecessors(), v8::internal::compiler::MoveOptimizer::MigrateMoves(), and v8::internal::compiler::MoveOptimizer::OptimizeMerge().
end() [1/2]
template<typename NormalMap , size_t kArraySize = 4, typename EqualKey = typename internal::select_equal_key< NormalMap, internal::has_key_equal<NormalMap>::value>::equal_key, typename MapInit = internal::SmallMapDefaultInit<NormalMap>>
iterator v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::end () [inline]
Definition at line 480 of file small-map.h.
                 {
    return UsingFullMap() ? iterator(map_.end()) : iterator(array_ + size_);
  }
References v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::array_, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::map_, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::size_, and v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::UsingFullMap().
Referenced by v8::internal::compiler::LinearScanAllocator::ChooseOneOfTwoPredecessorStates(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::count(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::erase(), v8::internal::maglev::MergePointInterpreterFrameState::MergeVirtualObjects(), v8::internal::compiler::MoveOptimizer::MigrateMoves(), v8::internal::compiler::MoveOptimizer::OptimizeMerge(), and v8::internal::compiler::LinearScanAllocator::SpillNotLiveRanges().
end() [2/2]
template<typename NormalMap , size_t kArraySize = 4, typename EqualKey = typename internal::select_equal_key< NormalMap, internal::has_key_equal<NormalMap>::value>::equal_key, typename MapInit = internal::SmallMapDefaultInit<NormalMap>>
const_iterator v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::end () const [inline]
Definition at line 484 of file small-map.h.
                             {
    return UsingFullMap() ? const_iterator(map_.end())
                          : const_iterator(array_ + size_);
  }
References v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::array_, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::map_, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::size_, and v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::UsingFullMap().
erase() [1/2]
template<typename NormalMap , size_t kArraySize = 4, typename EqualKey = typename internal::select_equal_key< NormalMap, internal::has_key_equal<NormalMap>::value>::equal_key, typename MapInit = internal::SmallMapDefaultInit<NormalMap>>
iterator v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::erase (const iterator & position) [inline]
Definition at line 501 of file small-map.h.
                                           {
    if (UsingFullMap()) {
      return iterator(map_.erase(position.map_iter_));
    }
    size_t i = static_cast<size_t>(position.array_iter_ - array_);
    // TODO(crbug.com/817982): When we have a checked iterator, this CHECK might
    // not be necessary.
    CHECK_LE(i, size_);
    array_[i].~value_type();
    --size_;
    if (i != size_) {
      new (&array_[i]) value_type(std::move(array_[size_]));
      array_[size_].~value_type();
      return iterator(array_ + i);
    }
    return end();
  }
References v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::array_, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::iterator::array_iter_, CHECK_LE, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::end(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::map_, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::iterator::map_iter_, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::size_, and v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::UsingFullMap().
Referenced by v8::internal::compiler::LinearScanAllocator::ChooseOneOfTwoPredecessorStates(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::erase(), v8::internal::maglev::MergePointInterpreterFrameState::MergeVirtualObjects(), v8::internal::compiler::MoveOptimizer::MigrateMoves(), v8::internal::compiler::MoveOptimizer::OptimizeMerge(), and v8::internal::compiler::LinearScanAllocator::SpillNotLiveRanges().
erase() [2/2]
template<typename NormalMap , size_t kArraySize = 4, typename EqualKey = typename internal::select_equal_key< NormalMap, internal::has_key_equal<NormalMap>::value>::equal_key, typename MapInit = internal::SmallMapDefaultInit<NormalMap>>
size_t v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::erase (const key_type & key) [inline]
Definition at line 520 of file small-map.h.
                                    {
    iterator iter = find(key);
    if (iter == end()) {
      return 0;
    }
    erase(iter);
    return 1;
  }
References v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::end(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::erase(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::find(), and v8::internal::key.
find() [1/2]
template<typename NormalMap , size_t kArraySize = 4, typename EqualKey = typename internal::select_equal_key< NormalMap, internal::has_key_equal<NormalMap>::value>::equal_key, typename MapInit = internal::SmallMapDefaultInit<NormalMap>>
iterator v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::find (const key_type & key) [inline]
Definition at line 321 of file small-map.h.
                                     {
    key_equal compare;
    if (UsingFullMap()) {
      return iterator(map()->find(key));
    }
    for (size_t i = 0; i < size_; ++i) {
      if (compare(array_[i].first, key)) {
        return iterator(array_ + i);
      }
    }
    return iterator(array_ + size_);
  }
References v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::array_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::key, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::map(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::size_, and v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::UsingFullMap().
Referenced by v8::internal::compiler::LinearScanAllocator::ChooseOneOfTwoPredecessorStates(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::count(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::erase(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::find(), v8::internal::maglev::MergePointInterpreterFrameState::MergeVirtualObjects(), v8::internal::compiler::MoveOptimizer::MigrateMoves(), v8::internal::compiler::MoveOptimizer::OptimizeMerge(), and v8::internal::compiler::LinearScanAllocator::SpillNotLiveRanges().
find() [2/2]
template<typename NormalMap , size_t kArraySize = 4, typename EqualKey = typename internal::select_equal_key< NormalMap, internal::has_key_equal<NormalMap>::value>::equal_key, typename MapInit = internal::SmallMapDefaultInit<NormalMap>>
const_iterator v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::find (const key_type & key) const [inline]
Definition at line 336 of file small-map.h.
                                                 {
    key_equal compare;
    if (UsingFullMap()) {
      return const_iterator(map()->find(key));
    }
    for (size_t i = 0; i < size_; ++i) {
      if (compare(array_[i].first, key)) {
        return const_iterator(array_ + i);
      }
    }
    return const_iterator(array_ + size_);
  }
References v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::array_, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::find(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::key, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::map(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::size_, and v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::UsingFullMap().
InitFrom()
template<typename NormalMap , size_t kArraySize = 4, typename EqualKey = typename internal::select_equal_key< NormalMap, internal::has_key_equal<NormalMap>::value>::equal_key, typename MapInit = internal::SmallMapDefaultInit<NormalMap>>
void v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::InitFrom (const SmallMap< NormalMap, kArraySize, EqualKey, MapInit > & src) [inline], [private]
Definition at line 595 of file small-map.h.
                                     {
    functor_ = src.functor_;
    size_ = src.size_;
    if (src.UsingFullMap()) {
      functor_(&map_);
      map_ = src.map_;
    } else {
      for (size_t i = 0; i < size_; ++i) {
        new (&array_[i]) value_type(src.array_[i]);
      }
    }
  }
References v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::array_, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::functor_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::map_, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::size_, and v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::UsingFullMap().
Referenced by v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::operator=(), and v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::SmallMap().
insert() [1/2]
template<typename NormalMap , size_t kArraySize = 4, typename EqualKey = typename internal::select_equal_key< NormalMap, internal::has_key_equal<NormalMap>::value>::equal_key, typename MapInit = internal::SmallMapDefaultInit<NormalMap>>
std::pair<iterator, bool> v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::insert (const value_type & x) [inline]
Definition at line 378 of file small-map.h.
                                                      {
    key_equal compare;
    if (UsingFullMap()) {
      std::pair<typename NormalMap::iterator, bool> ret = map_.insert(x);
      return std::make_pair(iterator(ret.first), ret.second);
    }
    for (size_t i = 0; i < size_; ++i) {
      if (compare(array_[i].first, x.first)) {
        return std::make_pair(iterator(array_ + i), false);
      }
    }
    if (V8_UNLIKELY(size_ == kArraySize)) {
      ConvertToRealMap(); // Invalidates all iterators!
      std::pair<typename NormalMap::iterator, bool> ret = map_.insert(x);
      return std::make_pair(iterator(ret.first), ret.second);
    }
    DCHECK(size_ < kArraySize);
    new (&array_[size_]) value_type(x);
    return std::make_pair(iterator(array_ + size_++), true);
  }
References v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::array_, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::ConvertToRealMap(), DCHECK, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::map_, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::size_, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::UsingFullMap(), and V8_UNLIKELY.
Referenced by v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::insert().
insert() [2/2]
template<typename NormalMap , size_t kArraySize = 4, typename EqualKey = typename internal::select_equal_key< NormalMap, internal::has_key_equal<NormalMap>::value>::equal_key, typename MapInit = internal::SmallMapDefaultInit<NormalMap>>
template<class InputIterator >
void v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::insert (InputIterator f, InputIterator l) [inline]
Definition at line 405 of file small-map.h.
                                                {
    while (f != l) {
      insert(*f);
      ++f;
    }
  }
References v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::insert(), and v8::internal::compiler::turboshaft::l.
map() [1/2]
template<typename NormalMap , size_t kArraySize = 4, typename EqualKey = typename internal::select_equal_key< NormalMap, internal::has_key_equal<NormalMap>::value>::equal_key, typename MapInit = internal::SmallMapDefaultInit<NormalMap>>
NormalMap* v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::map () [inline]
Definition at line 541 of file small-map.h.
                             {
    CHECK(UsingFullMap());
    return &map_;
  }
References CHECK, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::map_, and v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::UsingFullMap().
Referenced by v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::find().
map() [2/2]
template<typename NormalMap , size_t kArraySize = 4, typename EqualKey = typename internal::select_equal_key< NormalMap, internal::has_key_equal<NormalMap>::value>::equal_key, typename MapInit = internal::SmallMapDefaultInit<NormalMap>>
const NormalMap* v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::map () const [inline]
Definition at line 546 of file small-map.h.
                                         {
    CHECK(UsingFullMap());
    return &map_;
  }
References CHECK, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::map_, and v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::UsingFullMap().
operator=()
template<typename NormalMap , size_t kArraySize = 4, typename EqualKey = typename internal::select_equal_key< NormalMap, internal::has_key_equal<NormalMap>::value>::equal_key, typename MapInit = internal::SmallMapDefaultInit<NormalMap>>
void v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::operator= (const SmallMap< NormalMap, kArraySize, EqualKey, MapInit > & src) [inline]
Definition at line 166 of file small-map.h.
                                                  {
    if (&src == this) return;
    // This is not optimal. If src and dest are both using the small array, we
    // could skip the teardown and reconstruct. One problem to be resolved is
    // that the value_type itself is pair<const K, V>, and const K is not
    // assignable.
    Destroy();
    InitFrom(src);
  }
References v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::Destroy(), and v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::InitFrom().
operator[]()
template<typename NormalMap , size_t kArraySize = 4, typename EqualKey = typename internal::select_equal_key< NormalMap, internal::has_key_equal<NormalMap>::value>::equal_key, typename MapInit = internal::SmallMapDefaultInit<NormalMap>>
data_type& v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::operator[] (const key_type & key) [inline]
Definition at line 352 of file small-map.h.
                                             {
    key_equal compare;
    if (UsingFullMap()) {
      return map_[key];
    }
    // Search backwards to favor recently-added elements.
    for (size_t i = size_; i > 0; --i) {
      const size_t index = i - 1;
      if (compare(array_[index].first, key)) {
        return array_[index].second;
      }
    }
    if (V8_UNLIKELY(size_ == kArraySize)) {
      ConvertToRealMap();
      return map_[key];
    }
    DCHECK(size_ < kArraySize);
    new (&array_[size_]) value_type(key, data_type());
    return array_[size_++].second;
  }
References v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::array_, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::ConvertToRealMap(), DCHECK, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::key, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::map_, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::size_, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::UsingFullMap(), and V8_UNLIKELY.
size()
template<typename NormalMap , size_t kArraySize = 4, typename EqualKey = typename internal::select_equal_key< NormalMap, internal::has_key_equal<NormalMap>::value>::equal_key, typename MapInit = internal::SmallMapDefaultInit<NormalMap>>
size_t v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::size () const [inline]
Definition at line 533 of file small-map.h.
{ return UsingFullMap() ? map_.size() : size_; }
References v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::map_, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::size_, and v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::UsingFullMap().
Referenced by v8::internal::compiler::MoveOptimizer::OptimizeMerge().
try_emplace()
template<typename NormalMap , size_t kArraySize = 4, typename EqualKey = typename internal::select_equal_key< NormalMap, internal::has_key_equal<NormalMap>::value>::equal_key, typename MapInit = internal::SmallMapDefaultInit<NormalMap>>
template<typename... Args>
std::pair<iterator, bool> v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::try_emplace (const key_type & key, Args &&... args) [inline]
Definition at line 444 of file small-map.h.
                                                                           {
    key_equal compare;
    if (UsingFullMap()) {
      std::pair<typename NormalMap::iterator, bool> ret =
          map_.try_emplace(key, std::forward<Args>(args)...);
      return std::make_pair(iterator(ret.first), ret.second);
    }
    for (size_t i = 0; i < size_; ++i) {
      if (compare(array_[i].first, key)) {
        return std::make_pair(iterator(array_ + i), false);
      }
    }
    if (V8_UNLIKELY(size_ == kArraySize)) {
      ConvertToRealMap(); // Invalidates all iterators!
      std::pair<typename NormalMap::iterator, bool> ret =
          map_.try_emplace(key, std::forward<Args>(args)...);
      return std::make_pair(iterator(ret.first), ret.second);
    }
    DCHECK(size_ < kArraySize);
    new (&array_[size_]) value_type(key, std::forward<Args>(args)...);
    return std::make_pair(iterator(array_ + size_++), true);
  }
References v8::base::args, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::array_, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::ConvertToRealMap(), DCHECK, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::key, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::map_, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::size_, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::UsingFullMap(), and V8_UNLIKELY.
UsingFullMap()
template<typename NormalMap , size_t kArraySize = 4, typename EqualKey = typename internal::select_equal_key< NormalMap, internal::has_key_equal<NormalMap>::value>::equal_key, typename MapInit = internal::SmallMapDefaultInit<NormalMap>>
bool v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::UsingFullMap () const [inline]
Definition at line 539 of file small-map.h.
{ return size_ == kUsingFullMapSentinel; }
References v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::kUsingFullMapSentinel, and v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::size_.
Referenced by v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::begin(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::clear(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::Destroy(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::emplace(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::empty(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::end(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::erase(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::find(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::InitFrom(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::insert(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::map(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::operator[](), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::size(), and v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::try_emplace().
Member Data Documentation
union { ... } [private]
array_
template<typename NormalMap , size_t kArraySize = 4, typename EqualKey = typename internal::select_equal_key< NormalMap, internal::has_key_equal<NormalMap>::value>::equal_key, typename MapInit = internal::SmallMapDefaultInit<NormalMap>>
value_type v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::array_[kArraySize]
Definition at line 563 of file small-map.h.
Referenced by v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::begin(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::clear(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::ConvertToRealMap(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::Destroy(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::emplace(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::end(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::erase(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::find(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::InitFrom(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::insert(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::operator[](), and v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::try_emplace().
functor_
template<typename NormalMap , size_t kArraySize = 4, typename EqualKey = typename internal::select_equal_key< NormalMap, internal::has_key_equal<NormalMap>::value>::equal_key, typename MapInit = internal::SmallMapDefaultInit<NormalMap>>
MapInit v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::functor_ [private]
Definition at line 557 of file small-map.h.
Referenced by v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::ConvertToRealMap(), and v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::InitFrom().
kUsingFullMapSentinel
template<typename NormalMap , size_t kArraySize = 4, typename EqualKey = typename internal::select_equal_key< NormalMap, internal::has_key_equal<NormalMap>::value>::equal_key, typename MapInit = internal::SmallMapDefaultInit<NormalMap>>
constexpr size_t v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::kUsingFullMapSentinel [static], [constexpr], [private]
Initial value:
=
      std::numeric_limits<size_t>::max()
Definition at line 142 of file small-map.h.
Referenced by v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::ConvertToRealMap(), and v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::UsingFullMap().
map_
template<typename NormalMap , size_t kArraySize = 4, typename EqualKey = typename internal::select_equal_key< NormalMap, internal::has_key_equal<NormalMap>::value>::equal_key, typename MapInit = internal::SmallMapDefaultInit<NormalMap>>
NormalMap v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::map_
Definition at line 564 of file small-map.h.
Referenced by v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::begin(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::clear(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::ConvertToRealMap(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::Destroy(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::emplace(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::empty(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::end(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::erase(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::InitFrom(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::insert(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::map(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::operator[](), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::size(), and v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::try_emplace().
size_
template<typename NormalMap , size_t kArraySize = 4, typename EqualKey = typename internal::select_equal_key< NormalMap, internal::has_key_equal<NormalMap>::value>::equal_key, typename MapInit = internal::SmallMapDefaultInit<NormalMap>>
size_t v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::size_ [private]
Definition at line 555 of file small-map.h.
Referenced by v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::clear(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::ConvertToRealMap(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::Destroy(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::emplace(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::empty(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::end(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::erase(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::find(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::InitFrom(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::insert(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::operator[](), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::size(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::try_emplace(), and v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::UsingFullMap().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/base/small-map.h