cppgc::internal::ProcessGlobalLock Class Reference
#include <process-heap.h>
Public Types
enum class Reason { kForGC
, kForCrossThreadHandleCreation
 }
Static Public Member Functions
template<Reason reason>
static void Lock ()
template<Reason reason>
static void Unlock ()
static void AssertHeld ()
Static Private Attributes
static v8::base::LazyMutex process_mutex_ = LAZY_MUTEX_INITIALIZER
Detailed Description
Definition at line 18 of file process-heap.h.
Member Enumeration Documentation
Reason
enum cppgc::internal::ProcessGlobalLock::Reason [strong]
Enumerator
kForGC
kForCrossThreadHandleCreation
Definition at line 20 of file process-heap.h.
                    {
    kForGC,
    kForCrossThreadHandleCreation,
  };
Member Function Documentation
AssertHeld()
static void cppgc::internal::ProcessGlobalLock::AssertHeld () [inline], [static]
Definition at line 66 of file process-heap.h.
{ process_mutex_.Pointer()->AssertHeld(); }
References v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Pointer(), and process_mutex_.
Referenced by cppgc::internal::MarkerBase::ProcessCrossThreadWeaknessIfNeeded().
Lock()
template<Reason reason>
static void cppgc::internal::ProcessGlobalLock::Lock () [inline], [static]
Definition at line 26 of file process-heap.h.
                               {
    process_mutex_.Pointer()->Lock();
#if defined(V8_USE_PERFETTO)
    switch (reason) {
      case Reason::kForGC:
        TRACE_EVENT_BEGIN(TRACE_DISABLED_BY_DEFAULT("cppgc"), "AcquiredForGC",
                          perfetto::NamedTrack("CppGC.ProcessGlobalLock"));
        break;
      case Reason::kForCrossThreadHandleCreation:
#ifdef DEBUG
        TRACE_EVENT_BEGIN(TRACE_DISABLED_BY_DEFAULT("cppgc"),
                          "AcquiredForCrossThreadHandleCreation",
                          perfetto::NamedTrack("CppGC.ProcessGlobalLock"));
#endif // DEBUG
        break;
    }
#endif // defined(V8_USE_PERFETTO)
  }
References kForCrossThreadHandleCreation, kForGC, v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Pointer(), process_mutex_, and TRACE_DISABLED_BY_DEFAULT.
Unlock()
template<Reason reason>
static void cppgc::internal::ProcessGlobalLock::Unlock () [inline], [static]
Definition at line 47 of file process-heap.h.
                                 {
#if defined(V8_USE_PERFETTO)
    switch (reason) {
      case Reason::kForGC:
        TRACE_EVENT_END(TRACE_DISABLED_BY_DEFAULT("cppgc"),
                        perfetto::NamedTrack("CppGC.ProcessGlobalLock"));
        break;
      case Reason::kForCrossThreadHandleCreation:
#ifdef DEBUG
        TRACE_EVENT_END(TRACE_DISABLED_BY_DEFAULT("cppgc"),
                        perfetto::NamedTrack("CppGC.ProcessGlobalLock"));
#endif // DEBUG
        break;
    }
#endif // defined(V8_USE_PERFETTO)
    process_mutex_.Pointer()->Unlock();
  }
References kForCrossThreadHandleCreation, kForGC, v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Pointer(), process_mutex_, and TRACE_DISABLED_BY_DEFAULT.
Member Data Documentation
process_mutex_
v8::base::LazyMutex cppgc::internal::ProcessGlobalLock::process_mutex_ = LAZY_MUTEX_INITIALIZER [static], [private]
Definition at line 69 of file process-heap.h.
Referenced by AssertHeld(), Lock(), and Unlock().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/process-heap.h
/mnt/V8SourceCode/src/heap/cppgc/process-heap.cc