cppgc::internal::Filler Class Reference
#include <free-list.h>
Static Public Member Functions
static Filler & CreateAt (void *memory, size_t size)
Protected Member Functions
Filler (size_t size)
Additional Inherited Members
Detailed Description
Definition at line 19 of file free-list.h.
Constructor & Destructor Documentation
Filler()
cppgc::internal::Filler::Filler (size_t size) [inline], [explicit], [protected]
Definition at line 24 of file free-list.h.
: HeapObjectHeader(size, kFreeListGCInfoIndex) {}
Referenced by CreateAt().
Member Function Documentation
CreateAt()
Filler & cppgc::internal::Filler::CreateAt (void * memory, size_t size) [inline], [static]
Definition at line 76 of file free-list.h.
                                                  {
  // The memory area only needs to unpoisoned when running with ASAN. Zapped
  // values (DEBUG) or uninitialized values (MSAN) are overwritten below.
  ASAN_UNPOISON_MEMORY_REGION(memory, sizeof(Filler));
  return *new (memory) Filler(size);
}
References ASAN_UNPOISON_MEMORY_REGION, Filler(), and size().
Referenced by cppgc::internal::FreeList::AddReturningUnusedBounds(), and cppgc::internal::ObjectAllocator::AllocateObjectOnSpace().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc/free-list.h