cppgc::internal::LargePage Class Reference
#include <heap-page.h>
Public Member Functions
HeapObjectHeader * ObjectHeader ()
const HeapObjectHeader * ObjectHeader () const
Address PayloadStart ()
ConstAddress PayloadStart () const
Address PayloadEnd ()
ConstAddress PayloadEnd () const
size_t PayloadSize () const
size_t ObjectSize () const
size_t AllocatedBytesAtLastGC () const
bool PayloadContains (ConstAddress address) const
Static Public Member Functions
static constexpr size_t PageHeaderSize ()
static size_t AllocationSize (size_t size)
static LargePage * TryCreate (PageBackend &, LargePageSpace &, size_t)
static void Destroy (LargePage *)
static LargePage * From (BasePage *page)
static const LargePage * From (const BasePage *page)
Private Member Functions
LargePage (HeapBase &heap, BaseSpace &space, size_t)
~LargePage ()=default
Private Attributes
size_t payload_size_
Static Private Attributes
static constexpr size_t kGuaranteedObjectAlignment
Additional Inherited Members
Detailed Description
Definition at line 256 of file heap-page.h.
Constructor & Destructor Documentation
LargePage()
cppgc::internal::LargePage::LargePage (HeapBase & heap, BaseSpace & space, size_t size) [private]
Definition at line 241 of file heap-page.cc.
    : BasePage(heap, space, PageType::kLarge), payload_size_(size) {}
Referenced by TryCreate().
 LargePage()
cppgc::internal::LargePage::~LargePage () [private], [default]
Referenced by Destroy().
Member Function Documentation
AllocatedBytesAtLastGC()
size_t cppgc::internal::LargePage::AllocatedBytesAtLastGC () const [inline]
Definition at line 297 of file heap-page.h.
{ return ObjectSize(); }
Referenced by cppgc::internal::BasePage::AllocatedBytesAtLastGC().
AllocationSize()
size_t cppgc::internal::LargePage::AllocationSize (size_t size) [static]
Definition at line 245 of file heap-page.cc.
                                                    {
  return PageHeaderSize() + payload_size;
}
References PageHeaderSize().
Referenced by Destroy(), TryCreate(), and cppgc::internal::HeapStatisticsCollector::VisitLargePage().
Destroy()
void cppgc::internal::LargePage::Destroy (LargePage * page) [static]
Definition at line 273 of file heap-page.cc.
                                       {
  DCHECK(page);
  HeapBase& heap = page->heap();
  const size_t payload_size = page->PayloadSize();
#if DEBUG
  const BaseSpace& space = page->space();
  {
    // Destroy() happens on the mutator but another concurrent sweeper task may
    // add add a live object using `BaseSpace::AddPage()` while iterating the
    // pages.
    v8::base::MutexGuard guard(&space.pages_mutex());
    DCHECK_EQ(space.end(), std::find(space.begin(), space.end(), page));
  }
#endif // DEBUG
  page->~LargePage();
  PageBackend* backend = heap.page_backend();
  heap.stats_collector()->NotifyFreedMemory(AllocationSize(payload_size));
  backend->FreeLargePageMemory(reinterpret_cast<Address>(page));
}
References AllocationSize(), cppgc::internal::BaseSpace::begin(), DCHECK, DCHECK_EQ, cppgc::internal::BaseSpace::end(), cppgc::internal::PageBackend::FreeLargePageMemory(), cppgc::internal::BasePage::heap(), cppgc::internal::BaseSpace::pages_mutex(), PayloadSize(), cppgc::internal::BasePage::space(), and ~LargePage().
Referenced by cppgc::internal::BasePage::Destroy(), cppgc::internal::ExplicitManagementImpl::FreeUnreferencedObject(), and cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::VisitLargePage().
From() [1/2]
static LargePage* cppgc::internal::LargePage::From (BasePage * page) [inline], [static]
Definition at line 275 of file heap-page.h.
                                         {
    DCHECK(page->is_large());
    return static_cast<LargePage*>(page);
  }
References DCHECK, and cppgc::internal::BasePage::is_large().
Referenced by cppgc::internal::BasePage::AllocatedBytesAtLastGC(), cppgc::internal::BasePage::AllocatedSize(), cppgc::internal::BasePage::Destroy(), cppgc::internal::ObjectView< AccessMode >::End(), cppgc::internal::HeapObjectHeader::Finalize(), cppgc::internal::anonymous_namespace{sweeper.cc}::SweepFinalizer::FinalizePage(), cppgc::internal::ExplicitManagementImpl::FreeUnreferencedObject(), cppgc::internal::ObjectHeaderFromInnerAddressImpl(), cppgc::internal::BasePage::PayloadEnd(), cppgc::internal::BasePage::PayloadStart(), cppgc::internal::MarkingVerifierBase::ReportDifferences(), cppgc::internal::ObjectView< AccessMode >::Size(), cppgc::internal::HeapVisitor< Derived >::Traverse(), cppgc::internal::BasePage::TryObjectHeaderFromInnerAddress(), cppgc::internal::HeapStatisticsCollector::VisitHeapObjectHeader(), and cppgc::internal::anonymous_namespace{sweeper.cc}::PrepareForSweepVisitor::VisitLargePageSpace().
From() [2/2]
static const LargePage* cppgc::internal::LargePage::From (const BasePage * page) [inline], [static]
Definition at line 279 of file heap-page.h.
                                                     {
    return From(const_cast<BasePage*>(page));
  }
ObjectHeader() [1/2]
HeapObjectHeader * cppgc::internal::LargePage::ObjectHeader ()
Definition at line 293 of file heap-page.cc.
                                          {
  return reinterpret_cast<HeapObjectHeader*>(PayloadStart());
}
References PayloadStart().
Referenced by cppgc::internal::ObjectHeaderFromInnerAddressImpl(), cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::SweepLiveLargePage(), cppgc::internal::anonymous_namespace{object-allocator.cc}::TryAllocateLargeObject(), cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::VisitLargePage(), cppgc::internal::anonymous_namespace{sweeper.cc}::ConcurrentSweepTask::VisitLargePage(), and cppgc::internal::anonymous_namespace{sweeper.cc}::PrepareForSweepVisitor::VisitLargePageSpace().
ObjectHeader() [2/2]
const HeapObjectHeader * cppgc::internal::LargePage::ObjectHeader () const
Definition at line 297 of file heap-page.cc.
                                                      {
  return reinterpret_cast<const HeapObjectHeader*>(PayloadStart());
}
References PayloadStart().
ObjectSize()
size_t cppgc::internal::LargePage::ObjectSize () const [inline]
Definition at line 292 of file heap-page.h.
                            {
    DCHECK_GT(payload_size_, sizeof(HeapObjectHeader));
    return payload_size_ - sizeof(HeapObjectHeader);
  }
References DCHECK_GT.
Referenced by cppgc::internal::HeapObjectHeader::Finalize(), and cppgc::internal::ObjectView< AccessMode >::Size().
PageHeaderSize()
static constexpr size_t cppgc::internal::LargePage::PageHeaderSize () [inline], [static], [constexpr]
Definition at line 258 of file heap-page.h.
                                           {
    // Header should be un-aligned to `kAllocationGranularity` so that adding a
    // `HeapObjectHeader` gets the user object aligned to
    // `kGuaranteedObjectAlignment`.
    return RoundUp<kGuaranteedObjectAlignment>(sizeof(LargePage) +
                                               sizeof(HeapObjectHeader)) -
           sizeof(HeapObjectHeader);
  }
Referenced by cppgc::internal::BasePage::AllocatedSize(), AllocationSize(), and PayloadStart().
PayloadContains()
bool cppgc::internal::LargePage::PayloadContains (ConstAddress address) const [inline]
Definition at line 299 of file heap-page.h.
                                                   {
    return (PayloadStart() <= address) && (address < PayloadEnd());
  }
PayloadEnd() [1/2]
Address cppgc::internal::LargePage::PayloadEnd ()
Definition at line 309 of file heap-page.cc.
{ return PayloadStart() + PayloadSize(); }
References PayloadSize(), and PayloadStart().
Referenced by cppgc::internal::ObjectView< AccessMode >::End(), cppgc::internal::ObjectAllocator::MarkAllPagesAsYoung(), cppgc::internal::BasePage::PayloadEnd(), PayloadEnd(), and cppgc::internal::anonymous_namespace{object-allocator.cc}::TryAllocateLargeObject().
PayloadEnd() [2/2]
ConstAddress cppgc::internal::LargePage::PayloadEnd () const
Definition at line 311 of file heap-page.cc.
                                         {
  return const_cast<LargePage*>(this)->PayloadEnd();
}
References PayloadEnd().
PayloadSize()
size_t cppgc::internal::LargePage::PayloadSize () const [inline]
Definition at line 291 of file heap-page.h.
{ return payload_size_; }
Referenced by cppgc::internal::BasePage::AllocatedSize(), Destroy(), cppgc::internal::ExplicitManagementImpl::FreeUnreferencedObject(), PayloadEnd(), cppgc::internal::HeapStatisticsCollector::VisitHeapObjectHeader(), cppgc::internal::HeapStatisticsCollector::VisitLargePage(), and cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::VisitLargePage().
PayloadStart() [1/2]
Address cppgc::internal::LargePage::PayloadStart ()
Definition at line 301 of file heap-page.cc.
                                {
  return reinterpret_cast<Address>(this) + PageHeaderSize();
}
References PageHeaderSize().
Referenced by cppgc::internal::ObjectAllocator::MarkAllPagesAsYoung(), ObjectHeader(), PayloadEnd(), cppgc::internal::BasePage::PayloadStart(), PayloadStart(), and cppgc::internal::anonymous_namespace{object-allocator.cc}::TryAllocateLargeObject().
PayloadStart() [2/2]
ConstAddress cppgc::internal::LargePage::PayloadStart () const
Definition at line 305 of file heap-page.cc.
                                           {
  return const_cast<LargePage*>(this)->PayloadStart();
}
References PayloadStart().
TryCreate()
LargePage * cppgc::internal::LargePage::TryCreate (PageBackend & page_backend, LargePageSpace & space, size_t size) [static]
Definition at line 250 of file heap-page.cc.
                                                                    {
  // Ensure that the API-provided alignment guarantees does not violate the
  // internally guaranteed alignment of large page allocations.
  static_assert(kGuaranteedObjectAlignment <=
                api_constants::kMaxSupportedAlignment);
  static_assert(
      api_constants::kMaxSupportedAlignment % kGuaranteedObjectAlignment == 0);
  DCHECK_LE(kLargeObjectSizeThreshold, size);
  const size_t allocation_size = AllocationSize(size);
  auto* heap = space.raw_heap()->heap();
  void* memory = page_backend.TryAllocateLargePageMemory(allocation_size);
  if (!memory) return nullptr;
  LargePage* page = new (memory) LargePage(*heap, space, size);
  page->SynchronizedStore();
  page->heap().stats_collector()->NotifyAllocatedMemory(allocation_size);
  return page;
}
References AllocationSize(), DCHECK_LE, cppgc::internal::RawHeap::heap(), cppgc::internal::BasePage::heap(), kGuaranteedObjectAlignment, cppgc::internal::kLargeObjectSizeThreshold, cppgc::internal::api_constants::kMaxSupportedAlignment, LargePage(), cppgc::internal::StatsCollector::NotifyAllocatedMemory(), cppgc::internal::BaseSpace::raw_heap(), size(), cppgc::internal::BasePage::space(), cppgc::internal::HeapBase::stats_collector(), cppgc::internal::BasePage::SynchronizedStore(), and cppgc::internal::PageBackend::TryAllocateLargePageMemory().
Referenced by cppgc::internal::anonymous_namespace{object-allocator.cc}::TryAllocateLargeObjectImpl().
Member Data Documentation
kGuaranteedObjectAlignment
constexpr size_t cppgc::internal::LargePage::kGuaranteedObjectAlignment [static], [constexpr], [private]
Initial value:
=
      2 * kAllocationGranularity
Definition at line 304 of file heap-page.h.
Referenced by TryCreate().
payload_size_
size_t cppgc::internal::LargePage::payload_size_ [private]
Definition at line 310 of file heap-page.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/heap-page.h
/mnt/V8SourceCode/src/heap/cppgc/heap-page.cc