v8::internal::compiler::CreateCollectionIteratorParameters Class Reference
#include <js-operator.h>
Public Member Functions
CreateCollectionIteratorParameters (CollectionKind collection_kind, IterationKind iteration_kind)
CollectionKind collection_kind () const
IterationKind iteration_kind () const
Private Attributes
CollectionKind const collection_kind_
IterationKind const iteration_kind_
Detailed Description
Definition at line 616 of file js-operator.h.
Constructor & Destructor Documentation
CreateCollectionIteratorParameters()
v8::internal::compiler::CreateCollectionIteratorParameters::CreateCollectionIteratorParameters (CollectionKind collection_kind, IterationKind iteration_kind) [inline], [explicit]
Definition at line 618 of file js-operator.h.
      : collection_kind_(collection_kind), iteration_kind_(iteration_kind) {
    CHECK(!(collection_kind == CollectionKind::kSet &&
            iteration_kind == IterationKind::kKeys));
  }
References CHECK, collection_kind(), iteration_kind(), v8::internal::kKeys, and v8::internal::kSet.
Member Function Documentation
collection_kind()
CollectionKind v8::internal::compiler::CreateCollectionIteratorParameters::collection_kind () const [inline]
Definition at line 625 of file js-operator.h.
{ return collection_kind_; }
References collection_kind_.
Referenced by CreateCollectionIteratorParameters(), v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), and v8::internal::compiler::JSCreateLowering::ReduceJSCreateCollectionIterator().
iteration_kind()
IterationKind v8::internal::compiler::CreateCollectionIteratorParameters::iteration_kind () const [inline]
Definition at line 626 of file js-operator.h.
{ return iteration_kind_; }
References iteration_kind_.
Referenced by CreateCollectionIteratorParameters(), v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), and v8::internal::compiler::JSCreateLowering::ReduceJSCreateCollectionIterator().
Member Data Documentation
collection_kind_
CollectionKind const v8::internal::compiler::CreateCollectionIteratorParameters::collection_kind_ [private]
Definition at line 629 of file js-operator.h.
Referenced by collection_kind().
iteration_kind_
IterationKind const v8::internal::compiler::CreateCollectionIteratorParameters::iteration_kind_ [private]
Definition at line 630 of file js-operator.h.
Referenced by iteration_kind().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h