v8::internal::String Class Reference
#include <string.h>
Classes
class FlatContent
class Match
Public Types
enum Encoding { ONE_BYTE_ENCODING
, TWO_BYTE_ENCODING
 }
enum class EqualityType { kWholeString
, kPrefix
, kNoLengthCheck
 }
enum TrimMode { kTrim
, kTrimStart
, kTrimEnd
 }
enum class Utf8EncodingFlag { kNoFlags = 0
, kNullTerminate = 1u << 0
, kReplaceInvalid = 1u << 1
 }
using Utf8EncodingFlags = base::Flags< Utf8EncodingFlag >
using LineEndsVector = base::SmallVector< int32_t, kInlineLineEndsSize >
Public Member Functions
template<typename IsolateT >
void MakeThin (IsolateT *isolate, Tagged< String > canonical)
template<typename Char >
base::Vector< const Char > GetCharVector (const DisallowGarbageCollection &no_gc)
template<typename Char >
const Char * GetDirectStringChars (const DisallowGarbageCollection &no_gc) const
template<typename Char >
const Char * GetDirectStringChars (const DisallowGarbageCollection &no_gc, const SharedStringAccessGuardIfNeeded &access_guard) const
const uint8_t * AddressOfCharacterAt (uint32_t start_index, const DisallowGarbageCollection &no_gc)
uint32_t length () const
uint32_t length (AcquireLoadTag) const
void set_length (uint32_t hash)
void set_length (uint32_t hash, ReleaseStoreTag)
bool IsOneByteRepresentation () const
bool IsTwoByteRepresentation () const
void Set (uint32_t index, uint16_t value)
uint16_t Get (uint32_t index) const
uint16_t Get (uint32_t index, Isolate *isolate) const
uint16_t Get (uint32_t index, LocalIsolate *local_isolate) const
uint16_t Get (uint32_t index, const SharedStringAccessGuardIfNeeded &access_guard) const
template<template< typename > typename HandleType>
requires (std::is_convertible_v< HandleType< String >, DirectHandle< String >>) static HandleType< Number > ToNumber(Isolate *isolate
template<typename T , template< typename > typename HandleType>
requires (std::is_convertible_v< HandleType< T >, DirectHandle< String >>) static inline HandleType< String > Flatten(Isolate *isolate
template<typename T , template< typename > typename HandleType>
requires (std::is_convertible_v< HandleType< T >, DirectHandle< String >>) static inline HandleType< String > Flatten(LocalIsolate *isolate
V8_EXPORT_PRIVATE FlatContent GetFlatContent (const DisallowGarbageCollection &no_gc)
V8_EXPORT_PRIVATE FlatContent GetFlatContent (const DisallowGarbageCollection &no_gc, const SharedStringAccessGuardIfNeeded &)
Tagged< String > GetUnderlying () const
template<typename T , template< typename > typename HandleType>
requires (std::is_convertible_v< HandleType< T >, DirectHandle< String >>) static inline HandleType< String > Share(Isolate *isolate
bool Equals (Tagged< String > other) const
template<EqualityType kEqType = EqualityType::kWholeString, typename Char >
bool IsEqualTo (base::Vector< const Char > str, Isolate *isolate) const
template<EqualityType kEqType = EqualityType::kWholeString>
bool IsEqualTo (std::string_view str, Isolate *isolate) const
template<EqualityType kEqType = EqualityType::kWholeString, typename Char >
bool IsEqualTo (base::Vector< const Char > str) const
template<EqualityType kEqType = EqualityType::kWholeString, typename Char >
bool IsEqualTo (base::Vector< const Char > str, LocalIsolate *isolate) const
V8_EXPORT_PRIVATE bool HasOneBytePrefix (base::Vector< const char > str)
V8_EXPORT_PRIVATE bool IsOneByteEqualTo (base::Vector< const char > str)
std::unique_ptr< char[]> ToCString (uint32_t offset, uint32_t length, size_t *length_output=nullptr)
V8_EXPORT_PRIVATE std::unique_ptr< char[]> ToCString (size_t *length_output=nullptr)
V8_EXPORT_PRIVATE std::string ToStdString ()
template<typename T >
bool MarkForExternalizationDuringGC (Isolate *isolate, T *resource)
template<typename T >
void MakeExternalDuringGC (Isolate *isolate, T *resource)
V8_EXPORT_PRIVATE bool MakeExternal (Isolate *isolate, v8::String::ExternalStringResource *resource)
V8_EXPORT_PRIVATE bool MakeExternal (Isolate *isolate, v8::String::ExternalOneByteStringResource *resource)
bool SupportsExternalization (v8::String::Encoding)
bool AsArrayIndex (uint32_t *index)
bool AsIntegerIndex (size_t *index)
V8_EXPORT_PRIVATE void PrintOn (FILE *out)
V8_EXPORT_PRIVATE void PrintOn (std::ostream &out)
const char * PrefixForDebugPrint () const
const char * SuffixForDebugPrint () const
void StringShortPrint (StringStream *accumulator)
void PrintUC16 (std::ostream &os, int start=0, int end=-1)
void PrintUC16 (StringStream *accumulator, int start, int end)
bool IsFlat () const
bool IsShared () const
template<typename TDispatcher >
auto DispatchToSpecificType (TDispatcher &&dispatcher) const
template<typename Char >
bool IsConsStringEqualToImpl (Tagged< ConsString > string, base::Vector< const Char > str, const SharedStringAccessGuardIfNeeded &access_guard)
template<> base::Vector< const uint8_t > GetCharVector (const DisallowGarbageCollection &no_gc)
Static Public Member Functions
static bool IsOneByteRepresentationUnderneath (Tagged< String > string)
static V8_WARN_UNUSED_RESULT ComparisonResult Compare (Isolate *isolate, DirectHandle< String > x, DirectHandle< String > y)
static Tagged< Object > IndexOf (Isolate *isolate, DirectHandle< Object > receiver, DirectHandle< Object > search, DirectHandle< Object > position)
static int IndexOf (Isolate *isolate, DirectHandle< String > receiver, DirectHandle< String > search, uint32_t start_index)
static Tagged< Object > LastIndexOf (Isolate *isolate, DirectHandle< Object > receiver, DirectHandle< Object > search, DirectHandle< Object > position)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > GetSubstitution (Isolate *isolate, Match *match, DirectHandle< String > replacement, uint32_t start_index=0)
static bool Equals (Isolate *isolate, DirectHandle< String > one, DirectHandle< String > two)
static bool IsIdentifier (Isolate *isolate, DirectHandle< String > str)
static int32_t ToArrayIndex (Address addr)
template<typename SinkCharT >
static void WriteToFlat (Tagged< String > source, SinkCharT *sink, uint32_t start, uint32_t length)
template<typename SinkCharT >
static void WriteToFlat (Tagged< String > source, SinkCharT *sink, uint32_t start, uint32_t length, const SharedStringAccessGuardIfNeeded &access_guard)
template<typename SinkCharT >
static void WriteToFlat2 (SinkCharT *dst, Tagged< ConsString > src, uint32_t src_index, uint32_t length, const SharedStringAccessGuardIfNeeded &aguard, const DisallowGarbageCollection &no_gc)
static size_t Utf8Length (Isolate *isolate, DirectHandle< String > string)
static size_t WriteUtf8 (Isolate *isolate, DirectHandle< String > string, char *buffer, size_t capacity, Utf8EncodingFlags flags, size_t *processed_characters_return=nullptr)
static bool IsWellFormedUnicode (Isolate *isolate, DirectHandle< String > string)
static bool IsAscii (const char *chars, uint32_t length)
static bool IsAscii (const uint8_t *chars, uint32_t length)
static bool DoesNotContainEscapeCharacters (Tagged< String > string)
static uint32_t NonOneByteStart (const base::uc16 *chars, uint32_t length)
static bool IsOneByte (const base::uc16 *chars, uint32_t length)
template<class Visitor >
static Tagged< ConsString > VisitFlat (Visitor *visitor, Tagged< String > string, int offset=0)
template<class Visitor >
static Tagged< ConsString > VisitFlat (Visitor *visitor, Tagged< String > string, int offset, const SharedStringAccessGuardIfNeeded &access_guard)
template<typename IsolateT >
static LineEndsVector CalculateLineEndsVector (IsolateT *isolate, DirectHandle< String > string, bool include_ending_line)
template<typename IsolateT >
static Handle< FixedArray > CalculateLineEnds (IsolateT *isolate, DirectHandle< String > string, bool include_ending_line)
static bool IsInPlaceInternalizable (Tagged< String > string)
static bool IsInPlaceInternalizable (InstanceType instance_type)
static bool IsInPlaceInternalizableExcludingExternal (InstanceType instance_type)
template<typename TDispatcher , typename... TArgs>
static auto DispatchToSpecificTypeWithoutCast (InstanceType instance_type, TArgs &&... args)
Public Attributes
V8_OBJECT_INNER_CLASS class v8::internal::String::FlatContent V8_OBJECT_INNER_CLASS_END
HandleType< String > subject
HandleType< T > string
HandleType< T > AllocationType allocation = AllocationType::kYoung)
uint32_t length_
Static Public Attributes
static const int32_t kMaxOneByteCharCode = unibrow::Latin1::kMaxChar
static const uint32_t kMaxOneByteCharCodeU = unibrow::Latin1::kMaxChar
static const int kMaxUtf16CodeUnit = 0xffff
static const uint32_t kMaxUtf16CodeUnitU = kMaxUtf16CodeUnit
static const base::uc32 kMaxCodePoint = 0x10ffff
static const uint32_t kMaxLength = v8::String::kMaxLength
static const uint32_t kMaxHashCalcLength = 16383
static const uint32_t kMaxShortPrintLength = 1024
static constexpr uint32_t kInlineLineEndsSize = 32
Private Member Functions
uint16_t GetImpl (uint32_t index, const SharedStringAccessGuardIfNeeded &access_guard) const
template<EqualityType kEqType, typename Char >
bool IsEqualToImpl (base::Vector< const Char > str, const SharedStringAccessGuardIfNeeded &access_guard) const
template<template< typename > typename HandleType>
requires (std::is_convertible_v< HandleType< String >, DirectHandle< String >>) V8_EXPORT_PRIVATE inline static HandleType< String > SlowFlatten(Isolate *isolate
V8_EXPORT_PRIVATE FlatContent SlowGetFlatContent (const DisallowGarbageCollection &no_gc, const SharedStringAccessGuardIfNeeded &)
template<template< typename > typename HandleType>
requires (std::is_convertible_v< HandleType< String >, DirectHandle< String >>) EXPORT_TEMPLATE_DECLARE(V8_EXPORT_PRIVATE) static HandleType< String > SlowShare(Isolate *isolate
V8_EXPORT_PRIVATE bool SlowEquals (Tagged< String > other) const
V8_EXPORT_PRIVATE bool SlowEquals (Tagged< String > other, const SharedStringAccessGuardIfNeeded &) const
V8_EXPORT_PRIVATE bool SlowAsArrayIndex (uint32_t *index)
V8_EXPORT_PRIVATE bool SlowAsIntegerIndex (size_t *index)
V8_EXPORT_PRIVATE uint32_t ComputeAndSetRawHash ()
V8_EXPORT_PRIVATE uint32_t ComputeAndSetRawHash (const SharedStringAccessGuardIfNeeded &)
Static Private Member Functions
template<typename Char >
static V8_NOINLINE bool IsConsStringEqualToImpl (Tagged< ConsString > string, base::Vector< const Char > str, const SharedStringAccessGuardIfNeeded &access_guard)
static V8_EXPORT_PRIVATE std::optional< FlatContent > TryGetFlatContentFromDirectString (const DisallowGarbageCollection &no_gc, Tagged< String > string, uint32_t offset, uint32_t length, const SharedStringAccessGuardIfNeeded &)
static V8_EXPORT_PRIVATE bool SlowEquals (Isolate *isolate, DirectHandle< String > one, DirectHandle< String > two)
Private Attributes
HandleType< ConsString > cons
HandleType< ConsString > AllocationType allocation
HandleType< String > source
Friends
class Name
class CodeStubAssembler
class StringTableInsertionKey
class SharedStringTableInsertionKey
class SandboxTesting
class InternalizedStringKey
struct OffsetsForDebug
class Accessors
class StringBuiltinsAssembler
class maglev::MaglevAssembler
class maglev::MaglevGraphBuilder
class compiler::AccessBuilder
class wasm::baseline::LiftoffCompiler
class TorqueGeneratedStringAsserts
Detailed Description
Definition at line 118 of file string.h.
Member Typedef Documentation
LineEndsVector
using v8::internal::String::LineEndsVector = base::SmallVector<int32_t, kInlineLineEndsSize>
Definition at line 661 of file string.h.
Utf8EncodingFlags
using v8::internal::String::Utf8EncodingFlags = base::Flags<Utf8EncodingFlag>
Definition at line 582 of file string.h.
Member Enumeration Documentation
Encoding
enum v8::internal::String::Encoding
Enumerator
ONE_BYTE_ENCODING
TWO_BYTE_ENCODING
Definition at line 120 of file string.h.
{ ONE_BYTE_ENCODING, TWO_BYTE_ENCODING };
EqualityType
enum v8::internal::String::EqualityType [strong]
Enumerator
kWholeString
kPrefix
kNoLengthCheck
Definition at line 397 of file string.h.
{ kWholeString, kPrefix, kNoLengthCheck };
TrimMode
enum v8::internal::String::TrimMode
Enumerator
kTrim
kTrimStart
kTrimEnd
Definition at line 483 of file string.h.
{ kTrim, kTrimStart, kTrimEnd };
Utf8EncodingFlag
enum v8::internal::String::Utf8EncodingFlag [strong]
Enumerator
kNoFlags
kNullTerminate
kReplaceInvalid
Definition at line 577 of file string.h.
                              {
    kNoFlags = 0,
    kNullTerminate = 1u << 0,
    kReplaceInvalid = 1u << 1,
  };
Member Function Documentation
AddressOfCharacterAt()
const uint8_t * v8::internal::String::AddressOfCharacterAt (uint32_t start_index, const DisallowGarbageCollection & no_gc)
Definition at line 2224 of file string.cc.
                                                                  {
  DCHECK(IsFlat());
  Tagged<String> subject = this;
  StringShape shape(subject);
  if (shape.IsCons()) {
    subject = Cast<ConsString>(subject)->first();
    shape = StringShape(subject);
  } else if (shape.IsSliced()) {
    start_index += Cast<SlicedString>(subject)->offset();
    subject = Cast<SlicedString>(subject)->parent();
    shape = StringShape(subject);
  }
  if (shape.IsThin()) {
    subject = Cast<ThinString>(subject)->actual();
    shape = StringShape(subject);
  }
  CHECK_LE(0, start_index);
  CHECK_LE(start_index, subject->length());
  return shape.DispatchToSpecificType(
      subject, absl::Overload{
                   [&](Tagged<SeqOneByteString> s) {
                     return reinterpret_cast<const uint8_t*>(
                         s->GetChars(no_gc) + start_index);
                   },
                   [&](Tagged<SeqTwoByteString> s) {
                     return reinterpret_cast<const uint8_t*>(
                         s->GetChars(no_gc) + start_index);
                   },
                   [&](Tagged<ExternalOneByteString> s) {
                     return reinterpret_cast<const uint8_t*>(s->GetChars() +
                                                             start_index);
                   },
                   [&](Tagged<ExternalTwoByteString> s) {
                     return reinterpret_cast<const uint8_t*>(s->GetChars() +
                                                             start_index);
                   },
                   [&](Tagged<String> s) -> const uint8_t* { UNREACHABLE(); }});
}
References CHECK_LE, v8::internal::DCHECK(), v8::internal::StringShape::DispatchToSpecificType(), v8::internal::StringShape::IsCons(), IsFlat(), v8::internal::StringShape::IsSliced(), v8::internal::StringShape::IsThin(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, subject, and v8::internal::UNREACHABLE().
AsArrayIndex()
bool v8::internal::String::AsArrayIndex (uint32_t * index) [inline]
Definition at line 1767 of file string-inl.h.
                                         {
  DisallowGarbageCollection no_gc;
  uint32_t field = raw_hash_field();
  if (ContainsCachedArrayIndex(field)) {
    *index = ArrayIndexValueBits::decode(field);
    return true;
  }
  if (IsHashFieldComputed(field) && !IsIntegerIndex(field)) {
    return false;
  }
  return SlowAsArrayIndex(index);
}
References v8::internal::Name::ContainsCachedArrayIndex(), v8::base::BitField< T, shift, size, U >::decode(), v8::internal::index, v8::internal::Name::IsHashFieldComputed(), v8::internal::Name::IsIntegerIndex(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Name::raw_hash_field(), and SlowAsArrayIndex().
AsIntegerIndex()
bool v8::internal::String::AsIntegerIndex (size_t * index) [inline]
Definition at line 1780 of file string-inl.h.
                                         {
  uint32_t field = raw_hash_field();
  if (ContainsCachedArrayIndex(field)) {
    *index = ArrayIndexValueBits::decode(field);
    return true;
  }
  if (IsHashFieldComputed(field) && !IsIntegerIndex(field)) {
    return false;
  }
  return SlowAsIntegerIndex(index);
}
References v8::internal::Name::ContainsCachedArrayIndex(), v8::base::BitField< T, shift, size, U >::decode(), v8::internal::index, v8::internal::Name::IsHashFieldComputed(), v8::internal::Name::IsIntegerIndex(), v8::internal::Name::raw_hash_field(), and SlowAsIntegerIndex().
CalculateLineEnds()
template<typename IsolateT >
template Handle< FixedArray > v8::internal::String::CalculateLineEnds (IsolateT * isolate, DirectHandle< String > string, bool include_ending_line) [static]
Definition at line 1193 of file string.cc.
                                                                       {
  LineEndsVector line_ends =
      CalculateLineEndsVector(isolate, src, include_ending_line);
  int line_count = static_cast<int>(line_ends.size());
  Handle<FixedArray> array =
      isolate->factory()->NewFixedArray(line_count, AllocationType::kOld);
  {
    DisallowGarbageCollection no_gc;
    Tagged<FixedArray> raw_array = *array;
    for (int i = 0; i < line_count; i++) {
      raw_array->set(i, Smi::FromInt(line_ends[i]));
    }
  }
  return array;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::base::SmallVector< T, kSize, Allocator >::size().
Referenced by v8::internal::Script::InitLineEndsInternal().
CalculateLineEndsVector()
template<typename IsolateT >
template String::LineEndsVector v8::internal::String::CalculateLineEndsVector (IsolateT * isolate, DirectHandle< String > string, bool include_ending_line) [static]
Definition at line 1163 of file string.cc.
                                                                           {
  src = Flatten(isolate, src);
  // Rough estimate of line count based on a roughly estimated average
  // length of packed code. Most scripts have < 32 lines.
  int line_count_estimate = (src->length() >> 6) + 16;
  LineEndsVector line_ends;
  line_ends.reserve(line_count_estimate);
  {
    DisallowGarbageCollection no_gc;
    // Dispatch on type of strings.
    String::FlatContent content = src->GetFlatContent(no_gc);
    DCHECK(content.IsFlat());
    if (content.IsOneByte()) {
      CalculateLineEndsImpl(&line_ends, content.ToOneByteVector(),
                            include_ending_line);
    } else {
      CalculateLineEndsImpl(&line_ends, content.ToUC16Vector(),
                            include_ending_line);
    }
  }
  return line_ends;
}
References v8::internal::CalculateLineEndsImpl(), DCHECK, v8::internal::String::FlatContent::IsFlat(), v8::internal::String::FlatContent::IsOneByte(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::SmallVector< T, kSize, Allocator >::reserve(), v8::internal::String::FlatContent::ToOneByteVector(), and v8::internal::String::FlatContent::ToUC16Vector().
Referenced by v8::internal::Script::GetLineEnds().
Compare()
ComparisonResult v8::internal::String::Compare (Isolate * isolate, DirectHandle< String > x, DirectHandle< String > y) [static]
Definition at line 1348 of file string.cc.
                                                         {
  // A few fast case tests before we flatten.
  if (x.is_identical_to(y)) {
    return ComparisonResult::kEqual;
  } else if (y->length() == 0) {
    return x->length() == 0 ? ComparisonResult::kEqual
                            : ComparisonResult::kGreaterThan;
  } else if (x->length() == 0) {
    return ComparisonResult::kLessThan;
  }
  int const d = x->Get(0) - y->Get(0);
  if (d < 0) {
    return ComparisonResult::kLessThan;
  } else if (d > 0) {
    return ComparisonResult::kGreaterThan;
  }
  // Slow case.
  x = String::Flatten(isolate, x);
  y = String::Flatten(isolate, y);
  DisallowGarbageCollection no_gc;
  ComparisonResult result = ComparisonResult::kEqual;
  uint32_t prefix_length = x->length();
  if (y->length() < prefix_length) {
    prefix_length = y->length();
    result = ComparisonResult::kGreaterThan;
  } else if (y->length() > prefix_length) {
    result = ComparisonResult::kLessThan;
  }
  int r;
  String::FlatContent x_content = x->GetFlatContent(no_gc);
  String::FlatContent y_content = y->GetFlatContent(no_gc);
  if (x_content.IsOneByte()) {
    base::Vector<const uint8_t> x_chars = x_content.ToOneByteVector();
    if (y_content.IsOneByte()) {
      base::Vector<const uint8_t> y_chars = y_content.ToOneByteVector();
      r = CompareChars(x_chars.begin(), y_chars.begin(), prefix_length);
    } else {
      base::Vector<const base::uc16> y_chars = y_content.ToUC16Vector();
      r = CompareChars(x_chars.begin(), y_chars.begin(), prefix_length);
    }
  } else {
    base::Vector<const base::uc16> x_chars = x_content.ToUC16Vector();
    if (y_content.IsOneByte()) {
      base::Vector<const uint8_t> y_chars = y_content.ToOneByteVector();
      r = CompareChars(x_chars.begin(), y_chars.begin(), prefix_length);
    } else {
      base::Vector<const base::uc16> y_chars = y_content.ToUC16Vector();
      r = CompareChars(x_chars.begin(), y_chars.begin(), prefix_length);
    }
  }
  if (r < 0) {
    result = ComparisonResult::kLessThan;
  } else if (r > 0) {
    result = ComparisonResult::kGreaterThan;
  }
  return result;
}
References v8::base::Vector< T >::begin(), v8::internal::CompareChars(), v8::internal::DirectHandle< T >::is_identical_to(), v8::internal::String::FlatContent::IsOneByte(), v8::internal::kEqual, v8::internal::kGreaterThan, v8::internal::kLessThan, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, v8::internal::String::FlatContent::ToOneByteVector(), v8::internal::String::FlatContent::ToUC16Vector(), and v8::base::internal::y.
Referenced by v8::internal::Object::Compare(), and v8::internal::RUNTIME_FUNCTION().
ComputeAndSetRawHash() [1/2]
uint32_t v8::internal::String::ComputeAndSetRawHash () [private]
Definition at line 1822 of file string.cc.
                                      {
  DCHECK(!SharedStringAccessGuardIfNeeded::IsNeeded(this));
  return ComputeAndSetRawHash(SharedStringAccessGuardIfNeeded::NotNeeded());
}
References DCHECK.
ComputeAndSetRawHash() [2/2]
uint32_t v8::internal::String::ComputeAndSetRawHash (const SharedStringAccessGuardIfNeeded & access_guard) [private]
Definition at line 1827 of file string.cc.
                                                         {
  DisallowGarbageCollection no_gc;
  // Should only be called if hash code has not yet been computed.
  //
  // If in-place internalizable strings are shared, there may be calls to
  // ComputeAndSetRawHash in parallel. Since only flat strings are in-place
  // internalizable and their contents do not change, the result hash is the
  // same. The raw hash field is stored with relaxed ordering.
  DCHECK_IMPLIES(!v8_flags.shared_string_table, !HasHashCode());
  // Store the hash code in the object.
  uint64_t seed = HashSeed(EarlyGetReadOnlyRoots());
  size_t start = 0;
  Tagged<String> string = this;
  StringShape shape(string);
  if (shape.IsSliced()) {
    Tagged<SlicedString> sliced = Cast<SlicedString>(string);
    start = sliced->offset();
    string = sliced->parent();
    shape = StringShape(string);
  }
  if (shape.IsCons() && string->IsFlat()) {
    string = Cast<ConsString>(string)->first();
    shape = StringShape(string);
  }
  if (shape.IsThin()) {
    string = Cast<ThinString>(string)->actual();
    shape = StringShape(string);
    if (length() == string->length()) {
      uint32_t raw_hash = string->RawHash();
      DCHECK(IsHashFieldComputed(raw_hash));
      set_raw_hash_field(raw_hash);
      return raw_hash;
    }
  }
  uint32_t raw_hash_field =
      shape.IsOneByte()
          ? HashString<uint8_t>(string, start, length(), seed, access_guard)
          : HashString<uint16_t>(string, start, length(), seed, access_guard);
  set_raw_hash_field_if_empty(raw_hash_field);
  // Check the hash code is there (or a forwarding index if the string was
  // internalized/externalized in parallel).
  DCHECK(HasHashCode() || HasForwardingIndex(kAcquireLoad));
  // Ensure that the hash value of 0 is never computed.
  DCHECK_NE(HashBits::decode(raw_hash_field), 0);
  return raw_hash_field;
}
References DCHECK, DCHECK_IMPLIES, DCHECK_NE, v8::internal::HashSeed(), v8::internal::StringShape::IsCons(), v8::internal::StringShape::IsOneByte(), v8::internal::StringShape::IsSliced(), v8::internal::StringShape::IsThin(), v8::kAcquireLoad, v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::string, and v8::internal::v8_flags.
DispatchToSpecificType()
template<typename TDispatcher >
auto v8::internal::String::DispatchToSpecificType (TDispatcher && dispatcher) const [inline]
Definition at line 507 of file string-inl.h.
                                                                            {
  return StringShape(Tagged(this))
      .DispatchToSpecificType(Tagged(this),
                              std::forward<TDispatcher>(dispatcher));
}
References v8::internal::StringShape::DispatchToSpecificType(), and v8::internal::Tagged().
Referenced by GetImpl().
DispatchToSpecificTypeWithoutCast()
template<typename TDispatcher , typename... TArgs>
auto v8::internal::String::DispatchToSpecificTypeWithoutCast (InstanceType instance_type, TArgs &&... args) [inline], [static]
Definition at line 469 of file string-inl.h.
                                                 {
  switch (instance_type & kStringRepresentationAndEncodingMask) {
    case kSeqStringTag | kOneByteStringTag:
      return TDispatcher::HandleSeqOneByteString(std::forward<TArgs>(args)...);
    case kSeqStringTag | kTwoByteStringTag:
      return TDispatcher::HandleSeqTwoByteString(std::forward<TArgs>(args)...);
    case kConsStringTag | kOneByteStringTag:
    case kConsStringTag | kTwoByteStringTag:
      return TDispatcher::HandleConsString(std::forward<TArgs>(args)...);
    case kExternalStringTag | kOneByteStringTag:
      return TDispatcher::HandleExternalOneByteString(
          std::forward<TArgs>(args)...);
    case kExternalStringTag | kTwoByteStringTag:
      return TDispatcher::HandleExternalTwoByteString(
          std::forward<TArgs>(args)...);
    case kSlicedStringTag | kOneByteStringTag:
    case kSlicedStringTag | kTwoByteStringTag:
      return TDispatcher::HandleSlicedString(std::forward<TArgs>(args)...);
    case kThinStringTag | kOneByteStringTag:
    case kThinStringTag | kTwoByteStringTag:
      return TDispatcher::HandleThinString(std::forward<TArgs>(args)...);
    default:
      return TDispatcher::HandleInvalidString(std::forward<TArgs>(args)...);
  }
}
References v8::base::args, v8::internal::kConsStringTag, v8::internal::kExternalStringTag, v8::internal::kOneByteStringTag, v8::internal::kSeqStringTag, v8::internal::kSlicedStringTag, v8::internal::kStringRepresentationAndEncodingMask, v8::internal::kThinStringTag, and v8::internal::kTwoByteStringTag.
DoesNotContainEscapeCharacters()
bool v8::internal::String::DoesNotContainEscapeCharacters (Tagged< String > string) [static]
Definition at line 1127 of file string.cc.
                                                                 {
  // This method is not optimized. It is only meant to be used in verification
  // code.
  bool requires_escape = false;
  StringCharacterStream stream(string);
  while (stream.HasMore() && !requires_escape) {
    uint16_t c = stream.GetNext();
    requires_escape =
        c < 0x20 || c == 0x22 || c == 0x5c || (c >= 0xD800 && c <= 0xDFFF);
  }
  return !requires_escape;
}
References v8::internal::StringCharacterStream::GetNext(), and v8::internal::StringCharacterStream::HasMore().
Referenced by v8::internal::FastJsonStringifier< Char >::SerializeObjectKey().
Equals() [1/2]
bool v8::internal::String::Equals (Isolate * isolate, DirectHandle< String > one, DirectHandle< String > two) [inline], [static]
Definition at line 693 of file string-inl.h.
                                              {
  if (one.is_identical_to(two)) return true;
  if (IsInternalizedString(*one) && IsInternalizedString(*two)) {
    return false;
  }
  return SlowEquals(isolate, one, two);
}
References v8::internal::InstanceTypeChecker::IsInternalizedString(), one, and SlowEquals().
Equals() [2/2]
bool v8::internal::String::Equals (Tagged< String > other) const [inline]
Definition at line 684 of file string-inl.h.
                                              {
  if (other == this) return true;
  if (IsInternalizedString(this) && IsInternalizedString(other)) {
    return false;
  }
  return SlowEquals(other);
}
References v8::internal::InstanceTypeChecker::IsInternalizedString(), and SlowEquals().
Referenced by v8::internal::anonymous_namespace{call-site-info.cc}::AppendMethodCall(), v8::internal::BUILTIN(), v8::internal::Object::Equals(), v8::internal::GetStringOrBooleanOption(), v8::internal::temporal::GetTemporalFractionalSecondDigitsOption(), v8::internal::Intl::Normalize(), v8::internal::wasm::InstanceBuilder::ProcessExports(), v8::internal::RUNTIME_FUNCTION(), v8::internal::ScopeIterator::SetLocalVariableValue(), and v8::internal::anonymous_namespace{call-site-info.cc}::StringEndsWithMethodName().
Get() [1/4]
uint16_t v8::internal::String::Get (uint32_t index) const [inline]
Definition at line 1098 of file string-inl.h.
                                         {
  DCHECK(!SharedStringAccessGuardIfNeeded::IsNeeded(this));
  return GetImpl(index, SharedStringAccessGuardIfNeeded::NotNeeded());
}
References v8::internal::DCHECK(), GetImpl(), v8::internal::index, v8::internal::SharedStringAccessGuardIfNeeded::IsNeeded(), and v8::internal::SharedStringAccessGuardIfNeeded::NotNeeded().
Referenced by v8::internal::SeqOneByteString::Get().
Get() [2/4]
uint16_t v8::internal::String::Get (uint32_t index, const SharedStringAccessGuardIfNeeded & access_guard) const [inline]
Definition at line 1113 of file string-inl.h.
                                                                               {
  return GetImpl(index, access_guard);
}
References GetImpl(), and v8::internal::index.
Get() [3/4]
uint16_t v8::internal::String::Get (uint32_t index, Isolate * isolate) const [inline]
Definition at line 1103 of file string-inl.h.
                                                           {
  SharedStringAccessGuardIfNeeded scope(isolate);
  return GetImpl(index, scope);
}
References GetImpl(), and v8::internal::index.
Get() [4/4]
uint16_t v8::internal::String::Get (uint32_t index, LocalIsolate * local_isolate) const [inline]
Definition at line 1108 of file string-inl.h.
                                                                      {
  SharedStringAccessGuardIfNeeded scope(local_isolate);
  return GetImpl(index, scope);
}
References GetImpl(), and v8::internal::index.
GetCharVector() [1/2]
template<>
base::Vector< const base::uc16 > v8::internal::String::GetCharVector (const DisallowGarbageCollection & no_gc) [inline]
Definition at line 1255 of file string-inl.h.
                                            {
  String::FlatContent flat = GetFlatContent(no_gc);
  DCHECK(flat.IsOneByte());
  return flat.ToOneByteVector();
}
References v8::internal::DCHECK(), GetFlatContent(), v8::internal::String::FlatContent::IsOneByte(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::String::FlatContent::ToOneByteVector().
GetCharVector() [2/2]
template<typename Char >
base::Vector<const Char> v8::internal::String::GetCharVector (const DisallowGarbageCollection & no_gc) [inline]
GetDirectStringChars() [1/2]
template<typename Char >
const Char * v8::internal::String::GetDirectStringChars (const DisallowGarbageCollection & no_gc) const [inline]
Definition at line 826 of file string-inl.h.
                                                  {
  DCHECK(!SharedStringAccessGuardIfNeeded::IsNeeded(this));
  DCHECK(StringShape(this).IsDirect());
  return StringShape(this).IsExternal()
             ? Cast<typename CharTraits<Char>::ExternalString>(this).GetChars()
             : Cast<typename CharTraits<Char>::String>(this).GetChars(no_gc);
}
References v8::internal::DCHECK(), v8::internal::StringShape::IsExternal(), v8::internal::SharedStringAccessGuardIfNeeded::IsNeeded(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
GetDirectStringChars() [2/2]
template<typename Char >
const Char * v8::internal::String::GetDirectStringChars (const DisallowGarbageCollection & no_gc, const SharedStringAccessGuardIfNeeded & access_guard) const [inline]
Definition at line 836 of file string-inl.h.
                                                               {
  DCHECK(StringShape(this).IsDirect());
  return StringShape(this).IsExternal()
             ? Cast<typename CharTraits<Char>::ExternalString>(this)->GetChars()
             : Cast<typename CharTraits<Char>::String>(this)->GetChars(
                   no_gc, access_guard);
}
References v8::internal::DCHECK(), v8::internal::StringShape::IsExternal(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
GetFlatContent() [1/2]
String::FlatContent v8::internal::String::GetFlatContent (const DisallowGarbageCollection & no_gc) [inline]
Definition at line 1019 of file string-inl.h.
                                            {
  return GetFlatContent(no_gc, SharedStringAccessGuardIfNeeded::NotNeeded());
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::SharedStringAccessGuardIfNeeded::NotNeeded().
Referenced by GetCharVector().
GetFlatContent() [2/2]
String::FlatContent v8::internal::String::GetFlatContent (const DisallowGarbageCollection & no_gc, const SharedStringAccessGuardIfNeeded & access_guard) [inline]
Definition at line 1069 of file string-inl.h.
                                                         {
  std::optional<FlatContent> flat_content =
      TryGetFlatContentFromDirectString(no_gc, this, 0, length(), access_guard);
  if (flat_content.has_value()) return flat_content.value();
  return SlowGetFlatContent(no_gc, access_guard);
}
References length(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, SlowGetFlatContent(), and TryGetFlatContentFromDirectString().
GetImpl()
uint16_t v8::internal::String::GetImpl (uint32_t index, const SharedStringAccessGuardIfNeeded & access_guard) const [inline], [private]
Definition at line 1118 of file string-inl.h.
                                                                               {
  DCHECK(index >= 0 && index < length());
  return DispatchToSpecificType(
      [&](auto str) { return str->Get(index, access_guard); });
}
References v8::internal::DCHECK(), DispatchToSpecificType(), v8::internal::index, and length().
Referenced by Get().
GetSubstitution()
MaybeDirectHandle< String > v8::internal::String::GetSubstitution (Isolate * isolate, Match * match, DirectHandle< String > replacement, uint32_t start_index = 0) [static]
Definition at line 1490 of file string.cc.
                          {
  Factory* factory = isolate->factory();
  const int replacement_length = replacement->length();
  const int captures_length = match->CaptureCount();
  replacement = String::Flatten(isolate, replacement);
  DirectHandle<String> dollar_string =
      factory->LookupSingleCharacterStringFromCode('$');
  int next_dollar_ix =
      String::IndexOf(isolate, replacement, dollar_string, start_index);
  if (next_dollar_ix < 0) {
    return replacement;
  }
  IncrementalStringBuilder builder(isolate);
  if (next_dollar_ix > 0) {
    builder.AppendString(factory->NewSubString(replacement, 0, next_dollar_ix));
  }
  while (true) {
    const int peek_ix = next_dollar_ix + 1;
    if (peek_ix >= replacement_length) {
      builder.AppendCharacter('$');
      return builder.Finish();
    }
    int continue_from_ix = -1;
    const uint16_t peek = replacement->Get(peek_ix);
    switch (peek) {
      case '$': // $$
        builder.AppendCharacter('$');
        continue_from_ix = peek_ix + 1;
        break;
      case '&': // $& - match
        builder.AppendString(match->GetMatch());
        continue_from_ix = peek_ix + 1;
        break;
      case '`': // $` - prefix
        builder.AppendString(match->GetPrefix());
        continue_from_ix = peek_ix + 1;
        break;
      case '\'': // $' - suffix
        builder.AppendString(match->GetSuffix());
        continue_from_ix = peek_ix + 1;
        break;
      case '0':
      case '1':
      case '2':
      case '3':
      case '4':
      case '5':
      case '6':
      case '7':
      case '8':
      case '9': {
        // Valid indices are $1 .. $9, $01 .. $09 and $10 .. $99
        int scaled_index = (peek - '0');
        int advance = 1;
        if (peek_ix + 1 < replacement_length) {
          const uint16_t next_peek = replacement->Get(peek_ix + 1);
          if (next_peek >= '0' && next_peek <= '9') {
            const int new_scaled_index = scaled_index * 10 + (next_peek - '0');
            if (new_scaled_index < captures_length) {
              scaled_index = new_scaled_index;
              advance = 2;
            }
          }
        }
        if (scaled_index == 0 || scaled_index >= captures_length) {
          builder.AppendCharacter('$');
          continue_from_ix = peek_ix;
          break;
        }
        bool capture_exists;
        DirectHandle<String> capture;
        ASSIGN_RETURN_ON_EXCEPTION(
            isolate, capture, match->GetCapture(scaled_index, &capture_exists));
        if (capture_exists) builder.AppendString(capture);
        continue_from_ix = peek_ix + advance;
        break;
      }
      case '<': { // $<name> - named capture
        using CaptureState = String::Match::CaptureState;
        if (!match->HasNamedCaptures()) {
          builder.AppendCharacter('$');
          continue_from_ix = peek_ix;
          break;
        }
        DirectHandle<String> bracket_string =
            factory->LookupSingleCharacterStringFromCode('>');
        const int closing_bracket_ix =
            String::IndexOf(isolate, replacement, bracket_string, peek_ix + 1);
        if (closing_bracket_ix == -1) {
          // No closing bracket was found, treat '$<' as a string literal.
          builder.AppendCharacter('$');
          continue_from_ix = peek_ix;
          break;
        }
        DirectHandle<String> capture_name =
            factory->NewSubString(replacement, peek_ix + 1, closing_bracket_ix);
        DirectHandle<String> capture;
        CaptureState capture_state;
        ASSIGN_RETURN_ON_EXCEPTION(
            isolate, capture,
            match->GetNamedCapture(capture_name, &capture_state));
        if (capture_state == CaptureState::MATCHED) {
          builder.AppendString(capture);
        }
        continue_from_ix = closing_bracket_ix + 1;
        break;
      }
      default:
        builder.AppendCharacter('$');
        continue_from_ix = peek_ix;
        break;
    }
    // Go the the next $ in the replacement.
    // TODO(jgruber): Single-char lookups could be much more efficient.
    DCHECK_NE(continue_from_ix, -1);
    next_dollar_ix =
        String::IndexOf(isolate, replacement, dollar_string, continue_from_ix);
    // Return if there are no more $ characters in the replacement. If we
    // haven't reached the end, we need to append the suffix.
    if (next_dollar_ix < 0) {
      if (continue_from_ix < replacement_length) {
        builder.AppendString(factory->NewSubString(
            replacement, continue_from_ix, replacement_length));
      }
      return builder.Finish();
    }
    // Append substring between the previous and the next $ character.
    if (next_dollar_ix > continue_from_ix) {
      builder.AppendString(
          factory->NewSubString(replacement, continue_from_ix, next_dollar_ix));
    }
  }
  UNREACHABLE();
}
References v8::internal::IncrementalStringBuilder::AppendCharacter(), v8::internal::IncrementalStringBuilder::AppendString(), ASSIGN_RETURN_ON_EXCEPTION, v8::internal::String::Match::CaptureCount(), DCHECK_NE, v8::internal::Isolate::factory(), v8::internal::IncrementalStringBuilder::Finish(), v8::internal::String::Match::GetCapture(), v8::internal::String::Match::GetMatch(), v8::internal::String::Match::GetNamedCapture(), v8::internal::String::Match::GetPrefix(), v8::internal::String::Match::GetSuffix(), v8::internal::String::Match::HasNamedCaptures(), v8::internal::FactoryBase< Impl >::LookupSingleCharacterStringFromCode(), and UNREACHABLE.
Referenced by v8::internal::anonymous_namespace{runtime-regexp.cc}::RegExpReplace(), and v8::internal::RUNTIME_FUNCTION().
GetUnderlying()
Tagged< String > v8::internal::String::GetUnderlying () const [inline]
Definition at line 1146 of file string-inl.h.
                                           {
  // Giving direct access to underlying string only makes sense if the
  // wrapping string is already flattened.
  DCHECK(IsFlat());
  DCHECK(StringShape(this).IsIndirect());
  static_assert(offsetof(ConsString, first_) ==
                offsetof(SlicedString, parent_));
  static_assert(offsetof(ConsString, first_) == offsetof(ThinString, actual_));
  return static_cast<const SlicedString*>(this)->parent();
}
References v8::internal::DCHECK(), and IsFlat().
HasOneBytePrefix()
bool v8::internal::String::HasOneBytePrefix (base::Vector< const char > str)
Definition at line 1757 of file string.cc.
                                                        {
  DCHECK(!SharedStringAccessGuardIfNeeded::IsNeeded(this));
  return IsEqualToImpl<EqualityType::kPrefix>(
      str, SharedStringAccessGuardIfNeeded::NotNeeded());
}
References DCHECK.
IndexOf() [1/2]
Tagged< Object > v8::internal::String::IndexOf (Isolate * isolate, DirectHandle< Object > receiver, DirectHandle< Object > search, DirectHandle< Object > position) [static]
Definition at line 1421 of file string.cc.
                                                              {
  if (IsNullOrUndefined(*receiver, isolate)) {
    THROW_NEW_ERROR_RETURN_FAILURE(
        isolate, NewTypeError(MessageTemplate::kCalledOnNullOrUndefined,
                              isolate->factory()->NewStringFromAsciiChecked(
                                  "String.prototype.indexOf")));
  }
  DirectHandle<String> receiver_string;
  ASSIGN_RETURN_FAILURE_ON_EXCEPTION(isolate, receiver_string,
                                     Object::ToString(isolate, receiver));
  DirectHandle<String> search_string;
  ASSIGN_RETURN_FAILURE_ON_EXCEPTION(isolate, search_string,
                                     Object::ToString(isolate, search));
  ASSIGN_RETURN_FAILURE_ON_EXCEPTION(isolate, position,
                                     Object::ToInteger(isolate, position));
  uint32_t index = ToValidIndex(*receiver_string, *position);
  return Smi::FromInt(
      String::IndexOf(isolate, receiver_string, search_string, index));
}
References ASSIGN_RETURN_FAILURE_ON_EXCEPTION, v8::internal::Isolate::factory(), v8::internal::index, v8::internal::IsNullOrUndefined(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), v8::internal::anonymous_namespace{simd.cc}::search(), THROW_NEW_ERROR_RETURN_FAILURE, ToString(), and v8::internal::anonymous_namespace{string.cc}::ToValidIndex().
Referenced by v8::internal::anonymous_namespace{builtins-console.cc}::Formatter(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::StringReplaceOneCharWithString().
IndexOf() [2/2]
int v8::internal::String::IndexOf (Isolate * isolate, DirectHandle< String > receiver, DirectHandle< String > search, uint32_t start_index) [static]
Definition at line 1461 of file string.cc.
                                                                       {
  DCHECK_LE(start_index, receiver->length());
  uint32_t search_length = search->length();
  if (search_length == 0) return start_index;
  uint32_t receiver_length = receiver->length();
  if (start_index + search_length > receiver_length) return -1;
  receiver = String::Flatten(isolate, receiver);
  search = String::Flatten(isolate, search);
  DisallowGarbageCollection no_gc; // ensure vectors stay valid
  // Extract flattened substrings of cons strings before getting encoding.
  String::FlatContent receiver_content = receiver->GetFlatContent(no_gc);
  String::FlatContent search_content = search->GetFlatContent(no_gc);
  // dispatch on type of strings
  if (search_content.IsOneByte()) {
    base::Vector<const uint8_t> pat_vector = search_content.ToOneByteVector();
    return SearchString<const uint8_t>(isolate, receiver_content, pat_vector,
                                       start_index);
  }
  base::Vector<const base::uc16> pat_vector = search_content.ToUC16Vector();
  return SearchString<const base::uc16>(isolate, receiver_content, pat_vector,
                                        start_index);
}
References DCHECK_LE, v8::internal::String::FlatContent::IsOneByte(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::anonymous_namespace{simd.cc}::search(), v8::internal::search_length, v8::internal::String::FlatContent::ToOneByteVector(), and v8::internal::String::FlatContent::ToUC16Vector().
IsAscii() [1/2]
static bool v8::internal::String::IsAscii (const char * chars, uint32_t length) [inline], [static]
Definition at line 592 of file string.h.
                                                                 {
    return simdutf::validate_ascii(chars, length);
  }
References length().
Referenced by v8::Shell::ReadFile(), v8::internal::ValueDeserializer::ReadJSObjectProperties(), and v8::internal::anonymous_namespace{intl-objects.cc}::ToICUStringPiece().
IsAscii() [2/2]
static bool v8::internal::String::IsAscii (const uint8_t * chars, uint32_t length) [inline], [static]
Definition at line 596 of file string.h.
                                                                    {
    return simdutf::validate_ascii(reinterpret_cast<const char*>(chars),
                                   length);
  }
References length().
IsConsStringEqualToImpl() [1/2]
template<typename Char >
bool v8::internal::String::IsConsStringEqualToImpl (Tagged< ConsString > string, base::Vector< const Char > str, const SharedStringAccessGuardIfNeeded & access_guard)
Definition at line 790 of file string-inl.h.
                                                         {
  // Already checked the len in IsEqualToImpl. Check GE rather than EQ in case
  // this is a prefix check.
  DCHECK_GE(string->length(), str.size());
  ConsStringIterator iter(Cast<ConsString>(string));
  base::Vector<const Char> remaining_str = str;
  int offset;
  for (Tagged<String> segment = iter.Next(&offset); !segment.is_null();
       segment = iter.Next(&offset)) {
    // We create the iterator without an offset, so we should never have a
    // per-segment offset.
    DCHECK_EQ(offset, 0);
    // Compare the individual segment against the appropriate subvector of the
    // remaining string.
    size_t len = std::min<size_t>(segment->length(), remaining_str.size());
    base::Vector<const Char> sub_str = remaining_str.SubVector(0, len);
    if (!segment->IsEqualToImpl<EqualityType::kNoLengthCheck>(sub_str,
                                                              access_guard)) {
      return false;
    }
    remaining_str += len;
    if (remaining_str.empty()) break;
  }
  DCHECK_EQ(remaining_str.data(), str.end());
  DCHECK_EQ(remaining_str.size(), 0);
  return true;
}
References v8::base::Vector< T >::data(), DCHECK_EQ, DCHECK_GE, v8::base::Vector< T >::empty(), v8::base::Vector< T >::end(), kNoLengthCheck, v8::internal::ConsStringIterator::Next(), v8::base::Vector< T >::size(), string, and v8::base::Vector< T >::SubVector().
IsConsStringEqualToImpl() [2/2]
template<typename Char >
static V8_NOINLINE bool v8::internal::String::IsConsStringEqualToImpl (Tagged< ConsString > string, base::Vector< const Char > str, const SharedStringAccessGuardIfNeeded & access_guard) [static], [private]
IsEqualTo() [1/4]
template<String::EqualityType kEqType, typename Char >
bool v8::internal::String::IsEqualTo (base::Vector< const Char > str) const [inline]
Definition at line 716 of file string-inl.h.
                                                       {
  DCHECK(!SharedStringAccessGuardIfNeeded::IsNeeded(this));
  return IsEqualToImpl<kEqType>(str,
                                SharedStringAccessGuardIfNeeded::NotNeeded());
}
References v8::internal::DCHECK(), v8::internal::SharedStringAccessGuardIfNeeded::IsNeeded(), and v8::internal::SharedStringAccessGuardIfNeeded::NotNeeded().
IsEqualTo() [2/4]
template<String::EqualityType kEqType, typename Char >
bool v8::internal::String::IsEqualTo (base::Vector< const Char > str, Isolate * isolate) const [inline]
Definition at line 703 of file string-inl.h.
                                                                         {
  DCHECK(!SharedStringAccessGuardIfNeeded::IsNeeded(this));
  return IsEqualToImpl<kEqType>(str,
                                SharedStringAccessGuardIfNeeded::NotNeeded());
}
References v8::internal::DCHECK(), v8::internal::SharedStringAccessGuardIfNeeded::IsNeeded(), and v8::internal::SharedStringAccessGuardIfNeeded::NotNeeded().
Referenced by IsOneByteEqualTo().
IsEqualTo() [3/4]
template<String::EqualityType kEqType, typename Char >
bool v8::internal::String::IsEqualTo (base::Vector< const Char > str, LocalIsolate * isolate) const [inline]
Definition at line 723 of file string-inl.h.
                                                    {
  SharedStringAccessGuardIfNeeded access_guard(isolate);
  return IsEqualToImpl<kEqType>(str, access_guard);
}
IsEqualTo() [4/4]
template<String::EqualityType kEqType>
bool v8::internal::String::IsEqualTo (std::string_view str, Isolate * isolate) const [inline]
Definition at line 710 of file string-inl.h.
                                                                 {
  return IsEqualTo<kEqType>(base::Vector<const char>(str.data(), str.size()),
                            isolate);
}
IsEqualToImpl()
template<String::EqualityType kEqType, typename Char >
bool v8::internal::String::IsEqualToImpl (base::Vector< const Char > str, const SharedStringAccessGuardIfNeeded & access_guard) const [inline], [private]
Definition at line 730 of file string-inl.h.
                                                               {
  size_t len = str.size();
  switch (kEqType) {
    case EqualityType::kWholeString:
      if (static_cast<size_t>(length()) != len) return false;
      break;
    case EqualityType::kPrefix:
      if (static_cast<size_t>(length()) < len) return false;
      break;
    case EqualityType::kNoLengthCheck:
      DCHECK_EQ(length(), len);
      break;
  }
  DisallowGarbageCollection no_gc;
  int slice_offset = 0;
  Tagged<String> string = this;
  const Char* data = str.data();
  while (true) {
    auto ret = string->DispatchToSpecificType(absl::Overload{
        [&](Tagged<SeqOneByteString> s) {
          return CompareCharsEqual(
              s->GetChars(no_gc, access_guard) + slice_offset, data, len);
        },
        [&](Tagged<SeqTwoByteString> s) {
          return CompareCharsEqual(
              s->GetChars(no_gc, access_guard) + slice_offset, data, len);
        },
        [&](Tagged<ExternalOneByteString> s) {
          return CompareCharsEqual(s->GetChars() + slice_offset, data, len);
        },
        [&](Tagged<ExternalTwoByteString> s) {
          return CompareCharsEqual(s->GetChars() + slice_offset, data, len);
        },
        [&](Tagged<SlicedString> s) {
          slice_offset += s->offset();
          string = s->parent();
          return std::nullopt;
        },
        [&](Tagged<ConsString> s) {
          // The ConsString path is more complex and rare, so call out to an
          // out-of-line handler.
          // Slices cannot refer to ConsStrings, so there cannot be a non-zero
          // slice offset here.
          DCHECK_EQ(slice_offset, 0);
          return IsConsStringEqualToImpl<Char>(s, str, access_guard);
        },
        [&](Tagged<ThinString> s) {
          string = s->actual();
          return std::nullopt;
        }});
    if (ret) return ret.value();
  }
}
References v8::internal::CompareCharsEqual(), v8::base::Vector< T >::data(), DCHECK_EQ, kNoLengthCheck, kPrefix, kWholeString, length(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::base::Vector< T >::size().
IsFlat()
bool v8::internal::String::IsFlat () const [inline]
Definition at line 1135 of file string-inl.h.
                          {
  if (!StringShape(this).IsCons()) return true;
  return Cast<ConsString>(this)->IsFlat();
}
Referenced by AddressOfCharacterAt(), and GetUnderlying().
IsIdentifier()
bool v8::internal::String::IsIdentifier (Isolate * isolate, DirectHandle< String > str) [static]
Definition at line 1784 of file string.cc.
                                                                    {
  str = String::Flatten(isolate, str);
  DisallowGarbageCollection no_gc;
  String::FlatContent flat = str->GetFlatContent(no_gc);
  return flat.IsOneByte() ? IsIdentifierVector(flat.ToOneByteVector())
                          : IsIdentifierVector(flat.ToUC16Vector());
}
References v8::internal::anonymous_namespace{string.cc}::IsIdentifierVector(), v8::internal::String::FlatContent::IsOneByte(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::String::FlatContent::ToOneByteVector(), and v8::internal::String::FlatContent::ToUC16Vector().
Referenced by v8::internal::anonymous_namespace{call-site-info.cc}::AppendMethodCall(), and v8::ScriptCompiler::CompileFunction().
IsInPlaceInternalizable() [1/2]
bool v8::internal::String::IsInPlaceInternalizable (InstanceType instance_type) [inline], [static]
Definition at line 1863 of file string-inl.h.
                                                               {
  switch (instance_type) {
    case SEQ_TWO_BYTE_STRING_TYPE:
    case SEQ_ONE_BYTE_STRING_TYPE:
    case SHARED_SEQ_TWO_BYTE_STRING_TYPE:
    case SHARED_SEQ_ONE_BYTE_STRING_TYPE:
    case EXTERNAL_TWO_BYTE_STRING_TYPE:
    case EXTERNAL_ONE_BYTE_STRING_TYPE:
    case SHARED_EXTERNAL_TWO_BYTE_STRING_TYPE:
    case SHARED_EXTERNAL_ONE_BYTE_STRING_TYPE:
      return true;
    default:
      return false;
  }
}
References v8::internal::EXTERNAL_ONE_BYTE_STRING_TYPE, v8::internal::EXTERNAL_TWO_BYTE_STRING_TYPE, v8::internal::SEQ_ONE_BYTE_STRING_TYPE, v8::internal::SEQ_TWO_BYTE_STRING_TYPE, v8::internal::SHARED_EXTERNAL_ONE_BYTE_STRING_TYPE, v8::internal::SHARED_EXTERNAL_TWO_BYTE_STRING_TYPE, v8::internal::SHARED_SEQ_ONE_BYTE_STRING_TYPE, and v8::internal::SHARED_SEQ_TWO_BYTE_STRING_TYPE.
IsInPlaceInternalizable() [2/2]
bool v8::internal::String::IsInPlaceInternalizable (Tagged< String > string) [inline], [static]
Definition at line 1858 of file string-inl.h.
                                                          {
  return IsInPlaceInternalizable(string->map()->instance_type());
}
References string.
Referenced by v8::internal::SharedHeapSerializer::CanBeInSharedOldSpace(), v8::internal::Scavenger::EvacuateInPlaceInternalizableString(), v8::internal::Scavenger::EvacuateObject(), v8::internal::FactoryBase< Impl >::GetInPlaceInternalizedStringMap(), IsInPlaceInternalizableExcludingExternal(), v8::internal::FactoryBase< Impl >::RefineAllocationTypeForInPlaceInternalizableString(), and v8::internal::RUNTIME_FUNCTION().
IsInPlaceInternalizableExcludingExternal()
bool v8::internal::String::IsInPlaceInternalizableExcludingExternal (InstanceType instance_type) [inline], [static]
Definition at line 1880 of file string-inl.h.
                                {
  return IsInPlaceInternalizable(instance_type) &&
         !InstanceTypeChecker::IsExternalString(instance_type);
}
References v8::internal::InstanceTypeChecker::IsExternalString(), and IsInPlaceInternalizable().
Referenced by v8::internal::EvacuateVisitorBase::ShouldPromoteIntoSharedHeap().
IsOneByte()
static bool v8::internal::String::IsOneByte (const base::uc16 * chars, uint32_t length) [inline], [static]
Definition at line 644 of file string.h.
                                                                       {
    return NonOneByteStart(chars, length) >= length;
  }
References length(), and NonOneByteStart().
Referenced by v8::internal::StringSearchBase::IsOneByteString(), MakeExternal(), v8::internal::Factory::NewCopiedSubstring(), and v8::internal::Factory::NewStringFromTwoByte().
IsOneByteEqualTo()
bool v8::internal::String::IsOneByteEqualTo (base::Vector< const char > str) [inline]
Definition at line 821 of file string-inl.h.
                                                        {
  return IsEqualTo(str);
}
References IsEqualTo().
IsOneByteRepresentation()
bool v8::internal::String::IsOneByteRepresentation () const [inline]
Definition at line 513 of file string-inl.h.
                                           {
  return InstanceTypeChecker::IsOneByteString(map());
}
References v8::internal::InstanceTypeChecker::IsOneByteString(), and v8::internal::HeapObjectLayout::map().
Referenced by Set().
IsOneByteRepresentationUnderneath()
bool v8::internal::String::IsOneByteRepresentationUnderneath (Tagged< String > string) [inline], [static]
Definition at line 522 of file string-inl.h.
                                                                    {
  while (true) {
    uint32_t type = string->map()->instance_type();
    static_assert(kIsIndirectStringTag != 0);
    static_assert((kIsIndirectStringMask & kStringEncodingMask) == 0);
    DCHECK(string->IsFlat());
    switch (type & (kIsIndirectStringMask | kStringEncodingMask)) {
      case kOneByteStringTag:
        return true;
      case kTwoByteStringTag:
        return false;
      default: // Cons, sliced, thin, strings need to go deeper.
        string = string->GetUnderlying();
    }
  }
}
References v8::internal::DCHECK(), v8::internal::kIsIndirectStringMask, v8::internal::kIsIndirectStringTag, v8::internal::kOneByteStringTag, v8::internal::kStringEncodingMask, v8::internal::kTwoByteStringTag, string, and v8::internal::tracing::type.
Referenced by v8::internal::JsonStringifier::AppendString(), v8::internal::JsonStringifier::AppendStringByCopy(), v8::internal::BUILTIN(), v8::internal::IncrementalStringBuilder::CanAppendByCopy(), v8::internal::NativeRegExpMacroAssembler::CheckStackGuardState(), v8::internal::anonymous_namespace{builtins-string.cc}::ConvertCase(), v8::internal::JSRawJson::Create(), v8::internal::Uri::Escape(), v8::internal::anonymous_namespace{js-regexp.cc}::EscapeRegExpSource(), v8::internal::NativeRegExpMacroAssembler::Execute(), v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::HandleInterrupts(), v8::internal::anonymous_namespace{regexp-interpreter.cc}::HandleInterrupts(), v8::internal::RegExpImpl::IrregexpExecRaw(), v8::internal::RegExpImpl::IrregexpPrepare(), v8::internal::StringToIntHelper::IsOneByte(), IsWellFormedUnicode(), v8::internal::IrregexpInterpreter::Match(), v8::internal::RUNTIME_FUNCTION(), v8::internal::JsonStringifier::SerializeString(), v8::internal::JsonStringifier::SerializeString_(), v8::internal::TryStringToInt(), and v8::internal::Uri::Unescape().
IsShared()
bool v8::internal::String::IsShared () const [inline]
Definition at line 1140 of file string-inl.h.
                            {
  const bool result = StringShape(this).IsShared();
  DCHECK_IMPLIES(result, HeapLayout::InAnySharedSpace(this));
  return result;
}
References DCHECK_IMPLIES, v8::internal::HeapLayout::InAnySharedSpace(), v8::internal::StringShape::IsShared(), and v8::base::internal::result.
Referenced by v8::internal::ExternalString::DisposeResource(), and MakeExternal().
IsTwoByteRepresentation()
bool v8::internal::String::IsTwoByteRepresentation () const [inline]
Definition at line 517 of file string-inl.h.
                                           {
  return InstanceTypeChecker::IsTwoByteString(map());
}
References v8::internal::InstanceTypeChecker::IsTwoByteString(), and v8::internal::HeapObjectLayout::map().
Referenced by MakeExternal(), and PrefixForDebugPrint().
IsWellFormedUnicode()
bool v8::internal::String::IsWellFormedUnicode (Isolate * isolate, DirectHandle< String > string) [inline], [static]
Definition at line 1236 of file string-inl.h.
                                                              {
  // One-byte strings are definitionally well formed and cannot have unpaired
  // surrogates.
  if (string->IsOneByteRepresentation()) return true;
  // TODO(v8:13557): The two-byte case can be optimized by extending the
  // InstanceType. See
  // https://docs.google.com/document/d/15f-1c_Ysw3lvjy_Gx0SmmD9qeO8UuXuAbWIpWCnTDO8/
  string = Flatten(isolate, string);
  if (String::IsOneByteRepresentationUnderneath(*string)) return true;
  DisallowGarbageCollection no_gc;
  String::FlatContent flat = string->GetFlatContent(no_gc);
  DCHECK(flat.IsFlat());
  const uint16_t* data = flat.ToUC16Vector().begin();
  return !unibrow::Utf16::HasUnpairedSurrogate(data, string->length());
}
References v8::base::Vector< T >::begin(), v8::internal::DCHECK(), unibrow::Utf16::HasUnpairedSurrogate(), v8::internal::String::FlatContent::IsFlat(), IsOneByteRepresentationUnderneath(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, string, and v8::internal::String::FlatContent::ToUC16Vector().
Referenced by v8::internal::RUNTIME_FUNCTION().
LastIndexOf()
Tagged< Object > v8::internal::String::LastIndexOf (Isolate * isolate, DirectHandle< Object > receiver, DirectHandle< Object > search, DirectHandle< Object > position) [static]
Definition at line 1684 of file string.cc.
                                                                  {
  if (IsNullOrUndefined(*receiver, isolate)) {
    THROW_NEW_ERROR_RETURN_FAILURE(
        isolate, NewTypeError(MessageTemplate::kCalledOnNullOrUndefined,
                              isolate->factory()->NewStringFromAsciiChecked(
                                  "String.prototype.lastIndexOf")));
  }
  DirectHandle<String> receiver_string;
  ASSIGN_RETURN_FAILURE_ON_EXCEPTION(isolate, receiver_string,
                                     Object::ToString(isolate, receiver));
  DirectHandle<String> search_string;
  ASSIGN_RETURN_FAILURE_ON_EXCEPTION(isolate, search_string,
                                     Object::ToString(isolate, search));
  ASSIGN_RETURN_FAILURE_ON_EXCEPTION(isolate, position,
                                     Object::ToNumber(isolate, position));
  uint32_t start_index;
  if (IsNaN(*position)) {
    start_index = receiver_string->length();
  } else {
    ASSIGN_RETURN_FAILURE_ON_EXCEPTION(isolate, position,
                                       Object::ToInteger(isolate, position));
    start_index = ToValidIndex(*receiver_string, *position);
  }
  uint32_t pattern_length = search_string->length();
  uint32_t receiver_length = receiver_string->length();
  if (start_index + pattern_length > receiver_length) {
    start_index = receiver_length - pattern_length;
  }
  if (pattern_length == 0) {
    return Smi::FromInt(start_index);
  }
  receiver_string = String::Flatten(isolate, receiver_string);
  search_string = String::Flatten(isolate, search_string);
  int last_index = -1;
  DisallowGarbageCollection no_gc; // ensure vectors stay valid
  String::FlatContent receiver_content = receiver_string->GetFlatContent(no_gc);
  String::FlatContent search_content = search_string->GetFlatContent(no_gc);
  if (search_content.IsOneByte()) {
    base::Vector<const uint8_t> pat_vector = search_content.ToOneByteVector();
    if (receiver_content.IsOneByte()) {
      last_index = StringMatchBackwards(receiver_content.ToOneByteVector(),
                                        pat_vector, start_index);
    } else {
      last_index = StringMatchBackwards(receiver_content.ToUC16Vector(),
                                        pat_vector, start_index);
    }
  } else {
    base::Vector<const base::uc16> pat_vector = search_content.ToUC16Vector();
    if (receiver_content.IsOneByte()) {
      last_index = StringMatchBackwards(receiver_content.ToOneByteVector(),
                                        pat_vector, start_index);
    } else {
      last_index = StringMatchBackwards(receiver_content.ToUC16Vector(),
                                        pat_vector, start_index);
    }
  }
  return Smi::FromInt(last_index);
}
References ASSIGN_RETURN_FAILURE_ON_EXCEPTION, v8::internal::Isolate::factory(), v8::internal::IsNaN(), v8::internal::IsNullOrUndefined(), v8::internal::String::FlatContent::IsOneByte(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::anonymous_namespace{simd.cc}::search(), v8::internal::anonymous_namespace{string.cc}::StringMatchBackwards(), THROW_NEW_ERROR_RETURN_FAILURE, v8::internal::ToNumber(), v8::internal::String::FlatContent::ToOneByteVector(), ToString(), v8::internal::String::FlatContent::ToUC16Vector(), and v8::internal::anonymous_namespace{string.cc}::ToValidIndex().
Referenced by v8::internal::BUILTIN(), and v8::internal::RUNTIME_FUNCTION().
length() [1/2]
uint32_t v8::internal::String::length () const [inline]
Definition at line 132 of file string-inl.h.
{ return length_; }
References length_.
Referenced by v8::internal::SeqOneByteString::AllocatedSize(), v8::internal::SeqTwoByteString::AllocatedSize(), v8::internal::SeqOneByteString::clear_padding_destructively(), v8::internal::SeqTwoByteString::clear_padding_destructively(), v8::internal::SeqOneByteString::DataSizeFor(), v8::internal::SeqTwoByteString::DataSizeFor(), v8::internal::SeqOneByteString::Get(), v8::internal::SeqTwoByteString::Get(), v8::internal::ExternalOneByteString::Get(), v8::internal::ExternalTwoByteString::Get(), GetFlatContent(), GetImpl(), IsAscii(), IsEqualToImpl(), IsOneByte(), MakeExternal(), NonOneByteStart(), PrintUC16(), v8::internal::RUNTIME_FUNCTION(), v8::internal::SeqOneByteString::SeqOneByteStringSet(), v8::internal::SeqOneByteString::SeqOneByteStringSetChars(), v8::internal::SeqTwoByteString::SeqTwoByteStringSet(), Set(), v8::internal::SeqOneByteString::SizeFor(), v8::internal::SeqTwoByteString::SizeFor(), StringShortPrint(), ToCString(), ToStdString(), TryGetFlatContentFromDirectString(), VisitFlat(), and WriteToFlat().
length() [2/2]
uint32_t v8::internal::String::length (AcquireLoadTag) const [inline]
Definition at line 134 of file string-inl.h.
                                            {
  return base::AsAtomic32::Acquire_Load(&length_);
}
References v8::base::AsAtomicImpl< TAtomicStorageType >::Acquire_Load(), and length_.
MakeExternal() [1/2]
bool v8::internal::String::MakeExternal (Isolate * isolate, v8::String::ExternalOneByteStringResource * resource)
Definition at line 436 of file string.cc.
                                                                           {
  // Disallow garbage collection to avoid possible GC vs string access deadlock.
  DisallowGarbageCollection no_gc;
  // Externalizing twice leaks the external resource, so it's
  // prohibited by the API.
  DCHECK(
      this->SupportsExternalization(v8::String::Encoding::ONE_BYTE_ENCODING));
  DCHECK(resource->IsCacheable());
#ifdef ENABLE_SLOW_DCHECKS
  if (v8_flags.enable_slow_asserts) {
    // Assert that the resource and the string are equivalent.
    DCHECK(static_cast<size_t>(this->length()) == resource->length());
    if (this->IsTwoByteRepresentation()) {
      base::ScopedVector<uint16_t> smart_chars(this->length());
      String::WriteToFlat(this, smart_chars.begin(), 0, this->length());
      DCHECK(String::IsOneByte(smart_chars.begin(), this->length()));
    }
    base::ScopedVector<char> smart_chars(this->length());
    String::WriteToFlat(this, smart_chars.begin(), 0, this->length());
    DCHECK_EQ(0, memcmp(smart_chars.begin(), resource->data(),
                        resource->length() * sizeof(smart_chars[0])));
  }
#endif // DEBUG
  int size = this->Size(); // Byte size of the original string.
  // Abort if size does not allow in-place conversion.
  if (size < static_cast<int>(sizeof(UncachedExternalString))) return false;
  // Read-only strings cannot be made external, since that would mutate the
  // string.
  if (HeapLayout::InReadOnlySpace(this)) return false;
  if (IsShared()) {
    return MarkForExternalizationDuringGC(isolate, resource);
  }
  // For strings in the shared space we need the shared space isolate instead of
  // the current isolate.
  if (HeapLayout::InWritableSharedSpace(this)) {
    resource->Unaccount(reinterpret_cast<v8::Isolate*>(isolate));
    isolate = isolate->shared_space_isolate();
  }
  bool is_internalized = IsInternalizedString(this);
  bool has_pointers = StringShape(this).IsIndirect();
  base::MutexGuardIf mutex_guard(isolate->internalized_string_access(),
                                 is_internalized);
  // Morph the string to an external string by replacing the map and
  // reinitializing the fields. This won't work if the space the existing
  // string occupies is too small for a regular external string. Instead, we
  // resort to an uncached external string instead, omitting the field caching
  // the address of the backing store. When we encounter uncached external
  // strings in generated code, we need to bailout to runtime.
  constexpr bool is_one_byte = true;
  Tagged<Map> new_map =
      ComputeExternalStringMap<is_one_byte>(isolate, this, size);
  if (!isolate->heap()->IsLargeObject(this)) {
    // Byte size of the external String object.
    int new_size = this->SizeFromMap(new_map);
    if (has_pointers) {
      DCHECK(!HeapLayout::InWritableSharedSpace(this));
      isolate->heap()->NotifyObjectLayoutChange(
          this, no_gc, InvalidateRecordedSlots::kYes,
          InvalidateExternalPointerSlots::kNo, new_size);
    }
    isolate->heap()->NotifyObjectSizeChange(
        this, size, new_size,
        has_pointers ? ClearRecordedSlots::kYes : ClearRecordedSlots::kNo);
  } else {
    // We don't need special handling for the combination IsLargeObject &&
    // has_pointers, because indirect strings never get that large.
    DCHECK(!has_pointers);
  }
  // The external pointer slots must be initialized before the new map is
  // installed. Otherwise, a GC marking thread may see the new map before the
  // slots are initialized and attempt to mark the (invalid) external pointers
  // table entries as alive.
  static_cast<ExternalString*>(this)
      ->InitExternalPointerFieldsDuringExternalization(new_map, isolate);
  // We are storing the new map using release store after creating a filler in
  // the NotifyObjectSizeChange call for the left-over space to avoid races with
  // the sweeper thread.
  this->set_map(isolate, new_map, kReleaseStore);
  Tagged<ExternalOneByteString> self = Cast<ExternalOneByteString>(this);
  self->SetResource(isolate, resource);
  isolate->heap()->RegisterExternalString(this);
  // Force regeneration of the hash value.
  if (is_internalized) self->EnsureHash();
  return true;
}
References v8::base::Vector< T >::begin(), v8::String::ExternalOneByteStringResource::data(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Isolate::heap(), v8::internal::HeapLayout::InReadOnlySpace(), v8::internal::Isolate::internalized_string_access(), v8::internal::HeapLayout::InWritableSharedSpace(), v8::String::ExternalStringResourceBase::IsCacheable(), v8::internal::StringShape::IsIndirect(), v8::internal::InstanceTypeChecker::IsInternalizedString(), v8::internal::Heap::IsLargeObject(), IsOneByte(), IsShared(), IsTwoByteRepresentation(), v8::internal::kNo, v8::kReleaseStore, v8::internal::kYes, length(), v8::String::ExternalOneByteStringResource::length(), MarkForExternalizationDuringGC(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Heap::NotifyObjectLayoutChange(), v8::internal::Heap::NotifyObjectSizeChange(), v8::internal::Heap::RegisterExternalString(), v8::internal::HeapObjectLayout::set_map(), v8::internal::Isolate::shared_space_isolate(), v8::internal::HeapObjectLayout::Size(), size(), v8::internal::HeapObjectLayout::SizeFromMap(), SupportsExternalization(), v8::internal::this, v8::String::ExternalStringResourceBase::Unaccount(), v8::internal::v8_flags, and WriteToFlat().
MakeExternal() [2/2]
V8_EXPORT_PRIVATE bool v8::internal::String::MakeExternal (Isolate * isolate, v8::String::ExternalStringResource * resource)
MakeExternalDuringGC()
template<typename T >
void v8::internal::String::MakeExternalDuringGC (Isolate * isolate, T * resource)
Definition at line 290 of file string.cc.
                                                               {
  isolate->heap()->safepoint()->AssertActive();
  DCHECK_NE(isolate->heap()->gc_state(), Heap::NOT_IN_GC);
  constexpr bool is_one_byte =
      std::is_base_of_v<v8::String::ExternalOneByteStringResource, T>;
  int size = this->Size(); // Byte size of the original string.
  DCHECK_GE(size, sizeof(UncachedExternalString));
  // Morph the string to an external string by replacing the map and
  // reinitializing the fields. This won't work if the space the existing
  // string occupies is too small for a regular external string. Instead, we
  // resort to an uncached external string instead, omitting the field caching
  // the address of the backing store. When we encounter uncached external
  // strings in generated code, we need to bailout to runtime.
  Tagged<Map> new_map =
      ComputeExternalStringMap<is_one_byte>(isolate, this, size);
  // Byte size of the external String object.
  int new_size = this->SizeFromMap(new_map);
  // Shared strings are never indirect.
  DCHECK(!StringShape(this).IsIndirect());
  if (!isolate->heap()->IsLargeObject(this)) {
    isolate->heap()->NotifyObjectSizeChange(this, size, new_size,
                                            ClearRecordedSlots::kNo);
  }
  // The external pointer slots must be initialized before the new map is
  // installed. Otherwise, a GC marking thread may see the new map before the
  // slots are initialized and attempt to mark the (invalid) external pointers
  // table entries as alive.
  static_cast<ExternalString*>(this)
      ->InitExternalPointerFieldsDuringExternalization(new_map, isolate);
  // We are storing the new map using release store after creating a filler in
  // the NotifyObjectSizeChange call for the left-over space to avoid races with
  // the sweeper thread.
  this->set_map(isolate, new_map, kReleaseStore);
  if constexpr (is_one_byte) {
    Tagged<ExternalOneByteString> self = Cast<ExternalOneByteString>(this);
    self->SetResource(isolate, resource);
  } else {
    Tagged<ExternalTwoByteString> self = Cast<ExternalTwoByteString>(this);
    self->SetResource(isolate, resource);
  }
  isolate->heap()->RegisterExternalString(this);
}
References v8::internal::IsolateSafepoint::AssertActive(), v8::internal::DCHECK(), DCHECK_GE, DCHECK_NE, v8::internal::Heap::gc_state(), v8::internal::Isolate::heap(), v8::internal::Heap::IsLargeObject(), v8::internal::kNo, v8::kReleaseStore, v8::internal::Heap::NOT_IN_GC, v8::internal::Heap::NotifyObjectSizeChange(), v8::internal::Heap::RegisterExternalString(), v8::internal::Heap::safepoint(), v8::internal::HeapObjectLayout::set_map(), v8::internal::HeapObjectLayout::Size(), size(), and v8::internal::HeapObjectLayout::SizeFromMap().
MakeThin()
template<typename IsolateT >
void v8::internal::String::MakeThin (IsolateT * isolate, Tagged< String > canonical)
Definition at line 135 of file string.cc.
                                                                    {
  DisallowGarbageCollection no_gc;
  DCHECK_NE(this, internalized);
  DCHECK(IsInternalizedString(internalized));
  Tagged<Map> initial_map = map(kAcquireLoad);
  StringShape initial_shape(initial_map);
  DCHECK(!initial_shape.IsThin());
#ifdef DEBUG
  // Check that shared strings can only transition to ThinStrings on the main
  // thread when no other thread is active.
  // The exception is during serialization, as no strings have escaped the
  // thread yet.
  if (initial_shape.IsShared() && !isolate->has_active_deserializer()) {
    isolate->AsIsolate()->global_safepoint()->AssertActive();
  }
#endif
  bool may_contain_recorded_slots = initial_shape.IsIndirect();
  int old_size = SizeFromMap(initial_map);
  ReadOnlyRoots roots(isolate);
  Tagged<Map> target_map = internalized->IsOneByteRepresentation()
                               ? roots.thin_one_byte_string_map()
                               : roots.thin_two_byte_string_map();
  if (initial_shape.IsExternal()) {
    // Notify GC about the layout change before the transition to avoid
    // concurrent marking from observing any in-between state (e.g.
    // ExternalString map where the resource external pointer is overwritten
    // with a tagged pointer).
    // ExternalString -> ThinString transitions can only happen on the
    // main-thread.
    isolate->AsIsolate()->heap()->NotifyObjectLayoutChange(
        Tagged(this), no_gc, InvalidateRecordedSlots::kYes,
        InvalidateExternalPointerSlots::kYes, sizeof(ThinString));
    MigrateExternalString(isolate->AsIsolate(), this, internalized);
  }
  // Update actual first and then do release store on the map word. This ensures
  // that the concurrent marker will read the pointer when visiting a
  // ThinString.
  Tagged<ThinString> thin = UncheckedCast<ThinString>(Tagged(this));
  thin->set_actual(internalized);
  DCHECK_GE(old_size, sizeof(ThinString));
  int size_delta = old_size - sizeof(ThinString);
  if (size_delta != 0) {
    if (!Heap::IsLargeObject(thin)) {
      isolate->heap()->NotifyObjectSizeChange(
          thin, old_size, sizeof(ThinString),
          may_contain_recorded_slots ? ClearRecordedSlots::kYes
                                     : ClearRecordedSlots::kNo);
    } else {
      // We don't need special handling for the combination IsLargeObject &&
      // may_contain_recorded_slots, because indirect strings never get that
      // large.
      DCHECK(!may_contain_recorded_slots);
    }
  }
  if (initial_shape.IsExternal()) {
    set_map(isolate, target_map, kReleaseStore);
  } else {
    set_map_safe_transition(isolate, target_map, kReleaseStore);
  }
}
References v8::internal::DCHECK(), DCHECK_GE, DCHECK_NE, v8::internal::compiler::initial_map, v8::internal::StringShape::IsExternal(), v8::internal::StringShape::IsIndirect(), v8::internal::InstanceTypeChecker::IsInternalizedString(), v8::internal::Heap::IsLargeObject(), v8::internal::StringShape::IsShared(), v8::internal::StringShape::IsThin(), v8::kAcquireLoad, v8::internal::kNo, v8::kReleaseStore, v8::internal::kYes, v8::internal::HeapObjectLayout::map(), v8::internal::anonymous_namespace{string.cc}::MigrateExternalString(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::HeapObjectLayout::set_map(), v8::internal::HeapObjectLayout::set_map_safe_transition(), v8::internal::HeapObjectLayout::SizeFromMap(), and v8::internal::Tagged().
MarkForExternalizationDuringGC()
template<typename T >
bool v8::internal::String::MarkForExternalizationDuringGC (Isolate * isolate, T * resource)
Referenced by MakeExternal().
NonOneByteStart()
static uint32_t v8::internal::String::NonOneByteStart (const base::uc16 * chars, uint32_t length) [inline], [static]
Definition at line 603 of file string.h.
                                                          {
    DCHECK(IsAligned(reinterpret_cast<Address>(chars), sizeof(base::uc16)));
    const uint16_t* start = chars;
    const uint16_t* limit = chars + length;
    if (static_cast<size_t>(length) >= kUIntptrSize) {
      // Check unaligned chars.
      while (!IsAligned(reinterpret_cast<Address>(chars), kUIntptrSize)) {
        if (*chars > unibrow::Latin1::kMaxChar) {
          return static_cast<uint32_t>(chars - start);
        }
        ++chars;
      }
      // Check aligned words.
      static_assert(unibrow::Latin1::kMaxChar == 0xFF);
#ifdef V8_TARGET_LITTLE_ENDIAN
      const uintptr_t non_one_byte_mask = kUintptrAllBitsSet / 0xFFFF * 0xFF00;
#else
      const uintptr_t non_one_byte_mask = kUintptrAllBitsSet / 0xFFFF * 0x00FF;
#endif
      while (chars + sizeof(uintptr_t) <= limit) {
        if (*reinterpret_cast<const uintptr_t*>(chars) & non_one_byte_mask) {
          break;
        }
        chars += (sizeof(uintptr_t) / sizeof(base::uc16));
      }
    }
    // Check remaining unaligned chars, or find non-one-byte char in word.
    while (chars < limit) {
      if (*chars > unibrow::Latin1::kMaxChar) {
        return static_cast<uint32_t>(chars - start);
      }
      ++chars;
    }
    return static_cast<uint32_t>(chars - start);
  }
References v8::internal::DCHECK(), IsAligned(), unibrow::Latin1::kMaxChar, v8::internal::kUintptrAllBitsSet, v8::internal::kUIntptrSize, and length().
Referenced by IsOneByte().
PrefixForDebugPrint()
const char * v8::internal::String::PrefixForDebugPrint () const
Definition at line 570 of file string.cc.
                                              {
  StringShape shape(this);
  if (IsTwoByteRepresentation()) {
    if (shape.IsInternalized()) {
      return "u#";
    } else if (shape.IsCons()) {
      return "uc\"";
    } else if (shape.IsThin()) {
      return "u>\"";
    } else if (shape.IsExternal()) {
      return "ue\"";
    } else {
      return "u\"";
    }
  } else {
    if (shape.IsInternalized()) {
      return "#";
    } else if (shape.IsCons()) {
      return "c\"";
    } else if (shape.IsThin()) {
      return ">\"";
    } else if (shape.IsExternal()) {
      return "e\"";
    } else {
      return "\"";
    }
  }
  UNREACHABLE();
}
References v8::internal::StringShape::IsCons(), v8::internal::StringShape::IsExternal(), v8::internal::StringShape::IsInternalized(), v8::internal::StringShape::IsThin(), IsTwoByteRepresentation(), and v8::internal::UNREACHABLE().
Referenced by StringShortPrint().
PrintOn() [1/2]
void v8::internal::String::PrintOn (FILE * out)
Definition at line 1905 of file string.cc.
                               {
  uint32_t length = this->length();
  for (uint32_t i = 0; i < length; i++) {
    PrintF(file, "%c", Get(i));
  }
}
References file(), v8::internal::compiler::turboshaft::Get(), v8::internal::length, and v8::internal::PrintF().
PrintOn() [2/2]
void v8::internal::String::PrintOn (std::ostream & out)
Definition at line 1912 of file string.cc.
                                        {
  uint32_t length = this->length();
  for (uint32_t i = 0; i < length; i++) {
    ostream.put(Get(i));
  }
}
References v8::internal::compiler::turboshaft::Get(), and v8::internal::length.
PrintUC16() [1/2]
void v8::internal::String::PrintUC16 (std::ostream & os, int start = 0, int end = -1)
Definition at line 623 of file string.cc.
                                                         {
  if (end < 0) end = length();
  StringCharacterStream stream(this, start);
  for (int i = start; i < end && stream.HasMore(); i++) {
    os << AsUC16(stream.GetNext());
  }
}
References v8::internal::compiler::end(), v8::internal::StringCharacterStream::GetNext(), v8::internal::StringCharacterStream::HasMore(), and length().
Referenced by StringShortPrint().
PrintUC16() [2/2]
void v8::internal::String::PrintUC16 (StringStream * accumulator, int start, int end)
Definition at line 631 of file string.cc.
                                                                    {
  if (end < 0) end = length();
  StringCharacterStream stream(this, start);
  for (int i = start; i < end && stream.HasMore(); i++) {
    uint16_t c = stream.GetNext();
    if (c == '\n') {
      accumulator->Add("\\n");
    } else if (c == '\r') {
      accumulator->Add("\\r");
    } else if (c == '\\') {
      accumulator->Add("\\\\");
    } else if (!std::isprint(c)) {
      accumulator->Add("\\x%02x", c);
    } else {
      accumulator->Put(static_cast<char>(c));
    }
  }
}
References v8::internal::StringStream::Add(), v8::internal::compiler::end(), v8::internal::StringCharacterStream::GetNext(), v8::internal::StringCharacterStream::HasMore(), length(), and v8::internal::StringStream::Put().
requires() [1/6]
template<template< typename > typename HandleType>
v8::internal::String::requires (std::is_convertible_v< HandleType< String >, DirectHandle< String >>) [private]
requires() [2/6]
template<template< typename > typename HandleType>
v8::internal::String::requires (std::is_convertible_v< HandleType< String >, DirectHandle< String >>)
requires() [3/6]
template<template< typename > typename HandleType>
v8::internal::String::requires (std::is_convertible_v< HandleType< String >, DirectHandle< String >>) [private]
requires() [4/6]
template<typename T , template< typename > typename HandleType>
v8::internal::String::requires (std::is_convertible_v< HandleType< T >, DirectHandle< String >>)
requires() [5/6]
template<typename T , template< typename > typename HandleType>
v8::internal::String::requires (std::is_convertible_v< HandleType< T >, DirectHandle< String >>)
requires() [6/6]
template<typename T , template< typename > typename HandleType>
v8::internal::String::requires (std::is_convertible_v< HandleType< T >, DirectHandle< String >>)
Set()
void v8::internal::String::Set (uint32_t index, uint16_t value) [inline]
Definition at line 1126 of file string-inl.h.
                                               {
  DCHECK(index >= 0 && index < length());
  DCHECK(StringShape(this).IsSequential());
  return IsOneByteRepresentation()
             ? Cast<SeqOneByteString>(this)->SeqOneByteStringSet(index, value)
             : Cast<SeqTwoByteString>(this)->SeqTwoByteStringSet(index, value);
}
References v8::internal::DCHECK(), v8::internal::index, IsOneByteRepresentation(), length(), and v8::internal::value.
set_length() [1/2]
void v8::internal::String::set_length (uint32_t hash) [inline]
Definition at line 138 of file string-inl.h.
                                      {
#ifdef V8_ATOMIC_OBJECT_FIELD_WRITES
  base::AsAtomic32::Relaxed_Store(&length_, value);
#else
  length_ = value;
#endif
}
References length_, v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Store(), and v8::internal::value.
set_length() [2/2]
void v8::internal::String::set_length (uint32_t hash, ReleaseStoreTag) [inline]
Definition at line 146 of file string-inl.h.
                                                       {
  base::AsAtomic32::Release_Store(&length_, value);
}
References length_, v8::base::AsAtomicImpl< TAtomicStorageType >::Release_Store(), and v8::internal::value.
SlowAsArrayIndex()
bool v8::internal::String::SlowAsArrayIndex (uint32_t * index) [private]
Definition at line 1876 of file string.cc.
                                             {
  DisallowGarbageCollection no_gc;
  uint32_t length = this->length();
  if (length <= kMaxCachedArrayIndexLength) {
    uint32_t field = EnsureRawHash(); // Force computation of hash code.
    if (!IsIntegerIndex(field)) return false;
    *index = ArrayIndexValueBits::decode(field);
    return true;
  }
  if (length == 0 || length > kMaxArrayIndexSize) return false;
  StringCharacterStream stream(this);
  return StringToIndex(&stream, index);
}
References v8::internal::index, v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::StringToIndex().
Referenced by AsArrayIndex().
SlowAsIntegerIndex()
bool v8::internal::String::SlowAsIntegerIndex (size_t * index) [private]
Definition at line 1890 of file string.cc.
                                             {
  DisallowGarbageCollection no_gc;
  uint32_t length = this->length();
  if (length <= kMaxCachedArrayIndexLength) {
    uint32_t field = EnsureRawHash(); // Force computation of hash code.
    if (!IsIntegerIndex(field)) return false;
    *index = ArrayIndexValueBits::decode(field);
    return true;
  }
  if (length == 0 || length > kMaxIntegerIndexSize) return false;
  StringCharacterStream stream(this);
  return StringToIndex<StringCharacterStream, size_t, kToIntegerIndex>(&stream,
                                                                       index);
}
References v8::internal::index, v8::internal::length, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by AsIntegerIndex().
SlowEquals() [1/3]
bool v8::internal::String::SlowEquals (Isolate * isolate, DirectHandle< String > one, DirectHandle< String > two) [static], [private]
Definition at line 1283 of file string.cc.
                                                  {
  // Fast check: negative check with lengths.
  const uint32_t one_length = one->length();
  if (one_length != two->length()) return false;
  if (one_length == 0) return true;
  // Fast check: if at least one ThinString is involved, dereference it/them
  // and restart.
  if (IsThinString(*one) || IsThinString(*two)) {
    if (IsThinString(*one)) {
      one = direct_handle(Cast<ThinString>(*one)->actual(), isolate);
    }
    if (IsThinString(*two)) {
      two = direct_handle(Cast<ThinString>(*two)->actual(), isolate);
    }
    return String::Equals(isolate, one, two);
  }
  // Fast check: if hash code is computed for both strings
  // a fast negative check can be performed.
  uint32_t one_hash;
  uint32_t two_hash;
  if (one->TryGetHash(&one_hash) && two->TryGetHash(&two_hash)) {
#ifdef ENABLE_SLOW_DCHECKS
    if (v8_flags.enable_slow_asserts) {
      if (one_hash != two_hash) {
        bool found_difference = false;
        for (uint32_t i = 0; i < one_length; i++) {
          if (one->Get(i) != two->Get(i)) {
            found_difference = true;
            break;
          }
        }
        DCHECK(found_difference);
      }
    }
#endif
    if (one_hash != two_hash) return false;
  }
  one = String::Flatten(isolate, one);
  two = String::Flatten(isolate, two);
  DisallowGarbageCollection no_gc;
  String::FlatContent flat1 = one->GetFlatContent(no_gc);
  String::FlatContent flat2 = two->GetFlatContent(no_gc);
  if (flat1.IsOneByte() && flat2.IsOneByte()) {
    return CompareCharsEqual(flat1.ToOneByteVector().begin(),
                             flat2.ToOneByteVector().begin(), one_length);
  } else if (flat1.IsTwoByte() && flat2.IsTwoByte()) {
    return CompareCharsEqual(flat1.ToUC16Vector().begin(),
                             flat2.ToUC16Vector().begin(), one_length);
  } else if (flat1.IsOneByte() && flat2.IsTwoByte()) {
    return CompareCharsEqual(flat1.ToOneByteVector().begin(),
                             flat2.ToUC16Vector().begin(), one_length);
  } else if (flat1.IsTwoByte() && flat2.IsOneByte()) {
    return CompareCharsEqual(flat1.ToUC16Vector().begin(),
                             flat2.ToOneByteVector().begin(), one_length);
  }
  UNREACHABLE();
}
References v8::base::Vector< T >::begin(), v8::internal::CompareCharsEqual(), DCHECK, v8::internal::direct_handle(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::Equals(), v8::internal::String::FlatContent::IsOneByte(), v8::internal::InstanceTypeChecker::IsThinString(), v8::internal::String::FlatContent::IsTwoByte(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, one, v8::internal::String::FlatContent::ToOneByteVector(), v8::internal::String::FlatContent::ToUC16Vector(), UNREACHABLE, and v8::internal::v8_flags.
SlowEquals() [2/3]
bool v8::internal::String::SlowEquals (Tagged< String > other) const [private]
Definition at line 1218 of file string.cc.
                                                  {
  DCHECK(!SharedStringAccessGuardIfNeeded::IsNeeded(this));
  DCHECK(!SharedStringAccessGuardIfNeeded::IsNeeded(other));
  return SlowEquals(other, SharedStringAccessGuardIfNeeded::NotNeeded());
}
References DCHECK.
Referenced by v8::internal::Name::Equals(), and Equals().
SlowEquals() [3/3]
bool v8::internal::String::SlowEquals (Tagged< String > other, const SharedStringAccessGuardIfNeeded & access_guard) const [private]
Definition at line 1224 of file string.cc.
                                                               {
  DisallowGarbageCollection no_gc;
  // Fast check: negative check with lengths.
  uint32_t len = length();
  if (len != other->length()) return false;
  if (len == 0) return true;
  // Fast check: if at least one ThinString is involved, dereference it/them
  // and restart.
  if (IsThinString(this) || IsThinString(other)) {
    if (IsThinString(other)) other = Cast<ThinString>(other)->actual();
    if (IsThinString(this)) {
      return Cast<ThinString>(this)->actual()->Equals(other);
    } else {
      return this->Equals(other);
    }
  }
  // Fast check: if hash code is computed for both strings
  // a fast negative check can be performed.
  uint32_t this_hash;
  uint32_t other_hash;
  if (TryGetHash(&this_hash) && other->TryGetHash(&other_hash)) {
#ifdef ENABLE_SLOW_DCHECKS
    if (v8_flags.enable_slow_asserts) {
      if (this_hash != other_hash) {
        bool found_difference = false;
        for (uint32_t i = 0; i < len; i++) {
          if (Get(i) != other->Get(i)) {
            found_difference = true;
            break;
          }
        }
        DCHECK(found_difference);
      }
    }
#endif
    if (this_hash != other_hash) return false;
  }
  // We know the strings are both non-empty. Compare the first chars
  // before we try to flatten the strings.
  if (this->Get(0, access_guard) != other->Get(0, access_guard)) return false;
  if (IsSeqOneByteString(this) && IsSeqOneByteString(other)) {
    const uint8_t* str1 =
        Cast<SeqOneByteString>(this)->GetChars(no_gc, access_guard);
    const uint8_t* str2 =
        Cast<SeqOneByteString>(other)->GetChars(no_gc, access_guard);
    return CompareCharsEqual(str1, str2, len);
  }
  StringComparator comparator;
  return comparator.Equals(this, other, access_guard);
}
References v8::internal::CompareCharsEqual(), DCHECK, v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::Equals(), v8::internal::StringComparator::Equals(), v8::internal::compiler::turboshaft::Get(), v8::internal::InstanceTypeChecker::IsThinString(), v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::v8_flags.
SlowGetFlatContent()
V8_EXPORT_PRIVATE FlatContent v8::internal::String::SlowGetFlatContent (const DisallowGarbageCollection & no_gc, const SharedStringAccessGuardIfNeeded &) [private]
Referenced by GetFlatContent().
StringShortPrint()
void v8::internal::String::StringShortPrint (StringStream * accumulator)
Definition at line 606 of file string.cc.
                                                       {
  const uint32_t len = length();
  accumulator->Add("<String[%u]: ", len);
  accumulator->Add(PrefixForDebugPrint());
  if (len > kMaxShortPrintLength) {
    accumulator->Add("...<truncated>>");
    accumulator->Add(SuffixForDebugPrint());
    accumulator->Put('>');
    return;
  }
  PrintUC16(accumulator, 0, len);
  accumulator->Add(SuffixForDebugPrint());
  accumulator->Put('>');
}
References v8::internal::StringStream::Add(), kMaxShortPrintLength, length(), PrefixForDebugPrint(), PrintUC16(), v8::internal::StringStream::Put(), and SuffixForDebugPrint().
SuffixForDebugPrint()
const char * v8::internal::String::SuffixForDebugPrint () const
Definition at line 600 of file string.cc.
                                              {
  StringShape shape(this);
  if (shape.IsInternalized()) return "";
  return "\"";
}
References v8::internal::StringShape::IsInternalized().
Referenced by StringShortPrint().
SupportsExternalization()
bool v8::internal::String::SupportsExternalization (v8::String::Encoding encoding)
Definition at line 530 of file string.cc.
                                                              {
  if (IsThinString(this)) {
    return i::Cast<i::ThinString>(this)->actual()->SupportsExternalization(
        encoding);
  }
  // RO_SPACE strings cannot be externalized.
  if (HeapLayout::InReadOnlySpace(this)) {
    return false;
  }
#if V8_COMPRESS_POINTERS && !V8_ENABLE_SANDBOX
  // In this configuration, small strings may not be in-place externalizable.
  if (this->Size() < static_cast<int>(sizeof(UncachedExternalString))) {
    return false;
  }
#else
  DCHECK_LE(sizeof(UncachedExternalString), this->Size());
#endif
  StringShape shape(this);
  // Already an external string.
  if (shape.IsExternal()) {
    return false;
  }
  // Only strings in old space can be externalized.
  if (HeapLayout::InYoungGeneration(Tagged(this))) {
    return false;
  }
  // Encoding changes are not supported.
  static_assert(kStringEncodingMask == 1 << 3);
  static_assert(v8::String::Encoding::ONE_BYTE_ENCODING == 1 << 3);
  static_assert(v8::String::Encoding::TWO_BYTE_ENCODING == 0);
  return (static_cast<uint32_t>(shape.IsOneByte()) << 3) ==
         static_cast<uint32_t>(encoding);
}
References DCHECK_LE, v8::internal::HeapLayout::InReadOnlySpace(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::StringShape::IsExternal(), v8::internal::StringShape::IsOneByte(), v8::internal::InstanceTypeChecker::IsThinString(), v8::internal::kStringEncodingMask, v8::internal::HeapObjectLayout::Size(), and v8::internal::Tagged().
Referenced by MakeExternal().
ToArrayIndex()
int32_t v8::internal::String::ToArrayIndex (Address addr) [static]
Definition at line 650 of file string.cc.
                                         {
  DisallowGarbageCollection no_gc;
  Tagged<String> key(addr);
  uint32_t index;
  if (!key->AsArrayIndex(&index)) return -1;
  if (index <= INT_MAX) return index;
  return -1;
}
References v8::internal::index, v8::internal::key, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
ToCString() [1/2]
std::unique_ptr< char[]> v8::internal::String::ToCString (size_t * length_output = nullptr)
Definition at line 742 of file string.cc.
                                                             {
  return ToCString(0, length(), length_return);
}
References length(), and ToCString().
ToCString() [2/2]
std::unique_ptr< char[]> v8::internal::String::ToCString (uint32_t offset, uint32_t length, size_t * length_output = nullptr)
Definition at line 713 of file string.cc.
                                                                 {
  DCHECK_LE(length, this->length());
  DCHECK_LE(offset, this->length() - length);
  StringCharacterStream stream(this, offset);
  // First, compute the required size of the output buffer.
  size_t utf8_bytes = stream.CountUtf8Bytes(length);
  if (length_return) {
    *length_return = utf8_bytes;
  }
  // Second, allocate the output buffer.
  size_t capacity = utf8_bytes + 1;
  char* result = NewArray<char>(capacity);
  // Third, encode the string into the output buffer.
  stream.Reset(this, offset);
  size_t pos = stream.WriteUtf8Bytes(length, result, utf8_bytes);
  // Add an explicit null terminator
  DCHECK_LT(pos, capacity);
  result[pos] = 0;
  return std::unique_ptr<char[]>(result);
}
References v8::internal::StringCharacterStream::CountUtf8Bytes(), DCHECK_LE, DCHECK_LT, length(), v8::internal::StringCharacterStream::Reset(), v8::base::internal::result, and v8::internal::StringCharacterStream::WriteUtf8Bytes().
Referenced by v8::internal::RUNTIME_FUNCTION(), and ToCString().
ToStdString()
std::string v8::internal::String::ToStdString ()
Definition at line 746 of file string.cc.
                              {
  uint32_t length = this->length();
  StringCharacterStream stream(this, 0);
  size_t utf8_bytes = stream.CountUtf8Bytes(length);
  std::string result;
  result.resize(utf8_bytes);
  stream.Reset(this, 0);
  stream.WriteUtf8Bytes(length, result.data(), utf8_bytes);
  return result;
}
References v8::internal::StringCharacterStream::CountUtf8Bytes(), length(), v8::internal::StringCharacterStream::Reset(), v8::base::internal::result, v8::internal::string, and v8::internal::StringCharacterStream::WriteUtf8Bytes().
TryGetFlatContentFromDirectString()
std::optional< String::FlatContent > v8::internal::String::TryGetFlatContentFromDirectString (const DisallowGarbageCollection & no_gc, Tagged< String > string, uint32_t offset, uint32_t length, const SharedStringAccessGuardIfNeeded & access_guard) [inline], [static], [private]
Definition at line 995 of file string-inl.h.
                                                         {
  DCHECK_LE(offset + length, string->length());
  return string->DispatchToSpecificType(absl::Overload{
      [&](Tagged<SeqOneByteString> s) {
        return FlatContent(s->GetChars(no_gc, access_guard) + offset, length,
                           no_gc);
      },
      [&](Tagged<SeqTwoByteString> s) {
        return FlatContent(s->GetChars(no_gc, access_guard) + offset, length,
                           no_gc);
      },
      [&](Tagged<ExternalOneByteString> s) {
        return FlatContent(s->GetChars() + offset, length, no_gc);
      },
      [&](Tagged<ExternalTwoByteString> s) {
        return FlatContent(s->GetChars() + offset, length, no_gc);
      },
      [&](Tagged<String> s) { return std::nullopt; }});
}
References DCHECK_LE, length(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and string.
Referenced by GetFlatContent().
Utf8Length()
size_t v8::internal::String::Utf8Length (Isolate * isolate, DirectHandle< String > string) [inline], [static]
Definition at line 1214 of file string-inl.h.
                                                                       {
  string = Flatten(isolate, string);
  DisallowGarbageCollection no_gc;
  FlatContent content = string->GetFlatContent(no_gc);
  DCHECK(content.IsFlat());
  if (content.IsOneByte()) {
    auto vec = content.ToOneByteVector();
    return simdutf::utf8_length_from_latin1(
        reinterpret_cast<const char*>(vec.begin()), vec.size());
  }
  // TODO(419496232): Use simdutf once upstream bug is resolved.
  size_t utf8_length = 0;
  uint16_t last_character = unibrow::Utf16::kNoPreviousCharacter;
  for (uint16_t c : content.ToUC16Vector()) {
    utf8_length += unibrow::Utf8::Length(c, last_character);
    last_character = c;
  }
  return utf8_length;
}
References v8::internal::DCHECK(), v8::internal::String::FlatContent::IsFlat(), v8::internal::String::FlatContent::IsOneByte(), unibrow::Utf16::kNoPreviousCharacter, unibrow::Utf8::Length(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::String::FlatContent::ToOneByteVector(), and v8::internal::String::FlatContent::ToUC16Vector().
Referenced by v8::internal::anonymous_namespace{builtins-trace.cc}::MaybeUtf8::MaybeUtf8(), and v8::String::Utf8LengthV2().
VisitFlat() [1/2]
template<class Visitor >
Tagged< ConsString > v8::internal::String::VisitFlat (Visitor * visitor, Tagged< String > string, int offset, const SharedStringAccessGuardIfNeeded & access_guard) [inline], [static]
Definition at line 1167 of file string-inl.h.
                                                         {
  DisallowGarbageCollection no_gc;
  int slice_offset = offset;
  const uint32_t length = string->length();
  DCHECK_LE(offset, length);
  while (true) {
    std::optional<Tagged<ConsString>> ret =
        string->DispatchToSpecificType(absl::Overload{
            [&](Tagged<SeqOneByteString> s) {
              visitor->VisitOneByteString(
                  s->GetChars(no_gc, access_guard) + slice_offset,
                  length - offset);
              return Tagged<ConsString>();
            },
            [&](Tagged<SeqTwoByteString> s) {
              visitor->VisitTwoByteString(
                  s->GetChars(no_gc, access_guard) + slice_offset,
                  length - offset);
              return Tagged<ConsString>();
            },
            [&](Tagged<ExternalOneByteString> s) {
              visitor->VisitOneByteString(s->GetChars() + slice_offset,
                                          length - offset);
              return Tagged<ConsString>();
            },
            [&](Tagged<ExternalTwoByteString> s) {
              visitor->VisitTwoByteString(s->GetChars() + slice_offset,
                                          length - offset);
              return Tagged<ConsString>();
            },
            [&](Tagged<SlicedString> s) {
              slice_offset += s->offset();
              string = s->parent();
              return std::nullopt;
            },
            [&](Tagged<ThinString> s) {
              string = s->actual();
              return std::nullopt;
            },
            [&](Tagged<ConsString> s) { return s; }});
    if (ret) return ret.value();
  }
}
References DCHECK_LE, length(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
VisitFlat() [2/2]
template<class Visitor >
Tagged< ConsString > v8::internal::String::VisitFlat (Visitor * visitor, Tagged< String > string, int offset = 0) [inline], [static]
Definition at line 1159 of file string-inl.h.
                                                       {
  DCHECK(!SharedStringAccessGuardIfNeeded::IsNeeded(string));
  return VisitFlat(visitor, string, offset,
                   SharedStringAccessGuardIfNeeded::NotNeeded());
}
References v8::internal::DCHECK(), v8::internal::SharedStringAccessGuardIfNeeded::IsNeeded(), and v8::internal::SharedStringAccessGuardIfNeeded::NotNeeded().
Referenced by v8::internal::StringComparator::State::Advance(), v8::ContainsOnlyOneByteHelper::Check(), v8::ContainsOnlyOneByteHelper::CheckCons(), v8::internal::StringCharacterStream::HasMore(), v8::internal::StringComparator::State::Init(), and v8::internal::StringCharacterStream::Reset().
WriteToFlat() [1/2]
template<typename SinkCharT >
void v8::internal::String::WriteToFlat (Tagged< String > source, SinkCharT * sink, uint32_t start, uint32_t length) [static]
Definition at line 763 of file string.cc.
                                          {
  DCHECK(!SharedStringAccessGuardIfNeeded::IsNeeded(source));
  return WriteToFlat(source, sink, start, length,
                     SharedStringAccessGuardIfNeeded::NotNeeded());
}
References v8::internal::DCHECK(), v8::internal::SharedStringAccessGuardIfNeeded::IsNeeded(), length(), v8::internal::SharedStringAccessGuardIfNeeded::NotNeeded(), and source.
Referenced by v8::internal::IncrementalStringBuilder::AppendStringByCopy(), v8::internal::compiler::JSNativeContextSpecialization::Concatenate(), v8::internal::anonymous_namespace{externalize-string-extension.cc}::CreateExternalizableString(), v8::internal::ETWJITInterface::EventHandler(), v8::internal::ExternalizeStringExtension::Externalize(), v8::internal::JsonStringifier::InitializeGap(), v8::internal::IsSpecialIndex(), MakeExternal(), v8::internal::Factory::NewCopiedSubstring(), v8::internal::Factory::NewInternalizedStringImpl(), v8::internal::PerfettoV8String::PerfettoV8String(), v8::internal::requires(), v8::internal::RUNTIME_FUNCTION(), v8::internal::anonymous_namespace{compiler.cc}::StressBackgroundCompileThread::SourceStream::SourceStream(), v8::internal::StringBuilderConcatHelper(), v8::internal::StringReplaceGlobalAtomRegExpWithString(), v8::internal::StringReplaceGlobalRegExpWithEmptyString(), v8::internal::TryStringToDouble(), v8::internal::StringTable::Data::TryStringToIndexOrLookupExisting(), v8::internal::TryStringToInt(), v8::internal::anonymous_namespace{objects.cc}::WriteFixedArrayToFlat(), v8::WriteHelper(), and v8::WriteHelperV2().
WriteToFlat() [2/2]
template<typename SinkCharT >
void v8::internal::String::WriteToFlat (Tagged< String > source, SinkCharT * sink, uint32_t start, uint32_t length, const SharedStringAccessGuardIfNeeded & access_guard) [static]
Definition at line 771 of file string.cc.
                                                                              {
  DisallowGarbageCollection no_gc;
  if (length == 0) return;
  while (true) {
    DCHECK_GT(length, 0);
    DCHECK_LE(length, source->length());
    DCHECK_LT(start, source->length());
    DCHECK_LE(start + length, source->length());
    if (source->DispatchToSpecificType(absl::Overload{
            [&](Tagged<SeqOneByteString> str) {
              CopyChars(sink, str->GetChars(no_gc, access_guard) + start,
                        length);
              return true;
            },
            [&](Tagged<SeqTwoByteString> str) {
              CopyChars(sink, str->GetChars(no_gc, access_guard) + start,
                        length);
              return true;
            },
            [&](Tagged<ExternalOneByteString> str) {
              CopyChars(sink, str->GetChars() + start, length);
              return true;
            },
            [&](Tagged<ExternalTwoByteString> str) {
              CopyChars(sink, str->GetChars() + start, length);
              return true;
            },
            [&](Tagged<ConsString> cons_string) {
              Tagged<String> first = cons_string->first();
              uint32_t boundary = first->length();
              // Here we explicitly use signed ints as the values can become
              // negative. The sum of {first_length} and {second_length} is
              // always {length}, but the values can become negative, in which
              // case no characters of the respective string are needed.
              int32_t first_length = boundary - start;
              int32_t second_length = length - first_length;
              DCHECK_EQ(static_cast<uint32_t>(first_length + second_length),
                        length);
              if (second_length >= first_length) {
                DCHECK_GT(second_length, 0);
                // Right hand side is longer. Recurse over left.
                if (first_length > 0) {
                  DCHECK_LT(first_length, length);
                  DCHECK_LT(second_length, length);
                  WriteToFlat(first, sink, start, first_length, access_guard);
                  if (start == 0 && cons_string->second() == first) {
                    DCHECK_LE(boundary * 2, length);
                    CopyChars(sink + boundary, sink, boundary);
                    return true;
                  }
                  sink += first_length;
                  start = 0;
                  length -= first_length;
                } else {
                  start -= boundary;
                }
                source = cons_string->second();
              } else {
                DCHECK_GT(first_length, 0);
                // Left hand side is longer. Recurse over right.
                if (second_length > 0) {
                  DCHECK_LT(first_length, length);
                  DCHECK_LT(second_length, length);
                  uint32_t second_start = first_length;
                  DCHECK_EQ(second_start + second_length, length);
                  Tagged<String> second = cons_string->second();
                  // When repeatedly appending to a string, we get a cons string
                  // that is unbalanced to the left, a list, essentially. We
                  // inline the common case of sequential one-byte right child.
                  if (second_length == 1) {
                    sink[second_start] =
                        static_cast<SinkCharT>(second->Get(0, access_guard));
                  } else if (IsSeqOneByteString(second)) {
                    CopyChars(sink + second_start,
                              Cast<SeqOneByteString>(second)->GetChars(
                                  no_gc, access_guard),
                              second_length);
                  } else {
                    WriteToFlat(second, sink + second_start, 0, second_length,
                                access_guard);
                  }
                  length -= second_length;
                }
                source = first;
              }
              return length == 0;
            },
            [&](Tagged<SlicedString> slice) {
              uint32_t offset = slice->offset();
              source = slice->parent();
              start += offset;
              return false;
            },
            [&](Tagged<ThinString> thin_string) {
              source = thin_string->actual();
              return false;
            }})) {
      return;
    }
  }
  UNREACHABLE();
}
References DCHECK_GT, DCHECK_LE, DCHECK_LT, length(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and source.
WriteToFlat2()
template<typename SinkCharT >
void v8::internal::String::WriteToFlat2 (SinkCharT * dst, Tagged< ConsString > src, uint32_t src_index, uint32_t length, const SharedStringAccessGuardIfNeeded & aguard, const DisallowGarbageCollection & no_gc) [static]
Definition at line 1052 of file string.cc.
                                                                  {
  DCHECK_NE(length, 0);
  DCHECK(!src->IsFlat());
  DCHECK_LE(src_index + length, src->length());
  // Limitations of the current implementation, which only supports flattening
  // the entire string.
  DCHECK_EQ(src_index, 0);
  DCHECK_EQ(length, src->length());
#ifdef V8_ENABLE_SANDBOX
  // See also: https://crbug.com/415407113.
  DCHECK(Sandbox::current()->Contains(dst));
#endif // V8_ENABLE_SANDBOX
  // The most common form of cons strings are degenerate unbalanced left-heavy
  // binary trees (i.e. where `second` is a flat string and `first` another
  // cons string). This form is created when building a string by appending
  // repeatedly: `str = "a" + "b" + ... + "z";
  //
  // To optimize for this, we flatten in reverse-DFS order, i.e. right-to-left.
  // This way, the stack never grows beyond size 1. Additionally, we elide the
  // stack push for the element that will immediately be processed next.
  // Finally, the iterative algorithm is split into two physically separate
  // loops - the first is optimized for cases when the cons tree contains only
  // sequential one-byte strings. The second handles all other cases
  // generically.
  //
  // Note this implementation is highly tuned. Please don't change anything
  // without watching benchmark scores.
  SinkCharT* rdst = dst + length; // Reverse cursor.
  wtf_stack_t stack{src->first()};
  wtf_stack_top_t top = src->second();
  WriteToFlat_RepeatOptimizer<SinkCharT> ropt;
  WriteToFlat2Impl<kWTFSeqOneByte>(rdst, top, stack, ropt, aguard, no_gc);
  WriteToFlat2Impl<kWTFGeneric>(rdst, top, stack, ropt, aguard, no_gc);
}
References v8::internal::anonymous_namespace{read-only-promotion.cc}::Contains(), DCHECK, DCHECK_EQ, DCHECK_LE, DCHECK_NE, v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::stack.
WriteUtf8()
size_t v8::internal::String::WriteUtf8 (Isolate * isolate, DirectHandle< String > string, char * buffer, size_t capacity, Utf8EncodingFlags flags, size_t * processed_characters_return = nullptr) [static]
Definition at line 1096 of file string.cc.
                                                              {
  DCHECK_IMPLIES(flags & Utf8EncodingFlag::kNullTerminate, capacity > 0);
  DCHECK_IMPLIES(capacity > 0, buffer != nullptr);
  string = Flatten(isolate, string);
  DisallowGarbageCollection no_gc;
  FlatContent content = string->GetFlatContent(no_gc);
  DCHECK(content.IsFlat());
  auto encoding_result = content.IsOneByte()
                             ? unibrow::Utf8::Encode<uint8_t>(
                                   content.ToOneByteVector(), buffer, capacity,
                                   flags & Utf8EncodingFlag::kNullTerminate,
                                   flags & Utf8EncodingFlag::kReplaceInvalid)
                             : unibrow::Utf8::Encode<uint16_t>(
                                   content.ToUC16Vector(), buffer, capacity,
                                   flags & Utf8EncodingFlag::kNullTerminate,
                                   flags & Utf8EncodingFlag::kReplaceInvalid);
  if (processed_characters_return != nullptr) {
    *processed_characters_return = encoding_result.characters_processed;
  }
  return encoding_result.bytes_written;
}
References DCHECK, DCHECK_IMPLIES, flags(), v8::internal::String::FlatContent::IsFlat(), v8::internal::String::FlatContent::IsOneByte(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::String::FlatContent::ToOneByteVector(), and v8::internal::String::FlatContent::ToUC16Vector().
Referenced by v8::internal::anonymous_namespace{builtins-trace.cc}::MaybeUtf8::MaybeUtf8(), and v8::String::WriteUtf8V2().
Friends And Related Function Documentation
Accessors
friend class Accessors [friend]
Definition at line 704 of file string.h.
CodeStubAssembler
friend class CodeStubAssembler [friend]
Definition at line 697 of file string.h.
compiler::AccessBuilder
friend class compiler::AccessBuilder [friend]
Definition at line 708 of file string.h.
InternalizedStringKey
friend class InternalizedStringKey [friend]
Definition at line 701 of file string.h.
maglev::MaglevAssembler
friend class maglev::MaglevAssembler [friend]
Definition at line 706 of file string.h.
maglev::MaglevGraphBuilder
friend class maglev::MaglevGraphBuilder [friend]
Definition at line 707 of file string.h.
Name
friend class Name [friend]
Definition at line 696 of file string.h.
OffsetsForDebug
friend struct OffsetsForDebug [friend]
Definition at line 703 of file string.h.
SandboxTesting
friend class SandboxTesting [friend]
Definition at line 700 of file string.h.
SharedStringTableInsertionKey
friend class SharedStringTableInsertionKey [friend]
Definition at line 699 of file string.h.
StringBuiltinsAssembler
friend class StringBuiltinsAssembler [friend]
Definition at line 705 of file string.h.
StringTableInsertionKey
friend class StringTableInsertionKey [friend]
Definition at line 698 of file string.h.
TorqueGeneratedStringAsserts
friend class TorqueGeneratedStringAsserts [friend]
Definition at line 710 of file string.h.
wasm::baseline::LiftoffCompiler
friend class wasm::baseline::LiftoffCompiler [friend]
Definition at line 709 of file string.h.
Member Data Documentation
allocation [1/2]
HandleType< T > AllocationType v8::internal::String::allocation = AllocationType::kYoung)
Definition at line 298 of file string.h.
allocation [2/2]
HandleType<ConsString> AllocationType v8::internal::String::allocation [private]
Definition at line 734 of file string.h.
cons
HandleType<ConsString> v8::internal::String::cons [private]
Definition at line 734 of file string.h.
kInlineLineEndsSize
constexpr uint32_t v8::internal::String::kInlineLineEndsSize = 32 [static], [constexpr]
Definition at line 660 of file string.h.
kMaxCodePoint
const base::uc32 v8::internal::String::kMaxCodePoint = 0x10ffff [static]
Definition at line 516 of file string.h.
Referenced by v8::internal::anonymous_namespace{regexp-compiler.cc}::AddRange(), v8::internal::Scanner::IsInvalid(), v8::internal::compiler::Typer::Visitor::JSCallTyper(), v8::internal::anonymous_namespace{regexp-macro-assembler.cc}::MaskEndOfRangeMarker(), and v8::internal::Scanner::ScanUnicodeEscape().
kMaxHashCalcLength
const uint32_t v8::internal::String::kMaxHashCalcLength = 16383 [static]
Definition at line 527 of file string.h.
Referenced by v8::internal::StringHasher::GetTrivialHash(), and v8::internal::StringHasher::HashSequentialString().
kMaxLength
const uint32_t v8::internal::String::kMaxLength = v8::String::kMaxLength [static]
Definition at line 523 of file string.h.
Referenced by v8::internal::IncrementalStringBuilder::Accumulate(), v8::internal::RegExpBuiltinsAssembler::AdvanceStringIndex(), v8::internal::FactoryBase< Impl >::AllocateRawOneByteInternalizedString(), v8::internal::FactoryBase< Impl >::AllocateRawTwoByteInternalizedString(), v8::internal::compiler::JSNativeContextSpecialization::BuildIndexedStringLoad(), v8::internal::BUILTIN(), v8::String::Concat(), v8::internal::anonymous_namespace{builtins-string.cc}::ConvertCaseHelper(), v8::internal::anonymous_namespace{js-regexp.cc}::CountAdditionalEscapeChars(), v8::internal::IncrementalStringBuilder::EscapedLengthIfCurrentPartFits(), v8::internal::JsonStringifier::EscapedLengthIfCurrentPartFits(), v8::internal::anonymous_namespace{uri.cc}::EscapePrivate(), v8::internal::JsonStringifier::Extend(), v8::internal::anonymous_namespace{json-stringifier.cc}::FastJsonStringify(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::FromInt32ToTagged(), v8::internal::compiler::JSTypedLowering::GenerateStringAddition(), v8::internal::LookupIterator::GetStringPropertyValue(), v8::internal::StringHasher::GetTrivialHash(), v8::internal::ReplacementStringBuilder::IncrementCharacterCount(), v8::internal::compiler::Typer::Visitor::JSCallTyper(), v8::internal::anonymous_namespace{runtime-wasm.cc}::MeasureWtf8(), v8::internal::FactoryBase< Impl >::NewConsString(), v8::String::NewExternalOneByte(), v8::internal::Factory::NewExternalStringFromOneByte(), v8::internal::Factory::NewExternalStringFromTwoByte(), v8::String::NewExternalTwoByte(), v8::String::NewFromUtf8Literal(), v8::internal::FactoryBase< Impl >::NewRawStringWithMap(), v8::internal::anonymous_namespace{objects.cc}::NoSideEffectsErrorToString(), v8::internal::BigInt::NoSideEffectsToString(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAdd(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeConcat(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeStartsWith(), v8::internal::requires(), v8::internal::RUNTIME_FUNCTION(), v8::internal::JsonStringifier::SerializeArrayLikeSlow(), v8::internal::anonymous_namespace{js-number-format.cc}::SignedStringLength(), v8::internal::SerializedCodeData::SourceHash(), v8::internal::StringBuiltinsAssembler::StringAdd(), v8::internal::StringBuilderConcatLength(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::StringConcatHelper(), v8::internal::JsonStringifier::Stringify(), v8::internal::StringReplaceGlobalAtomRegExpWithString(), v8::internal::BigInt::ToString(), v8::internal::maglev::MaglevGraphBuilder::TryBuildNewConsString(), and v8::internal::anonymous_namespace{uri.cc}::UnescapeSlow().
kMaxOneByteCharCode
const int32_t v8::internal::String::kMaxOneByteCharCode = unibrow::Latin1::kMaxChar [static]
Definition at line 512 of file string.h.
Referenced by v8::internal::CharacterRange::AddCaseEquivalents(), v8::internal::BUILTIN(), v8::internal::RegExpMacroAssemblerRISCV::CheckBitInTable(), v8::internal::TextNode::FilterOneByte(), v8::internal::maglev::BuiltinStringFromCharCode::GenerateCode(), v8::internal::anonymous_namespace{regexp-compiler.cc}::GetCaseIndependentLetters(), v8::internal::maglev::MaglevGraphBuilder::GetConstantSingleCharacterStringFromCode(), v8::internal::JsonStringifier::InitializeGap(), v8::internal::maglev::MaglevAssembler::LoadSingleCharacterString(), v8::internal::FactoryBase< Impl >::LookupSingleCharacterStringFromCode(), v8::internal::QuickCheckDetails::Rationalize(), v8::internal::SeqOneByteString::SeqOneByteStringSet(), v8::internal::CodeStubAssembler::SingleCharacterStringConstant(), v8::internal::anonymous_namespace{regexp-compiler.cc}::SplitSearchSpace(), v8::internal::maglev::MaglevAssembler::StringFromCharCode(), v8::internal::CodeStubAssembler::StringFromSingleCharCode(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::StringFromSingleCharCode(), v8::internal::CodeStubAssembler::StringFromSingleOneByteCharCode(), v8::internal::TextNode::TextEmitPass(), v8::internal::TF_BUILTIN(), and v8::internal::anonymous_namespace{uri.cc}::UnescapeSlow().
kMaxOneByteCharCodeU
const uint32_t v8::internal::String::kMaxOneByteCharCodeU = unibrow::Latin1::kMaxChar [static]
Definition at line 513 of file string.h.
Referenced by v8::internal::anonymous_namespace{regexp-compiler.cc}::CharMask(), v8::internal::CharacterRange::ClampToOneByte(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitAtomNonLetter(), v8::internal::StringSearch< PatternChar, SubjectChar >::exceedsOneByte(), and v8::internal::anonymous_namespace{regexp-compiler.cc}::MaxCodeUnit().
kMaxShortPrintLength
const uint32_t v8::internal::String::kMaxShortPrintLength = 1024 [static]
Definition at line 530 of file string.h.
Referenced by v8::internal::StringStream::PrintObject(), and StringShortPrint().
kMaxUtf16CodeUnit
const int v8::internal::String::kMaxUtf16CodeUnit = 0xffff [static]
Definition at line 514 of file string.h.
Referenced by v8::internal::RegExpMacroAssemblerRISCV::CheckNotCharacterAfterMinusAnd(), v8::internal::DEFINE_LAZY_LEAKY_OBJECT_GETTER(), v8::internal::anonymous_namespace{regexp-compiler.cc}::GenerateBranches(), and v8::internal::TF_BUILTIN().
kMaxUtf16CodeUnitU
const uint32_t v8::internal::String::kMaxUtf16CodeUnitU = kMaxUtf16CodeUnit [static]
Definition at line 515 of file string.h.
Referenced by v8::internal::anonymous_namespace{regexp-compiler.cc}::CharMask(), and v8::internal::anonymous_namespace{regexp-compiler.cc}::MaxCodeUnit().
length_
uint32_t v8::internal::String::length_
Definition at line 772 of file string.h.
Referenced by length(), v8::internal::FlatStringReader::length(), and set_length().
source
HandleType<String> v8::internal::String::source [private]
Definition at line 748 of file string.h.
Referenced by WriteToFlat().
string
HandleType< T > v8::internal::String::string
Definition at line 297 of file string.h.
Referenced by IsConsStringEqualToImpl(), IsInPlaceInternalizable(), IsOneByteRepresentationUnderneath(), IsWellFormedUnicode(), v8::internal::ExternalString::BodyDescriptor::IterateBody(), v8::internal::ConsStringIterator::PushLeft(), and TryGetFlatContentFromDirectString().
subject
HandleType<String> v8::internal::String::subject
Definition at line 275 of file string.h.
Referenced by AddressOfCharacterAt().
V8_OBJECT_INNER_CLASS_END
V8_OBJECT_INNER_CLASS class v8::internal::String::FlatContent v8::internal::String::V8_OBJECT_INNER_CLASS_END
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/string.h
/mnt/V8SourceCode/src/objects/string-inl.h
/mnt/V8SourceCode/src/objects/string.cc