v8::internal::NestedTimedHistogram Class Reference
#include <counters.h>
Public Member Functions
NestedTimedHistogram (const char *name, int min, int max, TimedHistogramResolution resolution, int num_buckets, Counters *counters)
Private Member Functions
NestedTimedHistogramScope * Enter (NestedTimedHistogramScope *next)
void Leave (NestedTimedHistogramScope *previous)
NestedTimedHistogram ()=default
NestedTimedHistogram (const NestedTimedHistogram &)=delete
NestedTimedHistogram & operator= (const NestedTimedHistogram &)=delete
Private Attributes
NestedTimedHistogramScope * current_ = nullptr
Friends
class Counters
class NestedTimedHistogramScope
class PauseNestedTimedHistogramScope
Additional Inherited Members
Detailed Description
Definition at line 284 of file counters.h.
Constructor & Destructor Documentation
NestedTimedHistogram() [1/3]
v8::internal::NestedTimedHistogram::NestedTimedHistogram (const char * name, int min, int max, TimedHistogramResolution resolution, int num_buckets, Counters * counters) [inline]
Definition at line 287 of file counters.h.
      : NestedTimedHistogram() {
    Initialize(name, min, max, resolution, num_buckets, counters);
  }
References v8::internal::Histogram::counters(), v8::internal::TimedHistogram::Initialize(), v8::internal::Histogram::max(), v8::internal::Histogram::min(), v8::internal::Histogram::name(), and v8::internal::Histogram::num_buckets().
NestedTimedHistogram() [2/3]
v8::internal::NestedTimedHistogram::NestedTimedHistogram () [private], [default]
NestedTimedHistogram() [3/3]
v8::internal::NestedTimedHistogram::NestedTimedHistogram (const NestedTimedHistogram &) [private], [delete]
Member Function Documentation
Enter()
NestedTimedHistogramScope* v8::internal::NestedTimedHistogram::Enter (NestedTimedHistogramScope * next) [inline], [private]
Definition at line 299 of file counters.h.
                                                                           {
    NestedTimedHistogramScope* previous = current_;
    current_ = next;
    return previous;
  }
References current_.
Leave()
void v8::internal::NestedTimedHistogram::Leave (NestedTimedHistogramScope * previous) [inline], [private]
Definition at line 305 of file counters.h.
                                                         {
    current_ = previous;
  }
References current_.
operator=()
NestedTimedHistogram& v8::internal::NestedTimedHistogram::operator= (const NestedTimedHistogram &) [private], [delete]
Friends And Related Function Documentation
Counters
friend class Counters [friend]
Definition at line 295 of file counters.h.
NestedTimedHistogramScope
friend class NestedTimedHistogramScope [friend]
Definition at line 296 of file counters.h.
PauseNestedTimedHistogramScope
friend class PauseNestedTimedHistogramScope [friend]
Definition at line 297 of file counters.h.
Member Data Documentation
current_
NestedTimedHistogramScope* v8::internal::NestedTimedHistogram::current_ = nullptr [private]
Definition at line 309 of file counters.h.
Referenced by Enter(), and Leave().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/logging/counters.h