v8::internal::wasm::anonymous_namespace{module-decoder.cc}::ValidateFunctionsTask Class Reference
Public Member Functions
ValidateFunctionsTask (base::Vector< const uint8_t > wire_bytes, const WasmModule *module, WasmEnabledFeatures enabled_features, std::function< bool(int)> filter, WasmError *error_out, std::atomic< WasmDetectedFeatures > *detected_features)
void Run (JobDelegate *delegate) override
size_t GetMaxConcurrency (size_t) const override
Controls the maximum number of threads calling Run() concurrently, given the number of threads currently assigned to this job and executing Run().
Private Member Functions
bool ValidateFunction (int func_index, Zone *zone, WasmDetectedFeatures *detected_features)
void SetError (int func_index, WasmError error)
void UpdateDetectedFeatures (WasmDetectedFeatures detected_features)
Private Attributes
const base::Vector< const uint8_t > wire_bytes_
const WasmModule *const module_
const WasmEnabledFeatures enabled_features_
const std::function< bool(int)> filter_
std::atomic< int > next_function_
const int after_last_function_
base::Mutex set_error_mutex_
WasmError *const error_out_
std::atomic< WasmDetectedFeatures > *const detected_features_
Detailed Description
Definition at line 513 of file module-decoder.cc.
Constructor & Destructor Documentation
ValidateFunctionsTask()
v8::internal::wasm::anonymous_namespace{module-decoder.cc}::ValidateFunctionsTask::ValidateFunctionsTask (base::Vector< const uint8_t > wire_bytes, const WasmModule * module, WasmEnabledFeatures enabled_features, std::function< bool(int)> filter, WasmError * error_out, std::atomic< WasmDetectedFeatures > * detected_features) [inline], [explicit]
Definition at line 515 of file module-decoder.cc.
      : wire_bytes_(wire_bytes),
        module_(module),
        enabled_features_(enabled_features),
        filter_(std::move(filter)),
        next_function_(module->num_imported_functions),
        after_last_function_(next_function_ + module->num_declared_functions),
        error_out_(error_out),
        detected_features_(detected_features) {
    DCHECK(!error_out->has_error());
  }
References v8::internal::DCHECK(), and v8::internal::wasm::WasmError::has_error().
Member Function Documentation
GetMaxConcurrency()
size_t v8::internal::wasm::anonymous_namespace{module-decoder.cc}::ValidateFunctionsTask::GetMaxConcurrency (size_t worker_count) const [inline], [override], [virtual]
Controls the maximum number of threads calling Run() concurrently, given the number of threads currently assigned to this job and executing Run().
Run() is only invoked if the number of threads previously running Run() was less than the value returned. In general, this should return the latest number of incomplete work items (smallest unit of work) left to process, including items that are currently in progress. |worker_count| is the number of threads currently assigned to this job which some callers may need to determine their return value. Since GetMaxConcurrency() is a leaf function, it must not call back any JobHandle methods.
Implements v8::JobTask.
Definition at line 564 of file module-decoder.cc.
                                                    {
    int next_func = next_function_.load(std::memory_order_relaxed);
    return std::max(0, after_last_function_ - next_func);
  }
Run()
void v8::internal::wasm::anonymous_namespace{module-decoder.cc}::ValidateFunctionsTask::Run (JobDelegate * delegate) [inline], [override], [virtual]
Implements v8::JobTask.
Definition at line 531 of file module-decoder.cc.
                                           {
    TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.wasm.detailed"),
                 "wasm.ValidateFunctionsTask");
    WasmDetectedFeatures detected_features;
    Zone zone(GetWasmEngine()->allocator(), ZONE_NAME);
    do {
      // Get the index of the next function to validate.
      // {fetch_add} might overrun {after_last_function_} by a bit. Since the
      // number of functions is limited to a value much smaller than the
      // integer range, this is near impossible to happen.
      static_assert(kV8MaxWasmTotalFunctions < kMaxInt / 2);
      int func_index;
      do {
        func_index = next_function_.fetch_add(1, std::memory_order_relaxed);
        if (V8_UNLIKELY(func_index >= after_last_function_)) {
          UpdateDetectedFeatures(detected_features);
          return;
        }
        DCHECK_LE(0, func_index);
      } while ((filter_ && !filter_(func_index)) ||
               module_->function_was_validated(func_index));
      zone.Reset();
      if (!ValidateFunction(func_index, &zone, &detected_features)) {
        // No need to validate any more functions.
        next_function_.store(after_last_function_, std::memory_order_relaxed);
        return;
      }
    } while (!delegate->ShouldYield());
    UpdateDetectedFeatures(detected_features);
  }
References DCHECK_LE, v8::internal::wasm::GetWasmEngine(), v8::internal::kMaxInt, v8::internal::wasm::kV8MaxWasmTotalFunctions, v8::internal::Zone::Reset(), v8::JobDelegate::ShouldYield(), TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT0, V8_UNLIKELY, and ZONE_NAME.
SetError()
void v8::internal::wasm::anonymous_namespace{module-decoder.cc}::ValidateFunctionsTask::SetError (int func_index, WasmError error) [inline], [private]
Definition at line 591 of file module-decoder.cc.
                                                 {
    base::MutexGuard mutex_guard{&set_error_mutex_};
    if (error_out_->has_error() && error_out_->offset() <= error.offset()) {
      return;
    }
    *error_out_ = GetWasmErrorWithName(wire_bytes_, func_index, module_, error);
  }
References v8::internal::wasm::GetWasmErrorWithName(), and v8::internal::wasm::WasmError::offset().
UpdateDetectedFeatures()
void v8::internal::wasm::anonymous_namespace{module-decoder.cc}::ValidateFunctionsTask::UpdateDetectedFeatures (WasmDetectedFeatures detected_features) [inline], [private]
Definition at line 599 of file module-decoder.cc.
                                                                      {
    WasmDetectedFeatures old_features =
        detected_features_->load(std::memory_order_relaxed);
    while (!detected_features_->compare_exchange_weak(
        old_features, old_features | detected_features,
        std::memory_order_relaxed)) {
      // Retry with updated {old_features}.
    }
  }
ValidateFunction()
bool v8::internal::wasm::anonymous_namespace{module-decoder.cc}::ValidateFunctionsTask::ValidateFunction (int func_index, Zone * zone, WasmDetectedFeatures * detected_features) [inline], [private]
Definition at line 570 of file module-decoder.cc.
                                                                 {
    const WasmFunction& function = module_->functions[func_index];
    DCHECK_LT(0, function.code.offset());
    bool is_shared = module_->type(function.sig_index).is_shared;
    FunctionBody body{function.sig, function.code.offset(),
                      wire_bytes_.begin() + function.code.offset(),
                      wire_bytes_.begin() + function.code.end_offset(),
                      is_shared};
    DecodeResult validation_result = ValidateFunctionBody(
        zone, enabled_features_, module_, detected_features, body);
    if (V8_UNLIKELY(validation_result.failed())) {
      SetError(func_index, std::move(validation_result).error());
      return false;
    }
    module_->set_function_validated(func_index);
    return true;
  }
References code, DCHECK_LT, v8::internal::wasm::Result< T >::failed(), v8::internal::is_shared, v8::internal::wasm::FunctionBody::sig, V8_UNLIKELY, and v8::internal::wasm::ValidateFunctionBody().
Member Data Documentation
after_last_function_
const int v8::internal::wasm::anonymous_namespace{module-decoder.cc}::ValidateFunctionsTask::after_last_function_ [private]
Definition at line 614 of file module-decoder.cc.
detected_features_
std::atomic<WasmDetectedFeatures>* const v8::internal::wasm::anonymous_namespace{module-decoder.cc}::ValidateFunctionsTask::detected_features_ [private]
Definition at line 617 of file module-decoder.cc.
enabled_features_
const WasmEnabledFeatures v8::internal::wasm::anonymous_namespace{module-decoder.cc}::ValidateFunctionsTask::enabled_features_ [private]
Definition at line 611 of file module-decoder.cc.
error_out_
WasmError* const v8::internal::wasm::anonymous_namespace{module-decoder.cc}::ValidateFunctionsTask::error_out_ [private]
Definition at line 616 of file module-decoder.cc.
filter_
const std::function<bool(int)> v8::internal::wasm::anonymous_namespace{module-decoder.cc}::ValidateFunctionsTask::filter_ [private]
Definition at line 612 of file module-decoder.cc.
module_
const WasmModule* const v8::internal::wasm::anonymous_namespace{module-decoder.cc}::ValidateFunctionsTask::module_ [private]
Definition at line 610 of file module-decoder.cc.
next_function_
std::atomic<int> v8::internal::wasm::anonymous_namespace{module-decoder.cc}::ValidateFunctionsTask::next_function_ [private]
Definition at line 613 of file module-decoder.cc.
set_error_mutex_
base::Mutex v8::internal::wasm::anonymous_namespace{module-decoder.cc}::ValidateFunctionsTask::set_error_mutex_ [private]
Definition at line 615 of file module-decoder.cc.
wire_bytes_
const base::Vector<const uint8_t> v8::internal::wasm::anonymous_namespace{module-decoder.cc}::ValidateFunctionsTask::wire_bytes_ [private]
Definition at line 609 of file module-decoder.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/module-decoder.cc