v8::internal::wasm::WasmInitExpr Class Reference
#include <wasm-init-expr.h>
Classes
union Immediate
Public Types
enum Operator {
kGlobalGet
, kI32Const
, kI64Const
, kF32Const
,
kF64Const
, kS128Const
, kI32Add
, kI32Sub
,
kI32Mul
, kI64Add
, kI64Sub
, kI64Mul
,
kRefNullConst
, kRefFuncConst
, kStructNew
, kStructNewDefault
,
kArrayNew
, kArrayNewDefault
, kArrayNewFixed
, kRefI31
,
kStringConst
, kAnyConvertExtern
, kExternConvertAny
 }
Public Member Functions
WasmInitExpr (int32_t v)
WasmInitExpr (int64_t v)
WasmInitExpr (float v)
WasmInitExpr (double v)
WasmInitExpr (uint8_t v[kSimd128Size])
HeapType heap_type () const
Immediate immediate () const
Operator kind () const
const ZoneVector< WasmInitExpr > * operands () const
bool operator== (const WasmInitExpr &other) const
Static Public Member Functions
static WasmInitExpr Binop (Zone *zone, Operator op, WasmInitExpr lhs, WasmInitExpr rhs)
static WasmInitExpr GlobalGet (uint32_t index)
static WasmInitExpr RefFuncConst (uint32_t index)
static WasmInitExpr RefNullConst (HeapType heap_type)
static WasmInitExpr StructNew (ModuleTypeIndex index, ZoneVector< WasmInitExpr > *elements)
static WasmInitExpr StructNewDefault (ModuleTypeIndex index)
static WasmInitExpr ArrayNew (Zone *zone, ModuleTypeIndex index, WasmInitExpr initial, WasmInitExpr length)
static WasmInitExpr ArrayNewDefault (Zone *zone, ModuleTypeIndex index, WasmInitExpr length)
static WasmInitExpr ArrayNewFixed (ModuleTypeIndex index, ZoneVector< WasmInitExpr > *elements)
static WasmInitExpr RefI31 (Zone *zone, WasmInitExpr value)
static WasmInitExpr StringConst (uint32_t index)
static WasmInitExpr AnyConvertExtern (Zone *zone, WasmInitExpr arg)
static WasmInitExpr ExternConvertAny (Zone *zone, WasmInitExpr arg)
static WasmInitExpr DefaultValue (ValueType type)
Private Member Functions
WasmInitExpr (Operator kind, const ZoneVector< WasmInitExpr > *operands)
WasmInitExpr (Operator kind)
WasmInitExpr (Zone *zone, Operator kind, std::initializer_list< WasmInitExpr > operands)
Private Attributes
Immediate immediate_
Operator kind_
const ZoneVector< WasmInitExpr > * operands_
Detailed Description
Definition at line 26 of file wasm-init-expr.h.
Member Enumeration Documentation
Operator
enum v8::internal::wasm::WasmInitExpr::Operator
Enumerator
kGlobalGet
kI32Const
kI64Const
kF32Const
kF64Const
kS128Const
kI32Add
kI32Sub
kI32Mul
kI64Add
kI64Sub
kI64Mul
kRefNullConst
kRefFuncConst
kStructNew
kStructNewDefault
kArrayNew
kArrayNewDefault
kArrayNewFixed
kRefI31
kStringConst
kAnyConvertExtern
kExternConvertAny
Definition at line 28 of file wasm-init-expr.h.
                {
    kGlobalGet,
    kI32Const,
    kI64Const,
    kF32Const,
    kF64Const,
    kS128Const,
    kI32Add,
    kI32Sub,
    kI32Mul,
    kI64Add,
    kI64Sub,
    kI64Mul,
    kRefNullConst,
    kRefFuncConst,
    kStructNew,
    kStructNewDefault,
    kArrayNew,
    kArrayNewDefault,
    kArrayNewFixed,
    kRefI31,
    kStringConst,
    kAnyConvertExtern,
    kExternConvertAny
  };
Constructor & Destructor Documentation
WasmInitExpr() [1/8]
v8::internal::wasm::WasmInitExpr::WasmInitExpr (int32_t v) [inline], [explicit]
Definition at line 64 of file wasm-init-expr.h.
                                   : kind_(kI32Const), operands_(nullptr) {
    immediate_.i32_const = v;
  }
References v8::internal::wasm::WasmInitExpr::Immediate::i32_const, and immediate_.
Referenced by AnyConvertExtern(), Binop(), DefaultValue(), and ExternConvertAny().
WasmInitExpr() [2/8]
v8::internal::wasm::WasmInitExpr::WasmInitExpr (int64_t v) [inline], [explicit]
Definition at line 67 of file wasm-init-expr.h.
                                   : kind_(kI64Const), operands_(nullptr) {
    immediate_.i64_const = v;
  }
References v8::internal::wasm::WasmInitExpr::Immediate::i64_const, and immediate_.
WasmInitExpr() [3/8]
v8::internal::wasm::WasmInitExpr::WasmInitExpr (float v) [inline], [explicit]
Definition at line 70 of file wasm-init-expr.h.
                                 : kind_(kF32Const), operands_(nullptr) {
    immediate_.f32_const = v;
  }
References v8::internal::wasm::WasmInitExpr::Immediate::f32_const, and immediate_.
WasmInitExpr() [4/8]
v8::internal::wasm::WasmInitExpr::WasmInitExpr (double v) [inline], [explicit]
Definition at line 73 of file wasm-init-expr.h.
                                  : kind_(kF64Const), operands_(nullptr) {
    immediate_.f64_const = v;
  }
References v8::internal::wasm::WasmInitExpr::Immediate::f64_const, and immediate_.
WasmInitExpr() [5/8]
v8::internal::wasm::WasmInitExpr::WasmInitExpr (uint8_t v[kSimd128Size]) [inline], [explicit]
Definition at line 76 of file wasm-init-expr.h.
      : kind_(kS128Const), operands_(nullptr) {
    memcpy(immediate_.s128_const.data(), v, kSimd128Size);
  }
References immediate_, v8::internal::kSimd128Size, and v8::internal::wasm::WasmInitExpr::Immediate::s128_const.
WasmInitExpr() [6/8]
v8::internal::wasm::WasmInitExpr::WasmInitExpr (Operator kind, const ZoneVector< WasmInitExpr > * operands) [inline], [private]
Definition at line 247 of file wasm-init-expr.h.
      : kind_(kind), operands_(operands) {}
WasmInitExpr() [7/8]
v8::internal::wasm::WasmInitExpr::WasmInitExpr (Operator kind) [inline], [explicit], [private]
Definition at line 249 of file wasm-init-expr.h.
: kind_(kind), operands_(nullptr) {}
WasmInitExpr() [8/8]
v8::internal::wasm::WasmInitExpr::WasmInitExpr (Zone * zone, Operator kind, std::initializer_list< WasmInitExpr > operands) [inline], [private]
Definition at line 250 of file wasm-init-expr.h.
      : kind_(kind),
        operands_(zone->New<ZoneVector<WasmInitExpr>>(operands, zone)) {}
Member Function Documentation
AnyConvertExtern()
static WasmInitExpr v8::internal::wasm::WasmInitExpr::AnyConvertExtern (Zone * zone, WasmInitExpr arg) [inline], [static]
Definition at line 155 of file wasm-init-expr.h.
                                                                     {
    return WasmInitExpr(zone, kAnyConvertExtern, {arg});
  }
References kAnyConvertExtern, and WasmInitExpr().
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateInitExpr().
ArrayNew()
static WasmInitExpr v8::internal::wasm::WasmInitExpr::ArrayNew (Zone * zone, ModuleTypeIndex index, WasmInitExpr initial, WasmInitExpr length) [inline], [static]
Definition at line 123 of file wasm-init-expr.h.
                                                                          {
    WasmInitExpr expr(zone, kArrayNew, {initial, length});
    expr.immediate_.index = index.index;
    return expr;
  }
References immediate_, v8::internal::index, v8::internal::wasm::WasmInitExpr::Immediate::index, kArrayNew, and v8::internal::length.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateArrayInitExpr().
ArrayNewDefault()
static WasmInitExpr v8::internal::wasm::WasmInitExpr::ArrayNewDefault (Zone * zone, ModuleTypeIndex index, WasmInitExpr length) [inline], [static]
Definition at line 130 of file wasm-init-expr.h.
                                                           {
    WasmInitExpr expr(zone, kArrayNewDefault, {length});
    expr.immediate_.index = index.index;
    return expr;
  }
References immediate_, v8::internal::index, v8::internal::wasm::WasmInitExpr::Immediate::index, kArrayNewDefault, and v8::internal::length.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateArrayInitExpr().
ArrayNewFixed()
static WasmInitExpr v8::internal::wasm::WasmInitExpr::ArrayNewFixed (ModuleTypeIndex index, ZoneVector< WasmInitExpr > * elements) [inline], [static]
Definition at line 137 of file wasm-init-expr.h.
                                                                        {
    WasmInitExpr expr(kArrayNewFixed, elements);
    expr.immediate_.index = index.index;
    return expr;
  }
References immediate_, v8::internal::index, v8::internal::wasm::WasmInitExpr::Immediate::index, and kArrayNewFixed.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateArrayInitExpr().
Binop()
static WasmInitExpr v8::internal::wasm::WasmInitExpr::Binop (Zone * zone, Operator op, WasmInitExpr lhs, WasmInitExpr rhs) [inline], [static]
Definition at line 85 of file wasm-init-expr.h.
                                              {
    DCHECK(op == kI32Add || op == kI32Sub || op == kI32Mul || op == kI64Add ||
           op == kI64Sub || op == kI64Mul);
    return WasmInitExpr(zone, op, {lhs, rhs});
  }
References v8::internal::DCHECK(), kI32Add, kI32Mul, kI32Sub, kI64Add, kI64Mul, kI64Sub, and WasmInitExpr().
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateInitExpr().
DefaultValue()
static WasmInitExpr v8::internal::wasm::WasmInitExpr::DefaultValue (ValueType type) [inline], [static]
Definition at line 218 of file wasm-init-expr.h.
                                                   {
    // No initializer, emit a default value.
    switch (type.kind()) {
      case kI8:
      case kI16:
      case kI32:
        return WasmInitExpr(int32_t{0});
      case kI64:
        return WasmInitExpr(int64_t{0});
      case kF16:
      case kF32:
        return WasmInitExpr(0.0f);
      case kF64:
        return WasmInitExpr(0.0);
      case kRefNull:
        return WasmInitExpr::RefNullConst(type.heap_type());
      case kS128: {
        uint8_t value[kSimd128Size] = {0};
        return WasmInitExpr(value);
      }
      case kVoid:
      case kTop:
      case kBottom:
      case kRef:
        UNREACHABLE();
    }
  }
References v8::internal::kF32, v8::internal::kF64, v8::internal::kI16, v8::internal::kI32, v8::internal::kI64, v8::internal::kI8, v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, v8::internal::kSimd128Size, RefNullConst(), v8::internal::tracing::type, v8::internal::UNREACHABLE(), v8::internal::value, and WasmInitExpr().
Referenced by v8::internal::wasm::AsmJsParser::AddGlobalImport().
ExternConvertAny()
static WasmInitExpr v8::internal::wasm::WasmInitExpr::ExternConvertAny (Zone * zone, WasmInitExpr arg) [inline], [static]
Definition at line 159 of file wasm-init-expr.h.
                                                                     {
    return WasmInitExpr(zone, kExternConvertAny, {arg});
  }
References kExternConvertAny, and WasmInitExpr().
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateInitExpr().
GlobalGet()
static WasmInitExpr v8::internal::wasm::WasmInitExpr::GlobalGet (uint32_t index) [inline], [static]
Definition at line 92 of file wasm-init-expr.h.
                                                {
    WasmInitExpr expr(kGlobalGet);
    expr.immediate_.index = index;
    return expr;
  }
References immediate_, v8::internal::index, v8::internal::wasm::WasmInitExpr::Immediate::index, and kGlobalGet.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateInitExpr().
heap_type()
HeapType v8::internal::wasm::WasmInitExpr::heap_type () const [inline]
Definition at line 81 of file wasm-init-expr.h.
                             {
    return HeapType::FromBits(immediate_.heap_type_);
  }
References v8::internal::wasm::HeapType::FromBits(), v8::internal::wasm::WasmInitExpr::Immediate::heap_type_, and immediate_.
Referenced by operator==(), RefNullConst(), and v8::internal::wasm::anonymous_namespace{wasm-module-builder.cc}::WriteInitializerExpressionWithoutEnd().
immediate()
Immediate v8::internal::wasm::WasmInitExpr::immediate () const [inline]
Definition at line 163 of file wasm-init-expr.h.
{ return immediate_; }
References immediate_.
Referenced by operator==(), and v8::internal::wasm::anonymous_namespace{wasm-module-builder.cc}::WriteInitializerExpressionWithoutEnd().
kind()
Operator v8::internal::wasm::WasmInitExpr::kind () const [inline]
Definition at line 164 of file wasm-init-expr.h.
{ return kind_; }
References kind_.
Referenced by operator==(), v8::internal::wasm::WasmModuleBuilder::WasmElemSegment::WasmElemSegment(), and v8::internal::wasm::anonymous_namespace{wasm-module-builder.cc}::WriteInitializerExpressionWithoutEnd().
operands()
const ZoneVector<WasmInitExpr>* v8::internal::wasm::WasmInitExpr::operands () const [inline]
Definition at line 165 of file wasm-init-expr.h.
{ return operands_; }
References operands_.
Referenced by operator==(), and v8::internal::wasm::anonymous_namespace{wasm-module-builder.cc}::WriteInitializerExpressionWithoutEnd().
operator==()
bool v8::internal::wasm::WasmInitExpr::operator== (const WasmInitExpr & other) const [inline]
Definition at line 167 of file wasm-init-expr.h.
                                                   {
    if (kind() != other.kind()) return false;
    switch (kind()) {
      case kGlobalGet:
      case kRefFuncConst:
      case kStringConst:
        return immediate().index == other.immediate().index;
      case kI32Const:
        return immediate().i32_const == other.immediate().i32_const;
      case kI64Const:
        return immediate().i64_const == other.immediate().i64_const;
      case kF32Const:
        return immediate().f32_const == other.immediate().f32_const;
      case kF64Const:
        return immediate().f64_const == other.immediate().f64_const;
      case kI32Add:
      case kI32Sub:
      case kI32Mul:
      case kI64Add:
      case kI64Sub:
      case kI64Mul:
        return operands_[0] == other.operands_[0] &&
               operands_[1] == other.operands_[1];
      case kS128Const:
        return immediate().s128_const == other.immediate().s128_const;
      case kRefNullConst:
        return heap_type() == other.heap_type();
      case kStructNew:
      case kStructNewDefault:
      case kArrayNew:
      case kArrayNewDefault:
        if (immediate().index != other.immediate().index) return false;
        DCHECK_EQ(operands()->size(), other.operands()->size());
        for (uint32_t i = 0; i < operands()->size(); i++) {
          if (operands()[i] != other.operands()[i]) return false;
        }
        return true;
      case kArrayNewFixed:
        if (immediate().index != other.immediate().index) return false;
        if (operands()->size() != other.operands()->size()) return false;
        for (uint32_t i = 0; i < operands()->size(); i++) {
          if (operands()[i] != other.operands()[i]) return false;
        }
        return true;
      case kRefI31:
      case kAnyConvertExtern:
      case kExternConvertAny:
        return operands_[0] == other.operands_[0];
    }
  }
References DCHECK_EQ, v8::internal::wasm::WasmInitExpr::Immediate::f32_const, v8::internal::wasm::WasmInitExpr::Immediate::f64_const, heap_type(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::WasmInitExpr::Immediate::i32_const, v8::internal::wasm::WasmInitExpr::Immediate::i64_const, immediate(), v8::internal::index, v8::internal::wasm::WasmInitExpr::Immediate::index, kAnyConvertExtern, kArrayNew, kArrayNewDefault, kArrayNewFixed, kExternConvertAny, kF32Const, kF64Const, kGlobalGet, kI32Add, kI32Const, kI32Mul, kI32Sub, kI64Add, kI64Const, kI64Mul, kI64Sub, kind(), kRefFuncConst, kRefI31, kRefNullConst, kS128Const, kStringConst, kStructNew, kStructNewDefault, operands(), operands_, v8::internal::wasm::WasmInitExpr::Immediate::s128_const, and size().
RefFuncConst()
static WasmInitExpr v8::internal::wasm::WasmInitExpr::RefFuncConst (uint32_t index) [inline], [static]
Definition at line 98 of file wasm-init-expr.h.
                                                   {
    WasmInitExpr expr(kRefFuncConst);
    expr.immediate_.index = index;
    return expr;
  }
References immediate_, v8::internal::index, v8::internal::wasm::WasmInitExpr::Immediate::index, and kRefFuncConst.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateInitExpr().
RefI31()
static WasmInitExpr v8::internal::wasm::WasmInitExpr::RefI31 (Zone * zone, WasmInitExpr value) [inline], [static]
Definition at line 144 of file wasm-init-expr.h.
                                                             {
    WasmInitExpr expr(zone, kRefI31, {value});
    return expr;
  }
References kRefI31, and v8::internal::value.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateInitExpr().
RefNullConst()
static WasmInitExpr v8::internal::wasm::WasmInitExpr::RefNullConst (HeapType heap_type) [inline], [static]
Definition at line 104 of file wasm-init-expr.h.
                                                       {
    WasmInitExpr expr(kRefNullConst);
    expr.immediate_.heap_type_ = heap_type.raw_bit_field();
    return expr;
  }
References heap_type(), v8::internal::wasm::WasmInitExpr::Immediate::heap_type_, immediate_, kRefNullConst, and v8::internal::wasm::ValueTypeBase::raw_bit_field().
Referenced by DefaultValue(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateInitExpr(), and v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateRefTypeElementSegment().
StringConst()
static WasmInitExpr v8::internal::wasm::WasmInitExpr::StringConst (uint32_t index) [inline], [static]
Definition at line 149 of file wasm-init-expr.h.
                                                  {
    WasmInitExpr expr(kStringConst);
    expr.immediate_.index = index;
    return expr;
  }
References immediate_, v8::internal::index, v8::internal::wasm::WasmInitExpr::Immediate::index, and kStringConst.
StructNew()
static WasmInitExpr v8::internal::wasm::WasmInitExpr::StructNew (ModuleTypeIndex index, ZoneVector< WasmInitExpr > * elements) [inline], [static]
Definition at line 110 of file wasm-init-expr.h.
                                                                    {
    WasmInitExpr expr(kStructNew, elements);
    expr.immediate_.index = index.index;
    return expr;
  }
References immediate_, v8::internal::index, v8::internal::wasm::WasmInitExpr::Immediate::index, and kStructNew.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateStructNewInitExpr().
StructNewDefault()
static WasmInitExpr v8::internal::wasm::WasmInitExpr::StructNewDefault (ModuleTypeIndex index) [inline], [static]
Definition at line 117 of file wasm-init-expr.h.
                                                              {
    WasmInitExpr expr(kStructNewDefault);
    expr.immediate_.index = index.index;
    return expr;
  }
References immediate_, v8::internal::index, v8::internal::wasm::WasmInitExpr::Immediate::index, and kStructNewDefault.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateStructNewInitExpr().
Member Data Documentation
immediate_
Immediate v8::internal::wasm::WasmInitExpr::immediate_ [private]
Definition at line 254 of file wasm-init-expr.h.
Referenced by ArrayNew(), ArrayNewDefault(), ArrayNewFixed(), GlobalGet(), heap_type(), immediate(), RefFuncConst(), RefNullConst(), StringConst(), StructNew(), StructNewDefault(), and WasmInitExpr().
kind_
Operator v8::internal::wasm::WasmInitExpr::kind_ [private]
Definition at line 255 of file wasm-init-expr.h.
Referenced by kind().
operands_
const ZoneVector<WasmInitExpr>* v8::internal::wasm::WasmInitExpr::operands_ [private]
Definition at line 256 of file wasm-init-expr.h.
Referenced by operands(), and operator==().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/wasm-init-expr.h