v8::internal::SamplingHeapProfiler Class Reference
#include <sampling-heap-profiler.h>
Classes
class AllocationNode
class Observer
struct Sample
Public Member Functions
SamplingHeapProfiler (Heap *heap, StringsStorage *names, uint64_t rate, int stack_depth, v8::HeapProfiler::SamplingFlags flags)
~SamplingHeapProfiler ()
SamplingHeapProfiler (const SamplingHeapProfiler &)=delete
SamplingHeapProfiler & operator= (const SamplingHeapProfiler &)=delete
v8::AllocationProfile * GetAllocationProfile ()
StringsStorage * names () const
Private Member Functions
void SampleObject (Address soon_object, size_t size)
const std::vector< v8::AllocationProfile::Sample > BuildSamples () const
AllocationNode * FindOrAddChildNode (AllocationNode *parent, const char *name, int script_id, int start_position)
uint32_t next_node_id ()
uint64_t next_sample_id ()
v8::AllocationProfile::Node * TranslateAllocationNode (AllocationProfile *profile, SamplingHeapProfiler::AllocationNode *node, const std::map< int, Handle< Script >> &scripts)
v8::AllocationProfile::Allocation ScaleSample (size_t size, unsigned int count) const
AllocationNode * AddStack ()
Static Private Member Functions
static void OnWeakCallback (const WeakCallbackInfo< Sample > &data)
Private Attributes
Isolate *const isolate_
Heap *const heap_
uint64_t last_sample_id_ = 0
uint32_t last_node_id_ = 0
Observer allocation_observer_
StringsStorage *const names_
AllocationNode profile_root_
std::unordered_map< Sample *, std::unique_ptr< Sample > > samples_
const int stack_depth_
const uint64_t rate_
v8::HeapProfiler::SamplingFlags flags_
Detailed Description
Definition at line 46 of file sampling-heap-profiler.h.
Constructor & Destructor Documentation
SamplingHeapProfiler() [1/2]
v8::internal::SamplingHeapProfiler::SamplingHeapProfiler (Heap * heap, StringsStorage * names, uint64_t rate, int stack_depth, v8::HeapProfiler::SamplingFlags flags)
Definition at line 53 of file sampling-heap-profiler.cc.
    : isolate_(Isolate::FromHeap(heap)),
      heap_(heap),
      allocation_observer_(heap_, static_cast<intptr_t>(rate), rate, this,
                           isolate_->random_number_generator()),
      names_(names),
      profile_root_(nullptr, "(root)", v8::UnboundScript::kNoScriptId, 0,
                    next_node_id()),
      stack_depth_(stack_depth),
      rate_(rate),
      flags_(flags) {
  CHECK_GT(rate_, 0u);
  heap_->AddAllocationObserversToAllSpaces(&allocation_observer_,
                                           &allocation_observer_);
}
References v8::internal::Heap::AddAllocationObserversToAllSpaces(), allocation_observer_, CHECK_GT, heap_, and rate_.
 SamplingHeapProfiler()
v8::internal::SamplingHeapProfiler::~SamplingHeapProfiler ()
Definition at line 71 of file sampling-heap-profiler.cc.
                                            {
  heap_->RemoveAllocationObserversFromAllSpaces(&allocation_observer_,
                                                &allocation_observer_);
}
References allocation_observer_, heap_, and v8::internal::Heap::RemoveAllocationObserversFromAllSpaces().
SamplingHeapProfiler() [2/2]
v8::internal::SamplingHeapProfiler::SamplingHeapProfiler (const SamplingHeapProfiler &) [delete]
Member Function Documentation
AddStack()
SamplingHeapProfiler::AllocationNode * v8::internal::SamplingHeapProfiler::AddStack () [private]
Definition at line 153 of file sampling-heap-profiler.cc.
                                                                   {
  AllocationNode* node = &profile_root_;
  std::vector<Tagged<SharedFunctionInfo>> stack;
  JavaScriptStackFrameIterator frame_it(isolate_);
  int frames_captured = 0;
  bool found_arguments_marker_frames = false;
  while (!frame_it.done() && frames_captured < stack_depth_) {
    JavaScriptFrame* frame = frame_it.frame();
    // If we are materializing objects during deoptimization, inlined
    // closures may not yet be materialized, and this includes the
    // closure on the stack. Skip over any such frames (they'll be
    // in the top frames of the stack). The allocations made in this
    // sensitive moment belong to the formerly optimized frame anyway.
    if (IsJSFunction(frame->unchecked_function())) {
      Tagged<SharedFunctionInfo> shared = frame->function()->shared();
      stack.push_back(shared);
      frames_captured++;
    } else {
      found_arguments_marker_frames = true;
    }
    frame_it.Advance();
  }
  if (frames_captured == 0) {
    const char* name = nullptr;
    switch (isolate_->current_vm_state()) {
      case GC:
        name = "(GC)";
        break;
      case PARSER:
        name = "(PARSER)";
        break;
      case COMPILER:
        name = "(COMPILER)";
        break;
      case BYTECODE_COMPILER:
        name = "(BYTECODE_COMPILER)";
        break;
      case OTHER:
        name = "(V8 API)";
        break;
      case EXTERNAL:
        name = "(EXTERNAL)";
        break;
      case LOGGING:
        name = "(LOGGING)";
        break;
      case IDLE:
        name = "(IDLE)";
        break;
      // Treat atomics wait as a normal JS event; we don't care about the
      // difference for allocations.
      case ATOMICS_WAIT:
      case JS:
        name = "(JS)";
        break;
    }
    return FindOrAddChildNode(node, name, v8::UnboundScript::kNoScriptId, 0);
  }
  // We need to process the stack in reverse order as the top of the stack is
  // the first element in the list.
  for (auto it = stack.rbegin(); it != stack.rend(); ++it) {
    Tagged<SharedFunctionInfo> shared = *it;
    const char* name = this->names()->GetCopy(shared->DebugNameCStr().get());
    int script_id = v8::UnboundScript::kNoScriptId;
    if (IsScript(shared->script())) {
      Tagged<Script> script = Cast<Script>(shared->script());
      script_id = script->id();
    }
    node = FindOrAddChildNode(node, name, script_id, shared->StartPosition());
  }
  if (found_arguments_marker_frames) {
    node =
        FindOrAddChildNode(node, "(deopt)", v8::UnboundScript::kNoScriptId, 0);
  }
  return node;
}
References v8::internal::JavaScriptStackFrameIterator::Advance(), v8::ATOMICS_WAIT, v8::BYTECODE_COMPILER, v8::COMPILER, v8::internal::JavaScriptStackFrameIterator::done(), v8::EXTERNAL, FindOrAddChildNode(), v8::internal::JavaScriptStackFrameIterator::frame(), v8::internal::JavaScriptFrame::function(), v8::GC, v8::internal::StringsStorage::GetCopy(), v8::IDLE, isolate_, v8::JS, v8::UnboundScript::kNoScriptId, v8::LOGGING, v8::internal::name, names(), v8::OTHER, v8::PARSER, profile_root_, v8::internal::script, v8::internal::stack, stack_depth_, and v8::internal::JavaScriptFrame::unchecked_function().
Referenced by SampleObject().
BuildSamples()
const std::vector< v8::AllocationProfile::Sample > v8::internal::SamplingHeapProfiler::BuildSamples () const [private]
Definition at line 307 of file sampling-heap-profiler.cc.
                                         {
  std::vector<v8::AllocationProfile::Sample> samples;
  samples.reserve(samples_.size());
  for (const auto& it : samples_) {
    const Sample* sample = it.second.get();
    samples.emplace_back(v8::AllocationProfile::Sample{
        sample->owner->id_, sample->size, ScaleSample(sample->size, 1).count,
        sample->sample_id});
  }
  return samples;
}
References v8::AllocationProfile::Allocation::count, v8::internal::SamplingHeapProfiler::AllocationNode::id_, v8::internal::SamplingHeapProfiler::Sample::owner, v8::internal::SamplingHeapProfiler::Sample::sample_id, samples_, ScaleSample(), and v8::internal::SamplingHeapProfiler::Sample::size.
Referenced by GetAllocationProfile().
FindOrAddChildNode()
SamplingHeapProfiler::AllocationNode * v8::internal::SamplingHeapProfiler::FindOrAddChildNode (AllocationNode * parent, const char * name, int script_id, int start_position) [private]
Definition at line 138 of file sampling-heap-profiler.cc.
                        {
  AllocationNode::FunctionId id =
      AllocationNode::function_id(script_id, start_position, name);
  AllocationNode* child = parent->FindChildNode(id);
  if (child) {
    DCHECK_EQ(strcmp(child->name_, name), 0);
    return child;
  }
  auto new_child = std::make_unique<AllocationNode>(
      parent, name, script_id, start_position, next_node_id());
  return parent->AddChildNode(id, std::move(new_child));
}
References v8::internal::SamplingHeapProfiler::AllocationNode::AddChildNode(), DCHECK_EQ, v8::internal::SamplingHeapProfiler::AllocationNode::FindChildNode(), v8::internal::SamplingHeapProfiler::AllocationNode::function_id(), v8::internal::name, v8::internal::SamplingHeapProfiler::AllocationNode::name_, and next_node_id().
Referenced by AddStack().
GetAllocationProfile()
v8::AllocationProfile * v8::internal::SamplingHeapProfiler::GetAllocationProfile ()
Definition at line 284 of file sampling-heap-profiler.cc.
                                                                {
  if (flags_ & v8::HeapProfiler::kSamplingForceGC) {
    isolate_->heap()->CollectAllGarbage(
        GCFlag::kNoFlags, GarbageCollectionReason::kSamplingProfiler);
  }
  // To resolve positions to line/column numbers, we will need to look up
  // scripts. Build a map to allow fast mapping from script id to script.
  std::map<int, Handle<Script>> scripts;
  {
    Script::Iterator iterator(isolate_);
    for (Tagged<Script> script = iterator.Next(); !script.is_null();
         script = iterator.Next()) {
      scripts[script->id()] = handle(script, isolate_);
    }
  }
  auto profile = new v8::internal::AllocationProfile();
  TranslateAllocationNode(profile, &profile_root_, scripts);
  profile->samples_ = BuildSamples();
  return profile;
}
References BuildSamples(), v8::internal::Heap::CollectAllGarbage(), flags_, v8::internal::handle(), v8::internal::Isolate::heap(), isolate_, v8::internal::kNoFlags, v8::HeapProfiler::kSamplingForceGC, v8::internal::kSamplingProfiler, v8::internal::Script::Iterator::Next(), profile_root_, v8::internal::script, and TranslateAllocationNode().
names()
StringsStorage* v8::internal::SamplingHeapProfiler::names () const [inline]
Definition at line 126 of file sampling-heap-profiler.h.
{ return names_; }
References names_.
Referenced by AddStack().
next_node_id()
uint32_t v8::internal::SamplingHeapProfiler::next_node_id () [inline], [private]
Definition at line 169 of file sampling-heap-profiler.h.
{ return ++last_node_id_; }
References last_node_id_.
Referenced by FindOrAddChildNode().
next_sample_id()
uint64_t v8::internal::SamplingHeapProfiler::next_sample_id () [inline], [private]
Definition at line 170 of file sampling-heap-profiler.h.
{ return ++last_sample_id_; }
References last_sample_id_.
Referenced by SampleObject().
OnWeakCallback()
void v8::internal::SamplingHeapProfiler::OnWeakCallback (const WeakCallbackInfo< Sample > & data) [static], [private]
Definition at line 104 of file sampling-heap-profiler.cc.
                                          {
  Sample* sample = data.GetParameter();
  Heap* heap = reinterpret_cast<Isolate*>(data.GetIsolate())->heap();
  bool is_minor_gc = Heap::IsYoungGenerationCollector(
      heap->current_or_last_garbage_collector());
  bool should_keep_sample =
      is_minor_gc
          ? (sample->profiler->flags_ &
             v8::HeapProfiler::kSamplingIncludeObjectsCollectedByMinorGC)
          : (sample->profiler->flags_ &
             v8::HeapProfiler::kSamplingIncludeObjectsCollectedByMajorGC);
  if (should_keep_sample) {
    sample->global.Reset();
    return;
  }
  AllocationNode* node = sample->owner;
  DCHECK_GT(node->allocations_[sample->size], 0);
  node->allocations_[sample->size]--;
  if (node->allocations_[sample->size] == 0) {
    node->allocations_.erase(sample->size);
    while (node->allocations_.empty() && node->children_.empty() &&
           node->parent_ && !node->parent_->pinned_) {
      AllocationNode* parent = node->parent_;
      AllocationNode::FunctionId id = AllocationNode::function_id(
          node->script_id_, node->script_position_, node->name_);
      parent->children_.erase(id);
      node = parent;
    }
  }
  sample->profiler->samples_.erase(sample);
  // sample is deleted because its unique ptr was erased from samples_.
}
References v8::internal::SamplingHeapProfiler::AllocationNode::allocations_, v8::internal::SamplingHeapProfiler::AllocationNode::children_, DCHECK_GT, flags_, v8::internal::SamplingHeapProfiler::AllocationNode::function_id(), v8::WeakCallbackInfo< T >::GetIsolate(), v8::WeakCallbackInfo< T >::GetParameter(), v8::internal::SamplingHeapProfiler::Sample::global, heap(), v8::internal::Heap::IsYoungGenerationCollector(), v8::HeapProfiler::kSamplingIncludeObjectsCollectedByMajorGC, v8::HeapProfiler::kSamplingIncludeObjectsCollectedByMinorGC, v8::internal::SamplingHeapProfiler::AllocationNode::name_, v8::internal::SamplingHeapProfiler::Sample::owner, v8::internal::SamplingHeapProfiler::AllocationNode::parent_, v8::internal::SamplingHeapProfiler::AllocationNode::pinned_, v8::internal::SamplingHeapProfiler::Sample::profiler, samples_, v8::internal::SamplingHeapProfiler::AllocationNode::script_id_, v8::internal::SamplingHeapProfiler::AllocationNode::script_position_, and v8::internal::SamplingHeapProfiler::Sample::size.
Referenced by SampleObject().
operator=()
SamplingHeapProfiler& v8::internal::SamplingHeapProfiler::operator= (const SamplingHeapProfiler &) [delete]
SampleObject()
void v8::internal::SamplingHeapProfiler::SampleObject (Address soon_object, size_t size) [private]
Definition at line 76 of file sampling-heap-profiler.cc.
                                                                        {
  DisallowGarbageCollection no_gc;
  // Check if the area is iterable by confirming that it starts with a map.
  DCHECK(IsMap(HeapObject::FromAddress(soon_object)->map(isolate_), isolate_));
  HandleScope scope(isolate_);
  Tagged<HeapObject> heap_object = HeapObject::FromAddress(soon_object);
  Handle<Object> obj(heap_object, isolate_);
  // Since soon_object can be in code space or trusted space we can't use
  // v8::Utils::ToLocal.
  DCHECK(
      obj.is_null() ||
      (IsSmi(*obj) ||
       (V8_EXTERNAL_CODE_SPACE_BOOL && HeapLayout::InCodeSpace(heap_object)) ||
       HeapLayout::InTrustedSpace(heap_object) || !IsTheHole(*obj)));
  auto loc = Local<v8::Value>::FromSlot(obj.location());
  AllocationNode* node = AddStack();
  node->allocations_[size]++;
  auto sample =
      std::make_unique<Sample>(size, node, loc, this, next_sample_id());
  sample->global.SetWeak(sample.get(), OnWeakCallback,
                         WeakCallbackType::kParameter);
  samples_.emplace(sample.get(), std::move(sample));
}
References AddStack(), v8::internal::SamplingHeapProfiler::AllocationNode::allocations_, v8::internal::DCHECK(), v8::internal::HeapObject::FromAddress(), v8::Local< T >::FromSlot(), v8::internal::HeapLayout::InCodeSpace(), v8::internal::HeapLayout::InTrustedSpace(), v8::internal::HandleBase::is_null(), isolate_, v8::internal::IsSmi(), v8::kParameter, v8::internal::loc, v8::internal::HandleBase::location(), next_sample_id(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, OnWeakCallback(), samples_, size(), and V8_EXTERNAL_CODE_SPACE_BOOL.
Referenced by v8::internal::SamplingHeapProfiler::Observer::Step().
ScaleSample()
v8::AllocationProfile::Allocation v8::internal::SamplingHeapProfiler::ScaleSample (size_t size, unsigned int count) const [private]
Definition at line 46 of file sampling-heap-profiler.cc.
                                           {
  double scale = 1.0 / (1.0 - std::exp(-static_cast<double>(size) / rate_));
  // Round count instead of truncating.
  return {size, static_cast<unsigned int>(count * scale + 0.5)};
}
References v8::base::ieee754::exp(), rate_, and size().
Referenced by BuildSamples(), and TranslateAllocationNode().
TranslateAllocationNode()
v8::AllocationProfile::Node * v8::internal::SamplingHeapProfiler::TranslateAllocationNode (AllocationProfile * profile, SamplingHeapProfiler::AllocationNode * node, const std::map< int, Handle< Script >> & scripts) [private]
Definition at line 235 of file sampling-heap-profiler.cc.
                                                {
  // By pinning the node we make sure its children won't get disposed if
  // a GC kicks in during the tree retrieval.
  node->pinned_ = true;
  Local<v8::String> script_name =
      ToApiHandle<v8::String>(isolate_->factory()->InternalizeUtf8String(""));
  int line = v8::AllocationProfile::kNoLineNumberInfo;
  int column = v8::AllocationProfile::kNoColumnNumberInfo;
  std::vector<v8::AllocationProfile::Allocation> allocations;
  allocations.reserve(node->allocations_.size());
  if (node->script_id_ != v8::UnboundScript::kNoScriptId) {
    auto script_iterator = scripts.find(node->script_id_);
    if (script_iterator != scripts.end()) {
      DirectHandle<Script> script = script_iterator->second;
      if (IsName(script->name())) {
        Tagged<Name> name = Cast<Name>(script->name());
        script_name = ToApiHandle<v8::String>(
            isolate_->factory()->InternalizeUtf8String(names_->GetName(name)));
      }
      Script::PositionInfo pos_info;
      Script::GetPositionInfo(script, node->script_position_, &pos_info);
      line = pos_info.line + 1;
      column = pos_info.column + 1;
    }
  }
  for (auto alloc : node->allocations_) {
    allocations.push_back(ScaleSample(alloc.first, alloc.second));
  }
  profile->nodes_.push_back(v8::AllocationProfile::Node{
      ToApiHandle<v8::String>(
          isolate_->factory()->InternalizeUtf8String(node->name_)),
      script_name, node->script_id_, node->script_position_, line, column,
      node->id_, std::vector<v8::AllocationProfile::Node*>(), allocations});
  v8::AllocationProfile::Node* current = &profile->nodes_.back();
  // The |children_| map may have nodes inserted into it during translation
  // because the translation may allocate strings on the JS heap that have
  // the potential to be sampled. That's ok since map iterators are not
  // invalidated upon std::map insertion.
  for (const auto& it : node->children_) {
    current->children.push_back(
        TranslateAllocationNode(profile, it.second.get(), scripts));
  }
  node->pinned_ = false;
  return current;
}
References v8::internal::SamplingHeapProfiler::AllocationNode::allocations_, v8::AllocationProfile::Node::children, v8::internal::SamplingHeapProfiler::AllocationNode::children_, v8::internal::Script::PositionInfo::column, v8::internal::Isolate::factory(), v8::internal::StringsStorage::GetName(), v8::internal::Script::GetPositionInfo(), v8::internal::SamplingHeapProfiler::AllocationNode::id_, v8::internal::Factory::InternalizeUtf8String(), isolate_, v8::AllocationProfile::kNoColumnNumberInfo, v8::AllocationProfile::kNoLineNumberInfo, v8::UnboundScript::kNoScriptId, v8::internal::Script::PositionInfo::line, v8::internal::name, v8::internal::SamplingHeapProfiler::AllocationNode::name_, names_, v8::internal::AllocationProfile::nodes_, v8::internal::SamplingHeapProfiler::AllocationNode::pinned_, ScaleSample(), v8::internal::script, v8::internal::SamplingHeapProfiler::AllocationNode::script_id_, and v8::internal::SamplingHeapProfiler::AllocationNode::script_position_.
Referenced by GetAllocationProfile().
Member Data Documentation
allocation_observer_
Observer v8::internal::SamplingHeapProfiler::allocation_observer_ [private]
Definition at line 190 of file sampling-heap-profiler.h.
Referenced by SamplingHeapProfiler(), and ~SamplingHeapProfiler().
flags_
v8::HeapProfiler::SamplingFlags v8::internal::SamplingHeapProfiler::flags_ [private]
Definition at line 196 of file sampling-heap-profiler.h.
Referenced by GetAllocationProfile(), and OnWeakCallback().
heap_
Heap* const v8::internal::SamplingHeapProfiler::heap_ [private]
Definition at line 187 of file sampling-heap-profiler.h.
Referenced by SamplingHeapProfiler(), and ~SamplingHeapProfiler().
isolate_
Isolate* const v8::internal::SamplingHeapProfiler::isolate_ [private]
Definition at line 186 of file sampling-heap-profiler.h.
Referenced by AddStack(), GetAllocationProfile(), SampleObject(), and TranslateAllocationNode().
last_node_id_
uint32_t v8::internal::SamplingHeapProfiler::last_node_id_ = 0 [private]
Definition at line 189 of file sampling-heap-profiler.h.
Referenced by next_node_id().
last_sample_id_
uint64_t v8::internal::SamplingHeapProfiler::last_sample_id_ = 0 [private]
Definition at line 188 of file sampling-heap-profiler.h.
Referenced by next_sample_id().
names_
StringsStorage* const v8::internal::SamplingHeapProfiler::names_ [private]
Definition at line 191 of file sampling-heap-profiler.h.
Referenced by names(), and TranslateAllocationNode().
profile_root_
AllocationNode v8::internal::SamplingHeapProfiler::profile_root_ [private]
Definition at line 192 of file sampling-heap-profiler.h.
Referenced by AddStack(), and GetAllocationProfile().
rate_
const uint64_t v8::internal::SamplingHeapProfiler::rate_ [private]
Definition at line 195 of file sampling-heap-profiler.h.
Referenced by SamplingHeapProfiler(), and ScaleSample().
samples_
std::unordered_map<Sample*, std::unique_ptr<Sample> > v8::internal::SamplingHeapProfiler::samples_ [private]
Definition at line 193 of file sampling-heap-profiler.h.
Referenced by BuildSamples(), OnWeakCallback(), and SampleObject().
stack_depth_
const int v8::internal::SamplingHeapProfiler::stack_depth_ [private]
Definition at line 194 of file sampling-heap-profiler.h.
Referenced by AddStack().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/profiler/sampling-heap-profiler.h
/mnt/V8SourceCode/src/profiler/sampling-heap-profiler.cc