v8::internal::RootsReferencesExtractor Class Reference
Public Member Functions
RootsReferencesExtractor (V8HeapExplorer *explorer)
void SetVisitingWeakRoots ()
void VisitRootPointer (Root root, const char *description, FullObjectSlot p) override
void VisitRootPointers (Root root, const char *description, FullObjectSlot start, FullObjectSlot end) override
void VisitRootPointers (Root root, const char *description, OffHeapObjectSlot start, OffHeapObjectSlot end) override
void VisitRunningCode (FullObjectSlot code_slot, FullObjectSlot istream_or_smi_zero_slot) final
Private Attributes
V8HeapExplorer * explorer_
bool visiting_weak_roots_
Additional Inherited Members
Detailed Description
Definition at line 2499 of file heap-snapshot-generator.cc.
Constructor & Destructor Documentation
RootsReferencesExtractor()
v8::internal::RootsReferencesExtractor::RootsReferencesExtractor (V8HeapExplorer * explorer) [inline], [explicit]
Definition at line 2501 of file heap-snapshot-generator.cc.
      : explorer_(explorer), visiting_weak_roots_(false) {}
Member Function Documentation
SetVisitingWeakRoots()
void v8::internal::RootsReferencesExtractor::SetVisitingWeakRoots () [inline]
Definition at line 2504 of file heap-snapshot-generator.cc.
{ visiting_weak_roots_ = true; }
References visiting_weak_roots_.
Referenced by v8::internal::V8HeapExplorer::IterateAndExtractReferences().
VisitRootPointer()
void v8::internal::RootsReferencesExtractor::VisitRootPointer (Root root, const char * description, FullObjectSlot p) [inline], [override], [virtual]
Reimplemented from v8::internal::RootVisitor.
Definition at line 2506 of file heap-snapshot-generator.cc.
                                                   {
    Tagged<Object> object = *p;
#ifdef V8_ENABLE_DIRECT_HANDLE
    if (object.ptr() == kTaggedNullAddress) return;
#endif
    if (root == Root::kBuiltins) {
      explorer_->TagBuiltinCodeObject(Cast<Code>(object), description);
    }
    explorer_->SetGcSubrootReference(root, description, visiting_weak_roots_,
                                     object);
  }
References explorer_, v8::internal::kTaggedNullAddress, v8::internal::V8HeapExplorer::SetGcSubrootReference(), v8::internal::V8HeapExplorer::TagBuiltinCodeObject(), and visiting_weak_roots_.
Referenced by VisitRootPointers(), and VisitRunningCode().
VisitRootPointers() [1/2]
void v8::internal::RootsReferencesExtractor::VisitRootPointers (Root root, const char * description, FullObjectSlot start, FullObjectSlot end) [inline], [override], [virtual]
Implements v8::internal::RootVisitor.
Definition at line 2519 of file heap-snapshot-generator.cc.
                                                                            {
    for (FullObjectSlot p = start; p < end; ++p) {
      DCHECK(!MapWord::IsPacked(p.Relaxed_Load().ptr()));
      VisitRootPointer(root, description, p);
    }
  }
References v8::internal::DCHECK(), v8::internal::compiler::end(), v8::internal::MapWord::IsPacked(), and VisitRootPointer().
VisitRootPointers() [2/2]
void v8::internal::RootsReferencesExtractor::VisitRootPointers (Root root, const char * description, OffHeapObjectSlot start, OffHeapObjectSlot end) [inline], [override], [virtual]
Reimplemented from v8::internal::RootVisitor.
Definition at line 2527 of file heap-snapshot-generator.cc.
                                                         {
    DCHECK_EQ(root, Root::kStringTable);
    PtrComprCageBase cage_base(explorer_->heap_->isolate());
    for (OffHeapObjectSlot p = start; p < end; ++p) {
      explorer_->SetGcSubrootReference(root, description, visiting_weak_roots_,
                                       p.load(cage_base));
    }
  }
References DCHECK_EQ, v8::internal::compiler::end(), explorer_, v8::internal::V8HeapExplorer::heap_, v8::internal::Heap::isolate(), v8::internal::V8HeapExplorer::SetGcSubrootReference(), and visiting_weak_roots_.
VisitRunningCode()
void v8::internal::RootsReferencesExtractor::VisitRunningCode (FullObjectSlot code_slot, FullObjectSlot istream_or_smi_zero_slot) [inline], [final], [virtual]
Reimplemented from v8::internal::RootVisitor.
Definition at line 2540 of file heap-snapshot-generator.cc.
                                                                       {
    Tagged<Object> istream_or_smi_zero = *istream_or_smi_zero_slot;
    if (istream_or_smi_zero != Smi::zero()) {
      Tagged<Code> code = Cast<Code>(*code_slot);
      code->IterateDeoptimizationLiterals(this);
      VisitRootPointer(Root::kStackRoots, nullptr, istream_or_smi_zero_slot);
    }
    VisitRootPointer(Root::kStackRoots, nullptr, code_slot);
  }
References code, VisitRootPointer(), and v8::internal::Smi::zero().
Member Data Documentation
explorer_
V8HeapExplorer* v8::internal::RootsReferencesExtractor::explorer_ [private]
Definition at line 2552 of file heap-snapshot-generator.cc.
Referenced by VisitRootPointer(), and VisitRootPointers().
visiting_weak_roots_
bool v8::internal::RootsReferencesExtractor::visiting_weak_roots_ [private]
Definition at line 2553 of file heap-snapshot-generator.cc.
Referenced by SetVisitingWeakRoots(), VisitRootPointer(), and VisitRootPointers().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/profiler/heap-snapshot-generator.cc