cppgc::internal::GlobalGCInfoTable Class Reference
#include <gc-info-table.h>
Public Member Functions
GlobalGCInfoTable (const GlobalGCInfoTable &)=delete
GlobalGCInfoTable & operator= (const GlobalGCInfoTable &)=delete
Static Public Member Functions
static void Initialize (PageAllocator &page_allocator)
static GCInfoTable & GetMutable ()
static const GCInfoTable & Get ()
static const GCInfo & GCInfoFromIndex (GCInfoIndex index)
Static Private Attributes
static GCInfoTable * global_table_ = nullptr
Detailed Description
Definition at line 101 of file gc-info-table.h.
Constructor & Destructor Documentation
GlobalGCInfoTable()
cppgc::internal::GlobalGCInfoTable::GlobalGCInfoTable (const GlobalGCInfoTable &) [delete]
Member Function Documentation
GCInfoFromIndex()
static const GCInfo& cppgc::internal::GlobalGCInfoTable::GCInfoFromIndex (GCInfoIndex index) [inline], [static]
Definition at line 115 of file gc-info-table.h.
                                                          {
    return Get().GCInfoFromIndex(index);
  }
References v8::internal::compiler::turboshaft::Get(), and v8::internal::index.
Referenced by cppgc::internal::MutatorMarkingState::DynamicallyMarkAddress(), cppgc::internal::HeapObjectHeader::Finalize(), cppgc::internal::HeapObjectHeader::GetName(), cppgc::internal::TraceTraitFromInnerAddressImpl::GetTraceDescriptor(), cppgc::internal::HeapObjectHeader::IsFinalizable(), cppgc::internal::MarkingStateBase::MarkAndPush(), and cppgc::internal::HeapObjectHeader::TraceImpl().
Get()
static const GCInfoTable& cppgc::internal::GlobalGCInfoTable::Get () [inline], [static]
Definition at line 113 of file gc-info-table.h.
{ return *global_table_; }
GetMutable()
static GCInfoTable& cppgc::internal::GlobalGCInfoTable::GetMutable () [inline], [static]
Definition at line 112 of file gc-info-table.h.
{ return *global_table_; }
Referenced by cppgc::internal::EnsureGCInfoIndexTrait::EnsureGCInfoIndex().
Initialize()
void cppgc::internal::GlobalGCInfoTable::Initialize (PageAllocator & page_allocator) [static]
Definition at line 42 of file gc-info-table.cc.
                                                                {
  static v8::base::LeakyObject<GCInfoTable> table(page_allocator,
                                                  GetGlobalOOMHandler());
  if (!global_table_) {
    global_table_ = table.get();
  } else {
    CHECK_EQ(&page_allocator, &global_table_->allocator());
  }
}
References cppgc::internal::GCInfoTable::allocator(), CHECK_EQ, v8::base::LeakyObject< T >::get(), cppgc::internal::GetGlobalOOMHandler(), and global_table_.
Referenced by cppgc::InitializeProcess().
operator=()
GlobalGCInfoTable& cppgc::internal::GlobalGCInfoTable::operator= (const GlobalGCInfoTable &) [delete]
Member Data Documentation
global_table_
GCInfoTable * cppgc::internal::GlobalGCInfoTable::global_table_ = nullptr [static], [private]
Definition at line 121 of file gc-info-table.h.
Referenced by Initialize().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/gc-info-table.h
/mnt/V8SourceCode/src/heap/cppgc/gc-info-table.cc