v8::internal::EvacuateRecordOnlyVisitor Class Reference
Public Member Functions
EvacuateRecordOnlyVisitor (Heap *heap)
bool Visit (Tagged< HeapObject > object, int size) override
size_t live_object_size () const
Private Attributes
Heap * heap_
const PtrComprCageBase cage_base_
size_t live_object_size_ = 0
Detailed Description
Definition at line 1807 of file mark-compact.cc.
Constructor & Destructor Documentation
EvacuateRecordOnlyVisitor()
v8::internal::EvacuateRecordOnlyVisitor::EvacuateRecordOnlyVisitor (Heap * heap) [inline], [explicit]
Definition at line 1809 of file mark-compact.cc.
      : heap_(heap), cage_base_(heap->isolate()) {}
Member Function Documentation
live_object_size()
size_t v8::internal::EvacuateRecordOnlyVisitor::live_object_size () const [inline]
Definition at line 1823 of file mark-compact.cc.
{ return live_object_size_; }
References live_object_size_.
Referenced by v8::internal::anonymous_namespace{mark-compact.cc}::ReRecordPage().
Visit()
bool v8::internal::EvacuateRecordOnlyVisitor::Visit (Tagged< HeapObject > object, int size) [inline], [override], [virtual]
Implements v8::internal::HeapObjectVisitor.
Definition at line 1812 of file mark-compact.cc.
                                                           {
    RecordMigratedSlotVisitor visitor(heap_);
    Tagged<Map> map = object->map(cage_base_);
    // Instead of calling object.IterateFast(cage_base(), &visitor) here
    // we can shortcut and use the precomputed size value passed to the visitor.
    DCHECK_EQ(object->SizeFromMap(map), size);
    live_object_size_ += ALIGN_TO_ALLOCATION_ALIGNMENT(size);
    visitor.Visit(map, object, size);
    return true;
  }
References ALIGN_TO_ALLOCATION_ALIGNMENT, cage_base_, DCHECK_EQ, heap_, live_object_size_, size(), and v8::internal::HeapVisitor< ConcreteVisitor >::Visit().
Member Data Documentation
cage_base_
const PtrComprCageBase v8::internal::EvacuateRecordOnlyVisitor::cage_base_ [private]
Definition at line 1827 of file mark-compact.cc.
Referenced by Visit().
heap_
Heap* v8::internal::EvacuateRecordOnlyVisitor::heap_ [private]
Definition at line 1826 of file mark-compact.cc.
Referenced by Visit().
live_object_size_
size_t v8::internal::EvacuateRecordOnlyVisitor::live_object_size_ = 0 [private]
Definition at line 1828 of file mark-compact.cc.
Referenced by live_object_size(), and Visit().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/mark-compact.cc