v8::internal::maglev::BasicBlockRef Class Reference
#include <maglev-ir.h>
Public Member Functions
BasicBlockRef ()
BasicBlockRef (BasicBlock *block)
BasicBlockRef (const BasicBlockRef &)=delete
BasicBlockRef (BasicBlockRef &&)=delete
BasicBlockRef & operator= (const BasicBlockRef &)=delete
BasicBlockRef & operator= (BasicBlockRef &&)=delete
BasicBlockRef (BasicBlockRef *ref_list_head)
BasicBlockRef * SetToBlockAndReturnNext (BasicBlock *block)
BasicBlockRef * Reset ()
BasicBlockRef * MoveToRefList (BasicBlockRef *ref_list_head)
void Bind (BasicBlock *block)
BasicBlock * block_ptr () const
void set_block_ptr (BasicBlock *block)
BasicBlockRef * next_ref () const
bool has_ref () const
Private Attributes
xx xx xx xx xx xx xx xx xx
union {
 BasicBlock * block_ptr_
 BasicBlockRef * next_ref_
};
Detailed Description
Definition at line 1102 of file maglev-ir.h.
Constructor & Destructor Documentation
BasicBlockRef() [1/5]
v8::internal::maglev::BasicBlockRef::BasicBlockRef () [inline]
Definition at line 1106 of file maglev-ir.h.
                  : next_ref_(nullptr) {
#ifdef DEBUG
    state_ = kRefList;
#endif
  }
BasicBlockRef() [2/5]
v8::internal::maglev::BasicBlockRef::BasicBlockRef (BasicBlock * block) [inline], [explicit]
Definition at line 1111 of file maglev-ir.h.
                                            : block_ptr_(block) {
#ifdef DEBUG
    state_ = kBlockPointer;
#endif
  }
BasicBlockRef() [3/5]
v8::internal::maglev::BasicBlockRef::BasicBlockRef (const BasicBlockRef &) [delete]
BasicBlockRef() [4/5]
v8::internal::maglev::BasicBlockRef::BasicBlockRef (BasicBlockRef &&) [delete]
BasicBlockRef() [5/5]
v8::internal::maglev::BasicBlockRef::BasicBlockRef (BasicBlockRef * ref_list_head) [inline], [explicit]
Definition at line 1126 of file maglev-ir.h.
                                                       : BasicBlockRef() {
    BasicBlockRef* old_next_ptr = MoveToRefList(ref_list_head);
    USE(old_next_ptr);
    DCHECK_NULL(old_next_ptr);
  }
References DCHECK_NULL, MoveToRefList(), and USE.
Member Function Documentation
Bind()
void v8::internal::maglev::BasicBlockRef::Bind (BasicBlock * block) [inline]
Definition at line 1167 of file maglev-ir.h.
                               {
    DCHECK_EQ(state_, kRefList);
    BasicBlockRef* next_ref = SetToBlockAndReturnNext(block);
    while (next_ref != nullptr) {
      next_ref = next_ref->SetToBlockAndReturnNext(block);
    }
    DCHECK_EQ(block_ptr(), block);
  }
References block_ptr(), DCHECK_EQ, next_ref(), and SetToBlockAndReturnNext().
Referenced by v8::internal::maglev::MaglevGraphBuilder::StartNewBlock().
block_ptr()
BasicBlock* v8::internal::maglev::BasicBlockRef::block_ptr () const [inline]
Definition at line 1177 of file maglev-ir.h.
                                {
    DCHECK_EQ(state_, kBlockPointer);
    return block_ptr_;
  }
References block_ptr_, and DCHECK_EQ.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters(), v8::internal::maglev::MaglevGraphBuilder::AttachExceptionHandlerInfo(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::BeginLoop(), Bind(), v8::internal::maglev::ExceptionHandlerInfo::catch_block(), v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::PrintTargets(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
has_ref()
bool v8::internal::maglev::BasicBlockRef::has_ref () const [inline]
Definition at line 1192 of file maglev-ir.h.
                       {
    DCHECK_EQ(state_, kRefList);
    return next_ref_ != nullptr;
  }
References DCHECK_EQ, and next_ref_.
MoveToRefList()
BasicBlockRef* v8::internal::maglev::BasicBlockRef::MoveToRefList (BasicBlockRef * ref_list_head) [inline]
Definition at line 1157 of file maglev-ir.h.
                                                             {
    DCHECK_EQ(state_, kRefList);
    DCHECK_EQ(ref_list_head->state_, kRefList);
    BasicBlockRef* old_next_ptr = next_ref_;
    next_ref_ = ref_list_head->next_ref_;
    ref_list_head->next_ref_ = this;
    return old_next_ptr;
  }
References DCHECK_EQ, and next_ref_.
Referenced by BasicBlockRef(), and v8::internal::maglev::MaglevGraphBuilder::ProcessMergePointPredecessors().
next_ref()
BasicBlockRef* v8::internal::maglev::BasicBlockRef::next_ref () const [inline]
Definition at line 1187 of file maglev-ir.h.
                                  {
    DCHECK_EQ(state_, kRefList);
    return next_ref_;
  }
References DCHECK_EQ, and next_ref_.
Referenced by Bind().
operator=() [1/2]
BasicBlockRef& v8::internal::maglev::BasicBlockRef::operator= (BasicBlockRef &&) [delete]
operator=() [2/2]
BasicBlockRef& v8::internal::maglev::BasicBlockRef::operator= (const BasicBlockRef &) [delete]
Reset()
BasicBlockRef* v8::internal::maglev::BasicBlockRef::Reset () [inline]
Definition at line 1147 of file maglev-ir.h.
                         {
    DCHECK_EQ(state_, kRefList);
    BasicBlockRef* old_next_ptr = next_ref_;
    next_ref_ = nullptr;
    return old_next_ptr;
  }
References DCHECK_EQ, and next_ref_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::ProcessMergePointPredecessors().
set_block_ptr()
void v8::internal::maglev::BasicBlockRef::set_block_ptr (BasicBlock * block) [inline]
Definition at line 1182 of file maglev-ir.h.
                                        {
    DCHECK_EQ(state_, kBlockPointer);
    block_ptr_ = block;
  }
References block_ptr_, and DCHECK_EQ.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::PatchJumps().
SetToBlockAndReturnNext()
BasicBlockRef* v8::internal::maglev::BasicBlockRef::SetToBlockAndReturnNext (BasicBlock * block) [inline]
Definition at line 1134 of file maglev-ir.h.
                                                            {
    DCHECK_EQ(state_, kRefList);
    BasicBlockRef* old_next_ptr = next_ref_;
    block_ptr_ = block;
#ifdef DEBUG
    state_ = kBlockPointer;
#endif
    return old_next_ptr;
  }
References block_ptr_, DCHECK_EQ, and next_ref_.
Referenced by Bind(), and v8::internal::maglev::MaglevGraphBuilder::ProcessMergePointPredecessors().
Member Data Documentation
union { ... } [private]
block_ptr_
BasicBlock* v8::internal::maglev::BasicBlockRef::block_ptr_
Definition at line 1199 of file maglev-ir.h.
Referenced by block_ptr(), set_block_ptr(), and SetToBlockAndReturnNext().
next_ref_
BasicBlockRef* v8::internal::maglev::BasicBlockRef::next_ref_
Definition at line 1200 of file maglev-ir.h.
Referenced by has_ref(), MoveToRefList(), next_ref(), Reset(), and SetToBlockAndReturnNext().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h