v8::internal::BackgroundCompileTask Class Reference
#include <compiler.h>
Public Member Functions
BackgroundCompileTask (ScriptStreamingData *data, Isolate *isolate, v8::ScriptType type, ScriptCompiler::CompileOptions options, ScriptCompiler::CompilationDetails *compilation_details, CompileHintCallback compile_hint_callback=nullptr, void *compile_hint_callback_data=nullptr)
BackgroundCompileTask (const BackgroundCompileTask &)=delete
BackgroundCompileTask & operator= (const BackgroundCompileTask &)=delete
~BackgroundCompileTask ()
BackgroundCompileTask (Isolate *isolate, Handle< SharedFunctionInfo > shared_info, std::unique_ptr< Utf16CharacterStream > character_stream, WorkerThreadRuntimeCallStats *worker_thread_runtime_stats, TimedHistogram *timer, int max_stack_size)
void Run ()
void RunOnMainThread (Isolate *isolate)
void Run (LocalIsolate *isolate, ReusableUnoptimizedCompileState *reusable_state)
MaybeHandle< SharedFunctionInfo > FinalizeScript (Isolate *isolate, DirectHandle< String > source, const ScriptDetails &script_details, MaybeDirectHandle< Script > maybe_cached_script)
bool FinalizeFunction (Isolate *isolate, Compiler::ClearExceptionFlag flag)
void AbortFunction ()
UnoptimizedCompileFlags flags () const
Private Member Functions
void ReportStatistics (Isolate *isolate)
void ClearFunctionJobPointer ()
bool is_streaming_compilation () const
Private Attributes
Isolate * isolate_for_local_isolate_
UnoptimizedCompileFlags flags_
UnoptimizedCompileState compile_state_
std::unique_ptr< Utf16CharacterStream > character_stream_
int stack_size_
WorkerThreadRuntimeCallStats * worker_thread_runtime_call_stats_
TimedHistogram * timer_
ScriptCompiler::CompilationDetails * compilation_details_
std::unique_ptr< PersistentHandles > persistent_handles_
MaybeIndirectHandle< SharedFunctionInfo > outer_function_sfi_
IndirectHandle< Script > script_
IsCompiledScope is_compiled_scope_
FinalizeUnoptimizedCompilationDataList finalize_unoptimized_compilation_data_
DeferredFinalizationJobDataList jobs_to_retry_finalization_on_main_thread_
base::SmallVector< v8::Isolate::UseCounterFeature, 8 > use_counts_
int total_preparse_skipped_ = 0
MaybeIndirectHandle< SharedFunctionInfo > input_shared_info_
int start_position_
int end_position_
int function_literal_id_
CompileHintCallback compile_hint_callback_ = nullptr
void * compile_hint_callback_data_ = nullptr
Detailed Description
Definition at line 587 of file compiler.h.
Constructor & Destructor Documentation
BackgroundCompileTask() [1/3]
v8::internal::BackgroundCompileTask::BackgroundCompileTask (ScriptStreamingData * data, Isolate * isolate, v8::ScriptType type, ScriptCompiler::CompileOptions options, ScriptCompiler::CompilationDetails * compilation_details, CompileHintCallback compile_hint_callback = nullptr, void * compile_hint_callback_data = nullptr)
Definition at line 1693 of file compiler.cc.
    : isolate_for_local_isolate_(isolate),
      flags_(UnoptimizedCompileFlags::ForToplevelCompile(
          isolate, true, construct_language_mode(v8_flags.use_strict),
          REPLMode::kNo, type,
          (options & ScriptCompiler::CompileOptions::kEagerCompile) == 0 &&
              v8_flags.lazy_streaming)),
      character_stream_(ScannerStream::For(streamed_data->source_stream.get(),
                                           streamed_data->encoding)),
      stack_size_(v8_flags.stack_size),
      worker_thread_runtime_call_stats_(
          isolate->counters()->worker_thread_runtime_call_stats()),
      timer_(isolate->counters()->compile_script_on_background()),
      compilation_details_(compilation_details),
      start_position_(0),
      end_position_(0),
      function_literal_id_(kFunctionLiteralIdTopLevel),
      compile_hint_callback_(compile_hint_callback),
      compile_hint_callback_data_(compile_hint_callback_data) {
  if (options & ScriptCompiler::CompileOptions::kProduceCompileHints) {
    flags_.set_produce_compile_hints(true);
  }
  DCHECK(is_streaming_compilation());
  if (options & ScriptCompiler::kConsumeCompileHints) {
    DCHECK_NOT_NULL(compile_hint_callback);
    DCHECK_NOT_NULL(compile_hint_callback_data);
  } else {
    DCHECK_NULL(compile_hint_callback);
    DCHECK_NULL(compile_hint_callback_data);
  }
  flags_.set_compile_hints_magic_enabled(
      options &
      ScriptCompiler::CompileOptions::kFollowCompileHintsMagicComment);
  flags_.set_compile_hints_per_function_magic_enabled(
      options & ScriptCompiler::CompileOptions::
                    kFollowCompileHintsPerFunctionMagicComment);
}
References v8::internal::DCHECK(), DCHECK_NOT_NULL, DCHECK_NULL, flags_, is_streaming_compilation(), and v8::ScriptCompiler::kConsumeCompileHints.
BackgroundCompileTask() [2/3]
v8::internal::BackgroundCompileTask::BackgroundCompileTask (const BackgroundCompileTask &) [delete]
 BackgroundCompileTask()
v8::internal::BackgroundCompileTask::~BackgroundCompileTask () [default]
BackgroundCompileTask() [3/3]
v8::internal::BackgroundCompileTask::BackgroundCompileTask (Isolate * isolate, Handle< SharedFunctionInfo > shared_info, std::unique_ptr< Utf16CharacterStream > character_stream, WorkerThreadRuntimeCallStats * worker_thread_runtime_stats, TimedHistogram * timer, int max_stack_size)
Definition at line 1735 of file compiler.cc.
    : isolate_for_local_isolate_(isolate),
      // TODO(leszeks): Create this from parent compile flags, to avoid
      // accessing the Isolate.
      flags_(
          UnoptimizedCompileFlags::ForFunctionCompile(isolate, *shared_info)),
      character_stream_(std::move(character_stream)),
      stack_size_(max_stack_size),
      worker_thread_runtime_call_stats_(worker_thread_runtime_stats),
      timer_(timer),
      compilation_details_(nullptr),
      start_position_(shared_info->StartPosition()),
      end_position_(shared_info->EndPosition()),
      function_literal_id_(shared_info->function_literal_id(kRelaxedLoad)) {
  DCHECK(!shared_info->is_toplevel());
  DCHECK(!is_streaming_compilation());
  character_stream_->Seek(start_position_);
  // Get the script out of the outer ParseInfo and turn it into a persistent
  // handle we can transfer to the background thread.
  persistent_handles_ = std::make_unique<PersistentHandles>(isolate);
  input_shared_info_ = persistent_handles_->NewHandle(shared_info);
}
References character_stream_, v8::internal::DCHECK(), input_shared_info_, is_streaming_compilation(), persistent_handles_, and start_position_.
Member Function Documentation
AbortFunction()
void v8::internal::BackgroundCompileTask::AbortFunction ()
Definition at line 2729 of file compiler.cc.
                                          {
  // The UncompiledData on the input SharedFunctionInfo will have a pointer to
  // the LazyCompileDispatcher Job that launched this task, which is about to be
  // deleted, so clear that to avoid the SharedFunctionInfo from pointing to
  // deallocated memory.
  input_shared_info_.ToHandleChecked()->ClearUncompiledDataJobPointer(
      isolate_for_local_isolate_);
}
References input_shared_info_, and isolate_for_local_isolate_.
ClearFunctionJobPointer()
void v8::internal::BackgroundCompileTask::ClearFunctionJobPointer () [private]
FinalizeFunction()
bool v8::internal::BackgroundCompileTask::FinalizeFunction (Isolate * isolate, Compiler::ClearExceptionFlag flag)
Definition at line 2688 of file compiler.cc.
                                                       {
  DCHECK(!flags_.is_toplevel());
  MaybeDirectHandle<SharedFunctionInfo> maybe_result;
  DirectHandle<SharedFunctionInfo> input_shared_info =
      input_shared_info_.ToHandleChecked();
  // The UncompiledData on the input SharedFunctionInfo will have a pointer to
  // the LazyCompileDispatcher Job that launched this task, which will now be
  // considered complete, so clear that regardless of whether the finalize
  // succeeds or not.
  input_shared_info->ClearUncompiledDataJobPointer(isolate);
  // We might not have been able to finalize all jobs on the background
  // thread (e.g. asm.js jobs), so finalize those deferred jobs now.
  if (FinalizeDeferredUnoptimizedCompilationJobs(
          isolate, script_, &jobs_to_retry_finalization_on_main_thread_,
          compile_state_.pending_error_handler(),
          &finalize_unoptimized_compilation_data_)) {
    maybe_result = outer_function_sfi_;
  }
  ReportStatistics(isolate);
  DirectHandle<SharedFunctionInfo> result;
  if (!maybe_result.ToHandle(&result)) {
    FailWithPreparedException(isolate, script_,
                              compile_state_.pending_error_handler(), flag);
    return false;
  }
  FinalizeUnoptimizedCompilation(isolate, script_, flags_, &compile_state_,
                                 finalize_unoptimized_compilation_data_);
  // Move the compiled data from the placeholder SFI back to the real SFI.
  input_shared_info->CopyFrom(*result, isolate);
  return true;
}
References compile_state_, v8::internal::DCHECK(), v8::internal::anonymous_namespace{compiler.cc}::FailWithPreparedException(), finalize_unoptimized_compilation_data_, v8::internal::anonymous_namespace{compiler.cc}::FinalizeDeferredUnoptimizedCompilationJobs(), v8::internal::anonymous_namespace{compiler.cc}::FinalizeUnoptimizedCompilation(), flags_, input_shared_info_, jobs_to_retry_finalization_on_main_thread_, outer_function_sfi_, v8::internal::UnoptimizedCompileState::pending_error_handler(), ReportStatistics(), v8::base::internal::result, script_, and v8::internal::MaybeDirectHandle< T >::ToHandle().
Referenced by v8::internal::Compiler::FinalizeBackgroundCompileTask().
FinalizeScript()
MaybeHandle< SharedFunctionInfo > v8::internal::BackgroundCompileTask::FinalizeScript (Isolate * isolate, DirectHandle< String > source, const ScriptDetails & script_details, MaybeDirectHandle< Script > maybe_cached_script)
Definition at line 2620 of file compiler.cc.
                                                   {
  ScriptOriginOptions origin_options = script_details.origin_options;
  DCHECK(flags_.is_toplevel());
  DCHECK_EQ(flags_.is_module(), origin_options.IsModule());
  MaybeDirectHandle<SharedFunctionInfo> maybe_result;
  Handle<Script> script = script_;
  // We might not have been able to finalize all jobs on the background
  // thread (e.g. asm.js jobs), so finalize those deferred jobs now.
  if (FinalizeDeferredUnoptimizedCompilationJobs(
          isolate, script, &jobs_to_retry_finalization_on_main_thread_,
          compile_state_.pending_error_handler(),
          &finalize_unoptimized_compilation_data_)) {
    maybe_result = outer_function_sfi_;
  }
  if (DirectHandle<Script> cached_script;
      maybe_cached_script.ToHandle(&cached_script) && !maybe_result.is_null()) {
    BackgroundMergeTask merge;
    merge.SetUpOnMainThread(isolate, cached_script);
    CHECK(merge.HasPendingBackgroundWork());
    merge.BeginMergeInBackground(isolate->AsLocalIsolate(), script);
    CHECK(merge.HasPendingForegroundWork());
    DirectHandle<SharedFunctionInfo> result =
        merge.CompleteMergeInForeground(isolate, script);
    maybe_result = result;
    script = handle(Cast<Script>(result->script()), isolate);
    DCHECK(Object::StrictEquals(script->source(), *source));
    DCHECK(isolate->factory()->script_list()->Contains(MakeWeak(*script)));
  } else {
    Script::SetSource(isolate, script, source);
    script->set_origin_options(origin_options);
    // The one post-hoc fix-up: Add the script to the script list.
    DirectHandle<WeakArrayList> scripts = isolate->factory()->script_list();
    scripts = WeakArrayList::Append(isolate, scripts,
                                    MaybeObjectDirectHandle::Weak(script));
    isolate->heap()->SetRootScriptList(*scripts);
    // Set the script fields after finalization, to keep this path the same
    // between main-thread and off-thread finalization.
    {
      DisallowGarbageCollection no_gc;
      SetScriptFieldsFromDetails(isolate, *script, script_details, &no_gc);
      LOG(isolate, ScriptDetails(*script));
    }
  }
  ReportStatistics(isolate);
  DirectHandle<SharedFunctionInfo> result;
  if (!maybe_result.ToHandle(&result)) {
    FailWithPreparedException(isolate, script,
                              compile_state_.pending_error_handler());
    return kNullMaybeHandle;
  }
  FinalizeUnoptimizedScriptCompilation(isolate, script, flags_, &compile_state_,
                                       finalize_unoptimized_compilation_data_);
  return handle(*result, isolate);
}
References v8::internal::WeakArrayList::Append(), v8::internal::Isolate::AsLocalIsolate(), v8::internal::BackgroundMergeTask::BeginMergeInBackground(), CHECK, compile_state_, v8::internal::BackgroundMergeTask::CompleteMergeInForeground(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{compiler.cc}::FailWithPreparedException(), finalize_unoptimized_compilation_data_, v8::internal::anonymous_namespace{compiler.cc}::FinalizeDeferredUnoptimizedCompilationJobs(), v8::internal::anonymous_namespace{compiler.cc}::FinalizeUnoptimizedScriptCompilation(), flags_, v8::internal::handle(), v8::internal::BackgroundMergeTask::HasPendingBackgroundWork(), v8::internal::BackgroundMergeTask::HasPendingForegroundWork(), v8::internal::Isolate::heap(), v8::internal::MaybeDirectHandle< T >::is_null(), v8::ScriptOriginOptions::IsModule(), jobs_to_retry_finalization_on_main_thread_, v8::internal::kNullMaybeHandle, LOG, v8::internal::MakeWeak(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::ScriptDetails::origin_options, outer_function_sfi_, v8::internal::UnoptimizedCompileState::pending_error_handler(), ReportStatistics(), v8::base::internal::result, v8::internal::script, script_, v8::internal::Heap::SetRootScriptList(), v8::internal::SetScriptFieldsFromDetails(), v8::internal::Script::SetSource(), v8::internal::BackgroundMergeTask::SetUpOnMainThread(), v8::internal::Object::StrictEquals(), v8::internal::MaybeDirectHandle< T >::ToHandle(), and v8::internal::MaybeObjectDirectHandle::Weak().
Referenced by v8::internal::Compiler::GetSharedFunctionInfoForStreamedScript().
flags()
UnoptimizedCompileFlags v8::internal::BackgroundCompileTask::flags () const [inline]
Definition at line 625 of file compiler.h.
{ return flags_; }
Referenced by v8::internal::Compiler::GetSharedFunctionInfoForStreamedScript(), and Run().
is_streaming_compilation()
bool v8::internal::BackgroundCompileTask::is_streaming_compilation () const [private]
Definition at line 1930 of file compiler.cc.
                                                           {
  return function_literal_id_ == kFunctionLiteralIdTopLevel;
}
References function_literal_id_, and v8::internal::kFunctionLiteralIdTopLevel.
Referenced by BackgroundCompileTask(), and Run().
operator=()
BackgroundCompileTask& v8::internal::BackgroundCompileTask::operator= (const BackgroundCompileTask &) [delete]
ReportStatistics()
void v8::internal::BackgroundCompileTask::ReportStatistics (Isolate * isolate) [private]
Definition at line 2738 of file compiler.cc.
                                                             {
  // Update use-counts.
  for (auto feature : use_counts_) {
    isolate->CountUsage(feature);
  }
}
References v8::internal::Isolate::CountUsage(), and use_counts_.
Referenced by FinalizeFunction(), and FinalizeScript().
Run() [1/2]
void v8::internal::BackgroundCompileTask::Run ()
Definition at line 1934 of file compiler.cc.
                                {
  base::FlushDenormalsScope flush_denormals_scope(
      isolate_for_local_isolate_->flush_denormals());
  DCHECK_NE(ThreadId::Current(), isolate_for_local_isolate_->thread_id());
  LocalIsolate isolate(isolate_for_local_isolate_, ThreadKind::kBackground);
  UnparkedScope unparked_scope(&isolate);
  LocalHandleScope handle_scope(&isolate);
  ReusableUnoptimizedCompileState reusable_state(&isolate);
  Run(&isolate, &reusable_state);
}
References v8::internal::ThreadId::Current(), DCHECK_NE, v8::internal::Isolate::flush_denormals(), isolate_for_local_isolate_, v8::internal::kBackground, and v8::internal::Isolate::thread_id().
Referenced by RunOnMainThread().
Run() [2/2]
void v8::internal::BackgroundCompileTask::Run (LocalIsolate * isolate, ReusableUnoptimizedCompileState * reusable_state)
Definition at line 1954 of file compiler.cc.
                                                                            {
  TimedHistogramScope timer(
      timer_, nullptr,
      compilation_details_
          ? &compilation_details_->background_time_in_microseconds
          : nullptr);
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
               "BackgroundCompileTask::Run");
  RCS_SCOPE(isolate, RuntimeCallCounterId::kCompileCompileTask,
            RuntimeCallStats::CounterMode::kThreadSpecific);
  bool toplevel_script_compilation = flags_.is_toplevel();
  ParseInfo info(isolate, flags_, &compile_state_, reusable_state,
                 GetCurrentStackPosition() - stack_size_ * KB);
  info.set_character_stream(std::move(character_stream_));
  info.SetCompileHintCallbackAndData(compile_hint_callback_,
                                     compile_hint_callback_data_);
  if (is_streaming_compilation()) info.set_is_streaming_compilation();
  if (toplevel_script_compilation) {
    DCHECK_NULL(persistent_handles_);
    DCHECK(input_shared_info_.is_null());
    // We don't have the script source, origin, or details yet, so use default
    // values for them. These will be fixed up during the main-thread merge.
    Handle<Script> script = info.CreateScript(
        isolate, isolate->factory()->empty_string(), kNullMaybeHandle,
        ScriptOriginOptions(false, false, false, info.flags().is_module()));
    script_ = isolate->heap()->NewPersistentHandle(script);
  } else {
    DCHECK_NOT_NULL(persistent_handles_);
    isolate->heap()->AttachPersistentHandles(std::move(persistent_handles_));
    DirectHandle<SharedFunctionInfo> shared_info =
        input_shared_info_.ToHandleChecked();
    script_ = isolate->heap()->NewPersistentHandle(
        Cast<Script>(shared_info->script()));
    info.CheckFlagsForFunctionFromScript(*script_);
    {
      SharedStringAccessGuardIfNeeded access_guard(isolate);
      info.set_function_name(info.ast_value_factory()->GetString(
          shared_info->Name(), access_guard));
    }
    // Get preparsed scope data from the function literal.
    if (shared_info->HasUncompiledDataWithPreparseData(isolate)) {
      info.set_consumed_preparse_data(ConsumedPreparseData::For(
          isolate,
          handle(shared_info->uncompiled_data_with_preparse_data(isolate)
                     ->preparse_data(isolate),
                 isolate)));
    }
  }
  // Update the character stream's runtime call stats.
  info.character_stream()->set_runtime_call_stats(info.runtime_call_stats());
  Parser parser(isolate, &info);
  if (flags().is_toplevel()) {
    parser.InitializeEmptyScopeChain(&info);
  } else {
    // TODO(leszeks): Consider keeping Scope zones alive between compile tasks
    // and passing the Scope for the FunctionLiteral through here directly
    // without copying/deserializing.
    DirectHandle<SharedFunctionInfo> shared_info =
        input_shared_info_.ToHandleChecked();
    MaybeDirectHandle<ScopeInfo> maybe_outer_scope_info;
    if (shared_info->HasOuterScopeInfo()) {
      maybe_outer_scope_info =
          direct_handle(shared_info->GetOuterScopeInfo(), isolate);
    }
    parser.DeserializeScopeChain(
        isolate, &info, maybe_outer_scope_info,
        Scope::DeserializationMode::kIncludingVariables);
  }
  parser.ParseOnBackground(isolate, &info, script_, start_position_,
                           end_position_, function_literal_id_);
  parser.UpdateStatistics(script_, &use_counts_, &total_preparse_skipped_);
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
               "V8.CompileCodeBackground");
  RCS_SCOPE(isolate, RuntimeCallCounterIdForCompile(&info),
            RuntimeCallStats::CounterMode::kThreadSpecific);
  MaybeHandle<SharedFunctionInfo> maybe_result;
  if (info.literal() != nullptr) {
    if (toplevel_script_compilation) {
      CreateTopLevelSharedFunctionInfo(&info, script_, isolate);
    } else {
      // Clone into a placeholder SFI for storing the results.
      info.literal()->set_shared_function_info(
          isolate->factory()->CloneSharedFunctionInfo(
              input_shared_info_.ToHandleChecked()));
    }
    if (IterativelyExecuteAndFinalizeUnoptimizedCompilationJobs(
            isolate, script_, &info, reusable_state->allocator(),
            &is_compiled_scope_, &finalize_unoptimized_compilation_data_,
            &jobs_to_retry_finalization_on_main_thread_)) {
      maybe_result = info.literal()->shared_function_info();
    }
  }
  if (maybe_result.is_null()) {
    PrepareException(isolate, &info);
  } else if (v8_flags.enable_slow_asserts) {
#ifdef ENABLE_SLOW_DCHECKS
    MergeAssumptionChecker checker(isolate);
    checker.IterateObjects(*maybe_result.ToHandleChecked());
#endif
  }
  outer_function_sfi_ = isolate->heap()->NewPersistentMaybeHandle(maybe_result);
  DCHECK(isolate->heap()->ContainsPersistentHandle(script_.location()));
  persistent_handles_ = isolate->heap()->DetachPersistentHandles();
}
References v8::internal::ReusableUnoptimizedCompileState::allocator(), v8::internal::ParseInfo::ast_value_factory(), v8::internal::LocalHeap::AttachPersistentHandles(), v8::ScriptCompiler::CompilationDetails::background_time_in_microseconds, v8::internal::ParseInfo::character_stream(), character_stream_, v8::internal::ParseInfo::CheckFlagsForFunctionFromScript(), v8::internal::FactoryBase< Impl >::CloneSharedFunctionInfo(), compilation_details_, compile_hint_callback_, compile_hint_callback_data_, compile_state_, v8::internal::ParseInfo::CreateScript(), v8::internal::anonymous_namespace{compiler.cc}::CreateTopLevelSharedFunctionInfo(), v8::internal::DCHECK(), DCHECK_NOT_NULL, DCHECK_NULL, v8::internal::Parser::DeserializeScopeChain(), v8::internal::LocalHeap::DetachPersistentHandles(), v8::internal::direct_handle(), end_position_, v8::internal::LocalIsolate::factory(), finalize_unoptimized_compilation_data_, flags(), v8::internal::ParseInfo::flags(), flags_, v8::internal::ConsumedPreparseData::For(), function_literal_id_, v8::internal::GetCurrentStackPosition(), v8::internal::AstValueFactory::GetString(), v8::internal::handle(), v8::internal::LocalIsolate::heap(), v8::internal::Parser::InitializeEmptyScopeChain(), input_shared_info_, is_compiled_scope_, v8::internal::MaybeHandle< T >::is_null(), is_streaming_compilation(), v8::internal::anonymous_namespace{compiler.cc}::IterativelyExecuteAndFinalizeUnoptimizedCompilationJobs(), jobs_to_retry_finalization_on_main_thread_, v8::internal::KB, v8::internal::Scope::kIncludingVariables, v8::internal::kNullMaybeHandle, v8::internal::ParseInfo::literal(), v8::internal::LocalHeap::NewPersistentHandle(), v8::internal::LocalHeap::NewPersistentMaybeHandle(), outer_function_sfi_, v8::internal::Parser::ParseOnBackground(), persistent_handles_, v8::internal::anonymous_namespace{compiler.cc}::PrepareException(), RCS_SCOPE, v8::internal::ParseInfo::runtime_call_stats(), v8::internal::script, script_, v8::internal::ParseInfo::set_character_stream(), v8::internal::ParseInfo::set_consumed_preparse_data(), v8::internal::ParseInfo::set_function_name(), v8::internal::ParseInfo::set_is_streaming_compilation(), v8::internal::Utf16CharacterStream::set_runtime_call_stats(), v8::internal::FunctionLiteral::set_shared_function_info(), v8::internal::ParseInfo::SetCompileHintCallbackAndData(), v8::internal::FunctionLiteral::shared_function_info(), stack_size_, start_position_, timer_, v8::internal::MaybeHandle< T >::ToHandleChecked(), total_preparse_skipped_, TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT0, v8::internal::Parser::UpdateStatistics(), use_counts_, and v8::internal::v8_flags.
RunOnMainThread()
void v8::internal::BackgroundCompileTask::RunOnMainThread (Isolate * isolate)
Definition at line 1948 of file compiler.cc.
                                                            {
  LocalHandleScope handle_scope(isolate->main_thread_local_isolate());
  ReusableUnoptimizedCompileState reusable_state(isolate);
  Run(isolate->main_thread_local_isolate(), &reusable_state);
}
References v8::internal::Isolate::main_thread_local_isolate(), and Run().
Member Data Documentation
character_stream_
std::unique_ptr<Utf16CharacterStream> v8::internal::BackgroundCompileTask::character_stream_ [private]
Definition at line 639 of file compiler.h.
Referenced by BackgroundCompileTask(), and Run().
compilation_details_
ScriptCompiler::CompilationDetails* v8::internal::BackgroundCompileTask::compilation_details_ [private]
Definition at line 643 of file compiler.h.
Referenced by Run().
compile_hint_callback_
CompileHintCallback v8::internal::BackgroundCompileTask::compile_hint_callback_ = nullptr [private]
Definition at line 661 of file compiler.h.
Referenced by Run().
compile_hint_callback_data_
void* v8::internal::BackgroundCompileTask::compile_hint_callback_data_ = nullptr [private]
Definition at line 662 of file compiler.h.
Referenced by Run().
compile_state_
UnoptimizedCompileState v8::internal::BackgroundCompileTask::compile_state_ [private]
Definition at line 638 of file compiler.h.
Referenced by FinalizeFunction(), FinalizeScript(), and Run().
end_position_
int v8::internal::BackgroundCompileTask::end_position_ [private]
Definition at line 658 of file compiler.h.
Referenced by Run().
finalize_unoptimized_compilation_data_
FinalizeUnoptimizedCompilationDataList v8::internal::BackgroundCompileTask::finalize_unoptimized_compilation_data_ [private]
Definition at line 650 of file compiler.h.
Referenced by FinalizeFunction(), FinalizeScript(), and Run().
flags_
UnoptimizedCompileFlags v8::internal::BackgroundCompileTask::flags_ [private]
Definition at line 637 of file compiler.h.
Referenced by BackgroundCompileTask(), FinalizeFunction(), FinalizeScript(), and Run().
function_literal_id_
int v8::internal::BackgroundCompileTask::function_literal_id_ [private]
Definition at line 659 of file compiler.h.
Referenced by is_streaming_compilation(), and Run().
input_shared_info_
MaybeIndirectHandle<SharedFunctionInfo> v8::internal::BackgroundCompileTask::input_shared_info_ [private]
Definition at line 656 of file compiler.h.
Referenced by AbortFunction(), BackgroundCompileTask(), FinalizeFunction(), and Run().
is_compiled_scope_
IsCompiledScope v8::internal::BackgroundCompileTask::is_compiled_scope_ [private]
Definition at line 649 of file compiler.h.
Referenced by Run().
isolate_for_local_isolate_
Isolate* v8::internal::BackgroundCompileTask::isolate_for_local_isolate_ [private]
Definition at line 636 of file compiler.h.
Referenced by AbortFunction(), and Run().
jobs_to_retry_finalization_on_main_thread_
DeferredFinalizationJobDataList v8::internal::BackgroundCompileTask::jobs_to_retry_finalization_on_main_thread_ [private]
Definition at line 651 of file compiler.h.
Referenced by FinalizeFunction(), FinalizeScript(), and Run().
outer_function_sfi_
MaybeIndirectHandle<SharedFunctionInfo> v8::internal::BackgroundCompileTask::outer_function_sfi_ [private]
Definition at line 647 of file compiler.h.
Referenced by FinalizeFunction(), FinalizeScript(), and Run().
persistent_handles_
std::unique_ptr<PersistentHandles> v8::internal::BackgroundCompileTask::persistent_handles_ [private]
Definition at line 646 of file compiler.h.
Referenced by BackgroundCompileTask(), and Run().
script_
IndirectHandle<Script> v8::internal::BackgroundCompileTask::script_ [private]
Definition at line 648 of file compiler.h.
Referenced by FinalizeFunction(), FinalizeScript(), and Run().
stack_size_
int v8::internal::BackgroundCompileTask::stack_size_ [private]
Definition at line 640 of file compiler.h.
Referenced by Run().
start_position_
int v8::internal::BackgroundCompileTask::start_position_ [private]
Definition at line 657 of file compiler.h.
Referenced by BackgroundCompileTask(), and Run().
timer_
TimedHistogram* v8::internal::BackgroundCompileTask::timer_ [private]
Definition at line 642 of file compiler.h.
Referenced by Run().
total_preparse_skipped_
int v8::internal::BackgroundCompileTask::total_preparse_skipped_ = 0 [private]
Definition at line 653 of file compiler.h.
Referenced by Run().
use_counts_
base::SmallVector<v8::Isolate::UseCounterFeature, 8> v8::internal::BackgroundCompileTask::use_counts_ [private]
Definition at line 652 of file compiler.h.
Referenced by ReportStatistics(), and Run().
worker_thread_runtime_call_stats_
WorkerThreadRuntimeCallStats* v8::internal::BackgroundCompileTask::worker_thread_runtime_call_stats_ [private]
Definition at line 641 of file compiler.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/compiler.h
/mnt/V8SourceCode/src/codegen/compiler.cc