v8::internal::SimulatorStack Class Reference
#include <simulator.h>
Static Public Member Functions
static uintptr_t JsLimitFromCLimit (v8::internal::Isolate *isolate, uintptr_t c_limit)
static void IterateRegistersAndStack (Isolate *isolate, ::heap::base::StackVisitor *visitor)
static bool ShouldSwitchCStackForWasmStackSwitching ()
static uintptr_t RegisterJSStackComparableAddress (v8::internal::Isolate *isolate)
static void UnregisterJSStackComparableAddress (v8::internal::Isolate *isolate)
Detailed Description
Definition at line 102 of file simulator.h.
Member Function Documentation
IterateRegistersAndStack()
static void v8::internal::SimulatorStack::IterateRegistersAndStack (Isolate * isolate, ::heap::base::StackVisitor * visitor) [inline], [static]
Definition at line 124 of file simulator.h.
                                                                      {}
Referenced by v8::internal::Isolate::IterateRegistersAndStackOfSimulator().
JsLimitFromCLimit()
static uintptr_t v8::internal::SimulatorStack::JsLimitFromCLimit (v8::internal::Isolate * isolate, uintptr_t c_limit) [inline], [static]
Definition at line 104 of file simulator.h.
                                                               {
    USE(isolate);
    return c_limit;
  }
References USE.
Referenced by v8::internal::StackGuard::ThreadLocal::Initialize(), and v8::internal::StackGuard::SetStackLimit().
RegisterJSStackComparableAddress()
static uintptr_t v8::internal::SimulatorStack::RegisterJSStackComparableAddress (v8::internal::Isolate * isolate) [inline], [static]
Definition at line 133 of file simulator.h.
                                  {
    USE(isolate);
    return internal::GetCurrentStackPosition();
  }
References v8::internal::GetCurrentStackPosition(), and USE.
Referenced by v8::Context::BackupIncumbentScope::BackupIncumbentScope(), v8::internal::ExternalCallbackScope::ExternalCallbackScope(), and v8::TryCatch::TryCatch().
ShouldSwitchCStackForWasmStackSwitching()
static bool v8::internal::SimulatorStack::ShouldSwitchCStackForWasmStackSwitching () [inline], [static]
Definition at line 129 of file simulator.h.
{ return true; }
UnregisterJSStackComparableAddress()
static void v8::internal::SimulatorStack::UnregisterJSStackComparableAddress (v8::internal::Isolate * isolate) [inline], [static]
Definition at line 139 of file simulator.h.
                                  {
    USE(isolate);
  }
References USE.
Referenced by v8::internal::Isolate::UnregisterTryCatchHandler(), v8::Context::BackupIncumbentScope::~BackupIncumbentScope(), and v8::internal::ExternalCallbackScope::~ExternalCallbackScope().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/execution/simulator.h