v8::internal::AsyncFunctionBuiltinsAssembler Class Reference
Public Member Functions
AsyncFunctionBuiltinsAssembler (compiler::CodeAssemblerState *state)
Protected Member Functions
template<typename Descriptor >
void AsyncFunctionAwait ()
void AsyncFunctionAwaitResumeClosure (const TNode< Context > context, const TNode< Object > sent_value, JSGeneratorObject::ResumeMode resume_mode)
Additional Inherited Members
Detailed Description
Definition at line 18 of file builtins-async-function-gen.cc.
Constructor & Destructor Documentation
AsyncFunctionBuiltinsAssembler()
v8::internal::AsyncFunctionBuiltinsAssembler::AsyncFunctionBuiltinsAssembler (compiler::CodeAssemblerState * state) [inline], [explicit]
Definition at line 20 of file builtins-async-function-gen.cc.
      : AsyncBuiltinsAssembler(state) {}
Member Function Documentation
AsyncFunctionAwait()
template<typename Descriptor >
void v8::internal::AsyncFunctionBuiltinsAssembler::AsyncFunctionAwait [protected]
Definition at line 199 of file builtins-async-function-gen.cc.
                                                        {
  auto async_function_object =
      Parameter<JSAsyncFunctionObject>(Descriptor::kAsyncFunctionObject);
  auto value = Parameter<JSAny>(Descriptor::kValue);
  auto context = Parameter<Context>(Descriptor::kContext);
  TNode<JSPromise> outer_promise = LoadObjectField<JSPromise>(
      async_function_object, JSAsyncFunctionObject::kPromiseOffset);
  Await(context, async_function_object, value, outer_promise,
        RootIndex::kAsyncFunctionAwaitResolveClosureSharedFun,
        RootIndex::kAsyncFunctionAwaitRejectClosureSharedFun);
  // Return outer promise to avoid adding an load of the outer promise before
  // suspending in BytecodeGenerator.
  Return(outer_promise);
}
References v8::internal::AsyncBuiltinsAssembler::Await(), v8::internal::compiler::CodeAssembler::Return(), and v8::internal::value.
AsyncFunctionAwaitResumeClosure()
void v8::internal::AsyncFunctionBuiltinsAssembler::AsyncFunctionAwaitResumeClosure (const TNode< Context > context, const TNode< Object > sent_value, JSGeneratorObject::ResumeMode resume_mode) [protected]
Definition at line 32 of file builtins-async-function-gen.cc.
                                             {
  DCHECK(resume_mode == JSGeneratorObject::kNext ||
         resume_mode == JSGeneratorObject::kThrow);
  TNode<JSAsyncFunctionObject> async_function_object =
      CAST(LoadContextElementNoCell(context, Context::EXTENSION_INDEX));
  // Inline version of GeneratorPrototypeNext / GeneratorPrototypeReturn with
  // unnecessary runtime checks removed.
  // Ensure that the {async_function_object} is neither closed nor running.
  CSA_SLOW_DCHECK(
      this, SmiGreaterThan(
                LoadObjectField<Smi>(async_function_object,
                                     JSGeneratorObject::kContinuationOffset),
                SmiConstant(JSGeneratorObject::kGeneratorClosed)));
  // Remember the {resume_mode} for the {async_function_object}.
  StoreObjectFieldNoWriteBarrier(async_function_object,
                                 JSGeneratorObject::kResumeModeOffset,
                                 SmiConstant(resume_mode));
  // Resume the {receiver} using our trampoline.
  CallBuiltin(Builtin::kResumeGeneratorTrampoline, context, sent_value,
              async_function_object);
  // The resulting Promise is a throwaway, so it doesn't matter what it
  // resolves to. What is important is that we don't end up keeping the
  // whole chain of intermediate Promises alive by returning the return value
  // of ResumeGenerator, as that would create a memory leak.
}
References v8::internal::compiler::CodeAssembler::CallBuiltin(), CAST, v8::internal::DCHECK(), v8::internal::Context::EXTENSION_INDEX, v8::internal::JSGeneratorObject::kGeneratorClosed, v8::internal::JSGeneratorObject::kNext, v8::internal::JSGeneratorObject::kThrow, v8::internal::compiler::CodeAssembler::SmiConstant(), and v8::internal::CodeStubAssembler::StoreObjectFieldNoWriteBarrier().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/builtins/builtins-async-function-gen.cc