v8::internal::JSDisplayNames Class Reference
#include <js-display-names.h>
Public Types
enum class Style { kLong
, kShort
, kNarrow
 }
enum class Fallback { kCode
, kNone
 }
enum class LanguageDisplay { kDialect
, kStandard
 }
Public Member Functions
Handle< String > StyleAsString (Isolate *isolate) const
Handle< String > FallbackAsString (Isolate *isolate) const
DirectHandle< String > LanguageDisplayAsString (Isolate *isolate) const
void set_style (Style style)
Style style () const
void set_fallback (Fallback fallback)
Fallback fallback () const
void set_language_display (LanguageDisplay language_display)
LanguageDisplay language_display () const
Static Public Member Functions
static MaybeDirectHandle< JSDisplayNames > New (Isolate *isolate, DirectHandle< Map > map, DirectHandle< Object > locales, DirectHandle< Object > options)
static DirectHandle< JSObject > ResolvedOptions (Isolate *isolate, DirectHandle< JSDisplayNames > format_holder)
static MaybeDirectHandle< Object > Of (Isolate *isolate, DirectHandle< JSDisplayNames > holder, Handle< Object > code_obj)
static V8_EXPORT_PRIVATE const std::set< std::string > & GetAvailableLocales ()
Detailed Description
Definition at line 30 of file js-display-names.h.
Member Enumeration Documentation
Fallback
enum v8::internal::JSDisplayNames::Fallback [strong]
Enumerator
kCode
kNone
Definition at line 67 of file js-display-names.h.
                      {
    kCode,
    kNone,
  };
LanguageDisplay
enum v8::internal::JSDisplayNames::LanguageDisplay [strong]
Enumerator
kDialect
kStandard
Definition at line 74 of file js-display-names.h.
                             {
    kDialect,
    kStandard,
  };
Style
enum v8::internal::JSDisplayNames::Style [strong]
Enumerator
kLong
kShort
kNarrow
Definition at line 56 of file js-display-names.h.
                   {
    kLong, // Everything spelled out.
    kShort, // Abbreviations used when possible.
    kNarrow // Use the shortest possible form.
  };
Member Function Documentation
fallback()
JSDisplayNames::Fallback v8::internal::JSDisplayNames::fallback () const [inline]
Definition at line 43 of file js-display-names-inl.h.
                                                             {
  return FallbackBit::decode(flags());
}
References v8::internal::flags.
Referenced by FallbackAsString(), ResolvedOptions(), and set_fallback().
FallbackAsString()
Handle< String > v8::internal::JSDisplayNames::FallbackAsString (Isolate * isolate) const
Definition at line 653 of file js-display-names.cc.
                                                                      {
  switch (fallback()) {
    case Fallback::kCode:
      return isolate->factory()->code_string();
    case Fallback::kNone:
      return isolate->factory()->none_string();
  }
  UNREACHABLE();
}
References v8::internal::Isolate::factory(), fallback(), kCode, kNone, and v8::internal::UNREACHABLE().
GetAvailableLocales()
const std::set< std::string > & v8::internal::JSDisplayNames::GetAvailableLocales () [static]
Definition at line 635 of file js-display-names.cc.
                                                             {
  static base::LazyInstance<Intl::AvailableLocales<CheckCalendar>>::type
      available_locales = LAZY_INSTANCE_INITIALIZER;
  return available_locales.Pointer()->Get();
}
References LAZY_INSTANCE_INITIALIZER, and v8::internal::tracing::type.
Referenced by v8::internal::BUILTIN(), and New().
language_display()
JSDisplayNames::LanguageDisplay v8::internal::JSDisplayNames::language_display () const [inline]
Definition at line 53 of file js-display-names-inl.h.
          {
  return LanguageDisplayBit::decode(flags());
}
References v8::internal::flags.
Referenced by LanguageDisplayAsString(), ResolvedOptions(), and set_language_display().
LanguageDisplayAsString()
DirectHandle< String > v8::internal::JSDisplayNames::LanguageDisplayAsString (Isolate * isolate) const
Definition at line 663 of file js-display-names.cc.
                            {
  switch (language_display()) {
    case LanguageDisplay::kDialect:
      return isolate->factory()->dialect_string();
    case LanguageDisplay::kStandard:
      return isolate->factory()->standard_string();
  }
  UNREACHABLE();
}
References v8::internal::Isolate::factory(), kDialect, kStandard, language_display(), and v8::internal::UNREACHABLE().
New()
MaybeDirectHandle< JSDisplayNames > v8::internal::JSDisplayNames::New (Isolate * isolate, DirectHandle< Map > map, DirectHandle< Object > locales, DirectHandle< Object > options) [static]
Definition at line 404 of file js-display-names.cc.
                                        {
  const char* service = "Intl.DisplayNames";
  Factory* factory = isolate->factory();
  DirectHandle<JSReceiver> options;
  // 3. Let requestedLocales be ? CanonicalizeLocaleList(locales).
  Maybe<std::vector<std::string>> maybe_requested_locales =
      Intl::CanonicalizeLocaleList(isolate, locales);
  MAYBE_RETURN(maybe_requested_locales, DirectHandle<JSDisplayNames>());
  std::vector<std::string> requested_locales =
      maybe_requested_locales.FromJust();
  // 4. Let options be ? GetOptionsObject(options).
  ASSIGN_RETURN_ON_EXCEPTION(isolate, options,
                             GetOptionsObject(isolate, input_options, service));
  // Note: No need to create a record. It's not observable.
  // 5. Let opt be a new Record.
  // 6. Let localeData be %DisplayNames%.[[LocaleData]].
  // 7. Let matcher be ? GetOption(options, "localeMatcher", "string", «
  // "lookup", "best fit" », "best fit").
  Maybe<Intl::MatcherOption> maybe_locale_matcher =
      Intl::GetLocaleMatcher(isolate, options, service);
  MAYBE_RETURN(maybe_locale_matcher, MaybeDirectHandle<JSDisplayNames>());
  // 8. Set opt.[[localeMatcher]] to matcher.
  Intl::MatcherOption matcher = maybe_locale_matcher.FromJust();
  // ecma402/#sec-Intl.DisplayNames-internal-slots
  // The value of the [[RelevantExtensionKeys]] internal slot is
  // « ».
  // 9. Let r be ResolveLocale(%DisplayNames%.[[AvailableLocales]],
  // requestedLocales, opt, %DisplayNames%.[[RelevantExtensionKeys]]).
  Intl::ResolvedLocale r;
  if (!Intl::ResolveLocale(isolate, JSDisplayNames::GetAvailableLocales(),
                           requested_locales, matcher, {})
           .To(&r)) {
    THROW_NEW_ERROR(isolate, NewRangeError(MessageTemplate::kIcuError));
  }
  icu::Locale icu_locale = r.icu_locale;
  // 10. Let s be ? GetOption(options, "style", "string",
  // «"long", "short", "narrow"», "long").
  Maybe<Style> maybe_style = GetStringOption<Style>(
      isolate, options, "style", service,
      std::to_array<const std::string_view>({"long", "short", "narrow"}),
      std::array{Style::kLong, Style::kShort, Style::kNarrow}, Style::kLong);
  MAYBE_RETURN(maybe_style, MaybeDirectHandle<JSDisplayNames>());
  Style style_enum = maybe_style.FromJust();
  // 11. Set displayNames.[[Style]] to style.
  // 12. Let type be ? GetOption(options, "type", "string", « "language",
  // "region", "script", "currency" , "calendar", "dateTimeField", "unit"»,
  // undefined).
  Maybe<Type> maybe_type = GetStringOption<Type>(
      isolate, options, "type", service,
      std::to_array<const std::string_view>({"language", "region", "script",
                                             "currency", "calendar",
                                             "dateTimeField"}),
      std::array{Type::kLanguage, Type::kRegion, Type::kScript, Type::kCurrency,
                 Type::kCalendar, Type::kDateTimeField},
      Type::kUndefined);
  MAYBE_RETURN(maybe_type, MaybeDirectHandle<JSDisplayNames>());
  Type type_enum = maybe_type.FromJust();
  // 13. If type is undefined, throw a TypeError exception.
  if (type_enum == Type::kUndefined) {
    THROW_NEW_ERROR(isolate, NewTypeError(MessageTemplate::kInvalidArgument));
  }
  // 14. Set displayNames.[[Type]] to type.
  // 15. Let fallback be ? GetOption(options, "fallback", "string",
  // « "code", "none" », "code").
  Maybe<Fallback> maybe_fallback = GetStringOption<Fallback>(
      isolate, options, "fallback", service,
      std::to_array<const std::string_view>({"code", "none"}),
      std::array{Fallback::kCode, Fallback::kNone}, Fallback::kCode);
  MAYBE_RETURN(maybe_fallback, MaybeDirectHandle<JSDisplayNames>());
  Fallback fallback_enum = maybe_fallback.FromJust();
  // 16. Set displayNames.[[Fallback]] to fallback.
  LanguageDisplay language_display_enum = LanguageDisplay::kDialect;
  // 24. Let languageDisplay be ? GetOption(options, "languageDisplay",
  // "string", « "dialect", "standard" », "dialect").
  Maybe<LanguageDisplay> maybe_language_display =
      GetStringOption<LanguageDisplay>(
          isolate, options, "languageDisplay", service,
          std::to_array<const std::string_view>({"dialect", "standard"}),
          std::array{LanguageDisplay::kDialect, LanguageDisplay::kStandard},
          LanguageDisplay::kDialect);
  MAYBE_RETURN(maybe_language_display, MaybeDirectHandle<JSDisplayNames>());
  // 25. If type is "language", then
  if (type_enum == Type::kLanguage) {
    // a. Set displayNames.[[LanguageDisplay]] to languageDisplay.
    language_display_enum = maybe_language_display.FromJust();
  }
  // Set displayNames.[[Fallback]] to fallback.
  // 17. Set displayNames.[[Locale]] to the value of r.[[Locale]].
  // Let dataLocale be r.[[dataLocale]].
  // Let dataLocaleData be localeData.[[<dataLocale>]].
  // Let types be dataLocaleData.[[types]].
  // Assert: types is a Record (see 1.3.3).
  // Let typeFields be types.[[<type>]].
  // Assert: typeFields is a Record (see 1.3.3).
  // Let styleFields be typeFields.[[<style>]].
  // Assert: styleFields is a Record (see 1.3.3).
  // Set displayNames.[[Fields]] to styleFields.
  std::shared_ptr<DisplayNamesInternal> internal{CreateInternal(
      icu_locale, style_enum, type_enum, fallback_enum == Fallback::kCode,
      language_display_enum == LanguageDisplay::kDialect)};
  if (internal == nullptr) {
    THROW_NEW_ERROR(isolate, NewTypeError(MessageTemplate::kIcuError));
  }
  DirectHandle<Managed<DisplayNamesInternal>> managed_internal =
      Managed<DisplayNamesInternal>::From(isolate, 0, std::move(internal));
  DirectHandle<JSDisplayNames> display_names =
      Cast<JSDisplayNames>(factory->NewFastOrSlowJSObjectFromMap(map));
  display_names->set_flags(0);
  display_names->set_style(style_enum);
  display_names->set_fallback(fallback_enum);
  display_names->set_language_display(language_display_enum);
  DisallowGarbageCollection no_gc;
  display_names->set_internal(*managed_internal);
  // Return displayNames.
  return display_names;
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Intl::CanonicalizeLocaleList(), v8::internal::anonymous_namespace{js-display-names.cc}::CreateInternal(), v8::internal::Isolate::factory(), v8::internal::Managed< CppType >::From(), v8::Maybe< T >::FromJust(), GetAvailableLocales(), v8::internal::Intl::GetLocaleMatcher(), v8::internal::GetOptionsObject(), v8::internal::Intl::ResolvedLocale::icu_locale, kCode, kDialect, kLong, kNarrow, kNone, kShort, kStandard, MAYBE_RETURN, v8::internal::Factory::NewFastOrSlowJSObjectFromMap(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Intl::ResolveLocale(), and THROW_NEW_ERROR.
Of()
MaybeDirectHandle< Object > v8::internal::JSDisplayNames::Of (Isolate * isolate, DirectHandle< JSDisplayNames > holder, Handle< Object > code_obj) [static]
Definition at line 609 of file js-display-names.cc.
                             {
  DirectHandle<String> code;
  ASSIGN_RETURN_ON_EXCEPTION(isolate, code,
                             Object::ToString(isolate, code_obj));
  DisplayNamesInternal* internal = display_names->internal()->raw();
  Maybe<icu::UnicodeString> maybe_result =
      internal->of(isolate, code->ToCString().get());
  MAYBE_RETURN(maybe_result, DirectHandle<Object>());
  icu::UnicodeString result = maybe_result.FromJust();
  if (result.isBogus()) {
    return isolate->factory()->undefined_value();
  }
  return Intl::ToString(isolate, result).ToHandleChecked();
}
References ASSIGN_RETURN_ON_EXCEPTION, code, v8::internal::Isolate::factory(), v8::Maybe< T >::FromJust(), MAYBE_RETURN, v8::base::internal::result, v8::internal::Intl::ToString(), and v8::Value::ToString().
Referenced by v8::internal::BUILTIN().
ResolvedOptions()
DirectHandle< JSObject > v8::internal::JSDisplayNames::ResolvedOptions (Isolate * isolate, DirectHandle< JSDisplayNames > format_holder) [static]
Definition at line 556 of file js-display-names.cc.
                                                                  {
  Factory* factory = isolate->factory();
  // 4. Let options be ! ObjectCreate(%ObjectPrototype%).
  DirectHandle<JSObject> options =
      factory->NewJSObject(isolate->object_function());
  DisplayNamesInternal* internal = display_names->internal()->raw();
  Maybe<std::string> maybe_locale = Intl::ToLanguageTag(internal->locale());
  DCHECK(maybe_locale.IsJust());
  DirectHandle<String> locale = isolate->factory()->NewStringFromAsciiChecked(
      maybe_locale.FromJust().c_str());
  DirectHandle<String> style = display_names->StyleAsString(isolate);
  DirectHandle<String> type =
      factory->NewStringFromAsciiChecked(internal->type());
  DirectHandle<String> fallback = display_names->FallbackAsString(isolate);
  DirectHandle<String> language_display =
      display_names->LanguageDisplayAsString(isolate);
  Maybe<bool> maybe_create_locale = JSReceiver::CreateDataProperty(
      isolate, options, factory->locale_string(), locale, Just(kDontThrow));
  DCHECK(maybe_create_locale.FromJust());
  USE(maybe_create_locale);
  Maybe<bool> maybe_create_style = JSReceiver::CreateDataProperty(
      isolate, options, factory->style_string(), style, Just(kDontThrow));
  DCHECK(maybe_create_style.FromJust());
  USE(maybe_create_style);
  Maybe<bool> maybe_create_type = JSReceiver::CreateDataProperty(
      isolate, options, factory->type_string(), type, Just(kDontThrow));
  DCHECK(maybe_create_type.FromJust());
  USE(maybe_create_type);
  Maybe<bool> maybe_create_fallback = JSReceiver::CreateDataProperty(
      isolate, options, factory->fallback_string(), fallback, Just(kDontThrow));
  DCHECK(maybe_create_fallback.FromJust());
  USE(maybe_create_fallback);
    if (std::strcmp("language", internal->type()) == 0) {
      Maybe<bool> maybe_create_language_display =
          JSReceiver::CreateDataProperty(isolate, options,
                                         factory->languageDisplay_string(),
                                         language_display, Just(kDontThrow));
      DCHECK(maybe_create_language_display.FromJust());
      USE(maybe_create_language_display);
    }
  return options;
}
References v8::internal::JSReceiver::CreateDataProperty(), v8::internal::DCHECK(), v8::internal::Isolate::factory(), fallback(), v8::Maybe< T >::FromJust(), v8::internal::internal, v8::Maybe< T >::IsJust(), v8::Just(), v8::internal::kDontThrow, language_display(), v8::internal::Factory::NewJSObject(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), style(), v8::internal::Intl::ToLanguageTag(), v8::internal::tracing::type, and USE.
Referenced by v8::internal::BUILTIN().
set_fallback()
void v8::internal::JSDisplayNames::set_fallback (Fallback fallback) [inline]
Definition at line 38 of file js-display-names-inl.h.
                                                          {
  DCHECK(FallbackBit::is_valid(fallback));
  set_flags(FallbackBit::update(flags(), fallback));
}
References v8::internal::DCHECK(), fallback(), and v8::internal::flags.
set_language_display()
void v8::internal::JSDisplayNames::set_language_display (LanguageDisplay language_display) [inline]
Definition at line 47 of file js-display-names-inl.h.
                                      {
  DCHECK(LanguageDisplayBit::is_valid(language_display));
  set_flags(LanguageDisplayBit::update(flags(), language_display));
}
References v8::internal::DCHECK(), v8::internal::flags, and language_display().
set_style()
void v8::internal::JSDisplayNames::set_style (Style style) [inline]
style()
JSDisplayNames::Style v8::internal::JSDisplayNames::style () const [inline]
Definition at line 34 of file js-display-names-inl.h.
                                                       {
  return StyleBits::decode(flags());
}
References v8::internal::flags.
Referenced by v8::internal::ACCESSORS(), ResolvedOptions(), and StyleAsString().
StyleAsString()
Handle< String > v8::internal::JSDisplayNames::StyleAsString (Isolate * isolate) const
Definition at line 641 of file js-display-names.cc.
                                                                   {
  switch (style()) {
    case Style::kLong:
      return isolate->factory()->long_string();
    case Style::kShort:
      return isolate->factory()->short_string();
    case Style::kNarrow:
      return isolate->factory()->narrow_string();
  }
  UNREACHABLE();
}
References v8::internal::Isolate::factory(), kLong, kNarrow, kShort, style(), and v8::internal::UNREACHABLE().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-display-names.h
/mnt/V8SourceCode/src/objects/js-display-names-inl.h
/mnt/V8SourceCode/src/objects/js-display-names.cc