v8::internal::InstructionStreamMap Class Reference
#include <profile-generator.h>
Classes
struct CodeEntryMapInfo
Public Member Functions
InstructionStreamMap (CodeEntryStorage &storage)
~InstructionStreamMap ()
InstructionStreamMap (const InstructionStreamMap &)=delete
InstructionStreamMap & operator= (const InstructionStreamMap &)=delete
void AddCode (Address addr, CodeEntry *entry, unsigned size)
void MoveCode (Address from, Address to)
bool RemoveCode (CodeEntry *)
void ClearCodesInRange (Address start, Address end)
CodeEntry * FindEntry (Address addr, Address *out_instruction_start=nullptr)
void Print ()
size_t size () const
size_t GetEstimatedMemoryUsage () const
CodeEntryStorage & code_entries ()
void Clear ()
Private Attributes
std::multimap< Address, CodeEntryMapInfo > code_map_
CodeEntryStorage & code_entries_
Detailed Description
Definition at line 497 of file profile-generator.h.
Constructor & Destructor Documentation
InstructionStreamMap() [1/2]
v8::internal::InstructionStreamMap::InstructionStreamMap (CodeEntryStorage & storage) [explicit]
Definition at line 965 of file profile-generator.cc.
    : code_entries_(storage) {}
 InstructionStreamMap()
v8::internal::InstructionStreamMap::~InstructionStreamMap ()
Definition at line 968 of file profile-generator.cc.
{ Clear(); }
References Clear().
InstructionStreamMap() [2/2]
v8::internal::InstructionStreamMap::InstructionStreamMap (const InstructionStreamMap &) [delete]
Member Function Documentation
AddCode()
void v8::internal::InstructionStreamMap::AddCode (Address addr, CodeEntry * entry, unsigned size)
Definition at line 983 of file profile-generator.cc.
                                                  {
  code_map_.emplace(addr, CodeEntryMapInfo{entry, size});
  entry->set_instruction_start(addr);
}
References code_map_, v8::internal::CodeEntry::set_instruction_start(), and size().
Referenced by v8::internal::ProfilerCodeObserver::CreateEntriesForRuntimeCallStats(), v8::internal::CodeCreateEventRecord::UpdateCodeMap(), and v8::internal::ReportBuiltinEventRecord::UpdateCodeMap().
Clear()
void v8::internal::InstructionStreamMap::Clear ()
Definition at line 970 of file profile-generator.cc.
                                 {
  for (auto& slot : code_map_) {
    if (CodeEntry* entry = slot.second.entry) {
      code_entries_.DecRef(entry);
    } else {
      // We expect all entries in the code mapping to contain a CodeEntry.
      UNREACHABLE();
    }
  }
  code_map_.clear();
}
References code_entries_, code_map_, v8::internal::CodeEntryStorage::DecRef(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::ProfilerCodeObserver::ClearCodeMap(), and ~InstructionStreamMap().
ClearCodesInRange()
void v8::internal::InstructionStreamMap::ClearCodesInRange (Address start, Address end)
Definition at line 1001 of file profile-generator.cc.
                                                                       {
  auto left = code_map_.upper_bound(start);
  if (left != code_map_.begin()) {
    --left;
    if (left->first + left->second.size <= start) ++left;
  }
  auto right = left;
  for (; right != code_map_.end() && right->first < end; ++right) {
    code_entries_.DecRef(right->second.entry);
  }
  code_map_.erase(left, right);
}
References code_entries_, code_map_, v8::internal::CodeEntryStorage::DecRef(), and v8::internal::compiler::end().
code_entries()
CodeEntryStorage& v8::internal::InstructionStreamMap::code_entries () [inline]
Definition at line 518 of file profile-generator.h.
{ return code_entries_; }
Referenced by v8::internal::ReportBuiltinEventRecord::UpdateCodeMap().
FindEntry()
CodeEntry * v8::internal::InstructionStreamMap::FindEntry (Address addr, Address * out_instruction_start = nullptr)
Definition at line 1014 of file profile-generator.cc.
                                                                           {
  // Note that an address may correspond to multiple CodeEntry objects. An
  // arbitrary selection is made (as per multimap spec) in the event of a
  // collision.
  auto it = code_map_.upper_bound(addr);
  if (it == code_map_.begin()) return nullptr;
  --it;
  Address start_address = it->first;
  Address end_address = start_address + it->second.size;
  CodeEntry* ret = addr < end_address ? it->second.entry : nullptr;
  DCHECK(!ret || (addr >= start_address && addr < end_address));
  if (ret && out_instruction_start) *out_instruction_start = start_address;
  return ret;
}
References code_map_, and v8::internal::DCHECK().
Referenced by v8::internal::Symbolizer::FindEntry(), v8::internal::CodeDisableOptEventRecord::UpdateCodeMap(), v8::internal::CodeDeoptEventRecord::UpdateCodeMap(), and v8::internal::ReportBuiltinEventRecord::UpdateCodeMap().
GetEstimatedMemoryUsage()
size_t v8::internal::InstructionStreamMap::GetEstimatedMemoryUsage () const
Definition at line 1060 of file profile-generator.cc.
                                                           {
  size_t map_size = 0;
  for (const auto& pair : code_map_) {
    map_size += sizeof(pair.first) + sizeof(pair.second) +
                pair.second.entry->EstimatedSize();
  }
  return sizeof(*this) + map_size;
}
References code_map_.
Referenced by v8::internal::ProfilerCodeObserver::GetEstimatedMemoryUsage().
MoveCode()
void v8::internal::InstructionStreamMap::MoveCode (Address from, Address to)
Definition at line 1030 of file profile-generator.cc.
                                                            {
  if (from == to) return;
  auto range = code_map_.equal_range(from);
  // Instead of iterating until |range.second|, iterate the number of elements.
  // This is because the |range.second| may no longer be the element past the
  // end of the equal elements range after insertions.
  size_t distance = std::distance(range.first, range.second);
  auto it = range.first;
  while (distance--) {
    CodeEntryMapInfo& info = it->second;
    DCHECK(info.entry);
    DCHECK_EQ(info.entry->instruction_start(), from);
    info.entry->set_instruction_start(to);
    DCHECK(from + info.size <= to || to + info.size <= from);
    code_map_.emplace(to, info);
    it++;
  }
  code_map_.erase(range.first, it);
}
References code_map_, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::InstructionStreamMap::CodeEntryMapInfo::entry, v8::internal::CodeEntry::instruction_start(), v8::internal::CodeEntry::set_instruction_start(), and v8::internal::InstructionStreamMap::CodeEntryMapInfo::size.
Referenced by v8::internal::CodeMoveEventRecord::UpdateCodeMap().
operator=()
InstructionStreamMap& v8::internal::InstructionStreamMap::operator= (const InstructionStreamMap &) [delete]
Print()
void v8::internal::InstructionStreamMap::Print ()
Definition at line 1053 of file profile-generator.cc.
                                 {
  for (const auto& pair : code_map_) {
    base::OS::Print("%p %5d %s\n", reinterpret_cast<void*>(pair.first),
                    pair.second.size, pair.second.entry->name());
  }
}
References code_map_, and v8::internal::Print().
RemoveCode()
bool v8::internal::InstructionStreamMap::RemoveCode (CodeEntry * entry)
Definition at line 989 of file profile-generator.cc.
                                                      {
  auto range = code_map_.equal_range(entry->instruction_start());
  for (auto i = range.first; i != range.second; ++i) {
    if (i->second.entry == entry) {
      code_entries_.DecRef(entry);
      code_map_.erase(i);
      return true;
    }
  }
  return false;
}
References code_entries_, code_map_, v8::internal::CodeEntryStorage::DecRef(), and v8::internal::CodeEntry::instruction_start().
Referenced by v8::internal::CodeDeleteEventRecord::UpdateCodeMap().
size()
size_t v8::internal::InstructionStreamMap::size () const [inline]
Definition at line 514 of file profile-generator.h.
{ return code_map_.size(); }
Referenced by AddCode().
Member Data Documentation
code_entries_
CodeEntryStorage& v8::internal::InstructionStreamMap::code_entries_ [private]
Definition at line 529 of file profile-generator.h.
Referenced by Clear(), ClearCodesInRange(), and RemoveCode().
code_map_
std::multimap<Address, CodeEntryMapInfo> v8::internal::InstructionStreamMap::code_map_ [private]
Definition at line 528 of file profile-generator.h.
Referenced by AddCode(), Clear(), ClearCodesInRange(), FindEntry(), GetEstimatedMemoryUsage(), MoveCode(), Print(), and RemoveCode().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/profiler/profile-generator.h
/mnt/V8SourceCode/src/profiler/profile-generator.cc