v8::internal::YoungGenerationRememberedSetsMarkingWorklist::Local Class Reference
#include <minor-mark-sweep.h>
Public Member Functions
Local (YoungGenerationRememberedSetsMarkingWorklist *handler)
template<typename Visitor >
bool ProcessNextItem (Visitor *visitor)
Private Attributes
YoungGenerationRememberedSetsMarkingWorklist *const handler_
std::optional< size_t > index_
Detailed Description
Definition at line 38 of file minor-mark-sweep.h.
Constructor & Destructor Documentation
Local()
v8::internal::YoungGenerationRememberedSetsMarkingWorklist::Local::Local (YoungGenerationRememberedSetsMarkingWorklist * handler) [inline], [explicit]
Definition at line 40 of file minor-mark-sweep.h.
        : handler_(handler) {}
Member Function Documentation
ProcessNextItem()
template<typename Visitor >
bool v8::internal::YoungGenerationRememberedSetsMarkingWorklist::Local::ProcessNextItem (Visitor * visitor) [inline]
Definition at line 44 of file minor-mark-sweep.h.
                                           {
      return handler_->ProcessNextItem(visitor, index_);
    }
References handler_, index_, and v8::internal::YoungGenerationRememberedSetsMarkingWorklist::ProcessNextItem().
Referenced by v8::internal::MinorMarkSweepCollector::DrainMarkingWorklist(), and v8::internal::ConcurrentMarking::RunMinorImpl().
Member Data Documentation
handler_
YoungGenerationRememberedSetsMarkingWorklist* const v8::internal::YoungGenerationRememberedSetsMarkingWorklist::Local::handler_ [private]
Definition at line 49 of file minor-mark-sweep.h.
Referenced by ProcessNextItem().
index_
std::optional<size_t> v8::internal::YoungGenerationRememberedSetsMarkingWorklist::Local::index_ [private]
Definition at line 50 of file minor-mark-sweep.h.
Referenced by ProcessNextItem().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/minor-mark-sweep.h