v8::internal::BasicBlockProfilerData Class Reference
#include <basic-block-profiler.h>
Public Member Functions
BasicBlockProfilerData (size_t n_blocks)
V8_EXPORT_PRIVATE BasicBlockProfilerData (DirectHandle< OnHeapBasicBlockProfilerData > js_heap_data, Isolate *isolate)
V8_EXPORT_PRIVATE BasicBlockProfilerData (Tagged< OnHeapBasicBlockProfilerData > js_heap_data)
BasicBlockProfilerData (const BasicBlockProfilerData &)=delete
BasicBlockProfilerData & operator= (const BasicBlockProfilerData &)=delete
size_t n_blocks () const
const uint32_t * counts () const
void SetCode (const std::ostringstream &os)
void SetFunctionName (std::unique_ptr< char[]> name)
void SetSchedule (const std::ostringstream &os)
void SetBlockId (size_t offset, int32_t id)
void SetHash (int hash)
void AddBranch (int32_t true_block_id, int32_t false_block_id)
DirectHandle< OnHeapBasicBlockProfilerData > CopyToJSHeap (Isolate *isolate)
void Log (Isolate *isolate, std::ostream &os)
Private Member Functions
V8_EXPORT_PRIVATE void ResetCounts ()
void CopyFromJSHeap (Tagged< OnHeapBasicBlockProfilerData > js_heap_data)
Private Attributes
std::vector< int32_t > block_ids_
std::vector< uint32_t > counts_
std::vector< std::pair< int32_t, int32_t > > branches_
std::string function_name_
std::string schedule_
std::string code_
int hash_ = 0
Friends
class BasicBlockProfiler
std::ostream & operator<< (std::ostream &os, const BasicBlockProfilerData &s)
Detailed Description
Definition at line 24 of file basic-block-profiler.h.
Constructor & Destructor Documentation
BasicBlockProfilerData() [1/4]
v8::internal::BasicBlockProfilerData::BasicBlockProfilerData (size_t n_blocks) [explicit]
Definition at line 22 of file basic-block-profiler.cc.
    : block_ids_(n_blocks), counts_(n_blocks, 0) {}
BasicBlockProfilerData() [2/4]
v8::internal::BasicBlockProfilerData::BasicBlockProfilerData (DirectHandle< OnHeapBasicBlockProfilerData > js_heap_data, Isolate * isolate)
Definition at line 74 of file basic-block-profiler.cc.
                                                                               {
  DisallowHeapAllocation no_gc;
  CopyFromJSHeap(*js_heap_data);
}
References CopyFromJSHeap(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
BasicBlockProfilerData() [3/4]
v8::internal::BasicBlockProfilerData::BasicBlockProfilerData (Tagged< OnHeapBasicBlockProfilerData > js_heap_data)
Definition at line 80 of file basic-block-profiler.cc.
                                                       {
  CopyFromJSHeap(js_heap_data);
}
References CopyFromJSHeap().
BasicBlockProfilerData() [4/4]
v8::internal::BasicBlockProfilerData::BasicBlockProfilerData (const BasicBlockProfilerData &) [delete]
Member Function Documentation
AddBranch()
void v8::internal::BasicBlockProfilerData::AddBranch (int32_t true_block_id, int32_t false_block_id)
Definition at line 50 of file basic-block-profiler.cc.
                                                               {
  branches_.emplace_back(true_block_id, false_block_id);
}
References branches_.
Referenced by v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::Branch(), and v8::internal::compiler::BasicBlockInstrumentor::Instrument().
CopyFromJSHeap()
void v8::internal::BasicBlockProfilerData::CopyFromJSHeap (Tagged< OnHeapBasicBlockProfilerData > js_heap_data) [private]
Definition at line 85 of file basic-block-profiler.cc.
                                                       {
  function_name_ = js_heap_data->name()->ToStdString();
  schedule_ = js_heap_data->schedule()->ToStdString();
  code_ = js_heap_data->code()->ToStdString();
  Tagged<FixedUInt32Array> counts =
      Cast<FixedUInt32Array>(js_heap_data->counts());
  for (int i = 0; i < counts->length() / kBlockCountSlotSize; ++i) {
    counts_.push_back(counts->get(i));
  }
  Tagged<FixedInt32Array> block_ids(js_heap_data->block_ids());
  for (int i = 0; i < block_ids->length() / kBlockIdSlotSize; ++i) {
    block_ids_.push_back(block_ids->get(i));
  }
  Tagged<PodArray<std::pair<int32_t, int32_t>>> branches =
      js_heap_data->branches();
  for (int i = 0; i < branches->length(); ++i) {
    branches_.push_back(branches->get(i));
  }
  CHECK_EQ(block_ids_.size(), counts_.size());
  hash_ = js_heap_data->hash();
}
References block_ids_, branches_, CHECK_EQ, code_, counts(), counts_, function_name_, hash_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::anonymous_namespace{basic-block-profiler.cc}::kBlockCountSlotSize, v8::internal::anonymous_namespace{basic-block-profiler.cc}::kBlockIdSlotSize, and schedule_.
Referenced by BasicBlockProfilerData().
CopyToJSHeap()
DirectHandle< OnHeapBasicBlockProfilerData > v8::internal::BasicBlockProfilerData::CopyToJSHeap (Isolate * isolate)
Definition at line 108 of file basic-block-profiler.cc.
                      {
  int id_array_size_in_bytes = static_cast<int>(n_blocks() * kBlockIdSlotSize);
  CHECK(id_array_size_in_bytes >= 0 &&
        static_cast<size_t>(id_array_size_in_bytes) / kBlockIdSlotSize ==
            n_blocks()); // Overflow
  DirectHandle<FixedInt32Array> block_ids = FixedInt32Array::New(
      isolate, id_array_size_in_bytes, AllocationType::kOld);
  for (int i = 0; i < static_cast<int>(n_blocks()); ++i) {
    block_ids->set(i, block_ids_[i]);
  }
  int counts_array_size_in_bytes =
      static_cast<int>(n_blocks() * kBlockCountSlotSize);
  CHECK(counts_array_size_in_bytes >= 0 &&
        static_cast<size_t>(counts_array_size_in_bytes) / kBlockCountSlotSize ==
            n_blocks()); // Overflow
  DirectHandle<FixedUInt32Array> counts = FixedUInt32Array::New(
      isolate, counts_array_size_in_bytes, AllocationType::kOld);
  for (int i = 0; i < static_cast<int>(n_blocks()); ++i) {
    counts->set(i, counts_[i]);
  }
  DirectHandle<PodArray<std::pair<int32_t, int32_t>>> branches =
      PodArray<std::pair<int32_t, int32_t>>::New(
          isolate, static_cast<int>(branches_.size()), AllocationType::kOld);
  for (int i = 0; i < static_cast<int>(branches_.size()); ++i) {
    branches->set(i, branches_[i]);
  }
  DirectHandle<String> name = CopyStringToJSHeap(function_name_, isolate);
  DirectHandle<String> schedule = CopyStringToJSHeap(schedule_, isolate);
  DirectHandle<String> code = CopyStringToJSHeap(code_, isolate);
  return isolate->factory()->NewOnHeapBasicBlockProfilerData(
      block_ids, counts, branches, name, schedule, code, hash_,
      AllocationType::kOld);
}
References block_ids_, branches_, CHECK, code, code_, v8::internal::anonymous_namespace{basic-block-profiler.cc}::CopyStringToJSHeap(), counts(), counts_, v8::internal::Isolate::factory(), function_name_, hash_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::anonymous_namespace{basic-block-profiler.cc}::kBlockCountSlotSize, v8::internal::anonymous_namespace{basic-block-profiler.cc}::kBlockIdSlotSize, v8::internal::kOld, n_blocks(), v8::internal::name, v8::internal::anonymous_namespace{intl-objects.cc}::New(), v8::internal::FixedIntegerArrayBase< T, Base >::New(), and schedule_.
counts()
const uint32_t* v8::internal::BasicBlockProfilerData::counts () const [inline]
Definition at line 40 of file basic-block-profiler.h.
{ return &counts_[0]; }
References counts_.
Referenced by CopyFromJSHeap(), CopyToJSHeap(), v8::internal::compiler::BasicBlockInstrumentor::Instrument(), v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::LoadCounterValue(), and v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::StoreCounterValue().
Log()
void v8::internal::BasicBlockProfilerData::Log (Isolate * isolate, std::ostream & os)
Definition at line 221 of file basic-block-profiler.cc.
                                                                 {
  bool any_nonzero_counter = false;
  constexpr char kNext[] = "\t";
  for (size_t i = 0; i < n_blocks(); ++i) {
    if (counts_[i] > 0) {
      any_nonzero_counter = true;
      os << ProfileDataFromFileConstants::kBlockCounterMarker << kNext
         << function_name_.c_str() << kNext << block_ids_[i] << kNext
         << counts_[i] << '\n';
    }
  }
  if (any_nonzero_counter) {
    for (size_t i = 0; i < branches_.size(); ++i) {
      os << ProfileDataFromFileConstants::kBlockHintMarker << kNext
         << function_name_.c_str() << kNext << branches_[i].first << kNext
         << branches_[i].second << '\n';
    }
    os << ProfileDataFromFileConstants::kBuiltinHashMarker << kNext
       << function_name_.c_str() << kNext << hash_ << '\n';
  }
}
References block_ids_, branches_, counts_, function_name_, hash_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::ProfileDataFromFileConstants::kBlockCounterMarker, v8::internal::ProfileDataFromFileConstants::kBlockHintMarker, v8::internal::ProfileDataFromFileConstants::kBuiltinHashMarker, and n_blocks().
Referenced by v8::internal::BasicBlockProfiler::Log().
n_blocks()
size_t v8::internal::BasicBlockProfilerData::n_blocks () const [inline]
Definition at line 36 of file basic-block-profiler.h.
                          {
    DCHECK_EQ(block_ids_.size(), counts_.size());
    return block_ids_.size();
  }
References block_ids_, counts_, and DCHECK_EQ.
Referenced by CopyToJSHeap(), v8::internal::BasicBlockProfiler::GetCoverageBitmap(), Log(), ResetCounts(), and SetBlockId().
operator=()
BasicBlockProfilerData& v8::internal::BasicBlockProfilerData::operator= (const BasicBlockProfilerData &) [delete]
ResetCounts()
void v8::internal::BasicBlockProfilerData::ResetCounts () [private]
Definition at line 44 of file basic-block-profiler.cc.
                                         {
  for (size_t i = 0; i < n_blocks(); ++i) {
    counts_[i] = 0;
  }
}
References counts_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, and n_blocks().
SetBlockId()
void v8::internal::BasicBlockProfilerData::SetBlockId (size_t offset, int32_t id)
Definition at line 37 of file basic-block-profiler.cc.
                                                                 {
  DCHECK(offset < n_blocks());
  block_ids_[offset] = id;
}
References block_ids_, v8::internal::DCHECK(), and n_blocks().
Referenced by v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::Bind(), and v8::internal::compiler::BasicBlockInstrumentor::Instrument().
SetCode()
void v8::internal::BasicBlockProfilerData::SetCode (const std::ostringstream & os)
Definition at line 25 of file basic-block-profiler.cc.
                                                               {
  code_ = os.str();
}
References code_.
SetFunctionName()
void v8::internal::BasicBlockProfilerData::SetFunctionName (std::unique_ptr< char[]> name)
Definition at line 29 of file basic-block-profiler.cc.
                                                                       {
  function_name_ = name.get();
}
References function_name_, and v8::internal::name.
Referenced by v8::internal::compiler::BasicBlockInstrumentor::Instrument(), and v8::internal::compiler::turboshaft::Pipeline::PrepareForInstructionSelection().
SetHash()
void v8::internal::BasicBlockProfilerData::SetHash (int hash)
Definition at line 42 of file basic-block-profiler.cc.
{ hash_ = hash; }
References hash_.
Referenced by v8::internal::compiler::turboshaft::Pipeline::GenerateCode().
SetSchedule()
void v8::internal::BasicBlockProfilerData::SetSchedule (const std::ostringstream & os)
Definition at line 33 of file basic-block-profiler.cc.
                                                                   {
  schedule_ = os.str();
}
References schedule_.
Referenced by v8::internal::compiler::BasicBlockInstrumentor::Instrument(), and v8::internal::compiler::turboshaft::Pipeline::PrepareForInstructionSelection().
Friends And Related Function Documentation
BasicBlockProfiler
friend class BasicBlockProfiler [friend]
Definition at line 57 of file basic-block-profiler.h.
operator<<
std::ostream& operator<< (std::ostream & os, const BasicBlockProfilerData & s) [friend]
Definition at line 243 of file basic-block-profiler.cc.
                                                                        {
  if (std::all_of(d.counts_.cbegin(), d.counts_.cend(),
                  [](uint32_t count) { return count == 0; })) {
    // No data was collected for this function.
    return os;
  }
  const char* name = "unknown function";
  if (!d.function_name_.empty()) {
    name = d.function_name_.c_str();
  }
  if (!d.schedule_.empty()) {
    os << "schedule for " << name << " (B0 entered " << d.counts_[0]
       << " times)" << '\n';
    os << d.schedule_.c_str() << '\n';
  }
  os << "block counts for " << name << ":" << '\n';
  std::vector<std::pair<size_t, uint32_t>> pairs;
  pairs.reserve(d.n_blocks());
  for (size_t i = 0; i < d.n_blocks(); ++i) {
    pairs.push_back(std::make_pair(i, d.counts_[i]));
  }
  std::sort(
      pairs.begin(), pairs.end(),
      [=](std::pair<size_t, uint32_t> left, std::pair<size_t, uint32_t> right) {
        if (right.second == left.second) return left.first < right.first;
        return right.second < left.second;
      });
  for (auto it : pairs) {
    if (it.second == 0) break;
    os << "block B" << it.first << " : " << it.second << '\n';
  }
  os << '\n';
  if (!d.code_.empty()) {
    os << d.code_.c_str() << '\n';
  }
  return os;
}
Member Data Documentation
block_ids_
std::vector<int32_t> v8::internal::BasicBlockProfilerData::block_ids_ [private]
Definition at line 66 of file basic-block-profiler.h.
Referenced by CopyFromJSHeap(), CopyToJSHeap(), Log(), n_blocks(), and SetBlockId().
branches_
std::vector<std::pair<int32_t, int32_t> > v8::internal::BasicBlockProfilerData::branches_ [private]
Definition at line 68 of file basic-block-profiler.h.
Referenced by AddBranch(), CopyFromJSHeap(), CopyToJSHeap(), and Log().
code_
std::string v8::internal::BasicBlockProfilerData::code_ [private]
Definition at line 71 of file basic-block-profiler.h.
Referenced by CopyFromJSHeap(), CopyToJSHeap(), and SetCode().
counts_
std::vector<uint32_t> v8::internal::BasicBlockProfilerData::counts_ [private]
Definition at line 67 of file basic-block-profiler.h.
Referenced by CopyFromJSHeap(), CopyToJSHeap(), counts(), v8::internal::BasicBlockProfiler::GetCoverageBitmap(), Log(), n_blocks(), and ResetCounts().
function_name_
std::string v8::internal::BasicBlockProfilerData::function_name_ [private]
Definition at line 69 of file basic-block-profiler.h.
Referenced by CopyFromJSHeap(), CopyToJSHeap(), Log(), v8::internal::BasicBlockProfiler::Log(), v8::internal::BasicBlockProfiler::Print(), and SetFunctionName().
hash_
int v8::internal::BasicBlockProfilerData::hash_ = 0 [private]
Definition at line 72 of file basic-block-profiler.h.
Referenced by CopyFromJSHeap(), CopyToJSHeap(), Log(), and SetHash().
schedule_
std::string v8::internal::BasicBlockProfilerData::schedule_ [private]
Definition at line 70 of file basic-block-profiler.h.
Referenced by CopyFromJSHeap(), CopyToJSHeap(), and SetSchedule().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/diagnostics/basic-block-profiler.h
/mnt/V8SourceCode/src/diagnostics/basic-block-profiler.cc