v8::internal::StringHasher Class Reference
#include <string-hasher.h>
Public Member Functions
StringHasher ()=delete
Static Public Member Functions
template<typename char_t >
static uint32_t HashSequentialString (const char_t *chars, uint32_t length, uint64_t seed)
static uint32_t MakeArrayIndexHash (uint32_t value, uint32_t length)
static uint32_t GetTrivialHash (uint32_t length)
Static Public Attributes
static const int kZeroHash = 27
Detailed Description
Definition at line 34 of file string-hasher.h.
Constructor & Destructor Documentation
StringHasher()
v8::internal::StringHasher::StringHasher () [delete]
Member Function Documentation
GetTrivialHash()
uint32_t v8::internal::StringHasher::GetTrivialHash (uint32_t length) [inline], [static]
Definition at line 90 of file string-hasher-inl.h.
                                                     {
  DCHECK_GT(length, String::kMaxHashCalcLength);
  // The hash of a large string is simply computed from the length.
  // Ensure that the max length is small enough to be encoded without losing
  // information.
  static_assert(String::kMaxLength <= String::HashBits::kMax);
  uint32_t hash = length;
  return String::CreateHashFieldValue(hash, String::HashFieldType::kHash);
}
References v8::internal::Name::CreateHashFieldValue(), DCHECK_GT, v8::internal::Name::kHash, v8::base::BitField< T, shift, size, U >::kMax, v8::internal::String::kMaxHashCalcLength, v8::internal::String::kMaxLength, and v8::internal::length.
Referenced by HashSequentialString().
HashSequentialString()
template<typename char_t >
uint32_t v8::internal::StringHasher::HashSequentialString (const char_t * chars, uint32_t length, uint64_t seed) [inline], [static]
Definition at line 223 of file string-hasher-inl.h.
                                                                            {
  static_assert(std::is_integral_v<char_t>);
  static_assert(sizeof(char_t) <= 2);
  using uchar = std::make_unsigned_t<char_t>;
  const uchar* chars = reinterpret_cast<const uchar*>(chars_raw);
  DCHECK_IMPLIES(length > 0, chars != nullptr);
  if (length >= 1) {
    if (length <= String::kMaxIntegerIndexSize) {
      // Possible array or integer index; try to compute the array index hash.
      static_assert(String::kMaxArrayIndexSize <= String::kMaxIntegerIndexSize);
      detail::ArrayIndexT index;
      uint32_t i;
      switch (detail::TryParseArrayIndex(chars, length, i, index)) {
        case detail::kSuccess:
          DCHECK_LE(index, String::kMaxArrayIndex);
          return MakeArrayIndexHash(static_cast<uint32_t>(index), length);
        case detail::kNonIndex:
          // A non-index result from TryParseArrayIndex means we don't need to
          // check for integer indices.
          break;
        case detail::kOverflow: {
#if V8_HOST_ARCH_64_BIT
          // On 64-bit, we might have a valid integer index even if the value
          // overflowed an array index.
          static_assert(String::kMaxArrayIndexSize <
                        String::kMaxIntegerIndexSize);
          switch (detail::TryParseIntegerIndex(chars, length, i, index)) {
            case detail::kSuccess: {
              uint32_t hash = String::CreateHashFieldValue(
                  detail::GetUsableRapidHash(chars, length, seed),
                  String::HashFieldType::kIntegerIndex);
              if (Name::ContainsCachedArrayIndex(hash)) {
                // The hash accidentally looks like a cached index. Fix that by
                // setting a bit that looks like a longer-than-cacheable string
                // length.
                hash |= (String::kMaxCachedArrayIndexLength + 1)
                        << String::ArrayIndexLengthBits::kShift;
              }
              DCHECK(!Name::ContainsCachedArrayIndex(hash));
              return hash;
            }
            case detail::kNonIndex:
            case detail::kOverflow:
              break;
          }
#else
          static_assert(String::kMaxArrayIndexSize ==
                        String::kMaxIntegerIndexSize);
#endif
          break;
        }
      }
      // If the we failed to compute an index hash, this falls through into the
      // non-index hash case.
    } else if (length > String::kMaxHashCalcLength) {
      // We should never go down this path if we might have an index value.
      static_assert(String::kMaxHashCalcLength > String::kMaxIntegerIndexSize);
      static_assert(String::kMaxHashCalcLength > String::kMaxArrayIndexSize);
      return GetTrivialHash(length);
    }
  }
  // Non-index hash.
  return String::CreateHashFieldValue(
      detail::GetUsableRapidHash(chars, length, seed),
      String::HashFieldType::kHash);
}
References v8::internal::Name::ContainsCachedArrayIndex(), v8::internal::Name::CreateHashFieldValue(), v8::internal::DCHECK(), DCHECK_IMPLIES, DCHECK_LE, GetTrivialHash(), v8::internal::detail::GetUsableRapidHash(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::Name::kHash, v8::internal::Name::kIntegerIndex, v8::internal::Name::kMaxArrayIndex, v8::internal::Name::kMaxArrayIndexSize, v8::internal::Name::kMaxCachedArrayIndexLength, v8::internal::String::kMaxHashCalcLength, v8::internal::Name::kMaxIntegerIndexSize, v8::internal::detail::kNonIndex, v8::internal::detail::kOverflow, v8::base::BitField< T, shift, size, U >::kShift, v8::internal::detail::kSuccess, v8::internal::length, MakeArrayIndexHash(), and v8::internal::detail::TryParseArrayIndex().
Referenced by v8::internal::anonymous_namespace{strings-storage.cc}::ComputeStringHash(), v8::internal::SeededStringHasher::operator()(), v8::internal::SeqSubStringKey< SeqString >::SeqSubStringKey(), and v8::internal::HeapSnapshotJSONSerializer::StringHash().
MakeArrayIndexHash()
uint32_t v8::internal::StringHasher::MakeArrayIndexHash (uint32_t value, uint32_t length) [inline], [static]
Definition at line 100 of file string-hasher-inl.h.
                                                                         {
  // For array indexes mix the length into the hash as an array index could
  // be zero.
  DCHECK_LE(length, String::kMaxArrayIndexSize);
  DCHECK(TenToThe(String::kMaxCachedArrayIndexLength) <
         (1 << String::kArrayIndexValueBits));
  value <<= String::ArrayIndexValueBits::kShift;
  value |= length << String::ArrayIndexLengthBits::kShift;
  DCHECK(String::IsIntegerIndex(value));
  DCHECK_EQ(length <= String::kMaxCachedArrayIndexLength,
            Name::ContainsCachedArrayIndex(value));
  return value;
}
References v8::internal::Name::ContainsCachedArrayIndex(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LE, v8::internal::Name::IsIntegerIndex(), v8::internal::Name::kArrayIndexValueBits, v8::internal::Name::kMaxArrayIndexSize, v8::internal::Name::kMaxCachedArrayIndexLength, v8::base::BitField< T, shift, size, U >::kShift, v8::internal::length, v8::internal::TenToThe(), and v8::internal::value.
Referenced by HashSequentialString(), v8::internal::Factory::SizeToString(), and v8::internal::FactoryBase< Impl >::SmiToString().
Member Data Documentation
kZeroHash
const int v8::internal::StringHasher::kZeroHash = 27 [static]
Definition at line 49 of file string-hasher.h.
Referenced by v8::internal::detail::ConvertRawHashToUsableHash().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/strings/string-hasher.h
/mnt/V8SourceCode/src/strings/string-hasher-inl.h