v8::internal::GCCallbacksInSafepoint Class Reference
#include <gc-callbacks.h>
Classes
struct CallbackData
Public Types
enum GCType { kLocal = 1 << 0
, kShared = 1 << 1
, kAll = kLocal | kShared
 }
using CallbackType = void(*)(void *)
Public Member Functions
void Add (CallbackType callback, void *data, GCType gc_type)
void Remove (CallbackType callback, void *data)
void Invoke (GCType gc_type) const
bool IsEmpty () const
Private Member Functions
std::vector< CallbackData >::iterator FindCallback (CallbackType callback, void *data)
Private Attributes
std::vector< CallbackData > callbacks_
Detailed Description
Definition at line 96 of file gc-callbacks.h.
Member Typedef Documentation
CallbackType
using v8::internal::GCCallbacksInSafepoint::CallbackType = void (*)(void*)
Definition at line 98 of file gc-callbacks.h.
Member Enumeration Documentation
GCType
enum v8::internal::GCCallbacksInSafepoint::GCType
Enumerator
kLocal
kShared
kAll
Definition at line 100 of file gc-callbacks.h.
{ kLocal = 1 << 0, kShared = 1 << 1, kAll = kLocal | kShared };
Member Function Documentation
Add()
void v8::internal::GCCallbacksInSafepoint::Add (CallbackType callback, void * data, GCType gc_type) [inline]
Definition at line 102 of file gc-callbacks.h.
                                                              {
    DCHECK_NOT_NULL(callback);
    DCHECK_EQ(callbacks_.end(), FindCallback(callback, data));
    callbacks_.emplace_back(callback, data, gc_type);
  }
References callbacks_, DCHECK_EQ, DCHECK_NOT_NULL, and FindCallback().
Referenced by v8::internal::LocalHeap::AddGCEpilogueCallback().
FindCallback()
std::vector<CallbackData>::iterator v8::internal::GCCallbacksInSafepoint::FindCallback (CallbackType callback, void * data) [inline], [private]
Definition at line 135 of file gc-callbacks.h.
                                                               {
    return std::find_if(callbacks_.begin(), callbacks_.end(),
                        [callback, data](CallbackData& callback_data) {
                          return callback_data.callback == callback &&
                                 callback_data.user_data == data;
                        });
  }
References callbacks_.
Referenced by Add(), and Remove().
Invoke()
void v8::internal::GCCallbacksInSafepoint::Invoke (GCType gc_type) const [inline]
Definition at line 115 of file gc-callbacks.h.
                                    {
    DisallowGarbageCollection scope;
    for (const CallbackData& callback_data : callbacks_) {
      if (callback_data.gc_type_ & gc_type)
        callback_data.callback(callback_data.user_data);
    }
  }
References callbacks_.
Referenced by v8::internal::LocalHeap::InvokeGCEpilogueCallbacksInSafepoint().
IsEmpty()
bool v8::internal::GCCallbacksInSafepoint::IsEmpty () const [inline]
Definition at line 123 of file gc-callbacks.h.
{ return callbacks_.empty(); }
References callbacks_.
Referenced by v8::internal::LocalHeap::~LocalHeap().
Remove()
void v8::internal::GCCallbacksInSafepoint::Remove (CallbackType callback, void * data) [inline]
Definition at line 108 of file gc-callbacks.h.
                                                 {
    auto it = FindCallback(callback, data);
    DCHECK_NE(callbacks_.end(), it);
    *it = callbacks_.back();
    callbacks_.pop_back();
  }
References callbacks_, DCHECK_NE, and FindCallback().
Referenced by v8::internal::LocalHeap::RemoveGCEpilogueCallback().
Member Data Documentation
callbacks_
std::vector<CallbackData> v8::internal::GCCallbacksInSafepoint::callbacks_ [private]
Definition at line 144 of file gc-callbacks.h.
Referenced by Add(), FindCallback(), Invoke(), IsEmpty(), and Remove().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/gc-callbacks.h