v8::WasmMemoryObject Class Reference
#include <v8-wasm.h>
Public Member Functions
WasmMemoryObject ()=delete
Local< ArrayBuffer > Buffer ()
Returns underlying ArrayBuffer.
Static Public Member Functions
static WasmMemoryObject * Cast (Value *value)
Static Private Member Functions
static void CheckCast (Value *object)
Additional Inherited Members
Detailed Description
Definition at line 70 of file v8-wasm.h.
Constructor & Destructor Documentation
WasmMemoryObject()
v8::WasmMemoryObject::WasmMemoryObject () [delete]
Member Function Documentation
Buffer()
Local< ArrayBuffer > v8::WasmMemoryObject::Buffer ()
Returns underlying ArrayBuffer.
Definition at line 8806 of file api.cc.
                                              {
#if V8_ENABLE_WEBASSEMBLY
  auto obj = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  return Utils::ToLocal(i::direct_handle(obj->array_buffer(), i_isolate));
#else
  UNREACHABLE();
#endif // V8_ENABLE_WEBASSEMBLY
}
References v8::internal::Isolate::Current(), v8::internal::direct_handle(), v8::Utils::OpenDirectHandle(), and UNREACHABLE.
Cast()
static WasmMemoryObject* v8::WasmMemoryObject::Cast (Value * value) [inline], [static]
Definition at line 79 of file v8-wasm.h.
                                                        {
#ifdef V8_ENABLE_CHECKS
    CheckCast(value);
#endif
    return static_cast<WasmMemoryObject*>(value);
  }
References v8::internal::value.
CheckCast()
void v8::WasmMemoryObject::CheckCast (Value * object) [static], [private]
Definition at line 3991 of file api.cc.
                                              {
  Utils::ApiCheck(that->IsWasmMemoryObject(), "v8::WasmMemoryObject::Cast",
                  "Value is not a WasmMemoryObject");
}
References v8::Utils::ApiCheck(), and v8::Value::IsWasmMemoryObject().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-wasm.h
/mnt/V8SourceCode/src/api/api.cc