v8::internal::compiler::ExitMachineGraphParameters Class Reference
#include <common-operator.h>
Public Member Functions
ExitMachineGraphParameters (MachineRepresentation output_representation, Type output_type)
MachineRepresentation output_representation () const
const Type & output_type () const
Private Attributes
const MachineRepresentation output_representation_
const Type output_type_
Detailed Description
Definition at line 511 of file common-operator.h.
Constructor & Destructor Documentation
ExitMachineGraphParameters()
v8::internal::compiler::ExitMachineGraphParameters::ExitMachineGraphParameters (MachineRepresentation output_representation, Type output_type) [inline]
Definition at line 513 of file common-operator.h.
      : output_representation_(output_representation),
        output_type_(output_type) {}
Member Function Documentation
output_representation()
MachineRepresentation v8::internal::compiler::ExitMachineGraphParameters::output_representation () const [inline]
Definition at line 518 of file common-operator.h.
                                                      {
    return output_representation_;
  }
References output_representation_.
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), and v8::internal::compiler::operator==().
output_type()
const Type& v8::internal::compiler::ExitMachineGraphParameters::output_type () const [inline]
Definition at line 522 of file common-operator.h.
{ return output_type_; }
References output_type_.
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), and v8::internal::compiler::operator==().
Member Data Documentation
output_representation_
const MachineRepresentation v8::internal::compiler::ExitMachineGraphParameters::output_representation_ [private]
Definition at line 525 of file common-operator.h.
Referenced by output_representation().
output_type_
const Type v8::internal::compiler::ExitMachineGraphParameters::output_type_ [private]
Definition at line 526 of file common-operator.h.
Referenced by output_type().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/common-operator.h