v8::internal::RegExpBackReference Class Reference
#include <regexp-ast.h>
Public Member Functions
RegExpBackReference (Zone *zone)
RegExpBackReference (RegExpCapture *capture, Zone *zone)
DECL_BOILERPLATE (BackReference)
int min_match () override
int max_match () override
const ZoneList< RegExpCapture * > * captures () const
void add_capture (RegExpCapture *capture, Zone *zone)
const ZoneVector< base::uc16 > * name () const
void set_name (const ZoneVector< base::uc16 > *name)
Private Attributes
ZoneList< RegExpCapture * > captures_
const ZoneVector< base::uc16 > * name_ = nullptr
Additional Inherited Members
Detailed Description
Definition at line 711 of file regexp-ast.h.
Constructor & Destructor Documentation
RegExpBackReference() [1/2]
v8::internal::RegExpBackReference::RegExpBackReference (Zone * zone) [inline], [explicit]
Definition at line 713 of file regexp-ast.h.
: captures_(1, zone) {}
RegExpBackReference() [2/2]
v8::internal::RegExpBackReference::RegExpBackReference (RegExpCapture * capture, Zone * zone) [inline], [explicit]
Definition at line 714 of file regexp-ast.h.
      : captures_(1, zone) {
    captures_.Add(capture, zone);
  }
References captures_.
Member Function Documentation
add_capture()
void v8::internal::RegExpBackReference::add_capture (RegExpCapture * capture, Zone * zone) [inline]
Definition at line 726 of file regexp-ast.h.
                                                       {
    captures_.Add(capture, zone);
  }
References captures_.
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::PatchNamedBackReferences().
captures()
const ZoneList<RegExpCapture*>* v8::internal::RegExpBackReference::captures () const [inline]
Definition at line 725 of file regexp-ast.h.
{ return &captures_; }
References captures_.
DECL_BOILERPLATE()
v8::internal::RegExpBackReference::DECL_BOILERPLATE (BackReference)
max_match()
int v8::internal::RegExpBackReference::max_match () [inline], [override], [virtual]
Implements v8::internal::RegExpTree.
Definition at line 724 of file regexp-ast.h.
{ return kInfinity; }
References v8::internal::RegExpTree::kInfinity.
min_match()
int v8::internal::RegExpBackReference::min_match () [inline], [override], [virtual]
Implements v8::internal::RegExpTree.
Definition at line 721 of file regexp-ast.h.
{ return 0; }
name()
const ZoneVector<base::uc16>* v8::internal::RegExpBackReference::name () const [inline]
Definition at line 729 of file regexp-ast.h.
{ return name_; }
References name_.
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::PatchNamedBackReferences(), and set_name().
set_name()
void v8::internal::RegExpBackReference::set_name (const ZoneVector< base::uc16 > * name) [inline]
Definition at line 730 of file regexp-ast.h.
{ name_ = name; }
References name(), and name_.
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseNamedBackReference().
Member Data Documentation
captures_
ZoneList<RegExpCapture*> v8::internal::RegExpBackReference::captures_ [private]
Definition at line 733 of file regexp-ast.h.
Referenced by add_capture(), captures(), and RegExpBackReference().
name_
const ZoneVector<base::uc16>* v8::internal::RegExpBackReference::name_ = nullptr [private]
Definition at line 734 of file regexp-ast.h.
Referenced by name(), and set_name().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/regexp/regexp-ast.h