v8::internal::CodeTraceContext Class Reference
#include <code-trace-context.h>
Public Member Functions
CodeTraceContext (CodeDataSource::TraceContext::TracePacketHandle trace_packet, CodeDataSourceIncrementalState *incremental_state)
CodeTraceContext (CodeTraceContext &&) V8_NOEXCEPT=default
~CodeTraceContext ()
uint64_t InternIsolate (Isolate &isolate)
uint64_t InternJsScript (Isolate &isolate, Tagged< Script > script)
uint64_t InternJsFunction (Isolate &isolate, DirectHandle< SharedFunctionInfo > info, uint64_t v8_js_script_iid, int line_num, int column_num)
perfetto::protos::pbzero::V8JsCode * set_v8_js_code ()
perfetto::protos::pbzero::V8InternalCode * set_v8_internal_code ()
perfetto::protos::pbzero::V8WasmCode * set_v8_wasm_code ()
perfetto::protos::pbzero::V8RegExpCode * set_v8_reg_exp_code ()
perfetto::protos::pbzero::V8CodeMove * set_code_move ()
bool log_script_sources () const
bool log_instructions () const
Private Attributes
CodeDataSource::TraceContext::TracePacketHandle trace_packet_
CodeDataSourceIncrementalState & incremental_state_
Detailed Description
Definition at line 30 of file code-trace-context.h.
Constructor & Destructor Documentation
CodeTraceContext() [1/2]
v8::internal::CodeTraceContext::CodeTraceContext (CodeDataSource::TraceContext::TracePacketHandle trace_packet, CodeDataSourceIncrementalState * incremental_state) [inline]
Definition at line 32 of file code-trace-context.h.
      : trace_packet_(std::move(trace_packet)),
        incremental_state_(*incremental_state) {}
CodeTraceContext() [2/2]
v8::internal::CodeTraceContext::CodeTraceContext (CodeTraceContext &&) [default]
 CodeTraceContext()
v8::internal::CodeTraceContext::~CodeTraceContext () [inline]
Definition at line 39 of file code-trace-context.h.
                      {
    if (V8_UNLIKELY(incremental_state_.has_buffered_interned_data())) {
      incremental_state_.FlushInternedData(trace_packet_);
    }
  }
References v8::internal::CodeDataSourceIncrementalState::FlushInternedData(), v8::internal::CodeDataSourceIncrementalState::has_buffered_interned_data(), incremental_state_, trace_packet_, and V8_UNLIKELY.
Member Function Documentation
InternIsolate()
uint64_t v8::internal::CodeTraceContext::InternIsolate (Isolate & isolate) [inline]
Definition at line 45 of file code-trace-context.h.
                                           {
    return incremental_state_.InternIsolate(isolate);
  }
References incremental_state_, and v8::internal::CodeDataSourceIncrementalState::InternIsolate().
Referenced by v8::internal::PerfettoLogger::BytecodeMoveEvent(), v8::internal::PerfettoLogger::CodeCreateEvent(), v8::internal::PerfettoLogger::CodeMoveEvent(), and v8::internal::PerfettoLogger::RegExpCodeCreateEvent().
InternJsFunction()
uint64_t v8::internal::CodeTraceContext::InternJsFunction (Isolate & isolate, DirectHandle< SharedFunctionInfo > info, uint64_t v8_js_script_iid, int line_num, int column_num) [inline]
Definition at line 53 of file code-trace-context.h.
                                            {
    return incremental_state_.InternJsFunction(isolate, info, v8_js_script_iid,
                                               line_num, column_num);
  }
References incremental_state_, and v8::internal::CodeDataSourceIncrementalState::InternJsFunction().
Referenced by v8::internal::PerfettoLogger::CodeCreateEvent().
InternJsScript()
uint64_t v8::internal::CodeTraceContext::InternJsScript (Isolate & isolate, Tagged< Script > script) [inline]
Definition at line 49 of file code-trace-context.h.
                                                                   {
    return incremental_state_.InternJsScript(isolate, script);
  }
References incremental_state_, v8::internal::CodeDataSourceIncrementalState::InternJsScript(), and v8::internal::script.
Referenced by v8::internal::PerfettoLogger::CodeCreateEvent().
log_instructions()
bool v8::internal::CodeTraceContext::log_instructions () const [inline]
Definition at line 94 of file code-trace-context.h.
                                {
    return incremental_state_.log_instructions();
  }
References incremental_state_, and v8::internal::CodeDataSourceIncrementalState::log_instructions().
Referenced by v8::internal::PerfettoLogger::BytecodeMoveEvent(), v8::internal::PerfettoLogger::CodeCreateEvent(), v8::internal::PerfettoLogger::CodeMoveEvent(), v8::internal::PerfettoLogger::RegExpCodeCreateEvent(), and v8::internal::anonymous_namespace{perfetto-logger.cc}::WriteJsCode().
log_script_sources()
bool v8::internal::CodeTraceContext::log_script_sources () const [inline]
Definition at line 90 of file code-trace-context.h.
                                  {
    return incremental_state_.log_script_sources();
  }
References incremental_state_, and v8::internal::CodeDataSourceIncrementalState::log_script_sources().
set_code_move()
perfetto::protos::pbzero::V8CodeMove* v8::internal::CodeTraceContext::set_code_move () [inline]
Definition at line 86 of file code-trace-context.h.
                                                  {
    return trace_packet_->set_v8_code_move();
  }
References trace_packet_.
Referenced by v8::internal::PerfettoLogger::BytecodeMoveEvent(), and v8::internal::PerfettoLogger::CodeMoveEvent().
set_v8_internal_code()
perfetto::protos::pbzero::V8InternalCode* v8::internal::CodeTraceContext::set_v8_internal_code () [inline]
Definition at line 74 of file code-trace-context.h.
                                                             {
    return trace_packet_->set_v8_internal_code();
  }
References trace_packet_.
Referenced by v8::internal::PerfettoLogger::CodeCreateEvent().
set_v8_js_code()
perfetto::protos::pbzero::V8JsCode* v8::internal::CodeTraceContext::set_v8_js_code () [inline]
Definition at line 70 of file code-trace-context.h.
                                                 {
    return trace_packet_->set_v8_js_code();
  }
References trace_packet_.
Referenced by v8::internal::PerfettoLogger::CodeCreateEvent().
set_v8_reg_exp_code()
perfetto::protos::pbzero::V8RegExpCode* v8::internal::CodeTraceContext::set_v8_reg_exp_code () [inline]
Definition at line 82 of file code-trace-context.h.
                                                          {
    return trace_packet_->set_v8_reg_exp_code();
  }
References trace_packet_.
Referenced by v8::internal::PerfettoLogger::RegExpCodeCreateEvent().
set_v8_wasm_code()
perfetto::protos::pbzero::V8WasmCode* v8::internal::CodeTraceContext::set_v8_wasm_code () [inline]
Definition at line 78 of file code-trace-context.h.
                                                     {
    return trace_packet_->set_v8_wasm_code();
  }
References trace_packet_.
Member Data Documentation
incremental_state_
CodeDataSourceIncrementalState& v8::internal::CodeTraceContext::incremental_state_ [private]
Definition at line 100 of file code-trace-context.h.
Referenced by InternIsolate(), InternJsFunction(), InternJsScript(), log_instructions(), log_script_sources(), and ~CodeTraceContext().
trace_packet_
CodeDataSource::TraceContext::TracePacketHandle v8::internal::CodeTraceContext::trace_packet_ [private]
Definition at line 99 of file code-trace-context.h.
Referenced by set_code_move(), set_v8_internal_code(), set_v8_js_code(), set_v8_reg_exp_code(), set_v8_wasm_code(), and ~CodeTraceContext().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/tracing/code-trace-context.h