v8::Date Class Reference
An instance of the built-in Date constructor (ECMA-262, 15.9).
#include <v8-date.h>
Public Member Functions
double ValueOf () const
A specialization of Value::NumberValue that is more efficient because we know the structure of this object.
v8::Local< v8::String > ToISOString () const
Generates ISO string representation.
v8::Local< v8::String > ToUTCString () const
Generates UTC string representation.
Static Public Member Functions
static V8_WARN_UNUSED_RESULT MaybeLocal< Value > New (Local< Context > context, double time)
static V8_WARN_UNUSED_RESULT MaybeLocal< Value > Parse (Local< Context > context, Local< String > date_string)
static Date * Cast (Value *value)
Static Private Member Functions
static void CheckCast (Value *obj)
Additional Inherited Members
Detailed Description
An instance of the built-in Date constructor (ECMA-262, 15.9).
Definition at line 19 of file v8-date.h.
Member Function Documentation
Cast()
static Date* v8::Date::Cast (Value * value) [inline], [static]
Definition at line 44 of file v8-date.h.
                                            {
#ifdef V8_ENABLE_CHECKS
    CheckCast(value);
#endif
    return static_cast<Date*>(value);
  }
References v8::internal::value.
CheckCast()
void v8::Date::CheckCast (v8::Value * that) [static], [private]
Definition at line 4130 of file api.cc.
                                    {
  auto obj = *Utils::OpenDirectHandle(that);
  Utils::ApiCheck(i::IsJSDate(obj), "v8::Date::Cast()", "Value is not a Date");
}
References v8::Utils::ApiCheck(), and v8::Utils::OpenDirectHandle().
New()
MaybeLocal< v8::Value > v8::Date::New (Local< Context > context, double time) [static]
Definition at line 7948 of file api.cc.
                                                                   {
  if (std::isnan(time)) {
    // Introduce only canonical NaN value into the VM, to avoid signaling NaNs.
    time = std::numeric_limits<double>::quiet_NaN();
  }
  PrepareForExecutionScope api_scope{context, RCCId::kAPI_Date_New};
  i::Isolate* i_isolate = api_scope.i_isolate();
  return api_scope.EscapeMaybe(
      Utils::ToMaybeLocal(i::JSDate::New(i_isolate, i_isolate->date_function(),
                                         i_isolate->date_function(), time)));
}
References v8::internal::JSDate::New(), time(), and v8::Utils::ToMaybeLocal().
Parse()
MaybeLocal< Value > v8::Date::Parse (Local< Context > context, Local< String > date_string) [static]
Definition at line 7960 of file api.cc.
                                                                           {
  PrepareForExecutionScope api_scope{context, RCCId::kAPI_Date_Parse};
  i::Isolate* i_isolate = api_scope.i_isolate();
  auto string = Utils::OpenDirectHandle(*value);
  double time = ParseDateTimeString(i_isolate, string);
  return api_scope.EscapeMaybe(
      Utils::ToMaybeLocal(i::JSDate::New(i_isolate, i_isolate->date_function(),
                                         i_isolate->date_function(), time)));
}
References v8::internal::JSDate::New(), v8::Utils::OpenDirectHandle(), v8::internal::ParseDateTimeString(), time(), v8::Utils::ToMaybeLocal(), and v8::internal::value.
ToISOString()
v8::Local< v8::String > v8::Date::ToISOString () const
Generates ISO string representation.
Definition at line 7977 of file api.cc.
                                            {
  auto obj = Utils::OpenDirectHandle(this);
  auto jsdate = i::Cast<i::JSDate>(obj);
  i::Isolate* i_isolate = i::Isolate::Current();
  i::DateBuffer buffer =
      i::ToDateString(jsdate->value(), i_isolate->date_cache(),
                      i::ToDateStringMode::kISODateAndTime);
  i::DirectHandle<i::String> str =
      i_isolate->factory()
          ->NewStringFromUtf8(base::VectorOf(buffer))
          .ToHandleChecked();
  return Utils::ToLocal(str);
}
References v8::internal::Isolate::Current(), v8::internal::Isolate::date_cache(), v8::internal::Isolate::factory(), v8::internal::Factory::NewStringFromUtf8(), v8::Utils::OpenDirectHandle(), v8::internal::ToDateString(), and v8::base::VectorOf().
ToUTCString()
v8::Local< v8::String > v8::Date::ToUTCString () const
Generates UTC string representation.
Definition at line 7991 of file api.cc.
                                            {
  auto obj = Utils::OpenDirectHandle(this);
  auto jsdate = i::Cast<i::JSDate>(obj);
  i::Isolate* i_isolate = i::Isolate::Current();
  i::DateBuffer buffer =
      i::ToDateString(jsdate->value(), i_isolate->date_cache(),
                      i::ToDateStringMode::kUTCDateAndTime);
  i::DirectHandle<i::String> str =
      i_isolate->factory()
          ->NewStringFromUtf8(base::VectorOf(buffer))
          .ToHandleChecked();
  return Utils::ToLocal(str);
}
References v8::internal::Isolate::Current(), v8::internal::Isolate::date_cache(), v8::internal::Isolate::factory(), v8::internal::Factory::NewStringFromUtf8(), v8::Utils::OpenDirectHandle(), v8::internal::ToDateString(), and v8::base::VectorOf().
ValueOf()
double v8::Date::ValueOf () const
A specialization of Value::NumberValue that is more efficient because we know the structure of this object.
Definition at line 7971 of file api.cc.
                             {
  auto obj = Utils::OpenDirectHandle(this);
  auto jsdate = i::Cast<i::JSDate>(obj);
  return jsdate->value();
}
References v8::Utils::OpenDirectHandle().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-date.h
/mnt/V8SourceCode/src/api/api.cc