v8::internal::OrderedNameDictionary Class Reference
#include <ordered-hash-table.h>
Public Member Functions
void SetEntry (InternalIndex entry, Tagged< Object > key, Tagged< Object > value, PropertyDetails details)
template<typename IsolateT >
InternalIndex FindEntry (IsolateT *isolate, Tagged< Object > key)
template<typename IsolateT >
InternalIndex FindEntry (IsolateT *isolate, DirectHandle< Object > key)
template<template< typename > typename HandleType>
requires(std::is_convertible_v< HandleType< OrderedNameDictionary >, DirectHandle< OrderedNameDictionary >>) static HandleType< OrderedNameDictionary > Tagged< Object > ValueAt (InternalIndex entry)
Tagged< Name > NameAt (InternalIndex entry)
void ValueAtPut (InternalIndex entry, Tagged< Object > value)
PropertyDetails DetailsAt (InternalIndex entry)
void DetailsAtPut (InternalIndex entry, PropertyDetails value)
void SetHash (int hash)
int Hash ()
Static Public Member Functions
static MaybeHandle< OrderedNameDictionary > Add (Isolate *isolate, Handle< OrderedNameDictionary > table, DirectHandle< Name > key, DirectHandle< Object > value, PropertyDetails details)
static Handle< OrderedNameDictionary > DeleteEntry (Isolate *isolate, Handle< OrderedNameDictionary > table, InternalIndex entry)
static MaybeHandle< OrderedNameDictionary > Allocate (Isolate *isolate, int capacity, AllocationType allocation=AllocationType::kYoung)
static MaybeHandle< OrderedNameDictionary > AllocateEmpty (Isolate *isolate, AllocationType allocation=AllocationType::kReadOnly)
static Tagged< HeapObject > GetEmpty (ReadOnlyRoots ro_roots)
static Handle< Map > GetMap (RootsTable &roots)
static bool Is (DirectHandle< HeapObject > table)
static constexpr int HashIndex ()
Static Public Attributes
static const int kValueOffset = 1
static const int kPropertyDetailsOffset = 2
static const int kPrefixSize = 1
static const bool kIsOrderedDictionaryType = true
Private Types
using Base = OrderedHashTable< OrderedNameDictionary, 3 >
Additional Inherited Members
Detailed Description
Definition at line 777 of file ordered-hash-table.h.
Member Typedef Documentation
Base
using v8::internal::OrderedNameDictionary::Base = OrderedHashTable<OrderedNameDictionary, 3> [private]
Definition at line 779 of file ordered-hash-table.h.
Member Function Documentation
Add()
MaybeHandle< OrderedNameDictionary > v8::internal::OrderedNameDictionary::Add (Isolate * isolate, Handle< OrderedNameDictionary > table, DirectHandle< Name > key, DirectHandle< Object > value, PropertyDetails details) [static]
Definition at line 531 of file ordered-hash-table.cc.
                             {
  DCHECK(IsUniqueName(*key));
  DCHECK(table->FindEntry(isolate, *key).is_not_found());
  MaybeHandle<OrderedNameDictionary> table_candidate =
      OrderedNameDictionary::EnsureCapacityForAdding(isolate, table);
  if (!table_candidate.ToHandle(&table)) {
    return table_candidate;
  }
  DisallowGarbageCollection no_gc;
  Tagged<OrderedNameDictionary> raw_table = *table;
  // Read the existing bucket values.
  int hash = key->hash();
  int bucket = raw_table->HashToBucket(hash);
  int previous_entry = raw_table->HashToEntryRaw(hash);
  int nof = raw_table->NumberOfElements();
  // Insert a new entry at the end,
  int new_entry = nof + raw_table->NumberOfDeletedElements();
  int new_index = raw_table->EntryToIndexRaw(new_entry);
  raw_table->set(new_index, *key);
  raw_table->set(new_index + kValueOffset, *value);
  // TODO(gsathya): Optimize how PropertyDetails are stored in this
  // dictionary to save memory (by reusing padding?) and performance
  // (by not doing the Smi conversion).
  raw_table->set(new_index + kPropertyDetailsOffset, details.AsSmi());
  raw_table->set(new_index + kChainOffset, Smi::FromInt(previous_entry));
  // and point the bucket to the new entry.
  raw_table->set(HashTableStartIndex() + bucket, Smi::FromInt(new_entry));
  raw_table->SetNumberOfElements(nof + 1);
  return table;
}
References v8::internal::PropertyDetails::AsSmi(), v8::internal::DCHECK(), v8::internal::Smi::FromInt(), v8::internal::OrderedHashTable< OrderedNameDictionary, 3 >::HashTableStartIndex(), v8::internal::IsUniqueName(), v8::internal::OrderedHashTable< OrderedNameDictionary, 3 >::kChainOffset, v8::internal::key, kPropertyDetailsOffset, kValueOffset, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::OrderedHashTable< OrderedNameDictionary, 3 >::table, v8::internal::MaybeHandle< T >::ToHandle(), and v8::internal::FixedArray::value.
Allocate()
MaybeHandle< OrderedNameDictionary > v8::internal::OrderedNameDictionary::Allocate (Isolate * isolate, int capacity, AllocationType allocation = AllocationType::kYoung) [static]
Definition at line 614 of file ordered-hash-table.cc.
                                                               {
  MaybeHandle<OrderedNameDictionary> table_candidate =
      Base::Allocate(isolate, capacity, allocation);
  DirectHandle<OrderedNameDictionary> table;
  if (table_candidate.ToHandle(&table)) {
    table->SetHash(PropertyArray::kNoHashSentinel);
  }
  return table_candidate;
}
References v8::internal::OrderedHashTable< OrderedNameDictionary, 3 >::Allocate(), v8::internal::PropertyArray::kNoHashSentinel, v8::internal::OrderedHashTable< OrderedNameDictionary, 3 >::table, and v8::internal::MaybeHandle< T >::ToHandle().
AllocateEmpty()
MaybeHandle< OrderedNameDictionary > v8::internal::OrderedNameDictionary::AllocateEmpty (Isolate * isolate, AllocationType allocation = AllocationType::kReadOnly) [static]
Definition at line 637 of file ordered-hash-table.cc.
                                                 {
  RootIndex ri = RootIndex::kEmptyOrderedPropertyDictionary;
  MaybeHandle<OrderedNameDictionary> table_candidate =
      Base::AllocateEmpty(isolate, allocation, ri);
  DirectHandle<OrderedNameDictionary> table;
  if (table_candidate.ToHandle(&table)) {
    table->SetHash(PropertyArray::kNoHashSentinel);
  }
  return table_candidate;
}
References v8::internal::OrderedHashTable< OrderedNameDictionary, 3 >::AllocateEmpty(), v8::internal::PropertyArray::kNoHashSentinel, v8::internal::OrderedHashTable< OrderedNameDictionary, 3 >::table, and v8::internal::MaybeHandle< T >::ToHandle().
Referenced by v8::internal::Heap::CreateImportantReadOnlyObjects().
DeleteEntry()
Handle< OrderedNameDictionary > v8::internal::OrderedNameDictionary::DeleteEntry (Isolate * isolate, Handle< OrderedNameDictionary > table, InternalIndex entry) [static]
Definition at line 584 of file ordered-hash-table.cc.
                         {
  DCHECK(entry.is_found());
  Tagged<Object> hash_table_hole =
      ReadOnlyRoots(isolate).hash_table_hole_value();
  PropertyDetails details = PropertyDetails::Empty();
  table->SetEntry(entry, hash_table_hole, hash_table_hole, details);
  int nof = table->NumberOfElements();
  table->SetNumberOfElements(nof - 1);
  int nod = table->NumberOfDeletedElements();
  table->SetNumberOfDeletedElements(nod + 1);
  return Shrink(isolate, table);
}
References v8::internal::DCHECK(), v8::internal::PropertyDetails::Empty(), v8::internal::InternalIndex::is_found(), cppgc::internal::anonymous_namespace{explicit-management.cc}::Shrink(), and v8::internal::OrderedHashTable< OrderedNameDictionary, 3 >::table.
DetailsAt()
PropertyDetails v8::internal::OrderedNameDictionary::DetailsAt (InternalIndex entry) [inline]
Definition at line 117 of file ordered-hash-table-inl.h.
                                                                           {
  DCHECK_LT(entry.as_int(), this->UsedCapacity());
  // TODO(gsathya): Optimize the cast away.
  return PropertyDetails(
      Cast<Smi>(get(EntryToIndex(entry) + kPropertyDetailsOffset)));
}
References v8::internal::InternalIndex::as_int(), DCHECK_LT, v8::internal::OrderedHashTable< OrderedNameDictionary, 3 >::EntryToIndex(), v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::get(), kPropertyDetailsOffset, and v8::internal::this.
DetailsAtPut()
void v8::internal::OrderedNameDictionary::DetailsAtPut (InternalIndex entry, PropertyDetails value) [inline]
Definition at line 124 of file ordered-hash-table-inl.h.
                                                                       {
  DCHECK_LT(entry.as_int(), this->UsedCapacity());
  // TODO(gsathya): Optimize the cast away.
  this->set(EntryToIndex(entry) + kPropertyDetailsOffset, value.AsSmi());
}
References v8::internal::InternalIndex::as_int(), DCHECK_LT, v8::internal::OrderedHashTable< OrderedNameDictionary, 3 >::EntryToIndex(), kPropertyDetailsOffset, v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::set(), v8::internal::this, and v8::internal::FixedArray::value.
FindEntry() [1/2]
template<typename IsolateT >
InternalIndex v8::internal::OrderedNameDictionary::FindEntry (IsolateT * isolate, DirectHandle< Object > key) [inline]
Definition at line 801 of file ordered-hash-table.h.
                                                                       {
    return FindEntry(isolate, *key);
  }
References v8::internal::key.
FindEntry() [2/2]
template<typename IsolateT >
InternalIndex v8::internal::OrderedNameDictionary::FindEntry (IsolateT * isolate, Tagged< Object > key)
Definition at line 501 of file ordered-hash-table.cc.
                                                                   {
  DisallowGarbageCollection no_gc;
  DCHECK(IsUniqueName(key));
  Tagged<Name> raw_key = Cast<Name>(key);
  if (NumberOfElements() == 0) {
    // This is not just an optimization but also ensures that we do the right
    // thing if Capacity() == 0
    return InternalIndex::NotFound();
  }
  int raw_entry = HashToEntryRaw(raw_key->hash());
  while (raw_entry != kNotFound) {
    InternalIndex entry(raw_entry);
    Tagged<Object> candidate_key = KeyAt(entry);
    DCHECK(IsHashTableHole(candidate_key) ||
           IsUniqueName(Cast<Name>(candidate_key)));
    if (candidate_key == raw_key) return entry;
    // TODO(gsathya): This is loading the bucket count from the hash
    // table for every iteration. This should be peeled out of the
    // loop.
    raw_entry = NextChainEntryRaw(raw_entry);
  }
  return InternalIndex::NotFound();
}
References v8::internal::DCHECK(), v8::internal::OrderedHashTable< OrderedNameDictionary, 3 >::HashToEntryRaw(), v8::internal::IsUniqueName(), v8::internal::key, v8::internal::OrderedHashTable< OrderedNameDictionary, 3 >::KeyAt(), v8::internal::OrderedHashTable< OrderedNameDictionary, 3 >::kNotFound, v8::internal::OrderedHashTable< OrderedNameDictionary, 3 >::NextChainEntryRaw(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::InternalIndex::NotFound(), and v8::internal::OrderedHashTable< OrderedNameDictionary, 3 >::NumberOfElements().
GetEmpty()
static Tagged<HeapObject> v8::internal::OrderedNameDictionary::GetEmpty (ReadOnlyRoots ro_roots) [static]
GetMap()
Handle< Map > v8::internal::OrderedNameDictionary::GetMap (RootsTable & roots) [inline], [static]
Definition at line 68 of file ordered-hash-table-inl.h.
                                                           {
  return roots.ordered_name_dictionary_map();
}
Hash()
int v8::internal::OrderedNameDictionary::Hash () [inline]
Definition at line 216 of file ordered-hash-table-inl.h.
                                       {
  Tagged<Object> hash_obj = this->get(HashIndex());
  int hash = Smi::ToInt(hash_obj);
  DCHECK(PropertyArray::HashField::is_valid(hash));
  return hash;
}
References v8::internal::DCHECK(), v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::get(), HashIndex(), v8::base::BitField< T, shift, size, U >::is_valid(), and v8::internal::Smi::ToInt().
HashIndex()
static constexpr int v8::internal::OrderedNameDictionary::HashIndex () [inline], [static], [constexpr]
Definition at line 849 of file ordered-hash-table.h.
{ return PrefixIndex(); }
Referenced by Hash(), and SetHash().
Is()
bool v8::internal::OrderedNameDictionary::Is (DirectHandle< HeapObject > table) [inline], [static]
Definition at line 164 of file ordered-hash-table-inl.h.
                                                                    {
  return IsOrderedNameDictionary(*table);
}
References v8::internal::OrderedHashTable< OrderedNameDictionary, 3 >::table.
NameAt()
Tagged< Name > v8::internal::OrderedNameDictionary::NameAt (InternalIndex entry) [inline]
Definition at line 94 of file ordered-hash-table-inl.h.
                                                              {
  return Cast<Name>(KeyAt(entry));
}
References v8::internal::OrderedHashTable< OrderedNameDictionary, 3 >::KeyAt().
SetEntry()
void v8::internal::OrderedNameDictionary::SetEntry (InternalIndex entry, Tagged< Object > key, Tagged< Object > value, PropertyDetails details)
Definition at line 568 of file ordered-hash-table.cc.
                                                              {
  DisallowGarbageCollection gc;
  DCHECK_IMPLIES(!IsName(key), IsHashTableHole(key));
  DisallowGarbageCollection no_gc;
  int index = EntryToIndex(entry);
  this->set(index, key);
  this->set(index + kValueOffset, value);
  // TODO(gsathya): Optimize how PropertyDetails are stored in this
  // dictionary to save memory (by reusing padding?) and performance
  // (by not doing the Smi conversion).
  this->set(index + kPropertyDetailsOffset, details.AsSmi());
}
References v8::internal::PropertyDetails::AsSmi(), DCHECK_IMPLIES, v8::internal::OrderedHashTable< OrderedNameDictionary, 3 >::EntryToIndex(), v8::internal::FixedArray::index, v8::internal::key, kPropertyDetailsOffset, kValueOffset, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::set(), and v8::internal::FixedArray::value.
SetHash()
void v8::internal::OrderedNameDictionary::SetHash (int hash) [inline]
Definition at line 211 of file ordered-hash-table-inl.h.
                                                   {
  DCHECK(PropertyArray::HashField::is_valid(hash));
  this->set(HashIndex(), Smi::FromInt(hash));
}
References v8::internal::DCHECK(), v8::internal::Smi::FromInt(), HashIndex(), v8::base::BitField< T, shift, size, U >::is_valid(), and v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::set().
ValueAt()
template<template< typename > typename HandleType>
Tagged< Object > v8::internal::OrderedNameDictionary::ValueAt (InternalIndex entry) [inline]
Definition at line 89 of file ordered-hash-table-inl.h.
                                                                        {
  DCHECK_LT(entry.as_int(), UsedCapacity());
  return get(EntryToIndex(entry) + kValueOffset);
}
References v8::internal::InternalIndex::as_int(), DCHECK_LT, v8::internal::OrderedHashTable< OrderedNameDictionary, 3 >::EntryToIndex(), v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::get(), kValueOffset, and v8::internal::OrderedHashTable< OrderedNameDictionary, 3 >::UsedCapacity().
ValueAtPut()
void v8::internal::OrderedNameDictionary::ValueAtPut (InternalIndex entry, Tagged< Object > value) [inline]
Definition at line 110 of file ordered-hash-table-inl.h.
                                                                    {
  DCHECK_LT(entry.as_int(), UsedCapacity());
  this->set(EntryToIndex(entry) + kValueOffset, value);
}
References v8::internal::InternalIndex::as_int(), DCHECK_LT, v8::internal::OrderedHashTable< OrderedNameDictionary, 3 >::EntryToIndex(), kValueOffset, v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::set(), v8::internal::OrderedHashTable< OrderedNameDictionary, 3 >::UsedCapacity(), and v8::internal::FixedArray::value.
Member Data Documentation
kIsOrderedDictionaryType
const bool v8::internal::OrderedNameDictionary::kIsOrderedDictionaryType = true [static]
Definition at line 851 of file ordered-hash-table.h.
kPrefixSize
const int v8::internal::OrderedNameDictionary::kPrefixSize = 1 [static]
Definition at line 847 of file ordered-hash-table.h.
kPropertyDetailsOffset
const int v8::internal::OrderedNameDictionary::kPropertyDetailsOffset = 2 [static]
Definition at line 846 of file ordered-hash-table.h.
Referenced by Add(), DetailsAt(), DetailsAtPut(), and SetEntry().
kValueOffset
const int v8::internal::OrderedNameDictionary::kValueOffset = 1 [static]
Definition at line 845 of file ordered-hash-table.h.
Referenced by Add(), SetEntry(), ValueAt(), and ValueAtPut().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/ordered-hash-table.h
/mnt/V8SourceCode/src/objects/ordered-hash-table-inl.h
/mnt/V8SourceCode/src/objects/ordered-hash-table.cc