v8::internal::ExternalizeStringExtension Class Reference
#include <externalize-string-extension.h>
Public Member Functions
ExternalizeStringExtension ()
v8::Local< v8::FunctionTemplate > GetNativeFunctionTemplate (v8::Isolate *isolate, v8::Local< v8::String > name) override
Static Public Member Functions
static void Externalize (const v8::FunctionCallbackInfo< v8::Value > &info)
static void CreateExternalizableString (const v8::FunctionCallbackInfo< v8::Value > &info)
static void CreateExternalizableTwoByteString (const v8::FunctionCallbackInfo< v8::Value > &info)
static void IsOneByte (const v8::FunctionCallbackInfo< v8::Value > &info)
Static Private Member Functions
static const char * BuildSource (char *buf, size_t size)
Private Attributes
char buffer_ [400]
Static Private Attributes
static const char *const kSource
Detailed Description
Definition at line 17 of file externalize-string-extension.h.
Constructor & Destructor Documentation
ExternalizeStringExtension()
v8::internal::ExternalizeStringExtension::ExternalizeStringExtension () [inline]
Definition at line 19 of file externalize-string-extension.h.
      : v8::Extension("v8/externalize", BuildSource(buffer_, sizeof(buffer_))) {
  }
Member Function Documentation
BuildSource()
const char * v8::internal::ExternalizeStringExtension::BuildSource (char * buf, size_t size) [static], [private]
Definition at line 53 of file externalize-string-extension.cc.
                                                                          {
  base::SNPrintF(base::VectorOf(buf, size),
                 "native function externalizeString();"
                 "native function createExternalizableString();"
                 "native function createExternalizableTwoByteString();"
                 "native function isOneByteString();"
                 "let kExternalStringMinOneByteLength = %d;"
                 "let kExternalStringMinTwoByteLength = %d;"
                 "let kExternalStringMinOneByteCachedLength = %d;"
                 "let kExternalStringMinTwoByteCachedLength = %d;",
                 kMinOneByteLength, kMinTwoByteLength, kMinOneByteCachedLength,
                 kMinTwoByteCachedLength);
  return buf;
}
References v8::internal::kMinOneByteCachedLength, v8::internal::kMinOneByteLength, v8::internal::kMinTwoByteCachedLength, v8::internal::kMinTwoByteLength, size(), v8::base::SNPrintF(), and v8::base::VectorOf().
CreateExternalizableString()
void v8::internal::ExternalizeStringExtension::CreateExternalizableString (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 247 of file externalize-string-extension.cc.
                                                 {
  DCHECK(ValidateCallbackInfo(info));
  if (info.Length() < 1 || !info[0]->IsString()) {
    info.GetIsolate()->ThrowError(
        "First parameter to createExternalizableString() must be a string.");
    return;
  }
  v8::Isolate* isolate = info.GetIsolate();
  DirectHandle<String> string =
      Utils::OpenDirectHandle(*info[0].As<v8::String>());
  v8::String::Encoding encoding = string->IsOneByteRepresentation()
                                      ? v8::String::Encoding::ONE_BYTE_ENCODING
                                      : v8::String::Encoding::TWO_BYTE_ENCODING;
  MaybeDirectHandle<String> maybe_result =
      i::CreateExternalizableString(isolate, string, encoding);
  DirectHandle<String> result;
  if (maybe_result.ToHandle(&result)) {
    DCHECK(!isolate->HasPendingException());
    info.GetReturnValue().Set(Utils::ToLocal(result));
  } else {
    DCHECK(isolate->HasPendingException());
  }
}
References v8::internal::anonymous_namespace{externalize-string-extension.cc}::CreateExternalizableString(), v8::internal::DCHECK(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::Isolate::HasPendingException(), v8::FunctionCallbackInfo< T >::Length(), v8::Utils::OpenDirectHandle(), v8::base::internal::result, v8::Isolate::ThrowError(), v8::internal::MaybeDirectHandle< T >::ToHandle(), and v8::internal::ValidateCallbackInfo().
Referenced by GetNativeFunctionTemplate().
CreateExternalizableTwoByteString()
void v8::internal::ExternalizeStringExtension::CreateExternalizableTwoByteString (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 272 of file externalize-string-extension.cc.
                                                 {
  DCHECK(ValidateCallbackInfo(info));
  if (info.Length() < 1 || !info[0]->IsString()) {
    info.GetIsolate()->ThrowError(
        "First parameter to createExternalizableString() must be a string.");
    return;
  }
  v8::Isolate* isolate = info.GetIsolate();
  DirectHandle<String> string =
      Utils::OpenDirectHandle(*info[0].As<v8::String>());
  MaybeDirectHandle<String> maybe_result = i::CreateExternalizableString(
      isolate, string, v8::String::Encoding::TWO_BYTE_ENCODING);
  DirectHandle<String> result;
  if (maybe_result.ToHandle(&result)) {
    DCHECK(!isolate->HasPendingException());
    info.GetReturnValue().Set(Utils::ToLocal(result));
  } else {
    DCHECK(isolate->HasPendingException());
  }
}
References v8::internal::anonymous_namespace{externalize-string-extension.cc}::CreateExternalizableString(), v8::internal::DCHECK(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::Isolate::HasPendingException(), v8::FunctionCallbackInfo< T >::Length(), v8::Utils::OpenDirectHandle(), v8::base::internal::result, v8::Isolate::ThrowError(), v8::internal::MaybeDirectHandle< T >::ToHandle(), and v8::internal::ValidateCallbackInfo().
Referenced by GetNativeFunctionTemplate().
Externalize()
void v8::internal::ExternalizeStringExtension::Externalize (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 99 of file externalize-string-extension.cc.
                                                 {
  DCHECK(ValidateCallbackInfo(info));
  if (info.Length() < 1 || !info[0]->IsString()) {
    info.GetIsolate()->ThrowError(
        "First parameter to externalizeString() must be a string.");
    return;
  }
  bool result = false;
  DirectHandle<String> string =
      Utils::OpenDirectHandle(*info[0].As<v8::String>());
  const bool externalize_as_one_byte = string->IsOneByteRepresentation();
  if (!string->SupportsExternalization(
          externalize_as_one_byte ? v8::String::Encoding::ONE_BYTE_ENCODING
                                  : v8::String::Encoding::TWO_BYTE_ENCODING)) {
    // If the string is shared, testing with the combination of
    // --shared-string-table and --isolate in d8 may result in races to
    // externalize the same string. If GC is stressed in addition, this test
    // might fail as the string was already externalized (marked for
    // externalization by another thread and externalized during GC).
    if (!StringShape(*string).IsExternal()) {
      info.GetIsolate()->ThrowError("string does not support externalization.");
    }
    return;
  }
  uint32_t length = string->length();
  if (externalize_as_one_byte) {
    uint8_t* data = new uint8_t[length];
    String::WriteToFlat(*string, data, 0, length);
    SimpleOneByteStringResource* resource =
        new SimpleOneByteStringResource(reinterpret_cast<char*>(data), length);
    result = Utils::ToLocal(string)->MakeExternal(info.GetIsolate(), resource);
    if (!result) delete resource;
  } else {
    base::uc16* data = new base::uc16[length];
    String::WriteToFlat(*string, data, 0, length);
    SimpleTwoByteStringResource* resource =
        new SimpleTwoByteStringResource(data, length);
    result = Utils::ToLocal(string)->MakeExternal(info.GetIsolate(), resource);
    if (!result) delete resource;
  }
  // If the string is shared, testing with the combination of
  // --shared-string-table and --isolate in d8 may result in races to
  // externalize the same string. Those races manifest as externalization
  // sometimes failing if another thread won and already forwarded the string to
  // the external resource. Don't consider those races as failures.
  if (!result && !HasExternalForwardingIndex(string)) {
    info.GetIsolate()->ThrowError("externalizeString() failed.");
    return;
  }
}
References v8::internal::DCHECK(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::internal::anonymous_namespace{externalize-string-extension.cc}::HasExternalForwardingIndex(), v8::internal::StringShape::IsExternal(), v8::FunctionCallbackInfo< T >::Length(), v8::internal::length, v8::Utils::OpenDirectHandle(), v8::base::internal::result, v8::internal::string, v8::Isolate::ThrowError(), v8::internal::ValidateCallbackInfo(), and v8::internal::String::WriteToFlat().
Referenced by GetNativeFunctionTemplate().
GetNativeFunctionTemplate()
v8::Local< v8::FunctionTemplate > v8::internal::ExternalizeStringExtension::GetNativeFunctionTemplate (v8::Isolate * isolate, v8::Local< v8::String > name) [override], [virtual]
Reimplemented from v8::Extension.
Definition at line 68 of file externalize-string-extension.cc.
                                               {
  if (strcmp(*v8::String::Utf8Value(isolate, str), "externalizeString") == 0) {
    return v8::FunctionTemplate::New(isolate,
                                     ExternalizeStringExtension::Externalize);
  } else if (strcmp(*v8::String::Utf8Value(isolate, str),
                    "createExternalizableString") == 0) {
    return v8::FunctionTemplate::New(
        isolate, ExternalizeStringExtension::CreateExternalizableString);
  } else if (strcmp(*v8::String::Utf8Value(isolate, str),
                    "createExternalizableTwoByteString") == 0) {
    return v8::FunctionTemplate::New(
        isolate, ExternalizeStringExtension::CreateExternalizableTwoByteString);
  } else {
    DCHECK_EQ(strcmp(*v8::String::Utf8Value(isolate, str), "isOneByteString"),
              0);
    return v8::FunctionTemplate::New(isolate,
                                     ExternalizeStringExtension::IsOneByte);
  }
}
References CreateExternalizableString(), CreateExternalizableTwoByteString(), DCHECK_EQ, Externalize(), IsOneByte(), and v8::FunctionTemplate::New().
IsOneByte()
void v8::internal::ExternalizeStringExtension::IsOneByte (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 294 of file externalize-string-extension.cc.
                                                 {
  DCHECK(ValidateCallbackInfo(info));
  if (info.Length() != 1 || !info[0]->IsString()) {
    info.GetIsolate()->ThrowError(
        "isOneByteString() requires a single string argument.");
    return;
  }
  bool is_one_byte = Utils::OpenDirectHandle(*info[0].As<v8::String>())
                         ->IsOneByteRepresentation();
  info.GetReturnValue().Set(is_one_byte);
}
References v8::internal::DCHECK(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::FunctionCallbackInfo< T >::Length(), v8::Utils::OpenDirectHandle(), v8::Isolate::ThrowError(), and v8::internal::ValidateCallbackInfo().
Referenced by GetNativeFunctionTemplate().
Member Data Documentation
buffer_
char v8::internal::ExternalizeStringExtension::buffer_[400] [private]
Definition at line 33 of file externalize-string-extension.h.
kSource
const char* const v8::internal::ExternalizeStringExtension::kSource [static], [private]
Definition at line 34 of file externalize-string-extension.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/extensions/externalize-string-extension.h
/mnt/V8SourceCode/src/extensions/externalize-string-extension.cc