v8::internal::maglev::BuiltinStringPrototypeCharCodeOrCodePointAt Class Reference
#include <maglev-ir.h>
Public Types
enum Mode { kCharCodeAt
, kCodePointAt
 }
Public Member Functions
BuiltinStringPrototypeCharCodeOrCodePointAt (uint64_t bitfield, Mode mode)
Input & string_input ()
Input & index_input ()
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
auto options () const
Mode mode () const
Static Public Attributes
static constexpr OpProperties kProperties
static constexpr Base::InputTypes kInputTypes
static constexpr int kStringIndex = 0
static constexpr int kIndexIndex = 1
Private Types
using Base = FixedInputValueNodeT< 2, BuiltinStringPrototypeCharCodeOrCodePointAt >
using ModeField = NextBitField< Mode, 1 >
Additional Inherited Members
Detailed Description
Definition at line 7728 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::BuiltinStringPrototypeCharCodeOrCodePointAt::Base = FixedInputValueNodeT<2, BuiltinStringPrototypeCharCodeOrCodePointAt> [private]
Definition at line 7731 of file maglev-ir.h.
ModeField
using v8::internal::maglev::BuiltinStringPrototypeCharCodeOrCodePointAt::ModeField = NextBitField<Mode, 1> [private]
Definition at line 7765 of file maglev-ir.h.
Member Enumeration Documentation
Mode
enum v8::internal::maglev::BuiltinStringPrototypeCharCodeOrCodePointAt::Mode
Enumerator
kCharCodeAt
kCodePointAt
Definition at line 7735 of file maglev-ir.h.
            {
    kCharCodeAt,
    kCodePointAt,
  };
Constructor & Destructor Documentation
BuiltinStringPrototypeCharCodeOrCodePointAt()
v8::internal::maglev::BuiltinStringPrototypeCharCodeOrCodePointAt::BuiltinStringPrototypeCharCodeOrCodePointAt (uint64_t bitfield, Mode mode) [inline], [explicit]
Definition at line 7740 of file maglev-ir.h.
      : Base(bitfield | ModeField::encode(mode)) {}
Member Function Documentation
GenerateCode()
void v8::internal::maglev::BuiltinStringPrototypeCharCodeOrCodePointAt::GenerateCode (MaglevAssembler * , const ProcessingState &)
index_input()
Input& v8::internal::maglev::BuiltinStringPrototypeCharCodeOrCodePointAt::index_input () [inline]
Definition at line 7753 of file maglev-ir.h.
{ return input(kIndexIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
MaxCallStackArgs()
int v8::internal::maglev::BuiltinStringPrototypeCharCodeOrCodePointAt::MaxCallStackArgs () const
mode()
Mode v8::internal::maglev::BuiltinStringPrototypeCharCodeOrCodePointAt::mode () const [inline]
Definition at line 7762 of file maglev-ir.h.
{ return ModeField::decode(bitfield()); }
Referenced by PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
options()
auto v8::internal::maglev::BuiltinStringPrototypeCharCodeOrCodePointAt::options () const [inline]
Definition at line 7760 of file maglev-ir.h.
{ return std::tuple{mode()}; }
References mode().
PrintParams()
void v8::internal::maglev::BuiltinStringPrototypeCharCodeOrCodePointAt::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8017 of file maglev-ir.cc.
                                                               {
  switch (mode()) {
    case BuiltinStringPrototypeCharCodeOrCodePointAt::kCharCodeAt:
      os << "(CharCodeAt)";
      break;
    case BuiltinStringPrototypeCharCodeOrCodePointAt::kCodePointAt:
      os << "(CodePointAt)";
      break;
  }
}
References kCharCodeAt, kCodePointAt, and mode().
SetValueLocationConstraints()
void v8::internal::maglev::BuiltinStringPrototypeCharCodeOrCodePointAt::SetValueLocationConstraints ()
string_input()
Input& v8::internal::maglev::BuiltinStringPrototypeCharCodeOrCodePointAt::string_input () [inline]
Definition at line 7752 of file maglev-ir.h.
{ return input(kStringIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
Member Data Documentation
kIndexIndex
constexpr int v8::internal::maglev::BuiltinStringPrototypeCharCodeOrCodePointAt::kIndexIndex = 1 [static], [constexpr]
Definition at line 7751 of file maglev-ir.h.
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::BuiltinStringPrototypeCharCodeOrCodePointAt::kInputTypes [static], [constexpr]
Initial value:
{
      ValueRepresentation::kTagged, ValueRepresentation::kInt32}
Definition at line 7747 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::BuiltinStringPrototypeCharCodeOrCodePointAt::kProperties [static], [constexpr]
Initial value:
=
      OpProperties::CanAllocate() | OpProperties::CanRead() |
      OpProperties::DeferredCall() | OpProperties::Int32()
Definition at line 7744 of file maglev-ir.h.
kStringIndex
constexpr int v8::internal::maglev::BuiltinStringPrototypeCharCodeOrCodePointAt::kStringIndex = 0 [static], [constexpr]
Definition at line 7750 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc