v8::internal::ExitPoint Class Reference
#include <accessor-assembler.h>
Public Types
using IndirectReturnHandler = std::function< void(TNode< Object > result)>
Public Member Functions
ExitPoint (CodeStubAssembler *assembler)
ExitPoint (CodeStubAssembler *assembler, const IndirectReturnHandler &indirect_return_handler)
ExitPoint (CodeStubAssembler *assembler, CodeAssemblerLabel *out, compiler::CodeAssembler::TVariable< Object > *var_result)
template<class... TArgs>
void ReturnCallRuntime (Runtime::FunctionId function, TNode< Context > context, TArgs... args)
template<class... TArgs>
void ReturnCallBuiltin (Builtin builtin, TNode< Context > context, TArgs... args)
template<class... TArgs>
void ReturnCallStub (const CallInterfaceDescriptor &descriptor, TNode< Code > target, TNode< Context > context, TArgs... args)
void Return (const TNode< Object > result)
bool IsDirect () const
Private Types
using CodeAssemblerLabel = compiler::CodeAssemblerLabel
Private Attributes
CodeStubAssembler *const asm_
IndirectReturnHandler indirect_return_handler_
Detailed Description
Definition at line 606 of file accessor-assembler.h.
Member Typedef Documentation
CodeAssemblerLabel
using v8::internal::ExitPoint::CodeAssemblerLabel = compiler::CodeAssemblerLabel [private]
Definition at line 608 of file accessor-assembler.h.
IndirectReturnHandler
using v8::internal::ExitPoint::IndirectReturnHandler = std::function<void(TNode<Object> result)>
Definition at line 611 of file accessor-assembler.h.
Constructor & Destructor Documentation
ExitPoint() [1/3]
v8::internal::ExitPoint::ExitPoint (CodeStubAssembler * assembler) [inline], [explicit]
Definition at line 613 of file accessor-assembler.h.
      : ExitPoint(assembler, nullptr) {}
ExitPoint() [2/3]
v8::internal::ExitPoint::ExitPoint (CodeStubAssembler * assembler, const IndirectReturnHandler & indirect_return_handler) [inline]
Definition at line 616 of file accessor-assembler.h.
      : asm_(assembler), indirect_return_handler_(indirect_return_handler) {}
ExitPoint() [3/3]
v8::internal::ExitPoint::ExitPoint (CodeStubAssembler * assembler, CodeAssemblerLabel * out, compiler::CodeAssembler::TVariable< Object > * var_result) [inline]
Definition at line 620 of file accessor-assembler.h.
      : ExitPoint(assembler, [=](TNode<Object> result) {
          *var_result = result;
          assembler->Goto(out);
        }) {
    DCHECK_EQ(out != nullptr, var_result != nullptr);
  }
References v8::internal::compiler::CodeAssembler::Goto(), and v8::base::internal::result.
Member Function Documentation
IsDirect()
bool v8::internal::ExitPoint::IsDirect () const [inline]
Definition at line 669 of file accessor-assembler.h.
{ return !indirect_return_handler_; }
References indirect_return_handler_.
Referenced by Return(), ReturnCallBuiltin(), ReturnCallRuntime(), and ReturnCallStub().
Return()
void v8::internal::ExitPoint::Return (const TNode< Object > result) [inline]
Definition at line 661 of file accessor-assembler.h.
                                          {
    if (IsDirect()) {
      asm_->Return(result);
    } else {
      indirect_return_handler_(result);
    }
  }
References asm_, indirect_return_handler_, IsDirect(), v8::base::internal::result, and v8::internal::compiler::CodeAssembler::Return().
Referenced by v8::internal::AccessorAssembler::EmitElementLoad(), v8::internal::KeyedStoreGenericAssembler::EmitGenericPropertyStore(), v8::internal::AccessorAssembler::HandleLoadAccessor(), v8::internal::AccessorAssembler::HandleLoadField(), v8::internal::AccessorAssembler::HandleLoadICHandlerCase(), v8::internal::AccessorAssembler::HandleLoadICProtoHandler(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerCase(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerHasNamedCase(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerLoadNamedCase(), v8::internal::AccessorAssembler::LoadGlobalIC_TryPropertyCellCase(), v8::internal::AccessorAssembler::StoreGlobalIC_PropertyCellCase(), v8::internal::AccessorAssembler::TryEnumeratedKeyedLoad(), and v8::internal::AccessorAssembler::TryMegaDOMCase().
ReturnCallBuiltin()
template<class... TArgs>
void v8::internal::ExitPoint::ReturnCallBuiltin (Builtin builtin, TNode< Context > context, TArgs... args) [inline]
Definition at line 640 of file accessor-assembler.h.
                                        {
    if (IsDirect()) {
      asm_->TailCallBuiltin(builtin, context, args...);
    } else {
      indirect_return_handler_(asm_->CallBuiltin(builtin, context, args...));
    }
  }
References v8::base::args, asm_, v8::internal::compiler::CodeAssembler::CallBuiltin(), indirect_return_handler_, IsDirect(), and v8::internal::compiler::CodeAssembler::TailCallBuiltin().
Referenced by v8::internal::AccessorAssembler::GenericPropertyLoad(), v8::internal::AccessorAssembler::HandleLoadCallbackProperty(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerHasNamedCase(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerLoadNamedCase(), v8::internal::AccessorAssembler::LoadGlobalIC(), v8::internal::AccessorAssembler::LoadIC(), and v8::internal::AccessorAssembler::LoadIC_BytecodeHandler().
ReturnCallRuntime()
template<class... TArgs>
void v8::internal::ExitPoint::ReturnCallRuntime (Runtime::FunctionId function, TNode< Context > context, TArgs... args) [inline]
Definition at line 630 of file accessor-assembler.h.
                                        {
    if (IsDirect()) {
      asm_->TailCallRuntime(function, context, args...);
    } else {
      indirect_return_handler_(asm_->CallRuntime(function, context, args...));
    }
  }
References v8::base::args, asm_, v8::internal::compiler::CodeAssembler::CallRuntime(), indirect_return_handler_, IsDirect(), and v8::internal::compiler::CodeAssembler::TailCallRuntime().
Referenced by v8::internal::KeyedStoreGenericAssembler::EmitGenericPropertyStore(), v8::internal::AccessorAssembler::GenerateLoadIC_Megamorphic(), v8::internal::AccessorAssembler::GenerateLoadIC_Noninlined(), v8::internal::AccessorAssembler::GenerateStoreIC_Megamorphic(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerHasNamedCase(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerLoadNamedCase(), v8::internal::AccessorAssembler::LoadGlobalIC(), v8::internal::AccessorAssembler::LoadIC(), v8::internal::AccessorAssembler::LoadIC_BytecodeHandler(), and v8::internal::AccessorAssembler::LoadSuperIC().
ReturnCallStub()
template<class... TArgs>
void v8::internal::ExitPoint::ReturnCallStub (const CallInterfaceDescriptor & descriptor, TNode< Code > target, TNode< Context > context, TArgs... args) [inline]
Definition at line 650 of file accessor-assembler.h.
                                     {
    if (IsDirect()) {
      asm_->TailCallStub(descriptor, target, context, args...);
    } else {
      indirect_return_handler_(
          asm_->CallStub(descriptor, target, context, args...));
    }
  }
References v8::base::args, asm_, v8::internal::compiler::CodeAssembler::CallStub(), indirect_return_handler_, IsDirect(), and v8::internal::compiler::CodeAssembler::TailCallStub().
Referenced by v8::internal::AccessorAssembler::HandleLoadICHandlerCase().
Member Data Documentation
asm_
CodeStubAssembler* const v8::internal::ExitPoint::asm_ [private]
Definition at line 672 of file accessor-assembler.h.
Referenced by Return(), ReturnCallBuiltin(), ReturnCallRuntime(), and ReturnCallStub().
indirect_return_handler_
IndirectReturnHandler v8::internal::ExitPoint::indirect_return_handler_ [private]
Definition at line 673 of file accessor-assembler.h.
Referenced by IsDirect(), Return(), ReturnCallBuiltin(), ReturnCallRuntime(), and ReturnCallStub().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ic/accessor-assembler.h