v8::internal::BufferedCharacterStream< ByteStream > Class Template Reference
Public Member Functions
template<class... TArgs>
BufferedCharacterStream (size_t pos, TArgs... args)
bool can_be_cloned () const final
std::unique_ptr< Utf16CharacterStream > Clone () const override
Protected Member Functions
bool ReadBlock (size_t position) final
bool can_access_heap () const final
Private Member Functions
BufferedCharacterStream (const BufferedCharacterStream< ByteStream > &other)
Private Attributes
base::uc16 buffer_ [kBufferSize]
ByteStream< uint8_t > byte_stream_
Static Private Attributes
static const size_t kBufferSize = 512
Additional Inherited Members
Detailed Description
template<template< typename T > class ByteStream>
class v8::internal::BufferedCharacterStream< ByteStream >
Definition at line 236 of file scanner-character-streams.cc.
Constructor & Destructor Documentation
BufferedCharacterStream() [1/2]
template<template< typename T > class ByteStream>
template<class... TArgs>
v8::internal::BufferedCharacterStream< ByteStream >::BufferedCharacterStream (size_t pos, TArgs... args) [inline]
Definition at line 239 of file scanner-character-streams.cc.
                                                     : byte_stream_(args...) {
    buffer_pos_ = pos;
  }
References v8::internal::Utf16CharacterStream::buffer_pos_, and v8::internal::Utf16CharacterStream::pos().
BufferedCharacterStream() [2/2]
template<template< typename T > class ByteStream>
v8::internal::BufferedCharacterStream< ByteStream >::BufferedCharacterStream (const BufferedCharacterStream< ByteStream > & other) [inline], [private]
Definition at line 278 of file scanner-character-streams.cc.
      : byte_stream_(other.byte_stream_) {}
Member Function Documentation
can_access_heap()
template<template< typename T > class ByteStream>
bool v8::internal::BufferedCharacterStream< ByteStream >::can_access_heap () const [inline], [final], [protected], [virtual]
Implements v8::internal::Utf16CharacterStream.
Definition at line 273 of file scanner-character-streams.cc.
                                     {
    return ByteStream<uint8_t>::kCanAccessHeap;
  }
can_be_cloned()
template<template< typename T > class ByteStream>
bool v8::internal::BufferedCharacterStream< ByteStream >::can_be_cloned () const [inline], [final], [virtual]
Implements v8::internal::Utf16CharacterStream.
Definition at line 243 of file scanner-character-streams.cc.
                                   {
    return ByteStream<uint16_t>::kCanBeCloned;
  }
Referenced by v8::internal::BufferedCharacterStream< ByteStream >::Clone().
Clone()
template<template< typename T > class ByteStream>
std::unique_ptr<Utf16CharacterStream> v8::internal::BufferedCharacterStream< ByteStream >::Clone () const [inline], [override], [virtual]
Implements v8::internal::Utf16CharacterStream.
Definition at line 247 of file scanner-character-streams.cc.
                                                             {
    CHECK(can_be_cloned());
    return std::unique_ptr<Utf16CharacterStream>(
        new BufferedCharacterStream<ByteStream>(*this));
  }
References v8::internal::BufferedCharacterStream< ByteStream >::can_be_cloned(), and CHECK.
ReadBlock()
template<template< typename T > class ByteStream>
bool v8::internal::BufferedCharacterStream< ByteStream >::ReadBlock (size_t position) [inline], [final], [protected], [virtual]
Implements v8::internal::Utf16CharacterStream.
Definition at line 254 of file scanner-character-streams.cc.
                                        {
    buffer_pos_ = position;
    buffer_start_ = &buffer_[0];
    buffer_cursor_ = buffer_start_;
    DisallowGarbageCollection no_gc;
    Range<uint8_t> range =
        byte_stream_.GetDataAt(position, runtime_call_stats(), &no_gc);
    if (range.length() == 0) {
      buffer_end_ = buffer_start_;
      return false;
    }
    size_t length = std::min({kBufferSize, range.length()});
    i::CopyChars(buffer_, range.start, length);
    buffer_end_ = &buffer_[length];
    return true;
  }
References v8::internal::BufferedCharacterStream< ByteStream >::buffer_, v8::internal::Utf16CharacterStream::buffer_cursor_, v8::internal::Utf16CharacterStream::buffer_end_, v8::internal::Utf16CharacterStream::buffer_pos_, v8::internal::Utf16CharacterStream::buffer_start_, v8::internal::BufferedCharacterStream< ByteStream >::byte_stream_, v8::internal::CopyChars(), v8::internal::BufferedCharacterStream< ByteStream >::kBufferSize, v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::Utf16CharacterStream::runtime_call_stats().
Member Data Documentation
buffer_
template<template< typename T > class ByteStream>
base::uc16 v8::internal::BufferedCharacterStream< ByteStream >::buffer_[kBufferSize] [private]
Definition at line 282 of file scanner-character-streams.cc.
Referenced by v8::internal::BufferedCharacterStream< ByteStream >::ReadBlock().
byte_stream_
template<template< typename T > class ByteStream>
ByteStream<uint8_t> v8::internal::BufferedCharacterStream< ByteStream >::byte_stream_ [private]
Definition at line 283 of file scanner-character-streams.cc.
Referenced by v8::internal::BufferedCharacterStream< ByteStream >::ReadBlock().
kBufferSize
template<template< typename T > class ByteStream>
const size_t v8::internal::BufferedCharacterStream< ByteStream >::kBufferSize = 512 [static], [private]
Definition at line 281 of file scanner-character-streams.cc.
Referenced by v8::internal::BufferedCharacterStream< ByteStream >::ReadBlock().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/parsing/scanner-character-streams.cc