v8::internal::compiler::turboshaft::InstructionSelectionNormalizationReducer< Next > Class Template Reference
#include <instruction-selection-normalization-reducer.h>
Public Member Functions
V< Word > REDUCE() WordBinop (V< Word > left, V< Word > right, WordBinopOp::Kind kind, WordRepresentation rep)
V< Word32 > REDUCE() Comparison (V< Any > left, V< Any > right, ComparisonOp::Kind kind, RegisterRepresentation rep)
Private Member Functions
bool IsSimpleConstant (V< Any > index)
bool IsComplexConstant (V< Any > index)
Detailed Description
template<typename Next>
class v8::internal::compiler::turboshaft::InstructionSelectionNormalizationReducer< Next >
Definition at line 30 of file instruction-selection-normalization-reducer.h.
Member Function Documentation
Comparison()
template<typename Next >
V<Word32> REDUCE() v8::internal::compiler::turboshaft::InstructionSelectionNormalizationReducer< Next >::Comparison (V< Any > left, V< Any > right, ComparisonOp::Kind kind, RegisterRepresentation rep) [inline]
Definition at line 57 of file instruction-selection-normalization-reducer.h.
                                                           {
    if (ComparisonOp::IsCommutative(kind)) {
      if (!IsSimpleConstant(right) && IsSimpleConstant(left)) {
        std::swap(left, right);
      } else if (!IsComplexConstant(right) && IsComplexConstant(left)) {
        std::swap(left, right);
      }
    }
    return Next::ReduceComparison(left, right, kind, rep);
  }
References v8::internal::compiler::turboshaft::ComparisonOp::IsCommutative(), v8::internal::compiler::turboshaft::InstructionSelectionNormalizationReducer< Next >::IsComplexConstant(), and v8::internal::compiler::turboshaft::InstructionSelectionNormalizationReducer< Next >::IsSimpleConstant().
IsComplexConstant()
template<typename Next >
bool v8::internal::compiler::turboshaft::InstructionSelectionNormalizationReducer< Next >::IsComplexConstant (V< Any > index) [inline], [private]
Definition at line 79 of file instruction-selection-normalization-reducer.h.
                                       {
    const Operation& op = __ Get(index);
    switch (op.opcode) {
      case Opcode::kConstant:
        return true;
      case Opcode::kChange:
        return IsComplexConstant(op.Cast<ChangeOp>().input());
      case Opcode::kTaggedBitcast:
        return IsComplexConstant(op.Cast<TaggedBitcastOp>().input());
      case Opcode::kTryChange:
        return IsComplexConstant(op.Cast<ChangeOp>().input());
      default:
        return false;
    }
  }
References __, v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::compiler::turboshaft::Get(), v8::internal::index, v8::internal::compiler::turboshaft::ChangeOp::input(), v8::internal::compiler::turboshaft::TaggedBitcastOp::input(), v8::internal::compiler::anonymous_namespace{gap-resolver.cc}::kConstant, and v8::internal::compiler::turboshaft::Operation::opcode.
Referenced by v8::internal::compiler::turboshaft::InstructionSelectionNormalizationReducer< Next >::Comparison(), and v8::internal::compiler::turboshaft::InstructionSelectionNormalizationReducer< Next >::WordBinop().
IsSimpleConstant()
template<typename Next >
bool v8::internal::compiler::turboshaft::InstructionSelectionNormalizationReducer< Next >::IsSimpleConstant (V< Any > index) [inline], [private]
Definition at line 72 of file instruction-selection-normalization-reducer.h.
                                      {
    return __ Get(index).template Is<ConstantOp>();
  }
References __, v8::internal::compiler::turboshaft::Get(), and v8::internal::index.
Referenced by v8::internal::compiler::turboshaft::InstructionSelectionNormalizationReducer< Next >::Comparison(), and v8::internal::compiler::turboshaft::InstructionSelectionNormalizationReducer< Next >::WordBinop().
WordBinop()
template<typename Next >
V<Word> REDUCE() v8::internal::compiler::turboshaft::InstructionSelectionNormalizationReducer< Next >::WordBinop (V< Word > left, V< Word > right, WordBinopOp::Kind kind, WordRepresentation rep) [inline]
Definition at line 34 of file instruction-selection-normalization-reducer.h.
                                                    {
    // Putting constant on the right side.
    if (WordBinopOp::IsCommutative(kind)) {
      if (!IsSimpleConstant(right) && IsSimpleConstant(left)) {
        std::swap(left, right);
      } else if (!IsComplexConstant(right) && IsComplexConstant(left)) {
        std::swap(left, right);
      }
    }
    // Transforming multiplications by power of two constants into shifts
    if (kind == WordBinopOp::Kind::kMul) {
      int64_t cst;
      if (__ matcher().MatchPowerOfTwoWordConstant(right, &cst, rep) &&
          cst < rep.bit_width()) {
        return __ ShiftLeft(left, base::bits::WhichPowerOfTwo(cst), rep);
      }
    }
    return Next::ReduceWordBinop(left, right, kind, rep);
  }
References __, v8::internal::compiler::turboshaft::WordBinopOp::IsCommutative(), v8::internal::compiler::turboshaft::InstructionSelectionNormalizationReducer< Next >::IsComplexConstant(), v8::internal::compiler::turboshaft::InstructionSelectionNormalizationReducer< Next >::IsSimpleConstant(), v8::internal::compiler::turboshaft::WordBinopOp::kMul, and v8::base::bits::WhichPowerOfTwo().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/instruction-selection-normalization-reducer.h