cppgc::internal::HeapGrowing::HeapGrowingImpl Class Reference
Public Member Functions
HeapGrowingImpl (GarbageCollector *, StatsCollector *, cppgc::Heap::ResourceConstraints, cppgc::Heap::MarkingType, cppgc::Heap::SweepingType)
~HeapGrowingImpl ()
HeapGrowingImpl (const HeapGrowingImpl &)=delete
HeapGrowingImpl & operator= (const HeapGrowingImpl &)=delete
void AllocatedObjectSizeIncreased (size_t) final
void AllocatedObjectSizeDecreased (size_t) final
void ResetAllocatedObjectSize (size_t) final
size_t limit_for_atomic_gc () const
size_t limit_for_incremental_gc () const
void DisableForTesting ()
Private Member Functions
void ConfigureLimit (size_t allocated_object_size)
Private Attributes
GarbageCollector * collector_
StatsCollector * stats_collector_
size_t initial_heap_size_ = 1 * kMB
size_t limit_for_atomic_gc_ = 0
size_t limit_for_incremental_gc_ = 0
SingleThreadedHandle gc_task_handle_
bool disabled_for_testing_ = false
const cppgc::Heap::MarkingType marking_support_
const cppgc::Heap::SweepingType sweeping_support_
Detailed Description
Definition at line 30 of file heap-growing.cc.
Constructor & Destructor Documentation
HeapGrowingImpl() [1/2]
cppgc::internal::HeapGrowing::HeapGrowingImpl::HeapGrowingImpl (GarbageCollector * collector, StatsCollector * stats_collector, cppgc::Heap::ResourceConstraints constraints, cppgc::Heap::MarkingType marking_support, cppgc::Heap::SweepingType sweeping_support)
Definition at line 69 of file heap-growing.cc.
    : collector_(collector),
      stats_collector_(stats_collector),
      gc_task_handle_(SingleThreadedHandle::NonEmptyTag{}),
      marking_support_(marking_support),
      sweeping_support_(sweeping_support) {
  if (constraints.initial_heap_size_bytes > 0) {
    initial_heap_size_ = constraints.initial_heap_size_bytes;
  }
  constexpr size_t kNoAllocatedBytes = 0;
  ConfigureLimit(kNoAllocatedBytes);
  stats_collector->RegisterObserver(this);
}
References ConfigureLimit(), initial_heap_size_, cppgc::Heap::ResourceConstraints::initial_heap_size_bytes, and cppgc::internal::StatsCollector::RegisterObserver().
 HeapGrowingImpl()
cppgc::internal::HeapGrowing::HeapGrowingImpl::~HeapGrowingImpl ()
Definition at line 87 of file heap-growing.cc.
                                             {
  stats_collector_->UnregisterObserver(this);
}
HeapGrowingImpl() [2/2]
cppgc::internal::HeapGrowing::HeapGrowingImpl::HeapGrowingImpl (const HeapGrowingImpl &) [delete]
Member Function Documentation
AllocatedObjectSizeDecreased()
void cppgc::internal::HeapGrowing::HeapGrowingImpl::AllocatedObjectSizeDecreased (size_t) [inline], [final], [virtual]
Reimplemented from cppgc::internal::StatsCollector::AllocationObserver.
Definition at line 43 of file heap-growing.cc.
{}
AllocatedObjectSizeIncreased()
void cppgc::internal::HeapGrowing::HeapGrowingImpl::AllocatedObjectSizeIncreased (size_t) [final], [virtual]
Reimplemented from cppgc::internal::StatsCollector::AllocationObserver.
Definition at line 91 of file heap-growing.cc.
                                                                    {
  if (disabled_for_testing_) return;
  size_t allocated_object_size = stats_collector_->allocated_object_size();
  if (allocated_object_size > limit_for_atomic_gc_) {
    collector_->CollectGarbage(
        {CollectionType::kMajor, StackState::kMayContainHeapPointers,
         GCConfig::MarkingType::kAtomic, sweeping_support_});
  } else if (allocated_object_size > limit_for_incremental_gc_) {
    if (marking_support_ == cppgc::Heap::MarkingType::kAtomic) return;
    collector_->StartIncrementalGarbageCollection(
        {CollectionType::kMajor, StackState::kMayContainHeapPointers,
         marking_support_, sweeping_support_});
  }
}
References cppgc::Heap::kAtomic, and cppgc::internal::kMajor.
ConfigureLimit()
void cppgc::internal::HeapGrowing::HeapGrowingImpl::ConfigureLimit (size_t allocated_object_size) [private]
Definition at line 111 of file heap-growing.cc.
                                  {
  const size_t size = std::max(allocated_object_size, initial_heap_size_);
  limit_for_atomic_gc_ = std::max(static_cast<size_t>(size * kGrowingFactor),
                                  size + kMinLimitIncrease);
  // Estimate when to start incremental GC based on current allocation speed.
  // Ideally we start incremental GC such that it is ready to finalize no
  // later than when we reach |limit_for_atomic_gc_|. However, we need to cap
  // |limit_for_incremental_gc_| within a range to prevent:
  // 1) |limit_for_incremental_gc_| being too close to |limit_for_atomic_gc_|
  // such that incremental gc gets nothing done before reaching
  // |limit_for_atomic_gc_| (in case where the allocation rate is very low).
  // 2) |limit_for_incremental_gc_| being too close to |size| such that GC is
  // essentially always running and write barriers are always active (in
  // case allocation rate is very high).
  size_t estimated_bytes_allocated_during_incremental_gc =
      std::ceil(heap::base::IncrementalMarkingSchedule::kEstimatedMarkingTime
                    .InMillisecondsF() *
                stats_collector_->GetRecentAllocationSpeedInBytesPerMs());
  size_t limit_incremental_gc_based_on_allocation_rate =
      limit_for_atomic_gc_ - estimated_bytes_allocated_during_incremental_gc;
  size_t maximum_limit_incremental_gc =
      size + (limit_for_atomic_gc_ - size) * kMaximumLimitRatioForIncrementalGC;
  size_t minimum_limit_incremental_gc =
      size + (limit_for_atomic_gc_ - size) * kMinimumLimitRatioForIncrementalGC;
  limit_for_incremental_gc_ =
      std::max(minimum_limit_incremental_gc,
               std::min(maximum_limit_incremental_gc,
                        limit_incremental_gc_based_on_allocation_rate));
}
References heap::base::IncrementalMarkingSchedule::kEstimatedMarkingTime, cppgc::internal::HeapGrowing::kGrowingFactor, cppgc::internal::anonymous_namespace{heap-growing.cc}::kMaximumLimitRatioForIncrementalGC, cppgc::internal::anonymous_namespace{heap-growing.cc}::kMinimumLimitRatioForIncrementalGC, cppgc::internal::HeapGrowing::kMinLimitIncrease, and size().
Referenced by HeapGrowingImpl().
DisableForTesting()
void cppgc::internal::HeapGrowing::HeapGrowingImpl::DisableForTesting ()
Definition at line 142 of file heap-growing.cc.
                                                   {
  disabled_for_testing_ = true;
}
limit_for_atomic_gc()
size_t cppgc::internal::HeapGrowing::HeapGrowingImpl::limit_for_atomic_gc () const [inline]
Definition at line 46 of file heap-growing.cc.
{ return limit_for_atomic_gc_; }
References limit_for_atomic_gc_.
limit_for_incremental_gc()
size_t cppgc::internal::HeapGrowing::HeapGrowingImpl::limit_for_incremental_gc () const [inline]
Definition at line 47 of file heap-growing.cc.
{ return limit_for_incremental_gc_; }
References limit_for_incremental_gc_.
operator=()
HeapGrowingImpl& cppgc::internal::HeapGrowing::HeapGrowingImpl::operator= (const HeapGrowingImpl &) [delete]
ResetAllocatedObjectSize()
void cppgc::internal::HeapGrowing::HeapGrowingImpl::ResetAllocatedObjectSize (size_t allocated_object_size) [final], [virtual]
Reimplemented from cppgc::internal::StatsCollector::AllocationObserver.
Definition at line 106 of file heap-growing.cc.
                                  {
  ConfigureLimit(allocated_object_size);
}
Member Data Documentation
collector_
GarbageCollector* cppgc::internal::HeapGrowing::HeapGrowingImpl::collector_ [private]
Definition at line 54 of file heap-growing.cc.
disabled_for_testing_
bool cppgc::internal::HeapGrowing::HeapGrowingImpl::disabled_for_testing_ = false [private]
Definition at line 63 of file heap-growing.cc.
gc_task_handle_
SingleThreadedHandle cppgc::internal::HeapGrowing::HeapGrowingImpl::gc_task_handle_ [private]
Definition at line 61 of file heap-growing.cc.
initial_heap_size_
size_t cppgc::internal::HeapGrowing::HeapGrowingImpl::initial_heap_size_ = 1 * kMB [private]
Definition at line 57 of file heap-growing.cc.
Referenced by HeapGrowingImpl().
limit_for_atomic_gc_
size_t cppgc::internal::HeapGrowing::HeapGrowingImpl::limit_for_atomic_gc_ = 0 [private]
Definition at line 58 of file heap-growing.cc.
Referenced by limit_for_atomic_gc().
limit_for_incremental_gc_
size_t cppgc::internal::HeapGrowing::HeapGrowingImpl::limit_for_incremental_gc_ = 0 [private]
Definition at line 59 of file heap-growing.cc.
Referenced by limit_for_incremental_gc().
marking_support_
const cppgc::Heap::MarkingType cppgc::internal::HeapGrowing::HeapGrowingImpl::marking_support_ [private]
Definition at line 65 of file heap-growing.cc.
stats_collector_
StatsCollector* cppgc::internal::HeapGrowing::HeapGrowingImpl::stats_collector_ [private]
Definition at line 55 of file heap-growing.cc.
sweeping_support_
const cppgc::Heap::SweepingType cppgc::internal::HeapGrowing::HeapGrowingImpl::sweeping_support_ [private]
Definition at line 66 of file heap-growing.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc/heap-growing.cc