v8::internal::maglev::CheckMapsWithMigration Class Reference
#include <maglev-ir.h>
Public Member Functions
CheckMapsWithMigration (uint64_t bitfield, const compiler::ZoneRefSet< Map > &maps, CheckType check_type)
const compiler::ZoneRefSet< Map > & maps () const
Input & receiver_input ()
CheckType check_type () const
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
void ClearUnstableNodeAspects (KnownNodeAspects &known_node_aspects)
Static Public Attributes
static constexpr OpProperties kProperties
static constexpr Base::InputTypes kInputTypes {ValueRepresentation::kTagged}
static constexpr int kReceiverIndex = 0
Private Types
using Base = FixedInputNodeT< 1, CheckMapsWithMigration >
using CheckTypeBitField = NextBitField< CheckType, 1 >
Private Attributes
const compiler::ZoneRefSet< Map > maps_
Additional Inherited Members
Detailed Description
Definition at line 7323 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::CheckMapsWithMigration::Base = FixedInputNodeT<1, CheckMapsWithMigration> [private]
Definition at line 7325 of file maglev-ir.h.
CheckTypeBitField
using v8::internal::maglev::CheckMapsWithMigration::CheckTypeBitField = NextBitField<CheckType, 1> [private]
Definition at line 7354 of file maglev-ir.h.
Constructor & Destructor Documentation
CheckMapsWithMigration()
v8::internal::maglev::CheckMapsWithMigration::CheckMapsWithMigration (uint64_t bitfield, const compiler::ZoneRefSet< Map > & maps, CheckType check_type) [inline], [explicit]
Definition at line 7328 of file maglev-ir.h.
      : Base(CheckTypeBitField::update(bitfield, check_type)), maps_(maps) {}
Member Function Documentation
check_type()
CheckType v8::internal::maglev::CheckMapsWithMigration::check_type () const [inline]
Definition at line 7344 of file maglev-ir.h.
{ return CheckTypeBitField::decode(bitfield()); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
ClearUnstableNodeAspects()
void v8::internal::maglev::CheckMapsWithMigration::ClearUnstableNodeAspects (KnownNodeAspects & known_node_aspects)
Definition at line 8531 of file maglev-ir.cc.
                                          {
  // This instruction only migrates representations of values, not the values
  // themselves, so cached values are still valid.
}
GenerateCode()
void v8::internal::maglev::CheckMapsWithMigration::GenerateCode (MaglevAssembler * , const ProcessingState &)
maps()
const compiler::ZoneRefSet<Map>& v8::internal::maglev::CheckMapsWithMigration::maps () const [inline]
Definition at line 7340 of file maglev-ir.h.
{ return maps_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
MaxCallStackArgs()
int v8::internal::maglev::CheckMapsWithMigration::MaxCallStackArgs () const
PrintParams()
void v8::internal::maglev::CheckMapsWithMigration::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8122 of file maglev-ir.cc.
                                                               {
  os << "(";
  bool first = true;
  for (compiler::MapRef map : maps()) {
    if (first) {
      first = false;
    } else {
      os << ", ";
    }
    os << *map.object();
  }
  os << ")";
}
receiver_input()
Input& v8::internal::maglev::CheckMapsWithMigration::receiver_input () [inline]
Definition at line 7343 of file maglev-ir.h.
{ return input(kReceiverIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
SetValueLocationConstraints()
void v8::internal::maglev::CheckMapsWithMigration::SetValueLocationConstraints ()
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::CheckMapsWithMigration::kInputTypes {ValueRepresentation::kTagged} [static], [constexpr]
Definition at line 7338 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::CheckMapsWithMigration::kProperties [static], [constexpr]
Initial value:
=
      OpProperties::EagerDeopt() | OpProperties::DeferredCall() |
      OpProperties::CanAllocate() | OpProperties::CanWrite() |
      OpProperties::CanRead()
Definition at line 7333 of file maglev-ir.h.
kReceiverIndex
constexpr int v8::internal::maglev::CheckMapsWithMigration::kReceiverIndex = 0 [static], [constexpr]
Definition at line 7342 of file maglev-ir.h.
maps_
const compiler::ZoneRefSet<Map> v8::internal::maglev::CheckMapsWithMigration::maps_ [private]
Definition at line 7355 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc