v8::internal::FrameWriter Class Reference
Public Member Functions
FrameWriter (Deoptimizer *deoptimizer, FrameDescription *frame, CodeTracer::Scope *trace_scope)
void PushRawValue (intptr_t value, const char *debug_hint)
void PushRawObject (Tagged< Object > obj, const char *debug_hint)
void PushBottommostCallerPc (intptr_t pc)
void PushApprovedCallerPc (intptr_t pc)
void PushCallerFp (intptr_t fp)
void PushCallerConstantPool (intptr_t cp)
void PushTranslatedValue (const TranslatedFrame::iterator &iterator, const char *debug_hint=``)
void PushFeedbackVectorForMaterialization (const TranslatedFrame::iterator &iterator)
void PushStackJSArguments (TranslatedFrame::iterator &iterator, int parameters_count)
unsigned top_offset () const
FrameDescription * frame ()
Static Public Attributes
static const int NO_INPUT_INDEX = -1
Private Member Functions
void PushValue (intptr_t value)
Address output_address (unsigned output_offset)
void DebugPrintOutputValue (intptr_t value, const char *debug_hint=``)
void DebugPrintOutputPc (intptr_t value, const char *debug_hint=``)
void DebugPrintOutputObject (Tagged< Object > obj, unsigned output_offset, const char *debug_hint=``)
Private Attributes
Deoptimizer * deoptimizer_
FrameDescription * frame_
CodeTracer::Scope *const trace_scope_
unsigned top_offset_
Detailed Description
Definition at line 121 of file deoptimizer.cc.
Constructor & Destructor Documentation
FrameWriter()
v8::internal::FrameWriter::FrameWriter (Deoptimizer * deoptimizer, FrameDescription * frame, CodeTracer::Scope * trace_scope) [inline]
Definition at line 124 of file deoptimizer.cc.
      : deoptimizer_(deoptimizer),
        frame_(frame),
        trace_scope_(trace_scope),
        top_offset_(frame->GetFrameSize()) {}
Member Function Documentation
DebugPrintOutputObject()
void v8::internal::FrameWriter::DebugPrintOutputObject (Tagged< Object > obj, unsigned output_offset, const char * debug_hint = ``) [inline], [private]
Definition at line 244 of file deoptimizer.cc.
                                                           {
    if (trace_scope_ != nullptr) {
      PrintF(trace_scope_->file(), " " V8PRIxPTR_FMT ": [top + %3d] <- ",
             output_address(output_offset), output_offset);
      if (IsSmi(obj)) {
        PrintF(trace_scope_->file(), V8PRIxPTR_FMT " <Smi %d>", obj.ptr(),
               Cast<Smi>(obj).value());
      } else {
        ShortPrint(obj, trace_scope_->file());
      }
      PrintF(trace_scope_->file(), " ; %s", debug_hint);
    }
  }
References v8::internal::IsSmi(), v8::internal::PrintF(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::internal::ShortPrint(), and V8PRIxPTR_FMT.
DebugPrintOutputPc()
void v8::internal::FrameWriter::DebugPrintOutputPc (intptr_t value, const char * debug_hint = ``) [inline], [private]
Definition at line 230 of file deoptimizer.cc.
                                                                       {
#ifdef V8_ENABLE_CONTROL_FLOW_INTEGRITY
    if (trace_scope_ != nullptr) {
      PrintF(trace_scope_->file(),
             " " V8PRIxPTR_FMT ": [top + %3d] <- " V8PRIxPTR_FMT
             " (signed) " V8PRIxPTR_FMT " (unsigned) ; %s",
             output_address(top_offset_), top_offset_, value,
             PointerAuthentication::StripPAC(value), debug_hint);
    }
#else
    DebugPrintOutputValue(value, debug_hint);
#endif
  }
References v8::internal::PrintF(), v8::internal::PointerAuthentication::StripPAC(), V8PRIxPTR_FMT, and v8::internal::value.
DebugPrintOutputValue()
void v8::internal::FrameWriter::DebugPrintOutputValue (intptr_t value, const char * debug_hint = ``) [inline], [private]
Definition at line 222 of file deoptimizer.cc.
                                                                          {
    if (trace_scope_ != nullptr) {
      PrintF(trace_scope_->file(),
             " " V8PRIxPTR_FMT ": [top + %3d] <- " V8PRIxPTR_FMT " ; %s",
             output_address(top_offset_), top_offset_, value, debug_hint);
    }
  }
References v8::internal::PrintF(), V8PRIxPTR_FMT, and v8::internal::value.
frame()
FrameDescription* v8::internal::FrameWriter::frame () [inline]
Definition at line 207 of file deoptimizer.cc.
{ return frame_; }
Referenced by v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::Deoptimizer::DoComputeConstructCreateStubFrame(), v8::internal::Deoptimizer::DoComputeConstructInvokeStubFrame(), and v8::internal::Deoptimizer::DoComputeUnoptimizedFrame().
output_address()
Address v8::internal::FrameWriter::output_address (unsigned output_offset) [inline], [private]
Definition at line 216 of file deoptimizer.cc.
                                                 {
    Address output_address =
        static_cast<Address>(frame_->GetTop()) + output_offset;
    return output_address;
  }
PushApprovedCallerPc()
void v8::internal::FrameWriter::PushApprovedCallerPc (intptr_t pc) [inline]
Definition at line 155 of file deoptimizer.cc.
                                         {
    top_offset_ -= kPCOnStackSize;
    frame_->SetCallerPc(top_offset_, pc);
    DebugPrintOutputPc(pc, "caller's pc\n");
  }
References v8::internal::kPCOnStackSize.
Referenced by v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::Deoptimizer::DoComputeConstructCreateStubFrame(), v8::internal::Deoptimizer::DoComputeConstructInvokeStubFrame(), and v8::internal::Deoptimizer::DoComputeUnoptimizedFrame().
PushBottommostCallerPc()
void v8::internal::FrameWriter::PushBottommostCallerPc (intptr_t pc) [inline]
Definition at line 149 of file deoptimizer.cc.
                                           {
    top_offset_ -= kPCOnStackSize;
    frame_->SetFrameSlot(top_offset_, pc);
    DebugPrintOutputPc(pc, "bottommost caller's pc\n");
  }
References v8::internal::kPCOnStackSize.
Referenced by v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), and v8::internal::Deoptimizer::DoComputeUnoptimizedFrame().
PushCallerConstantPool()
void v8::internal::FrameWriter::PushCallerConstantPool (intptr_t cp) [inline]
Definition at line 167 of file deoptimizer.cc.
                                           {
    top_offset_ -= kSystemPointerSize;
    frame_->SetCallerConstantPool(top_offset_, cp);
    DebugPrintOutputValue(cp, "caller's constant_pool\n");
  }
References v8::internal::cp, and v8::internal::kSystemPointerSize.
Referenced by v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::Deoptimizer::DoComputeConstructCreateStubFrame(), v8::internal::Deoptimizer::DoComputeConstructInvokeStubFrame(), and v8::internal::Deoptimizer::DoComputeUnoptimizedFrame().
PushCallerFp()
void v8::internal::FrameWriter::PushCallerFp (intptr_t fp) [inline]
Definition at line 161 of file deoptimizer.cc.
                                 {
    top_offset_ -= kFPOnStackSize;
    frame_->SetCallerFp(top_offset_, fp);
    DebugPrintOutputValue(fp, "caller's fp\n");
  }
References v8::internal::kFPOnStackSize.
Referenced by v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::Deoptimizer::DoComputeConstructCreateStubFrame(), v8::internal::Deoptimizer::DoComputeConstructInvokeStubFrame(), and v8::internal::Deoptimizer::DoComputeUnoptimizedFrame().
PushFeedbackVectorForMaterialization()
void v8::internal::FrameWriter::PushFeedbackVectorForMaterialization (const TranslatedFrame::iterator & iterator) [inline]
Definition at line 184 of file deoptimizer.cc.
                                               {
    // Push a marker temporarily.
    PushRawObject(ReadOnlyRoots(deoptimizer_->isolate()).arguments_marker(),
                  "feedback vector");
    deoptimizer_->QueueFeedbackVectorForMaterialization(
        output_address(top_offset_), iterator);
  }
Referenced by v8::internal::Deoptimizer::DoComputeUnoptimizedFrame().
PushRawObject()
void v8::internal::FrameWriter::PushRawObject (Tagged< Object > obj, const char * debug_hint) [inline]
Definition at line 138 of file deoptimizer.cc.
                                                                 {
    intptr_t value = obj.ptr();
    PushValue(value);
    if (trace_scope_ != nullptr) {
      DebugPrintOutputObject(obj, top_offset_, debug_hint);
    }
  }
References v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), and v8::internal::value.
Referenced by v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::Deoptimizer::DoComputeConstructCreateStubFrame(), v8::internal::Deoptimizer::DoComputeConstructInvokeStubFrame(), v8::internal::Deoptimizer::DoComputeInlinedExtraArguments(), and v8::internal::Deoptimizer::DoComputeUnoptimizedFrame().
PushRawValue()
void v8::internal::FrameWriter::PushRawValue (intptr_t value, const char * debug_hint) [inline]
Definition at line 131 of file deoptimizer.cc.
                                                            {
    PushValue(value);
    if (trace_scope_ != nullptr) {
      DebugPrintOutputValue(value, debug_hint);
    }
  }
References v8::internal::value.
Referenced by v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::Deoptimizer::DoComputeConstructCreateStubFrame(), v8::internal::Deoptimizer::DoComputeConstructInvokeStubFrame(), and v8::internal::Deoptimizer::DoComputeUnoptimizedFrame().
PushStackJSArguments()
void v8::internal::FrameWriter::PushStackJSArguments (TranslatedFrame::iterator & iterator, int parameters_count) [inline]
Definition at line 193 of file deoptimizer.cc.
                                                  {
    std::vector<TranslatedFrame::iterator> parameters;
    parameters.reserve(parameters_count);
    for (int i = 0; i < parameters_count; ++i, ++iterator) {
      parameters.push_back(iterator);
    }
    for (auto& parameter : base::Reversed(parameters)) {
      PushTranslatedValue(parameter, "stack parameter");
    }
  }
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::base::Reversed().
Referenced by v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::Deoptimizer::DoComputeConstructCreateStubFrame(), v8::internal::Deoptimizer::DoComputeInlinedExtraArguments(), and v8::internal::Deoptimizer::DoComputeUnoptimizedFrame().
PushTranslatedValue()
void v8::internal::FrameWriter::PushTranslatedValue (const TranslatedFrame::iterator & iterator, const char * debug_hint = ``) [inline]
Definition at line 173 of file deoptimizer.cc.
                                                        {
    Tagged<Object> obj = iterator->GetRawValue();
    PushRawObject(obj, debug_hint);
    if (trace_scope_ != nullptr) {
      PrintF(trace_scope_->file(), " (input #%d)\n", iterator.input_index());
    }
    deoptimizer_->QueueValueForMaterialization(output_address(top_offset_), obj,
                                               iterator);
  }
References v8::internal::TranslatedValue::GetRawValue(), v8::internal::TranslatedFrame::iterator::input_index(), and v8::internal::PrintF().
Referenced by v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::Deoptimizer::DoComputeConstructCreateStubFrame(), v8::internal::Deoptimizer::DoComputeConstructInvokeStubFrame(), and v8::internal::Deoptimizer::DoComputeUnoptimizedFrame().
PushValue()
void v8::internal::FrameWriter::PushValue (intptr_t value) [inline], [private]
Definition at line 210 of file deoptimizer.cc.
                                 {
    CHECK_GE(top_offset_, 0);
    top_offset_ -= kSystemPointerSize;
    frame_->SetFrameSlot(top_offset_, value);
  }
References CHECK_GE, v8::internal::kSystemPointerSize, and v8::internal::value.
top_offset()
unsigned v8::internal::FrameWriter::top_offset () const [inline]
Definition at line 205 of file deoptimizer.cc.
{ return top_offset_; }
Referenced by v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::Deoptimizer::DoComputeConstructCreateStubFrame(), v8::internal::Deoptimizer::DoComputeConstructInvokeStubFrame(), and v8::internal::Deoptimizer::DoComputeUnoptimizedFrame().
Member Data Documentation
deoptimizer_
Deoptimizer* v8::internal::FrameWriter::deoptimizer_ [private]
Definition at line 259 of file deoptimizer.cc.
frame_
FrameDescription* v8::internal::FrameWriter::frame_ [private]
Definition at line 260 of file deoptimizer.cc.
NO_INPUT_INDEX
const int v8::internal::FrameWriter::NO_INPUT_INDEX = -1 [static]
Definition at line 123 of file deoptimizer.cc.
top_offset_
unsigned v8::internal::FrameWriter::top_offset_ [private]
Definition at line 262 of file deoptimizer.cc.
trace_scope_
CodeTracer::Scope* const v8::internal::FrameWriter::trace_scope_ [private]
Definition at line 261 of file deoptimizer.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/deoptimizer/deoptimizer.cc