v8::internal::DeoptimizationLiteralArray Class Reference
#include <deoptimization-data.h>
Public Member Functions
Tagged< Object > get (int index) const
Tagged< Object > get (PtrComprCageBase cage_base, int index) const
Tagged< MaybeObject > get_raw (int index) const
void set (int index, Tagged< Object > value)
Additional Inherited Members
Detailed Description
Definition at line 22 of file deoptimization-data.h.
Member Function Documentation
get() [1/2]
Tagged< Object > v8::internal::DeoptimizationLiteralArray::get (int index) const [inline]
Definition at line 62 of file deoptimization-data-inl.h.
                                                                     {
  return get(GetPtrComprCageBase(), index);
}
References v8::internal::GetPtrComprCageBase(), and v8::internal::index.
get() [2/2]
Tagged< Object > v8::internal::DeoptimizationLiteralArray::get (PtrComprCageBase cage_base, int index) const [inline]
Definition at line 66 of file deoptimization-data-inl.h.
                                                 {
  Tagged<MaybeObject> maybe = TrustedWeakFixedArray::get(index);
  // Slots in the DeoptimizationLiteralArray should only be cleared when there
  // is no possible code path that could need that slot. This works because the
  // weakly-held deoptimization literals are basically local variables that
  // TurboFan has decided not to keep on the stack. Thus, if the deoptimization
  // literal goes away, then whatever code needed it should be unreachable. The
  // exception is currently running InstructionStream: in that case, the
  // deoptimization literals array might be the only thing keeping the target
  // object alive. Thus, when an InstructionStream is running, we strongly mark
  // all of its deoptimization literals.
  CHECK(!maybe.IsCleared());
  return maybe.GetHeapObjectOrSmi();
}
References CHECK, v8::internal::TaggedArrayBase< TrustedWeakFixedArray, TrustedWeakFixedArrayShape, TrustedObjectLayout >::get(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectOrSmi(), v8::internal::index, and v8::internal::TaggedImpl< kRefType, StorageType >::IsCleared().
get_raw()
Tagged< MaybeObject > v8::internal::DeoptimizationLiteralArray::get_raw (int index) const [inline]
Definition at line 84 of file deoptimization-data-inl.h.
                     {
  return TrustedWeakFixedArray::get(index);
}
References v8::internal::TaggedArrayBase< TrustedWeakFixedArray, TrustedWeakFixedArrayShape, TrustedObjectLayout >::get(), and v8::internal::index.
set()
void v8::internal::DeoptimizationLiteralArray::set (int index, Tagged< Object > value) [inline]
Definition at line 89 of file deoptimization-data-inl.h.
                                                                           {
  Tagged<MaybeObject> maybe = value;
  if (IsBytecodeArray(value)) {
    // The BytecodeArray lives in trusted space, so we cannot reference it from
    // a fixed array. However, we can use the BytecodeArray's wrapper object,
    // which exists for exactly this purpose.
    maybe = Cast<BytecodeArray>(value)->wrapper();
#ifdef V8_ENABLE_SANDBOX
  } else if (IsRegExpData(value)) {
    // Store the RegExpData wrapper if the sandbox is enabled, as data lives in
    // trusted space. We can't store a tagged value to a trusted space object
    // inside the sandbox, we'd need to go through the trusted pointer table.
    // Otherwise we can store the RegExpData object directly.
    maybe = Cast<RegExpData>(value)->wrapper();
#endif
  } else if (Code::IsWeakObjectInDeoptimizationLiteralArray(value)) {
    maybe = MakeWeak(maybe);
  }
  TrustedWeakFixedArray::set(index, maybe);
}
References v8::internal::index, v8::internal::Code::IsWeakObjectInDeoptimizationLiteralArray(), v8::internal::MakeWeak(), v8::internal::TaggedArrayBase< TrustedWeakFixedArray, TrustedWeakFixedArrayShape, TrustedObjectLayout >::set(), and v8::internal::value.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/deoptimization-data.h
/mnt/V8SourceCode/src/objects/deoptimization-data-inl.h