v8::internal::wasm::SyncStreamingDecoder Class Reference
Public Member Functions
SyncStreamingDecoder (Isolate *isolate, WasmEnabledFeatures enabled, CompileTimeImports compile_imports, DirectHandle< Context > context, const char *api_method_name_for_errors, std::shared_ptr< CompilationResultResolver > resolver)
void OnBytesReceived (base::Vector< const uint8_t > bytes) override
void Finish (bool can_use_compiled_module) override
void Abort () override
void NotifyCompilationDiscarded () override
void NotifyNativeModuleCreated (const std::shared_ptr< NativeModule > &) override
Private Attributes
Isolate * isolate_
const WasmEnabledFeatures enabled_
CompileTimeImports compile_imports_
IndirectHandle< Context > context_
const char * api_method_name_for_errors_
std::shared_ptr< CompilationResultResolver > resolver_
std::vector< std::vector< uint8_t > > buffer_
size_t buffer_size_ = 0
Additional Inherited Members
Detailed Description
Definition at line 15 of file sync-streaming-decoder.cc.
Constructor & Destructor Documentation
SyncStreamingDecoder()
v8::internal::wasm::SyncStreamingDecoder::SyncStreamingDecoder (Isolate * isolate, WasmEnabledFeatures enabled, CompileTimeImports compile_imports, DirectHandle< Context > context, const char * api_method_name_for_errors, std::shared_ptr< CompilationResultResolver > resolver) [inline]
Definition at line 17 of file sync-streaming-decoder.cc.
      : isolate_(isolate),
        enabled_(enabled),
        compile_imports_(std::move(compile_imports)),
        context_(indirect_handle(context)),
        api_method_name_for_errors_(api_method_name_for_errors),
        resolver_(resolver) {}
Member Function Documentation
Abort()
void v8::internal::wasm::SyncStreamingDecoder::Abort () [inline], [override], [virtual]
Implements v8::internal::wasm::StreamingDecoder.
Definition at line 78 of file sync-streaming-decoder.cc.
                        {
    // Abort is fully handled by the API, we only clear the buffer.
    buffer_.clear();
  }
Finish()
void v8::internal::wasm::SyncStreamingDecoder::Finish (bool can_use_compiled_module) [inline], [override], [virtual]
Implements v8::internal::wasm::StreamingDecoder.
Definition at line 37 of file sync-streaming-decoder.cc.
                                                     {
    // We copy all received chunks into one byte buffer.
    auto bytes = base::OwnedVector<uint8_t>::NewForOverwrite(buffer_size_);
    uint8_t* destination = bytes.begin();
    for (auto& chunk : buffer_) {
      std::memcpy(destination, chunk.data(), chunk.size());
      destination += chunk.size();
    }
    CHECK_EQ(destination - bytes.begin(), buffer_size_);
    // Check if we can deserialize the module from cache.
    if (can_use_compiled_module && deserializing()) {
      HandleScope scope(isolate_);
      SaveAndSwitchContext saved_context(isolate_, *context_);
      MaybeDirectHandle<WasmModuleObject> module_object =
          DeserializeNativeModule(isolate_, compiled_module_bytes_,
                                  bytes.as_vector(), compile_imports_,
                                  base::VectorOf(url()));
      if (!module_object.is_null()) {
        DirectHandle<WasmModuleObject> module = module_object.ToHandleChecked();
        resolver_->OnCompilationSucceeded(module);
        return;
      }
    }
    // Compile the received bytes synchronously.
    ErrorThrower thrower(isolate_, api_method_name_for_errors_);
    MaybeDirectHandle<WasmModuleObject> module_object =
        GetWasmEngine()->SyncCompile(isolate_, enabled_,
                                     std::move(compile_imports_), &thrower,
                                     std::move(bytes));
    if (thrower.error()) {
      resolver_->OnCompilationFailed(thrower.Reify());
      return;
    }
    DirectHandle<WasmModuleObject> module = module_object.ToHandleChecked();
    resolver_->OnCompilationSucceeded(module);
  }
References CHECK_EQ, v8::internal::wasm::DeserializeNativeModule(), v8::internal::wasm::ErrorThrower::error(), v8::internal::wasm::GetWasmEngine(), v8::internal::MaybeDirectHandle< T >::is_null(), v8::base::OwnedVector< T >::NewForOverwrite(), v8::internal::wasm::ErrorThrower::Reify(), v8::internal::wasm::WasmEngine::SyncCompile(), v8::internal::MaybeDirectHandle< T >::ToHandleChecked(), and v8::base::VectorOf().
NotifyCompilationDiscarded()
void v8::internal::wasm::SyncStreamingDecoder::NotifyCompilationDiscarded () [inline], [override], [virtual]
Implements v8::internal::wasm::StreamingDecoder.
Definition at line 83 of file sync-streaming-decoder.cc.
{ buffer_.clear(); }
NotifyNativeModuleCreated()
void v8::internal::wasm::SyncStreamingDecoder::NotifyNativeModuleCreated (const std::shared_ptr< NativeModule > &) [inline], [override], [virtual]
Implements v8::internal::wasm::StreamingDecoder.
Definition at line 85 of file sync-streaming-decoder.cc.
                                                   {
    // This function is only called from the {AsyncCompileJob}.
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
OnBytesReceived()
void v8::internal::wasm::SyncStreamingDecoder::OnBytesReceived (base::Vector< const uint8_t > bytes) [inline], [override], [virtual]
Implements v8::internal::wasm::StreamingDecoder.
Definition at line 30 of file sync-streaming-decoder.cc.
                                                                 {
    buffer_.emplace_back(bytes.size());
    CHECK_EQ(buffer_.back().size(), bytes.size());
    std::memcpy(buffer_.back().data(), bytes.data(), bytes.size());
    buffer_size_ += bytes.size();
  }
References CHECK_EQ, v8::base::Vector< T >::data(), and v8::base::Vector< T >::size().
Member Data Documentation
api_method_name_for_errors_
const char* v8::internal::wasm::SyncStreamingDecoder::api_method_name_for_errors_ [private]
Definition at line 96 of file sync-streaming-decoder.cc.
buffer_
std::vector<std::vector<uint8_t> > v8::internal::wasm::SyncStreamingDecoder::buffer_ [private]
Definition at line 99 of file sync-streaming-decoder.cc.
buffer_size_
size_t v8::internal::wasm::SyncStreamingDecoder::buffer_size_ = 0 [private]
Definition at line 100 of file sync-streaming-decoder.cc.
compile_imports_
CompileTimeImports v8::internal::wasm::SyncStreamingDecoder::compile_imports_ [private]
Definition at line 94 of file sync-streaming-decoder.cc.
context_
IndirectHandle<Context> v8::internal::wasm::SyncStreamingDecoder::context_ [private]
Definition at line 95 of file sync-streaming-decoder.cc.
enabled_
const WasmEnabledFeatures v8::internal::wasm::SyncStreamingDecoder::enabled_ [private]
Definition at line 93 of file sync-streaming-decoder.cc.
isolate_
Isolate* v8::internal::wasm::SyncStreamingDecoder::isolate_ [private]
Definition at line 92 of file sync-streaming-decoder.cc.
resolver_
std::shared_ptr<CompilationResultResolver> v8::internal::wasm::SyncStreamingDecoder::resolver_ [private]
Definition at line 97 of file sync-streaming-decoder.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/sync-streaming-decoder.cc