v8::internal::NativeContextInferrer Class Reference
#include <memory-measurement.h>
Public Member Functions
bool Infer (PtrComprCageBase cage_base, Tagged< Map > map, Tagged< HeapObject > object, Address *native_context)
Detailed Description
Definition at line 70 of file memory-measurement.h.
Member Function Documentation
Infer()
bool v8::internal::NativeContextInferrer::Infer (PtrComprCageBase cage_base, Tagged< Map > map, Tagged< HeapObject > object, Address * native_context) [inline]
Definition at line 21 of file memory-measurement-inl.h.
                                                           {
  Tagged<Object> maybe_native_context =
      map->map()->raw_native_context_or_null();
  *native_context = maybe_native_context.ptr();
  // The value might be equal to Smi::uninitialized_deserialization_value()
  // during NativeContext deserialization.
  return !IsSmi(maybe_native_context) && !IsNull(maybe_native_context);
}
References v8::internal::IsNull(), v8::internal::IsSmi(), v8::internal::native_context, and v8::internal::TaggedImpl< kRefType, StorageType >::ptr().
Referenced by v8::internal::ConcurrentMarking::RunMajor().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/memory-measurement.h
/mnt/V8SourceCode/src/heap/memory-measurement-inl.h