v8::internal::HandleScopeImplementer Class Reference
#include <api.h>
Classes
class EnteredContextRewindScope
Public Member Functions
HandleScopeImplementer (Isolate *isolate)
~HandleScopeImplementer ()
HandleScopeImplementer (const HandleScopeImplementer &)=delete
HandleScopeImplementer & operator= (const HandleScopeImplementer &)=delete
char * RestoreThread (char *from)
char * ArchiveThread (char *to)
void FreeThreadResources ()
V8_EXPORT_PRIVATE void Iterate (i::RootVisitor *v)
internal::Address * GetSpareOrNewBlock ()
void DeleteExtensions (internal::Address *prev_limit)
void EnterContext (Tagged< NativeContext > context)
void LeaveContext ()
bool LastEnteredContextWas (Tagged< NativeContext > context)
size_t EnteredContextCount () const
DirectHandle< NativeContext > LastEnteredContext ()
void SaveContext (Tagged< Context > context)
Tagged< Context > RestoreContext ()
bool HasSavedContexts ()
DetachableVector< Address * > * blocks ()
Isolate * isolate () const
void ReturnBlock (Address *block)
Static Public Member Functions
static int ArchiveSpacePerThread ()
static V8_EXPORT_PRIVATE char * Iterate (i::RootVisitor *v, char *data)
Static Public Attributes
static const size_t kEnteredContextsOffset
Private Member Functions
void ResetAfterArchive ()
void Free ()
void BeginPersistentScope ()
bool HasPersistentScope () const
std::unique_ptr< PersistentHandles > DetachPersistent (Address *first_block)
void IterateThis (RootVisitor *v)
char * RestoreThreadHelper (char *from)
char * ArchiveThreadHelper (char *to)
Private Attributes
Isolate * isolate_
DetachableVector< Address * > blocks_
DetachableVector< Tagged< NativeContext > > entered_contexts_
DetachableVector< Tagged< Context > > saved_contexts_
Address * spare_
std::optional< Address * > last_handle_before_persistent_block_
HandleScopeData handle_scope_data_
Friends
class HandleScopeImplementerOffsets
class PersistentHandlesScope
Detailed Description
Definition at line 329 of file api.h.
Constructor & Destructor Documentation
HandleScopeImplementer() [1/2]
v8::internal::HandleScopeImplementer::HandleScopeImplementer (Isolate * isolate) [inline], [explicit]
Definition at line 347 of file api.h.
      : isolate_(isolate), spare_(nullptr) {}
Referenced by ArchiveSpacePerThread().
 HandleScopeImplementer()
v8::internal::HandleScopeImplementer::~HandleScopeImplementer () [inline]
Definition at line 350 of file api.h.
{ DeleteArray(spare_); }
References spare_.
HandleScopeImplementer() [2/2]
v8::internal::HandleScopeImplementer::HandleScopeImplementer (const HandleScopeImplementer &) [delete]
Member Function Documentation
ArchiveSpacePerThread()
int v8::internal::HandleScopeImplementer::ArchiveSpacePerThread () [static]
Definition at line 12005 of file api.cc.
                                                  {
  return sizeof(HandleScopeImplementer);
}
References HandleScopeImplementer().
Referenced by v8::internal::ArchiveSpacePerThread(), ArchiveThread(), Iterate(), v8::internal::ThreadManager::IterateArchivedThreads(), and RestoreThread().
ArchiveThread()
char * v8::internal::HandleScopeImplementer::ArchiveThread (char * to)
Definition at line 11994 of file api.cc.
                                                         {
  HandleScopeData* current = isolate_->handle_scope_data();
  handle_scope_data_ = *current;
  MemCopy(storage, this, sizeof(*this));
  ResetAfterArchive();
  current->Initialize();
  return storage + ArchiveSpacePerThread();
}
References ArchiveSpacePerThread(), v8::internal::Isolate::handle_scope_data(), handle_scope_data_, v8::internal::HandleScopeData::Initialize(), isolate_, v8::internal::MemCopy(), and ResetAfterArchive().
Referenced by v8::internal::ThreadManager::EagerlyArchiveThread().
ArchiveThreadHelper()
char* v8::internal::HandleScopeImplementer::ArchiveThreadHelper (char * to) [private]
BeginPersistentScope()
void v8::internal::HandleScopeImplementer::BeginPersistentScope () [inline], [private]
Definition at line 416 of file api.h.
                              {
    DCHECK(!last_handle_before_persistent_block_.has_value());
    last_handle_before_persistent_block_ = isolate()->handle_scope_data()->next;
  }
References v8::internal::DCHECK(), v8::internal::Isolate::handle_scope_data(), isolate(), last_handle_before_persistent_block_, and v8::internal::HandleScopeData::next.
Referenced by v8::internal::PersistentHandlesScope::PersistentHandlesScope().
blocks()
DetachableVector<Address*>* v8::internal::HandleScopeImplementer::blocks () [inline]
Definition at line 381 of file api.h.
{ return &blocks_; }
References blocks_.
Referenced by IterateThis(), and v8::internal::PersistentHandlesScope::PersistentHandlesScope().
DeleteExtensions()
void v8::internal::HandleScopeImplementer::DeleteExtensions (internal::Address * prev_limit) [inline]
Definition at line 481 of file api.h.
                                                                         {
  while (!blocks_.empty()) {
    internal::Address* block_start = blocks_.back();
    internal::Address* block_limit = block_start + kHandleBlockSize;
    // SealHandleScope may make the prev_limit to point inside the block.
    // Cast possibly-unrelated pointers to plain Address before comparing them
    // to avoid undefined behavior.
    if (reinterpret_cast<Address>(block_start) <
            reinterpret_cast<Address>(prev_limit) &&
        reinterpret_cast<Address>(prev_limit) <=
            reinterpret_cast<Address>(block_limit)) {
#ifdef ENABLE_LOCAL_HANDLE_ZAPPING
      internal::HandleScope::ZapRange(prev_limit, block_limit);
#endif
      break;
    }
    blocks_.pop_back();
#ifdef ENABLE_LOCAL_HANDLE_ZAPPING
    internal::HandleScope::ZapRange(block_start, block_limit);
#endif
    if (spare_ != nullptr) {
      DeleteArray(spare_);
    }
    spare_ = block_start;
  }
  DCHECK((blocks_.empty() && prev_limit == nullptr) ||
         (!blocks_.empty() && prev_limit != nullptr));
}
References blocks_, v8::internal::DCHECK(), v8::internal::kHandleBlockSize, and spare_.
Referenced by v8::internal::HandleScope::DeleteExtensions().
DetachPersistent()
std::unique_ptr< PersistentHandles > v8::internal::HandleScopeImplementer::DetachPersistent (Address * first_block) [private]
Definition at line 12082 of file api.cc.
                          {
  std::unique_ptr<PersistentHandles> ph(new PersistentHandles(isolate()));
  DCHECK(HasPersistentScope());
  DCHECK_NOT_NULL(first_block);
  Address* block_start;
  do {
    block_start = blocks_.back();
    ph->blocks_.push_back(blocks_.back());
#if DEBUG
    ph->ordered_blocks_.insert(blocks_.back());
#endif
    blocks_.pop_back();
  } while (block_start != first_block);
  // ph->blocks_ now contains the blocks installed on the HandleScope stack
  // since BeginPersistentScope was called, but in reverse order.
  // Switch first and last blocks, such that the last block is the one
  // that is potentially half full.
  DCHECK(!ph->blocks_.empty());
  std::swap(ph->blocks_.front(), ph->blocks_.back());
  ph->block_next_ = isolate()->handle_scope_data()->next;
  block_start = ph->blocks_.back();
  ph->block_limit_ = block_start + kHandleBlockSize;
  DCHECK_EQ(blocks_.empty(),
            last_handle_before_persistent_block_.value() == nullptr);
  last_handle_before_persistent_block_.reset();
  return ph;
}
References blocks_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NOT_NULL, v8::internal::Isolate::handle_scope_data(), HasPersistentScope(), isolate(), v8::internal::kHandleBlockSize, last_handle_before_persistent_block_, and v8::internal::HandleScopeData::next.
Referenced by v8::internal::PersistentHandlesScope::Detach().
EnterContext()
void v8::internal::HandleScopeImplementer::EnterContext (Tagged< NativeContext > context) [inline]
Definition at line 507 of file api-inl.h.
                                                                       {
  entered_contexts_.push_back(context);
}
References entered_contexts_.
Referenced by v8::internal::wasm::InstanceBuilder::ExecuteStartFunction().
EnteredContextCount()
size_t v8::internal::HandleScopeImplementer::EnteredContextCount () const [inline]
Definition at line 371 of file api.h.
{ return entered_contexts_.size(); }
References entered_contexts_.
Referenced by v8::internal::HandleScopeImplementer::EnteredContextRewindScope::~EnteredContextRewindScope().
Free()
void v8::internal::HandleScopeImplementer::Free () [inline], [private]
Definition at line 401 of file api.h.
              {
    DCHECK(blocks_.empty());
    DCHECK(entered_contexts_.empty());
    DCHECK(saved_contexts_.empty());
    blocks_.free();
    entered_contexts_.free();
    saved_contexts_.free();
    if (spare_ != nullptr) {
      DeleteArray(spare_);
      spare_ = nullptr;
    }
    DCHECK(isolate_->thread_local_top()->CallDepthIsZero());
  }
References blocks_, v8::internal::ThreadLocalTop::CallDepthIsZero(), v8::internal::DCHECK(), entered_contexts_, isolate_, saved_contexts_, spare_, and v8::internal::Isolate::thread_local_top().
Referenced by FreeThreadResources().
FreeThreadResources()
void v8::internal::HandleScopeImplementer::FreeThreadResources ()
Definition at line 11992 of file api.cc.
{ Free(); }
References Free().
Referenced by v8::internal::ThreadManager::FreeThreadResources().
GetSpareOrNewBlock()
internal::Address * v8::internal::HandleScopeImplementer::GetSpareOrNewBlock () [inline]
Definition at line 473 of file api.h.
                                                            {
  internal::Address* block =
      (spare_ != nullptr) ? spare_
                          : NewArray<internal::Address>(kHandleBlockSize);
  spare_ = nullptr;
  return block;
}
References v8::internal::kHandleBlockSize, and spare_.
Referenced by v8::internal::PersistentHandlesScope::PersistentHandlesScope().
HasPersistentScope()
bool v8::internal::HandleScopeImplementer::HasPersistentScope () const [inline], [private]
Definition at line 420 of file api.h.
                                  {
    return last_handle_before_persistent_block_.has_value();
  }
References last_handle_before_persistent_block_.
Referenced by DetachPersistent(), v8::internal::PersistentHandlesScope::IsActive(), and IterateThis().
HasSavedContexts()
bool v8::internal::HandleScopeImplementer::HasSavedContexts () [inline]
Definition at line 458 of file api.h.
                                              {
  return !saved_contexts_.empty();
}
References saved_contexts_.
isolate()
Isolate* v8::internal::HandleScopeImplementer::isolate () const [inline]
Definition at line 382 of file api.h.
{ return isolate_; }
References isolate_.
Referenced by BeginPersistentScope(), v8::internal::PersistentHandlesScope::Detach(), DetachPersistent(), v8::internal::PersistentHandlesScope::PersistentHandlesScope(), and v8::internal::PersistentHandlesScope::~PersistentHandlesScope().
Iterate() [1/2]
void v8::internal::HandleScopeImplementer::Iterate (i::RootVisitor * v)
Definition at line 12069 of file api.cc.
                                                   {
  HandleScopeData* current = isolate_->handle_scope_data();
  handle_scope_data_ = *current;
  IterateThis(v);
}
References v8::internal::Isolate::handle_scope_data(), handle_scope_data_, isolate_, and IterateThis().
Referenced by v8::internal::Heap::CheckHandleCount(), v8::internal::ThreadManager::Iterate(), v8::internal::Heap::IterateRoots(), and v8::internal::Heap::IterateRootsForPrecisePinning().
Iterate() [2/2]
char * v8::internal::HandleScopeImplementer::Iterate (i::RootVisitor * v, char * data) [static]
Definition at line 12075 of file api.cc.
                                                                   {
  HandleScopeImplementer* scope_implementer =
      reinterpret_cast<HandleScopeImplementer*>(storage);
  scope_implementer->IterateThis(v);
  return storage + ArchiveSpacePerThread();
}
References ArchiveSpacePerThread(), and IterateThis().
IterateThis()
void v8::internal::HandleScopeImplementer::IterateThis (RootVisitor * v) [private]
Definition at line 12015 of file api.cc.
                                                       {
#ifdef DEBUG
  bool found_block_before_persistent = false;
#endif
  // Iterate over all handles in the blocks except for the last.
  for (int i = static_cast<int>(blocks()->size()) - 2; i >= 0; --i) {
    Address* block = blocks()->at(i);
    // Cast possibly-unrelated pointers to plain Address before comparing them
    // to avoid undefined behavior.
    if (HasPersistentScope() &&
        (reinterpret_cast<Address>(
             last_handle_before_persistent_block_.value()) <=
         reinterpret_cast<Address>(&block[kHandleBlockSize])) &&
        (reinterpret_cast<Address>(
             last_handle_before_persistent_block_.value()) >=
         reinterpret_cast<Address>(block))) {
      v->VisitRootPointers(
          Root::kHandleScope, nullptr, FullObjectSlot(block),
          FullObjectSlot(last_handle_before_persistent_block_.value()));
      DCHECK(!found_block_before_persistent);
#ifdef DEBUG
      found_block_before_persistent = true;
#endif
    } else {
      v->VisitRootPointers(Root::kHandleScope, nullptr, FullObjectSlot(block),
                           FullObjectSlot(&block[kHandleBlockSize]));
    }
  }
  DCHECK_EQ(HasPersistentScope() &&
                last_handle_before_persistent_block_.value() != nullptr,
            found_block_before_persistent);
  // Iterate over live handles in the last block (if any).
  if (!blocks()->empty()) {
    v->VisitRootPointers(Root::kHandleScope, nullptr,
                         FullObjectSlot(blocks()->back()),
                         FullObjectSlot(handle_scope_data_.next));
  }
  saved_contexts_.shrink_to_fit();
  if (!saved_contexts_.empty()) {
    FullObjectSlot start(&saved_contexts_.front());
    v->VisitRootPointers(Root::kHandleScope, nullptr, start,
                         start + static_cast<int>(saved_contexts_.size()));
  }
  entered_contexts_.shrink_to_fit();
  if (!entered_contexts_.empty()) {
    FullObjectSlot start(&entered_contexts_.front());
    v->VisitRootPointers(Root::kHandleScope, nullptr, start,
                         start + static_cast<int>(entered_contexts_.size()));
  }
}
References blocks(), v8::internal::DCHECK(), DCHECK_EQ, entered_contexts_, handle_scope_data_, HasPersistentScope(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kHandleBlockSize, last_handle_before_persistent_block_, v8::internal::HandleScopeData::next, saved_contexts_, size(), and v8::internal::RootVisitor::VisitRootPointers().
Referenced by Iterate().
LastEnteredContext()
DirectHandle< NativeContext > v8::internal::HandleScopeImplementer::LastEnteredContext () [inline]
Definition at line 511 of file api-inl.h.
                                                                       {
  if (entered_contexts_.empty()) return {};
  return direct_handle(entered_contexts_.back(), isolate_);
}
References v8::internal::direct_handle(), entered_contexts_, and isolate_.
Referenced by v8::Isolate::GetEnteredOrMicrotaskContext().
LastEnteredContextWas()
bool v8::internal::HandleScopeImplementer::LastEnteredContextWas (Tagged< NativeContext > context) [inline]
Definition at line 467 of file api.h.
                                   {
  return !entered_contexts_.empty() && entered_contexts_.back() == context;
}
References entered_contexts_.
LeaveContext()
void v8::internal::HandleScopeImplementer::LeaveContext () [inline]
Definition at line 462 of file api.h.
                                          {
  DCHECK(!entered_contexts_.empty());
  entered_contexts_.pop_back();
}
References v8::internal::DCHECK(), and entered_contexts_.
Referenced by v8::internal::wasm::InstanceBuilder::ExecuteStartFunction().
operator=()
HandleScopeImplementer& v8::internal::HandleScopeImplementer::operator= (const HandleScopeImplementer &) [delete]
ResetAfterArchive()
void v8::internal::HandleScopeImplementer::ResetAfterArchive () [inline], [private]
Definition at line 393 of file api.h.
                           {
    blocks_.detach();
    entered_contexts_.detach();
    saved_contexts_.detach();
    spare_ = nullptr;
    last_handle_before_persistent_block_.reset();
  }
References blocks_, entered_contexts_, last_handle_before_persistent_block_, saved_contexts_, and spare_.
Referenced by ArchiveThread().
RestoreContext()
Tagged< Context > v8::internal::HandleScopeImplementer::RestoreContext () [inline]
Definition at line 452 of file api.h.
                                                       {
  Tagged<Context> last_context = saved_contexts_.back();
  saved_contexts_.pop_back();
  return last_context;
}
References saved_contexts_.
RestoreThread()
char * v8::internal::HandleScopeImplementer::RestoreThread (char * from)
Definition at line 12009 of file api.cc.
                                                         {
  MemCopy(this, storage, sizeof(*this));
  *isolate_->handle_scope_data() = handle_scope_data_;
  return storage + ArchiveSpacePerThread();
}
References ArchiveSpacePerThread(), v8::internal::Isolate::handle_scope_data(), handle_scope_data_, isolate_, and v8::internal::MemCopy().
Referenced by v8::internal::ThreadManager::RestoreThread().
RestoreThreadHelper()
char* v8::internal::HandleScopeImplementer::RestoreThreadHelper (char * from) [private]
ReturnBlock()
void v8::internal::HandleScopeImplementer::ReturnBlock (Address * block) [inline]
Definition at line 384 of file api.h.
                                   {
    DCHECK_NOT_NULL(block);
    if (spare_ != nullptr) DeleteArray(spare_);
    spare_ = block;
  }
References DCHECK_NOT_NULL, and spare_.
SaveContext()
void v8::internal::HandleScopeImplementer::SaveContext (Tagged< Context > context) [inline]
Definition at line 448 of file api.h.
                                                                {
  saved_contexts_.push_back(context);
}
References saved_contexts_.
Friends And Related Function Documentation
HandleScopeImplementerOffsets
friend class HandleScopeImplementerOffsets [friend]
Definition at line 442 of file api.h.
PersistentHandlesScope
friend class PersistentHandlesScope [friend]
Definition at line 443 of file api.h.
Member Data Documentation
blocks_
DetachableVector<Address*> v8::internal::HandleScopeImplementer::blocks_ [private]
Definition at line 426 of file api.h.
Referenced by blocks(), DeleteExtensions(), DetachPersistent(), Free(), and ResetAfterArchive().
entered_contexts_
DetachableVector<Tagged<NativeContext> > v8::internal::HandleScopeImplementer::entered_contexts_ [private]
Definition at line 429 of file api.h.
Referenced by EnterContext(), EnteredContextCount(), Free(), IterateThis(), LastEnteredContext(), LastEnteredContextWas(), LeaveContext(), and ResetAfterArchive().
handle_scope_data_
HandleScopeData v8::internal::HandleScopeImplementer::handle_scope_data_ [private]
Definition at line 436 of file api.h.
Referenced by ArchiveThread(), Iterate(), IterateThis(), and RestoreThread().
isolate_
Isolate* v8::internal::HandleScopeImplementer::isolate_ [private]
Definition at line 425 of file api.h.
Referenced by ArchiveThread(), Free(), isolate(), Iterate(), LastEnteredContext(), and RestoreThread().
kEnteredContextsOffset
const size_t v8::internal::HandleScopeImplementer::kEnteredContextsOffset [static]
Initial value:
=
    offsetof(HandleScopeImplementer, entered_contexts_)
Definition at line 390 of file api.h.
Referenced by v8::internal::MicrotaskQueueBuiltinsAssembler::EnterContext(), v8::internal::MicrotaskQueueBuiltinsAssembler::GetEnteredContextCount(), and v8::internal::MicrotaskQueueBuiltinsAssembler::RewindEnteredContext().
last_handle_before_persistent_block_
std::optional<Address*> v8::internal::HandleScopeImplementer::last_handle_before_persistent_block_ [private]
Definition at line 434 of file api.h.
Referenced by BeginPersistentScope(), DetachPersistent(), HasPersistentScope(), IterateThis(), and ResetAfterArchive().
saved_contexts_
DetachableVector<Tagged<Context> > v8::internal::HandleScopeImplementer::saved_contexts_ [private]
Definition at line 432 of file api.h.
Referenced by Free(), HasSavedContexts(), IterateThis(), ResetAfterArchive(), RestoreContext(), and SaveContext().
spare_
Address* v8::internal::HandleScopeImplementer::spare_ [private]
Definition at line 433 of file api.h.
Referenced by DeleteExtensions(), Free(), GetSpareOrNewBlock(), ResetAfterArchive(), ReturnBlock(), and ~HandleScopeImplementer().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/api/api.h
/mnt/V8SourceCode/src/api/api-inl.h
/mnt/V8SourceCode/src/api/api.cc