cppgc::internal::anonymous_namespace{compactor.cc}::CompactionState Class Reference
Public Member Functions
CompactionState (NormalPageSpace *space, MovableReferences &movable_references)
void AddPage (NormalPage *page)
void RelocateObject (const NormalPage *page, const Address header, size_t size)
void FinishCompactingSpace ()
void FinishCompactingPage (NormalPage *page)
Private Types
using Pages = std::vector< NormalPage * >
Private Member Functions
CPPGC_STACK_ALLOCATED ()
void ReturnCurrentPageToSpace ()
Private Attributes
NormalPageSpace * space_
MovableReferences & movable_references_
NormalPage * current_page_ = nullptr
size_t used_bytes_in_current_page_ = 0
Pages available_pages_
Detailed Description
Definition at line 231 of file compactor.cc.
Member Typedef Documentation
Pages
using cppgc::internal::anonymous_namespace{compactor.cc}::CompactionState::Pages = std::vector<NormalPage*> [private]
Definition at line 233 of file compactor.cc.
Constructor & Destructor Documentation
CompactionState()
cppgc::internal::anonymous_namespace{compactor.cc}::CompactionState::CompactionState (NormalPageSpace * space, MovableReferences & movable_references) [inline]
Definition at line 236 of file compactor.cc.
      : space_(space), movable_references_(movable_references) {}
Member Function Documentation
AddPage()
void cppgc::internal::anonymous_namespace{compactor.cc}::CompactionState::AddPage (NormalPage * page) [inline]
Definition at line 239 of file compactor.cc.
                                 {
    DCHECK_EQ(space_, &page->space());
    // If not the first page, add |page| onto the available pages chain.
    if (!current_page_)
      current_page_ = page;
    else
      available_pages_.push_back(page);
  }
References DCHECK_EQ, and cppgc::internal::BasePage::space().
Referenced by cppgc::internal::anonymous_namespace{compactor.cc}::CompactPage().
CPPGC_STACK_ALLOCATED()
cppgc::internal::anonymous_namespace{compactor.cc}::CompactionState::CPPGC_STACK_ALLOCATED () [private]
FinishCompactingPage()
void cppgc::internal::anonymous_namespace{compactor.cc}::CompactionState::FinishCompactingPage (NormalPage * page) [inline]
Definition at line 294 of file compactor.cc.
                                              {
#if DEBUG || defined(V8_USE_MEMORY_SANITIZER) || \
    defined(V8_USE_ADDRESS_SANITIZER)
    // Zap the unused portion, until it is either compacted into or freed.
    if (current_page_ != page) {
      ZapMemory(page->PayloadStart(), page->PayloadSize());
    } else {
      ZapMemory(page->PayloadStart() + used_bytes_in_current_page_,
                page->PayloadSize() - used_bytes_in_current_page_);
    }
#endif
    page->object_start_bitmap().MarkAsFullyPopulated();
  }
References cppgc::internal::ObjectStartBitmap::MarkAsFullyPopulated(), cppgc::internal::NormalPage::object_start_bitmap(), cppgc::internal::NormalPage::PayloadSize(), cppgc::internal::NormalPage::PayloadStart(), and cppgc::internal::ZapMemory().
Referenced by cppgc::internal::anonymous_namespace{compactor.cc}::CompactPage().
FinishCompactingSpace()
void cppgc::internal::anonymous_namespace{compactor.cc}::CompactionState::FinishCompactingSpace () [inline]
Definition at line 278 of file compactor.cc.
                               {
    // If the current page hasn't been allocated into, add it to the available
    // list, for subsequent release below.
    if (used_bytes_in_current_page_ == 0) {
      available_pages_.push_back(current_page_);
    } else {
      ReturnCurrentPageToSpace();
    }
    // Return remaining available pages back to the backend.
    for (NormalPage* page : available_pages_) {
      SetMemoryInaccessible(page->PayloadStart(), page->PayloadSize());
      NormalPage::Destroy(page);
    }
  }
References cppgc::internal::NormalPage::Destroy(), and cppgc::internal::SetMemoryInaccessible().
Referenced by cppgc::internal::anonymous_namespace{compactor.cc}::CompactSpace().
RelocateObject()
void cppgc::internal::anonymous_namespace{compactor.cc}::CompactionState::RelocateObject (const NormalPage * page, const Address header, size_t size) [inline]
Definition at line 248 of file compactor.cc.
                                   {
    // Allocate and copy over the live object.
    Address compact_frontier =
        current_page_->PayloadStart() + used_bytes_in_current_page_;
    if (compact_frontier + size > current_page_->PayloadEnd()) {
      // Can't fit on current page. Add remaining onto the freelist and advance
      // to next available page.
      ReturnCurrentPageToSpace();
      current_page_ = available_pages_.back();
      available_pages_.pop_back();
      used_bytes_in_current_page_ = 0;
      compact_frontier = current_page_->PayloadStart();
    }
    if (V8_LIKELY(compact_frontier != header)) {
      // Use a non-overlapping copy, if possible.
      if (current_page_ == page)
        memmove(compact_frontier, header, size);
      else
        memcpy(compact_frontier, header, size);
      movable_references_.Relocate(header + sizeof(HeapObjectHeader),
                                   compact_frontier + sizeof(HeapObjectHeader),
                                   size);
    }
    current_page_->object_start_bitmap().SetBit(compact_frontier);
    used_bytes_in_current_page_ += size;
    DCHECK_LE(used_bytes_in_current_page_, current_page_->PayloadSize());
  }
References DCHECK_LE, size(), and V8_LIKELY.
Referenced by cppgc::internal::anonymous_namespace{compactor.cc}::CompactPage().
ReturnCurrentPageToSpace()
void cppgc::internal::anonymous_namespace{compactor.cc}::CompactionState::ReturnCurrentPageToSpace () [inline], [private]
Definition at line 309 of file compactor.cc.
                                  {
    DCHECK_EQ(space_, &current_page_->space());
    space_->AddPage(current_page_);
    if (used_bytes_in_current_page_ != current_page_->PayloadSize()) {
      // Put the remainder of the page onto the free list.
      size_t freed_size =
          current_page_->PayloadSize() - used_bytes_in_current_page_;
      Address payload = current_page_->PayloadStart();
      Address free_start = payload + used_bytes_in_current_page_;
      SetMemoryInaccessible(free_start, freed_size);
      space_->free_list().Add({free_start, freed_size});
      current_page_->object_start_bitmap().SetBit(free_start);
    }
  }
References DCHECK_EQ, and cppgc::internal::SetMemoryInaccessible().
Member Data Documentation
available_pages_
Pages cppgc::internal::anonymous_namespace{compactor.cc}::CompactionState::available_pages_ [private]
Definition at line 332 of file compactor.cc.
current_page_
NormalPage* cppgc::internal::anonymous_namespace{compactor.cc}::CompactionState::current_page_ = nullptr [private]
Definition at line 327 of file compactor.cc.
movable_references_
MovableReferences& cppgc::internal::anonymous_namespace{compactor.cc}::CompactionState::movable_references_ [private]
Definition at line 325 of file compactor.cc.
space_
NormalPageSpace* cppgc::internal::anonymous_namespace{compactor.cc}::CompactionState::space_ [private]
Definition at line 324 of file compactor.cc.
used_bytes_in_current_page_
size_t cppgc::internal::anonymous_namespace{compactor.cc}::CompactionState::used_bytes_in_current_page_ = 0 [private]
Definition at line 329 of file compactor.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc/compactor.cc