v8::internal::compiler::turboshaft::RedundantStoreAnalysis Class Reference
#include <store-store-elimination-reducer-inl.h>
Public Member Functions
RedundantStoreAnalysis (const Graph &graph, Zone *phase_zone)
void Run (ZoneSet< OpIndex > &eliminable_stores, ZoneMap< OpIndex, uint64_t > &mergeable_store_pairs)
void ProcessBlock (const Block &block)
Private Attributes
const Graph & graph_
MaybeRedundantStoresTable table_
ZoneSet< OpIndex > * eliminable_stores_ = nullptr
ZoneMap< OpIndex, uint64_t > * mergeable_store_pairs_ = nullptr
OpIndex last_field_initialization_store_ = OpIndex::Invalid()
Detailed Description
Definition at line 280 of file store-store-elimination-reducer-inl.h.
Constructor & Destructor Documentation
RedundantStoreAnalysis()
v8::internal::compiler::turboshaft::RedundantStoreAnalysis::RedundantStoreAnalysis (const Graph & graph, Zone * phase_zone) [inline]
Definition at line 282 of file store-store-elimination-reducer-inl.h.
      : graph_(graph), table_(graph, phase_zone) {}
Member Function Documentation
ProcessBlock()
void v8::internal::compiler::turboshaft::RedundantStoreAnalysis::ProcessBlock (const Block & block) [inline]
Definition at line 313 of file store-store-elimination-reducer-inl.h.
                                        {
    table_.BeginBlock(&block);
    auto op_range = graph_.OperationIndices(block);
    for (auto it = op_range.end(); it != op_range.begin();) {
      --it;
      OpIndex index = *it;
      const Operation& op = graph_.Get(index);
      switch (op.opcode) {
        case Opcode::kStore: {
          const StoreOp& store = op.Cast<StoreOp>();
          // TODO(nicohartmann@): Use the new effect flags to distinguish heap
          // access once available.
          const bool is_on_heap_store = store.kind.tagged_base;
          const bool is_fixed_offset_store = !store.index().valid();
          const uint8_t size = store.stored_rep.SizeInBytes();
          // For now we consider only stores of fixed offsets of objects on the
          // heap.
          if (is_on_heap_store && is_fixed_offset_store) {
            bool is_eliminable_store = false;
            switch (table_.GetObservability(store.base(), store.offset, size)) {
              case StoreObservability::kUnobservable:
                eliminable_stores_->insert(index);
                last_field_initialization_store_ = OpIndex::Invalid();
                is_eliminable_store = true;
                break;
              case StoreObservability::kGCObservable:
                if (store.maybe_initializing_or_transitioning) {
                  // We cannot eliminate this store, but we mark all following
                  // stores to the same `base+offset` as unobservable.
                  table_.MarkStoreAsUnobservable(store.base(), store.offset,
                                                 size);
                } else {
                  eliminable_stores_->insert(index);
                  last_field_initialization_store_ = OpIndex::Invalid();
                  is_eliminable_store = true;
                }
                break;
              case StoreObservability::kObservable:
                // We cannot eliminate this store, but we mark all following
                // stores to the same `base+offset` as unobservable.
                table_.MarkStoreAsUnobservable(store.base(), store.offset,
                                               size);
                break;
            }
            // Try to merge 2 consecutive 32-bit stores into a single 64-bit
            // one.
            if (COMPRESS_POINTERS_BOOL && !is_eliminable_store &&
                store.maybe_initializing_or_transitioning &&
                store.kind == StoreOp::Kind::TaggedBase() &&
                store.write_barrier == WriteBarrierKind::kNoWriteBarrier &&
                store.stored_rep.IsCompressibleTagged()) {
              if (last_field_initialization_store_.valid() &&
                  graph_.NextIndex(index) == last_field_initialization_store_) {
                const StoreOp& store0 = store;
                const StoreOp& store1 =
                    graph_.Get(last_field_initialization_store_)
                        .Cast<StoreOp>();
                DCHECK(!store0.index().valid());
                DCHECK(!store1.index().valid());
                const ConstantOp* c0 =
                    graph_.Get(store0.value()).TryCast<ConstantOp>();
                const ConstantOp* c1 =
                    graph_.Get(store1.value()).TryCast<ConstantOp>();
                // TODO(dmercadier): for now, we only apply this optimization
                // when storing read-only values, because otherwise the GC will
                // lose track of Handles when we convert them to a raw Word64.
                // However, if we were to keep the reloc info up-to-date, then
                // this might work for any object. To do this, we might need to
                // delay this optimization to later (instruction selector for
                // instance).
                if (c0 && c1 && c0->kind == ConstantOp::Kind::kHeapObject &&
                    c1->kind == ConstantOp::Kind::kHeapObject &&
                    store1.offset - store0.offset == 4 &&
                    HeapLayout::InReadOnlySpace(*c0->handle()) &&
                    HeapLayout::InReadOnlySpace(*c1->handle())) {
                  uint32_t high = static_cast<uint32_t>(c1->handle()->ptr());
                  uint32_t low = static_cast<uint32_t>(c0->handle()->ptr());
#if V8_TARGET_BIG_ENDIAN
                  uint64_t merged = make_uint64(low, high);
#else
                  uint64_t merged = make_uint64(high, low);
#endif
                  mergeable_store_pairs_->insert({index, merged});
                  eliminable_stores_->insert(last_field_initialization_store_);
                  last_field_initialization_store_ = OpIndex::Invalid();
                }
              } else {
                last_field_initialization_store_ = index;
              }
            }
          }
          break;
        }
        case Opcode::kLoad: {
          const LoadOp& load = op.Cast<LoadOp>();
          // TODO(nicohartmann@): Use the new effect flags to distinguish heap
          // access once available.
          const bool is_on_heap_load = load.kind.tagged_base;
          const bool is_fixed_offset_load = !load.index().valid();
          // For now we consider only loads of fields of objects on the heap.
          if (is_on_heap_load) {
            if (is_fixed_offset_load) {
              table_.MarkPotentiallyAliasingStoresAsObservable(load.base(),
                                                               load.offset);
            } else {
              // A dynamically indexed load might alias any fixed offset.
              table_.MarkAllStoresAsObservable();
            }
          }
          break;
        }
        default: {
          OpEffects effects = op.Effects();
          if (effects.can_read_mutable_memory()) {
            table_.MarkAllStoresAsObservable();
          } else if (effects.requires_consistent_heap()) {
            table_.MarkAllStoresAsGCObservable();
          }
        } break;
      }
    }
  }
References v8::internal::compiler::turboshaft::LoadOp::base(), v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::BeginBlock(), v8::internal::compiler::turboshaft::OpEffects::can_read_mutable_memory(), v8::internal::compiler::turboshaft::Operation::Cast(), COMPRESS_POINTERS_BOOL, v8::internal::DCHECK(), v8::internal::compiler::turboshaft::Operation::Effects(), eliminable_stores_, v8::internal::compiler::turboshaft::Graph::Get(), v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::GetObservability(), graph_, v8::internal::compiler::turboshaft::ConstantOp::handle(), v8::internal::compiler::turboshaft::LoadOp::index(), v8::internal::compiler::turboshaft::StoreOp::index(), v8::internal::index, v8::internal::HeapLayout::InReadOnlySpace(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::turboshaft::kGCObservable, v8::internal::compiler::turboshaft::ConstantOp::kHeapObject, v8::internal::compiler::turboshaft::ConstantOp::kind, v8::internal::compiler::turboshaft::LoadOp::kind, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::turboshaft::kObservable, v8::internal::compiler::turboshaft::kUnobservable, last_field_initialization_store_, make_uint64(), v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::MarkAllStoresAsGCObservable(), v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::MarkAllStoresAsObservable(), v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::MarkPotentiallyAliasingStoresAsObservable(), v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::MarkStoreAsUnobservable(), mergeable_store_pairs_, v8::internal::compiler::turboshaft::Graph::NextIndex(), v8::internal::compiler::turboshaft::LoadOp::offset, v8::internal::compiler::turboshaft::StoreOp::offset, v8::internal::compiler::turboshaft::Operation::opcode, v8::internal::compiler::turboshaft::Graph::OperationIndices(), v8::internal::compiler::turboshaft::OpEffects::requires_consistent_heap(), size(), store(), table_, v8::internal::compiler::turboshaft::LoadOp::Kind::tagged_base, v8::internal::compiler::turboshaft::LoadOp::Kind::TaggedBase(), v8::internal::compiler::turboshaft::Operation::TryCast(), v8::internal::compiler::turboshaft::OpIndex::valid(), v8::internal::compiler::turboshaft::OptionalOpIndex::valid(), and v8::internal::compiler::turboshaft::StoreOp::value().
Referenced by Run().
Run()
void v8::internal::compiler::turboshaft::RedundantStoreAnalysis::Run (ZoneSet< OpIndex > & eliminable_stores, ZoneMap< OpIndex, uint64_t > & mergeable_store_pairs) [inline]
Definition at line 285 of file store-store-elimination-reducer-inl.h.
                                                              {
    eliminable_stores_ = &eliminable_stores;
    mergeable_store_pairs_ = &mergeable_store_pairs;
    for (uint32_t processed = graph_.block_count(); processed > 0;
         --processed) {
      BlockIndex block_index = static_cast<BlockIndex>(processed - 1);
      const Block& block = graph_.Get(block_index);
      ProcessBlock(block);
      // If this block is a loop header, check if this loop needs to be
      // revisited.
      if (block.IsLoop()) {
        DCHECK(!table_.IsSealed());
        bool needs_revisit = false;
        table_.Seal(&needs_revisit);
        if (needs_revisit) {
          Block* back_edge = block.LastPredecessor();
          DCHECK_GE(back_edge->index(), block_index);
          processed = back_edge->index().id() + 1;
        }
      }
    }
    eliminable_stores_ = nullptr;
    mergeable_store_pairs_ = nullptr;
  }
References v8::internal::compiler::turboshaft::Graph::block_count(), v8::internal::DCHECK(), DCHECK_GE, eliminable_stores_, v8::internal::compiler::turboshaft::Graph::Get(), graph_, v8::internal::compiler::turboshaft::BlockIndex::id(), v8::internal::compiler::turboshaft::Block::index(), v8::internal::compiler::turboshaft::Block::IsLoop(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::IsSealed(), v8::internal::compiler::turboshaft::Block::LastPredecessor(), mergeable_store_pairs_, ProcessBlock(), v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::Seal(), and table_.
Referenced by v8::internal::compiler::turboshaft::StoreStoreEliminationReducer< Next >::Analyze().
Member Data Documentation
eliminable_stores_
ZoneSet<OpIndex>* v8::internal::compiler::turboshaft::RedundantStoreAnalysis::eliminable_stores_ = nullptr [private]
Definition at line 447 of file store-store-elimination-reducer-inl.h.
Referenced by ProcessBlock(), and Run().
graph_
const Graph& v8::internal::compiler::turboshaft::RedundantStoreAnalysis::graph_ [private]
Definition at line 445 of file store-store-elimination-reducer-inl.h.
Referenced by ProcessBlock(), and Run().
last_field_initialization_store_
OpIndex v8::internal::compiler::turboshaft::RedundantStoreAnalysis::last_field_initialization_store_ = OpIndex::Invalid() [private]
Definition at line 450 of file store-store-elimination-reducer-inl.h.
Referenced by ProcessBlock().
mergeable_store_pairs_
ZoneMap<OpIndex, uint64_t>* v8::internal::compiler::turboshaft::RedundantStoreAnalysis::mergeable_store_pairs_ = nullptr [private]
Definition at line 449 of file store-store-elimination-reducer-inl.h.
Referenced by ProcessBlock(), and Run().
table_
MaybeRedundantStoresTable v8::internal::compiler::turboshaft::RedundantStoreAnalysis::table_ [private]
Definition at line 446 of file store-store-elimination-reducer-inl.h.
Referenced by ProcessBlock(), and Run().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/store-store-elimination-reducer-inl.h