v8::internal::interpreter::TryCatchBuilder Class Reference
#include <control-flow-builders.h>
Public Member Functions
TryCatchBuilder (BytecodeArrayBuilder *builder, BlockCoverageBuilder *block_coverage_builder, TryCatchStatement *statement, HandlerTable::CatchPrediction catch_prediction)
~TryCatchBuilder () override
void BeginTry (Register context)
void EndTry ()
void EndCatch ()
Private Attributes
int handler_id_
HandlerTable::CatchPrediction catch_prediction_
BytecodeLabel exit_
BlockCoverageBuilder * block_coverage_builder_
TryCatchStatement * statement_
Additional Inherited Members
Detailed Description
Definition at line 202 of file control-flow-builders.h.
Constructor & Destructor Documentation
TryCatchBuilder()
v8::internal::interpreter::TryCatchBuilder::TryCatchBuilder (BytecodeArrayBuilder * builder, BlockCoverageBuilder * block_coverage_builder, TryCatchStatement * statement, HandlerTable::CatchPrediction catch_prediction) [inline]
Definition at line 204 of file control-flow-builders.h.
      : ControlFlowBuilder(builder),
        handler_id_(builder->NewHandlerEntry()),
        catch_prediction_(catch_prediction),
        block_coverage_builder_(block_coverage_builder),
        statement_(statement) {}
 TryCatchBuilder()
v8::internal::interpreter::TryCatchBuilder::~TryCatchBuilder () [override]
Definition at line 148 of file control-flow-builders.cc.
                                  {
  if (block_coverage_builder_ != nullptr) {
    block_coverage_builder_->IncrementBlockCounter(
        statement_, SourceRangeKind::kContinuation);
  }
}
References block_coverage_builder_, v8::internal::interpreter::BlockCoverageBuilder::IncrementBlockCounter(), v8::internal::kContinuation, and statement_.
Member Function Documentation
BeginTry()
void v8::internal::interpreter::TryCatchBuilder::BeginTry (Register context)
Definition at line 155 of file control-flow-builders.cc.
                                               {
  builder()->MarkTryBegin(handler_id_, context);
}
References v8::internal::interpreter::ControlFlowBuilder::builder(), handler_id_, and v8::internal::interpreter::BytecodeArrayBuilder::MarkTryBegin().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildTryCatch().
EndCatch()
void v8::internal::interpreter::TryCatchBuilder::EndCatch ()
Definition at line 171 of file control-flow-builders.cc.
{ builder()->Bind(&exit_); }
References v8::internal::interpreter::BytecodeArrayBuilder::Bind(), v8::internal::interpreter::ControlFlowBuilder::builder(), and exit_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildTryCatch().
EndTry()
void v8::internal::interpreter::TryCatchBuilder::EndTry ()
Definition at line 160 of file control-flow-builders.cc.
                             {
  builder()->MarkTryEnd(handler_id_);
  builder()->Jump(&exit_);
  builder()->MarkHandler(handler_id_, catch_prediction_);
  if (block_coverage_builder_ != nullptr) {
    block_coverage_builder_->IncrementBlockCounter(statement_,
                                                   SourceRangeKind::kCatch);
  }
}
References block_coverage_builder_, v8::internal::interpreter::ControlFlowBuilder::builder(), catch_prediction_, exit_, handler_id_, v8::internal::interpreter::BlockCoverageBuilder::IncrementBlockCounter(), v8::internal::interpreter::BytecodeArrayBuilder::Jump(), v8::internal::kCatch, v8::internal::interpreter::BytecodeArrayBuilder::MarkHandler(), v8::internal::interpreter::BytecodeArrayBuilder::MarkTryEnd(), and statement_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildTryCatch().
Member Data Documentation
block_coverage_builder_
BlockCoverageBuilder* v8::internal::interpreter::TryCatchBuilder::block_coverage_builder_ [private]
Definition at line 225 of file control-flow-builders.h.
Referenced by EndTry(), and ~TryCatchBuilder().
catch_prediction_
HandlerTable::CatchPrediction v8::internal::interpreter::TryCatchBuilder::catch_prediction_ [private]
Definition at line 222 of file control-flow-builders.h.
Referenced by EndTry().
exit_
BytecodeLabel v8::internal::interpreter::TryCatchBuilder::exit_ [private]
Definition at line 223 of file control-flow-builders.h.
Referenced by EndCatch(), and EndTry().
handler_id_
int v8::internal::interpreter::TryCatchBuilder::handler_id_ [private]
Definition at line 221 of file control-flow-builders.h.
Referenced by BeginTry(), and EndTry().
statement_
TryCatchStatement* v8::internal::interpreter::TryCatchBuilder::statement_ [private]
Definition at line 226 of file control-flow-builders.h.
Referenced by EndTry(), and ~TryCatchBuilder().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/interpreter/control-flow-builders.h
/mnt/V8SourceCode/src/interpreter/control-flow-builders.cc