v8::internal::HeapObjectsMap Class Reference
#include <heap-snapshot-generator.h>
Classes
struct EntryInfo
struct TimeInterval
Public Types
enum class MarkEntryAccessed { kNo
, kYes
 }
enum class IsNativeObject { kNo
, kYes
 }
Public Member Functions
HeapObjectsMap (Heap *heap)
HeapObjectsMap (const HeapObjectsMap &)=delete
HeapObjectsMap & operator= (const HeapObjectsMap &)=delete
Heap * heap () const
SnapshotObjectId FindEntry (Address addr)
SnapshotObjectId FindOrAddEntry (Address addr, unsigned int size, MarkEntryAccessed accessed=MarkEntryAccessed::kYes, IsNativeObject is_native_object=IsNativeObject::kNo)
SnapshotObjectId FindMergedNativeEntry (NativeObject addr)
void AddMergedNativeEntry (NativeObject addr, Address canonical_addr)
bool MoveObject (Address from, Address to, int size)
void UpdateObjectSize (Address addr, int size)
SnapshotObjectId last_assigned_id () const
SnapshotObjectId get_next_id ()
SnapshotObjectId get_next_native_id ()
void StopHeapObjectsTracking ()
SnapshotObjectId PushHeapObjectsStats (OutputStream *stream, int64_t *timestamp_us)
const std::vector< TimeInterval > & samples () const
void UpdateHeapObjectsMap ()
void RemoveDeadEntries ()
Static Public Attributes
static const int kObjectIdStep = 2
static const SnapshotObjectId kInternalRootObjectId = 1
static const SnapshotObjectId kGcRootsObjectId
static const SnapshotObjectId kGcRootsFirstSubrootId
static const SnapshotObjectId kFirstAvailableObjectId
static const SnapshotObjectId kFirstAvailableNativeId = 2
Private Attributes
SnapshotObjectId next_id_
SnapshotObjectId next_native_id_
base::HashMap entries_map_
std::vector< EntryInfo > entries_
std::vector< TimeInterval > time_intervals_
std::unordered_map< NativeObject, size_t > merged_native_entries_map_
Heap * heap_
Detailed Description
Definition at line 308 of file heap-snapshot-generator.h.
Member Enumeration Documentation
IsNativeObject
enum v8::internal::HeapObjectsMap::IsNativeObject [strong]
Enumerator
kNo
kYes
Definition at line 323 of file heap-snapshot-generator.h.
                            {
    kNo,
    kYes,
  };
MarkEntryAccessed
enum v8::internal::HeapObjectsMap::MarkEntryAccessed [strong]
Enumerator
kNo
kYes
Definition at line 319 of file heap-snapshot-generator.h.
                               {
    kNo,
    kYes,
  };
Constructor & Destructor Documentation
HeapObjectsMap() [1/2]
v8::internal::HeapObjectsMap::HeapObjectsMap (Heap * heap) [explicit]
Definition at line 578 of file heap-snapshot-generator.cc.
    : next_id_(kFirstAvailableObjectId),
      next_native_id_(kFirstAvailableNativeId),
      heap_(heap) {
  // The dummy element at zero index is needed as entries_map_ cannot hold
  // an entry with zero value. Otherwise it's impossible to tell if
  // LookupOrInsert has added a new item or just returning exisiting one
  // having the value of zero.
  entries_.emplace_back(0, kNullAddress, 0, true);
}
References entries_, and v8::internal::kNullAddress.
HeapObjectsMap() [2/2]
v8::internal::HeapObjectsMap::HeapObjectsMap (const HeapObjectsMap &) [delete]
Member Function Documentation
AddMergedNativeEntry()
void v8::internal::HeapObjectsMap::AddMergedNativeEntry (NativeObject addr, Address canonical_addr)
Definition at line 686 of file heap-snapshot-generator.cc.
                                                                  {
  base::HashMap::Entry* entry =
      entries_map_.Lookup(reinterpret_cast<void*>(canonical_addr),
                          ComputeAddressHash(canonical_addr));
  auto result = merged_native_entries_map_.insert(
      {addr, reinterpret_cast<size_t>(entry->value)});
  if (!result.second) {
    result.first->second = reinterpret_cast<size_t>(entry->value);
  }
}
References v8::internal::ComputeAddressHash(), entries_map_, merged_native_entries_map_, and v8::base::internal::result.
Referenced by v8::internal::NativeObjectsExplorer::MergeNodeIntoEntry().
FindEntry()
SnapshotObjectId v8::internal::HeapObjectsMap::FindEntry (Address addr)
Definition at line 640 of file heap-snapshot-generator.cc.
                                                       {
  base::HashMap::Entry* entry = entries_map_.Lookup(
      reinterpret_cast<void*>(addr), ComputeAddressHash(addr));
  if (entry == nullptr) return v8::HeapProfiler::kUnknownObjectId;
  int entry_index = static_cast<int>(reinterpret_cast<intptr_t>(entry->value));
  EntryInfo& entry_info = entries_.at(entry_index);
  DCHECK(static_cast<uint32_t>(entries_.size()) > entries_map_.occupancy());
  return entry_info.id;
}
References v8::internal::ComputeAddressHash(), v8::internal::DCHECK(), entries_, entries_map_, v8::internal::HeapObjectsMap::EntryInfo::id, and v8::HeapProfiler::kUnknownObjectId.
FindMergedNativeEntry()
SnapshotObjectId v8::internal::HeapObjectsMap::FindMergedNativeEntry (NativeObject addr)
Definition at line 679 of file heap-snapshot-generator.cc.
                                                                        {
  auto it = merged_native_entries_map_.find(addr);
  if (it == merged_native_entries_map_.end())
    return v8::HeapProfiler::kUnknownObjectId;
  return entries_[it->second].id;
}
References entries_, v8::HeapProfiler::kUnknownObjectId, and merged_native_entries_map_.
Referenced by v8::internal::NativeObjectsExplorer::MergeNodeIntoEntry().
FindOrAddEntry()
SnapshotObjectId v8::internal::HeapObjectsMap::FindOrAddEntry (Address addr, unsigned int size, MarkEntryAccessed accessed = MarkEntryAccessed::kYes, IsNativeObject is_native_object = IsNativeObject::kNo)
Definition at line 650 of file heap-snapshot-generator.cc.
                                     {
  bool accessed_bool = accessed == MarkEntryAccessed::kYes;
  bool is_native_object_bool = is_native_object == IsNativeObject::kYes;
  DCHECK(static_cast<uint32_t>(entries_.size()) > entries_map_.occupancy());
  base::HashMap::Entry* entry = entries_map_.LookupOrInsert(
      reinterpret_cast<void*>(addr), ComputeAddressHash(addr));
  if (entry->value != nullptr) {
    int entry_index =
        static_cast<int>(reinterpret_cast<intptr_t>(entry->value));
    EntryInfo& entry_info = entries_.at(entry_index);
    entry_info.accessed = accessed_bool;
    if (v8_flags.heap_profiler_trace_objects) {
      PrintF("Update object size : %p with old size %d and new size %d\n",
             reinterpret_cast<void*>(addr), entry_info.size, size);
    }
    entry_info.size = size;
    DCHECK_EQ(is_native_object_bool, entry_info.id % 2 == 0);
    return entry_info.id;
  }
  entry->value = reinterpret_cast<void*>(entries_.size());
  SnapshotObjectId id =
      is_native_object_bool ? get_next_native_id() : get_next_id();
  entries_.push_back(EntryInfo(id, addr, size, accessed_bool));
  DCHECK(static_cast<uint32_t>(entries_.size()) > entries_map_.occupancy());
  return id;
}
References v8::internal::HeapObjectsMap::EntryInfo::accessed, v8::internal::ComputeAddressHash(), v8::internal::DCHECK(), DCHECK_EQ, entries_, entries_map_, get_next_id(), get_next_native_id(), v8::internal::HeapObjectsMap::EntryInfo::id, kYes, v8::internal::PrintF(), size(), v8::internal::HeapObjectsMap::EntryInfo::size, and v8::internal::v8_flags.
Referenced by v8::internal::V8HeapExplorer::AddEntry(), v8::internal::EmbedderGraphEntriesAllocator::AllocateEntry(), v8::internal::AllocationTracker::AllocationEvent(), UpdateHeapObjectsMap(), and UpdateObjectSize().
get_next_id()
SnapshotObjectId v8::internal::HeapObjectsMap::get_next_id () [inline]
Definition at line 346 of file heap-snapshot-generator.h.
                                 {
    next_id_ += kObjectIdStep;
    return next_id_ - kObjectIdStep;
  }
References kObjectIdStep, and next_id_.
Referenced by v8::internal::V8HeapExplorer::AllocateEntry(), v8::internal::V8HeapExplorer::ExtractNumberReference(), and FindOrAddEntry().
get_next_native_id()
SnapshotObjectId v8::internal::HeapObjectsMap::get_next_native_id () [inline]
Definition at line 350 of file heap-snapshot-generator.h.
                                        {
    next_native_id_ += kObjectIdStep;
    return next_native_id_ - kObjectIdStep;
  }
References kObjectIdStep, and next_native_id_.
Referenced by FindOrAddEntry().
heap()
Heap* v8::internal::HeapObjectsMap::heap () const [inline]
Definition at line 332 of file heap-snapshot-generator.h.
{ return heap_; }
References heap_.
Referenced by v8::internal::AllocationTracker::AllocationEvent().
last_assigned_id()
SnapshotObjectId v8::internal::HeapObjectsMap::last_assigned_id () const [inline]
Definition at line 343 of file heap-snapshot-generator.h.
                                            {
    return next_id_ - kObjectIdStep;
  }
References kObjectIdStep, and next_id_.
Referenced by PushHeapObjectsStats(), and v8::internal::HeapSnapshot::RememberLastJSObjectId().
MoveObject()
bool v8::internal::HeapObjectsMap::MoveObject (Address from, Address to, int size)
Definition at line 589 of file heap-snapshot-generator.cc.
                                                                         {
  DCHECK_NE(kNullAddress, to);
  DCHECK_NE(kNullAddress, from);
  if (from == to) return false;
  void* from_value = entries_map_.Remove(reinterpret_cast<void*>(from),
                                         ComputeAddressHash(from));
  if (from_value == nullptr) {
    // It may occur that some untracked object moves to an address X and there
    // is a tracked object at that address. In this case we should remove the
    // entry as we know that the object has died.
    void* to_value = entries_map_.Remove(reinterpret_cast<void*>(to),
                                         ComputeAddressHash(to));
    if (to_value != nullptr) {
      int to_entry_info_index =
          static_cast<int>(reinterpret_cast<intptr_t>(to_value));
      entries_.at(to_entry_info_index).addr = kNullAddress;
    }
  } else {
    base::HashMap::Entry* to_entry = entries_map_.LookupOrInsert(
        reinterpret_cast<void*>(to), ComputeAddressHash(to));
    if (to_entry->value != nullptr) {
      // We found the existing entry with to address for an old object.
      // Without this operation we will have two EntryInfo's with the same
      // value in addr field. It is bad because later at RemoveDeadEntries
      // one of this entry will be removed with the corresponding entries_map_
      // entry.
      int to_entry_info_index =
          static_cast<int>(reinterpret_cast<intptr_t>(to_entry->value));
      entries_.at(to_entry_info_index).addr = kNullAddress;
    }
    int from_entry_info_index =
        static_cast<int>(reinterpret_cast<intptr_t>(from_value));
    entries_.at(from_entry_info_index).addr = to;
    // Size of an object can change during its life, so to keep information
    // about the object in entries_ consistent, we have to adjust size when the
    // object is migrated.
    if (v8_flags.heap_profiler_trace_objects) {
      PrintF("Move object from %p to %p old size %6d new size %6d\n",
             reinterpret_cast<void*>(from), reinterpret_cast<void*>(to),
             entries_.at(from_entry_info_index).size, object_size);
    }
    entries_.at(from_entry_info_index).size = object_size;
    to_entry->value = from_value;
  }
  return from_value != nullptr;
}
References v8::internal::ComputeAddressHash(), DCHECK_NE, entries_, entries_map_, v8::internal::kNullAddress, v8::internal::PrintF(), v8::internal::wasm::to_value(), and v8::internal::v8_flags.
operator=()
HeapObjectsMap& v8::internal::HeapObjectsMap::operator= (const HeapObjectsMap &) [delete]
PushHeapObjectsStats()
SnapshotObjectId v8::internal::HeapObjectsMap::PushHeapObjectsStats (OutputStream * stream, int64_t * timestamp_us)
Definition at line 726 of file heap-snapshot-generator.cc.
                                                                             {
  UpdateHeapObjectsMap();
  time_intervals_.emplace_back(next_id_);
  int prefered_chunk_size = stream->GetChunkSize();
  std::vector<v8::HeapStatsUpdate> stats_buffer;
  DCHECK(!entries_.empty());
  EntryInfo* entry_info = &entries_.front();
  EntryInfo* end_entry_info = &entries_.back() + 1;
  for (size_t time_interval_index = 0;
       time_interval_index < time_intervals_.size(); ++time_interval_index) {
    TimeInterval& time_interval = time_intervals_[time_interval_index];
    SnapshotObjectId time_interval_id = time_interval.id;
    uint32_t entries_size = 0;
    EntryInfo* start_entry_info = entry_info;
    while (entry_info < end_entry_info && entry_info->id < time_interval_id) {
      entries_size += entry_info->size;
      ++entry_info;
    }
    uint32_t entries_count =
        static_cast<uint32_t>(entry_info - start_entry_info);
    if (time_interval.count != entries_count ||
        time_interval.size != entries_size) {
      stats_buffer.emplace_back(static_cast<uint32_t>(time_interval_index),
                                time_interval.count = entries_count,
                                time_interval.size = entries_size);
      if (static_cast<int>(stats_buffer.size()) >= prefered_chunk_size) {
        OutputStream::WriteResult result = stream->WriteHeapStatsChunk(
            &stats_buffer.front(), static_cast<int>(stats_buffer.size()));
        if (result == OutputStream::kAbort) return last_assigned_id();
        stats_buffer.clear();
      }
    }
  }
  DCHECK(entry_info == end_entry_info);
  if (!stats_buffer.empty()) {
    OutputStream::WriteResult result = stream->WriteHeapStatsChunk(
        &stats_buffer.front(), static_cast<int>(stats_buffer.size()));
    if (result == OutputStream::kAbort) return last_assigned_id();
  }
  stream->EndOfStream();
  if (timestamp_us) {
    *timestamp_us =
        (time_intervals_.back().timestamp - time_intervals_.front().timestamp)
            .InMicroseconds();
  }
  return last_assigned_id();
}
References v8::internal::HeapObjectsMap::TimeInterval::count, v8::internal::DCHECK(), v8::OutputStream::EndOfStream(), entries_, v8::OutputStream::GetChunkSize(), v8::internal::HeapObjectsMap::TimeInterval::id, v8::OutputStream::kAbort, last_assigned_id(), next_id_, v8::base::internal::result, v8::internal::HeapObjectsMap::TimeInterval::size, v8::internal::HeapObjectsMap::EntryInfo::size, time_intervals_, UpdateHeapObjectsMap(), and v8::OutputStream::WriteHeapStatsChunk().
RemoveDeadEntries()
void v8::internal::HeapObjectsMap::RemoveDeadEntries ()
Definition at line 775 of file heap-snapshot-generator.cc.
                                       {
  DCHECK(entries_.size() > 0 && entries_.at(0).id == 0 &&
         entries_.at(0).addr == kNullAddress);
  // Build up temporary reverse map.
  std::unordered_map<size_t, NativeObject> reverse_merged_native_entries_map;
  for (const auto& it : merged_native_entries_map_) {
    auto result =
        reverse_merged_native_entries_map.emplace(it.second, it.first);
    DCHECK(result.second);
    USE(result);
  }
  size_t first_free_entry = 1;
  for (size_t i = 1; i < entries_.size(); ++i) {
    EntryInfo& entry_info = entries_.at(i);
    auto merged_reverse_it = reverse_merged_native_entries_map.find(i);
    if (entry_info.accessed) {
      if (first_free_entry != i) {
        entries_.at(first_free_entry) = entry_info;
      }
      entries_.at(first_free_entry).accessed = false;
      base::HashMap::Entry* entry =
          entries_map_.Lookup(reinterpret_cast<void*>(entry_info.addr),
                              ComputeAddressHash(entry_info.addr));
      DCHECK(entry);
      entry->value = reinterpret_cast<void*>(first_free_entry);
      if (merged_reverse_it != reverse_merged_native_entries_map.end()) {
        auto it = merged_native_entries_map_.find(merged_reverse_it->second);
        DCHECK_NE(merged_native_entries_map_.end(), it);
        it->second = first_free_entry;
      }
      ++first_free_entry;
    } else {
      if (entry_info.addr) {
        entries_map_.Remove(reinterpret_cast<void*>(entry_info.addr),
                            ComputeAddressHash(entry_info.addr));
        if (merged_reverse_it != reverse_merged_native_entries_map.end()) {
          merged_native_entries_map_.erase(merged_reverse_it->second);
        }
      }
    }
  }
  entries_.erase(entries_.begin() + first_free_entry, entries_.end());
  DCHECK(static_cast<uint32_t>(entries_.size()) - 1 ==
         entries_map_.occupancy());
}
References v8::internal::HeapObjectsMap::EntryInfo::accessed, v8::internal::HeapObjectsMap::EntryInfo::addr, v8::internal::ComputeAddressHash(), v8::internal::DCHECK(), DCHECK_NE, entries_, entries_map_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kNullAddress, merged_native_entries_map_, v8::base::internal::result, and USE.
Referenced by UpdateHeapObjectsMap().
samples()
const std::vector<TimeInterval>& v8::internal::HeapObjectsMap::samples () const [inline]
Definition at line 358 of file heap-snapshot-generator.h.
{ return time_intervals_; }
References time_intervals_.
Referenced by v8::internal::HeapSnapshotJSONSerializer::SerializeSamples().
StopHeapObjectsTracking()
void v8::internal::HeapObjectsMap::StopHeapObjectsTracking ()
Definition at line 698 of file heap-snapshot-generator.cc.
{ time_intervals_.clear(); }
References time_intervals_.
UpdateHeapObjectsMap()
void v8::internal::HeapObjectsMap::UpdateHeapObjectsMap ()
Definition at line 700 of file heap-snapshot-generator.cc.
                                          {
  if (v8_flags.heap_profiler_trace_objects) {
    PrintF("Begin HeapObjectsMap::UpdateHeapObjectsMap. map has %d entries.\n",
           entries_map_.occupancy());
  }
  heap_->PreciseCollectAllGarbage(GCFlag::kNoFlags,
                                  GarbageCollectionReason::kHeapProfiler);
  PtrComprCageBase cage_base(heap_->isolate());
  CombinedHeapObjectIterator iterator(heap_);
  for (Tagged<HeapObject> obj = iterator.Next(); !obj.is_null();
       obj = iterator.Next()) {
    FindOrAddEntry(obj.address(), SizeForSnapshot(obj, cage_base));
    if (v8_flags.heap_profiler_trace_objects) {
      int object_size = obj->Size(cage_base);
      PrintF("Update object : %p %6d. Next address is %p\n",
             reinterpret_cast<void*>(obj.address()), object_size,
             reinterpret_cast<void*>(obj.address() + object_size));
    }
  }
  RemoveDeadEntries();
  if (v8_flags.heap_profiler_trace_objects) {
    PrintF("End HeapObjectsMap::UpdateHeapObjectsMap. map has %d entries.\n",
           entries_map_.occupancy());
  }
}
References entries_map_, FindOrAddEntry(), heap_, v8::internal::Tagged< HeapObject >::is_null(), v8::internal::Heap::isolate(), v8::internal::kHeapProfiler, v8::internal::kNoFlags, v8::internal::CombinedHeapObjectIterator::Next(), v8::internal::Heap::PreciseCollectAllGarbage(), v8::internal::PrintF(), RemoveDeadEntries(), v8::internal::anonymous_namespace{heap-snapshot-generator.cc}::SizeForSnapshot(), and v8::internal::v8_flags.
Referenced by PushHeapObjectsStats().
UpdateObjectSize()
void v8::internal::HeapObjectsMap::UpdateObjectSize (Address addr, int size)
Definition at line 636 of file heap-snapshot-generator.cc.
                                                            {
  FindOrAddEntry(addr, size, MarkEntryAccessed::kNo);
}
References FindOrAddEntry(), kNo, and size().
Member Data Documentation
entries_
std::vector<EntryInfo> v8::internal::HeapObjectsMap::entries_ [private]
Definition at line 385 of file heap-snapshot-generator.h.
Referenced by FindEntry(), FindMergedNativeEntry(), FindOrAddEntry(), HeapObjectsMap(), MoveObject(), PushHeapObjectsStats(), and RemoveDeadEntries().
entries_map_
base::HashMap v8::internal::HeapObjectsMap::entries_map_ [private]
Definition at line 384 of file heap-snapshot-generator.h.
Referenced by AddMergedNativeEntry(), FindEntry(), FindOrAddEntry(), MoveObject(), RemoveDeadEntries(), and UpdateHeapObjectsMap().
heap_
Heap* v8::internal::HeapObjectsMap::heap_ [private]
Definition at line 389 of file heap-snapshot-generator.h.
Referenced by heap(), and UpdateHeapObjectsMap().
kFirstAvailableNativeId
const SnapshotObjectId v8::internal::HeapObjectsMap::kFirstAvailableNativeId = 2 [static]
Definition at line 365 of file heap-snapshot-generator.h.
kFirstAvailableObjectId
const SnapshotObjectId v8::internal::HeapObjectsMap::kFirstAvailableObjectId [static]
Initial value:
=
    HeapObjectsMap::kGcRootsFirstSubrootId +
    static_cast<int>(Root::kNumberOfRoots) * HeapObjectsMap::kObjectIdStep
Definition at line 364 of file heap-snapshot-generator.h.
Referenced by v8::internal::HeapSnapshot::AddSyntheticRootEntries().
kGcRootsFirstSubrootId
const SnapshotObjectId v8::internal::HeapObjectsMap::kGcRootsFirstSubrootId [static]
Initial value:
=
    HeapObjectsMap::kGcRootsObjectId + HeapObjectsMap::kObjectIdStep
Definition at line 363 of file heap-snapshot-generator.h.
Referenced by v8::internal::HeapSnapshot::AddSyntheticRootEntries().
kGcRootsObjectId
const SnapshotObjectId v8::internal::HeapObjectsMap::kGcRootsObjectId [static]
Initial value:
=
    HeapObjectsMap::kInternalRootObjectId + HeapObjectsMap::kObjectIdStep
Definition at line 362 of file heap-snapshot-generator.h.
Referenced by v8::internal::HeapSnapshot::AddGcRootsEntry().
kInternalRootObjectId
const SnapshotObjectId v8::internal::HeapObjectsMap::kInternalRootObjectId = 1 [static]
Definition at line 361 of file heap-snapshot-generator.h.
Referenced by v8::internal::HeapSnapshot::AddRootEntry().
kObjectIdStep
const int v8::internal::HeapObjectsMap::kObjectIdStep = 2 [static]
Definition at line 360 of file heap-snapshot-generator.h.
Referenced by v8::internal::HeapSnapshot::AddSyntheticRootEntries(), get_next_id(), get_next_native_id(), v8::internal::HeapObjectsMap::TimeInterval::last_assigned_id(), and last_assigned_id().
merged_native_entries_map_
std::unordered_map<NativeObject, size_t> v8::internal::HeapObjectsMap::merged_native_entries_map_ [private]
Definition at line 388 of file heap-snapshot-generator.h.
Referenced by AddMergedNativeEntry(), FindMergedNativeEntry(), and RemoveDeadEntries().
next_id_
SnapshotObjectId v8::internal::HeapObjectsMap::next_id_ [private]
Definition at line 381 of file heap-snapshot-generator.h.
Referenced by get_next_id(), last_assigned_id(), and PushHeapObjectsStats().
next_native_id_
SnapshotObjectId v8::internal::HeapObjectsMap::next_native_id_ [private]
Definition at line 382 of file heap-snapshot-generator.h.
Referenced by get_next_native_id().
time_intervals_
std::vector<TimeInterval> v8::internal::HeapObjectsMap::time_intervals_ [private]
Definition at line 386 of file heap-snapshot-generator.h.
Referenced by PushHeapObjectsStats(), samples(), and StopHeapObjectsTracking().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/profiler/heap-snapshot-generator.h
/mnt/V8SourceCode/src/profiler/heap-snapshot-generator.cc