v8::internal::CallPrinter Class Reference
#include <prettyprinter.h>
Public Types
enum class SpreadErrorInArgsHint { kErrorInArgs
, kNoErrorInArgs
 }
enum class ErrorHint {
kNone
, kNormalIterator
, kAsyncIterator
, kCallAndNormalIterator
,
kCallAndAsyncIterator
 }
Public Member Functions
CallPrinter (Isolate *isolate, bool is_user_js, SpreadErrorInArgsHint error_in_spread_args=SpreadErrorInArgsHint::kNoErrorInArgs)
~CallPrinter ()
DirectHandle< String > Print (FunctionLiteral *program, int position)
ErrorHint GetErrorHint () const
Expression * spread_arg () const
ObjectLiteralProperty * destructuring_prop () const
Assignment * destructuring_assignment () const
Protected Member Functions
void PrintLiteral (DirectHandle< Object > value, bool quote)
void PrintLiteral (const AstRawString *value, bool quote)
void FindStatements (const ZonePtrList< Statement > *statements)
void FindArguments (const ZonePtrList< Expression > *arguments)
Private Member Functions
void Print (char c)
void Print (const char *str)
void Print (DirectHandle< String > str)
void Find (AstNode *node, bool print=false)
DEFINE_AST_VISITOR_SUBCLASS_MEMBERS ()
Private Attributes
Isolate * isolate_
int num_prints_
IncrementalStringBuilder builder_
int position_
bool found_
bool done_
bool is_user_js_
bool is_iterator_error_
bool is_async_iterator_error_
bool is_call_error_
SpreadErrorInArgsHint error_in_spread_args_
ObjectLiteralProperty * destructuring_prop_
Assignment * destructuring_assignment_
Expression * spread_arg_
FunctionKind function_kind_
Detailed Description
Definition at line 17 of file prettyprinter.h.
Member Enumeration Documentation
ErrorHint
enum v8::internal::CallPrinter::ErrorHint [strong]
Enumerator
kNone
kNormalIterator
kAsyncIterator
kCallAndNormalIterator
kCallAndAsyncIterator
Definition at line 29 of file prettyprinter.h.
                       {
    kNone,
    kNormalIterator,
    kAsyncIterator,
    kCallAndNormalIterator,
    kCallAndAsyncIterator
  };
SpreadErrorInArgsHint
enum v8::internal::CallPrinter::SpreadErrorInArgsHint [strong]
Enumerator
kErrorInArgs
kNoErrorInArgs
Definition at line 19 of file prettyprinter.h.
{ kErrorInArgs, kNoErrorInArgs };
Constructor & Destructor Documentation
CallPrinter()
v8::internal::CallPrinter::CallPrinter (Isolate * isolate, bool is_user_js, SpreadErrorInArgsHint error_in_spread_args = SpreadErrorInArgsHint::kNoErrorInArgs) [explicit]
Definition at line 21 of file prettyprinter.cc.
    : builder_(isolate) {
  isolate_ = isolate;
  position_ = 0;
  num_prints_ = 0;
  found_ = false;
  done_ = false;
  is_call_error_ = false;
  is_iterator_error_ = false;
  is_async_iterator_error_ = false;
  destructuring_prop_ = nullptr;
  destructuring_assignment_ = nullptr;
  is_user_js_ = is_user_js;
  error_in_spread_args_ = error_in_spread_args;
  spread_arg_ = nullptr;
  function_kind_ = FunctionKind::kNormalFunction;
  InitializeAstVisitor(isolate);
}
References destructuring_assignment_, destructuring_prop_, done_, error_in_spread_args_, found_, function_kind_, is_async_iterator_error_, is_call_error_, is_iterator_error_, is_user_js_, isolate_, v8::internal::kNormalFunction, num_prints_, position_, and spread_arg_.
 CallPrinter()
v8::internal::CallPrinter::~CallPrinter () [default]
Member Function Documentation
DEFINE_AST_VISITOR_SUBCLASS_MEMBERS()
v8::internal::CallPrinter::DEFINE_AST_VISITOR_SUBCLASS_MEMBERS () [private]
destructuring_assignment()
Assignment* v8::internal::CallPrinter::destructuring_assignment () const [inline]
Definition at line 42 of file prettyprinter.h.
                                               {
    return destructuring_assignment_;
  }
References destructuring_assignment_.
Referenced by v8::internal::ErrorUtils::ThrowLoadFromNullOrUndefined().
destructuring_prop()
ObjectLiteralProperty* v8::internal::CallPrinter::destructuring_prop () const [inline]
Definition at line 39 of file prettyprinter.h.
                                                    {
    return destructuring_prop_;
  }
References destructuring_prop_.
Referenced by v8::internal::ErrorUtils::ThrowLoadFromNullOrUndefined().
Find()
void v8::internal::CallPrinter::Find (AstNode * node, bool print = false) [private]
Definition at line 62 of file prettyprinter.cc.
                                                {
  if (found_) {
    if (print) {
      int prev_num_prints = num_prints_;
      Visit(node);
      if (prev_num_prints != num_prints_) return;
    }
    Print("(intermediate value)");
  } else {
    Visit(node);
  }
}
References found_, num_prints_, Print(), and v8::internal::AstVisitor< CallPrinter >::Visit().
Referenced by FindArguments(), FindStatements(), and Print().
FindArguments()
void v8::internal::CallPrinter::FindArguments (const ZonePtrList< Expression > * arguments) [protected]
Definition at line 620 of file prettyprinter.cc.
                                                                        {
  if (found_) return;
  for (int i = 0; i < arguments->length(); i++) {
    Find(arguments->at(i));
  }
}
References v8::internal::ZoneList< T >::at(), Find(), found_, and v8::internal::ZoneList< T >::length().
FindStatements()
void v8::internal::CallPrinter::FindStatements (const ZonePtrList< Statement > * statements) [protected]
Definition at line 613 of file prettyprinter.cc.
                                                                         {
  if (statements == nullptr) return;
  for (int i = 0; i < statements->length(); i++) {
    Find(statements->at(i));
  }
}
References v8::internal::ZoneList< T >::at(), Find(), and v8::internal::ZoneList< T >::length().
GetErrorHint()
CallPrinter::ErrorHint v8::internal::CallPrinter::GetErrorHint () const
Definition at line 43 of file prettyprinter.cc.
                                                     {
  if (is_call_error_) {
    if (is_iterator_error_) return ErrorHint::kCallAndNormalIterator;
    if (is_async_iterator_error_) return ErrorHint::kCallAndAsyncIterator;
  } else {
    if (is_iterator_error_) return ErrorHint::kNormalIterator;
    if (is_async_iterator_error_) return ErrorHint::kAsyncIterator;
  }
  return ErrorHint::kNone;
}
References is_async_iterator_error_, is_call_error_, is_iterator_error_, kAsyncIterator, kCallAndAsyncIterator, kCallAndNormalIterator, kNone, and kNormalIterator.
Referenced by v8::internal::anonymous_namespace{messages.cc}::RenderCallSite().
Print() [1/4]
void v8::internal::CallPrinter::Print (char c) [private]
Definition at line 75 of file prettyprinter.cc.
                              {
  if (!found_ || done_) return;
  num_prints_++;
  builder_.AppendCharacter(c);
}
References v8::internal::IncrementalStringBuilder::AppendCharacter(), builder_, done_, found_, and num_prints_.
Print() [2/4]
void v8::internal::CallPrinter::Print (const char * str) [private]
Definition at line 81 of file prettyprinter.cc.
                                       {
  if (!found_ || done_) return;
  num_prints_++;
  builder_.AppendCString(str);
}
References v8::internal::IncrementalStringBuilder::AppendCString(), builder_, done_, found_, and num_prints_.
Print() [3/4]
void v8::internal::CallPrinter::Print (DirectHandle< String > str) [private]
Definition at line 87 of file prettyprinter.cc.
                                                {
  if (!found_ || done_) return;
  num_prints_++;
  builder_.AppendString(str);
}
References v8::internal::IncrementalStringBuilder::AppendString(), builder_, done_, found_, and num_prints_.
Print() [4/4]
DirectHandle< String > v8::internal::CallPrinter::Print (FunctionLiteral * program, int position)
Definition at line 54 of file prettyprinter.cc.
                                                      {
  num_prints_ = 0;
  position_ = position;
  Find(program);
  return builder_.Finish().ToHandleChecked();
}
References builder_, Find(), v8::internal::IncrementalStringBuilder::Finish(), num_prints_, and position_.
Referenced by Find(), PrintLiteral(), v8::internal::anonymous_namespace{messages.cc}::RenderCallSite(), v8::internal::ErrorUtils::ThrowLoadFromNullOrUndefined(), and v8::internal::ErrorUtils::ThrowSpreadArgError().
PrintLiteral() [1/2]
void v8::internal::CallPrinter::PrintLiteral (const AstRawString * value, bool quote) [protected]
Definition at line 649 of file prettyprinter.cc.
                                                                    {
  PrintLiteral(value->string(), quote);
}
References PrintLiteral(), and v8::internal::value.
PrintLiteral() [2/2]
void v8::internal::CallPrinter::PrintLiteral (DirectHandle< Object > value, bool quote) [protected]
Definition at line 627 of file prettyprinter.cc.
                                                                     {
  if (IsString(*value)) {
    if (quote) Print("\"");
    Print(Cast<String>(value));
    if (quote) Print("\"");
  } else if (IsNull(*value, isolate_)) {
    Print("null");
  } else if (IsTrue(*value, isolate_)) {
    Print("true");
  } else if (IsFalse(*value, isolate_)) {
    Print("false");
  } else if (IsUndefined(*value, isolate_)) {
    Print("undefined");
  } else if (IsNumber(*value)) {
    Print(isolate_->factory()->NumberToString(value));
  } else if (IsSymbol(*value)) {
    // Symbols can only occur as literals if they were inserted by the parser.
    PrintLiteral(direct_handle(Cast<Symbol>(value)->description(), isolate_),
                 false);
  }
}
References v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::IsNull(), v8::internal::IsNumber(), isolate_, v8::internal::FactoryBase< Impl >::NumberToString(), Print(), and v8::internal::value.
Referenced by PrintLiteral().
spread_arg()
Expression* v8::internal::CallPrinter::spread_arg () const [inline]
Definition at line 38 of file prettyprinter.h.
{ return spread_arg_; }
References spread_arg_.
Referenced by v8::internal::ErrorUtils::ThrowSpreadArgError().
Member Data Documentation
builder_
IncrementalStringBuilder v8::internal::CallPrinter::builder_ [private]
Definition at line 60 of file prettyprinter.h.
Referenced by Print().
destructuring_assignment_
Assignment* v8::internal::CallPrinter::destructuring_assignment_ [private]
Definition at line 70 of file prettyprinter.h.
Referenced by CallPrinter(), and destructuring_assignment().
destructuring_prop_
ObjectLiteralProperty* v8::internal::CallPrinter::destructuring_prop_ [private]
Definition at line 69 of file prettyprinter.h.
Referenced by CallPrinter(), and destructuring_prop().
done_
bool v8::internal::CallPrinter::done_ [private]
Definition at line 63 of file prettyprinter.h.
Referenced by CallPrinter(), and Print().
error_in_spread_args_
SpreadErrorInArgsHint v8::internal::CallPrinter::error_in_spread_args_ [private]
Definition at line 68 of file prettyprinter.h.
Referenced by CallPrinter().
found_
bool v8::internal::CallPrinter::found_ [private]
Definition at line 62 of file prettyprinter.h.
Referenced by CallPrinter(), Find(), FindArguments(), and Print().
function_kind_
FunctionKind v8::internal::CallPrinter::function_kind_ [private]
Definition at line 72 of file prettyprinter.h.
Referenced by CallPrinter().
is_async_iterator_error_
bool v8::internal::CallPrinter::is_async_iterator_error_ [private]
Definition at line 66 of file prettyprinter.h.
Referenced by CallPrinter(), and GetErrorHint().
is_call_error_
bool v8::internal::CallPrinter::is_call_error_ [private]
Definition at line 67 of file prettyprinter.h.
Referenced by CallPrinter(), and GetErrorHint().
is_iterator_error_
bool v8::internal::CallPrinter::is_iterator_error_ [private]
Definition at line 65 of file prettyprinter.h.
Referenced by CallPrinter(), and GetErrorHint().
is_user_js_
bool v8::internal::CallPrinter::is_user_js_ [private]
Definition at line 64 of file prettyprinter.h.
Referenced by CallPrinter().
isolate_
Isolate* v8::internal::CallPrinter::isolate_ [private]
Definition at line 58 of file prettyprinter.h.
Referenced by CallPrinter(), and PrintLiteral().
num_prints_
int v8::internal::CallPrinter::num_prints_ [private]
Definition at line 59 of file prettyprinter.h.
Referenced by CallPrinter(), Find(), and Print().
position_
int v8::internal::CallPrinter::position_ [private]
Definition at line 61 of file prettyprinter.h.
Referenced by CallPrinter(), and Print().
spread_arg_
Expression* v8::internal::CallPrinter::spread_arg_ [private]
Definition at line 71 of file prettyprinter.h.
Referenced by CallPrinter(), and spread_arg().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ast/prettyprinter.h
/mnt/V8SourceCode/src/ast/prettyprinter.cc