v8::internal::compiler::Mips64OperandGenerator Class Reference
Public Member Functions
Mips64OperandGenerator (InstructionSelector *selector)
InstructionOperand UseOperand (OpIndex node, InstructionCode opcode)
InstructionOperand UseRegisterOrImmediateZero (OpIndex node)
bool IsIntegerConstant (OpIndex node)
std::optional< int64_t > GetOptionalIntegerConstant (OpIndex operation)
bool CanBeImmediate (OpIndex node, InstructionCode mode)
bool CanBeImmediate (int64_t value, InstructionCode opcode)
Private Member Functions
bool ImmediateFitsAddrMode1Instruction (int32_t imm) const
Additional Inherited Members
Detailed Description
Definition at line 23 of file instruction-selector-mips64.cc.
Constructor & Destructor Documentation
Mips64OperandGenerator()
v8::internal::compiler::Mips64OperandGenerator::Mips64OperandGenerator (InstructionSelector * selector) [inline], [explicit]
Definition at line 25 of file instruction-selector-mips64.cc.
      : OperandGenerator(selector) {}
Member Function Documentation
CanBeImmediate() [1/2]
bool v8::internal::compiler::Mips64OperandGenerator::CanBeImmediate (int64_t value, InstructionCode opcode) [inline]
Definition at line 72 of file instruction-selector-mips64.cc.
                                                             {
    switch (ArchOpcodeField::decode(opcode)) {
      case kMips64Shl:
      case kMips64Sar:
      case kMips64Shr:
        return is_uint5(value);
      case kMips64Dshl:
      case kMips64Dsar:
      case kMips64Dshr:
        return is_uint6(value);
      case kMips64Add:
      case kMips64And32:
      case kMips64And:
      case kMips64Dadd:
      case kMips64Or32:
      case kMips64Or:
      case kMips64Tst:
      case kMips64Xor:
        return is_uint16(value);
      case kMips64Lb:
      case kMips64Lbu:
      case kMips64Sb:
      case kMips64Lh:
      case kMips64Lhu:
      case kMips64Sh:
      case kMips64Lw:
      case kMips64Sw:
      case kMips64Ld:
      case kMips64Sd:
      case kMips64Lwc1:
      case kMips64Swc1:
      case kMips64Ldc1:
      case kMips64Sdc1:
        return is_int32(value);
      default:
        return is_int16(value);
    }
  }
References v8::base::BitField< T, shift, size, U >::decode(), and v8::internal::value.
CanBeImmediate() [2/2]
bool v8::internal::compiler::Mips64OperandGenerator::CanBeImmediate (OpIndex node, InstructionCode mode) [inline]
Definition at line 63 of file instruction-selector-mips64.cc.
                                                          {
    const ConstantOp* constant = selector()->Get(node).TryCast<ConstantOp>();
    if (!constant) return false;
    int64_t value;
    return selector()->MatchSignedIntegralConstant(node, &value) &&
           CanBeImmediate(value, mode);
  }
References v8::internal::compiler::CanBeImmediate(), mode(), v8::internal::compiler::turboshaft::Operation::TryCast(), and v8::internal::value.
Referenced by v8::internal::compiler::ExtendingLoadMatcher::Initialize(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicStore(), and v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitWordCompare().
GetOptionalIntegerConstant()
std::optional<int64_t> v8::internal::compiler::Mips64OperandGenerator::GetOptionalIntegerConstant (OpIndex operation) [inline]
Definition at line 56 of file instruction-selector-mips64.cc.
                                                                     {
    if (int64_t constant; MatchSignedIntegralConstant(operation, &constant)) {
      return constant;
    }
    return std::nullopt;
  }
ImmediateFitsAddrMode1Instruction()
bool v8::internal::compiler::Mips64OperandGenerator::ImmediateFitsAddrMode1Instruction (int32_t imm) const [inline], [private]
Definition at line 112 of file instruction-selector-mips64.cc.
                                                            {
    TRACE("UNIMPLEMENTED instr_sel: %s at line %d\n", __FUNCTION__, __LINE__);
    return false;
  }
References v8::internal::TRACE().
IsIntegerConstant()
bool v8::internal::compiler::Mips64OperandGenerator::IsIntegerConstant (OpIndex node) [inline]
Definition at line 51 of file instruction-selector-mips64.cc.
                                       {
    int64_t unused;
    return selector()->MatchSignedIntegralConstant(node, &unused);
  }
UseOperand()
InstructionOperand v8::internal::compiler::Mips64OperandGenerator::UseOperand (OpIndex node, InstructionCode opcode) [inline]
Definition at line 28 of file instruction-selector-mips64.cc.
                                                                      {
    if (CanBeImmediate(node, opcode)) {
      return UseImmediate(node);
    }
    return UseRegister(node);
  }
References v8::internal::compiler::CanBeImmediate(), and v8::internal::maglev::UseRegister().
Referenced by v8::internal::compiler::VisitBinop(), and v8::internal::compiler::VisitRRO().
UseRegisterOrImmediateZero()
InstructionOperand v8::internal::compiler::Mips64OperandGenerator::UseRegisterOrImmediateZero (OpIndex node) [inline]
Definition at line 37 of file instruction-selector-mips64.cc.
                                                              {
    if (const ConstantOp* constant =
            selector()->Get(node).TryCast<ConstantOp>()) {
      if ((constant->IsIntegral() && constant->integral() == 0) ||
          (constant->kind == ConstantOp::Kind::kFloat32 &&
           constant->float32().get_bits() == 0) ||
          (constant->kind == ConstantOp::Kind::kFloat64 &&
           constant->float64().get_bits() == 0)) {
        return UseImmediate(node);
      }
    }
    return UseRegister(node);
  }
References v8::internal::compiler::turboshaft::Get(), v8::internal::compiler::turboshaft::ConstantOp::kFloat32, v8::internal::compiler::turboshaft::ConstantOp::kFloat64, and v8::internal::maglev::UseRegister().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicStore().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/mips64/instruction-selector-mips64.cc