v8::internal::compiler::turboshaft::FloatRepresentation Class Reference
#include <representations.h>
Public Types
enum class Enum : uint8_t { kFloat32 = static_cast<int>(RegisterRepresentation::Enum::kFloat32)
, kFloat64 = static_cast<int>(RegisterRepresentation::Enum::kFloat64)
 }
Public Member Functions
constexpr FloatRepresentation (Enum value)
constexpr FloatRepresentation (RegisterRepresentation rep)
FloatRepresentation ()=default
constexpr Enum value () const
constexpr operator Enum () const
Static Public Member Functions
static constexpr FloatRepresentation Float32 ()
static constexpr FloatRepresentation Float64 ()
Detailed Description
Definition at line 484 of file representations.h.
Member Enumeration Documentation
Enum
enum v8::internal::compiler::turboshaft::FloatRepresentation::Enum : uint8_t [strong]
Enumerator
kFloat32
kFloat64
Definition at line 486 of file representations.h.
                  : uint8_t {
    kFloat32 = static_cast<int>(RegisterRepresentation::Enum::kFloat32),
    kFloat64 = static_cast<int>(RegisterRepresentation::Enum::kFloat64)
  };
Constructor & Destructor Documentation
FloatRepresentation() [1/3]
constexpr v8::internal::compiler::turboshaft::FloatRepresentation::FloatRepresentation (Enum value) [inline], [explicit], [constexpr]
Definition at line 498 of file representations.h.
      : RegisterRepresentation(
            static_cast<RegisterRepresentation::Enum>(value)) {}
FloatRepresentation() [2/3]
constexpr v8::internal::compiler::turboshaft::FloatRepresentation::FloatRepresentation (RegisterRepresentation rep) [inline], [explicit], [constexpr]
Definition at line 501 of file representations.h.
      : FloatRepresentation(static_cast<Enum>(rep.value())) {
    DCHECK(rep.IsFloat());
  }
References v8::internal::DCHECK(), and v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::IsFloat().
FloatRepresentation() [3/3]
v8::internal::compiler::turboshaft::FloatRepresentation::FloatRepresentation () [default]
Referenced by Float32(), and Float64().
Member Function Documentation
Float32()
static constexpr FloatRepresentation v8::internal::compiler::turboshaft::FloatRepresentation::Float32 () [inline], [static], [constexpr]
Definition at line 491 of file representations.h.
                                                 {
    return FloatRepresentation(Enum::kFloat32);
  }
References FloatRepresentation(), and kFloat32.
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatBinop(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::FloatConstant(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::FloatUnary(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatUnary(), v8::internal::compiler::turboshaft::FloatUnaryOp::IsSupported(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::ProduceWord32Result(), and v8::internal::compiler::turboshaft::Typer::TypeFloatBinop().
Float64()
static constexpr FloatRepresentation v8::internal::compiler::turboshaft::FloatRepresentation::Float64 () [inline], [static], [constexpr]
Definition at line 494 of file representations.h.
                                                 {
    return FloatRepresentation(Enum::kFloat64);
  }
References FloatRepresentation(), and kFloat64.
Referenced by v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Float64Unary(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatBinop(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::FloatConstant(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::FloatUnary(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatUnary(), v8::internal::compiler::turboshaft::FloatUnaryOp::IsSupported(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ObjectIsNumericValue(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::ProduceWord32Result(), v8::internal::compiler::turboshaft::Typer::TypeFloatBinop(), and v8::internal::compiler::turboshaft::FloatBinopOp::Validate().
operator Enum()
constexpr v8::internal::compiler::turboshaft::FloatRepresentation::operator Enum () const [inline], [constexpr]
Definition at line 510 of file representations.h.
{ return value(); }
References value().
value()
constexpr Enum v8::internal::compiler::turboshaft::FloatRepresentation::value () const [inline], [constexpr]
Definition at line 507 of file representations.h.
                               {
    return static_cast<Enum>(RegisterRepresentation::value());
  }
References v8::internal::compiler::turboshaft::RegisterRepresentation::value().
Referenced by v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::FloatConstant(), v8::internal::compiler::turboshaft::FloatUnaryOp::IsSupported(), and operator Enum().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/representations.h