v8::internal::CodeEntry Class Reference
#include <profile-generator.h>
Classes
struct Equals
struct Hasher
struct RareData
Public Types
enum class CodeType { JS
, WASM
, OTHER
 }
Public Member Functions
CodeEntry (LogEventListener::CodeTag tag, const char *name, const char *resource_name=CodeEntry::kEmptyResourceName, LineAndColumn line_and_column={}, std::unique_ptr< SourcePositionTable > line_info=nullptr, bool is_shared_cross_origin=false, CodeType code_type=CodeType::JS)
CodeEntry (const CodeEntry &)=delete
CodeEntry & operator= (const CodeEntry &)=delete
~CodeEntry ()
const char * name () const
const char * resource_name () const
LineAndColumn line_and_column () const
const SourcePositionTable * line_info () const
int script_id () const
void set_script_id (int script_id)
int position () const
void set_position (int position)
void set_bailout_reason (const char *bailout_reason)
const char * bailout_reason () const
void set_deopt_info (const char *deopt_reason, int deopt_id, std::vector< CpuProfileDeoptFrame > inlined_frames)
size_t EstimatedSize () const
CpuProfileDeoptInfo GetDeoptInfo ()
bool has_deopt_info () const
void clear_deopt_info ()
const char * code_type_string () const
Address instruction_start () const
void set_instruction_start (Address address)
Address ** heap_object_location_address ()
void FillFunctionInfo (Tagged< SharedFunctionInfo > shared)
void SetBuiltinId (Builtin id)
Builtin builtin () const
bool is_shared_cross_origin () const
bool is_ref_counted () const
size_t GetHash () const
bool IsSameFunctionAs (const CodeEntry *entry) const
LineAndColumn GetSourcePosition (int pc_offset) const
void SetInlineStacks (std::unordered_set< CodeEntry *, Hasher, Equals > inline_entries, std::unordered_map< int, std::vector< CodeEntryAndPosition >> inline_stacks)
const std::vector< CodeEntryAndPosition > * GetInlineStack (int pc_offset) const
LogEventListener::Event event () const
LogEventListener::CodeTag code_tag () const
void ReleaseStrings (StringsStorage &strings)
void print () const
Static Public Member Functions
static V8_EXPORT_PRIVATE CodeEntry * program_entry ()
static V8_EXPORT_PRIVATE CodeEntry * idle_entry ()
static V8_EXPORT_PRIVATE CodeEntry * gc_entry ()
static V8_EXPORT_PRIVATE CodeEntry * unresolved_entry ()
static V8_EXPORT_PRIVATE CodeEntry * root_entry ()
Static Public Attributes
static V8_EXPORT_PRIVATE const char *const kEmptyResourceName = ``
static const char *const kEmptyBailoutReason = ``
static const char *const kNoDeoptReason = ``
static V8_EXPORT_PRIVATE const char *const kProgramEntryName = `(program)`
static V8_EXPORT_PRIVATE const char *const kIdleEntryName = `(idle)`
static V8_EXPORT_PRIVATE const char *const kGarbageCollectorEntryName = `(garbage collector)`
static V8_EXPORT_PRIVATE const char *const kUnresolvedFunctionName = `(unresolved function)`
static V8_EXPORT_PRIVATE const char *const kRootEntryName = `(root)`
Private Types
using EventField = base::BitField< LogEventListener::Event, 0, 4 >
using CodeTagField = base::BitField< LogEventListener::CodeTag, 0, 4 >
using BuiltinField = base::BitField< Builtin, 8, 20 >
using RefCountedField = base::BitField< bool, 28, 1 >
using CodeTypeField = base::BitField< CodeType, 29, 2 >
using SharedCrossOriginField = base::BitField< bool, 31, 1 >
Private Member Functions
RareData * EnsureRareData ()
void mark_ref_counted ()
size_t AddRef ()
size_t DecRef ()
Private Attributes
std::uint32_t bit_field_
std::atomic< std::size_t > ref_count_ = {0}
const char * name_
const char * resource_name_
LineAndColumn line_and_column_
int script_id_
int position_
std::unique_ptr< SourcePositionTable > line_info_
std::unique_ptr< RareData > rare_data_
Address instruction_start_ = kNullAddress
Address * heap_object_location_ = nullptr
Friends
class CodeEntryStorage
Detailed Description
Definition at line 76 of file profile-generator.h.
Member Typedef Documentation
BuiltinField
using v8::internal::CodeEntry::BuiltinField = base::BitField<Builtin, 8, 20> [private]
Definition at line 246 of file profile-generator.h.
CodeTagField
using v8::internal::CodeEntry::CodeTagField = base::BitField<LogEventListener::CodeTag, 0, 4> [private]
Definition at line 245 of file profile-generator.h.
CodeTypeField
using v8::internal::CodeEntry::CodeTypeField = base::BitField<CodeType, 29, 2> [private]
Definition at line 250 of file profile-generator.h.
EventField
using v8::internal::CodeEntry::EventField = base::BitField<LogEventListener::Event, 0, 4> [private]
Definition at line 244 of file profile-generator.h.
RefCountedField
using v8::internal::CodeEntry::RefCountedField = base::BitField<bool, 28, 1> [private]
Definition at line 249 of file profile-generator.h.
SharedCrossOriginField
using v8::internal::CodeEntry::SharedCrossOriginField = base::BitField<bool, 31, 1> [private]
Definition at line 251 of file profile-generator.h.
Member Enumeration Documentation
CodeType
enum v8::internal::CodeEntry::CodeType [strong]
Enumerator
JS
WASM
OTHER
Definition at line 78 of file profile-generator.h.
{ JS, WASM, OTHER };
Constructor & Destructor Documentation
CodeEntry() [1/2]
v8::internal::CodeEntry::CodeEntry (LogEventListener::CodeTag tag, const char * name, const char * resource_name = CodeEntry::kEmptyResourceName, LineAndColumn line_and_column = {}, std::unique_ptr< SourcePositionTable > line_info = nullptr, bool is_shared_cross_origin = false, CodeType code_type = CodeType::JS) [inline]
Definition at line 16 of file profile-generator-inl.h.
    : bit_field_(CodeTagField::encode(tag) |
                 BuiltinField::encode(Builtin::kIllegal) |
                 CodeTypeField::encode(code_type) |
                 SharedCrossOriginField::encode(is_shared_cross_origin)),
      name_(name),
      resource_name_(resource_name),
      line_and_column_(line_and_column),
      script_id_(v8::UnboundScript::kNoScriptId),
      position_(0),
      line_info_(std::move(line_info)) {}
CodeEntry() [2/2]
v8::internal::CodeEntry::CodeEntry (const CodeEntry &) [delete]
 CodeEntry()
v8::internal::CodeEntry::~CodeEntry () [inline]
Definition at line 90 of file profile-generator.h.
               {
    // No alive handles should be associated with the CodeEntry at time of
    // destruction.
    DCHECK(!heap_object_location_);
    DCHECK_EQ(ref_count_, 0UL);
  }
References v8::internal::DCHECK(), DCHECK_EQ, heap_object_location_, and ref_count_.
Member Function Documentation
AddRef()
size_t v8::internal::CodeEntry::AddRef () [inline], [private]
Definition at line 230 of file profile-generator.h.
                  {
    DCHECK(is_ref_counted());
    DCHECK_LT(ref_count_, std::numeric_limits<size_t>::max());
    ref_count_++;
    return ref_count_;
  }
References v8::internal::DCHECK(), DCHECK_LT, is_ref_counted(), and ref_count_.
Referenced by v8::internal::CodeEntryStorage::AddRef().
bailout_reason()
const char* v8::internal::CodeEntry::bailout_reason () const [inline]
Definition at line 108 of file profile-generator.h.
                                     {
    return rare_data_ ? rare_data_->bailout_reason_ : kEmptyBailoutReason;
  }
References kEmptyBailoutReason, and rare_data_.
Referenced by v8::internal::anonymous_namespace{profile-generator.cc}::BuildNodeValue(), v8::CpuProfileNode::GetBailoutReason(), v8::internal::ProfileNode::Print(), and set_bailout_reason().
builtin()
Builtin v8::internal::CodeEntry::builtin () const [inline]
Definition at line 148 of file profile-generator.h.
{ return BuiltinField::decode(bit_field_); }
References bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::Symbolizer::SymbolizeTickSample().
clear_deopt_info()
void v8::internal::CodeEntry::clear_deopt_info () [inline]
Definition at line 120 of file profile-generator.h.
                          {
    if (!rare_data_) return;
    // TODO(alph): Clear rare_data_ if that was the only field in use.
    rare_data_->deopt_reason_ = kNoDeoptReason;
    rare_data_->deopt_id_ = kNoDeoptimizationId;
  }
References v8::internal::kNoDeoptimizationId, kNoDeoptReason, and rare_data_.
Referenced by v8::internal::ProfileNode::CollectDeoptInfo().
code_tag()
LogEventListener::CodeTag v8::internal::CodeEntry::code_tag () const [inline]
Definition at line 181 of file profile-generator.h.
                                           {
    return CodeTagField::decode(bit_field_);
  }
References bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::ProfileNode::source_type().
code_type_string()
const char* v8::internal::CodeEntry::code_type_string () const [inline]
Definition at line 127 of file profile-generator.h.
                                       {
    switch (CodeTypeField::decode(bit_field_)) {
      case CodeType::JS:
        return "JS";
      case CodeType::WASM:
        return "wasm";
      case CodeType::OTHER:
        return "other";
    }
  }
References bit_field_, v8::base::BitField< T, shift, size, U >::decode(), JS, OTHER, and WASM.
Referenced by v8::internal::anonymous_namespace{profile-generator.cc}::BuildNodeValue().
DecRef()
size_t v8::internal::CodeEntry::DecRef () [inline], [private]
Definition at line 237 of file profile-generator.h.
                  {
    DCHECK(is_ref_counted());
    DCHECK_GT(ref_count_, 0UL);
    ref_count_--;
    return ref_count_;
  }
References v8::internal::DCHECK(), DCHECK_GT, is_ref_counted(), and ref_count_.
Referenced by v8::internal::CodeEntryStorage::DecRef().
EnsureRareData()
CodeEntry::RareData * v8::internal::CodeEntry::EnsureRareData () [private]
Definition at line 270 of file profile-generator.cc.
                                             {
  if (!rare_data_) {
    rare_data_.reset(new RareData());
  }
  return rare_data_.get();
}
References rare_data_.
Referenced by set_bailout_reason(), set_deopt_info(), and SetInlineStacks().
EstimatedSize()
size_t v8::internal::CodeEntry::EstimatedSize () const
Definition at line 224 of file profile-generator.cc.
                                      {
  size_t estimated_size = 0;
  if (rare_data_) {
    estimated_size += sizeof(rare_data_.get());
    for (const auto& inline_entry : rare_data_->inline_entries_) {
      estimated_size += inline_entry->EstimatedSize();
    }
    estimated_size += rare_data_->inline_entries_.size() *
                      sizeof(decltype(rare_data_->inline_entries_)::value_type);
    for (const auto& inline_stack_pair : rare_data_->inline_stacks_) {
      estimated_size += inline_stack_pair.second.size() *
                        sizeof(decltype(inline_stack_pair.second)::value_type);
    }
    estimated_size +=
        rare_data_->inline_stacks_.size() *
        (sizeof(decltype(rare_data_->inline_stacks_)::key_type) +
         sizeof(decltype(rare_data_->inline_stacks_)::value_type));
    estimated_size +=
        rare_data_->deopt_inlined_frames_.capacity() *
        sizeof(decltype(rare_data_->deopt_inlined_frames_)::value_type);
  }
  if (line_info_) {
    estimated_size += line_info_->Size();
  }
  return sizeof(*this) + estimated_size;
}
References line_info_, rare_data_, and v8::internal::wasm::value_type().
event()
LogEventListener::Event v8::internal::CodeEntry::event () const [inline]
Definition at line 177 of file profile-generator.h.
                                      {
    return EventField::decode(bit_field_);
  }
References bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
FillFunctionInfo()
void v8::internal::CodeEntry::FillFunctionInfo (Tagged< SharedFunctionInfo > shared)
Definition at line 213 of file profile-generator.cc.
                                                                  {
  if (!IsScript(shared->script())) return;
  Tagged<Script> script = Cast<Script>(shared->script());
  set_script_id(script->id());
  set_position(shared->StartPosition());
  if (shared->all_optimization_disabled()) {
    set_bailout_reason(
        GetBailoutReason(shared->disabled_optimization_reason()));
  }
}
References v8::internal::GetBailoutReason(), v8::internal::script, set_bailout_reason(), set_position(), and set_script_id().
Referenced by v8::internal::ProfilerListener::CodeCreateEvent().
gc_entry()
CodeEntry * v8::internal::CodeEntry::gc_entry () [static]
Definition at line 125 of file profile-generator.cc.
                               {
  static base::LeakyObject<CodeEntry> kGcEntry(
      LogEventListener::CodeTag::kBuiltin,
      CodeEntry::kGarbageCollectorEntryName, CodeEntry::kEmptyResourceName,
      LineAndColumn{}, nullptr, false, CodeEntry::CodeType::OTHER);
  return kGcEntry.get();
}
References v8::base::LeakyObject< T >::get(), kEmptyResourceName, kGarbageCollectorEntryName, and OTHER.
Referenced by v8::internal::anonymous_namespace{symbolizer.cc}::EntryForVMState(), and v8::internal::ProfileNode::source_type().
GetDeoptInfo()
CpuProfileDeoptInfo v8::internal::CodeEntry::GetDeoptInfo ()
Definition at line 255 of file profile-generator.cc.
                                            {
  DCHECK(has_deopt_info());
  CpuProfileDeoptInfo info;
  info.deopt_reason = rare_data_->deopt_reason_;
  DCHECK_NE(kNoDeoptimizationId, rare_data_->deopt_id_);
  if (rare_data_->deopt_inlined_frames_.empty()) {
    info.stack.push_back(CpuProfileDeoptFrame(
        {script_id_, static_cast<size_t>(std::max(0, position()))}));
  } else {
    info.stack = rare_data_->deopt_inlined_frames_;
  }
  return info;
}
References v8::internal::DCHECK(), DCHECK_NE, v8::CpuProfileDeoptInfo::deopt_reason, has_deopt_info(), v8::internal::kNoDeoptimizationId, position(), rare_data_, script_id_, and v8::CpuProfileDeoptInfo::stack.
Referenced by v8::internal::ProfileNode::CollectDeoptInfo().
GetHash()
size_t v8::internal::CodeEntry::GetHash () const
Definition at line 151 of file profile-generator.cc.
                                {
  base::Hasher hasher;
  if (script_id_ != v8::UnboundScript::kNoScriptId) {
    hasher.Add(script_id_);
    hasher.Add(position_);
  } else {
    hasher.Add(name_);
    hasher.Add(resource_name_);
    hasher.Add(position_);
  }
  return hasher.hash();
}
References v8::base::Hasher::Add(), v8::base::Hasher::hash(), v8::UnboundScript::kNoScriptId, name_, position_, resource_name_, and script_id_.
Referenced by v8::internal::CodeEntry::Hasher::operator()(), and v8::internal::ProfileNode::Hasher::operator()().
GetInlineStack()
const std::vector< CodeEntryAndPosition > * v8::internal::CodeEntry::GetInlineStack (int pc_offset) const
Definition at line 192 of file profile-generator.cc.
                         {
  if (!line_info_) return nullptr;
  int inlining_id = line_info_->GetInliningId(pc_offset);
  if (inlining_id == SourcePosition::kNotInlined) return nullptr;
  DCHECK(rare_data_);
  auto it = rare_data_->inline_stacks_.find(inlining_id);
  return it != rare_data_->inline_stacks_.end() ? &it->second : nullptr;
}
References v8::internal::DCHECK(), v8::internal::SourcePosition::kNotInlined, line_info_, and rare_data_.
Referenced by v8::internal::Symbolizer::SymbolizeTickSample().
GetSourcePosition()
LineAndColumn v8::internal::CodeEntry::GetSourcePosition (int pc_offset) const
Definition at line 180 of file profile-generator.cc.
                                                              {
  if (line_info_) return line_info_->GetSourceLineAndColumn(pc_offset);
  return {};
}
References line_info_.
Referenced by v8::internal::Symbolizer::SymbolizeTickSample().
has_deopt_info()
bool v8::internal::CodeEntry::has_deopt_info () const [inline]
Definition at line 117 of file profile-generator.h.
                              {
    return rare_data_ && rare_data_->deopt_id_ != kNoDeoptimizationId;
  }
References v8::internal::kNoDeoptimizationId, and rare_data_.
Referenced by v8::internal::ProfileTree::AddPathFromEnd(), and GetDeoptInfo().
heap_object_location_address()
Address** v8::internal::CodeEntry::heap_object_location_address () [inline]
Definition at line 143 of file profile-generator.h.
{ return &heap_object_location_; }
References heap_object_location_.
Referenced by v8::internal::WeakCodeRegistry::Track(), and v8::internal::anonymous_namespace{weak-code-registry.cc}::Untrack().
idle_entry()
CodeEntry * v8::internal::CodeEntry::idle_entry () [static]
Definition at line 116 of file profile-generator.cc.
                                 {
  static base::LeakyObject<CodeEntry> kIdleEntry(
      LogEventListener::CodeTag::kFunction, CodeEntry::kIdleEntryName,
      CodeEntry::kEmptyResourceName, LineAndColumn{}, nullptr, false,
      CodeEntry::CodeType::OTHER);
  return kIdleEntry.get();
}
References v8::base::LeakyObject< T >::get(), kEmptyResourceName, v8::internal::torque::ls::kFunction, kIdleEntryName, and OTHER.
Referenced by v8::internal::anonymous_namespace{symbolizer.cc}::EntryForVMState(), and v8::internal::ProfileNode::source_type().
instruction_start()
Address v8::internal::CodeEntry::instruction_start () const [inline]
Definition at line 140 of file profile-generator.h.
{ return instruction_start_; }
References instruction_start_.
Referenced by v8::internal::InstructionStreamMap::MoveCode(), and v8::internal::InstructionStreamMap::RemoveCode().
is_ref_counted()
bool v8::internal::CodeEntry::is_ref_counted () const [inline]
Definition at line 156 of file profile-generator.h.
{ return RefCountedField::decode(bit_field_); }
References bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by AddRef(), v8::internal::CodeEntryStorage::AddRef(), DecRef(), and v8::internal::CodeEntryStorage::DecRef().
is_shared_cross_origin()
bool v8::internal::CodeEntry::is_shared_cross_origin () const [inline]
Definition at line 150 of file profile-generator.h.
                                      {
    return SharedCrossOriginField::decode(bit_field_);
  }
References bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::CpuProfileNode::IsScriptSharedCrossOrigin().
IsSameFunctionAs()
bool v8::internal::CodeEntry::IsSameFunctionAs (const CodeEntry * entry) const
Definition at line 164 of file profile-generator.cc.
                                                             {
  if (this == entry) return true;
  if (script_id_ != v8::UnboundScript::kNoScriptId) {
    return script_id_ == entry->script_id_ && position_ == entry->position_;
  }
  return name_ == entry->name_ && resource_name_ == entry->resource_name_ &&
         line_and_column_.line == entry->line_and_column_.line &&
         line_and_column_.column == entry->line_and_column_.column;
}
References v8::internal::LineAndColumn::column, v8::UnboundScript::kNoScriptId, v8::internal::LineAndColumn::line, line_and_column_, name_, position_, resource_name_, and script_id_.
Referenced by v8::internal::ProfileNode::Equals::operator()(), and v8::internal::CodeEntry::Equals::operator()().
line_and_column()
LineAndColumn v8::internal::CodeEntry::line_and_column () const [inline]
Definition at line 99 of file profile-generator.h.
{ return line_and_column_; }
References line_and_column_.
Referenced by v8::internal::anonymous_namespace{profile-generator.cc}::BuildNodeValue(), v8::internal::ProfileNode::Print(), and v8::internal::Symbolizer::SymbolizeTickSample().
line_info()
const SourcePositionTable* v8::internal::CodeEntry::line_info () const [inline]
Definition at line 100 of file profile-generator.h.
{ return line_info_.get(); }
References line_info_.
mark_ref_counted()
void v8::internal::CodeEntry::mark_ref_counted () [inline], [private]
Definition at line 225 of file profile-generator.h.
                          {
    bit_field_ = RefCountedField::update(bit_field_, true);
    ref_count_ = 1;
  }
References bit_field_, ref_count_, and v8::base::BitField< T, shift, size, U >::update().
Referenced by v8::internal::CodeEntryStorage::Create().
name()
const char* v8::internal::CodeEntry::name () const [inline]
Definition at line 97 of file profile-generator.h.
{ return name_; }
References name_.
Referenced by v8::internal::anonymous_namespace{profile-generator.cc}::BuildNodeValue(), v8::CpuProfileNode::GetFunctionName(), v8::CpuProfileNode::GetFunctionNameStr(), and v8::internal::ProfileNode::Print().
operator=()
CodeEntry& v8::internal::CodeEntry::operator= (const CodeEntry &) [delete]
position()
int v8::internal::CodeEntry::position () const [inline]
Definition at line 103 of file profile-generator.h.
{ return position_; }
References position_.
Referenced by GetDeoptInfo(), and set_position().
print()
void v8::internal::CodeEntry::print () const
Definition at line 290 of file profile-generator.cc.
                            {
  base::OS::Print("CodeEntry: at %p\n", this);
  base::OS::Print(" - name: %s\n", name_);
  base::OS::Print(" - resource_name: %s\n", resource_name_);
  base::OS::Print(" - line_number: %d\n", line_and_column_.line);
  base::OS::Print(" - column_number: %d\n", line_and_column_.column);
  base::OS::Print(" - script_id: %d\n", script_id_);
  base::OS::Print(" - position: %d\n", position_);
  if (line_info_) {
    line_info_->print();
  }
  if (rare_data_) {
    base::OS::Print(" - deopt_reason: %s\n", rare_data_->deopt_reason_);
    base::OS::Print(" - bailout_reason: %s\n", rare_data_->bailout_reason_);
    base::OS::Print(" - deopt_id: %d\n", rare_data_->deopt_id_);
    if (!rare_data_->inline_stacks_.empty()) {
      base::OS::Print(" - inline stacks:\n");
      for (auto it = rare_data_->inline_stacks_.begin();
           it != rare_data_->inline_stacks_.end(); it++) {
        base::OS::Print(" inlining_id: [%d]\n", it->first);
        for (const auto& e : it->second) {
          base::OS::Print(" %s --> %d:%d\n", e.code_entry->name(),
                          e.line_and_column.line, e.line_and_column.column);
        }
      }
    } else {
      base::OS::Print(" - inline stacks: (empty)\n");
    }
    if (!rare_data_->deopt_inlined_frames_.empty()) {
      base::OS::Print(" - deopt inlined frames:\n");
      for (const CpuProfileDeoptFrame& frame :
           rare_data_->deopt_inlined_frames_) {
        base::OS::Print("script_id: %d position: %zu\n", frame.script_id,
                        frame.position);
      }
    } else {
      base::OS::Print(" - deopt inlined frames: (empty)\n");
    }
  }
  base::OS::Print("\n");
}
References v8::internal::LineAndColumn::column, v8::internal::LineAndColumn::line, line_and_column_, line_info_, name_, v8::CpuProfileDeoptFrame::position, position_, v8::internal::Print(), rare_data_, resource_name_, v8::CpuProfileDeoptFrame::script_id, and script_id_.
program_entry()
CodeEntry * v8::internal::CodeEntry::program_entry () [static]
Definition at line 107 of file profile-generator.cc.
                                    {
  static base::LeakyObject<CodeEntry> kProgramEntry(
      LogEventListener::CodeTag::kFunction, CodeEntry::kProgramEntryName,
      CodeEntry::kEmptyResourceName, LineAndColumn{}, nullptr, false,
      CodeEntry::CodeType::OTHER);
  return kProgramEntry.get();
}
References v8::base::LeakyObject< T >::get(), kEmptyResourceName, v8::internal::torque::ls::kFunction, kProgramEntryName, and OTHER.
Referenced by v8::internal::anonymous_namespace{symbolizer.cc}::EntryForVMState(), and v8::internal::ProfileNode::source_type().
ReleaseStrings()
void v8::internal::CodeEntry::ReleaseStrings (StringsStorage & strings)
Definition at line 277 of file profile-generator.cc.
                                                      {
  DCHECK_EQ(ref_count_, 0UL);
  if (name_) {
    strings.Release(name_);
    name_ = nullptr;
  }
  if (resource_name_) {
    strings.Release(resource_name_);
    resource_name_ = nullptr;
  }
}
References DCHECK_EQ, name_, ref_count_, v8::internal::StringsStorage::Release(), and resource_name_.
Referenced by v8::internal::CodeEntryStorage::DecRef().
resource_name()
const char* v8::internal::CodeEntry::resource_name () const [inline]
Definition at line 98 of file profile-generator.h.
{ return resource_name_; }
References resource_name_.
Referenced by v8::internal::anonymous_namespace{profile-generator.cc}::BuildNodeValue(), v8::CpuProfileNode::GetScriptResourceName(), v8::CpuProfileNode::GetScriptResourceNameStr(), and v8::internal::ProfileNode::Print().
root_entry()
CodeEntry * v8::internal::CodeEntry::root_entry () [static]
Definition at line 143 of file profile-generator.cc.
                                 {
  static base::LeakyObject<CodeEntry> kRootEntry(
      LogEventListener::CodeTag::kFunction, CodeEntry::kRootEntryName,
      CodeEntry::kEmptyResourceName, LineAndColumn{}, nullptr, false,
      CodeEntry::CodeType::OTHER);
  return kRootEntry.get();
}
References v8::base::LeakyObject< T >::get(), kEmptyResourceName, v8::internal::torque::ls::kFunction, kRootEntryName, and OTHER.
Referenced by v8::internal::ProfileNode::source_type().
script_id()
int v8::internal::CodeEntry::script_id () const [inline]
Definition at line 101 of file profile-generator.h.
{ return script_id_; }
References script_id_.
Referenced by v8::internal::anonymous_namespace{profile-generator.cc}::BuildNodeValue(), v8::CpuProfileNode::GetScriptId(), v8::internal::ProfileNode::Print(), and set_script_id().
set_bailout_reason()
void v8::internal::CodeEntry::set_bailout_reason (const char * bailout_reason) [inline]
Definition at line 105 of file profile-generator.h.
                                                      {
    EnsureRareData()->bailout_reason_ = bailout_reason;
  }
References bailout_reason(), v8::internal::CodeEntry::RareData::bailout_reason_, and EnsureRareData().
Referenced by FillFunctionInfo(), and v8::internal::CodeDisableOptEventRecord::UpdateCodeMap().
set_deopt_info()
void v8::internal::CodeEntry::set_deopt_info (const char * deopt_reason, int deopt_id, std::vector< CpuProfileDeoptFrame > inlined_frames)
Definition at line 204 of file profile-generator.cc.
                                                    {
  RareData* rare_data = EnsureRareData();
  rare_data->deopt_reason_ = deopt_reason;
  rare_data->deopt_id_ = deopt_id;
  rare_data->deopt_inlined_frames_ = std::move(inlined_frames);
}
References v8::internal::CodeEntry::RareData::deopt_id_, v8::internal::CodeEntry::RareData::deopt_inlined_frames_, v8::internal::CodeEntry::RareData::deopt_reason_, and EnsureRareData().
Referenced by v8::internal::CodeDeoptEventRecord::UpdateCodeMap().
set_instruction_start()
void v8::internal::CodeEntry::set_instruction_start (Address address) [inline]
Definition at line 141 of file profile-generator.h.
{ instruction_start_ = address; }
References instruction_start_.
Referenced by v8::internal::InstructionStreamMap::AddCode(), and v8::internal::InstructionStreamMap::MoveCode().
set_position()
void v8::internal::CodeEntry::set_position (int position) [inline]
Definition at line 104 of file profile-generator.h.
{ position_ = position; }
References position(), and position_.
Referenced by FillFunctionInfo().
set_script_id()
void v8::internal::CodeEntry::set_script_id (int script_id) [inline]
Definition at line 102 of file profile-generator.h.
{ script_id_ = script_id; }
References script_id(), and script_id_.
Referenced by FillFunctionInfo().
SetBuiltinId()
void v8::internal::CodeEntry::SetBuiltinId (Builtin id)
Definition at line 174 of file profile-generator.cc.
                                       {
  bit_field_ =
      CodeTagField::update(bit_field_, LogEventListener::CodeTag::kBuiltin);
  bit_field_ = BuiltinField::update(bit_field_, id);
}
References bit_field_, and v8::base::BitField< T, shift, size, U >::update().
Referenced by v8::internal::ReportBuiltinEventRecord::UpdateCodeMap().
SetInlineStacks()
void v8::internal::CodeEntry::SetInlineStacks (std::unordered_set< CodeEntry *, Hasher, Equals > inline_entries, std::unordered_map< int, std::vector< CodeEntryAndPosition >> inline_stacks)
Definition at line 185 of file profile-generator.cc.
                                                                          {
  EnsureRareData()->inline_entries_ = std::move(inline_entries);
  rare_data_->inline_stacks_ = std::move(inline_stacks);
}
References EnsureRareData(), v8::internal::CodeEntry::RareData::inline_entries_, and rare_data_.
Referenced by v8::internal::ProfilerListener::CodeCreateEvent().
unresolved_entry()
CodeEntry * v8::internal::CodeEntry::unresolved_entry () [static]
Definition at line 134 of file profile-generator.cc.
                                       {
  static base::LeakyObject<CodeEntry> kUnresolvedEntry(
      LogEventListener::CodeTag::kFunction, CodeEntry::kUnresolvedFunctionName,
      CodeEntry::kEmptyResourceName, LineAndColumn{}, nullptr, false,
      CodeEntry::CodeType::OTHER);
  return kUnresolvedEntry.get();
}
References v8::base::LeakyObject< T >::get(), kEmptyResourceName, v8::internal::torque::ls::kFunction, kUnresolvedFunctionName, and OTHER.
Referenced by v8::internal::ProfileNode::source_type(), and v8::internal::Symbolizer::SymbolizeTickSample().
Friends And Related Function Documentation
CodeEntryStorage
friend class CodeEntryStorage [friend]
Definition at line 212 of file profile-generator.h.
Member Data Documentation
bit_field_
std::uint32_t v8::internal::CodeEntry::bit_field_ [private]
Definition at line 253 of file profile-generator.h.
Referenced by builtin(), code_tag(), code_type_string(), event(), is_ref_counted(), is_shared_cross_origin(), mark_ref_counted(), and SetBuiltinId().
heap_object_location_
Address* v8::internal::CodeEntry::heap_object_location_ = nullptr [private]
Definition at line 263 of file profile-generator.h.
Referenced by heap_object_location_address(), and ~CodeEntry().
instruction_start_
Address v8::internal::CodeEntry::instruction_start_ = kNullAddress [private]
Definition at line 262 of file profile-generator.h.
Referenced by instruction_start(), and set_instruction_start().
kEmptyBailoutReason
const char *const v8::internal::CodeEntry::kEmptyBailoutReason = `` [static]
Definition at line 186 of file profile-generator.h.
Referenced by bailout_reason(), and v8::internal::ProfileNode::Print().
kEmptyResourceName
const char *const v8::internal::CodeEntry::kEmptyResourceName = `` [static]
Definition at line 185 of file profile-generator.h.
Referenced by v8::internal::ProfilerListener::CodeCreateEvent(), gc_entry(), idle_entry(), program_entry(), v8::internal::ProfilerListener::RegExpCodeCreateEvent(), root_entry(), and unresolved_entry().
kGarbageCollectorEntryName
const char *const v8::internal::CodeEntry::kGarbageCollectorEntryName = `(garbage collector)` [static]
Definition at line 191 of file profile-generator.h.
Referenced by gc_entry().
kIdleEntryName
const char *const v8::internal::CodeEntry::kIdleEntryName = `(idle)` [static]
Definition at line 190 of file profile-generator.h.
Referenced by idle_entry().
kNoDeoptReason
const char *const v8::internal::CodeEntry::kNoDeoptReason = `` [static]
Definition at line 187 of file profile-generator.h.
Referenced by clear_deopt_info().
kProgramEntryName
const char *const v8::internal::CodeEntry::kProgramEntryName = `(program)` [static]
Definition at line 189 of file profile-generator.h.
Referenced by program_entry().
kRootEntryName
const char *const v8::internal::CodeEntry::kRootEntryName = `(root)` [static]
Definition at line 195 of file profile-generator.h.
Referenced by root_entry().
kUnresolvedFunctionName
const char *const v8::internal::CodeEntry::kUnresolvedFunctionName = `(unresolved function)` [static]
Definition at line 194 of file profile-generator.h.
Referenced by unresolved_entry().
line_and_column_
LineAndColumn v8::internal::CodeEntry::line_and_column_ [private]
Definition at line 257 of file profile-generator.h.
Referenced by IsSameFunctionAs(), line_and_column(), and print().
line_info_
std::unique_ptr<SourcePositionTable> v8::internal::CodeEntry::line_info_ [private]
Definition at line 260 of file profile-generator.h.
Referenced by EstimatedSize(), GetInlineStack(), GetSourcePosition(), line_info(), and print().
name_
const char* v8::internal::CodeEntry::name_ [private]
Definition at line 255 of file profile-generator.h.
Referenced by GetHash(), IsSameFunctionAs(), name(), print(), and ReleaseStrings().
position_
int v8::internal::CodeEntry::position_ [private]
Definition at line 259 of file profile-generator.h.
Referenced by GetHash(), IsSameFunctionAs(), position(), print(), and set_position().
rare_data_
std::unique_ptr<RareData> v8::internal::CodeEntry::rare_data_ [private]
Definition at line 261 of file profile-generator.h.
Referenced by bailout_reason(), clear_deopt_info(), v8::internal::CodeEntryStorage::DecRef(), EnsureRareData(), EstimatedSize(), GetDeoptInfo(), GetInlineStack(), has_deopt_info(), print(), and SetInlineStacks().
ref_count_
std::atomic<std::size_t> v8::internal::CodeEntry::ref_count_ = {0} [private]
Definition at line 254 of file profile-generator.h.
Referenced by AddRef(), DecRef(), mark_ref_counted(), ReleaseStrings(), and ~CodeEntry().
resource_name_
const char* v8::internal::CodeEntry::resource_name_ [private]
Definition at line 256 of file profile-generator.h.
Referenced by GetHash(), IsSameFunctionAs(), print(), ReleaseStrings(), and resource_name().
script_id_
int v8::internal::CodeEntry::script_id_ [private]
Definition at line 258 of file profile-generator.h.
Referenced by GetDeoptInfo(), GetHash(), IsSameFunctionAs(), print(), script_id(), and set_script_id().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/profiler/profile-generator.h
/mnt/V8SourceCode/src/profiler/profile-generator-inl.h
/mnt/V8SourceCode/src/profiler/profile-generator.cc