v8::internal::maglev::RootConstant Class Reference
#include <maglev-ir.h>
Public Types
using OutputRegister = Register
Public Member Functions
RootConstant (uint64_t bitfield, RootIndex index)
bool ToBoolean (LocalIsolate *local_isolate) const
RootIndex index () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
void DoLoadToRegister (MaglevAssembler *, OutputRegister)
Handle< Object > DoReify (LocalIsolate *isolate) const
Private Types
using Base = FixedInputValueNodeT< 0, RootConstant >
Private Attributes
const RootIndex index_
Additional Inherited Members
Detailed Description
Definition at line 5612 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::RootConstant::Base = FixedInputValueNodeT<0, RootConstant> [private]
Definition at line 5613 of file maglev-ir.h.
OutputRegister
using v8::internal::maglev::RootConstant::OutputRegister = Register
Definition at line 5616 of file maglev-ir.h.
Constructor & Destructor Documentation
RootConstant()
v8::internal::maglev::RootConstant::RootConstant (uint64_t bitfield, RootIndex index) [inline], [explicit]
Definition at line 5618 of file maglev-ir.h.
      : Base(bitfield), index_(index) {}
Member Function Documentation
DoLoadToRegister()
void v8::internal::maglev::RootConstant::DoLoadToRegister (MaglevAssembler * , OutputRegister)
DoReify()
Handle< Object > v8::internal::maglev::RootConstant::DoReify (LocalIsolate * isolate) const
Definition at line 1240 of file maglev-ir.cc.
                                                                {
  return isolate->root_handle(index());
}
References index(), and v8::internal::LocalIsolate::root_handle().
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::RootConstant::GenerateCode (MaglevAssembler * , const ProcessingState &)
index()
RootIndex v8::internal::maglev::RootConstant::index () const [inline]
Definition at line 5623 of file maglev-ir.h.
{ return index_; }
References index_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfUndetectable(), DoReify(), v8::internal::maglev::ValueNode::GetStaticType(), v8::internal::maglev::MaglevGraphBuilder::GetTruncatedInt32ForToNumber(), PrintParams(), v8::internal::maglev::MaglevGraphBuilder::ReduceCallWithArrayLikeForArgumentsObject(), and v8::internal::maglev::MaglevGraphBuilder::TryGetFloat64Constant().
PrintParams()
void v8::internal::maglev::RootConstant::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 7962 of file maglev-ir.cc.
                                                                          {
  os << "(" << RootsTable::name(index()) << ")";
}
References index(), and v8::internal::RootsTable::name().
SetValueLocationConstraints()
void v8::internal::maglev::RootConstant::SetValueLocationConstraints ()
ToBoolean()
bool v8::internal::maglev::RootConstant::ToBoolean (LocalIsolate * local_isolate) const
Definition at line 353 of file maglev-ir.cc.
                                                              {
#ifdef DEBUG
  // (Ab)use static locals to call CheckToBooleanOnAllRoots once, on first
  // call to this function.
  static bool check_once = CheckToBooleanOnAllRoots(local_isolate);
  DCHECK(check_once);
#endif
  // ToBoolean is only supported for RO roots.
  DCHECK(RootsTable::IsReadOnly(index_));
  return RootToBoolean(index_);
}
References v8::internal::DCHECK(), index_, v8::internal::RootsTable::IsReadOnly(), and v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::RootToBoolean().
Member Data Documentation
index_
const RootIndex v8::internal::maglev::RootConstant::index_ [private]
Definition at line 5633 of file maglev-ir.h.
Referenced by index(), and ToBoolean().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc