v8::AsyncHooks Class Reference
#include <async-hooks-wrapper.h>
Public Member Functions
AsyncHooks (Isolate *isolate)
~AsyncHooks ()
async_id_t GetExecutionAsyncId () const
async_id_t GetTriggerAsyncId () const
Local< Object > CreateHook (const v8::FunctionCallbackInfo< v8::Value > &info)
Public Attributes
Persistent< FunctionTemplate > async_hook_ctor
Static Private Member Functions
static void ShellPromiseHook (PromiseHookType type, Local< Promise > promise, Local< Value > parent)
static void PromiseHookDispatch (PromiseHookType type, Local< Promise > promise, Local< Value > parent, const AsyncHooksWrap &wrap, AsyncHooks *hooks)
Private Attributes
std::vector< std::shared_ptr< AsyncHooksWrap > > async_wraps_
v8::Isolate * v8_isolate_
Persistent< ObjectTemplate > async_hooks_templ
Persistent< Private > async_id_symbol
Persistent< Private > trigger_id_symbol
std::stack< AsyncContext > asyncContexts
async_id_t current_async_id
bool skip_after_termination_ = false
Detailed Description
Definition at line 60 of file async-hooks-wrapper.h.
Constructor & Destructor Documentation
AsyncHooks()
v8::AsyncHooks::AsyncHooks (v8::Isolate * v8_isolate) [explicit]
Definition at line 54 of file async-hooks-wrapper.cc.
                                            : v8_isolate_(v8_isolate) {
  AsyncContext ctx;
  ctx.execution_async_id = 1;
  ctx.trigger_async_id = 0;
  asyncContexts.push(ctx);
  current_async_id = 1;
  HandleScope handle_scope(v8_isolate_);
  async_hook_ctor.Reset(v8_isolate_, FunctionTemplate::New(v8_isolate_));
  async_hook_ctor.Get(v8_isolate_)
      ->SetClassName(String::NewFromUtf8Literal(v8_isolate_, "AsyncHook"));
  async_hooks_templ.Reset(v8_isolate_,
                          async_hook_ctor.Get(v8_isolate_)->InstanceTemplate());
  async_hooks_templ.Get(v8_isolate_)->SetInternalFieldCount(1);
  async_hooks_templ.Get(v8_isolate_)
      ->Set(v8_isolate_, "enable",
            FunctionTemplate::New(v8_isolate_, EnableHook));
  async_hooks_templ.Get(v8_isolate_)
      ->Set(v8_isolate_, "disable",
            FunctionTemplate::New(v8_isolate_, DisableHook));
  async_id_symbol.Reset(v8_isolate_, Private::New(v8_isolate_));
  trigger_id_symbol.Reset(v8_isolate_, Private::New(v8_isolate_));
  v8_isolate_->SetPromiseHook(ShellPromiseHook);
}
References async_hook_ctor, async_hooks_templ, async_id_symbol, asyncContexts, current_async_id, v8::anonymous_namespace{async-hooks-wrapper.cc}::DisableHook(), v8::anonymous_namespace{async-hooks-wrapper.cc}::EnableHook(), v8::AsyncContext::execution_async_id, v8::FunctionTemplate::New(), v8::Private::New(), v8::String::NewFromUtf8Literal(), v8::Isolate::SetPromiseHook(), ShellPromiseHook(), v8::AsyncContext::trigger_async_id, trigger_id_symbol, and v8_isolate_.
 AsyncHooks()
v8::AsyncHooks::~AsyncHooks ()
Definition at line 83 of file async-hooks-wrapper.cc.
                        {
  v8_isolate_->SetPromiseHook(nullptr);
  async_wraps_.clear();
}
References async_wraps_, v8::Isolate::SetPromiseHook(), and v8_isolate_.
Member Function Documentation
CreateHook()
Local< Object > v8::AsyncHooks::CreateHook (const v8::FunctionCallbackInfo< v8::Value > & info)
Definition at line 126 of file async-hooks-wrapper.cc.
                                                 {
  DCHECK(i::ValidateCallbackInfo(info));
  v8::Isolate* v8_isolate = info.GetIsolate();
  EscapableHandleScope handle_scope(v8_isolate);
  if (v8_isolate->IsExecutionTerminating()) {
    return Local<Object>();
  }
  Local<Context> currentContext = v8_isolate->GetCurrentContext();
  if (info.Length() != 1 || !info[0]->IsObject()) {
    v8_isolate->ThrowError("Invalid arguments passed to createHook");
    return Local<Object>();
  }
  std::shared_ptr<AsyncHooksWrap> wrap =
      std::make_shared<AsyncHooksWrap>(v8_isolate);
  Local<Object> fn_obj = info[0].As<Object>();
  v8::TryCatch try_catch(v8_isolate);
#define SET_HOOK_FN(name) \
  MaybeLocal<Value> name##_maybe_func = fn_obj->Get(\
      currentContext, String::NewFromUtf8Literal(v8_isolate, #name)); \
  Local<Value> name##_func; \
  if (name##_maybe_func.ToLocal(&name##_func) && name##_func->IsFunction()) { \
    wrap->set_##name##_function(name##_func.As<Function>()); \
  } else { \
    try_catch.ReThrow(); \
  }
  SET_HOOK_FN(init);
  SET_HOOK_FN(before);
  SET_HOOK_FN(after);
  SET_HOOK_FN(promiseResolve);
#undef SET_HOOK_FN
  Local<Object> obj = async_hooks_templ.Get(v8_isolate)
                          ->NewInstance(currentContext)
                          .ToLocalChecked();
  i::DirectHandle<i::Object> managed = i::Managed<AsyncHooksWrap>::From(
      reinterpret_cast<i::Isolate*>(v8_isolate), sizeof(AsyncHooksWrap), wrap);
  obj->SetInternalField(0, Utils::ToLocal(managed));
  async_wraps_.push_back(std::move(wrap));
  return handle_scope.Escape(obj);
}
References async_hooks_templ, async_wraps_, DCHECK, v8::EscapableHandleScope::Escape(), v8::internal::Managed< CppType >::From(), v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::Isolate::IsExecutionTerminating(), v8::FunctionCallbackInfo< T >::Length(), SET_HOOK_FN, v8::Object::SetInternalField(), v8::Isolate::ThrowError(), and v8::internal::ValidateCallbackInfo().
Referenced by v8::Shell::AsyncHooksCreateHook().
GetExecutionAsyncId()
async_id_t v8::AsyncHooks::GetExecutionAsyncId () const
Definition at line 118 of file async-hooks-wrapper.cc.
                                                 {
  return asyncContexts.top().execution_async_id;
}
References asyncContexts.
GetTriggerAsyncId()
async_id_t v8::AsyncHooks::GetTriggerAsyncId () const
Definition at line 122 of file async-hooks-wrapper.cc.
                                               {
  return asyncContexts.top().trigger_async_id;
}
References asyncContexts.
PromiseHookDispatch()
void v8::AsyncHooks::PromiseHookDispatch (PromiseHookType type, Local< Promise > promise, Local< Value > parent, const AsyncHooksWrap & wrap, AsyncHooks * hooks) [static], [private]
Definition at line 261 of file async-hooks-wrapper.cc.
                                                        {
  if (!wrap.IsEnabled()) return;
  v8::Isolate* v8_isolate = hooks->v8_isolate_;
  if (v8_isolate->IsExecutionTerminating()) return;
  HandleScope handle_scope(v8_isolate);
  Local<Value> rcv = Undefined(v8_isolate);
  Local<Context> context = v8_isolate->GetCurrentContext();
  Local<Value> async_id =
      promise->GetPrivate(context, hooks->async_id_symbol.Get(v8_isolate))
          .ToLocalChecked();
  Local<Value> args[1] = {async_id};
  switch (type) {
    case PromiseHookType::kInit:
      if (!wrap.init_function().IsEmpty()) {
        Local<Value> initArgs[4] = {
            async_id, String::NewFromUtf8Literal(v8_isolate, "PROMISE"),
            promise
                ->GetPrivate(context, hooks->trigger_id_symbol.Get(v8_isolate))
                .ToLocalChecked(),
            promise};
        USE(wrap.init_function()->Call(context, rcv, 4, initArgs));
      }
      break;
    case PromiseHookType::kBefore:
      if (!wrap.before_function().IsEmpty()) {
        USE(wrap.before_function()->Call(context, rcv, 1, args));
      }
      break;
    case PromiseHookType::kAfter:
      if (!wrap.after_function().IsEmpty()) {
        USE(wrap.after_function()->Call(context, rcv, 1, args));
      }
      break;
    case PromiseHookType::kResolve:
      if (!wrap.promiseResolve_function().IsEmpty()) {
        USE(wrap.promiseResolve_function()->Call(context, rcv, 1, args));
      }
  }
}
References v8::AsyncHooksWrap::after_function(), v8::base::args, async_id_symbol, v8::AsyncHooksWrap::before_function(), v8::Isolate::GetCurrentContext(), v8::AsyncHooksWrap::init_function(), v8::AsyncHooksWrap::IsEnabled(), v8::Isolate::IsExecutionTerminating(), v8::kAfter, v8::kBefore, v8::kInit, v8::kResolve, v8::String::NewFromUtf8Literal(), v8::AsyncHooksWrap::promiseResolve_function(), trigger_id_symbol, v8::internal::tracing::type, v8::Undefined(), USE, and v8_isolate_.
Referenced by ShellPromiseHook().
ShellPromiseHook()
void v8::AsyncHooks::ShellPromiseHook (PromiseHookType type, Local< Promise > promise, Local< Value > parent) [static], [private]
Definition at line 177 of file async-hooks-wrapper.cc.
                                                       {
  v8::Isolate* v8_isolate = v8::Isolate::GetCurrent();
  AsyncHooks* hooks = PerIsolateData::Get(v8_isolate)->GetAsyncHooks();
  if (v8_isolate->IsExecutionTerminating() || hooks->skip_after_termination_) {
    hooks->skip_after_termination_ = true;
    return;
  }
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  HandleScope handle_scope(v8_isolate);
  i::DirectHandle<i::Object> exception;
  // Keep track of any previously thrown exception.
  if (i_isolate->has_exception()) {
    exception = direct_handle(i_isolate->exception(), i_isolate);
  }
  {
    TryCatch try_catch(v8_isolate);
    try_catch.SetVerbose(true);
    Local<Context> currentContext = v8_isolate->GetCurrentContext();
    DCHECK(!currentContext.IsEmpty());
    if (type == PromiseHookType::kInit) {
      ++hooks->current_async_id;
      Local<Integer> async_id =
          Integer::New(v8_isolate, hooks->current_async_id);
      CHECK(!promise
                 ->HasPrivate(currentContext,
                              hooks->async_id_symbol.Get(v8_isolate))
                 .ToChecked());
      promise->SetPrivate(currentContext,
                          hooks->async_id_symbol.Get(v8_isolate), async_id);
      if (parent->IsPromise()) {
        Local<Promise> parent_promise = parent.As<Promise>();
        Local<Value> parent_async_id =
            parent_promise
                ->GetPrivate(currentContext,
                             hooks->async_id_symbol.Get(v8_isolate))
                .ToLocalChecked();
        promise->SetPrivate(currentContext,
                            hooks->trigger_id_symbol.Get(v8_isolate),
                            parent_async_id);
      } else {
        CHECK(parent->IsUndefined());
        promise->SetPrivate(currentContext,
                            hooks->trigger_id_symbol.Get(v8_isolate),
                            Integer::New(v8_isolate, 0));
      }
    } else if (type == PromiseHookType::kBefore) {
      AsyncContext ctx;
      ctx.execution_async_id =
          promise
              ->GetPrivate(currentContext,
                           hooks->async_id_symbol.Get(v8_isolate))
              .ToLocalChecked()
              .As<Integer>()
              ->Value();
      ctx.trigger_async_id =
          promise
              ->GetPrivate(currentContext,
                           hooks->trigger_id_symbol.Get(v8_isolate))
              .ToLocalChecked()
              .As<Integer>()
              ->Value();
      hooks->asyncContexts.push(ctx);
    } else if (type == PromiseHookType::kAfter) {
      hooks->asyncContexts.pop();
    }
    if (!i::StackLimitCheck{i_isolate}.HasOverflowed()) {
      for (size_t i = 0; i < hooks->async_wraps_.size(); ++i) {
        std::shared_ptr<AsyncHooksWrap> wrap = hooks->async_wraps_[i];
        PromiseHookDispatch(type, promise, parent, *wrap, hooks);
        if (try_catch.HasCaught()) break;
      }
      if (try_catch.HasCaught()) Shell::ReportException(v8_isolate, try_catch);
    }
  }
  if (!exception.is_null()) {
    i_isolate->set_exception(*exception);
  }
}
References v8::Local< T >::As(), async_id_symbol, async_wraps_, asyncContexts, CHECK, current_async_id, DCHECK, v8::internal::direct_handle(), v8::internal::Isolate::exception(), v8::AsyncContext::execution_async_id, v8::PerIsolateData::Get(), v8::PerIsolateData::GetAsyncHooks(), v8::Isolate::GetCurrent(), v8::Isolate::GetCurrentContext(), v8::internal::Isolate::has_exception(), v8::TryCatch::HasCaught(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::DirectHandle< T >::is_null(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8::Isolate::IsExecutionTerminating(), v8::kAfter, v8::kBefore, v8::kInit, v8::Integer::New(), PromiseHookDispatch(), v8::Shell::ReportException(), v8::internal::Isolate::set_exception(), v8::TryCatch::SetVerbose(), skip_after_termination_, v8::AsyncContext::trigger_async_id, trigger_id_symbol, and v8::internal::tracing::type.
Referenced by AsyncHooks().
Member Data Documentation
async_hook_ctor
Persistent<FunctionTemplate> v8::AsyncHooks::async_hook_ctor
Definition at line 70 of file async-hooks-wrapper.h.
Referenced by AsyncHooks(), and v8::anonymous_namespace{async-hooks-wrapper.cc}::UnwrapHook().
async_hooks_templ
Persistent<ObjectTemplate> v8::AsyncHooks::async_hooks_templ [private]
Definition at line 75 of file async-hooks-wrapper.h.
Referenced by AsyncHooks(), and CreateHook().
async_id_symbol
Persistent<Private> v8::AsyncHooks::async_id_symbol [private]
Definition at line 76 of file async-hooks-wrapper.h.
Referenced by AsyncHooks(), PromiseHookDispatch(), and ShellPromiseHook().
async_wraps_
std::vector<std::shared_ptr<AsyncHooksWrap> > v8::AsyncHooks::async_wraps_ [private]
Definition at line 73 of file async-hooks-wrapper.h.
Referenced by CreateHook(), ShellPromiseHook(), and ~AsyncHooks().
asyncContexts
std::stack<AsyncContext> v8::AsyncHooks::asyncContexts [private]
Definition at line 86 of file async-hooks-wrapper.h.
Referenced by AsyncHooks(), GetExecutionAsyncId(), GetTriggerAsyncId(), and ShellPromiseHook().
current_async_id
async_id_t v8::AsyncHooks::current_async_id [private]
Definition at line 87 of file async-hooks-wrapper.h.
Referenced by AsyncHooks(), and ShellPromiseHook().
skip_after_termination_
bool v8::AsyncHooks::skip_after_termination_ = false [private]
Definition at line 90 of file async-hooks-wrapper.h.
Referenced by ShellPromiseHook().
trigger_id_symbol
Persistent<Private> v8::AsyncHooks::trigger_id_symbol [private]
Definition at line 77 of file async-hooks-wrapper.h.
Referenced by AsyncHooks(), PromiseHookDispatch(), and ShellPromiseHook().
v8_isolate_
v8::Isolate* v8::AsyncHooks::v8_isolate_ [private]
Definition at line 74 of file async-hooks-wrapper.h.
Referenced by AsyncHooks(), PromiseHookDispatch(), and ~AsyncHooks().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/d8/async-hooks-wrapper.h
/mnt/V8SourceCode/src/d8/async-hooks-wrapper.cc