v8::internal::wasm::LiftoffVarState Class Reference
#include <liftoff-varstate.h>
Public Types
enum Location : uint8_t { kStack
, kRegister
, kIntConst
 }
Public Member Functions
LiftoffVarState (ValueKind kind, int offset)
LiftoffVarState (ValueKind kind, LiftoffRegister r, int offset)
LiftoffVarState (ValueKind kind, int32_t i32_const, int offset)
bool is_stack () const
bool is_gp_reg () const
bool is_fp_reg () const
bool is_gp_reg_pair () const
bool is_fp_reg_pair () const
bool is_reg () const
bool is_const () const
ValueKind kind () const
Location loc () const
int32_t i32_const () const
WasmValue constant () const
int offset () const
void set_offset (int offset)
Register gp_reg () const
DoubleRegister fp_reg () const
LiftoffRegister reg () const
RegClass reg_class () const
void MakeStack ()
void MakeRegister (LiftoffRegister r)
void MakeConstant (int32_t i32_const)
void Copy (LiftoffVarState src)
Private Attributes
Location loc_
ValueKind kind_
xx xx xx xx xx xx xx xx xx
union {
 LiftoffRegister reg_
 int32_t i32_const_
};
int spill_offset_
Detailed Description
Definition at line 13 of file liftoff-varstate.h.
Member Enumeration Documentation
Location
enum v8::internal::wasm::LiftoffVarState::Location : uint8_t
Enumerator
kStack
kRegister
kIntConst
Definition at line 15 of file liftoff-varstate.h.
: uint8_t { kStack, kRegister, kIntConst };
Constructor & Destructor Documentation
LiftoffVarState() [1/3]
v8::internal::wasm::LiftoffVarState::LiftoffVarState (ValueKind kind, int offset) [inline]
Definition at line 17 of file liftoff-varstate.h.
      : loc_(kStack), kind_(kind), spill_offset_(offset) {
    DCHECK_LE(0, offset);
  }
References DCHECK_LE, and offset().
LiftoffVarState() [2/3]
v8::internal::wasm::LiftoffVarState::LiftoffVarState (ValueKind kind, LiftoffRegister r, int offset) [inline]
Definition at line 21 of file liftoff-varstate.h.
      : loc_(kRegister), kind_(kind), reg_(r), spill_offset_(offset) {
    DCHECK_EQ(r.reg_class(), reg_class_for(kind));
    DCHECK_LE(0, offset);
  }
References DCHECK_EQ, DCHECK_LE, kind(), offset(), v8::internal::wasm::LiftoffRegister::reg_class(), and v8::internal::wasm::reg_class_for().
LiftoffVarState() [3/3]
v8::internal::wasm::LiftoffVarState::LiftoffVarState (ValueKind kind, int32_t i32_const, int offset) [inline]
Definition at line 26 of file liftoff-varstate.h.
      : loc_(kIntConst),
        kind_(kind),
        i32_const_(i32_const),
        spill_offset_(offset) {
    DCHECK(kind_ == kI32 || kind_ == kI64);
    DCHECK_LE(0, offset);
  }
References v8::internal::DCHECK(), DCHECK_LE, v8::internal::kI32, v8::internal::kI64, kind_, and offset().
Member Function Documentation
constant()
WasmValue v8::internal::wasm::LiftoffVarState::constant () const [inline]
Definition at line 52 of file liftoff-varstate.h.
                             {
    DCHECK(kind_ == kI32 || kind_ == kI64);
    DCHECK_EQ(loc_, kIntConst);
    return kind_ == kI32 ? WasmValue(i32_const_)
                         : WasmValue(int64_t{i32_const_});
  }
References v8::internal::DCHECK(), DCHECK_EQ, i32_const_, v8::internal::kI32, v8::internal::kI64, kind_, kIntConst, and loc_.
Referenced by v8::internal::wasm::LiftoffAssembler::LoadI64HalfIntoRegister(), v8::internal::wasm::LiftoffAssembler::LoadToFixedRegister(), v8::internal::wasm::LiftoffAssembler::Spill(), and v8::internal::wasm::ParallelMove::TransferToStack().
Copy()
void v8::internal::wasm::LiftoffVarState::Copy (LiftoffVarState src) [inline]
Definition at line 91 of file liftoff-varstate.h.
                                 {
    loc_ = src.loc();
    kind_ = src.kind();
    if (loc_ == kRegister) {
      reg_ = src.reg();
    } else if (loc_ == kIntConst) {
      i32_const_ = src.i32_const();
    }
  }
References i32_const(), i32_const_, kind(), kind_, kIntConst, kRegister, loc(), loc_, reg(), and reg_.
fp_reg()
DoubleRegister v8::internal::wasm::LiftoffVarState::fp_reg () const [inline]
Definition at line 69 of file liftoff-varstate.h.
{ return reg().fp(); }
References v8::internal::wasm::LiftoffRegister::fp(), and reg().
gp_reg()
Register v8::internal::wasm::LiftoffVarState::gp_reg () const [inline]
Definition at line 68 of file liftoff-varstate.h.
{ return reg().gp(); }
References v8::internal::wasm::LiftoffRegister::gp(), and reg().
i32_const()
int32_t v8::internal::wasm::LiftoffVarState::i32_const () const [inline]
Definition at line 48 of file liftoff-varstate.h.
                            {
    DCHECK_EQ(loc_, kIntConst);
    return i32_const_;
  }
References DCHECK_EQ, i32_const_, kIntConst, and loc_.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallIndirectImpl(), v8::internal::wasm::LiftoffStackSlots::Construct(), Copy(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitBinOpImm(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitSimdShiftOp(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetCurrentDebugSideTableEntries(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::IndexStaticallyInBounds(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::IndexToVarStateSaturating(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::JumpIfFalse(), v8::internal::wasm::ParallelMove::LoadI64HalfIntoRegister(), v8::internal::wasm::ParallelMove::LoadIntoRegister(), v8::internal::wasm::liftoff::LoadToRegister(), MakeConstant(), v8::internal::wasm::operator<<(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::PopIndexToVarState(), v8::internal::wasm::liftoff::StoreToMemory(), and v8::internal::wasm::ParallelMove::Transfer().
is_const()
bool v8::internal::wasm::LiftoffVarState::is_const () const [inline]
Definition at line 41 of file liftoff-varstate.h.
{ return loc_ == kIntConst; }
References kIntConst, and loc_.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallIndirectImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitBinOpImm(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitSimdShiftOp(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::IndexStaticallyInBounds(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::IndexToVarStateSaturating(), v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::InitMergeRegion(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::JumpIfFalse(), v8::internal::wasm::LiftoffAssembler::LoadI64HalfIntoRegister(), v8::internal::wasm::ParallelMove::LoadIntoRegister(), v8::internal::wasm::LiftoffAssembler::LoadToFixedRegister(), v8::internal::wasm::liftoff::LoadToRegister(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::PopIndexToVarState(), v8::internal::wasm::liftoff::StoreToMemory(), and v8::internal::wasm::ParallelMove::Transfer().
is_fp_reg()
bool v8::internal::wasm::LiftoffVarState::is_fp_reg () const [inline]
Definition at line 37 of file liftoff-varstate.h.
{ return loc_ == kRegister && reg_.is_fp(); }
References v8::internal::wasm::LiftoffRegister::is_fp(), kRegister, loc_, and reg_.
is_fp_reg_pair()
bool v8::internal::wasm::LiftoffVarState::is_fp_reg_pair () const [inline]
Definition at line 39 of file liftoff-varstate.h.
{ return loc_ == kRegister && reg_.is_fp_pair(); }
References v8::internal::wasm::LiftoffRegister::is_fp_pair(), kRegister, loc_, and reg_.
is_gp_reg()
bool v8::internal::wasm::LiftoffVarState::is_gp_reg () const [inline]
Definition at line 36 of file liftoff-varstate.h.
{ return loc_ == kRegister && reg_.is_gp(); }
References v8::internal::wasm::LiftoffRegister::is_gp(), kRegister, loc_, and reg_.
is_gp_reg_pair()
bool v8::internal::wasm::LiftoffVarState::is_gp_reg_pair () const [inline]
Definition at line 38 of file liftoff-varstate.h.
{ return loc_ == kRegister && reg_.is_gp_pair(); }
References v8::internal::wasm::LiftoffRegister::is_gp_pair(), kRegister, loc_, and reg_.
is_reg()
bool v8::internal::wasm::LiftoffVarState::is_reg () const [inline]
Definition at line 40 of file liftoff-varstate.h.
{ return loc_ == kRegister; }
References kRegister, and loc_.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::IndexToVarStateSaturating(), v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::InitMergeRegion(), v8::internal::wasm::LiftoffAssembler::LoadI64HalfIntoRegister(), v8::internal::wasm::ParallelMove::LoadIntoRegister(), v8::internal::wasm::liftoff::LoadToRegister(), v8::internal::wasm::LiftoffAssembler::LoadToRegister(), v8::internal::wasm::LiftoffAssembler::LoadToRegister_Slow(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LocalSetFromStackSlot(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::MemoryInit(), v8::internal::wasm::LiftoffAssembler::MoveToReturnLocations(), v8::internal::wasm::LiftoffAssembler::PeekToRegister(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::PopIndexToVarState(), v8::internal::wasm::LiftoffAssembler::PopToFixedRegister(), v8::internal::wasm::LiftoffAssembler::PopVarState(), v8::internal::wasm::LiftoffAssembler::SpillAllRegisters(), v8::internal::wasm::liftoff::StoreToMemory(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TableInit(), and v8::internal::wasm::ParallelMove::Transfer().
is_stack()
bool v8::internal::wasm::LiftoffVarState::is_stack () const [inline]
Definition at line 35 of file liftoff-varstate.h.
{ return loc_ == kStack; }
References kStack, and loc_.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CatchCase(), v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::InitMergeRegion(), v8::internal::wasm::LiftoffAssembler::LoadI64HalfIntoRegister(), v8::internal::wasm::ParallelMove::LoadIntoRegister(), v8::internal::wasm::LiftoffAssembler::LoadToFixedRegister(), v8::internal::wasm::liftoff::LoadToRegister(), v8::internal::wasm::liftoff::StoreToMemory(), and v8::internal::wasm::ParallelMove::Transfer().
kind()
ValueKind v8::internal::wasm::LiftoffVarState::kind () const [inline]
Definition at line 43 of file liftoff-varstate.h.
{ return kind_; }
References kind_.
Referenced by v8::internal::wasm::LiftoffStackSlots::Construct(), Copy(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetCurrentDebugSideTableEntries(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::IndexToVarStateSaturating(), v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::InitMergeRegion(), LiftoffVarState(), v8::internal::wasm::ParallelMove::LoadI64HalfIntoRegister(), v8::internal::wasm::ParallelMove::LoadIntoRegister(), v8::internal::wasm::LiftoffAssembler::LoadToFixedRegister(), v8::internal::wasm::LiftoffAssembler::LoadToModifiableRegister(), v8::internal::wasm::liftoff::LoadToRegister(), v8::internal::wasm::LiftoffAssembler::LoadToRegister_Slow(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LocalSetFromStackSlot(), v8::internal::wasm::LiftoffAssembler::MoveToReturnLocations(), v8::internal::wasm::operator<<(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::PopIndexToVarState(), v8::internal::wasm::LiftoffAssembler::PopToFixedRegister(), v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::PrepareStackTransfers(), v8::internal::wasm::LiftoffStackSlots::SlotSizeInBytes(), v8::internal::wasm::LiftoffAssembler::Spill(), v8::internal::wasm::LiftoffAssembler::SpillAllRegisters(), v8::internal::wasm::liftoff::StoreToMemory(), v8::internal::wasm::ParallelMove::Transfer(), and v8::internal::wasm::ParallelMove::TransferToStack().
loc()
Location v8::internal::wasm::LiftoffVarState::loc () const [inline]
Definition at line 45 of file liftoff-varstate.h.
{ return loc_; }
References loc_.
Referenced by v8::internal::wasm::LiftoffStackSlots::Construct(), Copy(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetCurrentDebugSideTableEntries(), v8::internal::wasm::ParallelMove::LoadI64HalfIntoRegister(), v8::internal::wasm::operator<<(), v8::internal::wasm::LiftoffAssembler::Spill(), and v8::internal::wasm::ParallelMove::TransferToStack().
MakeConstant()
void v8::internal::wasm::LiftoffVarState::MakeConstant (int32_t i32_const) [inline]
Definition at line 83 of file liftoff-varstate.h.
                                       {
    DCHECK(kind_ == kI32 || kind_ == kI64);
    loc_ = kIntConst;
    i32_const_ = i32_const;
  }
References v8::internal::DCHECK(), i32_const(), i32_const_, v8::internal::kI32, v8::internal::kI64, kind_, kIntConst, and loc_.
MakeRegister()
void v8::internal::wasm::LiftoffVarState::MakeRegister (LiftoffRegister r) [inline]
Definition at line 78 of file liftoff-varstate.h.
                                       {
    loc_ = kRegister;
    reg_ = r;
  }
References kRegister, loc_, and reg_.
Referenced by v8::internal::wasm::LiftoffAssembler::PeekToRegister().
MakeStack()
void v8::internal::wasm::LiftoffVarState::MakeStack () [inline]
Definition at line 76 of file liftoff-varstate.h.
{ loc_ = kStack; }
References kStack, and loc_.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LocalSetFromStackSlot(), v8::internal::wasm::LiftoffAssembler::Spill(), and v8::internal::wasm::LiftoffAssembler::SpillAllRegisters().
offset()
int v8::internal::wasm::LiftoffVarState::offset () const [inline]
Definition at line 59 of file liftoff-varstate.h.
                     {
    V8_ASSUME(spill_offset_ >= 0);
    return spill_offset_;
  }
References spill_offset_, and V8_ASSUME.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CatchCase(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetCurrentDebugSideTableEntries(), v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::GetSafepointIndexForStackSlot(), v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::InitMergeRegion(), LiftoffVarState(), v8::internal::wasm::ParallelMove::LoadI64HalfIntoRegister(), v8::internal::wasm::LiftoffAssembler::LoadI64HalfIntoRegister(), v8::internal::wasm::ParallelMove::LoadIntoRegister(), v8::internal::wasm::LiftoffAssembler::LoadToFixedRegister(), v8::internal::wasm::liftoff::LoadToRegister(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LocalSetFromStackSlot(), v8::internal::wasm::LiftoffAssembler::MergeIntoNewState(), v8::internal::wasm::operator<<(), v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::PrepareStackTransfers(), set_offset(), v8::internal::wasm::LiftoffAssembler::Spill(), v8::internal::wasm::LiftoffAssembler::SpillAllRegisters(), v8::internal::wasm::liftoff::StoreToMemory(), v8::internal::wasm::ParallelMove::Transfer(), and v8::internal::wasm::ParallelMove::TransferToStack().
reg()
LiftoffRegister v8::internal::wasm::LiftoffVarState::reg () const [inline]
Definition at line 70 of file liftoff-varstate.h.
                              {
    DCHECK_EQ(loc_, kRegister);
    return reg_;
  }
References DCHECK_EQ, kRegister, loc_, and reg_.
Referenced by v8::internal::wasm::LiftoffStackSlots::Construct(), Copy(), fp_reg(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetCurrentDebugSideTableEntries(), gp_reg(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::IndexToVarStateSaturating(), v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::InitMergeRegion(), v8::internal::wasm::ParallelMove::LoadI64HalfIntoRegister(), v8::internal::wasm::LiftoffAssembler::LoadI64HalfIntoRegister(), v8::internal::wasm::ParallelMove::LoadIntoRegister(), v8::internal::wasm::liftoff::LoadToRegister(), v8::internal::wasm::LiftoffAssembler::LoadToRegister(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LocalSetFromStackSlot(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::MemoryInit(), v8::internal::wasm::LiftoffAssembler::MoveToReturnLocations(), v8::internal::wasm::operator<<(), v8::internal::wasm::LiftoffAssembler::PeekToRegister(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::PopIndexToVarState(), v8::internal::wasm::LiftoffAssembler::PopToFixedRegister(), v8::internal::wasm::LiftoffAssembler::PopVarState(), reg_class(), v8::internal::wasm::LiftoffAssembler::Spill(), v8::internal::wasm::LiftoffAssembler::SpillAllRegisters(), v8::internal::wasm::liftoff::StoreToMemory(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TableInit(), v8::internal::wasm::ParallelMove::Transfer(), and v8::internal::wasm::ParallelMove::TransferToStack().
reg_class()
RegClass v8::internal::wasm::LiftoffVarState::reg_class () const [inline]
Definition at line 74 of file liftoff-varstate.h.
{ return reg().reg_class(); }
References reg(), and v8::internal::wasm::LiftoffRegister::reg_class().
Referenced by v8::internal::wasm::ParallelMove::LoadIntoRegister().
set_offset()
void v8::internal::wasm::LiftoffVarState::set_offset (int offset) [inline]
Definition at line 63 of file liftoff-varstate.h.
                              {
    DCHECK_LE(0, spill_offset_);
    spill_offset_ = offset;
  }
References DCHECK_LE, offset(), and spill_offset_.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::InitMergeRegion().
Member Data Documentation
union { ... } [private]
i32_const_
int32_t v8::internal::wasm::LiftoffVarState::i32_const_
Definition at line 109 of file liftoff-varstate.h.
Referenced by constant(), Copy(), i32_const(), and MakeConstant().
kind_
ValueKind v8::internal::wasm::LiftoffVarState::kind_ [private]
Definition at line 105 of file liftoff-varstate.h.
Referenced by constant(), Copy(), kind(), LiftoffVarState(), and MakeConstant().
loc_
Location v8::internal::wasm::LiftoffVarState::loc_ [private]
Definition at line 102 of file liftoff-varstate.h.
Referenced by constant(), Copy(), i32_const(), is_const(), is_fp_reg(), is_fp_reg_pair(), is_gp_reg(), is_gp_reg_pair(), is_reg(), is_stack(), loc(), MakeConstant(), MakeRegister(), MakeStack(), and reg().
reg_
LiftoffRegister v8::internal::wasm::LiftoffVarState::reg_
Definition at line 108 of file liftoff-varstate.h.
Referenced by Copy(), is_fp_reg(), is_fp_reg_pair(), is_gp_reg(), is_gp_reg_pair(), MakeRegister(), and reg().
spill_offset_
int v8::internal::wasm::LiftoffVarState::spill_offset_ [private]
Definition at line 111 of file liftoff-varstate.h.
Referenced by offset(), and set_offset().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/baseline/liftoff-varstate.h