v8::internal::StatsTable Class Reference
#include <counters.h>
Public Member Functions
StatsTable (const StatsTable &)=delete
StatsTable & operator= (const StatsTable &)=delete
void SetCounterFunction (CounterLookupCallback f)
void SetCreateHistogramFunction (CreateHistogramCallback f)
void SetAddHistogramSampleFunction (AddHistogramSampleCallback f)
bool HasCounterFunction () const
int * FindLocation (const char *name)
void * CreateHistogram (const char *name, int min, int max, size_t buckets)
void AddHistogramSample (void *histogram, int sample)
Private Member Functions
StatsTable (Counters *counters)
Private Attributes
CounterLookupCallback lookup_function_
CreateHistogramCallback create_histogram_function_
AddHistogramSampleCallback add_histogram_sample_function_
Friends
class Counters
Detailed Description
Definition at line 31 of file counters.h.
Constructor & Destructor Documentation
StatsTable() [1/2]
v8::internal::StatsTable::StatsTable (const StatsTable &) [delete]
StatsTable() [2/2]
v8::internal::StatsTable::StatsTable (Counters * counters) [explicit], [private]
Definition at line 19 of file counters.cc.
    : lookup_function_(nullptr),
      create_histogram_function_(nullptr),
      add_histogram_sample_function_(nullptr) {}
Member Function Documentation
AddHistogramSample()
void v8::internal::StatsTable::AddHistogramSample (void * histogram, int sample) [inline]
Definition at line 77 of file counters.h.
                                                       {
    if (!add_histogram_sample_function_) return;
    return add_histogram_sample_function_(histogram, sample);
  }
References add_histogram_sample_function_.
Referenced by v8::internal::Counters::AddHistogramSample().
CreateHistogram()
void* v8::internal::StatsTable::CreateHistogram (const char * name, int min, int max, size_t buckets) [inline]
Definition at line 70 of file counters.h.
                                                                            {
    if (!create_histogram_function_) return nullptr;
    return create_histogram_function_(name, min, max, buckets);
  }
References create_histogram_function_, and v8::internal::name.
Referenced by v8::internal::Counters::CreateHistogram().
FindLocation()
int* v8::internal::StatsTable::FindLocation (const char * name) [inline]
Definition at line 60 of file counters.h.
                                      {
    if (!lookup_function_) return nullptr;
    return lookup_function_(name);
  }
References lookup_function_, and v8::internal::name.
Referenced by v8::internal::Counters::FindLocation().
HasCounterFunction()
bool v8::internal::StatsTable::HasCounterFunction () const [inline]
Definition at line 52 of file counters.h.
{ return lookup_function_ != nullptr; }
References lookup_function_.
operator=()
StatsTable& v8::internal::StatsTable::operator= (const StatsTable &) [delete]
SetAddHistogramSampleFunction()
void v8::internal::StatsTable::SetAddHistogramSampleFunction (AddHistogramSampleCallback f) [inline]
Definition at line 48 of file counters.h.
                                                                   {
    add_histogram_sample_function_ = f;
  }
References add_histogram_sample_function_.
Referenced by v8::internal::Counters::SetAddHistogramSampleFunction().
SetCounterFunction()
void v8::internal::StatsTable::SetCounterFunction (CounterLookupCallback f)
Definition at line 24 of file counters.cc.
                                                           {
  lookup_function_ = f;
}
References lookup_function_.
Referenced by v8::internal::Counters::ResetCounterFunction().
SetCreateHistogramFunction()
void v8::internal::StatsTable::SetCreateHistogramFunction (CreateHistogramCallback f) [inline]
Definition at line 42 of file counters.h.
                                                             {
    create_histogram_function_ = f;
  }
References create_histogram_function_.
Referenced by v8::internal::Counters::ResetCreateHistogramFunction().
Friends And Related Function Documentation
Counters
friend class Counters [friend]
Definition at line 83 of file counters.h.
Member Data Documentation
add_histogram_sample_function_
AddHistogramSampleCallback v8::internal::StatsTable::add_histogram_sample_function_ [private]
Definition at line 89 of file counters.h.
Referenced by AddHistogramSample(), and SetAddHistogramSampleFunction().
create_histogram_function_
CreateHistogramCallback v8::internal::StatsTable::create_histogram_function_ [private]
Definition at line 88 of file counters.h.
Referenced by CreateHistogram(), and SetCreateHistogramFunction().
lookup_function_
CounterLookupCallback v8::internal::StatsTable::lookup_function_ [private]
Definition at line 87 of file counters.h.
Referenced by FindLocation(), HasCounterFunction(), and SetCounterFunction().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/logging/counters.h
/mnt/V8SourceCode/src/logging/counters.cc