v8::internal::BuiltinContinuationFrameInfo Class Reference
#include <frames.h>
Public Member Functions
bool frame_has_result_stack_slot () const
uint32_t translated_stack_parameter_count () const
uint32_t stack_parameter_count () const
uint32_t frame_size_in_bytes () const
uint32_t frame_size_in_bytes_above_fp () const
Static Public Member Functions
static BuiltinContinuationFrameInfo Precise (int translation_height, const CallInterfaceDescriptor &continuation_descriptor, const RegisterConfiguration *register_config, bool is_topmost, DeoptimizeKind deopt_kind, BuiltinContinuationMode continuation_mode)
static BuiltinContinuationFrameInfo Conservative (int parameters_count, const CallInterfaceDescriptor &continuation_descriptor, const RegisterConfiguration *register_config)
Private Member Functions
BuiltinContinuationFrameInfo (int translation_height, const CallInterfaceDescriptor &continuation_descriptor, const RegisterConfiguration *register_config, bool is_topmost, DeoptimizeKind deopt_kind, BuiltinContinuationMode continuation_mode, FrameInfoKind frame_info_kind)
Private Attributes
bool frame_has_result_stack_slot_
uint32_t translated_stack_parameter_count_
uint32_t stack_parameter_count_
uint32_t frame_size_in_bytes_
uint32_t frame_size_in_bytes_above_fp_
Detailed Description
Definition at line 1977 of file frames.h.
Constructor & Destructor Documentation
BuiltinContinuationFrameInfo()
v8::internal::BuiltinContinuationFrameInfo::BuiltinContinuationFrameInfo (int translation_height, const CallInterfaceDescriptor & continuation_descriptor, const RegisterConfiguration * register_config, bool is_topmost, DeoptimizeKind deopt_kind, BuiltinContinuationMode continuation_mode, FrameInfoKind frame_info_kind) [private]
Definition at line 4280 of file frames.cc.
                                   {
  const bool is_conservative = frame_info_kind == FrameInfoKind::kConservative;
  // Note: This is according to the Translation's notion of 'parameters' which
  // differs to that of the SharedFunctionInfo, e.g. by including the receiver.
  const int parameters_count = translation_height;
  frame_has_result_stack_slot_ =
      !is_topmost || deopt_kind == DeoptimizeKind::kLazy;
  const int result_slot_count =
      (frame_has_result_stack_slot_ || is_conservative) ? 1 : 0;
  const int exception_slot_count =
      (BuiltinContinuationModeIsWithCatch(continuation_mode) || is_conservative)
          ? 1
          : 0;
  const int allocatable_register_count =
      register_config->num_allocatable_general_registers();
  const int padding_slot_count =
      BuiltinContinuationFrameConstants::PaddingSlotCount(
          allocatable_register_count);
  const int register_parameter_count =
      continuation_descriptor.GetRegisterParameterCount();
  translated_stack_parameter_count_ =
      parameters_count - register_parameter_count;
  stack_parameter_count_ = translated_stack_parameter_count_ +
                           result_slot_count + exception_slot_count;
  const int stack_param_pad_count =
      ArgumentPaddingSlots(stack_parameter_count_);
  // If the builtins frame appears to be topmost we should ensure that the
  // value of result register is preserved during continuation execution.
  // We do this here by "pushing" the result of callback function to the
  // top of the reconstructed stack and popping it in
  // {Builtin::kNotifyDeoptimized}.
  static constexpr int kTopOfStackPadding = TopOfStackRegisterPaddingSlots();
  static constexpr int kTheResult = 1;
  const int push_result_count =
      (is_topmost || is_conservative) ? kTheResult + kTopOfStackPadding : 0;
  frame_size_in_bytes_ =
      kSystemPointerSize * (stack_parameter_count_ + stack_param_pad_count +
                            allocatable_register_count + padding_slot_count +
                            push_result_count) +
      BuiltinContinuationFrameConstants::kFixedFrameSize;
  frame_size_in_bytes_above_fp_ =
      kSystemPointerSize * (allocatable_register_count + padding_slot_count +
                            push_result_count) +
      (BuiltinContinuationFrameConstants::kFixedFrameSize -
       BuiltinContinuationFrameConstants::kFixedFrameSizeAboveFp);
}
References v8::internal::ArgumentPaddingSlots(), v8::internal::anonymous_namespace{frames.cc}::BuiltinContinuationModeIsWithCatch(), v8::internal::CallInterfaceDescriptor::GetRegisterParameterCount(), v8::internal::kConservative, v8::internal::TypedFrameConstants::kFixedFrameSize, v8::internal::CommonFrameConstants::kFixedFrameSizeAboveFp, v8::internal::kLazy, v8::internal::kSystemPointerSize, v8::internal::RegisterConfiguration::num_allocatable_general_registers(), v8::internal::BuiltinContinuationFrameConstants::PaddingSlotCount(), and v8::internal::anonymous_namespace{frames.cc}::TopOfStackRegisterPaddingSlots().
Member Function Documentation
Conservative()
static BuiltinContinuationFrameInfo v8::internal::BuiltinContinuationFrameInfo::Conservative (int parameters_count, const CallInterfaceDescriptor & continuation_descriptor, const RegisterConfiguration * register_config) [inline], [static]
Definition at line 1993 of file frames.h.
                                                    {
    // It doesn't matter what we pass as is_topmost, deopt_kind and
    // continuation_mode; these values are ignored in conservative mode.
    return {parameters_count,
            continuation_descriptor,
            register_config,
            false,
            DeoptimizeKind::kEager,
            BuiltinContinuationMode::STUB,
            FrameInfoKind::kConservative};
  }
References v8::internal::kConservative, v8::internal::kEager, and v8::internal::STUB.
Referenced by v8::internal::maglev::MaxCallDepthProcessor::ConservativeFrameSize(), and v8::internal::compiler::anonymous_namespace{instruction.cc}::GetConservativeFrameSizeInBytes().
frame_has_result_stack_slot()
bool v8::internal::BuiltinContinuationFrameInfo::frame_has_result_stack_slot () const [inline]
Definition at line 2008 of file frames.h.
                                           {
    return frame_has_result_stack_slot_;
  }
References frame_has_result_stack_slot_.
Referenced by v8::internal::Deoptimizer::DoComputeBuiltinContinuation().
frame_size_in_bytes()
uint32_t v8::internal::BuiltinContinuationFrameInfo::frame_size_in_bytes () const [inline]
Definition at line 2015 of file frames.h.
{ return frame_size_in_bytes_; }
References frame_size_in_bytes_.
Referenced by v8::internal::Deoptimizer::DoComputeBuiltinContinuation().
frame_size_in_bytes_above_fp()
uint32_t v8::internal::BuiltinContinuationFrameInfo::frame_size_in_bytes_above_fp () const [inline]
Definition at line 2016 of file frames.h.
                                                {
    return frame_size_in_bytes_above_fp_;
  }
References frame_size_in_bytes_above_fp_.
Referenced by v8::internal::Deoptimizer::DoComputeBuiltinContinuation().
Precise()
static BuiltinContinuationFrameInfo v8::internal::BuiltinContinuationFrameInfo::Precise (int translation_height, const CallInterfaceDescriptor & continuation_descriptor, const RegisterConfiguration * register_config, bool is_topmost, DeoptimizeKind deopt_kind, BuiltinContinuationMode continuation_mode) [inline], [static]
Definition at line 1979 of file frames.h.
                                                                            {
    return {translation_height,
            continuation_descriptor,
            register_config,
            is_topmost,
            deopt_kind,
            continuation_mode,
            FrameInfoKind::kPrecise};
  }
References v8::internal::kPrecise.
Referenced by v8::internal::Deoptimizer::DoComputeBuiltinContinuation().
stack_parameter_count()
uint32_t v8::internal::BuiltinContinuationFrameInfo::stack_parameter_count () const [inline]
Definition at line 2014 of file frames.h.
{ return stack_parameter_count_; }
References stack_parameter_count_.
Referenced by v8::internal::Deoptimizer::DoComputeBuiltinContinuation().
translated_stack_parameter_count()
uint32_t v8::internal::BuiltinContinuationFrameInfo::translated_stack_parameter_count () const [inline]
Definition at line 2011 of file frames.h.
                                                    {
    return translated_stack_parameter_count_;
  }
References translated_stack_parameter_count_.
Referenced by v8::internal::Deoptimizer::DoComputeBuiltinContinuation().
Member Data Documentation
frame_has_result_stack_slot_
bool v8::internal::BuiltinContinuationFrameInfo::frame_has_result_stack_slot_ [private]
Definition at line 2028 of file frames.h.
Referenced by frame_has_result_stack_slot().
frame_size_in_bytes_
uint32_t v8::internal::BuiltinContinuationFrameInfo::frame_size_in_bytes_ [private]
Definition at line 2031 of file frames.h.
Referenced by frame_size_in_bytes().
frame_size_in_bytes_above_fp_
uint32_t v8::internal::BuiltinContinuationFrameInfo::frame_size_in_bytes_above_fp_ [private]
Definition at line 2032 of file frames.h.
Referenced by frame_size_in_bytes_above_fp().
stack_parameter_count_
uint32_t v8::internal::BuiltinContinuationFrameInfo::stack_parameter_count_ [private]
Definition at line 2030 of file frames.h.
Referenced by stack_parameter_count().
translated_stack_parameter_count_
uint32_t v8::internal::BuiltinContinuationFrameInfo::translated_stack_parameter_count_ [private]
Definition at line 2029 of file frames.h.
Referenced by translated_stack_parameter_count().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/frames.h
/mnt/V8SourceCode/src/execution/frames.cc