v8::internal::AllocationSite Class Reference
#include <allocation-site.h>
Classes
class BodyDescriptor
Public Types
enum PretenureDecision {
kUndecided = 0
, kDontTenure = 1
, kMaybeTenure = 2
, kTenure = 3
,
kZombie = 4
, kLastPretenureDecisionValue = kZombie
 }
using ElementsKindBits = base::BitField< ElementsKind, 0, 6 >
using DoNotInlineBit = base::BitField< bool, 6, 1 >
using MementoFoundCountBits = base::BitField< int, 0, 26 >
using PretenureDecisionBits = base::BitField< PretenureDecision, 26, 3 >
using DeoptDependentCodeBit = base::BitField< bool, 29, 1 >
Public Member Functions
const char * PretenureDecisionName (PretenureDecision decision)
Tagged< UnionOf< Smi, JSObject > > transition_info_or_boilerplate () const
Tagged< JSObject > boilerplate () const
Tagged< JSObject > boilerplate (AcquireLoadTag tag) const
void set_boilerplate (Tagged< JSObject > value, ReleaseStoreTag, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
int transition_info () const
void set_transition_info (int value)
Tagged< UnionOf< Smi, AllocationSite > > nested_site () const
void set_nested_site (Tagged< UnionOf< Smi, AllocationSite >> value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
int32_t pretenure_data (RelaxedLoadTag) const
void set_pretenure_data (int32_t value, RelaxedStoreTag)
int32_t pretenure_create_count () const
void set_pretenure_create_count (int32_t value)
Tagged< DependentCode > dependent_code () const
void set_dependent_code (Tagged< DependentCode > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
void Initialize ()
bool HasWeakNext () const
bool IsNested ()
int IncrementMementoFoundCount (int increment=1)
void IncrementMementoCreateCount ()
AllocationType GetAllocationType () const
void ResetPretenureDecision ()
PretenureDecision pretenure_decision () const
void set_pretenure_decision (PretenureDecision decision)
bool deopt_dependent_code () const
void set_deopt_dependent_code (bool deopt)
int memento_found_count () const
void set_memento_found_count (int count)
int memento_create_count () const
void set_memento_create_count (int count)
bool IsZombie () const
bool IsMaybeTenure () const
void MarkZombie ()
bool MakePretenureDecision (PretenureDecision current_decision, double ratio, bool maximum_size_scavenge)
bool DigestPretenuringFeedback (bool maximum_size_scavenge)
ElementsKind GetElementsKind () const
void SetElementsKind (ElementsKind kind)
bool CanInlineCall () const
void SetDoNotInlineCall ()
bool PointsToLiteral () const
Static Public Member Functions
template<AllocationSiteUpdateMode update_or_check = AllocationSiteUpdateMode::kUpdate>
static bool DigestTransitionFeedback (Isolate *isolate, DirectHandle< AllocationSite > site, ElementsKind to_kind)
static bool ShouldTrack (ElementsKind boilerplate_elements_kind)
static bool ShouldTrack (ElementsKind from, ElementsKind to)
static bool CanTrack (InstanceType type)
Static Public Attributes
static const uint32_t kMaximumArrayBytesToPretransition = 8 * 1024
Private Member Functions
bool PretenuringDecisionMade () const
Private Attributes
TaggedMember< UnionOf< Smi, JSObject > > transition_info_or_boilerplate_
TaggedMember< UnionOf< Smi, AllocationSite > > nested_site_
TaggedMember< DependentCode > dependent_code_
std::atomic< int32_t > pretenure_data_
int32_t pretenure_create_count_
Friends
class CodeStubAssembler
class ArrayBuiltinsAssembler
class ObjectBuiltinsAssembler
class V8HeapExplorer
Detailed Description
Definition at line 23 of file allocation-site.h.
Member Typedef Documentation
DeoptDependentCodeBit
using v8::internal::AllocationSite::DeoptDependentCodeBit = base::BitField<bool, 29, 1>
Definition at line 83 of file allocation-site.h.
DoNotInlineBit
using v8::internal::AllocationSite::DoNotInlineBit = base::BitField<bool, 6, 1>
Definition at line 77 of file allocation-site.h.
ElementsKindBits
using v8::internal::AllocationSite::ElementsKindBits = base::BitField<ElementsKind, 0, 6>
Definition at line 76 of file allocation-site.h.
MementoFoundCountBits
using v8::internal::AllocationSite::MementoFoundCountBits = base::BitField<int, 0, 26>
Definition at line 81 of file allocation-site.h.
PretenureDecisionBits
using v8::internal::AllocationSite::PretenureDecisionBits = base::BitField<PretenureDecision, 26, 3>
Definition at line 82 of file allocation-site.h.
Member Enumeration Documentation
PretenureDecision
enum v8::internal::AllocationSite::PretenureDecision
Enumerator
kUndecided
kDontTenure
kMaybeTenure
kTenure
kZombie
kLastPretenureDecisionValue
Definition at line 28 of file allocation-site.h.
                         {
    kUndecided = 0,
    kDontTenure = 1,
    kMaybeTenure = 2,
    kTenure = 3,
    kZombie = 4, // See comment to IsZombie() for documentation.
    kLastPretenureDecisionValue = kZombie
  };
Member Function Documentation
boilerplate() [1/2]
Tagged< JSObject > v8::internal::AllocationSite::boilerplate () const [inline]
Definition at line 63 of file allocation-site-inl.h.
                                                          {
  DCHECK(PointsToLiteral());
  return Cast<JSObject>(transition_info_or_boilerplate_.load());
}
References v8::internal::DCHECK(), PointsToLiteral(), and transition_info_or_boilerplate_.
Referenced by DigestTransitionFeedback().
boilerplate() [2/2]
Tagged< JSObject > v8::internal::AllocationSite::boilerplate (AcquireLoadTag tag) const [inline]
Definition at line 68 of file allocation-site-inl.h.
                                                                            {
  DCHECK(PointsToLiteral());
  return Cast<JSObject>(transition_info_or_boilerplate_.Acquire_Load());
}
References v8::internal::DCHECK(), PointsToLiteral(), and transition_info_or_boilerplate_.
CanInlineCall()
bool v8::internal::AllocationSite::CanInlineCall () const [inline]
Definition at line 130 of file allocation-site-inl.h.
                                                {
  return DoNotInlineBit::decode(transition_info()) == 0;
}
References v8::base::BitField< T, shift, size, U >::decode(), and transition_info().
CanTrack()
bool v8::internal::AllocationSite::CanTrack (InstanceType type) [inline], [static]
Definition at line 152 of file allocation-site-inl.h.
                                                      {
  if (!V8_ALLOCATION_SITE_TRACKING_BOOL) return false;
  if (v8_flags.allocation_site_pretenuring) {
    // TurboFan doesn't care at all about String pretenuring feedback,
    // so don't bother even trying to track that.
    return type == JS_ARRAY_TYPE || type == JS_OBJECT_TYPE;
  }
  return type == JS_ARRAY_TYPE;
}
References v8::internal::tracing::type, V8_ALLOCATION_SITE_TRACKING_BOOL, and v8::internal::v8_flags.
Referenced by v8::internal::Factory::CopyJSObjectWithAllocationSite(), v8::internal::AllocationSiteUsageContext::ShouldCreateMemento(), and v8::internal::PretenuringHandler::UpdateAllocationSite().
deopt_dependent_code()
bool v8::internal::AllocationSite::deopt_dependent_code () const [inline]
Definition at line 173 of file allocation-site-inl.h.
                                                       {
  return DeoptDependentCodeBit::decode(pretenure_data(kRelaxedLoad));
}
References v8::base::BitField< T, shift, size, U >::decode(), v8::kRelaxedLoad, and pretenure_data().
dependent_code()
Tagged< DependentCode > v8::internal::AllocationSite::dependent_code () const [inline]
Definition at line 41 of file allocation-site-inl.h.
                                                                  {
  return dependent_code_.load();
}
References dependent_code_.
DigestPretenuringFeedback()
bool v8::internal::AllocationSite::DigestPretenuringFeedback (bool maximum_size_scavenge) [inline]
DigestTransitionFeedback()
template<AllocationSiteUpdateMode update_or_check>
bool v8::internal::AllocationSite::DigestTransitionFeedback (Isolate * isolate, DirectHandle< AllocationSite > site, ElementsKind to_kind) [static]
Definition at line 249 of file allocation-site-inl.h.
                                                                    {
  bool result = false;
  if (site->PointsToLiteral() && IsJSArray(site->boilerplate())) {
    DirectHandle<JSArray> boilerplate(Cast<JSArray>(site->boilerplate()),
                                      isolate);
    ElementsKind kind = boilerplate->GetElementsKind();
    // if kind is holey ensure that to_kind is as well.
    if (IsHoleyElementsKind(kind)) {
      to_kind = GetHoleyElementsKind(to_kind);
    }
    if (IsMoreGeneralElementsKindTransition(kind, to_kind)) {
      // If the array is huge, it's not likely to be defined in a local
      // function, so we shouldn't make new instances of it very often.
      uint32_t length = 0;
      CHECK(Object::ToArrayLength(boilerplate->length(), &length));
      if (length <= kMaximumArrayBytesToPretransition) {
        if (update_or_check == AllocationSiteUpdateMode::kCheckOnly) {
          return true;
        }
        if (v8_flags.trace_track_allocation_sites) {
          bool is_nested = site->IsNested();
          PrintF("AllocationSite: JSArray %p boilerplate %supdated %s->%s\n",
                 reinterpret_cast<void*>(site->ptr()),
                 is_nested ? "(nested)" : " ", ElementsKindToString(kind),
                 ElementsKindToString(to_kind));
        }
        CHECK_NE(to_kind, DICTIONARY_ELEMENTS);
        JSObject::TransitionElementsKind(isolate, boilerplate, to_kind);
        DependentCode::DeoptimizeDependencyGroups(
            isolate, *site,
            DependentCode::kAllocationSiteTransitionChangedGroup);
        result = true;
      }
    }
  } else {
    // The AllocationSite is for a constructed Array.
    ElementsKind kind = site->GetElementsKind();
    // if kind is holey ensure that to_kind is as well.
    if (IsHoleyElementsKind(kind)) {
      to_kind = GetHoleyElementsKind(to_kind);
    }
    if (IsMoreGeneralElementsKindTransition(kind, to_kind)) {
      if (update_or_check == AllocationSiteUpdateMode::kCheckOnly) return true;
      if (v8_flags.trace_track_allocation_sites) {
        PrintF("AllocationSite: JSArray %p site updated %s->%s\n",
               reinterpret_cast<void*>(site->ptr()), ElementsKindToString(kind),
               ElementsKindToString(to_kind));
      }
      site->SetElementsKind(to_kind);
      DependentCode::DeoptimizeDependencyGroups(
          isolate, *site, DependentCode::kAllocationSiteTransitionChangedGroup);
      result = true;
    }
  }
  return result;
}
References boilerplate(), CHECK, CHECK_NE, v8::internal::DependentCode::DeoptimizeDependencyGroups(), v8::internal::DICTIONARY_ELEMENTS, v8::internal::ElementsKindToString(), v8::internal::GetHoleyElementsKind(), v8::internal::IsHoleyElementsKind(), v8::internal::IsMoreGeneralElementsKindTransition(), v8::internal::DependentCode::kAllocationSiteTransitionChangedGroup, v8::internal::kCheckOnly, kMaximumArrayBytesToPretransition, v8::internal::length, v8::internal::PrintF(), v8::base::internal::result, v8::internal::Object::ToArrayLength(), v8::internal::JSObject::TransitionElementsKind(), and v8::internal::v8_flags.
GetAllocationType()
AllocationType v8::internal::AllocationSite::GetAllocationType () const
Definition at line 4965 of file objects.cc.
                                                       {
  PretenureDecision mode = pretenure_decision();
  // Zombie objects "decide" to be untenured.
  return mode == kTenure ? AllocationType::kOld : AllocationType::kYoung;
}
References v8::internal::kOld, v8::internal::kYoung, and mode().
GetElementsKind()
ElementsKind v8::internal::AllocationSite::GetElementsKind () const [inline]
Definition at line 122 of file allocation-site-inl.h.
                                                          {
  return ElementsKindBits::decode(transition_info());
}
References v8::base::BitField< T, shift, size, U >::decode(), and transition_info().
HasWeakNext()
bool v8::internal::AllocationSite::HasWeakNext () const [inline]
Definition at line 90 of file allocation-site-inl.h.
                                              {
  return map() == GetReadOnlyRoots().allocation_site_map();
}
References v8::internal::GetReadOnlyRoots(), and v8::internal::HeapObjectLayout::map().
IncrementMementoCreateCount()
void v8::internal::AllocationSite::IncrementMementoCreateCount () [inline]
Definition at line 215 of file allocation-site-inl.h.
                                                        {
  DCHECK(v8_flags.allocation_site_pretenuring);
  int value = memento_create_count();
  set_memento_create_count(value + 1);
}
References v8::internal::DCHECK(), memento_create_count(), set_memento_create_count(), v8::internal::v8_flags, and v8::internal::value.
IncrementMementoFoundCount()
int v8::internal::AllocationSite::IncrementMementoFoundCount (int increment = 1) [inline]
Definition at line 207 of file allocation-site-inl.h.
                                                            {
  DCHECK(!IsZombie());
  int new_value = memento_found_count() + increment;
  set_memento_found_count(new_value);
  return new_value;
}
References v8::internal::DCHECK(), IsZombie(), memento_found_count(), and set_memento_found_count().
Initialize()
void v8::internal::AllocationSite::Initialize () [inline]
Definition at line 94 of file allocation-site-inl.h.
                                       {
  transition_info_or_boilerplate_.store(this, Smi::zero(), SKIP_WRITE_BARRIER);
  SetElementsKind(GetInitialFastElementsKind());
  set_nested_site(Smi::zero());
  set_pretenure_data(0, kRelaxedStore);
  set_pretenure_create_count(0);
  set_dependent_code(DependentCode::empty_dependent_code(GetReadOnlyRoots()),
                     SKIP_WRITE_BARRIER);
}
References v8::internal::DependentCode::empty_dependent_code(), v8::internal::GetInitialFastElementsKind(), v8::internal::GetReadOnlyRoots(), v8::kRelaxedStore, set_dependent_code(), set_nested_site(), set_pretenure_create_count(), set_pretenure_data(), SetElementsKind(), v8::internal::SKIP_WRITE_BARRIER, transition_info_or_boilerplate_, and v8::internal::Smi::zero().
Referenced by MarkZombie().
IsMaybeTenure()
bool v8::internal::AllocationSite::IsMaybeTenure () const [inline]
Definition at line 108 of file allocation-site-inl.h.
                                                {
  return pretenure_decision() == kMaybeTenure;
}
References kMaybeTenure, and pretenure_decision().
IsNested()
bool v8::internal::AllocationSite::IsNested ()
Definition at line 4971 of file objects.cc.
                              {
  DCHECK(v8_flags.trace_track_allocation_sites);
  Tagged<Object> current = Isolate::Current()->heap()->allocation_sites_list();
  while (IsAllocationSite(current)) {
    Tagged<AllocationSiteWithWeakNext> current_site =
        Cast<AllocationSiteWithWeakNext>(current);
    if (current_site->nested_site() == this) {
      return true;
    }
    current = current_site->weak_next();
  }
  return false;
}
References v8::internal::Heap::allocation_sites_list(), v8::internal::Isolate::Current(), v8::internal::DCHECK(), v8::internal::Isolate::heap(), and v8::internal::v8_flags.
IsZombie()
bool v8::internal::AllocationSite::IsZombie () const [inline]
Definition at line 104 of file allocation-site-inl.h.
                                           {
  return pretenure_decision() == kZombie;
}
References kZombie, and pretenure_decision().
Referenced by IncrementMementoFoundCount(), and MarkZombie().
MakePretenureDecision()
bool v8::internal::AllocationSite::MakePretenureDecision (PretenureDecision current_decision, double ratio, bool maximum_size_scavenge) [inline]
MarkZombie()
void v8::internal::AllocationSite::MarkZombie () [inline]
Definition at line 116 of file allocation-site-inl.h.
                                       {
  DCHECK(!IsZombie());
  Initialize();
  set_pretenure_decision(kZombie);
}
References v8::internal::DCHECK(), Initialize(), IsZombie(), kZombie, and set_pretenure_decision().
memento_create_count()
int v8::internal::AllocationSite::memento_create_count () const [inline]
Definition at line 199 of file allocation-site-inl.h.
                                                      {
  return pretenure_create_count();
}
References pretenure_create_count().
Referenced by IncrementMementoCreateCount().
memento_found_count()
int v8::internal::AllocationSite::memento_found_count () const [inline]
Definition at line 183 of file allocation-site-inl.h.
                                                     {
  return MementoFoundCountBits::decode(pretenure_data(kRelaxedLoad));
}
References v8::base::BitField< T, shift, size, U >::decode(), v8::kRelaxedLoad, and pretenure_data().
Referenced by IncrementMementoFoundCount().
nested_site()
Tagged< UnionOf< Smi, AllocationSite > > v8::internal::AllocationSite::nested_site () const [inline]
Definition at line 32 of file allocation-site-inl.h.
          {
  return nested_site_.load();
}
References nested_site_.
PointsToLiteral()
bool v8::internal::AllocationSite::PointsToLiteral () const [inline]
Definition at line 138 of file allocation-site-inl.h.
                                                  {
  Tagged<Object> raw_value = transition_info_or_boilerplate_.Acquire_Load();
  DCHECK_EQ(!IsSmi(raw_value), IsJSArray(raw_value) || IsJSObject(raw_value));
  return !IsSmi(raw_value);
}
References DCHECK_EQ, v8::internal::IsSmi(), and transition_info_or_boilerplate_.
Referenced by boilerplate(), set_transition_info(), and transition_info().
pretenure_create_count()
int32_t v8::internal::AllocationSite::pretenure_create_count () const [inline]
Definition at line 56 of file allocation-site-inl.h.
                                                            {
  return pretenure_create_count_;
}
References pretenure_create_count_.
Referenced by memento_create_count().
pretenure_data()
int32_t v8::internal::AllocationSite::pretenure_data (RelaxedLoadTag) const [inline]
Definition at line 49 of file allocation-site-inl.h.
                                                                  {
  return pretenure_data_.load(std::memory_order_relaxed);
}
References pretenure_data_.
Referenced by deopt_dependent_code(), memento_found_count(), pretenure_decision(), set_deopt_dependent_code(), set_memento_found_count(), and set_pretenure_decision().
pretenure_decision()
AllocationSite::PretenureDecision v8::internal::AllocationSite::pretenure_decision () const [inline]
Definition at line 162 of file allocation-site-inl.h.
          {
  return PretenureDecisionBits::decode(pretenure_data(kRelaxedLoad));
}
References v8::base::BitField< T, shift, size, U >::decode(), v8::kRelaxedLoad, and pretenure_data().
Referenced by IsMaybeTenure(), IsZombie(), and PretenuringDecisionMade().
PretenureDecisionName()
const char * v8::internal::AllocationSite::PretenureDecisionName (PretenureDecision decision)
Definition at line 4990 of file objects.cc.
                                                                            {
  switch (decision) {
    case kUndecided:
      return "undecided";
    case kDontTenure:
      return "don't tenure";
    case kMaybeTenure:
      return "maybe tenure";
    case kTenure:
      return "tenure";
    case kZombie:
      return "zombie";
    default:
      UNREACHABLE();
  }
}
References v8::internal::UNREACHABLE().
PretenuringDecisionMade()
bool v8::internal::AllocationSite::PretenuringDecisionMade () const [inline], [private]
Definition at line 112 of file allocation-site-inl.h.
                                                          {
  return pretenure_decision() != kUndecided;
}
References kUndecided, and pretenure_decision().
ResetPretenureDecision()
void v8::internal::AllocationSite::ResetPretenureDecision ()
Definition at line 4959 of file objects.cc.
                                            {
  set_pretenure_decision(kUndecided);
  set_memento_found_count(0);
  set_memento_create_count(0);
}
set_boilerplate()
void v8::internal::AllocationSite::set_boilerplate (Tagged< JSObject > value, ReleaseStoreTag tag, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 73 of file allocation-site-inl.h.
                                                                   {
  transition_info_or_boilerplate_.Release_Store(this, value, mode);
}
References mode(), transition_info_or_boilerplate_, and v8::internal::value.
set_deopt_dependent_code()
void v8::internal::AllocationSite::set_deopt_dependent_code (bool deopt) [inline]
Definition at line 177 of file allocation-site-inl.h.
                                                               {
  int32_t value = pretenure_data(kRelaxedLoad);
  set_pretenure_data(DeoptDependentCodeBit::update(value, deopt),
                     kRelaxedStore);
}
References v8::kRelaxedLoad, v8::kRelaxedStore, pretenure_data(), set_pretenure_data(), v8::base::BitField< T, shift, size, U >::update(), and v8::internal::value.
set_dependent_code()
void v8::internal::AllocationSite::set_dependent_code (Tagged< DependentCode > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 44 of file allocation-site-inl.h.
                                                               {
  dependent_code_.store(this, value, mode);
}
References dependent_code_, mode(), and v8::internal::value.
Referenced by Initialize().
set_memento_create_count()
void v8::internal::AllocationSite::set_memento_create_count (int count) [inline]
Definition at line 203 of file allocation-site-inl.h.
                                                              {
  set_pretenure_create_count(count);
}
References set_pretenure_create_count().
Referenced by IncrementMementoCreateCount().
set_memento_found_count()
void v8::internal::AllocationSite::set_memento_found_count (int count) [inline]
Definition at line 187 of file allocation-site-inl.h.
                                                             {
  int32_t value = pretenure_data(kRelaxedLoad);
  // Verify that we can count more mementos than we can possibly find in one
  // new space collection.
  DCHECK((Isolate::Current()->heap()->MaxSemiSpaceSize() /
          (Heap::kMinObjectSizeInTaggedWords * kTaggedSize +
           sizeof(AllocationSiteWithWeakNext))) < MementoFoundCountBits::kMax);
  DCHECK_LT(count, MementoFoundCountBits::kMax);
  set_pretenure_data(MementoFoundCountBits::update(value, count),
                     kRelaxedStore);
}
References v8::internal::Isolate::Current(), v8::internal::DCHECK(), DCHECK_LT, heap(), v8::base::BitField< T, shift, size, U >::kMax, v8::internal::Heap::kMinObjectSizeInTaggedWords, v8::kRelaxedLoad, v8::kRelaxedStore, v8::internal::kTaggedSize, pretenure_data(), set_pretenure_data(), v8::base::BitField< T, shift, size, U >::update(), and v8::internal::value.
Referenced by IncrementMementoFoundCount().
set_nested_site()
void v8::internal::AllocationSite::set_nested_site (Tagged< UnionOf< Smi, AllocationSite >> value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 36 of file allocation-site-inl.h.
                                                                       {
  nested_site_.store(this, value, mode);
}
References mode(), nested_site_, and v8::internal::value.
Referenced by Initialize().
set_pretenure_create_count()
void v8::internal::AllocationSite::set_pretenure_create_count (int32_t value) [inline]
Definition at line 59 of file allocation-site-inl.h.
                                                                    {
  pretenure_create_count_ = value;
}
References pretenure_create_count_, and v8::internal::value.
Referenced by Initialize(), and set_memento_create_count().
set_pretenure_data()
void v8::internal::AllocationSite::set_pretenure_data (int32_t value, RelaxedStoreTag) [inline]
Definition at line 52 of file allocation-site-inl.h.
                                                                             {
  pretenure_data_.store(value, std::memory_order_relaxed);
}
References pretenure_data_, and v8::internal::value.
Referenced by Initialize(), set_deopt_dependent_code(), set_memento_found_count(), and set_pretenure_decision().
set_pretenure_decision()
void v8::internal::AllocationSite::set_pretenure_decision (PretenureDecision decision) [inline]
Definition at line 167 of file allocation-site-inl.h.
                                                                             {
  int32_t value = pretenure_data(kRelaxedLoad);
  set_pretenure_data(PretenureDecisionBits::update(value, decision),
                     kRelaxedStore);
}
References v8::kRelaxedLoad, v8::kRelaxedStore, pretenure_data(), set_pretenure_data(), v8::base::BitField< T, shift, size, U >::update(), and v8::internal::value.
Referenced by MarkZombie().
set_transition_info()
void v8::internal::AllocationSite::set_transition_info (int value) [inline]
Definition at line 84 of file allocation-site-inl.h.
                                                  {
  DCHECK(!PointsToLiteral());
  transition_info_or_boilerplate_.Release_Store(this, Smi::FromInt(value),
                                                SKIP_WRITE_BARRIER);
}
References v8::internal::DCHECK(), v8::internal::Smi::FromInt(), PointsToLiteral(), v8::internal::SKIP_WRITE_BARRIER, transition_info_or_boilerplate_, and v8::internal::value.
Referenced by SetDoNotInlineCall(), and SetElementsKind().
SetDoNotInlineCall()
void v8::internal::AllocationSite::SetDoNotInlineCall () [inline]
Definition at line 134 of file allocation-site-inl.h.
                                               {
  set_transition_info(DoNotInlineBit::update(transition_info(), true));
}
References set_transition_info(), transition_info(), and v8::base::BitField< T, shift, size, U >::update().
SetElementsKind()
void v8::internal::AllocationSite::SetElementsKind (ElementsKind kind) [inline]
Definition at line 126 of file allocation-site-inl.h.
                                                             {
  set_transition_info(ElementsKindBits::update(transition_info(), kind));
}
References set_transition_info(), transition_info(), and v8::base::BitField< T, shift, size, U >::update().
Referenced by Initialize().
ShouldTrack() [1/2]
bool v8::internal::AllocationSite::ShouldTrack (ElementsKind boilerplate_elements_kind) [inline], [static]
Definition at line 146 of file allocation-site-inl.h.
                                            {
  if (!V8_ALLOCATION_SITE_TRACKING_BOOL) return false;
  return IsSmiElementsKind(boilerplate_elements_kind);
}
References v8::internal::IsSmiElementsKind(), and V8_ALLOCATION_SITE_TRACKING_BOOL.
Referenced by v8::internal::CodeFactory::ArrayNoArgumentConstructor(), v8::internal::CodeFactory::ArraySingleArgumentConstructor(), v8::internal::compiler::CompilationDependencies::DependOnElementsKind(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ElementsKindDependency::ElementsKindDependency(), v8::internal::ArrayBuiltinsAssembler::GenerateArrayNoArgumentConstructor(), v8::internal::ArrayBuiltinsAssembler::GenerateArraySingleArgumentConstructor(), v8::internal::RUNTIME_FUNCTION(), v8::internal::AllocationSiteUsageContext::ShouldCreateMemento(), v8::internal::KeyedStoreGenericAssembler::TryChangeToHoleyMapHelper(), and v8::internal::KeyedStoreGenericAssembler::TryRewriteElements().
ShouldTrack() [2/2]
bool v8::internal::AllocationSite::ShouldTrack (ElementsKind from, ElementsKind to) [static]
Definition at line 4985 of file objects.cc.
                                                                   {
  if (!V8_ALLOCATION_SITE_TRACKING_BOOL) return false;
  return IsMoreGeneralElementsKindTransition(from, to);
}
References v8::internal::IsMoreGeneralElementsKindTransition(), and V8_ALLOCATION_SITE_TRACKING_BOOL.
transition_info()
int v8::internal::AllocationSite::transition_info () const [inline]
Definition at line 79 of file allocation-site-inl.h.
                                                 {
  DCHECK(!PointsToLiteral());
  return Cast<Smi>(transition_info_or_boilerplate_.Acquire_Load()).value();
}
References v8::internal::DCHECK(), PointsToLiteral(), and transition_info_or_boilerplate_.
Referenced by CanInlineCall(), GetElementsKind(), SetDoNotInlineCall(), and SetElementsKind().
transition_info_or_boilerplate()
Tagged< UnionOf< Smi, JSObject > > v8::internal::AllocationSite::transition_info_or_boilerplate () const [inline]
Definition at line 28 of file allocation-site-inl.h.
                                                     {
  return transition_info_or_boilerplate_.load();
}
References transition_info_or_boilerplate_.
Friends And Related Function Documentation
ArrayBuiltinsAssembler
friend class ArrayBuiltinsAssembler [friend]
Definition at line 156 of file allocation-site.h.
CodeStubAssembler
friend class CodeStubAssembler [friend]
Definition at line 155 of file allocation-site.h.
ObjectBuiltinsAssembler
friend class ObjectBuiltinsAssembler [friend]
Definition at line 157 of file allocation-site.h.
V8HeapExplorer
friend class V8HeapExplorer [friend]
Definition at line 158 of file allocation-site.h.
Member Data Documentation
dependent_code_
TaggedMember<DependentCode> v8::internal::AllocationSite::dependent_code_ [private]
Definition at line 164 of file allocation-site.h.
Referenced by dependent_code(), and set_dependent_code().
kMaximumArrayBytesToPretransition
const uint32_t v8::internal::AllocationSite::kMaximumArrayBytesToPretransition = 8 * 1024 [static]
Definition at line 25 of file allocation-site.h.
Referenced by DigestTransitionFeedback().
nested_site_
TaggedMember<UnionOf<Smi, AllocationSite> > v8::internal::AllocationSite::nested_site_ [private]
Definition at line 163 of file allocation-site.h.
Referenced by nested_site(), and set_nested_site().
pretenure_create_count_
int32_t v8::internal::AllocationSite::pretenure_create_count_ [private]
Definition at line 166 of file allocation-site.h.
Referenced by pretenure_create_count(), and set_pretenure_create_count().
pretenure_data_
std::atomic<int32_t> v8::internal::AllocationSite::pretenure_data_ [private]
Definition at line 165 of file allocation-site.h.
Referenced by pretenure_data(), and set_pretenure_data().
transition_info_or_boilerplate_
TaggedMember<UnionOf<Smi, JSObject> > v8::internal::AllocationSite::transition_info_or_boilerplate_ [private]
Definition at line 162 of file allocation-site.h.
Referenced by boilerplate(), Initialize(), PointsToLiteral(), set_boilerplate(), set_transition_info(), transition_info(), and transition_info_or_boilerplate().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/allocation-site.h
/mnt/V8SourceCode/src/objects/allocation-site-inl.h
/mnt/V8SourceCode/src/objects/objects.cc