v8::internal::compiler::BytecodeGraphBuilder Class Reference
Classes
class BytecodePositionDecorator
class Environment
struct ExceptionHandler
class OsrIteratorState
struct SubEnvironment
Public Member Functions
BytecodeGraphBuilder (JSHeapBroker *broker, Zone *local_zone, NativeContextRef native_context, SharedFunctionInfoRef shared_info, BytecodeArrayRef bytecode, FeedbackCellRef feedback_cell, BytecodeOffset osr_offset, JSGraph *jsgraph, CallFrequency const &invocation_frequency, SourcePositionTable *source_positions, NodeOriginTable *node_origins, int inlining_id, CodeKind code_kind, BytecodeGraphBuilderFlags flags, TickCounter *tick_counter, ObserveNodeInfo const &observe_node_info)
BytecodeGraphBuilder (const BytecodeGraphBuilder &)=delete
BytecodeGraphBuilder & operator= (const BytecodeGraphBuilder &)=delete
void CreateGraph ()
Private Types
enum class NamedStoreMode { kSet
, kDefineOwn
 }
Private Member Functions
void RemoveMergeEnvironmentsBeforeOffset (int limit_offset)
void AdvanceToOsrEntryAndPeelLoops ()
void AdvanceIteratorsTo (int bytecode_offset)
void VisitSingleBytecode ()
void VisitBytecodes ()
void AddBytecodePositionDecorator ()
void RemoveBytecodePositionDecorator ()
Node * GetFunctionClosure ()
Node * GetParameter (int index, const char *debug_name_hint=nullptr)
CodeKind code_kind () const
void CreateFeedbackVectorNode ()
Node * feedback_vector_node () const
void CreateNativeContextNode ()
Node * native_context_node () const
Node * BuildLoadFeedbackCell (int index)
Node * BuildLoadNativeContextField (int index)
FeedbackSource CreateFeedbackSource (int slot_id)
FeedbackSource CreateFeedbackSource (FeedbackSlot slot)
void set_environment (Environment *env)
const Environment * environment () const
Environment * environment ()
Node * NewNode (const Operator *op, bool incomplete=false)
template<class... Args>
Node * NewNode (const Operator *op, Node *n0, Args... nodes)
Node * NewIfTrue ()
Node * NewIfFalse ()
Node * NewIfValue (int32_t value)
Node * NewIfDefault ()
Node * NewMerge ()
Node * NewLoop ()
Node * NewBranch (Node *condition, BranchHint hint=BranchHint::kNone)
Node * NewSwitch (Node *condition, int control_output_count)
Node * NewPhi (int count, Node *input, Node *control)
Node * NewEffectPhi (int count, Node *input, Node *control)
Node * MergeControl (Node *control, Node *other)
Node * MergeEffect (Node *effect, Node *other_effect, Node *control)
Node * MergeValue (Node *value, Node *other_value, Node *control)
Node * MakeNode (const Operator *op, int value_input_count, Node *const *value_inputs, bool incomplete=false)
Node ** EnsureInputBufferSize (int size)
Node *const * GetCallArgumentsFromRegisters (Node *callee, Node *receiver, interpreter::Register first_arg, int arg_count)
Node *const * ProcessCallVarArgs (ConvertReceiverMode receiver_mode, Node *callee, interpreter::Register first_reg, int arg_count)
Node *const * GetConstructArgumentsFromRegister (Node *target, Node *new_target, interpreter::Register first_arg, int arg_count)
Node * ProcessCallRuntimeArguments (const Operator *call_runtime_op, interpreter::Register receiver, size_t reg_count)
void PrepareEagerCheckpoint ()
void PrepareFrameState (Node *node, OutputFrameStateCombine combine, BytecodeOffset bailout_id, const BytecodeLivenessState *liveness)
void PrepareFrameState (Node *node, OutputFrameStateCombine combine)
void PrepareFrameStateForFunctionEntryStackCheck (Node *node)
void PrepareFrameStateForOSREntryStackCheck (Node *node)
void BuildCreateArguments (CreateArgumentsType type)
Node * BuildLoadGlobal (NameRef name, uint32_t feedback_slot_index, TypeofMode typeof_mode)
void BuildNamedStore (NamedStoreMode store_mode)
void BuildLdaLookupSlot (TypeofMode typeof_mode)
void BuildLdaLookupContextSlot (ContextMode context_mode, TypeofMode typeof_mode)
void BuildLdaLookupGlobalSlot (TypeofMode typeof_mode)
void BuildCallVarArgs (ConvertReceiverMode receiver_mode)
void BuildCall (ConvertReceiverMode receiver_mode, Node *const *args, size_t arg_count, int slot_id)
void BuildCall (ConvertReceiverMode receiver_mode, std::initializer_list< Node * > args, int slot_id)
void BuildUnaryOp (const Operator *op)
void BuildBinaryOp (const Operator *op)
void BuildBinaryOpWithImmediate (const Operator *op)
void BuildCompareOp (const Operator *op)
void BuildDelete (LanguageMode language_mode)
void BuildCastOperator (const Operator *op)
void BuildHoleCheckAndThrow (Node *condition, Runtime::FunctionId runtime_id, Node *name=nullptr)
JSTypeHintLowering::LoweringResult TryBuildSimplifiedUnaryOp (const Operator *op, Node *operand, FeedbackSlot slot)
JSTypeHintLowering::LoweringResult TryBuildSimplifiedBinaryOp (const Operator *op, Node *left, Node *right, FeedbackSlot slot)
JSTypeHintLowering::LoweringResult TryBuildSimplifiedForInNext (Node *receiver, Node *cache_array, Node *cache_type, Node *index, FeedbackSlot slot)
JSTypeHintLowering::LoweringResult TryBuildSimplifiedForInPrepare (Node *receiver, FeedbackSlot slot)
JSTypeHintLowering::LoweringResult TryBuildSimplifiedToNumber (Node *input, FeedbackSlot slot)
JSTypeHintLowering::LoweringResult TryBuildSimplifiedConstruct (const Operator *op, Node *const *args, int arg_count, FeedbackSlot slot)
JSTypeHintLowering::LoweringResult TryBuildSimplifiedGetIterator (const Operator *op, Node *receiver, FeedbackSlot load_slot, FeedbackSlot call_slot)
JSTypeHintLowering::LoweringResult TryBuildSimplifiedLoadNamed (const Operator *op, FeedbackSlot slot)
JSTypeHintLowering::LoweringResult TryBuildSimplifiedLoadKeyed (const Operator *op, Node *receiver, Node *key, FeedbackSlot slot)
JSTypeHintLowering::LoweringResult TryBuildSimplifiedStoreNamed (const Operator *op, Node *receiver, Node *value, FeedbackSlot slot)
JSTypeHintLowering::LoweringResult TryBuildSimplifiedStoreKeyed (const Operator *op, Node *receiver, Node *key, Node *value, FeedbackSlot slot)
void ApplyEarlyReduction (JSTypeHintLowering::LoweringResult reduction)
Environment * CheckContextExtensions (uint32_t depth)
Environment * CheckContextExtensionsSlowPath (uint32_t depth)
OptionalScopeInfoRef TryGetScopeInfo ()
Environment * CheckContextExtensionAtDepth (Environment *slow_environment, uint32_t depth, ContextMode context_mode)
ForInMode GetForInMode (FeedbackSlot slot)
CallFrequency ComputeCallFrequency (int slot_id) const
SpeculationMode GetSpeculationMode (int slot_id) const
CallFeedbackRelation ComputeCallFeedbackRelation (int slot_id) const
void BuildFunctionEntryStackCheck ()
void BuildIterationBodyStackCheck ()
void BuildOSREntryStackCheck ()
void BuildJump ()
void BuildJumpIf (Node *condition)
void BuildJumpIfNot (Node *condition)
void BuildJumpIfEqual (Node *comperand)
void BuildJumpIfNotEqual (Node *comperand)
void BuildJumpIfTrue ()
void BuildJumpIfFalse ()
void BuildJumpIfToBooleanTrue ()
void BuildJumpIfToBooleanFalse ()
void BuildJumpIfNotHole ()
void BuildJumpIfJSReceiver ()
void BuildJumpIfForInDone ()
void BuildSwitchOnSmi (Node *condition)
void BuildSwitchOnGeneratorState (const ZoneVector< ResumeJumpTarget > &resume_jump_targets, bool allow_fallthrough_on_executing)
void MergeIntoSuccessorEnvironment (int target_offset)
void BuildLoopHeaderEnvironment (int current_offset)
void SwitchToMergeEnvironment (int current_offset)
void MergeControlToLeaveFunction (Node *exit)
void BuildLoopExitsForBranch (int target_offset)
void BuildLoopExitsForFunctionExit (const BytecodeLivenessState *liveness)
void BuildLoopExitsUntilLoop (int loop_offset, const BytecodeLivenessState *liveness)
void BuildReturn (const BytecodeLivenessState *liveness)
void ExitThenEnterExceptionHandlers (int current_offset)
void UpdateSourceAndBytecodePosition (int offset)
template<class T = Object>
ref_traits< T >::ref_type MakeRefForConstantForIndexOperand (int operand_index)
TFGraph * graph () const
CommonOperatorBuilder * common () const
Zone * graph_zone () const
JSGraph * jsgraph () const
Isolate * isolate () const
JSOperatorBuilder * javascript () const
SimplifiedOperatorBuilder * simplified () const
Zone * local_zone () const
BytecodeArrayRef bytecode_array () const
FeedbackVectorRef feedback_vector () const
const JSTypeHintLowering & type_hint_lowering () const
const FrameStateFunctionInfo * frame_state_function_info () const
SourcePositionTableIterator & source_position_iterator ()
interpreter::BytecodeArrayIterator const & bytecode_iterator () const
interpreter::BytecodeArrayIterator & bytecode_iterator ()
BytecodeAnalysis const & bytecode_analysis () const
int currently_peeled_loop_offset () const
void set_currently_peeled_loop_offset (int offset)
bool skip_first_stack_check () const
bool skip_tierup_check () const
int current_exception_handler () const
void set_current_exception_handler (int index)
bool needs_eager_checkpoint () const
void mark_as_needing_eager_checkpoint (bool value)
JSHeapBroker * broker () const
NativeContextRef native_context () const
SharedFunctionInfoRef shared_info () const
Private Attributes
JSHeapBroker *const broker_
LocalIsolate *const local_isolate_
Zone *const local_zone_
JSGraph *const jsgraph_
NativeContextRef const native_context_
SharedFunctionInfoRef const shared_info_
BytecodeArrayRef const bytecode_array_
FeedbackCellRef const feedback_cell_
FeedbackVectorRef const feedback_vector_
CallFrequency const invocation_frequency_
JSTypeHintLowering const type_hint_lowering_
const FrameStateFunctionInfo *const frame_state_function_info_
SourcePositionTableIterator source_position_iterator_
interpreter::BytecodeArrayIterator bytecode_iterator_
BytecodeAnalysis const bytecode_analysis_
Environment * environment_
BytecodePositionDecorator * decorator_
bool const osr_
int currently_peeled_loop_offset_
const bool skip_first_stack_and_tierup_check_
ZoneMap< int, Environment * > merge_environments_
ZoneMap< int, Environment * > generator_merge_environments_
ZoneVector< Node * > cached_parameters_
ZoneStack< ExceptionHandler > exception_handlers_
int current_exception_handler_
int input_buffer_size_
Node ** input_buffer_
const CodeKind code_kind_
Node * feedback_vector_node_
Node * native_context_node_
bool needs_eager_checkpoint_
SetOncePointer< Node > function_closure_
ZoneVector< Node * > exit_controls_
StateValuesCache state_values_cache_
NodeOriginTable *const node_origins_
SourcePositionTable *const source_positions_
SourcePosition const start_position_
TickCounter *const tick_counter_
ObserveNodeInfo const observe_node_info_
Static Private Attributes
static const int kInputBufferSizeIncrement = 64
static constexpr int kBinaryOperationHintIndex = 1
static constexpr int kBinaryOperationSmiHintIndex = 1
static constexpr int kCompareOperationHintIndex = 1
static constexpr int kCountOperationHintIndex = 0
static constexpr int kUnaryOperationHintIndex = 0
Detailed Description
Definition at line 40 of file bytecode-graph-builder.cc.
Member Enumeration Documentation
NamedStoreMode
enum v8::internal::compiler::BytecodeGraphBuilder::NamedStoreMode [strong], [private]
Enumerator
kSet
kDefineOwn
Definition at line 231 of file bytecode-graph-builder.cc.
                            {
    // Check the prototype chain before storing.
    kSet,
    // Define value to the receiver without checking the prototype chain.
    kDefineOwn,
  };
Constructor & Destructor Documentation
BytecodeGraphBuilder() [1/2]
v8::internal::compiler::BytecodeGraphBuilder::BytecodeGraphBuilder (JSHeapBroker * broker, Zone * local_zone, NativeContextRef native_context, SharedFunctionInfoRef shared_info, BytecodeArrayRef bytecode, FeedbackCellRef feedback_cell, BytecodeOffset osr_offset, JSGraph * jsgraph, CallFrequency const & invocation_frequency, SourcePositionTable * source_positions, NodeOriginTable * node_origins, int inlining_id, CodeKind code_kind, BytecodeGraphBuilderFlags flags, TickCounter * tick_counter, ObserveNodeInfo const & observe_node_info)
Definition at line 1043 of file bytecode-graph-builder.cc.
    : broker_(broker),
      local_isolate_(broker_->local_isolate()
                         ? broker_->local_isolate()
                         : broker_->isolate()->AsLocalIsolate()),
      local_zone_(local_zone),
      jsgraph_(jsgraph),
      native_context_(native_context),
      shared_info_(shared_info),
      bytecode_array_(bytecode),
      feedback_cell_(feedback_cell),
      feedback_vector_(feedback_cell.feedback_vector(broker).value()),
      invocation_frequency_(invocation_frequency),
      type_hint_lowering_(
          broker, jsgraph, feedback_vector_,
          (flags & BytecodeGraphBuilderFlag::kBailoutOnUninitialized)
              ? JSTypeHintLowering::kBailoutOnUninitialized
              : JSTypeHintLowering::kNoFlags),
      frame_state_function_info_(common()->CreateFrameStateFunctionInfo(
          FrameStateType::kUnoptimizedFunction,
          bytecode_array().parameter_count(), bytecode_array().max_arguments(),
          bytecode_array().register_count(), shared_info.object(),
          bytecode_array().object())),
      source_position_iterator_(bytecode_array().SourcePositionTable(broker)),
      bytecode_iterator_(bytecode_array().object()),
      bytecode_analysis_(
          bytecode_array().object(), local_zone, osr_offset,
          flags & BytecodeGraphBuilderFlag::kAnalyzeEnvironmentLiveness),
      environment_(nullptr),
      decorator_(nullptr),
      osr_(!osr_offset.IsNone()),
      currently_peeled_loop_offset_(-1),
      skip_first_stack_and_tierup_check_(
          flags & BytecodeGraphBuilderFlag::kSkipFirstStackAndTierupCheck),
      merge_environments_(local_zone),
      generator_merge_environments_(local_zone),
      cached_parameters_(local_zone),
      exception_handlers_(local_zone),
      current_exception_handler_(0),
      input_buffer_size_(0),
      input_buffer_(nullptr),
      code_kind_(code_kind),
      feedback_vector_node_(nullptr),
      native_context_node_(nullptr),
      needs_eager_checkpoint_(true),
      exit_controls_(local_zone),
      state_values_cache_(jsgraph),
      node_origins_(node_origins),
      source_positions_(source_positions),
      start_position_(shared_info.StartPosition(), inlining_id),
      tick_counter_(tick_counter),
      observe_node_info_(observe_node_info) {}
References v8::internal::compiler::kAnalyzeEnvironmentLiveness, v8::internal::compiler::kBailoutOnUninitialized, v8::internal::kNoFlags, v8::internal::compiler::kSkipFirstStackAndTierupCheck, and v8::internal::compiler::kUnoptimizedFunction.
BytecodeGraphBuilder() [2/2]
v8::internal::compiler::BytecodeGraphBuilder::BytecodeGraphBuilder (const BytecodeGraphBuilder &) [delete]
Member Function Documentation
AddBytecodePositionDecorator()
void v8::internal::compiler::BytecodeGraphBuilder::AddBytecodePositionDecorator () [private]
Definition at line 1509 of file bytecode-graph-builder.cc.
                                                        {
  DCHECK_NULL(decorator_);
  decorator_ = graph_zone()->New<BytecodePositionDecorator>(node_origins_);
  graph()->AddDecorator(decorator_);
}
References DCHECK_NULL, and graph().
Referenced by CreateGraph().
AdvanceIteratorsTo()
void v8::internal::compiler::BytecodeGraphBuilder::AdvanceIteratorsTo (int bytecode_offset) [private]
Definition at line 1247 of file bytecode-graph-builder.cc.
                                                                 {
  for (; bytecode_iterator().current_offset() != bytecode_offset;
       bytecode_iterator().Advance()) {
    int current_offset = bytecode_iterator().current_offset();
    UpdateSourceAndBytecodePosition(current_offset);
  }
}
AdvanceToOsrEntryAndPeelLoops()
void v8::internal::compiler::BytecodeGraphBuilder::AdvanceToOsrEntryAndPeelLoops () [private]
Definition at line 1374 of file bytecode-graph-builder.cc.
                                                         {
  environment()->FillWithOsrValues();
  // The entry stack check has to happen *before* initialising the OSR prelude;
  // it has to happen before setting up exception handlers, so that the
  // optimized code can't accidentally catch a failingstack with a OSR-ed loop
  // inside a try-catch, e.g.
  //
  // try {
  // loop { OSR(); }
  // } catch {
  // // Ignore failed stack check.
  // }
  BuildOSREntryStackCheck();
  OsrIteratorState iterator_states(this);
  iterator_states.ProcessOsrPrelude();
  int osr_entry = bytecode_analysis().osr_entry_point();
  CHECK_EQ(bytecode_iterator().current_offset(), osr_entry);
  // Suppose we have n nested loops, loop_0 being the outermost one, and
  // loop_n being the OSR loop. We start iterating the bytecode at the header
  // of loop_n (the OSR loop), and then we peel the part of the the body of
  // loop_{n-1} following the end of loop_n. We then rewind the iterator to
  // the header of loop_{n-1}, and so on until we have partly peeled loop 0.
  // The full loop_0 body will be generating with the rest of the function,
  // outside the OSR generation.
  // To do so, if we are visiting a loop, we continue to visit what's left
  // of its parent, and then when reaching the parent's JumpLoop, we do not
  // create any jump for that but rewind the bytecode iterator to visit the
  // parent loop entirely, and so on.
  int current_parent_offset =
      bytecode_analysis().GetLoopInfoFor(osr_entry).parent_offset();
  while (current_parent_offset != -1) {
    const LoopInfo& current_parent_loop =
        bytecode_analysis().GetLoopInfoFor(current_parent_offset);
    // We iterate until the back edge of the parent loop, which we detect by
    // the offset that the JumpLoop targets.
    for (; !bytecode_iterator().done(); bytecode_iterator().Advance()) {
      if (bytecode_iterator().current_bytecode() ==
              interpreter::Bytecode::kJumpLoop &&
          bytecode_iterator().GetJumpTargetOffset() == current_parent_offset) {
        // Reached the end of the current parent loop.
        break;
      }
      VisitSingleBytecode();
    }
    DCHECK(!bytecode_iterator()
                .done()); // Should have found the loop's jump target.
    // We also need to take care of the merge environments and exceptions
    // handlers here because the omitted JumpLoop bytecode can still be the
    // target of jumps or the first bytecode after a try block.
    ExitThenEnterExceptionHandlers(bytecode_iterator().current_offset());
    SwitchToMergeEnvironment(bytecode_iterator().current_offset());
    // This jump is the jump of our parent loop, which is not yet created.
    // So we do not build the jump nodes, but restore the bytecode and the
    // SourcePosition iterators to the values they had when we were visiting
    // the offset pointed at by the JumpLoop we've just reached.
    // We have already built nodes for inner loops, but now we will
    // iterate again over them and build new nodes corresponding to the same
    // bytecode offsets. Any jump or reference to this inner loops must now
    // point to the new nodes we will build, hence we clear the relevant part
    // of the environment.
    // Completely clearing the environment is not possible because merge
    // environments for forward jumps out of the loop need to be preserved
    // (e.g. a return or a labeled break in the middle of a loop).
    RemoveMergeEnvironmentsBeforeOffset(bytecode_iterator().current_offset());
    iterator_states.RestoreState(current_parent_offset,
                                 current_parent_loop.parent_offset());
    current_parent_offset = current_parent_loop.parent_offset();
  }
}
References CHECK_EQ, v8::internal::DCHECK(), v8::internal::compiler::LoopInfo::parent_offset(), v8::internal::compiler::BytecodeGraphBuilder::OsrIteratorState::ProcessOsrPrelude(), and v8::internal::compiler::BytecodeGraphBuilder::OsrIteratorState::RestoreState().
ApplyEarlyReduction()
void v8::internal::compiler::BytecodeGraphBuilder::ApplyEarlyReduction (JSTypeHintLowering::LoweringResult reduction) [private]
Definition at line 4415 of file bytecode-graph-builder.cc.
                                                {
  if (reduction.IsExit()) {
    MergeControlToLeaveFunction(reduction.control());
  } else if (reduction.IsSideEffectFree()) {
    environment()->UpdateEffectDependency(reduction.effect());
    environment()->UpdateControlDependency(reduction.control());
  } else {
    DCHECK(!reduction.Changed());
    // At the moment, we assume side-effect free reduction. To support
    // side-effects, we would have to invalidate the eager checkpoint,
    // so that deoptimization does not repeat the side effect.
  }
}
References v8::internal::compiler::JSTypeHintLowering::LoweringResult::Changed(), v8::internal::compiler::JSTypeHintLowering::LoweringResult::control(), v8::internal::DCHECK(), v8::internal::compiler::JSTypeHintLowering::LoweringResult::effect(), v8::internal::compiler::JSTypeHintLowering::LoweringResult::IsExit(), and v8::internal::compiler::JSTypeHintLowering::LoweringResult::IsSideEffectFree().
broker()
JSHeapBroker* v8::internal::compiler::BytecodeGraphBuilder::broker () const [inline], [private]
Definition at line 443 of file bytecode-graph-builder.cc.
{ return broker_; }
References broker_.
Referenced by BuildLoadFeedbackCell(), CreateFeedbackVectorNode(), CreateNativeContextNode(), and MakeRefForConstantForIndexOperand().
BuildBinaryOp()
void v8::internal::compiler::BytecodeGraphBuilder::BuildBinaryOp (const Operator * op) [private]
Definition at line 3055 of file bytecode-graph-builder.cc.
                                                           {
  DCHECK(JSOperator::IsBinaryWithFeedback(op->opcode()));
  PrepareEagerCheckpoint();
  Node* left =
      environment()->LookupRegister(bytecode_iterator().GetRegisterOperand(0));
  Node* right = environment()->LookupAccumulator();
  FeedbackSlot slot =
      bytecode_iterator().GetSlotOperand(kBinaryOperationHintIndex);
  JSTypeHintLowering::LoweringResult lowering =
      TryBuildSimplifiedBinaryOp(op, left, right, slot);
  if (lowering.IsExit()) return;
  Node* node = nullptr;
  if (lowering.IsSideEffectFree()) {
    node = lowering.value();
  } else {
    DCHECK(!lowering.Changed());
    DCHECK(IrOpcode::IsFeedbackCollectingOpcode(op->opcode()));
    node = NewNode(op, left, right, feedback_vector_node());
  }
  environment()->BindAccumulator(node, Environment::kAttachFrameState);
}
References v8::internal::compiler::JSTypeHintLowering::LoweringResult::Changed(), v8::internal::DCHECK(), v8::internal::compiler::JSTypeHintLowering::LoweringResult::IsExit(), v8::internal::compiler::JSTypeHintLowering::LoweringResult::IsSideEffectFree(), v8::internal::compiler::Operator::opcode(), and v8::internal::compiler::JSTypeHintLowering::LoweringResult::value().
BuildBinaryOpWithImmediate()
void v8::internal::compiler::BytecodeGraphBuilder::BuildBinaryOpWithImmediate (const Operator * op) [private]
Definition at line 3248 of file bytecode-graph-builder.cc.
                                                                        {
  DCHECK(JSOperator::IsBinaryWithFeedback(op->opcode()));
  PrepareEagerCheckpoint();
  Node* left = environment()->LookupAccumulator();
  Node* right =
      jsgraph()->ConstantNoHole(bytecode_iterator().GetImmediateOperand(0));
  FeedbackSlot slot =
      bytecode_iterator().GetSlotOperand(kBinaryOperationSmiHintIndex);
  JSTypeHintLowering::LoweringResult lowering =
      TryBuildSimplifiedBinaryOp(op, left, right, slot);
  if (lowering.IsExit()) return;
  Node* node = nullptr;
  if (lowering.IsSideEffectFree()) {
    node = lowering.value();
  } else {
    DCHECK(!lowering.Changed());
    DCHECK(IrOpcode::IsFeedbackCollectingOpcode(op->opcode()));
    node = NewNode(op, left, right, feedback_vector_node());
  }
  environment()->BindAccumulator(node, Environment::kAttachFrameState);
}
References v8::internal::compiler::JSTypeHintLowering::LoweringResult::Changed(), v8::internal::DCHECK(), v8::internal::compiler::JSTypeHintLowering::LoweringResult::IsExit(), v8::internal::compiler::JSTypeHintLowering::LoweringResult::IsSideEffectFree(), v8::internal::compiler::Operator::opcode(), and v8::internal::compiler::JSTypeHintLowering::LoweringResult::value().
BuildCall() [1/2]
void v8::internal::compiler::BytecodeGraphBuilder::BuildCall (ConvertReceiverMode receiver_mode, Node *const * args, size_t arg_count, int slot_id) [private]
Definition at line 2526 of file bytecode-graph-builder.cc.
                                                  {
  DCHECK_EQ(interpreter::Bytecodes::GetReceiverMode(
                bytecode_iterator().current_bytecode()),
            receiver_mode);
  PrepareEagerCheckpoint();
  FeedbackSource feedback = CreateFeedbackSource(slot_id);
  CallFrequency frequency = ComputeCallFrequency(slot_id);
  SpeculationMode speculation_mode = GetSpeculationMode(slot_id);
  CallFeedbackRelation call_feedback_relation =
      ComputeCallFeedbackRelation(slot_id);
  const Operator* op =
      javascript()->Call(arg_count, frequency, feedback, receiver_mode,
                         speculation_mode, call_feedback_relation);
  DCHECK(IrOpcode::IsFeedbackCollectingOpcode(op->opcode()));
  Node* node = MakeNode(op, static_cast<int>(arg_count), args);
  environment()->BindAccumulator(node, Environment::kAttachFrameState);
}
References v8::base::args, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::interpreter::Bytecodes::GetReceiverMode(), v8::internal::torque::MakeNode(), and v8::internal::compiler::Operator::opcode().
Referenced by BuildCall().
BuildCall() [2/2]
void v8::internal::compiler::BytecodeGraphBuilder::BuildCall (ConvertReceiverMode receiver_mode, std::initializer_list< Node * > args, int slot_id) [inline], [private]
Definition at line 245 of file bytecode-graph-builder.cc.
                                                               {
    BuildCall(receiver_mode, args.begin(), args.size(), slot_id);
  }
References v8::base::args, and BuildCall().
BuildCallVarArgs()
void v8::internal::compiler::BytecodeGraphBuilder::BuildCallVarArgs (ConvertReceiverMode receiver_mode) [private]
Definition at line 2572 of file bytecode-graph-builder.cc.
                                                                             {
  DCHECK_EQ(interpreter::Bytecodes::GetReceiverMode(
                bytecode_iterator().current_bytecode()),
            receiver_mode);
  Node* callee =
      environment()->LookupRegister(bytecode_iterator().GetRegisterOperand(0));
  interpreter::Register first_reg = bytecode_iterator().GetRegisterOperand(1);
  size_t reg_count = bytecode_iterator().GetRegisterCountOperand(2);
  int const slot_id = bytecode_iterator().GetIndexOperand(3);
  int arg_count = receiver_mode == ConvertReceiverMode::kNullOrUndefined
                      ? static_cast<int>(reg_count)
                      : static_cast<int>(reg_count) - 1;
  Node* const* call_args =
      ProcessCallVarArgs(receiver_mode, callee, first_reg, arg_count);
  BuildCall(receiver_mode, call_args, JSCallNode::ArityForArgc(arg_count),
            slot_id);
}
References DCHECK_EQ, v8::internal::interpreter::Bytecodes::GetReceiverMode(), and v8::internal::kNullOrUndefined.
BuildCastOperator()
void v8::internal::compiler::BytecodeGraphBuilder::BuildCastOperator (const Operator * op) [private]
Definition at line 3585 of file bytecode-graph-builder.cc.
                                                                  {
  Node* value = NewNode(js_op, environment()->LookupAccumulator());
  environment()->BindRegister(bytecode_iterator().GetRegisterOperand(0), value,
                              Environment::kAttachFrameState);
}
References v8::internal::value.
BuildCompareOp()
void v8::internal::compiler::BytecodeGraphBuilder::BuildCompareOp (const Operator * op) [private]
Definition at line 3424 of file bytecode-graph-builder.cc.
                                                            {
  DCHECK(JSOperator::IsBinaryWithFeedback(op->opcode()));
  PrepareEagerCheckpoint();
  Node* left =
      environment()->LookupRegister(bytecode_iterator().GetRegisterOperand(0));
  Node* right = environment()->LookupAccumulator();
  FeedbackSlot slot = bytecode_iterator().GetSlotOperand(1);
  JSTypeHintLowering::LoweringResult lowering =
      TryBuildSimplifiedBinaryOp(op, left, right, slot);
  if (lowering.IsExit()) return;
  Node* node = nullptr;
  if (lowering.IsSideEffectFree()) {
    node = lowering.value();
  } else {
    DCHECK(!lowering.Changed());
    DCHECK(IrOpcode::IsFeedbackCollectingOpcode(op->opcode()));
    node = NewNode(op, left, right, feedback_vector_node());
  }
  environment()->BindAccumulator(node, Environment::kAttachFrameState);
}
References v8::internal::compiler::JSTypeHintLowering::LoweringResult::Changed(), v8::internal::DCHECK(), v8::internal::compiler::JSTypeHintLowering::LoweringResult::IsExit(), v8::internal::compiler::JSTypeHintLowering::LoweringResult::IsSideEffectFree(), v8::internal::compiler::Operator::opcode(), and v8::internal::compiler::JSTypeHintLowering::LoweringResult::value().
BuildCreateArguments()
void v8::internal::compiler::BytecodeGraphBuilder::BuildCreateArguments (CreateArgumentsType type) [private]
Definition at line 2379 of file bytecode-graph-builder.cc.
                                                                        {
  const Operator* op = javascript()->CreateArguments(type);
  Node* object = NewNode(op, GetFunctionClosure());
  environment()->BindAccumulator(object, Environment::kAttachFrameState);
}
References v8::internal::tracing::type.
BuildDelete()
void v8::internal::compiler::BytecodeGraphBuilder::BuildDelete (LanguageMode language_mode) [private]
Definition at line 3377 of file bytecode-graph-builder.cc.
                                                                 {
  PrepareEagerCheckpoint();
  Node* key = environment()->LookupAccumulator();
  Node* object =
      environment()->LookupRegister(bytecode_iterator().GetRegisterOperand(0));
  Node* mode = jsgraph()->ConstantNoHole(static_cast<int32_t>(language_mode));
  Node* node = NewNode(javascript()->DeleteProperty(), object, key, mode);
  environment()->BindAccumulator(node, Environment::kAttachFrameState);
}
References v8::internal::anonymous_namespace{runtime-object.cc}::DeleteProperty(), v8::internal::key, and mode().
BuildFunctionEntryStackCheck()
void v8::internal::compiler::BytecodeGraphBuilder::BuildFunctionEntryStackCheck () [private]
Definition at line 1349 of file bytecode-graph-builder.cc.
                                                        {
  if (!skip_first_stack_check()) {
    DCHECK(exception_handlers_.empty());
    Node* node =
        NewNode(javascript()->StackCheck(StackCheckKind::kJSFunctionEntry));
    PrepareFrameStateForFunctionEntryStackCheck(node);
  }
}
References v8::internal::DCHECK().
BuildHoleCheckAndThrow()
void v8::internal::compiler::BytecodeGraphBuilder::BuildHoleCheckAndThrow (Node * condition, Runtime::FunctionId runtime_id, Node * name = nullptr) [private]
Definition at line 2952 of file bytecode-graph-builder.cc.
                                                               {
  Node* accumulator = environment()->LookupAccumulator();
  NewBranch(condition, BranchHint::kFalse);
  {
    SubEnvironment sub_environment(this);
    NewIfTrue();
    BuildLoopExitsForFunctionExit(bytecode_analysis().GetInLivenessFor(
        bytecode_iterator().current_offset()));
    Node* node;
    const Operator* op = javascript()->CallRuntime(runtime_id);
    if (runtime_id == Runtime::kThrowAccessedUninitializedVariable) {
      DCHECK_NOT_NULL(name);
      node = NewNode(op, name);
    } else {
      DCHECK(runtime_id == Runtime::kThrowSuperAlreadyCalledError ||
             runtime_id == Runtime::kThrowSuperNotCalled);
      node = NewNode(op);
    }
    environment()->RecordAfterState(node, Environment::kAttachFrameState);
    Node* control = NewNode(common()->Throw());
    MergeControlToLeaveFunction(control);
  }
  NewIfFalse();
  environment()->BindAccumulator(accumulator);
}
References v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::kFalse, and v8::internal::name.
BuildIterationBodyStackCheck()
void v8::internal::compiler::BytecodeGraphBuilder::BuildIterationBodyStackCheck () [private]
Definition at line 1358 of file bytecode-graph-builder.cc.
                                                        {
  Node* node =
      NewNode(javascript()->StackCheck(StackCheckKind::kJSIterationBody));
  environment()->RecordAfterState(node, Environment::kAttachFrameState);
}
BuildJump()
void v8::internal::compiler::BytecodeGraphBuilder::BuildJump () [private]
Definition at line 4171 of file bytecode-graph-builder.cc.
                                     {
  MergeIntoSuccessorEnvironment(bytecode_iterator().GetJumpTargetOffset());
}
BuildJumpIf()
void v8::internal::compiler::BytecodeGraphBuilder::BuildJumpIf (Node * condition) [private]
Definition at line 4175 of file bytecode-graph-builder.cc.
                                                      {
  NewBranch(condition, BranchHint::kNone);
  {
    SubEnvironment sub_environment(this);
    NewIfTrue();
    MergeIntoSuccessorEnvironment(bytecode_iterator().GetJumpTargetOffset());
  }
  NewIfFalse();
}
References v8::internal::kNone.
BuildJumpIfEqual()
void v8::internal::compiler::BytecodeGraphBuilder::BuildJumpIfEqual (Node * comperand) [private]
Definition at line 4195 of file bytecode-graph-builder.cc.
                                                           {
  Node* accumulator = environment()->LookupAccumulator();
  Node* condition =
      NewNode(simplified()->ReferenceEqual(), accumulator, comperand);
  BuildJumpIf(condition);
}
BuildJumpIfFalse()
void v8::internal::compiler::BytecodeGraphBuilder::BuildJumpIfFalse () [private]
Definition at line 4209 of file bytecode-graph-builder.cc.
                                            {
  NewBranch(environment()->LookupAccumulator(), BranchHint::kNone);
  {
    SubEnvironment sub_environment(this);
    NewIfFalse();
    environment()->BindAccumulator(jsgraph()->FalseConstant());
    MergeIntoSuccessorEnvironment(bytecode_iterator().GetJumpTargetOffset());
  }
  NewIfTrue();
  environment()->BindAccumulator(jsgraph()->TrueConstant());
}
References v8::internal::kNone.
BuildJumpIfForInDone()
void v8::internal::compiler::BytecodeGraphBuilder::BuildJumpIfForInDone () [private]
Definition at line 4258 of file bytecode-graph-builder.cc.
                                                {
  // There's an eager checkpoint here for the speculative comparison, but it can
  // never actually deopt because these are known to be Smi.
  PrepareEagerCheckpoint();
  Node* index =
      environment()->LookupRegister(bytecode_iterator().GetRegisterOperand(1));
  Node* cache_length =
      environment()->LookupRegister(bytecode_iterator().GetRegisterOperand(2));
  Node* condition = NewNode(
      simplified()->SpeculativeNumberEqual(NumberOperationHint::kSignedSmall),
      index, cache_length);
  BuildJumpIf(condition);
}
References v8::internal::index.
BuildJumpIfJSReceiver()
void v8::internal::compiler::BytecodeGraphBuilder::BuildJumpIfJSReceiver () [private]
Definition at line 4252 of file bytecode-graph-builder.cc.
                                                 {
  Node* accumulator = environment()->LookupAccumulator();
  Node* condition = NewNode(simplified()->ObjectIsReceiver(), accumulator);
  BuildJumpIf(condition);
}
BuildJumpIfNot()
void v8::internal::compiler::BytecodeGraphBuilder::BuildJumpIfNot (Node * condition) [private]
Definition at line 4185 of file bytecode-graph-builder.cc.
                                                         {
  NewBranch(condition, BranchHint::kNone);
  {
    SubEnvironment sub_environment(this);
    NewIfFalse();
    MergeIntoSuccessorEnvironment(bytecode_iterator().GetJumpTargetOffset());
  }
  NewIfTrue();
}
References v8::internal::kNone.
BuildJumpIfNotEqual()
void v8::internal::compiler::BytecodeGraphBuilder::BuildJumpIfNotEqual (Node * comperand) [private]
Definition at line 4202 of file bytecode-graph-builder.cc.
                                                              {
  Node* accumulator = environment()->LookupAccumulator();
  Node* condition =
      NewNode(simplified()->ReferenceEqual(), accumulator, comperand);
  BuildJumpIfNot(condition);
}
BuildJumpIfNotHole()
void v8::internal::compiler::BytecodeGraphBuilder::BuildJumpIfNotHole () [private]
Definition at line 4245 of file bytecode-graph-builder.cc.
                                              {
  Node* accumulator = environment()->LookupAccumulator();
  Node* condition = NewNode(simplified()->ReferenceEqual(), accumulator,
                            jsgraph()->TheHoleConstant());
  BuildJumpIfNot(condition);
}
BuildJumpIfToBooleanFalse()
void v8::internal::compiler::BytecodeGraphBuilder::BuildJumpIfToBooleanFalse () [private]
Definition at line 4239 of file bytecode-graph-builder.cc.
                                                     {
  Node* accumulator = environment()->LookupAccumulator();
  Node* condition = NewNode(simplified()->ToBoolean(), accumulator);
  BuildJumpIfNot(condition);
}
BuildJumpIfToBooleanTrue()
void v8::internal::compiler::BytecodeGraphBuilder::BuildJumpIfToBooleanTrue () [private]
Definition at line 4233 of file bytecode-graph-builder.cc.
                                                    {
  Node* accumulator = environment()->LookupAccumulator();
  Node* condition = NewNode(simplified()->ToBoolean(), accumulator);
  BuildJumpIf(condition);
}
BuildJumpIfTrue()
void v8::internal::compiler::BytecodeGraphBuilder::BuildJumpIfTrue () [private]
Definition at line 4221 of file bytecode-graph-builder.cc.
                                           {
  NewBranch(environment()->LookupAccumulator(), BranchHint::kNone);
  {
    SubEnvironment sub_environment(this);
    NewIfTrue();
    environment()->BindAccumulator(jsgraph()->TrueConstant());
    MergeIntoSuccessorEnvironment(bytecode_iterator().GetJumpTargetOffset());
  }
  NewIfFalse();
  environment()->BindAccumulator(jsgraph()->FalseConstant());
}
References v8::internal::kNone.
BuildLdaLookupContextSlot()
void v8::internal::compiler::BytecodeGraphBuilder::BuildLdaLookupContextSlot (ContextMode context_mode, TypeofMode typeof_mode) [private]
Definition at line 1930 of file bytecode-graph-builder.cc.
                                                                             {
  uint32_t depth = bytecode_iterator().GetUnsignedImmediateOperand(2);
  // Check if any context in the depth has an extension.
  Environment* slow_environment = CheckContextExtensions(depth);
  // Fast path, do a context load.
  {
    uint32_t slot_index = bytecode_iterator().GetIndexOperand(1);
    const Operator* op =
        context_mode == ContextMode::kHasContextCells
            ? javascript()->LoadContext(depth, slot_index)
            : javascript()->LoadContextNoCell(depth, slot_index, false);
    environment()->BindAccumulator(NewNode(op));
  }
  if (!slow_environment) {
    // The slow path was fully replaced by a set of compilation dependencies.
    return;
  }
  // Add a merge to the fast environment.
  NewMerge();
  Environment* fast_environment = environment();
  // Slow path, do a runtime load lookup.
  set_environment(slow_environment);
  {
    Node* name = jsgraph()->ConstantNoHole(MakeRefForConstantForIndexOperand(0),
                                           broker());
    const Operator* op =
        javascript()->CallRuntime(typeof_mode == TypeofMode::kNotInside
                                      ? Runtime::kLoadLookupSlot
                                      : Runtime::kLoadLookupSlotInsideTypeof);
    Node* value = NewNode(op, name);
    environment()->BindAccumulator(value, Environment::kAttachFrameState);
  }
  fast_environment->Merge(environment(),
                          bytecode_analysis().GetOutLivenessFor(
                              bytecode_iterator().current_offset()));
  set_environment(fast_environment);
  mark_as_needing_eager_checkpoint(true);
}
References broker(), v8::internal::kHasContextCells, v8::internal::kNotInside, v8::internal::compiler::BytecodeGraphBuilder::Environment::Merge(), v8::internal::name, and v8::internal::value.
BuildLdaLookupGlobalSlot()
void v8::internal::compiler::BytecodeGraphBuilder::BuildLdaLookupGlobalSlot (TypeofMode typeof_mode) [private]
Definition at line 1995 of file bytecode-graph-builder.cc.
                                                                          {
  uint32_t depth = bytecode_iterator().GetUnsignedImmediateOperand(2);
  // Check if any context in the depth has an extension.
  Environment* slow_environment = CheckContextExtensions(depth);
  // Fast path, do a global load.
  {
    PrepareEagerCheckpoint();
    NameRef name = MakeRefForConstantForIndexOperand<Name>(0);
    uint32_t feedback_slot_index = bytecode_iterator().GetIndexOperand(1);
    Node* node = BuildLoadGlobal(name, feedback_slot_index, typeof_mode);
    environment()->BindAccumulator(node, Environment::kAttachFrameState);
  }
  if (!slow_environment) {
    // The slow path was fully replaced by a set of compilation dependencies.
    return;
  }
  // Add a merge to the fast environment.
  NewMerge();
  Environment* fast_environment = environment();
  // Slow path, do a runtime load lookup.
  set_environment(slow_environment);
  {
    Node* name = jsgraph()->ConstantNoHole(
        MakeRefForConstantForIndexOperand<Name>(0), broker());
    const Operator* op =
        javascript()->CallRuntime(typeof_mode == TypeofMode::kNotInside
                                      ? Runtime::kLoadLookupSlot
                                      : Runtime::kLoadLookupSlotInsideTypeof);
    Node* value = NewNode(op, name);
    environment()->BindAccumulator(value, Environment::kAttachFrameState);
  }
  fast_environment->Merge(environment(),
                          bytecode_analysis().GetOutLivenessFor(
                              bytecode_iterator().current_offset()));
  set_environment(fast_environment);
  mark_as_needing_eager_checkpoint(true);
}
References broker(), v8::internal::kNotInside, v8::internal::compiler::BytecodeGraphBuilder::Environment::Merge(), v8::internal::name, and v8::internal::value.
BuildLdaLookupSlot()
void v8::internal::compiler::BytecodeGraphBuilder::BuildLdaLookupSlot (TypeofMode typeof_mode) [private]
Definition at line 1784 of file bytecode-graph-builder.cc.
                                                                    {
  PrepareEagerCheckpoint();
  Node* name =
      jsgraph()->ConstantNoHole(MakeRefForConstantForIndexOperand(0), broker());
  const Operator* op =
      javascript()->CallRuntime(typeof_mode == TypeofMode::kNotInside
                                    ? Runtime::kLoadLookupSlot
                                    : Runtime::kLoadLookupSlotInsideTypeof);
  Node* value = NewNode(op, name);
  environment()->BindAccumulator(value, Environment::kAttachFrameState);
}
References broker(), v8::internal::kNotInside, v8::internal::name, and v8::internal::value.
BuildLoadFeedbackCell()
Node * v8::internal::compiler::BytecodeGraphBuilder::BuildLoadFeedbackCell (int index) [private]
Definition at line 1138 of file bytecode-graph-builder.cc.
                                                           {
  return jsgraph()->ConstantNoHole(
      feedback_vector().GetClosureFeedbackCell(broker(), index), broker());
}
References broker(), v8::internal::compiler::JSGraph::ConstantNoHole(), feedback_vector(), v8::internal::index, and jsgraph().
BuildLoadGlobal()
Node * v8::internal::compiler::BytecodeGraphBuilder::BuildLoadGlobal (NameRef name, uint32_t feedback_slot_index, TypeofMode typeof_mode) [private]
Definition at line 1590 of file bytecode-graph-builder.cc.
                                                                    {
  FeedbackSource feedback = CreateFeedbackSource(feedback_slot_index);
  DCHECK(IsLoadGlobalICKind(broker()->GetFeedbackSlotKind(feedback)));
  const Operator* op = javascript()->LoadGlobal(name, feedback, typeof_mode);
  DCHECK(IrOpcode::IsFeedbackCollectingOpcode(op->opcode()));
  return NewNode(op, feedback_vector_node());
}
References broker(), v8::internal::DCHECK(), v8::internal::IsLoadGlobalICKind(), v8::internal::name, and v8::internal::compiler::Operator::opcode().
BuildLoadNativeContextField()
Node * v8::internal::compiler::BytecodeGraphBuilder::BuildLoadNativeContextField (int index) [private]
Definition at line 1148 of file bytecode-graph-builder.cc.
                                                                 {
  Node* result = NewNode(javascript()->LoadContextNoCell(0, index, true));
  NodeProperties::ReplaceContextInput(result, native_context_node());
  return result;
}
References v8::internal::index, javascript(), native_context_node(), NewNode(), v8::internal::compiler::NodeProperties::ReplaceContextInput(), and v8::base::internal::result.
BuildLoopExitsForBranch()
void v8::internal::compiler::BytecodeGraphBuilder::BuildLoopExitsForBranch (int target_offset) [private]
Definition at line 4138 of file bytecode-graph-builder.cc.
                                                                    {
  int origin_offset = bytecode_iterator().current_offset();
  // Only build loop exits for forward edges.
  if (target_offset > origin_offset) {
    BuildLoopExitsUntilLoop(
        bytecode_analysis().GetLoopOffsetFor(target_offset),
        bytecode_analysis().GetInLivenessFor(target_offset));
  }
}
BuildLoopExitsForFunctionExit()
void v8::internal::compiler::BytecodeGraphBuilder::BuildLoopExitsForFunctionExit (const BytecodeLivenessState * liveness) [private]
Definition at line 4166 of file bytecode-graph-builder.cc.
                                           {
  BuildLoopExitsUntilLoop(-1, liveness);
}
BuildLoopExitsUntilLoop()
void v8::internal::compiler::BytecodeGraphBuilder::BuildLoopExitsUntilLoop (int loop_offset, const BytecodeLivenessState * liveness) [private]
Definition at line 4148 of file bytecode-graph-builder.cc.
                                                            {
  int origin_offset = bytecode_iterator().current_offset();
  int current_loop = bytecode_analysis().GetLoopOffsetFor(origin_offset);
  // The limit_offset is the stop offset for building loop exists, used for OSR.
  // It prevents the creations of loopexits for loops which do not exist.
  loop_offset = std::max(loop_offset, currently_peeled_loop_offset_);
  while (loop_offset < current_loop) {
    Node* loop_node = merge_environments_[current_loop]->GetControlDependency();
    const LoopInfo& loop_info =
        bytecode_analysis().GetLoopInfoFor(current_loop);
    environment()->PrepareForLoopExit(loop_node, loop_info.assignments(),
                                      liveness);
    current_loop = loop_info.parent_offset();
  }
}
References v8::internal::compiler::LoopInfo::assignments(), and v8::internal::compiler::LoopInfo::parent_offset().
BuildLoopHeaderEnvironment()
void v8::internal::compiler::BytecodeGraphBuilder::BuildLoopHeaderEnvironment (int current_offset) [private]
Definition at line 4081 of file bytecode-graph-builder.cc.
                                                                        {
  if (bytecode_analysis().IsLoopHeader(current_offset)) {
    mark_as_needing_eager_checkpoint(true);
    const LoopInfo& loop_info =
        bytecode_analysis().GetLoopInfoFor(current_offset);
    const BytecodeLivenessState* liveness =
        bytecode_analysis().GetInLivenessFor(current_offset);
    const auto& resume_jump_targets = loop_info.resume_jump_targets();
    bool generate_suspend_switch = !resume_jump_targets.empty();
    // Add loop header.
    environment()->PrepareForLoop(loop_info.assignments(), liveness);
    // Store a copy of the environment so we can connect merged back edge inputs
    // to the loop header.
    merge_environments_[current_offset] = environment()->Copy();
    // If this loop contains resumes, create a new switch just after the loop
    // for those resumes.
    if (generate_suspend_switch) {
      BuildSwitchOnGeneratorState(loop_info.resume_jump_targets(), true);
      // TODO(leszeks): At this point we know we are executing rather than
      // resuming, so we should be able to prune off the phis in the environment
      // related to the resume path.
      // Set the generator state to a known constant.
      environment()->BindGeneratorState(
          jsgraph()->SmiConstant(JSGeneratorObject::kGeneratorExecuting));
    }
  }
}
References v8::internal::compiler::LoopInfo::assignments(), v8::internal::JSGeneratorObject::kGeneratorExecuting, and v8::internal::compiler::LoopInfo::resume_jump_targets().
BuildNamedStore()
void v8::internal::compiler::BytecodeGraphBuilder::BuildNamedStore (NamedStoreMode store_mode) [private]
Definition at line 2166 of file bytecode-graph-builder.cc.
                                                                    {
  PrepareEagerCheckpoint();
  Node* value = environment()->LookupAccumulator();
  Node* object =
      environment()->LookupRegister(bytecode_iterator().GetRegisterOperand(0));
  NameRef name = MakeRefForConstantForIndexOperand<Name>(1);
  FeedbackSource feedback =
      CreateFeedbackSource(bytecode_iterator().GetIndexOperand(2));
  const Operator* op;
  if (store_mode == NamedStoreMode::kDefineOwn) {
    DCHECK_EQ(FeedbackSlotKind::kDefineNamedOwn,
              broker()->GetFeedbackSlotKind(feedback));
    op = javascript()->DefineNamedOwnProperty(name, feedback);
  } else {
    DCHECK_EQ(NamedStoreMode::kSet, store_mode);
    LanguageMode language_mode =
        GetLanguageModeFromSlotKind(broker()->GetFeedbackSlotKind(feedback));
    op = javascript()->SetNamedProperty(language_mode, name, feedback);
  }
  JSTypeHintLowering::LoweringResult lowering =
      TryBuildSimplifiedStoreNamed(op, object, value, feedback.slot);
  if (lowering.IsExit()) return;
  Node* node = nullptr;
  if (lowering.IsSideEffectFree()) {
    node = lowering.value();
  } else {
    DCHECK(!lowering.Changed());
    DCHECK(IrOpcode::IsFeedbackCollectingOpcode(op->opcode()));
    node = NewNode(op, object, value, feedback_vector_node());
  }
  environment()->RecordAfterState(node, Environment::kAttachFrameState);
}
References broker(), v8::internal::compiler::JSTypeHintLowering::LoweringResult::Changed(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::GetLanguageModeFromSlotKind(), v8::internal::compiler::JSTypeHintLowering::LoweringResult::IsExit(), v8::internal::compiler::JSTypeHintLowering::LoweringResult::IsSideEffectFree(), v8::internal::kDefineNamedOwn, v8::internal::name, v8::internal::compiler::Operator::opcode(), v8::internal::compiler::FeedbackSource::slot, v8::internal::compiler::JSTypeHintLowering::LoweringResult::value(), and v8::internal::value.
BuildOSREntryStackCheck()
void v8::internal::compiler::BytecodeGraphBuilder::BuildOSREntryStackCheck () [private]
Definition at line 1364 of file bytecode-graph-builder.cc.
                                                   {
  DCHECK(exception_handlers_.empty());
  Node* node =
      NewNode(javascript()->StackCheck(StackCheckKind::kJSFunctionEntry));
  PrepareFrameStateForOSREntryStackCheck(node);
}
References v8::internal::DCHECK().
BuildReturn()
void v8::internal::compiler::BytecodeGraphBuilder::BuildReturn (const BytecodeLivenessState * liveness) [private]
Definition at line 3767 of file bytecode-graph-builder.cc.
                                                                            {
  BuildLoopExitsForFunctionExit(liveness);
  Node* pop_node = jsgraph()->ZeroConstant();
  Node* control =
      NewNode(common()->Return(), pop_node, environment()->LookupAccumulator());
  MergeControlToLeaveFunction(control);
}
BuildSwitchOnGeneratorState()
void v8::internal::compiler::BytecodeGraphBuilder::BuildSwitchOnGeneratorState (const ZoneVector< ResumeJumpTarget > & resume_jump_targets, bool allow_fallthrough_on_executing) [private]
Definition at line 3953 of file bytecode-graph-builder.cc.
                                         {
  Node* generator_state = environment()->LookupGeneratorState();
  int extra_cases = allow_fallthrough_on_executing ? 2 : 1;
  NewSwitch(generator_state,
            static_cast<int>(resume_jump_targets.size() + extra_cases));
  for (const ResumeJumpTarget& target : resume_jump_targets) {
    SubEnvironment sub_environment(this);
    NewIfValue(target.suspend_id());
    if (target.is_leaf()) {
      // Mark that we are resuming executing.
      environment()->BindGeneratorState(
          jsgraph()->SmiConstant(JSGeneratorObject::kGeneratorExecuting));
    }
    // Jump to the target offset, whether it's a loop header or the resume.
    MergeIntoSuccessorEnvironment(target.target_offset());
  }
  {
    SubEnvironment sub_environment(this);
    // We should never hit the default case (assuming generator state cannot be
    // corrupted), so abort if we do.
    // TODO(leszeks): Maybe only check this in debug mode, and otherwise use
    // the default to represent one of the cases above/fallthrough below?
    NewIfDefault();
    NewNode(simplified()->RuntimeAbort(AbortReason::kInvalidJumpTableIndex));
    // TODO(7099): Investigate if we need LoopExit here.
    Node* control = NewNode(common()->Throw());
    MergeControlToLeaveFunction(control);
  }
  if (allow_fallthrough_on_executing) {
    // If we are executing (rather than resuming), and we allow it, just fall
    // through to the actual loop body.
    NewIfValue(JSGeneratorObject::kGeneratorExecuting);
  } else {
    // Otherwise, this environment is dead.
    set_environment(nullptr);
  }
}
References v8::internal::JSGeneratorObject::kGeneratorExecuting, and v8::internal::ZoneVector< T >::size().
BuildSwitchOnSmi()
void v8::internal::compiler::BytecodeGraphBuilder::BuildSwitchOnSmi (Node * condition) [private]
Definition at line 3740 of file bytecode-graph-builder.cc.
                                                           {
  interpreter::JumpTableTargetOffsets offsets =
      bytecode_iterator().GetJumpTableTargetOffsets();
  NewSwitch(condition, offsets.size() + 1);
  for (interpreter::JumpTableTargetOffset entry : offsets) {
    SubEnvironment sub_environment(this);
    NewIfValue(entry.case_value);
    MergeIntoSuccessorEnvironment(entry.target_offset);
  }
  NewIfDefault();
}
References v8::internal::interpreter::JumpTableTargetOffsets::size().
BuildUnaryOp()
void v8::internal::compiler::BytecodeGraphBuilder::BuildUnaryOp (const Operator * op) [private]
Definition at line 3032 of file bytecode-graph-builder.cc.
                                                          {
  DCHECK(JSOperator::IsUnaryWithFeedback(op->opcode()));
  PrepareEagerCheckpoint();
  Node* operand = environment()->LookupAccumulator();
  FeedbackSlot slot =
      bytecode_iterator().GetSlotOperand(kUnaryOperationHintIndex);
  JSTypeHintLowering::LoweringResult lowering =
      TryBuildSimplifiedUnaryOp(op, operand, slot);
  if (lowering.IsExit()) return;
  Node* node = nullptr;
  if (lowering.IsSideEffectFree()) {
    node = lowering.value();
  } else {
    DCHECK(!lowering.Changed());
    DCHECK(IrOpcode::IsFeedbackCollectingOpcode(op->opcode()));
    node = NewNode(op, operand, feedback_vector_node());
  }
  environment()->BindAccumulator(node, Environment::kAttachFrameState);
}
References v8::internal::compiler::JSTypeHintLowering::LoweringResult::Changed(), v8::internal::DCHECK(), v8::internal::compiler::JSTypeHintLowering::LoweringResult::IsExit(), v8::internal::compiler::JSTypeHintLowering::LoweringResult::IsSideEffectFree(), v8::internal::compiler::Operator::opcode(), and v8::internal::compiler::JSTypeHintLowering::LoweringResult::value().
bytecode_analysis()
BytecodeAnalysis const& v8::internal::compiler::BytecodeGraphBuilder::bytecode_analysis () const [inline], [private]
Definition at line 420 of file bytecode-graph-builder.cc.
                                                    {
    return bytecode_analysis_;
  }
References bytecode_analysis_.
Referenced by PrepareEagerCheckpoint(), PrepareFrameState(), PrepareFrameStateForFunctionEntryStackCheck(), and PrepareFrameStateForOSREntryStackCheck().
bytecode_array()
BytecodeArrayRef v8::internal::compiler::BytecodeGraphBuilder::bytecode_array () const [inline], [private]
Definition at line 403 of file bytecode-graph-builder.cc.
{ return bytecode_array_; }
References bytecode_array_.
Referenced by CreateGraph().
bytecode_iterator() [1/2]
interpreter::BytecodeArrayIterator& v8::internal::compiler::BytecodeGraphBuilder::bytecode_iterator () [inline], [private]
Definition at line 417 of file bytecode-graph-builder.cc.
                                                        {
    return bytecode_iterator_;
  }
References bytecode_iterator_.
bytecode_iterator() [2/2]
interpreter::BytecodeArrayIterator const& v8::internal::compiler::BytecodeGraphBuilder::bytecode_iterator () const [inline], [private]
Definition at line 414 of file bytecode-graph-builder.cc.
                                                                    {
    return bytecode_iterator_;
  }
References bytecode_iterator_.
Referenced by MakeRefForConstantForIndexOperand(), PrepareEagerCheckpoint(), PrepareFrameState(), and PrepareFrameStateForFunctionEntryStackCheck().
CheckContextExtensionAtDepth()
BytecodeGraphBuilder::Environment * v8::internal::compiler::BytecodeGraphBuilder::CheckContextExtensionAtDepth (Environment * slow_environment, uint32_t depth, ContextMode context_mode) [private]
Definition at line 1805 of file bytecode-graph-builder.cc.
                                                                             {
  Node* extension_slot =
      NewNode(context_mode == ContextMode::kHasContextCells
                  ? javascript()->LoadContext(depth, Context::EXTENSION_INDEX)
                  : javascript()->LoadContextNoCell(
                        depth, Context::EXTENSION_INDEX, false));
  Node* check_no_extension =
      NewNode(simplified()->ReferenceEqual(), extension_slot,
              jsgraph()->UndefinedConstant());
  NewBranch(check_no_extension);
  {
    SubEnvironment sub_environment(this);
    NewIfFalse();
    // If there is an extension, merge into the slow path.
    if (slow_environment == nullptr) {
      slow_environment = environment();
      NewMerge();
    } else {
      slow_environment->Merge(environment(),
                              bytecode_analysis().GetInLivenessFor(
                                  bytecode_iterator().current_offset()));
    }
  }
  NewIfTrue();
  // Do nothing on if there is no extension, eventually falling through to
  // the fast path.
  DCHECK_NOT_NULL(slow_environment);
  return slow_environment;
}
References DCHECK_NOT_NULL, v8::internal::Context::EXTENSION_INDEX, v8::internal::kHasContextCells, v8::internal::compiler::BytecodeGraphBuilder::Environment::Merge(), and v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
CheckContextExtensions()
BytecodeGraphBuilder::Environment * v8::internal::compiler::BytecodeGraphBuilder::CheckContextExtensions (uint32_t depth) [private]
Definition at line 1857 of file bytecode-graph-builder.cc.
                    {
  OptionalScopeInfoRef maybe_scope_info = TryGetScopeInfo();
  if (!maybe_scope_info.has_value()) {
    return CheckContextExtensionsSlowPath(depth);
  }
  ScopeInfoRef scope_info = maybe_scope_info.value();
  // We only need to check up to the last-but-one depth, because an eval
  // in the same scope as the variable itself has no way of shadowing it.
  Environment* slow_environment = nullptr;
  for (uint32_t d = 0; d < depth; d++) {
    if (scope_info.HasContextExtensionSlot() &&
        !broker()->dependencies()->DependOnEmptyContextExtension(scope_info)) {
      // Using EmptyContextExtension dependency is not possible for this
      // scope_info, so generate dynamic checks.
      // The extension slot is never a context cell.
      slow_environment = CheckContextExtensionAtDepth(
          slow_environment, d, ContextMode::kNoContextCells);
    }
    DCHECK_IMPLIES(!scope_info.HasOuterScopeInfo(), d + 1 == depth);
    if (scope_info.HasOuterScopeInfo()) {
      scope_info = scope_info.OuterScopeInfo(broker());
    }
  }
  // There should have been at least one slow path generated, otherwise we
  // could have already skipped the lookup in the bytecode. The only exception
  // is if we replaced all the dynamic checks with code dependencies.
  DCHECK_IMPLIES(!v8_flags.empty_context_extension_dep,
                 slow_environment != nullptr);
  return slow_environment;
}
References broker(), DCHECK_IMPLIES, v8::internal::compiler::ScopeInfoRef::HasContextExtensionSlot(), v8::internal::compiler::ScopeInfoRef::HasOuterScopeInfo(), v8::internal::kNoContextCells, v8::internal::compiler::ScopeInfoRef::OuterScopeInfo(), and v8::internal::v8_flags.
CheckContextExtensionsSlowPath()
BytecodeGraphBuilder::Environment * v8::internal::compiler::BytecodeGraphBuilder::CheckContextExtensionsSlowPath (uint32_t depth) [private]
Definition at line 1892 of file bytecode-graph-builder.cc.
                                                                   {
  // Output environment where the context has an extension
  Environment* slow_environment = nullptr;
  // We only need to check up to the last-but-one depth, because an eval
  // in the same scope as the variable itself has no way of shadowing it.
  for (uint32_t d = 0; d < depth; d++) {
    Node* has_extension = NewNode(javascript()->HasContextExtension(d));
    Environment* undefined_extension_env;
    NewBranch(has_extension);
    {
      SubEnvironment sub_environment(this);
      NewIfTrue();
      // We don't know if the context has a context extension. If it doesn't,
      // the context extension offset might contain a context cell and even
      // though this code will not be executed it might still trigger a DCHECK
      // at later phases after context specialization which guards against using
      // LoadContextNoCell for contexts having ContextCells.
      slow_environment = CheckContextExtensionAtDepth(
          slow_environment, d, ContextMode::kHasContextCells);
      undefined_extension_env = environment();
    }
    NewIfFalse();
    environment()->Merge(undefined_extension_env,
                         bytecode_analysis().GetInLivenessFor(
                             bytecode_iterator().current_offset()));
    mark_as_needing_eager_checkpoint(true);
    // Do nothing on if there is no extension, eventually falling through to
    // the fast path.
  }
  // There should have been at least one slow path generated, otherwise we could
  // have already skipped the lookup in the bytecode.
  DCHECK_NOT_NULL(slow_environment);
  return slow_environment;
}
References DCHECK_NOT_NULL, and v8::internal::kHasContextCells.
code_kind()
CodeKind v8::internal::compiler::BytecodeGraphBuilder::code_kind () const [inline], [private]
Definition at line 84 of file bytecode-graph-builder.cc.
{ return code_kind_; }
References code_kind_.
common()
CommonOperatorBuilder* v8::internal::compiler::BytecodeGraphBuilder::common () const [inline], [private]
Definition at line 394 of file bytecode-graph-builder.cc.
{ return jsgraph_->common(); }
References v8::internal::compiler::MachineGraph::common(), and jsgraph_.
Referenced by v8::internal::compiler::BytecodeGraphBuilder::Environment::BindRegistersToProjections(), v8::internal::compiler::BytecodeGraphBuilder::Environment::Checkpoint(), v8::internal::compiler::BytecodeGraphBuilder::Environment::common(), CreateGraph(), v8::internal::compiler::BytecodeGraphBuilder::Environment::FillWithOsrValues(), GetParameter(), NewBranch(), NewIfDefault(), NewIfFalse(), NewIfTrue(), NewIfValue(), NewLoop(), NewMerge(), NewSwitch(), PrepareEagerCheckpoint(), v8::internal::compiler::BytecodeGraphBuilder::Environment::PrepareForLoop(), v8::internal::compiler::BytecodeGraphBuilder::Environment::PrepareForLoopExit(), and v8::internal::compiler::BytecodeGraphBuilder::Environment::UpdateStateValues().
ComputeCallFeedbackRelation()
CallFeedbackRelation v8::internal::compiler::BytecodeGraphBuilder::ComputeCallFeedbackRelation (int slot_id) const [private]
Definition at line 3117 of file bytecode-graph-builder.cc.
                       {
  FeedbackSlot slot = FeedbackVector::ToSlot(slot_id);
  FeedbackSource source(feedback_vector(), slot);
  ProcessedFeedback const& feedback = broker()->GetFeedbackForCall(source);
  if (feedback.IsInsufficient()) return CallFeedbackRelation::kUnrelated;
  CallFeedbackContent call_feedback_content =
      feedback.AsCall().call_feedback_content();
  return call_feedback_content == CallFeedbackContent::kTarget
             ? CallFeedbackRelation::kTarget
             : CallFeedbackRelation::kReceiver;
}
References v8::internal::compiler::ProcessedFeedback::AsCall(), broker(), v8::internal::compiler::CallFeedback::call_feedback_content(), v8::internal::compiler::ProcessedFeedback::IsInsufficient(), v8::internal::kTarget, and v8::internal::FeedbackVector::ToSlot().
ComputeCallFrequency()
CallFrequency v8::internal::compiler::BytecodeGraphBuilder::ComputeCallFrequency (int slot_id) const [private]
Definition at line 3095 of file bytecode-graph-builder.cc.
                                                                          {
  if (invocation_frequency_.IsUnknown()) return CallFrequency();
  FeedbackSlot slot = FeedbackVector::ToSlot(slot_id);
  FeedbackSource source(feedback_vector(), slot);
  ProcessedFeedback const& feedback = broker()->GetFeedbackForCall(source);
  float feedback_frequency =
      feedback.IsInsufficient() ? 0.0f : feedback.AsCall().frequency();
  if (feedback_frequency == 0.0f) { // Prevent multiplying zero and infinity.
    return CallFrequency(0.0f);
  } else {
    return CallFrequency(feedback_frequency * invocation_frequency_.value());
  }
}
References v8::internal::compiler::ProcessedFeedback::AsCall(), broker(), v8::internal::compiler::CallFeedback::frequency(), v8::internal::compiler::ProcessedFeedback::IsInsufficient(), and v8::internal::FeedbackVector::ToSlot().
CreateFeedbackSource() [1/2]
FeedbackSource v8::internal::compiler::BytecodeGraphBuilder::CreateFeedbackSource (FeedbackSlot slot) [private]
Definition at line 1158 of file bytecode-graph-builder.cc.
                                                                           {
  return FeedbackSource(feedback_vector(), slot);
}
References feedback_vector().
CreateFeedbackSource() [2/2]
FeedbackSource v8::internal::compiler::BytecodeGraphBuilder::CreateFeedbackSource (int slot_id) [private]
Definition at line 1154 of file bytecode-graph-builder.cc.
                                                                     {
  return CreateFeedbackSource(FeedbackVector::ToSlot(slot_id));
}
References v8::internal::FeedbackVector::ToSlot().
CreateFeedbackVectorNode()
void v8::internal::compiler::BytecodeGraphBuilder::CreateFeedbackVectorNode () [private]
Definition at line 1132 of file bytecode-graph-builder.cc.
                                                    {
  DCHECK_NULL(feedback_vector_node_);
  feedback_vector_node_ =
      jsgraph()->ConstantNoHole(feedback_vector(), broker());
}
References broker(), v8::internal::compiler::JSGraph::ConstantNoHole(), DCHECK_NULL, feedback_vector(), feedback_vector_node_, and jsgraph().
Referenced by CreateGraph().
CreateGraph()
void v8::internal::compiler::BytecodeGraphBuilder::CreateGraph ()
Definition at line 1162 of file bytecode-graph-builder.cc.
                                       {
  SourcePositionTable::Scope pos_scope(source_positions_, start_position_);
  if (node_origins_) {
    AddBytecodePositionDecorator();
  }
  // Set up the basic structure of the graph. Outputs for {Start} are the formal
  // parameters (including the receiver) plus new target, number of arguments,
  // context and closure.
  int start_output_arity = StartNode::OutputArityForFormalParameterCount(
      bytecode_array().parameter_count());
  graph()->SetStart(graph()->NewNode(common()->Start(start_output_arity)));
  Environment env(this, bytecode_array().register_count(),
                  bytecode_array().parameter_count(),
                  bytecode_array().incoming_new_target_or_generator_register(),
                  graph()->start());
  set_environment(&env);
  CreateFeedbackVectorNode();
  CreateNativeContextNode();
  VisitBytecodes();
  // Finish the basic structure of the graph.
  DCHECK_NE(0u, exit_controls_.size());
  int const input_count = static_cast<int>(exit_controls_.size());
  Node** const inputs = &exit_controls_.front();
  Node* end = graph()->NewNode(common()->End(input_count), input_count, inputs);
  graph()->SetEnd(end);
  if (node_origins_) {
    RemoveBytecodePositionDecorator();
  }
}
References AddBytecodePositionDecorator(), bytecode_array(), common(), CreateFeedbackVectorNode(), CreateNativeContextNode(), DCHECK_NE, v8::internal::compiler::end(), exit_controls_, v8::internal::ZoneVector< T >::front(), graph(), v8::internal::compiler::turboshaft::detail::input_count(), NewNode(), v8::internal::compiler::TFGraph::NewNode(), node_origins_, v8::internal::compiler::StartNode::OutputArityForFormalParameterCount(), RemoveBytecodePositionDecorator(), set_environment(), v8::internal::compiler::TFGraph::SetEnd(), v8::internal::compiler::TFGraph::SetStart(), v8::internal::ZoneVector< T >::size(), source_positions_, start_position_, and VisitBytecodes().
Referenced by v8::internal::compiler::BuildGraphFromBytecode().
CreateNativeContextNode()
void v8::internal::compiler::BytecodeGraphBuilder::CreateNativeContextNode () [private]
Definition at line 1143 of file bytecode-graph-builder.cc.
                                                   {
  DCHECK_NULL(native_context_node_);
  native_context_node_ = jsgraph()->ConstantNoHole(native_context(), broker());
}
References broker(), v8::internal::compiler::JSGraph::ConstantNoHole(), DCHECK_NULL, jsgraph(), native_context(), and native_context_node_.
Referenced by CreateGraph().
current_exception_handler()
int v8::internal::compiler::BytecodeGraphBuilder::current_exception_handler () const [inline], [private]
Definition at line 435 of file bytecode-graph-builder.cc.
{ return current_exception_handler_; }
References current_exception_handler_.
currently_peeled_loop_offset()
int v8::internal::compiler::BytecodeGraphBuilder::currently_peeled_loop_offset () const [inline], [private]
Definition at line 423 of file bytecode-graph-builder.cc.
                                           {
    return currently_peeled_loop_offset_;
  }
References currently_peeled_loop_offset_.
EnsureInputBufferSize()
Node ** v8::internal::compiler::BytecodeGraphBuilder::EnsureInputBufferSize (int size) [private]
Definition at line 4430 of file bytecode-graph-builder.cc.
                                                           {
  if (size > input_buffer_size_) {
    size = size + kInputBufferSizeIncrement + input_buffer_size_;
    input_buffer_ = local_zone()->AllocateArray<Node*>(size);
    input_buffer_size_ = size;
  }
  return input_buffer_;
}
References size().
environment() [1/2]
Environment* v8::internal::compiler::BytecodeGraphBuilder::environment () [inline], [private]
Definition at line 117 of file bytecode-graph-builder.cc.
{ return environment_; }
References environment_.
environment() [2/2]
const Environment* v8::internal::compiler::BytecodeGraphBuilder::environment () const [inline], [private]
Definition at line 116 of file bytecode-graph-builder.cc.
{ return environment_; }
References environment_.
Referenced by PrepareEagerCheckpoint().
ExitThenEnterExceptionHandlers()
void v8::internal::compiler::BytecodeGraphBuilder::ExitThenEnterExceptionHandlers (int current_offset) [private]
Definition at line 4439 of file bytecode-graph-builder.cc.
                                                                            {
  DisallowGarbageCollection no_gc;
  HandlerTable table(bytecode_array().handler_table_address(),
                     bytecode_array().handler_table_size(),
                     HandlerTable::kRangeBasedEncoding);
  // Potentially exit exception handlers.
  while (!exception_handlers_.empty()) {
    int current_end = exception_handlers_.top().end_offset_;
    if (current_offset < current_end) break; // Still covered by range.
    exception_handlers_.pop();
  }
  // Potentially enter exception handlers.
  int num_entries = table.NumberOfRangeEntries();
  while (current_exception_handler_ < num_entries) {
    int next_start = table.GetRangeStart(current_exception_handler_);
    if (current_offset < next_start) break; // Not yet covered by range.
    int next_end = table.GetRangeEnd(current_exception_handler_);
    int next_handler = table.GetRangeHandler(current_exception_handler_);
    int context_register = table.GetRangeData(current_exception_handler_);
    exception_handlers_.push(
        {next_start, next_end, next_handler, context_register});
    current_exception_handler_++;
  }
}
References v8::internal::HandlerTable::GetRangeData(), v8::internal::HandlerTable::GetRangeEnd(), v8::internal::HandlerTable::GetRangeHandler(), v8::internal::HandlerTable::GetRangeStart(), v8::internal::HandlerTable::kRangeBasedEncoding, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::HandlerTable::NumberOfRangeEntries().
feedback_vector()
FeedbackVectorRef v8::internal::compiler::BytecodeGraphBuilder::feedback_vector () const [inline], [private]
Definition at line 404 of file bytecode-graph-builder.cc.
{ return feedback_vector_; }
References feedback_vector_.
Referenced by BuildLoadFeedbackCell(), CreateFeedbackSource(), and CreateFeedbackVectorNode().
feedback_vector_node()
Node* v8::internal::compiler::BytecodeGraphBuilder::feedback_vector_node () const [inline], [private]
Definition at line 93 of file bytecode-graph-builder.cc.
                                     {
    DCHECK_NOT_NULL(feedback_vector_node_);
    return feedback_vector_node_;
  }
References DCHECK_NOT_NULL, and feedback_vector_node_.
frame_state_function_info()
const FrameStateFunctionInfo* v8::internal::compiler::BytecodeGraphBuilder::frame_state_function_info () const [inline], [private]
Definition at line 408 of file bytecode-graph-builder.cc.
                                                                  {
    return frame_state_function_info_;
  }
References frame_state_function_info_.
Referenced by v8::internal::compiler::BytecodeGraphBuilder::Environment::Checkpoint().
GetCallArgumentsFromRegisters()
Node *const * v8::internal::compiler::BytecodeGraphBuilder::GetCallArgumentsFromRegisters (Node * callee, Node * receiver, interpreter::Register first_arg, int arg_count) [private]
Definition at line 2498 of file bytecode-graph-builder.cc.
                   {
  const int arity = JSCallNode::ArityForArgc(arg_count);
  Node** all = local_zone()->AllocateArray<Node*>(static_cast<size_t>(arity));
  int cursor = 0;
  static_assert(JSCallNode::TargetIndex() == 0);
  static_assert(JSCallNode::ReceiverIndex() == 1);
  static_assert(JSCallNode::FirstArgumentIndex() == 2);
  static_assert(JSCallNode::kFeedbackVectorIsLastInput);
  all[cursor++] = callee;
  all[cursor++] = receiver;
  // The function arguments are in consecutive registers.
  const int arg_base = first_arg.index();
  for (int i = 0; i < arg_count; ++i) {
    all[cursor++] =
        environment()->LookupRegister(interpreter::Register(arg_base + i));
  }
  all[cursor++] = feedback_vector_node();
  DCHECK_EQ(cursor, arity);
  return all;
}
References all, DCHECK_EQ, v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::interpreter::Register::index().
GetConstructArgumentsFromRegister()
Node *const * v8::internal::compiler::BytecodeGraphBuilder::GetConstructArgumentsFromRegister (Node * target, Node * new_target, interpreter::Register first_arg, int arg_count) [private]
Definition at line 2772 of file bytecode-graph-builder.cc.
                   {
  const int arity = JSConstructNode::ArityForArgc(arg_count);
  Node** all = local_zone()->AllocateArray<Node*>(static_cast<size_t>(arity));
  int cursor = 0;
  static_assert(JSConstructNode::TargetIndex() == 0);
  static_assert(JSConstructNode::NewTargetIndex() == 1);
  static_assert(JSConstructNode::FirstArgumentIndex() == 2);
  static_assert(JSConstructNode::kFeedbackVectorIsLastInput);
  all[cursor++] = target;
  all[cursor++] = new_target;
  // The function arguments are in consecutive registers.
  int arg_base = first_arg.index();
  for (int i = 0; i < arg_count; ++i) {
    all[cursor++] =
        environment()->LookupRegister(interpreter::Register(arg_base + i));
  }
  all[cursor++] = feedback_vector_node();
  DCHECK_EQ(cursor, arity);
  return all;
}
References all, DCHECK_EQ, v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::interpreter::Register::index().
GetForInMode()
ForInMode v8::internal::compiler::BytecodeGraphBuilder::GetForInMode (FeedbackSlot slot) [private]
Definition at line 3081 of file bytecode-graph-builder.cc.
                                                              {
  FeedbackSource source(feedback_vector(), slot);
  switch (broker()->GetFeedbackForForIn(source)) {
    case ForInHint::kNone:
    case ForInHint::kEnumCacheKeysAndIndices:
      return ForInMode::kUseEnumCacheKeysAndIndices;
    case ForInHint::kEnumCacheKeys:
      return ForInMode::kUseEnumCacheKeys;
    case ForInHint::kAny:
      return ForInMode::kGeneric;
  }
  UNREACHABLE();
}
References broker(), v8::internal::kAny, v8::internal::kEnumCacheKeys, v8::internal::kEnumCacheKeysAndIndices, v8::internal::kNone, and v8::internal::UNREACHABLE().
GetFunctionClosure()
Node * v8::internal::compiler::BytecodeGraphBuilder::GetFunctionClosure () [private]
Definition at line 1103 of file bytecode-graph-builder.cc.
                                               {
  if (!function_closure_.is_set()) {
    int index = Linkage::kJSCallClosureParamIndex;
    Node* node = GetParameter(index, "%closure");
    function_closure_.set(node);
  }
  return function_closure_.get();
}
References function_closure_, GetParameter(), v8::internal::index, and v8::internal::compiler::Linkage::kJSCallClosureParamIndex.
Referenced by v8::internal::compiler::BytecodeGraphBuilder::Environment::Checkpoint().
GetParameter()
Node * v8::internal::compiler::BytecodeGraphBuilder::GetParameter (int index, const char * debug_name_hint = nullptr) [private]
Definition at line 1112 of file bytecode-graph-builder.cc.
                                                                      {
  // We use negative indices for some parameters.
  DCHECK_LE(ParameterInfo::kMinIndex, parameter_index);
  const size_t index =
      static_cast<size_t>(parameter_index - ParameterInfo::kMinIndex);
  if (cached_parameters_.size() <= index) {
    cached_parameters_.resize(index + 1, nullptr);
  }
  if (cached_parameters_[index] == nullptr) {
    cached_parameters_[index] =
        NewNode(common()->Parameter(parameter_index, debug_name_hint),
                graph()->start());
  }
  return cached_parameters_[index];
}
References cached_parameters_, common(), DCHECK_LE, graph(), v8::internal::index, v8::internal::compiler::ParameterInfo::kMinIndex, NewNode(), v8::internal::ZoneVector< T >::resize(), and v8::internal::ZoneVector< T >::size().
Referenced by v8::internal::compiler::BytecodeGraphBuilder::Environment::Environment(), and GetFunctionClosure().
GetSpeculationMode()
SpeculationMode v8::internal::compiler::BytecodeGraphBuilder::GetSpeculationMode (int slot_id) const [private]
Definition at line 3109 of file bytecode-graph-builder.cc.
                                                                          {
  FeedbackSlot slot = FeedbackVector::ToSlot(slot_id);
  FeedbackSource source(feedback_vector(), slot);
  ProcessedFeedback const& feedback = broker()->GetFeedbackForCall(source);
  return feedback.IsInsufficient() ? SpeculationMode::kDisallowSpeculation
                                   : feedback.AsCall().speculation_mode();
}
References v8::internal::compiler::ProcessedFeedback::AsCall(), broker(), v8::internal::compiler::ProcessedFeedback::IsInsufficient(), v8::internal::kDisallowSpeculation, v8::internal::compiler::CallFeedback::speculation_mode(), and v8::internal::FeedbackVector::ToSlot().
graph()
TFGraph* v8::internal::compiler::BytecodeGraphBuilder::graph () const [inline], [private]
Definition at line 393 of file bytecode-graph-builder.cc.
{ return jsgraph_->graph(); }
References v8::internal::compiler::MachineGraph::graph(), and jsgraph_.
Referenced by v8::internal::compiler::BytecodeGraphBuilder::Environment::Checkpoint(), CreateGraph(), v8::internal::compiler::BytecodeGraphBuilder::Environment::FillWithOsrValues(), GetParameter(), v8::internal::compiler::BytecodeGraphBuilder::Environment::graph(), graph_zone(), v8::internal::compiler::BytecodeGraphBuilder::Environment::PrepareForLoopExit(), and v8::internal::compiler::BytecodeGraphBuilder::Environment::UpdateStateValues().
graph_zone()
Zone* v8::internal::compiler::BytecodeGraphBuilder::graph_zone () const [inline], [private]
Definition at line 395 of file bytecode-graph-builder.cc.
{ return graph()->zone(); }
References graph(), and v8::internal::compiler::TFGraph::zone().
isolate()
Isolate* v8::internal::compiler::BytecodeGraphBuilder::isolate () const [inline], [private]
Definition at line 397 of file bytecode-graph-builder.cc.
{ return jsgraph_->isolate(); }
References v8::internal::compiler::JSGraph::isolate(), and jsgraph_.
javascript()
JSOperatorBuilder* v8::internal::compiler::BytecodeGraphBuilder::javascript () const [inline], [private]
Definition at line 398 of file bytecode-graph-builder.cc.
{ return jsgraph_->javascript(); }
References v8::internal::compiler::JSGraph::javascript(), and jsgraph_.
Referenced by BuildLoadNativeContextField().
jsgraph()
JSGraph* v8::internal::compiler::BytecodeGraphBuilder::jsgraph () const [inline], [private]
Definition at line 396 of file bytecode-graph-builder.cc.
{ return jsgraph_; }
References jsgraph_.
Referenced by BuildLoadFeedbackCell(), CreateFeedbackVectorNode(), CreateNativeContextNode(), v8::internal::compiler::BytecodeGraphBuilder::Environment::Environment(), and v8::internal::compiler::BytecodeGraphBuilder::Environment::Merge().
local_zone()
Zone* v8::internal::compiler::BytecodeGraphBuilder::local_zone () const [inline], [private]
Definition at line 402 of file bytecode-graph-builder.cc.
{ return local_zone_; }
References local_zone_.
Referenced by v8::internal::compiler::BytecodeGraphBuilder::Environment::zone().
MakeNode()
Node * v8::internal::compiler::BytecodeGraphBuilder::MakeNode (const Operator * op, int value_input_count, Node *const * value_inputs, bool incomplete = false) [private]
Definition at line 4466 of file bytecode-graph-builder.cc.
                                                      {
  DCHECK_EQ(op->ValueInputCount(), value_input_count);
  // Parameter nodes must be created through GetParameter.
  DCHECK_IMPLIES(
      op->opcode() == IrOpcode::kParameter,
      (nullptr == cached_parameters_[static_cast<std::size_t>(
                      ParameterIndexOf(op) - ParameterInfo::kMinIndex)]));
  bool has_context = OperatorProperties::HasContextInput(op);
  bool has_frame_state = OperatorProperties::HasFrameStateInput(op);
  bool has_control = op->ControlInputCount() == 1;
  bool has_effect = op->EffectInputCount() == 1;
  DCHECK_LT(op->ControlInputCount(), 2);
  DCHECK_LT(op->EffectInputCount(), 2);
  Node* result = nullptr;
  if (!has_context && !has_frame_state && !has_control && !has_effect) {
    result = graph()->NewNode(op, value_input_count, value_inputs, incomplete);
  } else {
    bool inside_handler = !exception_handlers_.empty();
    int input_count_with_deps = value_input_count;
    if (has_context) ++input_count_with_deps;
    if (has_frame_state) ++input_count_with_deps;
    if (has_control) ++input_count_with_deps;
    if (has_effect) ++input_count_with_deps;
    Node** buffer = EnsureInputBufferSize(input_count_with_deps);
    if (value_input_count > 0) {
      memcpy(buffer, value_inputs, kSystemPointerSize * value_input_count);
    }
    Node** current_input = buffer + value_input_count;
    if (has_context) {
      *current_input++ = OperatorProperties::NeedsExactContext(op)
                             ? environment()->Context()
                             : native_context_node();
    }
    if (has_frame_state) {
      // The frame state will be inserted later. Here we misuse the {Dead} node
      // as a sentinel to be later overwritten with the real frame state by the
      // calls to {PrepareFrameState} within individual visitor methods.
      *current_input++ = jsgraph()->Dead();
    }
    if (has_effect) {
      *current_input++ = environment()->GetEffectDependency();
    }
    if (has_control) {
      *current_input++ = environment()->GetControlDependency();
    }
    result = graph()->NewNode(op, input_count_with_deps, buffer, incomplete);
    // Update the current control dependency for control-producing nodes.
    if (result->op()->ControlOutputCount() > 0) {
      environment()->UpdateControlDependency(result);
    }
    // Update the current effect dependency for effect-producing nodes.
    if (result->op()->EffectOutputCount() > 0) {
      environment()->UpdateEffectDependency(result);
    }
    // Add implicit exception continuation for throwing nodes.
    if (!result->op()->HasProperty(Operator::kNoThrow) && inside_handler) {
      int handler_offset = exception_handlers_.top().handler_offset_;
      int context_index = exception_handlers_.top().context_register_;
      interpreter::Register context_register(context_index);
      Environment* success_env = environment()->Copy();
      const Operator* if_exception = common()->IfException();
      Node* effect = environment()->GetEffectDependency();
      Node* on_exception = graph()->NewNode(if_exception, effect, result);
      Node* context = environment()->LookupRegister(context_register);
      environment()->UpdateControlDependency(on_exception);
      environment()->UpdateEffectDependency(on_exception);
      environment()->BindAccumulator(on_exception);
      environment()->SetContext(context);
      MergeIntoSuccessorEnvironment(handler_offset);
      set_environment(success_env);
    }
    // Add implicit success continuation for throwing nodes.
    if (!result->op()->HasProperty(Operator::kNoThrow) && inside_handler) {
      const Operator* if_success = common()->IfSuccess();
      Node* on_success = graph()->NewNode(if_success, result);
      environment()->UpdateControlDependency(on_success);
    }
    // Ensure checkpoints are created after operations with side-effects.
    if (has_effect && !result->op()->HasProperty(Operator::kNoWrite)) {
      mark_as_needing_eager_checkpoint(true);
    }
  }
  return result;
}
References v8::internal::compiler::Operator::ControlInputCount(), v8::internal::compiler::BytecodeGraphBuilder::Environment::Copy(), DCHECK_EQ, DCHECK_IMPLIES, DCHECK_LT, v8::internal::compiler::Operator::EffectInputCount(), graph(), v8::internal::kSystemPointerSize, v8::internal::compiler::Operator::opcode(), v8::internal::compiler::ParameterIndexOf(), v8::base::internal::result, v8::internal::size_t, and v8::internal::compiler::Operator::ValueInputCount().
Referenced by NewNode().
MakeRefForConstantForIndexOperand()
template<class T = Object>
ref_traits<T>::ref_type v8::internal::compiler::BytecodeGraphBuilder::MakeRefForConstantForIndexOperand (int operand_index) [inline], [private]
Definition at line 383 of file bytecode-graph-builder.cc.
                         {
    // The BytecodeArray itself was fetched by using a barrier so all reads
    // from the constant pool are safe.
    return MakeRefAssumeMemoryFence(
        broker(), broker()->CanonicalPersistentHandle(
                      Cast<T>(bytecode_iterator().GetConstantForIndexOperand(
                          operand_index, local_isolate_))));
  }
References broker(), bytecode_iterator(), local_isolate_, and v8::internal::compiler::MakeRefAssumeMemoryFence().
mark_as_needing_eager_checkpoint()
void v8::internal::compiler::BytecodeGraphBuilder::mark_as_needing_eager_checkpoint (bool value) [inline], [private]
Definition at line 440 of file bytecode-graph-builder.cc.
                                                    {
    needs_eager_checkpoint_ = value;
  }
References needs_eager_checkpoint_, and v8::internal::value.
Referenced by PrepareEagerCheckpoint().
MergeControl()
Node * v8::internal::compiler::BytecodeGraphBuilder::MergeControl (Node * control, Node * other) [private]
Definition at line 4576 of file bytecode-graph-builder.cc.
                                                                   {
  int inputs = control->op()->ControlInputCount() + 1;
  if (control->opcode() == IrOpcode::kLoop) {
    // Control node for loop exists, add input.
    const Operator* op = common()->Loop(inputs);
    control->AppendInput(graph_zone(), other);
    NodeProperties::ChangeOp(control, op);
  } else if (control->opcode() == IrOpcode::kMerge) {
    // Control node for merge exists, add input.
    const Operator* op = common()->Merge(inputs);
    control->AppendInput(graph_zone(), other);
    NodeProperties::ChangeOp(control, op);
  } else {
    // Control node is a singleton, introduce a merge.
    const Operator* op = common()->Merge(inputs);
    Node* merge_inputs[] = {control, other};
    control = graph()->NewNode(op, arraysize(merge_inputs), merge_inputs, true);
  }
  return control;
}
References v8::internal::compiler::Node::AppendInput(), arraysize, v8::internal::compiler::Operator::ControlInputCount(), graph(), v8::internal::compiler::Node::op(), and v8::internal::compiler::Node::opcode().
MergeControlToLeaveFunction()
void v8::internal::compiler::BytecodeGraphBuilder::MergeControlToLeaveFunction (Node * exit) [private]
Definition at line 4133 of file bytecode-graph-builder.cc.
                                                                 {
  exit_controls_.push_back(exit);
  set_environment(nullptr);
}
MergeEffect()
Node * v8::internal::compiler::BytecodeGraphBuilder::MergeEffect (Node * effect, Node * other_effect, Node * control) [private]
Definition at line 4597 of file bytecode-graph-builder.cc.
                                                       {
  int inputs = control->op()->ControlInputCount();
  if (value->opcode() == IrOpcode::kEffectPhi &&
      NodeProperties::GetControlInput(value) == control) {
    // Phi already exists, add input.
    value->InsertInput(graph_zone(), inputs - 1, other);
    NodeProperties::ChangeOp(value, common()->EffectPhi(inputs));
  } else if (value != other) {
    // Phi does not exist yet, introduce one.
    value = NewEffectPhi(inputs, value, control);
    value->ReplaceInput(inputs - 1, other);
  }
  return value;
}
References v8::internal::compiler::Operator::ControlInputCount(), v8::internal::compiler::Node::op(), and v8::internal::value.
MergeIntoSuccessorEnvironment()
void v8::internal::compiler::BytecodeGraphBuilder::MergeIntoSuccessorEnvironment (int target_offset) [private]
Definition at line 4115 of file bytecode-graph-builder.cc.
                                                                          {
  BuildLoopExitsForBranch(target_offset);
  Environment*& merge_environment = merge_environments_[target_offset];
  if (merge_environment == nullptr) {
    // Append merge nodes to the environment. We may merge here with another
    // environment. So add a place holder for merge nodes. We may add redundant
    // but will be eliminated in a later pass.
    NewMerge();
    merge_environment = environment();
  } else {
    // Merge any values which are live coming into the successor.
    merge_environment->Merge(
        environment(), bytecode_analysis().GetInLivenessFor(target_offset));
  }
  set_environment(nullptr);
}
References v8::internal::compiler::BytecodeGraphBuilder::Environment::Merge().
MergeValue()
Node * v8::internal::compiler::BytecodeGraphBuilder::MergeValue (Node * value, Node * other_value, Node * control) [private]
Definition at line 4613 of file bytecode-graph-builder.cc.
                                                      {
  int inputs = control->op()->ControlInputCount();
  if (value->opcode() == IrOpcode::kPhi &&
      NodeProperties::GetControlInput(value) == control) {
    // Phi already exists, add input.
    value->InsertInput(graph_zone(), inputs - 1, other);
    NodeProperties::ChangeOp(
        value, common()->Phi(MachineRepresentation::kTagged, inputs));
  } else if (value != other) {
    // Phi does not exist yet, introduce one.
    value = NewPhi(inputs, value, control);
    value->ReplaceInput(inputs - 1, other);
  }
  return value;
}
References v8::internal::compiler::Operator::ControlInputCount(), v8::internal::kTagged, v8::internal::compiler::Node::op(), and v8::internal::value.
native_context()
NativeContextRef v8::internal::compiler::BytecodeGraphBuilder::native_context () const [inline], [private]
Definition at line 444 of file bytecode-graph-builder.cc.
{ return native_context_; }
References native_context_.
Referenced by CreateNativeContextNode().
native_context_node()
Node* v8::internal::compiler::BytecodeGraphBuilder::native_context_node () const [inline], [private]
Definition at line 100 of file bytecode-graph-builder.cc.
                                    {
    DCHECK_NOT_NULL(native_context_node_);
    return native_context_node_;
  }
References DCHECK_NOT_NULL, and native_context_node_.
Referenced by BuildLoadNativeContextField().
needs_eager_checkpoint()
bool v8::internal::compiler::BytecodeGraphBuilder::needs_eager_checkpoint () const [inline], [private]
Definition at line 439 of file bytecode-graph-builder.cc.
{ return needs_eager_checkpoint_; }
References needs_eager_checkpoint_.
Referenced by PrepareEagerCheckpoint().
NewBranch()
Node* v8::internal::compiler::BytecodeGraphBuilder::NewBranch (Node * condition, BranchHint hint = BranchHint::kNone) [inline], [private]
Definition at line 137 of file bytecode-graph-builder.cc.
                                                                      {
    return NewNode(common()->Branch(hint), condition);
  }
References common(), and NewNode().
NewEffectPhi()
Node * v8::internal::compiler::BytecodeGraphBuilder::NewEffectPhi (int count, Node * input, Node * control) [private]
Definition at line 4566 of file bytecode-graph-builder.cc.
                                                        {
  const Operator* phi_op = common()->EffectPhi(count);
  Node** buffer = EnsureInputBufferSize(count + 1);
  MemsetPointer(buffer, input, count);
  buffer[count] = control;
  return graph()->NewNode(phi_op, count + 1, buffer, true);
}
References graph(), and v8::internal::MemsetPointer().
NewIfDefault()
Node* v8::internal::compiler::BytecodeGraphBuilder::NewIfDefault () [inline], [private]
Definition at line 134 of file bytecode-graph-builder.cc.
{ return NewNode(common()->IfDefault()); }
References common(), and NewNode().
NewIfFalse()
Node* v8::internal::compiler::BytecodeGraphBuilder::NewIfFalse () [inline], [private]
Definition at line 132 of file bytecode-graph-builder.cc.
{ return NewNode(common()->IfFalse()); }
References common(), and NewNode().
NewIfTrue()
Node* v8::internal::compiler::BytecodeGraphBuilder::NewIfTrue () [inline], [private]
Definition at line 131 of file bytecode-graph-builder.cc.
{ return NewNode(common()->IfTrue()); }
References common(), and NewNode().
NewIfValue()
Node* v8::internal::compiler::BytecodeGraphBuilder::NewIfValue (int32_t value) [inline], [private]
Definition at line 133 of file bytecode-graph-builder.cc.
{ return NewNode(common()->IfValue(value)); }
References common(), NewNode(), and v8::internal::value.
NewLoop()
Node* v8::internal::compiler::BytecodeGraphBuilder::NewLoop () [inline], [private]
Definition at line 136 of file bytecode-graph-builder.cc.
{ return NewNode(common()->Loop(1), true); }
References common(), and NewNode().
NewMerge()
Node* v8::internal::compiler::BytecodeGraphBuilder::NewMerge () [inline], [private]
Definition at line 135 of file bytecode-graph-builder.cc.
{ return NewNode(common()->Merge(1), true); }
References common(), and NewNode().
NewNode() [1/2]
Node* v8::internal::compiler::BytecodeGraphBuilder::NewNode (const Operator * op, bool incomplete = false) [inline], [private]
Definition at line 120 of file bytecode-graph-builder.cc.
                                                             {
    return MakeNode(op, 0, static_cast<Node**>(nullptr), incomplete);
  }
References MakeNode().
Referenced by BuildLoadNativeContextField(), CreateGraph(), v8::internal::compiler::BytecodeGraphBuilder::Environment::FillWithOsrValues(), GetParameter(), NewBranch(), NewIfDefault(), NewIfFalse(), NewIfTrue(), NewIfValue(), NewLoop(), NewMerge(), NewSwitch(), and PrepareEagerCheckpoint().
NewNode() [2/2]
template<class... Args>
Node* v8::internal::compiler::BytecodeGraphBuilder::NewNode (const Operator * op, Node * n0, Args... nodes) [inline], [private]
Definition at line 125 of file bytecode-graph-builder.cc.
                                                             {
    Node* buffer[] = {n0, nodes...};
    return MakeNode(op, arraysize(buffer), buffer);
  }
References arraysize, and MakeNode().
NewPhi()
Node * v8::internal::compiler::BytecodeGraphBuilder::NewPhi (int count, Node * input, Node * control) [private]
Definition at line 4558 of file bytecode-graph-builder.cc.
                                                                        {
  const Operator* phi_op = common()->Phi(MachineRepresentation::kTagged, count);
  Node** buffer = EnsureInputBufferSize(count + 1);
  MemsetPointer(buffer, input, count);
  buffer[count] = control;
  return graph()->NewNode(phi_op, count + 1, buffer, true);
}
References graph(), v8::internal::kTagged, and v8::internal::MemsetPointer().
NewSwitch()
Node* v8::internal::compiler::BytecodeGraphBuilder::NewSwitch (Node * condition, int control_output_count) [inline], [private]
Definition at line 140 of file bytecode-graph-builder.cc.
                                                             {
    return NewNode(common()->Switch(control_output_count), condition);
  }
References common(), and NewNode().
operator=()
BytecodeGraphBuilder& v8::internal::compiler::BytecodeGraphBuilder::operator= (const BytecodeGraphBuilder &) [delete]
PrepareEagerCheckpoint()
void v8::internal::compiler::BytecodeGraphBuilder::PrepareEagerCheckpoint () [private]
Definition at line 1196 of file bytecode-graph-builder.cc.
                                                  {
  if (needs_eager_checkpoint()) {
    // Create an explicit checkpoint node for before the operation. This only
    // needs to happen if we aren't effect-dominated by a {Checkpoint} already.
    mark_as_needing_eager_checkpoint(false);
    Node* node = NewNode(common()->Checkpoint());
    DCHECK_EQ(1, OperatorProperties::GetFrameStateInputCount(node->op()));
    DCHECK_EQ(IrOpcode::kDead,
              NodeProperties::GetFrameStateInput(node)->opcode());
    BytecodeOffset bailout_id(bytecode_iterator().current_offset());
    const BytecodeLivenessState* liveness_before =
        bytecode_analysis().GetInLivenessFor(
            bytecode_iterator().current_offset());
    Node* frame_state_before = environment()->Checkpoint(
        bailout_id, OutputFrameStateCombine::Ignore(), liveness_before);
    NodeProperties::ReplaceFrameStateInput(node, frame_state_before);
#ifdef DEBUG
  } else {
    // In case we skipped checkpoint creation above, we must be able to find an
    // existing checkpoint that effect-dominates the nodes about to be created.
    // Starting a search from the current effect-dependency has to succeed.
    Node* effect = environment()->GetEffectDependency();
    while (effect->opcode() != IrOpcode::kCheckpoint) {
      DCHECK(effect->op()->HasProperty(Operator::kNoWrite));
      DCHECK_EQ(1, effect->op()->EffectInputCount());
      effect = NodeProperties::GetEffectInput(effect);
    }
  }
#else
  }
#endif // DEBUG
}
References bytecode_analysis(), bytecode_iterator(), v8::internal::compiler::BytecodeGraphBuilder::Environment::Checkpoint(), common(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::Operator::EffectInputCount(), environment(), v8::internal::compiler::BytecodeGraphBuilder::Environment::GetEffectDependency(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetFrameStateInput(), v8::internal::compiler::OperatorProperties::GetFrameStateInputCount(), v8::internal::compiler::BytecodeAnalysis::GetInLivenessFor(), v8::internal::compiler::Operator::HasProperty(), v8::internal::compiler::OutputFrameStateCombine::Ignore(), v8::internal::compiler::Operator::kNoWrite, mark_as_needing_eager_checkpoint(), needs_eager_checkpoint(), NewNode(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), and v8::internal::compiler::NodeProperties::ReplaceFrameStateInput().
PrepareFrameState() [1/2]
void v8::internal::compiler::BytecodeGraphBuilder::PrepareFrameState (Node * node, OutputFrameStateCombine combine) [inline], [private]
Definition at line 188 of file bytecode-graph-builder.cc.
                                                                      {
    if (!OperatorProperties::HasFrameStateInput(node->op())) return;
    const int offset = bytecode_iterator().current_offset();
    return PrepareFrameState(node, combine, BytecodeOffset(offset),
                             bytecode_analysis().GetOutLivenessFor(offset));
  }
References bytecode_analysis(), bytecode_iterator(), v8::internal::interpreter::BytecodeArrayIterator::current_offset(), v8::internal::compiler::OperatorProperties::HasFrameStateInput(), v8::internal::compiler::Node::op(), and PrepareFrameState().
PrepareFrameState() [2/2]
void v8::internal::compiler::BytecodeGraphBuilder::PrepareFrameState (Node * node, OutputFrameStateCombine combine, BytecodeOffset bailout_id, const BytecodeLivenessState * liveness) [private]
Definition at line 1231 of file bytecode-graph-builder.cc.
                                           {
  if (OperatorProperties::HasFrameStateInput(node->op())) {
    // Add the frame state for after the operation. The node in question has
    // already been created and had a {Dead} frame state input up until now.
    DCHECK_EQ(1, OperatorProperties::GetFrameStateInputCount(node->op()));
    DCHECK_EQ(IrOpcode::kDead,
              NodeProperties::GetFrameStateInput(node)->opcode());
    Node* frame_state_after =
        environment()->Checkpoint(bailout_id, combine, liveness);
    NodeProperties::ReplaceFrameStateInput(node, frame_state_after);
  }
}
References DCHECK_EQ, and v8::internal::compiler::Node::op().
Referenced by PrepareFrameState(), PrepareFrameStateForFunctionEntryStackCheck(), and PrepareFrameStateForOSREntryStackCheck().
PrepareFrameStateForFunctionEntryStackCheck()
void v8::internal::compiler::BytecodeGraphBuilder::PrepareFrameStateForFunctionEntryStackCheck (Node * node) [inline], [private]
Definition at line 200 of file bytecode-graph-builder.cc.
                                                               {
    DCHECK_EQ(bytecode_iterator().current_offset(), 0);
    DCHECK(OperatorProperties::HasFrameStateInput(node->op()));
    DCHECK(node->opcode() == IrOpcode::kJSStackCheck);
    return PrepareFrameState(node, OutputFrameStateCombine::Ignore(),
                             BytecodeOffset(kFunctionEntryBytecodeOffset),
                             bytecode_analysis().GetInLivenessFor(0));
  }
References bytecode_analysis(), bytecode_iterator(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::OperatorProperties::HasFrameStateInput(), v8::internal::compiler::OutputFrameStateCombine::Ignore(), v8::internal::kFunctionEntryBytecodeOffset, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), and PrepareFrameState().
PrepareFrameStateForOSREntryStackCheck()
void v8::internal::compiler::BytecodeGraphBuilder::PrepareFrameStateForOSREntryStackCheck (Node * node) [inline], [private]
Definition at line 218 of file bytecode-graph-builder.cc.
                                                          {
    DCHECK(OperatorProperties::HasFrameStateInput(node->op()));
    DCHECK(node->opcode() == IrOpcode::kJSStackCheck);
    const int offset = bytecode_analysis().osr_bailout_id().ToInt();
    return PrepareFrameState(node, OutputFrameStateCombine::Ignore(),
                             BytecodeOffset(offset),
                             bytecode_analysis().GetOutLivenessFor(offset));
  }
References bytecode_analysis(), v8::internal::DCHECK(), v8::internal::compiler::OperatorProperties::HasFrameStateInput(), v8::internal::compiler::OutputFrameStateCombine::Ignore(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::BytecodeAnalysis::osr_bailout_id(), PrepareFrameState(), and v8::internal::BytecodeOffset::ToInt().
ProcessCallRuntimeArguments()
Node * v8::internal::compiler::BytecodeGraphBuilder::ProcessCallRuntimeArguments (const Operator * call_runtime_op, interpreter::Register receiver, size_t reg_count) [private]
Definition at line 2713 of file bytecode-graph-builder.cc.
                      {
  int arg_count = static_cast<int>(reg_count);
  // arity is args.
  int arity = arg_count;
  Node** all = local_zone()->AllocateArray<Node*>(static_cast<size_t>(arity));
  int first_arg_index = receiver.index();
  for (int i = 0; i < static_cast<int>(reg_count); ++i) {
    all[i] = environment()->LookupRegister(
        interpreter::Register(first_arg_index + i));
  }
  Node* value = MakeNode(call_runtime_op, arity, all);
  return value;
}
References all, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::interpreter::Register::index(), v8::internal::torque::MakeNode(), and v8::internal::value.
ProcessCallVarArgs()
Node *const * v8::internal::compiler::BytecodeGraphBuilder::ProcessCallVarArgs (ConvertReceiverMode receiver_mode, Node * callee, interpreter::Register first_reg, int arg_count) [private]
Definition at line 2548 of file bytecode-graph-builder.cc.
                                                  {
  DCHECK_GE(arg_count, 0);
  Node* receiver_node;
  interpreter::Register first_arg;
  if (receiver_mode == ConvertReceiverMode::kNullOrUndefined) {
    // The receiver is implicit (and undefined), the arguments are in
    // consecutive registers.
    receiver_node = jsgraph()->UndefinedConstant();
    first_arg = first_reg;
  } else {
    // The receiver is the first register, followed by the arguments in the
    // consecutive registers.
    receiver_node = environment()->LookupRegister(first_reg);
    first_arg = interpreter::Register(first_reg.index() + 1);
  }
  Node* const* call_args = GetCallArgumentsFromRegisters(callee, receiver_node,
                                                         first_arg, arg_count);
  return call_args;
}
References DCHECK_GE, v8::internal::interpreter::Register::index(), v8::internal::kNullOrUndefined, and v8::internal::ETWJITInterface::Register().
RemoveBytecodePositionDecorator()
void v8::internal::compiler::BytecodeGraphBuilder::RemoveBytecodePositionDecorator () [private]
Definition at line 1515 of file bytecode-graph-builder.cc.
                                                           {
  DCHECK_NOT_NULL(decorator_);
  graph()->RemoveDecorator(decorator_);
  decorator_ = nullptr;
}
References DCHECK_NOT_NULL, and graph().
Referenced by CreateGraph().
RemoveMergeEnvironmentsBeforeOffset()
void v8::internal::compiler::BytecodeGraphBuilder::RemoveMergeEnvironmentsBeforeOffset (int limit_offset) [private]
Definition at line 1338 of file bytecode-graph-builder.cc.
                      {
  if (!merge_environments_.empty()) {
    ZoneMap<int, Environment*>::iterator it = merge_environments_.begin();
    ZoneMap<int, Environment*>::iterator stop_it = merge_environments_.end();
    while (it != stop_it && it->first <= limit_offset) {
      it = merge_environments_.erase(it);
    }
  }
}
set_current_exception_handler()
void v8::internal::compiler::BytecodeGraphBuilder::set_current_exception_handler (int index) [inline], [private]
Definition at line 436 of file bytecode-graph-builder.cc.
                                                {
    current_exception_handler_ = index;
  }
References current_exception_handler_, and v8::internal::index.
set_currently_peeled_loop_offset()
void v8::internal::compiler::BytecodeGraphBuilder::set_currently_peeled_loop_offset (int offset) [inline], [private]
Definition at line 426 of file bytecode-graph-builder.cc.
                                                    {
    currently_peeled_loop_offset_ = offset;
  }
References currently_peeled_loop_offset_.
set_environment()
void v8::internal::compiler::BytecodeGraphBuilder::set_environment (Environment * env) [inline], [private]
Definition at line 115 of file bytecode-graph-builder.cc.
{ environment_ = env; }
References environment_.
Referenced by CreateGraph(), and v8::internal::compiler::BytecodeGraphBuilder::SubEnvironment::~SubEnvironment().
shared_info()
SharedFunctionInfoRef v8::internal::compiler::BytecodeGraphBuilder::shared_info () const [inline], [private]
Definition at line 445 of file bytecode-graph-builder.cc.
{ return shared_info_; }
References shared_info_.
simplified()
SimplifiedOperatorBuilder* v8::internal::compiler::BytecodeGraphBuilder::simplified () const [inline], [private]
Definition at line 399 of file bytecode-graph-builder.cc.
                                                {
    return jsgraph_->simplified();
  }
References jsgraph_, and v8::internal::compiler::JSGraph::simplified().
skip_first_stack_check()
bool v8::internal::compiler::BytecodeGraphBuilder::skip_first_stack_check () const [inline], [private]
Definition at line 429 of file bytecode-graph-builder.cc.
                                      {
    return skip_first_stack_and_tierup_check_;
  }
References skip_first_stack_and_tierup_check_.
skip_tierup_check()
bool v8::internal::compiler::BytecodeGraphBuilder::skip_tierup_check () const [inline], [private]
Definition at line 432 of file bytecode-graph-builder.cc.
                                 {
    return skip_first_stack_and_tierup_check_ || osr_;
  }
References osr_, and skip_first_stack_and_tierup_check_.
source_position_iterator()
SourcePositionTableIterator& v8::internal::compiler::BytecodeGraphBuilder::source_position_iterator () [inline], [private]
Definition at line 411 of file bytecode-graph-builder.cc.
                                                          {
    return source_position_iterator_;
  }
References source_position_iterator_.
SwitchToMergeEnvironment()
void v8::internal::compiler::BytecodeGraphBuilder::SwitchToMergeEnvironment (int current_offset) [private]
Definition at line 4069 of file bytecode-graph-builder.cc.
                                                                      {
  auto it = merge_environments_.find(current_offset);
  if (it != merge_environments_.end()) {
    mark_as_needing_eager_checkpoint(true);
    if (environment() != nullptr) {
      it->second->Merge(environment(),
                        bytecode_analysis().GetInLivenessFor(current_offset));
    }
    set_environment(it->second);
  }
}
TryBuildSimplifiedBinaryOp()
JSTypeHintLowering::LoweringResult v8::internal::compiler::BytecodeGraphBuilder::TryBuildSimplifiedBinaryOp (const Operator * op, Node * left, Node * right, FeedbackSlot slot) [private]
Definition at line 4286 of file bytecode-graph-builder.cc.
                                                                    {
  Node* effect = environment()->GetEffectDependency();
  Node* control = environment()->GetControlDependency();
  JSTypeHintLowering::LoweringResult result =
      type_hint_lowering().ReduceBinaryOperation(op, left, right, effect,
                                                 control, slot);
  ApplyEarlyReduction(result);
  return result;
}
References v8::base::internal::result.
TryBuildSimplifiedConstruct()
JSTypeHintLowering::LoweringResult v8::internal::compiler::BytecodeGraphBuilder::TryBuildSimplifiedConstruct (const Operator * op, Node *const * args, int arg_count, FeedbackSlot slot) [private]
Definition at line 4337 of file bytecode-graph-builder.cc.
                                                                     {
  Node* effect = environment()->GetEffectDependency();
  Node* control = environment()->GetControlDependency();
  JSTypeHintLowering::LoweringResult result =
      type_hint_lowering().ReduceConstructOperation(op, args, arg_count, effect,
                                                    control, slot);
  ApplyEarlyReduction(result);
  return result;
}
References v8::base::args, and v8::base::internal::result.
TryBuildSimplifiedForInNext()
JSTypeHintLowering::LoweringResult v8::internal::compiler::BytecodeGraphBuilder::TryBuildSimplifiedForInNext (Node * receiver, Node * cache_array, Node * cache_type, Node * index, FeedbackSlot slot) [private]
Definition at line 4299 of file bytecode-graph-builder.cc.
                                                                     {
  Node* effect = environment()->GetEffectDependency();
  Node* control = environment()->GetControlDependency();
  JSTypeHintLowering::LoweringResult result =
      type_hint_lowering().ReduceForInNextOperation(
          receiver, cache_array, cache_type, index, effect, control, slot);
  ApplyEarlyReduction(result);
  return result;
}
References v8::internal::index, and v8::base::internal::result.
TryBuildSimplifiedForInPrepare()
JSTypeHintLowering::LoweringResult v8::internal::compiler::BytecodeGraphBuilder::TryBuildSimplifiedForInPrepare (Node * receiver, FeedbackSlot slot) [private]
Definition at line 4313 of file bytecode-graph-builder.cc.
                                                                        {
  Node* effect = environment()->GetEffectDependency();
  Node* control = environment()->GetControlDependency();
  JSTypeHintLowering::LoweringResult result =
      type_hint_lowering().ReduceForInPrepareOperation(enumerator, effect,
                                                       control, slot);
  ApplyEarlyReduction(result);
  return result;
}
References v8::base::internal::result.
TryBuildSimplifiedGetIterator()
JSTypeHintLowering::LoweringResult v8::internal::compiler::BytecodeGraphBuilder::TryBuildSimplifiedGetIterator (const Operator * op, Node * receiver, FeedbackSlot load_slot, FeedbackSlot call_slot) [private]
Definition at line 4351 of file bytecode-graph-builder.cc.
                                                                            {
  Node* effect = environment()->GetEffectDependency();
  Node* control = environment()->GetControlDependency();
  JSTypeHintLowering::LoweringResult early_reduction =
      type_hint_lowering().ReduceGetIteratorOperation(
          op, receiver, effect, control, load_slot, call_slot);
  ApplyEarlyReduction(early_reduction);
  return early_reduction;
}
TryBuildSimplifiedLoadKeyed()
JSTypeHintLowering::LoweringResult v8::internal::compiler::BytecodeGraphBuilder::TryBuildSimplifiedLoadKeyed (const Operator * op, Node * receiver, Node * key, FeedbackSlot slot) [private]
Definition at line 4376 of file bytecode-graph-builder.cc.
                                                                     {
  Node* effect = environment()->GetEffectDependency();
  Node* control = environment()->GetControlDependency();
  JSTypeHintLowering::LoweringResult result =
      type_hint_lowering().ReduceLoadKeyedOperation(op, receiver, key, effect,
                                                    control, slot);
  ApplyEarlyReduction(result);
  return result;
}
References v8::internal::key, and v8::base::internal::result.
TryBuildSimplifiedLoadNamed()
JSTypeHintLowering::LoweringResult v8::internal::compiler::BytecodeGraphBuilder::TryBuildSimplifiedLoadNamed (const Operator * op, FeedbackSlot slot) [private]
Definition at line 4365 of file bytecode-graph-builder.cc.
                                                                     {
  Node* effect = environment()->GetEffectDependency();
  Node* control = environment()->GetControlDependency();
  JSTypeHintLowering::LoweringResult early_reduction =
      type_hint_lowering().ReduceLoadNamedOperation(op, effect, control, slot);
  ApplyEarlyReduction(early_reduction);
  return early_reduction;
}
TryBuildSimplifiedStoreKeyed()
JSTypeHintLowering::LoweringResult v8::internal::compiler::BytecodeGraphBuilder::TryBuildSimplifiedStoreKeyed (const Operator * op, Node * receiver, Node * key, Node * value, FeedbackSlot slot) [private]
Definition at line 4402 of file bytecode-graph-builder.cc.
                                                                      {
  Node* effect = environment()->GetEffectDependency();
  Node* control = environment()->GetControlDependency();
  JSTypeHintLowering::LoweringResult result =
      type_hint_lowering().ReduceStoreKeyedOperation(op, receiver, key, value,
                                                     effect, control, slot);
  ApplyEarlyReduction(result);
  return result;
}
References v8::internal::key, v8::base::internal::result, and v8::internal::value.
TryBuildSimplifiedStoreNamed()
JSTypeHintLowering::LoweringResult v8::internal::compiler::BytecodeGraphBuilder::TryBuildSimplifiedStoreNamed (const Operator * op, Node * receiver, Node * value, FeedbackSlot slot) [private]
Definition at line 4389 of file bytecode-graph-builder.cc.
                                                                      {
  Node* effect = environment()->GetEffectDependency();
  Node* control = environment()->GetControlDependency();
  JSTypeHintLowering::LoweringResult result =
      type_hint_lowering().ReduceStoreNamedOperation(op, receiver, value,
                                                     effect, control, slot);
  ApplyEarlyReduction(result);
  return result;
}
References v8::base::internal::result, and v8::internal::value.
TryBuildSimplifiedToNumber()
JSTypeHintLowering::LoweringResult v8::internal::compiler::BytecodeGraphBuilder::TryBuildSimplifiedToNumber (Node * input, FeedbackSlot slot) [private]
Definition at line 4325 of file bytecode-graph-builder.cc.
                                                                    {
  Node* effect = environment()->GetEffectDependency();
  Node* control = environment()->GetControlDependency();
  JSTypeHintLowering::LoweringResult result =
      type_hint_lowering().ReduceToNumberOperation(value, effect, control,
                                                   slot);
  ApplyEarlyReduction(result);
  return result;
}
References v8::base::internal::result, and v8::internal::value.
TryBuildSimplifiedUnaryOp()
JSTypeHintLowering::LoweringResult v8::internal::compiler::BytecodeGraphBuilder::TryBuildSimplifiedUnaryOp (const Operator * op, Node * operand, FeedbackSlot slot) [private]
Definition at line 4273 of file bytecode-graph-builder.cc.
                                                                   {
  Node* effect = environment()->GetEffectDependency();
  Node* control = environment()->GetControlDependency();
  JSTypeHintLowering::LoweringResult result =
      type_hint_lowering().ReduceUnaryOperation(op, operand, effect, control,
                                                slot);
  ApplyEarlyReduction(result);
  return result;
}
References v8::base::internal::result.
TryGetScopeInfo()
OptionalScopeInfoRef v8::internal::compiler::BytecodeGraphBuilder::TryGetScopeInfo () [private]
Definition at line 1836 of file bytecode-graph-builder.cc.
                                                           {
  Node* context = environment()->Context();
  switch (context->opcode()) {
    case IrOpcode::kJSCreateFunctionContext:
      return CreateFunctionContextParametersOf(context->op()).scope_info();
    case IrOpcode::kJSCreateBlockContext:
    case IrOpcode::kJSCreateCatchContext:
    case IrOpcode::kJSCreateWithContext:
      return ScopeInfoOf(context->op());
    case IrOpcode::kParameter: {
      ScopeInfoRef scope_info = shared_info_.scope_info(broker());
      if (scope_info.HasOuterScopeInfo()) {
        scope_info = scope_info.OuterScopeInfo(broker());
      }
      return scope_info;
    }
    default:
      return std::nullopt;
  }
}
References broker(), v8::internal::compiler::CreateFunctionContextParametersOf(), v8::internal::compiler::ScopeInfoRef::HasOuterScopeInfo(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::ScopeInfoRef::OuterScopeInfo(), v8::internal::compiler::CreateFunctionContextParameters::scope_info(), and v8::internal::compiler::ScopeInfoOf().
type_hint_lowering()
const JSTypeHintLowering& v8::internal::compiler::BytecodeGraphBuilder::type_hint_lowering () const [inline], [private]
Definition at line 405 of file bytecode-graph-builder.cc.
                                                       {
    return type_hint_lowering_;
  }
References type_hint_lowering_.
UpdateSourceAndBytecodePosition()
void v8::internal::compiler::BytecodeGraphBuilder::UpdateSourceAndBytecodePosition (int offset) [private]
Definition at line 4630 of file bytecode-graph-builder.cc.
                                                                     {
  if (node_origins_) {
    node_origins_->SetCurrentBytecodePosition(offset);
  }
  if (source_position_iterator().done()) return;
  if (source_position_iterator().code_offset() == offset) {
    source_positions_->SetCurrentPosition(SourcePosition(
        source_position_iterator().source_position().ScriptOffset(),
        start_position_.InliningId()));
    source_position_iterator().Advance();
  } else {
    DCHECK_GT(source_position_iterator().code_offset(), offset);
  }
}
References DCHECK_GT.
VisitBytecodes()
void v8::internal::compiler::BytecodeGraphBuilder::VisitBytecodes () [private]
Definition at line 1475 of file bytecode-graph-builder.cc.
                                          {
  if (!bytecode_analysis().resume_jump_targets().empty()) {
    environment()->BindGeneratorState(
        jsgraph()->SmiConstant(JSGeneratorObject::kGeneratorExecuting));
  }
  if (osr_) {
    // Make sure we're at a valid OSR entrypoint.
    // This is also a defense-in-depth check to make sure that we're not
    // compiling invalid bytecode if the OSR offset is wrong (e.g. because it
    // belongs to different bytecode).
    int osr_offset = bytecode_analysis().osr_bailout_id().ToInt();
    int osr_entry = bytecode_analysis().osr_entry_point();
    interpreter::BytecodeArrayIterator it(bytecode_array().object());
    it.AdvanceTo(osr_offset);
    CHECK(it.CurrentBytecodeIsValidOSREntry());
    CHECK_EQ(osr_entry, it.GetJumpTargetOffset());
    // We peel the OSR loop and any outer loop containing it except that we
    // leave the nodes corresponding to the whole outermost loop (including
    // the last copies of the loops it contains) to be generated by the normal
    // bytecode iteration below.
    AdvanceToOsrEntryAndPeelLoops();
  } else {
    BuildFunctionEntryStackCheck();
  }
  for (; !bytecode_iterator().done(); bytecode_iterator().Advance()) {
    VisitSingleBytecode();
  }
  DCHECK(exception_handlers_.empty());
}
References v8::internal::interpreter::BytecodeArrayIterator::AdvanceTo(), CHECK, CHECK_EQ, v8::internal::interpreter::BytecodeArrayIterator::CurrentBytecodeIsValidOSREntry(), v8::internal::DCHECK(), v8::internal::interpreter::BytecodeArrayIterator::GetJumpTargetOffset(), and v8::internal::JSGeneratorObject::kGeneratorExecuting.
Referenced by CreateGraph().
VisitSingleBytecode()
void v8::internal::compiler::BytecodeGraphBuilder::VisitSingleBytecode () [private]
Definition at line 1451 of file bytecode-graph-builder.cc.
                                               {
  tick_counter_->TickAndMaybeEnterSafepoint();
  int current_offset = bytecode_iterator().current_offset();
  UpdateSourceAndBytecodePosition(current_offset);
  ExitThenEnterExceptionHandlers(current_offset);
  DCHECK_GE(exception_handlers_.empty() ? current_offset
                                        : exception_handlers_.top().end_offset_,
            current_offset);
  SwitchToMergeEnvironment(current_offset);
  if (environment() != nullptr) {
    BuildLoopHeaderEnvironment(current_offset);
    switch (bytecode_iterator().current_bytecode()) {
#define BYTECODE_CASE(name, ...) \
  case interpreter::Bytecode::k##name: \
    Visit##name(); \
    break;
      BYTECODE_LIST(BYTECODE_CASE, BYTECODE_CASE)
#undef BYTECODE_CASE
    }
  }
}
References BYTECODE_CASE, BYTECODE_LIST, and DCHECK_GE.
Member Data Documentation
broker_
JSHeapBroker* const v8::internal::compiler::BytecodeGraphBuilder::broker_ [private]
Definition at line 451 of file bytecode-graph-builder.cc.
Referenced by broker().
bytecode_analysis_
BytecodeAnalysis const v8::internal::compiler::BytecodeGraphBuilder::bytecode_analysis_ [private]
Definition at line 466 of file bytecode-graph-builder.cc.
Referenced by bytecode_analysis().
bytecode_array_
BytecodeArrayRef const v8::internal::compiler::BytecodeGraphBuilder::bytecode_array_ [private]
Definition at line 458 of file bytecode-graph-builder.cc.
Referenced by bytecode_array().
bytecode_iterator_
interpreter::BytecodeArrayIterator v8::internal::compiler::BytecodeGraphBuilder::bytecode_iterator_ [private]
Definition at line 465 of file bytecode-graph-builder.cc.
Referenced by bytecode_iterator().
cached_parameters_
ZoneVector<Node*> v8::internal::compiler::BytecodeGraphBuilder::cached_parameters_ [private]
Definition at line 488 of file bytecode-graph-builder.cc.
Referenced by GetParameter().
code_kind_
const CodeKind v8::internal::compiler::BytecodeGraphBuilder::code_kind_ [private]
Definition at line 498 of file bytecode-graph-builder.cc.
Referenced by code_kind().
current_exception_handler_
int v8::internal::compiler::BytecodeGraphBuilder::current_exception_handler_ [private]
Definition at line 492 of file bytecode-graph-builder.cc.
Referenced by current_exception_handler(), and set_current_exception_handler().
currently_peeled_loop_offset_
int v8::internal::compiler::BytecodeGraphBuilder::currently_peeled_loop_offset_ [private]
Definition at line 470 of file bytecode-graph-builder.cc.
Referenced by currently_peeled_loop_offset(), and set_currently_peeled_loop_offset().
decorator_
BytecodePositionDecorator* v8::internal::compiler::BytecodeGraphBuilder::decorator_ [private]
Definition at line 468 of file bytecode-graph-builder.cc.
environment_
Environment* v8::internal::compiler::BytecodeGraphBuilder::environment_ [private]
Definition at line 467 of file bytecode-graph-builder.cc.
Referenced by environment(), and set_environment().
exception_handlers_
ZoneStack<ExceptionHandler> v8::internal::compiler::BytecodeGraphBuilder::exception_handlers_ [private]
Definition at line 491 of file bytecode-graph-builder.cc.
exit_controls_
ZoneVector<Node*> v8::internal::compiler::BytecodeGraphBuilder::exit_controls_ [private]
Definition at line 511 of file bytecode-graph-builder.cc.
Referenced by CreateGraph().
feedback_cell_
FeedbackCellRef const v8::internal::compiler::BytecodeGraphBuilder::feedback_cell_ [private]
Definition at line 459 of file bytecode-graph-builder.cc.
feedback_vector_
FeedbackVectorRef const v8::internal::compiler::BytecodeGraphBuilder::feedback_vector_ [private]
Definition at line 460 of file bytecode-graph-builder.cc.
Referenced by feedback_vector().
feedback_vector_node_
Node* v8::internal::compiler::BytecodeGraphBuilder::feedback_vector_node_ [private]
Definition at line 499 of file bytecode-graph-builder.cc.
Referenced by CreateFeedbackVectorNode(), and feedback_vector_node().
frame_state_function_info_
const FrameStateFunctionInfo* const v8::internal::compiler::BytecodeGraphBuilder::frame_state_function_info_ [private]
Definition at line 463 of file bytecode-graph-builder.cc.
Referenced by frame_state_function_info().
function_closure_
SetOncePointer<Node> v8::internal::compiler::BytecodeGraphBuilder::function_closure_ [private]
Definition at line 508 of file bytecode-graph-builder.cc.
Referenced by GetFunctionClosure().
generator_merge_environments_
ZoneMap<int, Environment*> v8::internal::compiler::BytecodeGraphBuilder::generator_merge_environments_ [private]
Definition at line 486 of file bytecode-graph-builder.cc.
input_buffer_
Node** v8::internal::compiler::BytecodeGraphBuilder::input_buffer_ [private]
Definition at line 496 of file bytecode-graph-builder.cc.
input_buffer_size_
int v8::internal::compiler::BytecodeGraphBuilder::input_buffer_size_ [private]
Definition at line 495 of file bytecode-graph-builder.cc.
invocation_frequency_
CallFrequency const v8::internal::compiler::BytecodeGraphBuilder::invocation_frequency_ [private]
Definition at line 461 of file bytecode-graph-builder.cc.
jsgraph_
JSGraph* const v8::internal::compiler::BytecodeGraphBuilder::jsgraph_ [private]
Definition at line 454 of file bytecode-graph-builder.cc.
Referenced by common(), graph(), isolate(), javascript(), jsgraph(), and simplified().
kBinaryOperationHintIndex
constexpr int v8::internal::compiler::BytecodeGraphBuilder::kBinaryOperationHintIndex = 1 [static], [constexpr], [private]
Definition at line 527 of file bytecode-graph-builder.cc.
kBinaryOperationSmiHintIndex
constexpr int v8::internal::compiler::BytecodeGraphBuilder::kBinaryOperationSmiHintIndex = 1 [static], [constexpr], [private]
Definition at line 528 of file bytecode-graph-builder.cc.
kCompareOperationHintIndex
constexpr int v8::internal::compiler::BytecodeGraphBuilder::kCompareOperationHintIndex = 1 [static], [constexpr], [private]
Definition at line 529 of file bytecode-graph-builder.cc.
kCountOperationHintIndex
constexpr int v8::internal::compiler::BytecodeGraphBuilder::kCountOperationHintIndex = 0 [static], [constexpr], [private]
Definition at line 530 of file bytecode-graph-builder.cc.
kInputBufferSizeIncrement
const int v8::internal::compiler::BytecodeGraphBuilder::kInputBufferSizeIncrement = 64 [static], [private]
Definition at line 369 of file bytecode-graph-builder.cc.
kUnaryOperationHintIndex
constexpr int v8::internal::compiler::BytecodeGraphBuilder::kUnaryOperationHintIndex = 0 [static], [constexpr], [private]
Definition at line 531 of file bytecode-graph-builder.cc.
local_isolate_
LocalIsolate* const v8::internal::compiler::BytecodeGraphBuilder::local_isolate_ [private]
Definition at line 452 of file bytecode-graph-builder.cc.
Referenced by MakeRefForConstantForIndexOperand().
local_zone_
Zone* const v8::internal::compiler::BytecodeGraphBuilder::local_zone_ [private]
Definition at line 453 of file bytecode-graph-builder.cc.
Referenced by local_zone().
merge_environments_
ZoneMap<int, Environment*> v8::internal::compiler::BytecodeGraphBuilder::merge_environments_ [private]
Definition at line 478 of file bytecode-graph-builder.cc.
native_context_
NativeContextRef const v8::internal::compiler::BytecodeGraphBuilder::native_context_ [private]
Definition at line 456 of file bytecode-graph-builder.cc.
Referenced by native_context().
native_context_node_
Node* v8::internal::compiler::BytecodeGraphBuilder::native_context_node_ [private]
Definition at line 500 of file bytecode-graph-builder.cc.
Referenced by CreateNativeContextNode(), and native_context_node().
needs_eager_checkpoint_
bool v8::internal::compiler::BytecodeGraphBuilder::needs_eager_checkpoint_ [private]
Definition at line 505 of file bytecode-graph-builder.cc.
Referenced by mark_as_needing_eager_checkpoint(), and needs_eager_checkpoint().
node_origins_
NodeOriginTable* const v8::internal::compiler::BytecodeGraphBuilder::node_origins_ [private]
Definition at line 516 of file bytecode-graph-builder.cc.
Referenced by CreateGraph(), and v8::internal::compiler::BytecodeGraphBuilder::BytecodePositionDecorator::Decorate().
observe_node_info_
ObserveNodeInfo const v8::internal::compiler::BytecodeGraphBuilder::observe_node_info_ [private]
Definition at line 525 of file bytecode-graph-builder.cc.
osr_
bool const v8::internal::compiler::BytecodeGraphBuilder::osr_ [private]
Definition at line 469 of file bytecode-graph-builder.cc.
Referenced by skip_tierup_check().
shared_info_
SharedFunctionInfoRef const v8::internal::compiler::BytecodeGraphBuilder::shared_info_ [private]
Definition at line 457 of file bytecode-graph-builder.cc.
Referenced by shared_info().
skip_first_stack_and_tierup_check_
const bool v8::internal::compiler::BytecodeGraphBuilder::skip_first_stack_and_tierup_check_ [private]
Definition at line 472 of file bytecode-graph-builder.cc.
Referenced by skip_first_stack_check(), and skip_tierup_check().
source_position_iterator_
SourcePositionTableIterator v8::internal::compiler::BytecodeGraphBuilder::source_position_iterator_ [private]
Definition at line 464 of file bytecode-graph-builder.cc.
Referenced by source_position_iterator().
source_positions_
SourcePositionTable* const v8::internal::compiler::BytecodeGraphBuilder::source_positions_ [private]
Definition at line 519 of file bytecode-graph-builder.cc.
Referenced by CreateGraph().
start_position_
SourcePosition const v8::internal::compiler::BytecodeGraphBuilder::start_position_ [private]
Definition at line 521 of file bytecode-graph-builder.cc.
Referenced by CreateGraph().
state_values_cache_
StateValuesCache v8::internal::compiler::BytecodeGraphBuilder::state_values_cache_ [private]
Definition at line 513 of file bytecode-graph-builder.cc.
tick_counter_
TickCounter* const v8::internal::compiler::BytecodeGraphBuilder::tick_counter_ [private]
Definition at line 523 of file bytecode-graph-builder.cc.
type_hint_lowering_
JSTypeHintLowering const v8::internal::compiler::BytecodeGraphBuilder::type_hint_lowering_ [private]
Definition at line 462 of file bytecode-graph-builder.cc.
Referenced by type_hint_lowering().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/bytecode-graph-builder.cc