v8::internal::JSGlobalProxy Class Reference
#include <js-objects.h>
Public Member Functions
bool IsDetachedFrom (Isolate *isolate, Tagged< JSGlobalObject > global) const
V8_EXPORT_PRIVATE bool IsDetached ()
Static Public Member Functions
static int SizeWithEmbedderFields (int embedder_field_count)
Detailed Description
Definition at line 1186 of file js-objects.h.
Member Function Documentation
IsDetached()
bool v8::internal::JSGlobalProxy::IsDetached ()
Definition at line 5683 of file js-objects.cc.
{ return !GetCreationContext().has_value(); }
References v8::debug::GetCreationContext().
IsDetachedFrom()
bool v8::internal::JSGlobalProxy::IsDetachedFrom (Isolate * isolate, Tagged< JSGlobalObject > global) const [inline]
Definition at line 1017 of file js-objects-inl.h.
                                                                        {
  const PrototypeIterator iter(isolate, Tagged<JSReceiver>(*this));
  return iter.GetCurrent() != global;
}
References v8::internal::PrototypeIterator::GetCurrent().
SizeWithEmbedderFields()
int v8::internal::JSGlobalProxy::SizeWithEmbedderFields (int embedder_field_count) [inline], [static]
Definition at line 1023 of file js-objects-inl.h.
                                                                         {
  DCHECK_GE(embedder_field_count, 0);
  return kHeaderSize + embedder_field_count * kEmbedderDataSlotSize;
}
References DCHECK_GE, and v8::internal::kEmbedderDataSlotSize.
Referenced by v8::internal::Genesis::CreateNewGlobals(), and v8::internal::Genesis::Genesis().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-objects.h
/mnt/V8SourceCode/src/objects/js-objects-inl.h
/mnt/V8SourceCode/src/objects/js-objects.cc