v8::ScriptCompiler::StreamedSource Class Reference
Source code which can be streamed into V8 in pieces.
#include <v8-script.h>
Public Types
enum Encoding { ONE_BYTE
, TWO_BYTE
, UTF8
, WINDOWS_1252
 }
Public Member Functions
StreamedSource (std::unique_ptr< ExternalSourceStream > source_stream, Encoding encoding)
~StreamedSource ()
internal::ScriptStreamingData * impl () const
StreamedSource (const StreamedSource &)=delete
StreamedSource & operator= (const StreamedSource &)=delete
CompilationDetails & compilation_details ()
Private Attributes
std::unique_ptr< internal::ScriptStreamingData > impl_
CompilationDetails compilation_details_
Detailed Description
Source code which can be streamed into V8 in pieces.
It will be parsed while streaming and compiled after parsing has completed. StreamedSource must be kept alive while the streaming task is run (see ScriptStreamingTask below).
Definition at line 582 of file v8-script.h.
Member Enumeration Documentation
Encoding
enum v8::ScriptCompiler::StreamedSource::Encoding
Enumerator
ONE_BYTE
TWO_BYTE
UTF8
WINDOWS_1252
Definition at line 584 of file v8-script.h.
{ ONE_BYTE, TWO_BYTE, UTF8, WINDOWS_1252 };
Constructor & Destructor Documentation
StreamedSource() [1/2]
v8::ScriptCompiler::StreamedSource::StreamedSource (std::unique_ptr< ExternalSourceStream > source_stream, Encoding encoding)
Definition at line 1776 of file api.cc.
    : impl_(new i::ScriptStreamingData(std::move(stream), encoding)) {}
 StreamedSource()
v8::ScriptCompiler::StreamedSource::~StreamedSource () [default]
StreamedSource() [2/2]
v8::ScriptCompiler::StreamedSource::StreamedSource (const StreamedSource &) [delete]
Member Function Documentation
compilation_details()
CompilationDetails& v8::ScriptCompiler::StreamedSource::compilation_details () [inline]
Definition at line 596 of file v8-script.h.
{ return compilation_details_; }
Referenced by v8::anonymous_namespace{api.cc}::CompileStreamedSource(), and v8::ScriptCompiler::StartStreaming().
impl()
internal::ScriptStreamingData* v8::ScriptCompiler::StreamedSource::impl () const [inline]
Definition at line 590 of file v8-script.h.
{ return impl_.get(); }
Referenced by v8::anonymous_namespace{api.cc}::CompileStreamedSource(), and v8::ScriptCompiler::StartStreaming().
operator=()
StreamedSource& v8::ScriptCompiler::StreamedSource::operator= (const StreamedSource &) [delete]
Member Data Documentation
compilation_details_
CompilationDetails v8::ScriptCompiler::StreamedSource::compilation_details_ [private]
Definition at line 603 of file v8-script.h.
impl_
std::unique_ptr<internal::ScriptStreamingData> v8::ScriptCompiler::StreamedSource::impl_ [private]
Definition at line 599 of file v8-script.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-script.h
/mnt/V8SourceCode/src/api/api.cc