v8::internal::compiler::CommonOperatorBuilder Class Reference
#include <common-operator.h>
Public Member Functions
CommonOperatorBuilder (Zone *zone)
CommonOperatorBuilder (const CommonOperatorBuilder &)=delete
CommonOperatorBuilder & operator= (const CommonOperatorBuilder &)=delete
const Operator * Plug ()
const Operator * Chained (const Operator *op)
const Operator * Dead ()
const Operator * DeadValue (MachineRepresentation rep, int value_input_count=1)
const Operator * Unreachable ()
const Operator * StaticAssert (const char *source)
const Operator * SLVerifierHint (const Operator *semantics, const std::optional< Type > &override_output_type)
const Operator * End (size_t control_input_count)
const Operator * Branch (BranchHint=BranchHint::kNone, BranchSemantics semantics=BranchSemantics::kUnspecified)
const Operator * IfTrue ()
const Operator * IfFalse ()
const Operator * IfSuccess ()
const Operator * IfException ()
const Operator * Switch (size_t control_output_count)
const Operator * IfValue (int32_t value, int32_t order=0, BranchHint hint=BranchHint::kNone)
const Operator * IfDefault (BranchHint hint=BranchHint::kNone)
const Operator * Throw ()
const Operator * Deoptimize (DeoptimizeReason reason, FeedbackSource const &feedback)
const Operator * DeoptimizeIf (DeoptimizeReason reason, FeedbackSource const &feedback)
const Operator * DeoptimizeUnless (DeoptimizeReason reason, FeedbackSource const &feedback)
const Operator * Assert (BranchSemantics semantics, const char *condition_string, const char *file, int line)
const Operator * Return (int value_input_count=1)
const Operator * Terminate ()
const Operator * Start (int value_output_count)
const Operator * Loop (int control_input_count)
const Operator * Merge (int control_input_count)
const Operator * Parameter (int index, const char *debug_name=nullptr)
const Operator * OsrValue (int index)
const Operator * Int32Constant (int32_t)
const Operator * Int64Constant (int64_t)
const Operator * TaggedIndexConstant (int32_t value)
const Operator * Float32Constant (float)
const Operator * Float64Constant (double)
const Operator * ExternalConstant (const ExternalReference &)
const Operator * NumberConstant (double)
const Operator * PointerConstant (intptr_t)
const Operator * HeapConstant (const Handle< HeapObject > &)
const Operator * CompressedHeapConstant (const Handle< HeapObject > &)
const Operator * TrustedHeapConstant (const Handle< HeapObject > &)
const Operator * ObjectId (uint32_t)
const Operator * RelocatableInt32Constant (int32_t value, RelocInfo::Mode rmode)
const Operator * RelocatableInt64Constant (int64_t value, RelocInfo::Mode rmode)
const Operator * Select (MachineRepresentation, BranchHint=BranchHint::kNone, BranchSemantics semantics=BranchSemantics::kUnspecified)
const Operator * Phi (MachineRepresentation representation, int value_input_count)
const Operator * EffectPhi (int effect_input_count)
const Operator * InductionVariablePhi (int value_input_count)
const Operator * LoopExit ()
const Operator * LoopExitValue (MachineRepresentation rep)
const Operator * LoopExitEffect ()
const Operator * Checkpoint ()
const Operator * BeginRegion (RegionObservability)
const Operator * FinishRegion ()
const Operator * StateValues (int arguments, SparseInputMask bitmask)
const Operator * TypedStateValues (const ZoneVector< MachineType > *types, SparseInputMask bitmask)
const Operator * ArgumentsElementsState (ArgumentsStateType type)
const Operator * ArgumentsLengthState ()
const Operator * ObjectState (uint32_t object_id, int pointer_slots)
const Operator * TypedObjectState (uint32_t object_id, const ZoneVector< MachineType > *types)
const Operator * FrameState (BytecodeOffset bailout_id, OutputFrameStateCombine state_combine, const FrameStateFunctionInfo *function_info)
const Operator * Call (const CallDescriptor *call_descriptor)
const Operator * TailCall (const CallDescriptor *call_descriptor)
const Operator * Projection (size_t index)
const Operator * Retain ()
const Operator * TypeGuard (Type type)
const Operator * EnterMachineGraph (UseInfo use_info)
const Operator * ExitMachineGraph (MachineRepresentation output_representation, Type output_type)
const Operator * ResizeMergeOrPhi (const Operator *op, int size)
const FrameStateFunctionInfo * CreateFrameStateFunctionInfo (FrameStateType type, uint16_t parameter_count, uint16_t max_arguments, int local_count, IndirectHandle< SharedFunctionInfo > shared_info, IndirectHandle< BytecodeArray > bytecode_array)
Private Member Functions
Zone * zone () const
Private Attributes
const CommonOperatorGlobalCache & cache_
Zone *const zone_
Detailed Description
Definition at line 542 of file common-operator.h.
Constructor & Destructor Documentation
CommonOperatorBuilder() [1/2]
v8::internal::compiler::CommonOperatorBuilder::CommonOperatorBuilder (Zone * zone) [explicit]
Definition at line 970 of file common-operator.cc.
    : cache_(*GetCommonOperatorGlobalCache()), zone_(zone) {}
CommonOperatorBuilder() [2/2]
v8::internal::compiler::CommonOperatorBuilder::CommonOperatorBuilder (const CommonOperatorBuilder &) [delete]
Member Function Documentation
ArgumentsElementsState()
const Operator * v8::internal::compiler::CommonOperatorBuilder::ArgumentsElementsState (ArgumentsStateType type)
Definition at line 1545 of file common-operator.cc.
                             {
  return zone()->New<Operator1<ArgumentsStateType>>(// --
      IrOpcode::kArgumentsElementsState, Operator::kPure, // opcode
      "ArgumentsElementsState", // name
      0, 0, 0, 1, 0, 0, // counts
      type); // parameter
}
References v8::internal::compiler::Operator::kPure, v8::internal::Zone::New(), v8::internal::tracing::type, and zone().
ArgumentsLengthState()
const Operator * v8::internal::compiler::CommonOperatorBuilder::ArgumentsLengthState ()
Definition at line 1554 of file common-operator.cc.
                                                            {
  return zone()->New<Operator>(// --
      IrOpcode::kArgumentsLengthState, Operator::kPure, // opcode
      "ArgumentsLengthState", // name
      0, 0, 0, 1, 0, 0); // counts
}
References v8::internal::compiler::Operator::kPure, v8::internal::Zone::New(), and zone().
Assert()
const Operator * v8::internal::compiler::CommonOperatorBuilder::Assert (BranchSemantics semantics, const char * condition_string, const char * file, int line)
Definition at line 1097 of file common-operator.cc.
                                                                          {
  AssertParameters parameter(semantics, condition_string, file, line);
  return zone()->New<Operator1<AssertParameters>>(// --
      IrOpcode::kAssert, // opcode
      Operator::kFoldable | Operator::kNoThrow, // properties
      "Assert", // name
      1, 1, 1, 0, 1, 0, // counts
      parameter); // parameter
}
References file(), v8::internal::compiler::Operator::kFoldable, v8::internal::compiler::Operator::kNoThrow, v8::internal::Zone::New(), and zone().
BeginRegion()
const Operator * v8::internal::compiler::CommonOperatorBuilder::BeginRegion (RegionObservability region_observability)
Definition at line 1494 of file common-operator.cc.
                                              {
  switch (region_observability) {
    case RegionObservability::kObservable:
      return &cache_.kBeginRegionObservableOperator;
    case RegionObservability::kNotObservable:
      return &cache_.kBeginRegionNotObservableOperator;
  }
  UNREACHABLE();
}
References cache_, v8::internal::compiler::CommonOperatorGlobalCache::kBeginRegionNotObservableOperator, v8::internal::compiler::CommonOperatorGlobalCache::kBeginRegionObservableOperator, v8::internal::compiler::kNotObservable, v8::internal::compiler::kObservable, and v8::internal::UNREACHABLE().
Branch()
const Operator * v8::internal::compiler::CommonOperatorBuilder::Branch (BranchHint hint = BranchHint::kNone, BranchSemantics semantics = BranchSemantics::kUnspecified)
Definition at line 1031 of file common-operator.cc.
                                                                         {
#define CACHED_BRANCH(Semantics, Hint) \
  if (semantics == BranchSemantics::k##Semantics && \
      hint == BranchHint::k##Hint) { \
    return &cache_.kBranch##Semantics##Hint##Operator; \
  }
  CACHED_BRANCH_LIST(CACHED_BRANCH)
#undef CACHED_BRANCH
  UNREACHABLE();
}
References CACHED_BRANCH, CACHED_BRANCH_LIST, and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::Diamond::Diamond().
Call()
const Operator * v8::internal::compiler::CommonOperatorBuilder::Call (const CallDescriptor * call_descriptor)
Definition at line 1613 of file common-operator.cc.
                                           {
  class CallOperator final : public Operator1<const CallDescriptor*> {
   public:
    explicit CallOperator(const CallDescriptor* call_descriptor)
        : Operator1<const CallDescriptor*>(
              IrOpcode::kCall, call_descriptor->properties(), "Call",
              call_descriptor->InputCount() +
                  call_descriptor->FrameStateCount(),
              Operator::ZeroIfPure(call_descriptor->properties()),
              Operator::ZeroIfEliminatable(call_descriptor->properties()),
              call_descriptor->ReturnCount(),
              Operator::ZeroIfPure(call_descriptor->properties()),
              Operator::ZeroIfNoThrow(call_descriptor->properties()),
              call_descriptor) {}
    void PrintParameter(std::ostream& os,
                        PrintVerbosity verbose) const override {
      os << "[" << *parameter() << "]";
    }
  };
  return zone()->New<CallOperator>(call_descriptor);
}
References v8::internal::compiler::CallDescriptor::FrameStateCount(), v8::internal::compiler::CallDescriptor::InputCount(), v8::internal::Zone::New(), v8::internal::compiler::CallDescriptor::properties(), v8::internal::compiler::CallDescriptor::ReturnCount(), v8::internal::compiler::Operator::ZeroIfEliminatable(), v8::internal::compiler::Operator::ZeroIfNoThrow(), v8::internal::compiler::Operator::ZeroIfPure(), and zone().
Referenced by v8::internal::compiler::WasmGraphBuilder::BuildWasmCall(), v8::internal::compiler::GraphAssembler::Call(), and v8::internal::compiler::anonymous_namespace{js-typed-lowering.cc}::ReduceBuiltin().
Chained()
const Operator * v8::internal::compiler::CommonOperatorBuilder::Chained (const Operator * op)
Definition at line 1715 of file common-operator.cc.
                                                                 {
  // Use Chained only for operators that are not on the effect chain already.
  DCHECK_EQ(op->EffectInputCount(), 0);
  DCHECK_EQ(op->ControlInputCount(), 0);
  const char* mnemonic;
  switch (op->opcode()) {
    case IrOpcode::kChangeInt64ToBigInt:
      mnemonic = "Chained[ChangeInt64ToBigInt]";
      break;
    case IrOpcode::kChangeUint64ToBigInt:
      mnemonic = "Chained[ChangeUint64ToBigInt]";
      break;
    default:
      UNREACHABLE();
  }
  // TODO(nicohartmann@): Need to store operator properties once we have to
  // support Operator1 operators.
  Operator::Properties properties = op->properties();
  return zone()->New<Operator>(op->opcode(), properties, mnemonic,
                               op->ValueInputCount(), 1, 1,
                               op->ValueOutputCount(), 1, 0);
}
References v8::internal::compiler::Operator::ControlInputCount(), DCHECK_EQ, v8::internal::compiler::Operator::EffectInputCount(), v8::internal::Zone::New(), v8::internal::compiler::Operator::opcode(), v8::internal::compiler::Operator::properties(), v8::internal::UNREACHABLE(), v8::internal::compiler::Operator::ValueInputCount(), v8::internal::compiler::Operator::ValueOutputCount(), and zone().
Checkpoint()
const Operator* v8::internal::compiler::CommonOperatorBuilder::Checkpoint ()
CompressedHeapConstant()
const Operator * v8::internal::compiler::CommonOperatorBuilder::CompressedHeapConstant (const Handle< HeapObject > & value)
Definition at line 1352 of file common-operator.cc.
                                     {
  return zone()->New<Operator1<IndirectHandle<HeapObject>>>(// --
      IrOpcode::kCompressedHeapConstant, Operator::kPure, // opcode
      "CompressedHeapConstant", // name
      0, 0, 0, 1, 0, 0, // counts
      value); // parameter
}
References v8::internal::compiler::Operator::kPure, v8::internal::Zone::New(), v8::internal::value, and zone().
CreateFrameStateFunctionInfo()
const FrameStateFunctionInfo * v8::internal::compiler::CommonOperatorBuilder::CreateFrameStateFunctionInfo (FrameStateType type, uint16_t parameter_count, uint16_t max_arguments, int local_count, IndirectHandle< SharedFunctionInfo > shared_info, IndirectHandle< BytecodeArray > bytecode_array)
Definition at line 1693 of file common-operator.cc.
                                                  {
  return zone()->New<FrameStateFunctionInfo>(type, parameter_count,
                                             max_arguments, local_count,
                                             shared_info, bytecode_array);
}
References v8::internal::Zone::New(), v8::internal::tracing::type, and zone().
Referenced by v8::internal::compiler::JSInliner::CreateArtificialFrameState(), v8::internal::compiler::anonymous_namespace{frame-states.cc}::CreateBuiltinContinuationFrameStateCommon(), and v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::CreateConstructInvokeStubFrameState().
Dead()
const Operator* v8::internal::compiler::CommonOperatorBuilder::Dead ()
Referenced by v8::internal::compiler::LoopPeeler::Peel(), and v8::internal::compiler::UnrollLoop().
DeadValue()
const Operator * v8::internal::compiler::CommonOperatorBuilder::DeadValue (MachineRepresentation rep, int value_input_count = 1)
Definition at line 1738 of file common-operator.cc.
                                                                        {
  return zone()->New<Operator1<MachineRepresentation>>(// --
      IrOpcode::kDeadValue, Operator::kPure, // opcode
      "DeadValue", // name
      value_input_count, 0, 0, 1, 0, 0, // counts
      rep); // parameter
}
References v8::internal::compiler::Operator::kPure, v8::internal::Zone::New(), and zone().
Referenced by v8::internal::compiler::RepresentationSelector::ChangeToDeadValue().
Deoptimize()
const Operator * v8::internal::compiler::CommonOperatorBuilder::Deoptimize (DeoptimizeReason reason, FeedbackSource const & feedback)
Definition at line 1043 of file common-operator.cc.
                                                             {
#define CACHED_DEOPTIMIZE(Reason) \
  if (reason == DeoptimizeReason::k##Reason && !feedback.IsValid()) { \
    return &cache_.kDeoptimize##Reason##Operator; \
  }
  CACHED_DEOPTIMIZE_LIST(CACHED_DEOPTIMIZE)
#undef CACHED_DEOPTIMIZE
  // Uncached
  DeoptimizeParameters parameter(reason, feedback);
  return zone()->New<Operator1<DeoptimizeParameters>>(// --
      IrOpcode::kDeoptimize, // opcodes
      Operator::kFoldable | Operator::kNoThrow, // properties
      "Deoptimize", // name
      1, 1, 1, 0, 0, 1, // counts
      parameter); // parameter
}
References CACHED_DEOPTIMIZE, CACHED_DEOPTIMIZE_LIST, v8::internal::compiler::Operator::kFoldable, v8::internal::compiler::Operator::kNoThrow, v8::internal::Zone::New(), and zone().
DeoptimizeIf()
const Operator * v8::internal::compiler::CommonOperatorBuilder::DeoptimizeIf (DeoptimizeReason reason, FeedbackSource const & feedback)
Definition at line 1061 of file common-operator.cc.
                                                             {
#define CACHED_DEOPTIMIZE_IF(Reason) \
  if (reason == DeoptimizeReason::k##Reason && !feedback.IsValid()) { \
    return &cache_.kDeoptimizeIf##Reason##Operator; \
  }
  CACHED_DEOPTIMIZE_IF_LIST(CACHED_DEOPTIMIZE_IF)
#undef CACHED_DEOPTIMIZE_IF
  // Uncached
  DeoptimizeParameters parameter(reason, feedback);
  return zone()->New<Operator1<DeoptimizeParameters>>(// --
      IrOpcode::kDeoptimizeIf, // opcode
      Operator::kFoldable | Operator::kNoThrow, // properties
      "DeoptimizeIf", // name
      2, 1, 1, 0, 1, 1, // counts
      parameter); // parameter
}
References CACHED_DEOPTIMIZE_IF, CACHED_DEOPTIMIZE_IF_LIST, v8::internal::compiler::Operator::kFoldable, v8::internal::compiler::Operator::kNoThrow, v8::internal::Zone::New(), and zone().
DeoptimizeUnless()
const Operator * v8::internal::compiler::CommonOperatorBuilder::DeoptimizeUnless (DeoptimizeReason reason, FeedbackSource const & feedback)
Definition at line 1079 of file common-operator.cc.
                                                             {
#define CACHED_DEOPTIMIZE_UNLESS(Reason) \
  if (reason == DeoptimizeReason::k##Reason && !feedback.IsValid()) { \
    return &cache_.kDeoptimizeUnless##Reason##Operator; \
  }
  CACHED_DEOPTIMIZE_UNLESS_LIST(CACHED_DEOPTIMIZE_UNLESS)
#undef CACHED_DEOPTIMIZE_UNLESS
  // Uncached
  DeoptimizeParameters parameter(reason, feedback);
  return zone()->New<Operator1<DeoptimizeParameters>>(// --
      IrOpcode::kDeoptimizeUnless, // opcode
      Operator::kFoldable | Operator::kNoThrow, // properties
      "DeoptimizeUnless", // name
      2, 1, 1, 0, 1, 1, // counts
      parameter); // parameter
}
References CACHED_DEOPTIMIZE_UNLESS, CACHED_DEOPTIMIZE_UNLESS_LIST, v8::internal::compiler::Operator::kFoldable, v8::internal::compiler::Operator::kNoThrow, v8::internal::Zone::New(), and zone().
EffectPhi()
const Operator * v8::internal::compiler::CommonOperatorBuilder::EffectPhi (int effect_input_count)
Definition at line 1457 of file common-operator.cc.
                                                                       {
  DCHECK_LT(0, effect_input_count); // Disallow empty effect phis.
  switch (effect_input_count) {
#define CACHED_EFFECT_PHI(input_count) \
  case input_count: \
    return &cache_.kEffectPhi##input_count##Operator;
    CACHED_EFFECT_PHI_LIST(CACHED_EFFECT_PHI)
#undef CACHED_EFFECT_PHI
    default:
      break;
  }
  // Uncached.
  return zone()->New<Operator>(// --
      IrOpcode::kEffectPhi, Operator::kKontrol, // opcode
      "EffectPhi", // name
      0, effect_input_count, 1, 0, 1, 0); // counts
}
References CACHED_EFFECT_PHI, CACHED_EFFECT_PHI_LIST, DCHECK_LT, v8::internal::compiler::Operator::kKontrol, v8::internal::Zone::New(), and zone().
Referenced by v8::internal::compiler::Diamond::EffectPhi(), v8::internal::compiler::LoopPeeler::Peel(), v8::internal::compiler::SimplifyTFLoops::Reduce(), ResizeMergeOrPhi(), and v8::internal::compiler::UnrollLoop().
End()
const Operator * v8::internal::compiler::CommonOperatorBuilder::End (size_t control_input_count)
Definition at line 983 of file common-operator.cc.
                                                                     {
  switch (control_input_count) {
#define CACHED_END(input_count) \
  case input_count: \
    return &cache_.kEnd##input_count##Operator;
    CACHED_END_LIST(CACHED_END)
#undef CACHED_END
    default:
      break;
  }
  // Uncached.
  return zone()->New<Operator>(//--
      IrOpcode::kEnd, Operator::kKontrol, // opcode
      "End", // name
      0, 0, control_input_count, 0, 0, 0); // counts
}
References CACHED_END, CACHED_END_LIST, v8_inspector::anonymous_namespace{value-mirror.cc}::kEnd, v8::internal::compiler::Operator::kKontrol, v8::internal::Zone::New(), and zone().
Referenced by v8::internal::compiler::NodeProperties::MergeControlToEnd(), v8::internal::compiler::RawMachineAssembler::RawMachineAssembler(), v8::internal::compiler::NodeProperties::RemoveControlFromEnd(), and v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::WasmIntoJSInlinerImpl().
EnterMachineGraph()
const Operator * v8::internal::compiler::CommonOperatorBuilder::EnterMachineGraph (UseInfo use_info)
Definition at line 1444 of file common-operator.cc.
                                                                         {
  return zone()->New<Operator1<UseInfo>>(IrOpcode::kEnterMachineGraph,
                                         Operator::kPure, "EnterMachineGraph",
                                         1, 0, 0, 1, 0, 0, use_info);
}
References v8::internal::compiler::Operator::kPure, v8::internal::Zone::New(), and zone().
ExitMachineGraph()
const Operator * v8::internal::compiler::CommonOperatorBuilder::ExitMachineGraph (MachineRepresentation output_representation, Type output_type)
Definition at line 1450 of file common-operator.cc.
                                                                   {
  return zone()->New<Operator1<ExitMachineGraphParameters>>(
      IrOpcode::kExitMachineGraph, Operator::kPure, "ExitMachineGraph", 1, 0, 0,
      1, 0, 0, ExitMachineGraphParameters{output_representation, output_type});
}
References v8::internal::compiler::Operator::kPure, v8::internal::Zone::New(), and zone().
ExternalConstant()
const Operator * v8::internal::compiler::CommonOperatorBuilder::ExternalConstant (const ExternalReference & value)
Definition at line 1317 of file common-operator.cc.
                                    {
  return zone()->New<Operator1<ExternalReference>>(// --
      IrOpcode::kExternalConstant, Operator::kPure, // opcode
      "ExternalConstant", // name
      0, 0, 0, 1, 0, 0, // counts
      value); // parameter
}
References v8::internal::compiler::Operator::kPure, v8::internal::Zone::New(), v8::internal::value, and zone().
Referenced by v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::PushRegularApiCallInputs().
FinishRegion()
const Operator* v8::internal::compiler::CommonOperatorBuilder::FinishRegion ()
Float32Constant()
const Operator * v8::internal::compiler::CommonOperatorBuilder::Float32Constant (float value)
Definition at line 1299 of file common-operator.cc.
                                                                  {
  return zone()->New<Operator1<float>>(// --
      IrOpcode::kFloat32Constant, Operator::kPure, // opcode
      "Float32Constant", // name
      0, 0, 0, 1, 0, 0, // counts
      value); // parameter
}
References v8::internal::compiler::Operator::kPure, v8::internal::Zone::New(), v8::internal::value, and zone().
Float64Constant()
const Operator * v8::internal::compiler::CommonOperatorBuilder::Float64Constant (double value)
Definition at line 1308 of file common-operator.cc.
                                                                   {
  return zone()->New<Operator1<double>>(// --
      IrOpcode::kFloat64Constant, Operator::kPure, // opcode
      "Float64Constant", // name
      0, 0, 0, 1, 0, 0, // counts
      value); // parameter
}
References v8::internal::compiler::Operator::kPure, v8::internal::Zone::New(), v8::internal::value, and zone().
FrameState()
const Operator * v8::internal::compiler::CommonOperatorBuilder::FrameState (BytecodeOffset bailout_id, OutputFrameStateCombine state_combine, const FrameStateFunctionInfo * function_info)
Definition at line 1602 of file common-operator.cc.
                                                 {
  FrameStateInfo state_info(bailout_id, state_combine, function_info);
  return zone()->New<Operator1<FrameStateInfo>>(// --
      IrOpcode::kFrameState, Operator::kPure, // opcode
      "FrameState", // name
      5, 0, 0, 1, 0, 0, // counts
      state_info); // parameter
}
References v8::internal::compiler::Operator::kPure, v8::internal::Zone::New(), and zone().
Referenced by v8::internal::compiler::BytecodeGraphBuilder::Environment::Checkpoint(), v8::internal::compiler::CloneFrameState(), v8::internal::compiler::JSInliner::CreateArtificialFrameState(), v8::internal::compiler::anonymous_namespace{frame-states.cc}::CreateBuiltinContinuationFrameStateCommon(), and v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::CreateConstructInvokeStubFrameState().
HeapConstant()
const Operator * v8::internal::compiler::CommonOperatorBuilder::HeapConstant (const Handle< HeapObject > & value)
Definition at line 1343 of file common-operator.cc.
                                     {
  return zone()->New<Operator1<IndirectHandle<HeapObject>>>(// --
      IrOpcode::kHeapConstant, Operator::kPure, // opcode
      "HeapConstant", // name
      0, 0, 0, 1, 0, 0, // counts
      value); // parameter
}
References v8::internal::compiler::Operator::kPure, v8::internal::Zone::New(), v8::internal::value, and zone().
Referenced by v8::internal::compiler::BasicBlockInstrumentor::Instrument().
IfDefault()
const Operator * v8::internal::compiler::CommonOperatorBuilder::IfDefault (BranchHint hint = BranchHint::kNone)
Definition at line 1175 of file common-operator.cc.
                                                                {
  return zone()->New<Operator1<BranchHint>>(// --
      IrOpcode::kIfDefault, Operator::kKontrol, // opcode
      "IfDefault", // name
      0, 0, 1, 0, 0, 1, // counts
      hint); // parameter
}
References v8::internal::compiler::Operator::kKontrol, v8::internal::Zone::New(), and zone().
IfException()
const Operator* v8::internal::compiler::CommonOperatorBuilder::IfException ()
Referenced by v8::internal::compiler::CodeAssembler::HandleException().
IfFalse()
const Operator* v8::internal::compiler::CommonOperatorBuilder::IfFalse ()
Referenced by v8::internal::compiler::Diamond::Diamond(), and v8::internal::compiler::RawMachineAssembler::OptimizeControlFlow().
IfSuccess()
const Operator* v8::internal::compiler::CommonOperatorBuilder::IfSuccess ()
IfTrue()
const Operator* v8::internal::compiler::CommonOperatorBuilder::IfTrue ()
Referenced by v8::internal::compiler::Diamond::Diamond(), and v8::internal::compiler::RawMachineAssembler::OptimizeControlFlow().
IfValue()
const Operator * v8::internal::compiler::CommonOperatorBuilder::IfValue (int32_t value, int32_t order = 0, BranchHint hint = BranchHint::kNone)
Definition at line 1165 of file common-operator.cc.
                                                                {
  return zone()->New<Operator1<IfValueParameters>>(// --
      IrOpcode::kIfValue, Operator::kKontrol, // opcode
      "IfValue", // name
      0, 0, 1, 0, 0, 1, // counts
      IfValueParameters(index, comparison_order, hint)); // parameter
}
References v8::internal::index, v8::internal::compiler::Operator::kKontrol, v8::internal::Zone::New(), and zone().
InductionVariablePhi()
const Operator * v8::internal::compiler::CommonOperatorBuilder::InductionVariablePhi (int value_input_count)
Definition at line 1475 of file common-operator.cc.
                                                                           {
  DCHECK_LE(4, input_count); // There must be always the entry, backedge,
                              // increment and at least one bound.
  switch (input_count) {
#define CACHED_INDUCTION_VARIABLE_PHI(input_count) \
  case input_count: \
    return &cache_.kInductionVariablePhi##input_count##Operator;
    CACHED_INDUCTION_VARIABLE_PHI_LIST(CACHED_INDUCTION_VARIABLE_PHI)
#undef CACHED_INDUCTION_VARIABLE_PHI
    default:
      break;
  }
  // Uncached.
  return zone()->New<Operator>(// --
      IrOpcode::kInductionVariablePhi, Operator::kPure, // opcode
      "InductionVariablePhi", // name
      input_count, 0, 1, 1, 0, 0); // counts
}
References CACHED_INDUCTION_VARIABLE_PHI, CACHED_INDUCTION_VARIABLE_PHI_LIST, DCHECK_LE, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::Operator::kPure, v8::internal::Zone::New(), and zone().
Int32Constant()
const Operator * v8::internal::compiler::CommonOperatorBuilder::Int32Constant (int32_t value)
Definition at line 1274 of file common-operator.cc.
                                                                  {
  return zone()->New<Operator1<int32_t>>(// --
      IrOpcode::kInt32Constant, Operator::kPure, // opcode
      "Int32Constant", // name
      0, 0, 0, 1, 0, 0, // counts
      value); // parameter
}
References v8::internal::compiler::Operator::kPure, v8::internal::Zone::New(), v8::internal::value, and zone().
Referenced by v8::internal::compiler::BasicBlockInstrumentor::Instrument(), v8::internal::compiler::IntPtrConstant(), and v8::internal::compiler::UnrollLoop().
Int64Constant()
const Operator * v8::internal::compiler::CommonOperatorBuilder::Int64Constant (int64_t value)
Definition at line 1283 of file common-operator.cc.
                                                                  {
  return zone()->New<Operator1<int64_t>>(// --
      IrOpcode::kInt64Constant, Operator::kPure, // opcode
      "Int64Constant", // name
      0, 0, 0, 1, 0, 0, // counts
      value); // parameter
}
References v8::internal::compiler::Operator::kPure, v8::internal::Zone::New(), v8::internal::value, and zone().
Referenced by v8::internal::compiler::IntPtrConstant().
Loop()
const Operator * v8::internal::compiler::CommonOperatorBuilder::Loop (int control_input_count)
Definition at line 1191 of file common-operator.cc.
                                                                   {
  switch (control_input_count) {
#define CACHED_LOOP(input_count) \
  case input_count: \
    return &cache_.kLoop##input_count##Operator;
    CACHED_LOOP_LIST(CACHED_LOOP)
#undef CACHED_LOOP
    default:
      break;
  }
  // Uncached.
  return zone()->New<Operator>(// --
      IrOpcode::kLoop, Operator::kKontrol, // opcode
      "Loop", // name
      0, 0, control_input_count, 0, 0, 1); // counts
}
References CACHED_LOOP, CACHED_LOOP_LIST, v8::internal::compiler::Operator::kKontrol, v8::internal::Zone::New(), and zone().
Referenced by v8::internal::compiler::SimplifyTFLoops::Reduce(), and ResizeMergeOrPhi().
LoopExit()
const Operator* v8::internal::compiler::CommonOperatorBuilder::LoopExit ()
LoopExitEffect()
const Operator* v8::internal::compiler::CommonOperatorBuilder::LoopExitEffect ()
LoopExitValue()
const Operator * v8::internal::compiler::CommonOperatorBuilder::LoopExitValue (MachineRepresentation rep)
Definition at line 1226 of file common-operator.cc.
                               {
  switch (rep) {
#define CACHED_LOOP_EXIT_VALUE(kRep) \
  case MachineRepresentation::kRep: \
    return &cache_.kLoopExitValue##kRep##Operator;
    CACHED_LOOP_EXIT_VALUE_LIST(CACHED_LOOP_EXIT_VALUE)
#undef CACHED_LOOP_EXIT_VALUE
    default:
      // Uncached.
      return zone()->New<Operator1<MachineRepresentation>>(// --
          IrOpcode::kLoopExitValue, Operator::kPure, // opcode
          "LoopExitValue", // name
          1, 0, 1, 1, 0, 0, // counts
          rep); // parameter
  }
}
References CACHED_LOOP_EXIT_VALUE, CACHED_LOOP_EXIT_VALUE_LIST, v8::internal::compiler::Operator::kPure, v8::internal::Zone::New(), and zone().
Referenced by v8::internal::compiler::Revectorizer::VectorizeTree().
Merge()
const Operator * v8::internal::compiler::CommonOperatorBuilder::Merge (int control_input_count)
Definition at line 1209 of file common-operator.cc.
                                                                    {
  switch (control_input_count) {
#define CACHED_MERGE(input_count) \
  case input_count: \
    return &cache_.kMerge##input_count##Operator;
    CACHED_MERGE_LIST(CACHED_MERGE)
#undef CACHED_MERGE
    default:
      break;
  }
  // Uncached.
  return zone()->New<Operator>(// --
      IrOpcode::kMerge, Operator::kKontrol, // opcode
      "Merge", // name
      0, 0, control_input_count, 0, 0, 1); // counts
}
References CACHED_MERGE, CACHED_MERGE_LIST, v8::internal::compiler::Operator::kKontrol, v8::internal::Zone::New(), and zone().
Referenced by v8::internal::compiler::Diamond::Diamond(), v8::internal::compiler::SimplifiedLowering::Int32Div(), v8::internal::compiler::SimplifiedLowering::Int32Mod(), v8::internal::compiler::LoopPeeler::Peel(), v8::internal::compiler::SimplifyTFLoops::Reduce(), ResizeMergeOrPhi(), v8::internal::compiler::SimplifiedLowering::Uint32Mod(), and v8::internal::compiler::UnrollLoop().
NumberConstant()
const Operator * v8::internal::compiler::CommonOperatorBuilder::NumberConstant (double value)
Definition at line 1327 of file common-operator.cc.
                                                                  {
  return zone()->New<Operator1<double>>(// --
      IrOpcode::kNumberConstant, Operator::kPure, // opcode
      "NumberConstant", // name
      0, 0, 0, 1, 0, 0, // counts
      value); // parameter
}
References v8::internal::compiler::Operator::kPure, v8::internal::Zone::New(), v8::internal::value, and zone().
ObjectId()
const Operator * v8::internal::compiler::CommonOperatorBuilder::ObjectId (uint32_t object_id)
Definition at line 1400 of file common-operator.cc.
                                                                  {
  return zone()->New<Operator1<uint32_t>>(// --
      IrOpcode::kObjectId, Operator::kPure, // opcode
      "ObjectId", // name
      0, 0, 0, 1, 0, 0, // counts
      object_id); // parameter
}
References v8::internal::compiler::Operator::kPure, v8::internal::Zone::New(), and zone().
ObjectState()
const Operator * v8::internal::compiler::CommonOperatorBuilder::ObjectState (uint32_t object_id, int pointer_slots)
Definition at line 1566 of file common-operator.cc.
                                                                      {
  return zone()->New<Operator1<ObjectStateInfo>>(// --
      IrOpcode::kObjectState, Operator::kPure, // opcode
      "ObjectState", // name
      pointer_slots, 0, 0, 1, 0, 0, // counts
      ObjectStateInfo{object_id, pointer_slots}); // parameter
}
References v8::internal::compiler::Operator::kPure, v8::internal::Zone::New(), and zone().
operator=()
CommonOperatorBuilder& v8::internal::compiler::CommonOperatorBuilder::operator= (const CommonOperatorBuilder &) [delete]
OsrValue()
const Operator * v8::internal::compiler::CommonOperatorBuilder::OsrValue (int index)
Definition at line 1266 of file common-operator.cc.
                                                         {
  return zone()->New<Operator1<int>>(// --
      IrOpcode::kOsrValue, Operator::kNoProperties, // opcode
      "OsrValue", // name
      0, 0, 1, 1, 0, 0, // counts
      index); // parameter
}
References v8::internal::index, v8::internal::compiler::Operator::kNoProperties, v8::internal::Zone::New(), and zone().
Parameter()
const Operator * v8::internal::compiler::CommonOperatorBuilder::Parameter (int index, const char * debug_name = nullptr)
Definition at line 1245 of file common-operator.cc.
                                                                         {
  if (!debug_name) {
    switch (index) {
#define CACHED_PARAMETER(index) \
  case index: \
    return &cache_.kParameter##index##Operator;
      CACHED_PARAMETER_LIST(CACHED_PARAMETER)
#undef CACHED_PARAMETER
      default:
        break;
    }
  }
  // Uncached.
  return zone()->New<Operator1<ParameterInfo>>(// --
      IrOpcode::kParameter, Operator::kPure, // opcode
      "Parameter", // name
      1, 0, 0, 1, 0, 0, // counts
      ParameterInfo(index, debug_name)); // parameter info
}
References CACHED_PARAMETER, CACHED_PARAMETER_LIST, v8::internal::index, v8::internal::compiler::Operator::kPure, v8::internal::Zone::New(), and zone().
Phi()
const Operator * v8::internal::compiler::CommonOperatorBuilder::Phi (MachineRepresentation representation, int value_input_count)
Definition at line 1418 of file common-operator.cc.
                                                                  {
  DCHECK_LT(0, value_input_count); // Disallow empty phis.
#define CACHED_PHI(kRep, kValueInputCount) \
  if (MachineRepresentation::kRep == rep && \
      kValueInputCount == value_input_count) { \
    return &cache_.kPhi##kRep##kValueInputCount##Operator; \
  }
  CACHED_PHI_LIST(CACHED_PHI)
#undef CACHED_PHI
  // Uncached.
  return zone()->New<Operator1<MachineRepresentation>>(// --
      IrOpcode::kPhi, Operator::kPure, // opcode
      "Phi", // name
      value_input_count, 0, 1, 1, 0, 0, // counts
      rep); // parameter
}
References CACHED_PHI, CACHED_PHI_LIST, DCHECK_LT, v8::internal::compiler::Operator::kPure, v8::internal::Zone::New(), and zone().
Referenced by v8::internal::compiler::SimplifiedLowering::Int32Div(), v8::internal::compiler::SimplifiedLowering::Int32Mod(), v8::internal::compiler::VariableTracker::MergeInputs(), v8::internal::compiler::LoopPeeler::Peel(), v8::internal::compiler::Diamond::Phi(), v8::internal::compiler::SimplifyTFLoops::Reduce(), ResizeMergeOrPhi(), v8::internal::compiler::SimplifiedLowering::Uint32Mod(), v8::internal::compiler::UnrollLoop(), v8::internal::compiler::Revectorizer::VectorizeTree(), and v8::internal::compiler::RepresentationSelector::VisitPhi().
Plug()
const Operator* v8::internal::compiler::CommonOperatorBuilder::Plug ()
PointerConstant()
const Operator * v8::internal::compiler::CommonOperatorBuilder::PointerConstant (intptr_t value)
Definition at line 1335 of file common-operator.cc.
                                                                     {
  return zone()->New<Operator1<intptr_t>>(// --
      IrOpcode::kPointerConstant, Operator::kPure, // opcode
      "PointerConstant", // name
      0, 0, 0, 1, 0, 0, // counts
      value); // parameter
}
References v8::internal::compiler::Operator::kPure, v8::internal::Zone::New(), v8::internal::value, and zone().
Projection()
const Operator * v8::internal::compiler::CommonOperatorBuilder::Projection (size_t index)
Definition at line 1657 of file common-operator.cc.
                                                              {
  switch (index) {
#define CACHED_PROJECTION(index) \
  case index: \
    return &cache_.kProjection##index##Operator;
    CACHED_PROJECTION_LIST(CACHED_PROJECTION)
#undef CACHED_PROJECTION
    default:
      break;
  }
  // Uncached.
  return zone()->New<Operator1<size_t>>(// --
      IrOpcode::kProjection, // opcode
      Operator::kPure, // flags
      "Projection", // name
      1, 0, 1, 1, 0, 0, // counts
      index); // parameter
}
References CACHED_PROJECTION, CACHED_PROJECTION_LIST, v8::internal::index, v8::internal::compiler::Operator::kPure, v8::internal::Zone::New(), and zone().
RelocatableInt32Constant()
const Operator * v8::internal::compiler::CommonOperatorBuilder::RelocatableInt32Constant (int32_t value, RelocInfo::Mode rmode)
Definition at line 1382 of file common-operator.cc.
                                        {
  return zone()->New<Operator1<RelocatablePtrConstantInfo>>(// --
      IrOpcode::kRelocatableInt32Constant, Operator::kPure, // opcode
      "RelocatableInt32Constant", // name
      0, 0, 0, 1, 0, 0, // counts
      RelocatablePtrConstantInfo(value, rmode)); // parameter
}
References v8::internal::compiler::Operator::kPure, v8::internal::Zone::New(), v8::internal::value, and zone().
RelocatableInt64Constant()
const Operator * v8::internal::compiler::CommonOperatorBuilder::RelocatableInt64Constant (int64_t value, RelocInfo::Mode rmode)
Definition at line 1391 of file common-operator.cc.
                                        {
  return zone()->New<Operator1<RelocatablePtrConstantInfo>>(// --
      IrOpcode::kRelocatableInt64Constant, Operator::kPure, // opcode
      "RelocatableInt64Constant", // name
      0, 0, 0, 1, 0, 0, // counts
      RelocatablePtrConstantInfo(value, rmode)); // parameter
}
References v8::internal::compiler::Operator::kPure, v8::internal::Zone::New(), v8::internal::value, and zone().
ResizeMergeOrPhi()
const Operator * v8::internal::compiler::CommonOperatorBuilder::ResizeMergeOrPhi (const Operator * op, int size)
Definition at line 1677 of file common-operator.cc.
                                                                  {
  if (op->opcode() == IrOpcode::kPhi) {
    return Phi(PhiRepresentationOf(op), size);
  } else if (op->opcode() == IrOpcode::kEffectPhi) {
    return EffectPhi(size);
  } else if (op->opcode() == IrOpcode::kMerge) {
    return Merge(size);
  } else if (op->opcode() == IrOpcode::kLoop) {
    return Loop(size);
  } else {
    UNREACHABLE();
  }
}
References EffectPhi(), Loop(), Merge(), v8::internal::compiler::Operator::opcode(), Phi(), v8::internal::compiler::PhiRepresentationOf(), size(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::RawMachineAssembler::AppendPhiInput(), v8::internal::compiler::LoopPeeler::Peel(), v8::internal::compiler::DeadCodeElimination::TrimMergeOrPhi(), and v8::internal::compiler::UnrollLoop().
Retain()
const Operator* v8::internal::compiler::CommonOperatorBuilder::Retain ()
Return()
const Operator * v8::internal::compiler::CommonOperatorBuilder::Return (int value_input_count = 1)
Definition at line 1000 of file common-operator.cc.
                                                                   {
  switch (value_input_count) {
#define CACHED_RETURN(input_count) \
  case input_count: \
    return &cache_.kReturn##input_count##Operator;
    CACHED_RETURN_LIST(CACHED_RETURN)
#undef CACHED_RETURN
    default:
      break;
  }
  // Uncached.
  return zone()->New<Operator>(//--
      IrOpcode::kReturn, Operator::kNoThrow, // opcode
      "Return", // name
      value_input_count + 1, 1, 1, 0, 0, 1); // counts
}
References CACHED_RETURN, CACHED_RETURN_LIST, v8::internal::compiler::Operator::kNoThrow, v8::internal::Zone::New(), and zone().
Select()
const Operator * v8::internal::compiler::CommonOperatorBuilder::Select (MachineRepresentation rep, BranchHint hint = BranchHint::kNone, BranchSemantics semantics = BranchSemantics::kUnspecified)
Definition at line 1408 of file common-operator.cc.
                                                                         {
  return zone()->New<Operator1<SelectParameters>>(// --
      IrOpcode::kSelect, Operator::kPure, // opcode
      "Select", // name
      3, 0, 0, 1, 0, 0, // counts
      SelectParameters(rep, hint, semantics)); // parameter
}
References v8::internal::compiler::Operator::kPure, v8::internal::Zone::New(), and zone().
Referenced by v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::LowerCompareMapsWithoutLoad(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode(), and v8::internal::compiler::RepresentationSelector::VisitSelect().
SLVerifierHint()
const Operator * v8::internal::compiler::CommonOperatorBuilder::SLVerifierHint (const Operator * semantics, const std::optional< Type > & override_output_type)
Definition at line 1023 of file common-operator.cc.
                                                   {
  return zone()->New<Operator1<SLVerifierHintParameters>>(
      IrOpcode::kSLVerifierHint, Operator::kNoProperties, "SLVerifierHint", 1,
      0, 0, 1, 0, 0, SLVerifierHintParameters(semantics, override_output_type));
}
References v8::internal::compiler::Operator::kNoProperties, v8::internal::Zone::New(), and zone().
Start()
const Operator * v8::internal::compiler::CommonOperatorBuilder::Start (int value_output_count)
Definition at line 1183 of file common-operator.cc.
                                                                   {
  return zone()->New<Operator>(// --
      IrOpcode::kStart, Operator::kFoldable | Operator::kNoThrow, // opcode
      "Start", // name
      0, 0, 0, value_output_count, 1, 1); // counts
}
References v8::internal::compiler::Operator::kFoldable, v8::internal::compiler::Operator::kNoThrow, v8::kStart, v8::internal::Zone::New(), and zone().
Referenced by v8::internal::compiler::RawMachineAssembler::RawMachineAssembler(), and v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::WasmIntoJSInlinerImpl().
StateValues()
const Operator * v8::internal::compiler::CommonOperatorBuilder::StateValues (int arguments, SparseInputMask bitmask)
Definition at line 1505 of file common-operator.cc.
                                                                            {
  if (bitmask.IsDense()) {
    switch (arguments) {
#define CACHED_STATE_VALUES(arguments) \
  case arguments: \
    return &cache_.kStateValues##arguments##Operator;
      CACHED_STATE_VALUES_LIST(CACHED_STATE_VALUES)
#undef CACHED_STATE_VALUES
      default:
        break;
    }
  }
#if DEBUG
  DCHECK(bitmask.IsDense() || bitmask.CountReal() == arguments);
#endif
  // Uncached.
  return zone()->New<Operator1<SparseInputMask>>(// --
      IrOpcode::kStateValues, Operator::kPure, // opcode
      "StateValues", // name
      arguments, 0, 0, 1, 0, 0, // counts
      bitmask); // parameter
}
References CACHED_STATE_VALUES, CACHED_STATE_VALUES_LIST, v8::internal::compiler::SparseInputMask::CountReal(), v8::internal::DCHECK(), v8::internal::compiler::SparseInputMask::IsDense(), v8::internal::compiler::Operator::kPure, v8::internal::Zone::New(), and zone().
Referenced by v8::internal::compiler::JSInliner::CreateArtificialFrameState(), v8::internal::compiler::anonymous_namespace{frame-states.cc}::CreateBuiltinContinuationFrameStateCommon(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::CreateConstructInvokeStubFrameState(), and v8::internal::compiler::BytecodeGraphBuilder::Environment::UpdateStateValues().
StaticAssert()
const Operator * v8::internal::compiler::CommonOperatorBuilder::StaticAssert (const char * source)
Definition at line 1017 of file common-operator.cc.
                                                                      {
  return zone()->New<Operator1<const char*>>(
      IrOpcode::kStaticAssert, Operator::kFoldable, "StaticAssert", 1, 1, 0, 0,
      1, 0, source);
}
References v8::internal::compiler::Operator::kFoldable, v8::internal::Zone::New(), and zone().
Switch()
const Operator * v8::internal::compiler::CommonOperatorBuilder::Switch (size_t control_output_count)
Definition at line 1158 of file common-operator.cc.
                                                                         {
  return zone()->New<Operator>(// --
      IrOpcode::kSwitch, Operator::kKontrol, // opcode
      "Switch", // name
      1, 0, 1, 0, 0, control_output_count); // counts
}
References v8::internal::compiler::Operator::kKontrol, v8::internal::wasm::kSwitch, v8::internal::Zone::New(), and zone().
TaggedIndexConstant()
const Operator * v8::internal::compiler::CommonOperatorBuilder::TaggedIndexConstant (int32_t value)
Definition at line 1291 of file common-operator.cc.
                                                                        {
  return zone()->New<Operator1<int32_t>>(// --
      IrOpcode::kTaggedIndexConstant, Operator::kPure, // opcode
      "TaggedIndexConstant", // name
      0, 0, 0, 1, 0, 0, // counts
      value); // parameter
}
References v8::internal::compiler::Operator::kPure, v8::internal::Zone::New(), v8::internal::value, and zone().
TailCall()
const Operator * v8::internal::compiler::CommonOperatorBuilder::TailCall (const CallDescriptor * call_descriptor)
Definition at line 1637 of file common-operator.cc.
                                           {
  class TailCallOperator final : public Operator1<const CallDescriptor*> {
   public:
    explicit TailCallOperator(const CallDescriptor* call_descriptor)
        : Operator1<const CallDescriptor*>(
              IrOpcode::kTailCall,
              call_descriptor->properties() | Operator::kNoThrow, "TailCall",
              call_descriptor->InputCount() +
                  call_descriptor->FrameStateCount(),
              1, 1, 0, 0, 1, call_descriptor) {}
    void PrintParameter(std::ostream& os,
                        PrintVerbosity verbose) const override {
      os << "[" << *parameter() << "]";
    }
  };
  return zone()->New<TailCallOperator>(call_descriptor);
}
References v8::internal::compiler::CallDescriptor::FrameStateCount(), v8::internal::compiler::CallDescriptor::InputCount(), v8::internal::compiler::Operator::kNoThrow, v8::internal::wasm::kTailCall, v8::internal::Zone::New(), v8::internal::compiler::CallDescriptor::properties(), and zone().
Terminate()
const Operator* v8::internal::compiler::CommonOperatorBuilder::Terminate ()
Throw()
const Operator* v8::internal::compiler::CommonOperatorBuilder::Throw ()
Referenced by v8::internal::compiler::DeadCodeElimination::ReduceEffectPhi().
TrustedHeapConstant()
const Operator * v8::internal::compiler::CommonOperatorBuilder::TrustedHeapConstant (const Handle< HeapObject > & value)
Definition at line 1361 of file common-operator.cc.
                                     {
  return zone()->New<Operator1<IndirectHandle<HeapObject>>>(// --
      IrOpcode::kTrustedHeapConstant, Operator::kPure, // opcode
      "TrustedHeapConstant", // name
      0, 0, 0, 1, 0, 0, // counts
      value); // parameter
}
References v8::internal::compiler::Operator::kPure, v8::internal::Zone::New(), v8::internal::value, and zone().
TypedObjectState()
const Operator * v8::internal::compiler::CommonOperatorBuilder::TypedObjectState (uint32_t object_id, const ZoneVector< MachineType > * types)
Definition at line 1575 of file common-operator.cc.
                                                              {
  return zone()->New<Operator1<TypedObjectStateInfo>>(// --
      IrOpcode::kTypedObjectState, Operator::kPure, // opcode
      "TypedObjectState", // name
      static_cast<int>(types->size()), 0, 0, 1, 0, 0, // counts
      TypedObjectStateInfo(object_id, types)); // parameter
}
References v8::internal::compiler::Operator::kPure, v8::internal::Zone::New(), v8::internal::ZoneVector< T >::size(), and zone().
TypedStateValues()
const Operator * v8::internal::compiler::CommonOperatorBuilder::TypedStateValues (const ZoneVector< MachineType > * types, SparseInputMask bitmask)
Definition at line 1531 of file common-operator.cc.
                                                                   {
#if DEBUG
  DCHECK(bitmask.IsDense() ||
         bitmask.CountReal() == static_cast<int>(types->size()));
#endif
  return zone()->New<Operator1<TypedStateValueInfo>>(// --
      IrOpcode::kTypedStateValues, Operator::kPure, // opcode
      "TypedStateValues", // name
      static_cast<int>(types->size()), 0, 0, 1, 0, 0, // counts
      TypedStateValueInfo(types, bitmask)); // parameters
}
References v8::internal::compiler::SparseInputMask::CountReal(), v8::internal::DCHECK(), v8::internal::compiler::SparseInputMask::IsDense(), v8::internal::compiler::Operator::kPure, v8::internal::Zone::New(), v8::internal::ZoneVector< T >::size(), and zone().
TypeGuard()
const Operator * v8::internal::compiler::CommonOperatorBuilder::TypeGuard (Type type)
Definition at line 1436 of file common-operator.cc.
                                                          {
  return zone()->New<Operator1<Type>>(// --
      IrOpcode::kTypeGuard, Operator::kPure, // opcode
      "TypeGuard", // name
      1, 1, 1, 1, 1, 0, // counts
      type); // parameter
}
References v8::internal::compiler::Operator::kPure, v8::internal::Zone::New(), v8::internal::tracing::type, and zone().
Unreachable()
const Operator* v8::internal::compiler::CommonOperatorBuilder::Unreachable ()
zone()
Zone* v8::internal::compiler::CommonOperatorBuilder::zone () const [inline], [private]
Definition at line 679 of file common-operator.h.
{ return zone_; }
Referenced by ArgumentsElementsState(), ArgumentsLengthState(), Assert(), Call(), Chained(), CompressedHeapConstant(), CreateFrameStateFunctionInfo(), DeadValue(), Deoptimize(), DeoptimizeIf(), DeoptimizeUnless(), EffectPhi(), End(), EnterMachineGraph(), ExitMachineGraph(), ExternalConstant(), Float32Constant(), Float64Constant(), FrameState(), HeapConstant(), IfDefault(), IfValue(), InductionVariablePhi(), Int32Constant(), Int64Constant(), Loop(), LoopExitValue(), Merge(), NumberConstant(), ObjectId(), ObjectState(), OsrValue(), Parameter(), Phi(), PointerConstant(), Projection(), RelocatableInt32Constant(), RelocatableInt64Constant(), Return(), Select(), SLVerifierHint(), Start(), StateValues(), StaticAssert(), Switch(), TaggedIndexConstant(), TailCall(), TrustedHeapConstant(), TypedObjectState(), TypedStateValues(), and TypeGuard().
Member Data Documentation
cache_
const CommonOperatorGlobalCache& v8::internal::compiler::CommonOperatorBuilder::cache_ [private]
Definition at line 681 of file common-operator.h.
Referenced by BeginRegion().
zone_
Zone* const v8::internal::compiler::CommonOperatorBuilder::zone_ [private]
Definition at line 682 of file common-operator.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/common-operator.h
/mnt/V8SourceCode/src/compiler/common-operator.cc