v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer Class Reference
#include <instruction-selection-phase.h>
Classes
struct BlockData
struct LoopInfo
struct SpecialRPOStackFrame
Public Types
using Backedge = std::pair< const Block *, size_t >
Public Member Functions
TurboshaftSpecialRPONumberer (const Graph &graph, Zone *zone)
ZoneVector< uint32_t > ComputeSpecialRPO ()
Static Public Attributes
static const int kBlockOnStack = -2
static const int kBlockVisited1 = -3
static const int kBlockVisited2 = -4
static const int kBlockUnvisited = -1
Private Member Functions
void ComputeLoopInfo (size_t num_loops, ZoneVector< Backedge > &backedges)
ZoneVector< uint32_t > ComputeBlockPermutation (const Block *entry)
int32_t rpo_number (const Block *block) const
void set_rpo_number (const Block *block, int32_t rpo_number)
bool has_loop_number (const Block *block) const
size_t loop_number (const Block *block) const
void set_loop_number (const Block *block, size_t loop_number)
const Block * PushFront (const Block *head, const Block *block)
Zone * zone () const
Private Attributes
const Graph * graph_
FixedBlockSidetable< BlockData > block_data_
ZoneVector< LoopInfo > loops_
Detailed Description
Definition at line 31 of file instruction-selection-phase.h.
Member Typedef Documentation
Backedge
using v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::Backedge = std::pair<const Block*, size_t>
Definition at line 39 of file instruction-selection-phase.h.
Constructor & Destructor Documentation
TurboshaftSpecialRPONumberer()
v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::TurboshaftSpecialRPONumberer (const Graph & graph, Zone * zone) [inline]
Definition at line 71 of file instruction-selection-phase.h.
      : graph_(&graph), block_data_(graph.block_count(), zone), loops_(zone) {}
Member Function Documentation
ComputeBlockPermutation()
ZoneVector< uint32_t > v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::ComputeBlockPermutation (const Block * entry) [private]
Definition at line 246 of file instruction-selection-phase.cc.
                        {
  ZoneVector<uint32_t> result(graph_->block_count(), zone());
  size_t i = 0;
  for (const Block* b = entry; b; b = block_data_[b->index()].rpo_next) {
    result[i++] = b->index().id();
  }
  DCHECK_EQ(i, graph_->block_count());
  return result;
}
References v8::internal::compiler::turboshaft::Graph::block_count(), block_data_, DCHECK_EQ, graph_, v8::base::internal::result, and zone().
Referenced by ComputeSpecialRPO().
ComputeLoopInfo()
void v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::ComputeLoopInfo (size_t num_loops, ZoneVector< Backedge > & backedges) [private]
Definition at line 204 of file instruction-selection-phase.cc.
                                                       {
  ZoneVector<const Block*> stack(zone());
  // Extend loop information vector.
  loops_.resize(num_loops, LoopInfo{});
  // Compute loop membership starting from backedges.
  // O(max(loop_depth) * |loop|)
  for (auto [backedge, header_index] : backedges) {
    const Block* header = SuccessorBlocks(*backedge, *graph_)[header_index];
    DCHECK(header->IsLoop());
    size_t loop_num = loop_number(header);
    DCHECK_NULL(loops_[loop_num].header);
    loops_[loop_num].header = header;
    loops_[loop_num].members = zone()->New<SparseBitVector>(zone());
    if (backedge != header) {
      // As long as the header doesn't have a backedge to itself,
      // Push the member onto the queue and process its predecessors.
      DCHECK(!loops_[loop_num].members->Contains(backedge->index().id()));
      loops_[loop_num].members->Add(backedge->index().id());
      stack.push_back(backedge);
    }
    // Propagate loop membership backwards. All predecessors of M up to the
    // loop header H are members of the loop too. O(|blocks between M and H|).
    while (!stack.empty()) {
      const Block* block = stack.back();
      stack.pop_back();
      for (const Block* pred : block->PredecessorsIterable()) {
        if (pred != header) {
          if (!loops_[loop_num].members->Contains(pred->index().id())) {
            loops_[loop_num].members->Add(pred->index().id());
            stack.push_back(pred);
          }
        }
      }
    }
  }
}
References v8::internal::DCHECK(), DCHECK_NULL, graph_, v8::internal::compiler::turboshaft::Block::IsLoop(), loop_number(), loops_, v8::internal::Zone::New(), v8::internal::compiler::turboshaft::Block::PredecessorsIterable(), v8::internal::stack, v8::internal::compiler::turboshaft::SuccessorBlocks(), and zone().
Referenced by ComputeSpecialRPO().
ComputeSpecialRPO()
ZoneVector< uint32_t > v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::ComputeSpecialRPO ()
Definition at line 53 of file instruction-selection-phase.cc.
                                                                     {
  ZoneVector<SpecialRPOStackFrame> stack(zone());
  ZoneVector<Backedge> backedges(zone());
  // Determined empirically on a large Wasm module. Since they are allocated
  // only once per function compilation, the memory usage is not critical.
  stack.reserve(64);
  backedges.reserve(32);
  size_t num_loops = 0;
  auto Push = [&](const Block* block) {
    auto succs = SuccessorBlocks(*block, *graph_);
    stack.emplace_back(block, 0, std::move(succs));
    set_rpo_number(block, kBlockOnStack);
  };
  const Block* entry = &graph_->StartBlock();
  // Find correct insertion point within existing order.
  const Block* order = nullptr;
  Push(&graph_->StartBlock());
  while (!stack.empty()) {
    SpecialRPOStackFrame& frame = stack.back();
    if (frame.index < frame.successors.size()) {
      // Process the next successor.
      const Block* succ = frame.successors[frame.index++];
      if (rpo_number(succ) == kBlockVisited1) continue;
      if (rpo_number(succ) == kBlockOnStack) {
        // The successor is on the stack, so this is a backedge (cycle).
        DCHECK_EQ(frame.index - 1, 0);
        backedges.emplace_back(frame.block, frame.index - 1);
        // Assign a new loop number to the header.
        DCHECK(!has_loop_number(succ));
        set_loop_number(succ, num_loops++);
      } else {
        // Push the successor onto the stack.
        DCHECK_EQ(rpo_number(succ), kBlockUnvisited);
        Push(succ);
      }
    } else {
      // Finished with all successors; pop the stack and add the block.
      order = PushFront(order, frame.block);
      set_rpo_number(frame.block, kBlockVisited1);
      stack.pop_back();
    }
  }
  // If no loops were encountered, then the order we computed was correct.
  if (num_loops == 0) return ComputeBlockPermutation(entry);
  // Otherwise, compute the loop information from the backedges in order
  // to perform a traversal that groups loop bodies together.
  ComputeLoopInfo(num_loops, backedges);
  // Initialize the "loop stack". We assume that the entry cannot be a loop
  // header.
  CHECK(!has_loop_number(entry));
  LoopInfo* loop = nullptr;
  order = nullptr;
  // Perform an iterative post-order traversal, visiting loop bodies before
  // edges that lead out of loops. Visits each block once, but linking loop
  // sections together is linear in the loop size, so overall is
  // O(|B| + max(loop_depth) * max(|loop|))
  DCHECK(stack.empty());
  Push(&graph_->StartBlock());
  while (!stack.empty()) {
    SpecialRPOStackFrame& frame = stack.back();
    const Block* block = frame.block;
    const Block* succ = nullptr;
    if (frame.index < frame.successors.size()) {
      // Process the next normal successor.
      succ = frame.successors[frame.index++];
    } else if (has_loop_number(block)) {
      // Process additional outgoing edges from the loop header.
      if (rpo_number(block) == kBlockOnStack) {
        // Finish the loop body the first time the header is left on the
        // stack.
        DCHECK_NOT_NULL(loop);
        DCHECK_EQ(loop->header, block);
        loop->start = PushFront(order, block);
        order = loop->end;
        set_rpo_number(block, kBlockVisited2);
        // Pop the loop stack and continue visiting outgoing edges within
        // the context of the outer loop, if any.
        loop = loop->prev;
        // We leave the loop header on the stack; the rest of this iteration
        // and later iterations will go through its outgoing edges list.
      }
      // Use the next outgoing edge if there are any.
      size_t outgoing_index = frame.index - frame.successors.size();
      LoopInfo* info = &loops_[loop_number(block)];
      DCHECK_NE(loop, info);
      if (block != entry && outgoing_index < info->outgoing.size()) {
        succ = info->outgoing[outgoing_index];
        ++frame.index;
      }
    }
    if (succ != nullptr) {
      // Process the next successor.
      if (rpo_number(succ) == kBlockOnStack) continue;
      if (rpo_number(succ) == kBlockVisited2) continue;
      DCHECK_EQ(kBlockVisited1, rpo_number(succ));
      if (loop != nullptr && !loop->members->Contains(succ->index().id())) {
        // The successor is not in the current loop or any nested loop.
        // Add it to the outgoing edges of this loop and visit it later.
        loop->AddOutgoing(zone(), succ);
      } else {
        // Push the successor onto the stack.
        Push(succ);
        if (has_loop_number(succ)) {
          // Push the inner loop onto the loop stack.
          DCHECK_LT(loop_number(succ), num_loops);
          LoopInfo* next = &loops_[loop_number(succ)];
          next->end = order;
          next->prev = loop;
          loop = next;
        }
      }
    } else {
      // Finish with all successors of the current block.
      if (has_loop_number(block)) {
        // If we are going to pop a loop header, then add its entire body.
        LoopInfo* info = &loops_[loop_number(block)];
        for (const Block* b = info->start; true;
             b = block_data_[b->index()].rpo_next) {
          if (block_data_[b->index()].rpo_next == info->end) {
            PushFront(order, b);
            info->end = order;
            break;
          }
        }
        order = info->start;
      } else {
        // Pop a single node off the stack and add it to the order.
        order = PushFront(order, block);
        set_rpo_number(block, kBlockVisited2);
      }
      stack.pop_back();
    }
  }
  return ComputeBlockPermutation(entry);
}
References v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::LoopInfo::AddOutgoing(), v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::SpecialRPOStackFrame::block, block_data_, CHECK, ComputeBlockPermutation(), ComputeLoopInfo(), v8::internal::SparseBitVector::Contains(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LT, DCHECK_NE, DCHECK_NOT_NULL, v8::internal::ZoneVector< T >::emplace_back(), v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::LoopInfo::end, graph_, has_loop_number(), v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::LoopInfo::header, v8::internal::compiler::turboshaft::BlockIndex::id(), v8::internal::compiler::turboshaft::Block::index(), v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::SpecialRPOStackFrame::index, kBlockOnStack, kBlockUnvisited, kBlockVisited1, kBlockVisited2, loop_number(), loops_, v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::LoopInfo::members, v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::LoopInfo::outgoing, v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::LoopInfo::prev, PushFront(), v8::internal::ZoneVector< T >::reserve(), rpo_number(), set_loop_number(), set_rpo_number(), v8::internal::stack, v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::LoopInfo::start, v8::internal::compiler::turboshaft::Graph::StartBlock(), v8::internal::compiler::turboshaft::SuccessorBlocks(), v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::SpecialRPOStackFrame::successors, and zone().
Referenced by v8::internal::compiler::turboshaft::SpecialRPOSchedulingPhase::Run().
has_loop_number()
bool v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::has_loop_number (const Block * block) const [inline], [private]
Definition at line 88 of file instruction-selection-phase.h.
                                                 {
    return block_data_[block->index()].loop_number != BlockData::kNoLoopNumber;
  }
References v8::internal::compiler::turboshaft::Block::index().
Referenced by ComputeSpecialRPO().
loop_number()
size_t v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::loop_number (const Block * block) const [inline], [private]
Definition at line 92 of file instruction-selection-phase.h.
                                               {
    DCHECK(has_loop_number(block));
    return block_data_[block->index()].loop_number;
  }
References v8::internal::DCHECK(), and v8::internal::compiler::turboshaft::Block::index().
Referenced by ComputeLoopInfo(), and ComputeSpecialRPO().
PushFront()
const Block* v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::PushFront (const Block * head, const Block * block) [inline], [private]
Definition at line 101 of file instruction-selection-phase.h.
                                                                {
    block_data_[block->index()].rpo_next = head;
    return block;
  }
References v8::internal::compiler::turboshaft::Block::index().
Referenced by ComputeSpecialRPO().
rpo_number()
int32_t v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::rpo_number (const Block * block) const [inline], [private]
Definition at line 80 of file instruction-selection-phase.h.
                                               {
    return block_data_[block->index()].rpo_number;
  }
References v8::internal::compiler::turboshaft::Block::index().
Referenced by ComputeSpecialRPO().
set_loop_number()
void v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::set_loop_number (const Block * block, size_t loop_number) [inline], [private]
Definition at line 97 of file instruction-selection-phase.h.
                                                               {
    block_data_[block->index()].loop_number = loop_number;
  }
References v8::internal::compiler::turboshaft::Block::index().
Referenced by ComputeSpecialRPO().
set_rpo_number()
void v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::set_rpo_number (const Block * block, int32_t rpo_number) [inline], [private]
Definition at line 84 of file instruction-selection-phase.h.
                                                              {
    block_data_[block->index()].rpo_number = rpo_number;
  }
References v8::internal::compiler::turboshaft::Block::index().
Referenced by ComputeSpecialRPO().
zone()
Zone* v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::zone () const [inline], [private]
Definition at line 106 of file instruction-selection-phase.h.
{ return loops_.zone(); }
Referenced by ComputeBlockPermutation(), ComputeLoopInfo(), and ComputeSpecialRPO().
Member Data Documentation
block_data_
FixedBlockSidetable<BlockData> v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::block_data_ [private]
Definition at line 109 of file instruction-selection-phase.h.
Referenced by ComputeBlockPermutation(), and ComputeSpecialRPO().
graph_
const Graph* v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::graph_ [private]
Definition at line 108 of file instruction-selection-phase.h.
Referenced by ComputeBlockPermutation(), ComputeLoopInfo(), and ComputeSpecialRPO().
kBlockOnStack
const int v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::kBlockOnStack = -2 [static]
Definition at line 34 of file instruction-selection-phase.h.
Referenced by ComputeSpecialRPO().
kBlockUnvisited
const int v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::kBlockUnvisited = -1 [static]
Definition at line 37 of file instruction-selection-phase.h.
Referenced by ComputeSpecialRPO().
kBlockVisited1
const int v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::kBlockVisited1 = -3 [static]
Definition at line 35 of file instruction-selection-phase.h.
Referenced by ComputeSpecialRPO().
kBlockVisited2
const int v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::kBlockVisited2 = -4 [static]
Definition at line 36 of file instruction-selection-phase.h.
Referenced by ComputeSpecialRPO().
loops_
ZoneVector<LoopInfo> v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::loops_ [private]
Definition at line 110 of file instruction-selection-phase.h.
Referenced by ComputeLoopInfo(), and ComputeSpecialRPO().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/instruction-selection-phase.h
/mnt/V8SourceCode/src/compiler/turboshaft/instruction-selection-phase.cc