v8::internal::TracedNode Class Reference
#include <traced-handles.h>
Public Types
using IndexType = uint8_t
Public Member Functions
TracedNode (IndexType, IndexType)
IndexType index () const
bool is_weak () const
void set_weak (bool v)
bool is_droppable () const
void set_droppable (bool v)
bool is_in_use () const
void set_is_in_use (bool v)
bool is_in_young_list () const
void set_is_in_young_list (bool v)
IndexType next_free () const
void set_next_free (IndexType next_free_index)
void set_markbit ()
bool markbit () const
bool IsMetadataCleared () const
void clear_markbit ()
bool has_old_host () const
void set_has_old_host (bool v)
template<AccessMode access_mode = AccessMode::NON_ATOMIC>
void set_raw_object (Address value)
Address raw_object () const
Tagged< Object > object () const
FullObjectSlot location ()
FullObjectSlot Publish (Tagged< Object > object, bool needs_young_bit_update, bool needs_black_allocation, bool has_old_host, bool is_droppable)
void Release (Address zap_value)
Static Public Member Functions
static TracedNode * FromLocation (Address *location)
static const TracedNode * FromLocation (const Address *location)
Private Types
using IsInUse = base::BitField8< bool, 0, 1 >
using IsInYoungList = IsInUse::Next< bool, 1 >
using IsWeak = IsInYoungList::Next< bool, 1 >
using IsDroppable = IsWeak::Next< bool, 1 >
using HasOldHost = IsDroppable::Next< bool, 1 >
Private Attributes
Address object_ = kNullAddress
IndexType next_free_index_
IndexType index_
uint8_t flags_ = 0
std::atomic< bool > is_marked_ = false
Detailed Description
Definition at line 24 of file traced-handles.h.
Member Typedef Documentation
HasOldHost
using v8::internal::TracedNode::HasOldHost = IsDroppable::Next<bool, 1> [private]
Definition at line 98 of file traced-handles.h.
IndexType
using v8::internal::TracedNode::IndexType = uint8_t
Definition at line 29 of file traced-handles.h.
IsDroppable
using v8::internal::TracedNode::IsDroppable = IsWeak::Next<bool, 1> [private]
Definition at line 97 of file traced-handles.h.
IsInUse
using v8::internal::TracedNode::IsInUse = base::BitField8<bool, 0, 1> [private]
Definition at line 94 of file traced-handles.h.
IsInYoungList
using v8::internal::TracedNode::IsInYoungList = IsInUse::Next<bool, 1> [private]
Definition at line 95 of file traced-handles.h.
IsWeak
using v8::internal::TracedNode::IsWeak = IsInYoungList::Next<bool, 1> [private]
Definition at line 96 of file traced-handles.h.
Constructor & Destructor Documentation
TracedNode()
v8::internal::TracedNode::TracedNode (IndexType index, IndexType next_free_index)
Definition at line 28 of file traced-handles.cc.
    : next_free_index_(next_free_index), index_(index) {
  // TracedNode size should stay within 2 words.
  static_assert(sizeof(TracedNode) <= (2 * kSystemPointerSize));
  DCHECK(!is_in_use());
  DCHECK(!is_in_young_list());
  DCHECK(!is_weak());
  DCHECK(!markbit());
  DCHECK(!has_old_host());
  DCHECK(!is_droppable());
}
References v8::internal::DCHECK(), has_old_host(), is_droppable(), is_in_use(), is_in_young_list(), is_weak(), v8::internal::kSystemPointerSize, and markbit().
Member Function Documentation
clear_markbit()
void v8::internal::TracedNode::clear_markbit () [inline]
Definition at line 69 of file traced-handles.h.
{ is_marked_.store(false, std::memory_order_relaxed); }
References is_marked_.
Referenced by Release().
FromLocation() [1/2]
static TracedNode* v8::internal::TracedNode::FromLocation (Address * location) [inline], [static]
Definition at line 32 of file traced-handles.h.
                                                     {
    return reinterpret_cast<TracedNode*>(location);
  }
References location().
Referenced by v8::internal::TracedHandles::Copy(), v8::internal::TracedHandles::Destroy(), v8::internal::TracedHandles::IsValidInUseNode(), v8::internal::TracedHandles::Mark(), and v8::internal::TracedHandles::Move().
FromLocation() [2/2]
static const TracedNode* v8::internal::TracedNode::FromLocation (const Address * location) [inline], [static]
Definition at line 36 of file traced-handles.h.
                                                                 {
    return reinterpret_cast<const TracedNode*>(location);
  }
References location().
has_old_host()
bool v8::internal::TracedNode::has_old_host () const [inline]
Definition at line 71 of file traced-handles.h.
{ return HasOldHost::decode(flags_); }
References v8::base::BitField< T, shift, size, U >::decode(), and flags_.
Referenced by v8::internal::TracedHandles::Move(), v8::internal::TracedHandles::NeedsToBeRemembered(), Publish(), and TracedNode().
index()
IndexType v8::internal::TracedNode::index () const [inline]
Definition at line 42 of file traced-handles.h.
{ return index_; }
References index_.
Referenced by v8::internal::TracedNodeBlock::FreeNode(), and v8::internal::TracedNodeBlock::From().
is_droppable()
bool v8::internal::TracedNode::is_droppable () const [inline]
Definition at line 47 of file traced-handles.h.
{ return IsDroppable::decode(flags_); }
References v8::base::BitField< T, shift, size, U >::decode(), and flags_.
Referenced by TracedNode().
is_in_use()
bool v8::internal::TracedNode::is_in_use () const [inline]
Definition at line 50 of file traced-handles.h.
{ return IsInUse::decode(flags_); }
References v8::base::BitField< T, shift, size, U >::decode(), and flags_.
Referenced by v8::internal::TracedNodeBlock::FreeNode(), v8::internal::TracedHandles::IsValidInUseNode(), v8::internal::TracedHandles::MarkConservatively(), v8::internal::TracedHandles::Move(), Release(), and TracedNode().
is_in_young_list()
bool v8::internal::TracedNode::is_in_young_list () const [inline]
Definition at line 53 of file traced-handles.h.
{ return IsInYoungList::decode(flags_); }
References v8::base::BitField< T, shift, size, U >::decode(), and flags_.
Referenced by v8::internal::anonymous_namespace{traced-handles.cc}::MarkObject(), v8::internal::TracedHandles::Move(), v8::internal::TracedHandles::NeedsTrackingInYoungNodes(), and TracedNode().
is_weak()
bool v8::internal::TracedNode::is_weak () const [inline]
Definition at line 44 of file traced-handles.h.
{ return IsWeak::decode(flags_); }
References v8::base::BitField< T, shift, size, U >::decode(), and flags_.
Referenced by TracedNode().
IsMetadataCleared()
bool v8::internal::TracedNode::IsMetadataCleared () const [inline]
Definition at line 67 of file traced-handles.h.
{ return flags_ == 0 && !markbit(); }
References flags_, and markbit().
Referenced by Publish(), and Release().
location()
FullObjectSlot v8::internal::TracedNode::location () [inline]
Definition at line 85 of file traced-handles.h.
{ return FullObjectSlot(&object_); }
References object_.
Referenced by FromLocation().
markbit()
bool v8::internal::TracedNode::markbit () const [inline]
Definition at line 65 of file traced-handles.h.
{ return is_marked_.load(std::memory_order_relaxed); }
References is_marked_.
Referenced by IsMetadataCleared(), v8::internal::TracedHandles::IsValidInUseNode(), and TracedNode().
next_free()
IndexType v8::internal::TracedNode::next_free () const [inline]
Definition at line 58 of file traced-handles.h.
{ return next_free_index_; }
References next_free_index_.
object()
Tagged<Object> v8::internal::TracedNode::object () const [inline]
Definition at line 84 of file traced-handles.h.
{ return Tagged<Object>(object_); }
References object_, and v8::internal::Tagged< Object >.
Referenced by v8::internal::TracedHandles::MarkConservatively(), and v8::internal::TracedHandles::Move().
Publish()
FullObjectSlot v8::internal::TracedNode::Publish (Tagged< Object > object, bool needs_young_bit_update, bool needs_black_allocation, bool has_old_host, bool is_droppable) [inline]
Definition at line 91 of file traced-handles-inl.h.
                                                                               {
  DCHECK(IsMetadataCleared());
  flags_ = needs_young_bit_update << IsInYoungList::kShift |
           has_old_host << HasOldHost::kShift |
           is_droppable_value << IsDroppable::kShift | 1 << IsInUse::kShift;
  if (needs_black_allocation) set_markbit();
  reinterpret_cast<std::atomic<Address>*>(&object_)->store(
      object.ptr(), std::memory_order_release);
  return FullObjectSlot(&object_);
}
References v8::internal::DCHECK(), flags_, has_old_host(), IsMetadataCleared(), v8::base::BitField< T, shift, size, U >::kShift, object_, set_markbit(), and store().
raw_object()
Address v8::internal::TracedNode::raw_object () const [inline]
Definition at line 83 of file traced-handles.h.
{ return object_; }
References object_.
Referenced by v8::internal::TracedHandles::Copy(), v8::internal::TracedHandles::IsValidInUseNode(), and v8::internal::TracedHandles::Move().
Release()
void v8::internal::TracedNode::Release (Address zap_value)
Definition at line 40 of file traced-handles.cc.
                                          {
  DCHECK(is_in_use());
  // Clear all flags.
  flags_ = 0;
  clear_markbit();
  set_raw_object(zap_value);
  DCHECK(IsMetadataCleared());
}
References clear_markbit(), v8::internal::DCHECK(), flags_, is_in_use(), IsMetadataCleared(), and set_raw_object().
Referenced by v8::internal::TracedNodeBlock::FreeNode().
set_droppable()
void v8::internal::TracedNode::set_droppable (bool v) [inline]
Definition at line 48 of file traced-handles.h.
{ flags_ = IsDroppable::update(flags_, v); }
References flags_, and v8::base::BitField< T, shift, size, U >::update().
set_has_old_host()
void v8::internal::TracedNode::set_has_old_host (bool v) [inline]
Definition at line 72 of file traced-handles.h.
{ flags_ = HasOldHost::update(flags_, v); }
References flags_, and v8::base::BitField< T, shift, size, U >::update().
Referenced by v8::internal::TracedHandles::Move().
set_is_in_use()
void v8::internal::TracedNode::set_is_in_use (bool v) [inline]
Definition at line 51 of file traced-handles.h.
{ flags_ = IsInUse::update(flags_, v); }
References flags_, and v8::base::BitField< T, shift, size, U >::update().
set_is_in_young_list()
void v8::internal::TracedNode::set_is_in_young_list (bool v) [inline]
Definition at line 54 of file traced-handles.h.
                                    {
    flags_ = IsInYoungList::update(flags_, v);
  }
References flags_, and v8::base::BitField< T, shift, size, U >::update().
set_markbit()
void v8::internal::TracedNode::set_markbit () [inline]
Definition at line 63 of file traced-handles.h.
{ is_marked_.store(true, std::memory_order_relaxed); }
References is_marked_.
Referenced by v8::internal::anonymous_namespace{traced-handles.cc}::MarkObject(), and Publish().
set_next_free()
void v8::internal::TracedNode::set_next_free (IndexType next_free_index) [inline]
Definition at line 59 of file traced-handles.h.
                                                {
    next_free_index_ = next_free_index;
  }
References next_free_index_.
Referenced by v8::internal::TracedNodeBlock::FreeNode().
set_raw_object()
template<AccessMode access_mode = AccessMode::NON_ATOMIC>
void v8::internal::TracedNode::set_raw_object (Address value) [inline]
Definition at line 75 of file traced-handles.h.
                                     {
    if constexpr (access_mode == AccessMode::NON_ATOMIC) {
      object_ = value;
    } else {
      reinterpret_cast<std::atomic<Address>*>(&object_)->store(
          value, std::memory_order_relaxed);
    }
  }
References v8::internal::NON_ATOMIC, object_, store(), and v8::internal::value.
Referenced by v8::internal::TracedHandles::Destroy(), and Release().
set_weak()
void v8::internal::TracedNode::set_weak (bool v) [inline]
Definition at line 45 of file traced-handles.h.
{ flags_ = IsWeak::update(flags_, v); }
References flags_, and v8::base::BitField< T, shift, size, U >::update().
Member Data Documentation
flags_
uint8_t v8::internal::TracedNode::flags_ = 0 [private]
Definition at line 104 of file traced-handles.h.
Referenced by has_old_host(), is_droppable(), is_in_use(), is_in_young_list(), is_weak(), IsMetadataCleared(), Publish(), Release(), set_droppable(), set_has_old_host(), set_is_in_use(), set_is_in_young_list(), and set_weak().
index_
IndexType v8::internal::TracedNode::index_ [private]
Definition at line 103 of file traced-handles.h.
Referenced by index().
is_marked_
std::atomic<bool> v8::internal::TracedNode::is_marked_ = false [private]
Definition at line 107 of file traced-handles.h.
Referenced by clear_markbit(), markbit(), and set_markbit().
next_free_index_
IndexType v8::internal::TracedNode::next_free_index_ [private]
Definition at line 102 of file traced-handles.h.
Referenced by next_free(), and set_next_free().
object_
Address v8::internal::TracedNode::object_ = kNullAddress [private]
Definition at line 100 of file traced-handles.h.
Referenced by location(), object(), Publish(), raw_object(), and set_raw_object().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/handles/traced-handles.h
/mnt/V8SourceCode/src/handles/traced-handles-inl.h
/mnt/V8SourceCode/src/handles/traced-handles.cc