v8::internal::torque::VisitResultVector Class Reference
#include <types.h>
Public Member Functions
VisitResultVector ()
VisitResultVector (std::initializer_list< VisitResult > init)
TypeVector ComputeTypeVector () const
Detailed Description
Definition at line 865 of file types.h.
Constructor & Destructor Documentation
VisitResultVector() [1/2]
v8::internal::torque::VisitResultVector::VisitResultVector () [inline]
Definition at line 867 of file types.h.
: std::vector<VisitResult>() {}
VisitResultVector() [2/2]
v8::internal::torque::VisitResultVector::VisitResultVector (std::initializer_list< VisitResult > init) [inline]
Definition at line 868 of file types.h.
      : std::vector<VisitResult>(init) {}
Member Function Documentation
ComputeTypeVector()
TypeVector v8::internal::torque::VisitResultVector::ComputeTypeVector () const [inline]
Definition at line 870 of file types.h.
                                       {
    TypeVector result;
    for (auto& visit_result : *this) {
      result.push_back(visit_result.type());
    }
    return result;
  }
References v8::base::internal::result.
Referenced by v8::internal::torque::ImplementationVisitor::GeneratePointerCall(), v8::internal::torque::ImplementationVisitor::LookupCallable(), v8::internal::torque::ImplementationVisitor::LookupMethod(), and v8::internal::torque::ImplementationVisitor::Visit().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/types.h