v8::internal::wasm::LiftoffRegList::Iterator Class Reference
#include <liftoff-register.h>
Public Member Functions
LiftoffRegister operator* ()
Iterator & operator++ ()
bool operator== (const Iterator &other) const =default
Private Member Functions
Iterator (LiftoffRegList remaining)
Private Attributes
LiftoffRegList remaining_
Friends
class LiftoffRegList
Detailed Description
Definition at line 525 of file liftoff-register.h.
Constructor & Destructor Documentation
Iterator()
v8::internal::wasm::LiftoffRegList::Iterator::Iterator (LiftoffRegList remaining) [inline], [explicit], [private]
Definition at line 535 of file liftoff-register.h.
: remaining_(remaining) {}
Member Function Documentation
operator*()
LiftoffRegister v8::internal::wasm::LiftoffRegList::Iterator::operator* () [inline]
Definition at line 527 of file liftoff-register.h.
{ return remaining_.GetFirstRegSet(); }
References v8::internal::wasm::LiftoffRegList::GetFirstRegSet(), and remaining_.
operator++()
Iterator& v8::internal::wasm::LiftoffRegList::Iterator::operator++ () [inline]
Definition at line 528 of file liftoff-register.h.
                         {
    remaining_.clear(remaining_.GetFirstRegSet());
    return *this;
  }
References v8::internal::wasm::LiftoffRegList::clear(), v8::internal::wasm::LiftoffRegList::GetFirstRegSet(), and remaining_.
operator==()
bool v8::internal::wasm::LiftoffRegList::Iterator::operator== (const Iterator & other) const [default]
Friends And Related Function Documentation
LiftoffRegList
friend class LiftoffRegList [friend]
Definition at line 536 of file liftoff-register.h.
Member Data Documentation
remaining_
LiftoffRegList v8::internal::wasm::LiftoffRegList::Iterator::remaining_ [private]
Definition at line 538 of file liftoff-register.h.
Referenced by operator*(), and operator++().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/baseline/liftoff-register.h