v8::internal::CpuProfile Class Reference
#include <profile-generator.h>
Classes
struct SampleInfo
Public Member Functions
V8_EXPORT_PRIVATE CpuProfile (CpuProfiler *profiler, ProfilerId id, const char *title, CpuProfilingOptions options, std::unique_ptr< DiscardedSamplesDelegate > delegate=nullptr)
CpuProfile (const CpuProfile &)=delete
CpuProfile & operator= (const CpuProfile &)=delete
V8_EXPORT_PRIVATE bool CheckSubsample (base::TimeDelta sampling_interval)
void AddPath (base::TimeTicks timestamp, const ProfileStackTrace &path, LineAndColumn src_pos, bool update_stats, base::TimeDelta sampling_interval, StateTag state, EmbedderStateTag embedder_state, const std::optional< uint64_t > trace_id=std::nullopt)
void FinishProfile ()
const char * title () const
const ProfileTree * top_down () const
int samples_count () const
const SampleInfo & sample (int index) const
int64_t sampling_interval_us () const
base::TimeTicks start_time () const
base::TimeTicks end_time () const
CpuProfiler * cpu_profiler () const
ContextFilter & context_filter ()
ProfilerId id () const
void UpdateTicksScale ()
V8_EXPORT_PRIVATE void Print () const
Private Member Functions
void StreamPendingTraceEvents ()
Private Attributes
const char * title_
const CpuProfilingOptions options_
std::unique_ptr< DiscardedSamplesDelegate > delegate_
ContextFilter context_filter_
base::TimeTicks start_time_
base::TimeTicks end_time_
std::deque< SampleInfo > samples_
ProfileTree top_down_
CpuProfiler *const profiler_
size_t streaming_next_sample_
const ProfilerId id_
base::TimeDelta next_sample_delta_
Detailed Description
Definition at line 417 of file profile-generator.h.
Constructor & Destructor Documentation
CpuProfile() [1/2]
v8::internal::CpuProfile::CpuProfile (CpuProfiler * profiler, ProfilerId id, const char * title, CpuProfilingOptions options, std::unique_ptr< DiscardedSamplesDelegate > delegate = nullptr)
Definition at line 575 of file profile-generator.cc.
    : title_(title),
      options_(std::move(options)),
      delegate_(std::move(delegate)),
      start_time_(base::TimeTicks::Now()),
      top_down_(profiler->isolate(), profiler->code_entries()),
      profiler_(profiler),
      streaming_next_sample_(0),
      id_(id) {
  // The startTime timestamp is not converted to Perfetto's clock domain and
  // will get out of sync with other timestamps Perfetto knows about, including
  // the automatic trace event "ts" timestamp. startTime is included for
  // backward compatibility with the tracing protocol but the value of "ts"
  // should be used instead (it is recorded nearly immediately after).
  auto value = TracedValue::Create();
  value->SetDouble("startTime", start_time_.since_origin().InMicroseconds());
  TRACE_EVENT_SAMPLE_WITH_ID1(TRACE_DISABLED_BY_DEFAULT("v8.cpu_profiler"),
                              "Profile", id_, "data", std::move(value));
  DisallowHeapAllocation no_gc;
  if (delegate_) {
    delegate_->SetId(id_);
  }
  if (options_.has_filter_context()) {
    i::Address raw_filter_context =
        reinterpret_cast<i::Address>(options_.raw_filter_context());
    context_filter_.set_native_context_address(raw_filter_context);
  }
}
References context_filter_, v8::tracing::TracedValue::Create(), delegate_, v8::CpuProfilingOptions::has_filter_context(), id_, v8::base::TimeDelta::InMicroseconds(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, options_, v8::CpuProfilingOptions::raw_filter_context(), v8::internal::ContextFilter::set_native_context_address(), v8::base::time_internal::TimeBase< TimeClass >::since_origin(), start_time_, TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT_SAMPLE_WITH_ID1, and v8::internal::value.
CpuProfile() [2/2]
v8::internal::CpuProfile::CpuProfile (const CpuProfile &) [delete]
Member Function Documentation
AddPath()
void v8::internal::CpuProfile::AddPath (base::TimeTicks timestamp, const ProfileStackTrace & path, LineAndColumn src_pos, bool update_stats, base::TimeDelta sampling_interval, StateTag state, EmbedderStateTag embedder_state, const std::optional< uint64_t > trace_id = std::nullopt)
Definition at line 624 of file profile-generator.cc.
                                                               {
  if (!CheckSubsample(sampling_interval)) return;
  ProfileNode* top_frame_node =
      top_down_.AddPathFromEnd(path, src_pos, update_stats, options_.mode());
  bool is_buffer_full =
      options_.max_samples() != CpuProfilingOptions::kNoSampleLimit &&
      samples_.size() >= options_.max_samples();
  bool should_record_sample =
      !timestamp.IsNull() && timestamp >= start_time_ && !is_buffer_full;
  if (should_record_sample) {
    samples_.push_back({top_frame_node, timestamp, src_pos, state_tag,
                        embedder_state_tag, trace_id});
  } else if (is_buffer_full && delegate_ != nullptr) {
    const auto task_runner = V8::GetCurrentPlatform()->GetForegroundTaskRunner(
        reinterpret_cast<v8::Isolate*>(profiler_->isolate()));
    task_runner->PostTask(std::make_unique<CpuProfileMaxSamplesCallbackTask>(
        std::move(delegate_)));
    // std::move ensures that the delegate_ will be null on the next sample,
    // so we don't post a task multiple times.
  }
  const int kSamplesFlushCount = 100;
  const int kNodesFlushCount = 10;
  if (samples_.size() - streaming_next_sample_ >= kSamplesFlushCount ||
      top_down_.pending_nodes_count() >= kNodesFlushCount) {
    StreamPendingTraceEvents();
  }
}
References v8::internal::ProfileTree::AddPathFromEnd(), CheckSubsample(), delegate_, v8::internal::V8::GetCurrentPlatform(), v8::Platform::GetForegroundTaskRunner(), v8::base::time_internal::TimeBase< TimeClass >::IsNull(), v8::internal::CpuProfiler::isolate(), v8::CpuProfilingOptions::kNoSampleLimit, v8::CpuProfilingOptions::max_samples(), v8::CpuProfilingOptions::mode(), options_, v8::internal::ProfileTree::pending_nodes_count(), profiler_, samples_, start_time_, streaming_next_sample_, StreamPendingTraceEvents(), and top_down_.
CheckSubsample()
bool v8::internal::CpuProfile::CheckSubsample (base::TimeDelta sampling_interval)
Definition at line 607 of file profile-generator.cc.
                                                                      {
  DCHECK_GE(source_sampling_interval, base::TimeDelta());
  // If the sampling source's sampling interval is 0, record as many samples
  // are possible irrespective of the profile's sampling interval. Manually
  // taken samples (via CollectSample) fall into this case as well.
  if (source_sampling_interval.IsZero()) return true;
  next_sample_delta_ -= source_sampling_interval;
  if (next_sample_delta_ <= base::TimeDelta()) {
    next_sample_delta_ =
        base::TimeDelta::FromMicroseconds(options_.sampling_interval_us());
    return true;
  }
  return false;
}
References DCHECK_GE, v8::base::TimeDelta::FromMicroseconds(), v8::base::TimeDelta::IsZero(), next_sample_delta_, options_, and v8::CpuProfilingOptions::sampling_interval_us().
Referenced by AddPath().
context_filter()
ContextFilter& v8::internal::CpuProfile::context_filter () [inline]
Definition at line 459 of file profile-generator.h.
{ return context_filter_; }
References context_filter_.
cpu_profiler()
CpuProfiler* v8::internal::CpuProfile::cpu_profiler () const [inline]
Definition at line 458 of file profile-generator.h.
{ return profiler_; }
References profiler_.
Referenced by v8::CpuProfile::Delete().
end_time()
base::TimeTicks v8::internal::CpuProfile::end_time () const [inline]
Definition at line 457 of file profile-generator.h.
{ return end_time_; }
References end_time_.
Referenced by v8::CpuProfile::GetEndTime(), and v8::internal::CpuProfileJSONSerializer::SerializeImpl().
FinishProfile()
void v8::internal::CpuProfile::FinishProfile ()
Definition at line 771 of file profile-generator.cc.
                               {
  end_time_ = base::TimeTicks::Now();
  // Stop tracking context movements after profiling stops.
  context_filter_.set_native_context_address(kNullAddress);
  StreamPendingTraceEvents();
  auto value = TracedValue::Create();
  // The endTime timestamp is not converted to Perfetto's clock domain and will
  // get out of sync with other timestamps Perfetto knows about, including the
  // automatic trace event "ts" timestamp. endTime is included for backward
  // compatibility with the tracing protocol: its presence in "data" is used by
  // devtools to identify the last ProfileChunk but the value of "ts" should be
  // used instead (it is recorded nearly immediately after).
  value->SetDouble("endTime", end_time_.since_origin().InMicroseconds());
  TRACE_EVENT_SAMPLE_WITH_ID1(TRACE_DISABLED_BY_DEFAULT("v8.cpu_profiler"),
                              "ProfileChunk", id_, "data", std::move(value));
}
References context_filter_, v8::tracing::TracedValue::Create(), end_time_, id_, v8::base::TimeDelta::InMicroseconds(), v8::internal::kNullAddress, v8::base::TimeTicks::Now(), v8::internal::ContextFilter::set_native_context_address(), v8::base::time_internal::TimeBase< TimeClass >::since_origin(), StreamPendingTraceEvents(), TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT_SAMPLE_WITH_ID1, and v8::internal::value.
id()
ProfilerId v8::internal::CpuProfile::id () const [inline]
Definition at line 460 of file profile-generator.h.
{ return id_; }
References id_.
Referenced by v8::HeapGraphNode::GetId(), v8::internal::CpuProfilesCollection::StartProfiling(), and v8::internal::CpuProfiler::StopProfiling().
operator=()
CpuProfile& v8::internal::CpuProfile::operator= (const CpuProfile &) [delete]
Print()
void v8::internal::CpuProfile::Print () const
Definition at line 942 of file profile-generator.cc.
                             {
  base::OS::Print("[Top down]:\n");
  top_down_.Print();
  ProfilerStats::Instance()->Print();
  ProfilerStats::Instance()->Clear();
}
References v8::internal::ProfilerStats::Clear(), v8::internal::ProfilerStats::Instance(), v8::internal::ProfileTree::Print(), v8::internal::ProfilerStats::Print(), v8::internal::Print(), and top_down_.
sample()
const SampleInfo& v8::internal::CpuProfile::sample (int index) const [inline]
Definition at line 450 of file profile-generator.h.
{ return samples_[index]; }
References v8::internal::index, and samples_.
Referenced by v8::CpuProfile::GetSample(), v8::CpuProfile::GetSampleEmbedderState(), v8::CpuProfile::GetSampleState(), v8::CpuProfile::GetSampleTimestamp(), v8::internal::CpuProfileJSONSerializer::SerializeSamples(), v8::internal::CpuProfileJSONSerializer::SerializeTimeDeltas(), and StreamPendingTraceEvents().
samples_count()
int v8::internal::CpuProfile::samples_count () const [inline]
Definition at line 449 of file profile-generator.h.
{ return static_cast<int>(samples_.size()); }
References samples_.
Referenced by v8::internal::CpuProfileJSONSerializer::SerializeSamples(), and v8::internal::CpuProfileJSONSerializer::SerializeTimeDeltas().
sampling_interval_us()
int64_t v8::internal::CpuProfile::sampling_interval_us () const [inline]
Definition at line 452 of file profile-generator.h.
                                       {
    return options_.sampling_interval_us();
  }
References options_, and v8::CpuProfilingOptions::sampling_interval_us().
start_time()
base::TimeTicks v8::internal::CpuProfile::start_time () const [inline]
Definition at line 456 of file profile-generator.h.
{ return start_time_; }
References start_time_.
Referenced by v8::CpuProfile::GetStartTime(), v8::internal::CpuProfileJSONSerializer::SerializeImpl(), v8::internal::CpuProfileJSONSerializer::SerializeTimeDeltas(), and StreamPendingTraceEvents().
StreamPendingTraceEvents()
void v8::internal::CpuProfile::StreamPendingTraceEvents () [private]
Definition at line 691 of file profile-generator.cc.
                                          {
  std::vector<const ProfileNode*> pending_nodes = top_down_.TakePendingNodes();
  if (pending_nodes.empty() && samples_.empty()) return;
  auto value = TracedValue::Create();
  if (!pending_nodes.empty() || streaming_next_sample_ != samples_.size()) {
    value->BeginDictionary("cpuProfile");
    if (!pending_nodes.empty()) {
      value->BeginArray("nodes");
      for (auto node : pending_nodes) {
        value->BeginDictionary();
        BuildNodeValue(node, value.get());
        value->EndDictionary();
      }
      value->EndArray();
    }
    if (streaming_next_sample_ != samples_.size()) {
      value->BeginArray("samples");
      for (size_t i = streaming_next_sample_; i < samples_.size(); ++i) {
        value->AppendInteger(samples_[i].node->id());
      }
      value->EndArray();
      value->BeginDictionary("trace_ids");
      for (size_t i = streaming_next_sample_; i < samples_.size(); ++i) {
        if (!samples_[i].trace_id.has_value()) {
          continue;
        }
        value->SetUnsignedInteger(
            std::to_string(samples_[i].trace_id.value()).c_str(),
            samples_[i].node->id());
      }
      value->EndDictionary();
    }
    value->EndDictionary();
  }
  if (streaming_next_sample_ != samples_.size()) {
    // timeDeltas are computed within CLOCK_MONOTONIC. However, trace event
    // "ts" timestamps are converted to CLOCK_BOOTTIME by Perfetto. To get
    // absolute timestamps in CLOCK_BOOTTIME from timeDeltas, add them to
    // the "ts" timestamp from the initial "Profile" trace event sent by
    // CpuProfile::CpuProfile().
    //
    // Note that if the system is suspended and resumed while samples_ is
    // captured, timeDeltas derived after resume will not be convertible to
    // correct CLOCK_BOOTTIME time values (for instance, producing
    // CLOCK_BOOTTIME time values in the middle of the suspended period).
    value->BeginArray("timeDeltas");
    base::TimeTicks lastTimestamp =
        streaming_next_sample_ ? samples_[streaming_next_sample_ - 1].timestamp
                               : start_time();
    for (size_t i = streaming_next_sample_; i < samples_.size(); ++i) {
      value->AppendInteger(static_cast<int>(
          (samples_[i].timestamp - lastTimestamp).InMicroseconds()));
      lastTimestamp = samples_[i].timestamp;
    }
    value->EndArray();
    bool has_non_zero_lines =
        std::any_of(samples_.begin() + streaming_next_sample_, samples_.end(),
                    [](const SampleInfo& sample) {
                      return sample.line_and_column.line != 0;
                    });
    if (has_non_zero_lines) {
      value->BeginArray("lines");
      for (size_t i = streaming_next_sample_; i < samples_.size(); ++i) {
        value->AppendInteger(samples_[i].line_and_column.line);
      }
      value->EndArray();
      value->BeginArray("columns");
      for (size_t i = streaming_next_sample_; i < samples_.size(); ++i) {
        value->AppendInteger(samples_[i].line_and_column.column);
      }
      value->EndArray();
    }
    streaming_next_sample_ = samples_.size();
  }
  TRACE_EVENT_SAMPLE_WITH_ID1(TRACE_DISABLED_BY_DEFAULT("v8.cpu_profiler"),
                              "ProfileChunk", id_, "data", std::move(value));
}
References v8::base::any_of(), v8::internal::anonymous_namespace{profile-generator.cc}::BuildNodeValue(), v8::tracing::TracedValue::Create(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, id_, sample(), samples_, start_time(), streaming_next_sample_, v8::internal::ProfileTree::TakePendingNodes(), top_down_, TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT_SAMPLE_WITH_ID1, and v8::internal::value.
Referenced by AddPath(), and FinishProfile().
title()
const char* v8::internal::CpuProfile::title () const [inline]
Definition at line 446 of file profile-generator.h.
{ return title_; }
References title_.
Referenced by v8::CpuProfile::GetTitle().
top_down()
const ProfileTree* v8::internal::CpuProfile::top_down () const [inline]
Definition at line 447 of file profile-generator.h.
{ return &top_down_; }
References top_down_.
Referenced by v8::CpuProfile::GetTitle(), v8::CpuProfile::GetTopDownRoot(), and v8::internal::CpuProfileJSONSerializer::SerializeNodes().
UpdateTicksScale()
void v8::internal::CpuProfile::UpdateTicksScale ()
Member Data Documentation
context_filter_
ContextFilter v8::internal::CpuProfile::context_filter_ [private]
Definition at line 472 of file profile-generator.h.
Referenced by context_filter(), CpuProfile(), and FinishProfile().
delegate_
std::unique_ptr<DiscardedSamplesDelegate> v8::internal::CpuProfile::delegate_ [private]
Definition at line 471 of file profile-generator.h.
Referenced by AddPath(), and CpuProfile().
end_time_
base::TimeTicks v8::internal::CpuProfile::end_time_ [private]
Definition at line 474 of file profile-generator.h.
Referenced by end_time(), and FinishProfile().
id_
const ProfilerId v8::internal::CpuProfile::id_ [private]
Definition at line 479 of file profile-generator.h.
Referenced by CpuProfile(), FinishProfile(), id(), and StreamPendingTraceEvents().
next_sample_delta_
base::TimeDelta v8::internal::CpuProfile::next_sample_delta_ [private]
Definition at line 482 of file profile-generator.h.
Referenced by CheckSubsample().
options_
const CpuProfilingOptions v8::internal::CpuProfile::options_ [private]
Definition at line 470 of file profile-generator.h.
Referenced by AddPath(), CheckSubsample(), CpuProfile(), and sampling_interval_us().
profiler_
CpuProfiler* const v8::internal::CpuProfile::profiler_ [private]
Definition at line 477 of file profile-generator.h.
Referenced by AddPath(), and cpu_profiler().
samples_
std::deque<SampleInfo> v8::internal::CpuProfile::samples_ [private]
Definition at line 475 of file profile-generator.h.
Referenced by AddPath(), sample(), samples_count(), and StreamPendingTraceEvents().
start_time_
base::TimeTicks v8::internal::CpuProfile::start_time_ [private]
Definition at line 473 of file profile-generator.h.
Referenced by AddPath(), CpuProfile(), and start_time().
streaming_next_sample_
size_t v8::internal::CpuProfile::streaming_next_sample_ [private]
Definition at line 478 of file profile-generator.h.
Referenced by AddPath(), and StreamPendingTraceEvents().
title_
const char* v8::internal::CpuProfile::title_ [private]
Definition at line 469 of file profile-generator.h.
Referenced by title().
top_down_
ProfileTree v8::internal::CpuProfile::top_down_ [private]
Definition at line 476 of file profile-generator.h.
Referenced by AddPath(), Print(), StreamPendingTraceEvents(), and top_down().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/profiler/profile-generator.h
/mnt/V8SourceCode/src/profiler/profile-generator.cc