v8::internal::PropertyCallbackArguments Class Reference
#include <api-arguments.h>
Public Types
using T = PropertyCallbackInfo< Value >
using Super = CustomArguments< T >
Public Member Functions
PropertyCallbackArguments (Isolate *isolate, Tagged< Object > data, Tagged< Object > self, Tagged< JSObject > holder, Maybe< ShouldThrow > should_throw)
~PropertyCallbackArguments ()
PropertyCallbackArguments (const PropertyCallbackArguments &)=delete
PropertyCallbackArguments & operator= (const PropertyCallbackArguments &)=delete
DirectHandle< JSAny > CallAccessorGetter (DirectHandle< AccessorInfo > info, DirectHandle< Name > name)
V8_WARN_UNUSED_RESULT bool CallAccessorSetter (DirectHandle< AccessorInfo > info, DirectHandle< Name > name, DirectHandle< Object > value)
DirectHandle< Object > CallNamedQuery (DirectHandle< InterceptorInfo > interceptor, DirectHandle< Name > name)
DirectHandle< JSAny > CallNamedGetter (DirectHandle< InterceptorInfo > interceptor, DirectHandle< Name > name)
v8::Intercepted CallNamedSetter (DirectHandle< InterceptorInfo > interceptor, DirectHandle< Name > name, DirectHandle< Object > value)
v8::Intercepted CallNamedDefiner (DirectHandle< InterceptorInfo > interceptor, DirectHandle< Name > name, const v8::PropertyDescriptor &desc)
v8::Intercepted CallNamedDeleter (DirectHandle< InterceptorInfo > interceptor, DirectHandle< Name > name)
Handle< JSAny > CallNamedDescriptor (DirectHandle< InterceptorInfo > interceptor, DirectHandle< Name > name)
DirectHandle< JSObjectOrUndefined > CallNamedEnumerator (DirectHandle< InterceptorInfo > interceptor)
DirectHandle< Object > CallIndexedQuery (DirectHandle< InterceptorInfo > interceptor, uint32_t index)
DirectHandle< JSAny > CallIndexedGetter (DirectHandle< InterceptorInfo > interceptor, uint32_t index)
v8::Intercepted CallIndexedSetter (DirectHandle< InterceptorInfo > interceptor, uint32_t index, DirectHandle< Object > value)
v8::Intercepted CallIndexedDefiner (DirectHandle< InterceptorInfo > interceptor, uint32_t index, const v8::PropertyDescriptor &desc)
v8::Intercepted CallIndexedDeleter (DirectHandle< InterceptorInfo > interceptor, uint32_t index)
Handle< JSAny > CallIndexedDescriptor (DirectHandle< InterceptorInfo > interceptor, uint32_t index)
DirectHandle< JSObjectOrUndefined > CallIndexedEnumerator (DirectHandle< InterceptorInfo > interceptor)
void AcceptSideEffects ()
Maybe< InterceptorResult > GetBooleanReturnValue (v8::Intercepted intercepted, const char *callback_kind_for_error_message, bool ignore_return_value=false)
template<typename T >
const v8::PropertyCallbackInfo< T > & GetPropertyCallbackInfo ()
bool ShouldThrowOnError ()
Static Public Member Functions
template<typename T >
static Tagged< Object > GetPropertyKey (const PropertyCallbackInfo< T > &info)
template<typename T >
static Handle< Object > GetPropertyKeyHandle (const PropertyCallbackInfo< T > &info)
template<typename T >
static uint32_t GetPropertyIndex (const PropertyCallbackInfo< T > &info)
Static Public Attributes
static constexpr int kArgsLength = T::kArgsLength
static constexpr int kThisIndex = T::kThisIndex
static constexpr int kDataIndex = T::kDataIndex
static constexpr int kHolderV2Index = T::kHolderV2Index
static constexpr int kHolderIndex = T::kHolderIndex
static constexpr int kIsolateIndex = T::kIsolateIndex
static constexpr int kShouldThrowOnErrorIndex = T::kShouldThrowOnErrorIndex
static constexpr int kPropertyKeyIndex = T::kPropertyKeyIndex
Private Member Functions
DirectHandle< JSObjectOrUndefined > CallPropertyEnumerator (DirectHandle< InterceptorInfo > interceptor)
Tagged< JSObject > holder () const
Tagged< Object > receiver () const
Private Attributes
uint32_t index_ = kMaxUInt32
Additional Inherited Members
Detailed Description
Definition at line 70 of file api-arguments.h.
Member Typedef Documentation
Super
using v8::internal::PropertyCallbackArguments::Super = CustomArguments<T>
Definition at line 74 of file api-arguments.h.
T
using v8::internal::PropertyCallbackArguments::T = PropertyCallbackInfo<Value>
Definition at line 73 of file api-arguments.h.
Constructor & Destructor Documentation
PropertyCallbackArguments() [1/2]
v8::internal::PropertyCallbackArguments::PropertyCallbackArguments (Isolate * isolate, Tagged< Object > data, Tagged< Object > self, Tagged< JSObject > holder, Maybe< ShouldThrow > should_throw)
Definition at line 12 of file api-arguments.cc.
    : Super(isolate)
#ifdef DEBUG
      ,
      javascript_execution_counter_(isolate->javascript_execution_counter())
#endif // DEBUG
{
  if (DEBUG_BOOL) {
    // Zap these fields to ensure that they are initialized by a subsequent
    // CallXXX(..).
    Tagged<Object> zap_value(kZapValue);
    slot_at(T::kPropertyKeyIndex).store(zap_value);
    slot_at(T::kReturnValueIndex).store(zap_value);
  }
  slot_at(T::kThisIndex).store(self);
  slot_at(T::kHolderIndex).store(holder);
  slot_at(T::kDataIndex).store(data);
  slot_at(T::kIsolateIndex)
      .store(Tagged<Object>(reinterpret_cast<Address>(isolate)));
  int value = Internals::kInferShouldThrowMode;
  if (should_throw.IsJust()) {
    value = should_throw.FromJust();
  }
  slot_at(T::kShouldThrowOnErrorIndex).store(Smi::FromInt(value));
  slot_at(T::kHolderV2Index).store(Smi::zero());
  DCHECK(IsHeapObject(*slot_at(T::kHolderIndex)));
  DCHECK(IsSmi(*slot_at(T::kIsolateIndex)));
}
References v8::internal::DCHECK(), DEBUG_BOOL, v8::internal::Smi::FromInt(), v8::Maybe< T >::FromJust(), holder(), v8::internal::IsHeapObject(), v8::Maybe< T >::IsJust(), v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::isolate(), v8::internal::IsSmi(), v8::PropertyCallbackInfo< T >::kDataIndex, v8::PropertyCallbackInfo< T >::kHolderIndex, v8::PropertyCallbackInfo< T >::kHolderV2Index, v8::internal::Internals::kInferShouldThrowMode, v8::PropertyCallbackInfo< T >::kIsolateIndex, v8::PropertyCallbackInfo< T >::kPropertyKeyIndex, v8::PropertyCallbackInfo< T >::kReturnValueIndex, v8::PropertyCallbackInfo< T >::kShouldThrowOnErrorIndex, v8::PropertyCallbackInfo< T >::kThisIndex, v8::internal::kZapValue, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::slot_at(), v8::internal::FullObjectSlot::store(), v8::internal::value, and v8::internal::Smi::zero().
 PropertyCallbackArguments()
v8::internal::PropertyCallbackArguments::~PropertyCallbackArguments () [inline]
Definition at line 97 of file api-arguments-inl.h.
                                                     {
#ifdef DEBUG
// TODO(chromium:1310062): enable this check.
// if (javascript_execution_counter_) {
// CHECK_WITH_MSG(javascript_execution_counter_ ==
// isolate()->javascript_execution_counter(),
// "Unexpected side effect detected");
// }
#endif // DEBUG
}
PropertyCallbackArguments() [2/2]
v8::internal::PropertyCallbackArguments::PropertyCallbackArguments (const PropertyCallbackArguments &) [delete]
Member Function Documentation
AcceptSideEffects()
void v8::internal::PropertyCallbackArguments::AcceptSideEffects () [inline]
Definition at line 179 of file api-arguments.h.
                                  {
#ifdef DEBUG
    javascript_execution_counter_ = 0;
#endif // DEBUG
  }
Referenced by CallAccessorGetter(), CallAccessorSetter(), v8::internal::KeyAccumulator::CollectInterceptorKeysInternal(), GetBooleanReturnValue(), and v8::internal::RUNTIME_FUNCTION().
CallAccessorGetter()
DirectHandle< JSAny > v8::internal::PropertyCallbackArguments::CallAccessorGetter (DirectHandle< AccessorInfo > info, DirectHandle< Name > name) [inline]
Definition at line 416 of file api-arguments-inl.h.
                                                              {
  Isolate* isolate = this->isolate();
  RCS_SCOPE(isolate, RuntimeCallCounterId::kAccessorGetterCallback);
  // Unlike interceptor callbacks we know that the property exists, so
  // the callback is allowed to have side effects.
  AcceptSideEffects();
  slot_at(kPropertyKeyIndex).store(*name);
  slot_at(kReturnValueIndex).store(ReadOnlyRoots(isolate).undefined_value());
  AccessorNameGetterCallback f =
      reinterpret_cast<AccessorNameGetterCallback>(info->getter(isolate));
  PREPARE_CALLBACK_INFO_ACCESSOR(
      isolate, f, v8::Value, info, direct_handle(receiver(), isolate),
      ACCESSOR_GETTER, ExceptionContext::kAttributeGet);
  f(v8::Utils::ToLocal(name), callback_info);
  return GetReturnValue<JSAny>(isolate);
}
References AcceptSideEffects(), v8::internal::ACCESSOR_GETTER, v8::internal::direct_handle(), v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::isolate(), v8::kAttributeGet, kPropertyKeyIndex, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::kReturnValueIndex, v8::internal::name, PREPARE_CALLBACK_INFO_ACCESSOR, RCS_SCOPE, receiver(), v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::slot_at(), and v8::internal::FullObjectSlot::store().
CallAccessorSetter()
bool v8::internal::PropertyCallbackArguments::CallAccessorSetter (DirectHandle< AccessorInfo > info, DirectHandle< Name > name, DirectHandle< Object > value) [inline]
Definition at line 435 of file api-arguments-inl.h.
                                {
  Isolate* isolate = this->isolate();
  RCS_SCOPE(isolate, RuntimeCallCounterId::kAccessorSetterCallback);
  // Unlike interceptor callbacks we know that the property exists, so
  // the callback is allowed to have side effects.
  AcceptSideEffects();
  slot_at(kPropertyKeyIndex).store(*name);
  slot_at(kReturnValueIndex).store(ReadOnlyRoots(isolate).true_value());
  // The actual type of setter callback is either
  // v8::AccessorNameSetterCallback or
  // i::Accessors::AccessorNameBooleanSetterCallback, depending on whether the
  // AccessorInfo was created by the API or internally (see accessors.cc).
  // Here we handle both cases using the AccessorNameSetterCallback signature
  // and checking whether the returned result is set to default value
  // (the undefined value).
  // TODO(ishell, 348660658): update V8 Api to allow setter callbacks provide
  // the result of [[Set]] operation according to JavaScript semantics.
  AccessorNameSetterCallback f = reinterpret_cast<AccessorNameSetterCallback>(
      accessor_info->setter(isolate));
  PREPARE_CALLBACK_INFO_ACCESSOR(
      isolate, f, void, accessor_info, direct_handle(receiver(), isolate),
      ACCESSOR_SETTER, ExceptionContext::kAttributeSet);
  f(v8::Utils::ToLocal(name), v8::Utils::ToLocal(value), callback_info);
  // Historically, in case of v8::AccessorNameSetterCallback it wasn't allowed
  // to set the result and not setting the result was treated as successful
  // execution.
  // During interceptors Api refactoring it was temporarily allowed to call
  // v8::ReturnValue<void>::Set[NonEmpty](Local<S>) and the result was just
  // converted to v8::Boolean which was then treated as a result of [[Set]].
  // In case of AccessorNameBooleanSetterCallback, the result is always
  // set to v8::Boolean or an exception is be thrown (in which case the
  // result is ignored anyway). So, regardless of whether the signature was
  // v8::AccessorNameSetterCallback or AccessorNameBooleanSetterCallback
  // the result is guaranteed to be v8::Boolean value indicating success or
  // failure.
  DirectHandle<Boolean> result = GetReturnValue<Boolean>(isolate);
  return IsTrue(*result, isolate);
}
References AcceptSideEffects(), v8::internal::ACCESSOR_SETTER, v8::internal::direct_handle(), v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::isolate(), v8::kAttributeSet, kPropertyKeyIndex, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::kReturnValueIndex, v8::internal::name, PREPARE_CALLBACK_INFO_ACCESSOR, RCS_SCOPE, receiver(), v8::base::internal::result, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::slot_at(), v8::internal::FullObjectSlot::store(), and v8::internal::value.
Referenced by v8::internal::RUNTIME_FUNCTION().
CallIndexedDefiner()
v8::Intercepted v8::internal::PropertyCallbackArguments::CallIndexedDefiner (DirectHandle< InterceptorInfo > interceptor, uint32_t index, const v8::PropertyDescriptor & desc) [inline]
Definition at line 348 of file api-arguments-inl.h.
                                      {
  DCHECK(!interceptor->is_named());
  Isolate* isolate = this->isolate();
  RCS_SCOPE(isolate, RuntimeCallCounterId::kIndexedDefinerCallback);
  index_ = index;
  slot_at(kPropertyKeyIndex).store(Smi::zero()); // indexed callback marker
  slot_at(kReturnValueIndex).store(ReadOnlyRoots(isolate).true_value());
  IndexedPropertyDefinerCallbackV2 f =
      reinterpret_cast<IndexedPropertyDefinerCallbackV2>(
          interceptor->indexed_definer(isolate));
  DirectHandle<InterceptorInfo> has_side_effects;
  PREPARE_CALLBACK_INFO_INTERCEPTOR(isolate, f, void, has_side_effects,
                                    ExceptionContext::kIndexedDefiner);
  v8::Intercepted intercepted = f(index, desc, callback_info);
  return intercepted;
}
References v8::internal::DCHECK(), v8::internal::has_side_effects, v8::internal::index, index_, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::isolate(), v8::kIndexedDefiner, kPropertyKeyIndex, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::kReturnValueIndex, PREPARE_CALLBACK_INFO_INTERCEPTOR, RCS_SCOPE, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::slot_at(), v8::internal::FullObjectSlot::store(), and v8::internal::Smi::zero().
CallIndexedDeleter()
v8::Intercepted v8::internal::PropertyCallbackArguments::CallIndexedDeleter (DirectHandle< InterceptorInfo > interceptor, uint32_t index) [inline]
Definition at line 367 of file api-arguments-inl.h.
                                                               {
  DCHECK(!interceptor->is_named());
  Isolate* isolate = this->isolate();
  RCS_SCOPE(isolate, RuntimeCallCounterId::kIndexedDeleterCallback);
  index_ = index;
  slot_at(kPropertyKeyIndex).store(Smi::zero()); // indexed callback marker
  slot_at(kReturnValueIndex).store(ReadOnlyRoots(isolate).true_value());
  IndexedPropertyDeleterCallbackV2 f =
      reinterpret_cast<IndexedPropertyDeleterCallbackV2>(
          interceptor->indexed_deleter(isolate));
  PREPARE_CALLBACK_INFO_INTERCEPTOR(isolate, f, v8::Boolean, interceptor,
                                    ExceptionContext::kIndexedDeleter);
  v8::Intercepted intercepted = f(index, callback_info);
  return intercepted;
}
References v8::internal::DCHECK(), v8::internal::index, index_, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::isolate(), v8::kIndexedDeleter, kPropertyKeyIndex, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::kReturnValueIndex, PREPARE_CALLBACK_INFO_INTERCEPTOR, RCS_SCOPE, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::slot_at(), v8::internal::FullObjectSlot::store(), and v8::internal::Smi::zero().
CallIndexedDescriptor()
Handle< JSAny > v8::internal::PropertyCallbackArguments::CallIndexedDescriptor (DirectHandle< InterceptorInfo > interceptor, uint32_t index) [inline]
Definition at line 310 of file api-arguments-inl.h.
                                                               {
  DCHECK(!interceptor->is_named());
  Isolate* isolate = this->isolate();
  RCS_SCOPE(isolate, RuntimeCallCounterId::kIndexedDescriptorCallback);
  index_ = index;
  slot_at(kPropertyKeyIndex).store(Smi::zero()); // indexed callback marker
  slot_at(kReturnValueIndex).store(ReadOnlyRoots(isolate).undefined_value());
  IndexedPropertyDescriptorCallbackV2 f =
      reinterpret_cast<IndexedPropertyDescriptorCallbackV2>(
          interceptor->indexed_descriptor(isolate));
  PREPARE_CALLBACK_INFO_INTERCEPTOR(isolate, f, v8::Value, interceptor,
                                    ExceptionContext::kIndexedDescriptor);
  v8::Intercepted intercepted = f(index, callback_info);
  if (intercepted == v8::Intercepted::kNo) return {};
  return GetReturnValue<JSAny>(isolate);
}
References v8::internal::DCHECK(), v8::internal::index, index_, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::isolate(), v8::kIndexedDescriptor, v8::kNo, kPropertyKeyIndex, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::kReturnValueIndex, PREPARE_CALLBACK_INFO_INTERCEPTOR, RCS_SCOPE, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::slot_at(), v8::internal::FullObjectSlot::store(), and v8::internal::Smi::zero().
CallIndexedEnumerator()
DirectHandle< JSObjectOrUndefined > v8::internal::PropertyCallbackArguments::CallIndexedEnumerator (DirectHandle< InterceptorInfo > interceptor) [inline]
Definition at line 266 of file api-arguments-inl.h.
                                               {
  DCHECK(!interceptor->is_named());
  RCS_SCOPE(isolate(), RuntimeCallCounterId::kIndexedEnumeratorCallback);
  return CallPropertyEnumerator(interceptor);
}
References CallPropertyEnumerator(), v8::internal::DCHECK(), v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::isolate(), and RCS_SCOPE.
Referenced by v8::internal::KeyAccumulator::CollectInterceptorKeysInternal().
CallIndexedGetter()
DirectHandle< JSAny > v8::internal::PropertyCallbackArguments::CallIndexedGetter (DirectHandle< InterceptorInfo > interceptor, uint32_t index) [inline]
Definition at line 292 of file api-arguments-inl.h.
                                                               {
  DCHECK(!interceptor->is_named());
  Isolate* isolate = this->isolate();
  RCS_SCOPE(isolate, RuntimeCallCounterId::kNamedGetterCallback);
  index_ = index;
  slot_at(kPropertyKeyIndex).store(Smi::zero()); // indexed callback marker
  slot_at(kReturnValueIndex).store(ReadOnlyRoots(isolate).undefined_value());
  IndexedPropertyGetterCallbackV2 f =
      reinterpret_cast<IndexedPropertyGetterCallbackV2>(
          interceptor->indexed_getter(isolate));
  PREPARE_CALLBACK_INFO_INTERCEPTOR(isolate, f, v8::Value, interceptor,
                                    ExceptionContext::kIndexedGetter);
  v8::Intercepted intercepted = f(index, callback_info);
  if (intercepted == v8::Intercepted::kNo) return {};
  return GetReturnValue<JSAny>(isolate);
}
References v8::internal::DCHECK(), v8::internal::index, index_, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::isolate(), v8::kIndexedGetter, v8::kNo, kPropertyKeyIndex, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::kReturnValueIndex, PREPARE_CALLBACK_INFO_INTERCEPTOR, RCS_SCOPE, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::slot_at(), v8::internal::FullObjectSlot::store(), and v8::internal::Smi::zero().
Referenced by v8::internal::RUNTIME_FUNCTION().
CallIndexedQuery()
DirectHandle< Object > v8::internal::PropertyCallbackArguments::CallIndexedQuery (DirectHandle< InterceptorInfo > interceptor, uint32_t index) [inline]
Definition at line 274 of file api-arguments-inl.h.
                                                               {
  DCHECK(!interceptor->is_named());
  Isolate* isolate = this->isolate();
  RCS_SCOPE(isolate, RuntimeCallCounterId::kIndexedQueryCallback);
  index_ = index;
  slot_at(kPropertyKeyIndex).store(Smi::zero()); // indexed callback marker
  slot_at(kReturnValueIndex).store(Smi::FromInt(v8::None));
  IndexedPropertyQueryCallbackV2 f =
      reinterpret_cast<IndexedPropertyQueryCallbackV2>(
          interceptor->indexed_query(isolate));
  PREPARE_CALLBACK_INFO_INTERCEPTOR(isolate, f, v8::Integer, interceptor,
                                    ExceptionContext::kIndexedQuery);
  v8::Intercepted intercepted = f(index, callback_info);
  if (intercepted == v8::Intercepted::kNo) return {};
  return GetReturnValue<Object>(isolate);
}
References v8::internal::DCHECK(), v8::internal::Smi::FromInt(), v8::internal::index, index_, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::isolate(), v8::kIndexedQuery, v8::kNo, kPropertyKeyIndex, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::kReturnValueIndex, v8::None, PREPARE_CALLBACK_INFO_INTERCEPTOR, RCS_SCOPE, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::slot_at(), v8::internal::FullObjectSlot::store(), and v8::internal::Smi::zero().
Referenced by v8::internal::RUNTIME_FUNCTION().
CallIndexedSetter()
v8::Intercepted v8::internal::PropertyCallbackArguments::CallIndexedSetter (DirectHandle< InterceptorInfo > interceptor, uint32_t index, DirectHandle< Object > value) [inline]
Definition at line 328 of file api-arguments-inl.h.
                                {
  DCHECK(!interceptor->is_named());
  Isolate* isolate = this->isolate();
  RCS_SCOPE(isolate, RuntimeCallCounterId::kIndexedSetterCallback);
  index_ = index;
  slot_at(kPropertyKeyIndex).store(Smi::zero()); // indexed callback marker
  slot_at(kReturnValueIndex).store(ReadOnlyRoots(isolate).true_value());
  IndexedPropertySetterCallbackV2 f =
      reinterpret_cast<IndexedPropertySetterCallbackV2>(
          interceptor->indexed_setter(isolate));
  DirectHandle<InterceptorInfo> has_side_effects;
  PREPARE_CALLBACK_INFO_INTERCEPTOR(isolate, f, void, has_side_effects,
                                    ExceptionContext::kIndexedSetter);
  v8::Intercepted intercepted =
      f(index, v8::Utils::ToLocal(value), callback_info);
  return intercepted;
}
References v8::internal::DCHECK(), v8::internal::has_side_effects, v8::internal::index, index_, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::isolate(), v8::kIndexedSetter, kPropertyKeyIndex, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::kReturnValueIndex, PREPARE_CALLBACK_INFO_INTERCEPTOR, RCS_SCOPE, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::slot_at(), v8::internal::FullObjectSlot::store(), v8::internal::value, and v8::internal::Smi::zero().
CallNamedDefiner()
v8::Intercepted v8::internal::PropertyCallbackArguments::CallNamedDefiner (DirectHandle< InterceptorInfo > interceptor, DirectHandle< Name > name, const v8::PropertyDescriptor & desc) [inline]
Definition at line 226 of file api-arguments-inl.h.
                                      {
  DCHECK_NAME_COMPATIBLE(interceptor, name);
  Isolate* isolate = this->isolate();
  RCS_SCOPE(isolate, RuntimeCallCounterId::kNamedDefinerCallback);
  slot_at(kPropertyKeyIndex).store(*name);
  slot_at(kReturnValueIndex).store(ReadOnlyRoots(isolate).true_value());
  NamedPropertyDefinerCallback f =
      reinterpret_cast<NamedPropertyDefinerCallback>(
          interceptor->named_definer(isolate));
  DirectHandle<InterceptorInfo> has_side_effects;
  PREPARE_CALLBACK_INFO_INTERCEPTOR(isolate, f, void, has_side_effects,
                                    ExceptionContext::kNamedDefiner);
  v8::Intercepted intercepted =
      f(v8::Utils::ToLocal(name), desc, callback_info);
  return intercepted;
}
References DCHECK_NAME_COMPATIBLE, v8::internal::has_side_effects, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::isolate(), v8::kNamedDefiner, kPropertyKeyIndex, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::kReturnValueIndex, v8::internal::name, PREPARE_CALLBACK_INFO_INTERCEPTOR, RCS_SCOPE, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::slot_at(), and v8::internal::FullObjectSlot::store().
CallNamedDeleter()
v8::Intercepted v8::internal::PropertyCallbackArguments::CallNamedDeleter (DirectHandle< InterceptorInfo > interceptor, DirectHandle< Name > name) [inline]
Definition at line 245 of file api-arguments-inl.h.
                                                                        {
  DCHECK_NAME_COMPATIBLE(interceptor, name);
  Isolate* isolate = this->isolate();
  RCS_SCOPE(isolate, RuntimeCallCounterId::kNamedDeleterCallback);
  slot_at(kPropertyKeyIndex).store(*name);
  slot_at(kReturnValueIndex).store(ReadOnlyRoots(isolate).true_value());
  NamedPropertyDeleterCallback f =
      reinterpret_cast<NamedPropertyDeleterCallback>(
          interceptor->named_deleter(isolate));
  DirectHandle<InterceptorInfo> has_side_effects;
  PREPARE_CALLBACK_INFO_INTERCEPTOR(isolate, f, v8::Boolean, has_side_effects,
                                    ExceptionContext::kNamedDeleter);
  v8::Intercepted intercepted = f(v8::Utils::ToLocal(name), callback_info);
  return intercepted;
}
References DCHECK_NAME_COMPATIBLE, v8::internal::has_side_effects, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::isolate(), v8::kNamedDeleter, kPropertyKeyIndex, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::kReturnValueIndex, v8::internal::name, PREPARE_CALLBACK_INFO_INTERCEPTOR, RCS_SCOPE, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::slot_at(), and v8::internal::FullObjectSlot::store().
CallNamedDescriptor()
Handle< JSAny > v8::internal::PropertyCallbackArguments::CallNamedDescriptor (DirectHandle< InterceptorInfo > interceptor, DirectHandle< Name > name) [inline]
Definition at line 191 of file api-arguments-inl.h.
                                                                        {
  DCHECK_NAME_COMPATIBLE(interceptor, name);
  Isolate* isolate = this->isolate();
  RCS_SCOPE(isolate, RuntimeCallCounterId::kNamedDescriptorCallback);
  slot_at(kPropertyKeyIndex).store(*name);
  slot_at(kReturnValueIndex).store(ReadOnlyRoots(isolate).undefined_value());
  NamedPropertyDescriptorCallback f =
      reinterpret_cast<NamedPropertyDescriptorCallback>(
          interceptor->named_descriptor(isolate));
  PREPARE_CALLBACK_INFO_INTERCEPTOR(isolate, f, v8::Value, interceptor,
                                    ExceptionContext::kNamedDescriptor);
  v8::Intercepted intercepted = f(v8::Utils::ToLocal(name), callback_info);
  if (intercepted == v8::Intercepted::kNo) return {};
  return GetReturnValue<JSAny>(isolate);
}
References DCHECK_NAME_COMPATIBLE, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::isolate(), v8::kNamedDescriptor, v8::kNo, kPropertyKeyIndex, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::kReturnValueIndex, v8::internal::name, PREPARE_CALLBACK_INFO_INTERCEPTOR, RCS_SCOPE, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::slot_at(), and v8::internal::FullObjectSlot::store().
CallNamedEnumerator()
DirectHandle< JSObjectOrUndefined > v8::internal::PropertyCallbackArguments::CallNamedEnumerator (DirectHandle< InterceptorInfo > interceptor) [inline]
Definition at line 151 of file api-arguments-inl.h.
                                               {
  DCHECK(interceptor->is_named());
  RCS_SCOPE(isolate(), RuntimeCallCounterId::kNamedEnumeratorCallback);
  return CallPropertyEnumerator(interceptor);
}
References CallPropertyEnumerator(), v8::internal::DCHECK(), v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::isolate(), and RCS_SCOPE.
Referenced by v8::internal::KeyAccumulator::CollectInterceptorKeysInternal().
CallNamedGetter()
DirectHandle< JSAny > v8::internal::PropertyCallbackArguments::CallNamedGetter (DirectHandle< InterceptorInfo > interceptor, DirectHandle< Name > name) [inline]
Definition at line 175 of file api-arguments-inl.h.
                                                                        {
  DCHECK_NAME_COMPATIBLE(interceptor, name);
  Isolate* isolate = this->isolate();
  RCS_SCOPE(isolate, RuntimeCallCounterId::kNamedGetterCallback);
  slot_at(kPropertyKeyIndex).store(*name);
  slot_at(kReturnValueIndex).store(ReadOnlyRoots(isolate).undefined_value());
  NamedPropertyGetterCallback f = reinterpret_cast<NamedPropertyGetterCallback>(
      interceptor->named_getter(isolate));
  PREPARE_CALLBACK_INFO_INTERCEPTOR(isolate, f, v8::Value, interceptor,
                                    ExceptionContext::kNamedGetter);
  v8::Intercepted intercepted = f(v8::Utils::ToLocal(name), callback_info);
  if (intercepted == v8::Intercepted::kNo) return {};
  return GetReturnValue<JSAny>(isolate);
}
References DCHECK_NAME_COMPATIBLE, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::isolate(), v8::kNamedGetter, v8::kNo, kPropertyKeyIndex, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::kReturnValueIndex, v8::internal::name, PREPARE_CALLBACK_INFO_INTERCEPTOR, RCS_SCOPE, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::slot_at(), and v8::internal::FullObjectSlot::store().
Referenced by v8::internal::RUNTIME_FUNCTION().
CallNamedQuery()
DirectHandle< Object > v8::internal::PropertyCallbackArguments::CallNamedQuery (DirectHandle< InterceptorInfo > interceptor, DirectHandle< Name > name) [inline]
Definition at line 159 of file api-arguments-inl.h.
                                                                        {
  DCHECK_NAME_COMPATIBLE(interceptor, name);
  Isolate* isolate = this->isolate();
  RCS_SCOPE(isolate, RuntimeCallCounterId::kNamedQueryCallback);
  slot_at(kPropertyKeyIndex).store(*name);
  slot_at(kReturnValueIndex).store(Smi::FromInt(v8::None));
  NamedPropertyQueryCallback f = reinterpret_cast<NamedPropertyQueryCallback>(
      interceptor->named_query(isolate));
  PREPARE_CALLBACK_INFO_INTERCEPTOR(isolate, f, v8::Integer, interceptor,
                                    ExceptionContext::kNamedQuery);
  v8::Intercepted intercepted = f(v8::Utils::ToLocal(name), callback_info);
  if (intercepted == v8::Intercepted::kNo) return {};
  return GetReturnValue<Object>(isolate);
}
References DCHECK_NAME_COMPATIBLE, v8::internal::Smi::FromInt(), v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::isolate(), v8::kNamedQuery, v8::kNo, kPropertyKeyIndex, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::kReturnValueIndex, v8::internal::name, v8::None, PREPARE_CALLBACK_INFO_INTERCEPTOR, RCS_SCOPE, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::slot_at(), and v8::internal::FullObjectSlot::store().
CallNamedSetter()
v8::Intercepted v8::internal::PropertyCallbackArguments::CallNamedSetter (DirectHandle< InterceptorInfo > interceptor, DirectHandle< Name > name, DirectHandle< Object > value) [inline]
Definition at line 208 of file api-arguments-inl.h.
                                {
  DCHECK_NAME_COMPATIBLE(interceptor, name);
  Isolate* isolate = this->isolate();
  RCS_SCOPE(isolate, RuntimeCallCounterId::kNamedSetterCallback);
  slot_at(kPropertyKeyIndex).store(*name);
  slot_at(kReturnValueIndex).store(ReadOnlyRoots(isolate).true_value());
  NamedPropertySetterCallback f = reinterpret_cast<NamedPropertySetterCallback>(
      interceptor->named_setter(isolate));
  DirectHandle<InterceptorInfo> has_side_effects;
  PREPARE_CALLBACK_INFO_INTERCEPTOR(isolate, f, void, has_side_effects,
                                    ExceptionContext::kNamedSetter);
  v8::Intercepted intercepted =
      f(v8::Utils::ToLocal(name), v8::Utils::ToLocal(value), callback_info);
  return intercepted;
}
References DCHECK_NAME_COMPATIBLE, v8::internal::has_side_effects, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::isolate(), v8::kNamedSetter, kPropertyKeyIndex, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::kReturnValueIndex, v8::internal::name, PREPARE_CALLBACK_INFO_INTERCEPTOR, RCS_SCOPE, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::slot_at(), v8::internal::FullObjectSlot::store(), and v8::internal::value.
Referenced by v8::internal::RUNTIME_FUNCTION().
CallPropertyEnumerator()
DirectHandle< JSObjectOrUndefined > v8::internal::PropertyCallbackArguments::CallPropertyEnumerator (DirectHandle< InterceptorInfo > interceptor) [inline], [private]
Definition at line 385 of file api-arguments-inl.h.
                                               {
  // Named and indexed enumerator callbacks have same signatures.
  static_assert(std::is_same_v<NamedPropertyEnumeratorCallback,
                               IndexedPropertyEnumeratorCallback>);
  Isolate* isolate = this->isolate();
  slot_at(kPropertyKeyIndex).store(Smi::zero()); // not relevant
  // Enumerator callback's return value is initialized with undefined even
  // though it's supposed to return v8::Array.
  slot_at(kReturnValueIndex).store(ReadOnlyRoots(isolate).undefined_value());
  // TODO(ishell): consider making it return v8::Intercepted to indicate
  // whether the result was set or not.
  IndexedPropertyEnumeratorCallback f;
  if (interceptor->is_named()) {
    f = reinterpret_cast<NamedPropertyEnumeratorCallback>(
        interceptor->named_enumerator(isolate));
  } else {
    f = reinterpret_cast<IndexedPropertyEnumeratorCallback>(
        interceptor->indexed_enumerator(isolate));
  }
  PREPARE_CALLBACK_INFO_INTERCEPTOR(isolate, f, v8::Array, interceptor,
                                    ExceptionContext::kNamedEnumerator);
  f(callback_info);
  DirectHandle<JSAny> result = GetReturnValue<JSAny>(isolate);
  DCHECK(IsUndefined(*result) || IsJSObject(*result));
  return Cast<JSObjectOrUndefined>(result);
}
References v8::internal::DCHECK(), v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::isolate(), v8::kNamedEnumerator, kPropertyKeyIndex, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::kReturnValueIndex, PREPARE_CALLBACK_INFO_INTERCEPTOR, v8::base::internal::result, v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::slot_at(), v8::internal::FullObjectSlot::store(), and v8::internal::Smi::zero().
Referenced by CallIndexedEnumerator(), and CallNamedEnumerator().
GetBooleanReturnValue()
Maybe< InterceptorResult > v8::internal::PropertyCallbackArguments::GetBooleanReturnValue (v8::Intercepted intercepted, const char * callback_kind_for_error_message, bool ignore_return_value = false) [inline]
Definition at line 108 of file api-arguments-inl.h.
                              {
  Isolate* isolate = this->isolate();
  if (isolate->has_exception()) {
    // TODO(ishell, 328490288): fix Node.js which has Setter/Definer
    // interceptor callbacks not returning v8::Intercepted::kYes on exceptions.
    if ((false) && DEBUG_BOOL && (intercepted == v8::Intercepted::kNo)) {
      FATAL(
          "Check failed: %s interceptor callback has thrown an "
          "exception but hasn't returned v8::Intercepted::kYes.",
          callback_kind_for_error_message);
    }
    return Nothing<InterceptorResult>();
  }
  if (intercepted == v8::Intercepted::kNo) {
    // Not intercepted, there must be no side effects including exceptions.
    DCHECK(!isolate->has_exception());
    return Just(InterceptorResult::kNotIntercepted);
  }
  DCHECK_EQ(intercepted, v8::Intercepted::kYes);
  AcceptSideEffects();
  if (ignore_return_value) return Just(InterceptorResult::kTrue);
  bool result = IsTrue(*GetReturnValue<Boolean>(isolate), isolate);
  // TODO(ishell, 348688196): ensure callbacks comply with this and
  // enable the check.
  if ((false) && DEBUG_BOOL && !result && ShouldThrowOnError()) {
    FATAL(
        "Check failed: %s interceptor callback hasn't thrown an "
        "exception on failure as requested.",
        callback_kind_for_error_message);
  }
  return Just(result ? InterceptorResult::kTrue : InterceptorResult::kFalse);
}
References AcceptSideEffects(), v8::internal::DCHECK(), DCHECK_EQ, DEBUG_BOOL, FATAL, v8::internal::Isolate::has_exception(), v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::isolate(), v8::Just(), v8::internal::kFalse, v8::kNo, v8::internal::kNotIntercepted, v8::internal::kTrue, v8::kYes, v8::base::internal::result, and ShouldThrowOnError().
Referenced by v8::internal::RUNTIME_FUNCTION().
GetPropertyCallbackInfo()
template<typename T >
const v8::PropertyCallbackInfo<T>& v8::internal::PropertyCallbackArguments::GetPropertyCallbackInfo () [inline]
Definition at line 197 of file api-arguments.h.
                                                             {
    return *(reinterpret_cast<PropertyCallbackInfo<T>*>(&values_[0]));
  }
References v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::values_.
GetPropertyIndex()
template<typename T >
static uint32_t v8::internal::PropertyCallbackArguments::GetPropertyIndex (const PropertyCallbackInfo< T > & info) [inline], [static]
Definition at line 222 of file api-arguments.h.
                                                                        {
    // Currently all indexed interceptor callbacks are called via
    // PropertyCallbackArguments, so it's guaranteed that
    // v8::PropertyCallbackInfo<T>::args_ array IS the
    // PropertyCallbackArguments::values_ array. As a result we can restore
    // pointer to PropertyCallbackArguments object from the former.
    Address ptr = reinterpret_cast<Address>(&info.args_) -
                  offsetof(PropertyCallbackArguments, values_);
    auto pca = reinterpret_cast<const PropertyCallbackArguments*>(ptr);
    return pca->index_;
  }
References v8::PropertyCallbackInfo< T >::args_, index_, and v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::values_.
Referenced by v8::internal::Isolate::NotifyExceptionPropagationCallback().
GetPropertyKey()
template<typename T >
static Tagged<Object> v8::internal::PropertyCallbackArguments::GetPropertyKey (const PropertyCallbackInfo< T > & info) [inline], [static]
Definition at line 209 of file api-arguments.h.
                                                                            {
    return Tagged<Object>(info.args_[kPropertyKeyIndex]);
  }
References v8::PropertyCallbackInfo< T >::args_, kPropertyKeyIndex, and v8::internal::Tagged< Object >.
Referenced by v8::internal::ValidatePropertyCallbackInfo().
GetPropertyKeyHandle()
template<typename T >
static Handle<Object> v8::internal::PropertyCallbackArguments::GetPropertyKeyHandle (const PropertyCallbackInfo< T > & info) [inline], [static]
Definition at line 213 of file api-arguments.h.
                                           {
    return Handle<Object>(&info.args_[kPropertyKeyIndex]);
  }
References v8::PropertyCallbackInfo< T >::args_, and kPropertyKeyIndex.
Referenced by v8::internal::Isolate::NotifyExceptionPropagationCallback().
holder()
Tagged< JSObject > v8::internal::PropertyCallbackArguments::holder () const [inline], [private]
Definition at line 39 of file api-arguments-inl.h.
                                                                {
  return Cast<JSObject>(*slot_at(T::kHolderIndex));
}
References v8::PropertyCallbackInfo< T >::kHolderIndex, and v8::internal::CustomArguments< PropertyCallbackInfo< Value > >::slot_at().
Referenced by PropertyCallbackArguments().
operator=()
PropertyCallbackArguments& v8::internal::PropertyCallbackArguments::operator= (const PropertyCallbackArguments &) [delete]
receiver()
Tagged< Object > v8::internal::PropertyCallbackArguments::receiver () const [inline], [private]
Definition at line 43 of file api-arguments-inl.h.
                                                                {
  return *slot_at(T::kThisIndex);
}
Referenced by CallAccessorGetter(), and CallAccessorSetter().
ShouldThrowOnError()
bool v8::internal::PropertyCallbackArguments::ShouldThrowOnError () [inline]
Definition at line 203 of file api-arguments.h.
                            {
    return GetPropertyCallbackInfo<Value>().ShouldThrowOnError();
  }
Referenced by GetBooleanReturnValue().
Member Data Documentation
index_
uint32_t v8::internal::PropertyCallbackArguments::index_ = kMaxUInt32 [private]
Definition at line 244 of file api-arguments.h.
Referenced by CallIndexedDefiner(), CallIndexedDeleter(), CallIndexedDescriptor(), CallIndexedGetter(), CallIndexedQuery(), CallIndexedSetter(), and GetPropertyIndex().
kArgsLength
constexpr int v8::internal::PropertyCallbackArguments::kArgsLength = T::kArgsLength [static], [constexpr]
Definition at line 75 of file api-arguments.h.
kDataIndex
constexpr int v8::internal::PropertyCallbackArguments::kDataIndex = T::kDataIndex [static], [constexpr]
Definition at line 77 of file api-arguments.h.
kHolderIndex
constexpr int v8::internal::PropertyCallbackArguments::kHolderIndex = T::kHolderIndex [static], [constexpr]
Definition at line 79 of file api-arguments.h.
kHolderV2Index
constexpr int v8::internal::PropertyCallbackArguments::kHolderV2Index = T::kHolderV2Index [static], [constexpr]
Definition at line 78 of file api-arguments.h.
kIsolateIndex
constexpr int v8::internal::PropertyCallbackArguments::kIsolateIndex = T::kIsolateIndex [static], [constexpr]
Definition at line 80 of file api-arguments.h.
kPropertyKeyIndex
constexpr int v8::internal::PropertyCallbackArguments::kPropertyKeyIndex = T::kPropertyKeyIndex [static], [constexpr]
Definition at line 82 of file api-arguments.h.
Referenced by CallAccessorGetter(), CallAccessorSetter(), CallIndexedDefiner(), CallIndexedDeleter(), CallIndexedDescriptor(), CallIndexedGetter(), CallIndexedQuery(), CallIndexedSetter(), CallNamedDefiner(), CallNamedDeleter(), CallNamedDescriptor(), CallNamedGetter(), CallNamedQuery(), CallNamedSetter(), CallPropertyEnumerator(), GetPropertyKey(), and GetPropertyKeyHandle().
kShouldThrowOnErrorIndex
constexpr int v8::internal::PropertyCallbackArguments::kShouldThrowOnErrorIndex = T::kShouldThrowOnErrorIndex [static], [constexpr]
Definition at line 81 of file api-arguments.h.
kThisIndex
constexpr int v8::internal::PropertyCallbackArguments::kThisIndex = T::kThisIndex [static], [constexpr]
Definition at line 76 of file api-arguments.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/api/api-arguments.h
/mnt/V8SourceCode/src/api/api-arguments-inl.h
/mnt/V8SourceCode/src/api/api-arguments.cc