v8::internal::compiler::MapRef Class Reference
#include <heap-refs.h>
Public Member Functions
IndirectHandle< Map > object () const
int instance_size () const
InstanceType instance_type () const
int GetInObjectProperties () const
int GetInObjectPropertiesStartInWords () const
int NumberOfOwnDescriptors () const
int GetInObjectPropertyOffset (int index) const
int constructor_function_index () const
int NextFreePropertyIndex () const
int UnusedPropertyFields () const
ElementsKind elements_kind () const
bool is_stable () const
bool is_constructor () const
bool has_prototype_slot () const
bool is_access_check_needed () const
bool is_deprecated () const
bool CanBeDeprecated () const
bool CanTransition () const
bool IsInobjectSlackTrackingInProgress () const
bool is_dictionary_map () const
bool IsFixedCowArrayMap (JSHeapBroker *broker) const
bool IsPrimitiveMap () const
bool is_undetectable () const
bool is_callable () const
bool has_indexed_interceptor () const
bool has_named_interceptor () const
int construction_counter () const
bool is_migration_target () const
bool is_extensible () const
bool supports_fast_array_iteration (JSHeapBroker *broker) const
bool supports_fast_array_resize (JSHeapBroker *broker) const
bool is_abandoned_prototype_map () const
bool IsOneByteStringMap () const
bool IsTwoByteStringMap () const
bool IsSeqStringMap () const
bool IsThinStringMap () const
bool IsStringWrapperMap () const
OddballType oddball_type (JSHeapBroker *broker) const
bool CanInlineElementAccess () const
OptionalMapRef AsElementsKind (JSHeapBroker *broker, ElementsKind kind) const
bool IsBooleanMap (JSHeapBroker *broker) const
bool IsNullMap (JSHeapBroker *broker) const
bool IsUndefinedMap (JSHeapBroker *broker) const
HeapObjectRef GetBackPointer (JSHeapBroker *broker) const
HeapObjectRef prototype (JSHeapBroker *broker) const
bool PrototypesElementsDoNotHaveAccessorsOrThrow (JSHeapBroker *broker, ZoneVector< MapRef > *prototype_maps)
DescriptorArrayRef instance_descriptors (JSHeapBroker *broker) const
MapRef FindFieldOwner (JSHeapBroker *broker, InternalIndex descriptor_index) const
PropertyDetails GetPropertyDetails (JSHeapBroker *broker, InternalIndex descriptor_index) const
NameRef GetPropertyKey (JSHeapBroker *broker, InternalIndex descriptor_index) const
FieldIndex GetFieldIndexFor (InternalIndex descriptor_index) const
OptionalObjectRef GetStrongValue (JSHeapBroker *broker, InternalIndex descriptor_number) const
MapRef FindRootMap (JSHeapBroker *broker) const
ObjectRef GetConstructor (JSHeapBroker *broker) const
Detailed Description
Definition at line 897 of file heap-refs.h.
Member Function Documentation
AsElementsKind()
OptionalMapRef v8::internal::compiler::MapRef::AsElementsKind (JSHeapBroker * broker, ElementsKind kind) const
Definition at line 1196 of file heap-refs.cc.
                                                               {
  const ElementsKind current_kind = elements_kind();
  if (kind == current_kind) return *this;
#ifdef DEBUG
  // If starting from an initial JSArray map, TryAsElementsKind must succeed
  // and return the expected transitioned JSArray map.
  NativeContextRef native_context = broker->target_native_context();
  if (equals(native_context.GetInitialJSArrayMap(broker, current_kind))) {
    // Note that GetInitialJSArrayMap can park the current scope, which can
    // trigger a GC, which means that everything above this point that isn't in
    // a Handle could be invalidated.
    Tagged<Map> initial_js_array_map =
        *native_context.GetInitialJSArrayMap(broker, kind).object();
    Tagged<Map> as_elements_kind_map =
        Map::TryAsElementsKind(broker->isolate(), object(), kind,
                               ConcurrencyMode::kConcurrent)
            .value();
    CHECK_EQ(as_elements_kind_map, initial_js_array_map);
  }
#endif // DEBUG
  std::optional<Tagged<Map>> maybe_result = Map::TryAsElementsKind(
      broker->isolate(), object(), kind, ConcurrencyMode::kConcurrent);
  if (!maybe_result.has_value()) {
    TRACE_BROKER_MISSING(broker, "MapRef::AsElementsKind " << *this);
    return {};
  }
  return MakeRefAssumeMemoryFence(broker, maybe_result.value());
}
References broker(), CHECK_EQ, elements_kind(), v8::internal::kConcurrent, v8::internal::compiler::MakeRefAssumeMemoryFence(), v8::internal::native_context, TRACE_BROKER_MISSING, and v8::internal::Map::TryAsElementsKind().
CanBeDeprecated()
bool v8::internal::compiler::MapRef::CanBeDeprecated () const
Definition at line 1885 of file heap-refs.cc.
{ return object()->CanBeDeprecated(); }
References object().
Referenced by v8::internal::compiler::CompilationDependencies::TransitionDependencyOffTheRecord().
CanInlineElementAccess()
bool v8::internal::compiler::MapRef::CanInlineElementAccess () const
Definition at line 1178 of file heap-refs.cc.
                                          {
  if (!IsJSObjectMap()) return false;
  if (is_access_check_needed()) return false;
  if (has_indexed_interceptor()) return false;
  ElementsKind kind = elements_kind();
  if (IsFastElementsKind(kind)) return true;
  if (IsTypedArrayElementsKind(kind) &&
      (Is64() || (kind != BIGINT64_ELEMENTS && kind != BIGUINT64_ELEMENTS))) {
    return true;
  }
  if (IsRabGsabTypedArrayElementsKind(kind) &&
      kind != RAB_GSAB_BIGUINT64_ELEMENTS &&
      kind != RAB_GSAB_BIGINT64_ELEMENTS) {
    return true;
  }
  return false;
}
References elements_kind(), has_indexed_interceptor(), v8::internal::Is64(), is_access_check_needed(), v8::internal::IsFastElementsKind(), v8::internal::IsRabGsabTypedArrayElementsKind(), and v8::internal::IsTypedArrayElementsKind().
Referenced by v8::internal::compiler::AccessInfoFactory::ComputeElementAccessInfo().
CanTransition()
bool v8::internal::compiler::MapRef::CanTransition () const
Definition at line 1887 of file heap-refs.cc.
{ return object()->CanTransition(); }
References object().
Referenced by v8::internal::compiler::CompilationDependencies::DependOnStableMap().
construction_counter()
int v8::internal::compiler::MapRef::construction_counter () const
Referenced by v8::internal::compiler::CompilationDependencies::DependOnNoSlackTrackingChange(), and IsInobjectSlackTrackingInProgress().
constructor_function_index()
int v8::internal::compiler::MapRef::constructor_function_index () const
Definition at line 1876 of file heap-refs.cc.
                                             {
  return object()->GetConstructorFunctionIndex();
}
References object().
Referenced by v8::internal::compiler::NativeContextRef::GetConstructorFunction().
elements_kind()
ElementsKind v8::internal::compiler::MapRef::elements_kind () const
Referenced by AsElementsKind(), CanInlineElementAccess(), v8::internal::compiler::AccessInfoFactory::ComputeElementAccessInfo(), v8::internal::compiler::LoadElimination::ComputeLoopState(), v8::internal::compiler::AccessInfoFactory::ConsolidateElementLoad(), v8::internal::compiler::JSTypedArrayRef::elements_kind(), v8::internal::compiler::HeapObjectRef::GetHeapObjectType(), v8::internal::compiler::JSArrayRef::GetOwnCowElement(), v8::internal::compiler::JSPrimitiveWrapperRef::IsStringWrapper(), IsStringWrapperMap(), v8::internal::compiler::AccessInfoFactory::LookupSpecialFieldAccessor(), v8::internal::compiler::AccessInfoFactory::LookupSpecialFieldAccessorInHolder(), PrototypesElementsDoNotHaveAccessorsOrThrow(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypePush(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpread(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccess(), v8::internal::compiler::LoadElimination::ReduceTransitionElementsKindOrCheckMap(), v8::internal::compiler::turboshaft::TurbolevEarlyLoweringReducer< Next >::TransitionElementsKind(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::TransitionElementsKindOrCheckMap(), v8::internal::maglev::MaglevGraphBuilder::TryReduceConstructArrayConstructor(), and v8::internal::compiler::PropertyAccessInfo::TypedArrayLength().
FindFieldOwner()
MapRef v8::internal::compiler::MapRef::FindFieldOwner (JSHeapBroker * broker, InternalIndex descriptor_index) const
Definition at line 1387 of file heap-refs.cc.
                                                                    {
  CHECK_LT(descriptor_index.as_int(), NumberOfOwnDescriptors());
  // TODO(solanes, v8:7790): Consider caching the result of the field owner on
  // the descriptor array. It would be useful for same map as well as any
  // other map sharing that descriptor array.
  return MakeRefAssumeMemoryFence(
      broker, object()->FindFieldOwner(broker->cage_base(), descriptor_index));
}
References v8::internal::InternalIndex::as_int(), broker(), CHECK_LT, v8::internal::compiler::MakeRefAssumeMemoryFence(), and NumberOfOwnDescriptors().
Referenced by v8::internal::compiler::AccessInfoFactory::ComputeDataFieldAccessInfo(), and v8::internal::compiler::AccessInfoFactory::LookupTransition().
FindRootMap()
MapRef v8::internal::compiler::MapRef::FindRootMap (JSHeapBroker * broker) const
Definition at line 1813 of file heap-refs.cc.
                                                     {
  // TODO(solanes, v8:7790): Consider caching the result of the root map.
  return MakeRefAssumeMemoryFence(broker,
                                  object()->FindRootMap(broker->cage_base()));
}
References broker(), and v8::internal::compiler::MakeRefAssumeMemoryFence().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::InferRootMap().
GetBackPointer()
HeapObjectRef v8::internal::compiler::MapRef::GetBackPointer (JSHeapBroker * broker) const
Definition at line 1824 of file heap-refs.cc.
                                                               {
  // Immutable after initialization.
  return MakeRefAssumeMemoryFence(broker,
                                  Cast<HeapObject>(object()->GetBackPointer()));
}
References broker(), and v8::internal::compiler::MakeRefAssumeMemoryFence().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyStore(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildStoreField().
GetConstructor()
ObjectRef v8::internal::compiler::MapRef::GetConstructor (JSHeapBroker * broker) const
Definition at line 1819 of file heap-refs.cc.
                                                           {
  // Immutable after initialization.
  return MakeRefAssumeMemoryFence(broker, object()->GetConstructor());
}
References broker(), and v8::internal::compiler::MakeRefAssumeMemoryFence().
Referenced by v8::internal::maglev::MaglevGraphBuilder::TryReduceConstructGeneric().
GetFieldIndexFor()
FieldIndex v8::internal::compiler::MapRef::GetFieldIndexFor (InternalIndex descriptor_index) const
Definition at line 1354 of file heap-refs.cc.
                                                                        {
  CHECK_LT(descriptor_index.as_int(), NumberOfOwnDescriptors());
  FieldIndex result = FieldIndex::ForDescriptor(*object(), descriptor_index);
  DCHECK(result.is_inobject());
  return result;
}
References v8::internal::InternalIndex::as_int(), CHECK_LT, v8::internal::DCHECK(), v8::internal::FieldIndex::ForDescriptor(), NumberOfOwnDescriptors(), and v8::base::internal::result.
GetInObjectProperties()
int v8::internal::compiler::MapRef::GetInObjectProperties () const
Definition at line 1893 of file heap-refs.cc.
                                        {
  IF_ACCESS_FROM_HEAP_C(GetInObjectProperties);
  return data()->AsMap()->in_object_properties();
}
References IF_ACCESS_FROM_HEAP_C.
Referenced by v8::internal::compiler::JSCallReducerAssembler::AllocateEmptyJSArray(), v8::internal::maglev::MaglevGraphBuilder::BuildExtendPropertiesBackingStore(), v8::internal::compiler::JSNativeContextSpecialization::BuildExtendPropertiesBackingStore(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateEmptyLiteralObject(), v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral(), and v8::internal::maglev::MaglevGraphBuilder::TryReadBoilerplateForFastLiteral().
GetInObjectPropertiesStartInWords()
int v8::internal::compiler::MapRef::GetInObjectPropertiesStartInWords () const
Definition at line 1889 of file heap-refs.cc.
                                                    {
  return object()->GetInObjectPropertiesStartInWords();
}
References object().
GetInObjectPropertyOffset()
int v8::internal::compiler::MapRef::GetInObjectPropertyOffset (int index) const
Definition at line 1361 of file heap-refs.cc.
                                                 {
  return object()->GetInObjectPropertyOffset(i);
}
References object().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildAndAllocateJSArray(), v8::internal::compiler::AccessBuilder::ForJSObjectInObjectProperty(), and v8::internal::maglev::MaglevGraphBuilder::TryReadBoilerplateForFastLiteral().
GetPropertyDetails()
PropertyDetails v8::internal::compiler::MapRef::GetPropertyDetails (JSHeapBroker * broker, InternalIndex descriptor_index) const
Definition at line 1365 of file heap-refs.cc.
                                                                {
  CHECK_LT(descriptor_index.as_int(), NumberOfOwnDescriptors());
  return instance_descriptors(broker).GetPropertyDetails(descriptor_index);
}
References v8::internal::InternalIndex::as_int(), broker(), CHECK_LT, v8::internal::compiler::DescriptorArrayRef::GetPropertyDetails(), instance_descriptors(), and NumberOfOwnDescriptors().
Referenced by v8::internal::compiler::AccessInfoFactory::ComputeDataFieldAccessInfo(), v8::internal::compiler::CompilationDependencies::DependOnFieldConstness(), v8::internal::compiler::CompilationDependencies::FieldConstnessDependencyOffTheRecord(), v8::internal::compiler::AccessInfoFactory::LookupTransition(), v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral(), and v8::internal::maglev::MaglevGraphBuilder::TryReadBoilerplateForFastLiteral().
GetPropertyKey()
NameRef v8::internal::compiler::MapRef::GetPropertyKey (JSHeapBroker * broker, InternalIndex descriptor_index) const
Definition at line 1371 of file heap-refs.cc.
                                                                     {
  CHECK_LT(descriptor_index.as_int(), NumberOfOwnDescriptors());
  return instance_descriptors(broker).GetPropertyKey(broker, descriptor_index);
}
References v8::internal::InternalIndex::as_int(), broker(), CHECK_LT, v8::internal::compiler::DescriptorArrayRef::GetPropertyKey(), instance_descriptors(), and NumberOfOwnDescriptors().
Referenced by v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral().
GetStrongValue()
OptionalObjectRef v8::internal::compiler::MapRef::GetStrongValue (JSHeapBroker * broker, InternalIndex descriptor_number) const
Definition at line 1796 of file heap-refs.cc.
                                                                               {
  CHECK_LT(descriptor_index.as_int(), NumberOfOwnDescriptors());
  return instance_descriptors(broker).GetStrongValue(broker, descriptor_index);
}
References v8::internal::InternalIndex::as_int(), broker(), CHECK_LT, v8::internal::compiler::DescriptorArrayRef::GetStrongValue(), instance_descriptors(), and NumberOfOwnDescriptors().
has_indexed_interceptor()
bool v8::internal::compiler::MapRef::has_indexed_interceptor () const
Referenced by CanInlineElementAccess(), and v8::internal::compiler::AccessInfoFactory::ObjectMayHaveElements().
has_named_interceptor()
bool v8::internal::compiler::MapRef::has_named_interceptor () const
Referenced by v8::internal::compiler::AccessInfoFactory::ObjectMayHaveOwnProperties().
has_prototype_slot()
bool v8::internal::compiler::MapRef::has_prototype_slot () const
Referenced by v8::internal::compiler::NodeProperties::GetJSCreateMap(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildNamedAccess().
instance_descriptors()
DescriptorArrayRef v8::internal::compiler::MapRef::instance_descriptors (JSHeapBroker * broker) const
Definition at line 1802 of file heap-refs.cc.
                                                                          {
  return MakeRefAssumeMemoryFence(
      broker,
      object()->instance_descriptors(broker->cage_base(), kAcquireLoad));
}
References broker(), v8::kAcquireLoad, and v8::internal::compiler::MakeRefAssumeMemoryFence().
Referenced by v8::internal::compiler::AccessInfoFactory::ComputeDataFieldAccessInfo(), GetPropertyDetails(), GetPropertyKey(), GetStrongValue(), v8::internal::compiler::AccessInfoFactory::LookupTransition(), v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeHasOwnProperty(), and v8::internal::compiler::AccessInfoFactory::TryLoadPropertyDetails().
instance_size()
int v8::internal::compiler::MapRef::instance_size () const
Referenced by v8::internal::compiler::JSCallReducerAssembler::AllocateEmptyJSArray(), v8::internal::maglev::MaglevGraphBuilder::BuildAndAllocateKeyValueArray(), v8::internal::compiler::JSFunctionData::Cache(), v8::internal::maglev::MaglevGraphBuilder::CreateArgumentsObject(), v8::internal::maglev::MaglevGraphBuilder::CreateJSArrayIterator(), v8::internal::maglev::MaglevGraphBuilder::CreateJSObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateEmptyLiteralObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreatePromise(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateStringWrapper(), v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral(), and v8::internal::maglev::MaglevGraphBuilder::TryReadBoilerplateForFastLiteral().
instance_type()
InstanceType v8::internal::compiler::MapRef::instance_type () const
Referenced by v8::internal::compiler::anonymous_namespace{access-info.cc}::AccessorAccessInfoHelper(), v8::internal::compiler::AllocationBuilder::AllocateArray(), v8::internal::compiler::AllocationBuilder::AllocateContext(), v8::internal::compiler::AllocationBuilder::CanAllocateArray(), v8::internal::compiler::anonymous_namespace{access-info.cc}::CanInlinePropertyAccess(), v8::internal::compiler::AccessInfoFactory::ConsolidateElementLoad(), v8::internal::maglev::MaglevGraphBuilder::CreateJSGeneratorObject(), v8::internal::compiler::CompilationDependencies::DependOnFieldConstness(), v8::internal::compiler::CompilationDependencies::FieldConstnessDependencyOffTheRecord(), v8::internal::compiler::HeapObjectRef::GetHeapObjectType(), IsPrimitiveMap(), v8::internal::compiler::AccessInfoFactory::ObjectMayHaveElements(), v8::internal::compiler::AccessInfoFactory::ObjectMayHaveOwnProperties(), oddball_type(), v8::internal::compiler::JSCallReducer::ReduceObjectGetPrototype(), v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeHasOwnProperty(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccess(), v8::internal::compiler::AccessInfoFactory::TryLoadPropertyDetails(), and v8::internal::maglev::MaglevGraphBuilder::TryReduceGetProto().
is_abandoned_prototype_map()
bool v8::internal::compiler::MapRef::is_abandoned_prototype_map () const
Referenced by v8::internal::compiler::JSHeapBroker::ReadFeedbackForPropertyAccess().
is_access_check_needed()
bool v8::internal::compiler::MapRef::is_access_check_needed () const
Referenced by CanInlineElementAccess(), v8::internal::compiler::anonymous_namespace{access-info.cc}::CanInlinePropertyAccess(), v8::internal::compiler::AccessInfoFactory::ComputeElementAccessInfo(), v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), and v8::internal::maglev::MaglevGraphBuilder::TryInferApiHolderValue().
is_callable()
bool v8::internal::compiler::MapRef::is_callable () const
Referenced by v8::internal::compiler::HeapObjectRef::GetHeapObjectType(), v8::internal::maglev::IsInstanceOfLeafNodeType(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf(), v8::internal::maglev::StaticTypeForMap(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildFastInstanceOf().
is_constructor()
bool v8::internal::compiler::MapRef::is_constructor () const
Referenced by v8::internal::compiler::NodeProperties::GetJSCreateMap(), and v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeBind().
is_deprecated()
bool v8::internal::compiler::MapRef::is_deprecated () const
Referenced by v8::internal::compiler::JSHeapBroker::ReadFeedbackForPropertyAccess(), v8::internal::compiler::CompilationDependencies::TransitionDependencyOffTheRecord(), v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral(), and v8::internal::maglev::MaglevGraphBuilder::TryReadBoilerplateForFastLiteral().
is_dictionary_map()
bool v8::internal::compiler::MapRef::is_dictionary_map () const
Referenced by v8::internal::compiler::anonymous_namespace{access-info.cc}::AccessorAccessInfoHelper(), v8::internal::compiler::anonymous_namespace{access-info.cc}::CanInlinePropertyAccess(), v8::internal::compiler::AccessInfoFactory::ComputeElementAccessInfo(), v8::internal::compiler::AccessInfoFactory::ComputePropertyAccessInfo(), v8::internal::maglev::MaglevGraphBuilder::CreateJSObject(), v8::internal::compiler::AccessInfoFactory::ObjectMayHaveOwnProperties(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateEmptyLiteralObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateObject(), v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeHasOwnProperty(), and v8::internal::compiler::AccessInfoFactory::TryLoadPropertyDetails().
is_extensible()
bool v8::internal::compiler::MapRef::is_extensible () const
Referenced by v8::internal::compiler::AccessInfoFactory::ObjectMayHaveElements(), and v8::internal::compiler::AccessInfoFactory::ObjectMayHaveOwnProperties().
is_migration_target()
bool v8::internal::compiler::MapRef::is_migration_target () const
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildTransitionElementsKindAndCompareMaps(), v8::internal::maglev::MaglevGraphBuilder::BuildTransitionElementsKindOrCheckMap(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::KnownMapsMerger::InsertMap(), and v8::internal::compiler::JSHeapBroker::ReadFeedbackForPropertyAccess().
is_stable()
bool v8::internal::compiler::MapRef::is_stable () const
Definition at line 1880 of file heap-refs.cc.
                             {
  IF_ACCESS_FROM_HEAP_C(is_stable);
  return !Map::Bits3::IsUnstableBit::decode(data()->AsMap()->bit_field3());
}
References v8::internal::compiler::bit_field3, and IF_ACCESS_FROM_HEAP_C.
Referenced by v8::internal::compiler::PropertyAccessBuilder::BuildCheckMaps(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckMaps(), v8::internal::maglev::MaglevGraphBuilder::BuildStoreMap(), v8::internal::maglev::MaglevGraphBuilder::BuildTransitionElementsKindAndCompareMaps(), v8::internal::maglev::MaglevGraphBuilder::BuildTransitionElementsKindOrCheckMap(), v8::internal::compiler::CompilationDependencies::DependOnFieldConstness(), v8::internal::compiler::CompilationDependencies::FieldConstnessDependencyOffTheRecord(), v8::internal::compiler::anonymous_namespace{typed-optimization.cc}::GetStableMapFromObjectType(), v8::internal::compiler::NodeProperties::InferMapsUnsafe(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::KnownMapsMerger::InsertMap(), PrototypesElementsDoNotHaveAccessorsOrThrow(), v8::internal::compiler::JSNativeContextSpecialization::ReduceGlobalAccess(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildFastInstanceOf().
is_undetectable()
bool v8::internal::compiler::MapRef::is_undetectable () const
Referenced by v8::internal::compiler::HeapObjectRef::GetHeapObjectType().
IsBooleanMap()
bool v8::internal::compiler::MapRef::IsBooleanMap (JSHeapBroker * broker) const
Definition at line 1145 of file heap-refs.cc.
                                                    {
  return *this == broker->boolean_map();
}
References broker().
Referenced by v8::internal::maglev::IsInstanceOfLeafNodeType(), and v8::internal::maglev::StaticTypeForMap().
IsFixedCowArrayMap()
bool v8::internal::compiler::MapRef::IsFixedCowArrayMap (JSHeapBroker * broker) const
Definition at line 1377 of file heap-refs.cc.
                                                          {
  Handle<Map> fixed_cow_array_map =
      broker->isolate()->factory()->fixed_cow_array_map();
  return equals(MakeRef(broker, fixed_cow_array_map));
}
References broker(), and v8::internal::compiler::MakeRef().
Referenced by v8::internal::compiler::JSArrayRef::GetOwnCowElement(), v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteralElements(), and v8::internal::maglev::MaglevGraphBuilder::TryReadBoilerplateForFastLiteral().
IsInobjectSlackTrackingInProgress()
bool v8::internal::compiler::MapRef::IsInobjectSlackTrackingInProgress () const
Definition at line 1872 of file heap-refs.cc.
                                                     {
  return construction_counter() != Map::kNoSlackTracking;
}
References construction_counter(), and v8::internal::Map::kNoSlackTracking.
Referenced by v8::internal::compiler::JSFunctionData::Cache(), v8::internal::maglev::MaglevGraphBuilder::CreateJSObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateEmptyLiteralObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateObject(), and v8::internal::compiler::JSCreateLowering::ReduceJSCreateStringWrapper().
IsNullMap()
bool v8::internal::compiler::MapRef::IsNullMap (JSHeapBroker * broker) const
Definition at line 1149 of file heap-refs.cc.
                                                 {
  return *this == broker->null_map();
}
References broker().
Referenced by v8::internal::maglev::IsInstanceOfLeafNodeType().
IsOneByteStringMap()
bool v8::internal::compiler::MapRef::IsOneByteStringMap () const
Definition at line 1170 of file heap-refs.cc.
                                      {
  return InstanceTypeChecker::IsOneByteString(*object());
}
References v8::internal::InstanceTypeChecker::IsOneByteString().
Referenced by v8::internal::maglev::IsInstanceOfLeafNodeType(), and v8::internal::maglev::StaticTypeForMap().
IsPrimitiveMap()
bool v8::internal::compiler::MapRef::IsPrimitiveMap () const
Definition at line 1383 of file heap-refs.cc.
                                  {
  return instance_type() <= LAST_PRIMITIVE_HEAP_OBJECT_TYPE;
}
References instance_type().
Referenced by v8::internal::compiler::AccessInfoFactory::ComputePropertyAccessInfo(), v8::internal::compiler::CompilationDependencies::DependOnStablePrototypeChain(), v8::internal::compiler::NativeContextRef::GetConstructorFunction(), v8::internal::compiler::JSCallReducer::ReduceObjectGetPrototype(), and v8::internal::maglev::MaglevGraphBuilder::TryReduceGetProto().
IsSeqStringMap()
bool v8::internal::compiler::MapRef::IsSeqStringMap () const
Definition at line 1157 of file heap-refs.cc.
                                  {
  return InstanceTypeChecker::IsSeqString(*object());
}
References v8::internal::InstanceTypeChecker::IsSeqString().
Referenced by v8::internal::maglev::IsInstanceOfLeafNodeType(), and v8::internal::maglev::StaticTypeForMap().
IsStringWrapperMap()
bool v8::internal::compiler::MapRef::IsStringWrapperMap () const
Definition at line 1165 of file heap-refs.cc.
                                      {
  return IsJSPrimitiveWrapperMap() &&
         IsStringWrapperElementsKind(elements_kind());
}
References elements_kind(), and v8::internal::IsStringWrapperElementsKind().
Referenced by v8::internal::maglev::IsInstanceOfLeafNodeType(), and v8::internal::maglev::StaticTypeForMap().
IsThinStringMap()
bool v8::internal::compiler::MapRef::IsThinStringMap () const
Definition at line 1161 of file heap-refs.cc.
                                   {
  return InstanceTypeChecker::IsThinString(*object());
}
References v8::internal::InstanceTypeChecker::IsThinString().
IsTwoByteStringMap()
bool v8::internal::compiler::MapRef::IsTwoByteStringMap () const
Definition at line 1174 of file heap-refs.cc.
                                      {
  return InstanceTypeChecker::IsTwoByteString(*object());
}
References v8::internal::InstanceTypeChecker::IsTwoByteString().
IsUndefinedMap()
bool v8::internal::compiler::MapRef::IsUndefinedMap (JSHeapBroker * broker) const
Definition at line 1153 of file heap-refs.cc.
                                                      {
  return *this == broker->undefined_map();
}
References broker().
Referenced by v8::internal::maglev::IsInstanceOfLeafNodeType().
NextFreePropertyIndex()
int v8::internal::compiler::MapRef::NextFreePropertyIndex () const
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildExtendPropertiesBackingStore(), and v8::internal::compiler::JSNativeContextSpecialization::BuildExtendPropertiesBackingStore().
NumberOfOwnDescriptors()
int v8::internal::compiler::MapRef::NumberOfOwnDescriptors () const
Referenced by FindFieldOwner(), GetFieldIndexFor(), GetPropertyDetails(), GetPropertyKey(), GetStrongValue(), v8::internal::compiler::AccessInfoFactory::ObjectMayHaveOwnProperties(), v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeHasOwnProperty(), v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral(), and v8::internal::maglev::MaglevGraphBuilder::TryReadBoilerplateForFastLiteral().
object()
IndirectHandle<Map> v8::internal::compiler::MapRef::object () const
Referenced by v8::internal::compiler::anonymous_namespace{access-info.cc}::AccessorAccessInfoHelper(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildVirtualObject(), CanBeDeprecated(), v8::internal::compiler::anonymous_namespace{access-info.cc}::CanInlinePropertyAccess(), CanTransition(), v8::internal::maglev::StoreMap::ClearUnstableNodeAspects(), v8::internal::compiler::AccessInfoFactory::ComputeAccessorDescriptorAccessInfo(), v8::internal::compiler::AccessInfoFactory::ComputeDataFieldAccessInfo(), v8::internal::compiler::AccessInfoFactory::ComputePropertyAccessInfo(), constructor_function_index(), v8::internal::compiler::PropertyAccessInfo::DataField(), GetInObjectPropertiesStartInWords(), GetInObjectPropertyOffset(), v8::internal::compiler::anonymous_namespace{heap-refs.cc}::GetOwnFastConstantDataPropertyFromHeap(), v8::internal::compiler::anonymous_namespace{heap-refs.cc}::InstanceSizeWithMinSlack(), v8::internal::compiler::AccessInfoFactory::LookupSpecialFieldAccessor(), v8::internal::compiler::AccessInfoFactory::LookupSpecialFieldAccessorInHolder(), v8::internal::compiler::AccessInfoFactory::LookupTransition(), v8::internal::compiler::PropertyAccessTarget::Hash::operator()(), v8::internal::compiler::operator<<(), v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::operator<<(), v8::internal::maglev::VirtualObject::PrintParams(), v8::internal::maglev::InlinedAllocation::PrintParams(), v8::internal::maglev::StoreMap::PrintParams(), v8::internal::maglev::TransitionElementsKindOrCheckMap::PrintParams(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForPropertyAccess(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::StringAt(), v8::internal::compiler::turboshaft::TurbolevEarlyLoweringReducer< Next >::TransitionElementsKind(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::TransitionElementsKindOrCheckMap(), v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral(), v8::internal::compiler::AccessInfoFactory::TryLoadPropertyDetails(), and v8::internal::maglev::MaglevGraphBuilder::TryReadBoilerplateForFastLiteral().
oddball_type()
OddballType v8::internal::compiler::MapRef::oddball_type (JSHeapBroker * broker) const
Definition at line 1295 of file heap-refs.cc.
                                                           {
  if (instance_type() != ODDBALL_TYPE) {
    return OddballType::kNone;
  }
  if (equals(broker->undefined_map())) {
    return OddballType::kUndefined;
  }
  if (equals(broker->null_map())) {
    return OddballType::kNull;
  }
  if (equals(broker->boolean_map())) {
    return OddballType::kBoolean;
  }
  UNREACHABLE();
}
References broker(), instance_type(), v8::internal::compiler::kBoolean, v8::internal::compiler::kNone, v8::internal::compiler::kNull, v8::internal::compiler::kUndefined, and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::CompilationDependencies::DependOnStablePrototypeChain(), and PrototypesElementsDoNotHaveAccessorsOrThrow().
prototype()
HeapObjectRef v8::internal::compiler::MapRef::prototype (JSHeapBroker * broker) const
Definition at line 1808 of file heap-refs.cc.
                                                          {
  return MakeRefAssumeMemoryFence(broker,
                                  Cast<HeapObject>(object()->prototype()));
}
References broker(), and v8::internal::compiler::MakeRefAssumeMemoryFence().
Referenced by v8::internal::compiler::AccessInfoFactory::ComputeElementAccessInfo(), v8::internal::compiler::AccessInfoFactory::ComputePropertyAccessInfo(), v8::internal::compiler::CompilationDependencies::DependOnStablePrototypeChain(), v8::internal::compiler::anonymous_namespace{js-create-lowering.cc}::GetObjectCreateMap(), PrototypesElementsDoNotHaveAccessorsOrThrow(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeBind(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSFindNonDefaultConstructorOrConstruct(), v8::internal::compiler::JSCallReducer::ReduceObjectGetPrototype(), v8::internal::maglev::MaglevGraphBuilder::TryBuildFindNonDefaultConstructorOrConstruct(), and v8::internal::maglev::MaglevGraphBuilder::TryReduceGetProto().
PrototypesElementsDoNotHaveAccessorsOrThrow()
bool v8::internal::compiler::MapRef::PrototypesElementsDoNotHaveAccessorsOrThrow (JSHeapBroker * broker, ZoneVector< MapRef > * prototype_maps)
Definition at line 1229 of file heap-refs.cc.
                                                              {
  DCHECK_NOT_NULL(prototype_maps);
  MapRef prototype_map = prototype(broker).map(broker);
  while (prototype_map.oddball_type(broker) != OddballType::kNull) {
    // For the purposes of depending on prototypes' elements behavior when
    // doing keyed property sets, non-extensible and sealed fast elements are
    // okay because they behave like fast elements for stores into holes on
    // the receiver. In such cases, the value is stored on the receiver's
    // elements and does not trigger any setters and does not throw.
    //
    // Note that frozen elements are _not_ okay because of the "override
    // mistake":
    //
    // Object.prototype[1] = "x";
    // Object.freeze(Object.prototype);
    // ([])[1] = "y"; <-- throws in strict mode, nop in sloppy mode
    if (!prototype_map.IsJSObjectMap() || !prototype_map.is_stable() ||
        !IsFastOrNonextensibleOrSealedElementsKind(
            prototype_map.elements_kind())) {
      return false;
    }
    prototype_maps->push_back(prototype_map);
    prototype_map = prototype_map.prototype(broker).map(broker);
  }
  return true;
}
References broker(), DCHECK_NOT_NULL, elements_kind(), is_stable(), v8::internal::IsFastOrNonextensibleOrSealedElementsKind(), v8::internal::compiler::kNull, v8::internal::compiler::HeapObjectRef::map(), oddball_type(), prototype(), and v8::internal::ZoneVector< T >::push_back().
supports_fast_array_iteration()
bool v8::internal::compiler::MapRef::supports_fast_array_iteration (JSHeapBroker * broker) const
Definition at line 1257 of file heap-refs.cc.
                                                                     {
  return SupportsFastArrayIteration(broker, object());
}
References broker(), and v8::internal::compiler::anonymous_namespace{heap-refs.cc}::SupportsFastArrayIteration().
Referenced by v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpread().
supports_fast_array_resize()
bool v8::internal::compiler::MapRef::supports_fast_array_resize (JSHeapBroker * broker) const
Definition at line 1261 of file heap-refs.cc.
                                                                  {
  return SupportsFastArrayResize(broker, object());
}
References broker(), and v8::internal::compiler::anonymous_namespace{heap-refs.cc}::SupportsFastArrayResize().
UnusedPropertyFields()
int v8::internal::compiler::MapRef::UnusedPropertyFields () const
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildExtendPropertiesBackingStore(), and v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyStore().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/heap-refs.h
/mnt/V8SourceCode/src/compiler/heap-refs.cc