v8::internal::OrderedHashSet Class Reference
#include <ordered-hash-table.h>
Public Member Functions
template<typename IsolateT >
MaybeHandle< OrderedHashSet > Allocate (IsolateT *isolate, int capacity, AllocationType allocation)
Static Public Member Functions
template<template< typename > typename HandleType>
static requires(std::is_convertible_v< HandleType< OrderedHashSet >, DirectHandle< OrderedHashSet >>) static HandleType< OrderedHashSet > Handle< FixedArray > ConvertToKeysArray (Isolate *isolate, Handle< OrderedHashSet > table, GetKeysConversion convert)
template<typename IsolateT >
requires(std::is_convertible_v< HandleType< OrderedHashSet >, DirectHandle< OrderedHashSet >>) static HandleType< OrderedHashSet > static requires(std::is_convertible_v< HandleType< OrderedHashSet >, DirectHandle< OrderedHashSet >>) static HandleType< OrderedHashSet > MaybeHandle< OrderedHashSet > Allocate (IsolateT *isolate, int capacity, AllocationType allocation=AllocationType::kYoung)
static MaybeHandle< OrderedHashSet > AllocateEmpty (Isolate *isolate, AllocationType allocation=AllocationType::kReadOnly)
static Tagged< HeapObject > GetEmpty (ReadOnlyRoots ro_roots)
static Handle< Map > GetMap (RootsTable &roots)
static bool Is (DirectHandle< HeapObject > table)
Static Public Attributes
static const int kPrefixSize = 0
Private Types
using Base = OrderedHashTable< OrderedHashSet, 1 >
Additional Inherited Members
Detailed Description
Definition at line 280 of file ordered-hash-table.h.
Member Typedef Documentation
Base
using v8::internal::OrderedHashSet::Base = OrderedHashTable<OrderedHashSet, 1> [private]
Definition at line 282 of file ordered-hash-table.h.
Member Function Documentation
Allocate() [1/2]
template<typename IsolateT >
MaybeHandle<OrderedHashSet> v8::internal::OrderedHashSet::Allocate (IsolateT * isolate, int capacity, AllocationType allocation)
Definition at line 603 of file ordered-hash-table.cc.
                                                                {
  return Base::Allocate(isolate, capacity, allocation);
}
References v8::internal::OrderedHashTable< OrderedHashSet, 1 >::Allocate().
Allocate() [2/2]
template<typename IsolateT >
requires (std::is_convertible_v<HandleType<OrderedHashSet>, DirectHandle<OrderedHashSet>>) static HandleType<OrderedHashSet> static requires (std::is_convertible_v<HandleType<OrderedHashSet>, DirectHandle<OrderedHashSet>>) static HandleType<OrderedHashSet> MaybeHandle<OrderedHashSet> v8::internal::OrderedHashSet::Allocate (IsolateT * isolate, int capacity, AllocationType allocation = AllocationType::kYoung) [static]
Referenced by v8::internal::KeyAccumulator::AddKey(), v8::internal::Genesis::InstallABunchOfRandomThings(), and v8::internal::Factory::NewOrderedHashSet().
AllocateEmpty()
MaybeHandle< OrderedHashSet > v8::internal::OrderedHashSet::AllocateEmpty (Isolate * isolate, AllocationType allocation = AllocationType::kReadOnly) [static]
Definition at line 625 of file ordered-hash-table.cc.
                                                 {
  RootIndex ri = RootIndex::kEmptyOrderedHashSet;
  return Base::AllocateEmpty(isolate, allocation, ri);
}
References v8::internal::OrderedHashTable< OrderedHashSet, 1 >::AllocateEmpty().
Referenced by v8::internal::Heap::CreateReadOnlyObjects().
ConvertToKeysArray()
template<template< typename > typename HandleType>
Handle< FixedArray > v8::internal::OrderedHashSet::ConvertToKeysArray (Isolate * isolate, Handle< OrderedHashSet > table, GetKeysConversion convert) [static]
Definition at line 236 of file ordered-hash-table.cc.
                                                                               {
  int length = table->NumberOfElements();
  int nof_buckets = table->NumberOfBuckets();
  // Convert the dictionary to a linear list.
  Handle<FixedArray> result = Cast<FixedArray>(table);
  // From this point on table is no longer a valid OrderedHashSet.
  result->set_map(isolate, ReadOnlyRoots(isolate).fixed_array_map());
  for (int i = 0; i < length; i++) {
    int index = HashTableStartIndex() + nof_buckets + (i * kEntrySize);
    Tagged<Object> key = table->get(index);
    uint32_t index_value;
    if (convert == GetKeysConversion::kConvertToString) {
      if (Object::ToArrayIndex(key, &index_value)) {
        // Avoid trashing the number to string cache with numbers that
        // are not likely to be needed.
        bool use_cache = i < SmiStringCache::kMaxCapacity;
        key = *isolate->factory()->Uint32ToString(index_value, use_cache);
      } else {
        CHECK(IsName(key));
      }
    } else if (convert == GetKeysConversion::kNoNumbers) {
      DCHECK(!Object::ToArrayIndex(key, &index_value));
    }
    result->set(i, key);
  }
  return FixedArray::RightTrimOrEmpty(isolate, result, length);
}
References CHECK, v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::OrderedHashTable< OrderedHashSet, 1 >::HashTableStartIndex(), v8::internal::FixedArray::index, v8::internal::kConvertToString, v8::internal::OrderedHashTable< OrderedHashSet, 1 >::kEntrySize, v8::internal::key, v8::internal::SmiStringCache::kMaxCapacity, v8::internal::kNoNumbers, v8::internal::length, v8::base::internal::result, v8::internal::OrderedHashTable< OrderedHashSet, 1 >::table, v8::internal::Object::ToArrayIndex(), and v8::internal::Factory::Uint32ToString().
Referenced by v8::internal::KeyAccumulator::GetKeys(), and v8::internal::JsonStringifier::InitializeReplacer().
GetEmpty()
Tagged< HeapObject > v8::internal::OrderedHashSet::GetEmpty (ReadOnlyRoots ro_roots) [static]
Definition at line 265 of file ordered-hash-table.cc.
                                                                  {
  return ro_roots.empty_ordered_hash_set();
}
GetMap()
static Handle<Map> v8::internal::OrderedHashSet::GetMap (RootsTable & roots) [inline], [static]
Is()
bool v8::internal::OrderedHashSet::Is (DirectHandle< HeapObject > table) [inline], [static]
Definition at line 156 of file ordered-hash-table-inl.h.
                                                             {
  return IsOrderedHashSet(*table);
}
References v8::internal::OrderedHashTable< OrderedHashSet, 1 >::table.
Member Data Documentation
kPrefixSize
const int v8::internal::OrderedHashSet::kPrefixSize = 0 [static]
Definition at line 318 of file ordered-hash-table.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/ordered-hash-table.h
/mnt/V8SourceCode/src/objects/ordered-hash-table-inl.h
/mnt/V8SourceCode/src/objects/ordered-hash-table.cc