v8::internal::maglev::DeoptInfo Class Reference
#include <maglev-ir.h>
Public Member Functions
DeoptFrame & top_frame ()
const DeoptFrame & top_frame () const
const compiler::FeedbackSource & feedback_to_update () const
bool has_input_locations () const
InputLocation * input_locations () const
void InitializeInputLocations (Zone *zone, size_t count)
Label * deopt_entry_label ()
int translation_index () const
void set_translation_index (int index)
Protected Member Functions
DeoptInfo (Zone *zone, const DeoptFrame top_frame, compiler::FeedbackSource feedback_to_update)
Private Attributes
DeoptFrame top_frame_
const compiler::FeedbackSource feedback_to_update_
InputLocation * input_locations_ = nullptr
Label deopt_entry_label_
int translation_index_ = -1
Detailed Description
Definition at line 1822 of file maglev-ir.h.
Constructor & Destructor Documentation
DeoptInfo()
v8::internal::maglev::DeoptInfo::DeoptInfo (Zone * zone, const DeoptFrame top_frame, compiler::FeedbackSource feedback_to_update) [protected]
Definition at line 384 of file maglev-ir.cc.
    : top_frame_(top_frame), feedback_to_update_(feedback_to_update) {}
Member Function Documentation
deopt_entry_label()
Label* v8::internal::maglev::DeoptInfo::deopt_entry_label () [inline]
Definition at line 1841 of file maglev-ir.h.
{ return &deopt_entry_label_; }
References deopt_entry_label_.
Referenced by v8::internal::maglev::MaglevAssembler::GetDeoptLabel().
feedback_to_update()
const compiler::FeedbackSource& v8::internal::maglev::DeoptInfo::feedback_to_update () const [inline]
Definition at line 1830 of file maglev-ir.h.
                                                           {
    return feedback_to_update_;
  }
References feedback_to_update_.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildBeginDeopt(), and v8::internal::maglev::NodeBase::CopyEagerDeoptInfoOf().
has_input_locations()
bool v8::internal::maglev::DeoptInfo::has_input_locations () const [inline]
Definition at line 1834 of file maglev-ir.h.
{ return input_locations_ != nullptr; }
References input_locations_.
InitializeInputLocations()
void v8::internal::maglev::DeoptInfo::InitializeInputLocations (Zone * zone, size_t count)
Definition at line 341 of file maglev-ir.cc.
                                                                 {
  DCHECK_NULL(input_locations_);
  input_locations_ = zone->AllocateArray<InputLocation>(count);
  // Initialise locations so that they correctly don't have a next use id.
  for (size_t i = 0; i < count; ++i) {
    new (&input_locations_[i]) InputLocation();
  }
#ifdef DEBUG
  input_location_count_ = count;
#endif // DEBUG
}
References v8::internal::Zone::AllocateArray(), DCHECK_NULL, v8::internal::anonymous_namespace{json-stringifier.cc}::i, and input_locations_.
input_locations()
InputLocation* v8::internal::maglev::DeoptInfo::input_locations () const [inline]
Definition at line 1835 of file maglev-ir.h.
                                         {
    DCHECK_NOT_NULL(input_locations_);
    return input_locations_;
  }
References DCHECK_NOT_NULL, and input_locations_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateEagerDeopt(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateLazyDeopt(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildEagerDeopt(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildLazyDeopt(), and v8::internal::maglev::StraightForwardRegisterAllocator::SaveRegisterSnapshot().
set_translation_index()
void v8::internal::maglev::DeoptInfo::set_translation_index (int index) [inline]
Definition at line 1844 of file maglev-ir.h.
{ translation_index_ = index; }
References v8::internal::index, and translation_index_.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildBeginDeopt().
top_frame() [1/2]
DeoptFrame& v8::internal::maglev::DeoptInfo::top_frame () [inline]
Definition at line 1828 of file maglev-ir.h.
{ return top_frame_; }
References top_frame_.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildBeginDeopt(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildEagerDeopt(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildLazyDeopt(), v8::internal::maglev::NodeBase::CopyEagerDeoptInfoOf(), v8::internal::maglev::LazyDeoptInfo::GetFrameForExceptionHandler(), v8::internal::maglev::LazyDeoptInfo::IsResultRegister(), and v8::internal::maglev::MaxCallDepthProcessor::UpdateMaxDeoptedStackSize().
top_frame() [2/2]
const DeoptFrame& v8::internal::maglev::DeoptInfo::top_frame () const [inline]
Definition at line 1829 of file maglev-ir.h.
{ return top_frame_; }
References top_frame_.
translation_index()
int v8::internal::maglev::DeoptInfo::translation_index () const [inline]
Definition at line 1843 of file maglev-ir.h.
{ return translation_index_; }
References translation_index_.
Member Data Documentation
deopt_entry_label_
Label v8::internal::maglev::DeoptInfo::deopt_entry_label_ [private]
Definition at line 1857 of file maglev-ir.h.
Referenced by deopt_entry_label().
feedback_to_update_
const compiler::FeedbackSource v8::internal::maglev::DeoptInfo::feedback_to_update_ [private]
Definition at line 1852 of file maglev-ir.h.
Referenced by feedback_to_update().
input_locations_
InputLocation* v8::internal::maglev::DeoptInfo::input_locations_ = nullptr [private]
Definition at line 1853 of file maglev-ir.h.
Referenced by has_input_locations(), InitializeInputLocations(), and input_locations().
top_frame_
DeoptFrame v8::internal::maglev::DeoptInfo::top_frame_ [private]
Definition at line 1851 of file maglev-ir.h.
Referenced by top_frame().
translation_index_
int v8::internal::maglev::DeoptInfo::translation_index_ = -1 [private]
Definition at line 1858 of file maglev-ir.h.
Referenced by set_translation_index(), and translation_index().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc