v8::internal::NativeObjectsExplorer Class Reference
#include <heap-snapshot-generator.h>
Public Member Functions
NativeObjectsExplorer (HeapSnapshot *snapshot, SnapshottingProgressReportingInterface *progress)
NativeObjectsExplorer (const NativeObjectsExplorer &)=delete
NativeObjectsExplorer & operator= (const NativeObjectsExplorer &)=delete
bool IterateAndExtractReferences (HeapSnapshotGenerator *generator)
Private Member Functions
HeapEntry * EntryForEmbedderGraphNode (EmbedderGraph::Node *node)
void MergeNodeIntoEntry (HeapEntry *entry, EmbedderGraph::Node *original_node, EmbedderGraph::Node *wrapper_node)
Private Attributes
Isolate * isolate_
HeapSnapshot * snapshot_
StringsStorage * names_
HeapObjectsMap * heap_object_map_
std::unique_ptr< HeapEntriesAllocator > embedder_graph_entries_allocator_
HeapSnapshotGenerator * generator_ = nullptr
Static Private Attributes
static HeapThing const kNativesRootObject
Friends
class GlobalHandlesExtractor
Detailed Description
Definition at line 612 of file heap-snapshot-generator.h.
Constructor & Destructor Documentation
NativeObjectsExplorer() [1/2]
v8::internal::NativeObjectsExplorer::NativeObjectsExplorer (HeapSnapshot * snapshot, SnapshottingProgressReportingInterface * progress)
Definition at line 3146 of file heap-snapshot-generator.cc.
    : isolate_(
          Isolate::FromHeap(snapshot->profiler()->heap_object_map()->heap())),
      snapshot_(snapshot),
      names_(snapshot_->profiler()->names()),
      heap_object_map_(snapshot_->profiler()->heap_object_map()),
      embedder_graph_entries_allocator_(
          new EmbedderGraphEntriesAllocator(snapshot)) {}
NativeObjectsExplorer() [2/2]
v8::internal::NativeObjectsExplorer::NativeObjectsExplorer (const NativeObjectsExplorer &) [delete]
Member Function Documentation
EntryForEmbedderGraphNode()
HeapEntry * v8::internal::NativeObjectsExplorer::EntryForEmbedderGraphNode (EmbedderGraph::Node * node) [private]
Definition at line 3184 of file heap-snapshot-generator.cc.
                                 {
  // Return the entry for the wrapper node if present.
  if (node->WrapperNode()) {
    node = node->WrapperNode();
  }
  // Node is EmbedderNode.
  if (node->IsEmbedderNode()) {
    return generator_->FindOrAddEntry(node,
                                      embedder_graph_entries_allocator_.get());
  }
  // Node is V8NodeImpl.
  Tagged<Object> object =
      static_cast<EmbedderGraphImpl::V8NodeImpl*>(node)->GetObject();
  if (IsSmi(object)) return nullptr;
  auto* entry = generator_->FindEntry(
      reinterpret_cast<void*>(Cast<Object>(object).ptr()));
  return entry;
}
References embedder_graph_entries_allocator_, v8::internal::HeapSnapshotGenerator::FindEntry(), v8::internal::HeapSnapshotGenerator::FindOrAddEntry(), generator_, v8::EmbedderGraph::Node::IsEmbedderNode(), v8::internal::IsSmi(), and v8::EmbedderGraph::Node::WrapperNode().
Referenced by IterateAndExtractReferences().
IterateAndExtractReferences()
bool v8::internal::NativeObjectsExplorer::IterateAndExtractReferences (HeapSnapshotGenerator * generator)
Definition at line 3204 of file heap-snapshot-generator.cc.
                                      {
  generator_ = generator;
  if (v8_flags.heap_profiler_use_embedder_graph &&
      snapshot_->profiler()->HasBuildEmbedderGraphCallback()) {
    v8::HandleScope scope(reinterpret_cast<v8::Isolate*>(isolate_));
    DisallowGarbageCollection no_gc;
    EmbedderGraphImpl graph;
    snapshot_->profiler()->BuildEmbedderGraph(
        isolate_, &graph, generator_->TakeCppHeapExternalObjects());
    for (const auto& node : graph.nodes()) {
      // Only add embedder nodes as V8 nodes have been added already by the
      // V8HeapExplorer.
      if (!node->IsEmbedderNode()) continue;
      if (auto* entry = EntryForEmbedderGraphNode(node.get())) {
        if (node->IsRootNode()) {
          snapshot_->root()->SetIndexedAutoIndexReference(
              HeapGraphEdge::kElement, entry, generator_,
              HeapEntry::kOffHeapPointer);
        }
        if (node->WrapperNode()) {
          MergeNodeIntoEntry(entry, node.get(), node->WrapperNode());
        }
      }
    }
    // Fill edges of the graph.
    for (const auto& edge : graph.edges()) {
      // |from| and |to| can be nullptr if the corresponding node is a V8 node
      // pointing to a Smi.
      HeapEntry* from = EntryForEmbedderGraphNode(edge.from);
      if (!from) continue;
      HeapEntry* to = EntryForEmbedderGraphNode(edge.to);
      if (!to) continue;
      if (edge.name == nullptr) {
        from->SetIndexedAutoIndexReference(HeapGraphEdge::kElement, to,
                                           generator_,
                                           HeapEntry::kOffHeapPointer);
      } else {
        from->SetNamedReference(HeapGraphEdge::kInternal,
                                names_->GetCopy(edge.name), to, generator_,
                                HeapEntry::kOffHeapPointer);
      }
    }
    snapshot_->set_extra_native_bytes(graph.native_size());
  }
  generator_ = nullptr;
  return true;
}
References v8::internal::HeapProfiler::BuildEmbedderGraph(), EntryForEmbedderGraphNode(), generator_, v8::internal::StringsStorage::GetCopy(), graph(), v8::internal::HeapProfiler::HasBuildEmbedderGraphCallback(), isolate_, v8::internal::HeapGraphEdge::kElement, v8::internal::HeapGraphEdge::kInternal, v8::internal::HeapEntry::kOffHeapPointer, MergeNodeIntoEntry(), names_, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::HeapSnapshot::profiler(), v8::internal::HeapSnapshot::root(), v8::internal::HeapSnapshot::set_extra_native_bytes(), v8::internal::HeapEntry::SetIndexedAutoIndexReference(), v8::internal::HeapEntry::SetNamedReference(), snapshot_, v8::internal::HeapSnapshotGenerator::TakeCppHeapExternalObjects(), and v8::internal::v8_flags.
Referenced by v8::internal::HeapSnapshotGenerator::FillReferences().
MergeNodeIntoEntry()
void v8::internal::NativeObjectsExplorer::MergeNodeIntoEntry (HeapEntry * entry, EmbedderGraph::Node * original_node, EmbedderGraph::Node * wrapper_node) [private]
Definition at line 3156 of file heap-snapshot-generator.cc.
                                     {
  // The wrapper node may be an embedder node (for testing purposes) or a V8
  // node (production code).
  if (!wrapper_node->IsEmbedderNode()) {
    // For V8 nodes only we can add a lookup.
    EmbedderGraphImpl::V8NodeImpl* v8_node =
        static_cast<EmbedderGraphImpl::V8NodeImpl*>(wrapper_node);
    Tagged<Object> object = v8_node->GetObject();
    DCHECK(!IsSmi(object));
    if (original_node->GetNativeObject()) {
      Tagged<HeapObject> heap_object = Cast<HeapObject>(object);
      heap_object_map_->AddMergedNativeEntry(original_node->GetNativeObject(),
                                             heap_object.address());
      DCHECK_EQ(entry->id(), heap_object_map_->FindMergedNativeEntry(
                                 original_node->GetNativeObject()));
    }
  }
  entry->set_detachedness(original_node->GetDetachedness());
  entry->set_name(MergeNames(
      names_, EmbedderGraphNodeName(names_, original_node), entry->name()));
  entry->set_type(EmbedderGraphNodeType(original_node));
  DCHECK_GE(entry->self_size() + original_node->SizeInBytes(),
            entry->self_size());
  entry->add_self_size(original_node->SizeInBytes());
}
References v8::internal::HeapEntry::add_self_size(), v8::internal::HeapObjectsMap::AddMergedNativeEntry(), v8::internal::Tagged< HeapObject >::address(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, v8::internal::anonymous_namespace{heap-snapshot-generator.cc}::EmbedderGraphNodeName(), v8::internal::anonymous_namespace{heap-snapshot-generator.cc}::EmbedderGraphNodeType(), v8::internal::HeapObjectsMap::FindMergedNativeEntry(), v8::EmbedderGraph::Node::GetDetachedness(), v8::EmbedderGraph::Node::GetNativeObject(), v8::internal::EmbedderGraphImpl::V8NodeImpl::GetObject(), heap_object_map_, v8::internal::HeapEntry::id(), v8::EmbedderGraph::Node::IsEmbedderNode(), v8::internal::IsSmi(), v8::internal::anonymous_namespace{heap-snapshot-generator.cc}::MergeNames(), v8::internal::HeapEntry::name(), names_, v8::internal::HeapEntry::self_size(), v8::internal::HeapEntry::set_detachedness(), v8::internal::HeapEntry::set_name(), v8::internal::HeapEntry::set_type(), and v8::EmbedderGraph::Node::SizeInBytes().
Referenced by IterateAndExtractReferences().
operator=()
NativeObjectsExplorer& v8::internal::NativeObjectsExplorer::operator= (const NativeObjectsExplorer &) [delete]
Friends And Related Function Documentation
GlobalHandlesExtractor
friend class GlobalHandlesExtractor [friend]
Definition at line 637 of file heap-snapshot-generator.h.
Member Data Documentation
embedder_graph_entries_allocator_
std::unique_ptr<HeapEntriesAllocator> v8::internal::NativeObjectsExplorer::embedder_graph_entries_allocator_ [private]
Definition at line 631 of file heap-snapshot-generator.h.
Referenced by EntryForEmbedderGraphNode().
generator_
HeapSnapshotGenerator* v8::internal::NativeObjectsExplorer::generator_ = nullptr [private]
Definition at line 633 of file heap-snapshot-generator.h.
Referenced by EntryForEmbedderGraphNode(), and IterateAndExtractReferences().
heap_object_map_
HeapObjectsMap* v8::internal::NativeObjectsExplorer::heap_object_map_ [private]
Definition at line 630 of file heap-snapshot-generator.h.
Referenced by MergeNodeIntoEntry().
isolate_
Isolate* v8::internal::NativeObjectsExplorer::isolate_ [private]
Definition at line 627 of file heap-snapshot-generator.h.
Referenced by IterateAndExtractReferences().
kNativesRootObject
HeapThing const v8::internal::NativeObjectsExplorer::kNativesRootObject [static], [private]
Definition at line 635 of file heap-snapshot-generator.h.
names_
StringsStorage* v8::internal::NativeObjectsExplorer::names_ [private]
Definition at line 629 of file heap-snapshot-generator.h.
Referenced by IterateAndExtractReferences(), and MergeNodeIntoEntry().
snapshot_
HeapSnapshot* v8::internal::NativeObjectsExplorer::snapshot_ [private]
Definition at line 628 of file heap-snapshot-generator.h.
Referenced by IterateAndExtractReferences().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/profiler/heap-snapshot-generator.h
/mnt/V8SourceCode/src/profiler/heap-snapshot-generator.cc