v8::internal::compiler::CsaLoadElimination::HalfState Class Reference
Public Member Functions
HalfState (Zone *zone)
bool Equals (HalfState const *that) const
void IntersectWith (HalfState const *that)
HalfState const * KillField (Node *object, Node *offset, MachineRepresentation repr) const
HalfState const * AddField (Node *object, Node *offset, Node *value, MachineRepresentation repr) const
FieldInfo Lookup (Node *object, Node *offset) const
void Print () const
Private Types
using InnerMap = PersistentMap< Node *, FieldInfo >
template<typename OuterKey >
using OuterMap = PersistentMap< OuterKey, InnerMap >
using ConstantOffsetInfos = OuterMap< uint32_t >
using UnknownOffsetInfos = OuterMap< Node * >
Private Member Functions
void KillOffsetInFresh (Node *object, uint32_t offset, MachineRepresentation repr)
Static Private Member Functions
template<typename OuterKey >
static void Update (OuterMap< OuterKey > &map, OuterKey outer_key, Node *inner_key, FieldInfo info)
static void KillOffset (ConstantOffsetInfos &infos, uint32_t offset, MachineRepresentation repr, Zone *zone)
template<typename OuterKey >
static void IntersectWith (OuterMap< OuterKey > &to, const OuterMap< OuterKey > &from)
static void Print (const ConstantOffsetInfos &infos)
static void Print (const UnknownOffsetInfos &infos)
Private Attributes
Zone * zone_
ConstantOffsetInfos fresh_entries_
ConstantOffsetInfos constant_entries_
ConstantOffsetInfos arbitrary_entries_
UnknownOffsetInfos fresh_unknown_entries_
UnknownOffsetInfos constant_unknown_entries_
UnknownOffsetInfos arbitrary_unknown_entries_
Detailed Description
Definition at line 62 of file csa-load-elimination.h.
Member Typedef Documentation
ConstantOffsetInfos
using v8::internal::compiler::CsaLoadElimination::HalfState::ConstantOffsetInfos = OuterMap<uint32_t> [private]
Definition at line 94 of file csa-load-elimination.h.
InnerMap
using v8::internal::compiler::CsaLoadElimination::HalfState::InnerMap = PersistentMap<Node*, FieldInfo> [private]
Definition at line 90 of file csa-load-elimination.h.
OuterMap
template<typename OuterKey >
using v8::internal::compiler::CsaLoadElimination::HalfState::OuterMap = PersistentMap<OuterKey, InnerMap> [private]
Definition at line 92 of file csa-load-elimination.h.
UnknownOffsetInfos
using v8::internal::compiler::CsaLoadElimination::HalfState::UnknownOffsetInfos = OuterMap<Node*> [private]
Definition at line 96 of file csa-load-elimination.h.
Constructor & Destructor Documentation
HalfState()
v8::internal::compiler::CsaLoadElimination::HalfState::HalfState (Zone * zone) [inline], [explicit]
Definition at line 64 of file csa-load-elimination.h.
        : zone_(zone),
          fresh_entries_(zone, InnerMap(zone)),
          constant_entries_(zone, InnerMap(zone)),
          arbitrary_entries_(zone, InnerMap(zone)),
          fresh_unknown_entries_(zone, InnerMap(zone)),
          constant_unknown_entries_(zone, InnerMap(zone)),
          arbitrary_unknown_entries_(zone, InnerMap(zone)) {}
Member Function Documentation
AddField()
CsaLoadElimination::HalfState const * v8::internal::compiler::CsaLoadElimination::HalfState::AddField (Node * object, Node * offset, Node * value, MachineRepresentation repr) const
Definition at line 189 of file csa-load-elimination.cc.
                                                                               {
  HalfState* new_state = zone_->New<HalfState>(*this);
  IntPtrMatcher m(offset);
  if (m.HasResolvedValue()) {
    uint32_t offset_num = static_cast<uint32_t>(m.ResolvedValue());
    ConstantOffsetInfos& infos = Helpers::IsFreshObject(object)
                                     ? new_state->fresh_entries_
                                     : Helpers::IsConstantObject(object)
                                           ? new_state->constant_entries_
                                           : new_state->arbitrary_entries_;
    Update(infos, offset_num, object, FieldInfo(value, repr));
  } else {
    UnknownOffsetInfos& infos =
        Helpers::IsFreshObject(object)
            ? new_state->fresh_unknown_entries_
            : Helpers::IsConstantObject(object)
                  ? new_state->constant_unknown_entries_
                  : new_state->arbitrary_unknown_entries_;
    Update(infos, object, offset, FieldInfo(value, repr));
  }
  return new_state;
}
References arbitrary_entries_, arbitrary_unknown_entries_, constant_entries_, constant_unknown_entries_, fresh_entries_, fresh_unknown_entries_, v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::compiler::CsaLoadEliminationHelpers::IsConstantObject(), v8::internal::compiler::CsaLoadEliminationHelpers::IsFreshObject(), v8::internal::Zone::New(), v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue(), v8::internal::value, and v8::internal::compiler::CsaLoadElimination::zone_.
Referenced by v8::internal::compiler::CsaLoadElimination::ReduceLoadFromObject(), and v8::internal::compiler::CsaLoadElimination::ReduceStoreToObject().
Equals()
bool v8::internal::compiler::CsaLoadElimination::HalfState::Equals (HalfState const * that) const [inline]
Definition at line 73 of file csa-load-elimination.h.
                                             {
      return fresh_entries_ == that->fresh_entries_ &&
             constant_entries_ == that->constant_entries_ &&
             arbitrary_entries_ == that->arbitrary_entries_ &&
             fresh_unknown_entries_ == that->fresh_unknown_entries_ &&
             constant_unknown_entries_ == that->constant_unknown_entries_ &&
             arbitrary_unknown_entries_ == that->arbitrary_unknown_entries_;
    }
References arbitrary_entries_, arbitrary_unknown_entries_, constant_entries_, constant_unknown_entries_, fresh_entries_, and fresh_unknown_entries_.
IntersectWith() [1/2]
void v8::internal::compiler::CsaLoadElimination::HalfState::IntersectWith (HalfState const * that)
Definition at line 113 of file csa-load-elimination.cc.
                                                                     {
  IntersectWith(fresh_entries_, that->fresh_entries_);
  IntersectWith(constant_entries_, that->constant_entries_);
  IntersectWith(arbitrary_entries_, that->arbitrary_entries_);
  IntersectWith(fresh_unknown_entries_, that->fresh_unknown_entries_);
  IntersectWith(constant_unknown_entries_, that->constant_unknown_entries_);
  IntersectWith(arbitrary_unknown_entries_, that->arbitrary_unknown_entries_);
}
References arbitrary_entries_, arbitrary_unknown_entries_, constant_entries_, constant_unknown_entries_, fresh_entries_, and fresh_unknown_entries_.
IntersectWith() [2/2]
template<typename OuterKey >
void v8::internal::compiler::CsaLoadElimination::HalfState::IntersectWith (OuterMap< OuterKey > & to, const OuterMap< OuterKey > & from) [static], [private]
Definition at line 97 of file csa-load-elimination.cc.
                                                            {
  FieldInfo empty_info;
  for (const std::pair<OuterKey, InnerMap>& to_map : to) {
    InnerMap to_map_copy(to_map.second);
    OuterKey key = to_map.first;
    InnerMap current_map = from.Get(key);
    for (std::pair<Node*, FieldInfo> info : to_map.second) {
      if (current_map.Get(info.first) != info.second) {
        to_map_copy.Set(info.first, empty_info);
      }
    }
    to.Set(key, to_map_copy);
  }
}
References v8::internal::compiler::PersistentMap< Key, Value, Hasher >::Get(), v8::internal::key, and v8::internal::compiler::PersistentMap< Key, Value, Hasher >::Set().
KillField()
CsaLoadElimination::HalfState const * v8::internal::compiler::CsaLoadElimination::HalfState::KillField (Node * object, Node * offset, MachineRepresentation repr) const
Definition at line 122 of file csa-load-elimination.cc.
                                                                  {
  HalfState* result = zone_->New<HalfState>(*this);
  UnknownOffsetInfos empty_unknown(zone_, InnerMap(zone_));
  IntPtrMatcher m(offset);
  if (m.HasResolvedValue()) {
    uint32_t num_offset = static_cast<uint32_t>(m.ResolvedValue());
    if (Helpers::IsFreshObject(object)) {
      // May alias with:
      // - The same object/offset
      // - Arbitrary objects with the same offset
      // - The same object, unkwown offset
      // - Arbitrary objects with unkwown offset
      result->KillOffsetInFresh(object, num_offset, repr);
      KillOffset(result->arbitrary_entries_, num_offset, repr, zone_);
      result->fresh_unknown_entries_.Set(object, InnerMap(zone_));
      result->arbitrary_unknown_entries_ = empty_unknown;
    } else if (Helpers::IsConstantObject(object)) {
      // May alias with:
      // - Constant/arbitrary objects with the same offset
      // - Constant/arbitrary objects with unkwown offset
      KillOffset(result->constant_entries_, num_offset, repr, zone_);
      KillOffset(result->arbitrary_entries_, num_offset, repr, zone_);
      result->constant_unknown_entries_ = empty_unknown;
      result->arbitrary_unknown_entries_ = empty_unknown;
    } else {
      // May alias with:
      // - Any object with the same or unknown offset
      KillOffset(result->fresh_entries_, num_offset, repr, zone_);
      KillOffset(result->constant_entries_, num_offset, repr, zone_);
      KillOffset(result->arbitrary_entries_, num_offset, repr, zone_);
      result->fresh_unknown_entries_ = empty_unknown;
      result->constant_unknown_entries_ = empty_unknown;
      result->arbitrary_unknown_entries_ = empty_unknown;
    }
  } else {
    ConstantOffsetInfos empty_constant(zone_, InnerMap(zone_));
    if (Helpers::IsFreshObject(object)) {
      // May alias with:
      // - The same object with any known/unknown offset
      // - Arbitrary objects with any known/unknown offset
      for (auto map : result->fresh_entries_) {
        // TODO(manoskouk): Consider adding a map from fresh objects to offsets
        // to implement this efficiently.
        InnerMap map_copy(map.second);
        map_copy.Set(object, FieldInfo());
        result->fresh_entries_.Set(map.first, map_copy);
      }
      result->fresh_unknown_entries_.Set(object, InnerMap(zone_));
      result->arbitrary_entries_ = empty_constant;
      result->arbitrary_unknown_entries_ = empty_unknown;
    } else if (Helpers::IsConstantObject(object)) {
      // May alias with:
      // - Constant/arbitrary objects with the any known/unknown offset
      result->constant_entries_ = empty_constant;
      result->constant_unknown_entries_ = empty_unknown;
      result->arbitrary_entries_ = empty_constant;
      result->arbitrary_unknown_entries_ = empty_unknown;
    } else {
      // May alias with anything. Clear the state.
      return zone_->New<HalfState>(zone_);
    }
  }
  return result;
}
References v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::compiler::CsaLoadEliminationHelpers::IsConstantObject(), v8::internal::compiler::CsaLoadEliminationHelpers::IsFreshObject(), v8::internal::Zone::New(), v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue(), v8::base::internal::result, v8::internal::compiler::PersistentMap< Key, Value, Hasher >::Set(), and v8::internal::compiler::CsaLoadElimination::zone_.
Referenced by v8::internal::compiler::CsaLoadElimination::ComputeLoopState(), and v8::internal::compiler::CsaLoadElimination::ReduceStoreToObject().
KillOffset()
void v8::internal::compiler::CsaLoadElimination::HalfState::KillOffset (ConstantOffsetInfos & infos, uint32_t offset, MachineRepresentation repr, Zone * zone) [static], [private]
Definition at line 237 of file csa-load-elimination.cc.
                                                           {
  // All elements in the range [{offset}, {offset + ElementSizeInBytes(repr)})
  // are in the killed range. We do not need to traverse the inner maps, we can
  // just clear them.
  for (int i = 0; i < ElementSizeInBytes(repr); i++) {
    infos.Set(offset + i, InnerMap(zone));
  }
  // Now we have to remove all elements in earlier offsets that overlap with an
  // element in {offset}.
  // The earliest offset that may overlap with {offset} is
  // {kMaximumReprSizeInBytes - 1} before.
  uint32_t initial_offset = offset >= kMaximumReprSizeInBytes - 1
                                ? offset - (kMaximumReprSizeInBytes - 1)
                                : 0;
  // For all offsets from {initial_offset} to {offset}, we traverse the
  // respective inner map, and reset all elements that are large enough to
  // overlap with {offset}.
  for (uint32_t i = initial_offset; i < offset; i++) {
    InnerMap map_copy(infos.Get(i));
    for (const std::pair<Node*, FieldInfo> info : infos.Get(i)) {
      if (info.second.representation != MachineRepresentation::kNone &&
          ElementSizeInBytes(info.second.representation) >
              static_cast<int>(offset - i)) {
        map_copy.Set(info.first, {});
      }
    }
    infos.Set(i, map_copy);
  }
}
References v8::internal::ElementSizeInBytes(), v8::internal::compiler::PersistentMap< Key, Value, Hasher >::Get(), v8::internal::kMaximumReprSizeInBytes, v8::internal::kNone, v8::internal::compiler::PersistentMap< Key, Value, Hasher >::Set(), and v8::internal::compiler::CsaLoadElimination::zone().
KillOffsetInFresh()
void v8::internal::compiler::CsaLoadElimination::HalfState::KillOffsetInFresh (Node * object, uint32_t offset, MachineRepresentation repr) [private]
Definition at line 271 of file csa-load-elimination.cc.
                                                                     {
  for (int i = 0; i < ElementSizeInBytes(repr); i++) {
    Update(fresh_entries_, offset + i, object, {});
  }
  uint32_t initial_offset = offset >= kMaximumReprSizeInBytes - 1
                                ? offset - (kMaximumReprSizeInBytes - 1)
                                : 0;
  for (uint32_t i = initial_offset; i < offset; i++) {
    const FieldInfo& info = fresh_entries_.Get(i).Get(object);
    if (info.representation != MachineRepresentation::kNone &&
        ElementSizeInBytes(info.representation) >
            static_cast<int>(offset - i)) {
      Update(fresh_entries_, i, object, {});
    }
  }
}
References v8::internal::ElementSizeInBytes(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kMaximumReprSizeInBytes, v8::internal::kNone, and v8::internal::compiler::CsaLoadElimination::FieldInfo::representation.
Lookup()
CsaLoadElimination::FieldInfo v8::internal::compiler::CsaLoadElimination::HalfState::Lookup (Node * object, Node * offset) const
Definition at line 213 of file csa-load-elimination.cc.
                                      {
  IntPtrMatcher m(offset);
  if (m.HasResolvedValue()) {
    uint32_t num_offset = static_cast<uint32_t>(m.ResolvedValue());
    const ConstantOffsetInfos& infos = Helpers::IsFreshObject(object)
                                           ? fresh_entries_
                                           : Helpers::IsConstantObject(object)
                                                 ? constant_entries_
                                                 : arbitrary_entries_;
    return infos.Get(num_offset).Get(object);
  } else {
    const UnknownOffsetInfos& infos = Helpers::IsFreshObject(object)
                                          ? fresh_unknown_entries_
                                          : Helpers::IsConstantObject(object)
                                                ? constant_unknown_entries_
                                                : arbitrary_unknown_entries_;
    return infos.Get(object).Get(offset);
  }
}
References v8::internal::compiler::PersistentMap< Key, Value, Hasher >::Get(), v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::compiler::CsaLoadEliminationHelpers::IsConstantObject(), v8::internal::compiler::CsaLoadEliminationHelpers::IsFreshObject(), and v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue().
Referenced by v8::internal::compiler::CsaLoadElimination::ComputeLoopState(), v8::internal::compiler::CsaLoadElimination::ReduceLoadFromObject(), and v8::internal::compiler::CsaLoadElimination::ReduceStoreToObject().
Print() [1/3]
void v8::internal::compiler::CsaLoadElimination::HalfState::Print () const
Definition at line 321 of file csa-load-elimination.cc.
                                              {
  Print(fresh_entries_);
  Print(constant_entries_);
  Print(arbitrary_entries_);
  Print(fresh_unknown_entries_);
  Print(constant_unknown_entries_);
  Print(arbitrary_unknown_entries_);
}
References v8::internal::Print().
Print() [2/3]
void v8::internal::compiler::CsaLoadElimination::HalfState::Print (const ConstantOffsetInfos & infos) [static], [private]
Definition at line 290 of file csa-load-elimination.cc.
                                                                 {
  for (const auto outer_entry : infos) {
    for (const auto inner_entry : outer_entry.second) {
      Node* object = inner_entry.first;
      uint32_t offset = outer_entry.first;
      FieldInfo info = inner_entry.second;
      PrintF(" #%d:%s+(%d) -> #%d:%s [repr=%s]\n", object->id(),
             object->op()->mnemonic(), offset, info.value->id(),
             info.value->op()->mnemonic(),
             MachineReprToString(info.representation));
    }
  }
}
References v8::internal::compiler::Node::id(), v8::internal::MachineReprToString(), v8::internal::compiler::Operator::mnemonic(), v8::internal::compiler::Node::op(), v8::internal::PrintF(), v8::internal::compiler::CsaLoadElimination::FieldInfo::representation, and v8::internal::compiler::CsaLoadElimination::FieldInfo::value.
Print() [3/3]
void v8::internal::compiler::CsaLoadElimination::HalfState::Print (const UnknownOffsetInfos & infos) [static], [private]
Definition at line 306 of file csa-load-elimination.cc.
                                                                {
  for (const auto outer_entry : infos) {
    for (const auto inner_entry : outer_entry.second) {
      Node* object = outer_entry.first;
      Node* offset = inner_entry.first;
      FieldInfo info = inner_entry.second;
      PrintF(" #%d:%s+#%d:%s -> #%d:%s [repr=%s]\n", object->id(),
             object->op()->mnemonic(), offset->id(), offset->op()->mnemonic(),
             info.value->id(), info.value->op()->mnemonic(),
             MachineReprToString(info.representation));
    }
  }
}
References v8::internal::compiler::Node::id(), v8::internal::MachineReprToString(), v8::internal::compiler::Operator::mnemonic(), v8::internal::compiler::Node::op(), v8::internal::PrintF(), v8::internal::compiler::CsaLoadElimination::FieldInfo::representation, and v8::internal::compiler::CsaLoadElimination::FieldInfo::value.
Update()
template<typename OuterKey >
static void v8::internal::compiler::CsaLoadElimination::HalfState::Update (OuterMap< OuterKey > & map, OuterKey outer_key, Node * inner_key, FieldInfo info) [inline], [static], [private]
Definition at line 100 of file csa-load-elimination.h.
                                                        {
      InnerMap map_copy(map.Get(outer_key));
      map_copy.Set(inner_key, info);
      map.Set(outer_key, map_copy);
    }
References v8::internal::compiler::PersistentMap< Key, Value, Hasher >::Get(), and v8::internal::compiler::PersistentMap< Key, Value, Hasher >::Set().
Member Data Documentation
arbitrary_entries_
ConstantOffsetInfos v8::internal::compiler::CsaLoadElimination::HalfState::arbitrary_entries_ [private]
Definition at line 121 of file csa-load-elimination.h.
Referenced by AddField(), Equals(), and IntersectWith().
arbitrary_unknown_entries_
UnknownOffsetInfos v8::internal::compiler::CsaLoadElimination::HalfState::arbitrary_unknown_entries_ [private]
Definition at line 124 of file csa-load-elimination.h.
Referenced by AddField(), Equals(), and IntersectWith().
constant_entries_
ConstantOffsetInfos v8::internal::compiler::CsaLoadElimination::HalfState::constant_entries_ [private]
Definition at line 120 of file csa-load-elimination.h.
Referenced by AddField(), Equals(), and IntersectWith().
constant_unknown_entries_
UnknownOffsetInfos v8::internal::compiler::CsaLoadElimination::HalfState::constant_unknown_entries_ [private]
Definition at line 123 of file csa-load-elimination.h.
Referenced by AddField(), Equals(), and IntersectWith().
fresh_entries_
ConstantOffsetInfos v8::internal::compiler::CsaLoadElimination::HalfState::fresh_entries_ [private]
Definition at line 119 of file csa-load-elimination.h.
Referenced by AddField(), Equals(), and IntersectWith().
fresh_unknown_entries_
UnknownOffsetInfos v8::internal::compiler::CsaLoadElimination::HalfState::fresh_unknown_entries_ [private]
Definition at line 122 of file csa-load-elimination.h.
Referenced by AddField(), Equals(), and IntersectWith().
zone_
Zone* v8::internal::compiler::CsaLoadElimination::HalfState::zone_ [private]
Definition at line 118 of file csa-load-elimination.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/csa-load-elimination.h
/mnt/V8SourceCode/src/compiler/csa-load-elimination.cc