v8::internal::compiler::MemoryLowering::AllocationGroup Class Reference
Public Member Functions
AllocationGroup (Node *node, AllocationType allocation, Zone *zone)
AllocationGroup (Node *node, AllocationType allocation, Node *size, Zone *zone)
~AllocationGroup ()=default
void Add (Node *object)
bool Contains (Node *object) const
bool IsYoungGenerationAllocation () const
AllocationType allocation () const
Node * size () const
Private Member Functions
DISALLOW_IMPLICIT_CONSTRUCTORS (AllocationGroup)
Static Private Member Functions
static AllocationType CheckAllocationType (AllocationType allocation)
Private Attributes
ZoneSet< NodeId > node_ids_
AllocationType const allocation_
Node *const size_
Detailed Description
Definition at line 28 of file memory-lowering.cc.
Constructor & Destructor Documentation
AllocationGroup() [1/2]
v8::internal::compiler::MemoryLowering::AllocationGroup::AllocationGroup (Node * node, AllocationType allocation, Zone * zone)
Definition at line 726 of file memory-lowering.cc.
    : node_ids_(zone),
      allocation_(CheckAllocationType(allocation)),
      size_(nullptr) {
  node_ids_.insert(node->id());
}
References v8::internal::compiler::Node::id(), and node_ids_.
AllocationGroup() [2/2]
v8::internal::compiler::MemoryLowering::AllocationGroup::AllocationGroup (Node * node, AllocationType allocation, Node * size, Zone * zone)
Definition at line 735 of file memory-lowering.cc.
    : node_ids_(zone),
      allocation_(CheckAllocationType(allocation)),
      size_(size) {
  node_ids_.insert(node->id());
}
References v8::internal::compiler::Node::id(), and node_ids_.
 AllocationGroup()
v8::internal::compiler::MemoryLowering::AllocationGroup::~AllocationGroup () [default]
Member Function Documentation
Add()
void v8::internal::compiler::MemoryLowering::AllocationGroup::Add (Node * object)
Definition at line 744 of file memory-lowering.cc.
                                                  {
  node_ids_.insert(node->id());
}
References v8::internal::compiler::Node::id().
Referenced by v8::internal::compiler::MemoryLowering::ReduceAllocateRaw().
allocation()
AllocationType v8::internal::compiler::MemoryLowering::AllocationGroup::allocation () const [inline]
Definition at line 41 of file memory-lowering.cc.
{ return allocation_; }
References allocation_.
Referenced by CheckAllocationType(), IsYoungGenerationAllocation(), and v8::internal::compiler::MemoryLowering::ReduceAllocateRaw().
CheckAllocationType()
static AllocationType v8::internal::compiler::MemoryLowering::AllocationGroup::CheckAllocationType (AllocationType allocation) [inline], [static], [private]
Definition at line 49 of file memory-lowering.cc.
                                                                              {
    // For non-generational heap, all young allocations are redirected to old
    // space.
    if (v8_flags.single_generation && allocation == AllocationType::kYoung) {
      return AllocationType::kOld;
    }
    return allocation;
  }
References allocation(), v8::internal::kOld, v8::internal::kYoung, and v8::internal::v8_flags.
Contains()
bool v8::internal::compiler::MemoryLowering::AllocationGroup::Contains (Node * object) const
Definition at line 748 of file memory-lowering.cc.
                                                             {
  // Additions should stay within the same allocated object, so it's safe to
  // ignore them.
  while (node_ids_.find(node->id()) == node_ids_.end()) {
    switch (node->opcode()) {
      case IrOpcode::kBitcastTaggedToWord:
      case IrOpcode::kBitcastWordToTagged:
      case IrOpcode::kInt32Add:
      case IrOpcode::kInt64Add:
        node = NodeProperties::GetValueInput(node, 0);
        break;
      default:
        return false;
    }
  }
  return true;
}
References v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::Node::id(), and v8::internal::compiler::Node::opcode().
Referenced by v8::internal::compiler::MemoryLowering::ComputeWriteBarrierKind().
DISALLOW_IMPLICIT_CONSTRUCTORS()
v8::internal::compiler::MemoryLowering::AllocationGroup::DISALLOW_IMPLICIT_CONSTRUCTORS (AllocationGroup) [private]
IsYoungGenerationAllocation()
bool v8::internal::compiler::MemoryLowering::AllocationGroup::IsYoungGenerationAllocation () const [inline]
Definition at line 37 of file memory-lowering.cc.
                                           {
    return allocation() == AllocationType::kYoung;
  }
References allocation(), and v8::internal::kYoung.
size()
Node* v8::internal::compiler::MemoryLowering::AllocationGroup::size () const [inline]
Definition at line 42 of file memory-lowering.cc.
{ return size_; }
References size_.
Referenced by v8::internal::compiler::MemoryLowering::ReduceAllocateRaw().
Member Data Documentation
allocation_
AllocationType const v8::internal::compiler::MemoryLowering::AllocationGroup::allocation_ [private]
Definition at line 46 of file memory-lowering.cc.
Referenced by allocation().
node_ids_
ZoneSet<NodeId> v8::internal::compiler::MemoryLowering::AllocationGroup::node_ids_ [private]
Definition at line 45 of file memory-lowering.cc.
Referenced by AllocationGroup().
size_
Node* const v8::internal::compiler::MemoryLowering::AllocationGroup::size_ [private]
Definition at line 47 of file memory-lowering.cc.
Referenced by size().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/memory-lowering.cc