cppgc::internal::WriteBarrier Class Reference
#include <write-barrier.h>
Classes
class FlagUpdater
struct Params
Public Types
enum class Type : uint8_t { kNone
, kMarking
, kGenerational
 }
enum class GenerationalBarrierType : uint8_t { kPreciseSlot
, kPreciseUncompressedSlot
, kImpreciseSlot
 }
enum class ValueMode { kValuePresent
, kNoValuePresent
 }
Static Public Member Functions
static Type GetWriteBarrierType (const void *slot, const void *value, Params &params)
template<typename MemberStorage >
static Type GetWriteBarrierType (const void *slot, MemberStorage, Params &params)
template<typename HeapHandleCallback >
static Type GetWriteBarrierType (const void *slot, Params &params, HeapHandleCallback callback)
static Type GetWriteBarrierType (const void *value, Params &params)
static void DijkstraMarkingBarrier (const Params &params, const void *object)
static void DijkstraMarkingBarrierRange (const Params &params, const void *first_element, size_t element_size, size_t number_of_elements, TraceCallback trace_callback)
static void SteeleMarkingBarrier (const Params &params, const void *object)
template<GenerationalBarrierType >
static void GenerationalBarrier (const Params &params, const void *slot)
static void CheckParams (Type expected_type, const Params &params)
static bool IsEnabled ()
Private Types
using WriteBarrierTypePolicy = WriteBarrierTypeForNonCagedHeapPolicy
Private Member Functions
WriteBarrier ()=delete
Static Private Member Functions
static void DijkstraMarkingBarrierSlow (const void *value)
static void DijkstraMarkingBarrierSlowWithSentinelCheck (const void *value)
static void DijkstraMarkingBarrierRangeSlow (HeapHandle &heap_handle, const void *first_element, size_t element_size, size_t number_of_elements, TraceCallback trace_callback)
static void SteeleMarkingBarrierSlow (const void *value)
static void SteeleMarkingBarrierSlowWithSentinelCheck (const void *value)
Static Private Attributes
static AtomicEntryFlag write_barrier_enabled_
Detailed Description
Definition at line 39 of file write-barrier.h.
Member Typedef Documentation
WriteBarrierTypePolicy
using cppgc::internal::WriteBarrier::WriteBarrierTypePolicy = WriteBarrierTypeForNonCagedHeapPolicy [private]
Definition at line 126 of file write-barrier.h.
Member Enumeration Documentation
GenerationalBarrierType
enum cppgc::internal::WriteBarrier::GenerationalBarrierType : uint8_t [strong]
Enumerator
kPreciseSlot
kPreciseUncompressedSlot
kImpreciseSlot
Definition at line 47 of file write-barrier.h.
                                     : uint8_t {
    kPreciseSlot,
    kPreciseUncompressedSlot,
    kImpreciseSlot,
  };
Type
enum cppgc::internal::WriteBarrier::Type : uint8_t [strong]
Enumerator
kNone
kMarking
kGenerational
Definition at line 41 of file write-barrier.h.
                  : uint8_t {
    kNone,
    kMarking,
    kGenerational,
  };
ValueMode
enum cppgc::internal::WriteBarrier::ValueMode [strong]
Enumerator
kValuePresent
kNoValuePresent
Definition at line 64 of file write-barrier.h.
                       {
    kValuePresent,
    kNoValuePresent,
  };
Constructor & Destructor Documentation
WriteBarrier()
cppgc::internal::WriteBarrier::WriteBarrier () [private], [delete]
Member Function Documentation
CheckParams()
static void cppgc::internal::WriteBarrier::CheckParams (Type expected_type, const Params & params) [inline], [static]
Definition at line 112 of file write-barrier.h.
{}
Referenced by DijkstraMarkingBarrier(), DijkstraMarkingBarrierRange(), and SteeleMarkingBarrier().
DijkstraMarkingBarrier()
void cppgc::internal::WriteBarrier::DijkstraMarkingBarrier (const Params & params, const void * object) [inline], [static]
Definition at line 419 of file write-barrier.h.
                                                              {
  CheckParams(Type::kMarking, params);
#if defined(CPPGC_CAGED_HEAP)
  // Caged heap already filters out sentinels.
  DijkstraMarkingBarrierSlow(object);
#else // !CPPGC_CAGED_HEAP
  DijkstraMarkingBarrierSlowWithSentinelCheck(object);
#endif // !CPPGC_CAGED_HEAP
}
References CheckParams(), DijkstraMarkingBarrierSlow(), DijkstraMarkingBarrierSlowWithSentinelCheck(), and kMarking.
Referenced by cppgc::subtle::HeapConsistency::DijkstraWriteBarrier(), and cppgc::internal::DijkstraWriteBarrierPolicy::WriteBarrier().
DijkstraMarkingBarrierRange()
void cppgc::internal::WriteBarrier::DijkstraMarkingBarrierRange (const Params & params, const void * first_element, size_t element_size, size_t number_of_elements, TraceCallback trace_callback) [inline], [static]
Definition at line 431 of file write-barrier.h.
                                                                             {
  CheckParams(Type::kMarking, params);
  DijkstraMarkingBarrierRangeSlow(*params.heap, first_element, element_size,
                                  number_of_elements, trace_callback);
}
References CheckParams(), DijkstraMarkingBarrierRangeSlow(), cppgc::internal::WriteBarrier::Params::heap, and kMarking.
Referenced by cppgc::subtle::HeapConsistency::DijkstraWriteBarrierRange().
DijkstraMarkingBarrierRangeSlow()
void cppgc::internal::WriteBarrier::DijkstraMarkingBarrierRangeSlow (HeapHandle & heap_handle, const void * first_element, size_t element_size, size_t number_of_elements, TraceCallback trace_callback) [static], [private]
Definition at line 53 of file write-barrier.cc.
                                                             {
  auto& heap_base = HeapBase::From(heap_handle);
  // GetWriteBarrierType() checks marking state.
  DCHECK(heap_base.marker());
  // No write barriers should be executed from atomic pause marking.
  DCHECK(!heap_base.in_atomic_pause());
  cppgc::subtle::DisallowGarbageCollectionScope disallow_gc_scope(heap_base);
  const char* array = static_cast<const char*>(first_element);
  while (number_of_elements-- > 0) {
    trace_callback(&heap_base.marker()->Visitor(), array);
    array += element_size;
  }
}
References DCHECK, and cppgc::internal::HeapBase::From().
Referenced by DijkstraMarkingBarrierRange().
DijkstraMarkingBarrierSlow()
void cppgc::internal::WriteBarrier::DijkstraMarkingBarrierSlow (const void * value) [static], [private]
Definition at line 36 of file write-barrier.cc.
                                                               {
  const BasePage* page = BasePage::FromPayload(value);
  const auto& heap = page->heap();
  // GetWriteBarrierType() checks marking state.
  DCHECK(heap.marker());
  // No write barriers should be executed from atomic pause marking.
  DCHECK(!heap.in_atomic_pause());
  DCHECK(heap.is_incremental_marking_in_progress());
  auto& header =
      const_cast<HeapObjectHeader&>(page->ObjectHeaderFromInnerAddress(value));
  heap.marker()->WriteBarrierForObject<MarkerBase::WriteBarrierType::kDijkstra>(
      header);
}
References DCHECK, cppgc::internal::BasePage::FromPayload(), cppgc::internal::BasePage::heap(), cppgc::internal::MarkerBase::kDijkstra, cppgc::internal::BasePage::ObjectHeaderFromInnerAddress(), and v8::internal::value.
Referenced by DijkstraMarkingBarrier(), and DijkstraMarkingBarrierSlowWithSentinelCheck().
DijkstraMarkingBarrierSlowWithSentinelCheck()
void cppgc::internal::WriteBarrier::DijkstraMarkingBarrierSlowWithSentinelCheck (const void * value) [static], [private]
Definition at line 28 of file write-barrier.cc.
                       {
  if (!value || value == kSentinelPointer) return;
  DijkstraMarkingBarrierSlow(value);
}
References DijkstraMarkingBarrierSlow(), cppgc::kSentinelPointer, and v8::internal::value.
Referenced by DijkstraMarkingBarrier().
GenerationalBarrier()
template<GenerationalBarrierType >
static void cppgc::internal::WriteBarrier::GenerationalBarrier (const Params & params, const void * slot) [inline], [static]
Definition at line 105 of file write-barrier.h.
                                                             {}
Referenced by cppgc::subtle::HeapConsistency::GenerationalBarrier(), cppgc::subtle::HeapConsistency::GenerationalBarrierForSourceObject(), cppgc::subtle::HeapConsistency::GenerationalBarrierForUncompressedSlot(), and cppgc::internal::DijkstraWriteBarrierPolicy::WriteBarrier().
GetWriteBarrierType() [1/4]
WriteBarrier::Type cppgc::internal::WriteBarrier::GetWriteBarrierType (const void * slot, const void * value, WriteBarrier::Params & params) [inline], [static]
Definition at line 388 of file write-barrier.h.
                                                                     {
  return WriteBarrierTypePolicy::Get<ValueMode::kValuePresent>(slot, value,
                                                               params, []() {});
}
References v8::internal::value.
Referenced by cppgc::internal::DijkstraWriteBarrierPolicy::AssigningBarrier(), and cppgc::subtle::HeapConsistency::GetWriteBarrierType().
GetWriteBarrierType() [2/4]
template<typename MemberStorage >
WriteBarrier::Type cppgc::internal::WriteBarrier::GetWriteBarrierType (const void * slot, MemberStorage value, WriteBarrier::Params & params) [inline], [static]
Definition at line 396 of file write-barrier.h.
                                                                       {
  return WriteBarrierTypePolicy::Get<ValueMode::kValuePresent>(slot, value,
                                                               params, []() {});
}
References v8::internal::value.
GetWriteBarrierType() [3/4]
template<typename HeapHandleCallback >
WriteBarrier::Type cppgc::internal::WriteBarrier::GetWriteBarrierType (const void * slot, WriteBarrier::Params & params, HeapHandleCallback callback) [inline], [static]
Definition at line 404 of file write-barrier.h.
                                 {
  return WriteBarrierTypePolicy::Get<ValueMode::kNoValuePresent>(
      slot, nullptr, params, callback);
}
GetWriteBarrierType() [4/4]
WriteBarrier::Type cppgc::internal::WriteBarrier::GetWriteBarrierType (const void * value, WriteBarrier::Params & params) [inline], [static]
Definition at line 412 of file write-barrier.h.
                                                   {
  return WriteBarrierTypePolicy::Get<ValueMode::kValuePresent>(value, params,
                                                               []() {});
}
References v8::internal::value.
IsEnabled()
static bool cppgc::internal::WriteBarrier::IsEnabled () [inline], [static]
Definition at line 118 of file write-barrier.h.
{ return write_barrier_enabled_.MightBeEntered(); }
Referenced by cppgc::internal::DijkstraWriteBarrierPolicy::AssigningBarrier(), cppgc::internal::WriteBarrierTypeForNonCagedHeapPolicy::ValueModeDispatch< WriteBarrier::ValueMode::kNoValuePresent >::Get(), cppgc::internal::WriteBarrierTypeForNonCagedHeapPolicy::ValueModeDispatch< WriteBarrier::ValueMode::kValuePresent >::Get(), and cppgc::internal::PlatformAwareObjectStartBitmap::ShouldForceNonAtomic().
SteeleMarkingBarrier()
void cppgc::internal::WriteBarrier::SteeleMarkingBarrier (const Params & params, const void * object) [inline], [static]
Definition at line 442 of file write-barrier.h.
                                                            {
  CheckParams(Type::kMarking, params);
#if defined(CPPGC_CAGED_HEAP)
  // Caged heap already filters out sentinels.
  SteeleMarkingBarrierSlow(object);
#else // !CPPGC_CAGED_HEAP
  SteeleMarkingBarrierSlowWithSentinelCheck(object);
#endif // !CPPGC_CAGED_HEAP
}
References CheckParams(), kMarking, SteeleMarkingBarrierSlow(), and SteeleMarkingBarrierSlowWithSentinelCheck().
Referenced by cppgc::subtle::HeapConsistency::SteeleWriteBarrier().
SteeleMarkingBarrierSlow()
void cppgc::internal::WriteBarrier::SteeleMarkingBarrierSlow (const void * value) [static], [private]
Definition at line 80 of file write-barrier.cc.
                                                             {
  const BasePage* page = BasePage::FromPayload(value);
  const auto& heap = page->heap();
  // GetWriteBarrierType() checks marking state.
  DCHECK(heap.marker());
  // No write barriers should be executed from atomic pause marking.
  DCHECK(!heap.in_atomic_pause());
  DCHECK(heap.is_incremental_marking_in_progress());
  auto& header =
      const_cast<HeapObjectHeader&>(page->ObjectHeaderFromInnerAddress(value));
  heap.marker()->WriteBarrierForObject<MarkerBase::WriteBarrierType::kSteele>(
      header);
}
References DCHECK, cppgc::internal::BasePage::FromPayload(), cppgc::internal::BasePage::heap(), cppgc::internal::MarkerBase::kSteele, cppgc::internal::BasePage::ObjectHeaderFromInnerAddress(), and v8::internal::value.
Referenced by SteeleMarkingBarrier(), and SteeleMarkingBarrierSlowWithSentinelCheck().
SteeleMarkingBarrierSlowWithSentinelCheck()
void cppgc::internal::WriteBarrier::SteeleMarkingBarrierSlowWithSentinelCheck (const void * value) [static], [private]
Definition at line 72 of file write-barrier.cc.
                       {
  if (!value || value == kSentinelPointer) return;
  SteeleMarkingBarrierSlow(value);
}
References cppgc::kSentinelPointer, SteeleMarkingBarrierSlow(), and v8::internal::value.
Referenced by SteeleMarkingBarrier().
Member Data Documentation
write_barrier_enabled_
AtomicEntryFlag cppgc::internal::WriteBarrier::write_barrier_enabled_ [static], [private]
Definition at line 153 of file write-barrier.h.
Referenced by cppgc::internal::WriteBarrier::FlagUpdater::Enter(), and cppgc::internal::WriteBarrier::FlagUpdater::Exit().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/cppgc/internal/write-barrier.h
/mnt/V8SourceCode/src/heap/cppgc/write-barrier.cc