v8::internal::Debug Class Reference
#include <debug.h>
Classes
class TemporaryObjectsTracker
class ThreadLocal
Public Types
enum BreakPointKind { kRegular
, kInstrumentation
 }
Public Member Functions
Debug (const Debug &)=delete
Debug & operator= (const Debug &)=delete
void OnDebugBreak (DirectHandle< FixedArray > break_points_hit, StepAction stepAction, debug::BreakReasons break_reasons={})
debug::DebugDelegate::ActionAfterInstrumentation OnInstrumentationBreak ()
std::optional< Tagged< Object > > OnThrow (DirectHandle< Object > exception) V8_WARN_UNUSED_RESULT
void OnPromiseReject (DirectHandle< Object > promise, DirectHandle< Object > value)
void OnCompileError (DirectHandle< Script > script)
void OnAfterCompile (DirectHandle< Script > script)
void HandleDebugBreak (IgnoreBreakMode ignore_break_mode, debug::BreakReasons break_reasons)
void Break (JavaScriptFrame *frame, DirectHandle< JSFunction > break_target)
DirectHandle< FixedArray > GetLoadedScripts ()
std::optional< Tagged< DebugInfo > > TryGetDebugInfo (Tagged< SharedFunctionInfo > sfi)
bool HasDebugInfo (Tagged< SharedFunctionInfo > sfi)
bool HasCoverageInfo (Tagged< SharedFunctionInfo > sfi)
bool HasBreakInfo (Tagged< SharedFunctionInfo > sfi)
bool BreakAtEntry (Tagged< SharedFunctionInfo > sfi)
bool SetBreakpoint (Handle< SharedFunctionInfo > shared, DirectHandle< BreakPoint > break_point, int *source_position)
void ClearBreakPoint (DirectHandle< BreakPoint > break_point)
void ChangeBreakOnException (ExceptionBreakType type, bool enable)
bool IsBreakOnException (ExceptionBreakType type)
void SetTerminateOnResume ()
bool SetBreakPointForScript (Handle< Script > script, DirectHandle< String > condition, int *source_position, int *id)
bool SetBreakpointForFunction (Handle< SharedFunctionInfo > shared, DirectHandle< String > condition, int *id, BreakPointKind kind=kRegular)
void RemoveBreakpoint (int id)
MaybeHandle< FixedArray > GetHitBreakPoints (DirectHandle< DebugInfo > debug_info, int position, bool *has_break_points)
void PrepareStep (StepAction step_action)
void PrepareStepIn (DirectHandle< JSFunction > function)
void PrepareStepInSuspendedGenerator ()
void PrepareStepOnThrow ()
void ClearStepping ()
void PrepareRestartFrame (JavaScriptFrame *frame, int inlined_frame_index)
void SetBreakOnNextFunctionCall ()
void ClearBreakOnNextFunctionCall ()
void DiscardBaselineCode (Tagged< SharedFunctionInfo > shared)
void DiscardAllBaselineCode ()
void DeoptimizeFunction (DirectHandle< SharedFunctionInfo > shared)
void PrepareFunctionForDebugExecution (DirectHandle< SharedFunctionInfo > shared)
void InstallDebugBreakTrampoline ()
bool GetPossibleBreakpoints (Handle< Script > script, int start_position, int end_position, bool restrict_to_function, std::vector< BreakLocation > *locations)
bool IsFunctionBlackboxed (DirectHandle< Script > script, const int start, const int end)
bool IsBlackboxed (DirectHandle< SharedFunctionInfo > shared)
bool ShouldBeSkipped ()
bool CanBreakAtEntry (DirectHandle< SharedFunctionInfo > shared)
void SetDebugDelegate (debug::DebugDelegate *delegate)
bool EnsureBreakInfo (Handle< SharedFunctionInfo > shared)
void CreateBreakInfo (DirectHandle< SharedFunctionInfo > shared)
Handle< DebugInfo > GetOrCreateDebugInfo (DirectHandle< SharedFunctionInfo > shared)
void InstallCoverageInfo (DirectHandle< SharedFunctionInfo > shared, DirectHandle< CoverageInfo > coverage_info)
void RemoveAllCoverageInfos ()
Handle< Object > FindInnermostContainingFunctionInfo (Handle< Script > script, int position)
Handle< SharedFunctionInfo > FindClosestSharedFunctionInfoFromPosition (int position, Handle< Script > script, Handle< SharedFunctionInfo > outer_shared)
bool FindSharedFunctionInfosIntersectingRange (Handle< Script > script, int start_position, int end_position, std::vector< Handle< SharedFunctionInfo >> *candidates)
MaybeDirectHandle< SharedFunctionInfo > GetTopLevelWithRecompile (Handle< Script > script, bool *did_compile=nullptr)
bool IsBreakAtReturn (JavaScriptFrame *frame)
bool AllFramesOnStackAreBlackboxed ()
bool SetScriptSource (Handle< Script > script, Handle< String > source, bool preview, bool allow_top_frame_live_editing, debug::LiveEditResult *result)
int GetFunctionDebuggingId (DirectHandle< JSFunction > function)
char * ArchiveDebug (char *to)
char * RestoreDebug (char *from)
void FreeThreadResources ()
void Iterate (RootVisitor *v)
void InitThread (const ExecutionAccess &lock)
bool CheckExecutionState ()
void StartSideEffectCheckMode ()
void StopSideEffectCheckMode ()
void ApplySideEffectChecks (DirectHandle< DebugInfo > debug_info)
void ClearSideEffectChecks (DirectHandle< DebugInfo > debug_info)
void IgnoreSideEffectsOnNextCallTo (Handle< FunctionTemplateInfo > function)
bool PerformSideEffectCheck (DirectHandle< JSFunction > function, DirectHandle< Object > receiver)
void PrepareBuiltinForSideEffectCheck (Isolate *isolate, Builtin id)
bool PerformSideEffectCheckForAccessor (DirectHandle< AccessorInfo > accessor_info, DirectHandle< Object > receiver, AccessorComponent component)
bool PerformSideEffectCheckForCallback (Handle< FunctionTemplateInfo > function)
bool PerformSideEffectCheckForInterceptor (DirectHandle< InterceptorInfo > interceptor_info)
bool PerformSideEffectCheckAtBytecode (InterpretedFrame *frame)
bool PerformSideEffectCheckForObject (DirectHandle< Object > object)
bool is_active () const
bool in_debug_scope () const
bool needs_check_on_function_call () const
void set_break_points_active (bool v)
bool break_points_active () const
StackFrameId break_frame_id ()
Handle< Object > return_value_handle ()
Tagged< Object > return_value ()
void set_return_value (Tagged< Object > value)
Address is_active_address ()
Address hook_on_function_call_address ()
Address suspended_generator_address ()
StepAction last_step_action ()
bool break_on_next_function_call () const
bool scheduled_break_on_function_call () const
bool IsRestartFrameScheduled () const
bool ShouldRestartFrame (StackFrameId id) const
void clear_restart_frame ()
int restart_inline_frame_index () const
bool break_disabled () const
void RemoveBreakInfoAndMaybeFree (DirectHandle< DebugInfo > debug_info)
void NotifyDebuggerPausedEventSent ()
void ClearMutedLocation ()
uint64_t IsolateId () const
void SetIsolateId (uint64_t id)
Static Public Member Functions
static DirectHandle< Object > GetSourceBreakLocations (Isolate *isolate, DirectHandle< SharedFunctionInfo > shared)
static int ArchiveSpacePerThread ()
static char * Iterate (RootVisitor *v, char *thread_storage)
Static Public Attributes
static const int kBreakAtEntryPosition = 0
static const int kInstrumentationId = -1
Private Types
using DebugInfoClearFunction = std::function< void(Handle< DebugInfo >)>
Private Member Functions
Debug (Isolate *isolate)
~Debug ()
void UpdateDebugInfosForExecutionMode ()
void UpdateState ()
void UpdateHookOnFunctionCall ()
void Unload ()
int CurrentFrameCount ()
bool ignore_events () const
void clear_suspended_generator ()
bool has_suspended_generator () const
void OnException (DirectHandle< Object > exception, MaybeDirectHandle< JSPromise > promise, v8::debug::ExceptionType exception_type)
void ProcessCompileEvent (bool has_compile_error, DirectHandle< Script > script)
int FindBreakablePosition (Handle< DebugInfo > debug_info, int source_position)
void ApplyBreakPoints (Handle< DebugInfo > debug_info)
void ClearBreakPoints (Handle< DebugInfo > debug_info)
void ClearAllBreakPoints ()
void FloodWithOneShot (Handle< SharedFunctionInfo > function, bool returns_only=false)
void ClearOneShot ()
void SetMutedLocation (DirectHandle< SharedFunctionInfo > function, const BreakLocation &location)
bool IsFrameBlackboxed (JavaScriptFrame *frame)
void ActivateStepOut (StackFrame *frame)
bool IsBreakOnInstrumentation (Handle< DebugInfo > debug_info, const BreakLocation &location)
bool IsBreakOnDebuggerStatement (DirectHandle< SharedFunctionInfo > function, const BreakLocation &location)
MaybeHandle< FixedArray > CheckBreakPoints (Handle< DebugInfo > debug_info, BreakLocation *location, bool *has_break_points)
MaybeDirectHandle< FixedArray > CheckBreakPointsForLocations (Handle< DebugInfo > debug_info, std::vector< BreakLocation > &break_locations, bool *has_break_points)
bool IsMutedAtAnyBreakLocation (DirectHandle< SharedFunctionInfo > function, const std::vector< BreakLocation > &locations)
bool CheckBreakPoint (DirectHandle< BreakPoint > break_point, bool is_break_at_entry)
void AssertDebugContext ()
void ThreadInit ()
void PrintBreakLocation ()
void ClearAllDebuggerHints ()
void ClearAllDebugInfos (const DebugInfoClearFunction &clear_function)
void SetTemporaryObjectTrackingDisabled (bool disabled)
bool GetTemporaryObjectTrackingDisabled () const
Static Private Member Functions
static void Iterate (RootVisitor *v, ThreadLocal *thread_local_data)
Private Attributes
debug::DebugDelegate * debug_delegate_ = nullptr
std::atomic< bool > is_active_
bool hook_on_function_call_
bool is_suppressed_
bool running_live_edit_ = false
bool break_disabled_
bool break_points_active_
bool break_on_caught_exception_
bool break_on_uncaught_exception_
bool side_effect_check_failed_
DebugInfoCollection debug_infos_
std::unique_ptr< TemporaryObjectsTracker > temporary_objects_
IndirectHandle< RegExpMatchInfo > regexp_match_info_
ThreadLocal thread_local_
IndirectHandle< FunctionTemplateInfo > ignore_side_effects_for_function_template_info_
Isolate * isolate_
uint64_t isolate_id_
Friends
class Isolate
class DebugScope
class DisableBreak
class DisableTemporaryObjectTracking
class LiveEdit
class SuppressDebug
DirectHandle< FixedArray > GetDebuggedFunctions ()
void CheckDebuggerUnloaded ()
Detailed Description
Definition at line 249 of file debug.h.
Member Typedef Documentation
DebugInfoClearFunction
using v8::internal::Debug::DebugInfoClearFunction = std::function<void(Handle<DebugInfo>)> [private]
Definition at line 591 of file debug.h.
Member Enumeration Documentation
BreakPointKind
enum v8::internal::Debug::BreakPointKind
Enumerator
kRegular
kInstrumentation
Definition at line 286 of file debug.h.
{ kRegular, kInstrumentation };
Constructor & Destructor Documentation
Debug() [1/2]
v8::internal::Debug::Debug (const Debug &) [delete]
Debug() [2/2]
v8::internal::Debug::Debug (Isolate * isolate) [explicit], [private]
Definition at line 171 of file debug.cc.
    : is_active_(false),
      hook_on_function_call_(false),
      is_suppressed_(false),
      break_disabled_(false),
      break_points_active_(true),
      break_on_caught_exception_(false),
      break_on_uncaught_exception_(false),
      side_effect_check_failed_(false),
      debug_infos_(isolate),
      isolate_(isolate),
      isolate_id_(0) {
  ThreadInit();
}
References ThreadInit().
 Debug()
v8::internal::Debug::~Debug () [private]
Definition at line 186 of file debug.cc.
{ DCHECK_NULL(debug_delegate_); }
References DCHECK_NULL, and debug_delegate_.
Member Function Documentation
ActivateStepOut()
void v8::internal::Debug::ActivateStepOut (StackFrame * frame) [private]
AllFramesOnStackAreBlackboxed()
bool v8::internal::Debug::AllFramesOnStackAreBlackboxed ()
Definition at line 2719 of file debug.cc.
                                          {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  HandleScope scope(isolate_);
  for (StackFrameIterator it(isolate_, isolate_->thread_local_top());
       !it.done(); it.Advance()) {
    StackFrame* frame = it.frame();
    if (frame->is_javascript() &&
        !IsFrameBlackboxed(JavaScriptFrame::cast(frame))) {
      return false;
    }
  }
  return true;
}
References v8::internal::JavaScriptFrame::cast(), v8::internal::StackFrameIteratorBase::done(), v8::internal::StackFrame::is_javascript(), IsFrameBlackboxed(), isolate_, RCS_SCOPE, and v8::internal::Isolate::thread_local_top().
Referenced by v8::debug::CanBreakProgram(), and HandleDebugBreak().
ApplyBreakPoints()
void v8::internal::Debug::ApplyBreakPoints (Handle< DebugInfo > debug_info) [private]
Definition at line 1046 of file debug.cc.
                                                         {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  DisallowGarbageCollection no_gc;
  if (debug_info->CanBreakAtEntry()) {
    debug_info->SetBreakAtEntry();
  } else {
    if (!debug_info->HasInstrumentedBytecodeArray()) return;
    Tagged<FixedArray> break_points = debug_info->break_points();
    for (int i = 0; i < break_points->length(); i++) {
      if (IsUndefined(break_points->get(i), isolate_)) continue;
      Tagged<BreakPointInfo> info = Cast<BreakPointInfo>(break_points->get(i));
      if (info->GetBreakPointCount(isolate_) == 0) continue;
      DCHECK(debug_info->HasInstrumentedBytecodeArray());
      BreakIterator it(debug_info);
      it.SkipToPosition(info->source_position());
      it.SetDebugBreak();
    }
  }
  debug_info->SetDebugExecutionMode(DebugInfo::kBreakpoints);
}
References v8::internal::DCHECK(), isolate_, v8::internal::DebugInfo::kBreakpoints, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, RCS_SCOPE, v8::internal::BreakIterator::SetDebugBreak(), and v8::internal::BreakIterator::SkipToPosition().
Referenced by ClearBreakPoint(), ClearOneShot(), SetBreakpoint(), and UpdateDebugInfosForExecutionMode().
ApplySideEffectChecks()
void v8::internal::Debug::ApplySideEffectChecks (DirectHandle< DebugInfo > debug_info)
Definition at line 3099 of file debug.cc.
                                                                    {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  DCHECK(debug_info->HasInstrumentedBytecodeArray());
  Handle<BytecodeArray> debug_bytecode(debug_info->DebugBytecodeArray(isolate_),
                                       isolate_);
  DebugEvaluate::ApplySideEffectChecks(debug_bytecode);
  debug_info->SetDebugExecutionMode(DebugInfo::kSideEffects);
}
References v8::internal::DebugEvaluate::ApplySideEffectChecks(), v8::internal::DCHECK(), isolate_, v8::internal::DebugInfo::kSideEffects, and RCS_SCOPE.
Referenced by PerformSideEffectCheck(), and UpdateDebugInfosForExecutionMode().
ArchiveDebug()
char * v8::internal::Debug::ArchiveDebug (char * to)
Definition at line 486 of file debug.cc.
                                       {
  MemCopy(storage, reinterpret_cast<char*>(&thread_local_),
          ArchiveSpacePerThread());
  return storage + ArchiveSpacePerThread();
}
References ArchiveSpacePerThread(), v8::internal::MemCopy(), and thread_local_.
Referenced by v8::internal::ThreadManager::EagerlyArchiveThread().
ArchiveSpacePerThread()
int v8::internal::Debug::ArchiveSpacePerThread () [static]
Definition at line 525 of file debug.cc.
{ return sizeof(ThreadLocal); }
Referenced by ArchiveDebug(), v8::internal::ArchiveSpacePerThread(), Iterate(), and RestoreDebug().
AssertDebugContext()
void v8::internal::Debug::AssertDebugContext () [inline], [private]
Definition at line 582 of file debug.h.
{ DCHECK(in_debug_scope()); }
References v8::internal::DCHECK().
Referenced by OnDebugBreak().
Break()
void v8::internal::Debug::Break (JavaScriptFrame * frame, DirectHandle< JSFunction > break_target)
Definition at line 639 of file debug.cc.
                                                         {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  // Just continue if breaks are disabled or debugger cannot be loaded.
  if (break_disabled()) return;
  // Enter the debugger.
  DebugScope debug_scope(this);
  DisableBreak no_recursive_break(this);
  // Return if we fail to retrieve debug info.
  Handle<SharedFunctionInfo> shared(break_target->shared(), isolate_);
  if (!EnsureBreakInfo(shared)) return;
  PrepareFunctionForDebugExecution(shared);
  Handle<DebugInfo> debug_info(TryGetDebugInfo(*shared).value(), isolate_);
  // Find the break location where execution has stopped.
  BreakLocation location = BreakLocation::FromFrame(debug_info, frame);
  const bool hitInstrumentationBreak =
      IsBreakOnInstrumentation(debug_info, location);
  bool shouldPauseAfterInstrumentation = false;
  if (hitInstrumentationBreak) {
    debug::DebugDelegate::ActionAfterInstrumentation action =
        OnInstrumentationBreak();
    switch (action) {
      case debug::DebugDelegate::ActionAfterInstrumentation::kPause:
        shouldPauseAfterInstrumentation = true;
        break;
      case debug::DebugDelegate::ActionAfterInstrumentation::
          kPauseIfBreakpointsHit:
        shouldPauseAfterInstrumentation = false;
        break;
      case debug::DebugDelegate::ActionAfterInstrumentation::kContinue:
        return;
    }
  }
  // Find actual break points, if any, and trigger debug break event.
  ClearMutedLocation();
  bool has_break_points;
  bool scheduled_break =
      scheduled_break_on_function_call() || shouldPauseAfterInstrumentation;
  MaybeHandle<FixedArray> break_points_hit =
      CheckBreakPoints(debug_info, &location, &has_break_points);
  if (!break_points_hit.is_null() || break_on_next_function_call() ||
      scheduled_break) {
    StepAction lastStepAction = last_step_action();
    debug::BreakReasons break_reasons;
    if (scheduled_break) {
      break_reasons.Add(debug::BreakReason::kScheduled);
    }
    // If it's a debugger statement, add the reason and then mute the location
    // so we don't stop a second time.
    bool is_debugger_statement = IsBreakOnDebuggerStatement(shared, location);
    if (is_debugger_statement) {
      break_reasons.Add(debug::BreakReason::kDebuggerStatement);
    }
    // Clear all current stepping setup.
    ClearStepping();
    // Notify the debug event listeners.
    OnDebugBreak(!break_points_hit.is_null()
                     ? break_points_hit.ToHandleChecked()
                     : isolate_->factory()->empty_fixed_array(),
                 lastStepAction, break_reasons);
    if (is_debugger_statement) {
      // Don't pause here a second time
      SetMutedLocation(shared, location);
    }
    return;
  }
  // Debug break at function entry, do not worry about stepping.
  if (location.IsDebugBreakAtEntry()) {
    DCHECK(debug_info->BreakAtEntry());
    return;
  }
  DCHECK_NOT_NULL(frame);
  // No break point. Check for stepping.
  StepAction step_action = last_step_action();
  int current_frame_count = CurrentFrameCount();
  int target_frame_count = thread_local_.target_frame_count_;
  int last_frame_count = thread_local_.last_frame_count_;
  // StepOut at not return position was requested and return break locations
  // were flooded with one shots.
  if (thread_local_.fast_forward_to_return_) {
    // We might hit an instrumentation breakpoint before running into a
    // return/suspend location.
    DCHECK(location.IsReturnOrSuspend() || hitInstrumentationBreak);
    // We have to ignore recursive calls to function.
    if (current_frame_count > target_frame_count) return;
    ClearStepping();
    PrepareStep(StepOut);
    return;
  }
  bool step_break = false;
  switch (step_action) {
    case StepNone:
      if (has_break_points) {
        SetMutedLocation(shared, location);
      }
      return;
    case StepOut:
      // StepOut should not break in a deeper frame than target frame.
      if (current_frame_count > target_frame_count) return;
      step_break = true;
      break;
    case StepOver:
      // StepOver should not break in a deeper frame than target frame.
      if (current_frame_count > target_frame_count) return;
      [[fallthrough]];
    case StepInto: {
      // StepInto and StepOver should enter "generator stepping" mode, except
      // for the implicit initial yield in generators, where it should simply
      // step out of the generator function.
      if (location.IsSuspend()) {
        DCHECK(!has_suspended_generator());
        ClearStepping();
        if (!IsGeneratorFunction(shared->kind()) ||
            location.generator_suspend_id() > 0) {
          thread_local_.suspended_generator_ =
              location.GetGeneratorObjectForSuspendedFrame(frame);
        } else {
          PrepareStep(StepOut);
        }
        return;
      }
      FrameSummary summary = FrameSummary::GetTop(frame);
      const bool frame_or_statement_changed =
          current_frame_count != last_frame_count ||
          thread_local_.last_statement_position_ !=
              summary.SourceStatementPosition();
      // If we stayed on the same frame and reached the same bytecode offset
      // since the last step, we are in a loop and should pause. Otherwise
      // we keep "stepping" through the loop without ever actually pausing.
      const bool potential_single_statement_loop =
          current_frame_count == last_frame_count &&
          thread_local_.last_bytecode_offset_ == summary.code_offset();
      step_break = step_break || location.IsReturn() ||
                   potential_single_statement_loop ||
                   frame_or_statement_changed;
      break;
    }
  }
  StepAction lastStepAction = last_step_action();
  // Clear all current stepping setup.
  ClearStepping();
  if (step_break) {
    // If it's a debugger statement, add the reason and then mute the location
    // so we don't stop a second time.
    debug::BreakReasons break_reasons;
    bool is_debugger_statement = IsBreakOnDebuggerStatement(shared, location);
    if (is_debugger_statement) {
      break_reasons.Add(debug::BreakReason::kDebuggerStatement);
    }
    // Notify the debug event listeners.
    OnDebugBreak(isolate_->factory()->empty_fixed_array(), lastStepAction,
                 break_reasons);
    if (is_debugger_statement) {
      // Don't pause here a second time
      SetMutedLocation(shared, location);
    }
  } else {
    // Re-prepare to continue.
    PrepareStep(step_action);
  }
}
References v8::base::EnumSet< E, T >::Add(), break_disabled(), break_on_next_function_call(), CheckBreakPoints(), ClearMutedLocation(), ClearStepping(), v8::internal::FrameSummary::code_offset(), CurrentFrameCount(), v8::internal::DCHECK(), DCHECK_NOT_NULL, EnsureBreakInfo(), v8::internal::Isolate::factory(), v8::internal::Debug::ThreadLocal::fast_forward_to_return_, v8::internal::BreakLocation::FromFrame(), v8::internal::BreakLocation::generator_suspend_id(), v8::internal::BreakLocation::GetGeneratorObjectForSuspendedFrame(), v8::internal::FrameSummary::GetTop(), has_suspended_generator(), v8::internal::MaybeHandle< T >::is_null(), IsBreakOnDebuggerStatement(), IsBreakOnInstrumentation(), v8::internal::BreakLocation::IsDebugBreakAtEntry(), v8::internal::IsGeneratorFunction(), isolate_, v8::internal::BreakLocation::IsReturn(), v8::internal::BreakLocation::IsReturnOrSuspend(), v8::internal::BreakLocation::IsSuspend(), v8::debug::DebugDelegate::kContinue, v8::debug::kDebuggerStatement, v8::debug::DebugDelegate::kPause, v8::debug::DebugDelegate::kPauseIfBreakpointsHit, v8::debug::kScheduled, v8::internal::Debug::ThreadLocal::last_bytecode_offset_, v8::internal::Debug::ThreadLocal::last_frame_count_, v8::internal::Debug::ThreadLocal::last_statement_position_, last_step_action(), OnDebugBreak(), OnInstrumentationBreak(), PrepareFunctionForDebugExecution(), PrepareStep(), RCS_SCOPE, scheduled_break_on_function_call(), SetMutedLocation(), v8::internal::FrameSummary::SourceStatementPosition(), v8::internal::StepInto, v8::internal::StepNone, v8::internal::StepOut, v8::internal::StepOver, v8::internal::Debug::ThreadLocal::suspended_generator_, v8::internal::Debug::ThreadLocal::target_frame_count_, thread_local_, v8::internal::MaybeHandle< T >::ToHandleChecked(), and TryGetDebugInfo().
break_disabled()
bool v8::internal::Debug::break_disabled () const [inline]
Definition at line 483 of file debug.h.
{ return break_disabled_; }
Referenced by Break(), HandleDebugBreak(), PrepareStepIn(), PrepareStepInSuspendedGenerator(), and PrepareStepOnThrow().
break_frame_id()
StackFrameId v8::internal::Debug::break_frame_id () [inline]
Definition at line 441 of file debug.h.
{ return thread_local_.break_frame_id_; }
Referenced by CheckBreakPoint(), CurrentFrameCount(), v8::internal::DebugScope::DebugScope(), and PrepareStep().
break_on_next_function_call()
bool v8::internal::Debug::break_on_next_function_call () const [inline]
Definition at line 461 of file debug.h.
                                           {
    return thread_local_.break_on_next_function_call_;
  }
Referenced by Break(), and PrepareStepIn().
break_points_active()
bool v8::internal::Debug::break_points_active () const [inline]
Definition at line 439 of file debug.h.
{ return break_points_active_; }
Referenced by v8::internal::anonymous_namespace{runtime-wasm.cc}::ExecuteWasmDebugBreaks().
BreakAtEntry()
bool v8::internal::Debug::BreakAtEntry (Tagged< SharedFunctionInfo > sfi)
Definition at line 2442 of file debug.cc.
                                                       {
  if (std::optional<Tagged<DebugInfo>> debug_info = TryGetDebugInfo(sfi)) {
    return debug_info.value()->BreakAtEntry();
  }
  return false;
}
References TryGetDebugInfo().
Referenced by v8::internal::SharedFunctionInfo::BreakAtEntry(), and v8::internal::Heap::InsertIntoRememberedSetFromCode::DebugBreakAtEntry().
CanBreakAtEntry()
bool v8::internal::Debug::CanBreakAtEntry (DirectHandle< SharedFunctionInfo > shared)
Definition at line 2734 of file debug.cc.
                                                                   {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  // Allow break at entry for builtin functions.
  if (shared->native() || shared->IsApiFunction()) {
    // Functions that are subject to debugging can have regular breakpoints.
    DCHECK(!shared->IsSubjectToDebugging());
    return true;
  }
  return false;
}
References v8::internal::DCHECK(), isolate_, and RCS_SCOPE.
Referenced by CreateBreakInfo(), and EnsureBreakInfo().
ChangeBreakOnException()
void v8::internal::Debug::ChangeBreakOnException (ExceptionBreakType type, bool enable)
Definition at line 1256 of file debug.cc.
                                                                       {
  if (type == BreakUncaughtException) {
    break_on_uncaught_exception_ = enable;
  } else {
    break_on_caught_exception_ = enable;
  }
}
References break_on_caught_exception_, break_on_uncaught_exception_, v8::internal::BreakUncaughtException, and v8::internal::tracing::type.
Referenced by v8::debug::ChangeBreakOnException().
CheckBreakPoint()
bool v8::internal::Debug::CheckBreakPoint (DirectHandle< BreakPoint > break_point, bool is_break_at_entry) [private]
Definition at line 924 of file debug.cc.
                                                    {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  HandleScope scope(isolate_);
  // Instrumentation breakpoints are handled separately.
  if (break_point->id() == kInstrumentationId) {
    return false;
  }
  if (!break_point->condition()->length()) return true;
  DirectHandle<String> condition(break_point->condition(), isolate_);
  MaybeDirectHandle<Object> maybe_result;
  DirectHandle<Object> result;
  if (is_break_at_entry) {
    maybe_result = DebugEvaluate::WithTopmostArguments(isolate_, condition);
  } else {
    // Since we call CheckBreakpoint only for deoptimized frame on top of stack,
    // we can use 0 as index of inlined frame.
    const int inlined_jsframe_index = 0;
    const bool throw_on_side_effect = false;
    maybe_result =
        DebugEvaluate::Local(isolate_, break_frame_id(), inlined_jsframe_index,
                             condition, throw_on_side_effect);
  }
  DirectHandle<Object> maybe_exception;
  bool exception_thrown = true;
  if (maybe_result.ToHandle(&result)) {
    exception_thrown = false;
  } else if (isolate_->has_exception()) {
    maybe_exception = direct_handle(isolate_->exception(), isolate_);
    isolate_->clear_exception();
  }
  CHECK(in_debug_scope());
  DisableBreak no_recursive_break(this);
  {
    RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebuggerCallback);
    debug_delegate_->BreakpointConditionEvaluated(
        v8::Utils::ToLocal(isolate_->native_context()), break_point->id(),
        exception_thrown, v8::Utils::ToLocal(maybe_exception));
  }
  return !result.is_null() ? Object::BooleanValue(*result, isolate_) : false;
}
References v8::internal::Object::BooleanValue(), break_frame_id(), v8::debug::DebugDelegate::BreakpointConditionEvaluated(), CHECK, v8::internal::Isolate::clear_exception(), debug_delegate_, v8::internal::direct_handle(), v8::internal::Isolate::exception(), v8::internal::Isolate::has_exception(), in_debug_scope(), isolate_, kInstrumentationId, v8::internal::DebugEvaluate::Local(), v8::internal::Isolate::native_context(), RCS_SCOPE, v8::base::internal::result, v8::internal::MaybeDirectHandle< T >::ToHandle(), and v8::internal::DebugEvaluate::WithTopmostArguments().
Referenced by GetHitBreakPoints().
CheckBreakPoints()
MaybeHandle< FixedArray > v8::internal::Debug::CheckBreakPoints (Handle< DebugInfo > debug_info, BreakLocation * location, bool * has_break_points) [private]
Definition at line 859 of file debug.cc.
                                                                        {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  bool has_break_points_to_check =
      break_points_active_ && location->HasBreakPoint(isolate_, debug_info);
  if (!has_break_points_to_check) {
    *has_break_points = false;
    return {};
  }
  return Debug::GetHitBreakPoints(debug_info, location->position(),
                                  has_break_points);
}
References break_points_active_, GetHitBreakPoints(), v8::internal::BreakLocation::HasBreakPoint(), isolate_, v8::internal::BreakLocation::position(), and RCS_SCOPE.
Referenced by Break(), and CheckBreakPointsForLocations().
CheckBreakPointsForLocations()
MaybeDirectHandle< FixedArray > v8::internal::Debug::CheckBreakPointsForLocations (Handle< DebugInfo > debug_info, std::vector< BreakLocation > & break_locations, bool * has_break_points) [private]
Definition at line 206 of file debug.cc.
                            {
  DirectHandle<FixedArray> break_points_hit =
      isolate_->factory()->NewFixedArray(
          debug_info->GetBreakPointCount(isolate_));
  int break_points_hit_count = 0;
  bool has_break_points_at_all = false;
  for (size_t i = 0; i < break_locations.size(); i++) {
    bool location_has_break_points;
    MaybeDirectHandle<FixedArray> check_result = CheckBreakPoints(
        debug_info, &break_locations[i], &location_has_break_points);
    has_break_points_at_all |= location_has_break_points;
    if (!check_result.is_null()) {
      DirectHandle<FixedArray> break_points_current_hit =
          check_result.ToHandleChecked();
      int num_objects = break_points_current_hit->length();
      for (int j = 0; j < num_objects; ++j) {
        break_points_hit->set(break_points_hit_count++,
                              break_points_current_hit->get(j));
      }
    }
  }
  *has_break_points = has_break_points_at_all;
  if (break_points_hit_count == 0) return {};
  break_points_hit->RightTrim(isolate_, break_points_hit_count);
  return break_points_hit;
}
References CheckBreakPoints(), v8::internal::Isolate::factory(), v8::internal::MaybeDirectHandle< T >::is_null(), isolate_, v8::internal::FactoryBase< Impl >::NewFixedArray(), and v8::internal::MaybeDirectHandle< T >::ToHandleChecked().
CheckExecutionState()
bool v8::internal::Debug::CheckExecutionState () [inline]
Definition at line 402 of file debug.h.
{ return is_active(); }
Referenced by v8::debug::PrepareRestartFrame(), and v8::debug::PrepareStep().
clear_restart_frame()
void v8::internal::Debug::clear_restart_frame () [inline]
Definition at line 475 of file debug.h.
                             {
    thread_local_.restart_frame_id_ = StackFrameId::NO_ID;
    thread_local_.restart_inline_frame_index_ = -1;
  }
References v8::internal::NO_ID.
Referenced by ClearStepping(), v8::internal::Deoptimizer::Deoptimizer(), ThreadInit(), and v8::internal::Isolate::UnwindAndFindHandler().
clear_suspended_generator()
void v8::internal::Debug::clear_suspended_generator () [inline], [private]
Definition at line 526 of file debug.h.
                                   {
    thread_local_.suspended_generator_ = Smi::zero();
  }
References v8::internal::Smi::zero().
Referenced by PrepareStep(), PrepareStepInSuspendedGenerator(), and ThreadInit().
ClearAllBreakPoints()
void v8::internal::Debug::ClearAllBreakPoints () [private]
Definition at line 1213 of file debug.cc.
                                {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  ClearAllDebugInfos([=, this](Handle<DebugInfo> info) {
    ClearBreakPoints(info);
    info->ClearBreakInfo(isolate_);
  });
#if V8_ENABLE_WEBASSEMBLY
  // Clear all wasm breakpoints.
  if (!wasm_scripts_with_break_points_.is_null()) {
    DisallowGarbageCollection no_gc;
    for (int idx = wasm_scripts_with_break_points_->length() - 1; idx >= 0;
         --idx) {
      Tagged<HeapObject> raw_wasm_script;
      if (wasm_scripts_with_break_points_->Get(idx).GetHeapObject(
              &raw_wasm_script)) {
        Tagged<Script> wasm_script = Cast<Script>(raw_wasm_script);
        WasmScript::ClearAllBreakpoints(wasm_script);
        wasm_script->wasm_native_module()->GetDebugInfo()->RemoveIsolate(
            isolate_);
      }
    }
    wasm_scripts_with_break_points_ = Handle<WeakArrayList>{};
  }
#endif // V8_ENABLE_WEBASSEMBLY
}
References v8::internal::WasmScript::ClearAllBreakpoints(), ClearAllDebugInfos(), ClearBreakPoints(), isolate_, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and RCS_SCOPE.
Referenced by Unload().
ClearAllDebuggerHints()
void v8::internal::Debug::ClearAllDebuggerHints () [private]
Definition at line 2353 of file debug.cc.
                                  {
  ClearAllDebugInfos(
      [=](DirectHandle<DebugInfo> info) { info->set_debugger_hints(0); });
}
References ClearAllDebugInfos().
Referenced by Unload().
ClearAllDebugInfos()
void v8::internal::Debug::ClearAllDebugInfos (const DebugInfoClearFunction & clear_function) [private]
Definition at line 2358 of file debug.cc.
                                                                           {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  HandleScope scope(isolate_);
  DebugInfoCollection::Iterator it(&debug_infos_);
  for (; it.HasNext(); it.Advance()) {
    Handle<DebugInfo> debug_info(it.Next(), isolate_);
    clear_function(debug_info);
    if (debug_info->IsEmpty()) it.DeleteNext();
  }
}
References v8::internal::DebugInfoCollection::Iterator::Advance(), debug_infos_, v8::internal::DebugInfoCollection::Iterator::DeleteNext(), v8::internal::DebugInfoCollection::Iterator::HasNext(), isolate_, v8::internal::DebugInfoCollection::Iterator::Next(), and RCS_SCOPE.
Referenced by ClearAllBreakPoints(), ClearAllDebuggerHints(), and RemoveAllCoverageInfos().
ClearBreakOnNextFunctionCall()
void v8::internal::Debug::ClearBreakOnNextFunctionCall ()
Definition at line 1320 of file debug.cc.
                                         {
  thread_local_.break_on_next_function_call_ = false;
  UpdateHookOnFunctionCall();
}
References v8::internal::Debug::ThreadLocal::break_on_next_function_call_, thread_local_, and UpdateHookOnFunctionCall().
ClearBreakPoint()
void v8::internal::Debug::ClearBreakPoint (DirectHandle< BreakPoint > break_point)
Definition at line 1086 of file debug.cc.
                                                                {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  HandleScope scope(isolate_);
  DebugInfoCollection::Iterator it(&debug_infos_);
  for (; it.HasNext(); it.Advance()) {
    Handle<DebugInfo> debug_info(it.Next(), isolate_);
    if (!debug_info->HasBreakInfo()) continue;
    DirectHandle<Object> result =
        DebugInfo::FindBreakPointInfo(isolate_, debug_info, break_point);
    if (IsUndefined(*result, isolate_)) continue;
    if (DebugInfo::ClearBreakPoint(isolate_, debug_info, break_point)) {
      ClearBreakPoints(debug_info);
      if (debug_info->GetBreakPointCount(isolate_) == 0) {
        debug_info->ClearBreakInfo(isolate_);
        if (debug_info->IsEmpty()) it.DeleteNext();
      } else {
        ApplyBreakPoints(debug_info);
      }
      return;
    }
  }
}
References v8::internal::DebugInfoCollection::Iterator::Advance(), ApplyBreakPoints(), v8::internal::DebugInfo::ClearBreakPoint(), ClearBreakPoints(), debug_infos_, v8::internal::DebugInfoCollection::Iterator::DeleteNext(), v8::internal::DebugInfo::FindBreakPointInfo(), v8::internal::DebugInfoCollection::Iterator::HasNext(), isolate_, v8::internal::DebugInfoCollection::Iterator::Next(), RCS_SCOPE, and v8::base::internal::result.
Referenced by RemoveBreakpoint().
ClearBreakPoints()
void v8::internal::Debug::ClearBreakPoints (Handle< DebugInfo > debug_info) [private]
Definition at line 1067 of file debug.cc.
                                                         {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  if (debug_info->CanBreakAtEntry()) {
    debug_info->ClearBreakAtEntry();
  } else {
    // If we attempt to clear breakpoints but none exist, simply return. This
    // can happen e.g. CoverageInfos exist but no breakpoints are set.
    if (!debug_info->HasInstrumentedBytecodeArray() ||
        !debug_info->HasBreakInfo()) {
      return;
    }
    DisallowGarbageCollection no_gc;
    for (BreakIterator it(debug_info); !it.Done(); it.Next()) {
      it.ClearDebugBreak();
    }
  }
}
References v8::internal::BreakIterator::Done(), isolate_, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and RCS_SCOPE.
Referenced by ClearAllBreakPoints(), ClearBreakPoint(), ClearOneShot(), SetBreakpoint(), and UpdateDebugInfosForExecutionMode().
ClearMutedLocation()
void v8::internal::Debug::ClearMutedLocation ()
Definition at line 1681 of file debug.cc.
                               {
  thread_local_.muted_function_ = Smi::zero();
  thread_local_.muted_position_ = -1;
}
References v8::internal::Debug::ThreadLocal::muted_function_, v8::internal::Debug::ThreadLocal::muted_position_, thread_local_, and v8::internal::Smi::zero().
Referenced by Break(), v8::internal::WasmScript::CheckBreakPoints(), and ClearStepping().
ClearOneShot()
void v8::internal::Debug::ClearOneShot () [private]
Definition at line 1667 of file debug.cc.
                         {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  // The current implementation just runs through all the breakpoints. When the
  // last break point for a function is removed that function is automatically
  // removed from the list.
  HandleScope scope(isolate_);
  DebugInfoCollection::Iterator it(&debug_infos_);
  for (; it.HasNext(); it.Advance()) {
    Handle<DebugInfo> debug_info(it.Next(), isolate_);
    ClearBreakPoints(debug_info);
    ApplyBreakPoints(debug_info);
  }
}
References v8::internal::DebugInfoCollection::Iterator::Advance(), ApplyBreakPoints(), ClearBreakPoints(), debug_infos_, v8::internal::DebugInfoCollection::Iterator::HasNext(), isolate_, v8::internal::DebugInfoCollection::Iterator::Next(), and RCS_SCOPE.
Referenced by ClearStepping(), PrepareStepOnThrow(), and RestoreDebug().
ClearSideEffectChecks()
void v8::internal::Debug::ClearSideEffectChecks (DirectHandle< DebugInfo > debug_info)
Definition at line 3108 of file debug.cc.
                                                                    {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  DCHECK(debug_info->HasInstrumentedBytecodeArray());
  Handle<BytecodeArray> debug_bytecode(debug_info->DebugBytecodeArray(isolate_),
                                       isolate_);
  DirectHandle<BytecodeArray> original(
      debug_info->OriginalBytecodeArray(isolate_), isolate_);
  for (interpreter::BytecodeArrayIterator it(debug_bytecode); !it.done();
       it.Advance()) {
    // Restore from original. This may copy only the scaling prefix, which is
    // correct, since we patch scaling prefixes to debug breaks if exists.
    debug_bytecode->set(it.current_offset(),
                        original->get(it.current_offset()));
  }
}
References v8::internal::DCHECK(), v8::internal::interpreter::BytecodeArrayIterator::done(), isolate_, and RCS_SCOPE.
Referenced by UpdateDebugInfosForExecutionMode().
ClearStepping()
void v8::internal::Debug::ClearStepping ()
Definition at line 1645 of file debug.cc.
                          {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  // Clear the various stepping setup.
  ClearOneShot();
  ClearMutedLocation();
  thread_local_.last_step_action_ = StepNone;
  thread_local_.last_statement_position_ = kNoSourcePosition;
  thread_local_.last_bytecode_offset_ = kFunctionEntryBytecodeOffset;
  thread_local_.ignore_step_into_function_ = Smi::zero();
  thread_local_.fast_forward_to_return_ = false;
  thread_local_.last_frame_count_ = -1;
  thread_local_.target_frame_count_ = -1;
  thread_local_.break_on_next_function_call_ = false;
  thread_local_.scheduled_break_on_next_function_call_ = false;
  clear_restart_frame();
  UpdateHookOnFunctionCall();
}
References v8::internal::Debug::ThreadLocal::break_on_next_function_call_, clear_restart_frame(), ClearMutedLocation(), ClearOneShot(), v8::internal::Debug::ThreadLocal::fast_forward_to_return_, v8::internal::Debug::ThreadLocal::ignore_step_into_function_, isolate_, v8::internal::kFunctionEntryBytecodeOffset, v8::internal::kNoSourcePosition, v8::internal::Debug::ThreadLocal::last_bytecode_offset_, v8::internal::Debug::ThreadLocal::last_frame_count_, v8::internal::Debug::ThreadLocal::last_statement_position_, v8::internal::Debug::ThreadLocal::last_step_action_, RCS_SCOPE, v8::internal::Debug::ThreadLocal::scheduled_break_on_next_function_call_, v8::internal::StepNone, v8::internal::Debug::ThreadLocal::target_frame_count_, thread_local_, UpdateHookOnFunctionCall(), and v8::internal::Smi::zero().
Referenced by Break(), v8::debug::ClearStepping(), v8::internal::anonymous_namespace{runtime-wasm.cc}::ExecuteWasmDebugBreaks(), HandleDebugBreak(), v8::debug::PrepareRestartFrame(), v8::debug::PrepareStep(), PrepareStep(), and Unload().
CreateBreakInfo()
void v8::internal::Debug::CreateBreakInfo (DirectHandle< SharedFunctionInfo > shared)
Definition at line 2297 of file debug.cc.
                                                                   {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  HandleScope scope(isolate_);
  DirectHandle<DebugInfo> debug_info = GetOrCreateDebugInfo(shared);
  // Initialize with break information.
  DCHECK(!debug_info->HasBreakInfo());
  Factory* factory = isolate_->factory();
  DirectHandle<FixedArray> break_points(
      factory->NewFixedArray(DebugInfo::kEstimatedNofBreakPointsInFunction));
  int flags = debug_info->flags(kRelaxedLoad);
  flags |= DebugInfo::kHasBreakInfo;
  if (CanBreakAtEntry(shared)) flags |= DebugInfo::kCanBreakAtEntry;
  debug_info->set_flags(flags, kRelaxedStore);
  debug_info->set_break_points(*break_points);
  SharedFunctionInfo::EnsureSourcePositionsAvailable(isolate_, shared);
}
References CanBreakAtEntry(), v8::internal::DCHECK(), v8::internal::SharedFunctionInfo::EnsureSourcePositionsAvailable(), v8::internal::Isolate::factory(), v8::internal::flags, GetOrCreateDebugInfo(), isolate_, v8::internal::DebugInfo::kEstimatedNofBreakPointsInFunction, v8::kRelaxedLoad, v8::kRelaxedStore, v8::internal::FactoryBase< Impl >::NewFixedArray(), and RCS_SCOPE.
Referenced by EnsureBreakInfo(), and FindInnermostContainingFunctionInfo().
CurrentFrameCount()
int v8::internal::Debug::CurrentFrameCount () [private]
Definition at line 2791 of file debug.cc.
                             {
  DebuggableStackFrameIterator it(isolate_);
  if (break_frame_id() != StackFrameId::NO_ID) {
    // Skip to break frame.
    DCHECK(in_debug_scope());
    while (!it.done() && it.frame()->id() != break_frame_id()) it.Advance();
  }
  int counter = 0;
  for (; !it.done(); it.Advance()) {
    counter += it.FrameFunctionCount();
  }
  return counter;
}
References v8::internal::DebuggableStackFrameIterator::Advance(), break_frame_id(), v8::internal::DCHECK(), v8::internal::DebuggableStackFrameIterator::done(), v8::internal::DebuggableStackFrameIterator::frame(), v8::internal::DebuggableStackFrameIterator::FrameFunctionCount(), v8::internal::StackFrame::id(), in_debug_scope(), isolate_, and v8::internal::NO_ID.
Referenced by Break(), PrepareStep(), PrepareStepOnThrow(), and RestoreDebug().
DeoptimizeFunction()
void v8::internal::Debug::DeoptimizeFunction (DirectHandle< SharedFunctionInfo > shared)
Definition at line 1790 of file debug.cc.
                                                                      {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  if (shared->HasBaselineCode()) {
    DiscardBaselineCode(*shared);
  }
  Deoptimizer::DeoptimizeAllOptimizedCodeWithFunction(isolate_, shared);
}
References v8::internal::Deoptimizer::DeoptimizeAllOptimizedCodeWithFunction(), DiscardBaselineCode(), isolate_, and RCS_SCOPE.
Referenced by v8::internal::LiveEdit::PatchScript(), and PrepareFunctionForDebugExecution().
DiscardAllBaselineCode()
void v8::internal::Debug::DiscardAllBaselineCode ()
Definition at line 1767 of file debug.cc.
                                   {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  DiscardBaselineCodeVisitor visitor;
  visitor.VisitThread(isolate_, isolate_->thread_local_top());
  HeapObjectIterator iterator(isolate_->heap());
  auto trampoline = BUILTIN_CODE(isolate_, InterpreterEntryTrampoline);
  isolate_->thread_manager()->IterateArchivedThreads(&visitor);
  for (Tagged<HeapObject> obj = iterator.Next(); !obj.is_null();
       obj = iterator.Next()) {
    if (IsJSFunction(obj)) {
      Tagged<JSFunction> fun = Cast<JSFunction>(obj);
      if (fun->ActiveTierIsBaseline(isolate_)) {
        fun->UpdateCode(isolate_, *trampoline);
      }
    } else if (IsSharedFunctionInfo(obj)) {
      Tagged<SharedFunctionInfo> shared = Cast<SharedFunctionInfo>(obj);
      if (shared->HasBaselineCode()) {
        shared->FlushBaselineCode();
      }
    }
  }
}
References BUILTIN_CODE, v8::internal::Isolate::heap(), v8::internal::Tagged< HeapObject >::is_null(), isolate_, v8::internal::ThreadManager::IterateArchivedThreads(), v8::internal::HeapObjectIterator::Next(), RCS_SCOPE, v8::internal::Isolate::thread_local_top(), and v8::internal::Isolate::thread_manager().
Referenced by PrepareFunctionForDebugExecution().
DiscardBaselineCode()
void v8::internal::Debug::DiscardBaselineCode (Tagged< SharedFunctionInfo > shared)
Definition at line 1746 of file debug.cc.
                                                                 {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  DCHECK(shared->HasBaselineCode());
  DiscardBaselineCodeVisitor visitor(shared);
  visitor.VisitThread(isolate_, isolate_->thread_local_top());
  isolate_->thread_manager()->IterateArchivedThreads(&visitor);
  // TODO(v8:11429): Avoid this heap walk somehow.
  HeapObjectIterator iterator(isolate_->heap());
  auto trampoline = BUILTIN_CODE(isolate_, InterpreterEntryTrampoline);
  shared->FlushBaselineCode();
  for (Tagged<HeapObject> obj = iterator.Next(); !obj.is_null();
       obj = iterator.Next()) {
    if (IsJSFunction(obj)) {
      Tagged<JSFunction> fun = Cast<JSFunction>(obj);
      if (fun->shared() == shared && fun->ActiveTierIsBaseline(isolate_)) {
        fun->UpdateCode(isolate_, *trampoline);
      }
    }
  }
}
References BUILTIN_CODE, v8::internal::DCHECK(), v8::internal::Isolate::heap(), v8::internal::Tagged< HeapObject >::is_null(), isolate_, v8::internal::ThreadManager::IterateArchivedThreads(), v8::internal::HeapObjectIterator::Next(), RCS_SCOPE, v8::internal::Isolate::thread_local_top(), and v8::internal::Isolate::thread_manager().
Referenced by DeoptimizeFunction().
EnsureBreakInfo()
bool v8::internal::Debug::EnsureBreakInfo (Handle< SharedFunctionInfo > shared)
Definition at line 2277 of file debug.cc.
                                                             {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  // Return if we already have the break info for shared.
  if (shared->HasBreakInfo(isolate_)) {
    DCHECK(shared->is_compiled());
    return true;
  }
  if (!shared->IsSubjectToDebugging() && !CanBreakAtEntry(shared)) {
    return false;
  }
  IsCompiledScope is_compiled_scope = shared->is_compiled_scope(isolate_);
  if (!is_compiled_scope.is_compiled() &&
      !Compiler::Compile(isolate_, shared, Compiler::CLEAR_EXCEPTION,
                         &is_compiled_scope, CreateSourcePositions::kYes)) {
    return false;
  }
  CreateBreakInfo(shared);
  return true;
}
References CanBreakAtEntry(), v8::internal::Compiler::CLEAR_EXCEPTION, v8::internal::Compiler::Compile(), CreateBreakInfo(), v8::internal::DCHECK(), v8::internal::IsCompiledScope::is_compiled(), isolate_, v8::internal::kYes, and RCS_SCOPE.
Referenced by Break(), FindSharedFunctionInfosIntersectingRange(), FloodWithOneShot(), GetPossibleBreakpoints(), PrepareStep(), SetBreakpoint(), and SetBreakPointForScript().
FindBreakablePosition()
int v8::internal::Debug::FindBreakablePosition (Handle< DebugInfo > debug_info, int source_position) [private]
Definition at line 1033 of file debug.cc.
                                                      {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  if (debug_info->CanBreakAtEntry()) {
    return kBreakAtEntryPosition;
  } else {
    DCHECK(debug_info->HasInstrumentedBytecodeArray());
    BreakIterator it(debug_info);
    it.SkipToPosition(source_position);
    return it.position();
  }
}
References v8::internal::DCHECK(), isolate_, kBreakAtEntryPosition, v8::internal::BreakIterator::position(), RCS_SCOPE, and v8::internal::BreakIterator::SkipToPosition().
Referenced by FindClosestSharedFunctionInfoFromPosition(), and SetBreakpoint().
FindClosestSharedFunctionInfoFromPosition()
Handle< SharedFunctionInfo > v8::internal::Debug::FindClosestSharedFunctionInfoFromPosition (int position, Handle< Script > script, Handle< SharedFunctionInfo > outer_shared)
Definition at line 2104 of file debug.cc.
                                             {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  Handle<DebugInfo> outer_debug_info(TryGetDebugInfo(*outer_shared).value(),
                                     isolate_);
  CHECK(outer_debug_info->HasBreakInfo());
  int closest_position = FindBreakablePosition(outer_debug_info, position);
  Handle<SharedFunctionInfo> closest_candidate = outer_shared;
  if (closest_position == position) return outer_shared;
  const int start_position = outer_shared->StartPosition();
  const int end_position = outer_shared->EndPosition();
  if (start_position == end_position) return outer_shared;
  if (closest_position == 0) closest_position = end_position;
  std::vector<Handle<SharedFunctionInfo>> candidates;
  // Find all shared function infos of functions that are intersecting from
  // the requested position until the end of the enclosing function.
  if (!FindSharedFunctionInfosIntersectingRange(
          script, position, closest_position, &candidates)) {
    return outer_shared;
  }
  for (auto candidate : candidates) {
    Handle<DebugInfo> debug_info(TryGetDebugInfo(*candidate).value(), isolate_);
    CHECK(debug_info->HasBreakInfo());
    const int candidate_position = FindBreakablePosition(debug_info, position);
    if (candidate_position >= position &&
        candidate_position < closest_position) {
      closest_position = candidate_position;
      closest_candidate = candidate;
    }
    if (closest_position == position) break;
  }
  return closest_candidate;
}
References CHECK, FindBreakablePosition(), FindSharedFunctionInfosIntersectingRange(), isolate_, RCS_SCOPE, v8::internal::script, and TryGetDebugInfo().
Referenced by SetBreakPointForScript().
FindInnermostContainingFunctionInfo()
Handle< Object > v8::internal::Debug::FindInnermostContainingFunctionInfo (Handle< Script > script, int position)
Definition at line 2227 of file debug.cc.
                                                                        {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  for (int iteration = 0;; iteration++) {
    // Go through all shared function infos associated with this script to
    // find the innermost function containing this position.
    // If there is no shared function info for this script at all, there is
    // no point in looking for it by walking the heap.
    Tagged<SharedFunctionInfo> shared;
    IsCompiledScope is_compiled_scope;
    {
      shared = FindSharedFunctionInfoCandidate(position, script, isolate_);
      if (shared.is_null()) {
        if (iteration > 0) break;
        // It might be that the shared function info is not available as the
        // top level functions are removed due to the GC. Try to recompile
        // the top level functions.
        const bool success = CompileTopLevel(isolate_, script);
        if (!success) break;
        continue;
      }
      // We found it if it's already compiled.
      is_compiled_scope = shared->is_compiled_scope(isolate_);
      if (is_compiled_scope.is_compiled()) {
        Handle<SharedFunctionInfo> shared_handle(shared, isolate_);
        // If the iteration count is larger than 1, we had to compile the outer
        // function in order to create this shared function info. So there can
        // be no JSFunction referencing it. We can anticipate creating a debug
        // info while bypassing PrepareFunctionForDebugExecution.
        if (iteration > 1) {
          CreateBreakInfo(shared_handle);
        }
        return shared_handle;
      }
    }
    // If not, compile to reveal inner functions.
    HandleScope scope(isolate_);
    // InstructionStream that cannot be compiled lazily are internal and not
    // debuggable.
    DCHECK(shared->allows_lazy_compilation());
    if (!Compiler::Compile(isolate_, handle(shared, isolate_),
                           Compiler::CLEAR_EXCEPTION, &is_compiled_scope)) {
      break;
    }
  }
  return isolate_->factory()->undefined_value();
}
References v8::internal::Compiler::CLEAR_EXCEPTION, v8::internal::Compiler::Compile(), v8::internal::anonymous_namespace{debug.cc}::CompileTopLevel(), CreateBreakInfo(), v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{debug.cc}::FindSharedFunctionInfoCandidate(), v8::internal::handle(), v8::internal::IsCompiledScope::is_compiled(), v8::internal::Tagged< HeapObject >::is_null(), isolate_, RCS_SCOPE, and v8::internal::script.
Referenced by GetPossibleBreakpoints(), and SetBreakPointForScript().
FindSharedFunctionInfosIntersectingRange()
bool v8::internal::Debug::FindSharedFunctionInfosIntersectingRange (Handle< Script > script, int start_position, int end_position, std::vector< Handle< SharedFunctionInfo >> * candidates)
Definition at line 2142 of file debug.cc.
                                                                {
  bool candidateSubsumesRange = false;
  bool triedTopLevelCompile = false;
  while (true) {
    std::vector<Handle<SharedFunctionInfo>> candidates;
    std::vector<IsCompiledScope> compiled_scopes;
    {
      DisallowGarbageCollection no_gc;
      SharedFunctionInfo::ScriptIterator iterator(isolate_, *script);
      for (Tagged<SharedFunctionInfo> info = iterator.Next(); !info.is_null();
           info = iterator.Next()) {
        if (info->EndPosition() < start_position ||
            info->StartPosition() >= end_position) {
          continue;
        }
        candidateSubsumesRange |= info->StartPosition() <= start_position &&
                                  info->EndPosition() >= end_position;
        if (!info->IsSubjectToDebugging()) continue;
        if (!info->is_compiled() && !info->allows_lazy_compilation()) continue;
        candidates.push_back(i::handle(info, isolate_));
      }
    }
    if (!triedTopLevelCompile && !candidateSubsumesRange &&
        script->infos()->length() > 0) {
      MaybeDirectHandle<SharedFunctionInfo> shared =
          GetTopLevelWithRecompile(script, &triedTopLevelCompile);
      if (shared.is_null()) return false;
      if (triedTopLevelCompile) continue;
    }
    bool was_compiled = false;
    for (const auto& candidate : candidates) {
      IsCompiledScope is_compiled_scope(candidate->is_compiled_scope(isolate_));
      if (!is_compiled_scope.is_compiled()) {
        // InstructionStream that cannot be compiled lazily are internal and not
        // debuggable.
        DCHECK(candidate->allows_lazy_compilation());
        if (!Compiler::Compile(isolate_, candidate, Compiler::CLEAR_EXCEPTION,
                               &is_compiled_scope)) {
          return false;
        } else {
          was_compiled = true;
        }
      }
      DCHECK(is_compiled_scope.is_compiled());
      compiled_scopes.push_back(is_compiled_scope);
      if (!EnsureBreakInfo(candidate)) return false;
      PrepareFunctionForDebugExecution(candidate);
    }
    if (was_compiled) continue;
    *intersecting_shared = std::move(candidates);
    return true;
  }
  UNREACHABLE();
}
References v8::internal::Compiler::CLEAR_EXCEPTION, v8::internal::Compiler::Compile(), v8::internal::DCHECK(), EnsureBreakInfo(), GetTopLevelWithRecompile(), v8::internal::handle(), v8::internal::IsCompiledScope::is_compiled(), v8::internal::MaybeDirectHandle< T >::is_null(), isolate_, v8::internal::SharedFunctionInfo::ScriptIterator::Next(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, PrepareFunctionForDebugExecution(), v8::internal::script, and v8::internal::UNREACHABLE().
Referenced by FindClosestSharedFunctionInfoFromPosition(), and GetPossibleBreakpoints().
FloodWithOneShot()
void v8::internal::Debug::FloodWithOneShot (Handle< SharedFunctionInfo > function, bool returns_only = false) [private]
Definition at line 1239 of file debug.cc.
                                                {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  if (IsBlackboxed(shared)) return;
  // Make sure the function is compiled and has set up the debug info.
  if (!EnsureBreakInfo(shared)) return;
  PrepareFunctionForDebugExecution(shared);
  Handle<DebugInfo> debug_info(TryGetDebugInfo(*shared).value(), isolate_);
  // Flood the function with break points.
  DCHECK(debug_info->HasInstrumentedBytecodeArray());
  for (BreakIterator it(debug_info); !it.Done(); it.Next()) {
    if (returns_only && !it.GetBreakLocation().IsReturnOrSuspend()) continue;
    it.SetDebugBreak();
  }
}
References v8::internal::DCHECK(), v8::internal::BreakIterator::Done(), EnsureBreakInfo(), IsBlackboxed(), isolate_, PrepareFunctionForDebugExecution(), RCS_SCOPE, and TryGetDebugInfo().
Referenced by PrepareStep(), PrepareStepIn(), PrepareStepInSuspendedGenerator(), and PrepareStepOnThrow().
FreeThreadResources()
void v8::internal::Debug::FreeThreadResources () [inline]
Definition at line 398 of file debug.h.
{}
Referenced by v8::internal::ThreadManager::FreeThreadResources().
GetFunctionDebuggingId()
int v8::internal::Debug::GetFunctionDebuggingId (DirectHandle< JSFunction > function)
Definition at line 1112 of file debug.cc.
                                                                   {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  DirectHandle<SharedFunctionInfo> shared(function->shared(), isolate_);
  DirectHandle<DebugInfo> debug_info = GetOrCreateDebugInfo(shared);
  int id = debug_info->debugging_id();
  if (id == DebugInfo::kNoDebuggingId) {
    id = isolate_->heap()->NextDebuggingId();
    debug_info->set_debugging_id(id);
  }
  return id;
}
References GetOrCreateDebugInfo(), v8::internal::Isolate::heap(), isolate_, v8::internal::DebugInfo::kNoDebuggingId, v8::internal::Heap::NextDebuggingId(), and RCS_SCOPE.
Referenced by v8::debug::GetDebuggingId().
GetHitBreakPoints()
MaybeHandle< FixedArray > v8::internal::Debug::GetHitBreakPoints (DirectHandle< DebugInfo > debug_info, int position, bool * has_break_points)
Definition at line 1272 of file debug.cc.
                                                                              {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  DirectHandle<Object> break_points =
      debug_info->GetBreakPoints(isolate_, position);
  bool is_break_at_entry = debug_info->BreakAtEntry();
  DCHECK(!IsUndefined(*break_points, isolate_));
  if (!IsFixedArray(*break_points)) {
    const auto break_point = Cast<BreakPoint>(break_points);
    *has_break_points = break_point->id() != kInstrumentationId;
    if (!CheckBreakPoint(break_point, is_break_at_entry)) {
      return {};
    }
    Handle<FixedArray> break_points_hit = isolate_->factory()->NewFixedArray(1);
    break_points_hit->set(0, *break_points);
    return break_points_hit;
  }
  DirectHandle<FixedArray> array(Cast<FixedArray>(*break_points), isolate_);
  int num_objects = array->length();
  Handle<FixedArray> break_points_hit =
      isolate_->factory()->NewFixedArray(num_objects);
  int break_points_hit_count = 0;
  *has_break_points = false;
  for (int i = 0; i < num_objects; ++i) {
    const auto break_point =
        Cast<BreakPoint>(direct_handle(array->get(i), isolate_));
    *has_break_points |= break_point->id() != kInstrumentationId;
    if (CheckBreakPoint(break_point, is_break_at_entry)) {
      break_points_hit->set(break_points_hit_count++, *break_point);
    }
  }
  if (break_points_hit_count == 0) return {};
  break_points_hit->RightTrim(isolate_, break_points_hit_count);
  return break_points_hit;
}
References CheckBreakPoint(), v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, isolate_, kInstrumentationId, v8::internal::FactoryBase< Impl >::NewFixedArray(), and RCS_SCOPE.
Referenced by CheckBreakPoints().
GetLoadedScripts()
DirectHandle< FixedArray > v8::internal::Debug::GetLoadedScripts ()
Definition at line 2398 of file debug.cc.
                                                 {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  isolate_->heap()->CollectAllGarbage(GCFlag::kNoFlags,
                                      GarbageCollectionReason::kDebugger);
  Factory* factory = isolate_->factory();
  if (!IsWeakArrayList(*factory->script_list())) {
    return factory->empty_fixed_array();
  }
  auto array = Cast<WeakArrayList>(factory->script_list());
  Handle<FixedArray> results = factory->NewFixedArray(array->length());
  int length = 0;
  {
    Script::Iterator iterator(isolate_);
    for (Tagged<Script> script = iterator.Next(); !script.is_null();
         script = iterator.Next()) {
      if (script->HasValidSource()) results->set(length++, script);
    }
  }
  return FixedArray::RightTrimOrEmpty(isolate_, results, length);
}
References v8::internal::Heap::CollectAllGarbage(), v8::internal::Isolate::factory(), v8::internal::Isolate::heap(), isolate_, v8::internal::kDebugger, v8::internal::kNoFlags, v8::internal::length, v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::Script::Iterator::Next(), RCS_SCOPE, and v8::internal::script.
GetOrCreateDebugInfo()
Handle< DebugInfo > v8::internal::Debug::GetOrCreateDebugInfo (DirectHandle< SharedFunctionInfo > shared)
Definition at line 2319 of file debug.cc.
                                             {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  if (std::optional<Tagged<DebugInfo>> di = debug_infos_.Find(*shared)) {
    return handle(di.value(), isolate_);
  }
  Handle<DebugInfo> debug_info = isolate_->factory()->NewDebugInfo(shared);
  debug_infos_.Insert(*shared, *debug_info);
  return debug_info;
}
References debug_infos_, v8::internal::Isolate::factory(), v8::internal::DebugInfoCollection::Find(), v8::internal::handle(), v8::internal::DebugInfoCollection::Insert(), isolate_, v8::internal::Factory::NewDebugInfo(), and RCS_SCOPE.
Referenced by CreateBreakInfo(), GetFunctionDebuggingId(), InstallCoverageInfo(), IsBlackboxed(), and PerformSideEffectCheck().
GetPossibleBreakpoints()
bool v8::internal::Debug::GetPossibleBreakpoints (Handle< Script > script, int start_position, int end_position, bool restrict_to_function, std::vector< BreakLocation > * locations)
Definition at line 2000 of file debug.cc.
                                                                        {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  if (restrict_to_function) {
    Handle<Object> result =
        FindInnermostContainingFunctionInfo(script, start_position);
    if (IsUndefined(*result, isolate_)) return false;
    // Make sure the function has set up the debug info.
    Handle<SharedFunctionInfo> shared = Cast<SharedFunctionInfo>(result);
    if (!EnsureBreakInfo(shared)) return false;
    PrepareFunctionForDebugExecution(shared);
    Handle<DebugInfo> debug_info(TryGetDebugInfo(*shared).value(), isolate_);
    FindBreakablePositions(debug_info, start_position, end_position, locations);
    return true;
  }
  HandleScope scope(isolate_);
  std::vector<Handle<SharedFunctionInfo>> candidates;
  if (!FindSharedFunctionInfosIntersectingRange(script, start_position,
                                                end_position, &candidates)) {
    return false;
  }
  for (const auto& candidate : candidates) {
    CHECK(candidate->HasBreakInfo(isolate_));
    Handle<DebugInfo> debug_info(TryGetDebugInfo(*candidate).value(), isolate_);
    FindBreakablePositions(debug_info, start_position, end_position, locations);
  }
  return true;
}
References CHECK, EnsureBreakInfo(), v8::internal::anonymous_namespace{debug.cc}::FindBreakablePositions(), FindInnermostContainingFunctionInfo(), FindSharedFunctionInfosIntersectingRange(), isolate_, PrepareFunctionForDebugExecution(), RCS_SCOPE, v8::base::internal::result, v8::internal::script, and TryGetDebugInfo().
Referenced by v8::debug::Script::GetPossibleBreakpoints().
GetSourceBreakLocations()
DirectHandle< Object > v8::internal::Debug::GetSourceBreakLocations (Isolate * isolate, DirectHandle< SharedFunctionInfo > shared) [static]
Definition at line 1615 of file debug.cc.
                                                               {
  RCS_SCOPE(isolate, RuntimeCallCounterId::kDebugger);
  if (!shared->HasBreakInfo(isolate)) {
    return isolate->factory()->undefined_value();
  }
  DirectHandle<DebugInfo> debug_info(
      isolate->debug()->TryGetDebugInfo(*shared).value(), isolate);
  if (debug_info->GetBreakPointCount(isolate) == 0) {
    return isolate->factory()->undefined_value();
  }
  DirectHandle<FixedArray> locations = isolate->factory()->NewFixedArray(
      debug_info->GetBreakPointCount(isolate));
  int count = 0;
  for (int i = 0; i < debug_info->break_points()->length(); ++i) {
    if (!IsUndefined(debug_info->break_points()->get(i), isolate)) {
      Tagged<BreakPointInfo> break_point_info =
          Cast<BreakPointInfo>(debug_info->break_points()->get(i));
      int break_points = break_point_info->GetBreakPointCount(isolate);
      if (break_points == 0) continue;
      for (int j = 0; j < break_points; ++j) {
        locations->set(count++,
                       Smi::FromInt(break_point_info->source_position()));
      }
    }
  }
  return locations;
}
References v8::internal::Isolate::debug(), v8::internal::Isolate::factory(), v8::internal::Smi::FromInt(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::length, v8::internal::FactoryBase< Impl >::NewFixedArray(), RCS_SCOPE, and TryGetDebugInfo().
Referenced by v8::internal::RUNTIME_FUNCTION().
GetTemporaryObjectTrackingDisabled()
bool v8::internal::Debug::GetTemporaryObjectTrackingDisabled () const [private]
Definition at line 3362 of file debug.cc.
                                                     {
  if (temporary_objects_) {
    return temporary_objects_->disabled;
  }
  return false;
}
References temporary_objects_.
GetTopLevelWithRecompile()
MaybeDirectHandle< SharedFunctionInfo > v8::internal::Debug::GetTopLevelWithRecompile (Handle< Script > script, bool * did_compile = nullptr)
Definition at line 2202 of file debug.cc.
                                              {
  DCHECK_LE(kFunctionLiteralIdTopLevel, script->infos()->length());
  Tagged<MaybeObject> maybeToplevel =
      script->infos()->get(kFunctionLiteralIdTopLevel);
  Tagged<HeapObject> heap_object;
  const bool topLevelInfoExists =
      maybeToplevel.GetHeapObject(&heap_object) && !IsUndefined(heap_object);
  if (topLevelInfoExists) {
    if (did_compile) *did_compile = false;
    return direct_handle(Cast<SharedFunctionInfo>(heap_object), isolate_);
  }
  MaybeHandle<SharedFunctionInfo> shared;
  CompileTopLevel(isolate_, script, &shared);
  if (did_compile) *did_compile = true;
  return shared;
}
References v8::internal::anonymous_namespace{debug.cc}::CompileTopLevel(), DCHECK_LE, v8::internal::direct_handle(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObject(), isolate_, v8::internal::kFunctionLiteralIdTopLevel, and v8::internal::script.
Referenced by FindSharedFunctionInfosIntersectingRange().
HandleDebugBreak()
void v8::internal::Debug::HandleDebugBreak (IgnoreBreakMode ignore_break_mode, debug::BreakReasons break_reasons)
Definition at line 2836 of file debug.cc.
                                                                {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  // Ignore debug break during bootstrapping.
  if (isolate_->bootstrapper()->IsActive()) return;
  // Just continue if breaks are disabled.
  if (break_disabled()) return;
  // Ignore debug break if debugger is not active.
  if (!is_active()) return;
  StackLimitCheck check(isolate_);
  if (check.HasOverflowed()) return;
  HandleScope scope(isolate_);
  MaybeHandle<FixedArray> break_points;
  {
    DebuggableStackFrameIterator it(isolate_);
    DCHECK(!it.done());
    JavaScriptFrame* frame = it.frame()->is_javascript()
                                 ? JavaScriptFrame::cast(it.frame())
                                 : nullptr;
    if (frame && IsJSFunction(frame->function())) {
      DirectHandle<JSFunction> function(frame->function(), isolate_);
      DirectHandle<SharedFunctionInfo> shared(function->shared(), isolate_);
      // kScheduled breaks are triggered by the stack check. While we could
      // pause here, the JSFunction didn't have time yet to create and push
      // it's context. Instead, we step into the function and pause at the
      // first official breakable position.
      // This behavior mirrors "BreakOnNextFunctionCall".
      if (break_reasons.contains(v8::debug::BreakReason::kScheduled) &&
          BreakLocation::IsPausedInJsFunctionEntry(frame)) {
        thread_local_.scheduled_break_on_next_function_call_ = true;
        PrepareStepIn(function);
        return;
      }
      // Don't stop in builtin and blackboxed functions.
      bool ignore_break = ignore_break_mode == kIgnoreIfTopFrameBlackboxed
                              ? IsBlackboxed(shared)
                              : AllFramesOnStackAreBlackboxed();
      if (ignore_break) return;
      Handle<DebugInfo> debug_info;
      if (ToHandle(isolate_, TryGetDebugInfo(*shared), &debug_info) &&
          debug_info->HasBreakInfo()) {
        // Enter the debugger.
        DebugScope debug_scope(this);
        std::vector<BreakLocation> break_locations;
        BreakLocation::AllAtCurrentStatement(debug_info, frame,
                                             &break_locations);
        if (IsMutedAtAnyBreakLocation(shared, break_locations)) {
          // If we get to this point, a break was triggered because e.g. of
          // a debugger statement, an assert, .. . However, we do not stop
          // if this position "is muted", which happens if a conditional
          // breakpoint at this point evaluated to false.
          return;
        }
      }
    }
  }
  StepAction lastStepAction = last_step_action();
  // Clear stepping to avoid duplicate breaks.
  ClearStepping();
  DebugScope debug_scope(this);
  OnDebugBreak(break_points.is_null() ? isolate_->factory()->empty_fixed_array()
                                      : break_points.ToHandleChecked(),
               lastStepAction, break_reasons);
}
References v8::internal::BreakLocation::AllAtCurrentStatement(), AllFramesOnStackAreBlackboxed(), v8::internal::Isolate::bootstrapper(), break_disabled(), v8::internal::JavaScriptFrame::cast(), ClearStepping(), v8::base::EnumSet< E, T >::contains(), v8::internal::DCHECK(), v8::internal::DebuggableStackFrameIterator::done(), v8::internal::Isolate::factory(), v8::internal::DebuggableStackFrameIterator::frame(), v8::internal::JavaScriptFrame::function(), v8::internal::StackLimitCheck::HasOverflowed(), is_active(), v8::internal::StackFrame::is_javascript(), v8::internal::MaybeHandle< T >::is_null(), v8::internal::Bootstrapper::IsActive(), IsBlackboxed(), IsMutedAtAnyBreakLocation(), isolate_, v8::internal::BreakLocation::IsPausedInJsFunctionEntry(), v8::internal::kIgnoreIfTopFrameBlackboxed, v8::debug::kScheduled, last_step_action(), OnDebugBreak(), PrepareStepIn(), RCS_SCOPE, v8::internal::Debug::ThreadLocal::scheduled_break_on_next_function_call_, thread_local_, v8::internal::anonymous_namespace{debug.cc}::ToHandle(), v8::internal::MaybeHandle< T >::ToHandleChecked(), and TryGetDebugInfo().
Referenced by v8::debug::BreakRightNow().
has_suspended_generator()
bool v8::internal::Debug::has_suspended_generator () const [inline], [private]
Definition at line 530 of file debug.h.
                                       {
    return thread_local_.suspended_generator_ != Smi::zero();
  }
References v8::internal::Smi::zero().
Referenced by Break(), PrepareStep(), and PrepareStepInSuspendedGenerator().
HasBreakInfo()
bool v8::internal::Debug::HasBreakInfo (Tagged< SharedFunctionInfo > sfi)
Definition at line 2435 of file debug.cc.
                                                       {
  if (std::optional<Tagged<DebugInfo>> debug_info = TryGetDebugInfo(sfi)) {
    return debug_info.value()->HasBreakInfo();
  }
  return false;
}
References TryGetDebugInfo().
Referenced by v8::internal::SharedFunctionInfo::HasBreakInfo().
HasCoverageInfo()
bool v8::internal::Debug::HasCoverageInfo (Tagged< SharedFunctionInfo > sfi)
Definition at line 2428 of file debug.cc.
                                                          {
  if (std::optional<Tagged<DebugInfo>> debug_info = TryGetDebugInfo(sfi)) {
    return debug_info.value()->HasCoverageInfo();
  }
  return false;
}
References TryGetDebugInfo().
Referenced by v8::internal::SharedFunctionInfo::HasCoverageInfo().
HasDebugInfo()
bool v8::internal::Debug::HasDebugInfo (Tagged< SharedFunctionInfo > sfi)
Definition at line 2424 of file debug.cc.
                                                       {
  return TryGetDebugInfo(sfi).has_value();
}
References TryGetDebugInfo().
Referenced by v8::internal::SharedFunctionInfo::HasDebugInfo().
hook_on_function_call_address()
Address v8::internal::Debug::hook_on_function_call_address () [inline]
Definition at line 452 of file debug.h.
                                          {
    return reinterpret_cast<Address>(&hook_on_function_call_);
  }
Referenced by v8::internal::WasmTrustedInstanceData::New().
ignore_events()
bool v8::internal::Debug::ignore_events () const [inline], [private]
Definition at line 521 of file debug.h.
                                    {
    return is_suppressed_ || !is_active_ ||
           isolate_->debug_execution_mode() == DebugInfo::kSideEffects;
  }
References v8::internal::DebugInfo::kSideEffects.
Referenced by OnDebugBreak(), OnPromiseReject(), OnThrow(), PrepareStepIn(), PrepareStepInSuspendedGenerator(), PrepareStepOnThrow(), and ProcessCompileEvent().
IgnoreSideEffectsOnNextCallTo()
void v8::internal::Debug::IgnoreSideEffectsOnNextCallTo (Handle< FunctionTemplateInfo > function)
Definition at line 3240 of file debug.cc.
                                           {
  DCHECK(function->has_side_effects());
  // There must be only one such call handler info.
  CHECK(ignore_side_effects_for_function_template_info_.is_null());
  ignore_side_effects_for_function_template_info_ = function;
}
References CHECK, v8::internal::DCHECK(), and ignore_side_effects_for_function_template_info_.
Referenced by v8::Function::NewInstanceWithSideEffectType().
in_debug_scope()
bool v8::internal::Debug::in_debug_scope () const [inline]
Definition at line 431 of file debug.h.
                                     {
    return !!base::Relaxed_Load(&thread_local_.current_debug_scope_);
  }
References v8::base::Relaxed_Load().
Referenced by CheckBreakPoint(), CurrentFrameCount(), OnDebugBreak(), OnInstrumentationBreak(), OnPromiseReject(), OnThrow(), PrepareStep(), PrepareStepIn(), PrepareStepInSuspendedGenerator(), and PrepareStepOnThrow().
InitThread()
void v8::internal::Debug::InitThread (const ExecutionAccess & lock) [inline]
Definition at line 400 of file debug.h.
{ ThreadInit(); }
Referenced by v8::internal::ThreadManager::InitThread().
InstallCoverageInfo()
void v8::internal::Debug::InstallCoverageInfo (DirectHandle< SharedFunctionInfo > shared, DirectHandle< CoverageInfo > coverage_info)
Definition at line 2332 of file debug.cc.
                                                                          {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  DCHECK(!coverage_info.is_null());
  DirectHandle<DebugInfo> debug_info = GetOrCreateDebugInfo(shared);
  DCHECK(!debug_info->HasCoverageInfo());
  debug_info->set_flags(
      debug_info->flags(kRelaxedLoad) | DebugInfo::kHasCoverageInfo,
      kRelaxedStore);
  debug_info->set_coverage_info(*coverage_info);
}
References v8::internal::DCHECK(), GetOrCreateDebugInfo(), v8::internal::DirectHandle< T >::is_null(), isolate_, v8::kRelaxedLoad, v8::kRelaxedStore, and RCS_SCOPE.
Referenced by v8::internal::anonymous_namespace{compiler.cc}::FinalizeUnoptimizedCompilation().
InstallDebugBreakTrampoline()
void v8::internal::Debug::InstallDebugBreakTrampoline ()
Definition at line 1855 of file debug.cc.
                                        {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  // Check the list of debug infos whether the debug break trampoline needs to
  // be installed. If that's the case, iterate the heap for functions to rewire
  // to the trampoline.
  // If there is a breakpoint at function entry, we need to install trampoline.
  bool needs_to_use_trampoline = false;
  // If there we break at entry to an api callback, we need to clear ICs.
  bool needs_to_clear_ic = false;
  DebugInfoCollection::Iterator it(&debug_infos_);
  for (; it.HasNext(); it.Advance()) {
    Tagged<DebugInfo> debug_info = it.Next();
    if (debug_info->CanBreakAtEntry()) {
      needs_to_use_trampoline = true;
      if (debug_info->shared()->IsApiFunction()) {
        needs_to_clear_ic = true;
        break;
      }
    }
  }
  if (!needs_to_use_trampoline) return;
  HandleScope scope(isolate_);
  DirectHandle<Code> trampoline = BUILTIN_CODE(isolate_, DebugBreakTrampoline);
  std::vector<Handle<JSFunction>> needs_compile;
  using AccessorPairWithContext =
      std::pair<Handle<AccessorPair>, Handle<NativeContext>>;
  std::vector<AccessorPairWithContext> needs_instantiate;
  {
    // Deduplicate {needs_instantiate} by recording all collected AccessorPairs.
    std::set<Tagged<AccessorPair>> recorded;
    HeapObjectIterator iterator(isolate_->heap());
    DisallowGarbageCollection no_gc;
    for (Tagged<HeapObject> obj = iterator.Next(); !obj.is_null();
         obj = iterator.Next()) {
      if (needs_to_clear_ic && IsFeedbackVector(obj)) {
        Cast<FeedbackVector>(obj)->ClearSlots(isolate_);
        continue;
      } else if (IsJSFunctionAndNeedsTrampoline(isolate_, obj)) {
        Tagged<JSFunction> fun = Cast<JSFunction>(obj);
        if (!fun->is_compiled(isolate_)) {
          needs_compile.push_back(handle(fun, isolate_));
        } else {
          fun->UpdateCode(isolate_, *trampoline);
        }
      } else if (IsJSObject(obj)) {
        Tagged<JSObject> object = Cast<JSObject>(obj);
        Tagged<DescriptorArray> descriptors =
            object->map()->instance_descriptors(kRelaxedLoad);
        for (InternalIndex i : object->map()->IterateOwnDescriptors()) {
          if (descriptors->GetDetails(i).kind() == PropertyKind::kAccessor) {
            Tagged<Object> value = descriptors->GetStrongValue(i);
            if (!IsAccessorPair(value)) continue;
            Tagged<AccessorPair> accessor_pair = Cast<AccessorPair>(value);
            if (!IsFunctionTemplateInfo(accessor_pair->getter()) &&
                !IsFunctionTemplateInfo(accessor_pair->setter())) {
              continue;
            }
            if (recorded.find(accessor_pair) != recorded.end()) continue;
            needs_instantiate.emplace_back(
                handle(accessor_pair, isolate_),
                handle(object->GetCreationContext().value(), isolate_));
            recorded.insert(accessor_pair);
          }
        }
      }
    }
  }
  // Forcibly instantiate all lazy accessor pairs to make sure that they
  // properly hit the debug break trampoline.
  for (AccessorPairWithContext tuple : needs_instantiate) {
    DirectHandle<AccessorPair> accessor_pair = tuple.first;
    DirectHandle<NativeContext> native_context = tuple.second;
    DirectHandle<Object> getter = AccessorPair::GetComponent(
        isolate_, native_context, accessor_pair, ACCESSOR_GETTER);
    if (IsJSFunctionAndNeedsTrampoline(isolate_, *getter)) {
      Cast<JSFunction>(getter)->UpdateCode(isolate_, *trampoline);
    }
    DirectHandle<Object> setter = AccessorPair::GetComponent(
        isolate_, native_context, accessor_pair, ACCESSOR_SETTER);
    if (IsJSFunctionAndNeedsTrampoline(isolate_, *setter)) {
      Cast<JSFunction>(setter)->UpdateCode(isolate_, *trampoline);
    }
  }
  // By overwriting the function code with DebugBreakTrampoline, which tailcalls
  // to shared code, we bypass CompileLazy. Perform CompileLazy here instead.
  for (DirectHandle<JSFunction> fun : needs_compile) {
    IsCompiledScope is_compiled_scope;
    Compiler::Compile(isolate_, fun, Compiler::CLEAR_EXCEPTION,
                      &is_compiled_scope);
    DCHECK(is_compiled_scope.is_compiled());
    fun->UpdateCode(isolate_, *trampoline);
  }
}
References v8::internal::ACCESSOR_GETTER, v8::internal::ACCESSOR_SETTER, v8::internal::DebugInfoCollection::Iterator::Advance(), BUILTIN_CODE, v8::internal::Compiler::CLEAR_EXCEPTION, v8::internal::Compiler::Compile(), v8::internal::DCHECK(), debug_infos_, v8::internal::AccessorPair::GetComponent(), v8::internal::handle(), v8::internal::DebugInfoCollection::Iterator::HasNext(), v8::internal::Isolate::heap(), v8::internal::IsCompiledScope::is_compiled(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::anonymous_namespace{debug.cc}::IsJSFunctionAndNeedsTrampoline(), isolate_, v8::internal::kAccessor, v8::kRelaxedLoad, v8::internal::native_context, v8::internal::HeapObjectIterator::Next(), v8::internal::DebugInfoCollection::Iterator::Next(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, RCS_SCOPE, v8::internal::setter, and v8::internal::value.
Referenced by v8::internal::Genesis::Genesis(), and PrepareFunctionForDebugExecution().
is_active()
bool v8::internal::Debug::is_active () const [inline]
Definition at line 430 of file debug.h.
{ return is_active_; }
Referenced by v8::internal::Genesis::Genesis(), HandleDebugBreak(), v8::internal::MoveMessageToPromise(), v8::internal::Isolate::NeedsSourcePositions(), v8::internal::JSPromise::Resolve(), and UpdateState().
is_active_address()
Address v8::internal::Debug::is_active_address () [inline]
Definition at line 450 of file debug.h.
{ return reinterpret_cast<Address>(&is_active_); }
IsBlackboxed()
bool v8::internal::Debug::IsBlackboxed (DirectHandle< SharedFunctionInfo > shared)
Definition at line 2669 of file debug.cc.
                                                                {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  if (!debug_delegate_) return !shared->IsSubjectToDebugging();
  DirectHandle<DebugInfo> debug_info = GetOrCreateDebugInfo(shared);
  if (!debug_info->computed_debug_is_blackboxed()) {
    bool is_blackboxed =
        !shared->IsSubjectToDebugging() || !IsScript(shared->script());
    if (!is_blackboxed) {
      SuppressDebug while_processing(this);
      HandleScope handle_scope(isolate_);
      PostponeInterruptsScope no_interrupts(isolate_);
      DisableBreak no_recursive_break(this);
      DCHECK(IsScript(shared->script()));
      DirectHandle<Script> script(Cast<Script>(shared->script()), isolate_);
      DCHECK(script->IsUserJavaScript());
      {
        RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebuggerCallback);
        is_blackboxed = this->IsFunctionBlackboxed(
            script, shared->StartPosition(), shared->EndPosition());
      }
    }
    debug_info->set_debug_is_blackboxed(is_blackboxed);
    debug_info->set_computed_debug_is_blackboxed(true);
  }
  return debug_info->debug_is_blackboxed();
}
References v8::internal::DCHECK(), debug_delegate_, GetOrCreateDebugInfo(), IsFunctionBlackboxed(), isolate_, RCS_SCOPE, and v8::internal::script.
Referenced by FloodWithOneShot(), HandleDebugBreak(), IsFrameBlackboxed(), OnException(), PrepareStep(), PrepareStepIn(), and PrepareStepOnThrow().
IsBreakAtReturn()
bool v8::internal::Debug::IsBreakAtReturn (JavaScriptFrame * frame)
Definition at line 2378 of file debug.cc.
                                                  {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  HandleScope scope(isolate_);
  // Get the executing function in which the debug break occurred.
  DirectHandle<SharedFunctionInfo> shared(frame->function()->shared(),
                                          isolate_);
  // With no debug info there are no break points, so we can't be at a return.
  Handle<DebugInfo> debug_info;
  if (!ToHandle(isolate_, TryGetDebugInfo(*shared), &debug_info) ||
      !debug_info->HasBreakInfo()) {
    return false;
  }
  DCHECK(!frame->is_optimized());
  BreakLocation location = BreakLocation::FromFrame(debug_info, frame);
  return location.IsReturn();
}
References v8::internal::DCHECK(), v8::internal::BreakLocation::FromFrame(), v8::internal::JavaScriptFrame::function(), v8::internal::JavaScriptFrame::is_optimized(), isolate_, v8::internal::BreakLocation::IsReturn(), RCS_SCOPE, v8::internal::anonymous_namespace{debug.cc}::ToHandle(), and TryGetDebugInfo().
Referenced by v8::internal::DebugStackTraceIterator::GetReturnValue().
IsBreakOnDebuggerStatement()
bool v8::internal::Debug::IsBreakOnDebuggerStatement (DirectHandle< SharedFunctionInfo > function, const BreakLocation & location) [private]
Definition at line 842 of file debug.cc.
                                                                              {
  if (!function->HasBytecodeArray()) {
    return false;
  }
  Tagged<BytecodeArray> original_bytecode =
      function->GetBytecodeArray(isolate_);
  interpreter::Bytecode bytecode = interpreter::Bytecodes::FromByte(
      original_bytecode->get(location.code_offset()));
  return bytecode == interpreter::Bytecode::kDebugger;
}
References v8::internal::BreakLocation::code_offset(), v8::internal::interpreter::Bytecodes::FromByte(), and isolate_.
Referenced by Break().
IsBreakOnException()
bool v8::internal::Debug::IsBreakOnException (ExceptionBreakType type)
Definition at line 1264 of file debug.cc.
                                                      {
  if (type == BreakUncaughtException) {
    return break_on_uncaught_exception_;
  } else {
    return break_on_caught_exception_;
  }
}
References break_on_caught_exception_, break_on_uncaught_exception_, v8::internal::BreakUncaughtException, and v8::internal::tracing::type.
IsBreakOnInstrumentation()
bool v8::internal::Debug::IsBreakOnInstrumentation (Handle< DebugInfo > debug_info, const BreakLocation & location) [private]
Definition at line 816 of file debug.cc.
                                                                    {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  bool has_break_points_to_check =
      break_points_active_ && location.HasBreakPoint(isolate_, debug_info);
  if (!has_break_points_to_check) return {};
  DirectHandle<Object> break_points =
      debug_info->GetBreakPoints(isolate_, location.position());
  DCHECK(!IsUndefined(*break_points, isolate_));
  if (!IsFixedArray(*break_points)) {
    const auto break_point = Cast<BreakPoint>(break_points);
    return break_point->id() == kInstrumentationId;
  }
  DirectHandle<FixedArray> array(Cast<FixedArray>(*break_points), isolate_);
  for (int i = 0; i < array->length(); ++i) {
    const auto break_point =
        Cast<BreakPoint>(direct_handle(array->get(i), isolate_));
    if (break_point->id() == kInstrumentationId) {
      return true;
    }
  }
  return false;
}
References break_points_active_, v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::BreakLocation::HasBreakPoint(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, isolate_, kInstrumentationId, v8::internal::BreakLocation::position(), and RCS_SCOPE.
Referenced by Break().
IsFrameBlackboxed()
bool v8::internal::Debug::IsFrameBlackboxed (JavaScriptFrame * frame) [private]
Definition at line 2491 of file debug.cc.
                                                    {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  HandleScope scope(isolate_);
  std::vector<Handle<SharedFunctionInfo>> infos;
  frame->GetFunctions(&infos);
  for (const auto& info : infos) {
    if (!IsBlackboxed(info)) return false;
  }
  return true;
}
References v8::internal::JavaScriptFrame::GetFunctions(), IsBlackboxed(), isolate_, and RCS_SCOPE.
Referenced by AllFramesOnStackAreBlackboxed().
IsFunctionBlackboxed()
bool v8::internal::Debug::IsFunctionBlackboxed (DirectHandle< Script > script, const int start, const int end)
Definition at line 2661 of file debug.cc.
                                                {
  debug::Location start_location = GetDebugLocation(script, start);
  debug::Location end_location = GetDebugLocation(script, end);
  return debug_delegate_->IsFunctionBlackboxed(
      ToApiHandle<debug::Script>(script), start_location, end_location);
}
References debug_delegate_, v8::internal::compiler::end(), v8::internal::anonymous_namespace{debug.cc}::GetDebugLocation(), v8::debug::DebugDelegate::IsFunctionBlackboxed(), and v8::internal::script.
Referenced by IsBlackboxed(), and v8::internal::wasm::DebugInfoImpl::IsFrameBlackboxed().
IsMutedAtAnyBreakLocation()
bool v8::internal::Debug::IsMutedAtAnyBreakLocation (DirectHandle< SharedFunctionInfo > function, const std::vector< BreakLocation > & locations) [private]
Definition at line 874 of file debug.cc.
                                               {
  // A break location is considered muted if break locations on the current
  // statement have at least one break point, and all of these break points
  // evaluate to false. Aside from not triggering a debug break event at the
  // break location, we also do not trigger one for debugger statements, nor
  // an exception event on exception at this location.
  // This should have been computed at last break, and we should just
  // check that we are not at that location.
  if (IsSmi(thread_local_.muted_function_) ||
      *function != thread_local_.muted_function_) {
    return false;
  }
  for (const BreakLocation& location : locations) {
    if (location.position() == thread_local_.muted_position_) {
      return true;
    }
  }
  return false;
}
References v8::internal::IsSmi(), v8::internal::Debug::ThreadLocal::muted_function_, v8::internal::Debug::ThreadLocal::muted_position_, and thread_local_.
Referenced by HandleDebugBreak(), and OnException().
IsolateId()
uint64_t v8::internal::Debug::IsolateId () const [inline]
Definition at line 506 of file debug.h.
{ return isolate_id_; }
Referenced by v8::debug::GetIsolateId(), v8::internal::Script::TraceScriptRundown(), and v8::internal::Script::TraceScriptRundownSources().
IsRestartFrameScheduled()
bool v8::internal::Debug::IsRestartFrameScheduled () const [inline]
Definition at line 469 of file debug.h.
                                       {
    return thread_local_.restart_frame_id_ != StackFrameId::NO_ID;
  }
References v8::internal::NO_ID.
Referenced by v8::internal::Deoptimizer::Deoptimizer().
Iterate() [1/3]
void v8::internal::Debug::Iterate (RootVisitor * v)
Definition at line 527 of file debug.cc.
{ Iterate(v, &thread_local_); }
References thread_local_.
Referenced by v8::internal::ThreadManager::Iterate(), Iterate(), and v8::internal::Heap::IterateRoots().
Iterate() [2/3]
char * v8::internal::Debug::Iterate (RootVisitor * v, char * thread_storage) [static]
Definition at line 529 of file debug.cc.
                                                         {
  ThreadLocal* thread_local_data =
      reinterpret_cast<ThreadLocal*>(thread_storage);
  Iterate(v, thread_local_data);
  return thread_storage + ArchiveSpacePerThread();
}
References ArchiveSpacePerThread(), and Iterate().
Iterate() [3/3]
void v8::internal::Debug::Iterate (RootVisitor * v, ThreadLocal * thread_local_data) [static], [private]
Definition at line 536 of file debug.cc.
                                                                  {
  v->VisitRootPointer(Root::kDebug, nullptr,
                      FullObjectSlot(&thread_local_data->return_value_));
  v->VisitRootPointer(Root::kDebug, nullptr,
                      FullObjectSlot(&thread_local_data->suspended_generator_));
  v->VisitRootPointer(
      Root::kDebug, nullptr,
      FullObjectSlot(&thread_local_data->ignore_step_into_function_));
  v->VisitRootPointer(Root::kDebug, nullptr,
                      FullObjectSlot(&thread_local_data->muted_function_));
}
References v8::internal::Debug::ThreadLocal::ignore_step_into_function_, v8::internal::Debug::ThreadLocal::muted_function_, v8::internal::Debug::ThreadLocal::return_value_, v8::internal::Debug::ThreadLocal::suspended_generator_, and v8::internal::RootVisitor::VisitRootPointer().
last_step_action()
StepAction v8::internal::Debug::last_step_action () [inline]
Definition at line 460 of file debug.h.
{ return thread_local_.last_step_action_; }
Referenced by Break(), v8::internal::anonymous_namespace{runtime-wasm.cc}::ExecuteWasmDebugBreaks(), HandleDebugBreak(), v8::internal::wasm::DebugInfoImpl::IsStepping(), PrepareStep(), PrepareStepIn(), and PrepareStepOnThrow().
needs_check_on_function_call()
bool v8::internal::Debug::needs_check_on_function_call () const [inline]
Definition at line 434 of file debug.h.
                                                   {
    return hook_on_function_call_;
  }
Referenced by v8::internal::anonymous_namespace{compiler.cc}::GetOrCompileOptimized().
NotifyDebuggerPausedEventSent()
void v8::internal::Debug::NotifyDebuggerPausedEventSent ()
Definition at line 3384 of file debug.cc.
                                          {
  DebugScope* scope = reinterpret_cast<DebugScope*>(
      base::Relaxed_Load(&thread_local_.current_debug_scope_));
  CHECK(scope);
  isolate_->counters()->debug_pause_to_paused_event()->AddTimedSample(
      scope->ElapsedTimeSinceCreation());
}
References CHECK, v8::internal::Isolate::counters(), v8::internal::Debug::ThreadLocal::current_debug_scope_, v8::internal::DebugScope::ElapsedTimeSinceCreation(), isolate_, v8::base::Relaxed_Load(), and thread_local_.
Referenced by v8::debug::NotifyDebuggerPausedEventSent().
OnAfterCompile()
void v8::internal::Debug::OnAfterCompile (DirectHandle< Script > script)
Definition at line 2761 of file debug.cc.
                                                      {
  ProcessCompileEvent(false, script);
}
References ProcessCompileEvent(), and v8::internal::script.
Referenced by v8::internal::wasm::DeserializeNativeModule(), v8::internal::wasm::AsyncCompileJob::FinishCompile(), v8::internal::wasm::WasmEngine::ImportNativeModule(), v8::internal::Compiler::PostInstantiation(), and v8::internal::wasm::WasmEngine::SyncCompile().
OnCompileError()
void v8::internal::Debug::OnCompileError (DirectHandle< Script > script)
Definition at line 2757 of file debug.cc.
                                                      {
  ProcessCompileEvent(true, script);
}
References ProcessCompileEvent(), and v8::internal::script.
Referenced by v8::internal::PendingCompilationErrorHandler::ThrowPendingError().
OnDebugBreak()
void v8::internal::Debug::OnDebugBreak (DirectHandle< FixedArray > break_points_hit, StepAction stepAction, debug::BreakReasons break_reasons = {})
Definition at line 2604 of file debug.cc.
                                                            {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  DCHECK(!break_points_hit.is_null());
  // The caller provided for DebugScope.
  AssertDebugContext();
  // Bail out if there is no listener for this event
  if (ignore_events()) return;
#ifdef DEBUG
  PrintBreakLocation();
#endif // DEBUG
  if (!debug_delegate_) return;
  DCHECK(in_debug_scope());
  HandleScope scope(isolate_);
  DisableBreak no_recursive_break(this);
  if ((lastStepAction == StepAction::StepOver ||
       lastStepAction == StepAction::StepInto) &&
      ShouldBeSkipped()) {
    PrepareStep(lastStepAction);
    return;
  }
  std::vector<int> inspector_break_points_hit;
  // This array contains breakpoints installed using JS debug API.
  for (int i = 0; i < break_points_hit->length(); ++i) {
    Tagged<BreakPoint> break_point = Cast<BreakPoint>(break_points_hit->get(i));
    inspector_break_points_hit.push_back(break_point->id());
  }
  {
    RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebuggerCallback);
    if (lastStepAction != StepAction::StepNone)
      break_reasons.Add(debug::BreakReason::kStep);
    debug_delegate_->BreakProgramRequested(
        v8::Utils::ToLocal(isolate_->native_context()),
        inspector_break_points_hit, break_reasons);
  }
}
References v8::base::EnumSet< E, T >::Add(), AssertDebugContext(), v8::debug::DebugDelegate::BreakProgramRequested(), v8::internal::DCHECK(), debug_delegate_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, ignore_events(), in_debug_scope(), v8::internal::DirectHandle< T >::is_null(), isolate_, v8::debug::kStep, v8::internal::Isolate::native_context(), PrepareStep(), PrintBreakLocation(), RCS_SCOPE, ShouldBeSkipped(), v8::debug::StepInto, v8::internal::StepNone, and v8::debug::StepOver.
Referenced by Break(), v8::internal::anonymous_namespace{runtime-wasm.cc}::ExecuteWasmDebugBreaks(), and HandleDebugBreak().
OnException()
void v8::internal::Debug::OnException (DirectHandle< Object > exception, MaybeDirectHandle< JSPromise > promise, v8::debug::ExceptionType exception_type) [private]
Definition at line 2502 of file debug.cc.
                                                             {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  // Do not trigger exception event on stack overflow. We cannot perform
  // anything useful for debugging in that situation.
  StackLimitCheck stack_limit_check(isolate_);
  if (stack_limit_check.JsHasOverflowed()) return;
  // Return if the event has nowhere to go.
  if (!debug_delegate_) return;
  // Return if we are not interested in exception events.
  if (!break_on_caught_exception_ && !break_on_uncaught_exception_) return;
  HandleScope scope(isolate_);
  bool all_frames_ignored = true;
  bool is_debuggable = false;
  bool uncaught = !isolate_->WalkCallStackAndPromiseTree(
      promise, [this, &all_frames_ignored,
                &is_debuggable](Isolate::PromiseHandler handler) {
        if (!handler.async) {
          is_debuggable = true;
        } else if (!is_debuggable) {
          // Don't bother checking ignore listing if there are no debuggable
          // frames on the callstack
          return;
        }
        all_frames_ignored =
            all_frames_ignored &&
            IsBlackboxed(direct_handle(handler.function_info, isolate_));
      });
  if (all_frames_ignored || !is_debuggable) {
    return;
  }
  if (!uncaught) {
    if (!break_on_caught_exception_) {
      return;
    }
  } else {
    if (!break_on_uncaught_exception_) {
      return;
    }
  }
  {
    StackFrameIterator it(isolate_);
    for (; !it.done(); it.Advance()) {
      if (it.frame()->is_javascript()) {
        JavaScriptFrame* frame = JavaScriptFrame::cast(it.frame());
        FrameSummary summary = FrameSummary::GetTop(frame);
        DirectHandle<SharedFunctionInfo> shared{
            summary.AsJavaScript().function()->shared(), isolate_};
        if (shared->IsSubjectToDebugging()) {
          Handle<DebugInfo> debug_info;
          std::vector<BreakLocation> break_locations;
          if (ToHandle(isolate_, TryGetDebugInfo(*shared), &debug_info) &&
              debug_info->HasBreakInfo()) {
            // Enter the debugger.
            DebugScope debug_scope(this);
            BreakLocation::AllAtCurrentStatement(debug_info, frame,
                                                 &break_locations);
          }
          if (IsMutedAtAnyBreakLocation(shared, break_locations)) {
            return;
          }
          break; // Stop at first debuggable function
        }
#if V8_ENABLE_WEBASSEMBLY
      } else if (it.frame()->is_wasm()) {
        const WasmFrame* frame = WasmFrame::cast(it.frame());
        if (IsMutedAtWasmLocation(frame->script(), frame->position())) {
          return;
        }
        // Wasm is always subject to debugging
        break;
#endif // V8_ENABLE_WEBASSEMBLY
      }
    }
    if (it.done()) return; // Do not trigger an event with an empty stack.
  }
  DebugScope debug_scope(this);
  DisableBreak no_recursive_break(this);
  {
    DirectHandle<Object> promise_object;
    if (!promise.ToHandle(&promise_object)) {
      promise_object = isolate_->factory()->undefined_value();
    }
    RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebuggerCallback);
    debug_delegate_->ExceptionThrown(
        v8::Utils::ToLocal(isolate_->native_context()),
        v8::Utils::ToLocal(exception), v8::Utils::ToLocal(promise_object),
        uncaught, exception_type);
  }
}
References v8::internal::StackFrameIterator::Advance(), v8::internal::BreakLocation::AllAtCurrentStatement(), v8::internal::Isolate::PromiseHandler::async, break_on_caught_exception_, break_on_uncaught_exception_, v8::internal::JavaScriptFrame::cast(), debug_delegate_, v8::internal::direct_handle(), v8::internal::StackFrameIteratorBase::done(), v8::debug::DebugDelegate::ExceptionThrown(), v8::internal::Isolate::factory(), v8::internal::StackFrameIterator::frame(), v8::internal::Isolate::PromiseHandler::function_info, v8::internal::FrameSummary::GetTop(), v8::internal::if(), v8::internal::StackFrame::is_javascript(), IsBlackboxed(), IsMutedAtAnyBreakLocation(), isolate_, v8::internal::StackLimitCheck::JsHasOverflowed(), v8::internal::Isolate::native_context(), RCS_SCOPE, v8::internal::MaybeDirectHandle< T >::ToHandle(), v8::internal::anonymous_namespace{debug.cc}::ToHandle(), TryGetDebugInfo(), and v8::internal::Isolate::WalkCallStackAndPromiseTree().
Referenced by OnPromiseReject(), and OnThrow().
OnInstrumentationBreak()
debug::DebugDelegate::ActionAfterInstrumentation v8::internal::Debug::OnInstrumentationBreak ()
Definition at line 625 of file debug.cc.
                              {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  if (!debug_delegate_) {
    return debug::DebugDelegate::ActionAfterInstrumentation::
        kPauseIfBreakpointsHit;
  }
  DCHECK(in_debug_scope());
  HandleScope scope(isolate_);
  DisableBreak no_recursive_break(this);
  return debug_delegate_->BreakOnInstrumentation(
      v8::Utils::ToLocal(isolate_->native_context()), kInstrumentationId);
}
References v8::debug::DebugDelegate::BreakOnInstrumentation(), v8::internal::DCHECK(), debug_delegate_, in_debug_scope(), isolate_, kInstrumentationId, v8::debug::DebugDelegate::kPauseIfBreakpointsHit, v8::internal::Isolate::native_context(), and RCS_SCOPE.
Referenced by Break(), and v8::internal::anonymous_namespace{runtime-wasm.cc}::ExecuteWasmDebugBreaks().
OnPromiseReject()
void v8::internal::Debug::OnPromiseReject (DirectHandle< Object > promise, DirectHandle< Object > value)
Definition at line 2476 of file debug.cc.
                                                        {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  if (in_debug_scope() || ignore_events()) return;
  MaybeDirectHandle<JSPromise> maybe_promise;
  if (IsJSPromise(*promise)) {
    DirectHandle<JSPromise> js_promise = Cast<JSPromise>(promise);
    if (js_promise->is_silent()) {
      return;
    }
    maybe_promise = js_promise;
  }
  OnException(value, maybe_promise, v8::debug::kPromiseRejection);
}
References ignore_events(), in_debug_scope(), isolate_, v8::debug::kPromiseRejection, OnException(), RCS_SCOPE, and v8::internal::value.
Referenced by v8::internal::JSPromise::Reject().
OnThrow()
std::optional< Tagged< Object > > v8::internal::Debug::OnThrow (DirectHandle< Object > exception)
Definition at line 2449 of file debug.cc.
                                                                         {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  if (in_debug_scope() || ignore_events()) return {};
  // Temporarily clear any exception to allow evaluating
  // JavaScript from the debug event handler.
  HandleScope scope(isolate_);
  {
    std::optional<Isolate::ExceptionScope> exception_scope;
    if (isolate_->has_exception()) exception_scope.emplace(isolate_);
    Isolate::CatchType catch_type = isolate_->PredictExceptionCatcher();
    OnException(exception, MaybeDirectHandle<JSPromise>(),
                catch_type == Isolate::CAUGHT_BY_ASYNC_AWAIT ||
                        catch_type == Isolate::CAUGHT_BY_PROMISE
                    ? v8::debug::kPromiseRejection
                    : v8::debug::kException);
  }
  PrepareStepOnThrow();
  // If the OnException handler requested termination, then indicated this to
  // our caller Isolate::Throw so it can deal with it immediately instead of
  // throwing the original exception.
  if (isolate_->stack_guard()->CheckTerminateExecution()) {
    isolate_->stack_guard()->ClearTerminateExecution();
    return isolate_->TerminateExecution();
  }
  return {};
}
References v8::internal::Isolate::CAUGHT_BY_ASYNC_AWAIT, v8::internal::Isolate::CAUGHT_BY_PROMISE, v8::internal::Isolate::has_exception(), ignore_events(), in_debug_scope(), isolate_, v8::debug::kException, v8::debug::kPromiseRejection, OnException(), v8::internal::Isolate::PredictExceptionCatcher(), PrepareStepOnThrow(), RCS_SCOPE, v8::internal::Isolate::stack_guard(), and v8::internal::Isolate::TerminateExecution().
Referenced by v8::internal::Isolate::Throw().
operator=()
Debug& v8::internal::Debug::operator= (const Debug &) [delete]
PerformSideEffectCheck()
bool v8::internal::Debug::PerformSideEffectCheck (DirectHandle< JSFunction > function, DirectHandle< Object > receiver)
Definition at line 3124 of file debug.cc.
                                                                  {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  DCHECK_EQ(isolate_->debug_execution_mode(), DebugInfo::kSideEffects);
  DisallowJavascriptExecution no_js(isolate_);
  IsCompiledScope is_compiled_scope(
      function->shared()->is_compiled_scope(isolate_));
  if (!function->is_compiled(isolate_) &&
      !Compiler::Compile(isolate_, function, Compiler::KEEP_EXCEPTION,
                         &is_compiled_scope)) {
    return false;
  }
  DCHECK(is_compiled_scope.is_compiled());
  DirectHandle<SharedFunctionInfo> shared(function->shared(), isolate_);
  DirectHandle<DebugInfo> debug_info = GetOrCreateDebugInfo(shared);
  DebugInfo::SideEffectState side_effect_state =
      debug_info->GetSideEffectState(isolate_);
  if (shared->HasBuiltinId()) {
    PrepareBuiltinForSideEffectCheck(isolate_, shared->builtin_id());
  }
  switch (side_effect_state) {
    case DebugInfo::kHasSideEffects:
      if (v8_flags.trace_side_effect_free_debug_evaluate) {
        PrintF("[debug-evaluate] Function %s failed side effect check.\n",
               function->shared()->DebugNameCStr().get());
      }
      side_effect_check_failed_ = true;
      // Throw an uncatchable termination exception.
      isolate_->TerminateExecution();
      return false;
    case DebugInfo::kRequiresRuntimeChecks: {
      if (!shared->HasBytecodeArray()) {
        return PerformSideEffectCheckForObject(receiver);
      }
      // If function has bytecode array then prepare function for debug
      // execution to perform runtime side effect checks.
      DCHECK(shared->is_compiled());
      PrepareFunctionForDebugExecution(shared);
      ApplySideEffectChecks(debug_info);
      return true;
    }
    case DebugInfo::kHasNoSideEffect:
      return true;
    case DebugInfo::kNotComputed:
    default:
      UNREACHABLE();
  }
}
References ApplySideEffectChecks(), v8::internal::Compiler::Compile(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Isolate::debug_execution_mode(), GetOrCreateDebugInfo(), v8::internal::IsCompiledScope::is_compiled(), isolate_, v8::internal::Compiler::KEEP_EXCEPTION, v8::internal::DebugInfo::kHasNoSideEffect, v8::internal::DebugInfo::kHasSideEffects, v8::internal::DebugInfo::kNotComputed, v8::internal::DebugInfo::kRequiresRuntimeChecks, v8::internal::DebugInfo::kSideEffects, PerformSideEffectCheckForObject(), PrepareBuiltinForSideEffectCheck(), PrepareFunctionForDebugExecution(), v8::internal::PrintF(), RCS_SCOPE, side_effect_check_failed_, v8::internal::Isolate::TerminateExecution(), v8::internal::UNREACHABLE(), and v8::internal::v8_flags.
PerformSideEffectCheckAtBytecode()
bool v8::internal::Debug::PerformSideEffectCheckAtBytecode (InterpretedFrame * frame)
Definition at line 3297 of file debug.cc.
                                                                    {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  using interpreter::Bytecode;
  DCHECK_EQ(isolate_->debug_execution_mode(), DebugInfo::kSideEffects);
  Tagged<SharedFunctionInfo> shared = frame->function()->shared();
  Tagged<BytecodeArray> bytecode_array = shared->GetBytecodeArray(isolate_);
  int offset = frame->GetBytecodeOffset();
  interpreter::BytecodeArrayIterator bytecode_iterator(
      handle(bytecode_array, isolate_), offset);
  Bytecode bytecode = bytecode_iterator.current_bytecode();
  if (interpreter::Bytecodes::IsCallRuntime(bytecode)) {
    auto id = (bytecode == Bytecode::kInvokeIntrinsic)
                  ? bytecode_iterator.GetIntrinsicIdOperand(0)
                  : bytecode_iterator.GetRuntimeIdOperand(0);
    if (DebugEvaluate::IsSideEffectFreeIntrinsic(id)) {
      return true;
    }
    side_effect_check_failed_ = true;
    // Throw an uncatchable termination exception.
    isolate_->TerminateExecution();
    return false;
  }
  interpreter::Register reg;
  switch (bytecode) {
    case Bytecode::kStaCurrentContextSlotNoCell:
      reg = interpreter::Register::current_context();
      break;
    default:
      reg = bytecode_iterator.GetRegisterOperand(0);
      break;
  }
  DirectHandle<Object> object(frame->ReadInterpreterRegister(reg.index()),
                              isolate_);
  return PerformSideEffectCheckForObject(object);
}
References v8::internal::interpreter::BytecodeArrayIterator::current_bytecode(), v8::internal::interpreter::Register::current_context(), DCHECK_EQ, v8::internal::Isolate::debug_execution_mode(), v8::internal::JavaScriptFrame::function(), v8::internal::InterpretedFrame::GetBytecodeOffset(), v8::internal::interpreter::BytecodeArrayIterator::GetIntrinsicIdOperand(), v8::internal::interpreter::BytecodeArrayIterator::GetRegisterOperand(), v8::internal::interpreter::BytecodeArrayIterator::GetRuntimeIdOperand(), v8::internal::handle(), v8::internal::interpreter::Register::index(), v8::internal::interpreter::Bytecodes::IsCallRuntime(), isolate_, v8::internal::DebugEvaluate::IsSideEffectFreeIntrinsic(), v8::internal::DebugInfo::kSideEffects, PerformSideEffectCheckForObject(), RCS_SCOPE, v8::internal::UnoptimizedJSFrame::ReadInterpreterRegister(), side_effect_check_failed_, and v8::internal::Isolate::TerminateExecution().
PerformSideEffectCheckForAccessor()
bool v8::internal::Debug::PerformSideEffectCheckForAccessor (DirectHandle< AccessorInfo > accessor_info, DirectHandle< Object > receiver, AccessorComponent component)
Definition at line 3200 of file debug.cc.
                                 {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  DCHECK_EQ(isolate_->debug_execution_mode(), DebugInfo::kSideEffects);
  // List of allowlisted internal accessors can be found in accessors.h.
  SideEffectType side_effect_type =
      component == AccessorComponent::ACCESSOR_SETTER
          ? accessor_info->setter_side_effect_type()
          : accessor_info->getter_side_effect_type();
  switch (side_effect_type) {
    case SideEffectType::kHasNoSideEffect:
      // We do not support setter accessors with no side effects, since
      // calling set accessors go through a store bytecode. Store bytecodes
      // are considered to cause side effects (to non-temporary objects).
      DCHECK_NE(AccessorComponent::ACCESSOR_SETTER, component);
      return true;
    case SideEffectType::kHasSideEffectToReceiver:
      DCHECK(!receiver.is_null());
      if (PerformSideEffectCheckForObject(receiver)) return true;
      return false;
    case SideEffectType::kHasSideEffect:
      break;
  }
  if (v8_flags.trace_side_effect_free_debug_evaluate) {
    PrintF("[debug-evaluate] API Callback '");
    ShortPrint(accessor_info->name());
    PrintF("' may cause side effect.\n");
  }
  side_effect_check_failed_ = true;
  // Throw an uncatchable termination exception.
  isolate_->TerminateExecution();
  return false;
}
References v8::internal::ACCESSOR_SETTER, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, v8::internal::Isolate::debug_execution_mode(), v8::internal::DirectHandle< T >::is_null(), isolate_, v8::kHasNoSideEffect, v8::kHasSideEffect, v8::kHasSideEffectToReceiver, v8::internal::DebugInfo::kSideEffects, PerformSideEffectCheckForObject(), v8::internal::PrintF(), RCS_SCOPE, v8::internal::ShortPrint(), side_effect_check_failed_, v8::internal::Isolate::TerminateExecution(), and v8::internal::v8_flags.
Referenced by v8::internal::InvokeAccessorGetterCallback().
PerformSideEffectCheckForCallback()
bool v8::internal::Debug::PerformSideEffectCheckForCallback (Handle< FunctionTemplateInfo > function)
Definition at line 3248 of file debug.cc.
                                           {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  DCHECK_EQ(isolate_->debug_execution_mode(), DebugInfo::kSideEffects);
  // If an empty |function| handle is passed here then it means that
  // the callback IS side-effectful (see CallApiCallbackWithSideEffects
  // builtin).
  if (!function.is_null() && !function->has_side_effects()) {
    return true;
  }
  if (!ignore_side_effects_for_function_template_info_.is_null()) {
    // If the |ignore_side_effects_for_function_template_info_| is set then
    // the next API callback call must be made to this function.
    CHECK(ignore_side_effects_for_function_template_info_.is_identical_to(
        function));
    ignore_side_effects_for_function_template_info_ = {};
    return true;
  }
  if (v8_flags.trace_side_effect_free_debug_evaluate) {
    PrintF("[debug-evaluate] FunctionTemplateInfo may cause side effect.\n");
  }
  side_effect_check_failed_ = true;
  // Throw an uncatchable termination exception.
  isolate_->TerminateExecution();
  return false;
}
References CHECK, DCHECK_EQ, v8::internal::Isolate::debug_execution_mode(), ignore_side_effects_for_function_template_info_, isolate_, v8::internal::DebugInfo::kSideEffects, v8::internal::PrintF(), RCS_SCOPE, side_effect_check_failed_, v8::internal::Isolate::TerminateExecution(), and v8::internal::v8_flags.
Referenced by v8::internal::FunctionCallbackArguments::CallOrConstruct(), and v8::internal::anonymous_namespace{api.cc}::InvokeFunctionCallback().
PerformSideEffectCheckForInterceptor()
bool v8::internal::Debug::PerformSideEffectCheckForInterceptor (DirectHandle< InterceptorInfo > interceptor_info)
Definition at line 3278 of file debug.cc.
                                                    {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  DCHECK_EQ(isolate_->debug_execution_mode(), DebugInfo::kSideEffects);
  // Empty InterceptorInfo represents operations that do produce side effects.
  if (!interceptor_info.is_null()) {
    if (interceptor_info->has_no_side_effect()) return true;
  }
  if (v8_flags.trace_side_effect_free_debug_evaluate) {
    PrintF("[debug-evaluate] API Interceptor may cause side effect.\n");
  }
  side_effect_check_failed_ = true;
  // Throw an uncatchable termination exception.
  isolate_->TerminateExecution();
  return false;
}
References DCHECK_EQ, v8::internal::Isolate::debug_execution_mode(), v8::internal::DirectHandle< T >::is_null(), isolate_, v8::internal::DebugInfo::kSideEffects, v8::internal::PrintF(), RCS_SCOPE, side_effect_check_failed_, v8::internal::Isolate::TerminateExecution(), and v8::internal::v8_flags.
PerformSideEffectCheckForObject()
bool v8::internal::Debug::PerformSideEffectCheckForObject (DirectHandle< Object > object)
Definition at line 3335 of file debug.cc.
                                                                       {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  DCHECK_EQ(isolate_->debug_execution_mode(), DebugInfo::kSideEffects);
  // We expect no side-effects for primitives.
  if (IsNumber(*object)) return true;
  if (IsName(*object)) return true;
  if (temporary_objects_->HasObject(Cast<HeapObject>(object))) {
    return true;
  }
  if (v8_flags.trace_side_effect_free_debug_evaluate) {
    PrintF("[debug-evaluate] failed runtime side effect check.\n");
  }
  side_effect_check_failed_ = true;
  // Throw an uncatchable termination exception.
  isolate_->TerminateExecution();
  return false;
}
References DCHECK_EQ, v8::internal::Isolate::debug_execution_mode(), v8::internal::IsNumber(), isolate_, v8::internal::DebugInfo::kSideEffects, v8::internal::PrintF(), RCS_SCOPE, side_effect_check_failed_, temporary_objects_, v8::internal::Isolate::TerminateExecution(), and v8::internal::v8_flags.
Referenced by PerformSideEffectCheck(), PerformSideEffectCheckAtBytecode(), and PerformSideEffectCheckForAccessor().
PrepareBuiltinForSideEffectCheck()
void v8::internal::Debug::PrepareBuiltinForSideEffectCheck (Isolate * isolate, Builtin id)
Definition at line 3177 of file debug.cc.
                                                                         {
  switch (id) {
    case Builtin::kStringPrototypeMatch:
    case Builtin::kStringPrototypeSearch:
    case Builtin::kStringPrototypeSplit:
    case Builtin::kStringPrototypeMatchAll:
    case Builtin::kStringPrototypeReplace:
    case Builtin::kStringPrototypeReplaceAll:
      if (Protectors::IsRegExpSpeciesLookupChainIntact(isolate_)) {
        // Force RegExps to go slow path so that we have a chance to perform
        // side-effect checks for the functions for Symbol.match,
        // Symbol.matchAll, Symbol.search, Symbol.split and Symbol.replace.
        if (v8_flags.trace_side_effect_free_debug_evaluate) {
          PrintF("[debug-evaluate] invalidating protector cell for RegExps\n");
        }
        Protectors::InvalidateRegExpSpeciesLookupChain(isolate_);
      }
      return;
    default:
      return;
  }
}
References isolate_, v8::internal::PrintF(), and v8::internal::v8_flags.
Referenced by PerformSideEffectCheck().
PrepareFunctionForDebugExecution()
void v8::internal::Debug::PrepareFunctionForDebugExecution (DirectHandle< SharedFunctionInfo > shared)
Definition at line 1799 of file debug.cc.
                                             {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  // To prepare bytecode for debugging, we already need to have the debug
  // info (containing the debug copy) upfront, but since we do not recompile,
  // preparing for break points cannot fail.
  DCHECK(shared->is_compiled());
  DirectHandle<DebugInfo> debug_info(TryGetDebugInfo(*shared).value(),
                                     isolate_);
  if (debug_info->flags(kRelaxedLoad) & DebugInfo::kPreparedForDebugExecution) {
    return;
  }
  // Have to discard baseline code before installing debug bytecode, since the
  // bytecode array field on the baseline code object is immutable.
  if (debug_info->CanBreakAtEntry()) {
    // Deopt everything in case the function is inlined anywhere.
    Deoptimizer::DeoptimizeAll(isolate_);
    DiscardAllBaselineCode();
  } else {
    DeoptimizeFunction(shared);
  }
  if (shared->HasBytecodeArray()) {
    DCHECK(!shared->HasBaselineCode());
    SharedFunctionInfo::InstallDebugBytecode(shared, isolate_);
  }
  if (debug_info->CanBreakAtEntry()) {
    InstallDebugBreakTrampoline();
  } else {
    // Update PCs on the stack to point to recompiled code.
    RedirectActiveFunctions redirect_visitor(
        isolate_, *shared, RedirectActiveFunctions::Mode::kUseDebugBytecode);
    redirect_visitor.VisitThread(isolate_, isolate_->thread_local_top());
    isolate_->thread_manager()->IterateArchivedThreads(&redirect_visitor);
  }
  debug_info->set_flags(
      debug_info->flags(kRelaxedLoad) | DebugInfo::kPreparedForDebugExecution,
      kRelaxedStore);
}
References v8::internal::DCHECK(), v8::internal::Deoptimizer::DeoptimizeAll(), DeoptimizeFunction(), DiscardAllBaselineCode(), InstallDebugBreakTrampoline(), v8::internal::SharedFunctionInfo::InstallDebugBytecode(), isolate_, v8::internal::ThreadManager::IterateArchivedThreads(), v8::kRelaxedLoad, v8::kRelaxedStore, v8::internal::RedirectActiveFunctions::kUseDebugBytecode, RCS_SCOPE, v8::internal::Isolate::thread_local_top(), v8::internal::Isolate::thread_manager(), TryGetDebugInfo(), and v8::internal::RedirectActiveFunctions::VisitThread().
Referenced by Break(), FindSharedFunctionInfosIntersectingRange(), FloodWithOneShot(), GetPossibleBreakpoints(), PerformSideEffectCheck(), PrepareStep(), SetBreakpoint(), and SetBreakPointForScript().
PrepareRestartFrame()
void v8::internal::Debug::PrepareRestartFrame (JavaScriptFrame * frame, int inlined_frame_index)
Definition at line 3369 of file debug.cc.
                                                         {
  if (frame->is_optimized())
    Deoptimizer::DeoptimizeFunction(frame->function(),
                                    LazyDeoptimizeReason::kDebugger);
  thread_local_.restart_frame_id_ = frame->id();
  thread_local_.restart_inline_frame_index_ = inlined_frame_index;
  // TODO(crbug.com/1303521): A full "StepInto" is probably not needed. Get the
  // necessary bits out of PrepareSTep into a separate method or fold them
  // into Debug::PrepareRestartFrame.
  PrepareStep(StepInto);
}
References v8::internal::Deoptimizer::DeoptimizeFunction(), v8::internal::JavaScriptFrame::function(), v8::internal::StackFrame::id(), v8::internal::JavaScriptFrame::is_optimized(), PrepareStep(), v8::internal::Debug::ThreadLocal::restart_frame_id_, v8::internal::Debug::ThreadLocal::restart_inline_frame_index_, v8::internal::StepInto, and thread_local_.
Referenced by v8::internal::DebugStackTraceIterator::PrepareRestart().
PrepareStep()
void v8::internal::Debug::PrepareStep (StepAction step_action)
Definition at line 1426 of file debug.cc.
                                              {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  HandleScope scope(isolate_);
  DCHECK(in_debug_scope());
  // Get the frame where the execution has stopped and skip the debug frame if
  // any. The debug frame will only be present if execution was stopped due to
  // hitting a break point. In other situations (e.g. unhandled exception) the
  // debug frame is not present.
  StackFrameId frame_id = break_frame_id();
  // If there is no JavaScript stack don't do anything.
  if (frame_id == StackFrameId::NO_ID) return;
  thread_local_.last_step_action_ = step_action;
  DebuggableStackFrameIterator frames_it(isolate_, frame_id);
  CommonFrame* frame = frames_it.frame();
  BreakLocation location = BreakLocation::Invalid();
  Handle<SharedFunctionInfo> shared;
  int current_frame_count = CurrentFrameCount();
  if (frame->is_javascript()) {
    JavaScriptFrame* js_frame = JavaScriptFrame::cast(frame);
    DCHECK(IsJSFunction(js_frame->function()));
    // Get the debug info (create it if it does not exist).
    auto summary = FrameSummary::GetTop(frame).AsJavaScript();
    DirectHandle<JSFunction> function(summary.function());
    shared = Handle<SharedFunctionInfo>(function->shared(), isolate_);
    if (!EnsureBreakInfo(shared)) return;
    PrepareFunctionForDebugExecution(shared);
    // PrepareFunctionForDebugExecution can invalidate Baseline frames
    js_frame = JavaScriptFrame::cast(frames_it.Reframe());
    Handle<DebugInfo> debug_info(TryGetDebugInfo(*shared).value(), isolate_);
    location = BreakLocation::FromFrame(debug_info, js_frame);
    // Any step at a return is a step-out, and a step-out at a suspend behaves
    // like a return.
    if (location.IsReturn() ||
        (location.IsSuspend() && step_action == StepOut)) {
      // On StepOut we'll ignore our further calls to current function in
      // PrepareStepIn callback.
      if (last_step_action() == StepOut) {
        thread_local_.ignore_step_into_function_ = *function;
      }
      step_action = StepOut;
      thread_local_.last_step_action_ = StepInto;
    }
    // We need to schedule DebugOnFunction call callback
    UpdateHookOnFunctionCall();
    // A step-next in blackboxed function is a step-out.
    if (step_action == StepOver && IsBlackboxed(shared)) step_action = StepOut;
    thread_local_.last_statement_position_ = summary.SourceStatementPosition();
    thread_local_.last_bytecode_offset_ = summary.code_offset();
    thread_local_.last_frame_count_ = current_frame_count;
    // No longer perform the current async step.
    clear_suspended_generator();
#if V8_ENABLE_WEBASSEMBLY
  } else if (frame->is_wasm() && step_action != StepOut) {
#if V8_ENABLE_DRUMBRAKE
    // TODO(paolosev@microsoft.com) - If we are running with the interpreter, we
    // cannot step.
    if (frame->is_wasm_interpreter_entry()) return;
#endif // V8_ENABLE_DRUMBRAKE
    // Handle stepping in wasm.
    WasmFrame* wasm_frame = WasmFrame::cast(frame);
    auto* debug_info = wasm_frame->native_module()->GetDebugInfo();
    if (debug_info->PrepareStep(wasm_frame)) {
      UpdateHookOnFunctionCall();
      return;
    }
    // If the wasm code is not debuggable or will return after this step
    // (indicated by {PrepareStep} returning false), then step out of that frame
    // instead.
    step_action = StepOut;
    UpdateHookOnFunctionCall();
#endif // V8_ENABLE_WEBASSEMBLY
  }
  switch (step_action) {
    case StepNone:
      UNREACHABLE();
    case StepOut: {
      // Clear last position info. For stepping out it does not matter.
      thread_local_.last_statement_position_ = kNoSourcePosition;
      thread_local_.last_bytecode_offset_ = kFunctionEntryBytecodeOffset;
      thread_local_.last_frame_count_ = -1;
      if (!shared.is_null()) {
        if (!location.IsReturnOrSuspend() && !IsBlackboxed(shared)) {
          // At not return position we flood return positions with one shots and
          // will repeat StepOut automatically at next break.
          thread_local_.target_frame_count_ = current_frame_count;
          thread_local_.fast_forward_to_return_ = true;
          FloodWithOneShot(shared, true);
          return;
        }
        if (IsAsyncFunction(shared->kind())) {
          // Stepping out of an async function whose implicit promise is awaited
          // by some other async function, should resume the latter. The return
          // value here is either a JSPromise or a JSGeneratorObject (for the
          // initial yield of async generators).
          DirectHandle<JSReceiver> return_value(
              Cast<JSReceiver>(thread_local_.return_value_), isolate_);
          DirectHandle<Object> awaited_by_holder = JSReceiver::GetDataProperty(
              isolate_, return_value,
              isolate_->factory()->promise_awaited_by_symbol());
          if (IsWeakFixedArray(*awaited_by_holder, isolate_)) {
            auto weak_fixed_array = Cast<WeakFixedArray>(awaited_by_holder);
            if (weak_fixed_array->length() == 1 &&
                weak_fixed_array->get(0).IsWeak()) {
              DirectHandle<HeapObject> awaited_by(
                  weak_fixed_array->get(0).GetHeapObjectAssumeWeak(isolate_),
                  isolate_);
              if (IsJSGeneratorObject(*awaited_by)) {
                DCHECK(!has_suspended_generator());
                thread_local_.suspended_generator_ = *awaited_by;
                ClearStepping();
                return;
              }
            }
          }
        }
      }
      // Skip the current frame, find the first frame we want to step out to
      // and deoptimize every frame along the way.
      bool in_current_frame = true;
      for (; !frames_it.done(); frames_it.Advance()) {
#if V8_ENABLE_WEBASSEMBLY
#if V8_ENABLE_DRUMBRAKE
        // TODO(paolosev@microsoft.com): Implement stepping out from JS to wasm
        // interpreter.
        if (frame->is_wasm_interpreter_entry()) continue;
#endif // V8_ENABLE_DRUMBRAKE
        if (frames_it.frame()->is_wasm()) {
          if (in_current_frame) {
            in_current_frame = false;
            continue;
          }
          // Handle stepping out into Wasm.
          WasmFrame* wasm_frame = WasmFrame::cast(frames_it.frame());
          auto* debug_info = wasm_frame->native_module()->GetDebugInfo();
          if (debug_info->IsFrameBlackboxed(wasm_frame)) continue;
          debug_info->PrepareStepOutTo(wasm_frame);
          return;
        }
#endif // V8_ENABLE_WEBASSEMBLY
        JavaScriptFrame* js_frame = JavaScriptFrame::cast(frames_it.frame());
        if (last_step_action() == StepInto) {
          // Deoptimize frame to ensure calls are checked for step-in.
          Deoptimizer::DeoptimizeFunction(js_frame->function(),
                                          LazyDeoptimizeReason::kDebugger);
        }
        HandleScope inner_scope(isolate_);
        std::vector<Handle<SharedFunctionInfo>> infos;
        js_frame->GetFunctions(&infos);
        for (; !infos.empty(); current_frame_count--) {
          Handle<SharedFunctionInfo> info = infos.back();
          infos.pop_back();
          if (in_current_frame) {
            // We want to step out, so skip the current frame.
            in_current_frame = false;
            continue;
          }
          if (IsBlackboxed(info)) continue;
          FloodWithOneShot(info);
          thread_local_.target_frame_count_ = current_frame_count;
          return;
        }
      }
      break;
    }
    case StepOver:
      thread_local_.target_frame_count_ = current_frame_count;
      [[fallthrough]];
    case StepInto:
      FloodWithOneShot(shared);
      break;
  }
}
References v8::internal::DebuggableStackFrameIterator::Advance(), break_frame_id(), v8::internal::JavaScriptFrame::cast(), clear_suspended_generator(), ClearStepping(), CurrentFrameCount(), v8::internal::DCHECK(), v8::internal::Deoptimizer::DeoptimizeFunction(), v8::internal::DebuggableStackFrameIterator::done(), EnsureBreakInfo(), v8::internal::Isolate::factory(), v8::internal::Debug::ThreadLocal::fast_forward_to_return_, FloodWithOneShot(), v8::internal::DebuggableStackFrameIterator::frame(), v8::internal::BreakLocation::FromFrame(), v8::internal::JavaScriptFrame::function(), v8::internal::JSReceiver::GetDataProperty(), v8::internal::JavaScriptFrame::GetFunctions(), v8::internal::FrameSummary::GetTop(), has_suspended_generator(), v8::internal::Debug::ThreadLocal::ignore_step_into_function_, in_debug_scope(), v8::internal::BreakLocation::Invalid(), v8::internal::StackFrame::is_javascript(), v8::internal::HandleBase::is_null(), v8::internal::IsAsyncFunction(), IsBlackboxed(), isolate_, v8::internal::BreakLocation::IsReturn(), v8::internal::BreakLocation::IsReturnOrSuspend(), v8::internal::BreakLocation::IsSuspend(), v8::internal::kFunctionEntryBytecodeOffset, v8::internal::kNoSourcePosition, v8::internal::Debug::ThreadLocal::last_bytecode_offset_, v8::internal::Debug::ThreadLocal::last_frame_count_, v8::internal::Debug::ThreadLocal::last_statement_position_, last_step_action(), v8::internal::Debug::ThreadLocal::last_step_action_, v8::internal::NO_ID, PrepareFunctionForDebugExecution(), RCS_SCOPE, v8::internal::DebuggableStackFrameIterator::Reframe(), return_value(), v8::internal::Debug::ThreadLocal::return_value_, v8::internal::StepInto, v8::internal::StepNone, v8::internal::StepOut, v8::internal::StepOver, v8::internal::Debug::ThreadLocal::suspended_generator_, v8::internal::Debug::ThreadLocal::target_frame_count_, thread_local_, TryGetDebugInfo(), v8::internal::UNREACHABLE(), and UpdateHookOnFunctionCall().
Referenced by Break(), OnDebugBreak(), PrepareRestartFrame(), v8::debug::PrepareStep(), and RestoreDebug().
PrepareStepIn()
void v8::internal::Debug::PrepareStepIn (DirectHandle< JSFunction > function)
Definition at line 1325 of file debug.cc.
                                                           {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  CHECK(last_step_action() >= StepInto || break_on_next_function_call() ||
        scheduled_break_on_function_call());
  if (ignore_events()) return;
  if (in_debug_scope()) return;
  if (break_disabled()) return;
  Handle<SharedFunctionInfo> shared(function->shared(), isolate_);
  if (IsBlackboxed(shared)) return;
  if (*function == thread_local_.ignore_step_into_function_) return;
  thread_local_.ignore_step_into_function_ = Smi::zero();
  FloodWithOneShot(shared);
}
References break_disabled(), break_on_next_function_call(), CHECK, FloodWithOneShot(), ignore_events(), v8::internal::Debug::ThreadLocal::ignore_step_into_function_, in_debug_scope(), IsBlackboxed(), isolate_, last_step_action(), RCS_SCOPE, scheduled_break_on_function_call(), v8::internal::StepInto, thread_local_, and v8::internal::Smi::zero().
Referenced by HandleDebugBreak().
PrepareStepInSuspendedGenerator()
void v8::internal::Debug::PrepareStepInSuspendedGenerator ()
Definition at line 1339 of file debug.cc.
                                            {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  CHECK(has_suspended_generator());
  if (ignore_events()) return;
  if (in_debug_scope()) return;
  if (break_disabled()) return;
  thread_local_.last_step_action_ = StepInto;
  UpdateHookOnFunctionCall();
  DirectHandle<JSFunction> function(
      Cast<JSGeneratorObject>(thread_local_.suspended_generator_)->function(),
      isolate_);
  FloodWithOneShot(handle(function->shared(), isolate_));
  clear_suspended_generator();
}
References break_disabled(), CHECK, clear_suspended_generator(), FloodWithOneShot(), v8::internal::handle(), has_suspended_generator(), ignore_events(), in_debug_scope(), isolate_, v8::internal::Debug::ThreadLocal::last_step_action_, RCS_SCOPE, v8::internal::StepInto, v8::internal::Debug::ThreadLocal::suspended_generator_, thread_local_, and UpdateHookOnFunctionCall().
PrepareStepOnThrow()
void v8::internal::Debug::PrepareStepOnThrow ()
Definition at line 1354 of file debug.cc.
                               {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  if (last_step_action() == StepNone) return;
  if (ignore_events()) return;
  if (in_debug_scope()) return;
  if (break_disabled()) return;
  ClearOneShot();
  int current_frame_count = CurrentFrameCount();
  // Iterate through the JavaScript stack looking for handlers.
  JavaScriptStackFrameIterator it(isolate_);
  while (!it.done()) {
    JavaScriptFrame* frame = it.frame();
    if (frame->LookupExceptionHandlerInTable(nullptr, nullptr) > 0) break;
    std::vector<Tagged<SharedFunctionInfo>> infos;
    frame->GetFunctions(&infos);
    current_frame_count -= infos.size();
    it.Advance();
  }
  // No handler found. Nothing to instrument.
  if (it.done()) return;
  bool found_handler = false;
  // Iterate frames, including inlined frames. First, find the handler frame.
  // Then skip to the frame we want to break in, then instrument for stepping.
  for (; !it.done(); it.Advance()) {
    JavaScriptFrame* frame = JavaScriptFrame::cast(it.frame());
    if (last_step_action() == StepInto) {
      // Deoptimize frame to ensure calls are checked for step-in.
      Deoptimizer::DeoptimizeFunction(frame->function(),
                                      LazyDeoptimizeReason::kDebugger);
    }
    FrameSummaries summaries = frame->Summarize();
    for (size_t i = summaries.size(); i != 0; i--, current_frame_count--) {
      const FrameSummary& summary = summaries.frames[i - 1];
      if (!found_handler) {
        // We have yet to find the handler. If the frame inlines multiple
        // functions, we have to check each one for the handler.
        // If it only contains one function, we already found the handler.
        if (summaries.size() > 1) {
          DirectHandle<AbstractCode> code =
              summary.AsJavaScript().abstract_code();
          CHECK_EQ(CodeKind::INTERPRETED_FUNCTION, code->kind(isolate_));
          HandlerTable table(code->GetBytecodeArray());
          int code_offset = summary.code_offset();
          found_handler = table.LookupHandlerIndexForRange(code_offset) !=
                          HandlerTable::kNoHandlerFound;
        } else {
          found_handler = true;
        }
      }
      if (found_handler) {
        // We found the handler. If we are stepping next or out, we need to
        // iterate until we found the suitable target frame to break in.
        if ((last_step_action() == StepOver || last_step_action() == StepOut) &&
            current_frame_count > thread_local_.target_frame_count_) {
          continue;
        }
        Handle<SharedFunctionInfo> info(
            summary.AsJavaScript().function()->shared(), isolate_);
        if (IsBlackboxed(info)) continue;
        FloodWithOneShot(info);
        return;
      }
    }
  }
}
References v8::internal::JavaScriptStackFrameIterator::Advance(), break_disabled(), v8::internal::JavaScriptFrame::cast(), CHECK_EQ, ClearOneShot(), code, v8::internal::FrameSummary::code_offset(), CurrentFrameCount(), v8::internal::Deoptimizer::DeoptimizeFunction(), v8::internal::JavaScriptStackFrameIterator::done(), FloodWithOneShot(), v8::internal::JavaScriptStackFrameIterator::frame(), v8::internal::FrameSummaries::frames, v8::internal::JavaScriptFrame::function(), v8::internal::JavaScriptFrame::GetFunctions(), ignore_events(), in_debug_scope(), IsBlackboxed(), isolate_, v8::internal::HandlerTable::kNoHandlerFound, last_step_action(), v8::internal::CommonFrameWithJSLinkage::LookupExceptionHandlerInTable(), v8::internal::HandlerTable::LookupHandlerIndexForRange(), RCS_SCOPE, v8::internal::FrameSummaries::size(), v8::internal::StepInto, v8::internal::StepNone, v8::internal::StepOut, v8::internal::StepOver, v8::internal::CommonFrameWithJSLinkage::Summarize(), v8::internal::Debug::ThreadLocal::target_frame_count_, and thread_local_.
Referenced by OnThrow().
PrintBreakLocation()
void v8::internal::Debug::PrintBreakLocation () [private]
Referenced by OnDebugBreak().
ProcessCompileEvent()
void v8::internal::Debug::ProcessCompileEvent (bool has_compile_error, DirectHandle< Script > script) [private]
Definition at line 2765 of file debug.cc.
                                                             {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  // Ignore temporary scripts.
  if (script->id() == Script::kTemporaryScriptId) return;
  // TODO(kozyatinskiy): teach devtools to work with liveedit scripts better
  // first and then remove this fast return.
  if (running_live_edit_) return;
  // Attach the correct debug id to the script. The debug id is used by the
  // inspector to filter scripts by native context.
  script->set_context_data(isolate_->native_context()->debug_context_id());
  if (ignore_events()) return;
  if (!script->IsSubjectToDebugging()) return;
  if (!debug_delegate_) return;
  SuppressDebug while_processing(this);
  DebugScope debug_scope(this);
  HandleScope scope(isolate_);
  DisableBreak no_recursive_break(this);
  AllowJavascriptExecution allow_script(isolate_);
  {
    RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebuggerCallback);
    debug_delegate_->ScriptCompiled(ToApiHandle<debug::Script>(script),
                                    running_live_edit_, has_compile_error);
  }
}
References debug_delegate_, ignore_events(), isolate_, v8::internal::Script::kTemporaryScriptId, v8::internal::Isolate::native_context(), RCS_SCOPE, running_live_edit_, v8::internal::script, and v8::debug::DebugDelegate::ScriptCompiled().
Referenced by OnAfterCompile(), and OnCompileError().
RemoveAllCoverageInfos()
void v8::internal::Debug::RemoveAllCoverageInfos ()
Definition at line 2347 of file debug.cc.
                                   {
  ClearAllDebugInfos([=, this](DirectHandle<DebugInfo> info) {
    info->ClearCoverageInfo(isolate_);
  });
}
References ClearAllDebugInfos(), and isolate_.
Referenced by v8::internal::Coverage::SelectMode(), and Unload().
RemoveBreakInfoAndMaybeFree()
void v8::internal::Debug::RemoveBreakInfoAndMaybeFree (DirectHandle< DebugInfo > debug_info)
Definition at line 2370 of file debug.cc.
                                                                          {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  debug_info->ClearBreakInfo(isolate_);
  if (debug_info->IsEmpty()) {
    debug_infos_.DeleteSlow(debug_info->shared());
  }
}
References debug_infos_, v8::internal::DebugInfoCollection::DeleteSlow(), isolate_, and RCS_SCOPE.
Referenced by v8::internal::LiveEdit::PatchScript().
RemoveBreakpoint()
void v8::internal::Debug::RemoveBreakpoint (int id)
Definition at line 1153 of file debug.cc.
                                   {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  DirectHandle<BreakPoint> breakpoint = isolate_->factory()->NewBreakPoint(
      id, isolate_->factory()->empty_string());
  ClearBreakPoint(breakpoint);
}
References ClearBreakPoint(), v8::internal::Isolate::factory(), isolate_, v8::internal::Factory::NewBreakPoint(), and RCS_SCOPE.
Referenced by v8::debug::RemoveBreakpoint().
restart_inline_frame_index()
int v8::internal::Debug::restart_inline_frame_index () const [inline]
Definition at line 479 of file debug.h.
                                         {
    return thread_local_.restart_inline_frame_index_;
  }
Referenced by v8::internal::Deoptimizer::Deoptimizer().
RestoreDebug()
char * v8::internal::Debug::RestoreDebug (char * from)
Definition at line 492 of file debug.cc.
                                       {
  MemCopy(reinterpret_cast<char*>(&thread_local_), storage,
          ArchiveSpacePerThread());
  // Enter the isolate.
  v8::Isolate::Scope isolate_scope(reinterpret_cast<v8::Isolate*>(isolate_));
  // Enter the debugger.
  DebugScope debug_scope(this);
  // Clear any one-shot breakpoints that may have been set by the other
  // thread, and reapply breakpoints for this thread.
  ClearOneShot();
  if (thread_local_.last_step_action_ != StepNone) {
    int current_frame_count = CurrentFrameCount();
    int target_frame_count = thread_local_.target_frame_count_;
    DCHECK(current_frame_count >= target_frame_count);
    DebuggableStackFrameIterator frames_it(isolate_);
    while (current_frame_count > target_frame_count) {
      current_frame_count -= frames_it.FrameFunctionCount();
      frames_it.Advance();
    }
    DCHECK(current_frame_count == target_frame_count);
    // Set frame to what it was at Step break
    thread_local_.break_frame_id_ = frames_it.frame()->id();
    // Reset the previous step action for this thread.
    PrepareStep(thread_local_.last_step_action_);
  }
  return storage + ArchiveSpacePerThread();
}
References v8::internal::DebuggableStackFrameIterator::Advance(), ArchiveSpacePerThread(), v8::internal::Debug::ThreadLocal::break_frame_id_, ClearOneShot(), CurrentFrameCount(), v8::internal::DCHECK(), v8::internal::DebuggableStackFrameIterator::frame(), v8::internal::DebuggableStackFrameIterator::FrameFunctionCount(), v8::internal::StackFrame::id(), isolate_, v8::internal::Debug::ThreadLocal::last_step_action_, v8::internal::MemCopy(), PrepareStep(), v8::internal::StepNone, v8::internal::Debug::ThreadLocal::target_frame_count_, and thread_local_.
Referenced by v8::internal::ThreadManager::RestoreThread().
return_value()
Tagged<Object> v8::internal::Debug::return_value () [inline]
Definition at line 444 of file debug.h.
{ return thread_local_.return_value_; }
Referenced by PrepareStep().
return_value_handle()
Handle< Object > v8::internal::Debug::return_value_handle ()
Definition at line 3173 of file debug.cc.
                                          {
  return handle(thread_local_.return_value_, isolate_);
}
References v8::internal::handle(), isolate_, v8::internal::Debug::ThreadLocal::return_value_, and thread_local_.
Referenced by v8::internal::DebugStackTraceIterator::GetReturnValue(), and v8::internal::ReturnValueScope::ReturnValueScope().
scheduled_break_on_function_call()
bool v8::internal::Debug::scheduled_break_on_function_call () const [inline]
Definition at line 465 of file debug.h.
                                                {
    return thread_local_.scheduled_break_on_next_function_call_;
  }
Referenced by Break(), and PrepareStepIn().
set_break_points_active()
void v8::internal::Debug::set_break_points_active (bool v) [inline]
Definition at line 438 of file debug.h.
{ break_points_active_ = v; }
Referenced by v8::debug::SetBreakPointsActive().
set_return_value()
void v8::internal::Debug::set_return_value (Tagged< Object > value) [inline]
Definition at line 445 of file debug.h.
                                              {
    thread_local_.return_value_ = value;
  }
References v8::internal::value.
Referenced by v8::debug::SetReturnValue(), and v8::internal::ReturnValueScope::~ReturnValueScope().
SetBreakOnNextFunctionCall()
void v8::internal::Debug::SetBreakOnNextFunctionCall ()
Definition at line 1309 of file debug.cc.
                                       {
  // This method forces V8 to break on next function call regardless current
  // last_step_action_. If any break happens between SetBreakOnNextFunctionCall
  // and ClearBreakOnNextFunctionCall, we will clear this flag and stepping. If
  // break does not happen, e.g. all called functions are blackboxed or no
  // function is called, then we will clear this flag and let stepping continue
  // its normal business.
  thread_local_.break_on_next_function_call_ = true;
  UpdateHookOnFunctionCall();
}
References v8::internal::Debug::ThreadLocal::break_on_next_function_call_, thread_local_, and UpdateHookOnFunctionCall().
SetBreakpoint()
bool v8::internal::Debug::SetBreakpoint (Handle< SharedFunctionInfo > shared, DirectHandle< BreakPoint > break_point, int * source_position)
Definition at line 973 of file debug.cc.
                                                {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  HandleScope scope(isolate_);
  // Make sure the function is compiled and has set up the debug info.
  if (!EnsureBreakInfo(shared)) return false;
  PrepareFunctionForDebugExecution(shared);
  Handle<DebugInfo> debug_info(TryGetDebugInfo(*shared).value(), isolate_);
  // Source positions starts with zero.
  DCHECK_LE(0, *source_position);
  // Find the break point and change it.
  *source_position = FindBreakablePosition(debug_info, *source_position);
  DebugInfo::SetBreakPoint(isolate_, debug_info, *source_position, break_point);
  // At least one active break point now.
  DCHECK_LT(0, debug_info->GetBreakPointCount(isolate_));
  ClearBreakPoints(debug_info);
  ApplyBreakPoints(debug_info);
  return true;
}
References ApplyBreakPoints(), ClearBreakPoints(), DCHECK_LE, DCHECK_LT, EnsureBreakInfo(), FindBreakablePosition(), isolate_, PrepareFunctionForDebugExecution(), RCS_SCOPE, v8::internal::DebugInfo::SetBreakPoint(), and TryGetDebugInfo().
Referenced by SetBreakpointForFunction(), and SetBreakPointForScript().
SetBreakpointForFunction()
bool v8::internal::Debug::SetBreakpointForFunction (Handle< SharedFunctionInfo > shared, DirectHandle< String > condition, int * id, BreakPointKind kind = kRegular)
Definition at line 1124 of file debug.cc.
                                                          {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  if (kind == kInstrumentation) {
    *id = kInstrumentationId;
  } else {
    *id = ++thread_local_.last_breakpoint_id_;
  }
  DirectHandle<BreakPoint> breakpoint =
      isolate_->factory()->NewBreakPoint(*id, condition);
  int source_position = 0;
#if V8_ENABLE_WEBASSEMBLY
  if (shared->HasWasmExportedFunctionData(isolate_)) {
    Tagged<WasmExportedFunctionData> function_data =
        shared->wasm_exported_function_data();
    int func_index = function_data->function_index();
    // TODO(42204563): Avoid crashing if the instance object is not available.
    CHECK(function_data->instance_data()->has_instance_object());
    Tagged<WasmModuleObject> module_obj =
        function_data->instance_data()->instance_object()->module_object();
    DirectHandle<Script> script(module_obj->script(), isolate_);
    return WasmScript::SetBreakPointOnFirstBreakableForFunction(
        script, func_index, breakpoint);
  }
#endif // V8_ENABLE_WEBASSEMBLY
  return SetBreakpoint(shared, breakpoint, &source_position);
}
References CHECK, v8::internal::Isolate::factory(), isolate_, kInstrumentation, kInstrumentationId, v8::internal::Debug::ThreadLocal::last_breakpoint_id_, v8::internal::Factory::NewBreakPoint(), RCS_SCOPE, v8::internal::script, SetBreakpoint(), v8::internal::WasmScript::SetBreakPointOnFirstBreakableForFunction(), and thread_local_.
Referenced by v8::debug::SetFunctionBreakpoint(), and v8::debug::Script::SetInstrumentationBreakpoint().
SetBreakPointForScript()
bool v8::internal::Debug::SetBreakPointForScript (Handle< Script > script, DirectHandle< String > condition, int * source_position, int * id)
Definition at line 998 of file debug.cc.
                                                                  {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  *id = ++thread_local_.last_breakpoint_id_;
  DirectHandle<BreakPoint> break_point =
      isolate_->factory()->NewBreakPoint(*id, condition);
#if V8_ENABLE_WEBASSEMBLY
  if (script->type() == Script::Type::kWasm) {
    RecordWasmScriptWithBreakpoints(script);
    return WasmScript::SetBreakPoint(script, source_position, break_point);
  }
#endif // V8_ENABLE_WEBASSEMBLY
  HandleScope scope(isolate_);
  // Obtain shared function info for the innermost function containing this
  // position.
  Handle<Object> result =
      FindInnermostContainingFunctionInfo(script, *source_position);
  if (IsUndefined(*result, isolate_)) return false;
  auto shared = Cast<SharedFunctionInfo>(result);
  if (!EnsureBreakInfo(shared)) return false;
  PrepareFunctionForDebugExecution(shared);
  // Find the nested shared function info that is closest to the position within
  // the containing function.
  shared = FindClosestSharedFunctionInfoFromPosition(*source_position, script,
                                                     shared);
  // Set the breakpoint in the function.
  return SetBreakpoint(shared, break_point, source_position);
}
References EnsureBreakInfo(), v8::internal::Isolate::factory(), FindClosestSharedFunctionInfoFromPosition(), FindInnermostContainingFunctionInfo(), isolate_, v8::internal::Debug::ThreadLocal::last_breakpoint_id_, v8::internal::Factory::NewBreakPoint(), PrepareFunctionForDebugExecution(), RCS_SCOPE, v8::base::internal::result, v8::internal::script, v8::internal::WasmScript::SetBreakPoint(), SetBreakpoint(), and thread_local_.
Referenced by v8::internal::wasm::gdb_server::WasmModuleDebug::AddBreakpoint(), and v8::debug::Script::SetBreakpoint().
SetDebugDelegate()
void v8::internal::Debug::SetDebugDelegate (debug::DebugDelegate * delegate)
Definition at line 2805 of file debug.cc.
                                                         {
  debug_delegate_ = delegate;
  UpdateState();
}
References debug_delegate_, and UpdateState().
Referenced by v8::internal::wasm::gdb_server::GdbServer::DebugDelegate::DebugDelegate(), and v8::debug::SetDebugDelegate().
SetIsolateId()
void v8::internal::Debug::SetIsolateId (uint64_t id) [inline]
Definition at line 507 of file debug.h.
{ isolate_id_ = id; }
Referenced by v8::debug::SetIsolateId().
SetMutedLocation()
void v8::internal::Debug::SetMutedLocation (DirectHandle< SharedFunctionInfo > function, const BreakLocation & location) [private]
Definition at line 1686 of file debug.cc.
                                                            {
  thread_local_.muted_function_ = *function;
  thread_local_.muted_position_ = location.position();
}
References v8::internal::Debug::ThreadLocal::muted_function_, v8::internal::Debug::ThreadLocal::muted_position_, v8::internal::BreakLocation::position(), and thread_local_.
Referenced by Break().
SetScriptSource()
bool v8::internal::Debug::SetScriptSource (Handle< Script > script, Handle< String > source, bool preview, bool allow_top_frame_live_editing, debug::LiveEditResult * result)
Definition at line 2745 of file debug.cc.
                                                         {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  DebugScope debug_scope(this);
  running_live_edit_ = true;
  LiveEdit::PatchScript(isolate_, script, source, preview,
                        allow_top_frame_live_editing, result);
  running_live_edit_ = false;
  return result->status == debug::LiveEditResult::OK;
}
References isolate_, v8::debug::LiveEditResult::OK, v8::internal::LiveEdit::PatchScript(), RCS_SCOPE, v8::base::internal::result, running_live_edit_, and v8::internal::script.
Referenced by v8::debug::Script::SetScriptSource().
SetTemporaryObjectTrackingDisabled()
void v8::internal::Debug::SetTemporaryObjectTrackingDisabled (bool disabled) [private]
Definition at line 3356 of file debug.cc.
                                                            {
  if (temporary_objects_) {
    temporary_objects_->disabled = disabled;
  }
}
References temporary_objects_.
Referenced by v8::internal::DisableTemporaryObjectTracking::DisableTemporaryObjectTracking(), and v8::internal::DisableTemporaryObjectTracking::~DisableTemporaryObjectTracking().
SetTerminateOnResume()
void v8::internal::Debug::SetTerminateOnResume ()
Definition at line 3035 of file debug.cc.
                                 {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  DebugScope* scope = reinterpret_cast<DebugScope*>(
      base::Acquire_Load(&thread_local_.current_debug_scope_));
  CHECK_NOT_NULL(scope);
  scope->set_terminate_on_resume();
}
References v8::base::Acquire_Load(), CHECK_NOT_NULL, v8::internal::Debug::ThreadLocal::current_debug_scope_, isolate_, RCS_SCOPE, v8::internal::DebugScope::set_terminate_on_resume(), and thread_local_.
Referenced by v8::debug::SetTerminateOnResume().
ShouldBeSkipped()
bool v8::internal::Debug::ShouldBeSkipped ()
Definition at line 2696 of file debug.cc.
                            {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  SuppressDebug while_processing(this);
  PostponeInterruptsScope no_interrupts(isolate_);
  DisableBreak no_recursive_break(this);
  DebuggableStackFrameIterator iterator(isolate_);
  FrameSummary summary = iterator.GetTopValidFrame();
  DirectHandle<Object> script_obj = summary.script();
  if (!IsScript(*script_obj)) return false;
  DirectHandle<Script> script = Cast<Script>(script_obj);
  summary.EnsureSourcePositionsAvailable();
  int source_position = summary.SourcePosition();
  Script::PositionInfo info;
  Script::GetPositionInfo(script, source_position, &info);
  {
    RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebuggerCallback);
    return debug_delegate_->ShouldBeSkipped(ToApiHandle<debug::Script>(script),
                                            info.line, info.column);
  }
}
References v8::internal::Script::PositionInfo::column, debug_delegate_, v8::internal::FrameSummary::EnsureSourcePositionsAvailable(), v8::internal::Script::GetPositionInfo(), v8::internal::DebuggableStackFrameIterator::GetTopValidFrame(), isolate_, v8::internal::Script::PositionInfo::line, RCS_SCOPE, v8::internal::FrameSummary::script(), v8::internal::script, v8::debug::DebugDelegate::ShouldBeSkipped(), and v8::internal::FrameSummary::SourcePosition().
Referenced by OnDebugBreak().
ShouldRestartFrame()
bool v8::internal::Debug::ShouldRestartFrame (StackFrameId id) const [inline]
Definition at line 472 of file debug.h.
                                                 {
    return IsRestartFrameScheduled() && thread_local_.restart_frame_id_ == id;
  }
StartSideEffectCheckMode()
void v8::internal::Debug::StartSideEffectCheckMode ()
Definition at line 3043 of file debug.cc.
                                     {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  DCHECK_EQ(isolate_->debug_execution_mode(), DebugInfo::kBreakpoints);
  isolate_->set_debug_execution_mode(DebugInfo::kSideEffects);
  UpdateHookOnFunctionCall();
  side_effect_check_failed_ = false;
  DCHECK(!temporary_objects_);
  temporary_objects_.reset(new TemporaryObjectsTracker());
  isolate_->heap()->AddHeapObjectAllocationTracker(temporary_objects_.get());
  DirectHandle<RegExpMatchInfo> current_match_info(
      isolate_->native_context()->regexp_last_match_info(), isolate_);
  int register_count = current_match_info->number_of_capture_registers();
  regexp_match_info_ = indirect_handle(
      RegExpMatchInfo::New(isolate_,
                           JSRegExp::CaptureCountForRegisters(register_count)),
      isolate_);
  DCHECK_EQ(regexp_match_info_->number_of_capture_registers(),
            current_match_info->number_of_capture_registers());
  regexp_match_info_->set_last_subject(current_match_info->last_subject());
  regexp_match_info_->set_last_input(current_match_info->last_input());
  RegExpMatchInfo::CopyElements(isolate_, *regexp_match_info_, 0,
                                *current_match_info, 0, register_count,
                                SKIP_WRITE_BARRIER);
  // Update debug infos to have correct execution mode.
  UpdateDebugInfosForExecutionMode();
}
References v8::internal::Heap::AddHeapObjectAllocationTracker(), v8::internal::JSRegExp::CaptureCountForRegisters(), v8::internal::TaggedArrayBase< RegExpMatchInfo, RegExpMatchInfoShape >::CopyElements(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Isolate::debug_execution_mode(), v8::internal::Isolate::heap(), v8::internal::indirect_handle(), isolate_, v8::internal::DebugInfo::kBreakpoints, v8::internal::DebugInfo::kSideEffects, v8::internal::Isolate::native_context(), v8::internal::RegExpMatchInfo::New(), RCS_SCOPE, regexp_match_info_, v8::internal::Isolate::set_debug_execution_mode(), side_effect_check_failed_, v8::internal::SKIP_WRITE_BARRIER, temporary_objects_, UpdateDebugInfosForExecutionMode(), and UpdateHookOnFunctionCall().
Referenced by v8::debug::CallFunctionOn(), v8::internal::DebugEvaluate::Evaluate(), and v8::internal::DebugEvaluate::Global().
StopSideEffectCheckMode()
void v8::internal::Debug::StopSideEffectCheckMode ()
Definition at line 3073 of file debug.cc.
                                    {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  DCHECK_EQ(isolate_->debug_execution_mode(), DebugInfo::kSideEffects);
  if (side_effect_check_failed_) {
    DCHECK(isolate_->has_exception());
    DCHECK_IMPLIES(v8_flags.strict_termination_checks,
                   isolate_->is_execution_terminating());
    // Convert the termination exception into a regular exception.
    isolate_->CancelTerminateExecution();
    isolate_->Throw(*isolate_->factory()->NewEvalError(
        MessageTemplate::kNoSideEffectDebugEvaluate));
  }
  isolate_->set_debug_execution_mode(DebugInfo::kBreakpoints);
  UpdateHookOnFunctionCall();
  side_effect_check_failed_ = false;
  DCHECK(temporary_objects_);
  isolate_->heap()->RemoveHeapObjectAllocationTracker(temporary_objects_.get());
  temporary_objects_.reset();
  isolate_->native_context()->set_regexp_last_match_info(*regexp_match_info_);
  regexp_match_info_ = Handle<RegExpMatchInfo>::null();
  // Update debug infos to have correct execution mode.
  UpdateDebugInfosForExecutionMode();
}
References v8::internal::Isolate::CancelTerminateExecution(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::Isolate::debug_execution_mode(), v8::internal::Isolate::factory(), v8::internal::Isolate::has_exception(), v8::internal::Isolate::heap(), v8::internal::Isolate::is_execution_terminating(), isolate_, v8::internal::DebugInfo::kBreakpoints, v8::internal::DebugInfo::kSideEffects, v8::internal::Isolate::native_context(), v8::internal::Handle< T >::null(), RCS_SCOPE, regexp_match_info_, v8::internal::Heap::RemoveHeapObjectAllocationTracker(), v8::internal::Isolate::set_debug_execution_mode(), side_effect_check_failed_, temporary_objects_, v8::internal::Isolate::Throw(), UpdateDebugInfosForExecutionMode(), UpdateHookOnFunctionCall(), and v8::internal::v8_flags.
Referenced by v8::debug::CallFunctionOn(), v8::internal::DebugEvaluate::Evaluate(), and v8::internal::DebugEvaluate::Global().
suspended_generator_address()
Address v8::internal::Debug::suspended_generator_address () [inline]
Definition at line 456 of file debug.h.
                                        {
    return reinterpret_cast<Address>(&thread_local_.suspended_generator_);
  }
Referenced by v8::internal::FUNCTION_REFERENCE_WITH_TYPE().
ThreadInit()
void v8::internal::Debug::ThreadInit () [private]
Definition at line 464 of file debug.cc.
                       {
  thread_local_.break_frame_id_ = StackFrameId::NO_ID;
  thread_local_.last_step_action_ = StepNone;
  thread_local_.last_statement_position_ = kNoSourcePosition;
  thread_local_.last_bytecode_offset_ = kFunctionEntryBytecodeOffset;
  thread_local_.last_frame_count_ = -1;
  thread_local_.fast_forward_to_return_ = false;
  thread_local_.ignore_step_into_function_ = Smi::zero();
  thread_local_.target_frame_count_ = -1;
  thread_local_.return_value_ = Smi::zero();
  thread_local_.last_breakpoint_id_ = 0;
  clear_restart_frame();
  clear_suspended_generator();
  base::Relaxed_Store(&thread_local_.current_debug_scope_,
                      static_cast<base::AtomicWord>(0));
  thread_local_.break_on_next_function_call_ = false;
  thread_local_.scheduled_break_on_next_function_call_ = false;
  UpdateHookOnFunctionCall();
  thread_local_.muted_function_ = Smi::zero();
  thread_local_.muted_position_ = -1;
}
References v8::internal::Debug::ThreadLocal::break_frame_id_, v8::internal::Debug::ThreadLocal::break_on_next_function_call_, clear_restart_frame(), clear_suspended_generator(), v8::internal::Debug::ThreadLocal::current_debug_scope_, v8::internal::Debug::ThreadLocal::fast_forward_to_return_, v8::internal::Debug::ThreadLocal::ignore_step_into_function_, v8::internal::kFunctionEntryBytecodeOffset, v8::internal::kNoSourcePosition, v8::internal::Debug::ThreadLocal::last_breakpoint_id_, v8::internal::Debug::ThreadLocal::last_bytecode_offset_, v8::internal::Debug::ThreadLocal::last_frame_count_, v8::internal::Debug::ThreadLocal::last_statement_position_, v8::internal::Debug::ThreadLocal::last_step_action_, v8::internal::Debug::ThreadLocal::muted_function_, v8::internal::Debug::ThreadLocal::muted_position_, v8::internal::NO_ID, v8::base::Relaxed_Store(), v8::internal::Debug::ThreadLocal::return_value_, v8::internal::Debug::ThreadLocal::scheduled_break_on_next_function_call_, v8::internal::StepNone, v8::internal::Debug::ThreadLocal::target_frame_count_, thread_local_, UpdateHookOnFunctionCall(), and v8::internal::Smi::zero().
Referenced by Debug().
TryGetDebugInfo()
std::optional< Tagged< DebugInfo > > v8::internal::Debug::TryGetDebugInfo (Tagged< SharedFunctionInfo > sfi)
Definition at line 2419 of file debug.cc.
                                    {
  return debug_infos_.Find(sfi);
}
References debug_infos_, and v8::internal::DebugInfoCollection::Find().
Referenced by Break(), BreakAtEntry(), v8::internal::Heap::InsertIntoRememberedSetFromCode::DebugGetCoverageInfo(), FindClosestSharedFunctionInfoFromPosition(), FloodWithOneShot(), v8::internal::SharedFunctionInfo::GetDebugInfo(), GetPossibleBreakpoints(), GetSourceBreakLocations(), HandleDebugBreak(), HasBreakInfo(), HasCoverageInfo(), HasDebugInfo(), IsBreakAtReturn(), v8::internal::anonymous_namespace{debug.cc}::IsJSFunctionAndNeedsTrampoline(), OnException(), PrepareFunctionForDebugExecution(), PrepareStep(), v8::debug::ResetBlackboxedStateCache(), SetBreakpoint(), and v8::internal::SharedFunctionInfo::TryGetDebugInfo().
Unload()
void v8::internal::Debug::Unload () [private]
Definition at line 615 of file debug.cc.
                   {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  ClearAllBreakPoints();
  ClearStepping();
  RemoveAllCoverageInfos();
  ClearAllDebuggerHints();
  debug_delegate_ = nullptr;
}
References ClearAllBreakPoints(), ClearAllDebuggerHints(), ClearStepping(), debug_delegate_, isolate_, RCS_SCOPE, and RemoveAllCoverageInfos().
Referenced by v8::internal::Isolate::Deinit(), and UpdateState().
UpdateDebugInfosForExecutionMode()
void v8::internal::Debug::UpdateDebugInfosForExecutionMode () [private]
Definition at line 3010 of file debug.cc.
                                             {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  // Walk all debug infos and update their execution mode if it is different
  // from the isolate execution mode.
  const DebugInfo::ExecutionMode current_debug_execution_mode =
      isolate_->debug_execution_mode();
  HandleScope scope(isolate_);
  DebugInfoCollection::Iterator it(&debug_infos_);
  for (; it.HasNext(); it.Advance()) {
    Handle<DebugInfo> debug_info(it.Next(), isolate_);
    if (debug_info->HasInstrumentedBytecodeArray() &&
        debug_info->DebugExecutionMode() != current_debug_execution_mode) {
      DCHECK(debug_info->shared()->HasBytecodeArray());
      if (current_debug_execution_mode == DebugInfo::kBreakpoints) {
        ClearSideEffectChecks(debug_info);
        ApplyBreakPoints(debug_info);
      } else {
        ClearBreakPoints(debug_info);
        ApplySideEffectChecks(debug_info);
      }
    }
  }
}
References v8::internal::DebugInfoCollection::Iterator::Advance(), ApplyBreakPoints(), ApplySideEffectChecks(), ClearBreakPoints(), ClearSideEffectChecks(), v8::internal::DCHECK(), v8::internal::Isolate::debug_execution_mode(), debug_infos_, v8::internal::DebugInfoCollection::Iterator::HasNext(), isolate_, v8::internal::DebugInfo::kBreakpoints, v8::internal::DebugInfoCollection::Iterator::Next(), and RCS_SCOPE.
Referenced by StartSideEffectCheckMode(), and StopSideEffectCheckMode().
UpdateHookOnFunctionCall()
void v8::internal::Debug::UpdateHookOnFunctionCall () [private]
Definition at line 2828 of file debug.cc.
                                     {
  static_assert(LastStepAction == StepInto);
  hook_on_function_call_ =
      thread_local_.last_step_action_ == StepInto ||
      isolate_->debug_execution_mode() == DebugInfo::kSideEffects ||
      thread_local_.break_on_next_function_call_;
}
References v8::internal::Debug::ThreadLocal::break_on_next_function_call_, v8::internal::Isolate::debug_execution_mode(), hook_on_function_call_, isolate_, v8::internal::DebugInfo::kSideEffects, v8::internal::Debug::ThreadLocal::last_step_action_, v8::internal::LastStepAction, v8::internal::StepInto, and thread_local_.
Referenced by ClearBreakOnNextFunctionCall(), ClearStepping(), PrepareStep(), PrepareStepInSuspendedGenerator(), SetBreakOnNextFunctionCall(), StartSideEffectCheckMode(), StopSideEffectCheckMode(), and ThreadInit().
UpdateState()
void v8::internal::Debug::UpdateState () [private]
Definition at line 2810 of file debug.cc.
                        {
  RCS_SCOPE(isolate_, RuntimeCallCounterId::kDebugger);
  bool is_active = debug_delegate_ != nullptr;
  if (is_active == is_active_) return;
  if (is_active) {
    // Note that the debug context could have already been loaded to
    // bootstrap test cases.
    isolate_->compilation_cache()->DisableScriptAndEval();
    isolate_->CollectSourcePositionsForAllBytecodeArrays();
    is_active = true;
  } else {
    isolate_->compilation_cache()->EnableScriptAndEval();
    Unload();
  }
  is_active_ = is_active;
  isolate_->PromiseHookStateUpdated();
}
References v8::internal::Isolate::CollectSourcePositionsForAllBytecodeArrays(), v8::internal::Isolate::compilation_cache(), debug_delegate_, v8::internal::CompilationCache::DisableScriptAndEval(), v8::internal::CompilationCache::EnableScriptAndEval(), is_active(), is_active_, isolate_, v8::internal::Isolate::PromiseHookStateUpdated(), RCS_SCOPE, and Unload().
Referenced by v8::internal::DebugScope::DebugScope(), SetDebugDelegate(), and v8::internal::DebugScope::~DebugScope().
Friends And Related Function Documentation
CheckDebuggerUnloaded
void CheckDebuggerUnloaded () [friend]
DebugScope
friend class DebugScope [friend]
Definition at line 727 of file debug.h.
DisableBreak
friend class DisableBreak [friend]
Definition at line 728 of file debug.h.
DisableTemporaryObjectTracking
friend class DisableTemporaryObjectTracking [friend]
Definition at line 729 of file debug.h.
GetDebuggedFunctions
DirectHandle<FixedArray> GetDebuggedFunctions () [friend]
Isolate
friend class Isolate [friend]
Definition at line 726 of file debug.h.
LiveEdit
friend class LiveEdit [friend]
Definition at line 730 of file debug.h.
SuppressDebug
friend class SuppressDebug [friend]
Definition at line 731 of file debug.h.
Member Data Documentation
break_disabled_
bool v8::internal::Debug::break_disabled_ [private]
Definition at line 611 of file debug.h.
Referenced by v8::internal::DisableBreak::DisableBreak(), and v8::internal::DisableBreak::~DisableBreak().
break_on_caught_exception_
bool v8::internal::Debug::break_on_caught_exception_ [private]
Definition at line 615 of file debug.h.
Referenced by ChangeBreakOnException(), IsBreakOnException(), and OnException().
break_on_uncaught_exception_
bool v8::internal::Debug::break_on_uncaught_exception_ [private]
Definition at line 617 of file debug.h.
Referenced by ChangeBreakOnException(), IsBreakOnException(), and OnException().
break_points_active_
bool v8::internal::Debug::break_points_active_ [private]
Definition at line 613 of file debug.h.
Referenced by CheckBreakPoints(), and IsBreakOnInstrumentation().
debug_delegate_
debug::DebugDelegate* v8::internal::Debug::debug_delegate_ = nullptr [private]
Definition at line 597 of file debug.h.
Referenced by CheckBreakPoint(), IsBlackboxed(), IsFunctionBlackboxed(), OnDebugBreak(), OnException(), OnInstrumentationBreak(), ProcessCompileEvent(), SetDebugDelegate(), ShouldBeSkipped(), Unload(), UpdateState(), and ~Debug().
debug_infos_
DebugInfoCollection v8::internal::Debug::debug_infos_ [private]
Definition at line 622 of file debug.h.
Referenced by ClearAllDebugInfos(), ClearBreakPoint(), ClearOneShot(), GetOrCreateDebugInfo(), InstallDebugBreakTrampoline(), RemoveBreakInfoAndMaybeFree(), TryGetDebugInfo(), and UpdateDebugInfosForExecutionMode().
hook_on_function_call_
bool v8::internal::Debug::hook_on_function_call_ [private]
Definition at line 605 of file debug.h.
Referenced by UpdateHookOnFunctionCall().
ignore_side_effects_for_function_template_info_
IndirectHandle<FunctionTemplateInfo> v8::internal::Debug::ignore_side_effects_for_function_template_info_ [private]
Definition at line 717 of file debug.h.
Referenced by IgnoreSideEffectsOnNextCallTo(), and PerformSideEffectCheckForCallback().
is_active_
std::atomic<bool> v8::internal::Debug::is_active_ [private]
Definition at line 602 of file debug.h.
Referenced by UpdateState().
is_suppressed_
bool v8::internal::Debug::is_suppressed_ [private]
Definition at line 607 of file debug.h.
Referenced by v8::internal::SuppressDebug::SuppressDebug(), and v8::internal::SuppressDebug::~SuppressDebug().
isolate_
Isolate* v8::internal::Debug::isolate_ [private]
Definition at line 719 of file debug.h.
Referenced by AllFramesOnStackAreBlackboxed(), ApplyBreakPoints(), ApplySideEffectChecks(), Break(), CanBreakAtEntry(), CheckBreakPoint(), CheckBreakPoints(), CheckBreakPointsForLocations(), ClearAllBreakPoints(), ClearAllDebugInfos(), ClearBreakPoint(), ClearBreakPoints(), ClearOneShot(), ClearSideEffectChecks(), ClearStepping(), CreateBreakInfo(), CurrentFrameCount(), DeoptimizeFunction(), DiscardAllBaselineCode(), DiscardBaselineCode(), EnsureBreakInfo(), FindBreakablePosition(), FindClosestSharedFunctionInfoFromPosition(), FindInnermostContainingFunctionInfo(), FindSharedFunctionInfosIntersectingRange(), FloodWithOneShot(), GetFunctionDebuggingId(), GetHitBreakPoints(), GetLoadedScripts(), GetOrCreateDebugInfo(), GetPossibleBreakpoints(), GetTopLevelWithRecompile(), HandleDebugBreak(), InstallCoverageInfo(), InstallDebugBreakTrampoline(), IsBlackboxed(), IsBreakAtReturn(), IsBreakOnDebuggerStatement(), IsBreakOnInstrumentation(), IsFrameBlackboxed(), NotifyDebuggerPausedEventSent(), OnDebugBreak(), OnException(), OnInstrumentationBreak(), OnPromiseReject(), OnThrow(), PerformSideEffectCheck(), PerformSideEffectCheckAtBytecode(), PerformSideEffectCheckForAccessor(), PerformSideEffectCheckForCallback(), PerformSideEffectCheckForInterceptor(), PerformSideEffectCheckForObject(), PrepareBuiltinForSideEffectCheck(), PrepareFunctionForDebugExecution(), PrepareStep(), PrepareStepIn(), PrepareStepInSuspendedGenerator(), PrepareStepOnThrow(), ProcessCompileEvent(), RemoveAllCoverageInfos(), RemoveBreakInfoAndMaybeFree(), RemoveBreakpoint(), RestoreDebug(), return_value_handle(), SetBreakpoint(), SetBreakpointForFunction(), SetBreakPointForScript(), SetScriptSource(), SetTerminateOnResume(), ShouldBeSkipped(), StartSideEffectCheckMode(), StopSideEffectCheckMode(), Unload(), UpdateDebugInfosForExecutionMode(), UpdateHookOnFunctionCall(), UpdateState(), and v8::internal::DebugScope::~DebugScope().
isolate_id_
uint64_t v8::internal::Debug::isolate_id_ [private]
Definition at line 724 of file debug.h.
kBreakAtEntryPosition
const int v8::internal::Debug::kBreakAtEntryPosition = 0 [static]
Definition at line 487 of file debug.h.
Referenced by FindBreakablePosition(), v8::internal::BreakLocation::FromFrame(), and v8::internal::BreakLocation::HasBreakPoint().
kInstrumentationId
const int v8::internal::Debug::kInstrumentationId = -1 [static]
Definition at line 490 of file debug.h.
Referenced by CheckBreakPoint(), v8::internal::WasmScript::ClearBreakPoint(), GetHitBreakPoints(), IsBreakOnInstrumentation(), OnInstrumentationBreak(), and SetBreakpointForFunction().
regexp_match_info_
IndirectHandle<RegExpMatchInfo> v8::internal::Debug::regexp_match_info_ [private]
Definition at line 628 of file debug.h.
Referenced by StartSideEffectCheckMode(), and StopSideEffectCheckMode().
running_live_edit_
bool v8::internal::Debug::running_live_edit_ = false [private]
Definition at line 609 of file debug.h.
Referenced by ProcessCompileEvent(), and SetScriptSource().
side_effect_check_failed_
bool v8::internal::Debug::side_effect_check_failed_ [private]
Definition at line 619 of file debug.h.
Referenced by PerformSideEffectCheck(), PerformSideEffectCheckAtBytecode(), PerformSideEffectCheckForAccessor(), PerformSideEffectCheckForCallback(), PerformSideEffectCheckForInterceptor(), PerformSideEffectCheckForObject(), StartSideEffectCheckMode(), and StopSideEffectCheckMode().
temporary_objects_
std::unique_ptr<TemporaryObjectsTracker> v8::internal::Debug::temporary_objects_ [private]
Definition at line 626 of file debug.h.
Referenced by GetTemporaryObjectTrackingDisabled(), PerformSideEffectCheckForObject(), SetTemporaryObjectTrackingDisabled(), StartSideEffectCheckMode(), and StopSideEffectCheckMode().
thread_local_
ThreadLocal v8::internal::Debug::thread_local_ [private]
Definition at line 705 of file debug.h.
Referenced by ArchiveDebug(), Break(), ClearBreakOnNextFunctionCall(), ClearMutedLocation(), ClearStepping(), v8::internal::DebugScope::DebugScope(), HandleDebugBreak(), IsMutedAtAnyBreakLocation(), Iterate(), NotifyDebuggerPausedEventSent(), PrepareRestartFrame(), PrepareStep(), PrepareStepIn(), PrepareStepInSuspendedGenerator(), PrepareStepOnThrow(), RestoreDebug(), return_value_handle(), SetBreakOnNextFunctionCall(), SetBreakpointForFunction(), SetBreakPointForScript(), SetMutedLocation(), SetTerminateOnResume(), ThreadInit(), UpdateHookOnFunctionCall(), and v8::internal::DebugScope::~DebugScope().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/debug/debug.h
/mnt/V8SourceCode/src/debug/debug.cc