v8::internal::compiler::ReduceScope Class Reference
Public Types
using Reduction = EffectGraphReducer::Reduction
Public Member Functions
ReduceScope (Node *node, Reduction *reduction)
void SetValueChanged ()
Protected Member Functions
Node * current_node () const
Reduction * reduction ()
Private Attributes
Node * current_node_
Reduction * reduction_
Detailed Description
Definition at line 73 of file escape-analysis.cc.
Member Typedef Documentation
Reduction
using v8::internal::compiler::ReduceScope::Reduction = EffectGraphReducer::Reduction
Definition at line 75 of file escape-analysis.cc.
Constructor & Destructor Documentation
ReduceScope()
v8::internal::compiler::ReduceScope::ReduceScope (Node * node, Reduction * reduction) [inline], [explicit]
Definition at line 76 of file escape-analysis.cc.
      : current_node_(node), reduction_(reduction) {}
Member Function Documentation
current_node()
Node* v8::internal::compiler::ReduceScope::current_node () const [inline], [protected]
Definition at line 82 of file escape-analysis.cc.
{ return current_node_; }
References current_node_.
reduction()
Reduction* v8::internal::compiler::ReduceScope::reduction () [inline], [protected]
Definition at line 83 of file escape-analysis.cc.
{ return reduction_; }
References reduction_.
Referenced by SetValueChanged().
SetValueChanged()
void v8::internal::compiler::ReduceScope::SetValueChanged () [inline]
Definition at line 79 of file escape-analysis.cc.
{ reduction()->set_value_changed(); }
References reduction(), and v8::internal::compiler::EffectGraphReducer::Reduction::set_value_changed().
Referenced by v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode().
Member Data Documentation
current_node_
Node* v8::internal::compiler::ReduceScope::current_node_ [private]
Definition at line 86 of file escape-analysis.cc.
Referenced by current_node().
reduction_
Reduction* v8::internal::compiler::ReduceScope::reduction_ [private]
Definition at line 87 of file escape-analysis.cc.
Referenced by reduction().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/escape-analysis.cc