v8::internal::AsmWasmData Class Reference
#include <wasm-objects.h>
Public Types
using BodyDescriptor = StructBodyDescriptor
Static Public Member Functions
static Handle< AsmWasmData > New (Isolate *isolate, std::shared_ptr< wasm::NativeModule > native_module, DirectHandle< HeapNumber > uses_bitset)
Detailed Description
Definition at line 1365 of file wasm-objects.h.
Member Typedef Documentation
BodyDescriptor
using v8::internal::AsmWasmData::BodyDescriptor = StructBodyDescriptor
Definition at line 1373 of file wasm-objects.h.
Member Function Documentation
New()
Handle< AsmWasmData > v8::internal::AsmWasmData::New (Isolate * isolate, std::shared_ptr< wasm::NativeModule > native_module, DirectHandle< HeapNumber > uses_bitset) [static]
Definition at line 3313 of file wasm-objects.cc.
                                          {
  const WasmModule* module = native_module->module();
  size_t memory_estimate =
      wasm::WasmCodeManager::EstimateNativeModuleCodeSize(module) +
      wasm::WasmCodeManager::EstimateNativeModuleMetaDataSize(module);
  DirectHandle<Managed<wasm::NativeModule>> managed_native_module =
      Managed<wasm::NativeModule>::From(isolate, memory_estimate,
                                        std::move(native_module));
  auto result = Cast<AsmWasmData>(
      isolate->factory()->NewStruct(ASM_WASM_DATA_TYPE, AllocationType::kOld));
  result->set_managed_native_module(*managed_native_module);
  result->set_uses_bitset(*uses_bitset);
  return result;
}
References v8::internal::wasm::WasmCodeManager::EstimateNativeModuleCodeSize(), v8::internal::wasm::WasmCodeManager::EstimateNativeModuleMetaDataSize(), v8::internal::Isolate::factory(), v8::internal::Managed< CppType >::From(), v8::internal::kOld, v8::internal::FactoryBase< Impl >::NewStruct(), and v8::base::internal::result.
Referenced by v8::internal::wasm::WasmEngine::SyncCompileTranslatedAsmJs().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-objects.h
/mnt/V8SourceCode/src/wasm/wasm-objects.cc