v8::internal::IndirectPointerSlot Class Reference
#include <slots.h>
Public Types
enum TagCheckStrictness { kRequireExactMatch
, kAllowUnpublishedEntries
 }
Public Member Functions
IndirectPointerSlot ()
IndirectPointerSlot (Address ptr, IndirectPointerTag tag)
Tagged< Object > load (IsolateForSandbox isolate) const
void store (Tagged< ExposedTrustedObject > value) const
Tagged< Object > Relaxed_Load (IsolateForSandbox isolate) const
Tagged< Object > Relaxed_Load_AllowUnpublished (IsolateForSandbox isolate) const
Tagged< Object > Acquire_Load (IsolateForSandbox isolate) const
void Relaxed_Store (Tagged< ExposedTrustedObject > value) const
void Release_Store (Tagged< ExposedTrustedObject > value) const
IndirectPointerHandle Relaxed_LoadHandle () const
IndirectPointerHandle Acquire_LoadHandle () const
void Relaxed_StoreHandle (IndirectPointerHandle handle) const
void Release_StoreHandle (IndirectPointerHandle handle) const
IndirectPointerTag tag () const
bool IsEmpty () const
template<TagCheckStrictness allow_unpublished = kRequireExactMatch>
Tagged< Object > ResolveHandle (IndirectPointerHandle handle, IsolateForSandbox isolate) const
Additional Inherited Members
Detailed Description
Definition at line 478 of file slots.h.
Member Enumeration Documentation
TagCheckStrictness
enum v8::internal::IndirectPointerSlot::TagCheckStrictness
Enumerator
kRequireExactMatch
kAllowUnpublishedEntries
Definition at line 539 of file slots.h.
{ kRequireExactMatch, kAllowUnpublishedEntries };
Constructor & Destructor Documentation
IndirectPointerSlot() [1/2]
v8::internal::IndirectPointerSlot::IndirectPointerSlot () [inline]
Definition at line 482 of file slots.h.
      : SlotBase(kNullAddress)
#ifdef V8_ENABLE_SANDBOX
        ,
        tag_(kIndirectPointerNullTag)
#endif
  {
  }
IndirectPointerSlot() [2/2]
v8::internal::IndirectPointerSlot::IndirectPointerSlot (Address ptr, IndirectPointerTag tag) [inline], [explicit]
Definition at line 491 of file slots.h.
      : SlotBase(ptr)
#ifdef V8_ENABLE_SANDBOX
        ,
        tag_(tag)
#endif
  {
  }
Member Function Documentation
Acquire_Load()
Tagged< Object > v8::internal::IndirectPointerSlot::Acquire_Load (IsolateForSandbox isolate) const [inline]
Definition at line 380 of file slots-inl.h.
                                     {
  IndirectPointerHandle handle = Acquire_LoadHandle();
  return ResolveHandle(handle, isolate);
}
References Acquire_LoadHandle(), v8::internal::handle(), and ResolveHandle().
Acquire_LoadHandle()
IndirectPointerHandle v8::internal::IndirectPointerSlot::Acquire_LoadHandle () const [inline]
Definition at line 413 of file slots-inl.h.
                                                                    {
  return base::AsAtomic32::Acquire_Load(location());
}
References v8::base::AsAtomicImpl< TAtomicStorageType >::Acquire_Load(), and v8::internal::SlotBase< IndirectPointerSlot, IndirectPointerHandle, kTaggedSize >::location().
Referenced by Acquire_Load().
IsEmpty()
bool v8::internal::IndirectPointerSlot::IsEmpty () const [inline]
Definition at line 427 of file slots-inl.h.
                                        {
  return Relaxed_LoadHandle() == kNullIndirectPointerHandle;
}
References v8::internal::kNullIndirectPointerHandle, and Relaxed_LoadHandle().
Referenced by v8::internal::Serializer::ObjectSerializer::VisitIndirectPointer().
load()
Tagged< Object > v8::internal::IndirectPointerSlot::load (IsolateForSandbox isolate) const [inline]
Definition at line 360 of file slots-inl.h.
                                                                        {
  return Relaxed_Load(isolate);
}
References Relaxed_Load().
Referenced by v8::internal::WriteBarrier::IndirectPointerMarkingFromCode(), v8::internal::Serializer::ObjectSerializer::VisitIndirectPointer(), and v8::internal::MarkingBarrier::Write().
Relaxed_Load()
Tagged< Object > v8::internal::IndirectPointerSlot::Relaxed_Load (IsolateForSandbox isolate) const [inline]
Definition at line 368 of file slots-inl.h.
                                     {
  IndirectPointerHandle handle = Relaxed_LoadHandle();
  return ResolveHandle(handle, isolate);
}
References v8::internal::handle(), Relaxed_LoadHandle(), and ResolveHandle().
Referenced by load().
Relaxed_Load_AllowUnpublished()
Tagged< Object > v8::internal::IndirectPointerSlot::Relaxed_Load_AllowUnpublished (IsolateForSandbox isolate) const [inline]
Definition at line 374 of file slots-inl.h.
                                     {
  IndirectPointerHandle handle = Relaxed_LoadHandle();
  return ResolveHandle<kAllowUnpublishedEntries>(handle, isolate);
}
References v8::internal::handle(), and Relaxed_LoadHandle().
Referenced by v8::internal::FullMarkingVisitorBase< ConcurrentMarkingVisitor >::MarkPointerTableEntry().
Relaxed_LoadHandle()
IndirectPointerHandle v8::internal::IndirectPointerSlot::Relaxed_LoadHandle () const [inline]
Definition at line 409 of file slots-inl.h.
                                                                    {
  return base::AsAtomic32::Relaxed_Load(location());
}
References v8::internal::SlotBase< IndirectPointerSlot, IndirectPointerHandle, kTaggedSize >::location(), and v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Load().
Referenced by v8::internal::MarkCompactCollector::FlushBytecodeFromSFI(), IsEmpty(), v8::internal::FullMarkingVisitorBase< ConcreteVisitor >::MarkPointerTableEntry(), Relaxed_Load(), and Relaxed_Load_AllowUnpublished().
Relaxed_Store()
void v8::internal::IndirectPointerSlot::Relaxed_Store (Tagged< ExposedTrustedObject > value) const [inline]
Definition at line 386 of file slots-inl.h.
                                              {
#ifdef V8_ENABLE_SANDBOX
  IndirectPointerHandle handle = value->ReadField<IndirectPointerHandle>(
      ExposedTrustedObject::kSelfIndirectPointerOffset);
  DCHECK_NE(handle, kNullIndirectPointerHandle);
  Relaxed_StoreHandle(handle);
#else
  UNREACHABLE();
#endif // V8_ENABLE_SANDBOX
}
References DCHECK_NE, v8::internal::handle(), v8::internal::kNullIndirectPointerHandle, Relaxed_StoreHandle(), v8::internal::UNREACHABLE(), and v8::internal::value.
Referenced by store().
Relaxed_StoreHandle()
void v8::internal::IndirectPointerSlot::Relaxed_StoreHandle (IndirectPointerHandle handle) const [inline]
Definition at line 417 of file slots-inl.h.
                                        {
  return base::AsAtomic32::Relaxed_Store(location(), handle);
}
References v8::internal::handle(), v8::internal::SlotBase< IndirectPointerSlot, IndirectPointerHandle, kTaggedSize >::location(), and v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Store().
Referenced by Relaxed_Store().
Release_Store()
void v8::internal::IndirectPointerSlot::Release_Store (Tagged< ExposedTrustedObject > value) const [inline]
Definition at line 398 of file slots-inl.h.
                                              {
#ifdef V8_ENABLE_SANDBOX
  IndirectPointerHandle handle = value->ReadField<IndirectPointerHandle>(
      ExposedTrustedObject::kSelfIndirectPointerOffset);
  Release_StoreHandle(handle);
#else
  UNREACHABLE();
#endif // V8_ENABLE_SANDBOX
}
References v8::internal::handle(), Release_StoreHandle(), v8::internal::UNREACHABLE(), and v8::internal::value.
Release_StoreHandle()
void v8::internal::IndirectPointerSlot::Release_StoreHandle (IndirectPointerHandle handle) const [inline]
Definition at line 422 of file slots-inl.h.
                                        {
  return base::AsAtomic32::Release_Store(location(), handle);
}
References v8::internal::handle(), v8::internal::SlotBase< IndirectPointerSlot, IndirectPointerHandle, kTaggedSize >::location(), and v8::base::AsAtomicImpl< TAtomicStorageType >::Release_Store().
Referenced by Release_Store().
ResolveHandle()
template<IndirectPointerSlot::TagCheckStrictness allow_unpublished>
Tagged< Object > v8::internal::IndirectPointerSlot::ResolveHandle (IndirectPointerHandle handle, IsolateForSandbox isolate) const [inline]
Definition at line 432 of file slots-inl.h.
                                                                   {
#ifdef V8_ENABLE_SANDBOX
  // TODO(saelo) Maybe come up with a different entry encoding scheme that
  // returns Smi::zero for kNullCodePointerHandle?
  if (!handle) return Smi::zero();
  // Resolve the handle. The tag implies the pointer table to use.
  if (tag_ == kUnknownIndirectPointerTag) {
    // In this case we have to rely on the handle marking to determine which
    // pointer table to use.
    if (handle & kCodePointerHandleMarker) {
      return ResolveCodePointerHandle(handle);
    } else {
      return ResolveTrustedPointerHandle<allow_unpublished>(handle, isolate);
    }
  } else if (tag_ == kCodeIndirectPointerTag) {
    return ResolveCodePointerHandle(handle);
  } else {
    return ResolveTrustedPointerHandle<allow_unpublished>(handle, isolate);
  }
#else
  UNREACHABLE();
#endif // V8_ENABLE_SANDBOX
}
References v8::internal::handle(), v8::internal::kCodePointerHandleMarker, v8::internal::kUnknownIndirectPointerTag, v8::internal::UNREACHABLE(), and v8::internal::Smi::zero().
Referenced by Acquire_Load(), and Relaxed_Load().
store()
void v8::internal::IndirectPointerSlot::store (Tagged< ExposedTrustedObject > value) const [inline]
Definition at line 364 of file slots-inl.h.
                                                                        {
  return Relaxed_Store(value);
}
References Relaxed_Store(), and v8::internal::value.
Referenced by v8::internal::SlotAccessorForHeapObject::WriteIndirectPointerTo().
tag()
IndirectPointerTag v8::internal::IndirectPointerSlot::tag () const [inline]
Definition at line 527 of file slots.h.
{ return kIndirectPointerNullTag; }
References v8::internal::kIndirectPointerNullTag.
Referenced by v8::internal::FullMarkingVisitorBase< ConcreteVisitor >::MarkPointerTableEntry().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/slots.h
/mnt/V8SourceCode/src/objects/slots-inl.h