v8::internal::compiler::MemoryLowering::AllocationState Class Reference
#include <memory-lowering.h>
Public Member Functions
AllocationState (const AllocationState &)=delete
AllocationState & operator= (const AllocationState &)=delete
bool IsYoungGenerationAllocation () const
AllocationGroup * group () const
Node * top () const
Node * effect () const
intptr_t size () const
Static Public Member Functions
static AllocationState const * Empty (Zone *zone)
static AllocationState const * Closed (AllocationGroup *group, Node *effect, Zone *zone)
static AllocationState const * Open (AllocationGroup *group, intptr_t size, Node *top, Node *effect, Zone *zone)
Private Member Functions
AllocationState ()
AllocationState (AllocationGroup *group, Node *effect)
AllocationState (AllocationGroup *group, intptr_t size, Node *top, Node *effect)
Private Attributes
friend Zone
AllocationGroup *const group_
intptr_t const size_
Node *const top_
Node *const effect_
Detailed Description
Definition at line 33 of file memory-lowering.h.
Constructor & Destructor Documentation
AllocationState() [1/4]
v8::internal::compiler::MemoryLowering::AllocationState::AllocationState (const AllocationState &) [delete]
AllocationState() [2/4]
v8::internal::compiler::MemoryLowering::AllocationState::AllocationState () [private]
Definition at line 766 of file memory-lowering.cc.
    : group_(nullptr),
      size_(std::numeric_limits<int>::max()),
      top_(nullptr),
      effect_(nullptr) {}
AllocationState() [3/4]
v8::internal::compiler::MemoryLowering::AllocationState::AllocationState (AllocationGroup * group, Node * effect) [explicit], [private]
Definition at line 772 of file memory-lowering.cc.
    : group_(group),
      size_(std::numeric_limits<int>::max()),
      top_(nullptr),
      effect_(effect) {}
AllocationState() [4/4]
v8::internal::compiler::MemoryLowering::AllocationState::AllocationState (AllocationGroup * group, intptr_t size, Node * top, Node * effect) [private]
Definition at line 779 of file memory-lowering.cc.
    : group_(group), size_(size), top_(top), effect_(effect) {}
Member Function Documentation
Closed()
static AllocationState const* v8::internal::compiler::MemoryLowering::AllocationState::Closed (AllocationGroup * group, Node * effect, Zone * zone) [inline], [static]
Definition at line 41 of file memory-lowering.h.
                                                     {
      return zone->New<AllocationState>(group, effect);
    }
References effect(), group(), v8::internal::Zone::New(), and v8::internal::compiler::MemoryLowering::zone().
Referenced by v8::internal::compiler::MemoryOptimizer::MergeStates(), and v8::internal::compiler::MemoryLowering::ReduceAllocateRaw().
effect()
Node* v8::internal::compiler::MemoryLowering::AllocationState::effect () const [inline]
Definition at line 54 of file memory-lowering.h.
{ return effect_; }
References effect_.
Referenced by Closed(), Open(), and v8::internal::compiler::MemoryOptimizer::VisitAllocateRaw().
Empty()
static AllocationState const* v8::internal::compiler::MemoryLowering::AllocationState::Empty (Zone * zone) [inline], [static]
Definition at line 38 of file memory-lowering.h.
                                                    {
      return zone->New<AllocationState>();
    }
References v8::internal::Zone::New(), and v8::internal::compiler::MemoryLowering::zone().
group()
AllocationGroup* v8::internal::compiler::MemoryLowering::AllocationState::group () const [inline]
Definition at line 52 of file memory-lowering.h.
{ return group_; }
References group_.
Referenced by Closed(), v8::internal::compiler::MemoryLowering::ComputeWriteBarrierKind(), v8::internal::compiler::MemoryOptimizer::MergeStates(), Open(), and v8::internal::compiler::MemoryLowering::ReduceAllocateRaw().
IsYoungGenerationAllocation()
bool v8::internal::compiler::MemoryLowering::AllocationState::IsYoungGenerationAllocation () const
Definition at line 784 of file memory-lowering.cc.
                                                                      {
  return group() && group()->IsYoungGenerationAllocation();
}
Referenced by v8::internal::compiler::MemoryLowering::ComputeWriteBarrierKind().
Open()
static AllocationState const* v8::internal::compiler::MemoryLowering::AllocationState::Open (AllocationGroup * group, intptr_t size, Node * top, Node * effect, Zone * zone) [inline], [static]
Definition at line 45 of file memory-lowering.h.
                                                                            {
      return zone->New<AllocationState>(group, size, top, effect);
    }
References effect(), group(), v8::internal::Zone::New(), size(), top(), and v8::internal::compiler::MemoryLowering::zone().
Referenced by v8::internal::compiler::MemoryLowering::ReduceAllocateRaw().
operator=()
AllocationState& v8::internal::compiler::MemoryLowering::AllocationState::operator= (const AllocationState &) [delete]
size()
intptr_t v8::internal::compiler::MemoryLowering::AllocationState::size () const [inline]
Definition at line 55 of file memory-lowering.h.
{ return size_; }
References size_.
Referenced by Open(), and v8::internal::compiler::MemoryLowering::ReduceAllocateRaw().
top()
Node* v8::internal::compiler::MemoryLowering::AllocationState::top () const [inline]
Definition at line 53 of file memory-lowering.h.
{ return top_; }
References top_.
Referenced by Open(), and v8::internal::compiler::MemoryLowering::ReduceAllocateRaw().
Member Data Documentation
effect_
Node* const v8::internal::compiler::MemoryLowering::AllocationState::effect_ [private]
Definition at line 70 of file memory-lowering.h.
Referenced by effect().
group_
AllocationGroup* const v8::internal::compiler::MemoryLowering::AllocationState::group_ [private]
Definition at line 65 of file memory-lowering.h.
Referenced by group().
size_
intptr_t const v8::internal::compiler::MemoryLowering::AllocationState::size_ [private]
Definition at line 68 of file memory-lowering.h.
Referenced by size().
top_
Node* const v8::internal::compiler::MemoryLowering::AllocationState::top_ [private]
Definition at line 69 of file memory-lowering.h.
Referenced by top().
Zone
friend v8::internal::compiler::MemoryLowering::AllocationState::Zone [private]
Definition at line 58 of file memory-lowering.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/memory-lowering.h
/mnt/V8SourceCode/src/compiler/memory-lowering.cc