v8::internal::LogFile::MessageBuilder Class Reference
#include <log-file.h>
Public Member Functions
~MessageBuilder ()=default
void AppendString (Tagged< String > str, std::optional< int > length_limit=std::nullopt)
void AppendString (base::Vector< const char > str)
void AppendString (const char *str)
void AppendString (const char *str, size_t length, bool is_one_byte=true)
void PRINTF_FORMAT (2, 3) AppendFormatString(const char *format
void void AppendCharacter (char c)
void AppendTwoByteCharacter (char c1, char c2)
void AppendSymbolName (Tagged< Symbol > symbol)
template<typename T >
MessageBuilder & operator<< (T value)
void WriteToLogFile ()
Private Member Functions
MessageBuilder (LogFile *log)
int PRINTF_FORMAT (2, 0) FormatStringIntoBuffer(const char *format
void AppendSymbolNameDetails (Tagged< String > str, bool show_impl_info)
void PRINTF_FORMAT (2, 3) AppendRawFormatString(const char *format
void void AppendRawString (const char *format)
void AppendRawCharacter (const char character)
Private Attributes
int va_list args
LogFile * log_
NoGarbageCollectionMutexGuard lock_guard_
Friends
class LogFile
Detailed Description
Definition at line 60 of file log-file.h.
Constructor & Destructor Documentation
 MessageBuilder()
v8::internal::LogFile::MessageBuilder::~MessageBuilder () [default]
MessageBuilder()
v8::internal::LogFile::MessageBuilder::MessageBuilder (LogFile * log) [explicit], [private]
Definition at line 109 of file log-file.cc.
    : log_(log), lock_guard_(&log_->mutex_) {}
Member Function Documentation
AppendCharacter()
void v8::internal::LogFile::MessageBuilder::AppendCharacter (char c)
Definition at line 175 of file log-file.cc.
                                                  {
  if (std::isprint(c)) {
    if (c == ',') {
      // Escape commas to avoid adding column separators.
      AppendRawString("\\x2C");
    } else if (c == '\\') {
      AppendRawString("\\\\");
    } else {
      // Safe, printable ascii character.
      AppendRawCharacter(c);
    }
  } else if (c == '\n') {
    // Escape newlines to avoid adding row separators.
    AppendRawString("\\n");
  } else {
    // Escape non-printable characters.
    AppendRawFormatString("\\x%02x", c & 0xFF);
  }
}
AppendRawCharacter()
void v8::internal::LogFile::MessageBuilder::AppendRawCharacter (const char character) [private]
Definition at line 251 of file log-file.cc.
{ log_->os_ << c; }
AppendRawString()
void v8::internal::LogFile::MessageBuilder::AppendRawString (const char * format) [private]
Definition at line 247 of file log-file.cc.
                                                           {
  log_->os_ << str;
}
AppendString() [1/4]
void v8::internal::LogFile::MessageBuilder::AppendString (base::Vector< const char > str)
Definition at line 131 of file log-file.cc.
                                                                   {
  for (auto i = str.begin(); i < str.end(); i++) AppendCharacter(*i);
}
References v8::base::Vector< T >::begin(), and v8::base::Vector< T >::end().
AppendString() [2/4]
void v8::internal::LogFile::MessageBuilder::AppendString (const char * str)
Definition at line 135 of file log-file.cc.
                                                        {
  if (str == nullptr) return;
  AppendString(str, strlen(str));
}
AppendString() [3/4]
void v8::internal::LogFile::MessageBuilder::AppendString (const char * str, size_t length, bool is_one_byte = true)
Definition at line 140 of file log-file.cc.
                                                             {
  if (str == nullptr) return;
  if (is_one_byte) {
    for (size_t i = 0; i < length; i++) {
      DCHECK_IMPLIES(is_one_byte, str[i] != '\0');
      AppendCharacter(str[i]);
    }
  } else {
    DCHECK_EQ(length % 2, 0);
    for (size_t i = 0; i + 1 < length; i += 2) {
      AppendTwoByteCharacter(str[i], str[i + 1]);
    }
  }
}
References DCHECK_EQ, DCHECK_IMPLIES, and v8::internal::length.
AppendString() [4/4]
void v8::internal::LogFile::MessageBuilder::AppendString (Tagged< String > str, std::optional< int > length_limit = std::nullopt)
Definition at line 112 of file log-file.cc.
                                                                          {
  if (str.is_null()) return;
  DisallowGarbageCollection no_gc; // Ensure string stays valid.
  SharedStringAccessGuardIfNeeded access_guard(str);
  int length = str->length();
  if (length_limit) length = std::min(length, *length_limit);
  for (int i = 0; i < length; i++) {
    uint16_t c = str->Get(i, access_guard);
    if (c <= 0xFF) {
      AppendCharacter(static_cast<char>(c));
    } else {
      // Escape non-ascii characters.
      AppendRawFormatString("\\u%04x", c & 0xFFFF);
    }
  }
}
References v8::internal::Tagged< HeapObject >::is_null(), v8::internal::length, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
AppendSymbolName()
void v8::internal::LogFile::MessageBuilder::AppendSymbolName (Tagged< Symbol > symbol)
Definition at line 195 of file log-file.cc.
                                                                  {
  DCHECK(!symbol.is_null());
  OFStream& os = log_->os_;
  os << "symbol(";
  if (!IsUndefined(symbol->description())) {
    os << "\"";
    AppendSymbolNameDetails(Cast<String>(symbol->description()), false);
    os << "\" ";
  }
  os << "hash " << std::hex << symbol->hash() << std::dec << ")";
}
References v8::internal::DCHECK(), and v8::internal::Tagged< HeapObject >::is_null().
AppendSymbolNameDetails()
void v8::internal::LogFile::MessageBuilder::AppendSymbolNameDetails (Tagged< String > str, bool show_impl_info) [private]
Definition at line 207 of file log-file.cc.
                                                                           {
  if (str.is_null()) return;
  DisallowGarbageCollection no_gc; // Ensure string stays valid.
  OFStream& os = log_->os_;
  int limit = str->length();
  if (limit > 0x1000) limit = 0x1000;
  if (show_impl_info) {
    os << (str->IsOneByteRepresentation() ? 'a' : '2');
    if (StringShape(str).IsExternal()) os << 'e';
    if (StringShape(str).IsInternalized()) os << '#';
    os << ':' << str->length() << ':';
  }
  AppendString(str, limit);
}
References v8::internal::Tagged< HeapObject >::is_null(), v8::internal::StringShape::IsExternal(), v8::internal::StringShape::IsInternalized(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
AppendTwoByteCharacter()
void v8::internal::LogFile::MessageBuilder::AppendTwoByteCharacter (char c1, char c2)
Definition at line 167 of file log-file.cc.
                                                                   {
  if (c2 == 0) {
    AppendCharacter(c1);
  } else {
    // Escape non-printable characters.
    AppendRawFormatString("\\u%02x%02x", c1 & 0xFF, c2 & 0xFF);
  }
}
operator<<()
template<typename T >
MessageBuilder& v8::internal::LogFile::MessageBuilder::operator<< (T value) [inline]
Definition at line 77 of file log-file.h.
                                        {
      log_->os_ << value;
      return *this;
    }
References log_, v8::internal::LogFile::os_, and v8::internal::value.
PRINTF_FORMAT() [1/3]
int v8::internal::LogFile::MessageBuilder::PRINTF_FORMAT (2 , 0) const [private]
PRINTF_FORMAT() [2/3]
void v8::internal::LogFile::MessageBuilder::PRINTF_FORMAT (2 , 3) const
PRINTF_FORMAT() [3/3]
void v8::internal::LogFile::MessageBuilder::PRINTF_FORMAT (2 , 3) const [private]
WriteToLogFile()
void v8::internal::LogFile::MessageBuilder::WriteToLogFile ()
Definition at line 253 of file log-file.cc.
{ log_->os_ << std::endl; }
Referenced by v8::internal::V8FileLogger::EnsureLogScriptSource(), and v8::internal::LogFile::WriteLogHeader().
Friends And Related Function Documentation
LogFile
friend class LogFile [friend]
Definition at line 104 of file log-file.h.
Member Data Documentation
args
int va_list v8::internal::LogFile::MessageBuilder::args [private]
Definition at line 93 of file log-file.h.
lock_guard_
NoGarbageCollectionMutexGuard v8::internal::LogFile::MessageBuilder::lock_guard_ [private]
Definition at line 102 of file log-file.h.
log_
LogFile* v8::internal::LogFile::MessageBuilder::log_ [private]
Definition at line 101 of file log-file.h.
Referenced by operator<<().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/logging/log-file.h
/mnt/V8SourceCode/src/logging/log-file.cc