v8::internal::interpreter::IntrinsicsGenerator Class Reference
Public Member Functions
IntrinsicsGenerator (InterpreterAssembler *assembler)
IntrinsicsGenerator (const IntrinsicsGenerator &)=delete
IntrinsicsGenerator & operator= (const IntrinsicsGenerator &)=delete
TNode< Object > InvokeIntrinsic (TNode< Uint32T > function_id, TNode< Context > context, const InterpreterAssembler::RegListNodePair &args)
Private Member Functions
TNode< Object > IntrinsicAsBuiltinCall (const InterpreterAssembler::RegListNodePair &args, TNode< Context > context, Builtin name, int arg_count)
void AbortIfArgCountMismatch (int expected, TNode< Word32T > actual)
Isolate * isolate ()
Zone * zone ()
Factory * factory ()
Private Attributes
Isolate * isolate_
Zone * zone_
InterpreterAssembler * assembler_
Detailed Description
Definition at line 20 of file interpreter-intrinsics-generator.cc.
Constructor & Destructor Documentation
IntrinsicsGenerator() [1/2]
v8::internal::interpreter::IntrinsicsGenerator::IntrinsicsGenerator (InterpreterAssembler * assembler) [inline], [explicit]
Definition at line 22 of file interpreter-intrinsics-generator.cc.
      : isolate_(assembler->isolate()),
        zone_(assembler->zone()),
        assembler_(assembler) {}
IntrinsicsGenerator() [2/2]
v8::internal::interpreter::IntrinsicsGenerator::IntrinsicsGenerator (const IntrinsicsGenerator &) [delete]
Member Function Documentation
AbortIfArgCountMismatch()
void v8::internal::interpreter::IntrinsicsGenerator::AbortIfArgCountMismatch (int expected, TNode< Word32T > actual) [private]
Definition at line 257 of file interpreter-intrinsics-generator.cc.
                                                                         {
  InterpreterAssembler::Label match(assembler_);
  TNode<BoolT> comparison = __ Word32Equal(actual, __ Int32Constant(expected));
  __ GotoIf(comparison, &match);
  __ Abort(AbortReason::kWrongArgumentCountForInvokeIntrinsic);
  __ Goto(&match);
  __ BIND(&match);
}
References __, assembler_, and v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal().
factory()
Factory* v8::internal::interpreter::IntrinsicsGenerator::factory () [inline], [private]
Definition at line 47 of file interpreter-intrinsics-generator.cc.
{ return isolate()->factory(); }
References v8::internal::Isolate::factory(), and isolate().
IntrinsicAsBuiltinCall()
TNode< Object > v8::internal::interpreter::IntrinsicsGenerator::IntrinsicAsBuiltinCall (const InterpreterAssembler::RegListNodePair & args, TNode< Context > context, Builtin name, int arg_count) [private]
Definition at line 110 of file interpreter-intrinsics-generator.cc.
                                    {
  switch (arg_count) {
    case 1:
      return __ CallBuiltin(builtin, context,
                            __ LoadRegisterFromRegisterList(args, 0));
    case 2:
      return __ CallBuiltin(builtin, context,
                            __ LoadRegisterFromRegisterList(args, 0),
                            __ LoadRegisterFromRegisterList(args, 1));
    case 3:
      return __ CallBuiltin(builtin, context,
                            __ LoadRegisterFromRegisterList(args, 0),
                            __ LoadRegisterFromRegisterList(args, 1),
                            __ LoadRegisterFromRegisterList(args, 2));
    default:
      UNREACHABLE();
  }
}
References __, v8::base::args, and v8::internal::UNREACHABLE().
InvokeIntrinsic()
TNode< Object > v8::internal::interpreter::IntrinsicsGenerator::InvokeIntrinsic (TNode< Uint32T > function_id, TNode< Context > context, const InterpreterAssembler::RegListNodePair & args)
Definition at line 63 of file interpreter-intrinsics-generator.cc.
                                                     {
  InterpreterAssembler::Label abort(assembler_), end(assembler_);
  InterpreterAssembler::TVariable<Object> result(assembler_);
#define MAKE_LABEL(name, lower_case, count) \
  InterpreterAssembler::Label lower_case(assembler_);
  INTRINSICS_LIST(MAKE_LABEL)
#undef MAKE_LABEL
#define LABEL_POINTER(name, lower_case, count) &lower_case,
  InterpreterAssembler::Label* labels[] = {INTRINSICS_LIST(LABEL_POINTER)};
#undef LABEL_POINTER
#define CASE(name, lower_case, count) \
  static_cast<int32_t>(IntrinsicsHelper::IntrinsicId::k##name),
  int32_t cases[] = {INTRINSICS_LIST(CASE)};
#undef CASE
  __ Switch(function_id, &abort, cases, labels, arraysize(cases));
#define HANDLE_CASE(name, lower_case, expected_arg_count) \
  __ BIND(&lower_case); \
  { \
    if (v8_flags.debug_code && expected_arg_count >= 0) { \
      AbortIfArgCountMismatch(expected_arg_count, args.reg_count()); \
    } \
    TNode<Object> value = name(args, context, expected_arg_count); \
    if (value) { \
      result = value; \
      __ Goto(&end); \
    } \
  }
  INTRINSICS_LIST(HANDLE_CASE)
#undef HANDLE_CASE
  __ BIND(&abort);
  {
    __ Abort(AbortReason::kUnexpectedFunctionIDForInvokeIntrinsic);
    result = __ UndefinedConstant();
    __ Goto(&end);
  }
  __ BIND(&end);
  return result.value();
}
References __, arraysize, assembler_, CASE, v8::internal::compiler::end(), HANDLE_CASE, INTRINSICS_LIST, LABEL_POINTER, MAKE_LABEL, v8::base::internal::result, and v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
Referenced by v8::internal::interpreter::GenerateInvokeIntrinsic().
isolate()
Isolate* v8::internal::interpreter::IntrinsicsGenerator::isolate () [inline], [private]
Definition at line 45 of file interpreter-intrinsics-generator.cc.
{ return isolate_; }
References isolate_.
Referenced by factory().
operator=()
IntrinsicsGenerator& v8::internal::interpreter::IntrinsicsGenerator::operator= (const IntrinsicsGenerator &) [delete]
zone()
Zone* v8::internal::interpreter::IntrinsicsGenerator::zone () [inline], [private]
Definition at line 46 of file interpreter-intrinsics-generator.cc.
{ return zone_; }
References zone_.
Member Data Documentation
assembler_
InterpreterAssembler* v8::internal::interpreter::IntrinsicsGenerator::assembler_ [private]
Definition at line 51 of file interpreter-intrinsics-generator.cc.
Referenced by AbortIfArgCountMismatch(), and InvokeIntrinsic().
isolate_
Isolate* v8::internal::interpreter::IntrinsicsGenerator::isolate_ [private]
Definition at line 49 of file interpreter-intrinsics-generator.cc.
Referenced by isolate().
zone_
Zone* v8::internal::interpreter::IntrinsicsGenerator::zone_ [private]
Definition at line 50 of file interpreter-intrinsics-generator.cc.
Referenced by zone().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/interpreter/interpreter-intrinsics-generator.cc