v8::internal::InstructionGetters< T > Class Template Reference
#include <constants-loong64.h>
Public Member Functions
int RjValue () const
int RkValue () const
int RdValue () const
int Sa2Value () const
int Sa3Value () const
int Ui5Value () const
int Ui6Value () const
int Ui12Value () const
int LsbwValue () const
int MsbwValue () const
int LsbdValue () const
int MsbdValue () const
int CondValue () const
int Si12Value () const
int Si14Value () const
int Si16Value () const
int Si20Value () const
int FdValue () const
int FaValue () const
int FjValue () const
int FkValue () const
int CjValue () const
int CdValue () const
int CaValue () const
int CodeValue () const
int Hint5Value () const
int Hint15Value () const
int Offs16Value () const
int Offs21Value () const
int Offs26Value () const
int RjFieldRaw () const
int RkFieldRaw () const
int RdFieldRaw () const
int32_t ImmValue (int bits) const
int32_t Imm12Value () const
int32_t Imm14Value () const
int32_t Imm16Value () const
bool IsTrap () const
int RsValue () const
int RtValue () const
int RdValue () const
int BaseValue () const
int SaValue () const
int LsaSaValue () const
int FunctionValue () const
int FdValue () const
int FsValue () const
int FtValue () const
int FrValue () const
int WdValue () const
int WsValue () const
int WtValue () const
int Bp2Value () const
int Bp3Value () const
int FCccValue () const
int FBccValue () const
int FBtrueValue () const
Opcode OpcodeFieldRaw () const
int RsFieldRaw () const
int RsFieldRawNoAssert () const
int RtFieldRaw () const
int RdFieldRaw () const
int SaFieldRaw () const
int FunctionFieldRaw () const
int SecondaryValue () const
int32_t ImmValue (int bits) const
int32_t Imm9Value () const
int32_t Imm16Value () const
int32_t Imm18Value () const
int32_t Imm19Value () const
int32_t Imm21Value () const
int32_t Imm26Value () const
int32_t MsaImm8Value () const
int32_t MsaImm5Value () const
int32_t MsaImm10Value () const
int32_t MsaImmMI10Value () const
int32_t MsaBitDf () const
int32_t MsaBitMValue () const
int32_t MsaElmDf () const
int32_t MsaElmNValue () const
bool IsForbiddenAfterBranch () const
bool IsForbiddenInBranchDelay () const
bool IsLinkingInstruction () const
bool IsTrap () const
bool IsMSABranchInstr () const
bool IsMSAInstr () const
uint32_t OperandFunct3 () const
bool IsLoad ()
bool IsStore ()
int BaseOpcode () const
int RvcOpcode () const
int Rs1Value () const
int Rs2Value () const
int Rs3Value () const
int Vs1Value () const
int Vs2Value () const
int VdValue () const
int RdValue () const
int RvcRs1Value () const
int RvcRdValue () const
int RvcRs2Value () const
int RvcRs1sValue () const
int RvcRs2sValue () const
int Funct7Value () const
int Funct3Value () const
int Funct5Value () const
int RvcFunct6Value () const
int RvcFunct4Value () const
int RvcFunct3Value () const
int RvcFunct2Value () const
int RvcFunct2BValue () const
int CsrValue () const
int RoundMode () const
int MemoryOrder (bool is_pred) const
int Imm12Value () const
int32_t Imm12SExtValue () const
int BranchOffset () const
int StoreOffset () const
int Imm20UValue () const
int Imm20JValue () const
bool IsArithShift () const
int Shamt () const
int Shamt32 () const
int RvcImm6Value () const
int RvcImm6Addi16spValue () const
int RvcImm8Addi4spnValue () const
int RvcShamt6 () const
int RvcImm6LwspValue () const
int RvcImm6LdspValue () const
int RvcImm6SwspValue () const
int RvcImm6SdspValue () const
int RvcImm5WValue () const
int RvcImm5DValue () const
int RvcImm11CJValue () const
int RvcImm8BValue () const
int vl_vs_width ()
uint32_t Rvvzimm () const
uint32_t Rvvuimm () const
uint32_t RvvVsew () const
uint32_t RvvVlmul () const
uint8_t RvvVM () const
const char * RvvSEW () const
const char * RvvLMUL () const
int32_t RvvSimm5 () const
uint32_t RvvUimm5 () const
bool AqValue () const
bool RlValue () const
bool IsTrap () const
bool IsAUIPC () const
Static Public Member Functions
static bool IsForbiddenAfterBranchInstr (Instr instr)
Detailed Description
template<class T>
class v8::internal::InstructionGetters< T >
Definition at line 764 of file constants-loong64.h.
Member Function Documentation
AqValue()
template<class T >
bool v8::internal::InstructionGetters< T >::AqValue () const [inline]
Definition at line 1247 of file base-constants-riscv.h.
{ return this->Bits(kAqShift, kAqShift); }
References v8::internal::kAqShift.
Referenced by v8::internal::Decoder< V >::PrintAcquireRelease().
BaseOpcode()
template<class T >
int v8::internal::InstructionGetters< T >::BaseOpcode () const [inline]
Definition at line 818 of file base-constants-riscv.h.
                                {
    return this->InstructionBits() & kBaseOpcodeMask;
  }
References v8::internal::kBaseOpcodeMask.
Referenced by v8::internal::InstructionGetters< T >::CsrValue(), v8::internal::Decoder< V >::DecodeRType(), v8::internal::InstructionGetters< T >::Funct5Value(), v8::internal::InstructionGetters< T >::IsArithShift(), v8::internal::InstructionGetters< T >::MemoryOrder(), and v8::internal::InstructionGetters< T >::RoundMode().
BaseValue()
template<class T >
int v8::internal::InstructionGetters< T >::BaseValue () const [inline]
Definition at line 1474 of file constants-mips64.h.
                               {
    DCHECK_EQ(this->InstructionType(), InstructionBase::kImmediateType);
    return this->Bits(kBaseShift + kBaseBits - 1, kBaseShift);
  }
References DCHECK_EQ, v8::internal::kBaseBits, v8::internal::kBaseShift, and v8::internal::InstructionBase::kImmediateType.
Bp2Value()
template<class T >
int v8::internal::InstructionGetters< T >::Bp2Value () const [inline]
Definition at line 1523 of file constants-mips64.h.
                              {
    DCHECK_EQ(this->InstructionType(), InstructionBase::kRegisterType);
    return this->Bits(kBp2Shift + kBp2Bits - 1, kBp2Shift);
  }
References DCHECK_EQ, v8::internal::kBp2Bits, v8::internal::kBp2Shift, and v8::internal::InstructionBase::kRegisterType.
Bp3Value()
template<class T >
int v8::internal::InstructionGetters< T >::Bp3Value () const [inline]
Definition at line 1528 of file constants-mips64.h.
                              {
    DCHECK_EQ(this->InstructionType(), InstructionBase::kRegisterType);
    return this->Bits(kBp3Shift + kBp3Bits - 1, kBp3Shift);
  }
References DCHECK_EQ, v8::internal::kBp3Bits, v8::internal::kBp3Shift, and v8::internal::InstructionBase::kRegisterType.
BranchOffset()
template<class T >
int v8::internal::InstructionGetters< T >::BranchOffset () const [inline]
Definition at line 955 of file base-constants-riscv.h.
                                  {
    DCHECK(this->InstructionType() == InstructionBase::kBType);
    // | imm[12|10:5] | rs2 | rs1 | funct3 | imm[4:1|11] | opcode |
    // 31 25 11 7
    uint32_t Bits = this->InstructionBits();
    int16_t imm13 = ((Bits & 0xf00) >> 7) | ((Bits & 0x7e000000) >> 20) |
                    ((Bits & 0x80) << 4) | ((Bits & 0x80000000) >> 19);
    return imm13 << 19 >> 19;
  }
References v8::internal::DCHECK(), and v8::internal::InstructionBase::kBType.
Referenced by v8::internal::Decoder< V >::PrintBranchOffset().
CaValue()
template<class T >
int v8::internal::InstructionGetters< T >::CaValue () const [inline]
Definition at line 858 of file constants-loong64.h.
                             {
    return this->Bits(kCaShift + kCaBits - 1, kCaShift);
  }
References v8::internal::kCaBits, and v8::internal::kCaShift.
CdValue()
template<class T >
int v8::internal::InstructionGetters< T >::CdValue () const [inline]
Definition at line 854 of file constants-loong64.h.
                             {
    return this->Bits(kCdShift + kCdBits - 1, kCdShift);
  }
References v8::internal::kCdBits, and v8::internal::kCdShift.
CjValue()
template<class T >
int v8::internal::InstructionGetters< T >::CjValue () const [inline]
Definition at line 850 of file constants-loong64.h.
                             {
    return this->Bits(kCjShift + kCjBits - 1, kCjShift);
  }
References v8::internal::kCjBits, and v8::internal::kCjShift.
CodeValue()
template<class T >
int v8::internal::InstructionGetters< T >::CodeValue () const [inline]
Definition at line 862 of file constants-loong64.h.
                               {
    return this->Bits(kCodeShift + kCodeBits - 1, kCodeShift);
  }
References v8::internal::kCodeBits, and v8::internal::kCodeShift.
CondValue()
template<class T >
int v8::internal::InstructionGetters< T >::CondValue () const [inline]
Definition at line 814 of file constants-loong64.h.
                               {
    return this->Bits(kCondShift + kCondBits - 1, kCondShift);
  }
References v8::internal::kCondBits, and v8::internal::kCondShift.
CsrValue()
template<class T >
int v8::internal::InstructionGetters< T >::CsrValue () const [inline]
Definition at line 921 of file base-constants-riscv.h.
                              {
    DCHECK(this->InstructionType() == InstructionBase::kIType &&
           this->BaseOpcode() == SYSTEM);
    return (this->Bits(kCsrShift + kCsrBits - 1, kCsrShift));
  }
References v8::internal::InstructionGetters< T >::BaseOpcode(), v8::internal::DCHECK(), v8::internal::kCsrBits, v8::internal::kCsrShift, v8::internal::InstructionBase::kIType, and v8::internal::SYSTEM.
Referenced by v8::internal::Decoder< V >::DecodeIType(), and v8::internal::Decoder< V >::PrintCSRReg().
FaValue()
template<class T >
int v8::internal::InstructionGetters< T >::FaValue () const [inline]
Definition at line 838 of file constants-loong64.h.
                             {
    return this->Bits(kFaShift + kFaBits - 1, kFaShift);
  }
References v8::internal::kFaBits, and v8::internal::kFaShift.
FBccValue()
template<class T >
int v8::internal::InstructionGetters< T >::FBccValue () const [inline]
Definition at line 1539 of file constants-mips64.h.
                               {
    return this->Bits(kFBccShift + kFBccBits - 1, kFBccShift);
  }
References v8::internal::kFBccBits, and v8::internal::kFBccShift.
FBtrueValue()
template<class T >
int v8::internal::InstructionGetters< T >::FBtrueValue () const [inline]
Definition at line 1544 of file constants-mips64.h.
                                 {
    return this->Bits(kFBtrueShift + kFBtrueBits - 1, kFBtrueShift);
  }
References v8::internal::kFBtrueBits, and v8::internal::kFBtrueShift.
FCccValue()
template<class T >
int v8::internal::InstructionGetters< T >::FCccValue () const [inline]
Definition at line 1534 of file constants-mips64.h.
                               {
    return this->Bits(kFCccShift + kFCccBits - 1, kFCccShift);
  }
References v8::internal::kFCccBits, and v8::internal::kFCccShift.
FdValue() [1/2]
template<class T >
int v8::internal::InstructionGetters< T >::FdValue () const [inline]
Definition at line 834 of file constants-loong64.h.
                             {
    return this->Bits(kFdShift + kFdBits - 1, kFdShift);
  }
References v8::internal::kFdBits, and v8::internal::kFdShift.
FdValue() [2/2]
template<class T >
int v8::internal::InstructionGetters< T >::FdValue () const [inline]
Definition at line 1495 of file constants-mips64.h.
                             {
    return this->Bits(kFdShift + kFdBits - 1, kFdShift);
  }
References v8::internal::kFdBits, and v8::internal::kFdShift.
FjValue()
template<class T >
int v8::internal::InstructionGetters< T >::FjValue () const [inline]
Definition at line 842 of file constants-loong64.h.
                             {
    return this->Bits(kFjShift + kFjBits - 1, kFjShift);
  }
References v8::internal::kFjBits, and v8::internal::kFjShift.
FkValue()
template<class T >
int v8::internal::InstructionGetters< T >::FkValue () const [inline]
Definition at line 846 of file constants-loong64.h.
                             {
    return this->Bits(kFkShift + kFkBits - 1, kFkShift);
  }
References v8::internal::kFkBits, and v8::internal::kFkShift.
FrValue()
template<class T >
int v8::internal::InstructionGetters< T >::FrValue () const [inline]
Definition at line 1507 of file constants-mips64.h.
                             {
    return this->Bits(kFrShift + kFrBits - 1, kFrShift);
  }
References v8::internal::kFrBits, and v8::internal::kFrShift.
FsValue()
template<class T >
int v8::internal::InstructionGetters< T >::FsValue () const [inline]
Definition at line 1499 of file constants-mips64.h.
                             {
    return this->Bits(kFsShift + kFsBits - 1, kFsShift);
  }
References v8::internal::kFsBits, and v8::internal::kFsShift.
FtValue()
template<class T >
int v8::internal::InstructionGetters< T >::FtValue () const [inline]
Definition at line 1503 of file constants-mips64.h.
                             {
    return this->Bits(kFtShift + kFtBits - 1, kFtShift);
  }
References v8::internal::kFtBits, and v8::internal::kFtShift.
Funct3Value()
template<class T >
int v8::internal::InstructionGetters< T >::Funct3Value () const [inline]
Definition at line 897 of file base-constants-riscv.h.
                                 {
    DCHECK(this->InstructionType() == InstructionBase::kRType ||
           this->InstructionType() == InstructionBase::kIType ||
           this->InstructionType() == InstructionBase::kSType ||
           this->InstructionType() == InstructionBase::kBType);
    return this->Bits(kFunct3Shift + kFunct3Bits - 1, kFunct3Shift);
  }
References v8::internal::DCHECK(), v8::internal::InstructionBase::kBType, v8::internal::kFunct3Bits, v8::internal::kFunct3Shift, v8::internal::InstructionBase::kIType, v8::internal::InstructionBase::kRType, and v8::internal::InstructionBase::kSType.
Referenced by v8::internal::Decoder< V >::DecodeRFPType(), v8::internal::InstructionGetters< T >::IsArithShift(), v8::internal::InstructionGetters< T >::Shamt(), and v8::internal::InstructionGetters< T >::Shamt32().
Funct5Value()
template<class T >
int v8::internal::InstructionGetters< T >::Funct5Value () const [inline]
Definition at line 905 of file base-constants-riscv.h.
                                 {
    DCHECK(this->InstructionType() == InstructionBase::kRType &&
           this->BaseOpcode() == OP_FP);
    return this->Bits(kFunct5Shift + kFunct5Bits - 1, kFunct5Shift);
  }
References v8::internal::InstructionGetters< T >::BaseOpcode(), v8::internal::DCHECK(), v8::internal::kFunct5Bits, v8::internal::kFunct5Shift, v8::internal::InstructionBase::kRType, and v8::internal::OP_FP.
Funct7Value()
template<class T >
int v8::internal::InstructionGetters< T >::Funct7Value () const
FunctionFieldRaw()
template<class T >
int v8::internal::InstructionGetters< T >::FunctionFieldRaw () const [inline]
Definition at line 1579 of file constants-mips64.h.
                                      {
    return this->InstructionBits() & kFunctionFieldMask;
  }
References v8::internal::kFunctionFieldMask.
FunctionValue()
template<class T >
int v8::internal::InstructionGetters< T >::FunctionValue () const [inline]
Definition at line 1489 of file constants-mips64.h.
                                   {
    DCHECK(this->InstructionType() == InstructionBase::kRegisterType ||
           this->InstructionType() == InstructionBase::kImmediateType);
    return this->Bits(kFunctionShift + kFunctionBits - 1, kFunctionShift);
  }
References v8::internal::DCHECK(), v8::internal::kFunctionBits, v8::internal::kFunctionShift, v8::internal::InstructionBase::kImmediateType, and v8::internal::InstructionBase::kRegisterType.
Referenced by v8::internal::InstructionGetters< T >::SecondaryValue().
Hint15Value()
template<class T >
int v8::internal::InstructionGetters< T >::Hint15Value () const [inline]
Definition at line 870 of file constants-loong64.h.
                                 {
    return this->Bits(kHint15Shift + kHint15Bits - 1, kHint15Shift);
  }
References v8::internal::kHint15Bits, and v8::internal::kHint15Shift.
Hint5Value()
template<class T >
int v8::internal::InstructionGetters< T >::Hint5Value () const [inline]
Definition at line 866 of file constants-loong64.h.
                                {
    return this->Bits(kHint5Shift + kHint5Bits - 1, kHint5Shift);
  }
References v8::internal::kHint5Bits, and v8::internal::kHint5Shift.
Imm12SExtValue()
template<class T >
int32_t v8::internal::InstructionGetters< T >::Imm12SExtValue () const [inline]
Definition at line 950 of file base-constants-riscv.h.
                                        {
    int32_t Value = this->Imm12Value() << 20 >> 20;
    return Value;
  }
References v8::internal::InstructionGetters< T >::Imm12Value().
Imm12Value() [1/2]
template<class T >
int32_t v8::internal::InstructionGetters< T >::Imm12Value () const [inline]
Definition at line 907 of file constants-loong64.h.
{ abort(); }
Referenced by v8::internal::Assembler::ConstantPoolSizeAt(), v8::internal::Decoder< V >::DecodeIType(), v8::internal::InstructionGetters< T >::Imm12SExtValue(), v8::internal::Decoder< V >::PrintImm12(), v8::internal::Decoder< V >::PrintImm12X(), and v8::internal::Assembler::target_constant32_at().
Imm12Value() [2/2]
template<class T >
int v8::internal::InstructionGetters< T >::Imm12Value () const [inline]
Definition at line 944 of file base-constants-riscv.h.
                                {
    DCHECK(this->InstructionType() == InstructionBase::kIType);
    int Value = this->Bits(kImm12Shift + kImm12Bits - 1, kImm12Shift);
    return Value << 20 >> 20;
  }
References v8::internal::DCHECK(), v8::internal::kImm12Bits, v8::internal::kImm12Shift, and v8::internal::InstructionBase::kIType.
Imm14Value()
template<class T >
int32_t v8::internal::InstructionGetters< T >::Imm14Value () const [inline]
Definition at line 909 of file constants-loong64.h.
{ abort(); }
Imm16Value() [1/2]
template<class T >
int32_t v8::internal::InstructionGetters< T >::Imm16Value () const [inline]
Definition at line 911 of file constants-loong64.h.
{ abort(); }
Imm16Value() [2/2]
template<class T >
int32_t v8::internal::InstructionGetters< T >::Imm16Value () const [inline]
Definition at line 1609 of file constants-mips64.h.
                                    {
    DCHECK_EQ(this->InstructionType(), InstructionBase::kImmediateType);
    return this->Bits(kImm16Shift + kImm16Bits - 1, kImm16Shift);
  }
References DCHECK_EQ, v8::internal::kImm16Bits, v8::internal::kImm16Shift, and v8::internal::InstructionBase::kImmediateType.
Imm18Value()
template<class T >
int32_t v8::internal::InstructionGetters< T >::Imm18Value () const [inline]
Definition at line 1614 of file constants-mips64.h.
                                    {
    DCHECK_EQ(this->InstructionType(), InstructionBase::kImmediateType);
    return this->Bits(kImm18Shift + kImm18Bits - 1, kImm18Shift);
  }
References DCHECK_EQ, v8::internal::kImm18Bits, v8::internal::kImm18Shift, and v8::internal::InstructionBase::kImmediateType.
Imm19Value()
template<class T >
int32_t v8::internal::InstructionGetters< T >::Imm19Value () const [inline]
Definition at line 1619 of file constants-mips64.h.
                                    {
    DCHECK_EQ(this->InstructionType(), InstructionBase::kImmediateType);
    return this->Bits(kImm19Shift + kImm19Bits - 1, kImm19Shift);
  }
References DCHECK_EQ, v8::internal::kImm19Bits, v8::internal::kImm19Shift, and v8::internal::InstructionBase::kImmediateType.
Imm20JValue()
template<class T >
int v8::internal::InstructionGetters< T >::Imm20JValue () const [inline]
Definition at line 982 of file base-constants-riscv.h.
                                 {
    DCHECK(this->InstructionType() == InstructionBase::kJType);
    // | imm[20|10:1|11|19:12] | rd | opcode |
    // 31 12
    uint32_t Bits = this->InstructionBits();
    int32_t imm20 = ((Bits & 0x7fe00000) >> 20) | ((Bits & 0x100000) >> 9) |
                    (Bits & 0xff000) | ((Bits & 0x80000000) >> 11);
    return imm20 << 11 >> 11;
  }
References v8::internal::DCHECK(), and v8::internal::InstructionBase::kJType.
Referenced by v8::internal::Assembler::IsConstantPoolAt(), and v8::internal::Decoder< V >::PrintImm20J().
Imm20UValue()
template<class T >
int v8::internal::InstructionGetters< T >::Imm20UValue () const [inline]
Definition at line 974 of file base-constants-riscv.h.
                                 {
    DCHECK(this->InstructionType() == InstructionBase::kUType);
    // | imm[31:12] | rd | opcode |
    // 31 12
    int32_t Bits = this->InstructionBits();
    return Bits >> 12;
  }
References v8::internal::DCHECK(), and v8::internal::InstructionBase::kUType.
Referenced by v8::internal::Decoder< V >::PrintImm20U(), and v8::internal::Assembler::target_constant32_at().
Imm21Value()
template<class T >
int32_t v8::internal::InstructionGetters< T >::Imm21Value () const [inline]
Definition at line 1624 of file constants-mips64.h.
                                    {
    DCHECK_EQ(this->InstructionType(), InstructionBase::kImmediateType);
    return this->Bits(kImm21Shift + kImm21Bits - 1, kImm21Shift);
  }
References DCHECK_EQ, v8::internal::kImm21Bits, v8::internal::kImm21Shift, and v8::internal::InstructionBase::kImmediateType.
Imm26Value()
template<class T >
int32_t v8::internal::InstructionGetters< T >::Imm26Value () const [inline]
Definition at line 1629 of file constants-mips64.h.
                                    {
    DCHECK((this->InstructionType() == InstructionBase::kJumpType) ||
           (this->InstructionType() == InstructionBase::kImmediateType));
    return this->Bits(kImm26Shift + kImm26Bits - 1, kImm26Shift);
  }
References v8::internal::DCHECK(), v8::internal::kImm26Bits, v8::internal::kImm26Shift, v8::internal::InstructionBase::kImmediateType, and v8::internal::InstructionBase::kJumpType.
Imm9Value()
template<class T >
int32_t v8::internal::InstructionGetters< T >::Imm9Value () const [inline]
Definition at line 1604 of file constants-mips64.h.
                                   {
    DCHECK_EQ(this->InstructionType(), InstructionBase::kImmediateType);
    return this->Bits(kImm9Shift + kImm9Bits - 1, kImm9Shift);
  }
References DCHECK_EQ, v8::internal::kImm9Bits, v8::internal::kImm9Shift, and v8::internal::InstructionBase::kImmediateType.
ImmValue() [1/2]
template<class T >
int32_t v8::internal::InstructionGetters< T >::ImmValue (int bits) const [inline]
Definition at line 904 of file constants-loong64.h.
{ return this->Bits(bits - 1, 0); }
ImmValue() [2/2]
template<class T >
int32_t v8::internal::InstructionGetters< T >::ImmValue (int bits) const [inline]
Definition at line 1599 of file constants-mips64.h.
                                          {
    DCHECK_EQ(this->InstructionType(), InstructionBase::kImmediateType);
    return this->Bits(bits - 1, 0);
  }
References DCHECK_EQ, and v8::internal::InstructionBase::kImmediateType.
IsArithShift()
template<class T >
bool v8::internal::InstructionGetters< T >::IsArithShift () const [inline]
Definition at line 992 of file base-constants-riscv.h.
                                   {
    // Valid only for right shift operations
    DCHECK((this->BaseOpcode() == OP || this->BaseOpcode() == OP_32 ||
            this->BaseOpcode() == OP_IMM || this->BaseOpcode() == OP_IMM_32) &&
           this->Funct3Value() == 0b101);
    return this->InstructionBits() & 0x40000000;
  }
References v8::internal::InstructionGetters< T >::BaseOpcode(), v8::internal::DCHECK(), v8::internal::InstructionGetters< T >::Funct3Value(), v8::internal::OP, v8::internal::OP_32, v8::internal::OP_IMM, and v8::internal::OP_IMM_32.
IsAUIPC()
template<class T >
bool v8::internal::InstructionGetters< T >::IsAUIPC () const [inline]
Definition at line 1254 of file base-constants-riscv.h.
                       {
    return (this->InstructionBits() & kBaseOpcodeMask) == AUIPC;
  }
References v8::internal::AUIPC, and v8::internal::kBaseOpcodeMask.
Referenced by v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::GetWasmCalleeTag(), and v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::SetWasmCalleeTag().
IsForbiddenAfterBranch()
template<class T >
bool v8::internal::InstructionGetters< T >::IsForbiddenAfterBranch () const [inline]
Definition at line 1703 of file constants-mips64.h.
                                             {
    return IsForbiddenAfterBranchInstr(this->InstructionBits());
  }
References v8::internal::InstructionGetters< T >::IsForbiddenAfterBranchInstr().
Referenced by v8::internal::InstructionGetters< T >::IsForbiddenInBranchDelay().
IsForbiddenAfterBranchInstr()
template<class T >
bool v8::internal::InstructionGetters< T >::IsForbiddenAfterBranchInstr (Instr instr) [static]
Definition at line 1962 of file constants-mips64.h.
                                                                   {
  Opcode opcode = static_cast<Opcode>(instr & kOpcodeMask);
  switch (opcode) {
    case J:
    case JAL:
    case BEQ:
    case BNE:
    case BLEZ: // POP06 bgeuc/bleuc, blezalc, bgezalc
    case BGTZ: // POP07 bltuc/bgtuc, bgtzalc, bltzalc
    case BEQL:
    case BNEL:
    case BLEZL: // POP26 bgezc, blezc, bgec/blec
    case BGTZL: // POP27 bgtzc, bltzc, bltc/bgtc
    case BC:
    case BALC:
    case POP10: // beqzalc, bovc, beqc
    case POP30: // bnezalc, bnvc, bnec
    case POP66: // beqzc, jic
    case POP76: // bnezc, jialc
      return true;
    case REGIMM:
      switch (instr & kRtFieldMask) {
        case BLTZ:
        case BGEZ:
        case BLTZAL:
        case BGEZAL:
          return true;
        default:
          return false;
      }
      break;
    case SPECIAL:
      switch (instr & kFunctionFieldMask) {
        case JR:
        case JALR:
          return true;
        default:
          return false;
      }
      break;
    case COP1:
      switch (instr & kRsFieldMask) {
        case BC1:
        case BC1EQZ:
        case BC1NEZ:
        case BZ_V:
        case BZ_B:
        case BZ_H:
        case BZ_W:
        case BZ_D:
        case BNZ_V:
        case BNZ_B:
        case BNZ_H:
        case BNZ_W:
        case BNZ_D:
          return true;
          break;
        default:
          return false;
      }
      break;
    default:
      return false;
  }
}
References v8::internal::BALC, v8::internal::BC, v8::internal::BC1, v8::internal::BC1EQZ, v8::internal::BC1NEZ, v8::internal::BEQ, v8::internal::BEQL, v8::internal::BGEZ, v8::internal::BGEZAL, v8::internal::BGTZ, v8::internal::BGTZL, v8::internal::BLEZ, v8::internal::BLEZL, v8::internal::BLTZ, v8::internal::BLTZAL, v8::internal::BNE, v8::internal::BNEL, v8::internal::BNZ_B, v8::internal::BNZ_D, v8::internal::BNZ_H, v8::internal::BNZ_V, v8::internal::BNZ_W, v8::internal::BZ_B, v8::internal::BZ_D, v8::internal::BZ_H, v8::internal::BZ_V, v8::internal::BZ_W, v8::internal::COP1, v8::internal::J, v8::internal::JAL, v8::internal::JALR, v8::internal::JR, v8::internal::kFunctionFieldMask, v8::internal::kOpcodeMask, v8::internal::kRsFieldMask, v8::internal::kRtFieldMask, v8::internal::POP10, v8::internal::POP30, v8::internal::POP66, v8::internal::POP76, v8::internal::REGIMM, and v8::internal::SPECIAL.
Referenced by v8::internal::InstructionGetters< T >::IsForbiddenAfterBranch().
IsForbiddenInBranchDelay()
template<class T >
bool v8::internal::InstructionGetters< T >::IsForbiddenInBranchDelay () const [inline]
Definition at line 1707 of file constants-mips64.h.
                                               {
    return IsForbiddenAfterBranch();
  }
References v8::internal::InstructionGetters< T >::IsForbiddenAfterBranch().
IsLinkingInstruction()
template<class P >
bool v8::internal::InstructionGetters< P >::IsLinkingInstruction
Definition at line 1911 of file constants-mips64.h.
                                                       {
  switch (OpcodeFieldRaw()) {
    case JAL:
      return true;
    case POP76:
      if (RsFieldRawNoAssert() == JIALC)
        return true; // JIALC
      else
        return false; // BNEZC
    case REGIMM:
      switch (RtFieldRaw()) {
        case BGEZAL:
        case BLTZAL:
          return true;
        default:
          return false;
      }
    case SPECIAL:
      switch (FunctionFieldRaw()) {
        case JALR:
          return true;
        default:
          return false;
      }
    default:
      return false;
  }
}
References v8::internal::BGEZAL, v8::internal::BLTZAL, v8::internal::JAL, v8::internal::JALR, v8::internal::JIALC, v8::internal::POP76, v8::internal::REGIMM, and v8::internal::SPECIAL.
IsLoad()
template<class T >
bool v8::internal::InstructionGetters< T >::IsLoad
Definition at line 234 of file base-constants-riscv.cc.
                                   {
  switch (OperandFunct3()) {
    case RO_LB:
    case RO_LBU:
    case RO_LH:
    case RO_LHU:
    case RO_LW:
#ifdef V8_TARGET_ARCH_RISCV64
    case RO_LD:
    case RO_LWU:
#endif
      return true;
    case RO_C_LW:
    case RO_C_LWSP:
#ifdef V8_TARGET_ARCH_RISCV64
    case RO_C_LD:
    case RO_C_LDSP:
#endif
      return v8_flags.riscv_c_extension && this->IsShortInstruction();
    default:
      return BaseOpcode() == LOAD_FP;
  }
}
References v8::internal::LOAD_FP, v8::internal::RO_C_LW, v8::internal::RO_C_LWSP, v8::internal::RO_LB, v8::internal::RO_LBU, v8::internal::RO_LH, v8::internal::RO_LHU, v8::internal::RO_LW, and v8::internal::v8_flags.
IsMSABranchInstr()
template<class T >
bool v8::internal::InstructionGetters< T >::IsMSABranchInstr () const [inline]
Definition at line 1716 of file constants-mips64.h.
                                       {
    if (this->OpcodeFieldRaw() == COP1) {
      switch (this->RsFieldRaw()) {
        case BZ_V:
        case BZ_B:
        case BZ_H:
        case BZ_W:
        case BZ_D:
        case BNZ_V:
        case BNZ_B:
        case BNZ_H:
        case BNZ_W:
        case BNZ_D:
          return true;
        default:
          return false;
      }
    }
    return false;
  }
References v8::internal::BNZ_B, v8::internal::BNZ_D, v8::internal::BNZ_H, v8::internal::BNZ_V, v8::internal::BNZ_W, v8::internal::BZ_B, v8::internal::BZ_D, v8::internal::BZ_H, v8::internal::BZ_V, v8::internal::BZ_W, v8::internal::InstructionGetters< T >::OpcodeFieldRaw(), and v8::internal::InstructionGetters< T >::RsFieldRaw().
Referenced by v8::internal::InstructionGetters< T >::IsMSAInstr().
IsMSAInstr()
template<class T >
bool v8::internal::InstructionGetters< T >::IsMSAInstr () const [inline]
Definition at line 1737 of file constants-mips64.h.
                                 {
    if (this->IsMSABranchInstr() || (this->OpcodeFieldRaw() == MSA))
      return true;
    return false;
  }
References v8::internal::InstructionGetters< T >::IsMSABranchInstr(), and v8::internal::InstructionGetters< T >::OpcodeFieldRaw().
IsStore()
template<class T >
bool v8::internal::InstructionGetters< T >::IsStore
Definition at line 259 of file base-constants-riscv.cc.
                                    {
  switch (OperandFunct3()) {
    case RO_SB:
    case RO_SH:
    case RO_SW:
#ifdef V8_TARGET_ARCH_RISCV64
    case RO_SD:
#endif
      return true;
    case RO_C_SW:
    case RO_C_SWSP:
#ifdef V8_TARGET_ARCH_RISCV64
    case RO_C_SD:
    case RO_C_SDSP:
#endif
      return v8_flags.riscv_c_extension && this->IsShortInstruction();
    default:
      return BaseOpcode() == STORE_FP;
  }
}
References v8::internal::RO_C_SW, v8::internal::RO_C_SWSP, v8::internal::RO_SB, v8::internal::RO_SH, v8::internal::RO_SW, v8::internal::STORE_FP, and v8::internal::v8_flags.
IsTrap() [1/3]
template<class P >
bool v8::internal::InstructionGetters< P >::IsTrap
Definition at line 1294 of file constants-loong64.h.
                                         {
  if ((this->Bits(31, 15) << 15) == BREAK) return true;
  return false;
}
References v8::internal::BREAK.
IsTrap() [2/3]
template<class T >
bool v8::internal::InstructionGetters< T >::IsTrap () const
IsTrap() [3/3]
template<class T >
bool v8::internal::InstructionGetters< T >::IsTrap () const
LsaSaValue()
template<class T >
int v8::internal::InstructionGetters< T >::LsaSaValue () const [inline]
Definition at line 1484 of file constants-mips64.h.
                                {
    DCHECK_EQ(this->InstructionType(), InstructionBase::kRegisterType);
    return this->Bits(kSaShift + kLsaSaBits - 1, kSaShift);
  }
References DCHECK_EQ, v8::internal::kLsaSaBits, v8::internal::InstructionBase::kRegisterType, and v8::internal::kSaShift.
LsbdValue()
template<class T >
int v8::internal::InstructionGetters< T >::LsbdValue () const [inline]
Definition at line 806 of file constants-loong64.h.
                               {
    return this->Bits(kLsbdShift + kLsbdBits - 1, kLsbdShift);
  }
References v8::internal::kLsbdBits, and v8::internal::kLsbdShift.
LsbwValue()
template<class T >
int v8::internal::InstructionGetters< T >::LsbwValue () const [inline]
Definition at line 798 of file constants-loong64.h.
                               {
    return this->Bits(kLsbwShift + kLsbwBits - 1, kLsbwShift);
  }
References v8::internal::kLsbwBits, and v8::internal::kLsbwShift.
MemoryOrder()
template<class T >
int v8::internal::InstructionGetters< T >::MemoryOrder (bool is_pred) const [inline]
Definition at line 934 of file base-constants-riscv.h.
                                             {
    DCHECK((this->InstructionType() == InstructionBase::kIType &&
            this->BaseOpcode() == MISC_MEM));
    if (is_pred) {
      return this->Bits(kPredOrderShift + kMemOrderBits - 1, kPredOrderShift);
    } else {
      return this->Bits(kSuccOrderShift + kMemOrderBits - 1, kSuccOrderShift);
    }
  }
References v8::internal::InstructionGetters< T >::BaseOpcode(), v8::internal::DCHECK(), v8::internal::InstructionBase::kIType, v8::internal::kMemOrderBits, v8::internal::kPredOrderShift, v8::internal::kSuccOrderShift, and v8::internal::MISC_MEM.
Referenced by v8::internal::Decoder< V >::DecodeIType(), and v8::internal::Decoder< V >::PrintMemoryOrder().
MsaBitDf()
template<class T >
int32_t v8::internal::InstructionGetters< T >::MsaBitDf () const [inline]
Definition at line 1655 of file constants-mips64.h.
                                  {
    DCHECK_EQ(this->InstructionType(), InstructionBase::kImmediateType);
    int32_t df_m = this->Bits(22, 16);
    if (((df_m >> 6) & 1U) == 0) {
      return 3;
    } else if (((df_m >> 5) & 3U) == 2) {
      return 2;
    } else if (((df_m >> 4) & 7U) == 6) {
      return 1;
    } else if (((df_m >> 3) & 15U) == 14) {
      return 0;
    } else {
      return -1;
    }
  }
References DCHECK_EQ, and v8::internal::InstructionBase::kImmediateType.
Referenced by v8::internal::InstructionGetters< T >::MsaBitMValue().
MsaBitMValue()
template<class T >
int32_t v8::internal::InstructionGetters< T >::MsaBitMValue () const [inline]
Definition at line 1671 of file constants-mips64.h.
                                      {
    DCHECK_EQ(this->InstructionType(), InstructionBase::kImmediateType);
    return this->Bits(16 + this->MsaBitDf() + 3, 16);
  }
References DCHECK_EQ, v8::internal::InstructionBase::kImmediateType, and v8::internal::InstructionGetters< T >::MsaBitDf().
MsaElmDf()
template<class T >
int32_t v8::internal::InstructionGetters< T >::MsaElmDf () const [inline]
Definition at line 1676 of file constants-mips64.h.
                                  {
    DCHECK(this->InstructionType() == InstructionBase::kRegisterType ||
           this->InstructionType() == InstructionBase::kImmediateType);
    int32_t df_n = this->Bits(21, 16);
    if (((df_n >> 4) & 3U) == 0) {
      return 0;
    } else if (((df_n >> 3) & 7U) == 4) {
      return 1;
    } else if (((df_n >> 2) & 15U) == 12) {
      return 2;
    } else if (((df_n >> 1) & 31U) == 28) {
      return 3;
    } else {
      return -1;
    }
  }
References v8::internal::DCHECK(), v8::internal::InstructionBase::kImmediateType, and v8::internal::InstructionBase::kRegisterType.
Referenced by v8::internal::InstructionGetters< T >::MsaElmNValue().
MsaElmNValue()
template<class T >
int32_t v8::internal::InstructionGetters< T >::MsaElmNValue () const [inline]
Definition at line 1693 of file constants-mips64.h.
                                      {
    DCHECK(this->InstructionType() == InstructionBase::kRegisterType ||
           this->InstructionType() == InstructionBase::kImmediateType);
    return this->Bits(16 + 4 - this->MsaElmDf(), 16);
  }
References v8::internal::DCHECK(), v8::internal::InstructionBase::kImmediateType, v8::internal::InstructionBase::kRegisterType, and v8::internal::InstructionGetters< T >::MsaElmDf().
MsaImm10Value()
template<class T >
int32_t v8::internal::InstructionGetters< T >::MsaImm10Value () const [inline]
Definition at line 1645 of file constants-mips64.h.
                                       {
    DCHECK_EQ(this->InstructionType(), InstructionBase::kImmediateType);
    return this->Bits(kMsaImm10Shift + kMsaImm10Bits - 1, kMsaImm10Shift);
  }
References DCHECK_EQ, v8::internal::InstructionBase::kImmediateType, v8::internal::kMsaImm10Bits, and v8::internal::kMsaImm10Shift.
MsaImm5Value()
template<class T >
int32_t v8::internal::InstructionGetters< T >::MsaImm5Value () const [inline]
Definition at line 1640 of file constants-mips64.h.
                                      {
    DCHECK_EQ(this->InstructionType(), InstructionBase::kImmediateType);
    return this->Bits(kMsaImm5Shift + kMsaImm5Bits - 1, kMsaImm5Shift);
  }
References DCHECK_EQ, v8::internal::InstructionBase::kImmediateType, v8::internal::kMsaImm5Bits, and v8::internal::kMsaImm5Shift.
MsaImm8Value()
template<class T >
int32_t v8::internal::InstructionGetters< T >::MsaImm8Value () const [inline]
Definition at line 1635 of file constants-mips64.h.
                                      {
    DCHECK_EQ(this->InstructionType(), InstructionBase::kImmediateType);
    return this->Bits(kMsaImm8Shift + kMsaImm8Bits - 1, kMsaImm8Shift);
  }
References DCHECK_EQ, v8::internal::InstructionBase::kImmediateType, v8::internal::kMsaImm8Bits, and v8::internal::kMsaImm8Shift.
MsaImmMI10Value()
template<class T >
int32_t v8::internal::InstructionGetters< T >::MsaImmMI10Value () const [inline]
Definition at line 1650 of file constants-mips64.h.
                                         {
    DCHECK_EQ(this->InstructionType(), InstructionBase::kImmediateType);
    return this->Bits(kMsaImmMI10Shift + kMsaImmMI10Bits - 1, kMsaImmMI10Shift);
  }
References DCHECK_EQ, v8::internal::InstructionBase::kImmediateType, v8::internal::kMsaImmMI10Bits, and v8::internal::kMsaImmMI10Shift.
MsbdValue()
template<class T >
int v8::internal::InstructionGetters< T >::MsbdValue () const [inline]
Definition at line 810 of file constants-loong64.h.
                               {
    return this->Bits(kMsbdShift + kMsbdBits - 1, kMsbdShift);
  }
References v8::internal::kMsbdBits, and v8::internal::kMsbdShift.
MsbwValue()
template<class T >
int v8::internal::InstructionGetters< T >::MsbwValue () const [inline]
Definition at line 802 of file constants-loong64.h.
                               {
    return this->Bits(kMsbwShift + kMsbwBits - 1, kMsbwShift);
  }
References v8::internal::kMsbwBits, and v8::internal::kMsbwShift.
Offs16Value()
template<class T >
int v8::internal::InstructionGetters< T >::Offs16Value () const [inline]
Definition at line 874 of file constants-loong64.h.
                                 {
    return this->Bits(kOffsLowShift + kOffsLowBits - 1, kOffsLowShift);
  }
References v8::internal::kOffsLowBits, and v8::internal::kOffsLowShift.
Offs21Value()
template<class T >
int v8::internal::InstructionGetters< T >::Offs21Value () const [inline]
Definition at line 878 of file constants-loong64.h.
                                 {
    int low = this->Bits(kOffsLowShift + kOffsLowBits - 1, kOffsLowShift);
    int high =
        this->Bits(kOffs21HighShift + kOffs21HighBits - 1, kOffs21HighShift);
    return ((high << kOffsLowBits) + low);
  }
References v8::internal::kOffs21HighBits, v8::internal::kOffs21HighShift, v8::internal::kOffsLowBits, and v8::internal::kOffsLowShift.
Offs26Value()
template<class T >
int v8::internal::InstructionGetters< T >::Offs26Value () const [inline]
Definition at line 885 of file constants-loong64.h.
                                 {
    int low = this->Bits(kOffsLowShift + kOffsLowBits - 1, kOffsLowShift);
    int high =
        this->Bits(kOffs26HighShift + kOffs26HighBits - 1, kOffs26HighShift);
    return ((high << kOffsLowBits) + low);
  }
References v8::internal::kOffs26HighBits, v8::internal::kOffs26HighShift, v8::internal::kOffsLowBits, and v8::internal::kOffsLowShift.
OpcodeFieldRaw()
template<class T >
Opcode v8::internal::InstructionGetters< T >::OpcodeFieldRaw () const [inline]
Definition at line 1549 of file constants-mips64.h.
                                       {
    return static_cast<Opcode>(this->InstructionBits() & kOpcodeMask);
  }
References v8::internal::kOpcodeMask.
Referenced by v8::internal::InstructionGetters< T >::IsMSABranchInstr(), v8::internal::InstructionGetters< T >::IsMSAInstr(), and v8::internal::InstructionGetters< T >::SecondaryValue().
OperandFunct3()
template<class T >
uint32_t v8::internal::InstructionGetters< T >::OperandFunct3 () const [inline]
Definition at line 813 of file base-constants-riscv.h.
                                 {
    return this->InstructionBits() & (kBaseOpcodeMask | kFunct3Mask);
  }
References v8::internal::kBaseOpcodeMask, and v8::internal::kFunct3Mask.
RdFieldRaw() [1/2]
template<class T >
int v8::internal::InstructionGetters< T >::RdFieldRaw () const [inline]
Definition at line 900 of file constants-loong64.h.
                                {
    return this->InstructionBits() & kRdFieldMask;
  }
References v8::internal::kRdFieldMask.
RdFieldRaw() [2/2]
template<class T >
int v8::internal::InstructionGetters< T >::RdFieldRaw () const [inline]
Definition at line 1570 of file constants-mips64.h.
                                {
    DCHECK_EQ(this->InstructionType(), InstructionBase::kRegisterType);
    return this->InstructionBits() & kRdFieldMask;
  }
References DCHECK_EQ, v8::internal::kRdFieldMask, and v8::internal::InstructionBase::kRegisterType.
RdValue() [1/3]
template<class T >
int v8::internal::InstructionGetters< T >::RdValue () const [inline]
Definition at line 774 of file constants-loong64.h.
                             {
    return this->Bits(kRdShift + kRdBits - 1, kRdShift);
  }
References v8::internal::kRdBits, and v8::internal::kRdShift.
RdValue() [2/3]
template<class T >
int v8::internal::InstructionGetters< T >::RdValue () const [inline]
Definition at line 1469 of file constants-mips64.h.
                             {
    DCHECK_EQ(this->InstructionType(), InstructionBase::kRegisterType);
    return this->Bits(kRdShift + kRdBits - 1, kRdShift);
  }
References DCHECK_EQ, v8::internal::kRdBits, v8::internal::kRdShift, and v8::internal::InstructionBase::kRegisterType.
RdValue() [3/3]
template<class T >
int v8::internal::InstructionGetters< T >::RdValue () const [inline]
Definition at line 874 of file base-constants-riscv.h.
                             {
    DCHECK(this->InstructionType() == InstructionBase::kRType ||
           this->InstructionType() == InstructionBase::kR4Type ||
           this->InstructionType() == InstructionBase::kIType ||
           this->InstructionType() == InstructionBase::kSType ||
           this->InstructionType() == InstructionBase::kUType ||
           this->InstructionType() == InstructionBase::kJType ||
           this->InstructionType() == InstructionBase::kVType);
    return this->Bits(kRdShift + kRdBits - 1, kRdShift);
  }
References v8::internal::DCHECK(), v8::internal::InstructionBase::kIType, v8::internal::InstructionBase::kJType, v8::internal::InstructionBase::kR4Type, v8::internal::kRdBits, v8::internal::kRdShift, v8::internal::InstructionBase::kRType, v8::internal::InstructionBase::kSType, v8::internal::InstructionBase::kUType, and v8::internal::InstructionBase::kVType.
RjFieldRaw()
template<class T >
int v8::internal::InstructionGetters< T >::RjFieldRaw () const [inline]
Definition at line 892 of file constants-loong64.h.
                                {
    return this->InstructionBits() & kRjFieldMask;
  }
References v8::internal::kRjFieldMask.
RjValue()
template<class T >
int v8::internal::InstructionGetters< T >::RjValue () const [inline]
Definition at line 766 of file constants-loong64.h.
                             {
    return this->Bits(kRjShift + kRjBits - 1, kRjShift);
  }
References v8::internal::kRjBits, and v8::internal::kRjShift.
RkFieldRaw()
template<class T >
int v8::internal::InstructionGetters< T >::RkFieldRaw () const [inline]
Definition at line 896 of file constants-loong64.h.
                                {
    return this->InstructionBits() & kRkFieldMask;
  }
References v8::internal::kRkFieldMask.
RkValue()
template<class T >
int v8::internal::InstructionGetters< T >::RkValue () const [inline]
Definition at line 770 of file constants-loong64.h.
                             {
    return this->Bits(kRkShift + kRkBits - 1, kRkShift);
  }
References v8::internal::kRkBits, and v8::internal::kRkShift.
RlValue()
template<class T >
bool v8::internal::InstructionGetters< T >::RlValue () const [inline]
Definition at line 1249 of file base-constants-riscv.h.
{ return this->Bits(kRlShift, kRlShift); }
References v8::internal::kRlShift.
Referenced by v8::internal::Decoder< V >::PrintAcquireRelease().
RoundMode()
template<class T >
int v8::internal::InstructionGetters< T >::RoundMode () const [inline]
Definition at line 927 of file base-constants-riscv.h.
                               {
    DCHECK((this->InstructionType() == InstructionBase::kRType ||
            this->InstructionType() == InstructionBase::kR4Type) &&
           this->BaseOpcode() == OP_FP);
    return this->Bits(kFunct3Shift + kFunct3Bits - 1, kFunct3Shift);
  }
References v8::internal::InstructionGetters< T >::BaseOpcode(), v8::internal::DCHECK(), v8::internal::kFunct3Bits, v8::internal::kFunct3Shift, v8::internal::InstructionBase::kR4Type, v8::internal::InstructionBase::kRType, and v8::internal::OP_FP.
Referenced by v8::internal::Decoder< V >::PrintRoundingMode().
Rs1Value()
template<class T >
int v8::internal::InstructionGetters< T >::Rs1Value () const [inline]
Definition at line 827 of file base-constants-riscv.h.
                              {
    DCHECK(this->InstructionType() == InstructionBase::kRType ||
           this->InstructionType() == InstructionBase::kR4Type ||
           this->InstructionType() == InstructionBase::kIType ||
           this->InstructionType() == InstructionBase::kSType ||
           this->InstructionType() == InstructionBase::kBType ||
           this->InstructionType() == InstructionBase::kIType ||
           this->InstructionType() == InstructionBase::kVType);
    return this->Bits(kRs1Shift + kRs1Bits - 1, kRs1Shift);
  }
References v8::internal::DCHECK(), v8::internal::InstructionBase::kBType, v8::internal::InstructionBase::kIType, v8::internal::InstructionBase::kR4Type, v8::internal::kRs1Bits, v8::internal::kRs1Shift, v8::internal::InstructionBase::kRType, v8::internal::InstructionBase::kSType, and v8::internal::InstructionBase::kVType.
Referenced by v8::internal::Decoder< V >::DecodeIType(), v8::internal::Decoder< V >::DecodeRFPType(), v8::internal::Decoder< V >::DecodeRType(), v8::internal::Decoder< V >::DecodeRvvIVX(), v8::internal::Decoder< V >::FormatFPURegisterOrRoundMode(), v8::internal::Decoder< V >::FormatRegister(), v8::internal::Assembler::IsConstantPoolAt(), v8::internal::Decoder< V >::PrintFRs1(), v8::internal::Decoder< V >::PrintRs1(), v8::internal::Decoder< V >::PrintTarget(), v8::internal::Decoder< V >::PrintUimm(), and v8::internal::Assembler::target_at_put().
Rs2Value()
template<class T >
int v8::internal::InstructionGetters< T >::Rs2Value () const [inline]
Definition at line 838 of file base-constants-riscv.h.
                              {
    DCHECK(this->InstructionType() == InstructionBase::kRType ||
           this->InstructionType() == InstructionBase::kR4Type ||
           this->InstructionType() == InstructionBase::kSType ||
           this->InstructionType() == InstructionBase::kBType ||
           this->InstructionType() == InstructionBase::kIType ||
           this->InstructionType() == InstructionBase::kVType);
    return this->Bits(kRs2Shift + kRs2Bits - 1, kRs2Shift);
  }
References v8::internal::DCHECK(), v8::internal::InstructionBase::kBType, v8::internal::InstructionBase::kIType, v8::internal::InstructionBase::kR4Type, v8::internal::kRs2Bits, v8::internal::kRs2Shift, v8::internal::InstructionBase::kRType, v8::internal::InstructionBase::kSType, and v8::internal::InstructionBase::kVType.
Referenced by v8::internal::Decoder< V >::DecodeRFPType(), v8::internal::Decoder< V >::DecodeRType(), v8::internal::Decoder< V >::FormatFPURegisterOrRoundMode(), v8::internal::Decoder< V >::FormatRegister(), v8::internal::Decoder< V >::PrintFRs2(), and v8::internal::Decoder< V >::PrintRs2().
Rs3Value()
template<class T >
int v8::internal::InstructionGetters< T >::Rs3Value () const [inline]
Definition at line 848 of file base-constants-riscv.h.
                              {
    DCHECK(this->InstructionType() == InstructionBase::kR4Type);
    return this->Bits(kRs3Shift + kRs3Bits - 1, kRs3Shift);
  }
References v8::internal::DCHECK(), v8::internal::InstructionBase::kR4Type, v8::internal::kRs3Bits, and v8::internal::kRs3Shift.
Referenced by v8::internal::Decoder< V >::FormatFPURegisterOrRoundMode(), and v8::internal::Decoder< V >::PrintFRs3().
RsFieldRaw()
template<class T >
int v8::internal::InstructionGetters< T >::RsFieldRaw () const [inline]
Definition at line 1553 of file constants-mips64.h.
                                {
    DCHECK(this->InstructionType() == InstructionBase::kRegisterType ||
           this->InstructionType() == InstructionBase::kImmediateType);
    return this->InstructionBits() & kRsFieldMask;
  }
References v8::internal::DCHECK(), v8::internal::InstructionBase::kImmediateType, v8::internal::InstructionBase::kRegisterType, and v8::internal::kRsFieldMask.
Referenced by v8::internal::InstructionGetters< T >::IsMSABranchInstr().
RsFieldRawNoAssert()
template<class T >
int v8::internal::InstructionGetters< T >::RsFieldRawNoAssert () const [inline]
Definition at line 1560 of file constants-mips64.h.
                                        {
    return this->InstructionBits() & kRsFieldMask;
  }
References v8::internal::kRsFieldMask.
RsValue()
template<class T >
int v8::internal::InstructionGetters< T >::RsValue () const [inline]
Definition at line 1457 of file constants-mips64.h.
                             {
    DCHECK(this->InstructionType() == InstructionBase::kRegisterType ||
           this->InstructionType() == InstructionBase::kImmediateType);
    return this->Bits(kRsShift + kRsBits - 1, kRsShift);
  }
References v8::internal::DCHECK(), v8::internal::InstructionBase::kImmediateType, v8::internal::InstructionBase::kRegisterType, v8::internal::kRsBits, and v8::internal::kRsShift.
Referenced by v8::internal::InstructionGetters< T >::SecondaryValue().
RtFieldRaw()
template<class T >
int v8::internal::InstructionGetters< T >::RtFieldRaw () const [inline]
Definition at line 1564 of file constants-mips64.h.
                                {
    DCHECK(this->InstructionType() == InstructionBase::kRegisterType ||
           this->InstructionType() == InstructionBase::kImmediateType);
    return this->InstructionBits() & kRtFieldMask;
  }
References v8::internal::DCHECK(), v8::internal::InstructionBase::kImmediateType, v8::internal::InstructionBase::kRegisterType, and v8::internal::kRtFieldMask.
RtValue()
template<class T >
int v8::internal::InstructionGetters< T >::RtValue () const [inline]
Definition at line 1463 of file constants-mips64.h.
                             {
    DCHECK(this->InstructionType() == InstructionBase::kRegisterType ||
           this->InstructionType() == InstructionBase::kImmediateType);
    return this->Bits(kRtShift + kRtBits - 1, kRtShift);
  }
References v8::internal::DCHECK(), v8::internal::InstructionBase::kImmediateType, v8::internal::InstructionBase::kRegisterType, v8::internal::kRtBits, and v8::internal::kRtShift.
Referenced by v8::internal::InstructionGetters< T >::SecondaryValue().
RvcFunct2BValue()
template<class T >
int v8::internal::InstructionGetters< T >::RvcFunct2BValue [inline]
Definition at line 201 of file base-constants-riscv.cc.
                                                        {
  DCHECK(this->IsShortInstruction());
  return this->Bits(kRvcFunct2BShift + kRvcFunct2Bits - 1, kRvcFunct2BShift);
}
References v8::internal::DCHECK(), v8::internal::kRvcFunct2Bits, and v8::internal::kRvcFunct2BShift.
Referenced by v8::internal::Decoder< V >::DecodeCBType().
RvcFunct2Value()
template<class T >
int v8::internal::InstructionGetters< T >::RvcFunct2Value [inline]
Definition at line 195 of file base-constants-riscv.cc.
                                                       {
  DCHECK(this->IsShortInstruction());
  return this->Bits(kRvcFunct2Shift + kRvcFunct2Bits - 1, kRvcFunct2Shift);
}
References v8::internal::DCHECK(), v8::internal::kRvcFunct2Bits, and v8::internal::kRvcFunct2Shift.
RvcFunct3Value()
template<class T >
int v8::internal::InstructionGetters< T >::RvcFunct3Value [inline]
Definition at line 189 of file base-constants-riscv.cc.
                                                       {
  DCHECK(this->IsShortInstruction());
  return this->Bits(kRvcFunct3Shift + kRvcFunct3Bits - 1, kRvcFunct3Shift);
}
References v8::internal::DCHECK(), v8::internal::kRvcFunct3Bits, and v8::internal::kRvcFunct3Shift.
RvcFunct4Value()
template<class T >
int v8::internal::InstructionGetters< T >::RvcFunct4Value [inline]
Definition at line 183 of file base-constants-riscv.cc.
                                                       {
  DCHECK(this->IsShortInstruction());
  return this->Bits(kRvcFunct4Shift + kRvcFunct4Bits - 1, kRvcFunct4Shift);
}
References v8::internal::DCHECK(), v8::internal::kRvcFunct4Bits, and v8::internal::kRvcFunct4Shift.
Referenced by v8::internal::Decoder< V >::DecodeCRType().
RvcFunct6Value()
template<class T >
int v8::internal::InstructionGetters< T >::RvcFunct6Value [inline]
Definition at line 177 of file base-constants-riscv.cc.
                                                       {
  DCHECK(this->IsShortInstruction());
  return this->Bits(kRvcFunct6Shift + kRvcFunct6Bits - 1, kRvcFunct6Shift);
}
References v8::internal::DCHECK(), v8::internal::kRvcFunct6Bits, and v8::internal::kRvcFunct6Shift.
RvcImm11CJValue()
template<class T >
int v8::internal::InstructionGetters< T >::RvcImm11CJValue () const [inline]
Definition at line 1122 of file base-constants-riscv.h.
                                     {
    DCHECK(this->IsShortInstruction());
    // | funct3 | [11|4|9:8|10|6|7|3:1|5] | opcode |
    // 15 12 2
    uint32_t Bits = this->InstructionBits();
    int32_t imm12 = ((Bits & 0x4) << 3) | ((Bits & 0x38) >> 2) |
                    ((Bits & 0x40) << 1) | ((Bits & 0x80) >> 1) |
                    ((Bits & 0x100) << 2) | ((Bits & 0x600) >> 1) |
                    ((Bits & 0x800) >> 7) | ((Bits & 0x1000) >> 1);
    return imm12 << 20 >> 20;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::Decoder< V >::PrintRvcImm11CJ(), and v8::internal::Assembler::target_at().
RvcImm5DValue()
template<class T >
int v8::internal::InstructionGetters< T >::RvcImm5DValue () const [inline]
Definition at line 1113 of file base-constants-riscv.h.
                                   {
    DCHECK(this->IsShortInstruction());
    // | funct3 | imm[5:3] | rs1 | imm[7:6] | rd | opcode |
    // 15 12 10 6 4 2
    uint32_t Bits = this->InstructionBits();
    int32_t imm8 = ((Bits & 0x1c00) >> 7) | ((Bits & 0x60) << 1);
    return imm8;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::Decoder< V >::PrintRvcImm5D().
RvcImm5WValue()
template<class T >
int v8::internal::InstructionGetters< T >::RvcImm5WValue () const [inline]
Definition at line 1103 of file base-constants-riscv.h.
                                   {
    DCHECK(this->IsShortInstruction());
    // | funct3 | imm[5:3] | rs1 | imm[2|6] | rd | opcode |
    // 15 12 10 6 4 2
    uint32_t Bits = this->InstructionBits();
    int32_t imm7 =
        ((Bits & 0x1c00) >> 7) | ((Bits & 0x40) >> 4) | ((Bits & 0x20) << 1);
    return imm7;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::Decoder< V >::PrintRvcImm5W().
RvcImm6Addi16spValue()
template<class T >
int v8::internal::InstructionGetters< T >::RvcImm6Addi16spValue () const [inline]
Definition at line 1034 of file base-constants-riscv.h.
                                          {
    DCHECK(this->IsShortInstruction());
    // | funct3 | nzimm[9] | 2 | nzimm[4|6|8:7|5] | opcode |
    // 15 12 6 2
    uint32_t Bits = this->InstructionBits();
    int32_t imm10 = ((Bits & 0x1000) >> 3) | ((Bits & 0x40) >> 2) |
                    ((Bits & 0x20) << 1) | ((Bits & 0x18) << 4) |
                    ((Bits & 0x4) << 3);
    DCHECK_NE(imm10, 0);
    return imm10 << 22 >> 22;
  }
References v8::internal::DCHECK(), and DCHECK_NE.
Referenced by v8::internal::Decoder< V >::PrintRvcImm6Addi16sp().
RvcImm6LdspValue()
template<class T >
int v8::internal::InstructionGetters< T >::RvcImm6LdspValue () const [inline]
Definition at line 1075 of file base-constants-riscv.h.
                                      {
    DCHECK(this->IsShortInstruction());
    // | funct3 | uimm[5] | rs1 | uimm[4:3|8:6] | opcode |
    // 15 12 6 2
    uint32_t Bits = this->InstructionBits();
    int32_t imm9 =
        ((Bits & 0x1000) >> 7) | ((Bits & 0x60) >> 2) | ((Bits & 0x1c) << 4);
    return imm9;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::Decoder< V >::PrintRvcImm6Ldsp().
RvcImm6LwspValue()
template<class T >
int v8::internal::InstructionGetters< T >::RvcImm6LwspValue () const [inline]
Definition at line 1065 of file base-constants-riscv.h.
                                      {
    DCHECK(this->IsShortInstruction());
    // | funct3 | uimm[5] | rs1 | uimm[4:2|7:6] | opcode |
    // 15 12 6 2
    uint32_t Bits = this->InstructionBits();
    int32_t imm8 =
        ((Bits & 0x1000) >> 7) | ((Bits & 0x70) >> 2) | ((Bits & 0xc) << 4);
    return imm8;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::Decoder< V >::PrintRvcImm6Lwsp().
RvcImm6SdspValue()
template<class T >
int v8::internal::InstructionGetters< T >::RvcImm6SdspValue () const [inline]
Definition at line 1094 of file base-constants-riscv.h.
                                      {
    DCHECK(this->IsShortInstruction());
    // | funct3 | uimm[5:3|8:6] | rs2 | opcode |
    // 15 12 7
    uint32_t Bits = this->InstructionBits();
    int32_t imm9 = ((Bits & 0x1c00) >> 7) | ((Bits & 0x380) >> 1);
    return imm9;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::Decoder< V >::PrintRvcImm6Sdsp().
RvcImm6SwspValue()
template<class T >
int v8::internal::InstructionGetters< T >::RvcImm6SwspValue () const [inline]
Definition at line 1085 of file base-constants-riscv.h.
                                      {
    DCHECK(this->IsShortInstruction());
    // | funct3 | uimm[5:2|7:6] | rs2 | opcode |
    // 15 12 7
    uint32_t Bits = this->InstructionBits();
    int32_t imm8 = ((Bits & 0x1e00) >> 7) | ((Bits & 0x180) >> 1);
    return imm8;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::Decoder< V >::PrintRvcImm6Swsp().
RvcImm6Value()
template<class T >
int v8::internal::InstructionGetters< T >::RvcImm6Value () const [inline]
Definition at line 1025 of file base-constants-riscv.h.
                                  {
    DCHECK(this->IsShortInstruction());
    // | funct3 | imm[5] | rs1/rd | imm[4:0] | opcode |
    // 15 12 6 2
    uint32_t Bits = this->InstructionBits();
    int32_t imm6 = ((Bits & 0x1000) >> 7) | ((Bits & 0x7c) >> 2);
    return imm6 << 26 >> 26;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::Decoder< V >::PrintRvcImm6(), v8::internal::Decoder< V >::PrintRvcImm6U(), and v8::internal::InstructionGetters< T >::RvcShamt6().
RvcImm8Addi4spnValue()
template<class T >
int v8::internal::InstructionGetters< T >::RvcImm8Addi4spnValue () const [inline]
Definition at line 1046 of file base-constants-riscv.h.
                                          {
    DCHECK(this->IsShortInstruction());
    // | funct3 | nzimm[11] | rd' | opcode |
    // 15 13 5 2
    uint32_t Bits = this->InstructionBits();
    int32_t uimm10 = ((Bits & 0x20) >> 2) | ((Bits & 0x40) >> 4) |
                     ((Bits & 0x780) >> 1) | ((Bits & 0x1800) >> 7);
    DCHECK_NE(uimm10, 0);
    return uimm10;
  }
References v8::internal::DCHECK(), and DCHECK_NE.
Referenced by v8::internal::Decoder< V >::PrintRvcImm8Addi4spn().
RvcImm8BValue()
template<class T >
int v8::internal::InstructionGetters< T >::RvcImm8BValue () const [inline]
Definition at line 1134 of file base-constants-riscv.h.
                                   {
    DCHECK(this->IsShortInstruction());
    // | funct3 | imm[8|4:3] | rs1` | imm[7:6|2:1|5] | opcode |
    // 15 12 10 7 2
    uint32_t Bits = this->InstructionBits();
    int32_t imm9 = ((Bits & 0x4) << 3) | ((Bits & 0x18) >> 2) |
                   ((Bits & 0x60) << 1) | ((Bits & 0xc00) >> 7) |
                   ((Bits & 0x1000) >> 4);
    return imm9 << 23 >> 23;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::Decoder< V >::PrintRvcImm8B(), and v8::internal::Assembler::target_at().
RvcOpcode()
template<class T >
int v8::internal::InstructionGetters< T >::RvcOpcode () const [inline]
Definition at line 822 of file base-constants-riscv.h.
                               {
    DCHECK(this->IsShortInstruction());
    return this->InstructionBits() & kRvcOpcodeMask;
  }
References v8::internal::DCHECK(), and v8::internal::kRvcOpcodeMask.
Referenced by v8::internal::Decoder< V >::DecodeCBType(), v8::internal::Decoder< V >::DecodeCIType(), v8::internal::Decoder< V >::DecodeCIWType(), v8::internal::Decoder< V >::DecodeCJType(), v8::internal::Decoder< V >::DecodeCLType(), v8::internal::Decoder< V >::DecodeCSSType(), and v8::internal::Decoder< V >::DecodeCSType().
RvcRdValue()
template<class T >
int v8::internal::InstructionGetters< T >::RvcRdValue
Definition at line 153 of file base-constants-riscv.cc.
                                            {
  DCHECK(this->IsShortInstruction());
  return this->Bits(kRvcRdShift + kRvcRdBits - 1, kRvcRdShift);
}
References v8::internal::DCHECK(), v8::internal::kRvcRdBits, and v8::internal::kRvcRdShift.
Referenced by v8::internal::Decoder< V >::DecodeCIType(), v8::internal::Decoder< V >::DecodeCRType(), v8::internal::Decoder< V >::FormatRvcRegister(), and v8::internal::InstructionGetters< T >::RvcRs1Value().
RvcRs1sValue()
template<class T >
int v8::internal::InstructionGetters< T >::RvcRs1sValue
Definition at line 165 of file base-constants-riscv.cc.
                                              {
  DCHECK(this->IsShortInstruction());
  return 0b1000 + this->Bits(kRvcRs1sShift + kRvcRs1sBits - 1, kRvcRs1sShift);
}
References v8::internal::DCHECK(), v8::internal::kRvcRs1sBits, and v8::internal::kRvcRs1sShift.
Referenced by v8::internal::Decoder< V >::FormatRvcRegister().
RvcRs1Value()
template<class T >
int v8::internal::InstructionGetters< T >::RvcRs1Value () const [inline]
Definition at line 885 of file base-constants-riscv.h.
{ return this->RvcRdValue(); }
References v8::internal::InstructionGetters< T >::RvcRdValue().
Referenced by v8::internal::Decoder< V >::DecodeCRType(), and v8::internal::Decoder< V >::FormatRvcRegister().
RvcRs2sValue()
template<class T >
int v8::internal::InstructionGetters< T >::RvcRs2sValue
Definition at line 171 of file base-constants-riscv.cc.
                                              {
  DCHECK(this->IsShortInstruction());
  return 0b1000 + this->Bits(kRvcRs2sShift + kRvcRs2sBits - 1, kRvcRs2sShift);
}
References v8::internal::DCHECK(), v8::internal::kRvcRs2sBits, and v8::internal::kRvcRs2sShift.
Referenced by v8::internal::Decoder< V >::FormatRvcRegister().
RvcRs2Value()
template<class T >
int v8::internal::InstructionGetters< T >::RvcRs2Value
Definition at line 159 of file base-constants-riscv.cc.
                                             {
  DCHECK(this->IsShortInstruction());
  return this->Bits(kRvcRs2Shift + kRvcRs2Bits - 1, kRvcRs2Shift);
}
References v8::internal::DCHECK(), v8::internal::kRvcRs2Bits, and v8::internal::kRvcRs2Shift.
Referenced by v8::internal::Decoder< V >::DecodeCRType(), and v8::internal::Decoder< V >::FormatRvcRegister().
RvcShamt6()
template<class T >
int v8::internal::InstructionGetters< T >::RvcShamt6 () const [inline]
Definition at line 1057 of file base-constants-riscv.h.
                               {
    DCHECK(this->IsShortInstruction());
    // | funct3 | nzuimm[5] | rs1/rd | nzuimm[4:0] | opcode |
    // 15 12 6 2
    int32_t imm6 = this->RvcImm6Value();
    return imm6 & 0x3f;
  }
References v8::internal::DCHECK(), and v8::internal::InstructionGetters< T >::RvcImm6Value().
Referenced by v8::internal::Decoder< V >::PrintRvcShamt().
RvvLMUL()
template<class T >
const char* v8::internal::InstructionGetters< T >::RvvLMUL () const [inline]
Definition at line 1218 of file base-constants-riscv.h.
                                     {
    uint32_t vlmul = this->RvvVlmul();
    switch (vlmul) {
#define CAST_VLMUL(name) \
  case name: \
    return #name;
      RVV_LMUL(CAST_VLMUL)
      default:
        return "unknown";
#undef CAST_VLMUL
    }
  }
References CAST_VLMUL, RVV_LMUL, and v8::internal::InstructionGetters< T >::RvvVlmul().
Referenced by v8::internal::Decoder< V >::PrintRvvLMUL().
RvvSEW()
template<class T >
const char* v8::internal::InstructionGetters< T >::RvvSEW () const [inline]
Definition at line 1205 of file base-constants-riscv.h.
                                    {
    uint32_t vsew = this->RvvVsew();
    switch (vsew) {
#define CAST_VSEW(name) \
  case name: \
    return #name;
      RVV_SEW(CAST_VSEW)
      default:
        return "unknown";
#undef CAST_VSEW
    }
  }
References CAST_VSEW, RVV_SEW, and v8::internal::InstructionGetters< T >::RvvVsew().
Referenced by v8::internal::Decoder< V >::PrintRvvSEW().
RvvSimm5()
template<class T >
int32_t v8::internal::InstructionGetters< T >::RvvSimm5 () const [inline]
Definition at line 1234 of file base-constants-riscv.h.
                                  {
    DCHECK(this->InstructionType() == InstructionBase::kVType);
    return sext(this->Bits(kRvvImm5Shift + kRvvImm5Bits - 1, kRvvImm5Shift),
                kRvvImm5Bits);
  }
References v8::internal::DCHECK(), v8::internal::kRvvImm5Bits, v8::internal::kRvvImm5Shift, v8::internal::InstructionBase::kVType, and sext.
Referenced by v8::internal::Decoder< V >::PrintRvvSimm5().
Rvvuimm()
template<class T >
uint32_t v8::internal::InstructionGetters< T >::Rvvuimm
Definition at line 224 of file base-constants-riscv.cc.
                                              {
  DCHECK_EQ(
      this->InstructionBits() & (kBaseOpcodeMask | kFunct3Mask | 0xC0000000),
      RO_V_VSETIVLI);
  uint32_t Bits = this->InstructionBits();
  uint32_t uimm = Bits & kRvvUimmMask;
  return uimm >> kRvvUimmShift;
}
References DCHECK_EQ, v8::internal::kBaseOpcodeMask, v8::internal::kFunct3Mask, v8::internal::kRvvUimmMask, v8::internal::kRvvUimmShift, and v8::internal::RO_V_VSETIVLI.
RvvUimm5()
template<class T >
uint32_t v8::internal::InstructionGetters< T >::RvvUimm5 () const [inline]
Definition at line 1240 of file base-constants-riscv.h.
                                   {
    DCHECK(this->InstructionType() == InstructionBase::kVType);
    uint32_t imm = this->Bits(kRvvImm5Shift + kRvvImm5Bits - 1, kRvvImm5Shift);
    return zext(imm, kRvvImm5Bits);
  }
References v8::internal::DCHECK(), v8::internal::kRvvImm5Bits, v8::internal::kRvvImm5Shift, v8::internal::InstructionBase::kVType, and zext.
Referenced by v8::internal::Decoder< V >::PrintRvvUimm5().
RvvVlmul()
template<class T >
uint32_t v8::internal::InstructionGetters< T >::RvvVlmul () const [inline]
Definition at line 1192 of file base-constants-riscv.h.
                                   {
    uint32_t zimm = this->Rvvzimm();
    uint32_t vlmul = zimm & 0x7;
    return vlmul;
  }
References v8::internal::InstructionGetters< T >::Rvvzimm().
Referenced by v8::internal::InstructionGetters< T >::RvvLMUL().
RvvVM()
template<class T >
uint8_t v8::internal::InstructionGetters< T >::RvvVM () const [inline]
Definition at line 1198 of file base-constants-riscv.h.
                               {
    DCHECK(this->InstructionType() == InstructionBase::kVType ||
           this->InstructionType() == InstructionBase::kIType ||
           this->InstructionType() == InstructionBase::kSType);
    return this->Bits(kRvvVmShift + kRvvVmBits - 1, kRvvVmShift);
  }
References v8::internal::DCHECK(), v8::internal::InstructionBase::kIType, v8::internal::kRvvVmBits, v8::internal::kRvvVmShift, v8::internal::InstructionBase::kSType, and v8::internal::InstructionBase::kVType.
Referenced by v8::internal::Decoder< V >::DecodeRvvFVF(), v8::internal::Decoder< V >::DecodeRvvIVI(), v8::internal::Decoder< V >::DecodeRvvIVV(), v8::internal::Decoder< V >::DecodeRvvIVX(), and v8::internal::Decoder< V >::PrintRvvVm().
RvvVsew()
template<class T >
uint32_t v8::internal::InstructionGetters< T >::RvvVsew () const [inline]
Definition at line 1186 of file base-constants-riscv.h.
                                  {
    uint32_t zimm = this->Rvvzimm();
    uint32_t vsew = (zimm >> 3) & 0x7;
    return vsew;
  }
References v8::internal::InstructionGetters< T >::Rvvzimm().
Referenced by v8::internal::InstructionGetters< T >::RvvSEW().
Rvvzimm()
template<class T >
uint32_t v8::internal::InstructionGetters< T >::Rvvzimm
Definition at line 207 of file base-constants-riscv.cc.
                                              {
  if ((this->InstructionBits() &
       (kBaseOpcodeMask | kFunct3Mask | 0x80000000)) == RO_V_VSETVLI) {
    uint32_t Bits = this->InstructionBits();
    uint32_t zimm = Bits & kRvvZimmMask;
    return zimm >> kRvvZimmShift;
  } else {
    DCHECK_EQ(
        this->InstructionBits() & (kBaseOpcodeMask | kFunct3Mask | 0xC0000000),
        RO_V_VSETIVLI);
    uint32_t Bits = this->InstructionBits();
    uint32_t zimm = Bits & kRvvZimmMask;
    return (zimm >> kRvvZimmShift) & 0x3FF;
  }
}
References DCHECK_EQ, v8::internal::kBaseOpcodeMask, v8::internal::kFunct3Mask, v8::internal::kRvvZimmMask, v8::internal::kRvvZimmShift, v8::internal::RO_V_VSETIVLI, and v8::internal::RO_V_VSETVLI.
Referenced by v8::internal::InstructionGetters< T >::RvvVlmul(), and v8::internal::InstructionGetters< T >::RvvVsew().
Sa2Value()
template<class T >
int v8::internal::InstructionGetters< T >::Sa2Value () const [inline]
Definition at line 778 of file constants-loong64.h.
                              {
    return this->Bits(kSaShift + kSa2Bits - 1, kSaShift);
  }
References v8::internal::kSa2Bits, and v8::internal::kSaShift.
Sa3Value()
template<class T >
int v8::internal::InstructionGetters< T >::Sa3Value () const [inline]
Definition at line 782 of file constants-loong64.h.
                              {
    return this->Bits(kSaShift + kSa3Bits - 1, kSaShift);
  }
References v8::internal::kSa3Bits, and v8::internal::kSaShift.
SaFieldRaw()
template<class T >
int v8::internal::InstructionGetters< T >::SaFieldRaw () const [inline]
Definition at line 1575 of file constants-mips64.h.
                                {
    return this->InstructionBits() & kSaFieldMask;
  }
References v8::internal::kSaFieldMask.
SaValue()
template<class T >
int v8::internal::InstructionGetters< T >::SaValue () const [inline]
Definition at line 1479 of file constants-mips64.h.
                             {
    DCHECK_EQ(this->InstructionType(), InstructionBase::kRegisterType);
    return this->Bits(kSaShift + kSaBits - 1, kSaShift);
  }
References DCHECK_EQ, v8::internal::InstructionBase::kRegisterType, v8::internal::kSaBits, and v8::internal::kSaShift.
SecondaryValue()
template<class T >
int v8::internal::InstructionGetters< T >::SecondaryValue () const [inline]
Definition at line 1584 of file constants-mips64.h.
                                    {
    Opcode op = this->OpcodeFieldRaw();
    switch (op) {
      case SPECIAL:
      case SPECIAL2:
        return FunctionValue();
      case COP1:
        return RsValue();
      case REGIMM:
        return RtValue();
      default:
        return nullptrSF;
    }
  }
References v8::internal::COP1, v8::internal::InstructionGetters< T >::FunctionValue(), v8::internal::nullptrSF, v8::internal::InstructionGetters< T >::OpcodeFieldRaw(), v8::internal::REGIMM, v8::internal::InstructionGetters< T >::RsValue(), v8::internal::InstructionGetters< T >::RtValue(), v8::internal::SPECIAL, and v8::internal::SPECIAL2.
Shamt()
template<class T >
int v8::internal::InstructionGetters< T >::Shamt () const [inline]
Definition at line 1000 of file base-constants-riscv.h.
                           {
    // Valid only for shift instructions (SLLI, SRLI, SRAI)
    DCHECK(((this->InstructionBits() & kBaseOpcodeMask) == OP_IMM ||
            (this->InstructionBits() & kBaseOpcodeMask) == OP_IMM_32) &&
           (this->Funct3Value() == 0b001 || this->Funct3Value() == 0b101));
    // | 0A0000 | shamt | rs1 | funct3 | rd | opcode |
    // 31 25 20
    return this->Bits(kImm12Shift + 5, kImm12Shift);
  }
References v8::internal::DCHECK(), v8::internal::InstructionGetters< T >::Funct3Value(), v8::internal::kBaseOpcodeMask, v8::internal::kImm12Shift, v8::internal::OP_IMM, and v8::internal::OP_IMM_32.
Referenced by v8::internal::Decoder< V >::DecodeIType(), and v8::internal::Decoder< V >::PrintShamt().
Shamt32()
template<class T >
int v8::internal::InstructionGetters< T >::Shamt32 () const [inline]
Definition at line 1010 of file base-constants-riscv.h.
                             {
    // Valid only for shift instructions (SLLIW, SRLIW, SRAIW)
#ifdef V8_TARGET_ARCH_RISCV32
    DCHECK(((this->InstructionBits() & kBaseOpcodeMask) == OP_IMM_32 ||
            (this->InstructionBits() & kBaseOpcodeMask) == OP_IMM) &&
           (this->Funct3Value() == 0b001 || this->Funct3Value() == 0b101));
#else
    DCHECK((this->InstructionBits() & kBaseOpcodeMask) == OP_IMM_32 &&
           (this->Funct3Value() == 0b001 || this->Funct3Value() == 0b101));
#endif
    // | 0A00000 | shamt | rs1 | funct3 | rd | opcode |
    // 31 24 20
    return this->Bits(kImm12Shift + 4, kImm12Shift);
  }
References v8::internal::DCHECK(), v8::internal::InstructionGetters< T >::Funct3Value(), v8::internal::kBaseOpcodeMask, v8::internal::kImm12Shift, v8::internal::OP_IMM, and v8::internal::OP_IMM_32.
Referenced by v8::internal::Decoder< V >::PrintShamt32().
Si12Value()
template<class T >
int v8::internal::InstructionGetters< T >::Si12Value () const [inline]
Definition at line 818 of file constants-loong64.h.
                               {
    return this->Bits(kSi12Shift + kSi12Bits - 1, kSi12Shift);
  }
References v8::internal::kSi12Bits, and v8::internal::kSi12Shift.
Si14Value()
template<class T >
int v8::internal::InstructionGetters< T >::Si14Value () const [inline]
Definition at line 822 of file constants-loong64.h.
                               {
    return this->Bits(kSi14Shift + kSi14Bits - 1, kSi14Shift);
  }
References v8::internal::kSi14Bits, and v8::internal::kSi14Shift.
Si16Value()
template<class T >
int v8::internal::InstructionGetters< T >::Si16Value () const [inline]
Definition at line 826 of file constants-loong64.h.
                               {
    return this->Bits(kSi16Shift + kSi16Bits - 1, kSi16Shift);
  }
References v8::internal::kSi16Bits, and v8::internal::kSi16Shift.
Si20Value()
template<class T >
int v8::internal::InstructionGetters< T >::Si20Value () const [inline]
Definition at line 830 of file constants-loong64.h.
                               {
    return this->Bits(kSi20Shift + kSi20Bits - 1, kSi20Shift);
  }
References v8::internal::kSi20Bits, and v8::internal::kSi20Shift.
StoreOffset()
template<class T >
int v8::internal::InstructionGetters< T >::StoreOffset () const [inline]
Definition at line 965 of file base-constants-riscv.h.
                                 {
    DCHECK(this->InstructionType() == InstructionBase::kSType);
    // | imm[11:5] | rs2 | rs1 | funct3 | imm[4:0] | opcode |
    // 31 25 11 7
    uint32_t Bits = this->InstructionBits();
    int16_t imm12 = ((Bits & 0xf80) >> 7) | ((Bits & 0xfe000000) >> 20);
    return imm12 << 20 >> 20;
  }
References v8::internal::DCHECK(), and v8::internal::InstructionBase::kSType.
Referenced by v8::internal::Decoder< V >::PrintStoreOffset().
Ui12Value()
template<class T >
int v8::internal::InstructionGetters< T >::Ui12Value () const [inline]
Definition at line 794 of file constants-loong64.h.
                               {
    return this->Bits(kUi12Shift + kUi12Bits - 1, kUi12Shift);
  }
References v8::internal::kUi12Bits, and v8::internal::kUi12Shift.
Ui5Value()
template<class T >
int v8::internal::InstructionGetters< T >::Ui5Value () const [inline]
Definition at line 786 of file constants-loong64.h.
                              {
    return this->Bits(kUi5Shift + kUi5Bits - 1, kUi5Shift);
  }
References v8::internal::kUi5Bits, and v8::internal::kUi5Shift.
Ui6Value()
template<class T >
int v8::internal::InstructionGetters< T >::Ui6Value () const [inline]
Definition at line 790 of file constants-loong64.h.
                              {
    return this->Bits(kUi6Shift + kUi6Bits - 1, kUi6Shift);
  }
References v8::internal::kUi6Bits, and v8::internal::kUi6Shift.
VdValue()
template<class T >
int v8::internal::InstructionGetters< T >::VdValue () const [inline]
Definition at line 867 of file base-constants-riscv.h.
                             {
    DCHECK(this->InstructionType() == InstructionBase::kVType ||
           this->InstructionType() == InstructionBase::kIType ||
           this->InstructionType() == InstructionBase::kSType);
    return this->Bits(kVdShift + kVdBits - 1, kVdShift);
  }
References v8::internal::DCHECK(), v8::internal::InstructionBase::kIType, v8::internal::InstructionBase::kSType, v8::internal::kVdBits, v8::internal::kVdShift, and v8::internal::InstructionBase::kVType.
vl_vs_width()
template<class T >
int v8::internal::InstructionGetters< T >::vl_vs_width () [inline]
Definition at line 1145 of file base-constants-riscv.h.
                           {
    int width = 0;
    if ((this->InstructionBits() & kBaseOpcodeMask) != LOAD_FP &&
        (this->InstructionBits() & kBaseOpcodeMask) != STORE_FP)
      return -1;
    switch (this->InstructionBits() & (kRvvWidthMask | kRvvMewMask)) {
      case 0x0:
        width = 8;
        break;
      case 0x00005000:
        width = 16;
        break;
      case 0x00006000:
        width = 32;
        break;
      case 0x00007000:
        width = 64;
        break;
      case 0x10000000:
        width = 128;
        break;
      case 0x10005000:
        width = 256;
        break;
      case 0x10006000:
        width = 512;
        break;
      case 0x10007000:
        width = 1024;
        break;
      default:
        width = -1;
        break;
    }
    return width;
  }
References v8::internal::kBaseOpcodeMask, v8::internal::kRvvMewMask, v8::internal::kRvvWidthMask, v8::internal::LOAD_FP, and v8::internal::STORE_FP.
Referenced by v8::internal::Decoder< V >::DecodeIType(), v8::internal::Decoder< V >::DecodeRvvVL(), v8::internal::Decoder< V >::DecodeRvvVS(), and v8::internal::Decoder< V >::DecodeSType().
Vs1Value()
template<class T >
int v8::internal::InstructionGetters< T >::Vs1Value () const [inline]
Definition at line 853 of file base-constants-riscv.h.
                              {
    DCHECK(this->InstructionType() == InstructionBase::kVType ||
           this->InstructionType() == InstructionBase::kIType ||
           this->InstructionType() == InstructionBase::kSType);
    return this->Bits(kVs1Shift + kVs1Bits - 1, kVs1Shift);
  }
References v8::internal::DCHECK(), v8::internal::InstructionBase::kIType, v8::internal::InstructionBase::kSType, v8::internal::kVs1Bits, v8::internal::kVs1Shift, and v8::internal::InstructionBase::kVType.
Referenced by v8::internal::Decoder< V >::DecodeRvvFVV(), v8::internal::Decoder< V >::DecodeRvvMVV(), and v8::internal::Decoder< V >::PrintVs1().
Vs2Value()
template<class T >
int v8::internal::InstructionGetters< T >::Vs2Value () const [inline]
Definition at line 860 of file base-constants-riscv.h.
                              {
    DCHECK(this->InstructionType() == InstructionBase::kVType ||
           this->InstructionType() == InstructionBase::kIType ||
           this->InstructionType() == InstructionBase::kSType);
    return this->Bits(kVs2Shift + kVs2Bits - 1, kVs2Shift);
  }
References v8::internal::DCHECK(), v8::internal::InstructionBase::kIType, v8::internal::InstructionBase::kSType, v8::internal::kVs2Bits, v8::internal::kVs2Shift, and v8::internal::InstructionBase::kVType.
Referenced by v8::internal::Decoder< V >::DecodeRvvFVF(), v8::internal::Decoder< V >::DecodeRvvFVV(), v8::internal::Decoder< V >::DecodeRvvMVX(), and v8::internal::Decoder< V >::PrintVs2().
WdValue()
template<class T >
int v8::internal::InstructionGetters< T >::WdValue () const [inline]
Definition at line 1511 of file constants-mips64.h.
                             {
    return this->Bits(kWdShift + kWdBits - 1, kWdShift);
  }
References v8::internal::kWdBits, and v8::internal::kWdShift.
WsValue()
template<class T >
int v8::internal::InstructionGetters< T >::WsValue () const [inline]
Definition at line 1515 of file constants-mips64.h.
                             {
    return this->Bits(kWsShift + kWsBits - 1, kWsShift);
  }
References v8::internal::kWsBits, and v8::internal::kWsShift.
WtValue()
template<class T >
int v8::internal::InstructionGetters< T >::WtValue () const [inline]
Definition at line 1519 of file constants-mips64.h.
                             {
    return this->Bits(kWtShift + kWtBits - 1, kWtShift);
  }
References v8::internal::kWtBits, and v8::internal::kWtShift.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/loong64/constants-loong64.h
/mnt/V8SourceCode/src/codegen/mips64/constants-mips64.h
/mnt/V8SourceCode/src/codegen/riscv/base-constants-riscv.h
/mnt/V8SourceCode/src/codegen/riscv/base-constants-riscv.cc