v8::internal::Map Class Reference
#include <map.h>
Classes
struct Bits1
struct Bits2
struct Bits3
class BodyDescriptor
class FieldCounts
Public Member Functions
int GetInObjectPropertiesStartInWords () const
void SetInObjectPropertiesStartInWords (int value)
int GetInObjectProperties () const
int GetConstructorFunctionIndex () const
void SetConstructorFunctionIndex (int value)
InstanceType instance_type () const
void set_instance_type (InstanceType value)
int UsedInstanceSize () const
bool HasOutOfObjectProperties () const
int UnusedPropertyFields () const
int UnusedInObjectProperties () const
void SetInObjectUnusedPropertyFields (int unused_property_fields)
void SetOutOfObjectUnusedPropertyFields (int unused_property_fields)
void CopyUnusedPropertyFields (Tagged< Map > map)
void CopyUnusedPropertyFieldsAdjustedForInstanceSize (Tagged< Map > map)
void AccountAddedPropertyField ()
void AccountAddedOutOfObjectPropertyField (int unused_in_property_array)
void clear_padding ()
void StartInobjectSlackTracking ()
bool IsInobjectSlackTrackingInProgress () const
void InobjectSlackTrackingStep (Isolate *isolate)
int ComputeMinObjectSlack (Isolate *isolate)
int InstanceSizeFromSlack (int slack) const
bool is_abandoned_prototype_map () const
bool has_prototype_info () const
bool TryGetPrototypeInfo (Tagged< PrototypeInfo > *result) const
bool has_fast_smi_elements () const
bool has_fast_object_elements () const
bool has_fast_smi_or_object_elements () const
bool has_fast_double_elements () const
bool has_fast_elements () const
bool has_fast_packed_elements () const
bool has_sloppy_arguments_elements () const
bool has_fast_sloppy_arguments_elements () const
bool has_fast_string_wrapper_elements () const
bool has_typed_array_or_rab_gsab_typed_array_elements () const
bool has_any_typed_array_or_wasm_array_elements () const
bool has_dictionary_elements () const
bool has_any_nonextensible_elements () const
bool has_nonextensible_elements () const
bool has_sealed_elements () const
bool has_frozen_elements () const
bool has_shared_array_elements () const
bool IsDetached (Isolate *isolate) const
bool ShouldCheckForReadOnlyElementsInPrototypeChain (Isolate *isolate)
Tagged< Map > ElementsTransitionMap (Isolate *isolate, ConcurrencyMode cmode)
Tagged< FixedArrayBase > GetInitialElements () const
DECL_ACCESSORS (raw_transitions, Tagged< UnionOf< Smi, MaybeWeak< Map >, TransitionArray >>) DECL_RELEASE_ACQUIRE_ACCESSORS(raw_transitions
Tagged< UnionOf< Smi, MaybeWeak< Map >, TransitionArray > > DECL_RELEASE_ACQUIRE_ACCESSORS (prototype_info, Tagged< UnionOf< Smi, PrototypeInfo >>) static DirectHandle< PrototypeInfo > GetOrCreatePrototypeInfo(DirectHandle< JSObject > prototype
bool should_be_fast_prototype_map () const
Tagged< Map > GetPrototypeChainRootMap (Isolate *isolate) const
V8_EXPORT_PRIVATE Tagged< Map > FindRootMap (PtrComprCageBase cage_base) const
V8_EXPORT_PRIVATE Tagged< Map > FindFieldOwner (PtrComprCageBase cage_base, InternalIndex descriptor) const
int GetInObjectPropertyOffset (int index) const
FieldCounts GetFieldCounts () const
int NumberOfFields (ConcurrencyMode cmode) const
bool InstancesNeedRewriting (Tagged< Map > target, ConcurrencyMode cmode) const
bool InstancesNeedRewriting (Tagged< Map > target, int target_number_of_fields, int target_inobject, int target_unused, int *old_number_of_fields, ConcurrencyMode cmode) const
void init_prototype_and_constructor_or_back_pointer (ReadOnlyRoots roots)
void SetConstructor (Tagged< Object > constructor, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
Tagged< Object > TryGetConstructor (PtrComprCageBase cage_base, int max_steps)
void SetBackPointer (Tagged< HeapObject > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
bool TryGetBackPointer (PtrComprCageBase cage_base, Tagged< Map > *back_pointer) const
V8_EXPORT_PRIVATE void SetInstanceDescriptors (Isolate *isolate, Tagged< DescriptorArray > descriptors, int number_of_own_descriptors, WriteBarrierMode barrier_mode=UPDATE_WRITE_BARRIER)
void UpdateDescriptors (Isolate *isolate, Tagged< DescriptorArray > descriptors, int number_of_own_descriptors)
void InitializeDescriptors (Isolate *isolate, Tagged< DescriptorArray > descriptors)
bool IsPrototypeValidityCellValid () const
bool BelongsToSameNativeContextAs (Tagged< Map > other_map) const
bool BelongsToSameNativeContextAs (Tagged< Context > context) const
Tagged< Name > GetLastDescriptorName (Isolate *isolate) const
PropertyDetails GetLastDescriptorDetails (Isolate *isolate) const
InternalIndex LastAdded () const
int NumberOfOwnDescriptors () const
void SetNumberOfOwnDescriptors (int number)
InternalIndex::Range IterateOwnDescriptors () const
Tagged< Cell > RetrieveDescriptorsPointer ()
bool OnlyHasSimpleProperties () const
int EnumLength () const
void SetEnumLength (int length)
void mark_unstable ()
bool is_stable () const
bool CanBeDeprecated () const
bool TooManyFastProperties (StoreOrigin store_origin) const
void AppendDescriptor (Isolate *isolate, Descriptor *desc)
int NextFreePropertyIndex () const
int NumberOfEnumerableProperties () const
int Hash (Isolate *isolate, Tagged< HeapObject > prototype)
V8_EXPORT_PRIVATE Tagged< Map > FindElementsKindTransitionedMap (Isolate *isolate, MapHandlesSpan candidates, ConcurrencyMode cmode)
bool CanTransition () const
bool IsMapInArrayPrototypeChain (Isolate *isolate) const
void MapPrint (std::ostream &os)
bool EquivalentToForNormalization (const Tagged< Map > other, ElementsKind elements_kind, Tagged< HeapObject > prototype, PropertyNormalizationMode mode) const
bool EquivalentToForNormalization (const Tagged< Map > other, PropertyNormalizationMode mode) const
void PrintMapDetails (std::ostream &os)
void NotifyLeafMapLayoutChange (Isolate *isolate)
bool CanHaveFastTransitionableElementsKind () const
uint8_t WasmByte1 () const
uint8_t WasmByte2 () const
void SetWasmByte1 (uint8_t value)
void SetWasmByte2 (uint8_t value)
Static Public Member Functions
static std::optional< Tagged< JSFunction > > GetConstructorFunction (Tagged< Map > map, Tagged< Context > native_context)
static DirectHandle< PrototypeInfo > GetOrCreatePrototypeInfo (DirectHandle< Map > prototype_map, Isolate *isolate)
static void SetShouldBeFastPrototypeMap (DirectHandle< Map > map, bool value, Isolate *isolate)
static bool TryGetValidityCellHolderMap (Tagged< Map > map, Isolate *isolate, Tagged< Map > *out_validity_cell_holder_map)
static Handle< UnionOf< Smi, Cell > > GetOrCreatePrototypeChainValidityCell (DirectHandle< Map > map, Isolate *isolate, DirectHandle< PrototypeInfo > *out_prototype_info=nullptr)
static bool IsPrototypeChainInvalidated (Tagged< Map > map)
static bool IsMostGeneralFieldType (Representation representation, Tagged< FieldType > field_type)
static void GeneralizeIfCanHaveTransitionableFastElementsKind (Isolate *isolate, InstanceType instance_type, Representation *representation, DirectHandle< FieldType > *field_type)
static V8_EXPORT_PRIVATE DirectHandle< Map > PrepareForDataProperty (Isolate *isolate, DirectHandle< Map > old_map, InternalIndex descriptor_number, PropertyConstness constness, DirectHandle< Object > value)
static V8_EXPORT_PRIVATE Handle< Map > Normalize (Isolate *isolate, DirectHandle< Map > map, ElementsKind new_elements_kind, DirectHandle< JSPrototype > new_prototype, PropertyNormalizationMode mode, bool use_cache, const char *reason)
static V8_EXPORT_PRIVATE Handle< Map > Normalize (Isolate *isolate, DirectHandle< Map > map, ElementsKind new_elements_kind, DirectHandle< JSPrototype > new_prototype, PropertyNormalizationMode mode, const char *reason)
static Handle< Map > Normalize (Isolate *isolate, DirectHandle< Map > fast_map, PropertyNormalizationMode mode, const char *reason)
static V8_EXPORT_PRIVATE void SetPrototype (Isolate *isolate, DirectHandle< Map > map, DirectHandle< JSPrototype > prototype, bool enable_prototype_setup_mode=true)
static V8_EXPORT_PRIVATE MaybeHandle< Map > TryUpdate (Isolate *isolate, Handle< Map > map) V8_WARN_UNUSED_RESULT
static V8_EXPORT_PRIVATE DirectHandle< Map > Update (Isolate *isolate, DirectHandle< Map > map)
static Handle< Map > CopyInitialMap (Isolate *isolate, DirectHandle< Map > map)
static V8_EXPORT_PRIVATE Handle< Map > CopyInitialMap (Isolate *isolate, DirectHandle< Map > map, int instance_size, int in_object_properties, int unused_property_fields)
static DirectHandle< Map > CopyInitialMapNormalized (Isolate *isolate, DirectHandle< Map > map, PropertyNormalizationMode mode=CLEAR_INOBJECT_PROPERTIES)
static Handle< Map > CopyDropDescriptors (Isolate *isolate, DirectHandle< Map > map)
static V8_EXPORT_PRIVATE Handle< Map > CopyInsertDescriptor (Isolate *isolate, DirectHandle< Map > map, Descriptor *descriptor, TransitionFlag flag)
static MaybeObjectDirectHandle WrapFieldType (DirectHandle< FieldType > type)
static V8_EXPORT_PRIVATE Tagged< FieldType > UnwrapFieldType (Tagged< MaybeObject > wrapped_type)
V8_EXPORT_PRIVATE static V8_WARN_UNUSED_RESULT MaybeHandle< Map > CopyWithField (Isolate *isolate, DirectHandle< Map > map, DirectHandle< Name > name, DirectHandle< FieldType > type, PropertyAttributes attributes, PropertyConstness constness, Representation representation, TransitionFlag flag)
V8_EXPORT_PRIVATE static V8_WARN_UNUSED_RESULT MaybeHandle< Map > CopyWithConstant (Isolate *isolate, DirectHandle< Map > map, DirectHandle< Name > name, DirectHandle< Object > constant, PropertyAttributes attributes, TransitionFlag flag)
static DirectHandle< Map > TransitionElementsTo (Isolate *isolate, DirectHandle< Map > map, ElementsKind to_kind)
static std::optional< Tagged< Map > > TryAsElementsKind (Isolate *isolate, DirectHandle< Map > map, ElementsKind kind, ConcurrencyMode cmode)
static V8_EXPORT_PRIVATE Handle< Map > AsElementsKind (Isolate *isolate, DirectHandle< Map > map, ElementsKind kind)
static Handle< Map > CopyAsElementsKind (Isolate *isolate, DirectHandle< Map > map, ElementsKind kind, TransitionFlag flag)
static DirectHandle< Map > AsLanguageMode (Isolate *isolate, DirectHandle< Map > initial_map, DirectHandle< SharedFunctionInfo > shared_info)
static V8_EXPORT_PRIVATE Handle< Map > CopyForPreventExtensions (Isolate *isolate, DirectHandle< Map > map, PropertyAttributes attrs_to_add, DirectHandle< Symbol > transition_marker, const char *reason, bool old_map_is_dictionary_elements_kind=false)
static V8_EXPORT_PRIVATE DirectHandle< Map > TransitionToDataProperty (Isolate *isolate, DirectHandle< Map > map, DirectHandle< Name > name, DirectHandle< Object > value, PropertyAttributes attributes, PropertyConstness constness, StoreOrigin store_origin)
static V8_EXPORT_PRIVATE DirectHandle< Map > TransitionToAccessorProperty (Isolate *isolate, DirectHandle< Map > map, DirectHandle< Name > name, InternalIndex descriptor, DirectHandle< Object > getter, DirectHandle< Object > setter, PropertyAttributes attributes)
static Handle< Map > CopyForElementsTransition (Isolate *isolate, DirectHandle< Map > map)
static Handle< Map > CopyForPrototypeTransition (Isolate *isolate, DirectHandle< Map > map, DirectHandle< JSPrototype > prototype)
static Handle< Map > Copy (Isolate *isolate, DirectHandle< Map > map, const char *reason, TransitionKindFlag kind=SPECIAL_TRANSITION)
static V8_EXPORT_PRIVATE Handle< Map > Create (Isolate *isolate, int inobject_properties)
static int SlackForArraySize (int old_size, int size_limit)
static V8_EXPORT_PRIVATE void EnsureDescriptorSlack (Isolate *isolate, DirectHandle< Map > map, int slack)
static DirectHandle< Map > GetObjectCreateMap (Isolate *isolate, DirectHandle< JSPrototype > prototype)
static Handle< Map > GetDerivedMap (Isolate *isolate, DirectHandle< Map > from, DirectHandle< JSReceiver > prototype)
static constexpr std::optional< RootIndex > TryGetMapRootIdxFor (InstanceType type)
static Tagged< Map > GetMapFor (ReadOnlyRoots roots, InstanceType type)
static constexpr ObjectFields ObjectFieldsFrom (VisitorId visitor_id)
static V8_EXPORT_PRIVATE Handle< Map > TransitionRootMapToPrototypeForNewObject (Isolate *isolate, DirectHandle< Map > map, DirectHandle< JSPrototype > prototype)
static V8_EXPORT_PRIVATE Handle< Map > TransitionToUpdatePrototype (Isolate *isolate, DirectHandle< Map > map, DirectHandle< JSPrototype > prototype)
static DirectHandle< Map > TransitionToImmutableProto (Isolate *isolate, DirectHandle< Map > map)
static DirectHandle< Map > AddMissingTransitionsForTesting (Isolate *isolate, DirectHandle< Map > split_map, DirectHandle< DescriptorArray > descriptors)
static V8_EXPORT_PRIVATE VisitorId GetVisitorId (Tagged< Map > map)
static bool CanHaveFastTransitionableElementsKind (InstanceType instance_type)
Public Attributes
Tagged< UnionOf< Smi, MaybeWeak< Map >, TransitionArray > > Isolate * isolate
Static Public Attributes
static const int kNoConstructorFunctionIndex = 0
static const int kSlackTrackingCounterStart = 7
static const int kSlackTrackingCounterEnd = 1
static const int kNoSlackTracking = 0
static const int kGenerousAllocationCount
static constexpr int kPrototypeChainValid = 0
static constexpr int kPrototypeChainInvalid = 1
static constexpr Tagged< Smi > kPrototypeChainValidSmi = Smi::zero()
Private Member Functions
Tagged< Map > LookupElementsTransitionMap (Isolate *isolate, ElementsKind elements_kind, ConcurrencyMode cmode)
Tagged< Map > TryReplayPropertyTransitions (Isolate *isolate, Tagged< Map > map, ConcurrencyMode cmode)
bool EquivalentToForTransition (const Tagged< Map > other, ConcurrencyMode cmode, DirectHandle< HeapObject > new_prototype={}) const
bool EquivalentToForElementsKindTransition (const Tagged< Map > other, ConcurrencyMode cmode) const
void DeprecateTransitionTree (Isolate *isolate)
void ReplaceDescriptors (Isolate *isolate, Tagged< DescriptorArray > new_descriptors)
Static Private Member Functions
static void ConnectTransition (Isolate *isolate, DirectHandle< Map > parent, DirectHandle< Map > child, DirectHandle< Name > name, TransitionKindFlag transition_kind, bool force_connect=false)
static Handle< Map > RawCopy (Isolate *isolate, DirectHandle< Map > map, int instance_size, int inobject_properties)
static Handle< Map > ShareDescriptor (Isolate *isolate, DirectHandle< Map > map, DirectHandle< DescriptorArray > descriptors, Descriptor *descriptor)
static V8_EXPORT_PRIVATE Handle< Map > AddMissingTransitions (Isolate *isolate, DirectHandle< Map > map, DirectHandle< DescriptorArray > descriptors)
static void InstallDescriptors (Isolate *isolate, DirectHandle< Map > parent_map, DirectHandle< Map > child_map, InternalIndex new_descriptor, DirectHandle< DescriptorArray > descriptors, bool force_connect=false)
static Handle< Map > CopyAddDescriptor (Isolate *isolate, DirectHandle< Map > map, Descriptor *descriptor, TransitionFlag flag)
static Handle< Map > CopyReplaceDescriptors (Isolate *isolate, DirectHandle< Map > map, DirectHandle< DescriptorArray > descriptors, TransitionFlag flag, MaybeDirectHandle< Name > maybe_name, const char *reason, TransitionKindFlag transition_kind)
static Handle< Map > CopyReplaceDescriptor (Isolate *isolate, DirectHandle< Map > map, DirectHandle< DescriptorArray > descriptors, Descriptor *descriptor, InternalIndex index, TransitionFlag flag)
static Handle< Map > CopyNormalized (Isolate *isolate, DirectHandle< Map > map, PropertyNormalizationMode mode)
static bool ConcurrentIsHeapObjectWithMap (PtrComprCageBase cage_base, Tagged< Object > object, Tagged< Map > meta_map)
Friends
class MapUpdater
template<typename ConcreteVisitor >
class MarkingVisitorBase
Detailed Description
Definition at line 238 of file map.h.
Member Function Documentation
AccountAddedOutOfObjectPropertyField()
void v8::internal::Map::AccountAddedOutOfObjectPropertyField (int unused_in_property_array) [inline]
Definition at line 493 of file map-inl.h.
                                                                           {
  unused_in_property_array--;
  if (unused_in_property_array < 0) {
    unused_in_property_array += JSObject::kFieldsAdded;
  }
  CHECK_LT(static_cast<unsigned>(unused_in_property_array),
           JSObject::kFieldsAdded);
  set_used_or_unused_instance_size_in_words(unused_in_property_array);
  DCHECK_EQ(unused_in_property_array, UnusedPropertyFields());
}
References CHECK_LT, DCHECK_EQ, v8::internal::JSObject::kFieldsAdded, and UnusedPropertyFields().
Referenced by AccountAddedPropertyField().
AccountAddedPropertyField()
void v8::internal::Map::AccountAddedPropertyField () [inline]
Definition at line 472 of file map-inl.h.
                                    {
  // Update used instance size and unused property fields number.
  static_assert(JSObject::kFieldsAdded == JSObject::kHeaderSize / kTaggedSize);
#ifdef DEBUG
  int new_unused = UnusedPropertyFields() - 1;
  if (new_unused < 0) new_unused += JSObject::kFieldsAdded;
#endif
  int value = used_or_unused_instance_size_in_words();
  if (value >= JSObject::kFieldsAdded) {
    if (value == instance_size_in_words()) {
      AccountAddedOutOfObjectPropertyField(0);
    } else {
      // The property is added in-object, so simply increment the counter.
      set_used_or_unused_instance_size_in_words(value + 1);
    }
  } else {
    AccountAddedOutOfObjectPropertyField(value);
  }
  DCHECK_EQ(new_unused, UnusedPropertyFields());
}
References AccountAddedOutOfObjectPropertyField(), DCHECK_EQ, v8::internal::JSObject::kFieldsAdded, v8::internal::kTaggedSize, UnusedPropertyFields(), and v8::internal::value.
Referenced by AppendDescriptor().
AddMissingTransitions()
Handle< Map > v8::internal::Map::AddMissingTransitions (Isolate * isolate, DirectHandle< Map > map, DirectHandle< DescriptorArray > descriptors) [static], [private]
Definition at line 1629 of file map.cc.
                                               {
  DCHECK(descriptors->IsSortedNoDuplicates());
  int split_nof = split_map->NumberOfOwnDescriptors();
  int nof_descriptors = descriptors->number_of_descriptors();
  CHECK_LT(split_nof, nof_descriptors);
  // Start with creating last map which will own full descriptors array.
  // This is necessary to guarantee that GC will mark the whole descriptor
  // array if any of the allocations happening below fail.
  // Number of unused properties is temporarily incorrect and the layout
  // descriptor could unnecessarily be in slow mode but we will fix after
  // all the other intermediate maps are created.
  // Also the last map might have interesting symbols, we temporarily set
  // the flag and clear it right before the descriptors are installed. This
  // makes heap verification happy and ensures the flag ends up accurate.
  Handle<Map> last_map = CopyDropDescriptors(isolate, split_map);
  last_map->InitializeDescriptors(isolate, *descriptors);
  last_map->SetInObjectUnusedPropertyFields(0);
  last_map->set_may_have_interesting_properties(true);
  // During creation of intermediate maps we violate descriptors sharing
  // invariant since the last map is not yet connected to the transition tree
  // we create here. But it is safe because GC never trims map's descriptors
  // if there are no dead transitions from that map and this is exactly the
  // case for all the intermediate maps we create here.
  DirectHandle<Map> map = split_map;
  for (InternalIndex i : InternalIndex::Range(split_nof, nof_descriptors - 1)) {
    DirectHandle<Map> new_map = CopyDropDescriptors(isolate, map);
    // Force connection of these maps to prevent split_map being a root map to
    // be treated as detached.
    InstallDescriptors(isolate, map, new_map, i, descriptors,
                       /* force_connect */ true);
    DCHECK_EQ(*new_map->GetBackPointer(), *map);
    map = new_map;
  }
  map->NotifyLeafMapLayoutChange(isolate);
  last_map->set_may_have_interesting_properties(false);
  InstallDescriptors(isolate, map, last_map, InternalIndex(nof_descriptors - 1),
                     descriptors);
  return last_map;
}
References CHECK_LT, CopyDropDescriptors(), v8::internal::DCHECK(), DCHECK_EQ, InstallDescriptors(), and isolate.
Referenced by AddMissingTransitionsForTesting(), and v8::internal::MapUpdater::ConstructNewMap().
AddMissingTransitionsForTesting()
DirectHandle< Map > v8::internal::Map::AddMissingTransitionsForTesting (Isolate * isolate, DirectHandle< Map > split_map, DirectHandle< DescriptorArray > descriptors) [inline], [static]
Definition at line 367 of file map-inl.h.
                                               {
  return AddMissingTransitions(isolate, split_map, descriptors);
}
References AddMissingTransitions(), and isolate.
AppendDescriptor()
void v8::internal::Map::AppendDescriptor (Isolate * isolate, Descriptor * desc) [inline]
Definition at line 796 of file map-inl.h.
                                                             {
  Tagged<DescriptorArray> descriptors = instance_descriptors(isolate);
  int number_of_own_descriptors = NumberOfOwnDescriptors();
  DCHECK(descriptors->number_of_descriptors() == number_of_own_descriptors);
  {
    // The following two operations need to happen before the marking write
    // barrier.
    descriptors->Append(desc);
    SetNumberOfOwnDescriptors(number_of_own_descriptors + 1);
#ifndef V8_DISABLE_WRITE_BARRIERS
    WriteBarrier::ForDescriptorArray(descriptors,
                                     number_of_own_descriptors + 1);
#endif
  }
  // Properly mark the map if the {desc} is an "interesting symbol".
  if (desc->GetKey()->IsInteresting(isolate)) {
    set_may_have_interesting_properties(true);
  }
  PropertyDetails details = desc->GetDetails();
  if (details.location() == PropertyLocation::kField) {
    DCHECK_GT(UnusedPropertyFields(), 0);
    AccountAddedPropertyField();
  }
// This function does not support appending double field descriptors and
// it should never try to (otherwise, layout descriptor must be updated too).
#ifdef DEBUG
  DCHECK(details.location() != PropertyLocation::kField ||
         !details.representation().IsDouble());
#endif
}
References AccountAddedPropertyField(), v8::internal::DCHECK(), DCHECK_GT, v8::internal::WriteBarrier::ForDescriptorArray(), v8::internal::Descriptor::GetDetails(), v8::internal::Descriptor::GetKey(), v8::internal::instance_descriptors, v8::internal::Representation::IsDouble(), isolate, v8::internal::kField, v8::internal::PropertyDetails::location(), NumberOfOwnDescriptors(), v8::internal::PropertyDetails::representation(), SetNumberOfOwnDescriptors(), and UnusedPropertyFields().
AsElementsKind()
Handle< Map > v8::internal::Map::AsElementsKind (Isolate * isolate, DirectHandle< Map > map, ElementsKind kind) [static]
Definition at line 1174 of file map.cc.
                                                   {
  Handle<Map> closest_map(
      FindClosestElementsTransition(isolate, *map, kind,
                                    ConcurrencyMode::kSynchronous),
      isolate);
  if (closest_map->elements_kind() == kind) {
    return closest_map;
  }
  return AddMissingElementsTransitions(isolate, closest_map, kind);
}
References v8::internal::AddMissingElementsTransitions(), v8::internal::FindClosestElementsTransition(), isolate, and v8::internal::kSynchronous.
Referenced by v8::internal::MapUpdater::FindRootMap(), v8::internal::JSDataObjectBuilder::InitializeMapFromZero(), and v8::internal::RUNTIME_FUNCTION().
AsLanguageMode()
DirectHandle< Map > v8::internal::Map::AsLanguageMode (Isolate * isolate, DirectHandle< Map > initial_map, DirectHandle< SharedFunctionInfo > shared_info) [static]
Definition at line 1745 of file map.cc.
                                                  {
  DCHECK(InstanceTypeChecker::IsJSFunction(initial_map->instance_type()));
  // Initial map for sloppy mode function is stored in the function
  // constructor. Initial maps for strict mode are cached as special transitions
  // using |strict_function_transition_symbol| as a key.
  if (is_sloppy(shared_info->language_mode())) return initial_map;
  DirectHandle<Map> function_map(Cast<Map>(isolate->native_context()->GetNoCell(
                                     shared_info->function_map_index())),
                                 isolate);
  static_assert(LanguageModeSize == 2);
  DCHECK_EQ(LanguageMode::kStrict, shared_info->language_mode());
  DirectHandle<Symbol> transition_symbol =
      isolate->factory()->strict_function_transition_symbol();
  MaybeDirectHandle<Map> maybe_transition = TransitionsAccessor::SearchSpecial(
      isolate, initial_map, *transition_symbol);
  if (!maybe_transition.is_null()) {
    return maybe_transition.ToHandleChecked();
  }
  initial_map->NotifyLeafMapLayoutChange(isolate);
  // Create new map taking descriptors from the |function_map| and all
  // the other details from the |initial_map|.
  DirectHandle<Map> map =
      Map::CopyInitialMap(isolate, function_map, initial_map->instance_size(),
                          initial_map->GetInObjectProperties(),
                          initial_map->UnusedPropertyFields());
  map->SetConstructor(initial_map->GetConstructor());
  map->set_prototype(initial_map->prototype());
  map->set_construction_counter(initial_map->construction_counter());
  if (TransitionsAccessor::CanHaveMoreTransitions(isolate, initial_map)) {
    Map::ConnectTransition(isolate, initial_map, map, transition_symbol,
                           SPECIAL_TRANSITION);
  }
  return map;
}
References v8::internal::TransitionsAccessor::CanHaveMoreTransitions(), ConnectTransition(), CopyInitialMap(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Isolate::factory(), v8::internal::libvtune::function_map, v8::internal::compiler::initial_map, v8::internal::MaybeDirectHandle< T >::is_null(), v8::internal::is_sloppy(), isolate, v8::internal::kStrict, v8::internal::LanguageModeSize, v8::internal::Isolate::native_context(), v8::internal::TransitionsAccessor::SearchSpecial(), v8::internal::SPECIAL_TRANSITION, and v8::internal::MaybeDirectHandle< T >::ToHandleChecked().
Referenced by v8::internal::anonymous_namespace{builtins-function.cc}::CreateDynamicFunction().
BelongsToSameNativeContextAs() [1/2]
bool v8::internal::Map::BelongsToSameNativeContextAs (Tagged< Context > context) const [inline]
Definition at line 941 of file map-inl.h.
                                                                    {
  Tagged<Map> context_meta_map = context->map()->map();
  Tagged<Map> this_meta_map = map();
  DCHECK_NE(context_meta_map, GetReadOnlyRoots().meta_map());
  return this_meta_map == context_meta_map;
}
References DCHECK_NE, and v8::internal::GetReadOnlyRoots().
BelongsToSameNativeContextAs() [2/2]
bool v8::internal::Map::BelongsToSameNativeContextAs (Tagged< Map > other_map) const [inline]
Definition at line 932 of file map-inl.h.
                                                                  {
  Tagged<Map> this_meta_map = map();
  // If the meta map is contextless (as in case of remote object's meta map)
  // we can't be sure the maps belong to the same context.
  if (this_meta_map == GetReadOnlyRoots().meta_map()) return false;
  DCHECK(IsNativeContext(this_meta_map->native_context_or_null()));
  return this_meta_map == other_map->map();
}
References v8::internal::DCHECK(), and v8::internal::GetReadOnlyRoots().
CanBeDeprecated()
bool v8::internal::Map::CanBeDeprecated () const [inline]
Definition at line 722 of file map-inl.h.
                                {
  for (InternalIndex i : IterateOwnDescriptors()) {
    PropertyDetails details = instance_descriptors(kRelaxedLoad)->GetDetails(i);
    if (details.representation().MightCauseMapDeprecation()) return true;
    if (details.kind() == PropertyKind::kData &&
        details.location() == PropertyLocation::kDescriptor) {
      return true;
    }
  }
  return false;
}
References v8::internal::instance_descriptors, IterateOwnDescriptors(), v8::internal::kData, v8::internal::kDescriptor, v8::internal::PropertyDetails::kind(), v8::kRelaxedLoad, v8::internal::PropertyDetails::location(), v8::internal::Representation::MightCauseMapDeprecation(), and v8::internal::PropertyDetails::representation().
Referenced by DeprecateTransitionTree().
CanHaveFastTransitionableElementsKind() [1/2]
bool v8::internal::Map::CanHaveFastTransitionableElementsKind () const [inline]
Definition at line 169 of file map-inl.h.
                                                      {
  return CanHaveFastTransitionableElementsKind(instance_type());
}
References instance_type().
Referenced by v8::internal::compiler::CompilationDependencies::DependOnFieldConstness(), v8::internal::compiler::CompilationDependencies::FieldConstnessDependencyOffTheRecord(), GeneralizeIfCanHaveTransitionableFastElementsKind(), and v8::internal::Factory::NewMapImpl().
CanHaveFastTransitionableElementsKind() [2/2]
bool v8::internal::Map::CanHaveFastTransitionableElementsKind (InstanceType instance_type) [inline], [static]
Definition at line 163 of file map-inl.h.
                                                                          {
  return instance_type == JS_ARRAY_TYPE ||
         instance_type == JS_PRIMITIVE_WRAPPER_TYPE ||
         instance_type == JS_ARGUMENTS_OBJECT_TYPE;
}
References instance_type().
CanTransition()
bool v8::internal::Map::CanTransition () const [inline]
Definition at line 742 of file map-inl.h.
                              {
  // Only JSObject and subtypes have map transitions and back pointers.
  const InstanceType type = instance_type();
  // JSExternalObjects are non-extensible and thus the map is allocated in
  // read only sapce.
  DCHECK_IMPLIES(InstanceTypeChecker::IsMaybeReadOnlyJSObject(type),
                 HeapLayout::InReadOnlySpace(*this));
  // Shared JS objects have fixed shapes and do not transition. Their maps are
  // either in shared space or RO space.
  DCHECK_IMPLIES(InstanceTypeChecker::IsAlwaysSharedSpaceJSObject(type),
                 HeapLayout::InAnySharedSpace(*this));
  return InstanceTypeChecker::IsJSObject(type) &&
         !InstanceTypeChecker::IsMaybeReadOnlyJSObject(type) &&
         !InstanceTypeChecker::IsAlwaysSharedSpaceJSObject(type);
}
References DCHECK_IMPLIES, v8::internal::HeapLayout::InAnySharedSpace(), v8::internal::HeapLayout::InReadOnlySpace(), instance_type(), v8::internal::InstanceTypeChecker::IsMaybeReadOnlyJSObject(), and v8::internal::tracing::type.
clear_padding()
void v8::internal::Map::clear_padding () [inline]
Definition at line 789 of file map-inl.h.
                        {
  if (FIELD_SIZE(kOptionalPaddingOffset) == 0) return;
  DCHECK_EQ(4, FIELD_SIZE(kOptionalPaddingOffset));
  memset(reinterpret_cast<void*>(address() + kOptionalPaddingOffset), 0,
         FIELD_SIZE(kOptionalPaddingOffset));
}
References DCHECK_EQ, and FIELD_SIZE.
ComputeMinObjectSlack()
int v8::internal::Map::ComputeMinObjectSlack (Isolate * isolate)
Definition at line 2361 of file map.cc.
                                               {
  // Has to be an initial map.
  DCHECK(IsUndefined(GetBackPointer(), isolate));
  int slack = UnusedPropertyFields();
  TransitionsAccessor transitions(isolate, *this);
  TransitionsAccessor::TraverseCallback callback = [&](Tagged<Map> map) {
    slack = std::min(slack, map->UnusedPropertyFields());
  };
  transitions.TraverseTransitionTree(callback);
  return slack;
}
References v8::internal::DCHECK(), isolate, v8::internal::TransitionsAccessor::TraverseTransitionTree(), and UnusedPropertyFields().
ConcurrentIsHeapObjectWithMap()
bool v8::internal::Map::ConcurrentIsHeapObjectWithMap (PtrComprCageBase cage_base, Tagged< Object > object, Tagged< Map > meta_map) [inline], [static], [private]
Definition at line 829 of file map-inl.h.
                                                              {
  if (!IsHeapObject(object)) return false;
  Tagged<HeapObject> heap_object = Cast<HeapObject>(object);
  return heap_object->map(cage_base) == meta_map;
}
References v8::internal::IsHeapObject().
Referenced by TryGetBackPointer().
ConnectTransition()
void v8::internal::Map::ConnectTransition (Isolate * isolate, DirectHandle< Map > parent, DirectHandle< Map > child, DirectHandle< Name > name, TransitionKindFlag transition_kind, bool force_connect = false) [static], [private]
Definition at line 1545 of file map.cc.
                                                {
  DCHECK_EQ(parent->map(), child->map());
  DCHECK_IMPLIES(name->IsInteresting(isolate),
                 child->may_have_interesting_properties());
  DCHECK_IMPLIES(parent->may_have_interesting_properties(),
                 child->may_have_interesting_properties());
  if (!IsUndefined(parent->GetBackPointer(), isolate)) {
    parent->set_owns_descriptors(false);
  } else if (!parent->IsDetached(isolate)) {
    // |parent| is initial map and it must not contain descriptors in the
    // descriptors array that do not belong to the map.
    DCHECK_EQ(parent->NumberOfOwnDescriptors(),
              parent->instance_descriptors(isolate)->number_of_descriptors());
  }
  if (parent->IsDetached(isolate) && !force_connect) {
    DCHECK(child->IsDetached(isolate));
    if (v8_flags.log_maps) {
      LOG(isolate, MapEvent("Transition", parent, child, "prototype", name));
    }
  } else {
    TransitionsAccessor::Insert(isolate, parent, name, child, transition_kind);
    if (v8_flags.log_maps) {
      LOG(isolate, MapEvent("Transition", parent, child, "", name));
    }
  }
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::TransitionsAccessor::Insert(), isolate, LOG, v8::internal::name, and v8::internal::v8_flags.
Referenced by AsLanguageMode(), CopyAsElementsKind(), CopyReplaceDescriptors(), InstallDescriptors(), and ShareDescriptor().
Copy()
Handle< Map > v8::internal::Map::Copy (Isolate * isolate, DirectHandle< Map > map, const char * reason, TransitionKindFlag kind = SPECIAL_TRANSITION) [static]
Definition at line 1822 of file map.cc.
                                                                   {
  DirectHandle<DescriptorArray> descriptors(map->instance_descriptors(isolate),
                                            isolate);
  int number_of_own_descriptors = map->NumberOfOwnDescriptors();
  DirectHandle<DescriptorArray> new_descriptors = DescriptorArray::CopyUpTo(
      isolate, descriptors, number_of_own_descriptors);
  auto res =
      CopyReplaceDescriptors(isolate, map, new_descriptors, OMIT_TRANSITION,
                             MaybeDirectHandle<Name>(), reason, kind);
  return res;
}
References CopyReplaceDescriptors(), v8::internal::DescriptorArray::CopyUpTo(), isolate, and v8::internal::OMIT_TRANSITION.
Referenced by CopyAsElementsKind(), CopyForPrototypeTransition(), Create(), v8::internal::Genesis::CreateAsyncFunctionMaps(), v8::internal::Genesis::CreateJSProxyMaps(), v8::internal::anonymous_namespace{bootstrapper.cc}::CreateNonConstructorMap(), v8::internal::Genesis::CreateObjectFunction(), v8::internal::anonymous_namespace{api-natives.cc}::DisableAccessChecks(), v8::internal::anonymous_namespace{api-natives.cc}::EnableAccessChecks(), v8::internal::JSObject::ForceSetPrototype(), v8::internal::JSFunction::GetDerivedRabGsabDataViewMap(), v8::internal::JSFunction::GetDerivedRabGsabTypedArrayMap(), v8::internal::Genesis::InitializeGlobal(), v8::internal::Genesis::InitializeIteratorFunctions(), v8::internal::Genesis::InstallABunchOfRandomThings(), v8::internal::JSObject::OptimizeAsPrototype(), v8::internal::JSObject::PreventExtensions(), v8::internal::JSObject::PreventExtensionsWithTransition(), v8::internal::Factory::ReinitializeJSGlobalProxy(), v8::internal::anonymous_namespace{js-function.cc}::SetInstancePrototype(), v8::internal::anonymous_namespace{elements.cc}::FastNonextensibleObjectElementsAccessor< Subclass, KindTraits >::SetLengthImpl(), v8::internal::anonymous_namespace{elements.cc}::FastSealedObjectElementsAccessor< Subclass, KindTraits >::SetLengthImpl(), v8::internal::JSFunction::SetPrototype(), and TransitionToImmutableProto().
CopyAddDescriptor()
Handle< Map > v8::internal::Map::CopyAddDescriptor (Isolate * isolate, DirectHandle< Map > map, Descriptor * descriptor, TransitionFlag flag) [static], [private]
Definition at line 2197 of file map.cc.
                                                        {
  DirectHandle<DescriptorArray> descriptors(map->instance_descriptors(isolate),
                                            isolate);
  // Share descriptors only if map owns descriptors and is not an initial map.
  if (flag == INSERT_TRANSITION && map->owns_descriptors() &&
      !IsUndefined(map->GetBackPointer(), isolate) &&
      TransitionsAccessor::CanHaveMoreTransitions(isolate, map)) {
    return ShareDescriptor(isolate, map, descriptors, descriptor);
  }
  int nof = map->NumberOfOwnDescriptors();
  DirectHandle<DescriptorArray> new_descriptors =
      DescriptorArray::CopyUpTo(isolate, descriptors, nof, 1);
  new_descriptors->Append(descriptor);
  return CopyReplaceDescriptors(isolate, map, new_descriptors, flag,
                                descriptor->GetKey(), "CopyAddDescriptor",
                                SIMPLE_PROPERTY_TRANSITION);
}
References v8::internal::TransitionsAccessor::CanHaveMoreTransitions(), CopyReplaceDescriptors(), v8::internal::DescriptorArray::CopyUpTo(), v8::internal::Descriptor::GetKey(), v8::internal::INSERT_TRANSITION, isolate, ShareDescriptor(), and v8::internal::SIMPLE_PROPERTY_TRANSITION.
Referenced by CopyInsertDescriptor(), and CopyWithField().
CopyAsElementsKind()
Handle< Map > v8::internal::Map::CopyAsElementsKind (Isolate * isolate, DirectHandle< Map > map, ElementsKind kind, TransitionFlag flag) [static]
Definition at line 1699 of file map.cc.
                                                                            {
  // Only certain objects are allowed to have non-terminal fast transitional
  // elements kinds.
  DCHECK(IsJSObjectMap(*map));
  DCHECK_IMPLIES(
      !map->CanHaveFastTransitionableElementsKind(),
      IsDictionaryElementsKind(kind) || IsTerminalElementsKind(kind));
  Tagged<Map> maybe_elements_transition_map;
  if (flag == INSERT_TRANSITION) {
    // Ensure we are requested to add elements kind transition "near the root".
    DCHECK_EQ(map->FindRootMap(isolate)->NumberOfOwnDescriptors(),
              map->NumberOfOwnDescriptors());
    maybe_elements_transition_map =
        map->ElementsTransitionMap(isolate, ConcurrencyMode::kSynchronous);
    DCHECK(maybe_elements_transition_map.is_null() ||
           (maybe_elements_transition_map->elements_kind() ==
                DICTIONARY_ELEMENTS &&
            kind == DICTIONARY_ELEMENTS));
    DCHECK(!IsFastElementsKind(kind) ||
           IsMoreGeneralElementsKindTransition(map->elements_kind(), kind));
    DCHECK(kind != map->elements_kind());
  }
  bool insert_transition =
      flag == INSERT_TRANSITION &&
      TransitionsAccessor::CanHaveMoreTransitions(isolate, map) &&
      maybe_elements_transition_map.is_null();
  if (insert_transition) {
    Handle<Map> new_map = CopyForElementsTransition(isolate, map);
    new_map->set_elements_kind(kind);
    DirectHandle<Name> name = isolate->factory()->elements_transition_symbol();
    ConnectTransition(isolate, map, new_map, name, SPECIAL_TRANSITION);
    return new_map;
  }
  // Create a new free-floating map only if we are not allowed to store it.
  Handle<Map> new_map = Copy(isolate, map, "CopyAsElementsKind");
  new_map->set_elements_kind(kind);
  return new_map;
}
References v8::internal::TransitionsAccessor::CanHaveMoreTransitions(), ConnectTransition(), Copy(), CopyForElementsTransition(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::DICTIONARY_ELEMENTS, v8::internal::Isolate::factory(), v8::internal::INSERT_TRANSITION, v8::internal::Tagged< HeapObject >::is_null(), v8::internal::IsDictionaryElementsKind(), v8::internal::IsFastElementsKind(), v8::internal::IsMoreGeneralElementsKindTransition(), isolate, v8::internal::IsTerminalElementsKind(), v8::internal::kSynchronous, v8::internal::name, and v8::internal::SPECIAL_TRANSITION.
Referenced by v8::internal::AddMissingElementsTransitions(), v8::internal::anonymous_namespace{bootstrapper.cc}::InitializeJSArrayMaps(), v8::internal::Genesis::InstallABunchOfRandomThings(), and TransitionElementsTo().
CopyDropDescriptors()
Handle< Map > v8::internal::Map::CopyDropDescriptors (Isolate * isolate, DirectHandle< Map > map) [static]
Definition at line 1491 of file map.cc.
                                                                            {
  Handle<Map> result =
      RawCopy(isolate, map, map->instance_size(),
              IsJSObjectMap(*map) ? map->GetInObjectProperties() : 0);
  // Please note instance_type and instance_size are set when allocated.
  if (IsJSObjectMap(*map)) {
    result->CopyUnusedPropertyFields(*map);
  }
  map->NotifyLeafMapLayoutChange(isolate);
  return result;
}
References isolate, RawCopy(), and v8::base::internal::result.
Referenced by AddMissingTransitions(), CopyForElementsTransition(), CopyReplaceDescriptors(), v8::internal::anonymous_namespace{runtime-classes.cc}::InitClassConstructor(), v8::internal::anonymous_namespace{runtime-classes.cc}::InitClassPrototype(), v8::internal::JSObject::MigrateSlowToFast(), v8::internal::Factory::NewJSGlobalObject(), and ShareDescriptor().
CopyForElementsTransition()
Handle< Map > v8::internal::Map::CopyForElementsTransition (Isolate * isolate, DirectHandle< Map > map) [static]
Definition at line 1786 of file map.cc.
                                                                  {
  DCHECK(!map->IsDetached(isolate));
  DCHECK(!map->is_dictionary_map());
  Handle<Map> new_map = CopyDropDescriptors(isolate, map);
  if (map->owns_descriptors()) {
    // In case the map owned its own descriptors, share the descriptors and
    // transfer ownership to the new map.
    // The properties did not change, so reuse descriptors.
    map->set_owns_descriptors(false);
    new_map->InitializeDescriptors(isolate, map->instance_descriptors(isolate));
  } else {
    // In case the map did not own its own descriptors, a split is forced by
    // copying the map; creating a new descriptor array cell.
    DirectHandle<DescriptorArray> descriptors(
        map->instance_descriptors(isolate), isolate);
    int number_of_own_descriptors = map->NumberOfOwnDescriptors();
    DirectHandle<DescriptorArray> new_descriptors = DescriptorArray::CopyUpTo(
        isolate, descriptors, number_of_own_descriptors);
    new_map->InitializeDescriptors(isolate, *new_descriptors);
  }
  return new_map;
}
References CopyDropDescriptors(), v8::internal::DescriptorArray::CopyUpTo(), v8::internal::DCHECK(), and isolate.
Referenced by CopyAsElementsKind().
CopyForPreventExtensions()
Handle< Map > v8::internal::Map::CopyForPreventExtensions (Isolate * isolate, DirectHandle< Map > map, PropertyAttributes attrs_to_add, DirectHandle< Symbol > transition_marker, const char * reason, bool old_map_is_dictionary_elements_kind = false) [static]
Definition at line 1863 of file map.cc.
                                              {
  int num_descriptors = map->NumberOfOwnDescriptors();
  DirectHandle<DescriptorArray> new_desc =
      DescriptorArray::CopyUpToAddAttributes(
          isolate, direct_handle(map->instance_descriptors(isolate), isolate),
          num_descriptors, attrs_to_add);
  // Do not track transitions during bootstrapping.
  TransitionFlag flag =
      isolate->bootstrapper()->IsActive() ? OMIT_TRANSITION : INSERT_TRANSITION;
  Handle<Map> new_map =
      CopyReplaceDescriptors(isolate, map, new_desc, flag, transition_marker,
                             reason, SPECIAL_TRANSITION);
  new_map->set_is_extensible(false);
  if (!IsTypedArrayOrRabGsabTypedArrayElementsKind(map->elements_kind())) {
    ElementsKind new_kind = IsStringWrapperElementsKind(map->elements_kind())
                                ? SLOW_STRING_WRAPPER_ELEMENTS
                                : DICTIONARY_ELEMENTS;
    if (!old_map_is_dictionary_elements_kind) {
      switch (map->elements_kind()) {
        case PACKED_ELEMENTS:
          if (attrs_to_add == SEALED) {
            new_kind = PACKED_SEALED_ELEMENTS;
          } else if (attrs_to_add == FROZEN) {
            new_kind = PACKED_FROZEN_ELEMENTS;
          } else {
            new_kind = PACKED_NONEXTENSIBLE_ELEMENTS;
          }
          break;
        case PACKED_NONEXTENSIBLE_ELEMENTS:
          if (attrs_to_add == SEALED) {
            new_kind = PACKED_SEALED_ELEMENTS;
          } else if (attrs_to_add == FROZEN) {
            new_kind = PACKED_FROZEN_ELEMENTS;
          }
          break;
        case PACKED_SEALED_ELEMENTS:
          if (attrs_to_add == FROZEN) {
            new_kind = PACKED_FROZEN_ELEMENTS;
          }
          break;
        case HOLEY_ELEMENTS:
          if (attrs_to_add == SEALED) {
            new_kind = HOLEY_SEALED_ELEMENTS;
          } else if (attrs_to_add == FROZEN) {
            new_kind = HOLEY_FROZEN_ELEMENTS;
          } else {
            new_kind = HOLEY_NONEXTENSIBLE_ELEMENTS;
          }
          break;
        case HOLEY_NONEXTENSIBLE_ELEMENTS:
          if (attrs_to_add == SEALED) {
            new_kind = HOLEY_SEALED_ELEMENTS;
          } else if (attrs_to_add == FROZEN) {
            new_kind = HOLEY_FROZEN_ELEMENTS;
          }
          break;
        case HOLEY_SEALED_ELEMENTS:
          if (attrs_to_add == FROZEN) {
            new_kind = HOLEY_FROZEN_ELEMENTS;
          }
          break;
        default:
          break;
      }
    }
    new_map->set_elements_kind(new_kind);
  }
  return new_map;
}
References v8::internal::Isolate::bootstrapper(), CopyReplaceDescriptors(), v8::internal::DescriptorArray::CopyUpToAddAttributes(), v8::internal::DICTIONARY_ELEMENTS, v8::internal::direct_handle(), v8::internal::FROZEN, v8::internal::HOLEY_ELEMENTS, v8::internal::HOLEY_FROZEN_ELEMENTS, v8::internal::HOLEY_NONEXTENSIBLE_ELEMENTS, v8::internal::HOLEY_SEALED_ELEMENTS, v8::internal::INSERT_TRANSITION, v8::internal::Bootstrapper::IsActive(), isolate, v8::internal::IsStringWrapperElementsKind(), v8::internal::IsTypedArrayOrRabGsabTypedArrayElementsKind(), v8::internal::OMIT_TRANSITION, v8::internal::PACKED_ELEMENTS, v8::internal::PACKED_FROZEN_ELEMENTS, v8::internal::PACKED_NONEXTENSIBLE_ELEMENTS, v8::internal::PACKED_SEALED_ELEMENTS, v8::internal::SEALED, v8::internal::SLOW_STRING_WRAPPER_ELEMENTS, and v8::internal::SPECIAL_TRANSITION.
Referenced by v8::internal::MapUpdater::ConstructNewMapWithIntegrityLevelTransition(), and v8::internal::JSObject::PreventExtensionsWithTransition().
CopyForPrototypeTransition()
Handle< Map > v8::internal::Map::CopyForPrototypeTransition (Isolate * isolate, DirectHandle< Map > map, DirectHandle< JSPrototype > prototype) [static]
Definition at line 1811 of file map.cc.
                                         {
  // For simplicity we always copy descriptors although it would be possible to
  // share them in some situations.
  Handle<Map> new_map =
      Copy(isolate, map, "TransitionToPrototype", PROTOTYPE_TRANSITION);
  Map::SetPrototype(isolate, new_map, prototype);
  return new_map;
}
References Copy(), isolate, v8::internal::prototype, v8::internal::PROTOTYPE_TRANSITION, and SetPrototype().
Referenced by v8::internal::MapUpdater::ApplyPrototypeTransition(), and TransitionToUpdatePrototype().
CopyInitialMap() [1/2]
Handle< Map > v8::internal::Map::CopyInitialMap (Isolate * isolate, DirectHandle< Map > map) [inline], [static]
Definition at line 1027 of file map-inl.h.
                                                                       {
  return CopyInitialMap(isolate, map, map->instance_size(),
                        map->GetInObjectProperties(),
                        map->UnusedPropertyFields());
}
References isolate.
Referenced by AsLanguageMode(), v8::internal::anonymous_namespace{js-function.cc}::FastInitializeDerivedMap(), GetDerivedMap(), and GetObjectCreateMap().
CopyInitialMap() [2/2]
Handle< Map > v8::internal::Map::CopyInitialMap (Isolate * isolate, DirectHandle< Map > map, int instance_size, int in_object_properties, int unused_property_fields) [static]
Definition at line 1466 of file map.cc.
                                                            {
  EnsureInitialMap(isolate, map);
  Handle<Map> result =
      RawCopy(isolate, map, instance_size, inobject_properties);
  // Please note instance_type and instance_size are set when allocated.
  result->SetInObjectUnusedPropertyFields(unused_property_fields);
  int number_of_own_descriptors = map->NumberOfOwnDescriptors();
  if (number_of_own_descriptors > 0) {
    // The copy will use the same descriptors array without ownership.
    Tagged<DescriptorArray> descriptors = map->instance_descriptors(isolate);
    result->set_owns_descriptors(false);
    result->UpdateDescriptors(isolate, descriptors, number_of_own_descriptors);
    DCHECK_EQ(result->NumberOfFields(ConcurrencyMode::kSynchronous),
              result->GetInObjectProperties() - result->UnusedPropertyFields());
  }
  return result;
}
References DCHECK_EQ, v8::internal::anonymous_namespace{map.cc}::EnsureInitialMap(), isolate, v8::internal::kSynchronous, RawCopy(), and v8::base::internal::result.
CopyInitialMapNormalized()
DirectHandle< Map > v8::internal::Map::CopyInitialMapNormalized (Isolate * isolate, DirectHandle< Map > map, PropertyNormalizationMode mode = CLEAR_INOBJECT_PROPERTIES) [static]
Definition at line 1459 of file map.cc.
                                                                             {
  EnsureInitialMap(isolate, map);
  return CopyNormalized(isolate, map, mode);
}
References CopyNormalized(), v8::internal::anonymous_namespace{map.cc}::EnsureInitialMap(), isolate, and mode().
Referenced by v8::internal::Genesis::CreateObjectFunction().
CopyInsertDescriptor()
Handle< Map > v8::internal::Map::CopyInsertDescriptor (Isolate * isolate, DirectHandle< Map > map, Descriptor * descriptor, TransitionFlag flag) [static]
Definition at line 2220 of file map.cc.
                                                           {
  DirectHandle<DescriptorArray> old_descriptors(
      map->instance_descriptors(isolate), isolate);
  // We replace the key if it is already present.
  InternalIndex index =
      old_descriptors->SearchWithCache(isolate, *descriptor->GetKey(), *map);
  if (index.is_found()) {
    return CopyReplaceDescriptor(isolate, map, old_descriptors, descriptor,
                                 index, flag);
  }
  return CopyAddDescriptor(isolate, map, descriptor, flag);
}
References CopyAddDescriptor(), CopyReplaceDescriptor(), v8::internal::Descriptor::GetKey(), v8::internal::index, and isolate.
Referenced by TransitionToAccessorProperty().
CopyNormalized()
Handle< Map > v8::internal::Map::CopyNormalized (Isolate * isolate, DirectHandle< Map > map, PropertyNormalizationMode mode) [static], [private]
Definition at line 1389 of file map.cc.
                                                                {
  int new_instance_size = map->instance_size();
  if (mode == CLEAR_INOBJECT_PROPERTIES) {
    new_instance_size -= map->GetInObjectProperties() * kTaggedSize;
  }
  Handle<Map> result = RawCopy(
      isolate, map, new_instance_size,
      mode == CLEAR_INOBJECT_PROPERTIES ? 0 : map->GetInObjectProperties());
  {
    DisallowGarbageCollection no_gc;
    Tagged<Map> raw = *result;
    // Clear the unused_property_fields explicitly as this field should not
    // be accessed for normalized maps.
    raw->SetInObjectUnusedPropertyFields(0);
    raw->set_is_dictionary_map(true);
    raw->set_is_migration_target(false);
    raw->set_may_have_interesting_properties(true);
    raw->set_construction_counter(kNoSlackTracking);
  }
#ifdef VERIFY_HEAP
  if (v8_flags.verify_heap) result->DictionaryMapVerify(isolate);
#endif
  return result;
}
References v8::internal::CLEAR_INOBJECT_PROPERTIES, isolate, kNoSlackTracking, v8::internal::kTaggedSize, mode(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, RawCopy(), v8::base::internal::result, and v8::internal::v8_flags.
Referenced by CopyInitialMapNormalized(), and Normalize().
CopyReplaceDescriptor()
Handle< Map > v8::internal::Map::CopyReplaceDescriptor (Isolate * isolate, DirectHandle< Map > map, DirectHandle< DescriptorArray > descriptors, Descriptor * descriptor, InternalIndex index, TransitionFlag flag) [static], [private]
Definition at line 2236 of file map.cc.
                                                        {
  DirectHandle<Name> key = descriptor->GetKey();
  DCHECK_EQ(*key, descriptors->GetKey(insertion_index));
  // This function does not support replacing property fields as
  // that would break property field counters.
  DCHECK_NE(PropertyLocation::kField, descriptor->GetDetails().location());
  DCHECK_NE(PropertyLocation::kField,
            descriptors->GetDetails(insertion_index).location());
  DirectHandle<DescriptorArray> new_descriptors = DescriptorArray::CopyUpTo(
      isolate, descriptors, map->NumberOfOwnDescriptors());
  new_descriptors->Replace(insertion_index, descriptor);
  TransitionKindFlag simple_flag =
      (insertion_index.as_int() == descriptors->number_of_descriptors() - 1)
          ? SIMPLE_PROPERTY_TRANSITION
          : PROPERTY_TRANSITION;
  return CopyReplaceDescriptors(isolate, map, new_descriptors, flag, key,
                                "CopyReplaceDescriptor", simple_flag);
}
References v8::internal::InternalIndex::as_int(), CopyReplaceDescriptors(), v8::internal::DescriptorArray::CopyUpTo(), DCHECK_EQ, DCHECK_NE, v8::internal::Descriptor::GetDetails(), v8::internal::Descriptor::GetKey(), isolate, v8::internal::key, v8::internal::kField, v8::internal::PropertyDetails::location(), v8::internal::PROPERTY_TRANSITION, and v8::internal::SIMPLE_PROPERTY_TRANSITION.
Referenced by CopyInsertDescriptor().
CopyReplaceDescriptors()
Handle< Map > v8::internal::Map::CopyReplaceDescriptors (Isolate * isolate, DirectHandle< Map > map, DirectHandle< DescriptorArray > descriptors, TransitionFlag flag, MaybeDirectHandle< Name > maybe_name, const char * reason, TransitionKindFlag transition_kind) [static], [private]
Definition at line 1575 of file map.cc.
                                        {
  DCHECK(descriptors->IsSortedNoDuplicates());
  Handle<Map> result = CopyDropDescriptors(isolate, map);
  bool is_connected = false;
  // Properly mark the {result} if the {name} is an "interesting symbol".
  DirectHandle<Name> name;
  if (maybe_name.ToHandle(&name) && name->IsInteresting(isolate)) {
    result->set_may_have_interesting_properties(true);
  }
  if (map->is_prototype_map()) {
    result->InitializeDescriptors(isolate, *descriptors);
  } else {
    if (flag == INSERT_TRANSITION &&
        TransitionsAccessor::CanHaveMoreTransitions(isolate, map)) {
      result->InitializeDescriptors(isolate, *descriptors);
      DCHECK(!maybe_name.is_null());
      ConnectTransition(isolate, map, result, name, transition_kind);
      is_connected = true;
    } else if ((transition_kind == PROTOTYPE_TRANSITION &&
                v8_flags.move_prototype_transitions_first) ||
               isolate->bootstrapper()->IsActive()) {
      // Prototype transitions are always between root maps. UpdatePrototype
      // uses the MapUpdater and instance migration. Thus, field generalization
      // is allowed to happen lazily.
      DCHECK_IMPLIES(transition_kind == PROTOTYPE_TRANSITION,
                     IsUndefined(map->GetBackPointer()));
      result->InitializeDescriptors(isolate, *descriptors);
    } else {
      DCHECK_IMPLIES(transition_kind == PROTOTYPE_TRANSITION,
                     !v8_flags.move_prototype_transitions_first);
      descriptors->GeneralizeAllFields(transition_kind == PROTOTYPE_TRANSITION);
      result->InitializeDescriptors(isolate, *descriptors);
    }
  }
  if (v8_flags.log_maps && !is_connected) {
    LOG(isolate,
        MapEvent("ReplaceDescriptors", map, result, reason,
                 maybe_name.is_null() ? DirectHandle<HeapObject>() : name));
  }
  return result;
}
References v8::internal::Isolate::bootstrapper(), v8::internal::TransitionsAccessor::CanHaveMoreTransitions(), ConnectTransition(), CopyDropDescriptors(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::INSERT_TRANSITION, v8::internal::MaybeDirectHandle< T >::is_null(), v8::internal::Bootstrapper::IsActive(), isolate, LOG, v8::internal::name, v8::internal::PROTOTYPE_TRANSITION, v8::base::internal::result, v8::internal::MaybeDirectHandle< T >::ToHandle(), and v8::internal::v8_flags.
Referenced by Copy(), CopyAddDescriptor(), CopyForPreventExtensions(), and CopyReplaceDescriptor().
CopyUnusedPropertyFields()
void v8::internal::Map::CopyUnusedPropertyFields (Tagged< Map > map) [inline]
Definition at line 455 of file map-inl.h.
                                                  {
  set_used_or_unused_instance_size_in_words(
      map->used_or_unused_instance_size_in_words());
  DCHECK_EQ(UnusedPropertyFields(), map->UnusedPropertyFields());
}
References DCHECK_EQ, and UnusedPropertyFields().
CopyUnusedPropertyFieldsAdjustedForInstanceSize()
void v8::internal::Map::CopyUnusedPropertyFieldsAdjustedForInstanceSize (Tagged< Map > map) [inline]
Definition at line 461 of file map-inl.h.
                                                                         {
  int value = map->used_or_unused_instance_size_in_words();
  if (value >= JSPrimitiveWrapper::kFieldsAdded) {
    // Unused in-object fields. Adjust the offset from the objects start
    // so it matches the distance to the objects end.
    value += instance_size_in_words() - map->instance_size_in_words();
  }
  set_used_or_unused_instance_size_in_words(value);
  DCHECK_EQ(UnusedPropertyFields(), map->UnusedPropertyFields());
}
References DCHECK_EQ, UnusedPropertyFields(), and v8::internal::value.
CopyWithConstant()
MaybeHandle< Map > v8::internal::Map::CopyWithConstant (Isolate * isolate, DirectHandle< Map > map, DirectHandle< Name > name, DirectHandle< Object > constant, PropertyAttributes attributes, TransitionFlag flag) [static]
Definition at line 550 of file map.cc.
                                                            {
  // Ensure the descriptor array does not get too big.
  if (map->NumberOfOwnDescriptors() >= kMaxNumberOfDescriptors) {
    return MaybeHandle<Map>();
  }
  Representation representation =
      Object::OptimalRepresentation(*constant, isolate);
  DirectHandle<FieldType> type =
      Object::OptimalType(*constant, isolate, representation);
  return CopyWithField(isolate, map, name, type, attributes,
                       PropertyConstness::kConst, representation, flag);
}
References CopyWithField(), isolate, v8::internal::kConst, v8::internal::kMaxNumberOfDescriptors, v8::internal::name, v8::internal::Object::OptimalRepresentation(), v8::internal::Object::OptimalType(), and v8::internal::tracing::type.
CopyWithField()
MaybeHandle< Map > v8::internal::Map::CopyWithField (Isolate * isolate, DirectHandle< Map > map, DirectHandle< Name > name, DirectHandle< FieldType > type, PropertyAttributes attributes, PropertyConstness constness, Representation representation, TransitionFlag flag) [static]
Definition at line 513 of file map.cc.
                                                         {
  DCHECK(map->instance_descriptors(isolate)
             ->Search(*name, map->NumberOfOwnDescriptors())
             .is_not_found());
  // Ensure the descriptor array does not get too big.
  if (map->NumberOfOwnDescriptors() >= kMaxNumberOfDescriptors) {
    return MaybeHandle<Map>();
  }
  // Compute the new index for new field.
  int index = map->NextFreePropertyIndex();
  if (map->instance_type() == JS_CONTEXT_EXTENSION_OBJECT_TYPE) {
    constness = PropertyConstness::kMutable;
    representation = Representation::Tagged();
    type = FieldType::Any(isolate);
  } else {
    Map::GeneralizeIfCanHaveTransitionableFastElementsKind(
        isolate, map->instance_type(), &representation, &type);
  }
  MaybeObjectDirectHandle wrapped_type = WrapFieldType(type);
  Descriptor d = Descriptor::DataField(name, index, attributes, constness,
                                       representation, wrapped_type);
  Handle<Map> new_map = Map::CopyAddDescriptor(isolate, map, &d, flag);
  new_map->AccountAddedPropertyField();
  return new_map;
}
References v8::internal::FieldType::Any(), CopyAddDescriptor(), v8::internal::Descriptor::DataField(), v8::internal::DCHECK(), GeneralizeIfCanHaveTransitionableFastElementsKind(), v8::internal::index, isolate, v8::internal::kMaxNumberOfDescriptors, v8::internal::kMutable, v8::internal::name, v8::internal::Representation::Tagged(), v8::internal::tracing::type, and WrapFieldType().
Referenced by CopyWithConstant(), v8::internal::anonymous_namespace{bootstrapper.cc}::CreateLiteralObjectMapFromCache(), TransitionToDataProperty(), and v8::internal::JSDataObjectBuilder::TryAddFastPropertyForValue().
Create()
Handle< Map > v8::internal::Map::Create (Isolate * isolate, int inobject_properties) [static]
Definition at line 1835 of file map.cc.
                                                                 {
  Handle<Map> copy_handle =
      Copy(isolate,
           direct_handle(isolate->object_function()->initial_map(), isolate),
           "MapCreate");
  DisallowGarbageCollection no_gc;
  Tagged<Map> copy = *copy_handle;
  // Check that we do not overflow the instance size when adding the extra
  // inobject properties. If the instance size overflows, we allocate as many
  // properties as we can as inobject properties.
  if (inobject_properties > JSObject::kMaxInObjectProperties) {
    inobject_properties = JSObject::kMaxInObjectProperties;
  }
  int new_instance_size =
      JSObject::kHeaderSize + kTaggedSize * inobject_properties;
  // Adjust the map with the extra inobject properties.
  copy->set_instance_size(new_instance_size);
  copy->SetInObjectPropertiesStartInWords(JSObject::kHeaderSize / kTaggedSize);
  DCHECK_EQ(copy->GetInObjectProperties(), inobject_properties);
  copy->SetInObjectUnusedPropertyFields(inobject_properties);
  copy->set_visitor_id(Map::GetVisitorId(copy));
  return copy_handle;
}
References Copy(), DCHECK_EQ, v8::internal::direct_handle(), GetVisitorId(), isolate, v8::internal::JSObject::kMaxInObjectProperties, v8::internal::kTaggedSize, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::WasmStruct::AllocatePrototype(), v8::internal::Genesis::CreateAsyncIteratorMaps(), v8::internal::anonymous_namespace{runtime-classes.cc}::CreateClassPrototype(), v8::internal::Genesis::CreateIteratorMaps(), and v8::internal::Factory::ObjectLiteralMapFromCache().
DECL_ACCESSORS()
v8::internal::Map::DECL_ACCESSORS (raw_transitions , Tagged< UnionOf< Smi, MaybeWeak< Map >, TransitionArray >>)
DECL_RELEASE_ACQUIRE_ACCESSORS()
Tagged<UnionOf<Smi, MaybeWeak<Map>, TransitionArray> > v8::internal::Map::DECL_RELEASE_ACQUIRE_ACCESSORS (prototype_info , Tagged< UnionOf< Smi, PrototypeInfo >>)
DeprecateTransitionTree()
void v8::internal::Map::DeprecateTransitionTree (Isolate * isolate) [private]
Definition at line 651 of file map.cc.
                                                  {
  if (is_deprecated()) return;
  DisallowGarbageCollection no_gc;
  ReadOnlyRoots roots(isolate);
  TransitionsAccessor transitions(isolate, *this);
  transitions.ForEachTransition(
      &no_gc, [&](Tagged<Map> map) { map->DeprecateTransitionTree(isolate); },
      [&](Tagged<Map> map) {
        if (v8_flags.move_prototype_transitions_first) {
          map->DeprecateTransitionTree(isolate);
        }
      },
      nullptr);
  DCHECK(!IsFunctionTemplateInfo(constructor_or_back_pointer()));
  DCHECK(CanBeDeprecated());
  set_is_deprecated(true);
  if (v8_flags.log_maps) {
    LOG(isolate, MapEvent("Deprecate", direct_handle(*this, isolate), {}));
  }
  DependentCode::DeoptimizeDependencyGroups(isolate, *this,
                                            DependentCode::kTransitionGroup);
  NotifyLeafMapLayoutChange(isolate);
}
References CanBeDeprecated(), v8::internal::constructor_or_back_pointer, v8::internal::DCHECK(), v8::internal::DependentCode::DeoptimizeDependencyGroups(), v8::internal::direct_handle(), v8::internal::TransitionsAccessor::ForEachTransition(), v8::internal::is_deprecated, isolate, v8::internal::DependentCode::kTransitionGroup, LOG, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, NotifyLeafMapLayoutChange(), and v8::internal::v8_flags.
ElementsTransitionMap()
Tagged< Map > v8::internal::Map::ElementsTransitionMap (Isolate * isolate, ConcurrencyMode cmode) [inline]
Definition at line 880 of file map-inl.h.
                                                              {
  return TransitionsAccessor(isolate, *this, IsConcurrent(cmode))
      .SearchSpecial(ReadOnlyRoots(isolate).elements_transition_symbol());
}
References v8::internal::IsConcurrent(), isolate, and v8::internal::TransitionsAccessor::SearchSpecial().
EnsureDescriptorSlack()
void v8::internal::Map::EnsureDescriptorSlack (Isolate * isolate, DirectHandle< Map > map, int slack) [static]
Definition at line 861 of file map.cc.
                                           {
  // Only supports adding slack to owned descriptors.
  CHECK(map->owns_descriptors());
  DirectHandle<DescriptorArray> descriptors(map->instance_descriptors(isolate),
                                            isolate);
  int old_size = map->NumberOfOwnDescriptors();
  if (slack <= descriptors->number_of_slack_descriptors()) return;
  DirectHandle<DescriptorArray> new_descriptors =
      DescriptorArray::CopyUpTo(isolate, descriptors, old_size, slack);
  DisallowGarbageCollection no_gc;
  if (old_size == 0) {
    map->UpdateDescriptors(isolate, *new_descriptors,
                           map->NumberOfOwnDescriptors());
    return;
  }
  // If the source descriptors had an enum cache we copy it. This ensures
  // that the maps to which we push the new descriptor array back can rely
  // on a cache always being available once it is set. If the map has more
  // enumerated descriptors than available in the original cache, the cache
  // will be lazily replaced by the extended cache when needed.
  new_descriptors->CopyEnumCacheFrom(*descriptors);
  // Replace descriptors by new_descriptors in all maps that share it. The old
  // descriptors will not be trimmed in the mark-compactor, we need to mark
  // all its elements.
#ifndef V8_DISABLE_WRITE_BARRIERS
  WriteBarrier::ForDescriptorArray(*descriptors,
                                   descriptors->number_of_descriptors());
#endif
  // Update the descriptors from {map} (inclusive) until the initial map
  // (exclusive). In the case that {map} is the initial map, update it.
  map->UpdateDescriptors(isolate, *new_descriptors,
                         map->NumberOfOwnDescriptors());
  Tagged<Object> next = map->GetBackPointer();
  if (IsUndefined(next, isolate)) return;
  Tagged<Map> current = Cast<Map>(next);
  while (current->instance_descriptors(isolate) == *descriptors) {
    next = current->GetBackPointer();
    if (IsUndefined(next, isolate)) break;
    current->UpdateDescriptors(isolate, *new_descriptors,
                               current->NumberOfOwnDescriptors());
    current = Cast<Map>(next);
  }
}
References CHECK, v8::internal::DescriptorArray::CopyUpTo(), v8::internal::WriteBarrier::ForDescriptorArray(), isolate, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::Factory::CreateClassFunctionMap(), v8::internal::Genesis::CreateInitialMapForArraySubclass(), v8::internal::Genesis::CreateJSProxyMaps(), v8::internal::Factory::CreateSloppyFunctionMap(), v8::internal::Factory::CreateStrictFunctionMap(), v8::internal::Genesis::InitializeGlobal(), v8::internal::Genesis::InstallABunchOfRandomThings(), v8::internal::InstallError(), v8::internal::WasmValueObject::New(), and ShareDescriptor().
EnumLength()
int v8::internal::Map::EnumLength () const [inline]
Definition at line 249 of file map-inl.h.
                          {
  return Bits3::EnumLengthBits::decode(bit_field3());
}
References v8::internal::bit_field3.
EquivalentToForElementsKindTransition()
bool v8::internal::Map::EquivalentToForElementsKindTransition (const Tagged< Map > other, ConcurrencyMode cmode) const [private]
Definition at line 2319 of file map.cc.
                                                                             {
  if (!EquivalentToForTransition(other, cmode)) {
    return false;
  }
#ifdef DEBUG
  // Ensure that we don't try to generate elements kind transitions from maps
  // with fields that may be generalized in-place. This must already be handled
  // during addition of a new field.
  Tagged<DescriptorArray> descriptors = IsConcurrent(cmode)
                                            ? instance_descriptors(kAcquireLoad)
                                            : instance_descriptors();
  for (InternalIndex i : IterateOwnDescriptors()) {
    PropertyDetails details = descriptors->GetDetails(i);
    if (details.location() == PropertyLocation::kField) {
      DCHECK(IsMostGeneralFieldType(details.representation(),
                                    descriptors->GetFieldType(i)));
    }
  }
#endif
  return true;
}
References v8::internal::DCHECK(), EquivalentToForTransition(), v8::internal::instance_descriptors, v8::internal::IsConcurrent(), IsMostGeneralFieldType(), IterateOwnDescriptors(), v8::kAcquireLoad, v8::internal::kField, v8::internal::PropertyDetails::location(), and v8::internal::PropertyDetails::representation().
Referenced by FindElementsKindTransitionedMap().
EquivalentToForNormalization() [1/2]
bool v8::internal::Map::EquivalentToForNormalization (const Tagged< Map > other, ElementsKind elements_kind, Tagged< HeapObject > prototype, PropertyNormalizationMode mode) const
Definition at line 2342 of file map.cc.
                                                                             {
  int properties =
      mode == CLEAR_INOBJECT_PROPERTIES ? 0 : other->GetInObjectProperties();
  // Make sure the elements_kind bits are in bit_field2.
  DCHECK_EQ(this->elements_kind(),
            Map::Bits2::ElementsKindBits::decode(bit_field2()));
  int adjusted_other_bit_field2 =
      Map::Bits2::ElementsKindBits::update(other->bit_field2(), elements_kind);
  return CheckEquivalentModuloProto(*this, other) &&
         prototype() == other_prototype &&
         bit_field2() == adjusted_other_bit_field2 &&
         GetInObjectProperties() == properties &&
         JSObject::GetEmbedderFieldCount(*this) ==
             JSObject::GetEmbedderFieldCount(other);
}
References v8::internal::bit_field2, v8::internal::anonymous_namespace{map.cc}::CheckEquivalentModuloProto(), v8::internal::CLEAR_INOBJECT_PROPERTIES, DCHECK_EQ, v8::internal::JSObject::GetEmbedderFieldCount(), GetInObjectProperties(), mode(), and v8::internal::prototype.
Referenced by EquivalentToForNormalization().
EquivalentToForNormalization() [2/2]
bool v8::internal::Map::EquivalentToForNormalization (const Tagged< Map > other, PropertyNormalizationMode mode) const [inline]
Definition at line 201 of file map-inl.h.
                                                                             {
  return EquivalentToForNormalization(other, elements_kind(), prototype(),
                                      mode);
}
References EquivalentToForNormalization(), mode(), and v8::internal::prototype.
EquivalentToForTransition()
bool v8::internal::Map::EquivalentToForTransition (const Tagged< Map > other, ConcurrencyMode cmode, DirectHandle< HeapObject > new_prototype = {}) const [private]
Definition at line 2290 of file map.cc.
                                                  {
  CHECK_EQ(GetConstructor(), other->GetConstructor());
  CHECK_EQ(instance_type(), other->instance_type());
  if (bit_field() != other->bit_field()) return false;
  if (new_prototype.is_null()) {
    if (prototype() != other->prototype()) return false;
  } else {
    if (*new_prototype != other->prototype()) return false;
  }
  if (new_target_is_base() != other->new_target_is_base()) return false;
  if (InstanceTypeChecker::IsJSFunction(instance_type())) {
    // JSFunctions require more checks to ensure that sloppy function is
    // not equivalent to strict function.
    int nof =
        std::min(NumberOfOwnDescriptors(), other->NumberOfOwnDescriptors());
    Tagged<DescriptorArray> this_descriptors =
        IsConcurrent(cmode) ? instance_descriptors(kAcquireLoad)
                            : instance_descriptors();
    Tagged<DescriptorArray> that_descriptors =
        IsConcurrent(cmode) ? other->instance_descriptors(kAcquireLoad)
                            : other->instance_descriptors();
    return this_descriptors->IsEqualUpTo(that_descriptors, nof);
  }
  return true;
}
References v8::internal::bit_field, CHECK_EQ, v8::internal::instance_descriptors, instance_type(), v8::internal::DirectHandle< T >::is_null(), v8::internal::IsConcurrent(), v8::kAcquireLoad, NumberOfOwnDescriptors(), and v8::internal::prototype.
Referenced by EquivalentToForElementsKindTransition().
FindElementsKindTransitionedMap()
Tagged< Map > v8::internal::Map::FindElementsKindTransitionedMap (Isolate * isolate, MapHandlesSpan candidates, ConcurrencyMode cmode)
Definition at line 993 of file map.cc.
                                                                        {
  DisallowGarbageCollection no_gc;
  if (IsDetached(isolate)) return Map();
  ElementsKind kind = elements_kind();
  bool is_packed = IsFastPackedElementsKind(kind);
  Tagged<Map> transition;
  if (IsTransitionableFastElementsKind(kind)) {
    // Check the state of the root map.
    Tagged<Map> root_map = FindRootMap(isolate);
    if (!EquivalentToForElementsKindTransition(root_map, cmode)) return Map();
    root_map = root_map->LookupElementsTransitionMap(isolate, kind, cmode);
    DCHECK(!root_map.is_null());
    // Starting from the next existing elements kind transition try to
    // replay the property transitions that does not involve instance rewriting
    // (ElementsTransitionAndStoreStub does not support that).
    for (root_map = root_map->ElementsTransitionMap(isolate, cmode);
         !root_map.is_null() && root_map->has_fast_elements();
         root_map = root_map->ElementsTransitionMap(isolate, cmode)) {
      // If root_map's elements kind doesn't match any of the elements kind in
      // the candidates there is no need to do any additional work.
      if (!HasElementsKind(candidates, root_map->elements_kind())) continue;
      Tagged<Map> current =
          root_map->TryReplayPropertyTransitions(isolate, *this, cmode);
      if (current.is_null()) continue;
      if (InstancesNeedRewriting(current, cmode)) continue;
      const bool current_is_packed =
          IsFastPackedElementsKind(current->elements_kind());
      if (ContainsMap(candidates, current) &&
          (is_packed || !current_is_packed)) {
        transition = current;
        is_packed = is_packed && current_is_packed;
      }
    }
  }
  return transition;
}
References v8::internal::ContainsMap(), v8::internal::DCHECK(), EquivalentToForElementsKindTransition(), FindRootMap(), v8::internal::HasElementsKind(), InstancesNeedRewriting(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::wasm::is_packed(), IsDetached(), v8::internal::IsFastPackedElementsKind(), isolate, v8::internal::IsTransitionableFastElementsKind(), v8::internal::compiler::Map, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
FindFieldOwner()
Tagged< Map > v8::internal::Map::FindFieldOwner (PtrComprCageBase cage_base, InternalIndex descriptor) const
Definition at line 727 of file map.cc.
                                                                {
  DisallowGarbageCollection no_gc;
  DCHECK_EQ(PropertyLocation::kField,
            instance_descriptors(cage_base, kRelaxedLoad)
                ->GetDetails(descriptor)
                .location());
  Tagged<Map> result = *this;
  while (true) {
    Tagged<Map> parent;
    if (!result->TryGetBackPointer(cage_base, &parent)) break;
    if (parent->NumberOfOwnDescriptors() <= descriptor.as_int()) break;
    result = parent;
  }
  return result;
}
References v8::internal::InternalIndex::as_int(), DCHECK_EQ, v8::internal::instance_descriptors, v8::internal::kField, v8::kRelaxedLoad, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::base::internal::result.
FindRootMap()
Tagged< Map > v8::internal::Map::FindRootMap (PtrComprCageBase cage_base) const
Definition at line 708 of file map.cc.
                                                             {
  DisallowGarbageCollection no_gc;
  Tagged<Map> result = *this;
  while (true) {
    Tagged<Map> parent;
    if (!result->TryGetBackPointer(cage_base, &parent)) {
#if DEBUG
      if (IsJSObjectMap(result)) {
        DCHECK_LE(result->NumberOfOwnDescriptors(),
                  result->instance_descriptors(cage_base, kRelaxedLoad)
                      ->number_of_descriptors());
      }
#endif
      return result;
    }
    result = parent;
  }
}
References DCHECK_LE, v8::kRelaxedLoad, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::base::internal::result.
Referenced by FindElementsKindTransitionedMap().
GeneralizeIfCanHaveTransitionableFastElementsKind()
void v8::internal::Map::GeneralizeIfCanHaveTransitionableFastElementsKind (Isolate * isolate, InstanceType instance_type, Representation * representation, DirectHandle< FieldType > * field_type) [inline], [static]
Definition at line 180 of file map-inl.h.
                                                                         {
  if (CanHaveFastTransitionableElementsKind(instance_type)) {
    // We don't support propagation of field generalization through elements
    // kind transitions because they are inserted into the transition tree
    // before field transitions. In order to avoid complexity of handling
    // such a case we ensure that all maps with transitionable elements kinds
    // have the most general field representation and type.
    *field_type = FieldType::Any(isolate);
    *representation = Representation::Tagged();
  }
}
References v8::internal::FieldType::Any(), CanHaveFastTransitionableElementsKind(), instance_type(), isolate, and v8::internal::Representation::Tagged().
Referenced by v8::internal::MapUpdater::BuildDescriptorArray(), CopyWithField(), and v8::internal::MapUpdater::ReconfigureToDataField().
GetConstructorFunction()
std::optional< Tagged< JSFunction > > v8::internal::Map::GetConstructorFunction (Tagged< Map > map, Tagged< Context > native_context) [static]
Definition at line 53 of file map.cc.
                                                     {
  DisallowGarbageCollection no_gc;
  if (IsPrimitiveMap(map)) {
    int const constructor_function_index = map->GetConstructorFunctionIndex();
    if (constructor_function_index != kNoConstructorFunctionIndex) {
      return Cast<JSFunction>(
          native_context->GetNoCell(constructor_function_index));
    }
  }
  return {};
}
References v8::internal::IsPrimitiveMap(), kNoConstructorFunctionIndex, v8::internal::native_context, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::compiler::PropertyAccessBuilder::FoldLoadDictPrototypeConstant(), and v8::internal::maglev::MaglevGraphBuilder::TryFoldLoadDictPrototypeConstant().
GetConstructorFunctionIndex()
int v8::internal::Map::GetConstructorFunctionIndex () const [inline]
Definition at line 346 of file map-inl.h.
                                           {
#if V8_ENABLE_WEBASSEMBLY
  // We allow WasmNull here so builtins can produce error messages when
  // called from Wasm, without having to special-case WasmNull at every
  // caller of such a builtin.
  DCHECK(IsPrimitiveMap(*this) || instance_type() == WASM_NULL_TYPE);
#else
  DCHECK(IsPrimitiveMap(*this));
#endif
  return inobject_properties_start_or_constructor_function_index();
}
References v8::internal::DCHECK(), instance_type(), and v8::internal::IsPrimitiveMap().
Referenced by GetPrototypeChainRootMap().
GetDerivedMap()
Handle< Map > v8::internal::Map::GetDerivedMap (Isolate * isolate, DirectHandle< Map > from, DirectHandle< JSReceiver > prototype) [static]
Definition at line 945 of file map.cc.
                                                                   {
  DCHECK(IsUndefined(from->GetBackPointer()));
  if (IsJSObjectThatCanBeTrackedAsPrototype(*prototype)) {
    DirectHandle<JSObject> js_prototype = Cast<JSObject>(prototype);
    if (!js_prototype->map()->is_prototype_map()) {
      JSObject::OptimizeAsPrototype(js_prototype);
    }
    DirectHandle<PrototypeInfo> info =
        Map::GetOrCreatePrototypeInfo(js_prototype, isolate);
    Tagged<HeapObject> map_obj;
    Handle<Map> map;
    if (info->GetDerivedMap(from).GetHeapObjectIfWeak(&map_obj)) {
      map = handle(Cast<Map>(map_obj), isolate);
    } else {
      map = Map::CopyInitialMap(isolate, from);
      map->set_new_target_is_base(false);
      if (map->prototype() != *prototype) {
        Map::SetPrototype(isolate, map, prototype);
      }
      PrototypeInfo::AddDerivedMap(info, map, isolate);
    }
    return map;
  }
  // The TransitionToPrototype map will not have new_target_is_base reset. But
  // we don't need it to for proxies.
  return Map::TransitionRootMapToPrototypeForNewObject(isolate, from,
                                                       prototype);
}
References v8::internal::PrototypeInfo::AddDerivedMap(), CopyInitialMap(), v8::internal::DCHECK(), GetOrCreatePrototypeInfo(), v8::internal::handle(), v8::internal::IsJSObjectThatCanBeTrackedAsPrototype(), isolate, v8::internal::JSObject::OptimizeAsPrototype(), v8::internal::prototype, SetPrototype(), and TransitionRootMapToPrototypeForNewObject().
Referenced by v8::internal::JSFunction::GetDerivedMap().
GetFieldCounts()
Map::FieldCounts v8::internal::Map::GetFieldCounts () const
Definition at line 631 of file map.cc.
                                         {
  Tagged<DescriptorArray> descriptors = instance_descriptors();
  int mutable_count = 0;
  int const_count = 0;
  for (InternalIndex i : IterateOwnDescriptors()) {
    PropertyDetails details = descriptors->GetDetails(i);
    if (details.location() == PropertyLocation::kField) {
      switch (details.constness()) {
        case PropertyConstness::kMutable:
          mutable_count++;
          break;
        case PropertyConstness::kConst:
          const_count++;
          break;
      }
    }
  }
  return FieldCounts(mutable_count, const_count);
}
References v8::internal::PropertyDetails::constness(), v8::internal::instance_descriptors, IterateOwnDescriptors(), v8::internal::kConst, v8::internal::kField, v8::internal::kMutable, and v8::internal::PropertyDetails::location().
GetInitialElements()
Tagged< FixedArrayBase > v8::internal::Map::GetInitialElements () const [inline]
Definition at line 262 of file map-inl.h.
                                                     {
  Tagged<FixedArrayBase> result;
  if (has_fast_elements() || has_fast_string_wrapper_elements() ||
      has_any_nonextensible_elements()) {
    result = GetReadOnlyRoots().empty_fixed_array();
  } else if (has_typed_array_or_rab_gsab_typed_array_elements()) {
    result = GetReadOnlyRoots().empty_byte_array();
  } else if (has_dictionary_elements()) {
    result = GetReadOnlyRoots().empty_slow_element_dictionary();
  } else {
    UNREACHABLE();
  }
  DCHECK(!HeapLayout::InYoungGeneration(result));
  return result;
}
References v8::internal::DCHECK(), v8::internal::GetReadOnlyRoots(), has_any_nonextensible_elements(), has_dictionary_elements(), has_fast_elements(), has_fast_string_wrapper_elements(), has_typed_array_or_rab_gsab_typed_array_elements(), v8::internal::HeapLayout::InYoungGeneration(), v8::base::internal::result, and v8::internal::UNREACHABLE().
GetInObjectProperties()
int v8::internal::Map::GetInObjectProperties () const [inline]
Definition at line 341 of file map-inl.h.
                                     {
  DCHECK(IsJSObjectMap(*this));
  return instance_size_in_words() - GetInObjectPropertiesStartInWords();
}
References v8::internal::DCHECK(), and GetInObjectPropertiesStartInWords().
Referenced by EquivalentToForNormalization(), HasOutOfObjectProperties(), InstancesNeedRewriting(), SetInObjectUnusedPropertyFields(), and TooManyFastProperties().
GetInObjectPropertiesStartInWords()
int v8::internal::Map::GetInObjectPropertiesStartInWords () const [inline]
Definition at line 324 of file map-inl.h.
                                                 {
  DCHECK(IsJSObjectMap(*this));
  return inobject_properties_start_or_constructor_function_index();
}
References v8::internal::DCHECK().
Referenced by GetInObjectProperties(), and GetInObjectPropertyOffset().
GetInObjectPropertyOffset()
int v8::internal::Map::GetInObjectPropertyOffset (int index) const [inline]
Definition at line 363 of file map-inl.h.
                                                  {
  return (GetInObjectPropertiesStartInWords() + index) * kTaggedSize;
}
References GetInObjectPropertiesStartInWords(), v8::internal::index, and v8::internal::kTaggedSize.
Referenced by SetInObjectUnusedPropertyFields().
GetLastDescriptorDetails()
PropertyDetails v8::internal::Map::GetLastDescriptorDetails (Isolate * isolate) const [inline]
Definition at line 222 of file map-inl.h.
                                                                    {
  return instance_descriptors(isolate)->GetDetails(LastAdded());
}
References v8::internal::instance_descriptors, isolate, and LastAdded().
GetLastDescriptorName()
Tagged< Name > v8::internal::Map::GetLastDescriptorName (Isolate * isolate) const [inline]
Definition at line 218 of file map-inl.h.
                                                              {
  return instance_descriptors(isolate)->GetKey(LastAdded());
}
References v8::internal::instance_descriptors, isolate, and LastAdded().
GetMapFor()
Tagged< Map > v8::internal::Map::GetMapFor (ReadOnlyRoots roots, InstanceType type) [inline], [static]
Definition at line 874 of file map-inl.h.
                                                                 {
  RootIndex map_idx = TryGetMapRootIdxFor(type).value();
  return UncheckedCast<Map>(roots.object_at(map_idx));
}
References v8::internal::ReadOnlyRoots::object_at(), TryGetMapRootIdxFor(), and v8::internal::tracing::type.
Referenced by v8::internal::FactoryBase< Impl >::NewStruct().
GetObjectCreateMap()
DirectHandle< Map > v8::internal::Map::GetObjectCreateMap (Isolate * isolate, DirectHandle< JSPrototype > prototype) [static]
Definition at line 914 of file map.cc.
                                                                               {
  DirectHandle<Map> map(
      isolate->native_context()->object_function()->initial_map(), isolate);
  if (map->prototype() == *prototype) return map;
  if (IsNull(*prototype, isolate)) {
    return isolate->slow_object_with_null_prototype_map();
  }
  if (IsJSObjectThatCanBeTrackedAsPrototype(*prototype)) {
    DirectHandle<JSObject> js_prototype = Cast<JSObject>(prototype);
    if (!js_prototype->map()->is_prototype_map()) {
      JSObject::OptimizeAsPrototype(js_prototype);
    }
    DirectHandle<PrototypeInfo> info =
        Map::GetOrCreatePrototypeInfo(js_prototype, isolate);
    // TODO(verwaest): Use inobject slack tracking for this map.
    Tagged<HeapObject> map_obj;
    if (info->ObjectCreateMap().GetHeapObjectIfWeak(&map_obj)) {
      map = direct_handle(Cast<Map>(map_obj), isolate);
    } else {
      map = Map::CopyInitialMap(isolate, map);
      Map::SetPrototype(isolate, map, prototype);
      PrototypeInfo::SetObjectCreateMap(info, map, isolate);
    }
    return map;
  }
  return Map::TransitionRootMapToPrototypeForNewObject(isolate, map, prototype);
}
References CopyInitialMap(), v8::internal::direct_handle(), GetOrCreatePrototypeInfo(), v8::internal::IsJSObjectThatCanBeTrackedAsPrototype(), v8::internal::IsNull(), isolate, v8::internal::Isolate::native_context(), v8::internal::JSObject::OptimizeAsPrototype(), v8::internal::prototype, v8::internal::PrototypeInfo::SetObjectCreateMap(), SetPrototype(), and TransitionRootMapToPrototypeForNewObject().
Referenced by v8::internal::JSObject::ObjectCreate().
GetOrCreatePrototypeChainValidityCell()
Handle< UnionOf< Smi, Cell > > v8::internal::Map::GetOrCreatePrototypeChainValidityCell (DirectHandle< Map > map, Isolate * isolate, DirectHandle< PrototypeInfo > * out_prototype_info = nullptr) [static]
Definition at line 2430 of file map.cc.
                                                     {
  DirectHandle<Map> validity_cell_holder_map;
  {
    Tagged<Map> holder_map;
    if (!TryGetValidityCellHolderMap(*map, isolate, &holder_map)) {
      // Prototype value is not a JSObject.
      return handle(Map::kPrototypeChainValidSmi, isolate);
    }
    validity_cell_holder_map = direct_handle(holder_map, isolate);
  }
  // Ensure the prototype is registered with its own prototypes so its cell
  // will be invalidated when necessary.
  JSObject::LazyRegisterPrototypeUser(validity_cell_holder_map, isolate);
  if (out_prototype_info) {
    *out_prototype_info =
        Map::GetOrCreatePrototypeInfo(validity_cell_holder_map, isolate);
  }
  {
    Tagged<Object> maybe_cell =
        validity_cell_holder_map->prototype_validity_cell(kRelaxedLoad);
    // Return existing cell if it's still valid.
    if (IsCell(maybe_cell)) {
      Tagged<Cell> cell = Cast<Cell>(maybe_cell);
      if (cell->value() == Map::kPrototypeChainValidSmi) {
        return handle(cell, isolate);
      }
    }
  }
  // Otherwise create a new cell.
  Handle<Cell> cell = isolate->factory()->NewCell(Map::kPrototypeChainValidSmi);
  validity_cell_holder_map->set_prototype_validity_cell(*cell, kRelaxedStore);
  return cell;
}
References v8::internal::direct_handle(), v8::internal::Isolate::factory(), GetOrCreatePrototypeInfo(), v8::internal::handle(), isolate, kPrototypeChainValidSmi, v8::kRelaxedLoad, v8::kRelaxedStore, v8::internal::JSObject::LazyRegisterPrototypeUser(), v8::internal::Factory::NewCell(), and TryGetValidityCellHolderMap().
Referenced by v8::internal::LookupIterator::ApplyTransitionToDataProperty(), v8::internal::KeyAccumulator::GetKeys(), v8::internal::Genesis::InitializeGlobal(), v8::internal::LoadHandler::LoadFromPrototype(), v8::internal::LoadHandler::LoadFullChain(), v8::internal::LoadHandler::LoadNonExistent(), v8::internal::anonymous_namespace{ic.cc}::SetCloneTargetMap(), v8::internal::KeyedStoreIC::StoreElementHandler(), v8::internal::StoreHandler::StoreElementTransition(), v8::internal::StoreHandler::StoreThroughPrototype(), and v8::internal::StoreHandler::StoreTransition().
GetOrCreatePrototypeInfo()
DirectHandle< PrototypeInfo > v8::internal::Map::GetOrCreatePrototypeInfo (DirectHandle< Map > prototype_map, Isolate * isolate) [static]
Definition at line 2388 of file map.cc.
                                                        {
  DCHECK(IsJSObjectThatCanBeTrackedAsPrototype(*prototype));
  {
    Tagged<PrototypeInfo> prototype_info;
    if (prototype->map()->TryGetPrototypeInfo(&prototype_info)) {
      return direct_handle(prototype_info, isolate);
    }
  }
  DirectHandle<PrototypeInfo> proto_info =
      isolate->factory()->NewPrototypeInfo();
  prototype->map()->set_prototype_info(*proto_info, kReleaseStore);
  return proto_info;
}
References v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::IsJSObjectThatCanBeTrackedAsPrototype(), isolate, v8::kReleaseStore, v8::internal::Factory::NewPrototypeInfo(), and v8::internal::prototype.
Referenced by GetDerivedMap(), v8::internal::Module::GetModuleNamespace(), GetObjectCreateMap(), GetOrCreatePrototypeChainValidityCell(), v8::internal::JSObject::LazyRegisterPrototypeUser(), SetShouldBeFastPrototypeMap(), and v8::internal::JSObject::UnregisterPrototypeUser().
GetPrototypeChainRootMap()
Tagged< Map > v8::internal::Map::GetPrototypeChainRootMap (Isolate * isolate) const
Definition at line 37 of file map.cc.
                                                                {
  DisallowGarbageCollection no_alloc;
  if (IsJSReceiverMap(*this)) {
    return *this;
  }
  int constructor_function_index = GetConstructorFunctionIndex();
  if (constructor_function_index != Map::kNoConstructorFunctionIndex) {
    Tagged<Context> native_context = isolate->context()->native_context();
    Tagged<JSFunction> constructor_function =
        Cast<JSFunction>(native_context->GetNoCell(constructor_function_index));
    return constructor_function->initial_map();
  }
  return ReadOnlyRoots(isolate).null_value()->map();
}
References v8::internal::Isolate::context(), GetConstructorFunctionIndex(), isolate, kNoConstructorFunctionIndex, and v8::internal::native_context.
GetVisitorId()
VisitorId v8::internal::Map::GetVisitorId (Tagged< Map > map) [static]
Definition at line 66 of file map.cc.
                                           {
  static_assert(kVisitorIdCount <= 256);
  const int instance_type = map->instance_type();
  if (instance_type < FIRST_NONSTRING_TYPE) {
    switch (instance_type & kStringRepresentationMask) {
      case kSeqStringTag:
        if ((instance_type & kStringEncodingMask) == kOneByteStringTag) {
          return kVisitSeqOneByteString;
        } else {
          return kVisitSeqTwoByteString;
        }
      case kConsStringTag:
        if (IsShortcutCandidate(instance_type)) {
          return kVisitShortcutCandidate;
        } else {
          return kVisitConsString;
        }
      case kSlicedStringTag:
        return kVisitSlicedString;
      case kExternalStringTag:
        return kVisitExternalString;
      case kThinStringTag:
        return kVisitThinString;
    }
    UNREACHABLE();
  }
  if (InstanceTypeChecker::IsJSApiObject(map->instance_type())) {
    return kVisitJSApiObject;
  }
  switch (instance_type) {
    case FILLER_TYPE:
      return kVisitFiller;
    case FREE_SPACE_TYPE:
      return kVisitFreeSpace;
    case EMBEDDER_DATA_ARRAY_TYPE:
      return kVisitEmbedderDataArray;
    case NAME_TO_INDEX_HASH_TABLE_TYPE:
    case REGISTERED_SYMBOL_TABLE_TYPE:
    case HASH_TABLE_TYPE:
    case ORDERED_HASH_MAP_TYPE:
    case ORDERED_HASH_SET_TYPE:
    case ORDERED_NAME_DICTIONARY_TYPE:
    case NAME_DICTIONARY_TYPE:
    case SIMPLE_NAME_DICTIONARY_TYPE:
    case GLOBAL_DICTIONARY_TYPE:
    case NUMBER_DICTIONARY_TYPE:
    case SIMPLE_NUMBER_DICTIONARY_TYPE:
      return kVisitFixedArray;
    case SLOPPY_ARGUMENTS_ELEMENTS_TYPE:
      return kVisitSloppyArgumentsElements;
    case AWAIT_CONTEXT_TYPE:
    case BLOCK_CONTEXT_TYPE:
    case CATCH_CONTEXT_TYPE:
    case DEBUG_EVALUATE_CONTEXT_TYPE:
    case EVAL_CONTEXT_TYPE:
    case FUNCTION_CONTEXT_TYPE:
    case MODULE_CONTEXT_TYPE:
    case SCRIPT_CONTEXT_TYPE:
    case WITH_CONTEXT_TYPE:
      return kVisitContext;
    case NATIVE_CONTEXT_TYPE:
      return kVisitNativeContext;
    case CONTEXT_CELL_TYPE:
      return kVisitContextCell;
    case EPHEMERON_HASH_TABLE_TYPE:
      return kVisitEphemeronHashTable;
    case PROPERTY_ARRAY_TYPE:
      return kVisitPropertyArray;
    case FEEDBACK_CELL_TYPE:
      return kVisitFeedbackCell;
    case FEEDBACK_METADATA_TYPE:
      return kVisitFeedbackMetadata;
    case ODDBALL_TYPE:
      return kVisitOddball;
    case HOLE_TYPE:
      return kVisitHole;
    case MAP_TYPE:
      return kVisitMap;
    case CELL_TYPE:
      return kVisitCell;
    case PROPERTY_CELL_TYPE:
      return kVisitPropertyCell;
    case TRANSITION_ARRAY_TYPE:
      return kVisitTransitionArray;
    case JS_WEAK_MAP_TYPE:
    case JS_WEAK_SET_TYPE:
      return kVisitJSWeakCollection;
    case ACCESSOR_INFO_TYPE:
      return kVisitAccessorInfo;
    case INTERCEPTOR_INFO_TYPE:
      return kVisitInterceptorInfo;
    case FUNCTION_TEMPLATE_INFO_TYPE:
      return kVisitFunctionTemplateInfo;
    case OBJECT_TEMPLATE_INFO_TYPE:
      return kVisitStruct;
    case SYMBOL_TYPE:
      return kVisitSymbol;
    case JS_ARRAY_BUFFER_TYPE:
      return kVisitJSArrayBuffer;
    case JS_DATA_VIEW_TYPE:
    case JS_RAB_GSAB_DATA_VIEW_TYPE:
      return kVisitJSDataViewOrRabGsabDataView;
    case JS_EXTERNAL_OBJECT_TYPE:
      return kVisitJSExternalObject;
    case JS_FUNCTION_TYPE:
    case JS_CLASS_CONSTRUCTOR_TYPE:
    case JS_PROMISE_CONSTRUCTOR_TYPE:
    case JS_REG_EXP_CONSTRUCTOR_TYPE:
    case JS_ARRAY_CONSTRUCTOR_TYPE:
#define TYPED_ARRAY_CONSTRUCTORS_SWITCH(Type, type, TYPE, Ctype) \
  case TYPE##_TYPED_ARRAY_CONSTRUCTOR_TYPE:
      TYPED_ARRAYS(TYPED_ARRAY_CONSTRUCTORS_SWITCH)
#undef TYPED_ARRAY_CONSTRUCTORS_SWITCH
      return kVisitJSFunction;
    case JS_TYPED_ARRAY_TYPE:
      return kVisitJSTypedArray;
    case DOUBLE_STRING_CACHE_TYPE:
      return kVisitDoubleStringCache;
    case SMALL_ORDERED_HASH_MAP_TYPE:
      return kVisitSmallOrderedHashMap;
    case SMALL_ORDERED_HASH_SET_TYPE:
      return kVisitSmallOrderedHashSet;
    case SMALL_ORDERED_NAME_DICTIONARY_TYPE:
      return kVisitSmallOrderedNameDictionary;
    case SWISS_NAME_DICTIONARY_TYPE:
      return kVisitSwissNameDictionary;
    case SHARED_FUNCTION_INFO_TYPE:
      return kVisitSharedFunctionInfo;
    case PREPARSE_DATA_TYPE:
      return kVisitPreparseData;
    case COVERAGE_INFO_TYPE:
      return kVisitCoverageInfo;
    // Objects that may have embedder fields but otherwise are just a regular
    // JSObject.
    case JS_PROMISE_TYPE: {
      const bool has_raw_data_fields =
          COMPRESS_POINTERS_BOOL && JSObject::GetEmbedderFieldCount(map) > 0;
      return has_raw_data_fields ? kVisitJSObject : kVisitJSObjectFast;
    }
    // Objects that are guaranteed to not have any embedder fields and just
    // behave like regular JSObject.
    case JS_ARGUMENTS_OBJECT_TYPE:
    case JS_ARRAY_ITERATOR_PROTOTYPE_TYPE:
    case JS_ARRAY_ITERATOR_TYPE:
    case JS_ARRAY_TYPE:
    case JS_ASYNC_DISPOSABLE_STACK_TYPE:
    case JS_ASYNC_FROM_SYNC_ITERATOR_TYPE:
    case JS_ASYNC_FUNCTION_OBJECT_TYPE:
    case JS_ASYNC_GENERATOR_OBJECT_TYPE:
    case JS_CONTEXT_EXTENSION_OBJECT_TYPE:
    case JS_DISPOSABLE_STACK_BASE_TYPE:
    case JS_ERROR_TYPE:
    case JS_GENERATOR_OBJECT_TYPE:
    case JS_ITERATOR_FILTER_HELPER_TYPE:
    case JS_ITERATOR_MAP_HELPER_TYPE:
    case JS_ITERATOR_TAKE_HELPER_TYPE:
    case JS_ITERATOR_DROP_HELPER_TYPE:
    case JS_ITERATOR_FLAT_MAP_HELPER_TYPE:
    case JS_ITERATOR_PROTOTYPE_TYPE:
    case JS_MAP_ITERATOR_PROTOTYPE_TYPE:
    case JS_MAP_KEY_ITERATOR_TYPE:
    case JS_MAP_KEY_VALUE_ITERATOR_TYPE:
    case JS_MAP_TYPE:
    case JS_MAP_VALUE_ITERATOR_TYPE:
    case JS_MESSAGE_OBJECT_TYPE:
    case JS_MODULE_NAMESPACE_TYPE:
    case JS_OBJECT_PROTOTYPE_TYPE:
    case JS_OBJECT_TYPE:
    case JS_PRIMITIVE_WRAPPER_TYPE:
    case JS_PROMISE_PROTOTYPE_TYPE:
    case JS_REG_EXP_PROTOTYPE_TYPE:
    case JS_REG_EXP_STRING_ITERATOR_TYPE:
    case JS_SET_ITERATOR_PROTOTYPE_TYPE:
    case JS_SET_KEY_VALUE_ITERATOR_TYPE:
    case JS_SET_PROTOTYPE_TYPE:
    case JS_SET_TYPE:
    case JS_SET_VALUE_ITERATOR_TYPE:
    case JS_SYNC_DISPOSABLE_STACK_TYPE:
    case JS_SHADOW_REALM_TYPE:
    case JS_SHARED_ARRAY_TYPE:
    case JS_SHARED_STRUCT_TYPE:
    case JS_STRING_ITERATOR_PROTOTYPE_TYPE:
    case JS_STRING_ITERATOR_TYPE:
#ifdef V8_TEMPORAL_SUPPORT
    case JS_TEMPORAL_DURATION_TYPE:
    case JS_TEMPORAL_INSTANT_TYPE:
    case JS_TEMPORAL_PLAIN_DATE_TYPE:
    case JS_TEMPORAL_PLAIN_DATE_TIME_TYPE:
    case JS_TEMPORAL_PLAIN_MONTH_DAY_TYPE:
    case JS_TEMPORAL_PLAIN_TIME_TYPE:
    case JS_TEMPORAL_PLAIN_YEAR_MONTH_TYPE:
    case JS_TEMPORAL_ZONED_DATE_TIME_TYPE:
#endif // V8_TEMPORAL_SUPPORT
    case JS_TYPED_ARRAY_PROTOTYPE_TYPE:
    case JS_VALID_ITERATOR_WRAPPER_TYPE:
    case JS_RAW_JSON_TYPE:
#ifdef V8_INTL_SUPPORT
    case JS_V8_BREAK_ITERATOR_TYPE:
    case JS_COLLATOR_TYPE:
    case JS_DATE_TIME_FORMAT_TYPE:
    case JS_DISPLAY_NAMES_TYPE:
    case JS_DURATION_FORMAT_TYPE:
    case JS_LIST_FORMAT_TYPE:
    case JS_LOCALE_TYPE:
    case JS_NUMBER_FORMAT_TYPE:
    case JS_PLURAL_RULES_TYPE:
    case JS_RELATIVE_TIME_FORMAT_TYPE:
    case JS_SEGMENT_ITERATOR_TYPE:
    case JS_SEGMENTER_TYPE:
    case JS_SEGMENTS_TYPE:
#endif // V8_INTL_SUPPORT
#if V8_ENABLE_WEBASSEMBLY
    case WASM_EXCEPTION_PACKAGE_TYPE:
    case WASM_MODULE_OBJECT_TYPE:
    case WASM_VALUE_OBJECT_TYPE:
#endif // V8_ENABLE_WEBASSEMBLY
    case JS_BOUND_FUNCTION_TYPE:
    case JS_WRAPPED_FUNCTION_TYPE: {
      CHECK_EQ(0, JSObject::GetEmbedderFieldCount(map));
      return kVisitJSObjectFast;
    }
    case JS_REG_EXP_TYPE:
      return kVisitJSRegExp;
    // Objects that are used as API wrapper objects and can have embedder
    // fields. Note that there's more of these kinds (e.g. JS_ARRAY_BUFFER_TYPE)
    // but they have their own visitor id for other reasons
    case JS_API_OBJECT_TYPE:
    case JS_GLOBAL_PROXY_TYPE:
    case JS_GLOBAL_OBJECT_TYPE:
    case JS_SPECIAL_API_OBJECT_TYPE:
      return kVisitJSApiObject;
    case CPP_HEAP_EXTERNAL_OBJECT_TYPE:
      return kVisitCppHeapExternalObject;
    case JS_DATE_TYPE:
      return kVisitJSDate;
    case JS_WEAK_REF_TYPE:
      return kVisitJSWeakRef;
    case WEAK_CELL_TYPE:
      return kVisitWeakCell;
    case JS_FINALIZATION_REGISTRY_TYPE:
      return kVisitJSFinalizationRegistry;
    case JS_ATOMICS_MUTEX_TYPE:
    case JS_ATOMICS_CONDITION_TYPE:
      return kVisitJSSynchronizationPrimitive;
    case HEAP_NUMBER_TYPE:
      return kVisitHeapNumber;
    case FOREIGN_TYPE:
      return kVisitForeign;
    case BIGINT_TYPE:
      return kVisitBigInt;
    case ALLOCATION_SITE_TYPE:
      return kVisitAllocationSite;
    // Here we list all structs explicitly on purpose. This forces new structs
    // to choose a VisitorId explicitly.
    case PROMISE_FULFILL_REACTION_JOB_TASK_TYPE:
    case PROMISE_REJECT_REACTION_JOB_TASK_TYPE:
    case CALLABLE_TASK_TYPE:
    case CALLBACK_TASK_TYPE:
    case PROMISE_RESOLVE_THENABLE_JOB_TASK_TYPE:
    case ACCESS_CHECK_INFO_TYPE:
    case ACCESSOR_PAIR_TYPE:
    case ALIASED_ARGUMENTS_ENTRY_TYPE:
    case ALLOCATION_MEMENTO_TYPE:
    case ARRAY_BOILERPLATE_DESCRIPTION_TYPE:
    case ASYNC_GENERATOR_REQUEST_TYPE:
    case BREAK_POINT_TYPE:
    case BREAK_POINT_INFO_TYPE:
    case CLASS_BOILERPLATE_TYPE:
    case CLASS_POSITIONS_TYPE:
    case ENUM_CACHE_TYPE:
    case ERROR_STACK_DATA_TYPE:
    case FUNCTION_TEMPLATE_RARE_DATA_TYPE:
    case MODULE_REQUEST_TYPE:
    case PROMISE_CAPABILITY_TYPE:
    case PROMISE_REACTION_TYPE:
    case PROPERTY_DESCRIPTOR_OBJECT_TYPE:
    case SCRIPT_TYPE:
    case SCRIPT_OR_MODULE_TYPE:
    case SOURCE_TEXT_MODULE_INFO_ENTRY_TYPE:
    case STACK_FRAME_INFO_TYPE:
    case STACK_TRACE_INFO_TYPE:
    case TEMPLATE_OBJECT_DESCRIPTION_TYPE:
    case TUPLE2_TYPE:
#if V8_ENABLE_WEBASSEMBLY
    case ASM_WASM_DATA_TYPE:
    case WASM_EXCEPTION_TAG_TYPE:
#endif
      return kVisitStruct;
    case PROTOTYPE_INFO_TYPE:
      return kVisitPrototypeInfo;
    case DEBUG_INFO_TYPE:
      return kVisitDebugInfo;
    case CALL_SITE_INFO_TYPE:
      return kVisitCallSiteInfo;
    case BYTECODE_WRAPPER_TYPE:
      return kVisitBytecodeWrapper;
    case CODE_WRAPPER_TYPE:
      return kVisitCodeWrapper;
    case REG_EXP_BOILERPLATE_DESCRIPTION_TYPE:
      return kVisitRegExpBoilerplateDescription;
    case REG_EXP_DATA_WRAPPER_TYPE:
      return kVisitRegExpDataWrapper;
    case LOAD_HANDLER_TYPE:
    case STORE_HANDLER_TYPE:
      return kVisitDataHandler;
    case SOURCE_TEXT_MODULE_TYPE:
      return kVisitSourceTextModule;
    case SYNTHETIC_MODULE_TYPE:
      return kVisitSyntheticModule;
#if V8_ENABLE_WEBASSEMBLY
    case WASM_ARRAY_TYPE:
      return kVisitWasmArray;
    case WASM_MEMORY_MAP_DESCRIPTOR_TYPE:
      return kVisitWasmMemoryMapDescriptor;
    case WASM_FUNC_REF_TYPE:
      return kVisitWasmFuncRef;
    case WASM_GLOBAL_OBJECT_TYPE:
      return kVisitWasmGlobalObject;
    case WASM_INSTANCE_OBJECT_TYPE:
      return kVisitWasmInstanceObject;
    case WASM_MEMORY_OBJECT_TYPE:
      return kVisitWasmMemoryObject;
    case WASM_NULL_TYPE:
      return kVisitWasmNull;
    case WASM_RESUME_DATA_TYPE:
      return kVisitWasmResumeData;
    case WASM_STRUCT_TYPE:
      return kVisitWasmStruct;
    case WASM_DESCRIPTOR_OPTIONS_TYPE:
      return kVisitWasmDescriptorOptions;
    case WASM_SUSPENDER_OBJECT_TYPE:
      return kVisitWasmSuspenderObject;
    case WASM_CONTINUATION_OBJECT_TYPE:
      return kVisitWasmContinuationObject;
    case WASM_SUSPENDING_OBJECT_TYPE:
      return kVisitWasmSuspendingObject;
    case WASM_TABLE_OBJECT_TYPE:
      return kVisitWasmTableObject;
    case WASM_TAG_OBJECT_TYPE:
      return kVisitWasmTagObject;
    case WASM_TYPE_INFO_TYPE:
      return kVisitWasmTypeInfo;
#endif // V8_ENABLE_WEBASSEMBLY
#define MAKE_TQ_CASE(TYPE, Name) \
  case TYPE: \
    return kVisit##Name;
      TORQUE_INSTANCE_TYPE_TO_BODY_DESCRIPTOR_LIST(MAKE_TQ_CASE)
#undef MAKE_TQ_CASE
#define CASE(TypeCamelCase, TYPE_UPPER_CASE) \
  case TYPE_UPPER_CASE##_TYPE: \
    return kVisit##TypeCamelCase;
      SIMPLE_HEAP_OBJECT_LIST2(CASE)
      CONCRETE_TRUSTED_OBJECT_TYPE_LIST2(CASE)
#undef CASE
  }
  std::string name = ToString(map->instance_type());
  FATAL("Instance type %s (code %d) not mapped to VisitorId.", name.c_str(),
        instance_type);
}
References v8::internal::BIGINT_TYPE, CASE, CHECK_EQ, COMPRESS_POINTERS_BOOL, CONCRETE_TRUSTED_OBJECT_TYPE_LIST2, FATAL, v8::internal::FIRST_NONSTRING_TYPE, v8::internal::JSObject::GetEmbedderFieldCount(), instance_type(), v8::internal::IsShortcutCandidate(), v8::internal::kConsStringTag, v8::internal::kExternalStringTag, v8::internal::kOneByteStringTag, v8::internal::kSeqStringTag, v8::internal::kSlicedStringTag, v8::internal::kStringEncodingMask, v8::internal::kStringRepresentationMask, v8::internal::kThinStringTag, v8::internal::kVisitorIdCount, MAKE_TQ_CASE, v8::internal::name, SIMPLE_HEAP_OBJECT_LIST2, v8::internal::string, v8::internal::ToString(), TYPED_ARRAY_CONSTRUCTORS_SWITCH, TYPED_ARRAYS, and v8::internal::UNREACHABLE().
Referenced by v8::internal::MapUpdater::CompleteInobjectSlackTracking(), Create(), v8::internal::Factory::InitializeMap(), and v8::internal::anonymous_namespace{setup-heap-internal.cc}::InitializePartialMap().
has_any_nonextensible_elements()
bool v8::internal::Map::has_any_nonextensible_elements () const [inline]
Definition at line 682 of file map-inl.h.
                                               {
  return IsAnyNonextensibleElementsKind(elements_kind());
}
References v8::internal::IsAnyNonextensibleElementsKind().
Referenced by GetInitialElements().
has_any_typed_array_or_wasm_array_elements()
bool v8::internal::Map::has_any_typed_array_or_wasm_array_elements () const [inline]
Definition at line 669 of file map-inl.h.
                                                           {
  ElementsKind kind = elements_kind();
  return IsTypedArrayOrRabGsabTypedArrayElementsKind(kind) ||
#if V8_ENABLE_WEBASSEMBLY
         IsWasmArrayElementsKind(kind) ||
#endif // V8_ENABLE_WEBASSEMBLY
         false;
}
References v8::internal::IsTypedArrayOrRabGsabTypedArrayElementsKind(), and v8::internal::IsWasmArrayElementsKind().
has_dictionary_elements()
bool v8::internal::Map::has_dictionary_elements () const [inline]
Definition at line 678 of file map-inl.h.
                                        {
  return IsDictionaryElementsKind(elements_kind());
}
References v8::internal::IsDictionaryElementsKind().
Referenced by GetInitialElements().
has_fast_double_elements()
bool v8::internal::Map::has_fast_double_elements () const [inline]
Definition at line 641 of file map-inl.h.
                                         {
  return IsDoubleElementsKind(elements_kind());
}
References v8::internal::IsDoubleElementsKind().
has_fast_elements()
bool v8::internal::Map::has_fast_elements () const [inline]
Definition at line 645 of file map-inl.h.
                                  {
  return IsFastElementsKind(elements_kind());
}
References v8::internal::IsFastElementsKind().
Referenced by GetInitialElements().
has_fast_object_elements()
bool v8::internal::Map::has_fast_object_elements () const [inline]
Definition at line 633 of file map-inl.h.
                                         {
  return IsObjectElementsKind(elements_kind());
}
References v8::internal::IsObjectElementsKind().
has_fast_packed_elements()
bool v8::internal::Map::has_fast_packed_elements () const [inline]
Definition at line 649 of file map-inl.h.
                                         {
  return IsFastPackedElementsKind(elements_kind());
}
References v8::internal::IsFastPackedElementsKind().
has_fast_sloppy_arguments_elements()
bool v8::internal::Map::has_fast_sloppy_arguments_elements () const [inline]
Definition at line 657 of file map-inl.h.
                                                   {
  return elements_kind() == FAST_SLOPPY_ARGUMENTS_ELEMENTS;
}
References v8::internal::FAST_SLOPPY_ARGUMENTS_ELEMENTS.
has_fast_smi_elements()
bool v8::internal::Map::has_fast_smi_elements () const [inline]
Definition at line 629 of file map-inl.h.
                                      {
  return IsSmiElementsKind(elements_kind());
}
References v8::internal::IsSmiElementsKind().
has_fast_smi_or_object_elements()
bool v8::internal::Map::has_fast_smi_or_object_elements () const [inline]
Definition at line 637 of file map-inl.h.
                                                {
  return IsSmiOrObjectElementsKind(elements_kind());
}
References v8::internal::IsSmiOrObjectElementsKind().
has_fast_string_wrapper_elements()
bool v8::internal::Map::has_fast_string_wrapper_elements () const [inline]
Definition at line 661 of file map-inl.h.
                                                 {
  return elements_kind() == FAST_STRING_WRAPPER_ELEMENTS;
}
References v8::internal::FAST_STRING_WRAPPER_ELEMENTS.
Referenced by GetInitialElements().
has_frozen_elements()
bool v8::internal::Map::has_frozen_elements () const [inline]
Definition at line 694 of file map-inl.h.
                                    {
  return IsFrozenElementsKind(elements_kind());
}
References v8::internal::IsFrozenElementsKind().
has_nonextensible_elements()
bool v8::internal::Map::has_nonextensible_elements () const [inline]
Definition at line 686 of file map-inl.h.
                                           {
  return IsNonextensibleElementsKind(elements_kind());
}
References v8::internal::IsNonextensibleElementsKind().
has_prototype_info()
bool v8::internal::Map::has_prototype_info () const [inline]
Definition at line 586 of file map-inl.h.
                                   {
  DCHECK(is_prototype_map());
  return PrototypeInfo::IsPrototypeInfoFast(prototype_info());
}
References v8::internal::DCHECK(), v8::internal::is_prototype_map, and v8::internal::PrototypeInfo::IsPrototypeInfoFast().
Referenced by should_be_fast_prototype_map().
has_sealed_elements()
bool v8::internal::Map::has_sealed_elements () const [inline]
Definition at line 690 of file map-inl.h.
                                    {
  return IsSealedElementsKind(elements_kind());
}
References v8::internal::IsSealedElementsKind().
has_shared_array_elements()
bool v8::internal::Map::has_shared_array_elements () const [inline]
Definition at line 698 of file map-inl.h.
                                          {
  return IsSharedArrayElementsKind(elements_kind());
}
References v8::internal::IsSharedArrayElementsKind().
has_sloppy_arguments_elements()
bool v8::internal::Map::has_sloppy_arguments_elements () const [inline]
Definition at line 653 of file map-inl.h.
                                              {
  return IsSloppyArgumentsElementsKind(elements_kind());
}
References v8::internal::IsSloppyArgumentsElementsKind().
has_typed_array_or_rab_gsab_typed_array_elements()
bool v8::internal::Map::has_typed_array_or_rab_gsab_typed_array_elements () const [inline]
Definition at line 665 of file map-inl.h.
                                                                 {
  return IsTypedArrayOrRabGsabTypedArrayElementsKind(elements_kind());
}
References v8::internal::IsTypedArrayOrRabGsabTypedArrayElementsKind().
Referenced by GetInitialElements().
Hash()
int v8::internal::Map::Hash (Isolate * isolate, Tagged< HeapObject > prototype)
Definition at line 2261 of file map.cc.
                                                            {
  // For performance reasons we only hash the 2 most variable fields of a map:
  // prototype and bit_field2.
  int prototype_hash;
  if (IsNull(prototype)) {
    // No identity hash for null, so just pick a random number.
    prototype_hash = 1;
  } else {
    Tagged<JSReceiver> receiver = Cast<JSReceiver>(prototype);
    prototype_hash = receiver->GetOrCreateIdentityHash(isolate).value();
  }
  return prototype_hash ^ bit_field2();
}
References v8::internal::bit_field2, v8::internal::IsNull(), isolate, and v8::internal::prototype.
HasOutOfObjectProperties()
bool v8::internal::Map::HasOutOfObjectProperties () const [inline]
Definition at line 334 of file map-inl.h.
                                         {
  bool ret = used_or_unused_instance_size_in_words() < JSObject::kFieldsAdded;
  DCHECK_EQ(ret, GetInObjectProperties() <
                     NumberOfFields(ConcurrencyMode::kSynchronous));
  return ret;
}
References DCHECK_EQ, GetInObjectProperties(), v8::internal::JSObject::kFieldsAdded, v8::internal::kSynchronous, and NumberOfFields().
init_prototype_and_constructor_or_back_pointer()
void v8::internal::Map::init_prototype_and_constructor_or_back_pointer (ReadOnlyRoots roots) [inline]
InitializeDescriptors()
void v8::internal::Map::InitializeDescriptors (Isolate * isolate, Tagged< DescriptorArray > descriptors) [inline]
Definition at line 783 of file map-inl.h.
                                                                     {
  SetInstanceDescriptors(isolate, descriptors,
                         descriptors->number_of_descriptors());
}
References isolate, and SetInstanceDescriptors().
InobjectSlackTrackingStep()
void v8::internal::Map::InobjectSlackTrackingStep (Isolate * isolate) [inline]
Definition at line 1037 of file map-inl.h.
                                                    {
  DisallowGarbageCollection no_gc;
  // Slack tracking should only be performed on an initial map.
  DCHECK(IsUndefined(GetBackPointer()));
  if (!this->IsInobjectSlackTrackingInProgress()) return;
  int counter = construction_counter();
  set_construction_counter(counter - 1);
  if (counter == kSlackTrackingCounterEnd) {
    MapUpdater::CompleteInobjectSlackTracking(isolate, *this);
  }
}
References v8::internal::MapUpdater::CompleteInobjectSlackTracking(), v8::internal::construction_counter, v8::internal::DCHECK(), IsInobjectSlackTrackingInProgress(), isolate, kSlackTrackingCounterEnd, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
InstallDescriptors()
void v8::internal::Map::InstallDescriptors (Isolate * isolate, DirectHandle< Map > parent_map, DirectHandle< Map > child_map, InternalIndex new_descriptor, DirectHandle< DescriptorArray > descriptors, bool force_connect = false) [static], [private]
Definition at line 1675 of file map.cc.
                                                 {
  DCHECK(descriptors->IsSortedNoDuplicates());
  child->SetInstanceDescriptors(isolate, *descriptors,
                                new_descriptor.as_int() + 1);
  child->CopyUnusedPropertyFields(*parent);
  PropertyDetails details = descriptors->GetDetails(new_descriptor);
  if (details.location() == PropertyLocation::kField) {
    child->AccountAddedPropertyField();
  }
  DirectHandle<Name> name(descriptors->GetKey(new_descriptor), isolate);
  if (parent->may_have_interesting_properties() ||
      name->IsInteresting(isolate)) {
    child->set_may_have_interesting_properties(true);
  }
  ConnectTransition(isolate, parent, child, name, SIMPLE_PROPERTY_TRANSITION,
                    force_connect);
}
References v8::internal::InternalIndex::as_int(), ConnectTransition(), v8::internal::DCHECK(), isolate, v8::internal::kField, v8::internal::PropertyDetails::location(), v8::internal::name, and v8::internal::SIMPLE_PROPERTY_TRANSITION.
Referenced by AddMissingTransitions().
instance_type()
InstanceType v8::internal::Map::instance_type () const [inline]
Definition at line 274 of file map.h.
                                            {
    // TODO(solanes, v8:7790, v8:11353, v8:11945): Make this and the setter
    // non-atomic when TSAN sees the map's store synchronization.
    return static_cast<InstanceType>(
        RELAXED_READ_UINT16_FIELD(*this, kInstanceTypeOffset));
  }
References RELAXED_READ_UINT16_FIELD.
Referenced by CanHaveFastTransitionableElementsKind(), CanTransition(), EquivalentToForTransition(), GeneralizeIfCanHaveTransitionableFastElementsKind(), GetConstructorFunctionIndex(), GetVisitorId(), IsDetached(), and SetBackPointer().
InstanceSizeFromSlack()
int v8::internal::Map::InstanceSizeFromSlack (int slack) const [inline]
Definition at line 1059 of file map-inl.h.
                                              {
  return instance_size() - slack * kTaggedSize;
}
References v8::internal::kTaggedSize.
InstancesNeedRewriting() [1/2]
bool v8::internal::Map::InstancesNeedRewriting (Tagged< Map > target, ConcurrencyMode cmode) const
Definition at line 568 of file map.cc.
                                                              {
  int target_number_of_fields = target->NumberOfFields(cmode);
  int target_inobject = target->GetInObjectProperties();
  int target_unused = target->UnusedPropertyFields();
  int old_number_of_fields;
  return InstancesNeedRewriting(target, target_number_of_fields,
                                target_inobject, target_unused,
                                &old_number_of_fields, cmode);
}
Referenced by FindElementsKindTransitionedMap().
InstancesNeedRewriting() [2/2]
bool v8::internal::Map::InstancesNeedRewriting (Tagged< Map > target, int target_number_of_fields, int target_inobject, int target_unused, int * old_number_of_fields, ConcurrencyMode cmode) const
Definition at line 580 of file map.cc.
                                                              {
  // If fields were added (or removed), rewrite the instance.
  *old_number_of_fields = NumberOfFields(cmode);
  DCHECK(target_number_of_fields >= *old_number_of_fields);
  if (target_number_of_fields != *old_number_of_fields) return true;
  // If smi descriptors were replaced by double descriptors, rewrite.
  Tagged<DescriptorArray> old_desc = IsConcurrent(cmode)
                                         ? instance_descriptors(kAcquireLoad)
                                         : instance_descriptors();
  Tagged<DescriptorArray> new_desc =
      IsConcurrent(cmode) ? target->instance_descriptors(kAcquireLoad)
                          : target->instance_descriptors();
  for (InternalIndex i : IterateOwnDescriptors()) {
    if (new_desc->GetDetails(i).representation().IsDouble() !=
        old_desc->GetDetails(i).representation().IsDouble()) {
      return true;
    }
  }
  // If no fields were added, and no inobject properties were removed, setting
  // the map is sufficient.
  if (target_inobject == GetInObjectProperties()) return false;
  // In-object slack tracking may have reduced the object size of the new map.
  // In that case, succeed if all existing fields were inobject, and they still
  // fit within the new inobject size.
  DCHECK(target_inobject < GetInObjectProperties());
  if (target_number_of_fields <= target_inobject) {
    DCHECK(target_number_of_fields + target_unused == target_inobject);
    return false;
  }
  // Otherwise, properties will need to be moved to the backing store.
  return true;
}
References v8::internal::DCHECK(), GetInObjectProperties(), v8::internal::instance_descriptors, v8::internal::IsConcurrent(), IterateOwnDescriptors(), v8::kAcquireLoad, and NumberOfFields().
is_abandoned_prototype_map()
bool v8::internal::Map::is_abandoned_prototype_map () const [inline]
Definition at line 576 of file map-inl.h.
                                           {
  return is_prototype_map() && !owns_descriptors();
}
References v8::internal::is_prototype_map.
is_stable()
bool v8::internal::Map::is_stable () const [inline]
Definition at line 718 of file map-inl.h.
                          {
  return !Bits3::IsUnstableBit::decode(release_acquire_bit_field3());
}
References v8::internal::release_acquire_bit_field3.
Referenced by NotifyLeafMapLayoutChange().
IsDetached()
bool v8::internal::Map::IsDetached (Isolate * isolate) const [inline]
Definition at line 173 of file map-inl.h.
                                           {
  if (is_prototype_map()) return true;
  return instance_type() == JS_OBJECT_TYPE && NumberOfOwnDescriptors() > 0 &&
         IsUndefined(GetBackPointer(), isolate);
}
References instance_type(), v8::internal::is_prototype_map, isolate, and NumberOfOwnDescriptors().
Referenced by FindElementsKindTransitionedMap().
IsInobjectSlackTrackingInProgress()
bool v8::internal::Map::IsInobjectSlackTrackingInProgress () const [inline]
Definition at line 1033 of file map-inl.h.
                                                  {
  return construction_counter() != Map::kNoSlackTracking;
}
References v8::internal::construction_counter, and kNoSlackTracking.
Referenced by InobjectSlackTrackingStep(), and StartInobjectSlackTracking().
IsMapInArrayPrototypeChain()
bool v8::internal::Map::IsMapInArrayPrototypeChain (Isolate * isolate) const
Definition at line 1067 of file map.cc.
                                                           {
  if (isolate->initial_array_prototype()->map() == *this) {
    return true;
  }
  if (isolate->initial_object_prototype()->map() == *this) {
    return true;
  }
  return false;
}
References isolate.
IsMostGeneralFieldType()
bool v8::internal::Map::IsMostGeneralFieldType (Representation representation, Tagged< FieldType > field_type) [inline], [static]
Definition at line 157 of file map-inl.h.
                                                               {
  return !representation.IsHeapObject() || IsAny(field_type);
}
References v8::internal::IsAny(), and v8::internal::Representation::IsHeapObject().
Referenced by v8::internal::MapUpdater::BuildDescriptorArray(), and EquivalentToForElementsKindTransition().
IsPrototypeChainInvalidated()
bool v8::internal::Map::IsPrototypeChainInvalidated (Tagged< Map > map) [static]
Definition at line 2470 of file map.cc.
                                                     {
  DCHECK(map->is_prototype_map());
  Tagged<Object> maybe_cell = map->prototype_validity_cell(kRelaxedLoad);
  if (IsCell(maybe_cell)) {
    Tagged<Cell> cell = Cast<Cell>(maybe_cell);
    return cell->value() != Map::kPrototypeChainValidSmi;
  }
  return true;
}
References v8::internal::DCHECK(), kPrototypeChainValidSmi, and v8::kRelaxedLoad.
Referenced by v8::internal::anonymous_namespace{js-objects.cc}::MigrateFastToSlow(), and v8::internal::JSObject::SetNormalizedProperty().
IsPrototypeValidityCellValid()
bool v8::internal::Map::IsPrototypeValidityCellValid () const [inline]
Definition at line 921 of file map-inl.h.
                                             {
  Tagged<Object> validity_cell = prototype_validity_cell(kRelaxedLoad);
  if (IsSmi(validity_cell)) {
    // Smi validity cells should always be considered valid.
    DCHECK_EQ(Cast<Smi>(validity_cell).value(), Map::kPrototypeChainValid);
    return true;
  }
  Tagged<Smi> cell_value = Cast<Smi>(Cast<Cell>(validity_cell)->value());
  return cell_value == Smi::FromInt(Map::kPrototypeChainValid);
}
References DCHECK_EQ, v8::internal::Smi::FromInt(), v8::internal::IsSmi(), kPrototypeChainValid, v8::kRelaxedLoad, and v8::internal::value.
IterateOwnDescriptors()
InternalIndex::Range v8::internal::Map::IterateOwnDescriptors () const [inline]
Definition at line 245 of file map-inl.h.
                                                    {
  return InternalIndex::Range(NumberOfOwnDescriptors());
}
References NumberOfOwnDescriptors(), and v8::internal::compiler::turboshaft::Range().
Referenced by CanBeDeprecated(), EquivalentToForElementsKindTransition(), GetFieldCounts(), InstancesNeedRewriting(), NumberOfEnumerableProperties(), and NumberOfFields().
LastAdded()
InternalIndex v8::internal::Map::LastAdded () const [inline]
Definition at line 226 of file map-inl.h.
                                   {
  int number_of_own_descriptors = NumberOfOwnDescriptors();
  DCHECK_GT(number_of_own_descriptors, 0);
  return InternalIndex(number_of_own_descriptors - 1);
}
References DCHECK_GT, and NumberOfOwnDescriptors().
Referenced by GetLastDescriptorDetails(), and GetLastDescriptorName().
LookupElementsTransitionMap()
Tagged< Map > v8::internal::Map::LookupElementsTransitionMap (Isolate * isolate, ElementsKind elements_kind, ConcurrencyMode cmode) [private]
Definition at line 1058 of file map.cc.
                                                                    {
  Tagged<Map> to_map =
      FindClosestElementsTransition(isolate, *this, to_kind, cmode);
  if (to_map->elements_kind() == to_kind) return to_map;
  return Map();
}
References v8::internal::FindClosestElementsTransition(), isolate, and v8::internal::compiler::Map.
MapPrint()
void v8::internal::Map::MapPrint (std::ostream & os)
Definition at line 3996 of file objects-printer.cc.
                                 {
  bool is_meta_map = instance_type() == MAP_TYPE;
#ifdef OBJECT_PRINT
  PrintHeader(os, is_meta_map ? "MetaMap" : "Map");
#else
  os << (is_meta_map ? "MetaMap=" : "Map=") << reinterpret_cast<void*>(ptr());
#endif
  os << "\n - type: " << instance_type();
  os << "\n - instance size: ";
  if (instance_size() == kVariableSizeSentinel) {
    os << "variable";
  } else {
    os << instance_size();
  }
  if (is_meta_map) {
    // This is one of the meta maps, print only relevant fields.
    os << "\n - native_context: " << Brief(native_context_or_null());
    os << "\n";
    return;
  }
  if (IsJSObjectMap(*this)) {
    os << "\n - inobject properties: " << GetInObjectProperties();
    os << "\n - unused property fields: " << UnusedPropertyFields();
  }
  os << "\n - elements kind: " << ElementsKindToString(elements_kind());
  os << "\n - enum length: ";
  if (EnumLength() == kInvalidEnumCacheSentinel) {
    os << "invalid";
  } else {
    os << EnumLength();
  }
  if (is_deprecated()) os << "\n - deprecated_map";
  if (is_stable()) os << "\n - stable_map";
  if (is_migration_target()) os << "\n - migration_target";
  if (is_dictionary_map()) os << "\n - dictionary_map";
  if (has_named_interceptor()) os << "\n - named_interceptor";
  if (has_indexed_interceptor()) os << "\n - indexed_interceptor";
  if (may_have_interesting_properties())
    os << "\n - may_have_interesting_properties";
  if (is_undetectable()) os << "\n - undetectable";
  if (is_callable()) os << "\n - callable";
  if (is_constructor()) os << "\n - constructor";
  if (has_prototype_slot()) {
    os << "\n - has_prototype_slot";
    if (has_non_instance_prototype()) os << " (non-instance prototype)";
  }
  if (is_access_check_needed()) os << "\n - access_check_needed";
  if (!is_extensible()) os << "\n - non-extensible";
  if (IsContextMap(*this)) {
    os << "\n - native context: " << Brief(native_context());
  } else if (is_prototype_map()) {
    os << "\n - prototype_map";
    os << "\n - prototype info: " << Brief(prototype_info());
  } else {
    os << "\n - back pointer: " << Brief(GetBackPointer());
  }
  os << "\n - prototype_validity cell: "
     << Brief(prototype_validity_cell(kRelaxedLoad));
  os << "\n - instance descriptors " << (owns_descriptors() ? "(own) " : "")
     << "#" << NumberOfOwnDescriptors() << ": "
     << Brief(instance_descriptors());
  // Read-only maps can't have transitions, which is fortunate because we need
  // the isolate to iterate over the transitions.
  if (!HeapLayout::InReadOnlySpace(*this)) {
    Isolate* isolate = HeapLayout::InWritableSharedSpace(*this)
                           ? Isolate::Current()->shared_space_isolate()
                           : GetIsolateFromWritableObject(*this);
    TransitionsAccessor transitions(isolate, *this);
    int nof_transitions = transitions.NumberOfTransitions();
    if (nof_transitions > 0 || transitions.HasPrototypeTransitions() ||
        transitions.HasSideStepTransitions()) {
      os << "\n - transitions #" << nof_transitions << ": ";
      Tagged<HeapObject> heap_object;
      Tagged<Smi> smi;
      if (raw_transitions().ToSmi(&smi)) {
        os << Brief(smi);
      } else if (raw_transitions().GetHeapObject(&heap_object)) {
        os << Brief(heap_object);
      }
#ifdef OBJECT_PRINT
      transitions.PrintTransitions(os);
#endif // OBJECT_PRINT
    }
  }
  os << "\n - prototype: " << Brief(prototype());
  if (has_non_instance_prototype()) {
    os << "\n - non-instance prototype: " << Brief(GetNonInstancePrototype());
  }
  if (!IsContextMap(*this)) {
    os << "\n - constructor: " << Brief(GetConstructor());
  }
  os << "\n - dependent code: " << Brief(dependent_code());
  os << "\n - construction counter: " << construction_counter();
  os << "\n";
}
References v8::internal::Isolate::Current(), v8::internal::GetIsolateFromWritableObject(), v8::internal::TransitionsAccessor::HasPrototypeTransitions(), v8::internal::TransitionsAccessor::HasSideStepTransitions(), v8::internal::HeapLayout::InWritableSharedSpace(), v8::internal::TransitionsAccessor::NumberOfTransitions(), v8::internal::raw_transitions, and v8::internal::Isolate::shared_space_isolate().
mark_unstable()
void v8::internal::Map::mark_unstable () [inline]
Definition at line 713 of file map-inl.h.
                        {
  set_release_acquire_bit_field3(
      Bits3::IsUnstableBit::update(bit_field3(), true));
}
References v8::internal::bit_field3.
Referenced by NotifyLeafMapLayoutChange().
NextFreePropertyIndex()
int v8::internal::Map::NextFreePropertyIndex () const
Definition at line 1200 of file map.cc.
                                     {
  int number_of_own_descriptors = NumberOfOwnDescriptors();
  Tagged<DescriptorArray> descs = instance_descriptors(kRelaxedLoad);
  // Search properties backwards to find the last field.
  for (int i = number_of_own_descriptors - 1; i >= 0; --i) {
    PropertyDetails details = descs->GetDetails(InternalIndex(i));
    if (details.location() == PropertyLocation::kField) {
      return details.field_index() + details.field_width_in_words();
    }
  }
  return 0;
}
References v8::internal::PropertyDetails::field_index(), v8::internal::PropertyDetails::field_width_in_words(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::instance_descriptors, v8::internal::kField, v8::kRelaxedLoad, v8::internal::PropertyDetails::location(), and NumberOfOwnDescriptors().
Normalize() [1/3]
Handle< Map > v8::internal::Map::Normalize (Isolate * isolate, DirectHandle< Map > fast_map, PropertyNormalizationMode mode, const char * reason) [inline], [static]
Definition at line 194 of file map-inl.h.
                                                                               {
  const bool kUseCache = true;
  return Normalize(isolate, fast_map, fast_map->elements_kind(), {}, mode,
                   kUseCache, reason);
}
References isolate, mode(), and Normalize().
Normalize() [2/3]
Handle< Map > v8::internal::Map::Normalize (Isolate * isolate, DirectHandle< Map > map, ElementsKind new_elements_kind, DirectHandle< JSPrototype > new_prototype, PropertyNormalizationMode mode, bool use_cache, const char * reason) [static]
Definition at line 1293 of file map.cc.
                                               {
  DCHECK(!fast_map->is_dictionary_map());
  Tagged<Map> meta_map = fast_map->map();
  if (fast_map->is_prototype_map()) {
    use_cache = false;
  }
  DirectHandle<NormalizedMapCache> cache;
  if (use_cache) {
    Tagged<Object> normalized_map_cache =
        meta_map->native_context()->normalized_map_cache();
    use_cache = !IsUndefined(normalized_map_cache, isolate);
    if (use_cache) {
      cache = Cast<NormalizedMapCache>(
          direct_handle(normalized_map_cache, isolate));
    }
  }
  Handle<Map> new_map;
  if (use_cache && cache
                       ->Get(isolate, fast_map, new_elements_kind,
                             new_prototype.is_null() ? fast_map->prototype()
                                                     : *new_prototype,
                             mode)
                       .ToHandle(&new_map)) {
#ifdef VERIFY_HEAP
    if (v8_flags.verify_heap) new_map->DictionaryMapVerify(isolate);
#endif
#ifdef ENABLE_SLOW_DCHECKS
    if (v8_flags.enable_slow_asserts) {
      // The cached map should match newly created normalized map bit-by-bit,
      // except for the code cache, which can contain some ICs which can be
      // applied to the shared map, dependent code and weak cell cache.
      DirectHandle<Map> fresh = Map::CopyNormalized(isolate, fast_map, mode);
      fresh->set_elements_kind(new_elements_kind);
      if (!new_prototype.is_null()) {
        Map::SetPrototype(isolate, fresh, new_prototype);
      }
      static_assert(Map::kPrototypeValidityCellOffset ==
                    Map::kDependentCodeOffset + kTaggedSize);
      DCHECK_EQ(0, memcmp(reinterpret_cast<void*>(fresh->address()),
                          reinterpret_cast<void*>(new_map->address()),
                          Map::kBitField3Offset));
      // The IsInRetainedMapListBit might be different if the {new_map}
      // that we got from the {cache} was already embedded into optimized
      // code somewhere.
      // The IsMigrationTargetBit might be different if the {new_map} from
      // {cache} has already been marked as a migration target.
      constexpr int ignored_bit_field3_bits =
          Bits3::IsInRetainedMapListBit::kMask |
          Bits3::IsMigrationTargetBit::kMask;
      DCHECK_EQ(fresh->bit_field3() & ~ignored_bit_field3_bits,
                new_map->bit_field3() & ~ignored_bit_field3_bits);
      int offset = Map::kBitField3Offset + kInt32Size;
      DCHECK_EQ(0, memcmp(reinterpret_cast<void*>(fresh->address() + offset),
                          reinterpret_cast<void*>(new_map->address() + offset),
                          Map::kDependentCodeOffset - offset));
      offset = Map::kPrototypeValidityCellOffset + kTaggedSize;
      if (new_map->is_prototype_map()) {
        // For prototype maps, the PrototypeInfo is not copied.
        static_assert(Map::kTransitionsOrPrototypeInfoOffset ==
                      Map::kPrototypeValidityCellOffset + kTaggedSize);
        offset = kTransitionsOrPrototypeInfoOffset + kTaggedSize;
        DCHECK_EQ(fresh->raw_transitions(), Smi::zero());
      }
      DCHECK_EQ(0, memcmp(reinterpret_cast<void*>(fresh->address() + offset),
                          reinterpret_cast<void*>(new_map->address() + offset),
                          Map::kSize - offset));
    }
#endif
    if (v8_flags.log_maps) {
      LOG(isolate, MapEvent("NormalizeCached", fast_map, new_map, reason));
    }
  } else {
    new_map = Map::CopyNormalized(isolate, fast_map, mode);
    new_map->set_elements_kind(new_elements_kind);
    if (!new_prototype.is_null()) {
      Map::SetPrototype(isolate, new_map, new_prototype);
      DCHECK(new_map->is_dictionary_map() && !new_map->is_deprecated());
    }
    if (use_cache) {
      cache->Set(isolate, fast_map, new_map);
    }
    if (v8_flags.log_maps) {
      LOG(isolate, MapEvent("Normalize", fast_map, new_map, reason));
    }
  }
  fast_map->NotifyLeafMapLayoutChange(isolate);
  return new_map;
}
References v8::internal::HandleBase::address(), v8::internal::DirectHandle< T >::address(), CopyNormalized(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::direct_handle(), v8::internal::compiler::turboshaft::Get(), v8::internal::DirectHandle< T >::is_null(), isolate, v8::internal::kInt32Size, v8::internal::kTaggedSize, LOG, mode(), SetPrototype(), v8::internal::v8_flags, and v8::internal::Smi::zero().
Referenced by v8::internal::MapUpdater::Normalize(), Normalize(), v8::internal::JSObject::NormalizeProperties(), v8::internal::MapUpdater::ReconfigureExistingProperty(), TransitionToAccessorProperty(), and TransitionToDataProperty().
Normalize() [3/3]
static V8_EXPORT_PRIVATE Handle<Map> v8::internal::Map::Normalize (Isolate * isolate, DirectHandle< Map > map, ElementsKind new_elements_kind, DirectHandle< JSPrototype > new_prototype, PropertyNormalizationMode mode, const char * reason) [inline], [static]
Definition at line 600 of file map.h.
                          {
    const bool kUseCache = true;
    return Normalize(isolate, map, new_elements_kind, new_prototype, mode,
                     kUseCache, reason);
  }
References isolate, mode(), and Normalize().
NotifyLeafMapLayoutChange()
void v8::internal::Map::NotifyLeafMapLayoutChange (Isolate * isolate) [inline]
Definition at line 734 of file map-inl.h.
                                                    {
  if (is_stable()) {
    mark_unstable();
    DependentCode::DeoptimizeDependencyGroups(
        isolate, *this, DependentCode::kPrototypeCheckGroup);
  }
}
References v8::internal::DependentCode::DeoptimizeDependencyGroups(), is_stable(), isolate, v8::internal::DependentCode::kPrototypeCheckGroup, and mark_unstable().
Referenced by DeprecateTransitionTree().
NumberOfEnumerableProperties()
int v8::internal::Map::NumberOfEnumerableProperties () const
Definition at line 1188 of file map.cc.
                                            {
  int result = 0;
  Tagged<DescriptorArray> descs = instance_descriptors(kRelaxedLoad);
  for (InternalIndex i : IterateOwnDescriptors()) {
    if ((int{descs->GetDetails(i).attributes()} & ONLY_ENUMERABLE) == 0 &&
        !Object::FilterKey(descs->GetKey(i), ENUMERABLE_STRINGS)) {
      result++;
    }
  }
  return result;
}
References v8::internal::ENUMERABLE_STRINGS, v8::internal::Object::FilterKey(), v8::internal::instance_descriptors, IterateOwnDescriptors(), v8::kRelaxedLoad, v8::internal::ONLY_ENUMERABLE, and v8::base::internal::result.
NumberOfFields()
int v8::internal::Map::NumberOfFields (ConcurrencyMode cmode) const
Definition at line 619 of file map.cc.
                                                   {
  Tagged<DescriptorArray> descriptors = IsConcurrent(cmode)
                                            ? instance_descriptors(kAcquireLoad)
                                            : instance_descriptors();
  int result = 0;
  for (InternalIndex i : IterateOwnDescriptors()) {
    if (descriptors->GetDetails(i).location() == PropertyLocation::kField)
      result++;
  }
  return result;
}
References v8::internal::instance_descriptors, v8::internal::IsConcurrent(), IterateOwnDescriptors(), v8::kAcquireLoad, v8::internal::kField, and v8::base::internal::result.
Referenced by HasOutOfObjectProperties(), InstancesNeedRewriting(), and TooManyFastProperties().
NumberOfOwnDescriptors()
int v8::internal::Map::NumberOfOwnDescriptors () const [inline]
Definition at line 232 of file map-inl.h.
                                      {
  return Bits3::NumberOfOwnDescriptorsBits::decode(
      release_acquire_bit_field3());
}
References v8::internal::release_acquire_bit_field3.
Referenced by AppendDescriptor(), EquivalentToForTransition(), IsDetached(), IterateOwnDescriptors(), LastAdded(), NextFreePropertyIndex(), ReplaceDescriptors(), SetEnumLength(), and TryReplayPropertyTransitions().
ObjectFieldsFrom()
static constexpr ObjectFields v8::internal::Map::ObjectFieldsFrom (VisitorId visitor_id) [inline], [static], [constexpr]
Definition at line 938 of file map.h.
                                                                       {
    return (visitor_id < kDataOnlyVisitorIdCount)
               ? ObjectFields::kDataOnly
               : ObjectFields::kMaybePointers;
  }
References v8::internal::kDataOnly, v8::internal::kDataOnlyVisitorIdCount, and v8::internal::kMaybePointers.
Referenced by v8::internal::Scavenger::EvacuateInPlaceInternalizableString(), v8::internal::Scavenger::EvacuateObject(), v8::internal::Scavenger::EvacuateShortcutCandidate(), v8::internal::Scavenger::EvacuateThinString(), and v8::internal::anonymous_namespace{sweeper.cc}::PromotedPageRecordMigratedSlotVisitor::Process().
OnlyHasSimpleProperties()
bool v8::internal::Map::OnlyHasSimpleProperties () const
Definition at line 1213 of file map.cc.
                                        {
  // Wrapped string elements aren't explicitly stored in the elements backing
  // store, but are loaded indirectly from the underlying string.
  return !IsStringWrapperElementsKind(elements_kind()) &&
         !IsSpecialReceiverMap(*this) && !is_dictionary_map();
}
References v8::internal::IsSpecialReceiverMap(), and v8::internal::IsStringWrapperElementsKind().
PrepareForDataProperty()
DirectHandle< Map > v8::internal::Map::PrepareForDataProperty (Isolate * isolate, DirectHandle< Map > old_map, InternalIndex descriptor_number, PropertyConstness constness, DirectHandle< Object > value) [static]
Definition at line 1986 of file map.cc.
                                                                          {
  // The map should already be fully updated before storing the property.
  DCHECK(!map->is_deprecated());
  // Dictionaries can store any property value.
  DCHECK(!map->is_dictionary_map());
  return UpdateDescriptorForValue(isolate, map, descriptor, constness, value);
}
References v8::internal::DCHECK(), isolate, v8::internal::anonymous_namespace{map.cc}::UpdateDescriptorForValue(), and v8::internal::value.
Referenced by v8::internal::LookupIterator::PrepareForDataProperty(), v8::internal::LookupIterator::ReconfigureDataProperty(), and v8::internal::anonymous_namespace{js-objects.cc}::TryFastAddDataProperty().
PrintMapDetails()
void v8::internal::Map::PrintMapDetails (std::ostream & os)
Definition at line 3990 of file objects-printer.cc.
                                        {
  DisallowGarbageCollection no_gc;
  this->MapPrint(os);
  instance_descriptors()->PrintDescriptors(os);
}
RawCopy()
Handle< Map > v8::internal::Map::RawCopy (Isolate * isolate, DirectHandle< Map > map, int instance_size, int inobject_properties) [static], [private]
Definition at line 1257 of file map.cc.
                                                                     {
  Handle<Map> result = isolate->factory()->NewMap(
      src_handle, src_handle->instance_type(), instance_size,
      TERMINAL_FAST_ELEMENTS_KIND, inobject_properties);
  // We have to set the bitfields before any potential GCs could happen because
  // heap verification might fail otherwise.
  {
    DisallowGarbageCollection no_gc;
    Tagged<Map> src = *src_handle;
    Tagged<Map> raw = *result;
    raw->set_constructor_or_back_pointer(src->GetConstructorRaw());
    raw->set_bit_field(src->bit_field());
    raw->set_bit_field2(src->bit_field2());
    int new_bit_field3 = src->bit_field3();
    new_bit_field3 = Bits3::OwnsDescriptorsBit::update(new_bit_field3, true);
    new_bit_field3 =
        Bits3::NumberOfOwnDescriptorsBits::update(new_bit_field3, 0);
    new_bit_field3 = Bits3::EnumLengthBits::update(new_bit_field3,
                                                   kInvalidEnumCacheSentinel);
    new_bit_field3 = Bits3::IsDeprecatedBit::update(new_bit_field3, false);
    new_bit_field3 =
        Bits3::IsInRetainedMapListBit::update(new_bit_field3, false);
    if (!src->is_dictionary_map()) {
      new_bit_field3 = Bits3::IsUnstableBit::update(new_bit_field3, false);
    }
    // Same as bit_field comment above.
    raw->set_bit_field3(new_bit_field3);
    raw->clear_padding();
  }
  DirectHandle<JSPrototype> prototype(src_handle->prototype(), isolate);
  Map::SetPrototype(isolate, result, prototype);
  return result;
}
References v8::internal::Isolate::factory(), isolate, v8::internal::kInvalidEnumCacheSentinel, v8::internal::Factory::NewMap(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::prototype, v8::base::internal::result, SetPrototype(), and v8::internal::TERMINAL_FAST_ELEMENTS_KIND.
Referenced by CopyDropDescriptors(), CopyInitialMap(), and CopyNormalized().
ReplaceDescriptors()
void v8::internal::Map::ReplaceDescriptors (Isolate * isolate, Tagged< DescriptorArray > new_descriptors) [private]
Definition at line 677 of file map.cc.
                                                                      {
  PtrComprCageBase cage_base(isolate);
  // Don't overwrite the empty descriptor array or initial map's descriptors.
  if (NumberOfOwnDescriptors() == 0 ||
      IsUndefined(GetBackPointer(cage_base), isolate)) {
    return;
  }
  Tagged<DescriptorArray> to_replace = instance_descriptors(cage_base);
  // Replace descriptors by new_descriptors in all maps that share it. The old
  // descriptors will not be trimmed in the mark-compactor, we need to mark
  // all its elements.
  Tagged<Map> current = *this;
#ifndef V8_DISABLE_WRITE_BARRIERS
  WriteBarrier::ForDescriptorArray(to_replace,
                                   to_replace->number_of_descriptors());
#endif
  while (current->instance_descriptors(cage_base) == to_replace) {
    Tagged<Map> next;
    if (!current->TryGetBackPointer(cage_base, &next)) {
      break; // Stop overwriting at initial map.
    }
    current->SetEnumLength(kInvalidEnumCacheSentinel);
    current->UpdateDescriptors(isolate, new_descriptors,
                               current->NumberOfOwnDescriptors());
    current = next;
  }
  set_owns_descriptors(false);
}
References v8::internal::WriteBarrier::ForDescriptorArray(), v8::internal::instance_descriptors, isolate, v8::internal::kInvalidEnumCacheSentinel, and NumberOfOwnDescriptors().
RetrieveDescriptorsPointer()
Tagged<Cell> v8::internal::Map::RetrieveDescriptorsPointer () [inline]
set_instance_type()
void v8::internal::Map::set_instance_type (InstanceType value) [inline]
Definition at line 373 of file map-inl.h.
                                              {
  RELAXED_WRITE_UINT16_FIELD(*this, kInstanceTypeOffset, value);
}
References RELAXED_WRITE_UINT16_FIELD, and v8::internal::value.
SetBackPointer()
void v8::internal::Map::SetBackPointer (Tagged< HeapObject > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 864 of file map-inl.h.
                                                                        {
  CHECK_GE(instance_type(), FIRST_JS_RECEIVER_TYPE);
  CHECK(IsMap(value));
  CHECK(IsUndefined(GetBackPointer()));
  CHECK_EQ(Cast<Map>(value)->GetConstructorRaw(),
           constructor_or_back_pointer());
  set_constructor_or_back_pointer(value, mode);
}
References CHECK, CHECK_EQ, CHECK_GE, v8::internal::constructor_or_back_pointer, instance_type(), mode(), and v8::internal::value.
SetConstructor()
void v8::internal::Map::SetConstructor (Tagged< Object > constructor, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 1018 of file map-inl.h.
                                                                          {
  // Never overwrite a back pointer with a constructor.
  CHECK(!IsMap(constructor_or_back_pointer()));
  // Constructor field must contain {constructor, non-instance_prototype} tuple
  // for maps with non-instance prototype.
  DCHECK_EQ(has_non_instance_prototype(), IsTuple2(constructor));
  set_constructor_or_back_pointer(constructor, mode);
}
References CHECK, v8::internal::constructor_or_back_pointer, DCHECK_EQ, and mode().
SetConstructorFunctionIndex()
void v8::internal::Map::SetConstructorFunctionIndex (int value) [inline]
Definition at line 358 of file map-inl.h.
                                               {
  CHECK(IsPrimitiveMap(*this));
  set_inobject_properties_start_or_constructor_function_index(value);
}
References CHECK, v8::internal::IsPrimitiveMap(), and v8::internal::value.
SetEnumLength()
void v8::internal::Map::SetEnumLength (int length) [inline]
Definition at line 253 of file map-inl.h.
                                  {
  if (length != kInvalidEnumCacheSentinel) {
    DCHECK_LE(length, NumberOfOwnDescriptors());
    CHECK_LE(static_cast<unsigned>(length),
             static_cast<unsigned>(kMaxNumberOfDescriptors));
  }
  set_relaxed_bit_field3(Bits3::EnumLengthBits::update(bit_field3(), length));
}
References v8::internal::bit_field3, CHECK_LE, DCHECK_LE, v8::internal::kInvalidEnumCacheSentinel, v8::internal::kMaxNumberOfDescriptors, v8::internal::length, and NumberOfOwnDescriptors().
SetInObjectPropertiesStartInWords()
void v8::internal::Map::SetInObjectPropertiesStartInWords (int value) [inline]
Definition at line 329 of file map-inl.h.
                                                     {
  CHECK(IsJSObjectMap(*this));
  set_inobject_properties_start_or_constructor_function_index(value);
}
References CHECK, and v8::internal::value.
SetInObjectUnusedPropertyFields()
void v8::internal::Map::SetInObjectUnusedPropertyFields (int unused_property_fields) [inline]
Definition at line 431 of file map-inl.h.
                                                   {
  static_assert(JSObject::kFieldsAdded == JSObject::kHeaderSize / kTaggedSize);
  if (!IsJSObjectMap(*this)) {
    CHECK_EQ(0, value);
    set_used_or_unused_instance_size_in_words(0);
    return;
  }
  CHECK_LE(0, value);
  DCHECK_LE(value, GetInObjectProperties());
  int used_inobject_properties = GetInObjectProperties() - value;
  set_used_or_unused_instance_size_in_words(
      GetInObjectPropertyOffset(used_inobject_properties) / kTaggedSize);
  DCHECK_EQ(value, UnusedPropertyFields());
}
References CHECK_EQ, CHECK_LE, DCHECK_EQ, DCHECK_LE, GetInObjectProperties(), GetInObjectPropertyOffset(), v8::internal::JSObject::kFieldsAdded, v8::internal::kTaggedSize, UnusedPropertyFields(), and v8::internal::value.
SetInstanceDescriptors()
void v8::internal::Map::SetInstanceDescriptors (Isolate * isolate, Tagged< DescriptorArray > descriptors, int number_of_own_descriptors, WriteBarrierMode barrier_mode = UPDATE_WRITE_BARRIER)
Definition at line 2374 of file map.cc.
                                                                {
  DCHECK_IMPLIES(barrier_mode == WriteBarrierMode::SKIP_WRITE_BARRIER,
                 HeapLayout::InReadOnlySpace(descriptors));
  set_instance_descriptors(descriptors, kReleaseStore, barrier_mode);
  SetNumberOfOwnDescriptors(number_of_own_descriptors);
#ifndef V8_DISABLE_WRITE_BARRIERS
  WriteBarrier::ForDescriptorArray(descriptors, number_of_own_descriptors);
#endif
}
References DCHECK_IMPLIES, v8::internal::WriteBarrier::ForDescriptorArray(), v8::internal::HeapLayout::InReadOnlySpace(), v8::kReleaseStore, SetNumberOfOwnDescriptors(), and v8::internal::SKIP_WRITE_BARRIER.
Referenced by InitializeDescriptors(), and UpdateDescriptors().
SetNumberOfOwnDescriptors()
void v8::internal::Map::SetNumberOfOwnDescriptors (int number) [inline]
Definition at line 237 of file map-inl.h.
                                              {
  DCHECK_LE(number, instance_descriptors()->number_of_descriptors());
  CHECK_LE(static_cast<unsigned>(number),
           static_cast<unsigned>(kMaxNumberOfDescriptors));
  set_release_acquire_bit_field3(
      Bits3::NumberOfOwnDescriptorsBits::update(bit_field3(), number));
}
References v8::internal::bit_field3, CHECK_LE, DCHECK_LE, v8::internal::instance_descriptors, v8::internal::kMaxNumberOfDescriptors, and v8::internal::number_of_descriptors.
Referenced by AppendDescriptor(), and SetInstanceDescriptors().
SetOutOfObjectUnusedPropertyFields()
void v8::internal::Map::SetOutOfObjectUnusedPropertyFields (int unused_property_fields) [inline]
Definition at line 446 of file map-inl.h.
                                                      {
  static_assert(JSObject::kFieldsAdded == JSObject::kHeaderSize / kTaggedSize);
  CHECK_LT(static_cast<unsigned>(value), JSObject::kFieldsAdded);
  // For out of object properties "used_instance_size_in_words" byte encodes
  // the slack in the property array.
  set_used_or_unused_instance_size_in_words(value);
  DCHECK_EQ(value, UnusedPropertyFields());
}
References CHECK_LT, DCHECK_EQ, v8::internal::JSObject::kFieldsAdded, v8::internal::kTaggedSize, UnusedPropertyFields(), and v8::internal::value.
SetPrototype()
void v8::internal::Map::SetPrototype (Isolate * isolate, DirectHandle< Map > map, DirectHandle< JSPrototype > prototype, bool enable_prototype_setup_mode = true) [static]
Definition at line 2481 of file map.cc.
                                                         {
  RCS_SCOPE(isolate, RuntimeCallCounterId::kMap_SetPrototype);
  if (IsJSObjectThatCanBeTrackedAsPrototype(*prototype)) {
    DirectHandle<JSObject> prototype_jsobj = Cast<JSObject>(prototype);
    JSObject::OptimizeAsPrototype(prototype_jsobj, enable_prototype_setup_mode);
  } else {
    DCHECK(IsNull(*prototype, isolate) || IsJSProxy(*prototype) ||
           IsWasmObject(*prototype) ||
           HeapLayout::InWritableSharedSpace(*prototype));
  }
  WriteBarrierMode wb_mode =
      IsNull(*prototype, isolate) ? SKIP_WRITE_BARRIER : UPDATE_WRITE_BARRIER;
  map->set_prototype(*prototype, wb_mode);
}
References v8::internal::DCHECK(), v8::internal::HeapLayout::InWritableSharedSpace(), v8::internal::IsJSObjectThatCanBeTrackedAsPrototype(), v8::internal::IsNull(), isolate, v8::internal::IsWasmObject(), v8::internal::JSObject::OptimizeAsPrototype(), v8::internal::prototype, RCS_SCOPE, v8::internal::SKIP_WRITE_BARRIER, and v8::internal::UPDATE_WRITE_BARRIER.
Referenced by v8::internal::WasmStruct::AllocateDescriptorUninitialized(), v8::internal::WasmStruct::AllocatePrototype(), v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Direct_Impl(), CopyForPrototypeTransition(), v8::internal::Genesis::CreateAsyncFunctionMaps(), v8::internal::Genesis::CreateAsyncIteratorMaps(), v8::internal::Factory::CreateClassFunctionMap(), v8::internal::Genesis::CreateInitialMapForArraySubclass(), v8::internal::Genesis::CreateIteratorMaps(), v8::internal::Genesis::CreateJSProxyMaps(), v8::internal::anonymous_namespace{bootstrapper.cc}::CreateNonConstructorMap(), v8::internal::Genesis::CreateObjectFunction(), v8::internal::Factory::CreateSloppyFunctionMap(), v8::internal::Factory::CreateStrictFunctionMap(), v8::internal::JSFunction::EnsureHasInitialMap(), v8::internal::JSObject::ForceSetPrototype(), GetDerivedMap(), GetObjectCreateMap(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::GetOrCreateDebugProxyMap(), v8::internal::anonymous_namespace{runtime-classes.cc}::InitClassConstructor(), v8::internal::anonymous_namespace{runtime-classes.cc}::InitClassPrototype(), v8::internal::Genesis::InitializeGlobal(), v8::internal::Genesis::InstallABunchOfRandomThings(), v8::internal::Genesis::InstallTypedArray(), Normalize(), RawCopy(), and v8::internal::JSFunction::SetInitialMap().
SetShouldBeFastPrototypeMap()
void v8::internal::Map::SetShouldBeFastPrototypeMap (DirectHandle< Map > map, bool value, Isolate * isolate) [static]
Definition at line 2419 of file map.cc.
                                                        {
  DCHECK(map->is_prototype_map());
  if (value == false && !map->has_prototype_info()) {
    // "False" is the implicit default value, so there's nothing to do.
    return;
  }
  GetOrCreatePrototypeInfo(map, isolate)->set_should_be_fast_map(value);
}
References v8::internal::DCHECK(), GetOrCreatePrototypeInfo(), isolate, and v8::internal::value.
Referenced by v8::internal::Genesis::InitializeGlobal(), and v8::internal::JSObject::MakePrototypesFast().
SetWasmByte1()
void v8::internal::Map::SetWasmByte1 (uint8_t value) [inline]
SetWasmByte2()
void v8::internal::Map::SetWasmByte2 (uint8_t value) [inline]
ShareDescriptor()
Handle< Map > v8::internal::Map::ShareDescriptor (Isolate * isolate, DirectHandle< Map > map, DirectHandle< DescriptorArray > descriptors, Descriptor * descriptor) [static], [private]
Definition at line 1504 of file map.cc.
                                                         {
  // Sanity check. This path is only to be taken if the map owns its descriptor
  // array, implying that its NumberOfOwnDescriptors equals the number of
  // descriptors in the descriptor array.
  DCHECK_EQ(map->NumberOfOwnDescriptors(),
            map->instance_descriptors(isolate)->number_of_descriptors());
  Handle<Map> result = CopyDropDescriptors(isolate, map);
  DirectHandle<Name> name = descriptor->GetKey();
  // Properly mark the {result} if the {name} is an "interesting symbol".
  if (name->IsInteresting(isolate)) {
    result->set_may_have_interesting_properties(true);
  }
  // Ensure there's space for the new descriptor in the shared descriptor array.
  if (descriptors->number_of_slack_descriptors() == 0) {
    int old_size = descriptors->number_of_descriptors();
    if (old_size == 0) {
      descriptors = DescriptorArray::Allocate(isolate, 0, 1);
    } else {
      int slack = SlackForArraySize(old_size, kMaxNumberOfDescriptors);
      EnsureDescriptorSlack(isolate, map, slack);
      descriptors = direct_handle(map->instance_descriptors(isolate), isolate);
    }
  }
  {
    DisallowGarbageCollection no_gc;
    descriptors->Append(descriptor);
    result->InitializeDescriptors(isolate, *descriptors);
  }
  DCHECK(result->NumberOfOwnDescriptors() == map->NumberOfOwnDescriptors() + 1);
  ConnectTransition(isolate, map, result, name, SIMPLE_PROPERTY_TRANSITION);
  return result;
}
References v8::internal::DescriptorArray::Allocate(), ConnectTransition(), CopyDropDescriptors(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::direct_handle(), EnsureDescriptorSlack(), v8::internal::Descriptor::GetKey(), isolate, v8::internal::kMaxNumberOfDescriptors, v8::internal::name, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, v8::internal::SIMPLE_PROPERTY_TRANSITION, and SlackForArraySize().
Referenced by CopyAddDescriptor().
should_be_fast_prototype_map()
bool v8::internal::Map::should_be_fast_prototype_map () const [inline]
Definition at line 580 of file map-inl.h.
                                             {
  DCHECK(is_prototype_map());
  if (!has_prototype_info()) return false;
  return Cast<PrototypeInfo>(prototype_info())->should_be_fast_map();
}
References v8::internal::DCHECK(), has_prototype_info(), and v8::internal::is_prototype_map.
ShouldCheckForReadOnlyElementsInPrototypeChain()
bool v8::internal::Map::ShouldCheckForReadOnlyElementsInPrototypeChain (Isolate * isolate)
Definition at line 1220 of file map.cc.
                                                                         {
  // If this map has TypedArray elements kind, we won't look at the prototype
  // chain, so we can return early.
  if (IsTypedArrayElementsKind(elements_kind())) return false;
  for (PrototypeIterator iter(isolate, *this); !iter.IsAtEnd();
       iter.Advance()) {
    // Be conservative, don't look into any JSReceivers that may have custom
    // elements. For example, into JSProxies, String wrappers (which have have
    // non-configurable, non-writable elements), API objects, etc.
    if (IsCustomElementsReceiverMap(iter.GetCurrent()->map())) return true;
    Tagged<JSObject> current = iter.GetCurrent<JSObject>();
    ElementsKind elements_kind = current->GetElementsKind(isolate);
    // If this prototype has TypedArray elements kind, we won't look any further
    // in the prototype chain, so we can return early.
    if (IsTypedArrayElementsKind(elements_kind)) return false;
    if (IsFrozenElementsKind(elements_kind)) return true;
    if (IsDictionaryElementsKind(elements_kind) &&
        current->element_dictionary(isolate)->requires_slow_elements()) {
      return true;
    }
    if (IsSlowArgumentsElementsKind(elements_kind)) {
      Tagged<SloppyArgumentsElements> elements =
          Cast<SloppyArgumentsElements>(current->elements(isolate));
      Tagged<Object> arguments = elements->arguments();
      if (Cast<NumberDictionary>(arguments)->requires_slow_elements()) {
        return true;
      }
    }
  }
  return false;
}
References v8::internal::Cast< NumberDictionary >(), v8::internal::PrototypeIterator::IsAtEnd(), v8::internal::IsCustomElementsReceiverMap(), v8::internal::IsDictionaryElementsKind(), v8::internal::IsFrozenElementsKind(), isolate, v8::internal::IsSlowArgumentsElementsKind(), and v8::internal::IsTypedArrayElementsKind().
SlackForArraySize()
int v8::internal::Map::SlackForArraySize (int old_size, int size_limit) [inline], [static]
Definition at line 1049 of file map-inl.h.
                                                       {
  const int max_slack = size_limit - old_size;
  CHECK_LE(0, max_slack);
  if (old_size < 4) {
    DCHECK_LE(1, max_slack);
    return 1;
  }
  return std::min(max_slack, old_size / 4);
}
References CHECK_LE, and DCHECK_LE.
Referenced by v8::internal::TransitionsAccessor::InsertHelper(), and ShareDescriptor().
StartInobjectSlackTracking()
void v8::internal::Map::StartInobjectSlackTracking ()
Definition at line 2500 of file map.cc.
                                     {
  DCHECK(!this->IsInobjectSlackTrackingInProgress());
  if (UnusedPropertyFields() == 0) return;
  set_construction_counter(Map::kSlackTrackingCounterStart);
}
References v8::internal::DCHECK(), IsInobjectSlackTrackingInProgress(), kSlackTrackingCounterStart, and UnusedPropertyFields().
TooManyFastProperties()
bool v8::internal::Map::TooManyFastProperties (StoreOrigin store_origin) const [inline]
Definition at line 207 of file map-inl.h.
                                                              {
  if (UnusedPropertyFields() != 0) return false;
  if (store_origin != StoreOrigin::kMaybeKeyed) return false;
  if (is_prototype_map()) return false;
  int limit = std::max(
      {v8_flags.fast_properties_soft_limit.value(), GetInObjectProperties()});
  int external =
      NumberOfFields(ConcurrencyMode::kSynchronous) - GetInObjectProperties();
  return external > limit;
}
References GetInObjectProperties(), v8::internal::is_prototype_map, v8::internal::kMaybeKeyed, v8::internal::kSynchronous, NumberOfFields(), UnusedPropertyFields(), and v8::internal::v8_flags.
TransitionElementsTo()
DirectHandle< Map > v8::internal::Map::TransitionElementsTo (Isolate * isolate, DirectHandle< Map > map, ElementsKind to_kind) [static]
Definition at line 1079 of file map.cc.
                                                                  {
  ElementsKind from_kind = map->elements_kind();
  if (from_kind == to_kind) return map;
  // We should never be trying to go backwards in the elements kind manifold.
  DCHECK_IMPLIES(IsHoleyElementsKind(from_kind),
                 to_kind != GetPackedElementsKind(from_kind));
  Tagged<Context> native_context = isolate->context()->native_context();
  if (from_kind == FAST_SLOPPY_ARGUMENTS_ELEMENTS) {
    if (*map == native_context->fast_aliased_arguments_map()) {
      DCHECK_EQ(SLOW_SLOPPY_ARGUMENTS_ELEMENTS, to_kind);
      return direct_handle(native_context->slow_aliased_arguments_map(),
                           isolate);
    }
  } else if (from_kind == SLOW_SLOPPY_ARGUMENTS_ELEMENTS) {
    if (*map == native_context->slow_aliased_arguments_map()) {
      DCHECK_EQ(FAST_SLOPPY_ARGUMENTS_ELEMENTS, to_kind);
      return direct_handle(native_context->fast_aliased_arguments_map(),
                           isolate);
    }
  } else if (IsFastElementsKind(from_kind) && IsFastElementsKind(to_kind)) {
    // Reuse map transitions for JSArrays.
    DisallowGarbageCollection no_gc;
    if (native_context->GetInitialJSArrayMap(from_kind) == *map) {
      Tagged<Object> maybe_transitioned_map =
          native_context->GetNoCell(Context::ArrayMapIndex(to_kind));
      if (IsMap(maybe_transitioned_map)) {
        return direct_handle(Cast<Map>(maybe_transitioned_map), isolate);
      }
    }
  }
  DCHECK(!IsUndefined(*map, isolate));
  bool allow_store_transition = IsTransitionElementsKind(from_kind);
  // Only store fast element maps in ascending generality.
  if (IsFastElementsKind(to_kind)) {
    allow_store_transition =
        allow_store_transition && IsTransitionableFastElementsKind(from_kind) &&
        IsMoreGeneralElementsKindTransition(from_kind, to_kind);
  }
  if (!allow_store_transition) {
    return Map::CopyAsElementsKind(isolate, map, to_kind, OMIT_TRANSITION);
  }
  return MapUpdater{isolate, map}.ReconfigureElementsKind(to_kind);
}
References v8::internal::Context::ArrayMapIndex(), v8::internal::Isolate::context(), CopyAsElementsKind(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::direct_handle(), v8::internal::FAST_SLOPPY_ARGUMENTS_ELEMENTS, v8::internal::GetPackedElementsKind(), v8::internal::IsFastElementsKind(), v8::internal::IsHoleyElementsKind(), v8::internal::IsMoreGeneralElementsKindTransition(), isolate, v8::internal::IsTransitionableFastElementsKind(), v8::internal::IsTransitionElementsKind(), v8::internal::native_context, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::OMIT_TRANSITION, and v8::internal::SLOW_SLOPPY_ARGUMENTS_ELEMENTS.
Referenced by v8::internal::JSObject::GetElementsTransitionMap().
TransitionRootMapToPrototypeForNewObject()
Handle< Map > v8::internal::Map::TransitionRootMapToPrototypeForNewObject (Isolate * isolate, DirectHandle< Map > map, DirectHandle< JSPrototype > prototype) [static]
Definition at line 2506 of file map.cc.
                                         {
  DCHECK(IsUndefined(map->GetBackPointer()));
  Handle<Map> new_map = TransitionToUpdatePrototype(isolate, map, prototype);
  if (new_map->GetBackPointer() != *map &&
      map->IsInobjectSlackTrackingInProgress()) {
    // Advance the construction count on the base map to keep it in sync with
    // the transitioned map.
    map->InobjectSlackTrackingStep(isolate);
  }
  return new_map;
}
References v8::internal::DCHECK(), isolate, v8::internal::prototype, and TransitionToUpdatePrototype().
Referenced by GetDerivedMap(), GetObjectCreateMap(), v8::internal::Factory::NewJSBoundFunction(), v8::internal::Factory::NewJSObjectWithNullProto(), and v8::internal::Factory::NewSlowJSObjectWithPropertiesAndElements().
TransitionToAccessorProperty()
DirectHandle< Map > v8::internal::Map::TransitionToAccessorProperty (Isolate * isolate, DirectHandle< Map > map, DirectHandle< Name > name, InternalIndex descriptor, DirectHandle< Object > getter, DirectHandle< Object > setter, PropertyAttributes attributes) [static]
Definition at line 2083 of file map.cc.
                                                                {
  RCS_SCOPE(
      isolate,
      map->IsDetached(isolate)
          ? RuntimeCallCounterId::kPrototypeMap_TransitionToAccessorProperty
          : RuntimeCallCounterId::kMap_TransitionToAccessorProperty);
  // At least one of the accessors needs to be a new value.
  DCHECK(!IsNull(*getter, isolate) || !IsNull(*setter, isolate));
  DCHECK(IsUniqueName(*name));
  // Migrate to the newest map before transitioning to the new property.
  map = Update(isolate, map);
  // Dictionary maps can always have additional data properties.
  if (map->is_dictionary_map()) return map;
  PropertyNormalizationMode mode = map->is_prototype_map()
                                       ? KEEP_INOBJECT_PROPERTIES
                                       : CLEAR_INOBJECT_PROPERTIES;
  MaybeDirectHandle<Map> maybe_transition =
      TransitionsAccessor::SearchTransition(
          isolate, map, *name, PropertyKind::kAccessor, attributes);
  DirectHandle<Map> transition;
  if (maybe_transition.ToHandle(&transition)) {
    Tagged<DescriptorArray> descriptors =
        transition->instance_descriptors(isolate);
    InternalIndex last_descriptor = transition->LastAdded();
    DCHECK(descriptors->GetKey(last_descriptor)->Equals(*name));
    DCHECK_EQ(PropertyKind::kAccessor,
              descriptors->GetDetails(last_descriptor).kind());
    DCHECK_EQ(attributes,
              descriptors->GetDetails(last_descriptor).attributes());
    DirectHandle<Object> maybe_pair(
        descriptors->GetStrongValue(last_descriptor), isolate);
    if (!IsAccessorPair(*maybe_pair)) {
      return Map::Normalize(isolate, map, mode,
                            "TransitionToAccessorFromNonPair");
    }
    auto pair = Cast<AccessorPair>(maybe_pair);
    if (!pair->Equals(*getter, *setter)) {
      return Map::Normalize(isolate, map, mode,
                            "TransitionToDifferentAccessor");
    }
    return transition;
  }
  DirectHandle<AccessorPair> pair;
  Tagged<DescriptorArray> old_descriptors = map->instance_descriptors(isolate);
  if (descriptor.is_found()) {
    if (descriptor != map->LastAdded()) {
      return Map::Normalize(isolate, map, mode, "AccessorsOverwritingNonLast");
    }
    PropertyDetails old_details = old_descriptors->GetDetails(descriptor);
    if (old_details.kind() != PropertyKind::kAccessor) {
      return Map::Normalize(isolate, map, mode,
                            "AccessorsOverwritingNonAccessors");
    }
    if (old_details.attributes() != attributes) {
      return Map::Normalize(isolate, map, mode, "AccessorsWithAttributes");
    }
    DirectHandle<Object> maybe_pair(old_descriptors->GetStrongValue(descriptor),
                                    isolate);
    if (!IsAccessorPair(*maybe_pair)) {
      return Map::Normalize(isolate, map, mode, "AccessorsOverwritingNonPair");
    }
    auto current_pair = Cast<AccessorPair>(maybe_pair);
    if (current_pair->Equals(*getter, *setter)) return map;
    bool overwriting_accessor = false;
    if (!IsNull(*getter, isolate) &&
        !IsNull(current_pair->get(ACCESSOR_GETTER), isolate) &&
        current_pair->get(ACCESSOR_GETTER) != *getter) {
      overwriting_accessor = true;
    }
    if (!IsNull(*setter, isolate) &&
        !IsNull(current_pair->get(ACCESSOR_SETTER), isolate) &&
        current_pair->get(ACCESSOR_SETTER) != *setter) {
      overwriting_accessor = true;
    }
    if (overwriting_accessor) {
      return Map::Normalize(isolate, map, mode,
                            "AccessorsOverwritingAccessors");
    }
    pair = AccessorPair::Copy(isolate, Cast<AccessorPair>(maybe_pair));
  } else if (map->NumberOfOwnDescriptors() >= kMaxNumberOfDescriptors ||
             map->TooManyFastProperties(StoreOrigin::kNamed)) {
    return Map::Normalize(isolate, map, CLEAR_INOBJECT_PROPERTIES,
                          "TooManyAccessors");
  } else {
    pair = isolate->factory()->NewAccessorPair();
  }
  pair->SetComponents(*getter, *setter);
  // Do not track transitions during bootstrapping.
  TransitionFlag flag =
      isolate->bootstrapper()->IsActive() ? OMIT_TRANSITION : INSERT_TRANSITION;
  Descriptor d = Descriptor::AccessorConstant(name, pair, attributes);
  return Map::CopyInsertDescriptor(isolate, map, &d, flag);
}
References v8::internal::ACCESSOR_GETTER, v8::internal::ACCESSOR_SETTER, v8::internal::Descriptor::AccessorConstant(), v8::internal::PropertyDetails::attributes(), v8::internal::Isolate::bootstrapper(), v8::internal::CLEAR_INOBJECT_PROPERTIES, v8::internal::AccessorPair::Copy(), CopyInsertDescriptor(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Isolate::factory(), v8::internal::INSERT_TRANSITION, v8::internal::InternalIndex::is_found(), v8::internal::Bootstrapper::IsActive(), v8::internal::IsNull(), isolate, v8::internal::IsUniqueName(), v8::internal::kAccessor, v8::internal::KEEP_INOBJECT_PROPERTIES, v8::internal::PropertyDetails::kind(), v8::internal::kMaxNumberOfDescriptors, v8::internal::kNamed, mode(), v8::internal::name, v8::internal::FactoryBase< Impl >::NewAccessorPair(), Normalize(), v8::internal::OMIT_TRANSITION, RCS_SCOPE, v8::internal::TransitionsAccessor::SearchTransition(), v8::internal::setter, v8::internal::MaybeDirectHandle< T >::ToHandle(), and Update().
Referenced by v8::internal::LookupIterator::TransitionToAccessorProperty().
TransitionToDataProperty()
DirectHandle< Map > v8::internal::Map::TransitionToDataProperty (Isolate * isolate, DirectHandle< Map > map, DirectHandle< Name > name, DirectHandle< Object > value, PropertyAttributes attributes, PropertyConstness constness, StoreOrigin store_origin) [static]
Definition at line 1998 of file map.cc.
                                                           {
  RCS_SCOPE(isolate,
            map->IsDetached(isolate)
                ? RuntimeCallCounterId::kPrototypeMap_TransitionToDataProperty
                : RuntimeCallCounterId::kMap_TransitionToDataProperty);
  DCHECK(IsUniqueName(*name));
  DCHECK(!map->is_dictionary_map());
  // Migrate to the newest map before storing the property.
  map = Update(isolate, map);
  MaybeHandle<Map> maybe_transition = TransitionsAccessor::SearchTransition(
      isolate, map, *name, PropertyKind::kData, attributes);
  Handle<Map> transition;
  if (maybe_transition.ToHandle(&transition)) {
    InternalIndex descriptor = transition->LastAdded();
    DCHECK_EQ(attributes, transition->instance_descriptors(isolate)
                              ->GetDetails(descriptor)
                              .attributes());
    return UpdateDescriptorForValue(isolate, transition, descriptor, constness,
                                    value);
  }
  // Do not track transitions during bootstrapping.
  TransitionFlag flag =
      isolate->bootstrapper()->IsActive() ? OMIT_TRANSITION : INSERT_TRANSITION;
  MaybeDirectHandle<Map> maybe_map;
  if (!map->TooManyFastProperties(store_origin)) {
    Representation representation =
        Object::OptimalRepresentation(*value, isolate);
    DirectHandle<FieldType> type =
        Object::OptimalType(*value, isolate, representation);
    maybe_map = Map::CopyWithField(isolate, map, name, type, attributes,
                                   constness, representation, flag);
  }
  DirectHandle<Map> result;
  if (!maybe_map.ToHandle(&result)) {
    const char* reason = "TooManyFastProperties";
#if V8_TRACE_MAPS
    std::unique_ptr<base::ScopedVector<char>> buffer;
    if (v8_flags.log_maps) {
      base::ScopedVector<char> name_buffer(100);
      name->NameShortPrint(name_buffer);
      buffer.reset(new base::ScopedVector<char>(128));
      SNPrintF(*buffer, "TooManyFastProperties %s", name_buffer.begin());
      reason = buffer->begin();
    }
#endif
    DirectHandle<Object> maybe_constructor(map->GetConstructor(), isolate);
    if (v8_flags.feedback_normalization && map->new_target_is_base() &&
        IsJSFunction(*maybe_constructor) &&
        !Cast<JSFunction>(*maybe_constructor)->shared()->native()) {
      auto constructor = Cast<JSFunction>(maybe_constructor);
      DCHECK_NE(*constructor, constructor->native_context()->object_function());
      DirectHandle<Map> initial_map(constructor->initial_map(), isolate);
      result = Map::Normalize(isolate, initial_map, CLEAR_INOBJECT_PROPERTIES,
                              reason);
      initial_map->DeprecateTransitionTree(isolate);
      DirectHandle<JSReceiver> prototype(Cast<JSReceiver>(result->prototype()),
                                         isolate);
      JSFunction::SetInitialMap(isolate, constructor, result, prototype);
      // Deoptimize all code that embeds the previous initial map.
      DependentCode::DeoptimizeDependencyGroups(
          isolate, *initial_map, DependentCode::kInitialMapChangedGroup);
      if (!result->EquivalentToForNormalization(*map,
                                                CLEAR_INOBJECT_PROPERTIES)) {
        result =
            Map::Normalize(isolate, map, CLEAR_INOBJECT_PROPERTIES, reason);
      }
    } else {
      result = Map::Normalize(isolate, map, CLEAR_INOBJECT_PROPERTIES, reason);
    }
  }
  return result;
}
References v8::base::Vector< T >::begin(), v8::internal::Isolate::bootstrapper(), v8::internal::CLEAR_INOBJECT_PROPERTIES, CopyWithField(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, v8::internal::DependentCode::DeoptimizeDependencyGroups(), v8::internal::compiler::initial_map, v8::internal::INSERT_TRANSITION, v8::internal::Bootstrapper::IsActive(), isolate, v8::internal::IsUniqueName(), v8::internal::kData, v8::internal::DependentCode::kInitialMapChangedGroup, v8::internal::name, Normalize(), v8::internal::OMIT_TRANSITION, v8::internal::Object::OptimalRepresentation(), v8::internal::Object::OptimalType(), v8::internal::prototype, RCS_SCOPE, v8::base::internal::result, v8::internal::TransitionsAccessor::SearchTransition(), v8::internal::JSFunction::SetInitialMap(), v8::base::SNPrintF(), v8::internal::MaybeDirectHandle< T >::ToHandle(), v8::internal::MaybeHandle< T >::ToHandle(), v8::internal::tracing::type, Update(), v8::internal::anonymous_namespace{map.cc}::UpdateDescriptorForValue(), v8::internal::v8_flags, and v8::internal::value.
Referenced by v8::internal::DictionaryTemplateInfo::NewInstance(), and v8::internal::LookupIterator::PrepareTransitionToDataProperty().
TransitionToImmutableProto()
DirectHandle< Map > v8::internal::Map::TransitionToImmutableProto (Isolate * isolate, DirectHandle< Map > map) [static]
Definition at line 1424 of file map.cc.
                                                                         {
  DirectHandle<Map> new_map = Map::Copy(isolate, map, "ImmutablePrototype");
  new_map->set_is_immutable_proto(true);
  return new_map;
}
References Copy(), and isolate.
Referenced by v8::internal::JSObject::SetImmutableProto().
TransitionToUpdatePrototype()
Handle< Map > v8::internal::Map::TransitionToUpdatePrototype (Isolate * isolate, DirectHandle< Map > map, DirectHandle< JSPrototype > prototype) [static]
Definition at line 2520 of file map.cc.
                                         {
  Handle<Map> new_map;
  DCHECK_IMPLIES(v8_flags.move_prototype_transitions_first,
                 IsUndefined(map->GetBackPointer()));
  if (auto maybe_map = TransitionsAccessor::GetPrototypeTransition(
          isolate, *map, *prototype)) {
    new_map = handle(*maybe_map, isolate);
  } else {
    new_map = CopyForPrototypeTransition(isolate, map, prototype);
    if (!map->IsDetached(isolate)) {
      TransitionsAccessor::PutPrototypeTransition(isolate, map, prototype,
                                                  new_map);
    }
  }
  DCHECK_IMPLIES(map->IsInobjectSlackTrackingInProgress(),
                 new_map->IsInobjectSlackTrackingInProgress());
  CHECK_IMPLIES(map->IsInobjectSlackTrackingInProgress(),
                map->construction_counter() <= new_map->construction_counter());
  return new_map;
}
References CHECK_IMPLIES, CopyForPrototypeTransition(), DCHECK_IMPLIES, v8::internal::TransitionsAccessor::GetPrototypeTransition(), v8::internal::handle(), isolate, v8::internal::prototype, v8::internal::TransitionsAccessor::PutPrototypeTransition(), and v8::internal::v8_flags.
Referenced by v8::internal::MapUpdater::FindRootMap(), v8::internal::JSObject::SetPrototype(), and TransitionRootMapToPrototypeForNewObject().
TryAsElementsKind()
std::optional< Tagged< Map > > v8::internal::Map::TryAsElementsKind (Isolate * isolate, DirectHandle< Map > map, ElementsKind kind, ConcurrencyMode cmode) [static]
Definition at line 1163 of file map.cc.
                                                                         {
  Tagged<Map> closest_map =
      FindClosestElementsTransition(isolate, *map, kind, cmode);
  if (closest_map->elements_kind() != kind) return {};
  return closest_map;
}
References v8::internal::FindClosestElementsTransition(), and isolate.
Referenced by v8::internal::compiler::MapRef::AsElementsKind().
TryGetBackPointer()
bool v8::internal::Map::TryGetBackPointer (PtrComprCageBase cage_base, Tagged< Map > * back_pointer) const [inline]
Definition at line 845 of file map-inl.h.
                                                             {
  Tagged<Object> object = constructor_or_back_pointer(cage_base, kRelaxedLoad);
  // We don't expect maps from another native context in the transition tree,
  // so just compare object's map against current map's meta map.
  Tagged<Map> meta_map = map(cage_base);
  if (ConcurrentIsHeapObjectWithMap(cage_base, object, meta_map)) {
    DCHECK(IsMap(object));
    // Sanity check - only contextful maps can transition.
    DCHECK(IsNativeContext(meta_map->native_context_or_null()));
    *back_pointer = Cast<Map>(object);
    return true;
  }
  // If it was a map that'd mean that there are maps from different native
  // contexts in the transition tree.
  DCHECK(!IsMap(object));
  return false;
}
References ConcurrentIsHeapObjectWithMap(), v8::internal::constructor_or_back_pointer, v8::internal::DCHECK(), and v8::kRelaxedLoad.
TryGetConstructor()
Tagged< Object > v8::internal::Map::TryGetConstructor (PtrComprCageBase cage_base, int max_steps) [inline]
Definition at line 990 of file map-inl.h.
                                                     {
  Tagged<Object> maybe_constructor = constructor_or_back_pointer(cage_base);
  // Follow any back pointers.
  while (IsMap(maybe_constructor, cage_base)) {
    if (max_steps-- == 0) return Smi::FromInt(0);
    maybe_constructor =
        Cast<Map>(maybe_constructor)->constructor_or_back_pointer(cage_base);
  }
  if (IsTuple2(maybe_constructor)) {
    // Get constructor from the {constructor, non-instance_prototype} tuple.
    maybe_constructor = Cast<Tuple2>(maybe_constructor)->value1();
  }
  return maybe_constructor;
}
References v8::internal::constructor_or_back_pointer, and v8::internal::Smi::FromInt().
TryGetMapRootIdxFor()
static constexpr std::optional<RootIndex> v8::internal::Map::TryGetMapRootIdxFor (InstanceType type) [inline], [static], [constexpr]
Definition at line 910 of file map.h.
                         {
    switch (type) {
#define MAKE_CASE(TYPE, Name, name) \
  case TYPE: \
    return RootIndex::k##Name##Map;
      STRUCT_LIST(MAKE_CASE)
      TORQUE_DEFINED_INSTANCE_TYPE_LIST(MAKE_CASE)
#undef MAKE_CASE
      default:
        break;
    }
    return {};
  }
References MAKE_CASE, STRUCT_LIST, and v8::internal::tracing::type.
Referenced by v8::internal::CodeStubAssembler::GetInstanceTypeMap(), GetMapFor(), and v8::internal::InstanceTypeChecker::UniqueMapOfInstanceType().
TryGetPrototypeInfo()
bool v8::internal::Map::TryGetPrototypeInfo (Tagged< PrototypeInfo > * result) const [inline]
Definition at line 591 of file map-inl.h.
                                                                 {
  DCHECK(is_prototype_map());
  Tagged<Object> maybe_proto_info = prototype_info();
  if (!PrototypeInfo::IsPrototypeInfoFast(maybe_proto_info)) return false;
  *result = Cast<PrototypeInfo>(maybe_proto_info);
  return true;
}
References v8::internal::DCHECK(), v8::internal::is_prototype_map, v8::internal::PrototypeInfo::IsPrototypeInfoFast(), and v8::base::internal::result.
TryGetValidityCellHolderMap()
bool v8::internal::Map::TryGetValidityCellHolderMap (Tagged< Map > map, Isolate * isolate, Tagged< Map > * out_validity_cell_holder_map) [inline], [static]
Definition at line 600 of file map-inl.h.
                                               {
  if (map->is_prototype_map()) {
    // For prototype maps we can use their validity cell for guarding changes.
    *out_validity_cell_holder_map = map;
    return true;
  }
  // For non-prototype maps we use prototype's map's validity cell.
  Tagged<Object> maybe_prototype =
      map->GetPrototypeChainRootMap(isolate)->prototype();
  if (!IsJSObjectThatCanBeTrackedAsPrototype(maybe_prototype)) {
    return false;
  }
  *out_validity_cell_holder_map = Cast<JSObject>(maybe_prototype)->map();
  return true;
}
References v8::internal::IsJSObjectThatCanBeTrackedAsPrototype(), and isolate.
Referenced by GetOrCreatePrototypeChainValidityCell().
TryReplayPropertyTransitions()
Tagged< Map > v8::internal::Map::TryReplayPropertyTransitions (Isolate * isolate, Tagged< Map > map, ConcurrencyMode cmode) [private]
Definition at line 784 of file map.cc.
                                                                     {
  DisallowGarbageCollection no_gc;
  const int root_nof = NumberOfOwnDescriptors();
  const int old_nof = old_map->NumberOfOwnDescriptors();
  // TODO(jgruber,chromium:1239009): The main thread should use non-atomic
  // reads, but this currently leads to odd behavior (see the linked bug).
  // Investigate and fix this properly. Also below and in called functions.
  Tagged<DescriptorArray> old_descriptors =
      old_map->instance_descriptors(isolate, kAcquireLoad);
  Tagged<Map> new_map = *this;
  for (InternalIndex i : InternalIndex::Range(root_nof, old_nof)) {
    PropertyDetails old_details = old_descriptors->GetDetails(i);
    Tagged<Map> transition =
        TransitionsAccessor(isolate, new_map, IsConcurrent(cmode))
            .SearchTransition(old_descriptors->GetKey(i), old_details.kind(),
                              old_details.attributes());
    if (transition.is_null()) return Map();
    new_map = transition;
    Tagged<DescriptorArray> new_descriptors =
        new_map->instance_descriptors(isolate, kAcquireLoad);
    PropertyDetails new_details = new_descriptors->GetDetails(i);
    DCHECK_EQ(old_details.kind(), new_details.kind());
    DCHECK_EQ(old_details.attributes(), new_details.attributes());
    if (!IsGeneralizableTo(old_details.constness(), new_details.constness())) {
      return Map();
    }
    DCHECK(IsGeneralizableTo(old_details.location(), new_details.location()));
    if (!old_details.representation().fits_into(new_details.representation())) {
      return Map();
    }
    if (new_details.location() == PropertyLocation::kField) {
      if (new_details.kind() == PropertyKind::kData) {
        Tagged<FieldType> new_type = new_descriptors->GetFieldType(i);
        DCHECK_EQ(PropertyKind::kData, old_details.kind());
        DCHECK_EQ(PropertyLocation::kField, old_details.location());
        Tagged<FieldType> old_type = old_descriptors->GetFieldType(i);
        if (!FieldType::NowIs(old_type, new_type)) {
          return Map();
        }
      } else {
        DCHECK_EQ(PropertyKind::kAccessor, new_details.kind());
#ifdef DEBUG
        Tagged<FieldType> new_type = new_descriptors->GetFieldType(i);
        DCHECK(IsAny(new_type));
#endif
        UNREACHABLE();
      }
    } else {
      DCHECK_EQ(PropertyLocation::kDescriptor, new_details.location());
      if (old_details.location() == PropertyLocation::kField ||
          old_descriptors->GetStrongValue(i) !=
              new_descriptors->GetStrongValue(i)) {
        return Map();
      }
    }
  }
  if (new_map->NumberOfOwnDescriptors() != old_nof) return Map();
  return new_map;
}
References v8::internal::PropertyDetails::attributes(), v8::internal::PropertyDetails::constness(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Representation::fits_into(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::IsAny(), v8::internal::IsConcurrent(), v8::internal::IsGeneralizableTo(), isolate, v8::internal::kAccessor, v8::kAcquireLoad, v8::internal::kData, v8::internal::kDescriptor, v8::internal::kField, v8::internal::PropertyDetails::kind(), v8::internal::PropertyDetails::location(), v8::internal::compiler::Map, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::FieldType::NowIs(), NumberOfOwnDescriptors(), v8::internal::PropertyDetails::representation(), v8::internal::TransitionsAccessor::SearchTransition(), and v8::internal::UNREACHABLE().
TryUpdate()
MaybeHandle< Map > v8::internal::Map::TryUpdate (Isolate * isolate, Handle< Map > map) [static]
Definition at line 762 of file map.cc.
                                                                     {
  DisallowGarbageCollection no_gc;
  DisallowDeoptimization no_deoptimization(isolate);
  if (!old_map->is_deprecated()) return old_map;
  if (v8_flags.fast_map_update) {
    Tagged<Map> target_map = SearchMigrationTarget(isolate, *old_map);
    if (!target_map.is_null()) {
      return handle(target_map, isolate);
    }
  }
  std::optional<Tagged<Map>> new_map = MapUpdater::TryUpdateNoLock(
      isolate, *old_map, ConcurrencyMode::kSynchronous);
  if (!new_map.has_value()) return MaybeHandle<Map>();
  if (v8_flags.fast_map_update) {
    TransitionsAccessor::SetMigrationTarget(isolate, old_map, new_map.value());
  }
  return handle(new_map.value(), isolate);
}
References v8::internal::handle(), v8::internal::Tagged< HeapObject >::is_null(), isolate, v8::internal::kSynchronous, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::anonymous_namespace{map.cc}::SearchMigrationTarget(), v8::internal::TransitionsAccessor::SetMigrationTarget(), v8::internal::MapUpdater::TryUpdateNoLock(), and v8::internal::v8_flags.
Referenced by v8::internal::JSObject::TryMigrateInstance(), and v8::internal::KeyedStoreIC::UpdateStoreElement().
UnusedInObjectProperties()
int v8::internal::Map::UnusedInObjectProperties () const [inline]
Definition at line 394 of file map-inl.h.
                                        {
  // Like Map::UnusedPropertyFields(), but returns 0 for out of object
  // properties.
#if V8_ENABLE_WEBASSEMBLY
  DCHECK(!IsWasmObjectMap(*this));
#endif // V8_ENABLE_WEBASSEMBLY
  int value = used_or_unused_instance_size_in_words();
  DCHECK_IMPLIES(!IsJSObjectMap(*this), value == 0);
  if (value >= JSObject::kFieldsAdded) {
    return instance_size_in_words() - value;
  }
  return 0;
}
References v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::JSObject::kFieldsAdded, and v8::internal::value.
UnusedPropertyFields()
int v8::internal::Map::UnusedPropertyFields () const [inline]
Definition at line 377 of file map-inl.h.
                                    {
#if V8_ENABLE_WEBASSEMBLY
  DCHECK(!IsWasmObjectMap(*this));
#endif // V8_ENABLE_WEBASSEMBLY
  int value = used_or_unused_instance_size_in_words();
  DCHECK_IMPLIES(!IsJSObjectMap(*this), value == 0);
  int unused;
  if (value >= JSObject::kFieldsAdded) {
    unused = instance_size_in_words() - value;
  } else {
    // For out of object properties "used_or_unused_instance_size_in_words"
    // byte encodes the slack in the property array.
    unused = value;
  }
  return unused;
}
References v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::JSObject::kFieldsAdded, and v8::internal::value.
Referenced by AccountAddedOutOfObjectPropertyField(), AccountAddedPropertyField(), AppendDescriptor(), ComputeMinObjectSlack(), CopyUnusedPropertyFields(), CopyUnusedPropertyFieldsAdjustedForInstanceSize(), SetInObjectUnusedPropertyFields(), SetOutOfObjectUnusedPropertyFields(), StartInobjectSlackTracking(), and TooManyFastProperties().
UnwrapFieldType()
Tagged< FieldType > v8::internal::Map::UnwrapFieldType (Tagged< MaybeObject > wrapped_type) [static]
Definition at line 504 of file map.cc.
                                                                       {
  DCHECK(!wrapped_type.IsCleared());
  Tagged<HeapObject> heap_object;
  if (wrapped_type.GetHeapObjectIfWeak(&heap_object)) {
    return Cast<FieldType>(heap_object);
  }
  return Cast<FieldType>(wrapped_type);
}
References v8::internal::DCHECK(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectIfWeak(), and v8::internal::TaggedImpl< kRefType, StorageType >::IsCleared().
Referenced by v8::internal::DescriptorArray::GetFieldType().
Update()
DirectHandle< Map > v8::internal::Map::Update (Isolate * isolate, DirectHandle< Map > map) [static]
Definition at line 850 of file map.cc.
                                                                     {
  if (!map->is_deprecated()) return map;
  if (v8_flags.fast_map_update) {
    Tagged<Map> target_map = SearchMigrationTarget(isolate, *map);
    if (!target_map.is_null()) {
      return DirectHandle<Map>(target_map, isolate);
    }
  }
  return MapUpdater{isolate, map}.Update();
}
References v8::internal::Tagged< HeapObject >::is_null(), isolate, v8::internal::anonymous_namespace{map.cc}::SearchMigrationTarget(), and v8::internal::v8_flags.
Referenced by v8::internal::JsonParser< Char >::BuildJsonObject(), v8::internal::JSObject::MigrateInstance(), v8::internal::LookupIterator::PrepareForDataProperty(), v8::internal::JSObject::PreventExtensionsWithTransition(), v8::internal::ValueDeserializer::ReadJSObjectProperties(), TransitionToAccessorProperty(), TransitionToDataProperty(), and v8::internal::anonymous_namespace{js-objects.cc}::TryFastAddDataProperty().
UpdateDescriptors()
void v8::internal::Map::UpdateDescriptors (Isolate * isolate, Tagged< DescriptorArray > descriptors, int number_of_own_descriptors) [inline]
Definition at line 777 of file map-inl.h.
                                                           {
  SetInstanceDescriptors(isolate, descriptors, number_of_own_descriptors);
}
References isolate, and SetInstanceDescriptors().
UsedInstanceSize()
int v8::internal::Map::UsedInstanceSize () const [inline]
Definition at line 418 of file map-inl.h.
                                {
#if V8_ENABLE_WEBASSEMBLY
  DCHECK(!IsWasmObjectMap(*this));
#endif // V8_ENABLE_WEBASSEMBLY
  int words = used_or_unused_instance_size_in_words();
  if (words < JSObject::kFieldsAdded) {
    // All in-object properties are used and the words is tracking the slack
    // in the property array.
    return instance_size();
  }
  return words * kTaggedSize;
}
References v8::internal::DCHECK(), v8::internal::JSObject::kFieldsAdded, and v8::internal::kTaggedSize.
WasmByte1()
uint8_t v8::internal::Map::WasmByte1 () const [inline]
WasmByte2()
uint8_t v8::internal::Map::WasmByte2 () const [inline]
WrapFieldType()
MaybeObjectDirectHandle v8::internal::Map::WrapFieldType (DirectHandle< FieldType > type) [static]
Definition at line 496 of file map.cc.
                                                                       {
  if (IsClass(*type)) {
    return MaybeObjectDirectHandle::Weak(FieldType::AsClass(type));
  }
  return MaybeObjectDirectHandle(type);
}
References v8::internal::FieldType::AsClass(), v8::internal::IsClass(), v8::internal::tracing::type, and v8::internal::MaybeObjectDirectHandle::Weak().
Referenced by v8::internal::MapUpdater::BuildDescriptorArray(), CopyWithField(), and v8::internal::MapUpdater::UpdateFieldType().
Friends And Related Function Documentation
MapUpdater
friend class MapUpdater [friend]
Definition at line 1088 of file map.h.
MarkingVisitorBase
template<typename ConcreteVisitor >
friend class MarkingVisitorBase [friend]
Definition at line 1090 of file map.h.
Member Data Documentation
isolate
Tagged<UnionOf<Smi, MaybeWeak<Map>, TransitionArray> > Isolate* v8::internal::Map::isolate
Definition at line 514 of file map.h.
Referenced by AddMissingTransitions(), AddMissingTransitionsForTesting(), AppendDescriptor(), AsElementsKind(), AsLanguageMode(), ComputeMinObjectSlack(), ConnectTransition(), Copy(), CopyAddDescriptor(), CopyAsElementsKind(), CopyDropDescriptors(), CopyForElementsTransition(), CopyForPreventExtensions(), CopyForPrototypeTransition(), CopyInitialMap(), CopyInitialMapNormalized(), CopyInsertDescriptor(), CopyNormalized(), CopyReplaceDescriptor(), CopyReplaceDescriptors(), CopyWithConstant(), CopyWithField(), Create(), DeprecateTransitionTree(), ElementsTransitionMap(), EnsureDescriptorSlack(), FindElementsKindTransitionedMap(), GeneralizeIfCanHaveTransitionableFastElementsKind(), GetDerivedMap(), GetLastDescriptorDetails(), GetLastDescriptorName(), GetObjectCreateMap(), GetOrCreatePrototypeChainValidityCell(), GetOrCreatePrototypeInfo(), GetPrototypeChainRootMap(), Hash(), InitializeDescriptors(), InobjectSlackTrackingStep(), InstallDescriptors(), IsDetached(), IsMapInArrayPrototypeChain(), LookupElementsTransitionMap(), Normalize(), NotifyLeafMapLayoutChange(), PrepareForDataProperty(), RawCopy(), ReplaceDescriptors(), SetPrototype(), SetShouldBeFastPrototypeMap(), ShareDescriptor(), ShouldCheckForReadOnlyElementsInPrototypeChain(), TransitionElementsTo(), TransitionRootMapToPrototypeForNewObject(), TransitionToAccessorProperty(), TransitionToDataProperty(), TransitionToImmutableProto(), TransitionToUpdatePrototype(), TryAsElementsKind(), TryGetValidityCellHolderMap(), TryReplayPropertyTransitions(), TryUpdate(), Update(), and UpdateDescriptors().
kGenerousAllocationCount
const int v8::internal::Map::kGenerousAllocationCount [static]
Initial value:
=
      kSlackTrackingCounterStart - kSlackTrackingCounterEnd + 1
Definition at line 394 of file map.h.
kNoConstructorFunctionIndex
const int v8::internal::Map::kNoConstructorFunctionIndex = 0 [static]
Definition at line 261 of file map.h.
Referenced by v8::internal::compiler::NativeContextRef::GetConstructorFunction(), GetConstructorFunction(), GetPrototypeChainRootMap(), v8::internal::Object::NoSideEffectsToString(), and v8::internal::Object::ToObjectImpl().
kNoSlackTracking
const int v8::internal::Map::kNoSlackTracking = 0 [static]
Definition at line 361 of file map.h.
Referenced by v8::internal::MapUpdater::CompleteInobjectSlackTracking(), CopyNormalized(), v8::internal::ConstructorBuiltinsAssembler::CreateEmptyObjectLiteral(), v8::internal::anonymous_namespace{js-function.cc}::FastInitializeDerivedMap(), v8::internal::anonymous_namespace{runtime-classes.cc}::InitClassConstructor(), v8::internal::anonymous_namespace{runtime-classes.cc}::InitClassPrototype(), v8::internal::CodeStubAssembler::InitializeJSObjectBodyNoSlackTracking(), v8::internal::CodeStubAssembler::InitializeJSObjectBodyWithSlackTracking(), v8::internal::Factory::InitializeMap(), v8::internal::anonymous_namespace{setup-heap-internal.cc}::InitializePartialMap(), v8::internal::compiler::MapRef::IsInobjectSlackTrackingInProgress(), and IsInobjectSlackTrackingInProgress().
kPrototypeChainInvalid
constexpr int v8::internal::Map::kPrototypeChainInvalid = 1 [static], [constexpr]
Definition at line 537 of file map.h.
Referenced by v8::internal::Heap::CreateEarlyReadOnlyMapsAndObjects(), and v8::internal::anonymous_namespace{js-objects.cc}::InvalidateOnePrototypeValidityCellInternal().
kPrototypeChainValid
constexpr int v8::internal::Map::kPrototypeChainValid = 0 [static], [constexpr]
Definition at line 536 of file map.h.
Referenced by v8::internal::AccessorAssembler::CheckPrototypeValidityCell(), v8::internal::anonymous_namespace{ic.cc}::GetCloneTargetMap(), IsPrototypeValidityCellValid(), and v8::internal::TF_BUILTIN().
kPrototypeChainValidSmi
constexpr Tagged<Smi> v8::internal::Map::kPrototypeChainValidSmi = Smi::zero() [static], [constexpr]
Definition at line 538 of file map.h.
Referenced by GetOrCreatePrototypeChainValidityCell(), v8::internal::Factory::InitializeMap(), v8::internal::anonymous_namespace{setup-heap-internal.cc}::InitializePartialMap(), IsPrototypeChainInvalidated(), and v8::internal::anonymous_namespace{js-struct.cc}::PrepareMapCommon().
kSlackTrackingCounterEnd
const int v8::internal::Map::kSlackTrackingCounterEnd = 1 [static]
Definition at line 360 of file map.h.
Referenced by v8::internal::CodeStubAssembler::InitializeJSObjectBodyWithSlackTracking(), and InobjectSlackTrackingStep().
kSlackTrackingCounterStart
const int v8::internal::Map::kSlackTrackingCounterStart = 7 [static]
Definition at line 359 of file map.h.
Referenced by StartInobjectSlackTracking().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/map.h
/mnt/V8SourceCode/src/diagnostics/objects-printer.cc
/mnt/V8SourceCode/src/objects/map-inl.h
/mnt/V8SourceCode/src/objects/map.cc