v8_inspector::anonymous_namespace{value-mirror.cc}::SymbolMirror Class Reference
Public Member Functions
SymbolMirror (v8::Isolate *isolate, v8::Local< v8::Symbol > value)
Response buildRemoteObject (v8::Local< v8::Context > context, const WrapOptions &wrapOptions, std::unique_ptr< RemoteObject > *result) const override
void buildPropertyPreview (v8::Local< v8::Context > context, const String16 &name, std::unique_ptr< protocol::Runtime::PropertyPreview > *preview) const override
void buildEntryPreview (v8::Local< v8::Context > context, int *nameLimit, int *indexLimit, std::unique_ptr< ObjectPreview > *preview) const override
Response buildDeepSerializedValue (v8::Local< v8::Context > context, int maxDepth, v8::Local< v8::Object > additionalParameters, V8SerializationDuplicateTracker &duplicateTracker, std::unique_ptr< protocol::DictionaryValue > *result) const override
Additional Inherited Members
Detailed Description
Definition at line 745 of file value-mirror.cc.
Constructor & Destructor Documentation
SymbolMirror()
v8_inspector::anonymous_namespace{value-mirror.cc}::SymbolMirror::SymbolMirror (v8::Isolate * isolate, v8::Local< v8::Symbol > value) [inline]
Definition at line 747 of file value-mirror.cc.
      : ValueMirrorBase(isolate, value) {}
Member Function Documentation
buildDeepSerializedValue()
Response v8_inspector::anonymous_namespace{value-mirror.cc}::SymbolMirror::buildDeepSerializedValue (v8::Local< v8::Context > context, int maxDepth, v8::Local< v8::Object > additionalParameters, V8SerializationDuplicateTracker & duplicateTracker, std::unique_ptr< protocol::DictionaryValue > * result) const [inline], [override], [virtual]
Implements v8_inspector::ValueMirror.
Definition at line 793 of file value-mirror.cc.
                                                                     {
    v8::Local<v8::Value> value = v8Value(v8::Isolate::GetCurrent());
    bool isKnown;
    *result = duplicateTracker.LinkExistingOrCreate(value, &isKnown);
    if (isKnown) {
      return Response::Success();
    }
    (*result)->setString(
        "type", protocol::Runtime::DeepSerializedValue::TypeEnum::Symbol);
    return Response::Success();
  }
References v8::Isolate::GetCurrent(), v8_inspector::V8SerializationDuplicateTracker::LinkExistingOrCreate(), v8::base::internal::result, and v8::internal::value.
buildEntryPreview()
void v8_inspector::anonymous_namespace{value-mirror.cc}::SymbolMirror::buildEntryPreview (v8::Local< v8::Context > context, int * nameLimit, int * indexLimit, std::unique_ptr< ObjectPreview > * preview) const [inline], [override]
Definition at line 779 of file value-mirror.cc.
                                                            {
    v8::Local<v8::Symbol> value =
        v8Value(v8::Isolate::GetCurrent()).As<v8::Symbol>();
    *preview =
        ObjectPreview::create()
            .setType(RemoteObject::TypeEnum::Symbol)
            .setDescription(descriptionForSymbol(context, value))
            .setOverflow(false)
            .setProperties(std::make_unique<protocol::Array<PropertyPreview>>())
            .build();
  }
References v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForSymbol(), v8::Isolate::GetCurrent(), and v8::internal::value.
buildPropertyPreview()
void v8_inspector::anonymous_namespace{value-mirror.cc}::SymbolMirror::buildPropertyPreview (v8::Local< v8::Context > context, const String16 & name, std::unique_ptr< protocol::Runtime::PropertyPreview > * preview) const [inline], [override], [virtual]
Reimplemented from v8_inspector::ValueMirror.
Definition at line 765 of file value-mirror.cc.
                                                        {
    v8::Local<v8::Symbol> value =
        v8Value(v8::Isolate::GetCurrent()).As<v8::Symbol>();
    *preview = PropertyPreview::create()
                   .setName(name)
                   .setType(RemoteObject::TypeEnum::Symbol)
                   .setValue(abbreviateString(
                       descriptionForSymbol(context, value), kEnd))
                   .build();
  }
References v8_inspector::anonymous_namespace{value-mirror.cc}::abbreviateString(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForSymbol(), v8::Isolate::GetCurrent(), v8_inspector::anonymous_namespace{value-mirror.cc}::kEnd, name, and v8::internal::value.
buildRemoteObject()
Response v8_inspector::anonymous_namespace{value-mirror.cc}::SymbolMirror::buildRemoteObject (v8::Local< v8::Context > context, const WrapOptions & wrapOptions, std::unique_ptr< RemoteObject > * result) const [inline], [override]
Definition at line 750 of file value-mirror.cc.
                                                          {
    if (wrapOptions.mode == WrapMode::kJson) {
      return Response::ServerError("Object couldn't be returned by value");
    }
    v8::Local<v8::Symbol> value =
        v8Value(v8::Isolate::GetCurrent()).As<v8::Symbol>();
    *result = RemoteObject::create()
                  .setType(RemoteObject::TypeEnum::Symbol)
                  .setDescription(descriptionForSymbol(context, value))
                  .build();
    return Response::Success();
  }
References v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForSymbol(), v8::Isolate::GetCurrent(), v8_inspector::kJson, v8_inspector::WrapOptions::mode, v8::base::internal::result, and v8::internal::value.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/inspector/value-mirror.cc