v8::internal::Cancelable Class Reference
#include <cancelable-task.h>
Public Member Functions
Cancelable (CancelableTaskManager *parent)
virtual ~Cancelable ()
Cancelable (const Cancelable &)=delete
Cancelable & operator= (const Cancelable &)=delete
CancelableTaskManager::Id id ()
Protected Types
enum Status { kWaiting
, kCanceled
, kRunning
 }
Protected Member Functions
bool TryRun (Status *previous=nullptr)
Private Member Functions
bool Cancel ()
bool CompareExchangeStatus (Status expected, Status desired, Status *previous=nullptr)
Private Attributes
CancelableTaskManager *const parent_
std::atomic< Status > status_ {kWaiting}
const CancelableTaskManager::Id id_
Friends
class CancelableTaskManager
Detailed Description
Definition at line 93 of file cancelable-task.h.
Member Enumeration Documentation
Status
enum v8::internal::Cancelable::Status [protected]
Enumerator
kWaiting
kCanceled
kRunning
Definition at line 115 of file cancelable-task.h.
{ kWaiting, kCanceled, kRunning };
Constructor & Destructor Documentation
Cancelable() [1/2]
v8::internal::Cancelable::Cancelable (CancelableTaskManager * parent) [inline], [explicit]
Definition at line 95 of file cancelable-task.h.
      : parent_(parent), id_(parent->Register(this)) {}
 Cancelable()
v8::internal::Cancelable::~Cancelable () [virtual]
Definition at line 12 of file cancelable-task.cc.
                        {
  // The following check is needed to avoid calling an already terminated
  // manager object. This happens when the manager cancels all pending tasks
  // in {CancelAndWait} only before destroying the manager object.
  Status previous;
  if (TryRun(&previous) || previous == kRunning) {
    parent_->RemoveFinishedTask(id_);
  }
}
References id_, kRunning, parent_, v8::internal::CancelableTaskManager::RemoveFinishedTask(), and TryRun().
Cancelable() [2/2]
v8::internal::Cancelable::Cancelable (const Cancelable &) [delete]
Member Function Documentation
Cancel()
bool v8::internal::Cancelable::Cancel () [inline], [private]
Definition at line 126 of file cancelable-task.h.
{ return CompareExchangeStatus(kWaiting, kCanceled); }
Referenced by v8::internal::CancelableTaskManager::Register().
CompareExchangeStatus()
bool v8::internal::Cancelable::CompareExchangeStatus (Status expected, Status desired, Status * previous = nullptr) [inline], [private]
Definition at line 128 of file cancelable-task.h.
                                                         {
    // {compare_exchange_strong} updates {expected}.
    bool success = status_.compare_exchange_strong(expected, desired,
                                                   std::memory_order_acq_rel,
                                                   std::memory_order_acquire);
    if (previous) *previous = expected;
    return success;
  }
id()
CancelableTaskManager::Id v8::internal::Cancelable::id () [inline]
Definition at line 107 of file cancelable-task.h.
{ return id_; }
operator=()
Cancelable& v8::internal::Cancelable::operator= (const Cancelable &) [delete]
TryRun()
bool v8::internal::Cancelable::TryRun (Status * previous = nullptr) [inline], [protected]
Definition at line 117 of file cancelable-task.h.
                                          {
    return CompareExchangeStatus(kWaiting, kRunning, previous);
  }
Referenced by v8::internal::CancelableIdleTask::Run(), and ~Cancelable().
Friends And Related Function Documentation
CancelableTaskManager
friend class CancelableTaskManager [friend]
Definition at line 122 of file cancelable-task.h.
Member Data Documentation
id_
const CancelableTaskManager::Id v8::internal::Cancelable::id_ [private]
Definition at line 140 of file cancelable-task.h.
Referenced by ~Cancelable().
parent_
CancelableTaskManager* const v8::internal::Cancelable::parent_ [private]
Definition at line 138 of file cancelable-task.h.
Referenced by ~Cancelable().
status_
std::atomic<Status> v8::internal::Cancelable::status_ {kWaiting} [private]
Definition at line 139 of file cancelable-task.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/tasks/cancelable-task.h
/mnt/V8SourceCode/src/tasks/cancelable-task.cc