v8::internal::compiler::InstructionBlock Class Reference
#include <instruction.h>
Public Types
using Predecessors = ZoneVector< RpoNumber >
using Successors = ZoneVector< RpoNumber >
using PhiInstructions = ZoneVector< PhiInstruction * >
Public Member Functions
InstructionBlock (Zone *zone, RpoNumber rpo_number, RpoNumber loop_header, RpoNumber loop_end, RpoNumber dominator, bool deferred, bool handler)
int first_instruction_index () const
int last_instruction_index () const
int32_t code_start () const
void set_code_start (int32_t start)
int32_t code_end () const
void set_code_end (int32_t end)
bool IsDeferred () const
bool IsHandler () const
void MarkHandler ()
void UnmarkHandler ()
RpoNumber ao_number () const
RpoNumber rpo_number () const
RpoNumber loop_header () const
RpoNumber loop_end () const
bool IsLoopHeader () const
bool IsTableSwitchTarget () const
bool ShouldAlignCodeTarget () const
bool ShouldAlignLoopHeader () const
bool IsLoopHeaderInAssemblyOrder () const
bool omitted_by_jump_threading () const
void set_omitted_by_jump_threading ()
Predecessors & predecessors ()
const Predecessors & predecessors () const
size_t PredecessorCount () const
size_t PredecessorIndexOf (RpoNumber rpo_number) const
Successors & successors ()
const Successors & successors () const
size_t SuccessorCount () const
RpoNumber dominator () const
void set_dominator (RpoNumber dominator)
const PhiInstructions & phis () const
PhiInstruction * PhiAt (size_t i) const
void AddPhi (PhiInstruction *phi)
void set_ao_number (RpoNumber ao_number)
void set_code_target_alignment (bool val)
void set_loop_header_alignment (bool val)
void set_table_switch_target (bool val)
bool needs_frame () const
void mark_needs_frame ()
bool must_construct_frame () const
void mark_must_construct_frame ()
bool must_deconstruct_frame () const
void mark_must_deconstruct_frame ()
void clear_must_deconstruct_frame ()
Private Attributes
Successors successors_
Predecessors predecessors_
PhiInstructions phis_
RpoNumber ao_number_
const RpoNumber rpo_number_
const RpoNumber loop_header_
const RpoNumber loop_end_
RpoNumber dominator_
int32_t code_start_
int32_t code_end_ = -1
const bool deferred_: 1
bool handler_: 1
bool table_switch_target_: 1
bool code_target_alignment_: 1
bool loop_header_alignment_: 1
bool needs_frame_: 1
bool must_construct_frame_: 1
bool must_deconstruct_frame_: 1
bool omitted_by_jump_threading_: 1
Detailed Description
Definition at line 1703 of file instruction.h.
Member Typedef Documentation
PhiInstructions
using v8::internal::compiler::InstructionBlock::PhiInstructions = ZoneVector<PhiInstruction*>
Definition at line 1766 of file instruction.h.
Predecessors
using v8::internal::compiler::InstructionBlock::Predecessors = ZoneVector<RpoNumber>
Definition at line 1752 of file instruction.h.
Successors
using v8::internal::compiler::InstructionBlock::Successors = ZoneVector<RpoNumber>
Definition at line 1758 of file instruction.h.
Constructor & Destructor Documentation
InstructionBlock()
v8::internal::compiler::InstructionBlock::InstructionBlock (Zone * zone, RpoNumber rpo_number, RpoNumber loop_header, RpoNumber loop_end, RpoNumber dominator, bool deferred, bool handler)
Definition at line 662 of file instruction.cc.
    : successors_(zone),
      predecessors_(zone),
      phis_(zone),
      ao_number_(RpoNumber::Invalid()),
      rpo_number_(rpo_number),
      loop_header_(loop_header),
      loop_end_(loop_end),
      dominator_(dominator),
      deferred_(deferred),
      handler_(handler),
      table_switch_target_(false),
      code_target_alignment_(false),
      loop_header_alignment_(false),
      needs_frame_(!v8_flags.turbo_elide_frames),
      must_construct_frame_(false),
      must_deconstruct_frame_(false),
      omitted_by_jump_threading_(false) {}
Member Function Documentation
AddPhi()
void v8::internal::compiler::InstructionBlock::AddPhi (PhiInstruction * phi) [inline]
Definition at line 1769 of file instruction.h.
{ phis_.push_back(phi); }
Referenced by v8::internal::compiler::InstructionSelector::VisitPhi().
ao_number()
RpoNumber v8::internal::compiler::InstructionBlock::ao_number () const [inline]
Definition at line 1735 of file instruction.h.
{ return ao_number_; }
Referenced by v8::internal::compiler::CodeGenerator::IsNextInAssemblyOrder(), and v8::internal::compiler::operator<<().
clear_must_deconstruct_frame()
void v8::internal::compiler::InstructionBlock::clear_must_deconstruct_frame () [inline]
Definition at line 1786 of file instruction.h.
{ must_deconstruct_frame_ = false; }
Referenced by v8::internal::compiler::JumpThreading::ComputeForwarding().
code_end()
int32_t v8::internal::compiler::InstructionBlock::code_end () const [inline]
Definition at line 1727 of file instruction.h.
{ return code_end_; }
Referenced by v8::internal::compiler::CodeGenerator::AssembleInstruction(), v8::internal::compiler::operator<<(), and v8::internal::compiler::InstructionSelector::SelectInstructions().
code_start()
int32_t v8::internal::compiler::InstructionBlock::code_start () const [inline]
Definition at line 1724 of file instruction.h.
{ return code_start_; }
Referenced by v8::internal::compiler::CodeGenerator::AssembleBlock(), v8::internal::compiler::CodeGenerator::AssembleInstruction(), v8::internal::compiler::JumpThreading::ComputeForwarding(), v8::internal::compiler::InstructionSequence::EndBlock(), v8::internal::compiler::InstructionSequence::GetBlockStart(), v8::internal::compiler::RegisterAllocationData::IsBlockBoundary(), v8::internal::compiler::operator<<(), v8::internal::compiler::GraphC1Visualizer::PrintSchedule(), v8::internal::compiler::InstructionSelector::SelectInstructions(), and v8::internal::compiler::RegisterAllocatorVerifier::VerifyGapMoves().
dominator()
RpoNumber v8::internal::compiler::InstructionBlock::dominator () const [inline]
Definition at line 1763 of file instruction.h.
{ return dominator_; }
first_instruction_index()
int v8::internal::compiler::InstructionBlock::first_instruction_index () const [inline]
Definition at line 1711 of file instruction.h.
                                      {
    DCHECK_LE(0, code_start_);
    DCHECK_LT(0, code_end_);
    DCHECK_GE(code_end_, code_start_);
    return code_start_;
  }
References DCHECK_GE, DCHECK_LE, and DCHECK_LT.
Referenced by v8::internal::compiler::LiveRangeBuilder::AddInitialIntervals(), v8::internal::compiler::SpillPlacer::CommitSpill(), v8::internal::compiler::LiveRangeConnector::CommitSpillsInDeferredBlocks(), v8::internal::compiler::MoveOptimizer::CompressBlock(), v8::internal::compiler::RegisterAllocator::FindOptimalSpillingPos(), v8::internal::compiler::RegisterAllocator::FindOptimalSplitPos(), v8::internal::compiler::ConstraintBuilder::MeetRegisterConstraints(), v8::internal::compiler::ConstraintBuilder::MeetRegisterConstraintsForLastInstructionInBlock(), v8::internal::compiler::operator<<(), v8::internal::compiler::MoveOptimizer::OptimizeMerge(), v8::internal::compiler::GraphC1Visualizer::PrintSchedule(), v8::internal::compiler::LiveRangeBuilder::ProcessInstructions(), v8::internal::compiler::LiveRangeBuilder::ProcessLoopHeader(), v8::internal::compiler::LiveRangeBuilder::ProcessPhis(), v8::internal::compiler::LiveRangeConnector::ResolveControlFlow(), and v8::internal::compiler::ConstraintBuilder::ResolvePhis().
IsDeferred()
bool v8::internal::compiler::InstructionBlock::IsDeferred () const [inline]
Definition at line 1730 of file instruction.h.
{ return deferred_; }
Referenced by v8::internal::compiler::SpillPlacer::Add(), v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), v8::internal::compiler::LinearScanAllocator::BlockIsDeferredOrImmediatePredecessorIsNotDeferred(), v8::internal::compiler::LiveRangeConnector::CommitSpillsInDeferredBlocks(), v8::internal::compiler::InstructionSequence::ComputeAssemblyOrder(), v8::internal::compiler::LiveRangeConnector::ConnectRanges(), v8::internal::compiler::LinearScanAllocator::ConsiderBlockForControlFlow(), v8::internal::compiler::OperandAssigner::DecideSpillingMode(), v8::internal::compiler::SpillPlacer::FirstBackwardPass(), v8::internal::compiler::SpillPlacer::ForwardPass(), v8::internal::compiler::LinearScanAllocator::HasNonDeferredPredecessor(), v8::internal::compiler::LinearScanAllocator::LastDeferredInstructionIndex(), v8::internal::compiler::operator<<(), v8::internal::compiler::LiveRangeBuilder::ProcessInstructions(), v8::internal::compiler::LiveRangeBuilder::ProcessPhis(), v8::internal::compiler::FrameElider::PropagateIntoBlock(), v8::internal::compiler::RegisterAllocationData::RangesDefinedInDeferredStayInDeferred(), v8::internal::compiler::LiveRangeConnector::ResolveControlFlow(), v8::internal::compiler::SpillPlacer::SecondBackwardPass(), v8::internal::compiler::SpillPlacer::SetSpillRequired(), v8::internal::compiler::RegisterAllocator::Spill(), v8::internal::compiler::LinearScanAllocator::SpillBetweenUntil(), and v8::internal::compiler::LiveRangeBuilder::SpillModeForBlock().
IsHandler()
bool v8::internal::compiler::InstructionBlock::IsHandler () const [inline]
Definition at line 1731 of file instruction.h.
{ return handler_; }
Referenced by v8::internal::compiler::CodeGenerator::AssembleBlock(), and v8::internal::compiler::LiveRangeBuilder::ProcessInstructions().
IsLoopHeader()
bool v8::internal::compiler::InstructionBlock::IsLoopHeader () const [inline]
Definition at line 1742 of file instruction.h.
{ return loop_end_.IsValid(); }
Referenced by v8::internal::compiler::LiveRangeBuilder::BuildLiveRanges(), v8::internal::compiler::RegisterAllocatorVerifier::CreateForBlock(), v8::internal::compiler::RegisterAllocator::FindOptimalSpillingPos(), v8::internal::compiler::RegisterAllocator::FindOptimalSplitPos(), v8::internal::compiler::operator<<(), v8::internal::compiler::LiveRangeBuilder::ProcessLoopHeader(), v8::internal::compiler::ConstraintBuilder::ResolvePhis(), and v8::internal::compiler::RegisterAllocatorVerifier::ValidatePendingAssessment().
IsLoopHeaderInAssemblyOrder()
bool v8::internal::compiler::InstructionBlock::IsLoopHeaderInAssemblyOrder () const [inline]
Definition at line 1746 of file instruction.h.
                                                  {
    return loop_header_alignment_;
  }
IsTableSwitchTarget()
bool v8::internal::compiler::InstructionBlock::IsTableSwitchTarget () const [inline]
Definition at line 1743 of file instruction.h.
{ return table_switch_target_; }
last_instruction_index()
int v8::internal::compiler::InstructionBlock::last_instruction_index () const [inline]
Definition at line 1717 of file instruction.h.
                                     {
    DCHECK_LE(0, code_start_);
    DCHECK_LT(0, code_end_);
    DCHECK_GE(code_end_, code_start_);
    return code_end_ - 1;
  }
References DCHECK_GE, DCHECK_LE, and DCHECK_LT.
Referenced by v8::internal::compiler::LiveRangeBuilder::AddInitialIntervals(), v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), v8::internal::compiler::CodeGenerator::AssembleInstruction(), v8::internal::compiler::SpillPlacer::CommitSpill(), v8::internal::compiler::LiveRangeConnector::CommitSpillsInDeferredBlocks(), v8::internal::compiler::MoveOptimizer::CompressBlock(), v8::internal::compiler::anonymous_namespace{register-allocator.cc}::GetLastInstruction(), v8::internal::compiler::LinearScanAllocator::LastDeferredInstructionIndex(), v8::internal::compiler::MoveOptimizer::LastInstruction(), v8::internal::compiler::ConstraintBuilder::MeetRegisterConstraints(), v8::internal::compiler::ConstraintBuilder::MeetRegisterConstraintsForLastInstructionInBlock(), v8::internal::compiler::operator<<(), v8::internal::compiler::MoveOptimizer::OptimizeMerge(), v8::internal::compiler::GraphC1Visualizer::PrintSchedule(), v8::internal::compiler::LiveRangeBuilder::ProcessInstructions(), v8::internal::compiler::LiveRangeBuilder::ProcessPhis(), v8::internal::compiler::RegisterAllocationData::RangesDefinedInDeferredStayInDeferred(), v8::internal::compiler::LiveRangeConnector::ResolveControlFlow(), v8::internal::compiler::ConstraintBuilder::ResolvePhis(), and v8::internal::compiler::LinearScanAllocator::TryReuseSpillForPhi().
loop_end()
RpoNumber v8::internal::compiler::InstructionBlock::loop_end () const [inline]
Definition at line 1738 of file instruction.h.
                             {
    DCHECK(IsLoopHeader());
    return loop_end_;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::compiler::InstructionSequence::LastLoopInstructionIndex(), and v8::internal::compiler::operator<<().
loop_header()
RpoNumber v8::internal::compiler::InstructionBlock::loop_header () const [inline]
Definition at line 1737 of file instruction.h.
{ return loop_header_; }
Referenced by v8::internal::compiler::anonymous_namespace{register-allocator.cc}::GetContainingLoop(), and v8::internal::compiler::SpillPlacer::SetSpillRequired().
mark_must_construct_frame()
void v8::internal::compiler::InstructionBlock::mark_must_construct_frame () [inline]
Definition at line 1782 of file instruction.h.
{ must_construct_frame_ = true; }
Referenced by v8::internal::compiler::FrameElider::MarkDeConstruction().
mark_must_deconstruct_frame()
void v8::internal::compiler::InstructionBlock::mark_must_deconstruct_frame () [inline]
Definition at line 1785 of file instruction.h.
{ must_deconstruct_frame_ = true; }
mark_needs_frame()
void v8::internal::compiler::InstructionBlock::mark_needs_frame () [inline]
Definition at line 1779 of file instruction.h.
{ needs_frame_ = true; }
Referenced by v8::internal::compiler::SpillPlacer::CommitSpill(), v8::internal::compiler::TopLevelLiveRange::CommitSpillMoves(), v8::internal::compiler::LiveRangeConnector::CommitSpillsInDeferredBlocks(), v8::internal::compiler::TopLevelLiveRange::FilterSpillMoves(), and v8::internal::compiler::FrameElider::PropagateIntoBlock().
MarkHandler()
void v8::internal::compiler::InstructionBlock::MarkHandler () [inline]
Definition at line 1732 of file instruction.h.
{ handler_ = true; }
must_construct_frame()
bool v8::internal::compiler::InstructionBlock::must_construct_frame () const [inline]
Definition at line 1781 of file instruction.h.
{ return must_construct_frame_; }
Referenced by v8::internal::compiler::JumpThreading::ComputeForwarding(), and v8::internal::compiler::operator<<().
must_deconstruct_frame()
bool v8::internal::compiler::InstructionBlock::must_deconstruct_frame () const [inline]
Definition at line 1784 of file instruction.h.
{ return must_deconstruct_frame_; }
Referenced by v8::internal::compiler::CodeGenerator::AssembleInstruction(), v8::internal::compiler::JumpThreading::ComputeForwarding(), and v8::internal::compiler::operator<<().
needs_frame()
bool v8::internal::compiler::InstructionBlock::needs_frame () const [inline]
Definition at line 1778 of file instruction.h.
{ return needs_frame_; }
Referenced by v8::internal::compiler::operator<<(), and v8::internal::compiler::FrameElider::PropagateIntoBlock().
omitted_by_jump_threading()
bool v8::internal::compiler::InstructionBlock::omitted_by_jump_threading () const [inline]
Definition at line 1749 of file instruction.h.
{ return omitted_by_jump_threading_; }
PhiAt()
PhiInstruction* v8::internal::compiler::InstructionBlock::PhiAt (size_t i) const [inline]
Definition at line 1768 of file instruction.h.
{ return phis_[i]; }
References v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by v8::internal::compiler::InstructionSelector::SelectInstructions().
phis()
const PhiInstructions& v8::internal::compiler::InstructionBlock::phis () const [inline]
Definition at line 1767 of file instruction.h.
{ return phis_; }
Referenced by v8::internal::compiler::BundleBuilder::BuildBundles(), v8::internal::compiler::LiveRangeBuilder::ComputeLiveOut(), v8::internal::compiler::RegisterAllocatorVerifier::CreateForBlock(), v8::internal::compiler::operator<<(), v8::internal::compiler::LiveRangeBuilder::ProcessPhis(), v8::internal::compiler::ConstraintBuilder::ResolvePhis(), v8::internal::compiler::InstructionSelector::SelectInstructions(), and v8::internal::compiler::RegisterAllocatorVerifier::ValidatePendingAssessment().
PredecessorCount()
size_t v8::internal::compiler::InstructionBlock::PredecessorCount () const [inline]
Definition at line 1755 of file instruction.h.
{ return predecessors_.size(); }
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), v8::internal::compiler::LinearScanAllocator::BlockIsDeferredOrImmediatePredecessorIsNotDeferred(), v8::internal::compiler::LiveRangeConnector::CanEagerlyResolveControlFlow(), v8::internal::compiler::SpillPlacer::CommitSpill(), v8::internal::compiler::LinearScanAllocator::ComputeStateFromManyPredecessors(), v8::internal::compiler::RegisterAllocatorVerifier::CreateForBlock(), v8::internal::compiler::ConstraintBuilder::MeetRegisterConstraintsForLastInstructionInBlock(), v8::internal::compiler::MoveOptimizer::OptimizeMerge(), v8::internal::compiler::FrameElider::PropagateIntoBlock(), v8::internal::compiler::LiveRangeConnector::ResolveControlFlow(), v8::internal::compiler::InstructionSequence::ValidateEdgeSplitForm(), and v8::internal::compiler::RegisterAllocatorVerifier::ValidatePendingAssessment().
PredecessorIndexOf()
size_t v8::internal::compiler::InstructionBlock::PredecessorIndexOf (RpoNumber rpo_number) const
Definition at line 684 of file instruction.cc.
                                                                      {
  size_t j = 0;
  for (InstructionBlock::Predecessors::const_iterator i = predecessors_.begin();
       i != predecessors_.end(); ++i, ++j) {
    if (*i == rpo_number) break;
  }
  return j;
}
References v8::internal::ZoneVector< T >::begin(), v8::internal::ZoneVector< T >::end(), predecessors_, and rpo_number().
Referenced by v8::internal::compiler::LiveRangeBuilder::ComputeLiveOut().
predecessors() [1/2]
Predecessors& v8::internal::compiler::InstructionBlock::predecessors () [inline]
Definition at line 1753 of file instruction.h.
{ return predecessors_; }
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), v8::internal::compiler::LinearScanAllocator::BlockIsDeferredOrImmediatePredecessorIsNotDeferred(), v8::internal::compiler::LiveRangeConnector::CanEagerlyResolveControlFlow(), v8::internal::compiler::LinearScanAllocator::ChooseOneOfTwoPredecessorStates(), v8::internal::compiler::LiveRangeConnector::CommitSpillsInDeferredBlocks(), v8::internal::compiler::LinearScanAllocator::ComputeStateFromManyPredecessors(), v8::internal::compiler::RegisterAllocatorVerifier::CreateForBlock(), v8::internal::compiler::SpillPlacer::ForwardPass(), v8::internal::compiler::LinearScanAllocator::HasNonDeferredPredecessor(), v8::internal::compiler::InstructionBlockFor(), v8::internal::compiler::operator<<(), v8::internal::compiler::MoveOptimizer::OptimizeMerge(), v8::internal::compiler::LiveRangeBuilder::ProcessPhis(), v8::internal::compiler::FrameElider::PropagateIntoBlock(), v8::internal::compiler::ConstraintBuilder::ResolvePhis(), v8::internal::compiler::LinearScanAllocator::TryReuseSpillForPhi(), v8::internal::compiler::InstructionSequence::ValidateEdgeSplitForm(), and v8::internal::compiler::RegisterAllocatorVerifier::ValidatePendingAssessment().
predecessors() [2/2]
const Predecessors& v8::internal::compiler::InstructionBlock::predecessors () const [inline]
Definition at line 1754 of file instruction.h.
{ return predecessors_; }
rpo_number()
RpoNumber v8::internal::compiler::InstructionBlock::rpo_number () const [inline]
Definition at line 1736 of file instruction.h.
{ return rpo_number_; }
Referenced by v8::internal::compiler::SpillPlacer::Add(), v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), v8::internal::compiler::UnwindingInfoWriter::BeginInstructionBlock(), v8::internal::compiler::LinearScanAllocator::BlockIsDeferredOrImmediatePredecessorIsNotDeferred(), v8::internal::compiler::LiveRangeConnector::CanEagerlyResolveControlFlow(), v8::internal::compiler::LiveRangeConnector::CommitSpillsInDeferredBlocks(), v8::internal::compiler::JumpThreading::ComputeForwarding(), v8::internal::compiler::LiveRangeBuilder::ComputeLiveOut(), v8::internal::compiler::LiveRangeConnector::ConnectRanges(), v8::internal::compiler::RegisterAllocatorVerifier::CreateForBlock(), v8::internal::compiler::InstructionSequence::EndBlock(), v8::internal::compiler::RegisterAllocator::FindOptimalSplitPos(), v8::internal::compiler::LinearScanAllocator::LastDeferredInstructionIndex(), v8::internal::compiler::operator<<(), PredecessorIndexOf(), v8::internal::compiler::InstructionSequence::PrintBlock(), v8::internal::compiler::LiveRangeBuilder::ProcessLoopHeader(), v8::internal::compiler::LiveRangeBuilder::ProcessPhis(), v8::internal::compiler::LiveRangeConnector::ResolveControlFlow(), v8::internal::compiler::SpillPlacer::SetSpillRequired(), and v8::internal::compiler::RegisterAllocatorVerifier::VerifyGapMoves().
set_ao_number()
void v8::internal::compiler::InstructionBlock::set_ao_number (RpoNumber ao_number) [inline]
Definition at line 1771 of file instruction.h.
{ ao_number_ = ao_number; }
Referenced by v8::internal::compiler::InstructionSequence::ComputeAssemblyOrder().
set_code_end()
void v8::internal::compiler::InstructionBlock::set_code_end (int32_t end) [inline]
Definition at line 1728 of file instruction.h.
{ code_end_ = end; }
References v8::internal::compiler::end().
Referenced by v8::internal::compiler::InstructionSequence::EndBlock(), and v8::internal::compiler::InstructionSelector::VisitBlock().
set_code_start()
void v8::internal::compiler::InstructionBlock::set_code_start (int32_t start) [inline]
Definition at line 1725 of file instruction.h.
{ code_start_ = start; }
Referenced by v8::internal::compiler::InstructionSequence::StartBlock(), and v8::internal::compiler::InstructionSelector::VisitBlock().
set_code_target_alignment()
void v8::internal::compiler::InstructionBlock::set_code_target_alignment (bool val) [inline]
Definition at line 1773 of file instruction.h.
{ code_target_alignment_ = val; }
set_dominator()
void v8::internal::compiler::InstructionBlock::set_dominator (RpoNumber dominator) [inline]
Definition at line 1764 of file instruction.h.
{ dominator_ = dominator; }
set_loop_header_alignment()
void v8::internal::compiler::InstructionBlock::set_loop_header_alignment (bool val) [inline]
Definition at line 1774 of file instruction.h.
{ loop_header_alignment_ = val; }
Referenced by v8::internal::compiler::InstructionSequence::ComputeAssemblyOrder().
set_omitted_by_jump_threading()
void v8::internal::compiler::InstructionBlock::set_omitted_by_jump_threading () [inline]
Definition at line 1750 of file instruction.h.
{ omitted_by_jump_threading_ = true; }
set_table_switch_target()
void v8::internal::compiler::InstructionBlock::set_table_switch_target (bool val) [inline]
Definition at line 1776 of file instruction.h.
{ table_switch_target_ = val; }
Referenced by v8::internal::compiler::InstructionSelector::MarkAsTableSwitchTarget().
ShouldAlignCodeTarget()
bool v8::internal::compiler::InstructionBlock::ShouldAlignCodeTarget () const [inline]
Definition at line 1744 of file instruction.h.
{ return code_target_alignment_; }
ShouldAlignLoopHeader()
bool v8::internal::compiler::InstructionBlock::ShouldAlignLoopHeader () const [inline]
Definition at line 1745 of file instruction.h.
{ return loop_header_alignment_; }
SuccessorCount()
size_t v8::internal::compiler::InstructionBlock::SuccessorCount () const [inline]
Definition at line 1761 of file instruction.h.
{ return successors_.size(); }
Referenced by v8::internal::compiler::InstructionSequence::ComputeAssemblyOrder(), v8::internal::compiler::MoveOptimizer::OptimizeMerge(), v8::internal::compiler::FrameElider::PropagateIntoBlock(), and v8::internal::compiler::LiveRangeConnector::ResolveControlFlow().
successors() [1/2]
Successors& v8::internal::compiler::InstructionBlock::successors () [inline]
Definition at line 1759 of file instruction.h.
{ return successors_; }
Referenced by v8::internal::compiler::CodeGenerator::AssembleInstruction(), v8::internal::compiler::InstructionSequence::ComputeAssemblyOrder(), v8::internal::compiler::LiveRangeBuilder::ComputeLiveOut(), v8::internal::compiler::UnwindingInfoWriter::EndInstructionBlock(), v8::internal::compiler::SpillPlacer::FirstBackwardPass(), v8::internal::compiler::InstructionBlockFor(), v8::internal::compiler::ConstraintBuilder::MeetRegisterConstraintsForLastInstructionInBlock(), v8::internal::compiler::operator<<(), v8::internal::compiler::FrameElider::PropagateIntoBlock(), and v8::internal::compiler::SpillPlacer::SecondBackwardPass().
successors() [2/2]
const Successors& v8::internal::compiler::InstructionBlock::successors () const [inline]
Definition at line 1760 of file instruction.h.
{ return successors_; }
UnmarkHandler()
void v8::internal::compiler::InstructionBlock::UnmarkHandler () [inline]
Definition at line 1733 of file instruction.h.
{ handler_ = false; }
Member Data Documentation
ao_number_
RpoNumber v8::internal::compiler::InstructionBlock::ao_number_ [private]
Definition at line 1792 of file instruction.h.
code_end_
int32_t v8::internal::compiler::InstructionBlock::code_end_ = -1 [private]
Definition at line 1798 of file instruction.h.
code_start_
int32_t v8::internal::compiler::InstructionBlock::code_start_ [private]
Definition at line 1797 of file instruction.h.
code_target_alignment_
bool v8::internal::compiler::InstructionBlock::code_target_alignment_ [private]
Definition at line 1803 of file instruction.h.
deferred_
const bool v8::internal::compiler::InstructionBlock::deferred_ [private]
Definition at line 1799 of file instruction.h.
dominator_
RpoNumber v8::internal::compiler::InstructionBlock::dominator_ [private]
Definition at line 1796 of file instruction.h.
handler_
bool v8::internal::compiler::InstructionBlock::handler_ [private]
Definition at line 1800 of file instruction.h.
loop_end_
const RpoNumber v8::internal::compiler::InstructionBlock::loop_end_ [private]
Definition at line 1795 of file instruction.h.
loop_header_
const RpoNumber v8::internal::compiler::InstructionBlock::loop_header_ [private]
Definition at line 1794 of file instruction.h.
loop_header_alignment_
bool v8::internal::compiler::InstructionBlock::loop_header_alignment_ [private]
Definition at line 1805 of file instruction.h.
must_construct_frame_
bool v8::internal::compiler::InstructionBlock::must_construct_frame_ [private]
Definition at line 1808 of file instruction.h.
must_deconstruct_frame_
bool v8::internal::compiler::InstructionBlock::must_deconstruct_frame_ [private]
Definition at line 1809 of file instruction.h.
needs_frame_
bool v8::internal::compiler::InstructionBlock::needs_frame_ [private]
Definition at line 1807 of file instruction.h.
omitted_by_jump_threading_
bool v8::internal::compiler::InstructionBlock::omitted_by_jump_threading_ [private]
Definition at line 1810 of file instruction.h.
phis_
PhiInstructions v8::internal::compiler::InstructionBlock::phis_ [private]
Definition at line 1791 of file instruction.h.
predecessors_
Predecessors v8::internal::compiler::InstructionBlock::predecessors_ [private]
Definition at line 1790 of file instruction.h.
Referenced by PredecessorIndexOf().
rpo_number_
const RpoNumber v8::internal::compiler::InstructionBlock::rpo_number_ [private]
Definition at line 1793 of file instruction.h.
successors_
Successors v8::internal::compiler::InstructionBlock::successors_ [private]
Definition at line 1789 of file instruction.h.
table_switch_target_
bool v8::internal::compiler::InstructionBlock::table_switch_target_ [private]
Definition at line 1801 of file instruction.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/instruction.h
/mnt/V8SourceCode/src/compiler/backend/instruction.cc