v8::internal::OptimizingCompileInputQueue Class Reference
#include <optimizing-compile-dispatcher.h>
Public Member Functions
bool IsAvailable ()
size_t Length ()
OptimizingCompileInputQueue (int capacity)
TurbofanCompilationJob * Dequeue (OptimizingCompileTaskState &task_state)
TurbofanCompilationJob * DequeueIfIsolateMatches (OptimizingCompileTaskState &task_state)
bool Enqueue (std::unique_ptr< TurbofanCompilationJob > &job)
void FlushJobsForIsolate (Isolate *isolate)
bool HasJobForIsolate (Isolate *isolate)
void Prioritize (Isolate *isolate, Tagged< SharedFunctionInfo > function)
Private Attributes
std::deque< TurbofanCompilationJob * > queue_
size_t capacity_
base::Mutex mutex_
base::ConditionVariable task_finished_
Friends
class OptimizingCompileTaskExecutor
Detailed Description
Definition at line 35 of file optimizing-compile-dispatcher.h.
Constructor & Destructor Documentation
OptimizingCompileInputQueue()
v8::internal::OptimizingCompileInputQueue::OptimizingCompileInputQueue (int capacity) [inline], [explicit]
Definition at line 47 of file optimizing-compile-dispatcher.h.
: capacity_(capacity) {}
Member Function Documentation
Dequeue()
TurbofanCompilationJob * v8::internal::OptimizingCompileInputQueue::Dequeue (OptimizingCompileTaskState & task_state)
Definition at line 421 of file optimizing-compile-dispatcher.cc.
                                            {
  base::MutexGuard access(&mutex_);
  DCHECK_NULL(task_state.isolate);
  if (queue_.empty()) return nullptr;
  TurbofanCompilationJob* job = queue_.front();
  queue_.pop_front();
  DCHECK_NOT_NULL(job);
  task_state.isolate = job->isolate();
  task_state.job = job;
  return job;
}
References DCHECK_NOT_NULL, DCHECK_NULL, v8::internal::TurbofanCompilationJob::isolate(), v8::internal::OptimizingCompileTaskState::isolate, v8::internal::OptimizingCompileTaskState::job, mutex_, and queue_.
Referenced by v8::internal::OptimizingCompileTaskExecutor::NextInput().
DequeueIfIsolateMatches()
TurbofanCompilationJob * v8::internal::OptimizingCompileInputQueue::DequeueIfIsolateMatches (OptimizingCompileTaskState & task_state)
Definition at line 434 of file optimizing-compile-dispatcher.cc.
                                            {
  base::MutexGuard access(&mutex_);
  if (queue_.empty()) return nullptr;
  TurbofanCompilationJob* job = queue_.front();
  DCHECK_NOT_NULL(job);
  if (job->isolate() != task_state.isolate) return nullptr;
  DCHECK_NULL(task_state.job);
  task_state.job = job;
  queue_.pop_front();
  return job;
}
References DCHECK_NOT_NULL, DCHECK_NULL, v8::internal::TurbofanCompilationJob::isolate(), v8::internal::OptimizingCompileTaskState::isolate, v8::internal::OptimizingCompileTaskState::job, mutex_, and queue_.
Referenced by v8::internal::OptimizingCompileTaskExecutor::NextInputIfIsolateMatches().
Enqueue()
bool v8::internal::OptimizingCompileInputQueue::Enqueue (std::unique_ptr< TurbofanCompilationJob > & job)
Definition at line 447 of file optimizing-compile-dispatcher.cc.
                                                {
  base::MutexGuard access(&mutex_);
  if (queue_.size() < capacity_) {
    queue_.push_back(job.release());
    return true;
  } else {
    return false;
  }
}
References capacity_, mutex_, and queue_.
Referenced by v8::internal::OptimizingCompileTaskExecutor::TryQueueForOptimization().
FlushJobsForIsolate()
void v8::internal::OptimizingCompileInputQueue::FlushJobsForIsolate (Isolate * isolate)
Definition at line 403 of file optimizing-compile-dispatcher.cc.
                                                                      {
  base::MutexGuard access(&mutex_);
  std::erase_if(queue_, [isolate](TurbofanCompilationJob* job) {
    if (job->isolate() != isolate) return false;
    Compiler::DisposeTurbofanCompilationJob(isolate, job);
    delete job;
    return true;
  });
}
References v8::internal::Compiler::DisposeTurbofanCompilationJob(), v8::base::erase_if(), v8::internal::TurbofanCompilationJob::isolate(), mutex_, and queue_.
Referenced by v8::internal::OptimizingCompileDispatcher::FlushInputQueue().
HasJobForIsolate()
bool v8::internal::OptimizingCompileInputQueue::HasJobForIsolate (Isolate * isolate)
Definition at line 413 of file optimizing-compile-dispatcher.cc.
                                                                   {
  mutex_.AssertHeld();
  return std::find_if(queue_.begin(), queue_.end(),
                      [isolate](TurbofanCompilationJob* job) {
                        return job->isolate() == isolate;
                      }) != queue_.end();
}
References v8::base::Mutex::AssertHeld(), mutex_, and queue_.
Referenced by v8::internal::OptimizingCompileTaskExecutor::CancelCompilationJobsForIsolate(), v8::internal::OptimizingCompileTaskExecutor::HasCompilationJobsForIsolate(), and v8::internal::OptimizingCompileTaskExecutor::WaitUntilCompilationJobsDoneForIsolate().
IsAvailable()
bool v8::internal::OptimizingCompileInputQueue::IsAvailable () [inline]
Definition at line 37 of file optimizing-compile-dispatcher.h.
                            {
    base::MutexGuard access(&mutex_);
    return queue_.size() < capacity_;
  }
Length()
size_t v8::internal::OptimizingCompileInputQueue::Length () [inline]
Definition at line 42 of file optimizing-compile-dispatcher.h.
                         {
    base::MutexGuard access_queue(&mutex_);
    return queue_.size();
  }
Referenced by v8::internal::OptimizingCompileTaskExecutor::CompileTask::GetMaxConcurrency(), and v8::internal::OptimizingCompileTaskExecutor::~OptimizingCompileTaskExecutor().
Prioritize()
void v8::internal::OptimizingCompileInputQueue::Prioritize (Isolate * isolate, Tagged< SharedFunctionInfo > function)
Definition at line 377 of file optimizing-compile-dispatcher.cc.
                                                           {
  // Ensure that we only run this method on the main thread. This makes sure
  // that we never dereference handles during a safepoint.
  DCHECK_EQ(isolate->thread_id(), ThreadId::Current());
  base::MutexGuard access(&mutex_);
  auto it =
      std::find_if(queue_.begin(), queue_.end(),
                   [isolate, function](TurbofanCompilationJob* job) {
                     // Early bailout to avoid dereferencing handles from other
                     // isolates. The other isolate could be in a safepoint/GC
                     // and dereferencing the handle is therefore invalid.
                     if (job->isolate() != isolate) return false;
                     return *job->compilation_info()->shared_info() == function;
                   });
  if (it != queue_.end()) {
    auto first_for_isolate = std::find_if(
        queue_.begin(), queue_.end(), [isolate](TurbofanCompilationJob* job) {
          return job->isolate() == isolate;
        });
    DCHECK_NE(first_for_isolate, queue_.end());
    std::iter_swap(it, first_for_isolate);
  }
}
References v8::internal::ThreadId::Current(), DCHECK_EQ, DCHECK_NE, mutex_, queue_, and v8::internal::Isolate::thread_id().
Referenced by v8::internal::OptimizingCompileDispatcher::Prioritize().
Friends And Related Function Documentation
OptimizingCompileTaskExecutor
friend class OptimizingCompileTaskExecutor [friend]
Definition at line 67 of file optimizing-compile-dispatcher.h.
Member Data Documentation
capacity_
size_t v8::internal::OptimizingCompileInputQueue::capacity_ [private]
Definition at line 62 of file optimizing-compile-dispatcher.h.
Referenced by Enqueue().
mutex_
base::Mutex v8::internal::OptimizingCompileInputQueue::mutex_ [private]
Definition at line 64 of file optimizing-compile-dispatcher.h.
Referenced by v8::internal::OptimizingCompileTaskExecutor::CancelCompilationJobsForIsolate(), v8::internal::OptimizingCompileTaskExecutor::ClearTaskState(), Dequeue(), DequeueIfIsolateMatches(), Enqueue(), FlushJobsForIsolate(), v8::internal::OptimizingCompileTaskExecutor::HasCompilationJobsForIsolate(), HasJobForIsolate(), v8::internal::OptimizingCompileTaskExecutor::IsTaskRunningForIsolate(), Prioritize(), v8::internal::OptimizingCompileTaskExecutor::ResetJob(), and v8::internal::OptimizingCompileTaskExecutor::WaitUntilCompilationJobsDoneForIsolate().
queue_
std::deque<TurbofanCompilationJob*> v8::internal::OptimizingCompileInputQueue::queue_ [private]
Definition at line 61 of file optimizing-compile-dispatcher.h.
Referenced by Dequeue(), DequeueIfIsolateMatches(), Enqueue(), FlushJobsForIsolate(), HasJobForIsolate(), and Prioritize().
task_finished_
base::ConditionVariable v8::internal::OptimizingCompileInputQueue::task_finished_ [private]
Definition at line 65 of file optimizing-compile-dispatcher.h.
Referenced by v8::internal::OptimizingCompileTaskExecutor::ClearTaskState(), and v8::internal::OptimizingCompileTaskExecutor::WaitUntilCompilationJobsDoneForIsolate().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler-dispatcher/optimizing-compile-dispatcher.h
/mnt/V8SourceCode/src/compiler-dispatcher/optimizing-compile-dispatcher.cc