v8::PageAllocator::AllocationHint Class Reference
Optional hints for AllocatePages().
#include <v8-platform.h>
Public Member Functions
AllocationHint ()=default
constexpr V8_WARN_UNUSED_RESULT AllocationHint WithAddress (void *address) const
constexpr V8_WARN_UNUSED_RESULT AllocationHint WithMayGrow () const
bool MayGrow () const
void * Address () const
Private Member Functions
constexpr AllocationHint (void *address, bool may_grow)
Private Attributes
void * address_ = nullptr
bool may_grow_ = false
Detailed Description
Optional hints for AllocatePages().
Definition at line 505 of file v8-platform.h.
Constructor & Destructor Documentation
AllocationHint() [1/2]
v8::PageAllocator::AllocationHint::AllocationHint () [default]
Referenced by WithAddress(), and WithMayGrow().
AllocationHint() [2/2]
constexpr v8::PageAllocator::AllocationHint::AllocationHint (void * address, bool may_grow) [inline], [constexpr], [private]
Definition at line 522 of file v8-platform.h.
        : address_(address), may_grow_(may_grow) {}
Member Function Documentation
Address()
void* v8::PageAllocator::AllocationHint::Address () const [inline]
Definition at line 519 of file v8-platform.h.
{ return address_; }
References address_.
Referenced by v8::PageAllocator::AllocatePages(), v8::base::BoundedPageAllocator::AllocatePages(), and v8::internal::AllocatePages().
MayGrow()
bool v8::PageAllocator::AllocationHint::MayGrow () const [inline]
Definition at line 518 of file v8-platform.h.
{ return may_grow_; }
References may_grow_.
Referenced by v8::base::BoundedPageAllocator::AllocatePages().
WithAddress()
constexpr V8_WARN_UNUSED_RESULT AllocationHint v8::PageAllocator::AllocationHint::WithAddress (void * address) const [inline], [constexpr]
Definition at line 509 of file v8-platform.h.
                             {
      return AllocationHint(address, may_grow_);
    }
References AllocationHint(), and may_grow_.
Referenced by v8::internal::MemoryAllocator::AllocateAlignedMemory(), v8::internal::AllocatePages(), and v8::internal::VirtualMemoryCage::InitReservation().
WithMayGrow()
constexpr V8_WARN_UNUSED_RESULT AllocationHint v8::PageAllocator::AllocationHint::WithMayGrow () const [inline], [constexpr]
Definition at line 514 of file v8-platform.h.
                                                                       {
      return AllocationHint(address_, true);
    }
References address_, and AllocationHint().
Referenced by v8::internal::MemoryAllocator::AllocateAlignedMemory().
Member Data Documentation
address_
void* v8::PageAllocator::AllocationHint::address_ = nullptr [private]
Definition at line 525 of file v8-platform.h.
Referenced by Address(), and WithMayGrow().
may_grow_
bool v8::PageAllocator::AllocationHint::may_grow_ = false [private]
Definition at line 526 of file v8-platform.h.
Referenced by MayGrow(), and WithAddress().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/v8-platform.h