v8::internal::anonymous_namespace{scavenger.cc}::YoungGenerationConservativeStackVisitor Class Reference
Public Member Functions
YoungGenerationConservativeStackVisitor (Isolate *isolate, RootVisitor *root_visitor)
~YoungGenerationConservativeStackVisitor ()
Static Private Member Functions
static bool FilterPage (const MemoryChunk *chunk)
static bool FilterLargeObject (Tagged< HeapObject > object, MapWord map_word)
static bool FilterNormalObject (Tagged< HeapObject > object, MapWord map_word, MarkingBitmap *bitmap)
static void HandleObjectFound (Tagged< HeapObject > object, size_t object_size, MarkingBitmap *bitmap)
Private Attributes
Isolate *const isolate_
Static Private Attributes
static constexpr bool kOnlyVisitMainV8Cage = true
Friends
class ConservativeStackVisitorBase< YoungGenerationConservativeStackVisitor >
Detailed Description
Definition at line 379 of file scavenger.cc.
Constructor & Destructor Documentation
YoungGenerationConservativeStackVisitor()
v8::internal::anonymous_namespace{scavenger.cc}::YoungGenerationConservativeStackVisitor::YoungGenerationConservativeStackVisitor (Isolate * isolate, RootVisitor * root_visitor) [inline]
Definition at line 383 of file scavenger.cc.
      : ConservativeStackVisitorBase(isolate, root_visitor), isolate_(isolate) {
    DCHECK_NE(isolate->heap()->ConservativeStackScanningModeForMinorGC(),
              Heap::StackScanMode::kNone);
    DCHECK(!v8_flags.minor_ms);
    DCHECK(!v8_flags.sticky_mark_bits);
    DCHECK(std::all_of(
        isolate_->heap()->semi_space_new_space()->to_space().begin(),
        isolate_->heap()->semi_space_new_space()->to_space().end(),
        [](const PageMetadata* page) {
          return page->marking_bitmap()->IsClean();
        }));
    DCHECK(std::all_of(
        isolate_->heap()->semi_space_new_space()->from_space().begin(),
        isolate_->heap()->semi_space_new_space()->from_space().end(),
        [](const PageMetadata* page) {
          return page->marking_bitmap()->IsClean();
        }));
  }
References v8::base::all_of(), v8::internal::Heap::ConservativeStackScanningModeForMinorGC(), v8::internal::DCHECK(), DCHECK_NE, v8::internal::Isolate::heap(), v8::internal::Heap::kNone, and v8::internal::v8_flags.
 YoungGenerationConservativeStackVisitor()
v8::internal::anonymous_namespace{scavenger.cc}::YoungGenerationConservativeStackVisitor::~YoungGenerationConservativeStackVisitor () [inline]
Definition at line 404 of file scavenger.cc.
                                             {
    DCHECK(std::all_of(
        isolate_->heap()->semi_space_new_space()->to_space().begin(),
        isolate_->heap()->semi_space_new_space()->to_space().end(),
        [](const PageMetadata* page) {
          return page->marking_bitmap()->IsClean();
        }));
    for (PageMetadata* page :
         isolate_->heap()->semi_space_new_space()->from_space()) {
      page->marking_bitmap()->Clear<AccessMode::NON_ATOMIC>();
    }
  }
References v8::base::all_of(), v8::internal::MarkingBitmap::Clear(), v8::internal::DCHECK(), v8::internal::SemiSpaceNewSpace::from_space(), v8::internal::MemoryChunkMetadata::heap(), v8::internal::MutablePageMetadata::marking_bitmap(), v8::internal::NON_ATOMIC, and v8::internal::Heap::semi_space_new_space().
Member Function Documentation
FilterLargeObject()
static bool v8::internal::anonymous_namespace{scavenger.cc}::YoungGenerationConservativeStackVisitor::FilterLargeObject (Tagged< HeapObject > object, MapWord map_word) [inline], [static], [private]
Definition at line 424 of file scavenger.cc.
                                                                             {
    DCHECK_EQ(map_word, object->map_word(kRelaxedLoad));
    return !HeapLayout::IsSelfForwarded(object, map_word);
  }
References DCHECK_EQ, v8::internal::HeapLayout::IsSelfForwarded(), and v8::kRelaxedLoad.
FilterNormalObject()
static bool v8::internal::anonymous_namespace{scavenger.cc}::YoungGenerationConservativeStackVisitor::FilterNormalObject (Tagged< HeapObject > object, MapWord map_word, MarkingBitmap * bitmap) [inline], [static], [private]
Definition at line 429 of file scavenger.cc.
                                                        {
    DCHECK_EQ(map_word, object->map_word(kRelaxedLoad));
    if (map_word.IsForwardingAddress()) {
      DCHECK(HeapLayout::IsSelfForwarded(object));
      DCHECK(
          MarkingBitmap::MarkBitFromAddress(bitmap, object->address()).Get());
      return false;
    }
    MarkingBitmap::MarkBitFromAddress(bitmap, object->address())
        .Set<AccessMode::NON_ATOMIC>();
    return true;
  }
References v8::internal::Tagged< HeapObject >::address(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::MarkBit::Get(), v8::internal::MapWord::IsForwardingAddress(), v8::internal::HeapLayout::IsSelfForwarded(), v8::kRelaxedLoad, v8::internal::MarkingBitmap::MarkBitFromAddress(), v8::internal::NON_ATOMIC, and v8::internal::MarkBit::Set().
FilterPage()
static bool v8::internal::anonymous_namespace{scavenger.cc}::YoungGenerationConservativeStackVisitor::FilterPage (const MemoryChunk * chunk) [inline], [static], [private]
Definition at line 420 of file scavenger.cc.
                                                   {
    return chunk->IsFromPage();
  }
References v8::internal::MemoryChunk::IsFromPage().
HandleObjectFound()
static void v8::internal::anonymous_namespace{scavenger.cc}::YoungGenerationConservativeStackVisitor::HandleObjectFound (Tagged< HeapObject > object, size_t object_size, MarkingBitmap * bitmap) [inline], [static], [private]
Definition at line 443 of file scavenger.cc.
                                                       {
    DCHECK_EQ(object_size, object->Size());
    Address object_address = object->address();
    if (object_address + object_size <
        PageMetadata::FromHeapObject(object)->area_end()) {
      MarkingBitmap::MarkBitFromAddress(bitmap, object_address + object_size)
          .Set<AccessMode::NON_ATOMIC>();
    }
  }
References DCHECK_EQ, v8::internal::PageMetadata::FromHeapObject(), v8::internal::MarkingBitmap::MarkBitFromAddress(), v8::internal::NON_ATOMIC, and v8::internal::MarkBit::Set().
Friends And Related Function Documentation
ConservativeStackVisitorBase< YoungGenerationConservativeStackVisitor >
friend class ConservativeStackVisitorBase< YoungGenerationConservativeStackVisitor > [friend]
Definition at line 454 of file scavenger.cc.
Member Data Documentation
isolate_
Isolate* const v8::internal::anonymous_namespace{scavenger.cc}::YoungGenerationConservativeStackVisitor::isolate_ [private]
Definition at line 454 of file scavenger.cc.
kOnlyVisitMainV8Cage
constexpr bool v8::internal::anonymous_namespace{scavenger.cc}::YoungGenerationConservativeStackVisitor::kOnlyVisitMainV8Cage = true [static], [constexpr], [private]
Definition at line 418 of file scavenger.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/scavenger.cc