v8::internal::maglev::ToName Class Reference
#include <maglev-ir.h>
Public Member Functions
ToName (uint64_t bitfield)
Input & context ()
Input & value_input ()
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties = OpProperties::JSCall()
static constexpr Base::InputTypes kInputTypes
Private Types
using Base = FixedInputValueNodeT< 2, ToName >
Additional Inherited Members
Detailed Description
Definition at line 5117 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::ToName::Base = FixedInputValueNodeT<2, ToName> [private]
Definition at line 5118 of file maglev-ir.h.
Constructor & Destructor Documentation
ToName()
v8::internal::maglev::ToName::ToName (uint64_t bitfield) [inline], [explicit]
Definition at line 5121 of file maglev-ir.h.
: Base(bitfield) {}
Member Function Documentation
context()
Input& v8::internal::maglev::ToName::context () [inline]
Definition at line 5128 of file maglev-ir.h.
{ return Node::input(0); }
References v8::internal::maglev::NodeBase::input().
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::ToName::GenerateCode (MaglevAssembler * , const ProcessingState &)
MaxCallStackArgs()
int v8::internal::maglev::ToName::MaxCallStackArgs () const
PrintParams()
void v8::internal::maglev::ToName::PrintParams (std::ostream & , MaglevGraphLabeller *) const [inline]
Definition at line 5134 of file maglev-ir.h.
{}
SetValueLocationConstraints()
void v8::internal::maglev::ToName::SetValueLocationConstraints ()
value_input()
Input& v8::internal::maglev::ToName::value_input () [inline]
Definition at line 5129 of file maglev-ir.h.
{ return Node::input(1); }
References v8::internal::maglev::NodeBase::input().
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::ToName::kInputTypes [static], [constexpr]
Initial value:
{
      ValueRepresentation::kTagged, ValueRepresentation::kTagged}
Definition at line 5125 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::ToName::kProperties = OpProperties::JSCall() [static], [constexpr]
Definition at line 5124 of file maglev-ir.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h