v8::PrimitiveArray Class Reference
An array to hold Primitive values.
#include <v8-primitive.h>
Public Member Functions
int Length () const
void Set (Isolate *isolate, int index, Local< Primitive > item)
Local< Primitive > Get (Isolate *isolate, int index)
Static Public Member Functions
static Local< PrimitiveArray > New (Isolate *isolate, int length)
static PrimitiveArray * Cast (Data *data)
Static Private Member Functions
static void CheckCast (Data *obj)
Detailed Description
An array to hold Primitive values.
This is used by the embedder to pass host defined options to the ScriptOptions during compilation.
This is passed back to the embedder as part of HostImportModuleDynamicallyCallback for module loading.
Definition at line 58 of file v8-primitive.h.
Member Function Documentation
Cast()
static PrimitiveArray* v8::PrimitiveArray::Cast (Data * data) [inline], [static]
Definition at line 65 of file v8-primitive.h.
                                                    {
#ifdef V8_ENABLE_CHECKS
    CheckCast(data);
#endif
    return reinterpret_cast<PrimitiveArray*>(data);
  }
CheckCast()
void v8::PrimitiveArray::CheckCast (v8::Data * that) [static], [private]
Definition at line 2095 of file api.cc.
                                             {
  auto obj = Utils::OpenDirectHandle(that);
  Utils::ApiCheck(
      i::IsFixedArray(*obj), "v8::PrimitiveArray::Cast",
      "Value is not a PrimitiveArray; this is a temporary issue, v8::Data and "
      "v8::PrimitiveArray will not be compatible in the future");
}
References v8::Utils::ApiCheck(), and v8::Utils::OpenDirectHandle().
Get()
Local< Primitive > v8::PrimitiveArray::Get (Isolate * isolate, int index)
Definition at line 2084 of file api.cc.
                                                                   {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  auto array = Utils::OpenDirectHandle(this);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  Utils::ApiCheck(index >= 0 && index < array->length(),
                  "v8::PrimitiveArray::Get",
                  "index must be greater than or equal to 0 and less than the "
                  "array length");
  return ToApiHandle<Primitive>(i::direct_handle(array->get(index), i_isolate));
}
References v8::Utils::ApiCheck(), v8::internal::direct_handle(), v8::internal::index, v8::internal::length, and v8::Utils::OpenDirectHandle().
Length()
int v8::PrimitiveArray::Length () const
Definition at line 2068 of file api.cc.
                                 {
  return Utils::OpenDirectHandle(this)->length();
}
References v8::Utils::OpenDirectHandle().
New()
Local< PrimitiveArray > v8::PrimitiveArray::New (Isolate * isolate, int length) [static]
Definition at line 2058 of file api.cc.
                                                                         {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  Utils::ApiCheck(length >= 0, "v8::PrimitiveArray::New",
                  "length must be equal or greater than zero");
  i::DirectHandle<i::FixedArray> array =
      i_isolate->factory()->NewFixedArray(length);
  return ToApiHandle<PrimitiveArray>(array);
}
References v8::Utils::ApiCheck(), v8::internal::Isolate::factory(), v8::internal::length, and v8::internal::FactoryBase< Impl >::NewFixedArray().
Referenced by v8_inspector::V8Console::CommandLineAPIScope::CommandLineAPIScope(), v8::anonymous_namespace{d8.cc}::CreateScriptOrigin(), and v8::Shell::ReadLines().
Set()
void v8::PrimitiveArray::Set (Isolate * isolate, int index, Local< Primitive > item)
Definition at line 2072 of file api.cc.
                                                {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  auto array = Utils::OpenDirectHandle(this);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  Utils::ApiCheck(index >= 0 && index < array->length(),
                  "v8::PrimitiveArray::Set",
                  "index must be greater than or equal to 0 and less than the "
                  "array length");
  array->set(index, *Utils::OpenDirectHandle(*item));
}
References v8::Utils::ApiCheck(), v8::internal::index, v8::internal::length, and v8::Utils::OpenDirectHandle().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-primitive.h
/mnt/V8SourceCode/src/api/api.cc