v8::internal::wasm::ArrayTypeBase Class Reference
#include <struct-types.h>
Public Member Functions
constexpr ArrayTypeBase (bool mutability)
bool mutability () const
Protected Attributes
const bool mutability_
Detailed Description
Definition at line 314 of file struct-types.h.
Constructor & Destructor Documentation
ArrayTypeBase()
constexpr v8::internal::wasm::ArrayTypeBase::ArrayTypeBase (bool mutability) [inline], [explicit], [constexpr]
Definition at line 316 of file struct-types.h.
: mutability_(mutability) {}
Member Function Documentation
mutability()
bool v8::internal::wasm::ArrayTypeBase::mutability () const [inline]
Definition at line 318 of file struct-types.h.
{ return mutability_; }
References mutability_.
Referenced by v8::internal::wasm::TypeCanonicalizer::CanonicalHashing::Add(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_init_data(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_init_elem(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_set(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeAtomicOpcode(), v8::internal::wasm::TypeCanonicalizer::CanonicalEquality::EqualArrayType(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PopPackedArray(), v8::internal::wasm::ModuleDisassembler::PrintTypeDefinition(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::ValidArraySubtypeDefinition(), and v8::internal::wasm::WasmModuleBuilder::WriteTo().
Member Data Documentation
mutability_
const bool v8::internal::wasm::ArrayTypeBase::mutability_ [protected]
Definition at line 321 of file struct-types.h.
Referenced by mutability(), v8::internal::wasm::ArrayType::operator==(), and v8::internal::wasm::CanonicalArrayType::operator==().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/struct-types.h