v8::CFunctionInfo Class Reference
#include <v8-fast-api-calls.h>
Public Types
enum class Int64Representation : uint8_t { kNumber = 0
, kBigInt = 1
 }
Public Member Functions
CFunctionInfo (const CTypeInfo &return_info, unsigned int arg_count, const CTypeInfo *arg_info, Int64Representation repr=Int64Representation::kNumber)
const CTypeInfo & ReturnInfo () const
unsigned int ArgumentCount () const
Int64Representation GetInt64Representation () const
const CTypeInfo & ArgumentInfo (unsigned int index) const
bool HasOptions () const
Private Attributes
const CTypeInfo return_info_
const Int64Representation repr_
const unsigned int arg_count_
const CTypeInfo * arg_info_
Detailed Description
Definition at line 339 of file v8-fast-api-calls.h.
Member Enumeration Documentation
Int64Representation
enum v8::CFunctionInfo::Int64Representation : uint8_t [strong]
Enumerator
kNumber
kBigInt
Definition at line 341 of file v8-fast-api-calls.h.
                                 : uint8_t {
    kNumber = 0, // Use numbers to represent 64 bit integers.
    kBigInt = 1, // Use BigInts to represent 64 bit integers.
  };
Constructor & Destructor Documentation
CFunctionInfo()
v8::CFunctionInfo::CFunctionInfo (const CTypeInfo & return_info, unsigned int arg_count, const CTypeInfo * arg_info, Int64Representation repr = Int64Representation::kNumber)
Definition at line 11877 of file api.cc.
    : return_info_(return_info),
      repr_(repr),
      arg_count_(arg_count),
      arg_info_(arg_info) {
  DCHECK(repr == Int64Representation::kNumber ||
         repr == Int64Representation::kBigInt);
  if (arg_count_ > 0) {
    for (unsigned int i = 0; i < arg_count_ - 1; ++i) {
      DCHECK(arg_info_[i].GetType() != CTypeInfo::kCallbackOptionsType);
    }
  }
}
References arg_count_, arg_info_, DCHECK, v8::internal::anonymous_namespace{json-stringifier.cc}::i, kBigInt, v8::CTypeInfo::kCallbackOptionsType, and kNumber.
Member Function Documentation
ArgumentCount()
unsigned int v8::CFunctionInfo::ArgumentCount () const [inline]
Definition at line 359 of file v8-fast-api-calls.h.
                                     {
    return HasOptions() ? arg_count_ - 1 : arg_count_;
  }
Referenced by ArgumentInfo(), v8::internal::compiler::fast_api_call::FastApiCallBuilder::Build(), v8::internal::compiler::fast_api_call::CanOptimizeFastSignature(), v8::internal::compiler::SimplifiedOperatorBuilder::FastApiCall(), v8::internal::compiler::FastApiCallNode::FastCallArgumentCount(), v8::internal::compiler::fast_api_call::GetFastApiCallTarget(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::GetFunctionSigForFastApiImport(), v8::internal::compiler::turboshaft::FastApiCallOp::inputs_rep(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::IsSupportedWasmFastApiFunction(), v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall(), and v8::internal::compiler::RepresentationSelector::VisitFastApiCall().
ArgumentInfo()
const CTypeInfo & v8::CFunctionInfo::ArgumentInfo (unsigned int index) const
Definition at line 11893 of file api.cc.
                                                                     {
  DCHECK_LT(index, ArgumentCount());
  return arg_info_[index];
}
References arg_info_, ArgumentCount(), DCHECK_LT, and v8::internal::index.
Referenced by v8::internal::compiler::turboshaft::FastApiCallOp::argument_representation(), v8::internal::compiler::fast_api_call::FastApiCallBuilder::Build(), v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildJSFastApiCallWrapper(), v8::internal::compiler::fast_api_call::CanOptimizeFastSignature(), v8::internal::compiler::fast_api_call::GetFastApiCallTarget(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::GetFunctionSigForFastApiImport(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::IsSupportedWasmFastApiFunction(), and v8::internal::compiler::RepresentationSelector::VisitFastApiCall().
GetInt64Representation()
Int64Representation v8::CFunctionInfo::GetInt64Representation () const [inline]
Definition at line 363 of file v8-fast-api-calls.h.
{ return repr_; }
Referenced by v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::ConvertReturnValue(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::DefaultReturnValue(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::IsSupportedWasmFastApiFunction(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), and v8::internal::compiler::RepresentationSelector::VisitFastApiCall().
HasOptions()
bool v8::CFunctionInfo::HasOptions () const [inline]
Definition at line 371 of file v8-fast-api-calls.h.
                          {
    // The options arg is always the last one.
    return arg_count_ > 0 && arg_info_[arg_count_ - 1].GetType() ==
                                 CTypeInfo::kCallbackOptionsType;
  }
References v8::CTypeInfo::kCallbackOptionsType.
Referenced by v8::internal::compiler::fast_api_call::FastApiCallBuilder::Build().
ReturnInfo()
const CTypeInfo& v8::CFunctionInfo::ReturnInfo () const [inline]
Definition at line 355 of file v8-fast-api-calls.h.
{ return return_info_; }
Referenced by v8::internal::compiler::fast_api_call::FastApiCallBuilder::Build(), v8::internal::compiler::fast_api_call::CanOptimizeFastSignature(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::ConvertReturnValue(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::DefaultReturnValue(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::GetFunctionSigForFastApiImport(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::IsSupportedWasmFastApiFunction(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall(), and v8::internal::compiler::RepresentationSelector::VisitFastApiCall().
Member Data Documentation
arg_count_
const unsigned int v8::CFunctionInfo::arg_count_ [private]
Definition at line 380 of file v8-fast-api-calls.h.
Referenced by CFunctionInfo().
arg_info_
const CTypeInfo* v8::CFunctionInfo::arg_info_ [private]
Definition at line 381 of file v8-fast-api-calls.h.
Referenced by ArgumentInfo(), and CFunctionInfo().
repr_
const Int64Representation v8::CFunctionInfo::repr_ [private]
Definition at line 379 of file v8-fast-api-calls.h.
return_info_
const CTypeInfo v8::CFunctionInfo::return_info_ [private]
Definition at line 378 of file v8-fast-api-calls.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-fast-api-calls.h
/mnt/V8SourceCode/src/api/api.cc