v8::internal::torque::BuiltinPointerType Class Reference
#include <types.h>
Public Member Functions
std::string ToExplicitString () const override
std::string GetGeneratedTypeNameImpl () const override
std::string GetGeneratedTNodeTypeNameImpl () const override
const TypeVector & parameter_types () const
const Type * return_type () const
bool operator== (const BuiltinPointerType &other) const
size_t function_pointer_type_id () const
std::vector< TypeChecker > GetTypeCheckers () const override
bool HasContextParameter () const
Private Member Functions
BuiltinPointerType (const Type *parent, TypeVector parameter_types, const Type *return_type, size_t function_pointer_type_id)
std::string SimpleNameImpl () const override
Private Attributes
const TypeVector parameter_types_
const Type *const return_type_
const size_t function_pointer_type_id_
Friends
class TypeOracle
size_t hash_value (const BuiltinPointerType &p)
Additional Inherited Members
Detailed Description
Definition at line 334 of file types.h.
Constructor & Destructor Documentation
BuiltinPointerType()
v8::internal::torque::BuiltinPointerType::BuiltinPointerType (const Type * parent, TypeVector parameter_types, const Type * return_type, size_t function_pointer_type_id) [inline], [private]
Definition at line 369 of file types.h.
      : Type(Kind::kBuiltinPointerType, parent),
        parameter_types_(parameter_types),
        return_type_(return_type),
        function_pointer_type_id_(function_pointer_type_id) {}
Member Function Documentation
function_pointer_type_id()
size_t v8::internal::torque::BuiltinPointerType::function_pointer_type_id () const [inline]
Definition at line 359 of file types.h.
{ return function_pointer_type_id_; }
GetGeneratedTNodeTypeNameImpl()
std::string v8::internal::torque::BuiltinPointerType::GetGeneratedTNodeTypeNameImpl () const [inline], [override], [virtual]
Implements v8::internal::torque::Type.
Definition at line 341 of file types.h.
                                                           {
    return parent()->GetGeneratedTNodeTypeName();
  }
GetGeneratedTypeNameImpl()
std::string v8::internal::torque::BuiltinPointerType::GetGeneratedTypeNameImpl () const [inline], [override], [virtual]
Implements v8::internal::torque::Type.
Definition at line 338 of file types.h.
                                                      {
    return parent()->GetGeneratedTypeName();
  }
GetTypeCheckers()
std::vector<TypeChecker> v8::internal::torque::BuiltinPointerType::GetTypeCheckers () const [inline], [override], [virtual]
Reimplemented from v8::internal::torque::Type.
Definition at line 361 of file types.h.
                                                          {
    return {{"Smi", ""}};
  }
HasContextParameter()
bool v8::internal::torque::BuiltinPointerType::HasContextParameter () const
Definition at line 1165 of file types.cc.
                                                   {
  return FirstTypeIsContext(parameter_types());
}
References v8::internal::torque::anonymous_namespace{types.cc}::FirstTypeIsContext(), and parameter_types().
operator==()
bool v8::internal::torque::BuiltinPointerType::operator== (const BuiltinPointerType & other) const [inline]
Definition at line 355 of file types.h.
                                                         {
    return parameter_types_ == other.parameter_types_ &&
           return_type_ == other.return_type_;
  }
References parameter_types_, and return_type_.
parameter_types()
const TypeVector& v8::internal::torque::BuiltinPointerType::parameter_types () const [inline]
Definition at line 345 of file types.h.
{ return parameter_types_; }
Referenced by HasContextParameter().
return_type()
const Type* v8::internal::torque::BuiltinPointerType::return_type () const [inline]
Definition at line 346 of file types.h.
{ return return_type_; }
Referenced by v8::internal::torque::CallBuiltinPointerInstruction::GetValueDefinitionCount().
SimpleNameImpl()
std::string v8::internal::torque::BuiltinPointerType::SimpleNameImpl () const [override], [private], [virtual]
Implements v8::internal::torque::Type.
Definition at line 246 of file types.cc.
                                                   {
  std::stringstream result;
  result << "BuiltinPointer";
  for (const Type* t : parameter_types_) {
    result << "_" << t->SimpleName();
  }
  result << "_" << return_type_->SimpleName();
  return result.str();
}
References v8::base::internal::result.
ToExplicitString()
std::string v8::internal::torque::BuiltinPointerType::ToExplicitString () const [override], [virtual]
Implements v8::internal::torque::Type.
Definition at line 238 of file types.cc.
                                                     {
  std::stringstream result;
  result << "builtin (";
  PrintCommaSeparatedList(result, parameter_types_);
  result << ") => " << *return_type_;
  return result.str();
}
References v8::internal::torque::PrintCommaSeparatedList(), and v8::base::internal::result.
Friends And Related Function Documentation
hash_value
size_t hash_value (const BuiltinPointerType & p) [friend]
Definition at line 348 of file types.h.
                                                        {
    size_t result = base::hash_value(p.return_type_);
    for (const Type* parameter : p.parameter_types_) {
      result = base::hash_combine(result, parameter);
    }
    return result;
  }
TypeOracle
friend class TypeOracle [friend]
Definition at line 368 of file types.h.
Member Data Documentation
function_pointer_type_id_
const size_t v8::internal::torque::BuiltinPointerType::function_pointer_type_id_ [private]
Definition at line 379 of file types.h.
parameter_types_
const TypeVector v8::internal::torque::BuiltinPointerType::parameter_types_ [private]
Definition at line 377 of file types.h.
Referenced by operator==().
return_type_
const Type* const v8::internal::torque::BuiltinPointerType::return_type_ [private]
Definition at line 378 of file types.h.
Referenced by operator==().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/torque/types.h
/mnt/V8SourceCode/src/torque/types.cc