v8::internal::ConstantPoolPointerForwarder Class Reference
Public Member Functions
ConstantPoolPointerForwarder (PtrComprCageBase cage_base, LocalHeap *local_heap, DirectHandle< Script > old_script)
void AddBytecodeArray (Tagged< BytecodeArray > bytecode_array)
void RecordScopeInfos (Tagged< MaybeObject > maybe_old_info)
void RecordScopeInfos (Tagged< HeapObject > info)
void IterateAndForwardPointers ()
void set_has_shared_function_info_to_forward ()
bool HasAnythingToForward () const
bool InstallOwnScopeInfo (Tagged< SharedFunctionInfo > sfi)
void UpdateScopeInfo (Tagged< SharedFunctionInfo > sfi)
Private Member Functions
void VerifyScopeInfo (Tagged< ScopeInfo > scope_info, Tagged< ScopeInfo > replacement)
template<typename TArray >
void IterateConstantPoolEntry (Tagged< TArray > constant_pool, int i)
template<typename TArray >
void VisitSharedFunctionInfo (Tagged< TArray > constant_pool, int i, Tagged< SharedFunctionInfo > sfi)
template<typename TArray >
void VisitScopeInfo (Tagged< TArray > constant_pool, int i, Tagged< ScopeInfo > scope_info)
void IterateConstantPool (Tagged< TrustedFixedArray > constant_pool)
void IterateConstantPoolNestedArray (Tagged< FixedArray > nested_array)
Private Attributes
PtrComprCageBase cage_base_
LocalHeap * local_heap_
DirectHandle< Script > old_script_
std::vector< IndirectHandle< BytecodeArray > > bytecode_arrays_to_update_
bool has_shared_function_info_to_forward_ = false
std::unordered_map< int, IndirectHandle< ScopeInfo > > scope_infos_to_update_
Detailed Description
Definition at line 2077 of file compiler.cc.
Constructor & Destructor Documentation
ConstantPoolPointerForwarder()
v8::internal::ConstantPoolPointerForwarder::ConstantPoolPointerForwarder (PtrComprCageBase cage_base, LocalHeap * local_heap, DirectHandle< Script > old_script) [inline], [explicit]
Definition at line 2079 of file compiler.cc.
      : cage_base_(cage_base),
        local_heap_(local_heap),
        old_script_(old_script) {}
Member Function Documentation
AddBytecodeArray()
void v8::internal::ConstantPoolPointerForwarder::AddBytecodeArray (Tagged< BytecodeArray > bytecode_array) [inline]
Definition at line 2086 of file compiler.cc.
                                                              {
    CHECK(IsBytecodeArray(bytecode_array));
    bytecode_arrays_to_update_.emplace_back(bytecode_array, local_heap_);
  }
References bytecode_arrays_to_update_, CHECK, and local_heap_.
Referenced by v8::internal::BackgroundMergeTask::BeginMergeInBackground(), and v8::internal::BackgroundMergeTask::CompleteMergeInForeground().
HasAnythingToForward()
bool v8::internal::ConstantPoolPointerForwarder::HasAnythingToForward () const [inline]
Definition at line 2149 of file compiler.cc.
                                    {
    return has_shared_function_info_to_forward_ ||
           !scope_infos_to_update_.empty();
  }
References has_shared_function_info_to_forward_, and scope_infos_to_update_.
Referenced by v8::internal::BackgroundMergeTask::BeginMergeInBackground(), v8::internal::BackgroundMergeTask::CompleteMergeInForeground(), and IterateAndForwardPointers().
InstallOwnScopeInfo()
bool v8::internal::ConstantPoolPointerForwarder::InstallOwnScopeInfo (Tagged< SharedFunctionInfo > sfi) [inline]
Definition at line 2160 of file compiler.cc.
                                                           {
    if (!v8_flags.reuse_scope_infos) return false;
    auto it = scope_infos_to_update_.find(sfi->UniqueIdInScript());
    if (it == scope_infos_to_update_.end()) return false;
    sfi->SetScopeInfo(*it->second);
    return true;
  }
References scope_infos_to_update_, and v8::internal::v8_flags.
Referenced by v8::internal::BackgroundMergeTask::BeginMergeInBackground(), v8::internal::BackgroundMergeTask::CompleteMergeInForeground(), and UpdateScopeInfo().
IterateAndForwardPointers()
void v8::internal::ConstantPoolPointerForwarder::IterateAndForwardPointers () [inline]
Definition at line 2136 of file compiler.cc.
                                   {
    DCHECK(HasAnythingToForward());
    for (DirectHandle<BytecodeArray> entry : bytecode_arrays_to_update_) {
      local_heap_->Safepoint();
      DisallowGarbageCollection no_gc;
      IterateConstantPool(entry->constant_pool());
    }
  }
References bytecode_arrays_to_update_, v8::internal::DCHECK(), HasAnythingToForward(), IterateConstantPool(), local_heap_, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::LocalHeap::Safepoint().
Referenced by v8::internal::BackgroundMergeTask::BeginMergeInBackground(), and v8::internal::BackgroundMergeTask::CompleteMergeInForeground().
IterateConstantPool()
void v8::internal::ConstantPoolPointerForwarder::IterateConstantPool (Tagged< TrustedFixedArray > constant_pool) [inline], [private]
Definition at line 2271 of file compiler.cc.
                                                                    {
    for (int i = 0, length = constant_pool->length(); i < length; ++i) {
      IterateConstantPoolEntry(constant_pool, i);
    }
  }
References v8::internal::constant_pool, IterateConstantPoolEntry(), and v8::internal::length.
Referenced by IterateAndForwardPointers().
IterateConstantPoolEntry()
template<typename TArray >
void v8::internal::ConstantPoolPointerForwarder::IterateConstantPoolEntry (Tagged< TArray > constant_pool, int i) [inline], [private]
Definition at line 2217 of file compiler.cc.
                                                                     {
    Tagged<Object> obj = constant_pool->get(i);
    if (IsSmi(obj)) return;
    Tagged<HeapObject> heap_obj = Cast<HeapObject>(obj);
    if (IsFixedArray(heap_obj, cage_base_)) {
      // Constant pools can have nested fixed arrays, but such relationships
      // are acyclic and never more than a few layers deep, so recursion is
      // fine here.
      IterateConstantPoolNestedArray(Cast<FixedArray>(heap_obj));
    } else if (has_shared_function_info_to_forward_ &&
               IsSharedFunctionInfo(heap_obj, cage_base_)) {
      VisitSharedFunctionInfo(constant_pool, i,
                              Cast<SharedFunctionInfo>(heap_obj));
    } else if (!scope_infos_to_update_.empty() &&
               IsScopeInfo(heap_obj, cage_base_)) {
      VisitScopeInfo(constant_pool, i, Cast<ScopeInfo>(heap_obj));
    }
  }
References cage_base_, v8::internal::constant_pool, has_shared_function_info_to_forward_, v8::internal::IsSmi(), IterateConstantPoolNestedArray(), scope_infos_to_update_, VisitScopeInfo(), and VisitSharedFunctionInfo().
Referenced by IterateConstantPool(), and IterateConstantPoolNestedArray().
IterateConstantPoolNestedArray()
void v8::internal::ConstantPoolPointerForwarder::IterateConstantPoolNestedArray (Tagged< FixedArray > nested_array) [inline], [private]
Definition at line 2277 of file compiler.cc.
                                                                       {
    for (int i = 0, length = nested_array->length(); i < length; ++i) {
      IterateConstantPoolEntry(nested_array, i);
    }
  }
References IterateConstantPoolEntry(), and v8::internal::length.
Referenced by IterateConstantPoolEntry().
RecordScopeInfos() [1/2]
void v8::internal::ConstantPoolPointerForwarder::RecordScopeInfos (Tagged< HeapObject > info) [inline]
Definition at line 2097 of file compiler.cc.
                                                 {
    if (!v8_flags.reuse_scope_infos) return;
    Tagged<ScopeInfo> scope_info;
    if (Is<SharedFunctionInfo>(info)) {
      Tagged<SharedFunctionInfo> old_sfi = Cast<SharedFunctionInfo>(info);
      // Also record context-having own scope infos for SFIs.
      if (!old_sfi->scope_info()->IsEmpty() &&
          old_sfi->scope_info()->HasContext()) {
        scope_info = old_sfi->scope_info();
      } else if (old_sfi->HasOuterScopeInfo()) {
        scope_info = old_sfi->GetOuterScopeInfo();
      } else {
        return;
      }
    } else {
      scope_info = Cast<ScopeInfo>(info);
    }
    while (true) {
      auto it = scope_infos_to_update_.find(scope_info->UniqueIdInScript());
      if (it != scope_infos_to_update_.end()) {
        // Once we find an already recorded scope info, it need to match the one
        // on the chain.
        if (V8_UNLIKELY(*it->second != scope_info)) {
          info->Print();
          (*it->second)->Print();
          scope_info->Print();
          UNREACHABLE();
        }
        return;
      }
      scope_infos_to_update_[scope_info->UniqueIdInScript()] =
          handle(scope_info, local_heap_);
      if (!scope_info->HasOuterScopeInfo()) break;
      scope_info = scope_info->OuterScopeInfo();
    }
  }
References v8::internal::handle(), local_heap_, v8::internal::Print(), scope_infos_to_update_, v8::internal::UNREACHABLE(), v8::internal::v8_flags, and V8_UNLIKELY.
RecordScopeInfos() [2/2]
void v8::internal::ConstantPoolPointerForwarder::RecordScopeInfos (Tagged< MaybeObject > maybe_old_info) [inline]
Definition at line 2091 of file compiler.cc.
                                                            {
    RecordScopeInfos(maybe_old_info.GetHeapObjectAssumeWeak());
  }
References v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectAssumeWeak().
Referenced by v8::internal::BackgroundMergeTask::BeginMergeInBackground(), and v8::internal::BackgroundMergeTask::CompleteMergeInForeground().
set_has_shared_function_info_to_forward()
void v8::internal::ConstantPoolPointerForwarder::set_has_shared_function_info_to_forward () [inline]
Definition at line 2145 of file compiler.cc.
                                                 {
    has_shared_function_info_to_forward_ = true;
  }
References has_shared_function_info_to_forward_.
Referenced by v8::internal::BackgroundMergeTask::BeginMergeInBackground(), and v8::internal::BackgroundMergeTask::CompleteMergeInForeground().
UpdateScopeInfo()
void v8::internal::ConstantPoolPointerForwarder::UpdateScopeInfo (Tagged< SharedFunctionInfo > sfi) [inline]
Definition at line 2173 of file compiler.cc.
                                                       {
    if (!v8_flags.reuse_scope_infos) return;
    if (InstallOwnScopeInfo(sfi)) return;
    if (!sfi->HasOuterScopeInfo()) return;
    Tagged<ScopeInfo> parent =
        sfi->scope_info()->IsEmpty() ? Tagged<ScopeInfo>() : sfi->scope_info();
    Tagged<ScopeInfo> outer_info = sfi->GetOuterScopeInfo();
    auto it = scope_infos_to_update_.find(outer_info->UniqueIdInScript());
    while (it == scope_infos_to_update_.end()) {
      if (!outer_info->HasOuterScopeInfo()) return;
      parent = outer_info;
      outer_info = outer_info->OuterScopeInfo();
      it = scope_infos_to_update_.find(outer_info->UniqueIdInScript());
    }
    if (outer_info == *it->second) return;
    VerifyScopeInfo(outer_info, *it->second);
    if (parent.is_null()) {
      sfi->set_raw_outer_scope_info_or_feedback_metadata(*it->second);
    } else {
      parent->set_outer_scope_info(*it->second);
    }
  }
References InstallOwnScopeInfo(), v8::internal::Tagged< HeapObject >::is_null(), scope_infos_to_update_, v8::internal::v8_flags, and VerifyScopeInfo().
Referenced by v8::internal::BackgroundMergeTask::BeginMergeInBackground(), and v8::internal::BackgroundMergeTask::CompleteMergeInForeground().
VerifyScopeInfo()
void v8::internal::ConstantPoolPointerForwarder::VerifyScopeInfo (Tagged< ScopeInfo > scope_info, Tagged< ScopeInfo > replacement) [inline], [private]
Definition at line 2201 of file compiler.cc.
                                                      {
    if (replacement->scope_type() == SCRIPT_SCOPE ||
        replacement->scope_type() == MODULE_SCOPE) {
      // During streaming compilation we might not know whether we want to parse
      // this script as a classic script or module, and do the wrong thing. In
      // case compilation succeeded, we'll only reject the result later.
      CHECK(scope_info->scope_type() == SCRIPT_SCOPE ||
            scope_info->scope_type() == MODULE_SCOPE);
    } else {
      CHECK_EQ(replacement->EndPosition(), scope_info->EndPosition());
      CHECK_EQ(replacement->scope_type(), scope_info->scope_type());
      CHECK_EQ(replacement->ContextLength(), scope_info->ContextLength());
    }
  }
References CHECK, CHECK_EQ, v8::internal::MODULE_SCOPE, and v8::internal::SCRIPT_SCOPE.
Referenced by UpdateScopeInfo(), and VisitScopeInfo().
VisitScopeInfo()
template<typename TArray >
void v8::internal::ConstantPoolPointerForwarder::VisitScopeInfo (Tagged< TArray > constant_pool, int i, Tagged< ScopeInfo > scope_info) [inline], [private]
Definition at line 2248 of file compiler.cc.
                                                    {
    auto it = scope_infos_to_update_.find(scope_info->UniqueIdInScript());
    // Try to replace the scope info itself with an already existing version.
    if (it != scope_infos_to_update_.end()) {
      if (scope_info != *it->second) {
        VerifyScopeInfo(scope_info, *it->second);
        constant_pool->set(i, *it->second);
      }
    } else if (scope_info->HasOuterScopeInfo()) {
      // If we didn't find a match, but we have an outer scope info, try to
      // replace the outer scope info with an already existing outer scope
      // info. We only need to look at the direct outer scope info since we'll
      // process all scope infos that are created by this compilation task.
      Tagged<ScopeInfo> outer = scope_info->OuterScopeInfo();
      it = scope_infos_to_update_.find(outer->UniqueIdInScript());
      if (it != scope_infos_to_update_.end() && outer != *it->second) {
        VerifyScopeInfo(outer, *it->second);
        scope_info->set_outer_scope_info(*it->second);
      }
    }
  }
References v8::internal::constant_pool, scope_infos_to_update_, and VerifyScopeInfo().
Referenced by IterateConstantPoolEntry().
VisitSharedFunctionInfo()
template<typename TArray >
void v8::internal::ConstantPoolPointerForwarder::VisitSharedFunctionInfo (Tagged< TArray > constant_pool, int i, Tagged< SharedFunctionInfo > sfi) [inline], [private]
Definition at line 2237 of file compiler.cc.
                                                               {
    Tagged<MaybeObject> maybe_old_sfi =
        old_script_->infos()->get(sfi->function_literal_id(kRelaxedLoad));
    if (maybe_old_sfi.IsWeak()) {
      constant_pool->set(
          i, Cast<SharedFunctionInfo>(maybe_old_sfi.GetHeapObjectAssumeWeak()));
    }
  }
References v8::internal::constant_pool, v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectAssumeWeak(), v8::internal::TaggedImpl< kRefType, StorageType >::IsWeak(), v8::kRelaxedLoad, and old_script_.
Referenced by IterateConstantPoolEntry().
Member Data Documentation
bytecode_arrays_to_update_
std::vector<IndirectHandle<BytecodeArray> > v8::internal::ConstantPoolPointerForwarder::bytecode_arrays_to_update_ [private]
Definition at line 2286 of file compiler.cc.
Referenced by AddBytecodeArray(), and IterateAndForwardPointers().
cage_base_
PtrComprCageBase v8::internal::ConstantPoolPointerForwarder::cage_base_ [private]
Definition at line 2283 of file compiler.cc.
Referenced by IterateConstantPoolEntry().
has_shared_function_info_to_forward_
bool v8::internal::ConstantPoolPointerForwarder::has_shared_function_info_to_forward_ = false [private]
Definition at line 2289 of file compiler.cc.
Referenced by HasAnythingToForward(), IterateConstantPoolEntry(), and set_has_shared_function_info_to_forward().
local_heap_
LocalHeap* v8::internal::ConstantPoolPointerForwarder::local_heap_ [private]
Definition at line 2284 of file compiler.cc.
Referenced by AddBytecodeArray(), IterateAndForwardPointers(), and RecordScopeInfos().
old_script_
DirectHandle<Script> v8::internal::ConstantPoolPointerForwarder::old_script_ [private]
Definition at line 2285 of file compiler.cc.
Referenced by VisitSharedFunctionInfo().
scope_infos_to_update_
std::unordered_map<int, IndirectHandle<ScopeInfo> > v8::internal::ConstantPoolPointerForwarder::scope_infos_to_update_ [private]
Definition at line 2290 of file compiler.cc.
Referenced by HasAnythingToForward(), InstallOwnScopeInfo(), IterateConstantPoolEntry(), RecordScopeInfos(), UpdateScopeInfo(), and VisitScopeInfo().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/codegen/compiler.cc