v8::base::EnumSet< E, T > Class Template Reference
#include <enum-set.h>
Public Types
using StorageType = T
Public Member Functions
constexpr EnumSet ()=default
constexpr EnumSet (std::initializer_list< E > init)
constexpr bool empty () const
constexpr bool contains (E element) const
constexpr bool contains_all (EnumSet set) const
constexpr bool contains_any (EnumSet set) const
constexpr bool contains_only (E element) const
constexpr bool is_subset_of (EnumSet set) const
constexpr void Add (E element)
constexpr void Add (EnumSet set)
constexpr void Remove (E element)
constexpr void Remove (EnumSet set)
constexpr void RemoveAll ()
constexpr void Intersect (EnumSet set)
constexpr T ToIntegral () const
constexpr EnumSet operator~ () const
constexpr bool operator== (EnumSet set) const
constexpr EnumSet operator| (EnumSet set) const
constexpr EnumSet operator& (EnumSet set) const
constexpr EnumSet operator- (EnumSet set) const
EnumSet & operator|= (EnumSet set)
EnumSet & operator&= (EnumSet set)
EnumSet & operator-= (EnumSet set)
constexpr EnumSet operator| (E element) const
constexpr EnumSet operator& (E element) const
constexpr EnumSet operator- (E element) const
EnumSet & operator|= (E element)
EnumSet & operator&= (E element)
EnumSet & operator-= (E element)
Static Public Member Functions
static constexpr EnumSet FromIntegral (T bits)
Private Member Functions
constexpr EnumSet (T bits)
Static Private Member Functions
static constexpr T Mask (E element)
Private Attributes
T bits_ = 0
Detailed Description
template<class E, class T = int>
class v8::base::EnumSet< E, T >
Definition at line 20 of file enum-set.h.
Member Typedef Documentation
StorageType
template<class E , class T = int>
using v8::base::EnumSet< E, T >::StorageType = T
Definition at line 24 of file enum-set.h.
Constructor & Destructor Documentation
EnumSet() [1/3]
template<class E , class T = int>
constexpr v8::base::EnumSet< E, T >::EnumSet () [constexpr], [default]
Referenced by v8::base::EnumSet< E, T >::operator&(), v8::base::EnumSet< E, T >::operator-(), v8::base::EnumSet< E, T >::operator|(), and v8::base::EnumSet< E, T >::operator~().
EnumSet() [2/3]
template<class E , class T = int>
constexpr v8::base::EnumSet< E, T >::EnumSet (std::initializer_list< E > init) [inline], [constexpr]
Definition at line 28 of file enum-set.h.
                                                 {
    T bits = 0;
    for (E e : init) bits |= Mask(e);
    bits_ = bits;
  }
References v8::base::EnumSet< E, T >::bits_, and v8::base::EnumSet< E, T >::Mask().
EnumSet() [3/3]
template<class E , class T = int>
constexpr v8::base::EnumSet< E, T >::EnumSet (T bits) [inline], [explicit], [constexpr], [private]
Definition at line 93 of file enum-set.h.
: bits_(bits) {}
Member Function Documentation
Add() [1/2]
template<class E , class T = int>
constexpr void v8::base::EnumSet< E, T >::Add (E element) [inline], [constexpr]
Definition at line 50 of file enum-set.h.
{ bits_ |= Mask(element); }
References v8::base::EnumSet< E, T >::bits_, and v8::base::EnumSet< E, T >::Mask().
Referenced by v8::internal::wasm::CompileTimeImports::Add(), v8::internal::compiler::InstructionSelector::AlignmentRequirements(), v8::internal::Debug::Break(), v8::internal::ScavengerCollector::CollectGarbage(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ExecuteCompilationUnits(), v8::internal::wasm::WasmEnabledFeatures::FromContext(), v8::internal::wasm::WasmEnabledFeatures::FromFlags(), v8::internal::anonymous_namespace{mark-compact.cc}::GetCodeFlushMode(), v8_inspector::V8Debugger::handleProgramBreak(), v8::internal::wasm::TurboshaftGraphBuildingInterface::HandleWellKnownImport(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::InitializeCompilationProgressAfterDeserialization(), v8::internal::Debug::OnDebugBreak(), v8::internal::maglev::MaglevPhiRepresentationSelector::ProcessPhi(), v8::internal::maglev::Phi::RecordUseReprHint(), v8::internal::compiler::GapResolver::Resolve(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::TriggerOutstandingCallbacks(), and v8::internal::wasm::AsmJsParser::ValidateModuleVarStdlib().
Add() [2/2]
template<class E , class T = int>
constexpr void v8::base::EnumSet< E, T >::Add (EnumSet< E, T > set) [inline], [constexpr]
Definition at line 51 of file enum-set.h.
{ bits_ |= set.bits_; }
References v8::base::EnumSet< E, T >::bits_.
contains()
template<class E , class T = int>
constexpr bool v8::base::EnumSet< E, T >::contains (E element) const [inline], [constexpr]
Definition at line 35 of file enum-set.h.
                                           {
    return (bits_ & Mask(element)) != 0;
  }
References v8::base::EnumSet< E, T >::bits_, and v8::base::EnumSet< E, T >::Mask().
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::AddCallback(), v8::internal::anonymous_namespace{asm-js.cc}::AreStdlibMembersValid(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::CancelCompilation(), v8::internal::compiler::turboshaft::LoopFinder::CollectLoopInfo(), v8::internal::wasm::CompileTimeImports::contains(), v8_inspector::V8DebuggerAgentImpl::didPause(), v8::internal::Debug::HandleDebugBreak(), v8_inspector::V8Debugger::handleProgramBreak(), v8::internal::wasm::CompileTimeImports::has_string_constants(), v8::internal::compiler::MachineOperatorBuilder::AlignmentRequirements::IsUnalignedSupported(), v8::internal::Heap::IterateRoots(), v8::internal::Heap::IterateWeakRoots(), v8::internal::PerThreadAssertScope< kAllow, kTypes >::PerThreadAssertScope(), v8::internal::maglev::MaglevPhiRepresentationSelector::ProcessPhi(), v8::internal::wasm::PublishDetectedFeatures(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::TriggerCallbacks().
contains_all()
template<class E , class T = int>
constexpr bool v8::base::EnumSet< E, T >::contains_all (EnumSet< E, T > set) const [inline], [constexpr]
Definition at line 38 of file enum-set.h.
                                                 {
    return (bits_ & set.bits_) == set.bits_;
  }
References v8::base::EnumSet< E, T >::bits_.
Referenced by v8::internal::PerThreadAssertScope< kAllow, kTypes >::IsAllowed(), and v8::internal::wasm::AsyncStreamingProcessor::OnFinishedStream().
contains_any()
template<class E , class T = int>
constexpr bool v8::base::EnumSet< E, T >::contains_any (EnumSet< E, T > set) const [inline], [constexpr]
Definition at line 41 of file enum-set.h.
                                                 {
    return (bits_ & set.bits_) != 0;
  }
References v8::base::EnumSet< E, T >::bits_.
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::AddCallback(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::CheckBailoutAllowed(), v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::hitBreakReasonEncodedAsOther(), and v8::internal::maglev::MaglevPhiRepresentationSelector::ProcessPhi().
contains_only()
template<class E , class T = int>
constexpr bool v8::base::EnumSet< E, T >::contains_only (E element) const [inline], [constexpr]
Definition at line 44 of file enum-set.h.
                                                {
    return bits_ == Mask(element);
  }
References v8::base::EnumSet< E, T >::bits_, and v8::base::EnumSet< E, T >::Mask().
Referenced by v8::internal::maglev::MaglevPhiRepresentationSelector::ProcessPhi().
empty()
template<class E , class T = int>
constexpr bool v8::base::EnumSet< E, T >::empty () const [inline], [constexpr]
Definition at line 34 of file enum-set.h.
{ return bits_ == 0; }
References v8::base::EnumSet< E, T >::bits_.
Referenced by v8::internal::anonymous_namespace{asm-js.cc}::AreStdlibMembersValid(), v8::internal::wasm::CompileTimeImports::empty(), v8::internal::AsmJs::InstantiateAsmWasm(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::OnCompilationStopped(), v8::base::operator<<(), v8::internal::maglev::MaglevPhiRepresentationSelector::ProcessPhi(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::TriggerCallbacks().
FromIntegral()
template<class E , class T = int>
static constexpr EnumSet v8::base::EnumSet< E, T >::FromIntegral (T bits) [inline], [static], [constexpr]
Definition at line 90 of file enum-set.h.
{ return EnumSet{bits}; }
Intersect()
template<class E , class T = int>
constexpr void v8::base::EnumSet< E, T >::Intersect (EnumSet< E, T > set) [inline], [constexpr]
Definition at line 55 of file enum-set.h.
{ bits_ &= set.bits_; }
References v8::base::EnumSet< E, T >::bits_.
is_subset_of()
template<class E , class T = int>
constexpr bool v8::base::EnumSet< E, T >::is_subset_of (EnumSet< E, T > set) const [inline], [constexpr]
Definition at line 47 of file enum-set.h.
                                                 {
    return (bits_ & set.bits_) == bits_;
  }
References v8::base::EnumSet< E, T >::bits_.
Referenced by v8::internal::maglev::MaglevPhiRepresentationSelector::ProcessPhi(), and v8::internal::maglev::Phi::RecordUseReprHint().
Mask()
template<class E , class T = int>
static constexpr T v8::base::EnumSet< E, T >::Mask (E element) [inline], [static], [constexpr], [private]
Definition at line 95 of file enum-set.h.
                                     {
    DCHECK_GT(sizeof(T) * 8, static_cast<size_t>(element));
    return T{1} << static_cast<std::underlying_type_t<E>>(element);
  }
References DCHECK_GT.
Referenced by v8::base::EnumSet< E, T >::Add(), v8::base::EnumSet< E, T >::contains(), v8::base::EnumSet< E, T >::contains_only(), v8::base::EnumSet< E, T >::EnumSet(), v8::base::EnumSet< E, T >::operator&(), v8::base::EnumSet< E, T >::operator-(), v8::base::EnumSet< E, T >::operator|(), and v8::base::EnumSet< E, T >::Remove().
operator&() [1/2]
template<class E , class T = int>
constexpr EnumSet v8::base::EnumSet< E, T >::operator& (E element) const [inline], [constexpr]
Definition at line 79 of file enum-set.h.
                                               {
    return EnumSet(bits_ & Mask(element));
  }
References v8::base::EnumSet< E, T >::bits_, v8::base::EnumSet< E, T >::EnumSet(), and v8::base::EnumSet< E, T >::Mask().
operator&() [2/2]
template<class E , class T = int>
constexpr EnumSet v8::base::EnumSet< E, T >::operator& (EnumSet< E, T > set) const [inline], [constexpr]
Definition at line 65 of file enum-set.h.
                                                 {
    return EnumSet(bits_ & set.bits_);
  }
References v8::base::EnumSet< E, T >::bits_, and v8::base::EnumSet< E, T >::EnumSet().
operator&=() [1/2]
template<class E , class T = int>
EnumSet& v8::base::EnumSet< E, T >::operator&= (E element) [inline]
Definition at line 87 of file enum-set.h.
{ return *this = *this & element; }
operator&=() [2/2]
template<class E , class T = int>
EnumSet& v8::base::EnumSet< E, T >::operator&= (EnumSet< E, T > set) [inline]
Definition at line 73 of file enum-set.h.
{ return *this = *this & set; }
operator-() [1/2]
template<class E , class T = int>
constexpr EnumSet v8::base::EnumSet< E, T >::operator- (E element) const [inline], [constexpr]
Definition at line 82 of file enum-set.h.
                                               {
    return EnumSet(bits_ & ~Mask(element));
  }
References v8::base::EnumSet< E, T >::bits_, v8::base::EnumSet< E, T >::EnumSet(), and v8::base::EnumSet< E, T >::Mask().
operator-() [2/2]
template<class E , class T = int>
constexpr EnumSet v8::base::EnumSet< E, T >::operator- (EnumSet< E, T > set) const [inline], [constexpr]
Definition at line 68 of file enum-set.h.
                                                 {
    return EnumSet(bits_ & ~set.bits_);
  }
References v8::base::EnumSet< E, T >::bits_, and v8::base::EnumSet< E, T >::EnumSet().
operator-=() [1/2]
template<class E , class T = int>
EnumSet& v8::base::EnumSet< E, T >::operator-= (E element) [inline]
Definition at line 88 of file enum-set.h.
{ return *this = *this - element; }
operator-=() [2/2]
template<class E , class T = int>
EnumSet& v8::base::EnumSet< E, T >::operator-= (EnumSet< E, T > set) [inline]
Definition at line 74 of file enum-set.h.
{ return *this = *this - set; }
operator==()
template<class E , class T = int>
constexpr bool v8::base::EnumSet< E, T >::operator== (EnumSet< E, T > set) const [inline], [constexpr]
Definition at line 60 of file enum-set.h.
{ return bits_ == set.bits_; }
References v8::base::EnumSet< E, T >::bits_.
operator|() [1/2]
template<class E , class T = int>
constexpr EnumSet v8::base::EnumSet< E, T >::operator| (E element) const [inline], [constexpr]
Definition at line 76 of file enum-set.h.
                                               {
    return EnumSet(bits_ | Mask(element));
  }
References v8::base::EnumSet< E, T >::bits_, v8::base::EnumSet< E, T >::EnumSet(), and v8::base::EnumSet< E, T >::Mask().
operator|() [2/2]
template<class E , class T = int>
constexpr EnumSet v8::base::EnumSet< E, T >::operator| (EnumSet< E, T > set) const [inline], [constexpr]
Definition at line 62 of file enum-set.h.
                                                 {
    return EnumSet(bits_ | set.bits_);
  }
References v8::base::EnumSet< E, T >::bits_, and v8::base::EnumSet< E, T >::EnumSet().
operator|=() [1/2]
template<class E , class T = int>
EnumSet& v8::base::EnumSet< E, T >::operator|= (E element) [inline]
Definition at line 86 of file enum-set.h.
{ return *this = *this | element; }
operator|=() [2/2]
template<class E , class T = int>
EnumSet& v8::base::EnumSet< E, T >::operator|= (EnumSet< E, T > set) [inline]
Definition at line 72 of file enum-set.h.
{ return *this = *this | set; }
operator ()
template<class E , class T = int>
constexpr EnumSet v8::base::EnumSet< E, T >::operator~ () const [inline], [constexpr]
Definition at line 58 of file enum-set.h.
{ return EnumSet(~bits_); }
References v8::base::EnumSet< E, T >::bits_, and v8::base::EnumSet< E, T >::EnumSet().
Remove() [1/2]
template<class E , class T = int>
constexpr void v8::base::EnumSet< E, T >::Remove (E element) [inline], [constexpr]
Definition at line 52 of file enum-set.h.
{ bits_ &= ~Mask(element); }
References v8::base::EnumSet< E, T >::bits_, and v8::base::EnumSet< E, T >::Mask().
Referenced by v8::internal::anonymous_namespace{asm-js.cc}::AreStdlibMembersValid(), and v8::base::operator<<().
Remove() [2/2]
template<class E , class T = int>
constexpr void v8::base::EnumSet< E, T >::Remove (EnumSet< E, T > set) [inline], [constexpr]
Definition at line 53 of file enum-set.h.
{ bits_ &= ~set.bits_; }
References v8::base::EnumSet< E, T >::bits_.
RemoveAll()
template<class E , class T = int>
constexpr void v8::base::EnumSet< E, T >::RemoveAll () [inline], [constexpr]
Definition at line 54 of file enum-set.h.
{ bits_ = 0; }
References v8::base::EnumSet< E, T >::bits_.
Referenced by v8::internal::maglev::MaglevPhiRepresentationSelector::ProcessPhi().
ToIntegral()
template<class E , class T = int>
constexpr T v8::base::EnumSet< E, T >::ToIntegral () const [inline], [constexpr]
Definition at line 56 of file enum-set.h.
{ return bits_; }
References v8::base::EnumSet< E, T >::bits_.
Referenced by v8::internal::wasm::CompileTimeImports::compare(), v8::internal::AsmJsCompilationJob::FinalizeJobImpl(), v8::base::operator<<(), v8::internal::wasm::NativeModuleSerializer::WriteHeader(), and v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::WriteHeader().
Member Data Documentation
bits_
template<class E , class T = int>
T v8::base::EnumSet< E, T >::bits_ = 0 [private]
Definition at line 100 of file enum-set.h.
Referenced by v8::base::EnumSet< E, T >::Add(), v8::base::EnumSet< E, T >::contains(), v8::base::EnumSet< E, T >::contains_all(), v8::base::EnumSet< E, T >::contains_any(), v8::base::EnumSet< E, T >::contains_only(), v8::base::EnumSet< E, T >::empty(), v8::base::EnumSet< E, T >::EnumSet(), v8::base::EnumSet< E, T >::Intersect(), v8::base::EnumSet< E, T >::is_subset_of(), v8::base::EnumSet< E, T >::operator&(), v8::base::EnumSet< E, T >::operator-(), v8::internal::wasm::CompileTimeImports::operator=(), v8::base::EnumSet< E, T >::operator==(), v8::base::EnumSet< E, T >::operator|(), v8::base::EnumSet< E, T >::operator~(), v8::base::EnumSet< E, T >::Remove(), v8::base::EnumSet< E, T >::RemoveAll(), and v8::base::EnumSet< E, T >::ToIntegral().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/base/enum-set.h