v8::internal::SegmentedTable< Entry, size >::WriteIterator Class Reference
#include <segmented-table.h>
Public Member Functions
WriteIterator (Entry *base, uint32_t index)
uint32_t index () const
Entry * operator-> ()
Entry & operator* ()
WriteIterator & operator++ ()
WriteIterator & operator-- ()
Private Attributes
Entry * base_
uint32_t index_
std::conditional_t< kIsWriteProtected, CFIMetadataWriteScope, NopRwxMemoryWriteScope > write_scope_
Detailed Description
template<typename Entry, size_t size>
class v8::internal::SegmentedTable< Entry, size >::WriteIterator
Definition at line 155 of file segmented-table.h.
Constructor & Destructor Documentation
WriteIterator()
template<typename Entry , size_t size>
v8::internal::SegmentedTable< Entry, size >::WriteIterator::WriteIterator (Entry * base, uint32_t index) [explicit]
Definition at line 263 of file segmented-table-inl.h.
    : base_(base), index_(index), write_scope_("pointer table write") {}
Member Function Documentation
index()
template<typename Entry , size_t size>
uint32_t v8::internal::SegmentedTable< Entry, size >::WriteIterator::index () const [inline]
Definition at line 159 of file segmented-table.h.
{ return index_; }
Referenced by v8::internal::ExternalEntityTable< Entry, size >::GenericSweep(), and v8::internal::SegmentedTable< Entry, size >::InitializeFreeList().
operator*()
template<typename Entry , size_t size>
Entry& v8::internal::SegmentedTable< Entry, size >::WriteIterator::operator* () [inline]
Definition at line 164 of file segmented-table.h.
                       {
      DCHECK(!crossed_segment_);
      return base_[index_];
    }
References v8::internal::DCHECK().
operator++()
template<typename Entry , size_t size>
WriteIterator& v8::internal::SegmentedTable< Entry, size >::WriteIterator::operator++ () [inline]
Definition at line 168 of file segmented-table.h.
                                {
      index_++;
#ifdef DEBUG
      if (IsAligned(index_, kEntriesPerSegment)) {
        crossed_segment_ = true;
      }
#endif
      return *this;
    }
References IsAligned().
operator--()
template<typename Entry , size_t size>
WriteIterator& v8::internal::SegmentedTable< Entry, size >::WriteIterator::operator-- () [inline]
Definition at line 177 of file segmented-table.h.
                                {
      DCHECK_GT(index_, 0);
#ifdef DEBUG
      if (IsAligned(index_, kEntriesPerSegment)) {
        crossed_segment_ = true;
      }
#endif
      index_--;
      return *this;
    }
References DCHECK_GT, and IsAligned().
operator->()
template<typename Entry , size_t size>
Entry* v8::internal::SegmentedTable< Entry, size >::WriteIterator::operator-> () [inline]
Definition at line 160 of file segmented-table.h.
                        {
      DCHECK(!crossed_segment_);
      return &base_[index_];
    }
References v8::internal::DCHECK().
Member Data Documentation
base_
template<typename Entry , size_t size>
Entry* v8::internal::SegmentedTable< Entry, size >::WriteIterator::base_ [private]
Definition at line 189 of file segmented-table.h.
index_
template<typename Entry , size_t size>
uint32_t v8::internal::SegmentedTable< Entry, size >::WriteIterator::index_ [private]
Definition at line 190 of file segmented-table.h.
write_scope_
template<typename Entry , size_t size>
std::conditional_t<kIsWriteProtected, CFIMetadataWriteScope, NopRwxMemoryWriteScope> v8::internal::SegmentedTable< Entry, size >::WriteIterator::write_scope_ [private]
Definition at line 193 of file segmented-table.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/common/segmented-table.h
/mnt/V8SourceCode/src/common/segmented-table-inl.h