v8::internal::KeyedStoreIC Class Reference
#include <ic.h>
Public Member Functions
KeyedAccessStoreMode GetKeyedAccessStoreMode ()
KeyedStoreIC (Isolate *isolate, Handle< FeedbackVector > vector, FeedbackSlot slot, FeedbackSlotKind kind)
V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > Store (Handle< JSAny > object, Handle< Object > name, DirectHandle< Object > value)
Protected Member Functions
void UpdateStoreElement (Handle< Map > receiver_map, KeyedAccessStoreMode store_mode, Handle< Map > new_receiver_map)
Private Member Functions
DirectHandle< Map > ComputeTransitionedMap (Handle< Map > map, TransitionMode transition_mode)
Handle< Object > StoreElementHandler (DirectHandle< Map > receiver_map, KeyedAccessStoreMode store_mode, MaybeDirectHandle< UnionOf< Smi, Cell >> prev_validity_cell=kNullMaybeHandle)
void StoreElementPolymorphicHandlers (MapsAndHandlers *receiver_maps_and_handlers, KeyedAccessStoreMode store_mode)
Friends
class IC
Additional Inherited Members
Detailed Description
Definition at line 312 of file ic.h.
Constructor & Destructor Documentation
KeyedStoreIC()
v8::internal::KeyedStoreIC::KeyedStoreIC (Isolate * isolate, Handle< FeedbackVector > vector, FeedbackSlot slot, FeedbackSlotKind kind) [inline]
Definition at line 318 of file ic.h.
      : StoreIC(isolate, vector, slot, kind) {}
Member Function Documentation
ComputeTransitionedMap()
DirectHandle<Map> v8::internal::KeyedStoreIC::ComputeTransitionedMap (Handle< Map > map, TransitionMode transition_mode) [private]
GetKeyedAccessStoreMode()
KeyedAccessStoreMode v8::internal::KeyedStoreIC::GetKeyedAccessStoreMode () [inline]
Definition at line 314 of file ic.h.
                                                 {
    return nexus()->GetKeyedAccessStoreMode();
  }
References v8::internal::FeedbackNexus::GetKeyedAccessStoreMode(), and v8::internal::IC::nexus().
Referenced by UpdateStoreElement().
Store()
MaybeDirectHandle< Object > v8::internal::KeyedStoreIC::Store (Handle< JSAny > object, Handle< Object > name, DirectHandle< Object > value)
Definition at line 2599 of file ic.cc.
                                                                          {
  // TODO(verwaest): Let SetProperty do the migration, since storing a property
  // might deprecate the current map again, if value does not fit.
  if (MigrateDeprecated(isolate(), object)) {
    DirectHandle<Object> result;
    // TODO(v8:12548): refactor DefineKeyedOwnIC as a subclass of StoreIC
    // so the logic doesn't get mixed here.
    ASSIGN_RETURN_ON_EXCEPTION(
        isolate(), result,
        IsDefineKeyedOwnIC()
            ? Runtime::DefineObjectOwnProperty(isolate(), object, key, value,
                                               StoreOrigin::kNamed)
            : Runtime::SetObjectProperty(isolate(), object, key, value,
                                         StoreOrigin::kMaybeKeyed));
    return result;
  }
  DirectHandle<Object> store_handle;
  intptr_t maybe_index;
  Handle<Name> maybe_name;
  KeyType key_type = TryConvertKey(key, isolate(), &maybe_index, &maybe_name);
  if (key_type == kName) {
    ASSIGN_RETURN_ON_EXCEPTION(
        isolate(), store_handle,
        StoreIC::Store(object, maybe_name, value, StoreOrigin::kMaybeKeyed));
    if (vector_needs_update()) {
      if (ConfigureVectorState(MEGAMORPHIC, key)) {
        set_slow_stub_reason("unhandled internalized string key");
        TraceIC("StoreIC", key);
      }
    }
    return store_handle;
  }
  JSObject::MakePrototypesFast(object, kStartAtPrototype, isolate());
  // TODO(jkummerow): Refactor the condition logic here and below.
  bool use_ic = (state() != NO_FEEDBACK) && v8_flags.use_ic &&
                !IsStringWrapper(*object) && !IsAccessCheckNeeded(*object) &&
                !IsJSGlobalProxy(*object);
  if (use_ic && !IsSmi(*object)) {
    // Don't use ICs for maps of the objects in Array's prototype chain. We
    // expect to be able to trap element sets to objects with those maps in
    // the runtime to enable optimization of element hole access.
    DirectHandle<HeapObject> heap_object = Cast<HeapObject>(object);
    if (heap_object->map()->IsMapInArrayPrototypeChain(isolate())) {
      set_slow_stub_reason("map in array prototype");
      use_ic = false;
    }
  }
  Handle<Map> old_receiver_map;
  bool is_arguments = false;
  bool key_is_valid_index = (key_type == kIntPtr);
  KeyedAccessStoreMode store_mode = KeyedAccessStoreMode::kInBounds;
  if (use_ic && IsJSReceiver(*object) && key_is_valid_index) {
    DirectHandle<JSReceiver> receiver = Cast<JSReceiver>(object);
    old_receiver_map = handle(receiver->map(), isolate());
    is_arguments = IsJSArgumentsObject(*receiver);
    bool is_jsobject = IsJSObject(*receiver);
    size_t index;
    key_is_valid_index = IntPtrKeyToSize(maybe_index, receiver, &index);
    if (is_jsobject && !is_arguments && key_is_valid_index) {
      DirectHandle<JSObject> receiver_object = Cast<JSObject>(object);
      store_mode = GetStoreMode(receiver_object, index);
    }
  }
  DCHECK(store_handle.is_null());
  // TODO(v8:12548): refactor DefineKeyedOwnIC as a subclass of StoreIC
  // so the logic doesn't get mixed here.
  MaybeDirectHandle<Object> result =
      IsDefineKeyedOwnIC()
          ? Runtime::DefineObjectOwnProperty(isolate(), object, key, value,
                                             StoreOrigin::kNamed)
          : Runtime::SetObjectProperty(isolate(), object, key, value,
                                       StoreOrigin::kMaybeKeyed);
  if (result.is_null()) {
    DCHECK(isolate()->has_exception());
    set_slow_stub_reason("failed to set property");
    use_ic = false;
  }
  if (use_ic) {
    if (!old_receiver_map.is_null()) {
      if (is_arguments) {
        set_slow_stub_reason("arguments receiver");
      } else if (IsJSArray(*object) && StoreModeCanGrow(store_mode) &&
                 JSArray::HasReadOnlyLength(Cast<JSArray>(object))) {
        set_slow_stub_reason("array has read only length");
      } else if (IsJSObject(*object) &&
                 MayHaveTypedArrayInPrototypeChain(isolate(),
                                                   Cast<JSObject>(object))) {
        // Make sure we don't handle this in IC if there's any JSTypedArray in
        // the {receiver}'s prototype chain, since that prototype is going to
        // swallow all stores that are out-of-bounds for said prototype, and we
        // just let the runtime deal with the complexity of this.
        set_slow_stub_reason("typed array in the prototype chain");
      } else if (key_is_valid_index) {
        if (old_receiver_map->is_abandoned_prototype_map()) {
          set_slow_stub_reason("receiver with prototype map");
#if V8_ENABLE_WEBASSEMBLY
        } else if (IsWasmObjectMap(*old_receiver_map)) {
          // Handle object types for which we don't need to check for
          // read-only prototype elements because we'll use the slow handler
          // anyway.
          DirectHandle<HeapObject> receiver = Cast<HeapObject>(object);
          UpdateStoreElement(old_receiver_map, store_mode,
                             handle(receiver->map(), isolate()));
#endif // V8_ENABLE_WEBASSEMBLY
        } else if (old_receiver_map->has_dictionary_elements() ||
                   !old_receiver_map
                        ->ShouldCheckForReadOnlyElementsInPrototypeChain(
                            isolate())) {
          // We should go generic if receiver isn't a dictionary, but our
          // prototype chain does have dictionary elements. This ensures that
          // other non-dictionary receivers in the polymorphic case benefit
          // from fast path keyed stores.
          DirectHandle<HeapObject> receiver = Cast<HeapObject>(object);
          UpdateStoreElement(old_receiver_map, store_mode,
                             handle(receiver->map(), isolate()));
        } else {
          set_slow_stub_reason("prototype with potentially read-only elements");
        }
      } else {
        set_slow_stub_reason("non-smi-like key");
      }
    } else {
      set_slow_stub_reason("non-JSObject receiver");
    }
  }
  if (vector_needs_update()) {
    ConfigureVectorState(MEGAMORPHIC, key);
  }
  TraceIC("StoreIC", key);
  return result;
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::IC::ConfigureVectorState(), v8::internal::DCHECK(), v8::internal::Runtime::DefineObjectOwnProperty(), v8::internal::anonymous_namespace{ic.cc}::GetStoreMode(), v8::internal::handle(), v8::internal::JSArray::HasReadOnlyLength(), v8::internal::index, v8::internal::anonymous_namespace{ic.cc}::IntPtrKeyToSize(), v8::internal::HandleBase::is_null(), v8::internal::DirectHandle< T >::is_null(), v8::internal::IC::IsDefineKeyedOwnIC(), v8::internal::IC::isolate(), v8::internal::IsSmi(), v8::internal::key, v8::internal::kInBounds, v8::internal::kMaybeKeyed, v8::internal::anonymous_namespace{ic.cc}::kName, v8::internal::kNamed, v8::internal::kStartAtPrototype, v8::internal::JSObject::MakePrototypesFast(), v8::internal::anonymous_namespace{ic.cc}::MayHaveTypedArrayInPrototypeChain(), v8::internal::MEGAMORPHIC, v8::internal::anonymous_namespace{ic.cc}::MigrateDeprecated(), v8::internal::NO_FEEDBACK, v8::base::internal::result, v8::internal::IC::set_slow_stub_reason(), v8::internal::Runtime::SetObjectProperty(), v8::internal::IC::state(), v8::internal::StoreIC::Store(), v8::internal::StoreModeCanGrow(), v8::internal::IC::TraceIC(), v8::internal::anonymous_namespace{ic.cc}::TryConvertKey(), UpdateStoreElement(), v8::internal::v8_flags, v8::internal::value, and v8::internal::IC::vector_needs_update().
Referenced by v8::internal::RUNTIME_FUNCTION().
StoreElementHandler()
Handle< Object > v8::internal::KeyedStoreIC::StoreElementHandler (DirectHandle< Map > receiver_map, KeyedAccessStoreMode store_mode, MaybeDirectHandle< UnionOf< Smi, Cell >> prev_validity_cell = kNullMaybeHandle) [private]
Definition at line 2416 of file ic.cc.
                                                              {
  if (!IsJSObjectMap(*receiver_map)) {
    // DefineKeyedOwnIC, which is used to define computed fields in instances,
    // should handled by the slow stub below instead of the proxy stub.
    if (IsJSProxyMap(*receiver_map) && !IsDefineKeyedOwnIC()) {
      return StoreHandler::StoreProxy(isolate());
    }
#if V8_ENABLE_WEBASSEMBLY
    if (IsWasmObjectMap(*receiver_map)) {
      set_slow_stub_reason("wasm object");
    }
#endif // V8_ENABLE_WEBASSEMBLY
    // Wasm objects or other kind of special objects go through the slow stub.
    TRACE_HANDLER_STATS(isolate(), KeyedStoreIC_SlowStub);
    return StoreHandler::StoreSlow(isolate(), store_mode);
  }
  // The only case when could keep using non-slow element store handler for
  // a fast array with potentially read-only elements is when it's an
  // initializing store to array literal.
  DCHECK_IMPLIES(
      !receiver_map->has_dictionary_elements() &&
          receiver_map->ShouldCheckForReadOnlyElementsInPrototypeChain(
              isolate()),
      IsStoreInArrayLiteralIC());
  // TODO(ishell): move to StoreHandler::StoreElement().
  Handle<Code> code;
  if (receiver_map->has_sloppy_arguments_elements()) {
    // TODO(jgruber): Update counter name.
    TRACE_HANDLER_STATS(isolate(), KeyedStoreIC_KeyedStoreSloppyArgumentsStub);
    code = StoreHandler::StoreSloppyArgumentsBuiltin(isolate(), store_mode);
  } else if (receiver_map->has_fast_elements() ||
             receiver_map->has_sealed_elements() ||
             receiver_map->has_nonextensible_elements() ||
             receiver_map->has_typed_array_or_rab_gsab_typed_array_elements()) {
    // TODO(jgruber): Update counter name.
    TRACE_HANDLER_STATS(isolate(), KeyedStoreIC_StoreFastElementStub);
    if (IsJSArgumentsObjectMap(*receiver_map) &&
        receiver_map->has_fast_packed_elements()) {
      // Allow fast behaviour for in-bounds stores while making it miss and
      // properly handle the out of bounds store case.
      code = StoreHandler::StoreFastElementBuiltin(
          isolate(), KeyedAccessStoreMode::kInBounds);
    } else {
      code = StoreHandler::StoreFastElementBuiltin(isolate(), store_mode);
      if (receiver_map->has_typed_array_or_rab_gsab_typed_array_elements()) {
        return code;
      }
    }
  } else if (IsStoreInArrayLiteralIC()) {
    // TODO(jgruber): Update counter name.
    TRACE_HANDLER_STATS(isolate(), StoreInArrayLiteralIC_SlowStub);
    return StoreHandler::StoreSlow(isolate(), store_mode);
  } else {
    // TODO(jgruber): Update counter name.
    TRACE_HANDLER_STATS(isolate(), KeyedStoreIC_StoreElementStub);
    DCHECK(DICTIONARY_ELEMENTS == receiver_map->elements_kind() ||
           receiver_map->has_frozen_elements());
    return StoreHandler::StoreSlow(isolate(), store_mode);
  }
  if (IsAnyDefineOwn() || IsStoreInArrayLiteralIC()) return code;
  DirectHandle<UnionOf<Smi, Cell>> validity_cell;
  if (!prev_validity_cell.ToHandle(&validity_cell)) {
    validity_cell =
        Map::GetOrCreatePrototypeChainValidityCell(receiver_map, isolate());
  }
  if (IsSmi(*validity_cell)) {
    // There's no prototype validity cell to check, so we can just use the stub.
    return code;
  }
  Handle<StoreHandler> handler = isolate()->factory()->NewStoreHandler(0);
  handler->set_validity_cell(*validity_cell);
  handler->set_smi_handler(*code);
  return handler;
}
References code, v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::DICTIONARY_ELEMENTS, v8::internal::Isolate::factory(), v8::internal::Map::GetOrCreatePrototypeChainValidityCell(), v8::internal::IC::IsAnyDefineOwn(), v8::internal::IC::IsDefineKeyedOwnIC(), v8::internal::IC::isolate(), v8::internal::IsSmi(), v8::internal::IC::IsStoreInArrayLiteralIC(), v8::internal::kInBounds, v8::internal::Factory::NewStoreHandler(), v8::internal::IC::set_slow_stub_reason(), v8::internal::StoreHandler::StoreFastElementBuiltin(), v8::internal::StoreHandler::StoreProxy(), v8::internal::StoreHandler::StoreSloppyArgumentsBuiltin(), v8::internal::StoreHandler::StoreSlow(), and TRACE_HANDLER_STATS.
Referenced by StoreElementPolymorphicHandlers(), and UpdateStoreElement().
StoreElementPolymorphicHandlers()
void v8::internal::KeyedStoreIC::StoreElementPolymorphicHandlers (MapsAndHandlers * receiver_maps_and_handlers, KeyedAccessStoreMode store_mode) [private]
Definition at line 2498 of file ic.cc.
                                     {
  DirectHandleVector<Map> receiver_maps(isolate());
  receiver_maps.reserve(receiver_maps_and_handlers->size());
  for (DirectHandle<Map> map : receiver_maps_and_handlers->maps()) {
    receiver_maps.push_back(map);
  }
  for (size_t i = 0; i < receiver_maps_and_handlers->size(); i++) {
    auto [receiver_map, old_handler] = (*receiver_maps_and_handlers)[i];
    DCHECK(!receiver_map->is_deprecated());
    DirectHandle<Object> handler;
    DirectHandle<Map> transition;
    if (receiver_map->instance_type() < FIRST_JS_RECEIVER_TYPE ||
        receiver_map->ShouldCheckForReadOnlyElementsInPrototypeChain(
            isolate())) {
      // TODO(mvstanton): Consider embedding store_mode in the state of the slow
      // keyed store ic for uniformity.
      TRACE_HANDLER_STATS(isolate(), KeyedStoreIC_SlowStub);
      handler = StoreHandler::StoreSlow(isolate());
    } else {
      {
        Tagged<Map> tmap = receiver_map->FindElementsKindTransitionedMap(
            isolate(),
            MapHandlesSpan(receiver_maps.begin(), receiver_maps.end()),
            ConcurrencyMode::kSynchronous);
        if (!tmap.is_null()) {
          if (receiver_map->is_stable()) {
            receiver_map->NotifyLeafMapLayoutChange(isolate());
          }
          transition = direct_handle(tmap, isolate());
        }
      }
      MaybeDirectHandle<UnionOf<Smi, Cell>> validity_cell;
      Tagged<HeapObject> old_handler_obj;
      if (!old_handler.is_null() &&
          (*old_handler).GetHeapObject(&old_handler_obj) &&
          IsDataHandler(old_handler_obj)) {
        validity_cell = direct_handle(
            Cast<DataHandler>(old_handler_obj)->validity_cell(), isolate());
      }
      // TODO(mythria): Do not recompute the handler if we know there is no
      // change in the handler.
      // TODO(mvstanton): The code below is doing pessimistic elements
      // transitions. I would like to stop doing that and rely on Allocation
      // Site Tracking to do a better job of ensuring the data types are what
      // they need to be. Not all the elements are in place yet, pessimistic
      // elements transitions are still important for performance.
      if (!transition.is_null()) {
        TRACE_HANDLER_STATS(isolate(),
                            KeyedStoreIC_ElementsTransitionAndStoreStub);
        handler = StoreHandler::StoreElementTransition(
            isolate(), receiver_map, transition, store_mode, validity_cell);
      } else {
        handler = StoreElementHandler(receiver_map, store_mode, validity_cell);
      }
    }
    DCHECK(!handler.is_null());
    receiver_maps_and_handlers->set_map(i, receiver_map);
    receiver_maps_and_handlers->set_handler(i,
                                            MaybeObjectDirectHandle(handler));
  }
}
References v8::internal::DirectHandleVector< T >::begin(), v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::DirectHandleVector< T >::end(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::DirectHandle< T >::is_null(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::IC::isolate(), v8::internal::kSynchronous, v8::internal::MapsAndHandlers::maps(), v8::internal::DirectHandleVector< T >::push_back(), v8::internal::DirectHandleVector< T >::reserve(), v8::internal::MapsAndHandlers::set_handler(), v8::internal::MapsAndHandlers::set_map(), v8::internal::MapsAndHandlers::size(), StoreElementHandler(), v8::internal::StoreHandler::StoreElementTransition(), v8::internal::StoreHandler::StoreSlow(), and TRACE_HANDLER_STATS.
Referenced by UpdateStoreElement().
UpdateStoreElement()
void v8::internal::KeyedStoreIC::UpdateStoreElement (Handle< Map > receiver_map, KeyedAccessStoreMode store_mode, Handle< Map > new_receiver_map) [protected]
Definition at line 2276 of file ic.cc.
                                                                    {
  MapsAndHandlers target_maps_and_handlers(isolate());
  nexus()->ExtractMapsAndHandlers(
      &target_maps_and_handlers,
      [this](Handle<Map> map) { return Map::TryUpdate(isolate(), map); });
  if (target_maps_and_handlers.empty()) {
    DirectHandle<Map> monomorphic_map = receiver_map;
    // If we transitioned to a map that is a more general map than incoming
    // then use the new map.
    if (IsTransitionOfMonomorphicTarget(*receiver_map, *new_receiver_map)) {
      monomorphic_map = new_receiver_map;
    }
    DirectHandle<Object> handler =
        StoreElementHandler(monomorphic_map, store_mode);
    return ConfigureVectorState(DirectHandle<Name>(), monomorphic_map, handler);
  }
  for (DirectHandle<Map> map : target_maps_and_handlers.maps()) {
    if (!map.is_null() && map->instance_type() == JS_PRIMITIVE_WRAPPER_TYPE) {
      DCHECK(!IsStoreInArrayLiteralIC());
      set_slow_stub_reason("JSPrimitiveWrapper");
      return;
    }
  }
  // There are several special cases where an IC that is MONOMORPHIC can still
  // transition to a different IC that handles a superset of the original IC.
  // Handle those here if the receiver map hasn't changed or it has transitioned
  // to a more general kind.
  KeyedAccessStoreMode old_store_mode = GetKeyedAccessStoreMode();
  DirectHandle<Map> previous_receiver_map = target_maps_and_handlers.maps()[0];
  if (state() == MONOMORPHIC) {
    DirectHandle<Map> transitioned_receiver_map = new_receiver_map;
    if (IsTransitionOfMonomorphicTarget(*previous_receiver_map,
                                        *transitioned_receiver_map)) {
      // If the "old" and "new" maps are in the same elements map family, or
      // if they at least come from the same origin for a transitioning store,
      // stay MONOMORPHIC and use the map for the most generic ElementsKind.
      DirectHandle<Object> handler =
          StoreElementHandler(transitioned_receiver_map, store_mode);
      ConfigureVectorState(DirectHandle<Name>(), transitioned_receiver_map,
                           handler);
      return;
    }
    // If there is no transition and if we have seen the same map earlier and
    // there is only a change in the store_mode we can still stay monomorphic.
    if (receiver_map.is_identical_to(previous_receiver_map) &&
        new_receiver_map.is_identical_to(receiver_map) &&
        StoreModeIsInBounds(old_store_mode) &&
        !StoreModeIsInBounds(store_mode)) {
      if (IsJSArrayMap(*receiver_map) &&
          JSArray::MayHaveReadOnlyLength(*receiver_map)) {
        set_slow_stub_reason(
            "can't generalize store mode (potentially read-only length)");
        return;
      }
      // A "normal" IC that handles stores can switch to a version that can
      // grow at the end of the array, handle OOB accesses or copy COW arrays
      // and still stay MONOMORPHIC.
      DirectHandle<Object> handler =
          StoreElementHandler(receiver_map, store_mode);
      return ConfigureVectorState(DirectHandle<Name>(), receiver_map, handler);
    }
  }
  DCHECK(state() != GENERIC);
  bool map_added =
      AddOneReceiverMapIfMissing(&target_maps_and_handlers, receiver_map);
  if (IsTransitionOfMonomorphicTarget(*receiver_map, *new_receiver_map)) {
    map_added |=
        AddOneReceiverMapIfMissing(&target_maps_and_handlers, new_receiver_map);
  }
  if (!map_added) {
    // If the miss wasn't due to an unseen map, a polymorphic stub
    // won't help, use the megamorphic stub which can handle everything.
    set_slow_stub_reason("same map added twice");
    return;
  }
  // If the maximum number of receiver maps has been exceeded, use the
  // megamorphic version of the IC.
  if (static_cast<int>(target_maps_and_handlers.size()) >
      v8_flags.max_valid_polymorphic_map_count) {
    return;
  }
  // Make sure all polymorphic handlers have the same store mode, otherwise the
  // megamorphic stub must be used.
  if (!StoreModeIsInBounds(old_store_mode)) {
    if (StoreModeIsInBounds(store_mode)) {
      store_mode = old_store_mode;
    } else if (store_mode != old_store_mode) {
      set_slow_stub_reason("store mode mismatch");
      return;
    }
  }
  // If the store mode isn't the standard mode, make sure that all polymorphic
  // receivers are either external arrays, or all "normal" arrays with writable
  // length. Otherwise, use the megamorphic stub.
  if (!StoreModeIsInBounds(store_mode)) {
    size_t external_arrays = 0;
    for (DirectHandle<Map> map : target_maps_and_handlers.maps()) {
      if (IsJSArrayMap(*map) && JSArray::MayHaveReadOnlyLength(*map)) {
        set_slow_stub_reason(
            "unsupported combination of arrays (potentially read-only length)");
        return;
      } else if (map->has_typed_array_or_rab_gsab_typed_array_elements()) {
        DCHECK(!IsStoreInArrayLiteralIC());
        external_arrays++;
      }
    }
    if (external_arrays != 0 &&
        external_arrays != target_maps_and_handlers.size()) {
      DCHECK(!IsStoreInArrayLiteralIC());
      set_slow_stub_reason(
          "unsupported combination of external and normal arrays");
      return;
    }
  }
  StoreElementPolymorphicHandlers(&target_maps_and_handlers, store_mode);
  if (target_maps_and_handlers.empty()) {
    DirectHandle<Object> handler =
        StoreElementHandler(receiver_map, store_mode);
    ConfigureVectorState(DirectHandle<Name>(), receiver_map, handler);
  } else if (target_maps_and_handlers.size() == 1) {
    auto [map, handler] = target_maps_and_handlers[0];
    ConfigureVectorState(DirectHandle<Name>(), map, handler);
  } else {
    ConfigureVectorState(DirectHandle<Name>(), target_maps_and_handlers);
  }
}
References v8::internal::anonymous_namespace{ic.cc}::AddOneReceiverMapIfMissing(), v8::internal::IC::ConfigureVectorState(), v8::internal::DCHECK(), v8::internal::MapsAndHandlers::empty(), v8::internal::FeedbackNexus::ExtractMapsAndHandlers(), v8::internal::GENERIC, GetKeyedAccessStoreMode(), v8::internal::HandleBase::is_identical_to(), v8::internal::HandleBase::is_null(), v8::internal::IC::isolate(), v8::internal::IC::IsStoreInArrayLiteralIC(), v8::internal::IC::IsTransitionOfMonomorphicTarget(), v8::internal::MapsAndHandlers::maps(), v8::internal::JSArray::MayHaveReadOnlyLength(), v8::internal::MONOMORPHIC, v8::internal::IC::nexus(), v8::internal::IC::set_slow_stub_reason(), v8::internal::MapsAndHandlers::size(), v8::internal::IC::state(), StoreElementHandler(), StoreElementPolymorphicHandlers(), v8::internal::StoreModeIsInBounds(), v8::internal::Map::TryUpdate(), and v8::internal::v8_flags.
Referenced by v8::internal::StoreInArrayLiteralIC::Store(), and Store().
Friends And Related Function Documentation
IC
friend class IC [friend]
Definition at line 343 of file ic.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ic/ic.h
/mnt/V8SourceCode/src/ic/ic.cc