v8::internal::compiler::CreateArrayIteratorParameters Class Reference
#include <js-operator.h>
Public Member Functions
CreateArrayIteratorParameters (IterationKind kind)
IterationKind kind () const
Private Attributes
IterationKind const kind_
Detailed Description
Definition at line 592 of file js-operator.h.
Constructor & Destructor Documentation
CreateArrayIteratorParameters()
v8::internal::compiler::CreateArrayIteratorParameters::CreateArrayIteratorParameters (IterationKind kind) [inline], [explicit]
Definition at line 594 of file js-operator.h.
: kind_(kind) {}
Member Function Documentation
kind()
IterationKind v8::internal::compiler::CreateArrayIteratorParameters::kind () const [inline]
Definition at line 596 of file js-operator.h.
{ return kind_; }
References kind_.
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), v8::internal::compiler::JSCallReducer::ReduceArrayIteratorPrototypeNext(), and v8::internal::compiler::JSCreateLowering::ReduceJSCreateArrayIterator().
Member Data Documentation
kind_
IterationKind const v8::internal::compiler::CreateArrayIteratorParameters::kind_ [private]
Definition at line 599 of file js-operator.h.
Referenced by kind().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h