v8::base::Thread Class Reference
#include <platform.h>
Classes
class Options
class PlatformData
Public Types
enum class Priority { kBestEffort
, kUserVisible
, kUserBlocking
, kDefault
 }
using LocalStorageKey = int32_t
Public Member Functions
Thread (const Options &options)
Thread (const Thread &)=delete
Thread & operator= (const Thread &)=delete
virtual ~Thread ()
V8_WARN_UNUSED_RESULT bool Start ()
bool StartSynchronously ()
void Join ()
const char * name () const
virtual void Run ()=0
PlatformData * data ()
Priority priority () const
void NotifyStartedAndRun ()
Static Public Member Functions
static LocalStorageKey CreateThreadLocalKey ()
static void DeleteThreadLocalKey (LocalStorageKey key)
static void * GetThreadLocal (LocalStorageKey key)
static void SetThreadLocal (LocalStorageKey key, void *value)
static bool HasThreadLocal (LocalStorageKey key)
static void * GetExistingThreadLocal (LocalStorageKey key)
Static Public Attributes
static const int kMaxThreadNameLength = 16
Private Member Functions
void set_name (const char *name)
Private Attributes
PlatformData * data_
char name_ [kMaxThreadNameLength]
int stack_size_
Priority priority_
Semaphore * start_semaphore_
Detailed Description
Definition at line 538 of file platform.h.
Member Typedef Documentation
LocalStorageKey
using v8::base::Thread::LocalStorageKey = int32_t
Definition at line 546 of file platform.h.
Member Enumeration Documentation
Priority
enum v8::base::Thread::Priority [strong]
Enumerator
kBestEffort
kUserVisible
kUserBlocking
kDefault
Definition at line 551 of file platform.h.
{ kBestEffort, kUserVisible, kUserBlocking, kDefault };
Constructor & Destructor Documentation
Thread() [1/2]
v8::base::Thread::Thread (const Options & options) [explicit]
Definition at line 1189 of file platform-posix.cc.
    : data_(new PlatformData),
      stack_size_(options.stack_size()),
      priority_(options.priority()),
      start_semaphore_(nullptr) {
  const int min_stack_size = static_cast<int>(PTHREAD_STACK_MIN);
  if (stack_size_ > 0) stack_size_ = std::max(stack_size_, min_stack_size);
  set_name(options.name());
}
References v8::base::Thread::Options::name(), set_name(), and stack_size_.
Thread() [2/2]
v8::base::Thread::Thread (const Thread &) [delete]
 Thread()
v8::base::Thread::~Thread () [virtual]
Definition at line 1199 of file platform-posix.cc.
                {
  delete data_;
}
References data_.
Member Function Documentation
CreateThreadLocalKey()
Thread::LocalStorageKey v8::base::Thread::CreateThreadLocalKey () [static]
Definition at line 1351 of file platform-posix.cc.
                                                   {
  pthread_key_t key;
  int result = pthread_key_create(&key, nullptr);
  DCHECK_EQ(0, result);
  USE(result);
  LocalStorageKey local_key = PthreadKeyToLocalKey(key);
#if defined(V8_FAST_TLS_SUPPORTED) && defined(DEBUG)
  CheckFastTls(local_key);
#endif
  return local_key;
}
References DCHECK_EQ, v8::internal::key, v8::base::PthreadKeyToLocalKey(), v8::base::internal::result, and USE.
data()
PlatformData* v8::base::Thread::data () [inline]
Definition at line 627 of file platform.h.
{ return data_; }
Referenced by v8::base::ThreadEntry().
DeleteThreadLocalKey()
void v8::base::Thread::DeleteThreadLocalKey (LocalStorageKey key) [static]
Definition at line 1363 of file platform-posix.cc.
                                                     {
  pthread_key_t pthread_key = LocalKeyToPthreadKey(key);
  int result = pthread_key_delete(pthread_key);
  DCHECK_EQ(0, result);
  USE(result);
}
References DCHECK_EQ, v8::internal::key, v8::base::LocalKeyToPthreadKey(), v8::base::internal::result, and USE.
GetExistingThreadLocal()
static void* v8::base::Thread::GetExistingThreadLocal (LocalStorageKey key) [inline], [static]
Definition at line 617 of file platform.h.
                                                                  {
    return GetThreadLocal(key);
  }
References v8::internal::key.
GetThreadLocal()
void * v8::base::Thread::GetThreadLocal (LocalStorageKey key) [static]
Definition at line 1371 of file platform-posix.cc.
                                                {
  pthread_key_t pthread_key = LocalKeyToPthreadKey(key);
  return pthread_getspecific(pthread_key);
}
References v8::internal::key, and v8::base::LocalKeyToPthreadKey().
HasThreadLocal()
static bool v8::base::Thread::HasThreadLocal (LocalStorageKey key) [inline], [static]
Definition at line 605 of file platform.h.
                                                  {
    return GetThreadLocal(key) != nullptr;
  }
References v8::internal::key.
Join()
void v8::base::Thread::Join ()
Definition at line 1311 of file platform-posix.cc.
{ pthread_join(data_->thread_, nullptr); }
References data_, and v8::base::Thread::PlatformData::thread_.
Referenced by v8::internal::Profiler::Disengage(), v8::SourceGroup::JoinThread(), v8::internal::ParkingThread::ParkedJoin(), v8::StreamerThread::StartThreadForTaskAndJoin(), v8::internal::ProfilerEventsProcessor::StopSynchronously(), and v8::Worker::TerminateAndWaitForThread().
name()
const char* v8::base::Thread::name () const [inline]
Definition at line 593 of file platform.h.
                                  {
    return name_;
  }
Referenced by set_name(), v8::base::SetThreadName(), and v8::base::ThreadEntry().
NotifyStartedAndRun()
void v8::base::Thread::NotifyStartedAndRun () [inline]
Definition at line 630 of file platform.h.
                             {
    if (start_semaphore_) start_semaphore_->Signal();
    Run();
  }
Referenced by v8::base::ThreadEntry().
operator=()
Thread& v8::base::Thread::operator= (const Thread &) [delete]
priority()
Priority v8::base::Thread::priority () const [inline]
Definition at line 628 of file platform.h.
{ return priority_; }
Referenced by v8::base::ThreadEntry().
Run()
virtual void v8::base::Thread::Run () [pure virtual]
Implemented in v8::internal::ProfilerEventsProcessor, v8::internal::SamplingEventsProcessor, v8::internal::Profiler, v8::internal::SamplingThread, v8::platform::DefaultWorkerThreadsTaskRunner::WorkerThread, v8::internal::wasm::gdb_server::GdbServerThread, v8::Worker::WorkerThread, v8::SourceGroup::IsolateThread, v8::StreamerThread, v8::internal::anonymous_namespace{compiler.cc}::StressBackgroundCompileThread, and v8::internal::anonymous_namespace{code-serializer.cc}::StressOffThreadDeserializeThread.
set_name()
void v8::base::Thread::set_name (const char * name) [private]
Definition at line 1275 of file platform-posix.cc.
                                      {
  strncpy(name_, name, sizeof(name_) - 1);
  name_[sizeof(name_) - 1] = '\0';
}
References name(), and name_.
Referenced by Thread().
SetThreadLocal()
void v8::base::Thread::SetThreadLocal (LocalStorageKey key, void * value) [static]
Definition at line 1377 of file platform-posix.cc.
                                                            {
  pthread_key_t pthread_key = LocalKeyToPthreadKey(key);
  int result = pthread_setspecific(pthread_key, value);
  DCHECK_EQ(0, result);
  USE(result);
}
References DCHECK_EQ, v8::internal::key, v8::base::LocalKeyToPthreadKey(), v8::base::internal::result, USE, and v8::internal::value.
Start()
bool v8::base::Thread::Start ()
Definition at line 1280 of file platform-posix.cc.
                   {
  int result;
  pthread_attr_t attr;
  memset(&attr, 0, sizeof(attr));
  result = pthread_attr_init(&attr);
  if (result != 0) return false;
  size_t stack_size = stack_size_;
  if (stack_size == 0) {
#if V8_OS_DARWIN
    // Default on Mac OS X is 512kB -- bump up to 1MB
    stack_size = 1 * 1024 * 1024;
#elif V8_OS_AIX
    // Default on AIX is 96kB -- bump up to 2MB
    stack_size = 2 * 1024 * 1024;
#endif
  }
  if (stack_size > 0) {
    result = pthread_attr_setstacksize(&attr, stack_size);
    if (result != 0) return pthread_attr_destroy(&attr), false;
  }
  {
    MutexGuard lock_guard(&data_->thread_creation_mutex_);
    result = pthread_create(&data_->thread_, &attr, ThreadEntry, this);
    if (result != 0 || data_->thread_ == kNoThread) {
      return pthread_attr_destroy(&attr), false;
    }
  }
  result = pthread_attr_destroy(&attr);
  return result == 0;
}
References data_, v8::base::kNoThread, v8::base::internal::result, stack_size_, v8::base::Thread::PlatformData::thread_, v8::base::Thread::PlatformData::thread_creation_mutex_, and v8::base::ThreadEntry().
Referenced by v8::internal::anonymous_namespace{compiler.cc}::CompileScriptOnBothBackgroundAndMainThread(), v8::internal::Profiler::Engage(), v8::internal::wasm::gdb_server::GdbServerThread::StartAndInitialize(), v8::SourceGroup::StartExecuteInThread(), v8::StreamerThread::StartThreadForTaskAndJoin(), and v8::platform::DefaultWorkerThreadsTaskRunner::WorkerThread::WorkerThread().
StartSynchronously()
bool v8::base::Thread::StartSynchronously () [inline]
Definition at line 581 of file platform.h.
                            {
    start_semaphore_ = new Semaphore(0);
    if (!Start()) return false;
    start_semaphore_->Wait();
    delete start_semaphore_;
    start_semaphore_ = nullptr;
    return true;
  }
Referenced by v8::internal::SamplingEventsProcessor::SetSamplingInterval().
Member Data Documentation
data_
PlatformData* v8::base::Thread::data_ [private]
Definition at line 638 of file platform.h.
Referenced by Join(), Start(), and ~Thread().
kMaxThreadNameLength
const int v8::base::Thread::kMaxThreadNameLength = 16 [static]
Definition at line 624 of file platform.h.
Referenced by v8::base::SetThreadName().
name_
char v8::base::Thread::name_[kMaxThreadNameLength] [private]
Definition at line 640 of file platform.h.
Referenced by set_name().
priority_
Priority v8::base::Thread::priority_ [private]
Definition at line 642 of file platform.h.
stack_size_
int v8::base::Thread::stack_size_ [private]
Definition at line 641 of file platform.h.
Referenced by Start(), and Thread().
start_semaphore_
Semaphore* v8::base::Thread::start_semaphore_ [private]
Definition at line 643 of file platform.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/base/platform/platform.h
/mnt/V8SourceCode/src/base/platform/platform-posix.cc
/mnt/V8SourceCode/src/base/platform/platform-starboard.cc
/mnt/V8SourceCode/src/base/platform/platform-win32.cc