v8::internal::BytecodeArray Class Reference
#include <bytecode-array.h>
Classes
class BodyDescriptor
Public Member Functions
int length () const
int length (AcquireLoadTag tag) const
void set_length (int value)
void set_length (int value, ReleaseStoreTag tag)
DECL_RELEASE_ACQUIRE_PROTECTED_POINTER_ACCESSORS (source_position_table, TrustedByteArray) inline int32_t max_frame_size() const
uint8_t get (int index) const
void set (int index, uint8_t value)
Address GetFirstBytecodeAddress ()
int register_count () const
uint16_t parameter_count () const
uint16_t parameter_count_without_receiver () const
void set_parameter_count (uint16_t number_of_parameters)
uint16_t max_arguments () const
void set_max_arguments (uint16_t max_arguments)
interpreter::Register incoming_new_target_or_generator_register () const
void set_incoming_new_target_or_generator_register (interpreter::Register incoming_new_target_or_generator_register)
bool HasSourcePositionTable () const
int SourcePosition (int offset) const
int SourceStatementPosition (int offset) const
void SetSourcePositionsFailedToCollect ()
int BytecodeArraySize () const
V8_EXPORT_PRIVATE void PrintJson (std::ostream &os)
V8_EXPORT_PRIVATE void Disassemble (std::ostream &os)
void CopyBytecodesTo (Tagged< BytecodeArray > to)
void clear_padding ()
OBJECT_CONSTRUCTORS (BytecodeArray, ExposedTrustedObject)
Static Public Member Functions
static constexpr int SizeFor (int length)
static V8_EXPORT_PRIVATE void Disassemble (Handle< BytecodeArray > handle, std::ostream &os)
Static Public Attributes
static const int kMaxSize = 512 * MB
static const int kMaxLength = kMaxSize - kHeaderSize
Additional Inherited Members
Detailed Description
Definition at line 28 of file bytecode-array.h.
Member Function Documentation
BytecodeArraySize()
int v8::internal::BytecodeArray::BytecodeArraySize () const [inline]
Definition at line 162 of file bytecode-array-inl.h.
{ return SizeFor(this->length()); }
References length(), and SizeFor().
clear_padding()
void v8::internal::BytecodeArray::clear_padding () [inline]
Definition at line 108 of file bytecode-array-inl.h.
                                  {
  int data_size = kHeaderSize + length();
  memset(reinterpret_cast<void*>(address() + data_size), 0,
         SizeFor(length()) - data_size);
}
References v8::internal::HeapObject::address(), v8::internal::ExposedTrustedObject::kHeaderSize, length(), and SizeFor().
CopyBytecodesTo()
void v8::internal::BytecodeArray::CopyBytecodesTo (Tagged< BytecodeArray > to)
Definition at line 190 of file bytecode-array.cc.
                                                            {
  BytecodeArray from = *this;
  DCHECK_EQ(from->length(), to->length());
  CopyBytes(reinterpret_cast<uint8_t*>(to->GetFirstBytecodeAddress()),
            reinterpret_cast<uint8_t*>(from->GetFirstBytecodeAddress()),
            from->length());
}
References v8::internal::CopyBytes(), DCHECK_EQ, GetFirstBytecodeAddress(), and length().
DECL_RELEASE_ACQUIRE_PROTECTED_POINTER_ACCESSORS()
v8::internal::BytecodeArray::DECL_RELEASE_ACQUIRE_PROTECTED_POINTER_ACCESSORS (source_position_table , TrustedByteArray) const
Disassemble() [1/2]
void v8::internal::BytecodeArray::Disassemble (Handle< BytecodeArray > handle, std::ostream & os) [static]
Definition at line 111 of file bytecode-array.cc.
                                                {
  DisallowGarbageCollection no_gc;
  os << "Parameter count " << handle->parameter_count() << "\n";
  os << "Register count " << handle->register_count() << "\n";
  os << "Frame size " << handle->frame_size() << "\n";
  Address base_address = handle->GetFirstBytecodeAddress();
  SourcePositionTableIterator source_positions(handle->SourcePositionTable());
  interpreter::BytecodeArrayIterator iterator(handle);
  while (!iterator.done()) {
    if (!source_positions.done() &&
        iterator.current_offset() == source_positions.code_offset()) {
      os << std::setw(5) << source_positions.source_position().ScriptOffset();
      if (source_positions.is_breakable()) {
        os << (source_positions.is_statement() ? " S> " : " E> ");
      } else {
        os << (source_positions.is_statement() ? " s> " : " e> ");
      }
      source_positions.Advance();
    } else {
      os << " ";
    }
    Address current_address = base_address + iterator.current_offset();
    os << reinterpret_cast<const void*>(current_address) << " @ "
       << std::setw(4) << iterator.current_offset() << " : ";
    interpreter::BytecodeDecoder::Decode(
        os, reinterpret_cast<uint8_t*>(current_address));
    if (interpreter::Bytecodes::IsJump(iterator.current_bytecode())) {
      Address jump_target = base_address + iterator.GetJumpTargetOffset();
      os << " (" << reinterpret_cast<void*>(jump_target) << " @ "
         << iterator.GetJumpTargetOffset() << ")";
    }
    if (interpreter::Bytecodes::IsSwitch(iterator.current_bytecode())) {
      os << " {";
      bool first_entry = true;
      for (interpreter::JumpTableTargetOffset entry :
           iterator.GetJumpTableTargetOffsets()) {
        if (first_entry) {
          first_entry = false;
        } else {
          os << ",";
        }
        os << " " << entry.case_value << ": @" << entry.target_offset;
      }
      os << " }";
    }
    os << std::endl;
    iterator.Advance();
  }
  os << "Constant pool (size = " << handle->constant_pool()->length() << ")\n";
#ifdef OBJECT_PRINT
  if (handle->constant_pool()->length() > 0) {
    Print(handle->constant_pool(), os);
  }
#endif
  os << "Handler Table (size = " << handle->handler_table()->length() << ")\n";
#ifdef ENABLE_DISASSEMBLER
  if (handle->handler_table()->length() > 0) {
    HandlerTable table(*handle);
    table.HandlerTableRangePrint(os);
  }
#endif
  Tagged<TrustedByteArray> source_position_table =
      handle->SourcePositionTable();
  os << "Source Position Table (size = " << source_position_table->length()
     << ")\n";
#ifdef OBJECT_PRINT
  if (source_position_table->length() > 0) {
    os << Brief(source_position_table) << std::endl;
  }
#endif
}
References v8::internal::SourcePositionTableIterator::Advance(), v8::internal::interpreter::BytecodeArrayIterator::Advance(), v8::internal::SourcePositionTableIterator::code_offset(), v8::internal::interpreter::BytecodeArrayIterator::current_bytecode(), v8::internal::interpreter::BytecodeArrayIterator::current_offset(), v8::internal::interpreter::BytecodeDecoder::Decode(), v8::internal::SourcePositionTableIterator::done(), v8::internal::interpreter::BytecodeArrayIterator::done(), v8::internal::interpreter::BytecodeArrayIterator::GetJumpTableTargetOffsets(), v8::internal::interpreter::BytecodeArrayIterator::GetJumpTargetOffset(), v8::internal::handle(), v8::internal::SourcePositionTableIterator::is_breakable(), v8::internal::SourcePositionTableIterator::is_statement(), v8::internal::interpreter::Bytecodes::IsJump(), v8::internal::interpreter::Bytecodes::IsSwitch(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::HeapObject::Print(), v8::internal::SourcePosition::ScriptOffset(), and v8::internal::SourcePositionTableIterator::source_position().
Disassemble() [2/2]
void v8::internal::BytecodeArray::Disassemble (std::ostream & os)
Definition at line 101 of file bytecode-array.cc.
                                              {
  DisallowGarbageCollection no_gc;
  // Storage for backing the handle passed to the iterator. This handle won't be
  // updated by the gc, but that's ok because we've disallowed GCs anyway.
  BytecodeArray handle_storage = *this;
  Handle<BytecodeArray> handle(reinterpret_cast<Address*>(&handle_storage));
  Disassemble(handle, os);
}
References v8::internal::handle(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildInlineFunction(), and v8::internal::maglev::MaglevCompiler::Compile().
get()
uint8_t v8::internal::BytecodeArray::get (int index) const [inline]
GetFirstBytecodeAddress()
Address v8::internal::BytecodeArray::GetFirstBytecodeAddress () [inline]
Definition at line 114 of file bytecode-array-inl.h.
                                               {
  return ptr() - kHeapObjectTag + kHeaderSize;
}
References v8::internal::ExposedTrustedObject::kHeaderSize, v8::internal::kHeapObjectTag, and v8::internal::TaggedImpl< HeapObjectReferenceType::STRONG, Address >::ptr().
Referenced by CopyBytecodesTo(), and PrintJson().
HasSourcePositionTable()
bool v8::internal::BytecodeArray::HasSourcePositionTable () const [inline]
Definition at line 118 of file bytecode-array-inl.h.
                                                 {
  return has_source_position_table(kAcquireLoad);
}
References v8::kAcquireLoad.
Referenced by SourcePosition(), and SourceStatementPosition().
incoming_new_target_or_generator_register()
interpreter::Register v8::internal::BytecodeArray::incoming_new_target_or_generator_register () const [inline]
Definition at line 84 of file bytecode-array-inl.h.
          {
  int32_t register_operand =
      ReadField<int32_t>(kIncomingNewTargetOrGeneratorRegisterOffset);
  if (register_operand == 0) {
    return interpreter::Register::invalid_value();
  } else {
    return interpreter::Register::FromOperand(register_operand);
  }
}
References v8::internal::interpreter::Register::FromOperand(), and v8::internal::interpreter::Register::invalid_value().
Referenced by set_incoming_new_target_or_generator_register().
length() [1/2]
int v8::internal::BytecodeArray::length () const [inline]
Referenced by BytecodeArraySize(), clear_padding(), CopyBytecodesTo(), SizeFor(), and v8::internal::BytecodeArray::BodyDescriptor::SizeOf().
length() [2/2]
int v8::internal::BytecodeArray::length (AcquireLoadTag tag) const [inline]
max_arguments()
uint16_t v8::internal::BytecodeArray::max_arguments () const [inline]
Definition at line 72 of file bytecode-array-inl.h.
                                            {
  return ReadField<uint16_t>(kMaxArgumentsOffset);
}
Referenced by set_max_arguments().
OBJECT_CONSTRUCTORS()
v8::internal::BytecodeArray::OBJECT_CONSTRUCTORS (BytecodeArray , ExposedTrustedObject)
parameter_count()
uint16_t v8::internal::BytecodeArray::parameter_count () const [inline]
Definition at line 60 of file bytecode-array-inl.h.
                                              {
  return ReadField<uint16_t>(kParameterSizeOffset);
}
Referenced by parameter_count_without_receiver().
parameter_count_without_receiver()
uint16_t v8::internal::BytecodeArray::parameter_count_without_receiver () const [inline]
Definition at line 64 of file bytecode-array-inl.h.
                                                               {
  return parameter_count() - 1;
}
References parameter_count().
PrintJson()
void v8::internal::BytecodeArray::PrintJson (std::ostream & os)
Definition at line 45 of file bytecode-array.cc.
                                            {
  DisallowGarbageCollection no_gc;
  Address base_address = GetFirstBytecodeAddress();
  BytecodeArray handle_storage = *this;
  Handle<BytecodeArray> handle(reinterpret_cast<Address*>(&handle_storage));
  interpreter::BytecodeArrayIterator iterator(handle);
  bool first_data = true;
  os << "{\"data\": [";
  while (!iterator.done()) {
    if (!first_data) os << ", ";
    Address current_address = base_address + iterator.current_offset();
    first_data = false;
    os << "{\"offset\":" << iterator.current_offset() << ", \"disassembly\":\"";
    interpreter::BytecodeDecoder::Decode(
        os, reinterpret_cast<uint8_t*>(current_address), false);
    if (interpreter::Bytecodes::IsJump(iterator.current_bytecode())) {
      os << " (" << iterator.GetJumpTargetOffset() << ")";
    }
    if (interpreter::Bytecodes::IsSwitch(iterator.current_bytecode())) {
      os << " {";
      bool first_entry = true;
      for (interpreter::JumpTableTargetOffset entry :
           iterator.GetJumpTableTargetOffsets()) {
        if (!first_entry) os << ", ";
        first_entry = false;
        os << entry.target_offset;
      }
      os << "}";
    }
    os << "\"}";
    iterator.Advance();
  }
  os << "]";
  int constant_pool_length = constant_pool()->length();
  if (constant_pool_length > 0) {
    os << ", \"constantPool\": [";
    for (int i = 0; i < constant_pool_length; i++) {
      Tagged<Object> object = constant_pool()->get(i);
      if (i > 0) os << ", ";
      os << "\"" << object << "\"";
    }
    os << "]";
  }
  os << "}";
}
References v8::internal::interpreter::BytecodeArrayIterator::Advance(), v8::internal::constant_pool, v8::internal::interpreter::BytecodeArrayIterator::current_bytecode(), v8::internal::interpreter::BytecodeArrayIterator::current_offset(), v8::internal::interpreter::BytecodeDecoder::Decode(), v8::internal::interpreter::BytecodeArrayIterator::done(), GetFirstBytecodeAddress(), v8::internal::interpreter::BytecodeArrayIterator::GetJumpTableTargetOffsets(), v8::internal::interpreter::BytecodeArrayIterator::GetJumpTargetOffset(), v8::internal::handle(), v8::internal::interpreter::Bytecodes::IsJump(), v8::internal::interpreter::Bytecodes::IsSwitch(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
register_count()
int v8::internal::BytecodeArray::register_count () const [inline]
Definition at line 56 of file bytecode-array-inl.h.
                                        {
  return static_cast<int>(frame_size()) / kSystemPointerSize;
}
References v8::internal::kSystemPointerSize.
Referenced by set_incoming_new_target_or_generator_register().
set()
void v8::internal::BytecodeArray::set (int index, uint8_t value) [inline]
set_incoming_new_target_or_generator_register()
void v8::internal::BytecodeArray::set_incoming_new_target_or_generator_register (interpreter::Register incoming_new_target_or_generator_register) [inline]
Definition at line 95 of file bytecode-array-inl.h.
                                                                   {
  if (!incoming_new_target_or_generator_register.is_valid()) {
    WriteField<int32_t>(kIncomingNewTargetOrGeneratorRegisterOffset, 0);
  } else {
    DCHECK(incoming_new_target_or_generator_register.index() <
           register_count());
    DCHECK_NE(0, incoming_new_target_or_generator_register.ToOperand());
    WriteField<int32_t>(kIncomingNewTargetOrGeneratorRegisterOffset,
                        incoming_new_target_or_generator_register.ToOperand());
  }
}
References v8::internal::DCHECK(), DCHECK_NE, incoming_new_target_or_generator_register(), v8::internal::interpreter::Register::index(), v8::internal::interpreter::Register::is_valid(), register_count(), and v8::internal::interpreter::Register::ToOperand().
set_length() [1/2]
void v8::internal::BytecodeArray::set_length (int value) [inline]
set_length() [2/2]
void v8::internal::BytecodeArray::set_length (int value, ReleaseStoreTag tag) [inline]
set_max_arguments()
void v8::internal::BytecodeArray::set_max_arguments (uint16_t max_arguments) [inline]
Definition at line 76 of file bytecode-array-inl.h.
                                                            {
  WriteField<uint16_t>(kMaxArgumentsOffset, max_arguments);
}
References max_arguments().
set_parameter_count()
void v8::internal::BytecodeArray::set_parameter_count (uint16_t number_of_parameters) [inline]
Definition at line 68 of file bytecode-array-inl.h.
                                                                     {
  WriteField<uint16_t>(kParameterSizeOffset, number_of_parameters);
}
SetSourcePositionsFailedToCollect()
void v8::internal::BytecodeArray::SetSourcePositionsFailedToCollect () [inline]
Definition at line 134 of file bytecode-array-inl.h.
                                                      {
  TaggedField<Object>::Release_Store(*this, kSourcePositionTableOffset,
                                     Smi::zero());
}
References v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Release_Store(), and v8::internal::Smi::zero().
SizeFor()
static constexpr int v8::internal::BytecodeArray::SizeFor (int length) [inline], [static], [constexpr]
Definition at line 62 of file bytecode-array.h.
                                           {
    return OBJECT_POINTER_ALIGN(kHeaderSize + length);
  }
References v8::internal::ExposedTrustedObject::kHeaderSize, length(), and OBJECT_POINTER_ALIGN.
Referenced by BytecodeArraySize(), clear_padding(), v8::internal::Factory::CopyBytecodeArray(), v8::internal::HeapObject::SizeFromMap(), and v8::internal::BytecodeArray::BodyDescriptor::SizeOf().
SourcePosition()
int v8::internal::BytecodeArray::SourcePosition (int offset) const
Definition at line 20 of file bytecode-array.cc.
                                                  {
  int position = 0;
  if (!HasSourcePositionTable()) return position;
  for (SourcePositionTableIterator it(
           source_position_table(kAcquireLoad),
           SourcePositionTableIterator::kJavaScriptOnly,
           SourcePositionTableIterator::kDontSkipFunctionEntry);
       !it.done() && it.code_offset() <= offset; it.Advance()) {
    position = it.source_position().ScriptOffset();
  }
  return position;
}
References v8::internal::SourcePositionTableIterator::done(), HasSourcePositionTable(), v8::kAcquireLoad, v8::internal::SourcePositionTableIterator::kDontSkipFunctionEntry, and v8::internal::SourcePositionTableIterator::kJavaScriptOnly.
SourceStatementPosition()
int v8::internal::BytecodeArray::SourceStatementPosition (int offset) const
Definition at line 33 of file bytecode-array.cc.
                                                           {
  int position = 0;
  if (!HasSourcePositionTable()) return position;
  for (SourcePositionTableIterator it(source_position_table(kAcquireLoad));
       !it.done() && it.code_offset() <= offset; it.Advance()) {
    if (it.is_statement()) {
      position = it.source_position().ScriptOffset();
    }
  }
  return position;
}
References v8::internal::SourcePositionTableIterator::done(), HasSourcePositionTable(), and v8::kAcquireLoad.
Member Data Documentation
kMaxLength
const int v8::internal::BytecodeArray::kMaxLength = kMaxSize - kHeaderSize [static]
Definition at line 131 of file bytecode-array.h.
Referenced by v8::internal::FactoryBase< Impl >::NewBytecodeArray().
kMaxSize
const int v8::internal::BytecodeArray::kMaxSize = 512 * MB [static]
Definition at line 129 of file bytecode-array.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/bytecode-array.h
/mnt/V8SourceCode/src/objects/bytecode-array-inl.h
/mnt/V8SourceCode/src/objects/bytecode-array.cc