v8::internal::NumberParseIntHelper Class Reference
Public Member Functions
NumberParseIntHelper (DirectHandle< String > string, int radix)
NumberParseIntHelper (const uint8_t *string, int radix, size_t length)
NumberParseIntHelper (const base::uc16 *string, int radix, size_t length)
template<class Char >
void ParseInternal (const Char *start)
void ParseOneByte (const uint8_t *start) final
void ParseTwoByte (const base::uc16 *start) final
double GetResult ()
Private Member Functions
template<class Char >
void HandleGenericCase (const Char *current, const Char *end)
template<class Char >
double HandlePowerOfTwoCase (const Char *current, const Char *end)
template<class Char >
void HandleBaseTenCase (const Char *current, const Char *end)
Private Attributes
double result_ = 0
Additional Inherited Members
Detailed Description
Definition at line 674 of file conversions.cc.
Constructor & Destructor Documentation
NumberParseIntHelper() [1/3]
v8::internal::NumberParseIntHelper::NumberParseIntHelper (DirectHandle< String > string, int radix) [inline]
Definition at line 676 of file conversions.cc.
      : StringToIntHelper(string, radix) {}
NumberParseIntHelper() [2/3]
v8::internal::NumberParseIntHelper::NumberParseIntHelper (const uint8_t * string, int radix, size_t length) [inline]
Definition at line 679 of file conversions.cc.
      : StringToIntHelper(string, radix, length) {}
NumberParseIntHelper() [3/3]
v8::internal::NumberParseIntHelper::NumberParseIntHelper (const base::uc16 * string, int radix, size_t length) [inline]
Definition at line 682 of file conversions.cc.
      : StringToIntHelper(string, radix, length) {}
Member Function Documentation
GetResult()
double v8::internal::NumberParseIntHelper::GetResult () [inline]
Definition at line 703 of file conversions.cc.
                     {
    ParseInt();
    switch (state()) {
      case State::kJunk:
      case State::kEmpty:
        return JunkStringValue();
      case State::kZero:
        return SignedZero(negative());
      case State::kDone:
        return negative() ? -result_ : result_;
      case State::kError:
      case State::kRunning:
        break;
    }
    UNREACHABLE();
  }
References v8::internal::JunkStringValue(), v8::internal::swiss_table::kEmpty, v8::internal::kZero, v8::internal::StringToIntHelper::negative(), v8::internal::StringToIntHelper::ParseInt(), result_, v8::internal::SignedZero(), v8::internal::StringToIntHelper::state(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::StringToInt(), and v8::internal::TryStringToInt().
HandleBaseTenCase()
template<class Char >
void v8::internal::NumberParseIntHelper::HandleBaseTenCase (const Char * current, const Char * end) [inline], [private]
Definition at line 753 of file conversions.cc.
                                                               {
    // Parsing with strtod.
    // Doubles are less than 1.8e308.
    constexpr size_t kMaxSignificantDigits = 309;
    // The buffer may contain up to kMaxSignificantDigits + 1 digits and a zero
    // end.
    constexpr size_t kBufferSize = kMaxSignificantDigits + 2;
    char buffer[kBufferSize];
    size_t buffer_pos = 0;
    while (*current >= '0' && *current <= '9') {
      if (buffer_pos <= kMaxSignificantDigits) {
        // If the number has more than kMaxSignificantDigits it will be parsed
        // as infinity.
        static_assert(kMaxSignificantDigits < kBufferSize);
        buffer[buffer_pos++] = static_cast<char>(*current);
      }
      ++current;
      if (current == end) break;
    }
    SLOW_DCHECK(buffer_pos < kBufferSize);
    buffer[buffer_pos] = '\0';
    base::Vector<const char> buffer_vector(buffer, buffer_pos);
    result_ = Strtod(buffer_vector, 0);
    set_state(State::kDone);
  }
References v8::internal::compiler::end(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::kBufferSize, result_, v8::internal::StringToIntHelper::set_state(), SLOW_DCHECK, and v8::base::Strtod().
Referenced by ParseInternal().
HandleGenericCase()
template<class Char >
void v8::internal::NumberParseIntHelper::HandleGenericCase (const Char * current, const Char * end) [private]
Definition at line 784 of file conversions.cc.
                                                              {
  // The following code causes accumulating rounding error for numbers greater
  // than ~2^56. It's explicitly allowed in the spec: "if R is not 2, 4, 8, 10,
  // 16, or 32, then mathInt may be an implementation-dependent approximation to
  // the mathematical integer value" (15.1.2.2).
  int lim_0 = '0' + (radix() < 10 ? radix() : 10);
  int lim_a = 'a' + (radix() - 10);
  int lim_A = 'A' + (radix() - 10);
  // NOTE: The code for computing the value may seem a bit complex at
  // first glance. It is structured to use 32-bit multiply-and-add
  // loops as long as possible to avoid losing precision.
  bool done = false;
  do {
    // Parse the longest part of the string starting at {current}
    // possible while keeping the multiplier, and thus the part
    // itself, within 32 bits.
    uint32_t part = 0, multiplier = 1;
    while (true) {
      uint32_t d;
      if (*current >= '0' && *current < lim_0) {
        d = *current - '0';
      } else if (*current >= 'a' && *current < lim_a) {
        d = *current - 'a' + 10;
      } else if (*current >= 'A' && *current < lim_A) {
        d = *current - 'A' + 10;
      } else {
        done = true;
        break;
      }
      // Update the value of the part as long as the multiplier fits
      // in 32 bits. When we can't guarantee that the next iteration
      // will not overflow the multiplier, we stop parsing the part
      // by leaving the loop.
      const uint32_t kMaximumMultiplier = kMaxUInt32 / 36;
      uint32_t m = multiplier * static_cast<uint32_t>(radix());
      if (m > kMaximumMultiplier) break;
      part = part * radix() + d;
      multiplier = m;
      DCHECK(multiplier > part);
      ++current;
      if (current == end) {
        done = true;
        break;
      }
    }
    result_ = result_ * multiplier + part;
  } while (!done);
  if (!allow_trailing_junk() && AdvanceToNonspace(&current, end)) {
    return set_state(State::kJunk);
  }
  return set_state(State::kDone);
}
References v8::internal::AdvanceToNonspace(), v8::internal::StringToIntHelper::allow_trailing_junk(), v8::internal::DCHECK(), v8::internal::compiler::end(), v8::internal::kMaxUInt32, v8::internal::StringToIntHelper::radix(), result_, and v8::internal::StringToIntHelper::set_state().
Referenced by ParseInternal().
HandlePowerOfTwoCase()
template<class Char >
double v8::internal::NumberParseIntHelper::HandlePowerOfTwoCase (const Char * current, const Char * end) [inline], [private]
Definition at line 725 of file conversions.cc.
                                                                    {
    const bool allow_trailing_junk = true;
    // GetResult() will take care of the sign bit, so ignore it for now.
    const bool negative = false;
    switch (radix()) {
      case 2:
        return InternalStringToIntDouble<1>(current, end, negative,
                                            allow_trailing_junk);
      case 4:
        return InternalStringToIntDouble<2>(current, end, negative,
                                            allow_trailing_junk);
      case 8:
        return InternalStringToIntDouble<3>(current, end, negative,
                                            allow_trailing_junk);
      case 16:
        return InternalStringToIntDouble<4>(current, end, negative,
                                            allow_trailing_junk);
      case 32:
        return InternalStringToIntDouble<5>(current, end, negative,
                                            allow_trailing_junk);
      default:
        UNREACHABLE();
    }
  }
References v8::internal::StringToIntHelper::allow_trailing_junk(), v8::internal::compiler::end(), v8::internal::StringToIntHelper::negative(), v8::internal::StringToIntHelper::radix(), and v8::internal::UNREACHABLE().
Referenced by ParseInternal().
ParseInternal()
template<class Char >
void v8::internal::NumberParseIntHelper::ParseInternal (const Char * start) [inline]
Definition at line 686 of file conversions.cc.
                                        {
    const Char* current = start + cursor();
    const Char* end = start + length();
    if (radix() == 10) return HandleBaseTenCase(current, end);
    if (base::bits::IsPowerOfTwo(radix())) {
      result_ = HandlePowerOfTwoCase(current, end);
      set_state(State::kDone);
      return;
    }
    return HandleGenericCase(current, end);
  }
References v8::internal::StringToIntHelper::cursor(), v8::internal::compiler::end(), HandleBaseTenCase(), HandleGenericCase(), HandlePowerOfTwoCase(), v8::base::bits::IsPowerOfTwo(), v8::internal::StringToIntHelper::length(), v8::internal::StringToIntHelper::radix(), result_, and v8::internal::StringToIntHelper::set_state().
Referenced by ParseOneByte(), and ParseTwoByte().
ParseOneByte()
void v8::internal::NumberParseIntHelper::ParseOneByte (const uint8_t * start) [inline], [final], [virtual]
Implements v8::internal::StringToIntHelper.
Definition at line 698 of file conversions.cc.
{ return ParseInternal(start); }
References ParseInternal().
ParseTwoByte()
void v8::internal::NumberParseIntHelper::ParseTwoByte (const base::uc16 * start) [inline], [final], [virtual]
Implements v8::internal::StringToIntHelper.
Definition at line 699 of file conversions.cc.
                                                 {
    return ParseInternal(start);
  }
References ParseInternal().
Member Data Documentation
result_
double v8::internal::NumberParseIntHelper::result_ = 0 [private]
Definition at line 780 of file conversions.cc.
Referenced by GetResult(), HandleBaseTenCase(), HandleGenericCase(), and ParseInternal().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/numbers/conversions.cc