v8::internal::StrongRootAllocatorBase Class Reference
#include <v8-internal.h>
Public Member Functions
Heap * heap () const
Protected Member Functions
StrongRootAllocatorBase (Heap *heap)
StrongRootAllocatorBase (LocalHeap *heap)
StrongRootAllocatorBase (Isolate *isolate)
StrongRootAllocatorBase (v8::Isolate *isolate)
StrongRootAllocatorBase (LocalIsolate *isolate)
Address * allocate_impl (size_t n)
void deallocate_impl (Address *p, size_t n) noexcept
Private Attributes
Heap * heap_
Friends
bool operator== (const StrongRootAllocatorBase &a, const StrongRootAllocatorBase &b)
Detailed Description
Definition at line 1398 of file v8-internal.h.
Constructor & Destructor Documentation
StrongRootAllocatorBase() [1/5]
v8::internal::StrongRootAllocatorBase::StrongRootAllocatorBase (Heap * heap) [inline], [explicit], [protected]
Definition at line 1410 of file v8-internal.h.
: heap_(heap) {}
StrongRootAllocatorBase() [2/5]
v8::internal::StrongRootAllocatorBase::StrongRootAllocatorBase (LocalHeap * heap) [explicit], [protected]
Definition at line 7405 of file heap.cc.
    : StrongRootAllocatorBase(heap->heap()) {}
StrongRootAllocatorBase() [3/5]
v8::internal::StrongRootAllocatorBase::StrongRootAllocatorBase (Isolate * isolate) [explicit], [protected]
Definition at line 7407 of file heap.cc.
    : StrongRootAllocatorBase(isolate->heap()) {}
StrongRootAllocatorBase() [4/5]
v8::internal::StrongRootAllocatorBase::StrongRootAllocatorBase (v8::Isolate * isolate) [explicit], [protected]
Definition at line 7409 of file heap.cc.
    : StrongRootAllocatorBase(reinterpret_cast<Isolate*>(isolate)) {}
StrongRootAllocatorBase() [5/5]
v8::internal::StrongRootAllocatorBase::StrongRootAllocatorBase (LocalIsolate * isolate) [explicit], [protected]
Definition at line 7411 of file heap.cc.
    : StrongRootAllocatorBase(isolate->heap()) {}
Member Function Documentation
allocate_impl()
Address * v8::internal::StrongRootAllocatorBase::allocate_impl (size_t n) [protected]
Definition at line 7425 of file heap.cc.
                                                        {
  void* block = base::Malloc(sizeof(StrongRootsEntry*) + n * sizeof(Address));
  StrongRootsEntry** header = reinterpret_cast<StrongRootsEntry**>(block);
  Address* ret = reinterpret_cast<Address*>(reinterpret_cast<char*>(block) +
                                            sizeof(StrongRootsEntry*));
  memset(ret, kNullAddress, n * sizeof(Address));
  *header = heap()->RegisterStrongRoots(
      "StrongRootAllocator", FullObjectSlot(ret), FullObjectSlot(ret + n));
  return ret;
}
References heap(), v8::internal::kNullAddress, v8::base::Malloc(), and v8::internal::Heap::RegisterStrongRoots().
deallocate_impl()
void v8::internal::StrongRootAllocatorBase::deallocate_impl (Address * p, size_t n) [protected], [noexcept]
Definition at line 7439 of file heap.cc.
                                                                           {
  // The allocate method returns a pointer to Address 1, so the deallocate
  // method has to offset that pointer back by sizeof(StrongRootsEntry*).
  void* block = reinterpret_cast<char*>(p) - sizeof(StrongRootsEntry*);
  StrongRootsEntry** header = reinterpret_cast<StrongRootsEntry**>(block);
  heap()->UnregisterStrongRoots(*header);
  base::Free(block);
}
References v8::base::Free(), and heap().
heap()
Heap* v8::internal::StrongRootAllocatorBase::heap () const [inline]
Definition at line 1400 of file v8-internal.h.
{ return heap_; }
Referenced by allocate_impl().
Friends And Related Function Documentation
operator==
bool operator== (const StrongRootAllocatorBase & a, const StrongRootAllocatorBase & b) [friend]
Definition at line 1402 of file v8-internal.h.
                                                           {
    // TODO(pkasting): Replace this body with `= default` after dropping support
    // for old gcc versions.
    return a.heap_ == b.heap_;
  }
Member Data Documentation
heap_
Heap* v8::internal::StrongRootAllocatorBase::heap_ [private]
Definition at line 1421 of file v8-internal.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-internal.h
/mnt/V8SourceCode/src/heap/heap.cc