v8::internal::WeakArrayList Class Reference
#include <fixed-array.h>
Classes
class Iterator
Public Member Functions
V8_EXPORT_PRIVATE void Compact (Isolate *isolate)
Tagged< MaybeObject > Get (int index) const
Tagged< MaybeObject > Get (PtrComprCageBase cage_base, int index) const
Tagged< MaybeObject > get (int index) const
void Set (int index, Tagged< MaybeObject > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
void Set (int index, Tagged< Smi > value)
int capacity (RelaxedLoadTag) const
MaybeObjectSlot data_start ()
void CopyElements (Isolate *isolate, int dst_index, Tagged< WeakArrayList > src, int src_index, int len, WriteBarrierMode mode)
V8_EXPORT_PRIVATE bool IsFull () const
int AllocatedSize () const
int CountLiveWeakReferences () const
int CountLiveElements () const
V8_EXPORT_PRIVATE bool RemoveOne (MaybeObjectDirectHandle value)
V8_EXPORT_PRIVATE bool Contains (Tagged< MaybeObject > value)
Static Public Member Functions
static V8_EXPORT_PRIVATE Handle< WeakArrayList > AddToEnd (Isolate *isolate, Handle< WeakArrayList > array, MaybeObjectDirectHandle value)
static V8_EXPORT_PRIVATE Handle< WeakArrayList > AddToEnd (Isolate *isolate, Handle< WeakArrayList > array, MaybeObjectDirectHandle value1, Tagged< Smi > value2)
static V8_WARN_UNUSED_RESULT DirectHandle< WeakArrayList > Append (Isolate *isolate, DirectHandle< WeakArrayList > array, MaybeObjectDirectHandle value, AllocationType allocation=AllocationType::kYoung)
static constexpr int SizeForCapacity (int capacity)
static constexpr int CapacityForLength (int length)
static Handle< WeakArrayList > EnsureSpace (Isolate *isolate, Handle< WeakArrayList > array, int length, AllocationType allocation=AllocationType::kYoung)
Static Public Attributes
static constexpr int kMaxCapacity = kMaxFixedArrayCapacity
Static Private Member Functions
static int OffsetOfElementAt (int index)
Detailed Description
Definition at line 584 of file fixed-array.h.
Member Function Documentation
AddToEnd() [1/2]
Handle< WeakArrayList > v8::internal::WeakArrayList::AddToEnd (Isolate * isolate, Handle< WeakArrayList > array, MaybeObjectDirectHandle value) [static]
Definition at line 166 of file fixed-array.cc.
                                                                             {
  int length = array->length();
  array = EnsureSpace(isolate, array, length + 1);
  {
    DisallowGarbageCollection no_gc;
    Tagged<WeakArrayList> raw = *array;
    // Reload length; GC might have removed elements from the array.
    length = raw->length();
    raw->Set(length, *value);
    raw->set_length(length + 1);
  }
  return array;
}
References EnsureSpace(), v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::value.
Referenced by v8::internal::Isolate::AddDetachedContext(), v8::internal::ObjectDeserializer::CommitPostProcessedObjects(), v8::internal::CodeSerializer::FinishOffThreadDeserialize(), and v8::internal::DependentCode::InsertWeakCode().
AddToEnd() [2/2]
Handle< WeakArrayList > v8::internal::WeakArrayList::AddToEnd (Isolate * isolate, Handle< WeakArrayList > array, MaybeObjectDirectHandle value1, Tagged< Smi > value2) [static]
Definition at line 182 of file fixed-array.cc.
                                                                  {
  int length = array->length();
  array = EnsureSpace(isolate, array, length + 2);
  {
    DisallowGarbageCollection no_gc;
    Tagged<WeakArrayList> raw = *array;
    // Reload length; GC might have removed elements from the array.
    length = array->length();
    raw->Set(length, *value1);
    raw->Set(length + 1, value2);
    raw->set_length(length + 2);
  }
  return array;
}
References EnsureSpace(), v8::internal::length, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
AllocatedSize()
int v8::internal::WeakArrayList::AllocatedSize () const [inline]
Definition at line 443 of file fixed-array-inl.h.
                                              {
  return SizeFor(capacity(kRelaxedLoad));
}
References capacity(), and v8::kRelaxedLoad.
Append()
DirectHandle< WeakArrayList > v8::internal::WeakArrayList::Append (Isolate * isolate, DirectHandle< WeakArrayList > array, MaybeObjectDirectHandle value, AllocationType allocation = AllocationType::kYoung) [static]
Definition at line 201 of file fixed-array.cc.
                                                              {
  int length = 0;
  int new_length = 0;
  {
    DisallowGarbageCollection no_gc;
    Tagged<WeakArrayList> raw = *array;
    length = raw->length();
    if (length < raw->capacity()) {
      raw->Set(length, *value);
      raw->set_length(length + 1);
      return array;
    }
    // Not enough space in the array left, either grow, shrink or
    // compact the array.
    new_length = raw->CountLiveElements() + 1;
  }
  bool shrink = new_length < length / 4;
  bool grow = 3 * (length / 4) < new_length;
  if (shrink || grow) {
    // Grow or shrink array and compact out-of-place.
    int new_capacity = CapacityForLength(new_length);
    array = isolate->factory()->CompactWeakArrayList(array, new_capacity,
                                                     allocation);
  } else {
    // Perform compaction in the current array.
    array->Compact(isolate);
  }
  // Now append value to the array, there should always be enough space now.
  DCHECK_LT(array->length(), array->capacity());
  {
    DisallowGarbageCollection no_gc;
    Tagged<WeakArrayList> raw = *array;
    // Reload length, allocation might have killed some weak refs.
    int index = raw->length();
    raw->Set(index, *value);
    raw->set_length(index + 1);
  }
  return array;
}
References capacity(), CapacityForLength(), v8::internal::Factory::CompactWeakArrayList(), DCHECK_LT, v8::internal::Isolate::factory(), v8::internal::index, v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::value.
Referenced by v8::internal::BackgroundCompileTask::FinalizeScript(), v8::internal::WasmTrustedInstanceData::New(), v8::internal::Factory::ProcessNewScript(), and v8::internal::WasmMemoryObject::UseInInstance().
capacity()
int v8::internal::WeakArrayList::capacity (RelaxedLoadTag) const [inline]
Definition at line 396 of file fixed-array-inl.h.
                                                       {
  int value = TaggedField<Smi>::Relaxed_Load(*this, kCapacityOffset).value();
  return value;
}
References v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Relaxed_Load(), and v8::internal::value.
Referenced by AllocatedSize(), Append(), CopyElements(), EnsureSpace(), Get(), IsFull(), and v8::internal::ArrayList::New().
CapacityForLength()
static constexpr int v8::internal::WeakArrayList::CapacityForLength (int length) [inline], [static], [constexpr]
Definition at line 630 of file fixed-array.h.
                                                     {
    return length + std::max(length / 2, 2);
  }
References v8::internal::length.
Referenced by Append(), and EnsureSpace().
Compact()
void v8::internal::WeakArrayList::Compact (Isolate * isolate)
Definition at line 250 of file fixed-array.cc.
                                            {
  DisallowGarbageCollection no_gc;
  int length = this->length();
  int new_length = 0;
  for (int i = 0; i < length; i++) {
    Tagged<MaybeObject> value = Get(isolate, i);
    if (!value.IsCleared()) {
      if (new_length != i) {
        Set(new_length, value);
      }
      ++new_length;
    }
  }
  set_length(new_length);
}
References Get(), v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, Set(), and v8::internal::value.
Contains()
bool v8::internal::WeakArrayList::Contains (Tagged< MaybeObject > value)
Definition at line 322 of file fixed-array.cc.
                                                      {
  for (int i = 0; i < length(); ++i) {
    if (Get(i) == value) return true;
  }
  return false;
}
References Get(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::length, and v8::internal::value.
CopyElements()
void v8::internal::WeakArrayList::CopyElements (Isolate * isolate, int dst_index, Tagged< WeakArrayList > src, int src_index, int len, WriteBarrierMode mode) [inline]
Definition at line 700 of file fixed-array-inl.h.
                                                                 {
  if (len == 0) return;
  DCHECK_LE(dst_index + len, capacity());
  DCHECK_LE(src_index + len, src->capacity());
  DisallowGarbageCollection no_gc;
  MaybeObjectSlot dst_slot(data_start() + dst_index);
  MaybeObjectSlot src_slot(src->data_start() + src_index);
  isolate->heap()->CopyRange(*this, dst_slot, src_slot, len, mode);
}
References capacity(), v8::internal::Heap::CopyRange(), data_start(), DCHECK_LE, v8::internal::Isolate::heap(), mode(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
CountLiveElements()
int v8::internal::WeakArrayList::CountLiveElements () const
Definition at line 295 of file fixed-array.cc.
                                           {
  int non_cleared_objects = 0;
  for (int i = 0; i < length(); i++) {
    if (!Get(i).IsCleared()) {
      ++non_cleared_objects;
    }
  }
  return non_cleared_objects;
}
References Get(), and v8::internal::length.
CountLiveWeakReferences()
int v8::internal::WeakArrayList::CountLiveWeakReferences () const
Definition at line 285 of file fixed-array.cc.
                                                 {
  int live_weak_references = 0;
  for (int i = 0; i < length(); i++) {
    if (Get(i).IsWeak()) {
      ++live_weak_references;
    }
  }
  return live_weak_references;
}
References Get(), and v8::internal::length.
data_start()
MaybeObjectSlot v8::internal::WeakArrayList::data_start () [inline]
Definition at line 696 of file fixed-array-inl.h.
                                          {
  return RawMaybeWeakField(kObjectsOffset);
}
Referenced by CopyElements().
EnsureSpace()
Handle< WeakArrayList > v8::internal::WeakArrayList::EnsureSpace (Isolate * isolate, Handle< WeakArrayList > array, int length, AllocationType allocation = AllocationType::kYoung) [static]
Definition at line 272 of file fixed-array.cc.
                                                                            {
  int capacity = array->capacity();
  if (capacity < length) {
    int grow_by = CapacityForLength(length) - capacity;
    array = isolate->factory()->CopyWeakArrayListAndGrow(array, grow_by,
                                                         allocation);
  }
  return array;
}
References capacity(), CapacityForLength(), v8::internal::Factory::CopyWeakArrayListAndGrow(), v8::internal::Isolate::factory(), and v8::internal::length.
Referenced by v8::internal::PrototypeUsers::Add(), v8::internal::PrototypeInfo::AddDerivedMap(), v8::internal::Heap::AddRetainedMaps(), AddToEnd(), v8::internal::PrototypeUsers::Compact(), and v8::internal::anonymous_namespace{heap.cc}::CompactWeakArrayList().
Get() [1/2]
Tagged< MaybeObject > v8::internal::WeakArrayList::Get (int index) const [inline]
Definition at line 675 of file fixed-array-inl.h.
                                                      {
  PtrComprCageBase cage_base = GetPtrComprCageBase();
  return Get(cage_base, index);
}
References v8::internal::GetPtrComprCageBase(), and v8::internal::index.
Referenced by Compact(), Contains(), CountLiveElements(), CountLiveWeakReferences(), v8::internal::DependentCode::FillEntryFromBack(), get(), v8::internal::DependentCode::IterateAndCompact(), and RemoveOne().
get()
Tagged< MaybeObject > v8::internal::WeakArrayList::get (int index) const [inline]
Definition at line 679 of file fixed-array-inl.h.
{ return Get(index); }
References Get(), and v8::internal::index.
Get() [2/2]
Tagged< MaybeObject > v8::internal::WeakArrayList::Get (PtrComprCageBase cage_base, int index) const [inline]
Definition at line 681 of file fixed-array-inl.h.
                                                        {
  DCHECK_LT(static_cast<unsigned>(index), static_cast<unsigned>(capacity()));
  return objects(cage_base, index, kRelaxedLoad);
}
References capacity(), DCHECK_LT, v8::internal::index, and v8::kRelaxedLoad.
IsFull()
bool v8::internal::WeakArrayList::IsFull () const
Definition at line 269 of file fixed-array.cc.
{ return length() == capacity(); }
References capacity(), and v8::internal::length.
OffsetOfElementAt()
static int v8::internal::WeakArrayList::OffsetOfElementAt (int index) [inline], [static], [private]
Definition at line 678 of file fixed-array.h.
                                          {
    return kHeaderSize + index * kTaggedSize;
  }
References v8::internal::FixedArray::index, and v8::internal::kTaggedSize.
Referenced by v8::internal::ByteArray::New(), and v8::internal::TrustedByteArray::New().
RemoveOne()
bool v8::internal::WeakArrayList::RemoveOne (MaybeObjectDirectHandle value)
Definition at line 305 of file fixed-array.cc.
                                                           {
  int last_index = length() - 1;
  // Optimize for the most recently added element to be removed again.
  Tagged<ClearedWeakValue> cleared_value =
      ClearedValue(PtrComprCageBase{Isolate::Current()});
  for (int i = last_index; i >= 0; --i) {
    if (Get(i) != *value) continue;
    // Move the last element into this slot (or no-op, if this is the last
    // slot).
    Set(i, Get(last_index));
    Set(last_index, cleared_value);
    set_length(last_index);
    return true;
  }
  return false;
}
References v8::internal::ClearedValue(), v8::internal::Isolate::Current(), Get(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::length, Set(), and v8::internal::value.
Set() [1/2]
void v8::internal::WeakArrayList::Set (int index, Tagged< MaybeObject > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 687 of file fixed-array-inl.h.
                                               {
  set_objects(index, value, kRelaxedStore, mode);
}
References v8::internal::index, v8::kRelaxedStore, mode(), and v8::internal::value.
Referenced by Compact(), v8::internal::DependentCode::FillEntryFromBack(), RemoveOne(), and Set().
Set() [2/2]
void v8::internal::WeakArrayList::Set (int index, Tagged< Smi > value) [inline]
Definition at line 692 of file fixed-array-inl.h.
                                                    {
  Set(index, value, SKIP_WRITE_BARRIER);
}
References v8::internal::index, Set(), v8::internal::SKIP_WRITE_BARRIER, and v8::internal::value.
SizeForCapacity()
static constexpr int v8::internal::WeakArrayList::SizeForCapacity (int capacity) [inline], [static], [constexpr]
Definition at line 626 of file fixed-array.h.
                                                     {
    return SizeFor(capacity);
  }
References v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::SizeFor().
Referenced by v8::internal::FactoryBase< Impl >::AllocateRawWeakArrayList(), and v8::internal::Heap::CreateEarlyReadOnlyMapsAndObjects().
Member Data Documentation
kMaxCapacity
constexpr int v8::internal::WeakArrayList::kMaxCapacity = kMaxFixedArrayCapacity [static], [constexpr]
Definition at line 653 of file fixed-array.h.
Referenced by v8::internal::FactoryBase< Impl >::AllocateRawWeakArrayList(), and v8::internal::ArrayList::New().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/fixed-array.h
/mnt/V8SourceCode/src/objects/fixed-array-inl.h
/mnt/V8SourceCode/src/objects/fixed-array.cc