v8::internal::FutexWaitList Class Reference
Classes
struct HeadAndTail
Public Member Functions
FutexWaitList ()=default
FutexWaitList (const FutexWaitList &)=delete
FutexWaitList & operator= (const FutexWaitList &)=delete
void AddNode (FutexWaitListNode *node)
void RemoveNode (FutexWaitListNode *node)
void Verify () const
base::Mutex * mutex ()
Static Public Member Functions
static void * ToWaitLocation (Tagged< JSArrayBuffer > array_buffer, size_t addr)
static FutexWaitListNode * DeleteAsyncWaiterNode (FutexWaitListNode *node)
static void DeleteNodesForIsolate (Isolate *isolate, FutexWaitListNode **head, FutexWaitListNode **tail)
static bool NodeIsOnList (FutexWaitListNode *node, FutexWaitListNode *head)
Private Attributes
base::Mutex mutex_
base::SmallMap< std::map< void *, HeadAndTail >, 16 > location_lists_
base::SmallMap< std::map< Isolate *, HeadAndTail > > isolate_promises_to_resolve_
Friends
class FutexEmulation
Detailed Description
Definition at line 27 of file futex-emulation.cc.
Constructor & Destructor Documentation
FutexWaitList() [1/2]
v8::internal::FutexWaitList::FutexWaitList () [default]
FutexWaitList() [2/2]
v8::internal::FutexWaitList::FutexWaitList (const FutexWaitList &) [delete]
Member Function Documentation
AddNode()
void v8::internal::FutexWaitList::AddNode (FutexWaitListNode * node)
Definition at line 213 of file futex-emulation.cc.
                                                   {
  DCHECK_NULL(node->prev_);
  DCHECK_NULL(node->next_);
  auto [it, inserted] =
      location_lists_.insert({node->wait_location_, HeadAndTail{node, node}});
  if (!inserted) {
    it->second.tail->next_ = node;
    node->prev_ = it->second.tail;
    it->second.tail = node;
  }
  Verify();
}
References DCHECK_NULL, location_lists_, v8::internal::FutexWaitListNode::next_, v8::internal::FutexWaitListNode::prev_, Verify(), and v8::internal::FutexWaitListNode::wait_location_.
Referenced by v8::internal::FutexEmulation::WaitAsync(), and v8::internal::FutexEmulation::WaitSync().
DeleteAsyncWaiterNode()
static FutexWaitListNode* v8::internal::FutexWaitList::DeleteAsyncWaiterNode (FutexWaitListNode * node) [inline], [static]
Definition at line 46 of file futex-emulation.cc.
                                                                           {
    DCHECK(node->IsAsync());
    DCHECK_NOT_NULL(node->async_state_->isolate_for_async_waiters);
    FutexWaitListNode* next = node->next_;
    if (node->prev_ != nullptr) {
      node->prev_->next_ = next;
    }
    if (next != nullptr) {
      next->prev_ = node->prev_;
    }
    delete node;
    return next;
  }
References v8::internal::FutexWaitListNode::async_state_, v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::FutexWaitListNode::IsAsync(), v8::internal::FutexWaitListNode::next_, and v8::internal::FutexWaitListNode::prev_.
Referenced by DeleteNodesForIsolate(), v8::internal::FutexEmulation::IsolateDeinit(), and v8::internal::FutexEmulation::ResolveAsyncWaiterPromises().
DeleteNodesForIsolate()
static void v8::internal::FutexWaitList::DeleteNodesForIsolate (Isolate * isolate, FutexWaitListNode ** head, FutexWaitListNode ** tail) [inline], [static]
Definition at line 60 of file futex-emulation.cc.
                                                              {
    // For updating head & tail once we've iterated all nodes.
    FutexWaitListNode* new_head = nullptr;
    FutexWaitListNode* new_tail = nullptr;
    for (FutexWaitListNode* node = *head; node;) {
      if (node->IsAsync() &&
          node->async_state_->isolate_for_async_waiters == isolate) {
        node->async_state_->timeout_task_id =
            CancelableTaskManager::kInvalidTaskId;
        node = DeleteAsyncWaiterNode(node);
      } else {
        if (new_head == nullptr) {
          new_head = node;
        }
        new_tail = node;
        node = node->next_;
      }
    }
    *head = new_head;
    *tail = new_tail;
  }
References v8::internal::FutexWaitListNode::async_state_, DeleteAsyncWaiterNode(), v8::internal::CancelableTaskManager::kInvalidTaskId, and v8::internal::FutexWaitListNode::next_.
Referenced by v8::internal::FutexEmulation::IsolateDeinit().
mutex()
base::Mutex* v8::internal::FutexWaitList::mutex () [inline]
Definition at line 88 of file futex-emulation.cc.
{ return &mutex_; }
References mutex_.
Referenced by v8::internal::FutexEmulation::HandleAsyncWaiterTimeout(), v8::internal::FutexEmulation::IsolateDeinit(), v8::internal::FutexEmulation::NotifyAsyncWaiter(), v8::internal::FutexWaitListNode::NotifyWake(), v8::internal::FutexEmulation::NumUnresolvedAsyncPromisesForTesting(), v8::internal::FutexEmulation::NumWaitersForTesting(), v8::internal::FutexEmulation::ResolveAsyncWaiterPromises(), v8::internal::FutexEmulation::WaitAsync(), v8::internal::FutexEmulation::WaitSync(), and v8::internal::FutexEmulation::Wake().
NodeIsOnList()
bool v8::internal::FutexWaitList::NodeIsOnList (FutexWaitListNode * node, FutexWaitListNode * head) [static]
Definition at line 992 of file futex-emulation.cc.
                                                          {
  for (FutexWaitListNode* n = head; n; n = n->next_) {
    if (n == node) return true;
  }
  return false;
}
References v8::internal::FutexWaitListNode::next_.
Referenced by RemoveNode(), and Verify().
operator=()
FutexWaitList& v8::internal::FutexWaitList::operator= (const FutexWaitList &) [delete]
RemoveNode()
void v8::internal::FutexWaitList::RemoveNode (FutexWaitListNode * node)
Definition at line 227 of file futex-emulation.cc.
                                                      {
  if (!node->prev_ && !node->next_) {
    // If the node was the last one on its list, delete the whole list.
    size_t erased = location_lists_.erase(node->wait_location_);
    DCHECK_EQ(1, erased);
    USE(erased);
  } else if (node->prev_ && node->next_) {
    // If we have both a successor and a predecessor, skip the lookup in the
    // list and just update those two nodes directly.
    node->prev_->next_ = node->next_;
    node->next_->prev_ = node->prev_;
    node->prev_ = node->next_ = nullptr;
  } else {
    // Otherwise we have to lookup in the list to find the head and tail
    // pointers.
    auto it = location_lists_.find(node->wait_location_);
    DCHECK_NE(location_lists_.end(), it);
    DCHECK(NodeIsOnList(node, it->second.head));
    if (node->prev_) {
      DCHECK(!node->next_);
      node->prev_->next_ = nullptr;
      DCHECK_EQ(node, it->second.tail);
      it->second.tail = node->prev_;
      node->prev_ = nullptr;
    } else {
      DCHECK_EQ(node, it->second.head);
      it->second.head = node->next_;
      DCHECK(node->next_);
      node->next_->prev_ = nullptr;
      node->next_ = nullptr;
    }
  }
  Verify();
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, location_lists_, v8::internal::FutexWaitListNode::next_, NodeIsOnList(), v8::internal::FutexWaitListNode::prev_, USE, Verify(), and v8::internal::FutexWaitListNode::wait_location_.
Referenced by v8::internal::FutexEmulation::HandleAsyncWaiterTimeout(), v8::internal::FutexEmulation::NotifyAsyncWaiter(), v8::internal::FutexEmulation::WaitSync(), and v8::internal::FutexEmulation::Wake().
ToWaitLocation()
static void* v8::internal::FutexWaitList::ToWaitLocation (Tagged< JSArrayBuffer > array_buffer, size_t addr) [inline], [static]
Definition at line 36 of file futex-emulation.cc.
                                                                               {
    DCHECK_LT(addr, array_buffer->GetByteLength());
    // Use the cheaper JSArrayBuffer::backing_store() accessor, but DCHECK that
    // it matches the start of the JSArrayBuffer::GetBackingStore().
    DCHECK_EQ(array_buffer->backing_store(),
              array_buffer->GetBackingStore()->buffer_start());
    return static_cast<uint8_t*>(array_buffer->backing_store()) + addr;
  }
References DCHECK_EQ, and DCHECK_LT.
Referenced by v8::internal::FutexEmulation::NumUnresolvedAsyncPromisesForTesting(), v8::internal::FutexEmulation::NumWaitersForTesting(), v8::internal::FutexEmulation::WaitAsync(), v8::internal::FutexEmulation::WaitSync(), and v8::internal::FutexEmulation::Wake().
Verify()
void v8::internal::FutexWaitList::Verify () const
Definition at line 954 of file futex-emulation.cc.
                                 {
#ifdef DEBUG
  auto VerifyNode = [](FutexWaitListNode* node, FutexWaitListNode* head,
                       FutexWaitListNode* tail) {
    if (node->next_ != nullptr) {
      DCHECK_NE(node, tail);
      DCHECK_EQ(node, node->next_->prev_);
    } else {
      DCHECK_EQ(node, tail);
    }
    if (node->prev_ != nullptr) {
      DCHECK_NE(node, head);
      DCHECK_EQ(node, node->prev_->next_);
    } else {
      DCHECK_EQ(node, head);
    }
    DCHECK(NodeIsOnList(node, head));
  };
  for (const auto& [addr, head_and_tail] : location_lists_) {
    auto [head, tail] = head_and_tail;
    for (FutexWaitListNode* node = head; node; node = node->next_) {
      VerifyNode(node, head, tail);
    }
  }
  for (const auto& [isolate, head_and_tail] : isolate_promises_to_resolve_) {
    auto [head, tail] = head_and_tail;
    for (FutexWaitListNode* node = head; node; node = node->next_) {
      DCHECK(node->IsAsync());
      VerifyNode(node, head, tail);
      DCHECK_EQ(isolate, node->async_state_->isolate_for_async_waiters);
    }
  }
#endif // DEBUG
}
References v8::internal::FutexWaitListNode::async_state_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, v8::internal::FutexWaitListNode::IsAsync(), isolate_promises_to_resolve_, location_lists_, v8::internal::FutexWaitListNode::next_, NodeIsOnList(), and v8::internal::FutexWaitListNode::prev_.
Referenced by AddNode(), v8::internal::FutexEmulation::IsolateDeinit(), and RemoveNode().
Friends And Related Function Documentation
FutexEmulation
friend class FutexEmulation [friend]
Definition at line 91 of file futex-emulation.cc.
Member Data Documentation
isolate_promises_to_resolve_
base::SmallMap<std::map<Isolate*, HeadAndTail> > v8::internal::FutexWaitList::isolate_promises_to_resolve_ [private]
Definition at line 114 of file futex-emulation.cc.
Referenced by v8::internal::FutexEmulation::IsolateDeinit(), v8::internal::FutexEmulation::NotifyAsyncWaiter(), v8::internal::FutexEmulation::NumUnresolvedAsyncPromisesForTesting(), v8::internal::FutexEmulation::ResolveAsyncWaiterPromises(), and Verify().
location_lists_
base::SmallMap<std::map<void*, HeadAndTail>, 16> v8::internal::FutexWaitList::location_lists_ [private]
Definition at line 110 of file futex-emulation.cc.
Referenced by AddNode(), v8::internal::FutexEmulation::IsolateDeinit(), v8::internal::FutexEmulation::NumWaitersForTesting(), RemoveNode(), Verify(), and v8::internal::FutexEmulation::Wake().
mutex_
base::Mutex v8::internal::FutexWaitList::mutex_ [private]
Definition at line 103 of file futex-emulation.cc.
Referenced by mutex().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/execution/futex-emulation.cc