v8::Float16Array Class Reference
An instance of Float16Array constructor.
#include <v8-typed-array.h>
Static Public Member Functions
static Local< Float16Array > New (Local< ArrayBuffer > array_buffer, size_t byte_offset, size_t length)
static Local< Float16Array > New (Local< SharedArrayBuffer > shared_array_buffer, size_t byte_offset, size_t length)
static Float16Array * Cast (Value *value)
Static Public Attributes
static constexpr size_t kMaxLength
Private Member Functions
Float16Array ()
Static Private Member Functions
static void CheckCast (Value *obj)
Additional Inherited Members
Detailed Description
An instance of Float16Array constructor.
Definition at line 251 of file v8-typed-array.h.
Constructor & Destructor Documentation
Float16Array()
v8::Float16Array::Float16Array () [private]
Member Function Documentation
Cast()
static Float16Array* v8::Float16Array::Cast (Value * value) [inline], [static]
Definition at line 260 of file v8-typed-array.h.
                                                    {
#ifdef V8_ENABLE_CHECKS
    CheckCast(value);
#endif
    return static_cast<Float16Array*>(value);
  }
References v8::internal::value.
CheckCast()
void v8::Float16Array::CheckCast (Value * obj) [static], [private]
Definition at line 4107 of file api.cc.
                                          {
  Utils::ApiCheck(i::v8_flags.js_float16array, "v8::Float16Array::Cast",
                  "Float16Array is not supported");
  auto obj = *Utils::OpenDirectHandle(that);
  Utils::ApiCheck(
      i::IsJSTypedArray(obj) &&
          i::Cast<i::JSTypedArray>(obj)->type() == i::kExternalFloat16Array,
      "v8::Float16Array::Cast()", "Value is not a Float16Array");
}
References v8::Utils::ApiCheck(), v8::internal::kExternalFloat16Array, v8::Utils::OpenDirectHandle(), v8::internal::tracing::type, and v8::internal::v8_flags.
New() [1/2]
Local< Float16Array > v8::Float16Array::New (Local< ArrayBuffer > array_buffer, size_t byte_offset, size_t length) [static]
Definition at line 9288 of file api.cc.
                                                                         {
  Utils::ApiCheck(i::v8_flags.js_float16array, "v8::Float16Array::New",
                  "Float16Array is not supported");
  i::Isolate* i_isolate = i::Isolate::Current();
  ApiRuntimeCallStatsScope rcs_scope(i_isolate, RCCId::kAPI_Float16Array_New);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  if (!Utils::ApiCheck(
          length <= kMaxLength,
          "v8::Float16Array::New(Local<ArrayBuffer>, size_t, size_t)",
          "length exceeds max allowed value")) {
    return {};
  }
  auto buffer = Utils::OpenDirectHandle(*array_buffer);
  i::DirectHandle<i::JSTypedArray> obj = i_isolate->factory()->NewJSTypedArray(
      i::kExternalFloat16Array, buffer, byte_offset, length);
  return Utils::ToLocalFloat16Array(obj);
}
References v8::Utils::ApiCheck(), v8::internal::Isolate::Current(), v8::internal::Isolate::factory(), v8::internal::kExternalFloat16Array, kMaxLength, v8::internal::length, v8::internal::Factory::NewJSTypedArray(), v8::Utils::OpenDirectHandle(), and v8::internal::v8_flags.
New() [2/2]
Local< Float16Array > v8::Float16Array::New (Local< SharedArrayBuffer > shared_array_buffer, size_t byte_offset, size_t length) [static]
Definition at line 9306 of file api.cc.
                   {
  Utils::ApiCheck(i::v8_flags.js_float16array, "v8::Float16Array::New",
                  "Float16Array is not supported");
  i::Isolate* i_isolate = i::Isolate::Current();
  ApiRuntimeCallStatsScope rcs_scope(i_isolate, RCCId::kAPI_Float16Array_New);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  if (!Utils::ApiCheck(
          length <= kMaxLength,
          "v8::Float16Array::New(Local<SharedArrayBuffer>, size_t, size_t)",
          "length exceeds max allowed value")) {
    return {};
  }
  auto buffer = Utils::OpenDirectHandle(*shared_array_buffer);
  i::DirectHandle<i::JSTypedArray> obj = i_isolate->factory()->NewJSTypedArray(
      i::kExternalFloat16Array, buffer, byte_offset, length);
  return Utils::ToLocalFloat16Array(obj);
}
References v8::Utils::ApiCheck(), v8::internal::Isolate::Current(), v8::internal::Isolate::factory(), v8::internal::kExternalFloat16Array, kMaxLength, v8::internal::length, v8::internal::Factory::NewJSTypedArray(), v8::Utils::OpenDirectHandle(), and v8::internal::v8_flags.
Member Data Documentation
kMaxLength
constexpr size_t v8::Float16Array::kMaxLength [static], [constexpr]
Initial value:
=
      TypedArray::kMaxByteLength / sizeof(uint16_t)
Definition at line 253 of file v8-typed-array.h.
Referenced by New().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-typed-array.h
/mnt/V8SourceCode/src/api/api.cc