v8::internal::Context Class Reference
#include <contexts.h>
Public Types
enum Field {
SCOPE_INFO_INDEX
, PREVIOUS_INDEX
, EXTENSION_INDEX
, NEXT_CONTEXT_LINK
,
NATIVE_CONTEXT_SLOTS
, FIRST_WEAK_SLOT = NEXT_CONTEXT_LINK
, FIRST_JS_ARRAY_MAP_SLOT = JS_ARRAY_PACKED_SMI_ELEMENTS_MAP_INDEX
, MIN_CONTEXT_SLOTS = EXTENSION_INDEX
,
MIN_CONTEXT_EXTENDED_SLOTS = EXTENSION_INDEX + 1
, THROWN_OBJECT_INDEX = MIN_CONTEXT_SLOTS
, WRAPPED_CONTEXT_INDEX = MIN_CONTEXT_EXTENDED_SLOTS
 }
Public Member Functions
bool IsElementTheHole (int index)
template<typename MemoryTag >
Tagged< Object > GetNoCell (int index, MemoryTag tag)
template<typename MemoryTag >
void SetNoCell (int index, Tagged< Object > value, MemoryTag tag, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
Tagged< Object > GetNoCell (int index)
void SetNoCell (int index, Tagged< Object > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
void Initialize (Isolate *isolate)
Tagged< Object > unchecked_previous () const
Tagged< Context > previous () const
Tagged< Object > next_context_link () const
bool has_extension () const
Tagged< HeapObject > extension () const
V8_EXPORT_PRIVATE void set_extension (Tagged< HeapObject > object, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
Tagged< JSObject > extension_object () const
Tagged< JSReceiver > extension_receiver () const
Tagged< SourceTextModule > module () const
Tagged< Context > declaration_context () const
bool is_declaration_context () const
Tagged< Context > closure_context () const
V8_EXPORT_PRIVATE Tagged< JSGlobalProxy > global_proxy () const
V8_EXPORT_PRIVATE Tagged< JSGlobalObject > global_object () const
Tagged< Context > script_context () const
Tagged< NativeContext > native_context () const
bool IsDetached (Isolate *isolate) const
bool IsFunctionContext () const
bool IsCatchContext () const
bool IsWithContext () const
bool IsDebugEvaluateContext () const
bool IsAwaitContext () const
bool IsBlockContext () const
bool IsModuleContext () const
bool IsEvalContext () const
bool IsScriptContext () const
bool HasContextCells () const
bool HasSameSecurityTokenAs (Tagged< Context > that) const
Handle< Object > ErrorMessageForCodeGenerationFromStrings ()
DirectHandle< Object > ErrorMessageForWasmCodeGeneration ()
Tagged< Map > GetInitialJSArrayMap (ElementsKind kind) const
Static Public Member Functions
static V8_EXPORT_PRIVATE DirectHandle< Object > Get (DirectHandle< Context > context, int index, Isolate *isolate)
static V8_EXPORT_PRIVATE void Set (DirectHandle< Context > context, int index, DirectHandle< Object > new_value, Isolate *isolate)
static constexpr int SizeFor (int length)
static constexpr int OffsetOfElementAt (int index)
static constexpr int SlotOffset (int index)
static Handle< Object > Lookup (Handle< Context > context, Handle< String > name, ContextLookupFlags flags, int *index, PropertyAttributes *attributes, InitializationFlag *init_flag, VariableMode *variable_mode, bool *is_sloppy_function_name=nullptr)
static int FunctionMapIndex (LanguageMode language_mode, FunctionKind kind, bool has_shared_name)
static int ArrayMapIndex (ElementsKind elements_kind)
Static Public Attributes
static const int kScopeInfoOffset = kElementsOffset
static const int kPreviousOffset = kScopeInfoOffset + kTaggedSize
static const int kTodoHeaderSize = kPreviousOffset + kTaggedSize
static const int kExtensionOffset = kTodoHeaderSize
static const int kExtensionSize
static const int kExtendedHeaderSize = kTodoHeaderSize + kExtensionSize
static const int FIRST_FUNCTION_MAP_INDEX = SLOPPY_FUNCTION_MAP_INDEX
static const int LAST_FUNCTION_MAP_INDEX = CLASS_FUNCTION_MAP_INDEX
static const int FIRST_FIXED_TYPED_ARRAY_FUN_INDEX = UINT8_ARRAY_FUN_INDEX
static const int FIRST_RAB_GSAB_TYPED_ARRAY_MAP_INDEX
static const int kNoContext = 0
static const int kNotFound = -1
Protected Member Functions
template<typename MemoryTag >
Tagged< Object > get (int index, MemoryTag tag) const
Tagged< Object > get (PtrComprCageBase cage_base, int index, RelaxedLoadTag) const
void set (int index, Tagged< Object > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
void set (int index, Tagged< Object > value, WriteBarrierMode mode, RelaxedStoreTag)
Tagged< Object > get (PtrComprCageBase cage_base, int index, AcquireLoadTag) const
void set (int index, Tagged< Object > value, WriteBarrierMode mode, ReleaseStoreTag)
Private Member Functions
void set_previous (Tagged< Context > context, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
Friends
class compiler::ContextRef
class JavaScriptFrame
class V8HeapExplorer
class Factory
Detailed Description
Definition at line 479 of file contexts.h.
Member Enumeration Documentation
Field
enum v8::internal::Context::Field
Enumerator
SCOPE_INFO_INDEX
PREVIOUS_INDEX
EXTENSION_INDEX
NEXT_CONTEXT_LINK
NATIVE_CONTEXT_SLOTS
FIRST_WEAK_SLOT
FIRST_JS_ARRAY_MAP_SLOT
MIN_CONTEXT_SLOTS
MIN_CONTEXT_EXTENDED_SLOTS
THROWN_OBJECT_INDEX
WRAPPED_CONTEXT_INDEX
Definition at line 539 of file contexts.h.
             {
    // TODO(shell): use offset-based approach for accessing common values.
    // These slots are in all contexts.
    SCOPE_INFO_INDEX,
    PREVIOUS_INDEX,
    // This slot only exists if ScopeInfo::HasContextExtensionSlot returns true.
    EXTENSION_INDEX,
// These slots are only in native contexts.
#define NATIVE_CONTEXT_SLOT(index, type, name) index,
    NATIVE_CONTEXT_FIELDS(NATIVE_CONTEXT_SLOT)
#undef NATIVE_CONTEXT_SLOT
    // Properties from here are treated as weak references by the full GC.
    // Scavenge treats them as strong references.
    NEXT_CONTEXT_LINK, // Weak.
    // Total number of slots.
    NATIVE_CONTEXT_SLOTS,
    FIRST_WEAK_SLOT = NEXT_CONTEXT_LINK,
    FIRST_JS_ARRAY_MAP_SLOT = JS_ARRAY_PACKED_SMI_ELEMENTS_MAP_INDEX,
    // TODO(shell): Remove, once it becomes zero
    MIN_CONTEXT_SLOTS = EXTENSION_INDEX,
    MIN_CONTEXT_EXTENDED_SLOTS = EXTENSION_INDEX + 1,
    // This slot holds the thrown value in catch contexts.
    THROWN_OBJECT_INDEX = MIN_CONTEXT_SLOTS,
    // These slots hold values in debug evaluate contexts.
    WRAPPED_CONTEXT_INDEX = MIN_CONTEXT_EXTENDED_SLOTS,
  };
Member Function Documentation
ArrayMapIndex()
static int v8::internal::Context::ArrayMapIndex (ElementsKind elements_kind) [inline], [static]
Definition at line 685 of file contexts.h.
                                                       {
    DCHECK(IsFastElementsKind(elements_kind));
    return int{elements_kind} + FIRST_JS_ARRAY_MAP_SLOT;
  }
References v8::internal::DCHECK(), FIRST_JS_ARRAY_MAP_SLOT, and v8::internal::IsFastElementsKind().
Referenced by GetInitialJSArrayMap(), v8::internal::anonymous_namespace{builtins-array.cc}::GetReplacedElementsKindsMap(), v8::internal::anonymous_namespace{bootstrapper.cc}::InitializeJSArrayMaps(), v8::internal::CodeStubAssembler::LoadJSArrayElementsMap(), v8::internal::Map::TransitionElementsTo(), v8::internal::KeyedStoreGenericAssembler::TryChangeToHoleyMapHelper(), and v8::internal::KeyedStoreGenericAssembler::TryRewriteElements().
closure_context()
Tagged< Context > v8::internal::Context::closure_context () const
Definition at line 156 of file contexts.cc.
                                               {
  Tagged<Context> current = *this;
  while (!current->IsFunctionContext() && !current->IsScriptContext() &&
         !current->IsModuleContext() && !IsNativeContext(current) &&
         !current->IsEvalContext()) {
    current = current->previous();
  }
  return current;
}
declaration_context()
Tagged< Context > v8::internal::Context::declaration_context () const
Definition at line 148 of file contexts.cc.
                                                   {
  Tagged<Context> current = *this;
  while (!current->is_declaration_context()) {
    current = current->previous();
  }
  return current;
}
ErrorMessageForCodeGenerationFromStrings()
Handle< Object > v8::internal::Context::ErrorMessageForCodeGenerationFromStrings ()
Definition at line 676 of file contexts.cc.
                                                                 {
  Isolate* isolate = Isolate::Current();
  Handle<Object> result(error_message_for_code_gen_from_strings(), isolate);
  if (!IsUndefined(*result, isolate)) return result;
  return isolate->factory()->NewStringFromStaticChars(
      "Code generation from strings disallowed for this context");
}
References v8::internal::Isolate::Current(), v8::internal::Isolate::factory(), v8::internal::Factory::NewStringFromStaticChars(), and v8::base::internal::result.
ErrorMessageForWasmCodeGeneration()
DirectHandle< Object > v8::internal::Context::ErrorMessageForWasmCodeGeneration ()
Definition at line 684 of file contexts.cc.
                                                                {
  Isolate* isolate = Isolate::Current();
  DirectHandle<Object> result(error_message_for_wasm_code_gen(), isolate);
  if (!IsUndefined(*result, isolate)) return result;
  return isolate->factory()->NewStringFromStaticChars(
      "Wasm code generation disallowed by embedder");
}
References v8::internal::Isolate::Current(), v8::internal::Isolate::factory(), v8::internal::Factory::NewStringFromStaticChars(), and v8::base::internal::result.
extension()
Tagged< HeapObject > v8::internal::Context::extension () const [inline]
Definition at line 161 of file contexts-inl.h.
                                            {
  DCHECK(scope_info()->HasContextExtensionSlot());
  return Cast<HeapObject>(get(EXTENSION_INDEX, kRelaxedLoad));
}
References v8::internal::DCHECK(), EXTENSION_INDEX, get(), and v8::kRelaxedLoad.
Referenced by extension_object(), extension_receiver(), global_object(), has_extension(), and Lookup().
extension_object()
Tagged< JSObject > v8::internal::Context::extension_object () const
Definition at line 166 of file contexts.cc.
                                                 {
  DCHECK(IsNativeContext(*this) || IsFunctionContext() || IsBlockContext() ||
         IsEvalContext() || IsCatchContext());
  Tagged<HeapObject> object = extension();
  if (IsUndefined(object)) return JSObject();
  DCHECK(IsJSContextExtensionObject(object) ||
         (IsNativeContext(*this) && IsJSGlobalObject(object)));
  return Cast<JSObject>(object);
}
References v8::internal::DCHECK(), extension(), IsBlockContext(), IsCatchContext(), IsEvalContext(), and IsFunctionContext().
Referenced by extension_receiver().
extension_receiver()
Tagged< JSReceiver > v8::internal::Context::extension_receiver () const
Definition at line 176 of file contexts.cc.
                                                     {
  DCHECK(IsNativeContext(*this) || IsWithContext() || IsEvalContext() ||
         IsFunctionContext() || IsBlockContext());
  return IsWithContext() ? Cast<JSReceiver>(extension()) : extension_object();
}
References v8::internal::DCHECK(), extension(), extension_object(), IsBlockContext(), IsEvalContext(), IsFunctionContext(), and IsWithContext().
FunctionMapIndex()
int v8::internal::Context::FunctionMapIndex (LanguageMode language_mode, FunctionKind kind, bool has_shared_name) [inline], [static]
Definition at line 245 of file contexts-inl.h.
                                                    {
  if (IsClassConstructor(kind)) {
    // Like the strict function map, but with no 'name' accessor. 'name'
    // needs to be the last property and it is added during instantiation,
    // in case a static property with the same name exists"
    return CLASS_FUNCTION_MAP_INDEX;
  }
  int base = 0;
  if (IsGeneratorFunction(kind)) {
    CHECK_FOLLOWS2(GENERATOR_FUNCTION_MAP_INDEX,
                   GENERATOR_FUNCTION_WITH_NAME_MAP_INDEX);
    CHECK_FOLLOWS2(ASYNC_GENERATOR_FUNCTION_MAP_INDEX,
                   ASYNC_GENERATOR_FUNCTION_WITH_NAME_MAP_INDEX);
    base = IsAsyncFunction(kind) ? ASYNC_GENERATOR_FUNCTION_MAP_INDEX
                                 : GENERATOR_FUNCTION_MAP_INDEX;
  } else if (IsAsyncFunction(kind) || IsModuleWithTopLevelAwait(kind)) {
    CHECK_FOLLOWS2(ASYNC_FUNCTION_MAP_INDEX,
                   ASYNC_FUNCTION_WITH_NAME_MAP_INDEX);
    base = ASYNC_FUNCTION_MAP_INDEX;
  } else if (IsStrictFunctionWithoutPrototype(kind)) {
    CHECK_FOLLOWS2(STRICT_FUNCTION_WITHOUT_PROTOTYPE_MAP_INDEX,
                   METHOD_WITH_NAME_MAP_INDEX);
    base = STRICT_FUNCTION_WITHOUT_PROTOTYPE_MAP_INDEX;
  } else {
    CHECK_FOLLOWS2(SLOPPY_FUNCTION_MAP_INDEX,
                   SLOPPY_FUNCTION_WITH_NAME_MAP_INDEX);
    CHECK_FOLLOWS2(STRICT_FUNCTION_MAP_INDEX,
                   STRICT_FUNCTION_WITH_NAME_MAP_INDEX);
    base = is_strict(language_mode) ? STRICT_FUNCTION_MAP_INDEX
                                    : SLOPPY_FUNCTION_MAP_INDEX;
  }
  int offset = static_cast<int>(!has_shared_name);
  DCHECK_EQ(0, offset & ~1);
  return base + offset;
}
References CHECK_FOLLOWS2, DCHECK_EQ, v8::internal::is_strict(), v8::internal::IsAsyncFunction(), v8::internal::IsClassConstructor(), v8::internal::IsGeneratorFunction(), v8::internal::IsModuleWithTopLevelAwait(), and v8::internal::IsStrictFunctionWithoutPrototype().
Referenced by v8::internal::SharedFunctionInfo::UpdateFunctionMapIndex().
Get()
DirectHandle< Object > v8::internal::Context::Get (DirectHandle< Context > context, int index, Isolate * isolate) [static]
Definition at line 526 of file contexts.cc.
                                                    {
  DirectHandle<Object> value =
      handle(context->get(index, kRelaxedLoad), isolate);
  if (!Is<ContextCell>(value)) {
    return value;
  }
  DCHECK(context->HasContextCells());
  DirectHandle<ContextCell> cell = Cast<ContextCell>(value);
  switch (cell->state()) {
    case ContextCell::kConst:
    case ContextCell::kSmi:
      return handle(cell->tagged_value(), isolate);
    case ContextCell::kInt32:
      if (Smi::IsValid(cell->int32_value())) {
        return handle(Smi::FromInt(cell->int32_value()), isolate);
      }
      return isolate->factory()->NewHeapNumber(
          static_cast<double>(cell->int32_value()));
    case ContextCell::kFloat64:
      return isolate->factory()->NewHeapNumber(cell->float64_value());
    case ContextCell::kDetached:
      UNREACHABLE();
  }
  UNREACHABLE();
}
References v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::Smi::FromInt(), v8::internal::handle(), v8::internal::index, v8::internal::Smi::IsValid(), v8::internal::ContextCell::kConst, v8::internal::ContextCell::kDetached, v8::internal::ContextCell::kFloat64, v8::internal::ContextCell::kInt32, v8::kRelaxedLoad, v8::internal::ContextCell::kSmi, v8::internal::FactoryBase< Impl >::NewHeapNumber(), v8::internal::UNREACHABLE(), and v8::internal::value.
Referenced by v8::internal::LoadGlobalIC::Load(), v8::internal::anonymous_namespace{runtime-scopes.cc}::LoadLookupSlot(), v8::internal::ScopeIterator::VisitContextLocals(), and v8::internal::ScopeIterator::VisitLocals().
get() [1/3]
template<typename MemoryTag >
Tagged< Object > v8::internal::Context::get (int index, MemoryTag tag) const [protected]
Definition at line 91 of file contexts-inl.h.
                                                          {
  PtrComprCageBase cage_base = GetPtrComprCageBase(*this);
  return get(cage_base, index, tag);
}
References v8::internal::GetPtrComprCageBase(), and v8::internal::index.
Referenced by extension(), GetInitialJSArrayMap(), GetNoCell(), next_context_link(), previous(), SetNoCell(), v8::internal::NativeContext::synchronized_script_context_table(), v8::internal::NativeContext::TypedArrayElementsKindToCtorMap(), and v8::internal::NativeContext::TypedArrayElementsKindToRabGsabCtorMap().
get() [2/3]
Tagged< Object > v8::internal::Context::get (PtrComprCageBase cage_base, int index, AcquireLoadTag) const [inline], [protected]
Definition at line 117 of file contexts-inl.h.
                                                  {
  DCHECK_LT(static_cast<unsigned int>(index),
            static_cast<unsigned int>(length(kRelaxedLoad)));
  return ACQUIRE_READ_FIELD(*this, OffsetOfElementAt(index));
}
References ACQUIRE_READ_FIELD, DCHECK_LT, v8::internal::index, v8::kRelaxedLoad, v8::internal::length, and OffsetOfElementAt().
get() [3/3]
Tagged< Object > v8::internal::Context::get (PtrComprCageBase cage_base, int index, RelaxedLoadTag) const [inline], [protected]
Definition at line 96 of file contexts-inl.h.
                                                  {
  DCHECK_LT(static_cast<unsigned int>(index),
            static_cast<unsigned int>(length(kRelaxedLoad)));
  return TaggedField<Object>::Relaxed_Load(cage_base, *this,
                                           OffsetOfElementAt(index));
}
References DCHECK_LT, v8::internal::index, v8::kRelaxedLoad, v8::internal::length, OffsetOfElementAt(), and v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Relaxed_Load().
GetInitialJSArrayMap()
Tagged< Map > v8::internal::Context::GetInitialJSArrayMap (ElementsKind kind) const [inline]
Definition at line 294 of file contexts-inl.h.
                                                                 {
  DCHECK(IsNativeContext(*this));
  if (!IsFastElementsKind(kind)) return Map();
  DisallowGarbageCollection no_gc;
  Tagged<Object> const initial_js_array_map =
      get(Context::ArrayMapIndex(kind), kRelaxedLoad);
  DCHECK(!IsUndefined(initial_js_array_map));
  return Cast<Map>(initial_js_array_map);
}
References ArrayMapIndex(), v8::internal::DCHECK(), get(), v8::internal::IsFastElementsKind(), v8::kRelaxedLoad, v8::internal::compiler::Map, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
GetNoCell() [1/2]
Tagged< Object > v8::internal::Context::GetNoCell (int index) [inline]
Definition at line 74 of file contexts-inl.h.
                                           {
  return GetNoCell(index, kRelaxedLoad);
}
References GetNoCell(), v8::internal::index, and v8::kRelaxedLoad.
GetNoCell() [2/2]
template<typename MemoryTag >
Tagged< Object > v8::internal::Context::GetNoCell (int index, MemoryTag tag) [inline]
Definition at line 68 of file contexts-inl.h.
                                                          {
  Tagged<Object> value = get(index, tag);
  DCHECK(!Is<ContextCell>(value));
  return value;
}
References v8::internal::DCHECK(), get(), v8::internal::index, and v8::internal::value.
Referenced by GetNoCell().
global_object()
Tagged< JSGlobalObject > v8::internal::Context::global_object () const
Definition at line 190 of file contexts.cc.
                                                    {
  return Cast<JSGlobalObject>(native_context()->extension());
}
References extension(), and native_context().
Referenced by v8::internal::NativeContext::global_object(), and IsDetached().
global_proxy()
Tagged< JSGlobalProxy > v8::internal::Context::global_proxy () const
Definition at line 202 of file contexts.cc.
                                                  {
  return native_context()->global_proxy_object();
}
References native_context().
has_extension()
bool v8::internal::Context::has_extension () const [inline]
Definition at line 157 of file contexts-inl.h.
                                  {
  return scope_info()->HasContextExtensionSlot() && !IsUndefined(extension());
}
References extension().
HasContextCells()
bool v8::internal::Context::HasContextCells () const [inline]
Definition at line 206 of file contexts-inl.h.
                                           {
  return scope_info()->HasContextCells();
}
HasSameSecurityTokenAs()
bool v8::internal::Context::HasSameSecurityTokenAs (Tagged< Context > that) const [inline]
Definition at line 210 of file contexts-inl.h.
                                                               {
  return this->native_context()->security_token() ==
         that->native_context()->security_token();
}
References native_context().
Initialize()
void v8::internal::Context::Initialize (Isolate * isolate)
Definition at line 110 of file contexts.cc.
                                         {
  Tagged<ScopeInfo> scope_info = this->scope_info();
  int header = scope_info->ContextHeaderLength();
  for (int var = 0; var < scope_info->ContextLocalCount(); var++) {
    if (scope_info->ContextLocalInitFlag(var) == kNeedsInitialization) {
      set(header + var, ReadOnlyRoots(isolate).the_hole_value());
    }
  }
}
References v8::internal::kNeedsInitialization, and set().
is_declaration_context()
bool v8::internal::Context::is_declaration_context () const
Definition at line 136 of file contexts.cc.
                                           {
  if (IsFunctionContext() || IsNativeContext(*this) || IsScriptContext() ||
      IsModuleContext()) {
    return true;
  }
  if (IsEvalContext()) {
    return scope_info()->language_mode() == LanguageMode::kStrict;
  }
  if (!IsBlockContext()) return false;
  return scope_info()->is_declaration_scope();
}
References IsBlockContext(), IsEvalContext(), IsFunctionContext(), IsModuleContext(), IsScriptContext(), and v8::internal::kStrict.
IsAwaitContext()
bool v8::internal::Context::IsAwaitContext () const [inline]
Definition at line 186 of file contexts-inl.h.
                                   {
  return map()->instance_type() == AWAIT_CONTEXT_TYPE;
}
IsBlockContext()
bool v8::internal::Context::IsBlockContext () const [inline]
Definition at line 190 of file contexts-inl.h.
                                   {
  return map()->instance_type() == BLOCK_CONTEXT_TYPE;
}
Referenced by extension_object(), extension_receiver(), and is_declaration_context().
IsCatchContext()
bool v8::internal::Context::IsCatchContext () const [inline]
Definition at line 174 of file contexts-inl.h.
                                   {
  return map()->instance_type() == CATCH_CONTEXT_TYPE;
}
Referenced by extension_object().
IsDebugEvaluateContext()
bool v8::internal::Context::IsDebugEvaluateContext () const [inline]
Definition at line 182 of file contexts-inl.h.
                                           {
  return map()->instance_type() == DEBUG_EVALUATE_CONTEXT_TYPE;
}
IsDetached()
bool v8::internal::Context::IsDetached (Isolate * isolate) const [inline]
Definition at line 215 of file contexts-inl.h.
                                               {
  return global_object()->IsDetached(isolate);
}
References global_object().
IsElementTheHole()
bool v8::internal::Context::IsElementTheHole (int index) [inline]
Definition at line 63 of file contexts-inl.h.
                                        {
  return IsTheHole(get(index, kRelaxedLoad));
}
References v8::internal::index, and v8::kRelaxedLoad.
IsEvalContext()
bool v8::internal::Context::IsEvalContext () const [inline]
Definition at line 198 of file contexts-inl.h.
                                  {
  return map()->instance_type() == EVAL_CONTEXT_TYPE;
}
Referenced by extension_object(), extension_receiver(), and is_declaration_context().
IsFunctionContext()
bool v8::internal::Context::IsFunctionContext () const [inline]
Definition at line 170 of file contexts-inl.h.
                                      {
  return map()->instance_type() == FUNCTION_CONTEXT_TYPE;
}
Referenced by extension_object(), extension_receiver(), and is_declaration_context().
IsModuleContext()
bool v8::internal::Context::IsModuleContext () const [inline]
Definition at line 194 of file contexts-inl.h.
                                    {
  return map()->instance_type() == MODULE_CONTEXT_TYPE;
}
Referenced by is_declaration_context().
IsScriptContext()
bool v8::internal::Context::IsScriptContext () const [inline]
Definition at line 202 of file contexts-inl.h.
                                    {
  return map()->instance_type() == SCRIPT_CONTEXT_TYPE;
}
Referenced by is_declaration_context().
IsWithContext()
bool v8::internal::Context::IsWithContext () const [inline]
Definition at line 178 of file contexts-inl.h.
                                  {
  return map()->instance_type() == WITH_CONTEXT_TYPE;
}
Referenced by extension_receiver().
Lookup()
Handle< Object > v8::internal::Context::Lookup (Handle< Context > context, Handle< String > name, ContextLookupFlags flags, int * index, PropertyAttributes * attributes, InitializationFlag * init_flag, VariableMode * variable_mode, bool * is_sloppy_function_name = nullptr) [static]
Definition at line 238 of file contexts.cc.
                                                              {
  Isolate* isolate = Isolate::Current();
  bool follow_context_chain = (flags & FOLLOW_CONTEXT_CHAIN) != 0;
  bool has_seen_debug_evaluate_context = false;
  *index = kNotFound;
  *attributes = ABSENT;
  *init_flag = kCreatedInitialized;
  *variable_mode = VariableMode::kVar;
  if (is_sloppy_function_name != nullptr) {
    *is_sloppy_function_name = false;
  }
  if (v8_flags.trace_contexts) {
    PrintF("Context::Lookup(");
    ShortPrint(*name);
    PrintF(")\n");
  }
  do {
    if (v8_flags.trace_contexts) {
      PrintF(" - looking in context %p",
             reinterpret_cast<void*>(context->ptr()));
      if (context->IsScriptContext()) PrintF(" (script context)");
      if (IsNativeContext(*context)) PrintF(" (native context)");
      if (context->IsDebugEvaluateContext()) PrintF(" (debug context)");
      PrintF("\n");
    }
    // 1. Check global objects, subjects of with, and extension objects.
    DCHECK_IMPLIES(context->IsEvalContext() && context->has_extension(),
                   IsTheHole(context->extension(), isolate));
    if ((IsNativeContext(*context) || context->IsWithContext() ||
         context->IsFunctionContext() || context->IsBlockContext()) &&
        context->has_extension() && !context->extension_receiver().is_null()) {
      Handle<JSReceiver> object(context->extension_receiver(), isolate);
      if (IsNativeContext(*context)) {
        DisallowGarbageCollection no_gc;
        if (v8_flags.trace_contexts) {
          PrintF(" - trying other script contexts\n");
        }
        // Try other script contexts.
        Tagged<ScriptContextTable> script_contexts =
            context->native_context()->script_context_table();
        VariableLookupResult r;
        if (script_contexts->Lookup(name, &r)) {
          Tagged<Context> script_context =
              script_contexts->get(r.context_index);
          if (v8_flags.trace_contexts) {
            PrintF("=> found property in script context %d: %p\n",
                   r.context_index,
                   reinterpret_cast<void*>(script_context.ptr()));
          }
          *index = r.slot_index;
          *variable_mode = r.mode;
          *init_flag = r.init_flag;
          *attributes = GetAttributesForMode(r.mode);
          return handle(script_context, isolate);
        }
      }
      // Context extension objects needs to behave as if they have no
      // prototype. So even if we want to follow prototype chains, we need
      // to only do a local lookup for context extension objects.
      Maybe<PropertyAttributes> maybe = Nothing<PropertyAttributes>();
      if ((flags & FOLLOW_PROTOTYPE_CHAIN) == 0 ||
          IsJSContextExtensionObject(*object)) {
        maybe = JSReceiver::GetOwnPropertyAttributes(isolate, object, name);
      } else {
        // A with context will never bind "this", but debug-eval may look into
        // a with context when resolving "this". Other synthetic variables such
        // as new.target may be resolved as VariableMode::kDynamicLocal due to
        // bug v8:5405 , skipping them here serves as a workaround until a more
        // thorough fix can be applied.
        // TODO(v8:5405): Replace this check with a DCHECK when resolution of
        // of synthetic variables does not go through this code path.
        if (ScopeInfo::VariableIsSynthetic(*name)) {
          maybe = Just(ABSENT);
        } else {
          LookupIterator it(isolate, object, name, object);
          Maybe<bool> found = UnscopableLookup(&it, context->IsWithContext());
          if (found.IsNothing()) {
            maybe = Nothing<PropertyAttributes>();
          } else {
            // Luckily, consumers of |maybe| only care whether the property
            // was absent or not, so we can return a dummy |NONE| value
            // for its attributes when it was present.
            maybe = Just(found.FromJust() ? NONE : ABSENT);
          }
        }
      }
      if (maybe.IsNothing()) return Handle<Object>();
      DCHECK(!isolate->has_exception());
      *attributes = maybe.FromJust();
      if (maybe.FromJust() != ABSENT) {
        if (v8_flags.trace_contexts) {
          PrintF("=> found property in context object %p\n",
                 reinterpret_cast<void*>(object->ptr()));
        }
        return object;
      }
    }
    // 2. Check the context proper if it has slots.
    if (context->IsFunctionContext() || context->IsBlockContext() ||
        context->IsScriptContext() || context->IsEvalContext() ||
        context->IsModuleContext() || context->IsCatchContext()) {
      DisallowGarbageCollection no_gc;
      // Use serialized scope information of functions and blocks to search
      // for the context index.
      Tagged<ScopeInfo> scope_info = context->scope_info();
      VariableLookupResult lookup_result;
      int slot_index = scope_info->ContextSlotIndex(*name, &lookup_result);
      DCHECK(slot_index < 0 || slot_index >= MIN_CONTEXT_SLOTS);
      if (slot_index >= 0) {
        // Re-direct lookup to the ScriptContextTable in case we find a hole in
        // a REPL script context. REPL scripts allow re-declaration of
        // script-level let bindings. The value itself is stored in the script
        // context of the first script that declared a variable, all other
        // script contexts will contain 'the hole' for that particular name.
        if (scope_info->IsReplModeScope() &&
            context->IsElementTheHole(slot_index)) {
          context = Handle<Context>(context->previous(), isolate);
          continue;
        }
        if (v8_flags.trace_contexts) {
          PrintF("=> found local in context slot %d (mode = %hhu)\n",
                 slot_index, static_cast<uint8_t>(lookup_result.mode));
        }
        *index = slot_index;
        *variable_mode = lookup_result.mode;
        *init_flag = lookup_result.init_flag;
        *attributes = GetAttributesForMode(lookup_result.mode);
        return context;
      }
      // Check the slot corresponding to the intermediate context holding
      // only the function name variable. It's conceptually (and spec-wise)
      // in an outer scope of the function's declaration scope.
      if (follow_context_chain && context->IsFunctionContext()) {
        int function_index = scope_info->FunctionContextSlotIndex(*name);
        if (function_index >= 0) {
          if (v8_flags.trace_contexts) {
            PrintF("=> found intermediate function in context slot %d\n",
                   function_index);
          }
          *index = function_index;
          *attributes = READ_ONLY;
          *init_flag = kCreatedInitialized;
          *variable_mode = VariableMode::kConst;
          if (is_sloppy_function_name != nullptr &&
              is_sloppy(scope_info->language_mode())) {
            *is_sloppy_function_name = true;
          }
          return context;
        }
      }
      // Lookup variable in module imports and exports.
      if (context->IsModuleContext()) {
        VariableMode mode;
        InitializationFlag flag;
        MaybeAssignedFlag maybe_assigned_flag;
        int cell_index =
            scope_info->ModuleIndex(*name, &mode, &flag, &maybe_assigned_flag);
        if (cell_index != 0) {
          if (v8_flags.trace_contexts) {
            PrintF("=> found in module imports or exports\n");
          }
          *index = cell_index;
          *variable_mode = mode;
          *init_flag = flag;
          *attributes = SourceTextModuleDescriptor::GetCellIndexKind(
                            cell_index) == SourceTextModuleDescriptor::kExport
                            ? GetAttributesForMode(mode)
                            : READ_ONLY;
          return handle(context->module(), isolate);
        }
      }
    } else if (context->IsDebugEvaluateContext()) {
      has_seen_debug_evaluate_context = true;
      // Check materialized locals.
      Tagged<Object> ext = context->get(EXTENSION_INDEX, kRelaxedLoad);
      if (IsJSReceiver(ext)) {
        Handle<JSReceiver> extension(Cast<JSReceiver>(ext), isolate);
        LookupIterator it(isolate, extension, name, extension);
        Maybe<bool> found = JSReceiver::HasProperty(&it);
        if (found.FromMaybe(false)) {
          *attributes = NONE;
          return extension;
        }
      }
      // Check the original context, but do not follow its context chain.
      Tagged<Object> obj = context->get(WRAPPED_CONTEXT_INDEX, kRelaxedLoad);
      if (IsContext(obj)) {
        Handle<Context> wrapped_context(Cast<Context>(obj), isolate);
        Handle<Object> result =
            Context::Lookup(wrapped_context, name, DONT_FOLLOW_CHAINS, index,
                            attributes, init_flag, variable_mode);
        if (!result.is_null()) return result;
      }
    }
    // 3. Prepare to continue with the previous (next outermost) context.
    if (IsNativeContext(*context)) break;
    // In case we saw any DebugEvaluateContext, we'll need to check the block
    // list before we can advance to properly "shadow" stack-allocated
    // variables.
    // Note that this implicitly skips the block list check for the
    // "wrapped" context lookup for DebugEvaluateContexts. In that case
    // `has_seen_debug_evaluate_context` will always be false.
    if (has_seen_debug_evaluate_context &&
        IsEphemeronHashTable(isolate->heap()->locals_block_list_cache())) {
      DirectHandle<ScopeInfo> scope_info =
          direct_handle(context->scope_info(), isolate);
      Tagged<Object> maybe_outer_block_list =
          isolate->LocalsBlockListCacheGet(scope_info);
      if (IsStringSet(maybe_outer_block_list) &&
          Cast<StringSet>(maybe_outer_block_list)->Has(isolate, name)) {
        if (v8_flags.trace_contexts) {
          PrintF(" - name is blocklisted. Aborting.\n");
        }
        break;
      }
    }
    context = Handle<Context>(context->previous(), isolate);
  } while (follow_context_chain);
  if (v8_flags.trace_contexts) {
    PrintF("=> no property/slot found\n");
  }
  return Handle<Object>::null();
}
References v8::internal::ABSENT, v8::internal::VariableLookupResult::context_index, v8::internal::Isolate::Current(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::direct_handle(), v8::internal::DONT_FOLLOW_CHAINS, extension(), EXTENSION_INDEX, v8::internal::flags, v8::internal::FOLLOW_CONTEXT_CHAIN, v8::internal::FOLLOW_PROTOTYPE_CHAIN, v8::Maybe< T >::FromJust(), v8::Maybe< T >::FromMaybe(), v8::internal::GetAttributesForMode(), v8::internal::SourceTextModuleDescriptor::GetCellIndexKind(), v8::internal::JSReceiver::GetOwnPropertyAttributes(), v8::internal::handle(), v8::internal::Isolate::has_exception(), v8::internal::JSReceiver::HasProperty(), v8::internal::Isolate::heap(), v8::internal::index, v8::internal::VariableLookupResult::init_flag, v8::internal::HandleBase::is_null(), v8::internal::is_sloppy(), v8::Maybe< T >::IsNothing(), v8::Just(), v8::internal::kConst, v8::internal::kCreatedInitialized, v8::internal::SourceTextModuleDescriptor::kExport, kNotFound, v8::kRelaxedLoad, v8::internal::kVar, v8::internal::Isolate::LocalsBlockListCacheGet(), MIN_CONTEXT_SLOTS, mode(), v8::internal::VariableLookupResult::mode, v8::internal::name, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::NONE, v8::internal::Handle< T >::null(), v8::internal::PrintF(), v8::internal::READ_ONLY, v8::base::internal::result, script_context(), v8::internal::ShortPrint(), v8::internal::VariableLookupResult::slot_index, v8::internal::UnscopableLookup(), v8::internal::v8_flags, v8::internal::ScopeInfo::VariableIsSynthetic(), and WRAPPED_CONTEXT_INDEX.
Referenced by v8::internal::anonymous_namespace{runtime-scopes.cc}::DeclareEvalHelper(), v8::internal::anonymous_namespace{runtime-scopes.cc}::LoadLookupSlot(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::anonymous_namespace{runtime-scopes.cc}::StoreLookupSlot().
module()
Tagged< SourceTextModule > v8::internal::Context::module () const
Definition at line 182 of file contexts.cc.
                                               {
  Tagged<Context> current = *this;
  while (!current->IsModuleContext()) {
    current = current->previous();
  }
  return Cast<SourceTextModule>(current->extension());
}
native_context()
Tagged< NativeContext > v8::internal::Context::native_context () const [inline]
Definition at line 166 of file contexts-inl.h.
                                                    {
  return this->map()->native_context();
}
Referenced by global_object(), global_proxy(), and HasSameSecurityTokenAs().
next_context_link()
Tagged< Object > v8::internal::Context::next_context_link () const [inline]
Definition at line 153 of file contexts-inl.h.
                                                {
  return get(Context::NEXT_CONTEXT_LINK, kRelaxedLoad);
}
References get(), v8::kRelaxedLoad, and NEXT_CONTEXT_LINK.
OffsetOfElementAt()
static constexpr int v8::internal::Context::OffsetOfElementAt (int index) [inline], [static], [constexpr]
Definition at line 524 of file contexts.h.
                                                              {
    return SizeFor(index);
  }
References v8::internal::index, and SizeFor().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::CatchCase(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CatchException(), v8::internal::maglev::MaglevGraphBuilder::CreateContext(), v8::internal::V8HeapExplorer::ExtractContextReferences(), v8::internal::compiler::AccessBuilder::ForContextSlot(), v8::internal::compiler::AccessBuilder::ForContextSlotKnownPointer(), v8::internal::compiler::AccessBuilder::ForContextSlotSmi(), get(), v8::internal::V8HeapExplorer::IsEssentialHiddenReference(), v8::internal::baseline::BaselineAssembler::LdaContextSlotNoCell(), v8::internal::maglev::MaglevGraphBuilder::LoadAndCacheContextSlot(), set(), SlotOffset(), v8::internal::baseline::BaselineAssembler::StaContextSlotNoCell(), v8::internal::maglev::MaglevGraphBuilder::StoreAndCacheContextSlot(), v8::internal::maglev::MaglevGraphBuilder::TryGetParentContext(), v8::internal::maglev::Graph::TryGetScopeInfoForContextLoad(), v8::internal::maglev::MaglevGraphBuilder::TrySpecializeLoadContextSlot(), v8::internal::maglev::MaglevGraphBuilder::TrySpecializeStoreContextSlot(), v8::internal::maglev::KnownNodeAspects::UpdateMayHaveAliasingContexts(), and v8::internal::WeakListVisitor< Context >::VisitLiveObject().
previous()
Tagged< Context > v8::internal::Context::previous () const [inline]
Definition at line 144 of file contexts-inl.h.
                                        {
  Tagged<Object> result = get(PREVIOUS_INDEX, kRelaxedLoad);
  DCHECK(IsBootstrappingOrValidParentContext(result, *this));
  return UncheckedCast<Context>(result);
}
References v8::internal::DCHECK(), get(), v8::kRelaxedLoad, PREVIOUS_INDEX, and v8::base::internal::result.
script_context()
Tagged< Context > v8::internal::Context::script_context () const
Definition at line 194 of file contexts.cc.
                                              {
  Tagged<Context> current = *this;
  while (!current->IsScriptContext()) {
    current = current->previous();
  }
  return current;
}
Referenced by Lookup().
Set()
void v8::internal::Context::Set (DirectHandle< Context > context, int index, DirectHandle< Object > new_value, Isolate * isolate) [static]
Definition at line 554 of file contexts.cc.
                                                                    {
  DirectHandle<Object> old_value(context->get(index, kRelaxedLoad), isolate);
  if (!context->HasContextCells()) {
    context->set(index, *new_value);
    return;
  }
  if (IsTheHole(*old_value, isolate)) {
    // Setting the initial value.
    DirectHandle<ContextCell> cell =
        isolate->factory()->NewContextCell(Cast<JSAny>(new_value));
    context->set(index, *cell);
    return;
  }
  if (!Is<ContextCell>(old_value)) {
    context->set(index, *new_value);
    return;
  }
  if (IsUndefinedContextCell(*old_value, isolate)) {
    if (IsUndefined(*new_value)) return;
    if (IsTheHole(*new_value)) {
      // This can happened in let-variable in function contexts.
      context->set(index, *new_value);
      return;
    }
    DirectHandle<ContextCell> cell =
        isolate->factory()->NewContextCell(Cast<JSAny>(new_value));
    context->set(index, *cell);
    return;
  }
  DirectHandle<ContextCell> cell = Cast<ContextCell>(old_value);
  switch (cell->state()) {
    case ContextCell::kConst:
      // If we are assigning the same value, the property won't change.
      if (cell->tagged_value() == *new_value) {
        return;
      }
      // If both values are HeapNumbers with the same double value, the property
      // won't change either.
      if (Is<HeapNumber>(cell->tagged_value()) && Is<HeapNumber>(*new_value)) {
        double old_number = Cast<HeapNumber>(cell->tagged_value())->value();
        double new_number = Cast<HeapNumber>(*new_value)->value();
        if (old_number == new_number && old_number != 0) {
          return;
        }
      }
      NotifyContextCellStateWillChange(cell, isolate);
      if (Is<Smi>(*new_value)) {
        cell->set_smi_value(Cast<Smi>(*new_value));
        cell->set_state(ContextCell::kSmi);
      } else if (IsHeapNumber(*new_value)) {
        TransitionContextCellToUntagged(Cast<HeapNumber>(*new_value), cell);
        cell->clear_tagged_value();
      } else {
        context->set(index, *new_value);
        cell->clear_tagged_value();
        cell->set_state(ContextCell::kDetached);
      }
      return;
    case ContextCell::kSmi:
      if (IsSmi(*new_value)) {
        cell->set_smi_value(Cast<Smi>(*new_value));
        cell->set_state(ContextCell::kSmi);
      } else {
        NotifyContextCellStateWillChange(cell, isolate);
        if (IsHeapNumber(*new_value)) {
          TransitionContextCellToUntagged(Cast<HeapNumber>(*new_value), cell);
        } else {
          context->set(index, *new_value);
          cell->set_state(ContextCell::kDetached);
        }
        cell->clear_tagged_value();
      }
      return;
    case ContextCell::kInt32:
      if (IsSmi(*new_value)) {
        cell->set_int32_value(Cast<Smi>(*new_value).value());
        cell->set_state(ContextCell::kInt32);
      } else if (IsHeapNumber(*new_value)) {
        double double_value = Cast<HeapNumber>(*new_value)->value();
        if (auto int32_value = DoubleFitsInInt32(double_value)) {
          cell->set_int32_value(*int32_value);
          cell->set_state(ContextCell::kInt32);
        } else {
          NotifyContextCellStateWillChange(cell, isolate);
          cell->set_float64_value(double_value);
          cell->set_state(ContextCell::kFloat64);
        }
      } else {
        NotifyContextCellStateWillChange(cell, isolate);
        context->set(index, *new_value);
        cell->set_state(ContextCell::kDetached);
      }
      return;
    case ContextCell::kFloat64:
      if (IsSmi(*new_value)) {
        cell->set_float64_value(
            static_cast<double>(Cast<Smi>(*new_value).value()));
        cell->set_state(ContextCell::kFloat64);
      } else if (IsHeapNumber(*new_value)) {
        cell->set_float64_value(Cast<HeapNumber>(*new_value)->value());
        cell->set_state(ContextCell::kFloat64);
      } else {
        NotifyContextCellStateWillChange(cell, isolate);
        context->set(index, *new_value);
        cell->set_state(ContextCell::kDetached);
      }
      return;
    case ContextCell::kDetached:
      UNREACHABLE();
  }
  UNREACHABLE();
}
References v8::internal::anonymous_namespace{contexts.cc}::DoubleFitsInInt32(), v8::internal::Isolate::factory(), v8::internal::index, v8::internal::IsSmi(), v8::internal::ContextCell::kConst, v8::internal::ContextCell::kDetached, v8::internal::ContextCell::kFloat64, v8::internal::ContextCell::kInt32, v8::kRelaxedLoad, v8::internal::ContextCell::kSmi, v8::internal::Factory::NewContextCell(), v8::internal::anonymous_namespace{contexts.cc}::NotifyContextCellStateWillChange(), v8::internal::anonymous_namespace{contexts.cc}::TransitionContextCellToUntagged(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::anonymous_namespace{runtime-scopes.cc}::DeclareEvalHelper(), v8::internal::RUNTIME_FUNCTION(), v8::internal::ScopeIterator::SetContextVariableValue(), v8::internal::ScopeIterator::SetLocalVariableValue(), v8::internal::ScopeIterator::SetScriptVariableValue(), v8::internal::StoreGlobalIC::Store(), and v8::internal::anonymous_namespace{runtime-scopes.cc}::StoreLookupSlot().
set() [1/3]
void v8::internal::Context::set (int index, Tagged< Object > value, WriteBarrierMode mode, RelaxedStoreTag) [inline], [protected]
Definition at line 108 of file contexts-inl.h.
                                   {
  DCHECK_LT(static_cast<unsigned int>(index),
            static_cast<unsigned int>(length(kRelaxedLoad)));
  const int offset = OffsetOfElementAt(index);
  RELAXED_WRITE_FIELD(*this, offset, value);
  CONDITIONAL_WRITE_BARRIER(*this, offset, value, mode);
}
References CONDITIONAL_WRITE_BARRIER, DCHECK_LT, v8::internal::index, v8::kRelaxedLoad, v8::internal::length, mode(), OffsetOfElementAt(), RELAXED_WRITE_FIELD, and v8::internal::value.
set() [2/3]
void v8::internal::Context::set (int index, Tagged< Object > value, WriteBarrierMode mode, ReleaseStoreTag) [inline], [protected]
Definition at line 124 of file contexts-inl.h.
                                   {
  DCHECK_LT(static_cast<unsigned int>(index),
            static_cast<unsigned int>(length(kRelaxedLoad)));
  const int offset = OffsetOfElementAt(index);
  RELEASE_WRITE_FIELD(*this, offset, value);
  CONDITIONAL_WRITE_BARRIER(*this, offset, value, mode);
}
References CONDITIONAL_WRITE_BARRIER, DCHECK_LT, v8::internal::index, v8::kRelaxedLoad, v8::internal::length, mode(), OffsetOfElementAt(), RELEASE_WRITE_FIELD, and v8::internal::value.
set() [3/3]
void v8::internal::Context::set (int index, Tagged< Object > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline], [protected]
Definition at line 104 of file contexts-inl.h.
                                                                        {
  set(index, value, mode, kRelaxedStore);
}
References v8::internal::index, v8::kRelaxedStore, mode(), and v8::internal::value.
Referenced by Initialize(), v8::internal::NativeContext::set(), set_extension(), set_previous(), and SetNoCell().
set_extension()
void v8::internal::Context::set_extension (Tagged< HeapObject > object, WriteBarrierMode mode = UPDATE_WRITE_BARRIER)
Definition at line 725 of file contexts.cc.
                                                                            {
  DCHECK(scope_info()->HasContextExtensionSlot());
#ifdef VERIFY_HEAP
  if (v8_flags.verify_heap) VerifyExtensionSlot(object);
#endif
  set(EXTENSION_INDEX, object, mode);
}
References v8::internal::DCHECK(), EXTENSION_INDEX, mode(), set(), and v8::internal::v8_flags.
set_previous()
void v8::internal::Context::set_previous (Tagged< Context > context, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline], [private]
Definition at line 149 of file contexts-inl.h.
                                                                         {
  set(PREVIOUS_INDEX, context, mode);
}
References mode(), PREVIOUS_INDEX, and set().
SetNoCell() [1/2]
template<typename MemoryTag >
void v8::internal::Context::SetNoCell (int index, Tagged< Object > value, MemoryTag tag, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 79 of file contexts-inl.h.
                                               {
  DCHECK(!Is<ContextCell>(get(index, kRelaxedLoad)));
  set(index, value, mode, tag);
}
References v8::internal::DCHECK(), get(), v8::internal::index, v8::kRelaxedLoad, mode(), set(), and v8::internal::value.
Referenced by SetNoCell().
SetNoCell() [2/2]
void v8::internal::Context::SetNoCell (int index, Tagged< Object > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 85 of file contexts-inl.h.
                                               {
  SetNoCell(index, value, kRelaxedStore, mode);
}
References v8::internal::index, v8::kRelaxedStore, mode(), SetNoCell(), and v8::internal::value.
SizeFor()
static constexpr int v8::internal::Context::SizeFor (int length) [inline], [static], [constexpr]
Definition at line 515 of file contexts.h.
                                                     {
    // TODO(v8:9287): This is a workaround for GCMole build failures.
    int result = kElementsOffset + length * kTaggedSize;
    DCHECK_EQ(TorqueGeneratedContext::SizeFor(length), result);
    return result;
  }
References DCHECK_EQ, v8::internal::kTaggedSize, v8::internal::length, and v8::base::internal::result.
Referenced by v8::internal::compiler::AllocationBuilder::AllocateContext(), v8::internal::Factory::NewBlockContext(), v8::internal::Factory::NewBuiltinContext(), v8::internal::Factory::NewCatchContext(), v8::internal::Factory::NewContextInternal(), v8::internal::Factory::NewDebugEvaluateContext(), v8::internal::Factory::NewFunctionContext(), v8::internal::Factory::NewModuleContext(), v8::internal::Factory::NewScriptContext(), v8::internal::Factory::NewWithContext(), OffsetOfElementAt(), and v8::internal::HeapObject::SizeFromMap().
SlotOffset()
static constexpr int v8::internal::Context::SlotOffset (int index) [inline], [static], [constexpr]
Definition at line 528 of file contexts.h.
                                                       {
    return OffsetOfElementAt(index) - kHeapObjectTag;
  }
References v8::internal::index, v8::internal::kHeapObjectTag, and OffsetOfElementAt().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CatchCase(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CatchException(), v8::internal::compiler::AccessBuilder::ForContextSlot(), v8::internal::compiler::AccessBuilder::ForContextSlotKnownPointer(), v8::internal::compiler::AccessBuilder::ForContextSlotSmi(), v8::internal::MacroAssembler::LoadNativeContextSlot(), and v8::internal::CodeStubAssembler::StoreContextElementNoWriteBarrier().
unchecked_previous()
Tagged< Object > v8::internal::Context::unchecked_previous () const [inline]
Definition at line 140 of file contexts-inl.h.
                                                 {
  return get(PREVIOUS_INDEX, kRelaxedLoad);
}
References v8::kRelaxedLoad.
Friends And Related Function Documentation
compiler::ContextRef
friend class compiler::ContextRef [friend]
Definition at line 723 of file contexts.h.
Factory
friend class Factory [friend]
Definition at line 738 of file contexts.h.
JavaScriptFrame
friend class JavaScriptFrame [friend]
Definition at line 724 of file contexts.h.
V8HeapExplorer
friend class V8HeapExplorer [friend]
Definition at line 725 of file contexts.h.
Member Data Documentation
FIRST_FIXED_TYPED_ARRAY_FUN_INDEX
const int v8::internal::Context::FIRST_FIXED_TYPED_ARRAY_FUN_INDEX = UINT8_ARRAY_FUN_INDEX [static]
Definition at line 582 of file contexts.h.
Referenced by v8::internal::anonymous_namespace{js-function.cc}::TypedArrayElementsKindToConstructorIndex(), and v8::internal::NativeContext::TypedArrayElementsKindToCtorMap().
FIRST_FUNCTION_MAP_INDEX
const int v8::internal::Context::FIRST_FUNCTION_MAP_INDEX = SLOPPY_FUNCTION_MAP_INDEX [static]
Definition at line 579 of file contexts.h.
Referenced by v8::internal::compiler::NativeContextRef::GetFunctionMapFromIndex(), and v8::internal::TF_BUILTIN().
FIRST_RAB_GSAB_TYPED_ARRAY_MAP_INDEX
const int v8::internal::Context::FIRST_RAB_GSAB_TYPED_ARRAY_MAP_INDEX [static]
Initial value:
=
      RAB_GSAB_UINT8_ARRAY_MAP_INDEX
Definition at line 583 of file contexts.h.
Referenced by v8::internal::anonymous_namespace{js-function.cc}::TypedArrayElementsKindToRabGsabCtorIndex(), and v8::internal::NativeContext::TypedArrayElementsKindToRabGsabCtorMap().
kExtendedHeaderSize
const int v8::internal::Context::kExtendedHeaderSize = kTodoHeaderSize + kExtensionSize [static]
Definition at line 575 of file contexts.h.
kExtensionOffset
const int v8::internal::Context::kExtensionOffset = kTodoHeaderSize [static]
Definition at line 512 of file contexts.h.
Referenced by v8::internal::ConstructorBuiltinsAssembler::FastNewFunctionContext(), v8::internal::baseline::BaselineAssembler::LdaModuleVariable(), and v8::internal::baseline::BaselineAssembler::StaModuleVariable().
kExtensionSize
const int v8::internal::Context::kExtensionSize [static]
Initial value:
=
      (MIN_CONTEXT_EXTENDED_SLOTS - MIN_CONTEXT_SLOTS) * kTaggedSize
Definition at line 573 of file contexts.h.
kNoContext
const int v8::internal::Context::kNoContext = 0 [static]
Definition at line 586 of file contexts.h.
Referenced by v8::internal::Isolate::clear_topmost_script_having_context(), v8::internal::TickSample::GetStackSample(), v8::internal::MacroAssembler::LeaveExitFrame(), v8::internal::CodeStubAssembler::NoContextConstant(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::NoContextConstant(), v8::internal::compiler::turboshaft::AssertTypesReducer< Next >::NoContextConstant(), v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi(), and v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::WrapFastCall().
kNotFound
const int v8::internal::Context::kNotFound = -1 [static]
Definition at line 692 of file contexts.h.
Referenced by v8::internal::anonymous_namespace{runtime-scopes.cc}::DeclareEvalHelper(), v8::internal::anonymous_namespace{runtime-scopes.cc}::LoadLookupSlot(), Lookup(), and v8::internal::anonymous_namespace{runtime-scopes.cc}::StoreLookupSlot().
kPreviousOffset
const int v8::internal::Context::kPreviousOffset = kScopeInfoOffset + kTaggedSize [static]
Definition at line 504 of file contexts.h.
Referenced by v8::internal::ConstructorBuiltinsAssembler::FastNewFunctionContext(), v8::internal::baseline::BaselineAssembler::LdaContextSlotNoCell(), v8::internal::baseline::BaselineAssembler::LdaModuleVariable(), v8::internal::baseline::BaselineAssembler::StaContextSlotNoCell(), and v8::internal::baseline::BaselineAssembler::StaModuleVariable().
kScopeInfoOffset
const int v8::internal::Context::kScopeInfoOffset = kElementsOffset [static]
Definition at line 503 of file contexts.h.
Referenced by v8::internal::ConstructorBuiltinsAssembler::FastNewFunctionContext().
kTodoHeaderSize
const int v8::internal::Context::kTodoHeaderSize = kPreviousOffset + kTaggedSize [static]
Definition at line 509 of file contexts.h.
Referenced by v8::internal::ConstructorBuiltinsAssembler::FastNewFunctionContext(), and v8::internal::Factory::NewContextInternal().
LAST_FUNCTION_MAP_INDEX
const int v8::internal::Context::LAST_FUNCTION_MAP_INDEX = CLASS_FUNCTION_MAP_INDEX [static]
Definition at line 580 of file contexts.h.
Referenced by v8::internal::compiler::NativeContextRef::GetFunctionMapFromIndex(), and v8::internal::TF_BUILTIN().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/contexts.h
/mnt/V8SourceCode/src/objects/contexts-inl.h
/mnt/V8SourceCode/src/objects/contexts.cc