v8::internal::CodeSerializer Class Reference
#include <code-serializer.h>
Classes
struct OffThreadDeserializeData
Public Member Functions
CodeSerializer (const CodeSerializer &)=delete
CodeSerializer & operator= (const CodeSerializer &)=delete
AlignedCachedData * SerializeSharedFunctionInfo (Handle< SharedFunctionInfo > info)
uint32_t source_hash () const
Static Public Member Functions
static V8_EXPORT_PRIVATE ScriptCompiler::CachedData * Serialize (Isolate *isolate, Handle< SharedFunctionInfo > info)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< SharedFunctionInfo > Deserialize (Isolate *isolate, AlignedCachedData *cached_data, DirectHandle< String > source, const ScriptDetails &script_details, MaybeDirectHandle< Script > maybe_cached_script={})
static V8_WARN_UNUSED_RESULT OffThreadDeserializeData StartDeserializeOffThread (LocalIsolate *isolate, AlignedCachedData *cached_data)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< SharedFunctionInfo > FinishOffThreadDeserialize (Isolate *isolate, OffThreadDeserializeData &&data, AlignedCachedData *cached_data, DirectHandle< String > source, const ScriptDetails &script_details, BackgroundMergeTask *background_merge_task=nullptr)
Protected Member Functions
CodeSerializer (Isolate *isolate, uint32_t source_hash)
~CodeSerializer () override
void SerializeGeneric (Handle< HeapObject > heap_object, SlotType slot_type)
Private Member Functions
void SerializeObjectImpl (Handle< HeapObject > o, SlotType slot_type) override
Private Attributes
uint32_t source_hash_
Additional Inherited Members
Detailed Description
Definition at line 60 of file code-serializer.h.
Constructor & Destructor Documentation
CodeSerializer() [1/2]
v8::internal::CodeSerializer::CodeSerializer (const CodeSerializer &) [delete]
CodeSerializer() [2/2]
v8::internal::CodeSerializer::CodeSerializer (Isolate * isolate, uint32_t source_hash) [protected]
Definition at line 45 of file code-serializer.cc.
    : Serializer(isolate, Snapshot::kDefaultSerializerFlags),
      source_hash_(source_hash) {}
 CodeSerializer()
v8::internal::CodeSerializer::~CodeSerializer () [inline], [override], [protected]
Definition at line 103 of file code-serializer.h.
{ OutputStatistics("CodeSerializer"); }
References v8::internal::Serializer::OutputStatistics().
Member Function Documentation
Deserialize()
MaybeDirectHandle< SharedFunctionInfo > v8::internal::CodeSerializer::Deserialize (Isolate * isolate, AlignedCachedData * cached_data, DirectHandle< String > source, const ScriptDetails & script_details, MaybeDirectHandle< Script > maybe_cached_script = {}) [static]
Definition at line 481 of file code-serializer.cc.
                                                   {
  if (v8_flags.stress_background_compile) {
    StressOffThreadDeserializeThread thread(isolate, cached_data);
    CHECK(thread.Start());
    thread.Join();
    return thread.Finalize(isolate, source, script_details);
    // TODO(leszeks): Compare off-thread deserialized data to on-thread.
  }
  base::ElapsedTimer timer;
  if (v8_flags.profile_deserialization || v8_flags.log_function_events) {
    timer.Start();
  }
  HandleScope scope(isolate);
  DirectHandle<FixedArray> wrapped_arguments;
  if (!script_details.wrapped_arguments.is_null()) {
    wrapped_arguments = script_details.wrapped_arguments.ToHandleChecked();
  }
  SerializedCodeSanityCheckResult sanity_check_result =
      SerializedCodeSanityCheckResult::kSuccess;
  const SerializedCodeData scd = SerializedCodeData::FromCachedData(
      isolate, cached_data,
      SerializedCodeData::SourceHash(source, wrapped_arguments,
                                     script_details.origin_options),
      &sanity_check_result);
  if (sanity_check_result != SerializedCodeSanityCheckResult::kSuccess) {
    if (v8_flags.profile_deserialization) {
      PrintF("[Cached code failed check: %s]\n", ToString(sanity_check_result));
    }
    DCHECK(cached_data->rejected());
    isolate->counters()->code_cache_reject_reason()->AddSample(
        static_cast<int>(sanity_check_result));
    return MaybeDirectHandle<SharedFunctionInfo>();
  }
  // Deserialize.
  MaybeDirectHandle<SharedFunctionInfo> maybe_result =
      ObjectDeserializer::DeserializeSharedFunctionInfo(isolate, &scd, source);
  DirectHandle<SharedFunctionInfo> result;
  if (!maybe_result.ToHandle(&result)) {
    // Deserializing may fail if the reservations cannot be fulfilled.
    if (v8_flags.profile_deserialization) PrintF("[Deserializing failed]\n");
    return MaybeDirectHandle<SharedFunctionInfo>();
  }
  // Check whether the newly deserialized data should be merged into an
  // existing Script from the Isolate compilation cache. If so, perform
  // the merge in a single-threaded manner since this deserialization was
  // single-threaded.
  if (DirectHandle<Script> cached_script;
      maybe_cached_script.ToHandle(&cached_script)) {
    BackgroundMergeTask merge;
    merge.SetUpOnMainThread(isolate, cached_script);
    CHECK(merge.HasPendingBackgroundWork());
    DirectHandle<Script> new_script(Cast<Script>(result->script()), isolate);
    merge.BeginMergeInBackground(isolate->AsLocalIsolate(), new_script);
    CHECK(merge.HasPendingForegroundWork());
    result = merge.CompleteMergeInForeground(isolate, new_script);
  }
  Tagged<Script> script = Cast<Script>(result->script());
  script->set_deserialized(true);
  BaselineBatchCompileIfSparkplugCompiled(isolate, script);
  if (v8_flags.profile_deserialization) {
    double ms = timer.Elapsed().InMillisecondsF();
    int length = cached_data->length();
    PrintF("[Deserializing from %d bytes took %0.3f ms]\n", length, ms);
  }
  FinalizeDeserialization(isolate, result, timer, script_details);
  return scope.CloseAndEscape(result);
}
References v8::internal::Isolate::AsLocalIsolate(), v8::internal::anonymous_namespace{code-serializer.cc}::BaselineBatchCompileIfSparkplugCompiled(), v8::internal::BackgroundMergeTask::BeginMergeInBackground(), CHECK, v8::internal::BackgroundMergeTask::CompleteMergeInForeground(), v8::internal::Isolate::counters(), v8::internal::DCHECK(), v8::internal::ObjectDeserializer::DeserializeSharedFunctionInfo(), v8::base::ElapsedTimer::Elapsed(), v8::internal::anonymous_namespace{code-serializer.cc}::FinalizeDeserialization(), v8::internal::SerializedCodeData::FromCachedData(), v8::internal::BackgroundMergeTask::HasPendingBackgroundWork(), v8::internal::BackgroundMergeTask::HasPendingForegroundWork(), v8::base::TimeDelta::InMillisecondsF(), v8::internal::Serializer::isolate(), v8::internal::detail::kSuccess, v8::internal::length, v8::internal::AlignedCachedData::length(), v8::internal::ScriptDetails::origin_options, v8::internal::PrintF(), v8::internal::AlignedCachedData::rejected(), v8::base::internal::result, v8::internal::script, v8::internal::BackgroundMergeTask::SetUpOnMainThread(), v8::internal::SerializedCodeData::SourceHash(), v8::base::ElapsedTimer::Start(), v8::internal::MaybeDirectHandle< T >::ToHandle(), v8::internal::ToString(), v8::internal::v8_flags, and v8::internal::ScriptDetails::wrapped_arguments.
Referenced by v8::internal::anonymous_namespace{compiler.cc}::GetSharedFunctionInfoForScriptImpl(), and v8::internal::Compiler::GetWrappedFunction().
FinishOffThreadDeserialize()
MaybeDirectHandle< SharedFunctionInfo > v8::internal::CodeSerializer::FinishOffThreadDeserialize (Isolate * isolate, OffThreadDeserializeData && data, AlignedCachedData * cached_data, DirectHandle< String > source, const ScriptDetails & script_details, BackgroundMergeTask * background_merge_task = nullptr) [static]
Definition at line 610 of file code-serializer.cc.
                                                {
  base::ElapsedTimer timer;
  if (v8_flags.profile_deserialization || v8_flags.log_function_events) {
    timer.Start();
  }
  HandleScope scope(isolate);
  DirectHandle<FixedArray> wrapped_arguments;
  if (!script_details.wrapped_arguments.is_null()) {
    wrapped_arguments = script_details.wrapped_arguments.ToHandleChecked();
  }
  // Do a source sanity check now that we have the source. It's important for
  // FromPartiallySanityCheckedCachedData call that the sanity_check_result
  // holds the result of the off-thread sanity check.
  SerializedCodeSanityCheckResult sanity_check_result =
      data.sanity_check_result;
  const SerializedCodeData scd =
      SerializedCodeData::FromPartiallySanityCheckedCachedData(
          cached_data,
          SerializedCodeData::SourceHash(source, wrapped_arguments,
                                         script_details.origin_options),
          &sanity_check_result);
  if (sanity_check_result != SerializedCodeSanityCheckResult::kSuccess) {
    // The only case where the deserialization result could exist despite a
    // check failure is on a source mismatch, since we can't test for this
    // off-thread.
    DCHECK_IMPLIES(!data.maybe_result.is_null(),
                   sanity_check_result ==
                       SerializedCodeSanityCheckResult::kSourceMismatch);
    // The only kind of sanity check we can't test for off-thread is a source
    // mismatch.
    DCHECK_IMPLIES(sanity_check_result != data.sanity_check_result,
                   sanity_check_result ==
                       SerializedCodeSanityCheckResult::kSourceMismatch);
    if (v8_flags.profile_deserialization) {
      PrintF("[Cached code failed check: %s]\n", ToString(sanity_check_result));
    }
    DCHECK(cached_data->rejected());
    isolate->counters()->code_cache_reject_reason()->AddSample(
        static_cast<int>(sanity_check_result));
    return MaybeDirectHandle<SharedFunctionInfo>();
  }
  Handle<SharedFunctionInfo> result;
  if (!data.maybe_result.ToHandle(&result)) {
    // Deserializing may fail if the reservations cannot be fulfilled.
    if (v8_flags.profile_deserialization) {
      PrintF("[Off-thread deserializing failed]\n");
    }
    return MaybeDirectHandle<SharedFunctionInfo>();
  }
  // Change the result persistent handle into a regular handle.
  DCHECK(data.persistent_handles->Contains(result.location()));
  result = handle(*result, isolate);
  if (background_merge_task &&
      background_merge_task->HasPendingForegroundWork()) {
    DCHECK_EQ(data.scripts.size(), 1);
    DirectHandle<Script> new_script = data.scripts[0];
    result =
        background_merge_task->CompleteMergeInForeground(isolate, new_script);
    DCHECK(Object::StrictEquals(Cast<Script>(result->script())->source(),
                                *source));
    DCHECK(isolate->factory()->script_list()->Contains(
        MakeWeak(result->script())));
  } else {
    DirectHandle<Script> result_script(Cast<Script>(result->script()), isolate);
    // Fix up the source on the script. This should be the only deserialized
    // script, and the off-thread deserializer should have set its source to the
    // empty string. In debug mode the code cache does contain the original
    // source.
    DCHECK_EQ(data.scripts.size(), 1);
    DCHECK_EQ(*result_script, *data.scripts[0]);
#ifdef DEBUG
    if (!Cast<String>(result_script->source())->Equals(*source)) {
      isolate->PushStackTraceAndDie(
          reinterpret_cast<void*>(result_script->source().ptr()),
          reinterpret_cast<void*>(source->ptr()));
    }
#else
    CHECK_EQ(result_script->source(), ReadOnlyRoots(isolate).empty_string());
#endif
    Script::SetSource(isolate, result_script, source);
    // Fix up the script list to include the newly deserialized script.
    Handle<WeakArrayList> list = isolate->factory()->script_list();
    for (Handle<Script> script : data.scripts) {
      script->set_deserialized(true);
      BaselineBatchCompileIfSparkplugCompiled(isolate, *script);
      DCHECK(data.persistent_handles->Contains(script.location()));
      list = WeakArrayList::AddToEnd(isolate, list,
                                     MaybeObjectDirectHandle::Weak(script));
    }
    isolate->heap()->SetRootScriptList(*list);
  }
  if (v8_flags.profile_deserialization) {
    double ms = timer.Elapsed().InMillisecondsF();
    int length = cached_data->length();
    PrintF("[Finishing off-thread deserialize from %d bytes took %0.3f ms]\n",
           length, ms);
  }
  FinalizeDeserialization(isolate, result, timer, script_details);
  DCHECK(!background_merge_task ||
         !background_merge_task->HasPendingForegroundWork());
  return scope.CloseAndEscape(result);
}
References v8::internal::WeakArrayList::AddToEnd(), v8::internal::anonymous_namespace{code-serializer.cc}::BaselineBatchCompileIfSparkplugCompiled(), CHECK_EQ, v8::internal::BackgroundMergeTask::CompleteMergeInForeground(), v8::internal::Isolate::counters(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::base::ElapsedTimer::Elapsed(), v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{code-serializer.cc}::FinalizeDeserialization(), v8::internal::SerializedCodeData::FromPartiallySanityCheckedCachedData(), v8::internal::handle(), v8::internal::BackgroundMergeTask::HasPendingForegroundWork(), v8::internal::Isolate::heap(), v8::base::TimeDelta::InMillisecondsF(), v8::internal::Serializer::isolate(), v8::internal::detail::kSuccess, v8::internal::length, v8::internal::AlignedCachedData::length(), v8::internal::MakeWeak(), v8::internal::ScriptDetails::origin_options, v8::internal::PrintF(), v8::internal::Isolate::PushStackTraceAndDie(), v8::internal::AlignedCachedData::rejected(), v8::base::internal::result, v8::internal::script, v8::internal::Heap::SetRootScriptList(), v8::internal::Script::SetSource(), v8::internal::SerializedCodeData::SourceHash(), v8::base::ElapsedTimer::Start(), v8::internal::Object::StrictEquals(), v8::internal::ToString(), v8::internal::v8_flags, v8::internal::MaybeObjectDirectHandle::Weak(), and v8::internal::ScriptDetails::wrapped_arguments.
Referenced by v8::internal::anonymous_namespace{code-serializer.cc}::StressOffThreadDeserializeThread::Finalize(), and v8::internal::BackgroundDeserializeTask::Finish().
operator=()
CodeSerializer& v8::internal::CodeSerializer::operator= (const CodeSerializer &) [delete]
Serialize()
ScriptCompiler::CachedData * v8::internal::CodeSerializer::Serialize (Isolate * isolate, Handle< SharedFunctionInfo > info) [static]
Definition at line 50 of file code-serializer.cc.
                                                       {
  TRACE_EVENT_CALL_STATS_SCOPED(isolate, "v8", "V8.SerializeCode");
  NestedTimedHistogramScope histogram_timer(
      isolate->counters()->compile_serialize());
  RCS_SCOPE(isolate, RuntimeCallCounterId::kCompileSerialize);
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"), "V8.CompileSerialize");
  base::ElapsedTimer timer;
  if (v8_flags.profile_deserialization) timer.Start();
  DirectHandle<Script> script(Cast<Script>(info->script()), isolate);
  if (v8_flags.trace_serializer) {
    PrintF("[Serializing from");
    ShortPrint(script->name());
    PrintF("]\n");
  }
#if V8_ENABLE_WEBASSEMBLY
  // TODO(7110): Enable serialization of Asm modules once the AsmWasmData is
  // context independent.
  if (script->ContainsAsmModule()) return nullptr;
#endif // V8_ENABLE_WEBASSEMBLY
  // Serialize code object.
  DirectHandle<String> source(Cast<String>(script->source()), isolate);
  DirectHandle<FixedArray> wrapped_arguments;
  if (script->is_wrapped()) {
    wrapped_arguments =
        DirectHandle<FixedArray>(script->wrapped_arguments(), isolate);
  }
  HandleScope scope(isolate);
  CodeSerializer cs(isolate,
                    SerializedCodeData::SourceHash(source, wrapped_arguments,
                                                   script->origin_options()));
  DisallowGarbageCollection no_gc;
#ifndef DEBUG
  cs.reference_map()->AddAttachedReference(*source);
#endif
  AlignedCachedData* cached_data = cs.SerializeSharedFunctionInfo(info);
  if (v8_flags.profile_deserialization) {
    double ms = timer.Elapsed().InMillisecondsF();
    int length = cached_data->length();
    PrintF("[Serializing to %d bytes took %0.3f ms]\n", length, ms);
  }
  ScriptCompiler::CachedData* result =
      new ScriptCompiler::CachedData(cached_data->data(), cached_data->length(),
                                     ScriptCompiler::CachedData::BufferOwned);
  cached_data->ReleaseDataOwnership();
  delete cached_data;
  return result;
}
References v8::ScriptCompiler::CachedData::BufferOwned, v8::internal::Isolate::counters(), v8::internal::cs, v8::internal::AlignedCachedData::data(), v8::base::ElapsedTimer::Elapsed(), v8::base::TimeDelta::InMillisecondsF(), v8::internal::Serializer::isolate(), v8::internal::length, v8::internal::AlignedCachedData::length(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::PrintF(), RCS_SCOPE, v8::internal::AlignedCachedData::ReleaseDataOwnership(), v8::base::internal::result, v8::internal::script, v8::internal::ShortPrint(), v8::internal::SerializedCodeData::SourceHash(), v8::base::ElapsedTimer::Start(), TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT0, TRACE_EVENT_CALL_STATS_SCOPED, and v8::internal::v8_flags.
Referenced by v8::ScriptCompiler::CreateCodeCache(), and v8::ScriptCompiler::CreateCodeCacheForFunction().
SerializeGeneric()
void v8::internal::CodeSerializer::SerializeGeneric (Handle< HeapObject > heap_object, SlotType slot_type) [protected]
Definition at line 281 of file code-serializer.cc.
                                                          {
  // Object has not yet been serialized. Serialize it here.
  ObjectSerializer serializer(this, heap_object, &sink_);
  serializer.Serialize(slot_type);
}
References v8::internal::Serializer::ObjectSerializer::Serialize(), and v8::internal::Serializer::sink_.
Referenced by SerializeObjectImpl().
SerializeObjectImpl()
void v8::internal::CodeSerializer::SerializeObjectImpl (Handle< HeapObject > o, SlotType slot_type) [override], [private], [virtual]
Implements v8::internal::Serializer.
Definition at line 120 of file code-serializer.cc.
                                                             {
  ReadOnlyRoots roots(isolate());
  InstanceType instance_type;
  {
    DisallowGarbageCollection no_gc;
    Tagged<HeapObject> raw = *obj;
    if (SerializeHotObject(raw)) return;
    if (SerializeRoot(raw)) return;
    if (SerializeBackReference(raw)) return;
    if (SerializeReadOnlyObjectReference(raw, &sink_)) return;
    instance_type = raw->map()->instance_type();
    CHECK(!InstanceTypeChecker::IsInstructionStream(instance_type));
  }
  if (InstanceTypeChecker::IsScript(instance_type)) {
    DirectHandle<FixedArray> host_options;
    DirectHandle<UnionOf<Smi, Symbol, Undefined>> context_data;
    {
      DisallowGarbageCollection no_gc;
      Tagged<Script> script_obj = Cast<Script>(*obj);
      DCHECK_NE(script_obj->compilation_type(), Script::CompilationType::kEval);
      // We want to differentiate between undefined and uninitialized_symbol for
      // context_data for now. It is hack to allow debugging for scripts that
      // are included as a part of custom snapshot. (see
      // debug::Script::IsEmbedded())
      Tagged<UnionOf<Smi, Symbol, Undefined>> raw_context_data =
          script_obj->context_data();
      if (raw_context_data != roots.undefined_value() &&
          raw_context_data != roots.uninitialized_symbol()) {
        script_obj->set_context_data(roots.undefined_value());
      }
      context_data = direct_handle(raw_context_data, isolate());
      // We don't want to serialize host options to avoid serializing
      // unnecessary object graph.
      host_options =
          direct_handle(script_obj->host_defined_options(), isolate());
      script_obj->set_host_defined_options(roots.empty_fixed_array());
    }
    SerializeGeneric(obj, slot_type);
    {
      DisallowGarbageCollection no_gc;
      Tagged<Script> script_obj = Cast<Script>(*obj);
      script_obj->set_host_defined_options(*host_options);
      script_obj->set_context_data(*context_data);
    }
    return;
  } else if (InstanceTypeChecker::IsSharedFunctionInfo(instance_type)) {
    DirectHandle<DebugInfo> debug_info;
    CachedTieringDecision cached_tiering_decision;
    bool restore_bytecode = false;
    {
      DisallowGarbageCollection no_gc;
      Tagged<SharedFunctionInfo> sfi = Cast<SharedFunctionInfo>(*obj);
      DCHECK(!sfi->IsApiFunction());
#if V8_ENABLE_WEBASSEMBLY
      // TODO(7110): Enable serializing of Asm modules once the AsmWasmData
      // is context independent.
      DCHECK(!sfi->HasAsmWasmData());
#endif // V8_ENABLE_WEBASSEMBLY
      if (auto maybe_debug_info = sfi->TryGetDebugInfo(isolate())) {
        debug_info = direct_handle(maybe_debug_info.value(), isolate());
        // Clear debug info.
        if (debug_info->HasInstrumentedBytecodeArray()) {
          restore_bytecode = true;
          sfi->SetActiveBytecodeArray(
              debug_info->OriginalBytecodeArray(isolate()), isolate());
        }
      }
      if (v8_flags.profile_guided_optimization) {
        cached_tiering_decision = sfi->cached_tiering_decision();
        if (cached_tiering_decision > CachedTieringDecision::kEarlySparkplug) {
          sfi->set_cached_tiering_decision(
              CachedTieringDecision::kEarlySparkplug);
        }
      }
    }
    SerializeGeneric(obj, slot_type);
    DisallowGarbageCollection no_gc;
    Tagged<SharedFunctionInfo> sfi = Cast<SharedFunctionInfo>(*obj);
    if (restore_bytecode) {
      sfi->SetActiveBytecodeArray(debug_info->DebugBytecodeArray(isolate()),
                                  isolate());
    }
    if (v8_flags.profile_guided_optimization &&
        cached_tiering_decision > CachedTieringDecision::kEarlySparkplug) {
      sfi->set_cached_tiering_decision(cached_tiering_decision);
    }
    return;
  } else if (InstanceTypeChecker::IsUncompiledDataWithoutPreparseDataWithJob(
                 instance_type)) {
    Handle<UncompiledDataWithoutPreparseDataWithJob> data =
        Cast<UncompiledDataWithoutPreparseDataWithJob>(obj);
    Address job = data->job();
    data->set_job(kNullAddress);
    SerializeGeneric(data, slot_type);
    data->set_job(job);
    return;
  } else if (InstanceTypeChecker::IsUncompiledDataWithPreparseDataAndJob(
                 instance_type)) {
    Handle<UncompiledDataWithPreparseDataAndJob> data =
        Cast<UncompiledDataWithPreparseDataAndJob>(obj);
    Address job = data->job();
    data->set_job(kNullAddress);
    SerializeGeneric(data, slot_type);
    data->set_job(job);
    return;
  } else if (InstanceTypeChecker::IsScopeInfo(instance_type)) {
    // TODO(ishell): define a dedicated instance type for DependentCode and
    // serialize DependentCode objects as an empty_dependent_code instead
    // of customizing ScopeInfo serialization.
    static_assert(DEPENDENT_CODE_TYPE == WEAK_ARRAY_LIST_TYPE);
    Handle<ScopeInfo> scope_info = Cast<ScopeInfo>(obj);
    DirectHandle<DependentCode> dependent_code;
    bool restore_dependent_code = false;
    if (scope_info->SloppyEvalCanExtendVars()) {
      // If |scope_info| has a dependent code field, serialize it as an empty
      // dependent code in order to avoid accidental serialization of optimized
      // code.
      Tagged<DependentCode> empty_dependent_code =
          DependentCode::empty_dependent_code(ReadOnlyRoots(isolate()));
      if (scope_info->dependent_code() != empty_dependent_code) {
        dependent_code = direct_handle(scope_info->dependent_code(), isolate());
        restore_dependent_code = true;
        scope_info->set_dependent_code(empty_dependent_code);
      }
    }
    SerializeGeneric(scope_info, slot_type);
    if (restore_dependent_code) {
      scope_info->set_dependent_code(*dependent_code);
    }
    return;
  }
  // NOTE(mmarchini): If we try to serialize an InterpreterData our process
  // will crash since it stores a code object. Instead, we serialize the
  // bytecode array stored within the InterpreterData, which is the important
  // information. On deserialization we'll create our code objects again, if
  // --interpreted-frames-native-stack is on. See v8:9122 for more context
  if (V8_UNLIKELY(isolate()->interpreted_frames_native_stack()) &&
      IsInterpreterData(*obj)) {
    obj = handle(Cast<InterpreterData>(*obj)->bytecode_array(), isolate());
  }
  // Past this point we should not see any (context-specific) maps anymore.
  CHECK(!InstanceTypeChecker::IsMap(instance_type));
  // There should be no references to the global object embedded.
  CHECK(!InstanceTypeChecker::IsJSGlobalProxy(instance_type) &&
        !InstanceTypeChecker::IsJSGlobalObject(instance_type));
  // Embedded FixedArrays that need rehashing must support rehashing.
  CHECK_IMPLIES(obj->NeedsRehashing(cage_base()),
                obj->CanBeRehashed(cage_base()));
  // We expect no instantiated function objects or contexts.
  CHECK(!InstanceTypeChecker::IsJSFunction(instance_type) &&
        !InstanceTypeChecker::IsContext(instance_type));
  SerializeGeneric(obj, slot_type);
}
References v8::internal::Serializer::cage_base(), CHECK, CHECK_IMPLIES, v8::internal::DCHECK(), DCHECK_NE, v8::internal::DEPENDENT_CODE_TYPE, v8::internal::direct_handle(), v8::internal::DependentCode::empty_dependent_code(), v8::internal::handle(), v8::internal::Serializer::isolate(), v8::internal::kEarlySparkplug, v8::internal::Script::kEval, v8::internal::kNullAddress, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Serializer::SerializeBackReference(), SerializeGeneric(), v8::internal::Serializer::SerializeHotObject(), v8::internal::Serializer::SerializeReadOnlyObjectReference(), v8::internal::Serializer::SerializeRoot(), v8::internal::Serializer::sink_, v8::internal::v8_flags, and V8_UNLIKELY.
SerializeSharedFunctionInfo()
AlignedCachedData * v8::internal::CodeSerializer::SerializeSharedFunctionInfo (Handle< SharedFunctionInfo > info)
Definition at line 106 of file code-serializer.cc.
                                     {
  DisallowGarbageCollection no_gc;
  VisitRootPointer(Root::kHandleScope, nullptr,
                   FullObjectSlot(info.location()));
  SerializeDeferredObjects();
  Pad();
  SerializedCodeData data(sink_.data(), this);
  return data.GetScriptData();
}
References v8::internal::SnapshotByteSink::data(), v8::internal::SerializedCodeData::GetScriptData(), v8::internal::HandleBase::location(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Serializer::Pad(), v8::internal::Serializer::SerializeDeferredObjects(), v8::internal::Serializer::sink_, and v8::internal::RootVisitor::VisitRootPointer().
source_hash()
uint32_t v8::internal::CodeSerializer::source_hash () const [inline]
Definition at line 99 of file code-serializer.h.
{ return source_hash_; }
References source_hash_.
Referenced by v8::internal::SerializedCodeData::SanityCheckJustSource().
StartDeserializeOffThread()
CodeSerializer::OffThreadDeserializeData v8::internal::CodeSerializer::StartDeserializeOffThread (LocalIsolate * isolate, AlignedCachedData * cached_data) [static]
Definition at line 582 of file code-serializer.cc.
                                                                          {
  OffThreadDeserializeData result;
  DCHECK(!local_isolate->heap()->HasPersistentHandles());
  const SerializedCodeData scd =
      SerializedCodeData::FromCachedDataWithoutSource(
          local_isolate, cached_data, &result.sanity_check_result);
  if (result.sanity_check_result != SerializedCodeSanityCheckResult::kSuccess) {
    // Exit early but don't report yet, we'll re-check this when finishing on
    // the main thread
    DCHECK(cached_data->rejected());
    return result;
  }
  MaybeDirectHandle<SharedFunctionInfo> local_maybe_result =
      OffThreadObjectDeserializer::DeserializeSharedFunctionInfo(
          local_isolate, &scd, &result.scripts);
  result.maybe_result =
      local_isolate->heap()->NewPersistentMaybeHandle(local_maybe_result);
  result.persistent_handles = local_isolate->heap()->DetachPersistentHandles();
  return result;
}
References v8::internal::DCHECK(), v8::internal::OffThreadObjectDeserializer::DeserializeSharedFunctionInfo(), v8::internal::LocalHeap::DetachPersistentHandles(), v8::internal::SerializedCodeData::FromCachedDataWithoutSource(), v8::internal::LocalIsolate::heap(), v8::internal::detail::kSuccess, v8::internal::LocalHeap::NewPersistentMaybeHandle(), v8::internal::AlignedCachedData::rejected(), and v8::base::internal::result.
Referenced by v8::internal::BackgroundDeserializeTask::Run(), and v8::internal::anonymous_namespace{code-serializer.cc}::StressOffThreadDeserializeThread::Run().
Member Data Documentation
source_hash_
uint32_t v8::internal::CodeSerializer::source_hash_ [private]
Definition at line 111 of file code-serializer.h.
Referenced by source_hash().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/snapshot/code-serializer.h
/mnt/V8SourceCode/src/snapshot/code-serializer.cc