v8::internal::CodeFactory Class Reference
#include <code-factory.h>
Static Public Member Functions
static DirectHandle< Code > RuntimeCEntry (Isolate *isolate, int result_size=1, bool switch_to_central_stack=false)
static Handle< Code > CEntry (Isolate *isolate, int result_size=1, ArgvMode argv_mode=ArgvMode::kStack, bool builtin_exit_frame=false, bool switch_to_central_stack=false)
static Callable LoadGlobalIC (Isolate *isolate, TypeofMode typeof_mode)
static Callable LoadGlobalICInOptimizedCode (Isolate *isolate, TypeofMode typeof_mode)
static Callable DefineNamedOwnIC (Isolate *isolate)
static Callable DefineNamedOwnICInOptimizedCode (Isolate *isolate)
static Callable CallApiCallback (Isolate *isolate)
static Callable StringAdd (Isolate *isolate, StringAddFlags flags=STRING_ADD_CHECK_NONE)
static Callable FastNewFunctionContext (Isolate *isolate, ScopeType scope_type)
static Callable Call (Isolate *isolate, ConvertReceiverMode mode=ConvertReceiverMode::kAny)
static Callable Call_WithFeedback (Isolate *isolate, ConvertReceiverMode mode)
static Callable CallWithArrayLike (Isolate *isolate)
static Callable CallWithSpread (Isolate *isolate)
static Callable CallFunction (Isolate *isolate, ConvertReceiverMode mode=ConvertReceiverMode::kAny)
static Callable CallForwardVarargs (Isolate *isolate)
static Callable CallFunctionForwardVarargs (Isolate *isolate)
static Callable Construct (Isolate *isolate)
static Callable ConstructWithSpread (Isolate *isolate)
static Callable ConstructForwardVarargs (Isolate *isolate)
static Callable ConstructFunctionForwardVarargs (Isolate *isolate)
static Callable ArrayNoArgumentConstructor (Isolate *isolate, ElementsKind kind, AllocationSiteOverrideMode override_mode)
static Callable ArraySingleArgumentConstructor (Isolate *isolate, ElementsKind kind, AllocationSiteOverrideMode override_mode)
Detailed Description
Definition at line 22 of file code-factory.h.
Member Function Documentation
ArrayNoArgumentConstructor()
Callable v8::internal::CodeFactory::ArrayNoArgumentConstructor (Isolate * isolate, ElementsKind kind, AllocationSiteOverrideMode override_mode) [static]
Definition at line 142 of file code-factory.cc.
                                              {
#define CASE(kind_caps, kind_camel, mode_camel) \
  case kind_caps: \
    return Builtins::CallableFor(\
        isolate, \
        Builtin::kArrayNoArgumentConstructor_##kind_camel##_##mode_camel);
  if (override_mode == DONT_OVERRIDE && AllocationSite::ShouldTrack(kind)) {
    DCHECK(IsSmiElementsKind(kind));
    switch (kind) {
      CASE(PACKED_SMI_ELEMENTS, PackedSmi, DontOverride);
      CASE(HOLEY_SMI_ELEMENTS, HoleySmi, DontOverride);
      default:
        UNREACHABLE();
    }
  } else {
    DCHECK(override_mode == DISABLE_ALLOCATION_SITES ||
           !AllocationSite::ShouldTrack(kind));
    switch (kind) {
      CASE(PACKED_SMI_ELEMENTS, PackedSmi, DisableAllocationSites);
      CASE(HOLEY_SMI_ELEMENTS, HoleySmi, DisableAllocationSites);
      CASE(PACKED_ELEMENTS, Packed, DisableAllocationSites);
      CASE(HOLEY_ELEMENTS, Holey, DisableAllocationSites);
      CASE(PACKED_DOUBLE_ELEMENTS, PackedDouble, DisableAllocationSites);
      CASE(HOLEY_DOUBLE_ELEMENTS, HoleyDouble, DisableAllocationSites);
      default:
        UNREACHABLE();
    }
  }
#undef CASE
}
References CASE, v8::internal::DCHECK(), v8::internal::DISABLE_ALLOCATION_SITES, v8::internal::DisableAllocationSites, v8::internal::DONT_OVERRIDE, v8::internal::DontOverride, v8::internal::Holey, v8::internal::HOLEY_DOUBLE_ELEMENTS, v8::internal::HOLEY_ELEMENTS, v8::internal::HOLEY_SMI_ELEMENTS, v8::internal::HoleyDouble, v8::internal::HoleySmi, v8::internal::IsSmiElementsKind(), v8::internal::PACKED_DOUBLE_ELEMENTS, v8::internal::PACKED_ELEMENTS, v8::internal::PACKED_SMI_ELEMENTS, v8::internal::AllocationSite::ShouldTrack(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::ArrayBuiltinsAssembler::CreateArrayDispatchNoArgument().
ArraySingleArgumentConstructor()
Callable v8::internal::CodeFactory::ArraySingleArgumentConstructor (Isolate * isolate, ElementsKind kind, AllocationSiteOverrideMode override_mode) [static]
Definition at line 176 of file code-factory.cc.
                                              {
#define CASE(kind_caps, kind_camel, mode_camel) \
  case kind_caps: \
    return Builtins::CallableFor(\
        isolate, \
        Builtin::kArraySingleArgumentConstructor_##kind_camel##_##mode_camel)
  if (override_mode == DONT_OVERRIDE && AllocationSite::ShouldTrack(kind)) {
    DCHECK(IsSmiElementsKind(kind));
    switch (kind) {
      CASE(PACKED_SMI_ELEMENTS, PackedSmi, DontOverride);
      CASE(HOLEY_SMI_ELEMENTS, HoleySmi, DontOverride);
      default:
        UNREACHABLE();
    }
  } else {
    DCHECK(override_mode == DISABLE_ALLOCATION_SITES ||
           !AllocationSite::ShouldTrack(kind));
    switch (kind) {
      CASE(PACKED_SMI_ELEMENTS, PackedSmi, DisableAllocationSites);
      CASE(HOLEY_SMI_ELEMENTS, HoleySmi, DisableAllocationSites);
      CASE(PACKED_ELEMENTS, Packed, DisableAllocationSites);
      CASE(HOLEY_ELEMENTS, Holey, DisableAllocationSites);
      CASE(PACKED_DOUBLE_ELEMENTS, PackedDouble, DisableAllocationSites);
      CASE(HOLEY_DOUBLE_ELEMENTS, HoleyDouble, DisableAllocationSites);
      default:
        UNREACHABLE();
    }
  }
#undef CASE
}
References CASE, v8::internal::DCHECK(), v8::internal::DISABLE_ALLOCATION_SITES, v8::internal::DisableAllocationSites, v8::internal::DONT_OVERRIDE, v8::internal::DontOverride, v8::internal::Holey, v8::internal::HOLEY_DOUBLE_ELEMENTS, v8::internal::HOLEY_ELEMENTS, v8::internal::HOLEY_SMI_ELEMENTS, v8::internal::HoleyDouble, v8::internal::HoleySmi, v8::internal::IsSmiElementsKind(), v8::internal::PACKED_DOUBLE_ELEMENTS, v8::internal::PACKED_ELEMENTS, v8::internal::PACKED_SMI_ELEMENTS, v8::internal::AllocationSite::ShouldTrack(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::ArrayBuiltinsAssembler::CreateArrayDispatchSingleArgument().
Call()
Callable v8::internal::CodeFactory::Call (Isolate * isolate, ConvertReceiverMode mode = ConvertReceiverMode::kAny) [static]
Definition at line 74 of file code-factory.cc.
                                                                     {
  return Builtins::CallableFor(isolate, Builtins::Call(mode));
}
References v8::internal::Builtins::Call(), v8::internal::Builtins::CallableFor(), and mode().
Call_WithFeedback()
Callable v8::internal::CodeFactory::Call_WithFeedback (Isolate * isolate, ConvertReceiverMode mode) [static]
Definition at line 79 of file code-factory.cc.
                                                                  {
  switch (mode) {
    case ConvertReceiverMode::kNullOrUndefined:
      return Builtins::CallableFor(
          isolate, Builtin::kCall_ReceiverIsNullOrUndefined_WithFeedback);
    case ConvertReceiverMode::kNotNullOrUndefined:
      return Builtins::CallableFor(
          isolate, Builtin::kCall_ReceiverIsNotNullOrUndefined_WithFeedback);
    case ConvertReceiverMode::kAny:
      return Builtins::CallableFor(isolate,
                                   Builtin::kCall_ReceiverIsAny_WithFeedback);
  }
  UNREACHABLE();
}
References v8::internal::Builtins::CallableFor(), v8::internal::kAny, v8::internal::kNotNullOrUndefined, v8::internal::kNullOrUndefined, mode(), and v8::internal::UNREACHABLE().
CallApiCallback()
static Callable v8::internal::CodeFactory::CallApiCallback (Isolate * isolate) [static]
CallForwardVarargs()
Callable v8::internal::CodeFactory::CallForwardVarargs (Isolate * isolate) [static]
Definition at line 111 of file code-factory.cc.
                                                         {
  return Builtins::CallableFor(isolate, Builtin::kCallForwardVarargs);
}
References v8::internal::Builtins::CallableFor().
CallFunction()
Callable v8::internal::CodeFactory::CallFunction (Isolate * isolate, ConvertReceiverMode mode = ConvertReceiverMode::kAny) [static]
Definition at line 106 of file code-factory.cc.
                                                                             {
  return Builtins::CallableFor(isolate, Builtins::CallFunction(mode));
}
References v8::internal::Builtins::CallableFor(), v8::internal::Builtins::CallFunction(), and mode().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSCall().
CallFunctionForwardVarargs()
Callable v8::internal::CodeFactory::CallFunctionForwardVarargs (Isolate * isolate) [static]
Definition at line 116 of file code-factory.cc.
                                                                 {
  return Builtins::CallableFor(isolate, Builtin::kCallFunctionForwardVarargs);
}
References v8::internal::Builtins::CallableFor().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSCallForwardVarargs().
CallWithArrayLike()
Callable v8::internal::CodeFactory::CallWithArrayLike (Isolate * isolate) [static]
Definition at line 96 of file code-factory.cc.
                                                        {
  return Builtins::CallableFor(isolate, Builtin::kCallWithArrayLike);
}
References v8::internal::Builtins::CallableFor().
CallWithSpread()
Callable v8::internal::CodeFactory::CallWithSpread (Isolate * isolate) [static]
Definition at line 101 of file code-factory.cc.
                                                     {
  return Builtins::CallableFor(isolate, Builtin::kCallWithSpread);
}
References v8::internal::Builtins::CallableFor().
CEntry()
Handle< Code > v8::internal::CodeFactory::CEntry (Isolate * isolate, int result_size = 1, ArgvMode argv_mode = ArgvMode::kStack, bool builtin_exit_frame = false, bool switch_to_central_stack = false) [static]
Definition at line 25 of file code-factory.cc.
                                                               {
  Builtin builtin = Builtins::CEntry(result_size, argv_mode, builtin_exit_frame,
                                     switch_to_central_stack);
  return isolate->builtins()->code_handle(builtin);
}
References v8::internal::Isolate::builtins(), v8::internal::Builtins::CEntry(), and v8::internal::Builtins::code_handle().
Referenced by v8::internal::compiler::JSGraph::CEntryStubConstant(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CEntryStubConstant(), and RuntimeCEntry().
Construct()
Callable v8::internal::CodeFactory::Construct (Isolate * isolate) [static]
Definition at line 121 of file code-factory.cc.
                                                {
  return Builtins::CallableFor(isolate, Builtin::kConstruct);
}
References v8::internal::Builtins::CallableFor().
ConstructForwardVarargs()
Callable v8::internal::CodeFactory::ConstructForwardVarargs (Isolate * isolate) [static]
Definition at line 131 of file code-factory.cc.
                                                              {
  return Builtins::CallableFor(isolate, Builtin::kConstructForwardVarargs);
}
References v8::internal::Builtins::CallableFor().
ConstructFunctionForwardVarargs()
Callable v8::internal::CodeFactory::ConstructFunctionForwardVarargs (Isolate * isolate) [static]
Definition at line 136 of file code-factory.cc.
                                                                      {
  return Builtins::CallableFor(isolate,
                               Builtin::kConstructFunctionForwardVarargs);
}
References v8::internal::Builtins::CallableFor().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSConstructForwardVarargs().
ConstructWithSpread()
Callable v8::internal::CodeFactory::ConstructWithSpread (Isolate * isolate) [static]
Definition at line 126 of file code-factory.cc.
                                                          {
  return Builtins::CallableFor(isolate, Builtin::kConstructWithSpread);
}
References v8::internal::Builtins::CallableFor().
DefineNamedOwnIC()
Callable v8::internal::CodeFactory::DefineNamedOwnIC (Isolate * isolate) [static]
Definition at line 45 of file code-factory.cc.
                                                       {
  return Builtins::CallableFor(isolate, Builtin::kDefineNamedOwnICTrampoline);
}
References v8::internal::Builtins::CallableFor().
DefineNamedOwnICInOptimizedCode()
Callable v8::internal::CodeFactory::DefineNamedOwnICInOptimizedCode (Isolate * isolate) [static]
Definition at line 49 of file code-factory.cc.
                                                                      {
  return Builtins::CallableFor(isolate, Builtin::kDefineNamedOwnIC);
}
References v8::internal::Builtins::CallableFor().
FastNewFunctionContext()
Callable v8::internal::CodeFactory::FastNewFunctionContext (Isolate * isolate, ScopeType scope_type) [static]
Definition at line 59 of file code-factory.cc.
                                                                   {
  switch (scope_type) {
    case ScopeType::EVAL_SCOPE:
      return Builtins::CallableFor(isolate,
                                   Builtin::kFastNewFunctionContextEval);
    case ScopeType::FUNCTION_SCOPE:
      return Builtins::CallableFor(isolate,
                                   Builtin::kFastNewFunctionContextFunction);
    default:
      UNREACHABLE();
  }
}
References v8::internal::Builtins::CallableFor(), v8::internal::EVAL_SCOPE, v8::internal::FUNCTION_SCOPE, and v8::internal::UNREACHABLE().
LoadGlobalIC()
Callable v8::internal::CodeFactory::LoadGlobalIC (Isolate * isolate, TypeofMode typeof_mode) [static]
Definition at line 34 of file code-factory.cc.
                                                                           {
  return Builtins::CallableFor(isolate, Builtins::LoadGlobalIC(typeof_mode));
}
References v8::internal::Builtins::CallableFor(), and v8::internal::Builtins::LoadGlobalIC().
LoadGlobalICInOptimizedCode()
Callable v8::internal::CodeFactory::LoadGlobalICInOptimizedCode (Isolate * isolate, TypeofMode typeof_mode) [static]
Definition at line 39 of file code-factory.cc.
                                                                          {
  return Builtins::CallableFor(
      isolate, Builtins::LoadGlobalICInOptimizedCode(typeof_mode));
}
References v8::internal::Builtins::CallableFor(), and v8::internal::Builtins::LoadGlobalICInOptimizedCode().
RuntimeCEntry()
DirectHandle< Code > v8::internal::CodeFactory::RuntimeCEntry (Isolate * isolate, int result_size = 1, bool switch_to_central_stack = false) [static]
Definition at line 18 of file code-factory.cc.
                                                                            {
  return CodeFactory::CEntry(isolate, result_size, ArgvMode::kStack, false,
                             switch_to_central_stack);
}
References CEntry(), and v8::internal::kStack.
StringAdd()
Callable v8::internal::CodeFactory::StringAdd (Isolate * isolate, StringAddFlags flags = STRING_ADD_CHECK_NONE) [static]
Definition at line 54 of file code-factory.cc.
                                                                      {
  return Builtins::CallableFor(isolate, Builtins::StringAdd(flags));
}
References v8::internal::Builtins::CallableFor(), v8::internal::flags, and v8::internal::Builtins::StringAdd().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSAdd().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/code-factory.h
/mnt/V8SourceCode/src/codegen/code-factory.cc