v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator Class Reference
Public Member Functions
CppClassGenerator (const ClassType *type, std::ostream &header, std::ostream &inl_header, std::ostream &impl)
const std::string template_decl () const
void GenerateClass ()
void GenerateCppObjectDefinitionAsserts ()
void GenerateCppObjectLayoutDefinitionAsserts ()
Private Member Functions
SourcePosition Position ()
void GenerateClassConstructors ()
void GenerateFieldAccessors (const Field &class_field, std::vector< const Field * > &struct_fields)
void EmitLoadFieldStatement (std::ostream &stream, const Field &class_field, std::vector< const Field * > &struct_fields)
void EmitStoreFieldStatement (std::ostream &stream, const Field &class_field, std::vector< const Field * > &struct_fields)
std::string GetFieldOffsetForAccessor (const Field &f)
std::string GetTypeNameForAccessor (const Field &f)
bool CanContainHeapObjects (const Type *t)
Private Attributes
const ClassType * type_
const ClassType * super_
const std::string name_
const std::string gen_name_
const std::string gen_name_T_
const std::string gen_name_I_
std::ostream & hdr_
std::ostream & inl_
std::ostream & impl_
Detailed Description
Definition at line 4099 of file implementation-visitor.cc.
Constructor & Destructor Documentation
CppClassGenerator()
v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::CppClassGenerator (const ClassType * type, std::ostream & header, std::ostream & inl_header, std::ostream & impl) [inline]
Definition at line 4101 of file implementation-visitor.cc.
      : type_(type),
        super_(type->GetSuperClass()),
        name_(type->name()),
        gen_name_("TorqueGenerated" + name_),
        gen_name_T_(gen_name_ + "<D, P>"),
        gen_name_I_(gen_name_ + "<" + name_ + ", " + super_->name() + ">"),
        hdr_(header),
        inl_(inl_header),
        impl_(impl) {}
Member Function Documentation
CanContainHeapObjects()
bool v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::CanContainHeapObjects (const Type * t) [private]
Definition at line 4654 of file implementation-visitor.cc.
                                                           {
  return t->IsSubtypeOf(TypeOracle::GetTaggedType()) &&
         !t->IsSubtypeOf(TypeOracle::GetSmiType());
}
References v8::internal::torque::Type::IsSubtypeOf().
EmitLoadFieldStatement()
void v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::EmitLoadFieldStatement (std::ostream & stream, const Field & class_field, std::vector< const Field * > & struct_fields) [private]
Definition at line 4659 of file implementation-visitor.cc.
                                            {
  const Field& innermost_field =
      struct_fields.empty() ? class_field : *struct_fields.back();
  const Type* field_type = innermost_field.name_and_type.type;
  std::string type_name = GetTypeNameForAccessor(innermost_field);
  const std::string class_field_size =
      std::get<1>(class_field.GetFieldSizeInformation());
  // field_offset contains both the offset from the beginning of the object to
  // the class field and the combined offsets of any nested struct fields
  // within, but not the index adjustment.
  std::string field_offset = GetFieldOffsetForAccessor(class_field);
  for (const Field* nested_struct_field : struct_fields) {
    field_offset += " + " + std::to_string(*nested_struct_field->offset);
  }
  std::string offset = field_offset;
  if (class_field.index) {
    const char* index = class_field.index->optional ? "0" : "i";
    GenerateBoundsDCheck(stream, index, type_, class_field);
    stream << " int offset = " << field_offset << " + " << index << " * "
           << class_field_size << ";\n";
    offset = "offset";
  }
  stream << " " << type_name << " value = ";
  if (!field_type->IsSubtypeOf(TypeOracle::GetTaggedType())) {
    const char* load;
    switch (class_field.synchronization) {
      case FieldSynchronization::kNone:
        load = "ReadField";
        break;
      case FieldSynchronization::kRelaxed:
        load = "Relaxed_ReadField";
        break;
      case FieldSynchronization::kAcquireRelease:
        ReportError("Torque doesn't support @cppAcquireLoad on untagged data");
    }
    stream << "this->template " << load << "<" << type_name << ">(" << offset
           << ");\n";
  } else {
    const char* load;
    switch (class_field.synchronization) {
      case FieldSynchronization::kNone:
        load = "load";
        break;
      case FieldSynchronization::kRelaxed:
        load = "Relaxed_Load";
        break;
      case FieldSynchronization::kAcquireRelease:
        load = "Acquire_Load";
        break;
    }
    bool is_smi = field_type->IsSubtypeOf(TypeOracle::GetSmiType());
    const std::string load_type = is_smi ? "Smi" : type_name;
    const char* postfix = is_smi ? ".value()" : "";
    const char* optional_cage_base = is_smi ? "" : "cage_base, ";
    stream << "TaggedField<" << load_type << ">::" << load << "("
           << optional_cage_base << "*this, " << offset << ")" << postfix
           << ";\n";
  }
  if (CanContainHeapObjects(field_type)) {
    stream << " DCHECK(" << GenerateRuntimeTypeCheck(field_type, "value")
           << ");\n";
  }
}
References v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::anonymous_namespace{implementation-visitor.cc}::GenerateBoundsDCheck(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::anonymous_namespace{implementation-visitor.cc}::GenerateRuntimeTypeCheck(), v8::internal::torque::Field::GetFieldSizeInformation(), v8::internal::index, v8::internal::torque::Field::index, v8::internal::torque::Type::IsSubtypeOf(), v8::internal::torque::Field::name_and_type, v8::internal::torque::ReportError(), v8::internal::string, v8::internal::torque::Field::synchronization, and v8::internal::torque::NameAndType::type.
EmitStoreFieldStatement()
void v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::EmitStoreFieldStatement (std::ostream & stream, const Field & class_field, std::vector< const Field * > & struct_fields) [private]
Definition at line 4731 of file implementation-visitor.cc.
                                            {
  const Field& innermost_field =
      struct_fields.empty() ? class_field : *struct_fields.back();
  const Type* field_type = innermost_field.name_and_type.type;
  std::string type_name = GetTypeNameForAccessor(innermost_field);
  const std::string class_field_size =
      std::get<1>(class_field.GetFieldSizeInformation());
  // field_offset contains both the offset from the beginning of the object to
  // the class field and the combined offsets of any nested struct fields
  // within, but not the index adjustment.
  std::string field_offset = GetFieldOffsetForAccessor(class_field);
  for (const Field* nested_struct_field : struct_fields) {
    field_offset += " + " + std::to_string(*nested_struct_field->offset);
  }
  std::string offset = field_offset;
  if (class_field.index) {
    const char* index = class_field.index->optional ? "0" : "i";
    GenerateBoundsDCheck(stream, index, type_, class_field);
    stream << " int offset = " << field_offset << " + " << index << " * "
           << class_field_size << ";\n";
    offset = "offset";
  }
  if (!field_type->IsSubtypeOf(TypeOracle::GetTaggedType())) {
    const char* store;
    switch (class_field.synchronization) {
      case FieldSynchronization::kNone:
        store = "WriteField";
        break;
      case FieldSynchronization::kRelaxed:
        store = "Relaxed_WriteField";
        break;
      case FieldSynchronization::kAcquireRelease:
        ReportError("Torque doesn't support @cppReleaseStore on untagged data");
    }
    stream << " this->template " << store << "<" << type_name << ">(" << offset
           << ", value);\n";
  } else {
    bool strong_pointer = field_type->IsSubtypeOf(TypeOracle::GetObjectType());
    bool is_smi = field_type->IsSubtypeOf(TypeOracle::GetSmiType());
    const char* write_macro;
    if (!strong_pointer) {
      if (class_field.synchronization ==
          FieldSynchronization::kAcquireRelease) {
        ReportError("Torque doesn't support @cppReleaseStore on weak fields");
      }
      write_macro = "RELAXED_WRITE_WEAK_FIELD";
    } else {
      switch (class_field.synchronization) {
        case FieldSynchronization::kNone:
          write_macro = "WRITE_FIELD";
          break;
        case FieldSynchronization::kRelaxed:
          write_macro = "RELAXED_WRITE_FIELD";
          break;
        case FieldSynchronization::kAcquireRelease:
          write_macro = "RELEASE_WRITE_FIELD";
          break;
      }
    }
    std::string value_to_write;
    if (const auto type_wrapped_in_smi = Type::MatchUnaryGeneric(
            field_type, TypeOracle::GetSmiTaggedGeneric())) {
      DCHECK(is_smi);
      stream << " // " << type_wrapped_in_smi.value()->ToString() << "\n";
      value_to_write = "Smi::From31BitPattern(value)";
    } else {
      value_to_write = is_smi ? "Smi::FromInt(value)" : "value";
    }
    if (!is_smi) {
      // Don't DCHECK types if the roots aren't initialized, so that we don't
      // incorrectly fail these checks during initial heap setup.
      stream << " "
                "SLOW_DCHECK(!IsolateGroup::current()->shared_read_only_heap()-"
                ">roots_init_complete() || ("
             << GenerateRuntimeTypeCheck(field_type, "value") << "));\n";
    }
    stream << " " << write_macro << "(*this, " << offset << ", "
           << value_to_write << ");\n";
    if (!is_smi) {
      stream << " CONDITIONAL_WRITE_BARRIER(*this, " << offset
             << ", value, mode);\n";
    }
  }
}
References v8::internal::DCHECK(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::anonymous_namespace{implementation-visitor.cc}::GenerateBoundsDCheck(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::anonymous_namespace{implementation-visitor.cc}::GenerateRuntimeTypeCheck(), v8::internal::torque::Field::GetFieldSizeInformation(), v8::internal::index, v8::internal::torque::Field::index, v8::internal::torque::Type::IsSubtypeOf(), v8::internal::torque::Field::name_and_type, v8::internal::torque::ReportError(), store(), v8::internal::string, v8::internal::torque::Field::synchronization, and v8::internal::torque::NameAndType::type.
GenerateClass()
void v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GenerateClass ()
Definition at line 4178 of file implementation-visitor.cc.
                                      {
  // Is<name>_NonInline(Tagged<HeapObject>)
  if (!type_->IsShape()) {
    cpp::Function f("Is"s + name_ + "_NonInline");
    f.SetDescription("Alias for Is"s + name_ + "() that avoids inlining.");
    f.SetExport(true);
    f.SetReturnType("bool");
    f.AddParameter("Tagged<HeapObject>", "o");
    f.PrintDeclaration(hdr_);
    hdr_ << "\n";
    f.PrintDefinition(impl_, [&](std::ostream& stream) {
      stream << " return Is" << name_ << "(o);\n";
    });
  }
  hdr_ << "// Definition " << Position() << "\n";
  hdr_ << template_decl() << "\n";
  hdr_ << "class " << gen_name_ << " : public P {\n";
  hdr_ << " static_assert(\n"
       << " std::is_same_v<" << name_ << ", D>,\n"
       << " \"Use this class as direct base for " << name_ << ".\");\n";
  hdr_ << " static_assert(\n"
       << " std::is_same_v<" << super_->name() << ", P>,\n"
       << " \"Pass in " << super_->name()
       << " as second template parameter for " << gen_name_ << ".\");\n\n";
  hdr_ << " public: \n";
  hdr_ << " using Super = P;\n";
  hdr_ << " using TorqueGeneratedClass = " << gen_name_ << "<D,P>;\n\n";
  if (!type_->ShouldExport() && !type_->IsExtern()) {
    hdr_ << " protected: // not extern or @export\n";
  }
  for (const Field& f : type_->fields()) {
    CurrentSourcePosition::Scope scope(f.pos);
    std::vector<const Field*> struct_fields;
    GenerateFieldAccessors(f, struct_fields);
  }
  if (!type_->ShouldExport() && !type_->IsExtern()) {
    hdr_ << " public:\n";
  }
  std::vector<cpp::TemplateParameter> templateArgs = {
      cpp::TemplateParameter("D"), cpp::TemplateParameter("P")};
  cpp::Class c(std::move(templateArgs), gen_name_);
  if (type_->ShouldGeneratePrint()) {
    hdr_ << " DECL_PRINTER(" << name_ << ")\n\n";
  }
  if (type_->ShouldGenerateVerify()) {
    IfDefScope hdr_scope(hdr_, "VERIFY_HEAP");
    // V8_EXPORT_PRIVATE void Verify(Isolate*);
    cpp::Function f(&c, name_ + "Verify");
    f.SetExport();
    f.SetReturnType("void");
    f.AddParameter("Isolate*", "isolate");
    f.PrintDeclaration(hdr_);
    IfDefScope impl_scope(impl_, "VERIFY_HEAP");
    impl_ << "\ntemplate <>\n";
    impl_ << "void " << gen_name_I_ << "::" << name_
          << "Verify(Isolate* isolate) {\n";
    impl_ << " TorqueGeneratedClassVerifiers::" << name_ << "Verify(Cast<"
          << name_
          << ">(*this), "
             "isolate);\n";
    impl_ << "}\n\n";
    impl_ << "\n";
  }
  hdr_ << "\n";
  ClassFieldOffsetGenerator g(hdr_, inl_, type_, gen_name_,
                              type_->GetSuperClass());
  for (const auto& f : type_->fields()) {
    CurrentSourcePosition::Scope scope(f.pos);
    g.RecordOffsetFor(f);
  }
  g.Finish();
  hdr_ << "\n";
  auto index_fields = GetOrderedUniqueIndexFields(*type_);
  if (!index_fields.has_value()) {
    hdr_ << " // SizeFor implementations not generated due to complex array "
            "lengths\n\n";
    const Field& last_field = type_->LastField();
    std::string last_field_item_size =
        std::get<1>(*SizeOf(last_field.name_and_type.type));
    // int AllocatedSize() const
    {
      cpp::Function f =
          cpp::Function::DefaultGetter("int", &c, "AllocatedSize");
      f.PrintDeclaration(hdr_);
      f.PrintDefinition(inl_, [&](std::ostream& stream) {
        stream << " auto slice = "
               << Callable::PrefixNameForCCOutput(
                      type_->GetSliceMacroName(last_field))
               << "(*static_cast<const D*>(this));\n";
        stream << " return static_cast<int>(std::get<1>(slice)) + "
               << last_field_item_size
               << " * static_cast<int>(std::get<2>(slice));\n";
      });
    }
  } else if (type_->ShouldGenerateBodyDescriptor() ||
             (!type_->IsAbstract() &&
              !type_->IsSubtypeOf(TypeOracle::GetJSObjectType()))) {
    cpp::Function f(&c, "SizeFor");
    f.SetReturnType("int32_t");
    f.SetFlags(cpp::Function::kStatic | cpp::Function::kConstexpr |
               cpp::Function::kV8Inline);
    for (const Field& field : *index_fields) {
      f.AddParameter("int", field.name_and_type.name);
    }
    f.PrintInlineDefinition(hdr_, [&](std::ostream& stream) {
      if (index_fields->empty()) {
        stream << " DCHECK(kHeaderSize == kSize && kHeaderSize == "
               << *type_->size().SingleValue() << ");\n";
      }
      stream << " int32_t size = kHeaderSize;\n";
      for (const Field& field : type_->ComputeAllFields()) {
        if (field.index) {
          auto index_name_and_type =
              *ExtractSimpleFieldArraySize(*type_, field.index->expr);
          stream << " size += " << index_name_and_type.name << " * "
                 << std::get<0>(field.GetFieldSizeInformation()) << ";\n";
        }
      }
      if (type_->size().Alignment() < TargetArchitecture::TaggedSize()) {
        stream << " size = OBJECT_POINTER_ALIGN(size);\n";
      }
      stream << " return size;\n";
    });
    // V8_INLINE int32_t AllocatedSize() const
    {
      cpp::Function allocated_size_f =
          cpp::Function::DefaultGetter("int32_t", &c, "AllocatedSize");
      allocated_size_f.SetFlag(cpp::Function::kV8Inline);
      allocated_size_f.PrintInlineDefinition(hdr_, [&](std::ostream& stream) {
        stream << " return SizeFor(";
        bool first = true;
        for (const auto& field : *index_fields) {
          if (!first) stream << ", ";
          stream << "this->" << field.name_and_type.name << "()";
          first = false;
        }
        stream << ");\n";
      });
    }
  }
  hdr_ << " friend class Factory;\n\n";
  GenerateClassConstructors();
  hdr_ << "};\n\n";
  if (type_->ShouldGenerateFullClassDefinition()) {
    // If this class extends from another class which is defined in the same tq
    // file, and that other class doesn't generate a full class definition, then
    // the resulting .inc file would be uncompilable due to ordering
    // requirements: the generated file must go before the hand-written
    // definition of the base class, but it must also go after that same
    // hand-written definition.
    std::optional<const ClassType*> parent = type_->parent()->ClassSupertype();
    while (parent) {
      if ((*parent)->ShouldGenerateCppClassDefinitions() &&
          !(*parent)->ShouldGenerateFullClassDefinition() &&
          (*parent)->AttributedToFile() == type_->AttributedToFile()) {
        Error("Exported ", *type_,
              " cannot be in the same file as its parent extern ", **parent);
      }
      parent = (*parent)->parent()->ClassSupertype();
    }
    GenerateClassExport(type_, hdr_, inl_);
  }
}
References v8::internal::torque::cpp::Function::AddParameter(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FieldOffsetsGenerator::Finish(), v8::internal::anonymous_namespace{json-stringifier.cc}::for(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::GetOrderedUniqueIndexFields(), v8::internal::torque::Field::name_and_type, v8::internal::torque::cpp::Function::PrintDeclaration(), v8::internal::torque::cpp::Function::PrintDefinition(), v8::internal::torque::cpp::Function::PrintInlineDefinition(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FieldOffsetsGenerator::RecordOffsetFor(), v8::internal::torque::cpp::Function::SetDescription(), v8::internal::torque::cpp::Function::SetFlag(), v8::internal::torque::cpp::Function::SetFlags(), v8::internal::torque::cpp::Function::SetReturnType(), v8::internal::torque::SizeOf(), v8::internal::string, and v8::internal::torque::NameAndType::type.
GenerateClassConstructors()
void v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GenerateClassConstructors () [private]
Definition at line 4422 of file implementation-visitor.cc.
                                                  {
  const ClassType* typecheck_type = type_;
  while (typecheck_type->IsShape()) {
    typecheck_type = typecheck_type->GetSuperClass();
    // Shapes have already been checked earlier to inherit from JSObject, so we
    // should have found an appropriate type.
    DCHECK(typecheck_type);
  }
  hdr_ << " template <class DAlias = D>\n";
  hdr_ << " constexpr " << gen_name_ << "() : P() {\n";
  hdr_ << " static_assert(\n";
  hdr_ << " std::is_base_of_v<" << gen_name_ << ", DAlias>,\n";
  hdr_ << " \"class " << gen_name_
       << " should be used as direct base for " << name_ << ".\");\n";
  hdr_ << " }\n\n";
  hdr_ << " protected:\n";
  hdr_ << " inline explicit constexpr " << gen_name_
       << "(Address ptr, typename P::SkipTypeCheckTag\n)";
  hdr_ << " : P(ptr, typename P::SkipTypeCheckTag{}) {}\n";
  hdr_ << " inline explicit " << gen_name_ << "(Address ptr);\n";
  inl_ << "template<class D, class P>\n";
  inl_ << "inline " << gen_name_T_ << "::" << gen_name_ << "(Address ptr)\n";
  inl_ << " : P(ptr) {\n";
  inl_ << " SLOW_DCHECK(Is" << typecheck_type->name()
       << "_NonInline(*this));\n";
  inl_ << "}\n";
}
References v8::internal::DCHECK(), v8::internal::torque::ClassType::GetSuperClass(), v8::internal::torque::ClassType::IsShape(), and v8::internal::torque::AggregateType::name().
GenerateCppObjectDefinitionAsserts()
void v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GenerateCppObjectDefinitionAsserts ()
Definition at line 4359 of file implementation-visitor.cc.
                                                           {
  impl_ << "// Definition " << Position() << "\n"
        << "class " << gen_name_ << "Asserts {\n";
  ClassFieldOffsetGenerator g(impl_, impl_, type_, gen_name_,
                              type_->GetSuperClass(), false);
  for (const auto& f : type_->fields()) {
    CurrentSourcePosition::Scope scope(f.pos);
    g.RecordOffsetFor(f);
  }
  g.Finish();
  impl_ << "\n";
  for (const auto& f : type_->fields()) {
    std::string field_offset =
        "k" + CamelifyString(f.name_and_type.name) + "Offset";
    impl_ << " static_assert(" << field_offset << " == " << name_
          << "::" << field_offset << ",\n"
          << " \"Values of " << name_ << "::" << field_offset
          << " defined in Torque and C++ do not match\");\n";
  }
  if (!type_->IsAbstract() && type_->HasStaticSize()) {
    impl_ << " static_assert(kSize == " << name_ << "::kSize);\n";
  }
  impl_ << "};\n\n";
}
References v8::internal::torque::CamelifyString(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FieldOffsetsGenerator::Finish(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FieldOffsetsGenerator::RecordOffsetFor(), and v8::internal::string.
GenerateCppObjectLayoutDefinitionAsserts()
void v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GenerateCppObjectLayoutDefinitionAsserts ()
Definition at line 4387 of file implementation-visitor.cc.
                                                                 {
  impl_ << "// Definition " << Position() << "\n"
        << "class " << gen_name_ << "Asserts {\n";
  ClassFieldOffsetGenerator g(impl_, impl_, type_, gen_name_,
                              type_->GetSuperClass(), false);
  for (const auto& f : type_->fields()) {
    CurrentSourcePosition::Scope scope(f.pos);
    g.RecordOffsetFor(f);
  }
  g.Finish();
  impl_ << "\n";
  for (const auto& f : type_->fields()) {
    std::string field_offset =
        "k" + CamelifyString(f.name_and_type.name) + "Offset";
    std::string cpp_field_offset =
        f.index.has_value()
            ? "OFFSET_OF_DATA_START(" + name_ + ")"
            : "offsetof(" + name_ + ", " + f.name_and_type.name + "_)";
    impl_ << " static_assert(" << field_offset << " == " << cpp_field_offset
          << ",\n"
          << " \"Value of " << name_ << "::" << field_offset
          << " defined in Torque and offset of field " << name_
          << "::" << f.name_and_type.name << " in C++ do not match\");\n";
  }
  if (!type_->IsAbstract() && type_->HasStaticSize()) {
    impl_ << " static_assert(kSize == sizeof(" + name_ + "));\n";
  }
  impl_ << "};\n\n";
}
References v8::internal::torque::CamelifyString(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FieldOffsetsGenerator::Finish(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FieldOffsetsGenerator::RecordOffsetFor(), and v8::internal::string.
GenerateFieldAccessors()
void v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GenerateFieldAccessors (const Field & class_field, std::vector< const Field * > & struct_fields) [private]
Definition at line 4517 of file implementation-visitor.cc.
                                                                      {
  const Field& innermost_field =
      struct_fields.empty() ? class_field : *struct_fields.back();
  const Type* field_type = innermost_field.name_and_type.type;
  if (!CanGenerateFieldAccessors(field_type)) return;
  if (const StructType* struct_type = StructType::DynamicCast(field_type)) {
    struct_fields.resize(struct_fields.size() + 1);
    for (const Field& struct_field : struct_type->fields()) {
      struct_fields[struct_fields.size() - 1] = &struct_field;
      GenerateFieldAccessors(class_field, struct_fields);
    }
    struct_fields.resize(struct_fields.size() - 1);
    return;
  }
  bool indexed = class_field.index && !class_field.index->optional;
  std::string type_name = GetTypeNameForAccessor(innermost_field);
  bool can_contain_heap_objects = CanContainHeapObjects(field_type);
  // Assemble an accessor name by accumulating together all of the nested field
  // names.
  std::string name = class_field.name_and_type.name;
  for (const Field* nested_struct_field : struct_fields) {
    name += "_" + nested_struct_field->name_and_type.name;
  }
  // Generate declarations in header.
  if (can_contain_heap_objects && !field_type->IsClassType() &&
      !field_type->IsStructType() &&
      field_type != TypeOracle::GetObjectType()) {
    hdr_ << " // Torque type: " << field_type->ToString() << "\n";
  }
  std::vector<cpp::TemplateParameter> templateParameters = {
      cpp::TemplateParameter("D"), cpp::TemplateParameter("P")};
  cpp::Class owner(std::move(templateParameters), gen_name_);
  // getter
  {
    auto getter = cpp::Function::DefaultGetter(type_name, &owner, name);
    if (indexed) {
      getter.AddParameter("int", "i");
    }
    const char* tag_argument;
    switch (class_field.synchronization) {
      case FieldSynchronization::kNone:
        tag_argument = "";
        break;
      case FieldSynchronization::kRelaxed:
        getter.AddParameter("RelaxedLoadTag");
        tag_argument = ", kRelaxedLoad";
        break;
      case FieldSynchronization::kAcquireRelease:
        getter.AddParameter("AcquireLoadTag");
        tag_argument = ", kAcquireLoad";
        break;
    }
    getter.PrintDeclaration(hdr_);
    // For tagged data, generate the extra getter that derives an
    // PtrComprCageBase from the current object's pointer.
    if (can_contain_heap_objects) {
      getter.PrintDefinition(inl_, [&](auto& stream) {
        stream
            << " PtrComprCageBase cage_base = GetPtrComprCageBase(*this);\n";
        stream << " return " << gen_name_ << "::" << name << "(cage_base"
               << (indexed ? ", i" : "") << tag_argument << ");\n";
      });
      getter.InsertParameter(0, "PtrComprCageBase", "cage_base");
      getter.PrintDeclaration(hdr_);
    }
    getter.PrintDefinition(inl_, [&](auto& stream) {
      EmitLoadFieldStatement(stream, class_field, struct_fields);
      stream << " return value;\n";
    });
  }
  // setter
  {
    auto setter = cpp::Function::DefaultSetter(
        &owner, std::string("set_") + name, type_name, "value");
    if (indexed) {
      setter.InsertParameter(0, "int", "i");
    }
    switch (class_field.synchronization) {
      case FieldSynchronization::kNone:
        break;
      case FieldSynchronization::kRelaxed:
        setter.AddParameter("RelaxedStoreTag");
        break;
      case FieldSynchronization::kAcquireRelease:
        setter.AddParameter("ReleaseStoreTag");
        break;
    }
    if (can_contain_heap_objects) {
      setter.AddParameter("WriteBarrierMode", "mode", "UPDATE_WRITE_BARRIER");
    }
    setter.PrintDeclaration(hdr_);
    setter.PrintDefinition(inl_, [&](auto& stream) {
      EmitStoreFieldStatement(stream, class_field, struct_fields);
    });
  }
  hdr_ << "\n";
}
References v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::anonymous_namespace{implementation-visitor.cc}::CanGenerateFieldAccessors(), v8::internal::torque::Field::index, v8::internal::torque::TypeBase::IsClassType(), v8::internal::torque::TypeBase::IsStructType(), v8::internal::name, v8::internal::torque::NameAndType::name, v8::internal::torque::Field::name_and_type, v8::internal::setter, v8::internal::string, v8::internal::torque::Field::synchronization, v8::internal::torque::Type::ToString(), and v8::internal::torque::NameAndType::type.
GetFieldOffsetForAccessor()
std::string v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GetFieldOffsetForAccessor (const Field & f) [private]
Definition at line 4629 of file implementation-visitor.cc.
                                                                     {
  if (f.offset.has_value()) {
    return "k" + CamelifyString(f.name_and_type.name) + "Offset";
  }
  return CamelifyString(f.name_and_type.name) + "Offset()";
}
References v8::internal::torque::CamelifyString(), v8::internal::torque::NameAndType::name, v8::internal::torque::Field::name_and_type, and v8::internal::torque::Field::offset.
GetTypeNameForAccessor()
std::string v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GetTypeNameForAccessor (const Field & f) [private]
Definition at line 4636 of file implementation-visitor.cc.
                                                                  {
  const Type* field_type = f.name_and_type.type;
  if (!field_type->IsSubtypeOf(TypeOracle::GetTaggedType())) {
    const Type* constexpr_version = field_type->ConstexprVersion();
    if (!constexpr_version) {
      Error("Field accessor for ", type_->name(), ":: ", f.name_and_type.name,
            " cannot be generated because its type ", *field_type,
            " is neither a subclass of Object nor does the type have a "
            "constexpr "
            "version.")
          .Position(f.pos)
          .Throw();
    }
    return constexpr_version->GetGeneratedTypeName();
  }
  return field_type->TagglifiedCppTypeName();
}
References v8::internal::torque::Type::ConstexprVersion(), v8::internal::torque::Error(), v8::internal::torque::Type::GetGeneratedTypeName(), v8::internal::torque::Type::IsSubtypeOf(), v8::internal::torque::NameAndType::name, v8::internal::torque::Field::name_and_type, v8::internal::torque::Field::pos, v8::internal::torque::MessageBuilder::Position(), v8::internal::torque::Type::TagglifiedCppTypeName(), v8::internal::torque::MessageBuilder::Throw(), and v8::internal::torque::NameAndType::type.
Position()
SourcePosition v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::Position () [private]
Definition at line 4420 of file implementation-visitor.cc.
{ return type_->GetPosition(); }
template_decl()
const std::string v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::template_decl () const [inline]
Definition at line 4112 of file implementation-visitor.cc.
                                        {
    return "template <class D, class P>";
  }
Member Data Documentation
gen_name_
const std::string v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::gen_name_ [private]
Definition at line 4147 of file implementation-visitor.cc.
gen_name_I_
const std::string v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::gen_name_I_ [private]
Definition at line 4149 of file implementation-visitor.cc.
gen_name_T_
const std::string v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::gen_name_T_ [private]
Definition at line 4148 of file implementation-visitor.cc.
hdr_
std::ostream& v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::hdr_ [private]
Definition at line 4150 of file implementation-visitor.cc.
impl_
std::ostream& v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::impl_ [private]
Definition at line 4152 of file implementation-visitor.cc.
inl_
std::ostream& v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::inl_ [private]
Definition at line 4151 of file implementation-visitor.cc.
name_
const std::string v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::name_ [private]
Definition at line 4146 of file implementation-visitor.cc.
super_
const ClassType* v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::super_ [private]
Definition at line 4145 of file implementation-visitor.cc.
type_
const ClassType* v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::type_ [private]
Definition at line 4144 of file implementation-visitor.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/implementation-visitor.cc