v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee Class Reference
Classes
class CandidateVisitor
Static Public Member Functions
static HeapObjectList DeterminePromotees (Isolate *isolate, const DisallowGarbageCollection &no_gc, const SafepointScope &safepoint_scope)
Private Member Functions
Committee (Isolate *isolate)
const ExternalReferenceEncoder & ref_encoder () const
HeapObjectList DeterminePromotees (const SafepointScope &safepoint_scope)
bool EvaluateSubgraph (std::optional< Tagged< HeapObject >> maybe_host, Tagged< HeapObject > o, HeapObjectSet *accepted_subgraph, HeapObjectSet *visited, HeapObjectList *promotees)
void LogRejectedPromotionForNoMatchingHost (Tagged< HeapObject > o)
void LogRejectedPromotionForInvalidSubgraph (Tagged< HeapObject > o, int first_rejected_slot_offset)
Static Private Member Functions
static PromoRecommendation GetPromoRecommendation (Committee *committee, Isolate *isolate, Tagged< HeapObject > o)
static PromoRecommendation GetPromoRecommendationFunctionTemplateInfo (Committee *committee, Isolate *isolate, Tagged< FunctionTemplateInfo > o)
static PromoRecommendation GetPromoRecommendationCode (Committee *committee, Isolate *isolate, Tagged< Code > o)
static PromoRecommendation GetPromoRecommendationCodeWrapper (Committee *committee, Isolate *isolate, Tagged< CodeWrapper > o)
static PromoRecommendation GetPromoRecommendationObjectTemplateInfo (Committee *committee, Isolate *isolate, Tagged< ObjectTemplateInfo > o)
static PromoRecommendation GetPromoRecommendationSharedFunctionInfo (Committee *committee, Isolate *isolate, Tagged< SharedFunctionInfo > o)
static void LogAcceptedPromotionSet (const HeapObjectSet &os)
static void LogRejectedPromotionForFailedPredicate (Tagged< HeapObject > o)
Private Attributes
Isolate *const isolate_
ExternalReferenceEncoder ref_encoder_
HeapObjectSet promo_accepted_
HeapObjectSet promo_rejected_
HeapObjectSet promo_deferred_
Detailed Description
Definition at line 58 of file read-only-promotion.cc.
Constructor & Destructor Documentation
Committee()
v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::Committee (Isolate * isolate) [inline], [explicit], [private]
Definition at line 67 of file read-only-promotion.cc.
      : isolate_(isolate), ref_encoder_(isolate) {}
Member Function Documentation
DeterminePromotees() [1/2]
HeapObjectList v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::DeterminePromotees (const SafepointScope & safepoint_scope) [inline], [private]
Definition at line 72 of file read-only-promotion.cc.
                                                                           {
    DCHECK(promo_accepted_.empty());
    DCHECK(promo_rejected_.empty());
    // List of promotees as discovered in insertion order. Using the
    // `HeapObjectIterator` will visit pages in insertion order from a GC
    // perspective which is deterministic independent of the absolute pages
    // provided by the OS allocators in case of 32-bit builds (that don't use
    // cages).
    //
    // We keep a separate HeapObjectList as there's no standard-equivalent for a
    // hash set that can maintain insertion order.
    HeapObjectList promo_accepted_list;
    // We assume that a full and precise GC has reclaimed all dead objects
    // and therefore that no filtering of unreachable objects is required here.
    HeapObjectIterator it(isolate_->heap(), safepoint_scope);
    for (Tagged<HeapObject> o = it.Next(); !o.is_null(); o = it.Next()) {
      DCHECK(!HeapLayout::InReadOnlySpace(o));
      // Note that cycles prevent us from promoting/rejecting each subgraph as
      // we visit it, since locally we cannot determine whether the deferred
      // decision on the 'cycle object' will be 'promote' or 'reject'. This
      // could be solved if necessary (with more complex code), but for now
      // there are no performance issues.
      HeapObjectSet accepted_subgraph; // Either all are accepted or none.
      HeapObjectList accepted_subgraph_list;
      HeapObjectSet visited; // Cycle detection.
      if (!EvaluateSubgraph(std::nullopt, o, &accepted_subgraph, &visited,
                            &accepted_subgraph_list)) {
        continue;
      }
      if (accepted_subgraph.empty()) {
        continue;
      }
      if (V8_UNLIKELY(v8_flags.trace_read_only_promotion)) {
        LogAcceptedPromotionSet(accepted_subgraph);
      }
      promo_accepted_.insert(accepted_subgraph.begin(),
                             accepted_subgraph.end());
      promo_accepted_list.insert(promo_accepted_list.end(),
                                 accepted_subgraph_list.begin(),
                                 accepted_subgraph_list.end());
    }
    if (V8_UNLIKELY(v8_flags.trace_read_only_promotion)) {
      for (auto o : promo_deferred_) {
        LogRejectedPromotionForNoMatchingHost(o);
      }
    }
    // Remove duplicates from the promo_accepted_list. Note we have to jump
    // through these hoops in order to preserve deterministic ordering
    // (otherwise simply using the promo_accepted_ set would be sufficient).
    HeapObjectSet seen_promotees;
    HeapObjectList promotees;
    promotees.reserve(promo_accepted_list.size());
    for (Tagged<HeapObject> o : promo_accepted_list) {
      if (Contains(seen_promotees, o)) continue;
      seen_promotees.insert(o);
      promotees.push_back(o);
    }
    CHECK_EQ(promotees.size(), promo_accepted_.size());
    return promotees;
  }
References CHECK_EQ, v8::internal::anonymous_namespace{read-only-promotion.cc}::Contains(), v8::internal::DCHECK(), v8::internal::HeapLayout::InReadOnlySpace(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::HeapObjectIterator::Next(), v8::internal::v8_flags, and V8_UNLIKELY.
DeterminePromotees() [2/2]
static HeapObjectList v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::DeterminePromotees (Isolate * isolate, const DisallowGarbageCollection & no_gc, const SafepointScope & safepoint_scope) [inline], [static]
Definition at line 60 of file read-only-promotion.cc.
                                             {
    return Committee(isolate).DeterminePromotees(safepoint_scope);
  }
References DeterminePromotees().
Referenced by DeterminePromotees().
EvaluateSubgraph()
bool v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::EvaluateSubgraph (std::optional< Tagged< HeapObject >> maybe_host, Tagged< HeapObject > o, HeapObjectSet * accepted_subgraph, HeapObjectSet * visited, HeapObjectList * promotees) [inline], [private]
Definition at line 142 of file read-only-promotion.cc.
                                                                           {
    if (HeapLayout::InReadOnlySpace(o)) return true;
    if (Contains(promo_rejected_, o)) return false;
    if (Contains(promo_accepted_, o)) return true;
    if (Contains(*visited, o)) return true;
    visited->insert(o);
    PromoRecommendation recommendation =
        GetPromoRecommendation(this, isolate_, o);
    switch (recommendation) {
      case kPromote:
        break;
      case kReject: {
        const auto& [it, inserted] = promo_rejected_.insert(o);
        if (V8_UNLIKELY(v8_flags.trace_read_only_promotion) && inserted) {
          LogRejectedPromotionForFailedPredicate(o);
        }
        return false;
      }
      case kMatchHost:
        if (!maybe_host.has_value()) {
          // We've met this object during regular heap iteration and don't know
          // yet how it's used. Postpone the decision for later.
          DCHECK(!Contains(promo_deferred_, o));
          promo_deferred_.insert(o);
          visited->erase(o);
          return false;
        }
        // This object is referenced by another promotion candidate, so
        // let this one be promoted too.
        promo_deferred_.erase(o);
        break;
    }
    // Recurse into outgoing pointers.
    CandidateVisitor v(this, accepted_subgraph, visited, promotees, maybe_host);
    VisitObject(isolate_, o, &v);
    if (!v.all_slots_are_promo_candidates()) {
      const auto& [it, inserted] = promo_rejected_.insert(o);
      if (V8_UNLIKELY(v8_flags.trace_read_only_promotion) && inserted) {
        LogRejectedPromotionForInvalidSubgraph(o,
                                               v.first_rejected_slot_offset());
      }
      if (Tagged<TemplateInfo> info; TryCast<TemplateInfo>(o, &info)) {
        CHECK_WITH_MSG(!info->should_promote_to_read_only(),
                       "v8::Template was asked to be promoted to "
                       "read only space but it wasn't possible. "
                       "Use --trace-read-only-promotion for debugging.");
      }
      return false;
    }
    accepted_subgraph->insert(o);
    promotees->push_back(o);
    // Some sanity checks for general-purpose objects (they should be included
    // only as a part of expected hosts).
    DCHECK_IMPLIES(IsArrayList(o),
                   maybe_host.has_value() &&
                       IsTemplateInfoWithProperties(maybe_host.value()));
    return true;
  }
References v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::CandidateVisitor::all_slots_are_promo_candidates(), CHECK_WITH_MSG, v8::internal::anonymous_namespace{read-only-promotion.cc}::Contains(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::CandidateVisitor::first_rejected_slot_offset(), v8::internal::HeapLayout::InReadOnlySpace(), v8::internal::anonymous_namespace{read-only-promotion.cc}::kMatchHost, v8::internal::anonymous_namespace{read-only-promotion.cc}::kPromote, v8::internal::anonymous_namespace{read-only-promotion.cc}::kReject, v8::internal::v8_flags, V8_UNLIKELY, and v8::internal::VisitObject().
GetPromoRecommendation()
static PromoRecommendation v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::GetPromoRecommendation (Committee * committee, Isolate * isolate, Tagged< HeapObject > o) [inline], [static], [private]
Definition at line 222 of file read-only-promotion.cc.
                                                                          {
    const InstanceType itype = o->map(isolate)->instance_type();
#define V(TYPE) \
  if (InstanceTypeChecker::Is##TYPE(itype)) { \
    return GetPromoRecommendation##TYPE(committee, isolate, Cast<TYPE>(o)); \
    /* NOLINTNEXTLINE(readability/braces) */ \
  } else
    PROMO_CANDIDATE_TYPE_LIST(V)
    /* if { ... } else */ {
      return kReject;
    }
#undef V
    UNREACHABLE();
  }
References v8::internal::anonymous_namespace{read-only-promotion.cc}::kReject, PROMO_CANDIDATE_TYPE_LIST, and v8::internal::UNREACHABLE().
GetPromoRecommendationCode()
static PromoRecommendation v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::GetPromoRecommendationCode (Committee * committee, Isolate * isolate, Tagged< Code > o) [inline], [static], [private]
Definition at line 266 of file read-only-promotion.cc.
                                                                        {
    return Builtins::kCodeObjectsAreInROSpace && o->is_builtin() ? kPromote
                                                                 : kReject;
  }
References v8::internal::Builtins::kCodeObjectsAreInROSpace, v8::internal::anonymous_namespace{read-only-promotion.cc}::kPromote, and v8::internal::anonymous_namespace{read-only-promotion.cc}::kReject.
GetPromoRecommendationCodeWrapper()
static PromoRecommendation v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::GetPromoRecommendationCodeWrapper (Committee * committee, Isolate * isolate, Tagged< CodeWrapper > o) [inline], [static], [private]
Definition at line 272 of file read-only-promotion.cc.
                                                                     {
    return GetPromoRecommendationCode(committee, isolate, o->code(isolate));
  }
GetPromoRecommendationFunctionTemplateInfo()
static PromoRecommendation v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::GetPromoRecommendationFunctionTemplateInfo (Committee * committee, Isolate * isolate, Tagged< FunctionTemplateInfo > o) [inline], [static], [private]
Definition at line 258 of file read-only-promotion.cc.
                                                                              {
    // This flag is set by the embedder explicitly by calling
    // v8::FunctionTemplate::SealAndPrepareForPromotionToReadOnly(..).
    return o->should_promote_to_read_only() ? kPromote : kReject;
  }
References v8::internal::anonymous_namespace{read-only-promotion.cc}::kPromote, and v8::internal::anonymous_namespace{read-only-promotion.cc}::kReject.
GetPromoRecommendationObjectTemplateInfo()
static PromoRecommendation v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::GetPromoRecommendationObjectTemplateInfo (Committee * committee, Isolate * isolate, Tagged< ObjectTemplateInfo > o) [inline], [static], [private]
Definition at line 278 of file read-only-promotion.cc.
                                                                            {
    // This flag is set by the embedder explicitly by calling
    // v8::ObjectTemplate::SealAndPrepareForPromotionToReadOnly(..).
    return o->should_promote_to_read_only() ? kPromote : kReject;
  }
References v8::internal::anonymous_namespace{read-only-promotion.cc}::kPromote, and v8::internal::anonymous_namespace{read-only-promotion.cc}::kReject.
GetPromoRecommendationSharedFunctionInfo()
static PromoRecommendation v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::GetPromoRecommendationSharedFunctionInfo (Committee * committee, Isolate * isolate, Tagged< SharedFunctionInfo > o) [inline], [static], [private]
Definition at line 286 of file read-only-promotion.cc.
                                                                            {
    // Only internal SFIs are guaranteed to remain immutable.
    if (o->has_script(kAcquireLoad)) return kReject;
    // kIllegal is used for js_global_object_function, which is created during
    // bootstrapping but never rooted. We currently assumed that all objects in
    // the snapshot are live. But RO space is 1) not GC'd and 2) serialized
    // verbatim, preserving dead objects. As a workaround, exclude this builtin
    // id from RO allocation.
    // TODO(jgruber): A better solution. Remove the liveness assumption (see
    // test-heap-profiler.cc)? Overwrite dead RO objects with fillers
    // pre-serialization? Implement a RO GC pass pre-serialization?
    if (o->HasBuiltinId() && o->builtin_id() != Builtin::kIllegal) {
      return kPromote;
    }
    // Api functions are good candidates for promotion.
    if (o->IsApiFunction()) return kPromote;
    return kReject;
  }
References v8::kAcquireLoad, v8::internal::anonymous_namespace{read-only-promotion.cc}::kPromote, and v8::internal::anonymous_namespace{read-only-promotion.cc}::kReject.
LogAcceptedPromotionSet()
static void v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::LogAcceptedPromotionSet (const HeapObjectSet & os) [inline], [static], [private]
Definition at line 372 of file read-only-promotion.cc.
                                                               {
    std::cout << "ro-promotion: accepted set {";
    for (Tagged<HeapObject> o : os) {
      std::cout << reinterpret_cast<void*>(o.ptr()) << ", ";
    }
    std::cout << "}\n";
  }
LogRejectedPromotionForFailedPredicate()
static void v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::LogRejectedPromotionForFailedPredicate (Tagged< HeapObject > o) [inline], [static], [private]
Definition at line 380 of file read-only-promotion.cc.
                                                                           {
    std::cout << "ro-promotion: rejected due to failed predicate "
              << reinterpret_cast<void*>(o.ptr()) << " ("
              << o->map()->instance_type() << ")"
              << "\n";
  }
References v8::internal::TaggedImpl< kRefType, StorageType >::ptr().
LogRejectedPromotionForInvalidSubgraph()
void v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::LogRejectedPromotionForInvalidSubgraph (Tagged< HeapObject > o, int first_rejected_slot_offset) [inline], [private]
Definition at line 395 of file read-only-promotion.cc.
                                                                              {
    std::cout << "ro-promotion: rejected due to rejected subgraph "
              << reinterpret_cast<void*>(o.ptr()) << " ("
              << o->map()->instance_type() << ")"
              << " at slot offset " << first_rejected_slot_offset << " ";
    MaybeObjectSlot slot = o->RawMaybeWeakField(first_rejected_slot_offset);
    Tagged<MaybeObject> maybe_object = slot.load(isolate_);
    Tagged<HeapObject> heap_object;
    if (maybe_object.GetHeapObject(&heap_object)) {
      std::cout << reinterpret_cast<void*>(heap_object.ptr()) << " ("
                << heap_object->map()->instance_type() << ")"
                << "\n";
    } else {
      std::cout << "<cleared weak object>\n";
    }
  }
References v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObject(), v8::internal::FullMaybeObjectSlot::load(), and v8::internal::TaggedImpl< kRefType, StorageType >::ptr().
LogRejectedPromotionForNoMatchingHost()
void v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::LogRejectedPromotionForNoMatchingHost (Tagged< HeapObject > o) [inline], [private]
Definition at line 387 of file read-only-promotion.cc.
                                                                   {
    std::cout << "ro-promotion: rejected because it wasn't included into any "
                 "accepted set "
              << reinterpret_cast<void*>(o.ptr()) << " ("
              << o->map()->instance_type() << ")"
              << "\n";
  }
References v8::internal::TaggedImpl< kRefType, StorageType >::ptr().
ref_encoder()
const ExternalReferenceEncoder& v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::ref_encoder () const [inline], [private]
Definition at line 70 of file read-only-promotion.cc.
{ return ref_encoder_; }
Member Data Documentation
isolate_
Isolate* const v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::isolate_ [private]
Definition at line 414 of file read-only-promotion.cc.
promo_accepted_
HeapObjectSet v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::promo_accepted_ [private]
Definition at line 416 of file read-only-promotion.cc.
promo_deferred_
HeapObjectSet v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::promo_deferred_ [private]
Definition at line 418 of file read-only-promotion.cc.
promo_rejected_
HeapObjectSet v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::promo_rejected_ [private]
Definition at line 417 of file read-only-promotion.cc.
ref_encoder_
ExternalReferenceEncoder v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::ref_encoder_ [private]
Definition at line 415 of file read-only-promotion.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/read-only-promotion.cc