v8::internal::compiler::PropertyCellRef Class Reference
#include <heap-refs.h>
Public Member Functions
IndirectHandle< PropertyCell > object () const
V8_WARN_UNUSED_RESULT bool Cache (JSHeapBroker *broker) const
void CacheAsProtector (JSHeapBroker *broker) const
PropertyDetails property_details () const
ObjectRef value (JSHeapBroker *broker) const
Detailed Description
Definition at line 546 of file heap-refs.h.
Member Function Documentation
Cache()
bool v8::internal::compiler::PropertyCellRef::Cache (JSHeapBroker * broker) const
Definition at line 2505 of file heap-refs.cc.
                                                      {
  if (data_->should_access_heap()) return true;
  CHECK(broker->mode() == JSHeapBroker::kSerializing ||
        broker->mode() == JSHeapBroker::kSerialized);
  return data()->AsPropertyCell()->Cache(broker);
}
References broker(), CHECK, v8::internal::compiler::JSHeapBroker::kSerialized, and v8::internal::compiler::JSHeapBroker::kSerializing.
Referenced by v8::internal::compiler::GlobalAccessFeedback::GetConstantHint(), v8::internal::compiler::JSNativeContextSpecialization::ReduceGlobalAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyCellLoad(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyCellStore().
CacheAsProtector()
void v8::internal::compiler::PropertyCellRef::CacheAsProtector (JSHeapBroker * broker) const [inline]
Definition at line 553 of file heap-refs.h.
                                                    {
    bool cached = Cache(broker);
    // A protector always holds a Smi value and its cell type never changes, so
    // Cache can't fail.
    CHECK(cached);
  }
References broker(), and CHECK.
Referenced by v8::internal::compiler::CompilationDependencies::DependOnProtector(), v8::internal::compiler::JSTypedLowering::GenerateStringAddition(), and v8::internal::compiler::JSTypedLowering::ReduceJSAdd().
object()
IndirectHandle<PropertyCell> v8::internal::compiler::PropertyCellRef::object () const
property_details()
PropertyDetails v8::internal::compiler::PropertyCellRef::property_details () const
Referenced by v8::internal::compiler::CompilationDependencies::DependOnGlobalProperty(), v8::internal::compiler::JSNativeContextSpecialization::ReduceGlobalAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyCellLoad(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyCellStore().
value()
ObjectRef v8::internal::compiler::PropertyCellRef::value (JSHeapBroker * broker) const
Referenced by v8::internal::compiler::CompilationDependencies::DependOnProtector(), v8::internal::compiler::JSTypedLowering::GenerateStringAddition(), v8::internal::compiler::GlobalAccessFeedback::GetConstantHint(), v8::internal::compiler::JSNativeContextSpecialization::ReduceGlobalAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyCellLoad(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyCellStore().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/heap-refs.h
/mnt/V8SourceCode/src/compiler/heap-refs.cc