v8::internal::ExternalPointerSlot Class Reference
#include <slots.h>
Public Types
using RawContent = ExternalPointer_t
Public Member Functions
ExternalPointerSlot ()
ExternalPointerSlot (Address ptr, ExternalPointerTag tag_range)
ExternalPointerSlot (Address ptr, ExternalPointerTagRange tag_range)
template<ExternalPointerTag tag>
ExternalPointerSlot (ExternalPointerMember< tag > *member)
void init_lazily_initialized ()
void init (IsolateForSandbox isolate, Tagged< HeapObject > host, Address value, ExternalPointerTag tag)
Address load (IsolateForSandbox isolate)
void store (IsolateForSandbox isolate, Address value, ExternalPointerTag tag)
ExternalPointerTag load_tag (IsolateForSandbox isolate)
RawContent GetAndClearContentForSerialization (const DisallowGarbageCollection &no_gc)
void RestoreContentAfterSerialization (RawContent content, const DisallowGarbageCollection &no_gc)
void ReplaceContentWithIndexForSerialization (const DisallowGarbageCollection &no_gc, uint32_t index)
uint32_t GetContentAsIndexAfterDeserialization (const DisallowGarbageCollection &no_gc)
bool ExactTagIsKnown () const
ExternalPointerTag exact_tag () const
ExternalPointerTagRange tag_range () const
Additional Inherited Members
Detailed Description
Definition at line 319 of file slots.h.
Member Typedef Documentation
RawContent
using v8::internal::ExternalPointerSlot::RawContent = ExternalPointer_t
Definition at line 399 of file slots.h.
Constructor & Destructor Documentation
ExternalPointerSlot() [1/4]
v8::internal::ExternalPointerSlot::ExternalPointerSlot () [inline]
Definition at line 323 of file slots.h.
      : SlotBase(kNullAddress)
#ifdef V8_COMPRESS_POINTERS
        ,
        tag_range_()
#endif
  {
  }
ExternalPointerSlot() [2/4]
v8::internal::ExternalPointerSlot::ExternalPointerSlot (Address ptr, ExternalPointerTag tag_range) [inline]
Definition at line 332 of file slots.h.
      : SlotBase(ptr)
#ifdef V8_COMPRESS_POINTERS
        ,
        tag_range_(tag_range)
#endif
  {
  }
ExternalPointerSlot() [3/4]
v8::internal::ExternalPointerSlot::ExternalPointerSlot (Address ptr, ExternalPointerTagRange tag_range) [inline]
Definition at line 341 of file slots.h.
      : SlotBase(ptr)
#ifdef V8_COMPRESS_POINTERS
        ,
        tag_range_(tag_range)
#endif
  {
  }
ExternalPointerSlot() [4/4]
template<ExternalPointerTag tag>
v8::internal::ExternalPointerSlot::ExternalPointerSlot (ExternalPointerMember< tag > * member) [inline], [explicit]
Definition at line 351 of file slots.h.
      : SlotBase(member->storage_address())
#ifdef V8_COMPRESS_POINTERS
        ,
        tag_range_(tag)
#endif
  {
  }
Member Function Documentation
exact_tag()
ExternalPointerTag v8::internal::ExternalPointerSlot::exact_tag () const [inline]
Definition at line 422 of file slots.h.
{ return kExternalPointerNullTag; }
References v8::internal::kExternalPointerNullTag.
Referenced by v8::internal::ObjectPostProcessor::DecodeExternalPointerSlot(), v8::internal::ObjectPostProcessor::DecodeLazilyInitializedExternalPointerSlot(), and v8::internal::anonymous_namespace{read-only-serializer.cc}::EncodeRelocationsVisitor::VisitExternalPointer().
ExactTagIsKnown()
bool v8::internal::ExternalPointerSlot::ExactTagIsKnown () const [inline]
Definition at line 420 of file slots.h.
{ return true; }
Referenced by v8::internal::ObjectPostProcessor::DecodeExternalPointerSlot(), and v8::internal::ObjectPostProcessor::DecodeLazilyInitializedExternalPointerSlot().
GetAndClearContentForSerialization()
ExternalPointerSlot::RawContent v8::internal::ExternalPointerSlot::GetAndClearContentForSerialization (const DisallowGarbageCollection & no_gc) [inline]
Definition at line 272 of file slots-inl.h.
                                            {
#ifdef V8_ENABLE_SANDBOX
  ExternalPointerHandle content = Relaxed_LoadHandle();
  Relaxed_StoreHandle(kNullExternalPointerHandle);
#else
  Address content = ReadMaybeUnalignedValue<Address>(address());
  WriteMaybeUnalignedValue<Address>(address(), kNullAddress);
#endif
  return content;
}
References v8::internal::SlotBase< ExternalPointerSlot, ExternalPointer_t, kTaggedSize >::address(), v8::internal::kNullAddress, and v8::internal::kNullExternalPointerHandle.
GetContentAsIndexAfterDeserialization()
uint32_t v8::internal::ExternalPointerSlot::GetContentAsIndexAfterDeserialization (const DisallowGarbageCollection & no_gc) [inline]
Definition at line 304 of file slots-inl.h.
                                            {
#ifdef V8_ENABLE_SANDBOX
  static_assert(sizeof(ExternalPointerHandle) == sizeof(uint32_t));
  return Relaxed_LoadHandle();
#else
  return static_cast<uint32_t>(ReadMaybeUnalignedValue<Address>(address()));
#endif
}
References v8::internal::SlotBase< ExternalPointerSlot, ExternalPointer_t, kTaggedSize >::address().
Referenced by v8::internal::ObjectPostProcessor::DecodeExternalPointerSlot(), and v8::internal::ObjectPostProcessor::DecodeLazilyInitializedExternalPointerSlot().
init()
void v8::internal::ExternalPointerSlot::init (IsolateForSandbox isolate, Tagged< HeapObject > host, Address value, ExternalPointerTag tag) [inline]
Definition at line 205 of file slots-inl.h.
                                                       {
#ifdef V8_ENABLE_SANDBOX
  ExternalPointerTable& table = isolate.GetExternalPointerTableFor(tag);
  ExternalPointerHandle handle = table.AllocateAndInitializeEntry(
      isolate.GetExternalPointerTableSpaceFor(tag, host.address()), value, tag);
  // Use a Release_Store to ensure that the store of the pointer into the
  // table is not reordered after the store of the handle. Otherwise, other
  // threads may access an uninitialized table entry and crash.
  Release_StoreHandle(handle);
#else
  store(isolate, value, tag);
#endif // V8_ENABLE_SANDBOX
}
References v8::internal::Tagged< HeapObject >::address(), v8::internal::handle(), store(), and v8::internal::value.
Referenced by v8::internal::ObjectPostProcessor::DecodeExternalPointerSlot(), and v8::internal::ObjectPostProcessor::DecodeLazilyInitializedExternalPointerSlot().
init_lazily_initialized()
void v8::internal::ExternalPointerSlot::init_lazily_initialized () [inline]
Definition at line 197 of file slots-inl.h.
                                                  {
#ifdef V8_ENABLE_SANDBOX
  Relaxed_StoreHandle(kNullExternalPointerHandle);
#else
  WriteMaybeUnalignedValue<Address>(address(), kNullAddress);
#endif // V8_ENABLE_SANDBOX
}
References v8::internal::SlotBase< ExternalPointerSlot, ExternalPointer_t, kTaggedSize >::address(), v8::internal::kNullAddress, and v8::internal::kNullExternalPointerHandle.
Referenced by v8::internal::ObjectPostProcessor::DecodeLazilyInitializedExternalPointerSlot().
load()
Address v8::internal::ExternalPointerSlot::load (IsolateForSandbox isolate) [inline]
Definition at line 237 of file slots-inl.h.
                                                           {
#ifdef V8_ENABLE_SANDBOX
  const ExternalPointerTable& table =
      isolate.GetExternalPointerTableFor(tag_range_);
  ExternalPointerHandle handle = Relaxed_LoadHandle();
  return table.Get(handle, tag_range_);
#else
  return ReadMaybeUnalignedValue<Address>(address());
#endif // V8_ENABLE_SANDBOX
}
References v8::internal::SlotBase< ExternalPointerSlot, ExternalPointer_t, kTaggedSize >::address(), and v8::internal::handle().
Referenced by v8::internal::anonymous_namespace{read-only-serializer.cc}::ObjectPreProcessor::EncodeExternalPointerSlot(), and v8::internal::Serializer::ObjectSerializer::VisitExternalPointer().
load_tag()
ExternalPointerTag v8::internal::ExternalPointerSlot::load_tag (IsolateForSandbox isolate) [inline]
Definition at line 260 of file slots-inl.h.
                                                                          {
#ifdef V8_ENABLE_SANDBOX
  const ExternalPointerTable& table =
      isolate.GetExternalPointerTableFor(tag_range_);
  ExternalPointerHandle handle = Relaxed_LoadHandle();
  return table.GetTag(handle);
#else
  return kExternalPointerNullTag;
#endif // V8_ENABLE_SANDBOX
}
References v8::internal::handle(), and v8::internal::kExternalPointerNullTag.
ReplaceContentWithIndexForSerialization()
void v8::internal::ExternalPointerSlot::ReplaceContentWithIndexForSerialization (const DisallowGarbageCollection & no_gc, uint32_t index) [inline]
Definition at line 294 of file slots-inl.h.
                                                            {
#ifdef V8_ENABLE_SANDBOX
  static_assert(sizeof(ExternalPointerHandle) == sizeof(uint32_t));
  Relaxed_StoreHandle(index);
#else
  WriteMaybeUnalignedValue<Address>(address(), static_cast<Address>(index));
#endif
}
References v8::internal::SlotBase< ExternalPointerSlot, ExternalPointer_t, kTaggedSize >::address(), and v8::internal::index.
Referenced by v8::internal::anonymous_namespace{read-only-serializer.cc}::ObjectPreProcessor::EncodeExternalPointerSlot().
RestoreContentAfterSerialization()
void v8::internal::ExternalPointerSlot::RestoreContentAfterSerialization (ExternalPointerSlot::RawContent content, const DisallowGarbageCollection & no_gc) [inline]
Definition at line 284 of file slots-inl.h.
                                            {
#ifdef V8_ENABLE_SANDBOX
  return Relaxed_StoreHandle(content);
#else
  return WriteMaybeUnalignedValue<Address>(address(), content);
#endif
}
References v8::internal::SlotBase< ExternalPointerSlot, ExternalPointer_t, kTaggedSize >::address().
store()
void v8::internal::ExternalPointerSlot::store (IsolateForSandbox isolate, Address value, ExternalPointerTag tag) [inline]
Definition at line 248 of file slots-inl.h.
                                                        {
#ifdef V8_ENABLE_SANDBOX
  DCHECK(tag_range_.Contains(tag));
  ExternalPointerTable& table = isolate.GetExternalPointerTableFor(tag);
  ExternalPointerHandle handle = Relaxed_LoadHandle();
  table.Set(handle, value, tag);
#else
  WriteMaybeUnalignedValue<Address>(address(), value);
#endif // V8_ENABLE_SANDBOX
}
References v8::internal::SlotBase< ExternalPointerSlot, ExternalPointer_t, kTaggedSize >::address(), v8::internal::DCHECK(), v8::internal::handle(), and v8::internal::value.
Referenced by init().
tag_range()
ExternalPointerTagRange v8::internal::ExternalPointerSlot::tag_range () const [inline]
Definition at line 424 of file slots.h.
                                            {
    return ExternalPointerTagRange();
  }
Referenced by v8::internal::WriteBarrier::MarkingSlow(), v8::internal::ScavengeVisitor::VisitExternalPointer(), and v8::internal::IterateAndScavengePromotedObjectsVisitor::VisitExternalPointer().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/slots.h
/mnt/V8SourceCode/src/objects/slots-inl.h