v8::internal::wasm::WasmImportWrapperCache Class Reference
#include <wasm-import-wrapper-cache.h>
Classes
struct CacheKey
class CacheKeyHash
class ModificationScope
Public Member Functions
WasmImportWrapperCache ()=default
~WasmImportWrapperCache ()=default
void LazyInitialize (Isolate *triggering_isolate)
void Free (std::vector< WasmCode * > &wrappers)
V8_EXPORT_PRIVATE std::shared_ptr< WasmImportWrapperHandle > Get (Isolate *isolate, ImportCallKind kind, CanonicalTypeIndex type_index, int expected_arity, Suspend suspend, const wasm::CanonicalSig *sig)
V8_EXPORT_PRIVATE std::shared_ptr< WasmImportWrapperHandle > GetCompiled (Isolate *isolate, ImportCallKind kind, CanonicalTypeIndex type_index, int expected_arity, Suspend suspend, const wasm::CanonicalSig *sig)
V8_EXPORT_PRIVATE std::shared_ptr< WasmImportWrapperHandle > CompileWasmJsFastCallWrapper (Isolate *isolate, DirectHandle< JSReceiver > callable, const wasm::CanonicalSig *sig)
WasmCode * Lookup (Address pc) const
void LogForIsolate (Isolate *isolate)
size_t EstimateCurrentMemoryConsumption () const
V8_EXPORT_PRIVATE bool HasCodeForTesting (ImportCallKind kind, CanonicalTypeIndex type_index, int expected_arity, Suspend suspend)
Private Member Functions
std::optional< Builtin > BuiltinForWrapper (ImportCallKind kind, const wasm::CanonicalSig *sig, Suspend suspend)
std::shared_ptr< WasmImportWrapperHandle > CompileWrapper (Isolate *isolate, const CacheKey &cache_key, const wasm::CanonicalSig *sig, std::shared_ptr< WasmImportWrapperHandle > optional_handle)
Private Attributes
std::unique_ptr< WasmCodeAllocator > code_allocator_
base::Mutex mutex_
std::unordered_map< CacheKey, std::weak_ptr< WasmImportWrapperHandle >, CacheKeyHash > entry_map_
std::map< Address, WasmCode * > codes_
Friends
class WasmImportWrapperHandle
Detailed Description
Definition at line 25 of file wasm-import-wrapper-cache.h.
Constructor & Destructor Documentation
WasmImportWrapperCache()
v8::internal::wasm::WasmImportWrapperCache::WasmImportWrapperCache () [default]
Referenced by EstimateCurrentMemoryConsumption().
 WasmImportWrapperCache()
v8::internal::wasm::WasmImportWrapperCache::~WasmImportWrapperCache () [default]
Member Function Documentation
BuiltinForWrapper()
std::optional< Builtin > v8::internal::wasm::WasmImportWrapperCache::BuiltinForWrapper (ImportCallKind kind, const wasm::CanonicalSig * sig, Suspend suspend) [private]
Definition at line 205 of file wasm-import-wrapper-cache.cc.
                                                                       {
  if (kind != ImportCallKind::kJSFunction) return {};
  if (!IsJSCompatibleSignature(sig)) {
    return Builtin::kWasmToJsWrapperInvalidSig;
  }
  if (UseGenericWasmToJSWrapper(kind, sig, suspend)) {
    return Builtin::kWasmToJsWrapperAsm;
  }
  return {};
}
References v8::internal::wasm::IsJSCompatibleSignature(), v8::internal::wasm::kJSFunction, v8::internal::sig, and v8::internal::UseGenericWasmToJSWrapper().
Referenced by Get().
CompileWasmJsFastCallWrapper()
std::shared_ptr< WasmImportWrapperHandle > v8::internal::wasm::WasmImportWrapperCache::CompileWasmJsFastCallWrapper (Isolate * isolate, DirectHandle< JSReceiver > callable, const wasm::CanonicalSig * sig)
Definition at line 374 of file wasm-import-wrapper-cache.cc.
                                 {
  // Note: the wrapper we're about to compile is specific to this
  // instantiation, so it cannot be shared.
  WasmCompilationResult result =
      compiler::CompileWasmJSFastCallWrapper(sig, callable);
  std::shared_ptr<WasmImportWrapperHandle> wrapper_handle =
      std::make_shared<WasmImportWrapperHandle>(kNullAddress,
                                                sig->signature_hash());
  WasmCode* wasm_code;
  {
    ModificationScope cache_scope(this);
    wasm_code = cache_scope.AddWrapper(std::move(result),
                                       WasmCode::Kind::kWasmToJsWrapper,
                                       sig->signature_hash(), wrapper_handle);
  }
  // To avoid lock order inversion, code printing must happen after the
  // end of the {cache_scope}.
  wasm_code->MaybePrint();
  isolate->counters()->wasm_generated_code_size()->Increment(
      wasm_code->instructions().length());
  isolate->counters()->wasm_reloc_size()->Increment(
      wasm_code->reloc_info().length());
  if (GetWasmEngine()->LogWrapperCode(wasm_code)) {
    // Log the code immediately in the current isolate.
    GetWasmEngine()->LogOutstandingCodesForIsolate(isolate);
  }
  return wrapper_handle;
}
References v8::internal::wasm::WasmImportWrapperCache::ModificationScope::AddWrapper(), v8::internal::compiler::CompileWasmJSFastCallWrapper(), v8::internal::Isolate::counters(), v8::internal::wasm::GetWasmEngine(), v8::internal::wasm::WasmCode::instructions(), v8::internal::kNullAddress, v8::base::Vector< T >::length(), v8::internal::wasm::WasmEngine::LogOutstandingCodesForIsolate(), v8::internal::wasm::WasmCode::MaybePrint(), v8::internal::wasm::WasmCode::reloc_info(), v8::base::internal::result, and v8::internal::sig.
Referenced by v8::internal::wasm::InstanceBuilder::ProcessImportedFunction().
CompileWrapper()
std::shared_ptr< WasmImportWrapperHandle > v8::internal::wasm::WasmImportWrapperCache::CompileWrapper (Isolate * isolate, const CacheKey & cache_key, const wasm::CanonicalSig * sig, std::shared_ptr< WasmImportWrapperHandle > optional_handle) [private]
Definition at line 307 of file wasm-import-wrapper-cache.cc.
                                                           {
  wasm::WasmCompilationResult result;
  wasm::WasmCode::Kind code_kind;
  switch (cache_key.kind) {
    case ImportCallKind::kLinkError:
    case ImportCallKind::kWasmToWasm:
    case ImportCallKind::kWasmToJSFastApi:
      UNREACHABLE();
    case ImportCallKind::kJSFunction:
    case ImportCallKind::kUseCallBuiltin:
    case ImportCallKind::kRuntimeTypeError:
      result = compiler::CompileWasmImportCallWrapper(
          cache_key.kind, sig, cache_key.expected_arity, cache_key.suspend);
      code_kind = WasmCode::Kind::kWasmToJsWrapper;
      break;
    case ImportCallKind::kWasmToCapi:
      result = compiler::CompileWasmCapiCallWrapper(sig);
      code_kind = wasm::WasmCode::Kind::kWasmToCapiWrapper;
      break;
  }
  WasmCode* wasm_code;
  {
    wasm::WasmImportWrapperCache::ModificationScope cache_scope(this);
    if (!wrapper_handle) {
      auto it = entry_map_.find(cache_key);
      if (it != entry_map_.end()) {
        wrapper_handle = it->second.lock();
      }
    }
    if (wrapper_handle && wrapper_handle->has_code()) {
      // There was a race and we have code now.
      return wrapper_handle;
    }
    if (!wrapper_handle) {
      wrapper_handle = std::make_shared<WasmImportWrapperHandle>(
          kNullAddress, sig->signature_hash());
      entry_map_[cache_key] = wrapper_handle;
    }
    wasm_code = cache_scope.AddWrapper(std::move(result), code_kind,
                                       sig->signature_hash(), wrapper_handle);
  }
  // To avoid lock order inversion, code printing must happen after the
  // end of the {cache_scope}.
  wasm_code->MaybePrint();
  if (isolate) {
    isolate->counters()->wasm_generated_code_size()->Increment(
        wasm_code->instructions().length());
    isolate->counters()->wasm_reloc_size()->Increment(
        wasm_code->reloc_info().length());
  }
  if (GetWasmEngine()->LogWrapperCode(wasm_code) && isolate) {
    // Log the code immediately in the current isolate.
    GetWasmEngine()->LogOutstandingCodesForIsolate(isolate);
  }
  return wrapper_handle;
}
References v8::internal::wasm::WasmImportWrapperCache::ModificationScope::AddWrapper(), v8::internal::compiler::CompileWasmCapiCallWrapper(), v8::internal::compiler::CompileWasmImportCallWrapper(), v8::internal::Isolate::counters(), entry_map_, v8::internal::wasm::WasmImportWrapperCache::CacheKey::expected_arity, v8::internal::wasm::GetWasmEngine(), v8::internal::wasm::WasmCode::instructions(), v8::internal::wasm::WasmImportWrapperCache::CacheKey::kind, v8::internal::wasm::kJSFunction, v8::internal::wasm::kLinkError, v8::internal::kNullAddress, v8::internal::wasm::kRuntimeTypeError, v8::internal::wasm::kUseCallBuiltin, v8::internal::wasm::kWasmToCapi, v8::internal::wasm::kWasmToJSFastApi, v8::internal::wasm::kWasmToWasm, v8::base::Vector< T >::length(), v8::internal::wasm::WasmEngine::LogOutstandingCodesForIsolate(), v8::internal::wasm::WasmCode::MaybePrint(), v8::internal::wasm::WasmCode::reloc_info(), v8::base::internal::result, v8::internal::sig, v8::internal::wasm::WasmImportWrapperCache::CacheKey::suspend, and v8::internal::UNREACHABLE().
Referenced by Get(), and GetCompiled().
EstimateCurrentMemoryConsumption()
size_t v8::internal::wasm::WasmImportWrapperCache::EstimateCurrentMemoryConsumption () const
Definition at line 424 of file wasm-import-wrapper-cache.cc.
                                                                      {
  UPDATE_WHEN_CLASS_CHANGES(WasmImportWrapperCache, 88);
  base::MutexGuard lock(&mutex_);
  return sizeof(WasmImportWrapperCache) + ContentSize(entry_map_) +
         ContentSize(codes_);
}
References codes_, v8::internal::wasm::ContentSize(), entry_map_, mutex_, UPDATE_WHEN_CLASS_CHANGES, and WasmImportWrapperCache().
Referenced by v8::internal::MemoryMeasurement::FinishProcessing().
Free()
void v8::internal::wasm::WasmImportWrapperCache::Free (std::vector< WasmCode * > & wrappers)
Definition at line 177 of file wasm-import-wrapper-cache.cc.
                                                                {
  base::MutexGuard lock(&mutex_);
  if (codes_.empty() || wrappers.empty()) return;
  // {WasmCodeAllocator::FreeCode()} wants code objects to be sorted.
  std::sort(wrappers.begin(), wrappers.end(), [](WasmCode* a, WasmCode* b) {
    return a->instruction_start() < b->instruction_start();
  });
  for (WasmCode* wrapper : wrappers) {
    codes_.erase(wrapper->instruction_start());
  }
  for (auto it = entry_map_.begin(); it != entry_map_.end();) {
    if (it->second.expired()) {
      it = entry_map_.erase(it);
    } else {
      it++;
    }
  }
  code_allocator_->FreeCode(base::VectorOf(wrappers));
  for (WasmCode* wrapper : wrappers) {
    // TODO(407003348): Drop this check if it doesn't trigger in the wild.
    CHECK_EQ(wrapper->ref_count_bitfield_.load(std::memory_order_acquire),
             WasmCode::kIsDyingMask);
    delete wrapper;
  }
  // Make sure nobody tries to access stale pointers.
  wrappers.clear();
}
References CHECK_EQ, code_allocator_, codes_, entry_map_, v8::internal::wasm::WasmCode::kIsDyingMask, mutex_, v8::base::sort(), and v8::base::VectorOf().
Referenced by v8::internal::wasm::WasmEngine::FreeDeadCodeLocked().
Get()
std::shared_ptr< WasmImportWrapperHandle > v8::internal::wasm::WasmImportWrapperCache::Get (Isolate * isolate, ImportCallKind kind, CanonicalTypeIndex type_index, int expected_arity, Suspend suspend, const wasm::CanonicalSig * sig)
Definition at line 220 of file wasm-import-wrapper-cache.cc.
                                                                      {
  CacheKey cache_key(kind, type_index, expected_arity, suspend);
  {
    base::MutexGuard lock(&mutex_);
    // If we have an entry already, just return that.
    auto it = entry_map_.find(cache_key);
    if (it != entry_map_.end()) {
      std::shared_ptr<WasmImportWrapperHandle> handle = it->second.lock();
      if (handle) {
        return handle;
      }
    }
    // Check if we should use a builtin.
    std::optional<Builtin> builtin = BuiltinForWrapper(kind, sig, suspend);
    if (builtin) {
      Address call_target = Builtins::EmbeddedEntryOf(*builtin);
      static_assert(Builtins::kAllBuiltinsAreIsolateIndependent);
      std::shared_ptr<WasmImportWrapperHandle> wrapper_handle =
          std::make_shared<WasmImportWrapperHandle>(call_target,
                                                    sig->signature_hash());
      entry_map_[cache_key] = wrapper_handle;
      return wrapper_handle;
    }
  }
  // Fall back to compile a new wrapper.
  return CompileWrapper(isolate, cache_key, sig, nullptr);
}
References BuiltinForWrapper(), CompileWrapper(), v8::internal::Builtins::EmbeddedEntryOf(), entry_map_, v8::internal::handle(), v8::internal::Builtins::kAllBuiltinsAreIsolateIndependent, mutex_, and v8::internal::sig.
Referenced by v8::internal::WasmJSFunction::New(), and v8::internal::wasm::InstanceBuilder::ProcessImportedFunction().
GetCompiled()
std::shared_ptr< WasmImportWrapperHandle > v8::internal::wasm::WasmImportWrapperCache::GetCompiled (Isolate * isolate, ImportCallKind kind, CanonicalTypeIndex type_index, int expected_arity, Suspend suspend, const wasm::CanonicalSig * sig)
Definition at line 283 of file wasm-import-wrapper-cache.cc.
                                                                  {
  CHECK_NE(kind, ImportCallKind::kWasmToJSFastApi);
  DCHECK(!v8_flags.wasm_jitless);
  CacheKey cache_key{kind, type_index, expected_arity, suspend};
  std::shared_ptr<wasm::WasmImportWrapperHandle> wrapper_handle;
  {
    base::MutexGuard lock(&mutex_);
    auto it = entry_map_.find(cache_key);
    if (it != entry_map_.end()) {
      wrapper_handle = it->second.lock();
      if (wrapper_handle && wrapper_handle->has_code()) {
        return wrapper_handle;
      }
    }
  }
  return CompileWrapper(isolate, cache_key, sig, wrapper_handle);
}
References CHECK_NE, CompileWrapper(), v8::internal::DCHECK(), entry_map_, v8::internal::wasm::kWasmToJSFastApi, mutex_, v8::internal::sig, and v8::internal::v8_flags.
Referenced by v8::internal::wasm::CompileImportWrapperForTest(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::WasmTableObject::UpdateDispatchTable().
HasCodeForTesting()
bool v8::internal::wasm::WasmImportWrapperCache::HasCodeForTesting (ImportCallKind kind, CanonicalTypeIndex type_index, int expected_arity, Suspend suspend)
Definition at line 269 of file wasm-import-wrapper-cache.cc.
                                                                {
  base::MutexGuard lock(&mutex_);
  CacheKey cache_key(kind, type_index, expected_arity, suspend);
  auto it = entry_map_.find(cache_key);
  if (it == entry_map_.end()) return false;
  auto handle = it->second.lock();
  if (!handle) return false;
  return handle->has_code();
}
References entry_map_, v8::internal::handle(), and mutex_.
LazyInitialize()
void v8::internal::wasm::WasmImportWrapperCache::LazyInitialize (Isolate * triggering_isolate)
Definition at line 59 of file wasm-import-wrapper-cache.cc.
                                                                       {
  base::MutexGuard lock(&mutex_);
  if (code_allocator_.get() != nullptr) return; // Already initialized.
  // Most wrappers are small (200-300 bytes), most modules don't need many.
  // 32K is enough for ~100 wrappers.
  static constexpr size_t kInitialReservationSize = 1 << 15;
  // See {NewNativeModule} for reasoning.
  static constexpr int kAllocationRetries = 2;
  VirtualMemory code_space;
  for (int retries = 0;; ++retries) {
    code_space = GetWasmCodeManager()->TryAllocate(kInitialReservationSize);
    if (code_space.IsReserved()) break;
    if (retries == kAllocationRetries) {
      V8::FatalProcessOutOfMemory(
          triggering_isolate,
          "Failed to allocate code space for import wrappers");
      UNREACHABLE();
    }
    triggering_isolate->heap()->MemoryPressureNotification(
        MemoryPressureLevel::kCritical, true);
  }
  code_allocator_.reset(
      new WasmCodeAllocator(triggering_isolate->async_counters()));
  base::AddressRegion initial_region = code_space.region();
  code_allocator_->Init(std::move(code_space));
  code_allocator_->InitializeCodeRange(nullptr, initial_region);
}
References v8::internal::Isolate::async_counters(), code_allocator_, v8::internal::V8::FatalProcessOutOfMemory(), v8::internal::wasm::GetWasmCodeManager(), v8::internal::Isolate::heap(), v8::internal::VirtualMemory::IsReserved(), v8::kCritical, v8::internal::Heap::MemoryPressureNotification(), mutex_, v8::internal::VirtualMemory::region(), v8::internal::wasm::WasmCodeManager::TryAllocate(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::WasmJSFunction::New(), and v8::internal::wasm::WasmEngine::NewNativeModule().
LogForIsolate()
void v8::internal::wasm::WasmImportWrapperCache::LogForIsolate (Isolate * isolate)
Definition at line 170 of file wasm-import-wrapper-cache.cc.
                                                           {
  base::MutexGuard lock(&mutex_);
  for (const auto& entry : codes_) {
    entry.second->LogCode(isolate, "", -1); // No source URL, no ScriptId.
  }
}
References codes_, and mutex_.
Referenced by v8::internal::wasm::WasmEngine::AddIsolate(), and v8::internal::ExistingCodeLogger::LogCompiledFunctions().
Lookup()
WasmCode * v8::internal::wasm::WasmImportWrapperCache::Lookup (Address pc) const
Definition at line 407 of file wasm-import-wrapper-cache.cc.
                                                         {
  // This can be called from the disassembler via `code->MaybePrint()` in
  // `AddWrapper()` above, so we need a recursive mutex.
  base::MutexGuard lock(&mutex_);
  auto iter = codes_.upper_bound(pc);
  if (iter == codes_.begin()) return nullptr;
  --iter;
  WasmCode* candidate = iter->second;
  DCHECK_EQ(candidate->instruction_start(), iter->first);
  if (!candidate->contains(pc)) return nullptr;
  WasmCodeRefScope::AddRef(candidate);
  // Note: this function is used for iterating the stack, where dying
  // code objects can still have their last few activations, so we
  // must return {candidate} even if {candidate->is_dying()}.
  return candidate;
}
References v8::internal::wasm::WasmCodeRefScope::AddRef(), codes_, v8::internal::wasm::WasmCode::contains(), DCHECK_EQ, v8::internal::wasm::WasmCode::instruction_start(), and mutex_.
Referenced by v8::internal::wasm::WasmCodeManager::LookupCode().
Friends And Related Function Documentation
WasmImportWrapperHandle
friend class WasmImportWrapperHandle [friend]
Definition at line 121 of file wasm-import-wrapper-cache.h.
Member Data Documentation
code_allocator_
std::unique_ptr<WasmCodeAllocator> v8::internal::wasm::WasmImportWrapperCache::code_allocator_ [private]
Definition at line 112 of file wasm-import-wrapper-cache.h.
Referenced by v8::internal::wasm::WasmImportWrapperCache::ModificationScope::AddWrapper(), Free(), and LazyInitialize().
codes_
std::map<Address, WasmCode*> v8::internal::wasm::WasmImportWrapperCache::codes_ [private]
Definition at line 119 of file wasm-import-wrapper-cache.h.
Referenced by v8::internal::wasm::WasmImportWrapperCache::ModificationScope::AddWrapper(), EstimateCurrentMemoryConsumption(), Free(), LogForIsolate(), and Lookup().
entry_map_
std::unordered_map<CacheKey, std::weak_ptr<WasmImportWrapperHandle>, CacheKeyHash> v8::internal::wasm::WasmImportWrapperCache::entry_map_ [private]
Definition at line 116 of file wasm-import-wrapper-cache.h.
Referenced by CompileWrapper(), EstimateCurrentMemoryConsumption(), Free(), Get(), GetCompiled(), and HasCodeForTesting().
mutex_
base::Mutex v8::internal::wasm::WasmImportWrapperCache::mutex_ [mutable], [private]
Definition at line 113 of file wasm-import-wrapper-cache.h.
Referenced by v8::internal::wasm::WasmImportWrapperCache::ModificationScope::AddWrapper(), EstimateCurrentMemoryConsumption(), Free(), Get(), GetCompiled(), HasCodeForTesting(), LazyInitialize(), LogForIsolate(), Lookup(), and v8::internal::wasm::WasmImportWrapperHandle::set_code().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-import-wrapper-cache.h
/mnt/V8SourceCode/src/wasm/wasm-import-wrapper-cache.cc