v8::internal::SafepointTableBuilderBase Class Reference
#include <safepoint-table-base.h>
Public Member Functions
bool emitted () const
int safepoint_table_offset () const
Protected Member Functions
void set_safepoint_table_offset (int offset)
Private Attributes
int safepoint_table_offset_ = kNoSafepointTableOffset
Static Private Attributes
static constexpr int kNoSafepointTableOffset = -1
Detailed Description
Definition at line 64 of file safepoint-table-base.h.
Member Function Documentation
emitted()
bool v8::internal::SafepointTableBuilderBase::emitted () const [inline]
Definition at line 66 of file safepoint-table-base.h.
                       {
    return safepoint_table_offset_ != kNoSafepointTableOffset;
  }
References kNoSafepointTableOffset, and safepoint_table_offset_.
Referenced by safepoint_table_offset(), and set_safepoint_table_offset().
safepoint_table_offset()
int v8::internal::SafepointTableBuilderBase::safepoint_table_offset () const [inline]
Definition at line 70 of file safepoint-table-base.h.
                                     {
    DCHECK(emitted());
    return safepoint_table_offset_;
  }
References v8::internal::DCHECK(), emitted(), and safepoint_table_offset_.
Referenced by v8::internal::Assembler::GetCode().
set_safepoint_table_offset()
void v8::internal::SafepointTableBuilderBase::set_safepoint_table_offset (int offset) [inline], [protected]
Definition at line 76 of file safepoint-table-base.h.
                                              {
    DCHECK(!emitted());
    safepoint_table_offset_ = offset;
    DCHECK(emitted());
  }
References v8::internal::DCHECK(), emitted(), and safepoint_table_offset_.
Referenced by v8::internal::SafepointTableBuilder::Emit(), and v8::internal::MaglevSafepointTableBuilder::Emit().
Member Data Documentation
kNoSafepointTableOffset
constexpr int v8::internal::SafepointTableBuilderBase::kNoSafepointTableOffset = -1 [static], [constexpr], [private]
Definition at line 83 of file safepoint-table-base.h.
Referenced by emitted().
safepoint_table_offset_
int v8::internal::SafepointTableBuilderBase::safepoint_table_offset_ = kNoSafepointTableOffset [private]
Definition at line 84 of file safepoint-table-base.h.
Referenced by emitted(), safepoint_table_offset(), and set_safepoint_table_offset().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/codegen/safepoint-table-base.h