v8::internal::compiler::StateValuesCache Class Reference
#include <state-values-utils.h>
Classes
struct NodeKey
struct StateValuesKey
Public Member Functions
StateValuesCache (JSGraph *js_graph)
Node * GetNodeForValues (Node **values, size_t count, const BytecodeLivenessState *liveness=nullptr)
Private Types
using WorkingBuffer = std::array< Node *, kMaxInputCount >
Private Member Functions
SparseInputMask::BitMaskType FillBufferWithValues (WorkingBuffer *node_buffer, size_t *node_count, size_t *values_idx, Node **values, size_t count, const BytecodeLivenessState *liveness)
Node * BuildTree (size_t *values_idx, Node **values, size_t count, const BytecodeLivenessState *liveness, size_t level)
WorkingBuffer * GetWorkingSpace (size_t level)
Node * GetEmptyStateValues ()
Node * GetValuesNodeFromCache (Node **nodes, size_t count, SparseInputMask mask)
TFGraph * graph ()
CommonOperatorBuilder * common ()
Zone * zone ()
Static Private Member Functions
static bool AreKeysEqual (void *key1, void *key2)
static bool IsKeysEqualToNode (StateValuesKey *key, Node *node)
static bool AreValueKeysEqual (StateValuesKey *key1, StateValuesKey *key2)
Private Attributes
JSGraph * js_graph_
CustomMatcherZoneHashMap hash_map_
ZoneVector< WorkingBuffer > working_space_
Node * empty_state_values_
Static Private Attributes
static const size_t kMaxInputCount = 8
Detailed Description
Definition at line 24 of file state-values-utils.h.
Member Typedef Documentation
WorkingBuffer
using v8::internal::compiler::StateValuesCache::WorkingBuffer = std::array<Node*, kMaxInputCount> [private]
Definition at line 33 of file state-values-utils.h.
Constructor & Destructor Documentation
StateValuesCache()
v8::internal::compiler::StateValuesCache::StateValuesCache (JSGraph * js_graph) [explicit]
Definition at line 14 of file state-values-utils.cc.
    : js_graph_(js_graph),
      hash_map_(AreKeysEqual, ZoneHashMap::kDefaultHashMapCapacity,
                ZoneAllocationPolicy(zone())),
      working_space_(zone()),
      empty_state_values_(nullptr) {}
Member Function Documentation
AreKeysEqual()
bool v8::internal::compiler::StateValuesCache::AreKeysEqual (void * key1, void * key2) [static], [private]
Definition at line 23 of file state-values-utils.cc.
                                                          {
  NodeKey* node_key1 = reinterpret_cast<NodeKey*>(key1);
  NodeKey* node_key2 = reinterpret_cast<NodeKey*>(key2);
  if (node_key1->node == nullptr) {
    if (node_key2->node == nullptr) {
      return AreValueKeysEqual(reinterpret_cast<StateValuesKey*>(key1),
                               reinterpret_cast<StateValuesKey*>(key2));
    } else {
      return IsKeysEqualToNode(reinterpret_cast<StateValuesKey*>(key1),
                               node_key2->node);
    }
  } else {
    if (node_key2->node == nullptr) {
      // If the nodes are already processed, they must be the same.
      return IsKeysEqualToNode(reinterpret_cast<StateValuesKey*>(key2),
                               node_key1->node);
    } else {
      return node_key1->node == node_key2->node;
    }
  }
  UNREACHABLE();
}
References AreValueKeysEqual(), IsKeysEqualToNode(), v8::internal::compiler::StateValuesCache::NodeKey::node, and v8::internal::UNREACHABLE().
AreValueKeysEqual()
bool v8::internal::compiler::StateValuesCache::AreValueKeysEqual (StateValuesKey * key1, StateValuesKey * key2) [static], [private]
Definition at line 73 of file state-values-utils.cc.
                                                               {
  if (key1->count != key2->count) {
    return false;
  }
  if (key1->mask != key2->mask) {
    return false;
  }
  for (size_t i = 0; i < key1->count; i++) {
    if (key1->values[i] != key2->values[i]) {
      return false;
    }
  }
  return true;
}
References v8::internal::compiler::StateValuesCache::StateValuesKey::count, v8::internal::compiler::StateValuesCache::StateValuesKey::mask, and v8::internal::compiler::StateValuesCache::StateValuesKey::values.
Referenced by AreKeysEqual().
BuildTree()
Node * v8::internal::compiler::StateValuesCache::BuildTree (size_t * values_idx, Node ** values, size_t count, const BytecodeLivenessState * liveness, size_t level) [private]
Definition at line 170 of file state-values-utils.cc.
                                                {
  WorkingBuffer* node_buffer = GetWorkingSpace(level);
  size_t node_count = 0;
  SparseInputMask::BitMaskType input_mask = SparseInputMask::kDenseBitMask;
  if (level == 0) {
    input_mask = FillBufferWithValues(node_buffer, &node_count, values_idx,
                                      values, count, liveness);
    // Make sure we returned a sparse input mask.
    DCHECK_NE(input_mask, SparseInputMask::kDenseBitMask);
  } else {
    while (*values_idx < count && node_count < kMaxInputCount) {
      if (count - *values_idx < kMaxInputCount - node_count) {
        // If we have fewer values remaining than inputs remaining, dump the
        // remaining values into this node.
        // TODO(leszeks): We could optimise this further by only counting
        // remaining live nodes.
        size_t previous_input_count = node_count;
        input_mask = FillBufferWithValues(node_buffer, &node_count, values_idx,
                                          values, count, liveness);
        // Make sure we have exhausted our values.
        DCHECK_EQ(*values_idx, count);
        // Make sure we returned a sparse input mask.
        DCHECK_NE(input_mask, SparseInputMask::kDenseBitMask);
        // Make sure we haven't touched inputs below previous_input_count in the
        // mask.
        DCHECK_EQ(input_mask & ((1 << previous_input_count) - 1), 0u);
        // Mark all previous inputs as live.
        input_mask |= ((1 << previous_input_count) - 1);
        break;
      } else {
        // Otherwise, add the values to a subtree and add that as an input.
        Node* subtree =
            BuildTree(values_idx, values, count, liveness, level - 1);
        (*node_buffer)[node_count++] = subtree;
        // Don't touch the bitmask, so that it stays dense.
      }
    }
  }
  if (node_count == 1 && input_mask == SparseInputMask::kDenseBitMask) {
    // Elide the StateValue node if there is only one, dense input. This will
    // only happen if we built a single subtree (as nodes with values are always
    // sparse), and so we can replace ourselves with it.
    DCHECK_EQ((*node_buffer)[0]->opcode(), IrOpcode::kStateValues);
    return (*node_buffer)[0];
  } else {
    return GetValuesNodeFromCache(node_buffer->data(), node_count,
                                  SparseInputMask(input_mask));
  }
}
References DCHECK_EQ, DCHECK_NE, FillBufferWithValues(), GetValuesNodeFromCache(), GetWorkingSpace(), v8::internal::compiler::SparseInputMask::kDenseBitMask, and kMaxInputCount.
Referenced by GetNodeForValues().
common()
CommonOperatorBuilder* v8::internal::compiler::StateValuesCache::common () [inline], [private]
Definition at line 72 of file state-values-utils.h.
{ return js_graph_->common(); }
Referenced by GetEmptyStateValues(), and GetValuesNodeFromCache().
FillBufferWithValues()
SparseInputMask::BitMaskType v8::internal::compiler::StateValuesCache::FillBufferWithValues (WorkingBuffer * node_buffer, size_t * node_count, size_t * values_idx, Node ** values, size_t count, const BytecodeLivenessState * liveness) [private]
Definition at line 138 of file state-values-utils.cc.
                                                                        {
  SparseInputMask::BitMaskType input_mask = 0;
  // Virtual nodes are the live nodes plus the implicit optimized out nodes,
  // which are implied by the liveness mask.
  size_t virtual_node_count = *node_count;
  while (*values_idx < count && *node_count < kMaxInputCount &&
         virtual_node_count < SparseInputMask::kMaxSparseInputs) {
    DCHECK_LE(*values_idx, static_cast<size_t>(INT_MAX));
    if (liveness == nullptr ||
        liveness->RegisterIsLive(static_cast<int>(*values_idx))) {
      input_mask |= 1 << (virtual_node_count);
      (*node_buffer)[(*node_count)++] = values[*values_idx];
    }
    virtual_node_count++;
    (*values_idx)++;
  }
  DCHECK_GE(StateValuesCache::kMaxInputCount, *node_count);
  DCHECK_GE(SparseInputMask::kMaxSparseInputs, virtual_node_count);
  // Add the end marker at the end of the mask.
  input_mask |= SparseInputMask::kEndMarker << virtual_node_count;
  return input_mask;
}
References DCHECK_GE, DCHECK_LE, v8::internal::compiler::SparseInputMask::kEndMarker, kMaxInputCount, v8::internal::compiler::SparseInputMask::kMaxSparseInputs, and v8::internal::compiler::BytecodeLivenessState::RegisterIsLive().
Referenced by BuildTree().
GetEmptyStateValues()
Node * v8::internal::compiler::StateValuesCache::GetEmptyStateValues () [private]
Definition at line 90 of file state-values-utils.cc.
                                            {
  if (empty_state_values_ == nullptr) {
    empty_state_values_ =
        graph()->NewNode(common()->StateValues(0, SparseInputMask::Dense()));
  }
  return empty_state_values_;
}
References common(), v8::internal::compiler::SparseInputMask::Dense(), empty_state_values_, graph(), and v8::internal::compiler::TFGraph::NewNode().
Referenced by GetNodeForValues().
GetNodeForValues()
Node * v8::internal::compiler::StateValuesCache::GetNodeForValues (Node ** values, size_t count, const BytecodeLivenessState * liveness = nullptr)
Definition at line 253 of file state-values-utils.cc.
                                                                        {
#if DEBUG
  // Check that the values represent actual values, and not a tree of values.
  for (size_t i = 0; i < count; i++) {
    if (values[i] != nullptr) {
      DCHECK_NE(values[i]->opcode(), IrOpcode::kStateValues);
      DCHECK_NE(values[i]->opcode(), IrOpcode::kTypedStateValues);
    }
  }
  if (liveness != nullptr) {
    DCHECK_LE(count, static_cast<size_t>(liveness->register_count()));
    for (size_t i = 0; i < count; i++) {
      if (liveness->RegisterIsLive(static_cast<int>(i))) {
        DCHECK_NOT_NULL(values[i]);
      }
    }
  }
#endif
  if (count == 0) {
    return GetEmptyStateValues();
  }
  // This is a worst-case tree height estimate, assuming that all values are
  // live. We could get a better estimate by counting zeroes in the liveness
  // vector, but there's no point -- any excess height in the tree will be
  // collapsed by the single-input elision at the end of BuildTree.
  size_t height = 0;
  size_t max_inputs = kMaxInputCount;
  while (count > max_inputs) {
    height++;
    max_inputs *= kMaxInputCount;
  }
  size_t values_idx = 0;
  Node* tree = BuildTree(&values_idx, values, count, liveness, height);
  // The values should be exhausted by the end of BuildTree.
  DCHECK_EQ(values_idx, count);
  // The 'tree' must be rooted with a state value node.
  DCHECK_EQ(tree->opcode(), IrOpcode::kStateValues);
#if DEBUG
  CheckTreeContainsValues(tree, values, count, liveness);
#endif
  return tree;
}
References BuildTree(), DCHECK_EQ, DCHECK_LE, DCHECK_NE, DCHECK_NOT_NULL, GetEmptyStateValues(), kMaxInputCount, v8::internal::compiler::Node::opcode(), v8::internal::compiler::BytecodeLivenessState::register_count(), and v8::internal::compiler::BytecodeLivenessState::RegisterIsLive().
GetValuesNodeFromCache()
Node * v8::internal::compiler::StateValuesCache::GetValuesNodeFromCache (Node ** nodes, size_t count, SparseInputMask mask) [private]
Definition at line 118 of file state-values-utils.cc.
                                                                     {
  StateValuesKey key(count, mask, nodes);
  int hash = StateValuesHashKey(nodes, count);
  ZoneHashMap::Entry* lookup = hash_map_.LookupOrInsert(&key, hash);
  DCHECK_NOT_NULL(lookup);
  Node* node;
  if (lookup->value == nullptr) {
    int node_count = static_cast<int>(count);
    node = graph()->NewNode(common()->StateValues(node_count, mask), node_count,
                            nodes);
    NodeKey* new_key = zone()->New<NodeKey>(node);
    lookup->key = new_key;
    lookup->value = node;
  } else {
    node = reinterpret_cast<Node*>(lookup->value);
  }
  return node;
}
References common(), DCHECK_NOT_NULL, graph(), hash_map_, v8::base::TemplateHashMapEntry< Key, Value >::key, v8::internal::key, v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::LookupOrInsert(), v8::internal::Zone::New(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::anonymous_namespace{state-values-utils.cc}::StateValuesHashKey(), v8::base::TemplateHashMapEntry< Key, Value >::value, and zone().
Referenced by BuildTree().
GetWorkingSpace()
StateValuesCache::WorkingBuffer * v8::internal::compiler::StateValuesCache::GetWorkingSpace (size_t level) [private]
Definition at line 98 of file state-values-utils.cc.
                  {
  if (working_space_.size() <= level) {
    working_space_.resize(level + 1);
  }
  return &working_space_[level];
}
References v8::internal::ZoneVector< T >::resize(), v8::internal::ZoneVector< T >::size(), and working_space_.
Referenced by BuildTree().
graph()
TFGraph* v8::internal::compiler::StateValuesCache::graph () [inline], [private]
Definition at line 71 of file state-values-utils.h.
{ return js_graph_->graph(); }
Referenced by GetEmptyStateValues(), and GetValuesNodeFromCache().
IsKeysEqualToNode()
bool v8::internal::compiler::StateValuesCache::IsKeysEqualToNode (StateValuesKey * key, Node * node) [static], [private]
Definition at line 49 of file state-values-utils.cc.
                                                                        {
  if (key->count != static_cast<size_t>(node->InputCount())) {
    return false;
  }
  DCHECK_EQ(IrOpcode::kStateValues, node->opcode());
  SparseInputMask node_mask = SparseInputMaskOf(node->op());
  if (node_mask != key->mask) {
    return false;
  }
  // Comparing real inputs rather than sparse inputs, since we already know the
  // sparse input masks are the same.
  for (size_t i = 0; i < key->count; i++) {
    if (key->values[i] != node->InputAt(static_cast<int>(i))) {
      return false;
    }
  }
  return true;
}
References DCHECK_EQ, v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::InputCount(), v8::internal::key, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), and v8::internal::compiler::SparseInputMaskOf().
Referenced by AreKeysEqual().
zone()
Zone* v8::internal::compiler::StateValuesCache::zone () [inline], [private]
Definition at line 74 of file state-values-utils.h.
{ return graph()->zone(); }
References graph().
Referenced by GetValuesNodeFromCache().
Member Data Documentation
empty_state_values_
Node* v8::internal::compiler::StateValuesCache::empty_state_values_ [private]
Definition at line 79 of file state-values-utils.h.
Referenced by GetEmptyStateValues().
hash_map_
CustomMatcherZoneHashMap v8::internal::compiler::StateValuesCache::hash_map_ [private]
Definition at line 77 of file state-values-utils.h.
Referenced by GetValuesNodeFromCache().
js_graph_
JSGraph* v8::internal::compiler::StateValuesCache::js_graph_ [private]
Definition at line 76 of file state-values-utils.h.
kMaxInputCount
const size_t v8::internal::compiler::StateValuesCache::kMaxInputCount = 8 [static], [private]
Definition at line 32 of file state-values-utils.h.
Referenced by BuildTree(), FillBufferWithValues(), and GetNodeForValues().
working_space_
ZoneVector<WorkingBuffer> v8::internal::compiler::StateValuesCache::working_space_ [private]
Definition at line 78 of file state-values-utils.h.
Referenced by GetWorkingSpace().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/state-values-utils.h
/mnt/V8SourceCode/src/compiler/state-values-utils.cc