v8::internal::JSWeakCollection Class Reference
#include <js-collection.h>
Classes
class BodyDescriptorImpl
Public Types
using BodyDescriptor = BodyDescriptorImpl
Static Public Member Functions
static void Initialize (DirectHandle< JSWeakCollection > collection, Isolate *isolate)
static V8_EXPORT_PRIVATE void Set (DirectHandle< JSWeakCollection > collection, DirectHandle< Object > key, DirectHandle< Object > value, int32_t hash)
static bool Delete (DirectHandle< JSWeakCollection > collection, DirectHandle< Object > key, int32_t hash)
static DirectHandle< JSArray > GetEntries (DirectHandle< JSWeakCollection > holder, uint32_t max_entries)
Static Public Attributes
static const int kAddFunctionDescriptorIndex = 3
static const int kHeaderSizeOfAllWeakCollections = kHeaderSize
Detailed Description
Definition at line 85 of file js-collection.h.
Member Typedef Documentation
BodyDescriptor
using v8::internal::JSWeakCollection::BodyDescriptor = BodyDescriptorImpl
Definition at line 104 of file js-collection.h.
Member Function Documentation
Delete()
bool v8::internal::JSWeakCollection::Delete (DirectHandle< JSWeakCollection > collection, DirectHandle< Object > key, int32_t hash) [static]
Definition at line 6367 of file objects.cc.
                                                                      {
  DCHECK(IsJSReceiver(*key) || IsSymbol(*key));
  Handle<EphemeronHashTable> table(
      Cast<EphemeronHashTable>(weak_collection->table()), Isolate::Current());
  DCHECK(table->IsKey(GetReadOnlyRoots(), *key));
  bool was_present = false;
  DirectHandle<EphemeronHashTable> new_table = EphemeronHashTable::Remove(
      Isolate::Current(), table, key, &was_present, hash);
  weak_collection->set_table(*new_table);
  if (*table != *new_table) {
    // Zap the old table since we didn't record slots for its elements.
    EphemeronHashTable::FillEntriesWithHoles(table);
  }
  return was_present;
}
References v8::internal::Isolate::Current(), v8::internal::DCHECK(), v8::internal::GetReadOnlyRoots(), and v8::internal::key.
Referenced by v8::internal::RUNTIME_FUNCTION().
GetEntries()
DirectHandle< JSArray > v8::internal::JSWeakCollection::GetEntries (DirectHandle< JSWeakCollection > holder, uint32_t max_entries) [static]
Definition at line 6384 of file objects.cc.
                                                                 {
  Isolate* isolate = Isolate::Current();
  DirectHandle<EphemeronHashTable> table(
      Cast<EphemeronHashTable>(holder->table()), isolate);
  if (max_entries == 0 || max_entries > table->NumberOfElements()) {
    max_entries = table->NumberOfElements();
  }
  int values_per_entry = IsJSWeakMap(*holder) ? 2 : 1;
  DirectHandle<FixedArray> entries =
      isolate->factory()->NewFixedArray(max_entries * values_per_entry);
  // Recompute max_values because GC could have removed elements from the table.
  if (max_entries > table->NumberOfElements()) {
    max_entries = table->NumberOfElements();
  }
  {
    DisallowGarbageCollection no_gc;
    ReadOnlyRoots roots = ReadOnlyRoots(isolate);
    uint32_t count = 0;
    for (uint32_t i = 0;
         count / values_per_entry < max_entries && i < table->Capacity(); i++) {
      Tagged<Object> key;
      if (table->ToKey(roots, InternalIndex(i), &key)) {
        entries->set(count++, key);
        if (values_per_entry > 1) {
          Tagged<Object> value = table->Lookup(direct_handle(key, isolate));
          entries->set(count++, value);
        }
      }
    }
    DCHECK_EQ(max_entries * values_per_entry, count);
  }
  return isolate->factory()->NewJSArrayWithElements(entries);
}
References v8::internal::Isolate::Current(), DCHECK_EQ, v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::key, v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::Factory::NewJSArrayWithElements(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::value.
Referenced by v8::Object::PreviewEntries().
Initialize()
void v8::internal::JSWeakCollection::Initialize (DirectHandle< JSWeakCollection > collection, Isolate * isolate) [static]
Definition at line 6345 of file objects.cc.
                                                                      {
  DirectHandle<EphemeronHashTable> table = EphemeronHashTable::New(isolate, 0);
  weak_collection->set_table(*table);
}
References v8::internal::anonymous_namespace{intl-objects.cc}::New().
Referenced by v8::internal::Factory::NewJSWeakMap().
Set()
void v8::internal::JSWeakCollection::Set (DirectHandle< JSWeakCollection > collection, DirectHandle< Object > key, DirectHandle< Object > value, int32_t hash) [static]
Definition at line 6351 of file objects.cc.
                                         {
  DCHECK(IsJSReceiver(*key) || IsSymbol(*key));
  Handle<EphemeronHashTable> table(
      Cast<EphemeronHashTable>(weak_collection->table()), Isolate::Current());
  DCHECK(table->IsKey(GetReadOnlyRoots(), *key));
  DirectHandle<EphemeronHashTable> new_table =
      EphemeronHashTable::Put(Isolate::Current(), table, key, value, hash);
  weak_collection->set_table(*new_table);
  if (*table != *new_table) {
    // Zap the old table since we didn't record slots for its elements.
    EphemeronHashTable::FillEntriesWithHoles(table);
  }
}
References v8::internal::Isolate::Current(), v8::internal::DCHECK(), v8::internal::GetReadOnlyRoots(), v8::internal::key, and v8::internal::value.
Referenced by v8::internal::RUNTIME_FUNCTION(), and wasm::StoreImpl::SetHostInfo().
Member Data Documentation
kAddFunctionDescriptorIndex
const int v8::internal::JSWeakCollection::kAddFunctionDescriptorIndex = 3 [static]
Definition at line 98 of file js-collection.h.
Referenced by v8::internal::BaseCollectionsAssembler::GotoIfInitialAddFunctionModified(), and v8::internal::Genesis::InitializeGlobal().
kHeaderSizeOfAllWeakCollections
const int v8::internal::JSWeakCollection::kHeaderSizeOfAllWeakCollections = kHeaderSize [static]
Definition at line 106 of file js-collection.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-collection.h
/mnt/V8SourceCode/src/objects/objects.cc