v8::base::BoundedPageAllocator Class Reference
#include <bounded-page-allocator.h>
Public Types
enum class AllocationStatus { kSuccess
, kFailedToCommit
, kRanOutOfReservation
, kHintedAddressTakenOrNotFound
 }
using Address = uintptr_t
Public Member Functions
BoundedPageAllocator (v8::PageAllocator *page_allocator, Address start, size_t size, size_t allocate_page_size, PageInitializationMode page_initialization_mode, PageFreeingMode page_freeing_mode)
BoundedPageAllocator (const BoundedPageAllocator &)=delete
BoundedPageAllocator & operator= (const BoundedPageAllocator &)=delete
~BoundedPageAllocator () override=default
Address begin () const
size_t size () const
bool contains (Address address) const
size_t AllocatePageSize () override
Gets the page granularity for AllocatePages and FreePages.
size_t CommitPageSize () override
Gets the page granularity for SetPermissions and ReleasePages.
void SetRandomMmapSeed (int64_t seed) override
Sets the random seed so that GetRandomMmapAddr() will generate repeatable sequences of random mmap addresses.
void * GetRandomMmapAddr () override
Returns a randomized address, suitable for memory allocation under ASLR.
void * AllocatePages (void *hint, size_t size, size_t alignment, Permission access) override
Allocates memory in range with the given alignment and permission.
void * AllocatePages (size_t size, size_t alignment, Permission access, v8::PageAllocator::AllocationHint allocation_hint) override
Allocates memory in range with the given alignment and permission.
bool ReserveForSharedMemoryMapping (void *address, size_t size) override
INTERNAL ONLY: This interface has not been stabilised and may change without notice from one release to another without being deprecated first.
bool AllocatePagesAt (Address address, size_t size, Permission access)
bool ResizeAllocationAt (void *address, size_t old_size, size_t new_size, Permission access) override
Resizes the previously allocated memory at the given address.
bool FreePages (void *address, size_t size) override
Frees memory in a range that was allocated by a call to AllocatePages.
bool ReleasePages (void *address, size_t size, size_t new_size) override
Releases memory in a range that was allocated by a call to AllocatePages.
bool SetPermissions (void *address, size_t size, Permission access) override
Sets permissions on pages in an allocated range.
bool RecommitPages (void *address, size_t size, PageAllocator::Permission access) override
Recommits discarded pages in the given range with given permissions.
bool DiscardSystemPages (void *address, size_t size) override
Frees memory in the given [address, address + size) range.
bool DecommitPages (void *address, size_t size) override
Decommits any wired memory pages in the given range, allowing the OS to reclaim them, and marks the region as inacessible (kNoAccess).
bool SealPages (void *address, size_t size) override
Block any modifications to the given mapping such as changing permissions or unmapping the pages on supported platforms.
AllocationStatus get_last_allocation_status () const
Static Public Member Functions
static const char * AllocationStatusToString (AllocationStatus)
Private Attributes
v8::base::Mutex mutex_
const size_t allocate_page_size_
const size_t commit_page_size_
v8::PageAllocator *const page_allocator_
v8::base::RegionAllocator region_allocator_
const PageInitializationMode page_initialization_mode_
const PageFreeingMode page_freeing_mode_
AllocationStatus allocation_status_ = AllocationStatus::kSuccess
Detailed Description
Definition at line 58 of file bounded-page-allocator.h.
Member Typedef Documentation
Address
using v8::base::BoundedPageAllocator::Address = uintptr_t
Definition at line 67 of file bounded-page-allocator.h.
Member Enumeration Documentation
AllocationStatus
enum v8::base::BoundedPageAllocator::AllocationStatus [strong]
Enumerator
kSuccess
kFailedToCommit
kRanOutOfReservation
kHintedAddressTakenOrNotFound
Definition at line 60 of file bounded-page-allocator.h.
                              {
    kSuccess,
    kFailedToCommit,
    kRanOutOfReservation,
    kHintedAddressTakenOrNotFound,
  };
Constructor & Destructor Documentation
BoundedPageAllocator() [1/2]
v8::base::BoundedPageAllocator::BoundedPageAllocator (v8::PageAllocator * page_allocator, Address start, size_t size, size_t allocate_page_size, PageInitializationMode page_initialization_mode, PageFreeingMode page_freeing_mode)
Definition at line 10 of file bounded-page-allocator.cc.
    : allocate_page_size_(allocate_page_size),
      commit_page_size_(page_allocator->CommitPageSize()),
      page_allocator_(page_allocator),
      region_allocator_(start, size, allocate_page_size_),
      page_initialization_mode_(page_initialization_mode),
      page_freeing_mode_(page_freeing_mode) {
  DCHECK_NOT_NULL(page_allocator);
  DCHECK(IsAligned(allocate_page_size, page_allocator->AllocatePageSize()));
  DCHECK(IsAligned(allocate_page_size_, commit_page_size_));
}
References allocate_page_size_, v8::PageAllocator::AllocatePageSize(), commit_page_size_, DCHECK, DCHECK_NOT_NULL, and IsAligned().
BoundedPageAllocator() [2/2]
v8::base::BoundedPageAllocator::BoundedPageAllocator (const BoundedPageAllocator &) [delete]
 BoundedPageAllocator()
v8::base::BoundedPageAllocator::~BoundedPageAllocator () [override], [default]
Member Function Documentation
AllocatePages() [1/2]
void * v8::base::BoundedPageAllocator::AllocatePages (size_t length, size_t alignment, PageAllocator::Permission permissions, v8::PageAllocator::AllocationHint hint) [override], [virtual]
Allocates memory in range with the given alignment and permission.
In addition to AllocatePages it allows to pass in allocation hints. The underlying implementation may not make use of hints.
Reimplemented from v8::PageAllocator.
Definition at line 38 of file bounded-page-allocator.cc.
                                                                            {
  MutexGuard guard(&mutex_);
  DCHECK(IsAligned(alignment, region_allocator_.page_size()));
  DCHECK(IsAligned(alignment, allocate_page_size_));
  Address address = RegionAllocator::kAllocationFailure;
  Address hint_address = reinterpret_cast<Address>(hint.Address());
  if (hint_address && IsAligned(hint_address, alignment) &&
      region_allocator_.contains(hint_address, size)) {
    if (region_allocator_.AllocateRegionAt(hint_address, size)) {
      address = hint_address;
    }
  }
  const RegionAllocator::AllocationStrategy allocation_strategy =
      hint.MayGrow() ? RegionAllocator::AllocationStrategy::kLargestFit
                     : RegionAllocator::AllocationStrategy::kFirstFit;
  if (address == RegionAllocator::kAllocationFailure) {
    if (alignment <= allocate_page_size_) {
      // TODO(ishell): Consider using randomized version here.
      address = region_allocator_.AllocateRegion(size, allocation_strategy);
    } else {
      address = region_allocator_.AllocateAlignedRegion(size, alignment);
    }
  }
  if (address == RegionAllocator::kAllocationFailure) {
    allocation_status_ = AllocationStatus::kRanOutOfReservation;
    return nullptr;
  }
  void* ptr = reinterpret_cast<void*>(address);
  // It's assumed that free regions are in kNoAccess/kNoAccessWillJitLater
  // state.
  if (access == PageAllocator::kNoAccess ||
      access == PageAllocator::kNoAccessWillJitLater) {
    allocation_status_ = AllocationStatus::kSuccess;
    return ptr;
  }
  if (page_initialization_mode_ == PageInitializationMode::kRecommitOnly) {
    if (page_allocator_->RecommitPages(ptr, size, access)) {
      allocation_status_ = AllocationStatus::kSuccess;
      return ptr;
    }
  } else {
    if (page_allocator_->SetPermissions(ptr, size, access)) {
      allocation_status_ = AllocationStatus::kSuccess;
      return ptr;
    }
  }
  // This most likely means that we ran out of memory.
  CHECK_EQ(region_allocator_.FreeRegion(address), size);
  allocation_status_ = AllocationStatus::kFailedToCommit;
  return nullptr;
}
References v8::PageAllocator::AllocationHint::Address(), allocate_page_size_, v8::base::RegionAllocator::AllocateAlignedRegion(), v8::base::RegionAllocator::AllocateRegion(), v8::base::RegionAllocator::AllocateRegionAt(), allocation_status_, CHECK_EQ, v8::base::RegionAllocator::contains(), DCHECK, v8::base::RegionAllocator::FreeRegion(), IsAligned(), v8::base::RegionAllocator::kAllocationFailure, kFailedToCommit, v8::base::RegionAllocator::kFirstFit, v8::base::RegionAllocator::kLargestFit, v8::PageAllocator::kNoAccess, v8::PageAllocator::kNoAccessWillJitLater, kRanOutOfReservation, v8::base::kRecommitOnly, kSuccess, v8::PageAllocator::AllocationHint::MayGrow(), mutex_, page_allocator_, page_initialization_mode_, v8::base::RegionAllocator::page_size(), v8::PageAllocator::RecommitPages(), region_allocator_, v8::PageAllocator::SetPermissions(), and size().
AllocatePages() [2/2]
void * v8::base::BoundedPageAllocator::AllocatePages (void * address, size_t length, size_t alignment, Permission permissions) [override], [virtual]
Allocates memory in range with the given alignment and permission.
Implements v8::PageAllocator.
Definition at line 31 of file bounded-page-allocator.cc.
                                                                          {
  return AllocatePages(size, alignment, access,
                       v8::PageAllocator::AllocationHint().WithAddress(hint));
}
References size().
Referenced by v8::internal::CodeRange::RemapEmbeddedBuiltins().
AllocatePagesAt()
bool v8::base::BoundedPageAllocator::AllocatePagesAt (Address address, size_t size, PageAllocator::Permission access)
Definition at line 100 of file bounded-page-allocator.cc.
                                                                           {
  MutexGuard guard(&mutex_);
  DCHECK(IsAligned(address, allocate_page_size_));
  DCHECK(IsAligned(size, allocate_page_size_));
  DCHECK(region_allocator_.contains(address, size));
  if (!region_allocator_.AllocateRegionAt(address, size)) {
    allocation_status_ = AllocationStatus::kHintedAddressTakenOrNotFound;
    return false;
  }
  void* ptr = reinterpret_cast<void*>(address);
  if (!page_allocator_->SetPermissions(ptr, size, access)) {
    // This most likely means that we ran out of memory.
    CHECK_EQ(region_allocator_.FreeRegion(address), size);
    allocation_status_ = AllocationStatus::kFailedToCommit;
    return false;
  }
  allocation_status_ = AllocationStatus::kSuccess;
  return true;
}
References allocate_page_size_, v8::base::RegionAllocator::AllocateRegionAt(), allocation_status_, CHECK_EQ, v8::base::RegionAllocator::contains(), DCHECK, v8::base::RegionAllocator::FreeRegion(), IsAligned(), kFailedToCommit, kHintedAddressTakenOrNotFound, kSuccess, mutex_, page_allocator_, region_allocator_, v8::PageAllocator::SetPermissions(), and size().
AllocatePageSize()
size_t v8::base::BoundedPageAllocator::AllocatePageSize () [inline], [override], [virtual]
Gets the page granularity for AllocatePages and FreePages.
Addresses and lengths for those calls should be multiples of AllocatePageSize().
Implements v8::PageAllocator.
Definition at line 89 of file bounded-page-allocator.h.
{ return allocate_page_size_; }
Referenced by v8::internal::CodeRange::InitReservation(), and v8::internal::CodeRange::RemapEmbeddedBuiltins().
AllocationStatusToString()
const char * v8::base::BoundedPageAllocator::AllocationStatusToString (AllocationStatus allocation_status) [static]
Definition at line 319 of file bounded-page-allocator.cc.
                                        {
  switch (allocation_status) {
    case AllocationStatus::kSuccess:
      return "Success";
    case AllocationStatus::kFailedToCommit:
      return "Failed to commit";
    case AllocationStatus::kRanOutOfReservation:
      return "Ran out of reservation";
    case AllocationStatus::kHintedAddressTakenOrNotFound:
      return "Hinted address was taken or not found";
  }
}
References kFailedToCommit, kHintedAddressTakenOrNotFound, kRanOutOfReservation, and kSuccess.
Referenced by cppgc::internal::ObjectAllocator::OutOfLineAllocateImpl().
begin()
BoundedPageAllocator::Address v8::base::BoundedPageAllocator::begin () const
Definition at line 25 of file bounded-page-allocator.cc.
                                                              {
  return region_allocator_.begin();
}
References v8::base::RegionAllocator::begin(), and region_allocator_.
CommitPageSize()
size_t v8::base::BoundedPageAllocator::CommitPageSize () [inline], [override], [virtual]
Gets the page granularity for SetPermissions and ReleasePages.
Addresses and lengths for those calls should be multiples of CommitPageSize().
Implements v8::PageAllocator.
Definition at line 91 of file bounded-page-allocator.h.
{ return commit_page_size_; }
Referenced by v8::internal::CodeRange::RemapEmbeddedBuiltins().
contains()
bool v8::base::BoundedPageAllocator::contains (Address address) const [inline]
Definition at line 85 of file bounded-page-allocator.h.
                                       {
    return region_allocator_.contains(address);
  }
DecommitPages()
bool v8::base::BoundedPageAllocator::DecommitPages (void * address, size_t size) [override], [virtual]
Decommits any wired memory pages in the given range, allowing the OS to reclaim them, and marks the region as inacessible (kNoAccess).
The address range stays reserved and can be accessed again later by changing its permissions. However, in that case the memory content is guaranteed to be zero-initialized again. The memory must have been previously allocated by a call to AllocatePages. Returns true on success, false otherwise.
Implements v8::PageAllocator.
Definition at line 311 of file bounded-page-allocator.cc.
                                                                   {
  return page_allocator_->DecommitPages(address, size);
}
References v8::PageAllocator::DecommitPages(), page_allocator_, and size().
DiscardSystemPages()
bool v8::base::BoundedPageAllocator::DiscardSystemPages (void * address, size_t size) [override], [virtual]
Frees memory in the given [address, address + size) range.
address and size should be operating system page-aligned. The next write to this memory area brings the memory transparently back. This should be treated as a hint to the OS that the pages are no longer needed. It does not guarantee that the pages will be discarded immediately or at all.
Reimplemented from v8::PageAllocator.
Definition at line 307 of file bounded-page-allocator.cc.
                                                                        {
  return page_allocator_->DiscardSystemPages(address, size);
}
References v8::PageAllocator::DiscardSystemPages(), page_allocator_, and size().
FreePages()
bool v8::base::BoundedPageAllocator::FreePages (void * address, size_t length) [override], [virtual]
Frees memory in a range that was allocated by a call to AllocatePages.
Implements v8::PageAllocator.
Definition at line 201 of file bounded-page-allocator.cc.
                                                                   {
  // Careful: we are not locked here, do not touch BoundedPageAllocator
  // metadata.
  bool success;
  Address address = reinterpret_cast<Address>(raw_address);
  // The operations below can be expensive, don't hold the lock while they
  // happen. There is still potentially contention in the kernel, but at least
  // we don't need to hold the V8-side lock.
  if (page_initialization_mode_ ==
      PageInitializationMode::kAllocatedPagesMustBeZeroInitialized) {
    DCHECK_NE(page_freeing_mode_, PageFreeingMode::kDiscard);
    // When we are required to return zero-initialized pages, we decommit the
    // pages here, which will cause any wired pages to be removed by the OS.
    success = page_allocator_->DecommitPages(raw_address, size);
  } else {
    switch (page_freeing_mode_) {
      case PageFreeingMode::kMakeInaccessible:
        DCHECK_EQ(page_initialization_mode_,
                  PageInitializationMode::kAllocatedPagesCanBeUninitialized);
        success = page_allocator_->SetPermissions(raw_address, size,
                                                  PageAllocator::kNoAccess);
        break;
      case PageFreeingMode::kDiscard:
        success = page_allocator_->DiscardSystemPages(raw_address, size);
        break;
    }
  }
  MutexGuard guard(&mutex_);
  CHECK_EQ(size, region_allocator_.FreeRegion(address));
  return success;
}
References CHECK_EQ, DCHECK_EQ, DCHECK_NE, v8::PageAllocator::DecommitPages(), v8::PageAllocator::DiscardSystemPages(), v8::base::RegionAllocator::FreeRegion(), v8::base::kAllocatedPagesCanBeUninitialized, v8::base::kAllocatedPagesMustBeZeroInitialized, v8::base::kDiscard, v8::base::kMakeInaccessible, v8::PageAllocator::kNoAccess, mutex_, page_allocator_, page_freeing_mode_, page_initialization_mode_, region_allocator_, v8::PageAllocator::SetPermissions(), and size().
get_last_allocation_status()
AllocationStatus v8::base::BoundedPageAllocator::get_last_allocation_status () const [inline]
Definition at line 131 of file bounded-page-allocator.h.
                                                      {
    return allocation_status_;
  }
Referenced by cppgc::internal::ObjectAllocator::OutOfLineAllocateImpl().
GetRandomMmapAddr()
void* v8::base::BoundedPageAllocator::GetRandomMmapAddr () [inline], [override], [virtual]
Returns a randomized address, suitable for memory allocation under ASLR.
The address will be aligned to AllocatePageSize.
Implements v8::PageAllocator.
Definition at line 97 of file bounded-page-allocator.h.
                                     {
    return page_allocator_->GetRandomMmapAddr();
  }
operator=()
BoundedPageAllocator& v8::base::BoundedPageAllocator::operator= (const BoundedPageAllocator &) [delete]
RecommitPages()
bool v8::base::BoundedPageAllocator::RecommitPages (void * address, size_t length, PageAllocator::Permission permissions) [override], [virtual]
Recommits discarded pages in the given range with given permissions.
Discarded pages must be recommitted with their original permissions before they are used again.
Reimplemented from v8::PageAllocator.
Definition at line 295 of file bounded-page-allocator.cc.
                                                                         {
  DCHECK(IsAligned(reinterpret_cast<Address>(address), commit_page_size_));
  DCHECK(IsAligned(size, commit_page_size_));
  DCHECK(region_allocator_.contains(reinterpret_cast<Address>(address), size));
  const bool success = page_allocator_->RecommitPages(address, size, access);
  if (!success) {
    allocation_status_ = AllocationStatus::kFailedToCommit;
  }
  return success;
}
References allocation_status_, commit_page_size_, v8::base::RegionAllocator::contains(), DCHECK, IsAligned(), kFailedToCommit, page_allocator_, v8::PageAllocator::RecommitPages(), region_allocator_, and size().
ReleasePages()
bool v8::base::BoundedPageAllocator::ReleasePages (void * address, size_t length, size_t new_length) [override], [virtual]
Releases memory in a range that was allocated by a call to AllocatePages.
Implements v8::PageAllocator.
Definition at line 237 of file bounded-page-allocator.cc.
                                                         {
  Address address = reinterpret_cast<Address>(raw_address);
  DCHECK(IsAligned(address, allocate_page_size_));
  DCHECK_LT(new_size, size);
  DCHECK(IsAligned(size - new_size, commit_page_size_));
  // This must be held until the page permissions are updated.
  MutexGuard guard(&mutex_);
  // Check if we freed any allocatable pages by this release.
  size_t allocated_size = RoundUp(size, allocate_page_size_);
  size_t new_allocated_size = RoundUp(new_size, allocate_page_size_);
#ifdef DEBUG
  {
    // There must be an allocated region at given |address| of a size not
    // smaller than |size|.
    DCHECK_EQ(allocated_size, region_allocator_.CheckRegion(address));
  }
#endif
  if (new_allocated_size < allocated_size) {
    region_allocator_.TrimRegion(address, new_allocated_size);
  }
  // Keep the region in "used" state just uncommit some pages.
  void* free_address = reinterpret_cast<void*>(address + new_size);
  size_t free_size = size - new_size;
  if (page_initialization_mode_ ==
      PageInitializationMode::kAllocatedPagesMustBeZeroInitialized) {
    DCHECK_NE(page_freeing_mode_, PageFreeingMode::kDiscard);
    // See comment in FreePages().
    return (page_allocator_->DecommitPages(free_address, free_size));
  }
  if (page_freeing_mode_ == PageFreeingMode::kMakeInaccessible) {
    DCHECK_EQ(page_initialization_mode_,
              PageInitializationMode::kAllocatedPagesCanBeUninitialized);
    return page_allocator_->SetPermissions(free_address, free_size,
                                           PageAllocator::kNoAccess);
  }
  CHECK_EQ(page_freeing_mode_, PageFreeingMode::kDiscard);
  return page_allocator_->DiscardSystemPages(free_address, free_size);
}
References allocate_page_size_, CHECK_EQ, v8::base::RegionAllocator::CheckRegion(), commit_page_size_, DCHECK, DCHECK_EQ, DCHECK_LT, DCHECK_NE, v8::PageAllocator::DecommitPages(), v8::PageAllocator::DiscardSystemPages(), IsAligned(), v8::base::kAllocatedPagesCanBeUninitialized, v8::base::kAllocatedPagesMustBeZeroInitialized, v8::base::kDiscard, v8::base::kMakeInaccessible, v8::PageAllocator::kNoAccess, mutex_, page_allocator_, page_freeing_mode_, page_initialization_mode_, region_allocator_, RoundUp(), v8::PageAllocator::SetPermissions(), size(), and v8::base::RegionAllocator::TrimRegion().
ReserveForSharedMemoryMapping()
bool v8::base::BoundedPageAllocator::ReserveForSharedMemoryMapping (void * address, size_t size) [override], [virtual]
INTERNAL ONLY: This interface has not been stabilised and may change without notice from one release to another without being deprecated first.
Reserve pages at a fixed address returning whether the reservation is possible. The reserved memory is detached from the PageAllocator and so should not be freed by it. It's intended for use with SharedMemory::RemapTo, where ~SharedMemoryMapping would free the memory.
Reimplemented from v8::PageAllocator.
Definition at line 172 of file bounded-page-allocator.cc.
                                                                      {
  MutexGuard guard(&mutex_);
  Address address = reinterpret_cast<Address>(ptr);
  DCHECK(IsAligned(address, allocate_page_size_));
  DCHECK(IsAligned(size, commit_page_size_));
  DCHECK(region_allocator_.contains(address, size));
  // Region allocator requires page size rather than commit size so just over-
  // allocate there since any extra space couldn't be used anyway.
  size_t region_size = RoundUp(size, allocate_page_size_);
  if (!region_allocator_.AllocateRegionAt(
          address, region_size, RegionAllocator::RegionState::kExcluded)) {
    allocation_status_ = AllocationStatus::kHintedAddressTakenOrNotFound;
    return false;
  }
  const bool success = page_allocator_->SetPermissions(
      ptr, size, PageAllocator::Permission::kNoAccess);
  if (success) {
    allocation_status_ = AllocationStatus::kSuccess;
  } else {
    allocation_status_ = AllocationStatus::kFailedToCommit;
  }
  return success;
}
References allocate_page_size_, v8::base::RegionAllocator::AllocateRegionAt(), allocation_status_, commit_page_size_, v8::base::RegionAllocator::contains(), DCHECK, IsAligned(), v8::base::RegionAllocator::kExcluded, kFailedToCommit, kHintedAddressTakenOrNotFound, kSuccess, mutex_, page_allocator_, region_allocator_, RoundUp(), v8::PageAllocator::SetPermissions(), and size().
ResizeAllocationAt()
bool v8::base::BoundedPageAllocator::ResizeAllocationAt (void * address, size_t old_length, size_t new_length, PageAllocator::Permission permissions) [override], [virtual]
Resizes the previously allocated memory at the given address.
Returns true if the allocation could be resized. Returns false if this operation is either not supported or the object could not be resized in-place.
Reimplemented from v8::PageAllocator.
Definition at line 126 of file bounded-page-allocator.cc.
                                    {
  MutexGuard guard(&mutex_);
  const Address address_at = reinterpret_cast<Address>(address);
  DCHECK(IsAligned(old_size, commit_page_size_));
  DCHECK(IsAligned(new_size, commit_page_size_));
  if (new_size < old_size) {
    // Shrinking is not supported at the moment.
    return false;
  } else if (new_size == old_size) {
    // Nothing to do in this case.
    return true;
  }
  DCHECK_LT(old_size, new_size);
  const Address allocated_old_size = RoundUp(old_size, allocate_page_size_);
  const Address allocated_new_size = RoundUp(new_size, allocate_page_size_);
  if (allocated_old_size < allocated_new_size) {
    if (!region_allocator_.TryGrowRegion(address_at, allocated_new_size)) {
      allocation_status_ = AllocationStatus::kHintedAddressTakenOrNotFound;
      return false;
    }
  }
  if (!page_allocator_->SetPermissions(
          reinterpret_cast<void*>(address_at + old_size), new_size - old_size,
          access)) {
    if (allocated_old_size < allocated_new_size) {
      // This most likely means that we ran out of memory.
      CHECK_EQ(region_allocator_.TrimRegion(address_at, allocated_old_size),
               allocated_new_size - allocated_old_size);
    }
    allocation_status_ = AllocationStatus::kFailedToCommit;
    return false;
  }
  allocation_status_ = AllocationStatus::kSuccess;
  return true;
}
References allocate_page_size_, allocation_status_, CHECK_EQ, commit_page_size_, DCHECK, DCHECK_LT, IsAligned(), kFailedToCommit, kHintedAddressTakenOrNotFound, kSuccess, mutex_, page_allocator_, region_allocator_, RoundUp(), v8::PageAllocator::SetPermissions(), v8::base::RegionAllocator::TrimRegion(), and v8::base::RegionAllocator::TryGrowRegion().
SealPages()
bool v8::base::BoundedPageAllocator::SealPages (void * address, size_t length) [override], [virtual]
Block any modifications to the given mapping such as changing permissions or unmapping the pages on supported platforms.
The address space reservation will exist until the process ends, but it's possible to release the memory using DiscardSystemPages. Note that this might require write permissions to the page as e.g. on Linux, mseal will block discarding sealed anonymous memory.
Reimplemented from v8::PageAllocator.
Definition at line 315 of file bounded-page-allocator.cc.
                                                               {
  return page_allocator_->SealPages(address, size);
}
References page_allocator_, v8::PageAllocator::SealPages(), and size().
SetPermissions()
bool v8::base::BoundedPageAllocator::SetPermissions (void * address, size_t length, Permission permissions) [override], [virtual]
Sets permissions on pages in an allocated range.
Implements v8::PageAllocator.
Definition at line 283 of file bounded-page-allocator.cc.
                                                                          {
  DCHECK(IsAligned(reinterpret_cast<Address>(address), commit_page_size_));
  DCHECK(IsAligned(size, commit_page_size_));
  DCHECK(region_allocator_.contains(reinterpret_cast<Address>(address), size));
  const bool success = page_allocator_->SetPermissions(address, size, access);
  if (!success) {
    allocation_status_ = AllocationStatus::kFailedToCommit;
  }
  return success;
}
References allocation_status_, commit_page_size_, v8::base::RegionAllocator::contains(), DCHECK, IsAligned(), kFailedToCommit, page_allocator_, region_allocator_, v8::PageAllocator::SetPermissions(), and size().
SetRandomMmapSeed()
void v8::base::BoundedPageAllocator::SetRandomMmapSeed (int64_t seed) [inline], [override], [virtual]
Sets the random seed so that GetRandomMmapAddr() will generate repeatable sequences of random mmap addresses.
Implements v8::PageAllocator.
Definition at line 93 of file bounded-page-allocator.h.
                                                {
    page_allocator_->SetRandomMmapSeed(seed);
  }
size()
size_t v8::base::BoundedPageAllocator::size () const
Definition at line 29 of file bounded-page-allocator.cc.
{ return region_allocator_.size(); }
References region_allocator_, and v8::base::RegionAllocator::size().
Referenced by AllocatePages(), AllocatePagesAt(), DecommitPages(), DiscardSystemPages(), FreePages(), RecommitPages(), ReleasePages(), ReserveForSharedMemoryMapping(), SealPages(), and SetPermissions().
Member Data Documentation
allocate_page_size_
const size_t v8::base::BoundedPageAllocator::allocate_page_size_ [private]
Definition at line 137 of file bounded-page-allocator.h.
Referenced by AllocatePages(), AllocatePagesAt(), BoundedPageAllocator(), ReleasePages(), ReserveForSharedMemoryMapping(), and ResizeAllocationAt().
allocation_status_
AllocationStatus v8::base::BoundedPageAllocator::allocation_status_ = AllocationStatus::kSuccess [private]
Definition at line 143 of file bounded-page-allocator.h.
Referenced by AllocatePages(), AllocatePagesAt(), RecommitPages(), ReserveForSharedMemoryMapping(), ResizeAllocationAt(), and SetPermissions().
commit_page_size_
const size_t v8::base::BoundedPageAllocator::commit_page_size_ [private]
Definition at line 138 of file bounded-page-allocator.h.
Referenced by BoundedPageAllocator(), RecommitPages(), ReleasePages(), ReserveForSharedMemoryMapping(), ResizeAllocationAt(), and SetPermissions().
mutex_
v8::base::Mutex v8::base::BoundedPageAllocator::mutex_ [private]
Definition at line 136 of file bounded-page-allocator.h.
Referenced by AllocatePages(), AllocatePagesAt(), FreePages(), ReleasePages(), ReserveForSharedMemoryMapping(), and ResizeAllocationAt().
page_allocator_
v8::PageAllocator* const v8::base::BoundedPageAllocator::page_allocator_ [private]
Definition at line 139 of file bounded-page-allocator.h.
Referenced by AllocatePages(), AllocatePagesAt(), DecommitPages(), DiscardSystemPages(), FreePages(), RecommitPages(), ReleasePages(), ReserveForSharedMemoryMapping(), ResizeAllocationAt(), SealPages(), and SetPermissions().
page_freeing_mode_
const PageFreeingMode v8::base::BoundedPageAllocator::page_freeing_mode_ [private]
Definition at line 142 of file bounded-page-allocator.h.
Referenced by FreePages(), and ReleasePages().
page_initialization_mode_
const PageInitializationMode v8::base::BoundedPageAllocator::page_initialization_mode_ [private]
Definition at line 141 of file bounded-page-allocator.h.
Referenced by AllocatePages(), FreePages(), and ReleasePages().
region_allocator_
v8::base::RegionAllocator v8::base::BoundedPageAllocator::region_allocator_ [private]
Definition at line 140 of file bounded-page-allocator.h.
Referenced by AllocatePages(), AllocatePagesAt(), begin(), FreePages(), RecommitPages(), ReleasePages(), ReserveForSharedMemoryMapping(), ResizeAllocationAt(), SetPermissions(), and size().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/base/bounded-page-allocator.h
/mnt/V8SourceCode/src/base/bounded-page-allocator.cc