v8::internal::wasm::CWasmArgumentsPacker Class Reference
#include <wasm-arguments.h>
Public Member Functions
CWasmArgumentsPacker (size_t buffer_size)
i::Address argv () const
void Reset ()
template<typename T >
void Push (T val)
template<typename T >
T Pop ()
Static Public Member Functions
static int TotalSize (const CanonicalSig *sig)
Private Attributes
uint8_t on_stack_buffer_ [kMaxOnStackBuffer]
std::vector< uint8_t > heap_buffer_
uint8_t * buffer_
size_t offset_ = 0
Static Private Attributes
static const size_t kMaxOnStackBuffer = 10 * i::kSystemPointerSize
Detailed Description
Definition at line 29 of file wasm-arguments.h.
Constructor & Destructor Documentation
CWasmArgumentsPacker()
v8::internal::wasm::CWasmArgumentsPacker::CWasmArgumentsPacker (size_t buffer_size) [inline], [explicit]
Definition at line 31 of file wasm-arguments.h.
      : heap_buffer_(buffer_size <= kMaxOnStackBuffer ? 0 : buffer_size),
        buffer_((buffer_size <= kMaxOnStackBuffer) ? on_stack_buffer_
                                                   : heap_buffer_.data()) {}
Member Function Documentation
argv()
i::Address v8::internal::wasm::CWasmArgumentsPacker::argv () const [inline]
Definition at line 35 of file wasm-arguments.h.
{ return reinterpret_cast<i::Address>(buffer_); }
References buffer_.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::CallExternalJSFunction().
Pop()
template<typename T >
T v8::internal::wasm::CWasmArgumentsPacker::Pop () [inline]
Definition at line 46 of file wasm-arguments.h.
          {
    Address address = reinterpret_cast<Address>(buffer_ + offset_);
    offset_ += sizeof(T);
    return base::ReadUnalignedValue<T>(address);
  }
References buffer_, offset_, and T.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::CallExternalJSFunction().
Push()
template<typename T >
void v8::internal::wasm::CWasmArgumentsPacker::Push (T val) [inline]
Definition at line 39 of file wasm-arguments.h.
                   {
    Address address = reinterpret_cast<Address>(buffer_ + offset_);
    offset_ += sizeof(val);
    base::WriteUnalignedValue(address, val);
  }
References buffer_, offset_, and v8::base::WriteUnalignedValue().
Referenced by v8::internal::wasm::WasmInterpreterRuntime::CallExternalJSFunction().
Reset()
void v8::internal::wasm::CWasmArgumentsPacker::Reset () [inline]
Definition at line 36 of file wasm-arguments.h.
{ offset_ = 0; }
References offset_.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::CallExternalJSFunction().
TotalSize()
static int v8::internal::wasm::CWasmArgumentsPacker::TotalSize (const CanonicalSig * sig) [inline], [static]
Definition at line 52 of file wasm-arguments.h.
                                                {
    int return_size = 0;
    for (CanonicalValueType t : sig->returns()) {
      return_size += t.value_kind_full_size();
    }
    int param_size = 0;
    for (CanonicalValueType t : sig->parameters()) {
      param_size += t.value_kind_full_size();
    }
    return std::max(return_size, param_size);
  }
References v8::internal::sig.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::CallExternalJSFunction().
Member Data Documentation
buffer_
uint8_t* v8::internal::wasm::CWasmArgumentsPacker::buffer_ [private]
Definition at line 69 of file wasm-arguments.h.
Referenced by argv(), Pop(), and Push().
heap_buffer_
std::vector<uint8_t> v8::internal::wasm::CWasmArgumentsPacker::heap_buffer_ [private]
Definition at line 68 of file wasm-arguments.h.
kMaxOnStackBuffer
const size_t v8::internal::wasm::CWasmArgumentsPacker::kMaxOnStackBuffer = 10 * i::kSystemPointerSize [static], [private]
Definition at line 65 of file wasm-arguments.h.
offset_
size_t v8::internal::wasm::CWasmArgumentsPacker::offset_ = 0 [private]
Definition at line 70 of file wasm-arguments.h.
Referenced by Pop(), Push(), and Reset().
on_stack_buffer_
uint8_t v8::internal::wasm::CWasmArgumentsPacker::on_stack_buffer_[kMaxOnStackBuffer] [private]
Definition at line 67 of file wasm-arguments.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/wasm-arguments.h