v8::internal::FrameAndConstantPoolScope Class Reference
#include <macro-assembler.h>
Public Member Functions
FrameAndConstantPoolScope (MacroAssembler *masm, StackFrame::Type type)
~FrameAndConstantPoolScope ()
Private Member Functions
DISALLOW_IMPLICIT_CONSTRUCTORS (FrameAndConstantPoolScope)
Private Attributes
MacroAssembler * masm_
StackFrame::Type type_
bool old_has_frame_
bool old_constant_pool_available_
Detailed Description
Definition at line 151 of file macro-assembler.h.
Constructor & Destructor Documentation
FrameAndConstantPoolScope()
v8::internal::FrameAndConstantPoolScope::FrameAndConstantPoolScope (MacroAssembler * masm, StackFrame::Type type) [inline]
Definition at line 153 of file macro-assembler.h.
      : masm_(masm),
        type_(type),
        old_has_frame_(masm->has_frame()),
        old_constant_pool_available_(V8_EMBEDDED_CONSTANT_POOL_BOOL &&
                                     masm->is_constant_pool_available()) {
    masm->set_has_frame(true);
    if (V8_EMBEDDED_CONSTANT_POOL_BOOL) {
      masm->set_constant_pool_available(true);
    }
    if (type_ != StackFrame::MANUAL && type_ != StackFrame::NO_FRAME_TYPE) {
      masm->EnterFrame(type, !old_constant_pool_available_);
    }
  }
References v8::internal::MacroAssembler::EnterFrame(), v8::internal::StackFrame::MANUAL, v8::internal::StackFrame::NO_FRAME_TYPE, v8::internal::AssemblerBase::set_constant_pool_available(), v8::internal::MacroAssemblerBase::set_has_frame(), v8::internal::tracing::type, and V8_EMBEDDED_CONSTANT_POOL_BOOL.
 FrameAndConstantPoolScope()
v8::internal::FrameAndConstantPoolScope::~FrameAndConstantPoolScope () [inline]
Definition at line 168 of file macro-assembler.h.
                               {
    masm_->LeaveFrame(type_);
    masm_->set_has_frame(old_has_frame_);
    if (V8_EMBEDDED_CONSTANT_POOL_BOOL) {
      masm_->set_constant_pool_available(old_constant_pool_available_);
    }
  }
References V8_EMBEDDED_CONSTANT_POOL_BOOL.
Member Function Documentation
DISALLOW_IMPLICIT_CONSTRUCTORS()
v8::internal::FrameAndConstantPoolScope::DISALLOW_IMPLICIT_CONSTRUCTORS (FrameAndConstantPoolScope) [private]
Member Data Documentation
masm_
MacroAssembler* v8::internal::FrameAndConstantPoolScope::masm_ [private]
Definition at line 177 of file macro-assembler.h.
old_constant_pool_available_
bool v8::internal::FrameAndConstantPoolScope::old_constant_pool_available_ [private]
Definition at line 180 of file macro-assembler.h.
old_has_frame_
bool v8::internal::FrameAndConstantPoolScope::old_has_frame_ [private]
Definition at line 179 of file macro-assembler.h.
type_
StackFrame::Type v8::internal::FrameAndConstantPoolScope::type_ [private]
Definition at line 178 of file macro-assembler.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/codegen/macro-assembler.h