v8::internal::IterationStatementSourceRanges Class Reference
#include <ast-source-ranges.h>
Public Member Functions
IterationStatementSourceRanges (const SourceRange &body_range)
SourceRange GetRange (SourceRangeKind kind) override
bool HasRange (SourceRangeKind kind) override
void RemoveContinuationRange () override
Private Attributes
SourceRange body_range_
bool has_continuation_ = true
Detailed Description
Definition at line 258 of file ast-source-ranges.h.
Constructor & Destructor Documentation
IterationStatementSourceRanges()
v8::internal::IterationStatementSourceRanges::IterationStatementSourceRanges (const SourceRange & body_range) [inline], [explicit]
Definition at line 260 of file ast-source-ranges.h.
      : body_range_(body_range) {}
Member Function Documentation
GetRange()
SourceRange v8::internal::IterationStatementSourceRanges::GetRange (SourceRangeKind kind) [inline], [override], [virtual]
Implements v8::internal::AstNodeSourceRanges.
Definition at line 263 of file ast-source-ranges.h.
                                                      {
    DCHECK(HasRange(kind));
    switch (kind) {
      case SourceRangeKind::kBody:
        return body_range_;
      case SourceRangeKind::kContinuation:
        if (!has_continuation_) return SourceRange::Empty();
        return SourceRange::ContinuationOf(body_range_);
      default:
        UNREACHABLE();
    }
  }
References body_range_, v8::internal::SourceRange::ContinuationOf(), v8::internal::DCHECK(), v8::internal::SourceRange::Empty(), has_continuation_, HasRange(), v8::internal::kBody, v8::internal::kContinuation, and v8::internal::UNREACHABLE().
HasRange()
bool v8::internal::IterationStatementSourceRanges::HasRange (SourceRangeKind kind) [inline], [override], [virtual]
Implements v8::internal::AstNodeSourceRanges.
Definition at line 276 of file ast-source-ranges.h.
                                               {
    return kind == SourceRangeKind::kBody ||
           kind == SourceRangeKind::kContinuation;
  }
References v8::internal::kBody, and v8::internal::kContinuation.
Referenced by GetRange(), and RemoveContinuationRange().
RemoveContinuationRange()
void v8::internal::IterationStatementSourceRanges::RemoveContinuationRange () [inline], [override], [virtual]
Reimplemented from v8::internal::AstNodeSourceRanges.
Definition at line 281 of file ast-source-ranges.h.
                                          {
    DCHECK(HasRange(SourceRangeKind::kContinuation));
    has_continuation_ = false;
  }
References v8::internal::DCHECK(), has_continuation_, HasRange(), and v8::internal::kContinuation.
Member Data Documentation
body_range_
SourceRange v8::internal::IterationStatementSourceRanges::body_range_ [private]
Definition at line 287 of file ast-source-ranges.h.
Referenced by GetRange().
has_continuation_
bool v8::internal::IterationStatementSourceRanges::has_continuation_ = true [private]
Definition at line 288 of file ast-source-ranges.h.
Referenced by GetRange(), and RemoveContinuationRange().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ast/ast-source-ranges.h