v8::internal::wasm::LiftoffRegister Class Reference
#include <liftoff-register.h>
Public Member Functions
constexpr LiftoffRegister (Register reg)
constexpr LiftoffRegister (DoubleRegister reg)
constexpr bool is_pair () const
constexpr bool is_gp_pair () const
constexpr bool is_fp_pair () const
constexpr bool is_gp () const
constexpr bool is_fp () const
LiftoffRegister low () const
LiftoffRegister high () const
Register low_gp () const
Register high_gp () const
DoubleRegister low_fp () const
DoubleRegister high_fp () const
constexpr Register gp () const
constexpr DoubleRegister fp () const
constexpr int liftoff_code () const
constexpr RegClass reg_class () const
bool operator== (const LiftoffRegister other) const
bool overlaps (const LiftoffRegister other) const
Static Public Member Functions
static LiftoffRegister from_liftoff_code (int code)
static LiftoffRegister from_code (RegClass rc, int code)
static LiftoffRegister from_external_code (RegClass rc, ValueKind kind, int code)
static LiftoffRegister ForPair (Register low, Register high)
static LiftoffRegister ForFpPair (DoubleRegister low)
Private Types
using storage_t = std::conditional_t< needed_bits<=8, uint8_t, std::conditional_t< needed_bits<=16, uint16_t, uint32_t > >
Private Member Functions
constexpr LiftoffRegister (storage_t code)
Private Attributes
storage_t code_
Static Private Attributes
static constexpr int needed_bits
Detailed Description
Definition at line 143 of file liftoff-register.h.
Member Typedef Documentation
storage_t
using v8::internal::wasm::LiftoffRegister::storage_t = std::conditional_t< needed_bits <= 8, uint8_t, std::conditional_t<needed_bits <= 16, uint16_t, uint32_t> > [private]
Definition at line 147 of file liftoff-register.h.
Constructor & Destructor Documentation
LiftoffRegister() [1/3]
constexpr v8::internal::wasm::LiftoffRegister::LiftoffRegister (Register reg) [inline], [explicit], [constexpr]
Definition at line 160 of file liftoff-register.h.
      : LiftoffRegister(reg.code()) {
    DCHECK(kLiftoffAssemblerGpCacheRegs.has(reg));
    DCHECK_EQ(reg, gp());
  }
References v8::internal::DCHECK(), DCHECK_EQ, gp(), v8::internal::RegListBase< RegisterT >::has(), and v8::internal::wasm::kLiftoffAssemblerGpCacheRegs.
Referenced by ForFpPair(), ForPair(), from_code(), high(), and low().
LiftoffRegister() [2/3]
constexpr v8::internal::wasm::LiftoffRegister::LiftoffRegister (DoubleRegister reg) [inline], [explicit], [constexpr]
Definition at line 165 of file liftoff-register.h.
      : LiftoffRegister(kAfterMaxLiftoffGpRegCode + reg.code()) {
    DCHECK(kLiftoffAssemblerFpCacheRegs.has(reg));
    DCHECK_EQ(reg, fp());
  }
References v8::internal::DCHECK(), DCHECK_EQ, fp(), v8::internal::RegListBase< RegisterT >::has(), and v8::internal::wasm::kLiftoffAssemblerFpCacheRegs.
LiftoffRegister() [3/3]
constexpr v8::internal::wasm::LiftoffRegister::LiftoffRegister (storage_t code) [inline], [explicit], [constexpr], [private]
Definition at line 326 of file liftoff-register.h.
: code_(code) {}
Member Function Documentation
ForFpPair()
static LiftoffRegister v8::internal::wasm::LiftoffRegister::ForFpPair (DoubleRegister low) [inline], [static]
Definition at line 233 of file liftoff-register.h.
                                                       {
    DCHECK(kNeedS128RegPair);
    DCHECK_EQ(0, low.code() % 2);
    storage_t combined_code = low.code() | 2 << (2 * kBitsPerGpRegCode);
    return LiftoffRegister(combined_code);
  }
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::wasm::kBitsPerGpRegCode, v8::internal::wasm::kNeedS128RegPair, LiftoffRegister(), and low().
Referenced by v8::internal::wasm::ParallelMove::ExecuteLoads(), from_external_code(), from_liftoff_code(), v8::internal::wasm::LiftoffAssembler::GetUnusedRegister(), and v8::internal::wasm::LiftoffAssembler::MoveToReturnLocations().
ForPair()
static LiftoffRegister v8::internal::wasm::LiftoffRegister::ForPair (Register low, Register high) [inline], [static]
Definition at line 225 of file liftoff-register.h.
                                                              {
    DCHECK(kNeedI64RegPair);
    DCHECK_NE(low, high);
    storage_t combined_code = low.code() | (high.code() << kBitsPerGpRegCode) |
                              (1 << (2 * kBitsPerGpRegCode));
    return LiftoffRegister(combined_code);
  }
References v8::internal::DCHECK(), DCHECK_NE, high(), v8::internal::wasm::kBitsPerGpRegCode, v8::internal::wasm::kNeedI64RegPair, LiftoffRegister(), and low().
Referenced by v8::internal::wasm::liftoff::AtomicBinop64(), v8::internal::wasm::liftoff::AtomicI64CompareExchange(), v8::internal::wasm::LiftoffAssembler::AtomicLoad(), v8::internal::wasm::liftoff::AtomicOp64(), v8::internal::wasm::LiftoffAssembler::CallC(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CurrentMemoryPages(), v8::internal::wasm::LiftoffAssembler::FinishCall(), from_liftoff_code(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GenerateCCall(), v8::internal::wasm::LiftoffAssembler::GetUnusedRegister(), v8::internal::wasm::LiftoffAssembler::MoveToReturnLocations(), v8::internal::wasm::liftoff::OpWithCarry(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ParameterProcessor::Process(), v8::internal::wasm::liftoff::ReplaceInPair(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TableGrow(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TableSize().
fp()
constexpr DoubleRegister v8::internal::wasm::LiftoffRegister::fp () const [inline], [constexpr]
Definition at line 299 of file liftoff-register.h.
                                      {
    DCHECK(is_fp());
    return DoubleRegister::from_code(code_ - kAfterMaxLiftoffGpRegCode);
  }
References code_, v8::internal::DCHECK(), v8::internal::RegisterBase< DoubleRegister, kDoubleAfterLast >::from_code(), is_fp(), and v8::internal::wasm::kAfterMaxLiftoffGpRegCode.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CheckNan(), v8::internal::wasm::LiftoffStackSlots::Construct(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_extract_lane(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_replace_lane(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_splat(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_extract_lane(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_replace_lane(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_splat(), v8::internal::wasm::LiftoffAssembler::emit_type_conversion(), v8::internal::wasm::liftoff::EmitAllTrue(), v8::internal::wasm::liftoff::EmitSimdCommutativeBinOp(), v8::internal::wasm::liftoff::EmitSimdNonCommutativeBinOp(), v8::internal::wasm::liftoff::EmitSimdShiftOp(), v8::internal::wasm::liftoff::EmitSimdShiftOpImm(), v8::internal::wasm::F16x8BinOpViaF32(), v8::internal::wasm::F16x8CmpOpViaF32(), v8::internal::wasm::LiftoffVarState::fp_reg(), v8::internal::wasm::liftoff::GetRegFromType(), v8::internal::wasm::LiftoffAssembler::GetUnusedRegister(), LiftoffRegister(), v8::internal::wasm::liftoff::Load(), v8::internal::wasm::LiftoffAssembler::LoadConstant(), v8::internal::wasm::liftoff::LoadFromStack(), v8::internal::wasm::liftoff::LoadInternal(), v8::internal::wasm::LiftoffAssembler::Move(), v8::internal::wasm::operator<<(), v8::internal::wasm::LiftoffAssembler::PopRegisters(), v8::internal::wasm::liftoff::push(), v8::internal::wasm::LiftoffAssembler::PushRegisters(), v8::internal::wasm::LiftoffAssembler::SpillAdjacentFpRegisters(), v8::internal::wasm::liftoff::Store(), v8::internal::wasm::LiftoffAssembler::Store(), and v8::internal::wasm::liftoff::StoreToMemory().
from_code()
static LiftoffRegister v8::internal::wasm::LiftoffRegister::from_code (RegClass rc, int code) [inline], [static]
Definition at line 194 of file liftoff-register.h.
                                                          {
    switch (rc) {
      case kGpReg:
        return LiftoffRegister(Register::from_code(code));
      case kFpReg:
        return LiftoffRegister(DoubleRegister::from_code(code));
      default:
        UNREACHABLE();
    }
  }
References code, v8::internal::Register::from_code(), v8::internal::RegisterBase< DoubleRegister, kDoubleAfterLast >::from_code(), v8::internal::wasm::kFpReg, v8::internal::wasm::kGpReg, LiftoffRegister(), and v8::internal::UNREACHABLE().
Referenced by from_external_code().
from_external_code()
static LiftoffRegister v8::internal::wasm::LiftoffRegister::from_external_code (RegClass rc, ValueKind kind, int code) [inline], [static]
Definition at line 207 of file liftoff-register.h.
                                                      {
    if (kFPAliasing == AliasingKind::kCombine && kind == kF32) {
      // Liftoff assumes a one-to-one mapping between float registers and
      // double registers, and so does not distinguish between f32 and f64
      // registers. The f32 register code must therefore be halved in order
      // to pass the f64 code to Liftoff.
      DCHECK_EQ(0, code % 2);
      return LiftoffRegister::from_code(rc, code >> 1);
    }
    if (kNeedS128RegPair && kind == kS128) {
      // Similarly for double registers and SIMD registers, the SIMD code
      // needs to be doubled to pass the f64 code to Liftoff.
      return LiftoffRegister::ForFpPair(DoubleRegister::from_code(code << 1));
    }
    return LiftoffRegister::from_code(rc, code);
  }
References code, DCHECK_EQ, ForFpPair(), v8::internal::RegisterBase< DoubleRegister, kDoubleAfterLast >::from_code(), from_code(), v8::internal::kCombine, v8::internal::kF32, v8::internal::kFPAliasing, v8::internal::wasm::kNeedS128RegPair, and v8::internal::kS128.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ParameterProcessor::CurrentRegister(), v8::internal::wasm::LiftoffAssembler::FinishCall(), v8::internal::wasm::LiftoffAssembler::MoveToReturnLocationsMultiReturn(), and v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::PrepareStackTransfers().
from_liftoff_code()
static LiftoffRegister v8::internal::wasm::LiftoffRegister::from_liftoff_code (int code) [inline], [static]
Definition at line 181 of file liftoff-register.h.
                                                     {
    LiftoffRegister reg{static_cast<storage_t>(code)};
    // Check that the code is correct by round-tripping through the
    // reg-class-specific constructor.
    DCHECK(
        (reg.is_gp() && code == LiftoffRegister{reg.gp()}.liftoff_code()) ||
        (reg.is_fp() && code == LiftoffRegister{reg.fp()}.liftoff_code()) ||
        (reg.is_gp_pair() &&
         code == ForPair(reg.low_gp(), reg.high_gp()).liftoff_code()) ||
        (reg.is_fp_pair() && code == ForFpPair(reg.low_fp()).liftoff_code()));
    return reg;
  }
References code, v8::internal::DCHECK(), ForFpPair(), ForPair(), and liftoff_code().
Referenced by v8::internal::wasm::LiftoffRegList::GetFirstRegSet(), v8::internal::wasm::LiftoffRegList::GetLastRegSet(), v8::internal::wasm::DebugInfoImpl::GetValue(), and v8::internal::wasm::LiftoffAssembler::SpillAdjacentFpRegisters().
gp()
constexpr Register v8::internal::wasm::LiftoffRegister::gp () const [inline], [constexpr]
Definition at line 294 of file liftoff-register.h.
                                {
    DCHECK(is_gp());
    return Register::from_code(code_);
  }
References code_, v8::internal::DCHECK(), v8::internal::Register::from_code(), and is_gp().
Referenced by v8::internal::wasm::liftoff::CacheStatePreservingTempRegisters::Acquire(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicCompareExchange(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicGet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicRMW(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicSet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayFill(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayFillImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayGet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayLen(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArraySet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::AssertNullTypecheckImpl(), v8::internal::wasm::LiftoffAssembler::AtomicCompareExchange(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BoundsCheckArray(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BoundsCheckMem(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrOnCastFailImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrOnCastImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrOnNonNull(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrOnNull(), v8::internal::wasm::LiftoffAssembler::CallCWithStackBuffer(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallRefImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CatchCase(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CatchException(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CheckMaxSteps(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CheckS128Nan(), v8::internal::wasm::LiftoffAssembler::ClearRegister(), v8::internal::wasm::LiftoffStackSlots::Construct(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CurrentMemoryPages(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::DataDrop(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ElemDrop(), v8::internal::wasm::liftoff::Emit64BitShiftOperation(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_alltrue(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_bitmask(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_extract_lane_s(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_extract_lane_u(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_replace_lane(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_splat(), v8::internal::wasm::LiftoffAssembler::emit_i32_popcnt(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_alltrue(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_bitmask(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_extract_lane(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_replace_lane(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_splat(), v8::internal::wasm::LiftoffAssembler::emit_i64_and(), v8::internal::wasm::LiftoffAssembler::emit_i64_andi(), v8::internal::wasm::LiftoffAssembler::emit_i64_muli(), v8::internal::wasm::LiftoffAssembler::emit_i64_or(), v8::internal::wasm::LiftoffAssembler::emit_i64_ori(), v8::internal::wasm::LiftoffAssembler::emit_i64_popcnt(), v8::internal::wasm::LiftoffAssembler::emit_i64_xor(), v8::internal::wasm::LiftoffAssembler::emit_i64_xori(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_alltrue(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_bitmask(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_alltrue(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_bitmask(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_extract_lane_s(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_extract_lane_u(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_replace_lane(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_splat(), v8::internal::wasm::LiftoffAssembler::emit_inc_i32_at(), v8::internal::wasm::LiftoffAssembler::emit_ptrsize_set_cond(), v8::internal::wasm::LiftoffAssembler::emit_type_conversion(), v8::internal::wasm::liftoff::EmitAllTrue(), v8::internal::wasm::liftoff::EmitAnyTrue(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitDivOrRem64CCall(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitI64Shift(), v8::internal::wasm::liftoff::EmitInt32DivOrRem(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitIsNull(), v8::internal::wasm::liftoff::EmitShiftOperation(), v8::internal::wasm::liftoff::EmitSimdShift(), v8::internal::wasm::liftoff::EmitSimdShiftOp(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitTypeConversion(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetExceptionProperty(), v8::internal::wasm::liftoff::GetRegFromType(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetRttFromDescriptorOnStack(), v8::internal::wasm::liftoff::GetTmpByteRegister(), v8::internal::wasm::LiftoffAssembler::GetUnusedRegister(), v8::internal::wasm::LiftoffVarState::gp_reg(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::I31GetS(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::I31GetU(), v8::internal::wasm::liftoff::I64Shiftop(), v8::internal::wasm::LiftoffAssembler::IncrementSmi(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::IndexToVarStateSaturating(), LiftoffRegister(), v8::internal::wasm::liftoff::Load(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Load16BitExceptionValue(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Load32BitExceptionValue(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LoadAtomicObjectField(), v8::internal::wasm::LiftoffAssembler::LoadConstant(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LoadExceptionValue(), v8::internal::wasm::liftoff::LoadFromStack(), v8::internal::wasm::LiftoffAssembler::LoadI64HalfIntoRegister(), v8::internal::wasm::liftoff::LoadInternal(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LoadObjectField(), v8::internal::wasm::LiftoffAssembler::LoadOldFramePointer(), v8::internal::wasm::LiftoffAssembler::LoadSmiAsInt32(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::MemoryGrow(), v8::internal::wasm::LiftoffAssembler::Move(), v8::internal::wasm::liftoff::MoveStackValue(), v8::internal::wasm::operator<<(), v8::internal::wasm::liftoff::OpWithCarry(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::PopIndexToVarState(), v8::internal::wasm::LiftoffAssembler::PrepareCall(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ParameterProcessor::Process(), v8::internal::wasm::liftoff::push(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::RefAsNonNull(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::RefCastImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::RefGetDesc(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::RefI31(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::RefTest(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::RttCanon(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SetDefaultValue(), v8::internal::wasm::liftoff::Store(), v8::internal::wasm::LiftoffAssembler::Store(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StoreExceptionValue(), v8::internal::wasm::liftoff::StoreToMemory(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringAsIter(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringAsWtf16(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringAsWtf8(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringCompare(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringConcat(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringEncodeWtf16(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringEncodeWtf16Array(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringEncodeWtf8(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringEncodeWtf8Array(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringEq(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringHash(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringIsUSVSequence(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringMeasureWtf16(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringMeasureWtf8(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringNewWtf16Array(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringNewWtf8Array(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringViewIterAdvance(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringViewIterNext(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringViewIterRewind(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringViewIterSlice(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringViewWtf16Encode(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringViewWtf16GetCodeUnit(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringViewWtf16Slice(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringViewWtf8Advance(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringViewWtf8Encode(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringViewWtf8Slice(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructAtomicCompareExchange(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructAtomicGet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructAtomicRMW(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructAtomicSet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructGet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructNew(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructSet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SubtypeCheck(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Throw(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TraceMemoryOperation(), v8::internal::wasm::LiftoffAssembler::CacheState::TrySetCachedInstanceRegister(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::UnOp().
high()
LiftoffRegister v8::internal::wasm::LiftoffRegister::high () const [inline]
Definition at line 263 of file liftoff-register.h.
                               {
    // Common case for most archs where only gp pair supported.
    if (!kNeedS128RegPair) return LiftoffRegister(high_gp());
    return is_gp_pair() ? LiftoffRegister(high_gp())
                        : LiftoffRegister(high_fp());
  }
References high_fp(), high_gp(), is_gp_pair(), v8::internal::wasm::kNeedS128RegPair, and LiftoffRegister().
Referenced by v8::internal::wasm::LiftoffRegList::clear(), v8::internal::wasm::LiftoffAssembler::CacheState::clear_used(), v8::internal::wasm::LiftoffStackSlots::Construct(), v8::internal::wasm::LiftoffAssembler::CacheState::dec_used(), ForPair(), v8::internal::wasm::LiftoffAssembler::CacheState::get_use_count(), v8::internal::wasm::LiftoffRegList::has(), v8::internal::wasm::LiftoffAssembler::CacheState::inc_used(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::IndexToVarStateSaturating(), v8::internal::wasm::LiftoffAssembler::CacheState::is_used(), v8::internal::wasm::ParallelMove::LoadConstant(), v8::internal::wasm::ParallelMove::LoadI64HalfIntoRegister(), v8::internal::wasm::LiftoffAssembler::LoadI64HalfIntoRegister(), v8::internal::wasm::ParallelMove::LoadStackSlot(), v8::internal::wasm::ParallelMove::MoveRegister(), overlaps(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::PopIndexToVarState(), and v8::internal::wasm::LiftoffRegList::set().
high_fp()
DoubleRegister v8::internal::wasm::LiftoffRegister::high_fp () const [inline]
Definition at line 288 of file liftoff-register.h.
                                 {
    DCHECK(is_fp_pair());
    static constexpr storage_t kCodeMask = (1 << kBitsPerFpRegCode) - 1;
    return DoubleRegister::from_code((code_ & kCodeMask) + 1);
  }
References code_, v8::internal::DCHECK(), v8::internal::RegisterBase< DoubleRegister, kDoubleAfterLast >::from_code(), is_fp_pair(), and v8::internal::wasm::kBitsPerFpRegCode.
Referenced by v8::internal::wasm::LiftoffAssembler::emit_f32x4_demote_f64x2_zero(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_div(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_sqrt(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_abs(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_add(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_ceil(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_div(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_floor(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_mul(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_nearest_int(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_neg(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_qfma(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_qfms(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_splat(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_sqrt(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_sub(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_trunc(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_alltrue(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_extmul_high_i8x16_s(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_extmul_high_i8x16_u(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_sconvert_i8x16_high(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_uconvert_i8x16_high(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_alltrue(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_extmul_high_i16x8_s(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_extmul_high_i16x8_u(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_sconvert_i16x8_high(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_trunc_sat_f64x2_s_zero(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_trunc_sat_f64x2_u_zero(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_uconvert_i16x8_high(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_extmul_high_i32x4_s(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_extmul_high_i32x4_u(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_sconvert_i32x4_high(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_uconvert_i32x4_high(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_alltrue(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_swizzle(), v8::internal::wasm::LiftoffAssembler::emit_s128_const(), v8::internal::wasm::liftoff::EmitAnyTrue(), high(), v8::internal::wasm::LiftoffAssembler::LoadLane(), v8::internal::wasm::LiftoffAssembler::LoadTransform(), v8::internal::wasm::operator<<(), v8::internal::wasm::liftoff::S128NarrowOp(), and v8::internal::wasm::LiftoffAssembler::StoreLane().
high_gp()
Register v8::internal::wasm::LiftoffRegister::high_gp () const [inline]
Definition at line 276 of file liftoff-register.h.
                           {
    DCHECK(is_gp_pair());
    static constexpr storage_t kCodeMask = (1 << kBitsPerGpRegCode) - 1;
    return Register::from_code((code_ >> kBitsPerGpRegCode) & kCodeMask);
  }
References code_, v8::internal::DCHECK(), v8::internal::Register::from_code(), is_gp_pair(), and v8::internal::wasm::kBitsPerGpRegCode.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicCompareExchange(), v8::internal::wasm::liftoff::Emit64BitShiftOperation(), v8::internal::wasm::LiftoffAssembler::emit_i64_clz(), v8::internal::wasm::LiftoffAssembler::emit_i64_ctz(), v8::internal::wasm::LiftoffAssembler::emit_i64_eqz(), v8::internal::wasm::LiftoffAssembler::emit_i64_mul(), v8::internal::wasm::LiftoffAssembler::emit_i64_popcnt(), v8::internal::wasm::LiftoffAssembler::emit_i64_sari(), v8::internal::wasm::LiftoffAssembler::emit_i64_set_cond(), v8::internal::wasm::LiftoffAssembler::emit_i64_shli(), v8::internal::wasm::LiftoffAssembler::emit_i64_shri(), v8::internal::wasm::LiftoffAssembler::emit_i64_signextend_i16(), v8::internal::wasm::LiftoffAssembler::emit_i64_signextend_i32(), v8::internal::wasm::LiftoffAssembler::emit_i64_signextend_i8(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_extract_lane(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_replace_lane(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_splat(), v8::internal::wasm::LiftoffAssembler::emit_type_conversion(), v8::internal::wasm::liftoff::EnsureNoAlias(), high(), v8::internal::wasm::liftoff::I64Binop(), v8::internal::wasm::liftoff::I64BinopI(), v8::internal::wasm::liftoff::I64Shiftop(), v8::internal::wasm::liftoff::I64Store(), v8::internal::wasm::liftoff::IsRegInRegPair(), v8::internal::wasm::liftoff::Load(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Load64BitExceptionValue(), v8::internal::wasm::LiftoffAssembler::LoadConstant(), v8::internal::wasm::liftoff::LoadInternal(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::MemoryGrow(), v8::internal::wasm::operator<<(), v8::internal::wasm::liftoff::OpWithCarry(), v8::internal::wasm::liftoff::OpWithCarryI(), v8::internal::wasm::liftoff::PairContains(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::PopIndexToVarState(), v8::internal::wasm::liftoff::push(), v8::internal::wasm::liftoff::ReplaceInPair(), v8::internal::wasm::liftoff::SignExtendI32ToI64(), v8::internal::wasm::liftoff::Store(), v8::internal::wasm::LiftoffAssembler::Store(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructAtomicCompareExchange().
is_fp()
constexpr bool v8::internal::wasm::LiftoffRegister::is_fp () const [inline], [constexpr]
Definition at line 252 of file liftoff-register.h.
                               {
    return code_ >= kAfterMaxLiftoffGpRegCode &&
           code_ < kAfterMaxLiftoffFpRegCode;
  }
References code_, v8::internal::wasm::kAfterMaxLiftoffFpRegCode, and v8::internal::wasm::kAfterMaxLiftoffGpRegCode.
Referenced by fp(), v8::internal::wasm::LiftoffVarState::is_fp_reg(), and v8::internal::wasm::ParallelMove::MoveRegister().
is_fp_pair()
constexpr bool v8::internal::wasm::LiftoffRegister::is_fp_pair () const [inline], [constexpr]
Definition at line 248 of file liftoff-register.h.
                                    {
    return kNeedS128RegPair && (code_ & (2 << (2 * kBitsPerGpRegCode))) != 0;
  }
References code_, v8::internal::wasm::kBitsPerGpRegCode, and v8::internal::wasm::kNeedS128RegPair.
Referenced by high_fp(), v8::internal::wasm::LiftoffVarState::is_fp_reg_pair(), v8::internal::wasm::ParallelMove::LoadStackSlot(), v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::RegisterReuseMap::Lookup(), low_fp(), v8::internal::wasm::LiftoffAssembler::Move(), v8::internal::wasm::ParallelMove::MoveRegister(), v8::internal::wasm::operator<<(), operator==(), and reg_class().
is_gp()
constexpr bool v8::internal::wasm::LiftoffRegister::is_gp () const [inline], [constexpr]
Definition at line 251 of file liftoff-register.h.
{ return code_ < kAfterMaxLiftoffGpRegCode; }
References code_, and v8::internal::wasm::kAfterMaxLiftoffGpRegCode.
Referenced by gp(), v8::internal::wasm::LiftoffVarState::is_gp_reg(), v8::internal::wasm::LiftoffAssembler::Move(), v8::internal::wasm::operator<<(), and reg_class().
is_gp_pair()
constexpr bool v8::internal::wasm::LiftoffRegister::is_gp_pair () const [inline], [constexpr]
Definition at line 245 of file liftoff-register.h.
                                    {
    return kNeedI64RegPair && (code_ & (1 << (2 * kBitsPerGpRegCode))) != 0;
  }
References code_, v8::internal::wasm::kBitsPerGpRegCode, and v8::internal::wasm::kNeedI64RegPair.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicCompareExchange(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitI64Shift(), high(), high_gp(), v8::internal::wasm::LiftoffVarState::is_gp_reg_pair(), v8::internal::wasm::liftoff::IsRegInRegPair(), v8::internal::wasm::ParallelMove::LoadConstant(), v8::internal::wasm::liftoff::LoadInternal(), v8::internal::wasm::ParallelMove::LoadStackSlot(), v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::RegisterReuseMap::Lookup(), low(), low_gp(), v8::internal::wasm::LiftoffAssembler::Move(), v8::internal::wasm::ParallelMove::MoveRegister(), v8::internal::wasm::operator<<(), operator==(), reg_class(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructAtomicCompareExchange().
is_pair()
constexpr bool v8::internal::wasm::LiftoffRegister::is_pair () const [inline], [constexpr]
Definition at line 240 of file liftoff-register.h.
                                 {
    return (kNeedI64RegPair || kNeedS128RegPair) &&
           (code_ & (3 << (2 * kBitsPerGpRegCode)));
  }
References code_, v8::internal::wasm::kBitsPerGpRegCode, v8::internal::wasm::kNeedI64RegPair, and v8::internal::wasm::kNeedS128RegPair.
Referenced by v8::internal::wasm::LiftoffRegList::clear(), v8::internal::wasm::LiftoffAssembler::CacheState::clear_used(), v8::internal::wasm::LiftoffAssembler::CacheState::dec_used(), v8::internal::wasm::LiftoffAssembler::CacheState::get_use_count(), v8::internal::wasm::LiftoffRegList::has(), v8::internal::wasm::LiftoffAssembler::CacheState::inc_used(), v8::internal::wasm::LiftoffAssembler::CacheState::is_used(), overlaps(), and v8::internal::wasm::LiftoffRegList::set().
liftoff_code()
constexpr int v8::internal::wasm::LiftoffRegister::liftoff_code () const [inline], [constexpr]
Definition at line 304 of file liftoff-register.h.
                                     {
    static_assert(sizeof(int) >= sizeof(storage_t));
    return static_cast<int>(code_);
  }
References code_.
Referenced by v8::internal::wasm::LiftoffRegList::clear(), v8::internal::wasm::LiftoffAssembler::CacheState::clear_used(), v8::internal::wasm::LiftoffAssembler::CacheState::dec_used(), from_liftoff_code(), v8::internal::wasm::LiftoffAssembler::CacheState::get_use_count(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetCurrentDebugSideTableEntries(), v8::internal::wasm::LiftoffRegList::has(), v8::internal::wasm::LiftoffAssembler::CacheState::inc_used(), v8::internal::wasm::LiftoffAssembler::CacheState::is_used(), v8::internal::wasm::ParallelMove::register_load(), v8::internal::wasm::ParallelMove::register_move(), v8::internal::wasm::LiftoffRegList::set(), v8::internal::wasm::LiftoffAssembler::SpillAdjacentFpRegisters(), and v8::internal::wasm::ParallelMove::src_reg_use_count().
low()
LiftoffRegister v8::internal::wasm::LiftoffRegister::low () const [inline]
Definition at line 257 of file liftoff-register.h.
                              {
    // Common case for most archs where only gp pair supported.
    if (!kNeedS128RegPair) return LiftoffRegister(low_gp());
    return is_gp_pair() ? LiftoffRegister(low_gp()) : LiftoffRegister(low_fp());
  }
References is_gp_pair(), v8::internal::wasm::kNeedS128RegPair, LiftoffRegister(), low_fp(), and low_gp().
Referenced by v8::internal::wasm::LiftoffAssembler::AtomicCompareExchange(), v8::internal::wasm::LiftoffRegList::clear(), v8::internal::wasm::LiftoffAssembler::CacheState::clear_used(), v8::internal::wasm::LiftoffStackSlots::Construct(), v8::internal::wasm::LiftoffAssembler::CacheState::dec_used(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitBitRotationCCall(), ForFpPair(), ForPair(), v8::internal::wasm::LiftoffAssembler::CacheState::get_use_count(), v8::internal::wasm::LiftoffRegList::has(), v8::internal::wasm::LiftoffAssembler::CacheState::inc_used(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::IndexToVarStateSaturating(), v8::internal::wasm::LiftoffAssembler::CacheState::is_used(), v8::internal::wasm::ParallelMove::LoadConstant(), v8::internal::wasm::ParallelMove::LoadI64HalfIntoRegister(), v8::internal::wasm::LiftoffAssembler::LoadI64HalfIntoRegister(), v8::internal::wasm::ParallelMove::LoadStackSlot(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::MemoryGrow(), v8::internal::wasm::ParallelMove::MoveRegister(), overlaps(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::PopIndexToVarState(), v8::internal::wasm::LiftoffRegList::set(), and v8::internal::wasm::LiftoffAssembler::Store().
low_fp()
DoubleRegister v8::internal::wasm::LiftoffRegister::low_fp () const [inline]
Definition at line 282 of file liftoff-register.h.
                                {
    DCHECK(is_fp_pair());
    static constexpr storage_t kCodeMask = (1 << kBitsPerFpRegCode) - 1;
    return DoubleRegister::from_code(code_ & kCodeMask);
  }
References code_, v8::internal::DCHECK(), v8::internal::RegisterBase< DoubleRegister, kDoubleAfterLast >::from_code(), is_fp_pair(), and v8::internal::wasm::kBitsPerFpRegCode.
Referenced by v8::internal::wasm::LiftoffAssembler::emit_f32x4_demote_f64x2_zero(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_div(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_sqrt(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_abs(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_add(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_ceil(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_div(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_floor(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_mul(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_nearest_int(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_neg(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_qfma(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_qfms(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_splat(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_sqrt(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_sub(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_trunc(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_alltrue(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_extmul_low_i8x16_s(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_extmul_low_i8x16_u(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_sconvert_i8x16_low(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_uconvert_i8x16_low(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_alltrue(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_extmul_low_i16x8_s(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_extmul_low_i16x8_u(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_sconvert_i16x8_low(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_trunc_sat_f64x2_s_zero(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_trunc_sat_f64x2_u_zero(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_uconvert_i16x8_low(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_extmul_low_i32x4_s(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_extmul_low_i32x4_u(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_sconvert_i32x4_low(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_uconvert_i32x4_low(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_alltrue(), v8::internal::wasm::LiftoffAssembler::emit_i8x16_swizzle(), v8::internal::wasm::LiftoffAssembler::emit_s128_const(), v8::internal::wasm::LiftoffAssembler::emit_s128_store_nonzero_if_nan(), v8::internal::wasm::liftoff::EmitAnyTrue(), v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::liftoff::Load(), v8::internal::wasm::liftoff::LoadInternal(), v8::internal::wasm::LiftoffAssembler::LoadLane(), v8::internal::wasm::LiftoffAssembler::LoadTransform(), low(), v8::internal::wasm::LiftoffAssembler::Move(), v8::internal::wasm::operator<<(), v8::internal::wasm::liftoff::S128NarrowOp(), v8::internal::wasm::liftoff::Store(), v8::internal::wasm::LiftoffAssembler::Store(), and v8::internal::wasm::LiftoffAssembler::StoreLane().
low_gp()
Register v8::internal::wasm::LiftoffRegister::low_gp () const [inline]
Definition at line 270 of file liftoff-register.h.
                          {
    DCHECK(is_gp_pair());
    static constexpr storage_t kCodeMask = (1 << kBitsPerGpRegCode) - 1;
    return Register::from_code(code_ & kCodeMask);
  }
References code_, v8::internal::DCHECK(), v8::internal::Register::from_code(), is_gp_pair(), and v8::internal::wasm::kBitsPerGpRegCode.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicCompareExchange(), v8::internal::wasm::liftoff::Emit64BitShiftOperation(), v8::internal::wasm::LiftoffAssembler::emit_i64_clz(), v8::internal::wasm::LiftoffAssembler::emit_i64_ctz(), v8::internal::wasm::LiftoffAssembler::emit_i64_eqz(), v8::internal::wasm::LiftoffAssembler::emit_i64_mul(), v8::internal::wasm::LiftoffAssembler::emit_i64_popcnt(), v8::internal::wasm::LiftoffAssembler::emit_i64_sari(), v8::internal::wasm::LiftoffAssembler::emit_i64_set_cond(), v8::internal::wasm::LiftoffAssembler::emit_i64_shli(), v8::internal::wasm::LiftoffAssembler::emit_i64_shri(), v8::internal::wasm::LiftoffAssembler::emit_i64_signextend_i16(), v8::internal::wasm::LiftoffAssembler::emit_i64_signextend_i32(), v8::internal::wasm::LiftoffAssembler::emit_i64_signextend_i8(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_extract_lane(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_replace_lane(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_splat(), v8::internal::wasm::LiftoffAssembler::emit_type_conversion(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitI64Shift(), v8::internal::wasm::liftoff::EnsureNoAlias(), v8::internal::wasm::liftoff::I64Binop(), v8::internal::wasm::liftoff::I64BinopI(), v8::internal::wasm::liftoff::I64Shiftop(), v8::internal::wasm::liftoff::I64Store(), v8::internal::wasm::liftoff::IsRegInRegPair(), v8::internal::wasm::liftoff::Load(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Load64BitExceptionValue(), v8::internal::wasm::LiftoffAssembler::LoadConstant(), v8::internal::wasm::liftoff::LoadInternal(), low(), v8::internal::wasm::operator<<(), v8::internal::wasm::liftoff::OpWithCarry(), v8::internal::wasm::liftoff::OpWithCarryI(), v8::internal::wasm::liftoff::PairContains(), v8::internal::wasm::liftoff::push(), v8::internal::wasm::liftoff::ReplaceInPair(), v8::internal::wasm::liftoff::SignExtendI32ToI64(), v8::internal::wasm::liftoff::Store(), v8::internal::wasm::LiftoffAssembler::Store(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructAtomicCompareExchange().
operator==()
bool v8::internal::wasm::LiftoffRegister::operator== (const LiftoffRegister other) const [inline]
Definition at line 314 of file liftoff-register.h.
                                                     {
    DCHECK_EQ(is_gp_pair(), other.is_gp_pair());
    DCHECK_EQ(is_fp_pair(), other.is_fp_pair());
    return code_ == other.code_;
  }
References code_, DCHECK_EQ, is_fp_pair(), and is_gp_pair().
overlaps()
bool v8::internal::wasm::LiftoffRegister::overlaps (const LiftoffRegister other) const [inline]
Definition at line 319 of file liftoff-register.h.
                                                   {
    if (is_pair()) return low().overlaps(other) || high().overlaps(other);
    if (other.is_pair()) return *this == other.low() || *this == other.high();
    return *this == other;
  }
References high(), is_pair(), low(), and overlaps().
Referenced by v8::internal::wasm::liftoff::Emit64BitShiftOperation(), v8::internal::wasm::LiftoffAssembler::emit_i64_set_cond(), and overlaps().
reg_class()
constexpr RegClass v8::internal::wasm::LiftoffRegister::reg_class () const [inline], [constexpr]
Definition at line 309 of file liftoff-register.h.
                                       {
    return is_fp_pair() ? kFpRegPair
                        : is_gp_pair() ? kGpRegPair : is_gp() ? kGpReg : kFpReg;
  }
References is_fp_pair(), is_gp(), is_gp_pair(), v8::internal::wasm::kFpReg, v8::internal::wasm::kFpRegPair, v8::internal::wasm::kGpReg, and v8::internal::wasm::kGpRegPair.
Referenced by v8::internal::wasm::LiftoffAssembler::GetUnusedRegister(), v8::internal::wasm::LiftoffVarState::LiftoffVarState(), v8::internal::wasm::ParallelMove::LoadIntoRegister(), v8::internal::wasm::LiftoffAssembler::LoadToModifiableRegister(), v8::internal::wasm::LiftoffAssembler::Move(), v8::internal::wasm::ParallelMove::MoveRegister(), v8::internal::wasm::LiftoffAssembler::PushRegister(), v8::internal::wasm::LiftoffVarState::reg_class(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Select().
Member Data Documentation
code_
storage_t v8::internal::wasm::LiftoffRegister::code_ [private]
Definition at line 328 of file liftoff-register.h.
Referenced by fp(), gp(), high_fp(), high_gp(), is_fp(), is_fp_pair(), is_gp(), is_gp_pair(), is_pair(), liftoff_code(), low_fp(), low_gp(), and operator==().
needed_bits
constexpr int v8::internal::wasm::LiftoffRegister::needed_bits [static], [constexpr], [private]
Initial value:
=
      std::max(kNeedI64RegPair || kNeedS128RegPair ? kBitsPerRegPair : 0,
               kBitsPerLiftoffRegCode)
Definition at line 144 of file liftoff-register.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/baseline/liftoff-register.h