v8::internal::compiler::LiveRangeBuilder Class Reference
#include <register-allocator.h>
Public Member Functions
LiveRangeBuilder (RegisterAllocationData *data, Zone *local_zone)
LiveRangeBuilder (const LiveRangeBuilder &)=delete
LiveRangeBuilder & operator= (const LiveRangeBuilder &)=delete
void BuildLiveRanges ()
Static Public Member Functions
static SparseBitVector * ComputeLiveOut (const InstructionBlock *block, RegisterAllocationData *data)
Private Types
using SpillMode = RegisterAllocationData::SpillMode
Private Member Functions
RegisterAllocationData * data () const
InstructionSequence * code () const
Zone * allocation_zone () const
Zone * code_zone () const
const RegisterConfiguration * config () const
ZoneVector< SparseBitVector * > & live_in_sets () const
void AddInitialIntervals (const InstructionBlock *block, SparseBitVector *live_out)
void ProcessInstructions (const InstructionBlock *block, SparseBitVector *live)
void ProcessPhis (const InstructionBlock *block, SparseBitVector *live)
void ProcessLoopHeader (const InstructionBlock *block, SparseBitVector *live)
int FixedFPLiveRangeID (int index, MachineRepresentation rep)
TopLevelLiveRange * FixedLiveRangeFor (int index, SpillMode spill_mode)
TopLevelLiveRange * FixedFPLiveRangeFor (int index, MachineRepresentation rep, SpillMode spill_mode)
TopLevelLiveRange * FixedSIMD128LiveRangeFor (int index, SpillMode spill_mode)
void MapPhiHint (InstructionOperand *operand, UsePosition *use_pos)
void ResolvePhiHint (InstructionOperand *operand, UsePosition *use_pos)
UsePosition * NewUsePosition (LifetimePosition pos, InstructionOperand *operand, void *hint, UsePositionHintType hint_type)
UsePosition * NewUsePosition (LifetimePosition pos)
TopLevelLiveRange * LiveRangeFor (InstructionOperand *operand, SpillMode spill_mode)
UsePosition * Define (LifetimePosition position, InstructionOperand *operand, void *hint, UsePositionHintType hint_type, SpillMode spill_mode)
void Define (LifetimePosition position, InstructionOperand *operand, SpillMode spill_mode)
UsePosition * Use (LifetimePosition block_start, LifetimePosition position, InstructionOperand *operand, void *hint, UsePositionHintType hint_type, SpillMode spill_mode)
void Use (LifetimePosition block_start, LifetimePosition position, InstructionOperand *operand, SpillMode spill_mode)
SpillMode SpillModeForBlock (const InstructionBlock *block) const
Static Private Member Functions
static int FixedLiveRangeID (int index)
Private Attributes
RegisterAllocationData *const data_
ZoneMap< InstructionOperand *, UsePosition * > phi_hints_
Static Private Attributes
static constexpr int kNumberOfFixedRangesPerRegister
Detailed Description
Definition at line 1366 of file register-allocator.h.
Member Typedef Documentation
SpillMode
using v8::internal::compiler::LiveRangeBuilder::SpillMode = RegisterAllocationData::SpillMode [private]
Definition at line 1378 of file register-allocator.h.
Constructor & Destructor Documentation
LiveRangeBuilder() [1/2]
v8::internal::compiler::LiveRangeBuilder::LiveRangeBuilder (RegisterAllocationData * data, Zone * local_zone) [explicit]
Definition at line 1791 of file register-allocator.cc.
    : data_(data), phi_hints_(local_zone) {}
LiveRangeBuilder() [2/2]
v8::internal::compiler::LiveRangeBuilder::LiveRangeBuilder (const LiveRangeBuilder &) [delete]
Member Function Documentation
AddInitialIntervals()
void v8::internal::compiler::LiveRangeBuilder::AddInitialIntervals (const InstructionBlock * block, SparseBitVector * live_out) [private]
Definition at line 1828 of file register-allocator.cc.
                                                                      {
  // Add an interval that includes the entire block to the live range for
  // each live_out value.
  LifetimePosition start = LifetimePosition::GapFromInstructionIndex(
      block->first_instruction_index());
  LifetimePosition end = LifetimePosition::InstructionFromInstructionIndex(
                             block->last_instruction_index())
                             .NextStart();
  for (int operand_index : *live_out) {
    TopLevelLiveRange* range = data()->GetLiveRangeFor(operand_index);
    range->AddUseInterval(start, end, allocation_zone());
  }
}
References v8::internal::compiler::TopLevelLiveRange::AddUseInterval(), allocation_zone(), data(), v8::internal::compiler::end(), v8::internal::compiler::InstructionBlock::first_instruction_index(), v8::internal::compiler::LifetimePosition::GapFromInstructionIndex(), v8::internal::compiler::RegisterAllocationData::GetLiveRangeFor(), v8::internal::compiler::LifetimePosition::InstructionFromInstructionIndex(), v8::internal::compiler::InstructionBlock::last_instruction_index(), and v8::internal::compiler::LifetimePosition::NextStart().
Referenced by BuildLiveRanges().
allocation_zone()
Zone* v8::internal::compiler::LiveRangeBuilder::allocation_zone () const [inline], [private]
Definition at line 1384 of file register-allocator.h.
{ return data()->allocation_zone(); }
References v8::internal::compiler::RegisterAllocationData::allocation_zone(), and data().
Referenced by AddInitialIntervals(), Define(), NewUsePosition(), ProcessInstructions(), ProcessLoopHeader(), and Use().
BuildLiveRanges()
void v8::internal::compiler::LiveRangeBuilder::BuildLiveRanges ()
Definition at line 2401 of file register-allocator.cc.
                                       {
  // Process the blocks in reverse order.
  for (int block_id = code()->InstructionBlockCount() - 1; block_id >= 0;
       --block_id) {
    data_->tick_counter()->TickAndMaybeEnterSafepoint();
    InstructionBlock* block =
        code()->InstructionBlockAt(RpoNumber::FromInt(block_id));
    SparseBitVector* live = ComputeLiveOut(block, data());
    // Initially consider all live_out values live for the entire block. We
    // will shorten these intervals if necessary.
    AddInitialIntervals(block, live);
    // Process the instructions in reverse order, generating and killing
    // live values.
    ProcessInstructions(block, live);
    // All phi output operands are killed by this block.
    ProcessPhis(block, live);
    // Now live is live_in for this block except not including values live
    // out on backward successor edges.
    if (block->IsLoopHeader()) ProcessLoopHeader(block, live);
    live_in_sets()[block_id] = live;
  }
  // Postprocess the ranges.
  const size_t live_ranges_size = data()->live_ranges().size();
  for (TopLevelLiveRange* range : data()->live_ranges()) {
    data_->tick_counter()->TickAndMaybeEnterSafepoint();
    CHECK_EQ(live_ranges_size,
             data()->live_ranges().size()); // TODO(neis): crbug.com/831822
    DCHECK_NOT_NULL(range);
    // Give slots to all ranges with a non fixed slot use.
    if (range->has_slot_use() && range->HasNoSpillType()) {
      SpillMode spill_mode =
          range->slot_use_kind() ==
                  TopLevelLiveRange::SlotUseKind::kDeferredSlotUse
              ? SpillMode::kSpillDeferred
              : SpillMode::kSpillAtDefinition;
      data()->AssignSpillRangeToLiveRange(range, spill_mode);
    }
    // TODO(bmeurer): This is a horrible hack to make sure that for constant
    // live ranges, every use requires the constant to be in a register.
    // Without this hack, all uses with "any" policy would get the constant
    // operand assigned.
    if (range->HasSpillOperand() && range->GetSpillOperand()->IsConstant()) {
      for (UsePosition* pos : range->positions()) {
        if (pos->type() == UsePositionType::kRequiresSlot ||
            pos->type() == UsePositionType::kRegisterOrSlotOrConstant) {
          continue;
        }
        UsePositionType new_type = UsePositionType::kRegisterOrSlot;
        // Can't mark phis as needing a register.
        if (!pos->pos().IsGapPosition()) {
          new_type = UsePositionType::kRequiresRegister;
        }
        pos->set_type(new_type, true);
      }
    }
    range->ResetCurrentHintPosition();
  }
  for (auto preassigned : data()->preassigned_slot_ranges()) {
    TopLevelLiveRange* range = preassigned.first;
    int slot_id = preassigned.second;
    SpillRange* spill = range->HasSpillRange()
                            ? range->GetSpillRange()
                            : data()->AssignSpillRangeToLiveRange(
                                  range, SpillMode::kSpillAtDefinition);
    spill->set_assigned_slot(slot_id);
  }
#ifdef DEBUG
  Verify();
#endif
}
References AddInitialIntervals(), v8::internal::compiler::RegisterAllocationData::AssignSpillRangeToLiveRange(), CHECK_EQ, code(), ComputeLiveOut(), data(), data_, DCHECK_NOT_NULL, v8::internal::compiler::RpoNumber::FromInt(), v8::internal::compiler::TopLevelLiveRange::GetSpillRange(), v8::internal::compiler::TopLevelLiveRange::HasSpillRange(), v8::internal::compiler::InstructionSequence::InstructionBlockAt(), v8::internal::compiler::InstructionBlock::IsLoopHeader(), v8::internal::compiler::kRegisterOrSlot, v8::internal::compiler::kRegisterOrSlotOrConstant, v8::internal::compiler::kRequiresRegister, v8::internal::compiler::kRequiresSlot, live_in_sets(), v8::internal::compiler::RegisterAllocationData::live_ranges(), ProcessInstructions(), ProcessLoopHeader(), ProcessPhis(), v8::internal::compiler::SpillRange::set_assigned_slot(), size(), v8::internal::compiler::RegisterAllocationData::tick_counter(), and v8::internal::TickCounter::TickAndMaybeEnterSafepoint().
Referenced by v8::internal::compiler::turboshaft::BuildLiveRangesPhase::Run().
code()
InstructionSequence* v8::internal::compiler::LiveRangeBuilder::code () const [inline], [private]
Definition at line 1383 of file register-allocator.h.
{ return data()->code(); }
References v8::internal::compiler::RegisterAllocationData::code(), and data().
Referenced by BuildLiveRanges(), code_zone(), ComputeLiveOut(), LiveRangeFor(), ProcessInstructions(), ProcessLoopHeader(), and ProcessPhis().
code_zone()
Zone* v8::internal::compiler::LiveRangeBuilder::code_zone () const [inline], [private]
Definition at line 1385 of file register-allocator.h.
{ return code()->zone(); }
References code(), and v8::internal::compiler::InstructionSequence::zone().
ComputeLiveOut()
SparseBitVector * v8::internal::compiler::LiveRangeBuilder::ComputeLiveOut (const InstructionBlock * block, RegisterAllocationData * data) [static]
Definition at line 1795 of file register-allocator.cc.
                                                                 {
  size_t block_index = block->rpo_number().ToSize();
  SparseBitVector* live_out = data->live_out_sets()[block_index];
  if (live_out == nullptr) {
    // Compute live out for the given block, except not including backward
    // successor edges.
    Zone* zone = data->allocation_zone();
    const InstructionSequence* code = data->code();
    live_out = zone->New<SparseBitVector>(zone);
    // Process all successor blocks.
    for (const RpoNumber& succ : block->successors()) {
      // Add values live on entry to the successor.
      if (succ <= block->rpo_number()) continue;
      SparseBitVector* live_in = data->live_in_sets()[succ.ToSize()];
      if (live_in != nullptr) live_out->Union(*live_in);
      // All phi input operands corresponding to this successor edge are live
      // out from this block.
      const InstructionBlock* successor = code->InstructionBlockAt(succ);
      size_t index = successor->PredecessorIndexOf(block->rpo_number());
      DCHECK(index < successor->PredecessorCount());
      for (PhiInstruction* phi : successor->phis()) {
        live_out->Add(phi->operands()[index]);
      }
    }
    data->live_out_sets()[block_index] = live_out;
  }
  return live_out;
}
References v8::internal::SparseBitVector::Add(), v8::internal::compiler::RegisterAllocationData::allocation_zone(), v8::internal::compiler::RegisterAllocationData::code(), code(), data(), v8::internal::DCHECK(), v8::internal::index, v8::internal::compiler::InstructionSequence::InstructionBlockAt(), v8::internal::compiler::RegisterAllocationData::live_in_sets(), v8::internal::compiler::RegisterAllocationData::live_out_sets(), v8::internal::Zone::New(), v8::internal::compiler::InstructionBlock::phis(), v8::internal::compiler::InstructionBlock::PredecessorIndexOf(), v8::internal::compiler::InstructionBlock::rpo_number(), v8::internal::compiler::InstructionBlock::successors(), v8::internal::compiler::RpoNumber::ToSize(), and v8::internal::SparseBitVector::Union().
Referenced by BuildLiveRanges().
config()
const RegisterConfiguration* v8::internal::compiler::LiveRangeBuilder::config () const [inline], [private]
Definition at line 1386 of file register-allocator.h.
{ return data()->config(); }
References v8::internal::compiler::RegisterAllocationData::config(), and data().
Referenced by FixedFPLiveRangeFor(), FixedFPLiveRangeID(), FixedLiveRangeFor(), FixedSIMD128LiveRangeFor(), and ProcessInstructions().
data()
RegisterAllocationData* v8::internal::compiler::LiveRangeBuilder::data () const [inline], [private]
Definition at line 1382 of file register-allocator.h.
{ return data_; }
References data_.
Referenced by AddInitialIntervals(), allocation_zone(), BuildLiveRanges(), code(), ComputeLiveOut(), config(), FixedFPLiveRangeFor(), FixedLiveRangeFor(), FixedSIMD128LiveRangeFor(), live_in_sets(), LiveRangeFor(), ProcessInstructions(), and ProcessLoopHeader().
Define() [1/2]
void v8::internal::compiler::LiveRangeBuilder::Define (LifetimePosition position, InstructionOperand * operand, SpillMode spill_mode) [inline], [private]
Definition at line 1430 of file register-allocator.h.
                                    {
    Define(position, operand, nullptr, UsePositionHintType::kNone, spill_mode);
  }
References Define(), and v8::internal::compiler::kNone.
Define() [2/2]
UsePosition * v8::internal::compiler::LiveRangeBuilder::Define (LifetimePosition position, InstructionOperand * operand, void * hint, UsePositionHintType hint_type, SpillMode spill_mode) [private]
Definition at line 1985 of file register-allocator.cc.
                                                            {
  TopLevelLiveRange* range = LiveRangeFor(operand, spill_mode);
  if (range == nullptr) return nullptr;
  if (range->IsEmpty() || range->Start() > position) {
    // Can happen if there is a definition without use.
    range->AddUseInterval(position, position.NextStart(), allocation_zone());
    range->AddUsePosition(NewUsePosition(position.NextStart()),
                          allocation_zone());
  } else {
    range->ShortenTo(position);
  }
  if (!operand->IsUnallocated()) return nullptr;
  UnallocatedOperand* unalloc_operand = UnallocatedOperand::cast(operand);
  UsePosition* use_pos =
      NewUsePosition(position, unalloc_operand, hint, hint_type);
  range->AddUsePosition(use_pos, allocation_zone());
  return use_pos;
}
References v8::internal::compiler::TopLevelLiveRange::AddUseInterval(), v8::internal::compiler::TopLevelLiveRange::AddUsePosition(), allocation_zone(), v8::internal::compiler::LiveRange::IsEmpty(), LiveRangeFor(), NewUsePosition(), v8::internal::compiler::LifetimePosition::NextStart(), v8::internal::compiler::TopLevelLiveRange::ShortenTo(), and v8::internal::compiler::LiveRange::Start().
Referenced by Define(), ProcessInstructions(), and ProcessPhis().
FixedFPLiveRangeFor()
TopLevelLiveRange * v8::internal::compiler::LiveRangeBuilder::FixedFPLiveRangeFor (int index, MachineRepresentation rep, SpillMode spill_mode) [private]
Definition at line 1889 of file register-allocator.cc.
                                                                {
  int num_regs = config()->num_double_registers();
  ZoneVector<TopLevelLiveRange*>* live_ranges =
      &data()->fixed_double_live_ranges();
  if (kFPAliasing == AliasingKind::kCombine) {
    switch (rep) {
      case MachineRepresentation::kFloat16:
      case MachineRepresentation::kFloat32:
        num_regs = config()->num_float_registers();
        live_ranges = &data()->fixed_float_live_ranges();
        break;
      case MachineRepresentation::kSimd128:
        num_regs = config()->num_simd128_registers();
        live_ranges = &data()->fixed_simd128_live_ranges();
        break;
      default:
        break;
    }
  }
  int offset = spill_mode == SpillMode::kSpillAtDefinition ? 0 : num_regs;
  DCHECK(index < num_regs);
  USE(num_regs);
  TopLevelLiveRange* result = (*live_ranges)[offset + index];
  if (result == nullptr) {
    result = data()->NewLiveRange(FixedFPLiveRangeID(offset + index, rep), rep);
    DCHECK(result->IsFixed());
    result->set_assigned_register(index);
    data()->MarkAllocated(rep, index);
    if (spill_mode == SpillMode::kSpillDeferred) {
      result->set_deferred_fixed();
    }
    (*live_ranges)[offset + index] = result;
  }
  return result;
}
References config(), data(), v8::internal::DCHECK(), v8::internal::compiler::RegisterAllocationData::fixed_double_live_ranges(), v8::internal::compiler::RegisterAllocationData::fixed_float_live_ranges(), v8::internal::compiler::RegisterAllocationData::fixed_simd128_live_ranges(), FixedFPLiveRangeID(), v8::internal::index, v8::internal::kCombine, v8::internal::kFloat16, v8::internal::kFloat32, v8::internal::kFPAliasing, v8::internal::kSimd128, v8::internal::compiler::RegisterAllocationData::MarkAllocated(), v8::internal::compiler::RegisterAllocationData::NewLiveRange(), v8::internal::RegisterConfiguration::num_double_registers(), v8::internal::RegisterConfiguration::num_float_registers(), v8::internal::RegisterConfiguration::num_simd128_registers(), v8::base::internal::result, and USE.
Referenced by LiveRangeFor(), and ProcessInstructions().
FixedFPLiveRangeID()
int v8::internal::compiler::LiveRangeBuilder::FixedFPLiveRangeID (int index, MachineRepresentation rep) [private]
Definition at line 1843 of file register-allocator.cc.
                                                                             {
  int result = -index - 1;
  switch (rep) {
    case MachineRepresentation::kSimd256:
      result -=
          kNumberOfFixedRangesPerRegister * config()->num_simd128_registers();
      [[fallthrough]];
    case MachineRepresentation::kSimd128:
      result -=
          kNumberOfFixedRangesPerRegister * config()->num_float_registers();
      [[fallthrough]];
    case MachineRepresentation::kFloat32:
      result -=
          kNumberOfFixedRangesPerRegister * config()->num_double_registers();
      [[fallthrough]];
    case MachineRepresentation::kFloat64:
      result -=
          kNumberOfFixedRangesPerRegister * config()->num_general_registers();
      break;
    default:
      UNREACHABLE();
  }
  return result;
}
References config(), v8::internal::index, v8::internal::kFloat32, v8::internal::kFloat64, kNumberOfFixedRangesPerRegister, v8::internal::kSimd128, v8::internal::kSimd256, v8::internal::RegisterConfiguration::num_double_registers(), v8::internal::RegisterConfiguration::num_float_registers(), v8::internal::RegisterConfiguration::num_general_registers(), v8::internal::RegisterConfiguration::num_simd128_registers(), v8::base::internal::result, and v8::internal::UNREACHABLE().
Referenced by FixedFPLiveRangeFor(), and FixedSIMD128LiveRangeFor().
FixedLiveRangeFor()
TopLevelLiveRange * v8::internal::compiler::LiveRangeBuilder::FixedLiveRangeFor (int index, SpillMode spill_mode) [private]
Definition at line 1868 of file register-allocator.cc.
                                                                             {
  int offset = spill_mode == SpillMode::kSpillAtDefinition
                   ? 0
                   : config()->num_general_registers();
  DCHECK(index < config()->num_general_registers());
  TopLevelLiveRange* result = data()->fixed_live_ranges()[offset + index];
  if (result == nullptr) {
    MachineRepresentation rep = InstructionSequence::DefaultRepresentation();
    result = data()->NewLiveRange(FixedLiveRangeID(offset + index), rep);
    DCHECK(result->IsFixed());
    result->set_assigned_register(index);
    data()->MarkAllocated(rep, index);
    if (spill_mode == SpillMode::kSpillDeferred) {
      result->set_deferred_fixed();
    }
    data()->fixed_live_ranges()[offset + index] = result;
  }
  return result;
}
References config(), data(), v8::internal::DCHECK(), v8::internal::compiler::InstructionSequence::DefaultRepresentation(), v8::internal::compiler::RegisterAllocationData::fixed_live_ranges(), FixedLiveRangeID(), v8::internal::index, v8::internal::compiler::RegisterAllocationData::MarkAllocated(), v8::internal::compiler::RegisterAllocationData::NewLiveRange(), v8::internal::RegisterConfiguration::num_general_registers(), and v8::base::internal::result.
Referenced by LiveRangeFor(), and ProcessInstructions().
FixedLiveRangeID()
static int v8::internal::compiler::LiveRangeBuilder::FixedLiveRangeID (int index) [inline], [static], [private]
Definition at line 1409 of file register-allocator.h.
{ return -index - 1; }
References v8::internal::index.
Referenced by FixedLiveRangeFor().
FixedSIMD128LiveRangeFor()
TopLevelLiveRange * v8::internal::compiler::LiveRangeBuilder::FixedSIMD128LiveRangeFor (int index, SpillMode spill_mode) [private]
Definition at line 1928 of file register-allocator.cc.
                                     {
  DCHECK_EQ(kFPAliasing, AliasingKind::kIndependent);
  int num_regs = config()->num_simd128_registers();
  ZoneVector<TopLevelLiveRange*>* live_ranges =
      &data()->fixed_simd128_live_ranges();
  int offset = spill_mode == SpillMode::kSpillAtDefinition ? 0 : num_regs;
  DCHECK(index < num_regs);
  USE(num_regs);
  TopLevelLiveRange* result = (*live_ranges)[offset + index];
  if (result == nullptr) {
    result = data()->NewLiveRange(
        FixedFPLiveRangeID(offset + index, MachineRepresentation::kSimd128),
        MachineRepresentation::kSimd128);
    DCHECK(result->IsFixed());
    result->set_assigned_register(index);
    data()->MarkAllocated(MachineRepresentation::kSimd128, index);
    if (spill_mode == SpillMode::kSpillDeferred) {
      result->set_deferred_fixed();
    }
    (*live_ranges)[offset + index] = result;
  }
  return result;
}
References config(), data(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::RegisterAllocationData::fixed_simd128_live_ranges(), FixedFPLiveRangeID(), v8::internal::index, v8::internal::kFPAliasing, v8::internal::kIndependent, v8::internal::kSimd128, v8::internal::compiler::RegisterAllocationData::MarkAllocated(), v8::internal::compiler::RegisterAllocationData::NewLiveRange(), v8::internal::RegisterConfiguration::num_simd128_registers(), v8::base::internal::result, and USE.
Referenced by LiveRangeFor(), and ProcessInstructions().
live_in_sets()
ZoneVector<SparseBitVector*>& v8::internal::compiler::LiveRangeBuilder::live_in_sets () const [inline], [private]
Definition at line 1387 of file register-allocator.h.
                                                     {
    return data()->live_in_sets();
  }
References data(), and v8::internal::compiler::RegisterAllocationData::live_in_sets().
Referenced by BuildLiveRanges(), and ProcessLoopHeader().
LiveRangeFor()
TopLevelLiveRange * v8::internal::compiler::LiveRangeBuilder::LiveRangeFor (InstructionOperand * operand, SpillMode spill_mode) [private]
Definition at line 1954 of file register-allocator.cc.
                                                                        {
  if (operand->IsUnallocated()) {
    return data()->GetLiveRangeFor(
        UnallocatedOperand::cast(operand)->virtual_register());
  } else if (operand->IsConstant()) {
    return data()->GetLiveRangeFor(
        ConstantOperand::cast(operand)->virtual_register());
  } else if (operand->IsRegister()) {
    return FixedLiveRangeFor(
        LocationOperand::cast(operand)->GetRegister().code(), spill_mode);
  } else if (operand->IsFPRegister()) {
    LocationOperand* op = LocationOperand::cast(operand);
    if (kFPAliasing == AliasingKind::kIndependent &&
        op->representation() == MachineRepresentation::kSimd128) {
      return FixedSIMD128LiveRangeFor(op->register_code(), spill_mode);
    }
    return FixedFPLiveRangeFor(op->register_code(), op->representation(),
                               spill_mode);
  } else {
    return nullptr;
  }
}
References v8::internal::compiler::LocationOperand::cast(), code(), data(), FixedFPLiveRangeFor(), FixedLiveRangeFor(), FixedSIMD128LiveRangeFor(), v8::internal::compiler::RegisterAllocationData::GetLiveRangeFor(), v8::internal::compiler::InstructionOperand::IsFPRegister(), v8::internal::compiler::InstructionOperand::IsRegister(), v8::internal::kFPAliasing, v8::internal::kIndependent, v8::internal::kSimd128, v8::internal::compiler::LocationOperand::register_code(), and v8::internal::compiler::LocationOperand::representation().
Referenced by Define(), and Use().
MapPhiHint()
void v8::internal::compiler::LiveRangeBuilder::MapPhiHint (InstructionOperand * operand, UsePosition * use_pos) [private]
Definition at line 2472 of file register-allocator.cc.
                                                        {
  DCHECK(!use_pos->IsResolved());
  auto res = phi_hints_.insert(std::make_pair(operand, use_pos));
  DCHECK(res.second);
  USE(res);
}
References v8::internal::DCHECK(), v8::internal::compiler::UsePosition::IsResolved(), phi_hints_, and USE.
Referenced by ProcessPhis().
NewUsePosition() [1/2]
UsePosition* v8::internal::compiler::LiveRangeBuilder::NewUsePosition (LifetimePosition pos) [inline], [private]
Definition at line 1421 of file register-allocator.h.
                                                    {
    return NewUsePosition(pos, nullptr, nullptr, UsePositionHintType::kNone);
  }
References v8::internal::compiler::kNone, and NewUsePosition().
NewUsePosition() [2/2]
UsePosition * v8::internal::compiler::LiveRangeBuilder::NewUsePosition (LifetimePosition pos, InstructionOperand * operand, void * hint, UsePositionHintType hint_type) [private]
Definition at line 1978 of file register-allocator.cc.
                                                                             {
  return allocation_zone()->New<UsePosition>(pos, operand, hint, hint_type);
}
References allocation_zone(), and v8::internal::Zone::New().
Referenced by Define(), NewUsePosition(), and Use().
operator=()
LiveRangeBuilder& v8::internal::compiler::LiveRangeBuilder::operator= (const LiveRangeBuilder &) [delete]
ProcessInstructions()
void v8::internal::compiler::LiveRangeBuilder::ProcessInstructions (const InstructionBlock * block, SparseBitVector * live) [private]
Definition at line 2025 of file register-allocator.cc.
                                                                  {
  int block_start = block->first_instruction_index();
  LifetimePosition block_start_position =
      LifetimePosition::GapFromInstructionIndex(block_start);
  bool fixed_float_live_ranges = false;
  bool fixed_simd128_live_ranges = false;
  if (kFPAliasing == AliasingKind::kCombine) {
    int mask = data()->code()->representation_mask();
    fixed_float_live_ranges = (mask & kFloat32Bit) != 0;
    fixed_simd128_live_ranges = (mask & kSimd128Bit) != 0;
  } else if (kFPAliasing == AliasingKind::kIndependent) {
    int mask = data()->code()->representation_mask();
    fixed_simd128_live_ranges = (mask & kSimd128Bit) != 0;
  }
  SpillMode spill_mode = SpillModeForBlock(block);
  for (int index = block->last_instruction_index(); index >= block_start;
       index--) {
    LifetimePosition curr_position =
        LifetimePosition::InstructionFromInstructionIndex(index);
    Instruction* instr = code()->InstructionAt(index);
    DCHECK_NOT_NULL(instr);
    DCHECK(curr_position.IsInstructionPosition());
    // Process output, inputs, and temps of this instruction.
    for (size_t i = 0; i < instr->OutputCount(); i++) {
      InstructionOperand* output = instr->OutputAt(i);
      if (output->IsUnallocated()) {
        // Unsupported.
        DCHECK(!UnallocatedOperand::cast(output)->HasSlotPolicy());
        int out_vreg = UnallocatedOperand::cast(output)->virtual_register();
        live->Remove(out_vreg);
      } else if (output->IsConstant()) {
        int out_vreg = ConstantOperand::cast(output)->virtual_register();
        live->Remove(out_vreg);
      }
      if (block->IsHandler() && index == block_start && output->IsAllocated() &&
          output->IsRegister() &&
          AllocatedOperand::cast(output)->GetRegister() ==
              v8::internal::kReturnRegister0) {
        // The register defined here is blocked from gap start - it is the
        // exception value.
        // TODO(mtrofin): should we explore an explicit opcode for
        // the first instruction in the handler?
        Define(LifetimePosition::GapFromInstructionIndex(index), output,
               spill_mode);
      } else {
        Define(curr_position, output, spill_mode);
      }
    }
    if (instr->ClobbersRegisters()) {
      for (int i = 0; i < config()->num_allocatable_general_registers(); ++i) {
        // Create a UseInterval at this instruction for all fixed registers,
        // (including the instruction outputs). Adding another UseInterval here
        // is OK because AddUseInterval will just merge it with the existing
        // one at the end of the range.
        int code = config()->GetAllocatableGeneralCode(i);
        TopLevelLiveRange* range = FixedLiveRangeFor(code, spill_mode);
        range->AddUseInterval(curr_position, curr_position.End(),
                              allocation_zone());
      }
    }
    if (instr->ClobbersDoubleRegisters()) {
      for (int i = 0; i < config()->num_allocatable_double_registers(); ++i) {
        // Add a UseInterval for all DoubleRegisters. See comment above for
        // general registers.
        int code = config()->GetAllocatableDoubleCode(i);
        TopLevelLiveRange* range = FixedFPLiveRangeFor(
            code, MachineRepresentation::kFloat64, spill_mode);
        range->AddUseInterval(curr_position, curr_position.End(),
                              allocation_zone());
      }
      // Clobber fixed float registers on archs with non-simple aliasing.
      if (kFPAliasing == AliasingKind::kCombine) {
        if (fixed_float_live_ranges) {
          for (int i = 0; i < config()->num_allocatable_float_registers();
               ++i) {
            // Add a UseInterval for all FloatRegisters. See comment above for
            // general registers.
            int code = config()->GetAllocatableFloatCode(i);
            TopLevelLiveRange* range = FixedFPLiveRangeFor(
                code, MachineRepresentation::kFloat32, spill_mode);
            range->AddUseInterval(curr_position, curr_position.End(),
                                  allocation_zone());
          }
        }
        if (fixed_simd128_live_ranges) {
          for (int i = 0; i < config()->num_allocatable_simd128_registers();
               ++i) {
            int code = config()->GetAllocatableSimd128Code(i);
            TopLevelLiveRange* range = FixedFPLiveRangeFor(
                code, MachineRepresentation::kSimd128, spill_mode);
            range->AddUseInterval(curr_position, curr_position.End(),
                                  allocation_zone());
          }
        }
      } else if (kFPAliasing == AliasingKind::kIndependent) {
        if (fixed_simd128_live_ranges) {
          for (int i = 0; i < config()->num_allocatable_simd128_registers();
               ++i) {
            int code = config()->GetAllocatableSimd128Code(i);
            TopLevelLiveRange* range =
                FixedSIMD128LiveRangeFor(code, spill_mode);
            range->AddUseInterval(curr_position, curr_position.End(),
                                  allocation_zone());
          }
        }
      }
    }
    for (size_t i = 0; i < instr->InputCount(); i++) {
      InstructionOperand* input = instr->InputAt(i);
      if (input->IsImmediate()) {
        continue; // Ignore immediates.
      }
      LifetimePosition use_pos;
      if (input->IsUnallocated() &&
          UnallocatedOperand::cast(input)->IsUsedAtStart()) {
        use_pos = curr_position;
      } else {
        use_pos = curr_position.End();
      }
      if (input->IsUnallocated()) {
        UnallocatedOperand* unalloc = UnallocatedOperand::cast(input);
        int vreg = unalloc->virtual_register();
        live->Add(vreg);
        if (unalloc->HasSlotPolicy()) {
          data()->GetLiveRangeFor(vreg)->register_slot_use(
              block->IsDeferred()
                  ? TopLevelLiveRange::SlotUseKind::kDeferredSlotUse
                  : TopLevelLiveRange::SlotUseKind::kGeneralSlotUse);
        }
      }
      Use(block_start_position, use_pos, input, spill_mode);
    }
    for (size_t i = 0; i < instr->TempCount(); i++) {
      InstructionOperand* temp = instr->TempAt(i);
      // Unsupported.
      DCHECK_IMPLIES(temp->IsUnallocated(),
                     !UnallocatedOperand::cast(temp)->HasSlotPolicy());
      if (instr->ClobbersTemps()) {
        if (temp->IsRegister()) continue;
        if (temp->IsUnallocated()) {
          UnallocatedOperand* temp_unalloc = UnallocatedOperand::cast(temp);
          if (temp_unalloc->HasFixedPolicy()) {
            continue;
          }
        }
      }
      Use(block_start_position, curr_position.End(), temp, spill_mode);
      Define(curr_position, temp, spill_mode);
    }
    // Process the moves of the instruction's gaps, making their sources live.
    const Instruction::GapPosition kPositions[] = {Instruction::END,
                                                   Instruction::START};
    curr_position = curr_position.PrevStart();
    DCHECK(curr_position.IsGapPosition());
    for (const Instruction::GapPosition& position : kPositions) {
      ParallelMove* move = instr->GetParallelMove(position);
      if (move == nullptr) continue;
      if (position == Instruction::END) {
        curr_position = curr_position.End();
      } else {
        curr_position = curr_position.Start();
      }
      for (MoveOperands* cur : *move) {
        InstructionOperand& from = cur->source();
        InstructionOperand& to = cur->destination();
        void* hint = &to;
        UsePositionHintType hint_type = UsePosition::HintTypeForOperand(to);
        UsePosition* to_use = nullptr;
        int phi_vreg = -1;
        if (to.IsUnallocated()) {
          int to_vreg = UnallocatedOperand::cast(to).virtual_register();
          TopLevelLiveRange* to_range = data()->GetLiveRangeFor(to_vreg);
          if (to_range->is_phi()) {
            phi_vreg = to_vreg;
            if (to_range->is_non_loop_phi()) {
              hint = to_range->current_hint_position();
              hint_type = hint == nullptr ? UsePositionHintType::kNone
                                          : UsePositionHintType::kUsePos;
            } else {
              hint_type = UsePositionHintType::kPhi;
              hint = data()->GetPhiMapValueFor(to_vreg);
            }
          } else {
            if (live->Contains(to_vreg)) {
              to_use =
                  Define(curr_position, &to, &from,
                         UsePosition::HintTypeForOperand(from), spill_mode);
              live->Remove(to_vreg);
            } else {
              cur->Eliminate();
              continue;
            }
          }
        } else {
          Define(curr_position, &to, spill_mode);
        }
        UsePosition* from_use = Use(block_start_position, curr_position, &from,
                                    hint, hint_type, spill_mode);
        // Mark range live.
        if (from.IsUnallocated()) {
          live->Add(UnallocatedOperand::cast(from).virtual_register());
        }
        // When the value is moved to a register to meet input constraints,
        // we should consider this value use similar as a register use in the
        // backward spilling heuristics, even though this value use is not
        // register benefical at the AllocateBlockedReg stage.
        if (to.IsAnyRegister() ||
            (to.IsUnallocated() &&
             UnallocatedOperand::cast(&to)->HasRegisterPolicy())) {
          from_use->set_spill_detrimental();
        }
        // Resolve use position hints just created.
        if (to_use != nullptr && from_use != nullptr) {
          to_use->ResolveHint(from_use);
          from_use->ResolveHint(to_use);
        }
        DCHECK_IMPLIES(to_use != nullptr, to_use->IsResolved());
        DCHECK_IMPLIES(from_use != nullptr, from_use->IsResolved());
        // Potentially resolve phi hint.
        if (phi_vreg != -1) ResolvePhiHint(&from, from_use);
      }
    }
  }
}
References v8::internal::SparseBitVector::Add(), v8::internal::compiler::TopLevelLiveRange::AddUseInterval(), allocation_zone(), v8::internal::compiler::LocationOperand::cast(), v8::internal::compiler::Instruction::ClobbersDoubleRegisters(), v8::internal::compiler::Instruction::ClobbersRegisters(), v8::internal::compiler::Instruction::ClobbersTemps(), v8::internal::compiler::RegisterAllocationData::code(), code(), config(), v8::internal::SparseBitVector::Contains(), v8::internal::compiler::LiveRange::current_hint_position(), data(), v8::internal::DCHECK(), DCHECK_IMPLIES, DCHECK_NOT_NULL, Define(), v8::internal::compiler::Instruction::END, v8::internal::compiler::LifetimePosition::End(), v8::internal::compiler::InstructionBlock::first_instruction_index(), FixedFPLiveRangeFor(), FixedLiveRangeFor(), FixedSIMD128LiveRangeFor(), v8::internal::compiler::LifetimePosition::GapFromInstructionIndex(), v8::internal::RegisterConfiguration::GetAllocatableDoubleCode(), v8::internal::RegisterConfiguration::GetAllocatableFloatCode(), v8::internal::RegisterConfiguration::GetAllocatableGeneralCode(), v8::internal::RegisterConfiguration::GetAllocatableSimd128Code(), v8::internal::compiler::RegisterAllocationData::GetLiveRangeFor(), v8::internal::compiler::Instruction::GetParallelMove(), v8::internal::compiler::RegisterAllocationData::GetPhiMapValueFor(), v8::internal::compiler::LocationOperand::GetRegister(), v8::internal::compiler::UnallocatedOperand::HasFixedPolicy(), v8::internal::compiler::UnallocatedOperand::HasSlotPolicy(), v8::internal::compiler::UsePosition::HintTypeForOperand(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::Instruction::InputCount(), v8::internal::compiler::InstructionSequence::InstructionAt(), v8::internal::compiler::LifetimePosition::InstructionFromInstructionIndex(), v8::internal::compiler::TopLevelLiveRange::is_non_loop_phi(), v8::internal::compiler::TopLevelLiveRange::is_phi(), v8::internal::compiler::InstructionOperand::IsAnyRegister(), v8::internal::compiler::InstructionBlock::IsDeferred(), v8::internal::compiler::LifetimePosition::IsGapPosition(), v8::internal::compiler::InstructionBlock::IsHandler(), v8::internal::compiler::LifetimePosition::IsInstructionPosition(), v8::internal::compiler::InstructionOperand::IsRegister(), v8::internal::compiler::UsePosition::IsResolved(), v8::internal::kCombine, v8::internal::kFloat32, v8::internal::compiler::anonymous_namespace{register-allocator.cc}::kFloat32Bit, v8::internal::kFloat64, v8::internal::kFPAliasing, v8::internal::kIndependent, v8::internal::compiler::kNone, v8::internal::compiler::kPhi, v8::internal::kReturnRegister0, v8::internal::kSimd128, v8::internal::compiler::anonymous_namespace{register-allocator.cc}::kSimd128Bit, v8::internal::compiler::kUsePos, v8::internal::compiler::InstructionBlock::last_instruction_index(), v8::internal::RegisterConfiguration::num_allocatable_double_registers(), v8::internal::RegisterConfiguration::num_allocatable_float_registers(), v8::internal::RegisterConfiguration::num_allocatable_general_registers(), v8::internal::RegisterConfiguration::num_allocatable_simd128_registers(), v8::internal::compiler::Instruction::OutputAt(), v8::internal::compiler::Instruction::OutputCount(), v8::internal::compiler::LifetimePosition::PrevStart(), v8::internal::compiler::TopLevelLiveRange::register_slot_use(), v8::internal::SparseBitVector::Remove(), v8::internal::compiler::InstructionSequence::representation_mask(), v8::internal::compiler::UsePosition::ResolveHint(), ResolvePhiHint(), v8::internal::compiler::UsePosition::set_spill_detrimental(), SpillModeForBlock(), v8::internal::compiler::Instruction::START, v8::internal::compiler::LifetimePosition::Start(), v8::internal::compiler::Instruction::TempAt(), v8::internal::compiler::Instruction::TempCount(), Use(), and v8::internal::compiler::UnallocatedOperand::virtual_register().
Referenced by BuildLiveRanges().
ProcessLoopHeader()
void v8::internal::compiler::LiveRangeBuilder::ProcessLoopHeader (const InstructionBlock * block, SparseBitVector * live) [private]
Definition at line 2380 of file register-allocator.cc.
                                                                {
  DCHECK(block->IsLoopHeader());
  // Add a live range stretching from the first loop instruction to the last
  // for each value live on entry to the header.
  LifetimePosition start = LifetimePosition::GapFromInstructionIndex(
      block->first_instruction_index());
  LifetimePosition end = LifetimePosition::GapFromInstructionIndex(
                             code()->LastLoopInstructionIndex(block))
                             .NextFullStart();
  for (int operand_index : *live) {
    TopLevelLiveRange* range = data()->GetLiveRangeFor(operand_index);
    range->EnsureInterval(start, end, allocation_zone());
  }
  // Insert all values into the live in sets of all blocks in the loop.
  for (int i = block->rpo_number().ToInt() + 1; i < block->loop_end().ToInt();
       ++i) {
    live_in_sets()[i]->Union(*live);
  }
}
References allocation_zone(), code(), data(), v8::internal::DCHECK(), v8::internal::compiler::end(), v8::internal::compiler::TopLevelLiveRange::EnsureInterval(), v8::internal::compiler::InstructionBlock::first_instruction_index(), v8::internal::compiler::LifetimePosition::GapFromInstructionIndex(), v8::internal::compiler::RegisterAllocationData::GetLiveRangeFor(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::InstructionBlock::IsLoopHeader(), live_in_sets(), v8::internal::compiler::LifetimePosition::NextFullStart(), v8::internal::compiler::InstructionBlock::rpo_number(), v8::internal::compiler::RpoNumber::ToInt(), and v8::internal::anonymous_namespace{temporal-parser.cc}::ToInt().
Referenced by BuildLiveRanges().
ProcessPhis()
void v8::internal::compiler::LiveRangeBuilder::ProcessPhis (const InstructionBlock * block, SparseBitVector * live) [private]
Definition at line 2258 of file register-allocator.cc.
                                                          {
  for (PhiInstruction* phi : block->phis()) {
    // The live range interval already ends at the first instruction of the
    // block.
    int phi_vreg = phi->virtual_register();
    live->Remove(phi_vreg);
    // Select a hint from a predecessor block that precedes this block in the
    // rpo order. In order of priority:
    // - Avoid hints from deferred blocks.
    // - Prefer hints from allocated (or explicit) operands.
    // - Prefer hints from empty blocks (containing just parallel moves and a
    // jump). In these cases, if we can elide the moves, the jump threader
    // is likely to be able to elide the jump.
    // The enforcement of hinting in rpo order is required because hint
    // resolution that happens later in the compiler pipeline visits
    // instructions in reverse rpo order, relying on the fact that phis are
    // encountered before their hints.
    InstructionOperand* hint = nullptr;
    int hint_preference = 0;
    // The cost of hinting increases with the number of predecessors. At the
    // same time, the typical benefit decreases, since this hinting only
    // optimises the execution path through one predecessor. A limit of 2 is
    // sufficient to hit the common if/else pattern.
    int predecessor_limit = 2;
    for (RpoNumber predecessor : block->predecessors()) {
      const InstructionBlock* predecessor_block =
          code()->InstructionBlockAt(predecessor);
      DCHECK_EQ(predecessor_block->rpo_number(), predecessor);
      // Only take hints from earlier rpo numbers.
      if (predecessor >= block->rpo_number()) continue;
      // Look up the predecessor instruction.
      const Instruction* predecessor_instr =
          GetLastInstruction(code(), predecessor_block);
      InstructionOperand* predecessor_hint = nullptr;
      // Phis are assigned in the END position of the last instruction in each
      // predecessor block.
      for (MoveOperands* move :
           *predecessor_instr->GetParallelMove(Instruction::END)) {
        InstructionOperand& to = move->destination();
        if (to.IsUnallocated() &&
            UnallocatedOperand::cast(to).virtual_register() == phi_vreg) {
          predecessor_hint = &move->source();
          break;
        }
      }
      DCHECK_NOT_NULL(predecessor_hint);
      // For each predecessor, generate a score according to the priorities
      // described above, and pick the best one. Flags in higher-order bits have
      // a higher priority than those in lower-order bits.
      int predecessor_hint_preference = 0;
      const int kNotDeferredBlockPreference = (1 << 2);
      const int kMoveIsAllocatedPreference = (1 << 1);
      const int kBlockIsEmptyPreference = (1 << 0);
      // - Avoid hints from deferred blocks.
      if (!predecessor_block->IsDeferred()) {
        predecessor_hint_preference |= kNotDeferredBlockPreference;
      }
      // - Prefer hints from allocated operands.
      //
      // Already-allocated operands are typically assigned using the parallel
      // moves on the last instruction. For example:
      //
      // gap (v101 = [x0|R|w32]) (v100 = v101)
      // ArchJmp
      // ...
      // phi: v100 = v101 v102
      //
      // We have already found the END move, so look for a matching START move
      // from an allocated operand.
      //
      // Note that we cannot simply look up data()->live_ranges()[vreg] here
      // because the live ranges are still being built when this function is
      // called.
      // TODO(v8): Find a way to separate hinting from live range analysis in
      // BuildLiveRanges so that we can use the O(1) live-range look-up.
      auto moves = predecessor_instr->GetParallelMove(Instruction::START);
      if (moves != nullptr) {
        for (MoveOperands* move : *moves) {
          InstructionOperand& to = move->destination();
          if (predecessor_hint->Equals(to)) {
            if (move->source().IsAllocated()) {
              predecessor_hint_preference |= kMoveIsAllocatedPreference;
            }
            break;
          }
        }
      }
      // - Prefer hints from empty blocks.
      if (predecessor_block->last_instruction_index() ==
          predecessor_block->first_instruction_index()) {
        predecessor_hint_preference |= kBlockIsEmptyPreference;
      }
      if ((hint == nullptr) ||
          (predecessor_hint_preference > hint_preference)) {
        // Take the hint from this predecessor.
        hint = predecessor_hint;
        hint_preference = predecessor_hint_preference;
      }
      if (--predecessor_limit <= 0) break;
    }
    DCHECK_NOT_NULL(hint);
    LifetimePosition block_start = LifetimePosition::GapFromInstructionIndex(
        block->first_instruction_index());
    UsePosition* use_pos = Define(block_start, &phi->output(), hint,
                                  UsePosition::HintTypeForOperand(*hint),
                                  SpillModeForBlock(block));
    MapPhiHint(hint, use_pos);
  }
}
References code(), DCHECK_EQ, DCHECK_NOT_NULL, Define(), v8::internal::compiler::Instruction::END, v8::internal::compiler::InstructionOperand::Equals(), v8::internal::compiler::InstructionBlock::first_instruction_index(), v8::internal::compiler::LifetimePosition::GapFromInstructionIndex(), v8::internal::compiler::anonymous_namespace{register-allocator.cc}::GetLastInstruction(), v8::internal::compiler::Instruction::GetParallelMove(), v8::internal::compiler::UsePosition::HintTypeForOperand(), v8::internal::compiler::InstructionSequence::InstructionBlockAt(), v8::internal::compiler::InstructionBlock::IsDeferred(), v8::internal::compiler::InstructionBlock::last_instruction_index(), MapPhiHint(), v8::internal::compiler::InstructionBlock::phis(), v8::internal::compiler::InstructionBlock::predecessors(), v8::internal::SparseBitVector::Remove(), v8::internal::compiler::InstructionBlock::rpo_number(), SpillModeForBlock(), and v8::internal::compiler::Instruction::START.
Referenced by BuildLiveRanges().
ResolvePhiHint()
void v8::internal::compiler::LiveRangeBuilder::ResolvePhiHint (InstructionOperand * operand, UsePosition * use_pos) [private]
Definition at line 2480 of file register-allocator.cc.
                                                            {
  auto it = phi_hints_.find(operand);
  if (it == phi_hints_.end()) return;
  DCHECK(!it->second->IsResolved());
  it->second->ResolveHint(use_pos);
}
References v8::internal::DCHECK(), and phi_hints_.
Referenced by ProcessInstructions().
SpillModeForBlock()
SpillMode v8::internal::compiler::LiveRangeBuilder::SpillModeForBlock (const InstructionBlock * block) const [inline], [private]
Definition at line 1442 of file register-allocator.h.
                                                                   {
    return block->IsDeferred() ? SpillMode::kSpillDeferred
                               : SpillMode::kSpillAtDefinition;
  }
References v8::internal::compiler::InstructionBlock::IsDeferred().
Referenced by ProcessInstructions(), and ProcessPhis().
Use() [1/2]
void v8::internal::compiler::LiveRangeBuilder::Use (LifetimePosition block_start, LifetimePosition position, InstructionOperand * operand, SpillMode spill_mode) [inline], [private]
Definition at line 1437 of file register-allocator.h.
                                                              {
    Use(block_start, position, operand, nullptr, UsePositionHintType::kNone,
        spill_mode);
  }
References v8::internal::compiler::kNone, and Use().
Use() [2/2]
UsePosition * v8::internal::compiler::LiveRangeBuilder::Use (LifetimePosition block_start, LifetimePosition position, InstructionOperand * operand, void * hint, UsePositionHintType hint_type, SpillMode spill_mode) [private]
Definition at line 2008 of file register-allocator.cc.
                                                         {
  TopLevelLiveRange* range = LiveRangeFor(operand, spill_mode);
  if (range == nullptr) return nullptr;
  UsePosition* use_pos = nullptr;
  if (operand->IsUnallocated()) {
    UnallocatedOperand* unalloc_operand = UnallocatedOperand::cast(operand);
    use_pos = NewUsePosition(position, unalloc_operand, hint, hint_type);
    range->AddUsePosition(use_pos, allocation_zone());
  }
  range->AddUseInterval(block_start, position, allocation_zone());
  return use_pos;
}
References v8::internal::compiler::TopLevelLiveRange::AddUseInterval(), v8::internal::compiler::TopLevelLiveRange::AddUsePosition(), allocation_zone(), LiveRangeFor(), and NewUsePosition().
Referenced by ProcessInstructions(), and Use().
Member Data Documentation
data_
RegisterAllocationData* const v8::internal::compiler::LiveRangeBuilder::data_ [private]
Definition at line 1446 of file register-allocator.h.
Referenced by BuildLiveRanges(), and data().
kNumberOfFixedRangesPerRegister
constexpr int v8::internal::compiler::LiveRangeBuilder::kNumberOfFixedRangesPerRegister [static], [constexpr], [private]
Initial value:
=
      RegisterAllocationData::kNumberOfFixedRangesPerRegister
Definition at line 1379 of file register-allocator.h.
Referenced by FixedFPLiveRangeID().
phi_hints_
ZoneMap<InstructionOperand*, UsePosition*> v8::internal::compiler::LiveRangeBuilder::phi_hints_ [private]
Definition at line 1447 of file register-allocator.h.
Referenced by MapPhiHint(), and ResolvePhiHint().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/register-allocator.h
/mnt/V8SourceCode/src/compiler/backend/register-allocator.cc