v8::internal::wasm::SimdShuffle Class Reference
#include <simd-shuffle.h>
Public Types
enum class CanonicalShuffle : uint8_t {
kUnknown
, kIdentity
, kS64x2Even
, kS64x2Odd
,
kS64x2ReverseBytes
, kS64x2Reverse
, kS32x4Even
, kS32x4Odd
,
kS32x4InterleaveLowHalves
, kS32x4InterleaveHighHalves
, kS32x4ReverseBytes
, kS32x4Reverse
,
kS32x2Reverse
, kS32x4TransposeEven
, kS32x4TransposeOdd
, kS16x8Even
,
kS16x8Odd
, kS16x8InterleaveLowHalves
, kS16x8InterleaveHighHalves
, kS16x8ReverseBytes
,
kS16x2Reverse
, kS16x4Reverse
, kS16x8TransposeEven
, kS16x8TransposeOdd
,
kS8x16Even
, kS8x16Odd
, kS8x16InterleaveLowHalves
, kS8x16InterleaveHighHalves
,
kS8x16TransposeEven
, kS8x16TransposeOdd
, kMaxShuffles
 }
using ShuffleArray = std::array< uint8_t, kSimd128Size >
Static Public Member Functions
template<const int simd_size = kSimd128Size>
static void CanonicalizeShuffle (bool inputs_equal, uint8_t *shuffle, bool *needs_swap, bool *is_swizzle) requires(simd_size
template<int LANES>
static bool TryMatchSplat (const uint8_t *shuffle, int *index)
static bool TryMatch32x4Rotate (const uint8_t *shuffle, uint8_t *shuffle32x4, bool is_swizzle)
static bool TryMatch32x4Reverse (const uint8_t *shuffle32x4)
static bool TryMatch32x4OneLaneSwizzle (const uint8_t *shuffle32x4, uint8_t *from, uint8_t *to)
static bool TryMatch64x1Shuffle (const uint8_t *shuffle, uint8_t *shuffle64x1)
static bool TryMatch64x2Shuffle (const uint8_t *shuffle, uint8_t *shuffle64x2)
static bool TryMatch32x1Shuffle (const uint8_t *shuffle, uint8_t *shuffle32x1)
static bool TryMatch32x2Shuffle (const uint8_t *shuffle, uint8_t *shuffle32x2)
static bool TryMatch32x4Shuffle (const uint8_t *shuffle, uint8_t *shuffle32x4)
static bool TryMatch32x8Shuffle (const uint8_t *shuffle, uint8_t *shuffle32x8)
static bool TryMatch16x1Shuffle (const uint8_t *shuffle, uint8_t *shuffle16x1)
static bool TryMatch16x2Shuffle (const uint8_t *shuffle, uint8_t *shuffle16x2)
static bool TryMatch16x4Shuffle (const uint8_t *shuffle, uint8_t *shuffle16x4)
static bool TryMatch16x8Shuffle (const uint8_t *shuffle, uint8_t *shuffle16x8)
static bool TryMatchConcat (const uint8_t *shuffle, uint8_t *offset)
static bool TryMatchBlend (const uint8_t *shuffle)
static bool TryMatchByteToDwordZeroExtend (const uint8_t *shuffle)
static bool TryMatch8x16UpperToLowerReduce (const uint8_t *shuffle1, const uint8_t *shuffle2, const uint8_t *shuffle3, const uint8_t *shuffle4)
static bool TryMatch16x8UpperToLowerReduce (const uint8_t *shuffle1, const uint8_t *shuffle2, const uint8_t *shuffle3)
static bool TryMatch32x4UpperToLowerReduce (const uint8_t *shuffle1, const uint8_t *shuffle2)
static bool TryMatch32x4PairwiseReduce (const uint8_t *shuffle1, const uint8_t *shuffle2)
static bool TryMatch64x2Reduce (const uint8_t *shuffle64x2)
static uint8_t PackShuffle4 (uint8_t *shuffle)
static uint8_t PackBlend8 (const uint8_t *shuffle16x8)
static uint8_t PackBlend4 (const uint8_t *shuffle32x4)
static int32_t Pack2Lanes (const std::array< uint8_t, 2 > &shuffle)
static int32_t Pack4Lanes (const uint8_t *shuffle)
static void Pack16Lanes (uint32_t *dst, const uint8_t *shuffle)
static CanonicalShuffle TryMatchCanonical (const ShuffleArray &shuffle)
Detailed Description
Definition at line 44 of file simd-shuffle.h.
Member Typedef Documentation
ShuffleArray
using v8::internal::wasm::SimdShuffle::ShuffleArray = std::array<uint8_t, kSimd128Size>
Definition at line 286 of file simd-shuffle.h.
Member Enumeration Documentation
CanonicalShuffle
enum v8::internal::wasm::SimdShuffle::CanonicalShuffle : uint8_t [strong]
Enumerator
kUnknown
kIdentity
kS64x2Even
kS64x2Odd
kS64x2ReverseBytes
kS64x2Reverse
kS32x4Even
kS32x4Odd
kS32x4InterleaveLowHalves
kS32x4InterleaveHighHalves
kS32x4ReverseBytes
kS32x4Reverse
kS32x2Reverse
kS32x4TransposeEven
kS32x4TransposeOdd
kS16x8Even
kS16x8Odd
kS16x8InterleaveLowHalves
kS16x8InterleaveHighHalves
kS16x8ReverseBytes
kS16x2Reverse
kS16x4Reverse
kS16x8TransposeEven
kS16x8TransposeOdd
kS8x16Even
kS8x16Odd
kS8x16InterleaveLowHalves
kS8x16InterleaveHighHalves
kS8x16TransposeEven
kS8x16TransposeOdd
kMaxShuffles
Definition at line 252 of file simd-shuffle.h.
                              : uint8_t {
    kUnknown,
    kIdentity,
    kS64x2Even,
    kS64x2Odd,
    kS64x2ReverseBytes,
    kS64x2Reverse,
    kS32x4Even,
    kS32x4Odd,
    kS32x4InterleaveLowHalves,
    kS32x4InterleaveHighHalves,
    kS32x4ReverseBytes,
    kS32x4Reverse,
    kS32x2Reverse,
    kS32x4TransposeEven,
    kS32x4TransposeOdd,
    kS16x8Even,
    kS16x8Odd,
    kS16x8InterleaveLowHalves,
    kS16x8InterleaveHighHalves,
    kS16x8ReverseBytes,
    kS16x2Reverse,
    kS16x4Reverse,
    kS16x8TransposeEven,
    kS16x8TransposeOdd,
    kS8x16Even,
    kS8x16Odd,
    kS8x16InterleaveLowHalves,
    kS8x16InterleaveHighHalves,
    kS8x16TransposeEven,
    kS8x16TransposeOdd,
    kMaxShuffles,
  };
Member Function Documentation
CanonicalizeShuffle()
template<const int simd_size = kSimd128Size>
static void v8::internal::wasm::SimdShuffle::CanonicalizeShuffle (bool inputs_equal, uint8_t * shuffle, bool * needs_swap, bool * is_swizzle) [static]
References v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Simd8x16ShuffleOp().
Pack16Lanes()
void v8::internal::wasm::SimdShuffle::Pack16Lanes (uint32_t * dst, const uint8_t * shuffle) [static]
Definition at line 409 of file simd-shuffle.cc.
                                                                   {
  for (int i = 0; i < 4; i++) {
    dst[i] = wasm::SimdShuffle::Pack4Lanes(shuffle + (i * 4));
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and Pack4Lanes().
Pack2Lanes()
int32_t v8::internal::wasm::SimdShuffle::Pack2Lanes (const std::array< uint8_t, 2 > & shuffle) [static]
Definition at line 391 of file simd-shuffle.cc.
                                                                   {
  int32_t result = 0;
  for (int i = 1; i >= 0; --i) {
    result <<= 8;
    result |= shuffle[i];
  }
  return result;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::base::internal::result.
Pack4Lanes()
int32_t v8::internal::wasm::SimdShuffle::Pack4Lanes (const uint8_t * shuffle) [static]
Definition at line 400 of file simd-shuffle.cc.
                                                      {
  int32_t result = 0;
  for (int i = 3; i >= 0; --i) {
    result <<= 8;
    result |= shuffle[i];
  }
  return result;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::base::internal::result.
Referenced by Pack16Lanes().
PackBlend4()
uint8_t v8::internal::wasm::SimdShuffle::PackBlend4 (const uint8_t * shuffle32x4) [static]
Definition at line 383 of file simd-shuffle.cc.
                                                          {
  int8_t result = 0;
  for (int i = 0; i < 4; ++i) {
    result |= (shuffle32x4[i] >= 4 ? 0x3 : 0) << (i * 2);
  }
  return result;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::base::internal::result.
PackBlend8()
uint8_t v8::internal::wasm::SimdShuffle::PackBlend8 (const uint8_t * shuffle16x8) [static]
Definition at line 375 of file simd-shuffle.cc.
                                                          {
  int8_t result = 0;
  for (int i = 0; i < 8; ++i) {
    result |= (shuffle16x8[i] >= 8 ? 1 : 0) << i;
  }
  return result;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::base::internal::result.
PackShuffle4()
uint8_t v8::internal::wasm::SimdShuffle::PackShuffle4 (uint8_t * shuffle) [static]
Definition at line 370 of file simd-shuffle.cc.
                                                  {
  return (shuffle[0] & 3) | ((shuffle[1] & 3) << 2) | ((shuffle[2] & 3) << 4) |
         ((shuffle[3] & 3) << 6);
}
TryMatch16x1Shuffle()
bool v8::internal::wasm::SimdShuffle::TryMatch16x1Shuffle (const uint8_t * shuffle, uint8_t * shuffle16x1) [static]
Definition at line 220 of file simd-shuffle.cc.
                                                            {
  return MatchHelper<1, 2>(shuffle, shuffle16x1);
}
TryMatch16x2Shuffle()
bool v8::internal::wasm::SimdShuffle::TryMatch16x2Shuffle (const uint8_t * shuffle, uint8_t * shuffle16x2) [static]
Definition at line 225 of file simd-shuffle.cc.
                                                            {
  return MatchHelper<2, 2>(shuffle, shuffle16x2);
}
TryMatch16x4Shuffle()
bool v8::internal::wasm::SimdShuffle::TryMatch16x4Shuffle (const uint8_t * shuffle, uint8_t * shuffle16x4) [static]
Definition at line 230 of file simd-shuffle.cc.
                                                            {
  return MatchHelper<4, 2>(shuffle, shuffle16x4);
}
TryMatch16x8Shuffle()
bool v8::internal::wasm::SimdShuffle::TryMatch16x8Shuffle (const uint8_t * shuffle, uint8_t * shuffle16x8) [static]
Definition at line 235 of file simd-shuffle.cc.
                                                            {
  return MatchHelper<8, 2>(shuffle, shuffle16x8);
}
TryMatch16x8UpperToLowerReduce()
bool v8::internal::wasm::SimdShuffle::TryMatch16x8UpperToLowerReduce (const uint8_t * shuffle1, const uint8_t * shuffle2, const uint8_t * shuffle3) [static]
Definition at line 347 of file simd-shuffle.cc.
                                                                          {
  return TryMatchUpperToLowerFirst(shuffle1) &&
         TryMatchUpperToLowerSecond(shuffle2) &&
         TryMatchUpperToLowerThird(shuffle3);
}
References v8::internal::wasm::anonymous_namespace{simd-shuffle.cc}::TryMatchUpperToLowerFirst(), v8::internal::wasm::anonymous_namespace{simd-shuffle.cc}::TryMatchUpperToLowerSecond(), and v8::internal::wasm::anonymous_namespace{simd-shuffle.cc}::TryMatchUpperToLowerThird().
TryMatch32x1Shuffle()
bool v8::internal::wasm::SimdShuffle::TryMatch32x1Shuffle (const uint8_t * shuffle, uint8_t * shuffle32x1) [static]
Definition at line 200 of file simd-shuffle.cc.
                                                            {
  return MatchHelper<1, 4>(shuffle, shuffle32x1);
}
TryMatch32x2Shuffle()
bool v8::internal::wasm::SimdShuffle::TryMatch32x2Shuffle (const uint8_t * shuffle, uint8_t * shuffle32x2) [static]
Definition at line 205 of file simd-shuffle.cc.
                                                            {
  return MatchHelper<2, 4>(shuffle, shuffle32x2);
}
TryMatch32x4OneLaneSwizzle()
bool v8::internal::wasm::SimdShuffle::TryMatch32x4OneLaneSwizzle (const uint8_t * shuffle32x4, uint8_t * from, uint8_t * to) [static]
Definition at line 118 of file simd-shuffle.cc.
                                                               {
  constexpr uint32_t patterns[12]{
      0x30200000, // 0 -> 1
      0x30000100, // 0 -> 2
      0x00020100, // 0 -> 3
      0x03020101, // 1 -> 0
      0x03010100, // 1 -> 2
      0x01020100, // 1 -> 3
      0x03020102, // 2 -> 0
      0x03020200, // 2 -> 1
      0x02020100, // 2 -> 3
      0x03020103, // 3 -> 0
      0x03020300, // 3 -> 1
      0x03030100 // 3 -> 2
  };
  unsigned pattern_idx = 0;
  uint32_t shuffle = *reinterpret_cast<const uint32_t*>(shuffle32x4);
#ifdef V8_TARGET_BIG_ENDIAN
  shuffle = base::bits::ReverseBytes(shuffle);
#endif
  for (unsigned from = 0; from < 4; ++from) {
    for (unsigned to = 0; to < 4; ++to) {
      if (from == to) {
        continue;
      }
      if (shuffle == patterns[pattern_idx]) {
        *from_lane = from;
        *to_lane = to;
        return true;
      }
      ++pattern_idx;
    }
  }
  return false;
}
References v8::base::bits::ReverseBytes().
TryMatch32x4PairwiseReduce()
bool v8::internal::wasm::SimdShuffle::TryMatch32x4PairwiseReduce (const uint8_t * shuffle1, const uint8_t * shuffle2) [static]
Definition at line 361 of file simd-shuffle.cc.
                                                                      {
  return TryMatch32x4Pairwise(shuffle1) && TryMatch32x2Pairwise(shuffle2);
}
References v8::internal::wasm::anonymous_namespace{simd-shuffle.cc}::TryMatch32x2Pairwise(), and v8::internal::wasm::anonymous_namespace{simd-shuffle.cc}::TryMatch32x4Pairwise().
TryMatch32x4Reverse()
bool v8::internal::wasm::SimdShuffle::TryMatch32x4Reverse (const uint8_t * shuffle32x4) [static]
Definition at line 113 of file simd-shuffle.cc.
                                                                {
  return shuffle32x4[0] == 3 && shuffle32x4[1] == 2 && shuffle32x4[2] == 1 &&
         shuffle32x4[3] == 0;
}
TryMatch32x4Rotate()
bool v8::internal::wasm::SimdShuffle::TryMatch32x4Rotate (const uint8_t * shuffle, uint8_t * shuffle32x4, bool is_swizzle) [static]
Definition at line 94 of file simd-shuffle.cc.
                                                                            {
  uint8_t offset;
  bool is_concat = TryMatchConcat(shuffle, &offset);
  DCHECK_NE(offset, 0); // 0 is identity, it should not be matched.
  // Since we already have a concat shuffle, we know that the indices goes from:
  // [ offset, ..., 15, 0, ... ], it suffices to check that the offset points
  // to the low byte of a 32x4 element.
  if (!is_concat || !is_swizzle || offset % 4 != 0) {
    return false;
  }
  uint8_t offset_32 = offset / 4;
  for (int i = 0; i < 4; i++) {
    shuffle32x4[i] = (offset_32 + i) % 4;
  }
  return true;
}
References DCHECK_NE, v8::internal::anonymous_namespace{json-stringifier.cc}::i, and TryMatchConcat().
TryMatch32x4Shuffle()
bool v8::internal::wasm::SimdShuffle::TryMatch32x4Shuffle (const uint8_t * shuffle, uint8_t * shuffle32x4) [static]
Definition at line 210 of file simd-shuffle.cc.
                                                            {
  return MatchHelper<4, 4>(shuffle, shuffle32x4);
}
TryMatch32x4UpperToLowerReduce()
bool v8::internal::wasm::SimdShuffle::TryMatch32x4UpperToLowerReduce (const uint8_t * shuffle1, const uint8_t * shuffle2) [static]
Definition at line 355 of file simd-shuffle.cc.
                                                                          {
  return TryMatchUpperToLowerFirst(shuffle1) &&
         TryMatchUpperToLowerSecond(shuffle2);
}
References v8::internal::wasm::anonymous_namespace{simd-shuffle.cc}::TryMatchUpperToLowerFirst(), and v8::internal::wasm::anonymous_namespace{simd-shuffle.cc}::TryMatchUpperToLowerSecond().
TryMatch32x8Shuffle()
bool v8::internal::wasm::SimdShuffle::TryMatch32x8Shuffle (const uint8_t * shuffle, uint8_t * shuffle32x8) [static]
Definition at line 215 of file simd-shuffle.cc.
                                                            {
  return MatchHelper<8, 4>(shuffle, shuffle32x8);
}
TryMatch64x1Shuffle()
bool v8::internal::wasm::SimdShuffle::TryMatch64x1Shuffle (const uint8_t * shuffle, uint8_t * shuffle64x1) [static]
Definition at line 195 of file simd-shuffle.cc.
                                                            {
  return MatchHelper<1, 8>(shuffle, shuffle64x1);
}
TryMatch64x2Reduce()
bool v8::internal::wasm::SimdShuffle::TryMatch64x2Reduce (const uint8_t * shuffle64x2) [static]
Definition at line 366 of file simd-shuffle.cc.
                                                               {
  return shuffle64x2[0] == 1;
}
TryMatch64x2Shuffle()
bool v8::internal::wasm::SimdShuffle::TryMatch64x2Shuffle (const uint8_t * shuffle, uint8_t * shuffle64x2) [static]
Definition at line 157 of file simd-shuffle.cc.
                                                            {
  constexpr std::array<std::array<uint8_t, 8>, 4> element_patterns = {
      {{0, 1, 2, 3, 4, 5, 6, 7},
       {8, 9, 10, 11, 12, 13, 14, 15},
       {16, 17, 18, 19, 20, 21, 22, 23},
       {24, 25, 26, 27, 28, 29, 30, 31}}};
  for (unsigned i = 0; i < 2; ++i) {
    uint64_t element = *reinterpret_cast<const uint64_t*>(&shuffle[i * 8]);
    for (unsigned j = 0; j < 4; ++j) {
      uint64_t pattern =
          *reinterpret_cast<const uint64_t*>(element_patterns[j].data());
      if (pattern == element) {
        shuffle64x2[i] = j;
        break;
      }
      if (j == 3) {
        return false;
      }
    }
  }
  return true;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i.
TryMatch8x16UpperToLowerReduce()
bool v8::internal::wasm::SimdShuffle::TryMatch8x16UpperToLowerReduce (const uint8_t * shuffle1, const uint8_t * shuffle2, const uint8_t * shuffle3, const uint8_t * shuffle4) [static]
Definition at line 337 of file simd-shuffle.cc.
                                                                          {
  return TryMatchUpperToLowerFirst(shuffle1) &&
         TryMatchUpperToLowerSecond(shuffle2) &&
         TryMatchUpperToLowerThird(shuffle3) &&
         TryMatchUpperToLowerFourth(shuffle4);
}
References v8::internal::wasm::anonymous_namespace{simd-shuffle.cc}::TryMatchUpperToLowerFirst(), v8::internal::wasm::anonymous_namespace{simd-shuffle.cc}::TryMatchUpperToLowerFourth(), v8::internal::wasm::anonymous_namespace{simd-shuffle.cc}::TryMatchUpperToLowerSecond(), and v8::internal::wasm::anonymous_namespace{simd-shuffle.cc}::TryMatchUpperToLowerThird().
TryMatchBlend()
bool v8::internal::wasm::SimdShuffle::TryMatchBlend (const uint8_t * shuffle) [static]
Definition at line 257 of file simd-shuffle.cc.
                                                      {
  for (int i = 0; i < 16; ++i) {
    if ((shuffle[i] & 0xF) != i) return false;
  }
  return true;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i.
TryMatchByteToDwordZeroExtend()
bool v8::internal::wasm::SimdShuffle::TryMatchByteToDwordZeroExtend (const uint8_t * shuffle) [static]
Definition at line 264 of file simd-shuffle.cc.
                                                                      {
  for (int i = 0; i < 16; ++i) {
    if ((i % 4 != 0) && (shuffle[i] < 16)) return false;
    if ((i % 4 == 0) && (shuffle[i] > 15 || (shuffle[i] != shuffle[0] + i / 4)))
      return false;
  }
  return true;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i.
TryMatchCanonical()
SimdShuffle::CanonicalShuffle v8::internal::wasm::SimdShuffle::TryMatchCanonical (const ShuffleArray & shuffle) [static]
Definition at line 29 of file simd-shuffle.cc.
                                 {
  using CanonicalShuffleList =
      std::array<std::pair<const ShuffleArray, const CanonicalShuffle>,
                 static_cast<size_t>(CanonicalShuffle::kMaxShuffles) - 1>;
  static constexpr CanonicalShuffleList canonical_shuffle_list = {{
      {expand<2>({0, 1}), CanonicalShuffle::kIdentity},
      {expand<2>({0, 2}), CanonicalShuffle::kS64x2Even},
      {expand<2>({1, 3}), CanonicalShuffle::kS64x2Odd},
      {expand<2>({1, 0}), CanonicalShuffle::kS64x2Reverse},
      {expand<4>({0, 2, 4, 6}), CanonicalShuffle::kS32x4Even},
      {expand<4>({1, 3, 5, 7}), CanonicalShuffle::kS32x4Odd},
      {expand<4>({0, 4, 1, 5}), CanonicalShuffle::kS32x4InterleaveLowHalves},
      {expand<4>({2, 6, 3, 7}), CanonicalShuffle::kS32x4InterleaveHighHalves},
      {expand<4>({3, 2, 1, 0}), CanonicalShuffle::kS32x4Reverse},
      {expand<4>({0, 4, 2, 6}), CanonicalShuffle::kS32x4TransposeEven},
      {expand<4>({1, 5, 3, 7}), CanonicalShuffle::kS32x4TransposeOdd},
      {expand<4>({1, 0, 3, 2}), CanonicalShuffle::kS32x2Reverse},
      {expand<8>({0, 2, 4, 6, 8, 10, 12, 14}), CanonicalShuffle::kS16x8Even},
      {expand<8>({1, 3, 5, 7, 9, 11, 13, 15}), CanonicalShuffle::kS16x8Odd},
      {expand<8>({0, 8, 1, 9, 2, 10, 3, 11}),
       CanonicalShuffle::kS16x8InterleaveLowHalves},
      {expand<8>({4, 12, 5, 13, 6, 14, 7, 15}),
       CanonicalShuffle::kS16x8InterleaveHighHalves},
      {expand<8>({0, 8, 2, 10, 4, 12, 6, 14}),
       CanonicalShuffle::kS16x8TransposeEven},
      {expand<8>({1, 9, 3, 11, 5, 13, 7, 15}),
       CanonicalShuffle::kS16x8TransposeOdd},
      {expand<8>({1, 0, 3, 2, 5, 4, 7, 6}), CanonicalShuffle::kS16x2Reverse},
      {expand<8>({3, 2, 1, 0, 7, 6, 5, 4}), CanonicalShuffle::kS16x4Reverse},
      {{7, 6, 5, 4, 3, 2, 1, 0, 15, 14, 13, 12, 11, 10, 9, 8},
       CanonicalShuffle::kS64x2ReverseBytes},
      {{3, 2, 1, 0, 7, 6, 5, 4, 11, 10, 9, 8, 15, 14, 13, 12},
       CanonicalShuffle::kS32x4ReverseBytes},
      {{1, 0, 3, 2, 5, 4, 7, 6, 9, 8, 11, 10, 13, 12, 15, 14},
       CanonicalShuffle::kS16x8ReverseBytes},
      {{0, 16, 1, 17, 2, 18, 3, 19, 4, 20, 5, 21, 6, 22, 7, 23},
       CanonicalShuffle::kS8x16InterleaveLowHalves},
      {{8, 24, 9, 25, 10, 26, 11, 27, 12, 28, 13, 29, 14, 30, 15, 31},
       CanonicalShuffle::kS8x16InterleaveHighHalves},
      {{0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30},
       CanonicalShuffle::kS8x16Even},
      {{1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31},
       CanonicalShuffle::kS8x16Odd},
      {{0, 16, 2, 18, 4, 20, 6, 22, 8, 24, 10, 26, 12, 28, 14, 30},
       CanonicalShuffle::kS8x16TransposeEven},
      {{1, 17, 3, 19, 5, 21, 7, 23, 9, 25, 11, 27, 13, 29, 15, 31},
       CanonicalShuffle::kS8x16TransposeOdd},
  }};
  for (auto& [lanes, canonical] : canonical_shuffle_list) {
    if (std::equal(lanes.begin(), lanes.end(), shuffle.begin())) {
      return canonical;
    }
  }
  return CanonicalShuffle::kUnknown;
}
References v8::internal::equal, kIdentity, kMaxShuffles, kS16x2Reverse, kS16x4Reverse, kS16x8Even, kS16x8InterleaveHighHalves, kS16x8InterleaveLowHalves, kS16x8Odd, kS16x8ReverseBytes, kS16x8TransposeEven, kS16x8TransposeOdd, kS32x2Reverse, kS32x4Even, kS32x4InterleaveHighHalves, kS32x4InterleaveLowHalves, kS32x4Odd, kS32x4Reverse, kS32x4ReverseBytes, kS32x4TransposeEven, kS32x4TransposeOdd, kS64x2Even, kS64x2Odd, kS64x2Reverse, kS64x2ReverseBytes, kS8x16Even, kS8x16InterleaveHighHalves, kS8x16InterleaveLowHalves, kS8x16Odd, kS8x16TransposeEven, kS8x16TransposeOdd, and kUnknown.
TryMatchConcat()
bool v8::internal::wasm::SimdShuffle::TryMatchConcat (const uint8_t * shuffle, uint8_t * offset) [static]
Definition at line 240 of file simd-shuffle.cc.
                                                                        {
  // Don't match the identity shuffle (e.g. [0 1 2 ... 15]).
  uint8_t start = shuffle[0];
  if (start == 0) return false;
  DCHECK_GT(kSimd128Size, start); // The shuffle should be canonicalized.
  // A concatenation is a series of consecutive indices, with at most one jump
  // in the middle from the last lane to the first.
  for (int i = 1; i < kSimd128Size; ++i) {
    if ((shuffle[i]) != ((shuffle[i - 1] + 1))) {
      if (shuffle[i - 1] != 15) return false;
      if (shuffle[i] % kSimd128Size != 0) return false;
    }
  }
  *offset = start;
  return true;
}
References DCHECK_GT, v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::kSimd128Size.
Referenced by TryMatch32x4Rotate().
TryMatchSplat()
template<int LANES>
static bool v8::internal::wasm::SimdShuffle::TryMatchSplat (const uint8_t * shuffle, int * index) [inline], [static]
Definition at line 104 of file simd-shuffle.h.
                                                                {
    const int kBytesPerLane = kSimd128Size / LANES;
    // Get the first lane's worth of bytes and check that indices start at a
    // lane boundary and are consecutive.
    uint8_t lane0[kBytesPerLane];
    lane0[0] = shuffle[0];
    if (lane0[0] % kBytesPerLane != 0) return false;
    for (int i = 1; i < kBytesPerLane; ++i) {
      lane0[i] = shuffle[i];
      if (lane0[i] != lane0[0] + i) return false;
    }
    // Now check that the other lanes are identical to lane0.
    for (int i = 1; i < LANES; ++i) {
      for (int j = 0; j < kBytesPerLane; ++j) {
        if (lane0[j] != shuffle[i * kBytesPerLane + j]) return false;
      }
    }
    *index = lane0[0] / kBytesPerLane;
    return true;
  }
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, and v8::internal::kSimd128Size.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/simd-shuffle.h
/mnt/V8SourceCode/src/wasm/simd-shuffle.cc