v8::internal::SlotBase< Subclass, Data, SlotDataAlignment > Class Template Reference
#include <slots.h>
Public Types
using TData = Data
Public Member Functions
Subclass & operator++ ()
Subclass operator++ (int)
Subclass & operator-- ()
Subclass operator-- (int)
bool operator< (const SlotBase &other) const
bool operator<= (const SlotBase &other) const
bool operator> (const SlotBase &other) const
bool operator>= (const SlotBase &other) const
bool operator== (const SlotBase &other) const
bool operator!= (const SlotBase &other) const
size_t operator- (const SlotBase &other) const
Subclass operator- (int i) const
Subclass operator+ (int i) const
Subclass & operator+= (int i)
Subclass operator- (int i)
Subclass & operator-= (int i)
void * ToVoidPtr () const
Address address () const
TData * location () const
Static Public Attributes
static constexpr size_t kSlotDataSize = sizeof(Data)
static constexpr size_t kSlotDataAlignment = SlotDataAlignment
Protected Member Functions
SlotBase (Address ptr)
Private Attributes
Address ptr_
Friends
Subclass operator+ (int i, const Subclass &slot)
Detailed Description
template<typename Subclass, typename Data, size_t SlotDataAlignment = sizeof(Data)>
class v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >
Definition at line 25 of file slots.h.
Member Typedef Documentation
TData
template<typename Subclass , typename Data , size_t SlotDataAlignment = sizeof(Data)>
using v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::TData = Data
Definition at line 27 of file slots.h.
Constructor & Destructor Documentation
SlotBase()
template<typename Subclass , typename Data , size_t SlotDataAlignment = sizeof(Data)>
v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::SlotBase (Address ptr) [inline], [explicit], [protected]
Definition at line 83 of file slots.h.
                                 : ptr_(ptr) {
    DCHECK(IsAligned(ptr, kSlotDataAlignment));
  }
References v8::internal::DCHECK(), and IsAligned().
Member Function Documentation
address()
template<typename Subclass , typename Data , size_t SlotDataAlignment = sizeof(Data)>
Address v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::address () const [inline]
Definition at line 78 of file slots.h.
{ return ptr_; }
Referenced by v8::internal::MarkCompactCollector::SharedHeapObjectVisitor::CheckForSharedObject(), v8::internal::WriteBarrier::CombinedWriteBarrierInternal(), v8::internal::V8HeapExplorer::ExtractDescriptorArrayReferences(), v8::internal::PretenuringHandler::FindAllocationMemento(), v8::internal::WriteBarrier::ForEphemeronHashTable(), v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointersVisitor::LogUpdatedCodePointerTableEntry(), v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointersVisitor::LogUpdatedExternalPointerTableEntry(), v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointersVisitor::LogUpdatedPointer(), v8::internal::WriteBarrier::MarkingFromCode(), v8::internal::WriteBarrier::MarkingSlow(), v8::internal::WriteBarrier::MarkingSlowFromCppHeapWrappable(), v8::internal::WriteBarrier::SharedSlow(), v8::internal::MarkCompactCollector::UpdatePointersInClientHeap(), v8::internal::anonymous_namespace{mark-compact.cc}::UpdateStrongCodeSlot(), v8::internal::anonymous_namespace{mark-compact.cc}::RememberedSetUpdatingItem::UpdateUntypedOldToOldPointers(), v8::internal::anonymous_namespace{mark-compact.cc}::RememberedSetUpdatingItem::UpdateUntypedTrustedToTrustedPointers(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitCppHeapPointer(), v8::internal::ScavengeVisitor::VisitExternalPointer(), v8::internal::IterateAndScavengePromotedObjectsVisitor::VisitExternalPointer(), v8::internal::Serializer::ObjectSerializer::VisitExternalPointer(), v8::internal::Serializer::ObjectSerializer::VisitIndirectPointer(), v8::internal::Serializer::ObjectSerializer::VisitPointers(), v8::internal::Serializer::ObjectSerializer::VisitProtectedPointer(), and v8::internal::IndexedReferencesExtractor::VisitSlotImpl().
location()
template<typename Subclass , typename Data , size_t SlotDataAlignment = sizeof(Data)>
TData* v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::location () const [inline]
Definition at line 80 of file slots.h.
{ return reinterpret_cast<TData*>(ptr_); }
Referenced by v8::internal::TracedHandles::Copy(), v8::internal::CustomArguments< T >::GetReturnValue(), v8::internal::GlobalizeTracedReference(), v8::internal::ReadOnlyHeap::InitializeFromIsolateRoots(), v8::internal::ReadOnlyHeap::InitializeIsolateRoots(), v8::internal::MemsetPointer(), v8::internal::MemsetTagged(), v8::internal::anonymous_namespace{traced-handles.cc}::ClearWeaknessProcessor::ProcessBlock(), v8::internal::Serializer::SerializeRootObject(), and v8::internal::anonymous_namespace{frames.cc}::VisitSpillSlot().
operator!=()
template<typename Subclass , typename Data , size_t SlotDataAlignment = sizeof(Data)>
bool v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::operator!= (const SlotBase< Subclass, Data, SlotDataAlignment > & other) const [inline]
Definition at line 56 of file slots.h.
{ return ptr_ != other.ptr_; }
References v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::ptr_.
operator+()
template<typename Subclass , typename Data , size_t SlotDataAlignment = sizeof(Data)>
Subclass v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::operator+ (int i) const [inline]
Definition at line 62 of file slots.h.
{ return Subclass(ptr_ + i * kSlotDataSize); }
operator++() [1/2]
template<typename Subclass , typename Data , size_t SlotDataAlignment = sizeof(Data)>
Subclass& v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::operator++ () [inline]
Definition at line 32 of file slots.h.
                         { // Prefix increment.
    ptr_ += kSlotDataSize;
    return *static_cast<Subclass*>(this);
  }
operator++() [2/2]
template<typename Subclass , typename Data , size_t SlotDataAlignment = sizeof(Data)>
Subclass v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::operator++ (int) [inline]
Definition at line 36 of file slots.h.
                           { // Postfix increment.
    Subclass result = *static_cast<Subclass*>(this);
    ptr_ += kSlotDataSize;
    return result;
  }
References v8::base::internal::result.
operator+=()
template<typename Subclass , typename Data , size_t SlotDataAlignment = sizeof(Data)>
Subclass& v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::operator+= (int i) [inline]
Definition at line 66 of file slots.h.
                              {
    ptr_ += i * kSlotDataSize;
    return *static_cast<Subclass*>(this);
  }
operator-() [1/3]
template<typename Subclass , typename Data , size_t SlotDataAlignment = sizeof(Data)>
size_t v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::operator- (const SlotBase< Subclass, Data, SlotDataAlignment > & other) const [inline]
Definition at line 57 of file slots.h.
                                                {
    DCHECK_GE(ptr_, other.ptr_);
    return static_cast<size_t>((ptr_ - other.ptr_) / kSlotDataSize);
  }
References DCHECK_GE, and v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::ptr_.
operator-() [2/3]
template<typename Subclass , typename Data , size_t SlotDataAlignment = sizeof(Data)>
Subclass v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::operator- (int i) [inline]
Definition at line 70 of file slots.h.
{ return Subclass(ptr_ - i * kSlotDataSize); }
operator-() [3/3]
template<typename Subclass , typename Data , size_t SlotDataAlignment = sizeof(Data)>
Subclass v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::operator- (int i) const [inline]
Definition at line 61 of file slots.h.
{ return Subclass(ptr_ - i * kSlotDataSize); }
operator--() [1/2]
template<typename Subclass , typename Data , size_t SlotDataAlignment = sizeof(Data)>
Subclass& v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::operator-- () [inline]
Definition at line 41 of file slots.h.
                         { // Prefix decrement.
    ptr_ -= kSlotDataSize;
    return *static_cast<Subclass*>(this);
  }
operator--() [2/2]
template<typename Subclass , typename Data , size_t SlotDataAlignment = sizeof(Data)>
Subclass v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::operator-- (int) [inline]
Definition at line 45 of file slots.h.
                           { // Postfix decrement.
    Subclass result = *static_cast<Subclass*>(this);
    ptr_ -= kSlotDataSize;
    return result;
  }
References v8::base::internal::result.
operator-=()
template<typename Subclass , typename Data , size_t SlotDataAlignment = sizeof(Data)>
Subclass& v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::operator-= (int i) [inline]
Definition at line 71 of file slots.h.
                              {
    ptr_ -= i * kSlotDataSize;
    return *static_cast<Subclass*>(this);
  }
operator<()
template<typename Subclass , typename Data , size_t SlotDataAlignment = sizeof(Data)>
bool v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::operator< (const SlotBase< Subclass, Data, SlotDataAlignment > & other) const [inline]
Definition at line 51 of file slots.h.
{ return ptr_ < other.ptr_; }
References v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::ptr_.
operator<=()
template<typename Subclass , typename Data , size_t SlotDataAlignment = sizeof(Data)>
bool v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::operator<= (const SlotBase< Subclass, Data, SlotDataAlignment > & other) const [inline]
Definition at line 52 of file slots.h.
{ return ptr_ <= other.ptr_; }
References v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::ptr_.
operator==()
template<typename Subclass , typename Data , size_t SlotDataAlignment = sizeof(Data)>
bool v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::operator== (const SlotBase< Subclass, Data, SlotDataAlignment > & other) const [inline]
Definition at line 55 of file slots.h.
{ return ptr_ == other.ptr_; }
References v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::ptr_.
operator>()
template<typename Subclass , typename Data , size_t SlotDataAlignment = sizeof(Data)>
bool v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::operator> (const SlotBase< Subclass, Data, SlotDataAlignment > & other) const [inline]
Definition at line 53 of file slots.h.
{ return ptr_ > other.ptr_; }
References v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::ptr_.
operator>=()
template<typename Subclass , typename Data , size_t SlotDataAlignment = sizeof(Data)>
bool v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::operator>= (const SlotBase< Subclass, Data, SlotDataAlignment > & other) const [inline]
Definition at line 54 of file slots.h.
{ return ptr_ >= other.ptr_; }
References v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::ptr_.
ToVoidPtr()
template<typename Subclass , typename Data , size_t SlotDataAlignment = sizeof(Data)>
void* v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::ToVoidPtr () const [inline]
Definition at line 76 of file slots.h.
{ return reinterpret_cast<void*>(address()); }
Friends And Related Function Documentation
operator+
template<typename Subclass , typename Data , size_t SlotDataAlignment = sizeof(Data)>
Subclass operator+ (int i, const Subclass & slot) [friend]
Definition at line 63 of file slots.h.
                                                         {
    return Subclass(slot.ptr_ + i * kSlotDataSize);
  }
Member Data Documentation
kSlotDataAlignment
template<typename Subclass , typename Data , size_t SlotDataAlignment = sizeof(Data)>
constexpr size_t v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::kSlotDataAlignment = SlotDataAlignment [static], [constexpr]
Definition at line 30 of file slots.h.
kSlotDataSize
template<typename Subclass , typename Data , size_t SlotDataAlignment = sizeof(Data)>
constexpr size_t v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::kSlotDataSize = sizeof(Data) [static], [constexpr]
Definition at line 29 of file slots.h.
ptr_
template<typename Subclass , typename Data , size_t SlotDataAlignment = sizeof(Data)>
Address v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::ptr_ [private]
Definition at line 91 of file slots.h.
Referenced by v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::operator!=(), v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::operator-(), v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::operator<(), v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::operator<=(), v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::operator==(), v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::operator>(), and v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::operator>=().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/slots.h