v8::internal::compiler::OptionalOperator Class Reference
#include <machine-operator.h>
Public Member Functions
OptionalOperator (bool supported, const Operator *op)
bool IsSupported () const
const Operator * op () const
const Operator * placeholder () const
Private Attributes
bool supported_
const Operator *const op_
Detailed Description
Definition at line 29 of file machine-operator.h.
Constructor & Destructor Documentation
OptionalOperator()
v8::internal::compiler::OptionalOperator::OptionalOperator (bool supported, const Operator * op) [inline]
Definition at line 31 of file machine-operator.h.
      : supported_(supported), op_(op) {}
Member Function Documentation
IsSupported()
bool v8::internal::compiler::OptionalOperator::IsSupported () const [inline]
Definition at line 34 of file machine-operator.h.
{ return supported_; }
References supported_.
Referenced by v8::internal::compiler::CodeAssembler::IsFloat64RoundDownSupported(), v8::internal::compiler::CodeAssembler::IsFloat64RoundTiesEvenSupported(), v8::internal::compiler::CodeAssembler::IsFloat64RoundTruncateSupported(), v8::internal::compiler::CodeAssembler::IsFloat64RoundUpSupported(), v8::internal::compiler::CodeAssembler::IsInt32AbsWithOverflowSupported(), v8::internal::compiler::CodeAssembler::IsInt64AbsWithOverflowSupported(), v8::internal::compiler::CodeAssembler::IsTruncateFloat64ToFloat16RawBitsSupported(), v8::internal::compiler::CodeAssembler::IsWord32CtzSupported(), v8::internal::compiler::CodeAssembler::IsWord32PopcntSupported(), v8::internal::compiler::CodeAssembler::IsWord64CtzSupported(), and v8::internal::compiler::CodeAssembler::IsWord64PopcntSupported().
op()
const Operator* v8::internal::compiler::OptionalOperator::op () const [inline]
Definition at line 36 of file machine-operator.h.
                             {
    DCHECK(supported_);
    return op_;
  }
References v8::internal::DCHECK(), op_, and supported_.
placeholder()
const Operator* v8::internal::compiler::OptionalOperator::placeholder () const [inline]
Definition at line 42 of file machine-operator.h.
{ return op_; }
References op_.
Referenced by v8::internal::compiler::RepresentationChanger::Float64OperatorFor().
Member Data Documentation
op_
const Operator* const v8::internal::compiler::OptionalOperator::op_ [private]
Definition at line 46 of file machine-operator.h.
Referenced by op(), and placeholder().
supported_
bool v8::internal::compiler::OptionalOperator::supported_ [private]
Definition at line 45 of file machine-operator.h.
Referenced by IsSupported(), and op().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/machine-operator.h