v8::internal::HeapGraphEdge Class Reference
#include <heap-snapshot-generator.h>
Public Types
enum Type {
kContextVariable = v8::HeapGraphEdge::kContextVariable
, kElement = v8::HeapGraphEdge::kElement
, kProperty = v8::HeapGraphEdge::kProperty
, kInternal = v8::HeapGraphEdge::kInternal
,
kHidden = v8::HeapGraphEdge::kHidden
, kShortcut = v8::HeapGraphEdge::kShortcut
, kWeak = v8::HeapGraphEdge::kWeak
 }
Public Member Functions
HeapGraphEdge (Type type, const char *name, HeapEntry *from, HeapEntry *to)
HeapGraphEdge (Type type, int index, HeapEntry *from, HeapEntry *to)
Type type () const
int index () const
const char * name () const
HeapEntry * from () const
HeapEntry * to () const
Isolate * isolate () const
Private Types
using TypeField = base::BitField< Type, 0, 3 >
using FromIndexField = base::BitField< int, 3, 29 >
Private Member Functions
HeapSnapshot * snapshot () const
int from_index () const
Private Attributes
uint32_t bit_field_
HeapEntry * to_entry_
xx xx xx xx xx xx xx xx xx
union {
 int index_
 const char * name_
};
Detailed Description
Definition at line 61 of file heap-snapshot-generator.h.
Member Typedef Documentation
FromIndexField
using v8::internal::HeapGraphEdge::FromIndexField = base::BitField<int, 3, 29> [private]
Definition at line 96 of file heap-snapshot-generator.h.
TypeField
using v8::internal::HeapGraphEdge::TypeField = base::BitField<Type, 0, 3> [private]
Definition at line 95 of file heap-snapshot-generator.h.
Member Enumeration Documentation
Type
enum v8::internal::HeapGraphEdge::Type
Enumerator
kContextVariable
kElement
kProperty
kInternal
kHidden
kShortcut
kWeak
Definition at line 63 of file heap-snapshot-generator.h.
            {
    kContextVariable = v8::HeapGraphEdge::kContextVariable,
    kElement = v8::HeapGraphEdge::kElement,
    kProperty = v8::HeapGraphEdge::kProperty,
    kInternal = v8::HeapGraphEdge::kInternal,
    kHidden = v8::HeapGraphEdge::kHidden,
    kShortcut = v8::HeapGraphEdge::kShortcut,
    kWeak = v8::HeapGraphEdge::kWeak
  };
Constructor & Destructor Documentation
HeapGraphEdge() [1/2]
v8::internal::HeapGraphEdge::HeapGraphEdge (Type type, const char * name, HeapEntry * from, HeapEntry * to)
Definition at line 210 of file heap-snapshot-generator.cc.
    : bit_field_(TypeField::encode(type) |
                 FromIndexField::encode(from->index())),
      to_entry_(to),
      name_(name) {
  DCHECK(type == kContextVariable || type == kProperty || type == kInternal ||
         type == kShortcut || type == kWeak);
}
References v8::internal::DCHECK(), kContextVariable, kInternal, kProperty, kShortcut, kWeak, and type().
HeapGraphEdge() [2/2]
v8::internal::HeapGraphEdge::HeapGraphEdge (Type type, int index, HeapEntry * from, HeapEntry * to)
Definition at line 220 of file heap-snapshot-generator.cc.
    : bit_field_(TypeField::encode(type) |
                 FromIndexField::encode(from->index())),
      to_entry_(to),
      index_(index) {
  DCHECK(type == kElement || type == kHidden);
}
References v8::internal::DCHECK(), kElement, kHidden, and type().
Member Function Documentation
from()
HeapEntry * v8::internal::HeapGraphEdge::from () const [inline]
Definition at line 17 of file heap-snapshot-generator-inl.h.
                                     {
  return &snapshot()->entries()[from_index()];
}
References v8::internal::HeapSnapshot::entries(), from_index(), and snapshot().
from_index()
int v8::internal::HeapGraphEdge::from_index () const [inline], [private]
Definition at line 93 of file heap-snapshot-generator.h.
{ return FromIndexField::decode(bit_field_); }
References bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by from().
index()
int v8::internal::HeapGraphEdge::index () const [inline]
Definition at line 77 of file heap-snapshot-generator.h.
                    {
    DCHECK(type() == kElement || type() == kHidden);
    return index_;
  }
References v8::internal::DCHECK(), index_, kElement, kHidden, and type().
Referenced by v8::HeapGraphEdge::GetName(), v8::internal::HeapEntry::Print(), and v8::internal::HeapSnapshotJSONSerializer::SerializeEdge().
isolate()
Isolate * v8::internal::HeapGraphEdge::isolate () const [inline]
Definition at line 21 of file heap-snapshot-generator-inl.h.
{ return to_entry_->isolate(); }
References v8::internal::HeapEntry::isolate(), and to_entry_.
Referenced by v8::HeapGraphEdge::GetName().
name()
const char* v8::internal::HeapGraphEdge::name () const [inline]
Definition at line 81 of file heap-snapshot-generator.h.
                           {
    DCHECK(type() == kContextVariable || type() == kProperty ||
           type() == kInternal || type() == kShortcut || type() == kWeak);
    return name_;
  }
References v8::internal::DCHECK(), kContextVariable, kInternal, kProperty, kShortcut, kWeak, name_, and type().
Referenced by v8::HeapGraphEdge::GetName(), v8::internal::HeapEntry::Print(), and v8::internal::HeapSnapshotJSONSerializer::SerializeEdge().
snapshot()
HeapSnapshot * v8::internal::HeapGraphEdge::snapshot () const [inline], [private]
Definition at line 23 of file heap-snapshot-generator-inl.h.
                                            {
  return to_entry_->snapshot();
}
References v8::internal::HeapEntry::snapshot(), and to_entry_.
Referenced by from().
to()
HeapEntry* v8::internal::HeapGraphEdge::to () const [inline]
Definition at line 87 of file heap-snapshot-generator.h.
{ return to_entry_; }
References to_entry_.
Referenced by v8::internal::HeapEntry::Print(), and v8::internal::HeapSnapshotJSONSerializer::SerializeEdge().
type()
Type v8::internal::HeapGraphEdge::type () const [inline]
Definition at line 76 of file heap-snapshot-generator.h.
{ return TypeField::decode(bit_field_); }
References bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::HeapGraphEdge::GetName(), HeapGraphEdge(), index(), name(), v8::internal::HeapEntry::Print(), and v8::internal::HeapSnapshotJSONSerializer::SerializeEdge().
Member Data Documentation
union { ... } [private]
bit_field_
uint32_t v8::internal::HeapGraphEdge::bit_field_ [private]
Definition at line 97 of file heap-snapshot-generator.h.
Referenced by from_index(), and type().
index_
int v8::internal::HeapGraphEdge::index_
Definition at line 100 of file heap-snapshot-generator.h.
Referenced by index().
name_
const char* v8::internal::HeapGraphEdge::name_
Definition at line 101 of file heap-snapshot-generator.h.
Referenced by name().
to_entry_
HeapEntry* v8::internal::HeapGraphEdge::to_entry_ [private]
Definition at line 98 of file heap-snapshot-generator.h.
Referenced by isolate(), snapshot(), and to().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/profiler/heap-snapshot-generator.h
/mnt/V8SourceCode/src/profiler/heap-snapshot-generator-inl.h
/mnt/V8SourceCode/src/profiler/heap-snapshot-generator.cc