v8::base::DiscriminatedUnion< TagEnum, Ts > Class Template Reference
#include <discriminated-union.h>
Public Types
using Tag = TagEnum
Public Member Functions
DiscriminatedUnion (DiscriminatedUnion &&other) V8_NOEXCEPT=default
DiscriminatedUnion (const DiscriminatedUnion &other) V8_NOEXCEPT=default
DiscriminatedUnion & operator= (DiscriminatedUnion &&other) V8_NOEXCEPT=default
DiscriminatedUnion & operator= (const DiscriminatedUnion &other) V8_NOEXCEPT=default
template<typename T >
constexpr DiscriminatedUnion (Tag tag, T &&data) V8_NOEXCEPT
template<typename T >
constexpr DiscriminatedUnion (T &&data) V8_NOEXCEPT
constexpr Tag tag () const
template<Tag tag>
constexpr const auto & get () const
template<Tag tag>
constexpr auto & get ()
template<typename T >
constexpr const auto & get () const
template<typename T >
constexpr auto & get ()
Private Attributes
char data_ [std::max({sizeof(Ts)...})]
uint8_t tag_
Detailed Description
template<typename TagEnum, typename... Ts>
class v8::base::DiscriminatedUnion< TagEnum, Ts >
Definition at line 40 of file discriminated-union.h.
Member Typedef Documentation
Tag
template<typename TagEnum , typename... Ts>
using v8::base::DiscriminatedUnion< TagEnum, Ts >::Tag = TagEnum
Definition at line 46 of file discriminated-union.h.
Constructor & Destructor Documentation
DiscriminatedUnion() [1/4]
template<typename TagEnum , typename... Ts>
v8::base::DiscriminatedUnion< TagEnum, Ts >::DiscriminatedUnion (DiscriminatedUnion< TagEnum, Ts > && other) [default]
DiscriminatedUnion() [2/4]
template<typename TagEnum , typename... Ts>
v8::base::DiscriminatedUnion< TagEnum, Ts >::DiscriminatedUnion (const DiscriminatedUnion< TagEnum, Ts > & other) [default]
DiscriminatedUnion() [3/4]
template<typename TagEnum , typename... Ts>
template<typename T >
constexpr v8::base::DiscriminatedUnion< TagEnum, Ts >::DiscriminatedUnion (Tag tag, T && data) [inline], [explicit], [constexpr]
Definition at line 59 of file discriminated-union.h.
                                                                       {
    constexpr size_t index = index_of_type_v<std::decay_t<T>, Ts...>;
    static_assert(index < sizeof...(Ts));
    static_assert(index < std::numeric_limits<uint8_t>::max());
    // TODO(leszeks): Support unions with repeated types.
    DCHECK_EQ(tag, static_cast<Tag>(index));
    tag_ = static_cast<uint8_t>(index);
    new (data_) T(std::forward<T>(data));
  }
References v8::base::DiscriminatedUnion< TagEnum, Ts >::data_, DCHECK_EQ, v8::internal::index, T, v8::base::DiscriminatedUnion< TagEnum, Ts >::tag(), and v8::base::DiscriminatedUnion< TagEnum, Ts >::tag_.
DiscriminatedUnion() [4/4]
template<typename TagEnum , typename... Ts>
template<typename T >
constexpr v8::base::DiscriminatedUnion< TagEnum, Ts >::DiscriminatedUnion (T && data) [inline], [explicit], [constexpr]
Definition at line 71 of file discriminated-union.h.
                                                              {
    constexpr size_t index = index_of_type_v<std::decay_t<T>, Ts...>;
    static_assert(index < sizeof...(Ts));
    static_assert(index < std::numeric_limits<uint8_t>::max());
    tag_ = static_cast<uint8_t>(index);
    new (data_) T(std::forward<T>(data));
  }
References v8::base::DiscriminatedUnion< TagEnum, Ts >::data_, v8::internal::index, T, and v8::base::DiscriminatedUnion< TagEnum, Ts >::tag_.
Member Function Documentation
get() [1/4]
template<typename TagEnum , typename... Ts>
template<Tag tag>
constexpr auto& v8::base::DiscriminatedUnion< TagEnum, Ts >::get () [inline], [constexpr]
Definition at line 91 of file discriminated-union.h.
                        {
    using T = nth_type_t<static_cast<size_t>(tag), Ts...>;
    DCHECK_EQ(tag, this->tag());
    return *reinterpret_cast<T*>(data_);
  }
References v8::base::DiscriminatedUnion< TagEnum, Ts >::data_, DCHECK_EQ, and v8::base::DiscriminatedUnion< TagEnum, Ts >::tag().
get() [2/4]
template<typename TagEnum , typename... Ts>
template<typename T >
constexpr auto& v8::base::DiscriminatedUnion< TagEnum, Ts >::get () [inline], [constexpr]
Definition at line 106 of file discriminated-union.h.
                        {
    DCHECK_EQ(static_cast<Tag>(index_of_type_v<T, Ts...>), this->tag());
    return *reinterpret_cast<T*>(data_);
  }
References v8::base::DiscriminatedUnion< TagEnum, Ts >::data_, DCHECK_EQ, and v8::base::DiscriminatedUnion< TagEnum, Ts >::tag().
get() [3/4]
template<typename TagEnum , typename... Ts>
template<Tag tag>
constexpr const auto& v8::base::DiscriminatedUnion< TagEnum, Ts >::get () const [inline], [constexpr]
Definition at line 83 of file discriminated-union.h.
                                    {
    using T = nth_type_t<static_cast<size_t>(tag), Ts...>;
    DCHECK_EQ(tag, this->tag());
    return *reinterpret_cast<const T*>(data_);
  }
References v8::base::DiscriminatedUnion< TagEnum, Ts >::data_, DCHECK_EQ, and v8::base::DiscriminatedUnion< TagEnum, Ts >::tag().
Referenced by v8::internal::maglev::InterpretedDeoptFrame::data(), v8::internal::maglev::InlinedArgumentsDeoptFrame::data(), v8::internal::maglev::ConstructInvokeStubDeoptFrame::data(), v8::internal::maglev::BuiltinContinuationDeoptFrame::data(), v8::internal::maglev::MaglevGraphBuilder::GetDeoptFrameForLazyDeoptHelper(), and v8::internal::maglev::MaglevGraphBuilder::GetLatestCheckpointedFrame().
get() [4/4]
template<typename TagEnum , typename... Ts>
template<typename T >
constexpr const auto& v8::base::DiscriminatedUnion< TagEnum, Ts >::get () const [inline], [constexpr]
Definition at line 99 of file discriminated-union.h.
                                    {
    DCHECK_EQ(static_cast<Tag>(index_of_type_v<T, Ts...>), this->tag());
    return *reinterpret_cast<const T*>(data_);
  }
References v8::base::DiscriminatedUnion< TagEnum, Ts >::data_, DCHECK_EQ, and v8::base::DiscriminatedUnion< TagEnum, Ts >::tag().
operator=() [1/2]
template<typename TagEnum , typename... Ts>
DiscriminatedUnion& v8::base::DiscriminatedUnion< TagEnum, Ts >::operator= (const DiscriminatedUnion< TagEnum, Ts > & other) [default]
operator=() [2/2]
template<typename TagEnum , typename... Ts>
DiscriminatedUnion& v8::base::DiscriminatedUnion< TagEnum, Ts >::operator= (DiscriminatedUnion< TagEnum, Ts > && other) [default]
tag()
template<typename TagEnum , typename... Ts>
constexpr Tag v8::base::DiscriminatedUnion< TagEnum, Ts >::tag () const [inline], [constexpr]
Definition at line 79 of file discriminated-union.h.
{ return static_cast<Tag>(tag_); }
References v8::base::DiscriminatedUnion< TagEnum, Ts >::tag_.
Referenced by v8::base::DiscriminatedUnion< TagEnum, Ts >::DiscriminatedUnion(), v8::base::DiscriminatedUnion< TagEnum, Ts >::get(), v8::internal::maglev::MaglevGraphBuilder::GetDeoptFrameForLazyDeoptHelper(), v8::internal::maglev::MaglevGraphBuilder::GetLatestCheckpointedFrame(), v8::internal::maglev::DeoptFrame::IsJsFrame(), and v8::internal::maglev::DeoptFrame::type().
Member Data Documentation
data_
template<typename TagEnum , typename... Ts>
char v8::base::DiscriminatedUnion< TagEnum, Ts >::data_[std::max({sizeof(Ts)...})] [private]
Definition at line 112 of file discriminated-union.h.
Referenced by v8::base::DiscriminatedUnion< TagEnum, Ts >::DiscriminatedUnion(), and v8::base::DiscriminatedUnion< TagEnum, Ts >::get().
tag_
template<typename TagEnum , typename... Ts>
uint8_t v8::base::DiscriminatedUnion< TagEnum, Ts >::tag_ [private]
Definition at line 114 of file discriminated-union.h.
Referenced by v8::base::DiscriminatedUnion< TagEnum, Ts >::DiscriminatedUnion(), and v8::base::DiscriminatedUnion< TagEnum, Ts >::tag().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/base/discriminated-union.h