v8::internal::CpuProfileJSONSerializer Class Reference
#include <profile-generator.h>
Public Member Functions
CpuProfileJSONSerializer (CpuProfile *profile)
CpuProfileJSONSerializer (const CpuProfileJSONSerializer &)=delete
CpuProfileJSONSerializer & operator= (const CpuProfileJSONSerializer &)=delete
void Serialize (v8::OutputStream *stream)
Private Member Functions
void SerializePositionTicks (const v8::CpuProfileNode *node, int lineCount)
void SerializeCallFrame (const v8::CpuProfileNode *node)
void SerializeChildren (const v8::CpuProfileNode *node, int childrenCount)
void SerializeNode (const v8::CpuProfileNode *node)
void SerializeNodes ()
void SerializeSamples ()
void SerializeTimeDeltas ()
void SerializeImpl ()
Private Attributes
CpuProfile * profile_
OutputStreamWriter * writer_
Static Private Attributes
static const int kEdgeFieldsCount
static const int kNodeFieldsCount
Detailed Description
Definition at line 614 of file profile-generator.h.
Constructor & Destructor Documentation
CpuProfileJSONSerializer() [1/2]
v8::internal::CpuProfileJSONSerializer::CpuProfileJSONSerializer (CpuProfile * profile) [inline], [explicit]
Definition at line 616 of file profile-generator.h.
      : profile_(profile), writer_(nullptr) {}
CpuProfileJSONSerializer() [2/2]
v8::internal::CpuProfileJSONSerializer::CpuProfileJSONSerializer (const CpuProfileJSONSerializer &) [delete]
Member Function Documentation
operator=()
CpuProfileJSONSerializer& v8::internal::CpuProfileJSONSerializer::operator= (const CpuProfileJSONSerializer &) [delete]
Serialize()
void v8::internal::CpuProfileJSONSerializer::Serialize (v8::OutputStream * stream)
Definition at line 800 of file profile-generator.cc.
                                                               {
  DCHECK_NULL(writer_);
  writer_ = new OutputStreamWriter(stream);
  SerializeImpl();
  delete writer_;
  writer_ = nullptr;
}
References DCHECK_NULL, SerializeImpl(), and writer_.
Referenced by v8::CpuProfile::Serialize().
SerializeCallFrame()
void v8::internal::CpuProfileJSONSerializer::SerializeCallFrame (const v8::CpuProfileNode * node) [private]
Definition at line 824 of file profile-generator.cc.
                                  {
  writer_->AddString("\"functionName\":\"");
  writer_->AddString(node->GetFunctionNameStr());
  writer_->AddString("\",\"lineNumber\":");
  writer_->AddNumber(node->GetLineNumber() - 1);
  writer_->AddString(",\"columnNumber\":");
  writer_->AddNumber(node->GetColumnNumber() - 1);
  writer_->AddString(",\"scriptId\":");
  writer_->AddNumber(node->GetScriptId());
  writer_->AddString(",\"url\":\"");
  writer_->AddString(node->GetScriptResourceNameStr());
  writer_->AddCharacter('"');
}
References v8::internal::OutputStreamWriter::AddCharacter(), v8::internal::OutputStreamWriter::AddNumber(), v8::internal::OutputStreamWriter::AddString(), v8::CpuProfileNode::GetColumnNumber(), v8::CpuProfileNode::GetFunctionNameStr(), v8::CpuProfileNode::GetLineNumber(), v8::CpuProfileNode::GetScriptId(), v8::CpuProfileNode::GetScriptResourceNameStr(), and writer_.
Referenced by SerializeNode().
SerializeChildren()
void v8::internal::CpuProfileJSONSerializer::SerializeChildren (const v8::CpuProfileNode * node, int childrenCount) [private]
Definition at line 839 of file profile-generator.cc.
                                                                    {
  for (int i = 0; i < childrenCount; i++) {
    writer_->AddNumber(node->GetChild(i)->GetNodeId());
    if (i != (childrenCount - 1)) writer_->AddCharacter(',');
  }
}
References v8::internal::OutputStreamWriter::AddCharacter(), v8::internal::OutputStreamWriter::AddNumber(), v8::CpuProfileNode::GetChild(), v8::CpuProfileNode::GetNodeId(), and writer_.
Referenced by SerializeNode().
SerializeImpl()
void v8::internal::CpuProfileJSONSerializer::SerializeImpl () [private]
Definition at line 914 of file profile-generator.cc.
                                             {
  writer_->AddCharacter('{');
  writer_->AddString("\"nodes\":[");
  SerializeNodes();
  writer_->AddString("]");
  writer_->AddString(",\"startTime\":");
  writer_->AddNumber(static_cast<unsigned>(
      profile_->start_time().since_origin().InMicroseconds()));
  writer_->AddString(",\"endTime\":");
  writer_->AddNumber(static_cast<unsigned>(
      profile_->end_time().since_origin().InMicroseconds()));
  writer_->AddString(",\"samples\":[");
  SerializeSamples();
  if (writer_->aborted()) return;
  writer_->AddCharacter(']');
  writer_->AddString(",\"timeDeltas\":[");
  SerializeTimeDeltas();
  if (writer_->aborted()) return;
  writer_->AddString("]");
  writer_->AddCharacter('}');
  writer_->Finalize();
}
References v8::internal::OutputStreamWriter::aborted(), v8::internal::OutputStreamWriter::AddCharacter(), v8::internal::OutputStreamWriter::AddNumber(), v8::internal::OutputStreamWriter::AddString(), v8::internal::CpuProfile::end_time(), v8::internal::OutputStreamWriter::Finalize(), v8::base::TimeDelta::InMicroseconds(), profile_, SerializeNodes(), SerializeSamples(), SerializeTimeDeltas(), v8::base::time_internal::TimeBase< TimeClass >::since_origin(), v8::internal::CpuProfile::start_time(), and writer_.
Referenced by Serialize().
SerializeNode()
void v8::internal::CpuProfileJSONSerializer::SerializeNode (const v8::CpuProfileNode * node) [private]
Definition at line 847 of file profile-generator.cc.
                                                                         {
  writer_->AddCharacter('{');
  writer_->AddString("\"id\":");
  writer_->AddNumber(node->GetNodeId());
  writer_->AddString(",\"hitCount\":");
  writer_->AddNumber(node->GetHitCount());
  writer_->AddString(",\"callFrame\":{");
  SerializeCallFrame(node);
  writer_->AddCharacter('}');
  const int childrenCount = node->GetChildrenCount();
  if (childrenCount) {
    writer_->AddString(",\"children\":[");
    SerializeChildren(node, childrenCount);
    writer_->AddCharacter(']');
  }
  const char* deoptReason = node->GetBailoutReason();
  if (deoptReason && deoptReason[0] && strcmp(deoptReason, "no reason")) {
    writer_->AddString(",\"deoptReason\":\"");
    writer_->AddString(deoptReason);
    writer_->AddCharacter('"');
  }
  unsigned lineCount = node->GetHitLineCount();
  if (lineCount) {
    writer_->AddString(",\"positionTicks\":[");
    SerializePositionTicks(node, lineCount);
    writer_->AddCharacter(']');
  }
  writer_->AddCharacter('}');
}
References v8::internal::OutputStreamWriter::AddCharacter(), v8::internal::OutputStreamWriter::AddNumber(), v8::internal::OutputStreamWriter::AddString(), v8::CpuProfileNode::GetBailoutReason(), v8::CpuProfileNode::GetChildrenCount(), v8::CpuProfileNode::GetHitCount(), v8::CpuProfileNode::GetHitLineCount(), v8::CpuProfileNode::GetNodeId(), SerializeCallFrame(), SerializeChildren(), SerializePositionTicks(), and writer_.
Referenced by SerializeNodes().
SerializeNodes()
void v8::internal::CpuProfileJSONSerializer::SerializeNodes () [private]
Definition at line 882 of file profile-generator.cc.
                                              {
  std::vector<const v8::CpuProfileNode*> nodes;
  FlattenNodesTree(
      reinterpret_cast<const v8::CpuProfileNode*>(profile_->top_down()->root()),
      &nodes);
  for (size_t i = 0; i < nodes.size(); i++) {
    SerializeNode(nodes.at(i));
    if (writer_->aborted()) return;
    if (i != (nodes.size() - 1)) writer_->AddCharacter(',');
  }
}
References v8::internal::OutputStreamWriter::aborted(), v8::internal::OutputStreamWriter::AddCharacter(), v8::internal::anonymous_namespace{profile-generator.cc}::FlattenNodesTree(), profile_, v8::internal::ProfileTree::root(), SerializeNode(), v8::internal::CpuProfile::top_down(), and writer_.
Referenced by SerializeImpl().
SerializePositionTicks()
void v8::internal::CpuProfileJSONSerializer::SerializePositionTicks (const v8::CpuProfileNode * node, int lineCount) [private]
Definition at line 808 of file profile-generator.cc.
                                                 {
  std::vector<v8::CpuProfileNode::LineTick> entries(lineCount);
  if (node->GetLineTicks(&entries[0], lineCount)) {
    for (int i = 0; i < lineCount; i++) {
      writer_->AddCharacter('{');
      writer_->AddString("\"line\":");
      writer_->AddNumber(entries[i].line);
      writer_->AddString(",\"ticks\":");
      writer_->AddNumber(entries[i].hit_count);
      writer_->AddCharacter('}');
      if (i != (lineCount - 1)) writer_->AddCharacter(',');
    }
  }
}
References v8::internal::OutputStreamWriter::AddCharacter(), v8::internal::OutputStreamWriter::AddNumber(), v8::internal::OutputStreamWriter::AddString(), v8::CpuProfileNode::GetLineTicks(), and writer_.
Referenced by SerializeNode().
SerializeSamples()
void v8::internal::CpuProfileJSONSerializer::SerializeSamples () [private]
Definition at line 906 of file profile-generator.cc.
                                                {
  int count = profile_->samples_count();
  for (int i = 0; i < count; i++) {
    writer_->AddNumber(profile_->sample(i).node->id());
    if (i != (count - 1)) writer_->AddString(",");
  }
}
References v8::internal::OutputStreamWriter::AddNumber(), v8::internal::OutputStreamWriter::AddString(), v8::internal::ProfileNode::id(), v8::internal::CpuProfile::SampleInfo::node, profile_, v8::internal::CpuProfile::sample(), v8::internal::CpuProfile::samples_count(), and writer_.
Referenced by SerializeImpl().
SerializeTimeDeltas()
void v8::internal::CpuProfileJSONSerializer::SerializeTimeDeltas () [private]
Definition at line 895 of file profile-generator.cc.
                                                   {
  int count = profile_->samples_count();
  uint64_t lastTime = profile_->start_time().since_origin().InMicroseconds();
  for (int i = 0; i < count; i++) {
    uint64_t ts = profile_->sample(i).timestamp.since_origin().InMicroseconds();
    writer_->AddNumber(static_cast<int>(ts - lastTime));
    if (i != (count - 1)) writer_->AddString(",");
    lastTime = ts;
  }
}
References v8::internal::OutputStreamWriter::AddNumber(), v8::internal::OutputStreamWriter::AddString(), v8::base::TimeDelta::InMicroseconds(), profile_, v8::internal::CpuProfile::sample(), v8::internal::CpuProfile::samples_count(), v8::base::time_internal::TimeBase< TimeClass >::since_origin(), v8::internal::CpuProfile::start_time(), v8::internal::CpuProfile::SampleInfo::timestamp, and writer_.
Referenced by SerializeImpl().
Member Data Documentation
kEdgeFieldsCount
const int v8::internal::CpuProfileJSONSerializer::kEdgeFieldsCount [static], [private]
Definition at line 632 of file profile-generator.h.
kNodeFieldsCount
const int v8::internal::CpuProfileJSONSerializer::kNodeFieldsCount [static], [private]
Definition at line 633 of file profile-generator.h.
profile_
CpuProfile* v8::internal::CpuProfileJSONSerializer::profile_ [private]
Definition at line 635 of file profile-generator.h.
Referenced by SerializeImpl(), SerializeNodes(), SerializeSamples(), and SerializeTimeDeltas().
writer_
OutputStreamWriter* v8::internal::CpuProfileJSONSerializer::writer_ [private]
Definition at line 636 of file profile-generator.h.
Referenced by Serialize(), SerializeCallFrame(), SerializeChildren(), SerializeImpl(), SerializeNode(), SerializeNodes(), SerializePositionTicks(), SerializeSamples(), and SerializeTimeDeltas().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/profiler/profile-generator.h
/mnt/V8SourceCode/src/profiler/profile-generator.cc