v8::internal::JSTemporalDuration Class Reference
#include <js-temporal-objects.h>
Static Public Member Functions
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalDuration > Constructor (Isolate *isolate, DirectHandle< JSFunction > target, DirectHandle< HeapObject > new_target, DirectHandle< Object > years, DirectHandle< Object > months, DirectHandle< Object > weeks, DirectHandle< Object > days, DirectHandle< Object > hours, DirectHandle< Object > minutes, DirectHandle< Object > seconds, DirectHandle< Object > milliseconds, DirectHandle< Object > microseconds, DirectHandle< Object > nanoseconds)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Smi > Compare (Isolate *isolate, DirectHandle< Object > one, DirectHandle< Object > two, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalDuration > From (Isolate *isolate, DirectHandle< Object > item)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Smi > Sign (Isolate *isolate, DirectHandle< JSTemporalDuration > duration)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Oddball > Blank (Isolate *isolate, DirectHandle< JSTemporalDuration > duration)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalDuration > Negated (Isolate *isolate, DirectHandle< JSTemporalDuration > duration)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalDuration > Abs (Isolate *isolate, DirectHandle< JSTemporalDuration > duration)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalDuration > Add (Isolate *isolate, DirectHandle< JSTemporalDuration > duration, DirectHandle< Object > other, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalDuration > Subtract (Isolate *isolate, DirectHandle< JSTemporalDuration > duration, DirectHandle< Object > other, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalDuration > Round (Isolate *isolate, DirectHandle< JSTemporalDuration > duration, DirectHandle< Object > round_to_obj)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > Total (Isolate *isolate, DirectHandle< JSTemporalDuration > duration, DirectHandle< Object > total_of)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > ToJSON (Isolate *isolate, DirectHandle< JSTemporalDuration > duration)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > ToLocaleString (Isolate *isolate, DirectHandle< JSTemporalDuration > duration, DirectHandle< Object > locales, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > ToString (Isolate *isolate, DirectHandle< JSTemporalDuration > duration, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalDuration > With (Isolate *isolate, DirectHandle< JSTemporalDuration > duration, DirectHandle< Object > temporal_duration_like)
Detailed Description
Definition at line 81 of file js-temporal-objects.h.
Member Function Documentation
Abs()
MaybeDirectHandle< JSTemporalDuration > v8::internal::JSTemporalDuration::Abs (Isolate * isolate, DirectHandle< JSTemporalDuration > duration) [static]
Definition at line 1621 of file js-temporal-objects.cc.
                                                                 {
  return ConstructRustWrappingType<JSTemporalDuration>(
      isolate, CONSTRUCTOR(duration), CONSTRUCTOR(duration),
      duration->duration()->raw()->abs());
}
References CONSTRUCTOR, and v8::internal::duration.
Add()
MaybeDirectHandle< JSTemporalDuration > v8::internal::JSTemporalDuration::Add (Isolate * isolate, DirectHandle< JSTemporalDuration > duration, DirectHandle< Object > other, DirectHandle< Object > options) [static]
Definition at line 1629 of file js-temporal-objects.cc.
                                                              {
  const char method_name[] = "Temporal.Duration.prototype.add";
  DirectHandle<JSTemporalDuration> other_duration;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, other_duration,
      temporal::ToTemporalDuration(isolate, other, method_name));
  auto result =
      duration->duration()->raw()->add(*other_duration->duration()->raw());
  return ConstructRustWrappingType<JSTemporalDuration>(
      isolate, CONSTRUCTOR(instant), CONSTRUCTOR(instant), std::move(result));
}
References ASSIGN_RETURN_ON_EXCEPTION, CONSTRUCTOR, v8::internal::duration, v8::base::internal::result, and v8::internal::temporal::ToTemporalDuration().
Blank()
MaybeDirectHandle< Oddball > v8::internal::JSTemporalDuration::Blank (Isolate * isolate, DirectHandle< JSTemporalDuration > duration) [static]
Definition at line 1606 of file js-temporal-objects.cc.
                                                                 {
  return isolate->factory()->ToBoolean(duration->duration()->raw()->sign() ==
                                       temporal_rs::Sign::Zero);
}
References v8::internal::duration, v8::internal::Isolate::factory(), and v8::internal::FactoryBase< Impl >::ToBoolean().
Compare()
MaybeDirectHandle< Smi > v8::internal::JSTemporalDuration::Compare (Isolate * isolate, DirectHandle< Object > one, DirectHandle< Object > two, DirectHandle< Object > options) [static]
Definition at line 1522 of file js-temporal-objects.cc.
                                                                    {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
Referenced by v8::internal::BUILTIN().
Constructor()
MaybeDirectHandle< JSTemporalDuration > v8::internal::JSTemporalDuration::Constructor (Isolate * isolate, DirectHandle< JSFunction > target, DirectHandle< HeapObject > new_target, DirectHandle< Object > years, DirectHandle< Object > months, DirectHandle< Object > weeks, DirectHandle< Object > days, DirectHandle< Object > hours, DirectHandle< Object > minutes, DirectHandle< Object > seconds, DirectHandle< Object > milliseconds, DirectHandle< Object > microseconds, DirectHandle< Object > nanoseconds) [static]
Definition at line 1438 of file js-temporal-objects.cc.
                                      {
  // 1. If NewTarget is undefined, then
  if (IsUndefined(*new_target)) {
    // a. Throw a TypeError exception.
    THROW_NEW_ERROR(isolate,
                    NewTypeError(MessageTemplate::kMethodInvokedOnWrongType,
                                 isolate->factory()->NewStringFromAsciiChecked(
                                     "Temporal.Duration")));
  }
  // 2. Let y be ? ToIntegerIfIntegral(years).
  double y;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, y, temporal::ToIntegerIfIntegral(isolate, years),
      DirectHandle<JSTemporalDuration>());
  // 3. Let mo be ? ToIntegerIfIntegral(months).
  double mo;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, mo, temporal::ToIntegerIfIntegral(isolate, months),
      DirectHandle<JSTemporalDuration>());
  // 4. Let w be ? ToIntegerIfIntegral(weeks).
  double w;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, w, temporal::ToIntegerIfIntegral(isolate, weeks),
      DirectHandle<JSTemporalDuration>());
  // 5. Let d be ? ToIntegerIfIntegral(days).
  double d;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, d, temporal::ToIntegerIfIntegral(isolate, days),
      DirectHandle<JSTemporalDuration>());
  // 6. Let h be ? ToIntegerIfIntegral(hours).
  double h;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, h, temporal::ToIntegerIfIntegral(isolate, hours),
      DirectHandle<JSTemporalDuration>());
  // 7. Let m be ? ToIntegerIfIntegral(minutes).
  double m;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, m, temporal::ToIntegerIfIntegral(isolate, minutes),
      DirectHandle<JSTemporalDuration>());
  // 8. Let s be ? ToIntegerIfIntegral(seconds).
  double s;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, s, temporal::ToIntegerIfIntegral(isolate, seconds),
      DirectHandle<JSTemporalDuration>());
  // 9. Let ms be ? ToIntegerIfIntegral(milliseconds).
  double ms;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, ms, temporal::ToIntegerIfIntegral(isolate, milliseconds),
      DirectHandle<JSTemporalDuration>());
  // 10. Let mis be ? ToIntegerIfIntegral(microseconds).
  double mis;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, mis, temporal::ToIntegerIfIntegral(isolate, microseconds),
      DirectHandle<JSTemporalDuration>());
  // 11. Let ns be ? ToIntegerIfIntegral(nanoseconds).
  double ns;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, ns, temporal::ToIntegerIfIntegral(isolate, nanoseconds),
      DirectHandle<JSTemporalDuration>());
  // 12. Return ?CreateTemporalDuration(y, mo, w, d, h, m, s, ms, mis, ns,
  // NewTarget).
  return ConstructRustWrappingType<JSTemporalDuration>(
      isolate, CONSTRUCTOR(duration), CONSTRUCTOR(duration),
      temporal_rs::Duration::create(y, mo, w, d, h, m, s, ms, mis, ms));
}
References CONSTRUCTOR, v8::internal::duration, v8::internal::Isolate::factory(), h(), MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::microseconds, v8::internal::nanoseconds, v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), v8::internal::seconds, THROW_NEW_ERROR, v8::internal::temporal::ToIntegerIfIntegral(), and v8::internal::y.
Referenced by v8::internal::BUILTIN().
From()
MaybeDirectHandle< JSTemporalDuration > v8::internal::JSTemporalDuration::From (Isolate * isolate, DirectHandle< Object > item) [static]
Definition at line 1529 of file js-temporal-objects.cc.
                                                 {
  const char method_name[] = "Temporal.Duration.from";
  return temporal::ToTemporalDuration(isolate, item, method_name);
}
References v8::internal::temporal::ToTemporalDuration().
Negated()
MaybeDirectHandle< JSTemporalDuration > v8::internal::JSTemporalDuration::Negated (Isolate * isolate, DirectHandle< JSTemporalDuration > duration) [static]
Definition at line 1613 of file js-temporal-objects.cc.
                                                                 {
  return ConstructRustWrappingType<JSTemporalDuration>(
      isolate, CONSTRUCTOR(duration), CONSTRUCTOR(duration),
      duration->duration()->raw()->negated());
}
References CONSTRUCTOR, and v8::internal::duration.
Round()
MaybeDirectHandle< JSTemporalDuration > v8::internal::JSTemporalDuration::Round (Isolate * isolate, DirectHandle< JSTemporalDuration > duration, DirectHandle< Object > round_to_obj) [static]
Definition at line 1537 of file js-temporal-objects.cc.
                                       {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
Sign()
MaybeDirectHandle< Smi > v8::internal::JSTemporalDuration::Sign (Isolate * isolate, DirectHandle< JSTemporalDuration > duration) [static]
Definition at line 1599 of file js-temporal-objects.cc.
                                                                 {
  auto sign = duration->duration()->raw()->sign();
  return direct_handle(Smi::FromInt((temporal_rs::Sign::Value)sign), isolate);
}
References v8::internal::direct_handle(), v8::internal::duration, v8::internal::Smi::FromInt(), and v8::internal::sign.
Subtract()
MaybeDirectHandle< JSTemporalDuration > v8::internal::JSTemporalDuration::Subtract (Isolate * isolate, DirectHandle< JSTemporalDuration > duration, DirectHandle< Object > other, DirectHandle< Object > options) [static]
Definition at line 1646 of file js-temporal-objects.cc.
                                                              {
  const char method_name[] = "Temporal.Duration.prototype.subtract";
  DirectHandle<JSTemporalDuration> other_duration;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, other_duration,
      temporal::ToTemporalDuration(isolate, other, method_name));
  auto result =
      duration->duration()->raw()->subtract(*other_duration->duration()->raw());
  return ConstructRustWrappingType<JSTemporalDuration>(
      isolate, CONSTRUCTOR(instant), CONSTRUCTOR(instant), std::move(result));
}
References ASSIGN_RETURN_ON_EXCEPTION, CONSTRUCTOR, v8::internal::duration, v8::base::internal::result, and v8::internal::temporal::ToTemporalDuration().
ToJSON()
MaybeDirectHandle< String > v8::internal::JSTemporalDuration::ToJSON (Isolate * isolate, DirectHandle< JSTemporalDuration > duration) [static]
Definition at line 1663 of file js-temporal-objects.cc.
                                                                 {
  return temporal::TemporalDurationToString(isolate, duration,
                                            std::move(temporal::kToStringAuto));
}
References v8::internal::duration, v8::internal::temporal::kToStringAuto, and v8::internal::temporal::TemporalDurationToString().
ToLocaleString()
MaybeDirectHandle< String > v8::internal::JSTemporalDuration::ToLocaleString (Isolate * isolate, DirectHandle< JSTemporalDuration > duration, DirectHandle< Object > locales, DirectHandle< Object > options) [static]
Definition at line 1670 of file js-temporal-objects.cc.
                                                                {
  return temporal::TemporalDurationToString(isolate, duration,
                                            std::move(temporal::kToStringAuto));
}
References v8::internal::duration, v8::internal::temporal::kToStringAuto, and v8::internal::temporal::TemporalDurationToString().
ToString()
MaybeDirectHandle< String > v8::internal::JSTemporalDuration::ToString (Isolate * isolate, DirectHandle< JSTemporalDuration > duration, DirectHandle< Object > options) [static]
Definition at line 1678 of file js-temporal-objects.cc.
                                      {
  const char method_name[] = "Temporal.Duration.prototype.toString";
  // 3. Let resolvedOptions be ?GetOptionsObject(options).
  DirectHandle<JSReceiver> options;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, options, GetOptionsObject(isolate, options_obj, method_name));
  // 5. Let digits be ?GetTemporalFractionalSecondDigitsOption(resolvedOptions).
  temporal_rs::Precision digits;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, digits,
      temporal::GetTemporalFractionalSecondDigitsOption(isolate, options,
                                                        method_name),
      DirectHandle<String>());
  // 6. Let roundingMode be ? GetRoundingModeOption(resolvedOptions, trunc).
  RoundingMode rounding_mode;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, rounding_mode,
      temporal::GetRoundingModeOption(isolate, options, RoundingMode::Trunc,
                                      method_name),
      DirectHandle<String>());
  // 7. Let smallestUnit be ? GetTemporalUnitValuedOption(resolvedOptions,
  // "smallestUnit", time, unset).
  std::optional<Unit> smallest_unit;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, smallest_unit,
      temporal::GetTemporalUnit(isolate, options, "smallestUnit",
                                UnitGroup::kTime, std::nullopt, false,
                                method_name),
      DirectHandle<String>());
  // 8-17 performed by Rust
  auto rust_options = temporal_rs::ToStringRoundingOptions{
      .precision = digits,
      .smallest_unit = smallest_unit,
      .rounding_mode = rounding_mode,
  };
  return temporal::TemporalDurationToString(isolate, duration,
                                            std::move(rust_options));
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::duration, v8::internal::GetOptionsObject(), v8::internal::temporal::GetRoundingModeOption(), v8::internal::temporal::GetTemporalFractionalSecondDigitsOption(), v8::internal::temporal::GetTemporalUnit(), MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, and v8::internal::temporal::TemporalDurationToString().
Total()
MaybeDirectHandle< Object > v8::internal::JSTemporalDuration::Total (Isolate * isolate, DirectHandle< JSTemporalDuration > duration, DirectHandle< Object > total_of) [static]
Definition at line 1544 of file js-temporal-objects.cc.
                                       {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
With()
MaybeDirectHandle< JSTemporalDuration > v8::internal::JSTemporalDuration::With (Isolate * isolate, DirectHandle< JSTemporalDuration > duration, DirectHandle< Object > temporal_duration_like) [static]
Definition at line 1551 of file js-temporal-objects.cc.
                                                 {
  temporal_rs::PartialDuration partial;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, partial,
      temporal::ToTemporalPartialDurationRecord(isolate,
                                                temporal_duration_like),
      DirectHandle<JSTemporalDuration>());
  if (!partial.years.has_value()) {
    partial.years = duration->duration()->raw()->years();
  }
  if (!partial.months.has_value()) {
    partial.months = duration->duration()->raw()->months();
  }
  if (!partial.months.has_value()) {
    partial.months = duration->duration()->raw()->months();
  }
  if (!partial.weeks.has_value()) {
    partial.weeks = duration->duration()->raw()->weeks();
  }
  if (!partial.days.has_value()) {
    partial.days = duration->duration()->raw()->days();
  }
  if (!partial.hours.has_value()) {
    partial.hours = duration->duration()->raw()->hours();
  }
  if (!partial.minutes.has_value()) {
    partial.minutes = duration->duration()->raw()->minutes();
  }
  if (!partial.seconds.has_value()) {
    partial.seconds = duration->duration()->raw()->seconds();
  }
  if (!partial.milliseconds.has_value()) {
    partial.milliseconds = duration->duration()->raw()->milliseconds();
  }
  if (!partial.microseconds.has_value()) {
    partial.microseconds = duration->duration()->raw()->microseconds();
  }
  if (!partial.nanoseconds.has_value()) {
    partial.nanoseconds = duration->duration()->raw()->nanoseconds();
  }
  return ConstructRustWrappingType<JSTemporalDuration>(
      isolate, CONSTRUCTOR(duration), CONSTRUCTOR(duration),
      temporal_rs::Duration::from_partial_duration(partial));
}
References CONSTRUCTOR, v8::internal::duration, MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, and v8::internal::temporal::ToTemporalPartialDurationRecord().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-temporal-objects.h
/mnt/V8SourceCode/src/objects/js-temporal-objects.cc