v8::internal::TaggedIndex Class Reference
#include <tagged-index.h>
Static Public Member Functions
static Tagged< TaggedIndex > FromIntptr (intptr_t value)
static constexpr bool IsValid (intptr_t value)
Static Public Attributes
static constexpr int kTaggedValueSize = 31
static constexpr intptr_t kMinValue
static constexpr intptr_t kMaxValue = -(kMinValue + 1)
Detailed Description
Definition at line 36 of file tagged-index.h.
Member Function Documentation
FromIntptr()
static Tagged<TaggedIndex> v8::internal::TaggedIndex::FromIntptr (intptr_t value) [inline], [static]
Definition at line 39 of file tagged-index.h.
                                                               {
    DCHECK(TaggedIndex::IsValid(value));
    return Tagged<TaggedIndex>((static_cast<Address>(value) << kSmiTagSize) |
                               kSmiTag);
  }
References v8::internal::DCHECK(), IsValid(), v8::internal::kSmiTag, v8::internal::kSmiTagSize, and v8::internal::value.
Referenced by v8::internal::baseline::BaselineCompiler::IndexAsTagged(), v8::internal::compiler::OperandGenerator::ToConstant(), and v8::internal::baseline::BaselineCompiler::UintAsTagged().
IsValid()
static constexpr bool v8::internal::TaggedIndex::IsValid (intptr_t value) [inline], [static], [constexpr]
Definition at line 46 of file tagged-index.h.
                                                       {
    return kMinValue <= value && value <= kMaxValue;
  }
References kMaxValue, kMinValue, and v8::internal::value.
Referenced by FromIntptr(), v8::internal::maglev::Graph::GetTaggedIndexConstant(), v8::internal::IsTaggedIndex(), v8::internal::compiler::CodeAssembler::TaggedIndexConstant(), v8::internal::maglev::TaggedIndexConstant::TaggedIndexConstant(), and v8::internal::compiler::OperandGenerator::ToConstant().
Member Data Documentation
kMaxValue
constexpr intptr_t v8::internal::TaggedIndex::kMaxValue = -(kMinValue + 1) [static], [constexpr]
Definition at line 57 of file tagged-index.h.
Referenced by IsValid().
kMinValue
constexpr intptr_t v8::internal::TaggedIndex::kMinValue [static], [constexpr]
Initial value:
=
      static_cast<intptr_t>(kUintptrAllBitsSet << (kTaggedValueSize - 1))
Definition at line 55 of file tagged-index.h.
Referenced by IsValid().
kTaggedValueSize
constexpr int v8::internal::TaggedIndex::kTaggedValueSize = 31 [static], [constexpr]
Definition at line 54 of file tagged-index.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/tagged-index.h