v8::internal::compiler::NodeWrapper Class Reference
#include <node.h>
Public Member Functions
constexpr NodeWrapper (Node *node)
operator Node * () const
Node * operator-> () const
Protected Member Functions
Node * node () const
void set_node (Node *node)
Private Attributes
Node * node_
Detailed Description
Definition at line 320 of file node.h.
Constructor & Destructor Documentation
NodeWrapper()
constexpr v8::internal::compiler::NodeWrapper::NodeWrapper (Node * node) [inline], [explicit], [constexpr]
Definition at line 322 of file node.h.
: node_(node) {}
Member Function Documentation
node()
Node* v8::internal::compiler::NodeWrapper::node () const [inline], [protected]
Definition at line 327 of file node.h.
{ return node_; }
Referenced by v8::internal::compiler::JSCallOrConstructNode::Argument(), v8::internal::compiler::FrameState::context(), v8::internal::compiler::JSNodeWrapperBase::context(), v8::internal::compiler::StartNode::ContextParameterIndex_MaybeNonStandardLayout(), v8::internal::compiler::CommonNodeWrapperBase::control(), v8::internal::compiler::JSNodeWrapperBase::control(), v8::internal::compiler::CommonNodeWrapperBase::effect(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::FastApiCallNode::FastCallArgumentCount(), v8::internal::compiler::JSCallOrConstructNode::feedback_vector(), v8::internal::compiler::StartNode::FormalParameterCount(), v8::internal::compiler::StartNode::FormalParameterCountWithoutReceiver(), v8::internal::compiler::JSNodeWrapperBase::frame_state(), v8::internal::compiler::FrameState::frame_state_info(), v8::internal::compiler::FrameState::FrameState(), v8::internal::compiler::FrameState::function(), v8::internal::compiler::JSCallOrConstructNode::IsValidNode(), v8::internal::compiler::JSBinaryOpNode::JSBinaryOpNode(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::JSCallNodeBase(), v8::internal::compiler::JSCallOrConstructNode::JSCallOrConstructNode(), v8::internal::compiler::JSCloneObjectNode::JSCloneObjectNode(), v8::internal::compiler::JSConstructNodeBase< kOpcode >::JSConstructNodeBase(), v8::internal::compiler::JSCreateClosureNode::JSCreateClosureNode(), v8::internal::compiler::JSCreateEmptyLiteralArrayNode::JSCreateEmptyLiteralArrayNode(), v8::internal::compiler::JSCreateLiteralOpNode::JSCreateLiteralOpNode(), v8::internal::compiler::JSDefineKeyedOwnPropertyInLiteralNode::JSDefineKeyedOwnPropertyInLiteralNode(), v8::internal::compiler::JSDefineKeyedOwnPropertyNode::JSDefineKeyedOwnPropertyNode(), v8::internal::compiler::JSDefineNamedOwnPropertyNode::JSDefineNamedOwnPropertyNode(), v8::internal::compiler::JSFindNonDefaultConstructorOrConstructNode::JSFindNonDefaultConstructorOrConstructNode(), v8::internal::compiler::JSForInNextNode::JSForInNextNode(), v8::internal::compiler::JSForInPrepareNode::JSForInPrepareNode(), v8::internal::compiler::JSGetIteratorNode::JSGetIteratorNode(), v8::internal::compiler::JSGetTemplateObjectNode::JSGetTemplateObjectNode(), v8::internal::compiler::JSHasPropertyNode::JSHasPropertyNode(), v8::internal::compiler::JSLoadGlobalNode::JSLoadGlobalNode(), v8::internal::compiler::JSLoadNamedFromSuperNode::JSLoadNamedFromSuperNode(), v8::internal::compiler::JSLoadNamedNode::JSLoadNamedNode(), v8::internal::compiler::JSLoadPropertyNode::JSLoadPropertyNode(), v8::internal::compiler::JSSetKeyedPropertyNode::JSSetKeyedPropertyNode(), v8::internal::compiler::JSSetNamedPropertyNode::JSSetNamedPropertyNode(), v8::internal::compiler::JSStoreGlobalNode::JSStoreGlobalNode(), v8::internal::compiler::JSStoreInArrayLiteralNode::JSStoreInArrayLiteralNode(), v8::internal::compiler::JSUnaryOpNode::JSUnaryOpNode(), v8::internal::compiler::FrameState::locals(), v8::internal::compiler::FrameState::outer_frame_state(), v8::internal::compiler::FrameState::parameters(), v8::internal::compiler::JSBinaryOpNode::Parameters(), v8::internal::compiler::JSGetIteratorNode::Parameters(), v8::internal::compiler::JSCloneObjectNode::Parameters(), v8::internal::compiler::JSGetTemplateObjectNode::Parameters(), v8::internal::compiler::JSCreateLiteralOpNode::Parameters(), v8::internal::compiler::JSHasPropertyNode::Parameters(), v8::internal::compiler::JSLoadPropertyNode::Parameters(), v8::internal::compiler::JSSetKeyedPropertyNode::Parameters(), v8::internal::compiler::JSDefineKeyedOwnPropertyNode::Parameters(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::compiler::JSConstructNodeBase< kOpcode >::Parameters(), v8::internal::compiler::JSLoadNamedNode::Parameters(), v8::internal::compiler::JSLoadNamedFromSuperNode::Parameters(), v8::internal::compiler::JSSetNamedPropertyNode::Parameters(), v8::internal::compiler::JSDefineNamedOwnPropertyNode::Parameters(), v8::internal::compiler::JSStoreGlobalNode::Parameters(), v8::internal::compiler::JSLoadGlobalNode::Parameters(), v8::internal::compiler::JSCreateEmptyLiteralArrayNode::Parameters(), v8::internal::compiler::JSDefineKeyedOwnPropertyInLiteralNode::Parameters(), v8::internal::compiler::JSStoreInArrayLiteralNode::Parameters(), v8::internal::compiler::JSCreateClosureNode::Parameters(), v8::internal::compiler::JSForInPrepareNode::Parameters(), v8::internal::compiler::JSForInNextNode::Parameters(), v8::internal::compiler::FastApiCallNode::SlowCallArgumentCount(), v8::internal::compiler::FrameState::stack(), and v8::internal::compiler::StartNode::StartNode().
operator Node *()
v8::internal::compiler::NodeWrapper::operator Node * () const [inline]
Definition at line 323 of file node.h.
{ return node_; }
operator->()
Node* v8::internal::compiler::NodeWrapper::operator-> () const [inline]
Definition at line 324 of file node.h.
{ return node_; }
set_node()
void v8::internal::compiler::NodeWrapper::set_node (Node * node) [inline], [protected]
Definition at line 328 of file node.h.
                            {
    DCHECK_NOT_NULL(node);
    node_ = node;
  }
References DCHECK_NOT_NULL.
Member Data Documentation
node_
Node* v8::internal::compiler::NodeWrapper::node_ [private]
Definition at line 334 of file node.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/node.h