v8::internal::TracingAccountingAllocator Class Reference
Public Member Functions
TracingAccountingAllocator (Isolate *isolate)
~TracingAccountingAllocator ()=default
Protected Member Functions
void TraceAllocateSegmentImpl (v8::internal::Segment *segment) override
void TraceZoneCreationImpl (const Zone *zone) override
void TraceZoneDestructionImpl (const Zone *zone) override
Private Member Functions
void UpdateMemoryTrafficAndReportMemoryUsage (size_t memory_traffic_delta)
void Dump (std::ostringstream &out, bool dump_details)
Private Attributes
std::atomic< size_t > nesting_depth_ {0}
base::Mutex mutex_
std::unordered_set< const Zone * > active_zones_
std::ostringstream buffer_
size_t memory_traffic_since_last_report_ = 0
Detailed Description
Definition at line 4024 of file isolate.cc.
Constructor & Destructor Documentation
TracingAccountingAllocator()
v8::internal::TracingAccountingAllocator::TracingAccountingAllocator (Isolate * isolate) [inline], [explicit]
Definition at line 4026 of file isolate.cc.
      : AccountingAllocator(isolate) {}
 TracingAccountingAllocator()
v8::internal::TracingAccountingAllocator::~TracingAccountingAllocator () [default]
Member Function Documentation
Dump()
void v8::internal::TracingAccountingAllocator::Dump (std::ostringstream & out, bool dump_details) [inline], [private]
Definition at line 4101 of file isolate.cc.
                                                      {
    // Note: Neither isolate nor zones are locked, so be careful with accesses
    // as the allocator is potentially used on a concurrent thread.
    double time = isolate()->time_millis_since_init();
    out << "{" << "\"isolate\": \"" << reinterpret_cast<void*>(isolate())
        << "\", " << "\"time\": " << time << ", ";
    size_t total_segment_bytes_allocated = 0;
    size_t total_zone_allocation_size = 0;
    size_t total_zone_freed_size = 0;
    if (dump_details) {
      // Print detailed zone stats if memory usage changes direction.
      out << "\"zones\": [";
      bool first = true;
      for (const Zone* zone : active_zones_) {
        size_t zone_segment_bytes_allocated = zone->segment_bytes_allocated();
        size_t zone_allocation_size = zone->allocation_size_for_tracing();
        size_t freed_size = zone->freed_size_for_tracing();
        if (first) {
          first = false;
        } else {
          out << ", ";
        }
        out << "{" << "\"name\": \"" << zone->name() << "\", "
            << "\"allocated\": " << zone_segment_bytes_allocated << ", "
            << "\"used\": " << zone_allocation_size << ", "
            << "\"freed\": " << freed_size << "}";
        total_segment_bytes_allocated += zone_segment_bytes_allocated;
        total_zone_allocation_size += zone_allocation_size;
        total_zone_freed_size += freed_size;
      }
      out << "], ";
    } else {
      // Just calculate total allocated/used memory values.
      for (const Zone* zone : active_zones_) {
        total_segment_bytes_allocated += zone->segment_bytes_allocated();
        total_zone_allocation_size += zone->allocation_size_for_tracing();
        total_zone_freed_size += zone->freed_size_for_tracing();
      }
    }
    out << "\"allocated\": " << total_segment_bytes_allocated << ", "
        << "\"used\": " << total_zone_allocation_size << ", "
        << "\"freed\": " << total_zone_freed_size << "}";
  }
References v8::internal::Factory::isolate(), v8::internal::time, and v8::internal::Isolate::time_millis_since_init().
TraceAllocateSegmentImpl()
void v8::internal::TracingAccountingAllocator::TraceAllocateSegmentImpl (v8::internal::Segment * segment) [inline], [override], [protected], [virtual]
Reimplemented from v8::internal::AccountingAllocator.
Definition at line 4031 of file isolate.cc.
                                                                     {
    base::MutexGuard lock(&mutex_);
    UpdateMemoryTrafficAndReportMemoryUsage(segment->total_size());
  }
References v8::internal::Segment::total_size().
TraceZoneCreationImpl()
void v8::internal::TracingAccountingAllocator::TraceZoneCreationImpl (const Zone * zone) [inline], [override], [protected], [virtual]
Reimplemented from v8::internal::AccountingAllocator.
Definition at line 4036 of file isolate.cc.
                                                        {
    base::MutexGuard lock(&mutex_);
    active_zones_.insert(zone);
    nesting_depth_++;
  }
TraceZoneDestructionImpl()
void v8::internal::TracingAccountingAllocator::TraceZoneDestructionImpl (const Zone * zone) [inline], [override], [protected], [virtual]
Reimplemented from v8::internal::AccountingAllocator.
Definition at line 4042 of file isolate.cc.
                                                           {
    base::MutexGuard lock(&mutex_);
#ifdef V8_ENABLE_PRECISE_ZONE_STATS
    if (v8_flags.trace_zone_type_stats) {
      type_stats_.MergeWith(zone->type_stats());
    }
#endif
    UpdateMemoryTrafficAndReportMemoryUsage(zone->segment_bytes_allocated());
    active_zones_.erase(zone);
    nesting_depth_--;
#ifdef V8_ENABLE_PRECISE_ZONE_STATS
    if (v8_flags.trace_zone_type_stats && active_zones_.empty()) {
      type_stats_.Dump();
    }
#endif
  }
References v8::internal::Zone::segment_bytes_allocated(), and v8::internal::v8_flags.
UpdateMemoryTrafficAndReportMemoryUsage()
void v8::internal::TracingAccountingAllocator::UpdateMemoryTrafficAndReportMemoryUsage (size_t memory_traffic_delta) [inline], [private]
Definition at line 4061 of file isolate.cc.
                                                                            {
    if (!v8_flags.trace_zone_stats &&
        !(TracingFlags::zone_stats.load(std::memory_order_relaxed) &
          v8::tracing::TracingCategoryObserver::ENABLED_BY_TRACING)) {
      // Don't print anything if the zone tracing was enabled only because of
      // v8_flags.trace_zone_type_stats.
      return;
    }
    memory_traffic_since_last_report_ += memory_traffic_delta;
    if (memory_traffic_since_last_report_ < v8_flags.zone_stats_tolerance)
      return;
    memory_traffic_since_last_report_ = 0;
    Dump(buffer_, true);
    {
      std::string trace_str = buffer_.str();
      if (v8_flags.trace_zone_stats) {
        PrintF(
            "{"
            "\"type\": \"v8-zone-trace\", "
            "\"stats\": %s"
            "}\n",
            trace_str.c_str());
      }
      if (V8_UNLIKELY(
              TracingFlags::zone_stats.load(std::memory_order_relaxed) &
              v8::tracing::TracingCategoryObserver::ENABLED_BY_TRACING)) {
        TRACE_EVENT_INSTANT1(TRACE_DISABLED_BY_DEFAULT("v8.zone_stats"),
                             "V8.Zone_Stats", TRACE_EVENT_SCOPE_THREAD, "stats",
                             TRACE_STR_COPY(trace_str.c_str()));
      }
    }
    // Clear the buffer.
    buffer_.str(std::string());
  }
References v8::tracing::TracingCategoryObserver::ENABLED_BY_TRACING, v8::internal::PrintF(), v8::internal::string, TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT_INSTANT1, TRACE_EVENT_SCOPE_THREAD, TRACE_STR_COPY, v8::internal::v8_flags, V8_UNLIKELY, and v8::internal::TracingFlags::zone_stats.
Member Data Documentation
active_zones_
std::unordered_set<const Zone*> v8::internal::TracingAccountingAllocator::active_zones_ [private]
Definition at line 4149 of file isolate.cc.
buffer_
std::ostringstream v8::internal::TracingAccountingAllocator::buffer_ [private]
Definition at line 4153 of file isolate.cc.
memory_traffic_since_last_report_
size_t v8::internal::TracingAccountingAllocator::memory_traffic_since_last_report_ = 0 [private]
Definition at line 4155 of file isolate.cc.
mutex_
base::Mutex v8::internal::TracingAccountingAllocator::mutex_ [private]
Definition at line 4148 of file isolate.cc.
nesting_depth_
std::atomic<size_t> v8::internal::TracingAccountingAllocator::nesting_depth_ {0} [private]
Definition at line 4146 of file isolate.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/execution/isolate.cc