v8::internal::maglev::Float64Constant Class Reference
#include <maglev-ir.h>
Public Types
using OutputRegister = DoubleRegister
Public Member Functions
Float64Constant (uint64_t bitfield, Float64 value)
Float64Constant (uint64_t bitfield, uint64_t bitpattern)
Float64 value () const
bool ToBoolean (LocalIsolate *local_isolate) const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
void DoLoadToRegister (MaglevAssembler *, OutputRegister)
DirectHandle< Object > DoReify (LocalIsolate *isolate) const
Static Public Attributes
static constexpr OpProperties kProperties = OpProperties::Float64()
Private Types
using Base = FixedInputValueNodeT< 0, Float64Constant >
Private Attributes
const Float64 value_
Additional Inherited Members
Detailed Description
Definition at line 3953 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::Float64Constant::Base = FixedInputValueNodeT<0, Float64Constant> [private]
Definition at line 3954 of file maglev-ir.h.
OutputRegister
using v8::internal::maglev::Float64Constant::OutputRegister = DoubleRegister
Definition at line 3957 of file maglev-ir.h.
Constructor & Destructor Documentation
Float64Constant() [1/2]
v8::internal::maglev::Float64Constant::Float64Constant (uint64_t bitfield, Float64 value) [inline], [explicit]
Definition at line 3959 of file maglev-ir.h.
      : Base(bitfield), value_(value) {}
Float64Constant() [2/2]
v8::internal::maglev::Float64Constant::Float64Constant (uint64_t bitfield, uint64_t bitpattern) [inline], [explicit]
Definition at line 3962 of file maglev-ir.h.
      : Base(bitfield), value_(Float64::FromBits(bitpattern)) {}
Member Function Documentation
DoLoadToRegister()
void v8::internal::maglev::Float64Constant::DoLoadToRegister (MaglevAssembler * , OutputRegister)
DoReify()
DirectHandle< Object > v8::internal::maglev::Float64Constant::DoReify (LocalIsolate * isolate) const
Definition at line 1227 of file maglev-ir.cc.
                                                                         {
  return isolate->factory()->NewNumber<AllocationType::kOld>(
      value_.get_scalar());
}
References v8::internal::LocalIsolate::factory(), v8::internal::Float64::get_scalar(), v8::internal::kOld, v8::internal::FactoryBase< Impl >::NewNumber(), and value_.
GenerateCode()
void v8::internal::maglev::Float64Constant::GenerateCode (MaglevAssembler * , const ProcessingState &)
PrintParams()
void v8::internal::maglev::Float64Constant::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 7909 of file maglev-ir.cc.
                                                                             {
  if (value().is_nan()) {
    os << "(NaN [0x" << std::hex << value().get_bits() << std::dec << "]";
    if (value().is_hole_nan()) {
      os << ", the hole";
    } else if (value().get_bits() ==
               base::bit_cast<uint64_t>(
                   std::numeric_limits<double>::quiet_NaN())) {
      os << ", quiet NaN";
    }
    os << ")";
  } else {
    os << "(" << value().get_scalar() << ")";
  }
}
References v8::internal::Float64::get_bits(), v8::internal::Float64::get_scalar(), and value().
SetValueLocationConstraints()
void v8::internal::maglev::Float64Constant::SetValueLocationConstraints ()
ToBoolean()
bool v8::internal::maglev::Float64Constant::ToBoolean (LocalIsolate * local_isolate) const [inline]
Definition at line 3969 of file maglev-ir.h.
                                                    {
    return value_.get_scalar() != 0.0 && !value_.is_nan();
  }
References v8::internal::Float64::get_scalar(), v8::internal::Float64::is_nan(), and value_.
value()
Float64 v8::internal::maglev::Float64Constant::value () const [inline]
Definition at line 3967 of file maglev-ir.h.
{ return value_; }
References value_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::GetSilencedNaN(), v8::internal::maglev::MaglevGraphBuilder::GetTruncatedInt32ForToNumber(), PrintParams(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::maglev::MaglevGraphBuilder::TryGetInt32Constant(), and v8::internal::maglev::MaglevGraphBuilder::TryGetUint32Constant().
Member Data Documentation
kProperties
constexpr OpProperties v8::internal::maglev::Float64Constant::kProperties = OpProperties::Float64() [static], [constexpr]
Definition at line 3965 of file maglev-ir.h.
value_
const Float64 v8::internal::maglev::Float64Constant::value_ [private]
Definition at line 3981 of file maglev-ir.h.
Referenced by DoReify(), ToBoolean(), and value().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc