v8::internal::anonymous_namespace{builtins-internal-gen.cc}::SetOrCopyDataPropertiesAssembler Class Reference
Public Member Functions
SetOrCopyDataPropertiesAssembler (compiler::CodeAssemblerState *state)
Protected Member Functions
TNode< JSObject > AllocateJsObjectTarget (TNode< Context > context)
TNode< Object > SetOrCopyDataProperties (TNode< Context > context, TNode< JSReceiver > target, TNode< Object > source, Label *if_runtime, std::optional< TNode< IntPtrT >> excluded_property_count=std::nullopt, std::optional< TNode< IntPtrT >> excluded_property_base=std::nullopt, bool use_set=true)
Additional Inherited Members
Detailed Description
Definition at line 979 of file builtins-internal-gen.cc.
Constructor & Destructor Documentation
SetOrCopyDataPropertiesAssembler()
v8::internal::anonymous_namespace{builtins-internal-gen.cc}::SetOrCopyDataPropertiesAssembler::SetOrCopyDataPropertiesAssembler (compiler::CodeAssemblerState * state) [inline], [explicit]
Definition at line 981 of file builtins-internal-gen.cc.
      : CodeStubAssembler(state) {}
Member Function Documentation
AllocateJsObjectTarget()
TNode<JSObject> v8::internal::anonymous_namespace{builtins-internal-gen.cc}::SetOrCopyDataPropertiesAssembler::AllocateJsObjectTarget (TNode< Context > context) [inline], [protected]
Definition at line 985 of file builtins-internal-gen.cc.
                                                                 {
    const TNode<NativeContext> native_context = LoadNativeContext(context);
    const TNode<JSFunction> object_function = Cast(LoadContextElementNoCell(
        native_context, Context::OBJECT_FUNCTION_INDEX));
    const TNode<Map> map =
        Cast(LoadJSFunctionPrototypeOrInitialMap(object_function));
    const TNode<JSObject> target = AllocateJSObjectFromMap(map);
    return target;
  }
References v8::internal::Cast(), and v8::internal::native_context.
SetOrCopyDataProperties()
TNode<Object> v8::internal::anonymous_namespace{builtins-internal-gen.cc}::SetOrCopyDataPropertiesAssembler::SetOrCopyDataProperties (TNode< Context > context, TNode< JSReceiver > target, TNode< Object > source, Label * if_runtime, std::optional< TNode< IntPtrT >> excluded_property_count = std::nullopt, std::optional< TNode< IntPtrT >> excluded_property_base = std::nullopt, bool use_set = true) [inline], [protected]
Definition at line 994 of file builtins-internal-gen.cc.
                           {
    Label if_done(this), if_noelements(this),
        if_sourcenotjsobject(this, Label::kDeferred);
    // JSPrimitiveWrapper wrappers for numbers don't have any enumerable own
    // properties, so we can immediately skip the whole operation if {source} is
    // a Smi.
    GotoIf(TaggedIsSmi(source), &if_done);
    // Otherwise check if {source} is a proper JSObject, and if not, defer
    // to testing for non-empty strings below.
    TNode<Map> source_map = LoadMap(CAST(source));
    TNode<Uint16T> source_instance_type = LoadMapInstanceType(source_map);
    GotoIfNot(IsJSObjectInstanceType(source_instance_type),
              &if_sourcenotjsobject);
    TNode<FixedArrayBase> source_elements = LoadElements(CAST(source));
    GotoIf(IsEmptyFixedArray(source_elements), &if_noelements);
    Branch(IsEmptySlowElementDictionary(source_elements), &if_noelements,
           if_runtime);
    BIND(&if_noelements);
    {
      // If the target is deprecated, the object will be updated on first
      // store. If the source for that store equals the target, this will
      // invalidate the cached representation of the source. Handle this case
      // in runtime.
      TNode<Map> target_map = LoadMap(target);
      GotoIf(IsDeprecatedMap(target_map), if_runtime);
      if (use_set) {
        TNode<BoolT> target_is_simple_receiver = IsSimpleObjectMap(target_map);
        ForEachEnumerableOwnProperty(
            context, source_map, CAST(source), kEnumerationOrder,
            [=, this](TNode<Name> key, LazyNode<Object> value) {
              KeyedStoreGenericGenerator::SetProperty(
                  state(), context, target, target_is_simple_receiver, key,
                  value(), LanguageMode::kStrict);
            },
            if_runtime);
      } else {
        ForEachEnumerableOwnProperty(
            context, source_map, CAST(source), kEnumerationOrder,
            [=, this](TNode<Name> key, LazyNode<Object> value) {
              Label skip(this);
              if (excluded_property_count.has_value()) {
                BuildFastLoop<IntPtrT>(
                    IntPtrConstant(0), excluded_property_count.value(),
                    [&](TNode<IntPtrT> index) {
                      auto offset = Signed(TimesSystemPointerSize(index));
                      TNode<IntPtrT> location = Signed(
                          IntPtrSub(excluded_property_base.value(), offset));
                      auto property = LoadFullTagged(location);
                      Label continue_label(this);
                      BranchIfSameValue(key, property, &skip, &continue_label);
                      Bind(&continue_label);
                    },
                    1, LoopUnrollingMode::kNo, IndexAdvanceMode::kPost);
              }
              CallBuiltin(Builtin::kCreateDataProperty, context, target, key,
                          value());
              Goto(&skip);
              Bind(&skip);
            },
            if_runtime);
      }
      Goto(&if_done);
    }
    BIND(&if_sourcenotjsobject);
    {
      // Handle other JSReceivers in the runtime.
      GotoIf(IsJSReceiverInstanceType(source_instance_type), if_runtime);
      // Non-empty strings are the only non-JSReceivers that need to be
      // handled explicitly by Object.assign() and CopyDataProperties.
      GotoIfNot(IsStringInstanceType(source_instance_type), &if_done);
      TNode<Uint32T> source_length = LoadStringLengthAsWord32(CAST(source));
      Branch(Word32Equal(source_length, Uint32Constant(0)), &if_done,
             if_runtime);
    }
    BIND(&if_done);
    return target;
  }
References CAST, v8::internal::index, v8::internal::compiler::IntPtrConstant(), v8::internal::kEnumerationOrder, v8::internal::key, v8::internal::kStrict, v8::internal::KeyedStoreGenericGenerator::SetProperty(), v8::internal::value, and v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/builtins/builtins-internal-gen.cc