v8::internal::XMMRegister Class Reference
#include <register-ia32.h>
Public Member Functions
int high_bit () const
int low_bits () const
Protected Member Functions
constexpr XMMRegister (int code)
Private Member Functions
constexpr XMMRegister (int code)
Friends
class RegisterBase< XMMRegister, kDoubleAfterLast >
Additional Inherited Members
Detailed Description
Definition at line 104 of file register-ia32.h.
Constructor & Destructor Documentation
XMMRegister() [1/2]
constexpr v8::internal::XMMRegister::XMMRegister (int code) [inline], [explicit], [constexpr], [private]
Definition at line 106 of file register-ia32.h.
: RegisterBase(code) {}
XMMRegister() [2/2]
constexpr v8::internal::XMMRegister::XMMRegister (int code) [inline], [explicit], [constexpr], [protected]
Definition at line 228 of file register-x64.h.
: RegisterBase(code) {}
Member Function Documentation
high_bit()
int v8::internal::XMMRegister::high_bit () const [inline]
Definition at line 221 of file register-x64.h.
{ return code() >> 3; }
References v8::internal::RegisterBase< XMMRegister, kDoubleAfterLast >::code().
Referenced by v8::internal::Assembler::emit_optional_rex_32(), v8::internal::Assembler::emit_vex2_byte1(), v8::internal::Assembler::emit_vex3_byte1(), and v8::internal::Assembler::emit_vex_prefix().
low_bits()
int v8::internal::XMMRegister::low_bits () const [inline]
Definition at line 224 of file register-x64.h.
{ return code() & 0x7; }
References v8::internal::RegisterBase< XMMRegister, kDoubleAfterLast >::code().
Friends And Related Function Documentation
RegisterBase< XMMRegister, kDoubleAfterLast >
friend class RegisterBase< XMMRegister, kDoubleAfterLast > [friend]
Definition at line 68 of file register-ia32.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/ia32/register-ia32.h
/mnt/V8SourceCode/src/codegen/x64/register-x64.h