v8::internal::JSAsyncDisposableStack Class Reference
#include <js-disposable-stack.h>
Static Public Member Functions
static Maybe< bool > NextDisposeAsyncIteration (Isolate *isolate, DirectHandle< JSDisposableStackBase > async_disposable_stack, DirectHandle< JSPromise > outer_promise)
Detailed Description
Definition at line 102 of file js-disposable-stack.h.
Member Function Documentation
NextDisposeAsyncIteration()
Maybe< bool > v8::internal::JSAsyncDisposableStack::NextDisposeAsyncIteration (Isolate * isolate, DirectHandle< JSDisposableStackBase > async_disposable_stack, DirectHandle< JSPromise > outer_promise) [static]
Definition at line 212 of file js-disposable-stack.cc.
                                           {
  MaybeDirectHandle<Object> result;
  bool done;
  do {
    done = true;
    // 6. Let result be
    // DisposeResources(asyncDisposableStack.[[DisposeCapability]],
    // NormalCompletion(undefined)).
    result = DisposeResources(isolate, async_disposable_stack,
                              DisposableStackResourcesType::kAtLeastOneAsync);
    DirectHandle<Object> result_handle;
    if (result.ToHandle(&result_handle)) {
      if (!IsTrue(*result_handle)) {
        DirectHandle<Context> async_disposable_stack_context =
            isolate->factory()->NewBuiltinContext(
                isolate->native_context(),
                static_cast<int>(
                    JSDisposableStackBase::AsyncDisposableStackContextSlots::
                        kLength));
        async_disposable_stack_context->SetNoCell(
            static_cast<int>(JSDisposableStackBase::
                                 AsyncDisposableStackContextSlots::kStack),
            *async_disposable_stack);
        async_disposable_stack_context->SetNoCell(
            static_cast<int>(
                JSDisposableStackBase::AsyncDisposableStackContextSlots::
                    kOuterPromise),
            *outer_promise);
        DirectHandle<JSFunction> on_fulfilled =
            Factory::JSFunctionBuilder{
                isolate,
                isolate->factory()
                    ->async_disposable_stack_on_fulfilled_shared_fun(),
                async_disposable_stack_context}
                .Build();
        DirectHandle<JSFunction> on_rejected =
            Factory::JSFunctionBuilder{
                isolate,
                isolate->factory()
                    ->async_disposable_stack_on_rejected_shared_fun(),
                async_disposable_stack_context}
                .Build();
        DirectHandle<Object> args[] = {on_fulfilled, on_rejected};
        if (Execution::CallBuiltin(isolate, isolate->perform_promise_then(),
                                   Cast<JSPromise>(result_handle),
                                   base::VectorOf(args))
                .is_null()) {
          CHECK_EXCEPTION_ON_DISPOSAL(isolate, async_disposable_stack,
                                      Nothing<bool>());
          done = false;
        }
      } else {
        // 8. Perform ! Call(promiseCapability.[[Resolve]], undefined, « result
        // »).
        if (JSPromise::Resolve(outer_promise,
                               isolate->factory()->undefined_value())
                .is_null()) {
          CHECK_EXCEPTION_ON_DISPOSAL(isolate, async_disposable_stack,
                                      Nothing<bool>());
          done = false;
        }
      }
    } else {
      // 7. IfAbruptRejectPromise(result, promiseCapability).
      DirectHandle<Object> exception(isolate->exception(), isolate);
      if (!isolate->is_catchable_by_javascript(*exception)) {
        return Nothing<bool>();
      }
      isolate->clear_internal_exception();
      isolate->clear_pending_message();
      JSPromise::Reject(outer_promise, exception);
    }
  } while (!done);
  return Just(true);
}
References v8::base::args, v8::internal::Execution::CallBuiltin(), CHECK_EXCEPTION_ON_DISPOSAL, v8::internal::Isolate::clear_internal_exception(), v8::internal::Isolate::clear_pending_message(), v8::internal::Isolate::exception(), v8::internal::Isolate::factory(), v8::internal::Isolate::is_catchable_by_javascript(), v8::Just(), v8::internal::kAtLeastOneAsync, v8::internal::compiler::anonymous_namespace{gap-resolver.cc}::kStack, v8::internal::Isolate::native_context(), v8::internal::Factory::NewBuiltinContext(), v8::internal::JSPromise::Reject(), v8::internal::JSPromise::Resolve(), v8::base::internal::result, and v8::base::VectorOf().
Referenced by v8::internal::BUILTIN().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-disposable-stack.h
/mnt/V8SourceCode/src/objects/js-disposable-stack.cc