v8::internal::wasm::BranchTableIterator< ValidationTag > Class Template Reference
#include <function-body-decoder-impl.h>
Public Member Functions
uint32_t cur_index () const
bool has_next () const
uint32_t next ()
uint32_t length () const
const uint8_t * pc () const
BranchTableIterator (Decoder *decoder, const BranchTableImmediate &imm)
Private Attributes
Decoder *const decoder_
const uint8_t *const start_
const uint8_t * pc_
uint32_t index_ = 0
const uint32_t table_count_
Detailed Description
template<typename ValidationTag>
class v8::internal::wasm::BranchTableIterator< ValidationTag >
Definition at line 906 of file function-body-decoder-impl.h.
Constructor & Destructor Documentation
BranchTableIterator()
template<typename ValidationTag >
v8::internal::wasm::BranchTableIterator< ValidationTag >::BranchTableIterator (Decoder * decoder, const BranchTableImmediate & imm) [inline]
Definition at line 928 of file function-body-decoder-impl.h.
      : decoder_(decoder),
        start_(imm.start),
        pc_(imm.table),
        table_count_(imm.table_count) {}
Member Function Documentation
cur_index()
template<typename ValidationTag >
uint32_t v8::internal::wasm::BranchTableIterator< ValidationTag >::cur_index () const [inline]
Definition at line 908 of file function-body-decoder-impl.h.
{ return index_; }
References v8::internal::wasm::BranchTableIterator< ValidationTag >::index_.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTable(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GenerateBrTable(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::LowerToBranches().
has_next()
template<typename ValidationTag >
bool v8::internal::wasm::BranchTableIterator< ValidationTag >::has_next () const [inline]
Definition at line 909 of file function-body-decoder-impl.h.
                        {
    return VALIDATE(decoder_->ok()) && index_ <= table_count_;
  }
References v8::internal::wasm::BranchTableIterator< ValidationTag >::decoder_, v8::internal::wasm::BranchTableIterator< ValidationTag >::index_, v8::internal::wasm::Decoder::ok(), v8::internal::wasm::BranchTableIterator< ValidationTag >::table_count_, and VALIDATE.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTable(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), v8::internal::wasm::WasmBytecodeGenerator::DecodeInstruction(), v8::internal::wasm::BranchTableIterator< ValidationTag >::length(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::LowerToBranches(), v8::internal::wasm::BranchTableIterator< ValidationTag >::next(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::OpcodeLength().
length()
template<typename ValidationTag >
uint32_t v8::internal::wasm::BranchTableIterator< ValidationTag >::length () const [inline]
Definition at line 922 of file function-body-decoder-impl.h.
                          {
    DCHECK(!has_next());
    return static_cast<uint32_t>(pc_ - start_);
  }
References v8::internal::DCHECK(), v8::internal::wasm::BranchTableIterator< ValidationTag >::has_next(), v8::internal::wasm::BranchTableIterator< ValidationTag >::pc_, and v8::internal::wasm::BranchTableIterator< ValidationTag >::start_.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), v8::internal::wasm::BranchTableIterator< ValidationTag >::next(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::OpcodeLength().
next()
template<typename ValidationTag >
uint32_t v8::internal::wasm::BranchTableIterator< ValidationTag >::next () [inline]
Definition at line 912 of file function-body-decoder-impl.h.
                  {
    DCHECK(has_next());
    index_++;
    auto [result, length] =
        decoder_->read_u32v<ValidationTag>(pc_, "branch table entry");
    pc_ += length;
    return result;
  }
References v8::internal::DCHECK(), v8::internal::wasm::BranchTableIterator< ValidationTag >::decoder_, v8::internal::wasm::BranchTableIterator< ValidationTag >::has_next(), v8::internal::wasm::BranchTableIterator< ValidationTag >::index_, v8::internal::wasm::BranchTableIterator< ValidationTag >::length(), v8::internal::wasm::BranchTableIterator< ValidationTag >::pc_, v8::internal::wasm::Decoder::read_u32v(), and v8::base::internal::result.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTable(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), v8::internal::wasm::WasmBytecodeGenerator::DecodeInstruction(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GenerateBrTable(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::LowerToBranches(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::OpcodeLength().
pc()
template<typename ValidationTag >
const uint8_t* v8::internal::wasm::BranchTableIterator< ValidationTag >::pc () const [inline]
Definition at line 926 of file function-body-decoder-impl.h.
{ return pc_; }
References v8::internal::wasm::BranchTableIterator< ValidationTag >::pc_.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), and v8::internal::wasm::WasmBytecodeGenerator::DecodeInstruction().
Member Data Documentation
decoder_
template<typename ValidationTag >
Decoder* const v8::internal::wasm::BranchTableIterator< ValidationTag >::decoder_ [private]
Definition at line 935 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::BranchTableIterator< ValidationTag >::has_next(), and v8::internal::wasm::BranchTableIterator< ValidationTag >::next().
index_
template<typename ValidationTag >
uint32_t v8::internal::wasm::BranchTableIterator< ValidationTag >::index_ = 0 [private]
Definition at line 938 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::BranchTableIterator< ValidationTag >::cur_index(), v8::internal::wasm::BranchTableIterator< ValidationTag >::has_next(), and v8::internal::wasm::BranchTableIterator< ValidationTag >::next().
pc_
template<typename ValidationTag >
const uint8_t* v8::internal::wasm::BranchTableIterator< ValidationTag >::pc_ [private]
Definition at line 937 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::BranchTableIterator< ValidationTag >::length(), v8::internal::wasm::BranchTableIterator< ValidationTag >::next(), and v8::internal::wasm::BranchTableIterator< ValidationTag >::pc().
start_
template<typename ValidationTag >
const uint8_t* const v8::internal::wasm::BranchTableIterator< ValidationTag >::start_ [private]
Definition at line 936 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::BranchTableIterator< ValidationTag >::length().
table_count_
template<typename ValidationTag >
const uint32_t v8::internal::wasm::BranchTableIterator< ValidationTag >::table_count_ [private]
Definition at line 939 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::BranchTableIterator< ValidationTag >::has_next().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/function-body-decoder-impl.h