v8::internal::Expression Class Reference
#include <ast.h>
Public Member Functions
bool IsValidReferenceExpression () const
bool IsPrivateName () const
bool ToBooleanIsTrue () const
bool ToBooleanIsFalse () const
bool IsPropertyName () const
bool IsAnonymousFunctionDefinition () const
bool IsConciseMethodDefinition () const
bool IsAccessorFunctionDefinition () const
bool IsSmiLiteral () const
V8_EXPORT_PRIVATE bool IsNumberLiteral () const
bool IsStringLiteral () const
bool IsConsStringLiteral () const
bool IsNullLiteral () const
bool IsBooleanLiteral () const
bool IsTheHoleLiteral () const
bool IsUndefinedLiteral () const
bool IsNullOrUndefinedLiteral () const
bool IsLiteralButNotNullOrUndefined () const
bool IsCompileTimeValue ()
bool IsPattern ()
bool is_parenthesized () const
void mark_parenthesized ()
void clear_parenthesized ()
Protected Types
template<class T , int size>
using NextBitField = IsParenthesizedField::Next< T, size >
Protected Member Functions
Expression (int pos, NodeType type)
Private Types
using IsParenthesizedField = AstNode::NextBitField< bool, 1 >
Additional Inherited Members
Detailed Description
Definition at line 194 of file ast.h.
Member Typedef Documentation
IsParenthesizedField
using v8::internal::Expression::IsParenthesizedField = AstNode::NextBitField<bool, 1> [private]
Definition at line 273 of file ast.h.
NextBitField
template<class T , int size>
using v8::internal::Expression::NextBitField = IsParenthesizedField::Next<T, size> [protected]
Definition at line 281 of file ast.h.
Constructor & Destructor Documentation
Expression()
v8::internal::Expression::Expression (int pos, NodeType type) [inline], [protected]
Definition at line 276 of file ast.h.
                                     : AstNode(pos, type) {
    DCHECK(!is_parenthesized());
  }
References v8::internal::DCHECK(), and is_parenthesized().
Member Function Documentation
clear_parenthesized()
void v8::internal::Expression::clear_parenthesized () [inline]
Definition at line 268 of file ast.h.
                             {
    bit_field_ = IsParenthesizedField::update(bit_field_, false);
  }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::update().
Referenced by v8::internal::Parser::CollapseNaryExpression(), v8::internal::Parser::ShortcutStringLiteralAppendExpression(), and v8::internal::AstNodeFactory::ThisExpression().
is_parenthesized()
bool v8::internal::Expression::is_parenthesized () const [inline]
Definition at line 260 of file ast.h.
                                {
    return IsParenthesizedField::decode(bit_field_);
  }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by Expression(), and v8::internal::Parser::SetFunctionNameFromIdentifierRef().
IsAccessorFunctionDefinition()
bool v8::internal::Expression::IsAccessorFunctionDefinition () const
Definition at line 150 of file ast.cc.
                                                    {
  return IsFunctionLiteral() && IsAccessorFunction(AsFunctionLiteral()->kind());
}
References v8::internal::IsAccessorFunction().
Referenced by v8::internal::LiteralProperty::NeedsSetFunctionName(), and v8::internal::Parser::SetFunctionNameFromPropertyName().
IsAnonymousFunctionDefinition()
bool v8::internal::Expression::IsAnonymousFunctionDefinition () const
Definition at line 139 of file ast.cc.
                                                     {
  return (IsFunctionLiteral() &&
          AsFunctionLiteral()->IsAnonymousFunctionDefinition()) ||
         (IsClassLiteral() &&
          AsClassLiteral()->IsAnonymousFunctionDefinition());
}
Referenced by v8::internal::LiteralProperty::NeedsSetFunctionName(), and v8::internal::Parser::SetFunctionNameFromPropertyName().
IsBooleanLiteral()
bool v8::internal::Expression::IsBooleanLiteral () const
Definition at line 91 of file ast.cc.
                                        {
  return IsLiteral() && AsLiteral()->type() == Literal::kBoolean;
}
References v8::internal::Literal::kBoolean.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildLiteralStrictCompareBoolean(), and v8::internal::MatchLiteralStrictCompareBoolean().
IsCompileTimeValue()
bool v8::internal::Expression::IsCompileTimeValue ()
Definition at line 99 of file ast.cc.
                                    {
  if (IsLiteral()) return true;
  MaterializedLiteral* literal = AsMaterializedLiteral();
  if (literal == nullptr) return false;
  return literal->IsSimple();
}
References v8::internal::AstNode::AsMaterializedLiteral(), and v8::internal::MaterializedLiteral::IsSimple().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildCreateArrayLiteral(), v8::internal::LiteralBoilerplateBuilder::GetBoilerplateValue(), and v8::internal::ObjectLiteralProperty::IsCompileTimeValue().
IsConciseMethodDefinition()
bool v8::internal::Expression::IsConciseMethodDefinition () const
Definition at line 146 of file ast.cc.
                                                 {
  return IsFunctionLiteral() && IsConciseMethod(AsFunctionLiteral()->kind());
}
References v8::internal::IsConciseMethod().
Referenced by v8::internal::LiteralProperty::NeedsSetFunctionName(), and v8::internal::Parser::SetFunctionNameFromPropertyName().
IsConsStringLiteral()
bool v8::internal::Expression::IsConsStringLiteral () const
Definition at line 79 of file ast.cc.
                                           {
  return IsLiteral() && AsLiteral()->type() == Literal::kConsString;
}
References v8::internal::Literal::kConsString.
IsLiteralButNotNullOrUndefined()
bool v8::internal::Expression::IsLiteralButNotNullOrUndefined () const
Definition at line 118 of file ast.cc.
                                                      {
  return IsLiteral() && !IsNullOrUndefinedLiteral();
}
References IsNullOrUndefinedLiteral().
Referenced by v8::internal::interpreter::BytecodeGenerator::VisitNaryNullishExpression(), v8::internal::interpreter::BytecodeGenerator::VisitNullishExpression(), and v8::internal::interpreter::BytecodeGenerator::VisitNullishSubExpression().
IsNullLiteral()
bool v8::internal::Expression::IsNullLiteral () const
Definition at line 87 of file ast.cc.
                                     {
  return IsLiteral() && AsLiteral()->type() == Literal::kNull;
}
References v8::internal::Literal::kNull.
Referenced by v8::internal::ObjectLiteral::CalculateEmitStore(), IsNullOrUndefinedLiteral(), v8::internal::ObjectLiteralProperty::IsNullPrototype(), and v8::internal::MatchLiteralCompareNull().
IsNullOrUndefinedLiteral()
bool v8::internal::Expression::IsNullOrUndefinedLiteral () const [inline]
Definition at line 246 of file ast.h.
                                               {
    return IsNullLiteral() || IsUndefinedLiteral();
  }
References IsNullLiteral(), and IsUndefinedLiteral().
Referenced by IsLiteralButNotNullOrUndefined(), v8::internal::interpreter::BytecodeGenerator::VisitNullishExpression(), and v8::internal::interpreter::BytecodeGenerator::VisitNullishSubExpression().
IsNumberLiteral()
bool v8::internal::Expression::IsNumberLiteral () const
Definition at line 71 of file ast.cc.
                                       {
  return IsLiteral() && AsLiteral()->IsNumber();
}
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildDestructuringObjectAssignment(), and v8::internal::Parser::BuildUnaryExpression().
IsPattern()
bool v8::internal::Expression::IsPattern () [inline]
Definition at line 255 of file ast.h.
                   {
    static_assert(kObjectLiteral + 1 == kArrayLiteral);
    return base::IsInRange(node_type(), kObjectLiteral, kArrayLiteral);
  }
References v8::internal::AstNode::node_type().
IsPrivateName()
bool v8::internal::Expression::IsPrivateName () const
Definition at line 130 of file ast.cc.
                                     {
  return IsVariableProxy() && AsVariableProxy()->IsPrivateName();
}
Referenced by v8::internal::Property::IsPrivateReference().
IsPropertyName()
bool v8::internal::Expression::IsPropertyName () const
Definition at line 83 of file ast.cc.
                                      {
  return IsLiteral() && AsLiteral()->IsPropertyName();
}
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassProperty(), v8::internal::interpreter::BytecodeGenerator::BuildDestructuringObjectAssignment(), v8::internal::Property::GetAssignType(), v8::internal::Call::GetCallType(), v8::internal::ClassBoilerplate::New(), v8::internal::Parser::PushPropertyName(), and v8::internal::ErrorUtils::ThrowLoadFromNullOrUndefined().
IsSmiLiteral()
bool v8::internal::Expression::IsSmiLiteral () const
Definition at line 67 of file ast.cc.
                                    {
  return IsLiteral() && AsLiteral()->type() == Literal::kSmi;
}
References v8::internal::Literal::kSmi.
Referenced by v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::IsSmiLiteralSwitchCaseValue(), v8::internal::MatchSmiLiteralOperation(), v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::ReduceToSmiSwitchCaseValue(), and v8::internal::interpreter::BytecodeGenerator::VisitNaryArithmeticExpression().
IsStringLiteral()
bool v8::internal::Expression::IsStringLiteral () const
Definition at line 75 of file ast.cc.
                                       {
  return IsLiteral() && AsLiteral()->type() == Literal::kString;
}
References v8::internal::Literal::kString.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildLoadPropertyKey(), v8::internal::interpreter::IsLiteralCompareTypeof(), and v8::internal::MatchLiteralCompareEqualVariable().
IsTheHoleLiteral()
bool v8::internal::Expression::IsTheHoleLiteral () const
Definition at line 95 of file ast.cc.
                                        {
  return IsLiteral() && AsLiteral()->type() == Literal::kTheHole;
}
References v8::internal::Literal::kTheHole.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildCreateArrayLiteral().
IsUndefinedLiteral()
bool v8::internal::Expression::IsUndefinedLiteral () const
Definition at line 106 of file ast.cc.
                                          {
  if (IsLiteral() && AsLiteral()->type() == Literal::kUndefined) return true;
  const VariableProxy* var_proxy = AsVariableProxy();
  if (var_proxy == nullptr) return false;
  Variable* var = var_proxy->var();
  // The global identifier "undefined" is immutable. Everything
  // else could be reassigned.
  return var != nullptr && var->IsUnallocated() &&
         var_proxy->raw_name()->IsOneByteEqualTo("undefined");
}
References v8::internal::AstRawString::IsOneByteEqualTo(), v8::internal::Variable::IsUnallocated(), v8::internal::Literal::kUndefined, v8::internal::VariableProxy::raw_name(), v8::internal::tracing::type, and v8::internal::VariableProxy::var().
Referenced by IsNullOrUndefinedLiteral(), and v8::internal::MatchLiteralCompareUndefined().
IsValidReferenceExpression()
bool v8::internal::Expression::IsValidReferenceExpression () const
Definition at line 134 of file ast.cc.
                                                  {
  return IsProperty() ||
         (IsVariableProxy() && AsVariableProxy()->IsValidReferenceExpression());
}
mark_parenthesized()
void v8::internal::Expression::mark_parenthesized () [inline]
Definition at line 264 of file ast.h.
                            {
    bit_field_ = IsParenthesizedField::update(bit_field_, true);
  }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::update().
Referenced by v8::internal::EmptyParentheses::EmptyParentheses().
ToBooleanIsFalse()
bool v8::internal::Expression::ToBooleanIsFalse () const
Definition at line 126 of file ast.cc.
                                        {
  return IsLiteral() && AsLiteral()->ToBooleanIsFalse();
}
Referenced by v8::internal::interpreter::BytecodeGenerator::VisitLogicalAndExpression(), v8::internal::interpreter::BytecodeGenerator::VisitLogicalAndSubExpression(), v8::internal::interpreter::BytecodeGenerator::VisitLogicalOrExpression(), v8::internal::interpreter::BytecodeGenerator::VisitLogicalOrSubExpression(), and v8::internal::interpreter::BytecodeGenerator::VisitNaryLogicalAndExpression().
ToBooleanIsTrue()
bool v8::internal::Expression::ToBooleanIsTrue () const
Definition at line 122 of file ast.cc.
                                       {
  return IsLiteral() && AsLiteral()->ToBooleanIsTrue();
}
Referenced by v8::internal::interpreter::BytecodeGenerator::VisitLogicalAndExpression(), v8::internal::interpreter::BytecodeGenerator::VisitLogicalAndSubExpression(), v8::internal::interpreter::BytecodeGenerator::VisitLogicalOrExpression(), v8::internal::interpreter::BytecodeGenerator::VisitLogicalOrSubExpression(), v8::internal::interpreter::BytecodeGenerator::VisitNaryLogicalOrExpression(), v8::internal::interpreter::BytecodeGenerator::VisitNaryNullishExpression(), and v8::internal::interpreter::BytecodeGenerator::VisitNullishExpression().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ast/ast.h
/mnt/V8SourceCode/src/ast/ast.cc