v8_inspector::V8DebuggerAgentImpl Class Reference
#include <v8-debugger-agent-impl.h>
Classes
struct CachedScript
Public Types
enum BreakpointSource { UserBreakpointSource
, DebugCommandBreakpointSource
, MonitorCommandBreakpointSource
 }
Public Member Functions
V8DebuggerAgentImpl (V8InspectorSessionImpl *, protocol::FrontendChannel *, protocol::DictionaryValue *state)
~V8DebuggerAgentImpl () override
V8DebuggerAgentImpl (const V8DebuggerAgentImpl &)=delete
V8DebuggerAgentImpl & operator= (const V8DebuggerAgentImpl &)=delete
void restore ()
void stop ()
Response enable (std::optional< double > maxScriptsCacheSize, String16 *outDebuggerId) override
Response disable () override
Response setBreakpointsActive (bool active) override
Response setSkipAllPauses (bool skip) override
Response setBreakpointByUrl (int lineNumber, std::optional< String16 > optionalURL, std::optional< String16 > optionalURLRegex, std::optional< String16 > optionalScriptHash, std::optional< int > optionalColumnNumber, std::optional< String16 > optionalCondition, String16 *, std::unique_ptr< protocol::Array< protocol::Debugger::Location >> *locations) override
Response setBreakpoint (std::unique_ptr< protocol::Debugger::Location >, std::optional< String16 > optionalCondition, String16 *, std::unique_ptr< protocol::Debugger::Location > *actualLocation) override
Response setBreakpointOnFunctionCall (const String16 &functionObjectId, std::optional< String16 > optionalCondition, String16 *outBreakpointId) override
Response setInstrumentationBreakpoint (const String16 &instrumentation, String16 *outBreakpointId) override
Response removeBreakpoint (const String16 &breakpointId) override
Response continueToLocation (std::unique_ptr< protocol::Debugger::Location >, std::optional< String16 > targetCallFrames) override
Response getStackTrace (std::unique_ptr< protocol::Runtime::StackTraceId > inStackTraceId, std::unique_ptr< protocol::Runtime::StackTrace > *outStackTrace) override
Response searchInContent (const String16 &scriptId, const String16 &query, std::optional< bool > optionalCaseSensitive, std::optional< bool > optionalIsRegex, std::unique_ptr< protocol::Array< protocol::Debugger::SearchMatch >> *) override
Response getPossibleBreakpoints (std::unique_ptr< protocol::Debugger::Location > start, std::unique_ptr< protocol::Debugger::Location > end, std::optional< bool > restrictToFunction, std::unique_ptr< protocol::Array< protocol::Debugger::BreakLocation >> *locations) override
Response setScriptSource (const String16 &inScriptId, const String16 &inScriptSource, std::optional< bool > dryRun, std::optional< bool > allowTopFrameEditing, std::unique_ptr< protocol::Array< protocol::Debugger::CallFrame >> *optOutCallFrames, std::optional< bool > *optOutStackChanged, std::unique_ptr< protocol::Runtime::StackTrace > *optOutAsyncStackTrace, std::unique_ptr< protocol::Runtime::StackTraceId > *optOutAsyncStackTraceId, String16 *outStatus, std::unique_ptr< protocol::Runtime::ExceptionDetails > *optOutCompileError) override
Response restartFrame (const String16 &callFrameId, std::optional< String16 > mode, std::unique_ptr< protocol::Array< protocol::Debugger::CallFrame >> *newCallFrames, std::unique_ptr< protocol::Runtime::StackTrace > *asyncStackTrace, std::unique_ptr< protocol::Runtime::StackTraceId > *asyncStackTraceId) override
Response getScriptSource (const String16 &scriptId, String16 *scriptSource, std::optional< protocol::Binary > *bytecode) override
Response disassembleWasmModule (const String16 &in_scriptId, std::optional< String16 > *out_streamId, int *out_totalNumberOfLines, std::unique_ptr< protocol::Array< int >> *out_functionBodyOffsets, std::unique_ptr< protocol::Debugger::WasmDisassemblyChunk > *out_chunk) override
Response nextWasmDisassemblyChunk (const String16 &in_streamId, std::unique_ptr< protocol::Debugger::WasmDisassemblyChunk > *out_chunk) override
Response getWasmBytecode (const String16 &scriptId, protocol::Binary *bytecode) override
Response pause () override
Response resume (std::optional< bool > terminateOnResume) override
Response stepOver (std::unique_ptr< protocol::Array< protocol::Debugger::LocationRange >> inSkipList) override
Response stepInto (std::optional< bool > inBreakOnAsyncCall, std::unique_ptr< protocol::Array< protocol::Debugger::LocationRange >> inSkipList) override
Response stepOut () override
Response pauseOnAsyncCall (std::unique_ptr< protocol::Runtime::StackTraceId > inParentStackTraceId) override
Response setPauseOnExceptions (const String16 &pauseState) override
Response evaluateOnCallFrame (const String16 &callFrameId, const String16 &expression, std::optional< String16 > objectGroup, std::optional< bool > includeCommandLineAPI, std::optional< bool > silent, std::optional< bool > returnByValue, std::optional< bool > generatePreview, std::optional< bool > throwOnSideEffect, std::optional< double > timeout, std::unique_ptr< protocol::Runtime::RemoteObject > *result, std::unique_ptr< protocol::Runtime::ExceptionDetails > *) override
Response setVariableValue (int scopeNumber, const String16 &variableName, std::unique_ptr< protocol::Runtime::CallArgument > newValue, const String16 &callFrame) override
Response setReturnValue (std::unique_ptr< protocol::Runtime::CallArgument > newValue) override
Response setAsyncCallStackDepth (int depth) override
Response setBlackboxPatterns (std::unique_ptr< protocol::Array< String16 >> patterns, std::optional< bool > skipAnonymous) override
Response setBlackboxExecutionContexts (std::unique_ptr< protocol::Array< String16 >> uniqueIds) override
Response setBlackboxedRanges (const String16 &scriptId, std::unique_ptr< protocol::Array< protocol::Debugger::ScriptPosition >> positions) override
bool enabled () const
void setBreakpointFor (v8::Local< v8::Function > function, v8::Local< v8::String > condition, BreakpointSource source)
void removeBreakpointFor (v8::Local< v8::Function > function, BreakpointSource source)
void schedulePauseOnNextStatement (const String16 &breakReason, std::unique_ptr< protocol::DictionaryValue > data)
void cancelPauseOnNextStatement ()
void breakProgram (const String16 &breakReason, std::unique_ptr< protocol::DictionaryValue > data)
void reset ()
bool instrumentationFinished ()
void didPauseOnInstrumentation (v8::debug::BreakpointId instrumentationId)
void didPause (int contextId, v8::Local< v8::Value > exception, const std::vector< v8::debug::BreakpointId > &hitBreakpoints, v8::debug::ExceptionType exceptionType, bool isUncaught, v8::debug::BreakReasons breakReasons)
void didContinue ()
void didParseSource (std::unique_ptr< V8DebuggerScript >, bool success)
bool isFunctionBlackboxed (const String16 &scriptId, const v8::debug::Location &start, const v8::debug::Location &end)
bool shouldBeSkipped (const String16 &scriptId, int line, int column)
bool acceptsPause (bool isOOMBreak) const
void ScriptCollected (const V8DebuggerScript *script)
v8::Isolate * isolate ()
void clearBreakDetails ()
Private Types
enum EnableState { kDisabled
, kEnabled
, kStopping
 }
using ScriptsMap = std::unordered_map< String16, std::unique_ptr< V8DebuggerScript > >
using BreakpointIdToDebuggerBreakpointIdsMap = std::unordered_map< String16, std::vector< v8::debug::BreakpointId > >
using DebuggerBreakpointIdToBreakpointIdMap = std::unordered_map< v8::debug::BreakpointId, String16 >
using BreakReason = std::pair< String16, std::unique_ptr< protocol::DictionaryValue > >
Private Member Functions
void enableImpl ()
Response currentCallFrames (std::unique_ptr< protocol::Array< protocol::Debugger::CallFrame >> *)
std::unique_ptr< protocol::Runtime::StackTrace > currentAsyncStackTrace ()
std::unique_ptr< protocol::Runtime::StackTraceId > currentExternalStackTrace ()
void setPauseOnExceptionsImpl (int)
std::unique_ptr< protocol::Debugger::Location > setBreakpointImpl (const String16 &breakpointId, const String16 &scriptId, const String16 &condition, int lineNumber, int columnNumber)
void setBreakpointImpl (const String16 &breakpointId, v8::Local< v8::Function > function, v8::Local< v8::String > condition)
void removeBreakpointImpl (const String16 &breakpointId, const std::vector< V8DebuggerScript * > &scripts)
void internalSetAsyncCallStackDepth (int)
void increaseCachedSkipStackGeneration ()
Response setBlackboxPattern (const String16 &pattern)
void resetBlackboxedStateCache ()
bool isPaused () const
void setScriptInstrumentationBreakpointIfNeeded (V8DebuggerScript *script)
Response processSkipList (protocol::Array< protocol::Debugger::LocationRange > &skipList)
void pushBreakDetails (const String16 &breakReason, std::unique_ptr< protocol::DictionaryValue > breakAuxData)
void popBreakDetails ()
Private Attributes
V8InspectorImpl * m_inspector
V8Debugger * m_debugger
V8InspectorSessionImpl * m_session
EnableState m_enableState
protocol::DictionaryValue * m_state
protocol::Debugger::Frontend m_frontend
v8::Isolate * m_isolate
ScriptsMap m_scripts
BreakpointIdToDebuggerBreakpointIdsMap m_breakpointIdToDebuggerBreakpointIds
DebuggerBreakpointIdToBreakpointIdMap m_debuggerBreakpointIdToBreakpointId
std::map< String16, std::unique_ptr< DisassemblyCollectorImpl > > m_wasmDisassemblies
size_t m_nextWasmDisassemblyStreamId = 0
size_t m_maxScriptCacheSize = 0
size_t m_cachedScriptSize = 0
std::deque< CachedScript > m_cachedScripts
std::vector< BreakReason > m_breakReason
bool m_skipAllPauses = false
bool m_breakpointsActive = false
bool m_instrumentationFinished = true
bool m_skipAnonymousScripts = false
std::unique_ptr< V8Regex > m_blackboxPattern
std::unordered_map< String16, std::vector< std::pair< int, int > > > m_blackboxedPositions
std::unordered_map< String16, std::vector< std::pair< int, int > > > m_skipList
std::unordered_set< String16 > m_blackboxedExecutionContexts
Detailed Description
Definition at line 31 of file v8-debugger-agent-impl.h.
Member Typedef Documentation
BreakpointIdToDebuggerBreakpointIdsMap
using v8_inspector::V8DebuggerAgentImpl::BreakpointIdToDebuggerBreakpointIdsMap = std::unordered_map<String16, std::vector<v8::debug::BreakpointId> > [private]
Definition at line 234 of file v8-debugger-agent-impl.h.
BreakReason
using v8_inspector::V8DebuggerAgentImpl::BreakReason = std::pair<String16, std::unique_ptr<protocol::DictionaryValue> > [private]
Definition at line 273 of file v8-debugger-agent-impl.h.
DebuggerBreakpointIdToBreakpointIdMap
using v8_inspector::V8DebuggerAgentImpl::DebuggerBreakpointIdToBreakpointIdMap = std::unordered_map<v8::debug::BreakpointId, String16> [private]
Definition at line 236 of file v8-debugger-agent-impl.h.
ScriptsMap
using v8_inspector::V8DebuggerAgentImpl::ScriptsMap = std::unordered_map<String16, std::unique_ptr<V8DebuggerScript> > [private]
Definition at line 232 of file v8-debugger-agent-impl.h.
Member Enumeration Documentation
BreakpointSource
enum v8_inspector::V8DebuggerAgentImpl::BreakpointSource
Enumerator
UserBreakpointSource
DebugCommandBreakpointSource
MonitorCommandBreakpointSource
Definition at line 33 of file v8-debugger-agent-impl.h.
                        {
    UserBreakpointSource,
    DebugCommandBreakpointSource,
    MonitorCommandBreakpointSource
  };
EnableState
enum v8_inspector::V8DebuggerAgentImpl::EnableState [private]
Enumerator
kDisabled
kEnabled
kStopping
Definition at line 239 of file v8-debugger-agent-impl.h.
                   {
    kDisabled,
    kEnabled,
    kStopping, // This is the same as 'disabled', but it cannot become enabled
                // again.
  };
Constructor & Destructor Documentation
V8DebuggerAgentImpl() [1/2]
v8_inspector::V8DebuggerAgentImpl::V8DebuggerAgentImpl (V8InspectorSessionImpl * session, protocol::FrontendChannel * frontendChannel, protocol::DictionaryValue * state)
Definition at line 427 of file v8-debugger-agent-impl.cc.
    : m_inspector(session->inspector()),
      m_debugger(m_inspector->debugger()),
      m_session(session),
      m_enableState(kDisabled),
      m_state(state),
      m_frontend(frontendChannel),
      m_isolate(m_inspector->isolate()) {}
 V8DebuggerAgentImpl()
v8_inspector::V8DebuggerAgentImpl::~V8DebuggerAgentImpl () [override], [default]
V8DebuggerAgentImpl() [2/2]
v8_inspector::V8DebuggerAgentImpl::V8DebuggerAgentImpl (const V8DebuggerAgentImpl &) [delete]
Member Function Documentation
acceptsPause()
bool v8_inspector::V8DebuggerAgentImpl::acceptsPause (bool isOOMBreak) const
Definition at line 1057 of file v8-debugger-agent-impl.cc.
                                                            {
  return enabled() && (isOOMBreak || !m_skipAllPauses);
}
References enabled(), and m_skipAllPauses.
Referenced by v8_inspector::V8Debugger::BreakOnInstrumentation(), cancelPauseOnNextStatement(), v8_inspector::V8Debugger::disable(), v8_inspector::V8Debugger::handleProgramBreak(), and schedulePauseOnNextStatement().
breakProgram()
void v8_inspector::V8DebuggerAgentImpl::breakProgram (const String16 & breakReason, std::unique_ptr< protocol::DictionaryValue > data)
Definition at line 2294 of file v8-debugger-agent-impl.cc.
                                                 {
  if (!enabled() || m_skipAllPauses || !m_debugger->canBreakProgram()) return;
  std::vector<BreakReason> currentScheduledReason;
  currentScheduledReason.swap(m_breakReason);
  pushBreakDetails(breakReason, std::move(data));
  int contextGroupId = m_session->contextGroupId();
  int sessionId = m_session->sessionId();
  V8InspectorImpl* inspector = m_inspector;
  m_debugger->breakProgram(contextGroupId);
  // Check that session and |this| are still around.
  if (!inspector->sessionById(contextGroupId, sessionId)) return;
  if (!enabled()) return;
  popBreakDetails();
  m_breakReason.swap(currentScheduledReason);
  if (!m_breakReason.empty()) {
    m_debugger->setPauseOnNextCall(true, m_session->contextGroupId());
  }
}
References v8_inspector::V8Debugger::breakProgram(), v8_inspector::V8Debugger::canBreakProgram(), v8_inspector::V8InspectorSessionImpl::contextGroupId(), enabled(), m_breakReason, m_debugger, m_inspector, m_session, m_skipAllPauses, popBreakDetails(), pushBreakDetails(), v8_inspector::V8InspectorImpl::sessionById(), v8_inspector::V8InspectorSessionImpl::sessionId(), and v8_inspector::V8Debugger::setPauseOnNextCall().
cancelPauseOnNextStatement()
void v8_inspector::V8DebuggerAgentImpl::cancelPauseOnNextStatement ()
Definition at line 1458 of file v8-debugger-agent-impl.cc.
                                                     {
  if (isPaused() || !acceptsPause(false) || !m_breakpointsActive) return;
  if (m_breakReason.size() == 1) {
    m_debugger->setPauseOnNextCall(false, m_session->contextGroupId());
  }
  popBreakDetails();
}
References acceptsPause(), v8_inspector::V8InspectorSessionImpl::contextGroupId(), isPaused(), m_breakpointsActive, m_breakReason, m_debugger, m_session, popBreakDetails(), and v8_inspector::V8Debugger::setPauseOnNextCall().
clearBreakDetails()
void v8_inspector::V8DebuggerAgentImpl::clearBreakDetails ()
Definition at line 1443 of file v8-debugger-agent-impl.cc.
                                            {
  std::vector<BreakReason> emptyBreakReason;
  m_breakReason.swap(emptyBreakReason);
}
References m_breakReason.
Referenced by didPause(), disable(), and setBreakpointsActive().
continueToLocation()
Response v8_inspector::V8DebuggerAgentImpl::continueToLocation (std::unique_ptr< protocol::Debugger::Location > location, std::optional< String16 > targetCallFrames) [override]
Definition at line 934 of file v8-debugger-agent-impl.cc.
                                            {
  if (!enabled()) return Response::ServerError(kDebuggerNotEnabled);
  if (!isPaused()) return Response::ServerError(kDebuggerNotPaused);
  ScriptsMap::iterator it = m_scripts.find(location->getScriptId());
  if (it == m_scripts.end()) {
    return Response::ServerError("Cannot continue to specified location");
  }
  V8DebuggerScript* script = it->second.get();
  int contextId = script->executionContextId();
  InspectedContext* inspected = m_inspector->getContext(contextId);
  if (!inspected)
    return Response::ServerError("Cannot continue to specified location");
  v8::HandleScope handleScope(m_isolate);
  v8::Context::Scope contextScope(inspected->context());
  return m_debugger->continueToLocation(
      m_session->contextGroupId(), script, std::move(location),
      targetCallFrames.value_or(
          protocol::Debugger::ContinueToLocation::TargetCallFramesEnum::Any));
}
References v8_inspector::InspectedContext::context(), v8_inspector::V8InspectorSessionImpl::contextGroupId(), v8_inspector::V8Debugger::continueToLocation(), enabled(), v8_inspector::V8InspectorImpl::getContext(), isPaused(), v8_inspector::kDebuggerNotEnabled, v8_inspector::kDebuggerNotPaused, m_debugger, m_inspector, m_isolate, m_scripts, m_session, and v8::internal::script.
currentAsyncStackTrace()
std::unique_ptr< protocol::Runtime::StackTrace > v8_inspector::V8DebuggerAgentImpl::currentAsyncStackTrace () [private]
Definition at line 1860 of file v8-debugger-agent-impl.cc.
                                            {
  std::shared_ptr<AsyncStackTrace> asyncParent =
      m_debugger->currentAsyncParent();
  if (!asyncParent) return nullptr;
  return asyncParent->buildInspectorObject(
      m_debugger, m_debugger->maxAsyncCallChainDepth() - 1);
}
References v8_inspector::V8Debugger::currentAsyncParent(), m_debugger, and v8_inspector::V8Debugger::maxAsyncCallChainDepth().
Referenced by didPause(), and didPauseOnInstrumentation().
currentCallFrames()
Response v8_inspector::V8DebuggerAgentImpl::currentCallFrames (std::unique_ptr< protocol::Array< protocol::Debugger::CallFrame >> *) [private]
Definition at line 1774 of file v8-debugger-agent-impl.cc.
                                             {
  if (!isPaused()) {
    *result = std::make_unique<Array<CallFrame>>();
    return Response::Success();
  }
  v8::HandleScope handles(m_isolate);
  *result = std::make_unique<Array<CallFrame>>();
  auto iterator = v8::debug::StackTraceIterator::Create(m_isolate);
  int frameOrdinal = 0;
  for (; !iterator->Done(); iterator->Advance(), frameOrdinal++) {
    int contextId = iterator->GetContextId();
    InjectedScript* injectedScript = nullptr;
    if (contextId) m_session->findInjectedScript(contextId, injectedScript);
    String16 callFrameId = RemoteCallFrameId::serialize(
        m_inspector->isolateId(), contextId, frameOrdinal);
    v8::debug::Location loc = iterator->GetSourceLocation();
    std::unique_ptr<Array<Scope>> scopes;
    auto scopeIterator = iterator->GetScopeIterator();
    Response res =
        buildScopes(m_isolate, scopeIterator.get(), injectedScript, &scopes);
    if (!res.IsSuccess()) return res;
    std::unique_ptr<RemoteObject> protocolReceiver;
    if (injectedScript) {
      v8::Local<v8::Value> receiver;
      if (iterator->GetReceiver().ToLocal(&receiver)) {
        res = injectedScript->wrapObject(receiver, kBacktraceObjectGroup,
                                         WrapOptions({WrapMode::kIdOnly}),
                                         &protocolReceiver);
        if (!res.IsSuccess()) return res;
      }
    }
    if (!protocolReceiver) {
      protocolReceiver = RemoteObject::create()
                             .setType(RemoteObject::TypeEnum::Undefined)
                             .build();
    }
    v8::Local<v8::debug::Script> script = iterator->GetScript();
    DCHECK(!script.IsEmpty());
    std::unique_ptr<protocol::Debugger::Location> location =
        protocol::Debugger::Location::create()
            .setScriptId(String16::fromInteger(script->Id()))
            .setLineNumber(loc.GetLineNumber())
            .setColumnNumber(loc.GetColumnNumber())
            .build();
    auto frame = CallFrame::create()
                     .setCallFrameId(callFrameId)
                     .setFunctionName(toProtocolString(
                         m_isolate, iterator->GetFunctionDebugName()))
                     .setLocation(std::move(location))
                     .setUrl(String16())
                     .setScopeChain(std::move(scopes))
                     .setThis(std::move(protocolReceiver))
                     .setCanBeRestarted(iterator->CanBeRestarted())
                     .build();
    v8::debug::Location func_loc = iterator->GetFunctionLocation();
    if (!func_loc.IsEmpty()) {
      frame->setFunctionLocation(
          protocol::Debugger::Location::create()
              .setScriptId(String16::fromInteger(script->Id()))
              .setLineNumber(func_loc.GetLineNumber())
              .setColumnNumber(func_loc.GetColumnNumber())
              .build());
    }
    v8::Local<v8::Value> returnValue = iterator->GetReturnValue();
    if (!returnValue.IsEmpty() && injectedScript) {
      std::unique_ptr<RemoteObject> value;
      res =
          injectedScript->wrapObject(returnValue, kBacktraceObjectGroup,
                                     WrapOptions({WrapMode::kIdOnly}), &value);
      if (!res.IsSuccess()) return res;
      frame->setReturnValue(std::move(value));
    }
    (*result)->emplace_back(std::move(frame));
  }
  return Response::Success();
}
References v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::buildScopes(), v8::debug::StackTraceIterator::Create(), DCHECK, v8_inspector::V8InspectorSessionImpl::findInjectedScript(), v8_inspector::String16::fromInteger(), v8::debug::Location::GetColumnNumber(), v8::debug::Location::GetLineNumber(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8::debug::Location::IsEmpty(), v8_inspector::V8InspectorImpl::isolateId(), isPaused(), v8_inspector::kBacktraceObjectGroup, v8_inspector::kIdOnly, v8::internal::loc, m_inspector, m_isolate, m_session, v8::base::internal::result, v8::internal::script, v8_inspector::RemoteCallFrameId::serialize(), v8_inspector::toProtocolString(), v8::internal::compiler::Undefined, v8::internal::value, and v8_inspector::InjectedScript::wrapObject().
Referenced by didPause(), and didPauseOnInstrumentation().
currentExternalStackTrace()
std::unique_ptr< protocol::Runtime::StackTraceId > v8_inspector::V8DebuggerAgentImpl::currentExternalStackTrace () [private]
Definition at line 1869 of file v8-debugger-agent-impl.cc.
                                               {
  V8StackTraceId externalParent = m_debugger->currentExternalParent();
  if (externalParent.IsInvalid()) return nullptr;
  return protocol::Runtime::StackTraceId::create()
      .setId(stackTraceIdToString(externalParent.id))
      .setDebuggerId(
          internal::V8DebuggerId(externalParent.debugger_id).toString())
      .build();
}
References v8_inspector::V8Debugger::currentExternalParent(), v8_inspector::V8StackTraceId::debugger_id, v8_inspector::V8StackTraceId::id, v8_inspector::V8StackTraceId::IsInvalid(), m_debugger, v8_inspector::stackTraceIdToString(), and v8_inspector::internal::V8DebuggerId::toString().
Referenced by didPause(), and didPauseOnInstrumentation().
didContinue()
void v8_inspector::V8DebuggerAgentImpl::didContinue ()
Definition at line 2289 of file v8-debugger-agent-impl.cc.
                                      {
  m_frontend.resumed();
  m_frontend.flush();
}
References m_frontend.
Referenced by v8_inspector::V8Debugger::BreakOnInstrumentation().
didParseSource()
void v8_inspector::V8DebuggerAgentImpl::didParseSource (std::unique_ptr< V8DebuggerScript > script, bool success)
Definition at line 1944 of file v8-debugger-agent-impl.cc.
                                                          {
  v8::HandleScope handles(m_isolate);
  if (!success) {
    String16 scriptSource = script->source(0);
    script->setSourceURL(findSourceURL(scriptSource, false));
    script->setSourceMappingURL(findSourceMapURL(scriptSource, false));
    script->setBuildId(findDebugId(scriptSource, false));
  }
  int contextId = script->executionContextId();
  int contextGroupId = m_inspector->contextGroupId(contextId);
  InspectedContext* inspected =
      m_inspector->getContext(contextGroupId, contextId);
  std::unique_ptr<protocol::DictionaryValue> executionContextAuxData;
  if (inspected) {
    // Script reused between different groups/sessions can have a stale
    // execution context id.
    const String16& aux = inspected->auxData();
    std::vector<uint8_t> cbor;
    v8_crdtp::json::ConvertJSONToCBOR(
        v8_crdtp::span<uint16_t>(aux.characters16(), aux.length()), &cbor);
    executionContextAuxData = protocol::DictionaryValue::cast(
        protocol::Value::parseBinary(cbor.data(), cbor.size()));
  }
  bool isLiveEdit = script->isLiveEdit();
  bool hasSourceURLComment = script->hasSourceURLComment();
  bool isModule = script->isModule();
  String16 scriptId = script->scriptId();
  String16 scriptURL = script->sourceURL();
  String16 embedderName = script->embedderName();
  String16 scriptLanguage = getScriptLanguage(*script);
  std::optional<int> codeOffset;
  std::unique_ptr<Array<protocol::Debugger::DebugSymbols>> debugSymbols;
#if V8_ENABLE_WEBASSEMBLY
  if (script->getLanguage() == V8DebuggerScript::Language::WebAssembly) {
    codeOffset = script->codeOffset();
    getDebugSymbols(*script, &debugSymbols);
  }
#endif // V8_ENABLE_WEBASSEMBLY
  m_scripts[scriptId] = std::move(script);
  ScriptsMap::iterator scriptIterator = m_scripts.find(scriptId);
  DCHECK(scriptIterator != m_scripts.end());
  V8DebuggerScript* scriptRef = scriptIterator->second.get();
  // Release the strong reference once we exit 'didParseSource', to get notified
  // when debugger is the only one that holds the script. Has to be done after
  // script was added to m_scripts.
  DeferredMakeWeakScope weak_scope(*scriptRef);
  // V8 could create functions for parsed scripts before reporting and asks
  // inspector about blackboxed state, we should reset state each time when we
  // make any change that change isFunctionBlackboxed output - adding parsed
  // script is changing.
  scriptRef->resetBlackboxedStateCache();
  std::optional<String16> sourceMapURLParam = scriptRef->sourceMappingURL();
  const bool* isLiveEditParam = isLiveEdit ? &isLiveEdit : nullptr;
  const bool* hasSourceURLParam =
      hasSourceURLComment ? &hasSourceURLComment : nullptr;
  const bool* isModuleParam = isModule ? &isModule : nullptr;
  std::unique_ptr<V8StackTraceImpl> stack =
      V8StackTraceImpl::capture(m_inspector->debugger(), 1);
  std::unique_ptr<protocol::Runtime::StackTrace> stackTrace =
      stack && !stack->isEmpty()
          ? stack->buildInspectorObjectImpl(m_debugger, 0)
          : nullptr;
  if (!success) {
    m_frontend.scriptFailedToParse(
        scriptId, scriptURL, scriptRef->startLine(), scriptRef->startColumn(),
        scriptRef->endLine(), scriptRef->endColumn(), contextId,
        scriptRef->hash(), scriptRef->buildId(),
        std::move(executionContextAuxData), std::move(sourceMapURLParam),
        hasSourceURLParam, isModuleParam, scriptRef->length(),
        std::move(stackTrace), std::move(codeOffset), std::move(scriptLanguage),
        embedderName);
    return;
  }
  std::vector<protocol::DictionaryValue*> potentialBreakpoints;
  if (!scriptURL.isEmpty()) {
    protocol::DictionaryValue* breakpointsByUrl =
        m_state->getObject(DebuggerAgentState::breakpointsByUrl);
    if (breakpointsByUrl) {
      potentialBreakpoints.push_back(breakpointsByUrl->getObject(scriptURL));
    }
    potentialBreakpoints.push_back(
        m_state->getObject(DebuggerAgentState::breakpointsByRegex));
  }
  protocol::DictionaryValue* breakpointsByScriptHash =
      m_state->getObject(DebuggerAgentState::breakpointsByScriptHash);
  if (breakpointsByScriptHash) {
    potentialBreakpoints.push_back(
        breakpointsByScriptHash->getObject(scriptRef->hash()));
  }
  protocol::DictionaryValue* breakpointHints =
      m_state->getObject(DebuggerAgentState::breakpointHints);
  std::map<String16, std::unique_ptr<protocol::Debugger::Location>>
      resolvedBreakpoints;
  for (auto breakpoints : potentialBreakpoints) {
    if (!breakpoints) continue;
    for (size_t i = 0; i < breakpoints->size(); ++i) {
      auto breakpointWithCondition = breakpoints->at(i);
      String16 breakpointId = breakpointWithCondition.first;
      BreakpointType type;
      String16 selector;
      int lineNumber = 0;
      int columnNumber = 0;
      parseBreakpointId(breakpointId, &type, &selector, &lineNumber,
                        &columnNumber);
      Matcher matcher(m_inspector, type, selector);
      if (!matcher.matches(*scriptRef)) continue;
      // Make sure the session was not disabled by some re-entrant call
      // in the script matcher.
      DCHECK(enabled());
      String16 condition;
      breakpointWithCondition.second->asString(&condition);
      protocol::DictionaryValue* hint =
          breakpointHints ? breakpointHints->getObject(breakpointId) : nullptr;
      if (hint) {
        adjustBreakpointLocation(*scriptRef, hint, &lineNumber, &columnNumber);
      }
      std::unique_ptr<protocol::Debugger::Location> location =
          setBreakpointImpl(breakpointId, scriptId, condition, lineNumber,
                            columnNumber);
      if (location)
        resolvedBreakpoints.emplace(breakpointId, std::move(location));
    }
  }
  auto resolvedBreakpointObjects =
      !resolvedBreakpoints.empty()
          ? std::make_unique<std::vector<
                std::unique_ptr<protocol::Debugger::ResolvedBreakpoint>>>()
          : nullptr;
  for (const auto& pair : resolvedBreakpoints) {
    resolvedBreakpointObjects->emplace_back(
        protocol::Debugger::ResolvedBreakpoint::create()
            .setBreakpointId(pair.first)
            .setLocation(pair.second->Clone())
            .build());
  }
  m_frontend.scriptParsed(
      scriptId, scriptURL, scriptRef->startLine(), scriptRef->startColumn(),
      scriptRef->endLine(), scriptRef->endColumn(), contextId,
      scriptRef->hash(), scriptRef->buildId(),
      std::move(executionContextAuxData), isLiveEditParam,
      std::move(sourceMapURLParam), hasSourceURLParam, isModuleParam,
      scriptRef->length(), std::move(stackTrace), std::move(codeOffset),
      std::move(scriptLanguage), std::move(debugSymbols), embedderName,
      std::move(resolvedBreakpointObjects));
  for (auto& pair : resolvedBreakpoints) {
    m_frontend.breakpointResolved(pair.first, std::move(pair.second));
  }
  setScriptInstrumentationBreakpointIfNeeded(scriptRef);
}
References v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::adjustBreakpointLocation(), v8_inspector::InspectedContext::auxData(), v8_inspector::DebuggerAgentState::breakpointHints, v8_inspector::DebuggerAgentState::breakpointsByRegex, v8_inspector::DebuggerAgentState::breakpointsByScriptHash, v8_inspector::DebuggerAgentState::breakpointsByUrl, v8_inspector::V8DebuggerScript::buildId(), v8_inspector::V8StackTraceImpl::capture(), v8_inspector::String16::characters16(), v8_inspector::V8InspectorImpl::contextGroupId(), DCHECK, v8_inspector::V8InspectorImpl::debugger(), enabled(), v8_inspector::V8DebuggerScript::endColumn(), v8_inspector::V8DebuggerScript::endLine(), v8_inspector::findDebugId(), v8_inspector::findSourceMapURL(), v8_inspector::findSourceURL(), v8_inspector::V8InspectorImpl::getContext(), v8_inspector::getScriptLanguage(), v8_inspector::V8DebuggerScript::hash(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8_inspector::String16::isEmpty(), v8_inspector::String16::length(), v8_inspector::V8DebuggerScript::length(), m_debugger, m_frontend, m_inspector, m_isolate, m_scripts, m_state, v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::parseBreakpointId(), v8_inspector::V8DebuggerScript::resetBlackboxedStateCache(), v8::internal::script, setBreakpointImpl(), setScriptInstrumentationBreakpointIfNeeded(), v8_inspector::V8DebuggerScript::sourceMappingURL(), v8::internal::stack, v8_inspector::V8DebuggerScript::startColumn(), v8_inspector::V8DebuggerScript::startLine(), v8::internal::tracing::type, and v8_inspector::V8DebuggerScript::WebAssembly.
Referenced by enableImpl().
didPause()
void v8_inspector::V8DebuggerAgentImpl::didPause (int contextId, v8::Local< v8::Value > exception, const std::vector< v8::debug::BreakpointId > & hitBreakpoints, v8::debug::ExceptionType exceptionType, bool isUncaught, v8::debug::BreakReasons breakReasons)
Definition at line 2172 of file v8-debugger-agent-impl.cc.
                                      {
  v8::HandleScope handles(m_isolate);
  std::vector<BreakReason> hitReasons;
  if (breakReasons.contains(v8::debug::BreakReason::kOOM)) {
    hitReasons.push_back(
        std::make_pair(protocol::Debugger::Paused::ReasonEnum::OOM, nullptr));
  } else if (breakReasons.contains(v8::debug::BreakReason::kAssert)) {
    hitReasons.push_back(std::make_pair(
        protocol::Debugger::Paused::ReasonEnum::Assert, nullptr));
  } else if (breakReasons.contains(v8::debug::BreakReason::kException)) {
    InjectedScript* injectedScript = nullptr;
    m_session->findInjectedScript(contextId, injectedScript);
    if (injectedScript) {
      String16 breakReason =
          exceptionType == v8::debug::kPromiseRejection
              ? protocol::Debugger::Paused::ReasonEnum::PromiseRejection
              : protocol::Debugger::Paused::ReasonEnum::Exception;
      std::unique_ptr<protocol::Runtime::RemoteObject> obj;
      injectedScript->wrapObject(exception, kBacktraceObjectGroup,
                                 WrapOptions({WrapMode::kIdOnly}), &obj);
      std::unique_ptr<protocol::DictionaryValue> breakAuxData;
      if (obj) {
        std::vector<uint8_t> serialized;
        obj->AppendSerialized(&serialized);
        breakAuxData = protocol::DictionaryValue::cast(
            protocol::Value::parseBinary(serialized.data(), serialized.size()));
        breakAuxData->setBoolean("uncaught", isUncaught);
      }
      hitReasons.push_back(
          std::make_pair(breakReason, std::move(breakAuxData)));
    }
  }
  if (breakReasons.contains(v8::debug::BreakReason::kStep) ||
      breakReasons.contains(v8::debug::BreakReason::kAsyncStep)) {
    hitReasons.push_back(
        std::make_pair(protocol::Debugger::Paused::ReasonEnum::Step, nullptr));
  }
  auto hitBreakpointIds = std::make_unique<Array<String16>>();
  bool hitRegularBreakpoint = false;
  for (const auto& id : hitBreakpoints) {
    auto breakpointIterator = m_debuggerBreakpointIdToBreakpointId.find(id);
    if (breakpointIterator == m_debuggerBreakpointIdToBreakpointId.end()) {
      continue;
    }
    const String16& breakpointId = breakpointIterator->second;
    hitBreakpointIds->emplace_back(breakpointId);
    BreakpointType type;
    parseBreakpointId(breakpointId, &type);
    if (type == BreakpointType::kDebugCommand) {
      hitReasons.push_back(std::make_pair(
          protocol::Debugger::Paused::ReasonEnum::DebugCommand, nullptr));
    } else {
      hitRegularBreakpoint = true;
    }
  }
  for (size_t i = 0; i < m_breakReason.size(); ++i) {
    hitReasons.push_back(std::move(m_breakReason[i]));
  }
  clearBreakDetails();
  // Make sure that we only include (other: nullptr) once.
  const BreakReason otherHitReason =
      std::make_pair(protocol::Debugger::Paused::ReasonEnum::Other, nullptr);
  const bool otherBreakReasons =
      hitRegularBreakpoint || hitBreakReasonEncodedAsOther(breakReasons);
  if (otherBreakReasons && std::find(hitReasons.begin(), hitReasons.end(),
                                     otherHitReason) == hitReasons.end()) {
    hitReasons.push_back(
        std::make_pair(protocol::Debugger::Paused::ReasonEnum::Other, nullptr));
  }
  // We should always know why we pause: either the pause relates to this agent
  // (`hitReason` is non empty), or it relates to another agent (hit a
  // breakpoint there, or a triggered pause was scheduled by other agent).
  DCHECK(hitReasons.size() > 0 || !hitBreakpoints.empty() ||
         breakReasons.contains(v8::debug::BreakReason::kAgent));
  String16 breakReason = protocol::Debugger::Paused::ReasonEnum::Other;
  std::unique_ptr<protocol::DictionaryValue> breakAuxData;
  if (hitReasons.size() == 1) {
    breakReason = hitReasons[0].first;
    breakAuxData = std::move(hitReasons[0].second);
  } else if (hitReasons.size() > 1) {
    breakReason = protocol::Debugger::Paused::ReasonEnum::Ambiguous;
    std::unique_ptr<protocol::ListValue> reasons =
        protocol::ListValue::create();
    for (size_t i = 0; i < hitReasons.size(); ++i) {
      std::unique_ptr<protocol::DictionaryValue> reason =
          protocol::DictionaryValue::create();
      reason->setString("reason", hitReasons[i].first);
      if (hitReasons[i].second)
        reason->setObject("auxData", std::move(hitReasons[i].second));
      reasons->pushValue(std::move(reason));
    }
    breakAuxData = protocol::DictionaryValue::create();
    breakAuxData->setArray("reasons", std::move(reasons));
  }
  std::unique_ptr<Array<CallFrame>> protocolCallFrames;
  Response response = currentCallFrames(&protocolCallFrames);
  if (!response.IsSuccess())
    protocolCallFrames = std::make_unique<Array<CallFrame>>();
  v8::debug::NotifyDebuggerPausedEventSent(m_debugger->isolate());
  m_frontend.paused(std::move(protocolCallFrames), breakReason,
                    std::move(breakAuxData), std::move(hitBreakpointIds),
                    currentAsyncStackTrace(), currentExternalStackTrace());
}
References clearBreakDetails(), v8::base::EnumSet< E, T >::contains(), currentAsyncStackTrace(), currentCallFrames(), currentExternalStackTrace(), DCHECK, v8_inspector::V8InspectorSessionImpl::findInjectedScript(), v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::hitBreakReasonEncodedAsOther(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8_inspector::V8Debugger::isolate(), v8::debug::kAgent, v8::debug::kAssert, v8::debug::kAsyncStep, v8_inspector::kBacktraceObjectGroup, v8::debug::kException, v8_inspector::kIdOnly, v8::debug::kOOM, v8::debug::kPromiseRejection, v8::debug::kStep, m_breakReason, m_debugger, m_debuggerBreakpointIdToBreakpointId, m_frontend, m_isolate, m_session, v8::debug::NotifyDebuggerPausedEventSent(), v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::parseBreakpointId(), v8::internal::tracing::type, and v8_inspector::InjectedScript::wrapObject().
Referenced by enableImpl().
didPauseOnInstrumentation()
void v8_inspector::V8DebuggerAgentImpl::didPauseOnInstrumentation (v8::debug::BreakpointId instrumentationId)
Definition at line 2136 of file v8-debugger-agent-impl.cc.
                                           {
  String16 breakReason = protocol::Debugger::Paused::ReasonEnum::Other;
  std::unique_ptr<protocol::DictionaryValue> breakAuxData;
  std::unique_ptr<Array<CallFrame>> protocolCallFrames;
  Response response = currentCallFrames(&protocolCallFrames);
  if (!response.IsSuccess())
    protocolCallFrames = std::make_unique<Array<CallFrame>>();
  if (m_debuggerBreakpointIdToBreakpointId.find(instrumentationId) !=
      m_debuggerBreakpointIdToBreakpointId.end()) {
    DCHECK_GT(protocolCallFrames->size(), 0);
    if (!protocolCallFrames->empty()) {
      m_instrumentationFinished = false;
      breakReason = protocol::Debugger::Paused::ReasonEnum::Instrumentation;
      const String16 scriptId =
          protocolCallFrames->at(0)->getLocation()->getScriptId();
      DCHECK_NE(m_scripts.find(scriptId), m_scripts.end());
      const auto& script = m_scripts[scriptId];
      breakAuxData = protocol::DictionaryValue::create();
      breakAuxData->setString("scriptId", script->scriptId());
      breakAuxData->setString("url", script->sourceURL());
      if (!script->sourceMappingURL().isEmpty()) {
        breakAuxData->setString("sourceMapURL", (script->sourceMappingURL()));
      }
    }
  }
  m_frontend.paused(std::move(protocolCallFrames), breakReason,
                    std::move(breakAuxData),
                    std::make_unique<Array<String16>>(),
                    currentAsyncStackTrace(), currentExternalStackTrace());
}
References currentAsyncStackTrace(), currentCallFrames(), currentExternalStackTrace(), DCHECK_GT, DCHECK_NE, m_debuggerBreakpointIdToBreakpointId, m_frontend, m_instrumentationFinished, m_scripts, and v8::internal::script.
disable()
Response v8_inspector::V8DebuggerAgentImpl::disable () [override]
Definition at line 482 of file v8-debugger-agent-impl.cc.
                                      {
  if (!enabled()) return Response::Success();
  m_state->remove(DebuggerAgentState::breakpointsByRegex);
  m_state->remove(DebuggerAgentState::breakpointsByUrl);
  m_state->remove(DebuggerAgentState::breakpointsByScriptHash);
  m_state->remove(DebuggerAgentState::breakpointHints);
  m_state->remove(DebuggerAgentState::instrumentationBreakpoints);
  m_state->setInteger(DebuggerAgentState::pauseOnExceptionsState,
                      v8::debug::NoBreakOnException);
  m_state->setInteger(DebuggerAgentState::asyncCallStackDepth, 0);
  if (m_breakpointsActive) {
    m_debugger->setBreakpointsActive(false);
    m_breakpointsActive = false;
  }
  m_blackboxedPositions.clear();
  m_blackboxPattern.reset();
  resetBlackboxedStateCache();
  m_skipList.clear();
  m_scripts.clear();
  m_cachedScripts.clear();
  m_cachedScriptSize = 0;
  m_maxScriptCacheSize = 0;
  m_state->setDouble(DebuggerAgentState::maxScriptCacheSize, 0);
  for (const auto& it : m_debuggerBreakpointIdToBreakpointId) {
    m_debugger->removeBreakpoint(it.first);
  }
  m_breakpointIdToDebuggerBreakpointIds.clear();
  m_debuggerBreakpointIdToBreakpointId.clear();
  m_wasmDisassemblies.clear();
  m_debugger->setAsyncCallStackDepth(this, 0);
  clearBreakDetails();
  m_skipAllPauses = false;
  m_state->setBoolean(DebuggerAgentState::skipAllPauses, false);
  m_state->remove(DebuggerAgentState::blackboxPattern);
  m_enableState = kDisabled;
  m_instrumentationFinished = true;
  m_state->setBoolean(DebuggerAgentState::debuggerEnabled, false);
  m_debugger->disable();
  return Response::Success();
}
References v8_inspector::DebuggerAgentState::asyncCallStackDepth, v8_inspector::DebuggerAgentState::blackboxPattern, v8_inspector::DebuggerAgentState::breakpointHints, v8_inspector::DebuggerAgentState::breakpointsByRegex, v8_inspector::DebuggerAgentState::breakpointsByScriptHash, v8_inspector::DebuggerAgentState::breakpointsByUrl, clearBreakDetails(), v8_inspector::DebuggerAgentState::debuggerEnabled, v8_inspector::V8Debugger::disable(), enabled(), v8_inspector::DebuggerAgentState::instrumentationBreakpoints, kDisabled, m_blackboxedPositions, m_blackboxPattern, m_breakpointIdToDebuggerBreakpointIds, m_breakpointsActive, m_cachedScripts, m_cachedScriptSize, m_debugger, m_debuggerBreakpointIdToBreakpointId, m_enableState, m_instrumentationFinished, m_maxScriptCacheSize, m_scripts, m_skipAllPauses, m_skipList, m_state, m_wasmDisassemblies, v8_inspector::DebuggerAgentState::maxScriptCacheSize, v8::debug::NoBreakOnException, v8_inspector::DebuggerAgentState::pauseOnExceptionsState, v8_inspector::V8Debugger::removeBreakpoint(), resetBlackboxedStateCache(), v8_inspector::V8Debugger::setAsyncCallStackDepth(), v8_inspector::V8Debugger::setBreakpointsActive(), and v8_inspector::DebuggerAgentState::skipAllPauses.
Referenced by stop().
disassembleWasmModule()
Response v8_inspector::V8DebuggerAgentImpl::disassembleWasmModule (const String16 & in_scriptId, std::optional< String16 > * out_streamId, int * out_totalNumberOfLines, std::unique_ptr< protocol::Array< int >> * out_functionBodyOffsets, std::unique_ptr< protocol::Debugger::WasmDisassemblyChunk > * out_chunk) [override]
Definition at line 1325 of file v8-debugger-agent-impl.cc.
                                                                    {
#if V8_ENABLE_WEBASSEMBLY
  if (!enabled()) return Response::ServerError(kDebuggerNotEnabled);
  ScriptsMap::iterator it = m_scripts.find(in_scriptId);
  std::unique_ptr<DisassemblyCollectorImpl> collector =
      std::make_unique<DisassemblyCollectorImpl>();
  std::vector<int> functionBodyOffsets;
  if (it != m_scripts.end()) {
    V8DebuggerScript* script = it->second.get();
    if (script->getLanguage() != V8DebuggerScript::Language::WebAssembly) {
      return Response::InvalidParams("Script with id " + in_scriptId.utf8() +
                                     " is not WebAssembly");
    }
    script->Disassemble(collector.get(), &functionBodyOffsets);
  } else {
    auto cachedScriptIt =
        std::find_if(m_cachedScripts.begin(), m_cachedScripts.end(),
                     [&in_scriptId](const CachedScript& cachedScript) {
                       return cachedScript.scriptId == in_scriptId;
                     });
    if (cachedScriptIt == m_cachedScripts.end()) {
      return Response::InvalidParams("No script for id: " + in_scriptId.utf8());
    }
    v8::debug::Disassemble(v8::base::VectorOf(cachedScriptIt->bytecode),
                           collector.get(), &functionBodyOffsets);
  }
  *out_totalNumberOfLines =
      static_cast<int>(collector->total_number_of_lines());
  *out_functionBodyOffsets =
      std::make_unique<protocol::Array<int>>(std::move(functionBodyOffsets));
  // Even an empty module would disassemble to "(module)", never to zero lines.
  DCHECK(collector->HasNextChunk());
  DisassemblyChunk chunk(collector->NextChunk());
  *out_chunk = protocol::Debugger::WasmDisassemblyChunk::create()
                   .setBytecodeOffsets(std::make_unique<protocol::Array<int>>(
                       std::move(chunk.lineOffsets)))
                   .setLines(std::make_unique<protocol::Array<String16>>(
                       std::move(chunk.lines)))
                   .build();
  if (collector->HasNextChunk()) {
    String16 streamId = String16::fromInteger(m_nextWasmDisassemblyStreamId++);
    *out_streamId = streamId;
    m_wasmDisassemblies[streamId] = std::move(collector);
  }
  return Response::Success();
#else
  return Response::ServerError("WebAssembly is disabled");
#endif // V8_ENABLE_WEBASSEMBLY
}
References DCHECK, v8::internal::wasm::Disassemble(), enabled(), v8_inspector::String16::fromInteger(), v8_inspector::kDebuggerNotEnabled, v8_inspector::DisassemblyChunk::lineOffsets, v8_inspector::DisassemblyChunk::lines, m_cachedScripts, m_nextWasmDisassemblyStreamId, m_scripts, m_wasmDisassemblies, v8::internal::script, v8_inspector::String16::utf8(), v8::base::VectorOf(), and v8_inspector::V8DebuggerScript::WebAssembly.
enable()
Response v8_inspector::V8DebuggerAgentImpl::enable (std::optional< double > maxScriptsCacheSize, String16 * outDebuggerId) [override]
Definition at line 463 of file v8-debugger-agent-impl.cc.
                                                              {
  if (m_enableState == kStopping)
    return Response::ServerError("Debugger is stopping");
  m_maxScriptCacheSize = v8::base::saturated_cast<size_t>(
      maxScriptsCacheSize.value_or(std::numeric_limits<double>::max()));
  m_state->setDouble(DebuggerAgentState::maxScriptCacheSize,
                     static_cast<double>(m_maxScriptCacheSize));
  *outDebuggerId =
      m_debugger->debuggerIdFor(m_session->contextGroupId()).toString();
  if (enabled()) return Response::Success();
  if (!m_inspector->client()->canExecuteScripts(m_session->contextGroupId()))
    return Response::ServerError("Script execution is prohibited");
  enableImpl();
  return Response::Success();
}
References v8_inspector::V8InspectorClient::canExecuteScripts(), v8_inspector::V8InspectorImpl::client(), v8_inspector::V8InspectorSessionImpl::contextGroupId(), v8_inspector::V8Debugger::debuggerIdFor(), enabled(), enableImpl(), kStopping, m_debugger, m_enableState, m_inspector, m_maxScriptCacheSize, m_session, m_state, v8_inspector::DebuggerAgentState::maxScriptCacheSize, and v8_inspector::internal::V8DebuggerId::toString().
enabled()
bool v8_inspector::V8DebuggerAgentImpl::enabled () const [inline]
Definition at line 160 of file v8-debugger-agent-impl.h.
{ return m_enableState == kEnabled; }
References kEnabled, and m_enableState.
Referenced by acceptsPause(), v8_inspector::V8Debugger::BreakOnInstrumentation(), breakProgram(), continueToLocation(), didParseSource(), disable(), v8_inspector::V8RuntimeAgentImpl::disable(), disassembleWasmModule(), enable(), getScriptSource(), getWasmBytecode(), v8_inspector::V8Debugger::handleProgramBreak(), nextWasmDisassemblyChunk(), pause(), removeBreakpoint(), removeBreakpointImpl(), reset(), setAsyncCallStackDepth(), setBreakpoint(), setBreakpointByUrl(), setBreakpointImpl(), setBreakpointOnFunctionCall(), setBreakpointsActive(), v8_inspector::setFunctionBreakpoint(), setInstrumentationBreakpoint(), setPauseOnExceptions(), setReturnValue(), setScriptSource(), and setVariableValue().
enableImpl()
void v8_inspector::V8DebuggerAgentImpl::enableImpl () [private]
Definition at line 440 of file v8-debugger-agent-impl.cc.
                                     {
  m_enableState = kEnabled;
  m_state->setBoolean(DebuggerAgentState::debuggerEnabled, true);
  m_debugger->enable();
  std::vector<std::unique_ptr<V8DebuggerScript>> compiledScripts =
      m_debugger->getCompiledScripts(m_session->contextGroupId(), this);
  for (auto& script : compiledScripts) {
    didParseSource(std::move(script), true);
  }
  m_breakpointsActive = m_state->booleanProperty(
      DebuggerAgentState::breakpointsActiveWhenEnabled, true);
  if (m_breakpointsActive) {
    m_debugger->setBreakpointsActive(true);
  }
  if (isPaused()) {
    didPause(0, v8::Local<v8::Value>(), std::vector<v8::debug::BreakpointId>(),
             v8::debug::kException, false,
             v8::debug::BreakReasons({v8::debug::BreakReason::kAlreadyPaused}));
  }
}
References v8_inspector::DebuggerAgentState::breakpointsActiveWhenEnabled, v8_inspector::V8InspectorSessionImpl::contextGroupId(), v8_inspector::DebuggerAgentState::debuggerEnabled, didParseSource(), didPause(), v8_inspector::V8Debugger::enable(), v8_inspector::V8Debugger::getCompiledScripts(), isPaused(), v8::debug::kAlreadyPaused, kEnabled, v8::debug::kException, m_breakpointsActive, m_debugger, m_enableState, m_session, m_state, v8::internal::script, and v8_inspector::V8Debugger::setBreakpointsActive().
Referenced by enable(), and restore().
evaluateOnCallFrame()
Response v8_inspector::V8DebuggerAgentImpl::evaluateOnCallFrame (const String16 & callFrameId, const String16 & expression, std::optional< String16 > objectGroup, std::optional< bool > includeCommandLineAPI, std::optional< bool > silent, std::optional< bool > returnByValue, std::optional< bool > generatePreview, std::optional< bool > throwOnSideEffect, std::optional< double > timeout, std::unique_ptr< protocol::Runtime::RemoteObject > * result, std::unique_ptr< protocol::Runtime::ExceptionDetails > *) [override]
Definition at line 1574 of file v8-debugger-agent-impl.cc.
                                                                      {
  if (!isPaused()) return Response::ServerError(kDebuggerNotPaused);
  InjectedScript::CallFrameScope scope(m_session, callFrameId);
  Response response = scope.initialize();
  if (!response.IsSuccess()) return response;
  if (includeCommandLineAPI.value_or(false)) scope.installCommandLineAPI();
  if (silent.value_or(false)) scope.ignoreExceptionsAndMuteConsole();
  int frameOrdinal = static_cast<int>(scope.frameOrdinal());
  auto it = v8::debug::StackTraceIterator::Create(m_isolate, frameOrdinal);
  if (it->Done()) {
    return Response::ServerError("Could not find call frame with given id");
  }
  v8::MaybeLocal<v8::Value> maybeResultValue;
  {
    V8InspectorImpl::EvaluateScope evaluateScope(scope);
    if (timeout.has_value()) {
      response = evaluateScope.setTimeout(timeout.value() / 1000.0);
      if (!response.IsSuccess()) return response;
    }
    maybeResultValue = it->Evaluate(toV8String(m_isolate, expression),
                                    throwOnSideEffect.value_or(false));
  }
  // Re-initialize after running client's code, as it could have destroyed
  // context or session.
  response = scope.initialize();
  if (!response.IsSuccess()) return response;
  WrapOptions wrapOptions = generatePreview.value_or(false)
                                ? WrapOptions({WrapMode::kPreview})
                                : WrapOptions({WrapMode::kIdOnly});
  if (returnByValue.value_or(false))
    wrapOptions = WrapOptions({WrapMode::kJson});
  return scope.injectedScript()->wrapEvaluateResult(
      maybeResultValue, scope.tryCatch(), objectGroup.value_or(""), wrapOptions,
      throwOnSideEffect.value_or(false), result, exceptionDetails);
}
References v8::debug::StackTraceIterator::Create(), v8_inspector::InjectedScript::CallFrameScope::frameOrdinal(), v8_inspector::InjectedScript::Scope::ignoreExceptionsAndMuteConsole(), v8_inspector::InjectedScript::Scope::initialize(), v8_inspector::InjectedScript::Scope::injectedScript(), v8_inspector::InjectedScript::Scope::installCommandLineAPI(), isPaused(), v8_inspector::kDebuggerNotPaused, v8_inspector::kIdOnly, v8_inspector::kJson, v8_inspector::kPreview, m_isolate, m_session, v8::base::internal::result, v8_inspector::V8InspectorImpl::EvaluateScope::setTimeout(), v8_inspector::toV8String(), v8_inspector::InjectedScript::Scope::tryCatch(), and v8_inspector::InjectedScript::wrapEvaluateResult().
getPossibleBreakpoints()
Response v8_inspector::V8DebuggerAgentImpl::getPossibleBreakpoints (std::unique_ptr< protocol::Debugger::Location > start, std::unique_ptr< protocol::Debugger::Location > end, std::optional< bool > restrictToFunction, std::unique_ptr< protocol::Array< protocol::Debugger::BreakLocation >> * locations) [override]
Definition at line 868 of file v8-debugger-agent-impl.cc.
                   {
  String16 scriptId = start->getScriptId();
  if (start->getLineNumber() < 0 || start->getColumnNumber(0) < 0)
    return Response::ServerError(
        "start.lineNumber and start.columnNumber should be >= 0");
  v8::debug::Location v8Start(start->getLineNumber(),
                              start->getColumnNumber(0));
  v8::debug::Location v8End;
  if (end) {
    if (end->getScriptId() != scriptId)
      return Response::ServerError(
          "Locations should contain the same scriptId");
    int line = end->getLineNumber();
    int column = end->getColumnNumber(0);
    if (line < 0 || column < 0)
      return Response::ServerError(
          "end.lineNumber and end.columnNumber should be >= 0");
    v8End = v8::debug::Location(line, column);
  }
  auto it = m_scripts.find(scriptId);
  if (it == m_scripts.end()) return Response::ServerError("Script not found");
  std::vector<v8::debug::BreakLocation> v8Locations;
  {
    v8::HandleScope handleScope(m_isolate);
    int contextId = it->second->executionContextId();
    InspectedContext* inspected = m_inspector->getContext(contextId);
    if (!inspected) {
      return Response::ServerError("Cannot retrive script context");
    }
    v8::Context::Scope contextScope(inspected->context());
    v8::MicrotasksScope microtasks(inspected->context(),
                                   v8::MicrotasksScope::kDoNotRunMicrotasks);
    v8::TryCatch tryCatch(m_isolate);
    it->second->getPossibleBreakpoints(
        v8Start, v8End, restrictToFunction.value_or(false), &v8Locations);
  }
  *locations =
      std::make_unique<protocol::Array<protocol::Debugger::BreakLocation>>();
  // TODO(1106269): Return an error instead of capping the number of
  // breakpoints.
  const size_t numBreakpointsToSend =
      std::min(v8Locations.size(), kMaxNumBreakpoints);
  for (size_t i = 0; i < numBreakpointsToSend; ++i) {
    std::unique_ptr<protocol::Debugger::BreakLocation> breakLocation =
        protocol::Debugger::BreakLocation::create()
            .setScriptId(scriptId)
            .setLineNumber(v8Locations[i].GetLineNumber())
            .setColumnNumber(v8Locations[i].GetColumnNumber())
            .build();
    if (v8Locations[i].type() != v8::debug::kCommonBreakLocation) {
      breakLocation->setType(breakLocationType(v8Locations[i].type()));
    }
    (*locations)->emplace_back(std::move(breakLocation));
  }
  return Response::Success();
}
References v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::breakLocationType(), v8_inspector::InspectedContext::context(), v8::internal::compiler::end(), v8_inspector::V8InspectorImpl::getContext(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::debug::kCommonBreakLocation, v8::MicrotasksScope::kDoNotRunMicrotasks, v8_inspector::kMaxNumBreakpoints, m_inspector, m_isolate, m_scripts, and v8::internal::tracing::type.
getScriptSource()
Response v8_inspector::V8DebuggerAgentImpl::getScriptSource (const String16 & scriptId, String16 * scriptSource, std::optional< protocol::Binary > * bytecode) [override]
Definition at line 1230 of file v8-debugger-agent-impl.cc.
                                           {
  if (!enabled()) return Response::ServerError(kDebuggerNotEnabled);
  ScriptsMap::iterator it = m_scripts.find(scriptId);
  if (it == m_scripts.end()) {
    auto cachedScriptIt =
        std::find_if(m_cachedScripts.begin(), m_cachedScripts.end(),
                     [&scriptId](const CachedScript& cachedScript) {
                       return cachedScript.scriptId == scriptId;
                     });
    if (cachedScriptIt != m_cachedScripts.end()) {
      *scriptSource = cachedScriptIt->source;
      *bytecode = protocol::Binary::fromSpan(v8::MemorySpan<const uint8_t>(
          cachedScriptIt->bytecode.begin(), cachedScriptIt->bytecode.size()));
      return Response::Success();
    }
    return Response::ServerError("No script for id: " + scriptId.utf8());
  }
  *scriptSource = it->second->source(0);
#if V8_ENABLE_WEBASSEMBLY
  v8::MemorySpan<const uint8_t> span;
  if (it->second->wasmBytecode().To(&span)) {
    if (span.size() > kWasmBytecodeMaxLength) {
      return Response::ServerError(kWasmBytecodeExceedsTransferLimit);
    }
    *bytecode = protocol::Binary::fromSpan(span);
  }
#endif // V8_ENABLE_WEBASSEMBLY
  return Response::Success();
}
References enabled(), v8_inspector::protocol::Binary::fromSpan(), v8_inspector::kDebuggerNotEnabled, m_cachedScripts, m_scripts, v8::MemorySpan< T >::size(), and v8_inspector::String16::utf8().
getStackTrace()
Response v8_inspector::V8DebuggerAgentImpl::getStackTrace (std::unique_ptr< protocol::Runtime::StackTraceId > inStackTraceId, std::unique_ptr< protocol::Runtime::StackTrace > * outStackTrace) [override]
Definition at line 956 of file v8-debugger-agent-impl.cc.
                                                             {
  bool isOk = false;
  int64_t id = inStackTraceId->getId().toInteger64(&isOk);
  if (!isOk) return Response::ServerError("Invalid stack trace id");
  internal::V8DebuggerId debuggerId;
  if (inStackTraceId->hasDebuggerId()) {
    debuggerId =
        internal::V8DebuggerId(inStackTraceId->getDebuggerId(String16()));
  } else {
    debuggerId = m_debugger->debuggerIdFor(m_session->contextGroupId());
  }
  if (!debuggerId.isValid())
    return Response::ServerError("Invalid stack trace id");
  V8StackTraceId v8StackTraceId(id, debuggerId.pair());
  if (v8StackTraceId.IsInvalid())
    return Response::ServerError("Invalid stack trace id");
  auto stack =
      m_debugger->stackTraceFor(m_session->contextGroupId(), v8StackTraceId);
  if (!stack) {
    return Response::ServerError("Stack trace with given id is not found");
  }
  *outStackTrace = stack->buildInspectorObject(
      m_debugger, m_debugger->maxAsyncCallChainDepth());
  return Response::Success();
}
References v8_inspector::V8InspectorSessionImpl::contextGroupId(), v8_inspector::V8Debugger::debuggerIdFor(), v8_inspector::V8StackTraceId::IsInvalid(), v8_inspector::internal::V8DebuggerId::isValid(), m_debugger, m_session, v8_inspector::V8Debugger::maxAsyncCallChainDepth(), v8_inspector::internal::V8DebuggerId::pair(), v8::internal::stack, and v8_inspector::V8Debugger::stackTraceFor().
getWasmBytecode()
Response v8_inspector::V8DebuggerAgentImpl::getWasmBytecode (const String16 & scriptId, protocol::Binary * bytecode) [override]
Definition at line 1411 of file v8-debugger-agent-impl.cc.
                                                                        {
#if V8_ENABLE_WEBASSEMBLY
  if (!enabled()) return Response::ServerError(kDebuggerNotEnabled);
  ScriptsMap::iterator it = m_scripts.find(scriptId);
  if (it == m_scripts.end())
    return Response::ServerError("No script for id: " + scriptId.utf8());
  v8::MemorySpan<const uint8_t> span;
  if (!it->second->wasmBytecode().To(&span))
    return Response::ServerError("Script with id " + scriptId.utf8() +
                                 " is not WebAssembly");
  if (span.size() > kWasmBytecodeMaxLength) {
    return Response::ServerError(kWasmBytecodeExceedsTransferLimit);
  }
  *bytecode = protocol::Binary::fromSpan(span);
  return Response::Success();
#else
  return Response::ServerError("WebAssembly is disabled");
#endif // V8_ENABLE_WEBASSEMBLY
}
References enabled(), v8_inspector::protocol::Binary::fromSpan(), v8_inspector::kDebuggerNotEnabled, m_scripts, v8::MemorySpan< T >::size(), and v8_inspector::String16::utf8().
increaseCachedSkipStackGeneration()
void v8_inspector::V8DebuggerAgentImpl::increaseCachedSkipStackGeneration () [private]
instrumentationFinished()
bool v8_inspector::V8DebuggerAgentImpl::instrumentationFinished () [inline]
Definition at line 176 of file v8-debugger-agent-impl.h.
{ return m_instrumentationFinished; }
References m_instrumentationFinished.
Referenced by v8_inspector::V8Debugger::quitMessageLoopIfAgentsFinishedInstrumentation().
internalSetAsyncCallStackDepth()
void v8_inspector::V8DebuggerAgentImpl::internalSetAsyncCallStackDepth (int) [private]
isFunctionBlackboxed()
bool v8_inspector::V8DebuggerAgentImpl::isFunctionBlackboxed (const String16 & scriptId, const v8::debug::Location & start, const v8::debug::Location & end)
Definition at line 986 of file v8-debugger-agent-impl.cc.
                                                                           {
  ScriptsMap::iterator it = m_scripts.find(scriptId);
  if (it == m_scripts.end()) {
    // Unknown scripts are blackboxed.
    return true;
  }
  const String16& scriptSourceURL = it->second->sourceURL();
  if (m_blackboxPattern && !scriptSourceURL.isEmpty()
      && m_blackboxPattern->match(scriptSourceURL) != -1) {
    return true;
  }
  if (m_skipAnonymousScripts && scriptSourceURL.isEmpty()) {
    return true;
  }
  if (!m_blackboxedExecutionContexts.empty()) {
    int contextId = it->second->executionContextId();
    InspectedContext* inspected = m_inspector->getContext(contextId);
    if (inspected && m_blackboxedExecutionContexts.count(
                         inspected->uniqueId().toString()) > 0) {
      return true;
    }
  }
  auto itBlackboxedPositions = m_blackboxedPositions.find(scriptId);
  if (itBlackboxedPositions == m_blackboxedPositions.end()) return false;
  const std::vector<std::pair<int, int>>& ranges =
      itBlackboxedPositions->second;
  auto itStartRange = std::lower_bound(
      ranges.begin(), ranges.end(),
      std::make_pair(start.GetLineNumber(), start.GetColumnNumber()),
      positionComparator);
  auto itEndRange = std::lower_bound(
      itStartRange, ranges.end(),
      std::make_pair(end.GetLineNumber(), end.GetColumnNumber()),
      positionComparator);
  // Ranges array contains positions in script where blackbox state is changed.
  // [(0,0) ... ranges[0]) isn't blackboxed, [ranges[0] ... ranges[1]) is
  // blackboxed...
  return itStartRange == itEndRange &&
         std::distance(ranges.begin(), itStartRange) % 2;
}
References v8::internal::compiler::end(), v8::debug::Location::GetColumnNumber(), v8_inspector::V8InspectorImpl::getContext(), v8::debug::Location::GetLineNumber(), v8_inspector::String16::isEmpty(), m_blackboxedExecutionContexts, m_blackboxedPositions, m_blackboxPattern, m_inspector, m_scripts, m_skipAnonymousScripts, v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::positionComparator(), v8_inspector::internal::V8DebuggerId::toString(), and v8_inspector::InspectedContext::uniqueId().
Referenced by setScriptInstrumentationBreakpointIfNeeded().
isolate()
v8::Isolate* v8_inspector::V8DebuggerAgentImpl::isolate () [inline]
Definition at line 196 of file v8-debugger-agent-impl.h.
{ return m_isolate; }
References m_isolate.
isPaused()
bool v8_inspector::V8DebuggerAgentImpl::isPaused () const [private]
Definition at line 1879 of file v8-debugger-agent-impl.cc.
                                         {
  return m_debugger->isPausedInContextGroup(m_session->contextGroupId());
}
References v8_inspector::V8InspectorSessionImpl::contextGroupId(), v8_inspector::V8Debugger::isPausedInContextGroup(), m_debugger, and m_session.
Referenced by cancelPauseOnNextStatement(), continueToLocation(), currentCallFrames(), enableImpl(), evaluateOnCallFrame(), pause(), restartFrame(), resume(), schedulePauseOnNextStatement(), setReturnValue(), setVariableValue(), stepInto(), stepOut(), and stepOver().
nextWasmDisassemblyChunk()
Response v8_inspector::V8DebuggerAgentImpl::nextWasmDisassemblyChunk (const String16 & in_streamId, std::unique_ptr< protocol::Debugger::WasmDisassemblyChunk > * out_chunk) [override]
Definition at line 1379 of file v8-debugger-agent-impl.cc.
                                                                    {
#if V8_ENABLE_WEBASSEMBLY
  if (!enabled()) return Response::ServerError(kDebuggerNotEnabled);
  auto it = m_wasmDisassemblies.find(in_streamId);
  if (it == m_wasmDisassemblies.end()) {
    return Response::InvalidParams("No chunks available for stream " +
                                   in_streamId.utf8());
  }
  if (it->second->HasNextChunk()) {
    DisassemblyChunk chunk(it->second->NextChunk());
    *out_chunk = protocol::Debugger::WasmDisassemblyChunk::create()
                     .setBytecodeOffsets(std::make_unique<protocol::Array<int>>(
                         std::move(chunk.lineOffsets)))
                     .setLines(std::make_unique<protocol::Array<String16>>(
                         std::move(chunk.lines)))
                     .build();
  } else {
    *out_chunk =
        protocol::Debugger::WasmDisassemblyChunk::create()
            .setBytecodeOffsets(std::make_unique<protocol::Array<int>>())
            .setLines(std::make_unique<protocol::Array<String16>>())
            .build();
    m_wasmDisassemblies.erase(it);
  }
  return Response::Success();
#else
  return Response::ServerError("WebAssembly is disabled");
#endif // V8_ENABLE_WEBASSEMBLY
}
References enabled(), v8_inspector::kDebuggerNotEnabled, v8_inspector::DisassemblyChunk::lineOffsets, v8_inspector::DisassemblyChunk::lines, m_wasmDisassemblies, and v8_inspector::String16::utf8().
operator=()
V8DebuggerAgentImpl& v8_inspector::V8DebuggerAgentImpl::operator= (const V8DebuggerAgentImpl &) [delete]
pause()
Response v8_inspector::V8DebuggerAgentImpl::pause () [override]
Definition at line 1466 of file v8-debugger-agent-impl.cc.
                                    {
  if (!enabled()) return Response::ServerError(kDebuggerNotEnabled);
  if (m_debugger->isInInstrumentationPause()) {
    // If we are inside an instrumentation pause, remember the pause request
    // so that we can enter the requested pause once we are done
    // with the instrumentation.
    m_debugger->requestPauseAfterInstrumentation();
  } else if (isPaused()) {
    // Ignore the pause request if we are already paused.
    return Response::Success();
  } else if (m_debugger->canBreakProgram()) {
    m_debugger->interruptAndBreak(m_session->contextGroupId());
  } else {
    pushBreakDetails(protocol::Debugger::Paused::ReasonEnum::Other, nullptr);
    m_debugger->setPauseOnNextCall(true, m_session->contextGroupId());
  }
  return Response::Success();
}
References v8_inspector::V8Debugger::canBreakProgram(), v8_inspector::V8InspectorSessionImpl::contextGroupId(), enabled(), v8_inspector::V8Debugger::interruptAndBreak(), v8_inspector::V8Debugger::isInInstrumentationPause(), isPaused(), v8_inspector::kDebuggerNotEnabled, m_debugger, m_session, pushBreakDetails(), v8_inspector::V8Debugger::requestPauseAfterInstrumentation(), and v8_inspector::V8Debugger::setPauseOnNextCall().
pauseOnAsyncCall()
Response v8_inspector::V8DebuggerAgentImpl::pauseOnAsyncCall (std::unique_ptr< protocol::Runtime::StackTraceId > inParentStackTraceId) [override]
Definition at line 1540 of file v8-debugger-agent-impl.cc.
                                                                     {
  // Deprecated, just return OK.
  return Response::Success();
}
popBreakDetails()
void v8_inspector::V8DebuggerAgentImpl::popBreakDetails () [private]
Definition at line 1438 of file v8-debugger-agent-impl.cc.
                                          {
  if (m_breakReason.empty()) return;
  m_breakReason.pop_back();
}
References m_breakReason.
Referenced by breakProgram(), and cancelPauseOnNextStatement().
processSkipList()
Response v8_inspector::V8DebuggerAgentImpl::processSkipList (protocol::Array< protocol::Debugger::LocationRange > & skipList) [private]
Definition at line 2379 of file v8-debugger-agent-impl.cc.
                                                            {
  std::unordered_map<String16, std::vector<std::pair<int, int>>> skipListInit;
  for (std::unique_ptr<protocol::Debugger::LocationRange>& range : skipList) {
    protocol::Debugger::ScriptPosition* start = range->getStart();
    protocol::Debugger::ScriptPosition* end = range->getEnd();
    String16 scriptId = range->getScriptId();
    auto it = m_scripts.find(scriptId);
    if (it == m_scripts.end())
      return Response::ServerError("No script with passed id.");
    Response res = isValidPosition(start);
    if (res.IsError()) return res;
    res = isValidPosition(end);
    if (res.IsError()) return res;
    skipListInit[scriptId].emplace_back(start->getLineNumber(),
                                        start->getColumnNumber());
    skipListInit[scriptId].emplace_back(end->getLineNumber(),
                                        end->getColumnNumber());
  }
  // Verify that the skipList is sorted, and that all ranges
  // are properly defined (start comes before end).
  for (const auto& skipListPair : skipListInit) {
    Response res = isValidRangeOfPositions(skipListPair.second);
    if (res.IsError()) return res;
  }
  m_skipList = std::move(skipListInit);
  return Response::Success();
}
References v8::internal::compiler::end(), v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::isValidPosition(), v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::isValidRangeOfPositions(), m_scripts, and m_skipList.
Referenced by stepInto(), and stepOver().
pushBreakDetails()
void v8_inspector::V8DebuggerAgentImpl::pushBreakDetails (const String16 & breakReason, std::unique_ptr< protocol::DictionaryValue > breakAuxData) [private]
Definition at line 1432 of file v8-debugger-agent-impl.cc.
                                                         {
  m_breakReason.push_back(std::make_pair(breakReason, std::move(breakAuxData)));
}
References m_breakReason.
Referenced by breakProgram(), pause(), and schedulePauseOnNextStatement().
removeBreakpoint()
Response v8_inspector::V8DebuggerAgentImpl::removeBreakpoint (const String16 & breakpointId) [override]
Definition at line 784 of file v8-debugger-agent-impl.cc.
                                                                           {
  if (!enabled()) return Response::ServerError(kDebuggerNotEnabled);
  BreakpointType type;
  String16 selector;
  if (!parseBreakpointId(breakpointId, &type, &selector)) {
    return Response::Success();
  }
  Matcher matcher(m_inspector, type, selector);
  protocol::DictionaryValue* breakpoints = nullptr;
  switch (type) {
    case BreakpointType::kByUrl: {
      protocol::DictionaryValue* breakpointsByUrl =
          m_state->getObject(DebuggerAgentState::breakpointsByUrl);
      if (breakpointsByUrl) {
        breakpoints = breakpointsByUrl->getObject(selector);
      }
    } break;
    case BreakpointType::kByScriptHash: {
      protocol::DictionaryValue* breakpointsByScriptHash =
          m_state->getObject(DebuggerAgentState::breakpointsByScriptHash);
      if (breakpointsByScriptHash) {
        breakpoints = breakpointsByScriptHash->getObject(selector);
      }
    } break;
    case BreakpointType::kByUrlRegex:
      breakpoints = m_state->getObject(DebuggerAgentState::breakpointsByRegex);
      break;
    case BreakpointType::kInstrumentationBreakpoint:
      breakpoints =
          m_state->getObject(DebuggerAgentState::instrumentationBreakpoints);
      break;
    default:
      break;
  }
  if (breakpoints) breakpoints->remove(breakpointId);
  protocol::DictionaryValue* breakpointHints =
      m_state->getObject(DebuggerAgentState::breakpointHints);
  if (breakpointHints) breakpointHints->remove(breakpointId);
  // Get a list of scripts to remove breakpoints.
  // TODO(duongn): we can do better here if from breakpoint id we can tell it is
  // not Wasm breakpoint.
  std::vector<V8DebuggerScript*> scripts;
  for (const auto& scriptIter : m_scripts) {
    const bool scriptSelectorMatch = matcher.matches(*scriptIter.second);
    // Make sure the session was not disabled by some re-entrant call
    // in the script matcher.
    DCHECK(enabled());
    const bool isInstrumentation =
        type == BreakpointType::kInstrumentationBreakpoint;
    if (!scriptSelectorMatch && !isInstrumentation) continue;
    V8DebuggerScript* script = scriptIter.second.get();
    if (script->getLanguage() == V8DebuggerScript::Language::WebAssembly) {
      scripts.push_back(script);
    }
  }
  removeBreakpointImpl(breakpointId, scripts);
  return Response::Success();
}
References v8_inspector::DebuggerAgentState::breakpointHints, v8_inspector::DebuggerAgentState::breakpointsByRegex, v8_inspector::DebuggerAgentState::breakpointsByScriptHash, v8_inspector::DebuggerAgentState::breakpointsByUrl, DCHECK, enabled(), v8_inspector::DebuggerAgentState::instrumentationBreakpoints, v8_inspector::kDebuggerNotEnabled, m_inspector, m_scripts, m_state, v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::parseBreakpointId(), removeBreakpointImpl(), v8::internal::script, v8::internal::tracing::type, and v8_inspector::V8DebuggerScript::WebAssembly.
removeBreakpointFor()
void v8_inspector::V8DebuggerAgentImpl::removeBreakpointFor (v8::Local< v8::Function > function, BreakpointSource source)
Definition at line 2331 of file v8-debugger-agent-impl.cc.
                                                                       {
  String16 breakpointId = generateBreakpointId(
      source == DebugCommandBreakpointSource ? BreakpointType::kDebugCommand
                                             : BreakpointType::kMonitorCommand,
      function);
  std::vector<V8DebuggerScript*> scripts;
  removeBreakpointImpl(breakpointId, scripts);
}
References DebugCommandBreakpointSource, v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::generateBreakpointId(), and removeBreakpointImpl().
Referenced by v8_inspector::setFunctionBreakpoint().
removeBreakpointImpl()
void v8_inspector::V8DebuggerAgentImpl::removeBreakpointImpl (const String16 & breakpointId, const std::vector< V8DebuggerScript * > & scripts) [private]
Definition at line 845 of file v8-debugger-agent-impl.cc.
                                                 {
  DCHECK(enabled());
  BreakpointIdToDebuggerBreakpointIdsMap::iterator
      debuggerBreakpointIdsIterator =
          m_breakpointIdToDebuggerBreakpointIds.find(breakpointId);
  if (debuggerBreakpointIdsIterator ==
      m_breakpointIdToDebuggerBreakpointIds.end()) {
    return;
  }
  for (const auto& id : debuggerBreakpointIdsIterator->second) {
#if V8_ENABLE_WEBASSEMBLY
    for (auto& script : scripts) {
      script->removeWasmBreakpoint(id);
    }
#endif // V8_ENABLE_WEBASSEMBLY
    m_debugger->removeBreakpoint(id);
    m_debuggerBreakpointIdToBreakpointId.erase(id);
  }
  m_breakpointIdToDebuggerBreakpointIds.erase(breakpointId);
}
References DCHECK, enabled(), m_breakpointIdToDebuggerBreakpointIds, m_debugger, m_debuggerBreakpointIdToBreakpointId, v8_inspector::V8Debugger::removeBreakpoint(), and v8::internal::script.
Referenced by removeBreakpoint(), and removeBreakpointFor().
reset()
void v8_inspector::V8DebuggerAgentImpl::reset ()
Definition at line 2341 of file v8-debugger-agent-impl.cc.
                                {
  if (!enabled()) return;
  m_blackboxedPositions.clear();
  resetBlackboxedStateCache();
  m_skipList.clear();
  m_scripts.clear();
  m_cachedScripts.clear();
  m_cachedScriptSize = 0;
  m_debugger->allAsyncTasksCanceled();
  m_blackboxedExecutionContexts.clear();
}
References v8_inspector::V8Debugger::allAsyncTasksCanceled(), enabled(), m_blackboxedExecutionContexts, m_blackboxedPositions, m_cachedScripts, m_cachedScriptSize, m_debugger, m_scripts, m_skipList, and resetBlackboxedStateCache().
resetBlackboxedStateCache()
void v8_inspector::V8DebuggerAgentImpl::resetBlackboxedStateCache () [private]
Definition at line 1736 of file v8-debugger-agent-impl.cc.
                                                    {
  for (const auto& it : m_scripts) {
    it.second->resetBlackboxedStateCache();
  }
}
References m_scripts.
Referenced by disable(), reset(), and setBlackboxPatterns().
restartFrame()
Response v8_inspector::V8DebuggerAgentImpl::restartFrame (const String16 & callFrameId, std::optional< String16 > mode, std::unique_ptr< protocol::Array< protocol::Debugger::CallFrame >> * newCallFrames, std::unique_ptr< protocol::Runtime::StackTrace > * asyncStackTrace, std::unique_ptr< protocol::Runtime::StackTraceId > * asyncStackTraceId) [override]
Definition at line 1202 of file v8-debugger-agent-impl.cc.
                                                                   {
  if (!isPaused()) return Response::ServerError(kDebuggerNotPaused);
  if (!mode.has_value()) {
    return Response::ServerError(
        "Restarting frame without 'mode' not supported");
  }
  if (mode.value() != protocol::Debugger::RestartFrame::ModeEnum::StepInto) {
    return Response::InvalidParams("'StepInto' is the only valid mode");
  }
  InjectedScript::CallFrameScope scope(m_session, callFrameId);
  Response response = scope.initialize();
  if (!response.IsSuccess()) return response;
  int callFrameOrdinal = static_cast<int>(scope.frameOrdinal());
  if (!m_debugger->restartFrame(m_session->contextGroupId(),
                                callFrameOrdinal)) {
    return Response::ServerError("Restarting frame failed");
  }
  m_session->releaseObjectGroup(kBacktraceObjectGroup);
  *newCallFrames = std::make_unique<Array<CallFrame>>();
  return Response::Success();
}
References v8_inspector::V8InspectorSessionImpl::contextGroupId(), v8_inspector::InjectedScript::CallFrameScope::frameOrdinal(), v8_inspector::InjectedScript::Scope::initialize(), isPaused(), v8_inspector::kBacktraceObjectGroup, v8_inspector::kDebuggerNotPaused, m_debugger, m_session, mode(), v8_inspector::V8InspectorSessionImpl::releaseObjectGroup(), v8_inspector::V8Debugger::restartFrame(), and v8::debug::StepInto.
restore()
void v8_inspector::V8DebuggerAgentImpl::restore ()
Definition at line 526 of file v8-debugger-agent-impl.cc.
                                  {
  DCHECK(m_enableState == kDisabled);
  if (!m_state->booleanProperty(DebuggerAgentState::debuggerEnabled, false))
    return;
  if (!m_inspector->client()->canExecuteScripts(m_session->contextGroupId()))
    return;
  enableImpl();
  double maxScriptCacheSize = 0;
  m_state->getDouble(DebuggerAgentState::maxScriptCacheSize,
                     &maxScriptCacheSize);
  m_maxScriptCacheSize = v8::base::saturated_cast<size_t>(maxScriptCacheSize);
  int pauseState = v8::debug::NoBreakOnException;
  m_state->getInteger(DebuggerAgentState::pauseOnExceptionsState, &pauseState);
  setPauseOnExceptionsImpl(pauseState);
  m_skipAllPauses =
      m_state->booleanProperty(DebuggerAgentState::skipAllPauses, false);
  int asyncCallStackDepth = 0;
  m_state->getInteger(DebuggerAgentState::asyncCallStackDepth,
                      &asyncCallStackDepth);
  m_debugger->setAsyncCallStackDepth(this, asyncCallStackDepth);
  String16 blackboxPattern;
  if (m_state->getString(DebuggerAgentState::blackboxPattern,
                         &blackboxPattern)) {
    setBlackboxPattern(blackboxPattern);
  }
  m_skipAnonymousScripts =
      m_state->booleanProperty(DebuggerAgentState::skipAnonymousScripts, false);
}
References v8_inspector::DebuggerAgentState::asyncCallStackDepth, v8_inspector::DebuggerAgentState::blackboxPattern, v8_inspector::V8InspectorClient::canExecuteScripts(), v8_inspector::V8InspectorImpl::client(), v8_inspector::V8InspectorSessionImpl::contextGroupId(), DCHECK, v8_inspector::DebuggerAgentState::debuggerEnabled, enableImpl(), kDisabled, m_debugger, m_enableState, m_inspector, m_maxScriptCacheSize, m_session, m_skipAllPauses, m_skipAnonymousScripts, m_state, v8_inspector::DebuggerAgentState::maxScriptCacheSize, v8::debug::NoBreakOnException, v8_inspector::DebuggerAgentState::pauseOnExceptionsState, v8_inspector::V8Debugger::setAsyncCallStackDepth(), setBlackboxPattern(), setPauseOnExceptionsImpl(), v8_inspector::DebuggerAgentState::skipAllPauses, and v8_inspector::DebuggerAgentState::skipAnonymousScripts.
resume()
Response v8_inspector::V8DebuggerAgentImpl::resume (std::optional< bool > terminateOnResume) [override]
Definition at line 1487 of file v8-debugger-agent-impl.cc.
                                                                        {
  if (!isPaused()) return Response::ServerError(kDebuggerNotPaused);
  m_session->releaseObjectGroup(kBacktraceObjectGroup);
  m_instrumentationFinished = true;
  m_debugger->continueProgram(m_session->contextGroupId(),
                              terminateOnResume.value_or(false));
  return Response::Success();
}
References v8_inspector::V8InspectorSessionImpl::contextGroupId(), v8_inspector::V8Debugger::continueProgram(), isPaused(), v8_inspector::kBacktraceObjectGroup, v8_inspector::kDebuggerNotPaused, m_debugger, m_instrumentationFinished, m_session, and v8_inspector::V8InspectorSessionImpl::releaseObjectGroup().
schedulePauseOnNextStatement()
void v8_inspector::V8DebuggerAgentImpl::schedulePauseOnNextStatement (const String16 & breakReason, std::unique_ptr< protocol::DictionaryValue > data)
Definition at line 1448 of file v8-debugger-agent-impl.cc.
                                                 {
  if (isPaused() || !acceptsPause(false) || !m_breakpointsActive) return;
  if (m_breakReason.empty()) {
    m_debugger->setPauseOnNextCall(true, m_session->contextGroupId());
  }
  pushBreakDetails(breakReason, std::move(data));
}
References acceptsPause(), v8_inspector::V8InspectorSessionImpl::contextGroupId(), isPaused(), m_breakpointsActive, m_breakReason, m_debugger, m_session, pushBreakDetails(), and v8_inspector::V8Debugger::setPauseOnNextCall().
ScriptCollected()
void v8_inspector::V8DebuggerAgentImpl::ScriptCollected (const V8DebuggerScript * script)
Definition at line 2353 of file v8-debugger-agent-impl.cc.
                                                                        {
  DCHECK_NE(m_scripts.find(script->scriptId()), m_scripts.end());
  std::vector<uint8_t> bytecode;
#if V8_ENABLE_WEBASSEMBLY
  v8::MemorySpan<const uint8_t> span;
  if (script->wasmBytecode().To(&span)) {
    bytecode.reserve(span.size());
    bytecode.insert(bytecode.begin(), span.data(), span.data() + span.size());
  }
#endif
  {
    CachedScript cachedScript{script->scriptId(), script->source(0),
                              std::move(bytecode)};
    m_cachedScriptSize += cachedScript.size();
    m_cachedScripts.push_back(std::move(cachedScript));
    m_scripts.erase(script->scriptId());
  }
  while (m_cachedScriptSize > m_maxScriptCacheSize) {
    const CachedScript& cachedScript = m_cachedScripts.front();
    DCHECK_GE(m_cachedScriptSize, cachedScript.size());
    m_cachedScriptSize -= cachedScript.size();
    m_cachedScripts.pop_front();
  }
}
References v8::MemorySpan< T >::data(), DCHECK_GE, DCHECK_NE, m_cachedScripts, m_cachedScriptSize, m_maxScriptCacheSize, m_scripts, v8::internal::script, v8::MemorySpan< T >::size(), and v8_inspector::V8DebuggerAgentImpl::CachedScript::size().
Referenced by v8_inspector::V8DebuggerScript::WeakCallback().
searchInContent()
Response v8_inspector::V8DebuggerAgentImpl::searchInContent (const String16 & scriptId, const String16 & query, std::optional< bool > optionalCaseSensitive, std::optional< bool > optionalIsRegex, std::unique_ptr< protocol::Array< protocol::Debugger::SearchMatch >> *) [override]
Definition at line 1110 of file v8-debugger-agent-impl.cc.
                                                                {
  v8::HandleScope handles(m_isolate);
  ScriptsMap::iterator it = m_scripts.find(scriptId);
  if (it == m_scripts.end())
    return Response::ServerError("No script for id: " + scriptId.utf8());
  *results = std::make_unique<protocol::Array<protocol::Debugger::SearchMatch>>(
      searchInTextByLinesImpl(m_session, it->second->source(0), query,
                              optionalCaseSensitive.value_or(false),
                              optionalIsRegex.value_or(false)));
  return Response::Success();
}
References m_isolate, m_scripts, m_session, v8_inspector::searchInTextByLinesImpl(), and v8_inspector::String16::utf8().
setAsyncCallStackDepth()
Response v8_inspector::V8DebuggerAgentImpl::setAsyncCallStackDepth (int depth) [override]
Definition at line 1679 of file v8-debugger-agent-impl.cc.
                                                              {
  if (!enabled() && !m_session->runtimeAgent()->enabled()) {
    return Response::ServerError(kDebuggerNotEnabled);
  }
  m_state->setInteger(DebuggerAgentState::asyncCallStackDepth, depth);
  m_debugger->setAsyncCallStackDepth(this, depth);
  return Response::Success();
}
References v8_inspector::DebuggerAgentState::asyncCallStackDepth, enabled(), v8_inspector::V8RuntimeAgentImpl::enabled(), v8_inspector::kDebuggerNotEnabled, m_debugger, m_session, m_state, v8_inspector::V8InspectorSessionImpl::runtimeAgent(), and v8_inspector::V8Debugger::setAsyncCallStackDepth().
Referenced by v8_inspector::V8RuntimeAgentImpl::disable().
setBlackboxedRanges()
Response v8_inspector::V8DebuggerAgentImpl::setBlackboxedRanges (const String16 & scriptId, std::unique_ptr< protocol::Array< protocol::Debugger::ScriptPosition >> positions) [override]
Definition at line 1742 of file v8-debugger-agent-impl.cc.
                     {
  auto it = m_scripts.find(scriptId);
  if (it == m_scripts.end())
    return Response::ServerError("No script with passed id.");
  if (inPositions->empty()) {
    m_blackboxedPositions.erase(scriptId);
    it->second->resetBlackboxedStateCache();
    return Response::Success();
  }
  std::vector<std::pair<int, int>> positions;
  positions.reserve(inPositions->size());
  for (const std::unique_ptr<protocol::Debugger::ScriptPosition>& position :
       *inPositions) {
    Response res = isValidPosition(position.get());
    if (res.IsError()) return res;
    positions.push_back(
        std::make_pair(position->getLineNumber(), position->getColumnNumber()));
  }
  Response res = isValidRangeOfPositions(positions);
  if (res.IsError()) return res;
  m_blackboxedPositions[scriptId] = positions;
  it->second->resetBlackboxedStateCache();
  return Response::Success();
}
References v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::isValidPosition(), v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::isValidRangeOfPositions(), m_blackboxedPositions, and m_scripts.
setBlackboxExecutionContexts()
Response v8_inspector::V8DebuggerAgentImpl::setBlackboxExecutionContexts (std::unique_ptr< protocol::Array< String16 >> uniqueIds) [override]
Definition at line 1717 of file v8-debugger-agent-impl.cc.
                                                      {
  m_blackboxedExecutionContexts.clear();
  for (const String16& uniqueId : *uniqueIds) {
    m_blackboxedExecutionContexts.insert(uniqueId);
  }
  return Response::Success();
}
References m_blackboxedExecutionContexts.
setBlackboxPattern()
Response v8_inspector::V8DebuggerAgentImpl::setBlackboxPattern (const String16 & pattern) [private]
caseSensitive
multiline
Definition at line 1726 of file v8-debugger-agent-impl.cc.
                                                                        {
  std::unique_ptr<V8Regex> regex(new V8Regex(
      m_inspector, pattern, true /** caseSensitive */, false /** multiline */));
  if (!regex->isValid())
    return Response::ServerError("Pattern parser error: " +
                                 regex->errorMessage().utf8());
  m_blackboxPattern = std::move(regex);
  return Response::Success();
}
References m_blackboxPattern, and m_inspector.
Referenced by restore(), and setBlackboxPatterns().
setBlackboxPatterns()
Response v8_inspector::V8DebuggerAgentImpl::setBlackboxPatterns (std::unique_ptr< protocol::Array< String16 >> patterns, std::optional< bool > skipAnonymous) [override]
Definition at line 1688 of file v8-debugger-agent-impl.cc.
                                     {
  m_skipAnonymousScripts = skipAnonymous.value_or(false);
  m_state->setBoolean(DebuggerAgentState::skipAnonymousScripts,
                      m_skipAnonymousScripts);
  if (patterns->empty()) {
    m_blackboxPattern = nullptr;
    resetBlackboxedStateCache();
    m_state->remove(DebuggerAgentState::blackboxPattern);
    return Response::Success();
  }
  String16Builder patternBuilder;
  patternBuilder.append('(');
  for (size_t i = 0; i < patterns->size() - 1; ++i) {
    patternBuilder.append((*patterns)[i]);
    patternBuilder.append("|");
  }
  patternBuilder.append(patterns->back());
  patternBuilder.append(')');
  String16 pattern = patternBuilder.toString();
  Response response = setBlackboxPattern(pattern);
  if (!response.IsSuccess()) return response;
  resetBlackboxedStateCache();
  m_state->setString(DebuggerAgentState::blackboxPattern, pattern);
  return Response::Success();
}
References v8_inspector::String16Builder::append(), v8_inspector::DebuggerAgentState::blackboxPattern, v8::internal::anonymous_namespace{json-stringifier.cc}::i, m_blackboxPattern, m_skipAnonymousScripts, m_state, resetBlackboxedStateCache(), setBlackboxPattern(), v8_inspector::DebuggerAgentState::skipAnonymousScripts, and v8_inspector::String16Builder::toString().
setBreakpoint()
Response v8_inspector::V8DebuggerAgentImpl::setBreakpoint (std::unique_ptr< protocol::Debugger::Location > location, std::optional< String16 > optionalCondition, String16 * outBreakpointId, std::unique_ptr< protocol::Debugger::Location > * actualLocation) [override]
Definition at line 718 of file v8-debugger-agent-impl.cc.
                                                             {
  String16 breakpointId = generateBreakpointId(
      BreakpointType::kByScriptId, location->getScriptId(),
      location->getLineNumber(), location->getColumnNumber(0));
  if (!enabled()) return Response::ServerError(kDebuggerNotEnabled);
  if (m_breakpointIdToDebuggerBreakpointIds.find(breakpointId) !=
      m_breakpointIdToDebuggerBreakpointIds.end()) {
    return Response::ServerError(
        "Breakpoint at specified location already exists.");
  }
  *actualLocation = setBreakpointImpl(breakpointId, location->getScriptId(),
                                      optionalCondition.value_or(String16()),
                                      location->getLineNumber(),
                                      location->getColumnNumber(0));
  if (!*actualLocation)
    return Response::ServerError("Could not resolve breakpoint");
  *outBreakpointId = breakpointId;
  return Response::Success();
}
References enabled(), v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::generateBreakpointId(), v8_inspector::kDebuggerNotEnabled, m_breakpointIdToDebuggerBreakpointIds, and setBreakpointImpl().
setBreakpointByUrl()
Response v8_inspector::V8DebuggerAgentImpl::setBreakpointByUrl (int lineNumber, std::optional< String16 > optionalURL, std::optional< String16 > optionalURLRegex, std::optional< String16 > optionalScriptHash, std::optional< int > optionalColumnNumber, std::optional< String16 > optionalCondition, String16 * outBreakpointId, std::unique_ptr< protocol::Array< protocol::Debugger::Location >> * locations) [override]
Definition at line 617 of file v8-debugger-agent-impl.cc.
                                                                       {
  if (!enabled()) return Response::ServerError(kDebuggerNotEnabled);
  *locations = std::make_unique<Array<protocol::Debugger::Location>>();
  int specified = (optionalURL.has_value() ? 1 : 0) +
                  (optionalURLRegex.has_value() ? 1 : 0) +
                  (optionalScriptHash.has_value() ? 1 : 0);
  if (specified != 1) {
    return Response::ServerError(
        "Either url or urlRegex or scriptHash must be specified.");
  }
  int columnNumber = 0;
  if (optionalColumnNumber.has_value()) {
    columnNumber = optionalColumnNumber.value();
    if (columnNumber < 0)
      return Response::ServerError("Incorrect column number");
  }
  BreakpointType type = BreakpointType::kByUrl;
  String16 selector;
  if (optionalURLRegex.has_value()) {
    selector = optionalURLRegex.value();
    type = BreakpointType::kByUrlRegex;
  } else if (optionalURL.has_value()) {
    selector = optionalURL.value();
    type = BreakpointType::kByUrl;
  } else if (optionalScriptHash.has_value()) {
    selector = optionalScriptHash.value();
    type = BreakpointType::kByScriptHash;
  }
  // Note: This constructor can call into JavaScript.
  Matcher matcher(m_inspector, type, selector);
  String16 condition = optionalCondition.value_or(String16());
  String16 breakpointId =
      generateBreakpointId(type, selector, lineNumber, columnNumber);
  protocol::DictionaryValue* breakpoints;
  switch (type) {
    case BreakpointType::kByUrlRegex:
      breakpoints =
          getOrCreateObject(m_state, DebuggerAgentState::breakpointsByRegex);
      break;
    case BreakpointType::kByUrl:
      breakpoints = getOrCreateObject(
          getOrCreateObject(m_state, DebuggerAgentState::breakpointsByUrl),
          selector);
      break;
    case BreakpointType::kByScriptHash:
      breakpoints = getOrCreateObject(
          getOrCreateObject(m_state,
                            DebuggerAgentState::breakpointsByScriptHash),
          selector);
      break;
    default:
      UNREACHABLE();
  }
  if (breakpoints->get(breakpointId)) {
    return Response::ServerError(
        "Breakpoint at specified location already exists.");
  }
  std::unique_ptr<protocol::DictionaryValue> hint;
  for (const auto& script : m_scripts) {
    if (!matcher.matches(*script.second)) continue;
    // Make sure the session was not disabled by some re-entrant call
    // in the script matcher.
    DCHECK(enabled());
    int adjustedLineNumber = lineNumber;
    int adjustedColumnNumber = columnNumber;
    if (hint) {
      adjustBreakpointLocation(*script.second, hint.get(), &adjustedLineNumber,
                               &adjustedColumnNumber);
    }
    std::unique_ptr<protocol::Debugger::Location> location =
        setBreakpointImpl(breakpointId, script.first, condition,
                          adjustedLineNumber, adjustedColumnNumber);
    if (location && type != BreakpointType::kByUrlRegex) {
      hint = breakpointHint(*script.second, lineNumber, columnNumber,
                            location->getLineNumber(),
                            location->getColumnNumber(adjustedColumnNumber));
    }
    if (location) (*locations)->emplace_back(std::move(location));
  }
  breakpoints->setString(breakpointId, condition);
  if (hint) {
    protocol::DictionaryValue* breakpointHints =
        getOrCreateObject(m_state, DebuggerAgentState::breakpointHints);
    breakpointHints->setObject(breakpointId, std::move(hint));
  }
  *outBreakpointId = breakpointId;
  return Response::Success();
}
References v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::adjustBreakpointLocation(), v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::breakpointHint(), v8_inspector::DebuggerAgentState::breakpointHints, v8_inspector::DebuggerAgentState::breakpointsByRegex, v8_inspector::DebuggerAgentState::breakpointsByScriptHash, v8_inspector::DebuggerAgentState::breakpointsByUrl, DCHECK, enabled(), v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::generateBreakpointId(), v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::getOrCreateObject(), v8_inspector::kDebuggerNotEnabled, m_inspector, m_scripts, m_state, v8::internal::script, setBreakpointImpl(), v8::internal::tracing::type, and UNREACHABLE.
setBreakpointFor()
void v8_inspector::V8DebuggerAgentImpl::setBreakpointFor (v8::Local< v8::Function > function, v8::Local< v8::String > condition, BreakpointSource source)
Definition at line 2317 of file v8-debugger-agent-impl.cc.
                                                                    {
  String16 breakpointId = generateBreakpointId(
      source == DebugCommandBreakpointSource ? BreakpointType::kDebugCommand
                                             : BreakpointType::kMonitorCommand,
      function);
  if (m_breakpointIdToDebuggerBreakpointIds.find(breakpointId) !=
      m_breakpointIdToDebuggerBreakpointIds.end()) {
    return;
  }
  setBreakpointImpl(breakpointId, function, condition);
}
References DebugCommandBreakpointSource, v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::generateBreakpointId(), m_breakpointIdToDebuggerBreakpointIds, and setBreakpointImpl().
Referenced by v8_inspector::setFunctionBreakpoint().
setBreakpointImpl() [1/2]
std::unique_ptr< protocol::Debugger::Location > v8_inspector::V8DebuggerAgentImpl::setBreakpointImpl (const String16 & breakpointId, const String16 & scriptId, const String16 & condition, int lineNumber, int columnNumber) [private]
Definition at line 1062 of file v8-debugger-agent-impl.cc.
                                                                         {
  v8::HandleScope handles(m_isolate);
  DCHECK(enabled());
  ScriptsMap::iterator scriptIterator = m_scripts.find(scriptId);
  if (scriptIterator == m_scripts.end()) return nullptr;
  V8DebuggerScript* script = scriptIterator->second.get();
  v8::debug::BreakpointId debuggerBreakpointId;
  v8::debug::Location location(lineNumber, columnNumber);
  int contextId = script->executionContextId();
  InspectedContext* inspected = m_inspector->getContext(contextId);
  if (!inspected) return nullptr;
  {
    v8::Context::Scope contextScope(inspected->context());
    if (!script->setBreakpoint(condition, &location, &debuggerBreakpointId)) {
      return nullptr;
    }
  }
  m_debuggerBreakpointIdToBreakpointId[debuggerBreakpointId] = breakpointId;
  m_breakpointIdToDebuggerBreakpointIds[breakpointId].push_back(
      debuggerBreakpointId);
  return protocol::Debugger::Location::create()
      .setScriptId(scriptId)
      .setLineNumber(location.GetLineNumber())
      .setColumnNumber(location.GetColumnNumber())
      .build();
}
References v8_inspector::InspectedContext::context(), DCHECK, enabled(), v8::debug::Location::GetColumnNumber(), v8_inspector::V8InspectorImpl::getContext(), v8::debug::Location::GetLineNumber(), m_breakpointIdToDebuggerBreakpointIds, m_debuggerBreakpointIdToBreakpointId, m_inspector, m_isolate, m_scripts, and v8::internal::script.
Referenced by didParseSource(), setBreakpoint(), setBreakpointByUrl(), setBreakpointFor(), and setBreakpointOnFunctionCall().
setBreakpointImpl() [2/2]
void v8_inspector::V8DebuggerAgentImpl::setBreakpointImpl (const String16 & breakpointId, v8::Local< v8::Function > function, v8::Local< v8::String > condition) [private]
Definition at line 1097 of file v8-debugger-agent-impl.cc.
                                                                         {
  v8::debug::BreakpointId debuggerBreakpointId;
  if (!v8::debug::SetFunctionBreakpoint(function, condition,
                                        &debuggerBreakpointId)) {
    return;
  }
  m_debuggerBreakpointIdToBreakpointId[debuggerBreakpointId] = breakpointId;
  m_breakpointIdToDebuggerBreakpointIds[breakpointId].push_back(
      debuggerBreakpointId);
}
References m_breakpointIdToDebuggerBreakpointIds, m_debuggerBreakpointIdToBreakpointId, and v8::debug::SetFunctionBreakpoint().
setBreakpointOnFunctionCall()
Response v8_inspector::V8DebuggerAgentImpl::setBreakpointOnFunctionCall (const String16 & functionObjectId, std::optional< String16 > optionalCondition, String16 * outBreakpointId) [override]
Definition at line 742 of file v8-debugger-agent-impl.cc.
                               {
  if (!enabled()) return Response::ServerError(kDebuggerNotEnabled);
  InjectedScript::ObjectScope scope(m_session, functionObjectId);
  Response response = scope.initialize();
  if (!response.IsSuccess()) return response;
  if (!scope.object()->IsFunction()) {
    return Response::ServerError("Could not find function with given id");
  }
  v8::Local<v8::Function> function =
      v8::Local<v8::Function>::Cast(scope.object());
  String16 breakpointId =
      generateBreakpointId(BreakpointType::kBreakpointAtEntry, function);
  if (m_breakpointIdToDebuggerBreakpointIds.find(breakpointId) !=
      m_breakpointIdToDebuggerBreakpointIds.end()) {
    return Response::ServerError(
        "Breakpoint at specified location already exists.");
  }
  v8::Local<v8::String> condition =
      toV8String(m_isolate, optionalCondition.value_or(String16()));
  setBreakpointImpl(breakpointId, function, condition);
  *outBreakpointId = breakpointId;
  return Response::Success();
}
References v8::Local< T >::Cast(), enabled(), v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::generateBreakpointId(), v8_inspector::InjectedScript::Scope::initialize(), v8::Value::IsFunction(), v8_inspector::kDebuggerNotEnabled, m_breakpointIdToDebuggerBreakpointIds, m_isolate, m_session, v8_inspector::InjectedScript::ObjectScope::object(), setBreakpointImpl(), and v8_inspector::toV8String().
setBreakpointsActive()
Response v8_inspector::V8DebuggerAgentImpl::setBreakpointsActive (bool active) [override]
Definition at line 561 of file v8-debugger-agent-impl.cc.
                                                              {
  m_state->setBoolean(DebuggerAgentState::breakpointsActiveWhenEnabled, active);
  if (!enabled()) return Response::Success();
  if (m_breakpointsActive == active) return Response::Success();
  m_breakpointsActive = active;
  m_debugger->setBreakpointsActive(active);
  if (!active && !m_breakReason.empty()) {
    clearBreakDetails();
    m_debugger->setPauseOnNextCall(false, m_session->contextGroupId());
  }
  return Response::Success();
}
References v8_inspector::DebuggerAgentState::breakpointsActiveWhenEnabled, clearBreakDetails(), v8_inspector::V8InspectorSessionImpl::contextGroupId(), enabled(), m_breakpointsActive, m_breakReason, m_debugger, m_session, m_state, v8_inspector::V8Debugger::setBreakpointsActive(), and v8_inspector::V8Debugger::setPauseOnNextCall().
setInstrumentationBreakpoint()
Response v8_inspector::V8DebuggerAgentImpl::setInstrumentationBreakpoint (const String16 & instrumentation, String16 * outBreakpointId) [override]
Definition at line 769 of file v8-debugger-agent-impl.cc.
                                                                {
  if (!enabled()) return Response::ServerError(kDebuggerNotEnabled);
  String16 breakpointId = generateInstrumentationBreakpointId(instrumentation);
  protocol::DictionaryValue* breakpoints = getOrCreateObject(
      m_state, DebuggerAgentState::instrumentationBreakpoints);
  if (breakpoints->get(breakpointId)) {
    return Response::ServerError(
        "Instrumentation breakpoint is already enabled.");
  }
  breakpoints->setBoolean(breakpointId, true);
  *outBreakpointId = breakpointId;
  return Response::Success();
}
References enabled(), v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::generateInstrumentationBreakpointId(), v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::getOrCreateObject(), v8_inspector::DebuggerAgentState::instrumentationBreakpoints, v8_inspector::kDebuggerNotEnabled, and m_state.
setPauseOnExceptions()
Response v8_inspector::V8DebuggerAgentImpl::setPauseOnExceptions (const String16 & pauseState) [override]
Definition at line 1546 of file v8-debugger-agent-impl.cc.
                                      {
  if (!enabled()) return Response::ServerError(kDebuggerNotEnabled);
  v8::debug::ExceptionBreakState pauseState;
  if (stringPauseState == "none") {
    pauseState = v8::debug::NoBreakOnException;
  } else if (stringPauseState == "all") {
    pauseState = v8::debug::BreakOnAnyException;
  } else if (stringPauseState == "caught") {
    pauseState = v8::debug::BreakOnCaughtException;
  } else if (stringPauseState == "uncaught") {
    pauseState = v8::debug::BreakOnUncaughtException;
  } else {
    return Response::ServerError("Unknown pause on exceptions mode: " +
                                 stringPauseState.utf8());
  }
  setPauseOnExceptionsImpl(pauseState);
  return Response::Success();
}
References v8::debug::BreakOnAnyException, v8::debug::BreakOnCaughtException, v8::debug::BreakOnUncaughtException, enabled(), v8_inspector::kDebuggerNotEnabled, v8::debug::NoBreakOnException, setPauseOnExceptionsImpl(), and v8_inspector::String16::utf8().
setPauseOnExceptionsImpl()
void v8_inspector::V8DebuggerAgentImpl::setPauseOnExceptionsImpl (int pauseState) [private]
Definition at line 1566 of file v8-debugger-agent-impl.cc.
                                                                 {
  // TODO(dgozman): this changes the global state and forces all context groups
  // to pause. We should make this flag be per-context-group.
  m_debugger->setPauseOnExceptionsState(
      static_cast<v8::debug::ExceptionBreakState>(pauseState));
  m_state->setInteger(DebuggerAgentState::pauseOnExceptionsState, pauseState);
}
References m_debugger, m_state, v8_inspector::DebuggerAgentState::pauseOnExceptionsState, and v8_inspector::V8Debugger::setPauseOnExceptionsState().
Referenced by restore(), and setPauseOnExceptions().
setReturnValue()
Response v8_inspector::V8DebuggerAgentImpl::setReturnValue (std::unique_ptr< protocol::Runtime::CallArgument > newValue) [override]
Definition at line 1655 of file v8-debugger-agent-impl.cc.
                                                                 {
  if (!enabled()) return Response::ServerError(kDebuggerNotEnabled);
  if (!isPaused()) return Response::ServerError(kDebuggerNotPaused);
  v8::HandleScope handleScope(m_isolate);
  auto iterator = v8::debug::StackTraceIterator::Create(m_isolate);
  if (iterator->Done()) {
    return Response::ServerError("Could not find top call frame");
  }
  if (iterator->GetReturnValue().IsEmpty()) {
    return Response::ServerError(
        "Could not update return value at non-return position");
  }
  InjectedScript::ContextScope scope(m_session, iterator->GetContextId());
  Response response = scope.initialize();
  if (!response.IsSuccess()) return response;
  v8::Local<v8::Value> newValue;
  response = scope.injectedScript()->resolveCallArgument(protocolNewValue.get(),
                                                         &newValue);
  if (!response.IsSuccess()) return response;
  v8::debug::SetReturnValue(m_isolate, newValue);
  return Response::Success();
}
References v8::debug::StackTraceIterator::Create(), enabled(), v8_inspector::InjectedScript::Scope::initialize(), v8_inspector::InjectedScript::Scope::injectedScript(), isPaused(), v8_inspector::kDebuggerNotEnabled, v8_inspector::kDebuggerNotPaused, m_isolate, m_session, v8_inspector::InjectedScript::resolveCallArgument(), and v8::debug::SetReturnValue().
setScriptInstrumentationBreakpointIfNeeded()
void v8_inspector::V8DebuggerAgentImpl::setScriptInstrumentationBreakpointIfNeeded (V8DebuggerScript * script) [private]
Definition at line 2109 of file v8-debugger-agent-impl.cc.
                                 {
  protocol::DictionaryValue* breakpoints =
      m_state->getObject(DebuggerAgentState::instrumentationBreakpoints);
  if (!breakpoints) return;
  bool isBlackboxed = isFunctionBlackboxed(
      scriptRef->scriptId(), v8::debug::Location(0, 0),
      v8::debug::Location(scriptRef->endLine(), scriptRef->endColumn()));
  if (isBlackboxed) return;
  String16 sourceMapURL = scriptRef->sourceMappingURL();
  String16 breakpointId = generateInstrumentationBreakpointId(
      InstrumentationEnum::BeforeScriptExecution);
  if (!breakpoints->get(breakpointId)) {
    if (sourceMapURL.isEmpty()) return;
    breakpointId = generateInstrumentationBreakpointId(
        InstrumentationEnum::BeforeScriptWithSourceMapExecution);
    if (!breakpoints->get(breakpointId)) return;
  }
  v8::debug::BreakpointId debuggerBreakpointId;
  if (!scriptRef->setInstrumentationBreakpoint(&debuggerBreakpointId)) return;
  m_debuggerBreakpointIdToBreakpointId[debuggerBreakpointId] = breakpointId;
  m_breakpointIdToDebuggerBreakpointIds[breakpointId].push_back(
      debuggerBreakpointId);
}
References v8_inspector::V8DebuggerScript::endColumn(), v8_inspector::V8DebuggerScript::endLine(), v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::generateInstrumentationBreakpointId(), v8_inspector::DebuggerAgentState::instrumentationBreakpoints, v8_inspector::String16::isEmpty(), isFunctionBlackboxed(), m_breakpointIdToDebuggerBreakpointIds, m_debuggerBreakpointIdToBreakpointId, m_state, v8_inspector::V8DebuggerScript::scriptId(), v8_inspector::V8DebuggerScript::setInstrumentationBreakpoint(), and v8_inspector::V8DebuggerScript::sourceMappingURL().
Referenced by didParseSource().
setScriptSource()
Response v8_inspector::V8DebuggerAgentImpl::setScriptSource (const String16 & inScriptId, const String16 & inScriptSource, std::optional< bool > dryRun, std::optional< bool > allowTopFrameEditing, std::unique_ptr< protocol::Array< protocol::Debugger::CallFrame >> * optOutCallFrames, std::optional< bool > * optOutStackChanged, std::unique_ptr< protocol::Runtime::StackTrace > * optOutAsyncStackTrace, std::unique_ptr< protocol::Runtime::StackTraceId > * optOutAsyncStackTraceId, String16 * outStatus, std::unique_ptr< protocol::Runtime::ExceptionDetails > * optOutCompileError) [override]
Definition at line 1147 of file v8-debugger-agent-impl.cc.
                                                                        {
  if (!enabled()) return Response::ServerError(kDebuggerNotEnabled);
  ScriptsMap::iterator it = m_scripts.find(scriptId);
  if (it == m_scripts.end()) {
    return Response::ServerError("No script with given id found");
  }
  int contextId = it->second->executionContextId();
  InspectedContext* inspected = m_inspector->getContext(contextId);
  if (!inspected) {
    return Response::InternalError();
  }
  v8::HandleScope handleScope(m_isolate);
  v8::Local<v8::Context> context = inspected->context();
  v8::Context::Scope contextScope(context);
  const bool allowTopFrameLiveEditing = allowTopFrameEditing.value_or(false);
  v8::debug::LiveEditResult result;
  it->second->setSource(newContent, dryRun.value_or(false),
                        allowTopFrameLiveEditing, &result);
  *status = buildStatus(result.status);
  if (result.status == v8::debug::LiveEditResult::COMPILE_ERROR) {
    *optOutCompileError =
        protocol::Runtime::ExceptionDetails::create()
            .setExceptionId(m_inspector->nextExceptionId())
            .setText(toProtocolString(m_isolate, result.message))
            .setLineNumber(result.line_number != -1 ? result.line_number - 1
                                                    : 0)
            .setColumnNumber(result.column_number != -1 ? result.column_number
                                                        : 0)
            .build();
    return Response::Success();
  }
  if (result.restart_top_frame_required) {
    CHECK(allowTopFrameLiveEditing);
    // Nothing could have happened to the JS stack since the live edit so
    // restarting the top frame is guaranteed to be successful.
    CHECK(m_debugger->restartFrame(m_session->contextGroupId(),
                                   /* callFrameOrdinal */ 0));
    m_session->releaseObjectGroup(kBacktraceObjectGroup);
  }
  return Response::Success();
}
References v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::buildStatus(), CHECK, v8::debug::LiveEditResult::COMPILE_ERROR, v8_inspector::InspectedContext::context(), v8_inspector::V8InspectorSessionImpl::contextGroupId(), enabled(), v8_inspector::V8InspectorImpl::getContext(), v8_inspector::kBacktraceObjectGroup, v8_inspector::kDebuggerNotEnabled, m_debugger, m_inspector, m_isolate, m_scripts, m_session, v8_inspector::V8InspectorImpl::nextExceptionId(), v8_inspector::V8InspectorSessionImpl::releaseObjectGroup(), v8_inspector::V8Debugger::restartFrame(), v8::base::internal::result, v8::internal::status, and v8_inspector::toProtocolString().
setSkipAllPauses()
Response v8_inspector::V8DebuggerAgentImpl::setSkipAllPauses (bool skip) [override]
Definition at line 574 of file v8-debugger-agent-impl.cc.
                                                        {
  m_state->setBoolean(DebuggerAgentState::skipAllPauses, skip);
  m_skipAllPauses = skip;
  return Response::Success();
}
References m_skipAllPauses, m_state, and v8_inspector::DebuggerAgentState::skipAllPauses.
setVariableValue()
Response v8_inspector::V8DebuggerAgentImpl::setVariableValue (int scopeNumber, const String16 & variableName, std::unique_ptr< protocol::Runtime::CallArgument > newValue, const String16 & callFrame) [override]
Definition at line 1619 of file v8-debugger-agent-impl.cc.
                                 {
  if (!enabled()) return Response::ServerError(kDebuggerNotEnabled);
  if (!isPaused()) return Response::ServerError(kDebuggerNotPaused);
  InjectedScript::CallFrameScope scope(m_session, callFrameId);
  Response response = scope.initialize();
  if (!response.IsSuccess()) return response;
  v8::Local<v8::Value> newValue;
  response = scope.injectedScript()->resolveCallArgument(newValueArgument.get(),
                                                         &newValue);
  if (!response.IsSuccess()) return response;
  int frameOrdinal = static_cast<int>(scope.frameOrdinal());
  auto it = v8::debug::StackTraceIterator::Create(m_isolate, frameOrdinal);
  if (it->Done()) {
    return Response::ServerError("Could not find call frame with given id");
  }
  auto scopeIterator = it->GetScopeIterator();
  while (!scopeIterator->Done() && scopeNumber > 0) {
    --scopeNumber;
    scopeIterator->Advance();
  }
  if (scopeNumber != 0) {
    return Response::ServerError("Could not find scope with given number");
  }
  if (!scopeIterator->SetVariableValue(toV8String(m_isolate, variableName),
                                       newValue) ||
      scope.tryCatch().HasCaught()) {
    return Response::InternalError();
  }
  return Response::Success();
}
References v8::debug::StackTraceIterator::Create(), enabled(), v8_inspector::InjectedScript::CallFrameScope::frameOrdinal(), v8::TryCatch::HasCaught(), v8_inspector::InjectedScript::Scope::initialize(), v8_inspector::InjectedScript::Scope::injectedScript(), isPaused(), v8_inspector::kDebuggerNotEnabled, v8_inspector::kDebuggerNotPaused, m_isolate, m_session, v8_inspector::InjectedScript::resolveCallArgument(), v8_inspector::toV8String(), and v8_inspector::InjectedScript::Scope::tryCatch().
shouldBeSkipped()
bool v8_inspector::V8DebuggerAgentImpl::shouldBeSkipped (const String16 & scriptId, int line, int column)
Definition at line 1030 of file v8-debugger-agent-impl.cc.
                                                      {
  if (m_skipList.empty()) return false;
  auto it = m_skipList.find(scriptId);
  if (it == m_skipList.end()) return false;
  const std::vector<std::pair<int, int>>& ranges = it->second;
  DCHECK(!ranges.empty());
  const std::pair<int, int> location = std::make_pair(line, column);
  auto itLowerBound = std::lower_bound(ranges.begin(), ranges.end(), location,
                                       positionComparator);
  bool shouldSkip = false;
  if (itLowerBound != ranges.end()) {
    // Skip lists are defined as pairs of locations that specify the
    // start and the end of ranges to skip: [ranges[0], ranges[1], ..], where
    // locations in [ranges[0], ranges[1]) should be skipped, i.e.
    // [(lineStart, columnStart), (lineEnd, columnEnd)).
    const bool isSameAsLowerBound = location == *itLowerBound;
    const bool isUnevenIndex = (itLowerBound - ranges.begin()) % 2;
    shouldSkip = isSameAsLowerBound ^ isUnevenIndex;
  }
  return shouldSkip;
}
References DCHECK, m_skipList, and v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::positionComparator().
stepInto()
Response v8_inspector::V8DebuggerAgentImpl::stepInto (std::optional< bool > inBreakOnAsyncCall, std::unique_ptr< protocol::Array< protocol::Debugger::LocationRange >> inSkipList) [override]
Definition at line 1514 of file v8-debugger-agent-impl.cc.
                    {
  if (!isPaused()) return Response::ServerError(kDebuggerNotPaused);
  if (inSkipList) {
    const Response res = processSkipList(*inSkipList);
    if (res.IsError()) return res;
  } else {
    m_skipList.clear();
  }
  m_session->releaseObjectGroup(kBacktraceObjectGroup);
  m_debugger->stepIntoStatement(m_session->contextGroupId(),
                                inBreakOnAsyncCall.value_or(false));
  return Response::Success();
}
References v8_inspector::V8InspectorSessionImpl::contextGroupId(), isPaused(), v8_inspector::kBacktraceObjectGroup, v8_inspector::kDebuggerNotPaused, m_debugger, m_session, m_skipList, processSkipList(), v8_inspector::V8InspectorSessionImpl::releaseObjectGroup(), and v8_inspector::V8Debugger::stepIntoStatement().
stepOut()
Response v8_inspector::V8DebuggerAgentImpl::stepOut () [override]
Definition at line 1533 of file v8-debugger-agent-impl.cc.
                                      {
  if (!isPaused()) return Response::ServerError(kDebuggerNotPaused);
  m_session->releaseObjectGroup(kBacktraceObjectGroup);
  m_debugger->stepOutOfFunction(m_session->contextGroupId());
  return Response::Success();
}
References v8_inspector::V8InspectorSessionImpl::contextGroupId(), isPaused(), v8_inspector::kBacktraceObjectGroup, v8_inspector::kDebuggerNotPaused, m_debugger, m_session, v8_inspector::V8InspectorSessionImpl::releaseObjectGroup(), and v8_inspector::V8Debugger::stepOutOfFunction().
stepOver()
Response v8_inspector::V8DebuggerAgentImpl::stepOver (std::unique_ptr< protocol::Array< protocol::Debugger::LocationRange >> inSkipList) [override]
Definition at line 1497 of file v8-debugger-agent-impl.cc.
                    {
  if (!isPaused()) return Response::ServerError(kDebuggerNotPaused);
  if (inSkipList) {
    const Response res = processSkipList(*inSkipList);
    if (res.IsError()) return res;
  } else {
    m_skipList.clear();
  }
  m_session->releaseObjectGroup(kBacktraceObjectGroup);
  m_debugger->stepOverStatement(m_session->contextGroupId());
  return Response::Success();
}
References v8_inspector::V8InspectorSessionImpl::contextGroupId(), isPaused(), v8_inspector::kBacktraceObjectGroup, v8_inspector::kDebuggerNotPaused, m_debugger, m_session, m_skipList, processSkipList(), v8_inspector::V8InspectorSessionImpl::releaseObjectGroup(), and v8_inspector::V8Debugger::stepOverStatement().
stop()
void v8_inspector::V8DebuggerAgentImpl::stop ()
Definition at line 2414 of file v8-debugger-agent-impl.cc.
                               {
  disable();
  m_enableState = kStopping;
}
References disable(), kStopping, and m_enableState.
Member Data Documentation
m_blackboxedExecutionContexts
std::unordered_set<String16> v8_inspector::V8DebuggerAgentImpl::m_blackboxedExecutionContexts [private]
Definition at line 291 of file v8-debugger-agent-impl.h.
Referenced by isFunctionBlackboxed(), reset(), and setBlackboxExecutionContexts().
m_blackboxedPositions
std::unordered_map<String16, std::vector<std::pair<int, int> > > v8_inspector::V8DebuggerAgentImpl::m_blackboxedPositions [private]
Definition at line 289 of file v8-debugger-agent-impl.h.
Referenced by disable(), isFunctionBlackboxed(), reset(), and setBlackboxedRanges().
m_blackboxPattern
std::unique_ptr<V8Regex> v8_inspector::V8DebuggerAgentImpl::m_blackboxPattern [private]
Definition at line 287 of file v8-debugger-agent-impl.h.
Referenced by disable(), isFunctionBlackboxed(), setBlackboxPattern(), and setBlackboxPatterns().
m_breakpointIdToDebuggerBreakpointIds
BreakpointIdToDebuggerBreakpointIdsMap v8_inspector::V8DebuggerAgentImpl::m_breakpointIdToDebuggerBreakpointIds [private]
Definition at line 254 of file v8-debugger-agent-impl.h.
Referenced by disable(), removeBreakpointImpl(), setBreakpoint(), setBreakpointFor(), setBreakpointImpl(), setBreakpointOnFunctionCall(), and setScriptInstrumentationBreakpointIfNeeded().
m_breakpointsActive
bool v8_inspector::V8DebuggerAgentImpl::m_breakpointsActive = false [private]
Definition at line 283 of file v8-debugger-agent-impl.h.
Referenced by cancelPauseOnNextStatement(), disable(), enableImpl(), schedulePauseOnNextStatement(), and setBreakpointsActive().
m_breakReason
std::vector<BreakReason> v8_inspector::V8DebuggerAgentImpl::m_breakReason [private]
Definition at line 275 of file v8-debugger-agent-impl.h.
Referenced by breakProgram(), cancelPauseOnNextStatement(), clearBreakDetails(), didPause(), popBreakDetails(), pushBreakDetails(), schedulePauseOnNextStatement(), and setBreakpointsActive().
m_cachedScripts
std::deque<CachedScript> v8_inspector::V8DebuggerAgentImpl::m_cachedScripts [private]
Definition at line 271 of file v8-debugger-agent-impl.h.
Referenced by disable(), disassembleWasmModule(), getScriptSource(), reset(), and ScriptCollected().
m_cachedScriptSize
size_t v8_inspector::V8DebuggerAgentImpl::m_cachedScriptSize = 0 [private]
Definition at line 261 of file v8-debugger-agent-impl.h.
Referenced by disable(), reset(), and ScriptCollected().
m_debugger
V8Debugger* v8_inspector::V8DebuggerAgentImpl::m_debugger [private]
Definition at line 247 of file v8-debugger-agent-impl.h.
Referenced by breakProgram(), cancelPauseOnNextStatement(), continueToLocation(), currentAsyncStackTrace(), currentExternalStackTrace(), didParseSource(), didPause(), disable(), enable(), enableImpl(), getStackTrace(), isPaused(), pause(), removeBreakpointImpl(), reset(), restartFrame(), restore(), resume(), schedulePauseOnNextStatement(), setAsyncCallStackDepth(), setBreakpointsActive(), setPauseOnExceptionsImpl(), setScriptSource(), stepInto(), stepOut(), and stepOver().
m_debuggerBreakpointIdToBreakpointId
DebuggerBreakpointIdToBreakpointIdMap v8_inspector::V8DebuggerAgentImpl::m_debuggerBreakpointIdToBreakpointId [private]
Definition at line 255 of file v8-debugger-agent-impl.h.
Referenced by didPause(), didPauseOnInstrumentation(), disable(), removeBreakpointImpl(), setBreakpointImpl(), and setScriptInstrumentationBreakpointIfNeeded().
m_enableState
EnableState v8_inspector::V8DebuggerAgentImpl::m_enableState [private]
Definition at line 249 of file v8-debugger-agent-impl.h.
Referenced by disable(), enable(), enabled(), enableImpl(), restore(), and stop().
m_frontend
protocol::Debugger::Frontend v8_inspector::V8DebuggerAgentImpl::m_frontend [private]
Definition at line 251 of file v8-debugger-agent-impl.h.
Referenced by didContinue(), didParseSource(), didPause(), and didPauseOnInstrumentation().
m_inspector
V8InspectorImpl* v8_inspector::V8DebuggerAgentImpl::m_inspector [private]
Definition at line 246 of file v8-debugger-agent-impl.h.
Referenced by breakProgram(), continueToLocation(), currentCallFrames(), didParseSource(), enable(), getPossibleBreakpoints(), isFunctionBlackboxed(), removeBreakpoint(), restore(), setBlackboxPattern(), setBreakpointByUrl(), setBreakpointImpl(), and setScriptSource().
m_instrumentationFinished
bool v8_inspector::V8DebuggerAgentImpl::m_instrumentationFinished = true [private]
Definition at line 284 of file v8-debugger-agent-impl.h.
Referenced by didPauseOnInstrumentation(), disable(), instrumentationFinished(), and resume().
m_isolate
v8::Isolate* v8_inspector::V8DebuggerAgentImpl::m_isolate [private]
Definition at line 252 of file v8-debugger-agent-impl.h.
Referenced by continueToLocation(), currentCallFrames(), didParseSource(), didPause(), evaluateOnCallFrame(), getPossibleBreakpoints(), isolate(), searchInContent(), setBreakpointImpl(), setBreakpointOnFunctionCall(), setReturnValue(), setScriptSource(), and setVariableValue().
m_maxScriptCacheSize
size_t v8_inspector::V8DebuggerAgentImpl::m_maxScriptCacheSize = 0 [private]
Definition at line 260 of file v8-debugger-agent-impl.h.
Referenced by disable(), enable(), restore(), and ScriptCollected().
m_nextWasmDisassemblyStreamId
size_t v8_inspector::V8DebuggerAgentImpl::m_nextWasmDisassemblyStreamId = 0 [private]
Definition at line 258 of file v8-debugger-agent-impl.h.
Referenced by disassembleWasmModule().
m_scripts
ScriptsMap v8_inspector::V8DebuggerAgentImpl::m_scripts [private]
Definition at line 253 of file v8-debugger-agent-impl.h.
Referenced by continueToLocation(), didParseSource(), didPauseOnInstrumentation(), disable(), disassembleWasmModule(), getPossibleBreakpoints(), getScriptSource(), getWasmBytecode(), isFunctionBlackboxed(), processSkipList(), removeBreakpoint(), reset(), resetBlackboxedStateCache(), ScriptCollected(), searchInContent(), setBlackboxedRanges(), setBreakpointByUrl(), setBreakpointImpl(), and setScriptSource().
m_session
V8InspectorSessionImpl* v8_inspector::V8DebuggerAgentImpl::m_session [private]
Definition at line 248 of file v8-debugger-agent-impl.h.
Referenced by breakProgram(), cancelPauseOnNextStatement(), continueToLocation(), currentCallFrames(), didPause(), enable(), enableImpl(), evaluateOnCallFrame(), getStackTrace(), isPaused(), pause(), restartFrame(), restore(), resume(), schedulePauseOnNextStatement(), searchInContent(), setAsyncCallStackDepth(), setBreakpointOnFunctionCall(), setBreakpointsActive(), setReturnValue(), setScriptSource(), setVariableValue(), stepInto(), stepOut(), and stepOver().
m_skipAllPauses
bool v8_inspector::V8DebuggerAgentImpl::m_skipAllPauses = false [private]
Definition at line 282 of file v8-debugger-agent-impl.h.
Referenced by acceptsPause(), breakProgram(), disable(), restore(), and setSkipAllPauses().
m_skipAnonymousScripts
bool v8_inspector::V8DebuggerAgentImpl::m_skipAnonymousScripts = false [private]
Definition at line 285 of file v8-debugger-agent-impl.h.
Referenced by isFunctionBlackboxed(), restore(), and setBlackboxPatterns().
m_skipList
std::unordered_map<String16, std::vector<std::pair<int, int> > > v8_inspector::V8DebuggerAgentImpl::m_skipList [private]
Definition at line 290 of file v8-debugger-agent-impl.h.
Referenced by disable(), processSkipList(), reset(), shouldBeSkipped(), stepInto(), and stepOver().
m_state
protocol::DictionaryValue* v8_inspector::V8DebuggerAgentImpl::m_state [private]
Definition at line 250 of file v8-debugger-agent-impl.h.
Referenced by didParseSource(), disable(), enable(), enableImpl(), removeBreakpoint(), restore(), setAsyncCallStackDepth(), setBlackboxPatterns(), setBreakpointByUrl(), setBreakpointsActive(), setInstrumentationBreakpoint(), setPauseOnExceptionsImpl(), setScriptInstrumentationBreakpointIfNeeded(), and setSkipAllPauses().
m_wasmDisassemblies
std::map<String16, std::unique_ptr<DisassemblyCollectorImpl> > v8_inspector::V8DebuggerAgentImpl::m_wasmDisassemblies [private]
Definition at line 257 of file v8-debugger-agent-impl.h.
Referenced by disable(), disassembleWasmModule(), and nextWasmDisassemblyChunk().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/inspector/v8-debugger-agent-impl.h
/mnt/V8SourceCode/src/inspector/v8-debugger-agent-impl.cc