v8::internal::SharedObjectConveyorHandles Class Reference
#include <shared-object-conveyor-handles.h>
Public Member Functions
SharedObjectConveyorHandles (Isolate *isolate)
SharedObjectConveyorHandles (const SharedObjectConveyorHandles &)=delete
SharedObjectConveyorHandles & operator= (const SharedObjectConveyorHandles &)=delete
uint32_t Persist (Tagged< HeapObject > shared_object)
bool HasPersisted (uint32_t object_id) const
Tagged< HeapObject > GetPersisted (uint32_t object_id) const
Private Attributes
std::unique_ptr< PersistentHandles > persistent_handles_
std::vector< Handle< HeapObject > > shared_objects_
Detailed Description
Definition at line 29 of file shared-object-conveyor-handles.h.
Constructor & Destructor Documentation
SharedObjectConveyorHandles() [1/2]
v8::internal::SharedObjectConveyorHandles::SharedObjectConveyorHandles (Isolate * isolate) [explicit]
Definition at line 14 of file shared-object-conveyor-handles.cc.
    : persistent_handles_(
          isolate->shared_space_isolate()->NewPersistentHandles()) {}
SharedObjectConveyorHandles() [2/2]
v8::internal::SharedObjectConveyorHandles::SharedObjectConveyorHandles (const SharedObjectConveyorHandles &) [delete]
Member Function Documentation
GetPersisted()
Tagged<HeapObject> v8::internal::SharedObjectConveyorHandles::GetPersisted (uint32_t object_id) const [inline]
Definition at line 43 of file shared-object-conveyor-handles.h.
                                                            {
    DCHECK(HasPersisted(object_id));
    return *shared_objects_[object_id];
  }
References v8::internal::DCHECK(), HasPersisted(), and shared_objects_.
Referenced by v8::internal::ValueDeserializer::ReadSharedObject().
HasPersisted()
bool v8::internal::SharedObjectConveyorHandles::HasPersisted (uint32_t object_id) const [inline]
Definition at line 39 of file shared-object-conveyor-handles.h.
                                              {
    return object_id < shared_objects_.size();
  }
References shared_objects_.
Referenced by GetPersisted().
operator=()
SharedObjectConveyorHandles& v8::internal::SharedObjectConveyorHandles::operator= (const SharedObjectConveyorHandles &) [delete]
Persist()
uint32_t v8::internal::SharedObjectConveyorHandles::Persist (Tagged< HeapObject > shared_object)
Definition at line 18 of file shared-object-conveyor-handles.cc.
                                      {
  DCHECK(IsShared(shared_object));
  uint32_t id = static_cast<uint32_t>(shared_objects_.size());
  shared_objects_.push_back(persistent_handles_->NewHandle(shared_object));
  return id;
}
References v8::internal::DCHECK(), v8::internal::IsShared(), persistent_handles_, and shared_objects_.
Referenced by v8::internal::ValueSerializer::WriteSharedObject().
Member Data Documentation
persistent_handles_
std::unique_ptr<PersistentHandles> v8::internal::SharedObjectConveyorHandles::persistent_handles_ [private]
Definition at line 49 of file shared-object-conveyor-handles.h.
Referenced by Persist().
shared_objects_
std::vector<Handle<HeapObject> > v8::internal::SharedObjectConveyorHandles::shared_objects_ [private]
Definition at line 50 of file shared-object-conveyor-handles.h.
Referenced by GetPersisted(), HasPersisted(), and Persist().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/handles/shared-object-conveyor-handles.h
/mnt/V8SourceCode/src/handles/shared-object-conveyor-handles.cc