v8::internal::maglev::Constant Class Reference
#include <maglev-ir.h>
Public Types
using OutputRegister = Register
Public Member Functions
Constant (uint64_t bitfield, compiler::HeapObjectRef object)
bool ToBoolean (LocalIsolate *local_isolate) const
bool IsTheHole (compiler::JSHeapBroker *broker) const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
compiler::HeapObjectRef object ()
void DoLoadToRegister (MaglevAssembler *, OutputRegister)
DirectHandle< Object > DoReify (LocalIsolate *isolate) const
compiler::HeapObjectRef ref () const
Private Types
using Base = FixedInputValueNodeT< 0, Constant >
Private Attributes
const compiler::HeapObjectRef object_
Additional Inherited Members
Detailed Description
Definition at line 5580 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::Constant::Base = FixedInputValueNodeT<0, Constant> [private]
Definition at line 5581 of file maglev-ir.h.
OutputRegister
using v8::internal::maglev::Constant::OutputRegister = Register
Definition at line 5584 of file maglev-ir.h.
Constructor & Destructor Documentation
Constant()
v8::internal::maglev::Constant::Constant (uint64_t bitfield, compiler::HeapObjectRef object) [inline], [explicit]
Definition at line 5586 of file maglev-ir.h.
      : Base(bitfield), object_(object) {}
Member Function Documentation
DoLoadToRegister()
void v8::internal::maglev::Constant::DoLoadToRegister (MaglevAssembler * , OutputRegister)
DoReify()
DirectHandle< Object > v8::internal::maglev::Constant::DoReify (LocalIsolate * isolate) const
Definition at line 1232 of file maglev-ir.cc.
                                                                  {
  return object_.object();
}
References v8::internal::compiler::HeapObjectRef::object(), and object_.
GenerateCode()
void v8::internal::maglev::Constant::GenerateCode (MaglevAssembler * , const ProcessingState &)
IsTheHole()
bool v8::internal::maglev::Constant::IsTheHole (compiler::JSHeapBroker * broker) const [inline]
Definition at line 5593 of file maglev-ir.h.
                                                     {
    return object_.IsTheHole();
  }
References object_.
object()
compiler::HeapObjectRef v8::internal::maglev::Constant::object () [inline]
Definition at line 5601 of file maglev-ir.h.
{ return object_; }
References object_.
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::Constant::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 7927 of file maglev-ir.cc.
                                                                      {
  os << "(" << *object_.object() << ")";
}
References v8::internal::compiler::HeapObjectRef::object(), and object_.
ref()
compiler::HeapObjectRef v8::internal::maglev::Constant::ref () const [inline]
Definition at line 5606 of file maglev-ir.h.
{ return object_; }
References object_.
SetValueLocationConstraints()
void v8::internal::maglev::Constant::SetValueLocationConstraints ()
ToBoolean()
bool v8::internal::maglev::Constant::ToBoolean (LocalIsolate * local_isolate) const [inline]
Definition at line 5589 of file maglev-ir.h.
                                                    {
    return Object::BooleanValue(*object_.object(), local_isolate);
  }
References v8::internal::Object::BooleanValue(), v8::internal::compiler::HeapObjectRef::object(), and object_.
Member Data Documentation
object_
const compiler::HeapObjectRef v8::internal::maglev::Constant::object_ [private]
Definition at line 5609 of file maglev-ir.h.
Referenced by DoReify(), IsTheHole(), object(), PrintParams(), ref(), and ToBoolean().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc