v8::internal::wasm::NamesProvider Class Reference
#include <names-provider.h>
Public Types
enum FunctionNamesBehavior : bool { kWasmInternal = false
, kDevTools = true
 }
enum IndexAsComment : bool { kDontPrintIndex = false
, kIndexAsComment = true
 }
Public Member Functions
NamesProvider (const WasmModule *module, base::Vector< const uint8_t > wire_bytes)
~NamesProvider ()
void PrintFunctionName (StringBuilder &out, uint32_t function_index, FunctionNamesBehavior behavior=kWasmInternal, IndexAsComment index_as_comment=kDontPrintIndex)
void PrintLocalName (StringBuilder &out, uint32_t function_index, uint32_t local_index, IndexAsComment index_as_comment=kDontPrintIndex)
void PrintLabelName (StringBuilder &out, uint32_t function_index, uint32_t label_index, uint32_t fallback_index)
void PrintTypeName (StringBuilder &out, uint32_t type_index, IndexAsComment index_as_comment=kDontPrintIndex)
void PrintTypeName (StringBuilder &out, ModuleTypeIndex type_index, IndexAsComment index_as_comment=kDontPrintIndex)
void PrintTableName (StringBuilder &out, uint32_t table_index, IndexAsComment index_as_comment=kDontPrintIndex)
void PrintMemoryName (StringBuilder &out, uint32_t memory_index, IndexAsComment index_as_comment=kDontPrintIndex)
void PrintGlobalName (StringBuilder &out, uint32_t global_index, IndexAsComment index_as_comment=kDontPrintIndex)
void PrintElementSegmentName (StringBuilder &out, uint32_t element_segment_index, IndexAsComment index_as_comment=kDontPrintIndex)
void PrintDataSegmentName (StringBuilder &out, uint32_t data_segment_index, IndexAsComment index_as_comment=kDontPrintIndex)
void PrintFieldName (StringBuilder &out, uint32_t struct_index, uint32_t field_index, IndexAsComment index_as_comment=kDontPrintIndex)
void PrintTagName (StringBuilder &out, uint32_t tag_index, IndexAsComment index_as_comment=kDontPrintIndex)
void PrintHeapType (StringBuilder &out, HeapType type)
void PrintValueType (StringBuilder &out, ValueType type)
size_t EstimateCurrentMemoryConsumption () const
Private Member Functions
void DecodeNamesIfNotYetDone ()
void ComputeFunctionNamesFromImportsExports ()
void ComputeNamesFromImportsExports ()
void ComputeImportName (const WasmImport &import, std::map< uint32_t, std::string > &target)
void ComputeExportName (const WasmExport &ex, std::map< uint32_t, std::string > &target)
void WriteRef (StringBuilder &out, WireBytesRef ref)
Private Attributes
base::Mutex mutex_
bool has_decoded_ {false}
bool has_computed_function_import_names_ {false}
bool has_computed_import_names_ {false}
const WasmModule * module_
base::Vector< const uint8_t > wire_bytes_
std::unique_ptr< DecodedNameSection > name_section_names_
std::map< uint32_t, std::string > import_export_function_names_
std::map< uint32_t, std::string > import_export_table_names_
std::map< uint32_t, std::string > import_export_memory_names_
std::map< uint32_t, std::string > import_export_global_names_
std::map< uint32_t, std::string > import_export_tag_names_
Detailed Description
Definition at line 26 of file names-provider.h.
Member Enumeration Documentation
FunctionNamesBehavior
enum v8::internal::wasm::NamesProvider::FunctionNamesBehavior : bool
Enumerator
kWasmInternal
kDevTools
Definition at line 31 of file names-provider.h.
: bool { kWasmInternal = false, kDevTools = true };
IndexAsComment
enum v8::internal::wasm::NamesProvider::IndexAsComment : bool
Enumerator
kDontPrintIndex
kIndexAsComment
Definition at line 33 of file names-provider.h.
                      : bool {
    kDontPrintIndex = false,
    kIndexAsComment = true
  };
Constructor & Destructor Documentation
NamesProvider()
v8::internal::wasm::NamesProvider::NamesProvider (const WasmModule * module, base::Vector< const uint8_t > wire_bytes)
Definition at line 19 of file names-provider.cc.
    : module_(module), wire_bytes_(wire_bytes) {}
Referenced by EstimateCurrentMemoryConsumption().
 NamesProvider()
v8::internal::wasm::NamesProvider::~NamesProvider () [default]
Member Function Documentation
ComputeExportName()
void v8::internal::wasm::NamesProvider::ComputeExportName (const WasmExport & ex, std::map< uint32_t, std::string > & target) [private]
Definition at line 160 of file names-provider.cc.
                                                                           {
  if (target.find(ex.index) != target.end()) return;
  size_t length = ex.name.length();
  if (length == 0) return;
  StringBuilder buffer;
  buffer << '$';
  SanitizeUnicodeName(buffer, wire_bytes_.begin() + ex.name.offset(), length);
  target[ex.index] = std::string(buffer.start(), buffer.length());
}
References v8::base::Vector< T >::begin(), v8::internal::wasm::WasmExport::index, v8::internal::length, v8::internal::wasm::StringBuilder::length(), v8::internal::wasm::WireBytesRef::length(), v8::internal::wasm::WasmExport::name, v8::internal::wasm::WireBytesRef::offset(), v8::internal::wasm::anonymous_namespace{names-provider.cc}::SanitizeUnicodeName(), v8::internal::wasm::StringBuilder::start(), v8::internal::string, and wire_bytes_.
Referenced by ComputeFunctionNamesFromImportsExports(), and ComputeNamesFromImportsExports().
ComputeFunctionNamesFromImportsExports()
void v8::internal::wasm::NamesProvider::ComputeFunctionNamesFromImportsExports () [private]
Definition at line 38 of file names-provider.cc.
                                                           {
  DCHECK(!has_computed_function_import_names_);
  has_computed_function_import_names_ = true;
  // When tracing streaming compilations, we might not yet have wire bytes.
  if (wire_bytes_.empty()) return;
  for (const WasmImport& import : module_->import_table) {
    if (import.kind != kExternalFunction) continue;
    if (module_->lazily_generated_names.Has(import.index)) continue;
    ComputeImportName(import, import_export_function_names_);
  }
  for (const WasmExport& ex : module_->export_table) {
    if (ex.kind != kExternalFunction) continue;
    if (module_->lazily_generated_names.Has(ex.index)) continue;
    ComputeExportName(ex, import_export_function_names_);
  }
}
References ComputeExportName(), ComputeImportName(), v8::internal::DCHECK(), v8::base::Vector< T >::empty(), v8::internal::wasm::WasmModule::export_table, v8::internal::wasm::LazilyGeneratedNames::Has(), has_computed_function_import_names_, import_export_function_names_, v8::internal::wasm::WasmModule::import_table, v8::internal::wasm::WasmExport::index, v8::internal::wasm::kExternalFunction, v8::internal::wasm::WasmExport::kind, v8::internal::wasm::WasmModule::lazily_generated_names, module_, and wire_bytes_.
Referenced by PrintFunctionName().
ComputeImportName()
void v8::internal::wasm::NamesProvider::ComputeImportName (const WasmImport & import, std::map< uint32_t, std::string > & target) [private]
Definition at line 146 of file names-provider.cc.
                                                                           {
  const uint8_t* mod_start = wire_bytes_.begin() + import.module_name.offset();
  size_t mod_length = import.module_name.length();
  const uint8_t* field_start = wire_bytes_.begin() + import.field_name.offset();
  size_t field_length = import.field_name.length();
  StringBuilder buffer;
  buffer << '$';
  SanitizeUnicodeName(buffer, mod_start, mod_length);
  buffer << '.';
  SanitizeUnicodeName(buffer, field_start, field_length);
  target[import.index] = std::string(buffer.start(), buffer.length());
}
References v8::base::Vector< T >::begin(), v8::internal::wasm::StringBuilder::length(), v8::internal::wasm::anonymous_namespace{names-provider.cc}::SanitizeUnicodeName(), v8::internal::wasm::StringBuilder::start(), v8::internal::string, and wire_bytes_.
Referenced by ComputeFunctionNamesFromImportsExports(), and ComputeNamesFromImportsExports().
ComputeNamesFromImportsExports()
void v8::internal::wasm::NamesProvider::ComputeNamesFromImportsExports () [private]
Definition at line 55 of file names-provider.cc.
                                                   {
  DCHECK(!has_computed_import_names_);
  has_computed_import_names_ = true;
  // When tracing streaming compilations, we might not yet have wire bytes.
  if (wire_bytes_.empty()) return;
  DCHECK(has_decoded_);
  for (const WasmImport import : module_->import_table) {
    switch (import.kind) {
      case kExternalFunction:
        continue; // Functions are handled separately.
      case kExternalTable:
        if (name_section_names_->table_names_.Has(import.index)) continue;
        ComputeImportName(import, import_export_table_names_);
        break;
      case kExternalMemory:
        if (name_section_names_->memory_names_.Has(import.index)) continue;
        ComputeImportName(import, import_export_memory_names_);
        break;
      case kExternalGlobal:
        if (name_section_names_->global_names_.Has(import.index)) continue;
        ComputeImportName(import, import_export_global_names_);
        break;
      case kExternalTag:
        if (name_section_names_->tag_names_.Has(import.index)) continue;
        ComputeImportName(import, import_export_tag_names_);
        break;
    }
  }
  for (const WasmExport& ex : module_->export_table) {
    switch (ex.kind) {
      case kExternalFunction:
        continue; // Functions are handled separately.
      case kExternalTable:
        if (name_section_names_->table_names_.Has(ex.index)) continue;
        ComputeExportName(ex, import_export_table_names_);
        break;
      case kExternalMemory:
        if (name_section_names_->memory_names_.Has(ex.index)) continue;
        ComputeExportName(ex, import_export_memory_names_);
        break;
      case kExternalGlobal:
        if (name_section_names_->global_names_.Has(ex.index)) continue;
        ComputeExportName(ex, import_export_global_names_);
        break;
      case kExternalTag:
        if (name_section_names_->tag_names_.Has(ex.index)) continue;
        ComputeExportName(ex, import_export_tag_names_);
        break;
    }
  }
}
References ComputeExportName(), ComputeImportName(), v8::internal::DCHECK(), v8::base::Vector< T >::empty(), v8::internal::wasm::WasmModule::export_table, has_computed_import_names_, has_decoded_, import_export_global_names_, import_export_memory_names_, import_export_table_names_, import_export_tag_names_, v8::internal::wasm::WasmModule::import_table, v8::internal::wasm::WasmExport::index, v8::internal::wasm::kExternalFunction, v8::internal::wasm::kExternalGlobal, v8::internal::wasm::kExternalMemory, v8::internal::wasm::kExternalTable, v8::internal::wasm::kExternalTag, v8::internal::wasm::WasmExport::kind, module_, name_section_names_, and wire_bytes_.
Referenced by DecodeNamesIfNotYetDone().
DecodeNamesIfNotYetDone()
void v8::internal::wasm::NamesProvider::DecodeNamesIfNotYetDone () [private]
Definition at line 25 of file names-provider.cc.
                                            {
  base::MutexGuard lock(&mutex_);
  if (has_decoded_) return;
  has_decoded_ = true;
  name_section_names_.reset(
      new DecodedNameSection(wire_bytes_, module_->name_section));
  ComputeNamesFromImportsExports();
}
References ComputeNamesFromImportsExports(), has_decoded_, module_, mutex_, v8::internal::wasm::WasmModule::name_section, name_section_names_, and wire_bytes_.
Referenced by PrintDataSegmentName(), PrintElementSegmentName(), PrintFieldName(), PrintGlobalName(), PrintLabelName(), PrintLocalName(), PrintMemoryName(), PrintTableName(), PrintTagName(), and PrintTypeName().
EstimateCurrentMemoryConsumption()
size_t v8::internal::wasm::NamesProvider::EstimateCurrentMemoryConsumption () const
Definition at line 421 of file names-provider.cc.
                                                             {
  UPDATE_WHEN_CLASS_CHANGES(NamesProvider, 176);
  size_t result = sizeof(NamesProvider);
  if (name_section_names_) {
    DecodedNameSection* names = name_section_names_.get();
    result += names->local_names_.EstimateCurrentMemoryConsumption();
    result += names->label_names_.EstimateCurrentMemoryConsumption();
    result += names->type_names_.EstimateCurrentMemoryConsumption();
    result += names->table_names_.EstimateCurrentMemoryConsumption();
    result += names->memory_names_.EstimateCurrentMemoryConsumption();
    result += names->global_names_.EstimateCurrentMemoryConsumption();
    result += names->element_segment_names_.EstimateCurrentMemoryConsumption();
    result += names->data_segment_names_.EstimateCurrentMemoryConsumption();
    result += names->field_names_.EstimateCurrentMemoryConsumption();
    result += names->tag_names_.EstimateCurrentMemoryConsumption();
  }
  {
    base::MutexGuard lock(&mutex_);
    result += StringMapSize(import_export_function_names_);
    result += StringMapSize(import_export_table_names_);
    result += StringMapSize(import_export_memory_names_);
    result += StringMapSize(import_export_global_names_);
    result += StringMapSize(import_export_tag_names_);
  }
  if (v8_flags.trace_wasm_offheap_memory) {
    PrintF("NamesProvider: %zu\n", result);
  }
  return result;
}
References v8::internal::wasm::DecodedNameSection::data_segment_names_, v8::internal::wasm::DecodedNameSection::element_segment_names_, v8::internal::wasm::AdaptiveMap< Value >::EstimateCurrentMemoryConsumption(), v8::internal::wasm::DecodedNameSection::field_names_, v8::internal::wasm::DecodedNameSection::global_names_, import_export_function_names_, import_export_global_names_, import_export_memory_names_, import_export_table_names_, import_export_tag_names_, v8::internal::wasm::DecodedNameSection::label_names_, v8::internal::wasm::DecodedNameSection::local_names_, v8::internal::wasm::DecodedNameSection::memory_names_, mutex_, name_section_names_, NamesProvider(), v8::internal::PrintF(), v8::base::internal::result, v8::internal::wasm::anonymous_namespace{names-provider.cc}::StringMapSize(), v8::internal::wasm::DecodedNameSection::table_names_, v8::internal::wasm::DecodedNameSection::tag_names_, v8::internal::wasm::DecodedNameSection::type_names_, UPDATE_WHEN_CLASS_CHANGES, and v8::internal::v8_flags.
PrintDataSegmentName()
void v8::internal::wasm::NamesProvider::PrintDataSegmentName (StringBuilder & out, uint32_t data_segment_index, IndexAsComment index_as_comment = kDontPrintIndex)
Definition at line 345 of file names-provider.cc.
                                                                          {
  DecodeNamesIfNotYetDone();
  WireBytesRef ref =
      Get(name_section_names_->data_segment_names_, data_segment_index);
  if (ref.is_set()) {
    out << '$';
    WriteRef(out, ref);
    MaybeAddComment(out, data_segment_index, index_as_comment);
  } else {
    out << "$data" << data_segment_index;
  }
}
References DecodeNamesIfNotYetDone(), v8::internal::wasm::Get(), v8::internal::wasm::WireBytesRef::is_set(), v8::internal::wasm::anonymous_namespace{names-provider.cc}::MaybeAddComment(), name_section_names_, and WriteRef().
Referenced by v8::internal::wasm::ImmediatesPrinter< ValidationTag >::DataSegmentIndex(), and v8::internal::wasm::ModuleDisassembler::PrintModule().
PrintElementSegmentName()
void v8::internal::wasm::NamesProvider::PrintElementSegmentName (StringBuilder & out, uint32_t element_segment_index, IndexAsComment index_as_comment = kDontPrintIndex)
Definition at line 330 of file names-provider.cc.
                                                                             {
  DecodeNamesIfNotYetDone();
  WireBytesRef ref =
      Get(name_section_names_->element_segment_names_, element_segment_index);
  if (ref.is_set()) {
    out << '$';
    WriteRef(out, ref);
    MaybeAddComment(out, element_segment_index, index_as_comment);
  } else {
    out << "$elem" << element_segment_index;
  }
}
References DecodeNamesIfNotYetDone(), v8::internal::wasm::Get(), v8::internal::wasm::WireBytesRef::is_set(), v8::internal::wasm::anonymous_namespace{names-provider.cc}::MaybeAddComment(), name_section_names_, and WriteRef().
Referenced by v8::internal::wasm::ImmediatesPrinter< ValidationTag >::ElemSegmentIndex(), and v8::internal::wasm::ModuleDisassembler::PrintModule().
PrintFieldName()
void v8::internal::wasm::NamesProvider::PrintFieldName (StringBuilder & out, uint32_t struct_index, uint32_t field_index, IndexAsComment index_as_comment = kDontPrintIndex)
Definition at line 360 of file names-provider.cc.
                                                                    {
  DecodeNamesIfNotYetDone();
  WireBytesRef ref =
      Get(name_section_names_->field_names_, struct_index, field_index);
  if (ref.is_set()) {
    out << '$';
    WriteRef(out, ref);
    return MaybeAddComment(out, field_index, index_as_comment);
  }
  out << "$field" << field_index;
}
References DecodeNamesIfNotYetDone(), v8::internal::wasm::Get(), v8::internal::wasm::WireBytesRef::is_set(), v8::internal::wasm::anonymous_namespace{names-provider.cc}::MaybeAddComment(), name_section_names_, and WriteRef().
Referenced by v8::internal::wasm::ImmediatesPrinter< ValidationTag >::Field(), and v8::internal::wasm::ModuleDisassembler::PrintTypeDefinition().
PrintFunctionName()
void v8::internal::wasm::NamesProvider::PrintFunctionName (StringBuilder & out, uint32_t function_index, FunctionNamesBehavior behavior = kWasmInternal, IndexAsComment index_as_comment = kDontPrintIndex)
Definition at line 184 of file names-provider.cc.
                                                                       {
  // Function names are stored elsewhere, because we need to access them
  // during (streaming) compilation when the NamesProvider isn't ready yet.
  WireBytesRef ref = module_->lazily_generated_names.LookupFunctionName(
      ModuleWireBytes(wire_bytes_), function_index);
  if (ref.is_set()) {
    if (behavior == kDevTools) {
      out << '$';
      WriteRef(out, ref);
      MaybeAddComment(out, function_index, index_as_comment);
    } else {
      // For kWasmInternal behavior, function names don't get a `$` prefix.
      WriteRef(out, ref);
    }
    return;
  }
  if (behavior == kWasmInternal) return;
  {
    base::MutexGuard lock(&mutex_);
    if (!has_computed_function_import_names_) {
      ComputeFunctionNamesFromImportsExports();
    }
  }
  auto it = import_export_function_names_.find(function_index);
  if (it != import_export_function_names_.end()) {
    out << it->second;
    MaybeAddComment(out, function_index, index_as_comment);
  } else {
    out << "$func" << function_index;
  }
}
References ComputeFunctionNamesFromImportsExports(), has_computed_function_import_names_, import_export_function_names_, v8::internal::wasm::WireBytesRef::is_set(), kDevTools, kWasmInternal, v8::internal::wasm::WasmModule::lazily_generated_names, v8::internal::wasm::LazilyGeneratedNames::LookupFunctionName(), v8::internal::wasm::anonymous_namespace{names-provider.cc}::MaybeAddComment(), module_, mutex_, wire_bytes_, and WriteRef().
Referenced by v8::internal::wasm::FunctionBodyDisassembler::DecodeAsWat(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::FunctionIndex(), v8::internal::GetWasmFunctionDebugName(), v8::internal::wasm::ModuleDisassembler::PrintInitExpression(), and v8::internal::wasm::ModuleDisassembler::PrintModule().
PrintGlobalName()
void v8::internal::wasm::NamesProvider::PrintGlobalName (StringBuilder & out, uint32_t global_index, IndexAsComment index_as_comment = kDontPrintIndex)
Definition at line 311 of file names-provider.cc.
                                                                     {
  DecodeNamesIfNotYetDone();
  WireBytesRef ref = Get(name_section_names_->global_names_, global_index);
  if (ref.is_set()) {
    out << '$';
    WriteRef(out, ref);
    return MaybeAddComment(out, global_index, index_as_comment);
  }
  auto it = import_export_global_names_.find(global_index);
  if (it != import_export_global_names_.end()) {
    out << it->second;
    return MaybeAddComment(out, global_index, index_as_comment);
  }
  out << "$global" << global_index;
}
References DecodeNamesIfNotYetDone(), v8::internal::wasm::Get(), import_export_global_names_, v8::internal::wasm::WireBytesRef::is_set(), v8::internal::wasm::anonymous_namespace{names-provider.cc}::MaybeAddComment(), name_section_names_, and WriteRef().
Referenced by v8::internal::anonymous_namespace{debug-wasm-objects.cc}::GlobalsProxy::GetName(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::GlobalIndex(), and v8::internal::wasm::ModuleDisassembler::PrintModule().
PrintHeapType()
void v8::internal::wasm::NamesProvider::PrintHeapType (StringBuilder & out, HeapType type)
Definition at line 391 of file names-provider.cc.
                                                                   {
  if (type.is_index()) {
    if (type.is_exact()) out << "exact ";
    PrintTypeName(out, type.ref_index());
  } else {
    out << type.name();
  }
}
References PrintTypeName(), and v8::internal::tracing::type.
Referenced by v8::internal::wasm::ImmediatesPrinter< ValidationTag >::HeapType(), v8::internal::wasm::ModuleDisassembler::PrintInitExpression(), and v8::internal::wasm::ModuleDisassembler::PrintTypeDefinition().
PrintLabelName()
void v8::internal::wasm::NamesProvider::PrintLabelName (StringBuilder & out, uint32_t function_index, uint32_t label_index, uint32_t fallback_index)
Definition at line 248 of file names-provider.cc.
                                                            {
  DecodeNamesIfNotYetDone();
  WireBytesRef ref =
      Get(name_section_names_->label_names_, function_index, label_index);
  if (ref.is_set()) {
    out << '$';
    WriteRef(out, ref);
  } else {
    out << "$label" << fallback_index;
  }
}
References DecodeNamesIfNotYetDone(), v8::internal::wasm::Get(), v8::internal::wasm::WireBytesRef::is_set(), name_section_names_, and WriteRef().
Referenced by v8::internal::wasm::ImmediatesPrinter< ValidationTag >::PrintDepthAsLabel().
PrintLocalName()
void v8::internal::wasm::NamesProvider::PrintLocalName (StringBuilder & out, uint32_t function_index, uint32_t local_index, IndexAsComment index_as_comment = kDontPrintIndex)
Definition at line 233 of file names-provider.cc.
                                                                    {
  DecodeNamesIfNotYetDone();
  WireBytesRef ref =
      Get(name_section_names_->local_names_, function_index, local_index);
  if (ref.is_set()) {
    out << '$';
    WriteRef(out, ref);
    MaybeAddComment(out, local_index, index_as_comment);
  } else {
    out << "$var" << local_index;
  }
}
References DecodeNamesIfNotYetDone(), v8::internal::wasm::Get(), v8::internal::wasm::WireBytesRef::is_set(), v8::internal::wasm::anonymous_namespace{names-provider.cc}::MaybeAddComment(), name_section_names_, and WriteRef().
Referenced by v8::internal::wasm::FunctionBodyDisassembler::DecodeAsWat(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::LocalsProxy::GetName(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::LocalIndex(), v8::internal::wasm::PrintSignatureOneLine(), and v8::internal::wasm::ModuleDisassembler::PrintTypeDefinition().
PrintMemoryName()
void v8::internal::wasm::NamesProvider::PrintMemoryName (StringBuilder & out, uint32_t memory_index, IndexAsComment index_as_comment = kDontPrintIndex)
Definition at line 292 of file names-provider.cc.
                                                                     {
  DecodeNamesIfNotYetDone();
  WireBytesRef ref = Get(name_section_names_->memory_names_, memory_index);
  if (ref.is_set()) {
    out << '$';
    WriteRef(out, ref);
    return MaybeAddComment(out, memory_index, index_as_comment);
  }
  auto it = import_export_memory_names_.find(memory_index);
  if (it != import_export_memory_names_.end()) {
    out << it->second;
    return MaybeAddComment(out, memory_index, index_as_comment);
  }
  out << "$memory" << memory_index;
}
References DecodeNamesIfNotYetDone(), v8::internal::wasm::Get(), import_export_memory_names_, v8::internal::wasm::WireBytesRef::is_set(), v8::internal::wasm::anonymous_namespace{names-provider.cc}::MaybeAddComment(), name_section_names_, and WriteRef().
Referenced by v8::internal::anonymous_namespace{debug-wasm-objects.cc}::MemoriesProxy::GetName(), and v8::internal::wasm::ModuleDisassembler::PrintModule().
PrintTableName()
void v8::internal::wasm::NamesProvider::PrintTableName (StringBuilder & out, uint32_t table_index, IndexAsComment index_as_comment = kDontPrintIndex)
Definition at line 274 of file names-provider.cc.
                                                                    {
  DecodeNamesIfNotYetDone();
  WireBytesRef ref = Get(name_section_names_->table_names_, table_index);
  if (ref.is_set()) {
    out << '$';
    WriteRef(out, ref);
    return MaybeAddComment(out, table_index, index_as_comment);
  }
  auto it = import_export_table_names_.find(table_index);
  if (it != import_export_table_names_.end()) {
    out << it->second;
    return MaybeAddComment(out, table_index, index_as_comment);
  }
  out << "$table" << table_index;
}
References DecodeNamesIfNotYetDone(), v8::internal::wasm::Get(), import_export_table_names_, v8::internal::wasm::WireBytesRef::is_set(), v8::internal::wasm::anonymous_namespace{names-provider.cc}::MaybeAddComment(), name_section_names_, and WriteRef().
Referenced by v8::internal::anonymous_namespace{debug-wasm-objects.cc}::TablesProxy::GetName(), v8::internal::wasm::ModuleDisassembler::PrintModule(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::TableCopy(), and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::TableIndex().
PrintTagName()
void v8::internal::wasm::NamesProvider::PrintTagName (StringBuilder & out, uint32_t tag_index, IndexAsComment index_as_comment = kDontPrintIndex)
Definition at line 374 of file names-provider.cc.
                                                                  {
  DecodeNamesIfNotYetDone();
  WireBytesRef ref = Get(name_section_names_->tag_names_, tag_index);
  if (ref.is_set()) {
    out << '$';
    WriteRef(out, ref);
    return MaybeAddComment(out, tag_index, index_as_comment);
  }
  auto it = import_export_tag_names_.find(tag_index);
  if (it != import_export_tag_names_.end()) {
    out << it->second;
    return MaybeAddComment(out, tag_index, index_as_comment);
  }
  out << "$tag" << tag_index;
}
References DecodeNamesIfNotYetDone(), v8::internal::wasm::Get(), import_export_tag_names_, v8::internal::wasm::WireBytesRef::is_set(), v8::internal::wasm::anonymous_namespace{names-provider.cc}::MaybeAddComment(), name_section_names_, and WriteRef().
Referenced by v8::internal::wasm::ImmediatesPrinter< ValidationTag >::EffectHandlerTable(), v8::internal::wasm::ModuleDisassembler::PrintModule(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::TagIndex(), and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::TryTable().
PrintTypeName() [1/2]
void v8::internal::wasm::NamesProvider::PrintTypeName (StringBuilder & out, ModuleTypeIndex type_index, IndexAsComment index_as_comment = kDontPrintIndex) [inline]
Definition at line 52 of file names-provider.h.
                                                                        {
    PrintTypeName(out, type_index.index, index_as_comment);
  }
References v8::internal::wasm::TypeIndex::index.
PrintTypeName() [2/2]
void v8::internal::wasm::NamesProvider::PrintTypeName (StringBuilder & out, uint32_t type_index, IndexAsComment index_as_comment = kDontPrintIndex)
Definition at line 262 of file names-provider.cc.
                                                                   {
  DecodeNamesIfNotYetDone();
  WireBytesRef ref = Get(name_section_names_->type_names_, type_index);
  if (ref.is_set()) {
    out << '$';
    WriteRef(out, ref);
    return MaybeAddComment(out, type_index, index_as_comment);
  }
  out << "$type" << type_index;
}
References DecodeNamesIfNotYetDone(), v8::internal::wasm::Get(), v8::internal::wasm::WireBytesRef::is_set(), v8::internal::wasm::anonymous_namespace{names-provider.cc}::MaybeAddComment(), name_section_names_, and WriteRef().
Referenced by v8::internal::wasm::ImmediatesPrinter< ValidationTag >::ArrayCopy(), PrintHeapType(), v8::internal::wasm::ModuleDisassembler::PrintTypeDefinition(), PrintValueType(), and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::TypeIndex().
PrintValueType()
void v8::internal::wasm::NamesProvider::PrintValueType (StringBuilder & out, ValueType type)
Definition at line 400 of file names-provider.cc.
                                                                     {
  if (type.has_index()) {
    out << (type.is_nullable() ? "(ref null " : "(ref ");
    if (type.is_exact()) out << "exact ";
    PrintTypeName(out, type.ref_index());
    out << ')';
  } else {
    out << type.name();
  }
}
References PrintTypeName(), and v8::internal::tracing::type.
Referenced by v8::internal::wasm::FunctionBodyDisassembler::DecodeAsWat(), v8::internal::wasm::ModuleDisassembler::PrintModule(), v8::internal::wasm::ModuleDisassembler::PrintMutableType(), v8::internal::wasm::PrintSignatureOneLine(), v8::internal::wasm::ModuleDisassembler::PrintTable(), v8::internal::wasm::ModuleDisassembler::PrintTagSignature(), v8::internal::wasm::ModuleDisassembler::PrintTypeDefinition(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::SelectType(), and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::ValueType().
WriteRef()
void v8::internal::wasm::NamesProvider::WriteRef (StringBuilder & out, WireBytesRef ref) [private]
Definition at line 180 of file names-provider.cc.
                                                                 {
  out.write(wire_bytes_.begin() + ref.offset(), ref.length());
}
References v8::base::Vector< T >::begin(), v8::internal::wasm::WireBytesRef::length(), v8::internal::wasm::WireBytesRef::offset(), wire_bytes_, and v8::internal::wasm::StringBuilder::write().
Referenced by PrintDataSegmentName(), PrintElementSegmentName(), PrintFieldName(), PrintFunctionName(), PrintGlobalName(), PrintLabelName(), PrintLocalName(), PrintMemoryName(), PrintTableName(), PrintTagName(), and PrintTypeName().
Member Data Documentation
has_computed_function_import_names_
bool v8::internal::wasm::NamesProvider::has_computed_function_import_names_ {false} [private]
Definition at line 92 of file names-provider.h.
Referenced by ComputeFunctionNamesFromImportsExports(), and PrintFunctionName().
has_computed_import_names_
bool v8::internal::wasm::NamesProvider::has_computed_import_names_ {false} [private]
Definition at line 93 of file names-provider.h.
Referenced by ComputeNamesFromImportsExports().
has_decoded_
bool v8::internal::wasm::NamesProvider::has_decoded_ {false} [private]
Definition at line 91 of file names-provider.h.
Referenced by ComputeNamesFromImportsExports(), and DecodeNamesIfNotYetDone().
import_export_function_names_
std::map<uint32_t, std::string> v8::internal::wasm::NamesProvider::import_export_function_names_ [private]
Definition at line 97 of file names-provider.h.
Referenced by ComputeFunctionNamesFromImportsExports(), EstimateCurrentMemoryConsumption(), and PrintFunctionName().
import_export_global_names_
std::map<uint32_t, std::string> v8::internal::wasm::NamesProvider::import_export_global_names_ [private]
Definition at line 100 of file names-provider.h.
Referenced by ComputeNamesFromImportsExports(), EstimateCurrentMemoryConsumption(), and PrintGlobalName().
import_export_memory_names_
std::map<uint32_t, std::string> v8::internal::wasm::NamesProvider::import_export_memory_names_ [private]
Definition at line 99 of file names-provider.h.
Referenced by ComputeNamesFromImportsExports(), EstimateCurrentMemoryConsumption(), and PrintMemoryName().
import_export_table_names_
std::map<uint32_t, std::string> v8::internal::wasm::NamesProvider::import_export_table_names_ [private]
Definition at line 98 of file names-provider.h.
Referenced by ComputeNamesFromImportsExports(), EstimateCurrentMemoryConsumption(), and PrintTableName().
import_export_tag_names_
std::map<uint32_t, std::string> v8::internal::wasm::NamesProvider::import_export_tag_names_ [private]
Definition at line 101 of file names-provider.h.
Referenced by ComputeNamesFromImportsExports(), EstimateCurrentMemoryConsumption(), and PrintTagName().
module_
const WasmModule* v8::internal::wasm::NamesProvider::module_ [private]
Definition at line 94 of file names-provider.h.
Referenced by ComputeFunctionNamesFromImportsExports(), ComputeNamesFromImportsExports(), DecodeNamesIfNotYetDone(), and PrintFunctionName().
mutex_
base::Mutex v8::internal::wasm::NamesProvider::mutex_ [mutable], [private]
Definition at line 90 of file names-provider.h.
Referenced by DecodeNamesIfNotYetDone(), EstimateCurrentMemoryConsumption(), and PrintFunctionName().
name_section_names_
std::unique_ptr<DecodedNameSection> v8::internal::wasm::NamesProvider::name_section_names_ [private]
Definition at line 96 of file names-provider.h.
Referenced by ComputeNamesFromImportsExports(), DecodeNamesIfNotYetDone(), EstimateCurrentMemoryConsumption(), PrintDataSegmentName(), PrintElementSegmentName(), PrintFieldName(), PrintGlobalName(), PrintLabelName(), PrintLocalName(), PrintMemoryName(), PrintTableName(), PrintTagName(), and PrintTypeName().
wire_bytes_
base::Vector<const uint8_t> v8::internal::wasm::NamesProvider::wire_bytes_ [private]
Definition at line 95 of file names-provider.h.
Referenced by ComputeExportName(), ComputeFunctionNamesFromImportsExports(), ComputeImportName(), ComputeNamesFromImportsExports(), DecodeNamesIfNotYetDone(), PrintFunctionName(), and WriteRef().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/names-provider.h
/mnt/V8SourceCode/src/wasm/names-provider.cc