v8::internal::interpreter::ConstantArrayBuilder::Entry Class Reference
Public Member Functions
Entry (Tagged< Smi > smi)
Entry (double heap_number)
Entry (const AstRawString *raw_string)
Entry (const AstConsString *cons_string)
Entry (AstBigInt bigint)
Entry (const Scope *scope)
bool IsDeferred () const
bool IsJumpTableEntry () const
void SetDeferred (Handle< Object > handle)
void SetJumpTableSmi (Tagged< Smi > smi)
template<typename IsolateT >
Handle< Object > ToHandle (IsolateT *isolate) const
Static Public Member Functions
static Entry Deferred ()
static Entry UninitializedJumpTableSmi ()
Private Types
enum class Tag : uint8_t {
kDeferred
, kHandle
, kSmi
, kRawString
,
kConsString
, kHeapNumber
, kBigInt
, kScope
,
kUninitializedJumpTableSmi
, kJumpTableSmi
, ENTRY_TAG
 }
Private Member Functions
Entry (Tag tag)
Private Attributes
xx xx xx xx xx xx xx xx xx
union {
 IndirectHandle< Object > handle_
 Tagged< Smi > smi_
 double heap_number_
 const AstRawString * raw_string_
 const AstConsString * cons_string_
 AstBigInt bigint_
 const Scope * scope_
};
enum v8::internal::interpreter::ConstantArrayBuilder::Entry::Tag tag_
Detailed Description
Definition at line 115 of file constant-array-builder.h.
Member Enumeration Documentation
Tag
enum v8::internal::interpreter::ConstantArrayBuilder::Entry::Tag : uint8_t [strong], [private]
Enumerator
kDeferred
kHandle
kSmi
kRawString
kConsString
kHeapNumber
kBigInt
kScope
kUninitializedJumpTableSmi
kJumpTableSmi
ENTRY_TAG
Definition at line 176 of file constant-array-builder.h.
                   : uint8_t {
      kDeferred,
      kHandle,
      kSmi,
      kRawString,
      kConsString,
      kHeapNumber,
      kBigInt,
      kScope,
      kUninitializedJumpTableSmi,
      kJumpTableSmi,
#define ENTRY_TAG(NAME, ...) k##NAME,
      SINGLETON_CONSTANT_ENTRY_TYPES(ENTRY_TAG)
#undef ENTRY_TAG
    } tag_;
Constructor & Destructor Documentation
Entry() [1/7]
v8::internal::interpreter::ConstantArrayBuilder::Entry::Entry (Tagged< Smi > smi) [inline], [explicit], [strong]
Definition at line 120 of file constant-array-builder.h.
: smi_(smi), tag_(Tag::kSmi) {}
Entry() [2/7]
v8::internal::interpreter::ConstantArrayBuilder::Entry::Entry (double heap_number) [inline], [explicit]
Definition at line 121 of file constant-array-builder.h.
        : heap_number_(heap_number), tag_(Tag::kHeapNumber) {}
Entry() [3/7]
v8::internal::interpreter::ConstantArrayBuilder::Entry::Entry (const AstRawString * raw_string) [inline], [explicit]
Definition at line 123 of file constant-array-builder.h.
        : raw_string_(raw_string), tag_(Tag::kRawString) {}
Entry() [4/7]
v8::internal::interpreter::ConstantArrayBuilder::Entry::Entry (const AstConsString * cons_string) [inline], [explicit]
Definition at line 125 of file constant-array-builder.h.
        : cons_string_(cons_string), tag_(Tag::kConsString) {}
Entry() [5/7]
v8::internal::interpreter::ConstantArrayBuilder::Entry::Entry (AstBigInt bigint) [inline], [explicit]
Definition at line 127 of file constant-array-builder.h.
: bigint_(bigint), tag_(Tag::kBigInt) {}
Entry() [6/7]
v8::internal::interpreter::ConstantArrayBuilder::Entry::Entry (const Scope * scope) [inline], [explicit]
Definition at line 128 of file constant-array-builder.h.
: scope_(scope), tag_(Tag::kScope) {}
Entry() [7/7]
v8::internal::interpreter::ConstantArrayBuilder::Entry::Entry (Tag tag) [inline], [explicit], [private]
Definition at line 164 of file constant-array-builder.h.
: tag_(tag) {}
Member Function Documentation
Deferred()
static Entry v8::internal::interpreter::ConstantArrayBuilder::Entry::Deferred () [inline], [static]
Definition at line 135 of file constant-array-builder.h.
{ return Entry(Tag::kDeferred); }
Referenced by v8::internal::interpreter::ConstantArrayBuilder::InsertDeferred().
IsDeferred()
bool v8::internal::interpreter::ConstantArrayBuilder::Entry::IsDeferred () const [inline]
Definition at line 141 of file constant-array-builder.h.
{ return tag_ == Tag::kDeferred; }
Referenced by v8::internal::interpreter::ConstantArrayBuilder::At().
IsJumpTableEntry()
bool v8::internal::interpreter::ConstantArrayBuilder::Entry::IsJumpTableEntry () const [inline]
Definition at line 143 of file constant-array-builder.h.
                                  {
      return tag_ == Tag::kUninitializedJumpTableSmi ||
             tag_ == Tag::kJumpTableSmi;
    }
SetDeferred()
void v8::internal::interpreter::ConstantArrayBuilder::Entry::SetDeferred (Handle< Object > handle) [inline]
Definition at line 148 of file constant-array-builder.h.
                                            {
      DCHECK_EQ(tag_, Tag::kDeferred);
      tag_ = Tag::kHandle;
      handle_ = handle;
    }
References DCHECK_EQ, and v8::internal::handle().
Referenced by v8::internal::interpreter::ConstantArrayBuilder::SetDeferredAt().
SetJumpTableSmi()
void v8::internal::interpreter::ConstantArrayBuilder::Entry::SetJumpTableSmi (Tagged< Smi > smi) [inline]
Definition at line 154 of file constant-array-builder.h.
                                          {
      DCHECK_EQ(tag_, Tag::kUninitializedJumpTableSmi);
      tag_ = Tag::kJumpTableSmi;
      smi_ = smi;
    }
References DCHECK_EQ.
Referenced by v8::internal::interpreter::ConstantArrayBuilder::SetJumpTableSmi().
ToHandle()
template<typename IsolateT >
template Handle< Object > v8::internal::interpreter::ConstantArrayBuilder::Entry::ToHandle (IsolateT * isolate) const
Definition at line 396 of file constant-array-builder.cc.
                                                                          {
  switch (tag_) {
    case Tag::kDeferred:
      // We shouldn't have any deferred entries by now.
      UNREACHABLE();
    case Tag::kHandle:
      return handle_;
    case Tag::kSmi:
    case Tag::kJumpTableSmi:
      return handle(smi_, isolate);
    case Tag::kUninitializedJumpTableSmi:
      // TODO(leszeks): There's probably a better value we could use here.
      return isolate->factory()->the_hole_value();
    case Tag::kRawString:
      return raw_string_->string();
    case Tag::kConsString:
      return cons_string_->AllocateFlat(isolate);
    case Tag::kHeapNumber:
      return isolate->factory()->template NewNumber<AllocationType::kOld>(
          heap_number_);
    case Tag::kBigInt:
      // This should never fail: the parser will never create a BigInt
      // literal that cannot be allocated.
      return BigIntLiteral(isolate, bigint_.c_str()).ToHandleChecked();
    case Tag::kScope:
      return scope_->scope_info();
#define ENTRY_LOOKUP(Name, name) \
  case Tag::k##Name: \
    return isolate->factory()->name();
      SINGLETON_CONSTANT_ENTRY_TYPES(ENTRY_LOOKUP);
#undef ENTRY_LOOKUP
  }
  UNREACHABLE();
}
References v8::internal::AstConsString::AllocateFlat(), bigint_, v8::internal::BigIntLiteral(), v8::internal::AstBigInt::c_str(), cons_string_, ENTRY_LOOKUP, v8::internal::handle(), handle_, heap_number_, kBigInt, kConsString, kDeferred, kHandle, kHeapNumber, kJumpTableSmi, kRawString, kScope, kSmi, kUninitializedJumpTableSmi, raw_string_, scope_, v8::internal::Scope::scope_info(), SINGLETON_CONSTANT_ENTRY_TYPES, smi_, v8::internal::AstRawString::string(), tag_, and v8::internal::UNREACHABLE().
Referenced by v8::internal::interpreter::ConstantArrayBuilder::At().
UninitializedJumpTableSmi()
static Entry v8::internal::interpreter::ConstantArrayBuilder::Entry::UninitializedJumpTableSmi () [inline], [static]
Definition at line 137 of file constant-array-builder.h.
                                             {
      return Entry(Tag::kUninitializedJumpTableSmi);
    }
Referenced by v8::internal::interpreter::ConstantArrayBuilder::InsertJumpTable().
Member Data Documentation
union { ... } [private]
bigint_
AstBigInt v8::internal::interpreter::ConstantArrayBuilder::Entry::bigint_
Definition at line 172 of file constant-array-builder.h.
Referenced by ToHandle().
cons_string_
const AstConsString* v8::internal::interpreter::ConstantArrayBuilder::Entry::cons_string_
Definition at line 171 of file constant-array-builder.h.
Referenced by ToHandle().
handle_
IndirectHandle<Object> v8::internal::interpreter::ConstantArrayBuilder::Entry::handle_
Definition at line 167 of file constant-array-builder.h.
Referenced by ToHandle().
heap_number_
double v8::internal::interpreter::ConstantArrayBuilder::Entry::heap_number_
Definition at line 169 of file constant-array-builder.h.
Referenced by ToHandle().
raw_string_
const AstRawString* v8::internal::interpreter::ConstantArrayBuilder::Entry::raw_string_
Definition at line 170 of file constant-array-builder.h.
Referenced by ToHandle().
scope_
const Scope* v8::internal::interpreter::ConstantArrayBuilder::Entry::scope_
Definition at line 173 of file constant-array-builder.h.
Referenced by ToHandle().
smi_
Tagged<Smi> v8::internal::interpreter::ConstantArrayBuilder::Entry::smi_
Definition at line 168 of file constant-array-builder.h.
Referenced by ToHandle().
tag_
enum v8::internal::interpreter::ConstantArrayBuilder::Entry::Tag v8::internal::interpreter::ConstantArrayBuilder::Entry::tag_ [private]
Referenced by ToHandle().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/interpreter/constant-array-builder.h
/mnt/V8SourceCode/src/interpreter/constant-array-builder.cc