v8::internal::compiler::turboshaft::ZoneWithName< Name > Class Template Reference
#include <zone-with-name.h>
Public Member Functions
ZoneWithName (ZoneStats *pool, const char *name, bool support_zone_compression=false)
ZoneWithName (const ZoneWithName &)=delete
ZoneWithName (ZoneWithName &&other) V8_NOEXCEPT
ZoneWithName & operator= (const ZoneWithName &)=delete
ZoneWithName & operator= (ZoneWithName &&other) V8_NOEXCEPT
template<typename T , typename... Args>
ZoneWithNamePointer< T, Name > New (Args &&... args)
template<typename T >
ZoneWithNamePointer< T, Name > AllocateArray (size_t length)
Zone * get ()
operator Zone * ()
Zone * operator-> ()
void Destroy ()
Private Attributes
ZoneStats::Scope scope_
Detailed Description
template<auto Name>
class v8::internal::compiler::turboshaft::ZoneWithName< Name >
Definition at line 81 of file zone-with-name.h.
Constructor & Destructor Documentation
ZoneWithName() [1/3]
template<auto Name>
v8::internal::compiler::turboshaft::ZoneWithName< Name >::ZoneWithName (ZoneStats * pool, const char * name, bool support_zone_compression = false) [inline]
Definition at line 83 of file zone-with-name.h.
      : scope_(pool, name, support_zone_compression) {
#ifdef HAS_CPP_CLASS_TYPES_AS_TEMPLATE_ARGS
    DCHECK_EQ(std::strcmp(name, Name.c_str()), 0);
#endif
  }
References DCHECK_EQ, and v8::internal::name.
ZoneWithName() [2/3]
template<auto Name>
v8::internal::compiler::turboshaft::ZoneWithName< Name >::ZoneWithName (const ZoneWithName< Name > &) [delete]
ZoneWithName() [3/3]
template<auto Name>
v8::internal::compiler::turboshaft::ZoneWithName< Name >::ZoneWithName (ZoneWithName< Name > && other) [inline]
Definition at line 92 of file zone-with-name.h.
      : scope_(std::move(other.scope_)) {}
Member Function Documentation
AllocateArray()
template<auto Name>
template<typename T >
ZoneWithNamePointer<T, Name> v8::internal::compiler::turboshaft::ZoneWithName< Name >::AllocateArray (size_t length) [inline]
Definition at line 107 of file zone-with-name.h.
                                                            {
    return ZoneWithNamePointer<T, Name>{
        get()->template AllocateArray<T>(length)};
  }
References v8::internal::compiler::turboshaft::ZoneWithName< Name >::get(), and v8::internal::length.
Destroy()
template<auto Name>
void v8::internal::compiler::turboshaft::ZoneWithName< Name >::Destroy () [inline]
Definition at line 116 of file zone-with-name.h.
{ scope_.Destroy(); }
References v8::internal::compiler::ZoneStats::Scope::Destroy(), and v8::internal::compiler::turboshaft::ZoneWithName< Name >::scope_.
Referenced by v8::internal::compiler::TFPipelineData::DeleteGraphZone().
get()
template<auto Name>
Zone* v8::internal::compiler::turboshaft::ZoneWithName< Name >::get () [inline]
Definition at line 112 of file zone-with-name.h.
{ return scope_.zone(); }
References v8::internal::compiler::turboshaft::ZoneWithName< Name >::scope_, and v8::internal::compiler::ZoneStats::Scope::zone().
Referenced by v8::internal::compiler::turboshaft::ZoneWithName< Name >::AllocateArray(), v8::internal::compiler::turboshaft::ZoneWithName< Name >::New(), v8::internal::compiler::turboshaft::ZoneWithName< Name >::operator Zone *(), and v8::internal::compiler::turboshaft::ZoneWithName< Name >::operator->().
New()
template<auto Name>
template<typename T , typename... Args>
ZoneWithNamePointer<T, Name> v8::internal::compiler::turboshaft::ZoneWithName< Name >::New (Args &&... args) [inline]
Definition at line 101 of file zone-with-name.h.
                                                   {
    return ZoneWithNamePointer<T, Name>{
        get()->template New<T>(std::forward<Args>(args)...)};
  }
References v8::base::args, and v8::internal::compiler::turboshaft::ZoneWithName< Name >::get().
Referenced by v8::internal::compiler::TFPipelineData::InitializeWithGraphZone().
operator Zone *()
template<auto Name>
v8::internal::compiler::turboshaft::ZoneWithName< Name >::operator Zone * () [inline]
Definition at line 113 of file zone-with-name.h.
{ return get(); } // NOLINT(runtime/explicit)
References v8::internal::compiler::turboshaft::ZoneWithName< Name >::get().
operator->()
template<auto Name>
Zone* v8::internal::compiler::turboshaft::ZoneWithName< Name >::operator-> () [inline]
Definition at line 114 of file zone-with-name.h.
{ return get(); }
References v8::internal::compiler::turboshaft::ZoneWithName< Name >::get().
operator=() [1/2]
template<auto Name>
ZoneWithName& v8::internal::compiler::turboshaft::ZoneWithName< Name >::operator= (const ZoneWithName< Name > &) [delete]
operator=() [2/2]
template<auto Name>
ZoneWithName& v8::internal::compiler::turboshaft::ZoneWithName< Name >::operator= (ZoneWithName< Name > && other) [inline]
Definition at line 95 of file zone-with-name.h.
                                                            {
    scope_ = std::move(other.scope_);
    return *this;
  }
References v8::internal::compiler::turboshaft::ZoneWithName< Name >::scope_.
Member Data Documentation
scope_
template<auto Name>
ZoneStats::Scope v8::internal::compiler::turboshaft::ZoneWithName< Name >::scope_ [private]
Definition at line 120 of file zone-with-name.h.
Referenced by v8::internal::compiler::turboshaft::ZoneWithName< Name >::Destroy(), v8::internal::compiler::turboshaft::ZoneWithName< Name >::get(), and v8::internal::compiler::turboshaft::ZoneWithName< Name >::operator=().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/zone-with-name.h