v8::internal::RegExpBytecodeGenerator Class Reference
#include <regexp-bytecode-generator.h>
Public Member Functions
RegExpBytecodeGenerator (Isolate *isolate, Zone *zone)
~RegExpBytecodeGenerator () override
int stack_limit_slack_slot_count () override
bool CanReadUnaligned () const override
void Bind (Label *label) override
void AdvanceCurrentPosition (int by) override
void PopCurrentPosition () override
void PushCurrentPosition () override
void Backtrack () override
void GoTo (Label *label) override
void PushBacktrack (Label *label) override
bool Succeed () override
void Fail () override
void PopRegister (int register_index) override
void PushRegister (int register_index, StackCheckFlag check_stack_limit) override
void AdvanceRegister (int reg, int by) override
void SetCurrentPositionFromEnd (int by) override
void SetRegister (int register_index, int to) override
void WriteCurrentPositionToRegister (int reg, int cp_offset) override
void ClearRegisters (int reg_from, int reg_to) override
void ReadCurrentPositionFromRegister (int reg) override
void WriteStackPointerToRegister (int reg) override
void ReadStackPointerFromRegister (int reg) override
void LoadCurrentCharacterImpl (int cp_offset, Label *on_end_of_input, bool check_bounds, int characters, int eats_at_least) override
void CheckCharacter (unsigned c, Label *on_equal) override
void CheckCharacterAfterAnd (unsigned c, unsigned mask, Label *on_equal) override
void CheckCharacterGT (base::uc16 limit, Label *on_greater) override
void CheckCharacterLT (base::uc16 limit, Label *on_less) override
void CheckFixedLengthLoop (Label *on_tos_equals_current_position) override
void CheckAtStart (int cp_offset, Label *on_at_start) override
void CheckNotAtStart (int cp_offset, Label *on_not_at_start) override
void CheckNotCharacter (unsigned c, Label *on_not_equal) override
void CheckNotCharacterAfterAnd (unsigned c, unsigned mask, Label *on_not_equal) override
void CheckNotCharacterAfterMinusAnd (base::uc16 c, base::uc16 minus, base::uc16 mask, Label *on_not_equal) override
void CheckCharacterInRange (base::uc16 from, base::uc16 to, Label *on_in_range) override
void CheckCharacterNotInRange (base::uc16 from, base::uc16 to, Label *on_not_in_range) override
bool CheckCharacterInRangeArray (const ZoneList< CharacterRange > *ranges, Label *on_in_range) override
bool CheckCharacterNotInRangeArray (const ZoneList< CharacterRange > *ranges, Label *on_not_in_range) override
void CheckBitInTable (Handle< ByteArray > table, Label *on_bit_set) override
void SkipUntilBitInTable (int cp_offset, Handle< ByteArray > table, Handle< ByteArray > nibble_table, int advance_by) override
void CheckNotBackReference (int start_reg, bool read_backward, Label *on_no_match) override
void CheckNotBackReferenceIgnoreCase (int start_reg, bool read_backward, bool unicode, Label *on_no_match) override
void IfRegisterLT (int register_index, int comparand, Label *if_lt) override
void IfRegisterGE (int register_index, int comparand, Label *if_ge) override
void IfRegisterEqPos (int register_index, Label *if_eq) override
IrregexpImplementation Implementation () override
DirectHandle< HeapObject > GetCode (DirectHandle< String > source, RegExpFlags flags) override
Private Member Functions
void ExpandBuffer ()
void EmitOrLink (Label *label)
void Emit32 (uint32_t x)
void Emit16 (uint32_t x)
void Emit8 (uint32_t x)
void Emit (uint32_t bc, uint32_t arg)
void Emit (uint32_t bc, int32_t arg)
void EmitSkipTable (DirectHandle< ByteArray > table)
int length ()
void Copy (uint8_t *a)
DISALLOW_IMPLICIT_CONSTRUCTORS (RegExpBytecodeGenerator)
Private Attributes
ZoneVector< uint8_t > buffer_
int pc_
Label backtrack_
int advance_current_start_
int advance_current_offset_
int advance_current_end_
ZoneUnorderedMap< int, int > jump_edges_
Isolate * isolate_
Static Private Attributes
static constexpr int kInitialBufferSize = 1024
static const int kInvalidPC = -1
Additional Inherited Members
Detailed Description
Definition at line 16 of file regexp-bytecode-generator.h.
Constructor & Destructor Documentation
RegExpBytecodeGenerator()
v8::internal::RegExpBytecodeGenerator::RegExpBytecodeGenerator (Isolate * isolate, Zone * zone)
Definition at line 17 of file regexp-bytecode-generator.cc.
    : RegExpMacroAssembler(isolate, zone),
      buffer_(kInitialBufferSize, zone),
      pc_(0),
      advance_current_end_(kInvalidPC),
      jump_edges_(zone),
      isolate_(isolate) {}
 RegExpBytecodeGenerator()
v8::internal::RegExpBytecodeGenerator::~RegExpBytecodeGenerator () [override]
Definition at line 25 of file regexp-bytecode-generator.cc.
                                                  {
  if (backtrack_.is_linked()) backtrack_.Unuse();
}
References backtrack_, v8::internal::Label::is_linked(), and v8::internal::Label::Unuse().
Member Function Documentation
AdvanceCurrentPosition()
void v8::internal::RegExpBytecodeGenerator::AdvanceCurrentPosition (int by) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 166 of file regexp-bytecode-generator.cc.
                                                           {
  // TODO(chromium:1166138): Turn back into DCHECKs once the underlying issue
  // is fixed.
  CHECK_LE(kMinCPOffset, by);
  CHECK_GE(kMaxCPOffset, by);
  advance_current_start_ = pc_;
  advance_current_offset_ = by;
  Emit(BC_ADVANCE_CP, by);
  advance_current_end_ = pc_;
}
References advance_current_end_, advance_current_offset_, advance_current_start_, CHECK_GE, CHECK_LE, Emit(), v8::internal::RegExpMacroAssembler::kMaxCPOffset, v8::internal::RegExpMacroAssembler::kMinCPOffset, and pc_.
AdvanceRegister()
void v8::internal::RegExpBytecodeGenerator::AdvanceRegister (int reg, int by) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 123 of file regexp-bytecode-generator.cc.
                                                                        {
  DCHECK_LE(0, register_index);
  DCHECK_GE(kMaxRegister, register_index);
  Emit(BC_ADVANCE_REGISTER, register_index);
  Emit32(by);
}
References DCHECK_GE, DCHECK_LE, Emit(), Emit32(), and v8::internal::RegExpMacroAssembler::kMaxRegister.
Backtrack()
void v8::internal::RegExpBytecodeGenerator::Backtrack () [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 134 of file regexp-bytecode-generator.cc.
                                        {
  int error_code =
      can_fallback() ? RegExp::RE_FALLBACK_TO_EXPERIMENTAL : RegExp::RE_FAILURE;
  Emit(BC_POP_BT, error_code);
}
References v8::internal::RegExpMacroAssembler::can_fallback(), Emit(), v8::internal::RegExp::RE_FAILURE, and v8::internal::RegExp::RE_FALLBACK_TO_EXPERIMENTAL.
Referenced by GetCode().
Bind()
void v8::internal::RegExpBytecodeGenerator::Bind (Label * label) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 34 of file regexp-bytecode-generator.cc.
                                           {
  advance_current_end_ = kInvalidPC;
  DCHECK(!l->is_bound());
  if (l->is_linked()) {
    int pos = l->pos();
    while (pos != 0) {
      int fixup = pos;
      pos = *reinterpret_cast<int32_t*>(buffer_.data() + fixup);
      *reinterpret_cast<uint32_t*>(buffer_.data() + fixup) = pc_;
      jump_edges_.emplace(fixup, pc_);
    }
  }
  l->bind_to(pc_);
}
References advance_current_end_, buffer_, v8::internal::ZoneVector< T >::data(), v8::internal::DCHECK(), jump_edges_, kInvalidPC, v8::internal::compiler::turboshaft::l, and pc_.
Referenced by GetCode(), and SkipUntilBitInTable().
CanReadUnaligned()
bool v8::internal::RegExpBytecodeGenerator::CanReadUnaligned () const [inline], [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 30 of file regexp-bytecode-generator.h.
{ return false; }
CheckAtStart()
void v8::internal::RegExpBytecodeGenerator::CheckAtStart (int cp_offset, Label * on_at_start) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 244 of file regexp-bytecode-generator.cc.
                                                                            {
  Emit(BC_CHECK_AT_START, cp_offset);
  EmitOrLink(on_at_start);
}
References Emit(), and EmitOrLink().
CheckBitInTable()
void v8::internal::RegExpBytecodeGenerator::CheckBitInTable (Handle< ByteArray > table, Label * on_bit_set) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 327 of file regexp-bytecode-generator.cc.
                                                                 {
  Emit(BC_CHECK_BIT_IN_TABLE, 0);
  EmitOrLink(on_bit_set);
  EmitSkipTable(table);
}
References Emit(), EmitOrLink(), and EmitSkipTable().
CheckCharacter()
void v8::internal::RegExpBytecodeGenerator::CheckCharacter (unsigned c, Label * on_equal) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 234 of file regexp-bytecode-generator.cc.
                                                                        {
  if (c > MAX_FIRST_ARG) {
    Emit(BC_CHECK_4_CHARS, 0);
    Emit32(c);
  } else {
    Emit(BC_CHECK_CHAR, c);
  }
  EmitOrLink(on_equal);
}
References Emit(), Emit32(), EmitOrLink(), and v8::internal::MAX_FIRST_ARG.
CheckCharacterAfterAnd()
void v8::internal::RegExpBytecodeGenerator::CheckCharacterAfterAnd (unsigned c, unsigned mask, Label * on_equal) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 266 of file regexp-bytecode-generator.cc.
                                                                      {
  if (c > MAX_FIRST_ARG) {
    Emit(BC_AND_CHECK_4_CHARS, 0);
    Emit32(c);
  } else {
    Emit(BC_AND_CHECK_CHAR, c);
  }
  Emit32(mask);
  EmitOrLink(on_equal);
}
References Emit(), Emit32(), EmitOrLink(), and v8::internal::MAX_FIRST_ARG.
CheckCharacterGT()
void v8::internal::RegExpBytecodeGenerator::CheckCharacterGT (base::uc16 limit, Label * on_greater) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 228 of file regexp-bytecode-generator.cc.
                                                                  {
  Emit(BC_CHECK_GT, limit);
  EmitOrLink(on_greater);
}
References Emit(), and EmitOrLink().
CheckCharacterInRange()
void v8::internal::RegExpBytecodeGenerator::CheckCharacterInRange (base::uc16 from, base::uc16 to, Label * on_in_range) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 299 of file regexp-bytecode-generator.cc.
                                                                        {
  Emit(BC_CHECK_CHAR_IN_RANGE, 0);
  Emit16(from);
  Emit16(to);
  EmitOrLink(on_in_range);
}
References Emit(), Emit16(), and EmitOrLink().
CheckCharacterInRangeArray()
bool v8::internal::RegExpBytecodeGenerator::CheckCharacterInRangeArray (const ZoneList< CharacterRange > * ranges, Label * on_in_range) [inline], [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 72 of file regexp-bytecode-generator.h.
                                                               {
    // Disabled in the interpreter, because 1) there is no constant pool that
    // could store the ByteArray pointer, 2) bytecode size limits are not as
    // restrictive as code (e.g. branch distances on arm), 3) bytecode for
    // large character classes is already quite compact.
    // TODO(jgruber): Consider using BytecodeArrays (with a constant pool)
    // instead of plain ByteArrays; then we could implement
    // CheckCharacterInRangeArray in the interpreter.
    return false;
  }
CheckCharacterLT()
void v8::internal::RegExpBytecodeGenerator::CheckCharacterLT (base::uc16 limit, Label * on_less) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 222 of file regexp-bytecode-generator.cc.
                                                               {
  Emit(BC_CHECK_LT, limit);
  EmitOrLink(on_less);
}
References Emit(), and EmitOrLink().
CheckCharacterNotInRange()
void v8::internal::RegExpBytecodeGenerator::CheckCharacterNotInRange (base::uc16 from, base::uc16 to, Label * on_not_in_range) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 308 of file regexp-bytecode-generator.cc.
                                                                               {
  Emit(BC_CHECK_CHAR_NOT_IN_RANGE, 0);
  Emit16(from);
  Emit16(to);
  EmitOrLink(on_not_in_range);
}
References Emit(), Emit16(), and EmitOrLink().
CheckCharacterNotInRangeArray()
bool v8::internal::RegExpBytecodeGenerator::CheckCharacterNotInRangeArray (const ZoneList< CharacterRange > * ranges, Label * on_not_in_range) [inline], [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 83 of file regexp-bytecode-generator.h.
                                                                      {
    return false;
  }
CheckFixedLengthLoop()
void v8::internal::RegExpBytecodeGenerator::CheckFixedLengthLoop (Label * on_tos_equals_current_position) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 177 of file regexp-bytecode-generator.cc.
                                           {
  Emit(BC_CHECK_FIXED_LENGTH, 0);
  EmitOrLink(on_tos_equals_current_position);
}
References Emit(), and EmitOrLink().
CheckNotAtStart()
void v8::internal::RegExpBytecodeGenerator::CheckNotAtStart (int cp_offset, Label * on_not_at_start) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 249 of file regexp-bytecode-generator.cc.
                                                                      {
  Emit(BC_CHECK_NOT_AT_START, cp_offset);
  EmitOrLink(on_not_at_start);
}
References Emit(), and EmitOrLink().
CheckNotBackReference()
void v8::internal::RegExpBytecodeGenerator::CheckNotBackReference (int start_reg, bool read_backward, Label * on_no_match) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 346 of file regexp-bytecode-generator.cc.
                                                                         {
  DCHECK_LE(0, start_reg);
  DCHECK_GE(kMaxRegister, start_reg);
  Emit(read_backward ? BC_CHECK_NOT_BACK_REF_BACKWARD : BC_CHECK_NOT_BACK_REF,
       start_reg);
  EmitOrLink(on_not_equal);
}
References DCHECK_GE, DCHECK_LE, Emit(), EmitOrLink(), and v8::internal::RegExpMacroAssembler::kMaxRegister.
CheckNotBackReferenceIgnoreCase()
void v8::internal::RegExpBytecodeGenerator::CheckNotBackReferenceIgnoreCase (int start_reg, bool read_backward, bool unicode, Label * on_no_match) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 356 of file regexp-bytecode-generator.cc.
                                                                          {
  DCHECK_LE(0, start_reg);
  DCHECK_GE(kMaxRegister, start_reg);
  Emit(read_backward ? (unicode ? BC_CHECK_NOT_BACK_REF_NO_CASE_UNICODE_BACKWARD
                                : BC_CHECK_NOT_BACK_REF_NO_CASE_BACKWARD)
                     : (unicode ? BC_CHECK_NOT_BACK_REF_NO_CASE_UNICODE
                                : BC_CHECK_NOT_BACK_REF_NO_CASE),
       start_reg);
  EmitOrLink(on_not_equal);
}
References DCHECK_GE, DCHECK_LE, Emit(), EmitOrLink(), and v8::internal::RegExpMacroAssembler::kMaxRegister.
CheckNotCharacter()
void v8::internal::RegExpBytecodeGenerator::CheckNotCharacter (unsigned c, Label * on_not_equal) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 255 of file regexp-bytecode-generator.cc.
                                                                     {
  if (c > MAX_FIRST_ARG) {
    Emit(BC_CHECK_NOT_4_CHARS, 0);
    Emit32(c);
  } else {
    Emit(BC_CHECK_NOT_CHAR, c);
  }
  EmitOrLink(on_not_equal);
}
References Emit(), Emit32(), EmitOrLink(), and v8::internal::MAX_FIRST_ARG.
CheckNotCharacterAfterAnd()
void v8::internal::RegExpBytecodeGenerator::CheckNotCharacterAfterAnd (unsigned c, unsigned mask, Label * on_not_equal) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 278 of file regexp-bytecode-generator.cc.
                                                                             {
  if (c > MAX_FIRST_ARG) {
    Emit(BC_AND_CHECK_NOT_4_CHARS, 0);
    Emit32(c);
  } else {
    Emit(BC_AND_CHECK_NOT_CHAR, c);
  }
  Emit32(mask);
  EmitOrLink(on_not_equal);
}
References Emit(), Emit32(), EmitOrLink(), and v8::internal::MAX_FIRST_ARG.
CheckNotCharacterAfterMinusAnd()
void v8::internal::RegExpBytecodeGenerator::CheckNotCharacterAfterMinusAnd (base::uc16 c, base::uc16 minus, base::uc16 mask, Label * on_not_equal) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 291 of file regexp-bytecode-generator.cc.
                                                                    {
  Emit(BC_MINUS_AND_CHECK_NOT_CHAR, c);
  Emit16(minus);
  Emit16(mask);
  EmitOrLink(on_not_equal);
}
References Emit(), Emit16(), and EmitOrLink().
ClearRegisters()
void v8::internal::RegExpBytecodeGenerator::ClearRegisters (int reg_from, int reg_to) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 85 of file regexp-bytecode-generator.cc.
                                                                     {
  DCHECK(reg_from <= reg_to);
  for (int reg = reg_from; reg <= reg_to; reg++) {
    SetRegister(reg, -1);
  }
}
References v8::internal::DCHECK(), and SetRegister().
Copy()
void v8::internal::RegExpBytecodeGenerator::Copy (uint8_t * a) [private]
Definition at line 413 of file regexp-bytecode-generator.cc.
                                             {
  MemCopy(a, buffer_.data(), length());
}
References buffer_, v8::internal::ZoneVector< T >::data(), length(), and v8::internal::MemCopy().
Referenced by GetCode().
DISALLOW_IMPLICIT_CONSTRUCTORS()
v8::internal::RegExpBytecodeGenerator::DISALLOW_IMPLICIT_CONSTRUCTORS (RegExpBytecodeGenerator) [private]
Emit() [1/2]
void v8::internal::RegExpBytecodeGenerator::Emit (uint32_t bc, int32_t arg) [inline], [private]
Definition at line 21 of file regexp-bytecode-generator-inl.h.
                                                                          {
  DCHECK(is_int24(twenty_four_bits));
  Emit32((static_cast<uint32_t>(twenty_four_bits) << BYTECODE_SHIFT) | byte);
}
References v8::internal::BYTECODE_SHIFT, v8::internal::DCHECK(), and Emit32().
Emit() [2/2]
void v8::internal::RegExpBytecodeGenerator::Emit (uint32_t bc, uint32_t arg) [inline], [private]
Definition at line 16 of file regexp-bytecode-generator-inl.h.
                                                                           {
  DCHECK(is_uint24(twenty_four_bits));
  Emit32((twenty_four_bits << BYTECODE_SHIFT) | byte);
}
References v8::internal::BYTECODE_SHIFT, v8::internal::DCHECK(), and Emit32().
Referenced by AdvanceCurrentPosition(), AdvanceRegister(), Backtrack(), CheckAtStart(), CheckBitInTable(), CheckCharacter(), CheckCharacterAfterAnd(), CheckCharacterGT(), CheckCharacterInRange(), CheckCharacterLT(), CheckCharacterNotInRange(), CheckFixedLengthLoop(), CheckNotAtStart(), CheckNotBackReference(), CheckNotBackReferenceIgnoreCase(), CheckNotCharacter(), CheckNotCharacterAfterAnd(), CheckNotCharacterAfterMinusAnd(), Fail(), GoTo(), IfRegisterEqPos(), IfRegisterGE(), IfRegisterLT(), LoadCurrentCharacterImpl(), PopCurrentPosition(), PopRegister(), PushBacktrack(), PushCurrentPosition(), PushRegister(), ReadCurrentPositionFromRegister(), ReadStackPointerFromRegister(), SetCurrentPositionFromEnd(), SetRegister(), SkipUntilBitInTable(), Succeed(), WriteCurrentPositionToRegister(), and WriteStackPointerToRegister().
Emit16()
void v8::internal::RegExpBytecodeGenerator::Emit16 (uint32_t x) [inline], [private]
Definition at line 26 of file regexp-bytecode-generator-inl.h.
                                                  {
  DCHECK(pc_ <= static_cast<int>(buffer_.size()));
  if (pc_ + 1 >= static_cast<int>(buffer_.size())) {
    ExpandBuffer();
  }
  *reinterpret_cast<uint16_t*>(buffer_.data() + pc_) = word;
  pc_ += 2;
}
References buffer_, v8::internal::ZoneVector< T >::data(), v8::internal::DCHECK(), ExpandBuffer(), pc_, and v8::internal::ZoneVector< T >::size().
Referenced by CheckCharacterInRange(), CheckCharacterNotInRange(), and CheckNotCharacterAfterMinusAnd().
Emit32()
void v8::internal::RegExpBytecodeGenerator::Emit32 (uint32_t x) [inline], [private]
Definition at line 44 of file regexp-bytecode-generator-inl.h.
                                                  {
  DCHECK(pc_ <= static_cast<int>(buffer_.size()));
  if (pc_ + 3 >= static_cast<int>(buffer_.size())) {
    ExpandBuffer();
  }
  *reinterpret_cast<uint32_t*>(buffer_.data() + pc_) = word;
  pc_ += 4;
}
References buffer_, v8::internal::ZoneVector< T >::data(), v8::internal::DCHECK(), ExpandBuffer(), pc_, and v8::internal::ZoneVector< T >::size().
Referenced by AdvanceRegister(), CheckCharacter(), CheckCharacterAfterAnd(), CheckNotCharacter(), CheckNotCharacterAfterAnd(), Emit(), EmitOrLink(), IfRegisterGE(), IfRegisterLT(), SetRegister(), SkipUntilBitInTable(), and WriteCurrentPositionToRegister().
Emit8()
void v8::internal::RegExpBytecodeGenerator::Emit8 (uint32_t x) [inline], [private]
Definition at line 35 of file regexp-bytecode-generator-inl.h.
                                                 {
  DCHECK(pc_ <= static_cast<int>(buffer_.size()));
  if (pc_ == static_cast<int>(buffer_.size())) {
    ExpandBuffer();
  }
  *reinterpret_cast<unsigned char*>(buffer_.data() + pc_) = word;
  pc_ += 1;
}
References buffer_, v8::internal::ZoneVector< T >::data(), v8::internal::DCHECK(), ExpandBuffer(), pc_, and v8::internal::ZoneVector< T >::size().
Referenced by EmitSkipTable().
EmitOrLink()
void v8::internal::RegExpBytecodeGenerator::EmitOrLink (Label * label) [inline], [private]
Definition at line 49 of file regexp-bytecode-generator.cc.
                                                 {
  if (l == nullptr) l = &backtrack_;
  int pos = 0;
  if (l->is_bound()) {
    pos = l->pos();
    jump_edges_.emplace(pc_, pos);
  } else {
    if (l->is_linked()) {
      pos = l->pos();
    }
    l->link_to(pc_);
  }
  Emit32(pos);
}
References backtrack_, Emit32(), jump_edges_, v8::internal::compiler::turboshaft::l, and pc_.
Referenced by CheckAtStart(), CheckBitInTable(), CheckCharacter(), CheckCharacterAfterAnd(), CheckCharacterGT(), CheckCharacterInRange(), CheckCharacterLT(), CheckCharacterNotInRange(), CheckFixedLengthLoop(), CheckNotAtStart(), CheckNotBackReference(), CheckNotBackReferenceIgnoreCase(), CheckNotCharacter(), CheckNotCharacterAfterAnd(), CheckNotCharacterAfterMinusAnd(), GoTo(), IfRegisterEqPos(), IfRegisterGE(), IfRegisterLT(), LoadCurrentCharacterImpl(), PushBacktrack(), and SkipUntilBitInTable().
EmitSkipTable()
void v8::internal::RegExpBytecodeGenerator::EmitSkipTable (DirectHandle< ByteArray > table) [private]
Definition at line 317 of file regexp-bytecode-generator.cc.
                                                                         {
  for (int i = 0; i < kTableSize; i += kBitsPerByte) {
    int byte = 0;
    for (int j = 0; j < kBitsPerByte; j++) {
      if (table->get(i + j) != 0) byte |= 1 << j;
    }
    Emit8(byte);
  }
}
References Emit8(), v8::internal::kBitsPerByte, and v8::internal::RegExpMacroAssembler::kTableSize.
Referenced by CheckBitInTable(), and SkipUntilBitInTable().
ExpandBuffer()
void v8::internal::RegExpBytecodeGenerator::ExpandBuffer () [private]
Definition at line 417 of file regexp-bytecode-generator.cc.
                                           {
  // TODO(jgruber): The growth strategy could be smarter for large sizes.
  // TODO(jgruber): It's not necessary to default-initialize new elements.
  buffer_.resize(buffer_.size() * 2);
}
References buffer_, v8::internal::ZoneVector< T >::resize(), and v8::internal::ZoneVector< T >::size().
Referenced by Emit16(), Emit32(), and Emit8().
Fail()
void v8::internal::RegExpBytecodeGenerator::Fail () [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 164 of file regexp-bytecode-generator.cc.
{ Emit(BC_FAIL, 0); }
References Emit().
GetCode()
DirectHandle< HeapObject > v8::internal::RegExpBytecodeGenerator::GetCode (DirectHandle< String > source, RegExpFlags flags) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 394 of file regexp-bytecode-generator.cc.
                                                    {
  Bind(&backtrack_);
  Backtrack();
  DirectHandle<TrustedByteArray> array;
  if (v8_flags.regexp_peephole_optimization) {
    array = RegExpBytecodePeepholeOptimization::OptimizeBytecode(
        isolate_, zone(), source, buffer_.data(), length(), jump_edges_);
  } else {
    array = isolate_->factory()->NewTrustedByteArray(length());
    Copy(array->begin());
  }
  return array;
}
References Backtrack(), backtrack_, Bind(), buffer_, Copy(), v8::internal::ZoneVector< T >::data(), v8::internal::Isolate::factory(), isolate_, jump_edges_, length(), v8::internal::FactoryBase< Impl >::NewTrustedByteArray(), v8::internal::RegExpBytecodePeepholeOptimization::OptimizeBytecode(), v8::internal::v8_flags, and v8::internal::RegExpMacroAssembler::zone().
GoTo()
void v8::internal::RegExpBytecodeGenerator::GoTo (Label * label) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 140 of file regexp-bytecode-generator.cc.
                                           {
  if (advance_current_end_ == pc_) {
    // Combine advance current and goto.
    pc_ = advance_current_start_;
    Emit(BC_ADVANCE_CP_AND_GOTO, advance_current_offset_);
    EmitOrLink(l);
    advance_current_end_ = kInvalidPC;
  } else {
    // Regular goto.
    Emit(BC_GOTO, 0);
    EmitOrLink(l);
  }
}
References advance_current_end_, advance_current_offset_, advance_current_start_, Emit(), EmitOrLink(), kInvalidPC, v8::internal::compiler::turboshaft::l, and pc_.
IfRegisterEqPos()
void v8::internal::RegExpBytecodeGenerator::IfRegisterEqPos (int register_index, Label * if_eq) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 386 of file regexp-bytecode-generator.cc.
                                                            {
  DCHECK_LE(0, register_index);
  DCHECK_GE(kMaxRegister, register_index);
  Emit(BC_CHECK_REGISTER_EQ_POS, register_index);
  EmitOrLink(on_eq);
}
References DCHECK_GE, DCHECK_LE, Emit(), EmitOrLink(), and v8::internal::RegExpMacroAssembler::kMaxRegister.
IfRegisterGE()
void v8::internal::RegExpBytecodeGenerator::IfRegisterGE (int register_index, int comparand, Label * if_ge) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 377 of file regexp-bytecode-generator.cc.
                                                                       {
  DCHECK_LE(0, register_index);
  DCHECK_GE(kMaxRegister, register_index);
  Emit(BC_CHECK_REGISTER_GE, register_index);
  Emit32(comparand);
  EmitOrLink(on_greater_or_equal);
}
References DCHECK_GE, DCHECK_LE, Emit(), Emit32(), EmitOrLink(), and v8::internal::RegExpMacroAssembler::kMaxRegister.
IfRegisterLT()
void v8::internal::RegExpBytecodeGenerator::IfRegisterLT (int register_index, int comparand, Label * if_lt) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 368 of file regexp-bytecode-generator.cc.
                                                                {
  DCHECK_LE(0, register_index);
  DCHECK_GE(kMaxRegister, register_index);
  Emit(BC_CHECK_REGISTER_LT, register_index);
  Emit32(comparand);
  EmitOrLink(on_less_than);
}
References DCHECK_GE, DCHECK_LE, Emit(), Emit32(), EmitOrLink(), and v8::internal::RegExpMacroAssembler::kMaxRegister.
Implementation()
RegExpBytecodeGenerator::IrregexpImplementation v8::internal::RegExpBytecodeGenerator::Implementation () [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 30 of file regexp-bytecode-generator.cc.
                                        {
  return kBytecodeImplementation;
}
length()
int v8::internal::RegExpBytecodeGenerator::length () [private]
Definition at line 411 of file regexp-bytecode-generator.cc.
{ return pc_; }
References pc_.
Referenced by Copy(), and GetCode().
LoadCurrentCharacterImpl()
void v8::internal::RegExpBytecodeGenerator::LoadCurrentCharacterImpl (int cp_offset, Label * on_end_of_input, bool check_bounds, int characters, int eats_at_least) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 183 of file regexp-bytecode-generator.cc.
                                                                          {
  DCHECK_GE(eats_at_least, characters);
  if (eats_at_least > characters && check_bounds) {
    DCHECK(is_int24(cp_offset + eats_at_least));
    Emit(BC_CHECK_CURRENT_POSITION, cp_offset + eats_at_least);
    EmitOrLink(on_failure);
    check_bounds = false; // Load below doesn't need to check.
  }
  DCHECK_LE(kMinCPOffset, cp_offset);
  DCHECK_GE(kMaxCPOffset, cp_offset);
  int bytecode;
  if (check_bounds) {
    if (characters == 4) {
      bytecode = BC_LOAD_4_CURRENT_CHARS;
    } else if (characters == 2) {
      bytecode = BC_LOAD_2_CURRENT_CHARS;
    } else {
      DCHECK_EQ(1, characters);
      bytecode = BC_LOAD_CURRENT_CHAR;
    }
  } else {
    if (characters == 4) {
      bytecode = BC_LOAD_4_CURRENT_CHARS_UNCHECKED;
    } else if (characters == 2) {
      bytecode = BC_LOAD_2_CURRENT_CHARS_UNCHECKED;
    } else {
      DCHECK_EQ(1, characters);
      bytecode = BC_LOAD_CURRENT_CHAR_UNCHECKED;
    }
  }
  Emit(bytecode, cp_offset);
  if (check_bounds) EmitOrLink(on_failure);
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, DCHECK_LE, Emit(), EmitOrLink(), v8::internal::RegExpMacroAssembler::kMaxCPOffset, and v8::internal::RegExpMacroAssembler::kMinCPOffset.
PopCurrentPosition()
void v8::internal::RegExpBytecodeGenerator::PopCurrentPosition () [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 130 of file regexp-bytecode-generator.cc.
{ Emit(BC_POP_CP, 0); }
References Emit().
PopRegister()
void v8::internal::RegExpBytecodeGenerator::PopRegister (int register_index) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 64 of file regexp-bytecode-generator.cc.
                                                            {
  DCHECK_LE(0, register_index);
  DCHECK_GE(kMaxRegister, register_index);
  Emit(BC_POP_REGISTER, register_index);
}
References DCHECK_GE, DCHECK_LE, Emit(), and v8::internal::RegExpMacroAssembler::kMaxRegister.
PushBacktrack()
void v8::internal::RegExpBytecodeGenerator::PushBacktrack (Label * label) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 154 of file regexp-bytecode-generator.cc.
                                                    {
  Emit(BC_PUSH_BT, 0);
  EmitOrLink(l);
}
References Emit(), EmitOrLink(), and v8::internal::compiler::turboshaft::l.
PushCurrentPosition()
void v8::internal::RegExpBytecodeGenerator::PushCurrentPosition () [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 132 of file regexp-bytecode-generator.cc.
{ Emit(BC_PUSH_CP, 0); }
References Emit().
PushRegister()
void v8::internal::RegExpBytecodeGenerator::PushRegister (int register_index, StackCheckFlag check_stack_limit) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 70 of file regexp-bytecode-generator.cc.
                                                                             {
  DCHECK_LE(0, register_index);
  DCHECK_GE(kMaxRegister, register_index);
  Emit(BC_PUSH_REGISTER, register_index);
}
References DCHECK_GE, DCHECK_LE, Emit(), and v8::internal::RegExpMacroAssembler::kMaxRegister.
ReadCurrentPositionFromRegister()
void v8::internal::RegExpBytecodeGenerator::ReadCurrentPositionFromRegister (int reg) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 92 of file regexp-bytecode-generator.cc.
                        {
  DCHECK_LE(0, register_index);
  DCHECK_GE(kMaxRegister, register_index);
  Emit(BC_SET_CP_TO_REGISTER, register_index);
}
References DCHECK_GE, DCHECK_LE, Emit(), and v8::internal::RegExpMacroAssembler::kMaxRegister.
ReadStackPointerFromRegister()
void v8::internal::RegExpBytecodeGenerator::ReadStackPointerFromRegister (int reg) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 105 of file regexp-bytecode-generator.cc.
                                                                             {
  DCHECK_LE(0, register_index);
  DCHECK_GE(kMaxRegister, register_index);
  Emit(BC_SET_SP_TO_REGISTER, register_index);
}
References DCHECK_GE, DCHECK_LE, Emit(), and v8::internal::RegExpMacroAssembler::kMaxRegister.
SetCurrentPositionFromEnd()
void v8::internal::RegExpBytecodeGenerator::SetCurrentPositionFromEnd (int by) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 111 of file regexp-bytecode-generator.cc.
                                                              {
  DCHECK(is_uint24(by));
  Emit(BC_SET_CURRENT_POSITION_FROM_END, by);
}
References v8::internal::DCHECK(), and Emit().
SetRegister()
void v8::internal::RegExpBytecodeGenerator::SetRegister (int register_index, int to) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 116 of file regexp-bytecode-generator.cc.
                                                                    {
  DCHECK_LE(0, register_index);
  DCHECK_GE(kMaxRegister, register_index);
  Emit(BC_SET_REGISTER, register_index);
  Emit32(to);
}
References DCHECK_GE, DCHECK_LE, Emit(), Emit32(), and v8::internal::RegExpMacroAssembler::kMaxRegister.
Referenced by ClearRegisters().
SkipUntilBitInTable()
void v8::internal::RegExpBytecodeGenerator::SkipUntilBitInTable (int cp_offset, Handle< ByteArray > table, Handle< ByteArray > nibble_table, int advance_by) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 334 of file regexp-bytecode-generator.cc.
                    {
  Label cont;
  Emit(BC_SKIP_UNTIL_BIT_IN_TABLE, cp_offset);
  Emit32(advance_by);
  EmitSkipTable(table);
  EmitOrLink(&cont); // goto_when_match
  EmitOrLink(&cont); // goto_on_failure
  Bind(&cont);
}
References Bind(), Emit(), Emit32(), EmitOrLink(), and EmitSkipTable().
stack_limit_slack_slot_count()
int v8::internal::RegExpBytecodeGenerator::stack_limit_slack_slot_count () [inline], [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 29 of file regexp-bytecode-generator.h.
{ return 1; }
Succeed()
bool v8::internal::RegExpBytecodeGenerator::Succeed () [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 159 of file regexp-bytecode-generator.cc.
                                      {
  Emit(BC_SUCCEED, 0);
  return false; // Restart matching for global regexp not supported.
}
References Emit().
WriteCurrentPositionToRegister()
void v8::internal::RegExpBytecodeGenerator::WriteCurrentPositionToRegister (int reg, int cp_offset) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 77 of file regexp-bytecode-generator.cc.
                                                                            {
  DCHECK_LE(0, register_index);
  DCHECK_GE(kMaxRegister, register_index);
  Emit(BC_SET_REGISTER_TO_CP, register_index);
  Emit32(cp_offset); // Current position offset.
}
References DCHECK_GE, DCHECK_LE, Emit(), Emit32(), and v8::internal::RegExpMacroAssembler::kMaxRegister.
WriteStackPointerToRegister()
void v8::internal::RegExpBytecodeGenerator::WriteStackPointerToRegister (int reg) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 99 of file regexp-bytecode-generator.cc.
                                                                            {
  DCHECK_LE(0, register_index);
  DCHECK_GE(kMaxRegister, register_index);
  Emit(BC_SET_REGISTER_TO_SP, register_index);
}
References DCHECK_GE, DCHECK_LE, Emit(), and v8::internal::RegExpMacroAssembler::kMaxRegister.
Member Data Documentation
advance_current_end_
int v8::internal::RegExpBytecodeGenerator::advance_current_end_ [private]
Definition at line 129 of file regexp-bytecode-generator.h.
Referenced by AdvanceCurrentPosition(), Bind(), and GoTo().
advance_current_offset_
int v8::internal::RegExpBytecodeGenerator::advance_current_offset_ [private]
Definition at line 128 of file regexp-bytecode-generator.h.
Referenced by AdvanceCurrentPosition(), and GoTo().
advance_current_start_
int v8::internal::RegExpBytecodeGenerator::advance_current_start_ [private]
Definition at line 127 of file regexp-bytecode-generator.h.
Referenced by AdvanceCurrentPosition(), and GoTo().
backtrack_
Label v8::internal::RegExpBytecodeGenerator::backtrack_ [private]
Definition at line 125 of file regexp-bytecode-generator.h.
Referenced by EmitOrLink(), GetCode(), and ~RegExpBytecodeGenerator().
buffer_
ZoneVector<uint8_t> v8::internal::RegExpBytecodeGenerator::buffer_ [private]
Definition at line 121 of file regexp-bytecode-generator.h.
Referenced by Bind(), Copy(), Emit16(), Emit32(), Emit8(), ExpandBuffer(), and GetCode().
isolate_
Isolate* v8::internal::RegExpBytecodeGenerator::isolate_ [private]
Definition at line 137 of file regexp-bytecode-generator.h.
Referenced by GetCode().
jump_edges_
ZoneUnorderedMap<int, int> v8::internal::RegExpBytecodeGenerator::jump_edges_ [private]
Definition at line 135 of file regexp-bytecode-generator.h.
Referenced by Bind(), EmitOrLink(), and GetCode().
kInitialBufferSize
constexpr int v8::internal::RegExpBytecodeGenerator::kInitialBufferSize = 1024 [static], [constexpr], [private]
Definition at line 120 of file regexp-bytecode-generator.h.
kInvalidPC
const int v8::internal::RegExpBytecodeGenerator::kInvalidPC = -1 [static], [private]
Definition at line 139 of file regexp-bytecode-generator.h.
Referenced by Bind(), and GoTo().
pc_
int v8::internal::RegExpBytecodeGenerator::pc_ [private]
Definition at line 124 of file regexp-bytecode-generator.h.
Referenced by AdvanceCurrentPosition(), Bind(), Emit16(), Emit32(), Emit8(), EmitOrLink(), GoTo(), and length().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-bytecode-generator.h
/mnt/V8SourceCode/src/regexp/regexp-bytecode-generator-inl.h
/mnt/V8SourceCode/src/regexp/regexp-bytecode-generator.cc