v8::internal::torque::BuildFlags Class Reference
Public Member Functions
BuildFlags ()
Static Public Member Functions
static bool GetFlag (const std::string &name, const char *production)
Private Attributes
std::unordered_map< std::string, bool > build_flags_
Additional Inherited Members
Detailed Description
Definition at line 46 of file torque-parser.cc.
Constructor & Destructor Documentation
BuildFlags()
v8::internal::torque::BuildFlags::BuildFlags () [inline]
Definition at line 48 of file torque-parser.cc.
               {
    build_flags_["V8_EXTERNAL_CODE_SPACE"] = V8_EXTERNAL_CODE_SPACE_BOOL;
    build_flags_["TAGGED_SIZE_8_BYTES"] = TargetArchitecture::TaggedSize() == 8;
    build_flags_["V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE"] =
        V8_EXPERIMENTAL_UNDEFINED_DOUBLE_BOOL;
#ifdef V8_INTL_SUPPORT
    build_flags_["V8_INTL_SUPPORT"] = true;
#else
    build_flags_["V8_INTL_SUPPORT"] = false;
#endif
    build_flags_["V8_ENABLE_SWISS_NAME_DICTIONARY"] =
        V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL;
#ifdef V8_ENABLE_JAVASCRIPT_PROMISE_HOOKS
    build_flags_["V8_ENABLE_JAVASCRIPT_PROMISE_HOOKS"] = true;
#else
    build_flags_["V8_ENABLE_JAVASCRIPT_PROMISE_HOOKS"] = false;
#endif
#ifdef V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
    build_flags_["V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA"] = true;
#else
    build_flags_["V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA"] = false;
#endif
    build_flags_["TRUE_FOR_TESTING"] = true;
    build_flags_["FALSE_FOR_TESTING"] = false;
#ifdef V8_SCRIPTORMODULE_LEGACY_LIFETIME
    build_flags_["V8_SCRIPTORMODULE_LEGACY_LIFETIME"] = true;
#else
    build_flags_["V8_SCRIPTORMODULE_LEGACY_LIFETIME"] = false;
#endif
#ifdef V8_ENABLE_WEBASSEMBLY
    build_flags_["V8_ENABLE_WEBASSEMBLY"] = true;
    build_flags_["WASM_CODE_POINTER_NEEDS_PADDING"] =
        TargetArchitecture::TaggedSize() == 8;
#else
    build_flags_["V8_ENABLE_WEBASSEMBLY"] = false;
#endif
    build_flags_["V8_ENABLE_SANDBOX"] = V8_ENABLE_SANDBOX_BOOL;
    build_flags_["V8_ENABLE_LEAPTIERING"] = V8_ENABLE_LEAPTIERING_BOOL;
    build_flags_["V8_ENABLE_LEAPTIERING_TAGGED_SIZE_8_BYTES"] =
        V8_ENABLE_LEAPTIERING_BOOL && build_flags_["TAGGED_SIZE_8_BYTES"];
    build_flags_["DEBUG"] = DEBUG_BOOL;
#ifdef V8_ENABLE_DRUMBRAKE
    build_flags_["V8_ENABLE_DRUMBRAKE"] = true;
#else
    build_flags_["V8_ENABLE_DRUMBRAKE"] = false;
#endif
  }
References build_flags_, DEBUG_BOOL, v8::internal::torque::TargetArchitecture::TaggedSize(), V8_ENABLE_LEAPTIERING_BOOL, V8_ENABLE_SANDBOX_BOOL, V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL, V8_EXPERIMENTAL_UNDEFINED_DOUBLE_BOOL, and V8_EXTERNAL_CODE_SPACE_BOOL.
Member Function Documentation
GetFlag()
static bool v8::internal::torque::BuildFlags::GetFlag (const std::string & name, const char * production) [inline], [static]
Definition at line 95 of file torque-parser.cc.
                                                                     {
    auto it = Get().build_flags_.find(name);
    if (it == Get().build_flags_.end()) {
      ReportError("Unknown flag used in ", production, ": ", name,
                  ". Please add it to the list in BuildFlags.");
    }
    return it->second;
  }
References build_flags_, v8::base::ContextualVariable< Derived, VarType >::Get(), v8::internal::name, and v8::internal::torque::ReportError().
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeTorqueBuiltinDeclaration(), and v8::internal::torque::anonymous_namespace{torque-parser.cc}::ProcessIfAnnotation().
Member Data Documentation
build_flags_
std::unordered_map<std::string, bool> v8::internal::torque::BuildFlags::build_flags_ [private]
Definition at line 105 of file torque-parser.cc.
Referenced by BuildFlags(), and GetFlag().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/torque-parser.cc