v8::internal::IterationStatement Class Reference
#include <ast.h>
Public Member Functions
Statement * body () const
void set_body (Statement *s)
Protected Member Functions
IterationStatement (int pos, NodeType type)
void Initialize (Statement *body)
Private Attributes
Statement * body_
Additional Inherited Members
Detailed Description
Definition at line 437 of file ast.h.
Constructor & Destructor Documentation
IterationStatement()
v8::internal::IterationStatement::IterationStatement (int pos, NodeType type) [inline], [protected]
Definition at line 443 of file ast.h.
      : BreakableStatement(pos, type), body_(nullptr) {}
Member Function Documentation
body()
Statement* v8::internal::IterationStatement::body () const [inline]
Definition at line 439 of file ast.h.
{ return body_; }
References body_.
Referenced by v8::internal::DoWhileStatement::Initialize(), v8::internal::WhileStatement::Initialize(), v8::internal::ForEachStatement::Initialize(), Initialize(), v8::internal::ForStatement::Initialize(), v8::internal::interpreter::BytecodeGenerator::VisitIterationBody(), and v8::internal::Processor::VisitIterationStatement().
Initialize()
void v8::internal::IterationStatement::Initialize (Statement * body) [inline], [protected]
Definition at line 445 of file ast.h.
{ body_ = body; }
References body(), and body_.
Referenced by v8::internal::DoWhileStatement::Initialize(), v8::internal::WhileStatement::Initialize(), v8::internal::ForEachStatement::Initialize(), and v8::internal::ForStatement::Initialize().
set_body()
void v8::internal::IterationStatement::set_body (Statement * s) [inline]
Definition at line 440 of file ast.h.
{ body_ = s; }
References body_.
Referenced by v8::internal::Processor::VisitIterationStatement().
Member Data Documentation
body_
Statement* v8::internal::IterationStatement::body_ [private]
Definition at line 448 of file ast.h.
Referenced by body(), Initialize(), and set_body().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ast/ast.h