v8::internal::Bootstrapper Class Reference
#include <bootstrapper.h>
Public Member Functions
Bootstrapper (const Bootstrapper &)=delete
Bootstrapper & operator= (const Bootstrapper &)=delete
void Initialize (bool create_heap_objects)
void TearDown ()
DirectHandle< NativeContext > CreateEnvironment (MaybeDirectHandle< JSGlobalProxy > maybe_global_proxy, v8::Local< v8::ObjectTemplate > global_object_template, v8::ExtensionConfiguration *extensions, size_t context_snapshot_index, DeserializeEmbedderFieldsCallback embedder_fields_deserializer, v8::MicrotaskQueue *microtask_queue)
DirectHandle< NativeContext > CreateEnvironmentForTesting ()
DirectHandle< JSGlobalProxy > NewRemoteContext (MaybeDirectHandle< JSGlobalProxy > maybe_global_proxy, v8::Local< v8::ObjectTemplate > global_object_template)
void Iterate (RootVisitor *v)
bool IsActive () const
char * ArchiveState (char *to)
char * RestoreState (char *from)
void FreeThreadResources ()
bool InstallExtensions (DirectHandle< NativeContext > native_context, v8::ExtensionConfiguration *extensions)
SourceCodeCache * extensions_cache ()
Static Public Member Functions
static void InitializeOncePerProcess ()
static int ArchiveSpacePerThread ()
Private Types
using NestingCounterType = int
Private Member Functions
void LogAllMaps ()
Bootstrapper (Isolate *isolate)
Private Attributes
Isolate * isolate_
NestingCounterType nesting_
SourceCodeCache extensions_cache_
Friends
class BootstrapperActive
class Isolate
class NativesExternalStringResource
Detailed Description
Definition at line 46 of file bootstrapper.h.
Member Typedef Documentation
NestingCounterType
using v8::internal::Bootstrapper::NestingCounterType = int [private]
Definition at line 107 of file bootstrapper.h.
Constructor & Destructor Documentation
Bootstrapper() [1/2]
v8::internal::Bootstrapper::Bootstrapper (const Bootstrapper &) [delete]
Bootstrapper() [2/2]
v8::internal::Bootstrapper::Bootstrapper (Isolate * isolate) [explicit], [private]
Definition at line 140 of file bootstrapper.cc.
    : isolate_(isolate),
      nesting_(0),
      extensions_cache_(Script::Type::kExtension) {}
Member Function Documentation
ArchiveSpacePerThread()
int v8::internal::Bootstrapper::ArchiveSpacePerThread () [static]
Definition at line 7128 of file bootstrapper.cc.
{ return sizeof(NestingCounterType); }
Referenced by v8::internal::ArchiveSpacePerThread().
ArchiveState()
char * v8::internal::Bootstrapper::ArchiveState (char * to)
Definition at line 7131 of file bootstrapper.cc.
                                         {
  *reinterpret_cast<NestingCounterType*>(to) = nesting_;
  nesting_ = 0;
  return to + sizeof(NestingCounterType);
}
References nesting_.
Referenced by v8::internal::ThreadManager::EagerlyArchiveThread().
CreateEnvironment()
DirectHandle< NativeContext > v8::internal::Bootstrapper::CreateEnvironment (MaybeDirectHandle< JSGlobalProxy > maybe_global_proxy, v8::Local< v8::ObjectTemplate > global_object_template, v8::ExtensionConfiguration * extensions, size_t context_snapshot_index, DeserializeEmbedderFieldsCallback embedder_fields_deserializer, v8::MicrotaskQueue * microtask_queue)
Definition at line 350 of file bootstrapper.cc.
                                       {
  HandleScope scope(isolate_);
  DirectHandle<NativeContext> env;
  {
    Genesis genesis(isolate_, maybe_global_proxy, global_proxy_template,
                    context_snapshot_index, embedder_fields_deserializer,
                    microtask_queue);
    env = genesis.result();
    if (env.is_null() || !InstallExtensions(env, extensions)) {
      return {};
    }
  }
  LogAllMaps();
  isolate_->heap()->NotifyBootstrapComplete();
  return scope.CloseAndEscape(env);
}
References v8::internal::Isolate::heap(), InstallExtensions(), v8::internal::DirectHandle< T >::is_null(), isolate_, LogAllMaps(), v8::internal::Heap::NotifyBootstrapComplete(), and v8::internal::Genesis::result().
Referenced by CreateEnvironmentForTesting(), and v8::InvokeBootstrapper< i::NativeContext >::Invoke().
CreateEnvironmentForTesting()
DirectHandle<NativeContext> v8::internal::Bootstrapper::CreateEnvironmentForTesting () [inline]
Definition at line 68 of file bootstrapper.h.
                                                            {
    MaybeDirectHandle<JSGlobalProxy> no_global_proxy;
    v8::Local<v8::ObjectTemplate> no_global_object_template;
    ExtensionConfiguration no_extensions;
    static constexpr int kDefaultContextIndex = 0;
    DeserializeEmbedderFieldsCallback no_callback;
    v8::MicrotaskQueue* no_microtask_queue = nullptr;
    return CreateEnvironment(no_global_proxy, no_global_object_template,
                             &no_extensions, kDefaultContextIndex, no_callback,
                             no_microtask_queue);
  }
References CreateEnvironment().
Referenced by v8::internal::Snapshot::SerializeDeserializeAndVerifyForTesting().
extensions_cache()
SourceCodeCache* v8::internal::Bootstrapper::extensions_cache () [inline]
Definition at line 100 of file bootstrapper.h.
{ return &extensions_cache_; }
References extensions_cache_.
Referenced by v8::internal::Genesis::CompileExtension().
FreeThreadResources()
void v8::internal::Bootstrapper::FreeThreadResources ()
Definition at line 7144 of file bootstrapper.cc.
{ DCHECK(!IsActive()); }
References v8::internal::DCHECK(), and IsActive().
Referenced by v8::internal::ThreadManager::FreeThreadResources().
Initialize()
void v8::internal::Bootstrapper::Initialize (bool create_heap_objects)
Definition at line 145 of file bootstrapper.cc.
                                                      {
  extensions_cache_.Initialize(isolate_, create_heap_objects);
}
References extensions_cache_, v8::internal::SourceCodeCache::Initialize(), and isolate_.
Referenced by v8::internal::Isolate::Init().
InitializeOncePerProcess()
void v8::internal::Bootstrapper::InitializeOncePerProcess () [static]
Definition at line 160 of file bootstrapper.cc.
                                            {
  v8::RegisterExtension(std::make_unique<GCExtension>(GCFunctionName()));
#ifdef V8_FUZZILLI
  v8::RegisterExtension(std::make_unique<FuzzilliExtension>("fuzzilli"));
#endif
  v8::RegisterExtension(std::make_unique<ExternalizeStringExtension>());
  v8::RegisterExtension(std::make_unique<StatisticsExtension>());
  v8::RegisterExtension(std::make_unique<TriggerFailureExtension>());
  v8::RegisterExtension(std::make_unique<IgnitionStatisticsExtension>());
  if (isValidCpuTraceMarkFunctionName()) {
    v8::RegisterExtension(std::make_unique<CpuTraceMarkExtension>(
        v8_flags.expose_cputracemark_as));
  }
#ifdef ENABLE_VTUNE_TRACEMARK
  v8::RegisterExtension(
      std::make_unique<VTuneDomainSupportExtension>("vtunedomainmark"));
#endif // ENABLE_VTUNE_TRACEMARK
}
References v8::internal::GCFunctionName(), v8::internal::isValidCpuTraceMarkFunctionName(), v8::RegisterExtension(), and v8::internal::v8_flags.
Referenced by v8::internal::V8::Initialize().
InstallExtensions()
bool v8::internal::Bootstrapper::InstallExtensions (DirectHandle< NativeContext > native_context, v8::ExtensionConfiguration * extensions)
Definition at line 6510 of file bootstrapper.cc.
                                                                           {
  // Don't install extensions into the snapshot.
  if (isolate_->serializer_enabled()) return true;
  BootstrapperActive active(this);
  v8::Context::Scope context_scope(Utils::ToLocal(native_context));
  return Genesis::InstallExtensions(isolate_, native_context, extensions) &&
         Genesis::InstallSpecialObjects(isolate_, native_context);
}
References v8::internal::Genesis::InstallExtensions(), v8::internal::Genesis::InstallSpecialObjects(), isolate_, v8::internal::native_context, and v8::internal::Isolate::serializer_enabled().
Referenced by CreateEnvironment().
IsActive()
bool v8::internal::Bootstrapper::IsActive () const [inline]
Definition at line 88 of file bootstrapper.h.
{ return nesting_ != 0; }
References nesting_.
Referenced by v8::internal::Map::CopyForPreventExtensions(), v8::internal::Map::CopyReplaceDescriptors(), FreeThreadResources(), v8::internal::interpreter::BytecodeGenerator::GenerateBytecode(), v8::internal::Debug::HandleDebugBreak(), v8::internal::LookupIterator::InternalUpdateProtector(), v8::internal::V8FileLogger::MapEvent(), v8::internal::JSObject::OptimizeAsPrototype(), v8::internal::JSFunction::RequestOptimization(), v8::internal::anonymous_namespace{js-function.cc}::SetInstancePrototype(), v8::internal::anonymous_namespace{property-descriptor.cc}::ToPropertyDescriptorFastPath(), v8::internal::Map::TransitionToAccessorProperty(), and v8::internal::Map::TransitionToDataProperty().
Iterate()
void v8::internal::Bootstrapper::Iterate (RootVisitor * v)
Definition at line 345 of file bootstrapper.cc.
                                         {
  extensions_cache_.Iterate(v);
  v->Synchronize(VisitorSynchronization::kExtensions);
}
References extensions_cache_, v8::internal::SourceCodeCache::Iterate(), and v8::internal::RootVisitor::Synchronize().
Referenced by v8::internal::Heap::IterateRoots().
LogAllMaps()
void v8::internal::Bootstrapper::LogAllMaps () [private]
Definition at line 386 of file bootstrapper.cc.
                              {
  if (!v8_flags.log_maps || isolate_->initialized_from_snapshot()) return;
  // Log all created Map objects that are on the heap. For snapshots the Map
  // logging happens during deserialization in order to avoid printing Maps
  // multiple times during partial deserialization.
  LOG(isolate_, LogAllMaps());
}
References v8::internal::Isolate::initialized_from_snapshot(), isolate_, LOG, and v8::internal::v8_flags.
Referenced by CreateEnvironment(), and NewRemoteContext().
NewRemoteContext()
DirectHandle< JSGlobalProxy > v8::internal::Bootstrapper::NewRemoteContext (MaybeDirectHandle< JSGlobalProxy > maybe_global_proxy, v8::Local< v8::ObjectTemplate > global_object_template)
Definition at line 372 of file bootstrapper.cc.
                                                     {
  HandleScope scope(isolate_);
  DirectHandle<JSGlobalProxy> global_proxy;
  {
    Genesis genesis(isolate_, maybe_global_proxy, global_proxy_template);
    global_proxy = genesis.global_proxy();
    if (global_proxy.is_null()) return {};
  }
  LogAllMaps();
  return scope.CloseAndEscape(global_proxy);
}
References v8::internal::Genesis::global_proxy(), v8::internal::DirectHandle< T >::is_null(), isolate_, and LogAllMaps().
Referenced by v8::InvokeBootstrapper< i::JSGlobalProxy >::Invoke().
operator=()
Bootstrapper& v8::internal::Bootstrapper::operator= (const Bootstrapper &) [delete]
RestoreState()
char * v8::internal::Bootstrapper::RestoreState (char * from)
Definition at line 7138 of file bootstrapper.cc.
                                           {
  nesting_ = *reinterpret_cast<NestingCounterType*>(from);
  return from + sizeof(NestingCounterType);
}
References nesting_.
Referenced by v8::internal::ThreadManager::RestoreThread().
TearDown()
void v8::internal::Bootstrapper::TearDown ()
Definition at line 179 of file bootstrapper.cc.
                            {
  extensions_cache_.Initialize(isolate_, false); // Yes, symmetrical
}
References extensions_cache_, v8::internal::SourceCodeCache::Initialize(), and isolate_.
Referenced by v8::internal::Isolate::Deinit().
Friends And Related Function Documentation
BootstrapperActive
friend class BootstrapperActive [friend]
Definition at line 111 of file bootstrapper.h.
Isolate
friend class Isolate [friend]
Definition at line 112 of file bootstrapper.h.
NativesExternalStringResource
friend class NativesExternalStringResource [friend]
Definition at line 113 of file bootstrapper.h.
Member Data Documentation
extensions_cache_
SourceCodeCache v8::internal::Bootstrapper::extensions_cache_ [private]
Definition at line 109 of file bootstrapper.h.
Referenced by extensions_cache(), Initialize(), Iterate(), and TearDown().
isolate_
Isolate* v8::internal::Bootstrapper::isolate_ [private]
Definition at line 106 of file bootstrapper.h.
Referenced by CreateEnvironment(), Initialize(), InstallExtensions(), LogAllMaps(), NewRemoteContext(), and TearDown().
nesting_
NestingCounterType v8::internal::Bootstrapper::nesting_ [private]
Definition at line 108 of file bootstrapper.h.
Referenced by ArchiveState(), v8::internal::BootstrapperActive::BootstrapperActive(), IsActive(), RestoreState(), and v8::internal::BootstrapperActive::~BootstrapperActive().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/init/bootstrapper.h
/mnt/V8SourceCode/src/init/bootstrapper.cc