v8::CpuProfile Class Reference
CpuProfile contains a CPU profile in a form of top-down call tree (from main() down to functions that do all the work).
#include <v8-profiler.h>
Public Types
enum SerializationFormat { kJSON = 0
 }
Public Member Functions
Local< String > GetTitle () const
Returns CPU profile title.
const CpuProfileNode * GetTopDownRoot () const
Returns the root node of the top down call tree.
int GetSamplesCount () const
Returns number of samples recorded.
const CpuProfileNode * GetSample (int index) const
Returns profile node corresponding to the top frame the sample at the given index.
int64_t GetSampleTimestamp (int index) const
Returns the timestamp of the sample.
int64_t GetStartTime () const
Returns time when the profile recording was started (in microseconds) since some unspecified starting point.
StateTag GetSampleState (int index) const
Returns state of the vm when sample was captured.
EmbedderStateTag GetSampleEmbedderState (int index) const
Returns state of the embedder when sample was captured.
int64_t GetEndTime () const
Returns time when the profile recording was stopped (in microseconds) since some unspecified starting point.
void Delete ()
Deletes the profile and removes it from CpuProfiler's list.
void Serialize (OutputStream *stream, SerializationFormat format=kJSON) const
Prepare a serialized representation of the profile.
Detailed Description
CpuProfile contains a CPU profile in a form of top-down call tree (from main() down to functions that do all the work).
Definition at line 214 of file v8-profiler.h.
Member Enumeration Documentation
SerializationFormat
enum v8::CpuProfile::SerializationFormat
Enumerator
kJSON
Definition at line 216 of file v8-profiler.h.
                           {
    kJSON = 0 // See format description near 'Serialize' method.
  };
Member Function Documentation
Delete()
void v8::CpuProfile::Delete ()
Deletes the profile and removes it from CpuProfiler's list.
All pointers to nodes previously returned become invalid.
Definition at line 11340 of file api.cc.
                        {
  i::CpuProfile* profile = reinterpret_cast<i::CpuProfile*>(this);
  i::CpuProfiler* profiler = profile->cpu_profiler();
  DCHECK_NOT_NULL(profiler);
  profiler->DeleteProfile(profile);
}
References v8::internal::CpuProfile::cpu_profiler(), DCHECK_NOT_NULL, and v8::internal::CpuProfiler::DeleteProfile().
Referenced by v8::Shell::Main(), v8::D8Console::ProfileEnd(), and v8_inspector::V8ProfilerAgentImpl::stopProfiling().
GetEndTime()
int64_t v8::CpuProfile::GetEndTime () const
Returns time when the profile recording was stopped (in microseconds) since some unspecified starting point.
The point is equal to the starting point used by GetStartTime.
Definition at line 11387 of file api.cc.
                                     {
  const i::CpuProfile* profile = reinterpret_cast<const i::CpuProfile*>(this);
  return profile->end_time().since_origin().InMicroseconds();
}
References v8::internal::CpuProfile::end_time(), v8::base::TimeDelta::InMicroseconds(), and v8::base::time_internal::TimeBase< TimeClass >::since_origin().
Referenced by v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::createCPUProfile().
GetSample()
const CpuProfileNode * v8::CpuProfile::GetSample (int index) const
Returns profile node corresponding to the top frame the sample at the given index.
Definition at line 11359 of file api.cc.
                                                           {
  const i::CpuProfile* profile = reinterpret_cast<const i::CpuProfile*>(this);
  return reinterpret_cast<const CpuProfileNode*>(profile->sample(index).node);
}
References v8::internal::index, v8::internal::CpuProfile::SampleInfo::node, and v8::internal::CpuProfile::sample().
Referenced by v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::buildInspectorObjectForSamples().
GetSampleEmbedderState()
EmbedderStateTag v8::CpuProfile::GetSampleEmbedderState (int index) const
Returns state of the embedder when sample was captured.
Definition at line 11377 of file api.cc.
                                                                   {
  const i::CpuProfile* profile = reinterpret_cast<const i::CpuProfile*>(this);
  return profile->sample(index).embedder_state_tag;
}
References v8::internal::CpuProfile::SampleInfo::embedder_state_tag, v8::internal::index, and v8::internal::CpuProfile::sample().
GetSamplesCount()
int v8::CpuProfile::GetSamplesCount () const
Returns number of samples recorded.
The samples are not recorded unless |record_samples| parameter of CpuProfiler::StartCpuProfiling is true.
Definition at line 11407 of file api.cc.
                                      {
  return reinterpret_cast<const i::CpuProfile*>(this)->samples_count();
}
Referenced by v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::buildInspectorObjectForSamples(), and v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::buildInspectorObjectForTimestamps().
GetSampleState()
StateTag v8::CpuProfile::GetSampleState (int index) const
Returns state of the vm when sample was captured.
Definition at line 11372 of file api.cc.
                                                   {
  const i::CpuProfile* profile = reinterpret_cast<const i::CpuProfile*>(this);
  return profile->sample(index).state_tag;
}
References v8::internal::index, v8::internal::CpuProfile::sample(), and v8::internal::CpuProfile::SampleInfo::state_tag.
GetSampleTimestamp()
int64_t v8::CpuProfile::GetSampleTimestamp (int index) const
Returns the timestamp of the sample.
The timestamp is the number of microseconds since some unspecified starting point. The point is equal to the starting point used by GetStartTime.
Definition at line 11367 of file api.cc.
                                                      {
  const i::CpuProfile* profile = reinterpret_cast<const i::CpuProfile*>(this);
  return profile->sample(index).timestamp.since_origin().InMicroseconds();
}
References v8::internal::index, v8::base::TimeDelta::InMicroseconds(), v8::internal::CpuProfile::sample(), v8::base::time_internal::TimeBase< TimeClass >::since_origin(), and v8::internal::CpuProfile::SampleInfo::timestamp.
Referenced by v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::buildInspectorObjectForTimestamps().
GetStartTime()
int64_t v8::CpuProfile::GetStartTime () const
Returns time when the profile recording was started (in microseconds) since some unspecified starting point.
Definition at line 11382 of file api.cc.
                                       {
  const i::CpuProfile* profile = reinterpret_cast<const i::CpuProfile*>(this);
  return profile->start_time().since_origin().InMicroseconds();
}
References v8::base::TimeDelta::InMicroseconds(), v8::base::time_internal::TimeBase< TimeClass >::since_origin(), and v8::internal::CpuProfile::start_time().
Referenced by v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::buildInspectorObjectForTimestamps(), and v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::createCPUProfile().
GetTitle()
Local< String > v8::CpuProfile::GetTitle () const
Returns CPU profile title.
Definition at line 11347 of file api.cc.
                                         {
  const i::CpuProfile* profile = reinterpret_cast<const i::CpuProfile*>(this);
  i::Isolate* i_isolate = profile->top_down()->isolate();
  return ToApiHandle<String>(
      i_isolate->factory()->InternalizeUtf8String(profile->title()));
}
References v8::internal::Isolate::factory(), v8::internal::Factory::InternalizeUtf8String(), v8::internal::ProfileTree::isolate(), v8::internal::CpuProfile::title(), and v8::internal::CpuProfile::top_down().
GetTopDownRoot()
const CpuProfileNode * v8::CpuProfile::GetTopDownRoot () const
Returns the root node of the top down call tree.
Definition at line 11354 of file api.cc.
                                                       {
  const i::CpuProfile* profile = reinterpret_cast<const i::CpuProfile*>(this);
  return reinterpret_cast<const CpuProfileNode*>(profile->top_down()->root());
}
References v8::internal::ProfileTree::root(), and v8::internal::CpuProfile::top_down().
Referenced by v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::createCPUProfile(), and v8::Shell::Main().
Serialize()
void v8::CpuProfile::Serialize (OutputStream * stream, CpuProfile::SerializationFormat format = kJSON) const
Prepare a serialized representation of the profile.
The result is written into the stream provided in chunks of specified size.
For the JSON format, heap contents are represented as an object with the following structure:
{ nodes: [nodes array], startTime: number, endTime: number samples: [strings array] timeDeltas: [numbers array] }
Definition at line 11397 of file api.cc.
                                                                       {
  Utils::ApiCheck(format == kJSON, "v8::CpuProfile::Serialize",
                  "Unknown serialization format");
  Utils::ApiCheck(stream->GetChunkSize() > 0, "v8::CpuProfile::Serialize",
                  "Invalid stream chunk size");
  i::CpuProfileJSONSerializer serializer(ToInternal(this));
  serializer.Serialize(stream);
}
References v8::Utils::ApiCheck(), v8::base::format, v8::OutputStream::GetChunkSize(), v8::kJSON, v8::internal::CpuProfileJSONSerializer::Serialize(), and v8::ToInternal().
Referenced by v8::D8Console::ProfileEnd().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-profiler.h
/mnt/V8SourceCode/src/api/api.cc