v8::internal::AstConsString Class Reference
#include <ast-value-factory.h>
Classes
struct Segment
Public Member Functions
AstConsString * AddString (Zone *zone, const AstRawString *s)
bool IsEmpty () const
template<typename IsolateT >
IndirectHandle< String > GetString (IsolateT *isolate)
template<typename IsolateT >
Handle< String > AllocateFlat (IsolateT *isolate) const
std::forward_list< const AstRawString * > ToRawStrings () const
const AstRawString * last () const
Private Member Functions
AstConsString ()
template<typename IsolateT >
Handle< String > Allocate (IsolateT *isolate) const
Private Attributes
friend Zone
IndirectHandle< String > string_
Segment segment_
Friends
class AstValueFactory
Detailed Description
Definition at line 150 of file ast-value-factory.h.
Constructor & Destructor Documentation
AstConsString()
v8::internal::AstConsString::AstConsString () [inline], [private]
Definition at line 190 of file ast-value-factory.h.
: string_(), segment_({nullptr, nullptr}) {}
Member Function Documentation
AddString()
AstConsString* v8::internal::AstConsString::AddString (Zone * zone, const AstRawString * s) [inline]
Definition at line 152 of file ast-value-factory.h.
                                                              {
    if (s->IsEmpty()) return this;
    if (!IsEmpty()) {
      // We're putting the new string to the head of the list, meaning
      // the string segments will be in reverse order.
      Segment* tmp = zone->New<Segment>(segment_);
      segment_.next = tmp;
    }
    segment_.string = s;
    return this;
  }
References v8::internal::AstRawString::IsEmpty(), v8::internal::Zone::New(), v8::internal::AstConsString::Segment::next, and v8::internal::AstConsString::Segment::string.
Referenced by v8::internal::AstValueFactory::NewConsString().
Allocate()
template<typename IsolateT >
Handle< String > v8::internal::AstConsString::Allocate (IsolateT * isolate) const [private]
Definition at line 190 of file ast-value-factory.cc.
                                                              {
  DCHECK(string_.is_null());
  if (IsEmpty()) {
    return isolate->factory()->empty_string();
  }
  // AstRawStrings are internalized before AstConsStrings are allocated, so
  // AstRawString::string() will just work.
  Handle<String> tmp = segment_.string->string();
  for (AstConsString::Segment* current = segment_.next; current != nullptr;
       current = current->next) {
    tmp = isolate->factory()
              ->NewConsString(current->string->string(), tmp,
                              AllocationType::kOld)
              .ToHandleChecked();
  }
  return tmp;
}
References v8::internal::DCHECK(), IsEmpty(), v8::internal::kOld, v8::internal::AstConsString::Segment::next, segment_, v8::internal::AstRawString::string(), v8::internal::AstConsString::Segment::string, and string_.
AllocateFlat()
template<typename IsolateT >
Handle<String> v8::internal::AstConsString::AllocateFlat (IsolateT * isolate) const
Referenced by v8::internal::Literal::BuildValue(), v8::internal::FunctionLiteral::GetName(), and v8::internal::interpreter::ConstantArrayBuilder::Entry::ToHandle().
GetString()
template<typename IsolateT >
IndirectHandle<String> v8::internal::AstConsString::GetString (IsolateT * isolate) [inline]
Definition at line 171 of file ast-value-factory.h.
                                                      {
    if (string_.is_null()) {
      string_ = Allocate(isolate);
    }
    return string_;
  }
References v8::base::anonymous_namespace{platform-posix.cc}::Allocate().
Referenced by v8::internal::FunctionLiteral::GetInferredName().
IsEmpty()
bool v8::internal::AstConsString::IsEmpty () const [inline]
Definition at line 164 of file ast-value-factory.h.
                       {
    DCHECK_IMPLIES(segment_.string == nullptr, segment_.next == nullptr);
    DCHECK_IMPLIES(segment_.string != nullptr, !segment_.string->IsEmpty());
    return segment_.string == nullptr;
  }
References DCHECK_IMPLIES.
Referenced by Allocate(), and v8::internal::FunctionLiteral::GetDebugName().
last()
const AstRawString* v8::internal::AstConsString::last () const [inline]
Definition at line 184 of file ast-value-factory.h.
{ return segment_.string; }
References v8::internal::AstRawString::string().
Referenced by v8::internal::interpreter::ConstantArrayBuilder::Insert().
ToRawStrings()
std::forward_list<const AstRawString*> v8::internal::AstConsString::ToRawStrings () const
Referenced by v8::internal::FunctionLiteral::GetDebugName().
Friends And Related Function Documentation
AstValueFactory
friend class AstValueFactory [friend]
Definition at line 187 of file ast-value-factory.h.
Member Data Documentation
segment_
Segment v8::internal::AstConsString::segment_ [private]
Definition at line 208 of file ast-value-factory.h.
Referenced by Allocate().
string_
IndirectHandle<String> v8::internal::AstConsString::string_ [private]
Definition at line 196 of file ast-value-factory.h.
Referenced by Allocate().
Zone
friend v8::internal::AstConsString::Zone [private]
Definition at line 188 of file ast-value-factory.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ast/ast-value-factory.h
/mnt/V8SourceCode/src/ast/ast-value-factory.cc