v8::internal::compiler::turboshaft::SnapshotTableKey< Value, KeyData > Class Template Reference
#include <snapshot-table.h>
Public Member Functions
bool operator== (SnapshotTableKey other) const
const KeyData & data () const
KeyData & data ()
SnapshotTableKey ()
bool valid () const
Private Member Functions
SnapshotTableKey (SnapshotTableEntry< Value, KeyData > &entry)
Private Attributes
SnapshotTableEntry< Value, KeyData > * entry_
Friends
class SnapshotTable< Value, KeyData >
Detailed Description
template<class Value, class KeyData>
class v8::internal::compiler::turboshaft::SnapshotTableKey< Value, KeyData >
Definition at line 73 of file snapshot-table.h.
Constructor & Destructor Documentation
SnapshotTableKey() [1/2]
template<class Value , class KeyData >
v8::internal::compiler::turboshaft::SnapshotTableKey< Value, KeyData >::SnapshotTableKey () [inline]
Definition at line 80 of file snapshot-table.h.
: entry_(nullptr) {}
SnapshotTableKey() [2/2]
template<class Value , class KeyData >
v8::internal::compiler::turboshaft::SnapshotTableKey< Value, KeyData >::SnapshotTableKey (SnapshotTableEntry< Value, KeyData > & entry) [inline], [explicit], [private]
Definition at line 87 of file snapshot-table.h.
      : entry_(&entry) {}
Member Function Documentation
data() [1/2]
template<class Value , class KeyData >
KeyData& v8::internal::compiler::turboshaft::SnapshotTableKey< Value, KeyData >::data () [inline]
Definition at line 79 of file snapshot-table.h.
{ return *entry_; }
References v8::internal::compiler::turboshaft::SnapshotTableKey< Value, KeyData >::entry_.
data() [2/2]
template<class Value , class KeyData >
const KeyData& v8::internal::compiler::turboshaft::SnapshotTableKey< Value, KeyData >::data () const [inline]
Definition at line 78 of file snapshot-table.h.
{ return *entry_; }
References v8::internal::compiler::turboshaft::SnapshotTableKey< Value, KeyData >::entry_.
Referenced by v8::internal::compiler::turboshaft::OffsetListTraits::next(), v8::internal::compiler::turboshaft::BaseListTraits::next(), v8::internal::compiler::turboshaft::wle::OffsetListTraits::next(), v8::internal::compiler::turboshaft::wle::BaseListTraits::next(), v8::internal::compiler::turboshaft::OffsetListTraits::prev(), v8::internal::compiler::turboshaft::BaseListTraits::prev(), v8::internal::compiler::turboshaft::wle::OffsetListTraits::prev(), and v8::internal::compiler::turboshaft::wle::BaseListTraits::prev().
operator==()
template<class Value , class KeyData >
bool v8::internal::compiler::turboshaft::SnapshotTableKey< Value, KeyData >::operator== (SnapshotTableKey< Value, KeyData > other) const [inline]
Definition at line 75 of file snapshot-table.h.
                                                {
    return entry_ == other.entry_;
  }
References v8::internal::compiler::turboshaft::SnapshotTableKey< Value, KeyData >::entry_.
valid()
template<class Value , class KeyData >
bool v8::internal::compiler::turboshaft::SnapshotTableKey< Value, KeyData >::valid () const [inline]
Definition at line 82 of file snapshot-table.h.
{ return entry_ != nullptr; }
Referenced by v8::internal::compiler::turboshaft::OffsetListTraits::non_empty(), v8::internal::compiler::turboshaft::BaseListTraits::non_empty(), v8::internal::compiler::turboshaft::wle::OffsetListTraits::non_empty(), and v8::internal::compiler::turboshaft::wle::BaseListTraits::non_empty().
Friends And Related Function Documentation
SnapshotTable< Value, KeyData >
template<class Value , class KeyData >
friend class SnapshotTable< Value, KeyData > [friend]
Definition at line 82 of file snapshot-table.h.
Member Data Documentation
entry_
template<class Value , class KeyData >
SnapshotTableEntry<Value, KeyData>* v8::internal::compiler::turboshaft::SnapshotTableKey< Value, KeyData >::entry_ [private]
Definition at line 86 of file snapshot-table.h.
Referenced by v8::internal::compiler::turboshaft::SnapshotTableKey< Value, KeyData >::data(), and v8::internal::compiler::turboshaft::SnapshotTableKey< Value, KeyData >::operator==().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/snapshot-table.h