v8::internal::IrRegExpData::BodyDescriptor Class Reference
#include <objects-body-descriptors-inl.h>
Static Public Member Functions
template<typename ObjectVisitor >
static void IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor *v)
static int SizeOf (Tagged< Map > map, Tagged< HeapObject > obj)
Additional Inherited Members
Detailed Description
Definition at line 442 of file objects-body-descriptors-inl.h.
Member Function Documentation
IterateBody()
template<typename ObjectVisitor >
static void v8::internal::IrRegExpData::BodyDescriptor::IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor * v) [inline], [static]
Definition at line 445 of file objects-body-descriptors-inl.h.
                                                                    {
    IterateSelfIndirectPointer(obj, kRegExpDataIndirectPointerTag, v);
    IteratePointer(obj, kSourceOffset, v);
    IteratePointer(obj, kWrapperOffset, v);
    IterateProtectedPointer(obj, kLatin1BytecodeOffset, v);
    IterateProtectedPointer(obj, kUc16BytecodeOffset, v);
    IterateCodePointer(obj, kLatin1CodeOffset, v, IndirectPointerMode::kStrong);
    IterateCodePointer(obj, kUc16CodeOffset, v, IndirectPointerMode::kStrong);
    IteratePointer(obj, kCaptureNameMapOffset, v);
  }
References v8::internal::BodyDescriptorBase::IterateCodePointer(), v8::internal::BodyDescriptorBase::IteratePointer(), v8::internal::BodyDescriptorBase::IterateProtectedPointer(), v8::internal::BodyDescriptorBase::IterateSelfIndirectPointer(), and v8::internal::kStrong.
SizeOf()
static int v8::internal::IrRegExpData::BodyDescriptor::SizeOf (Tagged< Map > map, Tagged< HeapObject > obj) [inline], [static]
Definition at line 459 of file objects-body-descriptors-inl.h.
                                                                    {
    return kSize;
  }
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/objects-body-descriptors-inl.h