v8_inspector::V8StackTraceImpl Class Reference
#include <v8-stack-trace-impl.h>
Classes
class StackFrameIterator
Public Member Functions
~V8StackTraceImpl () override
V8StackTraceImpl (const V8StackTraceImpl &)=delete
V8StackTraceImpl & operator= (const V8StackTraceImpl &)=delete
std::unique_ptr< protocol::Runtime::StackTrace > buildInspectorObjectImpl (V8Debugger *debugger) const
std::unique_ptr< protocol::Runtime::StackTrace > buildInspectorObjectImpl (V8Debugger *debugger, int maxAsyncDepth) const
std::unique_ptr< V8StackTrace > clone () override
StringView firstNonEmptySourceURL () const override
bool isEmpty () const override
StringView topSourceURL () const override
int topLineNumber () const override
int topColumnNumber () const override
int topScriptId () const override
StringView topFunctionName () const override
std::unique_ptr< protocol::Runtime::API::StackTrace > buildInspectorObject (int maxAsyncDepth) const override
std::unique_ptr< StringBuffer > toString () const override
bool isEqualIgnoringTopFrame (V8StackTraceImpl *stackTrace) const
std::vector< V8StackFrame > frames () const override
Static Public Member Functions
static std::unique_ptr< V8StackTraceImpl > create (V8Debugger *, v8::Local< v8::StackTrace >, int maxStackSize)
static std::unique_ptr< V8StackTraceImpl > capture (V8Debugger *, int maxStackSize)
Static Public Attributes
static constexpr int kDefaultMaxCallStackSizeToCapture = 200
Private Member Functions
V8StackTraceImpl (std::vector< std::shared_ptr< StackFrame >> frames, int maxAsyncDepth, std::shared_ptr< AsyncStackTrace > asyncParent, const V8StackTraceId &externalParent)
Private Attributes
std::vector< std::shared_ptr< StackFrame > > m_frames
int m_maxAsyncDepth
std::weak_ptr< AsyncStackTrace > m_asyncParent
V8StackTraceId m_externalParent
Detailed Description
Definition at line 52 of file v8-stack-trace-impl.h.
Constructor & Destructor Documentation
 V8StackTraceImpl()
v8_inspector::V8StackTraceImpl::~V8StackTraceImpl () [override], [default]
V8StackTraceImpl() [1/2]
v8_inspector::V8StackTraceImpl::V8StackTraceImpl (const V8StackTraceImpl &) [delete]
Referenced by clone(), and create().
V8StackTraceImpl() [2/2]
v8_inspector::V8StackTraceImpl::V8StackTraceImpl (std::vector< std::shared_ptr< StackFrame >> frames, int maxAsyncDepth, std::shared_ptr< AsyncStackTrace > asyncParent, const V8StackTraceId & externalParent) [private]
Definition at line 257 of file v8-stack-trace-impl.cc.
    : m_frames(std::move(frames)),
      m_maxAsyncDepth(maxAsyncDepth),
      m_asyncParent(std::move(asyncParent)),
      m_externalParent(externalParent) {}
Member Function Documentation
buildInspectorObject()
std::unique_ptr< protocol::Runtime::API::StackTrace > v8_inspector::V8StackTraceImpl::buildInspectorObject (int maxAsyncDepth) const [override], [virtual]
Implements v8_inspector::V8StackTrace.
Definition at line 334 of file v8-stack-trace-impl.cc.
                                                              {
  return buildInspectorObjectImpl(nullptr,
                                  std::min(maxAsyncDepth, m_maxAsyncDepth));
}
References buildInspectorObjectImpl(), and m_maxAsyncDepth.
buildInspectorObjectImpl() [1/2]
std::unique_ptr< protocol::Runtime::StackTrace > v8_inspector::V8StackTraceImpl::buildInspectorObjectImpl (V8Debugger * debugger) const
Definition at line 321 of file v8-stack-trace-impl.cc.
                                                                     {
  return buildInspectorObjectImpl(debugger, m_maxAsyncDepth);
}
References m_maxAsyncDepth.
Referenced by buildInspectorObject().
buildInspectorObjectImpl() [2/2]
std::unique_ptr< protocol::Runtime::StackTrace > v8_inspector::V8StackTraceImpl::buildInspectorObjectImpl (V8Debugger * debugger, int maxAsyncDepth) const
Definition at line 326 of file v8-stack-trace-impl.cc.
                                                                    {
  return buildInspectorObjectCommon(debugger, m_frames, String16(),
                                    m_asyncParent.lock(), m_externalParent,
                                    maxAsyncDepth);
}
References v8_inspector::anonymous_namespace{v8-stack-trace-impl.cc}::buildInspectorObjectCommon(), m_asyncParent, m_externalParent, and m_frames.
capture()
std::unique_ptr< V8StackTraceImpl > v8_inspector::V8StackTraceImpl::capture (V8Debugger * debugger, int maxStackSize) [static]
Definition at line 238 of file v8-stack-trace-impl.cc.
                                            {
  DCHECK(debugger);
  TRACE_EVENT1(
      TRACE_DISABLED_BY_DEFAULT("v8.inspector") "," TRACE_DISABLED_BY_DEFAULT(
          "v8.stack_trace"),
      "V8StackTraceImpl::capture", "maxFrameCount", maxStackSize);
  v8::Isolate* isolate = debugger->isolate();
  v8::HandleScope handleScope(isolate);
  v8::Local<v8::StackTrace> v8StackTrace;
  if (isolate->InContext()) {
    v8StackTrace = v8::StackTrace::CurrentStackTrace(isolate, maxStackSize,
                                                     stackTraceOptions);
  }
  return V8StackTraceImpl::create(debugger, v8StackTrace, maxStackSize);
}
References create(), v8::StackTrace::CurrentStackTrace(), DCHECK, v8::Isolate::InContext(), v8_inspector::V8Debugger::isolate(), v8_inspector::anonymous_namespace{v8-stack-trace-impl.cc}::stackTraceOptions, TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT1.
Referenced by v8_inspector::V8Debugger::captureStackTrace(), v8_inspector::V8Debugger::continueToLocation(), v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::currentDebugLocation(), v8_inspector::V8DebuggerAgentImpl::didParseSource(), v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::reportCall(), and v8_inspector::V8Debugger::shouldContinueToCurrentLocation().
clone()
std::unique_ptr< V8StackTrace > v8_inspector::V8StackTraceImpl::clone () [override], [virtual]
Implements v8_inspector::V8StackTrace.
Definition at line 268 of file v8-stack-trace-impl.cc.
                                                    {
  return std::unique_ptr<V8StackTrace>(new V8StackTraceImpl(
      m_frames, 0, std::shared_ptr<AsyncStackTrace>(), V8StackTraceId()));
}
References m_frames, and V8StackTraceImpl().
create()
std::unique_ptr< V8StackTraceImpl > v8_inspector::V8StackTraceImpl::create (V8Debugger * debugger, v8::Local< v8::StackTrace > v8StackTrace, int maxStackSize) [static]
Definition at line 212 of file v8-stack-trace-impl.cc.
                      {
  DCHECK(debugger);
  v8::Isolate* isolate = debugger->isolate();
  v8::HandleScope scope(isolate);
  std::vector<std::shared_ptr<StackFrame>> frames;
  if (!v8StackTrace.IsEmpty() && v8StackTrace->GetFrameCount()) {
    frames = toFramesVector(debugger, v8StackTrace, maxStackSize);
  }
  int maxAsyncDepth = debugger->maxAsyncCallChainDepth();
  std::shared_ptr<AsyncStackTrace> asyncParent;
  V8StackTraceId externalParent;
  if (!v8StackTrace.IsEmpty()) {
    debugger->asyncParentFor(v8StackTrace->GetID(), &asyncParent,
                             &externalParent);
  }
  if (frames.empty() && !asyncParent && externalParent.IsInvalid()) return {};
  return std::unique_ptr<V8StackTraceImpl>(new V8StackTraceImpl(
      std::move(frames), maxAsyncDepth, asyncParent, externalParent));
}
References v8_inspector::V8Debugger::asyncParentFor(), DCHECK, frames(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8_inspector::V8StackTraceId::IsInvalid(), v8_inspector::V8Debugger::isolate(), v8_inspector::V8Debugger::maxAsyncCallChainDepth(), v8_inspector::anonymous_namespace{v8-stack-trace-impl.cc}::toFramesVector(), and V8StackTraceImpl().
Referenced by capture(), and v8_inspector::V8Debugger::createStackTrace().
firstNonEmptySourceURL()
StringView v8_inspector::V8StackTraceImpl::firstNonEmptySourceURL () const [override], [virtual]
Implements v8_inspector::V8StackTrace.
Definition at line 273 of file v8-stack-trace-impl.cc.
                                                          {
  StackFrameIterator current(this);
  while (!current.done()) {
    if (current.frame()->sourceURL().length()) {
      return toStringView(current.frame()->sourceURL());
    }
    current.next();
  }
  return StringView();
}
References v8_inspector::V8StackTraceImpl::StackFrameIterator::done(), v8_inspector::V8StackTraceImpl::StackFrameIterator::frame(), v8_inspector::String16::length(), v8_inspector::V8StackTraceImpl::StackFrameIterator::next(), v8_inspector::StackFrame::sourceURL(), and v8_inspector::toStringView().
frames()
std::vector< V8StackFrame > v8_inspector::V8StackTraceImpl::frames () const [override], [virtual]
Implements v8_inspector::V8StackTrace.
Definition at line 304 of file v8-stack-trace-impl.cc.
                                                       {
  std::vector<V8StackFrame> ret;
  ret.reserve(m_frames.size());
  for (const auto& frame : m_frames) {
    if (frame) {
      ret.emplace_back(V8StackFrame{
          toStringView(frame->sourceURL()), toStringView(frame->functionName()),
          frame->lineNumber() + 1, frame->columnNumber() + 1,
          frame->scriptId()});
    }
  }
  return ret;
}
References m_frames, and v8_inspector::toStringView().
Referenced by v8_inspector::AsyncStackTrace::capture(), create(), and v8_inspector::V8StackTraceImpl::StackFrameIterator::next().
isEmpty()
bool v8_inspector::V8StackTraceImpl::isEmpty () const [override], [virtual]
Implements v8_inspector::V8StackTrace.
Definition at line 284 of file v8-stack-trace-impl.cc.
{ return m_frames.empty(); }
References m_frames.
isEqualIgnoringTopFrame()
bool v8_inspector::V8StackTraceImpl::isEqualIgnoringTopFrame (V8StackTraceImpl * stackTrace) const
Definition at line 357 of file v8-stack-trace-impl.cc.
                                        {
  StackFrameIterator current(this);
  StackFrameIterator target(stackTrace);
  current.next();
  target.next();
  while (!current.done() && !target.done()) {
    if (!current.frame()->isEqual(target.frame())) {
      return false;
    }
    current.next();
    target.next();
  }
  return current.done() == target.done();
}
References v8_inspector::V8StackTraceImpl::StackFrameIterator::done(), v8_inspector::V8StackTraceImpl::StackFrameIterator::frame(), v8_inspector::StackFrame::isEqual(), and v8_inspector::V8StackTraceImpl::StackFrameIterator::next().
operator=()
V8StackTraceImpl& v8_inspector::V8StackTraceImpl::operator= (const V8StackTraceImpl &) [delete]
topColumnNumber()
int v8_inspector::V8StackTraceImpl::topColumnNumber () const [override], [virtual]
Implements v8_inspector::V8StackTrace.
Definition at line 294 of file v8-stack-trace-impl.cc.
                                            {
  return m_frames[0]->columnNumber() + 1;
}
References m_frames.
topFunctionName()
StringView v8_inspector::V8StackTraceImpl::topFunctionName () const [override], [virtual]
Implements v8_inspector::V8StackTrace.
Definition at line 300 of file v8-stack-trace-impl.cc.
                                                   {
  return toStringView(m_frames[0]->functionName());
}
References m_frames, and v8_inspector::toStringView().
topLineNumber()
int v8_inspector::V8StackTraceImpl::topLineNumber () const [override], [virtual]
Implements v8_inspector::V8StackTrace.
Definition at line 290 of file v8-stack-trace-impl.cc.
                                          {
  return m_frames[0]->lineNumber() + 1;
}
References m_frames.
topScriptId()
int v8_inspector::V8StackTraceImpl::topScriptId () const [override], [virtual]
Implements v8_inspector::V8StackTrace.
Definition at line 298 of file v8-stack-trace-impl.cc.
{ return m_frames[0]->scriptId(); }
References m_frames.
topSourceURL()
StringView v8_inspector::V8StackTraceImpl::topSourceURL () const [override], [virtual]
Implements v8_inspector::V8StackTrace.
Definition at line 286 of file v8-stack-trace-impl.cc.
                                                {
  return toStringView(m_frames[0]->sourceURL());
}
References m_frames, and v8_inspector::toStringView().
toString()
std::unique_ptr< StringBuffer > v8_inspector::V8StackTraceImpl::toString () const [override], [virtual]
Implements v8_inspector::V8StackTrace.
Definition at line 339 of file v8-stack-trace-impl.cc.
                                                             {
  String16Builder stackTrace;
  for (size_t i = 0; i < m_frames.size(); ++i) {
    const StackFrame& frame = *m_frames[i];
    stackTrace.append("\n at " + (frame.functionName().length()
                                         ? frame.functionName()
                                         : "(anonymous function)"));
    stackTrace.append(" (");
    stackTrace.append(frame.sourceURL());
    stackTrace.append(':');
    stackTrace.append(String16::fromInteger(frame.lineNumber() + 1));
    stackTrace.append(':');
    stackTrace.append(String16::fromInteger(frame.columnNumber() + 1));
    stackTrace.append(')');
  }
  return StringBufferFrom(stackTrace.toString());
}
References v8_inspector::String16Builder::append(), v8_inspector::StackFrame::columnNumber(), v8_inspector::String16::fromInteger(), v8_inspector::StackFrame::functionName(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8_inspector::String16::length(), v8_inspector::StackFrame::lineNumber(), m_frames, v8_inspector::StackFrame::sourceURL(), v8_inspector::StringBufferFrom(), and v8_inspector::String16Builder::toString().
Member Data Documentation
kDefaultMaxCallStackSizeToCapture
constexpr int v8_inspector::V8StackTraceImpl::kDefaultMaxCallStackSizeToCapture = 200 [static], [constexpr]
Definition at line 54 of file v8-stack-trace-impl.h.
Referenced by v8_inspector::V8Debugger::captureStackTrace(), v8_inspector::V8Debugger::continueToLocation(), v8_inspector::V8Debugger::createStackTrace(), v8_inspector::V8RuntimeAgentImpl::enable(), v8_inspector::V8Debugger::setMaxCallStackSizeToCapture(), and v8_inspector::V8Debugger::shouldContinueToCurrentLocation().
m_asyncParent
std::weak_ptr<AsyncStackTrace> v8_inspector::V8StackTraceImpl::m_asyncParent [private]
Definition at line 111 of file v8-stack-trace-impl.h.
Referenced by buildInspectorObjectImpl().
m_externalParent
V8StackTraceId v8_inspector::V8StackTraceImpl::m_externalParent [private]
Definition at line 112 of file v8-stack-trace-impl.h.
Referenced by buildInspectorObjectImpl().
m_frames
std::vector<std::shared_ptr<StackFrame> > v8_inspector::V8StackTraceImpl::m_frames [private]
Definition at line 109 of file v8-stack-trace-impl.h.
Referenced by buildInspectorObjectImpl(), clone(), frames(), isEmpty(), topColumnNumber(), topFunctionName(), topLineNumber(), topScriptId(), topSourceURL(), and toString().
m_maxAsyncDepth
int v8_inspector::V8StackTraceImpl::m_maxAsyncDepth [private]
Definition at line 110 of file v8-stack-trace-impl.h.
Referenced by buildInspectorObject(), and buildInspectorObjectImpl().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/inspector/v8-stack-trace-impl.h
/mnt/V8SourceCode/src/inspector/v8-stack-trace-impl.cc