v8::internal::SharedStructTypeRegistry Class Reference
#include <js-struct.h>
Classes
class Data
Public Member Functions
SharedStructTypeRegistry ()
~SharedStructTypeRegistry ()
MaybeDirectHandle< Map > Register (Isolate *isolate, Handle< String > key, const base::Vector< const DirectHandle< Name >> field_names, const std::set< uint32_t > &element_names)
void IterateElements (Isolate *isolate, RootVisitor *visitor)
void NotifyElementsRemoved (int count)
Static Public Member Functions
static constexpr Tagged< Smi > deleted_element ()
Private Member Functions
MaybeDirectHandle< Map > RegisterNoThrow (Isolate *isolate, Handle< String > key, const base::Vector< const DirectHandle< Name >> field_names, const std::set< uint32_t > &element_names)
MaybeDirectHandle< Map > CheckIfEntryMatches (Isolate *isolate, InternalIndex entry, DirectHandle< String > key, const base::Vector< const DirectHandle< Name >> field_names, const std::set< uint32_t > &element_names)
void EnsureCapacity (PtrComprCageBase cage_base, int additional_elements)
Private Attributes
std::unique_ptr< Data > data_
base::Mutex data_mutex_
Detailed Description
Definition at line 79 of file js-struct.h.
Constructor & Destructor Documentation
SharedStructTypeRegistry()
v8::internal::SharedStructTypeRegistry::SharedStructTypeRegistry ()
Definition at line 370 of file js-struct.cc.
    : data_(Data::New(Data::kMinCapacity)) {
  DCHECK_EQ(deleted_element(), Data::deleted_element());
}
References DCHECK_EQ, deleted_element(), and v8::internal::OffHeapHashTableBase< Data >::deleted_element().
 SharedStructTypeRegistry()
v8::internal::SharedStructTypeRegistry::~SharedStructTypeRegistry () [default]
Member Function Documentation
CheckIfEntryMatches()
MaybeDirectHandle< Map > v8::internal::SharedStructTypeRegistry::CheckIfEntryMatches (Isolate * isolate, InternalIndex entry, DirectHandle< String > key, const base::Vector< const DirectHandle< Name >> field_names, const std::set< uint32_t > & element_names) [private]
Definition at line 377 of file js-struct.cc.
                                           {
  Tagged<Map> existing_map = Cast<Map>(data_->GetKey(isolate, entry));
  // A map is considered a match iff all of the following hold:
  // - field names are the same element-wise (in order)
  // - element indices are the same
  // Registered types always have the key as the first descriptor.
  DCHECK_EQ(
      *JSSharedStruct::GetRegistryKey(isolate, existing_map).ToHandleChecked(),
      *key);
  int num_descriptors = static_cast<int>(field_names.size()) + 1;
  if (!element_names.empty()) {
    if (JSSharedStruct::GetElementsTemplate(isolate, existing_map).is_null()) {
      return MaybeDirectHandle<Map>();
    }
    num_descriptors++;
  }
  if (num_descriptors != existing_map->NumberOfOwnDescriptors()) {
    return MaybeDirectHandle<Map>();
  }
  Tagged<DescriptorArray> existing_descriptors =
      existing_map->instance_descriptors(isolate);
  auto field_names_iter = field_names.begin();
  for (InternalIndex i : existing_map->IterateOwnDescriptors()) {
    if (JSSharedStruct::IsElementsTemplateDescriptor(isolate, existing_map,
                                                     i)) {
      DirectHandle<NumberDictionary> elements_template(
          Cast<NumberDictionary>(
              existing_map->instance_descriptors()->GetStrongValue(isolate, i)),
          isolate);
      if (element_names.size() != elements_template->NumberOfElements()) {
        return MaybeDirectHandle<Map>();
      }
      for (int element : element_names) {
        if (elements_template->FindEntry(isolate, element).is_not_found()) {
          return MaybeDirectHandle<Map>();
        }
      }
      continue;
    }
    if (JSSharedStruct::IsRegistryKeyDescriptor(isolate, existing_map, i)) {
      continue;
    }
    Tagged<Name> existing_name = existing_descriptors->GetKey(i);
    DCHECK(IsUniqueName(existing_name));
    Tagged<Name> name = **field_names_iter;
    DCHECK(IsUniqueName(name));
    if (name != existing_name) return MaybeDirectHandle<Map>();
    ++field_names_iter;
  }
  return direct_handle(existing_map, isolate);
}
References v8::internal::Cast< NumberDictionary >(), data_, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::direct_handle(), v8::internal::JSSharedStruct::GetElementsTemplate(), v8::internal::JSSharedStruct::GetRegistryKey(), v8::internal::JSSharedStruct::IsElementsTemplateDescriptor(), v8::internal::JSSharedStruct::IsRegistryKeyDescriptor(), v8::internal::IsUniqueName(), v8::internal::key, and v8::internal::name.
Referenced by RegisterNoThrow().
deleted_element()
static constexpr Tagged<Smi> v8::internal::SharedStructTypeRegistry::deleted_element () [inline], [static], [constexpr]
Definition at line 81 of file js-struct.h.
{ return Smi::FromInt(1); }
References v8::internal::Smi::FromInt().
Referenced by SharedStructTypeRegistry().
EnsureCapacity()
void v8::internal::SharedStructTypeRegistry::EnsureCapacity (PtrComprCageBase cage_base, int additional_elements) [private]
Definition at line 514 of file js-struct.cc.
                                                                       {
  data_mutex_.AssertHeld();
  int new_capacity;
  if (data_->ShouldResizeToAdd(additional_elements, &new_capacity)) {
    std::unique_ptr<Data> new_data(Data::New(new_capacity));
    data_->RehashInto(cage_base, new_data.get());
    data_ = std::move(new_data);
  }
}
References v8::base::Mutex::AssertHeld(), data_, data_mutex_, and v8::internal::SharedStructTypeRegistry::Data::New().
Referenced by RegisterNoThrow().
IterateElements()
void v8::internal::SharedStructTypeRegistry::IterateElements (Isolate * isolate, RootVisitor * visitor)
Definition at line 496 of file js-struct.cc.
                                                                     {
  // Ideally this should only happen during a global safepoint, when all
  // workers and background threads are paused, so there would be no need to
  // take the data mutex. However, the array left trimming has a verifier
  // visitor that visits all roots (including weak ones), thus we take the
  // mutex.
  //
  // TODO(v8:12547): Figure out how to do
  // isolate->global_safepoint()->AssertActive() instead.
  base::MutexGuard data_guard(&data_mutex_);
  data_->IterateElements(Root::kSharedStructTypeRegistry, visitor);
}
References data_, and data_mutex_.
Referenced by v8::internal::Heap::IterateWeakRoots().
NotifyElementsRemoved()
void v8::internal::SharedStructTypeRegistry::NotifyElementsRemoved (int count)
Definition at line 510 of file js-struct.cc.
                                                              {
  data_->ElementsRemoved(count);
}
References data_.
Register()
MaybeDirectHandle< Map > v8::internal::SharedStructTypeRegistry::Register (Isolate * isolate, Handle< String > key, const base::Vector< const DirectHandle< Name >> field_names, const std::set< uint32_t > & element_names)
Definition at line 482 of file js-struct.cc.
                                           {
  MaybeDirectHandle<Map> canonical_map =
      RegisterNoThrow(isolate, key, field_names, element_names);
  if (canonical_map.is_null()) {
    THROW_NEW_ERROR(
        isolate,
        NewTypeError(MessageTemplate::kSharedStructTypeRegistryMismatch, key));
  }
  return canonical_map;
}
References v8::internal::MaybeDirectHandle< T >::is_null(), v8::internal::key, RegisterNoThrow(), and THROW_NEW_ERROR.
RegisterNoThrow()
MaybeDirectHandle< Map > v8::internal::SharedStructTypeRegistry::RegisterNoThrow (Isolate * isolate, Handle< String > key, const base::Vector< const DirectHandle< Name >> field_names, const std::set< uint32_t > & element_names) [private]
Definition at line 441 of file js-struct.cc.
                                           {
  key = isolate->factory()->InternalizeString(key);
  // To avoid deadlock with iteration during GC and modifying the table, no GC
  // must occur under lock.
  {
    NoGarbageCollectionMutexGuard data_guard(&data_mutex_);
    InternalIndex entry = data_->FindEntry(isolate, key, key->hash());
    if (entry.is_found()) {
      return CheckIfEntryMatches(isolate, entry, key, field_names,
                                 element_names);
    }
  }
  // We have a likely miss. Create a new instance map outside of the lock.
  DirectHandle<Map> map = JSSharedStruct::CreateInstanceMap(
      isolate, field_names, element_names, key);
  // Relookup to see if it's in fact a miss.
  NoGarbageCollectionMutexGuard data_guard(&data_mutex_);
  EnsureCapacity(isolate, 1);
  InternalIndex entry =
      data_->FindEntryOrInsertionEntry(isolate, key, key->hash());
  Tagged<Object> existing_key = data_->GetKey(isolate, entry);
  if (existing_key == Data::empty_element()) {
    data_->AddAt(isolate, entry, *map);
    return map;
  } else if (existing_key == Data::deleted_element()) {
    data_->OverwriteDeletedAt(isolate, entry, *map);
    return map;
  } else {
    // An entry with the same key was inserted between the two locks.
    return CheckIfEntryMatches(isolate, entry, key, field_names, element_names);
  }
}
References CheckIfEntryMatches(), v8::internal::JSSharedStruct::CreateInstanceMap(), data_, data_mutex_, v8::internal::OffHeapHashTableBase< Data >::deleted_element(), v8::internal::OffHeapHashTableBase< Data >::empty_element(), EnsureCapacity(), v8::internal::Isolate::factory(), v8::internal::Factory::InternalizeString(), v8::internal::InternalIndex::is_found(), and v8::internal::key.
Referenced by Register().
Member Data Documentation
data_
std::unique_ptr<Data> v8::internal::SharedStructTypeRegistry::data_ [private]
Definition at line 109 of file js-struct.h.
Referenced by CheckIfEntryMatches(), EnsureCapacity(), IterateElements(), NotifyElementsRemoved(), and RegisterNoThrow().
data_mutex_
base::Mutex v8::internal::SharedStructTypeRegistry::data_mutex_ [private]
Definition at line 112 of file js-struct.h.
Referenced by EnsureCapacity(), IterateElements(), and RegisterNoThrow().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-struct.h
/mnt/V8SourceCode/src/objects/js-struct.cc