v8::internal::ReportBuiltinEventRecord Class Reference
#include <cpu-profiler.h>
Public Member Functions
void UpdateCodeMap (InstructionStreamMap *instruction_stream_map)
Public Attributes
Address instruction_start
unsigned instruction_size
Builtin builtin
Additional Inherited Members
Detailed Description
Definition at line 101 of file cpu-profiler.h.
Member Function Documentation
UpdateCodeMap()
void v8::internal::ReportBuiltinEventRecord::UpdateCodeMap (InstructionStreamMap * instruction_stream_map) [inline]
Definition at line 48 of file cpu-profiler-inl.h.
                                                  {
  CodeEntry* entry = instruction_stream_map->FindEntry(instruction_start);
  if (entry) {
    entry->SetBuiltinId(builtin);
    return;
  }
#if V8_ENABLE_WEBASSEMBLY
  if (builtin == Builtin::kJSToWasmWrapper) {
    // Make sure to add the generic js-to-wasm wrapper builtin, because that
    // one is supposed to show up in profiles.
    entry = instruction_stream_map->code_entries().Create(
        LogEventListener::CodeTag::kBuiltin, "js-to-wasm");
    instruction_stream_map->AddCode(instruction_start, entry, instruction_size);
  }
  if (builtin == Builtin::kWasmToJsWrapperCSA) {
    // Make sure to add the generic wasm-to-js wrapper builtin, because that
    // one is supposed to show up in profiles.
    entry = instruction_stream_map->code_entries().Create(
        LogEventListener::CodeTag::kBuiltin, "wasm-to-js");
    instruction_stream_map->AddCode(instruction_start, entry, instruction_size);
  }
#endif // V8_ENABLE_WEBASSEMBLY
}
References v8::internal::InstructionStreamMap::AddCode(), builtin, v8::internal::InstructionStreamMap::code_entries(), v8::internal::CodeEntryStorage::Create(), v8::internal::InstructionStreamMap::FindEntry(), instruction_size, instruction_start, and v8::internal::CodeEntry::SetBuiltinId().
Member Data Documentation
builtin
Builtin v8::internal::ReportBuiltinEventRecord::builtin
Definition at line 105 of file cpu-profiler.h.
Referenced by v8::internal::ProfilerCodeObserver::LogBuiltins(), and UpdateCodeMap().
instruction_size
unsigned v8::internal::ReportBuiltinEventRecord::instruction_size
Definition at line 104 of file cpu-profiler.h.
Referenced by v8::internal::ProfilerCodeObserver::LogBuiltins(), and UpdateCodeMap().
instruction_start
Address v8::internal::ReportBuiltinEventRecord::instruction_start
Definition at line 103 of file cpu-profiler.h.
Referenced by v8::internal::ProfilerCodeObserver::LogBuiltins(), and UpdateCodeMap().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/profiler/cpu-profiler.h
/mnt/V8SourceCode/src/profiler/cpu-profiler-inl.h