v8::ContainsOnlyOneByteHelper Class Reference
Public Member Functions
ContainsOnlyOneByteHelper ()
ContainsOnlyOneByteHelper (const ContainsOnlyOneByteHelper &)=delete
ContainsOnlyOneByteHelper & operator= (const ContainsOnlyOneByteHelper &)=delete
bool Check (i::Tagged< i::String > string)
void VisitOneByteString (const uint8_t *chars, int length)
void VisitTwoByteString (const uint16_t *chars, int length)
Private Member Functions
bool CheckCons (i::Tagged< i::ConsString > cons_string)
Private Attributes
bool is_one_byte_
Detailed Description
Definition at line 5589 of file api.cc.
Constructor & Destructor Documentation
ContainsOnlyOneByteHelper() [1/2]
v8::ContainsOnlyOneByteHelper::ContainsOnlyOneByteHelper () [inline]
Definition at line 5591 of file api.cc.
: is_one_byte_(true) {}
ContainsOnlyOneByteHelper() [2/2]
v8::ContainsOnlyOneByteHelper::ContainsOnlyOneByteHelper (const ContainsOnlyOneByteHelper &) [delete]
Member Function Documentation
Check()
bool v8::ContainsOnlyOneByteHelper::Check (i::Tagged< i::String > string) [inline]
Definition at line 5595 of file api.cc.
                                      {
    i::Tagged<i::ConsString> cons_string =
        i::String::VisitFlat(this, string, 0);
    if (cons_string.is_null()) return is_one_byte_;
    return CheckCons(cons_string);
  }
References CheckCons(), v8::internal::Tagged< HeapObject >::is_null(), is_one_byte_, and v8::internal::String::VisitFlat().
Referenced by v8::String::ContainsOnlyOneByte().
CheckCons()
bool v8::ContainsOnlyOneByteHelper::CheckCons (i::Tagged< i::ConsString > cons_string) [inline], [private]
Definition at line 5637 of file api.cc.
                                                   {
    while (true) {
      // Check left side if flat.
      i::Tagged<i::String> left = cons_string->first();
      i::Tagged<i::ConsString> left_as_cons =
          i::String::VisitFlat(this, left, 0);
      if (!is_one_byte_) return false;
      // Check right side if flat.
      i::Tagged<i::String> right = cons_string->second();
      i::Tagged<i::ConsString> right_as_cons =
          i::String::VisitFlat(this, right, 0);
      if (!is_one_byte_) return false;
      // Standard recurse/iterate trick.
      if (!left_as_cons.is_null() && !right_as_cons.is_null()) {
        if (left->length() < right->length()) {
          CheckCons(left_as_cons);
          cons_string = right_as_cons;
        } else {
          CheckCons(right_as_cons);
          cons_string = left_as_cons;
        }
        // Check fast return.
        if (!is_one_byte_) return false;
        continue;
      }
      // Descend left in place.
      if (!left_as_cons.is_null()) {
        cons_string = left_as_cons;
        continue;
      }
      // Descend right in place.
      if (!right_as_cons.is_null()) {
        cons_string = right_as_cons;
        continue;
      }
      // Terminate.
      break;
    }
    return is_one_byte_;
  }
References v8::internal::Tagged< HeapObject >::is_null(), is_one_byte_, and v8::internal::String::VisitFlat().
Referenced by Check().
operator=()
ContainsOnlyOneByteHelper& v8::ContainsOnlyOneByteHelper::operator= (const ContainsOnlyOneByteHelper &) [delete]
VisitOneByteString()
void v8::ContainsOnlyOneByteHelper::VisitOneByteString (const uint8_t * chars, int length) [inline]
Definition at line 5601 of file api.cc.
                                                            {
    // Nothing to do.
  }
VisitTwoByteString()
void v8::ContainsOnlyOneByteHelper::VisitTwoByteString (const uint16_t * chars, int length) [inline]
Definition at line 5604 of file api.cc.
                                                             {
    // Accumulated bits.
    uintptr_t acc = 0;
    // Align to uintptr_t.
    const uint16_t* end = chars + length;
    while (Unaligned(chars) && chars != end) {
      acc |= *chars++;
    }
    // Read word aligned in blocks,
    // checking the return value at the end of each block.
    const uint16_t* aligned_end = Align(end);
    const int increment = sizeof(uintptr_t) / sizeof(uint16_t);
    const int inner_loops = 16;
    while (chars + inner_loops * increment < aligned_end) {
      for (int i = 0; i < inner_loops; i++) {
        acc |= *reinterpret_cast<const uintptr_t*>(chars);
        chars += increment;
      }
      // Check for early return.
      if ((acc & kOneByteMask) != 0) {
        is_one_byte_ = false;
        return;
      }
    }
    // Read the rest.
    while (chars != end) {
      acc |= *chars++;
    }
    // Check result.
    if ((acc & kOneByteMask) != 0) is_one_byte_ = false;
  }
References v8::Align(), v8::internal::compiler::end(), is_one_byte_, v8::kOneByteMask, v8::internal::length, and v8::Unaligned().
Member Data Documentation
is_one_byte_
bool v8::ContainsOnlyOneByteHelper::is_one_byte_ [private]
Definition at line 5677 of file api.cc.
Referenced by Check(), CheckCons(), and VisitTwoByteString().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/api/api.cc