v8::internal::Malloced Class Reference
#include <allocation.h>
Static Public Member Functions
static void * operator new (size_t size)
static void operator delete (void *p)
Detailed Description
Definition at line 32 of file allocation.h.
Member Function Documentation
operator delete()
void v8::internal::Malloced::operator delete (void * p) [static]
Definition at line 104 of file allocation.cc.
{ base::Free(p); }
References v8::base::Free().
operator new()
void * v8::internal::Malloced::operator new (size_t size) [static]
Definition at line 96 of file allocation.cc.
                                        {
  void* result = AllocWithRetry(size);
  if (V8_UNLIKELY(result == nullptr)) {
    V8::FatalProcessOutOfMemory(nullptr, "Malloced operator new");
  }
  return result;
}
References v8::internal::AllocWithRetry(), v8::internal::V8::FatalProcessOutOfMemory(), v8::base::internal::result, size(), and V8_UNLIKELY.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/utils/allocation.h
/mnt/V8SourceCode/src/utils/allocation.cc