v8_inspector::anonymous_namespace{value-mirror.cc}::NumberMirror Class Reference
Public Member Functions
NumberMirror (v8::Isolate *isolate, v8::Local< v8::Number > value)
Response buildRemoteObject (v8::Local< v8::Context > context, const WrapOptions &wrapOptions, std::unique_ptr< RemoteObject > *result) const override
void buildPropertyPreview (v8::Local< v8::Context > context, const String16 &name, std::unique_ptr< PropertyPreview > *result) const override
void buildEntryPreview (v8::Local< v8::Context > context, int *nameLimit, int *indexLimit, std::unique_ptr< ObjectPreview > *preview) const override
Response buildDeepSerializedValue (v8::Local< v8::Context > context, int maxDepth, v8::Local< v8::Object > additionalParameters, V8SerializationDuplicateTracker &duplicateTracker, std::unique_ptr< protocol::DictionaryValue > *result) const override
Additional Inherited Members
Detailed Description
Definition at line 603 of file value-mirror.cc.
Constructor & Destructor Documentation
NumberMirror()
v8_inspector::anonymous_namespace{value-mirror.cc}::NumberMirror::NumberMirror (v8::Isolate * isolate, v8::Local< v8::Number > value) [inline]
Definition at line 605 of file value-mirror.cc.
      : ValueMirrorBase(isolate, value) {}
Member Function Documentation
buildDeepSerializedValue()
Response v8_inspector::anonymous_namespace{value-mirror.cc}::NumberMirror::buildDeepSerializedValue (v8::Local< v8::Context > context, int maxDepth, v8::Local< v8::Object > additionalParameters, V8SerializationDuplicateTracker & duplicateTracker, std::unique_ptr< protocol::DictionaryValue > * result) const [inline], [override], [virtual]
Implements v8_inspector::ValueMirror.
Definition at line 653 of file value-mirror.cc.
                                                                     {
    *result = protocol::DictionaryValue::create();
    (*result)->setString(
        "type", protocol::Runtime::DeepSerializedValue::TypeEnum::Number);
    v8::Local<v8::Number> value =
        v8Value(v8::Isolate::GetCurrent()).As<v8::Number>();
    bool unserializable = false;
    String16 descriptionValue = descriptionForNumber(value, &unserializable);
    if (unserializable) {
      (*result)->setValue("value",
                          protocol::StringValue::create(descriptionValue));
    } else {
      (*result)->setValue("value", toProtocolValue(value->Value()));
    }
    return Response::Success();
  }
References v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForNumber(), v8::Isolate::GetCurrent(), v8::base::internal::result, v8_inspector::toProtocolValue(), and v8::internal::value.
buildEntryPreview()
void v8_inspector::anonymous_namespace{value-mirror.cc}::NumberMirror::buildEntryPreview (v8::Local< v8::Context > context, int * nameLimit, int * indexLimit, std::unique_ptr< ObjectPreview > * preview) const [inline], [override]
Definition at line 638 of file value-mirror.cc.
                                                            {
    v8::Local<v8::Number> value =
        v8Value(v8::Isolate::GetCurrent()).As<v8::Number>();
    bool unserializable = false;
    *preview =
        ObjectPreview::create()
            .setType(RemoteObject::TypeEnum::Number)
            .setDescription(descriptionForNumber(value, &unserializable))
            .setOverflow(false)
            .setProperties(std::make_unique<protocol::Array<PropertyPreview>>())
            .build();
  }
References v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForNumber(), v8::Isolate::GetCurrent(), and v8::internal::value.
buildPropertyPreview()
void v8_inspector::anonymous_namespace{value-mirror.cc}::NumberMirror::buildPropertyPreview (v8::Local< v8::Context > context, const String16 & name, std::unique_ptr< PropertyPreview > * result) const [inline], [override]
Definition at line 626 of file value-mirror.cc.
                                                             {
    v8::Local<v8::Number> value =
        v8Value(v8::Isolate::GetCurrent()).As<v8::Number>();
    bool unserializable = false;
    *result = PropertyPreview::create()
                  .setName(name)
                  .setType(RemoteObject::TypeEnum::Number)
                  .setValue(descriptionForNumber(value, &unserializable))
                  .build();
  }
References v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForNumber(), v8::Isolate::GetCurrent(), name, v8::base::internal::result, and v8::internal::value.
buildRemoteObject()
Response v8_inspector::anonymous_namespace{value-mirror.cc}::NumberMirror::buildRemoteObject (v8::Local< v8::Context > context, const WrapOptions & wrapOptions, std::unique_ptr< RemoteObject > * result) const [inline], [override]
Definition at line 608 of file value-mirror.cc.
                                                          {
    v8::Local<v8::Number> value =
        v8Value(v8::Isolate::GetCurrent()).As<v8::Number>();
    bool unserializable = false;
    String16 descriptionValue = descriptionForNumber(value, &unserializable);
    *result = RemoteObject::create()
                  .setType(RemoteObject::TypeEnum::Number)
                  .setDescription(descriptionValue)
                  .build();
    if (unserializable) {
      (*result)->setUnserializableValue(descriptionValue);
    } else {
      (*result)->setValue(protocol::FundamentalValue::create(value->Value()));
    }
    return Response::Success();
  }
References v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForNumber(), v8::Isolate::GetCurrent(), v8::base::internal::result, and v8::internal::value.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/inspector/value-mirror.cc