v8::DelayedTasksPlatform Class Reference
Classes
class DelayedIdleTask
class DelayedJob
class DelayedTask
class DelayedTaskRunner
Public Member Functions
DelayedTasksPlatform (std::unique_ptr< Platform > platform)
DelayedTasksPlatform (std::unique_ptr< Platform > platform, int64_t random_seed)
DelayedTasksPlatform (const DelayedTasksPlatform &)=delete
DelayedTasksPlatform & operator= (const DelayedTasksPlatform &)=delete
~DelayedTasksPlatform () override
PageAllocator * GetPageAllocator () override
Allows the embedder to manage memory page allocations.
void OnCriticalMemoryPressure () override
Enables the embedder to respond in cases where V8 can't allocate large blocks of memory.
std::shared_ptr< TaskRunner > GetForegroundTaskRunner (v8::Isolate *isolate, TaskPriority priority) override
Returns a TaskRunner with a specific |priority| which can be used to post a task on the foreground thread.
int NumberOfWorkerThreads () override
Gets the max number of worker threads that may be used to execute concurrent work scheduled for any single TaskPriority by Call(BlockingTask)OnWorkerThread() or PostJob().
void PostTaskOnWorkerThreadImpl (TaskPriority priority, std::unique_ptr< Task > task, const SourceLocation &location) override
Schedules a task with |priority| to be invoked on a worker thread.
void PostDelayedTaskOnWorkerThreadImpl (TaskPriority priority, std::unique_ptr< Task > task, double delay_in_seconds, const SourceLocation &location) override
Schedules a task with |priority| to be invoked on a worker thread after |delay_in_seconds| expires.
bool IdleTasksEnabled (Isolate *isolate) override
Returns true if idle tasks are enabled for the given |isolate|.
std::unique_ptr< JobHandle > CreateJobImpl (TaskPriority priority, std::unique_ptr< JobTask > job_task, const SourceLocation &location) override
Creates and returns a JobHandle associated with a Job.
double MonotonicallyIncreasingTime () override
Monotonically increasing time in seconds from an arbitrary fixed point in the past.
double CurrentClockTimeMillis () override
This function is deprecated and will be deleted.
v8::TracingController * GetTracingController () override
Returns an instance of a v8::TracingController.
v8::ThreadIsolatedAllocator * GetThreadIsolatedAllocator () override
Allows the embedder to provide an allocator that uses per-thread memory permissions to protect allocations.
Private Member Functions
int32_t GetRandomDelayInMilliseconds ()
std::unique_ptr< Task > MakeDelayedTask (std::unique_ptr< Task > task)
std::unique_ptr< IdleTask > MakeDelayedIdleTask (std::unique_ptr< IdleTask > task)
std::unique_ptr< JobTask > MakeDelayedJob (std::unique_ptr< JobTask > task)
Private Attributes
std::unique_ptr< Platform > platform_
base::Mutex mutex_
base::RandomNumberGenerator rng_
std::unordered_map< TaskRunner *, std::weak_ptr< DelayedTaskRunner > > delayed_task_runners_
Additional Inherited Members
Detailed Description
Definition at line 121 of file d8-platforms.cc.
Constructor & Destructor Documentation
DelayedTasksPlatform() [1/3]
v8::DelayedTasksPlatform::DelayedTasksPlatform (std::unique_ptr< Platform > platform) [inline], [explicit]
Definition at line 123 of file d8-platforms.cc.
      : platform_(std::move(platform)) {
    DCHECK_NOT_NULL(platform_);
  }
References DCHECK_NOT_NULL, and platform_.
DelayedTasksPlatform() [2/3]
v8::DelayedTasksPlatform::DelayedTasksPlatform (std::unique_ptr< Platform > platform, int64_t random_seed) [inline], [explicit]
Definition at line 128 of file d8-platforms.cc.
      : platform_(std::move(platform)), rng_(random_seed) {
    DCHECK_NOT_NULL(platform_);
  }
References DCHECK_NOT_NULL, and platform_.
DelayedTasksPlatform() [3/3]
v8::DelayedTasksPlatform::DelayedTasksPlatform (const DelayedTasksPlatform &) [delete]
 DelayedTasksPlatform()
v8::DelayedTasksPlatform::~DelayedTasksPlatform () [inline], [override]
Definition at line 137 of file d8-platforms.cc.
                                   {
    // When the platform shuts down, all task runners must be freed.
    DCHECK_EQ(0, delayed_task_runners_.size());
  }
References DCHECK_EQ, and delayed_task_runners_.
Member Function Documentation
CreateJobImpl()
std::unique_ptr<JobHandle> v8::DelayedTasksPlatform::CreateJobImpl (TaskPriority priority, std::unique_ptr< JobTask > job_task, const SourceLocation & location) [inline], [override], [virtual]
Creates and returns a JobHandle associated with a Job.
Implements v8::Platform.
Definition at line 193 of file d8-platforms.cc.
                                               {
    return platform_->CreateJob(priority, MakeDelayedJob(std::move(job_task)),
                                location);
  }
References MakeDelayedJob(), and platform_.
CurrentClockTimeMillis()
double v8::DelayedTasksPlatform::CurrentClockTimeMillis () [inline], [override], [virtual]
This function is deprecated and will be deleted.
Use either CurrentClockTimeMilliseconds() or CurrentClockTimeMillisecondsHighResolution().
Implements v8::Platform.
Definition at line 204 of file d8-platforms.cc.
                                           {
    return platform_->CurrentClockTimeMillis();
  }
References platform_.
GetForegroundTaskRunner()
std::shared_ptr<TaskRunner> v8::DelayedTasksPlatform::GetForegroundTaskRunner (v8::Isolate * isolate, TaskPriority priority) [inline], [override], [virtual]
Returns a TaskRunner with a specific |priority| which can be used to post a task on the foreground thread.
The TaskRunner's NonNestableTasksEnabled() must be true. This function should only be called from a foreground thread.
Implements v8::Platform.
Definition at line 150 of file d8-platforms.cc.
                                                          {
    std::shared_ptr<TaskRunner> runner =
        platform_->GetForegroundTaskRunner(isolate, priority);
    base::MutexGuard lock_guard(&mutex_);
    // Check if we can re-materialize the weak ptr in our map.
    std::weak_ptr<DelayedTaskRunner>& weak_delayed_runner =
        delayed_task_runners_[runner.get()];
    std::shared_ptr<DelayedTaskRunner> delayed_runner =
        weak_delayed_runner.lock();
    if (!delayed_runner) {
      // Create a new {DelayedTaskRunner} and keep a weak reference in our map.
      delayed_runner = std::make_shared<DelayedTaskRunner>(runner, this);
      weak_delayed_runner = delayed_runner;
    }
    return std::move(delayed_runner);
  }
References delayed_task_runners_, mutex_, and platform_.
GetPageAllocator()
PageAllocator* v8::DelayedTasksPlatform::GetPageAllocator () [inline], [override], [virtual]
Allows the embedder to manage memory page allocations.
Returning nullptr will cause V8 to use the default page allocator.
Reimplemented from v8::Platform.
Definition at line 142 of file d8-platforms.cc.
                                             {
    return platform_->GetPageAllocator();
  }
References platform_.
GetRandomDelayInMilliseconds()
int32_t v8::DelayedTasksPlatform::GetRandomDelayInMilliseconds () [inline], [private]
Definition at line 331 of file d8-platforms.cc.
                                         {
    base::MutexGuard lock_guard(&mutex_);
    double delay_fraction = rng_.NextDouble();
    // Sleep up to 100ms (100000us). Square {delay_fraction} to shift
    // distribution towards shorter sleeps.
    return 1e5 * (delay_fraction * delay_fraction);
  }
References mutex_, v8::base::RandomNumberGenerator::NextDouble(), and rng_.
Referenced by MakeDelayedIdleTask(), MakeDelayedJob(), and MakeDelayedTask().
GetThreadIsolatedAllocator()
v8::ThreadIsolatedAllocator* v8::DelayedTasksPlatform::GetThreadIsolatedAllocator () [inline], [override], [virtual]
Allows the embedder to provide an allocator that uses per-thread memory permissions to protect allocations.
Returning nullptr will cause V8 to disable protections that rely on this feature.
Reimplemented from v8::Platform.
Definition at line 212 of file d8-platforms.cc.
                                                                   {
    return platform_->GetThreadIsolatedAllocator();
  }
References platform_.
GetTracingController()
v8::TracingController* v8::DelayedTasksPlatform::GetTracingController () [inline], [override], [virtual]
Returns an instance of a v8::TracingController.
This must be non-nullptr.
Implements v8::Platform.
Definition at line 208 of file d8-platforms.cc.
                                                       {
    return platform_->GetTracingController();
  }
References platform_.
IdleTasksEnabled()
bool v8::DelayedTasksPlatform::IdleTasksEnabled (Isolate * isolate) [inline], [override], [virtual]
Returns true if idle tasks are enabled for the given |isolate|.
Reimplemented from v8::Platform.
Definition at line 189 of file d8-platforms.cc.
                                                   {
    return platform_->IdleTasksEnabled(isolate);
  }
References platform_.
MakeDelayedIdleTask()
std::unique_ptr<IdleTask> v8::DelayedTasksPlatform::MakeDelayedIdleTask (std::unique_ptr< IdleTask > task) [inline], [private]
Definition at line 344 of file d8-platforms.cc.
                                    {
    return std::make_unique<DelayedIdleTask>(std::move(task),
                                             GetRandomDelayInMilliseconds());
  }
References GetRandomDelayInMilliseconds().
Referenced by v8::DelayedTasksPlatform::DelayedTaskRunner::PostIdleTaskImpl().
MakeDelayedJob()
std::unique_ptr<JobTask> v8::DelayedTasksPlatform::MakeDelayedJob (std::unique_ptr< JobTask > task) [inline], [private]
Definition at line 350 of file d8-platforms.cc.
                                                                     {
    return std::make_unique<DelayedJob>(std::move(task),
                                        GetRandomDelayInMilliseconds());
  }
References GetRandomDelayInMilliseconds().
Referenced by CreateJobImpl().
MakeDelayedTask()
std::unique_ptr<Task> v8::DelayedTasksPlatform::MakeDelayedTask (std::unique_ptr< Task > task) [inline], [private]
Definition at line 339 of file d8-platforms.cc.
                                                                {
    return std::make_unique<DelayedTask>(std::move(task),
                                         GetRandomDelayInMilliseconds());
  }
References GetRandomDelayInMilliseconds().
Referenced by v8::DelayedTasksPlatform::DelayedTaskRunner::PostDelayedTaskImpl(), PostDelayedTaskOnWorkerThreadImpl(), v8::DelayedTasksPlatform::DelayedTaskRunner::PostNonNestableTaskImpl(), v8::DelayedTasksPlatform::DelayedTaskRunner::PostTaskImpl(), and PostTaskOnWorkerThreadImpl().
MonotonicallyIncreasingTime()
double v8::DelayedTasksPlatform::MonotonicallyIncreasingTime () [inline], [override], [virtual]
Monotonically increasing time in seconds from an arbitrary fixed point in the past.
This function is expected to return at least millisecond-precision values. For this reason, it is recommended that the fixed point be no further in the past than the epoch.
Implements v8::Platform.
Definition at line 200 of file d8-platforms.cc.
                                                {
    return platform_->MonotonicallyIncreasingTime();
  }
References platform_.
NumberOfWorkerThreads()
int v8::DelayedTasksPlatform::NumberOfWorkerThreads () [inline], [override], [virtual]
Gets the max number of worker threads that may be used to execute concurrent work scheduled for any single TaskPriority by Call(BlockingTask)OnWorkerThread() or PostJob().
This can be used to estimate the number of tasks a work package should be split into. A return value of 0 means that there are no worker threads available. Note that a value of 0 won't prohibit V8 from posting tasks using |CallOnWorkerThread|.
Implements v8::Platform.
Definition at line 171 of file d8-platforms.cc.
                                       {
    return platform_->NumberOfWorkerThreads();
  }
References platform_.
OnCriticalMemoryPressure()
void v8::DelayedTasksPlatform::OnCriticalMemoryPressure () [inline], [override], [virtual]
Enables the embedder to respond in cases where V8 can't allocate large blocks of memory.
V8 retries the failed allocation once after calling this method. On success, execution continues; otherwise V8 exits with a fatal error. Embedder overrides of this function must NOT call back into V8.
Reimplemented from v8::Platform.
Definition at line 146 of file d8-platforms.cc.
                                           {
    platform_->OnCriticalMemoryPressure();
  }
References platform_.
operator=()
DelayedTasksPlatform& v8::DelayedTasksPlatform::operator= (const DelayedTasksPlatform &) [delete]
PostDelayedTaskOnWorkerThreadImpl()
void v8::DelayedTasksPlatform::PostDelayedTaskOnWorkerThreadImpl (TaskPriority priority, std::unique_ptr< Task > task, double delay_in_seconds, const SourceLocation & location) [inline], [override], [virtual]
Schedules a task with |priority| to be invoked on a worker thread after |delay_in_seconds| expires.
Implements v8::Platform.
Definition at line 182 of file d8-platforms.cc.
                                                                        {
    platform_->PostDelayedTaskOnWorkerThread(
        priority, MakeDelayedTask(std::move(task)), delay_in_seconds, location);
  }
References MakeDelayedTask(), and platform_.
PostTaskOnWorkerThreadImpl()
void v8::DelayedTasksPlatform::PostTaskOnWorkerThreadImpl (TaskPriority priority, std::unique_ptr< Task > task, const SourceLocation & location) [inline], [override], [virtual]
Schedules a task with |priority| to be invoked on a worker thread.
Implements v8::Platform.
Definition at line 175 of file d8-platforms.cc.
                                                                           {
    platform_->PostTaskOnWorkerThread(
        priority, MakeDelayedTask(std::move(task)), location);
  }
References MakeDelayedTask(), and platform_.
Member Data Documentation
delayed_task_runners_
std::unordered_map<TaskRunner*, std::weak_ptr<DelayedTaskRunner> > v8::DelayedTasksPlatform::delayed_task_runners_ [private]
Definition at line 329 of file d8-platforms.cc.
Referenced by GetForegroundTaskRunner(), v8::DelayedTasksPlatform::DelayedTaskRunner::~DelayedTaskRunner(), and ~DelayedTasksPlatform().
mutex_
base::Mutex v8::DelayedTasksPlatform::mutex_ [private]
Definition at line 326 of file d8-platforms.cc.
Referenced by GetForegroundTaskRunner(), GetRandomDelayInMilliseconds(), and v8::DelayedTasksPlatform::DelayedTaskRunner::~DelayedTaskRunner().
platform_
std::unique_ptr<Platform> v8::DelayedTasksPlatform::platform_ [private]
Definition at line 321 of file d8-platforms.cc.
Referenced by CreateJobImpl(), CurrentClockTimeMillis(), DelayedTasksPlatform(), GetForegroundTaskRunner(), GetPageAllocator(), GetThreadIsolatedAllocator(), GetTracingController(), IdleTasksEnabled(), MonotonicallyIncreasingTime(), NumberOfWorkerThreads(), OnCriticalMemoryPressure(), PostDelayedTaskOnWorkerThreadImpl(), and PostTaskOnWorkerThreadImpl().
rng_
base::RandomNumberGenerator v8::DelayedTasksPlatform::rng_ [private]
Definition at line 327 of file d8-platforms.cc.
Referenced by GetRandomDelayInMilliseconds().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/d8/d8-platforms.cc