v8::internal::wasm::AsyncStreamingDecoder::DecodeSectionLength Class Reference
Public Member Functions
DecodeSectionLength (uint8_t id, uint32_t module_offset)
std::unique_ptr< DecodingState > NextWithValue (AsyncStreamingDecoder *streaming) override
Private Attributes
const uint8_t section_id_
const uint32_t module_offset_
Additional Inherited Members
Detailed Description
Definition at line 469 of file streaming-decoder.cc.
Constructor & Destructor Documentation
DecodeSectionLength()
v8::internal::wasm::AsyncStreamingDecoder::DecodeSectionLength::DecodeSectionLength (uint8_t id, uint32_t module_offset) [inline], [explicit]
Definition at line 471 of file streaming-decoder.cc.
      : DecodeVarInt32(max_module_size(), "section length"),
        section_id_(id),
        module_offset_(module_offset) {}
Member Function Documentation
NextWithValue()
std::unique_ptr< AsyncStreamingDecoder::DecodingState > v8::internal::wasm::AsyncStreamingDecoder::DecodeSectionLength::NextWithValue (AsyncStreamingDecoder * streaming) [override], [virtual]
Implements v8::internal::wasm::AsyncStreamingDecoder::DecodeVarInt32.
Definition at line 631 of file streaming-decoder.cc.
                                      {
  TRACE_STREAMING("DecodeSectionLength(%zu)\n", value_);
  // Check if this section fits into the overall module length limit.
  // Note: {this->module_offset_} is the position of the section ID byte,
  // {streaming->module_offset_} is the start of the section's payload (i.e.
  // right after the just-decoded section length varint).
  // The latter can already exceed the max module size, when the previous
  // section barely fit into it, and this new section's ID or length crossed
  // the threshold.
  uint32_t payload_start = streaming->module_offset();
  size_t max_size = max_module_size();
  if (payload_start > max_size || max_size - payload_start < value_) {
    return streaming->ToErrorState();
  }
  SectionBuffer* buf =
      streaming->CreateNewBuffer(module_offset_, section_id_, value_,
                                 buffer().SubVector(0, bytes_consumed_));
  DCHECK_NOT_NULL(buf);
  if (value_ == 0) {
    if (section_id_ == SectionCode::kCodeSectionCode) {
      return streaming->ToErrorState();
    }
    // Process section without payload as well, to enforce section order and
    // other feature checks specific to each individual section.
    streaming->ProcessSection(buf);
    if (!streaming->ok()) return nullptr;
    // There is no payload, we go to the next section immediately.
    return std::make_unique<DecodeSectionID>(streaming->module_offset_);
  }
  if (section_id_ == SectionCode::kCodeSectionCode) {
    // We reached the code section. All functions of the code section are put
    // into the same SectionBuffer.
    return std::make_unique<DecodeNumberOfFunctions>(buf);
  }
  return std::make_unique<DecodeSectionPayload>(buf);
}
References v8::internal::wasm::AsyncStreamingDecoder::CreateNewBuffer(), DCHECK_NOT_NULL, v8::internal::wasm::kCodeSectionCode, v8::internal::wasm::max_module_size(), v8::internal::wasm::AsyncStreamingDecoder::module_offset(), v8::internal::wasm::AsyncStreamingDecoder::module_offset_, v8::internal::wasm::AsyncStreamingDecoder::ok(), v8::internal::wasm::AsyncStreamingDecoder::ProcessSection(), v8::internal::wasm::AsyncStreamingDecoder::ToErrorState(), and TRACE_STREAMING.
Member Data Documentation
module_offset_
const uint32_t v8::internal::wasm::AsyncStreamingDecoder::DecodeSectionLength::module_offset_ [private]
Definition at line 482 of file streaming-decoder.cc.
section_id_
const uint8_t v8::internal::wasm::AsyncStreamingDecoder::DecodeSectionLength::section_id_ [private]
Definition at line 480 of file streaming-decoder.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/streaming-decoder.cc