v8::internal::FeedbackIterator Class Reference
#include <feedback-vector.h>
Public Member Functions
FeedbackIterator (const FeedbackNexus *nexus)
void Advance ()
bool done ()
Tagged< Map > map ()
Tagged< MaybeObject > handler ()
Static Public Member Functions
static int SizeFor (int number_of_entries)
static int MapIndexForEntry (int entry)
static int HandlerIndexForEntry (int entry)
Static Public Attributes
static constexpr int kEntrySize = 2
static constexpr int kHandlerOffset = 1
Private Types
enum State { kMonomorphic
, kPolymorphic
, kOther
 }
Private Member Functions
void AdvancePolymorphic ()
Private Attributes
DirectHandle< WeakFixedArray > polymorphic_feedback_
Tagged< Map > map_
Tagged< MaybeObject > handler_
bool done_
int index_
State state_
Detailed Description
Definition at line 1109 of file feedback-vector.h.
Member Enumeration Documentation
State
enum v8::internal::FeedbackIterator::State [private]
Enumerator
kMonomorphic
kPolymorphic
kOther
Definition at line 1137 of file feedback-vector.h.
{ kMonomorphic, kPolymorphic, kOther };
Constructor & Destructor Documentation
FeedbackIterator()
v8::internal::FeedbackIterator::FeedbackIterator (const FeedbackNexus * nexus) [explicit]
Definition at line 1454 of file feedback-vector.cc.
    : done_(false), index_(-1), state_(kOther) {
  DCHECK(
      IsLoadICKind(nexus->kind()) || IsSetNamedICKind(nexus->kind()) ||
      IsKeyedLoadICKind(nexus->kind()) || IsKeyedStoreICKind(nexus->kind()) ||
      IsDefineNamedOwnICKind(nexus->kind()) ||
      IsDefineKeyedOwnPropertyInLiteralKind(nexus->kind()) ||
      IsStoreInArrayLiteralICKind(nexus->kind()) ||
      IsKeyedHasICKind(nexus->kind()) || IsDefineKeyedOwnICKind(nexus->kind()));
  DisallowGarbageCollection no_gc;
  auto pair = nexus->GetFeedbackPair();
  Tagged<MaybeObject> feedback = pair.first;
  bool is_named_feedback = IsPropertyNameFeedback(feedback);
  Tagged<HeapObject> heap_object;
  if ((feedback.GetHeapObjectIfStrong(&heap_object) &&
       IsWeakFixedArray(heap_object)) ||
      is_named_feedback) {
    index_ = 0;
    state_ = kPolymorphic;
    heap_object = feedback.GetHeapObjectAssumeStrong();
    if (is_named_feedback) {
      polymorphic_feedback_ = nexus->config()->NewHandle(
          Cast<WeakFixedArray>(pair.second.GetHeapObjectAssumeStrong()));
    } else {
      polymorphic_feedback_ =
          nexus->config()->NewHandle(Cast<WeakFixedArray>(heap_object));
    }
    AdvancePolymorphic();
  } else if (feedback.GetHeapObjectIfWeak(&heap_object)) {
    state_ = kMonomorphic;
    Tagged<MaybeObject> handler = pair.second;
    map_ = Cast<Map>(heap_object);
    handler_ = handler;
  } else {
    done_ = true;
  }
}
References AdvancePolymorphic(), v8::internal::FeedbackNexus::config(), v8::internal::DCHECK(), done_, v8::internal::FeedbackNexus::GetFeedbackPair(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectAssumeStrong(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectIfStrong(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectIfWeak(), handler(), handler_, index_, v8::internal::IsDefineKeyedOwnICKind(), v8::internal::IsDefineKeyedOwnPropertyInLiteralKind(), v8::internal::IsDefineNamedOwnICKind(), v8::internal::IsKeyedHasICKind(), v8::internal::IsKeyedLoadICKind(), v8::internal::IsKeyedStoreICKind(), v8::internal::IsLoadICKind(), v8::internal::IsPropertyNameFeedback(), v8::internal::IsSetNamedICKind(), v8::internal::IsStoreInArrayLiteralICKind(), v8::internal::FeedbackNexus::kind(), kMonomorphic, v8::internal::kOther, kPolymorphic, map_, v8::internal::NexusConfig::NewHandle(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, polymorphic_feedback_, and state_.
Member Function Documentation
Advance()
void v8::internal::FeedbackIterator::Advance ()
Definition at line 1494 of file feedback-vector.cc.
                               {
  CHECK(!done_);
  if (state_ == kMonomorphic) {
    done_ = true;
    return;
  }
  CHECK_EQ(state_, kPolymorphic);
  AdvancePolymorphic();
}
References AdvancePolymorphic(), CHECK, CHECK_EQ, done_, kMonomorphic, kPolymorphic, and state_.
AdvancePolymorphic()
void v8::internal::FeedbackIterator::AdvancePolymorphic () [private]
Definition at line 1506 of file feedback-vector.cc.
                                          {
  CHECK(!done_);
  CHECK_EQ(state_, kPolymorphic);
  int length = polymorphic_feedback_->length();
  Tagged<HeapObject> heap_object;
  while (index_ < length) {
    if (polymorphic_feedback_->get(index_).GetHeapObjectIfWeak(&heap_object)) {
      Tagged<MaybeObject> handler =
          polymorphic_feedback_->get(index_ + kHandlerOffset);
      map_ = Cast<Map>(heap_object);
      handler_ = handler;
      index_ += kEntrySize;
      return;
    }
    index_ += kEntrySize;
  }
  CHECK_EQ(index_, length);
  done_ = true;
}
References CHECK, CHECK_EQ, done_, handler(), handler_, index_, kEntrySize, kHandlerOffset, kPolymorphic, v8::internal::length, map_, polymorphic_feedback_, and state_.
Referenced by Advance(), and FeedbackIterator().
done()
bool v8::internal::FeedbackIterator::done () [inline]
Definition at line 1113 of file feedback-vector.h.
{ return done_; }
Referenced by v8::internal::FeedbackNexus::ExtractMaps(), v8::internal::FeedbackNexus::ExtractMapsAndHandlers(), v8::internal::FeedbackNexus::FindHandlerForMap(), v8::internal::FeedbackNexus::GetFirstMap(), v8::internal::FeedbackNexus::IterateMapsWithUnclearedHandler(), and v8::internal::IC::UpdatePolymorphicIC().
handler()
Tagged<MaybeObject> v8::internal::FeedbackIterator::handler () [inline]
Definition at line 1115 of file feedback-vector.h.
{ return handler_; }
Referenced by AdvancePolymorphic(), and FeedbackIterator().
HandlerIndexForEntry()
static int v8::internal::FeedbackIterator::HandlerIndexForEntry (int entry) [inline], [static]
Definition at line 1127 of file feedback-vector.h.
                                             {
    CHECK_GE(entry, 0);
    return (entry * kEntrySize) + kHandlerOffset;
  }
References CHECK_GE, and cppgc::internal::anonymous_namespace{gc-info-table.cc}::kEntrySize.
map()
Tagged<Map> v8::internal::FeedbackIterator::map () [inline]
Definition at line 1114 of file feedback-vector.h.
{ return map_; }
Referenced by v8::internal::FeedbackNexus::GetFirstMap().
MapIndexForEntry()
static int v8::internal::FeedbackIterator::MapIndexForEntry (int entry) [inline], [static]
Definition at line 1122 of file feedback-vector.h.
                                         {
    CHECK_GE(entry, 0);
    return entry * kEntrySize;
  }
References CHECK_GE, and cppgc::internal::anonymous_namespace{gc-info-table.cc}::kEntrySize.
SizeFor()
static int v8::internal::FeedbackIterator::SizeFor (int number_of_entries) [inline], [static]
Definition at line 1117 of file feedback-vector.h.
                                            {
    CHECK_GT(number_of_entries, 0);
    return number_of_entries * kEntrySize;
  }
References CHECK_GT, and cppgc::internal::anonymous_namespace{gc-info-table.cc}::kEntrySize.
Member Data Documentation
done_
bool v8::internal::FeedbackIterator::done_ [private]
Definition at line 1142 of file feedback-vector.h.
Referenced by Advance(), AdvancePolymorphic(), and FeedbackIterator().
handler_
Tagged<MaybeObject> v8::internal::FeedbackIterator::handler_ [private]
Definition at line 1141 of file feedback-vector.h.
Referenced by AdvancePolymorphic(), and FeedbackIterator().
index_
int v8::internal::FeedbackIterator::index_ [private]
Definition at line 1143 of file feedback-vector.h.
Referenced by AdvancePolymorphic(), and FeedbackIterator().
kEntrySize
constexpr int v8::internal::FeedbackIterator::kEntrySize = 2 [static], [constexpr]
Definition at line 1132 of file feedback-vector.h.
Referenced by AdvancePolymorphic(), and v8::internal::CodeStubAssembler::FeedbackIteratorEntrySize().
kHandlerOffset
constexpr int v8::internal::FeedbackIterator::kHandlerOffset = 1 [static], [constexpr]
Definition at line 1133 of file feedback-vector.h.
Referenced by AdvancePolymorphic(), and v8::internal::CodeStubAssembler::FeedbackIteratorHandlerOffset().
map_
Tagged<Map> v8::internal::FeedbackIterator::map_ [private]
Definition at line 1140 of file feedback-vector.h.
Referenced by AdvancePolymorphic(), and FeedbackIterator().
polymorphic_feedback_
DirectHandle<WeakFixedArray> v8::internal::FeedbackIterator::polymorphic_feedback_ [private]
Definition at line 1139 of file feedback-vector.h.
Referenced by AdvancePolymorphic(), and FeedbackIterator().
state_
State v8::internal::FeedbackIterator::state_ [private]
Definition at line 1144 of file feedback-vector.h.
Referenced by Advance(), AdvancePolymorphic(), and FeedbackIterator().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/feedback-vector.h
/mnt/V8SourceCode/src/objects/feedback-vector.cc