v8::internal::EnsureSpace Class Reference
#include <assembler-arm.h>
Public Member Functions
EnsureSpace (Assembler *assembler)
EnsureSpace (Assembler *assembler)
EnsureSpace (Assembler *assembler)
EnsureSpace (Assembler *assembler)
EnsureSpace (Assembler *assembler)
EnsureSpace (Assembler *assembler)
EnsureSpace (Assembler *assembler)
EnsureSpace (Assembler *assembler)
EnsureSpace (Assembler *assembler)
Private Attributes
Assembler::BlockPoolsScope block_pools_scope_
Assembler *const assembler_
Detailed Description
Definition at line 1368 of file assembler-arm.h.
Constructor & Destructor Documentation
EnsureSpace() [1/9]
v8::internal::EnsureSpace::EnsureSpace (Assembler * assembler) [inline], [explicit]
Definition at line 354 of file assembler-arm-inl.h.
{ assembler->CheckBuffer(); }
References v8::internal::Assembler::CheckBuffer().
EnsureSpace() [2/9]
v8::internal::EnsureSpace::EnsureSpace (Assembler * assembler) [inline], [explicit]
EnsureSpace() [3/9]
v8::internal::EnsureSpace::EnsureSpace (Assembler * assembler) [inline], [explicit]
Definition at line 1818 of file assembler-ia32.h.
                                                       : assembler_(assembler) {
    if (V8_UNLIKELY(assembler_->buffer_overflow())) assembler_->GrowBuffer();
#ifdef DEBUG
    space_before_ = assembler->available_space();
#endif
  }
References assembler_, v8::internal::Assembler::available_space(), v8::internal::Assembler::buffer_overflow(), v8::internal::Assembler::GrowBuffer(), and V8_UNLIKELY.
EnsureSpace() [4/9]
v8::internal::EnsureSpace::EnsureSpace (Assembler * assembler) [inline], [explicit]
EnsureSpace() [5/9]
v8::internal::EnsureSpace::EnsureSpace (Assembler * assembler) [inline], [explicit]
EnsureSpace() [6/9]
v8::internal::EnsureSpace::EnsureSpace (Assembler * assembler) [inline], [explicit]
Definition at line 1538 of file assembler-ppc.h.
{ assembler->CheckBuffer(); }
References v8::internal::Assembler::CheckBuffer().
EnsureSpace() [7/9]
v8::internal::EnsureSpace::EnsureSpace (Assembler * assembler) [inline], [explicit]
EnsureSpace() [8/9]
v8::internal::EnsureSpace::EnsureSpace (Assembler * assembler) [inline], [explicit]
Definition at line 1476 of file assembler-s390.h.
{ assembler->CheckBuffer(); }
References v8::internal::Assembler::CheckBuffer().
EnsureSpace() [9/9]
v8::internal::EnsureSpace::EnsureSpace (Assembler * assembler) [inline], [explicit]
Definition at line 3161 of file assembler-x64.h.
                                                       : assembler_(assembler) {
    if (V8_UNLIKELY(assembler_->buffer_overflow())) assembler_->GrowBuffer();
#ifdef DEBUG
    space_before_ = assembler_->available_space();
#endif
  }
References V8_UNLIKELY.
Member Data Documentation
assembler_
Assembler *const v8::internal::EnsureSpace::assembler_ [private]
Definition at line 1833 of file assembler-ia32.h.
Referenced by EnsureSpace().
block_pools_scope_
Assembler::BlockPoolsScope v8::internal::EnsureSpace::block_pools_scope_ [private]
Definition at line 3524 of file assembler-arm64.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/arm/assembler-arm.h
/mnt/V8SourceCode/src/codegen/arm64/assembler-arm64.h
/mnt/V8SourceCode/src/codegen/ia32/assembler-ia32.h
/mnt/V8SourceCode/src/codegen/x64/assembler-x64.h
/mnt/V8SourceCode/src/codegen/loong64/assembler-loong64.h
/mnt/V8SourceCode/src/codegen/mips64/assembler-mips64.h
/mnt/V8SourceCode/src/codegen/ppc/assembler-ppc.h
/mnt/V8SourceCode/src/codegen/riscv/assembler-riscv.h
/mnt/V8SourceCode/src/codegen/s390/assembler-s390.h
/mnt/V8SourceCode/src/codegen/arm/assembler-arm-inl.h
/mnt/V8SourceCode/src/codegen/arm64/assembler-arm64-inl.h
/mnt/V8SourceCode/src/codegen/loong64/assembler-loong64-inl.h
/mnt/V8SourceCode/src/codegen/mips64/assembler-mips64-inl.h
/mnt/V8SourceCode/src/codegen/riscv/assembler-riscv-inl.h