v8::internal::maglev::NodeBase Class Reference
#include <maglev-ir.h>
Classes
struct OwnerOrTemporaries
Public Types
enum class InputAllocationPolicy { kFixedRegister
, kArbitraryRegister
, kAny
 }
Public Member Functions
constexpr Opcode opcode () const
constexpr OpProperties properties () const
void set_properties (OpProperties properties)
void set_input (int index, ValueNode *node)
template<class T >
constexpr bool Is () const
template<class T >
constexpr T * Cast ()
template<class T >
constexpr const T * Cast () const
template<class T >
constexpr T * TryCast ()
template<class T >
constexpr const T * TryCast () const
constexpr bool has_inputs () const
constexpr int input_count () const
constexpr Input & input (int index)
constexpr const Input & input (int index) const
std::optional< int32_t > TryGetInt32ConstantInput (int index)
constexpr auto begin ()
constexpr auto end ()
constexpr bool has_id () const
constexpr NodeIdT id () const
void set_id (NodeIdT id)
template<typename RegisterT >
uint8_t num_temporaries_needed () const
template<typename RegisterT >
RegListBase< RegisterT > & temporaries ()
RegList & general_temporaries ()
DoubleRegList & double_temporaries ()
template<typename RegisterT >
void assign_temporaries (RegListBase< RegisterT > list)
template<typename Function >
void ForAllInputsInRegallocAssignmentOrder (Function &&f)
void Print (std::ostream &os, MaglevGraphLabeller *, bool skip_targets=false) const
void Print () const
EagerDeoptInfo * eager_deopt_info ()
LazyDeoptInfo * lazy_deopt_info ()
const RegisterSnapshot & register_snapshot () const
ExceptionHandlerInfo * exception_handler_info ()
void set_register_snapshot (RegisterSnapshot snapshot)
void change_input (int index, ValueNode *node)
void change_representation (ValueRepresentation new_repr)
void set_opcode (Opcode new_opcode)
void CopyEagerDeoptInfoOf (NodeBase *other, Zone *zone)
void SetEagerDeoptInfo (Zone *zone, DeoptFrame deopt_frame, compiler::FeedbackSource feedback_to_update=compiler::FeedbackSource())
template<typename NodeT >
void OverwriteWith ()
void OverwriteWith (Opcode new_opcode, std::optional< OpProperties > maybe_new_properties=std::nullopt)
void OverwriteWithIdentityTo (ValueNode *node)
auto options () const
void ClearUnstableNodeAspects (KnownNodeAspects &)
void ClearElementsProperties (KnownNodeAspects &)
void set_owner (BasicBlock *block)
BasicBlock * owner () const
void InitTemporaries ()
template<> constexpr bool Is () const
template<> constexpr bool Is () const
template<> constexpr bool Is () const
template<> constexpr bool Is () const
template<> constexpr bool Is () const
template<> constexpr bool Is () const
Static Public Member Functions
template<class Derived , typename... Args>
static Derived * New (Zone *zone, std::initializer_list< ValueNode * > inputs, Args &&... args)
template<class Derived , typename... Args>
static Derived * New (Zone *zone, size_t input_count, Args &&... args)
Static Public Attributes
template<class T >
static constexpr Opcode opcode_of = detail::opcode_of_helper<T>::value
static constexpr OpProperties kProperties
Protected Types
using ReservedField = InputCountField::Next< bool, 1 >
template<class T , int size>
using NextBitField = ReservedField::Next< T, size >
Protected Member Functions
NodeBase (uint64_t bitfield)
constexpr uint64_t bitfield () const
void set_bitfield (uint64_t new_bitfield)
constexpr Input * input_base ()
constexpr const Input * input_base () const
Input * last_input ()
const Input * last_input () const
Address last_input_address () const
void initialize_input_null (int index)
void reduce_input_count (int num=1)
void set_temporaries_needed (uint8_t value)
void set_double_temporaries_needed (uint8_t value)
void RequireSpecificTemporary (Register reg)
void RequireSpecificDoubleTemporary (DoubleRegister reg)
Static Protected Attributes
static constexpr int kMaxInputs = InputCountField::kMax
Private Types
using OpcodeField = base::BitField64< Opcode, 0, 16 >
using OpPropertiesField = OpcodeField::Next< OpProperties, OpProperties::kSize >
using NumTemporariesNeededField = OpPropertiesField::Next< uint8_t, 2 >
using NumDoubleTemporariesNeededField = NumTemporariesNeededField::Next< uint8_t, 1 >
using InputCountField = NumDoubleTemporariesNeededField::Next< size_t, 17 >
Private Member Functions
Address deopt_info_address () const
Address register_snapshot_address () const
Address exception_handler_address () const
void CheckCanOverwriteWith (Opcode new_opcode, OpProperties new_properties)
NodeBase ()=delete
NodeBase (const NodeBase &)=delete
NodeBase (NodeBase &&)=delete
NodeBase & operator= (const NodeBase &)=delete
NodeBase & operator= (NodeBase &&)=delete
Static Private Member Functions
template<class Derived , typename... Args>
static Derived * Allocate (Zone *zone, size_t input_count, Args &&... args)
static constexpr size_t ExceptionHandlerInfoSize (OpProperties properties)
static constexpr size_t RegisterSnapshotSize (OpProperties properties)
static constexpr size_t EagerDeoptInfoSize (OpProperties properties)
static constexpr size_t LazyDeoptInfoSize (OpProperties properties)
Private Attributes
uint64_t bitfield_
NodeIdT id_ = kInvalidNodeId
OwnerOrTemporaries owner_or_temporaries_
Detailed Description
Definition at line 2083 of file maglev-ir.h.
Member Typedef Documentation
InputCountField
using v8::internal::maglev::NodeBase::InputCountField = NumDoubleTemporariesNeededField::Next<size_t, 17> [private]
Definition at line 2093 of file maglev-ir.h.
NextBitField
template<class T , int size>
using v8::internal::maglev::NodeBase::NextBitField = ReservedField::Next<T, size> [protected]
Definition at line 2101 of file maglev-ir.h.
NumDoubleTemporariesNeededField
using v8::internal::maglev::NodeBase::NumDoubleTemporariesNeededField = NumTemporariesNeededField::Next<uint8_t, 1> [private]
Definition at line 2091 of file maglev-ir.h.
NumTemporariesNeededField
using v8::internal::maglev::NodeBase::NumTemporariesNeededField = OpPropertiesField::Next<uint8_t, 2> [private]
Definition at line 2090 of file maglev-ir.h.
OpcodeField
using v8::internal::maglev::NodeBase::OpcodeField = base::BitField64<Opcode, 0, 16> [private]
Definition at line 2086 of file maglev-ir.h.
OpPropertiesField
using v8::internal::maglev::NodeBase::OpPropertiesField = OpcodeField::Next<OpProperties, OpProperties::kSize> [private]
Definition at line 2088 of file maglev-ir.h.
ReservedField
using v8::internal::maglev::NodeBase::ReservedField = InputCountField::Next<bool, 1> [protected]
Definition at line 2098 of file maglev-ir.h.
Member Enumeration Documentation
InputAllocationPolicy
enum v8::internal::maglev::NodeBase::InputAllocationPolicy [strong]
Enumerator
kFixedRegister
kArbitraryRegister
kAny
Definition at line 2230 of file maglev-ir.h.
{ kFixedRegister, kArbitraryRegister, kAny };
Constructor & Destructor Documentation
NodeBase() [1/4]
v8::internal::maglev::NodeBase::NodeBase (uint64_t bitfield) [inline], [explicit], [protected]
Definition at line 2334 of file maglev-ir.h.
: bitfield_(bitfield) {}
NodeBase() [2/4]
v8::internal::maglev::NodeBase::NodeBase () [private], [delete]
NodeBase() [3/4]
v8::internal::maglev::NodeBase::NodeBase (const NodeBase &) [private], [delete]
NodeBase() [4/4]
v8::internal::maglev::NodeBase::NodeBase (NodeBase &&) [private], [delete]
Member Function Documentation
Allocate()
template<class Derived , typename... Args>
static Derived* v8::internal::maglev::NodeBase::Allocate (Zone * zone, size_t input_count, Args &&... args) [inline], [static], [private]
Definition at line 2403 of file maglev-ir.h.
                                                                           {
    static_assert(
        !Derived::kProperties.can_eager_deopt() ||
            !Derived::kProperties.can_lazy_deopt(),
        "The current deopt info representation, at the end of inputs, requires "
        "that we cannot have both lazy and eager deopts on a node. If we ever "
        "need this, we have to update accessors to check node->properties() "
        "for which deopts are active.");
    constexpr size_t size_before_inputs =
        ExceptionHandlerInfoSize(Derived::kProperties) +
        RegisterSnapshotSize(Derived::kProperties) +
        EagerDeoptInfoSize(Derived::kProperties) +
        LazyDeoptInfoSize(Derived::kProperties);
    static_assert(IsAligned(size_before_inputs, alignof(Input)));
    const size_t size_before_node =
        size_before_inputs + input_count * sizeof(Input);
    DCHECK(IsAligned(size_before_inputs, alignof(Derived)));
    const size_t size = size_before_node + sizeof(Derived);
    intptr_t raw_buffer =
        reinterpret_cast<intptr_t>(zone->Allocate<NodeWithInlineInputs>(size));
#ifdef DEBUG
    memset(reinterpret_cast<void*>(raw_buffer), 0, size);
#endif
    void* node_buffer = reinterpret_cast<void*>(raw_buffer + size_before_node);
    uint64_t bitfield = OpcodeField::encode(opcode_of<Derived>) |
                        OpPropertiesField::encode(Derived::kProperties) |
                        InputCountField::encode(input_count);
    Derived* node =
        new (node_buffer) Derived(bitfield, std::forward<Args>(args)...);
    return node;
  }
References v8::internal::Zone::Allocate(), v8::base::args, bitfield(), v8::internal::DCHECK(), EagerDeoptInfoSize(), v8::base::BitField< T, shift, size, U >::encode(), ExceptionHandlerInfoSize(), input_count(), IsAligned(), LazyDeoptInfoSize(), RegisterSnapshotSize(), and size().
assign_temporaries()
template<typename RegisterT >
void v8::internal::maglev::NodeBase::assign_temporaries (RegListBase< RegisterT > list) [inline]
Definition at line 2226 of file maglev-ir.h.
                                                       {
    owner_or_temporaries_.temporaries<RegisterT>() = list;
  }
References owner_or_temporaries_, and v8::internal::maglev::NodeBase::OwnerOrTemporaries::temporaries().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AssignArbitraryTemporaries().
begin()
constexpr auto v8::internal::maglev::NodeBase::begin () [inline], [constexpr]
Definition at line 2193 of file maglev-ir.h.
{ return std::make_reverse_iterator(&input(-1)); }
References input().
bitfield()
constexpr uint64_t v8::internal::maglev::NodeBase::bitfield () const [inline], [constexpr], [protected]
Definition at line 2337 of file maglev-ir.h.
{ return bitfield_; }
References bitfield_.
Referenced by Allocate().
Cast() [1/2]
template<class T >
constexpr T* v8::internal::maglev::NodeBase::Cast () [inline], [constexpr]
Definition at line 2154 of file maglev-ir.h.
                      {
    DCHECK(Is<T>());
    return static_cast<T*>(this);
  }
References v8::internal::DCHECK().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNode(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters(), v8::internal::maglev::InlinedAllocation::allocation_block(), v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfRootConstant(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckNumericalValue(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadFixedArrayElement(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadFixedDoubleArrayElement(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadTaggedField(), v8::internal::maglev::MaglevGraphBuilder::CanTrackObjectChanges(), v8::internal::maglev::MaglevPhiRepresentationSelector::ConvertTaggedPhiTo(), v8::internal::maglev::MaglevPhiRepresentationSelector::FixLoopPhisBackedge(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::GetReservedRegisters(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::IsDeadNodeToSkip(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::NearestPostDominatingHole(), v8::internal::maglev::BasicBlock::predecessor_id(), v8::internal::maglev::MaglevGraphLabeller::PrintNodeLabel(), v8::internal::maglev::MaglevGraphBuilder::ReduceCallWithArrayLikeForArgumentsObject(), v8::internal::maglev::BasicBlock::set_predecessor_id(), v8::internal::maglev::MaglevGraphBuilder::TryReadBoilerplateForFastLiteral(), v8::internal::maglev::MaglevGraphBuilder::TryReduceArrayIteratingBuiltin(), v8::internal::maglev::MaglevGraphBuilder::TrySpecializeLoadContextSlot(), v8::internal::maglev::MaglevGraphBuilder::TrySpecializeStoreContextSlot(), v8::internal::maglev::KnownNodeAspects::UpdateMayHaveAliasingContexts(), v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateNodeInputs(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::VerifyIsNotEscaping(), and v8::internal::maglev::MaglevGraphBuilder::VisitCompareOperation().
Cast() [2/2]
template<class T >
constexpr const T* v8::internal::maglev::NodeBase::Cast () const [inline], [constexpr]
Definition at line 2159 of file maglev-ir.h.
                                  {
    DCHECK(Is<T>());
    return static_cast<const T*>(this);
  }
References v8::internal::DCHECK().
change_input()
void v8::internal::maglev::NodeBase::change_input (int index, ValueNode * node) [inline]
Definition at line 113 of file maglev-ir-inl.h.
                                                      {
  DCHECK_NE(input(index).node(), nullptr);
  // After the AnyUseMarkingProcessor the use count can be -1.
  if (input(index).node()->is_used()) {
    input(index).node()->remove_use();
  } else {
    DCHECK_EQ(input(index).node()->use_count(), -1);
  }
#ifdef DEBUG
  input(index) = Input(nullptr);
#endif
  set_input(index, node);
}
References DCHECK_EQ, DCHECK_NE, v8::internal::index, input(), v8::internal::maglev::Input::node(), v8::internal::maglev::ValueNode::remove_use(), and set_input().
Referenced by OverwriteWithIdentityTo(), v8::internal::maglev::SweepIdentityNodes::Process(), v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateNodePhiInput(), and v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateNonUntaggingNodeInputs().
change_representation()
void v8::internal::maglev::NodeBase::change_representation (ValueRepresentation new_repr) [inline]
Definition at line 2277 of file maglev-ir.h.
                                                           {
    DCHECK_EQ(opcode(), Opcode::kPhi);
    bitfield_ = OpPropertiesField::update(
        bitfield_, properties().WithNewValueRepresentation(new_repr));
  }
References bitfield_, DCHECK_EQ, opcode(), properties(), and v8::base::BitField< T, shift, size, U >::update().
CheckCanOverwriteWith()
void v8::internal::maglev::NodeBase::CheckCanOverwriteWith (Opcode new_opcode, OpProperties new_properties) [private]
Referenced by OverwriteWith().
ClearElementsProperties()
void v8::internal::maglev::NodeBase::ClearElementsProperties (KnownNodeAspects & known_node_aspects)
Definition at line 8479 of file maglev-ir.cc.
                                                                           {
  DCHECK(IsElementsArrayWrite(opcode()));
  // Clear Elements cache.
  auto elements_properties = known_node_aspects.loaded_properties.find(
      KnownNodeAspects::LoadedPropertyMapKey::Elements());
  if (elements_properties != known_node_aspects.loaded_properties.end()) {
    elements_properties->second.clear();
    if (v8_flags.trace_maglev_graph_building) {
      std::cout << " * Removing non-constant cached [Elements]";
    }
  }
}
References v8::internal::DCHECK(), v8::internal::maglev::KnownNodeAspects::LoadedPropertyMapKey::Elements(), v8::internal::maglev::IsElementsArrayWrite(), v8::internal::maglev::KnownNodeAspects::loaded_properties, opcode(), and v8::internal::v8_flags.
ClearUnstableNodeAspects()
void v8::internal::maglev::NodeBase::ClearUnstableNodeAspects (KnownNodeAspects & known_node_aspects)
Definition at line 8492 of file maglev-ir.cc.
                                                                            {
  DCHECK(properties().can_write());
  DCHECK(!IsSimpleFieldStore(opcode()));
  DCHECK(!IsElementsArrayWrite(opcode()));
  known_node_aspects.ClearUnstableNodeAspects();
}
References v8::internal::maglev::KnownNodeAspects::ClearUnstableNodeAspects(), v8::internal::DCHECK(), v8::internal::maglev::IsElementsArrayWrite(), v8::internal::maglev::IsSimpleFieldStore(), opcode(), and properties().
CopyEagerDeoptInfoOf()
void v8::internal::maglev::NodeBase::CopyEagerDeoptInfoOf (NodeBase * other, Zone * zone) [inline]
Definition at line 2287 of file maglev-ir.h.
                                                         {
    new (eager_deopt_info())
        EagerDeoptInfo(zone, other->eager_deopt_info()->top_frame(),
                       other->eager_deopt_info()->feedback_to_update());
  }
References eager_deopt_info(), v8::internal::maglev::DeoptInfo::feedback_to_update(), and v8::internal::maglev::DeoptInfo::top_frame().
deopt_info_address()
Address v8::internal::maglev::NodeBase::deopt_info_address () const [inline], [private]
Definition at line 2462 of file maglev-ir.h.
                                     {
    DCHECK(!properties().can_eager_deopt() || !properties().can_lazy_deopt());
    size_t extra =
        EagerDeoptInfoSize(properties()) + LazyDeoptInfoSize(properties());
    return last_input_address() - extra;
  }
References v8::internal::DCHECK(), EagerDeoptInfoSize(), last_input_address(), LazyDeoptInfoSize(), and properties().
Referenced by eager_deopt_info(), lazy_deopt_info(), and register_snapshot_address().
double_temporaries()
DoubleRegList& v8::internal::maglev::NodeBase::double_temporaries () [inline]
Definition at line 2223 of file maglev-ir.h.
{ return temporaries<DoubleRegister>(); }
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateControlNode(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNode(), and RequireSpecificDoubleTemporary().
eager_deopt_info()
EagerDeoptInfo* v8::internal::maglev::NodeBase::eager_deopt_info () [inline]
Definition at line 2246 of file maglev-ir.h.
                                     {
    DCHECK(properties().can_eager_deopt() ||
           properties().is_deopt_checkpoint());
    DCHECK(!properties().can_lazy_deopt());
    return reinterpret_cast<EagerDeoptInfo*>(deopt_info_address());
  }
References v8::internal::DCHECK(), deopt_info_address(), and properties().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateControlNode(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNode(), CopyEagerDeoptInfoOf(), v8::internal::maglev::SweepIdentityNodes::Process(), v8::internal::maglev::StraightForwardRegisterAllocator::SaveRegisterSnapshot(), and SetEagerDeoptInfo().
EagerDeoptInfoSize()
static constexpr size_t v8::internal::maglev::NodeBase::EagerDeoptInfoSize (OpProperties properties) [inline], [static], [constexpr], [private]
Definition at line 2448 of file maglev-ir.h.
                                                                      {
    return RoundUp<alignof(Input)>(
        (properties.can_eager_deopt() || properties.is_deopt_checkpoint())
            ? sizeof(EagerDeoptInfo)
            : 0);
  }
References v8::internal::maglev::OpProperties::can_eager_deopt(), v8::internal::maglev::OpProperties::is_deopt_checkpoint(), and properties().
Referenced by Allocate(), and deopt_info_address().
end()
constexpr auto v8::internal::maglev::NodeBase::end () [inline], [constexpr]
Definition at line 2194 of file maglev-ir.h.
                       {
    return std::make_reverse_iterator(&input(input_count() - 1));
  }
References input(), and input_count().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNode().
exception_handler_address()
Address v8::internal::maglev::NodeBase::exception_handler_address () const [inline], [private]
Definition at line 2478 of file maglev-ir.h.
                                            {
    size_t extra = ExceptionHandlerInfoSize(properties());
    return register_snapshot_address() - extra;
  }
References ExceptionHandlerInfoSize(), properties(), and register_snapshot_address().
Referenced by exception_handler_info().
exception_handler_info()
ExceptionHandlerInfo* v8::internal::maglev::NodeBase::exception_handler_info () [inline]
Definition at line 2264 of file maglev-ir.h.
                                                 {
    DCHECK(properties().can_throw());
    return reinterpret_cast<ExceptionHandlerInfo*>(exception_handler_address());
  }
References v8::internal::DCHECK(), exception_handler_address(), and properties().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNode(), v8::internal::maglev::MaglevAssembler::DefineExceptionHandlerPoint(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::EmitTrampolineFor(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ThrowingScope::ThrowingScope().
ExceptionHandlerInfoSize()
static constexpr size_t v8::internal::maglev::NodeBase::ExceptionHandlerInfoSize (OpProperties properties) [inline], [static], [constexpr], [private]
Definition at line 2438 of file maglev-ir.h.
                                                                            {
    return RoundUp<alignof(Input)>(
        properties.can_throw() ? sizeof(ExceptionHandlerInfo) : 0);
  }
References v8::internal::maglev::OpProperties::can_throw(), and properties().
Referenced by Allocate(), and exception_handler_address().
ForAllInputsInRegallocAssignmentOrder()
template<typename Function >
void v8::internal::maglev::NodeBase::ForAllInputsInRegallocAssignmentOrder (Function && f) [inline]
Definition at line 11862 of file maglev-ir.h.
                                                                        {
  auto iterate_inputs = [&](InputAllocationPolicy category) {
    for (Input& input : *this) {
      switch (compiler::UnallocatedOperand::cast(input.operand())
                  .extended_policy()) {
        case compiler::UnallocatedOperand::MUST_HAVE_REGISTER:
          if (category == InputAllocationPolicy::kArbitraryRegister)
            f(category, &input);
          break;
        case compiler::UnallocatedOperand::REGISTER_OR_SLOT_OR_CONSTANT:
          if (category == InputAllocationPolicy::kAny) f(category, &input);
          break;
        case compiler::UnallocatedOperand::FIXED_REGISTER:
        case compiler::UnallocatedOperand::FIXED_FP_REGISTER:
          if (category == InputAllocationPolicy::kFixedRegister)
            f(category, &input);
          break;
        case compiler::UnallocatedOperand::REGISTER_OR_SLOT:
        case compiler::UnallocatedOperand::SAME_AS_INPUT:
        case compiler::UnallocatedOperand::NONE:
        case compiler::UnallocatedOperand::MUST_HAVE_SLOT:
          UNREACHABLE();
      }
    }
  };
  iterate_inputs(InputAllocationPolicy::kFixedRegister);
  iterate_inputs(InputAllocationPolicy::kArbitraryRegister);
  iterate_inputs(InputAllocationPolicy::kAny);
}
References v8::internal::NONE, v8::internal::maglev::ValueLocation::operand(), and UNREACHABLE.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters().
general_temporaries()
RegList& v8::internal::maglev::NodeBase::general_temporaries () [inline]
Definition at line 2222 of file maglev-ir.h.
{ return temporaries<Register>(); }
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateControlNode(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNode(), and RequireSpecificTemporary().
has_id()
constexpr bool v8::internal::maglev::NodeBase::has_id () const [inline], [constexpr]
Definition at line 2198 of file maglev-ir.h.
{ return id_ != kInvalidNodeId; }
References id_, and v8::internal::maglev::kInvalidNodeId.
Referenced by v8::internal::maglev::MaglevGraphLabeller::PrintNodeLabel(), v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::PrintResult(), v8::internal::maglev::ValueNode::SetHint(), and v8::internal::maglev::ValueNode::use_count().
has_inputs()
constexpr bool v8::internal::maglev::NodeBase::has_inputs () const [inline], [constexpr]
Definition at line 2173 of file maglev-ir.h.
{ return input_count() > 0; }
References input_count().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::PrintInputs().
id()
constexpr NodeIdT v8::internal::maglev::NodeBase::id () const [inline], [constexpr]
Definition at line 2199 of file maglev-ir.h.
                               {
    DCHECK_NE(id_, kInvalidNodeId);
    return id_;
  }
References DCHECK_NE, id_, and v8::internal::maglev::kInvalidNodeId.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters(), v8::internal::maglev::BasicBlock::contains_node_id(), v8::internal::maglev::BasicBlock::first_non_phi_id(), v8::internal::maglev::BasicBlock::FirstNonGapMoveId(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::HighestPostDominatingHole(), v8::internal::maglev::StraightForwardRegisterAllocator::InitializeConditionalBranchTarget(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::IsLiveAtTarget(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::IsTargetOfNodeFallthrough(), v8::internal::maglev::LiveRangeAndNextUseProcessor::MarkCheckpointNodes(), v8::internal::maglev::LiveRangeAndNextUseProcessor::MarkUse(), v8::internal::maglev::MaglevGraphLabeller::PrintNodeLabel(), v8::internal::maglev::ValueNode::record_next_use(), set_id(), v8::internal::maglev::ValueNode::SetHint(), and v8::internal::maglev::ValueNode::start_id().
initialize_input_null()
void v8::internal::maglev::NodeBase::initialize_input_null (int index) [inline], [protected]
Definition at line 2909 of file maglev-ir.h.
                                                     {
  // Should already be null in debug, make sure it's null on release too.
  DCHECK_EQ(input(index).node(), nullptr);
  new (&input(index)) Input(nullptr);
}
References DCHECK_EQ, v8::internal::index, and input().
InitTemporaries()
void v8::internal::maglev::NodeBase::InitTemporaries () [inline]
Definition at line 2331 of file maglev-ir.h.
{ owner_or_temporaries_.InitReglist(); }
References v8::internal::maglev::NodeBase::OwnerOrTemporaries::InitReglist(), and owner_or_temporaries_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AddMoveBeforeCurrentNode().
input() [1/2]
constexpr Input& v8::internal::maglev::NodeBase::input (int index) [inline], [constexpr]
Definition at line 2179 of file maglev-ir.h.
                                    {
    DCHECK_LT(index, input_count());
    return *(input_base() - index);
  }
References DCHECK_LT, v8::internal::index, input_base(), and input_count().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNodeResult(), begin(), v8::internal::maglev::ForInNext::cache_array(), v8::internal::maglev::ForInNext::cache_index(), v8::internal::maglev::ForInNext::cache_type(), v8::internal::maglev::LoopOptimizationProcessor::CanHoist(), change_input(), v8::internal::maglev::CheckValueInputIs(), v8::internal::maglev::TryOnStackReplacement::closure(), v8::internal::maglev::ToName::context(), v8::internal::maglev::DeleteProperty::context(), v8::internal::maglev::ForInPrepare::context(), v8::internal::maglev::ForInNext::context(), v8::internal::maglev::ToObject::context(), v8::internal::maglev::ToString::context(), v8::internal::maglev::MaglevPhiRepresentationSelector::ConvertTaggedPhiTo(), end(), v8::internal::maglev::ForInPrepare::enumerator(), v8::internal::maglev::MaglevPhiRepresentationSelector::FixLoopPhisBackedge(), v8::internal::maglev::MaglevPhiRepresentationSelector::GetReplacementForPhiInputConversion(), initialize_input_null(), v8::internal::maglev::Float64Negate::input(), v8::internal::maglev::Float64Ieee754Unary::input(), v8::internal::maglev::CheckInt32IsSmi::input(), v8::internal::maglev::CheckUint32IsSmi::input(), v8::internal::maglev::CheckIntPtrIsSmi::input(), v8::internal::maglev::CheckHoleyFloat64IsSmi::input(), v8::internal::maglev::CheckedSmiTagInt32::input(), v8::internal::maglev::CheckedSmiSizedInt32::input(), v8::internal::maglev::CheckedSmiTagUint32::input(), v8::internal::maglev::CheckedSmiTagIntPtr::input(), v8::internal::maglev::UnsafeSmiTagInt32::input(), v8::internal::maglev::UnsafeSmiTagUint32::input(), v8::internal::maglev::UnsafeSmiTagIntPtr::input(), v8::internal::maglev::CheckedSmiUntag::input(), v8::internal::maglev::UnsafeSmiUntag::input(), v8::internal::maglev::Int32ToUint8Clamped::input(), v8::internal::maglev::Uint32ToUint8Clamped::input(), v8::internal::maglev::Float64ToUint8Clamped::input(), v8::internal::maglev::CheckedNumberToUint8Clamped::input(), v8::internal::maglev::Int32ToNumber::input(), v8::internal::maglev::Uint32ToNumber::input(), v8::internal::maglev::IntPtrToNumber::input(), v8::internal::maglev::Float64ToTagged::input(), v8::internal::maglev::Float64ToHeapNumberForField::input(), v8::internal::maglev::HoleyFloat64ToTagged::input(), v8::internal::maglev::CheckedSmiTagFloat64::input(), v8::internal::maglev::CheckedInt32ToUint32::input(), v8::internal::maglev::CheckedIntPtrToUint32::input(), v8::internal::maglev::UnsafeInt32ToUint32::input(), v8::internal::maglev::CheckedUint32ToInt32::input(), v8::internal::maglev::CheckedIntPtrToInt32::input(), v8::internal::maglev::ChangeInt32ToFloat64::input(), v8::internal::maglev::ChangeUint32ToFloat64::input(), v8::internal::maglev::ChangeIntPtrToFloat64::input(), v8::internal::maglev::CheckedTruncateFloat64ToInt32::input(), v8::internal::maglev::Int32AbsWithOverflow::input(), v8::internal::maglev::Float64Abs::input(), v8::internal::maglev::Int32CountLeadingZeros::input(), v8::internal::maglev::SmiCountLeadingZeros::input(), v8::internal::maglev::Float64CountLeadingZeros::input(), v8::internal::maglev::Float64Round::input(), v8::internal::maglev::CheckedTruncateFloat64ToUint32::input(), v8::internal::maglev::CheckedNumberOrOddballToHoleyFloat64::input(), v8::internal::maglev::CheckedNumberToInt32::input(), v8::internal::maglev::UncheckedNumberOrOddballToFloat64::input(), v8::internal::maglev::CheckedHoleyFloat64ToFloat64::input(), v8::internal::maglev::HoleyFloat64ToMaybeNanFloat64::input(), v8::internal::maglev::HoleyFloat64IsHole::input(), v8::internal::maglev::TruncateNumberOrOddballToInt32::input(), v8::internal::maglev::CheckedTruncateNumberOrOddballToInt32::input(), v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::IsStoreToNonEscapedObject(), v8::internal::maglev::DeleteProperty::key(), last_input(), v8::internal::maglev::BinaryWithFeedbackNode< Derived, kOperation >::left_input(), v8::internal::maglev::Int32BinaryWithOverflowNode< Derived, kOperation >::left_input(), v8::internal::maglev::Int32BinaryNode< Derived, kOperation >::left_input(), v8::internal::maglev::Int32ShiftRightLogical::left_input(), v8::internal::maglev::Int32Compare::left_input(), v8::internal::maglev::Float64BinaryNode< Derived, kOperation >::left_input(), v8::internal::maglev::Float64BinaryNodeWithCall< Derived, kOperation >::left_input(), v8::internal::maglev::Float64Compare::left_input(), v8::internal::maglev::StringEqual::lhs(), v8::internal::maglev::TaggedEqual::lhs(), v8::internal::maglev::TaggedNotEqual::lhs(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::MakePhiMaybePermuteInputs(), v8::internal::maglev::LiveRangeAndNextUseProcessor::MarkInputUses(), v8::internal::maglev::MaglevGraphBuilder::MarkNodeDead(), New(), v8::internal::maglev::DeleteProperty::object(), v8::internal::maglev::UnaryWithFeedbackNode< Derived, kOperation >::operand_input(), v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::PrintInputs(), v8::internal::maglev::TransitionElementsKindOrCheckMap::PrintParams(), v8::internal::maglev::SweepIdentityNodes::Process(), v8::internal::maglev::MaglevPhiRepresentationSelector::ProcessPhi(), v8::internal::maglev::ForInNext::receiver(), v8::internal::maglev::StringEqual::rhs(), v8::internal::maglev::TaggedEqual::rhs(), v8::internal::maglev::TaggedNotEqual::rhs(), v8::internal::maglev::BinaryWithFeedbackNode< Derived, kOperation >::right_input(), v8::internal::maglev::Int32BinaryWithOverflowNode< Derived, kOperation >::right_input(), v8::internal::maglev::Int32BinaryNode< Derived, kOperation >::right_input(), v8::internal::maglev::Int32ShiftRightLogical::right_input(), v8::internal::maglev::Int32Compare::right_input(), v8::internal::maglev::Float64BinaryNode< Derived, kOperation >::right_input(), v8::internal::maglev::Float64BinaryNodeWithCall< Derived, kOperation >::right_input(), v8::internal::maglev::Float64Compare::right_input(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::SameAsInput(), set_input(), v8::internal::maglev::ValueNode::SetHint(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ThrowingScope::ThrowingScope(), TryGetInt32ConstantInput(), v8::internal::maglev::KnownNodeAspects::UpdateMayHaveAliasingContexts(), v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateNodeInputs(), v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateNonUntaggingNodeInputs(), v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateUntaggingOfPhi(), v8::internal::maglev::Int32ToBoolean::value(), v8::internal::maglev::IntPtrToBoolean::value(), v8::internal::maglev::Float64ToBoolean::value(), v8::internal::maglev::LogicalNot::value(), v8::internal::maglev::SetPendingMessage::value(), v8::internal::maglev::ToBoolean::value(), v8::internal::maglev::ToBooleanLogicalNot::value(), v8::internal::maglev::TestUndetectable::value(), v8::internal::maglev::TestTypeOf::value(), v8::internal::maglev::Int32BitwiseNot::value_input(), v8::internal::maglev::Int32UnaryWithOverflowNode< Derived, kOperation >::value_input(), v8::internal::maglev::CheckedSmiIncrement::value_input(), v8::internal::maglev::CheckedSmiDecrement::value_input(), v8::internal::maglev::ToName::value_input(), v8::internal::maglev::ToNumberOrNumeric::value_input(), v8::internal::maglev::ToObject::value_input(), v8::internal::maglev::ToString::value_input(), and v8::internal::maglev::NumberToString::value_input().
input() [2/2]
constexpr const Input& v8::internal::maglev::NodeBase::input (int index) const [inline], [constexpr]
Definition at line 2183 of file maglev-ir.h.
                                                {
    DCHECK_LT(index, input_count());
    return *(input_base() - index);
  }
References DCHECK_LT, v8::internal::index, input_base(), and input_count().
input_base() [1/2]
constexpr Input* v8::internal::maglev::NodeBase::input_base () [inline], [constexpr], [protected]
Definition at line 2351 of file maglev-ir.h.
                                {
    return detail::ObjectPtrBeforeAddress<Input>(this);
  }
Referenced by input().
input_base() [2/2]
constexpr const Input* v8::internal::maglev::NodeBase::input_base () const [inline], [constexpr], [protected]
Definition at line 2354 of file maglev-ir.h.
                                            {
    return detail::ObjectPtrBeforeAddress<Input>(this);
  }
input_count()
constexpr int v8::internal::maglev::NodeBase::input_count () const [inline], [constexpr]
Definition at line 2174 of file maglev-ir.h.
                                    {
    static_assert(InputCountField::kMax <= kMaxInt);
    return static_cast<int>(InputCountField::decode(bitfield_));
  }
References bitfield_, v8::base::BitField< T, shift, size, U >::decode(), v8::base::BitField< T, shift, size, U >::kMax, and v8::internal::kMaxInt.
Referenced by Allocate(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateControlNode(), v8::internal::maglev::LoopOptimizationProcessor::CanHoist(), end(), v8::internal::maglev::FixedInputNodeTMixin< InputCount, Base, Derived >::FixedInputNodeTMixin(), has_inputs(), input(), v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::IsStoreToNonEscapedObject(), last_input(), v8::internal::maglev::MaglevGraphBuilder::MarkNodeDead(), New(), OverwriteWithIdentityTo(), v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::PrintInputs(), v8::internal::maglev::SweepIdentityNodes::Process(), v8::internal::maglev::MaglevPhiRepresentationSelector::ProcessPhi(), reduce_input_count(), v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateNodeInputs(), and v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateUntaggingOfPhi().
Is() [1/7]
template<class T >
constexpr bool v8::internal::maglev::NodeBase::Is [constexpr]
Definition at line 2552 of file maglev-ir.h.
                                  {
  return opcode() == opcode_of<T>;
}
References opcode().
Referenced by v8::internal::maglev::MaglevGraphBuilder::AddDeoptUse(), v8::internal::maglev::MaglevGraphBuilder::AddInitializedNodeToGraph(), v8::internal::maglev::StraightForwardRegisterAllocator::AddMoveBeforeCurrentNode(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateControlNode(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateEagerDeopt(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateLazyDeopt(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNode(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNodeResult(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters(), v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfToBooleanTrue(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckNumericalValue(), v8::internal::maglev::MaglevGraphBuilder::BuildInlinedAllocation(), v8::internal::maglev::MaglevGraphBuilder::BuildTaggedEqual(), v8::internal::maglev::MaglevGraphBuilder::CanTrackObjectChanges(), v8::internal::maglev::CheckValueInputIs(), v8::internal::maglev::MaglevPhiRepresentationSelector::ConvertTaggedPhiTo(), v8::internal::maglev::AnyUseMarkingProcessor::DropInputUses(), v8::internal::compiler::turboshaft::GeneratorAnalyzer::FindLoopHeaderBypasses(), v8::internal::maglev::MaglevPhiRepresentationSelector::FixLoopPhisBackedge(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::GetAllocation(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::GetReservedRegisters(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::HighestPostDominatingHole(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::IsDeadNodeToSkip(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::IsMaglevMainGeneratorSwitchBlock(), v8::internal::maglev::LiveRangeAndNextUseProcessor::MarkUse(), v8::internal::maglev::StraightForwardRegisterAllocator::MergeRegisterValues(), v8::internal::maglev::MergePointInterpreterFrameState::MergeValue(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::NearestPostDominatingHole(), v8::internal::maglev::MergePointInterpreterFrameState::NewForLoop(), v8::internal::maglev::MaglevGraphLabeller::PrintNodeLabel(), v8::internal::maglev::SweepIdentityNodes::Process(), v8::internal::maglev::MaglevGraphBuilder::ProcessMergePointPredecessors(), v8::internal::maglev::MaglevPhiRepresentationSelector::ProcessPhi(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::RecordMoves(), v8::internal::maglev::MaglevGraphBuilder::ReduceCallWithArrayLikeForArgumentsObject(), v8::internal::maglev::ControlNode::set_next_post_dominating_hole(), v8::internal::maglev::MaglevGraphBuilder::SetKnownValue(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ThrowingScope::ThrowingScope(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementStoreOnJSArrayOrJSObject(), v8::internal::maglev::Graph::TryGetScopeInfo(), v8::internal::maglev::MaglevGraphBuilder::TrySpecializeLoadContextSlot(), v8::internal::maglev::MaglevGraphBuilder::TrySpecializeStoreContextSlot(), v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateNodeInputs(), v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateNonUntaggingNodeInputs(), v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateUntaggingOfPhi(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::VerifyIsNotEscaping(), v8::internal::maglev::StraightForwardRegisterAllocator::VerifyRegisterState(), and v8::internal::maglev::MaglevGraphBuilder::VisitCompareOperation().
Is() [2/7]
template<>
constexpr bool v8::internal::maglev::NodeBase::Is () const [constexpr]
Definition at line 2558 of file maglev-ir.h.
                                             {
  return IsValueNode(opcode());
}
References v8::internal::maglev::IsValueNode(), and opcode().
Is() [3/7]
template<>
constexpr bool v8::internal::maglev::NodeBase::Is () const [constexpr]
Definition at line 2562 of file maglev-ir.h.
                                               {
  return IsControlNode(opcode());
}
References v8::internal::maglev::IsControlNode(), and opcode().
Is() [4/7]
template<>
constexpr bool v8::internal::maglev::NodeBase::Is () const [constexpr]
Definition at line 2566 of file maglev-ir.h.
                                                     {
  return IsBranchControlNode(opcode());
}
References v8::internal::maglev::IsBranchControlNode(), and opcode().
Is() [5/7]
template<>
constexpr bool v8::internal::maglev::NodeBase::Is () const [constexpr]
Definition at line 2570 of file maglev-ir.h.
                                                          {
  return IsConditionalControlNode(opcode());
}
References v8::internal::maglev::IsConditionalControlNode(), and opcode().
Is() [6/7]
template<>
constexpr bool v8::internal::maglev::NodeBase::Is () const [constexpr]
Definition at line 2574 of file maglev-ir.h.
                                                            {
  return IsUnconditionalControlNode(opcode());
}
References v8::internal::maglev::IsUnconditionalControlNode(), and opcode().
Is() [7/7]
template<>
constexpr bool v8::internal::maglev::NodeBase::Is () const [constexpr]
Definition at line 2578 of file maglev-ir.h.
                                                       {
  return IsTerminalControlNode(opcode());
}
References v8::internal::maglev::IsTerminalControlNode(), and opcode().
last_input() [1/2]
Input* v8::internal::maglev::NodeBase::last_input () [inline], [protected]
Definition at line 2357 of file maglev-ir.h.
{ return &input(input_count() - 1); }
References input(), and input_count().
Referenced by last_input_address().
last_input() [2/2]
const Input* v8::internal::maglev::NodeBase::last_input () const [inline], [protected]
Definition at line 2358 of file maglev-ir.h.
{ return &input(input_count() - 1); }
References input(), and input_count().
last_input_address()
Address v8::internal::maglev::NodeBase::last_input_address () const [inline], [protected]
Definition at line 2360 of file maglev-ir.h.
                                     {
    return reinterpret_cast<Address>(last_input());
  }
References last_input().
Referenced by deopt_info_address().
lazy_deopt_info()
LazyDeoptInfo* v8::internal::maglev::NodeBase::lazy_deopt_info () [inline]
Definition at line 2253 of file maglev-ir.h.
                                   {
    DCHECK(properties().can_lazy_deopt());
    DCHECK(!properties().can_eager_deopt());
    return reinterpret_cast<LazyDeoptInfo*>(deopt_info_address());
  }
References v8::internal::DCHECK(), deopt_info_address(), and properties().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNode(), v8::internal::maglev::MaglevAssembler::DefineExceptionHandlerAndLazyDeoptPoint(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::EmitTrampolineFor(), v8::internal::maglev::anonymous_namespace{maglev-ir-x64.cc}::HandleInterruptsAndTiering(), v8::internal::maglev::anonymous_namespace{maglev-ir-arm64.cc}::HandleInterruptsAndTiering(), v8::internal::maglev::anonymous_namespace{maglev-ir-riscv.cc}::HandleInterruptsAndTiering(), v8::internal::maglev::anonymous_namespace{maglev-ir-s390.cc}::HandleInterruptsAndTiering(), v8::internal::maglev::SweepIdentityNodes::Process(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ThrowingScope::ThrowingScope().
LazyDeoptInfoSize()
static constexpr size_t v8::internal::maglev::NodeBase::LazyDeoptInfoSize (OpProperties properties) [inline], [static], [constexpr], [private]
Definition at line 2455 of file maglev-ir.h.
                                                                     {
    return RoundUp<alignof(Input)>(
        properties.can_lazy_deopt() ? sizeof(LazyDeoptInfo) : 0);
  }
References v8::internal::maglev::OpProperties::can_lazy_deopt(), and properties().
Referenced by Allocate(), and deopt_info_address().
New() [1/2]
template<class Derived , typename... Args>
static Derived* v8::internal::maglev::NodeBase::New (Zone * zone, size_t input_count, Args &&... args) [inline], [static]
Definition at line 2130 of file maglev-ir.h.
                                                                      {
    Derived* node =
        Allocate<Derived>(zone, input_count, std::forward<Args>(args)...);
    return node;
  }
References v8::base::args, and input_count().
New() [2/2]
template<class Derived , typename... Args>
static Derived* v8::internal::maglev::NodeBase::New (Zone * zone, std::initializer_list< ValueNode * > inputs, Args &&... args) [inline], [static]
Definition at line 2110 of file maglev-ir.h.
                                      {
    static_assert(Derived::kProperties.is_conversion(),
                  "This method does not implicitly convert input types. Use "
                  "MaglevGraphBuilder::AddNewNode instead or NodeBase::New and "
                  "initialize and convert inputs manually.");
    Derived* node =
        Allocate<Derived>(zone, inputs.size(), std::forward<Args>(args)...);
    int i = 0;
    for (ValueNode* input : inputs) {
      DCHECK_NOT_NULL(input);
      node->set_input(i++, input);
    }
    return node;
  }
References v8::base::args, DCHECK_NOT_NULL, and input().
num_temporaries_needed()
template<typename RegisterT >
uint8_t v8::internal::maglev::NodeBase::num_temporaries_needed () const [inline]
Definition at line 2210 of file maglev-ir.h.
                                         {
    if constexpr (std::is_same_v<RegisterT, Register>) {
      return NumTemporariesNeededField::decode(bitfield_);
    } else {
      return NumDoubleTemporariesNeededField::decode(bitfield_);
    }
  }
References bitfield_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateControlNode(), and v8::internal::maglev::StraightForwardRegisterAllocator::AssignArbitraryTemporaries().
opcode()
constexpr Opcode v8::internal::maglev::NodeBase::opcode () const [inline], [constexpr]
Definition at line 2140 of file maglev-ir.h.
{ return OpcodeField::decode(bitfield_); }
References bitfield_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AddMoveBeforeCurrentNode(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNodeResult(), v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfRootConstant(), v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfToBooleanTrue(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckInternalizedStringValueOrByReference(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckNumericalValue(), v8::internal::maglev::MaglevGraphBuilder::BuildNewConsStringMap(), v8::internal::maglev::MaglevGraphBuilder::BuildTaggedEqual(), v8::internal::maglev::LoopOptimizationProcessor::CanHoist(), change_representation(), v8::internal::maglev::CheckValueInputIs(), ClearElementsProperties(), ClearUnstableNodeAspects(), v8::internal::maglev::FromConstantToBool(), v8::internal::maglev::ValueNode::GetStaticType(), Is(), v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::IsStoreToNonEscapedObject(), v8::internal::maglev::NodeTMixin< Base, Derived >::NodeTMixin(), Print(), v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::PrintResult(), v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::ProcessNodeBase(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::RecordMoveToRegister(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::RecordMoveToStackSlot(), reduce_input_count(), v8::internal::maglev::ValueNode::Reify(), v8::internal::maglev::ValueNode::SetConstantLocation(), v8::internal::maglev::ValueNode::SetNoSpill(), v8::internal::maglev::ValueNode::Spill(), v8::internal::maglev::KnownNodeAspects::UpdateMayHaveAliasingContexts(), v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateNodePhiInput(), and v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateUntaggingOfPhi().
operator=() [1/2]
NodeBase& v8::internal::maglev::NodeBase::operator= (const NodeBase &) [private], [delete]
operator=() [2/2]
NodeBase& v8::internal::maglev::NodeBase::operator= (NodeBase &&) [private], [delete]
options()
auto v8::internal::maglev::NodeBase::options () const [inline]
Definition at line 2322 of file maglev-ir.h.
{ return std::tuple{}; }
OverwriteWith() [1/2]
template<typename NodeT >
void v8::internal::maglev::NodeBase::OverwriteWith () [inline]
Definition at line 2303 of file maglev-ir.h.
                       {
    OverwriteWith(NodeBase::opcode_of<NodeT>, NodeT::kProperties);
  }
Referenced by v8::internal::maglev::MaglevGraphBuilder::MarkNodeDead(), and v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateUntaggingOfPhi().
OverwriteWith() [2/2]
void v8::internal::maglev::NodeBase::OverwriteWith (Opcode new_opcode, std::optional< OpProperties > maybe_new_properties = std::nullopt) [inline]
Definition at line 2307 of file maglev-ir.h.
                                                                   {
    OpProperties new_properties = maybe_new_properties.has_value()
                                      ? maybe_new_properties.value()
                                      : StaticPropertiesForOpcode(new_opcode);
#ifdef DEBUG
    CheckCanOverwriteWith(new_opcode, new_properties);
#endif
    set_opcode(new_opcode);
    set_properties(new_properties);
  }
References CheckCanOverwriteWith(), set_opcode(), set_properties(), and v8::internal::maglev::StaticPropertiesForOpcode().
OverwriteWithIdentityTo()
void v8::internal::maglev::NodeBase::OverwriteWithIdentityTo (ValueNode * node) [inline]
Definition at line 139 of file maglev-ir-inl.h.
                                                      {
  // OverwriteWith() checks if the node we're overwriting to has the same
  // input count and the same properties. Here we don't need to do that, since
  // overwriting with a node with property pure, we only need to check if
  // there is at least 1 input. Since the first input is always the one
  // closest to the input_base().
  DCHECK_GE(input_count(), 1);
  set_opcode(NodeBase::opcode_of<Identity>);
  set_properties(OpProperties::Pure());
  bitfield_ = InputCountField::update(bitfield_, 1);
  change_input(0, node);
}
References bitfield_, change_input(), DCHECK_GE, input_count(), v8::internal::maglev::OpProperties::Pure(), set_opcode(), set_properties(), and v8::base::BitField< T, shift, size, U >::update().
owner()
BasicBlock* v8::internal::maglev::NodeBase::owner () const [inline]
Definition at line 2329 of file maglev-ir.h.
{ return owner_or_temporaries_.owner(); }
References v8::internal::maglev::NodeBase::OwnerOrTemporaries::owner(), and owner_or_temporaries_.
Referenced by v8::internal::maglev::LoopOptimizationProcessor::CanHoist().
Print() [1/2]
void v8::internal::maglev::NodeBase::Print () const
Definition at line 461 of file maglev-ir.cc.
                           {
  MaglevGraphLabeller labeller;
  Print(std::cout, &labeller);
  std::cout << std::endl;
}
Print() [2/2]
void v8::internal::maglev::NodeBase::Print (std::ostream & os, MaglevGraphLabeller * graph_labeller, bool skip_targets = false) const
Definition at line 449 of file maglev-ir.cc.
                                              {
  switch (opcode()) {
#define V(Name) \
  case Opcode::k##Name: \
    return PrintImpl(os, graph_labeller, this->Cast<Name>(), skip_targets);
    NODE_BASE_LIST(V)
#undef V
  }
  UNREACHABLE();
}
References NODE_BASE_LIST, opcode(), and v8::internal::UNREACHABLE().
properties()
constexpr OpProperties v8::internal::maglev::NodeBase::properties () const [inline], [constexpr]
Definition at line 2141 of file maglev-ir.h.
                                            {
    return OpPropertiesField::decode(bitfield_);
  }
References bitfield_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::maglev::MaglevPhiRepresentationSelector::AddNode(), v8::internal::maglev::MaglevInliner::AddNodeAtBlockEnd(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateControlNode(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNode(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNodeResult(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateSpillSlot(), v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfRootConstant(), v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfUndefinedOrNull(), v8::internal::maglev::MaglevGraphBuilder::BuildTruncatingInt32BinarySmiOperationNodeForToNumber(), change_representation(), v8::internal::maglev::CheckValueInputIs(), ClearUnstableNodeAspects(), v8::internal::maglev::MaglevGraphBuilder::ConvertInputTo(), v8::internal::maglev::MaglevPhiRepresentationSelector::ConvertTaggedPhiTo(), deopt_info_address(), v8::internal::maglev::AnyUseMarkingProcessor::DropInputUses(), eager_deopt_info(), EagerDeoptInfoSize(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::EmitTrampolineFor(), exception_handler_address(), exception_handler_info(), ExceptionHandlerInfoSize(), v8::internal::maglev::MaglevGraphBuilder::GetInt32ElementIndex(), v8::internal::maglev::ValueNode::GetMachineRepresentation(), v8::internal::maglev::ValueNode::GetStaticType(), v8::internal::maglev::MaglevGraphBuilder::GetUint32ElementIndex(), v8::internal::maglev::ValueNode::is_tagged(), lazy_deopt_info(), LazyDeoptInfoSize(), v8::internal::maglev::MergePointInterpreterFrameState::MergeValue(), v8::internal::maglev::NodeTMixin< Base, Derived >::NodeTMixin(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::NoThrowingScopeRequired::NoThrowingScopeRequired(), v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::PrintResult(), v8::internal::maglev::SweepIdentityNodes::Process(), v8::internal::maglev::LoopOptimizationProcessor::ProcessNamedLoad(), v8::internal::maglev::MaglevPhiRepresentationSelector::ProcessPhi(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::RecordMoves(), reduce_input_count(), register_snapshot(), register_snapshot_address(), RegisterSnapshotSize(), v8::internal::maglev::StraightForwardRegisterAllocator::SaveRegisterSnapshot(), v8::internal::maglev::CallArguments::set_arg(), set_properties(), v8::internal::maglev::CallArguments::set_receiver(), set_register_snapshot(), SetEagerDeoptInfo(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ThrowingScope::ThrowingScope(), v8::internal::maglev::MaglevGraphBuilder::TryReduceCompareEqualAgainstConstant(), v8::internal::maglev::MaglevGraphBuilder::TryReduceConstructGeneric(), v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateNodePhiInput(), v8::internal::maglev::StraightForwardRegisterAllocator::UpdateUse(), v8::internal::maglev::ValueNode::use_double_register(), and v8::internal::maglev::ValueNode::value_representation().
reduce_input_count()
void v8::internal::maglev::NodeBase::reduce_input_count (int num = 1) [inline], [protected]
Definition at line 2369 of file maglev-ir.h.
                                       {
    DCHECK_EQ(opcode(), Opcode::kPhi);
    DCHECK_GE(input_count(), num);
    DCHECK(!properties().can_lazy_deopt());
    DCHECK(!properties().can_eager_deopt());
    bitfield_ = InputCountField::update(bitfield_, input_count() - num);
  }
References bitfield_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, input_count(), opcode(), properties(), and v8::base::BitField< T, shift, size, U >::update().
register_snapshot()
const RegisterSnapshot& v8::internal::maglev::NodeBase::register_snapshot () const [inline]
Definition at line 2259 of file maglev-ir.h.
                                                    {
    DCHECK(properties().needs_register_snapshot());
    return *reinterpret_cast<RegisterSnapshot*>(register_snapshot_address());
  }
References v8::internal::DCHECK(), properties(), and register_snapshot_address().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-ir-x64.cc}::HandleInterruptsAndTiering(), v8::internal::maglev::anonymous_namespace{maglev-ir-arm64.cc}::HandleInterruptsAndTiering(), v8::internal::maglev::anonymous_namespace{maglev-ir-riscv.cc}::HandleInterruptsAndTiering(), and v8::internal::maglev::anonymous_namespace{maglev-ir-s390.cc}::HandleInterruptsAndTiering().
register_snapshot_address()
Address v8::internal::maglev::NodeBase::register_snapshot_address () const [inline], [private]
Definition at line 2471 of file maglev-ir.h.
                                            {
    size_t extra = RegisterSnapshotSize(properties());
    return deopt_info_address() - extra;
  }
References deopt_info_address(), properties(), and RegisterSnapshotSize().
Referenced by exception_handler_address(), register_snapshot(), and set_register_snapshot().
RegisterSnapshotSize()
static constexpr size_t v8::internal::maglev::NodeBase::RegisterSnapshotSize (OpProperties properties) [inline], [static], [constexpr], [private]
Definition at line 2443 of file maglev-ir.h.
                                                                        {
    return RoundUp<alignof(Input)>(
        properties.needs_register_snapshot() ? sizeof(RegisterSnapshot) : 0);
  }
References v8::internal::maglev::OpProperties::needs_register_snapshot(), and properties().
Referenced by Allocate(), and register_snapshot_address().
RequireSpecificDoubleTemporary()
void v8::internal::maglev::NodeBase::RequireSpecificDoubleTemporary (DoubleRegister reg) [inline], [protected]
Definition at line 2397 of file maglev-ir.h.
                                                          {
    double_temporaries().set(reg);
  }
References double_temporaries(), and v8::internal::RegListBase< RegisterT >::set().
RequireSpecificTemporary()
void v8::internal::maglev::NodeBase::RequireSpecificTemporary (Register reg) [inline], [protected]
Definition at line 2393 of file maglev-ir.h.
                                              {
    general_temporaries().set(reg);
  }
References general_temporaries(), and v8::internal::RegListBase< RegisterT >::set().
set_bitfield()
void v8::internal::maglev::NodeBase::set_bitfield (uint64_t new_bitfield) [inline], [protected]
Definition at line 2338 of file maglev-ir.h.
                                           {
#ifdef DEBUG
    // Make sure that all the base bitfield bits (all bits before the next
    // bitfield start, excluding any spare bits) are equal in the new value.
    const uint64_t base_bitfield_mask =
        ((uint64_t{1} << NextBitField<bool, 1>::kShift) - 1) &
        ~ReservedField::kMask;
    DCHECK_EQ(bitfield_ & base_bitfield_mask,
              new_bitfield & base_bitfield_mask);
#endif
    bitfield_ = new_bitfield;
  }
References bitfield_, and DCHECK_EQ.
set_double_temporaries_needed()
void v8::internal::maglev::NodeBase::set_double_temporaries_needed (uint8_t value) [inline], [protected]
Definition at line 2386 of file maglev-ir.h.
                                                    {
    DCHECK_EQ(num_temporaries_needed<DoubleRegister>(), 0);
    bitfield_ = NumDoubleTemporariesNeededField::update(bitfield_, value);
  }
References bitfield_, DCHECK_EQ, v8::base::BitField< T, shift, size, U >::update(), and v8::internal::value.
set_id()
void v8::internal::maglev::NodeBase::set_id (NodeIdT id) [inline]
Definition at line 2203 of file maglev-ir.h.
                          {
    DCHECK_EQ(id_, kInvalidNodeId);
    DCHECK_NE(id, kInvalidNodeId);
    id_ = id;
  }
References DCHECK_EQ, DCHECK_NE, id(), id_, and v8::internal::maglev::kInvalidNodeId.
set_input()
void v8::internal::maglev::NodeBase::set_input (int index, ValueNode * node) [inline]
Definition at line 2915 of file maglev-ir.h.
                                                          {
  DCHECK_NOT_NULL(node);
  DCHECK_EQ(input(index).node(), nullptr);
  node->add_use();
  new (&input(index)) Input(node);
}
References v8::internal::maglev::ValueNode::add_use(), DCHECK_EQ, DCHECK_NOT_NULL, v8::internal::index, and input().
Referenced by change_input().
set_opcode()
void v8::internal::maglev::NodeBase::set_opcode (Opcode new_opcode) [inline]
Definition at line 2283 of file maglev-ir.h.
                                     {
    bitfield_ = OpcodeField::update(bitfield_, new_opcode);
  }
References bitfield_, and v8::base::BitField< T, shift, size, U >::update().
Referenced by OverwriteWith(), and OverwriteWithIdentityTo().
set_owner()
void v8::internal::maglev::NodeBase::set_owner (BasicBlock * block) [inline]
Definition at line 2327 of file maglev-ir.h.
{ owner_or_temporaries_ = block; }
References owner_or_temporaries_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::AddInitializedNodeToGraph(), v8::internal::maglev::MaglevGraphBuilder::FinishInlinedBlockForCaller(), and v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::ProcessGraph().
set_properties()
void v8::internal::maglev::NodeBase::set_properties (OpProperties properties) [inline]
Definition at line 2144 of file maglev-ir.h.
                                               {
    bitfield_ = OpPropertiesField::update(bitfield_, properties);
  }
References bitfield_, properties(), and v8::base::BitField< T, shift, size, U >::update().
Referenced by OverwriteWith(), and OverwriteWithIdentityTo().
set_register_snapshot()
void v8::internal::maglev::NodeBase::set_register_snapshot (RegisterSnapshot snapshot) [inline]
Definition at line 2269 of file maglev-ir.h.
                                                        {
    DCHECK(properties().needs_register_snapshot());
    *reinterpret_cast<RegisterSnapshot*>(register_snapshot_address()) =
        snapshot;
  }
References v8::internal::DCHECK(), properties(), and register_snapshot_address().
set_temporaries_needed()
void v8::internal::maglev::NodeBase::set_temporaries_needed (uint8_t value) [inline], [protected]
Definition at line 2381 of file maglev-ir.h.
                                             {
    DCHECK_EQ(num_temporaries_needed<Register>(), 0);
    bitfield_ = NumTemporariesNeededField::update(bitfield_, value);
  }
References bitfield_, DCHECK_EQ, v8::base::BitField< T, shift, size, U >::update(), and v8::internal::value.
SetEagerDeoptInfo()
void v8::internal::maglev::NodeBase::SetEagerDeoptInfo (Zone * zone, DeoptFrame deopt_frame, compiler::FeedbackSource feedback_to_update = compiler::FeedbackSource()) [inline]
Definition at line 2293 of file maglev-ir.h.
                                                       {
    DCHECK(properties().can_eager_deopt() ||
           properties().is_deopt_checkpoint());
    new (eager_deopt_info())
        EagerDeoptInfo(zone, deopt_frame, feedback_to_update);
  }
References v8::internal::DCHECK(), eager_deopt_info(), and properties().
Referenced by v8::internal::maglev::MaglevPhiRepresentationSelector::AddNode().
temporaries()
template<typename RegisterT >
RegListBase<RegisterT>& v8::internal::maglev::NodeBase::temporaries () [inline]
Definition at line 2219 of file maglev-ir.h.
                                        {
    return owner_or_temporaries_.temporaries<RegisterT>();
  }
References owner_or_temporaries_, and v8::internal::maglev::NodeBase::OwnerOrTemporaries::temporaries().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AssignArbitraryTemporaries(), and v8::internal::maglev::StraightForwardRegisterAllocator::AssignFixedTemporaries().
TryCast() [1/2]
template<class T >
constexpr T* v8::internal::maglev::NodeBase::TryCast () [inline], [constexpr]
Definition at line 2164 of file maglev-ir.h.
                         {
    return Is<T>() ? static_cast<T*>(this) : nullptr;
  }
Referenced by v8::internal::maglev::MaglevGraphBuilder::AddDeoptUse(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateControlNode(), v8::internal::maglev::StraightForwardRegisterAllocator::AssignArbitraryRegisterInput(), v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfReferenceEqual(), v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfRootConstant(), v8::internal::maglev::MaglevInliner::BuildInlineFunction(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadJSFunctionFeedbackCell(), v8::internal::maglev::MaglevGraphBuilder::BuildSmiUntag(), v8::internal::maglev::MaglevGraphBuilder::BuildStoreTaggedField(), v8::internal::maglev::MaglevGraphBuilder::BuildStringConcat(), v8::internal::maglev::StraightForwardRegisterAllocator::ComputePostDominatingHoles(), v8::internal::maglev::BasicBlock::ComputeRealJumpTarget(), v8::internal::maglev::MaglevPhiRepresentationSelector::ConvertTaggedPhiTo(), v8::internal::maglev::MaglevPhiRepresentationSelector::EnsurePhiInputsTagged(), v8::internal::maglev::KnownNodeAspects::EnsureType(), v8::internal::maglev::MaglevGraphBuilder::EscapeContext(), v8::internal::maglev::BasicBlock::ForEachSuccessorFollowing(), v8::internal::maglev::MaglevGraphBuilder::GetInt32ElementIndex(), v8::internal::maglev::KnownNodeAspects::GetType(), v8::internal::maglev::MaglevGraphBuilder::GetUint32ElementIndex(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::InputHint(), v8::internal::maglev::LoopOptimizationProcessor::IsLoopPhi(), v8::internal::maglev::MergePointInterpreterFrameState::MergeLoopValue(), v8::internal::maglev::MergePointInterpreterFrameState::MergeValue(), v8::internal::maglev::MergePointInterpreterFrameState::MergeVirtualObjectValue(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::NearestPostDominatingHole(), v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::PrintResult(), v8::internal::maglev::LoopOptimizationProcessor::Process(), v8::internal::maglev::MaglevPhiRepresentationSelector::ProcessPhi(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::RecordMoves(), v8::internal::maglev::MaglevGraphBuilder::RecordUseReprHintIfPhi(), v8::internal::maglev::MaglevGraphBuilder::ReduceCall(), v8::internal::maglev::MaglevGraphBuilder::ReduceCallWithArrayLikeForArgumentsObject(), v8::internal::maglev::MergePointInterpreterFrameState::RemovePredecessorAt(), v8::internal::maglev::StraightForwardRegisterAllocator::SaveRegisterSnapshot(), v8::internal::maglev::Phi::SetUseRequires31BitValue(), v8::internal::maglev::BasicBlock::successors(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ThrowingScope::ThrowingScope(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccessOnTypedArray(), TryGetInt32ConstantInput(), v8::internal::maglev::MaglevGraphBuilder::TryGetParentContext(), v8::internal::maglev::Graph::TryGetScopeInfo(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::FunctionContextSpecialization::TryToRef(), v8::internal::maglev::KnownNodeAspects::UpdateMayHaveAliasingContexts(), v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateNonUntaggingNodeInputs(), v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateUntaggingOfPhi(), and v8::internal::maglev::StraightForwardRegisterAllocator::VerifyRegisterState().
TryCast() [2/2]
template<class T >
constexpr const T* v8::internal::maglev::NodeBase::TryCast () const [inline], [constexpr]
Definition at line 2169 of file maglev-ir.h.
                                     {
    return Is<T>() ? static_cast<const T*>(this) : nullptr;
  }
TryGetInt32ConstantInput()
std::optional< int32_t > v8::internal::maglev::NodeBase::TryGetInt32ConstantInput (int index)
Definition at line 8552 of file maglev-ir.cc.
                                                                 {
  Node* node = input(index).node();
  if (auto smi = node->TryCast<SmiConstant>()) {
    return smi->value().value();
  }
  if (auto i32 = node->TryCast<Int32Constant>()) {
    return i32->value();
  }
  return {};
}
References v8::internal::index, input(), v8::internal::maglev::Input::node(), and TryCast().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-ir-arm64.cc}::TryGetAddImmediateInt32ConstantInput(), and v8::internal::maglev::anonymous_namespace{maglev-ir-arm64.cc}::TryGetLogicalImmediateInt32ConstantInput().
Member Data Documentation
bitfield_
uint64_t v8::internal::maglev::NodeBase::bitfield_ [private]
Definition at line 2485 of file maglev-ir.h.
Referenced by bitfield(), change_representation(), input_count(), num_temporaries_needed(), opcode(), OverwriteWithIdentityTo(), properties(), reduce_input_count(), set_bitfield(), set_double_temporaries_needed(), set_opcode(), set_properties(), and set_temporaries_needed().
id_
NodeIdT v8::internal::maglev::NodeBase::id_ = kInvalidNodeId [private]
Definition at line 2486 of file maglev-ir.h.
Referenced by has_id(), id(), and set_id().
kMaxInputs
constexpr int v8::internal::maglev::NodeBase::kMaxInputs = InputCountField::kMax [static], [constexpr], [protected]
Definition at line 2103 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::NodeBase::kProperties [static], [constexpr]
Initial value:
=
      OpProperties::Pure() | OpProperties::TaggedValue()
Definition at line 2137 of file maglev-ir.h.
opcode_of
template<class T >
constexpr Opcode v8::internal::maglev::NodeBase::opcode_of = detail::opcode_of_helper<T>::value [static], [constexpr]
Definition at line 2107 of file maglev-ir.h.
owner_or_temporaries_
OwnerOrTemporaries v8::internal::maglev::NodeBase::owner_or_temporaries_ [private]
Definition at line 2542 of file maglev-ir.h.
Referenced by assign_temporaries(), InitTemporaries(), owner(), set_owner(), and temporaries().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir-inl.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc