v8::internal::UnbufferedCharacterStream< ByteStream > Class Template Reference
Public Member Functions
template<class... TArgs>
UnbufferedCharacterStream (size_t pos, TArgs... args)
bool can_access_heap () const final
bool can_be_cloned () const final
std::unique_ptr< Utf16CharacterStream > Clone () const override
Protected Member Functions
bool ReadBlock (size_t position) final
UnbufferedCharacterStream (const UnbufferedCharacterStream< ByteStream > &other)
Protected Attributes
ByteStream< uint16_t > byte_stream_
Additional Inherited Members
Detailed Description
template<template< typename T > class ByteStream>
class v8::internal::UnbufferedCharacterStream< ByteStream >
Definition at line 289 of file scanner-character-streams.cc.
Constructor & Destructor Documentation
UnbufferedCharacterStream() [1/2]
template<template< typename T > class ByteStream>
template<class... TArgs>
v8::internal::UnbufferedCharacterStream< ByteStream >::UnbufferedCharacterStream (size_t pos, TArgs... args) [inline]
Definition at line 292 of file scanner-character-streams.cc.
                                                       : byte_stream_(args...) {
    buffer_pos_ = pos;
  }
References v8::internal::Utf16CharacterStream::buffer_pos_, and v8::internal::Utf16CharacterStream::pos().
UnbufferedCharacterStream() [2/2]
template<template< typename T > class ByteStream>
v8::internal::UnbufferedCharacterStream< ByteStream >::UnbufferedCharacterStream (const UnbufferedCharacterStream< ByteStream > & other) [inline], [protected]
Definition at line 334 of file scanner-character-streams.cc.
      : byte_stream_(other.byte_stream_) {}
Member Function Documentation
can_access_heap()
template<template< typename T > class ByteStream>
bool v8::internal::UnbufferedCharacterStream< ByteStream >::can_access_heap () const [inline], [final], [virtual]
Implements v8::internal::Utf16CharacterStream.
Definition at line 296 of file scanner-character-streams.cc.
                                     {
    return ByteStream<uint16_t>::kCanAccessHeap;
  }
can_be_cloned()
template<template< typename T > class ByteStream>
bool v8::internal::UnbufferedCharacterStream< ByteStream >::can_be_cloned () const [inline], [final], [virtual]
Implements v8::internal::Utf16CharacterStream.
Definition at line 300 of file scanner-character-streams.cc.
                                   {
    return ByteStream<uint16_t>::kCanBeCloned;
  }
Clone()
template<template< typename T > class ByteStream>
std::unique_ptr<Utf16CharacterStream> v8::internal::UnbufferedCharacterStream< ByteStream >::Clone () const [inline], [override], [virtual]
Implements v8::internal::Utf16CharacterStream.
Definition at line 304 of file scanner-character-streams.cc.
                                                             {
    return std::unique_ptr<Utf16CharacterStream>(
        new UnbufferedCharacterStream<ByteStream>(*this));
  }
ReadBlock()
template<template< typename T > class ByteStream>
bool v8::internal::UnbufferedCharacterStream< ByteStream >::ReadBlock (size_t position) [inline], [final], [protected], [virtual]
Implements v8::internal::Utf16CharacterStream.
Definition at line 310 of file scanner-character-streams.cc.
                                        {
    buffer_pos_ = position;
    DisallowGarbageCollection no_gc;
    Range<uint16_t> range =
        byte_stream_.GetDataAt(position, runtime_call_stats(), &no_gc);
    if (range.length() == 0) {
      // We should not set the buffer pointers to nullptr to avoid undefined
      // behavior, for example when incrementing buffer_cursor_. So instead use
      // this static array.
      static const uint16_t empty_buffer[1] = {0};
      buffer_start_ = empty_buffer;
      buffer_end_ = empty_buffer;
      buffer_cursor_ = empty_buffer;
      return false;
    }
    buffer_start_ = range.start;
    buffer_end_ = range.end;
    buffer_cursor_ = buffer_start_;
    DCHECK(!range.unaligned_start());
    DCHECK_LE(buffer_start_, buffer_end_);
    return true;
  }
References v8::internal::Utf16CharacterStream::buffer_cursor_, v8::internal::Utf16CharacterStream::buffer_end_, v8::internal::Utf16CharacterStream::buffer_pos_, v8::internal::Utf16CharacterStream::buffer_start_, v8::internal::UnbufferedCharacterStream< ByteStream >::byte_stream_, v8::internal::DCHECK(), DCHECK_LE, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::Utf16CharacterStream::runtime_call_stats().
Member Data Documentation
byte_stream_
template<template< typename T > class ByteStream>
ByteStream<uint16_t> v8::internal::UnbufferedCharacterStream< ByteStream >::byte_stream_ [protected]
Definition at line 337 of file scanner-character-streams.cc.
Referenced by v8::internal::UnbufferedCharacterStream< ByteStream >::ReadBlock().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/parsing/scanner-character-streams.cc