v8::internal::compiler::JSNativeContextSpecialization::ValueEffectControl Class Reference
Public Member Functions
ValueEffectControl ()
ValueEffectControl (Node *value, Node *effect, Node *control)
Node * value () const
Node * effect () const
Node * control () const
Private Attributes
Node * value_
Node * effect_
Node * control_
Detailed Description
Definition at line 133 of file js-native-context-specialization.h.
Constructor & Destructor Documentation
ValueEffectControl() [1/2]
v8::internal::compiler::JSNativeContextSpecialization::ValueEffectControl::ValueEffectControl () [inline]
Definition at line 135 of file js-native-context-specialization.h.
        : value_(nullptr), effect_(nullptr), control_(nullptr) {}
ValueEffectControl() [2/2]
v8::internal::compiler::JSNativeContextSpecialization::ValueEffectControl::ValueEffectControl (Node * value, Node * effect, Node * control) [inline]
Definition at line 137 of file js-native-context-specialization.h.
        : value_(value), effect_(effect), control_(control) {}
Member Function Documentation
control()
Node* v8::internal::compiler::JSNativeContextSpecialization::ValueEffectControl::control () const [inline]
Definition at line 142 of file js-native-context-specialization.h.
{ return control_; }
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccess().
effect()
Node* v8::internal::compiler::JSNativeContextSpecialization::ValueEffectControl::effect () const [inline]
Definition at line 141 of file js-native-context-specialization.h.
{ return effect_; }
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccess().
value()
Node* v8::internal::compiler::JSNativeContextSpecialization::ValueEffectControl::value () const [inline]
Definition at line 140 of file js-native-context-specialization.h.
{ return value_; }
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccess().
Member Data Documentation
control_
Node* v8::internal::compiler::JSNativeContextSpecialization::ValueEffectControl::control_ [private]
Definition at line 147 of file js-native-context-specialization.h.
effect_
Node* v8::internal::compiler::JSNativeContextSpecialization::ValueEffectControl::effect_ [private]
Definition at line 146 of file js-native-context-specialization.h.
value_
Node* v8::internal::compiler::JSNativeContextSpecialization::ValueEffectControl::value_ [private]
Definition at line 145 of file js-native-context-specialization.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-native-context-specialization.h