v8::internal::maglev::CallWithSpread Class Reference
#include <maglev-ir.h>
Public Member Functions
CallWithSpread (uint64_t bitfield, ValueNode *function, ValueNode *context)
Input & function ()
const Input & function () const
Input & context ()
const Input & context () const
int num_args () const
int num_args_no_spread () const
Input & arg (int i)
void set_arg (int i, ValueNode *node)
auto args_no_spread ()
Input & spread ()
Input & receiver ()
void VerifyInputs (MaglevGraphLabeller *graph_labeller) const
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr int kFunctionIndex = 0
static constexpr int kContextIndex = 1
static constexpr int kFixedInputCount = 2
static constexpr OpProperties kProperties = OpProperties::JSCall()
Private Types
using Base = ValueNodeT< CallWithSpread >
Additional Inherited Members
Detailed Description
Definition at line 10383 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::CallWithSpread::Base = ValueNodeT<CallWithSpread> [private]
Definition at line 10384 of file maglev-ir.h.
Constructor & Destructor Documentation
CallWithSpread()
v8::internal::maglev::CallWithSpread::CallWithSpread (uint64_t bitfield, ValueNode * function, ValueNode * context) [inline]
Definition at line 10394 of file maglev-ir.h.
      : Base(bitfield) {
    set_input(kFunctionIndex, function);
    set_input(kContextIndex, context);
  }
Member Function Documentation
arg()
Input& v8::internal::maglev::CallWithSpread::arg (int i) [inline]
Definition at line 10411 of file maglev-ir.h.
{ return input(i + kFixedInputCount); }
args_no_spread()
auto v8::internal::maglev::CallWithSpread::args_no_spread () [inline]
Definition at line 10415 of file maglev-ir.h.
                        {
    return base::make_iterator_range(
        std::make_reverse_iterator(&arg(-1)),
        std::make_reverse_iterator(&arg(num_args_no_spread() - 1)));
  }
References v8::base::make_iterator_range().
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
context() [1/2]
Input& v8::internal::maglev::CallWithSpread::context () [inline]
Definition at line 10404 of file maglev-ir.h.
{ return input(kContextIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
context() [2/2]
const Input& v8::internal::maglev::CallWithSpread::context () const [inline]
Definition at line 10405 of file maglev-ir.h.
{ return input(kContextIndex); }
function() [1/2]
Input& v8::internal::maglev::CallWithSpread::function () [inline]
Definition at line 10402 of file maglev-ir.h.
{ return input(kFunctionIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
function() [2/2]
const Input& v8::internal::maglev::CallWithSpread::function () const [inline]
Definition at line 10403 of file maglev-ir.h.
{ return input(kFunctionIndex); }
GenerateCode()
void v8::internal::maglev::CallWithSpread::GenerateCode (MaglevAssembler * , const ProcessingState &)
MaxCallStackArgs()
int v8::internal::maglev::CallWithSpread::MaxCallStackArgs () const
num_args()
int v8::internal::maglev::CallWithSpread::num_args () const [inline]
Definition at line 10406 of file maglev-ir.h.
{ return input_count() - kFixedInputCount; }
References v8::internal::compiler::turboshaft::detail::input_count().
num_args_no_spread()
int v8::internal::maglev::CallWithSpread::num_args_no_spread () const [inline]
Definition at line 10407 of file maglev-ir.h.
                                 {
    DCHECK_GT(num_args(), 0);
    return num_args() - 1;
  }
References DCHECK_GT.
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::CallWithSpread::PrintParams (std::ostream & , MaglevGraphLabeller *) const [inline]
Definition at line 10433 of file maglev-ir.h.
{}
receiver()
Input& v8::internal::maglev::CallWithSpread::receiver () [inline]
Definition at line 10424 of file maglev-ir.h.
{ return arg(0); }
set_arg()
void v8::internal::maglev::CallWithSpread::set_arg (int i, ValueNode * node) [inline]
Definition at line 10412 of file maglev-ir.h.
                                       {
    set_input(i + kFixedInputCount, node);
  }
SetValueLocationConstraints()
void v8::internal::maglev::CallWithSpread::SetValueLocationConstraints ()
spread()
Input& v8::internal::maglev::CallWithSpread::spread () [inline]
Definition at line 10420 of file maglev-ir.h.
                  {
    // Spread is the last argument/input.
    return input(input_count() - 1);
  }
References v8::internal::compiler::turboshaft::detail::input_count().
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
VerifyInputs()
void v8::internal::maglev::CallWithSpread::VerifyInputs (MaglevGraphLabeller * graph_labeller) const
Definition at line 965 of file maglev-ir.cc.
                                                                           {
  for (int i = 0; i < input_count(); i++) {
    CheckValueInputIs(this, i, ValueRepresentation::kTagged, graph_labeller);
  }
}
References v8::internal::maglev::CheckValueInputIs(), v8::internal::compiler::turboshaft::detail::input_count(), and v8::internal::maglev::kTagged.
Member Data Documentation
kContextIndex
constexpr int v8::internal::maglev::CallWithSpread::kContextIndex = 1 [static], [constexpr]
Definition at line 10389 of file maglev-ir.h.
kFixedInputCount
constexpr int v8::internal::maglev::CallWithSpread::kFixedInputCount = 2 [static], [constexpr]
Definition at line 10390 of file maglev-ir.h.
kFunctionIndex
constexpr int v8::internal::maglev::CallWithSpread::kFunctionIndex = 0 [static], [constexpr]
Definition at line 10388 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::CallWithSpread::kProperties = OpProperties::JSCall() [static], [constexpr]
Definition at line 10400 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc