cppgc::internal::FatalOutOfMemoryHandler Class Reference
#include <platform.h>
Public Types
using Callback = void(const std::string &, const SourceLocation &, HeapBase *)
Public Member Functions
FatalOutOfMemoryHandler ()=default
FatalOutOfMemoryHandler (HeapBase *heap)
void operator() (const std::string &reason=std::string(), const SourceLocation &=SourceLocation::Current()) const
void SetCustomHandler (Callback *)
FatalOutOfMemoryHandler (const FatalOutOfMemoryHandler &)=delete
FatalOutOfMemoryHandler & operator= (const FatalOutOfMemoryHandler &)=delete
Private Attributes
HeapBase * heap_ = nullptr
Callback * custom_handler_ = nullptr
Detailed Description
Definition at line 18 of file platform.h.
Member Typedef Documentation
Callback
using cppgc::internal::FatalOutOfMemoryHandler::Callback = void(const std::string&, const SourceLocation&, HeapBase*)
Definition at line 20 of file platform.h.
Constructor & Destructor Documentation
FatalOutOfMemoryHandler() [1/3]
cppgc::internal::FatalOutOfMemoryHandler::FatalOutOfMemoryHandler () [default]
FatalOutOfMemoryHandler() [2/3]
cppgc::internal::FatalOutOfMemoryHandler::FatalOutOfMemoryHandler (HeapBase * heap) [inline], [explicit]
Definition at line 23 of file platform.h.
: heap_(heap) {}
FatalOutOfMemoryHandler() [3/3]
cppgc::internal::FatalOutOfMemoryHandler::FatalOutOfMemoryHandler (const FatalOutOfMemoryHandler &) [delete]
Member Function Documentation
operator()()
void cppgc::internal::FatalOutOfMemoryHandler::operator() (const std::string & reason = std::string(), const SourceLocation & loc = SourceLocation::Current()) const
Definition at line 55 of file platform.cc.
                                                                          {
  if (custom_handler_) {
    (*custom_handler_)(reason, loc, heap_);
    FATAL("Custom out of memory handler should not have returned");
  }
#ifdef DEBUG
  V8_Fatal(loc.FileName(), static_cast<int>(loc.Line()),
           "Oilpan: Out of memory (%s)", reason.c_str());
#else // !DEBUG
  V8_Fatal("Oilpan: Out of memory");
#endif // !DEBUG
}
References custom_handler_, FATAL, v8::SourceLocation::FileName(), heap_, v8::SourceLocation::Line(), v8::internal::loc, and V8_Fatal().
operator=()
FatalOutOfMemoryHandler& cppgc::internal::FatalOutOfMemoryHandler::operator= (const FatalOutOfMemoryHandler &) [delete]
SetCustomHandler()
void cppgc::internal::FatalOutOfMemoryHandler::SetCustomHandler (Callback * callback)
Definition at line 69 of file platform.cc.
                                                                 {
  custom_handler_ = callback;
}
References custom_handler_.
Referenced by v8::internal::CppHeap::AttachIsolate(), v8::internal::CppHeap::DetachIsolate(), and v8::internal::CppHeap::InitializeOncePerProcess().
Member Data Documentation
custom_handler_
Callback* cppgc::internal::FatalOutOfMemoryHandler::custom_handler_ = nullptr [private]
Definition at line 37 of file platform.h.
Referenced by operator()(), and SetCustomHandler().
heap_
HeapBase* cppgc::internal::FatalOutOfMemoryHandler::heap_ = nullptr [private]
Definition at line 36 of file platform.h.
Referenced by operator()().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/platform.h
/mnt/V8SourceCode/src/heap/cppgc/platform.cc