cppgc::internal::FreeList Class Reference
#include <free-list.h>
Classes
struct Block
class Entry
Public Member Functions
FreeList ()
FreeList (const FreeList &)=delete
FreeList & operator= (const FreeList &)=delete
FreeList (FreeList &&other) V8_NOEXCEPT
FreeList & operator= (FreeList &&other) V8_NOEXCEPT
Block Allocate (size_t)
void Add (Block)
std::pair< Address, Address > AddReturningUnusedBounds (Block)
void Append (FreeList &&)
void Clear ()
size_t Size () const
bool IsEmpty () const
void CollectStatistics (HeapStatistics::FreeListStatistics &)
bool ContainsForTesting (Block) const
Private Member Functions
bool IsConsistent (size_t) const
Private Attributes
std::array< Entry *, kPageSizeLog2 > free_list_heads_
std::array< Entry *, kPageSizeLog2 > free_list_tails_
size_t biggest_free_list_index_ = 0
Detailed Description
Definition at line 27 of file free-list.h.
Constructor & Destructor Documentation
FreeList() [1/3]
cppgc::internal::FreeList::FreeList ()
Definition at line 54 of file free-list.cc.
{ Clear(); }
References Clear().
FreeList() [2/3]
cppgc::internal::FreeList::FreeList (const FreeList &) [delete]
FreeList() [3/3]
cppgc::internal::FreeList::FreeList (FreeList && other)
Definition at line 56 of file free-list.cc.
    : free_list_heads_(std::move(other.free_list_heads_)),
      free_list_tails_(std::move(other.free_list_tails_)),
      biggest_free_list_index_(std::move(other.biggest_free_list_index_)) {
  other.Clear();
}
Member Function Documentation
Add()
void cppgc::internal::FreeList::Add (FreeList::Block block)
Definition at line 70 of file free-list.cc.
{ AddReturningUnusedBounds(block); }
References AddReturningUnusedBounds().
Referenced by cppgc::internal::anonymous_namespace{sweeper.cc}::SweepFinalizer::FinalizePage().
AddReturningUnusedBounds()
std::pair< Address, Address > cppgc::internal::FreeList::AddReturningUnusedBounds (Block block)
Definition at line 72 of file free-list.cc.
                                                                        {
  const size_t size = block.size;
  DCHECK_GT(kPageSize, size);
  DCHECK_LE(sizeof(HeapObjectHeader), size);
  if (size < sizeof(Entry)) {
    // Create wasted entry. This can happen when an almost emptied linear
    // allocation buffer is returned to the freelist.
    // This could be SET_MEMORY_ACCESSIBLE. Since there's no payload, the next
    // operating overwrites the memory completely, and we can thus avoid
    // zeroing it out.
    auto& filler = Filler::CreateAt(block.address, size);
    USE(filler);
    DCHECK_EQ(reinterpret_cast<Address>(block.address) + size,
              filler.ObjectEnd());
    DCHECK_EQ(reinterpret_cast<Address>(&filler + 1), filler.ObjectEnd());
    return {reinterpret_cast<Address>(&filler + 1),
            reinterpret_cast<Address>(&filler + 1)};
  }
  Entry& entry = Entry::CreateAt(block.address, size);
  const size_t index = BucketIndexForSize(static_cast<uint32_t>(size));
  entry.Link(&free_list_heads_[index]);
  biggest_free_list_index_ = std::max(biggest_free_list_index_, index);
  if (!entry.Next()) {
    free_list_tails_[index] = &entry;
  }
  DCHECK_EQ(entry.ObjectEnd(), reinterpret_cast<Address>(&entry) + size);
  return {reinterpret_cast<Address>(&entry + 1),
          reinterpret_cast<Address>(&entry) + size};
}
References cppgc::internal::FreeList::Block::address, biggest_free_list_index_, cppgc::internal::anonymous_namespace{free-list.cc}::BucketIndexForSize(), cppgc::internal::FreeList::Entry::CreateAt(), cppgc::internal::Filler::CreateAt(), DCHECK_EQ, DCHECK_GT, DCHECK_LE, free_list_heads_, free_list_tails_, v8::internal::index, cppgc::internal::kPageSize, cppgc::internal::FreeList::Entry::Link(), cppgc::internal::FreeList::Entry::Next(), cppgc::internal::HeapObjectHeader::ObjectEnd(), size(), cppgc::internal::FreeList::Block::size, and USE.
Referenced by Add().
Allocate()
FreeList::Block cppgc::internal::FreeList::Allocate (size_t allocation_size)
Definition at line 133 of file free-list.cc.
                                                       {
  // Try reusing a block from the largest bin. The underlying reasoning
  // being that we want to amortize this slow allocation call by carving
  // off as a large a free block as possible in one go; a block that will
  // service this block and let following allocations be serviced quickly
  // by bump allocation.
  // bucket_size represents minimal size of entries in a bucket.
  size_t bucket_size = static_cast<size_t>(1) << biggest_free_list_index_;
  size_t index = biggest_free_list_index_;
  for (; index > 0; --index, bucket_size >>= 1) {
    DCHECK(IsConsistent(index));
    Entry* entry = free_list_heads_[index];
    if (allocation_size > bucket_size) {
      // Final bucket candidate; check initial entry if it is able
      // to service this allocation. Do not perform a linear scan,
      // as it is considered too costly.
      if (!entry || entry->AllocatedSize() < allocation_size) break;
    }
    if (entry) {
      if (!entry->Next()) {
        DCHECK_EQ(entry, free_list_tails_[index]);
        free_list_tails_[index] = nullptr;
      }
      entry->Unlink(&free_list_heads_[index]);
      biggest_free_list_index_ = index;
      return {entry, entry->AllocatedSize()};
    }
  }
  biggest_free_list_index_ = index;
  return {nullptr, 0u};
}
References cppgc::internal::HeapObjectHeader::AllocatedSize(), biggest_free_list_index_, DCHECK, DCHECK_EQ, free_list_heads_, free_list_tails_, v8::internal::index, IsConsistent(), cppgc::internal::FreeList::Entry::Next(), and cppgc::internal::FreeList::Entry::Unlink().
Append()
void cppgc::internal::FreeList::Append (FreeList && other)
Definition at line 104 of file free-list.cc.
                                      {
  DCHECK_NE(this, &other);
#if DEBUG
  const size_t expected_size = Size() + other.Size();
#endif
  // Newly created entries get added to the head.
  for (size_t index = 0; index < free_list_tails_.size(); ++index) {
    Entry* other_tail = other.free_list_tails_[index];
    Entry*& this_head = this->free_list_heads_[index];
    if (other_tail) {
      other_tail->SetNext(this_head);
      if (!this_head) {
        this->free_list_tails_[index] = other_tail;
      }
      this_head = other.free_list_heads_[index];
      other.free_list_heads_[index] = nullptr;
      other.free_list_tails_[index] = nullptr;
    }
  }
  biggest_free_list_index_ =
      std::max(biggest_free_list_index_, other.biggest_free_list_index_);
  other.biggest_free_list_index_ = 0;
#if DEBUG
  DCHECK_EQ(expected_size, Size());
#endif
  DCHECK(other.IsEmpty());
}
References biggest_free_list_index_, DCHECK, DCHECK_EQ, DCHECK_NE, free_list_heads_, free_list_tails_, v8::internal::index, cppgc::internal::FreeList::Entry::SetNext(), and Size().
Referenced by cppgc::internal::anonymous_namespace{sweeper.cc}::SweepFinalizer::FinalizePage().
Clear()
void cppgc::internal::FreeList::Clear ()
Definition at line 165 of file free-list.cc.
                     {
  std::fill(free_list_heads_.begin(), free_list_heads_.end(), nullptr);
  std::fill(free_list_tails_.begin(), free_list_tails_.end(), nullptr);
  biggest_free_list_index_ = 0;
}
References biggest_free_list_index_, free_list_heads_, and free_list_tails_.
Referenced by cppgc::internal::anonymous_namespace{sweeper.cc}::SweepFinalizer::FinalizePage(), and FreeList().
CollectStatistics()
void cppgc::internal::FreeList::CollectStatistics (HeapStatistics::FreeListStatistics & free_list_stats)
Definition at line 208 of file free-list.cc.
                                                       {
  std::vector<size_t>& bucket_size = free_list_stats.bucket_size;
  std::vector<size_t>& free_count = free_list_stats.free_count;
  std::vector<size_t>& free_size = free_list_stats.free_size;
  DCHECK(bucket_size.empty());
  DCHECK(free_count.empty());
  DCHECK(free_size.empty());
  for (size_t i = 0; i < kPageSizeLog2; ++i) {
    size_t entry_count = 0;
    size_t entry_size = 0;
    for (Entry* entry = free_list_heads_[i]; entry; entry = entry->Next()) {
      ++entry_count;
      entry_size += entry->AllocatedSize();
    }
    bucket_size.push_back(static_cast<size_t>(1) << i);
    free_count.push_back(entry_count);
    free_size.push_back(entry_size);
  }
}
References cppgc::HeapStatistics::FreeListStatistics::bucket_size, DCHECK, cppgc::HeapStatistics::FreeListStatistics::free_count, free_list_heads_, cppgc::HeapStatistics::FreeListStatistics::free_size, v8::internal::anonymous_namespace{json-stringifier.cc}::i, and cppgc::internal::kPageSizeLog2.
ContainsForTesting()
bool cppgc::internal::FreeList::ContainsForTesting (Block block) const
Definition at line 187 of file free-list.cc.
                                                   {
  for (Entry* list : free_list_heads_) {
    for (Entry* entry = list; entry; entry = entry->Next()) {
      if (entry <= block.address &&
          (reinterpret_cast<Address>(block.address) + block.size <=
           reinterpret_cast<Address>(entry) + entry->AllocatedSize()))
        return true;
    }
  }
  return false;
}
References cppgc::internal::FreeList::Block::address, free_list_heads_, cppgc::internal::FreeList::Entry::Next(), and cppgc::internal::FreeList::Block::size.
IsConsistent()
bool cppgc::internal::FreeList::IsConsistent (size_t index) const [private]
Definition at line 199 of file free-list.cc.
                                              {
  // Check that freelist head and tail pointers are consistent, i.e.
  // - either both are nulls (no entries in the bucket);
  // - or both are non-nulls and the tail points to the end.
  return (!free_list_heads_[index] && !free_list_tails_[index]) ||
         (free_list_heads_[index] && free_list_tails_[index] &&
          !free_list_tails_[index]->Next());
}
References free_list_heads_, free_list_tails_, and v8::internal::index.
Referenced by Allocate().
IsEmpty()
bool cppgc::internal::FreeList::IsEmpty () const
Definition at line 182 of file free-list.cc.
                             {
  return std::all_of(free_list_heads_.cbegin(), free_list_heads_.cend(),
                     [](const auto* entry) { return !entry; });
}
References v8::base::all_of(), and free_list_heads_.
operator=() [1/2]
FreeList& cppgc::internal::FreeList::operator= (const FreeList &) [delete]
operator=() [2/2]
FreeList & cppgc::internal::FreeList::operator= (FreeList && other)
Definition at line 63 of file free-list.cc.
                                                          {
  Clear();
  Append(std::move(other));
  DCHECK(other.IsEmpty());
  return *this;
}
References DCHECK.
Size()
size_t cppgc::internal::FreeList::Size () const
Definition at line 171 of file free-list.cc.
                            {
  size_t size = 0;
  for (auto* entry : free_list_heads_) {
    while (entry) {
      size += entry->AllocatedSize();
      entry = entry->Next();
    }
  }
  return size;
}
References free_list_heads_, and size().
Referenced by Append().
Member Data Documentation
biggest_free_list_index_
size_t cppgc::internal::FreeList::biggest_free_list_index_ = 0 [private]
Definition at line 72 of file free-list.h.
Referenced by AddReturningUnusedBounds(), Allocate(), Append(), and Clear().
free_list_heads_
std::array<Entry*, kPageSizeLog2> cppgc::internal::FreeList::free_list_heads_ [private]
Definition at line 70 of file free-list.h.
Referenced by AddReturningUnusedBounds(), Allocate(), Append(), Clear(), CollectStatistics(), ContainsForTesting(), IsConsistent(), IsEmpty(), and Size().
free_list_tails_
std::array<Entry*, kPageSizeLog2> cppgc::internal::FreeList::free_list_tails_ [private]
Definition at line 71 of file free-list.h.
Referenced by AddReturningUnusedBounds(), Allocate(), Append(), Clear(), and IsConsistent().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/free-list.h
/mnt/V8SourceCode/src/heap/cppgc/free-list.cc