v8::internal::compiler::IrOpcode Class Reference
#include <opcodes.h>
Public Types
enum Value { kLast
 }
Static Public Member Functions
static char const * Mnemonic (Value value)
static bool IsCommonOpcode (Value value)
static bool IsControlOpcode (Value value)
static bool IsJsOpcode (Value value)
static bool IsMachineOpcode (Value value)
static bool IsMachineConstantOpcode (Value value)
static bool IsConstantOpcode (Value value)
static bool IsPhiOpcode (Value value)
static bool IsMergeOpcode (Value value)
static bool IsIfProjectionOpcode (Value value)
static bool IsGraphTerminator (Value value)
static bool IsInlineeOpcode (Value value)
static bool IsComparisonOpcode (Value value)
static bool IsContextChainExtendingOpcode (Value value)
static bool IsFeedbackCollectingOpcode (Value value)
static bool IsFeedbackCollectingOpcode (int16_t value)
static bool isAtomicOpOpcode (Value value)
Detailed Description
Definition at line 1346 of file opcodes.h.
Member Enumeration Documentation
Value
enum v8::internal::compiler::IrOpcode::Value
Enumerator
kLast
Definition at line 1348 of file opcodes.h.
             {
#define DECLARE_OPCODE(x, ...) k##x,
    ALL_OP_LIST(DECLARE_OPCODE)
#undef DECLARE_OPCODE
        kLast = -1
#define COUNT_OPCODE(...) +1
                ALL_OP_LIST(COUNT_OPCODE)
#undef COUNT_OPCODE
  };
Member Function Documentation
isAtomicOpOpcode()
static bool v8::internal::compiler::IrOpcode::isAtomicOpOpcode (Value value) [inline], [static]
Definition at line 1506 of file opcodes.h.
                                            {
    switch (value) {
    #define CASE(Name, ...) \
      case k##Name: \
        return true;
      MACHINE_ATOMIC_OP_LIST(CASE)
      default:
        return false;
    #undef CASE
    }
    UNREACHABLE();
  }
References CASE, MACHINE_ATOMIC_OP_LIST, v8::internal::UNREACHABLE(), and v8::internal::value.
Referenced by v8::internal::compiler::AtomicOpParametersOf().
IsCommonOpcode()
static bool v8::internal::compiler::IrOpcode::IsCommonOpcode (Value value) [inline], [static]
Definition at line 1362 of file opcodes.h.
                                          {
    return kStart <= value && value <= kStaticAssert;
  }
References v8::kStart, and v8::internal::value.
Referenced by v8::internal::compiler::NodeProperties::IsCommon().
IsComparisonOpcode()
static bool v8::internal::compiler::IrOpcode::IsComparisonOpcode (Value value) [inline], [static]
Definition at line 1434 of file opcodes.h.
                                              {
#define CASE(Name, ...) \
  case k##Name: \
    return true;
    switch (value) {
      JS_COMPARE_BINOP_LIST(CASE);
      SIMPLIFIED_COMPARE_BINOP_LIST(CASE);
      MACHINE_COMPARE_BINOP_LIST(CASE);
      default:
        return false;
    }
#undef CASE
    UNREACHABLE();
  }
References CASE, JS_COMPARE_BINOP_LIST, MACHINE_COMPARE_BINOP_LIST, SIMPLIFIED_COMPARE_BINOP_LIST, v8::internal::UNREACHABLE(), and v8::internal::value.
Referenced by v8::internal::compiler::NodeMatcher::IsComparison().
IsConstantOpcode()
static bool v8::internal::compiler::IrOpcode::IsConstantOpcode (Value value) [inline], [static]
Definition at line 1395 of file opcodes.h.
                                            {
#define CASE(Name) \
  case k##Name: \
    return true;
    switch (value) {
      CONSTANT_OP_LIST(CASE);
      default:
        return false;
    }
#undef CASE
    UNREACHABLE();
  }
References CASE, CONSTANT_OP_LIST, v8::internal::UNREACHABLE(), and v8::internal::value.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::CreateStringConstant(), and v8::internal::compiler::NodeProperties::IsConstant().
IsContextChainExtendingOpcode()
static bool v8::internal::compiler::IrOpcode::IsContextChainExtendingOpcode (Value value) [inline], [static]
Definition at line 1449 of file opcodes.h.
                                                         {
    return kJSCreateFunctionContext <= value && value <= kJSCreateBlockContext;
  }
References v8::internal::value.
Referenced by v8::internal::compiler::NodeProperties::GetOuterContext().
IsControlOpcode()
static bool v8::internal::compiler::IrOpcode::IsControlOpcode (Value value) [inline], [static]
Definition at line 1367 of file opcodes.h.
                                           {
    return kStart <= value && value <= kEnd;
  }
References v8::kStart, and v8::internal::value.
Referenced by v8::internal::compiler::NodeProperties::IsControl().
IsFeedbackCollectingOpcode() [1/2]
static bool v8::internal::compiler::IrOpcode::IsFeedbackCollectingOpcode (int16_t value) [inline], [static]
Definition at line 1501 of file opcodes.h.
                                                        {
    DCHECK(0 <= value && value <= kLast);
    return IsFeedbackCollectingOpcode(static_cast<IrOpcode::Value>(value));
  }
References v8::internal::DCHECK(), v8::internal::kLast, and v8::internal::value.
IsFeedbackCollectingOpcode() [2/2]
static bool v8::internal::compiler::IrOpcode::IsFeedbackCollectingOpcode (Value value) [inline], [static]
Definition at line 1455 of file opcodes.h.
                                                      {
#define CASE(Name, ...) \
  case k##Name: \
    return true;
    switch (value) {
      JS_ARITH_BINOP_LIST(CASE)
      JS_ARITH_UNOP_LIST(CASE)
      JS_BITWISE_BINOP_LIST(CASE)
      JS_BITWISE_UNOP_LIST(CASE)
      JS_COMPARE_BINOP_LIST(CASE)
      case kJSCall:
      case kJSCallWithArrayLike:
      case kJSCallWithSpread:
      case kJSCloneObject:
      case kJSConstruct:
      case kJSConstructWithArrayLike:
      case kJSConstructWithSpread:
      case kJSCreateEmptyLiteralArray:
      case kJSCreateLiteralArray:
      case kJSCreateLiteralObject:
      case kJSCreateLiteralRegExp:
      case kJSDefineKeyedOwnProperty:
      case kJSForInNext:
      case kJSForInPrepare:
      case kJSGetIterator:
      case kJSGetTemplateObject:
      case kJSHasProperty:
      case kJSInstanceOf:
      case kJSLoadGlobal:
      case kJSLoadNamed:
      case kJSLoadNamedFromSuper:
      case kJSLoadProperty:
      case kJSDefineKeyedOwnPropertyInLiteral:
      case kJSStoreGlobal:
      case kJSStoreInArrayLiteral:
      case kJSSetNamedProperty:
      case kJSDefineNamedOwnProperty:
      case kJSSetKeyedProperty:
        return true;
      default:
        return false;
    }
#undef CASE
    UNREACHABLE();
  }
References CASE, JS_ARITH_BINOP_LIST, JS_ARITH_UNOP_LIST, JS_BITWISE_BINOP_LIST, JS_BITWISE_UNOP_LIST, JS_COMPARE_BINOP_LIST, v8::internal::UNREACHABLE(), and v8::internal::value.
IsGraphTerminator()
static bool v8::internal::compiler::IrOpcode::IsGraphTerminator (Value value) [inline], [static]
Definition at line 1423 of file opcodes.h.
                                             {
    return value == kDeoptimize || value == kReturn || value == kTailCall ||
           value == kTerminate || value == kThrow;
  }
References v8::internal::value.
Referenced by v8::internal::compiler::Verifier::Visitor::Check(), v8::internal::compiler::DeadCodeElimination::ReduceNode(), and v8::internal::compiler::UnrollLoop().
IsIfProjectionOpcode()
static bool v8::internal::compiler::IrOpcode::IsIfProjectionOpcode (Value value) [inline], [static]
Definition at line 1416 of file opcodes.h.
                                                {
    return kIfTrue <= value && value <= kIfDefault;
  }
References v8::internal::value.
Referenced by v8::internal::compiler::RawMachineAssembler::MakeReschedulable().
IsInlineeOpcode()
static bool v8::internal::compiler::IrOpcode::IsInlineeOpcode (Value value) [inline], [static]
Definition at line 1429 of file opcodes.h.
                                           {
    return value == kJSConstruct || value == kJSCall;
  }
References v8::internal::value.
Referenced by v8::internal::compiler::JSInliner::DetermineCallContext(), v8::internal::compiler::JSInliner::DetermineCallTarget(), v8::internal::compiler::JSInliningHeuristic::Finalize(), v8::internal::compiler::JSInliner::InlineCall(), v8::internal::compiler::JSInliningHeuristic::Reduce(), and v8::internal::compiler::JSInliner::ReduceJSCall().
IsJsOpcode()
static bool v8::internal::compiler::IrOpcode::IsJsOpcode (Value value) [inline], [static]
Definition at line 1372 of file opcodes.h.
                                      {
    return kJSEqual <= value && value <= kJSDebugger;
  }
References v8::internal::value.
Referenced by v8::internal::compiler::OperatorProperties::HasContextInput().
IsMachineConstantOpcode()
static bool v8::internal::compiler::IrOpcode::IsMachineConstantOpcode (Value value) [inline], [static]
Definition at line 1382 of file opcodes.h.
                                                   {
    switch (value) {
#define CASE(name) \
  case k##name: \
    return true;
      MACHINE_LEVEL_CONSTANT_OP_LIST(CASE)
#undef CASE
      default:
        return false;
    }
  }
References CASE, MACHINE_LEVEL_CONSTANT_OP_LIST, and v8::internal::value.
Referenced by v8::internal::compiler::SimplifiedLoweringVerifier::GetType(), v8::internal::compiler::SimplifiedLoweringVerifier::RecordMachineUsesOfConstant(), and v8::internal::compiler::RepresentationSelector::UpdateFeedbackType().
IsMachineOpcode()
static bool v8::internal::compiler::IrOpcode::IsMachineOpcode (Value value) [inline], [static]
Definition at line 1377 of file opcodes.h.
                                           {
    return kWord32Clz <= value && value <= kTraceInstruction;
  }
References v8::internal::value.
Referenced by v8::internal::compiler::RepresentationSelector::UpdateFeedbackType().
IsMergeOpcode()
static bool v8::internal::compiler::IrOpcode::IsMergeOpcode (Value value) [inline], [static]
Definition at line 1412 of file opcodes.h.
                                         {
    return value == kMerge || value == kLoop;
  }
References v8::internal::compiler::kLoop, and v8::internal::value.
Referenced by v8::internal::compiler::ScheduleLateNodeVisitor::GetBlockForUse(), v8::internal::compiler::CommonOperatorReducer::ReduceEffectPhi(), v8::internal::compiler::DeadCodeElimination::ReduceLoopOrMerge(), v8::internal::compiler::CommonOperatorReducer::ReducePhi(), and v8::internal::compiler::ScheduleLateNodeVisitor::VisitNode().
IsPhiOpcode()
static bool v8::internal::compiler::IrOpcode::IsPhiOpcode (Value value) [inline], [static]
Definition at line 1408 of file opcodes.h.
                                       {
    return value == kPhi || value == kEffectPhi;
  }
References v8::internal::compiler::kPhi, and v8::internal::value.
Referenced by v8::internal::compiler::DiamondMatcher::FalseInputOf(), v8::internal::compiler::ScheduleLateNodeVisitor::GetBlockForUse(), v8::internal::compiler::LoopTree::HeaderNode(), v8::internal::compiler::NodeProperties::IsPhi(), v8::internal::compiler::RawMachineAssembler::MakeReschedulable(), v8::internal::compiler::JSONGraphWriter::PrintNode(), v8::internal::compiler::CommonOperatorReducer::ReduceMerge(), and v8::internal::compiler::DiamondMatcher::TrueInputOf().
Mnemonic()
char const * v8::internal::compiler::IrOpcode::Mnemonic (Value value) [static]
Definition at line 28 of file opcodes.cc.
                                          {
  DCHECK_LE(0, static_cast<int>(value));
  DCHECK_LE(static_cast<int>(value), IrOpcode::Value::kLast);
  size_t const n = std::min<size_t>(value, arraysize(kMnemonics) - 1);
  return kMnemonics[n];
}
References arraysize, DCHECK_LE, v8::internal::compiler::anonymous_namespace{opcodes.cc}::kMnemonics, and v8::internal::value.
Referenced by v8::internal::compiler::operator<<(), and v8::internal::compiler::JSONGraphWriter::PrintNode().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/opcodes.h
/mnt/V8SourceCode/src/compiler/opcodes.cc