v8::internal::WasmStruct Class Reference
#include <wasm-objects.h>
Public Member Functions
Address RawFieldAddress (int raw_offset)
ObjectSlot RawField (int raw_offset)
V8_EXPORT_PRIVATE wasm::WasmValue GetFieldValue (uint32_t field_index)
void SetTaggedFieldValue (int raw_offset, Tagged< Object > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
Static Public Member Functions
static const wasm::CanonicalStructType * GcSafeType (Tagged< Map > map)
static int Size (const wasm::StructType *type)
static int Size (const wasm::CanonicalStructType *type)
static int GcSafeSize (Tagged< Map > map)
static void EncodeInstanceSizeInMap (int instance_size, Tagged< Map > map)
static int DecodeInstanceSizeFromMap (Tagged< Map > map)
static DirectHandle< WasmStruct > AllocateDescriptorUninitialized (Isolate *isolate, DirectHandle< WasmTrustedInstanceData > trusted_data, wasm::ModuleTypeIndex index, DirectHandle< Map > map, DirectHandle< Object > first_field)
static DirectHandle< JSObject > AllocatePrototype (Isolate *isolate, DirectHandle< JSPrototype > parent)
Detailed Description
Definition at line 1408 of file wasm-objects.h.
Member Function Documentation
AllocateDescriptorUninitialized()
DirectHandle< WasmStruct > v8::internal::WasmStruct::AllocateDescriptorUninitialized (Isolate * isolate, DirectHandle< WasmTrustedInstanceData > trusted_data, wasm::ModuleTypeIndex index, DirectHandle< Map > map, DirectHandle< Object > first_field) [static]
Definition at line 2259 of file wasm-objects.cc.
                                      {
  const wasm::WasmModule* module = trusted_data->module();
  const wasm::TypeDefinition& type = module->type(index);
  DCHECK(type.is_descriptor());
  // TODO(jkummerow): Figure out support for shared objects.
  if (type.is_shared) UNIMPLEMENTED();
  wasm::CanonicalTypeIndex described_index =
      module->canonical_type_id(type.describes);
  DirectHandle<Map> rtt_parent{
      Cast<Map>(trusted_data->managed_object_maps()->get(type.describes.index)),
      isolate};
  DirectHandle<NativeContext> context(
      Cast<NativeContext>(trusted_data->native_context()), isolate);
  DirectHandle<Map> rtt =
      CreateStructMap(isolate, described_index, rtt_parent, context);
  if (v8_flags.wasm_explicit_prototypes && !IsSmi(*first_field) &&
      IsWasmDescriptorOptions(Cast<HeapObject>(*first_field))) {
    DirectHandle<JSPrototype> prototype = direct_handle(
        Cast<JSReceiver>(
            Cast<WasmDescriptorOptions>(*first_field)->prototype()),
        isolate);
    Map::SetPrototype(isolate, rtt, prototype);
  }
  DirectHandle<WasmStruct> descriptor =
      isolate->factory()->NewWasmStructUninitialized(type.struct_type, map,
                                                     AllocationType::kOld);
  // The struct's body is uninitialized. As soon as we return, callers will
  // take care of that. Until then, no allocations are allowed.
  DisallowGarbageCollection no_gc;
  descriptor->set_described_rtt(*rtt);
  rtt->set_custom_descriptor(*descriptor);
  return descriptor;
}
References v8::internal::wasm::WasmModule::canonical_type_id(), v8::internal::CreateStructMap(), v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::index, v8::internal::IsSmi(), v8::internal::kOld, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::prototype, v8::internal::Map::SetPrototype(), v8::internal::tracing::type, v8::internal::wasm::WasmModule::type(), v8::internal::UNIMPLEMENTED(), and v8::internal::v8_flags.
Referenced by v8::internal::RUNTIME_FUNCTION().
AllocatePrototype()
DirectHandle< JSObject > v8::internal::WasmStruct::AllocatePrototype (Isolate * isolate, DirectHandle< JSPrototype > parent) [static]
Definition at line 2212 of file wasm-objects.cc.
                                                        {
  // Follow the example of {CreateClassPrototype} and create a map with no
  // in-object properties.
  // TODO(ishell): If we support caching the zero-in-object-properties map,
  // update this code.
  DirectHandle<Map> map = Map::Create(isolate, 0);
  map->set_is_prototype_map(true);
  Map::SetPrototype(isolate, map, parent);
  DirectHandle<JSObject> prototype =
      isolate->factory()->NewJSObjectFromMap(map);
  isolate->UpdateProtectorsOnSetPrototype(prototype, parent);
  return prototype;
}
References v8::internal::Map::Create(), v8::internal::Isolate::factory(), v8::internal::Factory::NewJSObjectFromMap(), v8::internal::prototype, v8::internal::Map::SetPrototype(), and v8::internal::Isolate::UpdateProtectorsOnSetPrototype().
Referenced by v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Direct_Impl(), and v8::internal::wasm::JSPrototypesSetup::MaterializeDescriptorOptionsImpl().
DecodeInstanceSizeFromMap()
int v8::internal::WasmStruct::DecodeInstanceSizeFromMap (Tagged< Map > map) [inline], [static]
Definition at line 733 of file wasm-objects-inl.h.
                                                         {
  return (map->WasmByte2() << (8 + kObjectAlignmentBits)) |
         (map->WasmByte1() << kObjectAlignmentBits);
}
References v8::internal::kObjectAlignmentBits.
Referenced by GcSafeSize().
EncodeInstanceSizeInMap()
void v8::internal::WasmStruct::EncodeInstanceSizeInMap (int instance_size, Tagged< Map > map) [inline], [static]
Definition at line 719 of file wasm-objects-inl.h.
                                                                           {
  // WasmStructs can be bigger than the {map.instance_size_in_words} field
  // can describe; yet we have to store the instance size somewhere on the
  // map so that the GC can read it without relying on any other objects
  // still being around. To solve this problem, we store the instance size
  // in two other fields that are otherwise unused for WasmStructs.
  static_assert(0xFFFF > ((kHeaderSize + wasm::kMaxValueTypeSize *
                                             wasm::kV8MaxWasmStructFields) >>
                          kObjectAlignmentBits));
  map->SetWasmByte1((instance_size >> kObjectAlignmentBits) & 0xff);
  map->SetWasmByte2(instance_size >> (8 + kObjectAlignmentBits));
}
References v8::internal::wasm::kMaxValueTypeSize, v8::internal::kObjectAlignmentBits, and v8::internal::wasm::kV8MaxWasmStructFields.
Referenced by v8::internal::CreateStructMap().
GcSafeSize()
int v8::internal::WasmStruct::GcSafeSize (Tagged< Map > map) [inline], [static]
Definition at line 738 of file wasm-objects-inl.h.
                                          {
  return DecodeInstanceSizeFromMap(map);
}
References DecodeInstanceSizeFromMap().
Referenced by v8::internal::HeapObject::SizeFromMap().
GcSafeType()
const wasm::CanonicalStructType * v8::internal::WasmStruct::GcSafeType (Tagged< Map > map) [static]
Definition at line 2202 of file wasm-objects.cc.
                                                                     {
  DCHECK_EQ(WASM_STRUCT_TYPE, map->instance_type());
  Tagged<HeapObject> raw = Cast<HeapObject>(map->constructor_or_back_pointer());
  // The {WasmTypeInfo} might be in the middle of being moved, which is why we
  // can't read its map for a checked cast. But we can rely on its native type
  // pointer being intact in the old location.
  Tagged<WasmTypeInfo> type_info = UncheckedCast<WasmTypeInfo>(raw);
  return wasm::GetTypeCanonicalizer()->LookupStruct(type_info->type_index());
}
References DCHECK_EQ, v8::internal::wasm::GetTypeCanonicalizer(), and v8::internal::wasm::TypeCanonicalizer::LookupStruct().
GetFieldValue()
wasm::WasmValue v8::internal::WasmStruct::GetFieldValue (uint32_t field_index)
Definition at line 2298 of file wasm-objects.cc.
                                                      {
  const wasm::CanonicalStructType* type =
      wasm::GetTypeCanonicalizer()->LookupStruct(
          map()->wasm_type_info()->type_index());
  wasm::CanonicalValueType field_type = type->field(index);
  int field_offset = WasmStruct::kHeaderSize + type->field_offset(index);
  Address field_address = GetFieldAddress(field_offset);
  switch (field_type.kind()) {
#define CASE_TYPE(valuetype, ctype) \
  case wasm::valuetype: \
    return wasm::WasmValue(base::ReadUnalignedValue<ctype>(field_address));
    CASE_TYPE(kI8, int8_t)
    CASE_TYPE(kI16, int16_t)
    FOREACH_WASMVALUE_CTYPES(CASE_TYPE)
#undef CASE_TYPE
    case wasm::kF16:
      return wasm::WasmValue(fp16_ieee_to_fp32_value(
          base::ReadUnalignedValue<uint16_t>(field_address)));
    case wasm::kRef:
    case wasm::kRefNull: {
      DirectHandle<Object> ref(TaggedField<Object>::load(*this, field_offset),
                               GetIsolateFromWritableObject(*this));
      return wasm::WasmValue(ref, field_type);
    }
    case wasm::kVoid:
    case wasm::kTop:
    case wasm::kBottom:
      UNREACHABLE();
  }
}
References CASE_TYPE, FOREACH_WASMVALUE_CTYPES, v8::internal::GetIsolateFromWritableObject(), v8::internal::wasm::GetTypeCanonicalizer(), v8::internal::index, v8::internal::kI16, v8::internal::kI8, v8::internal::wasm::ValueTypeBase::kind(), v8::internal::wasm::TypeCanonicalizer::LookupStruct(), v8::internal::tracing::type, and v8::internal::UNREACHABLE().
RawField()
ObjectSlot v8::internal::WasmStruct::RawField (int raw_offset) [inline]
Definition at line 747 of file wasm-objects-inl.h.
                                              {
  return ObjectSlot(RawFieldAddress(raw_offset));
}
References RawFieldAddress().
RawFieldAddress()
Address v8::internal::WasmStruct::RawFieldAddress (int raw_offset) [inline]
Definition at line 742 of file wasm-objects-inl.h.
                                                  {
  int offset = WasmStruct::kHeaderSize + raw_offset;
  return FIELD_ADDR(*this, offset);
}
References FIELD_ADDR.
Referenced by RawField().
SetTaggedFieldValue()
void v8::internal::WasmStruct::SetTaggedFieldValue (int raw_offset, Tagged< Object > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 751 of file wasm-objects-inl.h.
                                                            {
  int offset = WasmStruct::kHeaderSize + raw_offset;
  TaggedField<Object>::store(*this, offset, value);
  CONDITIONAL_WRITE_BARRIER(*this, offset, value, mode);
}
References CONDITIONAL_WRITE_BARRIER, mode(), v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::store(), and v8::internal::value.
Size() [1/2]
int v8::internal::WasmStruct::Size (const wasm::CanonicalStructType * type) [inline], [static]
Definition at line 1455 of file wasm-objects.h.
                                                        {
  // Object size must fit into a Smi (because of filler objects), and its
  // computation must not overflow.
  static_assert(Smi::kMaxValue <= kMaxInt);
  DCHECK_LE(type->total_fields_size(), Smi::kMaxValue - kHeaderSize);
  return std::max(kHeaderSize + static_cast<int>(type->total_fields_size()),
                  Heap::kMinObjectSizeInTaggedWords * kTaggedSize);
}
References DCHECK_LE, v8::internal::kMaxInt, v8::internal::Smi::kMaxValue, v8::internal::Heap::kMinObjectSizeInTaggedWords, v8::internal::kTaggedSize, and v8::internal::tracing::type.
Size() [2/2]
int v8::internal::WasmStruct::Size (const wasm::StructType * type) [inline], [static]
Definition at line 1446 of file wasm-objects.h.
                                               {
  // Object size must fit into a Smi (because of filler objects), and its
  // computation must not overflow.
  static_assert(Smi::kMaxValue <= kMaxInt);
  DCHECK_LE(type->total_fields_size(), Smi::kMaxValue - kHeaderSize);
  return std::max(kHeaderSize + static_cast<int>(type->total_fields_size()),
                  Heap::kMinObjectSizeInTaggedWords * kTaggedSize);
}
References DCHECK_LE, v8::internal::kMaxInt, v8::internal::Smi::kMaxValue, v8::internal::Heap::kMinObjectSizeInTaggedWords, v8::internal::kTaggedSize, and v8::internal::tracing::type.
Referenced by v8::internal::CreateStructMap(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructNew(), and v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::WasmAllocateStruct().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-objects.h
/mnt/V8SourceCode/src/wasm/wasm-objects-inl.h
/mnt/V8SourceCode/src/wasm/wasm-objects.cc