v8::internal::maglev::MaglevInliner Class Reference
#include <maglev-inlining.h>
Public Member Functions
MaglevInliner (Graph *graph)
void Run (bool is_tracing_maglev_graphs_enabled)
Private Member Functions
compiler::JSHeapBroker * broker () const
Zone * zone () const
MaglevCallSiteInfo * ChooseNextCallSite ()
MaybeReduceResult BuildInlineFunction (MaglevCallSiteInfo *call_site)
std::vector< BasicBlock * > TruncateGraphAt (BasicBlock *block)
template<class Node , typename... Args>
ValueNode * AddNodeAtBlockEnd (MaglevGraphBuilder &builder, std::initializer_list< ValueNode * > inputs, Args &&... args)
void RegisterNode (MaglevGraphBuilder &builder, Node *node)
ValueNode * EnsureTagged (MaglevGraphBuilder &builder, ValueNode *node)
void RemovePredecessorFollowing (ControlNode *control, BasicBlock *call_block)
void RemoveUnreachableBlocks ()
Static Private Member Functions
static void UpdatePredecessorsOf (BasicBlock *block, BasicBlock *prev_pred, BasicBlock *new_pred)
Private Attributes
Graph * graph_
Detailed Description
Definition at line 22 of file maglev-inlining.h.
Constructor & Destructor Documentation
MaglevInliner()
v8::internal::maglev::MaglevInliner::MaglevInliner (Graph * graph) [inline], [explicit]
Definition at line 24 of file maglev-inlining.h.
: graph_(graph) {}
Member Function Documentation
AddNodeAtBlockEnd()
template<class Node , typename... Args>
ValueNode* v8::internal::maglev::MaglevInliner::AddNodeAtBlockEnd (MaglevGraphBuilder & builder, std::initializer_list< ValueNode * > inputs, Args &&... args) [inline], [private]
Definition at line 244 of file maglev-inlining.h.
                                               {
    ValueNode* node =
        NodeBase::New<Node>(zone(), inputs, std::forward<Args>(args)...);
    DCHECK(!node->properties().can_eager_deopt());
    DCHECK(!node->properties().can_lazy_deopt());
    builder.node_buffer().push_back(node);
    RegisterNode(builder, node);
    return node;
  }
References v8::base::args, v8::internal::maglev::OpProperties::can_eager_deopt(), v8::internal::maglev::OpProperties::can_lazy_deopt(), v8::internal::DCHECK(), v8::internal::maglev::MaglevGraphBuilder::node_buffer(), v8::internal::maglev::NodeBase::properties(), and v8::internal::ZoneVector< T >::push_back().
broker()
compiler::JSHeapBroker* v8::internal::maglev::MaglevInliner::broker () const [inline], [private]
Definition at line 62 of file maglev-inlining.h.
{ return graph_->broker(); }
References v8::internal::maglev::Graph::broker(), and graph_.
BuildInlineFunction()
MaybeReduceResult v8::internal::maglev::MaglevInliner::BuildInlineFunction (MaglevCallSiteInfo * call_site) [inline], [private]
Definition at line 85 of file maglev-inlining.h.
                                                                       {
    CallKnownJSFunction* call_node = call_site->generic_call_node;
    BasicBlock* call_block = call_node->owner();
    MaglevCallerDetails* caller_details = &call_site->caller_details;
    DeoptFrame* caller_deopt_frame = caller_details->deopt_frame;
    const MaglevCompilationUnit* caller_unit =
        &caller_deopt_frame->GetCompilationUnit();
    compiler::SharedFunctionInfoRef shared = call_node->shared_function_info();
    if (!call_block || call_block->is_dead()) {
      // The block containing the call is unreachable, and it was previously
      // removed. Do not try to inline the call.
      return ReduceResult::Fail();
    }
    if (v8_flags.trace_maglev_inlining) {
      std::cout << " non-eager inlining " << shared << std::endl;
    }
    // Check if the catch block might become unreachable, ie, the call is the
    // only instance of a throwable node in this block to the same catch block.
    ExceptionHandlerInfo* call_exception_handler_info =
        call_node->exception_handler_info();
    bool catch_block_might_be_unreachable = false;
    if (call_exception_handler_info->HasExceptionHandler() &&
        !call_exception_handler_info->ShouldLazyDeopt()) {
      BasicBlock* catch_block = call_exception_handler_info->catch_block();
      catch_block_might_be_unreachable = true;
      for (ExceptionHandlerInfo* info : call_block->exception_handlers()) {
        if (info != call_exception_handler_info &&
            info->HasExceptionHandler() && !info->ShouldLazyDeopt() &&
            info->catch_block() == catch_block) {
          catch_block_might_be_unreachable = false;
          break;
        }
      }
    }
    // Remove exception handler info from call block.
    ExceptionHandlerInfo::List rem_handlers_in_call_block;
    call_block->exception_handlers().TruncateAt(&rem_handlers_in_call_block,
                                                call_exception_handler_info);
    rem_handlers_in_call_block.DropHead();
    // Truncate the basic block and remove the generic call node.
    ZoneVector<Node*> rem_nodes_in_call_block =
        call_block->Split(call_node, zone());
    // Create a new compilation unit.
    MaglevCompilationUnit* inner_unit = MaglevCompilationUnit::NewInner(
        zone(), caller_unit, shared, call_site->feedback_cell);
    compiler::BytecodeArrayRef bytecode = shared.GetBytecodeArray(broker());
    graph_->add_inlined_bytecode_size(bytecode.length());
    // Create a new graph builder for the inlined function.
    LocalIsolate* local_isolate = broker()->local_isolate_or_isolate();
    MaglevGraphBuilder inner_graph_builder(local_isolate, inner_unit, graph_,
                                           &call_site->caller_details);
    // Update caller deopt frame with inlined arguments.
    caller_details->deopt_frame =
        inner_graph_builder.AddInlinedArgumentsToDeoptFrame(
            caller_deopt_frame, inner_unit, call_node->closure().node(),
            call_site->caller_details.arguments);
    // We truncate the graph to build the function in-place, preserving the
    // invariant that all jumps move forward (except JumpLoop).
    std::vector<BasicBlock*> saved_bb = TruncateGraphAt(call_block);
    ControlNode* control_node = call_block->reset_control_node();
    // Set the inner graph builder to build in the truncated call block.
    inner_graph_builder.set_current_block(call_block);
    ReduceResult result = inner_graph_builder.BuildInlineFunction(
        caller_deopt_frame->GetSourcePosition(), call_node->context().node(),
        call_node->closure().node(), call_node->new_target().node());
    if (result.IsDoneWithAbort()) {
      // Since the rest of the block is dead, these nodes don't belong
      // to any basic block anymore.
      for (auto node : rem_nodes_in_call_block) {
        node->set_owner(nullptr);
      }
      // Restore the rest of the graph.
      for (auto bb : saved_bb) {
        graph_->Add(bb);
      }
      RemovePredecessorFollowing(control_node, call_block);
      // TODO(victorgomes): We probably don't need to iterate all the graph to
      // remove unreachable blocks, but only the successors of control_node in
      // saved_bbs.
      RemoveUnreachableBlocks();
      return result;
    }
    DCHECK(result.IsDoneWithValue());
    ValueNode* returned_value =
        EnsureTagged(inner_graph_builder, result.value());
    // Resume execution using the final block of the inner builder.
    // Add remaining nodes to the final block and use the control flow of the
    // old call block.
    BasicBlock* final_block = inner_graph_builder.FinishInlinedBlockForCaller(
        control_node, rem_nodes_in_call_block);
    DCHECK_NOT_NULL(final_block);
    final_block->exception_handlers().Append(
        std::move(rem_handlers_in_call_block));
    // Update the predecessor of the successors of the {final_block}, that were
    // previously pointing to {call_block}.
    final_block->ForEachSuccessor(
        [call_block, final_block](BasicBlock* successor) {
          UpdatePredecessorsOf(successor, call_block, final_block);
        });
    // Restore the rest of the graph.
    for (auto bb : saved_bb) {
      graph_->Add(bb);
    }
    if (auto alloc = returned_value->TryCast<InlinedAllocation>()) {
      // TODO(victorgomes): Support eliding VOs.
      alloc->ForceEscaping();
#ifdef DEBUG
      alloc->set_is_returned_value_from_inline_call();
#endif // DEBUG
    }
    call_node->OverwriteWithIdentityTo(returned_value);
    // Remove unreachable catch block if no throwable nodes were added during
    // inlining.
    // TODO(victorgomes): Improve this: track if we didnt indeed add a throwable
    // node.
    if (catch_block_might_be_unreachable) {
      RemoveUnreachableBlocks();
    }
    return ReduceResult::Done();
  }
References v8::internal::maglev::Graph::Add(), v8::internal::maglev::Graph::add_inlined_bytecode_size(), v8::internal::maglev::MaglevGraphBuilder::AddInlinedArgumentsToDeoptFrame(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Append(), v8::internal::maglev::MaglevCallerDetails::arguments, broker(), v8::internal::maglev::MaglevGraphBuilder::BuildInlineFunction(), v8::internal::maglev::MaglevCallSiteInfo::caller_details, v8::internal::maglev::ExceptionHandlerInfo::catch_block(), v8::internal::maglev::CallKnownJSFunction::closure(), v8::internal::maglev::CallKnownJSFunction::context(), v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::maglev::MaglevCallerDetails::deopt_frame, v8::internal::maglev::ReduceResult::Done(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::DropHead(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::EnsureTagged(), v8::internal::maglev::BasicBlock::exception_handlers(), v8::internal::maglev::MaybeReduceResult::Fail(), v8::internal::maglev::MaglevCallSiteInfo::feedback_cell, v8::internal::maglev::MaglevGraphBuilder::FinishInlinedBlockForCaller(), v8::internal::maglev::BasicBlock::ForEachSuccessor(), v8::internal::maglev::MaglevCallSiteInfo::generic_call_node, v8::internal::compiler::SharedFunctionInfoRef::GetBytecodeArray(), v8::internal::maglev::DeoptFrame::GetCompilationUnit(), v8::internal::maglev::DeoptFrame::GetSourcePosition(), v8::internal::maglev::ExceptionHandlerInfo::HasExceptionHandler(), v8::internal::maglev::BasicBlock::is_dead(), v8::internal::compiler::BytecodeArrayRef::length(), v8::internal::maglev::CallKnownJSFunction::new_target(), v8::internal::maglev::MaglevCompilationUnit::NewInner(), v8::internal::maglev::Input::node(), v8::internal::maglev::BasicBlock::reset_control_node(), v8::base::internal::result, v8::internal::maglev::MaglevGraphBuilder::set_current_block(), v8::internal::maglev::CallKnownJSFunction::shared_function_info(), v8::internal::maglev::ExceptionHandlerInfo::ShouldLazyDeopt(), v8::internal::maglev::BasicBlock::Split(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::TruncateAt(), v8::internal::maglev::NodeBase::TryCast(), and v8::internal::v8_flags.
Referenced by Run().
ChooseNextCallSite()
MaglevCallSiteInfo* v8::internal::maglev::MaglevInliner::ChooseNextCallSite () [inline], [private]
Definition at line 65 of file maglev-inlining.h.
                                           {
    auto it =
        v8_flags.maglev_inlining_following_eager_order
            ? std::ranges::find_if(graph_->inlineable_calls(),
                                   [](auto* site) { return site != nullptr; })
            : std::ranges::max_element(
                  graph_->inlineable_calls(),
                  [](const MaglevCallSiteInfo* info1,
                     const MaglevCallSiteInfo* info2) {
                    if (info1 == nullptr || info2 == nullptr) {
                      return info2 != nullptr;
                    }
                    return info1->score < info2->score;
                  });
    if (it == graph_->inlineable_calls().end()) return nullptr;
    MaglevCallSiteInfo* call_site = *it;
    *it = nullptr; // Erase call site.
    return call_site;
  }
References graph_, v8::internal::maglev::Graph::inlineable_calls(), v8::internal::maglev::MaglevCallSiteInfo::score, and v8::internal::v8_flags.
Referenced by Run().
EnsureTagged()
ValueNode* v8::internal::maglev::MaglevInliner::EnsureTagged (MaglevGraphBuilder & builder, ValueNode * node) [inline], [private]
Definition at line 262 of file maglev-inlining.h.
                                                                        {
    // TODO(victorgomes): Use KNA to create better conversion nodes?
    switch (node->value_representation()) {
      case ValueRepresentation::kInt32:
        return AddNodeAtBlockEnd<Int32ToNumber>(builder, {node});
      case ValueRepresentation::kUint32:
        return AddNodeAtBlockEnd<Uint32ToNumber>(builder, {node});
      case ValueRepresentation::kFloat64:
        return AddNodeAtBlockEnd<Float64ToTagged>(
            builder, {node}, Float64ToTagged::ConversionMode::kForceHeapNumber);
      case ValueRepresentation::kHoleyFloat64:
        return AddNodeAtBlockEnd<HoleyFloat64ToTagged>(
            builder, {node},
            HoleyFloat64ToTagged::ConversionMode::kForceHeapNumber);
      case ValueRepresentation::kIntPtr:
        return AddNodeAtBlockEnd<IntPtrToNumber>(builder, {node});
      case ValueRepresentation::kTagged:
        return node;
    }
  }
References v8::internal::maglev::kFloat64, v8::internal::maglev::Float64ToTagged::kForceHeapNumber, v8::internal::maglev::HoleyFloat64ToTagged::kForceHeapNumber, v8::internal::maglev::kHoleyFloat64, v8::internal::maglev::kInt32, v8::internal::maglev::kIntPtr, v8::internal::maglev::kTagged, v8::internal::maglev::kUint32, and v8::internal::maglev::ValueNode::value_representation().
RegisterNode()
void v8::internal::maglev::MaglevInliner::RegisterNode (MaglevGraphBuilder & builder, Node * node) [inline], [private]
Definition at line 256 of file maglev-inlining.h.
                                                             {
    if (builder.has_graph_labeller()) {
      builder.graph_labeller()->RegisterNode(node);
    }
  }
References v8::internal::maglev::MaglevGraphBuilder::graph_labeller(), v8::internal::maglev::MaglevGraphBuilder::has_graph_labeller(), and v8::internal::maglev::MaglevGraphLabeller::RegisterNode().
RemovePredecessorFollowing()
void v8::internal::maglev::MaglevInliner::RemovePredecessorFollowing (ControlNode * control, BasicBlock * call_block) [inline], [private]
Definition at line 298 of file maglev-inlining.h.
                                                          {
    BasicBlock::ForEachSuccessorFollowing(control, [&](BasicBlock* succ) {
      if (!succ->has_state()) {
        succ->set_predecessor(nullptr);
        return;
      }
      if (succ->is_loop() && succ->backedge_predecessor() == call_block) {
        succ->state()->TurnLoopIntoRegularBlock();
        return;
      }
      for (int i = succ->predecessor_count() - 1; i >= 0; i--) {
        if (succ->predecessor_at(i) == call_block) {
          succ->state()->RemovePredecessorAt(i);
        }
      }
    });
  }
References v8::internal::maglev::BasicBlock::backedge_predecessor(), v8::internal::anonymous_namespace{json-stringifier.cc}::for(), v8::internal::maglev::BasicBlock::ForEachSuccessorFollowing(), v8::internal::maglev::BasicBlock::has_state(), v8::internal::if(), v8::internal::maglev::BasicBlock::is_loop(), and v8::internal::maglev::BasicBlock::predecessor_count().
RemoveUnreachableBlocks()
void v8::internal::maglev::MaglevInliner::RemoveUnreachableBlocks () [inline], [private]
Definition at line 317 of file maglev-inlining.h.
                                 {
    graph_->set_may_have_unreachable_blocks();
    graph_->RemoveUnreachableBlocks();
  }
Run()
void v8::internal::maglev::MaglevInliner::Run (bool is_tracing_maglev_graphs_enabled) [inline]
Definition at line 26 of file maglev-inlining.h.
                                                  {
    if (graph_->inlineable_calls().empty()) return;
    while (true) {
      if (graph_->total_inlined_bytecode_size() >
          v8_flags.max_maglev_inlined_bytecode_size_cumulative) {
        // No more inlining.
        break;
      }
      MaglevCallSiteInfo* call_site = ChooseNextCallSite();
      if (!call_site) break;
      MaybeReduceResult result = BuildInlineFunction(call_site);
      if (result.IsFail()) continue;
      // If --trace-maglev-inlining-verbose, we print the graph after each
      // inlining step/call.
      if (is_tracing_maglev_graphs_enabled && v8_flags.print_maglev_graphs &&
          v8_flags.trace_maglev_inlining_verbose) {
        std::cout << "\nAfter inlining "
                  << call_site->generic_call_node->shared_function_info()
                  << std::endl;
        PrintGraph(std::cout, graph_);
      }
    }
    // Otherwise we print just once at the end.
    if (is_tracing_maglev_graphs_enabled && v8_flags.print_maglev_graphs &&
        !v8_flags.trace_maglev_inlining_verbose) {
      std::cout << "\nAfter inlining" << std::endl;
      PrintGraph(std::cout, graph_);
    }
  }
References BuildInlineFunction(), ChooseNextCallSite(), v8::internal::maglev::MaglevCallSiteInfo::generic_call_node, graph_, v8::internal::maglev::Graph::inlineable_calls(), v8::internal::maglev::PrintGraph(), v8::base::internal::result, v8::internal::maglev::CallKnownJSFunction::shared_function_info(), v8::internal::maglev::Graph::total_inlined_bytecode_size(), and v8::internal::v8_flags.
Referenced by v8::internal::maglev::MaglevCompiler::Compile(), and v8::internal::compiler::turboshaft::RunMaglevOptimizations().
TruncateGraphAt()
std::vector<BasicBlock*> v8::internal::maglev::MaglevInliner::TruncateGraphAt (BasicBlock * block) [inline], [private]
Definition at line 230 of file maglev-inlining.h.
                                                            {
    // TODO(victorgomes): Consider using a linked list of basic blocks in Maglev
    // instead of a vector.
    auto it =
        std::find(graph_->blocks().begin(), graph_->blocks().end(), block);
    CHECK_NE(it, graph_->blocks().end());
    size_t index = std::distance(graph_->blocks().begin(), it);
    std::vector<BasicBlock*> saved_bb(graph_->blocks().begin() + index + 1,
                                      graph_->blocks().end());
    graph_->blocks().resize(index);
    return saved_bb;
  }
References v8::internal::ZoneVector< T >::begin(), v8::internal::maglev::Graph::blocks(), CHECK_NE, v8::internal::ZoneVector< T >::end(), v8::internal::index, and v8::internal::ZoneVector< T >::resize().
UpdatePredecessorsOf()
static void v8::internal::maglev::MaglevInliner::UpdatePredecessorsOf (BasicBlock * block, BasicBlock * prev_pred, BasicBlock * new_pred) [inline], [static], [private]
Definition at line 283 of file maglev-inlining.h.
                                                         {
    if (!block->has_state()) {
      DCHECK_EQ(block->predecessor(), prev_pred);
      block->set_predecessor(new_pred);
      return;
    }
    for (int i = 0; i < block->predecessor_count(); i++) {
      if (block->predecessor_at(i) == prev_pred) {
        block->state()->set_predecessor_at(i, new_pred);
        break;
      }
    }
  }
References DCHECK_EQ, v8::internal::maglev::BasicBlock::has_state(), v8::internal::maglev::BasicBlock::predecessor(), v8::internal::maglev::BasicBlock::predecessor_at(), v8::internal::maglev::BasicBlock::predecessor_count(), v8::internal::maglev::BasicBlock::set_predecessor(), v8::internal::maglev::MergePointInterpreterFrameState::set_predecessor_at(), and v8::internal::maglev::BasicBlock::state().
zone()
Zone* v8::internal::maglev::MaglevInliner::zone () const [inline], [private]
Definition at line 63 of file maglev-inlining.h.
{ return graph_->zone(); }
References graph_, and v8::internal::maglev::Graph::zone().
Member Data Documentation
graph_
Graph* v8::internal::maglev::MaglevInliner::graph_ [private]
Definition at line 60 of file maglev-inlining.h.
Referenced by broker(), ChooseNextCallSite(), Run(), and zone().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-inlining.h