v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits > Class Template Reference
Public Types
using BackingStore = typename KindTraits::BackingStore
Static Public Member Functions
static DirectHandle< NumberDictionary > NormalizeImpl (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > store)
static void DeleteAtEnd (Isolate *isolate, DirectHandle< JSObject > obj, DirectHandle< BackingStore > backing_store, uint32_t entry)
static void DeleteCommon (Isolate *isolate, DirectHandle< JSObject > obj, uint32_t entry, DirectHandle< FixedArrayBase > store)
static void ReconfigureImpl (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > store, InternalIndex entry, DirectHandle< Object > value, PropertyAttributes attributes)
static Maybe< bool > AddImpl (Isolate *isolate, DirectHandle< JSObject > object, uint32_t index, DirectHandle< Object > value, PropertyAttributes attributes, uint32_t new_capacity)
static void DeleteImpl (Isolate *isolate, DirectHandle< JSObject > obj, InternalIndex entry)
static bool HasEntryImpl (Isolate *isolate, Tagged< FixedArrayBase > backing_store, InternalIndex entry)
static uint32_t NumberOfElementsImpl (Isolate *isolate, Tagged< JSObject > receiver, Tagged< FixedArrayBase > backing_store)
static V8_WARN_UNUSED_RESULT ExceptionStatus AddElementsToKeyAccumulatorImpl (DirectHandle< JSObject > receiver, KeyAccumulator *accumulator, AddKeyConversion convert)
static void ValidateContents (Isolate *isolate, Tagged< JSObject > holder, size_t length)
static Tagged< Object > PopImpl (Isolate *isolate, DirectHandle< JSArray > receiver)
static Tagged< Object > ShiftImpl (Isolate *isolate, DirectHandle< JSArray > receiver)
static Maybe< uint32_t > PushImpl (Isolate *isolate, DirectHandle< JSArray > receiver, BuiltinArguments *args, uint32_t push_size)
static Maybe< uint32_t > UnshiftImpl (Isolate *isolate, DirectHandle< JSArray > receiver, BuiltinArguments *args, uint32_t unshift_size)
static MaybeDirectHandle< Object > FillImpl (Isolate *isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > obj_value, size_t start, size_t end)
static Maybe< bool > IncludesValueImpl (Isolate *isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > search_value, size_t start_from, size_t length)
static Handle< FixedArray > CreateListFromArrayLikeImpl (Isolate *isolate, DirectHandle< JSObject > object, uint32_t length)
static Tagged< Object > RemoveElement (Isolate *isolate, DirectHandle< JSArray > receiver, Where remove_position)
static Maybe< uint32_t > AddArguments (Isolate *isolate, DirectHandle< JSArray > receiver, DirectHandle< FixedArrayBase > backing_store, BuiltinArguments *args, uint32_t add_size, Where add_position)
static void CopyArguments (BuiltinArguments *args, DirectHandle< FixedArrayBase > dst_store, uint32_t copy_size, uint32_t src_index, uint32_t dst_index)
Additional Inherited Members
Detailed Description
template<typename Subclass, typename KindTraits>
class v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >
Definition at line 2097 of file elements.cc.
Member Typedef Documentation
BackingStore
template<typename Subclass , typename KindTraits >
using v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::BackingStore = typename KindTraits::BackingStore
Definition at line 2099 of file elements.cc.
Member Function Documentation
AddArguments()
template<typename Subclass , typename KindTraits >
static Maybe<uint32_t> v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::AddArguments (Isolate * isolate, DirectHandle< JSArray > receiver, DirectHandle< FixedArrayBase > backing_store, BuiltinArguments * args, uint32_t add_size, Where add_position) [inline], [static]
Definition at line 2645 of file elements.cc.
                                             {
    uint32_t length = Smi::ToInt(receiver->length());
    DCHECK_LT(0, add_size);
    uint32_t elms_len = backing_store->length();
    // Check we do not overflow the new_length.
    DCHECK(add_size <= static_cast<uint32_t>(Smi::kMaxValue - length));
    uint32_t new_length = length + add_size;
    if (new_length > elms_len) {
      // New backing storage is needed.
      uint32_t capacity = JSObject::NewElementsCapacity(new_length);
      // If we add arguments to the start we have to shift the existing objects.
      int copy_dst_index = add_position == AT_START ? add_size : 0;
      // Copy over all objects to a new backing_store.
      ASSIGN_RETURN_ON_EXCEPTION_VALUE(
          isolate, backing_store,
          Subclass::ConvertElementsWithCapacity(isolate, receiver,
                                                backing_store, KindTraits::Kind,
                                                capacity, 0, copy_dst_index),
          Nothing<uint32_t>());
      receiver->set_elements(*backing_store);
    } else if (add_position == AT_START) {
      // If the backing store has enough capacity and we add elements to the
      // start we have to shift the existing objects.
      WriteBarrierMode mode = IsFastNumberElementsKind(KindTraits::Kind)
                                  ? SKIP_WRITE_BARRIER
                                  : UPDATE_WRITE_BARRIER;
      Cast<BackingStore>(backing_store)
          ->MoveElements(isolate, add_size, 0, length, mode);
    }
    int insertion_index = add_position == AT_START ? 0 : length;
    // Copy the arguments to the start.
    Subclass::CopyArguments(args, backing_store, add_size, 1, insertion_index);
    // Set the length.
    receiver->set_length(Smi::FromInt(new_length));
    return Just(new_length);
  }
References v8::base::args, ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::anonymous_namespace{elements.cc}::AT_START, v8::internal::DCHECK(), DCHECK_LT, v8::internal::Smi::FromInt(), v8::internal::IsFastNumberElementsKind(), v8::Just(), v8::internal::Smi::kMaxValue, v8::internal::length, mode(), v8::internal::JSObject::NewElementsCapacity(), v8::internal::SKIP_WRITE_BARRIER, v8::internal::Smi::ToInt(), and v8::internal::UPDATE_WRITE_BARRIER.
AddElementsToKeyAccumulatorImpl()
template<typename Subclass , typename KindTraits >
static V8_WARN_UNUSED_RESULT ExceptionStatus v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::AddElementsToKeyAccumulatorImpl (DirectHandle< JSObject > receiver, KeyAccumulator * accumulator, AddKeyConversion convert) [inline], [static]
Definition at line 2310 of file elements.cc.
                                {
    Isolate* isolate = accumulator->isolate();
    DirectHandle<FixedArrayBase> elements(receiver->elements(), isolate);
    size_t length =
        Subclass::GetMaxNumberOfEntries(isolate, *receiver, *elements);
    for (size_t i = 0; i < length; i++) {
      if (IsFastPackedElementsKind(KindTraits::Kind) ||
          HasEntryImpl(isolate, *elements, InternalIndex(i))) {
        RETURN_FAILURE_IF_NOT_SUCCESSFUL(accumulator->AddKey(
            Subclass::GetImpl(isolate, *elements, InternalIndex(i)), convert));
      }
    }
    return ExceptionStatus::kSuccess;
  }
References v8::internal::KeyAccumulator::AddKey(), v8::internal::IsFastPackedElementsKind(), v8::internal::KeyAccumulator::isolate(), v8::internal::kSuccess, v8::internal::length, and RETURN_FAILURE_IF_NOT_SUCCESSFUL.
AddImpl()
template<typename Subclass , typename KindTraits >
static Maybe<bool> v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::AddImpl (Isolate * isolate, DirectHandle< JSObject > object, uint32_t index, DirectHandle< Object > value, PropertyAttributes attributes, uint32_t new_capacity) [inline], [static]
Definition at line 2243 of file elements.cc.
                                                    {
    DCHECK_EQ(NONE, attributes);
    ElementsKind from_kind = object->GetElementsKind();
    ElementsKind to_kind = Subclass::kind();
    if (IsDictionaryElementsKind(from_kind) ||
        IsDoubleElementsKind(from_kind) != IsDoubleElementsKind(to_kind) ||
        Subclass::GetCapacityImpl(*object, object->elements()) !=
            new_capacity) {
      MAYBE_RETURN(
          Subclass::GrowCapacityAndConvertImpl(isolate, object, new_capacity),
          Nothing<bool>());
    } else {
      if (IsFastElementsKind(from_kind) && from_kind != to_kind) {
        JSObject::TransitionElementsKind(isolate, object, to_kind);
      }
      if (IsSmiOrObjectElementsKind(from_kind)) {
        DCHECK(IsSmiOrObjectElementsKind(to_kind));
        JSObject::EnsureWritableFastElements(isolate, object);
      }
    }
    Subclass::SetImpl(object, InternalIndex(index), *value);
    return Just(true);
  }
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::JSObject::EnsureWritableFastElements(), v8::internal::index, v8::internal::IsDictionaryElementsKind(), v8::internal::IsDoubleElementsKind(), v8::internal::IsFastElementsKind(), v8::internal::IsSmiOrObjectElementsKind(), v8::Just(), MAYBE_RETURN, v8::internal::NONE, v8::internal::JSObject::TransitionElementsKind(), and v8::internal::value.
CopyArguments()
template<typename Subclass , typename KindTraits >
static void v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::CopyArguments (BuiltinArguments * args, DirectHandle< FixedArrayBase > dst_store, uint32_t copy_size, uint32_t src_index, uint32_t dst_index) [inline], [static]
Definition at line 2687 of file elements.cc.
                                                {
    // Add the provided values.
    DisallowGarbageCollection no_gc;
    Tagged<FixedArrayBase> raw_backing_store = *dst_store;
    WriteBarrierMode mode = raw_backing_store->GetWriteBarrierMode(no_gc);
    for (uint32_t i = 0; i < copy_size; i++) {
      Tagged<Object> argument = (*args)[src_index + i];
      DCHECK(!IsTheHole(argument));
      Subclass::SetImpl(raw_backing_store, InternalIndex(dst_index + i),
                        argument, mode);
    }
  }
References v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, mode(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
CreateListFromArrayLikeImpl()
template<typename Subclass , typename KindTraits >
static Handle<FixedArray> v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::CreateListFromArrayLikeImpl (Isolate * isolate, DirectHandle< JSObject > object, uint32_t length) [inline], [static]
Definition at line 2570 of file elements.cc.
                                                                        {
    Handle<FixedArray> result = isolate->factory()->NewFixedArray(length);
    DirectHandle<FixedArrayBase> elements(object->elements(), isolate);
    for (uint32_t i = 0; i < length; i++) {
      InternalIndex entry(i);
      if (!Subclass::HasEntryImpl(isolate, *elements, entry)) continue;
      DirectHandle<Object> value;
      value = Subclass::GetImpl(isolate, *elements, entry);
      if (IsName(*value)) {
        value = isolate->factory()->InternalizeName(Cast<Name>(value));
      }
      result->set(i, *value);
    }
    return result;
  }
References v8::internal::Isolate::factory(), v8::internal::length, v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::base::internal::result, and v8::internal::value.
DeleteAtEnd()
template<typename Subclass , typename KindTraits >
static void v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::DeleteAtEnd (Isolate * isolate, DirectHandle< JSObject > obj, DirectHandle< BackingStore > backing_store, uint32_t entry) [inline], [static]
Definition at line 2139 of file elements.cc.
                                          {
    uint32_t length = static_cast<uint32_t>(backing_store->length());
    DCHECK_LT(entry, length);
    for (; entry > 0; entry--) {
      if (!backing_store->is_the_hole(isolate, entry - 1)) break;
    }
    if (entry == 0) {
      Tagged<FixedArray> empty = ReadOnlyRoots(isolate).empty_fixed_array();
      // Dynamically ask for the elements kind here since we manually redirect
      // the operations for argument backing stores.
      if (obj->GetElementsKind() == FAST_SLOPPY_ARGUMENTS_ELEMENTS) {
        Cast<SloppyArgumentsElements>(obj->elements())->set_arguments(empty);
      } else {
        obj->set_elements(empty);
      }
      return;
    }
    isolate->heap()->RightTrimArray(*backing_store, entry, length);
  }
References DCHECK_LT, v8::internal::FAST_SLOPPY_ARGUMENTS_ELEMENTS, v8::internal::Isolate::heap(), v8::internal::length, and v8::internal::Heap::RightTrimArray().
DeleteCommon()
template<typename Subclass , typename KindTraits >
static void v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::DeleteCommon (Isolate * isolate, DirectHandle< JSObject > obj, uint32_t entry, DirectHandle< FixedArrayBase > store) [inline], [static]
Definition at line 2162 of file elements.cc.
                                                                               {
    DCHECK(obj->HasSmiOrObjectElements() || obj->HasDoubleElements() ||
           obj->HasNonextensibleElements() || obj->HasFastArgumentsElements() ||
           obj->HasFastStringWrapperElements());
    DirectHandle<BackingStore> backing_store = Cast<BackingStore>(store);
    if (!IsJSArray(*obj) &&
        entry == static_cast<uint32_t>(store->length()) - 1) {
      DeleteAtEnd(isolate, obj, backing_store, entry);
      return;
    }
    backing_store->set_the_hole(isolate, entry);
    // TODO(verwaest): Move this out of elements.cc.
    // If the backing store is larger than a certain size and
    // has too few used values, normalize it.
    const int kMinLengthForSparsenessCheck = 64;
    if (backing_store->length() < kMinLengthForSparsenessCheck) return;
    uint32_t length = 0;
    if (IsJSArray(*obj)) {
      Object::ToArrayLength(Cast<JSArray>(*obj)->length(), &length);
    } else {
      length = static_cast<uint32_t>(store->length());
    }
    // To avoid doing the check on every delete, use a counter-based heuristic.
    const int kLengthFraction = 16;
    // The above constant must be large enough to ensure that we check for
    // normalization frequently enough. At a minimum, it should be large
    // enough to reliably hit the "window" of remaining elements count where
    // normalization would be beneficial.
    static_assert(kLengthFraction >=
                  NumberDictionary::kEntrySize *
                      NumberDictionary::kPreferFastElementsSizeFactor);
    size_t current_counter = isolate->elements_deletion_counter();
    if (current_counter < length / kLengthFraction) {
      isolate->set_elements_deletion_counter(current_counter + 1);
      return;
    }
    // Reset the counter whenever the full check is performed.
    isolate->set_elements_deletion_counter(0);
    if (!IsJSArray(*obj)) {
      uint32_t i;
      for (i = entry + 1; i < length; i++) {
        if (!backing_store->is_the_hole(isolate, i)) break;
      }
      if (i == length) {
        DeleteAtEnd(isolate, obj, backing_store, entry);
        return;
      }
    }
    int num_used = 0;
    for (int i = 0; i < backing_store->length(); ++i) {
      if (!backing_store->is_the_hole(isolate, i)) {
        ++num_used;
        // Bail out if a number dictionary wouldn't be able to save much space.
        if (NumberDictionary::kPreferFastElementsSizeFactor *
                NumberDictionary::ComputeCapacity(num_used) *
                NumberDictionary::kEntrySize >
            static_cast<uint32_t>(backing_store->length())) {
          return;
        }
      }
    }
    JSObject::NormalizeElements(isolate, obj);
  }
References v8::internal::DCHECK(), v8::internal::Isolate::elements_deletion_counter(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, cppgc::internal::anonymous_namespace{gc-info-table.cc}::kEntrySize, v8::internal::NumberDictionary::kPreferFastElementsSizeFactor, v8::internal::length, v8::internal::JSObject::NormalizeElements(), v8::internal::Isolate::set_elements_deletion_counter(), store(), and v8::internal::Object::ToArrayLength().
DeleteImpl()
template<typename Subclass , typename KindTraits >
static void v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::DeleteImpl (Isolate * isolate, DirectHandle< JSObject > obj, InternalIndex entry) [inline], [static]
Definition at line 2270 of file elements.cc.
                                              {
    ElementsKind kind = KindTraits::Kind;
    if (IsFastPackedElementsKind(kind) ||
        kind == PACKED_NONEXTENSIBLE_ELEMENTS) {
      JSObject::TransitionElementsKind(isolate, obj,
                                       GetHoleyElementsKind(kind));
    }
    if (IsSmiOrObjectElementsKind(KindTraits::Kind) ||
        IsNonextensibleElementsKind(kind)) {
      JSObject::EnsureWritableFastElements(isolate, obj);
    }
    DeleteCommon(isolate, obj, entry.as_uint32(),
                 direct_handle(obj->elements(), isolate));
  }
References v8::internal::InternalIndex::as_uint32(), v8::internal::direct_handle(), v8::internal::JSObject::EnsureWritableFastElements(), v8::internal::GetHoleyElementsKind(), v8::internal::IsFastPackedElementsKind(), v8::internal::IsNonextensibleElementsKind(), v8::internal::IsSmiOrObjectElementsKind(), v8::internal::PACKED_NONEXTENSIBLE_ELEMENTS, and v8::internal::JSObject::TransitionElementsKind().
FillImpl()
template<typename Subclass , typename KindTraits >
static MaybeDirectHandle<Object> v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::FillImpl (Isolate * isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > obj_value, size_t start, size_t end) [inline], [static]
Definition at line 2400 of file elements.cc.
                                                                      {
    // Ensure indexes are within array bounds
    DCHECK_LE(0, start);
    DCHECK_LE(start, end);
    // Make sure COW arrays are copied.
    if (IsSmiOrObjectElementsKind(Subclass::kind())) {
      JSObject::EnsureWritableFastElements(isolate, receiver);
    }
    // Make sure we have enough space.
    DCHECK_LE(end, std::numeric_limits<uint32_t>::max());
    if (end > Subclass::GetCapacityImpl(*receiver, receiver->elements())) {
      MAYBE_RETURN_NULL(Subclass::GrowCapacityAndConvertImpl(
          isolate, receiver, static_cast<uint32_t>(end)));
      CHECK_EQ(Subclass::kind(), receiver->GetElementsKind());
    }
    DCHECK_LE(end, Subclass::GetCapacityImpl(*receiver, receiver->elements()));
    for (size_t index = start; index < end; ++index) {
      Subclass::SetImpl(receiver, InternalIndex(index), *obj_value);
    }
    return MaybeDirectHandle<Object>(receiver);
  }
References CHECK_EQ, DCHECK_LE, v8::internal::compiler::end(), v8::internal::JSObject::EnsureWritableFastElements(), v8::internal::index, v8::internal::IsSmiOrObjectElementsKind(), and MAYBE_RETURN_NULL.
HasEntryImpl()
template<typename Subclass , typename KindTraits >
static bool v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::HasEntryImpl (Isolate * isolate, Tagged< FixedArrayBase > backing_store, InternalIndex entry) [inline], [static]
Definition at line 2286 of file elements.cc.
                                                {
    return !Cast<BackingStore>(backing_store)
                ->is_the_hole(isolate, entry.as_int());
  }
References v8::internal::InternalIndex::as_int().
IncludesValueImpl()
template<typename Subclass , typename KindTraits >
static Maybe<bool> v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::IncludesValueImpl (Isolate * isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > search_value, size_t start_from, size_t length) [inline], [static]
Definition at line 2428 of file elements.cc.
                                                                         {
    DCHECK(JSObject::PrototypeHasNoElements(isolate, *receiver));
    DisallowGarbageCollection no_gc;
    Tagged<FixedArrayBase> elements_base = receiver->elements();
    Tagged<Object> the_hole = ReadOnlyRoots(isolate).the_hole_value();
    Tagged<Object> undefined = ReadOnlyRoots(isolate).undefined_value();
    Tagged<Object> value = *search_value;
    if (start_from >= length) return Just(false);
    // Elements beyond the capacity of the backing store treated as undefined.
    size_t elements_length = static_cast<size_t>(elements_base->length());
    if (value == undefined && elements_length < length) return Just(true);
    if (elements_length == 0) {
      DCHECK_NE(value, undefined);
      return Just(false);
    }
    length = std::min(elements_length, length);
    DCHECK_LE(length, std::numeric_limits<int>::max());
    if (!IsNumber(value)) {
      if (value == undefined) {
        // Search for `undefined` or The Hole. Even in the case of
        // PACKED_DOUBLE_ELEMENTS or PACKED_SMI_ELEMENTS, we might encounter The
        // Hole here, since the {length} used here can be larger than
        // JSArray::length.
        if (IsSmiOrObjectElementsKind(Subclass::kind()) ||
            IsAnyNonextensibleElementsKind(Subclass::kind())) {
          Tagged<FixedArray> elements = Cast<FixedArray>(receiver->elements());
          for (size_t k = start_from; k < length; ++k) {
            Tagged<Object> element_k = elements->get(static_cast<int>(k));
            if (element_k == the_hole || element_k == undefined) {
              return Just(true);
            }
          }
          return Just(false);
        } else {
          // Search for The Hole in HOLEY_DOUBLE_ELEMENTS or
          // PACKED_DOUBLE_ELEMENTS.
          DCHECK(IsDoubleElementsKind(Subclass::kind()));
          Tagged<FixedDoubleArray> elements =
              Cast<FixedDoubleArray>(receiver->elements());
          for (size_t k = start_from; k < length; ++k) {
            if (elements->is_the_hole(static_cast<int>(k))) return Just(true);
          }
          return Just(false);
        }
      } else if (!IsObjectElementsKind(Subclass::kind()) &&
                 !IsAnyNonextensibleElementsKind(Subclass::kind())) {
        // Search for non-number, non-Undefined value, with either
        // PACKED_SMI_ELEMENTS, PACKED_DOUBLE_ELEMENTS, HOLEY_SMI_ELEMENTS or
        // HOLEY_DOUBLE_ELEMENTS. Guaranteed to return false, since these
        // elements kinds can only contain Number values or undefined.
        return Just(false);
      } else {
        // Search for non-number, non-Undefined value with either
        // PACKED_ELEMENTS or HOLEY_ELEMENTS.
        DCHECK(IsObjectElementsKind(Subclass::kind()) ||
               IsAnyNonextensibleElementsKind(Subclass::kind()));
        Tagged<FixedArray> elements = Cast<FixedArray>(receiver->elements());
        for (size_t k = start_from; k < length; ++k) {
          Tagged<Object> element_k = elements->get(static_cast<int>(k));
          if (element_k == the_hole) continue;
          if (Object::SameValueZero(value, element_k)) return Just(true);
        }
        return Just(false);
      }
    } else {
      if (!IsNaN(value)) {
        double search_number = Object::NumberValue(value);
        if (IsDoubleElementsKind(Subclass::kind())) {
          // Search for non-NaN Number in PACKED_DOUBLE_ELEMENTS or
          // HOLEY_DOUBLE_ELEMENTS --- Skip TheHole, and trust UCOMISD or
          // similar operation for result.
          Tagged<FixedDoubleArray> elements =
              Cast<FixedDoubleArray>(receiver->elements());
          for (size_t k = start_from; k < length; ++k) {
            if (elements->is_the_hole(static_cast<int>(k))) continue;
            if (elements->get_scalar(static_cast<int>(k)) == search_number) {
              return Just(true);
            }
          }
          return Just(false);
        } else {
          // Search for non-NaN Number in PACKED_ELEMENTS, HOLEY_ELEMENTS,
          // PACKED_SMI_ELEMENTS or HOLEY_SMI_ELEMENTS --- Skip non-Numbers,
          // and trust UCOMISD or similar operation for result
          Tagged<FixedArray> elements = Cast<FixedArray>(receiver->elements());
          for (size_t k = start_from; k < length; ++k) {
            Tagged<Object> element_k = elements->get(static_cast<int>(k));
            if (IsNumber(element_k) &&
                Object::NumberValue(element_k) == search_number) {
              return Just(true);
            }
          }
          return Just(false);
        }
      } else {
        // Search for NaN --- NaN cannot be represented with Smi elements, so
        // abort if ElementsKind is PACKED_SMI_ELEMENTS or HOLEY_SMI_ELEMENTS
        if (IsSmiElementsKind(Subclass::kind())) return Just(false);
        if (IsDoubleElementsKind(Subclass::kind())) {
          // Search for NaN in PACKED_DOUBLE_ELEMENTS or
          // HOLEY_DOUBLE_ELEMENTS --- Skip The Hole and trust
          // std::isnan(elementK) for result
          Tagged<FixedDoubleArray> elements =
              Cast<FixedDoubleArray>(receiver->elements());
          for (size_t k = start_from; k < length; ++k) {
            if (elements->is_the_hole(static_cast<int>(k))) continue;
            if (std::isnan(elements->get_scalar(static_cast<int>(k)))) {
              return Just(true);
            }
          }
          return Just(false);
        } else {
          // Search for NaN in PACKED_ELEMENTS or HOLEY_ELEMENTS. Return true
          // if elementK->IsHeapNumber() && std::isnan(elementK->Number())
          DCHECK(IsObjectElementsKind(Subclass::kind()) ||
                 IsAnyNonextensibleElementsKind(Subclass::kind()));
          Tagged<FixedArray> elements = Cast<FixedArray>(receiver->elements());
          for (size_t k = start_from; k < length; ++k) {
            if (IsNaN(elements->get(static_cast<int>(k)))) return Just(true);
          }
          return Just(false);
        }
      }
    }
  }
References v8::internal::DCHECK(), DCHECK_LE, DCHECK_NE, v8::internal::IsAnyNonextensibleElementsKind(), v8::internal::IsDoubleElementsKind(), v8::internal::IsNaN(), v8::internal::IsNumber(), v8::internal::IsObjectElementsKind(), v8::internal::IsSmiElementsKind(), v8::internal::IsSmiOrObjectElementsKind(), v8::Just(), v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Object::NumberValue(), v8::internal::JSObject::PrototypeHasNoElements(), v8::internal::Object::SameValueZero(), v8::internal::undefined, and v8::internal::value.
NormalizeImpl()
template<typename Subclass , typename KindTraits >
static DirectHandle<NumberDictionary> v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::NormalizeImpl (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > store) [inline], [static]
Definition at line 2101 of file elements.cc.
                                          {
    ElementsKind kind = Subclass::kind();
    // Ensure that notifications fire if the array or object prototypes are
    // normalizing.
    if (IsSmiOrObjectElementsKind(kind) ||
        kind == FAST_STRING_WRAPPER_ELEMENTS) {
      isolate->UpdateNoElementsProtectorOnNormalizeElements(object);
    }
    int capacity = object->GetFastElementsUsage();
    DirectHandle<NumberDictionary> dictionary =
        NumberDictionary::New(isolate, capacity);
    PropertyDetails details = PropertyDetails::Empty();
    int j = 0;
    int max_number_key = -1;
    for (int i = 0; j < capacity; i++) {
      if (IsHoleyElementsKindForRead(kind)) {
        if (Cast<BackingStore>(*store)->is_the_hole(isolate, i)) continue;
      }
      max_number_key = i;
      DirectHandle<Object> value =
          Subclass::GetImpl(isolate, *store, InternalIndex(i));
      dictionary =
          NumberDictionary::Add(isolate, dictionary, i, value, details);
      j++;
    }
    if (max_number_key > 0) {
      dictionary->UpdateMaxNumberKey(static_cast<uint32_t>(max_number_key),
                                     object);
    }
    return dictionary;
  }
References v8::bigint::Add(), v8::internal::PropertyDetails::Empty(), v8::internal::FAST_STRING_WRAPPER_ELEMENTS, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::IsHoleyElementsKindForRead(), v8::internal::IsSmiOrObjectElementsKind(), v8::internal::anonymous_namespace{intl-objects.cc}::New(), store(), v8::internal::Isolate::UpdateNoElementsProtectorOnNormalizeElements(), and v8::internal::value.
NumberOfElementsImpl()
template<typename Subclass , typename KindTraits >
static uint32_t v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::NumberOfElementsImpl (Isolate * isolate, Tagged< JSObject > receiver, Tagged< FixedArrayBase > backing_store) [inline], [static]
Definition at line 2293 of file elements.cc.
                                                                             {
    size_t max_index = Subclass::GetMaxIndex(receiver, backing_store);
    DCHECK_LE(max_index, std::numeric_limits<uint32_t>::max());
    if (IsFastPackedElementsKind(Subclass::kind())) {
      return static_cast<uint32_t>(max_index);
    }
    uint32_t count = 0;
    for (size_t i = 0; i < max_index; i++) {
      if (Subclass::HasEntryImpl(isolate, backing_store, InternalIndex(i))) {
        count++;
      }
    }
    return count;
  }
References DCHECK_LE, and v8::internal::IsFastPackedElementsKind().
PopImpl()
template<typename Subclass , typename KindTraits >
static Tagged<Object> v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::PopImpl (Isolate * isolate, DirectHandle< JSArray > receiver) [inline], [static]
Definition at line 2373 of file elements.cc.
                                                                {
    return Subclass::RemoveElement(isolate, receiver, AT_END);
  }
References v8::internal::anonymous_namespace{elements.cc}::AT_END.
PushImpl()
template<typename Subclass , typename KindTraits >
static Maybe<uint32_t> v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::PushImpl (Isolate * isolate, DirectHandle< JSArray > receiver, BuiltinArguments * args, uint32_t push_size) [inline], [static]
Definition at line 2383 of file elements.cc.
                                                                              {
    DirectHandle<FixedArrayBase> backing_store(receiver->elements(), isolate);
    return Subclass::AddArguments(isolate, receiver, backing_store, args,
                                  push_size, AT_END);
  }
References v8::base::args, and v8::internal::anonymous_namespace{elements.cc}::AT_END.
ReconfigureImpl()
template<typename Subclass , typename KindTraits >
static void v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::ReconfigureImpl (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > store, InternalIndex entry, DirectHandle< Object > value, PropertyAttributes attributes) [inline], [static]
Definition at line 2231 of file elements.cc.
                                                             {
    DirectHandle<NumberDictionary> dictionary =
        JSObject::NormalizeElements(isolate, object);
    entry = InternalIndex(dictionary->FindEntry(isolate, entry.as_uint32()));
    DictionaryElementsAccessor::ReconfigureImpl(
        isolate, object, Cast<FixedArrayBase>(dictionary), entry, value,
        attributes);
  }
References v8::internal::InternalIndex::as_uint32(), v8::internal::JSObject::NormalizeElements(), and v8::internal::value.
RemoveElement()
template<typename Subclass , typename KindTraits >
static Tagged<Object> v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::RemoveElement (Isolate * isolate, DirectHandle< JSArray > receiver, Where remove_position) [inline], [static]
Definition at line 2587 of file elements.cc.
                                                                       {
    constexpr ElementsKind kind = KindTraits::Kind;
    static_assert(IsFastElementsKind(kind));
    uint32_t length = static_cast<uint32_t>(Smi::ToInt(receiver->length()));
    if (length == 0) return ReadOnlyRoots(isolate).undefined_value();
    if constexpr (IsSmiOrObjectElementsKind(kind)) {
      JSObject::EnsureWritableFastElements(isolate, receiver);
    }
    DCHECK_GT(length, 0);
    int new_length = length - 1;
    int remove_index = remove_position == AT_START ? 0 : new_length;
    Tagged<Object> result;
    Tagged<JSArray> raw_receiver = *receiver;
    if constexpr (IsDoubleElementsKind(kind)) {
      result = *Subclass::GetImpl(isolate, raw_receiver->elements(),
                                  InternalIndex(remove_index));
      raw_receiver = *receiver;
    } else {
      result = Cast<BackingStore>(raw_receiver->elements())->get(remove_index);
    }
    // The result is now unhandlified, so we can't allocate anymore.
    DisallowGarbageCollection no_gc;
    if (V8_UNLIKELY(new_length == 0)) {
      raw_receiver->initialize_elements();
    } else {
      Tagged<BackingStore> dst_elms =
          Cast<BackingStore>(raw_receiver->elements());
      if (remove_position == AT_START) {
        if (V8_UNLIKELY(new_length > JSArray::kMaxCopyElements &&
                        isolate->heap()->CanMoveObjectStart(dst_elms))) {
          dst_elms = Cast<BackingStore>(
              isolate->heap()->LeftTrimFixedArray(dst_elms, 1));
          raw_receiver->set_elements(dst_elms);
        } else {
          WriteBarrierMode mode = IsFastNumberElementsKind(KindTraits::Kind)
                                      ? SKIP_WRITE_BARRIER
                                      : UPDATE_WRITE_BARRIER;
          dst_elms->MoveElements(isolate, 0, 1, new_length, mode);
          dst_elms->FillWithHoles(new_length, new_length + 1);
          Subclass::DecreaseLength(isolate, dst_elms, length, new_length);
        }
      } else {
        dst_elms->FillWithHoles(new_length, new_length + 1);
        Subclass::DecreaseLength(isolate, dst_elms, length, new_length);
      }
    }
    raw_receiver->set_length(Smi::FromInt(new_length));
    if (IsHoleyElementsKind(kind) && IsTheHole(result, isolate)) {
      return ReadOnlyRoots(isolate).undefined_value();
    }
    return result;
  }
References v8::internal::anonymous_namespace{elements.cc}::AT_START, v8::internal::Heap::CanMoveObjectStart(), DCHECK_GT, v8::internal::JSObject::EnsureWritableFastElements(), v8::internal::Smi::FromInt(), v8::internal::Isolate::heap(), v8::internal::IsDoubleElementsKind(), v8::internal::IsFastElementsKind(), v8::internal::IsFastNumberElementsKind(), v8::internal::IsHoleyElementsKind(), v8::internal::IsSmiOrObjectElementsKind(), v8::internal::JSArray::kMaxCopyElements, v8::internal::Heap::LeftTrimFixedArray(), v8::internal::length, mode(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, v8::internal::SKIP_WRITE_BARRIER, v8::internal::Smi::ToInt(), v8::internal::UPDATE_WRITE_BARRIER, and V8_UNLIKELY.
ShiftImpl()
template<typename Subclass , typename KindTraits >
static Tagged<Object> v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::ShiftImpl (Isolate * isolate, DirectHandle< JSArray > receiver) [inline], [static]
Definition at line 2378 of file elements.cc.
                                                                  {
    return Subclass::RemoveElement(isolate, receiver, AT_START);
  }
References v8::internal::anonymous_namespace{elements.cc}::AT_START.
UnshiftImpl()
template<typename Subclass , typename KindTraits >
static Maybe<uint32_t> v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::UnshiftImpl (Isolate * isolate, DirectHandle< JSArray > receiver, BuiltinArguments * args, uint32_t unshift_size) [inline], [static]
Definition at line 2391 of file elements.cc.
                                                            {
    DirectHandle<FixedArrayBase> backing_store(receiver->elements(), isolate);
    return Subclass::AddArguments(isolate, receiver, backing_store, args,
                                  unshift_size, AT_START);
  }
References v8::base::args, and v8::internal::anonymous_namespace{elements.cc}::AT_START.
ValidateContents()
template<typename Subclass , typename KindTraits >
static void v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::ValidateContents (Isolate * isolate, Tagged< JSObject > holder, size_t length) [inline], [static]
Definition at line 2327 of file elements.cc.
                                              {
#if DEBUG
    Heap* heap = isolate->heap();
    Tagged<FixedArrayBase> elements = holder->elements();
    Tagged<Map> map = elements->map();
    if (IsSmiOrObjectElementsKind(KindTraits::Kind)) {
      DCHECK_NE(map, ReadOnlyRoots(heap).fixed_double_array_map());
    } else if (IsDoubleElementsKind(KindTraits::Kind)) {
      DCHECK_NE(map, ReadOnlyRoots(heap).fixed_cow_array_map());
      if (map == ReadOnlyRoots(heap).fixed_array_map()) DCHECK_EQ(0u, length);
    } else {
      UNREACHABLE();
    }
    if (length == 0u) return; // nothing to do!
#if ENABLE_SLOW_DCHECKS
    DisallowGarbageCollection no_gc;
    Tagged<BackingStore> backing_store = Cast<BackingStore>(elements);
    DCHECK(length <= std::numeric_limits<int>::max());
    int length_int = static_cast<int>(length);
    int capacity_int = static_cast<int>(backing_store->length());
    if (IsSmiElementsKind(KindTraits::Kind)) {
      HandleScope scope(isolate);
      for (int i = 0; i < length_int; i++) {
        Tagged<Object> element = Cast<FixedArray>(backing_store)->get(i);
        DCHECK(IsSmi(element) || (IsHoleyElementsKind(KindTraits::Kind) &&
                                  IsTheHole(element, isolate)));
      }
    } else if (KindTraits::Kind == PACKED_ELEMENTS ||
               KindTraits::Kind == PACKED_DOUBLE_ELEMENTS) {
      for (int i = 0; i < length_int; i++) {
        DCHECK(!backing_store->is_the_hole(isolate, i));
      }
    } else {
      DCHECK(IsHoleyElementsKind(KindTraits::Kind));
    }
    // Any values in the backing store outside of the length have to be holes,
    // even if it is PACKED, in case it is extended (and made HOLEY as part of
    // that extension).
    for (int i = length_int; i < capacity_int; i++) {
      DCHECK(backing_store->is_the_hole(isolate, i));
    }
#endif
#endif
  }
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, v8::internal::Isolate::heap(), v8::internal::IsDoubleElementsKind(), v8::internal::IsHoleyElementsKind(), v8::internal::IsSmi(), v8::internal::IsSmiElementsKind(), v8::internal::IsSmiOrObjectElementsKind(), v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::PACKED_DOUBLE_ELEMENTS, v8::internal::PACKED_ELEMENTS, and v8::internal::UNREACHABLE().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/elements.cc