v8::internal::compiler::RpoNumber Class Reference
#include <instruction.h>
Public Member Functions
RpoNumber ()
int ToInt () const
size_t ToSize () const
bool IsValid () const
bool IsNext (const RpoNumber other) const
RpoNumber Next () const
bool operator== (RpoNumber other) const
bool operator!= (RpoNumber other) const
bool operator> (RpoNumber other) const
bool operator< (RpoNumber other) const
bool operator<= (RpoNumber other) const
bool operator>= (RpoNumber other) const
Static Public Member Functions
static RpoNumber FromInt (int index)
static RpoNumber Invalid ()
Static Public Attributes
static const int kInvalidRpoNumber = -1
Private Member Functions
RpoNumber (int32_t index)
Private Attributes
int32_t index_
Detailed Description
Definition at line 1170 of file instruction.h.
Constructor & Destructor Documentation
RpoNumber() [1/2]
v8::internal::compiler::RpoNumber::RpoNumber () [inline]
Definition at line 1173 of file instruction.h.
: index_(kInvalidRpoNumber) {}
RpoNumber() [2/2]
v8::internal::compiler::RpoNumber::RpoNumber (int32_t index) [inline], [explicit], [private]
Definition at line 1206 of file instruction.h.
: index_(index) {}
Member Function Documentation
FromInt()
static RpoNumber v8::internal::compiler::RpoNumber::FromInt (int index) [inline], [static]
Definition at line 1184 of file instruction.h.
{ return RpoNumber(index); }
References v8::internal::index.
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), v8::internal::compiler::JumpThreading::ApplyForwarding(), v8::internal::compiler::BundleBuilder::BuildBundles(), v8::internal::compiler::LiveRangeBuilder::BuildLiveRanges(), v8::internal::compiler::LiveRangeConnector::CommitSpillsInDeferredBlocks(), v8::internal::compiler::InstructionSequence::ComputeAssemblyOrder(), v8::internal::compiler::SpillPlacer::FirstBackwardPass(), v8::internal::compiler::SpillPlacer::ForwardPass(), v8::internal::compiler::GetLoopEndRpo(), v8::internal::compiler::GetRpo(), v8::internal::compiler::InstructionSequence::InstructionBlocksFor(), v8::internal::compiler::LinearScanAllocator::LastDeferredInstructionIndex(), v8::internal::compiler::anonymous_namespace{jump-threading.cc}::JumpThreadingState::onstack(), v8::internal::compiler::operator<<(), v8::internal::compiler::InstructionSequence::PrintBlock(), v8::internal::compiler::GraphC1Visualizer::PrintSchedule(), v8::internal::compiler::InstructionSelector::rpo_number(), v8::internal::compiler::SpillPlacer::SecondBackwardPass(), v8::internal::compiler::Constant::ToRpoNumber(), and v8::internal::compiler::anonymous_namespace{jump-threading.cc}::JumpThreadingState::unvisited().
Invalid()
static RpoNumber v8::internal::compiler::RpoNumber::Invalid () [inline], [static]
Definition at line 1185 of file instruction.h.
{ return RpoNumber(kInvalidRpoNumber); }
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), v8::internal::compiler::SpillPlacer::ClearData(), v8::internal::compiler::InstructionSequence::ComputeAssemblyOrder(), v8::internal::compiler::CodeGenerator::ComputeBranchInfo(), v8::internal::compiler::JumpThreading::ComputeForwarding(), v8::internal::compiler::GetLoopEndRpo(), v8::internal::compiler::GetRpo(), and v8::internal::compiler::InstructionSequence::RecomputeAssemblyOrderForTesting().
IsNext()
bool v8::internal::compiler::RpoNumber::IsNext (const RpoNumber other) const [inline]
Definition at line 1187 of file instruction.h.
                                           {
    DCHECK(IsValid());
    return other.index_ == this->index_ + 1;
  }
References v8::internal::DCHECK(), and index_.
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), and v8::internal::compiler::CodeGenerator::IsNextInAssemblyOrder().
IsValid()
bool v8::internal::compiler::RpoNumber::IsValid () const [inline]
Definition at line 1183 of file instruction.h.
{ return index_ >= 0; }
Referenced by v8::internal::compiler::JumpThreading::ApplyForwarding(), v8::internal::compiler::CodeGenerator::AssembleInstruction(), v8::internal::compiler::JumpThreading::ComputeForwarding(), v8::internal::compiler::SpillPlacer::ExpandBoundsToInclude(), v8::internal::compiler::operator<<(), and v8::internal::compiler::SpillPlacer::SetSpillRequired().
Next()
RpoNumber v8::internal::compiler::RpoNumber::Next () const [inline]
Definition at line 1192 of file instruction.h.
                         {
    DCHECK(IsValid());
    return RpoNumber(index_ + 1);
  }
References v8::internal::DCHECK().
Referenced by v8::internal::compiler::SpillPlacer::Add(), and v8::internal::compiler::LinearScanAllocator::LastDeferredInstructionIndex().
operator!=()
bool v8::internal::compiler::RpoNumber::operator!= (RpoNumber other) const [inline]
Definition at line 1199 of file instruction.h.
{ return index_ != other.index_; }
References index_.
operator<()
bool v8::internal::compiler::RpoNumber::operator< (RpoNumber other) const [inline]
Definition at line 1201 of file instruction.h.
{ return index_ < other.index_; }
References index_.
operator<=()
bool v8::internal::compiler::RpoNumber::operator<= (RpoNumber other) const [inline]
Definition at line 1202 of file instruction.h.
{ return index_ <= other.index_; }
References index_.
operator==()
bool v8::internal::compiler::RpoNumber::operator== (RpoNumber other) const [inline]
Definition at line 1198 of file instruction.h.
{ return index_ == other.index_; }
References index_.
operator>()
bool v8::internal::compiler::RpoNumber::operator> (RpoNumber other) const [inline]
Definition at line 1200 of file instruction.h.
{ return index_ > other.index_; }
References index_.
operator>=()
bool v8::internal::compiler::RpoNumber::operator>= (RpoNumber other) const [inline]
Definition at line 1203 of file instruction.h.
{ return index_ >= other.index_; }
References index_.
ToInt()
int v8::internal::compiler::RpoNumber::ToInt () const [inline]
Definition at line 1175 of file instruction.h.
                    {
    DCHECK(IsValid());
    return index_;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::compiler::TopLevelLiveRange::AddBlockRequiringSpillOperand(), v8::internal::compiler::InstructionSequence::AddImmediate(), v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), v8::internal::compiler::JumpThreading::ApplyForwarding(), v8::internal::compiler::UnwindingInfoWriter::BeginInstructionBlock(), v8::internal::compiler::LiveRangeConnector::CommitSpillsInDeferredBlocks(), v8::internal::compiler::JumpThreading::ComputeForwarding(), v8::internal::compiler::LiveRangeConnector::ConnectRanges(), v8::internal::compiler::RegisterAllocator::FindOptimalSplitPos(), v8::internal::compiler::SpillPlacer::FirstBackwardPass(), v8::internal::compiler::anonymous_namespace{jump-threading.cc}::JumpThreadingState::Forward(), v8::internal::compiler::SpillPlacer::ForwardPass(), v8::internal::compiler::GetLoopEndRpo(), v8::internal::compiler::operator<<(), v8::internal::compiler::LiveRangeBuilder::ProcessLoopHeader(), v8::internal::compiler::anonymous_namespace{jump-threading.cc}::JumpThreadingState::PushIfUnvisited(), v8::internal::compiler::LiveRangeConnector::ResolveControlFlow(), and v8::internal::compiler::SpillPlacer::SecondBackwardPass().
ToSize()
size_t v8::internal::compiler::RpoNumber::ToSize () const [inline]
Definition at line 1179 of file instruction.h.
                        {
    DCHECK(IsValid());
    return static_cast<size_t>(index_);
  }
References v8::internal::DCHECK().
Referenced by v8::internal::compiler::InstructionSequence::AddImmediate(), v8::internal::compiler::LiveRangeBuilder::ComputeLiveOut(), v8::internal::compiler::CodeGenerator::GetLabel(), v8::internal::compiler::RegisterAllocationData::GetSpillState(), v8::internal::compiler::InstructionSequence::InstructionBlockAt(), v8::internal::compiler::InstructionSequence::InstructionBlocksFor(), v8::internal::compiler::InstructionSequence::LastLoopInstructionIndex(), v8::internal::compiler::operator<<(), v8::internal::compiler::RegisterAllocationData::RememberSpillState(), v8::internal::compiler::SpillPlacer::SetDefinition(), and v8::internal::compiler::SpillPlacer::SetSpillRequired().
Member Data Documentation
index_
int32_t v8::internal::compiler::RpoNumber::index_ [private]
Definition at line 1207 of file instruction.h.
Referenced by IsNext(), operator!=(), operator<(), operator<=(), operator==(), operator>(), and operator>=().
kInvalidRpoNumber
const int v8::internal::compiler::RpoNumber::kInvalidRpoNumber = -1 [static]
Definition at line 1172 of file instruction.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/instruction.h