v8::internal::maglev::LoadNamedGeneric Class Reference
#include <maglev-ir.h>
Public Member Functions
LoadNamedGeneric (uint64_t bitfield, compiler::NameRef name, const compiler::FeedbackSource &feedback)
compiler::NameRef name () const
compiler::FeedbackSource feedback () const
Input & context ()
Input & object_input ()
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties = OpProperties::JSCall()
static constexpr Base::InputTypes kInputTypes
static constexpr int kContextIndex = 0
static constexpr int kObjectIndex = 1
Private Types
using Base = FixedInputValueNodeT< 2, LoadNamedGeneric >
Private Attributes
const compiler::NameRef name_
const compiler::FeedbackSource feedback_
Additional Inherited Members
Detailed Description
Definition at line 9324 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::LoadNamedGeneric::Base = FixedInputValueNodeT<2, LoadNamedGeneric> [private]
Definition at line 9325 of file maglev-ir.h.
Constructor & Destructor Documentation
LoadNamedGeneric()
v8::internal::maglev::LoadNamedGeneric::LoadNamedGeneric (uint64_t bitfield, compiler::NameRef name, const compiler::FeedbackSource & feedback) [inline], [explicit]
Definition at line 9328 of file maglev-ir.h.
      : Base(bitfield), name_(name), feedback_(feedback) {}
Member Function Documentation
context()
Input& v8::internal::maglev::LoadNamedGeneric::context () [inline]
Definition at line 9342 of file maglev-ir.h.
{ return input(kContextIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
feedback()
compiler::FeedbackSource v8::internal::maglev::LoadNamedGeneric::feedback () const [inline]
Definition at line 9338 of file maglev-ir.h.
{ return feedback_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::LoadNamedGeneric::GenerateCode (MaglevAssembler * , const ProcessingState &)
MaxCallStackArgs()
int v8::internal::maglev::LoadNamedGeneric::MaxCallStackArgs () const
name()
compiler::NameRef v8::internal::maglev::LoadNamedGeneric::name () const [inline]
Definition at line 9337 of file maglev-ir.h.
{ return name_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
object_input()
Input& v8::internal::maglev::LoadNamedGeneric::object_input () [inline]
Definition at line 9343 of file maglev-ir.h.
{ return input(kObjectIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::LoadNamedGeneric::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8269 of file maglev-ir.cc.
                                                                              {
  os << "(" << *name_.object() << ")";
}
References name_, and v8::internal::compiler::NameRef::object().
SetValueLocationConstraints()
void v8::internal::maglev::LoadNamedGeneric::SetValueLocationConstraints ()
Member Data Documentation
feedback_
const compiler::FeedbackSource v8::internal::maglev::LoadNamedGeneric::feedback_ [private]
Definition at line 9352 of file maglev-ir.h.
kContextIndex
constexpr int v8::internal::maglev::LoadNamedGeneric::kContextIndex = 0 [static], [constexpr]
Definition at line 9340 of file maglev-ir.h.
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::LoadNamedGeneric::kInputTypes [static], [constexpr]
Initial value:
{
      ValueRepresentation::kTagged, ValueRepresentation::kTagged}
Definition at line 9334 of file maglev-ir.h.
kObjectIndex
constexpr int v8::internal::maglev::LoadNamedGeneric::kObjectIndex = 1 [static], [constexpr]
Definition at line 9341 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::LoadNamedGeneric::kProperties = OpProperties::JSCall() [static], [constexpr]
Definition at line 9333 of file maglev-ir.h.
name_
const compiler::NameRef v8::internal::maglev::LoadNamedGeneric::name_ [private]
Definition at line 9351 of file maglev-ir.h.
Referenced by PrintParams().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc