v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData > Class Template Reference
#include <snapshot-table-opindex.h>
Public Types
using Base = SnapshotTable< Value, KeyData >
using Key = typename SnapshotTable< Value, KeyData >::Key
Public Member Functions
SparseOpIndexSnapshotTable (Zone *zone)
Value Get (OpIndex idx) const
Value GetPredecessorValue (OpIndex idx, int predecessor_index)
bool Set (OpIndex idx, Value new_value)
void NewKey (OpIndex idx, KeyData data, Value initial_value=Value{})
void NewKey (OpIndex idx, Value initial_value=Value{})
bool HasKeyFor (OpIndex idx) const
std::optional< Key > TryGetKeyFor (OpIndex idx) const
auto begin ()
auto end ()
const Value & Get (Key key) const
bool Set (Key key, Value new_value)
Private Member Functions
Key GetOrCreateKey (OpIndex idx)
Private Attributes
ZoneAbslFlatHashMap< OpIndex, Key > indices_to_keys_
Detailed Description
template<class Value, class KeyData = NoKeyData>
class v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >
Definition at line 18 of file snapshot-table-opindex.h.
Member Typedef Documentation
Base
template<class Value , class KeyData = NoKeyData>
using v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::Base = SnapshotTable<Value, KeyData>
Definition at line 20 of file snapshot-table-opindex.h.
Key
template<class Value , class KeyData = NoKeyData>
using v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::Key = typename SnapshotTable<Value, KeyData>::Key
Definition at line 21 of file snapshot-table-opindex.h.
Constructor & Destructor Documentation
SparseOpIndexSnapshotTable()
template<class Value , class KeyData = NoKeyData>
v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::SparseOpIndexSnapshotTable (Zone * zone) [inline], [explicit]
Definition at line 23 of file snapshot-table-opindex.h.
      : Base(zone), indices_to_keys_(zone) {}
Member Function Documentation
begin()
template<class Value , class KeyData = NoKeyData>
auto v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::begin () [inline]
Definition at line 63 of file snapshot-table-opindex.h.
{ return indices_to_keys_.begin(); }
References v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::indices_to_keys_.
end()
template<class Value , class KeyData = NoKeyData>
auto v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::end () [inline]
Definition at line 64 of file snapshot-table-opindex.h.
{ return indices_to_keys_.end(); }
References v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::indices_to_keys_.
Get() [1/2]
template<class Value , class KeyData = NoKeyData>
const Value& v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Get [inline]
Definition at line 222 of file snapshot-table.h.
{ return key.entry_->value; }
Get() [2/2]
template<class Value , class KeyData = NoKeyData>
Value v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::Get (OpIndex idx) const [inline]
Definition at line 27 of file snapshot-table-opindex.h.
                               {
    auto it = indices_to_keys_.find(idx);
    if (it == indices_to_keys_.end()) return Value{};
    return Base::Get(it->second);
  }
References v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Get(), and v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::indices_to_keys_.
Referenced by v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::DcheckWordBinop(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::DcheckWordBinop(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::GetResolvedType(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::GetTypeForPhiInput(), v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::Invalidate(), v8::internal::compiler::turboshaft::MemoryContentTable::Invalidate(), v8::internal::compiler::turboshaft::MemoryContentTable::InvalidateAtOffset(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::InvalidateIfAlias(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::InvalidateIfAlias(), v8::internal::compiler::turboshaft::MemoryContentTable::InvalidateMaybeAliasing(), v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::InvalidateMaybeAliasing(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessAllocateStruct(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessAssumeMap(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::RefineTypeKnowledge(), and v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::RefineTypeKnowledgeNotNull().
GetOrCreateKey()
template<class Value , class KeyData = NoKeyData>
Key v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::GetOrCreateKey (OpIndex idx) [inline], [private]
Definition at line 67 of file snapshot-table-opindex.h.
                                  {
    auto it = indices_to_keys_.find(idx);
    if (it != indices_to_keys_.end()) return it->second;
    Key key = Base::NewKey();
    indices_to_keys_.insert({idx, key});
    return key;
  }
References v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::indices_to_keys_, v8::internal::key, and v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::NewKey().
Referenced by v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::Set().
GetPredecessorValue()
template<class Value , class KeyData = NoKeyData>
Value v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::GetPredecessorValue (OpIndex idx, int predecessor_index) [inline]
Definition at line 33 of file snapshot-table-opindex.h.
                                                                {
    auto it = indices_to_keys_.find(idx);
    if (it == indices_to_keys_.end()) return Value{};
    return Base::GetPredecessorValue(it->second, predecessor_index);
  }
References v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::GetPredecessorValue(), and v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::indices_to_keys_.
Referenced by v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::GetTypeForPhiInput().
HasKeyFor()
template<class Value , class KeyData = NoKeyData>
bool v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::HasKeyFor (OpIndex idx) const [inline]
Definition at line 53 of file snapshot-table-opindex.h.
                                    {
    return indices_to_keys_.find(idx) != indices_to_keys_.end();
  }
References v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::indices_to_keys_.
Referenced by v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessStore(), and v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessStructSet().
NewKey() [1/2]
template<class Value , class KeyData = NoKeyData>
void v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::NewKey (OpIndex idx, KeyData data, Value initial_value = Value{}) [inline]
Definition at line 45 of file snapshot-table-opindex.h.
                                                                    {}) {
    DCHECK(!indices_to_keys_[idx].has_value());
    indices_to_keys_[idx] = Base::NewKey(data, initial_value);
  }
NewKey() [2/2]
template<class Value , class KeyData = NoKeyData>
void v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::NewKey (OpIndex idx, Value initial_value = Value{}) [inline]
Definition at line 49 of file snapshot-table-opindex.h.
                                                      {}) {
    NewKey(idx, KeyData{}, initial_value);
  }
Set() [1/2]
template<class Value , class KeyData = NoKeyData>
bool v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Set [inline]
Definition at line 239 of file snapshot-table.h.
                                     {
    DCHECK(!current_snapshot_->IsSealed());
    if (key.entry_->value == new_value) return false;
    log_.push_back(LogEntry{*key.entry_, key.entry_->value, new_value});
    key.entry_->value = new_value;
    return true;
  }
Set() [2/2]
template<class Value , class KeyData = NoKeyData>
bool v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::Set (OpIndex idx, Value new_value) [inline]
Definition at line 40 of file snapshot-table-opindex.h.
                                         {
    Key key = GetOrCreateKey(idx);
    return Base::Set(key, new_value);
  }
References v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::GetOrCreateKey(), v8::internal::key, and v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Set().
Referenced by v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::InvalidateIfAlias(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::InvalidateIfAlias(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessAllocate(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessAllocate(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessAssumeMap(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessCall(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessStore(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessStructSet(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessWasmAllocateArray(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::RefineTypeKnowledge(), and v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::RefineTypeKnowledgeNotNull().
TryGetKeyFor()
template<class Value , class KeyData = NoKeyData>
std::optional<Key> v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::TryGetKeyFor (OpIndex idx) const [inline]
Definition at line 57 of file snapshot-table-opindex.h.
                                                   {
    auto it = indices_to_keys_.find(idx);
    if (it != indices_to_keys_.end()) return it->second;
    return std::nullopt;
  }
References v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::indices_to_keys_.
Referenced by v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::DcheckWordBinop(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::DcheckWordBinop(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::InvalidateIfAlias(), and v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::InvalidateIfAlias().
Member Data Documentation
indices_to_keys_
template<class Value , class KeyData = NoKeyData>
ZoneAbslFlatHashMap<OpIndex, Key> v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::indices_to_keys_ [private]
Definition at line 74 of file snapshot-table-opindex.h.
Referenced by v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::begin(), v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::end(), v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::Get(), v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::GetOrCreateKey(), v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::GetPredecessorValue(), v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::HasKeyFor(), and v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::TryGetKeyFor().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/snapshot-table-opindex.h