v8::internal::RwxMemoryWriteScope Class Reference
#include <code-memory-access.h>
Public Member Functions
RwxMemoryWriteScope (const char *comment)
~RwxMemoryWriteScope ()
RwxMemoryWriteScope (const RwxMemoryWriteScope &)=delete
RwxMemoryWriteScope & operator= (const RwxMemoryWriteScope &)=delete
Static Public Member Functions
static bool IsSupported ()
Static Private Member Functions
static void SetWritable ()
static void SetExecutable ()
Friends
class RwxMemoryWriteScopeForTesting
class wasm::CodeSpaceWriteScope
class WritableJumpTablePair
Detailed Description
Definition at line 90 of file code-memory-access.h.
Constructor & Destructor Documentation
RwxMemoryWriteScope() [1/2]
v8::internal::RwxMemoryWriteScope::RwxMemoryWriteScope (const char * comment) [inline], [explicit]
Definition at line 28 of file code-memory-access-inl.h.
                                                            {
  if (!v8_flags.jitless || v8_flags.force_memory_protection_keys) {
    SetWritable();
  }
}
References SetWritable(), and v8::internal::v8_flags.
 RwxMemoryWriteScope()
v8::internal::RwxMemoryWriteScope::~RwxMemoryWriteScope () [inline]
Definition at line 34 of file code-memory-access-inl.h.
                                          {
  if (!v8_flags.jitless || v8_flags.force_memory_protection_keys) {
    SetExecutable();
  }
}
References SetExecutable(), and v8::internal::v8_flags.
RwxMemoryWriteScope() [2/2]
v8::internal::RwxMemoryWriteScope::RwxMemoryWriteScope (const RwxMemoryWriteScope &) [delete]
Member Function Documentation
IsSupported()
bool v8::internal::RwxMemoryWriteScope::IsSupported () [inline], [static]
Definition at line 373 of file code-memory-access-inl.h.
{ return false; }
Referenced by v8::internal::wasm::WasmCodeManager::HasMemoryProtectionKeySupport().
operator=()
RwxMemoryWriteScope& v8::internal::RwxMemoryWriteScope::operator= (const RwxMemoryWriteScope &) [delete]
SetExecutable()
void v8::internal::RwxMemoryWriteScope::SetExecutable () [inline], [static], [private]
Definition at line 379 of file code-memory-access-inl.h.
{}
Referenced by ~RwxMemoryWriteScope().
SetWritable()
void v8::internal::RwxMemoryWriteScope::SetWritable () [inline], [static], [private]
Definition at line 376 of file code-memory-access-inl.h.
{}
Referenced by RwxMemoryWriteScope().
Friends And Related Function Documentation
RwxMemoryWriteScopeForTesting
friend class RwxMemoryWriteScopeForTesting [friend]
Definition at line 113 of file code-memory-access.h.
wasm::CodeSpaceWriteScope
friend class wasm::CodeSpaceWriteScope [friend]
Definition at line 114 of file code-memory-access.h.
WritableJumpTablePair
friend class WritableJumpTablePair [friend]
Definition at line 115 of file code-memory-access.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/common/code-memory-access.h
/mnt/V8SourceCode/src/common/code-memory-access-inl.h