v8::OutputStream Class Reference
An interface for exporting data from V8, using `push` model.
#include <v8-profiler.h>
Public Types
enum WriteResult { kContinue = 0
, kAbort = 1
 }
Public Member Functions
virtual ~OutputStream ()=default
virtual void EndOfStream ()=0
Notify about the end of stream.
virtual int GetChunkSize ()
Get preferred output chunk size.
virtual WriteResult WriteAsciiChunk (char *data, int size)=0
Writes the next chunk of snapshot data into the stream.
virtual WriteResult WriteHeapStatsChunk (HeapStatsUpdate *data, int count)
Writes the next chunk of heap stats data into the stream.
Detailed Description
An interface for exporting data from V8, using `push` model.
Definition at line 186 of file v8-profiler.h.
Member Enumeration Documentation
WriteResult
enum v8::OutputStream::WriteResult
Enumerator
kContinue
kAbort
Definition at line 188 of file v8-profiler.h.
{ kContinue = 0, kAbort = 1 };
Constructor & Destructor Documentation
 OutputStream()
virtual v8::OutputStream::~OutputStream () [virtual], [default]
Member Function Documentation
EndOfStream()
virtual void v8::OutputStream::EndOfStream () [pure virtual]
Notify about the end of stream.
Implemented in v8::internal::StringOutputStream, v8::internal::FileOutputStream, v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::HeapStatsStream, and v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::HeapSnapshotOutputStream.
Referenced by v8::internal::OutputStreamWriter::Finalize(), and v8::internal::HeapObjectsMap::PushHeapObjectsStats().
GetChunkSize()
virtual int v8::OutputStream::GetChunkSize () [inline], [virtual]
Get preferred output chunk size.
Called only once.
Reimplemented in v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::HeapSnapshotOutputStream.
Definition at line 193 of file v8-profiler.h.
{ return 1024; }
Referenced by v8::internal::HeapObjectsMap::PushHeapObjectsStats(), v8::CpuProfile::Serialize(), and v8::HeapSnapshot::Serialize().
WriteAsciiChunk()
virtual WriteResult v8::OutputStream::WriteAsciiChunk (char * data, int size) [pure virtual]
Writes the next chunk of snapshot data into the stream.
Writing can be stopped by returning kAbort as function result. EndOfStream will not be called in case writing was aborted.
Implemented in v8::internal::StringOutputStream, v8::internal::FileOutputStream, v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::HeapStatsStream, and v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::HeapSnapshotOutputStream.
Referenced by v8::internal::OutputStreamWriter::WriteChunk().
WriteHeapStatsChunk()
virtual WriteResult v8::OutputStream::WriteHeapStatsChunk (HeapStatsUpdate * data, int count) [inline], [virtual]
Writes the next chunk of heap stats data into the stream.
Writing can be stopped by returning kAbort as function result. EndOfStream will not be called in case writing was aborted.
Reimplemented in v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::HeapStatsStream.
Definition at line 205 of file v8-profiler.h.
                                                                            {
    return kAbort;
  }
Referenced by v8::internal::HeapObjectsMap::PushHeapObjectsStats().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/v8-profiler.h