v8::internal::WasmTrustedInstanceData Class Reference
#include <wasm-objects.h>
Public Member Functions
DECL_PROTECTED_POINTER_ACCESSORS (dispatch_table_for_imports, WasmDispatchTable) DECL_PROTECTED_POINTER_ACCESSORS(managed_native_module
TrustedManaged< wasm::NativeModule > DECL_PROTECTED_POINTER_ACCESSORS (memory_bases_and_sizes, TrustedFixedAddressArray) inline void clear_padding()
Tagged< WasmMemoryObject > memory_object (int memory_index) const
uint8_t * memory_base (int memory_index) const
size_t memory_size (int memory_index) const
wasm::NativeModule * native_module () const
Tagged< WasmModuleObject > module_object () const
const wasm::WasmModule * module () const
void SetRawMemory (int memory_index, uint8_t *mem_start, size_t mem_size)
WasmCodePointer GetCallTarget (uint32_t func_index)
Tagged< WasmDispatchTable > dispatch_table (uint32_t table_index)
bool has_dispatch_table (uint32_t table_index)
bool try_get_func_ref (int index, Tagged< WasmFuncRef > *result)
uint8_t * GetGlobalStorage (const wasm::WasmGlobal &)
std::pair< Tagged< FixedArray >, uint32_t > GetGlobalBufferAndIndex (const wasm::WasmGlobal &)
wasm::WasmValue GetGlobalValue (Isolate *, const wasm::WasmGlobal &)
OBJECT_CONSTRUCTORS (WasmTrustedInstanceData, ExposedTrustedObject)
Static Public Member Functions
static DirectHandle< WasmTrustedInstanceData > New (Isolate *, DirectHandle< WasmModuleObject >, bool shared)
static bool CopyTableEntries (Isolate *isolate, DirectHandle< WasmTrustedInstanceData > trusted_instance_data, uint32_t table_dst_index, uint32_t table_src_index, uint32_t dst, uint32_t src, uint32_t count) V8_WARN_UNUSED_RESULT
static std::optional< MessageTemplate > InitTableEntries (Isolate *isolate, DirectHandle< WasmTrustedInstanceData > trusted_instance_data, DirectHandle< WasmTrustedInstanceData > shared_trusted_instance_data, uint32_t table_index, uint32_t segment_index, uint32_t dst, uint32_t src, uint32_t count) V8_WARN_UNUSED_RESULT
static DirectHandle< WasmFuncRef > GetOrCreateFuncRef (Isolate *isolate, DirectHandle< WasmTrustedInstanceData > trusted_instance_data, int function_index)
Static Public Attributes
static constexpr size_t kWasmInterpreterAdditionalFields = 0
static constexpr size_t kTaggedFieldsCount
static constexpr std::array< uint16_t, kTaggedFieldsCount > kTaggedFieldOffsets
static constexpr std::array< const char *, kTaggedFieldsCount > kTaggedFieldNames
static constexpr std::array< uint16_t, 6 > kProtectedFieldOffsets
static constexpr std::array< const char *, 6 > kProtectedFieldNames
Private Member Functions
void InitDataSegmentArrays (const wasm::NativeModule *)
Additional Inherited Members
Detailed Description
Definition at line 479 of file wasm-objects.h.
Member Function Documentation
CopyTableEntries()
bool v8::internal::WasmTrustedInstanceData::CopyTableEntries (Isolate * isolate, DirectHandle< WasmTrustedInstanceData > trusted_instance_data, uint32_t table_dst_index, uint32_t table_src_index, uint32_t dst, uint32_t src, uint32_t count) [static]
Definition at line 1897 of file wasm-objects.cc.
                                  {
  CHECK_LT(table_dst_index, trusted_instance_data->tables()->length());
  CHECK_LT(table_src_index, trusted_instance_data->tables()->length());
  auto table_dst =
      direct_handle(Cast<WasmTableObject>(
                        trusted_instance_data->tables()->get(table_dst_index)),
                    isolate);
  auto table_src =
      direct_handle(Cast<WasmTableObject>(
                        trusted_instance_data->tables()->get(table_src_index)),
                    isolate);
  uint32_t max_dst = table_dst->current_length();
  uint32_t max_src = table_src->current_length();
  bool copy_backward = src < dst;
  if (!base::IsInBounds(dst, count, max_dst) ||
      !base::IsInBounds(src, count, max_src)) {
    return false;
  }
  // no-op
  if ((dst == src && table_dst_index == table_src_index) || count == 0) {
    return true;
  }
  for (uint32_t i = 0; i < count; ++i) {
    uint32_t src_index = copy_backward ? (src + count - i - 1) : src + i;
    uint32_t dst_index = copy_backward ? (dst + count - i - 1) : dst + i;
    auto value = WasmTableObject::Get(isolate, table_src, src_index);
    WasmTableObject::Set(isolate, table_dst, dst_index, value);
  }
  return true;
}
References CHECK_LT, v8::internal::direct_handle(), v8::internal::WasmTableObject::Get(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::WasmTableObject::Set(), and v8::internal::value.
Referenced by v8::internal::RUNTIME_FUNCTION(), and v8::internal::wasm::WasmInterpreterRuntime::TableCopy().
DECL_PROTECTED_POINTER_ACCESSORS() [1/2]
v8::internal::WasmTrustedInstanceData::DECL_PROTECTED_POINTER_ACCESSORS (dispatch_table_for_imports , WasmDispatchTable)
DECL_PROTECTED_POINTER_ACCESSORS() [2/2]
TrustedManaged<wasm::NativeModule> v8::internal::WasmTrustedInstanceData::DECL_PROTECTED_POINTER_ACCESSORS (memory_bases_and_sizes , TrustedFixedAddressArray)
dispatch_table()
Tagged< WasmDispatchTable > v8::internal::WasmTrustedInstanceData::dispatch_table (uint32_t table_index) [inline]
Definition at line 297 of file wasm-objects-inl.h.
                          {
  Tagged<Object> table = dispatch_tables()->get(table_index);
  DCHECK(IsWasmDispatchTable(table));
  return Cast<WasmDispatchTable>(table);
}
References v8::internal::DCHECK().
GetCallTarget()
WasmCodePointer v8::internal::WasmTrustedInstanceData::GetCallTarget (uint32_t func_index)
Definition at line 1882 of file wasm-objects.cc.
                                                                          {
  wasm::NativeModule* native_module = this->native_module();
  SBXCHECK_BOUNDS(func_index, native_module->num_functions());
  if (func_index < native_module->num_imported_functions()) {
    return dispatch_table_for_imports()->target(func_index);
  }
  if (v8_flags.wasm_jitless) {
    return wasm::kInvalidWasmCodePointer;
  }
  return native_module->GetCodePointerHandle(func_index);
}
References v8::internal::dispatch_table_for_imports, v8::internal::wasm::NativeModule::GetCodePointerHandle(), v8::internal::wasm::kInvalidWasmCodePointer, native_module(), v8::internal::wasm::NativeModule::num_functions(), SBXCHECK_BOUNDS, and v8::internal::v8_flags.
GetGlobalBufferAndIndex()
std::pair< Tagged< FixedArray >, uint32_t > v8::internal::WasmTrustedInstanceData::GetGlobalBufferAndIndex (const wasm::WasmGlobal & global)
Definition at line 2165 of file wasm-objects.cc.
                                  {
  DisallowGarbageCollection no_gc;
  DCHECK(global.type.is_reference());
  if (global.mutability && global.imported) {
    Tagged<FixedArray> buffer =
        Cast<FixedArray>(imported_mutable_globals_buffers()->get(global.index));
    Address idx = imported_mutable_globals()->get(global.index);
    DCHECK_LE(idx, std::numeric_limits<uint32_t>::max());
    return {buffer, static_cast<uint32_t>(idx)};
  }
  return {tagged_globals_buffer(), global.offset};
}
References v8::internal::DCHECK(), DCHECK_LE, v8::internal::wasm::WasmGlobal::imported, v8::internal::wasm::WasmGlobal::index, v8::internal::wasm::ValueTypeBase::is_reference(), v8::internal::wasm::WasmGlobal::mutability, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::wasm::WasmGlobal::offset, v8::internal::tagged_globals_buffer, and v8::internal::wasm::WasmGlobal::type.
Referenced by GetGlobalValue().
GetGlobalStorage()
uint8_t * v8::internal::WasmTrustedInstanceData::GetGlobalStorage (const wasm::WasmGlobal & global)
Definition at line 2154 of file wasm-objects.cc.
                                  {
  DCHECK(!global.type.is_reference());
  if (global.mutability && global.imported) {
    return reinterpret_cast<uint8_t*>(
        imported_mutable_globals()->get_sandboxed_pointer(global.index));
  }
  return globals_start() + global.offset;
}
References v8::internal::DCHECK(), v8::internal::globals_start, v8::internal::wasm::WasmGlobal::imported, v8::internal::wasm::WasmGlobal::index, v8::internal::wasm::ValueTypeBase::is_reference(), v8::internal::wasm::WasmGlobal::mutability, v8::internal::wasm::WasmGlobal::offset, and v8::internal::wasm::WasmGlobal::type.
Referenced by GetGlobalValue().
GetGlobalValue()
wasm::WasmValue v8::internal::WasmTrustedInstanceData::GetGlobalValue (Isolate * isolate, const wasm::WasmGlobal & global)
Definition at line 2179 of file wasm-objects.cc.
                                                    {
  DisallowGarbageCollection no_gc;
  if (global.type.is_reference()) {
    Tagged<FixedArray> global_buffer; // The buffer of the global.
    uint32_t global_index = 0; // The index into the buffer.
    std::tie(global_buffer, global_index) = GetGlobalBufferAndIndex(global);
    return wasm::WasmValue(
        direct_handle(global_buffer->get(global_index), isolate),
        module()->canonical_type(global.type));
  }
  Address ptr = reinterpret_cast<Address>(GetGlobalStorage(global));
  switch (global.type.kind()) {
#define CASE_TYPE(valuetype, ctype) \
  case wasm::valuetype: \
    return wasm::WasmValue(base::ReadUnalignedValue<ctype>(ptr));
    FOREACH_WASMVALUE_CTYPES(CASE_TYPE)
#undef CASE_TYPE
    default:
      UNREACHABLE();
  }
}
References CASE_TYPE, v8::internal::direct_handle(), FOREACH_WASMVALUE_CTYPES, GetGlobalBufferAndIndex(), GetGlobalStorage(), v8::internal::wasm::ValueTypeBase::is_reference(), v8::internal::wasm::ValueTypeBase::kind(), module(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::TaggedImpl< HeapObjectReferenceType::STRONG, Address >::ptr(), v8::internal::wasm::WasmGlobal::type, and v8::internal::UNREACHABLE().
GetOrCreateFuncRef()
DirectHandle< WasmFuncRef > v8::internal::WasmTrustedInstanceData::GetOrCreateFuncRef (Isolate * isolate, DirectHandle< WasmTrustedInstanceData > trusted_instance_data, int function_index) [static]
Definition at line 1995 of file wasm-objects.cc.
                        {
  bool shared = HeapLayout::InAnySharedSpace(*trusted_instance_data);
  Tagged<WasmFuncRef> existing_func_ref;
  if (trusted_instance_data->try_get_func_ref(function_index,
                                              &existing_func_ref)) {
    return direct_handle(existing_func_ref, isolate);
  }
  const WasmModule* module = trusted_instance_data->module();
  bool is_import =
      function_index < static_cast<int>(module->num_imported_functions);
  wasm::ModuleTypeIndex sig_index = module->functions[function_index].sig_index;
  DirectHandle<TrustedObject> implicit_arg =
      is_import ? direct_handle(
                      Cast<TrustedObject>(
                          trusted_instance_data->dispatch_table_for_imports()
                              ->implicit_arg(function_index)),
                      isolate)
                : trusted_instance_data;
  // TODO(14034): Create funcref RTTs lazily?
  DirectHandle<Map> rtt{
      Cast<Map>(
          trusted_instance_data->managed_object_maps()->get(sig_index.index)),
      isolate};
  // Reuse the call target of the instance. In case of import wrappers, the
  // wrapper will automatically get tiered up together since it will use the
  // same CPT entry.
  DirectHandle<WasmInternalFunction> internal_function =
      isolate->factory()->NewWasmInternalFunction(
          implicit_arg, function_index, shared,
          trusted_instance_data->GetCallTarget(function_index));
  DirectHandle<WasmFuncRef> func_ref =
      isolate->factory()->NewWasmFuncRef(internal_function, rtt, shared);
  trusted_instance_data->func_refs()->set(function_index, *func_ref);
  return func_ref;
}
References v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::wasm::WasmModule::functions, v8::internal::HeapLayout::InAnySharedSpace(), v8::internal::wasm::TypeIndex::index, module(), and v8::internal::wasm::WasmModule::num_imported_functions.
Referenced by v8::internal::wasm::InstanceBuilder::Build_Phase1(), v8::internal::wasm::EvaluateConstantExpression(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::FunctionsProxy::Get(), v8::internal::WasmTableObject::Get(), v8::internal::wasm::JSPrototypesSetup::GetFunction(), v8::internal::wasm::WasmInterpreterRuntime::GetFunctionRef(), v8::internal::wasm::InstanceBuilder::ProcessExports(), and v8::internal::RUNTIME_FUNCTION().
has_dispatch_table()
bool v8::internal::WasmTrustedInstanceData::has_dispatch_table (uint32_t table_index) [inline]
Definition at line 304 of file wasm-objects-inl.h.
                                                                     {
  Tagged<Object> maybe_table = dispatch_tables()->get(table_index);
  DCHECK(maybe_table == Smi::zero() || IsWasmDispatchTable(maybe_table));
  return maybe_table != Smi::zero();
}
References v8::internal::DCHECK(), and v8::internal::Smi::zero().
InitDataSegmentArrays()
void v8::internal::WasmTrustedInstanceData::InitDataSegmentArrays (const wasm::NativeModule * native_module) [private]
Definition at line 1855 of file wasm-objects.cc.
                                           {
  const WasmModule* module = native_module->module();
  base::Vector<const uint8_t> wire_bytes = native_module->wire_bytes();
  uint32_t num_data_segments = module->num_declared_data_segments;
  // The number of declared data segments will be zero if there is no DataCount
  // section. These arrays will not be allocated nor initialized in that case,
  // since they cannot be used (since the validator checks that number of
  // declared data segments when validating the memory.init and memory.drop
  // instructions).
  DCHECK(num_data_segments == 0 ||
         num_data_segments == module->data_segments.size());
  for (uint32_t i = 0; i < num_data_segments; ++i) {
    const wasm::WasmDataSegment& segment = module->data_segments[i];
    // Initialize the pointer and size of passive segments.
    auto source_bytes = wire_bytes.SubVector(segment.source.offset(),
                                             segment.source.end_offset());
    data_segment_starts()->set(i,
                               reinterpret_cast<Address>(source_bytes.begin()));
    // Set the active segments to being already dropped, since memory.init on
    // a dropped passive segment and an active segment have the same
    // behavior.
    data_segment_sizes()->set(static_cast<int>(i),
                              segment.active ? 0 : source_bytes.length());
  }
}
References v8::internal::wasm::WasmDataSegment::active, v8::internal::data_segment_starts, v8::internal::wasm::WasmModule::data_segments, v8::internal::DCHECK(), v8::internal::wasm::WireBytesRef::end_offset(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::NativeModule::module(), module(), native_module(), v8::internal::wasm::WasmModule::num_declared_data_segments, v8::internal::wasm::WireBytesRef::offset(), v8::internal::wasm::WasmDataSegment::source, v8::base::Vector< T >::SubVector(), and v8::internal::wasm::NativeModule::wire_bytes().
InitTableEntries()
std::optional< MessageTemplate > v8::internal::WasmTrustedInstanceData::InitTableEntries (Isolate * isolate, DirectHandle< WasmTrustedInstanceData > trusted_instance_data, DirectHandle< WasmTrustedInstanceData > shared_trusted_instance_data, uint32_t table_index, uint32_t segment_index, uint32_t dst, uint32_t src, uint32_t count) [static]
Definition at line 1935 of file wasm-objects.cc.
                    {
  AccountingAllocator allocator;
  // This {Zone} will be used only by the temporary WasmFullDecoder allocated
  // down the line from this call. Therefore it is safe to stack-allocate it
  // here.
  Zone zone(&allocator, "LoadElemSegment");
  const WasmModule* module = trusted_instance_data->module();
  bool table_is_shared = module->tables[table_index].shared;
  bool segment_is_shared = module->elem_segments[segment_index].shared;
  DirectHandle<WasmTableObject> table_object(
      Cast<WasmTableObject>((table_is_shared ? shared_trusted_instance_data
                                             : trusted_instance_data)
                                ->tables()
                                ->get(table_index)),
      isolate);
  // If needed, try to lazily initialize the element segment.
  std::optional<MessageTemplate> opt_error = wasm::InitializeElementSegment(
      &zone, isolate, trusted_instance_data, shared_trusted_instance_data,
      segment_index);
  if (opt_error.has_value()) return opt_error;
  DirectHandle<FixedArray> elem_segment(
      Cast<FixedArray>((segment_is_shared ? shared_trusted_instance_data
                                          : trusted_instance_data)
                           ->element_segments()
                           ->get(segment_index)),
      isolate);
  if (!base::IsInBounds<uint64_t>(dst, count, table_object->current_length())) {
    return {MessageTemplate::kWasmTrapTableOutOfBounds};
  }
  if (!base::IsInBounds<uint64_t>(src, count, elem_segment->length())) {
    return {MessageTemplate::kWasmTrapElementSegmentOutOfBounds};
  }
  for (size_t i = 0; i < count; i++) {
    WasmTableObject::Set(
        isolate, table_object, static_cast<int>(dst + i),
        direct_handle(elem_segment->get(static_cast<int>(src + i)), isolate));
  }
  return {};
}
References v8::internal::direct_handle(), v8::internal::wasm::WasmModule::elem_segments, v8::internal::element_segments, v8::internal::wasm::InitializeElementSegment(), module(), v8::internal::WasmTableObject::Set(), v8::internal::wasm::WasmModule::tables, and v8::internal::tables.
Referenced by v8::internal::RUNTIME_FUNCTION(), and v8::internal::wasm::WasmInterpreterRuntime::TableInit().
memory_base()
uint8_t * v8::internal::WasmTrustedInstanceData::memory_base (int memory_index) const [inline]
Definition at line 285 of file wasm-objects-inl.h.
                                                                    {
  DCHECK_EQ(memory0_start(),
            reinterpret_cast<uint8_t*>(memory_bases_and_sizes()->get(0)));
  return reinterpret_cast<uint8_t*>(
      memory_bases_and_sizes()->get(2 * memory_index));
}
References DCHECK_EQ.
memory_object()
Tagged< WasmMemoryObject > v8::internal::WasmTrustedInstanceData::memory_object (int memory_index) const [inline]
Definition at line 280 of file wasm-objects-inl.h.
                            {
  return Cast<WasmMemoryObject>(memory_objects()->get(memory_index));
}
References v8::internal::memory_objects.
memory_size()
size_t v8::internal::WasmTrustedInstanceData::memory_size (int memory_index) const [inline]
Definition at line 292 of file wasm-objects-inl.h.
                                                                  {
  DCHECK_EQ(memory0_size(), memory_bases_and_sizes()->get(1));
  return memory_bases_and_sizes()->get(2 * memory_index + 1);
}
References DCHECK_EQ, and v8::internal::memory0_size.
module()
const wasm::WasmModule * v8::internal::WasmTrustedInstanceData::module () const [inline]
Definition at line 318 of file wasm-objects-inl.h.
                                                            {
  return native_module()->module();
}
References v8::internal::wasm::NativeModule::module(), and native_module().
Referenced by GetGlobalValue(), GetOrCreateFuncRef(), InitDataSegmentArrays(), InitTableEntries(), New(), and SetRawMemory().
module_object()
Tagged< WasmModuleObject > v8::internal::WasmTrustedInstanceData::module_object () const [inline]
Definition at line 314 of file wasm-objects-inl.h.
                                                                      {
  return instance_object()->module_object();
}
References v8::internal::instance_object.
Referenced by New().
native_module()
wasm::NativeModule * v8::internal::WasmTrustedInstanceData::native_module () const [inline]
Definition at line 310 of file wasm-objects-inl.h.
                                                               {
  return managed_native_module()->get().get();
}
Referenced by GetCallTarget(), InitDataSegmentArrays(), module(), and New().
New()
DirectHandle< WasmTrustedInstanceData > v8::internal::WasmTrustedInstanceData::New (Isolate * isolate, DirectHandle< WasmModuleObject > module_object, bool shared) [static]
Definition at line 1686 of file wasm-objects.cc.
                 {
  // Read the link to the {std::shared_ptr<NativeModule>} once from the
  // `module_object` and use it to initialize the fields of the
  // `WasmTrustedInstanceData`. It will then be stored in a `TrustedManaged` in
  // the `WasmTrustedInstanceData` where it is safe from manipulation.
  std::shared_ptr<wasm::NativeModule> native_module =
      module_object->shared_native_module();
  // Do first allocate all objects that will be stored in instance fields,
  // because otherwise we would have to allocate when the instance is not fully
  // initialized yet, which can lead to heap verification errors.
  const WasmModule* module = native_module->module();
  AllocationType allocation =
      shared ? AllocationType::kSharedOld : AllocationType::kYoung;
  int num_imported_functions = module->num_imported_functions;
  DirectHandle<WasmDispatchTable> dispatch_table_for_imports =
      isolate->factory()->NewWasmDispatchTable(num_imported_functions,
                                               wasm::kWasmFuncRef, shared);
  DirectHandle<FixedArray> well_known_imports =
      isolate->factory()->NewFixedArray(num_imported_functions, allocation);
  DirectHandle<FixedArray> func_refs =
      isolate->factory()->NewFixedArrayWithZeroes(
          static_cast<int>(module->functions.size()), allocation);
  int num_imported_mutable_globals = module->num_imported_mutable_globals;
  // The imported_mutable_globals is essentially a FixedAddressArray (storing
  // sandboxed pointers), but some entries (the indices for reference-type
  // globals) are accessed as 32-bit integers which is more convenient with a
  // raw ByteArray.
  DirectHandle<FixedAddressArray> imported_mutable_globals =
      FixedAddressArray::New(isolate, num_imported_mutable_globals, allocation);
  int num_data_segments = module->num_declared_data_segments;
  DirectHandle<FixedAddressArray> data_segment_starts =
      FixedAddressArray::New(isolate, num_data_segments, allocation);
  DirectHandle<FixedUInt32Array> data_segment_sizes =
      FixedUInt32Array::New(isolate, num_data_segments, allocation);
#if V8_ENABLE_DRUMBRAKE
  DirectHandle<FixedInt32Array> imported_function_indices =
      FixedInt32Array::New(isolate, num_imported_functions);
#endif // V8_ENABLE_DRUMBRAKE
  static_assert(wasm::kV8MaxWasmMemories < kMaxInt / 2);
  int num_memories = static_cast<int>(module->memories.size());
  DirectHandle<FixedArray> memory_objects =
      isolate->factory()->NewFixedArray(num_memories, allocation);
  DirectHandle<TrustedFixedAddressArray> memory_bases_and_sizes =
      TrustedFixedAddressArray::New(
          isolate, 2 * num_memories,
          shared ? AllocationType::kSharedTrusted : AllocationType::kTrusted);
  // TODO(clemensb): Should we have singleton empty dispatch table in the
  // trusted space?
  DirectHandle<WasmDispatchTable> empty_dispatch_table =
      isolate->factory()->NewWasmDispatchTable(0, wasm::kWasmFuncRef, shared);
  DirectHandle<ProtectedFixedArray> empty_protected_fixed_array =
      isolate->factory()->empty_protected_fixed_array();
  // Use the same memory estimate as the (untrusted) Managed in
  // WasmModuleObject. This is not security critical, and we at least always
  // read the memory estimation of *some* NativeModule here.
  size_t estimated_size =
      module_object->managed_native_module()->estimated_size();
  DirectHandle<TrustedManaged<wasm::NativeModule>>
      trusted_managed_native_module = TrustedManaged<wasm::NativeModule>::From(
          isolate, estimated_size, native_module, shared);
  // Now allocate the WasmTrustedInstanceData.
  // During this step, no more allocations should happen because the instance is
  // incomplete yet, so we should not trigger heap verification at this point.
  DirectHandle<WasmTrustedInstanceData> trusted_data =
      isolate->factory()->NewWasmTrustedInstanceData(shared);
  {
    DisallowHeapAllocation no_gc;
    // Some constants:
    uint8_t* empty_backing_store_buffer =
        reinterpret_cast<uint8_t*>(EmptyBackingStoreBuffer());
    ReadOnlyRoots ro_roots{isolate};
    Tagged<FixedArray> empty_fixed_array = ro_roots.empty_fixed_array();
    trusted_data->set_dispatch_table_for_imports(*dispatch_table_for_imports);
    trusted_data->set_imported_mutable_globals(*imported_mutable_globals);
    trusted_data->set_dispatch_table0(*empty_dispatch_table);
    trusted_data->set_dispatch_tables(*empty_protected_fixed_array);
    trusted_data->set_shared_part(*trusted_data); // TODO(14616): Good enough?
    trusted_data->set_data_segment_starts(*data_segment_starts);
    trusted_data->set_data_segment_sizes(*data_segment_sizes);
    trusted_data->set_element_segments(empty_fixed_array);
    trusted_data->set_managed_native_module(*trusted_managed_native_module);
    trusted_data->set_new_allocation_limit_address(
        isolate->heap()->NewSpaceAllocationLimitAddress());
    trusted_data->set_new_allocation_top_address(
        isolate->heap()->NewSpaceAllocationTopAddress());
    trusted_data->set_old_allocation_limit_address(
        isolate->heap()->OldSpaceAllocationLimitAddress());
    trusted_data->set_old_allocation_top_address(
        isolate->heap()->OldSpaceAllocationTopAddress());
    trusted_data->set_globals_start(empty_backing_store_buffer);
#if V8_ENABLE_DRUMBRAKE
    trusted_data->set_imported_function_indices(*imported_function_indices);
#endif // V8_ENABLE_DRUMBRAKE
    if (!shared) trusted_data->set_native_context(*isolate->native_context());
    trusted_data->set_jump_table_start(native_module->jump_table_start());
    trusted_data->set_hook_on_function_call_address(
        isolate->debug()->hook_on_function_call_address());
    trusted_data->set_managed_object_maps(
        *isolate->factory()->empty_fixed_array());
    trusted_data->set_well_known_imports(*well_known_imports);
    trusted_data->set_func_refs(*func_refs);
    trusted_data->set_feedback_vectors(
        *isolate->factory()->empty_fixed_array());
    trusted_data->set_tiering_budget_array(
        native_module->tiering_budget_array());
    trusted_data->set_break_on_entry(module_object->script()->break_on_entry());
    trusted_data->InitDataSegmentArrays(native_module.get());
    trusted_data->set_memory0_start(empty_backing_store_buffer);
    trusted_data->set_memory0_size(0);
    trusted_data->set_memory_objects(*memory_objects);
    trusted_data->set_memory_bases_and_sizes(*memory_bases_and_sizes);
    trusted_data->set_stress_deopt_counter_address(
        ExternalReference::stress_deopt_count(isolate).address());
    for (int i = 0; i < num_memories; ++i) {
      memory_bases_and_sizes->set(
          2 * i, reinterpret_cast<Address>(empty_backing_store_buffer));
      memory_bases_and_sizes->set(2 * i + 1, 0);
    }
  }
  // Allocate the exports object, to be store in the instance object.
  DirectHandle<JSObject> exports_object =
      isolate->factory()->NewJSObjectWithNullProto();
  DirectHandle<WasmInstanceObject> instance_object;
  if (!shared) {
    // Allocate the WasmInstanceObject (JS wrapper).
    DirectHandle<JSFunction> instance_cons(
        isolate->native_context()->wasm_instance_constructor(), isolate);
    instance_object = Cast<WasmInstanceObject>(
        isolate->factory()->NewJSObject(instance_cons, AllocationType::kOld));
    instance_object->set_trusted_data(*trusted_data);
    instance_object->set_module_object(*module_object);
    instance_object->set_exports_object(*exports_object);
    trusted_data->set_instance_object(*instance_object);
  }
  // Insert the new instance into the scripts weak list of instances. This list
  // is used for breakpoints affecting all instances belonging to the script.
  if (module_object->script()->type() == Script::Type::kWasm &&
      !instance_object.is_null()) {
    DirectHandle<WeakArrayList> weak_instance_list(
        module_object->script()->wasm_weak_instance_list(), isolate);
    weak_instance_list =
        WeakArrayList::Append(isolate, weak_instance_list,
                              MaybeObjectDirectHandle::Weak(instance_object));
    module_object->script()->set_wasm_weak_instance_list(*weak_instance_list);
  }
  return trusted_data;
}
References v8::internal::WeakArrayList::Append(), v8::internal::data_segment_starts, v8::internal::Isolate::debug(), v8::internal::dispatch_table_for_imports, v8::internal::EmptyBackingStoreBuffer(), v8::internal::Isolate::factory(), v8::internal::TrustedManaged< CppType >::From(), v8::internal::func_refs, v8::internal::wasm::WasmModule::functions, v8::internal::Isolate::heap(), v8::internal::Debug::hook_on_function_call_address(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::instance_object, v8::internal::wasm::NativeModule::jump_table_start(), v8::internal::kMaxInt, v8::internal::kOld, v8::internal::kSharedOld, v8::internal::kSharedTrusted, v8::internal::kTrusted, v8::internal::wasm::kV8MaxWasmMemories, v8::internal::wasm::kWasmFuncRef, v8::internal::kYoung, v8::internal::wasm::WasmModule::memories, v8::internal::memory_objects, v8::internal::wasm::NativeModule::module(), module(), module_object(), v8::internal::Isolate::native_context(), native_module(), v8::internal::FixedIntegerArrayBase< T, Base >::New(), v8::internal::FixedAddressArrayBase< Base >::New(), v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::FactoryBase< Impl >::NewFixedArrayWithZeroes(), v8::internal::Factory::NewJSObject(), v8::internal::Factory::NewJSObjectWithNullProto(), v8::internal::Heap::NewSpaceAllocationLimitAddress(), v8::internal::Heap::NewSpaceAllocationTopAddress(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::wasm::WasmModule::num_declared_data_segments, v8::internal::wasm::WasmModule::num_imported_functions, v8::internal::wasm::WasmModule::num_imported_mutable_globals, v8::internal::Heap::OldSpaceAllocationLimitAddress(), v8::internal::Heap::OldSpaceAllocationTopAddress(), v8::internal::wasm::NativeModule::tiering_budget_array(), and v8::internal::MaybeObjectDirectHandle::Weak().
Referenced by v8::internal::wasm::InstanceBuilder::Build_Phase1().
OBJECT_CONSTRUCTORS()
v8::internal::WasmTrustedInstanceData::OBJECT_CONSTRUCTORS (WasmTrustedInstanceData , ExposedTrustedObject)
SetRawMemory()
void v8::internal::WasmTrustedInstanceData::SetRawMemory (int memory_index, uint8_t * mem_start, size_t mem_size)
Definition at line 1642 of file wasm-objects.cc.
                                                            {
  CHECK_LT(memory_index, module()->memories.size());
  CHECK_LE(mem_size, module()->memories[memory_index].is_memory64()
                         ? wasm::max_mem64_bytes()
                         : wasm::max_mem32_bytes());
  // All memory bases and sizes are stored in a TrustedFixedAddressArray.
  Tagged<TrustedFixedAddressArray> bases_and_sizes = memory_bases_and_sizes();
  bases_and_sizes->set(memory_index * 2, reinterpret_cast<Address>(mem_start));
  bases_and_sizes->set(memory_index * 2 + 1, mem_size);
  // Memory 0 has fast-access fields.
  if (memory_index == 0) {
    set_memory0_start(mem_start);
    set_memory0_size(mem_size);
  }
}
References CHECK_LE, CHECK_LT, v8::internal::wasm::max_mem32_bytes(), v8::internal::wasm::max_mem64_bytes(), and module().
try_get_func_ref()
bool v8::internal::WasmTrustedInstanceData::try_get_func_ref (int index, Tagged< WasmFuncRef > * result)
Definition at line 1987 of file wasm-objects.cc.
                                                                            {
  Tagged<Object> val = func_refs()->get(index);
  if (IsSmi(val)) return false;
  *result = Cast<WasmFuncRef>(val);
  return true;
}
References v8::internal::func_refs, v8::internal::index, v8::internal::TaggedImpl< HeapObjectReferenceType::STRONG, Address >::IsSmi(), and v8::base::internal::result.
Member Data Documentation
kProtectedFieldNames
constexpr std::array< const char *, 6 > v8::internal::WasmTrustedInstanceData::kProtectedFieldNames [static], [constexpr]
Initial value:
= {
      WASM_PROTECTED_INSTANCE_DATA_FIELDS(WASM_INSTANCE_FIELD_NAME)}
Definition at line 659 of file wasm-objects.h.
kProtectedFieldOffsets
constexpr std::array< uint16_t, 6 > v8::internal::WasmTrustedInstanceData::kProtectedFieldOffsets [static], [constexpr]
Initial value:
= {
      WASM_PROTECTED_INSTANCE_DATA_FIELDS(WASM_INSTANCE_FIELD_OFFSET)}
Definition at line 657 of file wasm-objects.h.
kTaggedFieldNames
constexpr std::array< const char *, WasmTrustedInstanceData::kTaggedFieldsCount > v8::internal::WasmTrustedInstanceData::kTaggedFieldNames [static], [constexpr]
Initial value:
= {
          WASM_TAGGED_INSTANCE_DATA_FIELDS(WASM_INSTANCE_FIELD_NAME)}
Definition at line 655 of file wasm-objects.h.
kTaggedFieldOffsets
constexpr std::array< uint16_t, WasmTrustedInstanceData::kTaggedFieldsCount > v8::internal::WasmTrustedInstanceData::kTaggedFieldOffsets [static], [constexpr]
Initial value:
= {
          WASM_TAGGED_INSTANCE_DATA_FIELDS(WASM_INSTANCE_FIELD_OFFSET)}
Definition at line 652 of file wasm-objects.h.
kTaggedFieldsCount
constexpr size_t v8::internal::WasmTrustedInstanceData::kTaggedFieldsCount [static], [constexpr]
Initial value:
=
      16 + kWasmInterpreterAdditionalFields
Definition at line 648 of file wasm-objects.h.
kWasmInterpreterAdditionalFields
constexpr size_t v8::internal::WasmTrustedInstanceData::kWasmInterpreterAdditionalFields = 0 [static], [constexpr]
Definition at line 646 of file wasm-objects.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-objects.h
/mnt/V8SourceCode/src/wasm/wasm-objects-inl.h
/mnt/V8SourceCode/src/wasm/wasm-objects.cc