v8::internal::maglev::CallWithArrayLike Class Reference
#include <maglev-ir.h>
Public Member Functions
CallWithArrayLike (uint64_t bitfield)
Input & function ()
Input & receiver ()
Input & arguments_list ()
Input & context ()
void VerifyInputs (MaglevGraphLabeller *graph_labeller) const
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr int kFunctionIndex = 0
static constexpr int kReceiverIndex = 1
static constexpr int kArgumentsListIndex = 2
static constexpr int kContextIndex = 3
static constexpr OpProperties kProperties = OpProperties::JSCall()
static constexpr Base::InputTypes kInputTypes
Private Types
using Base = FixedInputValueNodeT< 4, CallWithArrayLike >
Additional Inherited Members
Detailed Description
Definition at line 10436 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::CallWithArrayLike::Base = FixedInputValueNodeT<4, CallWithArrayLike> [private]
Definition at line 10437 of file maglev-ir.h.
Constructor & Destructor Documentation
CallWithArrayLike()
v8::internal::maglev::CallWithArrayLike::CallWithArrayLike (uint64_t bitfield) [inline], [explicit]
Definition at line 10448 of file maglev-ir.h.
: Base(bitfield) {}
Member Function Documentation
arguments_list()
Input& v8::internal::maglev::CallWithArrayLike::arguments_list () [inline]
Definition at line 10457 of file maglev-ir.h.
{ return input(kArgumentsListIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
context()
Input& v8::internal::maglev::CallWithArrayLike::context () [inline]
Definition at line 10458 of file maglev-ir.h.
{ return input(kContextIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
function()
Input& v8::internal::maglev::CallWithArrayLike::function () [inline]
Definition at line 10455 of file maglev-ir.h.
{ return input(kFunctionIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::CallWithArrayLike::GenerateCode (MaglevAssembler * , const ProcessingState &)
MaxCallStackArgs()
int v8::internal::maglev::CallWithArrayLike::MaxCallStackArgs () const
PrintParams()
void v8::internal::maglev::CallWithArrayLike::PrintParams (std::ostream & , MaglevGraphLabeller *) const [inline]
Definition at line 10467 of file maglev-ir.h.
{}
receiver()
Input& v8::internal::maglev::CallWithArrayLike::receiver () [inline]
Definition at line 10456 of file maglev-ir.h.
{ return input(kReceiverIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
SetValueLocationConstraints()
void v8::internal::maglev::CallWithArrayLike::SetValueLocationConstraints ()
VerifyInputs()
void v8::internal::maglev::CallWithArrayLike::VerifyInputs (MaglevGraphLabeller * graph_labeller) const
Definition at line 950 of file maglev-ir.cc.
                                               {
  for (int i = 0; i < input_count(); i++) {
    CheckValueInputIs(this, i, ValueRepresentation::kTagged, graph_labeller);
  }
}
References v8::internal::maglev::CheckValueInputIs(), v8::internal::maglev::FixedInputNodeTMixin< InputCount, Base, Derived >::input_count(), and v8::internal::maglev::kTagged.
Member Data Documentation
kArgumentsListIndex
constexpr int v8::internal::maglev::CallWithArrayLike::kArgumentsListIndex = 2 [static], [constexpr]
Definition at line 10443 of file maglev-ir.h.
kContextIndex
constexpr int v8::internal::maglev::CallWithArrayLike::kContextIndex = 3 [static], [constexpr]
Definition at line 10444 of file maglev-ir.h.
kFunctionIndex
constexpr int v8::internal::maglev::CallWithArrayLike::kFunctionIndex = 0 [static], [constexpr]
Definition at line 10441 of file maglev-ir.h.
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::CallWithArrayLike::kInputTypes [static], [constexpr]
Initial value:
{
      ValueRepresentation::kTagged, ValueRepresentation::kTagged,
      ValueRepresentation::kTagged, ValueRepresentation::kTagged}
Definition at line 10451 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::CallWithArrayLike::kProperties = OpProperties::JSCall() [static], [constexpr]
Definition at line 10450 of file maglev-ir.h.
kReceiverIndex
constexpr int v8::internal::maglev::CallWithArrayLike::kReceiverIndex = 1 [static], [constexpr]
Definition at line 10442 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc