v8::internal::maglev::Abort Class Reference
#include <maglev-ir.h>
Public Member Functions
Abort (uint64_t bitfield, AbortReason reason)
AbortReason reason () const
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties = OpProperties::Call()
Private Types
using Base = TerminalControlNodeT< 0, Abort >
Private Attributes
const AbortReason reason_
Additional Inherited Members
Detailed Description
Definition at line 11356 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::Abort::Base = TerminalControlNodeT<0, Abort> [private]
Definition at line 11357 of file maglev-ir.h.
Constructor & Destructor Documentation
Abort()
v8::internal::maglev::Abort::Abort (uint64_t bitfield, AbortReason reason) [inline], [explicit]
Definition at line 11360 of file maglev-ir.h.
      : Base(bitfield), reason_(reason) {
    DCHECK_EQ(NodeBase::opcode(), opcode_of<Abort>);
  }
References DCHECK_EQ.
Member Function Documentation
GenerateCode()
void v8::internal::maglev::Abort::GenerateCode (MaglevAssembler * , const ProcessingState &)
MaxCallStackArgs()
int v8::internal::maglev::Abort::MaxCallStackArgs () const
PrintParams()
void v8::internal::maglev::Abort::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8007 of file maglev-ir.cc.
                                                                   {
  os << "(" << GetAbortReason(reason()) << ")";
}
References v8::internal::GetAbortReason(), and reason().
reason()
AbortReason v8::internal::maglev::Abort::reason () const [inline]
Definition at line 11367 of file maglev-ir.h.
{ return reason_; }
Referenced by PrintParams().
SetValueLocationConstraints()
void v8::internal::maglev::Abort::SetValueLocationConstraints ()
Member Data Documentation
kProperties
constexpr OpProperties v8::internal::maglev::Abort::kProperties = OpProperties::Call() [static], [constexpr]
Definition at line 11365 of file maglev-ir.h.
reason_
const AbortReason v8::internal::maglev::Abort::reason_ [private]
Definition at line 11375 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc