v8::internal::compiler::JSCallReducerAssembler::ForBuilder1 Class Reference
Public Member Functions
ForBuilder1 (JSGraphAssembler *gasm, TNode< Number > initial_value, const ConditionFunction1 &cond, const StepFunction1 &step, TNode< Object > initial_arg0)
V8_WARN_UNUSED_RESULT ForBuilder1 & Do (const For1BodyFunction &body)
V8_WARN_UNUSED_RESULT TNode< Object > Value ()
void ValueIsUnused ()
Private Attributes
JSGraphAssembler *const gasm_
const TNode< Number > initial_value_
const ConditionFunction1 cond_
const StepFunction1 step_
For1BodyFunction body_
const TNode< Object > initial_arg0_
Static Private Attributes
static constexpr MachineRepresentation kPhiRepresentation
Detailed Description
Definition at line 298 of file js-call-reducer.cc.
Constructor & Destructor Documentation
ForBuilder1()
v8::internal::compiler::JSCallReducerAssembler::ForBuilder1::ForBuilder1 (JSGraphAssembler * gasm, TNode< Number > initial_value, const ConditionFunction1 & cond, const StepFunction1 & step, TNode< Object > initial_arg0) [inline]
Definition at line 300 of file js-call-reducer.cc.
        : gasm_(gasm),
          initial_value_(initial_value),
          cond_(cond),
          step_(step),
          initial_arg0_(initial_arg0) {}
Member Function Documentation
Do()
V8_WARN_UNUSED_RESULT ForBuilder1& v8::internal::compiler::JSCallReducerAssembler::ForBuilder1::Do (const For1BodyFunction & body) [inline]
Definition at line 309 of file js-call-reducer.cc.
                                                                        {
      body_ = body;
      return *this;
    }
References body_.
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFilter(), and v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeReduce().
Value()
V8_WARN_UNUSED_RESULT TNode<Object> v8::internal::compiler::JSCallReducerAssembler::ForBuilder1::Value () [inline]
Definition at line 314 of file js-call-reducer.cc.
                                                {
      DCHECK(body_);
      TNode<Object> arg0 = initial_arg0_;
      auto loop_exit = gasm_->MakeDeferredLabel(kPhiRepresentation);
      {
        GraphAssembler::LoopScope<kPhiRepresentation, kPhiRepresentation>
            loop_scope(gasm_);
        auto loop_header = loop_scope.loop_header_label();
        auto loop_body = gasm_->MakeDeferredLabel(kPhiRepresentation);
        gasm_->Goto(loop_header, initial_value_, initial_arg0_);
        gasm_->Bind(loop_header);
        TNode<Number> i = loop_header->PhiAt<Number>(0);
        arg0 = loop_header->PhiAt<Object>(1);
        gasm_->BranchWithHint(cond_(i), &loop_body, &loop_exit,
                              BranchHint::kTrue, arg0);
        gasm_->Bind(&loop_body);
        body_(i, &arg0);
        gasm_->Goto(loop_header, step_(i), arg0);
      }
      gasm_->Bind(&loop_exit);
      return TNode<Object>::UncheckedCast(loop_exit.PhiAt<Object>(0));
    }
References v8::internal::compiler::GraphAssembler::Bind(), body_, v8::internal::compiler::GraphAssembler::BranchWithHint(), cond_, v8::internal::DCHECK(), gasm_, v8::internal::compiler::GraphAssembler::Goto(), initial_arg0_, initial_value_, kPhiRepresentation, v8::internal::kTrue, v8::internal::compiler::GraphAssembler::LoopScope< Reps >::loop_header_label(), v8::internal::compiler::GraphAssembler::MakeDeferredLabel(), step_, and v8::internal::TNode< T >::UncheckedCast().
Referenced by ValueIsUnused().
ValueIsUnused()
void v8::internal::compiler::JSCallReducerAssembler::ForBuilder1::ValueIsUnused () [inline]
Definition at line 345 of file js-call-reducer.cc.
{ USE(Value()); }
References USE, and Value().
Member Data Documentation
body_
For1BodyFunction v8::internal::compiler::JSCallReducerAssembler::ForBuilder1::body_ [private]
Definition at line 355 of file js-call-reducer.cc.
Referenced by Do(), and Value().
cond_
const ConditionFunction1 v8::internal::compiler::JSCallReducerAssembler::ForBuilder1::cond_ [private]
Definition at line 353 of file js-call-reducer.cc.
Referenced by Value().
gasm_
JSGraphAssembler* const v8::internal::compiler::JSCallReducerAssembler::ForBuilder1::gasm_ [private]
Definition at line 351 of file js-call-reducer.cc.
Referenced by Value().
initial_arg0_
const TNode<Object> v8::internal::compiler::JSCallReducerAssembler::ForBuilder1::initial_arg0_ [private]
Definition at line 356 of file js-call-reducer.cc.
Referenced by Value().
initial_value_
const TNode<Number> v8::internal::compiler::JSCallReducerAssembler::ForBuilder1::initial_value_ [private]
Definition at line 352 of file js-call-reducer.cc.
Referenced by Value().
kPhiRepresentation
constexpr MachineRepresentation v8::internal::compiler::JSCallReducerAssembler::ForBuilder1::kPhiRepresentation [static], [constexpr], [private]
Initial value:
=
        MachineRepresentation::kTagged
Definition at line 348 of file js-call-reducer.cc.
Referenced by Value().
step_
const StepFunction1 v8::internal::compiler::JSCallReducerAssembler::ForBuilder1::step_ [private]
Definition at line 354 of file js-call-reducer.cc.
Referenced by Value().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-call-reducer.cc