v8::internal::compiler::EscapeAnalysisTracker::Scope Class Reference
Public Member Functions
Scope (EffectGraphReducer *reducer, EscapeAnalysisTracker *tracker, Node *node, Reduction *reduction)
const VirtualObject * GetVirtualObject (Node *node)
const VirtualObject * InitVirtualObject (int size)
void SetVirtualObject (Node *object)
void SetEscaped (Node *node)
Node * ValueInput (int i)
Node * ContextInput ()
Node * CurrentNode ()
void SetReplacement (Node *replacement)
void MarkForDeletion ()
bool FrameStateMightLazyDeopt (Node *framestate)
~Scope ()
Private Attributes
EscapeAnalysisTracker * tracker_
EffectGraphReducer * reducer_
VirtualObject * vobject_ = nullptr
Node * replacement_ = nullptr
Additional Inherited Members
Detailed Description
Definition at line 180 of file escape-analysis.cc.
Constructor & Destructor Documentation
Scope()
v8::internal::compiler::EscapeAnalysisTracker::Scope::Scope (EffectGraphReducer * reducer, EscapeAnalysisTracker * tracker, Node * node, Reduction * reduction) [inline]
Definition at line 182 of file escape-analysis.cc.
        : VariableTracker::Scope(&tracker->variable_states_, node, reduction),
          tracker_(tracker),
          reducer_(reducer) {}
 Scope()
v8::internal::compiler::EscapeAnalysisTracker::Scope::~Scope () [inline]
Definition at line 275 of file escape-analysis.cc.
             {
      if (replacement_ != tracker_->replacements_[current_node()] ||
          vobject_ != tracker_->virtual_objects_.Get(current_node())) {
        reduction()->set_value_changed();
      }
      tracker_->replacements_[current_node()] = replacement_;
      tracker_->virtual_objects_.Set(current_node(), vobject_);
    }
Member Function Documentation
ContextInput()
Node* v8::internal::compiler::EscapeAnalysisTracker::Scope::ContextInput () [inline]
Definition at line 226 of file escape-analysis.cc.
                         {
      return tracker_->ResolveReplacement(
          NodeProperties::GetContextInput(current_node()));
    }
References v8::internal::compiler::NodeProperties::GetContextInput().
Referenced by v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode().
CurrentNode()
Node* v8::internal::compiler::EscapeAnalysisTracker::Scope::CurrentNode () [inline]
Definition at line 231 of file escape-analysis.cc.
                        {
      DCHECK_EQ(current_node()->opcode(), IrOpcode::kFrameState);
      return current_node();
    }
References DCHECK_EQ.
Referenced by v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode().
FrameStateMightLazyDeopt()
bool v8::internal::compiler::EscapeAnalysisTracker::Scope::FrameStateMightLazyDeopt (Node * framestate) [inline]
Definition at line 250 of file escape-analysis.cc.
                                                    {
      DCHECK_EQ(IrOpcode::kFrameState, framestate->opcode());
      if (auto it = tracker_->framestate_might_lazy_deopt_.find(framestate);
          it != tracker_->framestate_might_lazy_deopt_.end()) {
        return it->second;
      }
      for (Node* use : framestate->uses()) {
        switch (use->opcode()) {
          case IrOpcode::kCheckpoint:
          case IrOpcode::kDeoptimize:
          case IrOpcode::kDeoptimizeIf:
          case IrOpcode::kDeoptimizeUnless:
            // These nodes only cause eager deopts.
            break;
          default:
            if (use->opcode() == IrOpcode::kFrameState &&
                !FrameStateMightLazyDeopt(use)) {
              break;
            }
            return tracker_->framestate_might_lazy_deopt_[framestate] = true;
        }
      }
      return tracker_->framestate_might_lazy_deopt_[framestate] = false;
    }
References DCHECK_EQ, v8::internal::compiler::Node::opcode(), use(), and v8::internal::compiler::Node::uses().
Referenced by v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode().
GetVirtualObject()
const VirtualObject* v8::internal::compiler::EscapeAnalysisTracker::Scope::GetVirtualObject (Node * node) [inline]
Definition at line 187 of file escape-analysis.cc.
                                                      {
      VirtualObject* vobject = tracker_->virtual_objects_.Get(node);
      if (vobject) vobject->AddDependency(current_node());
      return vobject;
    }
References v8::internal::compiler::Dependable::AddDependency().
Referenced by v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::anonymous_namespace{escape-analysis.cc}::CheckMapsHelper(), and v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode().
InitVirtualObject()
const VirtualObject* v8::internal::compiler::EscapeAnalysisTracker::Scope::InitVirtualObject (int size) [inline]
Definition at line 193 of file escape-analysis.cc.
                                                     {
      DCHECK_EQ(IrOpcode::kAllocate, current_node()->opcode());
      VirtualObject* vobject = tracker_->virtual_objects_.Get(current_node());
      if (vobject) {
        CHECK(vobject->size() == size);
      } else {
        vobject = tracker_->NewVirtualObject(size);
      }
      if (vobject) vobject->AddDependency(current_node());
      vobject_ = vobject;
      return vobject;
    }
References v8::internal::compiler::Dependable::AddDependency(), CHECK, DCHECK_EQ, v8::internal::compiler::VirtualObject::size(), and size().
Referenced by v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode().
MarkForDeletion()
void v8::internal::compiler::EscapeAnalysisTracker::Scope::MarkForDeletion () [inline]
Definition at line 248 of file escape-analysis.cc.
{ SetReplacement(tracker_->jsgraph_->Dead()); }
Referenced by v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::anonymous_namespace{escape-analysis.cc}::CheckMapsHelper(), and v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode().
SetEscaped()
void v8::internal::compiler::EscapeAnalysisTracker::Scope::SetEscaped (Node * node) [inline]
Definition at line 210 of file escape-analysis.cc.
                                {
      if (VirtualObject* object = tracker_->virtual_objects_.Get(node)) {
        if (object->HasEscaped()) return;
        TRACE("Setting %s#%d to escaped because of use by %s#%d\n",
              node->op()->mnemonic(), node->id(),
              current_node()->op()->mnemonic(), current_node()->id());
        object->SetEscaped();
        object->RevisitDependants(reducer_);
      }
    }
References v8::internal::compiler::Node::id(), v8::internal::compiler::Operator::mnemonic(), v8::internal::compiler::Node::op(), and v8::internal::TRACE().
Referenced by v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode().
SetReplacement()
void v8::internal::compiler::EscapeAnalysisTracker::Scope::SetReplacement (Node * replacement) [inline]
Definition at line 236 of file escape-analysis.cc.
                                           {
      replacement_ = replacement;
      vobject_ =
          replacement ? tracker_->virtual_objects_.Get(replacement) : nullptr;
      if (replacement) {
        TRACE("Set %s#%d as replacement.\n", replacement->op()->mnemonic(),
              replacement->id());
      } else {
        TRACE("Set nullptr as replacement.\n");
      }
    }
References v8::internal::compiler::Node::id(), v8::internal::compiler::Operator::mnemonic(), v8::internal::compiler::Node::op(), and v8::internal::TRACE().
Referenced by v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode().
SetVirtualObject()
void v8::internal::compiler::EscapeAnalysisTracker::Scope::SetVirtualObject (Node * object) [inline]
Definition at line 206 of file escape-analysis.cc.
                                        {
      vobject_ = tracker_->virtual_objects_.Get(object);
    }
Referenced by v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode().
ValueInput()
Node* v8::internal::compiler::EscapeAnalysisTracker::Scope::ValueInput (int i) [inline]
Definition at line 222 of file escape-analysis.cc.
                            {
      return tracker_->ResolveReplacement(
          NodeProperties::GetValueInput(current_node(), i));
    }
References v8::internal::compiler::NodeProperties::GetValueInput().
Referenced by v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode().
Member Data Documentation
reducer_
EffectGraphReducer* v8::internal::compiler::EscapeAnalysisTracker::Scope::reducer_ [private]
Definition at line 286 of file escape-analysis.cc.
replacement_
Node* v8::internal::compiler::EscapeAnalysisTracker::Scope::replacement_ = nullptr [private]
Definition at line 288 of file escape-analysis.cc.
tracker_
EscapeAnalysisTracker* v8::internal::compiler::EscapeAnalysisTracker::Scope::tracker_ [private]
Definition at line 285 of file escape-analysis.cc.
vobject_
VirtualObject* v8::internal::compiler::EscapeAnalysisTracker::Scope::vobject_ = nullptr [private]
Definition at line 287 of file escape-analysis.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/escape-analysis.cc