v8::internal::Heap Class Reference
#include <heap.h>
Classes
struct Chunk
class DevToolsTraceEventScope
class ExternalMemoryAccounting
class ExternalStringTable
struct LimitsCompuatationResult
Public Types
enum class HeapGrowingMode { kSlow
, kConservative
, kMinimal
, kDefault
 }
enum HeapState {
NOT_IN_GC
, SCAVENGE
, MARK_COMPACT
, MINOR_MARK_SWEEP
,
TEAR_DOWN
 }
enum class StackScanMode { kNone
, kFull
, kSelective
 }
enum class OldGenerationExpansionNotificationOrigin { kFromClientHeap
, kFromSameHeap
 }
enum class IterateRootsMode { kMainIsolate
, kClientIsolate
 }
enum class SweepingForcedFinalizationMode { kUnifiedHeap
, kV8Only
 }
using Reservation = std::vector< Chunk >
using GetExternallyAllocatedMemoryInBytesCallback = v8::Isolate::GetExternallyAllocatedMemoryInBytesCallback
Public Member Functions
V8_EXPORT_PRIVATE void FatalProcessOutOfMemory (const char *location)
StackScanMode ConservativeStackScanningModeForMinorGC () const
StackScanMode ConservativeStackScanningModeForMajorGC () const
bool ShouldUsePrecisePinningForMinorGC () const
bool ShouldUsePrecisePinningForMajorGC () const
EphemeronRememberedSet * ephemeron_remembered_set ()
HeapProfiler * heap_profiler () const
void NotifyDeserializationComplete ()
void WeakenDescriptorArrays (GlobalHandleVector< DescriptorArray > strong_descriptor_arrays)
void NotifyBootstrapComplete ()
void NotifyOldGenerationExpansion (LocalHeap *local_heap, AllocationSpace space, MutablePageMetadata *chunk, OldGenerationExpansionNotificationOrigin=OldGenerationExpansionNotificationOrigin::kFromSameHeap)
Address * NewSpaceAllocationTopAddress ()
Address * NewSpaceAllocationLimitAddress ()
Address * OldSpaceAllocationTopAddress ()
Address * OldSpaceAllocationLimitAddress ()
size_t NewSpaceSize ()
size_t NewSpaceCapacity () const
size_t NewSpaceTargetCapacity () const
template<typename TSlot >
V8_EXPORT_PRIVATE void MoveRange (Tagged< HeapObject > dst_object, TSlot dst_slot, TSlot src_slot, int len, WriteBarrierMode mode)
template<typename TSlot >
V8_EXPORT_PRIVATE void CopyRange (Tagged< HeapObject > dst_object, TSlot dst_slot, TSlot src_slot, int len, WriteBarrierMode mode)
V8_EXPORT_PRIVATE void CreateFillerObjectAt (Address addr, int size, ClearFreedMemoryMode clear_memory_mode=ClearFreedMemoryMode::kDontClearFreedMemory)
void CreateFillerObjectAtBackground (const WritableFreeSpace &free_space)
bool CanMoveObjectStart (Tagged< HeapObject > object)
bool IsImmovable (Tagged< HeapObject > object)
V8_EXPORT_PRIVATE Tagged< FixedArrayBase > LeftTrimFixedArray (Tagged< FixedArrayBase > obj, int elements_to_trim)
template<typename Array >
void RightTrimArray (Tagged< Array > object, int new_capacity, int old_capacity)
Tagged< Boolean > ToBoolean (bool condition)
V8_EXPORT_PRIVATE int NotifyContextDisposed (bool has_dependent_context)
void set_native_contexts_list (Tagged< Object > object)
Tagged< Object > native_contexts_list () const
void set_allocation_sites_list (Tagged< UnionOf< Smi, Undefined, AllocationSiteWithWeakNext >> object)
Tagged< UnionOf< Smi, Undefined, AllocationSiteWithWeakNext > > allocation_sites_list ()
void set_dirty_js_finalization_registries_list (Tagged< Object > object)
Tagged< Object > dirty_js_finalization_registries_list ()
void set_dirty_js_finalization_registries_list_tail (Tagged< Object > object)
Tagged< Object > dirty_js_finalization_registries_list_tail ()
Address allocation_sites_list_address ()
void ForeachAllocationSite (Tagged< Object > list, const std::function< void(Tagged< AllocationSite >)> &visitor)
int ms_count () const
bool AllowedToBeMigrated (Tagged< Map > map, Tagged< HeapObject > object, AllocationSpace dest)
void CheckHandleCount ()
void PrintShortHeapStatistics ()
void PrintFreeListsStats ()
void DumpJSONHeapStatistics (std::stringstream &stream)
HeapState gc_state () const
V8_EXPORT_PRIVATE void SetGCState (HeapState state)
bool IsTearingDown () const
bool IsInGC () const
bool force_oom () const
bool ignore_local_gc_requests () const
bool IsAllocationObserverActive () const
bool IsGCWithMainThreadStack () const
bool IsGCWithStack () const
bool CanShortcutStringsDuringGC (GarbageCollector collector) const
void CollectGarbageForBackground (LocalHeap *local_heap)
void CreateReadOnlyApiObjects ()
void CreateMutableApiObjects ()
V8_EXPORT_PRIVATE void MemoryPressureNotification (v8::MemoryPressureLevel level, bool is_isolate_locked)
void CheckMemoryPressure ()
V8_EXPORT_PRIVATE void AddNearHeapLimitCallback (v8::NearHeapLimitCallback, void *data)
V8_EXPORT_PRIVATE void RemoveNearHeapLimitCallback (v8::NearHeapLimitCallback callback, size_t heap_limit)
V8_EXPORT_PRIVATE void AutomaticallyRestoreInitialHeapLimit (double threshold_percent)
V8_EXPORT_PRIVATE void AppendArrayBufferExtension (ArrayBufferExtension *extension)
V8_EXPORT_PRIVATE void ResizeArrayBufferExtension (ArrayBufferExtension *extension, int64_t delta)
void DetachArrayBufferExtension (ArrayBufferExtension *extension)
V8_EXPORT_PRIVATE void ExpandNewSpaceSizeForTesting ()
V8_EXPORT_PRIVATE void ReduceNewSpaceSizeForTesting ()
IsolateSafepoint * safepoint ()
V8_EXPORT_PRIVATE double MonotonicallyIncreasingTimeInMs () const
void RecordStats (HeapStats *stats)
bool MeasureMemory (std::unique_ptr< v8::MeasureMemoryDelegate > delegate, v8::MeasureMemoryExecution execution)
std::unique_ptr< v8::MeasureMemoryDelegate > CreateDefaultMeasureMemoryDelegate (v8::Local< v8::Context > context, v8::Local< v8::Promise::Resolver > promise, v8::MeasureMemoryMode mode)
void IncrementDeferredCounts (base::Vector< const v8::Isolate::UseCounterFeature > features)
int NextScriptId ()
int NextDebuggingId ()
int NextStackTraceId ()
uint32_t GetNextTemplateSerialNumber ()
void SetSerializedObjects (Tagged< HeapObject > objects)
void SetSerializedGlobalProxySizes (Tagged< FixedArray > sizes)
void SetBasicBlockProfilingData (DirectHandle< ArrayList > list)
void RememberUnmappedPage (Address page, bool compacted)
uint64_t external_memory_hard_limit ()
uint64_t external_memory () const
V8_EXPORT_PRIVATE uint64_t external_memory_limit_for_interrupt ()
V8_EXPORT_PRIVATE uint64_t external_memory_soft_limit ()
uint64_t UpdateExternalMemory (int64_t delta)
V8_EXPORT_PRIVATE size_t YoungArrayBufferBytes ()
V8_EXPORT_PRIVATE size_t OldArrayBufferBytes ()
uint64_t backing_store_bytes () const
void CompactWeakArrayLists ()
V8_EXPORT_PRIVATE void AddRetainedMaps (DirectHandle< NativeContext > context, GlobalHandleVector< Map > maps)
void OnMoveEvent (Tagged< HeapObject > source, Tagged< HeapObject > target, int size_in_bytes)
bool deserialization_complete () const
bool CanSafepoint () const
bool HasLowAllocationRate ()
bool HasHighFragmentation ()
void ActivateMemoryReducerIfNeeded ()
V8_EXPORT_PRIVATE bool ShouldOptimizeForMemoryUsage ()
V8_EXPORT_PRIVATE bool ShouldOptimizeForBattery () const
bool HighMemoryPressure ()
bool CollectionRequested ()
void CheckCollectionRequested ()
void RestoreHeapLimit (size_t heap_limit)
void ConfigureHeap (const v8::ResourceConstraints &constraints, v8::CppHeap *cpp_heap)
void ConfigureHeapDefault ()
void SetUp (LocalHeap *main_thread_local_heap)
void SetUpFromReadOnlyHeap (ReadOnlyHeap *ro_heap)
void ReplaceReadOnlySpace (SharedReadOnlySpace *shared_ro_space)
void SetUpSpaces (LinearAllocationArea &new_allocation_info, LinearAllocationArea &old_allocation_info)
void InitializeMainThreadLocalHeap (LocalHeap *main_thread_local_heap)
void InitializeHashSeed ()
bool CreateReadOnlyHeapObjects ()
bool CreateMutableHeapObjects ()
void CreateObjectStats ()
void StartTearDown ()
void TearDownWithSharedHeap ()
void TearDown ()
bool HasBeenSetUp () const
Address NewSpaceTop ()
Address NewSpaceLimit ()
NewSpace * new_space () const
PagedNewSpace * paged_new_space () const
SemiSpaceNewSpace * semi_space_new_space () const
OldSpace * old_space () const
StickySpace * sticky_space () const
CodeSpace * code_space () const
SharedSpace * shared_space () const
OldLargeObjectSpace * lo_space () const
CodeLargeObjectSpace * code_lo_space () const
SharedLargeObjectSpace * shared_lo_space () const
NewLargeObjectSpace * new_lo_space () const
ReadOnlySpace * read_only_space () const
TrustedSpace * trusted_space () const
SharedTrustedSpace * shared_trusted_space () const
TrustedLargeObjectSpace * trusted_lo_space () const
SharedTrustedLargeObjectSpace * shared_trusted_lo_space () const
PagedSpace * shared_allocation_space () const
OldLargeObjectSpace * shared_lo_allocation_space () const
SharedTrustedSpace * shared_trusted_allocation_space () const
SharedTrustedLargeObjectSpace * shared_trusted_lo_allocation_space () const
PagedSpace * paged_space (int idx) const
Space * space (int idx) const
GCTracer * tracer ()
const GCTracer * tracer () const
MemoryAllocator * memory_allocator ()
const MemoryAllocator * memory_allocator () const
Isolate * isolate () const
bool IsMainThread () const
MarkCompactCollector * mark_compact_collector ()
MinorMarkSweepCollector * minor_mark_sweep_collector ()
Sweeper * sweeper ()
ArrayBufferSweeper * array_buffer_sweeper ()
const base::AddressRegion & code_region ()
CodeRange * code_range ()
Address code_range_base ()
LocalHeap * main_thread_local_heap ()
Heap * AsHeap ()
RootsTable & roots_table ()
void SetRootMaterializedObjects (Tagged< FixedArray > objects)
void SetRootScriptList (Tagged< Object > value)
void SetRootNoScriptSharedFunctionInfos (Tagged< Object > value)
void SetMessageListeners (Tagged< ArrayList > value)
void SetFunctionsMarkedForManualOptimization (Tagged< Object > bytecode)
void SetSmiStringCache (Tagged< SmiStringCache > cache)
void SetDoubleStringCache (Tagged< DoubleStringCache > cache)
StrongRootsEntry * RegisterStrongRoots (const char *label, FullObjectSlot start, FullObjectSlot end)
void UnregisterStrongRoots (StrongRootsEntry *entry)
void UpdateStrongRoots (StrongRootsEntry *entry, FullObjectSlot start, FullObjectSlot end)
void SetBuiltinsConstantsTable (Tagged< FixedArray > cache)
void SetDetachedContexts (Tagged< WeakArrayList > detached_contexts)
void EnqueueDirtyJSFinalizationRegistry (Tagged< JSFinalizationRegistry > finalization_registry, std::function< void(Tagged< HeapObject > object, ObjectSlot slot, Tagged< Object > target)> gc_notify_updated_slot)
MaybeDirectHandle< JSFinalizationRegistry > DequeueDirtyJSFinalizationRegistry ()
void RemoveDirtyFinalizationRegistriesOnContext (Tagged< NativeContext > context)
bool HasDirtyJSFinalizationRegistries ()
void PostFinalizationRegistryCleanupTaskIfNeeded ()
void set_is_finalization_registry_cleanup_task_posted (bool posted)
bool is_finalization_registry_cleanup_task_posted ()
V8_EXPORT_PRIVATE void KeepDuringJob (DirectHandle< HeapObject > target)
void ClearKeptObjects ()
V8_EXPORT_PRIVATE void EnableInlineAllocation ()
V8_EXPORT_PRIVATE void DisableInlineAllocation ()
V8_EXPORT_PRIVATE void CollectGarbage (AllocationSpace space, GarbageCollectionReason gc_reason, const GCCallbackFlags gc_callback_flags=kNoGCCallbackFlags, PerformHeapLimitCheck check_heap_limit_reached=PerformHeapLimitCheck::kYes)
V8_EXPORT_PRIVATE void CollectAllGarbage (GCFlags gc_flags, GarbageCollectionReason gc_reason, const GCCallbackFlags gc_callback_flags=kNoGCCallbackFlags)
V8_EXPORT_PRIVATE void CollectAllAvailableGarbage (GarbageCollectionReason gc_reason)
V8_EXPORT_PRIVATE void PreciseCollectAllGarbage (GCFlags gc_flags, GarbageCollectionReason gc_reason, const GCCallbackFlags gc_callback_flags=kNoGCCallbackFlags)
V8_EXPORT_PRIVATE bool CollectGarbageShared (LocalHeap *local_heap, GarbageCollectionReason gc_reason)
V8_EXPORT_PRIVATE bool CollectGarbageFromAnyThread (LocalHeap *local_heap, GarbageCollectionReason gc_reason=GarbageCollectionReason::kBackgroundAllocationFailure)
V8_EXPORT_PRIVATE void CollectGarbageWithRetry (AllocationSpace space, GCFlags gc_flags, GarbageCollectionReason gc_reason, const GCCallbackFlags gc_callback_flags)
void HandleExternalMemoryInterrupt ()
void SetGetExternallyAllocatedMemoryInBytesCallback (GetExternallyAllocatedMemoryInBytesCallback callback)
void HandleGCRequest ()
void IterateRoots (RootVisitor *v, base::EnumSet< SkipRoot > options, IterateRootsMode roots_mode=IterateRootsMode::kMainIsolate)
void IterateRootsIncludingClients (RootVisitor *v, base::EnumSet< SkipRoot > options)
void IterateSmiRoots (RootVisitor *v)
void IterateWeakRoots (RootVisitor *v, base::EnumSet< SkipRoot > options)
void IterateWeakGlobalHandles (RootVisitor *v)
void IterateBuiltins (RootVisitor *v)
void IterateStackRoots (RootVisitor *v)
void IterateConservativeStackRoots (RootVisitor *root_visitor, IterateRootsMode roots_mode=IterateRootsMode::kMainIsolate)
void IterateConservativeStackRoots (::heap::base::StackVisitor *stack_visitor, StackScanMode stack_scan_mode)
void IterateRootsForPrecisePinning (RootVisitor *visitor)
uint8_t * IsMarkingFlagAddress ()
uint8_t * IsMinorMarkingFlagAddress ()
void ClearRecordedSlotRange (Address start, Address end)
GCFlags GCFlagsForIncrementalMarking ()
V8_EXPORT_PRIVATE void StartIncrementalMarking (GCFlags gc_flags, GarbageCollectionReason gc_reason, GCCallbackFlags gc_callback_flags=GCCallbackFlags::kNoGCCallbackFlags, GarbageCollector collector=GarbageCollector::MARK_COMPACTOR)
V8_EXPORT_PRIVATE void StartIncrementalMarkingOnInterrupt ()
V8_EXPORT_PRIVATE void StartIncrementalMarkingIfAllocationLimitIsReached (LocalHeap *local_heap, GCFlags gc_flags, GCCallbackFlags gc_callback_flags=GCCallbackFlags::kNoGCCallbackFlags)
V8_EXPORT_PRIVATE void FinalizeIncrementalMarkingAtomically (GarbageCollectionReason gc_reason)
V8_EXPORT_PRIVATE void FinalizeIncrementalMarkingAtomicallyIfRunning (GarbageCollectionReason gc_reason)
V8_EXPORT_PRIVATE void CompleteSweepingFull ()
void CompleteSweepingYoung ()
void EnsureSweepingCompletedForObject (Tagged< HeapObject > object)
IncrementalMarking * incremental_marking () const
ConcurrentMarking * concurrent_marking () const
void NotifyObjectLayoutChange (Tagged< HeapObject > object, const DisallowGarbageCollection &, InvalidateRecordedSlots invalidate_recorded_slots, InvalidateExternalPointerSlots invalidate_external_pointer_slots, int new_size=0)
void NotifyObjectSizeChange (Tagged< HeapObject >, int old_size, int new_size, ClearRecordedSlots clear_recorded_slots)
void SetConstructStubCreateDeoptPCOffset (int pc_offset)
void SetConstructStubInvokeDeoptPCOffset (int pc_offset)
void SetDeoptPCOffsetAfterAdaptShadowStack (int pc_offset)
void SetInterpreterEntryReturnPCOffset (int pc_offset)
void DeoptMarkedAllocationSites ()
v8::CppHeap * cpp_heap () const
std::optional< StackState > overridden_stack_state () const
V8_EXPORT_PRIVATE void SetStackStart ()
V8_EXPORT_PRIVATE ::heap::base::Stack & stack ()
V8_EXPORT_PRIVATEconst ::heap::base::Stack & stack () const
V8_EXPORT_PRIVATE void SetEmbedderRootsHandler (EmbedderRootsHandler *handler)
EmbedderRootsHandler * GetEmbedderRootsHandler () const
void RegisterExternalString (Tagged< String > string)
V8_EXPORT_PRIVATE void UpdateExternalString (Tagged< String > string, size_t old_payload, size_t new_payload)
void FinalizeExternalString (Tagged< String > string)
bool InOldSpace (Tagged< Object > object)
V8_EXPORT_PRIVATE bool Contains (Tagged< HeapObject > value) const
V8_EXPORT_PRIVATE bool ContainsCode (Tagged< HeapObject > value) const
V8_EXPORT_PRIVATE bool SharedHeapContains (Tagged< HeapObject > value) const
V8_EXPORT_PRIVATE bool MustBeInSharedOldSpace (Tagged< HeapObject > value)
V8_EXPORT_PRIVATE bool InSpace (Tagged< HeapObject > value, AllocationSpace space) const
V8_EXPORT_PRIVATE bool InSpaceSlow (Address addr, AllocationSpace space) const
V8_EXPORT_PRIVATE bool CanReferenceHeapObject (Tagged< HeapObject > obj)
size_t NumberOfTrackedHeapObjectTypes ()
size_t ObjectCountAtLastGC (size_t index)
size_t ObjectSizeAtLastGC (size_t index)
bool GetObjectTypeName (size_t index, const char **object_type, const char **object_sub_type)
size_t NumberOfNativeContexts ()
size_t NumberOfDetachedContexts ()
void CollectCodeStatistics ()
V8_EXPORT_PRIVATE size_t MaxReserved () const
size_t MaxSemiSpaceSize ()
size_t InitialSemiSpaceSize ()
size_t MaxOldGenerationSize ()
size_t Capacity ()
V8_EXPORT_PRIVATE size_t OldGenerationCapacity () const
base::Mutex * heap_expansion_mutex ()
size_t CommittedMemory ()
size_t CommittedOldGenerationMemory ()
size_t CommittedMemoryExecutable ()
size_t CommittedPhysicalMemory ()
size_t MaximumCommittedMemory ()
void UpdateMaximumCommitted ()
size_t Available ()
V8_EXPORT_PRIVATE size_t SizeOfObjects ()
V8_EXPORT_PRIVATE size_t TotalGlobalHandlesSize ()
V8_EXPORT_PRIVATE size_t UsedGlobalHandlesSize ()
void UpdateSurvivalStatistics (int start_new_space_size)
void IncrementPromotedObjectsSize (size_t object_size)
size_t promoted_objects_size ()
void IncrementNewSpaceSurvivingObjectSize (size_t object_size)
size_t new_space_surviving_object_size ()
size_t SurvivedYoungObjectSize ()
void IncrementNodesDiedInNewSpace (int count)
void IncrementNodesCopiedInNewSpace ()
void IncrementNodesPromoted ()
void IncrementYoungSurvivorsCounter (size_t survived)
V8_EXPORT_PRIVATE size_t NewSpaceAllocationCounter () const
void SetNewSpaceAllocationCounterForTesting (size_t new_value)
void UpdateOldGenerationAllocationCounter ()
size_t OldGenerationAllocationCounter ()
size_t EmbedderAllocationCounter () const
void set_old_generation_allocation_counter_at_last_gc (size_t new_value)
int gc_count () const
bool is_current_gc_forced () const
GarbageCollector current_or_last_garbage_collector () const
bool ShouldCurrentGCKeepAgesUnchanged () const
V8_EXPORT_PRIVATE size_t OldGenerationSizeOfObjects () const
V8_EXPORT_PRIVATE size_t OldGenerationWastedBytes () const
V8_EXPORT_PRIVATE size_t OldGenerationConsumedBytes () const
V8_EXPORT_PRIVATE size_t YoungGenerationSizeOfObjects () const
V8_EXPORT_PRIVATE size_t YoungGenerationWastedBytes () const
V8_EXPORT_PRIVATE size_t YoungGenerationConsumedBytes () const
V8_EXPORT_PRIVATE size_t EmbedderSizeOfObjects () const
V8_EXPORT_PRIVATE size_t GlobalSizeOfObjects () const
V8_EXPORT_PRIVATE size_t GlobalWastedBytes () const
V8_EXPORT_PRIVATE size_t GlobalConsumedBytes () const
V8_EXPORT_PRIVATE size_t OldGenerationConsumedBytesAtLastGC () const
V8_EXPORT_PRIVATE size_t GlobalConsumedBytesAtLastGC () const
bool AllocationLimitOvershotByLargeMargin () const
V8_EXPORT_PRIVATE int MaxRegularHeapObjectSize (AllocationType allocation)
void AddGCPrologueCallback (v8::Isolate::GCCallbackWithData callback, GCType gc_type_filter, void *data)
void RemoveGCPrologueCallback (v8::Isolate::GCCallbackWithData callback, void *data)
void AddGCEpilogueCallback (v8::Isolate::GCCallbackWithData callback, GCType gc_type_filter, void *data)
void RemoveGCEpilogueCallback (v8::Isolate::GCCallbackWithData callback, void *data)
void CallGCPrologueCallbacks (GCType gc_type, GCCallbackFlags flags, GCTracer::Scope::ScopeId scope_id)
void CallGCEpilogueCallbacks (GCType gc_type, GCCallbackFlags flags, GCTracer::Scope::ScopeId scope_id)
V8_EXPORT_PRIVATE Tagged< HeapObject > PrecedeWithFiller (Tagged< HeapObject > object, int filler_size)
V8_EXPORT_PRIVATE Tagged< HeapObject > PrecedeWithFillerBackground (Tagged< HeapObject > object, int filler_size)
V8_WARN_UNUSED_RESULT Tagged< HeapObject > AlignWithFillerBackground (Tagged< HeapObject > object, int object_size, int allocation_size, AllocationAlignment alignment)
V8_EXPORT_PRIVATE void * AllocateExternalBackingStore (const std::function< void *(size_t)> &allocate, size_t byte_length)
void AddAllocationObserversToAllSpaces (AllocationObserver *observer, AllocationObserver *new_space_observer)
void RemoveAllocationObserversFromAllSpaces (AllocationObserver *observer, AllocationObserver *new_space_observer)
bool IsPendingAllocation (Tagged< HeapObject > object)
bool IsPendingAllocation (Tagged< Object > object)
V8_EXPORT_PRIVATE void PublishMainThreadPendingAllocations ()
V8_EXPORT_PRIVATE void AddHeapObjectAllocationTracker (HeapObjectAllocationTracker *tracker)
V8_EXPORT_PRIVATE void RemoveHeapObjectAllocationTracker (HeapObjectAllocationTracker *tracker)
bool has_heap_object_allocation_tracker () const
V8_EXPORT_PRIVATE Tagged< Code > FindCodeForInnerPointer (Address inner_pointer)
Tagged< GcSafeCode > GcSafeFindCodeForInnerPointer (Address inner_pointer)
std::optional< Tagged< GcSafeCode > > GcSafeTryFindCodeForInnerPointer (Address inner_pointer)
std::optional< Tagged< InstructionStream > > GcSafeTryFindInstructionStreamForInnerPointer (Address inner_pointer)
std::optional< Tagged< Code > > TryFindCodeForInnerPointerForPrinting (Address inner_pointer)
bool GcSafeInstructionStreamContains (Tagged< InstructionStream > instruction_stream, Address addr)
bool sweeping_in_progress () const
bool sweeping_in_progress_for_space (AllocationSpace space) const
bool minor_sweeping_in_progress () const
bool major_sweeping_in_progress () const
void FinishSweepingIfOutOfWork ()
V8_EXPORT_PRIVATE void EnsureSweepingCompleted (SweepingForcedFinalizationMode mode)
void EnsureYoungSweepingCompleted ()
void EnsureQuarantinedPagesSweepingCompleted ()
void * GetRandomMmapAddr ()
V8_EXPORT_PRIVATE void MakeHeapIterable ()
V8_EXPORT_PRIVATE void Unmark ()
V8_EXPORT_PRIVATE void DeactivateMajorGCInProgressFlag ()
V8_EXPORT_PRIVATE void FreeLinearAllocationAreas ()
V8_EXPORT_PRIVATE void FreeMainThreadLinearAllocationAreas ()
V8_EXPORT_PRIVATE bool CanPromoteYoungAndExpandOldGeneration (size_t size) const
V8_EXPORT_PRIVATE bool CanExpandOldGeneration (size_t size) const
V8_EXPORT_PRIVATE bool IsOldGenerationExpansionAllowed (size_t size, const base::MutexGuard &expansion_mutex_witness) const
bool ShouldReduceMemory () const
bool IsLastResortGC ()
MarkingState * marking_state ()
NonAtomicMarkingState * non_atomic_marking_state ()
PretenuringHandler * pretenuring_handler ()
bool IsInlineAllocationEnabled () const
V8_EXPORT_PRIVATE uint64_t AllocatedExternalMemorySinceMarkCompact () const
std::shared_ptr< v8::TaskRunner > GetForegroundTaskRunner (TaskPriority priority=TaskPriority::kUserBlocking) const
bool ShouldUseBackgroundThreads () const
bool ShouldUseIncrementalMarking () const
HeapAllocator * allocator ()
const HeapAllocator * allocator () const
bool use_new_space () const
bool IsNewSpaceAllowedToGrowAboveTargetCapacity () const
template<typename TSlot >
void MoveRange (Tagged< HeapObject > dst_object, const TSlot dst_slot, const TSlot src_slot, int len, WriteBarrierMode mode)
template<typename TSlot >
void CopyRange (Tagged< HeapObject > dst_object, const TSlot dst_slot, const TSlot src_slot, int len, WriteBarrierMode mode)
Static Public Member Functions
static V8_EXPORT_PRIVATE size_t DefaultInitialOldGenerationSize ()
static V8_EXPORT_PRIVATE size_t OldGenerationLowMemory ()
static V8_EXPORT_PRIVATE size_t HeapLimitMultiplier ()
static size_t DefaultMinSemiSpaceSize ()
static V8_EXPORT_PRIVATE size_t DefaultMaxSemiSpaceSize ()
static size_t OldGenerationToSemiSpaceRatio ()
static size_t OldGenerationToSemiSpaceRatioLowMemory ()
static V8_EXPORT_PRIVATE size_t DefaulMinHeapSize ()
static V8_EXPORT_PRIVATE size_t DefaulMaxHeapSize ()
static V8_EXPORT_PRIVATE int GetMaximumFillToAlign (AllocationAlignment alignment)
static V8_EXPORT_PRIVATE int GetFillToAlign (Address address, AllocationAlignment alignment)
static size_t GetCodeRangeReservedAreaSize ()
static bool IsValidAllocationSpace (AllocationSpace space)
static bool IsYoungGenerationCollector (GarbageCollector collector)
static V8_EXPORT_PRIVATE bool IsFreeSpaceValid (const FreeSpace *object)
static GarbageCollector YoungGenerationCollector ()
static void CopyBlock (Address dst, Address src, int byte_size)
static V8_EXPORT_PRIVATE bool IsLargeObject (Tagged< HeapObject > object)
static void InitializeOncePerProcess ()
static int InsertIntoRememberedSetFromCode (MutablePageMetadata *chunk, size_t slot_offset)
static V8_EXPORT_PRIVATE void NotifyObjectLayoutChangeDone (Tagged< HeapObject > object)
static Tagged< String > UpdateYoungReferenceInExternalStringTableEntry (Heap *heap, FullObjectSlot pointer)
static bool InFromPage (Tagged< Object > object)
static bool InFromPage (Tagged< MaybeObject > object)
static bool InFromPage (Tagged< HeapObject > heap_object)
static bool InToPage (Tagged< Object > object)
static bool InToPage (Tagged< MaybeObject > object)
static bool InToPage (Tagged< HeapObject > heap_object)
static Heap * FromWritableHeapObject (Tagged< HeapObject > obj)
static V8_EXPORT_PRIVATE size_t AllocatorLimitOnMaxOldGenerationSize ()
static V8_EXPORT_PRIVATE size_t HeapSizeFromPhysicalMemory (uint64_t physical_memory)
static V8_EXPORT_PRIVATE void GenerationSizesFromHeapSize (size_t heap_size, size_t *young_generation_size, size_t *old_generation_size)
static V8_EXPORT_PRIVATE size_t YoungGenerationSizeFromOldGenerationSize (size_t old_generation_size)
static V8_EXPORT_PRIVATE size_t YoungGenerationSizeFromSemiSpaceSize (size_t semi_space_size)
static V8_EXPORT_PRIVATE size_t SemiSpaceSizeFromYoungGenerationSize (size_t young_generation_size)
static V8_EXPORT_PRIVATE size_t MinYoungGenerationSize ()
static V8_EXPORT_PRIVATE size_t MinOldGenerationSize ()
static V8_EXPORT_PRIVATE size_t MaxOldGenerationSizeFromPhysicalMemory (uint64_t physical_memory)
Static Public Attributes
static const int kPointerMultiplier = kTaggedSize / 4
static constexpr size_t kPhysicalMemoryToOldGenerationRatio = 4
static constexpr size_t kNewLargeObjectSpaceToSemiSpaceRatio = 1
static const int kTraceRingBufferSize = 512
static const int kStacktraceBufferSize = 512
static const int kMinObjectSizeInTaggedWords = 2
Private Types
enum class VerifyNoSlotsRecorded { kYes
, kNo
 }
enum class ResizeNewSpaceMode { kShrink
, kGrow
, kNone
 }
enum class IncrementalMarkingLimit { kNoLimit
, kSoftLimit
, kHardLimit
, kFallbackForEmbedderLimit
 }
enum AllocationRetryMode { kLightRetry
, kRetryOrFail
 }
using ExternalStringTableUpdaterCallback = Tagged< String >(*)(Heap *heap, FullObjectSlot pointer)
Private Member Functions
void AttachCppHeap (v8::CppHeap *cpp_heap)
Heap ()
~Heap ()
Heap (const Heap &)=delete
Heap & operator= (const Heap &)=delete
int NumberOfScavengeTasks ()
GarbageCollector SelectGarbageCollector (AllocationSpace space, GarbageCollectionReason gc_reason, const char **reason) const
void CheckHeapLimitReached ()
bool ReachedHeapLimit ()
void MakeLinearAllocationAreasIterable ()
void MarkSharedLinearAllocationAreasBlack ()
void UnmarkSharedLinearAllocationAreas ()
void FreeSharedLinearAllocationAreasAndResetFreeLists ()
void PerformGarbageCollection (GarbageCollector collector, GarbageCollectionReason gc_reason, const char *collector_reason)
void PerformHeapVerification ()
std::vector< Isolate * > PauseConcurrentThreadsInClients (GarbageCollector collector)
void ResumeConcurrentThreadsInClients (std::vector< Isolate * > paused_clients)
void StaticRootsEnsureAllocatedSize (DirectHandle< HeapObject > obj, int required)
bool CreateEarlyReadOnlyMapsAndObjects ()
bool CreateImportantReadOnlyObjects ()
bool CreateLateReadOnlyNonJSReceiverMaps ()
bool CreateLateReadOnlyJSReceiverMaps ()
bool CreateReadOnlyObjects ()
void CreateInternalAccessorInfoObjects ()
void CreateInitialMutableObjects ()
void CreateFillerObjectAtRaw (const WritableFreeSpace &free_space, ClearFreedMemoryMode clear_memory_mode, ClearRecordedSlots clear_slots_mode, VerifyNoSlotsRecorded verify_no_slots_recorded)
void ResetAllAllocationSitesDependentCode (AllocationType allocation)
void EvaluateOldSpaceLocalPretenuring (uint64_t size_of_objects_before_gc)
void ReportStatisticsAfterGC ()
void ActivateMemoryReducerIfNeededOnMainThread ()
void ShrinkOldGenerationAllocationLimitIfNotConfigured ()
void EnsureMinimumRemainingAllocationLimit (size_t at_least_remaining)
double ComputeMutatorUtilization (const char *tag, double mutator_speed, std::optional< double > gc_speed)
bool HasLowYoungGenerationAllocationRate ()
bool HasLowOldGenerationAllocationRate ()
bool HasLowEmbedderAllocationRate ()
ResizeNewSpaceMode ShouldResizeNewSpace ()
void StartResizeNewSpace ()
void ResizeNewSpace ()
void ExpandNewSpaceSize ()
void ReduceNewSpaceSize ()
void PrintMaxMarkingLimitReached ()
void PrintMaxNewSpaceSizeReached ()
int NextStressMarkingLimit ()
void AddToRingBuffer (const char *string)
void GetFromRingBuffer (char *buffer)
void CompactRetainedMaps (Tagged< WeakArrayList > retained_maps)
void CollectGarbageOnMemoryPressure ()
void EagerlyFreeExternalMemoryAndWasmCode ()
bool InvokeNearHeapLimitCallback ()
void InvokeIncrementalMarkingPrologueCallbacks ()
void InvokeIncrementalMarkingEpilogueCallbacks ()
Tagged< GcSafeCode > GcSafeGetCodeFromInstructionStream (Tagged< HeapObject > instruction_stream, Address inner_pointer)
Tagged< Map > GcSafeMapOfHeapObject (Tagged< HeapObject > object)
void GarbageCollectionPrologue (GarbageCollectionReason gc_reason, const v8::GCCallbackFlags gc_callback_flags)
void GarbageCollectionPrologueInSafepoint (GarbageCollector collector)
void GarbageCollectionEpilogue (GarbageCollector collector)
void GarbageCollectionEpilogueInSafepoint (GarbageCollector collector)
void MarkCompact ()
void MinorMarkSweep ()
void MarkCompactPrologue ()
void MarkCompactEpilogue ()
void Scavenge ()
void UpdateYoungReferencesInExternalStringTable (ExternalStringTableUpdaterCallback updater_func)
void UpdateReferencesInExternalStringTable (ExternalStringTableUpdaterCallback updater_func)
void ProcessAllWeakReferences (WeakObjectRetainer *retainer)
void ProcessNativeContexts (WeakObjectRetainer *retainer)
void ProcessAllocationSites (WeakObjectRetainer *retainer)
void ProcessDirtyJSFinalizationRegistries (WeakObjectRetainer *retainer)
void ProcessWeakListRoots (WeakObjectRetainer *retainer)
size_t OldGenerationSpaceAvailable ()
void UpdateTotalGCTime (base::TimeDelta duration)
bool IsIneffectiveMarkCompact (size_t old_generation_size, double mutator_utilization)
void CheckIneffectiveMarkCompact (size_t old_generation_size, double mutator_utilization)
void IncrementExternalBackingStoreBytes (ExternalBackingStoreType type, size_t amount)
void DecrementExternalBackingStoreBytes (ExternalBackingStoreType type, size_t amount)
MemoryReducer * memory_reducer ()
V8_EXPORT_PRIVATE bool ShouldOptimizeForLoadTime () const
void NotifyLoadingStarted ()
void NotifyLoadingEnded ()
size_t old_generation_allocation_limit () const
size_t global_allocation_limit () const
bool using_initial_limit () const
void set_using_initial_limit (bool value)
size_t max_old_generation_size () const
size_t min_old_generation_size () const
void SetOldGenerationAndGlobalMaximumSize (size_t max_old_generation_size)
void SetOldGenerationAndGlobalAllocationLimit (size_t new_old_generation_allocation_limit, size_t new_global_allocation_limit, const char *reason=__builtin_FUNCTION())
void ResetOldGenerationAndGlobalAllocationLimit ()
bool always_allocate () const
bool ShouldExpandOldGenerationOnSlowAllocation (LocalHeap *local_heap, AllocationOrigin origin)
bool ShouldExpandYoungGenerationOnSlowAllocation (size_t allocation_size)
HeapGrowingMode CurrentHeapGrowingMode ()
double PercentToOldGenerationLimit () const
double PercentToGlobalMemoryLimit () const
IncrementalMarkingLimit IncrementalMarkingLimitReached ()
bool ShouldStressCompaction () const
size_t GlobalMemoryAvailable ()
void RecomputeLimits (GarbageCollector collector, base::TimeTicks time)
void RecomputeLimitsAfterLoadingIfNeeded ()
V8_EXPORT_PRIVATE void StartMinorMSConcurrentMarkingIfNeeded ()
bool MinorMSSizeTaskTriggerReached () const
MinorGCJob * minor_gc_job ()
V8_WARN_UNUSED_RESULT AllocationResult AllocateMap (AllocationType allocation_type, InstanceType instance_type, int instance_size, ElementsKind elements_kind=TERMINAL_FAST_ELEMENTS_KIND, int inobject_properties=0)
V8_WARN_UNUSED_RESULT AllocationResult AllocateRaw (int size_in_bytes, AllocationType allocation, AllocationOrigin origin=AllocationOrigin::kRuntime, AllocationAlignment alignment=kTaggedAligned)
template<AllocationRetryMode mode>
V8_WARN_UNUSED_RESULT Tagged< HeapObject > AllocateRawWith (int size, AllocationType allocation, AllocationOrigin origin=AllocationOrigin::kRuntime, AllocationAlignment alignment=kTaggedAligned)
V8_WARN_UNUSED_RESULT Address AllocateRawOrFail (int size, AllocationType allocation, AllocationOrigin origin=AllocationOrigin::kRuntime, AllocationAlignment alignment=kTaggedAligned)
V8_WARN_UNUSED_RESULT AllocationResult Allocate (DirectHandle< Map > map, AllocationType allocation)
V8_WARN_UNUSED_RESULT AllocationResult AllocatePartialMap (InstanceType instance_type, int instance_size)
void FinalizePartialMap (Tagged< Map > map)
void set_force_oom (bool value)
void set_force_gc_on_next_allocation ()
bool IsPendingAllocationInternal (Tagged< HeapObject > object)
std::vector< Handle< NativeContext > > FindAllNativeContexts ()
std::vector< Tagged< WeakArrayList > > FindAllRetainedMaps ()
MemoryMeasurement * memory_measurement ()
AllocationType allocation_type_for_in_place_internalizable_strings () const
bool IsStressingScavenge ()
void SetIsMarkingFlag (bool value)
void SetIsMinorMarkingFlag (bool value)
size_t PromotedSinceLastGC ()
FRIEND_TEST (SpacesTest, InlineAllocationObserverCadence)
FRIEND_TEST (SpacesTest, AllocationObserver)
Static Private Member Functions
static bool IsRegularObjectAllocation (AllocationType allocation)
static LimitsCompuatationResult ComputeNewAllocationLimits (Heap *heap)
Private Attributes
ExternalMemoryAccounting external_memory_
Isolate * isolate_ = nullptr
HeapAllocator * heap_allocator_ = nullptr
size_t code_range_size_ = 0
size_t max_semi_space_size_ = 0
size_t min_semi_space_size_ = 0
size_t initial_semispace_size_ = 0
size_t min_old_generation_size_ = 0
std::atomic< size_t > max_old_generation_size_ {0}
size_t min_global_memory_size_ = 0
size_t max_global_memory_size_ = 0
size_t initial_max_old_generation_size_ = 0
size_t initial_max_old_generation_size_threshold_ = 0
size_t initial_old_generation_size_ = 0
std::atomic< bool > using_initial_limit_ = true
bool initial_size_overwritten_ = false
bool preconfigured_old_generation_size_ = false
size_t maximum_committed_ = 0
size_t old_generation_capacity_after_bootstrap_ = 0
std::atomic< uint64_t > backing_store_bytes_ {0}
size_t survived_since_last_expansion_ = 0
std::atomic< size_t > always_allocate_scope_count_ {0}
std::atomic< v8::MemoryPressureLevel > memory_pressure_level_
std::vector< std::pair< v8::NearHeapLimitCallback, void * > > near_heap_limit_callbacks_
int contexts_disposed_ = 0
NewSpace * new_space_ = nullptr
OldSpace * old_space_ = nullptr
CodeSpace * code_space_ = nullptr
SharedSpace * shared_space_ = nullptr
OldLargeObjectSpace * lo_space_ = nullptr
CodeLargeObjectSpace * code_lo_space_ = nullptr
NewLargeObjectSpace * new_lo_space_ = nullptr
SharedLargeObjectSpace * shared_lo_space_ = nullptr
ReadOnlySpace * read_only_space_ = nullptr
TrustedSpace * trusted_space_ = nullptr
SharedTrustedSpace * shared_trusted_space_ = nullptr
TrustedLargeObjectSpace * trusted_lo_space_ = nullptr
SharedTrustedLargeObjectSpace * shared_trusted_lo_space_ = nullptr
PagedSpace * shared_allocation_space_ = nullptr
OldLargeObjectSpace * shared_lo_allocation_space_ = nullptr
SharedTrustedSpace * shared_trusted_allocation_space_ = nullptr
SharedTrustedLargeObjectSpace * shared_trusted_lo_allocation_space_ = nullptr
std::unique_ptr< Space > space_ [LAST_SPACE+1]
LocalHeap * main_thread_local_heap_ = nullptr
std::atomic< HeapState > gc_state_ {NOT_IN_GC}
int stress_marking_percentage_ = 0
StressScavengeObserver * stress_scavenge_observer_ = nullptr
std::atomic< double > max_marking_limit_reached_ = 0.0
unsigned int ms_count_ = 0
unsigned int gc_count_ = 0
int consecutive_ineffective_mark_compacts_ = 0
uintptr_t mmap_region_base_ = 0
int remembered_unmapped_pages_index_ = 0
Address remembered_unmapped_pages_ [kRememberedUnmappedPages]
std::atomic< size_t > old_generation_allocation_limit_ {0}
std::atomic< size_t > global_allocation_limit_ {0}
std::atomic< Address > native_contexts_list_
Tagged< UnionOf< Smi, Undefined, AllocationSiteWithWeakNext > > allocation_sites_list_ = Smi::zero()
Tagged< Object > dirty_js_finalization_registries_list_ = Smi::zero()
Tagged< Object > dirty_js_finalization_registries_list_tail_ = Smi::zero()
GCCallbacks gc_prologue_callbacks_
GCCallbacks gc_epilogue_callbacks_
GetExternallyAllocatedMemoryInBytesCallback external_memory_callback_
base::SmallVector< v8::Isolate::UseCounterFeature, 8 > deferred_counters_
size_t promoted_objects_size_ = 0
double promotion_ratio_ = 0.0
double promotion_rate_ = 0.0
size_t new_space_surviving_object_size_ = 0
size_t previous_new_space_surviving_object_size_ = 0
double new_space_surviving_rate_ = 0.0
int nodes_died_in_new_space_ = 0
int nodes_copied_in_new_space_ = 0
int nodes_promoted_ = 0
base::TimeDelta total_gc_time_ms_
double last_gc_time_ = 0.0
std::unique_ptr< GCTracer > tracer_
std::unique_ptr< Sweeper > sweeper_
std::unique_ptr< MarkCompactCollector > mark_compact_collector_
std::unique_ptr< MinorMarkSweepCollector > minor_mark_sweep_collector_
std::unique_ptr< ScavengerCollector > scavenger_collector_
std::unique_ptr< ArrayBufferSweeper > array_buffer_sweeper_
std::unique_ptr< MemoryAllocator > memory_allocator_
std::unique_ptr< IncrementalMarking > incremental_marking_
std::unique_ptr< ConcurrentMarking > concurrent_marking_
std::unique_ptr< MemoryMeasurement > memory_measurement_
std::unique_ptr< MemoryReducer > memory_reducer_
std::unique_ptr< ObjectStats > live_object_stats_
std::unique_ptr< ObjectStats > dead_object_stats_
std::unique_ptr< MinorGCJob > minor_gc_job_
std::unique_ptr< AllocationObserver > stress_concurrent_allocation_observer_
std::unique_ptr< AllocationTrackerForDebugging > allocation_tracker_for_debugging_
std::unique_ptr< EphemeronRememberedSet > ephemeron_remembered_set_
std::unique_ptr< HeapProfiler > heap_profiler_
std::shared_ptr< v8::TaskRunner > task_runner_
std::unique_ptr< CodeRange > code_range_
std::unique_ptr< CppHeap > owning_cpp_heap_
v8::CppHeap * cpp_heap_ = nullptr
EmbedderRootsHandler * embedder_roots_handler_
StackState embedder_stack_state_ = StackState::kMayContainHeapPointers
std::optional< EmbedderStackStateOrigin > embedder_stack_state_origin_
StrongRootsEntry * strong_roots_head_ = nullptr
base::Mutex strong_roots_mutex_
base::Mutex heap_expansion_mutex_
bool need_to_remove_stress_concurrent_allocation_observer_ = false
size_t new_space_allocation_counter_ = 0
size_t old_generation_allocation_counter_at_last_gc_ = 0
size_t old_generation_size_at_last_gc_ {0}
size_t old_generation_wasted_at_last_gc_ {0}
size_t embedder_size_at_last_gc_ = 0
char trace_ring_buffer_ [kTraceRingBufferSize]
bool ring_buffer_full_ = false
size_t ring_buffer_end_ = 0
bool configured_ = false
GCFlags current_gc_flags_ = GCFlag::kNoFlags
GCCallbackFlags current_gc_callback_flags_
std::unique_ptr< IsolateSafepoint > safepoint_
bool is_current_gc_forced_ = false
bool is_current_gc_for_heap_profiler_ = false
GarbageCollector current_or_last_garbage_collector_
ExternalStringTable external_string_table_
const AllocationType allocation_type_for_in_place_internalizable_strings_
std::unique_ptr< CollectionBarrier > collection_barrier_
int ignore_local_gc_requests_depth_ = 0
int gc_callbacks_depth_ = 0
bool deserialization_complete_ = false
int max_regular_code_object_size_ = 0
bool inline_allocation_enabled_ = true
int pause_allocation_observers_depth_ = 0
bool force_oom_ = false
bool force_gc_on_next_allocation_ = false
bool delay_sweeper_tasks_for_testing_ = false
std::vector< HeapObjectAllocationTracker * > allocation_trackers_
bool is_finalization_registry_cleanup_task_posted_ = false
MarkingState marking_state_
NonAtomicMarkingState non_atomic_marking_state_
PretenuringHandler pretenuring_handler_
ResizeNewSpaceMode resize_new_space_mode_ = ResizeNewSpaceMode::kNone
std::unique_ptr< MemoryBalancer > mb_
std::atomic< double > load_start_time_ms_ {kLoadTimeNotLoading}
bool update_allocation_limits_after_loading_ = false
bool is_full_gc_during_loading_ = false
std::optional< const void * > selective_stack_scan_start_address_
Static Private Attributes
static const int kInitialEvalCacheSize = 64
static const int kRememberedUnmappedPages = 128
static const int kYoungSurvivalRateHighThreshold = 90
static const int kYoungSurvivalRateAllowedDeviation = 15
static const int kOldSurvivalRateLowThreshold = 10
static const int kMaxMarkCompactsInIdleRound = 7
static constexpr int kRetainMapEntrySize = 2
static const int kMaxLoadTimeMs = 7000
static const uintptr_t kMmapRegionMask = 0xFFFFFFFFu
static constexpr double kLoadTimeNotLoading = -1.0
Friends
class ActivateMemoryReducerTask
class AlwaysAllocateScope
class ArrayBufferCollector
class ArrayBufferSweeper
class ConservativePinningScope
class ConcurrentMarking
class ConservativeTracedHandlesMarkingVisitor
class CppHeap
class EmbedderStackStateScope
class EvacuateVisitorBase
class GCCallbacksScope
class GCTracer
class HeapAllocator
class HeapObjectIterator
class HeapVerifier
class IgnoreLocalGCRequests
class IncrementalMarking
class IncrementalMarkingJob
class LargeObjectSpace
class LocalHeap
class MarkingBarrier
class OldLargeObjectSpace
template<typename ConcreteVisitor >
class MarkingVisitorBase
class MarkCompactCollector
class MemoryBalancer
class MinorGCJob
class MinorGCTaskObserver
class MinorMarkSweepCollector
class MinorMSIncrementalMarkingTaskObserver
class NewLargeObjectSpace
class NewSpace
class ObjectStatsCollector
class PageMetadata
class PagedNewSpaceAllocatorPolicy
class PagedSpaceAllocatorPolicy
class PagedSpaceBase
class PagedSpaceForNewSpace
class PauseAllocationObserversScope
class PretenuringHandler
class ReadOnlyRoots
class DisableConservativeStackScanningScopeForTesting
class Scavenger
class ScavengerCollector
class ScheduleMinorGCTaskObserver
class SemiSpaceNewSpace
class SemiSpaceNewSpaceAllocatorPolicy
class StressConcurrentAllocationObserver
class Space
class SpaceWithLinearArea
class Sweeper
class UnifiedHeapMarkingState
class heap::TestMemoryAllocatorScope
class Factory
class LocalFactory
template<typename IsolateT >
class Deserializer
class Isolate
class heap::HeapTester
class HeapInternalsBase
Detailed Description
Definition at line 212 of file heap.h.
Member Typedef Documentation
ExternalStringTableUpdaterCallback
using v8::internal::Heap::ExternalStringTableUpdaterCallback = Tagged<String> (*)(Heap* heap, FullObjectSlot pointer) [private]
Definition at line 1711 of file heap.h.
GetExternallyAllocatedMemoryInBytesCallback
using v8::internal::Heap::GetExternallyAllocatedMemoryInBytesCallback = v8::Isolate::GetExternallyAllocatedMemoryInBytesCallback
Definition at line 1016 of file heap.h.
Reservation
using v8::internal::Heap::Reservation = std::vector<Chunk>
Definition at line 308 of file heap.h.
Member Enumeration Documentation
AllocationRetryMode
enum v8::internal::Heap::AllocationRetryMode [private]
Enumerator
kLightRetry
kRetryOrFail
Definition at line 2078 of file heap.h.
{ kLightRetry, kRetryOrFail };
HeapGrowingMode
enum v8::internal::Heap::HeapGrowingMode [strong]
Enumerator
kSlow
kConservative
kMinimal
kDefault
Definition at line 214 of file heap.h.
{ kSlow, kConservative, kMinimal, kDefault };
HeapState
enum v8::internal::Heap::HeapState
Enumerator
NOT_IN_GC
SCAVENGE
MARK_COMPACT
MINOR_MARK_SWEEP
TEAR_DOWN
Definition at line 216 of file heap.h.
                 {
    NOT_IN_GC,
    SCAVENGE,
    MARK_COMPACT,
    MINOR_MARK_SWEEP,
    TEAR_DOWN
  };
IncrementalMarkingLimit
enum v8::internal::Heap::IncrementalMarkingLimit [strong], [private]
Enumerator
kNoLimit
kSoftLimit
kHardLimit
kFallbackForEmbedderLimit
Definition at line 2027 of file heap.h.
                                     {
    kNoLimit,
    kSoftLimit,
    kHardLimit,
    kFallbackForEmbedderLimit
  };
IterateRootsMode
enum v8::internal::Heap::IterateRootsMode [strong]
Enumerator
kMainIsolate
kClientIsolate
Definition at line 1033 of file heap.h.
{ kMainIsolate, kClientIsolate };
OldGenerationExpansionNotificationOrigin
enum v8::internal::Heap::OldGenerationExpansionNotificationOrigin [strong]
Enumerator
kFromClientHeap
kFromSameHeap
Definition at line 422 of file heap.h.
                                                      {
    // Specifies that the notification is coming from the client heap.
    kFromClientHeap,
    // Specifies that the notification is done within the same heap.
    kFromSameHeap,
  };
ResizeNewSpaceMode
enum v8::internal::Heap::ResizeNewSpaceMode [strong], [private]
Enumerator
kShrink
kGrow
kNone
Definition at line 1864 of file heap.h.
{ kShrink, kGrow, kNone };
StackScanMode
enum v8::internal::Heap::StackScanMode [strong]
Enumerator
kNone
kFull
kSelective
Definition at line 377 of file heap.h.
{ kNone, kFull, kSelective };
SweepingForcedFinalizationMode
enum v8::internal::Heap::SweepingForcedFinalizationMode [strong]
Enumerator
kUnifiedHeap
kV8Only
Definition at line 1604 of file heap.h.
{ kUnifiedHeap, kV8Only };
VerifyNoSlotsRecorded
enum v8::internal::Heap::VerifyNoSlotsRecorded [strong], [private]
Enumerator
kYes
kNo
Definition at line 1829 of file heap.h.
{ kYes, kNo };
Constructor & Destructor Documentation
Heap() [1/2]
v8::internal::Heap::Heap () [private]
Definition at line 177 of file heap.cc.
    : isolate_(isolate()),
      memory_pressure_level_(MemoryPressureLevel::kNone),
      safepoint_(std::make_unique<IsolateSafepoint>(this)),
      external_string_table_(this),
      allocation_type_for_in_place_internalizable_strings_(
          isolate()->OwnsStringTables() ? AllocationType::kOld
                                        : AllocationType::kSharedOld),
      marking_state_(isolate_),
      non_atomic_marking_state_(isolate_),
      pretenuring_handler_(this) {
  // Ensure old_generation_size_ is a multiple of kPageSize.
  DCHECK_EQ(0, max_old_generation_size() & (PageMetadata::kPageSize - 1));
  max_regular_code_object_size_ = MemoryChunkLayout::MaxRegularCodeObjectSize();
  set_native_contexts_list(Smi::zero());
  // Put a dummy entry in the remembered pages so we can find the list the
  // minidump even if there are no real unmapped pages.
  RememberUnmappedPage(kNullAddress, false);
}
References DCHECK_EQ, v8::internal::kNone, v8::internal::kNullAddress, v8::internal::kOld, v8::internal::MutablePageMetadata::kPageSize, v8::internal::kSharedOld, max_old_generation_size(), max_regular_code_object_size_, v8::internal::MemoryChunkLayout::MaxRegularCodeObjectSize(), RememberUnmappedPage(), set_native_contexts_list(), and v8::internal::Smi::zero().
 Heap()
v8::internal::Heap::~Heap () [private], [default]
Heap() [2/2]
v8::internal::Heap::Heap (const Heap &) [private], [delete]
Member Function Documentation
ActivateMemoryReducerIfNeeded()
void v8::internal::Heap::ActivateMemoryReducerIfNeeded ()
Definition at line 3924 of file heap.cc.
                                         {
  if (memory_reducer_ == nullptr) return;
  // This method may be called from any thread. Post a task to run it on the
  // isolate's main thread to avoid synchronization.
  task_runner_->PostTask(std::make_unique<ActivateMemoryReducerTask>(this));
}
References memory_reducer_, and task_runner_.
Referenced by v8::internal::Isolate::SetPriority().
ActivateMemoryReducerIfNeededOnMainThread()
void v8::internal::Heap::ActivateMemoryReducerIfNeededOnMainThread () [private]
Definition at line 3931 of file heap.cc.
                                                     {
  // Activate memory reducer when switching to background if
  // - there was no mark compact since the start.
  // - the committed memory can be potentially reduced.
  // 2 pages for the old, code, and map space + 1 page for new space.
  const int kMinCommittedMemory = 7 * PageMetadata::kPageSize;
  if (ms_count_ == 0 && CommittedMemory() > kMinCommittedMemory &&
      isolate()->is_backgrounded()) {
    memory_reducer_->NotifyPossibleGarbage();
  }
}
References CommittedMemory(), isolate(), v8::internal::MutablePageMetadata::kPageSize, memory_reducer_, and ms_count_.
AddAllocationObserversToAllSpaces()
void v8::internal::Heap::AddAllocationObserversToAllSpaces (AllocationObserver * observer, AllocationObserver * new_space_observer)
Definition at line 1027 of file heap.cc.
                                                                          {
  DCHECK(observer && new_space_observer);
  FreeMainThreadLinearAllocationAreas();
  allocator()->AddAllocationObserver(observer, new_space_observer);
}
References v8::internal::HeapAllocator::AddAllocationObserver(), allocator(), v8::internal::DCHECK(), and FreeMainThreadLinearAllocationAreas().
Referenced by NotifyDeserializationComplete(), and v8::internal::SamplingHeapProfiler::SamplingHeapProfiler().
AddGCEpilogueCallback()
void v8::internal::Heap::AddGCEpilogueCallback (v8::Isolate::GCCallbackWithData callback, GCType gc_type_filter, void * data)
Definition at line 6446 of file heap.cc.
                                                             {
  gc_epilogue_callbacks_.Add(
      callback, reinterpret_cast<v8::Isolate*>(isolate()), gc_type, data);
}
References v8::internal::GCCallbacks::Add(), gc_epilogue_callbacks_, and isolate().
Referenced by v8::Isolate::AddGCEpilogueCallback(), v8::internal::wasm::WasmEngine::AddIsolate(), and SetUp().
AddGCPrologueCallback()
void v8::internal::Heap::AddGCPrologueCallback (v8::Isolate::GCCallbackWithData callback, GCType gc_type_filter, void * data)
Definition at line 6435 of file heap.cc.
                                                             {
  gc_prologue_callbacks_.Add(
      callback, reinterpret_cast<v8::Isolate*>(isolate()), gc_type, data);
}
References v8::internal::GCCallbacks::Add(), gc_prologue_callbacks_, and isolate().
Referenced by v8::Isolate::AddGCPrologueCallback(), and SetUp().
AddHeapObjectAllocationTracker()
void v8::internal::Heap::AddHeapObjectAllocationTracker (HeapObjectAllocationTracker * tracker)
Definition at line 920 of file heap.cc.
                                          {
  if (allocation_trackers_.empty() && v8_flags.inline_new) {
    DisableInlineAllocation();
  }
  allocation_trackers_.push_back(tracker);
  if (allocation_trackers_.size() == 1) {
    isolate_->UpdateLogObjectRelocation();
  }
}
References allocation_trackers_, DisableInlineAllocation(), isolate_, v8::internal::Isolate::UpdateLogObjectRelocation(), and v8::internal::v8_flags.
Referenced by v8::internal::Heap::AllocationTrackerForDebugging::AllocationTrackerForDebugging(), v8::internal::HeapProfiler::StartHeapObjectsTracking(), and v8::internal::Debug::StartSideEffectCheckMode().
AddNearHeapLimitCallback()
void v8::internal::Heap::AddNearHeapLimitCallback (v8::NearHeapLimitCallback callback, void * data)
Definition at line 4360 of file heap.cc.
                                                {
  const size_t kMaxCallbacks = 100;
  CHECK_LT(near_heap_limit_callbacks_.size(), kMaxCallbacks);
  for (auto callback_data : near_heap_limit_callbacks_) {
    CHECK_NE(callback_data.first, callback);
  }
  near_heap_limit_callbacks_.push_back(std::make_pair(callback, data));
}
References CHECK_LT, CHECK_NE, and near_heap_limit_callbacks_.
Referenced by v8::Isolate::AddNearHeapLimitCallback().
AddRetainedMaps()
void v8::internal::Heap::AddRetainedMaps (DirectHandle< NativeContext > context, GlobalHandleVector< Map > maps)
Definition at line 6521 of file heap.cc.
                                                         {
  Handle<WeakArrayList> array(Cast<WeakArrayList>(context->retained_maps()),
                              isolate());
  int new_maps_size = static_cast<int>(maps.size()) * kRetainMapEntrySize;
  if (array->length() + new_maps_size > array->capacity()) {
    CompactRetainedMaps(*array);
  }
  int cur_length = array->length();
  array =
      WeakArrayList::EnsureSpace(isolate(), array, cur_length + new_maps_size);
  if (*array != context->retained_maps()) {
    context->set_retained_maps(*array);
  }
  {
    DisallowGarbageCollection no_gc;
    Tagged<WeakArrayList> raw_array = *array;
    for (DirectHandle<Map> map : maps) {
      DCHECK(!HeapLayout::InAnySharedSpace(*map));
      if (map->is_in_retained_map_list()) {
        continue;
      }
      raw_array->Set(cur_length, MakeWeak(*map));
      raw_array->Set(cur_length + 1,
                     Smi::FromInt(v8_flags.retain_maps_for_n_gc));
      cur_length += kRetainMapEntrySize;
      raw_array->set_length(cur_length);
      map->set_is_in_retained_map_list(true);
    }
  }
}
References CompactRetainedMaps(), v8::internal::DCHECK(), v8::internal::WeakArrayList::EnsureSpace(), v8::internal::Smi::FromInt(), v8::internal::HeapLayout::InAnySharedSpace(), isolate(), kRetainMapEntrySize, v8::internal::MakeWeak(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::GlobalHandleVector< T >::size(), and v8::internal::v8_flags.
Referenced by v8::internal::OptimizedCompilationJob::RegisterWeakObjectsInOptimizedCode().
AddToRingBuffer()
void v8::internal::Heap::AddToRingBuffer (const char * string) [private]
Definition at line 5298 of file heap.cc.
                                             {
  size_t first_part =
      std::min(strlen(string), kTraceRingBufferSize - ring_buffer_end_);
  memcpy(trace_ring_buffer_ + ring_buffer_end_, string, first_part);
  ring_buffer_end_ += first_part;
  if (first_part < strlen(string)) {
    ring_buffer_full_ = true;
    size_t second_part = strlen(string) - first_part;
    memcpy(trace_ring_buffer_, string + first_part, second_part);
    ring_buffer_end_ = second_part;
  }
}
References kTraceRingBufferSize, ring_buffer_end_, ring_buffer_full_, and trace_ring_buffer_.
AlignWithFillerBackground()
Tagged< HeapObject > v8::internal::Heap::AlignWithFillerBackground (Tagged< HeapObject > object, int object_size, int allocation_size, AllocationAlignment alignment)
Definition at line 3170 of file heap.cc.
                                   {
  const int filler_size = allocation_size - object_size;
  DCHECK_LT(0, filler_size);
  const int pre_filler = GetFillToAlign(object.address(), alignment);
  if (pre_filler) {
    object = PrecedeWithFillerBackground(object, pre_filler);
  }
  DCHECK_LE(0, filler_size - pre_filler);
  const int post_filler = filler_size - pre_filler;
  if (post_filler) {
    CreateFillerObjectAtBackground(WritableFreeSpace::ForNonExecutableMemory(
        object.address() + object_size, post_filler));
  }
  return object;
}
References CreateFillerObjectAtBackground(), DCHECK_LE, DCHECK_LT, v8::internal::WritableFreeSpace::ForNonExecutableMemory(), GetFillToAlign(), and PrecedeWithFillerBackground().
Allocate()
AllocationResult v8::internal::Heap::Allocate (DirectHandle< Map > map, AllocationType allocation) [private]
Definition at line 327 of file setup-heap-internal.cc.
                                                                {
  DCHECK(map->instance_type() != MAP_TYPE);
  int size = map->instance_size();
  Tagged<HeapObject> result;
  AllocationResult allocation = AllocateRaw(size, allocation_type);
  if (!allocation.To(&result)) return allocation;
  // New space objects are allocated white.
  WriteBarrierMode write_barrier_mode =
      allocation_type == AllocationType::kYoung ? SKIP_WRITE_BARRIER
                                                : UPDATE_WRITE_BARRIER;
  result->set_map_after_allocation(isolate(), *map, write_barrier_mode);
  return AllocationResult::FromObject(result);
}
References AllocateRaw(), v8::internal::DCHECK(), v8::internal::AllocationResult::FromObject(), isolate(), v8::internal::kYoung, v8::base::internal::result, size(), v8::internal::SKIP_WRITE_BARRIER, v8::internal::AllocationResult::To(), and v8::internal::UPDATE_WRITE_BARRIER.
Referenced by CreateEarlyReadOnlyMapsAndObjects(), and CreateReadOnlyObjects().
AllocatedExternalMemorySinceMarkCompact()
uint64_t v8::internal::Heap::AllocatedExternalMemorySinceMarkCompact () const
Definition at line 5446 of file heap.cc.
                                                             {
  return external_memory_.AllocatedSinceMarkCompact();
}
References v8::internal::Heap::ExternalMemoryAccounting::AllocatedSinceMarkCompact(), and external_memory_.
Referenced by AllocationLimitOvershotByLargeMargin().
AllocateExternalBackingStore()
void * v8::internal::Heap::AllocateExternalBackingStore (const std::function< void *(size_t)> & allocate, size_t byte_length)
Definition at line 3188 of file heap.cc.
                                                                    {
  size_t max = isolate()->array_buffer_allocator()->MaxAllocationSize();
  DCHECK(max <= JSArrayBuffer::kMaxByteLength);
  if (byte_length > max) {
    return nullptr;
  }
  if (!always_allocate() && new_space()) {
    size_t new_space_backing_store_bytes =
        new_space()->ExternalBackingStoreOverallBytes();
    if ((!incremental_marking()->IsMajorMarking()) &&
        new_space_backing_store_bytes >= 2 * DefaultMaxSemiSpaceSize() &&
        new_space_backing_store_bytes >= byte_length) {
      // Performing a young generation GC amortizes over the allocated backing
      // store bytes and may free enough external bytes for this allocation.
      CollectGarbage(NEW_SPACE,
                     GarbageCollectionReason::kExternalMemoryPressure);
    }
  }
  void* result = allocate(byte_length);
  if (result) return result;
  if (!always_allocate()) {
    for (int i = 0; i < 2; i++) {
      CollectGarbage(OLD_SPACE,
                     GarbageCollectionReason::kExternalMemoryPressure);
      result = allocate(byte_length);
      if (result) return result;
    }
    CollectAllAvailableGarbage(
        GarbageCollectionReason::kExternalMemoryPressure);
  }
  return allocate(byte_length);
}
References always_allocate(), v8::internal::Isolate::array_buffer_allocator(), CollectAllAvailableGarbage(), CollectGarbage(), v8::internal::DCHECK(), DefaultMaxSemiSpaceSize(), v8::internal::NewSpace::ExternalBackingStoreOverallBytes(), incremental_marking(), isolate(), v8::internal::kExternalMemoryPressure, v8::internal::JSArrayBuffer::kMaxByteLength, v8::ArrayBuffer::Allocator::MaxAllocationSize(), v8::internal::NEW_SPACE, new_space(), v8::internal::OLD_SPACE, and v8::base::internal::result.
Referenced by v8::internal::BackingStore::Allocate().
AllocateMap()
AllocationResult v8::internal::Heap::AllocateMap (AllocationType allocation_type, InstanceType instance_type, int instance_size, ElementsKind elements_kind = TERMINAL_FAST_ELEMENTS_KIND, int inobject_properties = 0) [private]
Definition at line 256 of file setup-heap-internal.cc.
                                                            {
  static_assert(LAST_JS_OBJECT_TYPE == LAST_TYPE);
  Tagged<HeapObject> result;
  DCHECK_EQ(allocation_type, IsMutableMap(instance_type, elements_kind)
                                 ? AllocationType::kMap
                                 : AllocationType::kReadOnly);
  AllocationResult allocation = AllocateRaw(Map::kSize, allocation_type);
  if (!allocation.To(&result)) return allocation;
  ReadOnlyRoots roots(this);
  result->set_map_after_allocation(isolate(), roots.meta_map(),
                                   SKIP_WRITE_BARRIER);
  Tagged<Map> map = isolate()->factory()->InitializeMap(
      Cast<Map>(result), instance_type, instance_size, elements_kind,
      inobject_properties, roots);
  return AllocationResult::FromObject(map);
}
References AllocateRaw(), DCHECK_EQ, v8::internal::Isolate::factory(), v8::internal::AllocationResult::FromObject(), v8::internal::Factory::InitializeMap(), isolate(), v8::internal::kMap, v8::internal::kReadOnly, v8::internal::LAST_TYPE, v8::base::internal::result, v8::internal::SKIP_WRITE_BARRIER, and v8::internal::AllocationResult::To().
Referenced by CreateLateReadOnlyJSReceiverMaps(), and CreateLateReadOnlyNonJSReceiverMaps().
AllocatePartialMap()
AllocationResult v8::internal::Heap::AllocatePartialMap (InstanceType instance_type, int instance_size) [private]
Definition at line 304 of file setup-heap-internal.cc.
                                                             {
  Tagged<Object> result;
  AllocationResult allocation =
      AllocateRaw(Map::kSize, AllocationType::kReadOnly);
  if (!allocation.To(&result)) return allocation;
  // Cast<Map> cannot be used due to uninitialized map field.
  Tagged<Map> map = UncheckedCast<Map>(result);
  InitializePartialMap(isolate(), map,
                       UncheckedCast<Map>(isolate()->root(RootIndex::kMetaMap)),
                       instance_type, instance_size);
  return AllocationResult::FromObject(map);
}
References AllocateRaw(), v8::internal::AllocationResult::FromObject(), v8::internal::anonymous_namespace{setup-heap-internal.cc}::InitializePartialMap(), isolate(), v8::internal::kReadOnly, v8::base::internal::result, and v8::internal::AllocationResult::To().
Referenced by CreateEarlyReadOnlyMapsAndObjects().
AllocateRaw()
AllocationResult v8::internal::Heap::AllocateRaw (int size_in_bytes, AllocationType allocation, AllocationOrigin origin = AllocationOrigin::kRuntime, AllocationAlignment alignment = kTaggedAligned) [inline], [private]
Definition at line 198 of file heap-inl.h.
                                                                  {
  return heap_allocator_->AllocateRaw(size_in_bytes, type, origin, alignment);
}
References v8::internal::HeapAllocator::AllocateRaw(), heap_allocator_, and v8::internal::tracing::type.
Referenced by Allocate(), AllocateMap(), AllocatePartialMap(), CreateEarlyReadOnlyMapsAndObjects(), CreateImportantReadOnlyObjects(), and CreateReadOnlyObjects().
AllocateRawOrFail()
Address v8::internal::Heap::AllocateRawOrFail (int size, AllocationType allocation, AllocationOrigin origin = AllocationOrigin::kRuntime, AllocationAlignment alignment = kTaggedAligned) [inline], [private]
Definition at line 204 of file heap-inl.h.
                                                               {
  return heap_allocator_
      ->AllocateRawWith<HeapAllocator::kRetryOrFail>(size, allocation, origin,
                                                     alignment)
      .address();
}
References v8::internal::HeapAllocator::AllocateRawWith(), heap_allocator_, v8::internal::HeapAllocator::kRetryOrFail, and size().
AllocateRawWith()
template<AllocationRetryMode mode>
V8_WARN_UNUSED_RESULT Tagged<HeapObject> v8::internal::Heap::AllocateRawWith (int size, AllocationType allocation, AllocationOrigin origin = AllocationOrigin::kRuntime, AllocationAlignment alignment = kTaggedAligned) [inline], [private]
allocation_sites_list()
Tagged<UnionOf<Smi, Undefined, AllocationSiteWithWeakNext> > v8::internal::Heap::allocation_sites_list () [inline]
Definition at line 514 of file heap.h.
                          {
    return allocation_sites_list_;
  }
Referenced by v8::internal::ObjectStatsCollectorImpl::CollectGlobalStatistics(), DeoptMarkedAllocationSites(), v8::internal::AllocationSite::IsNested(), ProcessAllocationSites(), v8::internal::PretenuringHandler::ProcessPretenuringFeedback(), ProcessWeakListRoots(), and ResetAllAllocationSitesDependentCode().
allocation_sites_list_address()
Address v8::internal::Heap::allocation_sites_list_address () [inline]
Definition at line 532 of file heap.h.
                                          {
    return reinterpret_cast<Address>(&allocation_sites_list_);
  }
allocation_type_for_in_place_internalizable_strings()
AllocationType v8::internal::Heap::allocation_type_for_in_place_internalizable_strings () const [inline], [private]
Definition at line 2117 of file heap.h.
                                                                             {
    return allocation_type_for_in_place_internalizable_strings_;
  }
Referenced by v8::internal::Factory::AllocationTypeForInPlaceInternalizableString(), and v8::internal::LocalFactory::AllocationTypeForInPlaceInternalizableString().
AllocationLimitOvershotByLargeMargin()
bool v8::internal::Heap::AllocationLimitOvershotByLargeMargin () const
Definition at line 5450 of file heap.cc.
                                                      {
  // This guards against too eager finalization in small heaps.
  // The number is chosen based on v8.browsing_mobile on Nexus 7v2.
  constexpr size_t kMarginForSmallHeaps = 32u * MB;
  uint64_t size_now = OldGenerationConsumedBytes();
  if (!v8_flags.external_memory_accounted_in_global_limit) {
    size_now += AllocatedExternalMemorySinceMarkCompact();
  }
  if (incremental_marking()->IsMajorMarking()) {
    // No interleaved GCs, so we count young gen as part of old gen.
    size_now += YoungGenerationConsumedBytes();
  }
  const size_t v8_overshoot = old_generation_allocation_limit() < size_now
                                  ? size_now - old_generation_allocation_limit()
                                  : 0;
  const size_t global_limit = global_allocation_limit();
  const size_t global_size = GlobalConsumedBytes();
  const size_t global_overshoot =
      global_limit < global_size ? global_size - global_limit : 0;
  // Bail out if the V8 and global sizes are still below their respective
  // limits.
  if (v8_overshoot == 0 && global_overshoot == 0) {
    return false;
  }
  // Overshoot margin is 50% of allocation limit or half-way to the max heap
  // with special handling of small heaps.
  const size_t v8_margin = std::min(
      std::max(old_generation_allocation_limit() / 2, kMarginForSmallHeaps),
      (max_old_generation_size() - old_generation_allocation_limit()) / 2);
  const size_t global_margin =
      std::min(std::max(global_limit / 2, kMarginForSmallHeaps),
               (max_global_memory_size_ - global_limit) / 2);
  return v8_overshoot >= v8_margin || global_overshoot >= global_margin;
}
References AllocatedExternalMemorySinceMarkCompact(), global_allocation_limit(), GlobalConsumedBytes(), incremental_marking(), max_global_memory_size_, max_old_generation_size(), v8::internal::MB, old_generation_allocation_limit(), OldGenerationConsumedBytes(), v8::internal::v8_flags, and YoungGenerationConsumedBytes().
Referenced by RecomputeLimitsAfterLoadingIfNeeded(), ShouldExpandOldGenerationOnSlowAllocation(), ShouldExpandYoungGenerationOnSlowAllocation(), and ShouldOptimizeForLoadTime().
allocator() [1/2]
HeapAllocator* v8::internal::Heap::allocator () [inline]
Definition at line 1696 of file heap.h.
{ return heap_allocator_; }
Referenced by AddAllocationObserversToAllSpaces(), v8::internal::ScheduleMinorGCTaskObserver::AddToNewSpace(), v8::internal::Factory::allocator(), v8::internal::ScavengerCollector::CollectGarbage(), CreateReadOnlyObjects(), v8::internal::EvacuationAllocator::EvacuationAllocator(), v8::internal::MarkCompactCollector::Finish(), FreeMainThreadLinearAllocationAreas(), FreeSharedLinearAllocationAreasAndResetFreeLists(), IsPendingAllocationInternal(), MakeLinearAllocationAreasIterable(), v8::internal::MarkCompactCollector::MarkObjectsFromClientHeap(), MarkSharedLinearAllocationAreasBlack(), NewSpaceAllocationCounter(), NewSpaceLimit(), NewSpaceTop(), OldSpaceAllocationLimitAddress(), OldSpaceAllocationTopAddress(), v8::internal::IncrementalMarking::PauseBlackAllocation(), v8::internal::MarkCompactCollector::Prepare(), PublishMainThreadPendingAllocations(), RemoveAllocationObserversFromAllSpaces(), v8::internal::ScheduleMinorGCTaskObserver::RemoveFromNewSpace(), v8::internal::ConcurrentMarking::RunMajor(), v8::internal::ConcurrentMarking::RunMinorImpl(), SetUpSpaces(), v8::internal::IncrementalMarking::StartBlackAllocation(), v8::internal::IncrementalMarking::StartMarkingMajor(), StaticRootsEnsureAllocatedSize(), v8::internal::ScheduleMinorGCTaskObserver::Step(), v8::internal::IncrementalMarking::Stop(), TearDown(), UnmarkSharedLinearAllocationAreas(), and v8::internal::PauseAllocationObserversScope::~PauseAllocationObserversScope().
allocator() [2/2]
const HeapAllocator* v8::internal::Heap::allocator () const [inline]
Definition at line 1697 of file heap.h.
{ return heap_allocator_; }
AllocatorLimitOnMaxOldGenerationSize()
size_t v8::internal::Heap::AllocatorLimitOnMaxOldGenerationSize () [static]
Definition at line 278 of file heap.cc.
                                                  {
#ifdef V8_COMPRESS_POINTERS
  // Isolate and the young generation are also allocated on the heap.
  return kPtrComprCageReservationSize -
         YoungGenerationSizeFromSemiSpaceSize(DefaultMaxSemiSpaceSize()) -
         RoundUp(sizeof(Isolate), size_t{1} << kPageSizeBits);
#else
  return std::numeric_limits<size_t>::max();
#endif
}
References DefaultMaxSemiSpaceSize(), kPageSizeBits, RoundUp(), and YoungGenerationSizeFromSemiSpaceSize().
Referenced by ConfigureHeap(), InvokeNearHeapLimitCallback(), and MaxOldGenerationSizeFromPhysicalMemory().
AllowedToBeMigrated()
bool v8::internal::Heap::AllowedToBeMigrated (Tagged< Map > map, Tagged< HeapObject > object, AllocationSpace dest)
Definition at line 7230 of file heap.cc.
                                                    {
  // Object migration is governed by the following rules:
  //
  // 1) Objects in new-space can be migrated to the old space
  // that matches their target space or they stay in new-space.
  // 2) Objects in old-space stay in the same space when migrating.
  // 3) Fillers (two or more words) can migrate due to left-trimming of
  // fixed arrays in new-space or old space.
  // 4) Fillers (one word) can never migrate, they are skipped by
  // incremental marking explicitly to prevent invalid pattern.
  //
  // Since this function is used for debugging only, we do not place
  // asserts here, but check everything explicitly.
  if (map == ReadOnlyRoots(this).one_pointer_filler_map()) {
    return false;
  }
  InstanceType type = map->instance_type();
  MutablePageMetadata* chunk = MutablePageMetadata::FromHeapObject(object);
  AllocationSpace src = chunk->owner_identity();
  switch (src) {
    case NEW_SPACE:
      return dst == NEW_SPACE || dst == OLD_SPACE;
    case OLD_SPACE:
      return dst == OLD_SPACE;
    case CODE_SPACE:
      return dst == CODE_SPACE && type == INSTRUCTION_STREAM_TYPE;
    case SHARED_SPACE:
      return dst == SHARED_SPACE;
    case TRUSTED_SPACE:
      return dst == TRUSTED_SPACE;
    case SHARED_TRUSTED_SPACE:
      return dst == SHARED_TRUSTED_SPACE;
    case LO_SPACE:
    case CODE_LO_SPACE:
    case NEW_LO_SPACE:
    case SHARED_LO_SPACE:
    case TRUSTED_LO_SPACE:
    case SHARED_TRUSTED_LO_SPACE:
    case RO_SPACE:
      return false;
  }
  UNREACHABLE();
}
References v8::internal::CODE_LO_SPACE, v8::internal::CODE_SPACE, v8::internal::MutablePageMetadata::FromHeapObject(), v8::internal::LO_SPACE, v8::internal::NEW_LO_SPACE, v8::internal::NEW_SPACE, v8::internal::OLD_SPACE, v8::internal::MutablePageMetadata::owner_identity(), ReadOnlyRoots, v8::internal::RO_SPACE, v8::internal::SHARED_LO_SPACE, v8::internal::SHARED_SPACE, v8::internal::SHARED_TRUSTED_LO_SPACE, v8::internal::SHARED_TRUSTED_SPACE, v8::internal::TRUSTED_LO_SPACE, v8::internal::TRUSTED_SPACE, v8::internal::tracing::type, and v8::internal::UNREACHABLE().
Referenced by v8::internal::EvacuateVisitorBase::RawMigrateObject().
always_allocate()
bool v8::internal::Heap::always_allocate () const [inline], [private]
Definition at line 2017 of file heap.h.
{ return always_allocate_scope_count_ != 0; }
Referenced by v8::internal::IncrementalMarking::AdvanceAndFinalizeIfNecessary(), AllocateExternalBackingStore(), CollectGarbage(), CollectGarbageShared(), IncrementalMarkingLimitReached(), IsNewSpaceAllowedToGrowAboveTargetCapacity(), ShouldExpandOldGenerationOnSlowAllocation(), and ShouldExpandYoungGenerationOnSlowAllocation().
AppendArrayBufferExtension()
void v8::internal::Heap::AppendArrayBufferExtension (ArrayBufferExtension * extension)
Definition at line 4384 of file heap.cc.
                                                                     {
  // ArrayBufferSweeper is managing all counters and updating Heap counters.
  array_buffer_sweeper_->Append(extension);
}
References array_buffer_sweeper_.
Referenced by v8::internal::JSArrayBuffer::CreateExtension().
array_buffer_sweeper()
ArrayBufferSweeper* v8::internal::Heap::array_buffer_sweeper () [inline]
Definition at line 866 of file heap.h.
                                             {
    return array_buffer_sweeper_.get();
  }
Referenced by v8::internal::MinorMarkSweepCollector::CollectGarbage(), v8::internal::anonymous_namespace{heap.cc}::CompleteArrayBufferSweeping(), OldArrayBufferBytes(), v8::internal::MinorMarkSweepCollector::Sweep(), v8::internal::MarkCompactCollector::SweepArrayBufferExtensions(), v8::internal::ScavengerCollector::SweepArrayBufferExtensions(), and YoungArrayBufferBytes().
AsHeap()
Heap* v8::internal::Heap::AsHeap () [inline]
Definition at line 887 of file heap.h.
{ return this; }
AttachCppHeap()
void v8::internal::Heap::AttachCppHeap (v8::CppHeap * cpp_heap) [private]
Definition at line 6234 of file heap.cc.
                                            {
  // Only a single CppHeap can be attached at a time.
  CHECK(!owning_cpp_heap_);
  CHECK_IMPLIES(incremental_marking(), !incremental_marking()->IsMarking());
  CppHeap::From(cpp_heap)->AttachIsolate(isolate());
  cpp_heap_ = cpp_heap;
}
References v8::internal::CppHeap::AttachIsolate(), CHECK, CHECK_IMPLIES, cpp_heap(), cpp_heap_, v8::internal::CppHeap::From(), incremental_marking(), isolate(), and owning_cpp_heap_.
Referenced by ConfigureHeap().
AutomaticallyRestoreInitialHeapLimit()
void v8::internal::Heap::AutomaticallyRestoreInitialHeapLimit (double threshold_percent)
Definition at line 4400 of file heap.cc.
                                                                        {
  initial_max_old_generation_size_threshold_ =
      initial_max_old_generation_size_ * threshold_percent;
}
References initial_max_old_generation_size_, and initial_max_old_generation_size_threshold_.
Referenced by v8::Isolate::AutomaticallyRestoreInitialHeapLimit().
Available()
size_t v8::internal::Heap::Available ()
Definition at line 400 of file heap.cc.
                       {
  if (!HasBeenSetUp()) return 0;
  size_t total = 0;
  for (SpaceIterator it(this); it.HasNext();) {
    total += it.Next()->Available();
  }
  total += memory_allocator()->Available();
  return total;
}
References v8::internal::MemoryAllocator::Available(), HasBeenSetUp(), v8::internal::SpaceIterator::HasNext(), and memory_allocator().
Referenced by PrintShortHeapStatistics(), and SetUpSpaces().
backing_store_bytes()
uint64_t v8::internal::Heap::backing_store_bytes () const [inline]
Definition at line 668 of file heap.h.
                                       {
    return backing_store_bytes_.load(std::memory_order_relaxed);
  }
Referenced by v8::internal::ArrayBufferSweeper::Finish(), v8::Isolate::GetHeapStatistics(), and PrintShortHeapStatistics().
CallGCEpilogueCallbacks()
void v8::internal::Heap::CallGCEpilogueCallbacks (GCType gc_type, GCCallbackFlags flags, GCTracer::Scope::ScopeId scope_id)
Definition at line 2720 of file heap.cc.
                                                                  {
  if (gc_epilogue_callbacks_.IsEmpty()) return;
  GCCallbacksScope scope(this);
  if (scope.CheckReenter()) {
    RCS_SCOPE(isolate(), RuntimeCallCounterId::kGCEpilogueCallback);
    TRACE_GC(tracer(), scope_id);
    HandleScope handle_scope(isolate());
    gc_epilogue_callbacks_.Invoke(gc_type, flags);
  }
}
References v8::internal::GCCallbacksScope::CheckReenter(), v8::internal::flags, gc_epilogue_callbacks_, v8::internal::GCCallbacks::Invoke(), v8::internal::GCCallbacks::IsEmpty(), isolate(), RCS_SCOPE, TRACE_GC, and tracer().
Referenced by CollectGarbage(), InvokeIncrementalMarkingEpilogueCallbacks(), and v8::internal::GlobalHandles::InvokeSecondPassPhantomCallbacks().
CallGCPrologueCallbacks()
void v8::internal::Heap::CallGCPrologueCallbacks (GCType gc_type, GCCallbackFlags flags, GCTracer::Scope::ScopeId scope_id)
Definition at line 2707 of file heap.cc.
                                                                  {
  if (gc_prologue_callbacks_.IsEmpty()) return;
  GCCallbacksScope scope(this);
  if (scope.CheckReenter()) {
    RCS_SCOPE(isolate(), RuntimeCallCounterId::kGCPrologueCallback);
    TRACE_GC(tracer(), scope_id);
    HandleScope handle_scope(isolate());
    gc_prologue_callbacks_.Invoke(gc_type, flags);
  }
}
References v8::internal::GCCallbacksScope::CheckReenter(), v8::internal::flags, gc_prologue_callbacks_, v8::internal::GCCallbacks::Invoke(), v8::internal::GCCallbacks::IsEmpty(), isolate(), RCS_SCOPE, TRACE_GC, and tracer().
Referenced by CollectGarbage(), InvokeIncrementalMarkingPrologueCallbacks(), and v8::internal::GlobalHandles::InvokeSecondPassPhantomCallbacks().
CanExpandOldGeneration()
bool v8::internal::Heap::CanExpandOldGeneration (size_t size) const
Definition at line 413 of file heap.cc.
                                                   {
  if (force_oom_ || force_gc_on_next_allocation_) return false;
  if (OldGenerationCapacity() + size > max_old_generation_size()) return false;
  // Stay below `MaxReserved()` such that it is more likely that committing the
  // second semi space at the beginning of a GC succeeds.
  return memory_allocator()->Size() + size <= MaxReserved();
}
References force_gc_on_next_allocation_, force_oom_, max_old_generation_size(), MaxReserved(), memory_allocator(), OldGenerationCapacity(), v8::internal::MemoryAllocator::Size(), and size().
Referenced by CanPromoteYoungAndExpandOldGeneration(), ReachedHeapLimit(), and ShouldOptimizeForMemoryUsage().
CanMoveObjectStart()
bool v8::internal::Heap::CanMoveObjectStart (Tagged< HeapObject > object)
Definition at line 3384 of file heap.cc.
                                                       {
  if (!v8_flags.move_object_start) {
    return false;
  }
  // Sampling heap profiler may have a reference to the object.
  if (heap_profiler()->is_sampling_allocations()) {
    return false;
  }
  if (IsLargeObject(object)) {
    return false;
  }
  // Compilation jobs may have references to the object.
  if (isolate()->concurrent_recompilation_enabled() &&
      isolate()->optimizing_compile_dispatcher()->HasJobs()) {
    return false;
  }
  // Concurrent marking does not support moving object starts without snapshot
  // protocol.
  //
  // TODO(v8:13726): This can be improved via concurrently reading the contents
  // in the marker at the cost of some complexity.
  if (incremental_marking()->IsMarking()) {
    return false;
  }
  // Concurrent sweeper does not support moving object starts. It assumes that
  // markbits (black regions) and object starts are matching up.
  if (!MutablePageMetadata::FromHeapObject(object)->SweepingDone()) {
    return false;
  }
  return true;
}
References v8::internal::MutablePageMetadata::FromHeapObject(), heap_profiler(), incremental_marking(), IsLargeObject(), isolate(), and v8::internal::v8_flags.
Referenced by LeftTrimFixedArray(), and v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::RemoveElement().
CanPromoteYoungAndExpandOldGeneration()
bool v8::internal::Heap::CanPromoteYoungAndExpandOldGeneration (size_t size) const
Definition at line 426 of file heap.cc.
                                                                  {
  if (v8_flags.sticky_mark_bits) {
    DCHECK_NULL(new_space());
    size_t new_space_capacity =
        sticky_space()->Capacity() - sticky_space()->young_objects_size();
    size_t new_lo_space_capacity = new_lo_space_ ? new_lo_space_->Size() : 0;
    return CanExpandOldGeneration(size + new_space_capacity +
                                  new_lo_space_capacity);
  }
  if (!new_space()) {
    DCHECK_NULL(new_lo_space());
    return CanExpandOldGeneration(size);
  }
  size_t new_space_capacity =
      new_space()->Capacity() + new_lo_space()->Size() +
      (v8_flags.minor_ms ? 0
                         : semi_space_new_space()->QuarantinedPageCount() *
                               PageMetadata::kPageSize);
  // Over-estimate the new space size using capacity to allow some slack.
  return CanExpandOldGeneration(size + new_space_capacity);
}
References CanExpandOldGeneration(), v8::internal::PagedSpaceBase::Capacity(), v8::internal::NewSpace::Capacity(), DCHECK_NULL, v8::internal::MutablePageMetadata::kPageSize, new_lo_space(), new_lo_space_, new_space(), v8::internal::SemiSpaceNewSpace::QuarantinedPageCount(), semi_space_new_space(), v8::internal::LargeObjectSpace::Size(), size(), sticky_space(), v8::internal::v8_flags, and v8::internal::StickySpace::young_objects_size().
Referenced by v8::internal::ScavengerCollector::NumberOfScavengeTasks(), SelectGarbageCollector(), and ShouldExpandYoungGenerationOnSlowAllocation().
CanReferenceHeapObject()
bool v8::internal::Heap::CanReferenceHeapObject (Tagged< HeapObject > obj)
Definition at line 4611 of file heap.cc.
                                                        {
  MemoryChunk* chunk = MemoryChunk::FromHeapObject(obj);
  // Objects in read-only space are allowed to be used in any isolate.
  if (chunk->InReadOnlySpace()) return true;
  Heap* obj_heap = chunk->GetHeap();
  Heap* expected_heap = chunk->InWritableSharedSpace()
                            ? isolate()->shared_space_isolate()->heap()
                            : this;
  return obj_heap == expected_heap;
}
References v8::internal::MemoryChunk::FromHeapObject(), v8::internal::MemoryChunk::GetHeap(), v8::internal::Isolate::heap(), v8::internal::MemoryChunk::InReadOnlySpace(), v8::internal::MemoryChunk::InWritableSharedSpace(), isolate(), and v8::internal::Isolate::shared_space_isolate().
Referenced by v8::internal::HandleScope::CreateHandle().
CanSafepoint()
bool v8::internal::Heap::CanSafepoint () const [inline]
Definition at line 686 of file heap.h.
{ return deserialization_complete(); }
Referenced by v8::internal::HeapAllocator::AllocateRaw().
CanShortcutStringsDuringGC()
bool v8::internal::Heap::CanShortcutStringsDuringGC (GarbageCollector collector) const
Definition at line 535 of file heap.cc.
                                                                      {
  if (!v8_flags.shortcut_strings_with_stack && IsGCWithStack()) return false;
  switch (collector) {
    case GarbageCollector::MINOR_MARK_SWEEPER:
      if (!v8_flags.minor_ms_shortcut_strings) return false;
      DCHECK(!incremental_marking()->IsMajorMarking());
      // Minor MS cannot short cut strings during concurrent marking.
      if (incremental_marking()->IsMinorMarking()) return false;
      // Minor MS uses static roots to check for strings to shortcut.
      if (!V8_STATIC_ROOTS_BOOL) return false;
      break;
    case GarbageCollector::SCAVENGER:
      // Scavenger cannot short cut strings during incremental marking.
      DCHECK(!incremental_marking()->IsMajorMarking());
      if (isolate()->has_shared_space() &&
          !isolate()->is_shared_space_isolate() &&
          isolate()
              ->shared_space_isolate()
              ->heap()
              ->incremental_marking()
              ->IsMarking()) {
        DCHECK(isolate()
                   ->shared_space_isolate()
                   ->heap()
                   ->incremental_marking()
                   ->IsMajorMarking());
        return false;
      }
      break;
    default:
      UNREACHABLE();
  }
  return true;
}
References v8::internal::DCHECK(), heap(), incremental_marking(), IsGCWithStack(), isolate(), v8::internal::MINOR_MARK_SWEEPER, v8::internal::SCAVENGER, v8::internal::UNREACHABLE(), v8::internal::v8_flags, and V8_STATIC_ROOTS_BOOL.
Capacity()
size_t v8::internal::Heap::Capacity ()
Definition at line 326 of file heap.cc.
                      {
  if (!HasBeenSetUp()) {
    return 0;
  }
  return NewSpaceCapacity() + OldGenerationCapacity();
}
References HasBeenSetUp(), NewSpaceCapacity(), and OldGenerationCapacity().
Referenced by SetUpSpaces().
CheckCollectionRequested()
void v8::internal::Heap::CheckCollectionRequested ()
Definition at line 2239 of file heap.cc.
                                    {
  if (!CollectionRequested()) return;
  CollectAllGarbage(current_gc_flags_,
                    GarbageCollectionReason::kBackgroundAllocationFailure,
                    current_gc_callback_flags_);
}
References CollectAllGarbage(), CollectionRequested(), current_gc_callback_flags_, current_gc_flags_, and v8::internal::kBackgroundAllocationFailure.
Referenced by HandleGCRequest(), and v8::internal::BackgroundCollectionInterruptTask::RunInternal().
CheckHandleCount()
void v8::internal::Heap::CheckHandleCount ()
Definition at line 6623 of file heap.cc.
                            {
  CheckHandleCountVisitor v;
  isolate_->handle_scope_implementer()->Iterate(&v);
}
References v8::internal::Isolate::handle_scope_implementer(), isolate_, and v8::internal::HandleScopeImplementer::Iterate().
Referenced by GarbageCollectionEpilogueInSafepoint().
CheckHeapLimitReached()
void v8::internal::Heap::CheckHeapLimitReached () [private]
Definition at line 1811 of file heap.cc.
                                 {
  if (ReachedHeapLimit()) {
    InvokeNearHeapLimitCallback();
    if (ReachedHeapLimit()) {
      if (v8_flags.heap_snapshot_on_oom) {
        heap_profiler()->WriteSnapshotToDiskAfterGC();
      }
      FatalProcessOutOfMemory("Reached heap limit");
    }
  }
}
References FatalProcessOutOfMemory(), heap_profiler(), InvokeNearHeapLimitCallback(), ReachedHeapLimit(), v8::internal::v8_flags, and v8::internal::HeapProfiler::WriteSnapshotToDiskAfterGC().
Referenced by v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(), CollectAllAvailableGarbage(), and CollectGarbage().
CheckIneffectiveMarkCompact()
void v8::internal::Heap::CheckIneffectiveMarkCompact (size_t old_generation_size, double mutator_utilization) [private]
Definition at line 3861 of file heap.cc.
                                                                   {
  if (!v8_flags.detect_ineffective_gcs_near_heap_limit) return;
  if (!IsIneffectiveMarkCompact(old_generation_size, mutator_utilization)) {
    consecutive_ineffective_mark_compacts_ = 0;
    return;
  }
  ++consecutive_ineffective_mark_compacts_;
  if (consecutive_ineffective_mark_compacts_ ==
      kMaxConsecutiveIneffectiveMarkCompacts) {
    if (InvokeNearHeapLimitCallback()) {
      // The callback increased the heap limit.
      consecutive_ineffective_mark_compacts_ = 0;
      return;
    }
    if (v8_flags.heap_snapshot_on_oom) {
      heap_profiler()->WriteSnapshotToDiskAfterGC();
    }
    FatalProcessOutOfMemory("Ineffective mark-compacts near heap limit");
  }
}
References consecutive_ineffective_mark_compacts_, FatalProcessOutOfMemory(), heap_profiler(), InvokeNearHeapLimitCallback(), IsIneffectiveMarkCompact(), v8::internal::anonymous_namespace{heap.cc}::kMaxConsecutiveIneffectiveMarkCompacts, v8::internal::v8_flags, and v8::internal::HeapProfiler::WriteSnapshotToDiskAfterGC().
Referenced by RecomputeLimits().
CheckMemoryPressure()
void v8::internal::Heap::CheckMemoryPressure ()
Definition at line 4273 of file heap.cc.
                               {
  if (HighMemoryPressure()) {
    FreeCachesOnMemoryPressure(isolate());
  }
  // Reset the memory pressure level to avoid recursive GCs triggered by
  // CheckMemoryPressure from AdjustAmountOfExternalMemory called by
  // the finalizers.
  MemoryPressureLevel memory_pressure_level = memory_pressure_level_.exchange(
      MemoryPressureLevel::kNone, std::memory_order_relaxed);
  if (memory_pressure_level == MemoryPressureLevel::kCritical) {
    TRACE_EVENT0("devtools.timeline,v8", "V8.CheckMemoryPressure");
    CollectGarbageOnMemoryPressure();
  } else if (memory_pressure_level == MemoryPressureLevel::kModerate) {
    if (v8_flags.incremental_marking && incremental_marking()->IsStopped()) {
      TRACE_EVENT0("devtools.timeline,v8", "V8.CheckMemoryPressure");
      StartIncrementalMarking(GCFlag::kReduceMemoryFootprint,
                              GarbageCollectionReason::kMemoryPressure);
    }
  }
}
References CollectGarbageOnMemoryPressure(), v8::internal::anonymous_namespace{heap.cc}::FreeCachesOnMemoryPressure(), HighMemoryPressure(), incremental_marking(), isolate(), v8::kCritical, v8::internal::kMemoryPressure, v8::kModerate, v8::kNone, v8::internal::kReduceMemoryFootprint, memory_pressure_level_, StartIncrementalMarking(), TRACE_EVENT0, and v8::internal::v8_flags.
Referenced by HandleGCRequest(), and MemoryPressureNotification().
ClearKeptObjects()
void v8::internal::Heap::ClearKeptObjects ()
Definition at line 7147 of file heap.cc.
                            {
  set_weak_refs_keep_during_job(ReadOnlyRoots(isolate()).undefined_value());
}
References isolate(), and ReadOnlyRoots.
Referenced by v8::internal::Isolate::ClearKeptObjects().
ClearRecordedSlotRange()
void v8::internal::Heap::ClearRecordedSlotRange (Address start, Address end)
Definition at line 6649 of file heap.cc.
                                                            {
#ifndef V8_DISABLE_WRITE_BARRIERS
  MemoryChunk* chunk = MemoryChunk::FromAddress(start);
  DCHECK(!chunk->IsLargePage());
#if !V8_ENABLE_STICKY_MARK_BITS_BOOL
  if (!chunk->InYoungGeneration())
#endif
  {
    PageMetadata* page = PageMetadata::cast(chunk->Metadata());
    // This method will be invoked on objects in shared space for
    // internalization and string forwarding during GC.
    DCHECK(page->owner_identity() == OLD_SPACE ||
           page->owner_identity() == TRUSTED_SPACE ||
           page->owner_identity() == SHARED_SPACE);
    if (!page->SweepingDone()) {
      RememberedSet<OLD_TO_NEW>::RemoveRange(page, start, end,
                                             SlotSet::KEEP_EMPTY_BUCKETS);
      RememberedSet<OLD_TO_NEW_BACKGROUND>::RemoveRange(
          page, start, end, SlotSet::KEEP_EMPTY_BUCKETS);
      RememberedSet<OLD_TO_SHARED>::RemoveRange(page, start, end,
                                                SlotSet::KEEP_EMPTY_BUCKETS);
    }
  }
#endif
}
References v8::internal::PageMetadata::cast(), v8::internal::DCHECK(), v8::internal::compiler::end(), v8::internal::MemoryChunk::FromAddress(), v8::internal::MemoryChunk::InYoungGeneration(), v8::internal::MemoryChunk::IsLargePage(), heap::base::BasicSlotSet< kTaggedSize >::KEEP_EMPTY_BUCKETS, v8::internal::MemoryChunk::Metadata(), v8::internal::OLD_SPACE, v8::internal::MutablePageMetadata::owner_identity(), v8::internal::RememberedSet< type >::RemoveRange(), v8::internal::SHARED_SPACE, v8::internal::MutablePageMetadata::SweepingDone(), and v8::internal::TRUSTED_SPACE.
Referenced by CreateFillerObjectAtRaw().
code_lo_space()
CodeLargeObjectSpace* v8::internal::Heap::code_lo_space () const [inline]
Definition at line 778 of file heap.h.
{ return code_lo_space_; }
Referenced by DeactivateMajorGCInProgressFlag(), v8::internal::anonymous_namespace{deoptimizer.cc}::DeoptimizableCodeIterator::Next(), v8::internal::OldGenerationMemoryChunkIterator::next(), OldGenerationSizeOfObjects(), v8::internal::IncrementalMarking::OldGenerationSizeOfObjects(), and Unmark().
code_range()
CodeRange* v8::internal::Heap::code_range () [inline]
Definition at line 874 of file heap.h.
                          {
#ifdef V8_COMPRESS_POINTERS
    return code_range_;
#else
    return code_range_.get();
#endif
  }
Referenced by v8::internal::Isolate::Init(), and v8::internal::CodeDataSourceIncrementalState::InternIsolate().
code_range_base()
Address v8::internal::Heap::code_range_base () [inline]
Definition at line 185 of file heap-inl.h.
                              {
  return code_range_ ? code_range_->base() : kNullAddress;
}
References code_range_, and v8::internal::kNullAddress.
Referenced by v8::internal::Isolate::AddCrashKeysForIsolateAndHeapPointers(), and v8::internal::AssemblerOptions::Default().
code_region()
const base::AddressRegion & v8::internal::Heap::code_region () [inline]
Definition at line 180 of file heap-inl.h.
                                                  {
  static constexpr base::AddressRegion kEmptyRegion;
  return code_range_ ? code_range_->reservation()->region() : kEmptyRegion;
}
References code_range_.
Referenced by v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuiltinAssemblerOptions(), v8::Isolate::GetCodeRange(), v8::internal::TickSample::GetStackSample(), v8::internal::Isolate::InitializeIsShortBuiltinCallsEnabled(), and v8::internal::Isolate::MaybeRemapEmbeddedBuiltinsIntoCodeRange().
code_space()
CodeSpace* v8::internal::Heap::code_space () const [inline]
Definition at line 775 of file heap.h.
{ return code_space_; }
Referenced by v8::internal::Isolate::AddCrashKeysForIsolateAndHeapPointers(), DeactivateMajorGCInProgressFlag(), EnsureSweepingCompleted(), v8::internal::EvacuationAllocator::Finalize(), GarbageCollectionEpilogue(), GarbageCollectionEpilogueInSafepoint(), v8::internal::OldGenerationMemoryChunkIterator::next(), OldGenerationSizeOfObjects(), v8::internal::HeapAllocator::Setup(), v8::internal::MarkCompactCollector::StartCompaction(), Unmark(), and v8::internal::MarkCompactCollector::VerifyMarking().
CollectAllAvailableGarbage()
void v8::internal::Heap::CollectAllAvailableGarbage (GarbageCollectionReason gc_reason)
Definition at line 1351 of file heap.cc.
                                                                       {
  // Min and max number of attempts for GC. The method will continue with more
  // GCs until the root set is stable.
  static constexpr int kMaxNumberOfAttempts = 7;
  static constexpr int kMinNumberOfAttempts = 2;
  // Returns the number of roots. We assume stack layout is stable but global
  // roots could change between GCs due to finalizers and weak callbacks.
  const auto num_roots = [this]() {
    size_t js_roots = 0;
    js_roots += isolate()->global_handles()->handles_count();
    js_roots += isolate()->eternal_handles()->handles_count();
    size_t cpp_roots = 0;
    if (auto* cpp_heap = CppHeap::From(cpp_heap_)) {
      cpp_roots += cpp_heap->GetStrongPersistentRegion().NodesInUse();
      cpp_roots +=
          cpp_heap->GetStrongCrossThreadPersistentRegion().NodesInUse();
    }
    return js_roots + cpp_roots;
  };
  if (gc_reason == GarbageCollectionReason::kLastResort) {
    InvokeNearHeapLimitCallback();
  }
  RCS_SCOPE(isolate(), RuntimeCallCounterId::kGC_Custom_AllAvailableGarbage);
  FreeCachesOnMemoryPressure(isolate());
  GCFlags gc_flags = GCFlag::kReduceMemoryFootprint;
  if (gc_reason == GarbageCollectionReason::kLastResort) {
    gc_flags |= GCFlag::kLastResort;
  }
  if (gc_reason == GarbageCollectionReason::kLowMemoryNotification) {
    gc_flags |= GCFlag::kForced;
  }
  const auto perform_heap_limit_check = v8_flags.late_heap_limit_check
                                            ? PerformHeapLimitCheck::kNo
                                            : PerformHeapLimitCheck::kYes;
  for (int attempt = 0; attempt < kMaxNumberOfAttempts; attempt++) {
    const size_t roots_before = num_roots();
    current_gc_flags_ = gc_flags;
    CollectGarbage(OLD_SPACE, gc_reason, kNoGCCallbackFlags,
                   perform_heap_limit_check);
    DCHECK_EQ(GCFlags(GCFlag::kNoFlags), current_gc_flags_);
    // As long as we are at or above the heap limit, we need another GC to
    // survive CheckHeapLimitReached() after the loop.
    if (ReachedHeapLimit()) {
      continue;
    }
    if ((roots_before == num_roots()) &&
        ((attempt + 1) >= kMinNumberOfAttempts)) {
      break;
    }
  }
  CheckHeapLimitReached();
  EagerlyFreeExternalMemoryAndWasmCode();
  if (v8_flags.trace_duplicate_threshold_kb) {
    std::map<int, std::vector<Tagged<HeapObject>>> objects_by_size;
    PagedSpaceIterator spaces(this);
    for (PagedSpace* space = spaces.Next(); space != nullptr;
         space = spaces.Next()) {
      PagedSpaceObjectIterator it(this, space);
      for (Tagged<HeapObject> obj = it.Next(); !obj.is_null();
           obj = it.Next()) {
        objects_by_size[obj->Size()].push_back(obj);
      }
    }
    {
      LargeObjectSpaceObjectIterator it(lo_space());
      for (Tagged<HeapObject> obj = it.Next(); !obj.is_null();
           obj = it.Next()) {
        objects_by_size[obj->Size()].push_back(obj);
      }
    }
    for (auto it = objects_by_size.rbegin(); it != objects_by_size.rend();
         ++it) {
      ReportDuplicates(it->first, &it->second);
    }
  }
  if (gc_reason == GarbageCollectionReason::kLastResort &&
      v8_flags.heap_snapshot_on_oom) {
    heap_profiler()->WriteSnapshotToDiskAfterGC();
  }
}
References CheckHeapLimitReached(), CollectGarbage(), cpp_heap(), cpp_heap_, current_gc_flags_, DCHECK_EQ, EagerlyFreeExternalMemoryAndWasmCode(), v8::internal::Isolate::eternal_handles(), v8::internal::anonymous_namespace{heap.cc}::FreeCachesOnMemoryPressure(), v8::internal::CppHeap::From(), v8::internal::Isolate::global_handles(), v8::internal::GlobalHandles::handles_count(), v8::internal::EternalHandles::handles_count(), heap_profiler(), InvokeNearHeapLimitCallback(), v8::internal::Tagged< HeapObject >::is_null(), isolate(), v8::internal::kForced, v8::internal::kLastResort, v8::internal::kLowMemoryNotification, v8::internal::kNo, v8::internal::kNoFlags, v8::kNoGCCallbackFlags, v8::internal::kReduceMemoryFootprint, v8::internal::kYes, lo_space(), v8::internal::PagedSpaceIterator::Next(), v8::internal::LargeObjectSpaceObjectIterator::Next(), v8::internal::PagedSpaceObjectIterator::Next(), v8::internal::OLD_SPACE, RCS_SCOPE, ReachedHeapLimit(), v8::internal::anonymous_namespace{heap.cc}::ReportDuplicates(), space(), v8::internal::v8_flags, and v8::internal::HeapProfiler::WriteSnapshotToDiskAfterGC().
Referenced by AllocateExternalBackingStore(), v8::internal::BackgroundMergeTask::BeginMergeInBackground(), v8::internal::HeapAllocator::CollectAllAvailableGarbage(), CollectGarbageWithRetry(), v8::internal::SnapshotCreatorImpl::CreateBlob(), v8::internal::HeapSnapshotGenerator::GenerateSnapshot(), v8::internal::HeapProfiler::GetDetachedJSWrapperObjects(), v8::Isolate::LowMemoryNotification(), v8::internal::HeapProfiler::QueryObjects(), v8::Shell::RunMain(), and v8::internal::Snapshot::SerializeDeserializeAndVerifyForTesting().
CollectAllGarbage()
void v8::internal::Heap::CollectAllGarbage (GCFlags gc_flags, GarbageCollectionReason gc_reason, const GCCallbackFlags gc_callback_flags = kNoGCCallbackFlags)
Definition at line 1267 of file heap.cc.
                                                                        {
  current_gc_flags_ = gc_flags;
  CollectGarbage(OLD_SPACE, gc_reason, gc_callback_flags);
  DCHECK_EQ(GCFlags(GCFlag::kNoFlags), current_gc_flags_);
}
References CollectGarbage(), current_gc_flags_, DCHECK_EQ, v8::internal::kNoFlags, and v8::internal::OLD_SPACE.
Referenced by CheckCollectionRequested(), v8::internal::CppHeap::CollectGarbage(), CollectGarbageFromAnyThread(), CollectGarbageOnMemoryPressure(), FinalizeIncrementalMarkingAtomically(), v8::internal::SamplingHeapProfiler::GetAllocationProfile(), v8::internal::Debug::GetLoadedScripts(), HandleExternalMemoryInterrupt(), HandleGCRequest(), v8::internal::Deoptimizer::MaterializeHeapObjects(), PreciseCollectAllGarbage(), v8::internal::anonymous_namespace{objects.cc}::RehashObjectHashTableAndGCIfNeeded(), and v8::internal::Isolate::StackOverflow().
CollectCodeStatistics()
void v8::internal::Heap::CollectCodeStatistics ()
Definition at line 4447 of file heap.cc.
                                 {
  TRACE_EVENT0("v8", "Heap::CollectCodeStatistics");
  SafepointScope safepoint_scope(isolate(),
                                 kGlobalSafepointForSharedSpaceIsolate);
  MakeHeapIterable();
  CodeStatistics::ResetCodeAndMetadataStatistics(isolate());
  // We do not look for code in new space, or map space. If code
  // somehow ends up in those spaces, we would miss it here.
  CodeStatistics::CollectCodeStatistics(code_space_, isolate());
  CodeStatistics::CollectCodeStatistics(old_space_, isolate());
  CodeStatistics::CollectCodeStatistics(code_lo_space_, isolate());
  CodeStatistics::CollectCodeStatistics(trusted_space_, isolate());
  CodeStatistics::CollectCodeStatistics(trusted_lo_space_, isolate());
}
References code_lo_space_, code_space_, v8::internal::CodeStatistics::CollectCodeStatistics(), isolate(), v8::internal::kGlobalSafepointForSharedSpaceIsolate, MakeHeapIterable(), old_space_, v8::internal::CodeStatistics::ResetCodeAndMetadataStatistics(), TRACE_EVENT0, trusted_lo_space_, and trusted_space_.
Referenced by v8::Isolate::GetHeapCodeAndMetadataStatistics().
CollectGarbage()
void v8::internal::Heap::CollectGarbage (AllocationSpace space, GarbageCollectionReason gc_reason, const GCCallbackFlags gc_callback_flags = kNoGCCallbackFlags, PerformHeapLimitCheck check_heap_limit_reached = PerformHeapLimitCheck::kYes)
Definition at line 1595 of file heap.cc.
                                                                          {
  CHECK(isolate_->IsOnCentralStack());
  DCHECK_EQ(Isolate::TryGetCurrent(), isolate_);
  DCHECK_EQ(resize_new_space_mode_, ResizeNewSpaceMode::kNone);
  if (V8_UNLIKELY(!deserialization_complete_)) {
    // During isolate initialization heap always grows. GC is only requested
    // if a new page allocation fails. In such a case we should crash with
    // an out-of-memory instead of performing GC because the prologue/epilogue
    // callbacks may see objects that are not yet deserialized.
    CHECK(always_allocate());
    FatalProcessOutOfMemory("GC during deserialization");
  }
  // CollectGarbage consists of three parts:
  // 1. The prologue part which may execute callbacks. These callbacks may
  // allocate and trigger another garbage collection.
  // 2. The main garbage collection phase.
  // 3. The epilogue part which may execute callbacks. These callbacks may
  // allocate and trigger another garbage collection
  // Part 1: Invoke all callbacks which should happen before the actual garbage
  // collection is triggered. Note that these callbacks may trigger another
  // garbage collection since they may allocate.
  // JS execution is not allowed in any of the callbacks.
  DisallowJavascriptExecution no_js(isolate());
  // Some custom flushing (currently: FlushBytecodeFromSFI) can create
  // fresh TrustedPointerTableEntries during GC. These must not be affected
  // by an active TrustedPointerPublishingScope, so disable any such scope.
  DisableTrustedPointerPublishingScope no_trusted_pointer_tracking(isolate());
  DCHECK(AllowGarbageCollection::IsAllowed());
  // TODO(chromium:1523607): Ensure this for standalone cppgc as well.
  CHECK_IMPLIES(!v8_flags.allow_allocation_in_fast_api_call,
                !isolate()->InFastCCall());
  const char* collector_reason = nullptr;
  const GarbageCollector collector =
      SelectGarbageCollector(space, gc_reason, &collector_reason);
  current_or_last_garbage_collector_ = collector;
  DCHECK_IMPLIES(v8_flags.minor_ms && IsYoungGenerationCollector(collector),
                 !ShouldReduceMemory());
  if (collector == GarbageCollector::MARK_COMPACTOR &&
      incremental_marking()->IsMinorMarking()) {
    const GCFlags gc_flags = current_gc_flags_;
    // Minor GCs should not be memory reducing.
    current_gc_flags_ &= ~GCFlag::kReduceMemoryFootprint;
    CollectGarbage(NEW_SPACE,
                   GarbageCollectionReason::kFinalizeMinorMSForMajorGC);
    current_gc_flags_ = gc_flags;
  }
  const GCType gc_type = GetGCTypeFromGarbageCollector(collector);
  // Prologue callbacks. These callbacks may trigger GC themselves and thus
  // cannot be related exactly to garbage collection cycles.
  //
  // GCTracer scopes are managed by callees.
  InvokeExternalCallbacks(isolate(), [this, gc_callback_flags, gc_type]() {
    // Ensure that all pending phantom callbacks are invoked.
    isolate()->global_handles()->InvokeSecondPassPhantomCallbacks();
    // Prologue callbacks registered with Heap.
    CallGCPrologueCallbacks(gc_type, gc_callback_flags,
                            GCTracer::Scope::HEAP_EXTERNAL_PROLOGUE);
  });
  // The main garbage collection phase.
  //
  // We need a stack marker at the top of all entry points to allow
  // deterministic passes over the stack. E.g., a verifier that should only
  // find a subset of references of the marker.
  //
  // TODO(chromium:1056170): Consider adding a component that keeps track
  // of relevant GC stack regions where interesting pointers can be found.
  stack().SetMarkerIfNeededAndCallback([this, collector, gc_reason,
                                        collector_reason, gc_callback_flags]() {
    DisallowGarbageCollection no_gc_during_gc;
    size_t committed_memory_before =
        collector == GarbageCollector::MARK_COMPACTOR
            ? CommittedOldGenerationMemory()
            : 0;
    tracer()->StartObservablePause(base::TimeTicks::Now());
    VMState<GC> state(isolate());
    DevToolsTraceEventScope devtools_trace_event_scope(
        this, IsYoungGenerationCollector(collector) ? "MinorGC" : "MajorGC",
        ToString(gc_reason));
    GarbageCollectionPrologue(gc_reason, gc_callback_flags);
    {
      GCTracer::RecordGCPhasesInfo record_gc_phases_info(this, collector,
                                                         gc_reason);
      std::optional<TimedHistogramScope> histogram_timer_scope;
      std::optional<OptionalTimedHistogramScope> histogram_timer_priority_scope;
      TRACE_EVENT0("v8", record_gc_phases_info.trace_event_name());
      if (record_gc_phases_info.type_timer()) {
        histogram_timer_scope.emplace(record_gc_phases_info.type_timer(),
                                      isolate_);
      }
      if (record_gc_phases_info.type_priority_timer()) {
        histogram_timer_priority_scope.emplace(
            record_gc_phases_info.type_priority_timer(), isolate_,
            OptionalTimedHistogramScopeMode::TAKE_TIME);
      }
      PerformGarbageCollection(collector, gc_reason, collector_reason);
      // Clear flags describing the current GC now that the current GC is
      // complete. Do this before GarbageCollectionEpilogue() since that could
      // trigger another unforced GC.
      is_current_gc_forced_ = false;
      is_current_gc_for_heap_profiler_ = false;
      if (collector == GarbageCollector::MARK_COMPACTOR ||
          collector == GarbageCollector::SCAVENGER) {
        tracer()->RecordGCPhasesHistograms(record_gc_phases_info.mode());
      }
      if ((collector == GarbageCollector::MARK_COMPACTOR ||
           collector == GarbageCollector::MINOR_MARK_SWEEPER) &&
          cpp_heap()) {
        CppHeap::From(cpp_heap())->FinishAtomicSweepingIfRunning();
      }
    }
    GarbageCollectionEpilogue(collector);
    if (collector == GarbageCollector::MARK_COMPACTOR &&
        v8_flags.track_detached_contexts) {
      isolate()->CheckDetachedContextsAfterGC();
    }
    if (collector == GarbageCollector::MARK_COMPACTOR) {
      if (memory_reducer_ != nullptr) {
        memory_reducer_->NotifyMarkCompact(committed_memory_before);
      }
      if (initial_max_old_generation_size_ < max_old_generation_size() &&
          OldGenerationSizeOfObjects() <
              initial_max_old_generation_size_threshold_) {
        SetOldGenerationAndGlobalMaximumSize(initial_max_old_generation_size_);
      }
    }
    tracer()->StopAtomicPause();
    tracer()->StopObservablePause(collector, base::TimeTicks::Now());
    // Young generation cycles finish atomically. It is important that
    // StopObservablePause, and StopCycle are called in this
    // order; the latter may replace the current event with that of an
    // interrupted full cycle.
    if (IsYoungGenerationCollector(collector)) {
      tracer()->StopYoungCycleIfFinished();
    } else {
      tracer()->StopFullCycleIfFinished();
    }
    RecomputeLimits(collector, base::TimeTicks::Now());
  });
  if ((collector == GarbageCollector::MARK_COMPACTOR) &&
      is_full_gc_during_loading_) {
    if (ShouldOptimizeForLoadTime()) {
      update_allocation_limits_after_loading_ = true;
    }
    is_full_gc_during_loading_ = false;
  }
  // Epilogue callbacks. These callbacks may trigger GC themselves and thus
  // cannot be related exactly to garbage collection cycles.
  //
  // GCTracer scopes are managed by callees.
  InvokeExternalCallbacks(isolate(), [this, gc_callback_flags, gc_type]() {
    // Epilogue callbacks registered with Heap.
    CallGCEpilogueCallbacks(gc_type, gc_callback_flags,
                            GCTracer::Scope::HEAP_EXTERNAL_EPILOGUE);
    isolate()->global_handles()->PostGarbageCollectionProcessing(
        gc_callback_flags);
  });
  if (collector == GarbageCollector::MARK_COMPACTOR) {
    if ((gc_callback_flags &
         (kGCCallbackFlagForced | kGCCallbackFlagCollectAllAvailableGarbage))) {
      isolate()->CountUsage(v8::Isolate::kForcedGC);
    }
    if (v8_flags.heap_snapshot_on_gc > 0 &&
        static_cast<size_t>(v8_flags.heap_snapshot_on_gc) == ms_count_) {
      heap_profiler()->WriteSnapshotToDiskAfterGC();
    }
  } else {
    // Start incremental marking for the next cycle. We do this only for
    // minor GCs to avoid a loop where mark-compact causes another mark-compact.
    StartIncrementalMarkingIfAllocationLimitIsReached(
        main_thread_local_heap(), GCFlagsForIncrementalMarking(),
        kGCCallbackScheduleIdleGarbageCollection);
    if (v8_flags.minor_ms &&
        (gc_reason != GarbageCollectionReason::kFinalizeMinorMSForMajorGC)) {
      StartMinorMSConcurrentMarkingIfNeeded();
    }
  }
  if (perform_heap_limit_check == PerformHeapLimitCheck::kYes) {
    CheckHeapLimitReached();
  }
  if (collector == GarbageCollector::MARK_COMPACTOR) {
    current_gc_flags_ = GCFlag::kNoFlags;
  }
}
References always_allocate(), CallGCEpilogueCallbacks(), CallGCPrologueCallbacks(), CHECK, CHECK_IMPLIES, v8::internal::Isolate::CheckDetachedContextsAfterGC(), CheckHeapLimitReached(), CommittedOldGenerationMemory(), v8::internal::Isolate::CountUsage(), cpp_heap(), current_gc_flags_, current_or_last_garbage_collector_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, deserialization_complete_, FatalProcessOutOfMemory(), v8::internal::CppHeap::FinishAtomicSweepingIfRunning(), v8::internal::CppHeap::From(), GarbageCollectionEpilogue(), GarbageCollectionPrologue(), GCFlagsForIncrementalMarking(), v8::internal::GetGCTypeFromGarbageCollector(), v8::internal::Isolate::global_handles(), heap_profiler(), incremental_marking(), initial_max_old_generation_size_, initial_max_old_generation_size_threshold_, v8::internal::anonymous_namespace{heap.cc}::InvokeExternalCallbacks(), v8::internal::GlobalHandles::InvokeSecondPassPhantomCallbacks(), is_current_gc_for_heap_profiler_, is_current_gc_forced_, is_full_gc_during_loading_, isolate(), isolate_, v8::internal::Isolate::IsOnCentralStack(), IsYoungGenerationCollector(), v8::internal::kFinalizeMinorMSForMajorGC, v8::Isolate::kForcedGC, v8::kGCCallbackFlagCollectAllAvailableGarbage, v8::kGCCallbackFlagForced, v8::kGCCallbackScheduleIdleGarbageCollection, v8::internal::kNoFlags, kNone, v8::internal::kYes, main_thread_local_heap(), v8::internal::MARK_COMPACTOR, max_old_generation_size(), memory_reducer_, v8::internal::MINOR_MARK_SWEEPER, v8::internal::GCTracer::RecordGCPhasesInfo::mode(), ms_count_, v8::internal::NEW_SPACE, v8::base::TimeTicks::Now(), OldGenerationSizeOfObjects(), PerformGarbageCollection(), v8::internal::GlobalHandles::PostGarbageCollectionProcessing(), RecomputeLimits(), v8::internal::GCTracer::RecordGCPhasesHistograms(), resize_new_space_mode_, v8::internal::SCAVENGER, SelectGarbageCollector(), heap::base::Stack::SetMarkerIfNeededAndCallback(), SetOldGenerationAndGlobalMaximumSize(), ShouldOptimizeForLoadTime(), ShouldReduceMemory(), space(), stack(), StartIncrementalMarkingIfAllocationLimitIsReached(), StartMinorMSConcurrentMarkingIfNeeded(), v8::internal::GCTracer::StartObservablePause(), v8::internal::GCTracer::StopAtomicPause(), v8::internal::GCTracer::StopFullCycleIfFinished(), v8::internal::GCTracer::StopObservablePause(), v8::internal::GCTracer::StopYoungCycleIfFinished(), v8::internal::TAKE_TIME, v8::internal::ToString(), TRACE_EVENT0, v8::internal::GCTracer::RecordGCPhasesInfo::trace_event_name(), tracer(), v8::Isolate::TryGetCurrent(), v8::internal::GCTracer::RecordGCPhasesInfo::type_priority_timer(), v8::internal::GCTracer::RecordGCPhasesInfo::type_timer(), update_allocation_limits_after_loading_, v8::internal::v8_flags, V8_UNLIKELY, and v8::internal::HeapProfiler::WriteSnapshotToDiskAfterGC().
Referenced by AllocateExternalBackingStore(), CollectAllAvailableGarbage(), CollectAllGarbage(), v8::internal::HeapAllocator::CollectGarbage(), CollectGarbageWithRetry(), HandleGCRequest(), and StartTearDown().
CollectGarbageForBackground()
void v8::internal::Heap::CollectGarbageForBackground (LocalHeap * local_heap)
Definition at line 2232 of file heap.cc.
                                                            {
  CHECK(local_heap->is_main_thread());
  CollectGarbageWithRetry(OLD_SPACE, current_gc_flags_,
                          GarbageCollectionReason::kBackgroundAllocationFailure,
                          current_gc_callback_flags_);
}
References CHECK, CollectGarbageWithRetry(), current_gc_callback_flags_, current_gc_flags_, v8::internal::LocalHeap::is_main_thread(), v8::internal::kBackgroundAllocationFailure, and v8::internal::OLD_SPACE.
Referenced by v8::internal::LocalHeap::ParkSlowPath(), v8::internal::LocalHeap::SafepointSlowPath(), and v8::internal::LocalHeap::UnparkSlowPath().
CollectGarbageFromAnyThread()
bool v8::internal::Heap::CollectGarbageFromAnyThread (LocalHeap * local_heap, GarbageCollectionReason gc_reason = GarbageCollectionReason::kBackgroundAllocationFailure)
Definition at line 2498 of file heap.cc.
                                                                          {
  DCHECK(local_heap->IsRunning());
  if (isolate() == local_heap->heap()->isolate() &&
      local_heap->is_main_thread()) {
    CollectAllGarbage(current_gc_flags_, gc_reason, current_gc_callback_flags_);
    return true;
  } else {
    if (!collection_barrier_->TryRequestGC()) return false;
    const LocalHeap::ThreadState old_state =
        main_thread_local_heap()->state_.SetCollectionRequested();
    if (old_state.IsRunning()) {
      const bool performed_gc =
          collection_barrier_->AwaitCollectionBackground(local_heap);
      return performed_gc;
    } else {
      DCHECK(old_state.IsParked());
      return false;
    }
  }
}
References CollectAllGarbage(), collection_barrier_, current_gc_callback_flags_, current_gc_flags_, v8::internal::DCHECK(), v8::internal::LocalHeap::heap(), v8::internal::LocalHeap::is_main_thread(), isolate(), v8::internal::LocalHeap::ThreadState::IsParked(), v8::internal::LocalHeap::IsRunning(), v8::internal::LocalHeap::ThreadState::IsRunning(), main_thread_local_heap(), v8::internal::LocalHeap::AtomicThreadState::SetCollectionRequested(), and v8::internal::LocalHeap::state_.
Referenced by v8::internal::HeapAllocator::CollectAllAvailableGarbage(), v8::internal::HeapAllocator::CollectGarbage(), and CollectGarbageShared().
CollectGarbageOnMemoryPressure()
void v8::internal::Heap::CollectGarbageOnMemoryPressure () [private]
Definition at line 4294 of file heap.cc.
                                          {
  const int kGarbageThresholdInBytes = 8 * MB;
  const double kGarbageThresholdAsFractionOfTotalMemory = 0.1;
  // This constant is the maximum response time in RAIL performance model.
  const double kMaxMemoryPressurePauseMs = 100;
  double start = MonotonicallyIncreasingTimeInMs();
  CollectAllGarbage(GCFlag::kReduceMemoryFootprint,
                    GarbageCollectionReason::kMemoryPressure,
                    kGCCallbackFlagCollectAllAvailableGarbage);
  EagerlyFreeExternalMemoryAndWasmCode();
  double end = MonotonicallyIncreasingTimeInMs();
  // Estimate how much memory we can free.
  int64_t potential_garbage =
      (CommittedMemory() - SizeOfObjects()) + external_memory();
  // If we can potentially free large amount of memory, then start GC right
  // away instead of waiting for memory reducer.
  if (potential_garbage >= kGarbageThresholdInBytes &&
      potential_garbage >=
          CommittedMemory() * kGarbageThresholdAsFractionOfTotalMemory) {
    // If we spent less than half of the time budget, then perform full GC
    // Otherwise, start incremental marking.
    if (end - start < kMaxMemoryPressurePauseMs / 2) {
      CollectAllGarbage(GCFlag::kReduceMemoryFootprint,
                        GarbageCollectionReason::kMemoryPressure,
                        kGCCallbackFlagCollectAllAvailableGarbage);
    } else {
      if (v8_flags.incremental_marking && incremental_marking()->IsStopped()) {
        StartIncrementalMarking(GCFlag::kReduceMemoryFootprint,
                                GarbageCollectionReason::kMemoryPressure);
      }
    }
  }
}
References CollectAllGarbage(), CommittedMemory(), EagerlyFreeExternalMemoryAndWasmCode(), v8::internal::compiler::end(), external_memory(), incremental_marking(), v8::kGCCallbackFlagCollectAllAvailableGarbage, v8::internal::kMemoryPressure, v8::internal::kReduceMemoryFootprint, v8::internal::MB, MonotonicallyIncreasingTimeInMs(), SizeOfObjects(), StartIncrementalMarking(), and v8::internal::v8_flags.
Referenced by CheckMemoryPressure().
CollectGarbageShared()
bool v8::internal::Heap::CollectGarbageShared (LocalHeap * local_heap, GarbageCollectionReason gc_reason)
Definition at line 2484 of file heap.cc.
                                                                   {
  DCHECK(isolate()->has_shared_space());
  if (V8_UNLIKELY(!deserialization_complete_)) {
    CHECK(always_allocate());
    FatalProcessOutOfMemory("GC during deserialization");
  }
  Isolate* shared_space_isolate = isolate()->shared_space_isolate();
  return shared_space_isolate->heap()->CollectGarbageFromAnyThread(local_heap,
                                                                   gc_reason);
}
References always_allocate(), CHECK, CollectGarbageFromAnyThread(), v8::internal::DCHECK(), deserialization_complete_, FatalProcessOutOfMemory(), v8::internal::Isolate::heap(), isolate(), v8::internal::Isolate::shared_space_isolate(), and V8_UNLIKELY.
Referenced by v8::internal::HeapAllocator::CollectAllAvailableGarbage(), and v8::internal::HeapAllocator::CollectGarbage().
CollectGarbageWithRetry()
void v8::internal::Heap::CollectGarbageWithRetry (AllocationSpace space, GCFlags gc_flags, GarbageCollectionReason gc_reason, const GCCallbackFlags gc_callback_flags)
Definition at line 2198 of file heap.cc.
                                                                            {
  const auto perform_heap_limit_check = v8_flags.late_heap_limit_check
                                            ? PerformHeapLimitCheck::kNo
                                            : PerformHeapLimitCheck::kYes;
  if (space == NEW_SPACE) {
    DCHECK_EQ(GCFlags(), gc_flags);
    for (int i = 0; i < 2; i++) {
      CollectGarbage(NEW_SPACE, gc_reason, gc_callback_flags,
                     perform_heap_limit_check);
      if (!ReachedHeapLimit()) {
        return;
      }
    }
  }
  for (int i = 0; i < 2; i++) {
    current_gc_flags_ = gc_flags;
    CollectGarbage(OLD_SPACE, gc_reason, gc_callback_flags,
                   perform_heap_limit_check);
    DCHECK_EQ(GCFlags(), current_gc_flags_);
    if (!ReachedHeapLimit()) {
      return;
    }
  }
  CollectAllAvailableGarbage(GarbageCollectionReason::kLastResort);
}
References CollectAllAvailableGarbage(), CollectGarbage(), current_gc_flags_, DCHECK_EQ, v8::internal::kLastResort, v8::internal::kNo, v8::internal::kYes, v8::internal::NEW_SPACE, v8::internal::OLD_SPACE, ReachedHeapLimit(), space(), and v8::internal::v8_flags.
Referenced by CollectGarbageForBackground().
CollectionRequested()
bool v8::internal::Heap::CollectionRequested ()
Definition at line 2194 of file heap.cc.
                               {
  return collection_barrier_->WasGCRequested();
}
References collection_barrier_.
Referenced by CheckCollectionRequested(), HandleGCRequest(), and ShouldExpandOldGenerationOnSlowAllocation().
CommittedMemory()
size_t v8::internal::Heap::CommittedMemory ()
Definition at line 364 of file heap.cc.
                             {
  if (!HasBeenSetUp()) return 0;
  size_t new_space_committed = new_space_ ? new_space_->CommittedMemory() : 0;
  size_t new_lo_space_committed = new_lo_space_ ? new_lo_space_->Size() : 0;
  return new_space_committed + new_lo_space_committed +
         CommittedOldGenerationMemory();
}
References CommittedOldGenerationMemory(), HasBeenSetUp(), new_lo_space_, new_space_, and v8::internal::LargeObjectSpace::Size().
Referenced by ActivateMemoryReducerIfNeededOnMainThread(), CollectGarbageOnMemoryPressure(), GarbageCollectionEpilogue(), PrintShortHeapStatistics(), and UpdateMaximumCommitted().
CommittedMemoryExecutable()
size_t v8::internal::Heap::CommittedMemoryExecutable ()
Definition at line 385 of file heap.cc.
                                       {
  if (!HasBeenSetUp()) return 0;
  return static_cast<size_t>(memory_allocator()->SizeExecutable());
}
References HasBeenSetUp(), memory_allocator(), and v8::internal::MemoryAllocator::SizeExecutable().
CommittedOldGenerationMemory()
size_t v8::internal::Heap::CommittedOldGenerationMemory ()
Definition at line 348 of file heap.cc.
                                          {
  if (!HasBeenSetUp()) return 0;
  PagedSpaceIterator spaces(this);
  size_t total = 0;
  for (PagedSpace* space = spaces.Next(); space != nullptr;
       space = spaces.Next()) {
    total += space->CommittedMemory();
  }
  if (shared_lo_space_) {
    total += shared_lo_space_->Size();
  }
  return total + lo_space_->Size() + code_lo_space_->Size() +
         trusted_lo_space_->Size();
}
References code_lo_space_, v8::internal::BaseSpace::CommittedMemory(), HasBeenSetUp(), lo_space_, v8::internal::PagedSpaceIterator::Next(), shared_lo_space_, v8::internal::LargeObjectSpace::Size(), space(), and trusted_lo_space_.
Referenced by CollectGarbage(), CommittedMemory(), HasHighFragmentation(), and v8::internal::MemoryReducer::NotifyMarkCompact().
CommittedPhysicalMemory()
size_t v8::internal::Heap::CommittedPhysicalMemory ()
Definition at line 374 of file heap.cc.
                                     {
  if (!HasBeenSetUp()) return 0;
  size_t total = 0;
  for (SpaceIterator it(this); it.HasNext();) {
    total += it.Next()->CommittedPhysicalMemory();
  }
  return total;
}
References HasBeenSetUp(), and v8::internal::SpaceIterator::HasNext().
CompactRetainedMaps()
void v8::internal::Heap::CompactRetainedMaps (Tagged< WeakArrayList > retained_maps) [private]
Definition at line 6557 of file heap.cc.
                                                                  {
  int length = retained_maps->length();
  int new_length = 0;
  // This loop compacts the array by removing cleared weak cells.
  for (int i = 0; i < length; i += kRetainMapEntrySize) {
    Tagged<MaybeObject> maybe_object = retained_maps->Get(i);
    if (maybe_object.IsCleared()) {
      continue;
    }
    DCHECK(maybe_object.IsWeak());
    Tagged<MaybeObject> age = retained_maps->Get(i + 1);
    DCHECK(IsSmi(age));
    if (i != new_length) {
      retained_maps->Set(new_length, maybe_object);
      retained_maps->Set(new_length + 1, age);
    }
    new_length += kRetainMapEntrySize;
  }
  Tagged<HeapObject> undefined = ReadOnlyRoots(this).undefined_value();
  for (int i = new_length; i < length; i++) {
    retained_maps->Set(i, undefined);
  }
  if (new_length != length) retained_maps->set_length(new_length);
}
References v8::internal::DCHECK(), v8::internal::TaggedImpl< kRefType, StorageType >::IsCleared(), v8::internal::IsSmi(), v8::internal::TaggedImpl< kRefType, StorageType >::IsWeak(), kRetainMapEntrySize, v8::internal::length, ReadOnlyRoots, and v8::internal::undefined.
Referenced by AddRetainedMaps().
CompactWeakArrayLists()
void v8::internal::Heap::CompactWeakArrayLists ()
Definition at line 6488 of file heap.cc.
                                 {
  // Find known PrototypeUsers and compact them.
  std::vector<Handle<PrototypeInfo>> prototype_infos;
  {
    HeapObjectIterator iterator(this);
    for (Tagged<HeapObject> o = iterator.Next(); !o.is_null();
         o = iterator.Next()) {
      if (IsPrototypeInfo(*o)) {
        Tagged<PrototypeInfo> prototype_info = Cast<PrototypeInfo>(o);
        if (IsWeakArrayList(prototype_info->prototype_users())) {
          prototype_infos.emplace_back(handle(prototype_info, isolate()));
        }
      }
    }
  }
  for (auto& prototype_info : prototype_infos) {
    DirectHandle<WeakArrayList> array(
        Cast<WeakArrayList>(prototype_info->prototype_users()), isolate());
    DCHECK(InOldSpace(*array) ||
           *array == ReadOnlyRoots(this).empty_weak_array_list());
    Tagged<WeakArrayList> new_array = PrototypeUsers::Compact(
        array, this, JSObject::PrototypeRegistryCompactionCallback,
        AllocationType::kOld);
    prototype_info->set_prototype_users(new_array);
  }
  // Find known WeakArrayLists and compact them.
  Handle<WeakArrayList> scripts(script_list(), isolate());
  DCHECK(InOldSpace(*scripts));
  scripts = CompactWeakArrayList(this, scripts, AllocationType::kOld);
  set_script_list(*scripts);
}
References v8::internal::PrototypeUsers::Compact(), v8::internal::anonymous_namespace{heap.cc}::CompactWeakArrayList(), v8::internal::DCHECK(), v8::internal::handle(), InOldSpace(), v8::internal::Tagged< HeapObject >::is_null(), isolate(), v8::internal::kOld, v8::internal::HeapObjectIterator::Next(), v8::internal::JSObject::PrototypeRegistryCompactionCallback(), and ReadOnlyRoots.
Referenced by v8::internal::SnapshotCreatorImpl::CreateBlob().
CompleteSweepingFull()
void v8::internal::Heap::CompleteSweepingFull ()
Definition at line 2022 of file heap.cc.
                                {
  EnsureSweepingCompleted(SweepingForcedFinalizationMode::kUnifiedHeap);
  DCHECK(!sweeping_in_progress());
  DCHECK_IMPLIES(cpp_heap(),
                 !CppHeap::From(cpp_heap())->sweeper().IsSweepingInProgress());
  DCHECK(!tracer()->IsSweepingInProgress());
}
References cpp_heap(), v8::internal::DCHECK(), DCHECK_IMPLIES, EnsureSweepingCompleted(), v8::internal::CppHeap::From(), kUnifiedHeap, sweeper(), sweeping_in_progress(), and tracer().
Referenced by v8::internal::HeapSnapshotGenerator::GenerateSnapshot(), PerformGarbageCollection(), StartIncrementalMarking(), and StartTearDown().
CompleteSweepingYoung()
void v8::internal::Heap::CompleteSweepingYoung ()
Definition at line 2523 of file heap.cc.
                                 {
  DCHECK(!v8_flags.sticky_mark_bits);
  // If sweeping is in progress and there are no sweeper tasks running, finish
  // the sweeping here, to avoid having to pause and resume during the young
  // generation GC.
  FinishSweepingIfOutOfWork();
  EnsureYoungSweepingCompleted();
#if defined(CPPGC_YOUNG_GENERATION)
  // Always complete sweeping if young generation is enabled.
  if (cpp_heap()) {
    if (auto* iheap = CppHeap::From(cpp_heap());
        iheap->generational_gc_supported())
      iheap->FinishSweepingIfRunning();
  }
#endif // defined(CPPGC_YOUNG_GENERATION)
}
References cpp_heap(), v8::internal::DCHECK(), EnsureYoungSweepingCompleted(), FinishSweepingIfOutOfWork(), v8::internal::CppHeap::From(), cppgc::internal::HeapBase::generational_gc_supported(), and v8::internal::v8_flags.
Referenced by PerformGarbageCollection(), and StartIncrementalMarking().
ComputeMutatorUtilization()
double v8::internal::Heap::ComputeMutatorUtilization (const char * tag, double mutator_speed, std::optional< double > gc_speed) [private]
Definition at line 3804 of file heap.cc.
                                                                     {
  double result = ComputeMutatorUtilizationImpl(mutator_speed, gc_speed);
  if (v8_flags.trace_mutator_utilization) {
    isolate()->PrintWithTimestamp(
        "%s mutator utilization = %.3f ("
        "mutator_speed=%.f, gc_speed=%.f)\n",
        tag, result, mutator_speed, gc_speed.value_or(0));
  }
  return result;
}
References v8::internal::anonymous_namespace{heap.cc}::ComputeMutatorUtilizationImpl(), isolate(), v8::base::internal::result, and v8::internal::v8_flags.
Referenced by HasLowEmbedderAllocationRate(), HasLowOldGenerationAllocationRate(), and HasLowYoungGenerationAllocationRate().
ComputeNewAllocationLimits()
Heap::LimitsCompuatationResult v8::internal::Heap::ComputeNewAllocationLimits (Heap * heap) [static], [private]
Definition at line 2561 of file heap.cc.
                                                                        {
  DCHECK(!heap->using_initial_limit());
  heap->tracer()->RecordGCSizeCounters();
  const HeapGrowingMode mode = heap->CurrentHeapGrowingMode();
  std::optional<double> v8_gc_speed =
      heap->tracer()->OldGenerationSpeedInBytesPerMillisecond();
  double v8_mutator_speed =
      heap->tracer()->OldGenerationAllocationThroughputInBytesPerMillisecond();
  double v8_growing_factor = MemoryController<V8HeapTrait>::GrowingFactor(
      heap, heap->max_old_generation_size(), v8_gc_speed, v8_mutator_speed,
      mode);
  std::optional<double> embedder_gc_speed =
      heap->tracer()->EmbedderSpeedInBytesPerMillisecond();
  double embedder_speed =
      heap->tracer()->EmbedderAllocationThroughputInBytesPerMillisecond();
  double embedder_growing_factor =
      (embedder_gc_speed.has_value() && embedder_speed > 0)
          ? MemoryController<GlobalMemoryTrait>::GrowingFactor(
                heap, heap->max_global_memory_size_, embedder_gc_speed,
                embedder_speed, mode)
          : 0;
  size_t new_space_capacity = heap->NewSpaceTargetCapacity();
  size_t new_old_generation_allocation_limit =
      MemoryController<V8HeapTrait>::BoundAllocationLimit(
          heap, heap->OldGenerationConsumedBytesAtLastGC(),
          heap->OldGenerationConsumedBytesAtLastGC() * v8_growing_factor,
          heap->min_old_generation_size_, heap->max_old_generation_size(),
          new_space_capacity, mode);
  double global_growing_factor =
      std::max(v8_growing_factor, embedder_growing_factor);
  double external_growing_factor = std::min(
      global_growing_factor, GlobalMemoryTrait::kConservativeGrowingFactor);
  DCHECK_GT(global_growing_factor, 0);
  DCHECK_GT(external_growing_factor, 0);
  size_t new_global_allocation_limit =
      MemoryController<GlobalMemoryTrait>::BoundAllocationLimit(
          heap, heap->GlobalConsumedBytesAtLastGC(),
          (heap->OldGenerationConsumedBytesAtLastGC() +
           heap->embedder_size_at_last_gc_) *
                  global_growing_factor +
              (v8_flags.external_memory_accounted_in_global_limit
                   ? heap->external_memory_.low_since_mark_compact() *
                         external_growing_factor
                   : 0),
          heap->min_global_memory_size_, heap->max_global_memory_size_,
          new_space_capacity, mode);
  return {new_old_generation_allocation_limit, new_global_allocation_limit};
}
References v8::internal::MemoryController< Trait >::BoundAllocationLimit(), v8::internal::DCHECK(), DCHECK_GT, v8::internal::MemoryController< Trait >::GrowingFactor(), v8::internal::BaseControllerTrait::kConservativeGrowingFactor, mode(), and v8::internal::v8_flags.
Referenced by EnsureSweepingCompleted(), RecomputeLimits(), and RecomputeLimitsAfterLoadingIfNeeded().
concurrent_marking()
ConcurrentMarking* v8::internal::Heap::concurrent_marking () const [inline]
Definition at line 1125 of file heap.h.
                                                {
    return concurrent_marking_.get();
  }
Referenced by v8::internal::PagedNewSpaceAllocatorPolicy::EnsureAllocation(), v8::internal::IncrementalMarking::FetchBytesMarkedConcurrently(), v8::internal::MarkCompactCollector::FinishConcurrentMarking(), v8::internal::MinorMarkSweepCollector::FinishConcurrentMarking(), v8::internal::MinorMarkSweepCollector::MarkLiveObjects(), v8::internal::MarkCompactCollector::MaybeEnableBackgroundThreadsInCycle(), PauseConcurrentThreadsInClients(), v8::internal::IncrementalMarking::StartMarkingMajor(), v8::internal::IncrementalMarking::StartMarkingMinor(), StartTearDown(), v8::internal::IncrementalMarking::Step(), TearDown(), and v8::internal::MinorMarkSweepCollector::TearDown().
ConfigureHeap()
void v8::internal::Heap::ConfigureHeap (const v8::ResourceConstraints & constraints, v8::CppHeap * cpp_heap)
Definition at line 5109 of file heap.cc.
                                              {
  CHECK(!configured_);
  // Initialize max_semi_space_size_.
  {
    max_semi_space_size_ = DefaultMaxSemiSpaceSize();
    if (constraints.max_young_generation_size_in_bytes() > 0) {
      max_semi_space_size_ = SemiSpaceSizeFromYoungGenerationSize(
          constraints.max_young_generation_size_in_bytes());
    }
    if (v8_flags.max_semi_space_size > 0) {
      max_semi_space_size_ =
          static_cast<size_t>(v8_flags.max_semi_space_size) * MB;
    } else if (v8_flags.max_heap_size > 0) {
      size_t max_heap_size = static_cast<size_t>(v8_flags.max_heap_size) * MB;
      size_t young_generation_size, old_generation_size;
      if (v8_flags.max_old_space_size > 0) {
        old_generation_size =
            static_cast<size_t>(v8_flags.max_old_space_size) * MB;
        young_generation_size = max_heap_size > old_generation_size
                                    ? max_heap_size - old_generation_size
                                    : 0;
      } else {
        GenerationSizesFromHeapSize(max_heap_size, &young_generation_size,
                                    &old_generation_size);
      }
      max_semi_space_size_ =
          SemiSpaceSizeFromYoungGenerationSize(young_generation_size);
    }
    if (v8_flags.stress_compaction) {
      // This will cause more frequent GCs when stressing.
      max_semi_space_size_ = MB;
    }
    if (!v8_flags.minor_ms) {
      // TODO(dinfuehr): Rounding to a power of 2 is technically no longer
      // needed but yields best performance on Pixel2.
      max_semi_space_size_ =
          static_cast<size_t>(base::bits::RoundUpToPowerOfTwo64(
              static_cast<uint64_t>(max_semi_space_size_)));
    }
    max_semi_space_size_ =
        std::max(max_semi_space_size_, DefaultMinSemiSpaceSize());
    max_semi_space_size_ =
        RoundDown<PageMetadata::kPageSize>(max_semi_space_size_);
  }
  // Initialize max_old_generation_size_ and max_global_memory_.
  {
    size_t max_old_generation_size = 700ul * (kSystemPointerSize / 4) * MB;
    if (constraints.max_old_generation_size_in_bytes() > 0) {
      max_old_generation_size = constraints.max_old_generation_size_in_bytes();
    }
    if (v8_flags.max_old_space_size > 0) {
      max_old_generation_size =
          static_cast<size_t>(v8_flags.max_old_space_size) * MB;
    } else if (v8_flags.max_heap_size > 0) {
      size_t max_heap_size = static_cast<size_t>(v8_flags.max_heap_size) * MB;
      size_t young_generation_size =
          YoungGenerationSizeFromSemiSpaceSize(max_semi_space_size_);
      max_old_generation_size = max_heap_size > young_generation_size
                                    ? max_heap_size - young_generation_size
                                    : 0;
    }
    max_old_generation_size =
        std::max(max_old_generation_size, MinOldGenerationSize());
    max_old_generation_size = std::min(max_old_generation_size,
                                       AllocatorLimitOnMaxOldGenerationSize());
    max_old_generation_size =
        RoundDown<PageMetadata::kPageSize>(max_old_generation_size);
    SetOldGenerationAndGlobalMaximumSize(max_old_generation_size);
  }
  CHECK_IMPLIES(
      v8_flags.max_heap_size > 0,
      v8_flags.max_semi_space_size == 0 || v8_flags.max_old_space_size == 0);
  // Initialize min_semispace_size_.
  {
    min_semi_space_size_ = DefaultMinSemiSpaceSize();
    if (!v8_flags.optimize_for_size) {
      // Start with at least 1*MB semi-space on machines with a lot of memory.
      min_semi_space_size_ =
          std::max(min_semi_space_size_, static_cast<size_t>(1 * MB));
    }
    DCHECK_GE(min_semi_space_size_, DefaultMinSemiSpaceSize());
    if (v8_flags.min_semi_space_size > 0) {
      min_semi_space_size_ =
          static_cast<size_t>(v8_flags.min_semi_space_size) * MB;
    }
    min_semi_space_size_ = std::min(min_semi_space_size_, max_semi_space_size_);
    min_semi_space_size_ =
        RoundDown<PageMetadata::kPageSize>(min_semi_space_size_);
  }
  // Initialize initial_semispace_size_.
  {
    initial_semispace_size_ = min_semi_space_size_;
    if (constraints.initial_young_generation_size_in_bytes() > 0) {
      initial_semispace_size_ = SemiSpaceSizeFromYoungGenerationSize(
          constraints.initial_young_generation_size_in_bytes());
    }
    if (v8_flags.initial_heap_size > 0) {
      size_t young_generation, old_generation;
      Heap::GenerationSizesFromHeapSize(
          static_cast<size_t>(v8_flags.initial_heap_size) * MB,
          &young_generation, &old_generation);
      initial_semispace_size_ =
          SemiSpaceSizeFromYoungGenerationSize(young_generation);
    }
    initial_semispace_size_ =
        std::min(initial_semispace_size_, max_semi_space_size_);
    initial_semispace_size_ =
        std::max(initial_semispace_size_, min_semi_space_size_);
    initial_semispace_size_ =
        RoundDown<PageMetadata::kPageSize>(initial_semispace_size_);
  }
  DCHECK_LE(min_semi_space_size_, initial_semispace_size_);
  DCHECK_LE(initial_semispace_size_, max_semi_space_size_);
  if (v8_flags.lazy_new_space_shrinking) {
    initial_semispace_size_ = max_semi_space_size_;
  }
  // Initialize initial_old_space_size_.
  std::optional<size_t> initial_old_generation_size =
      [&]() -> std::optional<size_t> {
    if (v8_flags.initial_old_space_size > 0) {
      return static_cast<size_t>(v8_flags.initial_old_space_size) * MB;
    }
    if (v8_flags.initial_heap_size > 0) {
      size_t initial_heap_size =
          static_cast<size_t>(v8_flags.initial_heap_size) * MB;
      size_t young_generation_size =
          YoungGenerationSizeFromSemiSpaceSize(initial_semispace_size_);
      return initial_heap_size > young_generation_size
                 ? initial_heap_size - young_generation_size
                 : 0;
    }
    return std::nullopt;
  }();
  DCHECK(!preconfigured_old_generation_size_);
  if (initial_old_generation_size.has_value()) {
    initial_size_overwritten_ = true;
    initial_old_generation_size_ = *initial_old_generation_size;
  } else if (v8_flags.preconfigured_old_space_size > 0) {
    initial_size_overwritten_ = true;
    initial_old_generation_size_ =
        static_cast<size_t>(v8_flags.preconfigured_old_space_size) * MB;
    preconfigured_old_generation_size_ = true;
  } else {
    initial_old_generation_size_ = DefaultInitialOldGenerationSize();
    if (constraints.initial_old_generation_size_in_bytes() > 0) {
      initial_old_generation_size_ =
          constraints.initial_old_generation_size_in_bytes();
    }
  }
  initial_old_generation_size_ =
      std::min(initial_old_generation_size_, max_old_generation_size() / 2);
  initial_old_generation_size_ =
      RoundDown<PageMetadata::kPageSize>(initial_old_generation_size_);
  if (initial_size_overwritten_ && !preconfigured_old_generation_size_) {
    // If the embedder pre-configures the initial old generation size,
    // then allow V8 to skip full GCs below that threshold.
    min_old_generation_size_ = initial_old_generation_size_;
    min_global_memory_size_ =
        GlobalMemorySizeFromV8Size(min_old_generation_size_);
  }
  initial_max_old_generation_size_ = max_old_generation_size();
  ResetOldGenerationAndGlobalAllocationLimit();
  // We rely on being able to allocate new arrays in paged spaces.
  DCHECK(kMaxRegularHeapObjectSize >=
         (JSArray::kHeaderSize +
          FixedArray::SizeFor(JSArray::kInitialMaxFastElementArray) +
          ALIGN_TO_ALLOCATION_ALIGNMENT(sizeof(AllocationMemento))));
  code_range_size_ = constraints.code_range_size_in_bytes();
  heap_profiler_ = std::make_unique<HeapProfiler>(this);
  if (cpp_heap) {
    AttachCppHeap(cpp_heap);
    owning_cpp_heap_.reset(CppHeap::From(cpp_heap));
  }
  configured_ = true;
}
References ALIGN_TO_ALLOCATION_ALIGNMENT, AllocatorLimitOnMaxOldGenerationSize(), AttachCppHeap(), CHECK, CHECK_IMPLIES, code_range_size_, v8::ResourceConstraints::code_range_size_in_bytes(), configured_, cpp_heap(), v8::internal::DCHECK(), DCHECK_GE, DCHECK_LE, DefaultInitialOldGenerationSize(), DefaultMaxSemiSpaceSize(), DefaultMinSemiSpaceSize(), v8::internal::CppHeap::From(), GenerationSizesFromHeapSize(), v8::internal::anonymous_namespace{heap.cc}::GlobalMemorySizeFromV8Size(), heap_profiler_, initial_max_old_generation_size_, initial_old_generation_size_, v8::ResourceConstraints::initial_old_generation_size_in_bytes(), initial_semispace_size_, initial_size_overwritten_, v8::ResourceConstraints::initial_young_generation_size_in_bytes(), v8::internal::JSArray::kInitialMaxFastElementArray, v8::internal::kMaxRegularHeapObjectSize, v8::internal::kSystemPointerSize, max_old_generation_size(), v8::ResourceConstraints::max_old_generation_size_in_bytes(), max_semi_space_size_, v8::ResourceConstraints::max_young_generation_size_in_bytes(), v8::internal::MB, min_global_memory_size_, min_old_generation_size_, min_semi_space_size_, MinOldGenerationSize(), owning_cpp_heap_, preconfigured_old_generation_size_, ResetOldGenerationAndGlobalAllocationLimit(), v8::base::bits::RoundUpToPowerOfTwo64(), SemiSpaceSizeFromYoungGenerationSize(), SetOldGenerationAndGlobalMaximumSize(), v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::SizeFor(), v8::internal::v8_flags, and YoungGenerationSizeFromSemiSpaceSize().
Referenced by ConfigureHeapDefault(), v8::Isolate::Initialize(), and v8::internal::SnapshotCreatorImpl::SnapshotCreatorImpl().
ConfigureHeapDefault()
void v8::internal::Heap::ConfigureHeapDefault ()
Definition at line 5320 of file heap.cc.
                                {
  v8::ResourceConstraints constraints;
  ConfigureHeap(constraints, nullptr);
}
References ConfigureHeap().
Referenced by SetUp().
ConservativeStackScanningModeForMajorGC()
StackScanMode v8::internal::Heap::ConservativeStackScanningModeForMajorGC () const [inline]
Definition at line 387 of file heap.h.
                                                                {
    if (v8_flags.conservative_stack_scanning) {
      return StackScanMode::kFull;
    }
    if (selective_stack_scan_start_address_.has_value()) {
      return StackScanMode::kSelective;
    }
    return StackScanMode::kNone;
  }
References v8::internal::v8_flags.
Referenced by IterateConservativeStackRoots(), and v8::internal::MarkCompactCollector::StartCompaction().
ConservativeStackScanningModeForMinorGC()
StackScanMode v8::internal::Heap::ConservativeStackScanningModeForMinorGC () const [inline]
Definition at line 378 of file heap.h.
                                                                {
    if (v8_flags.scavenger_conservative_object_pinning) {
      return StackScanMode::kFull;
    }
    if (selective_stack_scan_start_address_.has_value()) {
      return StackScanMode::kSelective;
    }
    return StackScanMode::kNone;
  }
References v8::internal::v8_flags.
Referenced by v8::internal::ScavengerCollector::CollectGarbage(), and v8::internal::anonymous_namespace{scavenger.cc}::YoungGenerationConservativeStackVisitor::YoungGenerationConservativeStackVisitor().
Contains()
bool v8::internal::Heap::Contains (Tagged< HeapObject > value) const
Definition at line 4481 of file heap.cc.
                                                  {
  if (ReadOnlyHeap::Contains(value)) {
    return false;
  }
  if (memory_allocator()->IsOutsideAllocatedSpace(value.address())) {
    return false;
  }
  if (!HasBeenSetUp()) return false;
  return (new_space_ && new_space_->Contains(value)) ||
         old_space_->Contains(value) || code_space_->Contains(value) ||
         (shared_space_ && shared_space_->Contains(value)) ||
         (shared_trusted_space_ && shared_trusted_space_->Contains(value)) ||
         lo_space_->Contains(value) || code_lo_space_->Contains(value) ||
         (new_lo_space_ && new_lo_space_->Contains(value)) ||
         trusted_space_->Contains(value) ||
         trusted_lo_space_->Contains(value) ||
         (shared_lo_space_ && shared_lo_space_->Contains(value)) ||
         (shared_trusted_lo_space_ &&
          shared_trusted_lo_space_->Contains(value));
}
References code_lo_space_, code_space_, v8::internal::PagedSpaceBase::Contains(), v8::internal::ReadOnlyHeap::Contains(), v8::internal::LargeObjectSpace::Contains(), v8::internal::NewSpace::Contains(), HasBeenSetUp(), lo_space_, memory_allocator(), new_lo_space_, new_space_, old_space_, shared_lo_space_, shared_space_, shared_trusted_lo_space_, shared_trusted_space_, trusted_lo_space_, trusted_space_, and v8::internal::value.
Referenced by v8::internal::SnapshotCreatorImpl::AddContext(), v8::internal::SnapshotCreatorImpl::AddData(), v8::internal::MinorMarkSweepCollector::DrainMarkingWorklist(), v8::internal::MarkCompactCollector::MarkObject(), v8::internal::MarkCompactCollector::MarkRootObject(), and v8::internal::SnapshotCreatorImpl::SetDefaultContext().
ContainsCode()
bool v8::internal::Heap::ContainsCode (Tagged< HeapObject > value) const
Definition at line 4504 of file heap.cc.
                                                      {
  // TODO(v8:11880): support external code space.
  if (memory_allocator()->IsOutsideAllocatedSpace(value.address(),
                                                  EXECUTABLE)) {
    return false;
  }
  return HasBeenSetUp() &&
         (code_space_->Contains(value) || code_lo_space_->Contains(value));
}
References code_lo_space_, code_space_, v8::internal::PagedSpaceBase::Contains(), v8::internal::LargeObjectSpace::Contains(), v8::internal::EXECUTABLE, HasBeenSetUp(), memory_allocator(), and v8::internal::value.
CopyBlock()
void v8::internal::Heap::CopyBlock (Address dst, Address src, int byte_size) [inline], [static]
Definition at line 292 of file heap-inl.h.
                                                            {
  DCHECK(IsAligned(byte_size, kTaggedSize));
  CopyTagged(dst, src, static_cast<size_t>(byte_size / kTaggedSize));
}
References v8::internal::CopyTagged(), v8::internal::DCHECK(), IsAligned(), and v8::internal::kTaggedSize.
Referenced by v8::internal::Factory::CopyFixedDoubleArray(), v8::internal::Factory::CopyJSObjectWithAllocationSite(), v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::CopyToReadOnlyHeap(), v8::internal::Scavenger::MigrateObject(), and v8::internal::EvacuateVisitorBase::RawMigrateObject().
CopyRange() [1/2]
template<typename TSlot >
void v8::internal::Heap::CopyRange (Tagged< HeapObject > dst_object, const TSlot dst_slot, const TSlot src_slot, int len, WriteBarrierMode mode)
Definition at line 2164 of file heap.cc.
                                                                           {
  // Ensure ranges do not overlap.
  DCHECK(TSlot(dst_slot + len) <= src_slot || (src_slot + len) <= dst_slot);
  const auto atomic_callback = [](TSlot dst_slot, TSlot dst_end, TSlot src_slot,
                                  int len) {
    const AtomicSlot atomic_dst_end(dst_end);
    AtomicSlot dst(dst_slot);
    AtomicSlot src(src_slot);
    while (dst < atomic_dst_end) {
      *dst = *src;
      ++dst;
      ++src;
    }
  };
  const auto non_atomic_callback = [](TSlot dst_slot, TSlot src_slot, int len) {
    MemCopy(dst_slot.ToVoidPtr(), src_slot.ToVoidPtr(), len * kTaggedSize);
  };
  CopyOrMoveRangeImpl(this, dst_object, dst_slot, src_slot, len, mode,
                      atomic_callback, non_atomic_callback);
}
References v8::internal::anonymous_namespace{heap.cc}::CopyOrMoveRangeImpl(), v8::internal::DCHECK(), v8::internal::kTaggedSize, v8::internal::MemCopy(), and mode().
CopyRange() [2/2]
template<typename TSlot >
V8_EXPORT_PRIVATE void v8::internal::Heap::CopyRange (Tagged< HeapObject > dst_object, TSlot dst_slot, TSlot src_slot, int len, WriteBarrierMode mode)
Referenced by v8::internal::ScopeInfo::CopyElements(), v8::internal::WeakArrayList::CopyElements(), v8::internal::TaggedArrayBase< Derived, ShapeT, Super >::CopyElements(), v8::internal::PropertyArray::CopyElements(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::ArrayList::ToFixedArray().
cpp_heap()
v8::CppHeap* v8::internal::Heap::cpp_heap () const [inline]
Definition at line 1167 of file heap.h.
{ return cpp_heap_; }
Referenced by AttachCppHeap(), CollectAllAvailableGarbage(), CollectGarbage(), CompleteSweepingFull(), CompleteSweepingYoung(), ConfigureHeap(), v8::internal::IncrementalMarking::CppHeapStep(), EnsureSweepingCompleted(), FinishSweepingIfOutOfWork(), v8::Isolate::GetCppHeap(), v8::internal::TracedHandles::GetCppHeapIfUnifiedYoungGC(), v8::internal::IncrementalMarking::GetScheduledBytes(), IncrementalMarkingLimitReached(), v8::internal::MinorMarkSweepCollector::MarkLiveObjects(), v8::internal::GCTracer::NotifyFullCppGCCompleted(), v8::internal::GCTracer::NotifyYoungCppGCCompleted(), PerformGarbageCollection(), v8::internal::TracedHandles::ProcessWeakYoungObjects(), v8::internal::GCTracer::ReportFullCycleToRecorder(), v8::internal::GCTracer::ReportIncrementalMarkingStepToRecorder(), v8::internal::GCTracer::ReportYoungCycleToRecorder(), v8::internal::ConcurrentMarking::RunMajor(), v8::internal::IncrementalMarking::ShouldFinalize(), v8::internal::MarkCompactCollector::StartMarking(), v8::internal::GCTracer::StopFullCycleIfFinished(), and v8::internal::GCTracer::StopYoungCycleIfFinished().
CreateDefaultMeasureMemoryDelegate()
std::unique_ptr< v8::MeasureMemoryDelegate > v8::internal::Heap::CreateDefaultMeasureMemoryDelegate (v8::Local< v8::Context > context, v8::Local< v8::Promise::Resolver > promise, v8::MeasureMemoryMode mode)
Definition at line 4440 of file heap.cc.
                              {
  return i::MemoryMeasurement::DefaultDelegate(
      reinterpret_cast<v8::Isolate*>(isolate_), context, promise, mode);
}
References v8::internal::MemoryMeasurement::DefaultDelegate(), isolate_, and mode().
Referenced by v8::MeasureMemoryDelegate::Default().
CreateEarlyReadOnlyMapsAndObjects()
bool v8::internal::Heap::CreateEarlyReadOnlyMapsAndObjects () [private]
Definition at line 342 of file setup-heap-internal.cc.
                                             {
  // Setup maps and objects which are used often, or used in
  // CreateImportantReadOnlyObjects.
  ReadOnlyRoots roots(this);
  // First create the following, in the following order:
  // - Undefined value
  // - Null value
  // - Empty string
  // - False value
  // - True value
  // - /String maps
  // \...
  // - Symbol map
  // - Meta-map
  // - Undefined map
  // - Null map
  // - Boolean map
  //
  // This is so that:
  // 1. The falsy values are the first in the space, allowing ToBoolean false
  // checks to be a single less-than.
  // 2. The true value is immediately after the falsy values, so that we can
  // use a single compare's condition flags to check both falsy and true.
  // 3. The string maps are all together, and are the first maps, allowing
  // them to be checked with a single less-than if we know we have a map.
  // 4. The symbol map is with the string maps, for similarly fast Name
  // checks.
  Tagged<HeapObject> obj;
  {
    // We're a bit loose with raw pointers here for readability -- this is all
    // guaranteed to be safe anyway since the allocations can't cause a GC, so
    // disable gcmole in this range.
    DisableGCMole no_gc_mole;
    // First, set up the roots to all point to the right offset in the
    // allocation folded allocation.
#define ALLOCATE_AND_SET_ROOT(Type, name, Size) \
  { \
    AllocationResult alloc = AllocateRaw(Size, AllocationType::kReadOnly); \
    if (!alloc.To(&obj)) return false; \
  } \
  Tagged<Type> name = UncheckedCast<Type>(obj); \
  set_##name(name)
    ALLOCATE_AND_SET_ROOT(Undefined, undefined_value, sizeof(Undefined));
    ALLOCATE_AND_SET_ROOT(Null, null_value, sizeof(Null));
    ALLOCATE_AND_SET_ROOT(SeqOneByteString, empty_string,
                          SeqOneByteString::SizeFor(0));
    ALLOCATE_AND_SET_ROOT(False, false_value, sizeof(False));
    ALLOCATE_AND_SET_ROOT(True, true_value, sizeof(True));
    for (const StringTypeInit& entry : kStringTypeTable) {
      {
        AllocationResult alloc =
            AllocateRaw(Map::kSize, AllocationType::kReadOnly);
        if (!alloc.To(&obj)) return false;
      }
      Tagged<Map> map = UncheckedCast<Map>(obj);
      roots_table()[entry.index] = map.ptr();
    }
    ALLOCATE_AND_SET_ROOT(Map, symbol_map, Map::kSize);
    ALLOCATE_AND_SET_ROOT(Map, meta_map, Map::kSize);
    // Keep HeapNumber and Oddball maps together for cheap NumberOrOddball
    // checks.
    ALLOCATE_AND_SET_ROOT(Map, undefined_map, Map::kSize);
    ALLOCATE_AND_SET_ROOT(Map, null_map, Map::kSize);
    // Keep HeapNumber and Boolean maps together for cheap NumberOrBoolean
    // checks.
    ALLOCATE_AND_SET_ROOT(Map, boolean_map, Map::kSize);
    // Keep HeapNumber and BigInt maps together for cheaper numerics checks.
    ALLOCATE_AND_SET_ROOT(Map, heap_number_map, Map::kSize);
    ALLOCATE_AND_SET_ROOT(Map, bigint_map, Map::kSize);
    // Keep FreeSpace and filler maps together for cheap
    // `IsFreeSpaceOrFiller()`.
    ALLOCATE_AND_SET_ROOT(Map, free_space_map, Map::kSize);
    ALLOCATE_AND_SET_ROOT(Map, one_pointer_filler_map, Map::kSize);
    ALLOCATE_AND_SET_ROOT(Map, two_pointer_filler_map, Map::kSize);
#undef ALLOCATE_AND_SET_ROOT
    // Then, initialise the initial maps.
    InitializePartialMap(isolate(), meta_map, meta_map, MAP_TYPE, Map::kSize);
    InitializePartialMap(isolate(), undefined_map, meta_map, ODDBALL_TYPE,
                         sizeof(Undefined));
    InitializePartialMap(isolate(), null_map, meta_map, ODDBALL_TYPE,
                         sizeof(Null));
    InitializePartialMap(isolate(), boolean_map, meta_map, ODDBALL_TYPE,
                         sizeof(Boolean));
    boolean_map->SetConstructorFunctionIndex(Context::BOOLEAN_FUNCTION_INDEX);
    InitializePartialMap(isolate(), heap_number_map, meta_map, HEAP_NUMBER_TYPE,
                         sizeof(HeapNumber));
    heap_number_map->SetConstructorFunctionIndex(
        Context::NUMBER_FUNCTION_INDEX);
    InitializePartialMap(isolate(), bigint_map, meta_map, BIGINT_TYPE,
                         kVariableSizeSentinel);
    InitializePartialMap(isolate(), free_space_map, meta_map, FREE_SPACE_TYPE,
                         kVariableSizeSentinel);
    InitializePartialMap(isolate(), one_pointer_filler_map, meta_map,
                         FILLER_TYPE, kTaggedSize);
    InitializePartialMap(isolate(), two_pointer_filler_map, meta_map,
                         FILLER_TYPE, 2 * kTaggedSize);
    for (const StringTypeInit& entry : kStringTypeTable) {
      Tagged<Map> map = UncheckedCast<Map>(roots.object_at(entry.index));
      InitializePartialMap(isolate(), map, meta_map, entry.type, entry.size);
      map->SetConstructorFunctionIndex(Context::STRING_FUNCTION_INDEX);
      // Strings change maps in-place (e.g., when internalizing them). Thus they
      // are marked unstable to let the compilers not depend on them not
      // changing.
      map->mark_unstable();
    }
    InitializePartialMap(isolate(), symbol_map, meta_map, SYMBOL_TYPE,
                         sizeof(Symbol));
    symbol_map->SetConstructorFunctionIndex(Context::SYMBOL_FUNCTION_INDEX);
    // Finally, initialise the non-map objects using those maps.
    undefined_value->set_map_after_allocation(isolate(), undefined_map,
                                              SKIP_WRITE_BARRIER);
    undefined_value->set_kind(Oddball::kUndefined);
    null_value->set_map_after_allocation(isolate(), null_map,
                                         SKIP_WRITE_BARRIER);
    null_value->set_kind(Oddball::kNull);
    true_value->set_map_after_allocation(isolate(), boolean_map,
                                         SKIP_WRITE_BARRIER);
    true_value->set_kind(Oddball::kTrue);
    false_value->set_map_after_allocation(isolate(), boolean_map,
                                          SKIP_WRITE_BARRIER);
    false_value->set_kind(Oddball::kFalse);
    // The empty string is initialised with an empty hash despite being
    // internalized -- this will be calculated once the hashseed is available.
    // TODO(leszeks): Unify this initialisation with normal string
    // initialisation.
    empty_string->set_map_after_allocation(
        isolate(), roots.unchecked_internalized_one_byte_string_map(),
        SKIP_WRITE_BARRIER);
    empty_string->clear_padding_destructively(0);
    empty_string->set_length(0);
    empty_string->set_raw_hash_field(String::kEmptyHashField);
  }
  // Now that the initial objects are allocated, we can start allocating other
  // objects where the order matters less.
#define ALLOCATE_PARTIAL_MAP(instance_type, size, field_name) \
  { \
    Tagged<Map> map; \
    if (!AllocatePartialMap((instance_type), (size)).To(&map)) return false; \
    set_##field_name##_map(map); \
  }
  { // Partial map allocation
    ALLOCATE_PARTIAL_MAP(FIXED_ARRAY_TYPE, kVariableSizeSentinel, fixed_array);
    ALLOCATE_PARTIAL_MAP(TRUSTED_FIXED_ARRAY_TYPE, kVariableSizeSentinel,
                         trusted_fixed_array);
    ALLOCATE_PARTIAL_MAP(PROTECTED_FIXED_ARRAY_TYPE, kVariableSizeSentinel,
                         protected_fixed_array);
    ALLOCATE_PARTIAL_MAP(WEAK_FIXED_ARRAY_TYPE, kVariableSizeSentinel,
                         weak_fixed_array);
    ALLOCATE_PARTIAL_MAP(TRUSTED_WEAK_FIXED_ARRAY_TYPE, kVariableSizeSentinel,
                         trusted_weak_fixed_array);
    ALLOCATE_PARTIAL_MAP(PROTECTED_WEAK_FIXED_ARRAY_TYPE, kVariableSizeSentinel,
                         protected_weak_fixed_array);
    ALLOCATE_PARTIAL_MAP(WEAK_ARRAY_LIST_TYPE, kVariableSizeSentinel,
                         weak_array_list);
    ALLOCATE_PARTIAL_MAP(FIXED_ARRAY_TYPE, kVariableSizeSentinel,
                         fixed_cow_array)
    DCHECK_NE(roots.fixed_array_map(), roots.fixed_cow_array_map());
    ALLOCATE_PARTIAL_MAP(DESCRIPTOR_ARRAY_TYPE, kVariableSizeSentinel,
                         descriptor_array)
    ALLOCATE_PARTIAL_MAP(HOLE_TYPE, Hole::kSize, hole);
    // Some struct maps which we need for later dependencies
    for (const StructInit& entry : kStructTable) {
      if (!is_important_struct(entry.type)) continue;
      Tagged<Map> map;
      if (!AllocatePartialMap(entry.type, entry.size).To(&map)) return false;
      roots_table()[entry.index] = map.ptr();
    }
  }
#undef ALLOCATE_PARTIAL_MAP
  {
    AllocationResult alloc =
        AllocateRaw(FixedArray::SizeFor(0), AllocationType::kReadOnly);
    if (!alloc.To(&obj)) return false;
    obj->set_map_after_allocation(isolate(), roots.fixed_array_map(),
                                  SKIP_WRITE_BARRIER);
    Cast<FixedArray>(obj)->set_length(0);
  }
  set_empty_fixed_array(Cast<FixedArray>(obj));
  {
    AllocationResult alloc =
        AllocateRaw(WeakFixedArray::SizeFor(0), AllocationType::kReadOnly);
    if (!alloc.To(&obj)) return false;
    obj->set_map_after_allocation(isolate(), roots.weak_fixed_array_map(),
                                  SKIP_WRITE_BARRIER);
    Cast<WeakFixedArray>(obj)->set_length(0);
  }
  set_empty_weak_fixed_array(Cast<WeakFixedArray>(obj));
  {
    AllocationResult allocation = AllocateRaw(WeakArrayList::SizeForCapacity(0),
                                              AllocationType::kReadOnly);
    if (!allocation.To(&obj)) return false;
    obj->set_map_after_allocation(isolate(), roots.weak_array_list_map(),
                                  SKIP_WRITE_BARRIER);
    Cast<WeakArrayList>(obj)->set_capacity(0);
    Cast<WeakArrayList>(obj)->set_length(0);
  }
  set_empty_weak_array_list(Cast<WeakArrayList>(obj));
  DCHECK(!HeapLayout::InYoungGeneration(roots.undefined_value()));
  {
    AllocationResult allocation =
        Allocate(roots_table().hole_map(), AllocationType::kReadOnly);
    if (!allocation.To(&obj)) return false;
  }
  set_the_hole_value(Cast<Hole>(obj));
  // Set preliminary exception sentinel value before actually initializing it.
  set_exception(Cast<Hole>(obj));
  // Allocate the empty enum cache.
  {
    AllocationResult allocation =
        Allocate(roots_table().enum_cache_map(), AllocationType::kReadOnly);
    if (!allocation.To(&obj)) return false;
  }
  set_empty_enum_cache(Cast<EnumCache>(obj));
  Cast<EnumCache>(obj)->set_keys(roots.empty_fixed_array());
  Cast<EnumCache>(obj)->set_indices(roots.empty_fixed_array());
  // Allocate the empty descriptor array.
  {
    int size = DescriptorArray::SizeFor(0);
    if (!AllocateRaw(size, AllocationType::kReadOnly).To(&obj)) return false;
    obj->set_map_after_allocation(isolate(), roots.descriptor_array_map(),
                                  SKIP_WRITE_BARRIER);
    Tagged<DescriptorArray> array = Cast<DescriptorArray>(obj);
    array->Initialize(roots.empty_enum_cache(), roots.undefined_value(), 0, 0,
                      DescriptorArrayMarkingState::kInitialGCState);
    array->set_fast_iterable(DescriptorArray::FastIterableState::kJsonFast);
  }
  set_empty_descriptor_array(Cast<DescriptorArray>(obj));
  // Fix the instance_descriptors for the existing maps.
  FinalizePartialMap(roots.meta_map());
  FinalizePartialMap(roots.fixed_array_map());
  FinalizePartialMap(roots.trusted_fixed_array_map());
  FinalizePartialMap(roots.protected_fixed_array_map());
  FinalizePartialMap(roots.weak_fixed_array_map());
  FinalizePartialMap(roots.weak_array_list_map());
  FinalizePartialMap(roots.trusted_weak_fixed_array_map());
  FinalizePartialMap(roots.protected_weak_fixed_array_map());
  FinalizePartialMap(roots.fixed_cow_array_map());
  FinalizePartialMap(roots.descriptor_array_map());
  FinalizePartialMap(roots.undefined_map());
  roots.undefined_map()->set_is_undetectable(true);
  FinalizePartialMap(roots.null_map());
  roots.null_map()->set_is_undetectable(true);
  FinalizePartialMap(roots.boolean_map());
  FinalizePartialMap(roots.heap_number_map());
  FinalizePartialMap(roots.bigint_map());
  FinalizePartialMap(roots.hole_map());
  FinalizePartialMap(roots.symbol_map());
  FinalizePartialMap(roots.free_space_map());
  FinalizePartialMap(roots.one_pointer_filler_map());
  FinalizePartialMap(roots.two_pointer_filler_map());
  for (const StructInit& entry : kStructTable) {
    if (!is_important_struct(entry.type)) continue;
    FinalizePartialMap(Cast<Map>(roots.object_at(entry.index)));
  }
  for (const StringTypeInit& entry : kStringTypeTable) {
    FinalizePartialMap(Cast<Map>(roots.object_at(entry.index)));
  }
#define ALLOCATE_MAP(instance_type, size, field_name) \
  { \
    Tagged<Map> map; \
    if (!AllocateMap(AllocationType::kReadOnly, (instance_type), size) \
             .To(&map)) { \
      return false; \
    } \
    set_##field_name##_map(map); \
  }
#define ALLOCATE_VARSIZE_MAP(instance_type, field_name) \
  ALLOCATE_MAP(instance_type, kVariableSizeSentinel, field_name)
#define ALLOCATE_PRIMITIVE_MAP(instance_type, size, field_name, \
                               constructor_function_index) \
  { \
    ALLOCATE_MAP((instance_type), (size), field_name); \
    roots.field_name##_map()->SetConstructorFunctionIndex(\
        (constructor_function_index)); \
  }
  { // Map allocation
    ALLOCATE_VARSIZE_MAP(SCOPE_INFO_TYPE, scope_info)
    ALLOCATE_VARSIZE_MAP(FIXED_ARRAY_TYPE, module_info)
    ALLOCATE_VARSIZE_MAP(CLOSURE_FEEDBACK_CELL_ARRAY_TYPE,
                         closure_feedback_cell_array)
    ALLOCATE_VARSIZE_MAP(FEEDBACK_VECTOR_TYPE, feedback_vector)
    ALLOCATE_MAP(FOREIGN_TYPE, Foreign::kSize, foreign)
    ALLOCATE_MAP(TRUSTED_FOREIGN_TYPE, TrustedForeign::kSize, trusted_foreign)
    ALLOCATE_MAP(MEGA_DOM_HANDLER_TYPE, MegaDomHandler::kSize, mega_dom_handler)
    ALLOCATE_VARSIZE_MAP(FIXED_DOUBLE_ARRAY_TYPE, fixed_double_array)
    roots.fixed_double_array_map()->set_elements_kind(HOLEY_DOUBLE_ELEMENTS);
    ALLOCATE_VARSIZE_MAP(FEEDBACK_METADATA_TYPE, feedback_metadata)
    ALLOCATE_VARSIZE_MAP(BYTE_ARRAY_TYPE, byte_array)
    ALLOCATE_VARSIZE_MAP(TRUSTED_BYTE_ARRAY_TYPE, trusted_byte_array)
    ALLOCATE_VARSIZE_MAP(BYTECODE_ARRAY_TYPE, bytecode_array)
    ALLOCATE_VARSIZE_MAP(PROPERTY_ARRAY_TYPE, property_array)
    ALLOCATE_VARSIZE_MAP(SMALL_ORDERED_HASH_MAP_TYPE, small_ordered_hash_map)
    ALLOCATE_VARSIZE_MAP(SMALL_ORDERED_HASH_SET_TYPE, small_ordered_hash_set)
    ALLOCATE_VARSIZE_MAP(SMALL_ORDERED_NAME_DICTIONARY_TYPE,
                         small_ordered_name_dictionary)
    ALLOCATE_VARSIZE_MAP(INSTRUCTION_STREAM_TYPE, instruction_stream)
    ALLOCATE_MAP(CELL_TYPE, Cell::kSize, cell);
    {
      // The invalid_prototype_validity_cell is needed for JSObject maps.
      Tagged<Smi> value = Smi::FromInt(Map::kPrototypeChainInvalid);
      AllocationResult alloc =
          AllocateRaw(Cell::kSize, AllocationType::kReadOnly);
      if (!alloc.To(&obj)) return false;
      obj->set_map_after_allocation(isolate(), roots.cell_map(),
                                    SKIP_WRITE_BARRIER);
      Cast<Cell>(obj)->set_value(value);
      set_invalid_prototype_validity_cell(Cast<Cell>(obj));
    }
    ALLOCATE_MAP(PROPERTY_CELL_TYPE, PropertyCell::kSize, global_property_cell)
    // The "no closures" and "one closure" FeedbackCell maps need
    // to be marked unstable because their objects can change maps.
    ALLOCATE_MAP(FEEDBACK_CELL_TYPE, FeedbackCell::kAlignedSize,
                 no_closures_cell)
    roots.no_closures_cell_map()->mark_unstable();
    ALLOCATE_MAP(FEEDBACK_CELL_TYPE, FeedbackCell::kAlignedSize,
                 one_closure_cell)
    roots.one_closure_cell_map()->mark_unstable();
    ALLOCATE_MAP(FEEDBACK_CELL_TYPE, FeedbackCell::kAlignedSize,
                 many_closures_cell)
    ALLOCATE_VARSIZE_MAP(TRANSITION_ARRAY_TYPE, transition_array)
    ALLOCATE_VARSIZE_MAP(HASH_TABLE_TYPE, hash_table)
    ALLOCATE_VARSIZE_MAP(ORDERED_NAME_DICTIONARY_TYPE, ordered_name_dictionary)
    ALLOCATE_VARSIZE_MAP(NAME_DICTIONARY_TYPE, name_dictionary)
    ALLOCATE_VARSIZE_MAP(SWISS_NAME_DICTIONARY_TYPE, swiss_name_dictionary)
    ALLOCATE_VARSIZE_MAP(GLOBAL_DICTIONARY_TYPE, global_dictionary)
    ALLOCATE_VARSIZE_MAP(NUMBER_DICTIONARY_TYPE, number_dictionary)
    ALLOCATE_VARSIZE_MAP(REGISTERED_SYMBOL_TABLE_TYPE, registered_symbol_table)
    ALLOCATE_VARSIZE_MAP(ARRAY_LIST_TYPE, array_list)
    ALLOCATE_MAP(ACCESSOR_INFO_TYPE, AccessorInfo::kSize, accessor_info)
    ALLOCATE_MAP(INTERCEPTOR_INFO_TYPE, InterceptorInfo::kSize,
                 interceptor_info)
    ALLOCATE_VARSIZE_MAP(PREPARSE_DATA_TYPE, preparse_data)
    ALLOCATE_MAP(SHARED_FUNCTION_INFO_TYPE, SharedFunctionInfo::kSize,
                 shared_function_info)
    ALLOCATE_MAP(CODE_TYPE, Code::kSize, code)
    return true;
  }
}
References Allocate(), ALLOCATE_AND_SET_ROOT, ALLOCATE_MAP, ALLOCATE_PARTIAL_MAP, ALLOCATE_VARSIZE_MAP, AllocatePartialMap(), AllocateRaw(), v8::internal::BIGINT_TYPE, code, v8::internal::DCHECK(), DCHECK_NE, FinalizePartialMap(), v8::internal::Smi::FromInt(), v8::internal::HOLEY_DOUBLE_ELEMENTS, v8::internal::anonymous_namespace{setup-heap-internal.cc}::InitializePartialMap(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::anonymous_namespace{setup-heap-internal.cc}::is_important_struct(), isolate(), v8::internal::FeedbackCell::kAlignedSize, v8::internal::Name::kEmptyHashField, v8::internal::Oddball::kFalse, v8::internal::DescriptorArrayMarkingState::kInitialGCState, v8::internal::DescriptorArray::kJsonFast, v8::internal::Oddball::kNull, v8::internal::Map::kPrototypeChainInvalid, v8::internal::kReadOnly, v8::internal::Hole::kSize, v8::internal::anonymous_namespace{setup-heap-internal.cc}::kStringTypeTable, v8::internal::anonymous_namespace{setup-heap-internal.cc}::kStructTable, v8::internal::kTaggedSize, v8::internal::Oddball::kTrue, v8::internal::Oddball::kUndefined, v8::internal::kVariableSizeSentinel, v8::internal::ReadOnlyRoots::object_at(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), roots_table(), size(), v8::internal::TaggedArrayBase< WeakFixedArray, WeakFixedArrayShape >::SizeFor(), v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::SizeFor(), v8::internal::DescriptorArray::SizeFor(), v8::internal::SeqOneByteString::SizeFor(), v8::internal::WeakArrayList::SizeForCapacity(), v8::internal::SKIP_WRITE_BARRIER, v8::internal::AllocationResult::To(), and v8::internal::value.
Referenced by CreateReadOnlyHeapObjects().
CreateFillerObjectAt()
void v8::internal::Heap::CreateFillerObjectAt (Address addr, int size, ClearFreedMemoryMode clear_memory_mode = ClearFreedMemoryMode::kDontClearFreedMemory)
Definition at line 3348 of file heap.cc.
                                                                        {
  if (size == 0) return;
  if (MemoryChunk::FromAddress(addr)->executable()) {
    WritableJitPage jit_page(addr, size);
    WritableFreeSpace free_space = jit_page.FreeRange(addr, size);
    CreateFillerObjectAtRaw(free_space, clear_memory_mode,
                            ClearRecordedSlots::kNo,
                            VerifyNoSlotsRecorded::kYes);
  } else {
    WritableFreeSpace free_space =
        WritableFreeSpace::ForNonExecutableMemory(addr, size);
    CreateFillerObjectAtRaw(free_space, clear_memory_mode,
                            ClearRecordedSlots::kNo,
                            VerifyNoSlotsRecorded::kYes);
  }
}
References CreateFillerObjectAtRaw(), v8::internal::WritableFreeSpace::ForNonExecutableMemory(), v8::internal::WritableJitPage::FreeRange(), v8::internal::MemoryChunk::FromAddress(), v8::internal::kNo, kYes, and size().
Referenced by v8::internal::LargeObjectSpace::AdvanceAndInvokeAllocationObservers(), v8::internal::MainAllocator::AlignTopForTesting(), v8::internal::SemiSpace::AllocateFreshPage(), CreateReadOnlyObjects(), v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::DeleteDeadObjects(), v8::internal::ReadOnlySpace::EnsureSpaceForAllocation(), v8::internal::ReadOnlySpace::FinalizeSpaceForDeserialization(), v8::internal::EvacuationAllocator::FreeLastInMainAllocator(), v8::internal::ReadOnlySpace::FreeLinearAllocationArea(), v8::internal::TranslatedValue::GetRawValue(), v8::internal::MainAllocator::InvokeAllocationObservers(), v8::internal::MainAllocator::MakeLinearAllocationAreaIterable(), PrecedeWithFiller(), v8::internal::ReadOnlySpace::RepairFreeSpacesAfterDeserialization(), v8::internal::ReadOnlySpace::ShrinkPages(), v8::internal::ReadOnlyPageMetadata::ShrinkToHighWaterMark(), StaticRootsEnsureAllocatedSize(), v8::internal::PagedSpaceAllocatorPolicy::TryAllocationFromFreeList(), and v8::internal::PagedSpaceAllocatorPolicy::TryExtendLAB().
CreateFillerObjectAtBackground()
void v8::internal::Heap::CreateFillerObjectAtBackground (const WritableFreeSpace & free_space)
Definition at line 3339 of file heap.cc.
                                                                             {
  // TODO(leszeks): Verify that no slots need to be recorded.
  // Do not verify whether slots are cleared here: the concurrent thread is not
  // allowed to access the main thread's remembered set.
  CreateFillerObjectAtRaw(free_space,
                          ClearFreedMemoryMode::kDontClearFreedMemory,
                          ClearRecordedSlots::kNo, VerifyNoSlotsRecorded::kNo);
}
References CreateFillerObjectAtRaw(), v8::internal::kDontClearFreedMemory, v8::internal::kNo, and kNo.
Referenced by AlignWithFillerBackground(), and PrecedeWithFillerBackground().
CreateFillerObjectAtRaw()
void v8::internal::Heap::CreateFillerObjectAtRaw (const WritableFreeSpace & free_space, ClearFreedMemoryMode clear_memory_mode, ClearRecordedSlots clear_slots_mode, VerifyNoSlotsRecorded verify_no_slots_recorded) [private]
Definition at line 3366 of file heap.cc.
                                                    {
  // TODO(mlippautz): It would be nice to DCHECK that we never call this
  // with {addr} pointing into large object space; however we currently do,
  // see, e.g., Factory::NewFillerObject and in many tests.
  size_t size = free_space.Size();
  if (size == 0) return;
  CreateFillerObjectAtImpl(free_space, this, clear_memory_mode);
  Address addr = free_space.Address();
  if (clear_slots_mode == ClearRecordedSlots::kYes) {
    ClearRecordedSlotRange(addr, addr + size);
  } else if (verify_no_slots_recorded == VerifyNoSlotsRecorded::kYes) {
    VerifyNoNeedToClearSlots(addr, addr + size);
  }
}
References v8::internal::WritableFreeSpace::Address(), ClearRecordedSlotRange(), v8::internal::anonymous_namespace{heap.cc}::CreateFillerObjectAtImpl(), v8::internal::kYes, kYes, v8::internal::WritableFreeSpace::Size(), size(), and v8::internal::anonymous_namespace{heap.cc}::VerifyNoNeedToClearSlots().
Referenced by CreateFillerObjectAt(), CreateFillerObjectAtBackground(), LeftTrimFixedArray(), and NotifyObjectSizeChange().
CreateImportantReadOnlyObjects()
bool v8::internal::Heap::CreateImportantReadOnlyObjects () [private]
Definition at line 918 of file setup-heap-internal.cc.
                                          {
  // Allocate some objects early to get addresses to fit as arm64 immediates.
  Tagged<HeapObject> obj;
  ReadOnlyRoots roots(isolate());
  HandleScope initial_objects_handle_scope(isolate());
  // Hash seed for strings
  Factory* factory = isolate()->factory();
  set_hash_seed(*factory->NewByteArray(kInt64Size, AllocationType::kReadOnly));
  InitializeHashSeed();
  // Important strings and symbols
  for (const ConstantStringInit& entry : kImportantConstantStringTable) {
    if (entry.index == RootIndex::kempty_string) {
      // Special case the empty string, since it's allocated and initialised in
      // the initial section.
      isolate()->string_table()->InsertEmptyStringForBootstrapping(isolate());
    } else {
      DirectHandle<String> str = factory->InternalizeString(entry.contents);
      roots_table()[entry.index] = str->ptr();
    }
  }
  {
#define SYMBOL_INIT(_, name) \
  { \
    DirectHandle<Symbol> symbol(\
        isolate()->factory()->NewPrivateSymbol(AllocationType::kReadOnly)); \
    roots_table()[RootIndex::k##name] = symbol->ptr(); \
  }
      IMPORTANT_PRIVATE_SYMBOL_LIST_GENERATOR(SYMBOL_INIT, /* not used */)
      // SYMBOL_INIT used again later.
  }
  // Empty elements
  DirectHandle<NameDictionary>
      empty_property_dictionary = NameDictionary::New(
          isolate(), 1, AllocationType::kReadOnly, USE_CUSTOM_MINIMUM_CAPACITY);
  DCHECK(!empty_property_dictionary->HasSufficientCapacityToAdd(1));
  set_empty_property_dictionary(*empty_property_dictionary);
  // Allocate the empty OrderedNameDictionary
  DirectHandle<OrderedNameDictionary> empty_ordered_property_dictionary =
      OrderedNameDictionary::AllocateEmpty(isolate(), AllocationType::kReadOnly)
          .ToHandleChecked();
  set_empty_ordered_property_dictionary(*empty_ordered_property_dictionary);
  {
    if (!AllocateRaw(ByteArray::SizeFor(0), AllocationType::kReadOnly)
             .To(&obj)) {
      return false;
    }
    obj->set_map_after_allocation(isolate(), roots.byte_array_map(),
                                  SKIP_WRITE_BARRIER);
    Cast<ByteArray>(obj)->set_length(0);
    set_empty_byte_array(Cast<ByteArray>(obj));
  }
  {
    AllocationResult alloc =
        AllocateRaw(ScopeInfo::SizeFor(ScopeInfo::kVariablePartIndex),
                    AllocationType::kReadOnly);
    if (!alloc.To(&obj)) return false;
    obj->set_map_after_allocation(isolate(), roots.scope_info_map(),
                                  SKIP_WRITE_BARRIER);
    int flags = ScopeInfo::IsEmptyBit::encode(true);
    DCHECK_EQ(ScopeInfo::LanguageModeBit::decode(flags), LanguageMode::kSloppy);
    DCHECK_EQ(ScopeInfo::ReceiverVariableBits::decode(flags),
              VariableAllocationInfo::NONE);
    DCHECK_EQ(ScopeInfo::FunctionVariableBits::decode(flags),
              VariableAllocationInfo::NONE);
    Cast<ScopeInfo>(obj)->set_flags(flags, kRelaxedStore);
    Cast<ScopeInfo>(obj)->set_context_local_count(0);
    Cast<ScopeInfo>(obj)->set_parameter_count(0);
    Cast<ScopeInfo>(obj)->set_position_info_start(0);
    Cast<ScopeInfo>(obj)->set_position_info_end(0);
  }
  set_empty_scope_info(Cast<ScopeInfo>(obj));
  {
    if (!AllocateRaw(FixedArray::SizeFor(0), AllocationType::kReadOnly)
             .To(&obj)) {
      return false;
    }
    obj->set_map_after_allocation(isolate(), roots.property_array_map(),
                                  SKIP_WRITE_BARRIER);
    Cast<PropertyArray>(obj)->initialize_length(0);
    set_empty_property_array(Cast<PropertyArray>(obj));
  }
  // Heap Numbers
  // The -0 value must be set before NewNumber works.
  set_minus_zero_value(
      *factory->NewHeapNumber<AllocationType::kReadOnly>(-0.0));
  DCHECK(std::signbit(Object::NumberValue(roots.minus_zero_value())));
  set_nan_value(*factory->NewHeapNumber<AllocationType::kReadOnly>(
      std::numeric_limits<double>::quiet_NaN()));
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
  set_undefined_nan_value(
      *factory->NewHeapNumberFromBits<AllocationType::kReadOnly>(
          kUndefinedNanInt64));
#else
  set_undefined_nan_value(*factory->NewHeapNumber<AllocationType::kReadOnly>(
      std::numeric_limits<double>::quiet_NaN()));
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
  set_hole_nan_value(*factory->NewHeapNumberFromBits<AllocationType::kReadOnly>(
      kHoleNanInt64));
  set_infinity_value(
      *factory->NewHeapNumber<AllocationType::kReadOnly>(V8_INFINITY));
  set_minus_infinity_value(
      *factory->NewHeapNumber<AllocationType::kReadOnly>(-V8_INFINITY));
  set_max_safe_integer(
      *factory->NewHeapNumber<AllocationType::kReadOnly>(kMaxSafeInteger));
  set_max_uint_32(
      *factory->NewHeapNumber<AllocationType::kReadOnly>(kMaxUInt32));
  set_smi_min_value(
      *factory->NewHeapNumber<AllocationType::kReadOnly>(kSmiMinValue));
  set_smi_max_value_plus_one(
      *factory->NewHeapNumber<AllocationType::kReadOnly>(0.0 - kSmiMinValue));
  return true;
}
References v8::internal::OrderedNameDictionary::AllocateEmpty(), AllocateRaw(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Isolate::factory(), v8::internal::flags, IMPORTANT_PRIVATE_SYMBOL_LIST_GENERATOR, InitializeHashSeed(), v8::internal::StringTable::InsertEmptyStringForBootstrapping(), v8::internal::Factory::InternalizeString(), isolate(), v8::internal::kHoleNanInt64, v8::internal::anonymous_namespace{setup-heap-internal.cc}::kImportantConstantStringTable, v8::internal::kInt64Size, v8::internal::kMaxSafeInteger, v8::internal::kMaxUInt32, v8::internal::kReadOnly, v8::kRelaxedStore, v8::internal::kSloppy, v8::internal::kSmiMinValue, v8::internal::ScopeInfo::kVariablePartIndex, v8::internal::NameDictionary::New(), v8::internal::FactoryBase< Impl >::NewByteArray(), v8::internal::FactoryBase< Impl >::NewHeapNumber(), v8::internal::FactoryBase< Impl >::NewHeapNumberFromBits(), v8::internal::NONE, v8::internal::Object::NumberValue(), roots_table(), v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::SizeFor(), v8::internal::PrimitiveArrayBase< ByteArray, ByteArrayShape >::SizeFor(), v8::internal::ScopeInfo::SizeFor(), v8::internal::SKIP_WRITE_BARRIER, v8::internal::Isolate::string_table(), SYMBOL_INIT, v8::internal::AllocationResult::To(), v8::internal::USE_CUSTOM_MINIMUM_CAPACITY, and V8_INFINITY.
Referenced by CreateReadOnlyHeapObjects().
CreateInitialMutableObjects()
void v8::internal::Heap::CreateInitialMutableObjects () [private]
Definition at line 1404 of file setup-heap-internal.cc.
                                       {
  HandleScope initial_objects_handle_scope(isolate());
  Factory* factory = isolate()->factory();
  ReadOnlyRoots roots(this);
  // There's no "current microtask" in the beginning.
  set_current_microtask(roots.undefined_value());
  set_weak_refs_keep_during_job(roots.undefined_value());
  set_public_symbol_table(roots.empty_symbol_table());
  set_api_symbol_table(roots.empty_symbol_table());
  set_api_private_symbol_table(roots.empty_symbol_table());
  set_smi_string_cache(
      *SmiStringCache::New(isolate(), SmiStringCache::kInitialSize));
  set_double_string_cache(
      *DoubleStringCache::New(isolate(), DoubleStringCache::kInitialSize));
  // Unchecked to skip failing checks since required roots are uninitialized.
  set_basic_block_profiling_data(roots.unchecked_empty_array_list());
  // Allocate regexp caches.
  set_string_split_cache(*factory->NewFixedArray(
      RegExpResultsCache::kRegExpResultsCacheSize, AllocationType::kOld));
  set_regexp_multiple_cache(*factory->NewFixedArray(
      RegExpResultsCache::kRegExpResultsCacheSize, AllocationType::kOld));
  set_regexp_match_global_atom_cache(*factory->NewFixedArray(
      RegExpResultsCache_MatchGlobalAtom::kSize, AllocationType::kOld));
  set_detached_contexts(roots.empty_weak_array_list());
  set_feedback_vectors_for_profiling_tools(roots.undefined_value());
  set_functions_marked_for_manual_optimization(roots.undefined_value());
  set_shared_wasm_memories(roots.empty_weak_array_list());
  set_locals_block_list_cache(roots.undefined_value());
#ifdef V8_ENABLE_WEBASSEMBLY
  set_active_suspender(roots.undefined_value());
  set_js_to_wasm_wrappers(roots.empty_weak_fixed_array());
  set_wasm_canonical_rtts(roots.empty_weak_fixed_array());
#endif // V8_ENABLE_WEBASSEMBLY
  set_script_list(roots.empty_weak_array_list());
  set_materialized_objects(*factory->NewFixedArray(0, AllocationType::kOld));
  // Handling of script id generation is in Heap::NextScriptId().
  set_last_script_id(Smi::FromInt(v8::UnboundScript::kNoScriptId));
  set_last_debugging_id(Smi::FromInt(DebugInfo::kNoDebuggingId));
  set_last_stack_trace_id(Smi::zero());
  set_next_template_serial_number(
      Smi::FromInt(TemplateInfo::kUninitializedSerialNumber));
  // Allocate the empty script.
  DirectHandle<Script> script = factory->NewScript(factory->empty_string());
  script->set_type(Script::Type::kNative);
  // This is used for exceptions thrown with no stack frames. Such exceptions
  // can be shared everywhere.
  script->set_origin_options(ScriptOriginOptions(true, false));
  set_empty_script(*script);
  // Protectors
  set_array_buffer_detaching_protector(*factory->NewProtector());
  set_array_iterator_protector(*factory->NewProtector());
  set_array_species_protector(*factory->NewProtector());
  set_no_date_time_configuration_change_protector(*factory->NewProtector());
  set_is_concat_spreadable_protector(*factory->NewProtector());
  set_map_iterator_protector(*factory->NewProtector());
  set_no_elements_protector(*factory->NewProtector());
  set_mega_dom_protector(*factory->NewProtector());
  set_no_profiling_protector(*factory->NewProtector());
  set_no_undetectable_objects_protector(*factory->NewProtector());
  set_promise_hook_protector(*factory->NewProtector());
  set_promise_resolve_protector(*factory->NewProtector());
  set_promise_species_protector(*factory->NewProtector());
  set_promise_then_protector(*factory->NewProtector());
  set_regexp_species_protector(*factory->NewProtector());
  set_set_iterator_protector(*factory->NewProtector());
  set_string_iterator_protector(*factory->NewProtector());
  set_string_length_protector(*factory->NewProtector());
  set_string_wrapper_to_primitive_protector(*factory->NewProtector());
  set_number_string_not_regexp_like_protector(*factory->NewProtector());
  set_typed_array_species_protector(*factory->NewProtector());
  set_serialized_objects(roots.empty_fixed_array());
  set_serialized_global_proxy_sizes(roots.empty_fixed_array());
  // Evaluate the hash values which will then be cached in the strings.
  isolate()->factory()->zero_string()->EnsureHash();
  isolate()->factory()->one_string()->EnsureHash();
  // Initialize builtins constants table.
  set_builtins_constants_table(roots.empty_fixed_array());
  // Initialize descriptor cache.
  isolate_->descriptor_lookup_cache()->Clear();
  // Initialize compilation cache.
  isolate_->compilation_cache()->Clear();
  // Error.stack accessor callbacks and their SharedFunctionInfos:
  {
    DirectHandle<FunctionTemplateInfo> function_template;
    function_template = ApiNatives::CreateAccessorFunctionTemplateInfo(
        isolate_, Accessors::ErrorStackGetter, 0,
        SideEffectType::kHasSideEffect);
    FunctionTemplateInfo::SealAndPrepareForPromotionToReadOnly(
        isolate_, function_template);
    set_error_stack_getter_fun_template(*function_template);
    function_template = ApiNatives::CreateAccessorFunctionTemplateInfo(
        isolate_, Accessors::ErrorStackSetter, 1,
        SideEffectType::kHasSideEffectToReceiver);
    FunctionTemplateInfo::SealAndPrepareForPromotionToReadOnly(
        isolate_, function_template);
    set_error_stack_setter_fun_template(*function_template);
  }
  // Create internal SharedFunctionInfos.
  // Async functions:
  {
    DirectHandle<SharedFunctionInfo> info = CreateSharedFunctionInfo(
        isolate(), Builtin::kAsyncFunctionAwaitRejectClosure, 1);
    set_async_function_await_reject_closure_shared_fun(*info);
    info = CreateSharedFunctionInfo(
        isolate(), Builtin::kAsyncFunctionAwaitResolveClosure, 1);
    set_async_function_await_resolve_closure_shared_fun(*info);
  }
  // Async generators:
  {
    DirectHandle<SharedFunctionInfo> info = CreateSharedFunctionInfo(
        isolate(), Builtin::kAsyncGeneratorAwaitResolveClosure, 1);
    set_async_generator_await_resolve_closure_shared_fun(*info);
    info = CreateSharedFunctionInfo(
        isolate(), Builtin::kAsyncGeneratorAwaitRejectClosure, 1);
    set_async_generator_await_reject_closure_shared_fun(*info);
    info = CreateSharedFunctionInfo(
        isolate(), Builtin::kAsyncGeneratorYieldWithAwaitResolveClosure, 1);
    set_async_generator_yield_with_await_resolve_closure_shared_fun(*info);
    info = CreateSharedFunctionInfo(
        isolate(), Builtin::kAsyncGeneratorReturnResolveClosure, 1);
    set_async_generator_return_resolve_closure_shared_fun(*info);
    info = CreateSharedFunctionInfo(
        isolate(), Builtin::kAsyncGeneratorReturnClosedResolveClosure, 1);
    set_async_generator_return_closed_resolve_closure_shared_fun(*info);
    info = CreateSharedFunctionInfo(
        isolate(), Builtin::kAsyncGeneratorReturnClosedRejectClosure, 1);
    set_async_generator_return_closed_reject_closure_shared_fun(*info);
  }
  // AsyncIterator:
  {
    DirectHandle<SharedFunctionInfo> info = CreateSharedFunctionInfo(
        isolate_, Builtin::kAsyncIteratorValueUnwrap, 1);
    set_async_iterator_value_unwrap_shared_fun(*info);
    info = CreateSharedFunctionInfo(
        isolate_, Builtin::kAsyncIteratorPrototypeAsyncDisposeResolveClosure,
        0);
    set_async_iterator_prototype_async_dispose_resolve_closure_shared_fun(
        *info);
  }
  // AsyncFromSyncIterator:
  {
    DirectHandle<SharedFunctionInfo> info = CreateSharedFunctionInfo(
        isolate_, Builtin::kAsyncFromSyncIteratorCloseSyncAndRethrow, 1);
    set_async_from_sync_iterator_close_sync_and_rethrow_shared_fun(*info);
  }
  // Promises:
  {
    DirectHandle<SharedFunctionInfo> info = CreateSharedFunctionInfo(
        isolate_, Builtin::kPromiseCapabilityDefaultResolve, 1,
        FunctionKind::kConciseMethod);
    info->set_native(true);
    info->set_function_map_index(
        Context::STRICT_FUNCTION_WITHOUT_PROTOTYPE_MAP_INDEX);
    set_promise_capability_default_resolve_shared_fun(*info);
    info = CreateSharedFunctionInfo(isolate_,
                                    Builtin::kPromiseCapabilityDefaultReject, 1,
                                    FunctionKind::kConciseMethod);
    info->set_native(true);
    info->set_function_map_index(
        Context::STRICT_FUNCTION_WITHOUT_PROTOTYPE_MAP_INDEX);
    set_promise_capability_default_reject_shared_fun(*info);
    info = CreateSharedFunctionInfo(
        isolate_, Builtin::kPromiseGetCapabilitiesExecutor, 2);
    set_promise_get_capabilities_executor_shared_fun(*info);
  }
  // Promises / finally:
  {
    DirectHandle<SharedFunctionInfo> info =
        CreateSharedFunctionInfo(isolate(), Builtin::kPromiseThenFinally, 1);
    info->set_native(true);
    set_promise_then_finally_shared_fun(*info);
    info =
        CreateSharedFunctionInfo(isolate(), Builtin::kPromiseCatchFinally, 1);
    info->set_native(true);
    set_promise_catch_finally_shared_fun(*info);
    info = CreateSharedFunctionInfo(isolate(),
                                    Builtin::kPromiseValueThunkFinally, 0);
    set_promise_value_thunk_finally_shared_fun(*info);
    info =
        CreateSharedFunctionInfo(isolate(), Builtin::kPromiseThrowerFinally, 0);
    set_promise_thrower_finally_shared_fun(*info);
  }
  // Promise combinators:
  {
    DirectHandle<SharedFunctionInfo> info = CreateSharedFunctionInfo(
        isolate_, Builtin::kPromiseAllResolveElementClosure, 1);
    set_promise_all_resolve_element_closure_shared_fun(*info);
    info = CreateSharedFunctionInfo(
        isolate_, Builtin::kPromiseAllSettledResolveElementClosure, 1);
    set_promise_all_settled_resolve_element_closure_shared_fun(*info);
    info = CreateSharedFunctionInfo(
        isolate_, Builtin::kPromiseAllSettledRejectElementClosure, 1);
    set_promise_all_settled_reject_element_closure_shared_fun(*info);
    info = CreateSharedFunctionInfo(
        isolate_, Builtin::kPromiseAnyRejectElementClosure, 1);
    set_promise_any_reject_element_closure_shared_fun(*info);
  }
  // ProxyRevoke:
  {
    DirectHandle<SharedFunctionInfo> info =
        CreateSharedFunctionInfo(isolate_, Builtin::kProxyRevoke, 0);
    set_proxy_revoke_shared_fun(*info);
  }
  // ShadowRealm:
  {
    DirectHandle<SharedFunctionInfo> info = CreateSharedFunctionInfo(
        isolate_, Builtin::kShadowRealmImportValueFulfilled, 1);
    set_shadow_realm_import_value_fulfilled_shared_fun(*info);
  }
  // SourceTextModule:
  {
    DirectHandle<SharedFunctionInfo> info = CreateSharedFunctionInfo(
        isolate_, Builtin::kCallAsyncModuleFulfilled, 0);
    set_source_text_module_execute_async_module_fulfilled_sfi(*info);
    info = CreateSharedFunctionInfo(isolate_, Builtin::kCallAsyncModuleRejected,
                                    0);
    set_source_text_module_execute_async_module_rejected_sfi(*info);
  }
  // Array.fromAsync:
  {
    DirectHandle<SharedFunctionInfo> info = CreateSharedFunctionInfo(
        isolate_, Builtin::kArrayFromAsyncIterableOnFulfilled, 1);
    set_array_from_async_iterable_on_fulfilled_shared_fun(*info);
    info = CreateSharedFunctionInfo(
        isolate_, Builtin::kArrayFromAsyncIterableOnRejected, 1);
    set_array_from_async_iterable_on_rejected_shared_fun(*info);
    info = CreateSharedFunctionInfo(
        isolate_, Builtin::kArrayFromAsyncArrayLikeOnFulfilled, 1);
    set_array_from_async_array_like_on_fulfilled_shared_fun(*info);
    info = CreateSharedFunctionInfo(
        isolate_, Builtin::kArrayFromAsyncArrayLikeOnRejected, 1);
    set_array_from_async_array_like_on_rejected_shared_fun(*info);
  }
  // Atomics.Mutex
  {
    DirectHandle<SharedFunctionInfo> info = CreateSharedFunctionInfo(
        isolate_, Builtin::kAtomicsMutexAsyncUnlockResolveHandler, 1);
    set_atomics_mutex_async_unlock_resolve_handler_sfi(*info);
    info = CreateSharedFunctionInfo(
        isolate_, Builtin::kAtomicsMutexAsyncUnlockRejectHandler, 1);
    set_atomics_mutex_async_unlock_reject_handler_sfi(*info);
  }
  // Atomics.Condition
  {
    DirectHandle<SharedFunctionInfo> info = CreateSharedFunctionInfo(
        isolate_, Builtin::kAtomicsConditionAcquireLock, 0);
    set_atomics_condition_acquire_lock_sfi(*info);
  }
  // Async Disposable Stack
  {
    DirectHandle<SharedFunctionInfo> info = CreateSharedFunctionInfo(
        isolate_, Builtin::kAsyncDisposableStackOnFulfilled, 0);
    set_async_disposable_stack_on_fulfilled_shared_fun(*info);
    info = CreateSharedFunctionInfo(
        isolate_, Builtin::kAsyncDisposableStackOnRejected, 0);
    set_async_disposable_stack_on_rejected_shared_fun(*info);
    info = CreateSharedFunctionInfo(isolate_,
                                    Builtin::kAsyncDisposeFromSyncDispose, 0);
    set_async_dispose_from_sync_dispose_shared_fun(*info);
  }
  // Trusted roots:
  // TODO(saelo): these would ideally be read-only and shared, but we currently
  // don't have a trusted RO space.
  {
    set_empty_trusted_byte_array(*TrustedByteArray::New(isolate_, 0));
    set_empty_trusted_fixed_array(*TrustedFixedArray::New(isolate_, 0));
    set_empty_trusted_weak_fixed_array(
        *TrustedWeakFixedArray::New(isolate_, 0));
    set_empty_protected_fixed_array(*ProtectedFixedArray::New(isolate_, 0));
    set_empty_protected_weak_fixed_array(
        *ProtectedWeakFixedArray::New(isolate_, 0));
  }
}
References v8::internal::CompilationCache::Clear(), v8::internal::DescriptorLookupCache::Clear(), v8::internal::Isolate::compilation_cache(), v8::internal::ApiNatives::CreateAccessorFunctionTemplateInfo(), v8::internal::anonymous_namespace{setup-heap-internal.cc}::CreateSharedFunctionInfo(), v8::internal::Isolate::descriptor_lookup_cache(), v8::internal::Isolate::factory(), v8::internal::Smi::FromInt(), isolate(), isolate_, v8::internal::kConciseMethod, v8::kHasSideEffect, v8::kHasSideEffectToReceiver, v8::internal::SmiStringCache::kInitialSize, v8::internal::DoubleStringCache::kInitialSize, v8::internal::Script::kNative, v8::internal::DebugInfo::kNoDebuggingId, v8::UnboundScript::kNoScriptId, v8::internal::kOld, v8::internal::RegExpResultsCache::kRegExpResultsCacheSize, v8::internal::RegExpResultsCache_MatchGlobalAtom::kSize, v8::internal::TemplateInfo::kUninitializedSerialNumber, v8::internal::TrustedWeakFixedArray::New(), v8::internal::ProtectedWeakFixedArray::New(), v8::internal::SmiStringCache::New(), v8::internal::DoubleStringCache::New(), v8::internal::TrustedFixedArray::New(), v8::internal::TrustedByteArray::New(), v8::internal::ProtectedFixedArray::New(), v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::Factory::NewProtector(), v8::internal::FactoryBase< Impl >::NewScript(), v8::internal::script, v8::internal::FunctionTemplateInfo::SealAndPrepareForPromotionToReadOnly(), and v8::internal::Smi::zero().
Referenced by CreateMutableHeapObjects().
CreateInternalAccessorInfoObjects()
void v8::internal::Heap::CreateInternalAccessorInfoObjects () [private]
Definition at line 1734 of file setup-heap-internal.cc.
                                             {
  Isolate* isolate = this->isolate();
  HandleScope scope(isolate);
  DirectHandle<AccessorInfo> accessor_info;
#define INIT_ACCESSOR_INFO(_, accessor_name, AccessorName, ...) \
  accessor_info = Accessors::Make##AccessorName##Info(isolate); \
  roots_table()[RootIndex::k##AccessorName##Accessor] = accessor_info->ptr();
  ACCESSOR_INFO_LIST_GENERATOR(INIT_ACCESSOR_INFO, /* not used */)
#undef INIT_ACCESSOR_INFO
#define INIT_SIDE_EFFECT_FLAG(_, accessor_name, AccessorName, GetterType, \
                              SetterType) \
  Cast<AccessorInfo>(\
      Tagged<Object>(roots_table()[RootIndex::k##AccessorName##Accessor])) \
      ->set_getter_side_effect_type(SideEffectType::GetterType); \
  Cast<AccessorInfo>(\
      Tagged<Object>(roots_table()[RootIndex::k##AccessorName##Accessor])) \
      ->set_setter_side_effect_type(SideEffectType::SetterType);
  ACCESSOR_INFO_LIST_GENERATOR(INIT_SIDE_EFFECT_FLAG, /* not used */)
#undef INIT_SIDE_EFFECT_FLAG
}
References ACCESSOR_INFO_LIST_GENERATOR, INIT_ACCESSOR_INFO, INIT_SIDE_EFFECT_FLAG, and isolate().
Referenced by CreateMutableHeapObjects().
CreateLateReadOnlyJSReceiverMaps()
bool v8::internal::Heap::CreateLateReadOnlyJSReceiverMaps () [private]
Definition at line 823 of file setup-heap-internal.cc.
                                            {
#define ALLOCATE_ALWAYS_SHARED_SPACE_JSOBJECT_MAP(instance_type, size, \
                                                  field_name) \
  { \
    Tagged<Map> map; \
    if (!AllocateMap(AllocationType::kReadOnly, (instance_type), size, \
                     DICTIONARY_ELEMENTS) \
             .To(&map)) { \
      return false; \
    } \
    AlwaysSharedSpaceJSObject::PrepareMapNoEnumerableProperties(map); \
    set_##field_name##_map(map); \
  }
  HandleScope late_jsreceiver_maps_handle_scope(isolate());
  Factory* factory = isolate()->factory();
  ReadOnlyRoots roots(this);
  {
    // JSMessageObject and JSExternalObject types are wrappers around a set
    // of primitive values and exist only for the purpose of passing the data
    // across V8 Api. They are not supposed to be leaked to user JS code
    // except from d8 tests and they are not proper JSReceivers.
    ALLOCATE_MAP(JS_MESSAGE_OBJECT_TYPE, JSMessageObject::kHeaderSize,
                 message_object)
    roots.message_object_map()->SetEnumLength(0);
    roots.message_object_map()->set_is_extensible(false);
    ALLOCATE_MAP(JS_EXTERNAL_OBJECT_TYPE, JSExternalObject::kHeaderSize,
                 external)
    roots.external_map()->SetEnumLength(0);
    roots.external_map()->set_is_extensible(false);
    ALLOCATE_MAP(CPP_HEAP_EXTERNAL_OBJECT_TYPE,
                 CppHeapExternalObject::kHeaderSize, cpp_heap_external)
  }
  // Shared space object maps are immutable and can be in RO space.
  {
    Tagged<Map> shared_array_map;
    if (!AllocateMap(AllocationType::kReadOnly, JS_SHARED_ARRAY_TYPE,
                     JSSharedArray::kSize, SHARED_ARRAY_ELEMENTS,
                     JSSharedArray::kInObjectFieldCount)
             .To(&shared_array_map)) {
      return false;
    }
    AlwaysSharedSpaceJSObject::PrepareMapNoEnumerableProperties(
        shared_array_map);
    DirectHandle<DescriptorArray> descriptors =
        factory->NewDescriptorArray(1, 0, AllocationType::kReadOnly);
    Descriptor length_descriptor = Descriptor::DataField(
        factory->length_string(), JSSharedArray::kLengthFieldIndex,
        ALL_ATTRIBUTES_MASK, PropertyConstness::kConst, Representation::Smi(),
        MaybeObjectDirectHandle(FieldType::Any(isolate())));
    descriptors->Set(InternalIndex(0), &length_descriptor);
    shared_array_map->InitializeDescriptors(isolate(), *descriptors);
    set_js_shared_array_map(shared_array_map);
  }
  ALLOCATE_ALWAYS_SHARED_SPACE_JSOBJECT_MAP(
      JS_ATOMICS_MUTEX_TYPE, JSAtomicsMutex::kHeaderSize, js_atomics_mutex)
  ALLOCATE_ALWAYS_SHARED_SPACE_JSOBJECT_MAP(JS_ATOMICS_CONDITION_TYPE,
                                            JSAtomicsCondition::kHeaderSize,
                                            js_atomics_condition)
#undef ALLOCATE_ALWAYS_SHARED_SPACE_JSOBJECT_MAP
#undef ALLOCATE_PRIMITIVE_MAP
#undef ALLOCATE_VARSIZE_MAP
#undef ALLOCATE_MAP
  return true;
}
References v8::internal::ALL_ATTRIBUTES_MASK, ALLOCATE_ALWAYS_SHARED_SPACE_JSOBJECT_MAP, ALLOCATE_MAP, AllocateMap(), v8::internal::FieldType::Any(), v8::internal::Descriptor::DataField(), v8::internal::Isolate::factory(), isolate(), v8::internal::kConst, v8::internal::JSSharedArray::kInObjectFieldCount, v8::internal::JSSharedArray::kLengthFieldIndex, v8::internal::kReadOnly, v8::internal::JSSharedArray::kSize, v8::internal::FactoryBase< Impl >::NewDescriptorArray(), v8::internal::AlwaysSharedSpaceJSObject::PrepareMapNoEnumerableProperties(), v8::internal::SHARED_ARRAY_ELEMENTS, and v8::internal::Representation::Smi().
Referenced by CreateReadOnlyHeapObjects().
CreateLateReadOnlyNonJSReceiverMaps()
bool v8::internal::Heap::CreateLateReadOnlyNonJSReceiverMaps () [private]
Definition at line 726 of file setup-heap-internal.cc.
                                               {
  ReadOnlyRoots roots(this);
  {
    // Setup the struct maps.
    for (const StructInit& entry : kStructTable) {
      if (is_important_struct(entry.type)) continue;
      Tagged<Map> map;
      if (!AllocateMap(AllocationType::kReadOnly, entry.type, entry.size)
               .To(&map))
        return false;
      roots_table()[entry.index] = map.ptr();
    }
#define TORQUE_ALLOCATE_MAP(NAME, Name, name) \
  ALLOCATE_MAP(NAME, Name::SizeFor(), name)
    TORQUE_DEFINED_FIXED_INSTANCE_TYPE_LIST(TORQUE_ALLOCATE_MAP);
#undef TORQUE_ALLOCATE_MAP
#define TORQUE_ALLOCATE_VARSIZE_MAP(NAME, Name, name) \
  /* The DescriptorArray map is pre-allocated and initialized above. */ \
  if (NAME != DESCRIPTOR_ARRAY_TYPE) { \
    ALLOCATE_VARSIZE_MAP(NAME, name) \
  }
    TORQUE_DEFINED_VARSIZE_INSTANCE_TYPE_LIST(TORQUE_ALLOCATE_VARSIZE_MAP);
#undef TORQUE_ALLOCATE_VARSIZE_MAP
    ALLOCATE_VARSIZE_MAP(ORDERED_HASH_MAP_TYPE, ordered_hash_map)
    ALLOCATE_VARSIZE_MAP(ORDERED_HASH_SET_TYPE, ordered_hash_set)
    ALLOCATE_VARSIZE_MAP(SIMPLE_NUMBER_DICTIONARY_TYPE,
                         simple_number_dictionary)
    ALLOCATE_VARSIZE_MAP(SIMPLE_NAME_DICTIONARY_TYPE, simple_name_dictionary)
    ALLOCATE_VARSIZE_MAP(NAME_TO_INDEX_HASH_TABLE_TYPE,
                         name_to_index_hash_table)
    ALLOCATE_VARSIZE_MAP(DOUBLE_STRING_CACHE_TYPE, double_string_cache)
    ALLOCATE_VARSIZE_MAP(EMBEDDER_DATA_ARRAY_TYPE, embedder_data_array)
    ALLOCATE_VARSIZE_MAP(EPHEMERON_HASH_TABLE_TYPE, ephemeron_hash_table)
    ALLOCATE_VARSIZE_MAP(SCRIPT_CONTEXT_TABLE_TYPE, script_context_table)
    ALLOCATE_VARSIZE_MAP(OBJECT_BOILERPLATE_DESCRIPTION_TYPE,
                         object_boilerplate_description)
    ALLOCATE_VARSIZE_MAP(COVERAGE_INFO_TYPE, coverage_info);
    ALLOCATE_VARSIZE_MAP(REG_EXP_MATCH_INFO_TYPE, regexp_match_info);
    ALLOCATE_MAP(REG_EXP_DATA_TYPE, RegExpData::kSize, regexp_data);
    ALLOCATE_MAP(ATOM_REG_EXP_DATA_TYPE, AtomRegExpData::kSize,
                 atom_regexp_data);
    ALLOCATE_MAP(IR_REG_EXP_DATA_TYPE, IrRegExpData::kSize, ir_regexp_data);
    ALLOCATE_MAP(SOURCE_TEXT_MODULE_TYPE, SourceTextModule::kSize,
                 source_text_module)
    ALLOCATE_MAP(SYNTHETIC_MODULE_TYPE, SyntheticModule::kSize,
                 synthetic_module)
    ALLOCATE_MAP(CONTEXT_CELL_TYPE, sizeof(ContextCell), context_cell)
    IF_WASM(ALLOCATE_MAP, WASM_IMPORT_DATA_TYPE, WasmImportData::kSize,
            wasm_import_data)
    IF_WASM(ALLOCATE_MAP, WASM_CAPI_FUNCTION_DATA_TYPE,
            WasmCapiFunctionData::kSize, wasm_capi_function_data)
    IF_WASM(ALLOCATE_MAP, WASM_EXPORTED_FUNCTION_DATA_TYPE,
            WasmExportedFunctionData::kSize, wasm_exported_function_data)
    IF_WASM(ALLOCATE_MAP, WASM_INTERNAL_FUNCTION_TYPE,
            WasmInternalFunction::kSize, wasm_internal_function)
    IF_WASM(ALLOCATE_MAP, WASM_FUNC_REF_TYPE, WasmFuncRef::kSize, wasm_func_ref)
    IF_WASM(ALLOCATE_MAP, WASM_JS_FUNCTION_DATA_TYPE, WasmJSFunctionData::kSize,
            wasm_js_function_data)
    IF_WASM(ALLOCATE_MAP, WASM_RESUME_DATA_TYPE, WasmResumeData::kSize,
            wasm_resume_data)
    IF_WASM(ALLOCATE_MAP, WASM_SUSPENDER_OBJECT_TYPE,
            WasmSuspenderObject::kSize, wasm_suspender_object)
    IF_WASM(ALLOCATE_MAP, WASM_CONTINUATION_OBJECT_TYPE,
            WasmContinuationObject::kSize, wasm_continuation_object)
    IF_WASM(ALLOCATE_MAP, WASM_TYPE_INFO_TYPE, kVariableSizeSentinel,
            wasm_type_info)
    IF_WASM(ALLOCATE_MAP, WASM_NULL_TYPE, kVariableSizeSentinel, wasm_null);
    IF_WASM(ALLOCATE_MAP, WASM_TRUSTED_INSTANCE_DATA_TYPE,
            WasmTrustedInstanceData::kSize, wasm_trusted_instance_data);
    IF_WASM(ALLOCATE_VARSIZE_MAP, WASM_DISPATCH_TABLE_TYPE,
            wasm_dispatch_table);
    ALLOCATE_MAP(WEAK_CELL_TYPE, WeakCell::kSize, weak_cell)
    ALLOCATE_MAP(INTERPRETER_DATA_TYPE, InterpreterData::kSize,
                 interpreter_data)
    ALLOCATE_MAP(SHARED_FUNCTION_INFO_WRAPPER_TYPE,
                 SharedFunctionInfoWrapper::kSize, shared_function_info_wrapper)
    ALLOCATE_MAP(DICTIONARY_TEMPLATE_INFO_TYPE, DictionaryTemplateInfo::kSize,
                 dictionary_template_info)
  }
  return true;
}
References ALLOCATE_MAP, ALLOCATE_VARSIZE_MAP, AllocateMap(), IF_WASM, v8::internal::anonymous_namespace{setup-heap-internal.cc}::is_important_struct(), v8::internal::kReadOnly, v8::internal::anonymous_namespace{setup-heap-internal.cc}::kStructTable, v8::internal::kVariableSizeSentinel, v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), roots_table(), v8::internal::AllocationResult::To(), TORQUE_ALLOCATE_MAP, and TORQUE_ALLOCATE_VARSIZE_MAP.
Referenced by CreateReadOnlyHeapObjects().
CreateMutableApiObjects()
void v8::internal::Heap::CreateMutableApiObjects ()
Definition at line 1388 of file setup-heap-internal.cc.
                                   {
  HandleScope scope(isolate());
  set_message_listeners(*ArrayList::New(isolate(), 2, AllocationType::kOld));
}
References isolate(), v8::internal::kOld, and v8::internal::ArrayList::New().
Referenced by CreateMutableHeapObjects().
CreateMutableHeapObjects()
bool v8::internal::Heap::CreateMutableHeapObjects ()
Definition at line 233 of file setup-heap-internal.cc.
                                    {
  ReadOnlyRoots roots(this);
  // Ensure that all young generation pages are iterable. It must be after heap
  // setup, so that the maps have been created.
  if (new_space()) new_space()->MakeIterable();
  CreateMutableApiObjects();
  // Create initial objects
  CreateInitialMutableObjects();
  CreateInternalAccessorInfoObjects();
  CHECK_EQ(0u, gc_count_);
  set_native_contexts_list(roots.undefined_value());
  set_allocation_sites_list(roots.undefined_value());
  set_dirty_js_finalization_registries_list(roots.undefined_value());
  set_dirty_js_finalization_registries_list_tail(roots.undefined_value());
  return true;
}
References CHECK_EQ, CreateInitialMutableObjects(), CreateInternalAccessorInfoObjects(), CreateMutableApiObjects(), gc_count_, v8::internal::NewSpace::MakeIterable(), new_space(), set_allocation_sites_list(), set_dirty_js_finalization_registries_list(), set_dirty_js_finalization_registries_list_tail(), and set_native_contexts_list().
CreateObjectStats()
void v8::internal::Heap::CreateObjectStats ()
Definition at line 7279 of file heap.cc.
                             {
  if (V8_LIKELY(!TracingFlags::is_gc_stats_enabled())) return;
  if (!live_object_stats_) {
    live_object_stats_.reset(new ObjectStats(this));
  }
  if (!dead_object_stats_) {
    dead_object_stats_.reset(new ObjectStats(this));
  }
}
References dead_object_stats_, v8::internal::TracingFlags::is_gc_stats_enabled(), live_object_stats_, and V8_LIKELY.
CreateReadOnlyApiObjects()
void v8::internal::Heap::CreateReadOnlyApiObjects ()
Definition at line 1393 of file setup-heap-internal.cc.
                                    {
  HandleScope scope(isolate());
  auto info =
      isolate()->factory()->NewInterceptorInfo(AllocationType::kReadOnly);
  set_noop_interceptor_info(*info);
  // Make sure read only heap layout does not depend on the size of
  // ExternalPointer fields.
  StaticRootsEnsureAllocatedSize(info,
                                 3 * kTaggedSize + 7 * kSystemPointerSize);
}
References v8::internal::Isolate::factory(), isolate(), v8::internal::kReadOnly, v8::internal::kSystemPointerSize, v8::internal::kTaggedSize, v8::internal::Factory::NewInterceptorInfo(), and StaticRootsEnsureAllocatedSize().
Referenced by CreateReadOnlyHeapObjects().
CreateReadOnlyHeapObjects()
bool v8::internal::Heap::CreateReadOnlyHeapObjects ()
Definition at line 197 of file setup-heap-internal.cc.
                                     {
  // Create initial maps and important objects.
  if (!CreateEarlyReadOnlyMapsAndObjects()) return false;
  if (!CreateImportantReadOnlyObjects()) return false;
#if V8_STATIC_ROOTS_BOOL
  // The read only heap is sorted such that often used objects are allocated
  // early for their compressed address to fit into 12bit arm immediates.
  ReadOnlySpace* ro_space = isolate()->heap()->read_only_space();
  DCHECK_LT(V8HeapCompressionScheme::CompressAny(ro_space->top()), 0xfff);
  USE(ro_space);
#endif
  if (!CreateLateReadOnlyNonJSReceiverMaps()) return false;
  if (!CreateReadOnlyObjects()) return false;
  // Order is important. JSReceiver maps must come after all non-JSReceiver maps
  // in RO space with a sufficiently large gap in address. Currently there are
  // no JSReceiver instances in RO space.
  //
  // See InstanceTypeChecker::kNonJsReceiverMapLimit.
  if (!CreateLateReadOnlyJSReceiverMaps()) return false;
  CreateReadOnlyApiObjects();
#ifdef DEBUG
  ReadOnlyRoots roots(isolate());
  for (auto pos = RootIndex::kFirstReadOnlyRoot;
       pos <= RootIndex::kLastReadOnlyRoot; ++pos) {
    DCHECK(roots.is_initialized(pos));
  }
  roots.VerifyTypes();
#endif
  return true;
}
References v8::internal::V8HeapCompressionSchemeImpl< Cage >::CompressAny(), CreateEarlyReadOnlyMapsAndObjects(), CreateImportantReadOnlyObjects(), CreateLateReadOnlyJSReceiverMaps(), CreateLateReadOnlyNonJSReceiverMaps(), CreateReadOnlyApiObjects(), CreateReadOnlyObjects(), v8::internal::DCHECK(), DCHECK_LT, v8::internal::Isolate::heap(), v8::internal::ReadOnlyRoots::is_initialized(), isolate(), v8::internal::kFirstReadOnlyRoot, v8::internal::kLastReadOnlyRoot, read_only_space(), v8::internal::ReadOnlySpace::top(), and USE.
CreateReadOnlyObjects()
bool v8::internal::Heap::CreateReadOnlyObjects () [private]
Definition at line 1044 of file setup-heap-internal.cc.
                                 {
  HandleScope initial_objects_handle_scope(isolate());
  Factory* factory = isolate()->factory();
  ReadOnlyRoots roots(this);
  Tagged<HeapObject> obj;
  {
    AllocationResult alloc =
        AllocateRaw(ArrayList::SizeFor(0), AllocationType::kReadOnly);
    if (!alloc.To(&obj)) return false;
    obj->set_map_after_allocation(isolate(), roots.array_list_map(),
                                  SKIP_WRITE_BARRIER);
    // Unchecked to skip failing checks since required roots are uninitialized.
    UncheckedCast<ArrayList>(obj)->set_capacity(0);
    UncheckedCast<ArrayList>(obj)->set_length(0);
  }
  set_empty_array_list(UncheckedCast<ArrayList>(obj));
  {
    AllocationResult alloc = AllocateRaw(
        ObjectBoilerplateDescription::SizeFor(0), AllocationType::kReadOnly);
    if (!alloc.To(&obj)) return false;
    obj->set_map_after_allocation(isolate(),
                                  roots.object_boilerplate_description_map(),
                                  SKIP_WRITE_BARRIER);
    Cast<ObjectBoilerplateDescription>(obj)->set_capacity(0);
    Cast<ObjectBoilerplateDescription>(obj)->set_backing_store_size(0);
    Cast<ObjectBoilerplateDescription>(obj)->set_flags(0);
  }
  set_empty_object_boilerplate_description(
      Cast<ObjectBoilerplateDescription>(obj));
  {
    // Empty array boilerplate description
    AllocationResult alloc =
        Allocate(roots_table().array_boilerplate_description_map(),
                 AllocationType::kReadOnly);
    if (!alloc.To(&obj)) return false;
    Cast<ArrayBoilerplateDescription>(obj)->set_constant_elements(
        roots.empty_fixed_array());
    Cast<ArrayBoilerplateDescription>(obj)->set_elements_kind(
        ElementsKind::PACKED_SMI_ELEMENTS);
  }
  set_empty_array_boilerplate_description(
      Cast<ArrayBoilerplateDescription>(obj));
  // Empty arrays.
  {
    if (!AllocateRaw(ClosureFeedbackCellArray::SizeFor(0),
                     AllocationType::kReadOnly)
             .To(&obj)) {
      return false;
    }
    obj->set_map_after_allocation(
        isolate(), roots.closure_feedback_cell_array_map(), SKIP_WRITE_BARRIER);
    Cast<ClosureFeedbackCellArray>(obj)->set_length(0);
    set_empty_closure_feedback_cell_array(Cast<ClosureFeedbackCellArray>(obj));
  }
  DCHECK(!HeapLayout::InYoungGeneration(roots.empty_fixed_array()));
  // Allocate the empty SwissNameDictionary
  DirectHandle<SwissNameDictionary> empty_swiss_property_dictionary =
      factory->CreateCanonicalEmptySwissNameDictionary();
  set_empty_swiss_property_dictionary(*empty_swiss_property_dictionary);
  StaticRootsEnsureAllocatedSize(empty_swiss_property_dictionary,
                                 8 * kTaggedSize);
  roots.bigint_map()->SetConstructorFunctionIndex(
      Context::BIGINT_FUNCTION_INDEX);
  for (const ConstantStringInit& entry : kNotImportantConstantStringTable) {
    DirectHandle<String> str = factory->InternalizeString(entry.contents);
    roots_table()[entry.index] = str->ptr();
  }
#define ENSURE_SINGLE_CHAR_STRINGS_ARE_SINGLE_CHAR(_, name, contents) \
  static_assert(arraysize(contents) - 1 == 1);
  SINGLE_CHARACTER_INTERNALIZED_STRING_LIST_GENERATOR(
      ENSURE_SINGLE_CHAR_STRINGS_ARE_SINGLE_CHAR,
      /* not used */)
#undef ENSURE_SINGLE_CHAR_STRINGS_ARE_SINGLE_CHAR
  // Finish initializing oddballs after creating the string table.
  Oddball::Initialize(isolate(), factory->undefined_value(), "undefined",
                      factory->undefined_nan_value(), "undefined",
                      Oddball::kUndefined);
  // Initialize the null_value.
  Oddball::Initialize(isolate(), factory->null_value(), "null",
                      direct_handle(Smi::zero(), isolate()), "object",
                      Oddball::kNull);
  // Initialize the true_value.
  Oddball::Initialize(isolate(), factory->true_value(), "true",
                      direct_handle(Smi::FromInt(1), isolate()), "boolean",
                      Oddball::kTrue);
  // Initialize the false_value.
  Oddball::Initialize(isolate(), factory->false_value(), "false",
                      direct_handle(Smi::zero(), isolate()), "boolean",
                      Oddball::kFalse);
  // Initialize the_hole_value.
  Hole::Initialize(isolate(), factory->the_hole_value(),
                   factory->hole_nan_value());
  set_property_cell_hole_value(*factory->NewHole());
  set_hash_table_hole_value(*factory->NewHole());
  set_promise_hole_value(*factory->NewHole());
  set_uninitialized_value(*factory->NewHole());
  set_arguments_marker(*factory->NewHole());
  set_termination_exception(*factory->NewHole());
  set_exception(*factory->NewHole());
  set_optimized_out(*factory->NewHole());
  set_stale_register(*factory->NewHole());
  // Initialize marker objects used during compilation.
  set_self_reference_marker(*factory->NewHole());
  set_basic_block_counters_marker(*factory->NewHole());
  {
    HandleScope handle_scope(isolate());
    NOT_IMPORTANT_PRIVATE_SYMBOL_LIST_GENERATOR(SYMBOL_INIT, /* not used */)
#undef SYMBOL_INIT
  }
  {
    HandleScope handle_scope(isolate());
#define PUBLIC_SYMBOL_INIT(_, name, description) \
  DirectHandle<Symbol> name = factory->NewSymbol(AllocationType::kReadOnly); \
  DirectHandle<String> name##d = factory->InternalizeUtf8String(#description); \
  name->set_description(*name##d); \
  roots_table()[RootIndex::k##name] = name->ptr();
    PUBLIC_SYMBOL_LIST_GENERATOR(PUBLIC_SYMBOL_INIT, /* not used */)
#define WELL_KNOWN_SYMBOL_INIT(_, name, description) \
  DirectHandle<Symbol> name = factory->NewSymbol(AllocationType::kReadOnly); \
  DirectHandle<String> name##d = factory->InternalizeUtf8String(#description); \
  name->set_is_well_known_symbol(true); \
  name->set_description(*name##d); \
  roots_table()[RootIndex::k##name] = name->ptr();
    WELL_KNOWN_SYMBOL_LIST_GENERATOR(WELL_KNOWN_SYMBOL_INIT, /* not used */)
    // Mark "Interesting Symbols" appropriately.
    to_string_tag_symbol->set_is_interesting_symbol(true);
  }
  {
    // All Names that can cause protector invalidation have to be allocated
    // consecutively to allow for fast checks
    // Allocate the symbols's internal strings first, so we don't get
    // interleaved string allocations for the symbols later.
#define ALLOCATE_SYMBOL_STRING(_, name, description) \
  Handle<String> name##symbol_string = \
      factory->InternalizeUtf8String(#description); \
  USE(name##symbol_string);
    SYMBOL_FOR_PROTECTOR_LIST_GENERATOR(ALLOCATE_SYMBOL_STRING,
                                        /* not used */)
    PUBLIC_SYMBOL_FOR_PROTECTOR_LIST_GENERATOR(ALLOCATE_SYMBOL_STRING,
                                               /* not used */)
    WELL_KNOWN_SYMBOL_FOR_PROTECTOR_LIST_GENERATOR(ALLOCATE_SYMBOL_STRING,
                                                   /* not used */)
#undef ALLOCATE_SYMBOL_STRING
#define INTERNALIZED_STRING_INIT(_, name, description) \
  DirectHandle<String> name = factory->InternalizeUtf8String(description); \
  roots_table()[RootIndex::k##name] = name->ptr();
    INTERNALIZED_STRING_FOR_PROTECTOR_LIST_GENERATOR(INTERNALIZED_STRING_INIT,
                                                     /* not used */)
    SYMBOL_FOR_PROTECTOR_LIST_GENERATOR(PUBLIC_SYMBOL_INIT,
                                        /* not used */)
    PUBLIC_SYMBOL_FOR_PROTECTOR_LIST_GENERATOR(PUBLIC_SYMBOL_INIT,
                                               /* not used */)
    WELL_KNOWN_SYMBOL_FOR_PROTECTOR_LIST_GENERATOR(WELL_KNOWN_SYMBOL_INIT,
                                                   /* not used */)
    // Mark "Interesting Symbols" appropriately.
    to_primitive_symbol->set_is_interesting_symbol(true);
#ifdef DEBUG
    roots.VerifyNameForProtectors();
#endif
    roots.VerifyNameForProtectorsPages();
#undef INTERNALIZED_STRING_INIT
#undef PUBLIC_SYMBOL_INIT
#undef WELL_KNOWN_SYMBOL_INIT
  }
  DirectHandle<NumberDictionary> slow_element_dictionary =
      NumberDictionary::New(isolate(), 1, AllocationType::kReadOnly,
                            USE_CUSTOM_MINIMUM_CAPACITY);
  DCHECK(!slow_element_dictionary->HasSufficientCapacityToAdd(1));
  set_empty_slow_element_dictionary(*slow_element_dictionary);
  DirectHandle<RegisteredSymbolTable> empty_symbol_table =
      RegisteredSymbolTable::New(isolate(), 1, AllocationType::kReadOnly,
                                 USE_CUSTOM_MINIMUM_CAPACITY);
  DCHECK(!empty_symbol_table->HasSufficientCapacityToAdd(1));
  set_empty_symbol_table(*empty_symbol_table);
  set_undefined_context_cell(*factory->NewContextCell(
      factory->undefined_value(), AllocationType::kReadOnly));
  // Allocate the empty OrderedHashMap.
  DirectHandle<OrderedHashMap> empty_ordered_hash_map =
      OrderedHashMap::AllocateEmpty(isolate(), AllocationType::kReadOnly)
          .ToHandleChecked();
  set_empty_ordered_hash_map(*empty_ordered_hash_map);
  // Allocate the empty OrderedHashSet.
  DirectHandle<OrderedHashSet> empty_ordered_hash_set =
      OrderedHashSet::AllocateEmpty(isolate(), AllocationType::kReadOnly)
          .ToHandleChecked();
  set_empty_ordered_hash_set(*empty_ordered_hash_set);
  // Allocate the empty FeedbackMetadata.
  DirectHandle<FeedbackMetadata> empty_feedback_metadata =
      factory->NewFeedbackMetadata(0, 0, AllocationType::kReadOnly);
  set_empty_feedback_metadata(*empty_feedback_metadata);
  // Canonical scope arrays.
  DirectHandle<ScopeInfo> global_this_binding =
      ScopeInfo::CreateGlobalThisBinding(isolate());
  set_global_this_binding_scope_info(*global_this_binding);
  DirectHandle<ScopeInfo> empty_function =
      ScopeInfo::CreateForEmptyFunction(isolate());
  set_empty_function_scope_info(*empty_function);
  DirectHandle<ScopeInfo> native_scope_info =
      ScopeInfo::CreateForNativeContext(isolate());
  set_native_scope_info(*native_scope_info);
  DirectHandle<ScopeInfo> shadow_realm_scope_info =
      ScopeInfo::CreateForShadowRealmNativeContext(isolate());
  set_shadow_realm_scope_info(*shadow_realm_scope_info);
  // Allocate FeedbackCell for builtins.
  DirectHandle<FeedbackCell> many_closures_cell =
      factory->NewManyClosuresCell(AllocationType::kReadOnly);
  set_many_closures_cell(*many_closures_cell);
  // Allocate and initialize table for preallocated number strings.
  {
    HandleScope handle_scope(isolate());
    Handle<FixedArray> preallocated_number_string_table =
        factory->NewFixedArray(kPreallocatedNumberStringTableSize,
                               AllocationType::kReadOnly);
    char arr[16];
    base::Vector<char> buffer(arr, arraysize(arr));
    static_assert(kPreallocatedNumberStringTableSize >= 10);
    for (int i = 0; i < 10; ++i) {
      RootIndex root_index = RootsTable::SingleCharacterStringIndex('0' + i);
      Tagged<String> str =
          Cast<String>(factory->read_only_roots().object_at(root_index));
      DCHECK(ReadOnlyHeap::Contains(str));
      preallocated_number_string_table->set(i, str);
    }
    // This code duplicates FactoryBase::SmiToNumber.
    for (int i = 10; i < kPreallocatedNumberStringTableSize; ++i) {
      std::string_view string = IntToStringView(i, buffer);
      Handle<String> str = factory->InternalizeString(
          base::OneByteVector(string.data(), string.length()));
      DCHECK(ReadOnlyHeap::Contains(*str));
      preallocated_number_string_table->set(i, *str);
    }
    set_preallocated_number_string_table(*preallocated_number_string_table);
  }
  // Initialize the wasm null_value.
#ifdef V8_ENABLE_WEBASSEMBLY
  // Allocate the wasm-null object. It is a regular V8 heap object contained in
  // a V8 page.
  // In static-roots builds, it is large enough so that its payload (other than
  // its map word) can be mprotected on OS page granularity. We adjust the
  // layout such that we have a filler object in the current OS page, and the
  // wasm-null map word at the end of the current OS page. The payload then is
  // contained on a separate OS page which can be protected.
  // In non-static-roots builds, it is a regular object of size {kTaggedSize}
  // and does not need padding.
  constexpr size_t kLargestPossibleOSPageSize = 64 * KB;
  static_assert(kLargestPossibleOSPageSize >= kMinimumOSPageSize);
  if (V8_STATIC_ROOTS_BOOL || V8_STATIC_ROOTS_GENERATION_BOOL) {
    // Ensure all of the following lands on the same V8 page.
    constexpr int kOffsetAfterMapWord = HeapObject::kMapOffset + kTaggedSize;
    static_assert(kOffsetAfterMapWord % kObjectAlignment == 0);
    read_only_space_->EnsureSpaceForAllocation(
        kLargestPossibleOSPageSize + WasmNull::kSize - kOffsetAfterMapWord);
    Address next_page = RoundUp(read_only_space_->top() + kOffsetAfterMapWord,
                                kLargestPossibleOSPageSize);
    // Add some filler to end up right before an OS page boundary.
    int filler_size = static_cast<int>(next_page - read_only_space_->top() -
                                       kOffsetAfterMapWord);
    // TODO(v8:7748) Depending on where we end up this might actually not hold,
    // in which case we would need to use a one or two-word filler.
    CHECK(filler_size > 2 * kTaggedSize);
    Tagged<HeapObject> filler =
        allocator()->AllocateRawWith<HeapAllocator::kRetryOrFail>(
            filler_size, AllocationType::kReadOnly, AllocationOrigin::kRuntime,
            AllocationAlignment::kTaggedAligned);
    CreateFillerObjectAt(filler.address(), filler_size,
                         ClearFreedMemoryMode::kClearFreedMemory);
    set_wasm_null_padding(filler);
    CHECK_EQ(read_only_space_->top() + kOffsetAfterMapWord, next_page);
  } else {
    set_wasm_null_padding(roots.undefined_value());
  }
  // Finally, allocate the wasm-null object.
  {
    Tagged<HeapObject> wasm_null_obj;
    CHECK(AllocateRaw(WasmNull::kSize, AllocationType::kReadOnly)
              .To(&wasm_null_obj));
    // No need to initialize the payload since it's either empty or unmapped.
    CHECK_IMPLIES(!(V8_STATIC_ROOTS_BOOL || V8_STATIC_ROOTS_GENERATION_BOOL),
                  WasmNull::kSize == sizeof(Tagged_t));
    wasm_null_obj->set_map_after_allocation(isolate(), roots.wasm_null_map(),
                                            SKIP_WRITE_BARRIER);
    set_wasm_null(Cast<WasmNull>(wasm_null_obj));
    if (V8_STATIC_ROOTS_BOOL || V8_STATIC_ROOTS_GENERATION_BOOL) {
      CHECK_EQ(read_only_space_->top() % kLargestPossibleOSPageSize, 0);
    }
  }
#endif
  return true;
}
References v8::internal::Tagged< HeapObject >::address(), Allocate(), ALLOCATE_SYMBOL_STRING, v8::internal::OrderedHashSet::AllocateEmpty(), v8::internal::OrderedHashMap::AllocateEmpty(), AllocateRaw(), v8::internal::HeapAllocator::AllocateRawWith(), allocator(), arraysize, CHECK, CHECK_EQ, CHECK_IMPLIES, v8::internal::ReadOnlyHeap::Contains(), v8::internal::Factory::CreateCanonicalEmptySwissNameDictionary(), CreateFillerObjectAt(), v8::internal::ScopeInfo::CreateForEmptyFunction(), v8::internal::ScopeInfo::CreateForNativeContext(), v8::internal::ScopeInfo::CreateForShadowRealmNativeContext(), v8::internal::ScopeInfo::CreateGlobalThisBinding(), v8::internal::DCHECK(), v8::internal::direct_handle(), ENSURE_SINGLE_CHAR_STRINGS_ARE_SINGLE_CHAR, v8::internal::ReadOnlySpace::EnsureSpaceForAllocation(), v8::internal::Isolate::factory(), v8::internal::Smi::FromInt(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::Hole::Initialize(), v8::internal::Oddball::Initialize(), INTERNALIZED_STRING_FOR_PROTECTOR_LIST_GENERATOR, INTERNALIZED_STRING_INIT, v8::internal::Factory::InternalizeString(), v8::internal::IntToStringView(), v8::internal::HeapLayout::InYoungGeneration(), isolate(), v8::internal::KB, v8::internal::kClearFreedMemory, v8::internal::Oddball::kFalse, v8::internal::HeapObject::kMapOffset, kMinimumOSPageSize, v8::internal::anonymous_namespace{setup-heap-internal.cc}::kNotImportantConstantStringTable, v8::internal::Oddball::kNull, v8::internal::kObjectAlignment, v8::internal::kPreallocatedNumberStringTableSize, v8::internal::kReadOnly, v8::internal::HeapAllocator::kRetryOrFail, v8::internal::kRuntime, v8::internal::WasmNull::kSize, v8::internal::kTaggedAligned, v8::internal::kTaggedSize, v8::internal::Oddball::kTrue, v8::internal::Oddball::kUndefined, v8::internal::length, v8::internal::anonymous_namespace{intl-objects.cc}::New(), v8::internal::Factory::NewContextCell(), v8::internal::FactoryBase< Impl >::NewFeedbackMetadata(), v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::Factory::NewHole(), v8::internal::Factory::NewManyClosuresCell(), NOT_IMPORTANT_PRIVATE_SYMBOL_LIST_GENERATOR, v8::internal::ReadOnlyRoots::object_at(), v8::base::OneByteVector(), v8::internal::PACKED_SMI_ELEMENTS, PUBLIC_SYMBOL_FOR_PROTECTOR_LIST_GENERATOR, PUBLIC_SYMBOL_INIT, PUBLIC_SYMBOL_LIST_GENERATOR, v8::internal::Factory::read_only_roots(), read_only_space_, roots_table(), RoundUp(), SINGLE_CHARACTER_INTERNALIZED_STRING_LIST_GENERATOR, v8::internal::RootsTable::SingleCharacterStringIndex(), v8::internal::TaggedArrayBase< ArrayList, ArrayListShape >::SizeFor(), v8::internal::TaggedArrayBase< ObjectBoilerplateDescription, ObjectBoilerplateDescriptionShape >::SizeFor(), v8::internal::TaggedArrayBase< ClosureFeedbackCellArray, ClosureFeedbackCellArrayShape >::SizeFor(), v8::internal::SKIP_WRITE_BARRIER, StaticRootsEnsureAllocatedSize(), SYMBOL_FOR_PROTECTOR_LIST_GENERATOR, SYMBOL_INIT, v8::internal::AllocationResult::To(), v8::internal::ReadOnlySpace::top(), v8::internal::USE_CUSTOM_MINIMUM_CAPACITY, V8_STATIC_ROOTS_BOOL, V8_STATIC_ROOTS_GENERATION_BOOL, v8::internal::ReadOnlyRoots::VerifyNameForProtectorsPages(), WELL_KNOWN_SYMBOL_FOR_PROTECTOR_LIST_GENERATOR, WELL_KNOWN_SYMBOL_INIT, WELL_KNOWN_SYMBOL_LIST_GENERATOR, and v8::internal::Smi::zero().
Referenced by CreateReadOnlyHeapObjects().
current_or_last_garbage_collector()
GarbageCollector v8::internal::Heap::current_or_last_garbage_collector () const [inline]
Definition at line 1414 of file heap.h.
                                                             {
    return current_or_last_garbage_collector_;
  }
CurrentHeapGrowingMode()
Heap::HeapGrowingMode v8::internal::Heap::CurrentHeapGrowingMode () [private]
Definition at line 5578 of file heap.cc.
                                                 {
  if (ShouldReduceMemory() || v8_flags.stress_compaction) {
    return Heap::HeapGrowingMode::kMinimal;
  }
  if (ShouldOptimizeForMemoryUsage()) {
    return Heap::HeapGrowingMode::kConservative;
  }
  if (memory_reducer() != nullptr && memory_reducer()->ShouldGrowHeapSlowly()) {
    return Heap::HeapGrowingMode::kSlow;
  }
  return Heap::HeapGrowingMode::kDefault;
}
References kConservative, kDefault, kMinimal, kSlow, memory_reducer(), ShouldOptimizeForMemoryUsage(), ShouldReduceMemory(), and v8::internal::v8_flags.
Referenced by ShrinkOldGenerationAllocationLimitIfNotConfigured().
DeactivateMajorGCInProgressFlag()
void v8::internal::Heap::DeactivateMajorGCInProgressFlag ()
Definition at line 3756 of file heap.cc.
                                           {
  DCHECK(v8_flags.sticky_mark_bits);
  DCHECK_NULL(new_space());
  auto deactivate_space = [](auto& space) {
    for (auto* metadata : space) {
      metadata->Chunk()->ResetMajorGCInProgress();
    }
  };
  deactivate_space(*old_space());
  deactivate_space(*lo_space());
  {
    RwxMemoryWriteScope scope("For writing flags.");
    deactivate_space(*code_space());
    deactivate_space(*code_lo_space());
  }
  if (isolate()->is_shared_space_isolate()) {
    deactivate_space(*shared_space());
    deactivate_space(*shared_lo_space());
  }
  deactivate_space(*trusted_space());
  deactivate_space(*trusted_lo_space());
}
References code_lo_space(), code_space(), v8::internal::DCHECK(), DCHECK_NULL, isolate(), lo_space(), new_space(), old_space(), shared_lo_space(), shared_space(), space(), trusted_lo_space(), trusted_space(), and v8::internal::v8_flags.
DecrementExternalBackingStoreBytes()
void v8::internal::Heap::DecrementExternalBackingStoreBytes (ExternalBackingStoreType type, size_t amount) [inline], [private]
Definition at line 409 of file heap-inl.h.
                                                             {
  base::CheckedDecrement(&backing_store_bytes_, static_cast<uint64_t>(amount),
                         std::memory_order_relaxed);
}
References backing_store_bytes_.
Referenced by v8::internal::Space::DecrementExternalBackingStoreBytes(), and v8::internal::ArrayBufferSweeper::DecrementExternalMemoryCounters().
DefaulMaxHeapSize()
size_t v8::internal::Heap::DefaulMaxHeapSize () [static]
Definition at line 5089 of file heap.cc.
{ return 1024u * HeapLimitMultiplier() * MB; }
References HeapLimitMultiplier(), and v8::internal::MB.
Referenced by v8::internal::MemoryController< Trait >::MaxGrowingFactor(), MaxOldGenerationSizeFromPhysicalMemory(), and OldGenerationToSemiSpaceRatio().
DefaulMinHeapSize()
size_t v8::internal::Heap::DefaulMinHeapSize () [static]
Definition at line 5086 of file heap.cc.
{ return 128u * HeapLimitMultiplier() * MB; }
References HeapLimitMultiplier(), and v8::internal::MB.
Referenced by HeapSizeFromPhysicalMemory(), and v8::internal::MemoryController< Trait >::MaxGrowingFactor().
DefaultInitialOldGenerationSize()
size_t v8::internal::Heap::DefaultInitialOldGenerationSize () [static]
Definition at line 5047 of file heap.cc.
                                             {
  return 256 * MB * HeapLimitMultiplier();
}
References HeapLimitMultiplier(), and v8::internal::MB.
Referenced by ConfigureHeap().
DefaultMaxSemiSpaceSize()
size_t v8::internal::Heap::DefaultMaxSemiSpaceSize () [static]
Definition at line 5062 of file heap.cc.
                                     {
  if (v8_flags.minor_ms) {
    static constexpr size_t kMinorMsMaxCapacity = 72 * kPointerMultiplier * MB;
    return RoundUp(kMinorMsMaxCapacity, PageMetadata::kPageSize);
  }
  // Compute default max semi space size for Scavenger.
  static constexpr size_t kScavengerDefaultMaxCapacity =
      32 * kPointerMultiplier * MB;
  size_t max_semi_space_size = kScavengerDefaultMaxCapacity;
#if defined(ANDROID)
  if (!v8_flags.high_end_android) {
    // Note that kPointerMultiplier is always 1 on Android.
    static constexpr size_t kAndroidNonHighEndMaxCapacity =
        8 * kPointerMultiplier * MB;
    max_semi_space_size = kAndroidNonHighEndMaxCapacity;
  }
#endif
  return RoundUp(max_semi_space_size, PageMetadata::kPageSize);
}
References v8::internal::MutablePageMetadata::kPageSize, kPointerMultiplier, v8::internal::MB, RoundUp(), and v8::internal::v8_flags.
Referenced by AllocateExternalBackingStore(), AllocatorLimitOnMaxOldGenerationSize(), ConfigureHeap(), OldGenerationToSemiSpaceRatio(), and YoungGenerationSizeFromOldGenerationSize().
DefaultMinSemiSpaceSize()
size_t v8::internal::Heap::DefaultMinSemiSpaceSize () [static]
Definition at line 5057 of file heap.cc.
                                     {
  return RoundUp(512 * KB * kPointerMultiplier, PageMetadata::kPageSize);
}
References v8::internal::KB, v8::internal::MutablePageMetadata::kPageSize, kPointerMultiplier, and RoundUp().
Referenced by ConfigureHeap(), MinYoungGenerationSize(), and YoungGenerationSizeFromOldGenerationSize().
DeoptMarkedAllocationSites()
void v8::internal::Heap::DeoptMarkedAllocationSites ()
Definition at line 1044 of file heap.cc.
                                      {
  // TODO(hpayer): If iterating over the allocation sites list becomes a
  // performance issue, use a cache data structure in heap instead.
  ForeachAllocationSite(
      allocation_sites_list(), [this](Tagged<AllocationSite> site) {
        if (site->deopt_dependent_code()) {
          DependentCode::MarkCodeForDeoptimization(
              isolate_, site,
              DependentCode::kAllocationSiteTenuringChangedGroup);
          site->set_deopt_dependent_code(false);
        }
      });
  Deoptimizer::DeoptimizeMarkedCode(isolate_);
}
References allocation_sites_list(), v8::internal::Deoptimizer::DeoptimizeMarkedCode(), ForeachAllocationSite(), and isolate_.
Referenced by v8::internal::StackGuard::HandleInterrupts().
DequeueDirtyJSFinalizationRegistry()
MaybeDirectHandle< JSFinalizationRegistry > v8::internal::Heap::DequeueDirtyJSFinalizationRegistry ()
Definition at line 7080 of file heap.cc.
                                         {
  // Take a FinalizationRegistry from the head of the dirty list for fairness.
  if (HasDirtyJSFinalizationRegistries()) {
    DirectHandle<JSFinalizationRegistry> head(
        Cast<JSFinalizationRegistry>(dirty_js_finalization_registries_list()),
        isolate());
    set_dirty_js_finalization_registries_list(head->next_dirty());
    head->set_next_dirty(ReadOnlyRoots(this).undefined_value());
    if (*head == dirty_js_finalization_registries_list_tail()) {
      set_dirty_js_finalization_registries_list_tail(
          ReadOnlyRoots(this).undefined_value());
    }
    return head;
  }
  return {};
}
References dirty_js_finalization_registries_list(), dirty_js_finalization_registries_list_tail(), HasDirtyJSFinalizationRegistries(), isolate(), ReadOnlyRoots, set_dirty_js_finalization_registries_list(), and set_dirty_js_finalization_registries_list_tail().
Referenced by v8::internal::FinalizationRegistryCleanupTask::RunInternal().
deserialization_complete()
bool v8::internal::Heap::deserialization_complete () const [inline]
Definition at line 681 of file heap.h.
{ return deserialization_complete_; }
Referenced by v8::internal::IncrementalMarking::CanBeStarted(), IsPendingAllocationInternal(), v8::internal::LocalHeap::LocalHeap(), NotifyOldGenerationExpansion(), PauseConcurrentThreadsInClients(), ShouldExpandOldGenerationOnSlowAllocation(), ShouldExpandYoungGenerationOnSlowAllocation(), and v8::internal::StressConcurrentAllocationObserver::Step().
DetachArrayBufferExtension()
void v8::internal::Heap::DetachArrayBufferExtension (ArrayBufferExtension * extension)
Definition at line 4395 of file heap.cc.
                                                                     {
  // ArrayBufferSweeper is managing all counters and updating Heap counters.
  return array_buffer_sweeper_->Detach(extension);
}
References array_buffer_sweeper_.
Referenced by v8::internal::JSArrayBuffer::DetachInternal().
dirty_js_finalization_registries_list()
Tagged<Object> v8::internal::Heap::dirty_js_finalization_registries_list () [inline]
Definition at line 521 of file heap.h.
                                                         {
    return dirty_js_finalization_registries_list_;
  }
Referenced by v8::internal::StartupSerializer::CheckNoDirtyFinalizationRegistries(), DequeueDirtyJSFinalizationRegistry(), EnqueueDirtyJSFinalizationRegistry(), HasDirtyJSFinalizationRegistries(), ProcessDirtyJSFinalizationRegistries(), ProcessWeakListRoots(), and RemoveDirtyFinalizationRegistriesOnContext().
dirty_js_finalization_registries_list_tail()
Tagged<Object> v8::internal::Heap::dirty_js_finalization_registries_list_tail () [inline]
Definition at line 527 of file heap.h.
                                                              {
    return dirty_js_finalization_registries_list_tail_;
  }
Referenced by v8::internal::StartupSerializer::CheckNoDirtyFinalizationRegistries(), DequeueDirtyJSFinalizationRegistry(), EnqueueDirtyJSFinalizationRegistry(), and ProcessWeakListRoots().
DisableInlineAllocation()
void v8::internal::Heap::DisableInlineAllocation ()
Definition at line 5738 of file heap.cc.
                                   {
  inline_allocation_enabled_ = false;
  FreeMainThreadLinearAllocationAreas();
}
References FreeMainThreadLinearAllocationAreas(), and inline_allocation_enabled_.
Referenced by AddHeapObjectAllocationTracker(), and v8::internal::Isolate::Init().
DumpJSONHeapStatistics()
void v8::internal::Heap::DumpJSONHeapStatistics (std::stringstream & stream)
Definition at line 753 of file heap.cc.
                                                         {
  HeapStatistics stats;
  reinterpret_cast<v8::Isolate*>(isolate())->GetHeapStatistics(&stats);
// clang-format off
#define DICT(s) "{" << s << "}"
#define LIST(s) "[" << s << "]"
#define QUOTE(s) "\"" << s << "\""
#define MEMBER(s) QUOTE(s) << ":"
  auto SpaceStatistics = [this](int space_index) {
    HeapSpaceStatistics space_stats;
    reinterpret_cast<v8::Isolate*>(isolate())->GetHeapSpaceStatistics(
        &space_stats, space_index);
    std::stringstream stream;
    stream << DICT(
      MEMBER("name")
        << QUOTE(ToString(
              static_cast<AllocationSpace>(space_index)))
        << ","
      MEMBER("size") << space_stats.space_size() << ","
      MEMBER("used_size") << space_stats.space_used_size() << ","
      MEMBER("available_size") << space_stats.space_available_size() << ","
      MEMBER("physical_size") << space_stats.physical_space_size());
    return stream.str();
  };
  stream << DICT(
    MEMBER("isolate") << QUOTE(reinterpret_cast<void*>(isolate())) << ","
    MEMBER("id") << gc_count() << ","
    MEMBER("time_ms") << isolate()->time_millis_since_init() << ","
    MEMBER("total_heap_size") << stats.total_heap_size() << ","
    MEMBER("total_heap_size_executable")
      << stats.total_heap_size_executable() << ","
    MEMBER("total_physical_size") << stats.total_physical_size() << ","
    MEMBER("total_available_size") << stats.total_available_size() << ","
    MEMBER("used_heap_size") << stats.used_heap_size() << ","
    MEMBER("heap_size_limit") << stats.heap_size_limit() << ","
    MEMBER("malloced_memory") << stats.malloced_memory() << ","
    MEMBER("external_memory") << stats.external_memory() << ","
    MEMBER("peak_malloced_memory") << stats.peak_malloced_memory() << ","
    MEMBER("spaces") << LIST(
      SpaceStatistics(RO_SPACE) << "," <<
      SpaceStatistics(NEW_SPACE) << "," <<
      SpaceStatistics(OLD_SPACE) << "," <<
      SpaceStatistics(CODE_SPACE) << "," <<
      SpaceStatistics(LO_SPACE) << "," <<
      SpaceStatistics(CODE_LO_SPACE) << "," <<
      SpaceStatistics(NEW_LO_SPACE) << "," <<
      SpaceStatistics(TRUSTED_SPACE) << "," <<
      SpaceStatistics(TRUSTED_LO_SPACE)));
#undef DICT
#undef LIST
#undef QUOTE
#undef MEMBER
  // clang-format on
}
References v8::internal::CODE_LO_SPACE, v8::internal::CODE_SPACE, DICT, v8::HeapStatistics::external_memory(), gc_count(), v8::HeapStatistics::heap_size_limit(), isolate(), LIST, v8::internal::LO_SPACE, v8::HeapStatistics::malloced_memory(), MEMBER, v8::internal::NEW_LO_SPACE, v8::internal::NEW_SPACE, v8::internal::OLD_SPACE, v8::HeapStatistics::peak_malloced_memory(), v8::HeapSpaceStatistics::physical_space_size(), QUOTE, v8::internal::RO_SPACE, v8::HeapSpaceStatistics::space_available_size(), v8::HeapSpaceStatistics::space_size(), v8::HeapSpaceStatistics::space_used_size(), v8::internal::ToString(), v8::HeapStatistics::total_available_size(), v8::HeapStatistics::total_heap_size(), v8::HeapStatistics::total_heap_size_executable(), v8::HeapStatistics::total_physical_size(), v8::internal::TRUSTED_LO_SPACE, v8::internal::TRUSTED_SPACE, and v8::HeapStatistics::used_heap_size().
Referenced by v8::internal::GCTracer::StopObservablePause().
EagerlyFreeExternalMemoryAndWasmCode()
void v8::internal::Heap::EagerlyFreeExternalMemoryAndWasmCode () [private]
Definition at line 4351 of file heap.cc.
                                                {
#if V8_ENABLE_WEBASSEMBLY
  if (v8_flags.flush_liftoff_code) {
    wasm::GetWasmEngine()->FlushLiftoffCode();
  }
#endif // V8_ENABLE_WEBASSEMBLY
  CompleteArrayBufferSweeping(this);
}
References v8::internal::anonymous_namespace{heap.cc}::CompleteArrayBufferSweeping(), v8::internal::wasm::WasmEngine::FlushLiftoffCode(), v8::internal::wasm::GetWasmEngine(), and v8::internal::v8_flags.
Referenced by CollectAllAvailableGarbage(), and CollectGarbageOnMemoryPressure().
EmbedderAllocationCounter()
size_t v8::internal::Heap::EmbedderAllocationCounter () const
Definition at line 7275 of file heap.cc.
                                             {
  return cpp_heap_ ? CppHeap::From(cpp_heap_)->allocated_size() : 0;
}
References v8::internal::CppHeap::allocated_size(), cpp_heap_, and v8::internal::CppHeap::From().
Referenced by v8::internal::GCTracer::StartInSafepoint().
EmbedderSizeOfObjects()
size_t v8::internal::Heap::EmbedderSizeOfObjects () const
Definition at line 5419 of file heap.cc.
                                         {
  return cpp_heap_ ? CppHeap::From(cpp_heap_)->used_size() : 0;
}
References cpp_heap_, v8::internal::CppHeap::From(), and v8::internal::CppHeap::used_size().
Referenced by GlobalSizeOfObjects(), v8::internal::IncrementalMarking::IsBelowActivationThresholds(), MarkCompact(), and RecomputeLimitsAfterLoadingIfNeeded().
EnableInlineAllocation()
void v8::internal::Heap::EnableInlineAllocation ()
Definition at line 5736 of file heap.cc.
{ inline_allocation_enabled_ = true; }
References inline_allocation_enabled_.
Referenced by RemoveHeapObjectAllocationTracker().
EnqueueDirtyJSFinalizationRegistry()
void v8::internal::Heap::EnqueueDirtyJSFinalizationRegistry (Tagged< JSFinalizationRegistry > finalization_registry, std::function< void(Tagged< HeapObject > object, ObjectSlot slot, Tagged< Object > target)> gc_notify_updated_slot)
Definition at line 7050 of file heap.cc.
                                {
  // Add a FinalizationRegistry to the tail of the dirty list.
  DCHECK(!HasDirtyJSFinalizationRegistries() ||
         IsJSFinalizationRegistry(dirty_js_finalization_registries_list()));
  DCHECK(IsUndefined(finalization_registry->next_dirty(), isolate()));
  DCHECK(!finalization_registry->scheduled_for_cleanup());
  finalization_registry->set_scheduled_for_cleanup(true);
  if (IsUndefined(dirty_js_finalization_registries_list_tail(), isolate())) {
    DCHECK(IsUndefined(dirty_js_finalization_registries_list(), isolate()));
    set_dirty_js_finalization_registries_list(finalization_registry);
    // dirty_js_finalization_registries_list_ is rescanned by
    // ProcessWeakListRoots.
  } else {
    Tagged<JSFinalizationRegistry> tail = Cast<JSFinalizationRegistry>(
        dirty_js_finalization_registries_list_tail());
    tail->set_next_dirty(finalization_registry);
    gc_notify_updated_slot(
        tail, tail->RawField(JSFinalizationRegistry::kNextDirtyOffset),
        finalization_registry);
  }
  set_dirty_js_finalization_registries_list_tail(finalization_registry);
  // dirty_js_finalization_registries_list_tail_ is rescanned by
  // ProcessWeakListRoots.
}
References v8::internal::DCHECK(), dirty_js_finalization_registries_list(), dirty_js_finalization_registries_list_tail(), HasDirtyJSFinalizationRegistries(), isolate(), set_dirty_js_finalization_registries_list(), and set_dirty_js_finalization_registries_list_tail().
Referenced by v8::internal::FinalizationRegistryCleanupTask::RunInternal().
EnsureMinimumRemainingAllocationLimit()
void v8::internal::Heap::EnsureMinimumRemainingAllocationLimit (size_t at_least_remaining) [private]
Definition at line 3253 of file heap.cc.
                                                                          {
  base::MutexGuard guard(old_space()->mutex());
  size_t new_old_generation_allocation_limit =
      std::max(OldGenerationConsumedBytes() + at_least_remaining,
               old_generation_allocation_limit());
  new_old_generation_allocation_limit =
      std::max(new_old_generation_allocation_limit, min_old_generation_size());
  new_old_generation_allocation_limit =
      std::min(new_old_generation_allocation_limit, max_old_generation_size());
  size_t new_global_allocation_limit = std::max(
      GlobalConsumedBytes() + GlobalMemorySizeFromV8Size(at_least_remaining),
      global_allocation_limit());
  new_global_allocation_limit =
      std::max(new_global_allocation_limit, min_global_memory_size_);
  new_global_allocation_limit =
      std::min(new_global_allocation_limit, max_global_memory_size_);
  SetOldGenerationAndGlobalAllocationLimit(new_old_generation_allocation_limit,
                                           new_global_allocation_limit);
  // Reset using_initial_limit() to prevent the sweeper from overwriting this
  // limit right after this operation.
  set_using_initial_limit(true);
}
References global_allocation_limit(), GlobalConsumedBytes(), v8::internal::anonymous_namespace{heap.cc}::GlobalMemorySizeFromV8Size(), max_global_memory_size_, max_old_generation_size(), min_global_memory_size_, min_old_generation_size(), old_generation_allocation_limit(), old_space(), OldGenerationConsumedBytes(), set_using_initial_limit(), and SetOldGenerationAndGlobalAllocationLimit().
Referenced by NotifyContextDisposed().
EnsureQuarantinedPagesSweepingCompleted()
void v8::internal::Heap::EnsureQuarantinedPagesSweepingCompleted ()
Definition at line 7548 of file heap.cc.
                                                   {
  if (v8_flags.minor_ms) {
    return;
  }
  scavenger_collector_->CompleteSweepingQuarantinedPagesIfNeeded();
}
References scavenger_collector_, and v8::internal::v8_flags.
Referenced by EnsureSweepingCompleted(), EnsureYoungSweepingCompleted(), and v8::internal::MarkCompactCollector::MarkObjectsFromClientHeap().
EnsureSweepingCompleted()
void v8::internal::Heap::EnsureSweepingCompleted (SweepingForcedFinalizationMode mode)
Definition at line 7474 of file heap.cc.
                                                                      {
  CompleteArrayBufferSweeping(this);
  EnsureQuarantinedPagesSweepingCompleted();
  if (sweeper()->sweeping_in_progress()) {
    bool was_minor_sweeping_in_progress = minor_sweeping_in_progress();
    bool was_major_sweeping_in_progress = major_sweeping_in_progress();
    sweeper()->EnsureMajorCompleted();
    if (was_major_sweeping_in_progress) {
      TRACE_GC_EPOCH_WITH_FLOW(tracer(), GCTracer::Scope::MC_COMPLETE_SWEEPING,
                               ThreadKind::kMain,
                               sweeper_->GetTraceIdForFlowEvent(
                                   GCTracer::Scope::MC_COMPLETE_SWEEPING),
                               TRACE_EVENT_FLAG_FLOW_IN);
      old_space()->RefillFreeList();
      code_space()->RefillFreeList();
      if (shared_space()) {
        shared_space()->RefillFreeList();
        shared_trusted_space()->RefillFreeList();
      }
      trusted_space()->RefillFreeList();
    } else if (v8_flags.sticky_mark_bits) {
      // With sticky markbits there is no separate young gen. Minor sweeping
      // will thus sweep pages in old space, so old space freelist should be
      // refilled.
      DCHECK(was_minor_sweeping_in_progress);
      old_space()->RefillFreeList();
    }
    if (!v8_flags.sticky_mark_bits && v8_flags.minor_ms && use_new_space() &&
        was_minor_sweeping_in_progress) {
      TRACE_GC_EPOCH_WITH_FLOW(
          tracer(), GCTracer::Scope::MINOR_MS_COMPLETE_SWEEPING,
          ThreadKind::kMain,
          sweeper_->GetTraceIdForFlowEvent(
              GCTracer::Scope::MINOR_MS_COMPLETE_SWEEPING),
          TRACE_EVENT_FLAG_FLOW_IN | TRACE_EVENT_FLAG_FLOW_OUT);
      paged_new_space()->paged_space()->RefillFreeList();
    }
    tracer()->NotifyFullSweepingCompletedAndStopCycleIfFinished();
#ifdef VERIFY_HEAP
    if (v8_flags.verify_heap) {
      EvacuationVerifier verifier(this);
      verifier.Run();
    }
#endif
  }
  if (mode == SweepingForcedFinalizationMode::kUnifiedHeap && cpp_heap()) {
    // Ensure that sweeping is also completed for the C++ managed heap, if one
    // exists.
    CppHeap::From(cpp_heap())->FinishSweepingIfRunning();
    DCHECK(!CppHeap::From(cpp_heap())->sweeper().IsSweepingInProgress());
  }
  DCHECK_IMPLIES(
      mode == SweepingForcedFinalizationMode::kUnifiedHeap || !cpp_heap(),
      !tracer()->IsSweepingInProgress());
  if (v8_flags.external_memory_accounted_in_global_limit) {
    if (!using_initial_limit()) {
      auto new_limits = ComputeNewAllocationLimits(this);
      SetOldGenerationAndGlobalAllocationLimit(
          new_limits.old_generation_allocation_limit,
          new_limits.global_allocation_limit);
    }
  }
}
References code_space(), v8::internal::anonymous_namespace{heap.cc}::CompleteArrayBufferSweeping(), ComputeNewAllocationLimits(), cpp_heap(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::Sweeper::EnsureMajorCompleted(), EnsureQuarantinedPagesSweepingCompleted(), v8::internal::CppHeap::FinishSweepingIfRunning(), v8::internal::CppHeap::From(), v8::internal::kMain, kUnifiedHeap, major_sweeping_in_progress(), minor_sweeping_in_progress(), mode(), v8::internal::GCTracer::NotifyFullSweepingCompletedAndStopCycleIfFinished(), old_space(), paged_new_space(), v8::internal::PagedNewSpace::paged_space(), v8::internal::PagedSpaceBase::RefillFreeList(), SetOldGenerationAndGlobalAllocationLimit(), shared_space(), shared_trusted_space(), sweeper(), sweeper_, sweeping_in_progress(), TRACE_EVENT_FLAG_FLOW_IN, TRACE_EVENT_FLAG_FLOW_OUT, TRACE_GC_EPOCH_WITH_FLOW, tracer(), trusted_space(), use_new_space(), using_initial_limit(), and v8::internal::v8_flags.
Referenced by CompleteSweepingFull(), FinishSweepingIfOutOfWork(), MakeHeapIterable(), and v8::internal::ReadOnlyHeap::OnCreateHeapObjectsComplete().
EnsureSweepingCompletedForObject()
void v8::internal::Heap::EnsureSweepingCompletedForObject (Tagged< HeapObject > object)
Definition at line 2543 of file heap.cc.
                                                                     {
  if (!sweeping_in_progress()) return;
  MemoryChunk* chunk = MemoryChunk::FromHeapObject(object);
  if (chunk->InReadOnlySpace()) return;
  MutablePageMetadata* mutable_page =
      MutablePageMetadata::cast(chunk->Metadata());
  if (mutable_page->SweepingDone()) return;
  // SweepingDone() is always true for large pages.
  DCHECK(!chunk->IsLargePage());
  PageMetadata* page = PageMetadata::cast(mutable_page);
  sweeper()->EnsurePageIsSwept(page);
}
References v8::internal::MutablePageMetadata::cast(), v8::internal::PageMetadata::cast(), v8::internal::DCHECK(), v8::internal::Sweeper::EnsurePageIsSwept(), v8::internal::MemoryChunk::FromHeapObject(), v8::internal::MemoryChunk::InReadOnlySpace(), v8::internal::MemoryChunk::IsLargePage(), v8::internal::MemoryChunk::Metadata(), sweeper(), sweeping_in_progress(), and v8::internal::MutablePageMetadata::SweepingDone().
Referenced by v8::internal::TranslatedState::InitializeJSObjectAt(), v8::internal::TranslatedState::InitializeObjectWithTaggedFieldsAt(), and v8::internal::FoldedMutableHeapNumberAllocator::~FoldedMutableHeapNumberAllocator().
EnsureYoungSweepingCompleted()
void v8::internal::Heap::EnsureYoungSweepingCompleted ()
Definition at line 7555 of file heap.cc.
                                        {
  CompleteArrayBufferSweeping(this);
  EnsureQuarantinedPagesSweepingCompleted();
  if (!sweeper()->minor_sweeping_in_progress()) return;
  DCHECK(!v8_flags.sticky_mark_bits);
  TRACE_GC_EPOCH_WITH_FLOW(
      tracer(), GCTracer::Scope::MINOR_MS_COMPLETE_SWEEPING, ThreadKind::kMain,
      sweeper_->GetTraceIdForFlowEvent(
          GCTracer::Scope::MINOR_MS_COMPLETE_SWEEPING),
      TRACE_EVENT_FLAG_FLOW_IN);
  sweeper()->EnsureMinorCompleted();
  paged_new_space()->paged_space()->RefillFreeList();
  tracer()->NotifyYoungSweepingCompletedAndStopCycleIfFinished();
}
References v8::internal::anonymous_namespace{heap.cc}::CompleteArrayBufferSweeping(), v8::internal::DCHECK(), v8::internal::Sweeper::EnsureMinorCompleted(), EnsureQuarantinedPagesSweepingCompleted(), v8::internal::kMain, minor_sweeping_in_progress(), v8::internal::GCTracer::NotifyYoungSweepingCompletedAndStopCycleIfFinished(), paged_new_space(), v8::internal::PagedNewSpace::paged_space(), v8::internal::PagedSpaceBase::RefillFreeList(), sweeper(), sweeper_, TRACE_EVENT_FLAG_FLOW_IN, TRACE_GC_EPOCH_WITH_FLOW, tracer(), and v8::internal::v8_flags.
Referenced by CompleteSweepingYoung().
ephemeron_remembered_set()
EphemeronRememberedSet* v8::internal::Heap::ephemeron_remembered_set () [inline]
Definition at line 404 of file heap.h.
                                                     {
    return ephemeron_remembered_set_.get();
  }
Referenced by v8::internal::MinorMarkSweepCollector::ClearNonLiveReferences(), and v8::internal::WriteBarrier::CombinedGenerationalAndSharedEphemeronBarrierSlow().
EvaluateOldSpaceLocalPretenuring()
void v8::internal::Heap::EvaluateOldSpaceLocalPretenuring (uint64_t size_of_objects_before_gc) [private]
Definition at line 3094 of file heap.cc.
                                        {
  uint64_t size_of_objects_after_gc = SizeOfObjects();
  double old_generation_survival_rate =
      (static_cast<double>(size_of_objects_after_gc) * 100) /
      static_cast<double>(size_of_objects_before_gc);
  if (old_generation_survival_rate < kOldSurvivalRateLowThreshold) {
    // Too many objects died in the old generation, pretenuring of wrong
    // allocation sites may be the cause for that. We have to deopt all
    // dependent code registered in the allocation sites to re-evaluate
    // our pretenuring decisions.
    ResetAllAllocationSitesDependentCode(AllocationType::kOld);
    if (v8_flags.trace_pretenuring) {
      PrintF(
          "Deopt all allocation sites dependent code due to low survival "
          "rate in the old generation %f\n",
          old_generation_survival_rate);
    }
  }
}
References v8::internal::kOld, kOldSurvivalRateLowThreshold, v8::internal::PrintF(), ResetAllAllocationSitesDependentCode(), SizeOfObjects(), and v8::internal::v8_flags.
Referenced by MarkCompact().
ExpandNewSpaceSize()
void v8::internal::Heap::ExpandNewSpaceSize () [private]
Definition at line 4009 of file heap.cc.
                              {
  // Grow the size of new space if there is room to grow, and enough data
  // has survived scavenge since the last expansion.
  const size_t suggested_capacity =
      static_cast<size_t>(v8_flags.semi_space_growth_factor) *
      new_space_->TotalCapacity();
  const size_t chosen_capacity =
      std::min(suggested_capacity, new_space_->MaximumCapacity());
  DCHECK(IsAligned(chosen_capacity, PageMetadata::kPageSize));
  if (chosen_capacity > new_space_->TotalCapacity()) {
    new_space_->Grow(chosen_capacity);
    new_lo_space()->SetCapacity(new_space()->TotalCapacity());
  }
}
References v8::internal::DCHECK(), v8::internal::NewSpace::Grow(), IsAligned(), v8::internal::MutablePageMetadata::kPageSize, v8::internal::NewSpace::MaximumCapacity(), new_lo_space(), new_space(), new_space_, v8::internal::NewLargeObjectSpace::SetCapacity(), v8::internal::NewSpace::TotalCapacity(), and v8::internal::v8_flags.
Referenced by ExpandNewSpaceSizeForTesting(), and ResizeNewSpace().
ExpandNewSpaceSizeForTesting()
void v8::internal::Heap::ExpandNewSpaceSizeForTesting ()
Definition at line 4007 of file heap.cc.
{ ExpandNewSpaceSize(); }
References ExpandNewSpaceSize().
external_memory()
uint64_t v8::internal::Heap::external_memory () const [inline]
Definition at line 67 of file heap-inl.h.
{ return external_memory_.total(); }
References external_memory_, and v8::internal::Heap::ExternalMemoryAccounting::total().
Referenced by CollectGarbageOnMemoryPressure(), v8::ExternalMemoryAccounter::GetTotalAmountOfExternalAllocatedMemoryForTesting(), GlobalSizeOfObjects(), HandleExternalMemoryInterrupt(), PrintShortHeapStatistics(), and v8::internal::GCTracer::RecordGCSizeCounters().
external_memory_hard_limit()
uint64_t v8::internal::Heap::external_memory_hard_limit () [inline]
Definition at line 655 of file heap.h.
                                        {
    return external_memory_.low_since_mark_compact() +
           max_old_generation_size() / 2;
  }
Referenced by HandleExternalMemoryInterrupt().
external_memory_limit_for_interrupt()
uint64_t v8::internal::Heap::external_memory_limit_for_interrupt ()
Definition at line 1506 of file heap.cc.
                                                   {
  return external_memory_.limit_for_interrupt();
}
References external_memory_, and v8::internal::Heap::ExternalMemoryAccounting::limit_for_interrupt().
Referenced by v8::Isolate::AdjustAmountOfExternalAllocatedMemoryImpl().
external_memory_soft_limit()
uint64_t v8::internal::Heap::external_memory_soft_limit ()
Definition at line 1510 of file heap.cc.
                                          {
  return external_memory_.soft_limit();
}
References external_memory_, and v8::internal::Heap::ExternalMemoryAccounting::soft_limit().
FatalProcessOutOfMemory()
void v8::internal::Heap::FatalProcessOutOfMemory (const char * location)
Definition at line 6584 of file heap.cc.
                                                       {
  V8::FatalProcessOutOfMemory(isolate(), location, V8::kHeapOOM);
}
References v8::internal::V8::FatalProcessOutOfMemory(), isolate(), and v8::internal::V8::kHeapOOM.
Referenced by v8::internal::EvacuateNewSpaceVisitor::AllocateInOldSpace(), v8::internal::ReadOnlySpace::AllocateNextPageAt(), CheckHeapLimitReached(), CheckIneffectiveMarkCompact(), CollectGarbage(), CollectGarbageShared(), v8::internal::Scavenger::EvacuateObjectDefault(), v8::internal::JSTypedArray::GetBuffer(), KeepDuringJob(), and v8::internal::EvacuateNewSpaceVisitor::Visit().
FinalizeExternalString()
void v8::internal::Heap::FinalizeExternalString (Tagged< String > string) [inline]
Definition at line 219 of file heap-inl.h.
                                                       {
  DCHECK(IsExternalString(string));
  Tagged<ExternalString> ext_string = Cast<ExternalString>(string);
  PageMetadata* page = PageMetadata::FromHeapObject(string);
  page->DecrementExternalBackingStoreBytes(
      ExternalBackingStoreType::kExternalString,
      ext_string->ExternalPayloadSize());
  ext_string->DisposeResource(isolate());
}
References v8::internal::DCHECK(), v8::internal::MutablePageMetadata::DecrementExternalBackingStoreBytes(), v8::internal::PageMetadata::FromHeapObject(), v8::internal::InstanceTypeChecker::IsExternalString(), isolate(), and v8::internal::kExternalString.
Referenced by v8::internal::anonymous_namespace{string.cc}::MigrateExternalString(), and v8::internal::anonymous_namespace{string.cc}::MigrateExternalStringResource().
FinalizeIncrementalMarkingAtomically()
void v8::internal::Heap::FinalizeIncrementalMarkingAtomically (GarbageCollectionReason gc_reason)
Definition at line 4058 of file heap.cc.
                                       {
  DCHECK(!incremental_marking()->IsStopped());
  CollectAllGarbage(current_gc_flags_, gc_reason, current_gc_callback_flags_);
}
References CollectAllGarbage(), current_gc_callback_flags_, current_gc_flags_, v8::internal::DCHECK(), and incremental_marking().
Referenced by v8::internal::IncrementalMarking::AdvanceAndFinalizeIfComplete(), v8::internal::IncrementalMarking::AdvanceAndFinalizeIfNecessary(), FinalizeIncrementalMarkingAtomicallyIfRunning(), and v8::internal::CppHeap::StartDetachingIsolate().
FinalizeIncrementalMarkingAtomicallyIfRunning()
void v8::internal::Heap::FinalizeIncrementalMarkingAtomicallyIfRunning (GarbageCollectionReason gc_reason)
Definition at line 4064 of file heap.cc.
                                       {
  if (!incremental_marking()->IsStopped()) {
    FinalizeIncrementalMarkingAtomically(gc_reason);
  }
}
References FinalizeIncrementalMarkingAtomically(), and incremental_marking().
Referenced by PreciseCollectAllGarbage().
FinalizePartialMap()
void v8::internal::Heap::FinalizePartialMap (Tagged< Map > map) [private]
Definition at line 318 of file setup-heap-internal.cc.
                                             {
  ReadOnlyRoots roots(this);
  map->set_dependent_code(DependentCode::empty_dependent_code(roots));
  map->set_raw_transitions(Smi::zero());
  map->SetInstanceDescriptors(isolate(), roots.empty_descriptor_array(), 0,
                              SKIP_WRITE_BARRIER);
  map->init_prototype_and_constructor_or_back_pointer(roots);
}
References v8::internal::DependentCode::empty_dependent_code(), isolate(), v8::internal::SKIP_WRITE_BARRIER, and v8::internal::Smi::zero().
Referenced by CreateEarlyReadOnlyMapsAndObjects().
FindAllNativeContexts()
std::vector< Handle< NativeContext > > v8::internal::Heap::FindAllNativeContexts () [private]
Definition at line 7203 of file heap.cc.
                                                             {
  std::vector<Handle<NativeContext>> result;
  Tagged<Object> context = native_contexts_list();
  while (!IsUndefined(context, isolate())) {
    Tagged<NativeContext> native_context = Cast<NativeContext>(context);
    result.push_back(handle(native_context, isolate()));
    context = native_context->next_context_link();
  }
  return result;
}
References v8::internal::handle(), isolate(), v8::internal::native_context, native_contexts_list(), and v8::base::internal::result.
Referenced by MeasureMemory(), and v8::internal::MarkCompactCollector::StartMarking().
FindAllRetainedMaps()
std::vector< Tagged< WeakArrayList > > v8::internal::Heap::FindAllRetainedMaps () [private]
Definition at line 7214 of file heap.cc.
                                                           {
  std::vector<Tagged<WeakArrayList>> result;
  Tagged<Object> context = native_contexts_list();
  while (!IsUndefined(context, isolate())) {
    Tagged<NativeContext> native_context = Cast<NativeContext>(context);
    result.push_back(Cast<WeakArrayList>(native_context->retained_maps()));
    context = native_context->next_context_link();
  }
  return result;
}
References isolate(), v8::internal::native_context, native_contexts_list(), and v8::base::internal::result.
FindCodeForInnerPointer()
Tagged< Code > v8::internal::Heap::FindCodeForInnerPointer (Address inner_pointer)
Definition at line 7352 of file heap.cc.
                                                                {
  return GcSafeFindCodeForInnerPointer(inner_pointer)->UnsafeCastToCode();
}
References GcSafeFindCodeForInnerPointer().
Referenced by v8::internal::Deoptimizer::Deoptimizer(), and v8::internal::anonymous_namespace{frames.cc}::IsInterpreterFramePc().
FinishSweepingIfOutOfWork()
void v8::internal::Heap::FinishSweepingIfOutOfWork ()
Definition at line 7456 of file heap.cc.
                                     {
  if (sweeper()->major_sweeping_in_progress() &&
      sweeper()->UsingMajorSweeperTasks() &&
      !sweeper()->AreMajorSweeperTasksRunning()) {
    // At this point we know that all concurrent sweeping tasks have run
    // out of work and quit: all pages are swept. The main thread still needs
    // to complete sweeping though.
    DCHECK_IMPLIES(!delay_sweeper_tasks_for_testing_,
                   !sweeper()->HasUnsweptPagesForMajorSweeping());
    EnsureSweepingCompleted(SweepingForcedFinalizationMode::kV8Only);
  }
  if (cpp_heap()) {
    // Ensure that sweeping is also completed for the C++ managed heap, if one
    // exists and it's out of work.
    CppHeap::From(cpp_heap())->FinishSweepingIfOutOfWork();
  }
}
References cpp_heap(), DCHECK_IMPLIES, delay_sweeper_tasks_for_testing_, EnsureSweepingCompleted(), v8::internal::CppHeap::FinishSweepingIfOutOfWork(), v8::internal::CppHeap::From(), kV8Only, major_sweeping_in_progress(), and sweeper().
Referenced by CompleteSweepingYoung().
force_oom()
bool v8::internal::Heap::force_oom () const [inline]
Definition at line 575 of file heap.h.
{ return force_oom_; }
Referenced by v8::internal::PagedSpaceAllocatorPolicy::RefillLab().
ForeachAllocationSite()
void v8::internal::Heap::ForeachAllocationSite (Tagged< Object > list, const std::function< void(Tagged< AllocationSite >)> & visitor)
Definition at line 3057 of file heap.cc.
                                                              {
  DisallowGarbageCollection no_gc;
  Tagged<Object> current = list;
  while (IsAllocationSite(current)) {
    Tagged<AllocationSiteWithWeakNext> site =
        Cast<AllocationSiteWithWeakNext>(current);
    visitor(site);
    Tagged<Object> current_nested = site->nested_site();
    while (IsAllocationSite(current_nested)) {
      Tagged<AllocationSite> nested_site = Cast<AllocationSite>(current_nested);
      visitor(nested_site);
      current_nested = nested_site->nested_site();
    }
    current = site->weak_next();
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by DeoptMarkedAllocationSites(), v8::internal::PretenuringHandler::ProcessPretenuringFeedback(), and ResetAllAllocationSitesDependentCode().
FreeLinearAllocationAreas()
void v8::internal::Heap::FreeLinearAllocationAreas ()
Definition at line 3681 of file heap.cc.
                                     {
  FreeMainThreadLinearAllocationAreas();
  safepoint()->IterateLocalHeaps(
      [](LocalHeap* local_heap) { local_heap->FreeLinearAllocationAreas(); });
  if (isolate()->is_shared_space_isolate()) {
    isolate()->global_safepoint()->IterateClientIsolates(
        [](Isolate* client) { client->heap()->FreeLinearAllocationAreas(); });
  }
}
References v8::internal::LocalHeap::FreeLinearAllocationAreas(), FreeMainThreadLinearAllocationAreas(), v8::internal::Isolate::global_safepoint(), v8::internal::Isolate::heap(), isolate(), v8::internal::GlobalSafepoint::IterateClientIsolates(), v8::internal::IsolateSafepoint::IterateLocalHeaps(), and safepoint().
Referenced by PerformGarbageCollection(), and v8::internal::IncrementalMarking::StartMarkingMajor().
FreeMainThreadLinearAllocationAreas()
void v8::internal::Heap::FreeMainThreadLinearAllocationAreas ()
Definition at line 3693 of file heap.cc.
                                               {
  allocator()->FreeLinearAllocationAreas();
}
References allocator(), and v8::internal::HeapAllocator::FreeLinearAllocationAreas().
Referenced by AddAllocationObserversToAllSpaces(), DisableInlineAllocation(), FreeLinearAllocationAreas(), NotifyDeserializationComplete(), and StartTearDown().
FreeSharedLinearAllocationAreasAndResetFreeLists()
void v8::internal::Heap::FreeSharedLinearAllocationAreasAndResetFreeLists () [private]
Definition at line 3716 of file heap.cc.
                                                            {
  DCHECK(v8_flags.black_allocated_pages);
  allocator()->FreeSharedLinearAllocationAreasAndResetFreeLists();
  main_thread_local_heap()->FreeSharedLinearAllocationAreasAndResetFreeLists();
  safepoint()->IterateLocalHeaps([](LocalHeap* local_heap) {
    local_heap->FreeSharedLinearAllocationAreasAndResetFreeLists();
  });
}
References allocator(), v8::internal::DCHECK(), v8::internal::HeapAllocator::FreeSharedLinearAllocationAreasAndResetFreeLists(), v8::internal::LocalHeap::FreeSharedLinearAllocationAreasAndResetFreeLists(), v8::internal::IsolateSafepoint::IterateLocalHeaps(), main_thread_local_heap(), safepoint(), and v8::internal::v8_flags.
FRIEND_TEST() [1/2]
v8::internal::Heap::FRIEND_TEST (SpacesTest , AllocationObserver) [private]
FRIEND_TEST() [2/2]
v8::internal::Heap::FRIEND_TEST (SpacesTest , InlineAllocationObserverCadence) [private]
FromWritableHeapObject()
Heap * v8::internal::Heap::FromWritableHeapObject (Tagged< HeapObject > obj) [inline], [static]
Definition at line 281 of file heap-inl.h.
                                                         {
  MemoryChunkMetadata* chunk = MemoryChunkMetadata::FromHeapObject(obj);
  // RO_SPACE can be shared between heaps, so we can't use RO_SPACE objects to
  // find a heap. The exception is when the ReadOnlySpace is writeable, during
  // bootstrapping, so explicitly allow this case.
  SLOW_DCHECK(chunk->IsWritable());
  Heap* heap = chunk->heap();
  SLOW_DCHECK(heap != nullptr);
  return heap;
}
References v8::internal::MemoryChunkMetadata::FromHeapObject(), v8::internal::MemoryChunkMetadata::heap(), heap(), v8::internal::MemoryChunkMetadata::IsWritable(), and SLOW_DCHECK.
Referenced by v8::internal::WriteBarrier::PageFlagsAreConsistent().
GarbageCollectionEpilogue()
void v8::internal::Heap::GarbageCollectionEpilogue (GarbageCollector collector) [private]
Definition at line 1163 of file heap.cc.
                                                               {
  TRACE_GC(tracer(), GCTracer::Scope::HEAP_EPILOGUE);
  AllowGarbageCollection for_the_rest_of_the_epilogue;
  UpdateMaximumCommitted();
  isolate_->counters()->alive_after_last_gc()->Set(
      static_cast<int>(SizeOfObjects()));
  if (CommittedMemory() > 0) {
    isolate_->counters()->external_fragmentation_total()->AddSample(
        static_cast<int>(100 - (SizeOfObjects() * 100.0) / CommittedMemory()));
    isolate_->counters()->heap_sample_total_committed()->AddSample(
        static_cast<int>(CommittedMemory() / KB));
    isolate_->counters()->heap_sample_total_used()->AddSample(
        static_cast<int>(SizeOfObjects() / KB));
    isolate_->counters()->heap_sample_code_space_committed()->AddSample(
        static_cast<int>(code_space()->CommittedMemory() / KB));
    isolate_->counters()->heap_sample_maximum_committed()->AddSample(
        static_cast<int>(MaximumCommittedMemory() / KB));
  }
#ifdef DEBUG
  ReportStatisticsAfterGC();
  if (v8_flags.code_stats) ReportCodeStatistics("After GC");
#endif // DEBUG
  last_gc_time_ = MonotonicallyIncreasingTimeInMs();
}
References code_space(), CommittedMemory(), v8::internal::Isolate::counters(), isolate_, v8::internal::KB, last_gc_time_, MaximumCommittedMemory(), MonotonicallyIncreasingTimeInMs(), ReportStatisticsAfterGC(), SizeOfObjects(), TRACE_GC, tracer(), UpdateMaximumCommitted(), and v8::internal::v8_flags.
Referenced by CollectGarbage().
GarbageCollectionEpilogueInSafepoint()
void v8::internal::Heap::GarbageCollectionEpilogueInSafepoint (GarbageCollector collector) [private]
Definition at line 1074 of file heap.cc.
                                                                          {
  TRACE_GC(tracer(), GCTracer::Scope::HEAP_EPILOGUE_SAFEPOINT);
  {
    // Allows handle derefs for all threads/isolates from this thread.
    AllowHandleUsageOnAllThreads allow_all_handle_derefs;
    safepoint()->IterateLocalHeaps([](LocalHeap* local_heap) {
      local_heap->InvokeGCEpilogueCallbacksInSafepoint(
          GCCallbacksInSafepoint::GCType::kLocal);
    });
    if (collector == GarbageCollector::MARK_COMPACTOR &&
        isolate()->is_shared_space_isolate()) {
      isolate()->global_safepoint()->IterateClientIsolates([](Isolate* client) {
        client->heap()->safepoint()->IterateLocalHeaps(
            [](LocalHeap* local_heap) {
              local_heap->InvokeGCEpilogueCallbacksInSafepoint(
                  GCCallbacksInSafepoint::GCType::kShared);
            });
      });
    }
  }
#define UPDATE_COUNTERS_FOR_SPACE(space) \
  isolate_->counters()->space##_bytes_available()->Set(\
      static_cast<int>(space()->Available())); \
  isolate_->counters()->space##_bytes_committed()->Set(\
      static_cast<int>(space()->CommittedMemory())); \
  isolate_->counters()->space##_bytes_used()->Set(\
      static_cast<int>(space()->SizeOfObjects()));
#define UPDATE_FRAGMENTATION_FOR_SPACE(space) \
  if (space()->CommittedMemory() > 0) { \
    isolate_->counters()->external_fragmentation_##space()->AddSample(\
        static_cast<int>(100 - (space()->SizeOfObjects() * 100.0) / \
                                   space()->CommittedMemory())); \
  }
#define UPDATE_COUNTERS_AND_FRAGMENTATION_FOR_SPACE(space) \
  UPDATE_COUNTERS_FOR_SPACE(space) \
  UPDATE_FRAGMENTATION_FOR_SPACE(space)
  if (new_space()) {
    UPDATE_COUNTERS_FOR_SPACE(new_space)
  }
  UPDATE_COUNTERS_AND_FRAGMENTATION_FOR_SPACE(old_space)
  UPDATE_COUNTERS_AND_FRAGMENTATION_FOR_SPACE(code_space)
  UPDATE_COUNTERS_AND_FRAGMENTATION_FOR_SPACE(lo_space)
#undef UPDATE_COUNTERS_FOR_SPACE
#undef UPDATE_FRAGMENTATION_FOR_SPACE
#undef UPDATE_COUNTERS_AND_FRAGMENTATION_FOR_SPACE
#ifdef DEBUG
  if (v8_flags.print_global_handles) isolate_->global_handles()->Print();
  if (v8_flags.print_handles) PrintHandles();
  if (v8_flags.check_handle_count) CheckHandleCount();
#endif
  // Young generation GCs only run with memory reducing flags during
  // interleaved GCs.
  DCHECK_IMPLIES(IsYoungGenerationCollector(collector), !ShouldReduceMemory());
  if (collector == GarbageCollector::MARK_COMPACTOR) {
    memory_pressure_level_.store(MemoryPressureLevel::kNone,
                                 std::memory_order_relaxed);
    if (v8_flags.stress_marking > 0) {
      stress_marking_percentage_ = NextStressMarkingLimit();
    }
    // Discard memory if the GC was requested to reduce memory.
    if (ShouldReduceMemory()) {
      memory_allocator_->ReleasePooledChunksImmediately();
#if V8_ENABLE_WEBASSEMBLY
      isolate_->stack_pool().ReleaseFinishedStacks();
#endif
    }
  }
  // Remove CollectionRequested flag from main thread state, as the collection
  // was just performed.
  safepoint()->AssertActive();
  LocalHeap::ThreadState old_state =
      main_thread_local_heap()->state_.ClearCollectionRequested();
  CHECK(old_state.IsRunning());
  // Resume all threads waiting for the GC.
  collection_barrier_->ResumeThreadsAwaitingCollection();
}
References v8::internal::IsolateSafepoint::AssertActive(), CHECK, CheckHandleCount(), v8::internal::LocalHeap::AtomicThreadState::ClearCollectionRequested(), code_space(), collection_barrier_, DCHECK_IMPLIES, v8::internal::Isolate::global_handles(), v8::internal::Isolate::global_safepoint(), v8::internal::Isolate::heap(), v8::internal::LocalHeap::InvokeGCEpilogueCallbacksInSafepoint(), isolate(), isolate_, v8::internal::LocalHeap::ThreadState::IsRunning(), IsYoungGenerationCollector(), v8::internal::GlobalSafepoint::IterateClientIsolates(), v8::internal::IsolateSafepoint::IterateLocalHeaps(), v8::kNone, v8::internal::anonymous_namespace{elements.cc}::kShared, lo_space(), main_thread_local_heap(), v8::internal::MARK_COMPACTOR, memory_allocator_, memory_pressure_level_, new_space(), NextStressMarkingLimit(), old_space(), safepoint(), ShouldReduceMemory(), v8::internal::LocalHeap::state_, stress_marking_percentage_, TRACE_GC, tracer(), UPDATE_COUNTERS_AND_FRAGMENTATION_FOR_SPACE, UPDATE_COUNTERS_FOR_SPACE, and v8::internal::v8_flags.
Referenced by PerformGarbageCollection().
GarbageCollectionPrologue()
void v8::internal::Heap::GarbageCollectionPrologue (GarbageCollectionReason gc_reason, const v8::GCCallbackFlags gc_callback_flags) [private]
Definition at line 950 of file heap.cc.
                                               {
  TRACE_GC(tracer(), GCTracer::Scope::HEAP_PROLOGUE);
  is_current_gc_forced_ = gc_callback_flags & v8::kGCCallbackFlagForced ||
                          current_gc_flags_ & GCFlag::kForced ||
                          force_gc_on_next_allocation_;
  is_current_gc_for_heap_profiler_ =
      gc_reason == GarbageCollectionReason::kHeapProfiler;
  if (force_gc_on_next_allocation_) force_gc_on_next_allocation_ = false;
#ifdef V8_ENABLE_ALLOCATION_TIMEOUT
  heap_allocator_->UpdateAllocationTimeout();
#endif // V8_ENABLE_ALLOCATION_TIMEOUT
  if (minor_gc_job()) {
    DCHECK(use_new_space());
    minor_gc_job()->CancelTaskIfScheduled();
  }
  // Reset GC statistics.
  promoted_objects_size_ = 0;
  previous_new_space_surviving_object_size_ = new_space_surviving_object_size_;
  new_space_surviving_object_size_ = 0;
  nodes_died_in_new_space_ = 0;
  nodes_copied_in_new_space_ = 0;
  nodes_promoted_ = 0;
  UpdateMaximumCommitted();
#ifdef DEBUG
  DCHECK(!AllowGarbageCollection::IsAllowed());
  DCHECK_EQ(gc_state(), NOT_IN_GC);
  if (v8_flags.gc_verbose) Print();
#endif // DEBUG
}
References v8::internal::MinorGCJob::CancelTaskIfScheduled(), current_gc_flags_, v8::internal::DCHECK(), DCHECK_EQ, force_gc_on_next_allocation_, gc_state(), heap_allocator_, is_current_gc_for_heap_profiler_, is_current_gc_forced_, v8::internal::kForced, v8::kGCCallbackFlagForced, v8::internal::kHeapProfiler, minor_gc_job(), new_space_surviving_object_size_, nodes_copied_in_new_space_, nodes_died_in_new_space_, nodes_promoted_, NOT_IN_GC, previous_new_space_surviving_object_size_, v8::internal::Print(), promoted_objects_size_, TRACE_GC, tracer(), UpdateMaximumCommitted(), use_new_space(), and v8::internal::v8_flags.
Referenced by CollectGarbage().
GarbageCollectionPrologueInSafepoint()
void v8::internal::Heap::GarbageCollectionPrologueInSafepoint (GarbageCollector collector) [private]
Definition at line 989 of file heap.cc.
                                                                          {
  TRACE_GC(tracer(), GCTracer::Scope::HEAP_PROLOGUE_SAFEPOINT);
  gc_count_++;
  new_space_allocation_counter_ = NewSpaceAllocationCounter();
  if (v8_flags.large_page_pool_timeout == 0 &&
      collector == GarbageCollector::MARK_COMPACTOR) {
    memory_allocator()->pool()->ReleaseLargeImmediately();
  }
}
References gc_count_, v8::internal::MARK_COMPACTOR, memory_allocator(), new_space_allocation_counter_, NewSpaceAllocationCounter(), v8::internal::MemoryAllocator::pool(), v8::internal::PagePool::ReleaseLargeImmediately(), TRACE_GC, tracer(), and v8::internal::v8_flags.
Referenced by PerformGarbageCollection().
gc_count()
int v8::internal::Heap::gc_count () const [inline]
Definition at line 1410 of file heap.h.
{ return gc_count_; }
Referenced by v8::internal::ObjectStats::Dump(), DumpJSONHeapStatistics(), v8::internal::IdentityMapBase::InsertEntry(), v8::internal::IdentityMapBase::InsertKey(), v8::internal::IdentityMapBase::Lookup(), v8::internal::IdentityMapBase::LookupOrInsert(), v8::internal::ObjectStats::PrintJSON(), v8::internal::IdentityMapBase::Rehash(), and v8::internal::IdentityMapBase::Resize().
gc_state()
HeapState v8::internal::Heap::gc_state () const [inline]
Definition at line 564 of file heap.h.
                                    {
    return gc_state_.load(std::memory_order_relaxed);
  }
Referenced by v8::internal::IncrementalMarking::AdvanceOnAllocation(), v8::internal::IncrementalMarking::CanBeStarted(), v8::internal::Isolate::CountUsage(), v8::internal::IdentityMapBase::DeleteIndex(), v8::internal::StringTable::DropOldData(), v8::internal::IdentityMapBase::FindEntry(), v8::internal::IdentityMapBase::FindOrInsertEntry(), GarbageCollectionPrologue(), v8::internal::IdentityMapBase::InsertEntry(), v8::internal::IdentityMapBase::InsertKey(), IsNewSpaceAllowedToGrowAboveTargetCapacity(), v8::internal::IdentityMapBase::Lookup(), v8::internal::IdentityMapBase::LookupOrInsert(), v8::internal::String::MakeExternalDuringGC(), MinorMarkSweep(), v8::internal::StringTable::NotifyElementsRemoved(), v8::internal::GlobalHandles::PostGarbageCollectionProcessing(), v8::internal::IdentityMapBase::Rehash(), v8::internal::GlobalSafepoint::RemoveClient(), v8::internal::StringForwardingTable::Reset(), v8::internal::IdentityMapBase::Resize(), RightTrimArray(), ShouldExpandOldGenerationOnSlowAllocation(), ShouldExpandYoungGenerationOnSlowAllocation(), v8::internal::SamplingHeapProfiler::Observer::Step(), TearDown(), and TearDownWithSharedHeap().
GCFlagsForIncrementalMarking()
GCFlags v8::internal::Heap::GCFlagsForIncrementalMarking () [inline]
Definition at line 1085 of file heap.h.
                                         {
    return ShouldOptimizeForMemoryUsage() ? GCFlag::kReduceMemoryFootprint
                                          : GCFlag::kNoFlags;
  }
Referenced by CollectGarbage(), HandleExternalMemoryInterrupt(), and StartIncrementalMarkingOnInterrupt().
GcSafeFindCodeForInnerPointer()
Tagged< GcSafeCode > v8::internal::Heap::GcSafeFindCodeForInnerPointer (Address inner_pointer)
Definition at line 7356 of file heap.cc.
                                                                            {
  std::optional<Tagged<GcSafeCode>> maybe_code =
      GcSafeTryFindCodeForInnerPointer(inner_pointer);
  // Callers expect that the code object is found.
  CHECK(maybe_code.has_value());
  return UncheckedCast<GcSafeCode>(maybe_code.value());
}
References CHECK, and GcSafeTryFindCodeForInnerPointer().
Referenced by FindCodeForInnerPointer().
GcSafeGetCodeFromInstructionStream()
Tagged< GcSafeCode > v8::internal::Heap::GcSafeGetCodeFromInstructionStream (Tagged< HeapObject > instruction_stream, Address inner_pointer) [private]
Definition at line 7298 of file heap.cc.
                                                                  {
  Tagged<InstructionStream> istream =
      UncheckedCast<InstructionStream>(instruction_stream);
  DCHECK(!istream.is_null());
  DCHECK(GcSafeInstructionStreamContains(istream, inner_pointer));
  return UncheckedCast<GcSafeCode>(istream->raw_code(kAcquireLoad));
}
References v8::internal::DCHECK(), GcSafeInstructionStreamContains(), v8::internal::Tagged< HeapObject >::is_null(), and v8::kAcquireLoad.
Referenced by GcSafeTryFindCodeForInnerPointer().
GcSafeInstructionStreamContains()
bool v8::internal::Heap::GcSafeInstructionStreamContains (Tagged< InstructionStream > instruction_stream, Address addr)
Definition at line 7307 of file heap.cc.
                                                                {
  Tagged<Map> map = GcSafeMapOfHeapObject(instruction_stream);
  DCHECK_EQ(map, ReadOnlyRoots(this).instruction_stream_map());
  Builtin builtin_lookup_result =
      OffHeapInstructionStream::TryLookupCode(isolate(), addr);
  if (Builtins::IsBuiltinId(builtin_lookup_result)) {
    // Builtins don't have InstructionStream objects.
    DCHECK(!Builtins::IsBuiltinId(
        instruction_stream->code(kAcquireLoad)->builtin_id()));
    return false;
  }
  Address start = instruction_stream.address();
  Address end = start + instruction_stream->SizeFromMap(map);
  return start <= addr && addr < end;
}
References v8::internal::Tagged< HeapObject >::address(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::end(), GcSafeMapOfHeapObject(), v8::internal::Builtins::IsBuiltinId(), isolate(), v8::kAcquireLoad, ReadOnlyRoots, and v8::internal::OffHeapInstructionStream::TryLookupCode().
Referenced by GcSafeGetCodeFromInstructionStream().
GcSafeMapOfHeapObject()
Tagged< Map > v8::internal::Heap::GcSafeMapOfHeapObject (Tagged< HeapObject > object) [private]
Definition at line 7289 of file heap.cc.
                                                                 {
  PtrComprCageBase cage_base(isolate());
  MapWord map_word = object->map_word(cage_base, kRelaxedLoad);
  if (map_word.IsForwardingAddress()) {
    return map_word.ToForwardingAddress(object)->map(cage_base);
  }
  return map_word.ToMap();
}
References v8::internal::MapWord::IsForwardingAddress(), isolate(), v8::kRelaxedLoad, v8::internal::MapWord::ToForwardingAddress(), and v8::internal::MapWord::ToMap().
Referenced by GcSafeInstructionStreamContains().
GcSafeTryFindCodeForInnerPointer()
std::optional< Tagged< GcSafeCode > > v8::internal::Heap::GcSafeTryFindCodeForInnerPointer (Address inner_pointer)
Definition at line 7337 of file heap.cc.
                           {
  Builtin maybe_builtin =
      OffHeapInstructionStream::TryLookupCode(isolate(), inner_pointer);
  if (Builtins::IsBuiltinId(maybe_builtin)) {
    return Cast<GcSafeCode>(isolate()->builtins()->code(maybe_builtin));
  }
  std::optional<Tagged<InstructionStream>> maybe_istream =
      GcSafeTryFindInstructionStreamForInnerPointer(inner_pointer);
  if (!maybe_istream) return {};
  return GcSafeGetCodeFromInstructionStream(*maybe_istream, inner_pointer);
}
References code, GcSafeGetCodeFromInstructionStream(), GcSafeTryFindInstructionStreamForInnerPointer(), v8::internal::Builtins::IsBuiltinId(), isolate(), and v8::internal::OffHeapInstructionStream::TryLookupCode().
Referenced by GcSafeFindCodeForInnerPointer(), v8::internal::ETWJITInterface::EtwIsolateOperations::HeapGcSafeTryFindCodeForInnerPointer(), TryFindCodeForInnerPointerForPrinting(), v8::internal::TurbofanStubWithContextFrame::unchecked_code(), and v8::internal::StubFrame::unchecked_code().
GcSafeTryFindInstructionStreamForInnerPointer()
std::optional< Tagged< InstructionStream > > v8::internal::Heap::GcSafeTryFindInstructionStreamForInnerPointer (Address inner_pointer)
Definition at line 7327 of file heap.cc.
                                                                         {
  std::optional<Address> start =
      ThreadIsolation::StartOfJitAllocationAt(inner_pointer);
  if (start.has_value()) {
    return UncheckedCast<InstructionStream>(HeapObject::FromAddress(*start));
  }
  return {};
}
References v8::internal::HeapObject::FromAddress(), and v8::internal::ThreadIsolation::StartOfJitAllocationAt().
Referenced by GcSafeTryFindCodeForInnerPointer().
GenerationSizesFromHeapSize()
void v8::internal::Heap::GenerationSizesFromHeapSize (size_t heap_size, size_t * young_generation_size, size_t * old_generation_size) [static]
Definition at line 244 of file heap.cc.
                                                                    {
  // Initialize values for the case when the given heap size is too small.
  *young_generation_size = 0;
  *old_generation_size = 0;
  // Binary search for the largest old generation size that fits to the given
  // heap limit considering the correspondingly sized young generation.
  size_t lower = 0, upper = heap_size;
  while (lower + 1 < upper) {
    size_t old_generation = lower + (upper - lower) / 2;
    size_t young_generation =
        YoungGenerationSizeFromOldGenerationSize(old_generation);
    if (old_generation + young_generation <= heap_size) {
      // This size configuration fits into the given heap limit.
      *young_generation_size = young_generation;
      *old_generation_size = old_generation;
      lower = old_generation;
    } else {
      upper = old_generation;
    }
  }
}
References YoungGenerationSizeFromOldGenerationSize().
Referenced by v8::ResourceConstraints::ConfigureDefaults(), v8::ResourceConstraints::ConfigureDefaultsFromHeapSize(), and ConfigureHeap().
GetCodeRangeReservedAreaSize()
size_t v8::internal::Heap::GetCodeRangeReservedAreaSize () [static]
Definition at line 3153 of file heap.cc.
                                          {
  return CodeRange::GetWritableReservedAreaSize();
}
References v8::internal::CodeRange::GetWritableReservedAreaSize().
Referenced by v8::internal::wasm::WasmCodeAllocator::InitializeCodeRange(), and v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::OverheadPerCodeSpace().
GetEmbedderRootsHandler()
EmbedderRootsHandler * v8::internal::Heap::GetEmbedderRootsHandler () const
Definition at line 6230 of file heap.cc.
                                                          {
  return embedder_roots_handler_;
}
References embedder_roots_handler_.
Referenced by v8::internal::TracedHandles::SupportsClearingWeakNonLiveWrappers().
GetFillToAlign()
int v8::internal::Heap::GetFillToAlign (Address address, AllocationAlignment alignment) [static]
Definition at line 3143 of file heap.cc.
                                                                       {
  if (V8_COMPRESS_POINTERS_8GB_BOOL) return 0;
  if (alignment == kDoubleAligned && (address & kDoubleAlignmentMask) != 0)
    return kTaggedSize;
  if (alignment == kDoubleUnaligned && (address & kDoubleAlignmentMask) == 0) {
    return kDoubleSize - kTaggedSize; // No fill if double is always aligned.
  }
  return 0;
}
References v8::internal::kDoubleAligned, v8::internal::kDoubleAlignmentMask, v8::internal::kDoubleSize, v8::internal::kDoubleUnaligned, v8::internal::kTaggedSize, and V8_COMPRESS_POINTERS_8GB_BOOL.
Referenced by v8::internal::SemiSpaceNewSpace::AddParkedAllocationBuffer(), v8::internal::MainAllocator::AlignTopForTesting(), AlignWithFillerBackground(), v8::internal::SemiSpaceNewSpace::Allocate(), v8::internal::MainAllocator::AllocateFastAligned(), v8::internal::HeapObject::CheckRequiredAlignment(), v8::internal::SemiSpaceNewSpaceAllocatorPolicy::EnsureAllocation(), and v8::internal::ReadOnlySpace::TryAllocateLinearlyAligned().
GetForegroundTaskRunner()
std::shared_ptr< v8::TaskRunner > v8::internal::Heap::GetForegroundTaskRunner (TaskPriority priority = TaskPriority::kUserBlocking) const
Definition at line 6101 of file heap.cc.
                                 {
  return V8::GetCurrentPlatform()->GetForegroundTaskRunner(
      reinterpret_cast<v8::Isolate*>(isolate()), priority);
}
References v8::internal::V8::GetCurrentPlatform(), v8::Platform::GetForegroundTaskRunner(), and isolate().
Referenced by v8::internal::IsolateSafepoint::InitiateGlobalSafepointScopeRaw(), v8::internal::MemoryBalancer::PostHeartbeatTask(), and v8::internal::MinorGCJob::TryScheduleTask().
GetFromRingBuffer()
void v8::internal::Heap::GetFromRingBuffer (char * buffer) [private]
Definition at line 5311 of file heap.cc.
                                         {
  size_t copied = 0;
  if (ring_buffer_full_) {
    copied = kTraceRingBufferSize - ring_buffer_end_;
    memcpy(buffer, trace_ring_buffer_ + ring_buffer_end_, copied);
  }
  memcpy(buffer + copied, trace_ring_buffer_, ring_buffer_end_);
}
References kTraceRingBufferSize, ring_buffer_end_, ring_buffer_full_, and trace_ring_buffer_.
Referenced by RecordStats().
GetMaximumFillToAlign()
int v8::internal::Heap::GetMaximumFillToAlign (AllocationAlignment alignment) [static]
Definition at line 3129 of file heap.cc.
                                                             {
  if (V8_COMPRESS_POINTERS_8GB_BOOL) return 0;
  switch (alignment) {
    case kTaggedAligned:
      return 0;
    case kDoubleAligned:
    case kDoubleUnaligned:
      return kDoubleSize - kTaggedSize;
    default:
      UNREACHABLE();
  }
}
References v8::internal::kDoubleAligned, v8::internal::kDoubleSize, v8::internal::kDoubleUnaligned, v8::internal::kTaggedAligned, v8::internal::kTaggedSize, v8::internal::UNREACHABLE(), and V8_COMPRESS_POINTERS_8GB_BOOL.
Referenced by v8::internal::ReadOnlySpace::AllocateRawAligned(), v8::internal::MainAllocator::AllocateRawSlowAligned(), and v8::internal::PagedSpaceAllocatorPolicy::EnsureAllocation().
GetNextTemplateSerialNumber()
uint32_t v8::internal::Heap::GetNextTemplateSerialNumber () [inline]
Definition at line 386 of file heap-inl.h.
                                           {
  uint32_t next_serial_number =
      static_cast<uint32_t>(next_template_serial_number().value());
  if (next_serial_number < Smi::kMaxValue) {
    ++next_serial_number;
  } else {
    // In case of overflow, restart from a range where it's ok for serial
    // numbers to be non-unique.
    next_serial_number = TemplateInfo::kFirstNonUniqueSerialNumber;
  }
  DCHECK_NE(next_serial_number, TemplateInfo::kUninitializedSerialNumber);
  set_next_template_serial_number(Smi::FromInt(next_serial_number));
  return next_serial_number;
}
References DCHECK_NE, v8::internal::Smi::FromInt(), v8::internal::TemplateInfo::kFirstNonUniqueSerialNumber, v8::internal::Smi::kMaxValue, and v8::internal::TemplateInfo::kUninitializedSerialNumber.
Referenced by v8::internal::TemplateInfo::EnsureHasSerialNumber().
GetObjectTypeName()
bool v8::internal::Heap::GetObjectTypeName (size_t index, const char ** object_type, const char ** object_sub_type)
Definition at line 7167 of file heap.cc.
                                                           {
  if (index >= ObjectStats::OBJECT_STATS_COUNT) return false;
  switch (static_cast<int>(index)) {
#define COMPARE_AND_RETURN_NAME(name) \
  case name: \
    *object_type = #name; \
    *object_sub_type = ""; \
    return true;
    INSTANCE_TYPE_LIST(COMPARE_AND_RETURN_NAME)
#undef COMPARE_AND_RETURN_NAME
#define COMPARE_AND_RETURN_NAME(name) \
  case ObjectStats::FIRST_VIRTUAL_TYPE + \
      static_cast<int>(ObjectStats::VirtualInstanceType::name): \
    *object_type = #name; \
    *object_sub_type = ""; \
    return true;
    VIRTUAL_INSTANCE_TYPE_LIST(COMPARE_AND_RETURN_NAME)
#undef COMPARE_AND_RETURN_NAME
  }
  return false;
}
References COMPARE_AND_RETURN_NAME, v8::internal::index, INSTANCE_TYPE_LIST, v8::internal::ObjectStats::OBJECT_STATS_COUNT, and VIRTUAL_INSTANCE_TYPE_LIST.
GetRandomMmapAddr()
void* v8::internal::Heap::GetRandomMmapAddr () [inline]
Definition at line 1631 of file heap.h.
                            {
    void* result = v8::internal::GetRandomMmapAddr();
#if V8_TARGET_ARCH_X64
#if V8_OS_DARWIN
    // The Darwin kernel [as of macOS 10.12.5] does not clean up page
    // directory entries [PDE] created from mmap or mach_vm_allocate, even
    // after the region is destroyed. Using a virtual address space that is
    // too large causes a leak of about 1 wired [can never be paged out] page
    // per call to mmap(). The page is only reclaimed when the process is
    // killed. Confine the hint to a 32-bit section of the virtual address
    // space. See crbug.com/700928.
    uintptr_t offset = reinterpret_cast<uintptr_t>(result) & kMmapRegionMask;
    result = reinterpret_cast<void*>(mmap_region_base_ + offset);
#endif // V8_OS_DARWIN
#endif // V8_TARGET_ARCH_X64
    return result;
  }
References v8::internal::GetRandomMmapAddr(), and v8::base::internal::result.
Referenced by v8::internal::MemoryAllocator::AllocateUninitializedChunkAt(), and v8::internal::OffHeapInstructionStream::CreateOffHeapOffHeapInstructionStream().
global_allocation_limit()
size_t v8::internal::Heap::global_allocation_limit () const [inline], [private]
Definition at line 1987 of file heap.h.
                                         {
    return global_allocation_limit_.load(std::memory_order_relaxed);
  }
Referenced by AllocationLimitOvershotByLargeMargin(), EnsureMinimumRemainingAllocationLimit(), GlobalMemoryAvailable(), PercentToGlobalMemoryLimit(), v8::internal::GCTracer::PrintNVP(), RecomputeLimits(), RecomputeLimitsAfterLoadingIfNeeded(), ShrinkOldGenerationAllocationLimitIfNotConfigured(), and v8::internal::IncrementalMarking::Start().
GlobalConsumedBytes()
size_t v8::internal::Heap::GlobalConsumedBytes () const
Definition at line 5431 of file heap.cc.
                                       {
  return GlobalSizeOfObjects() + GlobalWastedBytes();
}
References GlobalSizeOfObjects(), and GlobalWastedBytes().
Referenced by AllocationLimitOvershotByLargeMargin(), EnsureMinimumRemainingAllocationLimit(), GlobalMemoryAvailable(), PercentToGlobalMemoryLimit(), v8::internal::GCTracer::RecordGCSizeCounters(), and ShrinkOldGenerationAllocationLimitIfNotConfigured().
GlobalConsumedBytesAtLastGC()
size_t v8::internal::Heap::GlobalConsumedBytesAtLastGC () const
Definition at line 5439 of file heap.cc.
                                               {
  return OldGenerationConsumedBytesAtLastGC() + embedder_size_at_last_gc_ +
         (v8_flags.external_memory_accounted_in_global_limit
              ? external_memory_.low_since_mark_compact()
              : 0);
}
References embedder_size_at_last_gc_, external_memory_, v8::internal::Heap::ExternalMemoryAccounting::low_since_mark_compact(), OldGenerationConsumedBytesAtLastGC(), and v8::internal::v8_flags.
Referenced by PercentToGlobalMemoryLimit().
GlobalMemoryAvailable()
size_t v8::internal::Heap::GlobalMemoryAvailable () [private]
Definition at line 5594 of file heap.cc.
                                   {
  size_t global_size = GlobalConsumedBytes();
  size_t global_limit = global_allocation_limit();
  if (global_size < global_limit) {
    return global_limit - global_size;
  } else {
    return 0;
  }
}
References global_allocation_limit(), and GlobalConsumedBytes().
Referenced by IncrementalMarkingLimitReached(), and RecomputeLimitsAfterLoadingIfNeeded().
GlobalSizeOfObjects()
size_t v8::internal::Heap::GlobalSizeOfObjects () const
Definition at line 5423 of file heap.cc.
                                       {
  return OldGenerationSizeOfObjects() + EmbedderSizeOfObjects() +
         (v8_flags.external_memory_accounted_in_global_limit ? external_memory()
                                                             : 0);
}
References EmbedderSizeOfObjects(), external_memory(), OldGenerationSizeOfObjects(), and v8::internal::v8_flags.
Referenced by GlobalConsumedBytes(), and v8::internal::IncrementalMarking::Start().
GlobalWastedBytes()
size_t v8::internal::Heap::GlobalWastedBytes () const
Definition at line 5429 of file heap.cc.
{ return OldGenerationWastedBytes(); }
References OldGenerationWastedBytes().
Referenced by GlobalConsumedBytes(), and v8::internal::IncrementalMarking::Start().
HandleExternalMemoryInterrupt()
void v8::internal::Heap::HandleExternalMemoryInterrupt ()
Definition at line 1453 of file heap.cc.
                                         {
  const GCCallbackFlags kGCCallbackFlagsForExternalMemory =
      static_cast<GCCallbackFlags>(
          kGCCallbackFlagSynchronousPhantomCallbackProcessing |
          kGCCallbackFlagCollectAllExternalMemory);
  uint64_t current = external_memory();
  if (current > external_memory_hard_limit()) {
    TRACE_EVENT2("devtools.timeline,v8", "V8.ExternalMemoryPressure",
                 "external_memory_mb", static_cast<int>((current) / MB),
                 "external_memory_hard_limit_mb",
                 static_cast<int>((external_memory_hard_limit()) / MB));
    CollectAllGarbage(
        GCFlag::kReduceMemoryFootprint,
        GarbageCollectionReason::kExternalMemoryPressure,
        static_cast<GCCallbackFlags>(kGCCallbackFlagCollectAllAvailableGarbage |
                                     kGCCallbackFlagsForExternalMemory));
    return;
  }
  if (v8_flags.external_memory_accounted_in_global_limit) {
    // Under `external_memory_accounted_in_global_limit`, external interrupt
    // only triggers a check to allocation limits.
    external_memory_.UpdateLimitForInterrupt(current);
    StartIncrementalMarkingIfAllocationLimitIsReached(
        main_thread_local_heap(), GCFlagsForIncrementalMarking(),
        kGCCallbackFlagsForExternalMemory);
    return;
  }
  uint64_t soft_limit = external_memory_.soft_limit();
  if (current <= soft_limit) {
    return;
  }
  TRACE_EVENT2("devtools.timeline,v8", "V8.ExternalMemoryPressure",
               "external_memory_mb", static_cast<int>((current) / MB),
               "external_memory_soft_limit_mb",
               static_cast<int>((soft_limit) / MB));
  if (incremental_marking()->IsStopped()) {
    if (incremental_marking()->CanAndShouldBeStarted()) {
      StartIncrementalMarking(GCFlagsForIncrementalMarking(),
                              GarbageCollectionReason::kExternalMemoryPressure,
                              kGCCallbackFlagsForExternalMemory);
    } else {
      CollectAllGarbage(i::GCFlag::kNoFlags,
                        GarbageCollectionReason::kExternalMemoryPressure,
                        kGCCallbackFlagsForExternalMemory);
    }
  } else {
    // Incremental marking is turned on and has already been started.
    current_gc_callback_flags_ = static_cast<GCCallbackFlags>(
        current_gc_callback_flags_ | kGCCallbackFlagsForExternalMemory);
    incremental_marking()->AdvanceAndFinalizeIfNecessary();
  }
}
References v8::internal::IncrementalMarking::AdvanceAndFinalizeIfNecessary(), CollectAllGarbage(), current_gc_callback_flags_, external_memory(), external_memory_, external_memory_hard_limit(), GCFlagsForIncrementalMarking(), incremental_marking(), v8::internal::kExternalMemoryPressure, v8::kGCCallbackFlagCollectAllAvailableGarbage, v8::kGCCallbackFlagCollectAllExternalMemory, v8::kGCCallbackFlagSynchronousPhantomCallbackProcessing, v8::internal::kNoFlags, v8::internal::kReduceMemoryFootprint, main_thread_local_heap(), v8::internal::MB, v8::internal::Heap::ExternalMemoryAccounting::soft_limit(), StartIncrementalMarking(), StartIncrementalMarkingIfAllocationLimitIsReached(), TRACE_EVENT2, v8::internal::Heap::ExternalMemoryAccounting::UpdateLimitForInterrupt(), and v8::internal::v8_flags.
HandleGCRequest()
void v8::internal::Heap::HandleGCRequest ()
Definition at line 1205 of file heap.cc.
                           {
  if (IsStressingScavenge() && stress_scavenge_observer_->HasRequestedGC()) {
    CollectGarbage(NEW_SPACE, GarbageCollectionReason::kTesting);
    stress_scavenge_observer_->RequestedGCDone();
  } else if (HighMemoryPressure()) {
    CheckMemoryPressure();
  } else if (CollectionRequested()) {
    CheckCollectionRequested();
  } else if (incremental_marking()->MajorCollectionRequested()) {
    CollectAllGarbage(current_gc_flags_,
                      GarbageCollectionReason::kFinalizeMarkingViaStackGuard,
                      current_gc_callback_flags_);
  } else if (minor_mark_sweep_collector()->gc_finalization_requsted()) {
    CollectGarbage(NEW_SPACE,
                   GarbageCollectionReason::kFinalizeConcurrentMinorMS);
  }
}
References CheckCollectionRequested(), CheckMemoryPressure(), CollectAllGarbage(), CollectGarbage(), CollectionRequested(), current_gc_callback_flags_, current_gc_flags_, v8::internal::StressScavengeObserver::HasRequestedGC(), HighMemoryPressure(), incremental_marking(), IsStressingScavenge(), v8::internal::kFinalizeConcurrentMinorMS, v8::internal::kFinalizeMarkingViaStackGuard, v8::internal::kTesting, minor_mark_sweep_collector(), v8::internal::NEW_SPACE, v8::internal::StressScavengeObserver::RequestedGCDone(), and stress_scavenge_observer_.
Referenced by v8::internal::StackGuard::HandleInterrupts().
has_heap_object_allocation_tracker()
bool v8::internal::Heap::has_heap_object_allocation_tracker () const [inline]
Definition at line 1562 of file heap.h.
                                                  {
    return !allocation_trackers_.empty();
  }
Referenced by v8::internal::Isolate::UpdateLogObjectRelocation().
HasBeenSetUp()
bool v8::internal::Heap::HasBeenSetUp () const
Definition at line 449 of file heap.cc.
                              {
  // We will always have an old space when the heap is set up.
  return old_space_ != nullptr;
}
References old_space_.
Referenced by Available(), Capacity(), CommittedMemory(), CommittedMemoryExecutable(), CommittedOldGenerationMemory(), CommittedPhysicalMemory(), Contains(), ContainsCode(), v8::internal::Isolate::Init(), InSpace(), InSpaceSlow(), OldGenerationCapacity(), v8::internal::ProfilingScope::ProfilingScope(), and UpdateMaximumCommitted().
HasDirtyJSFinalizationRegistries()
bool v8::internal::Heap::HasDirtyJSFinalizationRegistries ()
Definition at line 7035 of file heap.cc.
                                            {
  return !IsUndefined(dirty_js_finalization_registries_list(), isolate());
}
References dirty_js_finalization_registries_list(), and isolate().
Referenced by DequeueDirtyJSFinalizationRegistry(), EnqueueDirtyJSFinalizationRegistry(), and PostFinalizationRegistryCleanupTaskIfNeeded().
HasHighFragmentation()
bool v8::internal::Heap::HasHighFragmentation ()
Definition at line 3883 of file heap.cc.
                                {
  const size_t used = OldGenerationSizeOfObjects();
  const size_t committed = CommittedOldGenerationMemory();
  // Background thread allocation could result in committed memory being less
  // than used memory in some situations.
  if (committed < used) return false;
  constexpr size_t kSlack = 16 * MB;
  // Fragmentation is high if committed > 2 * used + kSlack.
  // Rewrite the expression to avoid overflow.
  return committed - used > used + kSlack;
}
References CommittedOldGenerationMemory(), v8::internal::MB, and OldGenerationSizeOfObjects().
Referenced by v8::internal::MemoryReducer::NotifyMarkCompact().
HasLowAllocationRate()
bool v8::internal::Heap::HasLowAllocationRate ()
Definition at line 3843 of file heap.cc.
                                {
  return HasLowYoungGenerationAllocationRate() &&
         HasLowOldGenerationAllocationRate() && HasLowEmbedderAllocationRate();
}
References HasLowEmbedderAllocationRate(), HasLowOldGenerationAllocationRate(), and HasLowYoungGenerationAllocationRate().
HasLowEmbedderAllocationRate()
bool v8::internal::Heap::HasLowEmbedderAllocationRate () [private]
Definition at line 3835 of file heap.cc.
                                        {
  double mu = ComputeMutatorUtilization(
      "Embedder", tracer()->EmbedderAllocationThroughputInBytesPerMillisecond(),
      tracer()->EmbedderSpeedInBytesPerMillisecond());
  const double kHighMutatorUtilization = 0.993;
  return mu > kHighMutatorUtilization;
}
References ComputeMutatorUtilization(), v8::internal::mu, and tracer().
Referenced by HasLowAllocationRate().
HasLowOldGenerationAllocationRate()
bool v8::internal::Heap::HasLowOldGenerationAllocationRate () [private]
Definition at line 3826 of file heap.cc.
                                             {
  double mu = ComputeMutatorUtilization(
      "Old generation",
      tracer()->OldGenerationAllocationThroughputInBytesPerMillisecond(),
      tracer()->OldGenerationSpeedInBytesPerMillisecond());
  const double kHighMutatorUtilization = 0.993;
  return mu > kHighMutatorUtilization;
}
References ComputeMutatorUtilization(), v8::internal::mu, and tracer().
Referenced by HasLowAllocationRate().
HasLowYoungGenerationAllocationRate()
bool v8::internal::Heap::HasLowYoungGenerationAllocationRate () [private]
Definition at line 3816 of file heap.cc.
                                               {
  double mu = ComputeMutatorUtilization(
      "Young generation",
      tracer()->NewSpaceAllocationThroughputInBytesPerMillisecond(),
      tracer()->YoungGenerationSpeedInBytesPerMillisecond(
          YoungGenerationSpeedMode::kOnlyAtomicPause));
  constexpr double kHighMutatorUtilization = 0.993;
  return mu > kHighMutatorUtilization;
}
References ComputeMutatorUtilization(), v8::internal::kOnlyAtomicPause, v8::internal::mu, and tracer().
Referenced by HasLowAllocationRate(), and RecomputeLimits().
heap_expansion_mutex()
base::Mutex* v8::internal::Heap::heap_expansion_mutex () [inline]
Definition at line 1322 of file heap.h.
{ return &heap_expansion_mutex_; }
Referenced by v8::internal::LargeObjectSpace::AllocateLargePage().
heap_profiler()
HeapProfiler* v8::internal::Heap::heap_profiler () const [inline]
Definition at line 408 of file heap.h.
{ return heap_profiler_.get(); }
Referenced by v8::internal::CppHeap::AttachIsolate(), CanMoveObjectStart(), CheckHeapLimitReached(), CheckIneffectiveMarkCompact(), CollectAllAvailableGarbage(), CollectGarbage(), v8::internal::Isolate::Deinit(), v8::HeapSnapshot::Delete(), v8::internal::Isolate::Init(), OnMoveEvent(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::Isolate::UpdateLogObjectRelocation().
HeapLimitMultiplier()
size_t v8::internal::Heap::HeapLimitMultiplier () [static]
Definition at line 5031 of file heap.cc.
                                 {
#if V8_OS_ANDROID
  // Don't apply pointer multiplier on Android since it has no swap space and
  // should instead adapt it's heap size based on available physical memory.
  if (!v8_flags.high_end_android) {
    return 1;
  }
#endif
  // The heap limit needs to be computed based on the system pointer size
  // because we want a pointer-compressed heap to have larger limit than
  // an ordinary 32-bit which that is constrained by 2GB virtual address space.
  return kSystemPointerSize / 4;
}
References v8::internal::kSystemPointerSize, and v8::internal::v8_flags.
Referenced by DefaulMaxHeapSize(), DefaulMinHeapSize(), DefaultInitialOldGenerationSize(), HeapSizeFromPhysicalMemory(), OldGenerationLowMemory(), and OldGenerationToSemiSpaceRatioLowMemory().
HeapSizeFromPhysicalMemory()
size_t v8::internal::Heap::HeapSizeFromPhysicalMemory (uint64_t physical_memory) [static]
Definition at line 226 of file heap.cc.
                                                                {
  // Compute the old generation size and cap it.
  uint64_t old_generation = physical_memory /
                            kPhysicalMemoryToOldGenerationRatio *
                            HeapLimitMultiplier();
  old_generation =
      std::min(old_generation,
               static_cast<uint64_t>(
                   MaxOldGenerationSizeFromPhysicalMemory(physical_memory)));
  old_generation =
      std::max({old_generation, static_cast<uint64_t>(DefaulMinHeapSize())});
  old_generation = RoundUp(old_generation, PageMetadata::kPageSize);
  size_t young_generation = YoungGenerationSizeFromOldGenerationSize(
      static_cast<size_t>(old_generation));
  return static_cast<size_t>(old_generation) + young_generation;
}
References DefaulMinHeapSize(), HeapLimitMultiplier(), v8::internal::MutablePageMetadata::kPageSize, kPhysicalMemoryToOldGenerationRatio, MaxOldGenerationSizeFromPhysicalMemory(), RoundUp(), and YoungGenerationSizeFromOldGenerationSize().
Referenced by v8::ResourceConstraints::ConfigureDefaults().
HighMemoryPressure()
bool v8::internal::Heap::HighMemoryPressure () [inline]
Definition at line 698 of file heap.h.
                            {
    return memory_pressure_level_.load(std::memory_order_relaxed) !=
           v8::MemoryPressureLevel::kNone;
  }
References v8::kNone.
Referenced by CheckMemoryPressure(), v8::internal::anonymous_namespace{compiler.cc}::CompileTurbofan_Concurrent(), HandleGCRequest(), IncrementalMarkingLimitReached(), and ShouldOptimizeForMemoryUsage().
ignore_local_gc_requests()
bool v8::internal::Heap::ignore_local_gc_requests () const [inline]
Definition at line 577 of file heap.h.
                                        {
    return ignore_local_gc_requests_depth_ > 0;
  }
incremental_marking()
IncrementalMarking* v8::internal::Heap::incremental_marking () const [inline]
Definition at line 1117 of file heap.h.
                                                  {
    return incremental_marking_.get();
  }
Referenced by v8::internal::UnifiedHeapMarker::AdvanceMarkingOnAllocationImpl(), AllocateExternalBackingStore(), v8::internal::MemoryAllocator::AllocatePage(), AllocationLimitOvershotByLargeMargin(), AttachCppHeap(), CanMoveObjectStart(), CanShortcutStringsDuringGC(), CheckMemoryPressure(), CollectGarbage(), CollectGarbageOnMemoryPressure(), v8::internal::PageMetadata::ConvertNewToOld(), FinalizeIncrementalMarkingAtomically(), FinalizeIncrementalMarkingAtomicallyIfRunning(), HandleExternalMemoryInterrupt(), HandleGCRequest(), v8::internal::ScavengerCollector::HandleSurvivingNewLargeObjects(), IncrementalMarkingLimitReached(), v8::internal::Isolate::Init(), v8::internal::MainAllocator::IsBlackAllocationEnabled(), IsNewSpaceAllowedToGrowAboveTargetCapacity(), v8::internal::LocalHeap::LocalHeap(), v8::internal::MinorMarkSweepCollector::MarkLiveObjects(), MinorMarkSweep(), NotifyLoadingEnded(), NotifyObjectLayoutChange(), v8::internal::MarkCompactCollector::Prepare(), v8::internal::OldLargeObjectSpace::PromoteNewLargeObject(), v8::internal::Sweeper::RawSweep(), RecomputeLimitsAfterLoadingIfNeeded(), v8::internal::PagedSpaceAllocatorPolicy::RefillLab(), RightTrimArray(), Scavenge(), v8::internal::IncrementalMarkingJob::ScheduleTask(), SelectGarbageCollector(), v8::internal::LocalHeap::SetUpSharedMarking(), ShouldExpandOldGenerationOnSlowAllocation(), ShouldExpandYoungGenerationOnSlowAllocation(), v8::internal::CppHeap::StartDetachingIsolate(), StartIncrementalMarking(), StartIncrementalMarkingIfAllocationLimitIsReached(), StartMinorMSConcurrentMarkingIfNeeded(), v8::internal::IncrementalMarking::Stop(), v8::internal::MarkCompactCollector::TearDown(), v8::internal::MinorMarkSweepCollector::TearDown(), v8::internal::MarkCompactCollector::VerifyMarking(), and WeakenDescriptorArrays().
IncrementalMarkingLimitReached()
Heap::IncrementalMarkingLimit v8::internal::Heap::IncrementalMarkingLimitReached () [private]
Definition at line 5640 of file heap.cc.
                                                                 {
  // InstructionStream using an AlwaysAllocateScope assumes that the GC state
  // does not change; that implies that no marking steps must be performed.
  if (!incremental_marking()->CanAndShouldBeStarted() || always_allocate()) {
    // Incremental marking is disabled or it is too early to start.
    return IncrementalMarkingLimit::kNoLimit;
  }
  if (v8_flags.stress_incremental_marking) {
    return IncrementalMarkingLimit::kHardLimit;
  }
  if (incremental_marking()->IsBelowActivationThresholds()) {
    // Incremental marking is disabled or it is too early to start.
    return IncrementalMarkingLimit::kNoLimit;
  }
  if (ShouldStressCompaction() || HighMemoryPressure()) {
    // If there is high memory pressure or stress testing is enabled, then
    // start marking immediately.
    return IncrementalMarkingLimit::kHardLimit;
  }
  if (v8_flags.stress_marking > 0) {
    int current_percent = static_cast<int>(
        std::max(PercentToOldGenerationLimit(), PercentToGlobalMemoryLimit()));
    if (current_percent > 0) {
      if (v8_flags.trace_stress_marking) {
        isolate()->PrintWithTimestamp(
            "[IncrementalMarking] %d%% of the memory limit reached\n",
            current_percent);
      }
      if (v8_flags.fuzzer_gc_analysis) {
        // Skips values >=100% since they already trigger marking.
        if (current_percent < 100) {
          double max_marking_limit_reached =
              max_marking_limit_reached_.load(std::memory_order_relaxed);
          while (current_percent > max_marking_limit_reached) {
            max_marking_limit_reached_.compare_exchange_weak(
                max_marking_limit_reached, current_percent,
                std::memory_order_relaxed);
          }
        }
      } else if (current_percent >= stress_marking_percentage_) {
        return IncrementalMarkingLimit::kHardLimit;
      }
    }
  }
  if (v8_flags.incremental_marking_soft_trigger > 0 ||
      v8_flags.incremental_marking_hard_trigger > 0) {
    int current_percent = static_cast<int>(
        std::max(PercentToOldGenerationLimit(), PercentToGlobalMemoryLimit()));
    if (current_percent > v8_flags.incremental_marking_hard_trigger &&
        v8_flags.incremental_marking_hard_trigger > 0) {
      return IncrementalMarkingLimit::kHardLimit;
    }
    if (current_percent > v8_flags.incremental_marking_soft_trigger &&
        v8_flags.incremental_marking_soft_trigger > 0) {
      return IncrementalMarkingLimit::kSoftLimit;
    }
    return IncrementalMarkingLimit::kNoLimit;
  }
  tracer()->RecordGCSizeCounters();
  size_t old_generation_space_available = OldGenerationSpaceAvailable();
  size_t global_memory_available = GlobalMemoryAvailable();
  if (old_generation_space_available > NewSpaceTargetCapacity() &&
      (global_memory_available > NewSpaceTargetCapacity())) {
    if (cpp_heap() && gc_count_ == 0 && using_initial_limit()) {
      // At this point the embedder memory is above the activation
      // threshold. No GC happened so far and it's thus unlikely to get a
      // configured heap any time soon. Start a memory reducer in this case
      // which will wait until the allocation rate is low to trigger garbage
      // collection.
      return IncrementalMarkingLimit::kFallbackForEmbedderLimit;
    }
    return IncrementalMarkingLimit::kNoLimit;
  }
  if (ShouldOptimizeForMemoryUsage()) {
    return IncrementalMarkingLimit::kHardLimit;
  }
  if (ShouldOptimizeForLoadTime()) {
    return IncrementalMarkingLimit::kNoLimit;
  }
  if (old_generation_space_available == 0) {
    return IncrementalMarkingLimit::kHardLimit;
  }
  if (global_memory_available == 0) {
    return IncrementalMarkingLimit::kHardLimit;
  }
  return IncrementalMarkingLimit::kSoftLimit;
}
References always_allocate(), cpp_heap(), gc_count_, GlobalMemoryAvailable(), HighMemoryPressure(), incremental_marking(), isolate(), kFallbackForEmbedderLimit, kHardLimit, kNoLimit, kSoftLimit, max_marking_limit_reached_, NewSpaceTargetCapacity(), OldGenerationSpaceAvailable(), PercentToGlobalMemoryLimit(), PercentToOldGenerationLimit(), v8::internal::GCTracer::RecordGCSizeCounters(), ShouldOptimizeForLoadTime(), ShouldOptimizeForMemoryUsage(), ShouldStressCompaction(), stress_marking_percentage_, tracer(), using_initial_limit(), and v8::internal::v8_flags.
Referenced by ShouldExpandOldGenerationOnSlowAllocation(), and StartIncrementalMarkingIfAllocationLimitIsReached().
IncrementDeferredCounts()
void v8::internal::Heap::IncrementDeferredCounts (base::Vector< const v8::Isolate::UseCounterFeature > features)
Definition at line 944 of file heap.cc.
                                                           {
  deferred_counters_.insert(deferred_counters_.end(), features.begin(),
                            features.end());
}
References v8::base::Vector< T >::begin(), deferred_counters_, v8::base::SmallVector< T, kSize, Allocator >::end(), v8::base::Vector< T >::end(), and v8::base::SmallVector< T, kSize, Allocator >::insert().
Referenced by v8::internal::Isolate::CountUsage().
IncrementExternalBackingStoreBytes()
void v8::internal::Heap::IncrementExternalBackingStoreBytes (ExternalBackingStoreType type, size_t amount) [inline], [private]
Definition at line 401 of file heap-inl.h.
                                                             {
  base::CheckedIncrement(&backing_store_bytes_, static_cast<uint64_t>(amount),
                         std::memory_order_relaxed);
  // TODO(mlippautz): Implement interrupt for global memory allocations that can
  // trigger garbage collections.
}
References backing_store_bytes_, and v8::base::CheckedIncrement().
Referenced by v8::internal::Space::IncrementExternalBackingStoreBytes(), and v8::internal::ArrayBufferSweeper::IncrementExternalMemoryCounters().
IncrementNewSpaceSurvivingObjectSize()
void v8::internal::Heap::IncrementNewSpaceSurvivingObjectSize (size_t object_size) [inline]
Definition at line 1364 of file heap.h.
                                                                       {
    new_space_surviving_object_size_ += object_size;
  }
Referenced by v8::internal::Sweeper::AddNewSpacePage().
IncrementNodesCopiedInNewSpace()
void v8::internal::Heap::IncrementNodesCopiedInNewSpace () [inline]
Definition at line 1379 of file heap.h.
{ nodes_copied_in_new_space_++; }
Referenced by v8::internal::anonymous_namespace{global-handles.cc}::UpdateListOfYoungNodesImpl().
IncrementNodesDiedInNewSpace()
void v8::internal::Heap::IncrementNodesDiedInNewSpace (int count) [inline]
Definition at line 1375 of file heap.h.
                                                      {
    nodes_died_in_new_space_ += count;
  }
Referenced by v8::internal::anonymous_namespace{global-handles.cc}::ClearListOfYoungNodesImpl(), and v8::internal::anonymous_namespace{global-handles.cc}::UpdateListOfYoungNodesImpl().
IncrementNodesPromoted()
void v8::internal::Heap::IncrementNodesPromoted () [inline]
Definition at line 1381 of file heap.h.
{ nodes_promoted_++; }
Referenced by v8::internal::anonymous_namespace{global-handles.cc}::UpdateListOfYoungNodesImpl().
IncrementPromotedObjectsSize()
void v8::internal::Heap::IncrementPromotedObjectsSize (size_t object_size) [inline]
Definition at line 1359 of file heap.h.
                                                               {
    promoted_objects_size_ += object_size;
  }
Referenced by v8::internal::Sweeper::AddPromotedPage().
IncrementYoungSurvivorsCounter()
void v8::internal::Heap::IncrementYoungSurvivorsCounter (size_t survived) [inline]
Definition at line 1383 of file heap.h.
                                                              {
    survived_since_last_expansion_ += survived;
  }
Referenced by v8::internal::Sweeper::AddNewSpacePage(), and v8::internal::Sweeper::AddPromotedPage().
InFromPage() [1/3]
bool v8::internal::Heap::InFromPage (Tagged< HeapObject > heap_object) [inline], [static]
Definition at line 254 of file heap-inl.h.
                                                    {
  return MemoryChunk::FromHeapObject(heap_object)->IsFromPage();
}
References v8::internal::MemoryChunk::FromHeapObject(), and v8::internal::MemoryChunk::IsFromPage().
InFromPage() [2/3]
bool v8::internal::Heap::InFromPage (Tagged< MaybeObject > object) [inline], [static]
Definition at line 248 of file heap-inl.h.
                                                {
  Tagged<HeapObject> heap_object;
  return object.GetHeapObject(&heap_object) && InFromPage(heap_object);
}
References v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObject(), and InFromPage().
InFromPage() [3/3]
bool v8::internal::Heap::InFromPage (Tagged< Object > object) [inline], [static]
Definition at line 242 of file heap-inl.h.
                                           {
  DCHECK(!HasWeakHeapObjectTag(object));
  return IsHeapObject(object) && InFromPage(Cast<HeapObject>(object));
}
References v8::internal::DCHECK(), v8::internal::HasWeakHeapObjectTag(), and v8::internal::IsHeapObject().
Referenced by v8::internal::Scavenger::CheckAndScavengeObject(), v8::internal::Scavenger::EvacuateObject(), v8::internal::ForwardingAddress(), v8::internal::anonymous_namespace{scavenger.cc}::ObjectPinningVisitorBase< ConcreteVisitor >::HandleHeapObject(), v8::internal::IterateAndScavengePromotedObjectsVisitor::HandleSlot(), InFromPage(), v8::internal::anonymous_namespace{scavenger.cc}::IsUnscavengedHeapObject(), v8::internal::Scavenger::PromoteObject(), v8::internal::Scavenger::ScavengeObject(), v8::internal::Scavenger::SemiSpaceCopyObject(), v8::internal::StringForwardingTable::Block::UpdateAfterYoungEvacuation(), v8::internal::anonymous_namespace{scavenger.cc}::GlobalHandlesWeakRootsUpdatingVisitor::UpdatePointer(), and UpdateYoungReferenceInExternalStringTableEntry().
InitializeHashSeed()
void v8::internal::Heap::InitializeHashSeed ()
Definition at line 6087 of file heap.cc.
                              {
  DCHECK(!deserialization_complete_);
  uint64_t new_hash_seed;
  if (v8_flags.hash_seed == 0) {
    int64_t rnd = isolate()->random_number_generator()->NextInt64();
    new_hash_seed = static_cast<uint64_t>(rnd);
  } else {
    new_hash_seed = static_cast<uint64_t>(v8_flags.hash_seed);
  }
  Tagged<ByteArray> hash_seed = ReadOnlyRoots(this).hash_seed();
  MemCopy(hash_seed->begin(), reinterpret_cast<uint8_t*>(&new_hash_seed),
          kInt64Size);
}
References v8::internal::DCHECK(), deserialization_complete_, isolate(), v8::internal::kInt64Size, v8::internal::MemCopy(), v8::base::RandomNumberGenerator::NextInt64(), v8::internal::Isolate::random_number_generator(), ReadOnlyRoots, and v8::internal::v8_flags.
Referenced by CreateImportantReadOnlyObjects(), and v8::internal::ReadOnlyDeserializer::DeserializeIntoIsolate().
InitializeMainThreadLocalHeap()
void v8::internal::Heap::InitializeMainThreadLocalHeap (LocalHeap * main_thread_local_heap)
InitializeOncePerProcess()
void v8::internal::Heap::InitializeOncePerProcess () [static]
Definition at line 6108 of file heap.cc.
                                    {
#ifdef V8_ENABLE_ALLOCATION_TIMEOUT
  HeapAllocator::InitializeOncePerProcess();
#endif
  MemoryAllocator::InitializeOncePerProcess();
  if (v8_flags.predictable) {
    ::heap::base::WorklistBase::EnforcePredictableOrder();
  }
}
References heap::base::WorklistBase::EnforcePredictableOrder(), v8::internal::MemoryAllocator::InitializeOncePerProcess(), and v8::internal::v8_flags.
Referenced by v8::internal::Isolate::InitializeOncePerProcess().
InitialSemiSpaceSize()
size_t v8::internal::Heap::InitialSemiSpaceSize () [inline]
Definition at line 1293 of file heap.h.
{ return initial_semispace_size_; }
InOldSpace()
bool v8::internal::Heap::InOldSpace (Tagged< Object > object) [inline]
Definition at line 275 of file heap-inl.h.
                                           {
  return old_space_->Contains(object) &&
         (!v8_flags.sticky_mark_bits || !HeapLayout::InYoungGeneration(object));
}
References v8::internal::PagedSpaceBase::Contains(), v8::internal::HeapLayout::InYoungGeneration(), old_space_, and v8::internal::v8_flags.
Referenced by CompactWeakArrayLists().
InsertIntoRememberedSetFromCode()
int v8::internal::Heap::InsertIntoRememberedSetFromCode (MutablePageMetadata * chunk, size_t slot_offset) [static]
Definition at line 6629 of file heap.cc.
                                                              {
  // This is called during runtime by a builtin, therefore it is run in the main
  // thread.
  DCHECK_NULL(LocalHeap::Current());
  RememberedSet<OLD_TO_NEW>::Insert<AccessMode::NON_ATOMIC>(chunk, slot_offset);
  return 0;
}
References DCHECK_NULL.
InSpace()
bool v8::internal::Heap::InSpace (Tagged< HeapObject > value, AllocationSpace space) const
Definition at line 4534 of file heap.cc.
                                                                        {
  if (memory_allocator()->IsOutsideAllocatedSpace(
          value.address(),
          IsAnyCodeSpace(space) ? EXECUTABLE : NOT_EXECUTABLE)) {
    return false;
  }
  if (!HasBeenSetUp()) return false;
  switch (space) {
    case NEW_SPACE:
      return new_space_->Contains(value);
    case OLD_SPACE:
      return old_space_->Contains(value);
    case CODE_SPACE:
      return code_space_->Contains(value);
    case SHARED_SPACE:
      return shared_space_->Contains(value);
    case TRUSTED_SPACE:
      return trusted_space_->Contains(value);
    case SHARED_TRUSTED_SPACE:
      return shared_trusted_space_->Contains(value);
    case LO_SPACE:
      return lo_space_->Contains(value);
    case CODE_LO_SPACE:
      return code_lo_space_->Contains(value);
    case NEW_LO_SPACE:
      return new_lo_space_->Contains(value);
    case SHARED_LO_SPACE:
      return shared_lo_space_->Contains(value);
    case SHARED_TRUSTED_LO_SPACE:
      return shared_trusted_lo_space_->Contains(value);
    case TRUSTED_LO_SPACE:
      return trusted_lo_space_->Contains(value);
    case RO_SPACE:
      return ReadOnlyHeap::Contains(value);
  }
  UNREACHABLE();
}
References v8::internal::CODE_LO_SPACE, code_lo_space_, v8::internal::CODE_SPACE, code_space_, v8::internal::PagedSpaceBase::Contains(), v8::internal::ReadOnlyHeap::Contains(), v8::internal::LargeObjectSpace::Contains(), v8::internal::NewSpace::Contains(), v8::internal::EXECUTABLE, HasBeenSetUp(), v8::internal::IsAnyCodeSpace(), v8::internal::LO_SPACE, lo_space_, memory_allocator(), v8::internal::NEW_LO_SPACE, new_lo_space_, v8::internal::NEW_SPACE, new_space_, v8::internal::NOT_EXECUTABLE, v8::internal::OLD_SPACE, old_space_, v8::internal::RO_SPACE, v8::internal::SHARED_LO_SPACE, shared_lo_space_, v8::internal::SHARED_SPACE, shared_space_, v8::internal::SHARED_TRUSTED_LO_SPACE, shared_trusted_lo_space_, v8::internal::SHARED_TRUSTED_SPACE, shared_trusted_space_, space(), v8::internal::TRUSTED_LO_SPACE, trusted_lo_space_, v8::internal::TRUSTED_SPACE, trusted_space_, v8::internal::UNREACHABLE(), and v8::internal::value.
InSpaceSlow()
bool v8::internal::Heap::InSpaceSlow (Address addr, AllocationSpace space) const
Definition at line 4573 of file heap.cc.
                                                                {
  if (memory_allocator()->IsOutsideAllocatedSpace(
          addr, IsAnyCodeSpace(space) ? EXECUTABLE : NOT_EXECUTABLE)) {
    return false;
  }
  if (!HasBeenSetUp()) return false;
  switch (space) {
    case NEW_SPACE:
      return new_space_->ContainsSlow(addr);
    case OLD_SPACE:
      return old_space_->ContainsSlow(addr);
    case CODE_SPACE:
      return code_space_->ContainsSlow(addr);
    case SHARED_SPACE:
      return shared_space_->ContainsSlow(addr);
    case TRUSTED_SPACE:
      return trusted_space_->ContainsSlow(addr);
    case SHARED_TRUSTED_SPACE:
      return shared_trusted_space_->ContainsSlow(addr);
    case LO_SPACE:
      return lo_space_->ContainsSlow(addr);
    case CODE_LO_SPACE:
      return code_lo_space_->ContainsSlow(addr);
    case NEW_LO_SPACE:
      return new_lo_space_->ContainsSlow(addr);
    case SHARED_LO_SPACE:
      return shared_lo_space_->ContainsSlow(addr);
    case SHARED_TRUSTED_LO_SPACE:
      return shared_trusted_lo_space_->ContainsSlow(addr);
    case TRUSTED_LO_SPACE:
      return trusted_lo_space_->ContainsSlow(addr);
    case RO_SPACE:
      return read_only_space_->ContainsSlow(addr);
  }
  UNREACHABLE();
}
References v8::internal::CODE_LO_SPACE, code_lo_space_, v8::internal::CODE_SPACE, code_space_, v8::internal::NewSpace::ContainsSlow(), v8::internal::LargeObjectSpace::ContainsSlow(), v8::internal::PagedSpaceBase::ContainsSlow(), v8::internal::ReadOnlySpace::ContainsSlow(), v8::internal::EXECUTABLE, HasBeenSetUp(), v8::internal::IsAnyCodeSpace(), v8::internal::LO_SPACE, lo_space_, memory_allocator(), v8::internal::NEW_LO_SPACE, new_lo_space_, v8::internal::NEW_SPACE, new_space_, v8::internal::NOT_EXECUTABLE, v8::internal::OLD_SPACE, old_space_, read_only_space_, v8::internal::RO_SPACE, v8::internal::SHARED_LO_SPACE, shared_lo_space_, v8::internal::SHARED_SPACE, shared_space_, v8::internal::SHARED_TRUSTED_LO_SPACE, shared_trusted_lo_space_, v8::internal::SHARED_TRUSTED_SPACE, shared_trusted_space_, space(), v8::internal::TRUSTED_LO_SPACE, trusted_lo_space_, v8::internal::TRUSTED_SPACE, trusted_space_, and v8::internal::UNREACHABLE().
Referenced by v8::internal::anonymous_namespace{frames.cc}::IsInterpreterFramePc(), and TryFindCodeForInnerPointerForPrinting().
InToPage() [1/3]
bool v8::internal::Heap::InToPage (Tagged< HeapObject > heap_object) [inline], [static]
Definition at line 271 of file heap-inl.h.
                                                  {
  return MemoryChunk::FromHeapObject(heap_object)->IsToPage();
}
References v8::internal::MemoryChunk::FromHeapObject(), and v8::internal::MemoryChunk::IsToPage().
InToPage() [2/3]
bool v8::internal::Heap::InToPage (Tagged< MaybeObject > object) [inline], [static]
Definition at line 265 of file heap-inl.h.
                                              {
  Tagged<HeapObject> heap_object;
  return object.GetHeapObject(&heap_object) && InToPage(heap_object);
}
References v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObject(), and InToPage().
InToPage() [3/3]
bool v8::internal::Heap::InToPage (Tagged< Object > object) [inline], [static]
Definition at line 259 of file heap-inl.h.
                                         {
  DCHECK(!HasWeakHeapObjectTag(object));
  return IsHeapObject(object) && InToPage(Cast<HeapObject>(object));
}
References v8::internal::DCHECK(), v8::internal::HasWeakHeapObjectTag(), and v8::internal::IsHeapObject().
Referenced by v8::internal::Scavenger::CheckAndScavengeObject(), InToPage(), v8::internal::anonymous_namespace{minor-mark-sweep.cc}::IsUnmarkedObjectInYoungGeneration(), v8::internal::Scavenger::PromoteObject(), v8::internal::Scavenger::ScavengeObject(), v8::internal::Scavenger::SemiSpaceCopyObject(), and v8::internal::anonymous_namespace{scavenger.cc}::GlobalHandlesWeakRootsUpdatingVisitor::UpdatePointer().
InvokeIncrementalMarkingEpilogueCallbacks()
void v8::internal::Heap::InvokeIncrementalMarkingEpilogueCallbacks () [private]
Definition at line 4078 of file heap.cc.
                                                     {
  AllowGarbageCollection allow_allocation;
  VMState<EXTERNAL> state(isolate_);
  CallGCEpilogueCallbacks(kGCTypeIncrementalMarking, kNoGCCallbackFlags,
                          GCTracer::Scope::MC_INCREMENTAL_EXTERNAL_EPILOGUE);
}
References CallGCEpilogueCallbacks(), isolate_, v8::kGCTypeIncrementalMarking, and v8::kNoGCCallbackFlags.
Referenced by v8::internal::IncrementalMarking::StartMarkingMajor().
InvokeIncrementalMarkingPrologueCallbacks()
void v8::internal::Heap::InvokeIncrementalMarkingPrologueCallbacks () [private]
Definition at line 4071 of file heap.cc.
                                                     {
  AllowGarbageCollection allow_allocation;
  VMState<EXTERNAL> state(isolate_);
  CallGCPrologueCallbacks(kGCTypeIncrementalMarking, kNoGCCallbackFlags,
                          GCTracer::Scope::MC_INCREMENTAL_EXTERNAL_PROLOGUE);
}
References CallGCPrologueCallbacks(), isolate_, v8::kGCTypeIncrementalMarking, and v8::kNoGCCallbackFlags.
Referenced by v8::internal::IncrementalMarking::StartMarkingMajor().
InvokeNearHeapLimitCallback()
bool v8::internal::Heap::InvokeNearHeapLimitCallback () [private]
Definition at line 4405 of file heap.cc.
                                       {
  if (!near_heap_limit_callbacks_.empty()) {
    AllowGarbageCollection allow_gc;
    TRACE_GC(tracer(), GCTracer::Scope::HEAP_EXTERNAL_NEAR_HEAP_LIMIT);
    VMState<EXTERNAL> callback_state(isolate());
    HandleScope scope(isolate());
    v8::NearHeapLimitCallback callback =
        near_heap_limit_callbacks_.back().first;
    void* data = near_heap_limit_callbacks_.back().second;
    size_t heap_limit = callback(data, max_old_generation_size(),
                                 initial_max_old_generation_size_);
    if (heap_limit > max_old_generation_size()) {
      SetOldGenerationAndGlobalMaximumSize(
          std::min(heap_limit, AllocatorLimitOnMaxOldGenerationSize()));
      return true;
    }
  }
  return false;
}
References AllocatorLimitOnMaxOldGenerationSize(), initial_max_old_generation_size_, isolate(), max_old_generation_size(), near_heap_limit_callbacks_, SetOldGenerationAndGlobalMaximumSize(), TRACE_GC, and tracer().
Referenced by CheckHeapLimitReached(), CheckIneffectiveMarkCompact(), and CollectAllAvailableGarbage().
is_current_gc_forced()
bool v8::internal::Heap::is_current_gc_forced () const [inline]
Definition at line 1412 of file heap.h.
{ return is_current_gc_forced_; }
is_finalization_registry_cleanup_task_posted()
bool v8::internal::Heap::is_finalization_registry_cleanup_task_posted () [inline]
Definition at line 949 of file heap.h.
                                                      {
    return is_finalization_registry_cleanup_task_posted_;
  }
IsAllocationObserverActive()
bool v8::internal::Heap::IsAllocationObserverActive () const [inline]
Definition at line 581 of file heap.h.
                                          {
    return pause_allocation_observers_depth_ == 0;
  }
IsFreeSpaceValid()
bool v8::internal::Heap::IsFreeSpaceValid (const FreeSpace * object) [static]
Definition at line 6424 of file heap.cc.
                                                   {
  Heap* heap = HeapUtils::GetOwnerHeap(object);
  Tagged<Object> free_space_map =
      heap->isolate()->root(RootIndex::kFreeSpaceMap);
  CHECK(!heap->deserialization_complete() ||
        object->map_slot().contains_map_value(free_space_map.ptr()));
  CHECK_LE(offsetof(FreeSpace, next_) + kTaggedSize,
           object->size(kRelaxedLoad));
  return true;
}
References CHECK, CHECK_LE, v8::internal::FullObjectSlot::contains_map_value(), v8::internal::HeapUtils::GetOwnerHeap(), v8::kRelaxedLoad, v8::internal::kTaggedSize, v8::internal::HeapObjectLayout::map_slot(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), and v8::internal::FreeSpace::size().
Referenced by v8::internal::FreeSpace::IsValid().
IsGCWithMainThreadStack()
bool v8::internal::Heap::IsGCWithMainThreadStack () const
Definition at line 527 of file heap.cc.
                                         {
  return embedder_stack_state_ == StackState::kMayContainHeapPointers;
}
References embedder_stack_state_.
Referenced by IsGCWithStack(), and IterateConservativeStackRoots().
IsGCWithStack()
bool v8::internal::Heap::IsGCWithStack () const
Definition at line 531 of file heap.cc.
                               {
  return IsGCWithMainThreadStack() || stack().HasBackgroundStacks();
}
References heap::base::Stack::HasBackgroundStacks(), IsGCWithMainThreadStack(), and stack().
Referenced by CanShortcutStringsDuringGC(), v8::internal::ScavengerCollector::CollectGarbage(), IterateConservativeStackRoots(), v8::internal::MinorMarkSweepCollector::MarkRootsFromConservativeStack(), and v8::internal::MarkCompactCollector::StartCompaction().
IsImmovable()
bool v8::internal::Heap::IsImmovable (Tagged< HeapObject > object)
Definition at line 3422 of file heap.cc.
                                                {
  MemoryChunk* chunk = MemoryChunk::FromHeapObject(object);
  return chunk->NeverEvacuate() || chunk->IsLargePage();
}
References v8::internal::MemoryChunk::FromHeapObject(), v8::internal::MemoryChunk::IsLargePage(), and v8::internal::MemoryChunk::NeverEvacuate().
IsIneffectiveMarkCompact()
bool v8::internal::Heap::IsIneffectiveMarkCompact (size_t old_generation_size, double mutator_utilization) [private]
Definition at line 3848 of file heap.cc.
                                                                {
  const double kHighHeapPercentage = 0.8;
  const double kLowMutatorUtilization = 0.4;
  return old_generation_size >=
             kHighHeapPercentage * max_old_generation_size() &&
         mutator_utilization < kLowMutatorUtilization;
}
References max_old_generation_size().
Referenced by CheckIneffectiveMarkCompact().
IsInGC()
bool v8::internal::Heap::IsInGC () const [inline]
Definition at line 569 of file heap.h.
                      {
    // Load state only once and store it in local variable. Otherwise multiples
    // loads could return different states on background threads.
    HeapState state = gc_state();
    return state != NOT_IN_GC && state != TEAR_DOWN;
  }
Referenced by v8::internal::HeapAllocator::AllocateRaw(), and v8::internal::TickSample::GetStackSample().
IsInlineAllocationEnabled()
bool v8::internal::Heap::IsInlineAllocationEnabled () const [inline]
Definition at line 1685 of file heap.h.
{ return inline_allocation_enabled_; }
IsLargeObject()
bool v8::internal::Heap::IsLargeObject (Tagged< HeapObject > object) [static]
Definition at line 3427 of file heap.cc.
                                                  {
  return MemoryChunk::FromHeapObject(object)->IsLargePage();
}
References v8::internal::MemoryChunk::FromHeapObject(), and v8::internal::MemoryChunk::IsLargePage().
Referenced by CanMoveObjectStart(), LeftTrimFixedArray(), v8::internal::String::MakeExternal(), v8::internal::String::MakeExternalDuringGC(), v8::internal::String::MakeThin(), NotifyObjectSizeChange(), RightTrimArray(), v8::internal::Scavenger::ScavengeObject(), v8::internal::JSObject::UpdateAllocationSite(), and v8::internal::anonymous_namespace{scavenger.cc}::GlobalHandlesWeakRootsUpdatingVisitor::UpdatePointer().
IsLastResortGC()
bool v8::internal::Heap::IsLastResortGC () [inline]
Definition at line 1675 of file heap.h.
{ return current_gc_flags_ & GCFlag::kLastResort; }
Referenced by v8::internal::anonymous_namespace{mark-compact.cc}::GetCodeFlushMode().
IsMainThread()
bool v8::internal::Heap::IsMainThread () const [inline]
Definition at line 63 of file heap-inl.h.
                              {
  return isolate()->thread_id() == ThreadId::Current();
}
References v8::internal::ThreadId::Current(), isolate(), and v8::internal::Isolate::thread_id().
Referenced by v8::internal::Sweeper::AddPageImpl(), v8::internal::Sweeper::AddPromotedPage(), v8::internal::PagedSpaceAllocatorPolicy::ContributeToSweeping(), v8::internal::Sweeper::EnsureMajorCompleted(), v8::internal::Sweeper::EnsurePageIsSwept(), v8::internal::Sweeper::FinishMajorJobs(), v8::internal::Sweeper::FinishMinorJobs(), v8::internal::Sweeper::ParallelSweepSpace(), v8::internal::Sweeper::MajorSweeperJob::Run(), v8::internal::Sweeper::MinorSweeperJob::Run(), v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::Run(), v8::internal::GCTracer::Scope::Scope(), v8::internal::Sweeper::SweepEmptyNewSpacePage(), and v8::internal::Sweeper::WaitForPageToBeSwept().
IsMarkingFlagAddress()
uint8_t * v8::internal::Heap::IsMarkingFlagAddress ()
Definition at line 7393 of file heap.cc.
                                    {
  return &isolate()->isolate_data()->is_marking_flag_;
}
References v8::internal::IsolateData::is_marking_flag_, isolate(), and v8::internal::Isolate::isolate_data().
IsMinorMarkingFlagAddress()
uint8_t * v8::internal::Heap::IsMinorMarkingFlagAddress ()
Definition at line 7401 of file heap.cc.
                                         {
  return &isolate()->isolate_data()->is_minor_marking_flag_;
}
References v8::internal::IsolateData::is_minor_marking_flag_, isolate(), and v8::internal::Isolate::isolate_data().
IsNewSpaceAllowedToGrowAboveTargetCapacity()
bool v8::internal::Heap::IsNewSpaceAllowedToGrowAboveTargetCapacity () const
Definition at line 5573 of file heap.cc.
                                                            {
  return always_allocate() || gc_state() == TEAR_DOWN ||
         incremental_marking()->IsMarking();
}
References always_allocate(), gc_state(), incremental_marking(), v8::internal::IncrementalMarking::IsMarking(), and TEAR_DOWN.
isolate()
Isolate * v8::internal::Heap::isolate () const [inline]
Definition at line 61 of file heap-inl.h.
{ return Isolate::FromHeap(this); }
References v8::internal::Isolate::FromHeap().
Referenced by ActivateMemoryReducerIfNeededOnMainThread(), v8::internal::V8HeapExplorer::AddEntry(), v8::internal::MarkCompactCollector::AddEvacuationCandidate(), AddGCEpilogueCallback(), AddGCPrologueCallback(), AddRetainedMaps(), v8::internal::Heap::ExternalStringTable::AddString(), Allocate(), AllocateExternalBackingStore(), AllocateMap(), AllocatePartialMap(), v8::internal::HeapAllocator::AllocateRaw(), v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(), v8::internal::Heap::AllocationTrackerForDebugging::AllocationEvent(), AttachCppHeap(), v8::internal::CollectionBarrier::AwaitCollectionBackground(), v8::internal::EvacuateVisitorBase::cage_base(), CallGCEpilogueCallbacks(), CallGCPrologueCallbacks(), v8::internal::MinorGCJob::CancelTaskIfScheduled(), CanMoveObjectStart(), CanReferenceHeapObject(), CanShortcutStringsDuringGC(), CheckMemoryPressure(), v8::internal::Heap::ExternalStringTable::CleanUpAll(), v8::internal::Heap::ExternalStringTable::CleanUpYoung(), v8::internal::HeapProfiler::ClearHeapObjectMap(), ClearKeptObjects(), v8::internal::MinorMarkSweepCollector::ClearNonLiveReferences(), v8::internal::anonymous_namespace{heap.cc}::ClearStubCaches(), v8::internal::LocalHandleScope::CloseMainThreadScope(), CollectAllAvailableGarbage(), CollectCodeStatistics(), v8::internal::MarkCompactCollector::CollectEvacuationCandidates(), v8::internal::MinorMarkSweepCollector::CollectGarbage(), CollectGarbage(), CollectGarbageFromAnyThread(), CollectGarbageShared(), v8::internal::V8HeapExplorer::CollectTemporaryGlobalObjectsTags(), CompactWeakArrayLists(), ComputeMutatorUtilization(), v8::internal::ConcurrentUnifiedHeapMarkingVisitor::ConcurrentUnifiedHeapMarkingVisitor(), v8::internal::ConservativePinningScope::ConservativePinningScope(), CreateEarlyReadOnlyMapsAndObjects(), CreateImportantReadOnlyObjects(), CreateInitialMutableObjects(), CreateInternalAccessorInfoObjects(), CreateLateReadOnlyJSReceiverMaps(), CreateMutableApiObjects(), CreateReadOnlyApiObjects(), CreateReadOnlyHeapObjects(), CreateReadOnlyObjects(), DeactivateMajorGCInProgressFlag(), v8::internal::ArrayBufferSweeper::DecrementExternalMemoryCounters(), DequeueDirtyJSFinalizationRegistry(), v8::internal::MinorMarkSweepCollector::DrainMarkingWorklist(), DumpJSONHeapStatistics(), EnqueueDirtyJSFinalizationRegistry(), v8::internal::ReadOnlySpace::EnsurePage(), v8::internal::LocalHeap::EnsurePersistentHandles(), v8::internal::MinorMarkSweepCollector::EvacuateExternalPointerReferences(), v8::internal::EvacuateVisitorBase::EvacuateVisitorBase(), v8::internal::EvacuationAllocator::EvacuationAllocator(), FatalProcessOutOfMemory(), FinalizeExternalString(), FinalizePartialMap(), FindAllNativeContexts(), FindAllRetainedMaps(), v8::internal::MarkCompactCollector::Finish(), v8::internal::Sweeper::FinishMajorJobs(), v8::internal::Sweeper::FinishMinorJobs(), FreeLinearAllocationAreas(), GarbageCollectionEpilogueInSafepoint(), GcSafeInstructionStreamContains(), GcSafeMapOfHeapObject(), GcSafeTryFindCodeForInnerPointer(), v8::internal::HeapSnapshotGenerator::GenerateSnapshot(), v8::internal::HeapSnapshotGenerator::GenerateSnapshotAfterGC(), GetForegroundTaskRunner(), v8::internal::V8HeapExplorer::GetLocationFunction(), v8::internal::LocalHandleScope::GetMainThreadHandle(), HasDirtyJSFinalizationRegistries(), v8::internal::HeapAllocator::heap_for_allocation(), IncrementalMarkingLimitReached(), v8::internal::ArrayBufferSweeper::IncrementExternalMemoryCounters(), v8::internal::WriteBarrier::IndirectPointerMarkingFromCode(), InitializeHashSeed(), v8::internal::anonymous_namespace{heap.cc}::InvokeExternalCallbacks(), InvokeNearHeapLimitCallback(), v8::internal::V8HeapExplorer::IsEssentialObject(), IsMainThread(), IsMarkingFlagAddress(), IsMinorMarkingFlagAddress(), v8::internal::ObjectStatsCollectorImpl::isolate(), v8::internal::ObjectStats::isolate(), v8::internal::IncrementalMarking::isolate(), v8::internal::MarkingBarrier::isolate(), v8::internal::IsolateSafepoint::isolate(), v8::internal::HeapProfiler::isolate(), v8::internal::MarkCompactCollector::IsUnmarkedSharedHeapObject(), v8::internal::V8HeapExplorer::IterateAndExtractReferences(), IterateBuiltins(), IterateConservativeStackRoots(), IterateRootsForPrecisePinning(), IterateRootsIncludingClients(), IterateSmiRoots(), IterateWeakRoots(), KeepDuringJob(), LeftTrimFixedArray(), v8::internal::LocalHeap::LocalHeap(), v8::internal::V8HeapExplorer::MakeGlobalObjectTagMap(), MakeLinearAllocationAreasIterable(), v8::internal::WriteBarrier::MarkingFromCode(), v8::internal::WriteBarrier::MarkingSlow(), v8::internal::WriteBarrier::MarkingSlowFromCppHeapWrappable(), v8::internal::MarkCompactCollector::MarkObjectsFromClientHeaps(), v8::internal::MarkingBarrier::MarkRange(), v8::internal::MarkCompactCollector::MarkRoots(), v8::internal::MinorMarkSweepCollector::MarkRoots(), v8::internal::MarkCompactCollector::MarkRootsFromConservativeStack(), v8::internal::MinorMarkSweepCollector::MarkRootsFromConservativeStack(), v8::internal::MinorMarkSweepCollector::MarkRootsFromTracedHandles(), MeasureMemory(), MemoryPressureNotification(), v8::internal::PretenuringHandler::MergeAllocationSitePretenuringFeedback(), v8::internal::ProfilingMigrationObserver::Move(), MustBeInSharedOldSpace(), NewSpaceAllocationLimitAddress(), NewSpaceAllocationTopAddress(), v8::internal::StressScavengeObserver::NextLimit(), NextStressMarkingLimit(), NotifyContextDisposed(), v8::internal::GCTracer::NotifyFullSweepingCompletedAndStopCycleIfFinished(), v8::internal::MemoryReducer::NotifyMarkCompact(), v8::internal::GCTracer::NotifyMarkingStart(), NotifyObjectLayoutChange(), NotifyOldGenerationExpansion(), v8::internal::MemoryReducer::NotifyTimer(), NumberOfNativeContexts(), v8::internal::IncrementalMarking::OldGenerationSizeOfObjects(), v8::internal::LocalHandleScope::OpenMainThreadScope(), PauseConcurrentThreadsInClients(), PerformGarbageCollection(), PerformHeapVerification(), v8::internal::MemoryBalancer::PostHeartbeatTask(), v8::internal::GCTracer::Print(), v8::internal::GCTracer::PrintNVP(), ProcessDirtyJSFinalizationRegistries(), v8::internal::PretenuringHandler::ProcessPretenuringFeedback(), v8::internal::GCTracer::RecordGCPhasesHistograms(), v8::internal::MarkCompactCollector::RecordSlot(), v8::internal::FieldStatsCollector::RecordStats(), v8::internal::ObjectStatsCollectorImpl::RecordVirtualFeedbackVectorDetails(), v8::internal::PagedSpaceAllocatorPolicy::RefillLab(), v8::internal::MemoryBalancer::RefreshLimit(), RegisterStrongRoots(), RemoveDirtyFinalizationRegistriesOnContext(), v8::internal::CodeLargeObjectSpace::RemovePage(), v8::internal::GCTracer::ReportFullCycleToRecorder(), v8::internal::GCTracer::ReportIncrementalMarkingStepToRecorder(), v8::internal::GCTracer::ReportIncrementalSweepingStepToRecorder(), ReportStatisticsAfterGC(), v8::internal::GCTracer::ReportYoungCycleToRecorder(), v8::internal::StressScavengeObserver::RequestedGCDone(), v8::internal::MinorMarkSweepCollector::RequestGC(), ResumeConcurrentThreadsInClients(), roots_table(), v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::Run(), v8::internal::Sweeper::MajorSweeperJob::Run(), v8::internal::Sweeper::MinorSweeperJob::Run(), v8::internal::ConcurrentMarking::JobTaskMajor::Run(), v8::internal::ConcurrentMarking::JobTaskMinor::Run(), v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::Run(), v8::internal::Sweeper::MajorSweeperJob::RunImpl(), v8::internal::Sweeper::MinorSweeperJob::RunImpl(), v8::internal::BackgroundCollectionInterruptTask::RunInternal(), v8::internal::FinalizationRegistryCleanupTask::RunInternal(), v8::internal::IncrementalMarkingJob::Task::RunInternal(), v8::internal::ConcurrentMarking::RunMajor(), v8::internal::ConcurrentMarking::RunMinor(), v8::internal::ConcurrentMarking::RunMinorImpl(), v8::internal::Scavenger::ScavengePage(), v8::internal::IncrementalMarkingJob::ScheduleTask(), SetFunctionsMarkedForManualOptimization(), SetIsMarkingFlag(), SetIsMinorMarkingFlag(), SetOldGenerationAndGlobalAllocationLimit(), SetSerializedGlobalProxySizes(), SetSerializedObjects(), v8::internal::HeapAllocator::Setup(), SetUp(), v8::internal::LocalHeap::SetUpSharedMarking(), SetUpSpaces(), v8::internal::WriteBarrier::SharedMarkingFromCode(), ShouldOptimizeForBattery(), ShouldOptimizeForMemoryUsage(), ShouldUseBackgroundThreads(), ShouldUseIncrementalMarking(), v8::internal::FinalizationRegistryCleanupTask::SlowAssertNoActiveJavaScript(), v8::internal::MarkCompactCollector::StartCompaction(), v8::internal::GCTracer::StartCycle(), v8::internal::HeapProfiler::StartHeapObjectsTracking(), StartIncrementalMarking(), StartIncrementalMarkingIfAllocationLimitIsReached(), v8::internal::MarkCompactCollector::StartMarking(), v8::internal::MinorMarkSweepCollector::StartSweepNewSpace(), v8::internal::MinorMarkSweepCollector::StartSweepNewSpaceWithStickyBits(), v8::internal::StressScavengeObserver::Step(), v8::internal::StressConcurrentAllocationObserver::Step(), v8::internal::GCTracer::StopCycle(), v8::internal::GCTracer::StopObservablePause(), v8::internal::IncrementalMarking::StopPointerTableBlackAllocation(), v8::internal::CollectionBarrier::StopTimeToCollectionTimer(), v8::internal::StressScavengeObserver::StressScavengeObserver(), v8::internal::HeapProfiler::TakeSnapshot(), TearDown(), v8::internal::MinorMarkSweepCollector::TraceFragmentation(), v8::internal::UnreachableObjectsFilter::MarkingVisitor::TransitiveClosure(), TryFindCodeForInnerPointerForPrinting(), v8::internal::HeapAllocator::TryResizeLargeObject(), v8::internal::MinorGCJob::TryScheduleTask(), Unmark(), UnregisterStrongRoots(), v8::internal::HeapObjectsMap::UpdateHeapObjectsMap(), v8::internal::EvacuateOldSpaceVisitor::Visit(), v8::internal::InternalizedStringTableCleaner::VisitRootPointers(), v8::internal::RootsReferencesExtractor::VisitRootPointers(), WeakenDescriptorArrays(), v8::internal::LocalHeap::~LocalHeap(), and v8::internal::SemiSpace::~SemiSpace().
IsOldGenerationExpansionAllowed()
bool v8::internal::Heap::IsOldGenerationExpansionAllowed (size_t size, const base::MutexGuard & expansion_mutex_witness) const
Definition at line 421 of file heap.cc.
                                                                      {
  return OldGenerationCapacity() + size <= max_old_generation_size();
}
References max_old_generation_size(), OldGenerationCapacity(), and size().
IsPendingAllocation() [1/2]
bool v8::internal::Heap::IsPendingAllocation (Tagged< HeapObject > object) [inline]
Definition at line 348 of file heap-inl.h.
                                                        {
  bool result = IsPendingAllocationInternal(object);
  if (v8_flags.trace_pending_allocations && result) {
    StdoutStream{} << "Pending allocation: " << std::hex << "0x" << object.ptr()
                   << "\n";
  }
  return result;
}
References IsPendingAllocationInternal(), v8::base::internal::result, and v8::internal::v8_flags.
Referenced by IsPendingAllocation(), v8::internal::compiler::JSHeapBroker::ObjectMayBeUninitialized(), v8::internal::GlobalDictionary::TryFindPropertyCellForConcurrentLookupIterator(), and v8::internal::SwissNameDictionary::TryValueAt().
IsPendingAllocation() [2/2]
bool v8::internal::Heap::IsPendingAllocation (Tagged< Object > object) [inline]
Definition at line 357 of file heap-inl.h.
                                                    {
  return IsHeapObject(object) && IsPendingAllocation(Cast<HeapObject>(object));
}
References v8::internal::IsHeapObject(), and IsPendingAllocation().
IsPendingAllocationInternal()
bool v8::internal::Heap::IsPendingAllocationInternal (Tagged< HeapObject > object) [inline], [private]
Definition at line 297 of file heap-inl.h.
                                                                {
  DCHECK(deserialization_complete());
  MemoryChunk* chunk = MemoryChunk::FromHeapObject(object);
  if (chunk->InReadOnlySpace()) return false;
  BaseSpace* base_space = chunk->Metadata()->owner();
  Address addr = object.address();
  switch (base_space->identity()) {
    case NEW_SPACE: {
      return allocator()->new_space_allocator()->IsPendingAllocation(addr);
    }
    case OLD_SPACE: {
      return allocator()->old_space_allocator()->IsPendingAllocation(addr);
    }
    case CODE_SPACE: {
      return allocator()->code_space_allocator()->IsPendingAllocation(addr);
    }
    case TRUSTED_SPACE: {
      return allocator()->trusted_space_allocator()->IsPendingAllocation(addr);
    }
    case LO_SPACE:
    case CODE_LO_SPACE:
    case TRUSTED_LO_SPACE:
    case NEW_LO_SPACE: {
      LargeObjectSpace* large_space =
          static_cast<LargeObjectSpace*>(base_space);
      base::MutexGuard guard(large_space->pending_allocation_mutex());
      return addr == large_space->pending_object();
    }
    case SHARED_SPACE:
    case SHARED_LO_SPACE:
    case SHARED_TRUSTED_SPACE:
    case SHARED_TRUSTED_LO_SPACE:
      // TODO(v8:13267): Ensure that all shared space objects have a memory
      // barrier after initialization.
      return false;
    case RO_SPACE:
      UNREACHABLE();
  }
  UNREACHABLE();
}
References allocator(), v8::internal::CODE_LO_SPACE, v8::internal::CODE_SPACE, v8::internal::HeapAllocator::code_space_allocator(), v8::internal::DCHECK(), deserialization_complete(), v8::internal::MemoryChunk::FromHeapObject(), v8::internal::BaseSpace::identity(), v8::internal::MemoryChunk::InReadOnlySpace(), v8::internal::MainAllocator::IsPendingAllocation(), v8::internal::LO_SPACE, v8::internal::MemoryChunk::Metadata(), v8::internal::NEW_LO_SPACE, v8::internal::NEW_SPACE, v8::internal::HeapAllocator::new_space_allocator(), v8::internal::OLD_SPACE, v8::internal::HeapAllocator::old_space_allocator(), v8::internal::MemoryChunkMetadata::owner(), v8::internal::LargeObjectSpace::pending_allocation_mutex(), v8::internal::LargeObjectSpace::pending_object(), v8::internal::RO_SPACE, v8::internal::SHARED_LO_SPACE, v8::internal::SHARED_SPACE, v8::internal::SHARED_TRUSTED_LO_SPACE, v8::internal::SHARED_TRUSTED_SPACE, v8::internal::TRUSTED_LO_SPACE, v8::internal::TRUSTED_SPACE, v8::internal::HeapAllocator::trusted_space_allocator(), and v8::internal::UNREACHABLE().
Referenced by IsPendingAllocation().
IsRegularObjectAllocation()
static bool v8::internal::Heap::IsRegularObjectAllocation (AllocationType allocation) [inline], [static], [private]
Definition at line 1776 of file heap.h.
                                                                   {
    return AllocationType::kYoung == allocation ||
           AllocationType::kOld == allocation;
  }
IsStressingScavenge()
bool v8::internal::Heap::IsStressingScavenge () [private]
Definition at line 7385 of file heap.cc.
                               {
  return v8_flags.stress_scavenge > 0 && new_space();
}
References new_space(), and v8::internal::v8_flags.
Referenced by HandleGCRequest(), SetUpSpaces(), and TearDown().
IsTearingDown()
bool v8::internal::Heap::IsTearingDown () const [inline]
Definition at line 568 of file heap.h.
{ return gc_state() == TEAR_DOWN; }
Referenced by v8::internal::GlobalHandles::PostGarbageCollectionProcessing(), v8::internal::ArrayBufferSweeper::RequestSweep(), v8::internal::ConcurrentMarking::RescheduleJobIfNeeded(), v8::internal::IncrementalMarkingJob::ScheduleTask(), v8::internal::IncrementalMarking::StartMarkingMajor(), v8::internal::IncrementalMarking::StartMarkingMinor(), StartMinorMSConcurrentMarkingIfNeeded(), v8::internal::ConcurrentMarking::TryScheduleJob(), and v8::internal::MinorGCJob::TryScheduleTask().
IsValidAllocationSpace()
bool v8::internal::Heap::IsValidAllocationSpace (AllocationSpace space) [static]
Definition at line 4622 of file heap.cc.
                                                       {
  switch (space) {
    case NEW_SPACE:
    case OLD_SPACE:
    case CODE_SPACE:
    case SHARED_SPACE:
    case LO_SPACE:
    case NEW_LO_SPACE:
    case CODE_LO_SPACE:
    case SHARED_LO_SPACE:
    case TRUSTED_SPACE:
    case SHARED_TRUSTED_SPACE:
    case TRUSTED_LO_SPACE:
    case SHARED_TRUSTED_LO_SPACE:
    case RO_SPACE:
      return true;
    default:
      return false;
  }
}
References v8::internal::CODE_LO_SPACE, v8::internal::CODE_SPACE, v8::internal::LO_SPACE, v8::internal::NEW_LO_SPACE, v8::internal::NEW_SPACE, v8::internal::OLD_SPACE, v8::internal::RO_SPACE, v8::internal::SHARED_LO_SPACE, v8::internal::SHARED_SPACE, v8::internal::SHARED_TRUSTED_LO_SPACE, v8::internal::SHARED_TRUSTED_SPACE, space(), v8::internal::TRUSTED_LO_SPACE, and v8::internal::TRUSTED_SPACE.
Referenced by v8::Isolate::GetHeapSpaceStatistics().
IsYoungGenerationCollector()
static bool v8::internal::Heap::IsYoungGenerationCollector (GarbageCollector collector) [inline], [static]
Definition at line 361 of file heap.h.
                                                                            {
    return collector == GarbageCollector::SCAVENGER ||
           collector == GarbageCollector::MINOR_MARK_SWEEPER;
  }
Referenced by CollectGarbage(), GarbageCollectionEpilogueInSafepoint(), v8::internal::SamplingHeapProfiler::OnWeakCallback(), PerformGarbageCollection(), RecomputeLimits(), v8::internal::GCTracer::RecordGCPhasesInfo::RecordGCPhasesInfo(), v8::internal::GCTracer::StartCycle(), StartIncrementalMarking(), v8::internal::GCTracer::StopCycle(), and v8::internal::GCTracer::StopObservablePause().
IterateBuiltins()
void v8::internal::Heap::IterateBuiltins (RootVisitor * v)
Definition at line 4967 of file heap.cc.
                                         {
  Builtins* builtins = isolate()->builtins();
  for (Builtin builtin = Builtins::kFirst; builtin <= Builtins::kLast;
       ++builtin) {
    const char* name = Builtins::name(builtin);
    v->VisitRootPointer(Root::kBuiltins, name, builtins->builtin_slot(builtin));
  }
  for (Builtin builtin = Builtins::kFirst; builtin <= Builtins::kLastTier0;
       ++builtin) {
    v->VisitRootPointer(Root::kBuiltins, Builtins::name(builtin),
                        builtins->builtin_tier0_slot(builtin));
  }
  // The entry table doesn't need to be updated since all builtins are embedded.
  static_assert(Builtins::AllBuiltinsAreIsolateIndependent());
}
References v8::internal::Builtins::AllBuiltinsAreIsolateIndependent(), v8::internal::Builtins::builtin_slot(), v8::internal::Builtins::builtin_tier0_slot(), v8::internal::Isolate::builtins(), isolate(), v8::internal::Builtins::kFirst, v8::internal::Builtins::kLast, v8::internal::Builtins::kLastTier0, v8::internal::Builtins::name(), v8::internal::name, and v8::internal::RootVisitor::VisitRootPointer().
Referenced by IterateRoots().
IterateConservativeStackRoots() [1/2]
void v8::internal::Heap::IterateConservativeStackRoots (::heap::base::StackVisitor * stack_visitor, StackScanMode stack_scan_mode)
Definition at line 5005 of file heap.cc.
                                                                        {
  DCHECK(IsGCWithStack());
  DCHECK_NE(stack_scan_mode, StackScanMode::kNone);
  if (stack_scan_mode == StackScanMode::kSelective) {
    DCHECK(IsGCWithMainThreadStack());
    DCHECK(selective_stack_scan_start_address_.has_value());
    stack().IteratePointersFromAddressUntilMarker(
        stack_visitor, selective_stack_scan_start_address_.value());
    return;
  }
  DCHECK_EQ(stack_scan_mode, StackScanMode::kFull);
  if (IsGCWithMainThreadStack()) {
    stack().IteratePointersUntilMarker(stack_visitor);
  }
  stack().IterateBackgroundStacks(stack_visitor);
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, IsGCWithMainThreadStack(), IsGCWithStack(), heap::base::Stack::IterateBackgroundStacks(), heap::base::Stack::IteratePointersFromAddressUntilMarker(), heap::base::Stack::IteratePointersUntilMarker(), kFull, kNone, kSelective, selective_stack_scan_start_address_, and stack().
IterateConservativeStackRoots() [2/2]
void v8::internal::Heap::IterateConservativeStackRoots (RootVisitor * root_visitor, IterateRootsMode roots_mode = IterateRootsMode::kMainIsolate)
Definition at line 4987 of file heap.cc.
                                                                      {
  const StackScanMode stack_scan_mode =
      ConservativeStackScanningModeForMajorGC();
  DCHECK_IMPLIES(stack_scan_mode == Heap::StackScanMode::kSelective,
                 IsGCWithStack());
  if ((stack_scan_mode == StackScanMode::kNone) || !IsGCWithStack()) return;
  // In case of a shared GC, we're interested in the main isolate for CSS.
  Isolate* main_isolate = roots_mode == IterateRootsMode::kClientIsolate
                              ? isolate()->shared_space_isolate()
                              : isolate();
  ConservativeStackVisitor stack_visitor(main_isolate, root_visitor);
  IterateConservativeStackRoots(&stack_visitor, stack_scan_mode);
}
References ConservativeStackScanningModeForMajorGC(), DCHECK_IMPLIES, IsGCWithStack(), isolate(), kClientIsolate, kNone, kSelective, and v8::internal::Isolate::shared_space_isolate().
Referenced by v8::internal::ScavengerCollector::CollectGarbage(), IterateRoots(), v8::internal::MarkCompactCollector::MarkRootsFromConservativeStack(), and v8::internal::MinorMarkSweepCollector::MarkRootsFromConservativeStack().
IterateRoots()
void v8::internal::Heap::IterateRoots (RootVisitor * v, base::EnumSet< SkipRoot > options, IterateRootsMode roots_mode = IterateRootsMode::kMainIsolate)
Definition at line 4808 of file heap.cc.
                                                     {
  v->VisitRootPointers(Root::kStrongRootList, nullptr,
                       roots_table().strong_roots_begin(),
                       roots_table().strong_roots_end());
  v->Synchronize(VisitorSynchronization::kStrongRootList);
  isolate_->bootstrapper()->Iterate(v);
  v->Synchronize(VisitorSynchronization::kBootstrapper);
  Relocatable::Iterate(isolate_, v);
  v->Synchronize(VisitorSynchronization::kRelocatable);
  isolate_->debug()->Iterate(v);
  v->Synchronize(VisitorSynchronization::kDebug);
  isolate_->compilation_cache()->Iterate(v);
  v->Synchronize(VisitorSynchronization::kCompilationCache);
  const bool skip_iterate_builtins =
      options.contains(SkipRoot::kOldGeneration) ||
      (Builtins::kCodeObjectsAreInROSpace &&
       options.contains(SkipRoot::kReadOnlyBuiltins) &&
       // Prior to ReadOnlyPromotion, builtins may be on the mutable heap.
       !isolate_->serializer_enabled());
  if (!skip_iterate_builtins) {
    IterateBuiltins(v);
    v->Synchronize(VisitorSynchronization::kBuiltins);
  }
  // Iterate over pointers being held by inactive threads.
  isolate_->thread_manager()->Iterate(v);
  v->Synchronize(VisitorSynchronization::kThreadManager);
  // Visitors in this block only run when not serializing. These include:
  //
  // - Thread-local and stack.
  // - Handles.
  // - Microtasks.
  // - The startup object cache.
  //
  // When creating real startup snapshot, these areas are expected to be empty.
  // It is also possible to create a snapshot of a *running* isolate for testing
  // purposes. In this case, these areas are likely not empty and will simply be
  // skipped.
  //
  // The general guideline for adding visitors to this section vs. adding them
  // above is that non-transient heap state is always visited, transient heap
  // state is visited only when not serializing.
  if (!options.contains(SkipRoot::kUnserializable)) {
    if (!options.contains(SkipRoot::kTracedHandles)) {
      // Young GCs always skip traced handles and visit them manually.
      DCHECK(!options.contains(SkipRoot::kOldGeneration));
      isolate_->traced_handles()->Iterate(v);
    }
    if (!options.contains(SkipRoot::kGlobalHandles)) {
      // Young GCs always skip global handles and visit them manually.
      DCHECK(!options.contains(SkipRoot::kOldGeneration));
      if (options.contains(SkipRoot::kWeak)) {
        isolate_->global_handles()->IterateStrongRoots(v);
      } else {
        isolate_->global_handles()->IterateAllRoots(v);
      }
    }
    v->Synchronize(VisitorSynchronization::kGlobalHandles);
    if (!options.contains(SkipRoot::kStack)) {
      ClearStaleLeftTrimmedPointerVisitor left_trim_visitor(this, v);
      IterateStackRoots(&left_trim_visitor);
      if (!options.contains(SkipRoot::kConservativeStack)) {
        IterateConservativeStackRoots(v, roots_mode);
      }
      v->Synchronize(VisitorSynchronization::kStackRoots);
    }
    // Iterate over main thread handles in handle scopes.
    if (!options.contains(SkipRoot::kMainThreadHandles)) {
      // Clear main thread handles with stale references to left-trimmed
      // objects. The GC would crash on such stale references.
      ClearStaleLeftTrimmedPointerVisitor left_trim_visitor(this, v);
      isolate_->handle_scope_implementer()->Iterate(&left_trim_visitor);
    }
    // Iterate local handles for all local heaps.
    safepoint_->Iterate(v);
    // Iterates all persistent handles.
    isolate_->persistent_handles_list()->Iterate(v, isolate_);
    v->Synchronize(VisitorSynchronization::kHandleScope);
    if (options.contains(SkipRoot::kOldGeneration)) {
      isolate_->eternal_handles()->IterateYoungRoots(v);
    } else {
      isolate_->eternal_handles()->IterateAllRoots(v);
    }
    v->Synchronize(VisitorSynchronization::kEternalHandles);
    // Iterate over pending Microtasks stored in MicrotaskQueues.
    MicrotaskQueue* default_microtask_queue =
        isolate_->default_microtask_queue();
    if (default_microtask_queue) {
      MicrotaskQueue* microtask_queue = default_microtask_queue;
      do {
        microtask_queue->IterateMicrotasks(v);
        microtask_queue = microtask_queue->next();
      } while (microtask_queue != default_microtask_queue);
    }
    v->Synchronize(VisitorSynchronization::kMicroTasks);
    // Iterate over other strong roots (currently only identity maps and
    // deoptimization entries).
    for (StrongRootsEntry* current = strong_roots_head_; current;
         current = current->next) {
      v->VisitRootPointers(Root::kStrongRoots, current->label, current->start,
                           current->end);
    }
    v->Synchronize(VisitorSynchronization::kStrongRoots);
    // Iterate over the startup and shared heap object caches unless
    // serializing or deserializing.
    SerializerDeserializer::IterateStartupObjectCache(isolate_, v);
    v->Synchronize(VisitorSynchronization::kStartupObjectCache);
    // Iterate over shared heap object cache when the isolate owns this data
    // structure. Isolates which own the shared heap object cache are:
    // * All isolates when not using --shared-string-table.
    // * Shared space/main isolate with --shared-string-table.
    //
    // Isolates which do not own the shared heap object cache should not iterate
    // it.
    if (isolate_->OwnsStringTables()) {
      SerializerDeserializer::IterateSharedHeapObjectCache(isolate_, v);
      v->Synchronize(VisitorSynchronization::kSharedHeapObjectCache);
    }
  }
  if (!options.contains(SkipRoot::kWeak)) {
    IterateWeakRoots(v, options);
  }
}
References v8::internal::Isolate::bootstrapper(), v8::internal::Isolate::compilation_cache(), v8::base::EnumSet< E, T >::contains(), v8::internal::DCHECK(), v8::internal::Isolate::debug(), v8::internal::Isolate::eternal_handles(), v8::internal::Isolate::global_handles(), v8::internal::Isolate::handle_scope_implementer(), isolate_, v8::internal::HandleScopeImplementer::Iterate(), v8::internal::Relocatable::Iterate(), v8::internal::TracedHandles::Iterate(), v8::internal::CompilationCache::Iterate(), v8::internal::Debug::Iterate(), v8::internal::ThreadManager::Iterate(), v8::internal::Bootstrapper::Iterate(), v8::internal::PersistentHandlesList::Iterate(), v8::internal::GlobalHandles::IterateAllRoots(), v8::internal::EternalHandles::IterateAllRoots(), IterateBuiltins(), IterateConservativeStackRoots(), v8::internal::MicrotaskQueue::IterateMicrotasks(), v8::internal::SerializerDeserializer::IterateSharedHeapObjectCache(), IterateStackRoots(), v8::internal::SerializerDeserializer::IterateStartupObjectCache(), v8::internal::GlobalHandles::IterateStrongRoots(), IterateWeakRoots(), v8::internal::EternalHandles::IterateYoungRoots(), v8::internal::Builtins::kCodeObjectsAreInROSpace, v8::internal::kConservativeStack, v8::internal::kGlobalHandles, v8::internal::kMainThreadHandles, v8::internal::kOldGeneration, v8::internal::kReadOnlyBuiltins, v8::internal::kStack, v8::internal::kTracedHandles, v8::internal::kUnserializable, v8::internal::kWeak, v8::internal::MicrotaskQueue::next(), v8::internal::StrongRootsEntry::next, v8::internal::Isolate::OwnsStringTables(), v8::internal::Isolate::persistent_handles_list(), roots_table(), safepoint_, v8::internal::Isolate::serializer_enabled(), strong_roots_head_, v8::internal::RootVisitor::Synchronize(), v8::internal::Isolate::thread_manager(), v8::internal::Isolate::traced_handles(), and v8::internal::RootVisitor::VisitRootPointers().
Referenced by v8::internal::ScavengerCollector::CollectGarbage(), v8::internal::StartupDeserializer::DeserializeIntoIsolate(), v8::internal::V8HeapExplorer::IterateAndExtractReferences(), IterateRootsIncludingClients(), LeftTrimFixedArray(), v8::internal::UnreachableObjectsFilter::MarkReachableObjects(), v8::internal::IncrementalMarking::MarkRoots(), v8::internal::MarkCompactCollector::MarkRoots(), v8::internal::MinorMarkSweepCollector::MarkRoots(), and v8::internal::StartupSerializer::SerializeStrongReferences().
IterateRootsForPrecisePinning()
void v8::internal::Heap::IterateRootsForPrecisePinning (RootVisitor * visitor)
Definition at line 5025 of file heap.cc.
                                                             {
  IterateStackRoots(visitor);
  isolate()->handle_scope_implementer()->Iterate(visitor);
}
References v8::internal::Isolate::handle_scope_implementer(), isolate(), v8::internal::HandleScopeImplementer::Iterate(), and IterateStackRoots().
Referenced by v8::internal::ScavengerCollector::CollectGarbage().
IterateRootsIncludingClients()
void v8::internal::Heap::IterateRootsIncludingClients (RootVisitor * v, base::EnumSet< SkipRoot > options)
Definition at line 4948 of file heap.cc.
                                                                       {
  IterateRoots(v, options, IterateRootsMode::kMainIsolate);
  if (isolate()->is_shared_space_isolate()) {
    ClientRootVisitor<> client_root_visitor(v);
    isolate()->global_safepoint()->IterateClientIsolates(
        [v = &client_root_visitor, options](Isolate* client) {
          client->heap()->IterateRoots(v, options,
                                       IterateRootsMode::kClientIsolate);
        });
  }
}
References v8::internal::Isolate::global_safepoint(), v8::internal::Isolate::heap(), isolate(), v8::internal::GlobalSafepoint::IterateClientIsolates(), IterateRoots(), kClientIsolate, and kMainIsolate.
IterateSmiRoots()
void v8::internal::Heap::IterateSmiRoots (RootVisitor * v)
Definition at line 4722 of file heap.cc.
                                         {
  // Acquire execution access since we are going to read stack limit values.
  ExecutionAccess access(isolate());
  v->VisitRootPointers(Root::kSmiRootList, nullptr,
                       roots_table().smi_roots_begin(),
                       roots_table().smi_roots_end());
  v->Synchronize(VisitorSynchronization::kSmiRootList);
}
References isolate(), roots_table(), v8::internal::RootVisitor::Synchronize(), and v8::internal::RootVisitor::VisitRootPointers().
Referenced by v8::internal::StartupDeserializer::DeserializeIntoIsolate(), and v8::internal::StartupSerializer::SerializeStrongReferences().
IterateStackRoots()
void v8::internal::Heap::IterateStackRoots (RootVisitor * v)
Definition at line 4985 of file heap.cc.
{ isolate_->Iterate(v); }
References isolate_, and v8::internal::Isolate::Iterate().
Referenced by IterateRoots(), and IterateRootsForPrecisePinning().
IterateWeakGlobalHandles()
void v8::internal::Heap::IterateWeakGlobalHandles (RootVisitor * v)
Definition at line 4962 of file heap.cc.
                                                  {
  isolate_->global_handles()->IterateWeakRoots(v);
  isolate_->traced_handles()->Iterate(v);
}
References v8::internal::Isolate::global_handles(), isolate_, v8::internal::TracedHandles::Iterate(), v8::internal::GlobalHandles::IterateWeakRoots(), and v8::internal::Isolate::traced_handles().
Referenced by v8::internal::V8HeapExplorer::IterateAndExtractReferences().
IterateWeakRoots()
void v8::internal::Heap::IterateWeakRoots (RootVisitor * v, base::EnumSet< SkipRoot > options)
Definition at line 4683 of file heap.cc.
                                                                         {
  DCHECK(!options.contains(SkipRoot::kWeak));
  if (!options.contains(SkipRoot::kUnserializable)) {
    // Isolate::topmost_script_having_context_address is treated weakly.
    v->VisitRootPointer(
        Root::kWeakRoots, nullptr,
        FullObjectSlot(isolate()->topmost_script_having_context_address()));
  }
  if (!options.contains(SkipRoot::kOldGeneration) &&
      !options.contains(SkipRoot::kUnserializable) &&
      isolate()->OwnsStringTables()) {
    // Do not visit for the following reasons.
    // - Serialization, since the string table is custom serialized.
    // - If we are skipping old generation, since all internalized strings
    // are in old space.
    // - If the string table is shared and this is not the shared heap,
    // since all internalized strings are in the shared heap.
    isolate()->string_table()->IterateElements(v);
  }
  v->Synchronize(VisitorSynchronization::kStringTable);
  if (!options.contains(SkipRoot::kExternalStringTable) &&
      !options.contains(SkipRoot::kUnserializable)) {
    // Scavenge collections have special processing for this.
    // Do not visit for serialization, since the external string table will
    // be populated from scratch upon deserialization.
    external_string_table_.IterateAll(v);
  }
  v->Synchronize(VisitorSynchronization::kExternalStringsTable);
  if (!options.contains(SkipRoot::kOldGeneration) &&
      !options.contains(SkipRoot::kUnserializable) &&
      isolate()->is_shared_space_isolate() &&
      isolate()->shared_struct_type_registry()) {
    isolate()->shared_struct_type_registry()->IterateElements(isolate(), v);
  }
  v->Synchronize(VisitorSynchronization::kSharedStructTypeRegistry);
}
References v8::base::EnumSet< E, T >::contains(), v8::internal::DCHECK(), external_string_table_, isolate(), v8::internal::Heap::ExternalStringTable::IterateAll(), v8::internal::SharedStructTypeRegistry::IterateElements(), v8::internal::StringTable::IterateElements(), v8::internal::kExternalStringTable, v8::internal::kOldGeneration, v8::internal::kUnserializable, v8::internal::kWeak, v8::internal::Isolate::shared_struct_type_registry(), v8::internal::Isolate::string_table(), v8::internal::RootVisitor::Synchronize(), and v8::internal::RootVisitor::VisitRootPointer().
Referenced by v8::internal::StartupDeserializer::DeserializeIntoIsolate(), v8::internal::V8HeapExplorer::IterateAndExtractReferences(), IterateRoots(), and v8::internal::StartupSerializer::SerializeWeakReferencesAndDeferred().
KeepDuringJob()
void v8::internal::Heap::KeepDuringJob (DirectHandle< HeapObject > target)
Definition at line 7127 of file heap.cc.
                                                        {
  DCHECK(IsUndefined(weak_refs_keep_during_job()) ||
         IsOrderedHashSet(weak_refs_keep_during_job()));
  Handle<OrderedHashSet> table;
  if (IsUndefined(weak_refs_keep_during_job(), isolate())) {
    table = isolate()->factory()->NewOrderedHashSet();
  } else {
    table =
        handle(Cast<OrderedHashSet>(weak_refs_keep_during_job()), isolate());
  }
  MaybeHandle<OrderedHashSet> maybe_table =
      OrderedHashSet::Add(isolate(), table, target);
  if (!maybe_table.ToHandle(&table)) {
    FatalProcessOutOfMemory(
        "Fatal JavaScript error: Too many distinct WeakRef objects "
        "created or dereferenced during single event loop turn.");
  }
  set_weak_refs_keep_during_job(*table);
}
References v8::bigint::Add(), v8::internal::DCHECK(), v8::internal::Isolate::factory(), FatalProcessOutOfMemory(), v8::internal::handle(), isolate(), v8::internal::Factory::NewOrderedHashSet(), and v8::internal::MaybeHandle< T >::ToHandle().
LeftTrimFixedArray()
Tagged< FixedArrayBase > v8::internal::Heap::LeftTrimFixedArray (Tagged< FixedArrayBase > obj, int elements_to_trim)
Definition at line 3508 of file heap.cc.
                                                                      {
  if (elements_to_trim == 0) {
    // This simplifies reasoning in the rest of the function.
    return object;
  }
  CHECK(!object.is_null());
  DCHECK(CanMoveObjectStart(object));
  // Add custom visitor to concurrent marker if new left-trimmable type
  // is added.
  DCHECK(IsFixedArray(object) || IsFixedDoubleArray(object));
  const int element_size = IsFixedArray(object) ? kTaggedSize : kDoubleSize;
  const int bytes_to_trim = elements_to_trim * element_size;
  Tagged<Map> map = object->map();
  // For now this trick is only applied to fixed arrays which may be in new
  // space or old space. In a large object space the object's start must
  // coincide with chunk and thus the trick is just not applicable.
  DCHECK(!IsLargeObject(object));
  DCHECK(object->map() != ReadOnlyRoots(this).fixed_cow_array_map());
  static_assert(offsetof(FixedArrayBase, map_) == 0);
  static_assert(offsetof(FixedArrayBase, length_) == kTaggedSize);
  static_assert(sizeof(FixedArrayBase) == 2 * kTaggedSize);
  const int len = object->length();
  DCHECK(elements_to_trim <= len);
  // Calculate location of new array start.
  Address old_start = object.address();
  Address new_start = old_start + bytes_to_trim;
  // Technically in new space this write might be omitted (except for
  // debug mode which iterates through the heap), but to play safer
  // we still do it.
  CreateFillerObjectAtRaw(
      WritableFreeSpace::ForNonExecutableMemory(old_start, bytes_to_trim),
      ClearFreedMemoryMode::kClearFreedMemory,
      MayContainRecordedSlots(object) ? ClearRecordedSlots::kYes
                                      : ClearRecordedSlots::kNo,
      VerifyNoSlotsRecorded::kYes);
  // Initialize header of the trimmed array. Since left trimming is only
  // performed on pages which are not concurrently swept creating a filler
  // object does not require synchronization.
  RELAXED_WRITE_FIELD(object, bytes_to_trim,
                      Tagged<Object>(MapWord::FromMap(map).ptr()));
  RELAXED_WRITE_FIELD(object, bytes_to_trim + kTaggedSize,
                      Smi::FromInt(len - elements_to_trim));
  Tagged<FixedArrayBase> new_object =
      Cast<FixedArrayBase>(HeapObject::FromAddress(new_start));
  if (isolate()->log_object_relocation()) {
    // Notify the heap profiler of change in object layout.
    OnMoveEvent(object, new_object, new_object->Size());
  }
#ifdef ENABLE_SLOW_DCHECKS
  if (v8_flags.enable_slow_asserts) {
    // Make sure the stack or other roots (e.g., Handles) don't contain pointers
    // to the original FixedArray (which is now the filler object).
    std::optional<IsolateSafepointScope> safepoint_scope;
    {
      AllowGarbageCollection allow_gc;
      safepoint_scope.emplace(this);
    }
    LeftTrimmerVerifierRootVisitor root_visitor(object);
    ReadOnlyRoots(this).Iterate(&root_visitor);
    // Stale references are allowed in some locations. IterateRoots() uses
    // ClearStaleLeftTrimmedPointerVisitor internally to clear such references
    // beforehand.
    IterateRoots(&root_visitor,
                 base::EnumSet<SkipRoot>{SkipRoot::kConservativeStack});
  }
#endif // ENABLE_SLOW_DCHECKS
  return new_object;
}
References CanMoveObjectStart(), CHECK, CreateFillerObjectAtRaw(), v8::internal::DCHECK(), v8::internal::WritableFreeSpace::ForNonExecutableMemory(), v8::internal::HeapObject::FromAddress(), v8::internal::Smi::FromInt(), v8::internal::MapWord::FromMap(), IsLargeObject(), isolate(), IterateRoots(), v8::internal::kClearFreedMemory, v8::internal::kConservativeStack, v8::internal::kDoubleSize, v8::internal::kNo, v8::internal::kTaggedSize, v8::internal::kYes, kYes, v8::internal::anonymous_namespace{heap.cc}::MayContainRecordedSlots(), OnMoveEvent(), ReadOnlyRoots, RELAXED_WRITE_FIELD, and v8::internal::v8_flags.
Referenced by v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::RemoveElement().
lo_space()
OldLargeObjectSpace* v8::internal::Heap::lo_space () const [inline]
Definition at line 777 of file heap.h.
{ return lo_space_; }
Referenced by CollectAllAvailableGarbage(), DeactivateMajorGCInProgressFlag(), v8::internal::MarkCompactCollector::Finish(), GarbageCollectionEpilogueInSafepoint(), v8::internal::ScavengerCollector::HandleSurvivingNewLargeObjects(), v8::internal::OldGenerationMemoryChunkIterator::next(), OldGenerationSizeOfObjects(), v8::internal::IncrementalMarking::OldGenerationSizeOfObjects(), v8::internal::MinorMarkSweepCollector::SweepNewLargeSpace(), and Unmark().
main_thread_local_heap()
LocalHeap* v8::internal::Heap::main_thread_local_heap () [inline]
Definition at line 885 of file heap.h.
{ return main_thread_local_heap_; }
Referenced by v8::internal::IsolateSafepoint::AssertMainThreadIsOnlyThread(), v8::internal::HeapAllocator::CollectAllAvailableGarbage(), CollectGarbage(), CollectGarbageFromAnyThread(), v8::internal::WriteBarrier::CurrentMarkingBarrier(), FreeSharedLinearAllocationAreasAndResetFreeLists(), GarbageCollectionEpilogueInSafepoint(), HandleExternalMemoryInterrupt(), MarkSharedLinearAllocationAreasBlack(), v8::internal::GlobalSafepointInterruptTask::RunInternal(), v8::internal::ScheduleMinorGCTaskObserver::ScheduleMinorGCTaskObserver(), SetUp(), SetUpSpaces(), StartIncrementalMarkingOnInterrupt(), StartTearDown(), TearDownWithSharedHeap(), UnmarkSharedLinearAllocationAreas(), and v8::internal::ScheduleMinorGCTaskObserver::~ScheduleMinorGCTaskObserver().
major_sweeping_in_progress()
bool v8::internal::Heap::major_sweeping_in_progress () const [inline]
Definition at line 1598 of file heap.h.
                                          {
    return sweeper_->major_sweeping_in_progress();
  }
Referenced by EnsureSweepingCompleted(), FinishSweepingIfOutOfWork(), and PrintShortHeapStatistics().
MakeHeapIterable()
void v8::internal::Heap::MakeHeapIterable ()
Definition at line 3661 of file heap.cc.
                            {
  EnsureSweepingCompleted(SweepingForcedFinalizationMode::kV8Only);
  MakeLinearAllocationAreasIterable();
}
References EnsureSweepingCompleted(), kV8Only, and MakeLinearAllocationAreasIterable().
Referenced by CollectCodeStatistics(), and v8::internal::HeapObjectIterator::HeapObjectIterator().
MakeLinearAllocationAreasIterable()
void v8::internal::Heap::MakeLinearAllocationAreasIterable () [private]
Definition at line 3667 of file heap.cc.
                                             {
  allocator()->MakeLinearAllocationAreasIterable();
  safepoint()->IterateLocalHeaps([](LocalHeap* local_heap) {
    local_heap->MakeLinearAllocationAreasIterable();
  });
  if (isolate()->is_shared_space_isolate()) {
    isolate()->global_safepoint()->IterateClientIsolates([](Isolate* client) {
      client->heap()->MakeLinearAllocationAreasIterable();
    });
  }
}
References allocator(), v8::internal::Isolate::global_safepoint(), v8::internal::Isolate::heap(), isolate(), v8::internal::GlobalSafepoint::IterateClientIsolates(), v8::internal::IsolateSafepoint::IterateLocalHeaps(), v8::internal::HeapAllocator::MakeLinearAllocationAreasIterable(), v8::internal::LocalHeap::MakeLinearAllocationAreasIterable(), and safepoint().
Referenced by MakeHeapIterable().
mark_compact_collector()
MarkCompactCollector* v8::internal::Heap::mark_compact_collector () [inline]
Definition at line 856 of file heap.h.
                                                 {
    return mark_compact_collector_.get();
  }
Referenced by v8::internal::MarkingBarrier::ActivateShared(), v8::internal::MinorMarkSweepCollector::CollectGarbage(), v8::internal::ConcurrentMarking::Join(), MarkCompact(), v8::internal::IncrementalMarking::MarkRoots(), v8::internal::ConcurrentMarking::RescheduleJobIfNeeded(), v8::internal::CppHeap::SelectMarkingType(), v8::internal::IncrementalMarking::ShouldFinalize(), v8::internal::IncrementalMarking::Step(), v8::internal::ConcurrentMarking::TryScheduleJob(), v8::internal::RecordMigratedSlotVisitor::VisitCodeTarget(), v8::internal::RecordMigratedSlotVisitor::VisitEmbeddedPointer(), WeakenDescriptorArrays(), and v8::internal::MarkingBarrier::Write().
MarkCompact()
void v8::internal::Heap::MarkCompact () [private]
Definition at line 2733 of file heap.cc.
                       {
  SetGCState(MARK_COMPACT);
  PROFILE(isolate_, CodeMovingGCEvent());
  UpdateOldGenerationAllocationCounter();
  uint64_t size_of_objects_before_gc = SizeOfObjects();
  mark_compact_collector()->Prepare();
  ms_count_++;
  contexts_disposed_ = 0;
  MarkCompactPrologue();
  mark_compact_collector()->CollectGarbage();
  MarkCompactEpilogue();
  if (v8_flags.allocation_site_pretenuring) {
    EvaluateOldSpaceLocalPretenuring(size_of_objects_before_gc);
  }
  // This should be updated before PostGarbageCollectionProcessing, which
  // can cause another GC. Take into account the objects promoted during
  // GC.
  old_generation_allocation_counter_at_last_gc_ +=
      static_cast<size_t>(promoted_objects_size_);
  old_generation_size_at_last_gc_ = OldGenerationSizeOfObjects();
  old_generation_wasted_at_last_gc_ = OldGenerationWastedBytes();
  external_memory_.UpdateLowSinceMarkCompact(external_memory_.total());
  embedder_size_at_last_gc_ = EmbedderSizeOfObjects();
  // Limits can now be computed based on estimate from MARK_COMPACT.
  set_using_initial_limit(false);
}
References v8::internal::MarkCompactCollector::CollectGarbage(), contexts_disposed_, embedder_size_at_last_gc_, EmbedderSizeOfObjects(), EvaluateOldSpaceLocalPretenuring(), external_memory_, isolate_, MARK_COMPACT, mark_compact_collector(), MarkCompactEpilogue(), MarkCompactPrologue(), ms_count_, old_generation_allocation_counter_at_last_gc_, old_generation_size_at_last_gc_, old_generation_wasted_at_last_gc_, OldGenerationSizeOfObjects(), OldGenerationWastedBytes(), v8::internal::MarkCompactCollector::Prepare(), PROFILE, promoted_objects_size_, set_using_initial_limit(), SetGCState(), SizeOfObjects(), v8::internal::Heap::ExternalMemoryAccounting::total(), v8::internal::Heap::ExternalMemoryAccounting::UpdateLowSinceMarkCompact(), UpdateOldGenerationAllocationCounter(), and v8::internal::v8_flags.
Referenced by PerformGarbageCollection().
MarkCompactEpilogue()
void v8::internal::Heap::MarkCompactEpilogue () [private]
Definition at line 2781 of file heap.cc.
                               {
  TRACE_GC(tracer(), GCTracer::Scope::MC_EPILOGUE);
  SetGCState(NOT_IN_GC);
  isolate_->counters()->objs_since_last_full()->Set(0);
}
References v8::internal::Isolate::counters(), isolate_, NOT_IN_GC, SetGCState(), TRACE_GC, and tracer().
Referenced by MarkCompact().
MarkCompactPrologue()
void v8::internal::Heap::MarkCompactPrologue () [private]
Definition at line 2788 of file heap.cc.
                               {
  TRACE_GC(tracer(), GCTracer::Scope::MC_PROLOGUE);
  isolate_->descriptor_lookup_cache()->Clear();
  RegExpResultsCache::Clear(string_split_cache());
  RegExpResultsCache::Clear(regexp_multiple_cache());
  RegExpResultsCache_MatchGlobalAtom::Clear(this);
  // Flush the number to string caches.
  smi_string_cache()->Clear();
  double_string_cache()->Clear();
}
References v8::internal::DescriptorLookupCache::Clear(), v8::internal::RegExpResultsCache_MatchGlobalAtom::Clear(), v8::internal::RegExpResultsCache::Clear(), v8::internal::Isolate::descriptor_lookup_cache(), isolate_, TRACE_GC, and tracer().
Referenced by MarkCompact().
marking_state()
MarkingState* v8::internal::Heap::marking_state () [inline]
Definition at line 1677 of file heap.h.
{ return &marking_state_; }
Referenced by v8::internal::HeapAllocator::AllocateRaw(), v8::internal::OldLargeObjectSpace::AllocateRaw(), RightTrimArray(), and v8::internal::InternalizedStringTableCleaner::VisitRootPointers().
MarkSharedLinearAllocationAreasBlack()
void v8::internal::Heap::MarkSharedLinearAllocationAreasBlack () [private]
Definition at line 3697 of file heap.cc.
                                                {
  DCHECK(!v8_flags.black_allocated_pages);
  allocator()->MarkSharedLinearAllocationAreasBlack();
  main_thread_local_heap()->MarkSharedLinearAllocationAreasBlack();
  safepoint()->IterateLocalHeaps([](LocalHeap* local_heap) {
    local_heap->MarkSharedLinearAllocationAreasBlack();
  });
}
References allocator(), v8::internal::DCHECK(), v8::internal::IsolateSafepoint::IterateLocalHeaps(), main_thread_local_heap(), v8::internal::HeapAllocator::MarkSharedLinearAllocationAreasBlack(), v8::internal::LocalHeap::MarkSharedLinearAllocationAreasBlack(), safepoint(), and v8::internal::v8_flags.
max_old_generation_size()
size_t v8::internal::Heap::max_old_generation_size () const [inline], [private]
Definition at line 1999 of file heap.h.
                                         {
    return max_old_generation_size_.load(std::memory_order_relaxed);
  }
Referenced by AllocationLimitOvershotByLargeMargin(), CanExpandOldGeneration(), CollectGarbage(), ConfigureHeap(), EnsureMinimumRemainingAllocationLimit(), Heap(), InvokeNearHeapLimitCallback(), IsIneffectiveMarkCompact(), IsOldGenerationExpansionAllowed(), MaxReserved(), v8::internal::MemoryBalancer::RefreshLimit(), SetOldGenerationAndGlobalMaximumSize(), and ShouldOptimizeForMemoryUsage().
MaximumCommittedMemory()
size_t v8::internal::Heap::MaximumCommittedMemory () [inline]
Definition at line 1337 of file heap.h.
{ return maximum_committed_; }
Referenced by GarbageCollectionEpilogue().
MaxOldGenerationSize()
size_t v8::internal::Heap::MaxOldGenerationSize () [inline]
Definition at line 1294 of file heap.h.
{ return max_old_generation_size(); }
Referenced by v8::internal::Isolate::InitializeIsShortBuiltinCallsEnabled().
MaxOldGenerationSizeFromPhysicalMemory()
size_t v8::internal::Heap::MaxOldGenerationSizeFromPhysicalMemory (uint64_t physical_memory) [static]
Definition at line 289 of file heap.cc.
                                                                            {
  size_t max_size = DefaulMaxHeapSize();
  // Increase the heap size from 2GB to 4GB for 64-bit systems with physical
  // memory at least 16GB. The threshold is set to 15GB to accommodate for some
  // memory being reserved by the hardware.
#ifdef V8_HOST_ARCH_64_BIT
  if ((physical_memory / GB) >= 15) {
#if V8_OS_ANDROID
    // As of 2024, Android devices with 16GiB are shipping (for instance the
    // Pixel 9 Pro). However, a large fraction of their memory is not usable,
    // and there is no disk swap, so heaps are still smaller than on desktop for
    // now.
    DCHECK_EQ(max_size / GB, v8_flags.high_end_android ? 2u : 1u);
#else
    DCHECK_EQ(max_size / GB, 2u);
#endif
    max_size *= 2;
  }
#endif // V8_HOST_ARCH_64_BIT
  return std::min(max_size, AllocatorLimitOnMaxOldGenerationSize());
}
References AllocatorLimitOnMaxOldGenerationSize(), DCHECK_EQ, DefaulMaxHeapSize(), v8::internal::GB, and v8::internal::v8_flags.
Referenced by HeapSizeFromPhysicalMemory().
MaxRegularHeapObjectSize()
int v8::internal::Heap::MaxRegularHeapObjectSize (AllocationType allocation) [inline]
Definition at line 189 of file heap-inl.h.
                                                            {
  if (allocation == AllocationType::kCode) {
    DCHECK_EQ(MemoryChunkLayout::MaxRegularCodeObjectSize(),
              max_regular_code_object_size_);
    return max_regular_code_object_size_;
  }
  return kMaxRegularHeapObjectSize;
}
References DCHECK_EQ, v8::internal::kCode, v8::internal::kMaxRegularHeapObjectSize, max_regular_code_object_size_, and v8::internal::MemoryChunkLayout::MaxRegularCodeObjectSize().
Referenced by v8::internal::HeapAllocator::AllocateRaw(), v8::internal::HeapAllocator::AllocateRawLargeInternal(), v8::internal::compiler::AllocationBuilder::CanAllocateArray(), and v8::internal::compiler::AllocationBuilder::CanAllocateSloppyArgumentElements().
MaxReserved()
size_t v8::internal::Heap::MaxReserved () const
Definition at line 202 of file heap.cc.
                               {
  const size_t kMaxNewLargeObjectSpaceSize = max_semi_space_size_;
  return static_cast<size_t>(
      (v8_flags.minor_ms ? 1 : 2) * max_semi_space_size_ +
      kMaxNewLargeObjectSpaceSize + max_old_generation_size());
}
References max_old_generation_size(), max_semi_space_size_, and v8::internal::v8_flags.
Referenced by CanExpandOldGeneration(), and SetUp().
MaxSemiSpaceSize()
size_t v8::internal::Heap::MaxSemiSpaceSize () [inline]
Definition at line 1292 of file heap.h.
{ return max_semi_space_size_; }
MeasureMemory()
bool v8::internal::Heap::MeasureMemory (std::unique_ptr< v8::MeasureMemoryDelegate > delegate, v8::MeasureMemoryExecution execution)
Definition at line 4425 of file heap.cc.
                                                             {
  HandleScope handle_scope(isolate());
  std::vector<Handle<NativeContext>> contexts = FindAllNativeContexts();
  std::vector<Handle<NativeContext>> to_measure;
  for (auto& current : contexts) {
    if (delegate->ShouldMeasure(v8::Utils::ToLocal(current))) {
      to_measure.push_back(current);
    }
  }
  return memory_measurement_->EnqueueRequest(std::move(delegate), execution,
                                             to_measure);
}
References FindAllNativeContexts(), isolate(), and memory_measurement_.
Referenced by v8::Isolate::MeasureMemory().
memory_allocator() [1/2]
MemoryAllocator* v8::internal::Heap::memory_allocator () [inline]
Definition at line 846 of file heap.h.
{ return memory_allocator_.get(); }
Referenced by v8::internal::SemiSpace::AllocateFreshPage(), v8::internal::LargeObjectSpace::AllocateLargePage(), v8::internal::ReadOnlySpace::AllocateNextPage(), v8::internal::ReadOnlySpace::AllocateNextPageAt(), Available(), CanExpandOldGeneration(), CommittedMemoryExecutable(), Contains(), ContainsCode(), v8::internal::Sweeper::EnsureMajorCompleted(), v8::internal::ReadOnlySpace::EnsureSpaceForAllocation(), v8::internal::MarkCompactCollector::Finish(), v8::internal::NewLargeObjectSpace::FreeDeadObjects(), GarbageCollectionPrologueInSafepoint(), InSpace(), InSpaceSlow(), v8::internal::GCTracer::Print(), v8::internal::GCTracer::PrintNVP(), PrintShortHeapStatistics(), RecordStats(), ReplaceReadOnlySpace(), v8::internal::SemiSpace::RewindPages(), v8::internal::ReadOnlySpace::Seal(), v8::internal::LargeObjectSpace::ShrinkPageToObjectSize(), v8::internal::ReadOnlyPageMetadata::ShrinkToHighWaterMark(), v8::internal::GCTracer::StartInSafepoint(), v8::internal::MinorMarkSweepCollector::StartSweepNewSpace(), v8::internal::GCTracer::StopInSafepoint(), v8::internal::MinorMarkSweepCollector::SweepNewLargeSpace(), TearDown(), v8::internal::LargeObjectSpace::TearDown(), v8::internal::HeapAllocator::TryResizeLargeObject(), v8::internal::Sweeper::ZeroOrDiscardUnusedMemory(), and v8::internal::SemiSpace::~SemiSpace().
memory_allocator() [2/2]
const MemoryAllocator* v8::internal::Heap::memory_allocator () const [inline]
Definition at line 847 of file heap.h.
                                                  {
    return memory_allocator_.get();
  }
memory_measurement()
MemoryMeasurement* v8::internal::Heap::memory_measurement () [inline], [private]
Definition at line 2115 of file heap.h.
{ return memory_measurement_.get(); }
Referenced by v8::internal::MarkCompactCollector::CollectGarbage(), and v8::internal::MarkCompactCollector::StartMarking().
memory_reducer()
MemoryReducer* v8::internal::Heap::memory_reducer () [inline], [private]
Definition at line 1971 of file heap.h.
{ return memory_reducer_.get(); }
Referenced by CurrentHeapGrowingMode(), NotifyOldGenerationExpansion(), and StartIncrementalMarkingIfAllocationLimitIsReached().
MemoryPressureNotification()
void v8::internal::Heap::MemoryPressureNotification (v8::MemoryPressureLevel level, bool is_isolate_locked)
Definition at line 4330 of file heap.cc.
                                                              {
  TRACE_EVENT1("devtools.timeline,v8", "V8.MemoryPressureNotification", "level",
               static_cast<int>(level));
  MemoryPressureLevel previous =
      memory_pressure_level_.exchange(level, std::memory_order_relaxed);
  if ((previous != MemoryPressureLevel::kCritical &&
       level == MemoryPressureLevel::kCritical) ||
      (previous == MemoryPressureLevel::kNone &&
       level == MemoryPressureLevel::kModerate)) {
    if (is_isolate_locked) {
      CheckMemoryPressure();
    } else {
      ExecutionAccess access(isolate());
      isolate()->stack_guard()->RequestGC();
      task_runner_->PostTask(
          std::make_unique<MemoryPressureInterruptTask>(this));
    }
  }
}
References CheckMemoryPressure(), isolate(), v8::kCritical, v8::kModerate, v8::kNone, memory_pressure_level_, v8::internal::Isolate::stack_guard(), task_runner_, and TRACE_EVENT1.
Referenced by v8::internal::wasm::WasmImportWrapperCache::LazyInitialize(), v8::Isolate::MemoryPressureNotification(), v8::internal::wasm::WasmCodeManager::NewNativeModule(), and v8::internal::BackingStore::TryAllocateAndPartiallyCommitMemory().
min_old_generation_size()
size_t v8::internal::Heap::min_old_generation_size () const [inline], [private]
Definition at line 2003 of file heap.h.
{ return min_old_generation_size_; }
Referenced by EnsureMinimumRemainingAllocationLimit(), and v8::internal::MemoryBalancer::RefreshLimit().
MinOldGenerationSize()
size_t v8::internal::Heap::MinOldGenerationSize () [static]
Definition at line 272 of file heap.cc.
                                  {
  size_t paged_space_count =
      LAST_GROWABLE_PAGED_SPACE - FIRST_GROWABLE_PAGED_SPACE + 1;
  return paged_space_count * PageMetadata::kPageSize;
}
References v8::internal::FIRST_GROWABLE_PAGED_SPACE, v8::internal::MutablePageMetadata::kPageSize, and v8::internal::LAST_GROWABLE_PAGED_SPACE.
Referenced by v8::ResourceConstraints::ConfigureDefaultsFromHeapSize(), and ConfigureHeap().
minor_gc_job()
MinorGCJob* v8::internal::Heap::minor_gc_job () [inline], [private]
Definition at line 2054 of file heap.h.
{ return minor_gc_job_.get(); }
Referenced by GarbageCollectionPrologue(), and StartMinorMSConcurrentMarkingIfNeeded().
minor_mark_sweep_collector()
MinorMarkSweepCollector* v8::internal::Heap::minor_mark_sweep_collector () [inline]
Definition at line 860 of file heap.h.
                                                        {
    return minor_mark_sweep_collector_.get();
  }
Referenced by v8::internal::ConcurrentMarking::GetMinorMaxConcurrency(), HandleGCRequest(), v8::internal::ConcurrentMarking::IsWorkLeft(), v8::internal::IncrementalMarking::MarkRoots(), v8::internal::ConcurrentMarking::RescheduleJobIfNeeded(), v8::internal::ConcurrentMarking::RunMinor(), v8::internal::ConcurrentMarking::RunMinorImpl(), and v8::internal::ConcurrentMarking::TryScheduleJob().
minor_sweeping_in_progress()
bool v8::internal::Heap::minor_sweeping_in_progress () const [inline]
Definition at line 1595 of file heap.h.
                                          {
    return sweeper_->minor_sweeping_in_progress();
  }
Referenced by EnsureSweepingCompleted(), EnsureYoungSweepingCompleted(), PrintShortHeapStatistics(), and v8::internal::IncrementalMarking::Start().
MinorMarkSweep()
void v8::internal::Heap::MinorMarkSweep () [private]
Definition at line 2768 of file heap.cc.
                          {
  DCHECK(v8_flags.minor_ms);
  CHECK_EQ(NOT_IN_GC, gc_state());
  DCHECK(use_new_space());
  DCHECK(!incremental_marking()->IsMajorMarking());
  TRACE_GC(tracer(), GCTracer::Scope::MINOR_MS);
  SetGCState(MINOR_MARK_SWEEP);
  minor_mark_sweep_collector_->CollectGarbage();
  SetGCState(NOT_IN_GC);
}
References CHECK_EQ, v8::internal::DCHECK(), gc_state(), incremental_marking(), MINOR_MARK_SWEEP, minor_mark_sweep_collector_, NOT_IN_GC, SetGCState(), TRACE_GC, tracer(), use_new_space(), and v8::internal::v8_flags.
Referenced by PerformGarbageCollection().
MinorMSSizeTaskTriggerReached()
bool v8::internal::Heap::MinorMSSizeTaskTriggerReached () const [private]
MinYoungGenerationSize()
size_t v8::internal::Heap::MinYoungGenerationSize () [static]
Definition at line 268 of file heap.cc.
                                    {
  return YoungGenerationSizeFromSemiSpaceSize(DefaultMinSemiSpaceSize());
}
References DefaultMinSemiSpaceSize(), and YoungGenerationSizeFromSemiSpaceSize().
Referenced by v8::ResourceConstraints::ConfigureDefaultsFromHeapSize().
MonotonicallyIncreasingTimeInMs()
double v8::internal::Heap::MonotonicallyIncreasingTimeInMs () const
Definition at line 4244 of file heap.cc.
                                                   {
  return V8::GetCurrentPlatform()->MonotonicallyIncreasingTime() *
         static_cast<double>(base::Time::kMillisecondsPerSecond);
}
References v8::internal::V8::GetCurrentPlatform(), v8::base::TimeConstants::kMillisecondsPerSecond, and v8::Platform::MonotonicallyIncreasingTime().
Referenced by v8::internal::Heap::AllocationTrackerForDebugging::AllocationEvent(), CollectGarbageOnMemoryPressure(), GarbageCollectionEpilogue(), v8::internal::StackGuard::HandleInterrupts(), v8::internal::Isolate::Init(), v8::internal::Heap::AllocationTrackerForDebugging::MoveEvent(), NotifyLoadingStarted(), v8::internal::MemoryReducer::NotifyMarkCompact(), v8::internal::MemoryReducer::NotifyPossibleGarbage(), ShouldOptimizeForLoadTime(), and v8::internal::V8FileLogger::Time().
MoveRange() [1/2]
template<typename TSlot >
void v8::internal::Heap::MoveRange (Tagged< HeapObject > dst_object, const TSlot dst_slot, const TSlot src_slot, int len, WriteBarrierMode mode)
Definition at line 2117 of file heap.cc.
                                                                           {
  // Ensure no range overflow.
  DCHECK(dst_slot < TSlot(dst_slot + len));
  DCHECK(src_slot < src_slot + len);
  const auto atomic_callback = [](TSlot dst_slot, TSlot dst_end, TSlot src_slot,
                                  int len) {
    if (dst_slot < src_slot) {
      // Copy tagged values forward using relaxed load/stores that do not
      // involve value decompression.
      const AtomicSlot atomic_dst_end(dst_end);
      AtomicSlot dst(dst_slot);
      AtomicSlot src(src_slot);
      while (dst < atomic_dst_end) {
        *dst = *src;
        ++dst;
        ++src;
      }
    } else {
      // Copy tagged values backwards using relaxed load/stores that do not
      // involve value decompression.
      const AtomicSlot atomic_dst_begin(dst_slot);
      AtomicSlot dst(dst_slot + len - 1);
      AtomicSlot src(src_slot + len - 1);
      while (dst >= atomic_dst_begin) {
        *dst = *src;
        --dst;
        --src;
      }
    }
  };
  const auto non_atomic_callback = [](TSlot dst_slot, TSlot src_slot, int len) {
    MemMove(dst_slot.ToVoidPtr(), src_slot.ToVoidPtr(), len * kTaggedSize);
  };
  CopyOrMoveRangeImpl(this, dst_object, dst_slot, src_slot, len, mode,
                      atomic_callback, non_atomic_callback);
}
References v8::internal::anonymous_namespace{heap.cc}::CopyOrMoveRangeImpl(), v8::internal::DCHECK(), v8::internal::kTaggedSize, v8::internal::MemMove(), and mode().
MoveRange() [2/2]
template<typename TSlot >
V8_EXPORT_PRIVATE void v8::internal::Heap::MoveRange (Tagged< HeapObject > dst_object, TSlot dst_slot, TSlot src_slot, int len, WriteBarrierMode mode)
Referenced by v8::internal::TaggedArrayBase< Derived, ShapeT, Super >::MoveElements(), and v8::internal::RUNTIME_FUNCTION().
ms_count()
int v8::internal::Heap::ms_count () const [inline]
Definition at line 543 of file heap.h.
{ return ms_count_; }
MustBeInSharedOldSpace()
bool v8::internal::Heap::MustBeInSharedOldSpace (Tagged< HeapObject > value)
Definition at line 4525 of file heap.cc.
                                                          {
  if (isolate()->OwnsStringTables()) return false;
  if (ReadOnlyHeap::Contains(value)) return false;
  if (HeapLayout::InYoungGeneration(value)) return false;
  if (IsExternalString(value)) return false;
  if (IsInternalizedString(value)) return true;
  return false;
}
References v8::internal::ReadOnlyHeap::Contains(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::InstanceTypeChecker::IsExternalString(), v8::internal::InstanceTypeChecker::IsInternalizedString(), isolate(), and v8::internal::value.
native_contexts_list()
Tagged<Object> v8::internal::Heap::native_contexts_list () const [inline]
Definition at line 504 of file heap.h.
                                              {
    return Tagged<Object>(
        native_contexts_list_.load(std::memory_order_acquire));
  }
References v8::internal::Tagged< Object >.
Referenced by FindAllNativeContexts(), FindAllRetainedMaps(), NumberOfNativeContexts(), ProcessNativeContexts(), and ProcessWeakListRoots().
new_lo_space()
NewLargeObjectSpace* v8::internal::Heap::new_lo_space () const [inline]
Definition at line 780 of file heap.h.
{ return new_lo_space_; }
Referenced by CanPromoteYoungAndExpandOldGeneration(), v8::internal::MinorMarkSweepCollector::CollectGarbage(), v8::internal::ScavengerCollector::CollectGarbage(), ExpandNewSpaceSize(), v8::internal::MarkCompactCollector::Finish(), v8::internal::ScavengerCollector::HandleSurvivingNewLargeObjects(), v8::internal::MarkCompactCollector::MarkObjectsFromClientHeap(), NotifyDeserializationComplete(), PerformGarbageCollection(), v8::internal::ConcurrentMarking::RunMajor(), v8::internal::ConcurrentMarking::RunMinor(), v8::internal::ConcurrentMarking::RunMinorImpl(), v8::internal::GCTracer::StartInSafepoint(), v8::internal::MinorMarkSweepCollector::Sweep(), v8::internal::MarkCompactCollector::SweepArrayBufferExtensions(), v8::internal::ScavengerCollector::SweepArrayBufferExtensions(), v8::internal::MinorMarkSweepCollector::SweepNewLargeSpace(), YoungGenerationConsumedBytes(), and YoungGenerationSizeOfObjects().
new_space()
NewSpace* v8::internal::Heap::new_space () const [inline]
Definition at line 770 of file heap.h.
{ return new_space_; }
Referenced by AllocateExternalBackingStore(), CanPromoteYoungAndExpandOldGeneration(), v8::internal::ScavengerCollector::CollectGarbage(), v8::internal::anonymous_namespace{heap.cc}::ComputeReducedNewSpaceSize(), CreateMutableHeapObjects(), DeactivateMajorGCInProgressFlag(), ExpandNewSpaceSize(), v8::internal::MarkCompactCollector::Finish(), v8::internal::MinorMarkSweepCollector::Finish(), GarbageCollectionEpilogueInSafepoint(), IsStressingScavenge(), v8::internal::MarkCompactCollector::MarkObjectsFromClientHeap(), v8::internal::EvacuateNewToOldSpacePageVisitor::Move(), NewSpaceAllocationCounter(), NewSpaceCapacity(), NewSpaceSize(), NewSpaceTargetCapacity(), NotifyContextDisposed(), NotifyDeserializationComplete(), v8::internal::ScavengerCollector::NumberOfScavengeTasks(), paged_new_space(), v8::internal::MarkCompactCollector::Prepare(), v8::internal::GCTracer::PrintNVP(), v8::internal::PretenuringHandler::ProcessPretenuringFeedback(), ReduceNewSpaceSize(), v8::internal::StressScavengeObserver::RequestedGCDone(), Scavenge(), SelectGarbageCollector(), semi_space_new_space(), v8::internal::HeapAllocator::Setup(), SetUpSpaces(), v8::internal::GCTracer::StartInSafepoint(), v8::internal::MinorMarkSweepCollector::StartMarking(), StartMinorMSConcurrentMarkingIfNeeded(), StartResizeNewSpace(), v8::internal::MinorMarkSweepCollector::StartSweepNewSpace(), v8::internal::StressScavengeObserver::Step(), v8::internal::MinorMarkSweepCollector::Sweep(), v8::internal::MarkCompactCollector::SweepArrayBufferExtensions(), v8::internal::ScavengerCollector::SweepArrayBufferExtensions(), v8::internal::Sweeper::SweepEmptyNewSpacePage(), Unmark(), YoungGenerationConsumedBytes(), YoungGenerationSizeOfObjects(), and YoungGenerationWastedBytes().
new_space_surviving_object_size()
size_t v8::internal::Heap::new_space_surviving_object_size () [inline]
Definition at line 1367 of file heap.h.
                                                  {
    return new_space_surviving_object_size_;
  }
Referenced by v8::internal::GCTracer::PrintNVP().
NewSpaceAllocationCounter()
size_t v8::internal::Heap::NewSpaceAllocationCounter () const
Definition at line 999 of file heap.cc.
                                             {
  size_t counter = new_space_allocation_counter_;
  if (new_space_) {
    DCHECK(!allocator()->new_space_allocator()->IsLabValid());
    counter += new_space()->AllocatedSinceLastGC();
  }
  return counter;
}
References v8::internal::NewSpace::AllocatedSinceLastGC(), allocator(), v8::internal::DCHECK(), new_space(), new_space_, and new_space_allocation_counter_.
Referenced by GarbageCollectionPrologueInSafepoint(), and v8::internal::GCTracer::StartInSafepoint().
NewSpaceAllocationLimitAddress()
Address * v8::internal::Heap::NewSpaceAllocationLimitAddress () [inline]
Definition at line 166 of file heap-inl.h.
                                              {
  return new_space_ || v8_flags.sticky_mark_bits
             ? isolate()->isolate_data()->new_allocation_info_.limit_address()
             : nullptr;
}
References isolate(), v8::internal::Isolate::isolate_data(), v8::internal::LinearAllocationArea::limit_address(), v8::internal::IsolateData::new_allocation_info_, new_space_, and v8::internal::v8_flags.
Referenced by v8::internal::WasmTrustedInstanceData::New().
NewSpaceAllocationTopAddress()
Address * v8::internal::Heap::NewSpaceAllocationTopAddress () [inline]
Definition at line 160 of file heap-inl.h.
                                            {
  return new_space_ || v8_flags.sticky_mark_bits
             ? isolate()->isolate_data()->new_allocation_info_.top_address()
             : nullptr;
}
References isolate(), v8::internal::Isolate::isolate_data(), v8::internal::IsolateData::new_allocation_info_, new_space_, v8::internal::LinearAllocationArea::top_address(), and v8::internal::v8_flags.
Referenced by v8::internal::WasmTrustedInstanceData::New().
NewSpaceCapacity()
size_t v8::internal::Heap::NewSpaceCapacity () const
Definition at line 4043 of file heap.cc.
                                    {
  if (v8_flags.sticky_mark_bits) {
    return sticky_space()->Capacity() - sticky_space()->young_objects_size();
  }
  return new_space() ? new_space()->Capacity() : 0;
}
References v8::internal::PagedSpaceBase::Capacity(), v8::internal::NewSpace::Capacity(), new_space(), sticky_space(), v8::internal::v8_flags, and v8::internal::StickySpace::young_objects_size().
Referenced by Capacity(), RecordStats(), and SetUpSpaces().
NewSpaceLimit()
Address v8::internal::Heap::NewSpaceLimit () [inline]
Definition at line 235 of file heap-inl.h.
                            {
  return new_space_ || v8_flags.sticky_mark_bits
             ? allocator()->new_space_allocator()->limit()
             : kNullAddress;
}
References allocator(), v8::internal::kNullAddress, v8::internal::MainAllocator::limit(), new_space_, v8::internal::HeapAllocator::new_space_allocator(), and v8::internal::v8_flags.
NewSpaceSize()
size_t v8::internal::Heap::NewSpaceSize ()
Definition at line 4036 of file heap.cc.
                          {
  if (v8_flags.sticky_mark_bits) {
    return sticky_space()->young_objects_size();
  }
  return new_space() ? new_space()->Size() : 0;
}
References new_space(), sticky_space(), v8::internal::v8_flags, and v8::internal::StickySpace::young_objects_size().
Referenced by PerformGarbageCollection(), PrintShortHeapStatistics(), and RecordStats().
NewSpaceTargetCapacity()
size_t v8::internal::Heap::NewSpaceTargetCapacity () const
Definition at line 4050 of file heap.cc.
                                          {
  if (v8_flags.sticky_mark_bits) {
    // TODO(333906585): Adjust target capacity for new sticky-space.
    return sticky_space()->Capacity() - sticky_space()->young_objects_size();
  }
  return new_space() ? new_space()->TotalCapacity() : 0;
}
References v8::internal::PagedSpaceBase::Capacity(), new_space(), sticky_space(), v8::internal::NewSpace::TotalCapacity(), v8::internal::v8_flags, and v8::internal::StickySpace::young_objects_size().
Referenced by IncrementalMarkingLimitReached(), PerformGarbageCollection(), v8::internal::PretenuringHandler::ProcessPretenuringFeedback(), and StartIncrementalMarkingIfAllocationLimitIsReached().
NewSpaceTop()
Address v8::internal::Heap::NewSpaceTop () [inline]
Definition at line 229 of file heap-inl.h.
                          {
  return new_space_ || v8_flags.sticky_mark_bits
             ? allocator()->new_space_allocator()->top()
             : kNullAddress;
}
References allocator(), v8::internal::kNullAddress, new_space_, v8::internal::HeapAllocator::new_space_allocator(), v8::internal::MainAllocator::top(), and v8::internal::v8_flags.
Referenced by v8::internal::MinorMarkSweepCollector::TraceFragmentation().
NextDebuggingId()
int v8::internal::Heap::NextDebuggingId ()
Definition at line 7616 of file heap.cc.
                          {
  int last_id = last_debugging_id().value();
  if (last_id == DebugInfo::DebuggingIdBits::kMax) {
    last_id = DebugInfo::kNoDebuggingId;
  }
  last_id++;
  set_last_debugging_id(Smi::FromInt(last_id));
  return last_id;
}
References v8::internal::Smi::FromInt(), and v8::internal::DebugInfo::kNoDebuggingId.
Referenced by v8::internal::Debug::GetFunctionDebuggingId().
NextScriptId()
int v8::internal::Heap::NextScriptId ()
Definition at line 7592 of file heap.cc.
                       {
  FullObjectSlot last_script_id_slot(&roots_table()[RootIndex::kLastScriptId]);
  Tagged<Smi> last_id = Cast<Smi>(last_script_id_slot.Relaxed_Load());
  Tagged<Smi> new_id, last_id_before_cas;
  do {
    if (last_id.value() == Smi::kMaxValue) {
      static_assert(v8::UnboundScript::kNoScriptId == 0);
      new_id = Smi::FromInt(1);
    } else {
      new_id = Smi::FromInt(last_id.value() + 1);
    }
    // CAS returns the old value on success, and the current value in the slot
    // on failure. Therefore, we want to break if the returned value matches the
    // old value (last_id), and keep looping (with the new last_id value) if it
    // doesn't.
    last_id_before_cas = last_id;
    last_id =
        Cast<Smi>(last_script_id_slot.Relaxed_CompareAndSwap(last_id, new_id));
  } while (last_id != last_id_before_cas);
  return new_id.value();
}
References v8::internal::Smi::FromInt(), v8::internal::Smi::kMaxValue, v8::UnboundScript::kNoScriptId, v8::internal::FullObjectSlot::Relaxed_CompareAndSwap(), v8::internal::FullObjectSlot::Relaxed_Load(), roots_table(), and v8::internal::Tagged< Smi >::value().
Referenced by v8::internal::Isolate::GetNextScriptId().
NextStackTraceId()
int v8::internal::Heap::NextStackTraceId ()
Definition at line 7626 of file heap.cc.
                           {
  int last_id = last_stack_trace_id().value();
  if (last_id == Smi::kMaxValue) {
    last_id = 0;
  }
  last_id++;
  set_last_stack_trace_id(Smi::FromInt(last_id));
  return last_id;
}
References v8::internal::Smi::FromInt(), and v8::internal::Smi::kMaxValue.
NextStressMarkingLimit()
int v8::internal::Heap::NextStressMarkingLimit () [private]
Definition at line 6128 of file heap.cc.
                                 {
  return isolate()->fuzzer_rng()->NextInt(v8_flags.stress_marking + 1);
}
References v8::internal::Isolate::fuzzer_rng(), isolate(), v8::base::RandomNumberGenerator::NextInt(), and v8::internal::v8_flags.
Referenced by GarbageCollectionEpilogueInSafepoint(), and SetUpSpaces().
non_atomic_marking_state()
NonAtomicMarkingState* v8::internal::Heap::non_atomic_marking_state () [inline]
Definition at line 1679 of file heap.h.
                                                    {
    return &non_atomic_marking_state_;
  }
Referenced by v8::internal::MarkCompactCollector::IsUnmarkedSharedHeapObject().
NotifyBootstrapComplete()
void v8::internal::Heap::NotifyBootstrapComplete ()
Definition at line 6191 of file heap.cc.
                                   {
  // This function is invoked for each native context creation. We are
  // interested only in the first native context.
  if (old_generation_capacity_after_bootstrap_ == 0) {
    old_generation_capacity_after_bootstrap_ = OldGenerationCapacity();
  }
}
References old_generation_capacity_after_bootstrap_, and OldGenerationCapacity().
Referenced by v8::internal::Bootstrapper::CreateEnvironment().
NotifyContextDisposed()
int v8::internal::Heap::NotifyContextDisposed (bool has_dependent_context)
Definition at line 1905 of file heap.cc.
                                                          {
  if (!has_dependent_context) {
    tracer()->ResetSurvivalEvents();
    if (!initial_size_overwritten_) {
      ResetOldGenerationAndGlobalAllocationLimit();
    } else if (preconfigured_old_generation_size_) {
      EnsureMinimumRemainingAllocationLimit(initial_old_generation_size_);
    }
    if (memory_reducer_) {
      memory_reducer_->NotifyPossibleGarbage();
    }
  } else if (v8_flags.idle_gc_on_context_disposal &&
             !v8_flags.single_generation) {
    DCHECK_NOT_NULL(new_space());
    IdleTaskOnContextDispose::TryPostJob(this);
  }
  if (!isolate()->context().is_null()) {
    RemoveDirtyFinalizationRegistriesOnContext(isolate()->raw_native_context());
    isolate()->raw_native_context()->set_retained_maps(
        ReadOnlyRoots(this).empty_weak_array_list());
  }
  return ++contexts_disposed_;
}
References contexts_disposed_, DCHECK_NOT_NULL, EnsureMinimumRemainingAllocationLimit(), initial_old_generation_size_, initial_size_overwritten_, isolate(), memory_reducer_, new_space(), preconfigured_old_generation_size_, v8::internal::Isolate::raw_native_context(), ReadOnlyRoots, RemoveDirtyFinalizationRegistriesOnContext(), ResetOldGenerationAndGlobalAllocationLimit(), v8::internal::GCTracer::ResetSurvivalEvents(), tracer(), v8::internal::IdleTaskOnContextDispose::TryPostJob(), and v8::internal::v8_flags.
Referenced by v8::Isolate::ContextDisposedNotification().
NotifyDeserializationComplete()
void v8::internal::Heap::NotifyDeserializationComplete ()
Definition at line 6159 of file heap.cc.
                                         {
  // There are no concurrent/background threads yet.
  safepoint()->AssertMainThreadIsOnlyThread();
  FreeMainThreadLinearAllocationAreas();
#if DEBUG
  PagedSpaceIterator spaces(this);
  for (PagedSpace* s = spaces.Next(); s != nullptr; s = spaces.Next()) {
    // All pages right after bootstrapping must be marked as never-evacuate.
    for (PageMetadata* p : *s) {
      DCHECK(p->Chunk()->NeverEvacuate());
    }
  }
#endif // DEBUG
  if (v8_flags.stress_concurrent_allocation) {
    stress_concurrent_allocation_observer_.reset(
        new StressConcurrentAllocationObserver(this));
    AddAllocationObserversToAllSpaces(
        stress_concurrent_allocation_observer_.get(),
        stress_concurrent_allocation_observer_.get());
    need_to_remove_stress_concurrent_allocation_observer_ = true;
  }
  // Deserialization will never create objects in new space.
  DCHECK_IMPLIES(new_space(), new_space()->Size() == 0);
  DCHECK_IMPLIES(new_lo_space(), new_lo_space()->Size() == 0);
  deserialization_complete_ = true;
}
References AddAllocationObserversToAllSpaces(), v8::internal::IsolateSafepoint::AssertMainThreadIsOnlyThread(), v8::internal::DCHECK(), DCHECK_IMPLIES, deserialization_complete_, FreeMainThreadLinearAllocationAreas(), need_to_remove_stress_concurrent_allocation_observer_, new_lo_space(), new_space(), v8::internal::PagedSpaceIterator::Next(), safepoint(), stress_concurrent_allocation_observer_, StressConcurrentAllocationObserver, and v8::internal::v8_flags.
Referenced by v8::internal::Isolate::Init().
NotifyLoadingEnded()
void v8::internal::Heap::NotifyLoadingEnded () [private]
Definition at line 7582 of file heap.cc.
                              {
  load_start_time_ms_.store(kLoadTimeNotLoading, std::memory_order_relaxed);
  RecomputeLimitsAfterLoadingIfNeeded();
  if (auto* job = incremental_marking()->incremental_marking_job()) {
    // The task will start incremental marking (if needed not already started)
    // and advance marking if incremental marking is active.
    job->ScheduleTask(TaskPriority::kUserVisible);
  }
}
References incremental_marking(), kLoadTimeNotLoading, v8::kUserVisible, load_start_time_ms_, and RecomputeLimitsAfterLoadingIfNeeded().
Referenced by v8::internal::Isolate::SetIsLoading().
NotifyLoadingStarted()
void v8::internal::Heap::NotifyLoadingStarted () [private]
Definition at line 7575 of file heap.cc.
                                {
  update_allocation_limits_after_loading_ = true;
  double now_ms = MonotonicallyIncreasingTimeInMs();
  DCHECK_NE(now_ms, kLoadTimeNotLoading);
  load_start_time_ms_.store(now_ms, std::memory_order_relaxed);
}
References DCHECK_NE, kLoadTimeNotLoading, load_start_time_ms_, MonotonicallyIncreasingTimeInMs(), and update_allocation_limits_after_loading_.
Referenced by v8::internal::Isolate::SetIsLoading().
NotifyObjectLayoutChange()
void v8::internal::Heap::NotifyObjectLayoutChange (Tagged< HeapObject > object, const DisallowGarbageCollection & , InvalidateRecordedSlots invalidate_recorded_slots, InvalidateExternalPointerSlots invalidate_external_pointer_slots, int new_size = 0)
Definition at line 4130 of file heap.cc.
                  {
  if (invalidate_recorded_slots == InvalidateRecordedSlots::kYes) {
    const bool may_contain_recorded_slots = MayContainRecordedSlots(object);
    MutablePageMetadata* const chunk =
        MutablePageMetadata::FromHeapObject(object);
    // Do not remove the recorded slot in the map word as this one can never be
    // invalidated.
    const Address clear_range_start = object.address() + kTaggedSize;
    // Only slots in the range of the new object size (which is potentially
    // smaller than the original one) can be invalidated. Clearing of recorded
    // slots up to the original object size even conflicts with concurrent
    // sweeping.
    const Address clear_range_end = object.address() + new_size;
    if (incremental_marking()->IsMarking()) {
      ObjectLock::Lock(object);
      DCHECK_EQ(pending_layout_change_object_address, kNullAddress);
      pending_layout_change_object_address = object.address();
      if (may_contain_recorded_slots && incremental_marking()->IsCompacting()) {
        RememberedSet<OLD_TO_OLD>::RemoveRange(
            chunk, clear_range_start, clear_range_end,
            SlotSet::EmptyBucketMode::KEEP_EMPTY_BUCKETS);
      }
    }
    if (may_contain_recorded_slots) {
      RememberedSet<OLD_TO_NEW>::RemoveRange(
          chunk, clear_range_start, clear_range_end,
          SlotSet::EmptyBucketMode::KEEP_EMPTY_BUCKETS);
      RememberedSet<OLD_TO_NEW_BACKGROUND>::RemoveRange(
          chunk, clear_range_start, clear_range_end,
          SlotSet::EmptyBucketMode::KEEP_EMPTY_BUCKETS);
      RememberedSet<OLD_TO_SHARED>::RemoveRange(
          chunk, clear_range_start, clear_range_end,
          SlotSet::EmptyBucketMode::KEEP_EMPTY_BUCKETS);
    }
    DCHECK(!chunk->InTrustedSpace());
  }
  // During external pointer table compaction, the external pointer table
  // records addresses of fields that index into the external pointer table. As
  // such, it needs to be informed when such a field is invalidated.
  if (invalidate_external_pointer_slots ==
      InvalidateExternalPointerSlots::kYes) {
    // Currently, the only time this function receives
    // InvalidateExternalPointerSlots::kYes is when an external string
    // transitions to a thin string. If this ever changed to happen for array
    // buffer extension slots, we would have to run the invalidator in
    // pointer-compression-but-no-sandbox configurations as well.
    DCHECK(IsString(object));
#ifdef V8_ENABLE_SANDBOX
    if (V8_ENABLE_SANDBOX_BOOL) {
      ExternalPointerSlotInvalidator slot_invalidator(isolate());
      int num_invalidated_slots = slot_invalidator.Visit(object);
      USE(num_invalidated_slots);
      DCHECK_GT(num_invalidated_slots, 0);
    }
    // During concurrent marking for a minor GC, the heap also builds up a
    // RememberedSet of external pointer field locations, and uses that set to
    // evacuate external pointer table entries when promoting objects. Here we
    // would need to invalidate that set too; until we do, assert that
    // NotifyObjectLayoutChange is never called on young objects.
    CHECK(!HeapLayout::InYoungGeneration(object));
#endif
  }
#ifdef VERIFY_HEAP
  if (v8_flags.verify_heap) {
    HeapVerifier::SetPendingLayoutChangeObject(this, object);
  }
#endif
}
References CHECK, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GT, v8::internal::MutablePageMetadata::FromHeapObject(), incremental_marking(), v8::internal::MemoryChunkMetadata::InTrustedSpace(), v8::internal::HeapLayout::InYoungGeneration(), isolate(), v8::internal::kNullAddress, v8::internal::kTaggedSize, v8::internal::kYes, v8::internal::ObjectLock::Lock(), v8::internal::anonymous_namespace{heap.cc}::MayContainRecordedSlots(), v8::internal::anonymous_namespace{heap.cc}::pending_layout_change_object_address, v8::internal::RememberedSet< type >::RemoveRange(), USE, V8_ENABLE_SANDBOX_BOOL, and v8::internal::v8_flags.
Referenced by v8::internal::TranslatedState::InitializeJSObjectAt(), v8::internal::TranslatedState::InitializeObjectWithTaggedFieldsAt(), and v8::internal::String::MakeExternal().
NotifyObjectLayoutChangeDone()
void v8::internal::Heap::NotifyObjectLayoutChangeDone (Tagged< HeapObject > object) [static]
Definition at line 4210 of file heap.cc.
                                                                 {
  if (pending_layout_change_object_address != kNullAddress) {
    DCHECK_EQ(pending_layout_change_object_address, object.address());
    ObjectLock::Unlock(object);
    pending_layout_change_object_address = kNullAddress;
  }
}
References DCHECK_EQ, v8::internal::kNullAddress, v8::internal::anonymous_namespace{heap.cc}::pending_layout_change_object_address, and v8::internal::ObjectLock::Unlock().
Referenced by v8::internal::HeapObject::set_map().
NotifyObjectSizeChange()
void v8::internal::Heap::NotifyObjectSizeChange (Tagged< HeapObject > object, int old_size, int new_size, ClearRecordedSlots clear_recorded_slots)
Definition at line 4218 of file heap.cc.
                                                                           {
  old_size = ALIGN_TO_ALLOCATION_ALIGNMENT(old_size);
  new_size = ALIGN_TO_ALLOCATION_ALIGNMENT(new_size);
  DCHECK_LE(new_size, old_size);
  DCHECK(!IsLargeObject(object));
  if (new_size == old_size) return;
  const bool is_main_thread = LocalHeap::Current() == nullptr;
  DCHECK_IMPLIES(!is_main_thread,
                 clear_recorded_slots == ClearRecordedSlots::kNo);
  const auto verify_no_slots_recorded =
      is_main_thread ? VerifyNoSlotsRecorded::kYes : VerifyNoSlotsRecorded::kNo;
  const auto clear_memory_mode = ClearFreedMemoryMode::kDontClearFreedMemory;
  const Address filler = object.address() + new_size;
  const int filler_size = old_size - new_size;
  CreateFillerObjectAtRaw(
      WritableFreeSpace::ForNonExecutableMemory(filler, filler_size),
      clear_memory_mode, clear_recorded_slots, verify_no_slots_recorded);
}
References ALIGN_TO_ALLOCATION_ALIGNMENT, CreateFillerObjectAtRaw(), v8::internal::DCHECK(), DCHECK_IMPLIES, DCHECK_LE, v8::internal::WritableFreeSpace::ForNonExecutableMemory(), IsLargeObject(), v8::internal::kDontClearFreedMemory, v8::internal::kNo, kNo, and kYes.
Referenced by v8::internal::String::MakeExternal(), v8::internal::String::MakeExternalDuringGC(), v8::internal::LocalHeap::NotifyObjectSizeChange(), RightTrimArray(), and v8::internal::anonymous_namespace{bigint.cc}::RightTrimString().
NotifyOldGenerationExpansion()
void v8::internal::Heap::NotifyOldGenerationExpansion (LocalHeap * local_heap, AllocationSpace space, MutablePageMetadata * chunk, OldGenerationExpansionNotificationOrigin notification_origin = OldGenerationExpansionNotificationOrigin::kFromSameHeap)
Definition at line 6199 of file heap.cc.
                                                                  {
  // Pages created during bootstrapping may contain immortal immovable objects.
  if (!deserialization_complete()) {
    DCHECK_NE(NEW_SPACE, chunk_metadata->owner()->identity());
    chunk_metadata->Chunk()->MarkNeverEvacuate();
  }
  if (IsAnyCodeSpace(space)) {
    isolate()->AddCodeMemoryChunk(chunk_metadata);
  }
  // Don't notify MemoryReducer when calling from client heap as otherwise not
  // thread safe.
  const size_t kMemoryReducerActivationThreshold = 1 * MB;
  if (local_heap->is_main_thread_for(this) && memory_reducer() != nullptr &&
      old_generation_capacity_after_bootstrap_ && ms_count_ == 0 &&
      OldGenerationCapacity() >= old_generation_capacity_after_bootstrap_ +
                                     kMemoryReducerActivationThreshold &&
      (notification_origin ==
       OldGenerationExpansionNotificationOrigin::kFromSameHeap) &&
      v8_flags.memory_reducer_for_small_heaps) {
    memory_reducer()->NotifyPossibleGarbage();
  }
}
References v8::internal::Isolate::AddCodeMemoryChunk(), v8::internal::MemoryChunkMetadata::Chunk(), DCHECK_NE, deserialization_complete(), v8::internal::BaseSpace::identity(), v8::internal::LocalHeap::is_main_thread_for(), v8::internal::IsAnyCodeSpace(), isolate(), kFromSameHeap, v8::internal::MemoryChunk::MarkNeverEvacuate(), v8::internal::MB, memory_reducer(), ms_count_, v8::internal::NEW_SPACE, v8::internal::MemoryReducer::NotifyPossibleGarbage(), old_generation_capacity_after_bootstrap_, OldGenerationCapacity(), v8::internal::MutablePageMetadata::owner(), space(), and v8::internal::v8_flags.
Referenced by v8::internal::OldLargeObjectSpace::AllocateRaw().
NumberOfDetachedContexts()
size_t v8::internal::Heap::NumberOfDetachedContexts ()
Definition at line 7225 of file heap.cc.
                                      {
  // The detached_contexts() array has two entries per detached context.
  return detached_contexts()->length() / 2;
}
NumberOfNativeContexts()
size_t v8::internal::Heap::NumberOfNativeContexts ()
Definition at line 7192 of file heap.cc.
                                    {
  int result = 0;
  Tagged<Object> context = native_contexts_list();
  while (!IsUndefined(context, isolate())) {
    ++result;
    Tagged<Context> native_context = Cast<Context>(context);
    context = native_context->next_context_link();
  }
  return result;
}
References isolate(), v8::internal::native_context, native_contexts_list(), and v8::base::internal::result.
NumberOfScavengeTasks()
int v8::internal::Heap::NumberOfScavengeTasks () [private]
NumberOfTrackedHeapObjectTypes()
size_t v8::internal::Heap::NumberOfTrackedHeapObjectTypes ()
Definition at line 7151 of file heap.cc.
                                            {
  return ObjectStats::OBJECT_STATS_COUNT;
}
References v8::internal::ObjectStats::OBJECT_STATS_COUNT.
ObjectCountAtLastGC()
size_t v8::internal::Heap::ObjectCountAtLastGC (size_t index)
Definition at line 7155 of file heap.cc.
                                             {
  if (live_object_stats_ == nullptr || index >= ObjectStats::OBJECT_STATS_COUNT)
    return 0;
  return live_object_stats_->object_count_last_gc(index);
}
References v8::internal::index, live_object_stats_, and v8::internal::ObjectStats::OBJECT_STATS_COUNT.
ObjectSizeAtLastGC()
size_t v8::internal::Heap::ObjectSizeAtLastGC (size_t index)
Definition at line 7161 of file heap.cc.
                                            {
  if (live_object_stats_ == nullptr || index >= ObjectStats::OBJECT_STATS_COUNT)
    return 0;
  return live_object_stats_->object_size_last_gc(index);
}
References v8::internal::index, live_object_stats_, and v8::internal::ObjectStats::OBJECT_STATS_COUNT.
old_generation_allocation_limit()
size_t v8::internal::Heap::old_generation_allocation_limit () const [inline], [private]
Definition at line 1983 of file heap.h.
                                                 {
    return old_generation_allocation_limit_.load(std::memory_order_relaxed);
  }
Referenced by AllocationLimitOvershotByLargeMargin(), EnsureMinimumRemainingAllocationLimit(), PercentToOldGenerationLimit(), v8::internal::GCTracer::PrintNVP(), RecomputeLimits(), RecomputeLimitsAfterLoadingIfNeeded(), ShrinkOldGenerationAllocationLimitIfNotConfigured(), v8::internal::IncrementalMarking::Start(), and v8::internal::IncrementalMarking::Stop().
old_space()
OldSpace* v8::internal::Heap::old_space () const [inline]
Definition at line 773 of file heap.h.
{ return old_space_; }
Referenced by v8::internal::Isolate::AddCrashKeysForIsolateAndHeapPointers(), v8::internal::PageMetadata::ConvertNewToOld(), DeactivateMajorGCInProgressFlag(), EnsureMinimumRemainingAllocationLimit(), EnsureSweepingCompleted(), v8::internal::EvacuationAllocator::Finalize(), GarbageCollectionEpilogueInSafepoint(), v8::internal::OldGenerationMemoryChunkIterator::next(), OldGenerationSizeOfObjects(), PrintFreeListsStats(), v8::internal::HeapAllocator::Setup(), ShrinkOldGenerationAllocationLimitIfNotConfigured(), v8::internal::MarkCompactCollector::StartCompaction(), sticky_space(), Unmark(), and v8::internal::MarkCompactCollector::VerifyMarking().
OldArrayBufferBytes()
size_t v8::internal::Heap::OldArrayBufferBytes ()
Definition at line 6972 of file heap.cc.
                                 {
  return array_buffer_sweeper()->OldBytes();
}
References array_buffer_sweeper(), and v8::internal::ArrayBufferSweeper::OldBytes().
OldGenerationAllocationCounter()
size_t v8::internal::Heap::OldGenerationAllocationCounter () [inline]
Definition at line 1398 of file heap.h.
                                          {
    return old_generation_allocation_counter_at_last_gc_ +
           PromotedSinceLastGC();
  }
Referenced by v8::internal::GCTracer::StartInSafepoint().
OldGenerationCapacity()
size_t v8::internal::Heap::OldGenerationCapacity () const
Definition at line 333 of file heap.cc.
                                         {
  if (!HasBeenSetUp()) return 0;
  PagedSpaceIterator spaces(this);
  size_t total = 0;
  for (PagedSpace* space = spaces.Next(); space != nullptr;
       space = spaces.Next()) {
    total += space->Capacity();
  }
  if (shared_lo_space_) {
    total += shared_lo_space_->SizeOfObjects();
  }
  return total + lo_space_->SizeOfObjects() + code_lo_space_->SizeOfObjects() +
         trusted_lo_space_->SizeOfObjects();
}
References code_lo_space_, HasBeenSetUp(), lo_space_, v8::internal::PagedSpaceIterator::Next(), shared_lo_space_, v8::internal::LargeObjectSpace::SizeOfObjects(), space(), and trusted_lo_space_.
Referenced by CanExpandOldGeneration(), Capacity(), IsOldGenerationExpansionAllowed(), NotifyBootstrapComplete(), and NotifyOldGenerationExpansion().
OldGenerationConsumedBytes()
size_t v8::internal::Heap::OldGenerationConsumedBytes () const
Definition at line 5381 of file heap.cc.
                                              {
  return OldGenerationSizeOfObjects() + OldGenerationWastedBytes();
}
References OldGenerationSizeOfObjects(), and OldGenerationWastedBytes().
Referenced by AllocationLimitOvershotByLargeMargin(), EnsureMinimumRemainingAllocationLimit(), PercentToOldGenerationLimit(), RecomputeLimits(), v8::internal::GCTracer::RecordGCSizeCounters(), and ShrinkOldGenerationAllocationLimitIfNotConfigured().
OldGenerationConsumedBytesAtLastGC()
size_t v8::internal::Heap::OldGenerationConsumedBytesAtLastGC () const
Definition at line 5435 of file heap.cc.
                                                      {
  return old_generation_size_at_last_gc_ + old_generation_wasted_at_last_gc_;
}
References old_generation_size_at_last_gc_, and old_generation_wasted_at_last_gc_.
Referenced by GlobalConsumedBytesAtLastGC(), and PercentToOldGenerationLimit().
OldGenerationLowMemory()
size_t v8::internal::Heap::OldGenerationLowMemory () [static]
Definition at line 5052 of file heap.cc.
                                    {
  return 128 * MB * HeapLimitMultiplier();
}
References HeapLimitMultiplier(), and v8::internal::MB.
Referenced by YoungGenerationSizeFromOldGenerationSize().
OldGenerationSizeOfObjects()
size_t v8::internal::Heap::OldGenerationSizeOfObjects () const
Definition at line 5351 of file heap.cc.
                                              {
  size_t total = 0;
  if (v8_flags.sticky_mark_bits)
    total += sticky_space()->old_objects_size();
  else
    total += old_space()->SizeOfObjects();
  total += lo_space()->SizeOfObjects();
  total += code_space()->SizeOfObjects();
  total += code_lo_space()->SizeOfObjects();
  if (shared_space()) {
    total += shared_space()->SizeOfObjects();
  }
  if (shared_lo_space()) {
    total += shared_lo_space()->SizeOfObjects();
  }
  total += trusted_space()->SizeOfObjects();
  total += trusted_lo_space()->SizeOfObjects();
  return total;
}
References code_lo_space(), code_space(), lo_space(), v8::internal::StickySpace::old_objects_size(), old_space(), shared_lo_space(), shared_space(), v8::internal::LargeObjectSpace::SizeOfObjects(), sticky_space(), trusted_lo_space(), trusted_space(), and v8::internal::v8_flags.
Referenced by CollectGarbage(), GlobalSizeOfObjects(), HasHighFragmentation(), v8::internal::MemoryBalancer::HeartbeatUpdate(), v8::internal::IncrementalMarking::IsBelowActivationThresholds(), MarkCompact(), OldGenerationConsumedBytes(), v8::internal::MemoryBalancer::RecomputeLimits(), RecomputeLimitsAfterLoadingIfNeeded(), v8::internal::IncrementalMarking::Start(), and v8::internal::IncrementalMarking::Stop().
OldGenerationSpaceAvailable()
size_t v8::internal::Heap::OldGenerationSpaceAvailable () [inline], [private]
Definition at line 1941 of file heap.h.
                                              {
    uint64_t bytes = OldGenerationConsumedBytes();
    if (!v8_flags.external_memory_accounted_in_global_limit) {
      // TODO(chromium:42203776): When not accounting external memory properly
      // in the global limit, just add allocated external bytes towards the
      // regular old gen bytes. This is historic behavior.
      bytes += AllocatedExternalMemorySinceMarkCompact();
    }
    if (old_generation_allocation_limit() <= bytes) return 0;
    return old_generation_allocation_limit() - static_cast<size_t>(bytes);
  }
References v8::internal::v8_flags.
Referenced by IncrementalMarkingLimitReached(), RecomputeLimitsAfterLoadingIfNeeded(), ShouldExpandOldGenerationOnSlowAllocation(), and StartIncrementalMarkingIfAllocationLimitIsReached().
OldGenerationToSemiSpaceRatio()
size_t v8::internal::Heap::OldGenerationToSemiSpaceRatio () [static]
Definition at line 5092 of file heap.cc.
                                           {
  DCHECK(!v8_flags.minor_ms);
  // Compute a ration such that when old gen max capacity is set to the highest
  // supported value, young gen max capacity would also be set to the max.
  const size_t max_semi_space_size = DefaultMaxSemiSpaceSize();
  DCHECK_GT(max_semi_space_size, 0);
  return DefaulMaxHeapSize() / max_semi_space_size;
}
References v8::internal::DCHECK(), DCHECK_GT, DefaulMaxHeapSize(), DefaultMaxSemiSpaceSize(), and v8::internal::v8_flags.
Referenced by YoungGenerationSizeFromOldGenerationSize().
OldGenerationToSemiSpaceRatioLowMemory()
size_t v8::internal::Heap::OldGenerationToSemiSpaceRatioLowMemory () [static]
Definition at line 5102 of file heap.cc.
                                                    {
  static const size_t old_generation_to_semi_space_ratio_low_memory =
      256 * HeapLimitMultiplier() / kPointerMultiplier;
  return old_generation_to_semi_space_ratio_low_memory /
         (v8_flags.minor_ms ? 2 : 1);
}
References HeapLimitMultiplier(), kPointerMultiplier, and v8::internal::v8_flags.
Referenced by YoungGenerationSizeFromOldGenerationSize().
OldGenerationWastedBytes()
size_t v8::internal::Heap::OldGenerationWastedBytes () const
Definition at line 5371 of file heap.cc.
                                            {
  PagedSpaceIterator spaces(this);
  size_t total = 0;
  for (PagedSpace* space = spaces.Next(); space != nullptr;
       space = spaces.Next()) {
    total += space->Waste();
  }
  return total;
}
References v8::internal::PagedSpaceIterator::Next(), and space().
Referenced by GlobalWastedBytes(), MarkCompact(), OldGenerationConsumedBytes(), RecomputeLimitsAfterLoadingIfNeeded(), v8::internal::IncrementalMarking::Start(), and v8::internal::IncrementalMarking::Stop().
OldSpaceAllocationLimitAddress()
Address * v8::internal::Heap::OldSpaceAllocationLimitAddress () [inline]
Definition at line 176 of file heap-inl.h.
                                              {
  return allocator()->old_space_allocator()->allocation_limit_address();
}
References v8::internal::MainAllocator::allocation_limit_address(), allocator(), and v8::internal::HeapAllocator::old_space_allocator().
Referenced by v8::internal::WasmTrustedInstanceData::New().
OldSpaceAllocationTopAddress()
Address * v8::internal::Heap::OldSpaceAllocationTopAddress () [inline]
Definition at line 172 of file heap-inl.h.
                                            {
  return allocator()->old_space_allocator()->allocation_top_address();
}
References v8::internal::MainAllocator::allocation_top_address(), allocator(), and v8::internal::HeapAllocator::old_space_allocator().
Referenced by v8::internal::WasmTrustedInstanceData::New().
OnMoveEvent()
void v8::internal::Heap::OnMoveEvent (Tagged< HeapObject > source, Tagged< HeapObject > target, int size_in_bytes)
Definition at line 3483 of file heap.cc.
                                          {
  if (heap_profiler()->is_tracking_object_moves()) {
    heap_profiler()->ObjectMoveEvent(source.address(), target.address(),
                                     size_in_bytes,
                                     /*is_embedder_object=*/false);
  }
  for (auto& tracker : allocation_trackers_) {
    tracker->MoveEvent(source.address(), target.address(), size_in_bytes);
  }
  if (IsSharedFunctionInfo(target, isolate_)) {
    LOG_CODE_EVENT(isolate_, SharedFunctionInfoMoveEvent(source.address(),
                                                         target.address()));
  } else if (IsNativeContext(target, isolate_)) {
    if (isolate_->current_embedder_state() != nullptr) {
      isolate_->current_embedder_state()->OnMoveEvent(source.address(),
                                                      target.address());
    }
    PROFILE(isolate_,
            NativeContextMoveEvent(source.address(), target.address()));
  } else if (IsMap(target, isolate_)) {
    LOG(isolate_, MapMoveEvent(Cast<Map>(source), Cast<Map>(target)));
  }
}
References v8::internal::Tagged< HeapObject >::address(), allocation_trackers_, heap_profiler(), isolate_, LOG, LOG_CODE_EVENT, v8::internal::HeapProfiler::ObjectMoveEvent(), and PROFILE.
Referenced by LeftTrimFixedArray(), v8::internal::Scavenger::MigrateObject(), and v8::internal::ProfilingMigrationObserver::Move().
operator=()
Heap& v8::internal::Heap::operator= (const Heap &) [private], [delete]
overridden_stack_state()
std::optional< StackState > v8::internal::Heap::overridden_stack_state () const
Definition at line 6243 of file heap.cc.
                                                           {
  if (!embedder_stack_state_origin_) return {};
  return embedder_stack_state_;
}
References embedder_stack_state_, and embedder_stack_state_origin_.
Referenced by v8::internal::CppHeap::DetachIsolate(), and v8::internal::CppHeap::overridden_stack_state().
paged_new_space()
PagedNewSpace * v8::internal::Heap::paged_new_space () const [inline]
Definition at line 426 of file heap-inl.h.
                                           {
  return PagedNewSpace::From(new_space());
}
References v8::internal::PagedNewSpace::From(), and new_space().
Referenced by EnsureSweepingCompleted(), EnsureYoungSweepingCompleted(), v8::internal::Sweeper::PrepareToBeSweptPage(), ReduceNewSpaceSize(), v8::internal::MinorMarkSweepCollector::StartMarking(), StartMinorMSConcurrentMarkingIfNeeded(), StartResizeNewSpace(), v8::internal::MinorMarkSweepCollector::StartSweepNewSpace(), v8::internal::MinorMarkSweepCollector::TraceFragmentation(), v8::internal::MarkCompactCollector::VerifyMarking(), and YoungGenerationWastedBytes().
paged_space()
PagedSpace * v8::internal::Heap::paged_space (int idx) const [inline]
Definition at line 152 of file heap-inl.h.
                                           {
  DCHECK(idx == OLD_SPACE || idx == CODE_SPACE || idx == SHARED_SPACE ||
         idx == TRUSTED_SPACE || idx == SHARED_TRUSTED_SPACE);
  return static_cast<PagedSpace*>(space_[idx].get());
}
References v8::internal::CODE_SPACE, v8::internal::DCHECK(), v8::internal::OLD_SPACE, v8::internal::SHARED_SPACE, v8::internal::SHARED_TRUSTED_SPACE, space_, and v8::internal::TRUSTED_SPACE.
Referenced by v8::internal::MainAllocator::FreeLinearAllocationAreaAndResetFreeList(), v8::internal::PagedSpaceIterator::Next(), v8::internal::Sweeper::PrepareToBeSweptPage(), and v8::internal::PagedSpaceAllocatorPolicy::RefillLab().
PauseConcurrentThreadsInClients()
std::vector< Isolate * > v8::internal::Heap::PauseConcurrentThreadsInClients (GarbageCollector collector) [private]
Definition at line 2449 of file heap.cc.
                                {
  std::vector<Isolate*> paused_clients;
  if (isolate()->is_shared_space_isolate()) {
    isolate()->global_safepoint()->IterateClientIsolates(
        [collector, &paused_clients](Isolate* client) {
          CHECK(client->heap()->deserialization_complete());
          if (v8_flags.concurrent_marking &&
              client->heap()->concurrent_marking()->Pause()) {
            paused_clients.push_back(client);
          }
          if (collector == GarbageCollector::MARK_COMPACTOR) {
            Sweeper* const client_sweeper = client->heap()->sweeper();
            client_sweeper->ContributeAndWaitForPromotedPagesIteration();
          }
        });
  }
  return paused_clients;
}
References CHECK, concurrent_marking(), v8::internal::Sweeper::ContributeAndWaitForPromotedPagesIteration(), deserialization_complete(), v8::internal::Isolate::global_safepoint(), v8::internal::Isolate::heap(), isolate(), v8::internal::GlobalSafepoint::IterateClientIsolates(), v8::internal::MARK_COMPACTOR, v8::internal::ConcurrentMarking::Pause(), sweeper(), and v8::internal::v8_flags.
Referenced by PerformGarbageCollection(), and StartIncrementalMarking().
PercentToGlobalMemoryLimit()
double v8::internal::Heap::PercentToGlobalMemoryLimit () const [private]
Definition at line 5628 of file heap.cc.
                                              {
  return PercentToLimit(GlobalConsumedBytesAtLastGC(), GlobalConsumedBytes(),
                        global_allocation_limit());
}
References global_allocation_limit(), GlobalConsumedBytes(), GlobalConsumedBytesAtLastGC(), and v8::internal::anonymous_namespace{heap.cc}::PercentToLimit().
Referenced by IncrementalMarkingLimitReached().
PercentToOldGenerationLimit()
double v8::internal::Heap::PercentToOldGenerationLimit () const [private]
Definition at line 5622 of file heap.cc.
                                               {
  return PercentToLimit(OldGenerationConsumedBytesAtLastGC(),
                        OldGenerationConsumedBytes(),
                        old_generation_allocation_limit());
}
References old_generation_allocation_limit(), OldGenerationConsumedBytes(), OldGenerationConsumedBytesAtLastGC(), and v8::internal::anonymous_namespace{heap.cc}::PercentToLimit().
Referenced by IncrementalMarkingLimitReached().
PerformGarbageCollection()
void v8::internal::Heap::PerformGarbageCollection (GarbageCollector collector, GarbageCollectionReason gc_reason, const char * collector_reason) [private]
Definition at line 2299 of file heap.cc.
                                                                  {
  if (IsYoungGenerationCollector(collector)) {
    if (v8_flags.sticky_mark_bits) {
      DCHECK_EQ(GarbageCollector::MINOR_MARK_SWEEPER, collector);
      // TODO(333906585): It's not necessary to complete full sweeping here.
      // Make sure that only the OLD_SPACE is swept.
      CompleteSweepingFull();
    } else {
      CompleteSweepingYoung();
      if (v8_flags.verify_heap) {
        // If heap verification is enabled, we want to ensure that sweeping is
        // completed here, as it will be triggered from Heap::Verify anyway.
        // In this way, sweeping finalization is accounted to the corresponding
        // full GC cycle.
        CompleteSweepingFull();
      }
    }
  } else {
    DCHECK_EQ(GarbageCollector::MARK_COMPACTOR, collector);
    CompleteSweepingFull();
  }
  const base::TimeTicks atomic_pause_start_time = base::TimeTicks::Now();
  std::optional<SafepointScope> safepoint_scope;
  {
    AllowGarbageCollection allow_shared_gc;
    safepoint_scope.emplace(isolate(), kGlobalSafepointForSharedSpaceIsolate);
  }
  if (!incremental_marking_->IsMarking() ||
      (collector == GarbageCollector::SCAVENGER)) {
    tracer()->StartCycle(collector, gc_reason, collector_reason,
                         GCTracer::MarkingType::kAtomic);
  }
  tracer()->StartAtomicPause();
  if ((!Heap::IsYoungGenerationCollector(collector) || v8_flags.minor_ms) &&
      incremental_marking_->IsMarking()) {
    DCHECK_IMPLIES(Heap::IsYoungGenerationCollector(collector),
                   incremental_marking_->IsMinorMarking());
    tracer()->UpdateCurrentEvent(gc_reason, collector_reason);
  }
  DCHECK(tracer()->IsConsistentWithCollector(collector));
  TRACE_GC_EPOCH(tracer(), CollectorScopeId(collector), ThreadKind::kMain);
  collection_barrier_->StopTimeToCollectionTimer();
  std::vector<Isolate*> paused_clients =
      PauseConcurrentThreadsInClients(collector);
  FreeLinearAllocationAreas();
  tracer()->StartInSafepoint(atomic_pause_start_time);
  GarbageCollectionPrologueInSafepoint(collector);
  PerformHeapVerification();
  const size_t start_young_generation_size =
      NewSpaceSize() + (new_lo_space() ? new_lo_space()->SizeOfObjects() : 0);
  // Make sure allocation observers are disabled until the new new space
  // capacity is set in the epilogue.
  PauseAllocationObserversScope pause_observers(this);
  const size_t new_space_capacity_before_gc = NewSpaceTargetCapacity();
  if (collector == GarbageCollector::MARK_COMPACTOR) {
    MarkCompact();
  } else if (collector == GarbageCollector::MINOR_MARK_SWEEPER) {
    MinorMarkSweep();
  } else {
    DCHECK_EQ(GarbageCollector::SCAVENGER, collector);
    Scavenge();
  }
  // We don't want growing or shrinking of the current cycle to affect
  // pretenuring decisions. The numbers collected in the GC will be for the
  // capacity that was set before the GC.
  pretenuring_handler_.ProcessPretenuringFeedback(new_space_capacity_before_gc);
  UpdateSurvivalStatistics(static_cast<int>(start_young_generation_size));
  ShrinkOldGenerationAllocationLimitIfNotConfigured();
  isolate_->counters()->objs_since_last_young()->Set(0);
  isolate_->eternal_handles()->PostGarbageCollectionProcessing();
  // Update relocatables.
  Relocatable::PostGarbageCollectionProcessing(isolate_);
  if (isolate_->is_shared_space_isolate()) {
    // Allows handle derefs for all threads/isolates from this thread.
    AllowHandleUsageOnAllThreads allow_all_handle_derefs;
    isolate()->global_safepoint()->IterateClientIsolates([](Isolate* client) {
      Relocatable::PostGarbageCollectionProcessing(client);
    });
  }
  // First round weak callbacks are not supposed to allocate and trigger
  // nested GCs.
  isolate_->global_handles()->InvokeFirstPassWeakCallbacks();
  if (cpp_heap() && (collector == GarbageCollector::MARK_COMPACTOR ||
                     collector == GarbageCollector::MINOR_MARK_SWEEPER)) {
    // TraceEpilogue may trigger operations that invalidate global handles. It
    // has to be called *after* all other operations that potentially touch
    // and reset global handles. It is also still part of the main garbage
    // collection pause and thus needs to be called *before* any operation
    // that can potentially trigger recursive garbage collections.
    TRACE_GC(tracer(), GCTracer::Scope::HEAP_EMBEDDER_TRACING_EPILOGUE);
    CppHeap::From(cpp_heap())->CompactAndSweep();
  }
  if (collector == GarbageCollector::MARK_COMPACTOR) {
    ClearStubCaches(isolate());
  }
  PerformHeapVerification();
  GarbageCollectionEpilogueInSafepoint(collector);
  const base::TimeTicks atomic_pause_end_time = base::TimeTicks::Now();
  tracer()->StopInSafepoint(atomic_pause_end_time);
  ResumeConcurrentThreadsInClients(std::move(paused_clients));
  // After every full GC the old generation allocation limit should be
  // configured.
  DCHECK_IMPLIES(!IsYoungGenerationCollector(collector),
                 !using_initial_limit());
}
References v8::internal::anonymous_namespace{heap.cc}::ClearStubCaches(), collection_barrier_, v8::internal::anonymous_namespace{heap.cc}::CollectorScopeId(), v8::internal::CppHeap::CompactAndSweep(), CompleteSweepingFull(), CompleteSweepingYoung(), v8::internal::Isolate::counters(), cpp_heap(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::Isolate::eternal_handles(), FreeLinearAllocationAreas(), v8::internal::CppHeap::From(), GarbageCollectionEpilogueInSafepoint(), GarbageCollectionPrologueInSafepoint(), v8::internal::Isolate::global_handles(), v8::internal::Isolate::global_safepoint(), incremental_marking_, v8::internal::GlobalHandles::InvokeFirstPassWeakCallbacks(), v8::internal::Isolate::is_shared_space_isolate(), isolate(), isolate_, IsYoungGenerationCollector(), v8::internal::GlobalSafepoint::IterateClientIsolates(), v8::internal::GCTracer::kAtomic, v8::internal::kGlobalSafepointForSharedSpaceIsolate, v8::internal::kMain, v8::internal::MARK_COMPACTOR, MarkCompact(), v8::internal::MINOR_MARK_SWEEPER, MinorMarkSweep(), new_lo_space(), NewSpaceSize(), NewSpaceTargetCapacity(), v8::base::TimeTicks::Now(), PauseConcurrentThreadsInClients(), PerformHeapVerification(), v8::internal::EternalHandles::PostGarbageCollectionProcessing(), v8::internal::Relocatable::PostGarbageCollectionProcessing(), pretenuring_handler_, v8::internal::PretenuringHandler::ProcessPretenuringFeedback(), ResumeConcurrentThreadsInClients(), Scavenge(), v8::internal::SCAVENGER, ShrinkOldGenerationAllocationLimitIfNotConfigured(), v8::internal::LargeObjectSpace::SizeOfObjects(), v8::internal::GCTracer::StartAtomicPause(), v8::internal::GCTracer::StartCycle(), v8::internal::GCTracer::StartInSafepoint(), v8::internal::GCTracer::StopInSafepoint(), TRACE_GC, TRACE_GC_EPOCH, tracer(), v8::internal::GCTracer::UpdateCurrentEvent(), UpdateSurvivalStatistics(), using_initial_limit(), and v8::internal::v8_flags.
Referenced by CollectGarbage().
PerformHeapVerification()
void v8::internal::Heap::PerformHeapVerification () [private]
Definition at line 2436 of file heap.cc.
                                   {
  HeapVerifier::VerifyHeapIfEnabled(this);
  if (isolate()->is_shared_space_isolate()) {
    // Allow handle creation for client isolates even if they are parked. This
    // is because some object verification methods create handles.
    AllowHandleUsageOnAllThreads allow_handle_creation;
    isolate()->global_safepoint()->IterateClientIsolates([](Isolate* client) {
      HeapVerifier::VerifyHeapIfEnabled(client->heap());
    });
  }
}
References v8::internal::Isolate::global_safepoint(), v8::internal::Isolate::heap(), isolate(), v8::internal::GlobalSafepoint::IterateClientIsolates(), and v8::internal::HeapVerifier::VerifyHeapIfEnabled().
Referenced by PerformGarbageCollection().
PostFinalizationRegistryCleanupTaskIfNeeded()
void v8::internal::Heap::PostFinalizationRegistryCleanupTaskIfNeeded ()
Definition at line 7039 of file heap.cc.
                                                       {
  // Only one cleanup task is posted at a time.
  if (!HasDirtyJSFinalizationRegistries() ||
      is_finalization_registry_cleanup_task_posted_) {
    return;
  }
  auto task = std::make_unique<FinalizationRegistryCleanupTask>(this);
  task_runner_->PostNonNestableTask(std::move(task));
  is_finalization_registry_cleanup_task_posted_ = true;
}
References HasDirtyJSFinalizationRegistries(), is_finalization_registry_cleanup_task_posted_, and task_runner_.
Referenced by v8::internal::FinalizationRegistryCleanupTask::RunInternal().
PrecedeWithFiller()
Tagged< HeapObject > v8::internal::Heap::PrecedeWithFiller (Tagged< HeapObject > object, int filler_size)
Definition at line 3157 of file heap.cc.
                                                            {
  CreateFillerObjectAt(object.address(), filler_size);
  return HeapObject::FromAddress(object.address() + filler_size);
}
References CreateFillerObjectAt(), and v8::internal::HeapObject::FromAddress().
Referenced by v8::internal::MainAllocator::AllocateFastAligned(), and v8::internal::ReadOnlySpace::TryAllocateLinearlyAligned().
PrecedeWithFillerBackground()
Tagged< HeapObject > v8::internal::Heap::PrecedeWithFillerBackground (Tagged< HeapObject > object, int filler_size)
Definition at line 3163 of file heap.cc.
                                                                      {
  CreateFillerObjectAtBackground(
      WritableFreeSpace::ForNonExecutableMemory(object.address(), filler_size));
  return HeapObject::FromAddress(object.address() + filler_size);
}
References CreateFillerObjectAtBackground(), v8::internal::WritableFreeSpace::ForNonExecutableMemory(), and v8::internal::HeapObject::FromAddress().
Referenced by AlignWithFillerBackground().
PreciseCollectAllGarbage()
void v8::internal::Heap::PreciseCollectAllGarbage (GCFlags gc_flags, GarbageCollectionReason gc_reason, const GCCallbackFlags gc_callback_flags = kNoGCCallbackFlags)
Definition at line 1446 of file heap.cc.
                                                                             {
  FinalizeIncrementalMarkingAtomicallyIfRunning(gc_reason);
  CollectAllGarbage(gc_flags, gc_reason, gc_callback_flags);
}
References CollectAllGarbage(), and FinalizeIncrementalMarkingAtomicallyIfRunning().
Referenced by v8::internal::compiler::CompilationDependencies::Commit(), v8::internal::HeapObjectsMap::UpdateHeapObjectsMap(), and wasm::StoreImpl::~StoreImpl().
pretenuring_handler()
PretenuringHandler* v8::internal::Heap::pretenuring_handler () [inline]
Definition at line 1683 of file heap.h.
{ return &pretenuring_handler_; }
Referenced by v8::internal::ConcurrentMarking::FlushPretenuringFeedback(), and v8::internal::MinorMarkSweepCollector::MarkLiveObjects().
PrintFreeListsStats()
void v8::internal::Heap::PrintFreeListsStats ()
Definition at line 678 of file heap.cc.
                               {
  DCHECK(v8_flags.trace_gc_freelists);
  if (v8_flags.trace_gc_freelists_verbose) {
    PrintIsolate(isolate_,
                 "Freelists statistics per Page: "
                 "[category: length || total free bytes]\n");
  }
  std::vector<int> categories_lengths(
      old_space()->free_list()->number_of_categories(), 0);
  std::vector<size_t> categories_sums(
      old_space()->free_list()->number_of_categories(), 0);
  unsigned int pageCnt = 0;
  // This loops computes freelists lengths and sum.
  // If v8_flags.trace_gc_freelists_verbose is enabled, it also prints
  // the stats of each FreeListCategory of each Page.
  for (PageMetadata* page : *old_space()) {
    std::ostringstream out_str;
    if (v8_flags.trace_gc_freelists_verbose) {
      out_str << "Page " << std::setw(4) << pageCnt;
    }
    for (int cat = kFirstCategory;
         cat <= old_space()->free_list()->last_category(); cat++) {
      FreeListCategory* free_list =
          page->free_list_category(static_cast<FreeListCategoryType>(cat));
      int length = free_list->FreeListLength();
      size_t sum = free_list->SumFreeList();
      if (v8_flags.trace_gc_freelists_verbose) {
        out_str << "[" << cat << ": " << std::setw(4) << length << " || "
                << std::setw(6) << sum << " ]"
                << (cat == old_space()->free_list()->last_category() ? "\n"
                                                                     : ", ");
      }
      categories_lengths[cat] += length;
      categories_sums[cat] += sum;
    }
    if (v8_flags.trace_gc_freelists_verbose) {
      PrintIsolate(isolate_, "%s", out_str.str().c_str());
    }
    pageCnt++;
  }
  // Print statistics about old_space (pages, free/wasted/used memory...).
  PrintIsolate(
      isolate_,
      "%d pages. Free space: %.1f MB (waste: %.2f). "
      "Usage: %.1f/%.1f (MB) -> %.2f%%.\n",
      pageCnt, static_cast<double>(old_space_->Available()) / MB,
      static_cast<double>(old_space_->Waste()) / MB,
      static_cast<double>(old_space_->Size()) / MB,
      static_cast<double>(old_space_->Capacity()) / MB,
      static_cast<double>(old_space_->Size()) / old_space_->Capacity() * 100);
  // Print global statistics of each FreeListCategory (length & sum).
  PrintIsolate(isolate_,
               "FreeLists global statistics: "
               "[category: length || total free KB]\n");
  std::ostringstream out_str;
  for (int cat = kFirstCategory;
       cat <= old_space()->free_list()->last_category(); cat++) {
    out_str << "[" << cat << ": " << categories_lengths[cat] << " || "
            << std::fixed << std::setprecision(2)
            << static_cast<double>(categories_sums[cat]) / KB << " KB]"
            << (cat == old_space()->free_list()->last_category() ? "\n" : ", ");
  }
  PrintIsolate(isolate_, "%s", out_str.str().c_str());
}
References v8::internal::PagedSpaceBase::Available(), v8::internal::PagedSpaceBase::Capacity(), v8::internal::DCHECK(), v8::internal::FreeListCategory::FreeListLength(), isolate_, v8::internal::KB, v8::internal::kFirstCategory, v8::internal::length, v8::internal::MB, old_space(), old_space_, v8::internal::PrintIsolate(), v8::internal::PagedSpaceBase::Size(), v8::internal::FreeListCategory::SumFreeList(), v8::internal::v8_flags, and v8::internal::PagedSpaceBase::Waste().
Referenced by v8::internal::GCTracer::NotifyFullSweepingCompletedAndStopCycleIfFinished(), and v8::internal::GCTracer::StopCycle().
PrintMaxMarkingLimitReached()
void v8::internal::Heap::PrintMaxMarkingLimitReached () [private]
Definition at line 6118 of file heap.cc.
                                       {
  PrintF("\n### Maximum marking limit reached = %.02lf\n",
         max_marking_limit_reached_.load(std::memory_order_relaxed));
}
References max_marking_limit_reached_, and v8::internal::PrintF().
Referenced by TearDown().
PrintMaxNewSpaceSizeReached()
void v8::internal::Heap::PrintMaxNewSpaceSizeReached () [private]
Definition at line 6123 of file heap.cc.
                                       {
  PrintF("\n### Maximum new space size reached = %.02lf\n",
         stress_scavenge_observer_->MaxNewSpaceSizeReached());
}
References v8::internal::StressScavengeObserver::MaxNewSpaceSizeReached(), v8::internal::PrintF(), and stress_scavenge_observer_.
Referenced by TearDown().
PrintShortHeapStatistics()
void v8::internal::Heap::PrintShortHeapStatistics ()
Definition at line 577 of file heap.cc.
                                    {
  if (!v8_flags.trace_gc_verbose) return;
  PrintIsolate(isolate_,
               "Memory allocator, used: %6zu KB"
               ", available: %7zu KB\n",
               memory_allocator()->Size() / KB,
               memory_allocator()->Available() / KB);
  PrintIsolate(isolate_,
               "Read-only space, used: %6zu KB"
               ", available: %7zu KB"
               ", committed: %6zu KB\n",
               read_only_space_->Size() / KB, size_t{0},
               read_only_space_->CommittedMemory() / KB);
  PrintIsolate(isolate_,
               "New space, used: %6zu KB"
               ", available:%c %7zu KB"
               ", committed: %6zu KB\n",
               NewSpaceSize() / KB,
               (v8_flags.minor_ms && minor_sweeping_in_progress()) ? '*' : ' ',
               new_space_->Available() / KB,
               new_space_->CommittedMemory() / KB);
  PrintIsolate(isolate_,
               "New large object space, used: %6zu KB"
               ", available: %7zu KB"
               ", committed: %6zu KB\n",
               new_lo_space_->SizeOfObjects() / KB,
               new_lo_space_->Available() / KB,
               new_lo_space_->CommittedMemory() / KB);
  PrintIsolate(isolate_,
               "Old space, used: %6zu KB"
               ", available:%c %7zu KB"
               ", committed: %6zu KB\n",
               old_space_->SizeOfObjects() / KB,
               major_sweeping_in_progress() ? '*' : ' ',
               old_space_->Available() / KB,
               old_space_->CommittedMemory() / KB);
  PrintIsolate(isolate_,
               "Code space, used: %6zu KB"
               ", available:%c %7zu KB"
               ", committed: %6zu KB\n",
               code_space_->SizeOfObjects() / KB,
               major_sweeping_in_progress() ? '*' : ' ',
               code_space_->Available() / KB,
               code_space_->CommittedMemory() / KB);
  PrintIsolate(isolate_,
               "Large object space, used: %6zu KB"
               ", available: %7zu KB"
               ", committed: %6zu KB\n",
               lo_space_->SizeOfObjects() / KB, lo_space_->Available() / KB,
               lo_space_->CommittedMemory() / KB);
  PrintIsolate(isolate_,
               "Code large object space, used: %6zu KB"
               ", available: %7zu KB"
               ", committed: %6zu KB\n",
               code_lo_space_->SizeOfObjects() / KB,
               code_lo_space_->Available() / KB,
               code_lo_space_->CommittedMemory() / KB);
  PrintIsolate(isolate_,
               "Trusted space, used: %6zu KB"
               ", available:%c %7zu KB"
               ", committed: %6zu KB\n",
               trusted_space_->SizeOfObjects() / KB,
               major_sweeping_in_progress() ? '*' : ' ',
               trusted_space_->Available() / KB,
               trusted_space_->CommittedMemory() / KB);
  PrintIsolate(isolate_,
               "Trusted large object space, used: %6zu KB"
               ", available: %7zu KB"
               ", committed: %6zu KB\n",
               trusted_lo_space_->SizeOfObjects() / KB,
               trusted_lo_space_->Available() / KB,
               trusted_lo_space_->CommittedMemory() / KB);
  ReadOnlySpace* const ro_space = read_only_space_;
  PrintIsolate(isolate_,
               "All spaces, used: %6zu KB"
               ", available:%c %7zu KB"
               ", committed: %6zu KB\n",
               (this->SizeOfObjects() + ro_space->Size()) / KB,
               sweeping_in_progress() ? '*' : ' ', (this->Available()) / KB,
               (this->CommittedMemory() + ro_space->CommittedMemory()) / KB);
  const size_t chunks = memory_allocator()->GetPooledChunksCount();
  PrintIsolate(isolate_, "Pool buffering %4zu chunk(s) of committed: %7zu KB\n",
               chunks, (chunks * PageMetadata::kPageSize) / KB);
  PrintIsolate(isolate_,
               "External memory reported: %7" PRId64 " KB\n",
               external_memory() / KB);
  PrintIsolate(isolate_,
               "Backing store memory: %7" PRIu64 " KB\n",
               backing_store_bytes() / KB);
  PrintIsolate(isolate_, "External memory global: %7zu KB\n",
               external_memory_callback_() / KB);
  PrintIsolate(isolate_,
               "Total time spent in GC: %7.1f ms\n",
               total_gc_time_ms_.InMillisecondsF());
  if (sweeping_in_progress()) {
    PrintIsolate(isolate_,
                 "(*) Sweeping is still in progress, making available sizes "
                 "inaccurate.\n");
  }
}
References Available(), v8::internal::LargeObjectSpace::Available(), v8::internal::NewLargeObjectSpace::Available(), v8::internal::PagedSpaceBase::Available(), backing_store_bytes(), code_lo_space_, code_space_, CommittedMemory(), v8::internal::BaseSpace::CommittedMemory(), external_memory(), external_memory_callback_, v8::internal::MemoryAllocator::GetPooledChunksCount(), v8::base::TimeDelta::InMillisecondsF(), isolate_, v8::internal::KB, v8::internal::MutablePageMetadata::kPageSize, lo_space_, major_sweeping_in_progress(), memory_allocator(), minor_sweeping_in_progress(), new_lo_space_, new_space_, NewSpaceSize(), old_space_, v8::internal::PrintIsolate(), read_only_space_, v8::internal::ReadOnlySpace::Size(), SizeOfObjects(), v8::internal::LargeObjectSpace::SizeOfObjects(), sweeping_in_progress(), total_gc_time_ms_, trusted_lo_space_, trusted_space_, and v8::internal::v8_flags.
Referenced by v8::internal::GCTracer::StopObservablePause().
ProcessAllocationSites()
void v8::internal::Heap::ProcessAllocationSites (WeakObjectRetainer * retainer) [private]
Definition at line 3026 of file heap.cc.
                                                              {
  Tagged<Object> allocation_site_obj =
      VisitWeakList<AllocationSiteWithWeakNext>(this, allocation_sites_list(),
                                                retainer);
  set_allocation_sites_list(
      Cast<UnionOf<Undefined, AllocationSiteWithWeakNext>>(
          allocation_site_obj));
}
References allocation_sites_list(), v8::internal::Cast(), set_allocation_sites_list(), and v8::internal::VisitWeakList< AllocationSiteWithWeakNext >().
Referenced by ProcessAllWeakReferences().
ProcessAllWeakReferences()
void v8::internal::Heap::ProcessAllWeakReferences (WeakObjectRetainer * retainer) [private]
Definition at line 3013 of file heap.cc.
                                                                {
  ProcessNativeContexts(retainer);
  ProcessAllocationSites(retainer);
  ProcessDirtyJSFinalizationRegistries(retainer);
}
References ProcessAllocationSites(), ProcessDirtyJSFinalizationRegistries(), and ProcessNativeContexts().
ProcessDirtyJSFinalizationRegistries()
void v8::internal::Heap::ProcessDirtyJSFinalizationRegistries (WeakObjectRetainer * retainer) [private]
Definition at line 3035 of file heap.cc.
                                                                            {
  Tagged<Object> head = VisitWeakList<JSFinalizationRegistry>(
      this, dirty_js_finalization_registries_list(), retainer);
  set_dirty_js_finalization_registries_list(head);
  // If the list is empty, set the tail to undefined. Otherwise the tail is set
  // by WeakListVisitor<JSFinalizationRegistry>::VisitLiveObject.
  if (IsUndefined(head, isolate())) {
    set_dirty_js_finalization_registries_list_tail(head);
  }
}
References dirty_js_finalization_registries_list(), isolate(), set_dirty_js_finalization_registries_list(), set_dirty_js_finalization_registries_list_tail(), and v8::internal::VisitWeakList< JSFinalizationRegistry >().
Referenced by ProcessAllWeakReferences().
ProcessNativeContexts()
void v8::internal::Heap::ProcessNativeContexts (WeakObjectRetainer * retainer) [private]
Definition at line 3019 of file heap.cc.
                                                             {
  Tagged<Object> head =
      VisitWeakList<Context>(this, native_contexts_list(), retainer);
  // Update the head of the list of contexts.
  set_native_contexts_list(head);
}
References native_contexts_list(), set_native_contexts_list(), and v8::internal::VisitWeakList< Context >().
Referenced by ProcessAllWeakReferences().
ProcessWeakListRoots()
void v8::internal::Heap::ProcessWeakListRoots (WeakObjectRetainer * retainer) [private]
Definition at line 3046 of file heap.cc.
                                                            {
  set_native_contexts_list(retainer->RetainAs(native_contexts_list()));
  set_allocation_sites_list(
      Cast<UnionOf<Smi, Undefined, AllocationSiteWithWeakNext>>(
          retainer->RetainAs(allocation_sites_list())));
  set_dirty_js_finalization_registries_list(
      retainer->RetainAs(dirty_js_finalization_registries_list()));
  set_dirty_js_finalization_registries_list_tail(
      retainer->RetainAs(dirty_js_finalization_registries_list_tail()));
}
References allocation_sites_list(), v8::internal::Cast(), dirty_js_finalization_registries_list(), dirty_js_finalization_registries_list_tail(), native_contexts_list(), v8::internal::WeakObjectRetainer::RetainAs(), set_allocation_sites_list(), set_dirty_js_finalization_registries_list(), set_dirty_js_finalization_registries_list_tail(), and set_native_contexts_list().
promoted_objects_size()
size_t v8::internal::Heap::promoted_objects_size () [inline]
Definition at line 1362 of file heap.h.
{ return promoted_objects_size_; }
Referenced by v8::internal::GCTracer::PrintNVP().
PromotedSinceLastGC()
size_t v8::internal::Heap::PromotedSinceLastGC () [inline], [private]
Definition at line 2126 of file heap.h.
                               {
    size_t old_generation_size = OldGenerationSizeOfObjects();
    return old_generation_size > old_generation_size_at_last_gc_
               ? old_generation_size - old_generation_size_at_last_gc_
               : 0;
  }
PublishMainThreadPendingAllocations()
void v8::internal::Heap::PublishMainThreadPendingAllocations ()
Definition at line 1040 of file heap.cc.
                                               {
  allocator()->PublishPendingAllocations();
}
References allocator(), and v8::internal::HeapAllocator::PublishPendingAllocations().
Referenced by v8::internal::maglev::MaglevCompilationInfo::MaglevCompilationInfo(), v8::internal::compiler::PipelineCompilationJob::PrepareJobImpl(), and v8::internal::IncrementalMarking::Step().
ReachedHeapLimit()
bool v8::internal::Heap::ReachedHeapLimit () [private]
Definition at line 1809 of file heap.cc.
{ return !CanExpandOldGeneration(0); }
References CanExpandOldGeneration().
Referenced by CheckHeapLimitReached(), CollectAllAvailableGarbage(), and CollectGarbageWithRetry().
read_only_space()
ReadOnlySpace* v8::internal::Heap::read_only_space () const [inline]
Definition at line 781 of file heap.h.
{ return read_only_space_; }
Referenced by v8::internal::Isolate::AddCrashKeysForIsolateAndHeapPointers(), v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::CopyToReadOnlyHeap(), v8::internal::SnapshotCreatorImpl::CreateBlob(), CreateReadOnlyHeapObjects(), v8::internal::ETWJITInterface::EtwIsolateOperations::HeapReadOnlySpaceWritable(), v8::internal::Deserializer< IsolateT >::ReadReadOnlyHeapRef(), v8::internal::Serializer::SerializeReadOnlyObjectReference(), v8::internal::ReadOnlyArtifacts::VerifyHeapAndSpaceRelationships(), and v8::internal::SnapshotCreatorImpl::~SnapshotCreatorImpl().
RecomputeLimits()
void v8::internal::Heap::RecomputeLimits (GarbageCollector collector, base::TimeTicks time) [private]
Definition at line 2614 of file heap.cc.
                                                                         {
  if (IsYoungGenerationCollector(collector) &&
      !HasLowYoungGenerationAllocationRate()) {
    return;
  }
  if (using_initial_limit()) {
    DCHECK(IsYoungGenerationCollector(collector));
    return;
  }
  auto new_limits = ComputeNewAllocationLimits(this);
  size_t new_old_generation_allocation_limit =
      new_limits.old_generation_allocation_limit;
  size_t new_global_allocation_limit = new_limits.global_allocation_limit;
  if (collector == GarbageCollector::MARK_COMPACTOR) {
    if (v8_flags.memory_balancer) {
      // Now recompute the new allocation limit.
      mb_->RecomputeLimits(new_limits.global_allocation_limit -
                               new_limits.old_generation_allocation_limit,
                           time);
    } else {
      SetOldGenerationAndGlobalAllocationLimit(
          new_limits.old_generation_allocation_limit,
          new_limits.global_allocation_limit);
    }
    CheckIneffectiveMarkCompact(
        OldGenerationConsumedBytes(),
        tracer()->AverageMarkCompactMutatorUtilization());
  } else {
    DCHECK(HasLowYoungGenerationAllocationRate());
    new_old_generation_allocation_limit = std::min(
        new_old_generation_allocation_limit, old_generation_allocation_limit());
    new_global_allocation_limit =
        std::min(new_global_allocation_limit, global_allocation_limit());
    SetOldGenerationAndGlobalAllocationLimit(
        new_old_generation_allocation_limit, new_global_allocation_limit);
  }
  CHECK_EQ(max_global_memory_size_,
           GlobalMemorySizeFromV8Size(max_old_generation_size_));
  CHECK_GE(global_allocation_limit(), old_generation_allocation_limit_);
}
References CHECK_EQ, CHECK_GE, CheckIneffectiveMarkCompact(), ComputeNewAllocationLimits(), v8::internal::DCHECK(), global_allocation_limit(), v8::internal::anonymous_namespace{heap.cc}::GlobalMemorySizeFromV8Size(), HasLowYoungGenerationAllocationRate(), IsYoungGenerationCollector(), v8::internal::MARK_COMPACTOR, max_global_memory_size_, max_old_generation_size_, mb_, old_generation_allocation_limit(), old_generation_allocation_limit_, OldGenerationConsumedBytes(), SetOldGenerationAndGlobalAllocationLimit(), v8::internal::time, tracer(), using_initial_limit(), and v8::internal::v8_flags.
Referenced by CollectGarbage().
RecomputeLimitsAfterLoadingIfNeeded()
void v8::internal::Heap::RecomputeLimitsAfterLoadingIfNeeded () [private]
Definition at line 2659 of file heap.cc.
                                               {
  if (!update_allocation_limits_after_loading_) {
    return;
  }
  if ((OldGenerationSpaceAvailable() > 0) && (GlobalMemoryAvailable() > 0)) {
    // Only recompute limits if memory accumulated during loading may lead to
    // atomic GC. If there is still room to allocate, keep the current limits.
    DCHECK(!AllocationLimitOvershotByLargeMargin());
    update_allocation_limits_after_loading_ = false;
    return;
  }
  if (!incremental_marking()->IsMajorMarking()) {
    // Incremental marking should have started already but was delayed. Don't
    // update the limits yet to not delay starting incremental marking any
    // further. Limits will be updated on incremental marking start, with the
    // intention to give more slack and avoid an immediate large finalization
    // pause.
    return;
  }
  update_allocation_limits_after_loading_ = false;
  UpdateOldGenerationAllocationCounter();
  old_generation_size_at_last_gc_ = OldGenerationSizeOfObjects();
  old_generation_wasted_at_last_gc_ = OldGenerationWastedBytes();
  external_memory_.UpdateLowSinceMarkCompact(external_memory_.total());
  embedder_size_at_last_gc_ = EmbedderSizeOfObjects();
  set_using_initial_limit(false);
  auto new_limits = ComputeNewAllocationLimits(this);
  size_t new_old_generation_allocation_limit =
      new_limits.old_generation_allocation_limit;
  size_t new_global_allocation_limit = new_limits.global_allocation_limit;
  new_old_generation_allocation_limit = std::max(
      new_old_generation_allocation_limit, old_generation_allocation_limit());
  new_global_allocation_limit =
      std::max(new_global_allocation_limit, global_allocation_limit());
  SetOldGenerationAndGlobalAllocationLimit(new_old_generation_allocation_limit,
                                           new_global_allocation_limit);
  CHECK_EQ(max_global_memory_size_,
           GlobalMemorySizeFromV8Size(max_old_generation_size_));
  CHECK_GE(global_allocation_limit(), old_generation_allocation_limit_);
}
References AllocationLimitOvershotByLargeMargin(), CHECK_EQ, CHECK_GE, ComputeNewAllocationLimits(), v8::internal::DCHECK(), embedder_size_at_last_gc_, EmbedderSizeOfObjects(), external_memory_, global_allocation_limit(), GlobalMemoryAvailable(), v8::internal::anonymous_namespace{heap.cc}::GlobalMemorySizeFromV8Size(), incremental_marking(), max_global_memory_size_, max_old_generation_size_, old_generation_allocation_limit(), old_generation_allocation_limit_, old_generation_size_at_last_gc_, old_generation_wasted_at_last_gc_, OldGenerationSizeOfObjects(), OldGenerationSpaceAvailable(), OldGenerationWastedBytes(), set_using_initial_limit(), SetOldGenerationAndGlobalAllocationLimit(), v8::internal::Heap::ExternalMemoryAccounting::total(), update_allocation_limits_after_loading_, v8::internal::Heap::ExternalMemoryAccounting::UpdateLowSinceMarkCompact(), and UpdateOldGenerationAllocationCounter().
Referenced by NotifyLoadingEnded(), and StartIncrementalMarking().
RecordStats()
void v8::internal::Heap::RecordStats (HeapStats * stats)
Definition at line 5325 of file heap.cc.
                                       {
  stats->start_marker = HeapStats::kStartMarker;
  stats->end_marker = HeapStats::kEndMarker;
  stats->ro_space_size = read_only_space_->Size();
  stats->ro_space_capacity = read_only_space_->Capacity();
  stats->new_space_size = NewSpaceSize();
  stats->new_space_capacity = NewSpaceCapacity();
  stats->old_space_size = old_space_->SizeOfObjects();
  stats->old_space_capacity = old_space_->Capacity();
  stats->code_space_size = code_space_->SizeOfObjects();
  stats->code_space_capacity = code_space_->Capacity();
  stats->map_space_size = 0;
  stats->map_space_capacity = 0;
  stats->lo_space_size = lo_space_->Size();
  stats->code_lo_space_size = code_lo_space_->Size();
  isolate_->global_handles()->RecordStats(stats);
  stats->memory_allocator_size = memory_allocator()->Size();
  stats->memory_allocator_capacity =
      memory_allocator()->Size() + memory_allocator()->Available();
  stats->os_error = base::OS::GetLastError();
  // TODO(leszeks): Include the string table in both current and peak usage.
  stats->malloced_memory = isolate_->allocator()->GetCurrentMemoryUsage();
  stats->malloced_peak_memory = isolate_->allocator()->GetMaxMemoryUsage();
  GetFromRingBuffer(stats->last_few_messages);
}
References v8::internal::Isolate::allocator(), v8::internal::MemoryAllocator::Available(), v8::internal::PagedSpaceBase::Capacity(), v8::internal::ReadOnlySpace::Capacity(), code_lo_space_, v8::internal::HeapStats::code_lo_space_size, code_space_, v8::internal::HeapStats::code_space_capacity, v8::internal::HeapStats::code_space_size, v8::internal::HeapStats::end_marker, v8::internal::AccountingAllocator::GetCurrentMemoryUsage(), GetFromRingBuffer(), v8::base::OS::GetLastError(), v8::internal::AccountingAllocator::GetMaxMemoryUsage(), v8::internal::Isolate::global_handles(), isolate_, v8::internal::HeapStats::kEndMarker, v8::internal::HeapStats::kStartMarker, v8::internal::HeapStats::last_few_messages, lo_space_, v8::internal::HeapStats::lo_space_size, v8::internal::HeapStats::malloced_memory, v8::internal::HeapStats::malloced_peak_memory, v8::internal::HeapStats::map_space_capacity, v8::internal::HeapStats::map_space_size, memory_allocator(), v8::internal::HeapStats::memory_allocator_capacity, v8::internal::HeapStats::memory_allocator_size, v8::internal::HeapStats::new_space_capacity, v8::internal::HeapStats::new_space_size, NewSpaceCapacity(), NewSpaceSize(), old_space_, v8::internal::HeapStats::old_space_capacity, v8::internal::HeapStats::old_space_size, v8::internal::HeapStats::os_error, read_only_space_, v8::internal::GlobalHandles::RecordStats(), v8::internal::HeapStats::ro_space_capacity, v8::internal::HeapStats::ro_space_size, v8::internal::MemoryAllocator::Size(), v8::internal::LargeObjectSpace::Size(), v8::internal::ReadOnlySpace::Size(), and v8::internal::HeapStats::start_marker.
ReduceNewSpaceSize()
void v8::internal::Heap::ReduceNewSpaceSize () [private]
Definition at line 4025 of file heap.cc.
                              {
  if (!v8_flags.minor_ms) {
    const size_t reduced_capacity = ComputeReducedNewSpaceSize(new_space());
    semi_space_new_space()->Shrink(reduced_capacity);
  } else {
    // MinorMS starts shrinking new space as part of sweeping.
    paged_new_space()->FinishShrinking();
  }
  new_lo_space_->SetCapacity(new_space()->TotalCapacity());
}
References v8::internal::anonymous_namespace{heap.cc}::ComputeReducedNewSpaceSize(), v8::internal::PagedNewSpace::FinishShrinking(), new_lo_space_, new_space(), paged_new_space(), semi_space_new_space(), v8::internal::NewLargeObjectSpace::SetCapacity(), v8::internal::SemiSpaceNewSpace::Shrink(), and v8::internal::v8_flags.
Referenced by ReduceNewSpaceSizeForTesting(), and ResizeNewSpace().
ReduceNewSpaceSizeForTesting()
void v8::internal::Heap::ReduceNewSpaceSizeForTesting ()
Definition at line 4006 of file heap.cc.
{ ReduceNewSpaceSize(); }
References ReduceNewSpaceSize().
RegisterExternalString()
void v8::internal::Heap::RegisterExternalString (Tagged< String > string) [inline]
Definition at line 213 of file heap-inl.h.
                                                       {
  DCHECK(IsExternalString(string));
  DCHECK(!IsThinString(string));
  external_string_table_.AddString(string);
}
References v8::internal::Heap::ExternalStringTable::AddString(), v8::internal::DCHECK(), external_string_table_, v8::internal::InstanceTypeChecker::IsExternalString(), and v8::internal::InstanceTypeChecker::IsThinString().
Referenced by v8::internal::Factory::InternalizeExternalString(), v8::internal::String::MakeExternal(), v8::internal::String::MakeExternalDuringGC(), v8::internal::Factory::NewExternalStringFromOneByte(), v8::internal::Factory::NewExternalStringFromTwoByte(), and v8::internal::anonymous_namespace{deserializer.cc}::PostProcessExternalString().
RegisterStrongRoots()
StrongRootsEntry * v8::internal::Heap::RegisterStrongRoots (const char * label, FullObjectSlot start, FullObjectSlot end)
Definition at line 6976 of file heap.cc.
                                                                {
  // We're either on the main thread, or in a background thread with an active
  // local heap.
  DCHECK(isolate()->CurrentLocalHeap()->IsRunning());
  base::MutexGuard guard(&strong_roots_mutex_);
  StrongRootsEntry* entry = new StrongRootsEntry(label);
  entry->start = start;
  entry->end = end;
  entry->prev = nullptr;
  entry->next = strong_roots_head_;
  if (strong_roots_head_) {
    DCHECK_NULL(strong_roots_head_->prev);
    strong_roots_head_->prev = entry;
  }
  strong_roots_head_ = entry;
  return entry;
}
References v8::internal::DCHECK(), DCHECK_NULL, v8::internal::compiler::end(), v8::internal::StrongRootsEntry::end, isolate(), v8::internal::StrongRootsEntry::next, v8::internal::StrongRootsEntry::prev, v8::internal::StrongRootsEntry::start, strong_roots_head_, and strong_roots_mutex_.
Referenced by v8::internal::StrongRootAllocatorBase::allocate_impl(), and v8::internal::IdentityMapBase::InsertEntry().
RememberUnmappedPage()
void v8::internal::Heap::RememberUnmappedPage (Address page, bool compacted)
Definition at line 6947 of file heap.cc.
                                                            {
  // Tag the page pointer to make it findable in the dump file.
  if (compacted) {
    page ^= 0xC1EAD & (PageMetadata::kPageSize - 1); // Cleared.
  } else {
    page ^= 0x1D1ED & (PageMetadata::kPageSize - 1); // I died.
  }
  remembered_unmapped_pages_[remembered_unmapped_pages_index_] = page;
  remembered_unmapped_pages_index_++;
  remembered_unmapped_pages_index_ %= kRememberedUnmappedPages;
}
References v8::internal::MutablePageMetadata::kPageSize, kRememberedUnmappedPages, remembered_unmapped_pages_, and remembered_unmapped_pages_index_.
Referenced by Heap(), and v8::internal::MemoryAllocator::PreFreeMemory().
RemoveAllocationObserversFromAllSpaces()
void v8::internal::Heap::RemoveAllocationObserversFromAllSpaces (AllocationObserver * observer, AllocationObserver * new_space_observer)
Definition at line 1034 of file heap.cc.
                                                                          {
  DCHECK(observer && new_space_observer);
  allocator()->RemoveAllocationObserver(observer, new_space_observer);
}
References allocator(), v8::internal::DCHECK(), and v8::internal::HeapAllocator::RemoveAllocationObserver().
Referenced by v8::internal::StressConcurrentAllocationObserver::Step(), TearDown(), and v8::internal::SamplingHeapProfiler::~SamplingHeapProfiler().
RemoveDirtyFinalizationRegistriesOnContext()
void v8::internal::Heap::RemoveDirtyFinalizationRegistriesOnContext (Tagged< NativeContext > context)
Definition at line 7097 of file heap.cc.
                                   {
  DisallowGarbageCollection no_gc;
  Isolate* isolate = this->isolate();
  Tagged<Object> prev = ReadOnlyRoots(isolate).undefined_value();
  Tagged<Object> current = dirty_js_finalization_registries_list();
  while (!IsUndefined(current, isolate)) {
    Tagged<JSFinalizationRegistry> finalization_registry =
        Cast<JSFinalizationRegistry>(current);
    if (finalization_registry->native_context() == context) {
      if (IsUndefined(prev, isolate)) {
        set_dirty_js_finalization_registries_list(
            finalization_registry->next_dirty());
      } else {
        Cast<JSFinalizationRegistry>(prev)->set_next_dirty(
            finalization_registry->next_dirty());
      }
      finalization_registry->set_scheduled_for_cleanup(false);
      current = finalization_registry->next_dirty();
      finalization_registry->set_next_dirty(
          ReadOnlyRoots(isolate).undefined_value());
    } else {
      prev = current;
      current = finalization_registry->next_dirty();
    }
  }
  set_dirty_js_finalization_registries_list_tail(prev);
}
References dirty_js_finalization_registries_list(), isolate(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, ReadOnlyRoots, set_dirty_js_finalization_registries_list(), and set_dirty_js_finalization_registries_list_tail().
Referenced by NotifyContextDisposed().
RemoveGCEpilogueCallback()
void v8::internal::Heap::RemoveGCEpilogueCallback (v8::Isolate::GCCallbackWithData callback, void * data)
Definition at line 6452 of file heap.cc.
                                                {
  gc_epilogue_callbacks_.Remove(callback, data);
}
References gc_epilogue_callbacks_, and v8::internal::GCCallbacks::Remove().
Referenced by v8::Isolate::RemoveGCEpilogueCallback().
RemoveGCPrologueCallback()
void v8::internal::Heap::RemoveGCPrologueCallback (v8::Isolate::GCCallbackWithData callback, void * data)
Definition at line 6441 of file heap.cc.
                                                {
  gc_prologue_callbacks_.Remove(callback, data);
}
References gc_prologue_callbacks_, and v8::internal::GCCallbacks::Remove().
Referenced by v8::Isolate::RemoveGCPrologueCallback().
RemoveHeapObjectAllocationTracker()
void v8::internal::Heap::RemoveHeapObjectAllocationTracker (HeapObjectAllocationTracker * tracker)
Definition at line 931 of file heap.cc.
                                          {
  allocation_trackers_.erase(std::remove(allocation_trackers_.begin(),
                                         allocation_trackers_.end(), tracker),
                             allocation_trackers_.end());
  if (allocation_trackers_.empty()) {
    isolate_->UpdateLogObjectRelocation();
  }
  if (allocation_trackers_.empty() && v8_flags.inline_new) {
    EnableInlineAllocation();
  }
}
References allocation_trackers_, EnableInlineAllocation(), isolate_, v8::internal::Isolate::UpdateLogObjectRelocation(), and v8::internal::v8_flags.
Referenced by v8::internal::HeapProfiler::StopHeapObjectsTracking(), v8::internal::Debug::StopSideEffectCheckMode(), and v8::internal::Heap::AllocationTrackerForDebugging::~AllocationTrackerForDebugging().
RemoveNearHeapLimitCallback()
void v8::internal::Heap::RemoveNearHeapLimitCallback (v8::NearHeapLimitCallback callback, size_t heap_limit)
Definition at line 4370 of file heap.cc.
                                                          {
  for (size_t i = 0; i < near_heap_limit_callbacks_.size(); i++) {
    if (near_heap_limit_callbacks_[i].first == callback) {
      near_heap_limit_callbacks_.erase(near_heap_limit_callbacks_.begin() + i);
      if (heap_limit) {
        RestoreHeapLimit(heap_limit);
      }
      return;
    }
  }
  UNREACHABLE();
}
References near_heap_limit_callbacks_, RestoreHeapLimit(), and v8::internal::UNREACHABLE().
Referenced by v8::Isolate::RemoveNearHeapLimitCallback().
ReplaceReadOnlySpace()
void v8::internal::Heap::ReplaceReadOnlySpace (SharedReadOnlySpace * shared_ro_space)
Definition at line 5860 of file heap.cc.
                                                          {
  if (read_only_space_) {
    read_only_space_->TearDown(memory_allocator());
    delete read_only_space_;
  }
  read_only_space_ = space;
  heap_allocator_->SetReadOnlySpace(read_only_space_);
}
References heap_allocator_, memory_allocator(), read_only_space_, v8::internal::HeapAllocator::SetReadOnlySpace(), space(), and v8::internal::ReadOnlySpace::TearDown().
Referenced by v8::internal::ReadOnlyArtifacts::ReinstallReadOnlySpace().
ReportStatisticsAfterGC()
void v8::internal::Heap::ReportStatisticsAfterGC () [private]
Definition at line 812 of file heap.cc.
                                   {
  if (deferred_counters_.empty()) return;
  // Move the contents into a new SmallVector first, in case
  // {Isolate::CountUsage} puts the counters into {deferred_counters_} again.
  decltype(deferred_counters_) to_report = std::move(deferred_counters_);
  DCHECK(deferred_counters_.empty());
  isolate()->CountUsage(base::VectorOf(to_report));
}
References v8::internal::Isolate::CountUsage(), v8::internal::DCHECK(), deferred_counters_, v8::base::SmallVector< T, kSize, Allocator >::empty(), isolate(), and v8::base::VectorOf().
Referenced by GarbageCollectionEpilogue().
ResetAllAllocationSitesDependentCode()
void v8::internal::Heap::ResetAllAllocationSitesDependentCode (AllocationType allocation) [private]
Definition at line 3076 of file heap.cc.
                                                                         {
  DisallowGarbageCollection no_gc_scope;
  bool marked = false;
  ForeachAllocationSite(
      allocation_sites_list(),
      [&marked, allocation, this](Tagged<AllocationSite> site) {
        if (site->GetAllocationType() == allocation) {
          site->ResetPretenureDecision();
          site->set_deopt_dependent_code(true);
          marked = true;
          pretenuring_handler_.RemoveAllocationSitePretenuringFeedback(site);
          return;
        }
      });
  if (marked) isolate_->stack_guard()->RequestDeoptMarkedAllocationSites();
}
References allocation_sites_list(), ForeachAllocationSite(), isolate_, and v8::internal::Isolate::stack_guard().
Referenced by EvaluateOldSpaceLocalPretenuring().
ResetOldGenerationAndGlobalAllocationLimit()
void v8::internal::Heap::ResetOldGenerationAndGlobalAllocationLimit () [private]
Definition at line 1586 of file heap.cc.
                                                      {
  DCHECK_IMPLIES(initial_size_overwritten_, !configured_);
  SetOldGenerationAndGlobalAllocationLimit(
      initial_old_generation_size_,
      GlobalMemorySizeFromV8Size(initial_old_generation_size_));
  set_using_initial_limit(true);
}
References configured_, DCHECK_IMPLIES, v8::internal::anonymous_namespace{heap.cc}::GlobalMemorySizeFromV8Size(), initial_old_generation_size_, initial_size_overwritten_, set_using_initial_limit(), and SetOldGenerationAndGlobalAllocationLimit().
Referenced by ConfigureHeap(), and NotifyContextDisposed().
ResizeArrayBufferExtension()
void v8::internal::Heap::ResizeArrayBufferExtension (ArrayBufferExtension * extension, int64_t delta)
Definition at line 4389 of file heap.cc.
                                                     {
  // ArrayBufferSweeper is managing all counters and updating Heap counters.
  array_buffer_sweeper_->Resize(extension, delta);
}
References array_buffer_sweeper_.
Referenced by v8::internal::ResizeHelper().
ResizeNewSpace()
void v8::internal::Heap::ResizeNewSpace () [private]
Definition at line 3987 of file heap.cc.
                          {
  DCHECK_IMPLIES(!v8_flags.minor_ms,
                 resize_new_space_mode_ == ResizeNewSpaceMode::kNone);
  const ResizeNewSpaceMode mode =
      v8_flags.minor_ms ? resize_new_space_mode_ : ShouldResizeNewSpace();
  resize_new_space_mode_ = ResizeNewSpaceMode::kNone;
  switch (mode) {
    case ResizeNewSpaceMode::kShrink:
      ReduceNewSpaceSize();
      break;
    case ResizeNewSpaceMode::kGrow:
      ExpandNewSpaceSize();
      break;
    case ResizeNewSpaceMode::kNone:
      break;
  }
}
References DCHECK_IMPLIES, ExpandNewSpaceSize(), kGrow, kNone, kShrink, mode(), ReduceNewSpaceSize(), resize_new_space_mode_, ShouldResizeNewSpace(), and v8::internal::v8_flags.
Referenced by v8::internal::MarkCompactCollector::Finish(), and v8::internal::MinorMarkSweepCollector::Finish().
RestoreHeapLimit()
void v8::internal::Heap::RestoreHeapLimit (size_t heap_limit) [inline]
Definition at line 707 of file heap.h.
                                           {
    // Do not set the limit lower than the live size + some slack.
    size_t min_limit = SizeOfObjects() + SizeOfObjects() / 4;
    SetOldGenerationAndGlobalMaximumSize(
        std::min(max_old_generation_size(), std::max(heap_limit, min_limit)));
  }
Referenced by RemoveNearHeapLimitCallback().
ResumeConcurrentThreadsInClients()
void v8::internal::Heap::ResumeConcurrentThreadsInClients (std::vector< Isolate * > paused_clients) [private]
Definition at line 2473 of file heap.cc.
                                        {
  if (isolate()->is_shared_space_isolate()) {
    for (Isolate* client : paused_clients) {
      client->heap()->concurrent_marking()->Resume();
    }
  } else {
    DCHECK(paused_clients.empty());
  }
}
References v8::internal::DCHECK(), and isolate().
Referenced by PerformGarbageCollection().
RightTrimArray()
template<typename Array >
void v8::internal::Heap::RightTrimArray (Tagged< Array > object, int new_capacity, int old_capacity)
Definition at line 3592 of file heap.cc.
                                            {
  DCHECK_EQ(old_capacity, object->capacity());
  DCHECK_LT(new_capacity, old_capacity);
  DCHECK_GE(new_capacity, 0);
  if constexpr (Array::kElementsAreMaybeObject) {
    // For MaybeObject elements, this function is safe to use only at the end
    // of the mark compact collection: When marking, we record the weak slots,
    // and shrinking invalidates them.
    DCHECK_EQ(gc_state(), MARK_COMPACT);
  }
  const int bytes_to_trim = (old_capacity - new_capacity) * Array::kElementSize;
  // Calculate location of new array end.
  const int old_size = Array::SizeFor(old_capacity);
  DCHECK_EQ(object->AllocatedSize(), old_size);
  Address old_end = object.address() + old_size;
  Address new_end = old_end - bytes_to_trim;
  const bool clear_slots = MayContainRecordedSlots(object);
  // Technically in new space this write might be omitted (except for debug
  // mode which iterates through the heap), but to play safer we still do it.
  // We do not create a filler for objects in a large object space.
  if (!IsLargeObject(object)) {
    NotifyObjectSizeChange(
        object, old_size, old_size - bytes_to_trim,
        clear_slots ? ClearRecordedSlots::kYes : ClearRecordedSlots::kNo);
    if (!v8_flags.black_allocated_pages) {
      Tagged<HeapObject> filler = HeapObject::FromAddress(new_end);
      // Clear the mark bits of the black area that belongs now to the filler.
      // This is an optimization. The sweeper will release black fillers anyway.
      if (incremental_marking()->black_allocation() &&
          marking_state()->IsMarked(filler)) {
        PageMetadata* page = PageMetadata::FromAddress(new_end);
        page->marking_bitmap()->ClearRange<AccessMode::ATOMIC>(
            MarkingBitmap::AddressToIndex(new_end),
            MarkingBitmap::LimitAddressToIndex(new_end + bytes_to_trim));
      }
    }
  } else if (clear_slots) {
    // Large objects are not swept, so it is not necessary to clear the
    // recorded slot.
    MemsetTagged(ObjectSlot(new_end), Tagged<Object>(kClearedFreeMemoryValue),
                 (old_end - new_end) / kTaggedSize);
  }
  // Initialize header of the trimmed array. We are storing the new capacity
  // using release store after creating a filler for the left-over space to
  // avoid races with the sweeper thread.
  object->set_capacity(new_capacity, kReleaseStore);
  // Notify the heap object allocation tracker of change in object layout. The
  // array may not be moved during GC, and size has to be adjusted nevertheless.
  for (auto& tracker : allocation_trackers_) {
    tracker->UpdateObjectSizeEvent(object.address(),
                                   Array::SizeFor(new_capacity));
  }
}
References v8::internal::MarkingBitmap::AddressToIndex(), allocation_trackers_, v8::internal::ATOMIC, v8::internal::MarkingBitmap::ClearRange(), DCHECK_EQ, DCHECK_GE, DCHECK_LT, v8::internal::PageMetadata::FromAddress(), v8::internal::HeapObject::FromAddress(), gc_state(), incremental_marking(), IsLargeObject(), v8::internal::kClearedFreeMemoryValue, v8::internal::kNo, v8::kReleaseStore, v8::internal::kTaggedSize, v8::internal::kYes, v8::internal::MarkingBitmap::LimitAddressToIndex(), MARK_COMPACT, v8::internal::MutablePageMetadata::marking_bitmap(), marking_state(), v8::internal::anonymous_namespace{heap.cc}::MayContainRecordedSlots(), v8::internal::MemsetTagged(), NotifyObjectSizeChange(), and v8::internal::v8_flags.
Referenced by v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::DecreaseLength(), v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::DeleteAtEnd(), and v8::internal::TaggedArrayBase< Derived, ShapeT, Super >::RightTrim().
roots_table()
RootsTable & v8::internal::Heap::roots_table () [inline]
Definition at line 69 of file heap-inl.h.
{ return isolate()->roots_table(); }
References isolate(), and v8::internal::Isolate::roots_table().
Referenced by CreateEarlyReadOnlyMapsAndObjects(), CreateImportantReadOnlyObjects(), CreateLateReadOnlyNonJSReceiverMaps(), CreateReadOnlyObjects(), IterateRoots(), IterateSmiRoots(), NextScriptId(), SetFunctionsMarkedForManualOptimization(), SetMessageListeners(), SetRootMaterializedObjects(), and SetRootScriptList().
safepoint()
IsolateSafepoint* v8::internal::Heap::safepoint () [inline]
Definition at line 622 of file heap.h.
{ return safepoint_.get(); }
Referenced by v8::internal::Isolate::Deinit(), v8::internal::StringTable::DropOldData(), FreeLinearAllocationAreas(), FreeSharedLinearAllocationAreasAndResetFreeLists(), GarbageCollectionEpilogueInSafepoint(), v8::internal::PersistentHandlesList::Iterate(), v8::internal::StringTable::IterateElements(), v8::internal::GlobalSafepoint::LeaveGlobalSafepointScope(), v8::internal::LocalHeap::LocalHeap(), v8::internal::String::MakeExternalDuringGC(), MakeLinearAllocationAreasIterable(), MarkSharedLinearAllocationAreasBlack(), NotifyDeserializationComplete(), v8::internal::StringTable::NotifyElementsRemoved(), v8::internal::LocalHeap::ParkSlowPath(), v8::internal::IncrementalMarking::PauseBlackAllocation(), v8::internal::StringForwardingTable::Reset(), v8::internal::PerClientSafepointData::safepoint(), v8::internal::LocalHeap::SetUpSharedMarking(), v8::internal::LocalHeap::SleepInSafepoint(), v8::internal::LocalHeap::SleepInUnpark(), v8::internal::IncrementalMarking::StartBlackAllocation(), TearDown(), TearDownWithSharedHeap(), UnmarkSharedLinearAllocationAreas(), and v8::internal::LocalHeap::~LocalHeap().
Scavenge()
void v8::internal::Heap::Scavenge () [private]
Definition at line 2800 of file heap.cc.
                    {
  DCHECK_NOT_NULL(new_space());
  DCHECK(!incremental_marking()->IsMarking());
  TRACE_GC(tracer(), GCTracer::Scope::SCAVENGER_SCAVENGE);
  SetGCState(SCAVENGE);
  // Implements Cheney's copying algorithm
  scavenger_collector_->CollectGarbage();
  SetGCState(NOT_IN_GC);
}
References v8::internal::DCHECK(), DCHECK_NOT_NULL, incremental_marking(), new_space(), NOT_IN_GC, SCAVENGE, scavenger_collector_, SetGCState(), TRACE_GC, and tracer().
Referenced by PerformGarbageCollection().
SelectGarbageCollector()
GarbageCollector v8::internal::Heap::SelectGarbageCollector (AllocationSpace space, GarbageCollectionReason gc_reason, const char ** reason) const [private]
Definition at line 473 of file heap.cc.
                                                                         {
  if (gc_reason == GarbageCollectionReason::kFinalizeMinorMSForMajorGC) {
    DCHECK_NE(static_cast<bool>(new_space()),
              v8_flags.sticky_mark_bits.value());
    DCHECK(!ShouldReduceMemory());
    *reason = "MinorMS finalization for starting major GC";
    return GarbageCollector::MINOR_MARK_SWEEPER;
  }
  if (gc_reason == GarbageCollectionReason::kFinalizeConcurrentMinorMS) {
    DCHECK_NE(static_cast<bool>(new_space()),
              v8_flags.sticky_mark_bits.value());
    DCHECK(!ShouldReduceMemory());
    *reason = "Concurrent MinorMS needs finalization";
    return GarbageCollector::MINOR_MARK_SWEEPER;
  }
  // Is global GC requested?
  if (space != NEW_SPACE && space != NEW_LO_SPACE) {
    isolate_->counters()->gc_compactor_caused_by_request()->Increment();
    *reason = "GC in old space requested";
    return GarbageCollector::MARK_COMPACTOR;
  }
  if (v8_flags.gc_global || ShouldStressCompaction() || !use_new_space()) {
    *reason = "GC in old space forced by flags";
    return GarbageCollector::MARK_COMPACTOR;
  }
  if (incremental_marking()->IsMajorMarking()) {
    *reason = "Incremental marking forced finalization";
    return GarbageCollector::MARK_COMPACTOR;
  }
  if (!CanPromoteYoungAndExpandOldGeneration(0)) {
    isolate_->counters()
        ->gc_compactor_caused_by_oldspace_exhaustion()
        ->Increment();
    *reason = "scavenge might not succeed";
    return GarbageCollector::MARK_COMPACTOR;
  }
  DCHECK(!v8_flags.single_generation);
  DCHECK(!v8_flags.gc_global);
  // Default
  *reason = nullptr;
  return YoungGenerationCollector();
}
References CanPromoteYoungAndExpandOldGeneration(), v8::internal::Isolate::counters(), v8::internal::DCHECK(), DCHECK_NE, incremental_marking(), isolate_, v8::internal::kFinalizeConcurrentMinorMS, v8::internal::kFinalizeMinorMSForMajorGC, v8::internal::MARK_COMPACTOR, v8::internal::MINOR_MARK_SWEEPER, v8::internal::NEW_LO_SPACE, v8::internal::NEW_SPACE, new_space(), ShouldReduceMemory(), ShouldStressCompaction(), space(), use_new_space(), v8::internal::v8_flags, and YoungGenerationCollector().
Referenced by CollectGarbage().
semi_space_new_space()
SemiSpaceNewSpace * v8::internal::Heap::semi_space_new_space () const [inline]
Definition at line 430 of file heap-inl.h.
                                                    {
  return SemiSpaceNewSpace::From(new_space());
}
References v8::internal::SemiSpaceNewSpace::From(), and new_space().
Referenced by CanPromoteYoungAndExpandOldGeneration(), v8::internal::SemiSpace::MoveQuarantinedPage(), v8::internal::GCTracer::PrintNVP(), ReduceNewSpaceSize(), YoungGenerationConsumedBytes(), and v8::internal::anonymous_namespace{scavenger.cc}::YoungGenerationConservativeStackVisitor::~YoungGenerationConservativeStackVisitor().
SemiSpaceSizeFromYoungGenerationSize()
size_t v8::internal::Heap::SemiSpaceSizeFromYoungGenerationSize (size_t young_generation_size) [static]
Definition at line 320 of file heap.cc.
                                  {
  return young_generation_size /
         (NumberOfSemiSpaces() + kNewLargeObjectSpaceToSemiSpaceRatio);
}
References kNewLargeObjectSpaceToSemiSpaceRatio, and v8::internal::anonymous_namespace{heap.cc}::NumberOfSemiSpaces().
Referenced by ConfigureHeap().
set_allocation_sites_list()
void v8::internal::Heap::set_allocation_sites_list (Tagged< UnionOf< Smi, Undefined, AllocationSiteWithWeakNext >> object) [inline]
Definition at line 509 of file heap.h.
                                                                          {
    allocation_sites_list_ = object;
  }
Referenced by CreateMutableHeapObjects(), v8::internal::StartupDeserializer::DeserializeIntoIsolate(), v8::internal::Factory::NewAllocationSite(), ProcessAllocationSites(), and ProcessWeakListRoots().
set_dirty_js_finalization_registries_list()
void v8::internal::Heap::set_dirty_js_finalization_registries_list (Tagged< Object > object) [inline]
Definition at line 518 of file heap.h.
                                                                        {
    dirty_js_finalization_registries_list_ = object;
  }
Referenced by CreateMutableHeapObjects(), DequeueDirtyJSFinalizationRegistry(), v8::internal::StartupDeserializer::DeserializeIntoIsolate(), EnqueueDirtyJSFinalizationRegistry(), ProcessDirtyJSFinalizationRegistries(), ProcessWeakListRoots(), and RemoveDirtyFinalizationRegistriesOnContext().
set_dirty_js_finalization_registries_list_tail()
void v8::internal::Heap::set_dirty_js_finalization_registries_list_tail (Tagged< Object > object) [inline]
Definition at line 524 of file heap.h.
                                                                             {
    dirty_js_finalization_registries_list_tail_ = object;
  }
Referenced by CreateMutableHeapObjects(), DequeueDirtyJSFinalizationRegistry(), v8::internal::StartupDeserializer::DeserializeIntoIsolate(), EnqueueDirtyJSFinalizationRegistry(), ProcessDirtyJSFinalizationRegistries(), ProcessWeakListRoots(), and RemoveDirtyFinalizationRegistriesOnContext().
set_force_gc_on_next_allocation()
void v8::internal::Heap::set_force_gc_on_next_allocation () [inline], [private]
Definition at line 2102 of file heap.h.
                                         {
    force_gc_on_next_allocation_ = true;
  }
set_force_oom()
void v8::internal::Heap::set_force_oom (bool value) [inline], [private]
Definition at line 2101 of file heap.h.
{ force_oom_ = value; }
References v8::internal::value.
set_is_finalization_registry_cleanup_task_posted()
void v8::internal::Heap::set_is_finalization_registry_cleanup_task_posted (bool posted) [inline]
Definition at line 945 of file heap.h.
                                                                     {
    is_finalization_registry_cleanup_task_posted_ = posted;
  }
Referenced by v8::internal::FinalizationRegistryCleanupTask::RunInternal().
set_native_contexts_list()
void v8::internal::Heap::set_native_contexts_list (Tagged< Object > object) [inline]
Definition at line 500 of file heap.h.
                                                       {
    native_contexts_list_.store(object.ptr(), std::memory_order_release);
  }
Referenced by CreateMutableHeapObjects(), v8::internal::StartupDeserializer::DeserializeIntoIsolate(), Heap(), ProcessNativeContexts(), and ProcessWeakListRoots().
set_old_generation_allocation_counter_at_last_gc()
void v8::internal::Heap::set_old_generation_allocation_counter_at_last_gc (size_t new_value) [inline]
Definition at line 1406 of file heap.h.
                                                                          {
    old_generation_allocation_counter_at_last_gc_ = new_value;
  }
set_using_initial_limit()
void v8::internal::Heap::set_using_initial_limit (bool value) [inline], [private]
Definition at line 1995 of file heap.h.
                                           {
    using_initial_limit_.store(value, std::memory_order_relaxed);
  }
References v8::internal::value.
Referenced by EnsureMinimumRemainingAllocationLimit(), MarkCompact(), RecomputeLimitsAfterLoadingIfNeeded(), and ResetOldGenerationAndGlobalAllocationLimit().
SetBasicBlockProfilingData()
void v8::internal::Heap::SetBasicBlockProfilingData (DirectHandle< ArrayList > list)
Definition at line 173 of file heap.cc.
                                                                  {
  set_basic_block_profiling_data(*list);
}
SetBuiltinsConstantsTable()
void v8::internal::Heap::SetBuiltinsConstantsTable (Tagged< FixedArray > cache)
Definition at line 7027 of file heap.cc.
                                                             {
  set_builtins_constants_table(cache);
}
Referenced by v8::internal::BuiltinsConstantsTableBuilder::Finalize().
SetConstructStubCreateDeoptPCOffset()
void v8::internal::Heap::SetConstructStubCreateDeoptPCOffset (int pc_offset)
Definition at line 142 of file heap.cc.
                                                            {
  DCHECK_EQ(Smi::zero(), construct_stub_create_deopt_pc_offset());
  set_construct_stub_create_deopt_pc_offset(Smi::FromInt(pc_offset));
}
References DCHECK_EQ, v8::internal::Smi::FromInt(), and v8::internal::Smi::zero().
SetConstructStubInvokeDeoptPCOffset()
void v8::internal::Heap::SetConstructStubInvokeDeoptPCOffset (int pc_offset)
Definition at line 147 of file heap.cc.
                                                            {
  DCHECK_EQ(Smi::zero(), construct_stub_invoke_deopt_pc_offset());
  set_construct_stub_invoke_deopt_pc_offset(Smi::FromInt(pc_offset));
}
References DCHECK_EQ, v8::internal::Smi::FromInt(), and v8::internal::Smi::zero().
SetDeoptPCOffsetAfterAdaptShadowStack()
void v8::internal::Heap::SetDeoptPCOffsetAfterAdaptShadowStack (int pc_offset)
Definition at line 152 of file heap.cc.
                                                              {
  DCHECK((Smi::zero() == deopt_pc_offset_after_adapt_shadow_stack()) ||
         (pc_offset == deopt_pc_offset_after_adapt_shadow_stack().value()));
  set_deopt_pc_offset_after_adapt_shadow_stack(Smi::FromInt(pc_offset));
}
References v8::internal::DCHECK(), v8::internal::Smi::FromInt(), v8::internal::value, and v8::internal::Smi::zero().
SetDetachedContexts()
void v8::internal::Heap::SetDetachedContexts (Tagged< WeakArrayList > detached_contexts)
Definition at line 7031 of file heap.cc.
                                                                      {
  set_detached_contexts(detached_contexts);
}
Referenced by v8::internal::anonymous_namespace{startup-serializer.cc}::SanitizeIsolateScope::SanitizeIsolateScope().
SetDoubleStringCache()
void v8::internal::Heap::SetDoubleStringCache (Tagged< DoubleStringCache > cache) [inline]
Definition at line 139 of file heap-inl.h.
                                                               {
  set_double_string_cache(cache);
}
Referenced by v8::internal::DoubleStringCache::Set().
SetEmbedderRootsHandler()
void v8::internal::Heap::SetEmbedderRootsHandler (EmbedderRootsHandler * handler)
Definition at line 6226 of file heap.cc.
                                                                {
  embedder_roots_handler_ = handler;
}
References embedder_roots_handler_.
Referenced by v8::Isolate::SetEmbedderRootsHandler().
SetFunctionsMarkedForManualOptimization()
void v8::internal::Heap::SetFunctionsMarkedForManualOptimization (Tagged< Object > bytecode) [inline]
Definition at line 129 of file heap-inl.h.
                                                                            {
  DCHECK(IsObjectHashTable(hash_table) || IsUndefined(hash_table, isolate()));
  roots_table()[RootIndex::kFunctionsMarkedForManualOptimization] =
      hash_table.ptr();
}
References v8::internal::DCHECK(), isolate(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), and roots_table().
Referenced by v8::internal::Snapshot::ClearReconstructableDataForSerialization(), and v8::internal::ManualOptimizationTable::MarkFunctionForManualOptimization().
SetGCState()
void v8::internal::Heap::SetGCState (HeapState state)
Definition at line 523 of file heap.cc.
                                     {
  gc_state_.store(state, std::memory_order_relaxed);
}
References gc_state_.
Referenced by MarkCompact(), MarkCompactEpilogue(), MinorMarkSweep(), Scavenge(), and StartTearDown().
SetGetExternallyAllocatedMemoryInBytesCallback()
void v8::internal::Heap::SetGetExternallyAllocatedMemoryInBytesCallback (GetExternallyAllocatedMemoryInBytesCallback callback) [inline]
Definition at line 1019 of file heap.h.
                                                            {
    external_memory_callback_ = callback;
  }
Referenced by v8::Isolate::SetGetExternallyAllocatedMemoryInBytesCallback(), and SetUpSpaces().
SetInterpreterEntryReturnPCOffset()
void v8::internal::Heap::SetInterpreterEntryReturnPCOffset (int pc_offset)
Definition at line 158 of file heap.cc.
                                                          {
  DCHECK_EQ(Smi::zero(), interpreter_entry_return_pc_offset());
  set_interpreter_entry_return_pc_offset(Smi::FromInt(pc_offset));
}
References DCHECK_EQ, v8::internal::Smi::FromInt(), and v8::internal::Smi::zero().
SetIsMarkingFlag()
void v8::internal::Heap::SetIsMarkingFlag (bool value) [private]
Definition at line 7389 of file heap.cc.
                                      {
  isolate()->isolate_data()->is_marking_flag_ = value;
}
References v8::internal::IsolateData::is_marking_flag_, isolate(), v8::internal::Isolate::isolate_data(), and v8::internal::value.
Referenced by v8::internal::Isolate::Init(), v8::internal::IncrementalMarking::StartMarkingMajor(), v8::internal::IncrementalMarking::StartMarkingMinor(), and v8::internal::IncrementalMarking::Stop().
SetIsMinorMarkingFlag()
void v8::internal::Heap::SetIsMinorMarkingFlag (bool value) [private]
Definition at line 7397 of file heap.cc.
                                           {
  isolate()->isolate_data()->is_minor_marking_flag_ = value;
}
References v8::internal::IsolateData::is_minor_marking_flag_, isolate(), v8::internal::Isolate::isolate_data(), and v8::internal::value.
Referenced by v8::internal::IncrementalMarking::StartMarkingMinor(), and v8::internal::IncrementalMarking::Stop().
SetMessageListeners()
void v8::internal::Heap::SetMessageListeners (Tagged< ArrayList > value) [inline]
Definition at line 125 of file heap-inl.h.
                                                      {
  roots_table()[RootIndex::kMessageListeners] = value.ptr();
}
References roots_table(), and v8::internal::value.
Referenced by v8::Isolate::AddMessageListenerWithErrorLevel().
SetNewSpaceAllocationCounterForTesting()
void v8::internal::Heap::SetNewSpaceAllocationCounterForTesting (size_t new_value) [inline]
Definition at line 1389 of file heap.h.
                                                                {
    new_space_allocation_counter_ = new_value;
  }
SetOldGenerationAndGlobalAllocationLimit()
void v8::internal::Heap::SetOldGenerationAndGlobalAllocationLimit (size_t new_old_generation_allocation_limit, size_t new_global_allocation_limit, const char * reason = __builtin_FUNCTION()) [private]
Definition at line 1558 of file heap.cc.
                                                            {
  CHECK_GE(new_global_allocation_limit, new_old_generation_allocation_limit);
#if defined(V8_USE_PERFETTO)
  TRACE_COUNTER(TRACE_DISABLED_BY_DEFAULT("v8.gc"),
                perfetto::CounterTrack(V8HeapTrait::kName,
                                       perfetto::ThreadTrack::Current()),
                new_old_generation_allocation_limit);
  TRACE_COUNTER(TRACE_DISABLED_BY_DEFAULT("v8.gc"),
                perfetto::CounterTrack(GlobalMemoryTrait::kName,
                                       perfetto::ThreadTrack::Current()),
                new_global_allocation_limit);
#endif
  old_generation_allocation_limit_.store(new_old_generation_allocation_limit,
                                         std::memory_order_relaxed);
  global_allocation_limit_.store(new_global_allocation_limit,
                                 std::memory_order_relaxed);
  if (v8_flags.trace_gc_nvp) [[unlikely]] {
    isolate()->PrintWithTimestamp(
        "action=SetOldGenerationAndGlobalAllocationLimit "
        "old_generation_allocation_limit=%zu global_allocation_limit=%zu "
        "reason=%s\n",
        new_old_generation_allocation_limit, new_global_allocation_limit,
        reason);
  }
}
References CHECK_GE, global_allocation_limit_, isolate(), v8::internal::V8HeapTrait::kName, v8::internal::GlobalMemoryTrait::kName, old_generation_allocation_limit_, TRACE_DISABLED_BY_DEFAULT, and v8::internal::v8_flags.
Referenced by EnsureMinimumRemainingAllocationLimit(), EnsureSweepingCompleted(), RecomputeLimits(), RecomputeLimitsAfterLoadingIfNeeded(), v8::internal::MemoryBalancer::RefreshLimit(), ResetOldGenerationAndGlobalAllocationLimit(), and ShrinkOldGenerationAllocationLimitIfNotConfigured().
SetOldGenerationAndGlobalMaximumSize()
void v8::internal::Heap::SetOldGenerationAndGlobalMaximumSize (size_t max_old_generation_size) [private]
Definition at line 1551 of file heap.cc.
                                    {
  max_old_generation_size_.store(max_old_generation_size,
                                 std::memory_order_relaxed);
  max_global_memory_size_ = GlobalMemorySizeFromV8Size(max_old_generation_size);
}
References v8::internal::anonymous_namespace{heap.cc}::GlobalMemorySizeFromV8Size(), max_global_memory_size_, max_old_generation_size(), and max_old_generation_size_.
Referenced by CollectGarbage(), ConfigureHeap(), and InvokeNearHeapLimitCallback().
SetRootMaterializedObjects()
void v8::internal::Heap::SetRootMaterializedObjects (Tagged< FixedArray > objects) [inline]
Definition at line 117 of file heap-inl.h.
                                                                {
  roots_table()[RootIndex::kMaterializedObjects] = objects.ptr();
}
References v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), and roots_table().
Referenced by v8::internal::MaterializedObjectStore::EnsureStackEntries().
SetRootNoScriptSharedFunctionInfos()
void v8::internal::Heap::SetRootNoScriptSharedFunctionInfos (Tagged< Object > value) [inline]
SetRootScriptList()
void v8::internal::Heap::SetRootScriptList (Tagged< Object > value) [inline]
Definition at line 121 of file heap-inl.h.
                                                 {
  roots_table()[RootIndex::kScriptList] = value.ptr();
}
References roots_table(), and v8::internal::value.
Referenced by v8::internal::ObjectDeserializer::CommitPostProcessedObjects(), v8::internal::BackgroundCompileTask::FinalizeScript(), and v8::internal::CodeSerializer::FinishOffThreadDeserialize().
SetSerializedGlobalProxySizes()
void v8::internal::Heap::SetSerializedGlobalProxySizes (Tagged< FixedArray > sizes)
Definition at line 168 of file heap.cc.
                                                                 {
  DCHECK(isolate()->serializer_enabled());
  set_serialized_global_proxy_sizes(sizes);
}
References v8::internal::DCHECK(), and isolate().
Referenced by v8::internal::SnapshotCreatorImpl::CreateBlob().
SetSerializedObjects()
void v8::internal::Heap::SetSerializedObjects (Tagged< HeapObject > objects)
Definition at line 163 of file heap.cc.
                                                          {
  DCHECK(isolate()->serializer_enabled());
  set_serialized_objects(objects);
}
References v8::internal::DCHECK(), and isolate().
Referenced by v8::internal::SnapshotCreatorImpl::AddData(), and v8::internal::anonymous_namespace{snapshot.cc}::ConvertSerializedObjectsToFixedArray().
SetSmiStringCache()
void v8::internal::Heap::SetSmiStringCache (Tagged< SmiStringCache > cache) [inline]
Definition at line 135 of file heap-inl.h.
                                                         {
  set_smi_string_cache(cache);
}
Referenced by v8::internal::SmiStringCache::Set().
SetStackStart()
void v8::internal::Heap::SetStackStart ()
Definition at line 6248 of file heap.cc.
                         {
  // If no main thread local heap has been set up (we're still in the
  // deserialization process), we don't need to set the stack start.
  if (main_thread_local_heap_ == nullptr) return;
  stack().SetStackStart();
}
References main_thread_local_heap_, heap::base::Stack::SetStackStart(), and stack().
Referenced by v8::internal::Isolate::Deinitialize(), v8::internal::Isolate::Enter(), and SetUp().
SetUp()
void v8::internal::Heap::SetUp (LocalHeap * main_thread_local_heap)
Definition at line 5743 of file heap.cc.
                                                  {
  DCHECK_NULL(main_thread_local_heap_);
  DCHECK_NULL(heap_allocator_);
  main_thread_local_heap_ = main_thread_local_heap;
  heap_allocator_ = &main_thread_local_heap->heap_allocator_;
  DCHECK_NOT_NULL(heap_allocator_);
  // Set the stack start for the main thread that sets up the heap.
  SetStackStart();
#ifdef V8_ENABLE_ALLOCATION_TIMEOUT
  heap_allocator_->UpdateAllocationTimeout();
#endif // V8_ENABLE_ALLOCATION_TIMEOUT
  // Initialize heap spaces and initial maps and objects.
  //
  // If the heap is not yet configured (e.g. through the API), configure it.
  // Configuration is based on the flags new-space-size (really the semispace
  // size) and old-space-size if set or the initial values of semispace_size_
  // and old_generation_size_ otherwise.
  if (!configured_) ConfigureHeapDefault();
  mmap_region_base_ =
      reinterpret_cast<uintptr_t>(v8::internal::GetRandomMmapAddr()) &
      ~kMmapRegionMask;
  v8::PageAllocator* code_page_allocator;
  if (isolate_->RequiresCodeRange() || code_range_size_ != 0) {
    const size_t requested_size =
        code_range_size_ == 0 ? kMaximalCodeRangeSize : code_range_size_;
    // When a target requires the code range feature, we put all code objects in
    // a contiguous range of virtual address space, so that they can call each
    // other with near calls.
#ifdef V8_COMPRESS_POINTERS
    // When pointer compression is enabled, isolates in the same group share the
    // same CodeRange, owned by the IsolateGroup.
    code_range_ = isolate_->isolate_group()->EnsureCodeRange(requested_size);
#else
    // Otherwise, each isolate has its own CodeRange, owned by the heap.
    code_range_ = std::make_unique<CodeRange>();
    if (!code_range_->InitReservation(isolate_->page_allocator(),
                                      requested_size, false)) {
      V8::FatalProcessOutOfMemory(
          isolate_, "Failed to reserve virtual memory for CodeRange");
    }
#endif // V8_COMPRESS_POINTERS
    LOG(isolate_,
        NewEvent("CodeRange",
                 reinterpret_cast<void*>(code_range_->reservation()->address()),
                 code_range_size_));
    isolate_->AddCodeRange(code_range_->reservation()->region().begin(),
                           code_range_->reservation()->region().size());
    code_page_allocator = code_range_->page_allocator();
  } else {
    code_page_allocator = isolate_->page_allocator();
  }
  v8::PageAllocator* trusted_page_allocator;
#ifdef V8_ENABLE_SANDBOX
  trusted_page_allocator =
      TrustedRange::GetProcessWideTrustedRange()->page_allocator();
#else
  trusted_page_allocator = isolate_->page_allocator();
#endif
  task_runner_ = V8::GetCurrentPlatform()->GetForegroundTaskRunner(
      reinterpret_cast<v8::Isolate*>(isolate()));
  collection_barrier_.reset(new CollectionBarrier(this, this->task_runner_));
  // Set up memory allocator.
  memory_allocator_.reset(new MemoryAllocator(
      isolate_, code_page_allocator, trusted_page_allocator, MaxReserved()));
  sweeper_.reset(new Sweeper(this));
  mark_compact_collector_.reset(new MarkCompactCollector(this));
  scavenger_collector_.reset(new ScavengerCollector(this));
  minor_mark_sweep_collector_.reset(new MinorMarkSweepCollector(this));
  ephemeron_remembered_set_.reset(new EphemeronRememberedSet());
  incremental_marking_.reset(
      new IncrementalMarking(this, mark_compact_collector_->weak_objects()));
  if (v8_flags.concurrent_marking || v8_flags.parallel_marking) {
    concurrent_marking_.reset(
        new ConcurrentMarking(this, mark_compact_collector_->weak_objects()));
  } else {
    concurrent_marking_.reset(new ConcurrentMarking(this, nullptr));
  }
  // Set up layout tracing callback.
  if (V8_UNLIKELY(v8_flags.trace_gc_heap_layout)) {
    v8::GCType gc_type = kGCTypeMarkSweepCompact;
    if (V8_UNLIKELY(!v8_flags.trace_gc_heap_layout_ignore_minor_gc)) {
      gc_type = static_cast<v8::GCType>(gc_type | kGCTypeScavenge |
                                        kGCTypeMinorMarkSweep);
    }
    AddGCPrologueCallback(HeapLayoutTracer::GCProloguePrintHeapLayout, gc_type,
                          nullptr);
    AddGCEpilogueCallback(HeapLayoutTracer::GCEpiloguePrintHeapLayout, gc_type,
                          nullptr);
  }
}
References v8::internal::Isolate::AddCodeRange(), AddGCEpilogueCallback(), AddGCPrologueCallback(), code_range_, code_range_size_, collection_barrier_, concurrent_marking_, ConcurrentMarking, configured_, ConfigureHeapDefault(), DCHECK_NOT_NULL, DCHECK_NULL, v8::internal::IsolateGroup::EnsureCodeRange(), ephemeron_remembered_set_, v8::internal::V8::FatalProcessOutOfMemory(), v8::internal::HeapLayoutTracer::GCEpiloguePrintHeapLayout(), v8::internal::HeapLayoutTracer::GCProloguePrintHeapLayout(), v8::internal::V8::GetCurrentPlatform(), v8::Platform::GetForegroundTaskRunner(), v8::internal::GetRandomMmapAddr(), heap_allocator_, v8::internal::LocalHeap::heap_allocator_, incremental_marking_, IncrementalMarking, isolate(), isolate_, v8::internal::Isolate::isolate_group(), v8::kGCTypeMarkSweepCompact, v8::kGCTypeMinorMarkSweep, v8::kGCTypeScavenge, v8::internal::kMaximalCodeRangeSize, kMmapRegionMask, LOG, main_thread_local_heap(), main_thread_local_heap_, mark_compact_collector_, MarkCompactCollector, MaxReserved(), memory_allocator_, minor_mark_sweep_collector_, MinorMarkSweepCollector, mmap_region_base_, v8::internal::Isolate::page_allocator(), v8::internal::Isolate::RequiresCodeRange(), scavenger_collector_, ScavengerCollector, SetStackStart(), Sweeper, sweeper_, task_runner_, v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::internal::Isolate::Init().
SetUpFromReadOnlyHeap()
void v8::internal::Heap::SetUpFromReadOnlyHeap (ReadOnlyHeap * ro_heap)
Definition at line 5851 of file heap.cc.
                                                      {
  DCHECK_NOT_NULL(ro_heap);
  DCHECK_IMPLIES(read_only_space_ != nullptr,
                 read_only_space_ == ro_heap->read_only_space());
  DCHECK_NULL(space_[RO_SPACE].get());
  read_only_space_ = ro_heap->read_only_space();
  heap_allocator_->SetReadOnlySpace(read_only_space_);
}
References DCHECK_IMPLIES, DCHECK_NOT_NULL, DCHECK_NULL, heap_allocator_, v8::internal::ReadOnlyHeap::read_only_space(), read_only_space_, v8::internal::RO_SPACE, v8::internal::HeapAllocator::SetReadOnlySpace(), and space_.
Referenced by v8::internal::Isolate::SetUpFromReadOnlyArtifacts().
SetUpSpaces()
void v8::internal::Heap::SetUpSpaces (LinearAllocationArea & new_allocation_info, LinearAllocationArea & old_allocation_info)
Definition at line 5967 of file heap.cc.
                                                                  {
  // Ensure SetUpFromReadOnlySpace has been ran.
  DCHECK_NOT_NULL(read_only_space_);
  if (v8_flags.sticky_mark_bits) {
    space_[OLD_SPACE] = std::make_unique<StickySpace>(this);
    old_space_ = static_cast<OldSpace*>(space_[OLD_SPACE].get());
  } else {
    space_[OLD_SPACE] = std::make_unique<OldSpace>(this);
    old_space_ = static_cast<OldSpace*>(space_[OLD_SPACE].get());
  }
  if (!v8_flags.single_generation) {
    if (!v8_flags.sticky_mark_bits) {
      if (v8_flags.minor_ms) {
        space_[NEW_SPACE] = std::make_unique<PagedNewSpace>(
            this, initial_semispace_size_, min_semi_space_size_,
            max_semi_space_size_);
      } else {
        space_[NEW_SPACE] = std::make_unique<SemiSpaceNewSpace>(
            this, initial_semispace_size_, min_semi_space_size_,
            max_semi_space_size_);
      }
      new_space_ = static_cast<NewSpace*>(space_[NEW_SPACE].get());
    }
    space_[NEW_LO_SPACE] =
        std::make_unique<NewLargeObjectSpace>(this, NewSpaceCapacity());
    new_lo_space_ =
        static_cast<NewLargeObjectSpace*>(space_[NEW_LO_SPACE].get());
  }
  space_[CODE_SPACE] = std::make_unique<CodeSpace>(this);
  code_space_ = static_cast<CodeSpace*>(space_[CODE_SPACE].get());
  space_[LO_SPACE] = std::make_unique<OldLargeObjectSpace>(this);
  lo_space_ = static_cast<OldLargeObjectSpace*>(space_[LO_SPACE].get());
  space_[CODE_LO_SPACE] = std::make_unique<CodeLargeObjectSpace>(this);
  code_lo_space_ =
      static_cast<CodeLargeObjectSpace*>(space_[CODE_LO_SPACE].get());
  space_[TRUSTED_SPACE] = std::make_unique<TrustedSpace>(this);
  trusted_space_ = static_cast<TrustedSpace*>(space_[TRUSTED_SPACE].get());
  space_[TRUSTED_LO_SPACE] = std::make_unique<TrustedLargeObjectSpace>(this);
  trusted_lo_space_ =
      static_cast<TrustedLargeObjectSpace*>(space_[TRUSTED_LO_SPACE].get());
  if (isolate()->is_shared_space_isolate()) {
    DCHECK(!v8_flags.sticky_mark_bits);
    space_[SHARED_SPACE] = std::make_unique<SharedSpace>(this);
    shared_space_ = static_cast<SharedSpace*>(space_[SHARED_SPACE].get());
    space_[SHARED_LO_SPACE] = std::make_unique<SharedLargeObjectSpace>(this);
    shared_lo_space_ =
        static_cast<SharedLargeObjectSpace*>(space_[SHARED_LO_SPACE].get());
    space_[SHARED_TRUSTED_SPACE] = std::make_unique<SharedTrustedSpace>(this);
    shared_trusted_space_ =
        static_cast<SharedTrustedSpace*>(space_[SHARED_TRUSTED_SPACE].get());
    space_[SHARED_TRUSTED_LO_SPACE] =
        std::make_unique<SharedTrustedLargeObjectSpace>(this);
    shared_trusted_lo_space_ = static_cast<SharedTrustedLargeObjectSpace*>(
        space_[SHARED_TRUSTED_LO_SPACE].get());
  }
  if (isolate()->has_shared_space()) {
    Heap* heap = isolate()->shared_space_isolate()->heap();
    shared_allocation_space_ = heap->shared_space_;
    shared_lo_allocation_space_ = heap->shared_lo_space_;
    shared_trusted_allocation_space_ = heap->shared_trusted_space_;
    shared_trusted_lo_allocation_space_ = heap->shared_trusted_lo_space_;
  }
  main_thread_local_heap()->SetUpMainThread(new_allocation_info,
                                            old_allocation_info);
  base::TimeTicks startup_time = base::TimeTicks::Now();
  tracer_.reset(new GCTracer(this, startup_time));
  array_buffer_sweeper_.reset(new ArrayBufferSweeper(this));
  memory_measurement_.reset(new MemoryMeasurement(isolate()));
  if (v8_flags.memory_reducer) memory_reducer_.reset(new MemoryReducer(this));
  if (V8_UNLIKELY(TracingFlags::is_gc_stats_enabled())) {
    live_object_stats_.reset(new ObjectStats(this));
    dead_object_stats_.reset(new ObjectStats(this));
  }
  if (Heap::AllocationTrackerForDebugging::IsNeeded()) {
    allocation_tracker_for_debugging_ =
        std::make_unique<Heap::AllocationTrackerForDebugging>(this);
  }
  LOG(isolate_, IntPtrTEvent("heap-capacity", Capacity()));
  LOG(isolate_, IntPtrTEvent("heap-available", Available()));
  SetGetExternallyAllocatedMemoryInBytesCallback(ReturnNull);
  if (new_space() || v8_flags.sticky_mark_bits) {
    minor_gc_job_.reset(new MinorGCJob(this));
  }
  if (v8_flags.stress_marking > 0) {
    stress_marking_percentage_ = NextStressMarkingLimit();
  }
  if (IsStressingScavenge()) {
    stress_scavenge_observer_ = new StressScavengeObserver(this);
    allocator()->new_space_allocator()->AddAllocationObserver(
        stress_scavenge_observer_);
  }
  if (v8_flags.memory_balancer) {
    mb_.reset(new MemoryBalancer(this, startup_time));
  }
}
References v8::internal::MainAllocator::AddAllocationObserver(), allocation_tracker_for_debugging_, allocator(), array_buffer_sweeper_, ArrayBufferSweeper, Available(), Capacity(), v8::internal::CODE_LO_SPACE, code_lo_space_, v8::internal::CODE_SPACE, code_space_, v8::internal::DCHECK(), DCHECK_NOT_NULL, dead_object_stats_, GCTracer, v8::internal::Isolate::has_shared_space(), v8::internal::Isolate::heap(), initial_semispace_size_, v8::internal::TracingFlags::is_gc_stats_enabled(), v8::internal::Isolate::is_shared_space_isolate(), v8::internal::Heap::AllocationTrackerForDebugging::IsNeeded(), isolate(), isolate_, IsStressingScavenge(), live_object_stats_, v8::internal::LO_SPACE, lo_space_, LOG, main_thread_local_heap(), max_semi_space_size_, mb_, memory_measurement_, memory_reducer_, MemoryBalancer, min_semi_space_size_, minor_gc_job_, MinorGCJob, v8::internal::NEW_LO_SPACE, new_lo_space_, v8::internal::NEW_SPACE, new_space(), new_space_, v8::internal::HeapAllocator::new_space_allocator(), NewSpaceCapacity(), NextStressMarkingLimit(), v8::base::TimeTicks::Now(), v8::internal::OLD_SPACE, old_space_, read_only_space_, v8::internal::ReturnNull(), SetGetExternallyAllocatedMemoryInBytesCallback(), v8::internal::LocalHeap::SetUpMainThread(), shared_allocation_space_, shared_lo_allocation_space_, v8::internal::SHARED_LO_SPACE, shared_lo_space_, v8::internal::SHARED_SPACE, shared_space_, v8::internal::Isolate::shared_space_isolate(), shared_trusted_allocation_space_, shared_trusted_lo_allocation_space_, v8::internal::SHARED_TRUSTED_LO_SPACE, shared_trusted_lo_space_, v8::internal::SHARED_TRUSTED_SPACE, shared_trusted_space_, space_, stress_marking_percentage_, stress_scavenge_observer_, tracer_, v8::internal::TRUSTED_LO_SPACE, trusted_lo_space_, v8::internal::TRUSTED_SPACE, trusted_space_, v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::internal::Isolate::Init().
shared_allocation_space()
PagedSpace* v8::internal::Heap::shared_allocation_space () const [inline]
Definition at line 793 of file heap.h.
                                              {
    return shared_allocation_space_;
  }
Referenced by v8::internal::EvacuationAllocator::Finalize(), and v8::internal::HeapAllocator::Setup().
shared_lo_allocation_space()
OldLargeObjectSpace* v8::internal::Heap::shared_lo_allocation_space () const [inline]
Definition at line 796 of file heap.h.
                                                          {
    return shared_lo_allocation_space_;
  }
Referenced by v8::internal::HeapAllocator::Setup().
shared_lo_space()
SharedLargeObjectSpace* v8::internal::Heap::shared_lo_space () const [inline]
Definition at line 779 of file heap.h.
{ return shared_lo_space_; }
Referenced by DeactivateMajorGCInProgressFlag(), OldGenerationSizeOfObjects(), v8::internal::IncrementalMarking::OldGenerationSizeOfObjects(), and Unmark().
shared_space()
SharedSpace* v8::internal::Heap::shared_space () const [inline]
Definition at line 776 of file heap.h.
{ return shared_space_; }
Referenced by DeactivateMajorGCInProgressFlag(), EnsureSweepingCompleted(), OldGenerationSizeOfObjects(), v8::internal::MarkCompactCollector::StartCompaction(), Unmark(), and v8::internal::MarkCompactCollector::VerifyMarking().
shared_trusted_allocation_space()
SharedTrustedSpace* v8::internal::Heap::shared_trusted_allocation_space () const [inline]
Definition at line 799 of file heap.h.
                                                              {
    return shared_trusted_allocation_space_;
  }
Referenced by v8::internal::HeapAllocator::Setup().
shared_trusted_lo_allocation_space()
SharedTrustedLargeObjectSpace* v8::internal::Heap::shared_trusted_lo_allocation_space () const [inline]
Definition at line 802 of file heap.h.
                                                                            {
    return shared_trusted_lo_allocation_space_;
  }
Referenced by v8::internal::HeapAllocator::Setup().
shared_trusted_lo_space()
SharedTrustedLargeObjectSpace* v8::internal::Heap::shared_trusted_lo_space () const [inline]
Definition at line 789 of file heap.h.
                                                                 {
    return shared_trusted_lo_space_;
  }
shared_trusted_space()
SharedTrustedSpace* v8::internal::Heap::shared_trusted_space () const [inline]
Definition at line 783 of file heap.h.
                                                   {
    return shared_trusted_space_;
  }
Referenced by EnsureSweepingCompleted().
SharedHeapContains()
bool v8::internal::Heap::SharedHeapContains (Tagged< HeapObject > value) const
Definition at line 4514 of file heap.cc.
                                                            {
  if (shared_allocation_space_) {
    if (shared_allocation_space_->Contains(value)) return true;
    if (shared_lo_allocation_space_->Contains(value)) return true;
    if (shared_trusted_allocation_space_->Contains(value)) return true;
    if (shared_trusted_lo_allocation_space_->Contains(value)) return true;
  }
  return false;
}
References v8::internal::PagedSpaceBase::Contains(), v8::internal::LargeObjectSpace::Contains(), shared_allocation_space_, shared_lo_allocation_space_, shared_trusted_allocation_space_, shared_trusted_lo_allocation_space_, and v8::internal::value.
ShouldCurrentGCKeepAgesUnchanged()
bool v8::internal::Heap::ShouldCurrentGCKeepAgesUnchanged () const [inline]
Definition at line 1420 of file heap.h.
                                                {
    return is_current_gc_forced_ || is_current_gc_for_heap_profiler_;
  }
Referenced by v8::internal::MarkCompactCollector::StartMarking(), and v8::internal::ConcurrentMarking::TryScheduleJob().
ShouldExpandOldGenerationOnSlowAllocation()
bool v8::internal::Heap::ShouldExpandOldGenerationOnSlowAllocation (LocalHeap * local_heap, AllocationOrigin origin) [private]
Definition at line 5502 of file heap.cc.
                                                                              {
  if (always_allocate() || OldGenerationSpaceAvailable() > 0) return true;
  // We reached the old generation allocation limit.
  // Allocations in the GC should always succeed if possible.
  if (origin == AllocationOrigin::kGC) return true;
  // Background threads need to be allowed to allocate without GC after teardown
  // was initiated.
  if (gc_state() == TEAR_DOWN) return true;
  // Allocations need to succeed during isolate deserialization. With shared
  // heap allocations, a client isolate may perform shared heap allocations
  // during isolate deserialization as well.
  if (!deserialization_complete() ||
      !local_heap->heap()->deserialization_complete()) {
    return true;
  }
  // Make it more likely that retry of allocations succeeds.
  if (local_heap->IsRetryOfFailedAllocation()) return true;
  // Background thread requested GC, allocation should fail
  if (CollectionRequested()) return false;
  if (ShouldOptimizeForMemoryUsage()) return false;
  if (ShouldOptimizeForLoadTime()) return true;
  if (incremental_marking()->IsMajorMarking() &&
      AllocationLimitOvershotByLargeMargin()) {
    return false;
  }
  if (incremental_marking()->IsStopped() &&
      IncrementalMarkingLimitReached() == IncrementalMarkingLimit::kNoLimit) {
    // We cannot start incremental marking.
    return false;
  }
  return true;
}
References AllocationLimitOvershotByLargeMargin(), always_allocate(), CollectionRequested(), deserialization_complete(), gc_state(), v8::internal::LocalHeap::heap(), incremental_marking(), IncrementalMarkingLimitReached(), v8::internal::LocalHeap::IsRetryOfFailedAllocation(), v8::internal::kGC, kNoLimit, OldGenerationSpaceAvailable(), ShouldOptimizeForLoadTime(), ShouldOptimizeForMemoryUsage(), and TEAR_DOWN.
ShouldExpandYoungGenerationOnSlowAllocation()
bool v8::internal::Heap::ShouldExpandYoungGenerationOnSlowAllocation (size_t allocation_size) [private]
Definition at line 5548 of file heap.cc.
                                                                             {
  DCHECK(deserialization_complete());
  if (always_allocate()) return true;
  if (gc_state() == TEAR_DOWN) return true;
  if (!CanPromoteYoungAndExpandOldGeneration(allocation_size)) {
    // Assuming all of new space is alive, doing a full GC and promoting all
    // objects should still succeed. Don't let new space grow if it means it
    // will exceed the available size of old space.
    return false;
  }
  if (incremental_marking()->IsMajorMarking() &&
      !AllocationLimitOvershotByLargeMargin()) {
    // Allocate a new page during full GC incremental marking to avoid
    // prematurely finalizing the incremental GC. Once the full GC is over, new
    // space will be empty and capacity will be reset.
    return true;
  }
  return false;
}
References AllocationLimitOvershotByLargeMargin(), always_allocate(), CanPromoteYoungAndExpandOldGeneration(), v8::internal::DCHECK(), deserialization_complete(), gc_state(), incremental_marking(), and TEAR_DOWN.
ShouldOptimizeForBattery()
bool v8::internal::Heap::ShouldOptimizeForBattery () const
Definition at line 468 of file heap.cc.
                                          {
  return v8_flags.optimize_gc_for_battery ||
         isolate()->BatterySaverModeEnabled();
}
References v8::internal::Isolate::BatterySaverModeEnabled(), isolate(), and v8::internal::v8_flags.
Referenced by v8::internal::ConcurrentMarking::GetMajorMaxConcurrency(), and v8::internal::ConcurrentMarking::GetMinorMaxConcurrency().
ShouldOptimizeForLoadTime()
bool v8::internal::Heap::ShouldOptimizeForLoadTime () const [private]
Definition at line 5490 of file heap.cc.
                                           {
  double load_start_time = load_start_time_ms_.load(std::memory_order_relaxed);
  return load_start_time != kLoadTimeNotLoading &&
         !AllocationLimitOvershotByLargeMargin() &&
         MonotonicallyIncreasingTimeInMs() < load_start_time + kMaxLoadTimeMs;
}
References AllocationLimitOvershotByLargeMargin(), kLoadTimeNotLoading, kMaxLoadTimeMs, load_start_time_ms_, and MonotonicallyIncreasingTimeInMs().
Referenced by CollectGarbage(), IncrementalMarkingLimitReached(), and ShouldExpandOldGenerationOnSlowAllocation().
ShouldOptimizeForMemoryUsage()
bool v8::internal::Heap::ShouldOptimizeForMemoryUsage ()
Definition at line 3898 of file heap.cc.
                                        {
  const size_t kOldGenerationSlack = max_old_generation_size() / 8;
  return isolate()->priority() == v8::Isolate::Priority::kBestEffort ||
         isolate()->MemorySaverModeEnabled() || HighMemoryPressure() ||
         !CanExpandOldGeneration(kOldGenerationSlack);
}
References CanExpandOldGeneration(), HighMemoryPressure(), isolate(), v8::Isolate::kBestEffort, max_old_generation_size(), v8::internal::Isolate::MemorySaverModeEnabled(), and v8::internal::Isolate::priority().
Referenced by v8::internal::MarkCompactCollector::ComputeEvacuationHeuristics(), CurrentHeapGrowingMode(), IncrementalMarkingLimitReached(), and ShouldExpandOldGenerationOnSlowAllocation().
ShouldReduceMemory()
bool v8::internal::Heap::ShouldReduceMemory () const [inline]
Definition at line 1671 of file heap.h.
                                  {
    return current_gc_flags_ & GCFlag::kReduceMemoryFootprint;
  }
Referenced by v8::internal::MarkCompactCollector::CollectEvacuationCandidates(), CollectGarbage(), v8::internal::MarkCompactCollector::ComputeEvacuationHeuristics(), CurrentHeapGrowingMode(), GarbageCollectionEpilogueInSafepoint(), v8::internal::ArrayBufferSweeper::RequestSweep(), SelectGarbageCollector(), ShouldResizeNewSpace(), v8::internal::MarkCompactCollector::StartCompaction(), v8::internal::GCTracer::StartCycle(), v8::internal::Sweeper::SweepEmptyNewSpacePage(), and v8::internal::GCTracer::UpdateCurrentEvent().
ShouldResizeNewSpace()
Heap::ResizeNewSpaceMode v8::internal::Heap::ShouldResizeNewSpace () [private]
Definition at line 3943 of file heap.cc.
                                                  {
  if (ShouldReduceMemory()) {
    return (v8_flags.predictable) ? ResizeNewSpaceMode::kNone
                                  : ResizeNewSpaceMode::kShrink;
  }
  static const size_t kLowAllocationThroughput = 1000;
  const double allocation_throughput =
      tracer_->AllocationThroughputInBytesPerMillisecond();
  const bool should_shrink = !v8_flags.predictable &&
                             (allocation_throughput != 0) &&
                             (allocation_throughput < kLowAllocationThroughput);
  const bool should_grow =
      (new_space_->TotalCapacity() < new_space_->MaximumCapacity()) &&
      (survived_since_last_expansion_ > new_space_->TotalCapacity());
  if (should_grow) survived_since_last_expansion_ = 0;
  if (should_grow == should_shrink) return ResizeNewSpaceMode::kNone;
  return should_grow ? ResizeNewSpaceMode::kGrow : ResizeNewSpaceMode::kShrink;
}
References kGrow, kNone, kShrink, v8::internal::NewSpace::MaximumCapacity(), new_space_, ShouldReduceMemory(), survived_since_last_expansion_, v8::internal::NewSpace::TotalCapacity(), tracer_, and v8::internal::v8_flags.
Referenced by ResizeNewSpace(), and StartResizeNewSpace().
ShouldStressCompaction()
bool v8::internal::Heap::ShouldStressCompaction () const [private]
Definition at line 5732 of file heap.cc.
                                        {
  return v8_flags.stress_compaction && (gc_count_ & 1) != 0;
}
References gc_count_, and v8::internal::v8_flags.
Referenced by IncrementalMarkingLimitReached(), and SelectGarbageCollector().
ShouldUseBackgroundThreads()
bool v8::internal::Heap::ShouldUseBackgroundThreads () const
Definition at line 454 of file heap.cc.
                                            {
  return !v8_flags.single_threaded_gc_in_background ||
         !isolate()->EfficiencyModeEnabled();
}
References v8::internal::Isolate::EfficiencyModeEnabled(), isolate(), and v8::internal::v8_flags.
Referenced by v8::internal::MarkCompactCollector::MaybeEnableBackgroundThreadsInCycle(), v8::internal::ArrayBufferSweeper::RequestSweep(), v8::internal::MinorMarkSweepCollector::StartMarking(), v8::internal::MarkCompactCollector::StartMarking(), and StartMinorMSConcurrentMarkingIfNeeded().
ShouldUseIncrementalMarking()
bool v8::internal::Heap::ShouldUseIncrementalMarking () const
Definition at line 459 of file heap.cc.
                                             {
  if (v8_flags.single_threaded_gc_in_background &&
      isolate()->EfficiencyModeEnabled()) {
    return v8_flags.incremental_marking_for_gc_in_background;
  } else {
    return true;
  }
}
References isolate(), and v8::internal::v8_flags.
Referenced by v8::internal::IncrementalMarking::CanAndShouldBeStarted().
ShouldUsePrecisePinningForMajorGC()
bool v8::internal::Heap::ShouldUsePrecisePinningForMajorGC () const [inline]
Definition at line 400 of file heap.h.
                                                 {
    return v8_flags.precise_object_pinning;
  }
References v8::internal::v8_flags.
ShouldUsePrecisePinningForMinorGC()
bool v8::internal::Heap::ShouldUsePrecisePinningForMinorGC () const [inline]
Definition at line 397 of file heap.h.
                                                 {
    return v8_flags.scavenger_precise_object_pinning;
  }
References v8::internal::v8_flags.
Referenced by v8::internal::ScavengerCollector::CollectGarbage().
ShrinkOldGenerationAllocationLimitIfNotConfigured()
void v8::internal::Heap::ShrinkOldGenerationAllocationLimitIfNotConfigured () [private]
Definition at line 3225 of file heap.cc.
                                                             {
  if (using_initial_limit() && !initial_size_overwritten_ &&
      tracer()->SurvivalEventsRecorded()) {
    base::MutexGuard guard(old_space()->mutex());
    const size_t minimum_growing_step =
        MemoryController<V8HeapTrait>::MinimumAllocationLimitGrowingStep(
            CurrentHeapGrowingMode());
    size_t new_old_generation_allocation_limit =
        std::max(OldGenerationConsumedBytes() + minimum_growing_step,
                 static_cast<size_t>(
                     static_cast<double>(old_generation_allocation_limit()) *
                     (tracer()->AverageSurvivalRatio() / 100)));
    new_old_generation_allocation_limit = std::min(
        new_old_generation_allocation_limit, old_generation_allocation_limit());
    size_t new_global_allocation_limit = std::max(
        GlobalConsumedBytes() + minimum_growing_step,
        static_cast<size_t>(static_cast<double>(global_allocation_limit()) *
                            (tracer()->AverageSurvivalRatio() / 100)));
    new_global_allocation_limit =
        std::min(new_global_allocation_limit, global_allocation_limit());
    SetOldGenerationAndGlobalAllocationLimit(
        new_old_generation_allocation_limit, new_global_allocation_limit);
  }
}
References CurrentHeapGrowingMode(), global_allocation_limit(), GlobalConsumedBytes(), initial_size_overwritten_, v8::internal::MemoryController< Trait >::MinimumAllocationLimitGrowingStep(), old_generation_allocation_limit(), old_space(), OldGenerationConsumedBytes(), SetOldGenerationAndGlobalAllocationLimit(), tracer(), and using_initial_limit().
Referenced by PerformGarbageCollection().
SizeOfObjects()
size_t v8::internal::Heap::SizeOfObjects ()
Definition at line 1008 of file heap.cc.
                           {
  size_t total = 0;
  for (SpaceIterator it(this); it.HasNext();) {
    total += it.Next()->SizeOfObjects();
  }
  return total;
}
References v8::internal::SpaceIterator::HasNext().
Referenced by CollectGarbageOnMemoryPressure(), v8::internal::Heap::DevToolsTraceEventScope::DevToolsTraceEventScope(), EvaluateOldSpaceLocalPretenuring(), GarbageCollectionEpilogue(), MarkCompact(), PrintShortHeapStatistics(), v8::internal::GCTracer::StartInSafepoint(), and v8::internal::GCTracer::StopInSafepoint().
space()
Space * v8::internal::Heap::space (int idx) const [inline]
Definition at line 158 of file heap-inl.h.
{ return space_[idx].get(); }
References space_.
Referenced by CollectAllAvailableGarbage(), CollectGarbage(), CollectGarbageWithRetry(), CommittedOldGenerationMemory(), DeactivateMajorGCInProgressFlag(), v8::internal::SpaceIterator::HasNext(), InSpace(), InSpaceSlow(), IsValidAllocationSpace(), v8::internal::SpaceIterator::Next(), NotifyOldGenerationExpansion(), OldGenerationCapacity(), OldGenerationWastedBytes(), ReplaceReadOnlySpace(), SelectGarbageCollector(), v8::internal::HeapAllocator::Setup(), and Unmark().
stack() [1/2]
heap::base::Stack & v8::internal::Heap::stack ()
Definition at line 6255 of file heap.cc.
                           {
  CHECK_NOT_NULL(main_thread_local_heap_);
  return main_thread_local_heap_->stack_;
}
References CHECK_NOT_NULL, main_thread_local_heap_, and v8::internal::LocalHeap::stack_.
Referenced by CollectGarbage(), v8::internal::LocalHeap::ExecuteBackgroundThreadWhileParked(), v8::internal::LocalHeap::ExecuteMainThreadWhileParked(), v8::internal::LocalHeap::ExecuteWithStackMarker(), v8::internal::LocalHeap::is_in_trampoline(), IsGCWithStack(), IterateConservativeStackRoots(), v8::internal::UnreachableObjectsFilter::MarkReachableObjects(), v8::internal::HeapProfiler::QueryObjects(), SetStackStart(), v8::internal::CppHeap::stack(), v8::internal::HeapProfiler::TakeSnapshot(), and v8::internal::HeapProfiler::WriteSnapshotToDiskAfterGC().
stack() [2/2]
const ::heap::base::Stack & v8::internal::Heap::stack () const
Definition at line 6260 of file heap.cc.
                                       {
  CHECK_NOT_NULL(main_thread_local_heap_);
  return main_thread_local_heap_->stack_;
}
References CHECK_NOT_NULL, main_thread_local_heap_, and v8::internal::LocalHeap::stack_.
StartIncrementalMarking()
void v8::internal::Heap::StartIncrementalMarking (GCFlags gc_flags, GarbageCollectionReason gc_reason, GCCallbackFlags gc_callback_flags = GCCallbackFlags::kNoGCCallbackFlags, GarbageCollector collector = GarbageCollector::MARK_COMPACTOR)
Definition at line 1930 of file heap.cc.
                                                               {
  DCHECK(incremental_marking()->IsStopped());
  CHECK_IMPLIES(!v8_flags.allow_allocation_in_fast_api_call,
                !isolate()->InFastCCall());
  DCHECK_EQ(isolate(), Isolate::TryGetCurrent());
  if (gc_callbacks_depth_ > 0) {
    // Do not start incremental marking while invoking GC callbacks.
    // Heap::CollectGarbage already decided which GC is going to be
    // invoked. In case it chose a young-gen GC, starting an incremental
    // full GC during callbacks would break the separate GC phases
    // guarantee.
    return;
  }
  if (IsYoungGenerationCollector(collector)) {
    CompleteSweepingYoung();
  } else {
    // Sweeping needs to be completed such that markbits are all cleared before
    // starting marking again.
    CompleteSweepingFull();
  }
  std::optional<SafepointScope> safepoint_scope;
  {
    AllowGarbageCollection allow_shared_gc;
    safepoint_scope.emplace(isolate(), kGlobalSafepointForSharedSpaceIsolate);
  }
#ifdef DEBUG
  VerifyCountersAfterSweeping();
#endif
  std::vector<Isolate*> paused_clients =
      PauseConcurrentThreadsInClients(collector);
  // Now that sweeping is completed, we can start the next full GC cycle.
  tracer()->StartCycle(collector, gc_reason, nullptr,
                       GCTracer::MarkingType::kIncremental);
  current_gc_flags_ = gc_flags;
  current_gc_callback_flags_ = gc_callback_flags;
  incremental_marking()->Start(collector, gc_reason);
  if (collector == GarbageCollector::MARK_COMPACTOR) {
    DCHECK(incremental_marking()->IsMajorMarking());
    is_full_gc_during_loading_ = update_allocation_limits_after_loading_;
    RecomputeLimitsAfterLoadingIfNeeded();
    DCHECK(!update_allocation_limits_after_loading_);
  }
  if (isolate()->is_shared_space_isolate()) {
    for (Isolate* client : paused_clients) {
      client->heap()->concurrent_marking()->Resume();
    }
  } else {
    DCHECK(paused_clients.empty());
  }
}
References CHECK_IMPLIES, CompleteSweepingFull(), CompleteSweepingYoung(), current_gc_callback_flags_, current_gc_flags_, v8::internal::DCHECK(), DCHECK_EQ, gc_callbacks_depth_, incremental_marking(), is_full_gc_during_loading_, isolate(), IsYoungGenerationCollector(), v8::internal::kGlobalSafepointForSharedSpaceIsolate, v8::internal::GCTracer::kIncremental, v8::internal::MARK_COMPACTOR, PauseConcurrentThreadsInClients(), RecomputeLimitsAfterLoadingIfNeeded(), v8::internal::IncrementalMarking::Start(), v8::internal::GCTracer::StartCycle(), tracer(), v8::Isolate::TryGetCurrent(), update_allocation_limits_after_loading_, and v8::internal::v8_flags.
Referenced by CheckMemoryPressure(), CollectGarbageOnMemoryPressure(), HandleExternalMemoryInterrupt(), v8::internal::MemoryReducer::NotifyTimer(), StartIncrementalMarkingIfAllocationLimitIsReached(), and StartMinorMSConcurrentMarkingIfNeeded().
StartIncrementalMarkingIfAllocationLimitIsReached()
void v8::internal::Heap::StartIncrementalMarkingIfAllocationLimitIsReached (LocalHeap * local_heap, GCFlags gc_flags, GCCallbackFlags gc_callback_flags = GCCallbackFlags::kNoGCCallbackFlags)
Definition at line 2037 of file heap.cc.
                                             {
  if (incremental_marking()->IsStopped() &&
      incremental_marking()->CanAndShouldBeStarted()) {
    switch (IncrementalMarkingLimitReached()) {
      case IncrementalMarkingLimit::kHardLimit:
        if (local_heap->is_main_thread_for(this)) {
          StartIncrementalMarking(
              gc_flags,
              OldGenerationSpaceAvailable() <= NewSpaceTargetCapacity()
                  ? GarbageCollectionReason::kAllocationLimit
                  : GarbageCollectionReason::kGlobalAllocationLimit,
              gc_callback_flags);
        } else {
          ExecutionAccess access(isolate());
          isolate()->stack_guard()->RequestStartIncrementalMarking();
          if (auto* job = incremental_marking()->incremental_marking_job()) {
            job->ScheduleTask();
          }
        }
        break;
      case IncrementalMarkingLimit::kSoftLimit:
        if (auto* job = incremental_marking()->incremental_marking_job()) {
          job->ScheduleTask(TaskPriority::kUserVisible);
        }
        break;
      case IncrementalMarkingLimit::kFallbackForEmbedderLimit:
        // This is a fallback case where no appropriate limits have been
        // configured yet.
        if (local_heap->is_main_thread_for(this) &&
            memory_reducer() != nullptr) {
          memory_reducer()->NotifyPossibleGarbage();
        }
        break;
      case IncrementalMarkingLimit::kNoLimit:
        break;
    }
  }
}
References incremental_marking(), IncrementalMarkingLimitReached(), v8::internal::LocalHeap::is_main_thread_for(), isolate(), v8::internal::kAllocationLimit, kFallbackForEmbedderLimit, v8::internal::kGlobalAllocationLimit, kHardLimit, kNoLimit, kSoftLimit, v8::kUserVisible, memory_reducer(), NewSpaceTargetCapacity(), v8::internal::MemoryReducer::NotifyPossibleGarbage(), OldGenerationSpaceAvailable(), v8::internal::Isolate::stack_guard(), and StartIncrementalMarking().
Referenced by v8::internal::OldLargeObjectSpace::AllocateRaw(), CollectGarbage(), v8::internal::PagedSpaceAllocatorPolicy::EnsureAllocation(), HandleExternalMemoryInterrupt(), and StartIncrementalMarkingOnInterrupt().
StartIncrementalMarkingOnInterrupt()
void v8::internal::Heap::StartIncrementalMarkingOnInterrupt ()
Definition at line 2031 of file heap.cc.
                                              {
  StartIncrementalMarkingIfAllocationLimitIsReached(
      main_thread_local_heap(), GCFlagsForIncrementalMarking(),
      kGCCallbackScheduleIdleGarbageCollection);
}
References GCFlagsForIncrementalMarking(), v8::kGCCallbackScheduleIdleGarbageCollection, main_thread_local_heap(), and StartIncrementalMarkingIfAllocationLimitIsReached().
Referenced by v8::internal::StackGuard::HandleInterrupts().
StartMinorMSConcurrentMarkingIfNeeded()
void v8::internal::Heap::StartMinorMSConcurrentMarkingIfNeeded () [private]
Definition at line 1237 of file heap.cc.
                                                 {
  if (incremental_marking()->IsMarking()) return;
  if (v8_flags.concurrent_minor_ms_marking && !IsTearingDown() &&
      incremental_marking()->CanAndShouldBeStarted() &&
      V8_LIKELY(!v8_flags.gc_global)) {
    size_t usable_capacity = 0;
    size_t new_space_size = 0;
    if (v8_flags.sticky_mark_bits) {
      // TODO(333906585): Adjust parameters.
      usable_capacity =
          sticky_space()->Capacity() - sticky_space()->old_objects_size();
      new_space_size = sticky_space()->young_objects_size();
    } else {
      usable_capacity = paged_new_space()->paged_space()->UsableCapacity();
      new_space_size = new_space()->Size();
    }
    if ((usable_capacity >=
         v8_flags.minor_ms_min_new_space_capacity_for_concurrent_marking_mb *
             MB) &&
        (new_space_size >= MinorMSConcurrentMarkingTrigger(this)) &&
        ShouldUseBackgroundThreads()) {
      StartIncrementalMarking(GCFlag::kNoFlags, GarbageCollectionReason::kTask,
                              kNoGCCallbackFlags,
                              GarbageCollector::MINOR_MARK_SWEEPER);
      // Schedule a task for finalizing the GC if needed.
      minor_gc_job()->TryScheduleTask();
    }
  }
}
References v8::internal::PagedSpaceBase::Capacity(), incremental_marking(), IsTearingDown(), v8::internal::kNoFlags, v8::kNoGCCallbackFlags, v8::internal::kTask, v8::internal::MB, minor_gc_job(), v8::internal::MINOR_MARK_SWEEPER, v8::internal::anonymous_namespace{heap.cc}::MinorMSConcurrentMarkingTrigger(), new_space(), v8::internal::StickySpace::old_objects_size(), paged_new_space(), v8::internal::PagedNewSpace::paged_space(), ShouldUseBackgroundThreads(), StartIncrementalMarking(), sticky_space(), v8::internal::MinorGCJob::TryScheduleTask(), v8::internal::PagedSpaceForNewSpace::UsableCapacity(), v8::internal::v8_flags, V8_LIKELY, and v8::internal::StickySpace::young_objects_size().
Referenced by CollectGarbage(), and v8::internal::PagedSpaceAllocatorPolicy::EnsureAllocation().
StartResizeNewSpace()
void v8::internal::Heap::StartResizeNewSpace () [private]
Definition at line 3977 of file heap.cc.
                               {
  DCHECK_EQ(ResizeNewSpaceMode::kNone, resize_new_space_mode_);
  DCHECK(v8_flags.minor_ms);
  resize_new_space_mode_ = ShouldResizeNewSpace();
  if (resize_new_space_mode_ == ResizeNewSpaceMode::kShrink) {
    size_t reduced_capacity = ComputeReducedNewSpaceSize(new_space());
    paged_new_space()->StartShrinking(reduced_capacity);
  }
}
References v8::internal::anonymous_namespace{heap.cc}::ComputeReducedNewSpaceSize(), v8::internal::DCHECK(), DCHECK_EQ, kNone, kShrink, new_space(), paged_new_space(), resize_new_space_mode_, ShouldResizeNewSpace(), v8::internal::PagedNewSpace::StartShrinking(), and v8::internal::v8_flags.
Referenced by v8::internal::MinorMarkSweepCollector::StartSweepNewSpace().
StartTearDown()
void v8::internal::Heap::StartTearDown ()
Definition at line 6265 of file heap.cc.
                         {
  if (cpp_heap_) {
    // This may invoke a GC in case marking is running to get us into a
    // well-defined state for tear down.
    CppHeap::From(cpp_heap_)->StartDetachingIsolate();
  }
  // Stressing incremental marking should make it likely to force a GC here with
  // a CppHeap present. Stress compaction serves as a more deterministic way to
  // trigger such a GC.
  if (v8_flags.stress_compaction) {
    CollectGarbage(OLD_SPACE, GarbageCollectionReason::kTesting);
  }
  // the heap during teardown.
  CompleteSweepingFull();
  if (v8_flags.concurrent_marking) {
    concurrent_marking()->Pause();
  }
  SetGCState(TEAR_DOWN);
  // Background threads may allocate and block until GC is performed. However
  // this might never happen when the main thread tries to quit and doesn't
  // process the event queue anymore. Avoid this deadlock by allowing all
  // allocations after tear down was requested to make sure all background
  // threads finish.
  collection_barrier_->NotifyShutdownRequested();
  // Main thread isn't going to allocate anymore.
  main_thread_local_heap()->FreeLinearAllocationAreas();
  FreeMainThreadLinearAllocationAreas();
}
References CollectGarbage(), collection_barrier_, CompleteSweepingFull(), concurrent_marking(), cpp_heap_, v8::internal::LocalHeap::FreeLinearAllocationAreas(), FreeMainThreadLinearAllocationAreas(), v8::internal::CppHeap::From(), v8::internal::kTesting, main_thread_local_heap(), v8::internal::OLD_SPACE, v8::internal::ConcurrentMarking::Pause(), SetGCState(), v8::internal::CppHeap::StartDetachingIsolate(), TEAR_DOWN, and v8::internal::v8_flags.
Referenced by v8::internal::Isolate::Deinit().
StaticRootsEnsureAllocatedSize()
void v8::internal::Heap::StaticRootsEnsureAllocatedSize (DirectHandle< HeapObject > obj, int required) [private]
Definition at line 898 of file setup-heap-internal.cc.
                                                        {
  if (V8_STATIC_ROOTS_BOOL || V8_STATIC_ROOTS_GENERATION_BOOL) {
    int obj_size = obj->Size();
    if (required == obj_size) return;
    CHECK_LT(obj_size, required);
    int filler_size = required - obj_size;
    Tagged<HeapObject> filler =
        allocator()->AllocateRawWith<HeapAllocator::kRetryOrFail>(
            filler_size, AllocationType::kReadOnly, AllocationOrigin::kRuntime,
            AllocationAlignment::kTaggedAligned);
    CreateFillerObjectAt(filler.address(), filler_size,
                         ClearFreedMemoryMode::kClearFreedMemory);
    CHECK_EQ(filler.address(), obj->address() + obj_size);
    CHECK_EQ(filler.address() + filler->Size(), obj->address() + required);
  }
}
References v8::internal::DirectHandle< T >::address(), v8::internal::Tagged< HeapObject >::address(), v8::internal::HeapAllocator::AllocateRawWith(), allocator(), CHECK_EQ, CHECK_LT, CreateFillerObjectAt(), v8::internal::kClearFreedMemory, v8::internal::kReadOnly, v8::internal::HeapAllocator::kRetryOrFail, v8::internal::kRuntime, v8::internal::kTaggedAligned, V8_STATIC_ROOTS_BOOL, and V8_STATIC_ROOTS_GENERATION_BOOL.
Referenced by CreateReadOnlyApiObjects(), and CreateReadOnlyObjects().
sticky_space()
StickySpace * v8::internal::Heap::sticky_space () const [inline]
Definition at line 434 of file heap-inl.h.
                                      {
  DCHECK(v8_flags.sticky_mark_bits);
  return StickySpace::From(old_space());
}
References v8::internal::DCHECK(), v8::internal::StickySpace::From(), old_space(), and v8::internal::v8_flags.
Referenced by CanPromoteYoungAndExpandOldGeneration(), NewSpaceCapacity(), NewSpaceSize(), NewSpaceTargetCapacity(), OldGenerationSizeOfObjects(), v8::internal::PretenuringHandler::ProcessPretenuringFeedback(), v8::internal::HeapAllocator::Setup(), v8::internal::MinorMarkSweepCollector::StartMarking(), StartMinorMSConcurrentMarkingIfNeeded(), v8::internal::MinorMarkSweepCollector::StartSweepNewSpaceWithStickyBits(), v8::internal::MinorMarkSweepCollector::Sweep(), v8::internal::Sweeper::SweepEmptyNewSpacePage(), v8::internal::MinorMarkSweepCollector::TraceFragmentation(), and YoungGenerationSizeOfObjects().
SurvivedYoungObjectSize()
size_t v8::internal::Heap::SurvivedYoungObjectSize () [inline]
Definition at line 1371 of file heap.h.
                                          {
    return promoted_objects_size_ + new_space_surviving_object_size_;
  }
Referenced by v8::internal::GCTracer::StopInSafepoint().
sweeper()
Sweeper* v8::internal::Heap::sweeper () [inline]
Definition at line 864 of file heap.h.
{ return sweeper_.get(); }
Referenced by CompleteSweepingFull(), v8::internal::PagedSpaceAllocatorPolicy::ContributeToSweeping(), EnsureSweepingCompleted(), EnsureSweepingCompletedForObject(), EnsureYoungSweepingCompleted(), FinishSweepingIfOutOfWork(), v8::internal::MinorMarkSweepCollector::MarkLiveObjects(), v8::internal::MarkCompactCollector::MarkObjectsFromClientHeap(), PauseConcurrentThreadsInClients(), v8::internal::PagedSpaceAllocatorPolicy::RefillLab(), v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::Run(), v8::internal::IncrementalMarking::StartMarkingMinor(), and v8::internal::PagedNewSpaceAllocatorPolicy::WaitForSweepingForAllocation().
sweeping_in_progress()
bool v8::internal::Heap::sweeping_in_progress () const [inline]
Definition at line 1591 of file heap.h.
{ return sweeper_->sweeping_in_progress(); }
Referenced by CompleteSweepingFull(), EnsureSweepingCompleted(), EnsureSweepingCompletedForObject(), PrintShortHeapStatistics(), v8::internal::PagedSpaceAllocatorPolicy::RefillLab(), and v8::internal::IncrementalMarking::Start().
sweeping_in_progress_for_space()
bool v8::internal::Heap::sweeping_in_progress_for_space (AllocationSpace space) const [inline]
Definition at line 1592 of file heap.h.
                                                                   {
    return sweeper_->sweeping_in_progress_for_space(space);
  }
References space.
TearDown()
void v8::internal::Heap::TearDown ()
Definition at line 6320 of file heap.cc.
                    {
  DCHECK_EQ(gc_state(), TEAR_DOWN);
  // Assert that there are no background threads left and no executable memory
  // chunks are unprotected.
  safepoint()->AssertMainThreadIsOnlyThread();
  DCHECK(concurrent_marking()->IsStopped());
  // It's too late for Heap::Verify() here, as parts of the Isolate are
  // already gone by the time this is called.
  UpdateMaximumCommitted();
  if (v8_flags.fuzzer_gc_analysis) {
    if (v8_flags.stress_marking > 0) {
      PrintMaxMarkingLimitReached();
    }
    if (IsStressingScavenge()) {
      PrintMaxNewSpaceSizeReached();
    }
  }
  if (cpp_heap_) {
    CppHeap::From(cpp_heap_)->DetachIsolate();
    cpp_heap_ = nullptr;
    isolate_->RunReleaseCppHeapCallback(std::move(owning_cpp_heap_));
  }
  minor_gc_job_.reset();
  if (need_to_remove_stress_concurrent_allocation_observer_) {
    RemoveAllocationObserversFromAllSpaces(
        stress_concurrent_allocation_observer_.get(),
        stress_concurrent_allocation_observer_.get());
  }
  stress_concurrent_allocation_observer_.reset();
  if (IsStressingScavenge()) {
    allocator()->new_space_allocator()->RemoveAllocationObserver(
        stress_scavenge_observer_);
    delete stress_scavenge_observer_;
    stress_scavenge_observer_ = nullptr;
  }
  if (mark_compact_collector_) {
    mark_compact_collector_->TearDown();
    mark_compact_collector_.reset();
  }
  if (minor_mark_sweep_collector_) {
    minor_mark_sweep_collector_->TearDown();
    minor_mark_sweep_collector_.reset();
  }
  sweeper_->TearDown();
  sweeper_.reset();
  scavenger_collector_.reset();
  array_buffer_sweeper_.reset();
  incremental_marking_.reset();
  concurrent_marking_.reset();
  memory_measurement_.reset();
  allocation_tracker_for_debugging_.reset();
  ephemeron_remembered_set_.reset();
  if (memory_reducer_ != nullptr) {
    memory_reducer_->TearDown();
    memory_reducer_.reset();
  }
  live_object_stats_.reset();
  dead_object_stats_.reset();
  embedder_roots_handler_ = nullptr;
  tracer_.reset();
  pretenuring_handler_.reset();
  for (int i = FIRST_MUTABLE_SPACE; i <= LAST_MUTABLE_SPACE; i++) {
    space_[i].reset();
  }
  read_only_space_ = nullptr;
  memory_allocator()->pool()->ReleaseOnTearDown(isolate());
  memory_allocator()->TearDown();
  StrongRootsEntry* next = nullptr;
  for (StrongRootsEntry* current = strong_roots_head_; current;
       current = next) {
    next = current->next;
    delete current;
  }
  strong_roots_head_ = nullptr;
  memory_allocator_.reset();
  heap_profiler_.reset();
}
References allocation_tracker_for_debugging_, allocator(), array_buffer_sweeper_, v8::internal::IsolateSafepoint::AssertMainThreadIsOnlyThread(), concurrent_marking(), concurrent_marking_, cpp_heap_, v8::internal::DCHECK(), DCHECK_EQ, dead_object_stats_, v8::internal::CppHeap::DetachIsolate(), embedder_roots_handler_, ephemeron_remembered_set_, v8::internal::FIRST_MUTABLE_SPACE, v8::internal::CppHeap::From(), gc_state(), heap_profiler_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, incremental_marking_, isolate(), isolate_, IsStressingScavenge(), v8::internal::LAST_MUTABLE_SPACE, live_object_stats_, mark_compact_collector_, memory_allocator(), memory_allocator_, memory_measurement_, memory_reducer_, minor_gc_job_, minor_mark_sweep_collector_, need_to_remove_stress_concurrent_allocation_observer_, v8::internal::HeapAllocator::new_space_allocator(), v8::internal::StrongRootsEntry::next, owning_cpp_heap_, v8::internal::MemoryAllocator::pool(), pretenuring_handler_, PrintMaxMarkingLimitReached(), PrintMaxNewSpaceSizeReached(), read_only_space_, v8::internal::PagePool::ReleaseOnTearDown(), v8::internal::MainAllocator::RemoveAllocationObserver(), RemoveAllocationObserversFromAllSpaces(), v8::internal::PretenuringHandler::reset(), v8::internal::Isolate::RunReleaseCppHeapCallback(), safepoint(), scavenger_collector_, space_, stress_concurrent_allocation_observer_, stress_scavenge_observer_, strong_roots_head_, sweeper_, TEAR_DOWN, v8::internal::MemoryAllocator::TearDown(), tracer_, UpdateMaximumCommitted(), and v8::internal::v8_flags.
Referenced by v8::internal::Isolate::Deinit().
TearDownWithSharedHeap()
void v8::internal::Heap::TearDownWithSharedHeap ()
Definition at line 6301 of file heap.cc.
                                  {
  DCHECK_EQ(gc_state(), TEAR_DOWN);
  // Assert that there are no background threads left and no executable memory
  // chunks are unprotected.
  safepoint()->AssertMainThreadIsOnlyThread();
  // Now that all threads are stopped, verify the heap before tearing down the
  // heap/isolate.
  HeapVerifier::VerifyHeapIfEnabled(this);
  // Might use the external pointer which might be in the shared heap.
  external_string_table_.TearDown();
  // Publish shared object worklist for the main thread if incremental marking
  // is enabled for the shared heap.
  main_thread_local_heap()->marking_barrier()->PublishSharedIfNeeded();
}
References v8::internal::IsolateSafepoint::AssertMainThreadIsOnlyThread(), DCHECK_EQ, external_string_table_, gc_state(), main_thread_local_heap(), v8::internal::LocalHeap::marking_barrier(), v8::internal::MarkingBarrier::PublishSharedIfNeeded(), safepoint(), TEAR_DOWN, v8::internal::Heap::ExternalStringTable::TearDown(), and v8::internal::HeapVerifier::VerifyHeapIfEnabled().
Referenced by v8::internal::Isolate::Deinit().
ToBoolean()
Tagged< Boolean > v8::internal::Heap::ToBoolean (bool condition) [inline]
Definition at line 381 of file heap-inl.h.
                                              {
  ReadOnlyRoots roots(this);
  return roots.boolean_value(condition);
}
References v8::internal::ReadOnlyRoots::boolean_value().
Referenced by v8::internal::anonymous_namespace{runtime-object.cc}::DeleteProperty(), v8::internal::RUNTIME_FUNCTION(), v8::internal::Object::ToBoolean(), and v8::internal::PropertyDescriptor::ToObject().
TotalGlobalHandlesSize()
size_t v8::internal::Heap::TotalGlobalHandlesSize ()
Definition at line 1017 of file heap.cc.
                                    {
  return isolate_->global_handles()->TotalSize() +
         isolate_->traced_handles()->total_size_bytes();
}
References v8::internal::Isolate::global_handles(), isolate_, v8::internal::TracedHandles::total_size_bytes(), v8::internal::GlobalHandles::TotalSize(), and v8::internal::Isolate::traced_handles().
tracer() [1/2]
GCTracer* v8::internal::Heap::tracer () [inline]
Definition at line 843 of file heap.h.
{ return tracer_.get(); }
Referenced by v8::internal::CppHeap::MetricRecorderAdapter::AddMainThreadEvent(), v8::internal::IncrementalMarkingJob::AverageTimeToTask(), CallGCEpilogueCallbacks(), CallGCPrologueCallbacks(), v8::internal::MinorMarkSweepCollector::ClearNonLiveReferences(), v8::internal::MinorMarkSweepCollector::CollectGarbage(), v8::internal::ScavengerCollector::CollectGarbage(), CollectGarbage(), v8::internal::anonymous_namespace{heap.cc}::CompleteArrayBufferSweeping(), CompleteSweepingFull(), v8::internal::ScavengerCollector::CompleteSweepingQuarantinedPagesIfNeeded(), v8::internal::MarkCompactCollector::ComputeEvacuationHeuristics(), v8::internal::Sweeper::EnsureMajorCompleted(), v8::internal::Sweeper::EnsurePageIsSwept(), EnsureSweepingCompleted(), EnsureYoungSweepingCompleted(), v8::internal::GlobalSafepoint::EnterGlobalSafepointScope(), v8::internal::IsolateSafepoint::EnterLocalSafepointScope(), v8::internal::MarkCompactCollector::Finish(), v8::internal::MinorMarkSweepCollector::Finish(), v8::internal::MinorMarkSweepCollector::FinishConcurrentMarking(), v8::internal::Sweeper::FinishMajorJobs(), v8::internal::CppHeap::FinishMarkingAndProcessWeakness(), v8::internal::Sweeper::FinishMinorJobs(), GarbageCollectionEpilogue(), GarbageCollectionEpilogueInSafepoint(), GarbageCollectionPrologue(), GarbageCollectionPrologueInSafepoint(), v8::internal::ArrayBufferSweeper::GetTraceIdForFlowEvent(), HasLowEmbedderAllocationRate(), HasLowOldGenerationAllocationRate(), HasLowYoungGenerationAllocationRate(), IncrementalMarkingLimitReached(), v8::internal::CppHeap::InitializeMarking(), InvokeNearHeapLimitCallback(), v8::internal::GlobalHandles::InvokeSecondPassPhantomCallbacks(), MarkCompactEpilogue(), MarkCompactPrologue(), v8::internal::MinorMarkSweepCollector::MarkLiveObjects(), v8::internal::MinorMarkSweepCollector::MarkRoots(), v8::internal::MarkCompactCollector::MarkRootsFromConservativeStack(), v8::internal::MinorMarkSweepCollector::MarkRootsFromConservativeStack(), v8::internal::MinorMarkSweepCollector::MarkRootsFromTracedHandles(), MinorMarkSweep(), NotifyContextDisposed(), PerformGarbageCollection(), v8::internal::MinorMarkSweepCollector::PerformWrapperTracing(), v8::internal::MarkCompactCollector::Prepare(), v8::internal::PretenuringHandler::ProcessPretenuringFeedback(), RecomputeLimits(), v8::internal::ArrayBufferSweeper::RequestSweep(), v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::Run(), v8::internal::ConcurrentMarking::JobTaskMajor::Run(), v8::internal::ConcurrentMarking::JobTaskMinor::Run(), v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::Run(), v8::internal::ConcurrentMarking::RunMajor(), v8::internal::ConcurrentMarking::RunMinorImpl(), Scavenge(), v8::internal::Isolate::SetPriority(), ShrinkOldGenerationAllocationLimitIfNotConfigured(), v8::internal::LocalHeap::SleepInSafepoint(), v8::internal::LocalHeap::SleepInUnpark(), v8::internal::IncrementalMarking::Start(), StartIncrementalMarking(), v8::internal::Sweeper::StartMajorSweeperTasks(), v8::internal::Sweeper::StartMajorSweeping(), v8::internal::MinorMarkSweepCollector::StartMarking(), v8::internal::MarkCompactCollector::StartMarking(), v8::internal::Sweeper::StartMinorSweeperTasks(), v8::internal::Sweeper::StartMinorSweeping(), v8::internal::MinorMarkSweepCollector::StartSweepNewSpace(), v8::internal::MinorMarkSweepCollector::StartSweepNewSpaceWithStickyBits(), v8::internal::IncrementalMarking::Step(), v8::internal::MinorMarkSweepCollector::Sweep(), v8::internal::Sweeper::SweepEmptyNewSpacePage(), v8::internal::MinorMarkSweepCollector::SweepNewLargeSpace(), v8::internal::anonymous_namespace{mark-compact.cc}::TraceEvacuation(), UpdateSurvivalStatistics(), and v8::internal::MarkCompactCollector::VerifyMarking().
tracer() [2/2]
const GCTracer* v8::internal::Heap::tracer () const [inline]
Definition at line 844 of file heap.h.
{ return tracer_.get(); }
trusted_lo_space()
TrustedLargeObjectSpace* v8::internal::Heap::trusted_lo_space () const [inline]
Definition at line 786 of file heap.h.
                                                    {
    return trusted_lo_space_;
  }
Referenced by DeactivateMajorGCInProgressFlag(), v8::internal::OldGenerationMemoryChunkIterator::next(), OldGenerationSizeOfObjects(), and Unmark().
trusted_space()
TrustedSpace* v8::internal::Heap::trusted_space () const [inline]
Definition at line 782 of file heap.h.
{ return trusted_space_; }
Referenced by DeactivateMajorGCInProgressFlag(), EnsureSweepingCompleted(), v8::internal::EvacuationAllocator::Finalize(), v8::internal::OldGenerationMemoryChunkIterator::next(), OldGenerationSizeOfObjects(), v8::internal::HeapAllocator::Setup(), v8::internal::MarkCompactCollector::StartCompaction(), Unmark(), and v8::internal::MarkCompactCollector::VerifyMarking().
TryFindCodeForInnerPointerForPrinting()
std::optional< Tagged< Code > > v8::internal::Heap::TryFindCodeForInnerPointerForPrinting (Address inner_pointer)
Definition at line 7364 of file heap.cc.
                           {
  if (InSpaceSlow(inner_pointer, i::CODE_SPACE) ||
      InSpaceSlow(inner_pointer, i::CODE_LO_SPACE) ||
      i::OffHeapInstructionStream::PcIsOffHeap(isolate(), inner_pointer)) {
    std::optional<Tagged<GcSafeCode>> maybe_code =
        GcSafeTryFindCodeForInnerPointer(inner_pointer);
    if (maybe_code.has_value()) {
      return maybe_code.value()->UnsafeCastToCode();
    }
  }
  return {};
}
References v8::internal::CODE_LO_SPACE, v8::internal::CODE_SPACE, GcSafeTryFindCodeForInnerPointer(), InSpaceSlow(), isolate(), and v8::internal::OffHeapInstructionStream::PcIsOffHeap().
Referenced by _v8_internal_Print_Code(), and _v8_internal_Print_OnlyCode().
Unmark()
void v8::internal::Heap::Unmark ()
Definition at line 3726 of file heap.cc.
                  {
  DCHECK(v8_flags.sticky_mark_bits);
  DCHECK_NULL(new_space());
  auto unmark_space = [](auto& space) {
    for (auto* page : space) {
      page->marking_bitmap()->template Clear<AccessMode::NON_ATOMIC>();
      page->Chunk()->SetMajorGCInProgress();
      page->SetLiveBytes(0);
    }
  };
  unmark_space(*old_space());
  unmark_space(*lo_space());
  if (isolate()->is_shared_space_isolate()) {
    unmark_space(*shared_space());
    unmark_space(*shared_lo_space());
  }
  {
    RwxMemoryWriteScope scope("For writing flags.");
    unmark_space(*code_space());
    unmark_space(*code_lo_space());
  }
  unmark_space(*trusted_space());
  unmark_space(*trusted_lo_space());
}
References code_lo_space(), code_space(), v8::internal::DCHECK(), DCHECK_NULL, isolate(), lo_space(), new_space(), old_space(), shared_lo_space(), shared_space(), space(), trusted_lo_space(), trusted_space(), and v8::internal::v8_flags.
Referenced by v8::internal::MarkCompactCollector::StartMarking().
UnmarkSharedLinearAllocationAreas()
void v8::internal::Heap::UnmarkSharedLinearAllocationAreas () [private]
Definition at line 3707 of file heap.cc.
                                             {
  DCHECK(!v8_flags.black_allocated_pages);
  allocator()->UnmarkSharedLinearAllocationAreas();
  main_thread_local_heap()->UnmarkSharedLinearAllocationsArea();
  safepoint()->IterateLocalHeaps([](LocalHeap* local_heap) {
    local_heap->UnmarkSharedLinearAllocationsArea();
  });
}
References allocator(), v8::internal::DCHECK(), v8::internal::IsolateSafepoint::IterateLocalHeaps(), main_thread_local_heap(), safepoint(), v8::internal::HeapAllocator::UnmarkSharedLinearAllocationAreas(), v8::internal::LocalHeap::UnmarkSharedLinearAllocationsArea(), and v8::internal::v8_flags.
UnregisterStrongRoots()
void v8::internal::Heap::UnregisterStrongRoots (StrongRootsEntry * entry)
Definition at line 7006 of file heap.cc.
                                                        {
  // We're either on the main thread, or in a background thread with an active
  // local heap.
  DCHECK(isolate()->CurrentLocalHeap()->IsRunning());
  base::MutexGuard guard(&strong_roots_mutex_);
  StrongRootsEntry* prev = entry->prev;
  StrongRootsEntry* next = entry->next;
  if (prev) prev->next = next;
  if (next) next->prev = prev;
  if (strong_roots_head_ == entry) {
    DCHECK_NULL(prev);
    strong_roots_head_ = next;
  }
  delete entry;
}
References v8::internal::DCHECK(), DCHECK_NULL, isolate(), v8::internal::StrongRootsEntry::next, v8::internal::StrongRootsEntry::prev, strong_roots_head_, and strong_roots_mutex_.
Referenced by v8::internal::IdentityMapBase::Clear().
UpdateExternalMemory()
uint64_t v8::internal::Heap::UpdateExternalMemory (int64_t delta)
Definition at line 6963 of file heap.cc.
                                                 {
  uint64_t amount = external_memory_.UpdateAmount(delta);
  uint64_t low_since_mark_compact = external_memory_.low_since_mark_compact();
  if (amount < low_since_mark_compact) {
    external_memory_.UpdateLowSinceMarkCompact(amount);
  }
  return amount;
}
References external_memory_, v8::internal::Heap::ExternalMemoryAccounting::low_since_mark_compact(), v8::internal::Heap::ExternalMemoryAccounting::UpdateAmount(), and v8::internal::Heap::ExternalMemoryAccounting::UpdateLowSinceMarkCompact().
Referenced by v8::Isolate::AdjustAmountOfExternalAllocatedMemoryImpl(), and v8::ExternalMemoryAccounter::Decrease().
UpdateExternalString()
void v8::internal::Heap::UpdateExternalString (Tagged< String > string, size_t old_payload, size_t new_payload)
Definition at line 2823 of file heap.cc.
                                                    {
  DCHECK(IsExternalString(string));
  PageMetadata* page = PageMetadata::FromHeapObject(string);
  if (old_payload > new_payload) {
    page->DecrementExternalBackingStoreBytes(
        ExternalBackingStoreType::kExternalString, old_payload - new_payload);
  } else {
    page->IncrementExternalBackingStoreBytes(
        ExternalBackingStoreType::kExternalString, new_payload - old_payload);
  }
}
References v8::internal::DCHECK(), v8::internal::MutablePageMetadata::DecrementExternalBackingStoreBytes(), v8::internal::PageMetadata::FromHeapObject(), v8::internal::MutablePageMetadata::IncrementExternalBackingStoreBytes(), v8::internal::InstanceTypeChecker::IsExternalString(), and v8::internal::kExternalString.
Referenced by v8::internal::anonymous_namespace{string.cc}::MigrateExternalStringResource(), v8::internal::anonymous_namespace{deserializer.cc}::PostProcessExternalString(), v8::internal::ExternalOneByteString::SetResource(), and v8::internal::ExternalTwoByteString::SetResource().
UpdateMaximumCommitted()
void v8::internal::Heap::UpdateMaximumCommitted ()
Definition at line 391 of file heap.cc.
                                  {
  if (!HasBeenSetUp()) return;
  const size_t current_committed_memory = CommittedMemory();
  if (current_committed_memory > maximum_committed_) {
    maximum_committed_ = current_committed_memory;
  }
}
References CommittedMemory(), HasBeenSetUp(), and maximum_committed_.
Referenced by GarbageCollectionEpilogue(), GarbageCollectionPrologue(), and TearDown().
UpdateOldGenerationAllocationCounter()
void v8::internal::Heap::UpdateOldGenerationAllocationCounter () [inline]
Definition at line 1393 of file heap.h.
                                              {
    old_generation_allocation_counter_at_last_gc_ =
        OldGenerationAllocationCounter();
  }
Referenced by MarkCompact(), and RecomputeLimitsAfterLoadingIfNeeded().
UpdateReferencesInExternalStringTable()
void v8::internal::Heap::UpdateReferencesInExternalStringTable (ExternalStringTableUpdaterCallback updater_func) [private]
Definition at line 3008 of file heap.cc.
                                                     {
  external_string_table_.UpdateReferences(updater_func);
}
References external_string_table_, and v8::internal::Heap::ExternalStringTable::UpdateReferences().
UpdateStrongRoots()
void v8::internal::Heap::UpdateStrongRoots (StrongRootsEntry * entry, FullObjectSlot start, FullObjectSlot end)
Definition at line 7000 of file heap.cc.
                                                 {
  entry->start = start;
  entry->end = end;
}
References v8::internal::compiler::end(), v8::internal::StrongRootsEntry::end, and v8::internal::StrongRootsEntry::start.
Referenced by v8::internal::IdentityMapBase::Resize().
UpdateSurvivalStatistics()
void v8::internal::Heap::UpdateSurvivalStatistics (int start_new_space_size)
Definition at line 2247 of file heap.cc.
                                                            {
  if (start_new_space_size == 0) return;
  promotion_ratio_ = (static_cast<double>(promoted_objects_size_) /
                      static_cast<double>(start_new_space_size) * 100);
  if (previous_new_space_surviving_object_size_ > 0) {
    promotion_rate_ =
        (static_cast<double>(promoted_objects_size_) /
         static_cast<double>(previous_new_space_surviving_object_size_) * 100);
  } else {
    promotion_rate_ = 0;
  }
  new_space_surviving_rate_ =
      (static_cast<double>(new_space_surviving_object_size_) /
       static_cast<double>(start_new_space_size) * 100);
  double survival_rate = promotion_ratio_ + new_space_surviving_rate_;
  tracer()->AddSurvivalRatio(survival_rate);
}
References v8::internal::GCTracer::AddSurvivalRatio(), new_space_surviving_object_size_, new_space_surviving_rate_, previous_new_space_surviving_object_size_, promoted_objects_size_, promotion_rate_, promotion_ratio_, and tracer().
Referenced by PerformGarbageCollection().
UpdateTotalGCTime()
void v8::internal::Heap::UpdateTotalGCTime (base::TimeDelta duration) [private]
Definition at line 6883 of file heap.cc.
                                                   {
  total_gc_time_ms_ += duration;
}
References v8::internal::duration, and total_gc_time_ms_.
Referenced by v8::internal::GCTracer::StopObservablePause().
UpdateYoungReferenceInExternalStringTableEntry()
Tagged< String > v8::internal::Heap::UpdateYoungReferenceInExternalStringTableEntry (Heap * heap, FullObjectSlot pointer) [static]
Definition at line 2838 of file heap.cc.
                                  {
  // This is only used for Scavenger.
  DCHECK(!v8_flags.minor_ms);
  PtrComprCageBase cage_base(heap->isolate());
  Tagged<HeapObject> obj = Cast<HeapObject>(*p);
  MapWord first_word = obj->map_word(cage_base, kRelaxedLoad);
  Tagged<String> new_string;
  if (InFromPage(obj)) {
    if (!first_word.IsForwardingAddress()) {
      // Unreachable external string can be finalized.
      Tagged<String> string = Cast<String>(obj);
      if (!IsExternalString(string, cage_base)) {
        // Original external string has been internalized.
        DCHECK(IsThinString(string, cage_base));
        return Tagged<String>();
      }
      heap->FinalizeExternalString(string);
      return Tagged<String>();
    }
    new_string = Cast<String>(first_word.ToForwardingAddress(obj));
  } else {
    new_string = Cast<String>(obj);
  }
  // String is still reachable.
  if (IsThinString(new_string, cage_base)) {
    // Filtering Thin strings out of the external string table.
    return Tagged<String>();
  } else if (IsExternalString(new_string, cage_base)) {
    MutablePageMetadata::MoveExternalBackingStoreBytes(
        ExternalBackingStoreType::kExternalString,
        PageMetadata::FromAddress((*p).ptr()),
        PageMetadata::FromHeapObject(new_string),
        Cast<ExternalString>(new_string)->ExternalPayloadSize());
    return new_string;
  }
  // Internalization can replace external strings with non-external strings.
  return IsExternalString(new_string, cage_base) ? new_string
                                                 : Tagged<String>();
}
References v8::internal::DCHECK(), v8::internal::PageMetadata::FromAddress(), v8::internal::PageMetadata::FromHeapObject(), InFromPage(), v8::internal::InstanceTypeChecker::IsExternalString(), v8::internal::MapWord::IsForwardingAddress(), v8::internal::InstanceTypeChecker::IsThinString(), v8::internal::kExternalString, v8::kRelaxedLoad, v8::internal::MutablePageMetadata::MoveExternalBackingStoreBytes(), v8::internal::MapWord::ToForwardingAddress(), and v8::internal::v8_flags.
UpdateYoungReferencesInExternalStringTable()
void v8::internal::Heap::UpdateYoungReferencesInExternalStringTable (ExternalStringTableUpdaterCallback updater_func) [private]
Definition at line 2991 of file heap.cc.
                                                     {
  external_string_table_.UpdateYoungReferences(updater_func);
}
References external_string_table_, and v8::internal::Heap::ExternalStringTable::UpdateYoungReferences().
Referenced by v8::internal::MinorMarkSweepCollector::Sweep().
use_new_space()
bool v8::internal::Heap::use_new_space () const [inline]
Definition at line 1699 of file heap.h.
                             {
    DCHECK_IMPLIES(new_space(), !v8_flags.sticky_mark_bits);
    return new_space() || v8_flags.sticky_mark_bits;
  }
References DCHECK_IMPLIES, and v8::internal::v8_flags.
Referenced by v8::internal::MinorMarkSweepCollector::CollectGarbage(), EnsureSweepingCompleted(), GarbageCollectionPrologue(), MinorMarkSweep(), v8::internal::MarkCompactCollector::Prepare(), v8::internal::ConcurrentMarking::RunMajor(), v8::internal::ConcurrentMarking::RunMinor(), and SelectGarbageCollector().
UsedGlobalHandlesSize()
size_t v8::internal::Heap::UsedGlobalHandlesSize ()
Definition at line 1022 of file heap.cc.
                                   {
  return isolate_->global_handles()->UsedSize() +
         isolate_->traced_handles()->used_size_bytes();
}
References v8::internal::Isolate::global_handles(), isolate_, v8::internal::Isolate::traced_handles(), v8::internal::TracedHandles::used_size_bytes(), and v8::internal::GlobalHandles::UsedSize().
using_initial_limit()
bool v8::internal::Heap::using_initial_limit () const [inline], [private]
Definition at line 1991 of file heap.h.
                                   {
    return using_initial_limit_.load(std::memory_order_relaxed);
  }
Referenced by EnsureSweepingCompleted(), IncrementalMarkingLimitReached(), PerformGarbageCollection(), RecomputeLimits(), and ShrinkOldGenerationAllocationLimitIfNotConfigured().
WeakenDescriptorArrays()
void v8::internal::Heap::WeakenDescriptorArrays (GlobalHandleVector< DescriptorArray > strong_descriptor_arrays)
Definition at line 6132 of file heap.cc.
                                                                  {
  if (incremental_marking()->IsMajorMarking()) {
    // During incremental/concurrent marking regular DescriptorArray objects are
    // treated with custom weakness. This weakness depends on
    // DescriptorArray::raw_gc_state() which is not set up properly upon
    // deserialization. The strong arrays are transitioned to weak ones at the
    // end of the GC.
    mark_compact_collector()->RecordStrongDescriptorArraysForWeakening(
        std::move(strong_descriptor_arrays));
    return;
  }
  // No GC is running, weaken the arrays right away.
  DisallowGarbageCollection no_gc;
  Tagged<Map> descriptor_array_map =
      ReadOnlyRoots(isolate()).descriptor_array_map();
  for (auto it = strong_descriptor_arrays.begin();
       it != strong_descriptor_arrays.end(); ++it) {
    Tagged<DescriptorArray> array = it.raw();
    DCHECK(IsStrongDescriptorArray(array));
    array->set_map_safe_transition_no_write_barrier(isolate(),
                                                    descriptor_array_map);
    DCHECK_EQ(array->raw_gc_state(kRelaxedLoad), 0);
  }
}
References v8::internal::GlobalHandleVector< T >::begin(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::GlobalHandleVector< T >::end(), incremental_marking(), isolate(), v8::kRelaxedLoad, mark_compact_collector(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, ReadOnlyRoots, and v8::internal::MarkCompactCollector::RecordStrongDescriptorArraysForWeakening().
Referenced by v8::internal::LocalHeap::WeakenDescriptorArrays().
YoungArrayBufferBytes()
size_t v8::internal::Heap::YoungArrayBufferBytes ()
Definition at line 6959 of file heap.cc.
                                   {
  return array_buffer_sweeper()->YoungBytes();
}
References array_buffer_sweeper(), and v8::internal::ArrayBufferSweeper::YoungBytes().
YoungGenerationCollector()
static GarbageCollector v8::internal::Heap::YoungGenerationCollector () [inline], [static]
Definition at line 368 of file heap.h.
                                                            {
    return (v8_flags.minor_ms) ? GarbageCollector::MINOR_MARK_SWEEPER
                               : GarbageCollector::SCAVENGER;
  }
References v8::internal::v8_flags.
Referenced by SelectGarbageCollector().
YoungGenerationConsumedBytes()
size_t v8::internal::Heap::YoungGenerationConsumedBytes () const
Definition at line 5402 of file heap.cc.
                                                {
  if (!new_space()) {
    return 0;
  }
  DCHECK_NOT_NULL(new_lo_space());
  if (v8_flags.minor_ms) {
    return YoungGenerationSizeOfObjects() + YoungGenerationWastedBytes();
  }
  // When using Scavenger, memory is compacted. Thus wasted space is always 0.
  // The diff between `new_space()->SizeOfObjects()` and
  // `new_space()->CurrentCapacitySafe()` is less than one page. Using capacity
  // here is also easier for concurrency since this method is reachable from
  // background old allocations.
  return semi_space_new_space()->CurrentCapacitySafe() +
         new_lo_space()->SizeOfObjects();
}
References v8::internal::SemiSpaceNewSpace::CurrentCapacitySafe(), DCHECK_NOT_NULL, new_lo_space(), new_space(), semi_space_new_space(), v8::internal::LargeObjectSpace::SizeOfObjects(), v8::internal::v8_flags, YoungGenerationSizeOfObjects(), and YoungGenerationWastedBytes().
Referenced by AllocationLimitOvershotByLargeMargin().
YoungGenerationSizeFromOldGenerationSize()
size_t v8::internal::Heap::YoungGenerationSizeFromOldGenerationSize (size_t old_generation_size) [static]
Definition at line 209 of file heap.cc.
                                                                           {
  // Compute the semi space size and cap it.
  bool is_low_memory = old_generation <= Heap::OldGenerationLowMemory();
  size_t semi_space;
  if (v8_flags.minor_ms && !is_low_memory) {
    semi_space = DefaultMaxSemiSpaceSize();
  } else {
    size_t ratio = is_low_memory ? OldGenerationToSemiSpaceRatioLowMemory()
                                 : OldGenerationToSemiSpaceRatio();
    semi_space = old_generation / ratio;
    semi_space = std::min({semi_space, DefaultMaxSemiSpaceSize()});
    semi_space = std::max({semi_space, DefaultMinSemiSpaceSize()});
    semi_space = RoundUp(semi_space, PageMetadata::kPageSize);
  }
  return YoungGenerationSizeFromSemiSpaceSize(semi_space);
}
References DefaultMaxSemiSpaceSize(), DefaultMinSemiSpaceSize(), v8::internal::MutablePageMetadata::kPageSize, OldGenerationLowMemory(), OldGenerationToSemiSpaceRatio(), OldGenerationToSemiSpaceRatioLowMemory(), RoundUp(), v8::internal::v8_flags, and YoungGenerationSizeFromSemiSpaceSize().
Referenced by GenerationSizesFromHeapSize(), and HeapSizeFromPhysicalMemory().
YoungGenerationSizeFromSemiSpaceSize()
size_t v8::internal::Heap::YoungGenerationSizeFromSemiSpaceSize (size_t semi_space_size) [static]
Definition at line 315 of file heap.cc.
                                                                        {
  return semi_space_size *
         (NumberOfSemiSpaces() + kNewLargeObjectSpaceToSemiSpaceRatio);
}
References kNewLargeObjectSpaceToSemiSpaceRatio, and v8::internal::anonymous_namespace{heap.cc}::NumberOfSemiSpaces().
Referenced by AllocatorLimitOnMaxOldGenerationSize(), ConfigureHeap(), MinYoungGenerationSize(), and YoungGenerationSizeFromOldGenerationSize().
YoungGenerationSizeOfObjects()
size_t v8::internal::Heap::YoungGenerationSizeOfObjects () const
Definition at line 5385 of file heap.cc.
                                                {
  DCHECK_NOT_NULL(new_space());
  DCHECK_NOT_NULL(new_lo_space());
  if (v8_flags.sticky_mark_bits) {
    return sticky_space()->young_objects_size() +
           new_lo_space()->SizeOfObjects();
  }
  DCHECK_NOT_NULL(new_lo_space());
  return new_space()->SizeOfObjects() + new_lo_space()->SizeOfObjects();
}
References DCHECK_NOT_NULL, new_lo_space(), new_space(), v8::internal::LargeObjectSpace::SizeOfObjects(), sticky_space(), v8::internal::v8_flags, and v8::internal::StickySpace::young_objects_size().
Referenced by YoungGenerationConsumedBytes().
YoungGenerationWastedBytes()
size_t v8::internal::Heap::YoungGenerationWastedBytes () const
Definition at line 5396 of file heap.cc.
                                              {
  DCHECK_NOT_NULL(new_space());
  DCHECK(v8_flags.minor_ms);
  return paged_new_space()->paged_space()->Waste();
}
References v8::internal::DCHECK(), DCHECK_NOT_NULL, new_space(), paged_new_space(), v8::internal::PagedNewSpace::paged_space(), v8::internal::v8_flags, and v8::internal::PagedSpaceBase::Waste().
Referenced by YoungGenerationConsumedBytes().
Friends And Related Function Documentation
ActivateMemoryReducerTask
friend class ActivateMemoryReducerTask [friend]
Definition at line 2483 of file heap.h.
AlwaysAllocateScope
friend class AlwaysAllocateScope [friend]
Definition at line 2484 of file heap.h.
ArrayBufferCollector
friend class ArrayBufferCollector [friend]
Definition at line 2485 of file heap.h.
ArrayBufferSweeper
friend class ArrayBufferSweeper [friend]
Definition at line 2486 of file heap.h.
Referenced by SetUpSpaces().
ConcurrentMarking
friend class ConcurrentMarking [friend]
Definition at line 2488 of file heap.h.
Referenced by SetUp().
ConservativePinningScope
friend class ConservativePinningScope [friend]
Definition at line 2487 of file heap.h.
ConservativeTracedHandlesMarkingVisitor
friend class ConservativeTracedHandlesMarkingVisitor [friend]
Definition at line 2489 of file heap.h.
CppHeap
friend class CppHeap [friend]
Definition at line 2490 of file heap.h.
Deserializer
template<typename IsolateT >
friend class Deserializer [friend]
Definition at line 2541 of file heap.h.
DisableConservativeStackScanningScopeForTesting
friend class DisableConservativeStackScanningScopeForTesting [friend]
Definition at line 2524 of file heap.h.
EmbedderStackStateScope
friend class EmbedderStackStateScope [friend]
Definition at line 2491 of file heap.h.
EvacuateVisitorBase
friend class EvacuateVisitorBase [friend]
Definition at line 2492 of file heap.h.
Factory
friend class Factory [friend]
Definition at line 2538 of file heap.h.
GCCallbacksScope
friend class GCCallbacksScope [friend]
Definition at line 2493 of file heap.h.
GCTracer
friend class GCTracer [friend]
Definition at line 2494 of file heap.h.
Referenced by SetUpSpaces().
heap::HeapTester
friend class heap::HeapTester [friend]
Definition at line 2547 of file heap.h.
heap::TestMemoryAllocatorScope
friend class heap::TestMemoryAllocatorScope [friend]
Definition at line 2535 of file heap.h.
HeapAllocator
friend class HeapAllocator [friend]
Definition at line 2495 of file heap.h.
HeapInternalsBase
friend class HeapInternalsBase [friend]
Definition at line 2550 of file heap.h.
HeapObjectIterator
friend class HeapObjectIterator [friend]
Definition at line 2496 of file heap.h.
HeapVerifier
friend class HeapVerifier [friend]
Definition at line 2497 of file heap.h.
IgnoreLocalGCRequests
friend class IgnoreLocalGCRequests [friend]
Definition at line 2498 of file heap.h.
IncrementalMarking
friend class IncrementalMarking [friend]
Definition at line 2499 of file heap.h.
Referenced by SetUp().
IncrementalMarkingJob
friend class IncrementalMarkingJob [friend]
Definition at line 2500 of file heap.h.
Isolate
friend class Isolate [friend]
Definition at line 2544 of file heap.h.
LargeObjectSpace
friend class LargeObjectSpace [friend]
Definition at line 2501 of file heap.h.
LocalFactory
friend class LocalFactory [friend]
Definition at line 2539 of file heap.h.
LocalHeap
friend class LocalHeap [friend]
Definition at line 2502 of file heap.h.
MarkCompactCollector
friend class MarkCompactCollector [friend]
Definition at line 2507 of file heap.h.
Referenced by SetUp().
MarkingBarrier
friend class MarkingBarrier [friend]
Definition at line 2503 of file heap.h.
MarkingVisitorBase
template<typename ConcreteVisitor >
friend class MarkingVisitorBase [friend]
Definition at line 2506 of file heap.h.
MemoryBalancer
friend class MemoryBalancer [friend]
Definition at line 2508 of file heap.h.
Referenced by SetUpSpaces().
MinorGCJob
friend class MinorGCJob [friend]
Definition at line 2509 of file heap.h.
Referenced by SetUpSpaces().
MinorGCTaskObserver
friend class MinorGCTaskObserver [friend]
Definition at line 2510 of file heap.h.
MinorMarkSweepCollector
friend class MinorMarkSweepCollector [friend]
Definition at line 2511 of file heap.h.
Referenced by SetUp().
MinorMSIncrementalMarkingTaskObserver
friend class MinorMSIncrementalMarkingTaskObserver [friend]
Definition at line 2512 of file heap.h.
NewLargeObjectSpace
friend class NewLargeObjectSpace [friend]
Definition at line 2513 of file heap.h.
NewSpace
friend class NewSpace [friend]
Definition at line 2514 of file heap.h.
ObjectStatsCollector
friend class ObjectStatsCollector [friend]
Definition at line 2515 of file heap.h.
OldLargeObjectSpace
friend class OldLargeObjectSpace [friend]
Definition at line 2504 of file heap.h.
PagedNewSpaceAllocatorPolicy
friend class PagedNewSpaceAllocatorPolicy [friend]
Definition at line 2517 of file heap.h.
PagedSpaceAllocatorPolicy
friend class PagedSpaceAllocatorPolicy [friend]
Definition at line 2518 of file heap.h.
PagedSpaceBase
friend class PagedSpaceBase [friend]
Definition at line 2519 of file heap.h.
PagedSpaceForNewSpace
friend class PagedSpaceForNewSpace [friend]
Definition at line 2520 of file heap.h.
PageMetadata
friend class PageMetadata [friend]
Definition at line 2516 of file heap.h.
PauseAllocationObserversScope
friend class PauseAllocationObserversScope [friend]
Definition at line 2521 of file heap.h.
PretenuringHandler
friend class PretenuringHandler [friend]
Definition at line 2522 of file heap.h.
ReadOnlyRoots
friend class ReadOnlyRoots [friend]
Definition at line 2523 of file heap.h.
Referenced by AllowedToBeMigrated(), ClearKeptObjects(), CompactRetainedMaps(), CompactWeakArrayLists(), DequeueDirtyJSFinalizationRegistry(), GcSafeInstructionStreamContains(), InitializeHashSeed(), v8::internal::ClearStaleLeftTrimmedPointerVisitor::IsLeftTrimmed(), LeftTrimFixedArray(), NotifyContextDisposed(), RemoveDirtyFinalizationRegistriesOnContext(), and WeakenDescriptorArrays().
Scavenger
friend class Scavenger [friend]
Definition at line 2525 of file heap.h.
ScavengerCollector
friend class ScavengerCollector [friend]
Definition at line 2526 of file heap.h.
Referenced by SetUp().
ScheduleMinorGCTaskObserver
friend class ScheduleMinorGCTaskObserver [friend]
Definition at line 2527 of file heap.h.
SemiSpaceNewSpace
friend class SemiSpaceNewSpace [friend]
Definition at line 2528 of file heap.h.
SemiSpaceNewSpaceAllocatorPolicy
friend class SemiSpaceNewSpaceAllocatorPolicy [friend]
Definition at line 2529 of file heap.h.
Space
friend class Space [friend]
Definition at line 2531 of file heap.h.
SpaceWithLinearArea
friend class SpaceWithLinearArea [friend]
Definition at line 2532 of file heap.h.
StressConcurrentAllocationObserver
friend class StressConcurrentAllocationObserver [friend]
Definition at line 2530 of file heap.h.
Referenced by NotifyDeserializationComplete().
Sweeper
friend class Sweeper [friend]
Definition at line 2533 of file heap.h.
Referenced by SetUp().
UnifiedHeapMarkingState
friend class UnifiedHeapMarkingState [friend]
Definition at line 2534 of file heap.h.
Member Data Documentation
allocation_sites_list_
Tagged<UnionOf<Smi, Undefined, AllocationSiteWithWeakNext> > v8::internal::Heap::allocation_sites_list_ = Smi::zero() [private]
Definition at line 2301 of file heap.h.
allocation_tracker_for_debugging_
std::unique_ptr<AllocationTrackerForDebugging> v8::internal::Heap::allocation_tracker_for_debugging_ [private]
Definition at line 2346 of file heap.h.
Referenced by SetUpSpaces(), and TearDown().
allocation_trackers_
std::vector<HeapObjectAllocationTracker*> v8::internal::Heap::allocation_trackers_ [private]
Definition at line 2452 of file heap.h.
Referenced by AddHeapObjectAllocationTracker(), v8::internal::HeapAllocator::AllocateRaw(), OnMoveEvent(), RemoveHeapObjectAllocationTracker(), and RightTrimArray().
allocation_type_for_in_place_internalizable_strings_
const AllocationType v8::internal::Heap::allocation_type_for_in_place_internalizable_strings_ [private]
Definition at line 2431 of file heap.h.
always_allocate_scope_count_
std::atomic<size_t> v8::internal::Heap::always_allocate_scope_count_ {0} [private]
Definition at line 2194 of file heap.h.
Referenced by v8::internal::AlwaysAllocateScope::AlwaysAllocateScope(), and v8::internal::AlwaysAllocateScope::~AlwaysAllocateScope().
array_buffer_sweeper_
std::unique_ptr<ArrayBufferSweeper> v8::internal::Heap::array_buffer_sweeper_ [private]
Definition at line 2334 of file heap.h.
Referenced by AppendArrayBufferExtension(), DetachArrayBufferExtension(), ResizeArrayBufferExtension(), SetUpSpaces(), and TearDown().
backing_store_bytes_
std::atomic<uint64_t> v8::internal::Heap::backing_store_bytes_ {0} [private]
Definition at line 2186 of file heap.h.
Referenced by DecrementExternalBackingStoreBytes(), and IncrementExternalBackingStoreBytes().
code_lo_space_
CodeLargeObjectSpace* v8::internal::Heap::code_lo_space_ = nullptr [private]
Definition at line 2212 of file heap.h.
Referenced by CollectCodeStatistics(), CommittedOldGenerationMemory(), Contains(), ContainsCode(), InSpace(), InSpaceSlow(), OldGenerationCapacity(), PrintShortHeapStatistics(), RecordStats(), and SetUpSpaces().
code_range_
std::unique_ptr<CodeRange> v8::internal::Heap::code_range_ [private]
Definition at line 2360 of file heap.h.
Referenced by code_range_base(), code_region(), v8::internal::Isolate::MaybeRemapEmbeddedBuiltinsIntoCodeRange(), and SetUp().
code_range_size_
size_t v8::internal::Heap::code_range_size_ = 0 [private]
Definition at line 2143 of file heap.h.
Referenced by ConfigureHeap(), and SetUp().
code_space_
CodeSpace* v8::internal::Heap::code_space_ = nullptr [private]
Definition at line 2209 of file heap.h.
Referenced by CollectCodeStatistics(), Contains(), ContainsCode(), InSpace(), InSpaceSlow(), PrintShortHeapStatistics(), RecordStats(), and SetUpSpaces().
collection_barrier_
std::unique_ptr<CollectionBarrier> v8::internal::Heap::collection_barrier_ [private]
Definition at line 2433 of file heap.h.
Referenced by CollectGarbageFromAnyThread(), CollectionRequested(), GarbageCollectionEpilogueInSafepoint(), v8::internal::LocalHeap::ParkSlowPath(), PerformGarbageCollection(), SetUp(), and StartTearDown().
concurrent_marking_
std::unique_ptr<ConcurrentMarking> v8::internal::Heap::concurrent_marking_ [private]
Definition at line 2338 of file heap.h.
Referenced by SetUp(), and TearDown().
configured_
bool v8::internal::Heap::configured_ = false [private]
Definition at line 2413 of file heap.h.
Referenced by ConfigureHeap(), ResetOldGenerationAndGlobalAllocationLimit(), and SetUp().
consecutive_ineffective_mark_compacts_
int v8::internal::Heap::consecutive_ineffective_mark_compacts_ = 0 [private]
Definition at line 2279 of file heap.h.
Referenced by CheckIneffectiveMarkCompact().
contexts_disposed_
int v8::internal::Heap::contexts_disposed_ = 0 [private]
Definition at line 2204 of file heap.h.
Referenced by MarkCompact(), and NotifyContextDisposed().
cpp_heap_
v8::CppHeap* v8::internal::Heap::cpp_heap_ = nullptr [private]
Definition at line 2370 of file heap.h.
Referenced by AttachCppHeap(), v8::internal::MinorMarkSweepCollector::ClearNonLiveReferences(), CollectAllAvailableGarbage(), v8::internal::MarkCompactCollector::CollectGarbage(), v8::internal::MinorMarkSweepCollector::CollectGarbage(), EmbedderAllocationCounter(), EmbedderSizeOfObjects(), v8::internal::MarkCompactCollector::FinishConcurrentMarking(), v8::internal::MinorMarkSweepCollector::FinishConcurrentMarking(), v8::internal::MinorMarkSweepCollector::MarkRootsFromTracedHandles(), v8::internal::MarkCompactCollector::MaybeEnableBackgroundThreadsInCycle(), v8::internal::MinorMarkSweepCollector::PerformWrapperTracing(), v8::internal::MarkCompactCollector::Prepare(), v8::internal::MinorMarkSweepCollector::StartMarking(), v8::internal::MarkCompactCollector::StartMarking(), StartTearDown(), and TearDown().
current_gc_callback_flags_
GCCallbackFlags v8::internal::Heap::current_gc_callback_flags_ [private]
Initial value:
=
      GCCallbackFlags::kNoGCCallbackFlags
Definition at line 2419 of file heap.h.
Referenced by CheckCollectionRequested(), CollectGarbageForBackground(), CollectGarbageFromAnyThread(), FinalizeIncrementalMarkingAtomically(), HandleExternalMemoryInterrupt(), HandleGCRequest(), and StartIncrementalMarking().
current_gc_flags_
GCFlags v8::internal::Heap::current_gc_flags_ = GCFlag::kNoFlags [private]
Definition at line 2416 of file heap.h.
Referenced by CheckCollectionRequested(), CollectAllAvailableGarbage(), CollectAllGarbage(), CollectGarbage(), CollectGarbageForBackground(), CollectGarbageFromAnyThread(), CollectGarbageWithRetry(), FinalizeIncrementalMarkingAtomically(), GarbageCollectionPrologue(), HandleGCRequest(), and StartIncrementalMarking().
current_or_last_garbage_collector_
GarbageCollector v8::internal::Heap::current_or_last_garbage_collector_ [private]
Initial value:
=
      GarbageCollector::SCAVENGER
Definition at line 2426 of file heap.h.
Referenced by CollectGarbage().
dead_object_stats_
std::unique_ptr<ObjectStats> v8::internal::Heap::dead_object_stats_ [private]
Definition at line 2342 of file heap.h.
Referenced by CreateObjectStats(), SetUpSpaces(), and TearDown().
deferred_counters_
base::SmallVector<v8::Isolate::UseCounterFeature, 8> v8::internal::Heap::deferred_counters_ [private]
Definition at line 2311 of file heap.h.
Referenced by IncrementDeferredCounts(), and ReportStatisticsAfterGC().
delay_sweeper_tasks_for_testing_
bool v8::internal::Heap::delay_sweeper_tasks_for_testing_ = false [private]
Definition at line 2450 of file heap.h.
Referenced by FinishSweepingIfOutOfWork().
deserialization_complete_
bool v8::internal::Heap::deserialization_complete_ = false [private]
Definition at line 2439 of file heap.h.
Referenced by CollectGarbage(), CollectGarbageShared(), InitializeHashSeed(), and NotifyDeserializationComplete().
dirty_js_finalization_registries_list_
Tagged<Object> v8::internal::Heap::dirty_js_finalization_registries_list_ = Smi::zero() [private]
Definition at line 2302 of file heap.h.
dirty_js_finalization_registries_list_tail_
Tagged<Object> v8::internal::Heap::dirty_js_finalization_registries_list_tail_ = Smi::zero() [private]
Definition at line 2304 of file heap.h.
embedder_roots_handler_
EmbedderRootsHandler* v8::internal::Heap::embedder_roots_handler_ [private]
Initial value:
=
      nullptr
Definition at line 2371 of file heap.h.
Referenced by GetEmbedderRootsHandler(), SetEmbedderRootsHandler(), and TearDown().
embedder_size_at_last_gc_
size_t v8::internal::Heap::embedder_size_at_last_gc_ = 0 [private]
Definition at line 2401 of file heap.h.
Referenced by GlobalConsumedBytesAtLastGC(), MarkCompact(), and RecomputeLimitsAfterLoadingIfNeeded().
embedder_stack_state_
StackState v8::internal::Heap::embedder_stack_state_ = StackState::kMayContainHeapPointers [private]
Definition at line 2374 of file heap.h.
Referenced by v8::internal::EmbedderStackStateScope::EmbedderStackStateScope(), IsGCWithMainThreadStack(), v8::internal::MinorMarkSweepCollector::MarkLiveObjects(), overridden_stack_state(), and v8::internal::EmbedderStackStateScope::~EmbedderStackStateScope().
embedder_stack_state_origin_
std::optional<EmbedderStackStateOrigin> v8::internal::Heap::embedder_stack_state_origin_ [private]
Definition at line 2375 of file heap.h.
Referenced by v8::internal::EmbedderStackStateScope::EmbedderStackStateScope(), overridden_stack_state(), and v8::internal::EmbedderStackStateScope::~EmbedderStackStateScope().
ephemeron_remembered_set_
std::unique_ptr<EphemeronRememberedSet> v8::internal::Heap::ephemeron_remembered_set_ [private]
Definition at line 2347 of file heap.h.
Referenced by SetUp(), and TearDown().
external_memory_
ExternalMemoryAccounting v8::internal::Heap::external_memory_ [private]
Definition at line 2133 of file heap.h.
Referenced by AllocatedExternalMemorySinceMarkCompact(), external_memory(), external_memory_limit_for_interrupt(), external_memory_soft_limit(), GlobalConsumedBytesAtLastGC(), HandleExternalMemoryInterrupt(), MarkCompact(), RecomputeLimitsAfterLoadingIfNeeded(), and UpdateExternalMemory().
external_memory_callback_
GetExternallyAllocatedMemoryInBytesCallback v8::internal::Heap::external_memory_callback_ [private]
Definition at line 2309 of file heap.h.
Referenced by PrintShortHeapStatistics().
external_string_table_
ExternalStringTable v8::internal::Heap::external_string_table_ [private]
Definition at line 2429 of file heap.h.
Referenced by v8::internal::MinorMarkSweepCollector::ClearNonLiveReferences(), IterateWeakRoots(), RegisterExternalString(), TearDownWithSharedHeap(), UpdateReferencesInExternalStringTable(), and UpdateYoungReferencesInExternalStringTable().
force_gc_on_next_allocation_
bool v8::internal::Heap::force_gc_on_next_allocation_ = false [private]
Definition at line 2449 of file heap.h.
Referenced by CanExpandOldGeneration(), and GarbageCollectionPrologue().
force_oom_
bool v8::internal::Heap::force_oom_ = false [private]
Definition at line 2448 of file heap.h.
Referenced by CanExpandOldGeneration().
gc_callbacks_depth_
int v8::internal::Heap::gc_callbacks_depth_ = 0 [private]
Definition at line 2437 of file heap.h.
Referenced by v8::internal::GCCallbacksScope::CheckReenter(), v8::internal::GCCallbacksScope::GCCallbacksScope(), StartIncrementalMarking(), and v8::internal::GCCallbacksScope::~GCCallbacksScope().
gc_count_
unsigned int v8::internal::Heap::gc_count_ = 0 [private]
Definition at line 2275 of file heap.h.
Referenced by CreateMutableHeapObjects(), GarbageCollectionPrologueInSafepoint(), IncrementalMarkingLimitReached(), and ShouldStressCompaction().
gc_epilogue_callbacks_
GCCallbacks v8::internal::Heap::gc_epilogue_callbacks_ [private]
Definition at line 2307 of file heap.h.
Referenced by AddGCEpilogueCallback(), CallGCEpilogueCallbacks(), and RemoveGCEpilogueCallback().
gc_prologue_callbacks_
GCCallbacks v8::internal::Heap::gc_prologue_callbacks_ [private]
Definition at line 2306 of file heap.h.
Referenced by AddGCPrologueCallback(), CallGCPrologueCallbacks(), and RemoveGCPrologueCallback().
gc_state_
std::atomic<HeapState> v8::internal::Heap::gc_state_ {NOT_IN_GC} [private]
Definition at line 2258 of file heap.h.
Referenced by SetGCState().
global_allocation_limit_
std::atomic<size_t> v8::internal::Heap::global_allocation_limit_ {0} [private]
Definition at line 2293 of file heap.h.
Referenced by SetOldGenerationAndGlobalAllocationLimit().
heap_allocator_
HeapAllocator* v8::internal::Heap::heap_allocator_ = nullptr [private]
Definition at line 2139 of file heap.h.
Referenced by AllocateRaw(), AllocateRawOrFail(), GarbageCollectionPrologue(), ReplaceReadOnlySpace(), SetUp(), and SetUpFromReadOnlyHeap().
heap_expansion_mutex_
base::Mutex v8::internal::Heap::heap_expansion_mutex_ [private]
Definition at line 2380 of file heap.h.
heap_profiler_
std::unique_ptr<HeapProfiler> v8::internal::Heap::heap_profiler_ [private]
Definition at line 2348 of file heap.h.
Referenced by ConfigureHeap(), and TearDown().
ignore_local_gc_requests_depth_
int v8::internal::Heap::ignore_local_gc_requests_depth_ = 0 [private]
Definition at line 2435 of file heap.h.
Referenced by v8::internal::IgnoreLocalGCRequests::IgnoreLocalGCRequests(), and v8::internal::IgnoreLocalGCRequests::~IgnoreLocalGCRequests().
incremental_marking_
std::unique_ptr<IncrementalMarking> v8::internal::Heap::incremental_marking_ [private]
Definition at line 2337 of file heap.h.
Referenced by PerformGarbageCollection(), SetUp(), and TearDown().
initial_max_old_generation_size_
size_t v8::internal::Heap::initial_max_old_generation_size_ = 0 [private]
Definition at line 2158 of file heap.h.
Referenced by AutomaticallyRestoreInitialHeapLimit(), CollectGarbage(), ConfigureHeap(), and InvokeNearHeapLimitCallback().
initial_max_old_generation_size_threshold_
size_t v8::internal::Heap::initial_max_old_generation_size_threshold_ = 0 [private]
Definition at line 2159 of file heap.h.
Referenced by AutomaticallyRestoreInitialHeapLimit(), and CollectGarbage().
initial_old_generation_size_
size_t v8::internal::Heap::initial_old_generation_size_ = 0 [private]
Definition at line 2160 of file heap.h.
Referenced by ConfigureHeap(), NotifyContextDisposed(), and ResetOldGenerationAndGlobalAllocationLimit().
initial_semispace_size_
size_t v8::internal::Heap::initial_semispace_size_ = 0 [private]
Definition at line 2146 of file heap.h.
Referenced by ConfigureHeap(), and SetUpSpaces().
initial_size_overwritten_
bool v8::internal::Heap::initial_size_overwritten_ = false [private]
Definition at line 2173 of file heap.h.
Referenced by ConfigureHeap(), NotifyContextDisposed(), ResetOldGenerationAndGlobalAllocationLimit(), and ShrinkOldGenerationAllocationLimitIfNotConfigured().
inline_allocation_enabled_
bool v8::internal::Heap::inline_allocation_enabled_ = true [private]
Definition at line 2443 of file heap.h.
Referenced by DisableInlineAllocation(), and EnableInlineAllocation().
is_current_gc_for_heap_profiler_
bool v8::internal::Heap::is_current_gc_for_heap_profiler_ = false [private]
Definition at line 2425 of file heap.h.
Referenced by CollectGarbage(), and GarbageCollectionPrologue().
is_current_gc_forced_
bool v8::internal::Heap::is_current_gc_forced_ = false [private]
Definition at line 2424 of file heap.h.
Referenced by CollectGarbage(), and GarbageCollectionPrologue().
is_finalization_registry_cleanup_task_posted_
bool v8::internal::Heap::is_finalization_registry_cleanup_task_posted_ = false [private]
Definition at line 2454 of file heap.h.
Referenced by PostFinalizationRegistryCleanupTaskIfNeeded().
is_full_gc_during_loading_
bool v8::internal::Heap::is_full_gc_during_loading_ = false [private]
Definition at line 2476 of file heap.h.
Referenced by CollectGarbage(), and StartIncrementalMarking().
isolate_
Isolate* v8::internal::Heap::isolate_ = nullptr [private]
Definition at line 2137 of file heap.h.
Referenced by AddHeapObjectAllocationTracker(), CheckHandleCount(), CollectGarbage(), CreateDefaultMeasureMemoryDelegate(), CreateInitialMutableObjects(), DeoptMarkedAllocationSites(), GarbageCollectionEpilogue(), GarbageCollectionEpilogueInSafepoint(), InvokeIncrementalMarkingEpilogueCallbacks(), InvokeIncrementalMarkingPrologueCallbacks(), IterateRoots(), IterateStackRoots(), IterateWeakGlobalHandles(), MarkCompact(), MarkCompactEpilogue(), MarkCompactPrologue(), OnMoveEvent(), PerformGarbageCollection(), PrintFreeListsStats(), PrintShortHeapStatistics(), RecordStats(), RemoveHeapObjectAllocationTracker(), ResetAllAllocationSitesDependentCode(), v8::internal::IdleTaskOnContextDispose::RunInternal(), v8::internal::GCTracer::Scope::Scope(), SelectGarbageCollector(), SetUp(), SetUpSpaces(), TearDown(), TotalGlobalHandlesSize(), v8::internal::IdleTaskOnContextDispose::TryRunMinorGC(), and UsedGlobalHandlesSize().
kInitialEvalCacheSize
const int v8::internal::Heap::kInitialEvalCacheSize = 64 [static], [private]
Definition at line 1760 of file heap.h.
kLoadTimeNotLoading
constexpr double v8::internal::Heap::kLoadTimeNotLoading = -1.0 [static], [constexpr], [private]
Definition at line 2467 of file heap.h.
Referenced by NotifyLoadingEnded(), NotifyLoadingStarted(), and ShouldOptimizeForLoadTime().
kMaxLoadTimeMs
const int v8::internal::Heap::kMaxLoadTimeMs = 7000 [static], [private]
Definition at line 1977 of file heap.h.
Referenced by ShouldOptimizeForLoadTime().
kMaxMarkCompactsInIdleRound
const int v8::internal::Heap::kMaxMarkCompactsInIdleRound = 7 [static], [private]
Definition at line 1768 of file heap.h.
kMinObjectSizeInTaggedWords
const int v8::internal::Heap::kMinObjectSizeInTaggedWords = 2 [static]
Definition at line 326 of file heap.h.
Referenced by v8::internal::Scavenger::PromoteObject(), v8::internal::AllocationSite::set_memento_found_count(), v8::internal::WasmStruct::Size(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructNew(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::StructNewImpl().
kMmapRegionMask
const uintptr_t v8::internal::Heap::kMmapRegionMask = 0xFFFFFFFFu [static], [private]
Definition at line 2281 of file heap.h.
Referenced by SetUp().
kNewLargeObjectSpaceToSemiSpaceRatio
constexpr size_t v8::internal::Heap::kNewLargeObjectSpaceToSemiSpaceRatio = 1 [static], [constexpr]
Definition at line 320 of file heap.h.
Referenced by SemiSpaceSizeFromYoungGenerationSize(), and YoungGenerationSizeFromSemiSpaceSize().
kOldSurvivalRateLowThreshold
const int v8::internal::Heap::kOldSurvivalRateLowThreshold = 10 [static], [private]
Definition at line 1766 of file heap.h.
Referenced by EvaluateOldSpaceLocalPretenuring().
kPhysicalMemoryToOldGenerationRatio
constexpr size_t v8::internal::Heap::kPhysicalMemoryToOldGenerationRatio = 4 [static], [constexpr]
Definition at line 319 of file heap.h.
Referenced by HeapSizeFromPhysicalMemory().
kPointerMultiplier
const int v8::internal::Heap::kPointerMultiplier = kTaggedSize / 4 [static]
Definition at line 315 of file heap.h.
Referenced by DefaultMaxSemiSpaceSize(), DefaultMinSemiSpaceSize(), OldGenerationToSemiSpaceRatioLowMemory(), and v8::internal::PretenuringHandler::ProcessPretenuringFeedback().
kRememberedUnmappedPages
const int v8::internal::Heap::kRememberedUnmappedPages = 128 [static], [private]
Definition at line 1762 of file heap.h.
Referenced by RememberUnmappedPage().
kRetainMapEntrySize
constexpr int v8::internal::Heap::kRetainMapEntrySize = 2 [static], [constexpr], [private]
Definition at line 1880 of file heap.h.
Referenced by AddRetainedMaps(), and CompactRetainedMaps().
kStacktraceBufferSize
const int v8::internal::Heap::kStacktraceBufferSize = 512 [static]
Definition at line 323 of file heap.h.
kTraceRingBufferSize
const int v8::internal::Heap::kTraceRingBufferSize = 512 [static]
Definition at line 322 of file heap.h.
Referenced by AddToRingBuffer(), and GetFromRingBuffer().
kYoungSurvivalRateAllowedDeviation
const int v8::internal::Heap::kYoungSurvivalRateAllowedDeviation = 15 [static], [private]
Definition at line 1765 of file heap.h.
kYoungSurvivalRateHighThreshold
const int v8::internal::Heap::kYoungSurvivalRateHighThreshold = 90 [static], [private]
Definition at line 1764 of file heap.h.
last_gc_time_
double v8::internal::Heap::last_gc_time_ = 0.0 [private]
Definition at line 2327 of file heap.h.
Referenced by GarbageCollectionEpilogue().
live_object_stats_
std::unique_ptr<ObjectStats> v8::internal::Heap::live_object_stats_ [private]
Definition at line 2341 of file heap.h.
Referenced by CreateObjectStats(), ObjectCountAtLastGC(), ObjectSizeAtLastGC(), SetUpSpaces(), and TearDown().
lo_space_
OldLargeObjectSpace* v8::internal::Heap::lo_space_ = nullptr [private]
Definition at line 2211 of file heap.h.
Referenced by CommittedOldGenerationMemory(), Contains(), InSpace(), InSpaceSlow(), OldGenerationCapacity(), PrintShortHeapStatistics(), RecordStats(), and SetUpSpaces().
load_start_time_ms_
std::atomic<double> v8::internal::Heap::load_start_time_ms_ {kLoadTimeNotLoading} [private]
Definition at line 2470 of file heap.h.
Referenced by NotifyLoadingEnded(), NotifyLoadingStarted(), and ShouldOptimizeForLoadTime().
main_thread_local_heap_
LocalHeap* v8::internal::Heap::main_thread_local_heap_ = nullptr [private]
Definition at line 2256 of file heap.h.
Referenced by SetStackStart(), SetUp(), stack(), v8::internal::MarkCompactCollector::TearDown(), and v8::internal::MinorMarkSweepCollector::TearDown().
mark_compact_collector_
std::unique_ptr<MarkCompactCollector> v8::internal::Heap::mark_compact_collector_ [private]
Definition at line 2331 of file heap.h.
Referenced by SetUp(), and TearDown().
marking_state_
MarkingState v8::internal::Heap::marking_state_ [private]
Definition at line 2456 of file heap.h.
max_global_memory_size_
size_t v8::internal::Heap::max_global_memory_size_ = 0 [private]
Definition at line 2156 of file heap.h.
Referenced by AllocationLimitOvershotByLargeMargin(), EnsureMinimumRemainingAllocationLimit(), RecomputeLimits(), RecomputeLimitsAfterLoadingIfNeeded(), and SetOldGenerationAndGlobalMaximumSize().
max_marking_limit_reached_
std::atomic<double> v8::internal::Heap::max_marking_limit_reached_ = 0.0 [private]
Definition at line 2269 of file heap.h.
Referenced by IncrementalMarkingLimitReached(), and PrintMaxMarkingLimitReached().
max_old_generation_size_
std::atomic<size_t> v8::internal::Heap::max_old_generation_size_ {0} [private]
Definition at line 2152 of file heap.h.
Referenced by RecomputeLimits(), RecomputeLimitsAfterLoadingIfNeeded(), and SetOldGenerationAndGlobalMaximumSize().
max_regular_code_object_size_
int v8::internal::Heap::max_regular_code_object_size_ = 0 [private]
Definition at line 2441 of file heap.h.
Referenced by Heap(), and MaxRegularHeapObjectSize().
max_semi_space_size_
size_t v8::internal::Heap::max_semi_space_size_ = 0 [private]
Definition at line 2144 of file heap.h.
Referenced by ConfigureHeap(), MaxReserved(), and SetUpSpaces().
maximum_committed_
size_t v8::internal::Heap::maximum_committed_ = 0 [private]
Definition at line 2180 of file heap.h.
Referenced by UpdateMaximumCommitted().
mb_
std::unique_ptr<MemoryBalancer> v8::internal::Heap::mb_ [private]
Definition at line 2464 of file heap.h.
Referenced by RecomputeLimits(), v8::internal::GCTracer::SampleAllocation(), SetUpSpaces(), and v8::internal::GCTracer::UpdateMemoryBalancerGCSpeed().
memory_allocator_
std::unique_ptr<MemoryAllocator> v8::internal::Heap::memory_allocator_ [private]
Definition at line 2336 of file heap.h.
Referenced by GarbageCollectionEpilogueInSafepoint(), SetUp(), and TearDown().
memory_measurement_
std::unique_ptr<MemoryMeasurement> v8::internal::Heap::memory_measurement_ [private]
Definition at line 2339 of file heap.h.
Referenced by MeasureMemory(), SetUpSpaces(), and TearDown().
memory_pressure_level_
std::atomic<v8::MemoryPressureLevel> v8::internal::Heap::memory_pressure_level_ [private]
Definition at line 2198 of file heap.h.
Referenced by CheckMemoryPressure(), GarbageCollectionEpilogueInSafepoint(), and MemoryPressureNotification().
memory_reducer_
std::unique_ptr<MemoryReducer> v8::internal::Heap::memory_reducer_ [private]
Definition at line 2340 of file heap.h.
Referenced by ActivateMemoryReducerIfNeeded(), ActivateMemoryReducerIfNeededOnMainThread(), CollectGarbage(), NotifyContextDisposed(), SetUpSpaces(), and TearDown().
min_global_memory_size_
size_t v8::internal::Heap::min_global_memory_size_ = 0 [private]
Definition at line 2155 of file heap.h.
Referenced by ConfigureHeap(), and EnsureMinimumRemainingAllocationLimit().
min_old_generation_size_
size_t v8::internal::Heap::min_old_generation_size_ = 0 [private]
Definition at line 2149 of file heap.h.
Referenced by ConfigureHeap().
min_semi_space_size_
size_t v8::internal::Heap::min_semi_space_size_ = 0 [private]
Definition at line 2145 of file heap.h.
Referenced by ConfigureHeap(), and SetUpSpaces().
minor_gc_job_
std::unique_ptr<MinorGCJob> v8::internal::Heap::minor_gc_job_ [private]
Definition at line 2343 of file heap.h.
Referenced by SetUpSpaces(), and TearDown().
minor_mark_sweep_collector_
std::unique_ptr<MinorMarkSweepCollector> v8::internal::Heap::minor_mark_sweep_collector_ [private]
Definition at line 2332 of file heap.h.
Referenced by MinorMarkSweep(), SetUp(), and TearDown().
mmap_region_base_
uintptr_t v8::internal::Heap::mmap_region_base_ = 0 [private]
Definition at line 2282 of file heap.h.
Referenced by SetUp().
ms_count_
unsigned int v8::internal::Heap::ms_count_ = 0 [private]
Definition at line 2272 of file heap.h.
Referenced by ActivateMemoryReducerIfNeededOnMainThread(), CollectGarbage(), MarkCompact(), and NotifyOldGenerationExpansion().
native_contexts_list_
std::atomic<Address> v8::internal::Heap::native_contexts_list_ [private]
Definition at line 2299 of file heap.h.
near_heap_limit_callbacks_
std::vector<std::pair<v8::NearHeapLimitCallback, void*> > v8::internal::Heap::near_heap_limit_callbacks_ [private]
Definition at line 2201 of file heap.h.
Referenced by AddNearHeapLimitCallback(), InvokeNearHeapLimitCallback(), and RemoveNearHeapLimitCallback().
need_to_remove_stress_concurrent_allocation_observer_
bool v8::internal::Heap::need_to_remove_stress_concurrent_allocation_observer_ = false [private]
Definition at line 2382 of file heap.h.
Referenced by NotifyDeserializationComplete(), v8::internal::StressConcurrentAllocationObserver::Step(), and TearDown().
new_lo_space_
NewLargeObjectSpace* v8::internal::Heap::new_lo_space_ = nullptr [private]
Definition at line 2213 of file heap.h.
Referenced by CanPromoteYoungAndExpandOldGeneration(), CommittedMemory(), Contains(), InSpace(), InSpaceSlow(), PrintShortHeapStatistics(), ReduceNewSpaceSize(), and SetUpSpaces().
new_space_
NewSpace* v8::internal::Heap::new_space_ = nullptr [private]
Definition at line 2207 of file heap.h.
Referenced by CommittedMemory(), Contains(), ExpandNewSpaceSize(), InSpace(), InSpaceSlow(), NewSpaceAllocationCounter(), NewSpaceAllocationLimitAddress(), NewSpaceAllocationTopAddress(), NewSpaceLimit(), NewSpaceTop(), PrintShortHeapStatistics(), SetUpSpaces(), and ShouldResizeNewSpace().
new_space_allocation_counter_
size_t v8::internal::Heap::new_space_allocation_counter_ = 0 [private]
Definition at line 2387 of file heap.h.
Referenced by GarbageCollectionPrologueInSafepoint(), and NewSpaceAllocationCounter().
new_space_surviving_object_size_
size_t v8::internal::Heap::new_space_surviving_object_size_ = 0 [private]
Definition at line 2316 of file heap.h.
Referenced by GarbageCollectionPrologue(), and UpdateSurvivalStatistics().
new_space_surviving_rate_
double v8::internal::Heap::new_space_surviving_rate_ = 0.0 [private]
Definition at line 2318 of file heap.h.
Referenced by v8::internal::GCTracer::PrintNVP(), and UpdateSurvivalStatistics().
nodes_copied_in_new_space_
int v8::internal::Heap::nodes_copied_in_new_space_ = 0 [private]
Definition at line 2320 of file heap.h.
Referenced by GarbageCollectionPrologue(), and v8::internal::GCTracer::PrintNVP().
nodes_died_in_new_space_
int v8::internal::Heap::nodes_died_in_new_space_ = 0 [private]
Definition at line 2319 of file heap.h.
Referenced by GarbageCollectionPrologue(), and v8::internal::GCTracer::PrintNVP().
nodes_promoted_
int v8::internal::Heap::nodes_promoted_ = 0 [private]
Definition at line 2321 of file heap.h.
Referenced by GarbageCollectionPrologue(), and v8::internal::GCTracer::PrintNVP().
non_atomic_marking_state_
NonAtomicMarkingState v8::internal::Heap::non_atomic_marking_state_ [private]
Definition at line 2457 of file heap.h.
old_generation_allocation_counter_at_last_gc_
size_t v8::internal::Heap::old_generation_allocation_counter_at_last_gc_ = 0 [private]
Definition at line 2392 of file heap.h.
Referenced by MarkCompact().
old_generation_allocation_limit_
std::atomic<size_t> v8::internal::Heap::old_generation_allocation_limit_ {0} [private]
Definition at line 2292 of file heap.h.
Referenced by RecomputeLimits(), RecomputeLimitsAfterLoadingIfNeeded(), and SetOldGenerationAndGlobalAllocationLimit().
old_generation_capacity_after_bootstrap_
size_t v8::internal::Heap::old_generation_capacity_after_bootstrap_ = 0 [private]
Definition at line 2181 of file heap.h.
Referenced by NotifyBootstrapComplete(), and NotifyOldGenerationExpansion().
old_generation_size_at_last_gc_
size_t v8::internal::Heap::old_generation_size_at_last_gc_ {0} [private]
Definition at line 2395 of file heap.h.
Referenced by MarkCompact(), OldGenerationConsumedBytesAtLastGC(), and RecomputeLimitsAfterLoadingIfNeeded().
old_generation_wasted_at_last_gc_
size_t v8::internal::Heap::old_generation_wasted_at_last_gc_ {0} [private]
Definition at line 2398 of file heap.h.
Referenced by MarkCompact(), OldGenerationConsumedBytesAtLastGC(), and RecomputeLimitsAfterLoadingIfNeeded().
old_space_
OldSpace* v8::internal::Heap::old_space_ = nullptr [private]
Definition at line 2208 of file heap.h.
Referenced by CollectCodeStatistics(), Contains(), HasBeenSetUp(), InOldSpace(), InSpace(), InSpaceSlow(), PrintFreeListsStats(), PrintShortHeapStatistics(), RecordStats(), and SetUpSpaces().
owning_cpp_heap_
std::unique_ptr<CppHeap> v8::internal::Heap::owning_cpp_heap_ [private]
Definition at line 2365 of file heap.h.
Referenced by AttachCppHeap(), ConfigureHeap(), and TearDown().
pause_allocation_observers_depth_
int v8::internal::Heap::pause_allocation_observers_depth_ = 0 [private]
Definition at line 2445 of file heap.h.
Referenced by v8::internal::PauseAllocationObserversScope::PauseAllocationObserversScope(), and v8::internal::PauseAllocationObserversScope::~PauseAllocationObserversScope().
preconfigured_old_generation_size_
bool v8::internal::Heap::preconfigured_old_generation_size_ = false [private]
Definition at line 2178 of file heap.h.
Referenced by ConfigureHeap(), and NotifyContextDisposed().
pretenuring_handler_
PretenuringHandler v8::internal::Heap::pretenuring_handler_ [private]
Definition at line 2459 of file heap.h.
Referenced by PerformGarbageCollection(), and TearDown().
previous_new_space_surviving_object_size_
size_t v8::internal::Heap::previous_new_space_surviving_object_size_ = 0 [private]
Definition at line 2317 of file heap.h.
Referenced by GarbageCollectionPrologue(), and UpdateSurvivalStatistics().
promoted_objects_size_
size_t v8::internal::Heap::promoted_objects_size_ = 0 [private]
Definition at line 2313 of file heap.h.
Referenced by GarbageCollectionPrologue(), MarkCompact(), and UpdateSurvivalStatistics().
promotion_rate_
double v8::internal::Heap::promotion_rate_ = 0.0 [private]
Definition at line 2315 of file heap.h.
Referenced by v8::internal::GCTracer::PrintNVP(), and UpdateSurvivalStatistics().
promotion_ratio_
double v8::internal::Heap::promotion_ratio_ = 0.0 [private]
Definition at line 2314 of file heap.h.
Referenced by v8::internal::GCTracer::PrintNVP(), and UpdateSurvivalStatistics().
read_only_space_
ReadOnlySpace* v8::internal::Heap::read_only_space_ = nullptr [private]
Definition at line 2215 of file heap.h.
Referenced by CreateReadOnlyObjects(), InSpaceSlow(), PrintShortHeapStatistics(), RecordStats(), ReplaceReadOnlySpace(), SetUpFromReadOnlyHeap(), SetUpSpaces(), and TearDown().
remembered_unmapped_pages_
Address v8::internal::Heap::remembered_unmapped_pages_[kRememberedUnmappedPages] [private]
Definition at line 2286 of file heap.h.
Referenced by RememberUnmappedPage().
remembered_unmapped_pages_index_
int v8::internal::Heap::remembered_unmapped_pages_index_ = 0 [private]
Definition at line 2285 of file heap.h.
Referenced by RememberUnmappedPage().
resize_new_space_mode_
ResizeNewSpaceMode v8::internal::Heap::resize_new_space_mode_ = ResizeNewSpaceMode::kNone [private]
Definition at line 2462 of file heap.h.
Referenced by CollectGarbage(), ResizeNewSpace(), and StartResizeNewSpace().
ring_buffer_end_
size_t v8::internal::Heap::ring_buffer_end_ = 0 [private]
Definition at line 2409 of file heap.h.
Referenced by AddToRingBuffer(), and GetFromRingBuffer().
ring_buffer_full_
bool v8::internal::Heap::ring_buffer_full_ = false [private]
Definition at line 2408 of file heap.h.
Referenced by AddToRingBuffer(), and GetFromRingBuffer().
safepoint_
std::unique_ptr<IsolateSafepoint> v8::internal::Heap::safepoint_ [private]
Definition at line 2422 of file heap.h.
Referenced by IterateRoots().
scavenger_collector_
std::unique_ptr<ScavengerCollector> v8::internal::Heap::scavenger_collector_ [private]
Definition at line 2333 of file heap.h.
Referenced by EnsureQuarantinedPagesSweepingCompleted(), Scavenge(), SetUp(), and TearDown().
selective_stack_scan_start_address_
std::optional<const void*> v8::internal::Heap::selective_stack_scan_start_address_ [private]
Definition at line 2480 of file heap.h.
Referenced by v8::internal::ConservativePinningScope::ConservativePinningScope(), IterateConservativeStackRoots(), and v8::internal::ConservativePinningScope::~ConservativePinningScope().
shared_allocation_space_
PagedSpace* v8::internal::Heap::shared_allocation_space_ = nullptr [private]
Definition at line 2223 of file heap.h.
Referenced by SetUpSpaces(), and SharedHeapContains().
shared_lo_allocation_space_
OldLargeObjectSpace* v8::internal::Heap::shared_lo_allocation_space_ = nullptr [private]
Definition at line 2224 of file heap.h.
Referenced by SetUpSpaces(), and SharedHeapContains().
shared_lo_space_
SharedLargeObjectSpace* v8::internal::Heap::shared_lo_space_ = nullptr [private]
Definition at line 2214 of file heap.h.
Referenced by CommittedOldGenerationMemory(), Contains(), InSpace(), InSpaceSlow(), OldGenerationCapacity(), and SetUpSpaces().
shared_space_
SharedSpace* v8::internal::Heap::shared_space_ = nullptr [private]
Definition at line 2210 of file heap.h.
Referenced by Contains(), InSpace(), InSpaceSlow(), and SetUpSpaces().
shared_trusted_allocation_space_
SharedTrustedSpace* v8::internal::Heap::shared_trusted_allocation_space_ = nullptr [private]
Definition at line 2225 of file heap.h.
Referenced by SetUpSpaces(), and SharedHeapContains().
shared_trusted_lo_allocation_space_
SharedTrustedLargeObjectSpace* v8::internal::Heap::shared_trusted_lo_allocation_space_ = nullptr [private]
Definition at line 2226 of file heap.h.
Referenced by SetUpSpaces(), and SharedHeapContains().
shared_trusted_lo_space_
SharedTrustedLargeObjectSpace* v8::internal::Heap::shared_trusted_lo_space_ = nullptr [private]
Definition at line 2219 of file heap.h.
Referenced by Contains(), InSpace(), InSpaceSlow(), and SetUpSpaces().
shared_trusted_space_
SharedTrustedSpace* v8::internal::Heap::shared_trusted_space_ = nullptr [private]
Definition at line 2217 of file heap.h.
Referenced by Contains(), InSpace(), InSpaceSlow(), and SetUpSpaces().
space_
std::unique_ptr<Space> v8::internal::Heap::space_[LAST_SPACE+1] [private]
Definition at line 2229 of file heap.h.
Referenced by paged_space(), SetUpFromReadOnlyHeap(), SetUpSpaces(), space(), and TearDown().
stress_concurrent_allocation_observer_
std::unique_ptr<AllocationObserver> v8::internal::Heap::stress_concurrent_allocation_observer_ [private]
Definition at line 2344 of file heap.h.
Referenced by NotifyDeserializationComplete(), and TearDown().
stress_marking_percentage_
int v8::internal::Heap::stress_marking_percentage_ = 0 [private]
Definition at line 2262 of file heap.h.
Referenced by GarbageCollectionEpilogueInSafepoint(), IncrementalMarkingLimitReached(), and SetUpSpaces().
stress_scavenge_observer_
StressScavengeObserver* v8::internal::Heap::stress_scavenge_observer_ = nullptr [private]
Definition at line 2265 of file heap.h.
Referenced by HandleGCRequest(), PrintMaxNewSpaceSizeReached(), SetUpSpaces(), and TearDown().
strong_roots_head_
StrongRootsEntry* v8::internal::Heap::strong_roots_head_ = nullptr [private]
Definition at line 2377 of file heap.h.
Referenced by IterateRoots(), RegisterStrongRoots(), TearDown(), and UnregisterStrongRoots().
strong_roots_mutex_
base::Mutex v8::internal::Heap::strong_roots_mutex_ [private]
Definition at line 2378 of file heap.h.
Referenced by RegisterStrongRoots(), and UnregisterStrongRoots().
survived_since_last_expansion_
size_t v8::internal::Heap::survived_since_last_expansion_ = 0 [private]
Definition at line 2190 of file heap.h.
Referenced by ShouldResizeNewSpace().
sweeper_
std::unique_ptr<Sweeper> v8::internal::Heap::sweeper_ [private]
Definition at line 2330 of file heap.h.
Referenced by EnsureSweepingCompleted(), EnsureYoungSweepingCompleted(), SetUp(), and TearDown().
task_runner_
std::shared_ptr<v8::TaskRunner> v8::internal::Heap::task_runner_ [private]
Definition at line 2350 of file heap.h.
Referenced by ActivateMemoryReducerIfNeeded(), MemoryPressureNotification(), PostFinalizationRegistryCleanupTaskIfNeeded(), and SetUp().
total_gc_time_ms_
base::TimeDelta v8::internal::Heap::total_gc_time_ms_ [private]
Definition at line 2324 of file heap.h.
Referenced by PrintShortHeapStatistics(), and UpdateTotalGCTime().
trace_ring_buffer_
char v8::internal::Heap::trace_ring_buffer_[kTraceRingBufferSize] [private]
Definition at line 2403 of file heap.h.
Referenced by AddToRingBuffer(), and GetFromRingBuffer().
tracer_
std::unique_ptr<GCTracer> v8::internal::Heap::tracer_ [private]
Definition at line 2329 of file heap.h.
Referenced by SetUpSpaces(), ShouldResizeNewSpace(), and TearDown().
trusted_lo_space_
TrustedLargeObjectSpace* v8::internal::Heap::trusted_lo_space_ = nullptr [private]
Definition at line 2218 of file heap.h.
Referenced by CollectCodeStatistics(), CommittedOldGenerationMemory(), Contains(), InSpace(), InSpaceSlow(), OldGenerationCapacity(), PrintShortHeapStatistics(), and SetUpSpaces().
trusted_space_
TrustedSpace* v8::internal::Heap::trusted_space_ = nullptr [private]
Definition at line 2216 of file heap.h.
Referenced by CollectCodeStatistics(), Contains(), InSpace(), InSpaceSlow(), PrintShortHeapStatistics(), and SetUpSpaces().
update_allocation_limits_after_loading_
bool v8::internal::Heap::update_allocation_limits_after_loading_ = false [private]
Definition at line 2472 of file heap.h.
Referenced by CollectGarbage(), NotifyLoadingStarted(), RecomputeLimitsAfterLoadingIfNeeded(), and StartIncrementalMarking().
using_initial_limit_
std::atomic<bool> v8::internal::Heap::using_initial_limit_ = true [private]
Definition at line 2170 of file heap.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/heap.h
/mnt/V8SourceCode/src/heap/heap-inl.h
/mnt/V8SourceCode/src/heap/heap.cc
/mnt/V8SourceCode/src/heap/setup-heap-internal.cc