v8::internal::GlobalSafepoint Class Reference
#include <safepoint.h>
Public Member Functions
GlobalSafepoint (Isolate *isolate)
void AppendClient (Isolate *client)
void RemoveClient (Isolate *client)
template<typename Callback >
void IterateClientIsolates (Callback callback)
template<typename Callback >
void IterateSharedSpaceAndClientIsolates (Callback callback)
void AssertNoClientsOnTearDown ()
void AssertActive ()
V8_EXPORT_PRIVATE bool IsRequestedForTesting ()
Private Member Functions
void EnterGlobalSafepointScope (Isolate *initiator)
void LeaveGlobalSafepointScope (Isolate *initiator)
Private Attributes
Isolate *const shared_space_isolate_
base::RecursiveMutex clients_mutex_
Isolate * clients_head_ = nullptr
int active_safepoint_scopes_ = 0
Friends
class GlobalSafepointScope
class Isolate
Detailed Description
Definition at line 182 of file safepoint.h.
Constructor & Destructor Documentation
GlobalSafepoint()
v8::internal::GlobalSafepoint::GlobalSafepoint (Isolate * isolate) [explicit]
Definition at line 324 of file safepoint.cc.
    : shared_space_isolate_(isolate) {}
Member Function Documentation
AppendClient()
void v8::internal::GlobalSafepoint::AppendClient (Isolate * client)
Definition at line 327 of file safepoint.cc.
                                                  {
  clients_mutex_.AssertHeld();
  DCHECK_NULL(client->global_safepoint_prev_client_isolate_);
  DCHECK_NULL(client->global_safepoint_next_client_isolate_);
  DCHECK_NE(clients_head_, client);
  if (clients_head_) {
    clients_head_->global_safepoint_prev_client_isolate_ = client;
  }
  client->global_safepoint_prev_client_isolate_ = nullptr;
  client->global_safepoint_next_client_isolate_ = clients_head_;
  clients_head_ = client;
}
References v8::base::RecursiveMutex::AssertHeld(), clients_head_, clients_mutex_, DCHECK_NE, DCHECK_NULL, v8::internal::Isolate::global_safepoint_next_client_isolate_, and v8::internal::Isolate::global_safepoint_prev_client_isolate_.
Referenced by v8::internal::Isolate::Init().
AssertActive()
void v8::internal::GlobalSafepoint::AssertActive () [inline]
Definition at line 208 of file safepoint.h.
{ clients_mutex_.AssertHeld(); }
References v8::base::RecursiveMutex::AssertHeld(), and clients_mutex_.
Referenced by v8::internal::IsolateSafepoint::InitiateGlobalSafepointScope(), IterateClientIsolates(), RemoveClient(), and v8::internal::IsolateSafepoint::TryInitiateGlobalSafepointScope().
AssertNoClientsOnTearDown()
void v8::internal::GlobalSafepoint::AssertNoClientsOnTearDown ()
Definition at line 364 of file safepoint.cc.
                                                {
  DCHECK_NULL(clients_head_);
}
References clients_head_, and DCHECK_NULL.
Referenced by v8::internal::Isolate::Deinit().
EnterGlobalSafepointScope()
void v8::internal::GlobalSafepoint::EnterGlobalSafepointScope (Isolate * initiator) [private]
Definition at line 368 of file safepoint.cc.
                                                                  {
  // Safepoints need to be initiated on some main thread.
  DCHECK_NULL(LocalHeap::Current());
  if (!clients_mutex_.TryLock()) {
    IgnoreLocalGCRequests ignore_gc_requests(initiator->heap());
    initiator->main_thread_local_heap()->ExecuteWhileParked(
        [this]() { clients_mutex_.Lock(); });
  }
  if (++active_safepoint_scopes_ > 1) return;
  TimedHistogramScope timer(
      initiator->counters()->gc_time_to_global_safepoint());
  TRACE_GC(initiator->heap()->tracer(),
           GCTracer::Scope::TIME_TO_GLOBAL_SAFEPOINT);
  std::vector<PerClientSafepointData> clients;
  // Try to initiate safepoint for all clients. Fail immediately when the
  // local_heaps_mutex_ can't be locked without blocking.
  IterateSharedSpaceAndClientIsolates([&clients, initiator](Isolate* client) {
    clients.emplace_back(client);
    client->heap()->safepoint()->TryInitiateGlobalSafepointScope(
        initiator, &clients.back());
  });
  // Iterate all clients again to initiate the safepoint for all of them - even
  // if that means blocking.
  for (PerClientSafepointData& client : clients) {
    if (client.is_locked()) continue;
    client.safepoint()->InitiateGlobalSafepointScope(initiator, &client);
  }
#if DEBUG
  for (const PerClientSafepointData& client : clients) {
    DCHECK_EQ(client.isolate()->shared_space_isolate(), shared_space_isolate_);
  }
#endif // DEBUG
  // Now that safepoints were initiated for all clients, wait until all threads
  // of all clients reached a safepoint.
  for (const PerClientSafepointData& client : clients) {
    DCHECK(client.is_locked());
    client.safepoint()->WaitUntilRunningThreadsInSafepoint(&client);
  }
}
References active_safepoint_scopes_, clients_mutex_, v8::internal::Isolate::counters(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NULL, v8::internal::LocalHeap::ExecuteWhileParked(), v8::internal::Isolate::heap(), v8::internal::Factory::isolate(), IterateSharedSpaceAndClientIsolates(), v8::base::RecursiveMutex::Lock(), v8::internal::Isolate::main_thread_local_heap(), v8::internal::Isolate::shared_space_isolate(), shared_space_isolate_, TRACE_GC, v8::internal::Heap::tracer(), and v8::base::RecursiveMutex::TryLock().
Referenced by v8::internal::GlobalSafepointScope::GlobalSafepointScope().
IsRequestedForTesting()
bool v8::internal::GlobalSafepoint::IsRequestedForTesting ()
Definition at line 430 of file safepoint.cc.
                                            {
  if (!clients_mutex_.TryLock()) return true;
  clients_mutex_.Unlock();
  return false;
}
References clients_mutex_, v8::base::RecursiveMutex::TryLock(), and v8::base::RecursiveMutex::Unlock().
IterateClientIsolates()
template<typename Callback >
void v8::internal::GlobalSafepoint::IterateClientIsolates (Callback callback) [inline]
Definition at line 190 of file safepoint.h.
                                                {
    AssertActive();
    for (Isolate* current = clients_head_; current;
         current = current->global_safepoint_next_client_isolate_) {
      DCHECK(!current->is_shared_space_isolate());
      SetCurrentIsolateScope current_isolate_scope{current};
      callback(current);
    }
  }
References AssertActive(), clients_head_, v8::internal::DCHECK(), and v8::internal::Isolate::global_safepoint_next_client_isolate_.
Referenced by v8::internal::MarkCompactCollector::ClearNonLiveReferences(), v8::internal::anonymous_namespace{heap.cc}::ClearStubCaches(), v8::internal::Heap::FreeLinearAllocationAreas(), v8::internal::Heap::GarbageCollectionEpilogueInSafepoint(), v8::internal::Heap::IterateRootsIncludingClients(), IterateSharedSpaceAndClientIsolates(), v8::internal::Heap::MakeLinearAllocationAreasIterable(), v8::internal::MarkCompactCollector::MarkObjectsFromClientHeaps(), v8::internal::MarkCompactCollector::MarkRoots(), v8::internal::MarkCompactCollector::MarkRootsFromConservativeStack(), v8::internal::Heap::PauseConcurrentThreadsInClients(), v8::internal::Heap::PerformGarbageCollection(), v8::internal::Heap::PerformHeapVerification(), v8::internal::MarkCompactCollector::PinPreciseRootsIfNeeded(), and v8::internal::MarkCompactCollector::UpdatePointersInClientHeaps().
IterateSharedSpaceAndClientIsolates()
template<typename Callback >
void v8::internal::GlobalSafepoint::IterateSharedSpaceAndClientIsolates (Callback callback) [inline]
Definition at line 201 of file safepoint.h.
                                                              {
    callback(shared_space_isolate_);
    IterateClientIsolates(callback);
  }
References IterateClientIsolates(), and shared_space_isolate_.
Referenced by EnterGlobalSafepointScope(), LeaveGlobalSafepointScope(), v8::internal::IncrementalMarking::PauseBlackAllocation(), and v8::internal::IncrementalMarking::StartBlackAllocation().
LeaveGlobalSafepointScope()
void v8::internal::GlobalSafepoint::LeaveGlobalSafepointScope (Isolate * initiator) [private]
Definition at line 416 of file safepoint.cc.
                                                                  {
  clients_mutex_.AssertHeld();
  DCHECK_GT(active_safepoint_scopes_, 0);
  if (--active_safepoint_scopes_ == 0) {
    IterateSharedSpaceAndClientIsolates([initiator](Isolate* client) {
      Heap* client_heap = client->heap();
      client_heap->safepoint()->LeaveGlobalSafepointScope(initiator);
    });
  }
  clients_mutex_.Unlock();
}
References active_safepoint_scopes_, v8::base::RecursiveMutex::AssertHeld(), clients_mutex_, DCHECK_GT, v8::internal::Isolate::heap(), IterateSharedSpaceAndClientIsolates(), v8::internal::Heap::safepoint(), and v8::base::RecursiveMutex::Unlock().
Referenced by v8::internal::GlobalSafepointScope::~GlobalSafepointScope().
RemoveClient()
void v8::internal::GlobalSafepoint::RemoveClient (Isolate * client)
Definition at line 344 of file safepoint.cc.
                                                  {
  DCHECK_EQ(client->heap()->gc_state(), Heap::TEAR_DOWN);
  AssertActive();
  if (client->global_safepoint_next_client_isolate_) {
    client->global_safepoint_next_client_isolate_
        ->global_safepoint_prev_client_isolate_ =
        client->global_safepoint_prev_client_isolate_;
  }
  if (client->global_safepoint_prev_client_isolate_) {
    client->global_safepoint_prev_client_isolate_
        ->global_safepoint_next_client_isolate_ =
        client->global_safepoint_next_client_isolate_;
  } else {
    DCHECK_EQ(clients_head_, client);
    clients_head_ = client->global_safepoint_next_client_isolate_;
  }
}
References AssertActive(), clients_head_, DCHECK_EQ, v8::internal::Heap::gc_state(), v8::internal::Isolate::global_safepoint_next_client_isolate_, v8::internal::Isolate::global_safepoint_prev_client_isolate_, v8::internal::Isolate::heap(), and v8::internal::Heap::TEAR_DOWN.
Referenced by v8::internal::Isolate::Deinit().
Friends And Related Function Documentation
GlobalSafepointScope
friend class GlobalSafepointScope [friend]
Definition at line 223 of file safepoint.h.
Isolate
friend class Isolate [friend]
Definition at line 224 of file safepoint.h.
Member Data Documentation
active_safepoint_scopes_
int v8::internal::GlobalSafepoint::active_safepoint_scopes_ = 0 [private]
Definition at line 221 of file safepoint.h.
Referenced by EnterGlobalSafepointScope(), and LeaveGlobalSafepointScope().
clients_head_
Isolate* v8::internal::GlobalSafepoint::clients_head_ = nullptr [private]
Definition at line 220 of file safepoint.h.
Referenced by AppendClient(), AssertNoClientsOnTearDown(), IterateClientIsolates(), and RemoveClient().
clients_mutex_
base::RecursiveMutex v8::internal::GlobalSafepoint::clients_mutex_ [private]
Definition at line 219 of file safepoint.h.
Referenced by AppendClient(), AssertActive(), v8::internal::Isolate::Deinit(), EnterGlobalSafepointScope(), v8::internal::Isolate::Init(), IsRequestedForTesting(), and LeaveGlobalSafepointScope().
shared_space_isolate_
Isolate* const v8::internal::GlobalSafepoint::shared_space_isolate_ [private]
Definition at line 216 of file safepoint.h.
Referenced by EnterGlobalSafepointScope(), and IterateSharedSpaceAndClientIsolates().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/safepoint.h
/mnt/V8SourceCode/src/heap/safepoint.cc