v8::internal::compiler::JSInliningHeuristic Class Reference
#include <js-inlining-heuristic.h>
Classes
struct Candidate
struct CandidateCompare
Public Types
enum Mode { kJSOnly
, kWasmWrappersOnly
, kWasmFullInlining
 }
Public Member Functions
JSInliningHeuristic (Editor *editor, Zone *local_zone, OptimizedCompilationInfo *info, JSGraph *jsgraph, JSHeapBroker *broker, SourcePositionTable *source_positions, NodeOriginTable *node_origins, Mode mode, const wasm::WasmModule *wasm_module, JsWasmCallsSidetable *js_wasm_calls_sidetable)
const char * reducer_name () const override
Reduction Reduce (Node *node) final
void Finalize () final
int total_inlined_bytecode_size () const
Private Types
enum StateCloneMode { kCloneState
, kChangeInPlace
 }
using Candidates = ZoneSet< Candidate, CandidateCompare >
Private Member Functions
void PrintCandidates ()
Reduction InlineCandidate (Candidate const &candidate, bool small_function)
void CreateOrReuseDispatch (Node *node, Node *callee, Candidate const &candidate, Node **if_successes, Node **calls, Node **inputs, int input_count, int *num_calls)
bool TryReuseDispatch (Node *node, Node *callee, Node **if_successes, Node **calls, Node **inputs, int input_count, int *num_calls)
FrameState DuplicateFrameStateAndRename (FrameState frame_state, Node *from, Node *to, StateCloneMode mode)
Node * DuplicateStateValuesAndRename (Node *state_values, Node *from, Node *to, StateCloneMode mode)
Candidate CollectFunctions (Node *node, int functions_size)
CommonOperatorBuilder * common () const
TFGraph * graph () const
JSGraph * jsgraph () const
JSHeapBroker * broker () const
CompilationDependencies * dependencies () const
Isolate * isolate () const
SimplifiedOperatorBuilder * simplified () const
Mode mode () const
Private Attributes
JSInliner inliner_
Candidates candidates_
ZoneSet< NodeId > seen_
SourcePositionTable * source_positions_
JSGraph *const jsgraph_
JSHeapBroker *const broker_
OptimizedCompilationInfo * info_
int total_inlined_bytecode_size_ = 0
int total_ignored_bytecode_size_ = 0
const Mode mode_
const int max_inlined_bytecode_size_cumulative_
const int max_inlined_bytecode_size_absolute_
const int max_inlined_bytecode_size_small_total_
Static Private Attributes
static const int kMaxCallPolymorphism = 4
Additional Inherited Members
Detailed Description
Definition at line 14 of file js-inlining-heuristic.h.
Member Typedef Documentation
Candidates
using v8::internal::compiler::JSInliningHeuristic::Candidates = ZoneSet<Candidate, CandidateCompare> [private]
Definition at line 97 of file js-inlining-heuristic.h.
Member Enumeration Documentation
Mode
enum v8::internal::compiler::JSInliningHeuristic::Mode
Enumerator
kJSOnly
kWasmWrappersOnly
kWasmFullInlining
Definition at line 16 of file js-inlining-heuristic.h.
            {
    kJSOnly, // Inline JS calls only.
    kWasmWrappersOnly, // Inline wasm wrappers only.
    kWasmFullInlining, // Inline wasm wrappers and (if supported) whole wasm
                        // functions.
  };
StateCloneMode
enum v8::internal::compiler::JSInliningHeuristic::StateCloneMode [private]
Enumerator
kCloneState
kChangeInPlace
Definition at line 109 of file js-inlining-heuristic.h.
{ kCloneState, kChangeInPlace };
Constructor & Destructor Documentation
JSInliningHeuristic()
v8::internal::compiler::JSInliningHeuristic::JSInliningHeuristic (Editor * editor, Zone * local_zone, OptimizedCompilationInfo * info, JSGraph * jsgraph, JSHeapBroker * broker, SourcePositionTable * source_positions, NodeOriginTable * node_origins, Mode mode, const wasm::WasmModule * wasm_module, JsWasmCallsSidetable * js_wasm_calls_sidetable) [inline]
Definition at line 23 of file js-inlining-heuristic.h.
      : AdvancedReducer(editor),
        inliner_(editor, local_zone, info, jsgraph, broker, source_positions,
                 node_origins, wasm_module, js_wasm_calls_sidetable,
                 mode == kWasmFullInlining),
        candidates_(local_zone),
        seen_(local_zone),
        source_positions_(source_positions),
        jsgraph_(jsgraph),
        broker_(broker),
        info_(info),
        mode_(mode),
        max_inlined_bytecode_size_cumulative_(
            v8_flags.max_inlined_bytecode_size_cumulative),
        max_inlined_bytecode_size_absolute_(
            v8_flags.max_inlined_bytecode_size_absolute),
        max_inlined_bytecode_size_small_total_(
            v8_flags.max_inlined_bytecode_size_small_total) {
    DCHECK_EQ(mode == kWasmWrappersOnly || mode == kWasmFullInlining,
              wasm_module != nullptr && js_wasm_calls_sidetable != nullptr);
  }
References DCHECK_EQ, kWasmFullInlining, kWasmWrappersOnly, and mode().
Member Function Documentation
broker()
JSHeapBroker* v8::internal::compiler::JSInliningHeuristic::broker () const [inline], [private]
Definition at line 120 of file js-inlining-heuristic.h.
{ return broker_; }
References broker_.
Referenced by CollectFunctions(), CreateOrReuseDispatch(), dependencies(), PrintCandidates(), and Reduce().
CollectFunctions()
JSInliningHeuristic::Candidate v8::internal::compiler::JSInliningHeuristic::CollectFunctions (Node * node, int functions_size) [private]
Definition at line 133 of file js-inlining-heuristic.cc.
                                    {
  DCHECK_NE(0, functions_size);
  Node* callee = node->InputAt(0);
  Candidate out;
  out.node = node;
  HeapObjectMatcher m(callee);
  if (m.HasResolvedValue() && m.Ref(broker()).IsJSFunction()) {
    JSFunctionRef function = m.Ref(broker()).AsJSFunction();
    out.functions[0] = function;
    if (CanConsiderForInlining(broker(), function)) {
      out.bytecode[0] = function.shared(broker()).GetBytecodeArray(broker());
      out.num_functions = 1;
      out.has_heapnumber_params = HasHeapNumberInputOrOutput(node);
      return out;
    }
  }
  if (m.IsPhi()) {
    int const value_input_count = m.node()->op()->ValueInputCount();
    if (value_input_count > functions_size) {
      out.num_functions = 0;
      return out;
    }
    for (int n = 0; n < value_input_count; ++n) {
      HeapObjectMatcher m2(callee->InputAt(n));
      if (!m2.HasResolvedValue() || !m2.Ref(broker()).IsJSFunction()) {
        out.num_functions = 0;
        return out;
      }
      out.functions[n] = m2.Ref(broker()).AsJSFunction();
      JSFunctionRef function = out.functions[n].value();
      if (CanConsiderForInlining(broker(), function)) {
        out.bytecode[n] = function.shared(broker()).GetBytecodeArray(broker());
      }
    }
    out.num_functions = value_input_count;
    return out;
  }
  if (m.IsCheckClosure()) {
    DCHECK(!out.functions[0].has_value());
    FeedbackCellRef feedback_cell = MakeRef(broker(), FeedbackCellOf(m.op()));
    if (CanConsiderForInlining(broker(), feedback_cell)) {
      out.shared_info = feedback_cell.shared_function_info(broker()).value();
      out.bytecode[0] = out.shared_info->GetBytecodeArray(broker());
    }
    out.num_functions = 1;
    return out;
  }
  if (m.IsJSCreateClosure()) {
    DCHECK(!out.functions[0].has_value());
    JSCreateClosureNode n(callee);
    FeedbackCellRef feedback_cell = n.GetFeedbackCellRefChecked(broker());
    if (CanConsiderForInlining(broker(), feedback_cell)) {
      out.shared_info = feedback_cell.shared_function_info(broker()).value();
      out.bytecode[0] = out.shared_info->GetBytecodeArray(broker());
      CHECK(out.shared_info->equals(n.Parameters().shared_info()));
    }
    out.num_functions = 1;
    return out;
  }
  out.num_functions = 0;
  return out;
}
References broker(), v8::internal::compiler::JSInliningHeuristic::Candidate::bytecode, v8::internal::compiler::anonymous_namespace{js-inlining-heuristic.cc}::CanConsiderForInlining(), CHECK, v8::internal::DCHECK(), DCHECK_NE, v8::internal::compiler::FeedbackCellOf(), v8::internal::compiler::JSInliningHeuristic::Candidate::functions, v8::internal::compiler::JSCreateClosureNode::GetFeedbackCellRefChecked(), v8::internal::compiler::JSInliningHeuristic::Candidate::has_heapnumber_params, v8::internal::compiler::anonymous_namespace{js-inlining-heuristic.cc}::HasHeapNumberInputOrOutput(), v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::MakeRef(), v8::internal::compiler::JSInliningHeuristic::Candidate::node, v8::internal::compiler::NodeMatcher::node(), v8::internal::compiler::JSInliningHeuristic::Candidate::num_functions, v8::internal::compiler::NodeMatcher::op(), v8::internal::compiler::Node::op(), v8::internal::compiler::JSCreateClosureNode::Parameters(), v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Ref(), v8::internal::compiler::FeedbackCellRef::shared_function_info(), v8::internal::compiler::JSInliningHeuristic::Candidate::shared_info, v8::internal::compiler::CreateClosureParameters::shared_info(), and v8::internal::compiler::Operator::ValueInputCount().
Referenced by Reduce().
common()
CommonOperatorBuilder * v8::internal::compiler::JSInliningHeuristic::common () const [private]
Definition at line 941 of file js-inlining-heuristic.cc.
                                                         {
  return jsgraph()->common();
}
References v8::internal::compiler::MachineGraph::common(), and jsgraph().
Referenced by CreateOrReuseDispatch(), and InlineCandidate().
CreateOrReuseDispatch()
void v8::internal::compiler::JSInliningHeuristic::CreateOrReuseDispatch (Node * node, Node * callee, Candidate const & candidate, Node ** if_successes, Node ** calls, Node ** inputs, int input_count, int * num_calls) [private]
Definition at line 717 of file js-inlining-heuristic.cc.
                                                                  {
  SourcePositionTable::Scope position(
      source_positions_, source_positions_->GetSourcePosition(node));
  if (TryReuseDispatch(node, callee, if_successes, calls, inputs, input_count,
                       num_calls)) {
    return;
  }
  static_assert(JSCallOrConstructNode::kHaveIdenticalLayouts);
  Node* fallthrough_control = NodeProperties::GetControlInput(node);
  *num_calls = candidate.num_functions;
  // Create the appropriate control flow to dispatch to the cloned calls.
  for (int i = 0; i < *num_calls; ++i) {
    // TODO(2206): Make comparison be based on underlying SharedFunctionInfo
    // instead of the target JSFunction reference directly.
    Node* target =
        jsgraph()->ConstantNoHole(candidate.functions[i].value(), broker());
    if (i != (*num_calls - 1)) {
      Node* check =
          graph()->NewNode(simplified()->ReferenceEqual(), callee, target);
      Node* branch =
          graph()->NewNode(common()->Branch(), check, fallthrough_control);
      fallthrough_control = graph()->NewNode(common()->IfFalse(), branch);
      if_successes[i] = graph()->NewNode(common()->IfTrue(), branch);
    } else {
      if_successes[i] = fallthrough_control;
    }
    // Clone the calls for each branch.
    // The first input to the call is the actual target (which we specialize
    // to the known {target}); the last input is the control dependency.
    // We also specialize the new.target of JSConstruct {node}s if it refers
    // to the same node as the {node}'s target input, so that we can later
    // properly inline the JSCreate operations.
    if (node->opcode() == IrOpcode::kJSConstruct) {
      // TODO(jgruber, v8:10675): This branch seems unreachable.
      JSConstructNode n(node);
      if (inputs[n.TargetIndex()] == inputs[n.NewTargetIndex()]) {
        inputs[n.NewTargetIndex()] = target;
      }
    }
    inputs[JSCallOrConstructNode::TargetIndex()] = target;
    inputs[input_count - 1] = if_successes[i];
    calls[i] = if_successes[i] =
        graph()->NewNode(node->op(), input_count, inputs);
  }
}
References broker(), calls(), common(), v8::internal::compiler::JSGraph::ConstantNoHole(), v8::internal::compiler::JSInliningHeuristic::Candidate::functions, v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::SourcePositionTable::GetSourcePosition(), graph(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::detail::input_count(), jsgraph(), v8::internal::compiler::JSCallOrConstructNode::kHaveIdenticalLayouts, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::JSInliningHeuristic::Candidate::num_functions, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), simplified(), source_positions_, and TryReuseDispatch().
Referenced by InlineCandidate().
dependencies()
CompilationDependencies * v8::internal::compiler::JSInliningHeuristic::dependencies () const [private]
Definition at line 937 of file js-inlining-heuristic.cc.
                                                                 {
  return broker()->dependencies();
}
References broker(), and v8::internal::compiler::JSHeapBroker::dependencies().
DuplicateFrameStateAndRename()
FrameState v8::internal::compiler::JSInliningHeuristic::DuplicateFrameStateAndRename (FrameState frame_state, Node * from, Node * to, StateCloneMode mode) [private]
Definition at line 456 of file js-inlining-heuristic.cc.
                                                                       {
  // Only rename in states that are not shared with other users. This needs to
  // be in sync with the condition in {DuplicateFrameStateAndRename}.
  if (frame_state->UseCount() > 1) return frame_state;
  Node* copy =
      mode == kChangeInPlace ? static_cast<Node*>(frame_state) : nullptr;
  if (frame_state.stack() == from) {
    if (!copy) {
      copy = graph()->CloneNode(frame_state);
    }
    copy->ReplaceInput(FrameState::kFrameStateStackInput, to);
  }
  Node* locals = frame_state.locals();
  Node* new_locals = DuplicateStateValuesAndRename(locals, from, to, mode);
  if (new_locals != locals) {
    if (!copy) {
      copy = graph()->CloneNode(frame_state);
    }
    copy->ReplaceInput(FrameState::kFrameStateLocalsInput, new_locals);
  }
  return copy != nullptr ? FrameState{copy} : frame_state;
}
References v8::internal::compiler::TFGraph::CloneNode(), DuplicateStateValuesAndRename(), graph(), kChangeInPlace, v8::internal::compiler::FrameState::kFrameStateLocalsInput, v8::internal::compiler::FrameState::kFrameStateStackInput, v8::internal::compiler::FrameState::locals(), mode(), v8::internal::compiler::Node::ReplaceInput(), and v8::internal::compiler::FrameState::stack().
Referenced by TryReuseDispatch().
DuplicateStateValuesAndRename()
Node * v8::internal::compiler::JSInliningHeuristic::DuplicateStateValuesAndRename (Node * state_values, Node * from, Node * to, StateCloneMode mode) [private]
Definition at line 408 of file js-inlining-heuristic.cc.
                                                                              {
  // Only rename in states that are not shared with other users. This needs to
  // be in sync with the condition in {CollectStateValuesOwnedUses}.
  if (state_values->UseCount() > 1) return state_values;
  Node* copy = mode == kChangeInPlace ? state_values : nullptr;
  for (int i = 0; i < state_values->InputCount(); i++) {
    Node* input = state_values->InputAt(i);
    Node* processed;
    if (input->opcode() == IrOpcode::kStateValues) {
      processed = DuplicateStateValuesAndRename(input, from, to, mode);
    } else if (input == from) {
      processed = to;
    } else {
      processed = input;
    }
    if (processed != input) {
      if (!copy) {
        copy = graph()->CloneNode(state_values);
      }
      copy->ReplaceInput(i, processed);
    }
  }
  return copy ? copy : state_values;
}
References v8::internal::compiler::TFGraph::CloneNode(), graph(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::InputCount(), kChangeInPlace, mode(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::Node::ReplaceInput(), and v8::internal::compiler::Node::UseCount().
Referenced by DuplicateFrameStateAndRename().
Finalize()
void v8::internal::compiler::JSInliningHeuristic::Finalize () [final], [virtual]
Reimplemented from v8::internal::compiler::Reducer.
Definition at line 333 of file js-inlining-heuristic.cc.
                                   {
  if (candidates_.empty()) return; // Nothing to do without candidates.
  if (v8_flags.trace_turbo_inlining) PrintCandidates();
  // We inline at most one candidate in every iteration of the fixpoint.
  // This is to ensure that we don't consume the full inlining budget
  // on things that aren't called very often.
  // TODO(bmeurer): Use std::priority_queue instead of std::set here.
  while (!candidates_.empty()) {
    auto i = candidates_.begin();
    Candidate candidate = *i;
    candidates_.erase(i);
    // Ignore this candidate if it's no longer valid.
    if (!IrOpcode::IsInlineeOpcode(candidate.node->opcode())) continue;
    if (candidate.node->IsDead()) continue;
    // We re-check HasHeapNumberInputOrOutput because the inputs/outputs of this
    // function could have previously been function calls that now have been
    // inlined and thusly revealed HeapNumbers.
    if (HasHeapNumberInputOrOutput(candidate.node) &&
        IsSmallWithHeapNumberParam(candidate.own_size) &&
        total_ignored_bytecode_size_ < max_inlined_bytecode_size_small_total_) {
      Reduction const reduction = InlineCandidate(candidate, true);
      if (reduction.Changed()) return;
    }
    // Make sure we have some extra budget left, so that any small functions
    // exposed by this function would be given a chance to inline.
    double size_of_candidate =
        candidate.total_size * v8_flags.reserve_inline_budget_scale_factor;
    int total_size =
        total_inlined_bytecode_size_ + static_cast<int>(size_of_candidate);
    if (total_size > max_inlined_bytecode_size_cumulative_) {
      info_->set_could_not_inline_all_candidates();
      // Try if any smaller functions are available to inline.
      continue;
    }
    Reduction const reduction = InlineCandidate(candidate, false);
    if (reduction.Changed()) return;
  }
}
References candidates_, v8::internal::compiler::Reduction::Changed(), v8::internal::compiler::anonymous_namespace{js-inlining-heuristic.cc}::HasHeapNumberInputOrOutput(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, info_, InlineCandidate(), v8::internal::compiler::Node::IsDead(), v8::internal::compiler::IrOpcode::IsInlineeOpcode(), v8::internal::compiler::anonymous_namespace{js-inlining-heuristic.cc}::IsSmallWithHeapNumberParam(), max_inlined_bytecode_size_cumulative_, max_inlined_bytecode_size_small_total_, v8::internal::compiler::JSInliningHeuristic::Candidate::node, v8::internal::compiler::Node::opcode(), v8::internal::compiler::JSInliningHeuristic::Candidate::own_size, PrintCandidates(), total_ignored_bytecode_size_, total_inlined_bytecode_size_, v8::internal::compiler::JSInliningHeuristic::Candidate::total_size, and v8::internal::v8_flags.
graph()
TFGraph * v8::internal::compiler::JSInliningHeuristic::graph () const [private]
Definition at line 935 of file js-inlining-heuristic.cc.
{ return jsgraph()->graph(); }
References v8::internal::compiler::MachineGraph::graph(), and jsgraph().
Referenced by CreateOrReuseDispatch(), DuplicateFrameStateAndRename(), DuplicateStateValuesAndRename(), InlineCandidate(), and TryReuseDispatch().
InlineCandidate()
Reduction v8::internal::compiler::JSInliningHeuristic::InlineCandidate (Candidate const & candidate, bool small_function) [private]
Definition at line 769 of file js-inlining-heuristic.cc.
                                                                    {
  int num_calls = candidate.num_functions;
  Node* const node = candidate.node;
#if V8_ENABLE_WEBASSEMBLY
  DCHECK_NE(node->opcode(), IrOpcode::kJSWasmCall);
#endif // V8_ENABLE_WEBASSEMBLY
  if (num_calls == 1) {
    Reduction const reduction = inliner_.ReduceJSCall(node);
    if (reduction.Changed()) {
      if (small_function) {
        total_ignored_bytecode_size_ += candidate.bytecode[0].value().length();
      } else {
        total_inlined_bytecode_size_ += candidate.bytecode[0].value().length();
      }
    }
    return reduction;
  }
  // Expand the JSCall/JSConstruct node to a subgraph first if
  // we have multiple known target functions.
  DCHECK_LT(1, num_calls);
  Node* calls[kMaxCallPolymorphism + 1];
  Node* if_successes[kMaxCallPolymorphism];
  Node* callee = NodeProperties::GetValueInput(node, 0);
  // Setup the inputs for the cloned call nodes.
  int const input_count = node->InputCount();
  Node** inputs = graph()->zone()->AllocateArray<Node*>(input_count);
  for (int i = 0; i < input_count; ++i) {
    inputs[i] = node->InputAt(i);
  }
  // Create the appropriate control flow to dispatch to the cloned calls.
  CreateOrReuseDispatch(node, callee, candidate, if_successes, calls, inputs,
                        input_count, &num_calls);
  // Check if we have an exception projection for the call {node}.
  Node* if_exception = nullptr;
  if (NodeProperties::IsExceptionalCall(node, &if_exception)) {
    Node* if_exceptions[kMaxCallPolymorphism + 1];
    for (int i = 0; i < num_calls; ++i) {
      if_successes[i] = graph()->NewNode(common()->IfSuccess(), calls[i]);
      if_exceptions[i] =
          graph()->NewNode(common()->IfException(), calls[i], calls[i]);
    }
    // Morph the {if_exception} projection into a join.
    Node* exception_control =
        graph()->NewNode(common()->Merge(num_calls), num_calls, if_exceptions);
    if_exceptions[num_calls] = exception_control;
    Node* exception_effect = graph()->NewNode(common()->EffectPhi(num_calls),
                                              num_calls + 1, if_exceptions);
    Node* exception_value = graph()->NewNode(
        common()->Phi(MachineRepresentation::kTagged, num_calls), num_calls + 1,
        if_exceptions);
    ReplaceWithValue(if_exception, exception_value, exception_effect,
                     exception_control);
  }
  // Morph the original call site into a join of the dispatched call sites.
  Node* control =
      graph()->NewNode(common()->Merge(num_calls), num_calls, if_successes);
  calls[num_calls] = control;
  Node* effect =
      graph()->NewNode(common()->EffectPhi(num_calls), num_calls + 1, calls);
  Node* value =
      graph()->NewNode(common()->Phi(MachineRepresentation::kTagged, num_calls),
                       num_calls + 1, calls);
  ReplaceWithValue(node, value, effect, control);
  // Inline the individual, cloned call sites.
  for (int i = 0; i < num_calls && total_inlined_bytecode_size_ <
                                       max_inlined_bytecode_size_absolute_;
       ++i) {
    if (candidate.can_inline_function[i] &&
        (small_function || total_inlined_bytecode_size_ <
                               max_inlined_bytecode_size_cumulative_)) {
      Node* call = calls[i];
      Reduction const reduction = inliner_.ReduceJSCall(call);
      if (reduction.Changed()) {
        if (small_function) {
          total_ignored_bytecode_size_ +=
              candidate.bytecode[i].value().length();
        } else {
          total_inlined_bytecode_size_ += candidate.bytecode[i]->length();
        }
        // Killing the call node is not strictly necessary, but it is safer to
        // make sure we do not resurrect the node.
        call->Kill();
      }
    }
  }
  return Replace(value);
}
References v8::internal::Zone::AllocateArray(), v8::internal::compiler::JSInliningHeuristic::Candidate::bytecode, calls(), v8::internal::compiler::JSInliningHeuristic::Candidate::can_inline_function, v8::internal::compiler::Reduction::Changed(), common(), CreateOrReuseDispatch(), DCHECK_LT, DCHECK_NE, v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, inliner_, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::InputCount(), v8::internal::compiler::NodeProperties::IsExceptionalCall(), v8::internal::compiler::Node::Kill(), kMaxCallPolymorphism, v8::internal::kTagged, max_inlined_bytecode_size_absolute_, max_inlined_bytecode_size_cumulative_, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::JSInliningHeuristic::Candidate::node, v8::internal::compiler::JSInliningHeuristic::Candidate::num_functions, v8::internal::compiler::Node::opcode(), v8::internal::compiler::JSInliner::ReduceJSCall(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), total_ignored_bytecode_size_, total_inlined_bytecode_size_, v8::internal::value, and v8::internal::compiler::TFGraph::zone().
Referenced by Finalize(), and Reduce().
isolate()
Isolate* v8::internal::compiler::JSInliningHeuristic::isolate () const [inline], [private]
Definition at line 122 of file js-inlining-heuristic.h.
{ return jsgraph_->isolate(); }
References v8::internal::compiler::JSGraph::isolate(), and jsgraph_.
jsgraph()
JSGraph* v8::internal::compiler::JSInliningHeuristic::jsgraph () const [inline], [private]
Definition at line 118 of file js-inlining-heuristic.h.
{ return jsgraph_; }
References jsgraph_.
Referenced by common(), CreateOrReuseDispatch(), graph(), simplified(), and TryReuseDispatch().
mode()
Mode v8::internal::compiler::JSInliningHeuristic::mode () const [inline], [private]
Definition at line 124 of file js-inlining-heuristic.h.
{ return mode_; }
References mode_.
Referenced by DuplicateFrameStateAndRename(), DuplicateStateValuesAndRename(), JSInliningHeuristic(), and Reduce().
PrintCandidates()
void v8::internal::compiler::JSInliningHeuristic::PrintCandidates () [private]
Definition at line 902 of file js-inlining-heuristic.cc.
                                          {
  StdoutStream os;
  os << candidates_.size() << " candidate(s) for inlining:" << std::endl;
  for (const Candidate& candidate : candidates_) {
    os << "- candidate: " << candidate.node->op()->mnemonic() << " node #"
       << candidate.node->id() << " with frequency " << candidate.frequency
       << ", has_heapnum_param:" << candidate.has_heapnumber_params << ""
       << ", " << candidate.num_functions << " target(s):" << std::endl;
    for (int i = 0; i < candidate.num_functions; ++i) {
      SharedFunctionInfoRef shared =
          candidate.functions[i].has_value()
              ? candidate.functions[i]->shared(broker())
              : candidate.shared_info.value();
      os << " - target: " << shared;
      if (candidate.bytecode[i].has_value()) {
        os << ", bytecode size: " << candidate.bytecode[i]->length();
        if (OptionalJSFunctionRef function = candidate.functions[i]) {
          if (OptionalCodeRef code = function->code(broker())) {
            unsigned inlined_bytecode_size = code->GetInlinedBytecodeSize();
            if (inlined_bytecode_size > 0) {
              os << ", existing opt code's inlined bytecode size: "
                 << inlined_bytecode_size;
            }
          }
        }
      } else {
        os << ", no bytecode";
      }
      os << std::endl;
    }
  }
}
References broker(), candidates_, code, and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by Finalize().
Reduce()
Reduction v8::internal::compiler::JSInliningHeuristic::Reduce (Node * node) [final], [virtual]
Implements v8::internal::compiler::Reducer.
Definition at line 201 of file js-inlining-heuristic.cc.
                                                {
#if V8_ENABLE_WEBASSEMBLY
  if (mode() == kWasmWrappersOnly || mode() == kWasmFullInlining) {
    if (node->opcode() == IrOpcode::kJSWasmCall) {
      return inliner_.ReduceJSWasmCall(node);
    }
    return NoChange();
  }
#endif // V8_ENABLE_WEBASSEMBLY
  DCHECK_EQ(mode(), kJSOnly);
  if (!IrOpcode::IsInlineeOpcode(node->opcode())) return NoChange();
  // Check if we already saw that {node} before, and if so, just skip it.
  if (seen_.find(node->id()) != seen_.end()) return NoChange();
  // Check if the {node} is an appropriate candidate for inlining.
  Candidate candidate = CollectFunctions(node, kMaxCallPolymorphism);
  if (candidate.num_functions == 0) {
    return NoChange();
  }
  bool can_inline_candidate = false, candidate_is_small = true;
  candidate.total_size = 0;
  FrameState frame_state{NodeProperties::GetFrameStateInput(node)};
  FrameStateInfo const& frame_info = frame_state.frame_state_info();
  Handle<SharedFunctionInfo> frame_shared_info;
  for (int i = 0; i < candidate.num_functions; ++i) {
    if (!candidate.bytecode[i].has_value()) {
      candidate.can_inline_function[i] = false;
      continue;
    }
    SharedFunctionInfoRef shared =
        candidate.functions[i].has_value()
            ? candidate.functions[i].value().shared(broker())
            : candidate.shared_info.value();
    candidate.can_inline_function[i] = candidate.bytecode[i].has_value();
    // Because of concurrent optimization, optimization of the inlining
    // candidate could have been disabled meanwhile.
    // JSInliner will check this again and not actually inline the function in
    // this case.
    CHECK_IMPLIES(
        candidate.can_inline_function[i],
        shared.IsInlineable(CodeKind::TURBOFAN_JS, broker()) ||
            shared.GetInlineability(CodeKind::TURBOFAN_JS, broker()) ==
                SharedFunctionInfo::kHasOptimizationDisabled);
    // Do not allow direct recursion i.e. f() -> f(). We still allow indirect
    // recursion like f() -> g() -> f(). The indirect recursion is helpful in
    // cases where f() is a small dispatch function that calls the appropriate
    // function. In the case of direct recursion, we only have some static
    // information for the first level of inlining and it may not be that useful
    // to just inline one level in recursive calls. In some cases like tail
    // recursion we may benefit from recursive inlining, if we have additional
    // analysis that converts them to iterative implementations. Though it is
    // not obvious if such an analysis is needed.
    if (frame_info.shared_info().ToHandle(&frame_shared_info) &&
        frame_shared_info.equals(shared.object())) {
      TRACE("Not considering call site #" << node->id() << ":"
                                          << node->op()->mnemonic()
                                          << ", because of recursive inlining");
      candidate.can_inline_function[i] = false;
    }
    if (candidate.can_inline_function[i]) {
      can_inline_candidate = true;
      BytecodeArrayRef bytecode = candidate.bytecode[i].value();
      candidate.total_size += bytecode.length();
      candidate.own_size += bytecode.length();
      unsigned inlined_bytecode_size = 0;
      if (OptionalJSFunctionRef function = candidate.functions[i]) {
        if (OptionalCodeRef code = function->code(broker())) {
          inlined_bytecode_size = code->GetInlinedBytecodeSize();
          candidate.total_size += inlined_bytecode_size;
        }
      }
      bool this_function_small = false;
      if (IsSmall(bytecode.length() + inlined_bytecode_size)) {
        this_function_small = true;
      } else if (candidate.has_heapnumber_params &&
                 IsSmallWithHeapNumberParam(bytecode.length())) {
        this_function_small = true;
      }
      candidate_is_small = candidate_is_small && this_function_small;
    }
  }
  if (!can_inline_candidate) return NoChange();
  // Gather feedback on how often this call site has been hit before.
  if (node->opcode() == IrOpcode::kJSCall) {
    CallParameters const p = CallParametersOf(node->op());
    candidate.frequency = p.frequency();
  } else {
    ConstructParameters const p = ConstructParametersOf(node->op());
    candidate.frequency = p.frequency();
  }
  // Don't consider a {candidate} whose frequency is below the
  // threshold, i.e. a call site that is only hit once every N
  // invocations of the caller.
  if (candidate.frequency.IsKnown() &&
      candidate.frequency.value() < v8_flags.min_inlining_frequency) {
    return NoChange();
  }
  // Found a candidate. Insert it into the set of seen nodes s.t. we don't
  // revisit in the future. Note this insertion happens here and not earlier in
  // order to make inlining decisions order-independent. A node may not be a
  // candidate when first seen, but later reductions may turn it into a valid
  // candidate. In that case, the node should be revisited by
  // JSInliningHeuristic.
  seen_.insert(node->id());
  // Forcibly inline small functions here. In the case of polymorphic inlining
  // candidate_is_small is set only when all functions are small.
  if (candidate_is_small &&
      total_ignored_bytecode_size_ < max_inlined_bytecode_size_small_total_) {
    TRACE("Inlining small function(s) at call site #"
          << node->id() << ":" << node->op()->mnemonic());
    return InlineCandidate(candidate, true);
  }
  if (total_inlined_bytecode_size_ >= max_inlined_bytecode_size_absolute_) {
    return NoChange();
  }
  // In the general case we remember the candidate for later.
  candidates_.insert(candidate);
  return NoChange();
}
References broker(), v8::internal::compiler::JSInliningHeuristic::Candidate::bytecode, v8::internal::compiler::CallParametersOf(), v8::internal::compiler::JSInliningHeuristic::Candidate::can_inline_function, candidates_, CHECK_IMPLIES, code, CollectFunctions(), v8::internal::compiler::ConstructParametersOf(), DCHECK_EQ, v8::internal::Handle< T >::equals(), v8::internal::compiler::JSInliningHeuristic::Candidate::frequency, v8::internal::compiler::ConstructParameters::frequency(), v8::internal::compiler::CallParameters::frequency(), v8::internal::compiler::JSInliningHeuristic::Candidate::functions, v8::internal::compiler::NodeProperties::GetFrameStateInput(), v8::internal::compiler::SharedFunctionInfoRef::GetInlineability(), v8::internal::compiler::JSInliningHeuristic::Candidate::has_heapnumber_params, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Node::id(), InlineCandidate(), inliner_, v8::internal::compiler::SharedFunctionInfoRef::IsInlineable(), v8::internal::compiler::IrOpcode::IsInlineeOpcode(), v8::internal::compiler::CallFrequency::IsKnown(), v8::internal::compiler::anonymous_namespace{js-inlining-heuristic.cc}::IsSmall(), v8::internal::compiler::anonymous_namespace{js-inlining-heuristic.cc}::IsSmallWithHeapNumberParam(), v8::internal::SharedFunctionInfo::kHasOptimizationDisabled, kJSOnly, kMaxCallPolymorphism, kWasmFullInlining, kWasmWrappersOnly, v8::internal::compiler::BytecodeArrayRef::length(), max_inlined_bytecode_size_absolute_, max_inlined_bytecode_size_small_total_, v8::internal::compiler::Operator::mnemonic(), mode(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::JSInliningHeuristic::Candidate::num_functions, v8::internal::compiler::SharedFunctionInfoRef::object(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::JSInliningHeuristic::Candidate::own_size, seen_, v8::internal::compiler::FrameStateInfo::shared_info(), v8::internal::compiler::JSInliningHeuristic::Candidate::shared_info, total_ignored_bytecode_size_, total_inlined_bytecode_size_, v8::internal::compiler::JSInliningHeuristic::Candidate::total_size, v8::internal::TRACE(), v8::internal::v8_flags, and v8::internal::compiler::CallFrequency::value().
reducer_name()
const char* v8::internal::compiler::JSInliningHeuristic::reducer_name () const [inline], [override], [virtual]
Implements v8::internal::compiler::Reducer.
Definition at line 53 of file js-inlining-heuristic.h.
{ return "JSInliningHeuristic"; }
simplified()
SimplifiedOperatorBuilder * v8::internal::compiler::JSInliningHeuristic::simplified () const [private]
Definition at line 945 of file js-inlining-heuristic.cc.
                                                                 {
  return jsgraph()->simplified();
}
References jsgraph(), and v8::internal::compiler::JSGraph::simplified().
Referenced by CreateOrReuseDispatch().
total_inlined_bytecode_size()
int v8::internal::compiler::JSInliningHeuristic::total_inlined_bytecode_size () const [inline]
Definition at line 61 of file js-inlining-heuristic.h.
                                          {
    return total_inlined_bytecode_size_ + total_ignored_bytecode_size_;
  }
References total_ignored_bytecode_size_, and total_inlined_bytecode_size_.
Referenced by v8::internal::compiler::InliningPhase::Run().
TryReuseDispatch()
bool v8::internal::compiler::JSInliningHeuristic::TryReuseDispatch (Node * node, Node * callee, Node ** if_successes, Node ** calls, Node ** inputs, int input_count, int * num_calls) [private]
Definition at line 480 of file js-inlining-heuristic.cc.
                                                           {
  // We will try to reuse the control flow branch created for computing
  // the {callee} target of the call. We only reuse the branch if there
  // is no side-effect between the call and the branch, and if the callee is
  // only used as the target (and possibly also in the related frame states).
  // We are trying to match the following pattern:
  //
  // C1 C2
  // . .
  // | |
  // Merge(merge) <-----------------+
  // ^ ^ |
  // V1 V2 | | E1 E2 |
  // . . | +----+ . . |
  // | | | | | | |
  // Phi(callee) EffectPhi(effect_phi) |
  // ^ ^ |
  // | | |
  // +----+ | |
  // | | | |
  // | StateValues | |
  // | ^ | |
  // +----+ | | |
  // | | | | |
  // | FrameState | |
  // | ^ | |
  // | | | +---+
  // | | | | |
  // +----+ Checkpoint(checkpoint) |
  // | | ^ |
  // | StateValues | +-------------+
  // | | | |
  // +-----+ | | |
  // | | | | |
  // | FrameState | |
  // | ^ | |
  // +-----------+ | | |
  // Call(node)
  // |
  // |
  // .
  //
  // The {callee} here is a phi that merges the possible call targets, {node}
  // is the actual call that we will try to duplicate and connect to the
  // control that comes into {merge}. There can be a {checkpoint} between
  // the call and the calle phi.
  //
  // The idea is to get rid of the merge, effect phi and phi, then duplicate
  // the call (with all the frame states and such), and connect the duplicated
  // calls and states directly to the inputs of the ex-phi, ex-effect-phi and
  // ex-merge. The tricky part is to make sure that there is no interference
  // from the outside. In particular, there should not be any unaccounted uses
  // of the phi, effect-phi and merge because we will remove them from
  // the graph.
  //
  // V1 E1 C1 V2 E2 C2
  // . . . . . .
  // | | | | | |
  // +----+ | | +----+ |
  // | | | | | | |
  // | StateValues | | | StateValues |
  // | ^ | | | ^ |
  // +----+ | | | +----+ | |
  // | | | | | | | | |
  // | FrameState | | | FrameState |
  // | ^ | | | ^ |
  // | | | | | | |
  // | | | | | | |
  // +----+ Checkpoint | +----+ Checkpoint |
  // | | ^ | | | ^ |
  // | StateValues | | | StateValues | |
  // | | | | | | | |
  // +-----+ | | | +-----+ | | |
  // | | | | | | | | | |
  // | FrameState | | | FrameState | |
  // | ^ | | | ^ | |
  // +-------------+| | | +-------------+| | |
  // Call----+ Call----+
  // | |
  // +-------+ +------------+
  // | |
  // Merge
  // EffectPhi
  // Phi
  // |
  // ...
  // Bailout if the call is not polymorphic anymore (other reducers might
  // have replaced the callee phi with a constant).
  if (callee->opcode() != IrOpcode::kPhi) return false;
  // If there is a control node between the callee computation
  // and the call, bail out.
  Node* merge = NodeProperties::GetControlInput(callee);
  if (NodeProperties::GetControlInput(node) != merge) return false;
  // If there is a non-checkpoint effect node between the callee computation
  // and the call, bail out. We will drop any checkpoint between the call and
  // the callee phi because the callee computation should have its own
  // checkpoint that the call can fall back to.
  Node* checkpoint = nullptr;
  Node* effect = NodeProperties::GetEffectInput(node);
  if (effect->opcode() == IrOpcode::kCheckpoint) {
    checkpoint = effect;
    if (NodeProperties::GetControlInput(checkpoint) != merge) return false;
    effect = NodeProperties::GetEffectInput(effect);
  }
  if (effect->opcode() != IrOpcode::kEffectPhi) return false;
  if (NodeProperties::GetControlInput(effect) != merge) return false;
  Node* effect_phi = effect;
  // The effect phi, the callee, the call and the checkpoint must be the only
  // users of the merge.
  for (Node* merge_use : merge->uses()) {
    if (merge_use != effect_phi && merge_use != callee && merge_use != node &&
        merge_use != checkpoint) {
      return false;
    }
  }
  // The effect phi must be only used by the checkpoint or the call.
  for (Node* effect_phi_use : effect_phi->uses()) {
    if (effect_phi_use != node && effect_phi_use != checkpoint) return false;
  }
  // We must replace the callee phi with the appropriate constant in
  // the entire subgraph reachable by inputs from the call (terminating
  // at phis and merges). Since we do not want to walk (and later duplicate)
  // the subgraph here, we limit the possible uses to this set:
  //
  // 1. In the call (as a target).
  // 2. The checkpoint between the call and the callee computation merge.
  // 3. The lazy deoptimization frame state.
  //
  // This corresponds to the most common pattern, where the function is
  // called with only local variables or constants as arguments.
  //
  // To check the uses, we first collect all the occurrences of callee in 1, 2
  // and 3, and then we check that all uses of callee are in the collected
  // occurrences. If there is an unaccounted use, we do not try to rewire
  // the control flow.
  //
  // Note: With CFG, this would be much easier and more robust - we would just
  // duplicate all the nodes between the merge and the call, replacing all
  // occurrences of the {callee} phi with the appropriate constant.
  // First compute the set of uses that are only reachable from 2 and 3.
  const size_t kMaxUses = 8;
  NodeAndIndex replaceable_uses[kMaxUses];
  size_t replaceable_uses_count = 0;
  // Collect the uses to check case 2.
  Node* checkpoint_state = nullptr;
  if (checkpoint) {
    checkpoint_state = checkpoint->InputAt(0);
    if (!CollectFrameStateUniqueUses(callee, FrameState{checkpoint_state},
                                     replaceable_uses, &replaceable_uses_count,
                                     kMaxUses)) {
      return false;
    }
  }
  // Collect the uses to check case 3.
  FrameState frame_state{NodeProperties::GetFrameStateInput(node)};
  if (!CollectFrameStateUniqueUses(callee, frame_state, replaceable_uses,
                                   &replaceable_uses_count, kMaxUses)) {
    return false;
  }
  // Bail out if there is a use of {callee} that is not reachable from 1, 2
  // and 3.
  for (Edge edge : callee->use_edges()) {
    // Case 1 (use by the call as a target).
    if (edge.from() == node && edge.index() == 0) continue;
    // Case 2 and 3 - used in checkpoint and/or lazy deopt frame states.
    bool found = false;
    for (size_t i = 0; i < replaceable_uses_count; i++) {
      if (replaceable_uses[i].node == edge.from() &&
          replaceable_uses[i].index == edge.index()) {
        found = true;
        break;
      }
    }
    if (!found) return false;
  }
  *num_calls = callee->op()->ValueInputCount();
  // Clone the call and the framestate, including the uniquely reachable
  // state values, making sure that we replace the phi with the constant.
  for (int i = 0; i < *num_calls; ++i) {
    // Clone the calls for each branch.
    // We need to specialize the calls to the correct target, effect, and
    // control. We also need to duplicate the checkpoint and the lazy
    // frame state, and change all the uses of the callee to the constant
    // callee.
    Node* target = callee->InputAt(i);
    Node* effect_phi_effect = effect_phi->InputAt(i);
    Node* control = merge->InputAt(i);
    if (checkpoint) {
      // Duplicate the checkpoint.
      FrameState new_checkpoint_state = DuplicateFrameStateAndRename(
          FrameState{checkpoint_state}, callee, target,
          (i == *num_calls - 1) ? kChangeInPlace : kCloneState);
      effect_phi_effect = graph()->NewNode(
          checkpoint->op(), new_checkpoint_state, effect_phi_effect, control);
    }
    // Duplicate the call.
    FrameState new_lazy_frame_state = DuplicateFrameStateAndRename(
        frame_state, callee, target,
        (i == *num_calls - 1) ? kChangeInPlace : kCloneState);
    inputs[0] = target;
    inputs[input_count - 3] = new_lazy_frame_state;
    inputs[input_count - 2] = effect_phi_effect;
    inputs[input_count - 1] = control;
    calls[i] = if_successes[i] =
        graph()->NewNode(node->op(), input_count, inputs);
  }
  // Mark the control inputs dead, so that we can kill the merge.
  node->ReplaceInput(input_count - 1, jsgraph()->Dead());
  callee->ReplaceInput(*num_calls, jsgraph()->Dead());
  effect_phi->ReplaceInput(*num_calls, jsgraph()->Dead());
  if (checkpoint) {
    checkpoint->ReplaceInput(2, jsgraph()->Dead());
  }
  merge->Kill();
  return true;
}
References calls(), v8::internal::compiler::anonymous_namespace{js-inlining-heuristic.cc}::CollectFrameStateUniqueUses(), DuplicateFrameStateAndRename(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetFrameStateInput(), graph(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::Node::InputAt(), jsgraph(), kChangeInPlace, kCloneState, v8::internal::compiler::Node::Kill(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::compiler::Node::use_edges(), v8::internal::compiler::Node::uses(), and v8::internal::compiler::Operator::ValueInputCount().
Referenced by CreateOrReuseDispatch().
Member Data Documentation
broker_
JSHeapBroker* const v8::internal::compiler::JSInliningHeuristic::broker_ [private]
Definition at line 131 of file js-inlining-heuristic.h.
Referenced by broker().
candidates_
Candidates v8::internal::compiler::JSInliningHeuristic::candidates_ [private]
Definition at line 127 of file js-inlining-heuristic.h.
Referenced by Finalize(), PrintCandidates(), and Reduce().
info_
OptimizedCompilationInfo* v8::internal::compiler::JSInliningHeuristic::info_ [private]
Definition at line 132 of file js-inlining-heuristic.h.
Referenced by Finalize().
inliner_
JSInliner v8::internal::compiler::JSInliningHeuristic::inliner_ [private]
Definition at line 126 of file js-inlining-heuristic.h.
Referenced by InlineCandidate(), and Reduce().
jsgraph_
JSGraph* const v8::internal::compiler::JSInliningHeuristic::jsgraph_ [private]
Definition at line 130 of file js-inlining-heuristic.h.
Referenced by isolate(), and jsgraph().
kMaxCallPolymorphism
const int v8::internal::compiler::JSInliningHeuristic::kMaxCallPolymorphism = 4 [static], [private]
Definition at line 68 of file js-inlining-heuristic.h.
Referenced by InlineCandidate(), and Reduce().
max_inlined_bytecode_size_absolute_
const int v8::internal::compiler::JSInliningHeuristic::max_inlined_bytecode_size_absolute_ [private]
Definition at line 137 of file js-inlining-heuristic.h.
Referenced by InlineCandidate(), and Reduce().
max_inlined_bytecode_size_cumulative_
const int v8::internal::compiler::JSInliningHeuristic::max_inlined_bytecode_size_cumulative_ [private]
Definition at line 136 of file js-inlining-heuristic.h.
Referenced by Finalize(), and InlineCandidate().
max_inlined_bytecode_size_small_total_
const int v8::internal::compiler::JSInliningHeuristic::max_inlined_bytecode_size_small_total_ [private]
Definition at line 138 of file js-inlining-heuristic.h.
Referenced by Finalize(), and Reduce().
mode_
const Mode v8::internal::compiler::JSInliningHeuristic::mode_ [private]
Definition at line 135 of file js-inlining-heuristic.h.
Referenced by mode().
seen_
ZoneSet<NodeId> v8::internal::compiler::JSInliningHeuristic::seen_ [private]
Definition at line 128 of file js-inlining-heuristic.h.
Referenced by Reduce().
source_positions_
SourcePositionTable* v8::internal::compiler::JSInliningHeuristic::source_positions_ [private]
Definition at line 129 of file js-inlining-heuristic.h.
Referenced by CreateOrReuseDispatch().
total_ignored_bytecode_size_
int v8::internal::compiler::JSInliningHeuristic::total_ignored_bytecode_size_ = 0 [private]
Definition at line 134 of file js-inlining-heuristic.h.
Referenced by Finalize(), InlineCandidate(), Reduce(), and total_inlined_bytecode_size().
total_inlined_bytecode_size_
int v8::internal::compiler::JSInliningHeuristic::total_inlined_bytecode_size_ = 0 [private]
Definition at line 133 of file js-inlining-heuristic.h.
Referenced by Finalize(), InlineCandidate(), Reduce(), and total_inlined_bytecode_size().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/js-inlining-heuristic.h
/mnt/V8SourceCode/src/compiler/js-inlining-heuristic.cc