v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::IteratingArrayBuiltinHelper Class Reference
Public Member Functions
IteratingArrayBuiltinHelper (Node *node, JSHeapBroker *broker, JSGraph *jsgraph, CompilationDependencies *dependencies)
bool can_reduce () const
bool has_stability_dependency () const
Effect effect () const
Control control () const
MapInference * inference ()
ElementsKind elements_kind () const
Private Attributes
bool can_reduce_ = false
bool has_stability_dependency_ = false
Node * receiver_
Effect effect_
Control control_
MapInference inference_
ElementsKind elements_kind_
Detailed Description
Definition at line 3687 of file js-call-reducer.cc.
Constructor & Destructor Documentation
IteratingArrayBuiltinHelper()
v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::IteratingArrayBuiltinHelper::IteratingArrayBuiltinHelper (Node * node, JSHeapBroker * broker, JSGraph * jsgraph, CompilationDependencies * dependencies) [inline]
Definition at line 3689 of file js-call-reducer.cc.
      : receiver_(NodeProperties::GetValueInput(node, 1)),
        effect_(NodeProperties::GetEffectInput(node)),
        control_(NodeProperties::GetControlInput(node)),
        inference_(broker, receiver_, effect_) {
    if (!v8_flags.turbo_inline_array_builtins) return;
    DCHECK_EQ(IrOpcode::kJSCall, node->opcode());
    const CallParameters& p = CallParametersOf(node->op());
    if (p.speculation_mode() != SpeculationMode::kAllowSpeculation) {
      return;
    }
    // Try to determine the {receiver} map.
    if (!inference_.HaveMaps()) return;
    ZoneRefSet<Map> const& receiver_maps = inference_.GetMaps();
    if (!CanInlineArrayIteratingBuiltin(broker, receiver_maps,
                                        &elements_kind_)) {
      return;
    }
    // TODO(jgruber): May only be needed for holey elements kinds.
    if (!dependencies->DependOnNoElementsProtector()) return;
    has_stability_dependency_ = inference_.RelyOnMapsPreferStability(
        dependencies, jsgraph, &effect_, control_, p.feedback());
    can_reduce_ = true;
  }
References broker(), v8::internal::compiler::CallParametersOf(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::CanInlineArrayIteratingBuiltin(), DCHECK_EQ, v8::internal::compiler::CompilationDependencies::DependOnNoElementsProtector(), v8::internal::compiler::CallParameters::feedback(), v8::internal::kAllowSpeculation, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::CallParameters::speculation_mode(), and v8::internal::v8_flags.
Member Function Documentation
can_reduce()
bool v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::IteratingArrayBuiltinHelper::can_reduce () const [inline]
Definition at line 3722 of file js-call-reducer.cc.
{ return can_reduce_; }
control()
Control v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::IteratingArrayBuiltinHelper::control () const [inline]
Definition at line 3725 of file js-call-reducer.cc.
{ return control_; }
effect()
Effect v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::IteratingArrayBuiltinHelper::effect () const [inline]
Definition at line 3724 of file js-call-reducer.cc.
{ return effect_; }
elements_kind()
ElementsKind v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::IteratingArrayBuiltinHelper::elements_kind () const [inline]
Definition at line 3727 of file js-call-reducer.cc.
{ return elements_kind_; }
has_stability_dependency()
bool v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::IteratingArrayBuiltinHelper::has_stability_dependency () const [inline]
Definition at line 3723 of file js-call-reducer.cc.
{ return has_stability_dependency_; }
inference()
MapInference* v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::IteratingArrayBuiltinHelper::inference () [inline]
Definition at line 3726 of file js-call-reducer.cc.
{ return &inference_; }
Member Data Documentation
can_reduce_
bool v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::IteratingArrayBuiltinHelper::can_reduce_ = false [private]
Definition at line 3730 of file js-call-reducer.cc.
control_
Control v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::IteratingArrayBuiltinHelper::control_ [private]
Definition at line 3734 of file js-call-reducer.cc.
effect_
Effect v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::IteratingArrayBuiltinHelper::effect_ [private]
Definition at line 3733 of file js-call-reducer.cc.
elements_kind_
ElementsKind v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::IteratingArrayBuiltinHelper::elements_kind_ [private]
Definition at line 3736 of file js-call-reducer.cc.
has_stability_dependency_
bool v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::IteratingArrayBuiltinHelper::has_stability_dependency_ = false [private]
Definition at line 3731 of file js-call-reducer.cc.
inference_
MapInference v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::IteratingArrayBuiltinHelper::inference_ [private]
Definition at line 3735 of file js-call-reducer.cc.
receiver_
Node* v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::IteratingArrayBuiltinHelper::receiver_ [private]
Definition at line 3732 of file js-call-reducer.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-call-reducer.cc