v8::internal::metrics::TimedScope< T, precision > Class Template Reference
#include <metrics.h>
Public Member Functions
TimedScope (T *event)
~TimedScope ()
void Start ()
void Stop ()
Private Attributes
T * event_
base::TimeTicks start_time_
Detailed Description
template<class T, int64_t(base::TimeDelta::*)() const precision = &base::TimeDelta::InMicroseconds>
class v8::internal::metrics::TimedScope< T, precision >
Definition at line 88 of file metrics.h.
Constructor & Destructor Documentation
TimedScope()
template<class T , int64_t(base::TimeDelta::*)() const precision = &base::TimeDelta::InMicroseconds>
v8::internal::metrics::TimedScope< T, precision >::TimedScope (T * event) [inline], [explicit]
Definition at line 90 of file metrics.h.
: event_(event) { Start(); }
 TimedScope()
template<class T , int64_t(base::TimeDelta::*)() const precision = &base::TimeDelta::InMicroseconds>
v8::internal::metrics::TimedScope< T, precision >::~TimedScope () [inline]
Definition at line 91 of file metrics.h.
{ Stop(); }
Member Function Documentation
Start()
template<class T , int64_t(base::TimeDelta::*)() const precision = &base::TimeDelta::InMicroseconds>
void v8::internal::metrics::TimedScope< T, precision >::Start () [inline]
Definition at line 93 of file metrics.h.
{ start_time_ = base::TimeTicks::Now(); }
References v8::base::TimeTicks::Now().
Stop()
template<class T , int64_t(base::TimeDelta::*)() const precision = &base::TimeDelta::InMicroseconds>
void v8::internal::metrics::TimedScope< T, precision >::Stop () [inline]
Definition at line 95 of file metrics.h.
              {
    if (start_time_.IsMin()) return;
    base::TimeDelta duration = base::TimeTicks::Now() - start_time_;
    event_->wall_clock_duration_in_us = (duration.*precision)();
    start_time_ = base::TimeTicks::Min();
  }
References v8::internal::duration, v8::base::time_internal::TimeBase< TimeTicks >::Min(), and v8::base::TimeTicks::Now().
Member Data Documentation
event_
template<class T , int64_t(base::TimeDelta::*)() const precision = &base::TimeDelta::InMicroseconds>
T* v8::internal::metrics::TimedScope< T, precision >::event_ [private]
Definition at line 103 of file metrics.h.
start_time_
template<class T , int64_t(base::TimeDelta::*)() const precision = &base::TimeDelta::InMicroseconds>
base::TimeTicks v8::internal::metrics::TimedScope< T, precision >::start_time_ [private]
Definition at line 104 of file metrics.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/logging/metrics.h