v8::internal::baseline::BaselineAssembler::ScratchRegisterScope Class Reference
#include <baseline-assembler-arm-inl.h>
Public Member Functions
ScratchRegisterScope (BaselineAssembler *assembler)
~ScratchRegisterScope ()
Register AcquireScratch ()
ScratchRegisterScope (BaselineAssembler *assembler)
~ScratchRegisterScope ()
Register AcquireScratch ()
ScratchRegisterScope (BaselineAssembler *assembler)
~ScratchRegisterScope ()
Register AcquireScratch ()
ScratchRegisterScope (BaselineAssembler *assembler)
~ScratchRegisterScope ()
Register AcquireScratch ()
ScratchRegisterScope (BaselineAssembler *assembler)
~ScratchRegisterScope ()
Register AcquireScratch ()
ScratchRegisterScope (BaselineAssembler *assembler)
~ScratchRegisterScope ()
Register AcquireScratch ()
ScratchRegisterScope (BaselineAssembler *assembler)
~ScratchRegisterScope ()
Register AcquireScratch ()
ScratchRegisterScope (BaselineAssembler *assembler)
~ScratchRegisterScope ()
Register AcquireScratch ()
ScratchRegisterScope (BaselineAssembler *assembler)
~ScratchRegisterScope ()
Register AcquireScratch ()
Private Attributes
BaselineAssembler * assembler_
ScratchRegisterScope * prev_scope_
UseScratchRegisterScope wrapped_scope_
int registers_used_
Detailed Description
Definition at line 17 of file baseline-assembler-arm-inl.h.
Constructor & Destructor Documentation
ScratchRegisterScope() [1/9]
v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::ScratchRegisterScope (BaselineAssembler * assembler) [inline], [explicit]
Definition at line 19 of file baseline-assembler-arm-inl.h.
      : assembler_(assembler),
        prev_scope_(assembler->scratch_register_scope_),
        wrapped_scope_(assembler->masm()) {
    if (!assembler_->scratch_register_scope_) {
      // If we haven't opened a scratch scope yet, for the first one add a
      // couple of extra registers.
      DCHECK(wrapped_scope_.CanAcquire());
      wrapped_scope_.Include(r8, r9);
      wrapped_scope_.Include(kInterpreterBytecodeOffsetRegister);
    }
    assembler_->scratch_register_scope_ = this;
  }
References assembler_, v8::internal::UseScratchRegisterScope::CanAcquire(), v8::internal::DCHECK(), v8::internal::UseScratchRegisterScope::Include(), v8::internal::kInterpreterBytecodeOffsetRegister, v8::internal::baseline::BaselineAssembler::scratch_register_scope_, and wrapped_scope_.
 ScratchRegisterScope() [1/9]
v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::~ScratchRegisterScope () [inline]
Definition at line 32 of file baseline-assembler-arm-inl.h.
{ assembler_->scratch_register_scope_ = prev_scope_; }
References assembler_, prev_scope_, and v8::internal::baseline::BaselineAssembler::scratch_register_scope_.
ScratchRegisterScope() [2/9]
v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::ScratchRegisterScope (BaselineAssembler * assembler) [inline], [explicit]
Definition at line 19 of file baseline-assembler-arm64-inl.h.
      : assembler_(assembler),
        prev_scope_(assembler->scratch_register_scope_),
        wrapped_scope_(assembler->masm()) {
    if (!assembler_->scratch_register_scope_) {
      // If we haven't opened a scratch scope yet, for the first one add a
      // couple of extra registers.
      wrapped_scope_.Include(x14, x15);
      wrapped_scope_.Include(x19);
    }
    assembler_->scratch_register_scope_ = this;
  }
References assembler_, v8::internal::UseScratchRegisterScope::Include(), v8::internal::baseline::BaselineAssembler::scratch_register_scope_, and wrapped_scope_.
 ScratchRegisterScope() [2/9]
v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::~ScratchRegisterScope () [inline]
Definition at line 31 of file baseline-assembler-arm64-inl.h.
{ assembler_->scratch_register_scope_ = prev_scope_; }
References assembler_, prev_scope_, and v8::internal::baseline::BaselineAssembler::scratch_register_scope_.
ScratchRegisterScope() [3/9]
v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::ScratchRegisterScope (BaselineAssembler * assembler) [inline], [explicit]
Definition at line 27 of file baseline-assembler-ia32-inl.h.
      : assembler_(assembler),
        prev_scope_(assembler->scratch_register_scope_),
        registers_used_(prev_scope_ == nullptr ? 0
                                               : prev_scope_->registers_used_) {
    assembler_->scratch_register_scope_ = this;
  }
References assembler_, and v8::internal::baseline::BaselineAssembler::scratch_register_scope_.
 ScratchRegisterScope() [3/9]
v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::~ScratchRegisterScope () [inline]
Definition at line 34 of file baseline-assembler-ia32-inl.h.
{ assembler_->scratch_register_scope_ = prev_scope_; }
References assembler_, prev_scope_, and v8::internal::baseline::BaselineAssembler::scratch_register_scope_.
ScratchRegisterScope() [4/9]
v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::ScratchRegisterScope (BaselineAssembler * assembler) [inline], [explicit]
Definition at line 19 of file baseline-assembler-loong64-inl.h.
      : assembler_(assembler),
        prev_scope_(assembler->scratch_register_scope_),
        wrapped_scope_(assembler->masm()) {
    if (!assembler_->scratch_register_scope_) {
      // If we haven't opened a scratch scope yet, for the first one add a
      // couple of extra registers.
      wrapped_scope_.Include({t0, t1, t2, t3});
    }
    assembler_->scratch_register_scope_ = this;
  }
References assembler_, v8::internal::UseScratchRegisterScope::Include(), v8::internal::baseline::BaselineAssembler::scratch_register_scope_, and wrapped_scope_.
 ScratchRegisterScope() [4/9]
v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::~ScratchRegisterScope () [inline]
Definition at line 30 of file baseline-assembler-loong64-inl.h.
{ assembler_->scratch_register_scope_ = prev_scope_; }
References assembler_, prev_scope_, and v8::internal::baseline::BaselineAssembler::scratch_register_scope_.
ScratchRegisterScope() [5/9]
v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::ScratchRegisterScope (BaselineAssembler * assembler) [inline], [explicit]
Definition at line 19 of file baseline-assembler-mips64-inl.h.
      : assembler_(assembler),
        prev_scope_(assembler->scratch_register_scope_),
        wrapped_scope_(assembler->masm()) {
    if (!assembler_->scratch_register_scope_) {
      // If we haven't opened a scratch scope yet, for the first one add a
      // couple of extra registers.
      wrapped_scope_.Include({t0, t1, t2, t3});
    }
    assembler_->scratch_register_scope_ = this;
  }
References assembler_, v8::internal::UseScratchRegisterScope::Include(), v8::internal::baseline::BaselineAssembler::scratch_register_scope_, and wrapped_scope_.
 ScratchRegisterScope() [5/9]
v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::~ScratchRegisterScope () [inline]
Definition at line 30 of file baseline-assembler-mips64-inl.h.
{ assembler_->scratch_register_scope_ = prev_scope_; }
References assembler_, prev_scope_, and v8::internal::baseline::BaselineAssembler::scratch_register_scope_.
ScratchRegisterScope() [6/9]
v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::ScratchRegisterScope (BaselineAssembler * assembler) [inline], [explicit]
Definition at line 32 of file baseline-assembler-ppc-inl.h.
      : assembler_(assembler),
        prev_scope_(assembler->scratch_register_scope_),
        registers_used_(prev_scope_ == nullptr ? 0
                                               : prev_scope_->registers_used_) {
    assembler_->scratch_register_scope_ = this;
  }
References assembler_, and v8::internal::baseline::BaselineAssembler::scratch_register_scope_.
 ScratchRegisterScope() [6/9]
v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::~ScratchRegisterScope () [inline]
Definition at line 39 of file baseline-assembler-ppc-inl.h.
{ assembler_->scratch_register_scope_ = prev_scope_; }
References assembler_, prev_scope_, and v8::internal::baseline::BaselineAssembler::scratch_register_scope_.
ScratchRegisterScope() [7/9]
v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::ScratchRegisterScope (BaselineAssembler * assembler) [inline], [explicit]
Definition at line 18 of file baseline-assembler-riscv-inl.h.
      : assembler_(assembler),
        prev_scope_(assembler->scratch_register_scope_),
        wrapped_scope_(assembler->masm()) {
    if (!assembler_->scratch_register_scope_) {
      // If we haven't opened a scratch scope yet, for the first one add a
      // couple of extra registers.
      wrapped_scope_.Include(kScratchReg, kScratchReg2);
    }
    assembler_->scratch_register_scope_ = this;
  }
References assembler_, v8::internal::UseScratchRegisterScope::Include(), v8::internal::kScratchReg, v8::internal::kScratchReg2, v8::internal::baseline::BaselineAssembler::scratch_register_scope_, and wrapped_scope_.
 ScratchRegisterScope() [7/9]
v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::~ScratchRegisterScope () [inline]
Definition at line 29 of file baseline-assembler-riscv-inl.h.
{ assembler_->scratch_register_scope_ = prev_scope_; }
References assembler_, prev_scope_, and v8::internal::baseline::BaselineAssembler::scratch_register_scope_.
ScratchRegisterScope() [8/9]
v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::ScratchRegisterScope (BaselineAssembler * assembler) [inline], [explicit]
Definition at line 31 of file baseline-assembler-s390-inl.h.
      : assembler_(assembler),
        prev_scope_(assembler->scratch_register_scope_),
        registers_used_(prev_scope_ == nullptr ? 0
                                               : prev_scope_->registers_used_) {
    assembler_->scratch_register_scope_ = this;
  }
References assembler_, and v8::internal::baseline::BaselineAssembler::scratch_register_scope_.
 ScratchRegisterScope() [8/9]
v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::~ScratchRegisterScope () [inline]
Definition at line 38 of file baseline-assembler-s390-inl.h.
{ assembler_->scratch_register_scope_ = prev_scope_; }
References assembler_, prev_scope_, and v8::internal::baseline::BaselineAssembler::scratch_register_scope_.
ScratchRegisterScope() [9/9]
v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::ScratchRegisterScope (BaselineAssembler * assembler) [inline], [explicit]
Definition at line 29 of file baseline-assembler-x64-inl.h.
      : assembler_(assembler),
        prev_scope_(assembler->scratch_register_scope_),
        registers_used_(prev_scope_ == nullptr ? 0
                                               : prev_scope_->registers_used_) {
    assembler_->scratch_register_scope_ = this;
  }
References assembler_, and v8::internal::baseline::BaselineAssembler::scratch_register_scope_.
 ScratchRegisterScope() [9/9]
v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::~ScratchRegisterScope () [inline]
Definition at line 36 of file baseline-assembler-x64-inl.h.
{ assembler_->scratch_register_scope_ = prev_scope_; }
References assembler_, prev_scope_, and v8::internal::baseline::BaselineAssembler::scratch_register_scope_.
Member Function Documentation
AcquireScratch() [1/9]
Register v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::AcquireScratch () [inline]
Definition at line 34 of file baseline-assembler-arm-inl.h.
{ return wrapped_scope_.Acquire(); }
References v8::internal::UseScratchRegisterScope::Acquire(), and wrapped_scope_.
Referenced by v8::internal::baseline::BaselineAssembler::AddToInterruptBudgetAndJumpIfNotExceeded(), v8::internal::baseline::BaselineAssembler::EmitReturn(), v8::internal::baseline::BaselineAssembler::IncrementSmi(), v8::internal::baseline::BaselineAssembler::JumpIfInstanceType(), v8::internal::baseline::BaselineAssembler::JumpIfObjectType(), v8::internal::baseline::BaselineAssembler::JumpIfObjectTypeFast(), v8::internal::baseline::BaselineAssembler::JumpIfPointer(), v8::internal::baseline::BaselineAssembler::JumpIfTagged(), v8::internal::baseline::BaselineAssembler::LoadFeedbackCell(), v8::internal::baseline::BaselineCompiler::PrologueFillFrame(), v8::internal::baseline::BaselineAssembler::StoreTaggedSignedField(), v8::internal::baseline::detail::ToRegister(), v8::internal::baseline::BaselineAssembler::TryLoadOptimizedOsrCode(), v8::internal::baseline::BaselineCompiler::VerifyFrame(), v8::internal::baseline::BaselineCompiler::VerifyFrameSize(), and v8::internal::baseline::EnsureAccumulatorPreservedScope::~EnsureAccumulatorPreservedScope().
AcquireScratch() [2/9]
Register v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::AcquireScratch () [inline]
Definition at line 33 of file baseline-assembler-arm64-inl.h.
{ return wrapped_scope_.AcquireX(); }
References v8::internal::UseScratchRegisterScope::AcquireX(), and wrapped_scope_.
AcquireScratch() [3/9]
Register v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::AcquireScratch () [inline]
Definition at line 36 of file baseline-assembler-ia32-inl.h.
                            {
    DCHECK_LT(registers_used_, detail::kNumScratchRegisters);
    return detail::kScratchRegisters[registers_used_++];
  }
References DCHECK_LT, v8::internal::baseline::detail::kNumScratchRegisters, v8::internal::baseline::detail::kScratchRegisters, and registers_used_.
AcquireScratch() [4/9]
Register v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::AcquireScratch () [inline]
Definition at line 32 of file baseline-assembler-loong64-inl.h.
{ return wrapped_scope_.Acquire(); }
References v8::internal::UseScratchRegisterScope::Acquire(), and wrapped_scope_.
AcquireScratch() [5/9]
Register v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::AcquireScratch () [inline]
Definition at line 32 of file baseline-assembler-mips64-inl.h.
{ return wrapped_scope_.Acquire(); }
References v8::internal::UseScratchRegisterScope::Acquire(), and wrapped_scope_.
AcquireScratch() [6/9]
Register v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::AcquireScratch () [inline]
Definition at line 41 of file baseline-assembler-ppc-inl.h.
                            {
    DCHECK_LT(registers_used_, detail::kNumScratchRegisters);
    return detail::kScratchRegisters[registers_used_++];
  }
References DCHECK_LT, v8::internal::baseline::detail::kNumScratchRegisters, v8::internal::baseline::detail::kScratchRegisters, and registers_used_.
AcquireScratch() [7/9]
Register v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::AcquireScratch () [inline]
Definition at line 31 of file baseline-assembler-riscv-inl.h.
{ return wrapped_scope_.Acquire(); }
References v8::internal::UseScratchRegisterScope::Acquire(), and wrapped_scope_.
AcquireScratch() [8/9]
Register v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::AcquireScratch () [inline]
Definition at line 40 of file baseline-assembler-s390-inl.h.
                            {
    DCHECK_LT(registers_used_, detail::kNumScratchRegisters);
    return detail::kScratchRegisters[registers_used_++];
  }
References DCHECK_LT, v8::internal::baseline::detail::kNumScratchRegisters, v8::internal::baseline::detail::kScratchRegisters, and registers_used_.
AcquireScratch() [9/9]
Register v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::AcquireScratch () [inline]
Definition at line 38 of file baseline-assembler-x64-inl.h.
                            {
    DCHECK_LT(registers_used_, detail::kNumScratchRegisters);
    return detail::kScratchRegisters[registers_used_++];
  }
References DCHECK_LT, v8::internal::baseline::detail::kNumScratchRegisters, v8::internal::baseline::detail::kScratchRegisters, and registers_used_.
Member Data Documentation
assembler_
BaselineAssembler * v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::assembler_ [private]
Definition at line 37 of file baseline-assembler-arm-inl.h.
Referenced by ScratchRegisterScope(), and ~ScratchRegisterScope().
prev_scope_
ScratchRegisterScope * v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::prev_scope_ [private]
Definition at line 38 of file baseline-assembler-arm-inl.h.
Referenced by ~ScratchRegisterScope().
registers_used_
int v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::registers_used_ [private]
Definition at line 44 of file baseline-assembler-ia32-inl.h.
Referenced by AcquireScratch().
wrapped_scope_
UseScratchRegisterScope v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::wrapped_scope_ [private]
Definition at line 39 of file baseline-assembler-arm-inl.h.
Referenced by AcquireScratch(), and ScratchRegisterScope().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/baseline/arm/baseline-assembler-arm-inl.h
/mnt/V8SourceCode/src/baseline/arm64/baseline-assembler-arm64-inl.h
/mnt/V8SourceCode/src/baseline/ia32/baseline-assembler-ia32-inl.h
/mnt/V8SourceCode/src/baseline/loong64/baseline-assembler-loong64-inl.h
/mnt/V8SourceCode/src/baseline/mips64/baseline-assembler-mips64-inl.h
/mnt/V8SourceCode/src/baseline/ppc/baseline-assembler-ppc-inl.h
/mnt/V8SourceCode/src/baseline/riscv/baseline-assembler-riscv-inl.h
/mnt/V8SourceCode/src/baseline/s390/baseline-assembler-s390-inl.h
/mnt/V8SourceCode/src/baseline/x64/baseline-assembler-x64-inl.h