v8::internal::wasm::FunctionBodyDisassembler Class Reference
#include <wasm-disassembler-impl.h>
Public Types
enum FunctionHeader : bool { kSkipHeader = false
, kPrintHeader = true
 }
using ValidationTag = Decoder::FullValidationTag
Public Member Functions
FunctionBodyDisassembler (Zone *zone, const WasmModule *module, uint32_t func_index, bool shared, WasmDetectedFeatures *detected, const FunctionSig *sig, const uint8_t *start, const uint8_t *end, uint32_t offset, const ModuleWireBytes wire_bytes, NamesProvider *names)
void DecodeAsWat (MultiLineStringBuilder &out, Indentation indentation, FunctionHeader include_header=kPrintHeader, uint32_t *first_instruction_offset=nullptr)
void DecodeGlobalInitializer (StringBuilder &out)
std::set< uint32_t > & used_types ()
Protected Member Functions
WasmOpcode GetOpcode ()
uint32_t PrintImmediatesAndGetLength (StringBuilder &out)
void PrintHexNumber (StringBuilder &out, uint64_t number)
LabelInfo & label_info (int depth)
Protected Attributes
uint32_t func_index_
WasmOpcode current_opcode_ = kExprUnreachable
const ModuleWireBytes wire_bytes_
NamesProvider * names_
std::set< uint32_t > used_types_
std::vector< LabelInfo > label_stack_
MultiLineStringBuilder * out_
uint32_t label_occurrence_index_ = 0
uint32_t label_generation_index_ = 0
Friends
class ImmediatesPrinter< ValidationTag >
Additional Inherited Members
Detailed Description
Definition at line 236 of file wasm-disassembler-impl.h.
Member Typedef Documentation
ValidationTag
using v8::internal::wasm::FunctionBodyDisassembler::ValidationTag = Decoder::FullValidationTag
Definition at line 239 of file wasm-disassembler-impl.h.
Member Enumeration Documentation
FunctionHeader
enum v8::internal::wasm::FunctionBodyDisassembler::FunctionHeader : bool
Enumerator
kSkipHeader
kPrintHeader
Definition at line 240 of file wasm-disassembler-impl.h.
: bool { kSkipHeader = false, kPrintHeader = true };
Constructor & Destructor Documentation
FunctionBodyDisassembler()
v8::internal::wasm::FunctionBodyDisassembler::FunctionBodyDisassembler (Zone * zone, const WasmModule * module, uint32_t func_index, bool shared, WasmDetectedFeatures * detected, const FunctionSig * sig, const uint8_t * start, const uint8_t * end, uint32_t offset, const ModuleWireBytes wire_bytes, NamesProvider * names) [inline]
Definition at line 242 of file wasm-disassembler-impl.h.
      : WasmDecoder<ValidationTag>(zone, module, WasmEnabledFeatures::All(),
                                   detected, sig, shared, start, end, offset),
        func_index_(func_index),
        wire_bytes_(wire_bytes),
        names_(names) {}
Member Function Documentation
DecodeAsWat()
void v8::internal::wasm::FunctionBodyDisassembler::DecodeAsWat (MultiLineStringBuilder & out, Indentation indentation, FunctionHeader include_header = kPrintHeader, uint32_t * first_instruction_offset = nullptr)
Definition at line 217 of file wasm-disassembler.cc.
                                                                               {
  out_ = &out;
  int base_indentation = indentation.current();
  // Print header.
  if (include_header == kPrintHeader) {
    out << indentation << "(func ";
    names_->PrintFunctionName(out, func_index_, NamesProvider::kDevTools);
    PrintSignatureOneLine(out, sig_, func_index_, names_, true,
                          kIndicesAsComments);
    out.NextLine(pc_offset());
  } else {
    out.set_current_line_bytecode_offset(pc_offset());
  }
  indentation.increase();
  // Decode and print locals.
  uint32_t locals_length = DecodeLocals(pc_);
  if (failed()) {
    // TODO(jkummerow): Improve error handling.
    out << "Failed to decode locals\n";
    return;
  }
  for (uint32_t i = static_cast<uint32_t>(sig_->parameter_count());
       i < num_locals_; i++) {
    out << indentation << "(local ";
    names_->PrintLocalName(out, func_index_, i);
    out << " ";
    names_->PrintValueType(out, local_type(i));
    out << ")";
    out.NextLine(pc_offset());
  }
  consume_bytes(locals_length);
  out.set_current_line_bytecode_offset(pc_offset());
  if (first_instruction_offset) *first_instruction_offset = pc_offset();
  // Main loop.
  while (pc_ < end_ && ok()) {
    WasmOpcode opcode = GetOpcode();
    current_opcode_ = opcode; // Some immediates need to know this.
    // Deal with indentation.
    if (opcode == kExprEnd || opcode == kExprElse || opcode == kExprCatch ||
        opcode == kExprCatchAll || opcode == kExprDelegate) {
      if (indentation.current() >= base_indentation) {
        indentation.decrease();
      }
    }
    out << indentation;
    if (opcode == kExprElse || opcode == kExprCatch ||
        opcode == kExprCatchAll || opcode == kExprBlock || opcode == kExprIf ||
        opcode == kExprLoop || opcode == kExprTry || opcode == kExprTryTable) {
      indentation.increase();
    }
    // Print the opcode and its immediates.
    if (opcode == kExprEnd) {
      if (indentation.current() < base_indentation) {
        out << ";; Unexpected end byte";
      } else if (indentation.current() == base_indentation) {
        out << ")"; // End of the function.
      } else {
        out << "end";
        const LabelInfo& label = label_stack_.back();
        if (label.start != nullptr) {
          out << " ";
          out.write(label.start, label.length);
        }
        label_stack_.pop_back();
      }
    } else {
      out << WasmOpcodes::OpcodeName(opcode);
    }
    if (opcode == kExprBlock || opcode == kExprIf || opcode == kExprLoop ||
        opcode == kExprTry || opcode == kExprTryTable) {
      // Create the LabelInfo now to get the correct offset, but only push it
      // after printing the immediates because the immediates don't see the new
      // label yet.
      LabelInfo label(out.line_number(), out.length(),
                      label_occurrence_index_++);
      pc_ += PrintImmediatesAndGetLength(out);
      label_stack_.push_back(label);
    } else {
      pc_ += PrintImmediatesAndGetLength(out);
    }
    out.NextLine(pc_offset());
  }
  if (pc_ != end_) {
    // TODO(jkummerow): Improve error handling.
    out << "Beyond end of code";
  }
}
References v8::internal::wasm::Decoder::consume_bytes(), v8::internal::wasm::Indentation::current(), current_opcode_, v8::internal::wasm::WasmDecoder< Decoder::FullValidationTag >::DecodeLocals(), v8::internal::wasm::Indentation::decrease(), v8::internal::wasm::Decoder::end_, v8::internal::wasm::Decoder::failed(), func_index_, GetOpcode(), v8::internal::wasm::Indentation::increase(), v8::internal::wasm::NamesProvider::kDevTools, v8::internal::wasm::kIndicesAsComments, kPrintHeader, label_occurrence_index_, label_stack_, v8::internal::wasm::LabelInfo::length, v8::internal::wasm::StringBuilder::length(), v8::internal::wasm::MultiLineStringBuilder::line_number(), v8::internal::wasm::WasmDecoder< Decoder::FullValidationTag >::local_type(), names_, v8::internal::wasm::MultiLineStringBuilder::NextLine(), v8::internal::wasm::WasmDecoder< Decoder::FullValidationTag >::num_locals_, v8::internal::wasm::Decoder::ok(), v8::internal::wasm::WasmOpcodes::OpcodeName(), out_, v8::internal::Signature< T >::parameter_count(), v8::internal::wasm::Decoder::pc_, v8::internal::wasm::Decoder::pc_offset(), v8::internal::wasm::NamesProvider::PrintFunctionName(), PrintImmediatesAndGetLength(), v8::internal::wasm::NamesProvider::PrintLocalName(), v8::internal::wasm::PrintSignatureOneLine(), v8::internal::wasm::NamesProvider::PrintValueType(), v8::internal::wasm::MultiLineStringBuilder::set_current_line_bytecode_offset(), v8::internal::wasm::WasmDecoder< Decoder::FullValidationTag >::sig_, v8::internal::wasm::LabelInfo::start, and v8::internal::wasm::StringBuilder::write().
Referenced by v8::internal::wasm::DisassembleFunctionImpl(), and v8::internal::wasm::ModuleDisassembler::PrintModule().
DecodeGlobalInitializer()
void v8::internal::wasm::FunctionBodyDisassembler::DecodeGlobalInitializer (StringBuilder & out)
Definition at line 314 of file wasm-disassembler.cc.
                                                                         {
  while (pc_ < end_) {
    WasmOpcode opcode = GetOpcode();
    current_opcode_ = opcode; // Some immediates need to know this.
    // Don't print the final "end".
    if (opcode == kExprEnd && pc_ + 1 == end_) break;
    uint32_t length;
    out << " (" << WasmOpcodes::OpcodeName(opcode);
    length = PrintImmediatesAndGetLength(out);
    out << ")";
    pc_ += length;
  }
}
References current_opcode_, v8::internal::wasm::Decoder::end_, GetOpcode(), v8::internal::length, v8::internal::wasm::WasmOpcodes::OpcodeName(), v8::internal::wasm::Decoder::pc_, and PrintImmediatesAndGetLength().
Referenced by v8::internal::wasm::ModuleDisassembler::PrintInitExpression().
GetOpcode()
WasmOpcode v8::internal::wasm::FunctionBodyDisassembler::GetOpcode () [protected]
Definition at line 328 of file wasm-disassembler.cc.
                                               {
  WasmOpcode opcode = static_cast<WasmOpcode>(*pc_);
  if (!WasmOpcodes::IsPrefixOpcode(opcode)) return opcode;
  return read_prefixed_opcode<ValidationTag>(pc_).first;
}
References v8::internal::wasm::WasmOpcodes::IsPrefixOpcode(), and v8::internal::wasm::Decoder::pc_.
Referenced by DecodeAsWat(), and DecodeGlobalInitializer().
label_info()
LabelInfo& v8::internal::wasm::FunctionBodyDisassembler::label_info (int depth) [inline], [protected]
Definition at line 270 of file wasm-disassembler-impl.h.
                                   {
    return label_stack_[label_stack_.size() - 1 - depth];
  }
Referenced by v8::internal::wasm::ImmediatesPrinter< ValidationTag >::PrintDepthAsLabel().
PrintHexNumber()
void v8::internal::wasm::FunctionBodyDisassembler::PrintHexNumber (StringBuilder & out, uint64_t number) [protected]
Definition at line 334 of file wasm-disassembler.cc.
                                                               {
  constexpr size_t kBufferSize = sizeof(number) * 2 + 2; // +2 for "0x".
  char buffer[kBufferSize];
  char* end = buffer + kBufferSize;
  char* ptr = end;
  do {
    *(--ptr) = kHexChars[number & 0xF];
    number >>= 4;
  } while (number > 0);
  *(--ptr) = 'x';
  *(--ptr) = '0';
  size_t length = static_cast<size_t>(end - ptr);
  char* output = out.allocate(length);
  memcpy(output, ptr, length);
}
References v8::internal::wasm::StringBuilder::allocate(), v8::internal::wasm::Decoder::buffer, v8::internal::wasm::Decoder::end(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::kBufferSize, v8::internal::wasm::kHexChars, and v8::internal::length.
Referenced by v8::internal::wasm::ImmediatesPrinter< ValidationTag >::F32Const(), and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::F64Const().
PrintImmediatesAndGetLength()
uint32_t v8::internal::wasm::FunctionBodyDisassembler::PrintImmediatesAndGetLength (StringBuilder & out) [protected]
Definition at line 730 of file wasm-disassembler.cc.
                        {
  using Printer = ImmediatesPrinter<ValidationTag>;
  Printer imm_printer(out, this);
  return WasmDecoder::OpcodeLength<Printer>(this, this->pc_, imm_printer);
}
References v8::internal::wasm::Decoder::pc_.
Referenced by DecodeAsWat(), and DecodeGlobalInitializer().
used_types()
std::set<uint32_t>& v8::internal::wasm::FunctionBodyDisassembler::used_types () [inline]
Definition at line 261 of file wasm-disassembler-impl.h.
{ return used_types_; }
Friends And Related Function Documentation
ImmediatesPrinter< ValidationTag >
friend class ImmediatesPrinter< ValidationTag > [friend]
Definition at line 270 of file wasm-disassembler-impl.h.
Member Data Documentation
current_opcode_
WasmOpcode v8::internal::wasm::FunctionBodyDisassembler::current_opcode_ = kExprUnreachable [protected]
Definition at line 276 of file wasm-disassembler-impl.h.
Referenced by DecodeAsWat(), DecodeGlobalInitializer(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::MemoryAccess(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::PrintDepthAsLabel(), and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::S128Const().
func_index_
uint32_t v8::internal::wasm::FunctionBodyDisassembler::func_index_ [protected]
Definition at line 275 of file wasm-disassembler-impl.h.
Referenced by DecodeAsWat(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::func_index(), and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::PrintDepthAsLabel().
label_generation_index_
uint32_t v8::internal::wasm::FunctionBodyDisassembler::label_generation_index_ = 0 [protected]
Definition at line 288 of file wasm-disassembler-impl.h.
Referenced by v8::internal::wasm::ImmediatesPrinter< ValidationTag >::PrintDepthAsLabel().
label_occurrence_index_
uint32_t v8::internal::wasm::FunctionBodyDisassembler::label_occurrence_index_ = 0 [protected]
Definition at line 287 of file wasm-disassembler-impl.h.
Referenced by DecodeAsWat().
label_stack_
std::vector<LabelInfo> v8::internal::wasm::FunctionBodyDisassembler::label_stack_ [protected]
Definition at line 280 of file wasm-disassembler-impl.h.
Referenced by DecodeAsWat(), and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::PrintDepthAsLabel().
names_
NamesProvider* v8::internal::wasm::FunctionBodyDisassembler::names_ [protected]
Definition at line 278 of file wasm-disassembler-impl.h.
Referenced by DecodeAsWat(), and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::names().
out_
MultiLineStringBuilder* v8::internal::wasm::FunctionBodyDisassembler::out_ [protected]
Definition at line 281 of file wasm-disassembler-impl.h.
Referenced by DecodeAsWat(), and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::PrintDepthAsLabel().
used_types_
std::set<uint32_t> v8::internal::wasm::FunctionBodyDisassembler::used_types_ [protected]
Definition at line 279 of file wasm-disassembler-impl.h.
Referenced by v8::internal::wasm::ImmediatesPrinter< ValidationTag >::use_type().
wire_bytes_
const ModuleWireBytes v8::internal::wasm::FunctionBodyDisassembler::wire_bytes_ [protected]
Definition at line 277 of file wasm-disassembler-impl.h.
Referenced by v8::internal::wasm::ImmediatesPrinter< ValidationTag >::StringConst().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-disassembler-impl.h
/mnt/V8SourceCode/src/wasm/wasm-disassembler.cc