v8::internal::LinearAreaOriginalData Class Reference
#include <main-allocator.h>
Public Member Functions
std::pair< Address, Address > GetTopAndLimit () const
std::pair< Address, Address > GetTopAndLimitLocked () const
void SetTopAndLimit (Address top, Address limit)
Private Attributes
std::atomic< Address > original_top_ = 0
std::atomic< Address > original_limit_ = 0
base::Mutex mutex_
Detailed Description
Definition at line 119 of file main-allocator.h.
Member Function Documentation
GetTopAndLimit()
std::pair<Address, Address> v8::internal::LinearAreaOriginalData::GetTopAndLimit () const [inline]
Definition at line 131 of file main-allocator.h.
                                                   {
    // The order of the two loads is important. See SetTopAndLimit().
    auto top = original_top_.load(std::memory_order_acquire);
    auto limit = original_limit_.load(std::memory_order_relaxed);
    return std::make_pair(top, limit);
  }
Referenced by GetTopAndLimitLocked().
GetTopAndLimitLocked()
std::pair< Address, Address > v8::internal::LinearAreaOriginalData::GetTopAndLimitLocked () const
Definition at line 944 of file main-allocator.cc.
          {
  base::MutexGuard guard(mutex_);
  auto [top, limit] = GetTopAndLimit();
  // This always holds because we load both fields while locking the mutex.
  DCHECK_LE(top, limit);
  return std::make_pair(top, limit);
}
References DCHECK_LE, GetTopAndLimit(), and mutex_.
Referenced by v8::internal::MainAllocator::IsPendingAllocation().
SetTopAndLimit()
void v8::internal::LinearAreaOriginalData::SetTopAndLimit (Address top, Address limit)
Definition at line 953 of file main-allocator.cc.
                                                                      {
  base::MutexGuard guard(mutex_);
  // The order of the two stores is important. See GetTopAndLimit().
  original_limit_.store(limit, std::memory_order_relaxed);
  // Use acquire/release semantics here to prevent subsequent stores to move
  // before this store here.
  original_top_.exchange(top, std::memory_order_acq_rel);
}
References mutex_, original_limit_, and original_top_.
Referenced by v8::internal::MainAllocator::MoveOriginalTopForward(), and v8::internal::MainAllocator::ResetLab().
Member Data Documentation
mutex_
base::Mutex v8::internal::LinearAreaOriginalData::mutex_ [mutable], [private]
Definition at line 150 of file main-allocator.h.
Referenced by GetTopAndLimitLocked(), and SetTopAndLimit().
original_limit_
std::atomic<Address> v8::internal::LinearAreaOriginalData::original_limit_ = 0 [private]
Definition at line 147 of file main-allocator.h.
Referenced by SetTopAndLimit().
original_top_
std::atomic<Address> v8::internal::LinearAreaOriginalData::original_top_ = 0 [private]
Definition at line 146 of file main-allocator.h.
Referenced by SetTopAndLimit().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/main-allocator.h
/mnt/V8SourceCode/src/heap/main-allocator.cc