v8::platform::tracing::TraceBufferRingBuffer Class Reference
#include <trace-buffer.h>
Public Member Functions
TraceBufferRingBuffer (size_t max_chunks, TraceWriter *trace_writer)
~TraceBufferRingBuffer () override=default
TraceObject * AddTraceEvent (uint64_t *handle) override
TraceObject * GetEventByHandle (uint64_t handle) override
bool Flush () override
Private Member Functions
uint64_t MakeHandle (size_t chunk_index, uint32_t chunk_seq, size_t event_index) const
void ExtractHandle (uint64_t handle, size_t *chunk_index, uint32_t *chunk_seq, size_t *event_index) const
size_t Capacity () const
size_t NextChunkIndex (size_t index) const
Private Attributes
base::Mutex mutex_
size_t max_chunks_
std::unique_ptr< TraceWriter > trace_writer_
std::vector< std::unique_ptr< TraceBufferChunk > > chunks_
size_t chunk_index_
bool is_empty_ = true
uint32_t current_chunk_seq_ = 1
Additional Inherited Members
Detailed Description
Definition at line 18 of file trace-buffer.h.
Constructor & Destructor Documentation
TraceBufferRingBuffer()
v8::platform::tracing::TraceBufferRingBuffer::TraceBufferRingBuffer (size_t max_chunks, TraceWriter * trace_writer)
Definition at line 11 of file trace-buffer.cc.
    : max_chunks_(max_chunks) {
  trace_writer_.reset(trace_writer);
  chunks_.resize(max_chunks);
}
References chunks_, and trace_writer_.
 TraceBufferRingBuffer()
v8::platform::tracing::TraceBufferRingBuffer::~TraceBufferRingBuffer () [override], [default]
Member Function Documentation
AddTraceEvent()
TraceObject * v8::platform::tracing::TraceBufferRingBuffer::AddTraceEvent (uint64_t * handle) [override], [virtual]
Implements v8::platform::tracing::TraceBuffer.
Definition at line 18 of file trace-buffer.cc.
                                                                  {
  base::MutexGuard guard(&mutex_);
  if (is_empty_ || chunks_[chunk_index_]->IsFull()) {
    chunk_index_ = is_empty_ ? 0 : NextChunkIndex(chunk_index_);
    is_empty_ = false;
    auto& chunk = chunks_[chunk_index_];
    if (chunk) {
      chunk->Reset(current_chunk_seq_++);
    } else {
      chunk.reset(new TraceBufferChunk(current_chunk_seq_++));
    }
  }
  auto& chunk = chunks_[chunk_index_];
  size_t event_index;
  TraceObject* trace_object = chunk->AddTraceEvent(&event_index);
  *handle = MakeHandle(chunk_index_, chunk->seq(), event_index);
  return trace_object;
}
References chunk_index_, chunks_, current_chunk_seq_, v8::internal::handle(), is_empty_, MakeHandle(), mutex_, and NextChunkIndex().
Capacity()
size_t v8::platform::tracing::TraceBufferRingBuffer::Capacity () const [inline], [private]
Definition at line 33 of file trace-buffer.h.
{ return max_chunks_ * TraceBufferChunk::kChunkSize; }
References v8::platform::tracing::TraceBufferChunk::kChunkSize, and max_chunks_.
Referenced by ExtractHandle(), and MakeHandle().
ExtractHandle()
void v8::platform::tracing::TraceBufferRingBuffer::ExtractHandle (uint64_t handle, size_t * chunk_index, uint32_t * chunk_seq, size_t * event_index) const [private]
Definition at line 74 of file trace-buffer.cc.
                                                                     {
  *chunk_seq = static_cast<uint32_t>(handle / Capacity());
  size_t indices = handle % Capacity();
  *chunk_index = indices / TraceBufferChunk::kChunkSize;
  *event_index = indices % TraceBufferChunk::kChunkSize;
}
References Capacity(), v8::internal::handle(), and v8::platform::tracing::TraceBufferChunk::kChunkSize.
Referenced by GetEventByHandle().
Flush()
bool v8::platform::tracing::TraceBufferRingBuffer::Flush () [override], [virtual]
Implements v8::platform::tracing::TraceBuffer.
Definition at line 48 of file trace-buffer.cc.
                                  {
  base::MutexGuard guard(&mutex_);
  // This flushes all the traces stored in the buffer.
  if (!is_empty_) {
    for (size_t i = NextChunkIndex(chunk_index_);; i = NextChunkIndex(i)) {
      if (auto& chunk = chunks_[i]) {
        for (size_t j = 0; j < chunk->size(); ++j) {
          trace_writer_->AppendTraceEvent(chunk->GetEventAt(j));
        }
      }
      if (i == chunk_index_) break;
    }
  }
  trace_writer_->Flush();
  // This resets the trace buffer.
  is_empty_ = true;
  return true;
}
References chunk_index_, chunks_, is_empty_, mutex_, NextChunkIndex(), and trace_writer_.
GetEventByHandle()
TraceObject * v8::platform::tracing::TraceBufferRingBuffer::GetEventByHandle (uint64_t handle) [override], [virtual]
Implements v8::platform::tracing::TraceBuffer.
Definition at line 37 of file trace-buffer.cc.
                                                                    {
  base::MutexGuard guard(&mutex_);
  size_t chunk_index, event_index;
  uint32_t chunk_seq;
  ExtractHandle(handle, &chunk_index, &chunk_seq, &event_index);
  if (chunk_index >= chunks_.size()) return nullptr;
  auto& chunk = chunks_[chunk_index];
  if (!chunk || chunk->seq() != chunk_seq) return nullptr;
  return chunk->GetEventAt(event_index);
}
References chunks_, ExtractHandle(), v8::internal::handle(), and mutex_.
MakeHandle()
uint64_t v8::platform::tracing::TraceBufferRingBuffer::MakeHandle (size_t chunk_index, uint32_t chunk_seq, size_t event_index) const [private]
Definition at line 67 of file trace-buffer.cc.
                                                                     {
  return static_cast<uint64_t>(chunk_seq) * Capacity() +
         chunk_index * TraceBufferChunk::kChunkSize + event_index;
}
References Capacity(), and v8::platform::tracing::TraceBufferChunk::kChunkSize.
Referenced by AddTraceEvent().
NextChunkIndex()
size_t v8::platform::tracing::TraceBufferRingBuffer::NextChunkIndex (size_t index) const [private]
Definition at line 83 of file trace-buffer.cc.
                                                               {
  if (++index >= max_chunks_) index = 0;
  return index;
}
References v8::internal::index, and max_chunks_.
Referenced by AddTraceEvent(), and Flush().
Member Data Documentation
chunk_index_
size_t v8::platform::tracing::TraceBufferRingBuffer::chunk_index_ [private]
Definition at line 40 of file trace-buffer.h.
Referenced by AddTraceEvent(), and Flush().
chunks_
std::vector<std::unique_ptr<TraceBufferChunk> > v8::platform::tracing::TraceBufferRingBuffer::chunks_ [private]
Definition at line 39 of file trace-buffer.h.
Referenced by AddTraceEvent(), Flush(), GetEventByHandle(), and TraceBufferRingBuffer().
current_chunk_seq_
uint32_t v8::platform::tracing::TraceBufferRingBuffer::current_chunk_seq_ = 1 [private]
Definition at line 42 of file trace-buffer.h.
Referenced by AddTraceEvent().
is_empty_
bool v8::platform::tracing::TraceBufferRingBuffer::is_empty_ = true [private]
Definition at line 41 of file trace-buffer.h.
Referenced by AddTraceEvent(), and Flush().
max_chunks_
size_t v8::platform::tracing::TraceBufferRingBuffer::max_chunks_ [private]
Definition at line 37 of file trace-buffer.h.
Referenced by Capacity(), and NextChunkIndex().
mutex_
base::Mutex v8::platform::tracing::TraceBufferRingBuffer::mutex_ [mutable], [private]
Definition at line 36 of file trace-buffer.h.
Referenced by AddTraceEvent(), Flush(), and GetEventByHandle().
trace_writer_
std::unique_ptr<TraceWriter> v8::platform::tracing::TraceBufferRingBuffer::trace_writer_ [private]
Definition at line 38 of file trace-buffer.h.
Referenced by Flush(), and TraceBufferRingBuffer().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/libplatform/tracing/trace-buffer.h
/mnt/V8SourceCode/src/libplatform/tracing/trace-buffer.cc