v8::internal::maglev::LiveRangeAndNextUseProcessor Class Reference
#include <maglev-pre-regalloc-codegen-processors.h>
Classes
struct LoopUsedNodes
struct NodeUse
Public Member Functions
LiveRangeAndNextUseProcessor (MaglevCompilationInfo *compilation_info, Graph *graph, RegallocInfo *regalloc_info)
void PreProcessGraph (Graph *graph)
void PostProcessGraph (Graph *graph)
void PostProcessBasicBlock (BasicBlock *block)
BlockProcessResult PreProcessBasicBlock (BasicBlock *block)
void PostPhiProcessing ()
template<typename NodeT >
ProcessResult Process (NodeT *node, const ProcessingState &state)
template<typename NodeT >
void MarkInputUses (NodeT *node, const ProcessingState &state)
void MarkInputUses (Phi *node, const ProcessingState &state)
void MarkInputUses (JumpLoop *node, const ProcessingState &state)
void MarkInputUses (Jump *node, const ProcessingState &state)
void MarkInputUses (CheckpointedJump *node, const ProcessingState &state)
void MarkJumpInputUses (uint32_t use, BasicBlock *target, const ProcessingState &state)
Private Member Functions
LoopUsedNodes * GetCurrentLoopUsedNodes ()
void MarkUse (ValueNode *node, uint32_t use_id, InputLocation *input, LoopUsedNodes *loop_used_nodes)
template<typename DeoptInfoT >
void MarkCheckpointNodes (NodeBase *node, DeoptInfoT *deopt_info, LoopUsedNodes *loop_used_nodes, const ProcessingState &state)
Private Attributes
MaglevCompilationInfo * compilation_info_
RegallocInfo * regalloc_info_
std::vector< LoopUsedNodes > loop_used_nodes_
uint32_t next_node_id_ = kFirstValidNodeId
Detailed Description
Definition at line 147 of file maglev-pre-regalloc-codegen-processors.h.
Constructor & Destructor Documentation
LiveRangeAndNextUseProcessor()
v8::internal::maglev::LiveRangeAndNextUseProcessor::LiveRangeAndNextUseProcessor (MaglevCompilationInfo * compilation_info, Graph * graph, RegallocInfo * regalloc_info) [inline], [explicit]
Definition at line 149 of file maglev-pre-regalloc-codegen-processors.h.
      : compilation_info_(compilation_info), regalloc_info_(regalloc_info) {}
Member Function Documentation
GetCurrentLoopUsedNodes()
LoopUsedNodes* v8::internal::maglev::LiveRangeAndNextUseProcessor::GetCurrentLoopUsedNodes () [inline], [private]
Definition at line 313 of file maglev-pre-regalloc-codegen-processors.h.
                                           {
    if (loop_used_nodes_.empty()) return nullptr;
    return &loop_used_nodes_.back();
  }
References loop_used_nodes_.
Referenced by MarkInputUses(), MarkJumpInputUses(), and Process().
MarkCheckpointNodes()
template<typename DeoptInfoT >
void v8::internal::maglev::LiveRangeAndNextUseProcessor::MarkCheckpointNodes (NodeBase * node, DeoptInfoT * deopt_info, LoopUsedNodes * loop_used_nodes, const ProcessingState & state) [inline], [private]
Definition at line 351 of file maglev-pre-regalloc-codegen-processors.h.
                                                         {
    int use_id = node->id();
    if (!deopt_info->has_input_locations()) {
      size_t count = 0;
      deopt_info->ForEachInput([&](ValueNode*) { count++; });
      deopt_info->InitializeInputLocations(compilation_info_->zone(), count);
    }
    InputLocation* input = deopt_info->input_locations();
    deopt_info->ForEachInput([&](ValueNode* node) {
      MarkUse(node, use_id, input, loop_used_nodes);
      input++;
    });
  }
References compilation_info_, v8::internal::maglev::NodeBase::id(), MarkUse(), and v8::internal::maglev::MaglevCompilationInfo::zone().
Referenced by MarkInputUses().
MarkInputUses() [1/5]
void v8::internal::maglev::LiveRangeAndNextUseProcessor::MarkInputUses (CheckpointedJump * node, const ProcessingState & state) [inline]
Definition at line 274 of file maglev-pre-regalloc-codegen-processors.h.
                                                                           {
    MarkJumpInputUses(node->id(), node->target(), state);
  }
References MarkJumpInputUses().
MarkInputUses() [2/5]
void v8::internal::maglev::LiveRangeAndNextUseProcessor::MarkInputUses (Jump * node, const ProcessingState & state) [inline]
Definition at line 271 of file maglev-pre-regalloc-codegen-processors.h.
                                                               {
    MarkJumpInputUses(node->id(), node->target(), state);
  }
References MarkJumpInputUses().
MarkInputUses() [3/5]
void v8::internal::maglev::LiveRangeAndNextUseProcessor::MarkInputUses (JumpLoop * node, const ProcessingState & state) [inline]
Definition at line 209 of file maglev-pre-regalloc-codegen-processors.h.
                                                                   {
    int predecessor_id = state.block()->predecessor_id();
    BasicBlock* target = node->target();
    uint32_t use = node->id();
    DCHECK(!loop_used_nodes_.empty());
    LoopUsedNodes loop_used_nodes = std::move(loop_used_nodes_.back());
    loop_used_nodes_.pop_back();
    DCHECK_EQ(loop_used_nodes.header, target);
    LoopUsedNodes* outer_loop_used_nodes = GetCurrentLoopUsedNodes();
    if (target->has_phi()) {
      for (Phi* phi : *target->phis()) {
        DCHECK(phi->is_used());
        ValueNode* input = phi->input(predecessor_id).node();
        MarkUse(input, use, &phi->input(predecessor_id), outer_loop_used_nodes);
      }
    }
    DCHECK_EQ(loop_used_nodes.header, target);
    if (!loop_used_nodes.used_nodes.empty()) {
      // Try to avoid unnecessary reloads or spills across the back-edge based
      // on use positions and calls inside the loop.
      RegallocInfo::RegallocLoopInfo& loop_info =
          regalloc_info_->loop_info_
              .emplace(loop_used_nodes.header->id(), compilation_info_->zone())
              .first->second;
      for (auto p : loop_used_nodes.used_nodes) {
        // If the node is used before the first call and after the last call,
        // keep it in a register across the back-edge.
        if (p.second.first_register_use != kInvalidNodeId &&
            (loop_used_nodes.first_call == kInvalidNodeId ||
             (p.second.first_register_use <= loop_used_nodes.first_call &&
              p.second.last_register_use > loop_used_nodes.last_call))) {
          loop_info.reload_hints_.Add(p.first, compilation_info_->zone());
        }
        // If the node is not used, or used after the first call and before the
        // last call, keep it spilled across the back-edge.
        if (p.second.first_register_use == kInvalidNodeId ||
            (loop_used_nodes.first_call != kInvalidNodeId &&
             p.second.first_register_use > loop_used_nodes.first_call &&
             p.second.last_register_use <= loop_used_nodes.last_call)) {
          loop_info.spill_hints_.Add(p.first, compilation_info_->zone());
        }
      }
      // Uses of nodes in this loop may need to propagate to an outer loop, so
      // that they're lifetime is extended there too.
      // TODO(leszeks): We only need to extend the lifetime in one outermost
      // loop, allow nodes to be "moved" between lifetime extensions.
      base::Vector<Input> used_node_inputs =
          compilation_info_->zone()->AllocateVector<Input>(
              loop_used_nodes.used_nodes.size());
      int i = 0;
      for (auto& [used_node, info] : loop_used_nodes.used_nodes) {
        Input* input = new (&used_node_inputs[i++]) Input(used_node);
        MarkUse(used_node, use, input, outer_loop_used_nodes);
      }
      node->set_used_nodes(used_node_inputs);
    }
  }
References v8::internal::Zone::AllocateVector(), v8::internal::maglev::ProcessingState::block(), compilation_info_, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::maglev::LiveRangeAndNextUseProcessor::LoopUsedNodes::first_call, GetCurrentLoopUsedNodes(), v8::internal::maglev::BasicBlock::has_phi(), v8::internal::maglev::LiveRangeAndNextUseProcessor::LoopUsedNodes::header, v8::internal::maglev::BasicBlock::id(), v8::internal::maglev::NodeBase::input(), v8::internal::maglev::kInvalidNodeId, v8::internal::maglev::LiveRangeAndNextUseProcessor::LoopUsedNodes::last_call, v8::internal::maglev::RegallocInfo::loop_info_, loop_used_nodes_, MarkUse(), v8::internal::maglev::Input::node(), v8::internal::maglev::BasicBlock::phis(), v8::internal::maglev::BasicBlock::predecessor_id(), regalloc_info_, v8::internal::maglev::RegallocInfo::RegallocLoopInfo::reload_hints_, v8::internal::maglev::JumpLoop::set_used_nodes(), v8::internal::maglev::RegallocInfo::RegallocLoopInfo::spill_hints_, use(), v8::internal::maglev::LiveRangeAndNextUseProcessor::LoopUsedNodes::used_nodes, and v8::internal::maglev::MaglevCompilationInfo::zone().
MarkInputUses() [4/5]
template<typename NodeT >
void v8::internal::maglev::LiveRangeAndNextUseProcessor::MarkInputUses (NodeT * node, const ProcessingState & state) [inline]
Definition at line 183 of file maglev-pre-regalloc-codegen-processors.h.
                                                                {
    LoopUsedNodes* loop_used_nodes = GetCurrentLoopUsedNodes();
    // Mark input uses in the same order as inputs are assigned in the register
    // allocator (see StraightForwardRegisterAllocator::AssignInputs).
    node->ForAllInputsInRegallocAssignmentOrder(
        [&](NodeBase::InputAllocationPolicy, Input* input) {
          MarkUse(input->node(), node->id(), input, loop_used_nodes);
        });
    if constexpr (NodeT::kProperties.can_eager_deopt()) {
      MarkCheckpointNodes(node, node->eager_deopt_info(), loop_used_nodes,
                          state);
    }
    if constexpr (NodeT::kProperties.can_lazy_deopt()) {
      MarkCheckpointNodes(node, node->lazy_deopt_info(), loop_used_nodes,
                          state);
    }
  }
References GetCurrentLoopUsedNodes(), MarkCheckpointNodes(), MarkUse(), and v8::internal::maglev::Input::node().
Referenced by Process().
MarkInputUses() [5/5]
void v8::internal::maglev::LiveRangeAndNextUseProcessor::MarkInputUses (Phi * node, const ProcessingState & state) [inline]
Definition at line 201 of file maglev-pre-regalloc-codegen-processors.h.
                                                              {
    // Don't mark Phi uses when visiting the node, because of loop phis.
    // Instead, they'll be visited while processing Jump/JumpLoop.
  }
MarkJumpInputUses()
void v8::internal::maglev::LiveRangeAndNextUseProcessor::MarkJumpInputUses (uint32_t use, BasicBlock * target, const ProcessingState & state) [inline]
Definition at line 277 of file maglev-pre-regalloc-codegen-processors.h.
                                                       {
    int i = state.block()->predecessor_id();
    if (!target->has_phi()) return;
    LoopUsedNodes* loop_used_nodes = GetCurrentLoopUsedNodes();
    Phi::List& phis = *target->phis();
    for (auto it = phis.begin(); it != phis.end();) {
      Phi* phi = *it;
      if (!phi->is_used()) {
        // Skip unused phis -- we're processing phis out of order with the dead
        // node sweeping processor, so we will still observe unused phis here.
        // We can eagerly remove them while we're at it so that the dead node
        // sweeping processor doesn't have to revisit them.
        it = phis.RemoveAt(it);
      } else {
        ValueNode* input = phi->input(i).node();
        MarkUse(input, use, &phi->input(i), loop_used_nodes);
        ++it;
      }
    }
  }
References v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::begin(), v8::internal::maglev::ProcessingState::block(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::end(), GetCurrentLoopUsedNodes(), v8::internal::maglev::BasicBlock::has_phi(), MarkUse(), v8::internal::maglev::BasicBlock::phis(), v8::internal::maglev::BasicBlock::predecessor_id(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::RemoveAt(), and use().
Referenced by MarkInputUses().
MarkUse()
void v8::internal::maglev::LiveRangeAndNextUseProcessor::MarkUse (ValueNode * node, uint32_t use_id, InputLocation * input, LoopUsedNodes * loop_used_nodes) [inline], [private]
Definition at line 318 of file maglev-pre-regalloc-codegen-processors.h.
                                               {
    DCHECK(!node->Is<Identity>());
    node->record_next_use(use_id, input);
    // If we are in a loop, loop_used_nodes is non-null. In this case, check if
    // the incoming node is from outside the loop, and make sure to extend its
    // lifetime to the loop end if yes.
    if (loop_used_nodes) {
      // If the node's id is smaller than the smallest id inside the loop, then
      // it must have been created before the loop. This means that it's alive
      // on loop entry, and therefore has to be alive across the loop back edge
      // too.
      if (node->id() < loop_used_nodes->header->first_id()) {
        auto [it, info] = loop_used_nodes->used_nodes.emplace(
            node, NodeUse{kInvalidNodeId, kInvalidNodeId});
        if (input->operand().IsUnallocated()) {
          const auto& operand =
              compiler::UnallocatedOperand::cast(input->operand());
          if (operand.HasRegisterPolicy() || operand.HasFixedRegisterPolicy() ||
              operand.HasFixedFPRegisterPolicy()) {
            if (it->second.first_register_use == kInvalidNodeId) {
              it->second.first_register_use = use_id;
            }
            it->second.last_register_use = use_id;
          }
        }
      }
    }
  }
References v8::internal::DCHECK(), v8::internal::maglev::BasicBlock::first_id(), v8::internal::maglev::LiveRangeAndNextUseProcessor::LoopUsedNodes::header, v8::internal::maglev::NodeBase::id(), v8::internal::maglev::NodeBase::Is(), v8::internal::maglev::kInvalidNodeId, v8::internal::maglev::ValueLocation::operand(), v8::internal::maglev::ValueNode::record_next_use(), and v8::internal::maglev::LiveRangeAndNextUseProcessor::LoopUsedNodes::used_nodes.
Referenced by MarkCheckpointNodes(), MarkInputUses(), and MarkJumpInputUses().
PostPhiProcessing()
void v8::internal::maglev::LiveRangeAndNextUseProcessor::PostPhiProcessing () [inline]
Definition at line 165 of file maglev-pre-regalloc-codegen-processors.h.
{}
PostProcessBasicBlock()
void v8::internal::maglev::LiveRangeAndNextUseProcessor::PostProcessBasicBlock (BasicBlock * block) [inline]
Definition at line 156 of file maglev-pre-regalloc-codegen-processors.h.
{}
PostProcessGraph()
void v8::internal::maglev::LiveRangeAndNextUseProcessor::PostProcessGraph (Graph * graph) [inline]
Definition at line 155 of file maglev-pre-regalloc-codegen-processors.h.
{ DCHECK(loop_used_nodes_.empty()); }
References v8::internal::DCHECK(), and loop_used_nodes_.
PreProcessBasicBlock()
BlockProcessResult v8::internal::maglev::LiveRangeAndNextUseProcessor::PreProcessBasicBlock (BasicBlock * block) [inline]
Definition at line 157 of file maglev-pre-regalloc-codegen-processors.h.
                                                             {
    if (!block->has_state()) return BlockProcessResult::kContinue;
    if (block->state()->is_loop()) {
      loop_used_nodes_.push_back(
          LoopUsedNodes{{}, kInvalidNodeId, kInvalidNodeId, block});
    }
    return BlockProcessResult::kContinue;
  }
References v8::internal::maglev::BasicBlock::has_state(), v8::internal::maglev::MergePointInterpreterFrameState::is_loop(), v8::internal::maglev::kContinue, v8::internal::maglev::kInvalidNodeId, loop_used_nodes_, and v8::internal::maglev::BasicBlock::state().
PreProcessGraph()
void v8::internal::maglev::LiveRangeAndNextUseProcessor::PreProcessGraph (Graph * graph) [inline]
Definition at line 154 of file maglev-pre-regalloc-codegen-processors.h.
{}
Process()
template<typename NodeT >
ProcessResult v8::internal::maglev::LiveRangeAndNextUseProcessor::Process (NodeT * node, const ProcessingState & state) [inline]
Definition at line 168 of file maglev-pre-regalloc-codegen-processors.h.
                                                                   {
    node->set_id(next_node_id_++);
    LoopUsedNodes* loop_used_nodes = GetCurrentLoopUsedNodes();
    if (loop_used_nodes && node->properties().is_call() &&
        loop_used_nodes->header->has_state()) {
      if (loop_used_nodes->first_call == kInvalidNodeId) {
        loop_used_nodes->first_call = node->id();
      }
      loop_used_nodes->last_call = node->id();
    }
    MarkInputUses(node, state);
    return ProcessResult::kContinue;
  }
References v8::internal::maglev::LiveRangeAndNextUseProcessor::LoopUsedNodes::first_call, GetCurrentLoopUsedNodes(), v8::internal::maglev::BasicBlock::has_state(), v8::internal::maglev::LiveRangeAndNextUseProcessor::LoopUsedNodes::header, v8::internal::maglev::OpProperties::is_call(), v8::internal::maglev::kContinue, v8::internal::maglev::kInvalidNodeId, v8::internal::maglev::LiveRangeAndNextUseProcessor::LoopUsedNodes::last_call, MarkInputUses(), next_node_id_, and v8::internal::maglev::NodeTMixin< Base, Derived >::properties().
Member Data Documentation
compilation_info_
MaglevCompilationInfo* v8::internal::maglev::LiveRangeAndNextUseProcessor::compilation_info_ [private]
Definition at line 367 of file maglev-pre-regalloc-codegen-processors.h.
Referenced by MarkCheckpointNodes(), and MarkInputUses().
loop_used_nodes_
std::vector<LoopUsedNodes> v8::internal::maglev::LiveRangeAndNextUseProcessor::loop_used_nodes_ [private]
Definition at line 369 of file maglev-pre-regalloc-codegen-processors.h.
Referenced by GetCurrentLoopUsedNodes(), MarkInputUses(), PostProcessGraph(), and PreProcessBasicBlock().
next_node_id_
uint32_t v8::internal::maglev::LiveRangeAndNextUseProcessor::next_node_id_ = kFirstValidNodeId [private]
Definition at line 370 of file maglev-pre-regalloc-codegen-processors.h.
Referenced by Process().
regalloc_info_
RegallocInfo* v8::internal::maglev::LiveRangeAndNextUseProcessor::regalloc_info_ [private]
Definition at line 368 of file maglev-pre-regalloc-codegen-processors.h.
Referenced by MarkInputUses().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-pre-regalloc-codegen-processors.h