v8::internal::compiler::GraphC1Visualizer Class Reference
Classes
class Tag
Public Member Functions
GraphC1Visualizer (std::ostream &os, Zone *zone)
GraphC1Visualizer (const GraphC1Visualizer &)=delete
GraphC1Visualizer & operator= (const GraphC1Visualizer &)=delete
void PrintCompilation (const OptimizedCompilationInfo *info)
void PrintSchedule (const char *phase, const Schedule *schedule, const SourcePositionTable *positions, const InstructionSequence *instructions)
void PrintLiveRanges (const char *phase, const RegisterAllocationData *data)
Zone * zone () const
Private Member Functions
void PrintIndent ()
void PrintStringProperty (const char *name, const char *value)
void PrintLongProperty (const char *name, int64_t value)
void PrintIntProperty (const char *name, int value)
void PrintBlockProperty (const char *name, int rpo_number)
void PrintNodeId (Node *n)
void PrintNode (Node *n)
void PrintInputs (Node *n)
template<typename InputIterator >
void PrintInputs (InputIterator *i, int count, const char *prefix)
void PrintType (Node *node)
void PrintLiveRange (const LiveRange *range, const char *type, int vreg)
void PrintLiveRangeChain (const TopLevelLiveRange *range, const char *type)
Private Attributes
std::ostream & os_
int indent_
Zone * zone_
Detailed Description
Definition at line 521 of file turbofan-graph-visualizer.cc.
Constructor & Destructor Documentation
GraphC1Visualizer() [1/2]
v8::internal::compiler::GraphC1Visualizer::GraphC1Visualizer (std::ostream & os, Zone * zone)
Definition at line 583 of file turbofan-graph-visualizer.cc.
    : os_(os), indent_(0), zone_(zone) {}
GraphC1Visualizer() [2/2]
v8::internal::compiler::GraphC1Visualizer::GraphC1Visualizer (const GraphC1Visualizer &) [delete]
Member Function Documentation
operator=()
GraphC1Visualizer& v8::internal::compiler::GraphC1Visualizer::operator= (const GraphC1Visualizer &) [delete]
PrintBlockProperty()
void v8::internal::compiler::GraphC1Visualizer::PrintBlockProperty (const char * name, int rpo_number) [private]
Definition at line 597 of file turbofan-graph-visualizer.cc.
                                                                           {
  PrintIndent();
  os_ << name << " \"B" << rpo_number << "\"\n";
}
References v8::internal::name, os_, and PrintIndent().
Referenced by PrintSchedule().
PrintCompilation()
void v8::internal::compiler::GraphC1Visualizer::PrintCompilation (const OptimizedCompilationInfo * info)
Definition at line 607 of file turbofan-graph-visualizer.cc.
                                                                             {
  Tag tag(this, "compilation");
  std::unique_ptr<char[]> name = info->GetDebugName();
  if (info->IsOptimizing()) {
    PrintStringProperty("name", name.get());
    PrintIndent();
    os_ << "method \"" << name.get() << ":" << info->optimization_id()
        << "\"\n";
  } else {
    PrintStringProperty("name", name.get());
    PrintStringProperty("method", "stub");
  }
  PrintLongProperty("date",
                    V8::GetCurrentPlatform()->CurrentClockTimeMilliseconds());
}
References v8::internal::V8::GetCurrentPlatform(), v8::internal::OptimizedCompilationInfo::GetDebugName(), v8::internal::OptimizedCompilationInfo::IsOptimizing(), v8::internal::name, v8::internal::OptimizedCompilationInfo::optimization_id(), os_, PrintIndent(), PrintLongProperty(), and PrintStringProperty().
Referenced by v8::internal::compiler::operator<<().
PrintIndent()
void v8::internal::compiler::GraphC1Visualizer::PrintIndent () [private]
Definition at line 577 of file turbofan-graph-visualizer.cc.
                                    {
  for (int i = 0; i < indent_; i++) {
    os_ << " ";
  }
}
References indent_, and os_.
Referenced by PrintBlockProperty(), PrintCompilation(), PrintIntProperty(), PrintLiveRange(), PrintLongProperty(), PrintSchedule(), PrintStringProperty(), v8::internal::compiler::GraphC1Visualizer::Tag::Tag(), and v8::internal::compiler::GraphC1Visualizer::Tag::~Tag().
PrintInputs() [1/2]
template<typename InputIterator >
void v8::internal::compiler::GraphC1Visualizer::PrintInputs (InputIterator * i, int count, const char * prefix) [private]
Definition at line 632 of file turbofan-graph-visualizer.cc.
                                                        {
  if (count > 0) {
    os_ << prefix;
  }
  while (count > 0) {
    os_ << " ";
    PrintNodeId(**i);
    ++(*i);
    count--;
  }
}
References os_, and PrintNodeId().
PrintInputs() [2/2]
void v8::internal::compiler::GraphC1Visualizer::PrintInputs (Node * n) [private]
Definition at line 645 of file turbofan-graph-visualizer.cc.
                                              {
  auto i = node->inputs().begin();
  PrintInputs(&i, node->op()->ValueInputCount(), " ");
  PrintInputs(&i, OperatorProperties::GetContextInputCount(node->op()),
              " Ctx:");
  PrintInputs(&i, OperatorProperties::GetFrameStateInputCount(node->op()),
              " FS:");
  PrintInputs(&i, node->op()->EffectInputCount(), " Eff:");
  PrintInputs(&i, node->op()->ControlInputCount(), " Ctrl:");
}
References v8::internal::compiler::Operator::ControlInputCount(), v8::internal::compiler::Operator::EffectInputCount(), v8::internal::compiler::OperatorProperties::GetContextInputCount(), v8::internal::compiler::OperatorProperties::GetFrameStateInputCount(), v8::internal::compiler::Node::inputs(), v8::internal::compiler::Node::op(), and v8::internal::compiler::Operator::ValueInputCount().
Referenced by PrintNode(), and PrintSchedule().
PrintIntProperty()
void v8::internal::compiler::GraphC1Visualizer::PrintIntProperty (const char * name, int value) [private]
Definition at line 602 of file turbofan-graph-visualizer.cc.
                                                                    {
  PrintIndent();
  os_ << name << " " << value << "\n";
}
References v8::internal::name, os_, PrintIndent(), and v8::internal::value.
Referenced by PrintSchedule().
PrintLiveRange()
void v8::internal::compiler::GraphC1Visualizer::PrintLiveRange (const LiveRange * range, const char * type, int vreg) [private]
Definition at line 829 of file turbofan-graph-visualizer.cc.
                                                 {
  if (range != nullptr && !range->IsEmpty()) {
    PrintIndent();
    os_ << vreg << ":" << range->relative_id() << " " << type;
    if (range->HasRegisterAssigned()) {
      AllocatedOperand op = AllocatedOperand::cast(range->GetAssignedOperand());
      if (op.IsRegister()) {
        os_ << " \"" << Register::from_code(op.register_code()) << "\"";
      } else if (op.IsDoubleRegister()) {
        os_ << " \"" << DoubleRegister::from_code(op.register_code()) << "\"";
      } else if (op.IsFloatRegister()) {
        os_ << " \"" << FloatRegister::from_code(op.register_code()) << "\"";
#if defined(V8_TARGET_ARCH_X64)
      } else if (op.IsSimd256Register()) {
        os_ << " \"" << Simd256Register::from_code(op.register_code()) << "\"";
#endif
      } else {
        DCHECK(op.IsSimd128Register());
        os_ << " \"" << Simd128Register::from_code(op.register_code()) << "\"";
      }
    } else if (range->spilled()) {
      const TopLevelLiveRange* top = range->TopLevel();
      int index = -1;
      if (top->HasSpillRange()) {
        index = kMaxInt; // This hasn't been set yet.
      } else if (top->GetSpillOperand()->IsConstant()) {
        os_ << " \"const(nostack):"
            << ConstantOperand::cast(top->GetSpillOperand())->virtual_register()
            << "\"";
      } else {
        index = AllocatedOperand::cast(top->GetSpillOperand())->index();
        if (IsFloatingPoint(top->representation())) {
          os_ << " \"fp_stack:" << index << "\"";
        } else {
          os_ << " \"stack:" << index << "\"";
        }
      }
    }
    const TopLevelLiveRange* parent = range->TopLevel();
    os_ << " " << parent->vreg() << ":" << parent->relative_id();
    // TODO(herhut) Find something useful to print for the hint field
    if (parent->get_bundle() != nullptr) {
      os_ << " B" << parent->get_bundle()->id();
    } else {
      os_ << " unknown";
    }
    for (const UseInterval& interval : range->intervals()) {
      os_ << " [" << interval.start().value() << ", " << interval.end().value()
          << "[";
    }
    for (const UsePosition* pos : range->positions()) {
      if (pos->RegisterIsBeneficial() || v8_flags.trace_all_uses) {
        os_ << " " << pos->pos().value() << " M";
      }
    }
    os_ << " \"\"\n";
  }
}
References v8::internal::compiler::LocationOperand::cast(), v8::internal::DCHECK(), v8::internal::Register::from_code(), v8::internal::YMMRegister::from_code(), v8::internal::RegisterBase< DoubleRegister, kDoubleAfterLast >::from_code(), v8::internal::RegisterBase< SwVfpRegister, kSwVfpAfterLast >::from_code(), v8::internal::RegisterBase< Simd128Register, kSimd128AfterLast >::from_code(), v8::internal::compiler::TopLevelLiveRange::get_bundle(), v8::internal::compiler::LiveRange::GetAssignedOperand(), v8::internal::compiler::TopLevelLiveRange::GetSpillOperand(), v8::internal::compiler::LiveRange::HasRegisterAssigned(), v8::internal::compiler::TopLevelLiveRange::HasSpillRange(), v8::internal::compiler::LiveRangeBundle::id(), v8::internal::compiler::LocationOperand::index(), v8::internal::index, v8::internal::compiler::LiveRange::intervals(), v8::internal::compiler::InstructionOperand::IsDoubleRegister(), v8::internal::compiler::LiveRange::IsEmpty(), v8::internal::IsFloatingPoint(), v8::internal::compiler::InstructionOperand::IsFloatRegister(), v8::internal::compiler::InstructionOperand::IsRegister(), v8::internal::compiler::InstructionOperand::IsSimd128Register(), v8::internal::compiler::InstructionOperand::IsSimd256Register(), v8::internal::kMaxInt, os_, v8::internal::compiler::LiveRange::positions(), PrintIndent(), v8::internal::compiler::LocationOperand::register_code(), v8::internal::compiler::LiveRange::relative_id(), v8::internal::compiler::LiveRange::representation(), v8::internal::compiler::LiveRange::spilled(), v8::internal::compiler::LiveRange::TopLevel(), v8::internal::tracing::type, v8::internal::v8_flags, and v8::internal::compiler::TopLevelLiveRange::vreg().
Referenced by PrintLiveRangeChain().
PrintLiveRangeChain()
void v8::internal::compiler::GraphC1Visualizer::PrintLiveRangeChain (const TopLevelLiveRange * range, const char * type) [private]
Definition at line 819 of file turbofan-graph-visualizer.cc.
                                                              {
  if (range == nullptr || range->IsEmpty()) return;
  int vreg = range->vreg();
  for (const LiveRange* child = range; child != nullptr;
       child = child->next()) {
    PrintLiveRange(child, type, vreg);
  }
}
References v8::internal::compiler::LiveRange::IsEmpty(), v8::internal::compiler::LiveRange::next(), PrintLiveRange(), v8::internal::tracing::type, and v8::internal::compiler::TopLevelLiveRange::vreg().
Referenced by PrintLiveRanges().
PrintLiveRanges()
void v8::internal::compiler::GraphC1Visualizer::PrintLiveRanges (const char * phase, const RegisterAllocationData * data)
Definition at line 801 of file turbofan-graph-visualizer.cc.
                                                                            {
  Tag tag(this, "intervals");
  PrintStringProperty("name", phase);
  for (const TopLevelLiveRange* range : data->fixed_double_live_ranges()) {
    PrintLiveRangeChain(range, "fixed");
  }
  for (const TopLevelLiveRange* range : data->fixed_live_ranges()) {
    PrintLiveRangeChain(range, "fixed");
  }
  for (const TopLevelLiveRange* range : data->live_ranges()) {
    PrintLiveRangeChain(range, "object");
  }
}
References v8::internal::compiler::RegisterAllocationData::fixed_double_live_ranges(), v8::internal::compiler::RegisterAllocationData::fixed_live_ranges(), v8::internal::compiler::RegisterAllocationData::live_ranges(), PrintLiveRangeChain(), and PrintStringProperty().
Referenced by v8::internal::compiler::operator<<().
PrintLongProperty()
void v8::internal::compiler::GraphC1Visualizer::PrintLongProperty (const char * name, int64_t value) [private]
Definition at line 592 of file turbofan-graph-visualizer.cc.
                                                                         {
  PrintIndent();
  os_ << name << " " << static_cast<int>(value / 1000) << "\n";
}
References v8::internal::name, os_, PrintIndent(), and v8::internal::value.
Referenced by PrintCompilation().
PrintNode()
void v8::internal::compiler::GraphC1Visualizer::PrintNode (Node * n) [private]
Definition at line 625 of file turbofan-graph-visualizer.cc.
                                         {
  PrintNodeId(n);
  os_ << " " << *n->op() << " ";
  PrintInputs(n);
}
References v8::internal::compiler::Node::op(), os_, PrintInputs(), and PrintNodeId().
Referenced by PrintSchedule().
PrintNodeId()
void v8::internal::compiler::GraphC1Visualizer::PrintNodeId (Node * n) [private]
Definition at line 623 of file turbofan-graph-visualizer.cc.
{ os_ << "n" << SafeId(n); }
References os_, and v8::internal::compiler::SafeId().
Referenced by PrintInputs(), PrintNode(), and PrintSchedule().
PrintSchedule()
void v8::internal::compiler::GraphC1Visualizer::PrintSchedule (const char * phase, const Schedule * schedule, const SourcePositionTable * positions, const InstructionSequence * instructions)
Definition at line 663 of file turbofan-graph-visualizer.cc.
                                                                               {
  Tag tag(this, "cfg");
  PrintStringProperty("name", phase);
  const BasicBlockVector* rpo = schedule->rpo_order();
  for (size_t i = 0; i < rpo->size(); i++) {
    BasicBlock* current = (*rpo)[i];
    Tag block_tag(this, "block");
    PrintBlockProperty("name", current->rpo_number());
    PrintIntProperty("from_bci", -1);
    PrintIntProperty("to_bci", -1);
    PrintIndent();
    os_ << "predecessors";
    for (BasicBlock* predecessor : current->predecessors()) {
      os_ << " \"B" << predecessor->rpo_number() << "\"";
    }
    os_ << "\n";
    PrintIndent();
    os_ << "successors";
    for (BasicBlock* successor : current->successors()) {
      os_ << " \"B" << successor->rpo_number() << "\"";
    }
    os_ << "\n";
    PrintIndent();
    os_ << "xhandlers\n";
    PrintIndent();
    os_ << "flags\n";
    if (current->dominator() != nullptr) {
      PrintBlockProperty("dominator", current->dominator()->rpo_number());
    }
    PrintIntProperty("loop_depth", current->loop_depth());
    const InstructionBlock* instruction_block =
        instructions->InstructionBlockAt(
            RpoNumber::FromInt(current->rpo_number()));
    if (instruction_block->code_start() >= 0) {
      int first_index = instruction_block->first_instruction_index();
      int last_index = instruction_block->last_instruction_index();
      PrintIntProperty(
          "first_lir_id",
          LifetimePosition::GapFromInstructionIndex(first_index).value());
      PrintIntProperty(
          "last_lir_id",
          LifetimePosition::InstructionFromInstructionIndex(last_index)
              .value());
    }
    {
      Tag states_tag(this, "states");
      Tag locals_tag(this, "locals");
      int total = 0;
      for (BasicBlock::const_iterator it = current->begin();
           it != current->end(); ++it) {
        if ((*it)->opcode() == IrOpcode::kPhi) total++;
      }
      PrintIntProperty("size", total);
      PrintStringProperty("method", "None");
      int index = 0;
      for (BasicBlock::const_iterator it = current->begin();
           it != current->end(); ++it) {
        if ((*it)->opcode() != IrOpcode::kPhi) continue;
        PrintIndent();
        os_ << index << " ";
        PrintNodeId(*it);
        os_ << " [";
        PrintInputs(*it);
        os_ << "]\n";
        index++;
      }
    }
    {
      Tag HIR_tag(this, "HIR");
      for (BasicBlock::const_iterator it = current->begin();
           it != current->end(); ++it) {
        Node* node = *it;
        if (node->opcode() == IrOpcode::kPhi) continue;
        int uses = node->UseCount();
        PrintIndent();
        os_ << "0 " << uses << " ";
        PrintNode(node);
        if (v8_flags.trace_turbo_types) {
          os_ << " ";
          PrintType(node);
        }
        if (positions != nullptr) {
          SourcePosition position = positions->GetSourcePosition(node);
          if (position.IsKnown()) {
            os_ << " pos:";
            if (position.isInlined()) {
              os_ << "inlining(" << position.InliningId() << "),";
            }
            os_ << position.ScriptOffset();
          }
        }
        os_ << " <|@\n";
      }
      BasicBlock::Control control = current->control();
      if (control != BasicBlock::kNone) {
        PrintIndent();
        os_ << "0 0 ";
        if (current->control_input() != nullptr) {
          PrintNode(current->control_input());
        } else {
          os_ << -1 - current->rpo_number() << " Goto";
        }
        os_ << " ->";
        for (BasicBlock* successor : current->successors()) {
          os_ << " B" << successor->rpo_number();
        }
        if (v8_flags.trace_turbo_types && current->control_input() != nullptr) {
          os_ << " ";
          PrintType(current->control_input());
        }
        os_ << " <|@\n";
      }
    }
    if (instructions != nullptr) {
      Tag LIR_tag(this, "LIR");
      for (int j = instruction_block->first_instruction_index();
           j <= instruction_block->last_instruction_index(); j++) {
        PrintIndent();
        os_ << j << " " << *instructions->InstructionAt(j) << " <|@\n";
      }
    }
  }
}
References v8::internal::compiler::BasicBlock::begin(), v8::internal::compiler::InstructionBlock::code_start(), v8::internal::compiler::BasicBlock::control(), v8::internal::compiler::BasicBlock::control_input(), v8::internal::compiler::BasicBlock::dominator(), v8::internal::compiler::BasicBlock::end(), v8::internal::compiler::InstructionBlock::first_instruction_index(), v8::internal::compiler::RpoNumber::FromInt(), v8::internal::compiler::LifetimePosition::GapFromInstructionIndex(), v8::internal::compiler::SourcePositionTable::GetSourcePosition(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::SourcePosition::InliningId(), v8::internal::compiler::InstructionSequence::InstructionAt(), v8::internal::compiler::InstructionSequence::InstructionBlockAt(), v8::internal::compiler::LifetimePosition::InstructionFromInstructionIndex(), v8::internal::SourcePosition::isInlined(), v8::internal::SourcePosition::IsKnown(), v8::internal::compiler::BasicBlock::kNone, v8::internal::compiler::InstructionBlock::last_instruction_index(), v8::internal::compiler::BasicBlock::loop_depth(), v8::internal::compiler::Node::opcode(), os_, v8::internal::compiler::BasicBlock::predecessors(), PrintBlockProperty(), PrintIndent(), PrintInputs(), PrintIntProperty(), PrintNode(), PrintNodeId(), PrintStringProperty(), PrintType(), v8::internal::compiler::BasicBlock::rpo_number(), v8::internal::compiler::Schedule::rpo_order(), v8::internal::SourcePosition::ScriptOffset(), v8::internal::ZoneVector< T >::size(), v8::internal::compiler::BasicBlock::successors(), v8::internal::compiler::Node::UseCount(), v8::internal::v8_flags, and v8::internal::value.
Referenced by v8::internal::compiler::operator<<().
PrintStringProperty()
void v8::internal::compiler::GraphC1Visualizer::PrintStringProperty (const char * name, const char * value) [private]
Definition at line 586 of file turbofan-graph-visualizer.cc.
                                                               {
  PrintIndent();
  os_ << name << " \"" << value << "\"\n";
}
References v8::internal::name, os_, PrintIndent(), and v8::internal::value.
Referenced by PrintCompilation(), PrintLiveRanges(), and PrintSchedule().
PrintType()
void v8::internal::compiler::GraphC1Visualizer::PrintType (Node * node) [private]
Definition at line 656 of file turbofan-graph-visualizer.cc.
                                            {
  if (NodeProperties::IsTyped(node)) {
    Type type = NodeProperties::GetType(node);
    os_ << " type:" << type;
  }
}
References v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::IsTyped(), os_, and v8::internal::tracing::type.
Referenced by PrintSchedule().
zone()
Zone* v8::internal::compiler::GraphC1Visualizer::zone () const [inline]
Definition at line 532 of file turbofan-graph-visualizer.cc.
{ return zone_; }
References zone_.
Member Data Documentation
indent_
int v8::internal::compiler::GraphC1Visualizer::indent_ [private]
Definition at line 573 of file turbofan-graph-visualizer.cc.
Referenced by PrintIndent(), v8::internal::compiler::GraphC1Visualizer::Tag::Tag(), and v8::internal::compiler::GraphC1Visualizer::Tag::~Tag().
os_
std::ostream& v8::internal::compiler::GraphC1Visualizer::os_ [private]
Definition at line 572 of file turbofan-graph-visualizer.cc.
Referenced by PrintBlockProperty(), PrintCompilation(), PrintIndent(), PrintInputs(), PrintIntProperty(), PrintLiveRange(), PrintLongProperty(), PrintNode(), PrintNodeId(), PrintSchedule(), PrintStringProperty(), PrintType(), v8::internal::compiler::GraphC1Visualizer::Tag::Tag(), and v8::internal::compiler::GraphC1Visualizer::Tag::~Tag().
zone_
Zone* v8::internal::compiler::GraphC1Visualizer::zone_ [private]
Definition at line 574 of file turbofan-graph-visualizer.cc.
Referenced by zone().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turbofan-graph-visualizer.cc