v8::internal::wasm::AsyncCompileJob Class Reference
#include <module-compiler.h>
Classes
class CompilationStateCallback
class CompileStep
class CompileTask
class DecodeModule
class Fail
class FinishCompilation
class PrepareAndStartCompile
Public Member Functions
AsyncCompileJob (Isolate *isolate, WasmEnabledFeatures enabled_features, CompileTimeImports compile_imports, base::OwnedVector< const uint8_t > bytes, DirectHandle< Context > context, DirectHandle< NativeContext > incumbent_context, const char *api_method_name, std::shared_ptr< CompilationResultResolver > resolver, int compilation_id)
~AsyncCompileJob ()
void Start ()
std::shared_ptr< StreamingDecoder > CreateStreamingDecoder ()
void Abort ()
void CancelPendingForegroundTask ()
Isolate * isolate () const
DirectHandle< NativeContext > context () const
v8::metrics::Recorder::ContextId context_id () const
Private Types
enum UseExistingForegroundTask : bool { kUseExistingForegroundTask = true
, kAssertNoExistingForegroundTask = false
 }
Private Member Functions
V8_WARN_UNUSED_RESULT bool DecrementAndCheckFinisherCount ()
void CreateNativeModule (std::shared_ptr< const WasmModule > module, size_t code_size_estimate)
bool GetOrCreateNativeModule (std::shared_ptr< const WasmModule > module, size_t code_size_estimate)
void PrepareRuntimeObjects ()
void FinishCompile (bool is_after_cache_hit)
void Failed ()
void AsyncCompileSucceeded (DirectHandle< WasmModuleObject > result)
void FinishSuccessfully ()
void StartForegroundTask ()
void ExecuteForegroundTaskImmediately ()
void StartBackgroundTask ()
template<typename Step , UseExistingForegroundTask = kAssertNoExistingForegroundTask, typename... Args>
void DoSync (Args &&... args)
template<typename Step , typename... Args>
void DoImmediately (Args &&... args)
template<typename Step , typename... Args>
void DoAsync (Args &&... args)
template<typename Step , typename... Args>
void NextStep (Args &&... args)
Private Attributes
Isolate *const isolate_
const char *const api_method_name_
const WasmEnabledFeatures enabled_features_
WasmDetectedFeatures detected_features_
CompileTimeImports compile_imports_
base::TimeTicks start_time_
base::OwnedVector< const uint8_t > bytes_copy_
ModuleWireBytes wire_bytes_
IndirectHandle< NativeContext > native_context_
IndirectHandle< NativeContext > incumbent_context_
v8::metrics::Recorder::ContextId context_id_
v8::metrics::WasmModuleDecoded metrics_event_
const std::shared_ptr< CompilationResultResolver > resolver_
IndirectHandle< WasmModuleObject > module_object_
std::shared_ptr< NativeModule > native_module_
std::unique_ptr< CompileStep > step_
CancelableTaskManager background_task_manager_
std::shared_ptr< v8::TaskRunner > foreground_task_runner_
std::atomic< int32_t > outstanding_finishers_ {1}
CompileTask * pending_foreground_task_ = nullptr
std::shared_ptr< StreamingDecoder > stream_
const int compilation_id_
Friends
class AsyncStreamingProcessor
Detailed Description
Definition at line 112 of file module-compiler.h.
Member Enumeration Documentation
UseExistingForegroundTask
enum v8::internal::wasm::AsyncCompileJob::UseExistingForegroundTask : bool [private]
Enumerator
kUseExistingForegroundTask
kAssertNoExistingForegroundTask
Definition at line 192 of file module-compiler.h.
                                 : bool {
    kUseExistingForegroundTask = true,
    kAssertNoExistingForegroundTask = false
  };
Constructor & Destructor Documentation
AsyncCompileJob()
v8::internal::wasm::AsyncCompileJob::AsyncCompileJob (Isolate * isolate, WasmEnabledFeatures enabled_features, CompileTimeImports compile_imports, base::OwnedVector< const uint8_t > bytes, DirectHandle< Context > context, DirectHandle< NativeContext > incumbent_context, const char * api_method_name, std::shared_ptr< CompilationResultResolver > resolver, int compilation_id)
Definition at line 2445 of file module-compiler.cc.
    : isolate_(isolate),
      api_method_name_(api_method_name),
      enabled_features_(enabled_features),
      compile_imports_(std::move(compile_imports)),
      start_time_(base::TimeTicks::Now()),
      bytes_copy_(std::move(bytes)),
      wire_bytes_(bytes_copy_.as_vector()),
      resolver_(std::move(resolver)),
      compilation_id_(compilation_id) {
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.wasm.detailed"),
               "wasm.AsyncCompileJob");
  CHECK(v8_flags.wasm_async_compilation);
  CHECK(!v8_flags.jitless || v8_flags.wasm_jitless);
  v8::Isolate* v8_isolate = reinterpret_cast<v8::Isolate*>(isolate);
  v8::Platform* platform = V8::GetCurrentPlatform();
  foreground_task_runner_ = platform->GetForegroundTaskRunner(v8_isolate);
  native_context_ =
      isolate->global_handles()->Create(context->native_context());
  incumbent_context_ = isolate->global_handles()->Create(*incumbent_context);
  DCHECK(IsNativeContext(*native_context_));
  context_id_ = isolate->GetOrRegisterRecorderContextId(native_context_);
  metrics_event_.async = true;
}
References v8::metrics::WasmModuleDecoded::async, CHECK, context(), context_id_, v8::internal::GlobalHandles::Create(), v8::internal::DCHECK(), foreground_task_runner_, v8::internal::V8::GetCurrentPlatform(), v8::Platform::GetForegroundTaskRunner(), v8::internal::Isolate::GetOrRegisterRecorderContextId(), v8::internal::Isolate::global_handles(), incumbent_context_, isolate(), metrics_event_, native_context_, TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT0, and v8::internal::v8_flags.
 AsyncCompileJob()
v8::internal::wasm::AsyncCompileJob::~AsyncCompileJob ()
Definition at line 2672 of file module-compiler.cc.
                                  {
  // Note: This destructor always runs on the foreground thread of the isolate.
  background_task_manager_.CancelAndWait();
  // If initial compilation did not finish yet we can abort it.
  if (native_module_) {
    Impl(native_module_->compilation_state())
        ->CancelCompilation(CompilationStateImpl::kCancelInitialCompilation);
  }
  // Tell the streaming decoder that the AsyncCompileJob is not available
  // anymore.
  if (stream_) stream_->NotifyCompilationDiscarded();
  CancelPendingForegroundTask();
  isolate_->global_handles()->Destroy(native_context_.location());
  isolate_->global_handles()->Destroy(incumbent_context_.location());
  if (!module_object_.is_null()) {
    isolate_->global_handles()->Destroy(module_object_.location());
  }
}
References background_task_manager_, v8::internal::CancelableTaskManager::CancelAndWait(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::CancelCompilation(), CancelPendingForegroundTask(), v8::internal::GlobalHandles::Destroy(), v8::internal::Isolate::global_handles(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::Impl(), incumbent_context_, isolate_, module_object_, native_context_, native_module_, and stream_.
Member Function Documentation
Abort()
void v8::internal::wasm::AsyncCompileJob::Abort ()
Definition at line 2480 of file module-compiler.cc.
                            {
  // Removing this job will trigger the destructor, which will cancel all
  // compilation.
  GetWasmEngine()->RemoveCompileJob(this);
}
References v8::internal::wasm::GetWasmEngine(), and v8::internal::wasm::WasmEngine::RemoveCompileJob().
Referenced by v8::internal::wasm::AsyncStreamingProcessor::OnAbort().
AsyncCompileSucceeded()
void v8::internal::wasm::AsyncCompileJob::AsyncCompileSucceeded (DirectHandle< WasmModuleObject > result) [private]
CancelPendingForegroundTask()
void v8::internal::wasm::AsyncCompileJob::CancelPendingForegroundTask ()
Definition at line 2990 of file module-compiler.cc.
                                                  {
  if (!pending_foreground_task_) return;
  pending_foreground_task_->Cancel();
  pending_foreground_task_ = nullptr;
}
References v8::internal::wasm::AsyncCompileJob::CompileTask::Cancel(), and pending_foreground_task_.
Referenced by ~AsyncCompileJob().
context()
DirectHandle<NativeContext> v8::internal::wasm::AsyncCompileJob::context () const [inline]
Definition at line 133 of file module-compiler.h.
{ return native_context_; }
References native_context_.
Referenced by AsyncCompileJob().
context_id()
v8::metrics::Recorder::ContextId v8::internal::wasm::AsyncCompileJob::context_id () const [inline]
Definition at line 134 of file module-compiler.h.
{ return context_id_; }
References context_id_.
Referenced by v8::internal::wasm::AsyncCompileJob::DecodeModule::RunInBackground().
CreateNativeModule()
void v8::internal::wasm::AsyncCompileJob::CreateNativeModule (std::shared_ptr< const WasmModule > module, size_t code_size_estimate) [private]
Definition at line 2691 of file module-compiler.cc.
                                                                       {
  // Embedder usage count for declared shared memories.
  const bool has_shared_memory =
      std::any_of(module->memories.begin(), module->memories.end(),
                  [](auto& memory) { return memory.is_shared; });
  if (has_shared_memory) {
    isolate_->CountUsage(v8::Isolate::UseCounterFeature::kWasmSharedMemory);
  }
  // Create the module object and populate with compiled functions and
  // information needed at instantiation time.
  native_module_ = GetWasmEngine()->NewNativeModule(
      isolate_, enabled_features_, detected_features_,
      std::move(compile_imports_), std::move(module), code_size_estimate);
  native_module_->SetWireBytes(std::move(bytes_copy_));
  native_module_->compilation_state()->set_compilation_id(compilation_id_);
}
References v8::base::any_of(), bytes_copy_, compilation_id_, compile_imports_, v8::internal::Isolate::CountUsage(), detected_features_, enabled_features_, v8::internal::wasm::GetWasmEngine(), isolate_, native_module_, and v8::internal::wasm::WasmEngine::NewNativeModule().
Referenced by GetOrCreateNativeModule(), and v8::internal::wasm::AsyncCompileJob::PrepareAndStartCompile::RunInForeground().
CreateStreamingDecoder()
std::shared_ptr< StreamingDecoder > v8::internal::wasm::AsyncCompileJob::CreateStreamingDecoder ()
Definition at line 2665 of file module-compiler.cc.
                                                                        {
  DCHECK_NULL(stream_);
  stream_ = StreamingDecoder::CreateAsyncStreamingDecoder(
      std::make_unique<AsyncStreamingProcessor>(this));
  return stream_;
}
References v8::internal::wasm::StreamingDecoder::CreateAsyncStreamingDecoder(), DCHECK_NULL, and stream_.
Referenced by v8::internal::wasm::WasmEngine::StartStreamingCompilation().
DecrementAndCheckFinisherCount()
V8_WARN_UNUSED_RESULT bool v8::internal::wasm::AsyncCompileJob::DecrementAndCheckFinisherCount () [inline], [private]
Definition at line 167 of file module-compiler.h.
                                                              {
    DCHECK_LT(0, outstanding_finishers_.load());
    return outstanding_finishers_.fetch_sub(1) == 1;
  }
References DCHECK_LT, and outstanding_finishers_.
Referenced by v8::internal::wasm::AsyncCompileJob::CompilationStateCallback::call(), and v8::internal::wasm::AsyncStreamingProcessor::OnFinishedStream().
DoAsync()
template<typename Step , typename... Args>
void v8::internal::wasm::AsyncCompileJob::DoAsync (Args &&... args) [private]
Definition at line 3025 of file module-compiler.cc.
                                            {
  NextStep<Step>(std::forward<Args>(args)...);
  StartBackgroundTask();
}
References v8::base::args, and StartBackgroundTask().
DoImmediately()
template<typename Step , typename... Args>
void v8::internal::wasm::AsyncCompileJob::DoImmediately (Args &&... args) [private]
Definition at line 3019 of file module-compiler.cc.
                                                  {
  NextStep<Step>(std::forward<Args>(args)...);
  ExecuteForegroundTaskImmediately();
}
References v8::base::args, and ExecuteForegroundTaskImmediately().
Referenced by v8::internal::wasm::AsyncStreamingProcessor::ProcessCodeSectionHeader().
DoSync()
template<typename Step , AsyncCompileJob::UseExistingForegroundTask use_existing_fg_task, typename... Args>
void v8::internal::wasm::AsyncCompileJob::DoSync (Args &&... args) [private]
Definition at line 3012 of file module-compiler.cc.
                                           {
  NextStep<Step>(std::forward<Args>(args)...);
  if (use_existing_fg_task && pending_foreground_task_ != nullptr) return;
  StartForegroundTask();
}
References v8::base::args, pending_foreground_task_, and StartForegroundTask().
Referenced by v8::internal::wasm::AsyncCompileJob::CompilationStateCallback::call(), v8::internal::wasm::AsyncStreamingProcessor::OnFinishedStream(), and v8::internal::wasm::AsyncCompileJob::DecodeModule::RunInBackground().
ExecuteForegroundTaskImmediately()
void v8::internal::wasm::AsyncCompileJob::ExecuteForegroundTaskImmediately () [private]
Definition at line 2982 of file module-compiler.cc.
                                                       {
  DCHECK_NULL(pending_foreground_task_);
  auto new_task = std::make_unique<CompileTask>(this, true);
  pending_foreground_task_ = new_task.get();
  new_task->Run();
}
References DCHECK_NULL, pending_foreground_task_, and v8::internal::CancelableTask::Run().
Referenced by DoImmediately().
Failed()
void v8::internal::wasm::AsyncCompileJob::Failed () [private]
Definition at line 2833 of file module-compiler.cc.
                             {
  // {job} keeps the {this} pointer alive.
  std::unique_ptr<AsyncCompileJob> job =
      GetWasmEngine()->RemoveCompileJob(this);
  // Revalidate the whole module to produce a deterministic error message.
  constexpr bool kValidate = true;
  WasmDetectedFeatures unused_detected_features;
  ModuleResult result =
      DecodeWasmModule(enabled_features_, wire_bytes_.module_bytes(), kValidate,
                       kWasmOrigin, &unused_detected_features);
  ErrorThrower thrower(isolate_, api_method_name_);
  if (result.failed()) {
    thrower.CompileFailed(std::move(result).error());
  } else {
    // The only possible reason why {result} might be okay is if the failure
    // was due to compile-time imports checking.
    CHECK(!job->compile_imports_.empty());
    WasmError error = ValidateAndSetBuiltinImports(
        result.value().get(), wire_bytes_.module_bytes(), job->compile_imports_,
        &unused_detected_features);
    CHECK(error.has_error());
    thrower.CompileError("%s", error.message().c_str());
  }
  resolver_->OnCompilationFailed(thrower.Reify());
}
References api_method_name_, CHECK, v8::internal::wasm::ErrorThrower::CompileFailed(), v8::internal::wasm::DecodeWasmModule(), enabled_features_, v8::internal::wasm::GetWasmEngine(), v8::internal::wasm::WasmError::has_error(), isolate_, v8::internal::wasm::kWasmOrigin, v8::internal::wasm::WasmError::message(), v8::internal::wasm::ModuleWireBytes::module_bytes(), v8::internal::wasm::ErrorThrower::Reify(), v8::internal::wasm::WasmEngine::RemoveCompileJob(), resolver_, v8::base::internal::result, v8::internal::wasm::ValidateAndSetBuiltinImports(), and wire_bytes_.
Referenced by v8::internal::wasm::AsyncStreamingProcessor::OnFinishedStream(), v8::internal::wasm::AsyncCompileJob::PrepareAndStartCompile::RunInForeground(), and v8::internal::wasm::AsyncCompileJob::Fail::RunInForeground().
FinishCompile()
void v8::internal::wasm::AsyncCompileJob::FinishCompile (bool is_after_cache_hit) [private]
Definition at line 2738 of file module-compiler.cc.
                                                           {
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.wasm.detailed"),
               "wasm.FinishAsyncCompile");
  if (stream_) {
    stream_->NotifyNativeModuleCreated(native_module_);
  }
  const WasmModule* module = native_module_->module();
  auto compilation_state = Impl(native_module_->compilation_state());
  // Update the compilation state with feature detected during module decoding
  // and (potentially) validation. We will publish all features below, in the
  // current isolate, so ignore the return value here.
  USE(compilation_state->UpdateDetectedFeatures(detected_features_));
  // If experimental PGO via files is enabled, load profile information now that
  // we have all wire bytes and know that the module is valid.
  if (V8_UNLIKELY(v8_flags.experimental_wasm_pgo_from_file)) {
    std::unique_ptr<ProfileInformation> pgo_info =
        LoadProfileFromFile(module, native_module_->wire_bytes());
    if (pgo_info) {
      compilation_state->ApplyPgoInfoLate(pgo_info.get());
    }
  }
  bool is_after_deserialization = !module_object_.is_null();
  if (!is_after_deserialization) {
    PrepareRuntimeObjects();
  }
  // Measure duration of baseline compilation or deserialization from cache.
  if (base::TimeTicks::IsHighResolution()) {
    base::TimeDelta duration = base::TimeTicks::Now() - start_time_;
    int duration_usecs = static_cast<int>(duration.InMicroseconds());
    isolate_->counters()->wasm_streaming_finish_wasm_module_time()->AddSample(
        duration_usecs);
    if (is_after_cache_hit || is_after_deserialization) {
      v8::metrics::WasmModuleCompiled event{
          true, // async
          true, // streamed
          is_after_cache_hit, // cached
          is_after_deserialization, // deserialized
          v8_flags.wasm_lazy_compilation, // lazy
          !compilation_state->failed(), // success
          native_module_->turbofan_code_size(), // code_size_in_bytes
          native_module_->liftoff_bailout_count(), // liftoff_bailout_count
          duration.InMicroseconds()}; // wall_clock_duration_in_us
      isolate_->metrics_recorder()->DelayMainThreadEvent(event, context_id_);
    }
  }
  DCHECK(!isolate_->context().is_null());
  // Finish the wasm script now and make it public to the debugger.
  DirectHandle<Script> script(module_object_->script(), isolate_);
  auto sourcemap_symbol =
      module->debug_symbols[WasmDebugSymbols::Type::SourceMap];
  if (script->type() == Script::Type::kWasm &&
      sourcemap_symbol.type != WasmDebugSymbols::Type::None &&
      !sourcemap_symbol.external_url.is_empty()) {
    ModuleWireBytes wire_bytes(native_module_->wire_bytes());
    MaybeDirectHandle<String> src_map_str =
        isolate_->factory()->NewStringFromUtf8(
            wire_bytes.GetNameOrNull(sourcemap_symbol.external_url),
            AllocationType::kOld);
    script->set_source_mapping_url(*src_map_str.ToHandleChecked());
  }
  {
    TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.wasm.detailed"),
                 "wasm.Debug.OnAfterCompile");
    isolate_->debug()->OnAfterCompile(script);
  }
  // Publish the detected features in this isolate, once initial compilation
  // is done. Validate should have detected all features, unless lazy validation
  // is enabled.
  PublishDetectedFeatures(compilation_state->detected_features(), isolate_,
                          true);
  // We might need debug code for the module, if the debugger was enabled while
  // streaming compilation was running. Since handling this while compiling via
  // streaming is tricky, we just remove all code which may have been generated,
  // and compile debug code lazily.
  if (native_module_->IsInDebugState()) {
    WasmCodeRefScope ref_scope;
    native_module_->RemoveCompiledCode(
        NativeModule::RemoveFilter::kRemoveNonDebugCode);
  }
  // Finally, log all generated code (it does not matter if this happens
  // repeatedly in case the script is shared).
  native_module_->LogWasmCodes(isolate_, module_object_->script());
  FinishSuccessfully();
}
References v8::internal::Isolate::context(), context_id_, v8::internal::Isolate::counters(), v8::internal::DCHECK(), v8::internal::Isolate::debug(), v8::internal::wasm::WasmModule::debug_symbols, detected_features_, v8::internal::duration, v8::internal::Isolate::factory(), FinishSuccessfully(), v8::internal::wasm::ModuleWireBytes::GetNameOrNull(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::Impl(), v8::base::TimeTicks::IsHighResolution(), isolate_, v8::internal::kOld, v8::internal::wasm::NativeModule::kRemoveNonDebugCode, v8::internal::wasm::LoadProfileFromFile(), v8::internal::Isolate::metrics_recorder(), module_object_, native_module_, v8::internal::Factory::NewStringFromUtf8(), v8::None, v8::base::TimeTicks::Now(), v8::internal::Debug::OnAfterCompile(), PrepareRuntimeObjects(), v8::internal::wasm::PublishDetectedFeatures(), v8::internal::script, start_time_, stream_, v8::internal::MaybeDirectHandle< T >::ToHandleChecked(), TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT0, USE, v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::internal::wasm::AsyncStreamingProcessor::Deserialize(), v8::internal::wasm::AsyncStreamingProcessor::OnFinishedStream(), v8::internal::wasm::AsyncCompileJob::PrepareAndStartCompile::RunInForeground(), and v8::internal::wasm::AsyncCompileJob::FinishCompilation::RunInForeground().
FinishSuccessfully()
void v8::internal::wasm::AsyncCompileJob::FinishSuccessfully () [private]
Definition at line 3212 of file module-compiler.cc.
                                         {
  TRACE_COMPILE("(4) Finish module...\n");
  {
    TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.wasm.detailed"),
                 "wasm.OnCompilationSucceeded");
    // We have to make sure that an "incumbent context" is available in case
    // the module's start function calls out to Blink.
    Local<v8::Context> backup_incumbent_context =
        Utils::ToLocal(incumbent_context_);
    v8::Context::BackupIncumbentScope incumbent(backup_incumbent_context);
    resolver_->OnCompilationSucceeded(module_object_);
  }
  GetWasmEngine()->RemoveCompileJob(this);
}
References v8::internal::wasm::GetWasmEngine(), incumbent_context_, module_object_, v8::internal::wasm::WasmEngine::RemoveCompileJob(), resolver_, TRACE_COMPILE, TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT0.
Referenced by FinishCompile().
GetOrCreateNativeModule()
bool v8::internal::wasm::AsyncCompileJob::GetOrCreateNativeModule (std::shared_ptr< const WasmModule > module, size_t code_size_estimate) [private]
Definition at line 2711 of file module-compiler.cc.
                                                                       {
  native_module_ = GetWasmEngine()->MaybeGetNativeModule(
      module->origin, wire_bytes_.module_bytes(), compile_imports_, isolate_);
  if (native_module_ == nullptr) {
    CreateNativeModule(std::move(module), code_size_estimate);
    return false;
  }
  return true;
}
References compile_imports_, CreateNativeModule(), v8::internal::wasm::GetWasmEngine(), isolate_, v8::internal::wasm::WasmEngine::MaybeGetNativeModule(), v8::internal::wasm::ModuleWireBytes::module_bytes(), native_module_, and wire_bytes_.
Referenced by v8::internal::wasm::AsyncStreamingProcessor::OnFinishedStream(), and v8::internal::wasm::AsyncCompileJob::PrepareAndStartCompile::RunInForeground().
isolate()
Isolate* v8::internal::wasm::AsyncCompileJob::isolate () const [inline]
Definition at line 131 of file module-compiler.h.
{ return isolate_; }
References isolate_.
Referenced by AsyncCompileJob(), v8::internal::wasm::AsyncStreamingProcessor::Deserialize(), v8::internal::wasm::AsyncStreamingProcessor::ProcessCodeSectionHeader(), and v8::internal::wasm::AsyncCompileJob::PrepareAndStartCompile::RunInForeground().
NextStep()
template<typename Step , typename... Args>
void v8::internal::wasm::AsyncCompileJob::NextStep (Args &&... args) [private]
Definition at line 3031 of file module-compiler.cc.
                                             {
  step_.reset(new Step(std::forward<Args>(args)...));
}
References v8::base::args, and step_.
PrepareRuntimeObjects()
void v8::internal::wasm::AsyncCompileJob::PrepareRuntimeObjects () [private]
Definition at line 2722 of file module-compiler.cc.
                                            {
  // Create heap objects for script and module bytes to be stored in the
  // module object. Asm.js is not compiled asynchronously.
  DCHECK(module_object_.is_null());
  auto source_url =
      stream_ ? base::VectorOf(stream_->url()) : base::Vector<const char>();
  auto script =
      GetWasmEngine()->GetOrCreateScript(isolate_, native_module_, source_url);
  DirectHandle<WasmModuleObject> module_object =
      WasmModuleObject::New(isolate_, native_module_, script);
  module_object_ = isolate_->global_handles()->Create(*module_object);
}
References v8::internal::GlobalHandles::Create(), v8::internal::DCHECK(), v8::internal::wasm::WasmEngine::GetOrCreateScript(), v8::internal::wasm::GetWasmEngine(), v8::internal::Isolate::global_handles(), isolate_, module_object_, native_module_, v8::internal::WasmModuleObject::New(), v8::internal::script, stream_, and v8::base::VectorOf().
Referenced by FinishCompile().
Start()
void v8::internal::wasm::AsyncCompileJob::Start ()
Definition at line 2475 of file module-compiler.cc.
                            {
  DoAsync<DecodeModule>(isolate_->counters(),
                        isolate_->metrics_recorder()); // --
}
References v8::internal::Isolate::counters(), isolate_, and v8::internal::Isolate::metrics_recorder().
Referenced by v8::internal::wasm::WasmEngine::AsyncCompile().
StartBackgroundTask()
void v8::internal::wasm::AsyncCompileJob::StartBackgroundTask () [private]
Definition at line 2996 of file module-compiler.cc.
                                          {
  auto task = std::make_unique<CompileTask>(this, false);
  // If --wasm-num-compilation-tasks=0 is passed, do only spawn foreground
  // tasks. This is used to make timing deterministic.
  if (v8_flags.wasm_num_compilation_tasks > 0) {
    V8::GetCurrentPlatform()->PostTaskOnWorkerThread(
        TaskPriority::kUserBlocking, std::move(task));
  } else {
    foreground_task_runner_->PostTask(std::move(task));
  }
}
References foreground_task_runner_, v8::internal::V8::GetCurrentPlatform(), v8::kUserBlocking, v8::Platform::PostTaskOnWorkerThread(), and v8::internal::v8_flags.
Referenced by DoAsync().
StartForegroundTask()
void v8::internal::wasm::AsyncCompileJob::StartForegroundTask () [private]
Definition at line 2974 of file module-compiler.cc.
                                          {
  DCHECK_NULL(pending_foreground_task_);
  auto new_task = std::make_unique<CompileTask>(this, true);
  pending_foreground_task_ = new_task.get();
  foreground_task_runner_->PostTask(std::move(new_task));
}
References DCHECK_NULL, foreground_task_runner_, and pending_foreground_task_.
Referenced by DoSync().
Friends And Related Function Documentation
AsyncStreamingProcessor
friend class AsyncStreamingProcessor [friend]
Definition at line 162 of file module-compiler.h.
Member Data Documentation
api_method_name_
const char* const v8::internal::wasm::AsyncCompileJob::api_method_name_ [private]
Definition at line 220 of file module-compiler.h.
Referenced by Failed().
background_task_manager_
CancelableTaskManager v8::internal::wasm::AsyncCompileJob::background_task_manager_ [private]
Definition at line 241 of file module-compiler.h.
Referenced by v8::internal::wasm::AsyncCompileJob::PrepareAndStartCompile::RunInForeground(), and ~AsyncCompileJob().
bytes_copy_
base::OwnedVector<const uint8_t> v8::internal::wasm::AsyncCompileJob::bytes_copy_ [private]
Definition at line 227 of file module-compiler.h.
Referenced by CreateNativeModule(), and v8::internal::wasm::AsyncStreamingProcessor::OnFinishedStream().
compilation_id_
const int v8::internal::wasm::AsyncCompileJob::compilation_id_ [private]
Definition at line 260 of file module-compiler.h.
Referenced by CreateNativeModule().
compile_imports_
CompileTimeImports v8::internal::wasm::AsyncCompileJob::compile_imports_ [private]
Definition at line 223 of file module-compiler.h.
Referenced by CreateNativeModule(), v8::internal::wasm::AsyncStreamingProcessor::Deserialize(), GetOrCreateNativeModule(), v8::internal::wasm::AsyncStreamingProcessor::OnAbort(), v8::internal::wasm::AsyncStreamingProcessor::OnFinishedStream(), v8::internal::wasm::AsyncStreamingProcessor::ProcessCodeSectionHeader(), and v8::internal::wasm::AsyncCompileJob::DecodeModule::RunInBackground().
context_id_
v8::metrics::Recorder::ContextId v8::internal::wasm::AsyncCompileJob::context_id_ [private]
Definition at line 233 of file module-compiler.h.
Referenced by AsyncCompileJob(), context_id(), FinishCompile(), v8::internal::wasm::AsyncStreamingProcessor::OnFinishedStream(), and v8::internal::wasm::AsyncCompileJob::PrepareAndStartCompile::RunInForeground().
detected_features_
WasmDetectedFeatures v8::internal::wasm::AsyncCompileJob::detected_features_ [private]
Definition at line 222 of file module-compiler.h.
Referenced by CreateNativeModule(), FinishCompile(), v8::internal::wasm::AsyncStreamingProcessor::OnFinishedStream(), and v8::internal::wasm::AsyncCompileJob::DecodeModule::RunInBackground().
enabled_features_
const WasmEnabledFeatures v8::internal::wasm::AsyncCompileJob::enabled_features_ [private]
Definition at line 221 of file module-compiler.h.
Referenced by CreateNativeModule(), Failed(), v8::internal::wasm::AsyncStreamingProcessor::OnFinishedStream(), v8::internal::wasm::AsyncStreamingProcessor::ProcessFunctionBody(), and v8::internal::wasm::AsyncCompileJob::DecodeModule::RunInBackground().
foreground_task_runner_
std::shared_ptr<v8::TaskRunner> v8::internal::wasm::AsyncCompileJob::foreground_task_runner_ [private]
Definition at line 243 of file module-compiler.h.
Referenced by AsyncCompileJob(), StartBackgroundTask(), and StartForegroundTask().
incumbent_context_
IndirectHandle<NativeContext> v8::internal::wasm::AsyncCompileJob::incumbent_context_ [private]
Definition at line 232 of file module-compiler.h.
Referenced by AsyncCompileJob(), FinishSuccessfully(), and ~AsyncCompileJob().
isolate_
Isolate* const v8::internal::wasm::AsyncCompileJob::isolate_ [private]
Definition at line 219 of file module-compiler.h.
Referenced by v8::internal::wasm::AsyncCompileJob::CompilationStateCallback::call(), CreateNativeModule(), v8::internal::wasm::AsyncStreamingProcessor::Deserialize(), Failed(), FinishCompile(), GetOrCreateNativeModule(), isolate(), v8::internal::wasm::AsyncStreamingProcessor::OnFinishedStream(), PrepareRuntimeObjects(), v8::internal::wasm::AsyncCompileJob::CompileStep::Run(), v8::internal::wasm::AsyncCompileJob::PrepareAndStartCompile::RunInForeground(), Start(), and ~AsyncCompileJob().
metrics_event_
v8::metrics::WasmModuleDecoded v8::internal::wasm::AsyncCompileJob::metrics_event_ [private]
Definition at line 234 of file module-compiler.h.
Referenced by AsyncCompileJob(), and v8::internal::wasm::AsyncStreamingProcessor::OnFinishedStream().
module_object_
IndirectHandle<WasmModuleObject> v8::internal::wasm::AsyncCompileJob::module_object_ [private]
Definition at line 237 of file module-compiler.h.
Referenced by v8::internal::wasm::AsyncStreamingProcessor::Deserialize(), FinishCompile(), FinishSuccessfully(), PrepareRuntimeObjects(), and ~AsyncCompileJob().
native_context_
IndirectHandle<NativeContext> v8::internal::wasm::AsyncCompileJob::native_context_ [private]
Definition at line 231 of file module-compiler.h.
Referenced by AsyncCompileJob(), context(), v8::internal::wasm::AsyncStreamingProcessor::Deserialize(), v8::internal::wasm::AsyncStreamingProcessor::OnFinishedStream(), v8::internal::wasm::AsyncCompileJob::CompileStep::Run(), and ~AsyncCompileJob().
native_module_
std::shared_ptr<NativeModule> v8::internal::wasm::AsyncCompileJob::native_module_ [private]
Definition at line 238 of file module-compiler.h.
Referenced by v8::internal::wasm::AsyncCompileJob::CompilationStateCallback::call(), CreateNativeModule(), v8::internal::wasm::AsyncStreamingProcessor::Deserialize(), FinishCompile(), GetOrCreateNativeModule(), v8::internal::wasm::AsyncStreamingProcessor::OnAbort(), v8::internal::wasm::AsyncStreamingProcessor::OnFinishedStream(), PrepareRuntimeObjects(), v8::internal::wasm::AsyncStreamingProcessor::ProcessCodeSectionHeader(), v8::internal::wasm::AsyncStreamingProcessor::ProcessFunctionBody(), v8::internal::wasm::AsyncCompileJob::PrepareAndStartCompile::RunInForeground(), v8::internal::wasm::AsyncCompileJob::FinishCompilation::RunInForeground(), and ~AsyncCompileJob().
outstanding_finishers_
std::atomic<int32_t> v8::internal::wasm::AsyncCompileJob::outstanding_finishers_ {1} [private]
Definition at line 248 of file module-compiler.h.
Referenced by DecrementAndCheckFinisherCount(), and v8::internal::wasm::AsyncStreamingProcessor::ProcessCodeSectionHeader().
pending_foreground_task_
CompileTask* v8::internal::wasm::AsyncCompileJob::pending_foreground_task_ = nullptr [private]
Definition at line 251 of file module-compiler.h.
Referenced by CancelPendingForegroundTask(), DoSync(), ExecuteForegroundTaskImmediately(), v8::internal::wasm::AsyncCompileJob::CompileTask::ResetPendingForegroundTask(), and StartForegroundTask().
resolver_
const std::shared_ptr<CompilationResultResolver> v8::internal::wasm::AsyncCompileJob::resolver_ [private]
Definition at line 235 of file module-compiler.h.
Referenced by Failed(), and FinishSuccessfully().
start_time_
base::TimeTicks v8::internal::wasm::AsyncCompileJob::start_time_ [private]
Definition at line 224 of file module-compiler.h.
Referenced by FinishCompile(), and v8::internal::wasm::AsyncStreamingProcessor::OnFinishedStream().
step_
std::unique_ptr<CompileStep> v8::internal::wasm::AsyncCompileJob::step_ [private]
Definition at line 240 of file module-compiler.h.
Referenced by NextStep(), and v8::internal::wasm::AsyncCompileJob::CompileTask::RunInternal().
stream_
std::shared_ptr<StreamingDecoder> v8::internal::wasm::AsyncCompileJob::stream_ [private]
Definition at line 257 of file module-compiler.h.
Referenced by CreateStreamingDecoder(), v8::internal::wasm::AsyncStreamingProcessor::Deserialize(), FinishCompile(), PrepareRuntimeObjects(), v8::internal::wasm::AsyncCompileJob::PrepareAndStartCompile::RunInForeground(), and ~AsyncCompileJob().
wire_bytes_
ModuleWireBytes v8::internal::wasm::AsyncCompileJob::wire_bytes_ [private]
Definition at line 230 of file module-compiler.h.
Referenced by v8::internal::wasm::AsyncStreamingProcessor::Deserialize(), Failed(), GetOrCreateNativeModule(), v8::internal::wasm::AsyncStreamingProcessor::OnFinishedStream(), v8::internal::wasm::AsyncCompileJob::DecodeModule::RunInBackground(), and v8::internal::wasm::AsyncCompileJob::PrepareAndStartCompile::RunInForeground().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/module-compiler.h
/mnt/V8SourceCode/src/wasm/module-compiler.cc