v8::internal::wasm::WasmInterpreter Class Reference
#include <wasm-interpreter.h>
Classes
class CodeMap
Public Member Functions
WasmInterpreter (Isolate *isolate, const WasmModule *module, const ModuleWireBytes &wire_bytes, DirectHandle< WasmInstanceObject > instance)
void BeginExecution (WasmInterpreterThread *thread, uint32_t function_index, Address frame_pointer, uint8_t *interpreter_fp, uint32_t ref_stack_offset, const std::vector< WasmValue > &argument_values)
void BeginExecution (WasmInterpreterThread *thread, uint32_t function_index, Address frame_pointer, uint8_t *interpreter_fp)
WasmInterpreterThread::State ContinueExecution (WasmInterpreterThread *thread, bool called_from_js)
WasmValue GetReturnValue (int index) const
std::vector< WasmInterpreterStackEntry > GetInterpretedStack (Address frame_pointer)
int GetFunctionIndex (Address frame_pointer, int index) const
void SetTrapFunctionIndex (int32_t func_index)
WasmInterpreterRuntime * GetWasmRuntime ()
Static Public Member Functions
static void InitializeOncePerProcess ()
static void GlobalTearDown ()
static void NotifyIsolateDisposal (Isolate *isolate)
Private Member Functions
WasmInterpreter (const WasmInterpreter &)=delete
WasmInterpreter & operator= (const WasmInterpreter &)=delete
Private Attributes
Zone zone_
IndirectHandle< WasmInstanceObject > instance_object_
const ZoneVector< uint8_t > module_bytes_
CodeMap codemap_
std::shared_ptr< WasmInterpreterRuntime > wasm_runtime_
Detailed Description
Definition at line 585 of file wasm-interpreter.h.
Constructor & Destructor Documentation
WasmInterpreter() [1/2]
v8::internal::wasm::WasmInterpreter::WasmInterpreter (Isolate * isolate, const WasmModule * module, const ModuleWireBytes & wire_bytes, DirectHandle< WasmInstanceObject > instance)
Definition at line 634 of file wasm-interpreter.cc.
    : zone_(isolate->allocator(), ZONE_NAME),
      instance_object_(MakeWeak(isolate, instance_object)),
      module_bytes_(wire_bytes.start(), wire_bytes.end(), &zone_),
      codemap_(isolate, module, module_bytes_.data(), &zone_) {
  wasm_runtime_ = std::make_shared<WasmInterpreterRuntime>(
      module, isolate, instance_object_, &codemap_);
  module->SetWasmInterpreter(wasm_runtime_);
#if !defined(V8_DRUMBRAKE_BOUNDS_CHECKS)
  // TODO(paolosev@microsoft.com) - For modules that have 64-bit Wasm memory we
  // need to use explicit bound checks; memory guard pages only work with 32-bit
  // memories. This could be implemented by allocating a different dispatch
  // table for each instance (probably in the WasmInterpreterRuntime object) and
  // patching the entries of Load/Store instructions with bultin handlers only
  // for instances related to modules that have 32-bit memories. 64-bit memories
  // are not supported yet by DrumBrake.
  base::CallOnce(&init_instruction_table_once, &InitInstructionTableOnce,
                 isolate);
  base::CallOnce(&init_trap_handlers_once, &InitTrapHandlersOnce, isolate);
  trap_handler::SetLandingPad(reinterpret_cast<Address>(TrapMemOutOfBounds));
#endif // !V8_DRUMBRAKE_BOUNDS_CHECKS
}
References v8::base::CallOnce(), codemap_, v8::internal::wasm::InitInstructionTableOnce(), v8::internal::wasm::InitTrapHandlersOnce(), instance_object_, v8::internal::trap_handler::SetLandingPad(), v8::internal::wasm::TrapMemOutOfBounds(), and wasm_runtime_.
WasmInterpreter() [2/2]
v8::internal::wasm::WasmInterpreter::WasmInterpreter (const WasmInterpreter &) [private], [delete]
Member Function Documentation
BeginExecution() [1/2]
void v8::internal::wasm::WasmInterpreter::BeginExecution (WasmInterpreterThread * thread, uint32_t function_index, Address frame_pointer, uint8_t * interpreter_fp) [inline]
Definition at line 93 of file wasm-interpreter-inl.h.
                                                                     {
  codemap_.GetCode(function_index);
  wasm_runtime_->BeginExecution(thread, function_index, frame_pointer,
                                interpreter_fp, thread->NextRefStackOffset());
}
References codemap_, v8::internal::wasm::WasmInterpreter::CodeMap::GetCode(), v8::internal::wasm::WasmInterpreterThread::NextRefStackOffset(), and wasm_runtime_.
BeginExecution() [2/2]
void v8::internal::wasm::WasmInterpreter::BeginExecution (WasmInterpreterThread * thread, uint32_t function_index, Address frame_pointer, uint8_t * interpreter_fp, uint32_t ref_stack_offset, const std::vector< WasmValue > & argument_values) [inline]
Definition at line 84 of file wasm-interpreter-inl.h.
                                      {
  codemap_.GetCode(function_index);
  wasm_runtime_->BeginExecution(thread, function_index, frame_pointer,
                                interpreter_fp, ref_stack_offset, &args);
}
References v8::base::args, codemap_, v8::internal::wasm::WasmInterpreter::CodeMap::GetCode(), and wasm_runtime_.
Referenced by v8::internal::wasm::InterpreterHandle::Execute().
ContinueExecution()
WasmInterpreterThread::State v8::internal::wasm::WasmInterpreter::ContinueExecution (WasmInterpreterThread * thread, bool called_from_js)
Definition at line 662 of file wasm-interpreter.cc.
                                                        {
  wasm_runtime_->ContinueExecution(thread, called_from_js);
  return thread->state();
}
References v8::internal::wasm::WasmInterpreterThread::state(), and wasm_runtime_.
Referenced by v8::internal::wasm::InterpreterHandle::ContinueExecution().
GetFunctionIndex()
int v8::internal::wasm::WasmInterpreter::GetFunctionIndex (Address frame_pointer, int index) const [inline]
Definition at line 111 of file wasm-interpreter-inl.h.
                                                              {
  return wasm_runtime_->GetFunctionIndex(frame_pointer, index);
}
References v8::internal::index, and wasm_runtime_.
Referenced by v8::internal::wasm::InterpreterHandle::GetFunctionIndex().
GetInterpretedStack()
std::vector< WasmInterpreterStackEntry > v8::internal::wasm::WasmInterpreter::GetInterpretedStack (Address frame_pointer) [inline]
Definition at line 107 of file wasm-interpreter-inl.h.
                                                          {
  return wasm_runtime_->GetInterpretedStack(frame_pointer);
}
References wasm_runtime_.
Referenced by v8::internal::wasm::InterpreterHandle::GetInterpretedStack().
GetReturnValue()
WasmValue v8::internal::wasm::WasmInterpreter::GetReturnValue (int index) const [inline]
Definition at line 102 of file wasm-interpreter-inl.h.
                                                                {
  return wasm_runtime_->GetReturnValue(index);
}
References v8::internal::index, and wasm_runtime_.
Referenced by v8::internal::wasm::InterpreterHandle::Execute().
GetWasmRuntime()
WasmInterpreterRuntime* v8::internal::wasm::WasmInterpreter::GetWasmRuntime () [inline]
Definition at line 647 of file wasm-interpreter.h.
                                                  {
    return wasm_runtime_.get();
  }
Referenced by v8::internal::wasm::WasmInterpreterThread::GetCurrentActivationFor(), and v8::internal::RUNTIME_FUNCTION().
GlobalTearDown()
void v8::internal::wasm::WasmInterpreter::GlobalTearDown () [static]
Definition at line 8674 of file wasm-interpreter.cc.
                                     {
  // TODO(paolosev@microsoft.com): Support multithreading.
#ifdef DRUMBRAKE_ENABLE_PROFILING
  PrintAndClearProfilingData();
#endif // DRUMBRAKE_ENABLE_PROFILING
  if (v8_flags.drumbrake_compact_bytecode) {
    WasmBytecodeGenerator::PrintBytecodeCompressionStats();
  }
  WasmInterpreterThread::Terminate();
}
References v8::internal::wasm::WasmBytecodeGenerator::PrintBytecodeCompressionStats(), v8::internal::wasm::WasmInterpreterThread::Terminate(), and v8::internal::v8_flags.
Referenced by v8::internal::wasm::WasmEngine::GlobalTearDown().
InitializeOncePerProcess()
void v8::internal::wasm::WasmInterpreter::InitializeOncePerProcess () [static]
Definition at line 8669 of file wasm-interpreter.cc.
                                               {
  WasmInterpreterThread::Initialize();
}
References v8::internal::wasm::WasmInterpreterThread::Initialize().
Referenced by v8::internal::wasm::WasmEngine::InitializeOncePerProcess().
NotifyIsolateDisposal()
void v8::internal::wasm::WasmInterpreter::NotifyIsolateDisposal (Isolate * isolate) [static]
Definition at line 8780 of file wasm-interpreter.cc.
                                                            {
  WasmInterpreterThread::NotifyIsolateDisposal(isolate);
}
References v8::internal::wasm::WasmInterpreterThread::NotifyIsolateDisposal().
Referenced by v8::internal::Isolate::Deinit().
operator=()
WasmInterpreter& v8::internal::wasm::WasmInterpreter::operator= (const WasmInterpreter &) [private], [delete]
SetTrapFunctionIndex()
void v8::internal::wasm::WasmInterpreter::SetTrapFunctionIndex (int32_t func_index) [inline]
Definition at line 116 of file wasm-interpreter-inl.h.
                                                                    {
  wasm_runtime_->SetTrapFunctionIndex(func_index);
}
References wasm_runtime_.
Referenced by v8::internal::wasm::InterpreterHandle::SetTrapFunctionIndex().
Member Data Documentation
codemap_
CodeMap v8::internal::wasm::WasmInterpreter::codemap_ [private]
Definition at line 664 of file wasm-interpreter.h.
Referenced by BeginExecution(), and WasmInterpreter().
instance_object_
IndirectHandle<WasmInstanceObject> v8::internal::wasm::WasmInterpreter::instance_object_ [private]
Definition at line 658 of file wasm-interpreter.h.
Referenced by WasmInterpreter().
module_bytes_
const ZoneVector<uint8_t> v8::internal::wasm::WasmInterpreter::module_bytes_ [private]
Definition at line 662 of file wasm-interpreter.h.
wasm_runtime_
std::shared_ptr<WasmInterpreterRuntime> v8::internal::wasm::WasmInterpreter::wasm_runtime_ [private]
Definition at line 667 of file wasm-interpreter.h.
Referenced by BeginExecution(), ContinueExecution(), GetFunctionIndex(), GetInterpretedStack(), v8::internal::wasm::WasmInterpreterThread::Activation::GetIsolate(), GetReturnValue(), SetTrapFunctionIndex(), and WasmInterpreter().
zone_
Zone v8::internal::wasm::WasmInterpreter::zone_ [private]
Definition at line 657 of file wasm-interpreter.h.
Referenced by v8::internal::wasm::WasmInterpreter::CodeMap::Preprocess().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter.h
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter-inl.h
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter.cc