v8::internal::compiler::AllNodes Class Reference
#include <all-nodes.h>
Public Member Functions
AllNodes (Zone *local_zone, Node *end, const TFGraph *graph, bool only_inputs=true)
AllNodes (Zone *local_zone, const TFGraph *graph, bool only_inputs=true)
bool IsLive (const Node *node) const
bool IsReachable (const Node *node) const
Public Attributes
NodeVector reachable
Private Member Functions
void Mark (Zone *local_zone, Node *end, const TFGraph *graph)
Private Attributes
BitVector is_reachable_
const bool only_inputs_
Detailed Description
Definition at line 17 of file all-nodes.h.
Constructor & Destructor Documentation
AllNodes() [1/2]
v8::internal::compiler::AllNodes::AllNodes (Zone * local_zone, Node * end, const TFGraph * graph, bool only_inputs = true)
Definition at line 20 of file all-nodes.cc.
    : reachable(local_zone),
      is_reachable_(static_cast<int>(graph->NodeCount()), local_zone),
      only_inputs_(only_inputs) {
  Mark(local_zone, end, graph);
}
References v8::internal::compiler::end(), graph(), and Mark().
AllNodes() [2/2]
v8::internal::compiler::AllNodes::AllNodes (Zone * local_zone, const TFGraph * graph, bool only_inputs = true)
Definition at line 13 of file all-nodes.cc.
    : reachable(local_zone),
      is_reachable_(static_cast<int>(graph->NodeCount()), local_zone),
      only_inputs_(only_inputs) {
  Mark(local_zone, graph->end(), graph);
}
References graph(), and Mark().
Member Function Documentation
IsLive()
bool v8::internal::compiler::AllNodes::IsLive (const Node * node) const [inline]
Definition at line 28 of file all-nodes.h.
                                      {
    CHECK(only_inputs_);
    return IsReachable(node);
  }
References CHECK, IsReachable(), and only_inputs_.
Referenced by v8::internal::compiler::JSONGraphWriter::Print().
IsReachable()
bool v8::internal::compiler::AllNodes::IsReachable (const Node * node) const [inline]
Definition at line 33 of file all-nodes.h.
                                           {
    if (!node) return false;
    int id = node->id();
    return id < is_reachable_.length() && is_reachable_.Contains(id);
  }
References v8::internal::BitVector::Contains(), v8::internal::compiler::Node::id(), is_reachable_, and v8::internal::BitVector::length().
Referenced by IsLive().
Mark()
void v8::internal::compiler::AllNodes::Mark (Zone * local_zone, Node * end, const TFGraph * graph) [private]
Definition at line 28 of file all-nodes.cc.
                                                                     {
  DCHECK_LT(end->id(), graph->NodeCount());
  is_reachable_.Add(end->id());
  reachable.push_back(end);
  // Find all nodes reachable from {end}.
  for (size_t i = 0; i < reachable.size(); i++) {
    for (Node* const input : reachable[i]->inputs()) {
      if (input == nullptr) {
        // TODO(titzer): print a warning.
        continue;
      }
      if (!is_reachable_.Contains(input->id())) {
        is_reachable_.Add(input->id());
        reachable.push_back(input);
      }
    }
    if (!only_inputs_) {
      for (Node* use : reachable[i]->uses()) {
        if (use == nullptr || use->id() >= graph->NodeCount()) {
          continue;
        }
        if (!is_reachable_.Contains(use->id())) {
          is_reachable_.Add(use->id());
          reachable.push_back(use);
        }
      }
    }
  }
}
References v8::internal::BitVector::Add(), v8::internal::BitVector::Contains(), DCHECK_LT, v8::internal::compiler::end(), graph(), is_reachable_, only_inputs_, v8::internal::ZoneVector< T >::push_back(), reachable, v8::internal::ZoneVector< T >::size(), and use().
Referenced by AllNodes().
Member Data Documentation
is_reachable_
BitVector v8::internal::compiler::AllNodes::is_reachable_ [private]
Definition at line 44 of file all-nodes.h.
Referenced by IsReachable(), and Mark().
only_inputs_
const bool v8::internal::compiler::AllNodes::only_inputs_ [private]
Definition at line 45 of file all-nodes.h.
Referenced by IsLive(), and Mark().
reachable
NodeVector v8::internal::compiler::AllNodes::reachable
Definition at line 39 of file all-nodes.h.
Referenced by Mark(), and v8::internal::compiler::JSInliner::ReduceJSCall().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/all-nodes.h
/mnt/V8SourceCode/src/compiler/all-nodes.cc