v8::internal::wasm::WasmCompilationUnit Class Reference
#include <function-compiler.h>
Public Member Functions
WasmCompilationUnit (int index, ExecutionTier tier, ForDebugging for_debugging)
WasmCompilationResult ExecuteCompilation (CompilationEnv *, const WireBytesStorage *, Counters *, WasmDetectedFeatures *detected)
ExecutionTier tier () const
ForDebugging for_debugging () const
int func_index () const
Static Public Member Functions
static void CompileWasmFunction (Counters *, NativeModule *, WasmDetectedFeatures *detected, const WasmFunction *, ExecutionTier)
Private Attributes
int func_index_
ExecutionTier tier_
ForDebugging for_debugging_
Detailed Description
Definition at line 96 of file function-compiler.h.
Constructor & Destructor Documentation
WasmCompilationUnit()
v8::internal::wasm::WasmCompilationUnit::WasmCompilationUnit (int index, ExecutionTier tier, ForDebugging for_debugging) [inline]
Definition at line 98 of file function-compiler.h.
      : func_index_(index), tier_(tier), for_debugging_(for_debugging) {
    DCHECK_IMPLIES(for_debugging != ForDebugging::kNotForDebugging,
                   tier_ == ExecutionTier::kLiftoff);
  }
References DCHECK_IMPLIES, v8::internal::wasm::kLiftoff, and v8::internal::wasm::kNotForDebugging.
Member Function Documentation
CompileWasmFunction()
void v8::internal::wasm::WasmCompilationUnit::CompileWasmFunction (Counters * counters, NativeModule * native_module, WasmDetectedFeatures * detected, const WasmFunction * function, ExecutionTier tier) [static]
Definition at line 168 of file function-compiler.cc.
                                                                  {
  ModuleWireBytes wire_bytes(native_module->wire_bytes());
  bool is_shared = native_module->module()->type(function->sig_index).is_shared;
  FunctionBody function_body{function->sig, function->code.offset(),
                             wire_bytes.start() + function->code.offset(),
                             wire_bytes.start() + function->code.end_offset(),
                             is_shared};
  DCHECK_LE(native_module->num_imported_functions(), function->func_index);
  DCHECK_LT(function->func_index, native_module->num_functions());
  WasmCompilationUnit unit(function->func_index, tier, kNotForDebugging);
  CompilationEnv env = CompilationEnv::ForModule(native_module);
  base::FlushDenormalsScope disable_denormals(
      tier == ExecutionTier::kTurbofan &&
      native_module->compile_imports().contains(
          CompileTimeImport::kDisableDenormalFloats));
  WasmCompilationResult result = unit.ExecuteCompilation(
      &env, native_module->compilation_state()->GetWireBytesStorage().get(),
      counters, detected);
  if (result.succeeded()) {
    WasmCodeRefScope code_ref_scope;
    native_module->PublishCode(native_module->AddCompiledCode(result));
  } else {
    native_module->compilation_state()->SetError();
  }
}
References v8::internal::wasm::NativeModule::AddCompiledCode(), v8::internal::wasm::NativeModule::compilation_state(), v8::internal::wasm::NativeModule::compile_imports(), v8::internal::wasm::CompileTimeImports::contains(), DCHECK_LE, DCHECK_LT, ExecuteCompilation(), v8::internal::wasm::CompilationEnv::ForModule(), v8::internal::wasm::CompilationState::GetWireBytesStorage(), v8::internal::is_shared, v8::internal::wasm::TypeDefinition::is_shared, v8::internal::wasm::kDisableDenormalFloats, v8::internal::wasm::kNotForDebugging, v8::internal::wasm::kTurbofan, v8::internal::wasm::NativeModule::module(), v8::internal::wasm::NativeModule::num_functions(), v8::internal::wasm::NativeModule::num_imported_functions(), v8::internal::wasm::NativeModule::PublishCode(), v8::base::internal::result, v8::internal::wasm::CompilationState::SetError(), v8::internal::wasm::FunctionBody::sig, v8::internal::wasm::ModuleWireBytes::start(), v8::internal::wasm::WasmModule::type(), and v8::internal::wasm::NativeModule::wire_bytes().
Referenced by v8::internal::wasm::WasmEngine::CompileFunction().
ExecuteCompilation()
WasmCompilationResult v8::internal::wasm::WasmCompilationUnit::ExecuteCompilation (CompilationEnv * env, const WireBytesStorage * wire_bytes_storage, Counters * counters, WasmDetectedFeatures * detected)
Definition at line 28 of file function-compiler.cc.
                                                        {
  DCHECK_GE(func_index_, static_cast<int>(env->module->num_imported_functions));
  const WasmFunction* func = &env->module->functions[func_index_];
  base::Vector<const uint8_t> code = wire_bytes_storage->GetCode(func->code);
  bool is_shared = env->module->type(func->sig_index).is_shared;
  wasm::FunctionBody func_body{func->sig, func->code.offset(), code.begin(),
                               code.end(), is_shared};
  std::optional<TimedHistogramScope> wasm_compile_function_time_scope;
  std::optional<TimedHistogramScope> wasm_compile_huge_function_time_scope;
  if (counters && base::TimeTicks::IsHighResolution()) {
    if (func_body.end - func_body.start >= 100 * KB) {
      auto huge_size_histogram = SELECT_WASM_COUNTER(
          counters, env->module->origin, wasm, huge_function_size_bytes);
      huge_size_histogram->AddSample(
          static_cast<int>(func_body.end - func_body.start));
      wasm_compile_huge_function_time_scope.emplace(
          counters->wasm_compile_huge_function_time());
    }
    auto timed_histogram = SELECT_WASM_COUNTER(counters, env->module->origin,
                                               wasm_compile, function_time);
    wasm_compile_function_time_scope.emplace(timed_histogram);
  }
  // Before executing compilation, make sure that the function was validated.
  // Both Liftoff and TurboFan compilation do not perform validation, so can
  // only run on valid functions.
  if (V8_UNLIKELY(!env->module->function_was_validated(func_index_))) {
    // This code path can only be reached in
    // - eager compilation mode,
    // - with lazy validation,
    // - with PGO (which compiles some functions eagerly), or
    // - with compilation hints (which also compiles some functions eagerly).
    DCHECK(!v8_flags.wasm_lazy_compilation || v8_flags.wasm_lazy_validation ||
           v8_flags.experimental_wasm_pgo_from_file ||
           v8_flags.experimental_wasm_compilation_hints);
    Zone validation_zone{GetWasmEngine()->allocator(), ZONE_NAME};
    if (ValidateFunctionBody(&validation_zone, env->enabled_features,
                             env->module, detected, func_body)
            .failed()) {
      return {};
    }
    env->module->set_function_validated(func_index_);
  }
  if (v8_flags.trace_wasm_compiler) {
    PrintF("Compiling wasm function %d with %s\n", func_index_,
           ExecutionTierToString(tier_));
  }
  WasmCompilationResult result;
  int declared_index = declared_function_index(env->module, func_index_);
  switch (tier_) {
    case ExecutionTier::kNone:
#if V8_ENABLE_DRUMBRAKE
    case ExecutionTier::kInterpreter:
#endif // V8_ENABLE_DRUMBRAKE
      UNREACHABLE();
    case ExecutionTier::kLiftoff: {
      // The --wasm-tier-mask-for-testing flag can force functions to be
      // compiled with TurboFan, and the --wasm-debug-mask-for-testing can force
      // them to be compiled for debugging, see documentation.
      bool try_liftoff = true;
      if (V8_UNLIKELY(v8_flags.wasm_tier_mask_for_testing != 0)) {
        bool must_use_liftoff =
            v8_flags.liftoff_only ||
            for_debugging_ != ForDebugging::kNotForDebugging;
        bool tiering_requested =
            declared_index < 32 &&
            (v8_flags.wasm_tier_mask_for_testing & (1 << declared_index));
        if (!must_use_liftoff && tiering_requested) try_liftoff = false;
      }
      if (V8_LIKELY(try_liftoff)) {
        auto options = LiftoffOptions{}
                           .set_func_index(func_index_)
                           .set_for_debugging(for_debugging_)
                           .set_counters(counters)
                           .set_detected_features(detected);
        // We do not use the debug side table, we only (optionally) pass it to
        // cover different code paths in Liftoff for testing.
        std::unique_ptr<DebugSideTable> unused_debug_sidetable;
        if (V8_UNLIKELY(declared_index < 32 &&
                        (v8_flags.wasm_debug_mask_for_testing &
                         (1 << declared_index)) != 0)) {
          options.set_debug_sidetable(&unused_debug_sidetable);
          if (!for_debugging_) options.set_for_debugging(kForDebugging);
        }
        if (v8_flags.wasm_code_coverage &&
            options.for_debugging == kNotForDebugging) {
          options.set_for_debugging(kForDebugging);
        }
        result = ExecuteLiftoffCompilation(env, func_body, options);
        if (result.succeeded()) break;
      }
      // If --liftoff-only, do not fall back to turbofan, even if compilation
      // failed.
      if (v8_flags.liftoff_only) break;
      // If Liftoff failed, fall back to TurboFan.
      // TODO(wasm): We could actually stop or remove the tiering unit for this
      // function to avoid compiling it twice with TurboFan.
      [[fallthrough]];
    }
    case ExecutionTier::kTurbofan: {
      compiler::WasmCompilationData data(func_body);
      data.func_index = func_index_;
      data.wire_bytes_storage = wire_bytes_storage;
      result = compiler::turboshaft::ExecuteTurboshaftWasmCompilation(
          env, data, detected, counters);
      // In exceptional cases it can happen that compilation requests for
      // debugging end up being executed by Turbofan, e.g. if Liftoff bails out
      // because of unsupported features or the --wasm-tier-mask-for-testing is
      // set. In that case we set the for_debugging field for the TurboFan
      // result to match the requested for_debugging_.
      result.for_debugging = for_debugging_;
      break;
    }
  }
  DCHECK(result.succeeded());
  if (counters) {
    counters->wasm_generated_code_size()->Increment(
        result.code_desc.instr_size);
    counters->wasm_reloc_size()->Increment(result.code_desc.reloc_size);
    counters->wasm_deopt_data_size()->Increment(
        static_cast<int>(result.deopt_data.size()));
  }
  result.func_index = func_index_;
  return result;
}
References v8::internal::wasm::WasmEngine::allocator(), code, v8::internal::wasm::WasmFunction::code, v8::internal::DCHECK(), DCHECK_GE, v8::internal::wasm::declared_function_index(), v8::internal::wasm::CompilationEnv::enabled_features, v8::internal::wasm::ExecuteLiftoffCompilation(), v8::internal::compiler::turboshaft::ExecuteTurboshaftWasmCompilation(), v8::internal::wasm::ExecutionTierToString(), v8::internal::wasm::Result< T >::failed(), for_debugging_, v8::internal::compiler::WasmCompilationData::func_index, func_index_, v8::internal::wasm::WasmModule::function_was_validated(), v8::internal::wasm::WasmModule::functions, v8::internal::wasm::WireBytesStorage::GetCode(), v8::internal::wasm::GetWasmEngine(), v8::internal::is_shared, v8::internal::wasm::TypeDefinition::is_shared, v8::base::TimeTicks::IsHighResolution(), v8::internal::KB, v8::internal::wasm::kForDebugging, v8::internal::wasm::kLiftoff, v8::internal::wasm::kNone, v8::internal::wasm::kNotForDebugging, v8::internal::wasm::kTurbofan, v8::internal::wasm::CompilationEnv::module, v8::internal::wasm::WasmModule::num_imported_functions, v8::internal::wasm::WireBytesRef::offset(), v8::internal::wasm::WasmModule::origin, v8::internal::PrintF(), v8::base::internal::result, SELECT_WASM_COUNTER, v8::internal::wasm::WasmModule::set_function_validated(), v8::internal::wasm::WasmFunction::sig, v8::internal::wasm::WasmFunction::sig_index, tier_, v8::internal::wasm::WasmModule::type(), v8::internal::UNREACHABLE(), v8::internal::v8_flags, V8_LIKELY, V8_UNLIKELY, v8::internal::wasm::ValidateFunctionBody(), v8::internal::compiler::WasmCompilationData::wire_bytes_storage, and ZONE_NAME.
Referenced by CompileWasmFunction().
for_debugging()
ForDebugging v8::internal::wasm::WasmCompilationUnit::for_debugging () const [inline]
Definition at line 109 of file function-compiler.h.
{ return for_debugging_; }
func_index()
int v8::internal::wasm::WasmCompilationUnit::func_index () const [inline]
Definition at line 110 of file function-compiler.h.
{ return func_index_; }
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::GetCompilationEventName().
tier()
ExecutionTier v8::internal::wasm::WasmCompilationUnit::tier () const [inline]
Definition at line 108 of file function-compiler.h.
{ return tier_; }
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::GetCompilationEventName().
Member Data Documentation
for_debugging_
ForDebugging v8::internal::wasm::WasmCompilationUnit::for_debugging_ [private]
Definition at line 119 of file function-compiler.h.
Referenced by ExecuteCompilation().
func_index_
int v8::internal::wasm::WasmCompilationUnit::func_index_ [private]
Definition at line 117 of file function-compiler.h.
Referenced by ExecuteCompilation().
tier_
ExecutionTier v8::internal::wasm::WasmCompilationUnit::tier_ [private]
Definition at line 118 of file function-compiler.h.
Referenced by ExecuteCompilation().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/function-compiler.h
/mnt/V8SourceCode/src/wasm/function-compiler.cc