v8::internal::TaggedArrayBase< Derived, ShapeT, Super > Class Template Reference
#include <fixed-array.h>
Public Types
using Header = detail::TaggedArrayHeader< ShapeT, Super >
using Shape = ShapeT
Public Member Functions
Tagged< ElementT > get (int index) const
Tagged< ElementT > get (int index, RelaxedLoadTag) const
Tagged< ElementT > get (int index, AcquireLoadTag) const
Tagged< ElementT > get (int index, SeqCstAccessTag) const
void set (int index, Tagged< ElementT > value, WriteBarrierMode mode=kDefaultMode)
template<typename T = ElementT, typename = std::enable_if<kSupportsSmiElements<T>>>
void set (int index, Tagged< Smi > value)
void set (int index, Tagged< ElementT > value, RelaxedStoreTag, WriteBarrierMode mode=kDefaultMode)
template<typename T = ElementT, typename = std::enable_if<kSupportsSmiElements<T>>>
void set (int index, Tagged< Smi > value, RelaxedStoreTag)
void set (int index, Tagged< ElementT > value, ReleaseStoreTag, WriteBarrierMode mode=kDefaultMode)
template<typename T = ElementT, typename = std::enable_if<kSupportsSmiElements<T>>>
void set (int index, Tagged< Smi > value, ReleaseStoreTag)
void set (int index, Tagged< ElementT > value, SeqCstAccessTag, WriteBarrierMode mode=kDefaultMode)
template<typename T = ElementT, typename = std::enable_if<kSupportsSmiElements<T>>>
void set (int index, Tagged< Smi > value, SeqCstAccessTag)
Tagged< ElementT > swap (int index, Tagged< ElementT > value, SeqCstAccessTag, WriteBarrierMode mode=kDefaultMode)
Tagged< ElementT > compare_and_swap (int index, Tagged< ElementT > expected, Tagged< ElementT > value, SeqCstAccessTag, WriteBarrierMode mode=kDefaultMode)
void RightTrim (Isolate *isolate, int new_capacity)
int AllocatedSize () const
SlotType RawFieldOfFirstElement () const
SlotType RawFieldOfElementAt (int index) const
template<class IsolateT >
Handle< D > Allocate (IsolateT *isolate, int capacity, std::optional< DisallowGarbageCollection > *no_gc_out, AllocationType allocation)
Static Public Member Functions
static void MoveElements (Isolate *isolate, Tagged< Derived > dst, int dst_index, Tagged< Derived > src, int src_index, int len, WriteBarrierMode mode=kDefaultMode)
static void CopyElements (Isolate *isolate, Tagged< Derived > dst, int dst_index, Tagged< Derived > src, int src_index, int len, WriteBarrierMode mode=kDefaultMode)
static constexpr int SizeFor (int capacity)
static constexpr int OffsetOfElementAt (int index)
Static Public Attributes
static constexpr bool kElementsAreMaybeObject = is_maybe_weak_v<ElementT>
static constexpr int kElementSize = kTaggedSize
static constexpr int kMaxCapacity = kMaxFixedArrayCapacity
static constexpr int kMaxRegularCapacity
Protected Member Functions
bool IsInBounds (int index) const
bool IsCowArray () const
FLEXIBLE_ARRAY_MEMBER (ElementMemberT, objects)
Static Protected Member Functions
template<class IsolateT >
static Handle< Derived > Allocate (IsolateT *isolate, int capacity, std::optional< DisallowGarbageCollection > *no_gc_out, AllocationType allocation=AllocationType::kYoung)
static constexpr int NewCapacityForIndex (int index, int old_capacity)
Private Types
using ElementT = typename ShapeT::ElementT
using ElementMemberT = TaggedMember< ElementT, typename ShapeT::CompressionScheme >
using SlotType = std::conditional_t< kElementsAreMaybeObject, MaybeObjectSlot, ObjectSlot >
Static Private Attributes
template<typename ElementT >
static constexpr bool kSupportsSmiElements
static constexpr WriteBarrierMode kDefaultMode
Detailed Description
template<class Derived, class ShapeT, class Super = HeapObjectLayout>
class v8::internal::TaggedArrayBase< Derived, ShapeT, Super >
Definition at line 95 of file fixed-array.h.
Member Typedef Documentation
ElementMemberT
template<class Derived , class ShapeT , class Super = HeapObjectLayout>
using v8::internal::TaggedArrayBase< Derived, ShapeT, Super >::ElementMemberT = TaggedMember<ElementT, typename ShapeT::CompressionScheme> [private]
Definition at line 102 of file fixed-array.h.
ElementT
template<class Derived , class ShapeT , class Super = HeapObjectLayout>
using v8::internal::TaggedArrayBase< Derived, ShapeT, Super >::ElementT = typename ShapeT::ElementT [private]
Definition at line 97 of file fixed-array.h.
Header
template<class Derived , class ShapeT , class Super = HeapObjectLayout>
using v8::internal::TaggedArrayBase< Derived, ShapeT, Super >::Header = detail::TaggedArrayHeader<ShapeT, Super>
Definition at line 113 of file fixed-array.h.
Shape
template<class Derived , class ShapeT , class Super = HeapObjectLayout>
using v8::internal::TaggedArrayBase< Derived, ShapeT, Super >::Shape = ShapeT
Definition at line 122 of file fixed-array.h.
SlotType
template<class Derived , class ShapeT , class Super = HeapObjectLayout>
using v8::internal::TaggedArrayBase< Derived, ShapeT, Super >::SlotType = std::conditional_t<kElementsAreMaybeObject, MaybeObjectSlot, ObjectSlot> [private]
Definition at line 118 of file fixed-array.h.
Member Function Documentation
Allocate() [1/2]
template<class Derived , class ShapeT , class Super = HeapObjectLayout>
template<class IsolateT >
Handle<D> v8::internal::TaggedArrayBase< Derived, ShapeT, Super >::Allocate (IsolateT * isolate, int capacity, std::optional< DisallowGarbageCollection > * no_gc_out, AllocationType allocation)
Definition at line 357 of file fixed-array-inl.h.
                               {
  // Note 0-capacity is explicitly allowed since not all subtypes can be
  // assumed to have canonical 0-capacity instances.
  DCHECK_GE(capacity, 0);
  DCHECK_LE(capacity, kMaxCapacity);
  DCHECK(!no_gc_out->has_value());
  Tagged<D> xs = UncheckedCast<D>(
      isolate->factory()->AllocateRawArray(SizeFor(capacity), allocation));
  ReadOnlyRoots roots{isolate};
  if (DEBUG_BOOL) no_gc_out->emplace();
  Tagged<Map> map = Cast<Map>(roots.object_at(S::kMapRootIndex));
  DCHECK(ReadOnlyHeap::Contains(map));
  xs->set_map_after_allocation(isolate, map, SKIP_WRITE_BARRIER);
  xs->set_capacity(capacity);
  return handle(xs, isolate);
}
References v8::internal::ReadOnlyHeap::Contains(), v8::internal::DCHECK(), DCHECK_GE, DCHECK_LE, DEBUG_BOOL, v8::internal::handle(), and v8::internal::SKIP_WRITE_BARRIER.
Allocate() [2/2]
template<class Derived , class ShapeT , class Super = HeapObjectLayout>
template<class IsolateT >
static Handle<Derived> v8::internal::TaggedArrayBase< Derived, ShapeT, Super >::Allocate (IsolateT * isolate, int capacity, std::optional< DisallowGarbageCollection > * no_gc_out, AllocationType allocation = AllocationType::kYoung) [static], [protected]
AllocatedSize()
template<class D , class S , class P >
int v8::internal::TaggedArrayBase< D, S, P >::AllocatedSize [inline]
Definition at line 273 of file fixed-array-inl.h.
                                                  {
  return SizeFor(this->capacity(kAcquireLoad));
}
References v8::kAcquireLoad.
compare_and_swap()
template<class D , class S , class P >
Tagged< typename TaggedArrayBase< D, S, P >::ElementT > v8::internal::TaggedArrayBase< D, S, P >::compare_and_swap (int index, Tagged< ElementT > expected, Tagged< ElementT > value, SeqCstAccessTag , WriteBarrierMode mode = kDefaultMode) [inline]
Definition at line 213 of file fixed-array-inl.h.
                                                                  {
  DCHECK(!IsCowArray());
  DCHECK(IsInBounds(index));
  return objects()[index].SeqCst_CompareAndSwap(this, expected, value, mode);
}
References v8::internal::DCHECK(), v8::internal::index, mode(), and v8::internal::value.
CopyElements()
template<class Derived , class ShapeT , class Super = HeapObjectLayout>
void v8::internal::TaggedArrayBase< D, S, P >::CopyElements (Isolate * isolate, Tagged< Derived > dst, int dst_index, Tagged< Derived > src, int src_index, int len, WriteBarrierMode mode = kDefaultMode) [inline], [static]
Definition at line 242 of file fixed-array-inl.h.
                                                                   {
  if (len == 0) return;
  DCHECK_GE(len, 0);
  DCHECK(dst->IsInBounds(dst_index));
  DCHECK_LE(dst_index + len, dst->capacity());
  DCHECK(src->IsInBounds(src_index));
  DCHECK_LE(src_index + len, src->capacity());
  DisallowGarbageCollection no_gc;
  SlotType dst_slot(&dst->objects()[dst_index]);
  SlotType src_slot(&src->objects()[src_index]);
  isolate->heap()->CopyRange(dst, dst_slot, src_slot, len, mode);
}
References v8::internal::Heap::CopyRange(), v8::internal::DCHECK(), DCHECK_GE, DCHECK_LE, v8::internal::Isolate::heap(), mode(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
FLEXIBLE_ARRAY_MEMBER()
template<class Derived , class ShapeT , class Super = HeapObjectLayout>
v8::internal::TaggedArrayBase< Derived, ShapeT, Super >::FLEXIBLE_ARRAY_MEMBER (ElementMemberT , objects) [protected]
get() [1/4]
template<class D , class S , class P >
Tagged< typename TaggedArrayBase< D, S, P >::ElementT > v8::internal::TaggedArrayBase< D, S, P >::get (int index) const [inline]
Definition at line 115 of file fixed-array-inl.h.
                                             {
  DCHECK(IsInBounds(index));
  // TODO(jgruber): This tag-less overload shouldn't be relaxed.
  return objects()[index].Relaxed_Load();
}
References v8::internal::DCHECK(), and v8::internal::index.
get() [2/4]
template<class D , class S , class P >
Tagged< typename TaggedArrayBase< D, S, P >::ElementT > v8::internal::TaggedArrayBase< D, S, P >::get (int index, AcquireLoadTag) const [inline]
Definition at line 130 of file fixed-array-inl.h.
                                                             {
  DCHECK(IsInBounds(index));
  return objects()[index].Acquire_Load();
}
References v8::internal::DCHECK(), and v8::internal::index.
get() [3/4]
template<class D , class S , class P >
Tagged< typename TaggedArrayBase< D, S, P >::ElementT > v8::internal::TaggedArrayBase< D, S, P >::get (int index, RelaxedLoadTag) const [inline]
Definition at line 123 of file fixed-array-inl.h.
                                                             {
  DCHECK(IsInBounds(index));
  return objects()[index].Relaxed_Load();
}
get() [4/4]
template<class D , class S , class P >
Tagged< typename TaggedArrayBase< D, S, P >::ElementT > v8::internal::TaggedArrayBase< D, S, P >::get (int index, SeqCstAccessTag) const [inline]
Definition at line 137 of file fixed-array-inl.h.
                                                              {
  DCHECK(IsInBounds(index));
  return objects()[index].SeqCst_Load();
}
IsCowArray()
template<class D , class S , class P >
bool v8::internal::TaggedArrayBase< D, S, P >::IsCowArray [inline], [protected]
Definition at line 108 of file fixed-array-inl.h.
                                                {
  return this->map() ==
         this->EarlyGetReadOnlyRoots().unchecked_fixed_cow_array_map();
}
IsInBounds()
template<class D , class S , class P >
bool v8::internal::TaggedArrayBase< D, S, P >::IsInBounds (int index) const [inline], [protected]
Definition at line 103 of file fixed-array-inl.h.
                                                         {
  return static_cast<unsigned>(index) < static_cast<unsigned>(this->capacity());
}
References v8::internal::index.
MoveElements()
template<class Derived , class ShapeT , class Super = HeapObjectLayout>
void v8::internal::TaggedArrayBase< D, S, P >::MoveElements (Isolate * isolate, Tagged< Derived > dst, int dst_index, Tagged< Derived > src, int src_index, int len, WriteBarrierMode mode = kDefaultMode) [inline], [static]
Definition at line 223 of file fixed-array-inl.h.
                                                                   {
  if (len == 0) return;
  DCHECK_GE(len, 0);
  DCHECK(dst->IsInBounds(dst_index));
  DCHECK_LE(dst_index + len, dst->length());
  DCHECK(src->IsInBounds(src_index));
  DCHECK_LE(src_index + len, src->length());
  DisallowGarbageCollection no_gc;
  SlotType dst_slot(&dst->objects()[dst_index]);
  SlotType src_slot(&src->objects()[src_index]);
  isolate->heap()->MoveRange(dst, dst_slot, src_slot, len, mode);
}
References v8::internal::DCHECK(), DCHECK_GE, DCHECK_LE, v8::internal::Isolate::heap(), mode(), v8::internal::Heap::MoveRange(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
NewCapacityForIndex()
template<class D , class S , class P >
constexpr int v8::internal::TaggedArrayBase< D, S, P >::NewCapacityForIndex (int index, int old_capacity) [static], [constexpr], [protected]
Definition at line 383 of file fixed-array-inl.h.
                                                                              {
  DCHECK_GE(index, old_capacity);
  // Note this is currently based on JSObject::NewElementsCapacity.
  int capacity = old_capacity;
  do {
    capacity = capacity + (capacity >> 1) + 16;
  } while (capacity <= index);
  return capacity;
}
References DCHECK_GE, and v8::internal::index.
OffsetOfElementAt()
template<class Derived , class ShapeT , class Super = HeapObjectLayout>
static constexpr int v8::internal::TaggedArrayBase< Derived, ShapeT, Super >::OffsetOfElementAt (int index) [inline], [static], [constexpr]
Definition at line 176 of file fixed-array.h.
                                                           {
    return SizeFor(index);
  }
References v8::internal::index, and v8::internal::TaggedArrayBase< Derived, ShapeT, Super >::SizeFor().
RawFieldOfElementAt()
template<class D , class S , class P >
TaggedArrayBase< D, S, P >::SlotType v8::internal::TaggedArrayBase< D, S, P >::RawFieldOfElementAt (int index) const [inline]
Definition at line 285 of file fixed-array-inl.h.
                                                             {
  return SlotType(&objects()[index]);
}
References v8::internal::index.
RawFieldOfFirstElement()
template<class D , class S , class P >
TaggedArrayBase< D, S, P >::SlotType v8::internal::TaggedArrayBase< D, S, P >::RawFieldOfFirstElement [inline]
Definition at line 279 of file fixed-array-inl.h.
                                                       {
  return RawFieldOfElementAt(0);
}
RightTrim()
template<class D , class S , class P >
void v8::internal::TaggedArrayBase< D, S, P >::RightTrim (Isolate * isolate, int new_capacity) [inline]
Definition at line 261 of file fixed-array-inl.h.
                                                                           {
  int old_capacity = this->capacity();
  CHECK_GT(new_capacity, 0); // Due to possible canonicalization.
  CHECK_LE(new_capacity, old_capacity);
  if (new_capacity == old_capacity) return;
  isolate->heap()->RightTrimArray(Cast<D>(this), new_capacity, old_capacity);
}
References CHECK_GT, CHECK_LE, v8::internal::Isolate::heap(), and v8::internal::Heap::RightTrimArray().
set() [1/8]
template<class D , class S , class P >
void v8::internal::TaggedArrayBase< D, S, P >::set (int index, Tagged< ElementT > value, RelaxedStoreTag tag, WriteBarrierMode mode = kDefaultMode) [inline]
Definition at line 158 of file fixed-array-inl.h.
                                                                               {
  DCHECK(!IsCowArray());
  DCHECK(IsInBounds(index));
  objects()[index].Relaxed_Store(this, value, mode);
}
set() [2/8]
template<class D , class S , class P >
void v8::internal::TaggedArrayBase< D, S, P >::set (int index, Tagged< ElementT > value, ReleaseStoreTag tag, WriteBarrierMode mode = kDefaultMode) [inline]
Definition at line 173 of file fixed-array-inl.h.
                                                                               {
  DCHECK(!IsCowArray());
  DCHECK(IsInBounds(index));
  objects()[index].Release_Store(this, value, mode);
}
References v8::internal::DCHECK(), v8::internal::index, mode(), and v8::internal::value.
set() [3/8]
template<class D , class S , class P >
void v8::internal::TaggedArrayBase< D, S, P >::set (int index, Tagged< ElementT > value, SeqCstAccessTag tag, WriteBarrierMode mode = kDefaultMode) [inline]
Definition at line 188 of file fixed-array-inl.h.
                                                                               {
  DCHECK(!IsCowArray());
  DCHECK(IsInBounds(index));
  objects()[index].SeqCst_Store(this, value, mode);
}
References v8::internal::DCHECK(), v8::internal::index, mode(), and v8::internal::value.
set() [4/8]
template<class D , class S , class P >
void v8::internal::TaggedArrayBase< D, S, P >::set (int index, Tagged< ElementT > value, WriteBarrierMode mode = kDefaultMode) [inline]
Definition at line 143 of file fixed-array-inl.h.
                                                          {
  DCHECK(!IsCowArray());
  DCHECK(IsInBounds(index));
  // TODO(jgruber): This tag-less overload shouldn't be relaxed.
  objects()[index].Relaxed_Store(this, value, mode);
}
set() [5/8]
template<class D , class S , class P >
template<typename , typename >
void v8::internal::TaggedArrayBase< D, S, P >::set (int index, Tagged< Smi > value) [inline]
Definition at line 153 of file fixed-array-inl.h.
                                                               {
  set(index, value, SKIP_WRITE_BARRIER);
}
set() [6/8]
template<class D , class S , class P >
template<typename , typename >
void v8::internal::TaggedArrayBase< D, S, P >::set (int index, Tagged< Smi > value, RelaxedStoreTag tag) [inline]
Definition at line 167 of file fixed-array-inl.h.
                                                        {
  set(index, value, tag, SKIP_WRITE_BARRIER);
}
References v8::internal::index, v8::internal::SKIP_WRITE_BARRIER, and v8::internal::value.
set() [7/8]
template<class D , class S , class P >
template<typename , typename >
void v8::internal::TaggedArrayBase< D, S, P >::set (int index, Tagged< Smi > value, ReleaseStoreTag tag) [inline]
Definition at line 182 of file fixed-array-inl.h.
                                                        {
  set(index, value, tag, SKIP_WRITE_BARRIER);
}
set() [8/8]
template<class D , class S , class P >
template<typename , typename >
void v8::internal::TaggedArrayBase< D, S, P >::set (int index, Tagged< Smi > value, SeqCstAccessTag tag) [inline]
Definition at line 197 of file fixed-array-inl.h.
                                                        {
  set(index, value, tag, SKIP_WRITE_BARRIER);
}
References v8::internal::index, v8::internal::SKIP_WRITE_BARRIER, and v8::internal::value.
SizeFor()
template<class Derived , class ShapeT , class Super = HeapObjectLayout>
static constexpr int v8::internal::TaggedArrayBase< Derived, ShapeT, Super >::SizeFor (int capacity) [inline], [static], [constexpr]
Definition at line 173 of file fixed-array.h.
                                                    {
    return sizeof(Header) + capacity * kElementSize;
  }
References v8::internal::TaggedArrayBase< Derived, ShapeT, Super >::kElementSize.
Referenced by v8::internal::TaggedArrayBase< Derived, ShapeT, Super >::OffsetOfElementAt().
swap()
template<class D , class S , class P >
Tagged< typename TaggedArrayBase< D, S, P >::ElementT > v8::internal::TaggedArrayBase< D, S, P >::swap (int index, Tagged< ElementT > value, SeqCstAccessTag , WriteBarrierMode mode = kDefaultMode) [inline]
Definition at line 204 of file fixed-array-inl.h.
                                                                       {
  DCHECK(!IsCowArray());
  DCHECK(IsInBounds(index));
  return objects()[index].SeqCst_Swap(this, value, mode);
}
Member Data Documentation
kDefaultMode
template<class Derived , class ShapeT , class Super = HeapObjectLayout>
constexpr WriteBarrierMode v8::internal::TaggedArrayBase< Derived, ShapeT, Super >::kDefaultMode [static], [constexpr], [private]
Initial value:
=
      std::is_same_v<ElementT, Smi> ? SKIP_WRITE_BARRIER : UPDATE_WRITE_BARRIER
Definition at line 109 of file fixed-array.h.
kElementsAreMaybeObject
template<class Derived , class ShapeT , class Super = HeapObjectLayout>
constexpr bool v8::internal::TaggedArrayBase< Derived, ShapeT, Super >::kElementsAreMaybeObject = is_maybe_weak_v<ElementT> [static], [constexpr]
Definition at line 114 of file fixed-array.h.
kElementSize
template<class Derived , class ShapeT , class Super = HeapObjectLayout>
constexpr int v8::internal::TaggedArrayBase< Derived, ShapeT, Super >::kElementSize = kTaggedSize [static], [constexpr]
Definition at line 115 of file fixed-array.h.
Referenced by v8::internal::TaggedArrayBase< Derived, ShapeT, Super >::SizeFor().
kMaxCapacity
template<class Derived , class ShapeT , class Super = HeapObjectLayout>
constexpr int v8::internal::TaggedArrayBase< Derived, ShapeT, Super >::kMaxCapacity = kMaxFixedArrayCapacity [static], [constexpr]
Definition at line 187 of file fixed-array.h.
kMaxRegularCapacity
template<class Derived , class ShapeT , class Super = HeapObjectLayout>
constexpr int v8::internal::TaggedArrayBase< Derived, ShapeT, Super >::kMaxRegularCapacity [static], [constexpr]
Initial value:
=
      (kMaxRegularHeapObjectSize - sizeof(Header)) / kElementSize
Definition at line 191 of file fixed-array.h.
kSupportsSmiElements
template<class Derived , class ShapeT , class Super = HeapObjectLayout>
template<typename ElementT >
constexpr bool v8::internal::TaggedArrayBase< Derived, ShapeT, Super >::kSupportsSmiElements [static], [constexpr], [private]
Initial value:
=
      std::is_convertible_v<Smi, ElementT>
Definition at line 106 of file fixed-array.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/fixed-array.h
/mnt/V8SourceCode/src/objects/fixed-array-inl.h