v8::PredictablePlatform Class Reference
Public Member Functions
PredictablePlatform (std::unique_ptr< Platform > platform)
PredictablePlatform (const PredictablePlatform &)=delete
PredictablePlatform & operator= (const PredictablePlatform &)=delete
PageAllocator * GetPageAllocator () override
Allows the embedder to manage memory page allocations.
void OnCriticalMemoryPressure () override
Enables the embedder to respond in cases where V8 can't allocate large blocks of memory.
std::shared_ptr< TaskRunner > GetForegroundTaskRunner (v8::Isolate *isolate, TaskPriority priority) override
Returns a TaskRunner with a specific |priority| which can be used to post a task on the foreground thread.
int NumberOfWorkerThreads () override
Gets the max number of worker threads that may be used to execute concurrent work scheduled for any single TaskPriority by Call(BlockingTask)OnWorkerThread() or PostJob().
void PostTaskOnWorkerThreadImpl (TaskPriority priority, std::unique_ptr< Task > task, const SourceLocation &location) override
Schedules a task with |priority| to be invoked on a worker thread.
void PostDelayedTaskOnWorkerThreadImpl (TaskPriority priority, std::unique_ptr< Task > task, double delay_in_seconds, const SourceLocation &location) override
Schedules a task with |priority| to be invoked on a worker thread after |delay_in_seconds| expires.
bool IdleTasksEnabled (Isolate *isolate) override
Returns true if idle tasks are enabled for the given |isolate|.
std::unique_ptr< JobHandle > CreateJobImpl (TaskPriority priority, std::unique_ptr< JobTask > job_task, const SourceLocation &location) override
Creates and returns a JobHandle associated with a Job.
double MonotonicallyIncreasingTime () override
Monotonically increasing time in seconds from an arbitrary fixed point in the past.
double CurrentClockTimeMillis () override
This function is deprecated and will be deleted.
v8::TracingController * GetTracingController () override
Returns an instance of a v8::TracingController.
v8::ThreadIsolatedAllocator * GetThreadIsolatedAllocator () override
Allows the embedder to provide an allocator that uses per-thread memory permissions to protect allocations.
Platform * platform () const
Private Attributes
std::atomic< uint64_t > synthetic_time_ {0}
std::unique_ptr< Platform > platform_
Additional Inherited Members
Detailed Description
Definition at line 21 of file d8-platforms.cc.
Constructor & Destructor Documentation
PredictablePlatform() [1/2]
v8::PredictablePlatform::PredictablePlatform (std::unique_ptr< Platform > platform) [inline], [explicit]
Definition at line 23 of file d8-platforms.cc.
      : platform_(std::move(platform)) {
    DCHECK_NOT_NULL(platform_);
  }
References DCHECK_NOT_NULL, and platform_.
PredictablePlatform() [2/2]
v8::PredictablePlatform::PredictablePlatform (const PredictablePlatform &) [delete]
Member Function Documentation
CreateJobImpl()
std::unique_ptr<JobHandle> v8::PredictablePlatform::CreateJobImpl (TaskPriority priority, std::unique_ptr< JobTask > job_task, const SourceLocation & location) [inline], [override], [virtual]
Creates and returns a JobHandle associated with a Job.
Implements v8::Platform.
Definition at line 77 of file d8-platforms.cc.
                                               {
    // Do not call {platform_->PostJob} here, as this would create a job that
    // posts tasks directly to the underlying default platform.
    return platform::NewDefaultJobHandle(this, priority, std::move(job_task),
                                         NumberOfWorkerThreads());
  }
References v8::platform::NewDefaultJobHandle(), and NumberOfWorkerThreads().
CurrentClockTimeMillis()
double v8::PredictablePlatform::CurrentClockTimeMillis () [inline], [override], [virtual]
This function is deprecated and will be deleted.
Use either CurrentClockTimeMilliseconds() or CurrentClockTimeMillisecondsHighResolution().
Implements v8::Platform.
Definition at line 97 of file d8-platforms.cc.
                                           {
    return MonotonicallyIncreasingTime() * base::Time::kMillisecondsPerSecond;
  }
References v8::base::TimeConstants::kMillisecondsPerSecond, and MonotonicallyIncreasingTime().
GetForegroundTaskRunner()
std::shared_ptr<TaskRunner> v8::PredictablePlatform::GetForegroundTaskRunner (v8::Isolate * isolate, TaskPriority priority) [inline], [override], [virtual]
Returns a TaskRunner with a specific |priority| which can be used to post a task on the foreground thread.
The TaskRunner's NonNestableTasksEnabled() must be true. This function should only be called from a foreground thread.
Implements v8::Platform.
Definition at line 39 of file d8-platforms.cc.
                                                          {
    return platform_->GetForegroundTaskRunner(isolate, priority);
  }
References platform_.
GetPageAllocator()
PageAllocator* v8::PredictablePlatform::GetPageAllocator () [inline], [override], [virtual]
Allows the embedder to manage memory page allocations.
Returning nullptr will cause V8 to use the default page allocator.
Reimplemented from v8::Platform.
Definition at line 31 of file d8-platforms.cc.
                                             {
    return platform_->GetPageAllocator();
  }
References platform_.
GetThreadIsolatedAllocator()
v8::ThreadIsolatedAllocator* v8::PredictablePlatform::GetThreadIsolatedAllocator () [inline], [override], [virtual]
Allows the embedder to provide an allocator that uses per-thread memory permissions to protect allocations.
Returning nullptr will cause V8 to disable protections that rely on this feature.
Reimplemented from v8::Platform.
Definition at line 105 of file d8-platforms.cc.
                                                                   {
    return platform_->GetThreadIsolatedAllocator();
  }
References platform_.
GetTracingController()
v8::TracingController* v8::PredictablePlatform::GetTracingController () [inline], [override], [virtual]
Returns an instance of a v8::TracingController.
This must be non-nullptr.
Implements v8::Platform.
Definition at line 101 of file d8-platforms.cc.
                                                       {
    return platform_->GetTracingController();
  }
References platform_.
IdleTasksEnabled()
bool v8::PredictablePlatform::IdleTasksEnabled (Isolate * isolate) [inline], [override], [virtual]
Returns true if idle tasks are enabled for the given |isolate|.
Reimplemented from v8::Platform.
Definition at line 75 of file d8-platforms.cc.
{ return false; }
MonotonicallyIncreasingTime()
double v8::PredictablePlatform::MonotonicallyIncreasingTime () [inline], [override], [virtual]
Monotonically increasing time in seconds from an arbitrary fixed point in the past.
This function is expected to return at least millisecond-precision values. For this reason, it is recommended that the fixed point be no further in the past than the epoch.
Implements v8::Platform.
Definition at line 86 of file d8-platforms.cc.
                                                {
    // In predictable mode, there should be no (observable) concurrency, but we
    // still run some tests that explicitly specify '--predictable' in the
    // '--isolates' variant, where several threads run the same test in
    // different isolates. To avoid TSan issues in that scenario we use atomic
    // increments here.
    uint64_t synthetic_time =
        synthetic_time_.fetch_add(1, std::memory_order_relaxed);
    return 1e-5 * synthetic_time;
  }
References synthetic_time_.
Referenced by CurrentClockTimeMillis().
NumberOfWorkerThreads()
int v8::PredictablePlatform::NumberOfWorkerThreads () [inline], [override], [virtual]
Gets the max number of worker threads that may be used to execute concurrent work scheduled for any single TaskPriority by Call(BlockingTask)OnWorkerThread() or PostJob().
This can be used to estimate the number of tasks a work package should be split into. A return value of 0 means that there are no worker threads available. Note that a value of 0 won't prohibit V8 from posting tasks using |CallOnWorkerThread|.
Implements v8::Platform.
Definition at line 44 of file d8-platforms.cc.
                                       {
    // The predictable platform executes everything on the main thread, but we
    // still pretend to have the default number of worker threads to not
    // unnecessarily change behaviour of the platform.
    return platform_->NumberOfWorkerThreads();
  }
References platform_.
Referenced by CreateJobImpl().
OnCriticalMemoryPressure()
void v8::PredictablePlatform::OnCriticalMemoryPressure () [inline], [override], [virtual]
Enables the embedder to respond in cases where V8 can't allocate large blocks of memory.
V8 retries the failed allocation once after calling this method. On success, execution continues; otherwise V8 exits with a fatal error. Embedder overrides of this function must NOT call back into V8.
Reimplemented from v8::Platform.
Definition at line 35 of file d8-platforms.cc.
                                           {
    platform_->OnCriticalMemoryPressure();
  }
References platform_.
operator=()
PredictablePlatform& v8::PredictablePlatform::operator= (const PredictablePlatform &) [delete]
platform()
Platform* v8::PredictablePlatform::platform () const [inline]
Definition at line 109 of file d8-platforms.cc.
{ return platform_.get(); }
References platform_.
PostDelayedTaskOnWorkerThreadImpl()
void v8::PredictablePlatform::PostDelayedTaskOnWorkerThreadImpl (TaskPriority priority, std::unique_ptr< Task > task, double delay_in_seconds, const SourceLocation & location) [inline], [override], [virtual]
Schedules a task with |priority| to be invoked on a worker thread after |delay_in_seconds| expires.
Implements v8::Platform.
Definition at line 69 of file d8-platforms.cc.
                                                                        {
    // Never run delayed tasks.
  }
PostTaskOnWorkerThreadImpl()
void v8::PredictablePlatform::PostTaskOnWorkerThreadImpl (TaskPriority priority, std::unique_ptr< Task > task, const SourceLocation & location) [inline], [override], [virtual]
Schedules a task with |priority| to be invoked on a worker thread.
Implements v8::Platform.
Definition at line 51 of file d8-platforms.cc.
                                                                           {
    // We post worker tasks on the foreground task runner of the
    // {kProcessGlobalPredictablePlatformWorkerTaskQueue} isolate. The task
    // queue of the {kProcessGlobalPredictablePlatformWorkerTaskQueue} isolate
    // is then executed on the main thread to achieve predictable behavior.
    //
    // In this context here it is okay to call {GetForegroundTaskRunner} from a
    // background thread. The reason is that code is executed sequentially with
    // the PredictablePlatform, and that the {DefaultPlatform} does not access
    // the isolate but only uses it as the key in a HashMap.
    platform_
        ->GetForegroundTaskRunner(
            kProcessGlobalPredictablePlatformWorkerTaskQueue, priority)
        ->PostTask(std::move(task));
  }
References v8::kProcessGlobalPredictablePlatformWorkerTaskQueue, and platform_.
Member Data Documentation
platform_
std::unique_ptr<Platform> v8::PredictablePlatform::platform_ [private]
Definition at line 113 of file d8-platforms.cc.
Referenced by GetForegroundTaskRunner(), GetPageAllocator(), GetThreadIsolatedAllocator(), GetTracingController(), NumberOfWorkerThreads(), OnCriticalMemoryPressure(), platform(), PostTaskOnWorkerThreadImpl(), and PredictablePlatform().
synthetic_time_
std::atomic<uint64_t> v8::PredictablePlatform::synthetic_time_ {0} [private]
Definition at line 112 of file d8-platforms.cc.
Referenced by MonotonicallyIncreasingTime().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/d8/d8-platforms.cc