v8::Uint32 Class Reference
A JavaScript value representing a 32-bit unsigned integer.
#include <v8-primitive.h>
Public Member Functions
uint32_t Value () const
Static Public Member Functions
static Uint32 * Cast (v8::Data *data)
Private Member Functions
Uint32 ()
Static Private Member Functions
static void CheckCast (v8::Data *that)
Detailed Description
A JavaScript value representing a 32-bit unsigned integer.
Definition at line 905 of file v8-primitive.h.
Constructor & Destructor Documentation
Uint32()
v8::Uint32::Uint32 () [private]
Member Function Documentation
Cast()
static Uint32* v8::Uint32::Cast (v8::Data * data) [inline], [static]
Definition at line 908 of file v8-primitive.h.
                                              {
#ifdef V8_ENABLE_CHECKS
    CheckCast(data);
#endif
    return static_cast<Uint32*>(data);
  }
CheckCast()
void v8::Uint32::CheckCast (v8::Data * that) [static], [private]
Definition at line 3945 of file api.cc.
                                     {
  Utils::ApiCheck(Value::Cast(that)->IsUint32(), "v8::Uint32::Cast",
                  "Value is not a 32-bit unsigned integer");
}
References v8::Utils::ApiCheck(), and v8::Value::Cast().
Value()
uint32_t v8::Uint32::Value () const
Definition at line 6210 of file api.cc.
                             {
  auto obj = *Utils::OpenDirectHandle(this);
  if (i::IsSmi(obj)) {
    return i::Smi::ToInt(obj);
  } else {
    return static_cast<uint32_t>(i::Object::NumberValue(obj));
  }
}
References v8::internal::IsSmi(), v8::internal::Object::NumberValue(), v8::Utils::OpenDirectHandle(), and v8::internal::Smi::ToInt().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-primitive.h
/mnt/V8SourceCode/src/api/api.cc