v8::internal::wasm::TransitiveTypeFeedbackProcessor Class Reference
Static Public Member Functions
static void Process (Isolate *isolate, Tagged< WasmTrustedInstanceData > trusted_instance_data, int func_index)
Private Member Functions
TransitiveTypeFeedbackProcessor (Isolate *isolate, Tagged< WasmTrustedInstanceData > trusted_instance_data, int func_index)
~TransitiveTypeFeedbackProcessor ()
void ProcessQueue ()
void ProcessFunction (int func_index)
void EnqueueCallees (base::Vector< CallSiteFeedback > feedback)
Private Attributes
DisallowGarbageCollection no_gc_scope_
Isolate *const isolate_
const Tagged< WasmTrustedInstanceData > instance_data_
const WasmModule *const module_
base::MutexGuard mutex_guard
std::unordered_map< uint32_t, FunctionTypeFeedback > & feedback_for_function_
std::set< int > queue_
Detailed Description
Definition at line 1286 of file module-compiler.cc.
Constructor & Destructor Documentation
TransitiveTypeFeedbackProcessor()
v8::internal::wasm::TransitiveTypeFeedbackProcessor::TransitiveTypeFeedbackProcessor (Isolate * isolate, Tagged< WasmTrustedInstanceData > trusted_instance_data, int func_index) [inline], [private]
Definition at line 1296 of file module-compiler.cc.
      : isolate_(isolate),
        instance_data_(trusted_instance_data),
        module_(trusted_instance_data->module()),
        mutex_guard(&module_->type_feedback.mutex),
        feedback_for_function_(module_->type_feedback.feedback_for_function) {
    queue_.insert(func_index);
  }
References queue_.
 TransitiveTypeFeedbackProcessor()
v8::internal::wasm::TransitiveTypeFeedbackProcessor::~TransitiveTypeFeedbackProcessor () [inline], [private]
Definition at line 1307 of file module-compiler.cc.
{ DCHECK(queue_.empty()); }
References v8::internal::DCHECK(), and queue_.
Member Function Documentation
EnqueueCallees()
void v8::internal::wasm::TransitiveTypeFeedbackProcessor::EnqueueCallees (base::Vector< CallSiteFeedback > feedback) [inline], [private]
Definition at line 1319 of file module-compiler.cc.
                                                             {
    for (const CallSiteFeedback& csf : feedback) {
      for (int j = 0; j < csf.num_cases(); j++) {
        int func = csf.function_index(j);
        // Don't spend time on calls that have never been executed.
        if (csf.call_count(j) == 0) continue;
        // Don't recompute feedback that has already been processed.
        auto existing = feedback_for_function_.find(func);
        if (existing != feedback_for_function_.end() &&
            !existing->second.feedback_vector.empty()) {
          if (!existing->second.needs_reprocessing_after_deopt) {
            continue;
          }
          DCHECK(v8_flags.wasm_deopt);
          existing->second.needs_reprocessing_after_deopt = false;
        }
        queue_.insert(func);
      }
    }
  }
References v8::internal::DCHECK(), feedback_for_function_, queue_, and v8::internal::v8_flags.
Referenced by ProcessFunction().
Process()
static void v8::internal::wasm::TransitiveTypeFeedbackProcessor::Process (Isolate * isolate, Tagged< WasmTrustedInstanceData > trusted_instance_data, int func_index) [inline], [static]
Definition at line 1288 of file module-compiler.cc.
                                      {
    TransitiveTypeFeedbackProcessor{isolate, trusted_instance_data, func_index}
        .ProcessQueue();
  }
Referenced by v8::internal::wasm::TierUpNowForTesting(), and v8::internal::wasm::TriggerTierUp().
ProcessFunction()
void v8::internal::wasm::TransitiveTypeFeedbackProcessor::ProcessFunction (int func_index) [private]
Definition at line 1516 of file module-compiler.cc.
                                                                    {
  int which_vector = declared_function_index(module_, func_index);
  Tagged<Object> maybe_feedback =
      instance_data_->feedback_vectors()->get(which_vector);
  if (!IsFixedArray(maybe_feedback)) return;
  Tagged<FixedArray> feedback = Cast<FixedArray>(maybe_feedback);
  base::Vector<uint32_t> call_targets =
      module_->type_feedback.feedback_for_function[func_index]
          .call_targets.as_vector();
  // For each entry in {call_targets}, there are two {Object} slots in the
  // {feedback} vector:
  // +--------------------------+-----------------------------+----------------+
  // | Call Type | Feedback: Entry 1 | Entry 2 |
  // +-------------------------+------------------------------+----------------+
  // | direct | Smi(count) | Smi(0), unused |
  // +--------------------------+-----------------------------+----------------+
  // | ref, uninitialized | Smi(0) | Smi(0) |
  // | ref, monomorphic | WasmFuncRef(target) | Smi(count>0) |
  // | ref, polymorphic | FixedArray | Undefined |
  // | ref, megamorphic | MegamorphicSymbol | Undefined |
  // +--------------------------+-----------------------------+----------------+
  // | indirect, uninitialized | Smi(0) | Smi(0) |
  // | indirect, monomorphic | Smi(truncated_target) | Smi(count>0) |
  // | indirect, wrong instance | WasmCrossInstanceCallSymbol | Smi(count>0) |
  // | indirect, polymorphic | FixedArray | Undefined |
  // | indirect, megamorphic | MegamorphicSymbol | Undefined |
  // +--------------------------+-----------------------------+----------------+
  // The FixedArray entries for the polymorphic cases look like the monomorphic
  // entries in the feedback vector itself, i.e., they can a (truncated) target,
  // or the wrong instance sentinel (for cross-instance call_indirect).
  // See {UpdateCallRefOrIndirectIC} in {wasm.tq} for how this is written.
  // Since this is combining untrusted data ({feedback} vector on the JS heap)
  // with trusted data ({call_targets}), make sure to avoid an OOB access.
  int checked_feedback_length = feedback->length();
  SBXCHECK_EQ(checked_feedback_length, call_targets.size() * 2);
  FeedbackMaker fm(isolate_, instance_data_, func_index,
                   checked_feedback_length / 2);
  for (int i = 0; i < checked_feedback_length; i += 2) {
    uint32_t sentinel_or_target = call_targets[i / 2];
    Tagged<Object> first_slot = feedback->get(i);
    Tagged<Object> second_slot = feedback->get(i + 1);
    if (sentinel_or_target != FunctionTypeFeedback::kCallRef &&
        sentinel_or_target != FunctionTypeFeedback::kCallIndirect) {
      // Direct call counts.
      int count = Smi::ToInt(first_slot);
      DCHECK_EQ(Smi::ToInt(second_slot), 0);
      // TODO(dlehmann): Currently, TurboFan assumes that we add feedback even
      // if the call count is zero. Once TurboFan is gone, revisit if we can
      // avoid this (similar to how we do for call_ref/call_indirect today).
      fm.AddCall(static_cast<int>(sentinel_or_target), count);
    } else if (IsSmi(second_slot) && Smi::ToInt(second_slot) == 0) {
      // Uninitialized call_ref or call_indirect.
      DCHECK_EQ(Smi::ToInt(first_slot), 0);
      if (v8_flags.trace_wasm_inlining) {
        PrintF("[function %d: call #%d: uninitialized]\n", func_index, i / 2);
      }
    } else if (IsWasmFuncRef(first_slot)) {
      // Monomorphic call_ref.
      DCHECK_EQ(sentinel_or_target, FunctionTypeFeedback::kCallRef);
      int count = Smi::ToInt(second_slot);
      fm.AddCallRefCandidate(Cast<WasmFuncRef>(first_slot), count);
    } else if (IsSmi(first_slot) || IsCrossInstanceCall(first_slot, isolate_)) {
      // Monomorphic call_indirect.
      DCHECK_EQ(sentinel_or_target, FunctionTypeFeedback::kCallIndirect);
      int count = Smi::ToInt(second_slot);
      fm.AddCallIndirectCandidate(first_slot, count);
    } else if (IsFixedArray(first_slot)) {
      // Polymorphic call_ref or call_indirect.
      Tagged<FixedArray> polymorphic = Cast<FixedArray>(first_slot);
      DCHECK(IsUndefined(second_slot));
      int checked_polymorphic_length = polymorphic->length();
      SBXCHECK_LE(checked_polymorphic_length, 2 * kMaxPolymorphism);
      if (sentinel_or_target == FunctionTypeFeedback::kCallRef) {
        for (int j = 0; j < checked_polymorphic_length; j += 2) {
          Tagged<WasmFuncRef> target = Cast<WasmFuncRef>(polymorphic->get(j));
          int count = Smi::ToInt(polymorphic->get(j + 1));
          fm.AddCallRefCandidate(target, count);
        }
      } else {
        DCHECK_EQ(sentinel_or_target, FunctionTypeFeedback::kCallIndirect);
        for (int j = 0; j < checked_polymorphic_length; j += 2) {
          Tagged<Object> target = polymorphic->get(j);
          int count = Smi::ToInt(polymorphic->get(j + 1));
          fm.AddCallIndirectCandidate(target, count);
        }
      }
    } else if (first_slot == ReadOnlyRoots{isolate_}.megamorphic_symbol()) {
      DCHECK(IsUndefined(second_slot));
      fm.set_megamorphic();
    } else {
      UNREACHABLE();
    }
    if (v8_flags.wasm_deopt &&
        first_slot != ReadOnlyRoots{isolate_}.megamorphic_symbol()) {
      // If we already had feedback for this call, also add the already existing
      // feedback to prevent deopt loops where two different instantiations
      // (which have their own on-heap feedback vector) to "flip-flop" between
      // their inlining decisions potentially causing deopt loops.
      const base::OwnedVector<CallSiteFeedback>& existing =
          feedback_for_function_[func_index].feedback_vector;
      size_t feedback_index = i / 2;
      if (feedback_index < existing.size()) {
        const CallSiteFeedback& old_feedback = existing[feedback_index];
        if (old_feedback.has_non_inlineable_targets()) {
          fm.set_has_non_inlineable_targets();
        }
        if (old_feedback.is_megamorphic()) {
          fm.set_megamorphic();
        }
        for (int j = 0; j < old_feedback.num_cases(); ++j) {
          int old_target_function_index = old_feedback.function_index(j);
          // If the new feedback already contains the target, we do not touch
          // the call count.
          if (!fm.HasTargetCached(old_target_function_index)) {
            fm.AddCall(old_target_function_index, old_feedback.call_count(j));
            // There shouldn't be any imported functions in there as they can't
            // be inlined. If this DCHECK is invalidated,
            // has_non_inlineable_targets_ would need to be updated here to
            // reflect that.
            DCHECK_GE(static_cast<uint32_t>(old_target_function_index),
                      instance_data_->module()->num_imported_functions);
          }
        }
      }
    }
    fm.FinalizeCall();
  }
  base::OwnedVector<CallSiteFeedback> result = std::move(fm).GetResult();
  EnqueueCallees(result.as_vector());
  DCHECK_EQ(result.size(),
            feedback_for_function_[func_index].call_targets.size());
  feedback_for_function_[func_index].feedback_vector = std::move(result);
}
References v8::internal::wasm::FeedbackMaker::AddCall(), v8::internal::wasm::FeedbackMaker::AddCallIndirectCandidate(), v8::internal::wasm::FeedbackMaker::AddCallRefCandidate(), v8::internal::wasm::CallSiteFeedback::call_count(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, v8::internal::wasm::declared_function_index(), EnqueueCallees(), v8::internal::wasm::TypeFeedbackStorage::feedback_for_function, feedback_for_function_, v8::internal::wasm::FeedbackMaker::FinalizeCall(), v8::internal::wasm::CallSiteFeedback::function_index(), v8::internal::wasm::CallSiteFeedback::has_non_inlineable_targets(), v8::internal::wasm::FeedbackMaker::HasTargetCached(), instance_data_, v8::internal::wasm::CallSiteFeedback::is_megamorphic(), v8::internal::wasm::IsCrossInstanceCall(), isolate_, v8::internal::IsSmi(), v8::internal::wasm::FunctionTypeFeedback::kCallIndirect, v8::internal::wasm::FunctionTypeFeedback::kCallRef, v8::internal::wasm::kMaxPolymorphism, module_, v8::internal::wasm::CallSiteFeedback::num_cases(), v8::internal::PrintF(), v8::base::internal::result, SBXCHECK_EQ, SBXCHECK_LE, v8::internal::wasm::FeedbackMaker::set_has_non_inlineable_targets(), v8::internal::wasm::FeedbackMaker::set_megamorphic(), v8::base::Vector< T >::size(), v8::base::OwnedVector< T >::size(), v8::internal::Smi::ToInt(), v8::internal::wasm::WasmModule::type_feedback, v8::internal::UNREACHABLE(), and v8::internal::v8_flags.
Referenced by ProcessQueue().
ProcessQueue()
void v8::internal::wasm::TransitiveTypeFeedbackProcessor::ProcessQueue () [inline], [private]
Definition at line 1309 of file module-compiler.cc.
                      {
    while (!queue_.empty()) {
      auto next = queue_.cbegin();
      ProcessFunction(*next);
      queue_.erase(next);
    }
  }
References ProcessFunction(), and queue_.
Member Data Documentation
feedback_for_function_
std::unordered_map<uint32_t, FunctionTypeFeedback>& v8::internal::wasm::TransitiveTypeFeedbackProcessor::feedback_for_function_ [private]
Definition at line 1347 of file module-compiler.cc.
Referenced by EnqueueCallees(), and ProcessFunction().
instance_data_
const Tagged<WasmTrustedInstanceData> v8::internal::wasm::TransitiveTypeFeedbackProcessor::instance_data_ [private]
Definition at line 1342 of file module-compiler.cc.
Referenced by ProcessFunction().
isolate_
Isolate* const v8::internal::wasm::TransitiveTypeFeedbackProcessor::isolate_ [private]
Definition at line 1341 of file module-compiler.cc.
Referenced by ProcessFunction().
module_
const WasmModule* const v8::internal::wasm::TransitiveTypeFeedbackProcessor::module_ [private]
Definition at line 1343 of file module-compiler.cc.
Referenced by ProcessFunction().
mutex_guard
base::MutexGuard v8::internal::wasm::TransitiveTypeFeedbackProcessor::mutex_guard [private]
Definition at line 1346 of file module-compiler.cc.
no_gc_scope_
DisallowGarbageCollection v8::internal::wasm::TransitiveTypeFeedbackProcessor::no_gc_scope_ [private]
Definition at line 1340 of file module-compiler.cc.
queue_
std::set<int> v8::internal::wasm::TransitiveTypeFeedbackProcessor::queue_ [private]
Definition at line 1348 of file module-compiler.cc.
Referenced by EnqueueCallees(), ProcessQueue(), TransitiveTypeFeedbackProcessor(), and ~TransitiveTypeFeedbackProcessor().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/module-compiler.cc