v8::internal::PrivateNameScopeIterator Class Reference
#include <scopes.h>
Public Member Functions
PrivateNameScopeIterator (Scope *start)
bool Done () const
void Next ()
void AddUnresolvedPrivateName (VariableProxy *proxy)
ClassScope * GetScope () const
Private Attributes
bool skipped_any_scopes_ = false
Scope * start_scope_
Scope * current_scope_
Detailed Description
Definition at line 1545 of file scopes.h.
Constructor & Destructor Documentation
PrivateNameScopeIterator()
v8::internal::PrivateNameScopeIterator::PrivateNameScopeIterator (Scope * start) [explicit]
Definition at line 3236 of file scopes.cc.
    : start_scope_(start), current_scope_(start) {
  if (!start->is_class_scope() || start->AsClassScope()->IsParsingHeritage()) {
    Next();
  }
}
References v8::internal::Scope::AsClassScope(), v8::internal::Scope::is_class_scope(), v8::internal::ClassScope::IsParsingHeritage(), and Next().
Member Function Documentation
AddUnresolvedPrivateName()
void v8::internal::PrivateNameScopeIterator::AddUnresolvedPrivateName (VariableProxy * proxy)
Definition at line 3261 of file scopes.cc.
                                                                            {
  // During a reparse, current_scope_->already_resolved_ may be true here,
  // because the class scope is deserialized while the function scope inside may
  // be new.
  DCHECK(!proxy->is_resolved());
  DCHECK(proxy->IsPrivateName());
  // Use dynamic lookup for top-level scopes in debug-evaluate.
  if (Done()) {
    start_scope_->ForceDynamicLookup(proxy);
    return;
  }
  GetScope()->EnsureRareData()->unresolved_private_names.Add(proxy);
  // Any closure scope that contain uses of private names that skips over a
  // class scope due to heritage expressions need private name context chain
  // recalculation, since not all scopes require a Context or ScopeInfo. See
  // comment in DeclarationScope::RecalcPrivateNameContextChain.
  if (V8_UNLIKELY(skipped_any_scopes_)) {
    start_scope_->GetClosureScope()->RecordNeedsPrivateNameContextChainRecalc();
  }
}
References v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Add(), v8::internal::DCHECK(), Done(), v8::internal::ClassScope::EnsureRareData(), v8::internal::Scope::ForceDynamicLookup(), v8::internal::Scope::GetClosureScope(), GetScope(), v8::internal::VariableProxy::is_resolved(), v8::internal::VariableProxy::IsPrivateName(), v8::internal::DeclarationScope::RecordNeedsPrivateNameContextChainRecalc(), skipped_any_scopes_, start_scope_, v8::internal::ClassScope::RareData::unresolved_private_names, and V8_UNLIKELY.
Referenced by v8::internal::Parser::ExpressionFromPrivateName(), v8::internal::PreParser::ExpressionFromPrivateName(), and v8::internal::ClassScope::ResolvePrivateNamesPartially().
Done()
bool v8::internal::PrivateNameScopeIterator::Done () const [inline]
Definition at line 1549 of file scopes.h.
{ return current_scope_ == nullptr; }
Referenced by AddUnresolvedPrivateName(), v8::internal::DeclarationScope::AllocateVariables(), v8::internal::ClassScope::LookupPrivateName(), Next(), v8::internal::ParserBase< Impl >::ParsePropertyOrPrivatePropertyName(), v8::internal::ClassScope::ResolvePrivateNamesPartially(), and v8::internal::Parser::SkipFunction().
GetScope()
ClassScope* v8::internal::PrivateNameScopeIterator::GetScope () const [inline]
Definition at line 1555 of file scopes.h.
                               {
    DCHECK(!Done());
    return current_scope_->AsClassScope();
  }
References v8::internal::DCHECK().
Referenced by AddUnresolvedPrivateName(), v8::internal::DeclarationScope::AllocateVariables(), and v8::internal::Parser::SkipFunction().
Next()
void v8::internal::PrivateNameScopeIterator::Next ()
Definition at line 3243 of file scopes.cc.
                                    {
  DCHECK(!Done());
  Scope* inner = current_scope_;
  Scope* scope = inner->outer_scope();
  while (scope != nullptr) {
    if (scope->is_class_scope()) {
      if (!inner->private_name_lookup_skips_outer_class()) {
        current_scope_ = scope;
        return;
      }
      skipped_any_scopes_ = true;
    }
    inner = scope;
    scope = scope->outer_scope();
  }
  current_scope_ = nullptr;
}
References current_scope_, v8::internal::DCHECK(), Done(), v8::internal::Scope::is_class_scope(), v8::internal::Scope::outer_scope(), v8::internal::Scope::private_name_lookup_skips_outer_class(), and skipped_any_scopes_.
Referenced by PrivateNameScopeIterator(), and v8::internal::ClassScope::ResolvePrivateNamesPartially().
Member Data Documentation
current_scope_
Scope* v8::internal::PrivateNameScopeIterator::current_scope_ [private]
Definition at line 1563 of file scopes.h.
Referenced by Next().
skipped_any_scopes_
bool v8::internal::PrivateNameScopeIterator::skipped_any_scopes_ = false [private]
Definition at line 1561 of file scopes.h.
Referenced by AddUnresolvedPrivateName(), and Next().
start_scope_
Scope* v8::internal::PrivateNameScopeIterator::start_scope_ [private]
Definition at line 1562 of file scopes.h.
Referenced by AddUnresolvedPrivateName().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ast/scopes.h
/mnt/V8SourceCode/src/ast/scopes.cc