v8::internal::ArrayLiteralBoilerplateBuilder Class Reference
#include <ast.h>
Public Member Functions
ArrayLiteralBoilerplateBuilder (const ZonePtrList< Expression > *values, int first_spread_index)
DirectHandle< ArrayBoilerplateDescription > boilerplate_description () const
bool IsFastCloningSupported () const
int ComputeFlags (bool disable_mementos=false) const
int first_spread_index () const
void InitDepthAndFlags ()
template<typename IsolateT >
Handle< ArrayBoilerplateDescription > GetOrBuildBoilerplateDescription (IsolateT *isolate)
template<typename IsolateT >
void BuildBoilerplateDescription (IsolateT *isolate)
Public Attributes
const ZonePtrList< Expression > * values_
int first_spread_index_
IndirectHandle< ArrayBoilerplateDescription > boilerplate_description_
Additional Inherited Members
Detailed Description
Definition at line 1423 of file ast.h.
Constructor & Destructor Documentation
ArrayLiteralBoilerplateBuilder()
v8::internal::ArrayLiteralBoilerplateBuilder::ArrayLiteralBoilerplateBuilder (const ZonePtrList< Expression > * values, int first_spread_index) [inline]
Definition at line 1425 of file ast.h.
      : values_(values), first_spread_index_(first_spread_index) {}
Member Function Documentation
boilerplate_description()
DirectHandle<ArrayBoilerplateDescription> v8::internal::ArrayLiteralBoilerplateBuilder::boilerplate_description () const [inline]
Definition at line 1428 of file ast.h.
                                                                            {
    return boilerplate_description_;
  }
References boilerplate_description_.
Referenced by v8::internal::LiteralBoilerplateBuilder::GetBoilerplateValue().
BuildBoilerplateDescription()
template<typename IsolateT >
void v8::internal::ArrayLiteralBoilerplateBuilder::BuildBoilerplateDescription (IsolateT * isolate)
Definition at line 663 of file ast.cc.
                       {
  if (!boilerplate_description_.is_null()) return;
  int constants_length =
      first_spread_index_ >= 0 ? first_spread_index_ : values_->length();
  ElementsKind kind = boilerplate_descriptor_kind();
  bool use_doubles = IsDoubleElementsKind(kind);
  DirectHandle<FixedArrayBase> elements;
  if (use_doubles) {
    elements = isolate->factory()->NewFixedDoubleArray(constants_length,
                                                       AllocationType::kOld);
  } else {
    elements = isolate->factory()->NewFixedArrayWithHoles(constants_length,
                                                          AllocationType::kOld);
  }
  // Fill in the literals.
  int array_index = 0;
  for (; array_index < constants_length; array_index++) {
    Expression* element = values_->at(array_index);
    DCHECK(!element->IsSpread());
    if (use_doubles) {
      Literal* literal = element->AsLiteral();
      if (literal && literal->type() == Literal::kTheHole) {
        DCHECK(IsHoleyElementsKind(kind));
        DCHECK(IsTheHole(*GetBoilerplateValue(element, isolate), isolate));
        Cast<FixedDoubleArray>(*elements)->set_the_hole(array_index);
        continue;
      } else if (literal && literal->IsNumber()) {
        Cast<FixedDoubleArray>(*elements)->set(array_index,
                                               literal->AsNumber());
      } else {
        DCHECK(
            IsUninitialized(*GetBoilerplateValue(element, isolate), isolate));
        Cast<FixedDoubleArray>(*elements)->set(array_index, 0);
      }
    } else {
      MaterializedLiteral* m_literal = element->AsMaterializedLiteral();
      if (m_literal != nullptr) {
        BuildConstants(isolate, m_literal);
      }
      // New handle scope here, needs to be after BuildConstants().
      typename IsolateT::HandleScopeType scope(isolate);
      Tagged<Object> boilerplate_value = *GetBoilerplateValue(element, isolate);
      // We shouldn't allocate after creating the boilerplate value.
      DisallowGarbageCollection no_gc;
      if (IsTheHole(boilerplate_value, isolate)) {
        DCHECK(IsHoleyElementsKind(kind));
        continue;
      }
      if (IsUninitialized(boilerplate_value, isolate)) {
        boilerplate_value = Smi::zero();
      }
      DCHECK_EQ(kind, GetMoreGeneralElementsKind(
                          kind, Object::OptimalElementsKind(
                                    boilerplate_value,
                                    GetPtrComprCageBase(*elements))));
      Cast<FixedArray>(*elements)->set(array_index, boilerplate_value);
    }
  } // namespace internal
  // Simple and shallow arrays can be lazily copied, we transform the
  // elements array to a copy-on-write array.
  if (is_simple() && depth() == kShallow && array_index > 0 &&
      IsSmiOrObjectElementsKind(kind)) {
    elements->set_map_safe_transition(
        isolate, ReadOnlyRoots(isolate).fixed_cow_array_map(), kReleaseStore);
  }
  boilerplate_description_ =
      isolate->factory()->NewArrayBoilerplateDescription(kind, elements);
}
References v8::internal::AstNode::AsMaterializedLiteral(), v8::internal::Literal::AsNumber(), boilerplate_description_, v8::internal::LiteralBoilerplateBuilder::boilerplate_descriptor_kind(), v8::internal::LiteralBoilerplateBuilder::BuildConstants(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::LiteralBoilerplateBuilder::depth(), first_spread_index_, v8::internal::LiteralBoilerplateBuilder::GetBoilerplateValue(), v8::internal::GetMoreGeneralElementsKind(), v8::internal::GetPtrComprCageBase(), v8::internal::LiteralBoilerplateBuilder::is_simple(), v8::internal::IsDoubleElementsKind(), v8::internal::IsHoleyElementsKind(), v8::internal::Literal::IsNumber(), v8::internal::IsSmiOrObjectElementsKind(), v8::internal::kOld, v8::kReleaseStore, v8::internal::LiteralBoilerplateBuilder::kShallow, v8::internal::Literal::kTheHole, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Object::OptimalElementsKind(), v8::internal::Literal::type(), values_, and v8::internal::Smi::zero().
Referenced by GetOrBuildBoilerplateDescription().
ComputeFlags()
int v8::internal::ArrayLiteralBoilerplateBuilder::ComputeFlags (bool disable_mementos = false) const [inline]
Definition at line 1436 of file ast.h.
                                                        {
    return LiteralBoilerplateBuilder::ComputeFlags(disable_mementos);
  }
References v8::internal::LiteralBoilerplateBuilder::ComputeFlags().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildCreateArrayLiteral().
first_spread_index()
int v8::internal::ArrayLiteralBoilerplateBuilder::first_spread_index () const [inline]
Definition at line 1440 of file ast.h.
{ return first_spread_index_; }
References first_spread_index_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildCreateArrayLiteral().
GetOrBuildBoilerplateDescription()
template<typename IsolateT >
Handle<ArrayBoilerplateDescription> v8::internal::ArrayLiteralBoilerplateBuilder::GetOrBuildBoilerplateDescription (IsolateT * isolate) [inline]
Definition at line 1447 of file ast.h.
                         {
    if (boilerplate_description_.is_null()) {
      BuildBoilerplateDescription(isolate);
    }
    return boilerplate_description_;
  }
References boilerplate_description_, and BuildBoilerplateDescription().
Referenced by v8::internal::interpreter::BytecodeGenerator::AllocateDeferredConstants().
InitDepthAndFlags()
void v8::internal::ArrayLiteralBoilerplateBuilder::InitDepthAndFlags ()
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildCreateArrayLiteral().
IsFastCloningSupported()
bool v8::internal::ArrayLiteralBoilerplateBuilder::IsFastCloningSupported () const
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildCreateArrayLiteral().
Member Data Documentation
boilerplate_description_
IndirectHandle<ArrayBoilerplateDescription> v8::internal::ArrayLiteralBoilerplateBuilder::boilerplate_description_
Definition at line 1461 of file ast.h.
Referenced by boilerplate_description(), BuildBoilerplateDescription(), and GetOrBuildBoilerplateDescription().
first_spread_index_
int v8::internal::ArrayLiteralBoilerplateBuilder::first_spread_index_
Definition at line 1460 of file ast.h.
Referenced by BuildBoilerplateDescription(), and first_spread_index().
values_
const ZonePtrList<Expression>* v8::internal::ArrayLiteralBoilerplateBuilder::values_
Definition at line 1459 of file ast.h.
Referenced by BuildBoilerplateDescription().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ast/ast.h
/mnt/V8SourceCode/src/ast/ast.cc