v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode > Class Template Reference
#include <function-body-decoder-impl.h>
Classes
class TraceLine
Public Member Functions
template<typename... InterfaceArgs>
WasmFullDecoder (Zone *zone, const WasmModule *module, WasmEnabledFeatures enabled, WasmDetectedFeatures *detected, const FunctionBody &body, InterfaceArgs &&... interface_args)
~WasmFullDecoder ()
Interface & interface ()
void Decode ()
void TraceFailed ()
const char * SafeOpcodeNameAt (const uint8_t *pc)
WasmCodePosition position () const
uint32_t control_depth () const
Control * control_at (uint32_t depth)
uint32_t stack_size () const
Value * stack_value (uint32_t depth) const
int32_t current_catch () const
uint32_t control_depth_of_current_catch () const
uint32_t pc_relative_offset () const
bool is_local_initialized (uint32_t local_index)
void set_local_initialized (uint32_t local_index)
uint32_t locals_initialization_stack_depth () const
void RollbackLocalsInitialization (Control *c)
void InitializeInitializedLocalsTracking (int non_defaultable_locals)
void DecodeFunctionBody ()
bool HasCatchAll (Control *block) const
Private Types
enum class WasmArrayAccess { kRead
, kWrite
 }
enum StackElementsCountMode : bool { kNonStrictCounting = false
, kStrictCounting = true
 }
enum MergeType { kBranchMerge
, kReturnMerge
, kFallthroughMerge
, kInitExprMerge
 }
enum class PushBranchValues : bool { kNo = false
, kYes = true
 }
enum class RewriteStackTypes : bool { kNo = false
, kYes = true
 }
using Value = typename Interface::Value
using Control = typename Interface::Control
using ArgVector = base::Vector< Value >
using PoppedArgVector = std::conditional_t< Interface::kUsesPoppedArgs, base::SmallVector< Value, 8 >, NoVector >
using ReturnVector = base::SmallVector< Value, 2 >
using OpcodeHandler = int(*)(WasmFullDecoder *, WasmOpcode)
Private Member Functions
ASSERT_TRIVIALLY_COPYABLE (Value)
void SetSucceedingCodeDynamicallyUnreachable ()
void MarkMightThrow ()
ValueType TableAddressType (const WasmTable *table)
ValueType MemoryAddressType (const WasmMemory *memory)
MemoryAccessImmediate MakeMemoryAccessImmediate (uint32_t pc_offset, uint32_t max_alignment)
DECODE (Nop)
DECODE (NopForTestingUnsupportedInLiftoff)
DECODE (Block)
DECODE (Rethrow)
DECODE (Throw)
DECODE (Try)
DECODE (Catch)
DECODE (Delegate)
DECODE (CatchAll)
DECODE (TryTable)
DECODE (ThrowRef)
DECODE (BrOnNull)
DECODE (BrOnNonNull)
DECODE (Loop)
DECODE (If)
DECODE (Else)
DECODE (End)
DECODE (Select)
DECODE (SelectWithType)
DECODE (Br)
DECODE (BrIf)
DECODE (BrTable)
DECODE (Return)
DECODE (Unreachable)
DECODE (I32Const)
DECODE (I64Const)
DECODE (F32Const)
DECODE (F64Const)
DECODE (RefNull)
DECODE (RefIsNull)
DECODE (RefFunc)
DECODE (RefAsNonNull)
DECODE (LocalGet)
DECODE (LocalSet)
DECODE (LocalTee)
DECODE (Drop)
DECODE (GlobalGet)
DECODE (GlobalSet)
DECODE (TableGet)
DECODE (TableSet)
DECODE (LoadMem)
DECODE (StoreMem)
DECODE (MemoryGrow)
DECODE (MemorySize)
DECODE (CallFunction)
DECODE (CallIndirect)
DECODE (ReturnCall)
DECODE (ReturnCallIndirect)
DECODE (CallRef)
DECODE (ReturnCallRef)
DECODE (RefEq)
bool IsSubtypeVec (base::Vector< const ValueType > subtypes, base::Vector< const ValueType > supertypes)
DECODE (ContNew)
DECODE (ContBind)
int DecodeEffectHandlerTable (EffectHandlerTableImmediate &handler_table_imm, base::Vector< HandlerCase > &handlers)
DECODE (Resume)
DECODE (ResumeThrow)
DECODE (Suspend)
DECODE (Switch)
DECODE (Numeric)
DECODE (AsmJs)
DECODE (Simd)
DECODE (Atomic)
DECODE (GC)
OpcodeHandler GetOpcodeHandler (uint8_t opcode)
void EndControl ()
template<typename func >
void InitMerge (Merge< Value > *merge, uint32_t arity, func get_val)
int EnsureStackArguments (int count)
V8_NOINLINE V8_PRESERVE_MOST int EnsureStackArguments_Slow (int count)
void ValidateParameters (const FunctionSig *sig)
void DropArgs (const FunctionSig *sig)
PoppedArgVector PopArgs (const StructType *type)
void DropArgs (const StructType *type)
PoppedArgVector PopSomeArgs (const FunctionSig *sig, int count)
PoppedArgVector PopArgs (const FunctionSig *sig)
Control * PushControl (ControlKind kind, const BlockTypeImmediate &imm)
void PopControl ()
int DecodeLoadMem (LoadType type, int prefix_len=1)
int DecodeLoadTransformMem (LoadType type, LoadTransformationKind transform, uint32_t opcode_length)
int DecodeLoadLane (WasmOpcode opcode, LoadType type, uint32_t opcode_length)
int DecodeStoreLane (WasmOpcode opcode, StoreType type, uint32_t opcode_length)
bool CheckStaticallyOutOfBounds (const WasmMemory *memory, uint64_t size, uint64_t offset)
int DecodeStoreMem (StoreType store, int prefix_len=1)
uint32_t SimdConstOp (uint32_t opcode_length)
uint32_t SimdExtractLane (WasmOpcode opcode, ValueType type, uint32_t opcode_length)
uint32_t SimdReplaceLane (WasmOpcode opcode, ValueType type, uint32_t opcode_length)
uint32_t Simd8x16ShuffleOp (uint32_t opcode_length)
uint32_t DecodeSimdOpcode (WasmOpcode opcode, uint32_t opcode_length)
bool TypeCheckAlwaysFails (Value obj, HeapType expected_type, bool null_succeeds)
bool TypeCheckAlwaysSucceeds (Value obj, HeapType type)
Value PopDescriptor (ModuleTypeIndex described_index)
int DecodeGCOpcode (WasmOpcode opcode, uint32_t opcode_length)
int ParseBrOnCast (WasmOpcode opcode, uint32_t pc_offset)
int DecodeStringNewWtf8 (unibrow::Utf8Variant variant, uint32_t opcode_length)
int DecodeStringMeasureWtf8 (unibrow::Utf8Variant variant, uint32_t opcode_length)
int DecodeStringEncodeWtf8 (unibrow::Utf8Variant variant, uint32_t opcode_length)
int DecodeStringViewWtf8Encode (unibrow::Utf8Variant variant, uint32_t opcode_length)
int DecodeStringNewWtf8Array (unibrow::Utf8Variant variant, uint32_t opcode_length)
int DecodeStringEncodeWtf8Array (unibrow::Utf8Variant variant, uint32_t opcode_length)
int DecodeStringRefOpcode (WasmOpcode opcode, uint32_t opcode_length)
uint32_t DecodeAtomicOpcode (WasmOpcode opcode, uint32_t opcode_length)
unsigned DecodeNumericOpcode (WasmOpcode opcode, uint32_t opcode_length)
unsigned DecodeAsmJsOpcode (WasmOpcode opcode, uint32_t opcode_length)
Value CreateValue (ValueType type)
Value * Push (Value value)
Value * Push (ValueType type)
void PushMergeValues (Control *c, Merge< Value > *merge)
void PushReturns (ReturnVector values)
Value * PushValueTypes (const base::Vector< const ValueType > types)
Value * PushParameters (const FunctionSig *sig)
Value * PushReturns (const FunctionSig *sig)
V8_NOINLINE V8_PRESERVE_MOST void PopTypeError (int index, Value val, const char *expected)
V8_NOINLINE V8_PRESERVE_MOST void PopTypeError (int index, Value val, std::string expected)
V8_NOINLINE V8_PRESERVE_MOST void PopTypeError (int index, Value val, ValueType expected)
V8_NOINLINE V8_PRESERVE_MOST void NotEnoughArgumentsError (int needed, int actual)
Value Pop (int index, ValueType expected)
void ValidateStackValue (int index, Value value, ValueType expected)
Value Pop ()
Value Peek (int depth, int index, ValueType expected)
Value Peek (int depth=0)
Value Peek (ValueType expected)
template<typename... ValueTypes>
requires ((std::is_same_v< ValueType, ValueTypes >||std::is_base_of_v< IndependentValueType, ValueTypes >) &&...) inline std
Value PopPackedArray (uint32_t operand_index, ValueType expected_element_type, WasmArrayAccess access)
void Drop (int count=1)
void Drop (const Value &)
template<StackElementsCountMode strict_count, PushBranchValues push_branch_values, MergeType merge_type, RewriteStackTypes rewrite_types>
bool TypeCheckStackAgainstMerge (Merge< Value > *merge)
template<StackElementsCountMode strict_count, PushBranchValues push_branch_values, MergeType merge_type, RewriteStackTypes rewrite_types>
V8_PRESERVE_MOST V8_NOINLINE bool TypeCheckStackAgainstMerge_Slow (Merge< Value > *merge)
template<StackElementsCountMode strict_count, MergeType merge_type>
bool DoReturn ()
int startrel (const uint8_t *ptr)
void FallThrough ()
bool TypeCheckOneArmedIf (Control *c)
bool TypeCheckFallThru ()
template<PushBranchValues push_branch_values, RewriteStackTypes rewrite_types>
bool TypeCheckBranch (Control *c)
void onFirstError () override
int BuildSimplePrototypeOperator (WasmOpcode opcode)
int BuildSimpleOperator (WasmOpcode opcode, const FunctionSig *sig)
int BuildSimpleOperator (WasmOpcode opcode, ValueType return_type, ValueType arg_type)
int BuildSimpleOperator (WasmOpcode opcode, ValueType return_type, ValueType lhs_type, ValueType rhs_type)
Static Private Member Functions
static Value UnreachableValue (const uint8_t *pc)
static int NonConstError (WasmFullDecoder *decoder, WasmOpcode opcode)
static int UnknownOpcodeError (WasmFullDecoder *decoder, WasmOpcode opcode)
static constexpr OpcodeHandler GetOpcodeHandlerTableEntry (size_t idx)
Private Attributes
uint32_t locals_offset_ = 0
Interface interface_
FastZoneVector< Value > stack_
bool * initialized_locals_
FastZoneVector< uint32_t > locals_initializers_stack_
FastZoneVector< Control > control_
bool current_code_reachable_and_ok_ = true
bool has_nondefaultable_locals_ = true
int32_t current_catch_ = -1
Static Private Attributes
static constexpr ValidationTag validate = {}
Additional Inherited Members
Detailed Description
template<typename ValidationTag, typename Interface, DecodingMode decoding_mode = kFunctionBody>
class v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >
Definition at line 3030 of file function-body-decoder-impl.h.
Member Typedef Documentation
ArgVector
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
using v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::ArgVector = base::Vector<Value> [private]
Definition at line 3033 of file function-body-decoder-impl.h.
Control
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
using v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Control = typename Interface::Control [private]
Definition at line 3032 of file function-body-decoder-impl.h.
OpcodeHandler
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
using v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::OpcodeHandler = int (*)(WasmFullDecoder*, WasmOpcode) [private]
Definition at line 4855 of file function-body-decoder-impl.h.
PoppedArgVector
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
using v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PoppedArgVector = std::conditional_t<Interface::kUsesPoppedArgs, base::SmallVector<Value, 8>, NoVector> [private]
Definition at line 3034 of file function-body-decoder-impl.h.
ReturnVector
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
using v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::ReturnVector = base::SmallVector<Value, 2> [private]
Definition at line 3037 of file function-body-decoder-impl.h.
Value
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
using v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Value = typename Interface::Value [private]
Definition at line 3031 of file function-body-decoder-impl.h.
Member Enumeration Documentation
MergeType
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
enum v8::internal::wasm::WasmFullDecoder::MergeType [private]
Enumerator
kBranchMerge
kReturnMerge
kFallthroughMerge
kInitExprMerge
Definition at line 7644 of file function-body-decoder-impl.h.
                 {
    kBranchMerge,
    kReturnMerge,
    kFallthroughMerge,
    kInitExprMerge
  };
PushBranchValues
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
enum v8::internal::wasm::WasmFullDecoder::PushBranchValues : bool [strong], [private]
Enumerator
kNo
kYes
Definition at line 7651 of file function-body-decoder-impl.h.
                              : bool {
    kNo = false,
    kYes = true,
  };
RewriteStackTypes
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
enum v8::internal::wasm::WasmFullDecoder::RewriteStackTypes : bool [strong], [private]
Enumerator
kNo
kYes
Definition at line 7655 of file function-body-decoder-impl.h.
                               : bool {
    kNo = false,
    kYes = true,
  };
StackElementsCountMode
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
enum v8::internal::wasm::WasmFullDecoder::StackElementsCountMode : bool [private]
Enumerator
kNonStrictCounting
kStrictCounting
Definition at line 7639 of file function-body-decoder-impl.h.
                              : bool {
    kNonStrictCounting = false,
    kStrictCounting = true
  };
WasmArrayAccess
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
enum v8::internal::wasm::WasmFullDecoder::WasmArrayAccess [strong], [private]
Enumerator
kRead
kWrite
Definition at line 6253 of file function-body-decoder-impl.h.
{ kRead, kWrite };
Constructor & Destructor Documentation
WasmFullDecoder()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
template<typename... InterfaceArgs>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::WasmFullDecoder (Zone * zone, const WasmModule * module, WasmEnabledFeatures enabled, WasmDetectedFeatures * detected, const FunctionBody & body, InterfaceArgs &&... interface_args) [inline]
Definition at line 3045 of file function-body-decoder-impl.h.
      : WasmDecoder<ValidationTag, decoding_mode>(
            zone, module, enabled, detected, body.sig, body.is_shared,
            body.start, body.end, body.offset),
        interface_(std::forward<InterfaceArgs>(interface_args)...),
        stack_(16, zone),
        control_(16, zone) {}
 WasmFullDecoder()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::~WasmFullDecoder () [inline]
Definition at line 3055 of file function-body-decoder-impl.h.
                     {
    control_.Reset(this->zone_);
    stack_.Reset(this->zone_);
    locals_initializers_stack_.Reset(this->zone_);
  }
References v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::control_, v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::locals_initializers_stack_, v8::internal::wasm::FastZoneVector< T >::Reset(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::stack_, and v8::internal::wasm::WasmDecoder< ValidationTag, kFunctionBody >::zone_.
Member Function Documentation
ASSERT_TRIVIALLY_COPYABLE()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::ASSERT_TRIVIALLY_COPYABLE (Value) [private]
BuildSimpleOperator() [1/3]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
int v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::BuildSimpleOperator (WasmOpcode opcode, const FunctionSig * sig) [inline], [private]
Definition at line 7840 of file function-body-decoder-impl.h.
                                                                     {
    DCHECK_GE(1, sig->return_count());
    if (sig->parameter_count() == 1) {
      // All current simple unary operators have exactly 1 return value.
      DCHECK_EQ(1, sig->return_count());
      return BuildSimpleOperator(opcode, sig->GetReturn(0), sig->GetParam(0));
    } else {
      DCHECK_EQ(2, sig->parameter_count());
      ValueType ret = sig->return_count() == 0 ? kWasmVoid : sig->GetReturn(0);
      return BuildSimpleOperator(opcode, ret, sig->GetParam(0),
                                 sig->GetParam(1));
    }
  }
References DCHECK_EQ, DCHECK_GE, v8::internal::wasm::kWasmVoid, and v8::internal::sig.
BuildSimpleOperator() [2/3]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
int v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::BuildSimpleOperator (WasmOpcode opcode, ValueType return_type, ValueType arg_type) [inline], [private]
Definition at line 7854 of file function-body-decoder-impl.h.
                                              {
    DCHECK_NE(kWasmVoid, return_type);
    Value val = Pop(arg_type);
    Value* ret = Push(return_type);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(UnOp, opcode, val, ret);
    return 1;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, DCHECK_NE, and v8::internal::wasm::kWasmVoid.
BuildSimpleOperator() [3/3]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
int v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::BuildSimpleOperator (WasmOpcode opcode, ValueType return_type, ValueType lhs_type, ValueType rhs_type) [inline], [private]
Definition at line 7863 of file function-body-decoder-impl.h.
                                                                  {
    auto [lval, rval] = Pop(lhs_type, rhs_type);
    Value* ret = return_type == kWasmVoid ? nullptr : Push(return_type);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(BinOp, opcode, lval, rval, ret);
    return 1;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::wasm::kWasmVoid, and nullptr.
BuildSimplePrototypeOperator()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
int v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::BuildSimplePrototypeOperator (WasmOpcode opcode) [inline], [private]
Definition at line 7835 of file function-body-decoder-impl.h.
                                                      {
    const FunctionSig* sig = WasmOpcodes::Signature(opcode);
    return BuildSimpleOperator(opcode, sig);
  }
References v8::internal::sig.
CheckStaticallyOutOfBounds()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::CheckStaticallyOutOfBounds (const WasmMemory * memory, uint64_t size, uint64_t offset) [inline], [private]
Definition at line 5226 of file function-body-decoder-impl.h.
                                                   {
    const bool statically_oob =
        !base::IsInBounds<uint64_t>(offset, size, memory->max_memory_size);
    if (V8_UNLIKELY(statically_oob)) {
      CALL_INTERFACE_IF_OK_AND_REACHABLE(Trap, TrapReason::kTrapMemOutOfBounds);
      SetSucceedingCodeDynamicallyUnreachable();
    }
    return statically_oob;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::wasm::WasmMemory::max_memory_size, size(), and V8_UNLIKELY.
control_at()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
Control* v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::control_at (uint32_t depth) [inline]
Definition at line 3142 of file function-body-decoder-impl.h.
                                      {
    DCHECK_GT(control_.size(), depth);
    return control_.end() - 1 - depth;
  }
References v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::control_, DCHECK_GT, v8::internal::wasm::FastZoneVector< T >::end(), and v8::internal::wasm::FastZoneVector< T >::size().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrIf(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BrIf(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrOnAbstractType(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrOnCastAbstractFromAnyRejectShared(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrOnCastFailImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrOnCastImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrOnNonAbstractType(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrOnNonNull(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrOnNull(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrOrRet(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BrOrRet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrTable(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTable(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallAndMaybeCatchException(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CatchAll(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CatchAll(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Delegate(), v8::internal::wasm::TurboshaftGraphBuildingInterface::Delegate(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitCoverageInstrumentationIfReachable(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitLandingPad(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetCurrentDebugSideTableEntries(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::If(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineWasmCall(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::NeedsTierupCheck(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::NextInstruction(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TraceCacheState(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::UnuseLabels().
control_depth()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
uint32_t v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::control_depth () const [inline]
Definition at line 3138 of file function-body-decoder-impl.h.
                                 {
    return static_cast<uint32_t>(control_.size());
  }
References v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::control_, and v8::internal::wasm::FastZoneVector< T >::size().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrIf(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BrIf(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrOnAbstractType(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrOnCastAbstractFromAnyRejectShared(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrOnCastFailImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrOnCastImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrOnNonAbstractType(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrOnNonNull(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrOnNull(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrOrRet(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BrOrRet(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTable(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::control_depth_of_current_catch(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Delegate(), v8::internal::wasm::TurboshaftGraphBuildingInterface::Delegate(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetCurrentDebugSideTableEntries(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::NeedsTierupCheck(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TraceCacheState(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::UnuseLabels().
control_depth_of_current_catch()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
uint32_t v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::control_depth_of_current_catch () const [inline]
Definition at line 3157 of file function-body-decoder-impl.h.
                                                  {
    return control_depth() - 1 - current_catch();
  }
References v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::control_depth(), and v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::current_catch().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::CallAndMaybeCatchException(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitLandingPad(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineWasmCall().
CreateValue()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
Value v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::CreateValue (ValueType type) [inline], [private]
Definition at line 7427 of file function-body-decoder-impl.h.
{ return Value{this->pc_, type}; }
References v8::internal::tracing::type.
current_catch()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
int32_t v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::current_catch () const [inline]
Definition at line 3155 of file function-body-decoder-impl.h.
{ return current_catch_; }
References v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::current_catch_.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::CallAndMaybeCatchException(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::control_depth_of_current_catch(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitLandingPad(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineWasmCall().
Decode()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
void v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Decode () [inline]
Definition at line 3063 of file function-body-decoder-impl.h.
                {
    DCHECK(stack_.empty());
    DCHECK(control_.empty());
    DCHECK_LE(this->pc_, this->end_);
    DCHECK_EQ(this->num_locals(), 0);
    locals_offset_ = this->pc_offset();
    uint32_t locals_length = this->DecodeLocals(this->pc());
    if (!VALIDATE(this->ok())) return TraceFailed();
    this->consume_bytes(locals_length);
    int non_defaultable = 0;
    uint32_t params_count =
        static_cast<uint32_t>(this->sig_->parameter_count());
    for (uint32_t index = params_count; index < this->num_locals(); index++) {
      if (!this->local_type(index).is_defaultable()) non_defaultable++;
      // We need this because reference locals are initialized with null, and
      // later we run a lowering step for null based on {detected_}.
      if (this->local_type(index).is_reference()) {
        this->detected_->add_reftypes();
      }
    }
    this->InitializeInitializedLocalsTracking(non_defaultable);
    // Cannot use CALL_INTERFACE_* macros because control is empty.
    interface().StartFunction(this);
    DecodeFunctionBody();
    // Decoding can fail even without validation, e.g. due to missing Liftoff
    // support.
    if (this->failed()) return TraceFailed();
    if (!VALIDATE(control_.empty())) {
      if (control_.size() > 1) {
        this->DecodeError(control_.back().pc(),
                          "unterminated control structure");
      } else {
        this->DecodeError("function body must end with \"end\" opcode");
      }
      return TraceFailed();
    }
    // Cannot use CALL_INTERFACE_* macros because control is empty.
    interface().FinishFunction(this);
    if (this->failed()) return TraceFailed();
    DCHECK(stack_.empty());
    TRACE("wasm-decode ok\n\n");
  }
References v8::internal::wasm::FastZoneVector< T >::back(), v8::internal::wasm::Decoder::consume_bytes(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::control_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LE, v8::internal::wasm::WasmDecoder< ValidationTag, kFunctionBody >::DecodeError(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeFunctionBody(), v8::internal::wasm::WasmDecoder< ValidationTag, kFunctionBody >::DecodeLocals(), v8::internal::wasm::WasmDecoder< ValidationTag, kFunctionBody >::detected_, v8::internal::wasm::FastZoneVector< T >::empty(), v8::internal::wasm::Decoder::end_, v8::internal::wasm::Decoder::failed(), v8::internal::index, v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::InitializeInitializedLocalsTracking(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::interface(), v8::internal::wasm::ValueTypeBase::is_defaultable(), v8::internal::wasm::ValueTypeBase::is_reference(), v8::internal::wasm::WasmDecoder< ValidationTag, kFunctionBody >::local_type(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::locals_offset_, v8::internal::wasm::WasmDecoder< ValidationTag, kFunctionBody >::num_locals(), v8::internal::wasm::Decoder::ok(), v8::internal::Signature< T >::parameter_count(), v8::internal::wasm::Decoder::pc(), v8::internal::wasm::Decoder::pc_, v8::internal::wasm::Decoder::pc_offset(), v8::internal::wasm::WasmDecoder< ValidationTag, kFunctionBody >::sig_, v8::internal::wasm::FastZoneVector< T >::size(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::stack_, v8::internal::TRACE(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::TraceFailed(), and VALIDATE.
Referenced by v8::internal::wasm::ExecuteLiftoffCompilation(), v8::internal::wasm::GenerateLiftoffDebugSideTable(), and v8::internal::wasm::ValidateFunctionBody().
DECODE() [1/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (AsmJs) [inline], [private]
Definition at line 4781 of file function-body-decoder-impl.h.
                {
    auto [full_opcode, opcode_length] =
        this->template read_prefixed_opcode<ValidationTag>(this->pc_,
                                                           "asmjs index");
    trace_msg->AppendOpcode(full_opcode);
    return DecodeAsmJsOpcode(full_opcode, opcode_length);
  }
DECODE() [2/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (Atomic) [inline], [private]
Definition at line 4810 of file function-body-decoder-impl.h.
                 {
    auto [full_opcode, opcode_length] =
        this->template read_prefixed_opcode<ValidationTag>(this->pc_,
                                                           "atomic index");
    trace_msg->AppendOpcode(full_opcode);
    return DecodeAtomicOpcode(full_opcode, opcode_length);
  }
DECODE() [3/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (Block) [inline], [private]
Definition at line 3514 of file function-body-decoder-impl.h.
                {
    BlockTypeImmediate imm(this->enabled_, this->detected_, this, this->pc_ + 1,
                           validate);
    if (!this->Validate(this->pc_ + 1, imm)) return 0;
    Control* block = PushControl(kControlBlock, imm);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(Block, block);
    return 1 + imm.length;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::wasm::kControlBlock, and v8::internal::wasm::BlockTypeImmediate::length.
DECODE() [4/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (Br) [inline], [private]
Definition at line 4063 of file function-body-decoder-impl.h.
             {
    BranchDepthImmediate imm(this, this->pc_ + 1, validate);
    if (!this->Validate(this->pc_ + 1, imm, control_.size())) return 0;
    Control* c = control_at(imm.depth);
    if (!VALIDATE(
            (TypeCheckBranch<PushBranchValues::kNo, RewriteStackTypes::kNo>(
                c)))) {
      return 0;
    }
    if (V8_LIKELY(current_code_reachable_and_ok_)) {
      CALL_INTERFACE(BrOrRet, imm.depth);
      c->br_merge()->reached = true;
    }
    EndControl();
    return 1 + imm.length;
  }
References CALL_INTERFACE, v8::internal::wasm::BranchDepthImmediate::depth, v8::internal::wasm::BranchDepthImmediate::length, v8::internal::wasm::FastZoneVector< T >::size(), V8_LIKELY, and VALIDATE.
DECODE() [5/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (BrIf) [inline], [private]
Definition at line 4080 of file function-body-decoder-impl.h.
               {
    BranchDepthImmediate imm(this, this->pc_ + 1, validate);
    if (!this->Validate(this->pc_ + 1, imm, control_.size())) return 0;
    Value cond = Pop(kWasmI32);
    Control* c = control_at(imm.depth);
    if (!VALIDATE(
            (TypeCheckBranch<PushBranchValues::kYes, RewriteStackTypes::kYes>(
                c)))) {
      return 0;
    }
    if (V8_LIKELY(current_code_reachable_and_ok_)) {
      CALL_INTERFACE(BrIf, cond, imm.depth);
      c->br_merge()->reached = true;
    }
    return 1 + imm.length;
  }
References CALL_INTERFACE, v8::internal::wasm::BranchDepthImmediate::depth, v8::internal::wasm::kWasmI32, v8::internal::wasm::BranchDepthImmediate::length, v8::internal::wasm::FastZoneVector< T >::size(), V8_LIKELY, and VALIDATE.
DECODE() [6/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (BrOnNonNull) [inline], [private]
Definition at line 3822 of file function-body-decoder-impl.h.
                      {
    this->detected_->add_typed_funcref();
    BranchDepthImmediate imm(this, this->pc_ + 1, validate);
    if (!this->Validate(this->pc_ + 1, imm, control_.size())) return 0;
    Value ref_object = Pop();
    if (!VALIDATE(ref_object.type.is_object_reference() ||
                  ref_object.type.is_bottom())) {
      PopTypeError(
          0, ref_object,
          "subtype of ((ref null any), (ref null extern) or (ref null func))");
      return 0;
    }
    // Typechecking the branch and creating the branch merges requires the
    // non-null value on the stack, so we push it temporarily.
    Value* value_on_branch = Push(ref_object.type.AsNonNull());
    Control* c = control_at(imm.depth);
    if (!VALIDATE(
            (TypeCheckBranch<PushBranchValues::kYes, RewriteStackTypes::kYes>(
                c)))) {
      return 0;
    }
    switch (ref_object.type.kind()) {
      case kBottom:
        // We are in unreachable code. Do nothing.
        DCHECK(!current_code_reachable_and_ok_);
        break;
      case kRef:
        // For a non-nullable value, we always take the branch.
        if (V8_LIKELY(current_code_reachable_and_ok_)) {
          CALL_INTERFACE(Forward, ref_object, value_on_branch);
          CALL_INTERFACE(BrOrRet, imm.depth);
          // We know that the following code is not reachable, but according
          // to the spec it technically is. Set it to spec-only reachable.
          SetSucceedingCodeDynamicallyUnreachable();
          c->br_merge()->reached = true;
        }
        break;
      case kRefNull: {
        if (V8_LIKELY(current_code_reachable_and_ok_)) {
          CALL_INTERFACE(BrOnNonNull, ref_object, value_on_branch, imm.depth,
                         true);
          c->br_merge()->reached = true;
        }
        break;
      }
      default:
        PopTypeError(0, ref_object, "object reference");
        return 0;
    }
    Drop(*value_on_branch);
    return 1 + imm.length;
  }
References CALL_INTERFACE, v8::internal::DCHECK(), v8::internal::wasm::BranchDepthImmediate::depth, v8::internal::kRef, v8::internal::kRefNull, v8::internal::wasm::BranchDepthImmediate::length, v8::internal::wasm::FastZoneVector< T >::size(), V8_LIKELY, and VALIDATE.
DECODE() [7/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (BrOnNull) [inline], [private]
Definition at line 3784 of file function-body-decoder-impl.h.
                   {
    this->detected_->add_typed_funcref();
    BranchDepthImmediate imm(this, this->pc_ + 1, validate);
    if (!this->Validate(this->pc_ + 1, imm, control_.size())) return 0;
    Value ref_object = Pop();
    Control* c = control_at(imm.depth);
    if (!VALIDATE(
            (TypeCheckBranch<PushBranchValues::kYes, RewriteStackTypes::kYes>(
                c)))) {
      return 0;
    }
    switch (ref_object.type.kind()) {
      case kBottom:
        // We are in a polymorphic stack. Leave the stack as it is.
        DCHECK(!current_code_reachable_and_ok_);
        [[fallthrough]];
      case kRef:
        // For a non-nullable value, we won't take the branch, and can leave
        // the stack as it is.
        Push(ref_object);
        break;
      case kRefNull: {
        Value* result = Push(ValueType::Ref(ref_object.type.heap_type()));
        // The result of br_on_null has the same value as the argument (but a
        // non-nullable type).
        if (V8_LIKELY(current_code_reachable_and_ok_)) {
          CALL_INTERFACE(BrOnNull, ref_object, imm.depth, false, result);
          c->br_merge()->reached = true;
        }
        break;
      }
      default:
        PopTypeError(0, ref_object, "object reference");
        return 0;
    }
    return 1 + imm.length;
  }
References CALL_INTERFACE, v8::internal::DCHECK(), v8::internal::wasm::BranchDepthImmediate::depth, v8::internal::kRef, v8::internal::kRefNull, v8::internal::wasm::BranchDepthImmediate::length, v8::internal::wasm::ValueType::Ref(), v8::base::internal::result, v8::internal::wasm::FastZoneVector< T >::size(), V8_LIKELY, and VALIDATE.
DECODE() [8/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (BrTable) [inline], [private]
Definition at line 4097 of file function-body-decoder-impl.h.
                  {
    BranchTableImmediate imm(this, this->pc_ + 1, validate);
    BranchTableIterator<ValidationTag> iterator(this, imm);
    Value key = Pop(kWasmI32);
    if (!VALIDATE(this->ok())) return 0;
    if (!this->Validate(this->pc_ + 1, imm)) return 0;
    // Cache the branch targets during the iteration, so that we can set
    // all branch targets as reachable after the {CALL_INTERFACE} call.
    SmallZoneVector<bool, 32> br_targets(control_.size(), this->zone());
    std::uninitialized_fill(br_targets.begin(), br_targets.end(), false);
    uint32_t arity = 0;
    while (iterator.has_next()) {
      const uint32_t index = iterator.cur_index();
      const uint8_t* pos = iterator.pc();
      const uint32_t target = iterator.next();
      if (!VALIDATE(target < control_depth())) {
        this->DecodeError(pos, "invalid branch depth: %u", target);
        return 0;
      }
      // Avoid redundant branch target checks.
      if (br_targets[target]) continue;
      br_targets[target] = true;
      if (ValidationTag::validate) {
        if (index == 0) {
          arity = control_at(target)->br_merge()->arity;
        } else if (!VALIDATE(control_at(target)->br_merge()->arity == arity)) {
          this->DecodeError(
              pos, "br_table: label arity inconsistent with previous arity %d",
              arity);
          return 0;
        }
        if (!VALIDATE(
                (TypeCheckBranch<PushBranchValues::kNo, RewriteStackTypes::kNo>(
                    control_at(target))))) {
          return 0;
        }
      }
    }
    if (V8_LIKELY(current_code_reachable_and_ok_)) {
      CALL_INTERFACE(BrTable, imm, key);
      for (uint32_t i = 0; i < control_depth(); ++i) {
        control_at(i)->br_merge()->reached |= br_targets[i];
      }
    }
    EndControl();
    return 1 + iterator.length();
  }
References v8::base::SmallVector< T, kSize, Allocator >::begin(), CALL_INTERFACE, v8::internal::wasm::BranchTableIterator< ValidationTag >::cur_index(), v8::internal::wasm::DecodeError(), v8::base::SmallVector< T, kSize, Allocator >::end(), v8::internal::wasm::BranchTableIterator< ValidationTag >::has_next(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::key, v8::internal::wasm::kWasmI32, v8::internal::wasm::BranchTableIterator< ValidationTag >::length(), v8::internal::wasm::BranchTableIterator< ValidationTag >::next(), v8::internal::wasm::BranchTableIterator< ValidationTag >::pc(), v8::internal::wasm::FastZoneVector< T >::size(), v8::internal::this, V8_LIKELY, and VALIDATE.
DECODE() [9/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (CallFunction) [inline], [private]
Definition at line 4367 of file function-body-decoder-impl.h.
                       {
    CallFunctionImmediate imm(this, this->pc_ + 1, validate);
    if (!this->Validate(this->pc_ + 1, imm)) return 0;
    PoppedArgVector args = PopArgs(imm.sig);
    Value* returns = PushReturns(imm.sig);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(CallDirect, imm, args.data(), returns);
    MarkMightThrow();
    return 1 + imm.length;
  }
References v8::base::args, CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::wasm::IndexImmediate::length, wasm::anonymous_namespace{c-api.cc}::PopArgs(), and v8::internal::wasm::CallFunctionImmediate::sig.
DECODE() [10/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (CallIndirect) [inline], [private]
Definition at line 4377 of file function-body-decoder-impl.h.
                       {
    CallIndirectImmediate imm(this, this->pc_ + 1, validate);
    if (!this->Validate(this->pc_ + 1, imm)) return 0;
    Value index = Pop(TableAddressType(imm.table_imm.table));
    PoppedArgVector args = PopArgs(imm.sig);
    Value* returns = PushReturns(imm.sig);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(CallIndirect, index, imm, args.data(),
                                       returns);
    MarkMightThrow();
    if (!this->module_->type(imm.sig_imm.index).is_final) {
      // In this case we emit an rtt.canon as part of the indirect call.
      this->detected_->add_gc();
    }
    return 1 + imm.length;
  }
References v8::base::args, CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::index, v8::internal::wasm::TypeIndexImmediate::index, v8::internal::wasm::CallIndirectImmediate::length, wasm::anonymous_namespace{c-api.cc}::PopArgs(), v8::internal::wasm::CallIndirectImmediate::sig, v8::internal::wasm::CallIndirectImmediate::sig_imm, v8::internal::wasm::TableIndexImmediate::table, and v8::internal::wasm::CallIndirectImmediate::table_imm.
DECODE() [11/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (CallRef) [inline], [private]
Definition at line 4430 of file function-body-decoder-impl.h.
                  {
    this->detected_->add_typed_funcref();
    SigIndexImmediate imm(this, this->pc_ + 1, validate);
    if (!this->Validate(this->pc_ + 1, imm)) return 0;
    Value func_ref = Pop(ValueType::RefNull(imm.heap_type()));
    PoppedArgVector args = PopArgs(imm.sig);
    Value* returns = PushReturns(imm.sig);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(CallRef, func_ref, imm.sig, args.data(),
                                       returns);
    MarkMightThrow();
    return 1 + imm.length;
  }
References v8::base::args, CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::wasm::SigIndexImmediate::heap_type(), v8::internal::wasm::TypeIndexImmediate::length, wasm::anonymous_namespace{c-api.cc}::PopArgs(), v8::internal::wasm::ValueType::RefNull(), and v8::internal::wasm::SigIndexImmediate::sig.
DECODE() [12/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (Catch) [inline], [private]
Definition at line 3574 of file function-body-decoder-impl.h.
                {
    CHECK_PROTOTYPE_OPCODE(legacy_eh);
    // We must have already seen a "try" opcode, so we don't need to check for
    // mixed legacy / new EH instructions again.
    TagIndexImmediate imm(this, this->pc_ + 1, validate);
    if (!this->Validate(this->pc_ + 1, imm)) return 0;
    DCHECK(!control_.empty());
    Control* c = &control_.back();
    if (!VALIDATE(c->is_try())) {
      this->DecodeError("catch does not match a try");
      return 0;
    }
    if (!VALIDATE(!c->is_try_catchall())) {
      this->DecodeError("catch after catch-all for try");
      return 0;
    }
    FallThrough();
    c->kind = kControlTryCatch;
    stack_.shrink_to(c->stack_depth);
    c->reachability = control_at(1)->innerReachability();
    current_code_reachable_and_ok_ = VALIDATE(this->ok()) && c->reachable();
    RollbackLocalsInitialization(c);
    const WasmTagSig* sig = imm.tag->sig;
    // tags can have return values, so we have to check.
    if (sig->return_count() != 0) {
      this->DecodeError("tag signature %u has non-void return", imm.index);
      return 0;
    }
    stack_.EnsureMoreCapacity(static_cast<int>(sig->parameter_count()),
                              this->zone_);
    for (ValueType type : sig->parameters()) Push(type);
    base::Vector<Value> values(stack_.begin() + c->stack_depth,
                               sig->parameter_count());
    current_catch_ = c->previous_catch; // Pop try scope.
    // If there is a throwing instruction in `c`, generate the header for a
    // catch block. Otherwise, the catch block is unreachable.
    if (c->might_throw) {
      CALL_INTERFACE_IF_OK_AND_PARENT_REACHABLE(CatchException, imm, c, values);
    } else {
      SetSucceedingCodeDynamicallyUnreachable();
    }
    return 1 + imm.length;
  }
References v8::internal::wasm::FastZoneVector< T >::back(), v8::internal::wasm::FastZoneVector< T >::begin(), CALL_INTERFACE_IF_OK_AND_PARENT_REACHABLE, CHECK_PROTOTYPE_OPCODE, v8::internal::DCHECK(), v8::internal::wasm::DecodeError(), v8::internal::wasm::FastZoneVector< T >::empty(), v8::internal::wasm::FastZoneVector< T >::EnsureMoreCapacity(), v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::kControlTryCatch, v8::internal::wasm::IndexImmediate::length, v8::internal::wasm::FastZoneVector< T >::shrink_to(), v8::internal::wasm::WasmTag::sig, v8::internal::sig, v8::internal::wasm::TagIndexImmediate::tag, v8::internal::this, v8::internal::tracing::type, and VALIDATE.
DECODE() [13/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (CatchAll) [inline], [private]
Definition at line 3654 of file function-body-decoder-impl.h.
                   {
    CHECK_PROTOTYPE_OPCODE(legacy_eh);
    // We must have already seen a "try" opcode, so we don't need to check for
    // mixed legacy / new EH instructions again.
    DCHECK(!control_.empty());
    Control* c = &control_.back();
    if (!VALIDATE(c->is_try())) {
      this->DecodeError("catch-all does not match a try");
      return 0;
    }
    if (!VALIDATE(!c->is_try_catchall())) {
      this->error("catch-all already present for try");
      return 0;
    }
    FallThrough();
    c->kind = kControlTryCatchAll;
    c->reachability = control_at(1)->innerReachability();
    current_code_reachable_and_ok_ = VALIDATE(this->ok()) && c->reachable();
    RollbackLocalsInitialization(c);
    current_catch_ = c->previous_catch; // Pop try scope.
    // If there is a throwing instruction in `c`, generate the header for a
    // catch block. Otherwise, the catch block is unreachable.
    if (c->might_throw) {
      CALL_INTERFACE_IF_OK_AND_PARENT_REACHABLE(CatchAll, c);
    } else {
      SetSucceedingCodeDynamicallyUnreachable();
    }
    stack_.shrink_to(c->stack_depth);
    return 1;
  }
References v8::internal::wasm::FastZoneVector< T >::back(), CALL_INTERFACE_IF_OK_AND_PARENT_REACHABLE, CHECK_PROTOTYPE_OPCODE, v8::internal::DCHECK(), v8::internal::wasm::DecodeError(), v8::internal::wasm::FastZoneVector< T >::empty(), v8::internal::wasm::kControlTryCatchAll, v8::internal::wasm::FastZoneVector< T >::shrink_to(), and VALIDATE.
DECODE() [14/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (ContBind) [inline], [private]
Definition at line 4521 of file function-body-decoder-impl.h.
                   {
    CHECK_PROTOTYPE_OPCODE(wasmfx);
    ContIndexImmediate orig_cont_imm(this, this->pc_ + 1, validate);
    if (!this->ValidateCont(this->pc_ + 1, orig_cont_imm)) return 0;
    ContIndexImmediate new_cont_imm(this, this->pc_ + orig_cont_imm.length + 1,
                                    validate);
    if (!this->ValidateCont(this->pc_ + 1, new_cont_imm)) return 0;
    const FunctionSig* orig_cont_sig =
        this->module_->signature(orig_cont_imm.cont_type->contfun_typeindex());
    const FunctionSig* new_cont_sig =
        this->module_->signature(new_cont_imm.cont_type->contfun_typeindex());
    if (!VALIDATE(
            IsSubtypeVec(orig_cont_sig->returns(), new_cont_sig->returns()))) {
      this->DecodeError("expecting returns of %d to match returns of %d",
                        orig_cont_imm.index.index, new_cont_imm.index.index);
      return 0;
    }
    int delta = static_cast<int>(orig_cont_sig->parameters().size()) -
                static_cast<int>(new_cont_sig->parameters().size());
    if (!VALIDATE(delta >= 0)) {
      this->DecodeError(
          "source cont type %d has fewer parameters than target %d",
          orig_cont_imm.index.index, new_cont_imm.index.index);
      return 0;
    }
    const base::Vector<const ValueType> sig_parameters =
        orig_cont_sig->parameters();
    const base::Vector<const ValueType> new_sig_parameters =
        new_cont_sig->parameters();
    if (!VALIDATE(IsSubtypeVec(new_sig_parameters,
                               sig_parameters + static_cast<size_t>(delta)))) {
      this->DecodeError(
          "parameters of new continuation %d should be subtypes of parameters "
          "of input continuation %d",
          new_cont_imm.index.index, orig_cont_imm.index.index);
    }
    Value orig_cont = Pop(ValueType::RefNull(orig_cont_imm.heap_type()));
    PoppedArgVector args = PopSomeArgs(orig_cont_sig, delta);
    Value* new_cont = Push(ValueType::Ref(new_cont_imm.heap_type()));
    CALL_INTERFACE_IF_OK_AND_REACHABLE(ContBind, orig_cont_imm, orig_cont,
                                       args.data(), new_cont_imm, new_cont);
    return 1 + orig_cont_imm.length + new_cont_imm.length;
  }
References v8::base::args, CALL_INTERFACE_IF_OK_AND_REACHABLE, CHECK_PROTOTYPE_OPCODE, v8::internal::wasm::ContIndexImmediate::cont_type, v8::internal::wasm::ContType::contfun_typeindex(), v8::internal::wasm::DecodeError(), v8::internal::wasm::ContIndexImmediate::heap_type(), v8::internal::wasm::TypeIndexImmediate::index, v8::internal::wasm::TypeIndex::index, v8::internal::wasm::TypeIndexImmediate::length, v8::internal::Signature< T >::parameters(), v8::internal::wasm::ValueType::Ref(), v8::internal::wasm::ValueType::RefNull(), v8::internal::Signature< T >::returns(), and VALIDATE.
DECODE() [15/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (ContNew) [inline], [private]
Definition at line 4505 of file function-body-decoder-impl.h.
                  {
    CHECK_PROTOTYPE_OPCODE(wasmfx);
    ContIndexImmediate imm(this, this->pc_ + 1, validate);
    if (!this->ValidateCont(this->pc_ + 1, imm)) return 0;
    // Pop a function type.
    Value func_ref =
        Pop(ValueType::RefNull(imm.cont_type->contfun_typeindex(), imm.shared,
                               RefTypeKind::kFunction));
    // Push a continuation type.
    Value* value = Push(ValueType::Ref(imm.heap_type()));
    CALL_INTERFACE_IF_OK_AND_REACHABLE(ContNew, imm, func_ref, value);
    return 1 + imm.length;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, CHECK_PROTOTYPE_OPCODE, v8::internal::wasm::ContIndexImmediate::cont_type, v8::internal::wasm::ContType::contfun_typeindex(), v8::internal::wasm::ContIndexImmediate::heap_type(), v8::internal::wasm::kFunction, v8::internal::wasm::TypeIndexImmediate::length, v8::internal::wasm::ValueType::Ref(), v8::internal::wasm::ValueType::RefNull(), v8::internal::wasm::ContIndexImmediate::shared, and v8::internal::value.
DECODE() [16/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (Delegate) [inline], [private]
Definition at line 3620 of file function-body-decoder-impl.h.
                   {
    CHECK_PROTOTYPE_OPCODE(legacy_eh);
    // We must have already seen a "try" opcode, so we don't need to check for
    // mixed legacy / new EH instructions again.
    BranchDepthImmediate imm(this, this->pc_ + 1, validate);
    // -1 because the current try block is not included in the count.
    if (!this->Validate(this->pc_ + 1, imm, control_depth() - 1)) return 0;
    Control* c = &control_.back();
    if (!VALIDATE(c->is_incomplete_try())) {
      this->DecodeError("delegate does not match a try");
      return 0;
    }
    // +1 because the current try block is not included in the count.
    uint32_t target_depth = imm.depth + 1;
    while (target_depth < control_depth() - 1 &&
           (!control_at(target_depth)->is_try() ||
            control_at(target_depth)->is_try_catch() ||
            control_at(target_depth)->is_try_catchall())) {
      target_depth++;
    }
    FallThrough();
    if (c->might_throw) {
      CALL_INTERFACE_IF_OK_AND_PARENT_REACHABLE(Delegate, target_depth, c);
      // Delegate propagates the `might_throw` status to the delegated-to block.
      if (control_at(1)->reachable() && target_depth != control_depth() - 1) {
        control_at(target_depth)->might_throw = true;
      }
    }
    current_catch_ = c->previous_catch;
    EndControl();
    PopControl();
    return 1 + imm.length;
  }
References v8::internal::wasm::FastZoneVector< T >::back(), CALL_INTERFACE_IF_OK_AND_PARENT_REACHABLE, CHECK_PROTOTYPE_OPCODE, v8::internal::wasm::DecodeError(), v8::internal::wasm::BranchDepthImmediate::depth, v8::internal::wasm::BranchDepthImmediate::length, and VALIDATE.
DECODE() [17/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (Drop) [inline], [private]
Definition at line 4296 of file function-body-decoder-impl.h.
               {
    Pop();
    CALL_INTERFACE_IF_OK_AND_REACHABLE(Drop);
    return 1;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE.
DECODE() [18/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (Else) [inline], [private]
Definition at line 3899 of file function-body-decoder-impl.h.
               {
    DCHECK(!control_.empty());
    Control* c = &control_.back();
    if (!VALIDATE(c->is_if())) {
      this->DecodeError("else does not match an if");
      return 0;
    }
    if (!VALIDATE(c->is_onearmed_if())) {
      this->DecodeError("else already present for if");
      return 0;
    }
    if (!VALIDATE(TypeCheckFallThru())) return 0;
    c->kind = kControlIfElse;
    CALL_INTERFACE_IF_OK_AND_PARENT_REACHABLE(Else, c);
    if (c->reachable()) c->end_merge.reached = true;
    RollbackLocalsInitialization(c);
    PushMergeValues(c, &c->start_merge);
    c->reachability = control_at(1)->innerReachability();
    current_code_reachable_and_ok_ = VALIDATE(this->ok()) && c->reachable();
    return 1;
  }
References v8::internal::wasm::FastZoneVector< T >::back(), CALL_INTERFACE_IF_OK_AND_PARENT_REACHABLE, v8::internal::DCHECK(), v8::internal::wasm::DecodeError(), v8::internal::wasm::FastZoneVector< T >::empty(), v8::internal::wasm::kControlIfElse, and VALIDATE.
DECODE() [19/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (End) [inline], [private]
Definition at line 3921 of file function-body-decoder-impl.h.
              {
    DCHECK(!control_.empty());
    if constexpr (decoding_mode == kFunctionBody) {
      Control* c = &control_.back();
      if (c->is_incomplete_try()) {
        // Catch-less try, fall through to the implicit catch-all.
        c->kind = kControlTryCatch;
        current_catch_ = c->previous_catch; // Pop try scope.
      }
      if (c->is_try_catch()) {
        // Emulate catch-all + re-throw.
        FallThrough();
        c->reachability = control_at(1)->innerReachability();
        current_code_reachable_and_ok_ = VALIDATE(this->ok()) && c->reachable();
        // Cache `c->might_throw` so we can access it safely after `c`'s
        // destructor is called in `PopContol()`.
        bool might_throw = c->might_throw;
        if (might_throw) {
          CALL_INTERFACE_IF_OK_AND_PARENT_REACHABLE(CatchAll, c);
          CALL_INTERFACE_IF_OK_AND_REACHABLE(Rethrow, c);
        }
        EndControl();
        PopControl();
        // We must mark the parent catch block as `might_throw`, since this
        // conceptually rethrows. Note that we do this regardless of whether
        // the code at this point is reachable.
        if (might_throw && current_catch() != -1) {
          control_at(control_depth_of_current_catch())->might_throw = true;
        }
        return 1;
      }
      if (c->is_onearmed_if()) {
        if (!VALIDATE(TypeCheckOneArmedIf(c))) return 0;
      }
      if (c->is_try_table()) {
        // "Pop" the {current_catch_} index. We did not push it if the block has
        // no handler, so also skip it here in this case.
        if (c->catch_cases.size() > 0) {
          current_catch_ = c->previous_catch;
        }
        FallThrough();
        // Temporarily set the reachability for the catch handlers, and restore
        // it before we actually exit the try block.
        Reachability reachability_at_end = c->reachability;
        c->reachability = control_at(1)->innerReachability();
        current_code_reachable_and_ok_ = VALIDATE(this->ok()) && c->reachable();
        for (CatchCase& catch_case : c->catch_cases) {
          uint32_t stack_size = stack_.size();
          size_t push_count = 0;
          if (catch_case.kind == kCatch || catch_case.kind == kCatchRef) {
            const WasmTagSig* sig = catch_case.maybe_tag.tag_imm.tag->sig;
            stack_.EnsureMoreCapacity(static_cast<int>(sig->parameter_count()),
                                      this->zone_);
            for (ValueType type : sig->parameters()) Push(type);
            push_count = sig->parameter_count();
          }
          if (catch_case.kind == kCatchRef || catch_case.kind == kCatchAllRef) {
            stack_.EnsureMoreCapacity(1, this->zone_);
            Push(ValueType::Ref(kWasmExnRef));
            push_count += 1;
          }
          base::Vector<Value> values(
              stack_.begin() + stack_.size() - push_count, push_count);
          if (c->might_throw) {
            // Already type checked on block entry.
            CALL_INTERFACE_IF_OK_AND_PARENT_REACHABLE(CatchCase, c, catch_case,
                                                      values);
            if (current_code_reachable_and_ok_) {
              Control* target = control_at(catch_case.br_imm.depth);
              target->br_merge()->reached = true;
            }
          }
          stack_.shrink_to(stack_size);
          if (catch_case.kind == kCatchAll || catch_case.kind == kCatchAllRef) {
            break;
          }
        }
        c->reachability = reachability_at_end;
        // If there is no catch-all case, we must mark the parent catch block as
        // `might_throw`, since this conceptually rethrows. Note that we do this
        // regardless of whether the code at this point is reachable.
        if (c->might_throw && !HasCatchAll(c) && current_catch() != -1) {
          control_at(control_depth_of_current_catch())->might_throw = true;
        }
        EndControl();
        PopControl();
        return 1;
      }
    }
    if (control_.size() == 1) {
      // We need to call this first because the interface might set
      // {this->end_}, making the next check pass.
      DoReturn<kStrictCounting, decoding_mode == kFunctionBody
                                    ? kFallthroughMerge
                                    : kInitExprMerge>();
      // If at the last (implicit) control, check we are at end.
      if (!VALIDATE(this->pc_ + 1 == this->end_)) {
        this->DecodeError(this->pc_ + 1, "trailing code after function end");
        return 0;
      }
      // The result of the block is the return value.
      trace_msg->Append("\n" TRACE_INST_FORMAT, startrel(this->pc_),
                        "(implicit) return");
      control_.pop();
      return 1;
    }
    if (!VALIDATE(TypeCheckFallThru())) return 0;
    PopControl();
    return 1;
  }
References v8::internal::wasm::FastZoneVector< T >::back(), v8::internal::wasm::FastZoneVector< T >::begin(), v8::internal::wasm::CatchCase::br_imm, CALL_INTERFACE_IF_OK_AND_PARENT_REACHABLE, CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::DCHECK(), v8::internal::wasm::DecodeError(), v8::internal::wasm::BranchDepthImmediate::depth, v8::internal::wasm::FastZoneVector< T >::empty(), v8::internal::wasm::FastZoneVector< T >::EnsureMoreCapacity(), v8::internal::wasm::kCatch, v8::internal::wasm::kCatchAll, v8::internal::wasm::kCatchAllRef, v8::internal::wasm::kCatchRef, v8::internal::wasm::kControlTryCatch, v8::internal::wasm::kFunctionBody, v8::internal::wasm::CatchCase::kind, v8::internal::wasm::kWasmExnRef, v8::internal::wasm::CatchCase::maybe_tag, v8::internal::wasm::FastZoneVector< T >::pop(), v8::internal::wasm::ValueType::Ref(), v8::internal::wasm::FastZoneVector< T >::shrink_to(), v8::internal::wasm::WasmTag::sig, v8::internal::sig, v8::internal::wasm::FastZoneVector< T >::size(), v8::internal::wasm::TagIndexImmediate::tag, v8::internal::wasm::CatchCase::MaybeTagIndex::tag_imm, v8::internal::this, TRACE_INST_FORMAT, v8::internal::tracing::type, and VALIDATE.
DECODE() [20/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (F32Const) [inline], [private]
Definition at line 4175 of file function-body-decoder-impl.h.
                   {
    ImmF32Immediate imm(this, this->pc_ + 1, validate);
    Value* value = Push(kWasmF32);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(F32Const, value, imm.value);
    return 1 + imm.length;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::wasm::kWasmF32, v8::internal::wasm::ImmF32Immediate::length, v8::internal::value, and v8::internal::wasm::ImmF32Immediate::value.
DECODE() [21/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (F64Const) [inline], [private]
Definition at line 4182 of file function-body-decoder-impl.h.
                   {
    ImmF64Immediate imm(this, this->pc_ + 1, validate);
    Value* value = Push(kWasmF64);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(F64Const, value, imm.value);
    return 1 + imm.length;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::wasm::kWasmF64, v8::internal::wasm::ImmF64Immediate::length, v8::internal::value, and v8::internal::wasm::ImmF64Immediate::value.
DECODE() [22/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (GC) [inline], [private]
Definition at line 4818 of file function-body-decoder-impl.h.
             {
    auto [full_opcode, opcode_length] =
        this->template read_prefixed_opcode<ValidationTag>(this->pc_,
                                                           "gc index");
    trace_msg->AppendOpcode(full_opcode);
    // If we are validating we could have read an illegal opcode. Handle that
    // separately.
    if (!VALIDATE(full_opcode != 0)) {
      DCHECK(this->failed());
      return 0;
    } else if (full_opcode >= kExprStringNewUtf8) {
      CHECK_PROTOTYPE_OPCODE(stringref);
      return DecodeStringRefOpcode(full_opcode, opcode_length);
    } else {
      this->detected_->add_gc();
      return DecodeGCOpcode(full_opcode, opcode_length);
    }
  }
References CHECK_PROTOTYPE_OPCODE, v8::internal::DCHECK(), and VALIDATE.
DECODE() [23/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (GlobalGet) [inline], [private]
Definition at line 4302 of file function-body-decoder-impl.h.
                    {
    GlobalIndexImmediate imm(this, this->pc_ + 1, validate);
    if (!this->Validate(this->pc_ + 1, imm)) return 0;
    Value* result = Push(imm.global->type);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(GlobalGet, result, imm);
    return 1 + imm.length;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::wasm::GlobalIndexImmediate::global, v8::internal::wasm::IndexImmediate::length, v8::base::internal::result, and v8::internal::wasm::WasmGlobal::type.
DECODE() [24/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (GlobalSet) [inline], [private]
Definition at line 4310 of file function-body-decoder-impl.h.
                    {
    GlobalIndexImmediate imm(this, this->pc_ + 1, validate);
    if (!this->Validate(this->pc_ + 1, imm)) return 0;
    if (!VALIDATE(imm.global->mutability)) {
      this->DecodeError("immutable global #%u cannot be assigned", imm.index);
      return 0;
    }
    Value value = Pop(imm.global->type);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(GlobalSet, value, imm);
    return 1 + imm.length;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::wasm::DecodeError(), v8::internal::wasm::GlobalIndexImmediate::global, v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::IndexImmediate::length, v8::internal::wasm::WasmGlobal::mutability, v8::internal::wasm::WasmGlobal::type, VALIDATE, and v8::internal::value.
DECODE() [25/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (I32Const) [inline], [private]
Definition at line 4161 of file function-body-decoder-impl.h.
                   {
    ImmI32Immediate imm(this, this->pc_ + 1, validate);
    Value* value = Push(kWasmI32);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(I32Const, value, imm.value);
    return 1 + imm.length;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::wasm::kWasmI32, v8::internal::wasm::ImmI32Immediate::length, v8::internal::value, and v8::internal::wasm::ImmI32Immediate::value.
DECODE() [26/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (I64Const) [inline], [private]
Definition at line 4168 of file function-body-decoder-impl.h.
                   {
    ImmI64Immediate imm(this, this->pc_ + 1, validate);
    Value* value = Push(kWasmI64);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(I64Const, value, imm.value);
    return 1 + imm.length;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::wasm::kWasmI64, v8::internal::wasm::ImmI64Immediate::length, v8::internal::value, and v8::internal::wasm::ImmI64Immediate::value.
DECODE() [27/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (If) [inline], [private]
Definition at line 3889 of file function-body-decoder-impl.h.
             {
    BlockTypeImmediate imm(this->enabled_, this->detected_, this, this->pc_ + 1,
                           validate);
    if (!this->Validate(this->pc_ + 1, imm)) return 0;
    Value cond = Pop(kWasmI32);
    Control* if_block = PushControl(kControlIf, imm);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(If, cond, if_block);
    return 1 + imm.length;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::wasm::kControlIf, v8::internal::wasm::kWasmI32, and v8::internal::wasm::BlockTypeImmediate::length.
DECODE() [28/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (LoadMem) [inline], [private]
Definition at line 4342 of file function-body-decoder-impl.h.
{ return DecodeLoadMem(GetLoadType(opcode)); }
References v8::internal::wasm::GetLoadType().
DECODE() [29/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (LocalGet) [inline], [private]
Definition at line 4263 of file function-body-decoder-impl.h.
                             {
    IndexImmediate imm(this, this->pc_ + 1, "local index", validate);
    if (!this->ValidateLocal(this->pc_ + 1, imm)) return 0;
    if (!VALIDATE(this->is_local_initialized(imm.index))) {
      this->DecodeError(this->pc_, "uninitialized non-defaultable local: %u",
                        imm.index);
      return 0;
    }
    Value* value = Push(this->local_type(imm.index));
    CALL_INTERFACE_IF_OK_AND_REACHABLE(LocalGet, value, imm);
    return 1 + imm.length;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::wasm::DecodeError(), v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::IndexImmediate::length, VALIDATE, and v8::internal::value.
DECODE() [30/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (LocalSet) [inline], [private]
Definition at line 4276 of file function-body-decoder-impl.h.
                   {
    IndexImmediate imm(this, this->pc_ + 1, "local index", validate);
    if (!this->ValidateLocal(this->pc_ + 1, imm)) return 0;
    Value value = Pop(this->local_type(imm.index));
    CALL_INTERFACE_IF_OK_AND_REACHABLE(LocalSet, value, imm);
    this->set_local_initialized(imm.index);
    return 1 + imm.length;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::IndexImmediate::length, and v8::internal::value.
DECODE() [31/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (LocalTee) [inline], [private]
Definition at line 4285 of file function-body-decoder-impl.h.
                   {
    IndexImmediate imm(this, this->pc_ + 1, "local index", validate);
    if (!this->ValidateLocal(this->pc_ + 1, imm)) return 0;
    ValueType local_type = this->local_type(imm.index);
    Value value = Pop(local_type);
    Value* result = Push(local_type);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(LocalTee, value, result, imm);
    this->set_local_initialized(imm.index);
    return 1 + imm.length;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::IndexImmediate::length, v8::base::internal::result, and v8::internal::value.
DECODE() [32/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (Loop) [inline], [private]
Definition at line 3875 of file function-body-decoder-impl.h.
               {
    BlockTypeImmediate imm(this->enabled_, this->detected_, this, this->pc_ + 1,
                           validate);
    if (!this->Validate(this->pc_ + 1, imm)) return 0;
    Control* block = PushControl(kControlLoop, imm);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(Loop, block);
    // Loops have a merge point at block entry, hence push the merge values
    // (Phis in case of TurboFan) after calling the interface.
    // TODO(clemensb): Can we skip this (and the related PushMergeValues in
    // PopControl) for Liftoff?
    PushMergeValues(block, &block->start_merge);
    return 1 + imm.length;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::wasm::kControlLoop, and v8::internal::wasm::BlockTypeImmediate::length.
DECODE() [33/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (MemoryGrow) [inline], [private]
Definition at line 4346 of file function-body-decoder-impl.h.
                     {
    // This opcode will not be emitted by the asm translator.
    DCHECK_EQ(kWasmOrigin, this->module_->origin);
    MemoryIndexImmediate imm(this, this->pc_ + 1, validate);
    if (!this->Validate(this->pc_ + 1, imm)) return 0;
    ValueType mem_type = MemoryAddressType(imm.memory);
    Value value = Pop(mem_type);
    Value* result = Push(mem_type);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(MemoryGrow, imm, value, result);
    return 1 + imm.length;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, DCHECK_EQ, v8::internal::wasm::kWasmOrigin, v8::internal::wasm::IndexImmediate::length, v8::internal::wasm::MemoryIndexImmediate::memory, v8::base::internal::result, and v8::internal::value.
DECODE() [34/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (MemorySize) [inline], [private]
Definition at line 4358 of file function-body-decoder-impl.h.
                     {
    MemoryIndexImmediate imm(this, this->pc_ + 1, validate);
    if (!this->Validate(this->pc_ + 1, imm)) return 0;
    ValueType result_type = MemoryAddressType(imm.memory);
    Value* result = Push(result_type);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(CurrentMemoryPages, imm, result);
    return 1 + imm.length;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::wasm::IndexImmediate::length, v8::internal::wasm::MemoryIndexImmediate::memory, and v8::base::internal::result.
DECODE() [35/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (Nop) [inline], [private]
Definition at line 3483 of file function-body-decoder-impl.h.
{ return 1; }
DECODE() [36/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (NopForTestingUnsupportedInLiftoff) [inline], [private]
Definition at line 3485 of file function-body-decoder-impl.h.
                                            {
    if (!VALIDATE(v8_flags.enable_testing_opcode_in_wasm)) {
      this->DecodeError("Invalid opcode 0x%x", opcode);
      return 0;
    }
    CALL_INTERFACE_IF_OK_AND_REACHABLE(NopForTestingUnsupportedInLiftoff);
    // Return {0} if we failed, to not advance the pc past the end.
    if (this->failed()) {
      DCHECK_EQ(this->pc_, this->end_);
      return 0;
    }
    return 1;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, DCHECK_EQ, v8::internal::wasm::DecodeError(), v8::internal::v8_flags, and VALIDATE.
DECODE() [37/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (Numeric) [inline], [private]
Definition at line 4769 of file function-body-decoder-impl.h.
                  {
    auto [full_opcode, opcode_length] =
        this->template read_prefixed_opcode<ValidationTag>(this->pc_,
                                                           "numeric index");
    if (full_opcode == kExprTableGrow || full_opcode == kExprTableSize ||
        full_opcode == kExprTableFill) {
      this->detected_->add_reftypes();
    }
    trace_msg->AppendOpcode(full_opcode);
    return DecodeNumericOpcode(full_opcode, opcode_length);
  }
DECODE() [38/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (RefAsNonNull) [inline], [private]
Definition at line 4241 of file function-body-decoder-impl.h.
                       {
    this->detected_->add_typed_funcref();
    Value value = Pop();
    switch (value.type.kind()) {
      case kBottom:
        // We are in unreachable code. Forward the bottom value.
      case kRef:
        // A non-nullable value can remain as-is.
        Push(value);
        return 1;
      case kRefNull: {
        Value* result = Push(ValueType::Ref(value.type.heap_type()));
        CALL_INTERFACE_IF_OK_AND_REACHABLE(RefAsNonNull, value, result);
        return 1;
      }
      default:
        if constexpr (!ValidationTag::validate) UNREACHABLE();
        PopTypeError(0, value, "reference type");
        return 0;
    }
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::kRef, v8::internal::kRefNull, v8::internal::wasm::ValueType::Ref(), v8::base::internal::result, v8::internal::UNREACHABLE(), and v8::internal::value.
DECODE() [39/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (RefEq) [inline], [private]
Definition at line 4461 of file function-body-decoder-impl.h.
                {
    this->detected_->add_gc();
    Value rhs = Pop();
    Value lhs = Pop();
    if (!VALIDATE(
            IsSubtypeOf(lhs.type.AsNonShared(), kWasmEqRef, this->module_) ||
            control_.back().unreachable())) {
      this->DecodeError(this->pc_,
                        "ref.eq[0] expected either eqref or (ref null shared "
                        "eq), found %s of type %s",
                        SafeOpcodeNameAt(lhs.pc()), lhs.type.name().c_str());
      return 0;
    }
    if (!VALIDATE(
            IsSubtypeOf(rhs.type.AsNonShared(), kWasmEqRef, this->module_) ||
            control_.back().unreachable())) {
      this->DecodeError(this->pc_,
                        "ref.eq[1] expected either eqref or (ref null shared "
                        "eq), found %s of type %s",
                        SafeOpcodeNameAt(rhs.pc()), rhs.type.name().c_str());
      return 0;
    }
    if (!VALIDATE(lhs.type.is_shared() == rhs.type.is_shared() ||
                  control_.back().unreachable())) {
      this->DecodeError(this->pc_,
                        "ref.eq: sharedness of both operands must match");
      return 0;
    }
    Value* result = Push(kWasmI32);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(BinOp, kExprRefEq, lhs, rhs, result);
    return 1;
  }
References v8::internal::wasm::FastZoneVector< T >::back(), CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::wasm::DecodeError(), v8::internal::wasm::IsSubtypeOf(), v8::internal::wasm::kWasmEqRef, v8::internal::wasm::kWasmI32, v8::base::internal::result, v8::internal::this, and VALIDATE.
DECODE() [40/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (RefFunc) [inline], [private]
Definition at line 4228 of file function-body-decoder-impl.h.
                  {
    this->detected_->add_reftypes();
    IndexImmediate imm(this, this->pc_ + 1, "function index", validate);
    if (!this->ValidateFunction(this->pc_ + 1, imm)) return 0;
    ModuleTypeIndex index = this->module_->functions[imm.index].sig_index;
    const TypeDefinition& type_def = this->module_->type(index);
    Value* value =
        Push(ValueType::Ref(index, type_def.is_shared, RefTypeKind::kFunction)
                 .AsExactIfEnabled(this->enabled_));
    CALL_INTERFACE_IF_OK_AND_REACHABLE(RefFunc, imm.index, value);
    return 1 + imm.length;
  }
References v8::internal::wasm::ValueType::AsExactIfEnabled(), CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::index, v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::TypeDefinition::is_shared, v8::internal::wasm::kFunction, v8::internal::wasm::IndexImmediate::length, v8::internal::wasm::ValueType::Ref(), v8::internal::this, and v8::internal::value.
DECODE() [41/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (RefIsNull) [inline], [private]
Definition at line 4206 of file function-body-decoder-impl.h.
                    {
    this->detected_->add_reftypes();
    Value value = Pop();
    Value* result = Push(kWasmI32);
    switch (value.type.kind()) {
      case kRefNull:
        CALL_INTERFACE_IF_OK_AND_REACHABLE(UnOp, kExprRefIsNull, value, result);
        return 1;
      case kBottom:
        // We are in unreachable code, the return value does not matter.
      case kRef:
        // For non-nullable references, the result is always false.
        CALL_INTERFACE_IF_OK_AND_REACHABLE(Drop);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(I32Const, result, 0);
        return 1;
      default:
        if constexpr (!ValidationTag::validate) UNREACHABLE();
        PopTypeError(0, value, "reference type");
        return 0;
    }
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::kRef, v8::internal::kRefNull, v8::internal::wasm::kWasmI32, v8::base::internal::result, v8::internal::UNREACHABLE(), and v8::internal::value.
DECODE() [42/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (RefNull) [inline], [private]
Definition at line 4189 of file function-body-decoder-impl.h.
                  {
    this->detected_->add_reftypes();
    HeapTypeImmediate imm(this->enabled_, this->detected_, this, this->pc_ + 1,
                          validate);
    if (!this->Validate(this->pc_ + 1, imm)) return 0;
    if (!VALIDATE(!this->enabled_.has_stringref() ||
                  !imm.type.is_string_view())) {
      this->DecodeError(this->pc_ + 1, "cannot create null string view");
      return 0;
    }
    ValueType type = ValueType::RefNull(imm.type);
    if (type.has_index()) type = type.AsExactIfEnabled(this->enabled_);
    Value* value = Push(type);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(RefNull, type, value);
    return 1 + imm.length;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::wasm::DecodeError(), v8::internal::wasm::ValueTypeBase::is_string_view(), v8::internal::wasm::HeapTypeImmediate::length, v8::internal::wasm::ValueType::RefNull(), v8::internal::tracing::type, v8::internal::wasm::HeapTypeImmediate::type, VALIDATE, and v8::internal::value.
DECODE() [43/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (Resume) [inline], [private]
Definition at line 4623 of file function-body-decoder-impl.h.
                 {
    CHECK_PROTOTYPE_OPCODE(wasmfx);
    ContIndexImmediate imm(this, this->pc_ + 1, validate);
    if (!this->ValidateCont(this->pc_ + 1, imm)) return 0;
    Pop(ValueType::RefNull(imm.heap_type()));
    EffectHandlerTableImmediate handler_table_imm(
        this, this->pc_ + 1 + imm.length, validate);
    if (!this->Validate(this->pc_ + imm.length + 1, handler_table_imm))
      return 0;
    base::Vector<HandlerCase> handlers =
        this->zone_->template AllocateVector<HandlerCase>(
            handler_table_imm.table_count);
    int table_length = DecodeEffectHandlerTable(handler_table_imm, handlers);
    if (table_length < 0) return 0;
    // Continuations are function-like values; check the args and returns.
    const FunctionSig* contFunSig =
        this->module_->signature(imm.cont_type->contfun_typeindex());
    PoppedArgVector args = PopArgs(contFunSig);
    Value* returns = PushReturns(contFunSig);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(Resume, imm, handlers, args.data(),
                                       returns);
    return 1 + imm.length + table_length;
  }
References v8::base::args, CALL_INTERFACE_IF_OK_AND_REACHABLE, CHECK_PROTOTYPE_OPCODE, v8::internal::wasm::ContIndexImmediate::cont_type, v8::internal::wasm::ContType::contfun_typeindex(), v8::internal::wasm::ContIndexImmediate::heap_type(), v8::internal::wasm::TypeIndexImmediate::length, wasm::anonymous_namespace{c-api.cc}::PopArgs(), v8::internal::wasm::ValueType::RefNull(), and v8::internal::wasm::BranchTableImmediate::table_count.
DECODE() [44/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (ResumeThrow) [inline], [private]
Definition at line 4653 of file function-body-decoder-impl.h.
                      {
    CHECK_PROTOTYPE_OPCODE(wasmfx);
    ContIndexImmediate cont_imm(this, this->pc_ + 1, validate);
    if (!this->ValidateCont(this->pc_ + 1, cont_imm)) return 0;
    Pop(ValueType::RefNull(cont_imm.heap_type()));
    TagIndexImmediate exc_imm(this, this->pc_ + cont_imm.length + 1, validate);
    if (!this->Validate(this->pc_ + cont_imm.length + 1, exc_imm)) return 0;
    if (exc_imm.tag->sig->return_count() != 0) {
      this->DecodeError("tag signature %u has non-void return", exc_imm.index);
      return 0;
    }
    PoppedArgVector args = PopArgs(exc_imm.tag->ToFunctionSig());
    EffectHandlerTableImmediate handler_table_imm(
        this, this->pc_ + cont_imm.length + exc_imm.length + 1, validate);
    if (!this->Validate(this->pc_ + cont_imm.length + exc_imm.length + 1,
                        handler_table_imm))
      return 0;
    base::Vector<HandlerCase> handlers =
        this->zone_->template AllocateVector<HandlerCase>(
            handler_table_imm.table_count);
    int table_length = DecodeEffectHandlerTable(handler_table_imm, handlers);
    if (table_length < 0) return 0;
    // The continuation might return, check the return type.
    const FunctionSig* contFunSig =
        this->module_->signature(cont_imm.cont_type->contfun_typeindex());
    Value* returns = PushReturns(contFunSig);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(ResumeThrow, cont_imm, exc_imm, handlers,
                                       args.data(), returns);
    return 1 + exc_imm.length + cont_imm.length + table_length;
  }
References v8::base::args, CALL_INTERFACE_IF_OK_AND_REACHABLE, CHECK_PROTOTYPE_OPCODE, v8::internal::wasm::ContIndexImmediate::cont_type, v8::internal::wasm::ContType::contfun_typeindex(), v8::internal::wasm::DecodeError(), v8::internal::wasm::ContIndexImmediate::heap_type(), v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::IndexImmediate::length, v8::internal::wasm::TypeIndexImmediate::length, wasm::anonymous_namespace{c-api.cc}::PopArgs(), v8::internal::wasm::ValueType::RefNull(), v8::internal::Signature< T >::return_count(), v8::internal::wasm::WasmTag::sig, v8::internal::wasm::BranchTableImmediate::table_count, v8::internal::wasm::TagIndexImmediate::tag, and v8::internal::wasm::WasmTag::ToFunctionSig().
DECODE() [45/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (Rethrow) [inline], [private]
Definition at line 3523 of file function-body-decoder-impl.h.
                  {
    CHECK_PROTOTYPE_OPCODE(legacy_eh);
    BranchDepthImmediate imm(this, this->pc_ + 1, validate);
    if (!this->Validate(this->pc_ + 1, imm, control_.size())) return 0;
    Control* c = control_at(imm.depth);
    if (!VALIDATE(c->is_try_catchall() || c->is_try_catch())) {
      this->error("rethrow not targeting catch or catch-all");
      return 0;
    }
    CALL_INTERFACE_IF_OK_AND_REACHABLE(Rethrow, c);
    MarkMightThrow();
    EndControl();
    return 1 + imm.length;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, CHECK_PROTOTYPE_OPCODE, v8::internal::wasm::BranchDepthImmediate::depth, v8::internal::wasm::BranchDepthImmediate::length, v8::internal::wasm::FastZoneVector< T >::size(), and VALIDATE.
DECODE() [46/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (Return) [inline], [private]
Definition at line 4151 of file function-body-decoder-impl.h.
                 {
    return DoReturn<kNonStrictCounting, kReturnMerge>() ? 1 : 0;
  }
DECODE() [47/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (ReturnCall) [inline], [private]
Definition at line 4393 of file function-body-decoder-impl.h.
                     {
    this->detected_->add_return_call();
    CallFunctionImmediate imm(this, this->pc_ + 1, validate);
    if (!this->Validate(this->pc_ + 1, imm)) return 0;
    if (!VALIDATE(this->CanReturnCall(imm.sig))) {
      this->DecodeError("%s: %s", WasmOpcodes::OpcodeName(kExprReturnCall),
                        "tail call type error");
      return 0;
    }
    PoppedArgVector args = PopArgs(imm.sig);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(ReturnCall, imm, args.data());
    EndControl();
    return 1 + imm.length;
  }
References v8::base::args, CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::wasm::DecodeError(), v8::internal::wasm::IndexImmediate::length, v8::internal::wasm::WasmOpcodes::OpcodeName(), wasm::anonymous_namespace{c-api.cc}::PopArgs(), v8::internal::wasm::CallFunctionImmediate::sig, and VALIDATE.
DECODE() [48/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (ReturnCallIndirect) [inline], [private]
Definition at line 4408 of file function-body-decoder-impl.h.
                             {
    this->detected_->add_return_call();
    CallIndirectImmediate imm(this, this->pc_ + 1, validate);
    if (!this->Validate(this->pc_ + 1, imm)) return 0;
    if (!VALIDATE(this->CanReturnCall(imm.sig))) {
      this->DecodeError("%s: %s",
                        WasmOpcodes::OpcodeName(kExprReturnCallIndirect),
                        "tail call return types mismatch");
      return 0;
    }
    Value index = Pop(TableAddressType(imm.table_imm.table));
    PoppedArgVector args = PopArgs(imm.sig);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(ReturnCallIndirect, index, imm,
                                       args.data());
    EndControl();
    if (!this->module_->type(imm.sig_imm.index).is_final) {
      // In this case we emit an rtt.canon as part of the indirect call.
      this->detected_->add_gc();
    }
    return 1 + imm.length;
  }
References v8::base::args, CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::wasm::DecodeError(), v8::internal::index, v8::internal::wasm::TypeIndexImmediate::index, v8::internal::wasm::CallIndirectImmediate::length, v8::internal::wasm::WasmOpcodes::OpcodeName(), wasm::anonymous_namespace{c-api.cc}::PopArgs(), v8::internal::wasm::CallIndirectImmediate::sig, v8::internal::wasm::CallIndirectImmediate::sig_imm, v8::internal::wasm::TableIndexImmediate::table, v8::internal::wasm::CallIndirectImmediate::table_imm, and VALIDATE.
DECODE() [49/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (ReturnCallRef) [inline], [private]
Definition at line 4443 of file function-body-decoder-impl.h.
                        {
    this->detected_->add_typed_funcref();
    this->detected_->add_return_call();
    SigIndexImmediate imm(this, this->pc_ + 1, validate);
    if (!this->Validate(this->pc_ + 1, imm)) return 0;
    if (!VALIDATE(this->CanReturnCall(imm.sig))) {
      this->DecodeError("%s: %s", WasmOpcodes::OpcodeName(kExprReturnCallRef),
                        "tail call return types mismatch");
      return 0;
    }
    Value func_ref = Pop(ValueType::RefNull(imm.heap_type()));
    PoppedArgVector args = PopArgs(imm.sig);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(ReturnCallRef, func_ref, imm.sig,
                                       args.data());
    EndControl();
    return 1 + imm.length;
  }
References v8::base::args, CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::wasm::DecodeError(), v8::internal::wasm::SigIndexImmediate::heap_type(), v8::internal::wasm::TypeIndexImmediate::length, v8::internal::wasm::WasmOpcodes::OpcodeName(), wasm::anonymous_namespace{c-api.cc}::PopArgs(), v8::internal::wasm::ValueType::RefNull(), v8::internal::wasm::SigIndexImmediate::sig, and VALIDATE.
DECODE() [50/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (Select) [inline], [private]
Definition at line 4034 of file function-body-decoder-impl.h.
                 {
    auto [tval, fval, cond] = Pop(kWasmBottom, kWasmBottom, kWasmI32);
    ValueType result_type = tval.type;
    if (result_type == kWasmBottom) {
      result_type = fval.type;
    } else {
      ValidateStackValue(1, fval, result_type);
    }
    if (!VALIDATE(!result_type.is_reference())) {
      this->DecodeError(
          "select without type is only valid for value type inputs");
      return 0;
    }
    Value* result = Push(result_type);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(Select, cond, fval, tval, result);
    return 1;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::wasm::DecodeError(), v8::internal::wasm::ValueTypeBase::is_reference(), v8::internal::wasm::kWasmBottom, v8::internal::wasm::kWasmI32, v8::base::internal::result, and VALIDATE.
DECODE() [51/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (SelectWithType) [inline], [private]
Definition at line 4052 of file function-body-decoder-impl.h.
                         {
    this->detected_->add_reftypes();
    SelectTypeImmediate imm(this->enabled_, this->detected_, this,
                            this->pc_ + 1, validate);
    if (!this->Validate(this->pc_ + 1, imm)) return 0;
    auto [tval, fval, cond] = Pop(imm.type, imm.type, kWasmI32);
    Value* result = Push(imm.type);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(Select, cond, fval, tval, result);
    return 1 + imm.length;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::wasm::kWasmI32, v8::internal::wasm::SelectTypeImmediate::length, v8::base::internal::result, and v8::internal::wasm::SelectTypeImmediate::type.
DECODE() [52/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (Simd) [inline], [private]
Definition at line 4789 of file function-body-decoder-impl.h.
               {
    this->detected_->add_simd();
    if (!CheckHardwareSupportsSimd()) {
      if (v8_flags.correctness_fuzzer_suppressions) {
        FATAL("Aborting on missing Wasm SIMD support");
      }
      this->DecodeError("Wasm SIMD unsupported");
      return 0;
    }
    auto [full_opcode, opcode_length] =
        this->template read_prefixed_opcode<ValidationTag>(this->pc_);
    if (!VALIDATE(this->ok())) return 0;
    trace_msg->AppendOpcode(full_opcode);
    if (WasmOpcodes::IsFP16SimdOpcode(full_opcode)) {
      this->detected_->add_fp16();
    } else if (WasmOpcodes::IsRelaxedSimdOpcode(full_opcode)) {
      this->detected_->add_relaxed_simd();
    }
    return DecodeSimdOpcode(full_opcode, opcode_length);
  }
References v8::internal::wasm::CheckHardwareSupportsSimd(), v8::internal::wasm::DecodeError(), FATAL, v8::internal::wasm::WasmOpcodes::IsFP16SimdOpcode(), v8::internal::wasm::WasmOpcodes::IsRelaxedSimdOpcode(), v8::internal::v8_flags, and VALIDATE.
DECODE() [53/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (StoreMem) [inline], [private]
Definition at line 4344 of file function-body-decoder-impl.h.
{ return DecodeStoreMem(GetStoreType(opcode)); }
References v8::internal::wasm::GetStoreType().
DECODE() [54/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (Suspend) [inline], [private]
Definition at line 4691 of file function-body-decoder-impl.h.
                  {
    CHECK_PROTOTYPE_OPCODE(wasmfx);
    TagIndexImmediate imm(this, this->pc_ + 1, validate);
    if (!this->Validate(this->pc_ + 1, imm)) return 0;
    const FunctionSig* sig = imm.tag->ToFunctionSig();
    PoppedArgVector args = PopArgs(sig);
    Value* returns = PushReturns(sig);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(Suspend, imm, args.data(), returns);
    return 1 + imm.length;
  }
References v8::base::args, CALL_INTERFACE_IF_OK_AND_REACHABLE, CHECK_PROTOTYPE_OPCODE, v8::internal::wasm::IndexImmediate::length, wasm::anonymous_namespace{c-api.cc}::PopArgs(), v8::internal::sig, v8::internal::wasm::TagIndexImmediate::tag, and v8::internal::wasm::WasmTag::ToFunctionSig().
DECODE() [55/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (Switch) [inline], [private]
Definition at line 4707 of file function-body-decoder-impl.h.
                 {
    CHECK_PROTOTYPE_OPCODE(wasmfx);
    ContIndexImmediate contimm(this, this->pc_ + 1, validate);
    if (!this->ValidateCont(this->pc_ + 1, contimm)) return 0;
    TagIndexImmediate tagimm(this, this->pc_ + contimm.length + 1, validate);
    if (!this->Validate(this->pc_ + contimm.length + 1, tagimm)) return 0;
    const FunctionSig* tag_sig = tagimm.tag->ToFunctionSig();
    const FunctionSig* cont_sig =
        this->module_->signature(contimm.cont_type->contfun_typeindex());
    if (!VALIDATE(IsSubtypeVec(cont_sig->returns(), tag_sig->returns()))) {
      this->DecodeError("return(s) from continuation %d do not match tag %d",
                        contimm.index.index, tagimm.index);
      return 0;
    }
    const base::Vector<const ValueType> cont_args = cont_sig->parameters();
    if (!VALIDATE(cont_args.size() >= 1 &&
                  IsSubtypeOf(cont_args.last(), kWasmContRef, this->module_))) {
      this->DecodeError(
          "expecting a (ref null? cont) as last parameter of type %d",
          contimm.index.index);
      return 0;
    }
    const ValueType return_type = cont_args.last();
    if (!VALIDATE(return_type.has_index() &&
                  this->module_->has_cont_type(return_type.ref_index()))) {
      this->DecodeError(
          "expecting a defined cont type as last parameter of type %d",
          contimm.index.index);
      return 0;
    }
    const ContType* return_cont =
        this->module_->cont_type(return_type.ref_index());
    const FunctionSig* return_sig =
        this->module_->signature(return_cont->contfun_typeindex());
    if (!VALIDATE(IsSubtypeVec(tag_sig->returns(), return_sig->returns()))) {
      this->DecodeError(
          "tag %d's return types should be a subtype of return continuation "
          "%d's return types",
          tagimm.index, cont_args.last().ref_index().index);
      return 0;
    }
    Value cont_ref = Pop(ValueType::RefNull(contimm.heap_type()));
    PoppedArgVector args =
        PopSomeArgs(cont_sig, static_cast<int>(cont_args.size()) - 1);
    Value* returns = PushParameters(return_sig);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(Switch, tagimm, contimm, cont_ref,
                                       args.data(), returns);
    return 1 + contimm.length + tagimm.length;
  }
References v8::base::args, CALL_INTERFACE_IF_OK_AND_REACHABLE, CHECK_PROTOTYPE_OPCODE, v8::internal::wasm::ContIndexImmediate::cont_type, v8::internal::wasm::ContType::contfun_typeindex(), v8::internal::wasm::DecodeError(), v8::internal::wasm::ValueTypeBase::has_index(), v8::internal::wasm::ContIndexImmediate::heap_type(), v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::TypeIndexImmediate::index, v8::internal::wasm::TypeIndex::index, v8::internal::wasm::IsSubtypeOf(), v8::internal::wasm::kWasmContRef, v8::base::Vector< T >::last(), v8::internal::wasm::IndexImmediate::length, v8::internal::wasm::TypeIndexImmediate::length, v8::internal::Signature< T >::parameters(), v8::internal::wasm::ValueType::ref_index(), v8::internal::wasm::ValueType::RefNull(), v8::internal::Signature< T >::returns(), v8::base::Vector< T >::size(), v8::internal::wasm::TagIndexImmediate::tag, v8::internal::this, v8::internal::wasm::WasmTag::ToFunctionSig(), and VALIDATE.
DECODE() [56/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (TableGet) [inline], [private]
Definition at line 4322 of file function-body-decoder-impl.h.
                   {
    this->detected_->add_reftypes();
    TableIndexImmediate imm(this, this->pc_ + 1, validate);
    if (!this->Validate(this->pc_ + 1, imm)) return 0;
    Value index = Pop(TableAddressType(imm.table));
    Value* result = Push(imm.table->type);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(TableGet, index, result, imm);
    return 1 + imm.length;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::index, v8::internal::wasm::IndexImmediate::length, v8::base::internal::result, v8::internal::wasm::TableIndexImmediate::table, unibrow::TableGet(), and v8::internal::wasm::WasmTable::type.
DECODE() [57/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (TableSet) [inline], [private]
Definition at line 4332 of file function-body-decoder-impl.h.
                   {
    this->detected_->add_reftypes();
    TableIndexImmediate imm(this, this->pc_ + 1, validate);
    if (!this->Validate(this->pc_ + 1, imm)) return 0;
    ValueType table_address_type = TableAddressType(imm.table);
    auto [index, value] = Pop(table_address_type, imm.table->type);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(TableSet, index, value, imm);
    return 1 + imm.length;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::index, v8::internal::wasm::IndexImmediate::length, v8::internal::wasm::TableIndexImmediate::table, v8::internal::wasm::WasmTable::type, and v8::internal::value.
DECODE() [58/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (Throw) [inline], [private]
Definition at line 3538 of file function-body-decoder-impl.h.
                {
    // Do not update the detected feature set. This instruction is used by both
    // the legacy and new EH proposals, so there is no way to know which
    // one the module is using from this instruction alone.
    TagIndexImmediate imm(this, this->pc_ + 1, validate);
    if (!this->Validate(this->pc_ + 1, imm)) return 0;
    if (imm.tag->sig->return_count() != 0) {
      this->DecodeError("tag signature %u has non-void return", imm.index);
      return 0;
    }
    PoppedArgVector args = PopArgs(imm.tag->ToFunctionSig());
    CALL_INTERFACE_IF_OK_AND_REACHABLE(Throw, imm, args.data());
    MarkMightThrow();
    EndControl();
    return 1 + imm.length;
  }
References v8::base::args, CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::wasm::DecodeError(), v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::IndexImmediate::length, wasm::anonymous_namespace{c-api.cc}::PopArgs(), v8::internal::Signature< T >::return_count(), v8::internal::wasm::WasmTag::sig, v8::internal::wasm::TagIndexImmediate::tag, and v8::internal::wasm::WasmTag::ToFunctionSig().
DECODE() [59/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (ThrowRef) [inline], [private]
Definition at line 3768 of file function-body-decoder-impl.h.
                   {
    CHECK_PROTOTYPE_OPCODE(exnref);
    if (!VALIDATE(!this->detected_->has_legacy_eh() ||
                  v8_flags.wasm_allow_mixed_eh_for_testing)) {
      this->DecodeError(
          "module uses a mix of legacy and new exception handling "
          "instructions");
      return 0;
    }
    Value value = Pop(kWasmExnRef);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(ThrowRef, &value);
    MarkMightThrow();
    EndControl();
    return 1;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, CHECK_PROTOTYPE_OPCODE, v8::internal::wasm::DecodeError(), v8::internal::wasm::kWasmExnRef, v8::internal::v8_flags, VALIDATE, and v8::internal::value.
DECODE() [60/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (Try) [inline], [private]
Definition at line 3555 of file function-body-decoder-impl.h.
              {
    CHECK_PROTOTYPE_OPCODE(legacy_eh);
    if (!VALIDATE(!this->detected_->has_exnref() ||
                  v8_flags.wasm_allow_mixed_eh_for_testing)) {
      this->DecodeError(
          "module uses a mix of legacy and new exception handling "
          "instructions");
      return 0;
    }
    BlockTypeImmediate imm(this->enabled_, this->detected_, this, this->pc_ + 1,
                           validate);
    if (!this->Validate(this->pc_ + 1, imm)) return 0;
    Control* try_block = PushControl(kControlTry, imm);
    try_block->previous_catch = current_catch_;
    current_catch_ = static_cast<int>(control_depth() - 1);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(Try, try_block);
    return 1 + imm.length;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, CHECK_PROTOTYPE_OPCODE, v8::internal::wasm::DecodeError(), v8::internal::wasm::kControlTry, v8::internal::wasm::BlockTypeImmediate::length, v8::internal::v8_flags, and VALIDATE.
DECODE() [61/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (TryTable) [inline], [private]
Definition at line 3685 of file function-body-decoder-impl.h.
                   {
    CHECK_PROTOTYPE_OPCODE(exnref);
    if (!VALIDATE(!this->detected_->has_legacy_eh() ||
                  v8_flags.wasm_allow_mixed_eh_for_testing)) {
      this->DecodeError(
          "module uses a mix of legacy and new exception handling "
          "instructions");
      return 0;
    }
    BlockTypeImmediate block_imm(this->enabled_, this->detected_, this,
                                 this->pc_ + 1, validate);
    if (!this->Validate(this->pc_ + 1, block_imm)) return 0;
    Control* try_block = PushControl(kControlTryTable, block_imm);
    TryTableImmediate try_table_imm(this, this->pc_ + 1 + block_imm.length,
                                    validate);
    if (try_table_imm.table_count > 0) {
      try_block->previous_catch = current_catch_;
      current_catch_ = static_cast<int>(control_depth() - 1);
    }
    if (!this->Validate(this->pc_ + 2, try_table_imm)) return 0;
    TryTableIterator<ValidationTag> try_table_iterator(this, try_table_imm);
    try_block->catch_cases = this->zone_->template AllocateVector<CatchCase>(
        try_table_imm.table_count);
    int i = 0;
    while (try_table_iterator.has_next()) {
      CatchCase catch_case = try_table_iterator.next();
      if (!VALIDATE(catch_case.kind <= kLastCatchKind)) {
        this->DecodeError("invalid catch kind in try table");
        return 0;
      }
      if ((catch_case.kind == kCatch || catch_case.kind == kCatchRef)) {
        if (!this->Validate(this->pc_, catch_case.maybe_tag.tag_imm)) {
          return 0;
        }
        const WasmTagSig* sig = catch_case.maybe_tag.tag_imm.tag->sig;
        if (sig->return_count() != 0) {
          // tags can have return values, so we have to check.
          this->DecodeError("tag signature %u has non-void return",
                            catch_case.maybe_tag.tag_imm.index);
          return 0;
        }
      }
      catch_case.br_imm.depth += 1;
      if (!this->Validate(this->pc_, catch_case.br_imm, control_.size())) {
        return 0;
      }
      uint32_t stack_size = stack_.size();
      uint32_t push_count = 0;
      if (catch_case.kind == kCatch || catch_case.kind == kCatchRef) {
        const WasmTagSig* sig = catch_case.maybe_tag.tag_imm.tag->sig;
        stack_.EnsureMoreCapacity(static_cast<int>(sig->parameter_count()),
                                  this->zone_);
        for (ValueType type : sig->parameters()) Push(type);
        push_count += sig->parameter_count();
      }
      if (catch_case.kind == kCatchRef || catch_case.kind == kCatchAllRef) {
        stack_.EnsureMoreCapacity(1, this->zone_);
        Push(ValueType::Ref(kWasmExnRef));
        push_count += 1;
      }
      Control* target = control_at(catch_case.br_imm.depth);
      if (!VALIDATE(push_count == target->br_merge()->arity)) {
        this->DecodeError(
            "catch kind generates %d operand%s, target block expects %d",
            push_count, push_count != 1 ? "s" : "", target->br_merge()->arity);
        return 0;
      }
      if (!VALIDATE(
              (TypeCheckBranch<PushBranchValues::kYes, RewriteStackTypes::kNo>(
                  target)))) {
        return 0;
      }
      stack_.shrink_to(stack_size);
      DCHECK_LT(i, try_table_imm.table_count);
      try_block->catch_cases[i] = catch_case;
      ++i;
    }
    uint32_t try_table_length = try_table_iterator.length();
    CALL_INTERFACE_IF_OK_AND_REACHABLE(TryTable, try_block);
    return 1 + block_imm.length + try_table_length;
  }
References v8::internal::wasm::CatchCase::br_imm, CALL_INTERFACE_IF_OK_AND_REACHABLE, CHECK_PROTOTYPE_OPCODE, DCHECK_LT, v8::internal::wasm::DecodeError(), v8::internal::wasm::BranchDepthImmediate::depth, v8::internal::wasm::FastZoneVector< T >::EnsureMoreCapacity(), v8::internal::wasm::TryTableIterator< ValidationTag >::has_next(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::kCatch, v8::internal::wasm::kCatchAllRef, v8::internal::wasm::kCatchRef, v8::internal::wasm::kControlTryTable, v8::internal::wasm::CatchCase::kind, v8::internal::wasm::kLastCatchKind, v8::internal::wasm::kWasmExnRef, v8::internal::wasm::BlockTypeImmediate::length, v8::internal::wasm::TryTableIterator< ValidationTag >::length(), v8::internal::wasm::CatchCase::maybe_tag, v8::internal::wasm::TryTableIterator< ValidationTag >::next(), v8::internal::wasm::ValueType::Ref(), v8::internal::wasm::FastZoneVector< T >::shrink_to(), v8::internal::wasm::WasmTag::sig, v8::internal::sig, v8::internal::wasm::FastZoneVector< T >::size(), v8::internal::wasm::BranchTableImmediate::table_count, v8::internal::wasm::TagIndexImmediate::tag, v8::internal::wasm::CatchCase::MaybeTagIndex::tag_imm, v8::internal::this, v8::internal::tracing::type, v8::internal::v8_flags, and VALIDATE.
DECODE() [62/62]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE (Unreachable) [inline], [private]
Definition at line 4155 of file function-body-decoder-impl.h.
                      {
    CALL_INTERFACE_IF_OK_AND_REACHABLE(Trap, TrapReason::kTrapUnreachable);
    EndControl();
    return 1;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE.
DecodeAsmJsOpcode()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
unsigned v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeAsmJsOpcode (WasmOpcode opcode, uint32_t opcode_length) [inline], [private]
Definition at line 7401 of file function-body-decoder-impl.h.
                                                                        {
    if ((opcode >> 8) != kAsmJsPrefix) {
      this->DecodeError("Invalid opcode: 0x%x", opcode);
      return 0;
    }
    switch (opcode) {
#define ASMJS_CASE(Op, ...) case kExpr##Op:
      FOREACH_ASMJS_COMPAT_OPCODE(ASMJS_CASE)
#undef ASMJS_CASE
      {
        // Deal with special asmjs opcodes.
        if (!VALIDATE(is_asmjs_module(this->module_)))
          break;
        const FunctionSig* asmJsSig = WasmOpcodes::AsmjsSignature(opcode);
        DCHECK_NOT_NULL(asmJsSig);
        BuildSimpleOperator(opcode, asmJsSig);
        return opcode_length;
      }
      default:
        break;
    }
    this->DecodeError("Invalid opcode: 0x%x", opcode);
    return 0;
  }
References ASMJS_CASE, DCHECK_NOT_NULL, v8::internal::wasm::DecodeError(), FOREACH_ASMJS_COMPAT_OPCODE, v8::internal::wasm::is_asmjs_module(), and VALIDATE.
DecodeAtomicOpcode()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
uint32_t v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeAtomicOpcode (WasmOpcode opcode, uint32_t opcode_length) [inline], [private]
Definition at line 6803 of file function-body-decoder-impl.h.
                                                                         {
    // Fast check for out-of-range opcodes (only allow 0xfeXX).
    if (!VALIDATE((opcode >> 8) == kAtomicPrefix)) {
      this->DecodeError("invalid atomic opcode: 0x%x", opcode);
      return 0;
    }
    MachineType memtype;
    switch (opcode) {
#define CASE_ATOMIC_STORE_OP(Name, Type) \
  case kExpr##Name: { \
    this->detected_->add_threads(); \
    memtype = MachineType::Type(); \
    break; /* to generic mem access code below */ \
  }
      ATOMIC_STORE_OP_LIST(CASE_ATOMIC_STORE_OP)
#undef CASE_ATOMIC_STORE_OP
#define CASE_ATOMIC_OP(Name, Type) \
  case kExpr##Name: { \
    this->detected_->add_threads(); \
    memtype = MachineType::Type(); \
    break; /* to generic mem access code below */ \
  }
      ATOMIC_OP_LIST(CASE_ATOMIC_OP)
#undef CASE_ATOMIC_OP
      case kExprAtomicFence: {
        this->detected_->add_threads();
        uint8_t zero = this->template read_u8<ValidationTag>(
            this->pc_ + opcode_length, "zero");
        if (!VALIDATE(zero == 0)) {
          this->DecodeError(this->pc_ + opcode_length,
                            "invalid atomic operand");
          return 0;
        }
        CALL_INTERFACE_IF_OK_AND_REACHABLE(AtomicFence);
        return 1 + opcode_length;
      }
      case kExprStructAtomicGetS:
      case kExprStructAtomicGetU: {
        CHECK_PROTOTYPE_OPCODE(shared);
        NON_CONST_ONLY
        MemoryOrderImmediate memory_order(this, this->pc_ + opcode_length,
                                          validate);
        if (!this->ok()) return 0;
        FieldImmediate field(
            this, this->pc_ + opcode_length + memory_order.length, validate);
        if (!this->Validate(this->pc_ + opcode_length + memory_order.length,
                            field)) {
          return 0;
        }
        ValueType field_type =
            field.struct_imm.struct_type->field(field.field_imm.index);
        if (!VALIDATE(field_type.is_packed())) {
          this->DecodeError(
              "%s: Field %d of type %d has non-packed type %s. Use "
              "struct.atomic.get instead.",
              WasmOpcodes::OpcodeName(opcode), field.field_imm.index,
              field.struct_imm.index.index, field_type.name().c_str());
          return 0;
        }
        Value struct_obj =
            Pop(ValueType::RefNull(field.struct_imm.heap_type()));
        Value* value = Push(field_type.Unpacked());
        const bool is_signed = opcode == kExprStructAtomicGetS;
        if (struct_obj.type.is_shared()) {
          CALL_INTERFACE_IF_OK_AND_REACHABLE(StructAtomicGet, struct_obj, field,
                                             is_signed, memory_order.order,
                                             value);
        } else {
          CALL_INTERFACE_IF_OK_AND_REACHABLE(StructGet, struct_obj, field,
                                             is_signed, value);
        }
        return opcode_length + memory_order.length + field.length;
      }
      case kExprStructAtomicGet: {
        CHECK_PROTOTYPE_OPCODE(shared);
        NON_CONST_ONLY
        MemoryOrderImmediate memory_order(this, this->pc_ + opcode_length,
                                          validate);
        if (!this->ok()) return 0;
        FieldImmediate field(
            this, this->pc_ + opcode_length + memory_order.length, validate);
        if (!this->Validate(this->pc_ + opcode_length + memory_order.length,
                            field)) {
          return 0;
        }
        ValueType field_type =
            field.struct_imm.struct_type->field(field.field_imm.index);
        if (!VALIDATE(field_type == kWasmI32 || field_type == kWasmI64 ||
                      (field_type.is_ref() &&
                       (IsSubtypeOf(field_type, kWasmAnyRef, this->module_) ||
                        IsSubtypeOf(field_type, kWasmSharedAnyRef,
                                    this->module_))))) {
          this->DecodeError(
              "struct.atomic.get: Field %d of type %d has invalid type %s ",
              field.field_imm.index, field.struct_imm.index.index,
              field_type.name().c_str());
          return 0;
        }
        Value struct_obj =
            Pop(ValueType::RefNull(field.struct_imm.heap_type()));
        Value* value = Push(field_type);
        if (struct_obj.type.is_shared()) {
          CALL_INTERFACE_IF_OK_AND_REACHABLE(StructAtomicGet, struct_obj, field,
                                             true, memory_order.order, value);
        } else {
          // Emitting atomic operations for unshared types as well would require
          // aligning all i64 fields in them, potentially regressing memory
          // usage.
          CALL_INTERFACE_IF_OK_AND_REACHABLE(StructGet, struct_obj, field, true,
                                             value);
        }
        return opcode_length + memory_order.length + field.length;
      }
      case kExprStructAtomicSet: {
        CHECK_PROTOTYPE_OPCODE(shared);
        NON_CONST_ONLY
        MemoryOrderImmediate memory_order(this, this->pc_ + opcode_length,
                                          validate);
        if (!this->ok()) return 0;
        FieldImmediate field(
            this, this->pc_ + opcode_length + memory_order.length, validate);
        if (!this->Validate(this->pc_ + opcode_length + memory_order.length,
                            field)) {
          return 0;
        }
        const StructType* struct_type = field.struct_imm.struct_type;
        if (!VALIDATE(struct_type->mutability(field.field_imm.index))) {
          this->DecodeError(
              "struct.atomic.set: Field %d of type %d is immutable.",
              field.field_imm.index, field.struct_imm.index.index);
          return 0;
        }
        ValueType field_type = struct_type->field(field.field_imm.index);
        if (!VALIDATE(field_type == kWasmI8 || field_type == kWasmI16 ||
                      field_type == kWasmI32 || field_type == kWasmI64 ||
                      (field_type.is_ref() &&
                       (IsSubtypeOf(field_type, kWasmAnyRef, this->module_) ||
                        IsSubtypeOf(field_type, kWasmSharedAnyRef,
                                    this->module_))))) {
          this->DecodeError(
              "struct.atomic.set: Field %d of type %d has invalid type %s ",
              field.field_imm.index, field.struct_imm.index.index,
              field_type.name().c_str());
          return 0;
        }
        auto [struct_obj, field_value] =
            Pop(ValueType::RefNull(field.struct_imm.heap_type()),
                struct_type->field(field.field_imm.index).Unpacked());
        if (struct_obj.type.is_shared()) {
          CALL_INTERFACE_IF_OK_AND_REACHABLE(StructAtomicSet, struct_obj, field,
                                             field_value, memory_order.order);
        } else {
          CALL_INTERFACE_IF_OK_AND_REACHABLE(StructSet, struct_obj, field,
                                             field_value);
        }
        return opcode_length + field.length + memory_order.length;
      }
      case kExprStructAtomicAdd:
      case kExprStructAtomicSub:
      case kExprStructAtomicAnd:
      case kExprStructAtomicOr:
      case kExprStructAtomicXor:
      case kExprStructAtomicExchange: {
        CHECK_PROTOTYPE_OPCODE(shared);
        NON_CONST_ONLY
        MemoryOrderImmediate memory_order(this, this->pc_ + opcode_length,
                                          validate);
        if (!this->ok()) return 0;
        FieldImmediate field(
            this, this->pc_ + opcode_length + memory_order.length, validate);
        if (!this->Validate(this->pc_ + opcode_length + memory_order.length,
                            field)) {
          return 0;
        }
        const StructType* struct_type = field.struct_imm.struct_type;
        if (!VALIDATE(struct_type->mutability(field.field_imm.index))) {
          this->DecodeError("%s: Field %d of type %d is immutable.",
                            WasmOpcodes::OpcodeName(opcode),
                            field.field_imm.index,
                            field.struct_imm.index.index);
          return 0;
        }
        ValueType field_type = struct_type->field(field.field_imm.index);
        if (!VALIDATE(field_type == kWasmI32 || field_type == kWasmI64 ||
                      (opcode == kExprStructAtomicExchange &&
                       IsSubtypeOf(field_type.AsNonShared(), kWasmAnyRef,
                                   this->module_)))) {
          this->DecodeError("%s: Field %d of type %d has invalid type %s ",
                            WasmOpcodes::OpcodeName(opcode),
                            field.field_imm.index, field.struct_imm.index.index,
                            field_type.name().c_str());
          return 0;
        }
        auto [struct_obj, field_value] =
            Pop(ValueType::RefNull(field.struct_imm.heap_type()), field_type);
        Value* result = Push(field_type);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(StructAtomicRMW, opcode, struct_obj,
                                           field, field_value,
                                           memory_order.order, result);
        return opcode_length + field.length + memory_order.length;
      }
      case kExprStructAtomicCompareExchange: {
        CHECK_PROTOTYPE_OPCODE(shared);
        NON_CONST_ONLY
        MemoryOrderImmediate memory_order(this, this->pc_ + opcode_length,
                                          validate);
        if (!this->ok()) return 0;
        FieldImmediate field(
            this, this->pc_ + opcode_length + memory_order.length, validate);
        if (!this->Validate(this->pc_ + opcode_length + memory_order.length,
                            field)) {
          return 0;
        }
        const StructType* struct_type = field.struct_imm.struct_type;
        if (!VALIDATE(struct_type->mutability(field.field_imm.index))) {
          this->DecodeError("%s: Field %d of type %d is immutable.",
                            WasmOpcodes::OpcodeName(opcode),
                            field.field_imm.index,
                            field.struct_imm.index.index);
          return 0;
        }
        ValueType field_type = struct_type->field(field.field_imm.index);
        if (!VALIDATE(field_type == kWasmI32 || field_type == kWasmI64 ||
                      IsSubtypeOf(field_type.AsNonShared(), kWasmEqRef,
                                  this->module_))) {
          this->DecodeError("%s: Field %d of type %d has invalid type %s ",
                            WasmOpcodes::OpcodeName(opcode),
                            field.field_imm.index, field.struct_imm.index.index,
                            field_type.name().c_str());
          return 0;
        }
        auto [struct_obj, expected_value, new_value] =
            Pop(ValueType::RefNull(field.struct_imm.heap_type()), field_type,
                field_type);
        Value* result = Push(field_type);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(
            StructAtomicCompareExchange, opcode, struct_obj, field,
            expected_value, new_value, memory_order.order, result);
        return opcode_length + field.length + memory_order.length;
      }
      case kExprArrayAtomicGet: {
        CHECK_PROTOTYPE_OPCODE(shared);
        NON_CONST_ONLY
        MemoryOrderImmediate memory_order(this, this->pc_ + opcode_length,
                                          validate);
        if (!this->ok()) return 0;
        ArrayIndexImmediate imm(
            this, this->pc_ + memory_order.length + opcode_length, validate);
        if (!this->Validate(this->pc_ + memory_order.length + opcode_length,
                            imm)) {
          return 0;
        }
        ValueType element_type = imm.array_type->element_type();
        if (!VALIDATE(element_type == kWasmI32 || element_type == kWasmI64 ||
                      (element_type.is_ref() &&
                       (IsSubtypeOf(element_type, kWasmAnyRef, this->module_) ||
                        IsSubtypeOf(element_type, kWasmSharedAnyRef,
                                    this->module_))))) {
          this->DecodeError(
              "array.atomic.get: Array %d has invalid element type %s ",
              imm.index.index, imm.array_type->element_type().name().c_str());
          return 0;
        }
        auto [array_obj, index] =
            Pop(ValueType::RefNull(imm.heap_type()), kWasmI32);
        Value* value = Push(imm.array_type->element_type());
        if (array_obj.type.is_shared()) {
          CALL_INTERFACE_IF_OK_AND_REACHABLE(ArrayAtomicGet, array_obj, imm,
                                             index, true, memory_order.order,
                                             value);
        } else {
          CALL_INTERFACE_IF_OK_AND_REACHABLE(ArrayGet, array_obj, imm, index,
                                             true, value);
        }
        return opcode_length + memory_order.length + imm.length;
      }
      case kExprArrayAtomicGetS:
      case kExprArrayAtomicGetU: {
        CHECK_PROTOTYPE_OPCODE(shared);
        NON_CONST_ONLY
        MemoryOrderImmediate memory_order(this, this->pc_ + opcode_length,
                                          validate);
        if (!this->ok()) return 0;
        ArrayIndexImmediate imm(
            this, this->pc_ + memory_order.length + opcode_length, validate);
        if (!this->Validate(this->pc_ + memory_order.length + opcode_length,
                            imm)) {
          return 0;
        }
        if (!VALIDATE(imm.array_type->element_type().is_packed())) {
          this->DecodeError(
              "%s: Array type %d has non-packed type %s. Use "
              "array.atomic.get instead.",
              WasmOpcodes::OpcodeName(opcode), imm.index.index,
              imm.array_type->element_type().name().c_str());
          return 0;
        }
        auto [array_obj, index] =
            Pop(ValueType::RefNull(imm.heap_type()), kWasmI32);
        Value* value = Push(imm.array_type->element_type().Unpacked());
        CALL_INTERFACE_IF_OK_AND_REACHABLE(ArrayGet, array_obj, imm, index,
                                           opcode == kExprArrayAtomicGetS,
                                           value);
        return opcode_length + memory_order.length + imm.length;
      }
      case kExprArrayAtomicSet: {
        CHECK_PROTOTYPE_OPCODE(shared);
        NON_CONST_ONLY
        MemoryOrderImmediate memory_order(this, this->pc_ + opcode_length,
                                          validate);
        if (!this->ok()) return 0;
        ArrayIndexImmediate imm(
            this, this->pc_ + opcode_length + memory_order.length, validate);
        if (!this->Validate(this->pc_ + opcode_length + memory_order.length,
                            imm)) {
          return 0;
        }
        if (!VALIDATE(imm.array_type->mutability())) {
          this->DecodeError("array.atomic.set: Array type %d is immutable",
                            imm.index.index);
          return 0;
        }
        ValueType element_type = imm.array_type->element_type();
        if (!VALIDATE(element_type == kWasmI8 || element_type == kWasmI16 ||
                      element_type == kWasmI32 || element_type == kWasmI64 ||
                      (element_type.is_ref() &&
                       (IsSubtypeOf(element_type, kWasmAnyRef, this->module_) ||
                        IsSubtypeOf(element_type, kWasmSharedAnyRef,
                                    this->module_))))) {
          this->DecodeError(
              "array.atomic.set: Array type %d has invalid type %s ", imm.index,
              element_type.name().c_str());
          return 0;
        }
        auto [array_obj, index, value] =
            Pop(ValueType::RefNull(imm.heap_type()), kWasmI32,
                imm.array_type->element_type().Unpacked());
        if (imm.heap_type().is_shared()) {
          CALL_INTERFACE_IF_OK_AND_REACHABLE(ArrayAtomicSet, array_obj, imm,
                                             index, value, memory_order.order);
        } else {
          CALL_INTERFACE_IF_OK_AND_REACHABLE(ArraySet, array_obj, imm, index,
                                             value);
        }
        return opcode_length + memory_order.length + imm.length;
      }
      case kExprArrayAtomicAdd:
      case kExprArrayAtomicSub:
      case kExprArrayAtomicAnd:
      case kExprArrayAtomicOr:
      case kExprArrayAtomicXor:
      case kExprArrayAtomicExchange: {
        CHECK_PROTOTYPE_OPCODE(shared);
        NON_CONST_ONLY
        MemoryOrderImmediate memory_order(this, this->pc_ + opcode_length,
                                          validate);
        if (!this->ok()) return 0;
        ArrayIndexImmediate imm(
            this, this->pc_ + opcode_length + memory_order.length, validate);
        if (!this->Validate(this->pc_ + opcode_length + memory_order.length,
                            imm)) {
          return 0;
        }
        if (!VALIDATE(imm.array_type->mutability())) {
          this->DecodeError("%s: Array type %d is immutable",
                            WasmOpcodes::OpcodeName(opcode), imm.index.index);
          return 0;
        }
        ValueType element_type = imm.array_type->element_type();
        if (!VALIDATE(element_type == kWasmI32 || element_type == kWasmI64 ||
                      (opcode == kExprArrayAtomicExchange &&
                       IsSubtypeOf(element_type.AsNonShared(), kWasmAnyRef,
                                   this->module_)))) {
          this->DecodeError("%s: Array type %d has invalid type %s ",
                            WasmOpcodes::OpcodeName(opcode), imm.index,
                            element_type.name().c_str());
          return 0;
        }
        auto [array_obj, index, value] =
            Pop(ValueType::RefNull(imm.heap_type()), kWasmI32, element_type);
        Value* result = Push(element_type);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(ArrayAtomicRMW, opcode, array_obj,
                                           imm, index, value,
                                           memory_order.order, result);
        return opcode_length + memory_order.length + imm.length;
      }
      case kExprArrayAtomicCompareExchange: {
        CHECK_PROTOTYPE_OPCODE(shared);
        NON_CONST_ONLY
        MemoryOrderImmediate memory_order(this, this->pc_ + opcode_length,
                                          validate);
        if (!this->ok()) return 0;
        ArrayIndexImmediate imm(
            this, this->pc_ + opcode_length + memory_order.length, validate);
        if (!this->Validate(this->pc_ + opcode_length + memory_order.length,
                            imm)) {
          return 0;
        }
        if (!VALIDATE(imm.array_type->mutability())) {
          this->DecodeError("%s: Array type %d is immutable",
                            WasmOpcodes::OpcodeName(opcode), imm.index.index);
          return 0;
        }
        ValueType element_type = imm.array_type->element_type();
        if (!VALIDATE(element_type == kWasmI32 || element_type == kWasmI64 ||
                      IsSubtypeOf(element_type.AsNonShared(), kWasmEqRef,
                                  this->module_))) {
          this->DecodeError("%s: Array type %d has invalid type %s ",
                            WasmOpcodes::OpcodeName(opcode), imm.index,
                            element_type.name().c_str());
          return 0;
        }
        auto [array_obj, index, expected_value, new_value] =
            Pop(ValueType::RefNull(imm.heap_type()), kWasmI32, element_type,
                element_type);
        Value* result = Push(element_type);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(
            ArrayAtomicCompareExchange, opcode, array_obj, imm, index,
            expected_value, new_value, memory_order.order, result);
        return opcode_length + memory_order.length + imm.length;
      }
      default:
        // This path is only possible if we are validating.
        V8_ASSUME(ValidationTag::validate);
        this->DecodeError("invalid atomic opcode: 0x%x", opcode);
        return 0;
    }
    const uint32_t element_size_log2 =
        ElementSizeLog2Of(memtype.representation());
    MemoryAccessImmediate imm =
        MakeMemoryAccessImmediate(opcode_length, element_size_log2);
    if (!this->Validate(this->pc_ + opcode_length, imm)) return false;
    if (!VALIDATE(imm.alignment == element_size_log2)) {
      this->DecodeError(this->pc_,
                        "invalid alignment for atomic operation; expected "
                        "alignment is %u, actual alignment is %u",
                        element_size_log2, imm.alignment);
    }
    const FunctionSig* sig =
        WasmOpcodes::SignatureForAtomicOp(opcode, imm.memory->is_memory64());
    V8_ASSUME(sig != nullptr);
    PoppedArgVector args = PopArgs(sig);
    Value* result = sig->return_count() ? Push(sig->GetReturn()) : nullptr;
    if (V8_LIKELY(!CheckStaticallyOutOfBounds(imm.memory, memtype.MemSize(),
                                              imm.offset))) {
      CALL_INTERFACE_IF_OK_AND_REACHABLE(AtomicOp, opcode, args.data(),
                                         sig->parameter_count(), imm, result);
    }
    return opcode_length + imm.length;
  }
References v8::internal::wasm::MemoryAccessImmediate::alignment, v8::base::args, v8::internal::wasm::ArrayIndexImmediate::array_type, v8::internal::wasm::ValueType::AsNonShared(), ATOMIC_OP_LIST, ATOMIC_STORE_OP_LIST, CALL_INTERFACE_IF_OK_AND_REACHABLE, CASE_ATOMIC_OP, CASE_ATOMIC_STORE_OP, CHECK_PROTOTYPE_OPCODE, v8::internal::wasm::DecodeError(), v8::internal::wasm::ArrayType::element_type(), v8::internal::ElementSizeLog2Of(), v8::internal::wasm::StructType::field(), v8::internal::wasm::FieldImmediate::field_imm, v8::internal::wasm::StructIndexImmediate::heap_type(), v8::internal::wasm::ArrayIndexImmediate::heap_type(), v8::internal::index, v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::TypeIndexImmediate::index, v8::internal::wasm::TypeIndex::index, v8::internal::wasm::WasmMemory::is_memory64(), v8::internal::wasm::ValueTypeBase::is_packed(), v8::internal::wasm::ValueTypeBase::is_ref(), v8::internal::wasm::ValueTypeBase::is_shared(), v8::internal::is_signed(), v8::internal::wasm::IsSubtypeOf(), v8::internal::wasm::kWasmAnyRef, v8::internal::wasm::kWasmEqRef, v8::internal::wasm::kWasmI16, v8::internal::wasm::kWasmI32, v8::internal::wasm::kWasmI64, v8::internal::wasm::kWasmI8, v8::internal::wasm::kWasmSharedAnyRef, v8::internal::wasm::TypeIndexImmediate::length, v8::internal::wasm::FieldImmediate::length, v8::internal::wasm::MemoryAccessImmediate::length, v8::internal::wasm::MemoryAccessImmediate::memory, v8::internal::MachineType::MemSize(), v8::internal::wasm::ArrayTypeBase::mutability(), v8::internal::wasm::StructTypeBase::mutability(), v8::internal::wasm::ValueTypeBase::name(), NON_CONST_ONLY, v8::internal::wasm::MemoryAccessImmediate::offset, v8::internal::compiler::turboshaft::OpcodeName(), wasm::anonymous_namespace{c-api.cc}::PopArgs(), v8::internal::MachineType::representation(), v8::base::internal::result, v8::internal::sig, v8::internal::wasm::FieldImmediate::struct_imm, v8::internal::wasm::StructIndexImmediate::struct_type, v8::internal::this, v8::internal::wasm::ValueType::Unpacked(), V8_ASSUME, V8_LIKELY, VALIDATE, v8::internal::value, and v8::internal::zero.
DecodeEffectHandlerTable()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
int v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeEffectHandlerTable (EffectHandlerTableImmediate & handler_table_imm, base::Vector< HandlerCase > & handlers) [inline], [private]
Definition at line 4572 of file function-body-decoder-impl.h.
                                         {
    EffectHandlerTableIterator<ValidationTag> handle_iterator(
        this, handler_table_imm);
    int i = 0;
    while (handle_iterator.has_next()) {
      HandlerCase handler = handle_iterator.next();
      if (!this->Validate(this->pc_, handler.tag)) {
        return -1;
      }
      handlers[i] = handler;
      uint32_t stack_size = stack_.size();
      uint32_t push_count = 0;
      if (handler.kind == kOnSuspend) {
        const WasmTagSig* sig = handler.tag.tag->sig;
        stack_.EnsureMoreCapacity(static_cast<int>(sig->parameter_count()),
                                  this->zone_);
        for (ValueType type : sig->parameters()) Push(type);
        push_count += sig->parameter_count();
        if (!VALIDATE((this->Validate(this->pc_, handler.maybe_depth.br,
                                      control_depth())))) {
          return -1;
        }
        Control* target = control_at(handler.maybe_depth.br.depth);
        if (!VALIDATE(push_count == target->br_merge()->arity)) {
          this->DecodeError(
              "handler generates %d operand%s, target block returns %d",
              push_count, push_count != 1 ? "s" : "",
              target->br_merge()->arity);
          return -1;
        }
        if (!VALIDATE((
                TypeCheckBranch<PushBranchValues::kYes, RewriteStackTypes::kNo>(
                    target)))) {
          return -1;
        }
        stack_.shrink_to(stack_size);
        DCHECK_LT(i, handler_table_imm.table_count);
      } else if (handler.kind != kSwitch) {
        this->DecodeError("invalid handler kind %d", handler.kind);
        return -1;
      }
      i++;
    }
    return handle_iterator.length();
  }
References v8::internal::wasm::HandlerCase::MaybeHandlerDepth::br, DCHECK_LT, v8::internal::wasm::DecodeError(), v8::internal::wasm::BranchDepthImmediate::depth, v8::internal::wasm::FastZoneVector< T >::EnsureMoreCapacity(), v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::has_next(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::HandlerCase::kind, v8::internal::wasm::kOnSuspend, v8::internal::wasm::kSwitch, v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::length(), v8::internal::wasm::HandlerCase::maybe_depth, v8::internal::wasm::EffectHandlerTableIterator< ValidationTag >::next(), v8::internal::wasm::FastZoneVector< T >::shrink_to(), v8::internal::wasm::WasmTag::sig, v8::internal::sig, v8::internal::wasm::FastZoneVector< T >::size(), v8::internal::wasm::BranchTableImmediate::table_count, v8::internal::wasm::TagIndexImmediate::tag, v8::internal::wasm::HandlerCase::tag, v8::internal::this, v8::internal::tracing::type, and VALIDATE.
DecodeFunctionBody()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
void v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeFunctionBody () [inline]
Definition at line 3212 of file function-body-decoder-impl.h.
                            {
    TRACE("wasm-decode %p...%p (module+%u, %d bytes)\n", this->start(),
          this->end(), this->pc_offset(),
          static_cast<int>(this->end() - this->start()));
    // Set up initial function block.
    {
      DCHECK(control_.empty());
      constexpr uint32_t kStackDepth = 0;
      constexpr uint32_t kInitStackDepth = 0;
      control_.EnsureMoreCapacity(1, this->zone_);
      control_.emplace_back(this->zone_, kControlBlock, kStackDepth,
                            kInitStackDepth, this->pc_, kReachable);
      Control* c = &control_.back();
      if constexpr (decoding_mode == kFunctionBody) {
        InitMerge(&c->start_merge, 0, nullptr);
        InitMerge(&c->end_merge,
                  static_cast<uint32_t>(this->sig_->return_count()),
                  [this](uint32_t i) {
                    return Value{this->pc_, this->sig_->GetReturn(i)};
                  });
      } else {
        DCHECK_EQ(this->sig_->parameter_count(), 0);
        DCHECK_EQ(this->sig_->return_count(), 1);
        c->start_merge.arity = 0;
        c->end_merge.arity = 1;
        c->end_merge.vals.first = Value{this->pc_, this->sig_->GetReturn(0)};
      }
      CALL_INTERFACE_IF_OK_AND_REACHABLE(StartFunctionBody, c);
    }
    if (V8_LIKELY(this->current_inst_trace_->first == 0)) {
      // Decode the function body.
      while (this->pc_ < this->end_) {
        // Most operations only grow the stack by at least one element (unary
        // and binary operations, local.get, constants, ...). Thus check that
        // there is enough space for those operations centrally, and avoid any
        // bounds checks in those operations.
        stack_.EnsureMoreCapacity(1, this->zone_);
        uint8_t first_byte = *this->pc_;
        WasmOpcode opcode = static_cast<WasmOpcode>(first_byte);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(NextInstruction, opcode);
        int len;
        // Allowing two of the most common decoding functions to get inlined
        // appears to be the sweet spot.
        // Handling _all_ opcodes via a giant switch-statement has been tried
        // and found to be slower than calling through the handler table.
        if (opcode == kExprLocalGet) {
          len = WasmFullDecoder::DecodeLocalGet(this, opcode);
        } else if (opcode == kExprI32Const) {
          len = WasmFullDecoder::DecodeI32Const(this, opcode);
        } else {
          OpcodeHandler handler = GetOpcodeHandler(first_byte);
          len = (*handler)(this, opcode);
        }
        this->pc_ += len;
      }
    } else {
      // Decode the function body.
      while (this->pc_ < this->end_) {
        DCHECK(this->current_inst_trace_->first == 0 ||
               this->current_inst_trace_->first >= this->pc_offset());
        if (V8_UNLIKELY(this->current_inst_trace_->first ==
                        this->pc_offset())) {
          TRACE("Emit trace at 0x%x with ID[0x%x]\n", this->pc_offset(),
                this->current_inst_trace_->second);
          CALL_INTERFACE_IF_OK_AND_REACHABLE(TraceInstruction,
                                             this->current_inst_trace_->second);
          this->current_inst_trace_++;
        }
        // Most operations only grow the stack by at least one element (unary
        // and binary operations, local.get, constants, ...). Thus check that
        // there is enough space for those operations centrally, and avoid any
        // bounds checks in those operations.
        stack_.EnsureMoreCapacity(1, this->zone_);
        uint8_t first_byte = *this->pc_;
        WasmOpcode opcode = static_cast<WasmOpcode>(first_byte);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(NextInstruction, opcode);
        OpcodeHandler handler = GetOpcodeHandler(first_byte);
        int len = (*handler)(this, opcode);
        this->pc_ += len;
      }
    }
    // Even without validation, compilation could fail because of bailouts,
    // e.g., unsupported operations in Liftoff or the decoder for Wasm-in-JS
    // inlining. In those cases, {pc_} did not necessarily advance until {end_}.
    if (this->pc_ != this->end_) {
      // `DecodeError` is only available when validating, hence this guard.
      if constexpr (ValidationTag::validate) {
        this->DecodeError("Beyond end of code");
      }
    }
  }
References v8::internal::wasm::FastZoneVector< T >::back(), CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::control_, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::wasm::FastZoneVector< T >::emplace_back(), v8::internal::wasm::FastZoneVector< T >::empty(), v8::internal::wasm::Decoder::end(), v8::internal::wasm::FastZoneVector< T >::EnsureMoreCapacity(), v8::internal::Signature< T >::GetReturn(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::InitMerge(), v8::internal::wasm::kControlBlock, v8::internal::wasm::kFunctionBody, v8::internal::wasm::kReachable, v8::internal::Signature< T >::parameter_count(), v8::internal::wasm::Decoder::pc_, v8::internal::wasm::Decoder::pc_offset(), v8::internal::Signature< T >::return_count(), v8::internal::wasm::WasmDecoder< ValidationTag, kFunctionBody >::sig_, v8::internal::wasm::Decoder::start(), v8::internal::this, v8::internal::TRACE(), and v8::internal::wasm::WasmDecoder< ValidationTag, kFunctionBody >::zone_.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Decode().
DecodeGCOpcode()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
int v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeGCOpcode (WasmOpcode opcode, uint32_t opcode_length) [inline], [private]
Definition at line 5527 of file function-body-decoder-impl.h.
                                                                {
    // Bigger GC opcodes are handled via {DecodeStringRefOpcode}, so we can
    // assume here that opcodes are within [0xfb00, 0xfbff].
    // This assumption might help the big switch below.
    V8_ASSUME(opcode >> 8 == kGCPrefix);
    switch (opcode) {
      case kExprStructNew: {
        StructIndexImmediate imm(this, this->pc_ + opcode_length, validate);
        if (!this->Validate(this->pc_ + opcode_length, imm)) return 0;
        Value descriptor = PopDescriptor(imm.index);
        PoppedArgVector args = PopArgs(imm.struct_type);
        Value* value = Push(
            ValueType::Ref(imm.heap_type()).AsExactIfEnabled(this->enabled_));
        CALL_INTERFACE_IF_OK_AND_REACHABLE(StructNew, imm, descriptor,
                                           args.data(), value);
        return opcode_length + imm.length;
      }
      case kExprStructNewDefault: {
        StructIndexImmediate imm(this, this->pc_ + opcode_length, validate);
        if (!this->Validate(this->pc_ + opcode_length, imm)) return 0;
        if (ValidationTag::validate) {
          for (uint32_t i = 0; i < imm.struct_type->field_count(); i++) {
            ValueType ftype = imm.struct_type->field(i);
            if (!VALIDATE(ftype.is_defaultable())) {
              this->DecodeError(
                  "%s: struct type %d has field %d of non-defaultable type %s",
                  WasmOpcodes::OpcodeName(opcode), imm.index.index, i,
                  ftype.name().c_str());
              return 0;
            }
          }
        }
        Value descriptor = PopDescriptor(imm.index);
        Value* value = Push(
            ValueType::Ref(imm.heap_type()).AsExactIfEnabled(this->enabled_));
        CALL_INTERFACE_IF_OK_AND_REACHABLE(StructNewDefault, imm, descriptor,
                                           value);
        return opcode_length + imm.length;
      }
      case kExprStructGet: {
        NON_CONST_ONLY
        FieldImmediate field(this, this->pc_ + opcode_length, validate);
        if (!this->Validate(this->pc_ + opcode_length, field)) return 0;
        ValueType field_type =
            field.struct_imm.struct_type->field(field.field_imm.index);
        if (!VALIDATE(!field_type.is_packed())) {
          this->DecodeError(
              "struct.get: Field %d of type %d has packed type %s. "
              "Use struct.get_s or struct.get_u instead.",
              field.field_imm.index, field.struct_imm.index.index,
              field_type.name().c_str());
          return 0;
        }
        Value struct_obj =
            Pop(ValueType::RefNull(field.struct_imm.heap_type()));
        Value* value = Push(field_type);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(StructGet, struct_obj, field, true,
                                           value);
        return opcode_length + field.length;
      }
      case kExprStructGetU:
      case kExprStructGetS: {
        NON_CONST_ONLY
        FieldImmediate field(this, this->pc_ + opcode_length, validate);
        if (!this->Validate(this->pc_ + opcode_length, field)) return 0;
        ValueType field_type =
            field.struct_imm.struct_type->field(field.field_imm.index);
        if (!VALIDATE(field_type.is_packed())) {
          this->DecodeError(
              "%s: Field %d of type %d has non-packed type %s. Use struct.get "
              "instead.",
              WasmOpcodes::OpcodeName(opcode), field.field_imm.index,
              field.struct_imm.index.index, field_type.name().c_str());
          return 0;
        }
        Value struct_obj =
            Pop(ValueType::RefNull(field.struct_imm.heap_type()));
        Value* value = Push(field_type.Unpacked());
        CALL_INTERFACE_IF_OK_AND_REACHABLE(StructGet, struct_obj, field,
                                           opcode == kExprStructGetS, value);
        return opcode_length + field.length;
      }
      case kExprStructSet: {
        NON_CONST_ONLY
        FieldImmediate field(this, this->pc_ + opcode_length, validate);
        if (!this->Validate(this->pc_ + opcode_length, field)) return 0;
        const StructType* struct_type = field.struct_imm.struct_type;
        if (!VALIDATE(struct_type->mutability(field.field_imm.index))) {
          this->DecodeError("struct.set: Field %d of type %d is immutable.",
                            field.field_imm.index,
                            field.struct_imm.index.index);
          return 0;
        }
        auto [struct_obj, field_value] =
            Pop(ValueType::RefNull(field.struct_imm.heap_type()),
                struct_type->field(field.field_imm.index).Unpacked());
        CALL_INTERFACE_IF_OK_AND_REACHABLE(StructSet, struct_obj, field,
                                           field_value);
        return opcode_length + field.length;
      }
      case kExprArrayNew: {
        ArrayIndexImmediate imm(this, this->pc_ + opcode_length, validate);
        if (!this->Validate(this->pc_ + opcode_length, imm)) return 0;
        auto [initial_value, length] =
            Pop(imm.array_type->element_type().Unpacked(), kWasmI32);
        Value* value = Push(
            ValueType::Ref(imm.heap_type()).AsExactIfEnabled(this->enabled_));
        CALL_INTERFACE_IF_OK_AND_REACHABLE(ArrayNew, imm, length, initial_value,
                                           value);
        return opcode_length + imm.length;
      }
      case kExprArrayNewDefault: {
        ArrayIndexImmediate imm(this, this->pc_ + opcode_length, validate);
        if (!this->Validate(this->pc_ + opcode_length, imm)) return 0;
        if (!VALIDATE(imm.array_type->element_type().is_defaultable())) {
          this->DecodeError(
              "%s: array type %d has non-defaultable element type %s",
              WasmOpcodes::OpcodeName(opcode), imm.index.index,
              imm.array_type->element_type().name().c_str());
          return 0;
        }
        Value length = Pop(kWasmI32);
        Value* value = Push(
            ValueType::Ref(imm.heap_type()).AsExactIfEnabled(this->enabled_));
        CALL_INTERFACE_IF_OK_AND_REACHABLE(ArrayNewDefault, imm, length, value);
        return opcode_length + imm.length;
      }
      case kExprArrayNewData: {
        // TODO(14616): Add check that array sharedness == segment sharedness?
        NON_CONST_ONLY
        ArrayIndexImmediate array_imm(this, this->pc_ + opcode_length,
                                      validate);
        if (!this->Validate(this->pc_ + opcode_length, array_imm)) return 0;
        ValueType element_type = array_imm.array_type->element_type();
        if (element_type.is_reference()) {
          this->DecodeError(
              "array.new_data can only be used with numeric-type arrays, found "
              "array type #%d instead",
              array_imm.index.index);
          return 0;
        }
        const uint8_t* data_index_pc =
            this->pc_ + opcode_length + array_imm.length;
        IndexImmediate data_segment(this, data_index_pc, "data segment",
                                    validate);
        if (!this->ValidateDataSegment(data_index_pc, data_segment)) return 0;
        auto [offset, length] = Pop(kWasmI32, kWasmI32);
        Value* array = Push(ValueType::Ref(array_imm.heap_type())
                                .AsExactIfEnabled(this->enabled_));
        CALL_INTERFACE_IF_OK_AND_REACHABLE(ArrayNewSegment, array_imm,
                                           data_segment, offset, length, array);
        return opcode_length + array_imm.length + data_segment.length;
      }
      case kExprArrayNewElem: {
        // TODO(14616): Add check that array sharedness == segment sharedness?
        NON_CONST_ONLY
        ArrayIndexImmediate array_imm(this, this->pc_ + opcode_length,
                                      validate);
        if (!this->Validate(this->pc_ + opcode_length, array_imm)) return 0;
        ValueType element_type = array_imm.array_type->element_type();
        if (element_type.is_numeric()) {
          this->DecodeError(
              "array.new_elem can only be used with reference-type arrays, "
              "found array type #%d instead",
              array_imm.index.index);
          return 0;
        }
        const uint8_t* elem_index_pc =
            this->pc_ + opcode_length + array_imm.length;
        IndexImmediate elem_segment(this, elem_index_pc, "element segment",
                                    validate);
        if (!this->ValidateElementSegment(elem_index_pc, elem_segment)) {
          return 0;
        }
        ValueType elem_segment_type =
            this->module_->elem_segments[elem_segment.index].type;
        if (V8_UNLIKELY(
                !IsSubtypeOf(elem_segment_type, element_type, this->module_))) {
          this->DecodeError(
              "array.new_elem: segment type %s is not a subtype of array "
              "element type %s",
              elem_segment_type.name().c_str(), element_type.name().c_str());
          return 0;
        }
        auto [offset, length] = Pop(kWasmI32, kWasmI32);
        Value* array = Push(ValueType::Ref(array_imm.heap_type())
                                .AsExactIfEnabled(this->enabled_));
        CALL_INTERFACE_IF_OK_AND_REACHABLE(ArrayNewSegment, array_imm,
                                           elem_segment, offset, length, array);
        return opcode_length + array_imm.length + elem_segment.length;
      }
      case kExprArrayInitData: {
        NON_CONST_ONLY
        // TODO(14616): Add check that array sharedness == segment sharedness?
        ArrayIndexImmediate array_imm(this, this->pc_ + opcode_length,
                                      validate);
        if (!this->Validate(this->pc_ + opcode_length, array_imm)) return 0;
        if (!array_imm.array_type->mutability()) {
          this->DecodeError(
              "array.init_data can only be used with mutable arrays, found "
              "array type #%d instead",
              array_imm.index.index);
          return 0;
        }
        ValueType element_type = array_imm.array_type->element_type();
        if (element_type.is_reference()) {
          this->DecodeError(
              "array.init_data can only be used with numeric-type arrays, "
              "found array type #%d instead",
              array_imm.index.index);
          return 0;
        }
        const uint8_t* data_index_pc =
            this->pc_ + opcode_length + array_imm.length;
        IndexImmediate data_segment(this, data_index_pc, "data segment",
                                    validate);
        if (!this->ValidateDataSegment(data_index_pc, data_segment)) return 0;
        auto [array, array_index, data_offset, length] =
            Pop(ValueType::RefNull(array_imm.heap_type()), kWasmI32, kWasmI32,
                kWasmI32);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(ArrayInitSegment, array_imm,
                                           data_segment, array, array_index,
                                           data_offset, length);
        return opcode_length + array_imm.length + data_segment.length;
      }
      case kExprArrayInitElem: {
        NON_CONST_ONLY
        // TODO(14616): Add check that array sharedness == segment sharedness?
        ArrayIndexImmediate array_imm(this, this->pc_ + opcode_length,
                                      validate);
        if (!this->Validate(this->pc_ + opcode_length, array_imm)) return 0;
        if (!array_imm.array_type->mutability()) {
          this->DecodeError(
              "array.init_elem can only be used with mutable arrays, found "
              "array type #%d instead",
              array_imm.index.index);
          return 0;
        }
        ValueType element_type = array_imm.array_type->element_type();
        if (element_type.is_numeric()) {
          this->DecodeError(
              "array.init_elem can only be used with reference-type arrays, "
              "found array type #%d instead",
              array_imm.index.index);
          return 0;
        }
        const uint8_t* elem_index_pc =
            this->pc_ + opcode_length + array_imm.length;
        IndexImmediate elem_segment(this, elem_index_pc, "element segment",
                                    validate);
        if (!this->ValidateElementSegment(elem_index_pc, elem_segment)) {
          return 0;
        }
        ValueType segment_type =
            this->module_->elem_segments[elem_segment.index].type;
        if (!VALIDATE(IsSubtypeOf(segment_type, element_type, this->module_))) {
          this->DecodeError(
              "array.init_elem: segment type %s is not a subtype of array "
              "element type %s",
              segment_type.name().c_str(), element_type.name().c_str());
          return 0;
        }
        auto [array, array_index, elem_offset, length] =
            Pop(ValueType::RefNull(array_imm.heap_type()), kWasmI32, kWasmI32,
                kWasmI32);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(ArrayInitSegment, array_imm,
                                           elem_segment, array, array_index,
                                           elem_offset, length);
        return opcode_length + array_imm.length + elem_segment.length;
      }
      case kExprArrayGetS:
      case kExprArrayGetU: {
        NON_CONST_ONLY
        ArrayIndexImmediate imm(this, this->pc_ + opcode_length, validate);
        if (!this->Validate(this->pc_ + opcode_length, imm)) return 0;
        if (!VALIDATE(imm.array_type->element_type().is_packed())) {
          this->DecodeError(
              "%s: Array type %d has non-packed type %s. Use "
              "array.get instead.",
              WasmOpcodes::OpcodeName(opcode), imm.index.index,
              imm.array_type->element_type().name().c_str());
          return 0;
        }
        auto [array_obj, index] =
            Pop(ValueType::RefNull(imm.heap_type()), kWasmI32);
        Value* value = Push(imm.array_type->element_type().Unpacked());
        CALL_INTERFACE_IF_OK_AND_REACHABLE(ArrayGet, array_obj, imm, index,
                                           opcode == kExprArrayGetS, value);
        return opcode_length + imm.length;
      }
      case kExprArrayGet: {
        NON_CONST_ONLY
        ArrayIndexImmediate imm(this, this->pc_ + opcode_length, validate);
        if (!this->Validate(this->pc_ + opcode_length, imm)) return 0;
        if (!VALIDATE(!imm.array_type->element_type().is_packed())) {
          this->DecodeError(
              "array.get: Array type %d has packed type %s. Use "
              "array.get_s or array.get_u instead.",
              imm.index.index, imm.array_type->element_type().name().c_str());
          return 0;
        }
        auto [array_obj, index] =
            Pop(ValueType::RefNull(imm.heap_type()), kWasmI32);
        Value* value = Push(imm.array_type->element_type());
        CALL_INTERFACE_IF_OK_AND_REACHABLE(ArrayGet, array_obj, imm, index,
                                           true, value);
        return opcode_length + imm.length;
      }
      case kExprArraySet: {
        NON_CONST_ONLY
        ArrayIndexImmediate imm(this, this->pc_ + opcode_length, validate);
        if (!this->Validate(this->pc_ + opcode_length, imm)) return 0;
        if (!VALIDATE(imm.array_type->mutability())) {
          this->DecodeError("array.set: Array type %d is immutable",
                            imm.index.index);
          return 0;
        }
        auto [array_obj, index, value] =
            Pop(ValueType::RefNull(imm.heap_type()), kWasmI32,
                imm.array_type->element_type().Unpacked());
        CALL_INTERFACE_IF_OK_AND_REACHABLE(ArraySet, array_obj, imm, index,
                                           value);
        return opcode_length + imm.length;
      }
      case kExprArrayLen: {
        NON_CONST_ONLY
        const bool is_shared = Peek().type.is_shared();
        Value array_obj =
            Pop(IndependentHeapType{GenericKind::kArray, kNullable, is_shared});
        Value* value = Push(kWasmI32);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(ArrayLen, array_obj, value);
        return opcode_length;
      }
      case kExprArrayCopy: {
        NON_CONST_ONLY
        ArrayIndexImmediate dst_imm(this, this->pc_ + opcode_length, validate);
        if (!this->Validate(this->pc_ + opcode_length, dst_imm)) return 0;
        if (!VALIDATE(dst_imm.array_type->mutability())) {
          this->DecodeError(
              "array.copy: immediate destination array type #%d is immutable",
              dst_imm.index.index);
          return 0;
        }
        ArrayIndexImmediate src_imm(
            this, this->pc_ + opcode_length + dst_imm.length, validate);
        if (!this->Validate(this->pc_ + opcode_length + dst_imm.length,
                            src_imm)) {
          return 0;
        }
        if (!IsSubtypeOf(src_imm.array_type->element_type(),
                         dst_imm.array_type->element_type(), this->module_)) {
          this->DecodeError(
              "array.copy: source array's #%d element type is not a subtype of "
              "destination array's #%d element type",
              src_imm.index.index, dst_imm.index.index);
          return 0;
        }
        auto [dst, dst_index, src, src_index, length] =
            Pop(ValueType::RefNull(dst_imm.heap_type()), kWasmI32,
                ValueType::RefNull(src_imm.heap_type()), kWasmI32, kWasmI32);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(ArrayCopy, dst, dst_index, src,
                                           src_index, src_imm, length);
        return opcode_length + dst_imm.length + src_imm.length;
      }
      case kExprArrayFill: {
        NON_CONST_ONLY
        ArrayIndexImmediate array_imm(this, this->pc_ + opcode_length,
                                      validate);
        if (!this->Validate(this->pc_ + opcode_length, array_imm)) return 0;
        if (!VALIDATE(array_imm.array_type->mutability())) {
          this->DecodeError("array.init: Array type #%d is immutable",
                            array_imm.index.index);
          return 0;
        }
        auto [array, offset, value, length] =
            Pop(ValueType::RefNull(array_imm.heap_type()), kWasmI32,
                array_imm.array_type->element_type().Unpacked(), kWasmI32);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(ArrayFill, array_imm, array, offset,
                                           value, length);
        return opcode_length + array_imm.length;
      }
      case kExprArrayNewFixed: {
        ArrayIndexImmediate array_imm(this, this->pc_ + opcode_length,
                                      validate);
        if (!this->Validate(this->pc_ + opcode_length, array_imm)) return 0;
        IndexImmediate length_imm(this,
                                  this->pc_ + opcode_length + array_imm.length,
                                  "array.new_fixed length", validate);
        uint32_t elem_count = length_imm.index;
        if (!VALIDATE(elem_count <= kV8MaxWasmArrayNewFixedLength)) {
          this->DecodeError(
              "Requested length %u for array.new_fixed too large, maximum is "
              "%zu",
              length_imm.index, kV8MaxWasmArrayNewFixedLength);
          return 0;
        }
        ValueType element_type = array_imm.array_type->element_type();
        std::vector<ValueType> element_types(elem_count,
                                             element_type.Unpacked());
        FunctionSig element_sig(0, elem_count, element_types.data());
        PoppedArgVector elements = PopArgs(&element_sig);
        Value* result = Push(ValueType::Ref(array_imm.heap_type())
                                 .AsExactIfEnabled(this->enabled_));
        CALL_INTERFACE_IF_OK_AND_REACHABLE(ArrayNewFixed, array_imm, length_imm,
                                           elements.data(), result);
        return opcode_length + array_imm.length + length_imm.length;
      }
      case kExprRefI31: {
        Value input = Pop(kWasmI32);
        Value* value = Push(ValueType::Ref(kWasmI31Ref));
        CALL_INTERFACE_IF_OK_AND_REACHABLE(RefI31, input, value);
        return opcode_length;
      }
      case kExprRefI31Shared: {
        CHECK_PROTOTYPE_OPCODE(shared);
        Value input = Pop(kWasmI32);
        Value* value =
            Push(IndependentHeapType{GenericKind::kI31, kNonNullable, true});
        CALL_INTERFACE_IF_OK_AND_REACHABLE(RefI31, input, value);
        return opcode_length;
      }
      case kExprI31GetS: {
        NON_CONST_ONLY
        const bool is_shared = Peek().type.is_shared();
        Value i31 =
            Pop(IndependentHeapType{GenericKind::kI31, kNullable, is_shared});
        Value* value = Push(kWasmI32);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(I31GetS, i31, value);
        return opcode_length;
      }
      case kExprI31GetU: {
        NON_CONST_ONLY
        const bool is_shared = Peek().type.is_shared();
        Value i31 =
            Pop(IndependentHeapType{GenericKind::kI31, kNullable, is_shared});
        Value* value = Push(kWasmI32);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(I31GetU, i31, value);
        return opcode_length;
      }
      case kExprRefGetDesc: {
        NON_CONST_ONLY
        CHECK_PROTOTYPE_OPCODE(custom_descriptors);
        // We may need to generalize this to any TypeIndex in the future, but
        // for now only structs can have descriptors.
        StructIndexImmediate imm(this, this->pc_ + opcode_length, validate);
        if (!this->Validate(this->pc_ + opcode_length, imm)) return 0;
        const TypeDefinition& type = this->module_->type(imm.index);
        if (!VALIDATE(type.has_descriptor())) {
          this->DecodeError(
              this->pc_ + opcode_length,
              "Invalid type for ref.get_desc: type %s has no custom descriptor",
              imm.heap_type().name().c_str());
          return 0;
        }
        Value ref = Pop(ValueType::RefNull(imm.heap_type()));
        Value* desc =
            Push(ValueType::Ref(this->module_->heap_type(type.descriptor))
                     .AsExact(ref.type.exactness()));
        CALL_INTERFACE_IF_OK_AND_REACHABLE(RefGetDesc, ref, desc);
        return opcode_length + imm.length;
      }
      case kExprRefCastDesc:
      case kExprRefCastDescNull: {
        NON_CONST_ONLY
        CHECK_PROTOTYPE_OPCODE(custom_descriptors);
        HeapTypeImmediate imm(this->enabled_, this->detected_, this,
                              this->pc_ + opcode_length, validate);
        if (!this->Validate(this->pc_ + opcode_length, imm)) return 0;
        if (!VALIDATE(imm.type.has_index())) {
          this->DecodeError(
              this->pc_ + opcode_length,
              "ref.cast_desc: immediate type must have an index, but was %s",
              imm.type.name().c_str());
          return 0;
        }
        ModuleTypeIndex expected_desc_index =
            this->module_->type(imm.type.ref_index()).descriptor;
        if (!VALIDATE(expected_desc_index.valid())) {
          this->DecodeError(
              this->pc_ + opcode_length,
              "ref.cast_desc: immediate type %s must have a descriptor",
              imm.type.name().c_str());
          return 0;
        }
        ValueType expected_desc_type =
            ValueType::RefNull(this->module_->heap_type(expected_desc_index))
                .AsExact(imm.type.exactness());
        Value desc = Pop(expected_desc_type);
        // We will have to generalize the object's expected type to "top type of
        // imm.type" if/when values outside the anyref hierarchy can have custom
        // descriptors. This DCHECK should point that out when the time comes:
        DCHECK_EQ(imm.type.ref_type_kind(), RefTypeKind::kStruct);
        ValueType expected_obj_type = ValueType::Generic(
            GenericKind::kAny, kNullable, imm.type.is_shared());
        Value obj = Pop(expected_obj_type);
        bool null_succeeds = (opcode == kExprRefCastDescNull);
        ValueType target_type = ValueType::RefMaybeNull(
            imm.type, null_succeeds ? kNullable : kNonNullable);
        Value* value = Push(target_type);
        // TODO(403372470): Do we need to special-case casts that always fail
        // or always succeed?
        CALL_INTERFACE_IF_OK_AND_REACHABLE(RefCastDesc, obj, desc, value);
        return opcode_length + imm.length;
      }
      case kExprRefCast:
      case kExprRefCastNull: {
        NON_CONST_ONLY
        HeapTypeImmediate imm(this->enabled_, this->detected_, this,
                              this->pc_ + opcode_length, validate);
        if (!this->Validate(this->pc_ + opcode_length, imm)) return 0;
        opcode_length += imm.length;
        Value obj = Pop();
        HeapType target_type = imm.type;
        if (!VALIDATE((obj.type.is_object_reference() &&
                       IsSameTypeHierarchy(obj.type.heap_type(), target_type,
                                           this->module_)) ||
                      obj.type.is_bottom())) {
          this->DecodeError(obj.pc(),
                            "Invalid types for %s: %s of type %s has to "
                            "be in the same reference type hierarchy as %s",
                            WasmOpcodes::OpcodeName(opcode),
                            SafeOpcodeNameAt(obj.pc()), obj.type.name().c_str(),
                            ValueType::Ref(target_type).name().c_str());
          return 0;
        }
        if (!VALIDATE(!target_type.is_string_view())) {
          // TODO(12868): This reflects the current state of discussion at
          // https://github.com/WebAssembly/stringref/issues/40
          // It is suboptimal because it allows classifying a stringview_wtf16
          // as a stringref. This would be solved by making the views types
          // that aren't subtypes of anyref, which is one of the possible
          // resolutions of that discussion.
          this->DecodeError(
              this->pc_,
              "Invalid type for %s: string views are not classifiable",
              WasmOpcodes::OpcodeName(opcode));
          return 0;
        }
        bool null_succeeds = opcode == kExprRefCastNull;
        Value* value = Push(ValueType::RefMaybeNull(
            target_type, null_succeeds ? kNullable : kNonNullable));
        if (current_code_reachable_and_ok_) {
          // This logic ensures that code generation can assume that functions
          // can only be cast to function types, and data objects to data types.
          if (V8_UNLIKELY(TypeCheckAlwaysSucceeds(obj, target_type))) {
            if (obj.type.is_nullable() && !null_succeeds) {
              CALL_INTERFACE(AssertNotNullTypecheck, obj, value);
            } else {
              CALL_INTERFACE(Forward, obj, value);
            }
          } else if (V8_UNLIKELY(TypeCheckAlwaysFails(obj, target_type,
                                                      null_succeeds))) {
            // Unrelated types. The only way this will not trap is if the object
            // is null.
            if (obj.type.is_nullable() && null_succeeds) {
              CALL_INTERFACE(AssertNullTypecheck, obj, value);
            } else {
              CALL_INTERFACE(Trap, TrapReason::kTrapIllegalCast);
              // We know that the following code is not reachable, but according
              // to the spec it technically is. Set it to spec-only reachable.
              SetSucceedingCodeDynamicallyUnreachable();
            }
          } else {
            if (target_type.is_index()) {
              CALL_INTERFACE(RefCast, obj, value);
            } else {
              CALL_INTERFACE(RefCastAbstract, obj, target_type, value,
                             null_succeeds);
            }
          }
        }
        return opcode_length;
      }
      case kExprRefTestNull:
      case kExprRefTest: {
        NON_CONST_ONLY
        HeapTypeImmediate imm(this->enabled_, this->detected_, this,
                              this->pc_ + opcode_length, validate);
        if (!this->Validate(this->pc_ + opcode_length, imm)) return 0;
        opcode_length += imm.length;
        Value obj = Pop();
        HeapType target_type = imm.type;
        Value* result = Push(kWasmI32);
        if (!VALIDATE((obj.type.is_object_reference() &&
                       IsSameTypeHierarchy(obj.type.heap_type(), target_type,
                                           this->module_)) ||
                      obj.type.is_bottom())) {
          this->DecodeError(obj.pc(),
                            "Invalid types for %s: %s of type %s has to "
                            "be in the same reference type hierarchy as %s",
                            WasmOpcodes::OpcodeName(opcode),
                            SafeOpcodeNameAt(obj.pc()), obj.type.name().c_str(),
                            ValueType::Ref(target_type).name().c_str());
          return 0;
        }
        if (!VALIDATE(!target_type.is_string_view())) {
          // TODO(12868): This reflects the current state of discussion at
          // https://github.com/WebAssembly/stringref/issues/40
          // It is suboptimal because it allows classifying a stringview_wtf16
          // as a stringref. This would be solved by making the views types
          // that aren't subtypes of anyref, which is one of the possible
          // resolutions of that discussion.
          this->DecodeError(
              this->pc_,
              "Invalid type for %s: string views are not classifiable",
              WasmOpcodes::OpcodeName(opcode));
          return 0;
        }
        bool null_succeeds = opcode == kExprRefTestNull;
        if (V8_LIKELY(current_code_reachable_and_ok_)) {
          // This logic ensures that code generation can assume that functions
          // can only be cast to function types, and data objects to data types.
          if (V8_UNLIKELY(TypeCheckAlwaysSucceeds(obj, target_type))) {
            // Type checking can still fail for null.
            if (obj.type.is_nullable() && !null_succeeds) {
              // We abuse ref.as_non_null, which isn't otherwise used as a unary
              // operator, as a sentinel for the negation of ref.is_null.
              CALL_INTERFACE(UnOp, kExprRefAsNonNull, obj, result);
            } else {
              CALL_INTERFACE(Drop);
              CALL_INTERFACE(I32Const, result, 1);
            }
          } else if (V8_UNLIKELY(TypeCheckAlwaysFails(obj, target_type,
                                                      null_succeeds))) {
            CALL_INTERFACE(Drop);
            CALL_INTERFACE(I32Const, result, 0);
          } else {
            if (imm.type.is_index()) {
              CALL_INTERFACE(RefTest, imm.type, obj, result, null_succeeds);
            } else {
              CALL_INTERFACE(RefTestAbstract, obj, target_type, result,
                             null_succeeds);
            }
          }
        }
        return opcode_length;
      }
      case kExprRefCastNop: {
        NON_CONST_ONLY
        // Temporary non-standard instruction, for performance experiments.
        if (!VALIDATE(v8_flags.experimental_wasm_ref_cast_nop)) {
          this->DecodeError(
              "Invalid opcode 0xfb4c (enable with "
              "--experimental-wasm-ref-cast-nop)");
          return 0;
        }
        HeapTypeImmediate imm(this->enabled_, this->detected_, this,
                              this->pc_ + opcode_length, validate);
        if (!this->Validate(this->pc_ + opcode_length, imm)) return 0;
        opcode_length += imm.length;
        HeapType target_type = imm.type;
        Value obj = Pop();
        if (!VALIDATE((obj.type.is_object_reference() &&
                       IsSameTypeHierarchy(obj.type.heap_type(), target_type,
                                           this->module_)) ||
                      obj.type.is_bottom())) {
          this->DecodeError(obj.pc(),
                            "Invalid types for %s: %s of type %s has to "
                            "be in the same reference type hierarchy as %s",
                            WasmOpcodes::OpcodeName(opcode),
                            SafeOpcodeNameAt(obj.pc()), obj.type.name().c_str(),
                            ValueType::Ref(target_type).name().c_str());
          return 0;
        }
        Value* value = Push(ValueType::Ref(target_type));
        CALL_INTERFACE_IF_OK_AND_REACHABLE(Forward, obj, value);
        return opcode_length;
      }
      case kExprBrOnCast:
      case kExprBrOnCastFail: {
        NON_CONST_ONLY
        return ParseBrOnCast(opcode, opcode_length);
      }
      case kExprBrOnCastDesc:
      case kExprBrOnCastDescFail: {
        NON_CONST_ONLY
        CHECK_PROTOTYPE_OPCODE(custom_descriptors);
        return ParseBrOnCast(opcode, opcode_length);
      }
      case kExprAnyConvertExtern: {
        const bool is_shared = Peek().type.is_shared();
        Value extern_val = Pop(
            IndependentHeapType{GenericKind::kExtern, kNullable, is_shared});
        ValueType intern_type = IndependentHeapType{
            GenericKind::kAny, Nullability(extern_val.type.is_nullable()),
            is_shared};
        Value* intern_val = Push(intern_type);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(UnOp, kExprAnyConvertExtern,
                                           extern_val, intern_val);
        return opcode_length;
      }
      case kExprExternConvertAny: {
        const bool is_shared = Peek().type.is_shared();
        Value val =
            Pop(IndependentHeapType{GenericKind::kAny, kNullable, is_shared});
        ValueType extern_type =
            IndependentHeapType{GenericKind::kExtern,
                                Nullability(val.type.is_nullable()), is_shared};
        Value* extern_val = Push(extern_type);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(UnOp, kExprExternConvertAny, val,
                                           extern_val);
        return opcode_length;
      }
      default:
        this->DecodeError("invalid gc opcode: %x", opcode);
        return 0;
    }
  }
References v8::base::args, v8::internal::wasm::ArrayIndexImmediate::array_type, v8::internal::wasm::ValueType::AsExact(), CALL_INTERFACE, CALL_INTERFACE_IF_OK_AND_REACHABLE, CHECK_PROTOTYPE_OPCODE, DCHECK_EQ, v8::internal::wasm::DecodeError(), v8::internal::wasm::ArrayType::element_type(), v8::internal::wasm::ValueTypeBase::exactness(), v8::internal::wasm::StructType::field(), v8::internal::wasm::StructTypeBase::field_count(), v8::internal::wasm::ValueTypeBase::has_index(), v8::internal::wasm::StructIndexImmediate::heap_type(), v8::internal::wasm::ArrayIndexImmediate::heap_type(), v8::internal::index, v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::TypeIndexImmediate::index, v8::internal::wasm::TypeIndex::index, v8::internal::wasm::ValueTypeBase::is_defaultable(), v8::internal::wasm::HeapType::is_index(), v8::internal::wasm::ValueTypeBase::is_numeric(), v8::internal::wasm::ValueTypeBase::is_packed(), v8::internal::wasm::ValueTypeBase::is_reference(), v8::internal::is_shared, v8::internal::wasm::ValueTypeBase::is_shared(), v8::internal::wasm::ValueTypeBase::is_string_view(), v8::internal::wasm::IsSameTypeHierarchy(), v8::internal::wasm::IsSubtypeOf(), v8::internal::wasm::kNonNullable, v8::internal::wasm::kNullable, v8::internal::torque::ls::kStruct, v8::internal::wasm::kV8MaxWasmArrayNewFixedLength, v8::internal::wasm::kWasmI31Ref, v8::internal::wasm::kWasmI32, v8::internal::length, v8::internal::wasm::IndexImmediate::length, v8::internal::wasm::TypeIndexImmediate::length, v8::internal::wasm::HeapTypeImmediate::length, v8::internal::wasm::StructTypeBase::mutability(), v8::internal::wasm::ValueTypeBase::name(), v8::internal::wasm::HeapType::name(), NON_CONST_ONLY, v8::internal::compiler::turboshaft::OpcodeName(), wasm::anonymous_namespace{c-api.cc}::PopArgs(), v8::internal::wasm::HeapType::ref_index(), v8::internal::wasm::ValueTypeBase::ref_type_kind(), v8::base::internal::result, v8::internal::wasm::StructIndexImmediate::struct_type, v8::internal::this, v8::internal::tracing::type, v8::internal::wasm::HeapTypeImmediate::type, v8::internal::wasm::ValueType::Unpacked(), V8_ASSUME, v8::internal::v8_flags, V8_LIKELY, V8_UNLIKELY, v8::internal::wasm::TypeIndex::valid(), VALIDATE, and v8::internal::value.
DecodeLoadLane()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
int v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeLoadLane (WasmOpcode opcode, LoadType type, uint32_t opcode_length) [inline], [private]
Definition at line 5188 of file function-body-decoder-impl.h.
                                                                               {
    MemoryAccessImmediate mem_imm =
        MakeMemoryAccessImmediate(opcode_length, type.size_log_2());
    if (!this->Validate(this->pc_ + opcode_length, mem_imm)) return 0;
    SimdLaneImmediate lane_imm(this, this->pc_ + opcode_length + mem_imm.length,
                               validate);
    if (!this->Validate(this->pc_ + opcode_length, opcode, lane_imm)) return 0;
    ValueType address_type = MemoryAddressType(mem_imm.memory);
    auto [index, v128] = Pop(address_type, kWasmS128);
    Value* result = Push(kWasmS128);
    if (V8_LIKELY(!CheckStaticallyOutOfBounds(mem_imm.memory, type.size(),
                                              mem_imm.offset))) {
      CALL_INTERFACE_IF_OK_AND_REACHABLE(LoadLane, type, v128, index, mem_imm,
                                         lane_imm.lane, result);
    }
    return opcode_length + mem_imm.length + lane_imm.length;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::index, v8::internal::wasm::kWasmS128, v8::internal::wasm::SimdLaneImmediate::lane, v8::internal::wasm::MemoryAccessImmediate::length, v8::internal::wasm::SimdLaneImmediate::length, v8::internal::wasm::MemoryAccessImmediate::memory, v8::internal::wasm::MemoryAccessImmediate::offset, v8::base::internal::result, v8::internal::tracing::type, and V8_LIKELY.
DecodeLoadMem()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
int v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeLoadMem (LoadType type, int prefix_len = 1) [inline], [private]
Definition at line 5153 of file function-body-decoder-impl.h.
                                                       {
    MemoryAccessImmediate imm =
        MakeMemoryAccessImmediate(prefix_len, type.size_log_2());
    if (!this->Validate(this->pc_ + prefix_len, imm)) return 0;
    ValueType address_type = MemoryAddressType(imm.memory);
    Value index = Pop(address_type);
    Value* result = Push(type.value_type());
    if (V8_LIKELY(
            !CheckStaticallyOutOfBounds(imm.memory, type.size(), imm.offset))) {
      CALL_INTERFACE_IF_OK_AND_REACHABLE(LoadMem, type, imm, index, result);
    }
    return prefix_len + imm.length;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::index, v8::internal::wasm::MemoryAccessImmediate::length, v8::internal::wasm::MemoryAccessImmediate::memory, v8::internal::wasm::MemoryAccessImmediate::offset, v8::base::internal::result, v8::internal::tracing::type, and V8_LIKELY.
DecodeLoadTransformMem()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
int v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeLoadTransformMem (LoadType type, LoadTransformationKind transform, uint32_t opcode_length) [inline], [private]
Definition at line 5167 of file function-body-decoder-impl.h.
                                                     {
    // Load extends always load 64-bits.
    uint32_t max_alignment =
        transform == LoadTransformationKind::kExtend ? 3 : type.size_log_2();
    MemoryAccessImmediate imm =
        MakeMemoryAccessImmediate(opcode_length, max_alignment);
    if (!this->Validate(this->pc_ + opcode_length, imm)) return 0;
    ValueType address_type = MemoryAddressType(imm.memory);
    Value index = Pop(address_type);
    Value* result = Push(kWasmS128);
    uintptr_t op_size =
        transform == LoadTransformationKind::kExtend ? 8 : type.size();
    if (V8_LIKELY(
            !CheckStaticallyOutOfBounds(imm.memory, op_size, imm.offset))) {
      CALL_INTERFACE_IF_OK_AND_REACHABLE(LoadTransform, type, transform, imm,
                                         index, result);
    }
    return opcode_length + imm.length;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::index, v8::internal::wasm::kWasmS128, v8::internal::wasm::MemoryAccessImmediate::length, v8::internal::wasm::MemoryAccessImmediate::memory, v8::internal::wasm::MemoryAccessImmediate::offset, v8::base::internal::result, v8::internal::tracing::type, and V8_LIKELY.
DecodeNumericOpcode()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
unsigned v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeNumericOpcode (WasmOpcode opcode, uint32_t opcode_length) [inline], [private]
Definition at line 7261 of file function-body-decoder-impl.h.
                                                                          {
    // Fast check for out-of-range opcodes (only allow 0xfcXX).
    // This avoids a dynamic check in signature lookup, and might also help the
    // big switch below.
    if (!VALIDATE((opcode >> 8) == kNumericPrefix)) {
      this->DecodeError("invalid numeric opcode: 0x%x", opcode);
      return 0;
    }
    const FunctionSig* sig = WasmOpcodes::Signature(opcode);
    switch (opcode) {
      case kExprI32SConvertSatF32:
      case kExprI32UConvertSatF32:
      case kExprI32SConvertSatF64:
      case kExprI32UConvertSatF64:
      case kExprI64SConvertSatF32:
      case kExprI64UConvertSatF32:
      case kExprI64SConvertSatF64:
      case kExprI64UConvertSatF64: {
        BuildSimpleOperator(opcode, sig);
        return opcode_length;
      }
      case kExprMemoryInit: {
        MemoryInitImmediate imm(this, this->pc_ + opcode_length, validate);
        if (!this->Validate(this->pc_ + opcode_length, imm)) return 0;
        ValueType mem_type = MemoryAddressType(imm.memory.memory);
        auto [dst, offset, size] = Pop(mem_type, kWasmI32, kWasmI32);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(MemoryInit, imm, dst, offset, size);
        return opcode_length + imm.length;
      }
      case kExprDataDrop: {
        IndexImmediate imm(this, this->pc_ + opcode_length,
                           "data segment index", validate);
        if (!this->ValidateDataSegment(this->pc_ + opcode_length, imm)) {
          return 0;
        }
        CALL_INTERFACE_IF_OK_AND_REACHABLE(DataDrop, imm);
        return opcode_length + imm.length;
      }
      case kExprMemoryCopy: {
        MemoryCopyImmediate imm(this, this->pc_ + opcode_length, validate);
        if (!this->Validate(this->pc_ + opcode_length, imm)) return 0;
        ValueType dst_type = MemoryAddressType(imm.memory_dst.memory);
        ValueType src_type = MemoryAddressType(imm.memory_src.memory);
        // size_type = min(dst_type, src_type), where kI32 < kI64.
        ValueType size_type = dst_type == kWasmI32 ? kWasmI32 : src_type;
        auto [dst, src, size] = Pop(dst_type, src_type, size_type);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(MemoryCopy, imm, dst, src, size);
        return opcode_length + imm.length;
      }
      case kExprMemoryFill: {
        MemoryIndexImmediate imm(this, this->pc_ + opcode_length, validate);
        if (!this->Validate(this->pc_ + opcode_length, imm)) return 0;
        ValueType mem_type = MemoryAddressType(imm.memory);
        auto [dst, value, size] = Pop(mem_type, kWasmI32, mem_type);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(MemoryFill, imm, dst, value, size);
        return opcode_length + imm.length;
      }
      case kExprTableInit: {
        TableInitImmediate imm(this, this->pc_ + opcode_length, validate);
        if (!this->Validate(this->pc_ + opcode_length, imm)) return 0;
        ValueType table_address_type = TableAddressType(imm.table.table);
        auto [dst, src, size] = Pop(table_address_type, kWasmI32, kWasmI32);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(TableInit, imm, dst, src, size);
        return opcode_length + imm.length;
      }
      case kExprElemDrop: {
        IndexImmediate imm(this, this->pc_ + opcode_length,
                           "element segment index", validate);
        if (!this->ValidateElementSegment(this->pc_ + opcode_length, imm)) {
          return 0;
        }
        CALL_INTERFACE_IF_OK_AND_REACHABLE(ElemDrop, imm);
        return opcode_length + imm.length;
      }
      case kExprTableCopy: {
        TableCopyImmediate imm(this, this->pc_ + opcode_length, validate);
        if (!this->Validate(this->pc_ + opcode_length, imm)) return 0;
        ValueType dst_type = TableAddressType(imm.table_dst.table);
        ValueType src_type = TableAddressType(imm.table_src.table);
        // size_type = min(dst_type, src_type), where kI32 < kI64.
        ValueType size_type = dst_type == kWasmI32 ? kWasmI32 : src_type;
        auto [dst, src, size] = Pop(dst_type, src_type, size_type);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(TableCopy, imm, dst, src, size);
        return opcode_length + imm.length;
      }
      case kExprTableGrow: {
        TableIndexImmediate imm(this, this->pc_ + opcode_length, validate);
        if (!this->Validate(this->pc_ + opcode_length, imm)) return 0;
        ValueType table_address_type = TableAddressType(imm.table);
        auto [value, delta] = Pop(imm.table->type, table_address_type);
        Value* result = Push(table_address_type);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(TableGrow, imm, value, delta,
                                           result);
        return opcode_length + imm.length;
      }
      case kExprTableSize: {
        TableIndexImmediate imm(this, this->pc_ + opcode_length, validate);
        if (!this->Validate(this->pc_ + opcode_length, imm)) return 0;
        Value* result = Push(TableAddressType(imm.table));
        CALL_INTERFACE_IF_OK_AND_REACHABLE(TableSize, imm, result);
        return opcode_length + imm.length;
      }
      case kExprTableFill: {
        TableIndexImmediate imm(this, this->pc_ + opcode_length, validate);
        if (!this->Validate(this->pc_ + opcode_length, imm)) return 0;
        ValueType table_address_type = TableAddressType(imm.table);
        auto [start, value, count] =
            Pop(table_address_type, imm.table->type, table_address_type);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(TableFill, imm, start, value, count);
        return opcode_length + imm.length;
      }
      case kExprF32LoadMemF16: {
        if (!this->enabled_.has_fp16()) {
          this->DecodeError(
              "invalid numeric opcode: 0x%x, "
              "enable with --experimental-wasm-fp16",
              opcode);
          return 0;
        }
        return DecodeLoadMem(LoadType::kF32LoadF16, 2);
      }
      case kExprF32StoreMemF16: {
        if (!this->enabled_.has_fp16()) {
          this->DecodeError(
              "invalid numeric opcode: 0x%x, "
              "enable with --experimental-wasm-fp16",
              opcode);
          return 0;
        }
        return DecodeStoreMem(StoreType::kF32StoreF16, 2);
      }
      default:
        this->DecodeError("invalid numeric opcode: 0x%x", opcode);
        return 0;
    }
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::wasm::DecodeError(), v8::internal::wasm::kWasmI32, v8::internal::wasm::IndexImmediate::length, v8::internal::wasm::MemoryInitImmediate::length, v8::internal::wasm::MemoryCopyImmediate::length, v8::internal::wasm::TableInitImmediate::length, v8::internal::wasm::TableCopyImmediate::length, v8::internal::wasm::MemoryIndexImmediate::memory, v8::internal::wasm::MemoryInitImmediate::memory, v8::internal::wasm::MemoryCopyImmediate::memory_dst, v8::internal::wasm::MemoryCopyImmediate::memory_src, v8::base::internal::result, v8::internal::sig, size(), v8::internal::wasm::TableIndexImmediate::table, v8::internal::wasm::TableInitImmediate::table, v8::internal::wasm::TableCopyImmediate::table_dst, v8::internal::wasm::TableCopyImmediate::table_src, v8::internal::wasm::WasmTable::type, VALIDATE, and v8::internal::value.
DecodeSimdOpcode()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
uint32_t v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeSimdOpcode (WasmOpcode opcode, uint32_t opcode_length) [inline], [private]
Definition at line 5289 of file function-body-decoder-impl.h.
                                                                       {
    if constexpr (decoding_mode == kConstantExpression) {
      // Currently, only s128.const is allowed in constant expressions.
      if (opcode != kExprS128Const) {
        this->DecodeError("opcode %s is not allowed in constant expressions",
                          this->SafeOpcodeNameAt(this->pc()));
        return 0;
      }
      return SimdConstOp(opcode_length);
    }
    // opcode_length is the number of bytes that this SIMD-specific opcode takes
    // up in the LEB128 encoded form.
    switch (opcode) {
      case kExprF64x2ExtractLane:
        return SimdExtractLane(opcode, kWasmF64, opcode_length);
      case kExprF16x8ExtractLane: {
        if (!this->enabled_.has_fp16()) {
          this->DecodeError(
              "invalid simd opcode: 0x%x, "
              "enable with --experimental-wasm-fp16",
              opcode);
          return 0;
        }
        [[fallthrough]];
      }
      case kExprF32x4ExtractLane:
        return SimdExtractLane(opcode, kWasmF32, opcode_length);
      case kExprI64x2ExtractLane:
        return SimdExtractLane(opcode, kWasmI64, opcode_length);
      case kExprI32x4ExtractLane:
      case kExprI16x8ExtractLaneS:
      case kExprI16x8ExtractLaneU:
      case kExprI8x16ExtractLaneS:
      case kExprI8x16ExtractLaneU:
        return SimdExtractLane(opcode, kWasmI32, opcode_length);
      case kExprF64x2ReplaceLane:
        return SimdReplaceLane(opcode, kWasmF64, opcode_length);
      case kExprF16x8ReplaceLane: {
        if (!this->enabled_.has_fp16()) {
          this->DecodeError(
              "invalid simd opcode: 0x%x, "
              "enable with --experimental-wasm-fp16",
              opcode);
          return 0;
        }
        [[fallthrough]];
      }
      case kExprF32x4ReplaceLane:
        return SimdReplaceLane(opcode, kWasmF32, opcode_length);
      case kExprI64x2ReplaceLane:
        return SimdReplaceLane(opcode, kWasmI64, opcode_length);
      case kExprI32x4ReplaceLane:
      case kExprI16x8ReplaceLane:
      case kExprI8x16ReplaceLane:
        return SimdReplaceLane(opcode, kWasmI32, opcode_length);
      case kExprI8x16Shuffle:
        return Simd8x16ShuffleOp(opcode_length);
      case kExprS128LoadMem:
        return DecodeLoadMem(LoadType::kS128Load, opcode_length);
      case kExprS128StoreMem:
        return DecodeStoreMem(StoreType::kS128Store, opcode_length);
      case kExprS128Load32Zero:
        return DecodeLoadTransformMem(LoadType::kI32Load,
                                      LoadTransformationKind::kZeroExtend,
                                      opcode_length);
      case kExprS128Load64Zero:
        return DecodeLoadTransformMem(LoadType::kI64Load,
                                      LoadTransformationKind::kZeroExtend,
                                      opcode_length);
      case kExprS128Load8Splat:
        return DecodeLoadTransformMem(LoadType::kI32Load8S,
                                      LoadTransformationKind::kSplat,
                                      opcode_length);
      case kExprS128Load16Splat:
        return DecodeLoadTransformMem(LoadType::kI32Load16S,
                                      LoadTransformationKind::kSplat,
                                      opcode_length);
      case kExprS128Load32Splat:
        return DecodeLoadTransformMem(
            LoadType::kI32Load, LoadTransformationKind::kSplat, opcode_length);
      case kExprS128Load64Splat:
        return DecodeLoadTransformMem(
            LoadType::kI64Load, LoadTransformationKind::kSplat, opcode_length);
      case kExprS128Load8x8S:
        return DecodeLoadTransformMem(LoadType::kI32Load8S,
                                      LoadTransformationKind::kExtend,
                                      opcode_length);
      case kExprS128Load8x8U:
        return DecodeLoadTransformMem(LoadType::kI32Load8U,
                                      LoadTransformationKind::kExtend,
                                      opcode_length);
      case kExprS128Load16x4S:
        return DecodeLoadTransformMem(LoadType::kI32Load16S,
                                      LoadTransformationKind::kExtend,
                                      opcode_length);
      case kExprS128Load16x4U:
        return DecodeLoadTransformMem(LoadType::kI32Load16U,
                                      LoadTransformationKind::kExtend,
                                      opcode_length);
      case kExprS128Load32x2S:
        return DecodeLoadTransformMem(LoadType::kI64Load32S,
                                      LoadTransformationKind::kExtend,
                                      opcode_length);
      case kExprS128Load32x2U:
        return DecodeLoadTransformMem(LoadType::kI64Load32U,
                                      LoadTransformationKind::kExtend,
                                      opcode_length);
      case kExprS128Load8Lane: {
        return DecodeLoadLane(opcode, LoadType::kI32Load8S, opcode_length);
      }
      case kExprS128Load16Lane: {
        return DecodeLoadLane(opcode, LoadType::kI32Load16S, opcode_length);
      }
      case kExprS128Load32Lane: {
        return DecodeLoadLane(opcode, LoadType::kI32Load, opcode_length);
      }
      case kExprS128Load64Lane: {
        return DecodeLoadLane(opcode, LoadType::kI64Load, opcode_length);
      }
      case kExprS128Store8Lane: {
        return DecodeStoreLane(opcode, StoreType::kI32Store8, opcode_length);
      }
      case kExprS128Store16Lane: {
        return DecodeStoreLane(opcode, StoreType::kI32Store16, opcode_length);
      }
      case kExprS128Store32Lane: {
        return DecodeStoreLane(opcode, StoreType::kI32Store, opcode_length);
      }
      case kExprS128Store64Lane: {
        return DecodeStoreLane(opcode, StoreType::kI64Store, opcode_length);
      }
      case kExprS128Const:
        return SimdConstOp(opcode_length);
      case kExprF16x8Splat:
      case kExprF16x8Abs:
      case kExprF16x8Neg:
      case kExprF16x8Sqrt:
      case kExprF16x8Ceil:
      case kExprF16x8Floor:
      case kExprF16x8Trunc:
      case kExprF16x8NearestInt:
      case kExprF16x8Eq:
      case kExprF16x8Ne:
      case kExprF16x8Lt:
      case kExprF16x8Gt:
      case kExprF16x8Le:
      case kExprF16x8Ge:
      case kExprF16x8Add:
      case kExprF16x8Sub:
      case kExprF16x8Mul:
      case kExprF16x8Div:
      case kExprF16x8Min:
      case kExprF16x8Max:
      case kExprF16x8Pmin:
      case kExprF16x8Pmax:
      case kExprI16x8SConvertF16x8:
      case kExprI16x8UConvertF16x8:
      case kExprF16x8SConvertI16x8:
      case kExprF16x8UConvertI16x8:
      case kExprF16x8DemoteF32x4Zero:
      case kExprF16x8DemoteF64x2Zero:
      case kExprF32x4PromoteLowF16x8:
      case kExprF16x8Qfma:
      case kExprF16x8Qfms: {
        if (!this->enabled_.has_fp16()) {
          this->DecodeError(
              "invalid simd opcode: 0x%x, "
              "enable with --experimental-wasm-fp16",
              opcode);
          return 0;
        }
        [[fallthrough]];
      }
      default: {
        const FunctionSig* sig = WasmOpcodes::Signature(opcode);
        if (!VALIDATE(sig != nullptr)) {
          this->DecodeError("invalid simd opcode");
          return 0;
        }
        PoppedArgVector args = PopArgs(sig);
        Value* results = sig->return_count() == 0 ? nullptr : PushReturns(sig);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(SimdOp, opcode, args.data(),
                                           results);
        return opcode_length;
      }
    }
  }
References v8::base::args, CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::wasm::DecodeError(), v8::internal::wasm::kConstantExpression, v8::internal::wasm::kWasmF32, v8::internal::wasm::kWasmF64, v8::internal::wasm::kWasmI32, v8::internal::wasm::kWasmI64, nullptr, wasm::anonymous_namespace{c-api.cc}::PopArgs(), v8::internal::sig, and VALIDATE.
DecodeStoreLane()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
int v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeStoreLane (WasmOpcode opcode, StoreType type, uint32_t opcode_length) [inline], [private]
Definition at line 5207 of file function-body-decoder-impl.h.
                                              {
    MemoryAccessImmediate mem_imm =
        MakeMemoryAccessImmediate(opcode_length, type.size_log_2());
    if (!this->Validate(this->pc_ + opcode_length, mem_imm)) return 0;
    SimdLaneImmediate lane_imm(this, this->pc_ + opcode_length + mem_imm.length,
                               validate);
    if (!this->Validate(this->pc_ + opcode_length, opcode, lane_imm)) return 0;
    ValueType address_type = MemoryAddressType(mem_imm.memory);
    auto [index, v128] = Pop(address_type, kWasmS128);
    if (V8_LIKELY(!CheckStaticallyOutOfBounds(mem_imm.memory, type.size(),
                                              mem_imm.offset))) {
      CALL_INTERFACE_IF_OK_AND_REACHABLE(StoreLane, type, mem_imm, index, v128,
                                         lane_imm.lane);
    }
    return opcode_length + mem_imm.length + lane_imm.length;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::index, v8::internal::wasm::kWasmS128, v8::internal::wasm::SimdLaneImmediate::lane, v8::internal::wasm::MemoryAccessImmediate::length, v8::internal::wasm::SimdLaneImmediate::length, v8::internal::wasm::MemoryAccessImmediate::memory, v8::internal::wasm::MemoryAccessImmediate::offset, v8::internal::tracing::type, and V8_LIKELY.
DecodeStoreMem()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
int v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeStoreMem (StoreType store, int prefix_len = 1) [inline], [private]
Definition at line 5237 of file function-body-decoder-impl.h.
                                                          {
    MemoryAccessImmediate imm =
        MakeMemoryAccessImmediate(prefix_len, store.size_log_2());
    if (!this->Validate(this->pc_ + prefix_len, imm)) return 0;
    ValueType address_type = MemoryAddressType(imm.memory);
    auto [index, value] = Pop(address_type, store.value_type());
    if (V8_LIKELY(!CheckStaticallyOutOfBounds(imm.memory, store.size(),
                                              imm.offset))) {
      CALL_INTERFACE_IF_OK_AND_REACHABLE(StoreMem, store, imm, index, value);
    }
    return prefix_len + imm.length;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::index, v8::internal::wasm::MemoryAccessImmediate::length, v8::internal::wasm::MemoryAccessImmediate::memory, v8::internal::wasm::MemoryAccessImmediate::offset, store(), V8_LIKELY, and v8::internal::value.
DecodeStringEncodeWtf8()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
int v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeStringEncodeWtf8 (unibrow::Utf8Variant variant, uint32_t opcode_length) [inline], [private]
Definition at line 6477 of file function-body-decoder-impl.h.
                                                     {
    NON_CONST_ONLY
    MemoryIndexImmediate imm(this, this->pc_ + opcode_length, validate);
    if (!this->Validate(this->pc_ + opcode_length, imm)) return 0;
    ValueType addr_type = MemoryAddressType(imm.memory);
    auto [str, addr] = Pop(kWasmStringRef, addr_type);
    Value* result = Push(kWasmI32);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(StringEncodeWtf8, imm, variant, str,
                                       addr, result);
    return opcode_length + imm.length;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::wasm::kWasmI32, v8::internal::wasm::kWasmStringRef, NON_CONST_ONLY, and v8::base::internal::result.
DecodeStringEncodeWtf8Array()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
int v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeStringEncodeWtf8Array (unibrow::Utf8Variant variant, uint32_t opcode_length) [inline], [private]
Definition at line 6519 of file function-body-decoder-impl.h.
                                                          {
    NON_CONST_ONLY
    Value start = Pop(2, kWasmI32);
    Value array = PopPackedArray(1, kWasmI8, WasmArrayAccess::kWrite);
    Value str = Pop(0, kWasmStringRef);
    Value* result = Push(kWasmI32);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(StringEncodeWtf8Array, variant, str,
                                       array, start, result);
    return opcode_length;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::wasm::kWasmI32, v8::internal::wasm::kWasmI8, v8::internal::wasm::kWasmStringRef, NON_CONST_ONLY, and v8::base::internal::result.
DecodeStringMeasureWtf8()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
int v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeStringMeasureWtf8 (unibrow::Utf8Variant variant, uint32_t opcode_length) [inline], [private]
Definition at line 6468 of file function-body-decoder-impl.h.
                                                      {
    NON_CONST_ONLY
    Value str = Pop(kWasmStringRef);
    Value* result = Push(kWasmI32);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(StringMeasureWtf8, variant, str, result);
    return opcode_length;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::wasm::kWasmI32, v8::internal::wasm::kWasmStringRef, NON_CONST_ONLY, and v8::base::internal::result.
DecodeStringNewWtf8()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
int v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeStringNewWtf8 (unibrow::Utf8Variant variant, uint32_t opcode_length) [inline], [private]
Definition at line 6453 of file function-body-decoder-impl.h.
                                                  {
    NON_CONST_ONLY
    bool null_on_invalid = variant == unibrow::Utf8Variant::kUtf8NoTrap;
    MemoryIndexImmediate imm(this, this->pc_ + opcode_length, validate);
    if (!this->Validate(this->pc_ + opcode_length, imm)) return 0;
    ValueType addr_type = MemoryAddressType(imm.memory);
    auto [offset, size] = Pop(addr_type, kWasmI32);
    Value* result = Push(ValueType::RefMaybeNull(
        kWasmStringRef, null_on_invalid ? kNullable : kNonNullable));
    CALL_INTERFACE_IF_OK_AND_REACHABLE(StringNewWtf8, imm, variant, offset,
                                       size, result);
    return opcode_length + imm.length;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::wasm::kNonNullable, v8::internal::wasm::kNullable, v8::internal::wasm::kWasmI32, v8::internal::wasm::kWasmStringRef, v8::internal::wasm::IndexImmediate::length, v8::internal::wasm::MemoryIndexImmediate::memory, NON_CONST_ONLY, v8::base::internal::result, and size().
DecodeStringNewWtf8Array()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
int v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeStringNewWtf8Array (unibrow::Utf8Variant variant, uint32_t opcode_length) [inline], [private]
Definition at line 6505 of file function-body-decoder-impl.h.
                                                       {
    NON_CONST_ONLY
    Value end = Pop(2, kWasmI32);
    Value start = Pop(1, kWasmI32);
    Value array = PopPackedArray(0, kWasmI8, WasmArrayAccess::kRead);
    bool null_on_invalid = variant == unibrow::Utf8Variant::kUtf8NoTrap;
    Value* result = Push(ValueType::RefMaybeNull(
        kWasmStringRef, null_on_invalid ? kNullable : kNonNullable));
    CALL_INTERFACE_IF_OK_AND_REACHABLE(StringNewWtf8Array, variant, array,
                                       start, end, result);
    return opcode_length;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::compiler::end(), v8::internal::wasm::kNonNullable, v8::internal::wasm::kNullable, v8::internal::wasm::kWasmI32, v8::internal::wasm::kWasmI8, v8::internal::wasm::kWasmStringRef, NON_CONST_ONLY, and v8::base::internal::result.
DecodeStringRefOpcode()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
int v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeStringRefOpcode (WasmOpcode opcode, uint32_t opcode_length) [inline], [private]
Definition at line 6531 of file function-body-decoder-impl.h.
                                                                       {
    // Fast check for out-of-range opcodes (only allow 0xfbXX).
    // This might help the big switch below.
    if (!VALIDATE((opcode >> 8) == kGCPrefix)) {
      this->DecodeError("invalid stringref opcode: %x", opcode);
      return 0;
    }
    switch (opcode) {
      case kExprStringNewUtf8:
        return DecodeStringNewWtf8(unibrow::Utf8Variant::kUtf8, opcode_length);
      case kExprStringNewUtf8Try:
        return DecodeStringNewWtf8(unibrow::Utf8Variant::kUtf8NoTrap,
                                   opcode_length);
      case kExprStringNewLossyUtf8:
        return DecodeStringNewWtf8(unibrow::Utf8Variant::kLossyUtf8,
                                   opcode_length);
      case kExprStringNewWtf8:
        return DecodeStringNewWtf8(unibrow::Utf8Variant::kWtf8, opcode_length);
      case kExprStringNewWtf16: {
        NON_CONST_ONLY
        MemoryIndexImmediate imm(this, this->pc_ + opcode_length, validate);
        if (!this->Validate(this->pc_ + opcode_length, imm)) return 0;
        ValueType addr_type = MemoryAddressType(imm.memory);
        auto [offset, size] = Pop(addr_type, kWasmI32);
        Value* result = Push(kWasmRefString);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(StringNewWtf16, imm, offset, size,
                                           result);
        return opcode_length + imm.length;
      }
      case kExprStringConst: {
        StringConstImmediate imm(this, this->pc_ + opcode_length, validate);
        if (!this->Validate(this->pc_ + opcode_length, imm)) return 0;
        Value* result = Push(kWasmRefString);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(StringConst, imm, result);
        return opcode_length + imm.length;
      }
      case kExprStringMeasureUtf8:
        return DecodeStringMeasureWtf8(unibrow::Utf8Variant::kUtf8,
                                       opcode_length);
      case kExprStringMeasureWtf8:
        return DecodeStringMeasureWtf8(unibrow::Utf8Variant::kWtf8,
                                       opcode_length);
      case kExprStringMeasureWtf16: {
        NON_CONST_ONLY
        Value str = Pop(kWasmStringRef);
        Value* result = Push(kWasmI32);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(StringMeasureWtf16, str, result);
        return opcode_length;
      }
      case kExprStringEncodeUtf8:
        return DecodeStringEncodeWtf8(unibrow::Utf8Variant::kUtf8,
                                      opcode_length);
      case kExprStringEncodeLossyUtf8:
        return DecodeStringEncodeWtf8(unibrow::Utf8Variant::kLossyUtf8,
                                      opcode_length);
      case kExprStringEncodeWtf8:
        return DecodeStringEncodeWtf8(unibrow::Utf8Variant::kWtf8,
                                      opcode_length);
      case kExprStringEncodeWtf16: {
        NON_CONST_ONLY
        MemoryIndexImmediate imm(this, this->pc_ + opcode_length, validate);
        if (!this->Validate(this->pc_ + opcode_length, imm)) return 0;
        ValueType addr_type = MemoryAddressType(imm.memory);
        auto [str, addr] = Pop(kWasmStringRef, addr_type);
        Value* result = Push(kWasmI32);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(StringEncodeWtf16, imm, str, addr,
                                           result);
        return opcode_length + imm.length;
      }
      case kExprStringConcat: {
        NON_CONST_ONLY
        auto [head, tail] = Pop(kWasmStringRef, kWasmStringRef);
        Value* result = Push(kWasmRefString);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(StringConcat, head, tail, result);
        return opcode_length;
      }
      case kExprStringEq: {
        NON_CONST_ONLY
        auto [a, b] = Pop(kWasmStringRef, kWasmStringRef);
        Value* result = Push(kWasmI32);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(StringEq, a, b, result);
        return opcode_length;
      }
      case kExprStringIsUSVSequence: {
        NON_CONST_ONLY
        Value str = Pop(kWasmStringRef);
        Value* result = Push(kWasmI32);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(StringIsUSVSequence, str, result);
        return opcode_length;
      }
      case kExprStringAsWtf8: {
        NON_CONST_ONLY
        Value str = Pop(kWasmStringRef);
        Value* result = Push(kWasmStringViewWtf8);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(StringAsWtf8, str, result);
        return opcode_length;
      }
      case kExprStringViewWtf8Advance: {
        NON_CONST_ONLY
        auto [view, pos, bytes] = Pop(kWasmStringViewWtf8, kWasmI32, kWasmI32);
        Value* result = Push(kWasmI32);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(StringViewWtf8Advance, view, pos,
                                           bytes, result);
        return opcode_length;
      }
      case kExprStringViewWtf8EncodeUtf8:
        return DecodeStringViewWtf8Encode(unibrow::Utf8Variant::kUtf8,
                                          opcode_length);
      case kExprStringViewWtf8EncodeLossyUtf8:
        return DecodeStringViewWtf8Encode(unibrow::Utf8Variant::kLossyUtf8,
                                          opcode_length);
      case kExprStringViewWtf8EncodeWtf8:
        return DecodeStringViewWtf8Encode(unibrow::Utf8Variant::kWtf8,
                                          opcode_length);
      case kExprStringViewWtf8Slice: {
        NON_CONST_ONLY
        auto [view, start, end] = Pop(kWasmStringViewWtf8, kWasmI32, kWasmI32);
        Value* result = Push(kWasmRefString);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(StringViewWtf8Slice, view, start,
                                           end, result);
        return opcode_length;
      }
      case kExprStringAsWtf16: {
        NON_CONST_ONLY
        Value str = Pop(kWasmStringRef);
        Value* result = Push(kWasmStringViewWtf16);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(StringAsWtf16, str, result);
        return opcode_length;
      }
      case kExprStringViewWtf16Length: {
        NON_CONST_ONLY
        Value view = Pop(kWasmStringViewWtf16);
        Value* result = Push(kWasmI32);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(StringMeasureWtf16, view, result);
        return opcode_length;
      }
      case kExprStringViewWtf16GetCodeunit: {
        NON_CONST_ONLY
        auto [view, pos] = Pop(kWasmStringViewWtf16, kWasmI32);
        Value* result = Push(kWasmI32);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(StringViewWtf16GetCodeUnit, view,
                                           pos, result);
        return opcode_length;
      }
      case kExprStringViewWtf16Encode: {
        NON_CONST_ONLY
        MemoryIndexImmediate imm(this, this->pc_ + opcode_length, validate);
        if (!this->Validate(this->pc_ + opcode_length, imm)) return 0;
        ValueType addr_type = MemoryAddressType(imm.memory);
        auto [view, addr, pos, codeunits] =
            Pop(kWasmStringViewWtf16, addr_type, kWasmI32, kWasmI32);
        Value* result = Push(kWasmI32);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(StringViewWtf16Encode, imm, view,
                                           addr, pos, codeunits, result);
        return opcode_length + imm.length;
      }
      case kExprStringViewWtf16Slice: {
        NON_CONST_ONLY
        auto [view, start, end] = Pop(kWasmStringViewWtf16, kWasmI32, kWasmI32);
        Value* result = Push(kWasmRefString);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(StringViewWtf16Slice, view, start,
                                           end, result);
        return opcode_length;
      }
      case kExprStringAsIter: {
        NON_CONST_ONLY
        Value str = Pop(kWasmStringRef);
        Value* result = Push(kWasmStringViewIter);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(StringAsIter, str, result);
        return opcode_length;
      }
      case kExprStringViewIterNext: {
        NON_CONST_ONLY
        Value view = Pop(kWasmStringViewIter);
        Value* result = Push(kWasmI32);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(StringViewIterNext, view, result);
        return opcode_length;
      }
      case kExprStringViewIterAdvance: {
        NON_CONST_ONLY
        auto [view, codepoints] = Pop(kWasmStringViewIter, kWasmI32);
        Value* result = Push(kWasmI32);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(StringViewIterAdvance, view,
                                           codepoints, result);
        return opcode_length;
      }
      case kExprStringViewIterRewind: {
        NON_CONST_ONLY
        auto [view, codepoints] = Pop(kWasmStringViewIter, kWasmI32);
        Value* result = Push(kWasmI32);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(StringViewIterRewind, view,
                                           codepoints, result);
        return opcode_length;
      }
      case kExprStringViewIterSlice: {
        NON_CONST_ONLY
        auto [view, codepoints] = Pop(kWasmStringViewIter, kWasmI32);
        Value* result = Push(kWasmRefString);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(StringViewIterSlice, view,
                                           codepoints, result);
        return opcode_length;
      }
      case kExprStringNewUtf8Array:
        return DecodeStringNewWtf8Array(unibrow::Utf8Variant::kUtf8,
                                        opcode_length);
      case kExprStringNewUtf8ArrayTry:
        return DecodeStringNewWtf8Array(unibrow::Utf8Variant::kUtf8NoTrap,
                                        opcode_length);
      case kExprStringNewLossyUtf8Array:
        return DecodeStringNewWtf8Array(unibrow::Utf8Variant::kLossyUtf8,
                                        opcode_length);
      case kExprStringNewWtf8Array:
        return DecodeStringNewWtf8Array(unibrow::Utf8Variant::kWtf8,
                                        opcode_length);
      case kExprStringNewWtf16Array: {
        NON_CONST_ONLY
        Value end = Pop(2, kWasmI32);
        Value start = Pop(1, kWasmI32);
        Value array = PopPackedArray(0, kWasmI16, WasmArrayAccess::kRead);
        Value* result = Push(kWasmRefString);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(StringNewWtf16Array, array, start,
                                           end, result);
        return opcode_length;
      }
      case kExprStringEncodeUtf8Array:
        return DecodeStringEncodeWtf8Array(unibrow::Utf8Variant::kUtf8,
                                           opcode_length);
      case kExprStringEncodeLossyUtf8Array:
        return DecodeStringEncodeWtf8Array(unibrow::Utf8Variant::kLossyUtf8,
                                           opcode_length);
      case kExprStringEncodeWtf8Array:
        return DecodeStringEncodeWtf8Array(unibrow::Utf8Variant::kWtf8,
                                           opcode_length);
      case kExprStringEncodeWtf16Array: {
        NON_CONST_ONLY
        Value start = Pop(2, kWasmI32);
        Value array = PopPackedArray(1, kWasmI16, WasmArrayAccess::kWrite);
        Value str = Pop(0, kWasmStringRef);
        Value* result = Push(kWasmI32);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(StringEncodeWtf16Array, str, array,
                                           start, result);
        return opcode_length;
      }
      case kExprStringCompare: {
        NON_CONST_ONLY
        auto [lhs, rhs] = Pop(kWasmStringRef, kWasmStringRef);
        Value* result = Push(kWasmI32);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(StringCompare, lhs, rhs, result);
        return opcode_length;
      }
      case kExprStringFromCodePoint: {
        NON_CONST_ONLY
        Value code_point = Pop(kWasmI32);
        Value* result = Push(kWasmRefString);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(StringFromCodePoint, code_point,
                                           result);
        return opcode_length;
      }
      case kExprStringHash: {
        NON_CONST_ONLY
        Value string = Pop(kWasmStringRef);
        Value* result = Push(kWasmI32);
        CALL_INTERFACE_IF_OK_AND_REACHABLE(StringHash, string, result);
        return opcode_length;
      }
      default:
        this->DecodeError("invalid stringref opcode: %x", opcode);
        return 0;
    }
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::wasm::DecodeError(), v8::internal::compiler::end(), unibrow::kLossyUtf8, v8::internal::wasm::kWasmI16, v8::internal::wasm::kWasmI32, v8::internal::wasm::kWasmRefString, v8::internal::wasm::kWasmStringRef, v8::internal::wasm::kWasmStringViewIter, v8::internal::wasm::kWasmStringViewWtf16, v8::internal::wasm::kWasmStringViewWtf8, v8::internal::wasm::StringConstImmediate::length, NON_CONST_ONLY, v8::base::internal::result, size(), and VALIDATE.
DecodeStringViewWtf8Encode()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
int v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeStringViewWtf8Encode (unibrow::Utf8Variant variant, uint32_t opcode_length) [inline], [private]
Definition at line 6490 of file function-body-decoder-impl.h.
                                                         {
    NON_CONST_ONLY
    MemoryIndexImmediate imm(this, this->pc_ + opcode_length, validate);
    if (!this->Validate(this->pc_ + opcode_length, imm)) return 0;
    ValueType addr_type = MemoryAddressType(imm.memory);
    auto [view, addr, pos, bytes] =
        Pop(kWasmStringViewWtf8, addr_type, kWasmI32, kWasmI32);
    Value* next_pos = Push(kWasmI32);
    Value* bytes_out = Push(kWasmI32);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(StringViewWtf8Encode, imm, variant, view,
                                       addr, pos, bytes, next_pos, bytes_out);
    return opcode_length + imm.length;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::wasm::kWasmI32, v8::internal::wasm::kWasmStringViewWtf8, and NON_CONST_ONLY.
DoReturn()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
template<StackElementsCountMode strict_count, MergeType merge_type>
bool v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DoReturn () [inline], [private]
Definition at line 7759 of file function-body-decoder-impl.h.
                  {
    if (!VALIDATE(
            (TypeCheckStackAgainstMerge<strict_count, PushBranchValues::kNo,
                                        merge_type, RewriteStackTypes::kNo>(
                &control_.front().end_merge)))) {
      return false;
    }
    DCHECK_IMPLIES(current_code_reachable_and_ok_,
                   stack_.size() >= this->sig_->return_count());
    CALL_INTERFACE_IF_OK_AND_REACHABLE(DoReturn, 0);
    EndControl();
    return true;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, DCHECK_IMPLIES, v8::internal::wasm::FastZoneVector< T >::front(), v8::internal::wasm::FastZoneVector< T >::size(), v8::internal::this, and VALIDATE.
Drop() [1/2]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
void v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Drop (const Value &) [inline], [private]
Definition at line 7637 of file function-body-decoder-impl.h.
{ Drop(1); }
References v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Drop().
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Drop().
Drop() [2/2]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
void v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Drop (int count = 1) [inline], [private]
Definition at line 7626 of file function-body-decoder-impl.h.
                                     {
    DCHECK(!control_.empty());
    uint32_t limit = control_.back().stack_depth;
    if (V8_UNLIKELY(stack_.size() < limit + count)) {
      // Pop what we can.
      count = std::min(count, static_cast<int>(stack_.size() - limit));
    }
    stack_.pop(count);
  }
References v8::internal::wasm::FastZoneVector< T >::back(), DCHECK, v8::internal::wasm::FastZoneVector< T >::empty(), v8::internal::wasm::FastZoneVector< T >::pop(), v8::internal::wasm::FastZoneVector< T >::size(), and V8_UNLIKELY.
DropArgs() [1/2]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
void v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DropArgs (const FunctionSig * sig) [inline], [private]
Definition at line 5040 of file function-body-decoder-impl.h.
                                                  {
    int count = static_cast<int>(sig->parameter_count());
    Drop(count);
  }
References v8::internal::sig.
DropArgs() [2/2]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
void v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DropArgs (const StructType * type) [inline], [private]
Definition at line 5061 of file function-body-decoder-impl.h.
                                                  {
    Drop(static_cast<int>(type->field_count()));
  }
References v8::internal::tracing::type.
EndControl()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
void v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::EndControl () [inline], [private]
Definition at line 4964 of file function-body-decoder-impl.h.
                    {
    DCHECK(!control_.empty());
    Control* current = &control_.back();
    stack_.shrink_to(current->stack_depth);
    current->reachability = kUnreachable;
    current_code_reachable_and_ok_ = false;
  }
References v8::internal::wasm::FastZoneVector< T >::back(), v8::internal::DCHECK(), v8::internal::wasm::FastZoneVector< T >::empty(), v8::internal::wasm::kUnreachable, and v8::internal::wasm::FastZoneVector< T >::shrink_to().
EnsureStackArguments()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
int v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::EnsureStackArguments (int count) [inline], [private]
Definition at line 4991 of file function-body-decoder-impl.h.
                                                {
    uint32_t limit = control_.back().stack_depth;
    if (V8_LIKELY(stack_.size() >= count + limit)) return 0;
    return EnsureStackArguments_Slow(count);
  }
References v8::internal::wasm::FastZoneVector< T >::back(), v8::internal::wasm::FastZoneVector< T >::size(), and V8_LIKELY.
EnsureStackArguments_Slow()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
V8_NOINLINE V8_PRESERVE_MOST int v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::EnsureStackArguments_Slow (int count) [inline], [private]
Definition at line 4997 of file function-body-decoder-impl.h.
                                                                        {
    uint32_t limit = control_.back().stack_depth;
    if (!VALIDATE(control_.back().unreachable())) {
      NotEnoughArgumentsError(count, stack_.size() - limit);
    }
    // Silently create unreachable values out of thin air underneath the
    // existing stack values. To do so, we have to move existing stack values
    // upwards in the stack, then instantiate the new Values as
    // {UnreachableValue}.
    int current_values = stack_.size() - limit;
    int additional_values = count - current_values;
    DCHECK_GT(additional_values, 0);
    // Ensure that after this operation there is still room for one more value.
    // Callers might not expect this operation to push values on the stack
    // (because it only does so in exceptional cases).
    stack_.EnsureMoreCapacity(additional_values + 1, this->zone_);
    Value unreachable_value = UnreachableValue(this->pc_);
    for (int i = 0; i < additional_values; ++i) stack_.push(unreachable_value);
    if (current_values > 0) {
      // Move the current values up to the end of the stack, and create
      // unreachable values below.
      Value* stack_base = stack_value(current_values + additional_values);
      for (int i = current_values - 1; i >= 0; i--) {
        stack_base[additional_values + i] = stack_base[i];
      }
      for (int i = 0; i < additional_values; i++) {
        stack_base[i] = UnreachableValue(this->pc_);
      }
    }
    return additional_values;
  }
References v8::internal::wasm::FastZoneVector< T >::back(), DCHECK_GT, v8::internal::wasm::FastZoneVector< T >::EnsureMoreCapacity(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::FastZoneVector< T >::push(), v8::internal::wasm::FastZoneVector< T >::size(), and VALIDATE.
FallThrough()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
void v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::FallThrough () [inline], [private]
Definition at line 7777 of file function-body-decoder-impl.h.
                     {
    Control* c = &control_.back();
    DCHECK_NE(c->kind, kControlLoop);
    if (!VALIDATE(TypeCheckFallThru())) return;
    CALL_INTERFACE_IF_OK_AND_REACHABLE(FallThruTo, c);
    if (c->reachable()) c->end_merge.reached = true;
  }
References v8::internal::wasm::FastZoneVector< T >::back(), CALL_INTERFACE_IF_OK_AND_REACHABLE, DCHECK_NE, v8::internal::wasm::kControlLoop, and VALIDATE.
GetOpcodeHandler()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
OpcodeHandler v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::GetOpcodeHandler (uint8_t opcode) [inline], [private]
Definition at line 4958 of file function-body-decoder-impl.h.
                                                 {
    static constexpr std::array<OpcodeHandler, 256> kOpcodeHandlers =
        base::make_array<256>(GetOpcodeHandlerTableEntry);
    return kOpcodeHandlers[opcode];
  }
GetOpcodeHandlerTableEntry()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
static constexpr OpcodeHandler v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::GetOpcodeHandlerTableEntry (size_t idx) [inline], [static], [constexpr], [private]
Definition at line 4876 of file function-body-decoder-impl.h.
                                                                        {
    DECODE_IMPL(Nop);
#define BUILD_SIMPLE_OPCODE(op, ...) DECODE_IMPL(op);
    FOREACH_SIMPLE_NON_CONST_OPCODE(BUILD_SIMPLE_OPCODE)
#undef BUILD_SIMPLE_OPCODE
#define BUILD_SIMPLE_EXTENDED_CONST_OPCODE(op, ...) DECODE_IMPL_CONST(op);
    FOREACH_SIMPLE_EXTENDED_CONST_OPCODE(BUILD_SIMPLE_EXTENDED_CONST_OPCODE)
#undef BUILD_SIMPLE_EXTENDED_CONST_OPCODE
    DECODE_IMPL(Block);
    DECODE_IMPL(Rethrow);
    DECODE_IMPL(Throw);
    DECODE_IMPL(Try);
    DECODE_IMPL(TryTable);
    DECODE_IMPL(ThrowRef);
    DECODE_IMPL(Catch);
    DECODE_IMPL(Delegate);
    DECODE_IMPL(CatchAll);
    DECODE_IMPL(ContNew);
    DECODE_IMPL(ContBind);
    DECODE_IMPL(Resume);
    DECODE_IMPL(ResumeThrow);
    DECODE_IMPL(Suspend);
    DECODE_IMPL(Switch);
    DECODE_IMPL(BrOnNull);
    DECODE_IMPL(BrOnNonNull);
    DECODE_IMPL(Loop);
    DECODE_IMPL(If);
    DECODE_IMPL(Else);
    DECODE_IMPL_CONST(End);
    DECODE_IMPL(Select);
    DECODE_IMPL(SelectWithType);
    DECODE_IMPL(Br);
    DECODE_IMPL(BrIf);
    DECODE_IMPL(BrTable);
    DECODE_IMPL(Return);
    DECODE_IMPL(Unreachable);
    DECODE_IMPL(NopForTestingUnsupportedInLiftoff);
    DECODE_IMPL_CONST(I32Const);
    DECODE_IMPL_CONST(I64Const);
    DECODE_IMPL_CONST(F32Const);
    DECODE_IMPL_CONST(F64Const);
    DECODE_IMPL_CONST(RefNull);
    DECODE_IMPL(RefIsNull);
    DECODE_IMPL_CONST(RefFunc);
    DECODE_IMPL(RefAsNonNull);
    DECODE_IMPL(RefEq);
    DECODE_IMPL(LocalGet);
    DECODE_IMPL(LocalSet);
    DECODE_IMPL(LocalTee);
    DECODE_IMPL(Drop);
    DECODE_IMPL_CONST(GlobalGet);
    DECODE_IMPL(GlobalSet);
    DECODE_IMPL(TableGet);
    DECODE_IMPL(TableSet);
#define DECODE_LOAD_MEM(op, ...) DECODE_IMPL2(kExpr##op, LoadMem);
    FOREACH_LOAD_MEM_OPCODE(DECODE_LOAD_MEM)
#undef DECODE_LOAD_MEM
#define DECODE_STORE_MEM(op, ...) DECODE_IMPL2(kExpr##op, StoreMem);
    FOREACH_STORE_MEM_OPCODE(DECODE_STORE_MEM)
#undef DECODE_LOAD_MEM
    DECODE_IMPL(MemoryGrow);
    DECODE_IMPL(MemorySize);
    DECODE_IMPL(CallFunction);
    DECODE_IMPL(CallIndirect);
    DECODE_IMPL(ReturnCall);
    DECODE_IMPL(ReturnCallIndirect);
    DECODE_IMPL(CallRef);
    DECODE_IMPL(ReturnCallRef);
    DECODE_IMPL2(kNumericPrefix, Numeric);
    DECODE_IMPL2(kAsmJsPrefix, AsmJs);
    DECODE_IMPL_CONST2(kSimdPrefix, Simd);
    DECODE_IMPL2(kAtomicPrefix, Atomic);
    DECODE_IMPL_CONST2(kGCPrefix, GC);
#define SIMPLE_PROTOTYPE_CASE(name, ...) DECODE_IMPL(name);
    FOREACH_SIMPLE_PROTOTYPE_OPCODE(SIMPLE_PROTOTYPE_CASE)
#undef SIMPLE_PROTOTYPE_CASE
    return &WasmFullDecoder::UnknownOpcodeError;
  }
References BUILD_SIMPLE_EXTENDED_CONST_OPCODE, BUILD_SIMPLE_OPCODE, DECODE_IMPL, DECODE_IMPL2, DECODE_IMPL_CONST, DECODE_IMPL_CONST2, DECODE_LOAD_MEM, DECODE_STORE_MEM, FOREACH_LOAD_MEM_OPCODE, FOREACH_SIMPLE_EXTENDED_CONST_OPCODE, FOREACH_SIMPLE_NON_CONST_OPCODE, FOREACH_SIMPLE_PROTOTYPE_OPCODE, FOREACH_STORE_MEM_OPCODE, v8::GC, SIMPLE_PROTOTYPE_CASE, unibrow::TableGet(), and v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::UnknownOpcodeError().
HasCatchAll()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::HasCatchAll (Control * block) const [inline]
Definition at line 3309 of file function-body-decoder-impl.h.
                                         {
    DCHECK(block->is_try_table());
    return std::any_of(block->catch_cases.begin(), block->catch_cases.end(),
                       [](const struct CatchCase& catch_case) {
                         return catch_case.kind == kCatchAll ||
                                catch_case.kind == kCatchAllRef;
                       });
  }
References v8::base::any_of(), and v8::internal::DCHECK().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CatchCase(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::CatchCase().
InitializeInitializedLocalsTracking()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
void v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::InitializeInitializedLocalsTracking (int non_defaultable_locals) [inline]
Definition at line 3195 of file function-body-decoder-impl.h.
                                                                       {
    has_nondefaultable_locals_ = non_defaultable_locals > 0;
    if (!has_nondefaultable_locals_) return;
    initialized_locals_ =
        this->zone_->template AllocateArray<bool>(this->num_locals_);
    // Parameters are always initialized.
    const size_t num_params = this->sig_->parameter_count();
    std::fill_n(initialized_locals_, num_params, true);
    // Locals are initialized if they are defaultable.
    for (size_t i = num_params; i < this->num_locals_; i++) {
      initialized_locals_[i] = this->local_types_[i].is_defaultable();
    }
    DCHECK(locals_initializers_stack_.empty());
    locals_initializers_stack_.EnsureMoreCapacity(non_defaultable_locals,
                                                  this->zone_);
  }
References v8::internal::DCHECK(), v8::internal::wasm::FastZoneVector< T >::empty(), v8::internal::wasm::FastZoneVector< T >::EnsureMoreCapacity(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::has_nondefaultable_locals_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::initialized_locals_, v8::internal::wasm::ValueTypeBase::is_defaultable(), v8::internal::wasm::WasmDecoder< ValidationTag, kFunctionBody >::local_types_, v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::locals_initializers_stack_, v8::internal::wasm::WasmDecoder< ValidationTag, kFunctionBody >::num_locals_, v8::internal::Signature< T >::parameter_count(), v8::internal::wasm::WasmDecoder< ValidationTag, kFunctionBody >::sig_, and v8::internal::wasm::WasmDecoder< ValidationTag, kFunctionBody >::zone_.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Decode().
InitMerge()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
template<typename func >
void v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::InitMerge (Merge< Value > * merge, uint32_t arity, func get_val) [inline], [private]
Definition at line 4973 of file function-body-decoder-impl.h.
                                                                              {
    merge->arity = arity;
    if constexpr (std::is_null_pointer_v<func>) {
      DCHECK_EQ(0, arity);
    } else if (arity == 1) {
      merge->vals.first = get_val(0);
    } else if (arity > 1) {
      merge->vals.array = this->zone()->template AllocateArray<Value>(arity);
      for (uint32_t i = 0; i < arity; i++) {
        merge->vals.array[i] = get_val(i);
      }
    }
  }
References v8::internal::wasm::Merge< Value >::arity, v8::internal::wasm::Merge< Value >::array, DCHECK_EQ, v8::internal::wasm::Merge< Value >::first, v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::wasm::Merge< Value >::vals.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeFunctionBody().
interface()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
Interface& v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::interface () [inline]
Definition at line 3061 of file function-body-decoder-impl.h.
{ return interface_; }
References v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::interface_.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Decode(), v8::internal::wasm::ExecuteLiftoffCompilation(), and v8::internal::wasm::GenerateLiftoffDebugSideTable().
is_local_initialized()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::is_local_initialized (uint32_t local_index) [inline]
Definition at line 3165 of file function-body-decoder-impl.h.
                                                  {
    DCHECK_GT(this->num_locals_, local_index);
    if (!has_nondefaultable_locals_) return true;
    return initialized_locals_[local_index];
  }
References DCHECK_GT, v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::has_nondefaultable_locals_, v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::initialized_locals_, and v8::internal::wasm::WasmDecoder< ValidationTag, kFunctionBody >::num_locals_.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::set_local_initialized().
IsSubtypeVec()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::IsSubtypeVec (base::Vector< const ValueType > subtypes, base::Vector< const ValueType > supertypes) [inline], [private]
Definition at line 4494 of file function-body-decoder-impl.h.
                                                            {
    if (subtypes.size() != supertypes.size()) return false;
    auto super_it = supertypes.begin();
    for (ValueType subtype : subtypes) {
      if (!IsSubtypeOf(subtype, *super_it++, this->module_)) return false;
    }
    return true;
  }
References v8::base::Vector< T >::begin(), v8::internal::wasm::IsSubtypeOf(), and v8::base::Vector< T >::size().
locals_initialization_stack_depth()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
uint32_t v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::locals_initialization_stack_depth () const [inline]
Definition at line 3181 of file function-body-decoder-impl.h.
                                                     {
    return static_cast<uint32_t>(locals_initializers_stack_.size());
  }
References v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::locals_initializers_stack_, and v8::internal::wasm::FastZoneVector< T >::size().
MakeMemoryAccessImmediate()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
MemoryAccessImmediate v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::MakeMemoryAccessImmediate (uint32_t pc_offset, uint32_t max_alignment) [inline], [private]
Definition at line 3378 of file function-body-decoder-impl.h.
                                                                        {
    return MemoryAccessImmediate(this, this->pc_ + pc_offset, max_alignment,
                                 validate);
  }
MarkMightThrow()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
void v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::MarkMightThrow () [inline], [private]
Definition at line 3364 of file function-body-decoder-impl.h.
                        {
    if (!current_code_reachable_and_ok_ || current_catch() == -1) return;
    control_at(control_depth_of_current_catch())->might_throw = true;
  }
MemoryAddressType()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
ValueType v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::MemoryAddressType (const WasmMemory * memory) [inline], [private]
Definition at line 3373 of file function-body-decoder-impl.h.
                                                                  {
    return memory->is_memory64() ? kWasmI64 : kWasmI32;
  }
References v8::internal::wasm::WasmMemory::is_memory64(), v8::internal::wasm::kWasmI32, and v8::internal::wasm::kWasmI64.
NonConstError()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
static int v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::NonConstError (WasmFullDecoder< ValidationTag, Interface, decoding_mode > * decoder, WasmOpcode opcode) [inline], [static], [private]
Definition at line 4844 of file function-body-decoder-impl.h.
                                                                        {
    decoder->DecodeError("opcode %s is not allowed in constant expressions",
                         WasmOpcodes::OpcodeName(opcode));
    return 0;
  }
References v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeError(), and v8::internal::wasm::WasmOpcodes::OpcodeName().
NotEnoughArgumentsError()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
V8_NOINLINE V8_PRESERVE_MOST void v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::NotEnoughArgumentsError (int needed, int actual) [inline], [private]
Definition at line 7505 of file function-body-decoder-impl.h.
                                                                        {
    DCHECK_LT(0, needed);
    DCHECK_LE(0, actual);
    DCHECK_LT(actual, needed);
    this->DecodeError(
        "not enough arguments on the stack for %s (need %d, got %d)",
        SafeOpcodeNameAt(this->pc_), needed, actual);
  }
References DCHECK_LE, DCHECK_LT, and v8::internal::wasm::DecodeError().
onFirstError()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
void v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::onFirstError () [inline], [override], [private], [virtual]
Reimplemented from v8::internal::wasm::Decoder.
Definition at line 7826 of file function-body-decoder-impl.h.
                               {
    this->end_ = this->pc_; // Terminate decoding loop.
    this->current_code_reachable_and_ok_ = false;
    TRACE(" !%s\n", this->error_.message().c_str());
    // Cannot use CALL_INTERFACE_* macros because we emitted an error.
    interface().OnFirstError(this);
  }
References TRACE.
ParseBrOnCast()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
int v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::ParseBrOnCast (WasmOpcode opcode, uint32_t pc_offset) [inline], [private]
Definition at line 6255 of file function-body-decoder-impl.h.
                                                           {
    BrOnCastImmediate flags_imm(this, this->pc_ + pc_offset, validate);
    pc_offset += flags_imm.length;
    BrOnCastFlags flags = flags_imm.flags;
    BranchDepthImmediate branch_depth(this, this->pc_ + pc_offset, validate);
    if (!this->Validate(this->pc_ + pc_offset, branch_depth, control_.size())) {
      return 0;
    }
    pc_offset += branch_depth.length;
    HeapTypeImmediate src_imm(this->enabled_, this->detected_, this,
                              this->pc_ + pc_offset, validate);
    if (!this->Validate(this->pc_ + pc_offset, src_imm)) return 0;
    pc_offset += src_imm.length;
    ValueType src_type = ValueType::RefMaybeNull(
        src_imm.type, flags.src_is_null ? kNullable : kNonNullable);
    const uint8_t* target_imm_pc = this->pc_ + pc_offset;
    HeapTypeImmediate target_imm(this->enabled_, this->detected_, this,
                                 target_imm_pc, validate);
    if (!this->Validate(target_imm_pc, target_imm)) return 0;
    pc_offset += target_imm.length;
    bool null_succeeds = flags.res_is_null;
    ValueType target_type = ValueType::RefMaybeNull(
        target_imm.type, null_succeeds ? kNullable : kNonNullable);
    if (!VALIDATE(IsSubtypeOf(target_type, src_type, this->module_))) {
      this->DecodeError("invalid types for %s: %s is not a subtype of %s",
                        WasmOpcodes::OpcodeName(opcode),
                        target_type.name().c_str(), src_type.name().c_str());
      return 0;
    }
    Value descriptor{nullptr, kWasmVoid};
    if (opcode == kExprBrOnCastDesc || opcode == kExprBrOnCastDescFail) {
      if (!VALIDATE(target_imm.type.has_index())) {
        this->DecodeError(
            target_imm_pc, "%s: target type must have an index, but was %s",
            WasmOpcodes::OpcodeName(opcode), target_imm.type.name().c_str());
        return 0;
      }
      ModuleTypeIndex target_desc_index =
          this->module_->type(target_imm.type.ref_index()).descriptor;
      if (!VALIDATE(target_desc_index.valid())) {
        this->DecodeError(
            target_imm_pc, "%s: target type %s must have a descriptor",
            WasmOpcodes::OpcodeName(opcode), target_imm.type.name().c_str());
        return 0;
      }
      ValueType desc_type =
          ValueType::RefNull(this->module_->heap_type(target_desc_index))
              .AsExact(target_type.exactness());
      descriptor = Pop(desc_type);
    }
    Value obj = Pop(src_type);
    if (!VALIDATE(
            (obj.type.is_object_reference() &&
             IsSameTypeHierarchy(obj.type.heap_type(), target_type.heap_type(),
                                 this->module_)) ||
            obj.type.is_bottom())) {
      this->DecodeError(obj.pc(),
                        "invalid types for %s: %s of type %s has to "
                        "be in the same reference type hierarchy as %s",
                        WasmOpcodes::OpcodeName(opcode),
                        SafeOpcodeNameAt(obj.pc()), obj.type.name().c_str(),
                        target_type.name().c_str());
      return 0;
    }
    Control* c = control_at(branch_depth.depth);
    if (c->br_merge()->arity == 0) {
      this->DecodeError("%s must target a branch of arity at least 1",
                        WasmOpcodes::OpcodeName(opcode));
      return 0;
    }
    if (opcode == kExprBrOnCast || opcode == kExprBrOnCastDesc) {
      Value* value_on_branch = Push(target_type);
      if (!VALIDATE(
              (TypeCheckBranch<PushBranchValues::kYes, RewriteStackTypes::kYes>(
                  c)))) {
        return 0;
      }
      if (V8_LIKELY(current_code_reachable_and_ok_)) {
        // This logic ensures that code generation can assume that functions
        // can only be cast to function types, and data objects to data types.
        if (V8_UNLIKELY(
                TypeCheckAlwaysSucceeds(obj, target_type.heap_type()))) {
          // The branch will still not be taken on null if not
          // {null_succeeds}.
          if (obj.type.is_nullable() && !null_succeeds) {
            CALL_INTERFACE(BrOnNonNull, obj, value_on_branch,
                           branch_depth.depth, false);
          } else {
            CALL_INTERFACE(Forward, obj, value_on_branch);
            CALL_INTERFACE(BrOrRet, branch_depth.depth);
            // We know that the following code is not reachable, but according
            // to the spec it technically is. Set it to spec-only reachable.
            SetSucceedingCodeDynamicallyUnreachable();
          }
          c->br_merge()->reached = true;
        } else if (V8_LIKELY(!TypeCheckAlwaysFails(obj, target_type.heap_type(),
                                                   null_succeeds))) {
          if (opcode == kExprBrOnCastDesc) {
            CALL_INTERFACE(BrOnCastDesc, target_imm.type, obj, descriptor,
                           value_on_branch, branch_depth.depth, null_succeeds);
          } else if (target_imm.type.is_index()) {
            CALL_INTERFACE(BrOnCast, target_imm.type, obj, value_on_branch,
                           branch_depth.depth, null_succeeds);
          } else {
            CALL_INTERFACE(BrOnCastAbstract, obj, target_type.heap_type(),
                           value_on_branch, branch_depth.depth, null_succeeds);
          }
          c->br_merge()->reached = true;
        }
      }
      Drop(*value_on_branch);
      Push(obj); // Restore stack state on fallthrough.
      // The fallthrough type is the source type as specified in the br_on_cast
      // instruction. This can be a super type of the stack value. Furthermore
      // nullability gets refined to non-nullable if the cast target is
      // nullable, meaning the branch will be taken on null.
      DCHECK(!src_type.heap_type().is_bottom());
      bool fallthrough_nullable = flags.src_is_null && !flags.res_is_null;
      stack_value(1)->type = ValueType::RefMaybeNull(
          src_type.heap_type(),
          fallthrough_nullable ? kNullable : kNonNullable);
      CALL_INTERFACE_IF_OK_AND_REACHABLE(Forward, obj, stack_value(1));
      return pc_offset;
    } else {
      DCHECK(opcode == kExprBrOnCastFail || opcode == kExprBrOnCastDescFail);
      // The branch type is set based on the source type immediate (independent
      // of the actual stack value). If the target type is nullable, the branch
      // type is non-nullable.
      Push(flags.res_is_null ? src_type.AsNonNull() : src_type);
      CALL_INTERFACE_IF_OK_AND_REACHABLE(Forward, obj, stack_value(1));
      if (!VALIDATE(
              (TypeCheckBranch<PushBranchValues::kYes, RewriteStackTypes::kYes>(
                  c)))) {
        return 0;
      }
      Value result_on_fallthrough = CreateValue(target_type);
      if (V8_LIKELY(current_code_reachable_and_ok_)) {
        // This logic ensures that code generation can assume that functions
        // can only be cast between compatible types.
        if (V8_UNLIKELY(TypeCheckAlwaysFails(obj, target_type.heap_type(),
                                             null_succeeds))) {
          // The types are incompatible (i.e. neither of the two types is a
          // subtype of the other). Always branch.
          CALL_INTERFACE(Forward, obj, stack_value(1));
          CALL_INTERFACE(BrOrRet, branch_depth.depth);
          // We know that the following code is not reachable, but according
          // to the spec it technically is. Set it to spec-only reachable.
          SetSucceedingCodeDynamicallyUnreachable();
          c->br_merge()->reached = true;
        } else if (V8_UNLIKELY(
                       TypeCheckAlwaysSucceeds(obj, target_type.heap_type()))) {
          // The branch can still be taken on null.
          if (obj.type.is_nullable() && !null_succeeds) {
            CALL_INTERFACE(BrOnNull, obj, branch_depth.depth, true,
                           &result_on_fallthrough);
            c->br_merge()->reached = true;
          } else {
            // Otherwise, the type check always succeeds. Do not branch. Also,
            // make sure the object remains on the stack.
            result_on_fallthrough = obj;
          }
        } else {
          if (opcode == kExprBrOnCastDescFail) {
            CALL_INTERFACE(BrOnCastDescFail, target_imm.type, obj, descriptor,
                           &result_on_fallthrough, branch_depth.depth,
                           null_succeeds);
          } else if (target_imm.type.is_index()) {
            CALL_INTERFACE(BrOnCastFail, target_imm.type, obj,
                           &result_on_fallthrough, branch_depth.depth,
                           null_succeeds);
          } else {
            CALL_INTERFACE(BrOnCastFailAbstract, obj, target_type.heap_type(),
                           &result_on_fallthrough, branch_depth.depth,
                           null_succeeds);
          }
          c->br_merge()->reached = true;
        }
      }
      // Make sure the correct value is on the stack state on fallthrough.
      Drop(obj);
      Push(result_on_fallthrough);
      return pc_offset;
    }
  }
References v8::internal::wasm::ValueType::AsExact(), v8::internal::wasm::ValueType::AsNonNull(), CALL_INTERFACE, CALL_INTERFACE_IF_OK_AND_REACHABLE, DCHECK, v8::internal::wasm::DecodeError(), v8::internal::wasm::BranchDepthImmediate::depth, v8::internal::wasm::ValueTypeBase::exactness(), flags(), v8::internal::wasm::BrOnCastImmediate::flags, v8::internal::wasm::ValueTypeBase::has_index(), v8::internal::wasm::ValueType::heap_type(), v8::internal::wasm::ValueTypeBase::is_bottom(), v8::internal::wasm::HeapType::is_index(), v8::internal::wasm::IsSameTypeHierarchy(), v8::internal::wasm::IsSubtypeOf(), v8::internal::wasm::kNonNullable, v8::internal::wasm::kNullable, v8::internal::wasm::kWasmVoid, v8::internal::wasm::BrOnCastImmediate::length, v8::internal::wasm::BranchDepthImmediate::length, v8::internal::wasm::HeapTypeImmediate::length, v8::internal::wasm::ValueTypeBase::name(), v8::internal::wasm::HeapType::name(), v8::internal::compiler::turboshaft::OpcodeName(), v8::internal::wasm::HeapType::ref_index(), v8::internal::wasm::FastZoneVector< T >::size(), v8::internal::this, v8::internal::wasm::HeapTypeImmediate::type, V8_LIKELY, V8_UNLIKELY, v8::internal::wasm::TypeIndex::valid(), and VALIDATE.
pc_relative_offset()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
uint32_t v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::pc_relative_offset () const [inline]
Definition at line 3161 of file function-body-decoder-impl.h.
                                      {
    return this->pc_offset() - locals_offset_;
  }
References v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::locals_offset_, and v8::internal::wasm::Decoder::pc_offset().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::GetBranchHint().
Peek() [1/3]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
Value v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Peek (int depth, int index, ValueType expected) [inline], [private]
Definition at line 7544 of file function-body-decoder-impl.h.
                                                                 {
    Value value = Peek(depth);
    ValidateStackValue(index, value, expected);
    return value;
  }
References v8::internal::index, and v8::internal::value.
Peek() [2/3]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
Value v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Peek (int depth = 0) [inline], [private]
Definition at line 7550 of file function-body-decoder-impl.h.
                                      {
    DCHECK(!control_.empty());
    uint32_t limit = control_.back().stack_depth;
    if (V8_UNLIKELY(stack_.size() <= limit + depth)) {
      // Peeking past the current control start in reachable code.
      if (!VALIDATE(decoding_mode == kFunctionBody &&
                    control_.back().unreachable())) {
        NotEnoughArgumentsError(depth + 1, stack_.size() - limit);
      }
      return UnreachableValue(this->pc_);
    }
    DCHECK_LT(depth, stack_.size());
    return *(stack_.end() - depth - 1);
  }
References v8::internal::wasm::FastZoneVector< T >::back(), DCHECK, DCHECK_LT, v8::internal::wasm::FastZoneVector< T >::empty(), v8::internal::wasm::FastZoneVector< T >::end(), v8::internal::wasm::kFunctionBody, v8::internal::wasm::FastZoneVector< T >::size(), V8_UNLIKELY, and VALIDATE.
Peek() [3/3]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
Value v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Peek (ValueType expected) [inline], [private]
Definition at line 7565 of file function-body-decoder-impl.h.
{ return Peek(0, 0, expected); }
References v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Peek().
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Peek().
Pop() [1/2]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
Value v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Pop () [inline], [private]
Definition at line 7529 of file function-body-decoder-impl.h.
                        {
    DCHECK(!control_.empty());
    uint32_t limit = control_.back().stack_depth;
    if (V8_UNLIKELY(stack_size() <= limit)) {
      // Popping past the current control start in reachable code.
      if (!VALIDATE(control_.back().unreachable())) {
        NotEnoughArgumentsError(1, 0);
      }
      return UnreachableValue(this->pc_);
    }
    Value top_of_stack = stack_.back();
    stack_.pop();
    return top_of_stack;
  }
References v8::internal::wasm::FastZoneVector< T >::back(), DCHECK, v8::internal::wasm::FastZoneVector< T >::empty(), v8::internal::wasm::FastZoneVector< T >::pop(), V8_UNLIKELY, and VALIDATE.
Pop() [2/2]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
Value v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Pop (int index, ValueType expected) [inline], [private]
Definition at line 7515 of file function-body-decoder-impl.h.
                                                     {
    Value value = Pop();
    ValidateStackValue(index, value, expected);
    return value;
  }
References v8::internal::index, and v8::internal::value.
PopArgs() [1/2]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
PoppedArgVector v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PopArgs (const FunctionSig * sig) [inline], [private]
Definition at line 5083 of file function-body-decoder-impl.h.
                                                            {
    return PopSomeArgs(sig, static_cast<int>(sig->parameter_count()));
  }
References v8::internal::sig.
PopArgs() [2/2]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
PoppedArgVector v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PopArgs (const StructType * type) [inline], [private]
Definition at line 5045 of file function-body-decoder-impl.h.
                                                            {
    int count = static_cast<int>(type->field_count());
    EnsureStackArguments(count);
    DCHECK_LE(control_.back().stack_depth, stack_size());
    DCHECK_GE(stack_size() - control_.back().stack_depth, count);
    Value* args_base = stack_.end() - count;
    for (int i = 0; i < count; i++) {
      ValidateStackValue(i, args_base[i], type->field(i).Unpacked());
    }
    // Note: Popping from the {FastZoneVector} does not invalidate the old (now
    // out-of-range) elements.
    stack_.pop(count);
    return PoppedArgVector{base::VectorOf(args_base, count)};
  }
References v8::internal::wasm::FastZoneVector< T >::back(), DCHECK_GE, DCHECK_LE, v8::internal::wasm::FastZoneVector< T >::end(), v8::internal::wasm::FastZoneVector< T >::pop(), v8::internal::tracing::type, and v8::base::VectorOf().
PopControl()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
void v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PopControl () [inline], [private]
Definition at line 5125 of file function-body-decoder-impl.h.
                    {
    // This cannot be the outermost control block.
    DCHECK_LT(1, control_.size());
    Control* c = &control_.back();
    DCHECK_LE(c->stack_depth, stack_.size());
    CALL_INTERFACE_IF_OK_AND_PARENT_REACHABLE(PopControl, c);
    // - In non-unreachable code, a loop just leaves the values on the stack.
    // - In unreachable code, it is not guaranteed that we have Values of the
    // correct types on the stack, so we have to make sure we do. Their values
    // do not matter, so we might as well push the (uninitialized) values of
    // the loop's end merge.
    if (!c->is_loop() || c->unreachable()) {
      PushMergeValues(c, &c->end_merge);
    }
    RollbackLocalsInitialization(c);
    bool parent_reached =
        c->reachable() || c->end_merge.reached || c->is_onearmed_if();
    control_.pop();
    // If the parent block was reachable before, but the popped control does not
    // return to here, this block becomes "spec only reachable".
    if (!parent_reached) SetSucceedingCodeDynamicallyUnreachable();
    current_code_reachable_and_ok_ =
        VALIDATE(this->ok()) && control_.back().reachable();
  }
References v8::internal::wasm::FastZoneVector< T >::back(), CALL_INTERFACE_IF_OK_AND_PARENT_REACHABLE, DCHECK_LE, DCHECK_LT, v8::internal::wasm::FastZoneVector< T >::pop(), v8::internal::wasm::FastZoneVector< T >::size(), and VALIDATE.
PopDescriptor()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
Value v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PopDescriptor (ModuleTypeIndex described_index) [inline], [private]
Definition at line 5518 of file function-body-decoder-impl.h.
                                                       {
    const TypeDefinition& type = this->module_->type(described_index);
    if (!type.has_descriptor()) return Value{nullptr, kWasmVoid};
    DCHECK(this->enabled_.has_custom_descriptors());
    ValueType desc_type =
        ValueType::RefNull(this->module_->heap_type(type.descriptor)).AsExact();
    return Pop(desc_type);
  }
References v8::internal::wasm::ValueType::AsExact(), DCHECK, v8::internal::wasm::kWasmVoid, and v8::internal::tracing::type.
PopPackedArray()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
Value v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PopPackedArray (uint32_t operand_index, ValueType expected_element_type, WasmArrayAccess access) [inline], [private]
Definition at line 7592 of file function-body-decoder-impl.h.
                                               {
    Value array = Pop();
    if (array.type.is_bottom()) {
      // We are in a polymorphic stack. Leave the stack as it is.
      DCHECK(!current_code_reachable_and_ok_);
      return array;
    }
    // Inputs of type "none" are okay due to implicit upcasting. The stringref
    // spec doesn't say this explicitly yet, but it's consistent with the rest
    // of Wasm. (Of course such inputs will trap at runtime.) See:
    // https://github.com/WebAssembly/stringref/issues/66
    if (array.type.is_reference_to(HeapType::kNone)) return array;
    if (VALIDATE(array.type.is_object_reference() && array.type.has_index())) {
      ModuleTypeIndex ref_index = array.type.ref_index();
      if (VALIDATE(this->module_->has_array(ref_index))) {
        const ArrayType* array_type = this->module_->array_type(ref_index);
        if (VALIDATE(array_type->element_type() == expected_element_type &&
                     (access == WasmArrayAccess::kRead ||
                      array_type->mutability()))) {
          return array;
        }
      }
    }
    PopTypeError(operand_index, array,
                 (std::string("array of ") +
                  (access == WasmArrayAccess::kWrite ? "mutable " : "") +
                  expected_element_type.name())
                     .c_str());
    return array;
  }
References DCHECK, v8::internal::wasm::ArrayType::element_type(), v8::internal::wasm::ArrayTypeBase::mutability(), v8::internal::wasm::ValueTypeBase::name(), v8::internal::string, and VALIDATE.
PopSomeArgs()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
PoppedArgVector v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PopSomeArgs (const FunctionSig * sig, int count) [inline], [private]
Definition at line 5066 of file function-body-decoder-impl.h.
                                                                           {
    DCHECK_LE(count, static_cast<int>(sig->parameter_count()));
    EnsureStackArguments(count);
    DCHECK_LE(control_.back().stack_depth, stack_size());
    DCHECK_GE(stack_size() - control_.back().stack_depth, count);
    Value* args_base = stack_.end() - count;
    for (int i = 0; i < count; ++i) {
      ValidateStackValue(i, args_base[i], sig->GetParam(i));
    }
    // Note: Popping from the {FastZoneVector} does not invalidate the old (now
    // out-of-range) elements.
    stack_.pop(count);
    return PoppedArgVector{base::VectorOf(args_base, count)};
  }
References v8::internal::wasm::FastZoneVector< T >::back(), DCHECK_GE, DCHECK_LE, v8::internal::wasm::FastZoneVector< T >::end(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::FastZoneVector< T >::pop(), v8::internal::sig, and v8::base::VectorOf().
PopTypeError() [1/3]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
V8_NOINLINE V8_PRESERVE_MOST void v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PopTypeError (int index, Value val, const char * expected) [inline], [private]
Definition at line 7488 of file function-body-decoder-impl.h.
                                                                       {
    this->DecodeError(val.pc(), "%s[%d] expected %s, found %s of type %s",
                      SafeOpcodeNameAt(this->pc_), index, expected,
                      SafeOpcodeNameAt(val.pc()), val.type.name().c_str());
  }
References v8::internal::wasm::DecodeError(), and v8::internal::index.
PopTypeError() [2/3]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
V8_NOINLINE V8_PRESERVE_MOST void v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PopTypeError (int index, Value val, std::string expected) [inline], [private]
Definition at line 7495 of file function-body-decoder-impl.h.
                                                                     {
    PopTypeError(index, val, expected.c_str());
  }
References v8::internal::index.
PopTypeError() [3/3]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
V8_NOINLINE V8_PRESERVE_MOST void v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PopTypeError (int index, Value val, ValueType expected) [inline], [private]
Definition at line 7500 of file function-body-decoder-impl.h.
                                                                     {
    PopTypeError(index, val, ("type " + expected.name()).c_str());
  }
References v8::internal::index, and v8::internal::wasm::ValueTypeBase::name().
position()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
WasmCodePosition v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::position () const [inline]
Definition at line 3132 of file function-body-decoder-impl.h.
                                    {
    int offset = static_cast<int>(this->pc_ - this->start_);
    DCHECK_EQ(this->pc_ - this->start_, offset); // overflows cannot happen
    return offset;
  }
References DCHECK_EQ, v8::internal::wasm::Decoder::pc_, and v8::internal::wasm::Decoder::start_.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::AddOutOfLineTrap(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayCopy(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayInitSegment(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayNew(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayNewFixed(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayNewSegment(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::AtomicLoadMem(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::AtomicStoreMem(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::AtomicWait(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrOnCastAbstractFromAnyRejectShared(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallBuiltinUnsharedCastFromAny(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallBuiltinUnsharedTestFromAny(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallDirect(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallIndirectImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallRefImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitBreakpoint(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitCoverageInstrumentationIfReachable(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitDebuggingInfo(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineWasmCall(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LoadLane(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LoadMem(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LoadTransform(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Loop(), v8::internal::wasm::TurboshaftGraphBuildingInterface::NextInstruction(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::RefFunc(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::RegisterProtectedInstruction(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Rethrow(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ReturnImpl(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StartFunction(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StartFunctionBody(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StoreLane(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StoreMem(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringAsIter(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringAsWtf16(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringAsWtf8(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringCompare(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringConcat(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringConst(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringEncodeWtf16(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringEncodeWtf16Array(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringEncodeWtf8(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringEncodeWtf8Array(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringEq(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringFromCodePoint(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringHash(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringIsUSVSequence(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringMeasureWtf8(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringNewWtf16(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringNewWtf16Array(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringNewWtf8(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringNewWtf8Array(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringViewIterAdvance(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringViewIterNext(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringViewIterRewind(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringViewIterSlice(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringViewWtf16Encode(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringViewWtf16GetCodeUnit(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringViewWtf16Slice(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringViewWtf8Advance(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringViewWtf8Encode(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringViewWtf8Slice(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructNew(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TableCopy(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TableFill(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TableGet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TableGrow(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TableInit(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TableSet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Throw(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ThrowRef(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TierupCheckOnTailCall(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TraceFunctionEntry(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TraceFunctionExit(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::UnOp().
Push() [1/2]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
Value* v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Push (Value value) [inline], [private]
Definition at line 7429 of file function-body-decoder-impl.h.
                                     {
    DCHECK_IMPLIES(this->ok(), value.type != kWasmVoid);
    if (!VALIDATE(!this->is_shared_ || value.type.is_shared())) {
      this->DecodeError(value.pc(), "%s does not have a shared type",
                        SafeOpcodeNameAt(value.pc()));
      return nullptr;
    }
    // {stack_.EnsureMoreCapacity} should have been called before, either in the
    // central decoding loop, or individually if more than one element is
    // pushed.
    stack_.push(value);
    return &stack_.back();
  }
References v8::internal::wasm::FastZoneVector< T >::back(), DCHECK_IMPLIES, v8::internal::wasm::DecodeError(), v8::internal::wasm::kWasmVoid, v8::internal::wasm::FastZoneVector< T >::push(), VALIDATE, and v8::internal::value.
Push() [2/2]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
Value* v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Push (ValueType type) [inline], [private]
Definition at line 7443 of file function-body-decoder-impl.h.
{ return Push(CreateValue(type)); }
References v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Push(), and v8::internal::tracing::type.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Push().
PushControl()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
Control* v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PushControl (ControlKind kind, const BlockTypeImmediate & imm) [inline], [private]
Definition at line 5087 of file function-body-decoder-impl.h.
                                                                        {
    DCHECK(!control_.empty());
    ValidateParameters(&imm.sig);
    uint32_t consumed_values = static_cast<uint32_t>(imm.sig.parameter_count());
    uint32_t stack_depth = stack_.size();
    DCHECK_LE(consumed_values, stack_depth);
    uint32_t inner_stack_depth = stack_depth - consumed_values;
    DCHECK_LE(control_.back().stack_depth, inner_stack_depth);
    uint32_t init_stack_depth = this->locals_initialization_stack_depth();
    Reachability reachability = control_.back().innerReachability();
    control_.EnsureMoreCapacity(1, this->zone_);
    control_.emplace_back(this->zone_, kind, inner_stack_depth,
                          init_stack_depth, this->pc_, reachability);
    Control* new_block = &control_.back();
    Value* arg_base = stack_.end() - consumed_values;
    // Update the type of input nodes to the more general types expected by the
    // block. In particular, in unreachable code, the input would have bottom
    // type otherwise.
    for (uint32_t i = 0; i < consumed_values; ++i) {
      DCHECK_IMPLIES(this->ok(), IsSubtypeOf(arg_base[i].type, imm.in_type(i),
                                             this->module_) ||
                                     arg_base[i].type == kWasmBottom);
      arg_base[i].type = imm.in_type(i);
    }
    // Initialize start- and end-merges of {c} with values according to the
    // in- and out-types of {c} respectively.
    const uint8_t* pc = this->pc_;
    InitMerge(&new_block->end_merge, imm.out_arity(), [pc, &imm](uint32_t i) {
      return Value{pc, imm.out_type(i)};
    });
    InitMerge(&new_block->start_merge, imm.in_arity(),
              [arg_base](uint32_t i) { return arg_base[i]; });
    return new_block;
  }
References v8::internal::wasm::FastZoneVector< T >::back(), v8::internal::DCHECK(), DCHECK_IMPLIES, DCHECK_LE, v8::internal::wasm::FastZoneVector< T >::emplace_back(), v8::internal::wasm::FastZoneVector< T >::empty(), v8::internal::wasm::FastZoneVector< T >::end(), v8::internal::wasm::FastZoneVector< T >::EnsureMoreCapacity(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::BlockTypeImmediate::in_type(), v8::internal::wasm::IsSubtypeOf(), v8::internal::wasm::kWasmBottom, v8::internal::wasm::BlockTypeImmediate::out_arity(), v8::internal::Signature< T >::parameter_count(), v8::internal::wasm::BlockTypeImmediate::sig, v8::internal::wasm::FastZoneVector< T >::size(), v8::internal::this, and v8::internal::tracing::type.
PushMergeValues()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
void v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PushMergeValues (Control * c, Merge< Value > * merge) [inline], [private]
Definition at line 7445 of file function-body-decoder-impl.h.
                                                        {
    if constexpr (decoding_mode == kConstantExpression) return;
    DCHECK_EQ(c, &control_.back());
    DCHECK(merge == &c->start_merge || merge == &c->end_merge);
    stack_.shrink_to(c->stack_depth);
    if (merge->arity == 1) {
      // {stack_.EnsureMoreCapacity} should have been called before in the
      // central decoding loop.
      Push(merge->vals.first);
    } else {
      stack_.EnsureMoreCapacity(merge->arity, this->zone_);
      for (uint32_t i = 0; i < merge->arity; i++) {
        Push(merge->vals.array[i]);
      }
    }
    DCHECK_EQ(c->stack_depth + merge->arity, stack_.size());
  }
References v8::internal::wasm::Merge< Value >::arity, v8::internal::wasm::Merge< Value >::array, v8::internal::wasm::FastZoneVector< T >::back(), DCHECK, DCHECK_EQ, v8::internal::wasm::FastZoneVector< T >::EnsureMoreCapacity(), v8::internal::wasm::Merge< Value >::first, v8::internal::wasm::kConstantExpression, v8::internal::wasm::FastZoneVector< T >::shrink_to(), v8::internal::wasm::FastZoneVector< T >::size(), v8::internal::this, and v8::internal::wasm::Merge< Value >::vals.
PushParameters()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
Value* v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PushParameters (const FunctionSig * sig) [inline], [private]
Definition at line 7477 of file function-body-decoder-impl.h.
                                                {
    return PushValueTypes(sig->parameters());
  }
References v8::internal::sig.
PushReturns() [1/2]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
Value* v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PushReturns (const FunctionSig * sig) [inline], [private]
Definition at line 7481 of file function-body-decoder-impl.h.
                                             {
    return PushValueTypes(sig->returns());
  }
References v8::internal::sig.
PushReturns() [2/2]
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
void v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PushReturns (ReturnVector values) [inline], [private]
Definition at line 7463 of file function-body-decoder-impl.h.
                                                  {
    stack_.EnsureMoreCapacity(static_cast<int>(values.size()), this->zone_);
    for (Value& value : values) Push(value);
  }
References v8::internal::wasm::FastZoneVector< T >::EnsureMoreCapacity(), v8::base::SmallVector< T, kSize, Allocator >::size(), v8::internal::this, and v8::internal::value.
PushValueTypes()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
Value* v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PushValueTypes (const base::Vector< const ValueType > types) [inline], [private]
Definition at line 7468 of file function-body-decoder-impl.h.
                                                                 {
    size_t count = types.size();
    stack_.EnsureMoreCapacity(static_cast<int>(count), this->zone_);
    for (size_t i = 0; i < count; ++i) {
      Push(types[i]);
    }
    return stack_.end() - count;
  }
References v8::internal::wasm::FastZoneVector< T >::end(), v8::internal::wasm::FastZoneVector< T >::EnsureMoreCapacity(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::base::Vector< T >::size().
requires()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
template<typename... ValueTypes>
v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::requires ((std::is_same_v< ValueType, ValueTypes >||std::is_base_of_v< IndependentValueType, ValueTypes >) && ...) [inline], [private]
Definition at line 7572 of file function-body-decoder-impl.h.
                                    {
    constexpr int kCount = sizeof...(ValueTypes);
    EnsureStackArguments(kCount);
    DCHECK_LE(control_.back().stack_depth, stack_size());
    DCHECK_GE(stack_size() - control_.back().stack_depth, kCount);
    // Note: Popping from the {FastZoneVector} does not invalidate the old (now
    // out-of-range) elements.
    stack_.pop(kCount);
    auto ValidateAndGetNextArg = [this, i = 0](ValueType type) mutable {
      ValidateStackValue(i, stack_.end()[i], type);
      return stack_.end()[i++];
    };
    return {ValidateAndGetNextArg(expected_types)...};
  }
References v8::internal::wasm::FastZoneVector< T >::back(), DCHECK_GE, DCHECK_LE, v8::internal::wasm::FastZoneVector< T >::end(), v8::internal::wasm::FastZoneVector< T >::pop(), and v8::internal::tracing::type.
RollbackLocalsInitialization()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
void v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::RollbackLocalsInitialization (Control * c) [inline]
Definition at line 3185 of file function-body-decoder-impl.h.
                                                {
    if (!has_nondefaultable_locals_) return;
    uint32_t previous_stack_height = c->init_stack_depth;
    while (locals_initializers_stack_.size() > previous_stack_height) {
      uint32_t local_index = locals_initializers_stack_.back();
      locals_initializers_stack_.pop();
      initialized_locals_[local_index] = false;
    }
  }
References v8::internal::wasm::FastZoneVector< T >::back(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::has_nondefaultable_locals_, v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::initialized_locals_, v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::locals_initializers_stack_, v8::internal::wasm::FastZoneVector< T >::pop(), and v8::internal::wasm::FastZoneVector< T >::size().
SafeOpcodeNameAt()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
const char* v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::SafeOpcodeNameAt (const uint8_t * pc) [inline]
Definition at line 3120 of file function-body-decoder-impl.h.
                                                  {
    if (!pc) return "<null>";
    if (pc >= this->end_) return "<end>";
    WasmOpcode opcode = static_cast<WasmOpcode>(*pc);
    if (!WasmOpcodes::IsPrefixOpcode(opcode)) {
      return WasmOpcodes::OpcodeName(static_cast<WasmOpcode>(opcode));
    }
    opcode = this->template read_prefixed_opcode<Decoder::FullValidationTag>(pc)
                 .first;
    return WasmOpcodes::OpcodeName(opcode);
  }
References v8::internal::wasm::Decoder::end_, v8::internal::wasm::WasmOpcodes::IsPrefixOpcode(), v8::internal::wasm::WasmOpcodes::OpcodeName(), and v8::internal::wasm::Decoder::pc().
Referenced by v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
set_local_initialized()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
void v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::set_local_initialized (uint32_t local_index) [inline]
Definition at line 3171 of file function-body-decoder-impl.h.
                                                   {
    DCHECK_GT(this->num_locals_, local_index);
    if (!has_nondefaultable_locals_) return;
    // This implicitly covers defaultable locals too (which are always
    // initialized).
    if (is_local_initialized(local_index)) return;
    initialized_locals_[local_index] = true;
    locals_initializers_stack_.push(local_index);
  }
References DCHECK_GT, v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::has_nondefaultable_locals_, v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::initialized_locals_, v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::is_local_initialized(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::locals_initializers_stack_, v8::internal::wasm::WasmDecoder< ValidationTag, kFunctionBody >::num_locals_, and v8::internal::wasm::FastZoneVector< T >::push().
SetSucceedingCodeDynamicallyUnreachable()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
void v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::SetSucceedingCodeDynamicallyUnreachable () [inline], [private]
Definition at line 3354 of file function-body-decoder-impl.h.
                                                 {
    Control* current = &control_.back();
    if (current->reachable()) {
      current->reachability = kSpecOnlyReachable;
      current_code_reachable_and_ok_ = false;
    }
  }
References v8::internal::wasm::FastZoneVector< T >::back(), and v8::internal::wasm::kSpecOnlyReachable.
Simd8x16ShuffleOp()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
uint32_t v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Simd8x16ShuffleOp (uint32_t opcode_length) [inline], [private]
Definition at line 5279 of file function-body-decoder-impl.h.
                                                     {
    Simd128Immediate imm(this, this->pc_ + opcode_length, validate);
    if (!this->Validate(this->pc_ + opcode_length, imm)) return 0;
    auto [input0, input1] = Pop(kWasmS128, kWasmS128);
    Value* result = Push(kWasmS128);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(Simd8x16ShuffleOp, imm, input0, input1,
                                       result);
    return opcode_length + 16;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::wasm::kWasmS128, and v8::base::internal::result.
SimdConstOp()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
uint32_t v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::SimdConstOp (uint32_t opcode_length) [inline], [private]
Definition at line 5250 of file function-body-decoder-impl.h.
                                               {
    Simd128Immediate imm(this, this->pc_ + opcode_length, validate);
    Value* result = Push(kWasmS128);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(S128Const, imm, result);
    return opcode_length + kSimd128Size;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::kSimd128Size, v8::internal::wasm::kWasmS128, and v8::base::internal::result.
SimdExtractLane()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
uint32_t v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::SimdExtractLane (WasmOpcode opcode, ValueType type, uint32_t opcode_length) [inline], [private]
Definition at line 5257 of file function-body-decoder-impl.h.
                                                   {
    SimdLaneImmediate imm(this, this->pc_ + opcode_length, validate);
    if (!this->Validate(this->pc_ + opcode_length, opcode, imm)) return 0;
    Value input = Pop(kWasmS128);
    Value* result = Push(type);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(SimdLaneOp, opcode, imm,
                                       base::VectorOf({input}), result);
    return opcode_length + imm.length;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::wasm::kWasmS128, v8::internal::wasm::SimdLaneImmediate::length, v8::base::internal::result, v8::internal::tracing::type, and v8::base::VectorOf().
SimdReplaceLane()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
uint32_t v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::SimdReplaceLane (WasmOpcode opcode, ValueType type, uint32_t opcode_length) [inline], [private]
Definition at line 5268 of file function-body-decoder-impl.h.
                                                   {
    SimdLaneImmediate imm(this, this->pc_ + opcode_length, validate);
    if (!this->Validate(this->pc_ + opcode_length, opcode, imm)) return 0;
    auto [v128, lane_val] = Pop(kWasmS128, type);
    Value* result = Push(kWasmS128);
    CALL_INTERFACE_IF_OK_AND_REACHABLE(
        SimdLaneOp, opcode, imm, base::VectorOf({v128, lane_val}), result);
    return opcode_length + imm.length;
  }
References CALL_INTERFACE_IF_OK_AND_REACHABLE, v8::internal::wasm::kWasmS128, v8::internal::wasm::SimdLaneImmediate::length, v8::base::internal::result, v8::internal::tracing::type, and v8::base::VectorOf().
stack_size()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
uint32_t v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::stack_size () const [inline]
Definition at line 3147 of file function-body-decoder-impl.h.
{ return stack_.size(); }
References v8::internal::wasm::FastZoneVector< T >::size(), and v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::stack_.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::CreateFrameState(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetStackValueTypesForDebugging(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::NextInstruction().
stack_value()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
Value* v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::stack_value (uint32_t depth) const [inline]
Definition at line 3149 of file function-body-decoder-impl.h.
                                           {
    DCHECK_LT(0, depth);
    DCHECK_GE(stack_.size(), depth);
    return stack_.end() - depth;
  }
References DCHECK_GE, DCHECK_LT, v8::internal::wasm::FastZoneVector< T >::end(), v8::internal::wasm::FastZoneVector< T >::size(), and v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::stack_.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BrOnCastFailImpl(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CreateFrameState(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::DoReturn(), v8::internal::wasm::TurboshaftGraphBuildingInterface::DoReturn(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetStackValueTypesForDebugging(), v8::internal::wasm::TurboshaftGraphBuildingInterface::Loop(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::SetupControlFlowEdge().
startrel()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
int v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::startrel (const uint8_t * ptr) [inline], [private]
Definition at line 7773 of file function-body-decoder-impl.h.
                                   {
    return static_cast<int>(ptr - this->start_);
  }
TableAddressType()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
ValueType v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::TableAddressType (const WasmTable * table) [inline], [private]
Definition at line 3369 of file function-body-decoder-impl.h.
                                                               {
    return table->is_table64() ? kWasmI64 : kWasmI32;
  }
References v8::internal::wasm::WasmTable::is_table64(), v8::internal::wasm::kWasmI32, and v8::internal::wasm::kWasmI64.
TraceFailed()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
void v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::TraceFailed () [inline]
Definition at line 3110 of file function-body-decoder-impl.h.
                     {
    if (this->error_.offset()) {
      TRACE("wasm-error module+%-6d func+%d: %s\n\n", this->error_.offset(),
            this->GetBufferRelativeOffset(this->error_.offset()),
            this->error_.message().c_str());
    } else {
      TRACE("wasm-error: %s\n\n", this->error_.message().c_str());
    }
  }
References v8::internal::wasm::Decoder::error_, v8::internal::wasm::WasmError::message(), v8::internal::wasm::WasmError::offset(), v8::internal::this, and v8::internal::TRACE().
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Decode().
TypeCheckAlwaysFails()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::TypeCheckAlwaysFails (Value obj, HeapType expected_type, bool null_succeeds) [inline], [private]
Definition at line 5480 of file function-body-decoder-impl.h.
                                                {
    bool types_unrelated =
        !IsSubtypeOf(ValueType::Ref(expected_type), obj.type, this->module_) &&
        !IsSubtypeOf(obj.type, ValueType::RefNull(expected_type),
                     this->module_);
    // For "unrelated" types the check can still succeed for the null value on
    // instructions treating null as a successful check.
    // TODO(12868): For string views, this implementation anticipates that
    // https://github.com/WebAssembly/stringref/issues/40 will be resolved
    // by making the views standalone types.
    return (types_unrelated &&
            (!null_succeeds || !obj.type.is_nullable() ||
             obj.type.is_string_view() || expected_type.is_string_view())) ||
           ((!null_succeeds || !obj.type.is_nullable()) &&
            (expected_type.representation() == HeapType::kNone ||
             expected_type.representation() == HeapType::kNoFunc ||
             expected_type.representation() == HeapType::kNoExtern ||
             expected_type.representation() == HeapType::kNoExn ||
             expected_type.representation() == HeapType::kNoneShared ||
             expected_type.representation() == HeapType::kNoFuncShared ||
             expected_type.representation() == HeapType::kNoExternShared ||
             expected_type.representation() == HeapType::kNoExnShared));
  }
References v8::internal::wasm::ValueTypeBase::is_string_view(), v8::internal::wasm::IsSubtypeOf(), v8::internal::wasm::HeapType::representation(), and v8::internal::this.
TypeCheckAlwaysSucceeds()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::TypeCheckAlwaysSucceeds (Value obj, HeapType type) [inline], [private]
Definition at line 5507 of file function-body-decoder-impl.h.
                                                         {
    return IsSubtypeOf(obj.type, ValueType::RefNull(type), this->module_);
  }
References v8::internal::wasm::IsSubtypeOf(), v8::internal::this, and v8::internal::tracing::type.
TypeCheckBranch()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
template<PushBranchValues push_branch_values, RewriteStackTypes rewrite_types>
bool v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::TypeCheckBranch (Control * c) [inline], [private]
Definition at line 7820 of file function-body-decoder-impl.h.
                                   {
    return TypeCheckStackAgainstMerge<kNonStrictCounting, push_branch_values,
                                      kBranchMerge, rewrite_types>(
        c->br_merge());
  }
TypeCheckFallThru()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::TypeCheckFallThru () [inline], [private]
Definition at line 7804 of file function-body-decoder-impl.h.
                           {
    return TypeCheckStackAgainstMerge<kStrictCounting, PushBranchValues::kYes,
                                      kFallthroughMerge,
                                      RewriteStackTypes::kNo>(
        &control_.back().end_merge);
  }
References v8::internal::wasm::FastZoneVector< T >::back().
TypeCheckOneArmedIf()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::TypeCheckOneArmedIf (Control * c) [inline], [private]
Definition at line 7785 of file function-body-decoder-impl.h.
                                       {
    DCHECK(c->is_onearmed_if());
    if (c->end_merge.arity != c->start_merge.arity) {
      this->DecodeError(c->pc(),
                        "start-arity and end-arity of one-armed if must match");
      return false;
    }
    for (uint32_t i = 0; i < c->start_merge.arity; ++i) {
      Value& start = c->start_merge[i];
      Value& end = c->end_merge[i];
      if (!IsSubtypeOf(start.type, end.type, this->module_)) {
        this->DecodeError("type error in merge[%u] (expected %s, got %s)", i,
                          end.type.name().c_str(), start.type.name().c_str());
        return false;
      }
    }
    return true;
  }
References DCHECK, v8::internal::wasm::DecodeError(), v8::internal::compiler::end(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::IsSubtypeOf(), and v8::internal::this.
TypeCheckStackAgainstMerge()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
template<StackElementsCountMode strict_count, PushBranchValues push_branch_values, MergeType merge_type, RewriteStackTypes rewrite_types>
bool v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::TypeCheckStackAgainstMerge (Merge< Value > * merge) [inline], [private]
Definition at line 7675 of file function-body-decoder-impl.h.
                                                                 {
    uint32_t arity = merge->arity;
    uint32_t actual = stack_.size() - control_.back().stack_depth;
    // Handle trivial cases first. Arity 0 is the most common case.
    if (arity == 0 && (!strict_count || actual == 0)) return true;
    // Arity 1 is still common enough that we handle it separately (only doing
    // the most basic subtype check).
    if (arity == 1 && (strict_count ? actual == arity : actual >= arity)) {
      if (stack_.back().type == merge->vals.first.type) return true;
    }
    return TypeCheckStackAgainstMerge_Slow<strict_count, push_branch_values,
                                           merge_type, rewrite_types>(merge);
  }
References v8::internal::wasm::Merge< Value >::arity, v8::internal::wasm::FastZoneVector< T >::back(), v8::internal::wasm::Merge< Value >::first, v8::internal::wasm::FastZoneVector< T >::size(), and v8::internal::wasm::Merge< Value >::vals.
TypeCheckStackAgainstMerge_Slow()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
template<StackElementsCountMode strict_count, PushBranchValues push_branch_values, MergeType merge_type, RewriteStackTypes rewrite_types>
V8_PRESERVE_MOST V8_NOINLINE bool v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::TypeCheckStackAgainstMerge_Slow (Merge< Value > * merge) [inline], [private]
Definition at line 7693 of file function-body-decoder-impl.h.
                           {
    constexpr const char* merge_description =
        merge_type == kBranchMerge ? "branch"
        : merge_type == kReturnMerge ? "return"
        : merge_type == kInitExprMerge ? "constant expression"
                                       : "fallthru";
    uint32_t arity = merge->arity;
    uint32_t actual = stack_.size() - control_.back().stack_depth;
    // Here we have to check for !unreachable(), because we need to typecheck as
    // if the current code is reachable even if it is spec-only reachable.
    if (V8_LIKELY(decoding_mode == kConstantExpression ||
                  !control_.back().unreachable())) {
      if (V8_UNLIKELY(strict_count ? actual != arity : actual < arity)) {
        this->DecodeError("expected %u elements on the stack for %s, found %u",
                          arity, merge_description, actual);
        return false;
      }
      // Typecheck the topmost {merge->arity} values on the stack.
      Value* stack_values = stack_.end() - arity;
      for (uint32_t i = 0; i < arity; ++i) {
        Value& val = stack_values[i];
        Value& old = (*merge)[i];
        if (!IsSubtypeOf(val.type, old.type, this->module_)) {
          this->DecodeError("type error in %s[%u] (expected %s, got %s)",
                            merge_description, i, old.type.name().c_str(),
                            val.type.name().c_str());
          return false;
        }
        if constexpr (static_cast<bool>(rewrite_types)) {
          // Upcast type on the stack to the target type of the label.
          val.type = old.type;
        }
      }
      return true;
    }
    // Unreachable code validation starts here.
    if (V8_UNLIKELY(strict_count && actual > arity)) {
      this->DecodeError("expected %u elements on the stack for %s, found %u",
                        arity, merge_description, actual);
      return false;
    }
    // TODO(manoskouk): Use similar code as above if we keep unreachable checks.
    for (int i = arity - 1, depth = 0; i >= 0; --i, ++depth) {
      Peek(depth, i, (*merge)[i].type);
    }
    if constexpr (static_cast<bool>(push_branch_values)) {
      uint32_t inserted_value_count =
          static_cast<uint32_t>(EnsureStackArguments(arity));
      if (inserted_value_count > 0) {
        // stack_.EnsureMoreCapacity() may have inserted unreachable values into
        // the bottom of the stack. If so, mark them with the correct type. If
        // drop values were also inserted, disregard them, as they will be
        // dropped anyway.
        Value* stack_base = stack_value(arity);
        for (uint32_t i = 0; i < std::min(arity, inserted_value_count); i++) {
          if (stack_base[i].type == kWasmBottom) {
            stack_base[i].type = (*merge)[i].type;
          }
        }
      }
    }
    return VALIDATE(this->ok());
  }
References v8::internal::wasm::Merge< Value >::arity, v8::internal::wasm::FastZoneVector< T >::back(), v8::internal::wasm::DecodeError(), v8::internal::wasm::FastZoneVector< T >::end(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::IsSubtypeOf(), v8::internal::wasm::kConstantExpression, v8::internal::wasm::kWasmBottom, v8::internal::wasm::FastZoneVector< T >::size(), v8::internal::this, v8::internal::tracing::type, V8_LIKELY, V8_UNLIKELY, and VALIDATE.
UnknownOpcodeError()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
static int v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::UnknownOpcodeError (WasmFullDecoder< ValidationTag, Interface, decoding_mode > * decoder, WasmOpcode opcode) [inline], [static], [private]
Definition at line 4850 of file function-body-decoder-impl.h.
                                                                             {
    decoder->DecodeError("Invalid opcode 0x%x", opcode);
    return 0;
  }
References v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeError().
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::GetOpcodeHandlerTableEntry().
UnreachableValue()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
static Value v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::UnreachableValue (const uint8_t * pc) [inline], [static], [private]
Definition at line 3350 of file function-body-decoder-impl.h.
                                                   {
    return Value{pc, kWasmBottom};
  }
References v8::internal::wasm::kWasmBottom.
ValidateParameters()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
void v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::ValidateParameters (const FunctionSig * sig) [inline], [private]
Definition at line 5029 of file function-body-decoder-impl.h.
                                                            {
    int num_params = static_cast<int>(sig->parameter_count());
    EnsureStackArguments(num_params);
    Value* param_base = stack_.end() - num_params;
    for (int i = 0; i < num_params; i++) {
      ValidateStackValue(i, param_base[i], sig->GetParam(i));
    }
  }
References v8::internal::wasm::FastZoneVector< T >::end(), and v8::internal::sig.
ValidateStackValue()
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
void v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::ValidateStackValue (int index, Value value, ValueType expected) [inline], [private]
Definition at line 7521 of file function-body-decoder-impl.h.
                                                        {
    if (!VALIDATE(IsSubtypeOf(value.type, expected, this->module_) ||
                  value.type == kWasmBottom || expected == kWasmBottom)) {
      PopTypeError(index, value, expected);
    }
  }
References v8::internal::index, v8::internal::wasm::IsSubtypeOf(), v8::internal::wasm::kWasmBottom, v8::internal::this, VALIDATE, and v8::internal::value.
Member Data Documentation
control_
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
FastZoneVector<Control> v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::control_ [private]
Definition at line 3337 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::control_at(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::control_depth(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Decode(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeFunctionBody(), and v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::~WasmFullDecoder().
current_catch_
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
int32_t v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::current_catch_ = -1 [private]
Definition at line 3348 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::current_catch().
current_code_reachable_and_ok_
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::current_code_reachable_and_ok_ = true [private]
Definition at line 3341 of file function-body-decoder-impl.h.
has_nondefaultable_locals_
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
bool v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::has_nondefaultable_locals_ = true [private]
Definition at line 3345 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::InitializeInitializedLocalsTracking(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::is_local_initialized(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::RollbackLocalsInitialization(), and v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::set_local_initialized().
initialized_locals_
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
bool* v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::initialized_locals_ [private]
Definition at line 3329 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::InitializeInitializedLocalsTracking(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::is_local_initialized(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::RollbackLocalsInitialization(), and v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::set_local_initialized().
interface_
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
Interface v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::interface_ [private]
Definition at line 3320 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::interface().
locals_initializers_stack_
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
FastZoneVector<uint32_t> v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::locals_initializers_stack_ [private]
Definition at line 3334 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::InitializeInitializedLocalsTracking(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::locals_initialization_stack_depth(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::RollbackLocalsInitialization(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::set_local_initialized(), and v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::~WasmFullDecoder().
locals_offset_
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
uint32_t v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::locals_offset_ = 0 [private]
Definition at line 3319 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Decode(), and v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::pc_relative_offset().
stack_
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
FastZoneVector<Value> v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::stack_ [private]
Definition at line 3323 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Decode(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::stack_size(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::stack_value(), and v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::~WasmFullDecoder().
validate
template<typename ValidationTag , typename Interface , DecodingMode decoding_mode = kFunctionBody>
constexpr ValidationTag v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::validate = {} [static], [constexpr], [private]
Definition at line 7878 of file function-body-decoder-impl.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/function-body-decoder-impl.h