v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::WeakScriptHandle Class Reference
Public Member Functions
WeakScriptHandle (DirectHandle< Script > script, Isolate *isolate)
~WeakScriptHandle ()
WeakScriptHandle (WeakScriptHandle &&) V8_NOEXCEPT=default
DirectHandle< Script > handle () const
void Clear ()
int script_id () const
const std::shared_ptr< const char[]> & source_url () const
Private Attributes
std::unique_ptr< Address * > location_
int script_id_
std::shared_ptr< const char[]> source_url_
Isolate * isolate_
Detailed Description
Definition at line 224 of file wasm-engine.cc.
Constructor & Destructor Documentation
WeakScriptHandle() [1/2]
v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::WeakScriptHandle::WeakScriptHandle (DirectHandle< Script > script, Isolate * isolate) [inline]
Definition at line 226 of file wasm-engine.cc.
      : script_id_(script->id()), isolate_(isolate) {
    DCHECK(IsString(script->name()) || IsUndefined(script->name()));
    if (IsString(script->name())) {
      source_url_ = Cast<String>(script->name())->ToCString();
    }
    auto global_handle = isolate->global_handles()->Create(*script);
    location_ = std::make_unique<Address*>(global_handle.location());
    GlobalHandles::MakeWeak(location_.get());
  }
References v8::internal::GlobalHandles::Create(), v8::internal::DCHECK(), v8::internal::Isolate::global_handles(), v8::internal::GlobalHandles::MakeWeak(), and v8::internal::script.
 WeakScriptHandle()
v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::WeakScriptHandle::~WeakScriptHandle () [inline]
Definition at line 237 of file wasm-engine.cc.
                      {
    // Usually the destructor of this class is called after the weak callback,
    // because the Script keeps the NativeModule alive. In that case,
    // {location_} is already cleared, and there is nothing to do.
    if (location_ == nullptr || *location_ == nullptr) return;
    // For asm.js modules, the Script usually outlives the NativeModule.
    // We must destroy the GlobalHandle before freeing the memory that's
    // backing {location_}, so that when the Script does die eventually, there
    // is no lingering weak GlobalHandle that would try to clear {location_}.
    // We can't do that from arbitrary threads, so we must post a task to the
    // main thread.
    GetWasmEngine()->ClearWeakScriptHandle(isolate_, std::move(location_));
  }
References v8::internal::wasm::WasmEngine::ClearWeakScriptHandle(), and v8::internal::wasm::GetWasmEngine().
WeakScriptHandle() [2/2]
v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::WeakScriptHandle::WeakScriptHandle (WeakScriptHandle &&) [default]
Member Function Documentation
Clear()
void v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::WeakScriptHandle::Clear () [inline]
Definition at line 259 of file wasm-engine.cc.
{ location_.reset(); }
handle()
DirectHandle<Script> v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::WeakScriptHandle::handle () const [inline]
Definition at line 253 of file wasm-engine.cc.
                                      {
    return DirectHandle<Script>::FromSlot(*location_);
  }
script_id()
int v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::WeakScriptHandle::script_id () const [inline]
Definition at line 261 of file wasm-engine.cc.
{ return script_id_; }
source_url()
const std::shared_ptr<const char[]>& v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::WeakScriptHandle::source_url () const [inline]
Definition at line 263 of file wasm-engine.cc.
                                                        {
    return source_url_;
  }
Member Data Documentation
isolate_
Isolate* v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::WeakScriptHandle::isolate_ [private]
Definition at line 284 of file wasm-engine.cc.
location_
std::unique_ptr<Address*> v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::WeakScriptHandle::location_ [private]
Definition at line 270 of file wasm-engine.cc.
script_id_
int v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::WeakScriptHandle::script_id_ [private]
Definition at line 274 of file wasm-engine.cc.
source_url_
std::shared_ptr<const char[]> v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::WeakScriptHandle::source_url_ [private]
Definition at line 281 of file wasm-engine.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/wasm-engine.cc