v8::debug::AccessorPair Class Reference
Pairs of accessors.
#include <debug-interface.h>
Public Member Functions
AccessorPair ()=delete
v8::Local< v8::Value > getter ()
v8::Local< v8::Value > setter ()
Static Public Member Functions
static bool IsAccessorPair (v8::Local< v8::Value > obj)
static AccessorPair * Cast (v8::Value *obj)
Static Private Member Functions
static void CheckCast (v8::Value *obj)
Detailed Description
Pairs of accessors.
In the case of private accessors, getters and setters are either null or Functions.
Definition at line 624 of file debug-interface.h.
Constructor & Destructor Documentation
AccessorPair()
v8::debug::AccessorPair::AccessorPair () [delete]
Member Function Documentation
Cast()
AccessorPair * v8::debug::AccessorPair::Cast (v8::Value * obj) [inline], [static]
Definition at line 695 of file debug-interface.h.
                                               {
#ifdef V8_ENABLE_CHECKS
  CheckCast(value);
#endif
  return static_cast<AccessorPair*>(value);
}
References CheckCast(), and v8::internal::value.
CheckCast()
void v8::debug::AccessorPair::CheckCast (v8::Value * obj) [static], [private]
Definition at line 1110 of file debug-interface.cc.
                                        {
  auto obj = Utils::OpenDirectHandle(that);
  Utils::ApiCheck(i::IsAccessorPair(*obj), "v8::debug::AccessorPair::Cast",
                  "Value is not a v8::debug::AccessorPair");
}
References v8::Utils::ApiCheck(), and v8::Utils::OpenDirectHandle().
Referenced by Cast().
getter()
Local< Value > v8::debug::AccessorPair::getter ()
Definition at line 1436 of file debug-interface.cc.
                                  {
  auto accessors = Utils::OpenDirectHandle(this);
  i::Isolate* isolate = i::Isolate::Current();
  i::DirectHandle<i::Object> getter(accessors->getter(), isolate);
  return Utils::ToLocal(getter);
}
References v8::internal::Isolate::Current(), and v8::Utils::OpenDirectHandle().
IsAccessorPair()
bool v8::debug::AccessorPair::IsAccessorPair (v8::Local< v8::Value > obj) [static]
Definition at line 1450 of file debug-interface.cc.
                                                   {
  return i::IsAccessorPair(*Utils::OpenDirectHandle(*that));
}
References v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::ValueMirror::getPrivateProperties().
setter()
Local< Value > v8::debug::AccessorPair::setter ()
Definition at line 1443 of file debug-interface.cc.
                                  {
  auto accessors = Utils::OpenDirectHandle(this);
  i::Isolate* isolate = i::Isolate::Current();
  i::DirectHandle<i::Object> setter(accessors->setter(), isolate);
  return Utils::ToLocal(setter);
}
References v8::internal::Isolate::Current(), v8::Utils::OpenDirectHandle(), and v8::internal::setter.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/debug/debug-interface.h
/mnt/V8SourceCode/src/debug/debug-interface.cc