v8::internal::RegExpMacroAssemblerRISCV Class Reference
#include <regexp-macro-assembler-riscv.h>
Public Member Functions
RegExpMacroAssemblerRISCV (Isolate *isolate, Zone *zone, Mode mode, int registers_to_save)
~RegExpMacroAssemblerRISCV () override
int stack_limit_slack_slot_count () override
void AdvanceCurrentPosition (int by) override
void AdvanceRegister (int reg, int by) override
void Backtrack () override
void Bind (Label *label) override
void CheckAtStart (int cp_offset, Label *on_at_start) override
void CheckCharacter (uint32_t c, Label *on_equal) override
void CheckCharacterAfterAnd (uint32_t c, uint32_t mask, Label *on_equal) override
void CheckCharacterGT (base::uc16 limit, Label *on_greater) override
void CheckCharacterLT (base::uc16 limit, Label *on_less) override
void CheckFixedLengthLoop (Label *on_tos_equals_current_position) override
void CheckNotAtStart (int cp_offset, Label *on_not_at_start) override
void CheckNotBackReference (int start_reg, bool read_backward, Label *on_no_match) override
void CheckNotBackReferenceIgnoreCase (int start_reg, bool read_backward, bool unicode, Label *on_no_match) override
void CheckNotCharacter (uint32_t c, Label *on_not_equal) override
void CheckNotCharacterAfterAnd (uint32_t c, uint32_t mask, Label *on_not_equal) override
void CheckNotCharacterAfterMinusAnd (base::uc16 c, base::uc16 minus, base::uc16 mask, Label *on_not_equal) override
void CheckCharacterInRange (base::uc16 from, base::uc16 to, Label *on_in_range) override
void CheckCharacterNotInRange (base::uc16 from, base::uc16 to, Label *on_not_in_range) override
bool CheckCharacterInRangeArray (const ZoneList< CharacterRange > *ranges, Label *on_in_range) override
bool CheckCharacterNotInRangeArray (const ZoneList< CharacterRange > *ranges, Label *on_not_in_range) override
void CheckBitInTable (Handle< ByteArray > table, Label *on_bit_set) override
void SkipUntilBitInTable (int cp_offset, Handle< ByteArray > table, Handle< ByteArray > nibble_table, int advance_by) override
void CheckPosition (int cp_offset, Label *on_outside_input) override
bool CheckSpecialClassRanges (StandardCharacterSet type, Label *on_no_match) override
void Fail () override
DirectHandle< HeapObject > GetCode (DirectHandle< String > source, RegExpFlags flags) override
void GoTo (Label *label) override
void IfRegisterGE (int reg, int comparand, Label *if_ge) override
void IfRegisterLT (int reg, int comparand, Label *if_lt) override
void IfRegisterEqPos (int reg, Label *if_eq) override
IrregexpImplementation Implementation () override
void LoadCurrentCharacterUnchecked (int cp_offset, int character_count) override
void PopCurrentPosition () override
void PopRegister (int register_index) override
void PushBacktrack (Label *label) override
void PushCurrentPosition () override
void PushRegister (int register_index, StackCheckFlag check_stack_limit) override
void ReadCurrentPositionFromRegister (int reg) override
void ReadStackPointerFromRegister (int reg) override
void SetCurrentPositionFromEnd (int by) override
void SetRegister (int register_index, int to) override
bool Succeed () override
void WriteCurrentPositionToRegister (int reg, int cp_offset) override
void ClearRegisters (int reg_from, int reg_to) override
void WriteStackPointerToRegister (int reg) override
void print_regexp_frame_constants ()
Static Public Member Functions
static int64_t CheckStackGuardState (Address *return_address, Address raw_code, Address re_frame, uintptr_t extra_space)
Private Member Functions
void CallCFunctionFromIrregexpCode (ExternalReference function, int num_arguments)
void PushCallerSavedRegisters ()
void PopCallerSavedRegisters ()
void CheckPreemption ()
void CheckStackLimit ()
void AssertAboveStackLimitMinusSlack ()
void CallCheckStackGuardState (Register scratch, Operand extra_space_for_variables=Operand(0))
void CallIsCharacterInRangeArray (const ZoneList< CharacterRange > *ranges)
MemOperand register_location (int register_index)
int char_size () const
void BranchOrBacktrack (Label *to, Condition condition, Register rs, const Operand &rt)
void SafeCall (Label *to, Condition cond, Register rs, const Operand &rt)
void SafeReturn ()
void SafeCallTarget (Label *name)
void Push (Register source)
void Pop (Register target)
void LoadRegExpStackPointerFromMemory (Register dst)
void StoreRegExpStackPointerToMemory (Register src, Register scratch)
void PushRegExpBasePointer (Register stack_pointer, Register scratch)
void PopRegExpBasePointer (Register stack_pointer_out, Register scratch)
Isolate * isolate () const
Static Private Member Functions
static constexpr Register current_input_offset ()
static constexpr Register current_character ()
static constexpr Register end_of_input_address ()
static constexpr Register frame_pointer ()
static constexpr Register backtrack_stackpointer ()
static constexpr Register code_pointer ()
Private Attributes
const std::unique_ptr< MacroAssembler > masm_
const NoRootArrayScope no_root_array_scope_
const Mode mode_
int num_registers_
const int num_saved_registers_
Label entry_label_
Label start_label_
Label success_label_
Label backtrack_label_
Label exit_label_
Label check_preempt_label_
Label stack_overflow_label_
Label internal_failure_label_
Label fallback_label_
Static Private Attributes
static constexpr int kFramePointerOffset = 0
static constexpr int kStoredRegistersOffset = kFramePointerOffset
static constexpr int kNumCalleeRegsToRetain = 12
static constexpr int kReturnAddressOffset
static constexpr int kStackFrameHeaderOffset = kReturnAddressOffset
static constexpr int kFrameTypeOffset
static constexpr int kIsolateOffset = kFrameTypeOffset - kSystemPointerSize
static constexpr int kDirectCallOffset = kIsolateOffset - kSystemPointerSize
static constexpr int kNumOutputRegistersOffset
static constexpr int kRegisterOutputOffset
static constexpr int kInputEndOffset
static constexpr int kInputStartOffset = kInputEndOffset - kSystemPointerSize
static constexpr int kStartIndexOffset
static constexpr int kInputStringOffset
static constexpr int kSuccessfulCapturesOffset
static constexpr int kStringStartMinusOneOffset
static constexpr int kBacktrackCountOffset
static constexpr int kRegExpStackBasePointerOffset
static constexpr int kNumberOfStackLocals = 4
static constexpr int kRegisterZeroOffset
static constexpr int kInitialBufferSize = 1024
Additional Inherited Members
Detailed Description
Definition at line 16 of file regexp-macro-assembler-riscv.h.
Constructor & Destructor Documentation
RegExpMacroAssemblerRISCV()
v8::internal::RegExpMacroAssemblerRISCV::RegExpMacroAssemblerRISCV (Isolate * isolate, Zone * zone, Mode mode, int registers_to_save)
Definition at line 87 of file regexp-macro-assembler-riscv.cc.
    : NativeRegExpMacroAssembler(isolate, zone),
      masm_(std::make_unique<MacroAssembler>(
          isolate, CodeObjectRequired::kYes,
          NewAssemblerBuffer(kInitialBufferSize))),
      no_root_array_scope_(masm_.get()),
      mode_(mode),
      num_registers_(registers_to_save),
      num_saved_registers_(registers_to_save),
      entry_label_(),
      start_label_(),
      success_label_(),
      backtrack_label_(),
      exit_label_(),
      internal_failure_label_() {
  DCHECK_EQ(0, registers_to_save % 2);
  __ jmp(&entry_label_); // We'll write the entry code later.
  // If the code gets too big or corrupted, an internal exception will be
  // raised, and we will exit right away.
  __ bind(&internal_failure_label_);
  __ li(a0, Operand(FAILURE));
  __ Ret();
  __ bind(&start_label_); // And then continue from here.
}
References __, DCHECK_EQ, entry_label_, v8::internal::NativeRegExpMacroAssembler::FAILURE, internal_failure_label_, and start_label_.
 RegExpMacroAssemblerRISCV()
v8::internal::RegExpMacroAssemblerRISCV::~RegExpMacroAssemblerRISCV () [override]
Definition at line 114 of file regexp-macro-assembler-riscv.cc.
                                                      {
  // Unuse labels in case we throw away the assembler without calling GetCode.
  entry_label_.Unuse();
  start_label_.Unuse();
  success_label_.Unuse();
  backtrack_label_.Unuse();
  exit_label_.Unuse();
  check_preempt_label_.Unuse();
  stack_overflow_label_.Unuse();
  internal_failure_label_.Unuse();
  fallback_label_.Unuse();
}
References backtrack_label_, check_preempt_label_, entry_label_, exit_label_, fallback_label_, internal_failure_label_, stack_overflow_label_, start_label_, success_label_, and v8::internal::Label::Unuse().
Member Function Documentation
AdvanceCurrentPosition()
void v8::internal::RegExpMacroAssemblerRISCV::AdvanceCurrentPosition (int by) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 131 of file regexp-macro-assembler-riscv.cc.
                                                             {
  if (by != 0) {
    __ AddWord(current_input_offset(), current_input_offset(),
               Operand(by * char_size()));
  }
}
References __, char_size(), and current_input_offset().
Referenced by SkipUntilBitInTable().
AdvanceRegister()
void v8::internal::RegExpMacroAssemblerRISCV::AdvanceRegister (int reg, int by) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 138 of file regexp-macro-assembler-riscv.cc.
                                                               {
  DCHECK_LE(0, reg);
  DCHECK_GT(num_registers_, reg);
  if (by != 0) {
    __ LoadWord(a0, register_location(reg));
    __ AddWord(a0, a0, Operand(by));
    __ StoreWord(a0, register_location(reg));
  }
}
References __, DCHECK_GT, DCHECK_LE, num_registers_, and register_location().
AssertAboveStackLimitMinusSlack()
void v8::internal::RegExpMacroAssemblerRISCV::AssertAboveStackLimitMinusSlack () [private]
Definition at line 1346 of file regexp-macro-assembler-riscv.cc.
                                                                {
  // ExternalReference stack_limit =
  // ExternalReference::address_of_regexp_stack_limit_address(
  // masm_->isolate());
  // __ li(a0, Operand(stack_limit));
  // __ LoadWord(a0, MemOperand(a0, 0));
  // SafeCall(&stack_overflow_label_, ls, backtrack_stackpointer(),
  // Operand(a0));
  DCHECK(v8_flags.slow_debug_code);
  Label no_stack_overflow;
  ASM_CODE_COMMENT_STRING(masm_.get(), "AssertAboveStackLimitMinusSlack");
  auto l = ExternalReference::address_of_regexp_stack_limit_address(isolate());
  __ li(a0, l);
  __ LoadWord(a0, MemOperand(a0, 0));
  __ SubWord(a0, a0, Operand(RegExpStack::kStackLimitSlackSize));
  __ Branch(&no_stack_overflow, Ugreater, backtrack_stackpointer(),
            Operand(a0));
  __ DebugBreak();
  __ bind(&no_stack_overflow);
}
References __, ASM_CODE_COMMENT_STRING, backtrack_stackpointer(), v8::internal::DCHECK(), isolate(), v8::internal::RegExpStack::kStackLimitSlackSize, v8::internal::compiler::turboshaft::l, masm_, v8::internal::Ugreater, and v8::internal::v8_flags.
Referenced by PushRegister().
Backtrack()
void v8::internal::RegExpMacroAssemblerRISCV::Backtrack () [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 148 of file regexp-macro-assembler-riscv.cc.
                                          {
  CheckPreemption();
  if (has_backtrack_limit()) {
    Label next;
    __ LoadWord(a0, MemOperand(frame_pointer(), kBacktrackCountOffset));
    __ AddWord(a0, a0, Operand(1));
    __ StoreWord(a0, MemOperand(frame_pointer(), kBacktrackCountOffset));
    __ BranchShort(&next, ne, a0, Operand(backtrack_limit()));
    // Backtrack limit exceeded.
    if (can_fallback()) {
      __ jmp(&fallback_label_);
    } else {
      // Can't fallback, so we treat it as a failed match.
      Fail();
    }
    __ bind(&next);
  }
  // Pop Code offset from backtrack stack, add Code and jump to location.
  Pop(a0);
  __ AddWord(a0, a0, code_pointer());
  __ Jump(a0);
}
References __, v8::internal::RegExpMacroAssembler::backtrack_limit(), v8::internal::RegExpMacroAssembler::can_fallback(), CheckPreemption(), code_pointer(), Fail(), fallback_label_, frame_pointer(), v8::internal::RegExpMacroAssembler::has_backtrack_limit(), kBacktrackCountOffset, v8::internal::ne, and Pop().
Referenced by BranchOrBacktrack(), GetCode(), and GoTo().
backtrack_stackpointer()
static constexpr Register v8::internal::RegExpMacroAssemblerRISCV::backtrack_stackpointer () [inline], [static], [constexpr], [private]
Definition at line 198 of file regexp-macro-assembler-riscv.h.
{ return s8; }
Referenced by AssertAboveStackLimitMinusSlack(), CheckFixedLengthLoop(), CheckStackLimit(), GetCode(), Pop(), Push(), ReadStackPointerFromRegister(), and WriteStackPointerToRegister().
Bind()
void v8::internal::RegExpMacroAssemblerRISCV::Bind (Label * label) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 173 of file regexp-macro-assembler-riscv.cc.
{ __ bind(label); }
References __.
Referenced by SkipUntilBitInTable().
BranchOrBacktrack()
void v8::internal::RegExpMacroAssemblerRISCV::BranchOrBacktrack (Label * to, Condition condition, Register rs, const Operand & rt) [private]
Definition at line 1277 of file regexp-macro-assembler-riscv.cc.
                                                                     {
  if (condition == al) { // Unconditional.
    if (to == nullptr) {
      Backtrack();
      return;
    }
    __ jmp(to);
    return;
  }
  if (to == nullptr) {
    __ Branch(&backtrack_label_, condition, rs, rt);
    return;
  }
  __ Branch(to, condition, rs, rt);
}
References __, v8::internal::al, Backtrack(), and backtrack_label_.
Referenced by CheckAtStart(), CheckBitInTable(), CheckCharacter(), CheckCharacterAfterAnd(), CheckCharacterGT(), CheckCharacterInRange(), CheckCharacterInRangeArray(), CheckCharacterLT(), CheckCharacterNotInRange(), CheckCharacterNotInRangeArray(), CheckFixedLengthLoop(), CheckNotAtStart(), CheckNotBackReference(), CheckNotBackReferenceIgnoreCase(), CheckNotCharacter(), CheckNotCharacterAfterAnd(), CheckNotCharacterAfterMinusAnd(), CheckPosition(), CheckSpecialClassRanges(), IfRegisterEqPos(), IfRegisterGE(), and IfRegisterLT().
CallCFunctionFromIrregexpCode()
void v8::internal::RegExpMacroAssemblerRISCV::CallCFunctionFromIrregexpCode (ExternalReference function, int num_arguments) [private]
Definition at line 1408 of file regexp-macro-assembler-riscv.cc.
                                                   {
  // Irregexp code must not set fast_c_call_caller_fp and fast_c_call_caller_pc
  // since
  //
  // 1. it may itself have been called using CallCFunction and nested calls are
  // unsupported, and
  // 2. it may itself have been called directly from C where the frame pointer
  // might not be set (-fomit-frame-pointer), and thus frame iteration would
  // fail.
  //
  // See also: crbug.com/v8/12670#c17.
  __ CallCFunction(function, num_arguments, SetIsolateDataSlots::kNo);
}
References __, and kNo.
Referenced by CallIsCharacterInRangeArray(), CheckNotBackReferenceIgnoreCase(), and GetCode().
CallCheckStackGuardState()
void v8::internal::RegExpMacroAssemblerRISCV::CallCheckStackGuardState (Register scratch, Operand extra_space_for_variables = Operand(0)) [private]
Definition at line 1165 of file regexp-macro-assembler-riscv.cc.
                                                                              {
  DCHECK(!isolate()->IsGeneratingEmbeddedBuiltins());
  DCHECK(!masm_->options().isolate_independent_code);
  int stack_alignment = base::OS::ActivationFrameAlignment();
  // Align the stack pointer and save the original sp value on the stack.
  __ mv(scratch, sp);
  __ SubWord(sp, sp, Operand(kSystemPointerSize));
  DCHECK(base::bits::IsPowerOfTwo(stack_alignment));
  __ And(sp, sp, Operand(-stack_alignment));
  __ StoreWord(scratch, MemOperand(sp));
  __ li(a3, extra_space);
  __ mv(a2, frame_pointer());
  // InstructionStream of self.
  __ li(a1, Operand(masm_->CodeObject()), CONSTANT_SIZE);
  // We need to make room for the return address on the stack.
  DCHECK(IsAligned(stack_alignment, kSystemPointerSize));
  __ SubWord(sp, sp, Operand(stack_alignment));
  // The stack pointer now points to cell where the return address will be
  // written. Arguments are in registers, meaning we treat the return address as
  // argument 5. Since DirectCEntry will handle allocating space for the C
  // argument slots, we don't need to care about that here. This is how the
  // stack will look (sp meaning the value of sp at this moment):
  // [sp + 3] - empty slot if needed for alignment.
  // [sp + 2] - saved sp.
  // [sp + 1] - second word reserved for return value.
  // [sp + 0] - first word reserved for return value.
  // a0 will point to the return address, placed by DirectCEntry.
  __ mv(a0, sp);
  ExternalReference stack_guard_check =
      ExternalReference::re_check_stack_guard_state();
  __ li(t6, Operand(stack_guard_check));
  EmbeddedData d = EmbeddedData::FromBlob();
  CHECK(Builtins::IsIsolateIndependent(Builtin::kDirectCEntry));
  Address entry = d.InstructionStartOf(Builtin::kDirectCEntry);
  __ li(kScratchReg, Operand(entry, RelocInfo::OFF_HEAP_TARGET));
  __ Call(kScratchReg);
  // DirectCEntry allocated space for the C argument slots so we have to
  // drop them with the return address from the stack with loading saved sp.
  // At this point stack must look:
  // [sp + 7] - empty slot if needed for alignment.
  // [sp + 6] - saved sp.
  // [sp + 5] - second word reserved for return value.
  // [sp + 4] - first word reserved for return value.
  // [sp + 3] - C argument slot.
  // [sp + 2] - C argument slot.
  // [sp + 1] - C argument slot.
  // [sp + 0] - C argument slot.
  __ LoadWord(sp, MemOperand(sp, stack_alignment + kCArgsSlotsSize));
  __ li(code_pointer(), Operand(masm_->CodeObject()));
}
References __, v8::base::OS::ActivationFrameAlignment(), v8::internal::wasm::liftoff::And(), CHECK, code_pointer(), v8::internal::CONSTANT_SIZE, v8::internal::DCHECK(), frame_pointer(), v8::internal::EmbeddedData::FromBlob(), v8::internal::EmbeddedData::InstructionStartOf(), IsAligned(), v8::internal::Builtins::IsIsolateIndependent(), isolate(), v8::base::bits::IsPowerOfTwo(), v8::internal::kCArgsSlotsSize, v8::internal::kScratchReg, v8::internal::kSystemPointerSize, masm_, and v8::internal::RelocInfo::OFF_HEAP_TARGET.
Referenced by GetCode().
CallIsCharacterInRangeArray()
void v8::internal::RegExpMacroAssemblerRISCV::CallIsCharacterInRangeArray (const ZoneList< CharacterRange > * ranges) [private]
Definition at line 215 of file regexp-macro-assembler-riscv.cc.
                                            {
  static const int kNumArguments = 3;
  __ PrepareCallCFunction(kNumArguments, a0);
  __ mv(a0, current_character());
  __ li(a1, Operand(GetOrAddRangeArray(ranges)));
  __ li(a2, Operand(ExternalReference::isolate_address(isolate())));
  {
    // We have a frame (set up in GetCode), but the assembler doesn't know.
    FrameScope scope(masm_.get(), StackFrame::MANUAL);
    CallCFunctionFromIrregexpCode(
        ExternalReference::re_is_character_in_range_array(), kNumArguments);
  }
  __ li(code_pointer(), Operand(masm_->CodeObject()));
}
References __, CallCFunctionFromIrregexpCode(), code_pointer(), current_character(), v8::internal::NativeRegExpMacroAssembler::GetOrAddRangeArray(), isolate(), v8::internal::ExternalReference::isolate_address(), v8::internal::StackFrame::MANUAL, and masm_.
Referenced by CheckCharacterInRangeArray(), and CheckCharacterNotInRangeArray().
char_size()
int v8::internal::RegExpMacroAssemblerRISCV::char_size () const [inline], [private]
Definition at line 204 of file regexp-macro-assembler-riscv.h.
{ return static_cast<int>(mode_); }
Referenced by AdvanceCurrentPosition(), CheckAtStart(), CheckNotAtStart(), CheckNotBackReference(), CheckNotBackReferenceIgnoreCase(), CheckPosition(), GetCode(), LoadCurrentCharacterUnchecked(), SetCurrentPositionFromEnd(), and WriteCurrentPositionToRegister().
CheckAtStart()
void v8::internal::RegExpMacroAssemblerRISCV::CheckAtStart (int cp_offset, Label * on_at_start) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 184 of file regexp-macro-assembler-riscv.cc.
                                                                 {
  __ LoadWord(a1, MemOperand(frame_pointer(), kStringStartMinusOneOffset));
  __ AddWord(a0, current_input_offset(),
             Operand(-char_size() + cp_offset * char_size()));
  BranchOrBacktrack(on_at_start, eq, a0, Operand(a1));
}
References __, BranchOrBacktrack(), char_size(), current_input_offset(), v8::internal::eq, frame_pointer(), and kStringStartMinusOneOffset.
CheckBitInTable()
void v8::internal::RegExpMacroAssemblerRISCV::CheckBitInTable (Handle< ByteArray > table, Label * on_bit_set) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 487 of file regexp-macro-assembler-riscv.cc.
                                                                   {
  __ li(a0, Operand(table));
  if (mode_ != LATIN1 || kTableMask != String::kMaxOneByteCharCode) {
    __ And(a1, current_character(), Operand(kTableSize - 1));
    __ AddWord(a0, a0, a1);
  } else {
    __ AddWord(a0, a0, current_character());
  }
  __ Lbu(a0, FieldMemOperand(a0, OFFSET_OF_DATA_START(ByteArray)));
  BranchOrBacktrack(on_bit_set, ne, a0, Operand(zero_reg));
}
References __, v8::internal::wasm::liftoff::And(), BranchOrBacktrack(), current_character(), v8::internal::FieldMemOperand(), v8::internal::String::kMaxOneByteCharCode, v8::internal::RegExpMacroAssembler::kTableMask, v8::internal::RegExpMacroAssembler::kTableSize, v8::internal::NativeRegExpMacroAssembler::LATIN1, mode_, v8::internal::ne, and OFFSET_OF_DATA_START.
Referenced by SkipUntilBitInTable().
CheckCharacter()
void v8::internal::RegExpMacroAssemblerRISCV::CheckCharacter (uint32_t c, Label * on_equal) [override]
Definition at line 175 of file regexp-macro-assembler-riscv.cc.
                                                                          {
  BranchOrBacktrack(on_equal, eq, current_character(), Operand(c));
}
References BranchOrBacktrack(), current_character(), and v8::internal::eq.
CheckCharacterAfterAnd()
void v8::internal::RegExpMacroAssemblerRISCV::CheckCharacterAfterAnd (uint32_t c, uint32_t mask, Label * on_equal) [override]
Definition at line 448 of file regexp-macro-assembler-riscv.cc.
                                                                        {
  __ And(a0, current_character(), Operand(mask));
  Operand rhs = (c == 0) ? Operand(zero_reg) : Operand(c);
  BranchOrBacktrack(on_equal, eq, a0, rhs);
}
References __, v8::internal::wasm::liftoff::And(), BranchOrBacktrack(), current_character(), and v8::internal::eq.
CheckCharacterGT()
void v8::internal::RegExpMacroAssemblerRISCV::CheckCharacterGT (base::uc16 limit, Label * on_greater) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 179 of file regexp-macro-assembler-riscv.cc.
                                                                    {
  BranchOrBacktrack(on_greater, gt, current_character(), Operand(limit));
}
References BranchOrBacktrack(), current_character(), and v8::internal::gt.
CheckCharacterInRange()
void v8::internal::RegExpMacroAssemblerRISCV::CheckCharacterInRange (base::uc16 from, base::uc16 to, Label * on_in_range) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 472 of file regexp-macro-assembler-riscv.cc.
                                                                          {
  __ SubWord(a0, current_character(), Operand(from));
  // Unsigned lower-or-same condition.
  BranchOrBacktrack(on_in_range, Uless_equal, a0, Operand(to - from));
}
References __, BranchOrBacktrack(), current_character(), and v8::internal::Uless_equal.
CheckCharacterInRangeArray()
bool v8::internal::RegExpMacroAssemblerRISCV::CheckCharacterInRangeArray (const ZoneList< CharacterRange > * ranges, Label * on_in_range) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 233 of file regexp-macro-assembler-riscv.cc.
                                                                {
  CallIsCharacterInRangeArray(ranges);
  BranchOrBacktrack(on_in_range, ne, a0, Operand(zero_reg));
  return true;
}
References BranchOrBacktrack(), CallIsCharacterInRangeArray(), and v8::internal::ne.
CheckCharacterLT()
void v8::internal::RegExpMacroAssemblerRISCV::CheckCharacterLT (base::uc16 limit, Label * on_less) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 200 of file regexp-macro-assembler-riscv.cc.
                                                                 {
  BranchOrBacktrack(on_less, lt, current_character(), Operand(limit));
}
References BranchOrBacktrack(), current_character(), and v8::internal::lt.
CheckCharacterNotInRange()
void v8::internal::RegExpMacroAssemblerRISCV::CheckCharacterNotInRange (base::uc16 from, base::uc16 to, Label * on_not_in_range) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 480 of file regexp-macro-assembler-riscv.cc.
                                                        {
  __ SubWord(a0, current_character(), Operand(from));
  // Unsigned higher condition.
  BranchOrBacktrack(on_not_in_range, Ugreater, a0, Operand(to - from));
}
References __, BranchOrBacktrack(), current_character(), and v8::internal::Ugreater.
CheckCharacterNotInRangeArray()
bool v8::internal::RegExpMacroAssemblerRISCV::CheckCharacterNotInRangeArray (const ZoneList< CharacterRange > * ranges, Label * on_not_in_range) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 240 of file regexp-macro-assembler-riscv.cc.
                                                                    {
  CallIsCharacterInRangeArray(ranges);
  BranchOrBacktrack(on_not_in_range, eq, a0, Operand(zero_reg));
  return true;
}
References BranchOrBacktrack(), CallIsCharacterInRangeArray(), and v8::internal::eq.
CheckFixedLengthLoop()
void v8::internal::RegExpMacroAssemblerRISCV::CheckFixedLengthLoop (Label * on_tos_equals_current_position) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 205 of file regexp-macro-assembler-riscv.cc.
                                                                    {
  Label backtrack_non_equal;
  __ Lw(a0, MemOperand(backtrack_stackpointer(), 0));
  __ BranchShort(&backtrack_non_equal, ne, current_input_offset(), Operand(a0));
  __ AddWord(backtrack_stackpointer(), backtrack_stackpointer(),
             Operand(kIntSize));
  __ bind(&backtrack_non_equal);
  BranchOrBacktrack(on_equal, eq, current_input_offset(), Operand(a0));
}
References __, backtrack_stackpointer(), BranchOrBacktrack(), current_input_offset(), v8::internal::eq, v8::internal::kIntSize, and v8::internal::ne.
CheckNotAtStart()
void v8::internal::RegExpMacroAssemblerRISCV::CheckNotAtStart (int cp_offset, Label * on_not_at_start) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 192 of file regexp-macro-assembler-riscv.cc.
                                                                        {
  __ LoadWord(a1, MemOperand(frame_pointer(), kStringStartMinusOneOffset));
  __ AddWord(a0, current_input_offset(),
             Operand(-char_size() + cp_offset * char_size()));
  BranchOrBacktrack(on_not_at_start, ne, a0, Operand(a1));
}
References __, BranchOrBacktrack(), char_size(), current_input_offset(), frame_pointer(), kStringStartMinusOneOffset, and v8::internal::ne.
CheckNotBackReference()
void v8::internal::RegExpMacroAssemblerRISCV::CheckNotBackReference (int start_reg, bool read_backward, Label * on_no_match) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 380 of file regexp-macro-assembler-riscv.cc.
                                                                          {
  Label fallthrough;
  // Find length of back-referenced capture.
  __ LoadWord(a0, register_location(start_reg));
  __ LoadWord(a1, register_location(start_reg + 1));
  __ SubWord(a1, a1, a0); // Length to check.
  // At this point, the capture registers are either both set or both cleared.
  // If the capture length is zero, then the capture is either empty or cleared.
  // Fall through in both cases.
  __ BranchShort(&fallthrough, eq, a1, Operand(zero_reg));
  if (read_backward) {
    __ LoadWord(t1, MemOperand(frame_pointer(), kStringStartMinusOneOffset));
    __ AddWord(t1, t1, a1);
    BranchOrBacktrack(on_no_match, le, current_input_offset(), Operand(t1));
  } else {
    __ AddWord(t1, a1, current_input_offset());
    // Check that there are enough characters left in the input.
    BranchOrBacktrack(on_no_match, gt, t1, Operand(zero_reg));
  }
  // Compute pointers to match string and capture string.
  __ AddWord(a0, a0, Operand(end_of_input_address()));
  __ AddWord(a2, end_of_input_address(), Operand(current_input_offset()));
  if (read_backward) {
    __ SubWord(a2, a2, Operand(a1));
  }
  __ AddWord(a1, a1, Operand(a0));
  Label loop;
  __ bind(&loop);
  if (mode_ == LATIN1) {
    __ Lbu(a3, MemOperand(a0, 0));
    __ addi(a0, a0, char_size());
    __ Lbu(a4, MemOperand(a2, 0));
    __ addi(a2, a2, char_size());
  } else {
    DCHECK(mode_ == UC16);
    __ Lhu(a3, MemOperand(a0, 0));
    __ addi(a0, a0, char_size());
    __ Lhu(a4, MemOperand(a2, 0));
    __ addi(a2, a2, char_size());
  }
  BranchOrBacktrack(on_no_match, ne, a3, Operand(a4));
  __ Branch(&loop, lt, a0, Operand(a1));
  // Move current character position to position after match.
  __ SubWord(current_input_offset(), a2, end_of_input_address());
  if (read_backward) {
    __ LoadWord(t1,
                register_location(start_reg)); // Index of start of capture.
    __ LoadWord(a2,
                register_location(start_reg + 1)); // Index of end of capture.
    __ AddWord(current_input_offset(), current_input_offset(), Operand(t1));
    __ SubWord(current_input_offset(), current_input_offset(), Operand(a2));
  }
  __ bind(&fallthrough);
}
References __, BranchOrBacktrack(), char_size(), current_input_offset(), v8::internal::DCHECK(), end_of_input_address(), v8::internal::eq, frame_pointer(), v8::internal::gt, kStringStartMinusOneOffset, v8::internal::NativeRegExpMacroAssembler::LATIN1, v8::internal::le, v8::internal::lt, mode_, v8::internal::ne, register_location(), and v8::internal::NativeRegExpMacroAssembler::UC16.
CheckNotBackReferenceIgnoreCase()
void v8::internal::RegExpMacroAssemblerRISCV::CheckNotBackReferenceIgnoreCase (int start_reg, bool read_backward, bool unicode, Label * on_no_match) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 247 of file regexp-macro-assembler-riscv.cc.
                                                                         {
  Label fallthrough;
  __ LoadWord(a0, register_location(start_reg)); // Index of start of capture.
  __ LoadWord(a1,
              register_location(start_reg + 1)); // Index of end of capture.
  __ SubWord(a1, a1, a0); // Length of capture.
  // At this point, the capture registers are either both set or both cleared.
  // If the capture length is zero, then the capture is either empty or cleared.
  // Fall through in both cases.
  __ BranchShort(&fallthrough, eq, a1, Operand(zero_reg));
  if (read_backward) {
    __ LoadWord(t1, MemOperand(frame_pointer(), kStringStartMinusOneOffset));
    __ AddWord(t1, t1, a1);
    BranchOrBacktrack(on_no_match, le, current_input_offset(), Operand(t1));
  } else {
    __ AddWord(t1, a1, current_input_offset());
    // Check that there are enough characters left in the input.
    BranchOrBacktrack(on_no_match, gt, t1, Operand(zero_reg));
  }
  if (mode_ == LATIN1) {
    Label success;
    Label fail;
    Label loop_check;
    // a0 - offset of start of capture.
    // a1 - length of capture.
    __ AddWord(a0, a0, Operand(end_of_input_address()));
    __ AddWord(a2, end_of_input_address(), Operand(current_input_offset()));
    if (read_backward) {
      __ SubWord(a2, a2, Operand(a1));
    }
    __ AddWord(a1, a0, Operand(a1));
    // a0 - Address of start of capture.
    // a1 - Address of end of capture.
    // a2 - Address of current input position.
    Label loop;
    __ bind(&loop);
    __ Lbu(a3, MemOperand(a0, 0));
    __ addi(a0, a0, char_size());
    __ Lbu(a4, MemOperand(a2, 0));
    __ addi(a2, a2, char_size());
    __ BranchShort(&loop_check, eq, a4, Operand(a3));
    // Mismatch, try case-insensitive match (converting letters to lower-case).
    __ Or(a3, a3, Operand(0x20)); // Convert capture character to lower-case.
    __ Or(a4, a4, Operand(0x20)); // Also convert input character.
    __ BranchShort(&fail, ne, a4, Operand(a3));
    __ SubWord(a3, a3, Operand('a'));
    __ BranchShort(&loop_check, Uless_equal, a3, Operand('z' - 'a'));
    // Latin-1: Check for values in range [224,254] but not 247.
    __ SubWord(a3, a3, Operand(224 - 'a'));
    // Weren't Latin-1 letters.
    __ BranchShort(&fail, Ugreater, a3, Operand(254 - 224));
    // Check for 247.
    __ BranchShort(&fail, eq, a3, Operand(247 - 224));
    __ bind(&loop_check);
    __ Branch(&loop, lt, a0, Operand(a1));
    __ jmp(&success);
    __ bind(&fail);
    GoTo(on_no_match);
    __ bind(&success);
    // Compute new value of character position after the matched part.
    __ SubWord(current_input_offset(), a2, end_of_input_address());
    if (read_backward) {
      __ LoadWord(t1,
                  register_location(start_reg)); // Index of start of capture.
      __ LoadWord(
          a2, register_location(start_reg + 1)); // Index of end of capture.
      __ AddWord(current_input_offset(), current_input_offset(), Operand(t1));
      __ SubWord(current_input_offset(), current_input_offset(), Operand(a2));
    }
  } else {
    DCHECK(mode_ == UC16);
    int argument_count = 4;
    __ PrepareCallCFunction(argument_count, a2);
    // a0 - offset of start of capture.
    // a1 - length of capture.
    // Put arguments into arguments registers.
    // Parameters are
    // a0: Address byte_offset1 - Address captured substring's start.
    // a1: Address byte_offset2 - Address of current character position.
    // a2: size_t byte_length - length of capture in bytes(!).
    // a3: Isolate* isolate.
    // Address of start of capture.
    __ AddWord(a0, a0, Operand(end_of_input_address()));
    // Length of capture.
    __ mv(a2, a1);
    // Save length in callee-save register for use on return.
    __ mv(s3, a1);
    // Address of current input position.
    __ AddWord(a1, current_input_offset(), Operand(end_of_input_address()));
    if (read_backward) {
      __ SubWord(a1, a1, Operand(s3));
    }
    // Isolate.
    __ li(a3, Operand(ExternalReference::isolate_address(masm_->isolate())));
    {
      AllowExternalCallThatCantCauseGC scope(masm_.get());
      ExternalReference function =
          unicode
              ? ExternalReference::re_case_insensitive_compare_unicode()
              : ExternalReference::re_case_insensitive_compare_non_unicode();
      CallCFunctionFromIrregexpCode(function, argument_count);
    }
    // Check if function returned non-zero for success or zero for failure.
    BranchOrBacktrack(on_no_match, eq, a0, Operand(zero_reg));
    // On success, increment position by length of capture.
    if (read_backward) {
      __ SubWord(current_input_offset(), current_input_offset(), Operand(s3));
    } else {
      __ AddWord(current_input_offset(), current_input_offset(), Operand(s3));
    }
  }
  __ bind(&fallthrough);
}
References __, BranchOrBacktrack(), CallCFunctionFromIrregexpCode(), char_size(), current_input_offset(), v8::internal::DCHECK(), end_of_input_address(), v8::internal::eq, frame_pointer(), GoTo(), v8::internal::gt, v8::internal::ExternalReference::isolate_address(), kStringStartMinusOneOffset, v8::internal::NativeRegExpMacroAssembler::LATIN1, v8::internal::le, v8::internal::lt, masm_, mode_, v8::internal::ne, v8::internal::wasm::liftoff::Or(), register_location(), v8::internal::NativeRegExpMacroAssembler::UC16, v8::internal::Ugreater, and v8::internal::Uless_equal.
CheckNotCharacter()
void v8::internal::RegExpMacroAssemblerRISCV::CheckNotCharacter (uint32_t c, Label * on_not_equal) [override]
Definition at line 443 of file regexp-macro-assembler-riscv.cc.
                                                                       {
  BranchOrBacktrack(on_not_equal, ne, current_character(), Operand(c));
}
References BranchOrBacktrack(), current_character(), and v8::internal::ne.
CheckNotCharacterAfterAnd()
void v8::internal::RegExpMacroAssemblerRISCV::CheckNotCharacterAfterAnd (uint32_t c, uint32_t mask, Label * on_not_equal) [override]
Definition at line 456 of file regexp-macro-assembler-riscv.cc.
                                                                               {
  __ And(a0, current_character(), Operand(mask));
  Operand rhs = (c == 0) ? Operand(zero_reg) : Operand(c);
  BranchOrBacktrack(on_not_equal, ne, a0, rhs);
}
References __, v8::internal::wasm::liftoff::And(), BranchOrBacktrack(), current_character(), and v8::internal::ne.
CheckNotCharacterAfterMinusAnd()
void v8::internal::RegExpMacroAssemblerRISCV::CheckNotCharacterAfterMinusAnd (base::uc16 c, base::uc16 minus, base::uc16 mask, Label * on_not_equal) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 464 of file regexp-macro-assembler-riscv.cc.
                                                                    {
  DCHECK_GT(String::kMaxUtf16CodeUnit, minus);
  __ SubWord(a0, current_character(), Operand(minus));
  __ And(a0, a0, Operand(mask));
  BranchOrBacktrack(on_not_equal, ne, a0, Operand(c));
}
References __, v8::internal::wasm::liftoff::And(), BranchOrBacktrack(), current_character(), DCHECK_GT, v8::internal::String::kMaxUtf16CodeUnit, and v8::internal::ne.
CheckPosition()
void v8::internal::RegExpMacroAssemblerRISCV::CheckPosition (int cp_offset, Label * on_outside_input) [override], [virtual]
Reimplemented from v8::internal::RegExpMacroAssembler.
Definition at line 1265 of file regexp-macro-assembler-riscv.cc.
                                                                       {
  if (cp_offset >= 0) {
    BranchOrBacktrack(on_outside_input, ge, current_input_offset(),
                      Operand(-cp_offset * char_size()));
  } else {
    __ LoadWord(a1, MemOperand(frame_pointer(), kStringStartMinusOneOffset));
    __ AddWord(a0, current_input_offset(), Operand(cp_offset * char_size()));
    BranchOrBacktrack(on_outside_input, le, a0, Operand(a1));
  }
}
References __, BranchOrBacktrack(), char_size(), current_input_offset(), frame_pointer(), v8::internal::ge, kStringStartMinusOneOffset, and v8::internal::le.
CheckPreemption()
void v8::internal::RegExpMacroAssemblerRISCV::CheckPreemption () [private]
Definition at line 1326 of file regexp-macro-assembler-riscv.cc.
                                                {
  // Check for preemption.
  ExternalReference stack_limit =
      ExternalReference::address_of_jslimit(masm_->isolate());
  __ li(a0, Operand(stack_limit));
  __ LoadWord(a0, MemOperand(a0));
  SafeCall(&check_preempt_label_, Uless_equal, sp, Operand(a0));
}
References __, check_preempt_label_, masm_, SafeCall(), and v8::internal::Uless_equal.
Referenced by Backtrack().
CheckSpecialClassRanges()
bool v8::internal::RegExpMacroAssemblerRISCV::CheckSpecialClassRanges (StandardCharacterSet type, Label * on_no_match) [override], [virtual]
Reimplemented from v8::internal::RegExpMacroAssembler.
Definition at line 514 of file regexp-macro-assembler-riscv.cc.
                                                   {
  // Range checks (c in min..max) are generally implemented by an unsigned
  // (c - min) <= (max - min) check.
  switch (type) {
    case StandardCharacterSet::kWhitespace:
      // Match space-characters.
      if (mode_ == LATIN1) {
        // One byte space characters are '\t'..'\r', ' ' and \u00a0.
        Label success;
        __ BranchShort(&success, eq, current_character(), Operand(' '));
        // Check range 0x09..0x0D.
        __ SubWord(a0, current_character(), Operand('\t'));
        __ BranchShort(&success, Uless_equal, a0, Operand('\r' - '\t'));
        // \u00a0 (NBSP).
        BranchOrBacktrack(on_no_match, ne, a0, Operand(0x00A0 - '\t'));
        __ bind(&success);
        return true;
      }
      return false;
    case StandardCharacterSet::kNotWhitespace:
      // The emitted code for generic character classes is good enough.
      return false;
    case StandardCharacterSet::kDigit:
      // Match Latin1 digits ('0'..'9').
      __ SubWord(a0, current_character(), Operand('0'));
      BranchOrBacktrack(on_no_match, Ugreater, a0, Operand('9' - '0'));
      return true;
    case StandardCharacterSet::kNotDigit:
      // Match non Latin1-digits.
      __ SubWord(a0, current_character(), Operand('0'));
      BranchOrBacktrack(on_no_match, Uless_equal, a0, Operand('9' - '0'));
      return true;
    case StandardCharacterSet::kNotLineTerminator: {
      // Match non-newlines (not 0x0A('\n'), 0x0D('\r'), 0x2028 and 0x2029).
      __ Xor(a0, current_character(), Operand(0x01));
      // See if current character is '\n'^1 or '\r'^1, i.e., 0x0B or 0x0C.
      __ SubWord(a0, a0, Operand(0x0B));
      BranchOrBacktrack(on_no_match, Uless_equal, a0, Operand(0x0C - 0x0B));
      if (mode_ == UC16) {
        // Compare original value to 0x2028 and 0x2029, using the already
        // computed (current_char ^ 0x01 - 0x0B). I.e., check for
        // 0x201D (0x2028 - 0x0B) or 0x201E.
        __ SubWord(a0, a0, Operand(0x2028 - 0x0B));
        BranchOrBacktrack(on_no_match, Uless_equal, a0, Operand(1));
      }
      return true;
    }
    case StandardCharacterSet::kLineTerminator: {
      // Match newlines (0x0A('\n'), 0x0D('\r'), 0x2028 and 0x2029).
      __ Xor(a0, current_character(), Operand(0x01));
      // See if current character is '\n'^1 or '\r'^1, i.e., 0x0B or 0x0C.
      __ SubWord(a0, a0, Operand(0x0B));
      if (mode_ == LATIN1) {
        BranchOrBacktrack(on_no_match, Ugreater, a0, Operand(0x0C - 0x0B));
      } else {
        Label done;
        BranchOrBacktrack(&done, Uless_equal, a0, Operand(0x0C - 0x0B));
        // Compare original value to 0x2028 and 0x2029, using the already
        // computed (current_char ^ 0x01 - 0x0B). I.e., check for
        // 0x201D (0x2028 - 0x0B) or 0x201E.
        __ SubWord(a0, a0, Operand(0x2028 - 0x0B));
        BranchOrBacktrack(on_no_match, Ugreater, a0, Operand(1));
        __ bind(&done);
      }
      return true;
    }
    case StandardCharacterSet::kWord: {
      if (mode_ != LATIN1) {
        // Table is 256 entries, so all Latin1 characters can be tested.
        BranchOrBacktrack(on_no_match, Ugreater, current_character(),
                          Operand('z'));
      }
      ExternalReference map = ExternalReference::re_word_character_map();
      __ li(a0, Operand(map));
      __ AddWord(a0, a0, current_character());
      __ Lbu(a0, MemOperand(a0, 0));
      BranchOrBacktrack(on_no_match, eq, a0, Operand(zero_reg));
      return true;
    }
    case StandardCharacterSet::kNotWord: {
      Label done;
      if (mode_ != LATIN1) {
        // Table is 256 entries, so all Latin1 characters can be tested.
        __ BranchShort(&done, Ugreater, current_character(), Operand('z'));
      }
      ExternalReference map = ExternalReference::re_word_character_map();
      __ li(a0, Operand(map));
      __ AddWord(a0, a0, current_character());
      __ Lbu(a0, MemOperand(a0, 0));
      BranchOrBacktrack(on_no_match, ne, a0, Operand(zero_reg));
      if (mode_ != LATIN1) {
        __ bind(&done);
      }
      return true;
    }
    case StandardCharacterSet::kEverything:
      // Match any character.
      return true;
    // No custom implementation (yet): s(UC16), S(UC16).
    default:
      return false;
  }
}
References __, BranchOrBacktrack(), current_character(), v8::internal::eq, v8::internal::kDigit, v8::internal::kEverything, v8::internal::kLineTerminator, v8::internal::kNotDigit, v8::internal::kNotLineTerminator, v8::internal::kNotWhitespace, v8::internal::kNotWord, v8::internal::kWhitespace, v8::internal::kWord, v8::internal::NativeRegExpMacroAssembler::LATIN1, mode_, v8::internal::ne, v8::internal::tracing::type, v8::internal::NativeRegExpMacroAssembler::UC16, v8::internal::Ugreater, v8::internal::Uless_equal, and v8::internal::wasm::liftoff::Xor().
CheckStackGuardState()
int64_t v8::internal::RegExpMacroAssemblerRISCV::CheckStackGuardState (Address * return_address, Address raw_code, Address re_frame, uintptr_t extra_space) [static]
Definition at line 1238 of file regexp-macro-assembler-riscv.cc.
                                                                               {
  Tagged<InstructionStream> re_code =
      Cast<InstructionStream>(Tagged<Object>(raw_code));
  return NativeRegExpMacroAssembler::CheckStackGuardState(
      frame_entry<Isolate*>(re_frame, kIsolateOffset),
      static_cast<int>(frame_entry<int64_t>(re_frame, kStartIndexOffset)),
      static_cast<RegExp::CallOrigin>(
          frame_entry<int64_t>(re_frame, kDirectCallOffset)),
      return_address, re_code,
      frame_entry_address<Address>(re_frame, kInputStringOffset),
      frame_entry_address<const uint8_t*>(re_frame, kInputStartOffset),
      frame_entry_address<const uint8_t*>(re_frame, kInputEndOffset),
      extra_space);
}
References v8::internal::NativeRegExpMacroAssembler::CheckStackGuardState(), kDirectCallOffset, kInputEndOffset, kInputStartOffset, kInputStringOffset, kIsolateOffset, and kStartIndexOffset.
CheckStackLimit()
void v8::internal::RegExpMacroAssemblerRISCV::CheckStackLimit () [private]
Definition at line 1335 of file regexp-macro-assembler-riscv.cc.
                                                {
  ExternalReference stack_limit =
      ExternalReference::address_of_regexp_stack_limit_address(
          masm_->isolate());
  __ li(a0, Operand(stack_limit));
  __ LoadWord(a0, MemOperand(a0));
  SafeCall(&stack_overflow_label_, Uless_equal, backtrack_stackpointer(),
           Operand(a0));
}
References __, backtrack_stackpointer(), masm_, SafeCall(), stack_overflow_label_, and v8::internal::Uless_equal.
Referenced by PushBacktrack(), PushCurrentPosition(), and PushRegister().
ClearRegisters()
void v8::internal::RegExpMacroAssemblerRISCV::ClearRegisters (int reg_from, int reg_to) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 1153 of file regexp-macro-assembler-riscv.cc.
                                                                       {
  DCHECK(reg_from <= reg_to);
  __ LoadWord(a0, MemOperand(frame_pointer(), kStringStartMinusOneOffset));
  for (int reg = reg_from; reg <= reg_to; reg++) {
    __ StoreWord(a0, register_location(reg));
  }
}
References __, v8::internal::DCHECK(), frame_pointer(), kStringStartMinusOneOffset, and register_location().
code_pointer()
static constexpr Register v8::internal::RegExpMacroAssemblerRISCV::code_pointer () [inline], [static], [constexpr], [private]
Definition at line 201 of file regexp-macro-assembler-riscv.h.
{ return s1; }
Referenced by Backtrack(), CallCheckStackGuardState(), CallIsCharacterInRangeArray(), GetCode(), and PushBacktrack().
current_character()
static constexpr Register v8::internal::RegExpMacroAssemblerRISCV::current_character () [inline], [static], [constexpr], [private]
Definition at line 185 of file regexp-macro-assembler-riscv.h.
{ return s5; }
Referenced by CallIsCharacterInRangeArray(), CheckBitInTable(), CheckCharacter(), CheckCharacterAfterAnd(), CheckCharacterGT(), CheckCharacterInRange(), CheckCharacterLT(), CheckCharacterNotInRange(), CheckNotCharacter(), CheckNotCharacterAfterAnd(), CheckNotCharacterAfterMinusAnd(), CheckSpecialClassRanges(), GetCode(), and LoadCurrentCharacterUnchecked().
current_input_offset()
static constexpr Register v8::internal::RegExpMacroAssemblerRISCV::current_input_offset () [inline], [static], [constexpr], [private]
Definition at line 182 of file regexp-macro-assembler-riscv.h.
{ return s2; }
Referenced by AdvanceCurrentPosition(), CheckAtStart(), CheckFixedLengthLoop(), CheckNotAtStart(), CheckNotBackReference(), CheckNotBackReferenceIgnoreCase(), CheckPosition(), GetCode(), IfRegisterEqPos(), LoadCurrentCharacterUnchecked(), PopCurrentPosition(), PushCurrentPosition(), ReadCurrentPositionFromRegister(), SetCurrentPositionFromEnd(), and WriteCurrentPositionToRegister().
end_of_input_address()
static constexpr Register v8::internal::RegExpMacroAssemblerRISCV::end_of_input_address () [inline], [static], [constexpr], [private]
Definition at line 188 of file regexp-macro-assembler-riscv.h.
{ return s6; }
Referenced by CheckNotBackReference(), CheckNotBackReferenceIgnoreCase(), GetCode(), and LoadCurrentCharacterUnchecked().
Fail()
void v8::internal::RegExpMacroAssemblerRISCV::Fail () [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 619 of file regexp-macro-assembler-riscv.cc.
                                     {
  __ li(a0, Operand(FAILURE));
  __ jmp(&exit_label_);
}
References __, exit_label_, and v8::internal::NativeRegExpMacroAssembler::FAILURE.
Referenced by Backtrack().
frame_pointer()
static constexpr Register v8::internal::RegExpMacroAssemblerRISCV::frame_pointer () [inline], [static], [constexpr], [private]
Definition at line 192 of file regexp-macro-assembler-riscv.h.
{ return fp; }
Referenced by Backtrack(), CallCheckStackGuardState(), CheckAtStart(), CheckNotAtStart(), CheckNotBackReference(), CheckNotBackReferenceIgnoreCase(), CheckPosition(), ClearRegisters(), GetCode(), PopRegExpBasePointer(), PushRegExpBasePointer(), and register_location().
GetCode()
DirectHandle< HeapObject > v8::internal::RegExpMacroAssemblerRISCV::GetCode (DirectHandle< String > source, RegExpFlags flags) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 662 of file regexp-macro-assembler-riscv.cc.
                                                    {
  Label return_a0;
  if (masm_->has_exception()) {
    // If the code gets corrupted due to long regular expressions and lack of
    // space on trampolines, an internal exception flag is set. If this case
    // is detected, we will jump into exit sequence right away.
    __ bind_to(&entry_label_, internal_failure_label_.pos());
  } else {
    // Finalize code - write the entry point code now we know how many
    // registers we need.
    // Entry code:
    __ bind(&entry_label_);
    // Tell the system that we have a stack frame. Because the type is MANUAL,
    // no is generated.
    FrameScope scope(masm_.get(), StackFrame::MANUAL);
    // Actually emit code to start a new stack frame.
    // Push arguments
    // Save callee-save registers.
    // Start new stack frame.
    // Store link register in existing stack-cell.
    // Order here should correspond to order of offset constants in header file.
    // TODO(plind): we save fp..s11, but ONLY use s3 here - use the regs
    // or dont save.
    RegList registers_to_retain = {fp, s1, s2, s3, s4, s5,
                                   s6, s7, s8, s9, s10, s11};
    DCHECK(registers_to_retain.Count() == kNumCalleeRegsToRetain);
    // The remaining arguments are passed in registers, e.g.by calling the code
    // entry as cast to a function with the signature:
    //
    // *int(*match)(String input_string, // a0
    // int start_offset, // a1
    // uint8_t* input_start, // a2
    // uint8_t* input_end, // a3
    // int* output, // a4
    // int output_size, // a5
    // int call_origin, // a6
    // Isolate* isolate, // a7
    // Address regexp); // on the stack
    RegList argument_registers = {a0, a1, a2, a3, a4, a5, a6, a7};
    // According to MultiPush implementation, registers will be pushed in the
    // order of ra, fp, then s8, ..., s1, and finally a7,...a0
    __ MultiPush(RegList{ra} | registers_to_retain);
    // Set frame pointer in space for it if this is not a direct call
    // from generated code.
    __ AddWord(frame_pointer(), sp, Operand(0));
    static_assert(kFrameTypeOffset == -kSystemPointerSize);
    __ li(kScratchReg, Operand(StackFrame::TypeToMarker(StackFrame::IRREGEXP)));
    __ push(kScratchReg);
    __ MultiPush(argument_registers);
    static_assert(kSuccessfulCapturesOffset ==
                  kInputStringOffset - kSystemPointerSize);
    __ mv(a0, zero_reg);
    __ push(a0); // Make room for success counter and initialize it to 0.
    static_assert(kStringStartMinusOneOffset ==
                  kSuccessfulCapturesOffset - kSystemPointerSize);
    __ push(a0); // Make room for "string start - 1" constant.
    static_assert(kBacktrackCountOffset ==
                  kStringStartMinusOneOffset - kSystemPointerSize);
    __ push(a0); // The backtrack counter
    static_assert(kRegExpStackBasePointerOffset ==
                  kBacktrackCountOffset - kSystemPointerSize);
    __ push(a0); // The regexp stack base ptr.
    // Initialize backtrack stack pointer. It must not be clobbered from here
    // on. Note the backtrack_stackpointer is callee-saved.
    static_assert(backtrack_stackpointer() == s8);
    LoadRegExpStackPointerFromMemory(backtrack_stackpointer());
    // Store the regexp base pointer - we'll later restore it / write it to
    // memory when returning from this irregexp code object.
    PushRegExpBasePointer(backtrack_stackpointer(), a1);
    {
      // Check if we have space on the stack for registers.
      Label stack_limit_hit, stack_ok;
      ExternalReference stack_limit =
          ExternalReference::address_of_jslimit(masm_->isolate());
      __ li(a0, Operand(stack_limit));
      __ LoadWord(a0, MemOperand(a0));
      __ SubWord(a0, sp, a0);
      Operand extra_space_for_variables(num_registers_ * kSystemPointerSize);
      // Handle it if the stack pointer is already below the stack limit.
      __ Branch(&stack_limit_hit, le, a0, Operand(zero_reg));
      // Check if there is room for the variable number of registers above
      // the stack limit.
      __ Branch(&stack_ok, uge, a0, extra_space_for_variables);
      // Exit with OutOfMemory exception. There is not enough space on the stack
      // for our working registers.
      __ li(a0, Operand(EXCEPTION));
      __ jmp(&return_a0);
      __ bind(&stack_limit_hit);
      CallCheckStackGuardState(a0, extra_space_for_variables);
      // If returned value is non-zero, we exit with the returned value as
      // result.
      __ Branch(&return_a0, ne, a0, Operand(zero_reg));
      __ bind(&stack_ok);
    }
    // Allocate space on stack for registers.
    __ SubWord(sp, sp, Operand(num_registers_ * kSystemPointerSize));
    // Load string end.
    __ LoadWord(end_of_input_address(),
                MemOperand(frame_pointer(), kInputEndOffset));
    // Load input start.
    __ LoadWord(a0, MemOperand(frame_pointer(), kInputStartOffset));
    // Find negative length (offset of start relative to end).
    __ SubWord(current_input_offset(), a0, end_of_input_address());
    // Set a0 to address of char before start of the input string
    // (effectively string position -1).
    __ LoadWord(a1, MemOperand(frame_pointer(), kStartIndexOffset));
    __ SubWord(a0, current_input_offset(), Operand(char_size()));
    __ slli(t1, a1, (mode_ == UC16) ? 1 : 0);
    __ SubWord(a0, a0, t1);
    // Store this value in a local variable, for use when clearing
    // position registers.
    __ StoreWord(a0, MemOperand(frame_pointer(), kStringStartMinusOneOffset));
    // Initialize code pointer register
    __ li(code_pointer(), Operand(masm_->CodeObject()), CONSTANT_SIZE);
    Label load_char_start_regexp;
    {
      Label start_regexp;
      // Load newline if index is at start, previous character otherwise.
      __ Branch(&load_char_start_regexp, ne, a1, Operand(zero_reg));
      __ li(current_character(), Operand('\n'));
      __ jmp(&start_regexp);
      // Global regexp restarts matching here.
      __ bind(&load_char_start_regexp);
      // Load previous char as initial value of current character register.
      LoadCurrentCharacterUnchecked(-1, 1);
      __ bind(&start_regexp);
    }
    // Initialize on-stack registers.
    if (num_saved_registers_ > 0) { // Always is, if generated from a regexp.
      // Fill saved registers with initial value = start offset - 1.
      if (num_saved_registers_ > 8) {
        // Address of register 0.
        __ AddWord(a1, frame_pointer(), Operand(kRegisterZeroOffset));
        __ li(a2, Operand(num_saved_registers_));
        Label init_loop;
        __ bind(&init_loop);
        __ StoreWord(a0, MemOperand(a1));
        __ AddWord(a1, a1, Operand(-kSystemPointerSize));
        __ SubWord(a2, a2, Operand(1));
        __ Branch(&init_loop, ne, a2, Operand(zero_reg));
      } else {
        for (int i = 0; i < num_saved_registers_; i++) {
          __ StoreWord(a0, register_location(i));
        }
      }
    }
    __ jmp(&start_label_);
    // Exit code:
    if (success_label_.is_linked()) {
      // Save captures when successful.
      __ bind(&success_label_);
      if (num_saved_registers_ > 0) {
        // Copy captures to output.
        __ LoadWord(a1, MemOperand(frame_pointer(), kInputStartOffset));
        __ LoadWord(a0, MemOperand(frame_pointer(), kRegisterOutputOffset));
        __ LoadWord(a2, MemOperand(frame_pointer(), kStartIndexOffset));
        __ SubWord(a1, end_of_input_address(), a1);
        // a1 is length of input in bytes.
        if (mode_ == UC16) {
          __ srli(a1, a1, 1);
        }
        // a1 is length of input in characters.
        __ AddWord(a1, a1, Operand(a2));
        // a1 is length of string in characters.
        DCHECK_EQ(0, num_saved_registers_ % 2);
        // Always an even number of capture registers. This allows us to
        // unroll the loop once to add an operation between a load of a
        // register and the following use of that register.
        for (int i = 0; i < num_saved_registers_; i += 2) {
          __ LoadWord(a2, register_location(i));
          __ LoadWord(a3, register_location(i + 1));
          if (i == 0 && global_with_zero_length_check()) {
            // Keep capture start in a4 for the zero-length check later.
            __ mv(s3, a2);
          }
          if (mode_ == UC16) {
            __ srai(a2, a2, 1);
            __ AddWord(a2, a2, a1);
            __ srai(a3, a3, 1);
            __ AddWord(a3, a3, a1);
          } else {
            __ AddWord(a2, a1, Operand(a2));
            __ AddWord(a3, a1, Operand(a3));
          }
          // V8 expects the output to be an int32_t array.
          __ Sw(a2, MemOperand(a0));
          __ AddWord(a0, a0, kIntSize);
          __ Sw(a3, MemOperand(a0));
          __ AddWord(a0, a0, kIntSize);
        }
      }
      if (global()) {
        // Restart matching if the regular expression is flagged as global.
        __ LoadWord(a0, MemOperand(frame_pointer(), kSuccessfulCapturesOffset));
        __ LoadWord(a1, MemOperand(frame_pointer(), kNumOutputRegistersOffset));
        __ LoadWord(a2, MemOperand(frame_pointer(), kRegisterOutputOffset));
        // Increment success counter.
        __ AddWord(a0, a0, 1);
        __ StoreWord(a0,
                     MemOperand(frame_pointer(), kSuccessfulCapturesOffset));
        // Capture results have been stored, so the number of remaining global
        // output registers is reduced by the number of stored captures.
        __ SubWord(a1, a1, num_saved_registers_);
        // Check whether we have enough room for another set of capture results.
        __ Branch(&return_a0, lt, a1, Operand(num_saved_registers_));
        __ StoreWord(a1,
                     MemOperand(frame_pointer(), kNumOutputRegistersOffset));
        // Advance the location for output.
        __ AddWord(a2, a2, num_saved_registers_ * kIntSize);
        __ StoreWord(a2, MemOperand(frame_pointer(), kRegisterOutputOffset));
        // Restore the original regexp stack pointer value (effectively, pop the
        // stored base pointer).
        PopRegExpBasePointer(backtrack_stackpointer(), a2);
        Label reload_string_start_minus_one;
        if (global_with_zero_length_check()) {
          // Special case for zero-length matches.
          // s3: capture start index
          // Not a zero-length match, restart.
          __ Branch(&reload_string_start_minus_one, ne, current_input_offset(),
                    Operand(s3));
          // Offset from the end is zero if we already reached the end.
          __ Branch(&exit_label_, eq, current_input_offset(),
                    Operand(zero_reg));
          // Advance current position after a zero-length match.
          Label advance;
          __ bind(&advance);
          __ AddWord(current_input_offset(), current_input_offset(),
                     Operand((mode_ == UC16) ? 2 : 1));
          if (global_unicode()) CheckNotInSurrogatePair(0, &advance);
        }
        __ bind(&reload_string_start_minus_one);
        // Prepare a0 to initialize registers with its value in the next run.
        // Must be immediately before the jump to avoid clobbering.
        __ LoadWord(a0,
                    MemOperand(frame_pointer(), kStringStartMinusOneOffset));
        __ Branch(&load_char_start_regexp);
      } else {
        __ li(a0, Operand(SUCCESS));
      }
    }
    // Exit and return a0.
    __ bind(&exit_label_);
    if (global()) {
      __ LoadWord(a0, MemOperand(frame_pointer(), kSuccessfulCapturesOffset));
    }
    __ bind(&return_a0);
    // Restore the original regexp stack pointer value (effectively, pop the
    // stored base pointer).
    PopRegExpBasePointer(backtrack_stackpointer(), a1);
    // Skip sp past regexp registers and local variables..
    __ mv(sp, frame_pointer());
    // Restore registers fp..s11 and return (restoring ra to pc).
    __ MultiPop(registers_to_retain | ra);
    __ Ret();
    // Backtrack code (branch target for conditional backtracks).
    if (backtrack_label_.is_linked()) {
      __ bind(&backtrack_label_);
      Backtrack();
    }
    Label exit_with_exception;
    // Preempt-code.
    if (check_preempt_label_.is_linked()) {
      SafeCallTarget(&check_preempt_label_);
      StoreRegExpStackPointerToMemory(backtrack_stackpointer(), a1);
      // Put regexp engine registers on stack.
      CallCheckStackGuardState(a0);
      // If returning non-zero, we should end execution with the given
      // result as return value.
      __ Branch(&return_a0, ne, a0, Operand(zero_reg));
      LoadRegExpStackPointerFromMemory(backtrack_stackpointer());
      // String might have moved: Reload end of string from frame.
      __ LoadWord(end_of_input_address(),
                  MemOperand(frame_pointer(), kInputEndOffset));
      SafeReturn();
    }
    // Backtrack stack overflow code.
    if (stack_overflow_label_.is_linked()) {
      SafeCallTarget(&stack_overflow_label_);
      // Call GrowStack(isolate).
      StoreRegExpStackPointerToMemory(backtrack_stackpointer(), a1);
      static constexpr int kNumArguments = 1;
      __ PrepareCallCFunction(kNumArguments, 0, a0);
      __ li(a0, ExternalReference::isolate_address(isolate()));
      ExternalReference grow_stack = ExternalReference::re_grow_stack();
      CallCFunctionFromIrregexpCode(grow_stack, kNumArguments);
      // If nullptr is returned, we have failed to grow the stack, and must exit
      // with a stack-overflow exception.
      __ BranchShort(&exit_with_exception, eq, a0, Operand(zero_reg));
      // Otherwise use return value as new stack pointer.
      __ mv(backtrack_stackpointer(), a0);
      // Restore saved registers and continue.
      SafeReturn();
    }
    if (exit_with_exception.is_linked()) {
      // If any of the code above needed to exit with an exception.
      __ bind(&exit_with_exception);
      // Exit with Result EXCEPTION(-1) to signal thrown exception.
      __ li(a0, Operand(EXCEPTION));
      __ jmp(&return_a0);
    }
    if (fallback_label_.is_linked()) {
      __ bind(&fallback_label_);
      __ li(a0, Operand(FALLBACK_TO_EXPERIMENTAL));
      __ jmp(&return_a0);
    }
  }
  CodeDesc code_desc;
  masm_->GetCode(isolate(), &code_desc);
  Handle<Code> code =
      Factory::CodeBuilder(isolate(), code_desc, CodeKind::REGEXP)
          .set_self_reference(masm_->CodeObject())
          .set_empty_source_position_table()
          .Build();
  LOG(masm_->isolate(),
      RegExpCodeCreateEvent(Cast<AbstractCode>(code), source, flags));
  return Cast<HeapObject>(code);
}
References __, Backtrack(), backtrack_label_, backtrack_stackpointer(), v8::internal::Factory::CodeBuilder::Build(), CallCFunctionFromIrregexpCode(), CallCheckStackGuardState(), char_size(), check_preempt_label_, v8::internal::RegExpMacroAssembler::CheckNotInSurrogatePair(), code, code_pointer(), v8::internal::CONSTANT_SIZE, v8::internal::RegListBase< RegisterT >::Count(), current_character(), current_input_offset(), v8::internal::DCHECK(), DCHECK_EQ, end_of_input_address(), entry_label_, v8::internal::eq, v8::internal::NativeRegExpMacroAssembler::EXCEPTION, exit_label_, fallback_label_, v8::internal::NativeRegExpMacroAssembler::FALLBACK_TO_EXPERIMENTAL, v8::internal::flags, frame_pointer(), v8::internal::RegExpMacroAssembler::global(), v8::internal::RegExpMacroAssembler::global_unicode(), v8::internal::RegExpMacroAssembler::global_with_zero_length_check(), v8::internal::wasm::grow_stack(), internal_failure_label_, v8::internal::Label::is_linked(), isolate(), v8::internal::ExternalReference::isolate_address(), kBacktrackCountOffset, kFrameTypeOffset, kInputEndOffset, kInputStartOffset, kInputStringOffset, v8::internal::kIntSize, kNumCalleeRegsToRetain, kNumOutputRegistersOffset, kRegExpStackBasePointerOffset, kRegisterOutputOffset, kRegisterZeroOffset, v8::internal::kScratchReg, kStartIndexOffset, kStringStartMinusOneOffset, kSuccessfulCapturesOffset, v8::internal::kSystemPointerSize, v8::internal::le, LoadCurrentCharacterUnchecked(), LoadRegExpStackPointerFromMemory(), LOG, v8::internal::lt, v8::internal::StackFrame::MANUAL, masm_, mode_, v8::internal::ne, num_registers_, num_saved_registers_, PopRegExpBasePointer(), v8::internal::Label::pos(), v8::internal::wasm::liftoff::push(), PushRegExpBasePointer(), register_location(), SafeCallTarget(), SafeReturn(), v8::internal::Factory::CodeBuilder::set_empty_source_position_table(), v8::internal::Factory::CodeBuilder::set_self_reference(), stack_overflow_label_, start_label_, StoreRegExpStackPointerToMemory(), v8::internal::NativeRegExpMacroAssembler::SUCCESS, success_label_, v8::internal::StackFrame::TypeToMarker(), v8::internal::NativeRegExpMacroAssembler::UC16, and v8::internal::uge.
GoTo()
void v8::internal::RegExpMacroAssemblerRISCV::GoTo (Label * label) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 1017 of file regexp-macro-assembler-riscv.cc.
                                              {
  if (to == nullptr) {
    Backtrack();
    return;
  }
  __ jmp(to);
  return;
}
References __, and Backtrack().
Referenced by CheckNotBackReferenceIgnoreCase(), and SkipUntilBitInTable().
IfRegisterEqPos()
void v8::internal::RegExpMacroAssemblerRISCV::IfRegisterEqPos (int reg, Label * if_eq) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 1038 of file regexp-macro-assembler-riscv.cc.
                                                                     {
  __ LoadWord(a0, register_location(reg));
  BranchOrBacktrack(if_eq, eq, a0, Operand(current_input_offset()));
}
References __, BranchOrBacktrack(), current_input_offset(), v8::internal::eq, and register_location().
IfRegisterGE()
void v8::internal::RegExpMacroAssemblerRISCV::IfRegisterGE (int reg, int comparand, Label * if_ge) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 1026 of file regexp-macro-assembler-riscv.cc.
                                                           {
  __ LoadWord(a0, register_location(reg));
  BranchOrBacktrack(if_ge, ge, a0, Operand(comparand));
}
References __, BranchOrBacktrack(), v8::internal::ge, and register_location().
IfRegisterLT()
void v8::internal::RegExpMacroAssemblerRISCV::IfRegisterLT (int reg, int comparand, Label * if_lt) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 1032 of file regexp-macro-assembler-riscv.cc.
                                                           {
  __ LoadWord(a0, register_location(reg));
  BranchOrBacktrack(if_lt, lt, a0, Operand(comparand));
}
References __, BranchOrBacktrack(), v8::internal::lt, and register_location().
Implementation()
RegExpMacroAssembler::IrregexpImplementation v8::internal::RegExpMacroAssemblerRISCV::Implementation () [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 1044 of file regexp-macro-assembler-riscv.cc.
                                          {
  return kRISCVImplementation;
}
isolate()
Isolate* v8::internal::RegExpMacroAssemblerRISCV::isolate () const [inline], [private]
Definition at line 231 of file regexp-macro-assembler-riscv.h.
{ return masm_->isolate(); }
References v8::internal::Factory::isolate().
Referenced by AssertAboveStackLimitMinusSlack(), CallCheckStackGuardState(), CallIsCharacterInRangeArray(), GetCode(), LoadRegExpStackPointerFromMemory(), PopRegExpBasePointer(), PushRegExpBasePointer(), ReadStackPointerFromRegister(), StoreRegExpStackPointerToMemory(), and WriteStackPointerToRegister().
LoadCurrentCharacterUnchecked()
void v8::internal::RegExpMacroAssemblerRISCV::LoadCurrentCharacterUnchecked (int cp_offset, int character_count) [override], [virtual]
Implements v8::internal::NativeRegExpMacroAssembler.
Definition at line 1367 of file regexp-macro-assembler-riscv.cc.
                                                                              {
  Register offset = current_input_offset();
  if (cp_offset != 0) {
    // kScratchReg2 is not being used to store the capture start index at this
    // point.
    __ AddWord(kScratchReg2, current_input_offset(),
               Operand(cp_offset * char_size()));
    offset = kScratchReg2;
  }
  // If unaligned load/stores are not supported then this function must only
  // be used to load a single character at a time.
  if (!CanReadUnaligned()) {
    DCHECK_EQ(1, characters);
  }
  if (mode_ == LATIN1) {
    if (characters == 4) {
      __ AddWord(kScratchReg, end_of_input_address(), offset);
      __ Load32U(current_character(), MemOperand(kScratchReg));
    } else if (characters == 2) {
      __ AddWord(kScratchReg, end_of_input_address(), offset);
      __ Lhu(current_character(), MemOperand(kScratchReg));
    } else {
      DCHECK_EQ(1, characters);
      __ AddWord(kScratchReg, end_of_input_address(), offset);
      __ Lbu(current_character(), MemOperand(kScratchReg));
    }
  } else {
    DCHECK_EQ(UC16, mode_);
    if (characters == 2) {
      __ AddWord(kScratchReg, end_of_input_address(), offset);
      __ Load32U(current_character(), MemOperand(kScratchReg));
    } else {
      DCHECK_EQ(1, characters);
      __ AddWord(kScratchReg, end_of_input_address(), offset);
      __ Lhu(current_character(), MemOperand(kScratchReg));
    }
  }
}
References __, v8::internal::NativeRegExpMacroAssembler::CanReadUnaligned(), char_size(), current_character(), current_input_offset(), DCHECK_EQ, end_of_input_address(), v8::internal::kScratchReg, v8::internal::kScratchReg2, v8::internal::NativeRegExpMacroAssembler::LATIN1, mode_, and v8::internal::NativeRegExpMacroAssembler::UC16.
Referenced by GetCode(), and SetCurrentPositionFromEnd().
LoadRegExpStackPointerFromMemory()
void v8::internal::RegExpMacroAssemblerRISCV::LoadRegExpStackPointerFromMemory (Register dst) [private]
Definition at line 624 of file regexp-macro-assembler-riscv.cc.
                                                                             {
  ExternalReference ref =
      ExternalReference::address_of_regexp_stack_stack_pointer(isolate());
  __ li(dst, Operand(ref));
  __ LoadWord(dst, MemOperand(dst));
}
References __, and isolate().
Referenced by GetCode().
Pop()
void v8::internal::RegExpMacroAssemblerRISCV::Pop (Register target) [inline], [private]
Definition at line 1320 of file regexp-macro-assembler-riscv.cc.
                                                   {
  DCHECK(target != backtrack_stackpointer());
  __ Lw(target, MemOperand(backtrack_stackpointer()));
  __ AddWord(backtrack_stackpointer(), backtrack_stackpointer(), kIntSize);
}
References __, backtrack_stackpointer(), v8::internal::DCHECK(), and v8::internal::kIntSize.
Referenced by Backtrack(), PopCurrentPosition(), and PopRegister().
PopCallerSavedRegisters()
void v8::internal::RegExpMacroAssemblerRISCV::PopCallerSavedRegisters () [private]
PopCurrentPosition()
void v8::internal::RegExpMacroAssemblerRISCV::PopCurrentPosition () [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 1048 of file regexp-macro-assembler-riscv.cc.
                                                   {
  Pop(current_input_offset());
}
References current_input_offset(), and Pop().
PopRegExpBasePointer()
void v8::internal::RegExpMacroAssemblerRISCV::PopRegExpBasePointer (Register stack_pointer_out, Register scratch) [private]
Definition at line 650 of file regexp-macro-assembler-riscv.cc.
                                                                       {
  ExternalReference ref =
      ExternalReference::address_of_regexp_stack_memory_top_address(isolate());
  __ LoadWord(stack_pointer_out,
              MemOperand(frame_pointer(), kRegExpStackBasePointerOffset));
  __ li(scratch, Operand(ref));
  __ LoadWord(scratch, MemOperand(scratch));
  __ AddWord(stack_pointer_out, stack_pointer_out, scratch);
  StoreRegExpStackPointerToMemory(stack_pointer_out, scratch);
}
References __, frame_pointer(), isolate(), kRegExpStackBasePointerOffset, and StoreRegExpStackPointerToMemory().
Referenced by GetCode().
PopRegister()
void v8::internal::RegExpMacroAssemblerRISCV::PopRegister (int register_index) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 1052 of file regexp-macro-assembler-riscv.cc.
                                                              {
  Pop(a0);
  __ StoreWord(a0, register_location(register_index));
}
References __, Pop(), and register_location().
print_regexp_frame_constants()
void v8::internal::RegExpMacroAssemblerRISCV::print_regexp_frame_constants ()
Push()
void v8::internal::RegExpMacroAssemblerRISCV::Push (Register source) [inline], [private]
Definition at line 1313 of file regexp-macro-assembler-riscv.cc.
                                                    {
  DCHECK(source != backtrack_stackpointer());
  __ AddWord(backtrack_stackpointer(), backtrack_stackpointer(),
             Operand(-kIntSize));
  __ Sw(source, MemOperand(backtrack_stackpointer()));
}
References __, backtrack_stackpointer(), v8::internal::DCHECK(), and v8::internal::kIntSize.
Referenced by PushBacktrack(), PushCurrentPosition(), and PushRegister().
PushBacktrack()
void v8::internal::RegExpMacroAssemblerRISCV::PushBacktrack (Label * label) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 1057 of file regexp-macro-assembler-riscv.cc.
                                                          {
  if (label->is_bound()) {
    int target = label->pos();
    __ li(a0,
          Operand(target + InstructionStream::kHeaderSize - kHeapObjectTag));
  } else {
    Assembler::BlockTrampolinePoolScope block_trampoline_pool(masm_.get());
    Label after_constant;
    __ BranchShort(&after_constant);
    int offset = masm_->pc_offset();
    int cp_offset = offset + InstructionStream::kHeaderSize - kHeapObjectTag;
    __ emit(0);
    masm_->label_at_put(label, offset);
    __ bind(&after_constant);
    if (is_int16(cp_offset)) {
      __ Load32U(a0, MemOperand(code_pointer(), cp_offset));
    } else {
      __ AddWord(a0, code_pointer(), cp_offset);
      __ Load32U(a0, MemOperand(a0, 0));
    }
  }
  Push(a0);
  CheckStackLimit();
}
References __, CheckStackLimit(), code_pointer(), v8::internal::Label::is_bound(), v8::internal::TrustedObject::kHeaderSize, v8::internal::kHeapObjectTag, masm_, v8::internal::Label::pos(), and Push().
PushCallerSavedRegisters()
void v8::internal::RegExpMacroAssemblerRISCV::PushCallerSavedRegisters () [private]
PushCurrentPosition()
void v8::internal::RegExpMacroAssemblerRISCV::PushCurrentPosition () [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 1082 of file regexp-macro-assembler-riscv.cc.
                                                    {
  Push(current_input_offset());
  CheckStackLimit();
}
References CheckStackLimit(), current_input_offset(), and Push().
PushRegExpBasePointer()
void v8::internal::RegExpMacroAssemblerRISCV::PushRegExpBasePointer (Register stack_pointer, Register scratch) [private]
Definition at line 639 of file regexp-macro-assembler-riscv.cc.
                                                                        {
  ExternalReference ref =
      ExternalReference::address_of_regexp_stack_memory_top_address(isolate());
  __ li(scratch, Operand(ref));
  __ LoadWord(scratch, MemOperand(scratch));
  __ SubWord(scratch, stack_pointer, scratch);
  __ StoreWord(scratch,
               MemOperand(frame_pointer(), kRegExpStackBasePointerOffset));
}
References __, frame_pointer(), isolate(), and kRegExpStackBasePointerOffset.
Referenced by GetCode().
PushRegister()
void v8::internal::RegExpMacroAssemblerRISCV::PushRegister (int register_index, StackCheckFlag check_stack_limit) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 1087 of file regexp-macro-assembler-riscv.cc.
                                                                               {
  __ LoadWord(a0, register_location(register_index));
  Push(a0);
  if (check_stack_limit) {
    CheckStackLimit();
  } else if (V8_UNLIKELY(v8_flags.slow_debug_code)) {
    AssertAboveStackLimitMinusSlack();
  }
}
References __, AssertAboveStackLimitMinusSlack(), CheckStackLimit(), Push(), register_location(), v8::internal::v8_flags, and V8_UNLIKELY.
ReadCurrentPositionFromRegister()
void v8::internal::RegExpMacroAssemblerRISCV::ReadCurrentPositionFromRegister (int reg) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 1098 of file regexp-macro-assembler-riscv.cc.
                                                                       {
  __ LoadWord(current_input_offset(), register_location(reg));
}
References __, current_input_offset(), and register_location().
ReadStackPointerFromRegister()
void v8::internal::RegExpMacroAssemblerRISCV::ReadStackPointerFromRegister (int reg) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 1111 of file regexp-macro-assembler-riscv.cc.
                                                                    {
  ExternalReference ref =
      ExternalReference::address_of_regexp_stack_memory_top_address(isolate());
  __ li(a1, ref);
  __ LoadWord(a1, MemOperand(a1));
  __ Lw(backtrack_stackpointer(), register_location(reg));
  __ AddWord(backtrack_stackpointer(), backtrack_stackpointer(), a1);
}
References __, backtrack_stackpointer(), isolate(), and register_location().
register_location()
MemOperand v8::internal::RegExpMacroAssemblerRISCV::register_location (int register_index) [private]
Definition at line 1256 of file regexp-macro-assembler-riscv.cc.
                                                                          {
  DCHECK(register_index < (1 << 30));
  if (num_registers_ <= register_index) {
    num_registers_ = register_index + 1;
  }
  return MemOperand(frame_pointer(),
                    kRegisterZeroOffset - register_index * kSystemPointerSize);
}
References v8::internal::DCHECK(), frame_pointer(), kRegisterZeroOffset, v8::internal::kSystemPointerSize, and num_registers_.
Referenced by AdvanceRegister(), CheckNotBackReference(), CheckNotBackReferenceIgnoreCase(), ClearRegisters(), GetCode(), IfRegisterEqPos(), IfRegisterGE(), IfRegisterLT(), PopRegister(), PushRegister(), ReadCurrentPositionFromRegister(), ReadStackPointerFromRegister(), SetRegister(), WriteCurrentPositionToRegister(), and WriteStackPointerToRegister().
SafeCall()
void v8::internal::RegExpMacroAssemblerRISCV::SafeCall (Label * to, Condition cond, Register rs, const Operand & rt) [inline], [private]
Definition at line 1296 of file regexp-macro-assembler-riscv.cc.
                                                            {
  __ BranchAndLink(to, cond, rs, rt);
}
References __.
Referenced by CheckPreemption(), and CheckStackLimit().
SafeCallTarget()
void v8::internal::RegExpMacroAssemblerRISCV::SafeCallTarget (Label * name) [inline], [private]
Definition at line 1307 of file regexp-macro-assembler-riscv.cc.
                                                          {
  __ bind(name);
  __ SubWord(ra, ra, Operand(masm_->CodeObject()));
  __ push(ra);
}
References __, masm_, v8::internal::name, and v8::internal::wasm::liftoff::push().
Referenced by GetCode().
SafeReturn()
void v8::internal::RegExpMacroAssemblerRISCV::SafeReturn () [inline], [private]
Definition at line 1301 of file regexp-macro-assembler-riscv.cc.
                                           {
  __ pop(ra);
  __ AddWord(t1, ra, Operand(masm_->CodeObject()));
  __ Jump(t1);
}
References __, and masm_.
Referenced by GetCode().
SetCurrentPositionFromEnd()
void v8::internal::RegExpMacroAssemblerRISCV::SetCurrentPositionFromEnd (int by) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 1120 of file regexp-macro-assembler-riscv.cc.
                                                                {
  Label after_position;
  __ BranchShort(&after_position, ge, current_input_offset(),
                 Operand(-by * char_size()));
  __ li(current_input_offset(), -by * char_size());
  // On RegExp code entry (where this operation is used), the character before
  // the current position is expected to be already loaded.
  // We have advanced the position, so it's safe to read backwards.
  LoadCurrentCharacterUnchecked(-1, 1);
  __ bind(&after_position);
}
References __, char_size(), current_input_offset(), v8::internal::ge, and LoadCurrentCharacterUnchecked().
SetRegister()
void v8::internal::RegExpMacroAssemblerRISCV::SetRegister (int register_index, int to) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 1132 of file regexp-macro-assembler-riscv.cc.
                                                                      {
  DCHECK(register_index >= num_saved_registers_); // Reserved for positions!
  __ li(a0, Operand(to));
  __ StoreWord(a0, register_location(register_index));
}
References __, v8::internal::DCHECK(), num_saved_registers_, and register_location().
SkipUntilBitInTable()
void v8::internal::RegExpMacroAssemblerRISCV::SkipUntilBitInTable (int cp_offset, Handle< ByteArray > table, Handle< ByteArray > nibble_table, int advance_by) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 501 of file regexp-macro-assembler-riscv.cc.
                    {
  // TODO(pthier): Optimize. Table can be loaded outside of the loop.
  Label cont, again;
  Bind(&again);
  LoadCurrentCharacter(cp_offset, &cont, true);
  CheckBitInTable(table, &cont);
  AdvanceCurrentPosition(advance_by);
  GoTo(&again);
  Bind(&cont);
}
References AdvanceCurrentPosition(), Bind(), CheckBitInTable(), GoTo(), and v8::internal::RegExpMacroAssembler::LoadCurrentCharacter().
stack_limit_slack_slot_count()
int v8::internal::RegExpMacroAssemblerRISCV::stack_limit_slack_slot_count () [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 127 of file regexp-macro-assembler-riscv.cc.
                                                            {
  return RegExpStack::kStackLimitSlackSlotCount;
}
References v8::internal::RegExpStack::kStackLimitSlackSlotCount.
StoreRegExpStackPointerToMemory()
void v8::internal::RegExpMacroAssemblerRISCV::StoreRegExpStackPointerToMemory (Register src, Register scratch) [private]
Definition at line 631 of file regexp-macro-assembler-riscv.cc.
                                    {
  ExternalReference ref =
      ExternalReference::address_of_regexp_stack_stack_pointer(isolate());
  __ li(scratch, Operand(ref));
  __ StoreWord(src, MemOperand(scratch));
}
References __, and isolate().
Referenced by GetCode(), and PopRegExpBasePointer().
Succeed()
bool v8::internal::RegExpMacroAssemblerRISCV::Succeed () [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 1138 of file regexp-macro-assembler-riscv.cc.
                                        {
  __ jmp(&success_label_);
  return global();
}
References __, v8::internal::RegExpMacroAssembler::global(), and success_label_.
WriteCurrentPositionToRegister()
void v8::internal::RegExpMacroAssemblerRISCV::WriteCurrentPositionToRegister (int reg, int cp_offset) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 1143 of file regexp-macro-assembler-riscv.cc.
                                                                              {
  if (cp_offset == 0) {
    __ StoreWord(current_input_offset(), register_location(reg));
  } else {
    __ AddWord(a0, current_input_offset(), Operand(cp_offset * char_size()));
    __ StoreWord(a0, register_location(reg));
  }
}
References __, char_size(), current_input_offset(), and register_location().
WriteStackPointerToRegister()
void v8::internal::RegExpMacroAssemblerRISCV::WriteStackPointerToRegister (int reg) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 1102 of file regexp-macro-assembler-riscv.cc.
                                                                   {
  ExternalReference ref =
      ExternalReference::address_of_regexp_stack_memory_top_address(isolate());
  __ li(a0, ref);
  __ LoadWord(a0, MemOperand(a0));
  __ SubWord(a0, backtrack_stackpointer(), a0);
  __ Sw(a0, register_location(reg));
}
References __, backtrack_stackpointer(), isolate(), and register_location().
Member Data Documentation
backtrack_label_
Label v8::internal::RegExpMacroAssemblerRISCV::backtrack_label_ [private]
Definition at line 250 of file regexp-macro-assembler-riscv.h.
Referenced by BranchOrBacktrack(), GetCode(), and ~RegExpMacroAssemblerRISCV().
check_preempt_label_
Label v8::internal::RegExpMacroAssemblerRISCV::check_preempt_label_ [private]
Definition at line 252 of file regexp-macro-assembler-riscv.h.
Referenced by CheckPreemption(), GetCode(), and ~RegExpMacroAssemblerRISCV().
entry_label_
Label v8::internal::RegExpMacroAssemblerRISCV::entry_label_ [private]
Definition at line 247 of file regexp-macro-assembler-riscv.h.
Referenced by GetCode(), RegExpMacroAssemblerRISCV(), and ~RegExpMacroAssemblerRISCV().
exit_label_
Label v8::internal::RegExpMacroAssemblerRISCV::exit_label_ [private]
Definition at line 251 of file regexp-macro-assembler-riscv.h.
Referenced by Fail(), GetCode(), and ~RegExpMacroAssemblerRISCV().
fallback_label_
Label v8::internal::RegExpMacroAssemblerRISCV::fallback_label_ [private]
Definition at line 255 of file regexp-macro-assembler-riscv.h.
Referenced by Backtrack(), GetCode(), and ~RegExpMacroAssemblerRISCV().
internal_failure_label_
Label v8::internal::RegExpMacroAssemblerRISCV::internal_failure_label_ [private]
Definition at line 254 of file regexp-macro-assembler-riscv.h.
Referenced by GetCode(), RegExpMacroAssemblerRISCV(), and ~RegExpMacroAssemblerRISCV().
kBacktrackCountOffset
constexpr int v8::internal::RegExpMacroAssemblerRISCV::kBacktrackCountOffset [static], [constexpr], [private]
Initial value:
=
      kStringStartMinusOneOffset - kSystemPointerSize
Definition at line 146 of file regexp-macro-assembler-riscv.h.
Referenced by Backtrack(), and GetCode().
kDirectCallOffset
constexpr int v8::internal::RegExpMacroAssemblerRISCV::kDirectCallOffset = kIsolateOffset - kSystemPointerSize [static], [constexpr], [private]
Definition at line 128 of file regexp-macro-assembler-riscv.h.
Referenced by CheckStackGuardState().
kFramePointerOffset
constexpr int v8::internal::RegExpMacroAssemblerRISCV::kFramePointerOffset = 0 [static], [constexpr], [private]
Definition at line 104 of file regexp-macro-assembler-riscv.h.
kFrameTypeOffset
constexpr int v8::internal::RegExpMacroAssemblerRISCV::kFrameTypeOffset [static], [constexpr], [private]
Initial value:
=
      kFramePointerOffset - kSystemPointerSize
Definition at line 119 of file regexp-macro-assembler-riscv.h.
Referenced by GetCode().
kInitialBufferSize
constexpr int v8::internal::RegExpMacroAssemblerRISCV::kInitialBufferSize = 1024 [static], [constexpr], [private]
Definition at line 159 of file regexp-macro-assembler-riscv.h.
kInputEndOffset
constexpr int v8::internal::RegExpMacroAssemblerRISCV::kInputEndOffset [static], [constexpr], [private]
Initial value:
=
      kRegisterOutputOffset - kSystemPointerSize
Definition at line 133 of file regexp-macro-assembler-riscv.h.
Referenced by CheckStackGuardState(), and GetCode().
kInputStartOffset
constexpr int v8::internal::RegExpMacroAssemblerRISCV::kInputStartOffset = kInputEndOffset - kSystemPointerSize [static], [constexpr], [private]
Definition at line 135 of file regexp-macro-assembler-riscv.h.
Referenced by CheckStackGuardState(), and GetCode().
kInputStringOffset
constexpr int v8::internal::RegExpMacroAssemblerRISCV::kInputStringOffset [static], [constexpr], [private]
Initial value:
=
      kStartIndexOffset - kSystemPointerSize
Definition at line 138 of file regexp-macro-assembler-riscv.h.
Referenced by CheckStackGuardState(), and GetCode().
kIsolateOffset
constexpr int v8::internal::RegExpMacroAssemblerRISCV::kIsolateOffset = kFrameTypeOffset - kSystemPointerSize [static], [constexpr], [private]
Definition at line 127 of file regexp-macro-assembler-riscv.h.
Referenced by CheckStackGuardState().
kNumberOfStackLocals
constexpr int v8::internal::RegExpMacroAssemblerRISCV::kNumberOfStackLocals = 4 [static], [constexpr], [private]
Definition at line 153 of file regexp-macro-assembler-riscv.h.
kNumCalleeRegsToRetain
constexpr int v8::internal::RegExpMacroAssemblerRISCV::kNumCalleeRegsToRetain = 12 [static], [constexpr], [private]
Definition at line 112 of file regexp-macro-assembler-riscv.h.
Referenced by GetCode().
kNumOutputRegistersOffset
constexpr int v8::internal::RegExpMacroAssemblerRISCV::kNumOutputRegistersOffset [static], [constexpr], [private]
Initial value:
=
      kDirectCallOffset - kSystemPointerSize
Definition at line 129 of file regexp-macro-assembler-riscv.h.
Referenced by GetCode().
kRegExpStackBasePointerOffset
constexpr int v8::internal::RegExpMacroAssemblerRISCV::kRegExpStackBasePointerOffset [static], [constexpr], [private]
Initial value:
=
      kBacktrackCountOffset - kSystemPointerSize
Definition at line 151 of file regexp-macro-assembler-riscv.h.
Referenced by GetCode(), PopRegExpBasePointer(), and PushRegExpBasePointer().
kRegisterOutputOffset
constexpr int v8::internal::RegExpMacroAssemblerRISCV::kRegisterOutputOffset [static], [constexpr], [private]
Initial value:
=
      kNumOutputRegistersOffset - kSystemPointerSize
Definition at line 131 of file regexp-macro-assembler-riscv.h.
Referenced by GetCode().
kRegisterZeroOffset
constexpr int v8::internal::RegExpMacroAssemblerRISCV::kRegisterZeroOffset [static], [constexpr], [private]
Initial value:
=
      kRegExpStackBasePointerOffset - kSystemPointerSize
Definition at line 155 of file regexp-macro-assembler-riscv.h.
Referenced by GetCode(), and register_location().
kReturnAddressOffset
constexpr int v8::internal::RegExpMacroAssemblerRISCV::kReturnAddressOffset [static], [constexpr], [private]
Initial value:
=
      kStoredRegistersOffset + kNumCalleeRegsToRetain * kSystemPointerSize
Definition at line 113 of file regexp-macro-assembler-riscv.h.
kStackFrameHeaderOffset
constexpr int v8::internal::RegExpMacroAssemblerRISCV::kStackFrameHeaderOffset = kReturnAddressOffset [static], [constexpr], [private]
Definition at line 117 of file regexp-macro-assembler-riscv.h.
kStartIndexOffset
constexpr int v8::internal::RegExpMacroAssemblerRISCV::kStartIndexOffset [static], [constexpr], [private]
Initial value:
=
      kInputStartOffset - kSystemPointerSize
Definition at line 136 of file regexp-macro-assembler-riscv.h.
Referenced by CheckStackGuardState(), and GetCode().
kStoredRegistersOffset
constexpr int v8::internal::RegExpMacroAssemblerRISCV::kStoredRegistersOffset = kFramePointerOffset [static], [constexpr], [private]
Definition at line 108 of file regexp-macro-assembler-riscv.h.
kStringStartMinusOneOffset
constexpr int v8::internal::RegExpMacroAssemblerRISCV::kStringStartMinusOneOffset [static], [constexpr], [private]
Initial value:
=
      kSuccessfulCapturesOffset - kSystemPointerSize
Definition at line 144 of file regexp-macro-assembler-riscv.h.
Referenced by CheckAtStart(), CheckNotAtStart(), CheckNotBackReference(), CheckNotBackReferenceIgnoreCase(), CheckPosition(), ClearRegisters(), and GetCode().
kSuccessfulCapturesOffset
constexpr int v8::internal::RegExpMacroAssemblerRISCV::kSuccessfulCapturesOffset [static], [constexpr], [private]
Initial value:
=
      kInputStringOffset - kSystemPointerSize
Definition at line 142 of file regexp-macro-assembler-riscv.h.
Referenced by GetCode().
masm_
const std::unique_ptr<MacroAssembler> v8::internal::RegExpMacroAssemblerRISCV::masm_ [private]
Definition at line 233 of file regexp-macro-assembler-riscv.h.
Referenced by AssertAboveStackLimitMinusSlack(), CallCheckStackGuardState(), CallIsCharacterInRangeArray(), CheckNotBackReferenceIgnoreCase(), CheckPreemption(), CheckStackLimit(), GetCode(), PushBacktrack(), SafeCallTarget(), and SafeReturn().
mode_
const Mode v8::internal::RegExpMacroAssemblerRISCV::mode_ [private]
Definition at line 237 of file regexp-macro-assembler-riscv.h.
Referenced by CheckBitInTable(), CheckNotBackReference(), CheckNotBackReferenceIgnoreCase(), CheckSpecialClassRanges(), GetCode(), and LoadCurrentCharacterUnchecked().
no_root_array_scope_
const NoRootArrayScope v8::internal::RegExpMacroAssemblerRISCV::no_root_array_scope_ [private]
Definition at line 234 of file regexp-macro-assembler-riscv.h.
num_registers_
int v8::internal::RegExpMacroAssemblerRISCV::num_registers_ [private]
Definition at line 240 of file regexp-macro-assembler-riscv.h.
Referenced by AdvanceRegister(), GetCode(), and register_location().
num_saved_registers_
const int v8::internal::RegExpMacroAssemblerRISCV::num_saved_registers_ [private]
Definition at line 244 of file regexp-macro-assembler-riscv.h.
Referenced by GetCode(), and SetRegister().
stack_overflow_label_
Label v8::internal::RegExpMacroAssemblerRISCV::stack_overflow_label_ [private]
Definition at line 253 of file regexp-macro-assembler-riscv.h.
Referenced by CheckStackLimit(), GetCode(), and ~RegExpMacroAssemblerRISCV().
start_label_
Label v8::internal::RegExpMacroAssemblerRISCV::start_label_ [private]
Definition at line 248 of file regexp-macro-assembler-riscv.h.
Referenced by GetCode(), RegExpMacroAssemblerRISCV(), and ~RegExpMacroAssemblerRISCV().
success_label_
Label v8::internal::RegExpMacroAssemblerRISCV::success_label_ [private]
Definition at line 249 of file regexp-macro-assembler-riscv.h.
Referenced by GetCode(), Succeed(), and ~RegExpMacroAssemblerRISCV().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/riscv/regexp-macro-assembler-riscv.h
/mnt/V8SourceCode/src/regexp/riscv/regexp-macro-assembler-riscv.cc