v8::internal::compiler::turboshaft::NodeGroup Class Reference
#include <wasm-revec-reducer.h>
Public Member Functions
NodeGroup (OpIndex a, OpIndex b)
size_t size () const
OpIndex operator[] (int i) const
bool operator== (const NodeGroup &other) const
bool operator!= (const NodeGroup &other) const
const OpIndex * begin () const
const OpIndex * end () const
Static Public Attributes
static constexpr int kSize = kSimd256Size / kSimd128Size
Private Attributes
OpIndex indexes_ [kSize]
Detailed Description
Definition at line 216 of file wasm-revec-reducer.h.
Constructor & Destructor Documentation
NodeGroup()
v8::internal::compiler::turboshaft::NodeGroup::NodeGroup (OpIndex a, OpIndex b) [inline]
Definition at line 220 of file wasm-revec-reducer.h.
                                  {
    indexes_[0] = a;
    indexes_[1] = b;
  }
References indexes_.
Member Function Documentation
begin()
const OpIndex* v8::internal::compiler::turboshaft::NodeGroup::begin () const [inline]
Definition at line 234 of file wasm-revec-reducer.h.
{ return indexes_; }
References indexes_.
end()
const OpIndex* v8::internal::compiler::turboshaft::NodeGroup::end () const [inline]
Definition at line 235 of file wasm-revec-reducer.h.
{ return indexes_ + kSize; }
References indexes_, and kSize.
operator!=()
bool v8::internal::compiler::turboshaft::NodeGroup::operator!= (const NodeGroup & other) const [inline]
Definition at line 230 of file wasm-revec-reducer.h.
                                                {
    return indexes_[0] != other.indexes_[0] || indexes_[1] != other.indexes_[1];
  }
References indexes_.
operator==()
bool v8::internal::compiler::turboshaft::NodeGroup::operator== (const NodeGroup & other) const [inline]
Definition at line 227 of file wasm-revec-reducer.h.
                                                {
    return indexes_[0] == other.indexes_[0] && indexes_[1] == other.indexes_[1];
  }
References indexes_.
operator[]()
OpIndex v8::internal::compiler::turboshaft::NodeGroup::operator[] (int i) const [inline]
Definition at line 225 of file wasm-revec-reducer.h.
{ return indexes_[i]; }
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and indexes_.
size()
size_t v8::internal::compiler::turboshaft::NodeGroup::size () const [inline]
Definition at line 224 of file wasm-revec-reducer.h.
{ return kSize; }
References kSize.
Referenced by v8::internal::compiler::turboshaft::SLPTree::BuildTreeRec(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::DecideVectorize(), v8::internal::compiler::turboshaft::SLPTree::HasInputDependencies(), v8::internal::compiler::turboshaft::SLPTree::NewForcePackNode(), v8::internal::compiler::turboshaft::SLPTree::NewIntersectPackNode(), and v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::ReduceForceOrIntersectPackNode().
Member Data Documentation
indexes_
OpIndex v8::internal::compiler::turboshaft::NodeGroup::indexes_[kSize] [private]
Definition at line 238 of file wasm-revec-reducer.h.
Referenced by begin(), end(), NodeGroup(), operator!=(), operator==(), and operator[]().
kSize
constexpr int v8::internal::compiler::turboshaft::NodeGroup::kSize = kSimd256Size / kSimd128Size [static], [constexpr]
Definition at line 219 of file wasm-revec-reducer.h.
Referenced by end(), and size().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/wasm-revec-reducer.h