v8::internal::compiler::ElementsTransition Class Reference
#include <simplified-operator.h>
Public Types
enum Mode : uint8_t { kFastTransition
, kSlowTransition
 }
Public Member Functions
ElementsTransition (Mode mode, MapRef source, MapRef target)
Mode mode () const
MapRef source () const
MapRef target () const
Private Attributes
Mode const mode_
MapRef const source_
MapRef const target_
Detailed Description
Definition at line 524 of file simplified-operator.h.
Member Enumeration Documentation
Mode
enum v8::internal::compiler::ElementsTransition::Mode : uint8_t
Enumerator
kFastTransition
kSlowTransition
Definition at line 526 of file simplified-operator.h.
            : uint8_t {
    kFastTransition, // simple transition, just updating the map.
    kSlowTransition // full transition, round-trip to the runtime.
  };
Constructor & Destructor Documentation
ElementsTransition()
v8::internal::compiler::ElementsTransition::ElementsTransition (Mode mode, MapRef source, MapRef target) [inline]
Definition at line 531 of file simplified-operator.h.
      : mode_(mode), source_(source), target_(target) {}
Member Function Documentation
mode()
Mode v8::internal::compiler::ElementsTransition::mode () const [inline]
Definition at line 534 of file simplified-operator.h.
{ return mode_; }
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), and v8::internal::compiler::LoadElimination::ReduceTransitionElementsKind().
source()
MapRef v8::internal::compiler::ElementsTransition::source () const [inline]
Definition at line 535 of file simplified-operator.h.
{ return source_; }
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), and v8::internal::compiler::LoadElimination::ReduceTransitionElementsKind().
target()
MapRef v8::internal::compiler::ElementsTransition::target () const [inline]
Definition at line 536 of file simplified-operator.h.
{ return target_; }
Referenced by v8::internal::compiler::LoadElimination::ComputeLoopState(), v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), and v8::internal::compiler::LoadElimination::ReduceTransitionElementsKind().
Member Data Documentation
mode_
Mode const v8::internal::compiler::ElementsTransition::mode_ [private]
Definition at line 539 of file simplified-operator.h.
source_
MapRef const v8::internal::compiler::ElementsTransition::source_ [private]
Definition at line 540 of file simplified-operator.h.
target_
MapRef const v8::internal::compiler::ElementsTransition::target_ [private]
Definition at line 541 of file simplified-operator.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/simplified-operator.h