v8::internal::RelocInfo Class Reference
#include <reloc-info.h>
Public Types
enum Mode : int8_t {
NO_INFO
, CODE_TARGET
, RELATIVE_CODE_TARGET
, COMPRESSED_EMBEDDED_OBJECT
,
FULL_EMBEDDED_OBJECT
, WASM_CALL
, WASM_STUB_CALL
, WASM_CODE_POINTER_TABLE_ENTRY
,
WASM_CANONICAL_SIG_ID
, EXTERNAL_REFERENCE
, INTERNAL_REFERENCE
, INTERNAL_REFERENCE_ENCODED
,
JS_DISPATCH_HANDLE
, OFF_HEAP_TARGET
, NEAR_BUILTIN_ENTRY
, CONST_POOL
,
VENEER_POOL
, DEOPT_SCRIPT_OFFSET
, DEOPT_INLINING_ID
, DEOPT_REASON
,
DEOPT_ID
, DEOPT_NODE_ID
, PC_JUMP
, NUMBER_OF_MODES
,
LAST_CODE_TARGET_MODE = RELATIVE_CODE_TARGET
, FIRST_REAL_RELOC_MODE = CODE_TARGET
, LAST_REAL_RELOC_MODE = VENEER_POOL
, FIRST_EMBEDDED_OBJECT_RELOC_MODE = COMPRESSED_EMBEDDED_OBJECT
,
LAST_EMBEDDED_OBJECT_RELOC_MODE = FULL_EMBEDDED_OBJECT
, LAST_GCED_ENUM = LAST_EMBEDDED_OBJECT_RELOC_MODE
, FIRST_BUILTIN_ENTRY_MODE = OFF_HEAP_TARGET
, LAST_BUILTIN_ENTRY_MODE = NEAR_BUILTIN_ENTRY
,
FIRST_SHAREABLE_RELOC_MODE = WASM_CALL
 }
Public Member Functions
RelocInfo ()=default
RelocInfo (Address pc, Mode rmode, intptr_t data, Address constant_pool=kNullAddress)
RelocInfo (Address pc, Mode rmode)
Address pc () const
Mode rmode () const
Address constant_pool () const
intptr_t data () const
bool IsCodedSpecially ()
bool IsInConstantPool ()
Address wasm_call_address () const
Address wasm_stub_call_address () const
V8_EXPORT_PRIVATE uint32_t wasm_canonical_sig_id () const
WasmCodePointer wasm_code_pointer_table_entry () const
uint32_t wasm_call_tag () const
void set_off_heap_target_address (Address target, ICacheFlushMode icache_flush_mode=FLUSH_ICACHE_IF_NEEDED)
Address target_address ()
Tagged< HeapObject > target_object (PtrComprCageBase cage_base)
DirectHandle< HeapObject > target_object_handle (Assembler *origin)
Builtin target_builtin_at (Assembler *origin)
Address target_off_heap_target ()
Address constant_pool_entry_address ()
Address target_address_address ()
bool HasTargetAddressAddress () const
int target_address_size ()
Address target_external_reference ()
Address target_internal_reference ()
Address target_internal_reference_address ()
JSDispatchHandle js_dispatch_handle ()
template<typename ObjectVisitor >
void Visit (Tagged< InstructionStream > host, ObjectVisitor *visitor)
Static Public Member Functions
static constexpr bool IsRealRelocMode (Mode mode)
static constexpr bool IsGCRelocMode (Mode mode)
static constexpr bool IsShareableRelocMode (Mode mode)
static constexpr bool IsCodeTarget (Mode mode)
static constexpr bool IsCodeTargetMode (Mode mode)
static constexpr bool IsRelativeCodeTarget (Mode mode)
static constexpr bool IsFullEmbeddedObject (Mode mode)
static constexpr bool IsCompressedEmbeddedObject (Mode mode)
static constexpr bool IsEmbeddedObjectMode (Mode mode)
static constexpr bool IsWasmCall (Mode mode)
static constexpr bool IsWasmStubCall (Mode mode)
static constexpr bool IsWasmCanonicalSigId (Mode mode)
static constexpr bool IsWasmCodePointerTableEntry (Mode mode)
static constexpr bool IsConstPool (Mode mode)
static constexpr bool IsVeneerPool (Mode mode)
static constexpr bool IsDeoptPosition (Mode mode)
static constexpr bool IsDeoptReason (Mode mode)
static constexpr bool IsDeoptId (Mode mode)
static constexpr bool IsDeoptNodeId (Mode mode)
static constexpr bool IsExternalReference (Mode mode)
static constexpr bool IsInternalReference (Mode mode)
static constexpr bool IsInternalReferenceEncoded (Mode mode)
static constexpr bool IsOffHeapTarget (Mode mode)
static constexpr bool IsNearBuiltinEntry (Mode mode)
static constexpr bool IsBuiltinEntryMode (Mode mode)
static constexpr bool IsJSDispatchHandle (Mode mode)
static constexpr bool IsNoInfo (Mode mode)
static bool IsOnlyForSerializer (Mode mode)
static constexpr int ModeMask (Mode mode)
static bool OffHeapTargetIsCodedSpecially ()
static constexpr int AllRealModesMask ()
static int EmbeddedObjectModeMask ()
static int JSDispatchHandleModeMask ()
static int PostCodegenRelocationMask ()
Static Public Attributes
static constexpr int kMinRelocCommentSize = 2 + kSystemPointerSize
static constexpr int kMaxCallSize = 6
static constexpr int kMaxSmallPCDelta = detail::kSmallPCDeltaMask
static const int kApplyMask
Protected Attributes
Address pc_
Mode rmode_
intptr_t data_ = 0
Address constant_pool_ = kNullAddress
Friends
template<typename RelocIteratorType >
class RelocIteratorBase
Detailed Description
Definition at line 94 of file reloc-info.h.
Member Enumeration Documentation
Mode
enum v8::internal::RelocInfo::Mode : int8_t
Enumerator
NO_INFO
CODE_TARGET
RELATIVE_CODE_TARGET
COMPRESSED_EMBEDDED_OBJECT
FULL_EMBEDDED_OBJECT
WASM_CALL
WASM_STUB_CALL
WASM_CODE_POINTER_TABLE_ENTRY
WASM_CANONICAL_SIG_ID
EXTERNAL_REFERENCE
INTERNAL_REFERENCE
INTERNAL_REFERENCE_ENCODED
JS_DISPATCH_HANDLE
OFF_HEAP_TARGET
NEAR_BUILTIN_ENTRY
CONST_POOL
VENEER_POOL
DEOPT_SCRIPT_OFFSET
DEOPT_INLINING_ID
DEOPT_REASON
DEOPT_ID
DEOPT_NODE_ID
PC_JUMP
NUMBER_OF_MODES
LAST_CODE_TARGET_MODE
FIRST_REAL_RELOC_MODE
LAST_REAL_RELOC_MODE
FIRST_EMBEDDED_OBJECT_RELOC_MODE
LAST_EMBEDDED_OBJECT_RELOC_MODE
LAST_GCED_ENUM
FIRST_BUILTIN_ENTRY_MODE
LAST_BUILTIN_ENTRY_MODE
FIRST_SHAREABLE_RELOC_MODE
Definition at line 106 of file reloc-info.h.
            : int8_t {
    // Please note the order is important (see IsRealRelocMode, IsGCRelocMode,
    // and IsShareableRelocMode predicates below).
    NO_INFO, // Never recorded value. Most common one, hence value 0.
    CODE_TARGET,
    // TODO(ishell): rename to NEAR_CODE_TARGET.
    RELATIVE_CODE_TARGET, // LAST_CODE_TARGET_MODE
    COMPRESSED_EMBEDDED_OBJECT,
    FULL_EMBEDDED_OBJECT, // LAST_GCED_ENUM
    WASM_CALL, // FIRST_SHAREABLE_RELOC_MODE
    WASM_STUB_CALL,
    WASM_CODE_POINTER_TABLE_ENTRY,
    WASM_CANONICAL_SIG_ID,
    EXTERNAL_REFERENCE, // The address of an external C++ function.
    INTERNAL_REFERENCE, // An address inside the same function.
    // Encoded internal reference, used only on RISCV64, RISCV32, MIPS64
    // and PPC.
    INTERNAL_REFERENCE_ENCODED,
    // An integer JSDispatchHandle, referring to an entry in the
    // JSDispatchTable.
    JS_DISPATCH_HANDLE,
    // An off-heap instruction stream target. See:
    // https://docs.google.com/document/d/1XmiXT54FQ0qqroWzRc8nzrpSSo_xoyFRkVgmonONEJk
    // TODO(ishell): rename to BUILTIN_ENTRY.
    OFF_HEAP_TARGET, // FIRST_BUILTIN_ENTRY_MODE
    // An un-embedded off-heap instruction stream target.
    // See http://crbug.com/v8/11527 for details.
    NEAR_BUILTIN_ENTRY, // LAST_BUILTIN_ENTRY_MODE
    // Marks constant and veneer pools. Only used on ARM and ARM64.
    // They use a custom noncompact encoding.
    CONST_POOL,
    VENEER_POOL,
    DEOPT_SCRIPT_OFFSET,
    DEOPT_INLINING_ID, // Deoptimization source position.
    DEOPT_REASON, // Deoptimization reason index.
    DEOPT_ID, // Deoptimization inlining id.
    DEOPT_NODE_ID, // Id of the node that caused deoptimization. This
                        // information is only recorded in debug builds.
    // This is not an actual reloc mode, but used to encode a long pc jump that
    // cannot be encoded as part of another record.
    PC_JUMP,
    // Pseudo-types
    NUMBER_OF_MODES,
    LAST_CODE_TARGET_MODE = RELATIVE_CODE_TARGET,
    FIRST_REAL_RELOC_MODE = CODE_TARGET,
    LAST_REAL_RELOC_MODE = VENEER_POOL,
    FIRST_EMBEDDED_OBJECT_RELOC_MODE = COMPRESSED_EMBEDDED_OBJECT,
    LAST_EMBEDDED_OBJECT_RELOC_MODE = FULL_EMBEDDED_OBJECT,
    LAST_GCED_ENUM = LAST_EMBEDDED_OBJECT_RELOC_MODE,
    FIRST_BUILTIN_ENTRY_MODE = OFF_HEAP_TARGET,
    LAST_BUILTIN_ENTRY_MODE = NEAR_BUILTIN_ENTRY,
    FIRST_SHAREABLE_RELOC_MODE = WASM_CALL,
  };
Constructor & Destructor Documentation
RelocInfo() [1/3]
v8::internal::RelocInfo::RelocInfo () [default]
RelocInfo() [2/3]
v8::internal::RelocInfo::RelocInfo (Address pc, Mode rmode, intptr_t data, Address constant_pool = kNullAddress) [inline]
Definition at line 176 of file reloc-info.h.
      : pc_(pc), rmode_(rmode), data_(data), constant_pool_(constant_pool) {
    DCHECK_IMPLIES(!COMPRESS_POINTERS_BOOL,
                   rmode != COMPRESSED_EMBEDDED_OBJECT);
  }
References COMPRESS_POINTERS_BOOL, COMPRESSED_EMBEDDED_OBJECT, DCHECK_IMPLIES, and rmode().
RelocInfo() [3/3]
v8::internal::RelocInfo::RelocInfo (Address pc, Mode rmode) [inline]
Definition at line 184 of file reloc-info.h.
: RelocInfo(pc, rmode, 0) {}
Member Function Documentation
AllRealModesMask()
static constexpr int v8::internal::RelocInfo::AllRealModesMask () [inline], [static], [constexpr]
Definition at line 372 of file reloc-info.h.
                                          {
    constexpr Mode kFirstUnrealRelocMode =
        static_cast<Mode>(RelocInfo::LAST_REAL_RELOC_MODE + 1);
    return (ModeMask(kFirstUnrealRelocMode) - 1) &
           ~(ModeMask(RelocInfo::FIRST_REAL_RELOC_MODE) - 1);
  }
References FIRST_REAL_RELOC_MODE, LAST_REAL_RELOC_MODE, and ModeMask().
Referenced by v8::internal::Code::IsIsolateIndependent().
constant_pool()
Address v8::internal::RelocInfo::constant_pool () const [inline]
Definition at line 278 of file reloc-info.h.
{ return constant_pool_; }
References constant_pool_.
Referenced by v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::SetWasmCalleeTag().
constant_pool_entry_address()
Address v8::internal::RelocInfo::constant_pool_entry_address () [inline]
Definition at line 89 of file assembler-arm-inl.h.
                                               {
  DCHECK(IsInConstantPool());
  return Assembler::constant_pool_entry_address(pc_, constant_pool_);
}
References constant_pool_, v8::internal::Assembler::constant_pool_entry_address(), v8::internal::DCHECK(), IsInConstantPool(), and pc_.
Referenced by v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::GetWasmCalleeTag(), v8::internal::MarkCompactCollector::ProcessRelocInfo(), v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::SetWasmCalleeTag(), and target_address_address().
data()
intptr_t v8::internal::RelocInfo::data () const [inline]
Definition at line 279 of file reloc-info.h.
{ return data_; }
References data_.
Referenced by v8::internal::ProfilerListener::AttachDeoptInlinedFrames(), v8::internal::Deoptimizer::GetDeoptInfo(), and v8::internal::RelocInfoWriter::Write().
EmbeddedObjectModeMask()
static int v8::internal::RelocInfo::EmbeddedObjectModeMask () [inline], [static]
Definition at line 379 of file reloc-info.h.
                                      {
    return ModeMask(RelocInfo::FULL_EMBEDDED_OBJECT) |
           ModeMask(RelocInfo::COMPRESSED_EMBEDDED_OBJECT);
  }
References COMPRESSED_EMBEDDED_OBJECT, FULL_EMBEDDED_OBJECT, and ModeMask().
Referenced by v8::internal::compiler::CheckNoDeprecatedMaps(), v8::internal::Code::ClearEmbeddedObjectsAndJSDispatchHandles(), v8::internal::maglev::MaglevCodeGenerator::CollectRetainedMaps(), v8::internal::OptimizedCompilationJob::CollectRetainedMaps(), and v8::internal::ObjectStatsCollectorImpl::RecordVirtualCodeDetails().
HasTargetAddressAddress()
bool v8::internal::RelocInfo::HasTargetAddressAddress () const
Definition at line 324 of file reloc-info.cc.
                                              {
  // TODO(jgruber): Investigate whether WASM_CALL is still appropriate on
  // non-intel platforms now that wasm code is no longer on the heap.
#if defined(V8_TARGET_ARCH_IA32) || defined(V8_TARGET_ARCH_X64)
  static constexpr int kTargetAddressAddressModeMask =
      ModeMask(CODE_TARGET) | ModeMask(FULL_EMBEDDED_OBJECT) |
      ModeMask(COMPRESSED_EMBEDDED_OBJECT) | ModeMask(EXTERNAL_REFERENCE) |
      ModeMask(OFF_HEAP_TARGET) | ModeMask(WASM_CALL) |
      ModeMask(WASM_STUB_CALL);
#else
  static constexpr int kTargetAddressAddressModeMask =
      ModeMask(CODE_TARGET) | ModeMask(RELATIVE_CODE_TARGET) |
      ModeMask(FULL_EMBEDDED_OBJECT) | ModeMask(EXTERNAL_REFERENCE) |
      ModeMask(OFF_HEAP_TARGET) | ModeMask(WASM_CALL);
#endif
  return (ModeMask(rmode_) & kTargetAddressAddressModeMask) != 0;
}
References CODE_TARGET, COMPRESSED_EMBEDDED_OBJECT, EXTERNAL_REFERENCE, FULL_EMBEDDED_OBJECT, ModeMask(), OFF_HEAP_TARGET, RELATIVE_CODE_TARGET, rmode_, WASM_CALL, and WASM_STUB_CALL.
Referenced by v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::SetWasmCalleeTag(), and target_address_address().
IsBuiltinEntryMode()
static constexpr bool v8::internal::RelocInfo::IsBuiltinEntryMode (Mode mode) [inline], [static], [constexpr]
Definition at line 251 of file reloc-info.h.
                                                      {
    return base::IsInRange(mode, FIRST_BUILTIN_ENTRY_MODE,
                           LAST_BUILTIN_ENTRY_MODE);
  }
References FIRST_BUILTIN_ENTRY_MODE, LAST_BUILTIN_ENTRY_MODE, and mode().
Referenced by Visit().
IsCodedSpecially()
bool v8::internal::RelocInfo::IsCodedSpecially ()
Definition at line 193 of file assembler-riscv.cc.
                                 {
  // The deserializer needs to know whether a pointer is specially coded. Being
  // specially coded on RISC-V means that it is a lui/addi instruction, and that
  // is always the case inside code objects.
  return true;
}
IsCodeTarget()
static constexpr bool v8::internal::RelocInfo::IsCodeTarget (Mode mode) [inline], [static], [constexpr]
Definition at line 197 of file reloc-info.h.
{ return mode == CODE_TARGET; }
References CODE_TARGET, and mode().
Referenced by v8::internal::WritableRelocInfo::set_target_object(), target_object(), and target_object_handle().
IsCodeTargetMode()
static constexpr bool v8::internal::RelocInfo::IsCodeTargetMode (Mode mode) [inline], [static], [constexpr]
Definition at line 198 of file reloc-info.h.
                                                    {
    return mode <= LAST_CODE_TARGET_MODE;
  }
References LAST_CODE_TARGET_MODE, and mode().
Referenced by v8::internal::Code::IsIsolateIndependent(), v8::internal::MarkingVisitorBase< ReferenceSummarizerMarkingVisitor >::ProcessWeakHeapObject(), v8::internal::InstructionStream::RelocateFromDesc(), v8::internal::InstructionStream::RelocateFromDescWriteBarriers(), v8::internal::SetupIsolateDelegate::ReplacePlaceholders(), set_off_heap_target_address(), v8::internal::WritableRelocInfo::set_target_address(), target_address(), v8::internal::UpdateTypedSlotHelper::UpdateCodeTarget(), Visit(), and v8::internal::RecordMigratedSlotVisitor::VisitCodeTarget().
IsCompressedEmbeddedObject()
static constexpr bool v8::internal::RelocInfo::IsCompressedEmbeddedObject (Mode mode) [inline], [static], [constexpr]
Definition at line 207 of file reloc-info.h.
                                                              {
    return COMPRESS_POINTERS_BOOL && mode == COMPRESSED_EMBEDDED_OBJECT;
  }
References COMPRESS_POINTERS_BOOL, COMPRESSED_EMBEDDED_OBJECT, and mode().
Referenced by v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::GetWasmCalleeTag(), v8::internal::MacroAssembler::li(), and v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::SetWasmCalleeTag().
IsConstPool()
static constexpr bool v8::internal::RelocInfo::IsConstPool (Mode mode) [inline], [static], [constexpr]
Definition at line 224 of file reloc-info.h.
{ return mode == CONST_POOL; }
References CONST_POOL, and mode().
Referenced by v8::internal::RelocIteratorBase< RelocInfoT >::next(), and v8::internal::RelocInfoWriter::Write().
IsDeoptId()
static constexpr bool v8::internal::RelocInfo::IsDeoptId (Mode mode) [inline], [static], [constexpr]
Definition at line 232 of file reloc-info.h.
{ return mode == DEOPT_ID; }
References DEOPT_ID, and mode().
Referenced by v8::internal::RelocIteratorBase< RelocInfoT >::next(), and v8::internal::RelocInfoWriter::Write().
IsDeoptNodeId()
static constexpr bool v8::internal::RelocInfo::IsDeoptNodeId (Mode mode) [inline], [static], [constexpr]
Definition at line 233 of file reloc-info.h.
                                                 {
    return mode == DEOPT_NODE_ID;
  }
References DEOPT_NODE_ID, and mode().
Referenced by v8::internal::RelocIteratorBase< RelocInfoT >::next(), and v8::internal::RelocInfoWriter::Write().
IsDeoptPosition()
static constexpr bool v8::internal::RelocInfo::IsDeoptPosition (Mode mode) [inline], [static], [constexpr]
Definition at line 226 of file reloc-info.h.
                                                   {
    return mode == DEOPT_SCRIPT_OFFSET || mode == DEOPT_INLINING_ID;
  }
References DEOPT_INLINING_ID, DEOPT_SCRIPT_OFFSET, and mode().
Referenced by v8::internal::RelocIteratorBase< RelocInfoT >::next(), and v8::internal::RelocInfoWriter::Write().
IsDeoptReason()
static constexpr bool v8::internal::RelocInfo::IsDeoptReason (Mode mode) [inline], [static], [constexpr]
Definition at line 229 of file reloc-info.h.
                                                 {
    return mode == DEOPT_REASON;
  }
References DEOPT_REASON, and mode().
Referenced by v8::internal::RelocIteratorBase< RelocInfoT >::next(), and v8::internal::RelocInfoWriter::Write().
IsEmbeddedObjectMode()
static constexpr bool v8::internal::RelocInfo::IsEmbeddedObjectMode (Mode mode) [inline], [static], [constexpr]
Definition at line 210 of file reloc-info.h.
                                                        {
    return base::IsInRange(mode, FIRST_EMBEDDED_OBJECT_RELOC_MODE,
                           LAST_EMBEDDED_OBJECT_RELOC_MODE);
  }
References FIRST_EMBEDDED_OBJECT_RELOC_MODE, LAST_EMBEDDED_OBJECT_RELOC_MODE, and mode().
Referenced by v8::internal::compiler::CheckNoDeprecatedMaps(), v8::internal::Code::ClearEmbeddedObjectsAndJSDispatchHandles(), v8::internal::maglev::MaglevCodeGenerator::CollectRetainedMaps(), v8::internal::OptimizedCompilationJob::CollectRetainedMaps(), v8::internal::Immediate::Immediate(), v8::internal::Operand::Operand(), v8::internal::ObjectStatsCollectorImpl::RecordVirtualCodeDetails(), v8::internal::InstructionStream::RelocateFromDesc(), v8::internal::InstructionStream::RelocateFromDescWriteBarriers(), v8::internal::SetupIsolateDelegate::ReplacePlaceholders(), v8::internal::UpdateTypedSlotHelper::UpdateEmbeddedPointer(), Visit(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitEmbeddedPointer(), and v8::internal::RecordMigratedSlotVisitor::VisitEmbeddedPointer().
IsExternalReference()
static constexpr bool v8::internal::RelocInfo::IsExternalReference (Mode mode) [inline], [static], [constexpr]
Definition at line 236 of file reloc-info.h.
                                                       {
    return mode == EXTERNAL_REFERENCE;
  }
References EXTERNAL_REFERENCE, and mode().
Referenced by Visit().
IsFullEmbeddedObject()
static constexpr bool v8::internal::RelocInfo::IsFullEmbeddedObject (Mode mode) [inline], [static], [constexpr]
Definition at line 204 of file reloc-info.h.
                                                        {
    return mode == FULL_EMBEDDED_OBJECT;
  }
References FULL_EMBEDDED_OBJECT, and mode().
Referenced by v8::internal::MacroAssembler::li(), v8::internal::WritableRelocInfo::set_target_object(), target_object(), and target_object_handle().
IsGCRelocMode()
static constexpr bool v8::internal::RelocInfo::IsGCRelocMode (Mode mode) [inline], [static], [constexpr]
Definition at line 190 of file reloc-info.h.
                                                 {
    return mode <= LAST_GCED_ENUM;
  }
References LAST_GCED_ENUM, and mode().
IsInConstantPool()
bool v8::internal::RelocInfo::IsInConstantPool ()
Definition at line 200 of file assembler-riscv.cc.
{ return false; }
Referenced by constant_pool_entry_address(), and v8::internal::MarkCompactCollector::ProcessRelocInfo().
IsInternalReference()
static constexpr bool v8::internal::RelocInfo::IsInternalReference (Mode mode) [inline], [static], [constexpr]
Definition at line 239 of file reloc-info.h.
                                                       {
    return mode == INTERNAL_REFERENCE;
  }
References INTERNAL_REFERENCE, and mode().
Referenced by v8::internal::WritableRelocInfo::apply(), v8::internal::Assembler::RelocateInternalReference(), and Visit().
IsInternalReferenceEncoded()
static constexpr bool v8::internal::RelocInfo::IsInternalReferenceEncoded (Mode mode) [inline], [static], [constexpr]
Definition at line 242 of file reloc-info.h.
                                                              {
    return mode == INTERNAL_REFERENCE_ENCODED;
  }
References INTERNAL_REFERENCE_ENCODED, and mode().
Referenced by v8::internal::Assembler::RelocateInternalReference(), and Visit().
IsJSDispatchHandle()
static constexpr bool v8::internal::RelocInfo::IsJSDispatchHandle (Mode mode) [inline], [static], [constexpr]
Definition at line 255 of file reloc-info.h.
                                                      {
    return mode == JS_DISPATCH_HANDLE;
  }
References JS_DISPATCH_HANDLE, and mode().
Referenced by v8::internal::MacroAssembler::li(), v8::internal::WritableRelocInfo::set_js_dispatch_handle(), and Visit().
IsNearBuiltinEntry()
static constexpr bool v8::internal::RelocInfo::IsNearBuiltinEntry (Mode mode) [inline], [static], [constexpr]
Definition at line 248 of file reloc-info.h.
                                                      {
    return mode == NEAR_BUILTIN_ENTRY;
  }
References mode(), and NEAR_BUILTIN_ENTRY.
Referenced by v8::internal::InstructionStream::RelocateFromDesc(), v8::internal::Assembler::RelocateRelativeReference(), and v8::internal::WritableRelocInfo::set_target_address().
IsNoInfo()
static constexpr bool v8::internal::RelocInfo::IsNoInfo (Mode mode) [inline], [static], [constexpr]
Definition at line 258 of file reloc-info.h.
{ return mode == NO_INFO; }
References mode(), and NO_INFO.
Referenced by v8::internal::compiler::InstructionSequence::AddImmediate(), v8::internal::Assembler::ConstantPoolAddEntry(), v8::internal::Assembler::emit(), v8::internal::Assembler::emit_w(), v8::internal::Immediate::is_int16(), v8::internal::Immediate::is_int8(), v8::internal::Immediate::is_uint16(), v8::internal::Immediate::is_uint8(), v8::internal::Immediate::is_zero(), v8::internal::Assembler::MustUseReg(), v8::internal::MacroAssembler::near_call(), v8::internal::MacroAssembler::near_jump(), v8::internal::Operand::Operand(), and v8::internal::AssemblerBase::ShouldRecordRelocInfo().
IsOffHeapTarget()
static constexpr bool v8::internal::RelocInfo::IsOffHeapTarget (Mode mode) [inline], [static], [constexpr]
Definition at line 245 of file reloc-info.h.
                                                   {
    return mode == OFF_HEAP_TARGET;
  }
References mode(), and OFF_HEAP_TARGET.
Referenced by target_off_heap_target().
IsOnlyForSerializer()
static bool v8::internal::RelocInfo::IsOnlyForSerializer (Mode mode) [inline], [static]
Definition at line 260 of file reloc-info.h.
                                             {
#ifdef V8_TARGET_ARCH_IA32
    // On ia32, inlined off-heap trampolines must be relocated.
    DCHECK_NE((kApplyMask & ModeMask(OFF_HEAP_TARGET)), 0);
    DCHECK_EQ((kApplyMask & ModeMask(EXTERNAL_REFERENCE)), 0);
    return mode == EXTERNAL_REFERENCE;
#else
    DCHECK_EQ((kApplyMask & ModeMask(OFF_HEAP_TARGET)), 0);
    DCHECK_EQ((kApplyMask & ModeMask(EXTERNAL_REFERENCE)), 0);
    return mode == EXTERNAL_REFERENCE || mode == OFF_HEAP_TARGET;
#endif
  }
References DCHECK_EQ, DCHECK_NE, EXTERNAL_REFERENCE, kApplyMask, mode(), ModeMask(), and OFF_HEAP_TARGET.
Referenced by v8::internal::AssemblerBase::ShouldRecordRelocInfo().
IsRealRelocMode()
static constexpr bool v8::internal::RelocInfo::IsRealRelocMode (Mode mode) [inline], [static], [constexpr]
Definition at line 186 of file reloc-info.h.
                                                   {
    return mode >= FIRST_REAL_RELOC_MODE && mode <= LAST_REAL_RELOC_MODE;
  }
References FIRST_REAL_RELOC_MODE, LAST_REAL_RELOC_MODE, and mode().
IsRelativeCodeTarget()
static constexpr bool v8::internal::RelocInfo::IsRelativeCodeTarget (Mode mode) [inline], [static], [constexpr]
Definition at line 201 of file reloc-info.h.
                                                        {
    return mode == RELATIVE_CODE_TARGET;
  }
References mode(), and RELATIVE_CODE_TARGET.
Referenced by v8::internal::WritableRelocInfo::apply(), v8::internal::Assembler::RelocateRelativeReference(), v8::internal::SetupIsolateDelegate::ReplacePlaceholders(), target_address_address(), and target_object_handle().
IsShareableRelocMode()
static constexpr bool v8::internal::RelocInfo::IsShareableRelocMode (Mode mode) [inline], [static], [constexpr]
Definition at line 193 of file reloc-info.h.
                                                        {
    return mode == RelocInfo::NO_INFO ||
           mode >= RelocInfo::FIRST_SHAREABLE_RELOC_MODE;
  }
References FIRST_SHAREABLE_RELOC_MODE, mode(), and NO_INFO.
Referenced by v8::internal::Assembler::ConstantPoolAddEntry().
IsVeneerPool()
static constexpr bool v8::internal::RelocInfo::IsVeneerPool (Mode mode) [inline], [static], [constexpr]
Definition at line 225 of file reloc-info.h.
{ return mode == VENEER_POOL; }
References mode(), and VENEER_POOL.
Referenced by v8::internal::RelocIteratorBase< RelocInfoT >::next(), and v8::internal::RelocInfoWriter::Write().
IsWasmCall()
static constexpr bool v8::internal::RelocInfo::IsWasmCall (Mode mode) [inline], [static], [constexpr]
Definition at line 214 of file reloc-info.h.
{ return mode == WASM_CALL; }
References mode(), and WASM_CALL.
Referenced by v8::internal::wasm::NativeModule::AddCodeWithCodeSpace(), v8::internal::wasm::WasmImportWrapperCache::ModificationScope::AddWrapper(), v8::internal::Assembler::ConstantPoolAddEntry(), v8::internal::WritableRelocInfo::set_target_address(), and target_address().
IsWasmCanonicalSigId()
static constexpr bool v8::internal::RelocInfo::IsWasmCanonicalSigId (Mode mode) [inline], [static], [constexpr]
Definition at line 218 of file reloc-info.h.
                                                        {
    return mode == WASM_CANONICAL_SIG_ID;
  }
References mode(), and WASM_CANONICAL_SIG_ID.
Referenced by v8::internal::MacroAssembler::li().
IsWasmCodePointerTableEntry()
static constexpr bool v8::internal::RelocInfo::IsWasmCodePointerTableEntry (Mode mode) [inline], [static], [constexpr]
Definition at line 221 of file reloc-info.h.
                                                               {
    return mode == WASM_CODE_POINTER_TABLE_ENTRY;
  }
References mode(), and WASM_CODE_POINTER_TABLE_ENTRY.
Referenced by v8::internal::wasm::NativeModule::AddCodeForTesting(), v8::internal::wasm::NativeModule::AddCodeWithCodeSpace(), and v8::internal::MacroAssembler::li().
IsWasmStubCall()
static constexpr bool v8::internal::RelocInfo::IsWasmStubCall (Mode mode) [inline], [static], [constexpr]
Definition at line 215 of file reloc-info.h.
                                                  {
    return mode == WASM_STUB_CALL;
  }
References mode(), and WASM_STUB_CALL.
Referenced by v8::internal::wasm::NativeModule::AddCodeForTesting(), v8::internal::wasm::NativeModule::AddCodeWithCodeSpace(), v8::internal::wasm::WasmImportWrapperCache::ModificationScope::AddWrapper(), v8::internal::Assembler::ConstantPoolAddEntry(), v8::internal::InstructionStream::RelocateFromDesc(), and target_address().
js_dispatch_handle()
JSDispatchHandle v8::internal::RelocInfo::js_dispatch_handle () [inline]
Definition at line 152 of file assembler-arm-inl.h.
                                               {
  DCHECK(rmode_ == JS_DISPATCH_HANDLE);
  return JSDispatchHandle(Assembler::uint32_constant_at(pc_, constant_pool_));
}
References constant_pool_, v8::internal::DCHECK(), JS_DISPATCH_HANDLE, pc_, rmode_, and v8::internal::Assembler::uint32_constant_at().
Referenced by Visit().
JSDispatchHandleModeMask()
static int v8::internal::RelocInfo::JSDispatchHandleModeMask () [inline], [static]
Definition at line 384 of file reloc-info.h.
                                        {
    return ModeMask(RelocInfo::JS_DISPATCH_HANDLE);
  }
References JS_DISPATCH_HANDLE, and ModeMask().
Referenced by v8::internal::Code::ClearEmbeddedObjectsAndJSDispatchHandles().
ModeMask()
static constexpr int v8::internal::RelocInfo::ModeMask (Mode mode) [inline], [static], [constexpr]
Definition at line 273 of file reloc-info.h.
{ return 1 << mode; }
References mode().
Referenced by v8::internal::wasm::NativeModule::AddCodeForTesting(), v8::internal::wasm::NativeModule::AddCodeWithCodeSpace(), AllRealModesMask(), v8::internal::ProfilerListener::AttachDeoptInlinedFrames(), v8::internal::wasm::NativeModuleDeserializer::CopyAndRelocate(), EmbeddedObjectModeMask(), v8::internal::anonymous_namespace{embedded-data.cc}::FinalizeEmbeddedCodeTargets(), v8::internal::Deoptimizer::GetDeoptInfo(), HasTargetAddressAddress(), v8::internal::Code::IsIsolateIndependent(), IsOnlyForSerializer(), JSDispatchHandleModeMask(), PostCodegenRelocationMask(), v8::internal::SetupIsolateDelegate::ReplacePlaceholders(), and v8::internal::wasm::NativeModuleSerializer::WriteCode().
OffHeapTargetIsCodedSpecially()
bool v8::internal::RelocInfo::OffHeapTargetIsCodedSpecially () [static]
Definition at line 241 of file reloc-info.cc.
                                              {
#if defined(V8_TARGET_ARCH_ARM) || defined(V8_TARGET_ARCH_ARM64) || \
    defined(V8_TARGET_ARCH_X64)
  return false;
#elif defined(V8_TARGET_ARCH_IA32) || defined(V8_TARGET_ARCH_MIPS64) || \
    defined(V8_TARGET_ARCH_PPC64) || defined(V8_TARGET_ARCH_S390X) || \
    defined(V8_TARGET_ARCH_RISCV64) || defined(V8_TARGET_ARCH_LOONG64) || \
    defined(V8_TARGET_ARCH_RISCV32)
  return true;
#endif
}
pc()
Address v8::internal::RelocInfo::pc () const [inline]
Definition at line 276 of file reloc-info.h.
{ return pc_; }
References pc_.
Referenced by v8::internal::Deoptimizer::GetDeoptInfo(), v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::GetWasmCalleeTag(), v8::internal::MarkCompactCollector::ProcessRelocInfo(), v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::SetWasmCalleeTag(), and v8::internal::RelocInfoWriter::Write().
PostCodegenRelocationMask()
static int v8::internal::RelocInfo::PostCodegenRelocationMask () [inline], [static]
Definition at line 391 of file reloc-info.h.
                                         {
    return ModeMask(RelocInfo::CODE_TARGET) |
           ModeMask(RelocInfo::COMPRESSED_EMBEDDED_OBJECT) |
           ModeMask(RelocInfo::FULL_EMBEDDED_OBJECT) |
           ModeMask(RelocInfo::NEAR_BUILTIN_ENTRY) |
           ModeMask(RelocInfo::WASM_STUB_CALL) |
           ModeMask(RelocInfo::RELATIVE_CODE_TARGET) | kApplyMask;
  }
References CODE_TARGET, COMPRESSED_EMBEDDED_OBJECT, FULL_EMBEDDED_OBJECT, kApplyMask, ModeMask(), NEAR_BUILTIN_ENTRY, RELATIVE_CODE_TARGET, and WASM_STUB_CALL.
Referenced by v8::internal::InstructionStream::RelocateFromDesc(), and v8::internal::InstructionStream::RelocateFromDescWriteBarriers().
rmode()
Mode v8::internal::RelocInfo::rmode () const [inline]
Definition at line 277 of file reloc-info.h.
{ return rmode_; }
References rmode_.
Referenced by v8::internal::ProfilerListener::AttachDeoptInlinedFrames(), v8::internal::anonymous_namespace{embedded-data.cc}::FinalizeEmbeddedCodeTargets(), v8::internal::Deoptimizer::GetDeoptInfo(), v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::GetWasmCalleeTag(), v8::internal::MarkCompactCollector::ProcessRelocInfo(), v8::internal::MarkingVisitorBase< ReferenceSummarizerMarkingVisitor >::ProcessWeakHeapObject(), RelocInfo(), v8::internal::SetupIsolateDelegate::ReplacePlaceholders(), v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::SetWasmCalleeTag(), v8::internal::UpdateTypedSlotHelper::UpdateCodeTarget(), v8::internal::UpdateTypedSlotHelper::UpdateEmbeddedPointer(), Visit(), v8::internal::RecordMigratedSlotVisitor::VisitCodeTarget(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitEmbeddedPointer(), v8::internal::RecordMigratedSlotVisitor::VisitEmbeddedPointer(), v8::internal::RelocInfoWriter::Write(), and v8::internal::wasm::NativeModuleSerializer::WriteCode().
set_off_heap_target_address()
void v8::internal::RelocInfo::set_off_heap_target_address (Address target, ICacheFlushMode icache_flush_mode = FLUSH_ICACHE_IF_NEEDED)
Definition at line 317 of file reloc-info.cc.
                                                                               {
  DCHECK(IsCodeTargetMode(rmode_));
  Assembler::set_target_address_at(pc_, constant_pool_, target, nullptr,
                                   icache_flush_mode);
}
References constant_pool_, v8::internal::DCHECK(), IsCodeTargetMode(), pc_, rmode_, and v8::internal::Assembler::set_target_address_at().
Referenced by v8::internal::anonymous_namespace{embedded-data.cc}::FinalizeEmbeddedCodeTargets().
target_address()
Address v8::internal::RelocInfo::target_address () [inline]
Definition at line 70 of file assembler-arm-inl.h.
                                  {
  DCHECK(IsCodeTargetMode(rmode_) || IsWasmCall(rmode_) ||
         IsWasmStubCall(rmode_));
  return Assembler::target_address_at(pc_, constant_pool_);
}
References constant_pool_, v8::internal::DCHECK(), IsCodeTargetMode(), IsWasmCall(), IsWasmStubCall(), pc_, rmode_, and v8::internal::Assembler::target_address_at().
Referenced by v8::internal::anonymous_namespace{embedded-data.cc}::FinalizeEmbeddedCodeTargets(), v8::internal::UpdateTypedSlotHelper::GetTargetObject(), v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::GetWasmCalleeTag(), v8::internal::SetupIsolateDelegate::ReplacePlaceholders(), v8::internal::UpdateTypedSlotHelper::UpdateCodeTarget(), v8::internal::ClientObjectVisitor< Visitor >::VisitCodeTarget(), v8::internal::MarkCompactCollector::CustomRootBodyMarkingVisitor::VisitCodeTarget(), v8::internal::RecordMigratedSlotVisitor::VisitCodeTarget(), and v8::internal::IndexedReferencesExtractor::VisitCodeTarget().
target_address_address()
Address v8::internal::RelocInfo::target_address_address () [inline]
Definition at line 76 of file assembler-arm-inl.h.
                                          {
  DCHECK(HasTargetAddressAddress());
  if (Assembler::IsMovW(Memory<int32_t>(pc_))) {
    return pc_;
  } else if (Assembler::IsLdrPcImmediateOffset(Memory<int32_t>(pc_))) {
    return constant_pool_entry_address();
  } else {
    DCHECK(Assembler::IsBOrBlPcImmediateOffset(Memory<int32_t>(pc_)));
    DCHECK(IsRelativeCodeTarget(rmode_));
    return pc_;
  }
}
References constant_pool_entry_address(), v8::internal::DCHECK(), HasTargetAddressAddress(), v8::internal::Assembler::IsBOrBlPcImmediateOffset(), v8::internal::Assembler::IsLdrPcImmediateOffset(), v8::internal::Assembler::IsMovW(), IsRelativeCodeTarget(), pc_, and rmode_.
Referenced by v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::GetWasmCalleeTag(), and v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::SetWasmCalleeTag().
target_address_size()
int v8::internal::RelocInfo::target_address_size () [inline]
Definition at line 94 of file assembler-arm-inl.h.
{ return kPointerSize; }
References v8::internal::kPointerSize.
target_builtin_at()
Builtin v8::internal::RelocInfo::target_builtin_at (Assembler * origin) [inline]
Definition at line 157 of file assembler-arm-inl.h.
{ UNREACHABLE(); }
References v8::internal::UNREACHABLE().
target_external_reference()
Address v8::internal::RelocInfo::target_external_reference () [inline]
Definition at line 118 of file assembler-arm-inl.h.
                                             {
  DCHECK(rmode_ == EXTERNAL_REFERENCE);
  return Assembler::target_address_at(pc_, constant_pool_);
}
References constant_pool_, v8::internal::DCHECK(), EXTERNAL_REFERENCE, pc_, rmode_, and v8::internal::Assembler::target_address_at().
Referenced by v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::GetWasmCalleeTag(), and v8::internal::wasm::NativeModuleSerializer::WriteCode().
target_internal_reference()
Address v8::internal::RelocInfo::target_internal_reference () [inline]
Definition at line 142 of file assembler-arm-inl.h.
                                             {
  DCHECK(rmode_ == INTERNAL_REFERENCE);
  return Memory<Address>(pc_);
}
References v8::internal::DCHECK(), INTERNAL_REFERENCE, pc_, and rmode_.
Referenced by v8::internal::wasm::NativeModuleSerializer::WriteCode().
target_internal_reference_address()
Address v8::internal::RelocInfo::target_internal_reference_address () [inline]
Definition at line 147 of file assembler-arm-inl.h.
                                                     {
  DCHECK(rmode_ == INTERNAL_REFERENCE);
  return pc_;
}
References v8::internal::DCHECK(), INTERNAL_REFERENCE, pc_, and rmode_.
target_object()
Tagged< HeapObject > v8::internal::RelocInfo::target_object (PtrComprCageBase cage_base) [inline]
Definition at line 96 of file assembler-arm-inl.h.
                                                                      {
  DCHECK(IsCodeTarget(rmode_) || IsFullEmbeddedObject(rmode_));
  return Cast<HeapObject>(
      Tagged<Object>(Assembler::target_address_at(pc_, constant_pool_)));
}
References constant_pool_, v8::internal::DCHECK(), IsCodeTarget(), IsFullEmbeddedObject(), pc_, rmode_, and v8::internal::Assembler::target_address_at().
Referenced by v8::internal::UpdateTypedSlotHelper::GetTargetObject(), v8::internal::SetupIsolateDelegate::ReplacePlaceholders(), v8::internal::UpdateTypedSlotHelper::UpdateEmbeddedPointer(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitEmbeddedPointer(), v8::internal::ClientObjectVisitor< Visitor >::VisitEmbeddedPointer(), v8::internal::MarkCompactCollector::CustomRootBodyMarkingVisitor::VisitEmbeddedPointer(), v8::internal::RecordMigratedSlotVisitor::VisitEmbeddedPointer(), and v8::internal::IndexedReferencesExtractor::VisitEmbeddedPointer().
target_object_handle()
DirectHandle< HeapObject > v8::internal::RelocInfo::target_object_handle (Assembler * origin) [inline]
Definition at line 102 of file assembler-arm-inl.h.
                                                                          {
  if (IsCodeTarget(rmode_) || IsFullEmbeddedObject(rmode_)) {
    return DirectHandle<HeapObject>::FromSlot(reinterpret_cast<Address*>(
        Assembler::target_address_at(pc_, constant_pool_)));
  }
  DCHECK(IsRelativeCodeTarget(rmode_));
  return origin->relative_code_target_object_handle_at(pc_);
}
References constant_pool_, v8::internal::DCHECK(), IsCodeTarget(), IsFullEmbeddedObject(), IsRelativeCodeTarget(), pc_, v8::internal::Assembler::relative_code_target_object_handle_at(), rmode_, and v8::internal::Assembler::target_address_at().
target_off_heap_target()
Address v8::internal::RelocInfo::target_off_heap_target () [inline]
Definition at line 159 of file assembler-arm-inl.h.
                                          {
  DCHECK(IsOffHeapTarget(rmode_));
  return Assembler::target_address_at(pc_, constant_pool_);
}
References constant_pool_, v8::internal::DCHECK(), IsOffHeapTarget(), pc_, rmode_, and v8::internal::Assembler::target_address_at().
Visit()
template<typename ObjectVisitor >
void v8::internal::RelocInfo::Visit (Tagged< InstructionStream > host, ObjectVisitor * visitor)
Definition at line 18 of file reloc-info-inl.h.
                                                                            {
  Mode mode = rmode();
  if (IsEmbeddedObjectMode(mode)) {
    visitor->VisitEmbeddedPointer(host, this);
  } else if (IsCodeTargetMode(mode)) {
    visitor->VisitCodeTarget(host, this);
  } else if (IsExternalReference(mode)) {
    visitor->VisitExternalReference(host, this);
  } else if (IsInternalReference(mode) || IsInternalReferenceEncoded(mode)) {
    visitor->VisitInternalReference(host, this);
  } else if (IsBuiltinEntryMode(mode)) {
    visitor->VisitOffHeapTarget(host, this);
  } else if (IsJSDispatchHandle(mode)) {
#ifdef V8_ENABLE_LEAPTIERING
    // This would need to pass the RelocInfo if dispatch entries were allowed
    // to move and we needed to update this slot.
    static_assert(!JSDispatchTable::kSupportsCompaction);
    visitor->VisitJSDispatchTableEntry(host, js_dispatch_handle());
#else
    UNREACHABLE();
#endif
  }
}
References IsBuiltinEntryMode(), IsCodeTargetMode(), IsEmbeddedObjectMode(), IsExternalReference(), IsInternalReference(), IsInternalReferenceEncoded(), IsJSDispatchHandle(), js_dispatch_handle(), mode(), rmode(), v8::internal::UNREACHABLE(), v8::internal::ObjectVisitor::VisitCodeTarget(), v8::internal::ObjectVisitor::VisitEmbeddedPointer(), v8::internal::ObjectVisitor::VisitExternalReference(), v8::internal::ObjectVisitor::VisitInternalReference(), v8::internal::ObjectVisitor::VisitJSDispatchTableEntry(), and v8::internal::ObjectVisitor::VisitOffHeapTarget().
Referenced by v8::internal::ObjectVisitor::VisitRelocInfo().
wasm_call_address()
Address v8::internal::RelocInfo::wasm_call_address () const
Definition at line 253 of file reloc-info.cc.
                                           {
  DCHECK_EQ(rmode_, WASM_CALL);
  return Assembler::target_address_at(pc_, constant_pool_);
}
References constant_pool_, DCHECK_EQ, pc_, rmode_, v8::internal::Assembler::target_address_at(), and WASM_CALL.
Referenced by v8::internal::wasm::NativeModuleSerializer::WriteCode().
wasm_call_tag()
uint32_t v8::internal::RelocInfo::wasm_call_tag () const
Definition at line 202 of file assembler-riscv.cc.
                                        {
  DCHECK(rmode_ == WASM_CALL || rmode_ == WASM_STUB_CALL);
  Instr instr = Assembler::instr_at(pc_);
  Instr instr1 = Assembler::instr_at(pc_ + 1 * kInstrSize);
  if (Assembler::IsAuipc(instr) && Assembler::IsJalr(instr1)) {
    DCHECK(reinterpret_cast<Instruction*>(pc_)->RdValue() ==
           reinterpret_cast<Instruction*>(pc_ + 4)->Rs1Value());
    return Assembler::BrachlongOffset(instr, instr1);
  } else {
    return static_cast<uint32_t>(
        Assembler::target_address_at(pc_, constant_pool_));
  }
}
References v8::internal::Assembler::BrachlongOffset(), constant_pool_, v8::internal::DCHECK(), v8::internal::Assembler::instr_at(), v8::internal::AssemblerRISCVI::IsAuipc(), v8::internal::Assembler::IsJalr(), v8::internal::kInstrSize, pc_, rmode_, v8::internal::Assembler::target_address_at(), WASM_CALL, and WASM_STUB_CALL.
Referenced by v8::internal::wasm::NativeModule::AddCodeForTesting().
wasm_canonical_sig_id()
uint32_t v8::internal::RelocInfo::wasm_canonical_sig_id () const
Definition at line 275 of file reloc-info.cc.
                                                {
  DCHECK_EQ(rmode_, WASM_CANONICAL_SIG_ID);
  return Assembler::uint32_constant_at(pc_, constant_pool_);
}
References constant_pool_, DCHECK_EQ, pc_, rmode_, v8::internal::Assembler::uint32_constant_at(), and WASM_CANONICAL_SIG_ID.
Referenced by v8::internal::wasm::NativeModuleSerializer::WriteCode().
wasm_code_pointer_table_entry()
WasmCodePointer v8::internal::RelocInfo::wasm_code_pointer_table_entry () const [inline]
Definition at line 130 of file assembler-arm-inl.h.
                                                               {
  DCHECK(rmode_ == WASM_CODE_POINTER_TABLE_ENTRY);
  return WasmCodePointer{Assembler::uint32_constant_at(pc_, constant_pool_)};
}
References constant_pool_, v8::internal::DCHECK(), pc_, rmode_, v8::internal::Assembler::uint32_constant_at(), and WASM_CODE_POINTER_TABLE_ENTRY.
Referenced by v8::internal::wasm::NativeModuleSerializer::WriteCode().
wasm_stub_call_address()
Address v8::internal::RelocInfo::wasm_stub_call_address () const
Definition at line 264 of file reloc-info.cc.
                                                {
  DCHECK_EQ(rmode_, WASM_STUB_CALL);
  return Assembler::target_address_at(pc_, constant_pool_);
}
References constant_pool_, DCHECK_EQ, pc_, rmode_, v8::internal::Assembler::target_address_at(), and WASM_STUB_CALL.
Referenced by v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::GetWasmCalleeTag(), and v8::internal::wasm::NativeModuleSerializer::WriteCode().
Friends And Related Function Documentation
RelocIteratorBase
template<typename RelocIteratorType >
friend class RelocIteratorBase [friend]
Definition at line 409 of file reloc-info.h.
Member Data Documentation
constant_pool_
Address v8::internal::RelocInfo::constant_pool_ = kNullAddress [protected]
Definition at line 406 of file reloc-info.h.
Referenced by constant_pool(), constant_pool_entry_address(), js_dispatch_handle(), v8::internal::WritableRelocInfo::set_js_dispatch_handle(), set_off_heap_target_address(), v8::internal::WritableRelocInfo::set_target_address(), v8::internal::WritableRelocInfo::set_target_external_reference(), v8::internal::WritableRelocInfo::set_target_object(), v8::internal::WritableRelocInfo::set_wasm_call_address(), v8::internal::WritableRelocInfo::set_wasm_canonical_sig_id(), v8::internal::WritableRelocInfo::set_wasm_code_pointer_table_entry(), v8::internal::WritableRelocInfo::set_wasm_stub_call_address(), target_address(), target_external_reference(), target_object(), target_object_handle(), target_off_heap_target(), wasm_call_address(), wasm_call_tag(), wasm_canonical_sig_id(), wasm_code_pointer_table_entry(), and wasm_stub_call_address().
data_
intptr_t v8::internal::RelocInfo::data_ = 0 [protected]
Definition at line 405 of file reloc-info.h.
Referenced by data().
kApplyMask
const int v8::internal::RelocInfo::kApplyMask [static]
Initial value:
=
    RelocInfo::ModeMask(RelocInfo::INTERNAL_REFERENCE) |
    RelocInfo::ModeMask(RelocInfo::INTERNAL_REFERENCE_ENCODED) |
    RelocInfo::ModeMask(RelocInfo::NEAR_BUILTIN_ENTRY) |
    RelocInfo::ModeMask(RelocInfo::RELATIVE_CODE_TARGET)
Definition at line 370 of file reloc-info.h.
Referenced by v8::internal::wasm::NativeModule::AddCodeForTesting(), v8::internal::wasm::NativeModule::AddCodeWithCodeSpace(), v8::internal::wasm::WasmImportWrapperCache::ModificationScope::AddWrapper(), IsOnlyForSerializer(), PostCodegenRelocationMask(), and v8::internal::InstructionStream::Relocate().
kMaxCallSize
constexpr int v8::internal::RelocInfo::kMaxCallSize = 6 [static], [constexpr]
Definition at line 101 of file reloc-info.h.
Referenced by v8::internal::RelocInfoWriter::Write().
kMaxSmallPCDelta
constexpr int v8::internal::RelocInfo::kMaxSmallPCDelta = detail::kSmallPCDeltaMask [static], [constexpr]
Definition at line 104 of file reloc-info.h.
kMinRelocCommentSize
constexpr int v8::internal::RelocInfo::kMinRelocCommentSize = 2 + kSystemPointerSize [static], [constexpr]
Definition at line 98 of file reloc-info.h.
pc_
Address v8::internal::RelocInfo::pc_ [protected]
Definition at line 403 of file reloc-info.h.
Referenced by v8::internal::WritableRelocInfo::apply(), constant_pool_entry_address(), js_dispatch_handle(), pc(), v8::internal::WritableRelocInfo::set_js_dispatch_handle(), set_off_heap_target_address(), v8::internal::WritableRelocInfo::set_target_address(), v8::internal::WritableRelocInfo::set_target_external_reference(), v8::internal::WritableRelocInfo::set_target_object(), v8::internal::WritableRelocInfo::set_wasm_call_address(), v8::internal::WritableRelocInfo::set_wasm_canonical_sig_id(), v8::internal::WritableRelocInfo::set_wasm_code_pointer_table_entry(), v8::internal::WritableRelocInfo::set_wasm_stub_call_address(), target_address(), target_address_address(), target_external_reference(), target_internal_reference(), target_internal_reference_address(), target_object(), target_object_handle(), target_off_heap_target(), wasm_call_address(), wasm_call_tag(), wasm_canonical_sig_id(), wasm_code_pointer_table_entry(), and wasm_stub_call_address().
rmode_
Mode v8::internal::RelocInfo::rmode_ [protected]
Definition at line 404 of file reloc-info.h.
Referenced by v8::internal::WritableRelocInfo::apply(), HasTargetAddressAddress(), js_dispatch_handle(), rmode(), v8::internal::WritableRelocInfo::set_js_dispatch_handle(), set_off_heap_target_address(), v8::internal::WritableRelocInfo::set_target_address(), v8::internal::WritableRelocInfo::set_target_external_reference(), v8::internal::WritableRelocInfo::set_target_object(), v8::internal::WritableRelocInfo::set_wasm_call_address(), v8::internal::WritableRelocInfo::set_wasm_canonical_sig_id(), v8::internal::WritableRelocInfo::set_wasm_code_pointer_table_entry(), v8::internal::WritableRelocInfo::set_wasm_stub_call_address(), target_address(), target_address_address(), target_external_reference(), target_internal_reference(), target_internal_reference_address(), target_object(), target_object_handle(), target_off_heap_target(), wasm_call_address(), wasm_call_tag(), wasm_canonical_sig_id(), wasm_code_pointer_table_entry(), and wasm_stub_call_address().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/reloc-info.h
/mnt/V8SourceCode/src/codegen/arm/assembler-arm-inl.h
/mnt/V8SourceCode/src/codegen/arm64/assembler-arm64-inl.h
/mnt/V8SourceCode/src/codegen/ia32/assembler-ia32-inl.h
/mnt/V8SourceCode/src/codegen/loong64/assembler-loong64-inl.h
/mnt/V8SourceCode/src/codegen/mips64/assembler-mips64-inl.h
/mnt/V8SourceCode/src/codegen/ppc/assembler-ppc-inl.h
/mnt/V8SourceCode/src/codegen/reloc-info-inl.h
/mnt/V8SourceCode/src/codegen/reloc-info.cc
/mnt/V8SourceCode/src/codegen/riscv/assembler-riscv-inl.h
/mnt/V8SourceCode/src/codegen/riscv/assembler-riscv.cc
/mnt/V8SourceCode/src/codegen/s390/assembler-s390-inl.h
/mnt/V8SourceCode/src/codegen/x64/assembler-x64-inl.h