cppgc::internal::MarkingStateBase Class Reference
#include <marking-state.h>
Public Member Functions
MarkingStateBase (HeapBase &, MarkingWorklists &)
virtual ~MarkingStateBase ()=default
MarkingStateBase (const MarkingStateBase &)=delete
MarkingStateBase & operator= (const MarkingStateBase &)=delete
void MarkAndPush (const void *, TraceDescriptor)
void MarkAndPush (HeapObjectHeader &)
void PushMarked (HeapObjectHeader &, TraceDescriptor desc)
virtual V8_EXPORT_PRIVATE void Publish ()
MarkingWorklists::MarkingWorklist::Local & marking_worklist ()
MarkingWorklists::NotFullyConstructedWorklist & not_fully_constructed_worklist ()
Protected Member Functions
void MarkAndPush (HeapObjectHeader &, TraceDescriptor)
bool MarkNoPush (HeapObjectHeader &)
Protected Attributes
HeapBase & heap_
MarkingWorklists::MarkingWorklist::Local marking_worklist_
MarkingWorklists::NotFullyConstructedWorklist & not_fully_constructed_worklist_
Detailed Description
Definition at line 27 of file marking-state.h.
Constructor & Destructor Documentation
MarkingStateBase() [1/2]
cppgc::internal::MarkingStateBase::MarkingStateBase (HeapBase & heap, MarkingWorklists & marking_worklists) [inline]
Definition at line 62 of file marking-state.h.
    : heap_(heap),
      marking_worklist_(*marking_worklists.marking_worklist()),
      not_fully_constructed_worklist_(
          *marking_worklists.not_fully_constructed_worklist()) {}
 MarkingStateBase()
virtual cppgc::internal::MarkingStateBase::~MarkingStateBase () [virtual], [default]
MarkingStateBase() [2/2]
cppgc::internal::MarkingStateBase::MarkingStateBase (const MarkingStateBase &) [delete]
Member Function Documentation
MarkAndPush() [1/3]
void cppgc::internal::MarkingStateBase::MarkAndPush (const void * object, TraceDescriptor desc) [inline]
Definition at line 69 of file marking-state.h.
                                                                           {
  DCHECK_NOT_NULL(object);
  MarkAndPush(
      HeapObjectHeader::FromObject(const_cast<void*>(desc.base_object_payload)),
      desc);
}
References cppgc::TraceDescriptor::base_object_payload, DCHECK_NOT_NULL, and cppgc::internal::HeapObjectHeader::FromObject().
Referenced by MarkAndPush(), v8::internal::CppMarkingState::MarkAndPush(), cppgc::internal::BasicMarkingState::ProcessEphemeron(), v8::internal::UnifiedHeapMarkingVisitorBase::Visit(), cppgc::internal::MarkingVisitorBase::Visit(), v8::internal::UnifiedHeapMarkingVisitorBase::VisitMultipleUncompressedMember(), cppgc::internal::MarkingVisitorBase::VisitMultipleUncompressedMember(), and cppgc::internal::RootMarkingVisitor::VisitRoot().
MarkAndPush() [2/3]
void cppgc::internal::MarkingStateBase::MarkAndPush (HeapObjectHeader & header) [inline]
Definition at line 96 of file marking-state.h.
                                                           {
  MarkAndPush(
      header,
      {header.ObjectStart(),
       GlobalGCInfoTable::GCInfoFromIndex(header.GetGCInfoIndex()).trace});
}
References cppgc::internal::GlobalGCInfoTable::GCInfoFromIndex(), cppgc::internal::HeapObjectHeader::GetGCInfoIndex(), MarkAndPush(), cppgc::internal::HeapObjectHeader::ObjectStart(), and cppgc::internal::GCInfo::trace.
MarkAndPush() [3/3]
void cppgc::internal::MarkingStateBase::MarkAndPush (HeapObjectHeader & header, TraceDescriptor desc) [inline], [protected]
Definition at line 76 of file marking-state.h.
                                                         {
  DCHECK_NOT_NULL(desc.callback);
  if (header.IsInConstruction<AccessMode::kAtomic>()) {
    not_fully_constructed_worklist_.Push<AccessMode::kAtomic>(&header);
  } else if (MarkNoPush(header)) {
    PushMarked(header, desc);
  }
}
References cppgc::TraceDescriptor::callback, DCHECK_NOT_NULL, cppgc::internal::HeapObjectHeader::IsInConstruction(), cppgc::internal::kAtomic, MarkNoPush(), not_fully_constructed_worklist_, cppgc::internal::MarkingWorklists::ExternalMarkingWorklist::Push(), and PushMarked().
marking_worklist()
MarkingWorklists::MarkingWorklist::Local& cppgc::internal::MarkingStateBase::marking_worklist () [inline]
Definition at line 42 of file marking-state.h.
                                                           {
    return marking_worklist_;
  }
References marking_worklist_.
Referenced by v8::internal::CppMarkingState::IsLocalEmpty(), cppgc::internal::anonymous_namespace{concurrent-marker.cc}::ConcurrentMarkingTask::ProcessWorklists(), and cppgc::internal::MarkerBase::ProcessWorklistsWithDeadline().
MarkNoPush()
bool cppgc::internal::MarkingStateBase::MarkNoPush (HeapObjectHeader & header) [inline], [protected]
Definition at line 87 of file marking-state.h.
                                                          {
  // A GC should only mark the objects that belong in its heap.
  DCHECK_EQ(&heap_, &BasePage::FromPayload(&header)->heap());
  // Never mark free space objects. This would e.g. hint to marking a promptly
  // freed backing store.
  DCHECK(!header.IsFree<AccessMode::kAtomic>());
  return header.TryMarkAtomic();
}
References DCHECK, DCHECK_EQ, cppgc::internal::BasePage::FromPayload(), heap(), heap_, cppgc::internal::HeapObjectHeader::IsFree(), cppgc::internal::kAtomic, and cppgc::internal::HeapObjectHeader::TryMarkAtomic().
Referenced by MarkAndPush(), and cppgc::internal::BasicMarkingState::ProcessWeakContainer().
not_fully_constructed_worklist()
MarkingWorklists::NotFullyConstructedWorklist& cppgc::internal::MarkingStateBase::not_fully_constructed_worklist () [inline]
Definition at line 46 of file marking-state.h.
                                   {
    return not_fully_constructed_worklist_;
  }
References not_fully_constructed_worklist_.
Referenced by cppgc::internal::MarkerBase::MarkNotFullyConstructedObjects(), cppgc::internal::MarkerBase::WriteBarrierForObject(), and cppgc::internal::MarkerBase::~MarkerBase().
operator=()
MarkingStateBase& cppgc::internal::MarkingStateBase::operator= (const MarkingStateBase &) [delete]
Publish()
void cppgc::internal::MarkingStateBase::Publish () [virtual]
Reimplemented in cppgc::internal::MutatorMarkingState, and cppgc::internal::BasicMarkingState.
Definition at line 15 of file marking-state.cc.
{ marking_worklist_.Publish(); }
References marking_worklist_.
Referenced by v8::internal::CppMarkingState::Publish(), and cppgc::internal::BasicMarkingState::Publish().
PushMarked()
void cppgc::internal::MarkingStateBase::PushMarked (HeapObjectHeader & header, TraceDescriptor desc) [inline]
Definition at line 103 of file marking-state.h.
                                                        {
  DCHECK(header.IsMarked<AccessMode::kAtomic>());
  DCHECK(!header.IsInConstruction<AccessMode::kAtomic>());
  DCHECK_NOT_NULL(desc.callback);
  marking_worklist_.Push(desc);
}
References cppgc::TraceDescriptor::callback, DCHECK, DCHECK_NOT_NULL, cppgc::internal::HeapObjectHeader::IsInConstruction(), cppgc::internal::HeapObjectHeader::IsMarked(), cppgc::internal::kAtomic, and marking_worklist_.
Referenced by MarkAndPush(), and cppgc::internal::BasicMarkingState::ProcessWeakContainer().
Member Data Documentation
heap_
HeapBase& cppgc::internal::MarkingStateBase::heap_ [protected]
Definition at line 55 of file marking-state.h.
Referenced by cppgc::internal::MutatorMarkingState::FlushDiscoveredEphemeronPairs(), and MarkNoPush().
marking_worklist_
MarkingWorklists::MarkingWorklist::Local cppgc::internal::MarkingStateBase::marking_worklist_ [protected]
Definition at line 57 of file marking-state.h.
Referenced by cppgc::internal::MutatorMarkingState::DynamicallyMarkAddress(), marking_worklist(), Publish(), and PushMarked().
not_fully_constructed_worklist_
MarkingWorklists::NotFullyConstructedWorklist& cppgc::internal::MarkingStateBase::not_fully_constructed_worklist_ [protected]
Definition at line 59 of file marking-state.h.
Referenced by cppgc::internal::MutatorMarkingState::FlushNotFullyConstructedObjects(), MarkAndPush(), not_fully_constructed_worklist(), and cppgc::internal::BasicMarkingState::ProcessWeakContainer().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/marking-state.h
/mnt/V8SourceCode/src/heap/cppgc/marking-state.cc