v8::internal::compiler::FunctionTemplateInfoRef Class Reference
#include <heap-refs.h>
Public Member Functions
IndirectHandle< FunctionTemplateInfo > object () const
bool is_signature_undefined (JSHeapBroker *broker) const
bool accept_any_receiver () const
int16_t allowed_receiver_instance_type_range_start () const
int16_t allowed_receiver_instance_type_range_end () const
Address callback (JSHeapBroker *broker) const
OptionalObjectRef callback_data (JSHeapBroker *broker) const
ZoneVector< Address > c_functions (JSHeapBroker *broker) const
ZoneVector< const CFunctionInfo * > c_signatures (JSHeapBroker *broker) const
HolderLookupResult LookupHolderOfExpectedType (JSHeapBroker *broker, MapRef receiver_map)
Detailed Description
Definition at line 988 of file heap-refs.h.
Member Function Documentation
accept_any_receiver()
bool v8::internal::compiler::FunctionTemplateInfoRef::accept_any_receiver () const
Referenced by v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), v8::internal::maglev::MaglevGraphBuilder::TryBuildCallKnownApiFunction(), and v8::internal::maglev::MaglevGraphBuilder::TryInferApiHolderValue().
allowed_receiver_instance_type_range_end()
int16_t v8::internal::compiler::FunctionTemplateInfoRef::allowed_receiver_instance_type_range_end () const
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceMegaDOMPropertyAccess().
allowed_receiver_instance_type_range_start()
int16_t v8::internal::compiler::FunctionTemplateInfoRef::allowed_receiver_instance_type_range_start () const
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceMegaDOMPropertyAccess().
c_functions()
ZoneVector< Address > v8::internal::compiler::FunctionTemplateInfoRef::c_functions (JSHeapBroker * broker) const
Definition at line 1902 of file heap-refs.cc.
                                {
  return GetCFunctions(Cast<FixedArray>(object()->GetCFunctionOverloads()),
                       broker->isolate(), broker->zone());
}
References broker(), and v8::internal::compiler::anonymous_namespace{heap-refs.cc}::GetCFunctions().
Referenced by v8::internal::compiler::fast_api_call::GetFastApiCallTarget(), v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::PushRegularApiCallInputs(), and v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall().
c_signatures()
ZoneVector< const CFunctionInfo * > v8::internal::compiler::FunctionTemplateInfoRef::c_signatures (JSHeapBroker * broker) const
Definition at line 1908 of file heap-refs.cc.
                                {
  return GetCSignatures(Cast<FixedArray>(object()->GetCFunctionOverloads()),
                        broker->isolate(), broker->zone());
}
References broker(), and v8::internal::compiler::anonymous_namespace{heap-refs.cc}::GetCSignatures().
Referenced by v8::internal::compiler::fast_api_call::GetFastApiCallTarget(), v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::PushRegularApiCallInputs(), and v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall().
callback()
Address v8::internal::compiler::FunctionTemplateInfoRef::callback (JSHeapBroker * broker) const
Definition at line 1681 of file heap-refs.cc.
                                                                    {
  return object()->callback(broker->isolate());
}
References broker(), and object().
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::PushRegularApiCallInputs(), v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), and v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall().
callback_data()
OptionalObjectRef v8::internal::compiler::FunctionTemplateInfoRef::callback_data (JSHeapBroker * broker) const
Definition at line 1685 of file heap-refs.cc.
                                {
  ObjectRef data =
      MakeRefAssumeMemoryFence(broker, object()->callback_data(kAcquireLoad));
  if (data.IsTheHole()) return {};
  return data;
}
References broker(), v8::kAcquireLoad, and v8::internal::compiler::MakeRefAssumeMemoryFence().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::InlineApiCall(), v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall(), and v8::internal::maglev::MaglevGraphBuilder::TryReduceCallForApiFunction().
is_signature_undefined()
bool v8::internal::compiler::FunctionTemplateInfoRef::is_signature_undefined (JSHeapBroker * broker) const
Definition at line 1693 of file heap-refs.cc.
                                {
  return i::IsUndefined(object()->signature(), broker->isolate());
}
References broker().
Referenced by v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), v8::internal::compiler::JSNativeContextSpecialization::ReduceMegaDOMPropertyAccess(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildCallKnownApiFunction().
LookupHolderOfExpectedType()
allowed_receiver_instance_type_range_end HolderLookupResult v8::internal::compiler::FunctionTemplateInfoRef::LookupHolderOfExpectedType (JSHeapBroker * broker, MapRef receiver_map)
Definition at line 1704 of file heap-refs.cc.
                                               {
  const HolderLookupResult not_found;
  if (!receiver_map.IsJSObjectMap() || (receiver_map.is_access_check_needed() &&
                                        !object()->accept_any_receiver())) {
    return not_found;
  }
  DirectHandle<FunctionTemplateInfo> expected_receiver_type;
  {
    DisallowGarbageCollection no_gc;
    Tagged<HeapObject> signature = object()->signature();
    if (i::IsUndefined(signature)) {
      return HolderLookupResult(CallOptimization::kHolderIsReceiver);
    }
    expected_receiver_type = broker->CanonicalPersistentHandle(
        Cast<FunctionTemplateInfo>(signature));
    if (expected_receiver_type->IsTemplateFor(*receiver_map.object())) {
      return HolderLookupResult(CallOptimization::kHolderIsReceiver);
    }
    if (!receiver_map.IsJSGlobalProxyMap()) return not_found;
  }
  HeapObjectRef prototype = receiver_map.prototype(broker);
  if (prototype.IsNull()) return not_found;
  if (!expected_receiver_type->IsTemplateFor(prototype.object()->map())) {
    return not_found;
  }
  CHECK(prototype.IsJSObject());
  return HolderLookupResult(CallOptimization::kHolderFound,
                            prototype.AsJSObject());
}
References broker(), CHECK, v8::internal::CallOptimization::kHolderFound, v8::internal::CallOptimization::kHolderIsReceiver, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::prototype.
Referenced by v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), and v8::internal::maglev::MaglevGraphBuilder::TryInferApiHolderValue().
object()
IndirectHandle<FunctionTemplateInfo> v8::internal::compiler::FunctionTemplateInfoRef::object () const
Referenced by callback(), v8::internal::maglev::CallKnownApiFunction::PrintParams(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::PushRegularApiCallInputs(), v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), and v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/heap-refs.h
/mnt/V8SourceCode/src/compiler/heap-refs.cc