v8::bigint::Processor Class Reference
#include <bigint.h>
Classes
class Destroyer
Public Member Functions
void Destroy ()
Status Multiply (RWDigits Z, Digits X, Digits Y)
Status Divide (RWDigits Q, Digits A, Digits B)
Status Modulo (RWDigits R, Digits A, Digits B)
Status ToString (char *out, uint32_t *out_length, Digits X, int radix, bool sign)
Status FromString (RWDigits Z, FromStringAccumulator *accumulator)
Static Public Member Functions
static Processor * New (Platform *platform)
Protected Member Functions
~Processor ()=default
Detailed Description
Definition at line 287 of file bigint.h.
Constructor & Destructor Documentation
 Processor()
v8::bigint::Processor::~Processor () [protected], [default]
Member Function Documentation
Destroy()
void v8::bigint::Processor::Destroy ()
Definition at line 34 of file bigint-internal.cc.
{ delete static_cast<ProcessorImpl*>(this); }
Referenced by v8::bigint::Processor::Destroyer::operator()(), v8::internal::Isolate::~Isolate(), and v8::internal::LocalIsolate::~LocalIsolate().
Divide()
Status v8::bigint::Processor::Divide (RWDigits Q, Digits A, Digits B)
Definition at line 132 of file bigint-internal.cc.
                                                       {
  ProcessorImpl* impl = static_cast<ProcessorImpl*>(this);
  impl->Divide(Q, A, B);
  return impl->get_and_clear_status();
}
References v8::internal::A, v8::internal::B, and wasm::impl().
Referenced by v8::internal::BigInt::Divide(), and v8::internal::MutableBigInt_AbsoluteDivAndCanonicalize().
FromString()
Status v8::bigint::Processor::FromString (RWDigits Z, FromStringAccumulator * accumulator)
Definition at line 324 of file fromstring.cc.
                                                                           {
  ProcessorImpl* impl = static_cast<ProcessorImpl*>(this);
  impl->FromString(Z, accumulator);
  return impl->get_and_clear_status();
}
References wasm::impl().
Referenced by v8::internal::StringToBigIntHelper< IsolateT >::DecimalString().
Modulo()
Status v8::bigint::Processor::Modulo (RWDigits R, Digits A, Digits B)
Definition at line 138 of file bigint-internal.cc.
                                                       {
  ProcessorImpl* impl = static_cast<ProcessorImpl*>(this);
  impl->Modulo(R, A, B);
  return impl->get_and_clear_status();
}
References v8::internal::A, v8::internal::B, and wasm::impl().
Referenced by v8::internal::MutableBigInt_AbsoluteModAndCanonicalize(), and v8::internal::BigInt::Remainder().
Multiply()
Status v8::bigint::Processor::Multiply (RWDigits Z, Digits X, Digits Y)
Definition at line 126 of file bigint-internal.cc.
                                                         {
  ProcessorImpl* impl = static_cast<ProcessorImpl*>(this);
  impl->Multiply(Z, X, Y);
  return impl->get_and_clear_status();
}
References wasm::impl(), and X().
Referenced by v8::internal::BigInt::Multiply(), and v8::internal::MutableBigInt_AbsoluteMulAndCanonicalize().
New()
Processor * v8::bigint::Processor::New (Platform * platform) [static]
Definition at line 29 of file bigint-internal.cc.
                                            {
  ProcessorImpl* impl = new ProcessorImpl(platform);
  return static_cast<Processor*>(impl);
}
References wasm::impl().
Referenced by v8::internal::Isolate::Init(), v8::internal::LocalIsolate::InitializeBigIntProcessor(), and v8::internal::BigInt::NoSideEffectsToString().
ToString()
Status v8::bigint::Processor::ToString (char * out, uint32_t * out_length, Digits X, int radix, bool sign)
Definition at line 590 of file tostring.cc.
                                      {
  ProcessorImpl* impl = static_cast<ProcessorImpl*>(this);
  impl->ToString(out, out_length, X, radix, sign);
  return impl->get_and_clear_status();
}
References wasm::impl(), v8::internal::sign, and X().
Referenced by v8::internal::StringToBigIntHelper< IsolateT >::DecimalString(), and v8::internal::BigInt::ToString().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/bigint/bigint.h
/mnt/V8SourceCode/src/bigint/bigint-internal.cc
/mnt/V8SourceCode/src/bigint/fromstring.cc
/mnt/V8SourceCode/src/bigint/tostring.cc