v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next > Class Template Reference
#include <string-escape-analysis-reducer.h>
Classes
class Deduplicator
struct ElidedStringPart
Public Member Functions
void Analyze ()
V< String > REDUCE_INPUT_GRAPH() StringConcat (V< String > ig_index, const StringConcatOp &op)
V< FrameState > REDUCE_INPUT_GRAPH() FrameState (V< FrameState > ig_index, const FrameStateOp &frame_state)
V< Word32 > REDUCE_INPUT_GRAPH() StringLength (V< Word32 > ig_index, const StringLengthOp &op)
Private Member Functions
V< FrameState > BuildFrameState (const FrameStateOp &input_frame_state, OpIndex ig_index)
void BuildFrameStateInput (FrameStateData::Builder *builder, FrameStateData::Iterator *it, Deduplicator *deduplicator)
void BuildMaybeElidedString (FrameStateData::Builder *builder, ElidedStringPart maybe_elided, Deduplicator *deduplicator)
ElidedStringPart GetElidedStringInput (V< String > ig_index)
Private Attributes
StringEscapeAnalyzer analyzer_ {Asm().input_graph(), Asm().phase_zone()}
ZoneAbslFlatHashMap< V< String >, std::pair< ElidedStringPart, ElidedStringPart > > elided_strings_ {Asm().phase_zone()}
SparseOpIndexSideTable< Deduplicator * > deduplicators_
Detailed Description
template<class Next>
class v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >
Definition at line 105 of file string-escape-analysis-reducer.h.
Member Function Documentation
Analyze()
template<class Next >
void v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::Analyze () [inline]
Definition at line 157 of file string-escape-analysis-reducer.h.
                 {
    if (v8_flags.turboshaft_string_concat_escape_analysis) {
      analyzer_.Run();
    }
    Next::Analyze();
  }
References v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::analyzer_, v8::internal::compiler::turboshaft::StringEscapeAnalyzer::Run(), and v8::internal::v8_flags.
BuildFrameState()
template<class Next >
V<FrameState> v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildFrameState (const FrameStateOp & input_frame_state, OpIndex ig_index) [inline], [private]
Definition at line 245 of file string-escape-analysis-reducer.h.
                                                  {
    DCHECK(v8_flags.turboshaft_string_concat_escape_analysis);
    const FrameStateInfo& info = input_frame_state.data->frame_state_info;
    FrameStateData::Builder builder;
    auto it =
        input_frame_state.data->iterator(input_frame_state.state_values());
    Deduplicator* deduplicator;
    if (input_frame_state.inlined) {
      V<FrameState> parent_ig_index = input_frame_state.parent_frame_state();
      builder.AddParentFrameState(__ MapToNewGraph(parent_ig_index));
      // The parent FrameState could contain dematerialized objects, and the
      // current FrameState could reference those. Also, new IDs created for the
      // current FrameState should not conflict with IDs in the parent frame
      // state. Thus, we need to initialize the current Deduplicator with the
      // one from the parent FrameState.
      DCHECK(analyzer_.ShouldReconstructFrameState(parent_ig_index));
      deduplicator = deduplicators_[parent_ig_index]->clone(__ phase_zone());
    } else {
      deduplicator =
          __ phase_zone() -> template New<Deduplicator>(__ phase_zone());
    }
    deduplicators_[ig_index] = deduplicator;
    // Closure
    BuildFrameStateInput(&builder, &it, deduplicator);
    // Parameters
    for (int i = 0; i < info.parameter_count(); i++) {
      BuildFrameStateInput(&builder, &it, deduplicator);
    }
    // Context
    BuildFrameStateInput(&builder, &it, deduplicator);
    // Registers/locals
    for (int i = 0; i < info.local_count(); i++) {
      BuildFrameStateInput(&builder, &it, deduplicator);
    }
    // Accumulator
    for (int i = 0; i < info.stack_count(); i++) {
      BuildFrameStateInput(&builder, &it, deduplicator);
    }
    return __ FrameState(builder.Inputs(), builder.inlined(),
                         builder.AllocateFrameStateData(info, __ graph_zone()));
  }
References __, v8::internal::compiler::turboshaft::FrameStateData::Builder::AddParentFrameState(), v8::internal::compiler::turboshaft::FrameStateData::Builder::AllocateFrameStateData(), v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::analyzer_, v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildFrameStateInput(), v8::internal::compiler::turboshaft::FrameStateOp::data, v8::internal::DCHECK(), v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::deduplicators_, v8::internal::compiler::turboshaft::FrameStateData::frame_state_info, v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::FrameState(), v8::internal::compiler::turboshaft::FrameStateData::Builder::inlined(), v8::internal::compiler::turboshaft::FrameStateOp::inlined, v8::internal::compiler::turboshaft::FrameStateData::Builder::Inputs(), v8::internal::compiler::turboshaft::FrameStateData::iterator(), v8::internal::compiler::FrameStateInfo::local_count(), v8::internal::compiler::FrameStateInfo::parameter_count(), v8::internal::compiler::turboshaft::FrameStateOp::parent_frame_state(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::ShouldReconstructFrameState(), v8::internal::compiler::FrameStateInfo::stack_count(), v8::internal::compiler::turboshaft::FrameStateOp::state_values(), and v8::internal::v8_flags.
Referenced by v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::FrameState().
BuildFrameStateInput()
template<class Next >
void v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildFrameStateInput (FrameStateData::Builder * builder, FrameStateData::Iterator * it, Deduplicator * deduplicator) [inline], [private]
Definition at line 298 of file string-escape-analysis-reducer.h.
                                                        {
    switch (it->current_instr()) {
      using Instr = FrameStateData::Instr;
      case Instr::kInput: {
        MachineType type;
        OpIndex input;
        it->ConsumeInput(&type, &input);
        if (elided_strings_.contains(input)) {
          DCHECK(type.IsTagged());
          BuildMaybeElidedString(builder, ElidedStringPart::Elided(input),
                                 deduplicator);
        } else {
          builder->AddInput(type, __ MapToNewGraph(input));
        }
        break;
      }
      case Instr::kDematerializedObject: {
        uint32_t old_id;
        uint32_t field_count;
        it->ConsumeDematerializedObject(&old_id, &field_count);
        builder->AddDematerializedObject(old_id, field_count);
        for (uint32_t i = 0; i < field_count; ++i) {
          BuildFrameStateInput(builder, it, deduplicator);
        }
        break;
      }
      case Instr::kDematerializedObjectReference: {
        uint32_t old_id;
        it->ConsumeDematerializedObjectReference(&old_id);
        builder->AddDematerializedObjectReference(old_id);
        break;
      }
      case Instr::kArgumentsElements: {
        CreateArgumentsType type;
        it->ConsumeArgumentsElements(&type);
        builder->AddArgumentsElements(type);
        break;
      }
      case Instr::kArgumentsLength:
        it->ConsumeArgumentsLength();
        builder->AddArgumentsLength();
        break;
      case Instr::kRestLength:
        it->ConsumeRestLength();
        builder->AddRestLength();
        break;
      case Instr::kUnusedRegister:
        it->ConsumeUnusedRegister();
        builder->AddUnusedRegister();
        break;
      case FrameStateData::Instr::kDematerializedStringConcat:
      case FrameStateData::Instr::kDematerializedStringConcatReference:
        // StringConcat should not have been escaped before this point.
        UNREACHABLE();
    }
  }
References __, v8::internal::compiler::turboshaft::FrameStateData::Builder::AddArgumentsElements(), v8::internal::compiler::turboshaft::FrameStateData::Builder::AddArgumentsLength(), v8::internal::compiler::turboshaft::FrameStateData::Builder::AddDematerializedObject(), v8::internal::compiler::turboshaft::FrameStateData::Builder::AddDematerializedObjectReference(), v8::internal::compiler::turboshaft::FrameStateData::Builder::AddInput(), v8::internal::compiler::turboshaft::FrameStateData::Builder::AddRestLength(), v8::internal::compiler::turboshaft::FrameStateData::Builder::AddUnusedRegister(), v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildMaybeElidedString(), v8::internal::compiler::turboshaft::FrameStateData::Iterator::ConsumeArgumentsElements(), v8::internal::compiler::turboshaft::FrameStateData::Iterator::ConsumeArgumentsLength(), v8::internal::compiler::turboshaft::FrameStateData::Iterator::ConsumeDematerializedObject(), v8::internal::compiler::turboshaft::FrameStateData::Iterator::ConsumeDematerializedObjectReference(), v8::internal::compiler::turboshaft::FrameStateData::Iterator::ConsumeInput(), v8::internal::compiler::turboshaft::FrameStateData::Iterator::ConsumeRestLength(), v8::internal::compiler::turboshaft::FrameStateData::Iterator::ConsumeUnusedRegister(), v8::internal::compiler::turboshaft::FrameStateData::Iterator::current_instr(), v8::internal::DCHECK(), v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::ElidedStringPart::Elided(), v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::elided_strings_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::FrameStateData::kDematerializedStringConcat, v8::internal::compiler::turboshaft::FrameStateData::kDematerializedStringConcatReference, v8::internal::tracing::type, and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildFrameState().
BuildMaybeElidedString()
template<class Next >
void v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildMaybeElidedString (FrameStateData::Builder * builder, ElidedStringPart maybe_elided, Deduplicator * deduplicator) [inline], [private]
Definition at line 357 of file string-escape-analysis-reducer.h.
                                                          {
    if (maybe_elided.is_elided()) {
      typename Deduplicator::DuplicatedId dup_id =
          deduplicator->GetDuplicatedIdForElidedString(maybe_elided);
      if (dup_id.duplicated) {
        // For performance reasons, we de-duplicate repeated StringConcat inputs
        // in the FrameState. Unlike for elided objects, deduplication has no
        // impact on correctness.
        builder->AddDematerializedStringConcatReference(dup_id.id);
        return;
      }
      builder->AddDematerializedStringConcat(dup_id.id);
      std::pair<ElidedStringPart, ElidedStringPart> inputs =
          elided_strings_.at(maybe_elided.ig_index());
      BuildMaybeElidedString(builder, inputs.first, deduplicator);
      BuildMaybeElidedString(builder, inputs.second, deduplicator);
    } else {
      builder->AddInput(MachineType::AnyTagged(), maybe_elided.og_index());
    }
  }
References v8::internal::compiler::turboshaft::FrameStateData::Builder::AddDematerializedStringConcat(), v8::internal::compiler::turboshaft::FrameStateData::Builder::AddDematerializedStringConcatReference(), v8::internal::compiler::turboshaft::FrameStateData::Builder::AddInput(), v8::internal::MachineType::AnyTagged(), v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::Deduplicator::DuplicatedId::duplicated, v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::elided_strings_, v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::Deduplicator::GetDuplicatedIdForElidedString(), v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::Deduplicator::DuplicatedId::id, v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::ElidedStringPart::ig_index, v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::ElidedStringPart::is_elided(), and v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::ElidedStringPart::og_index.
Referenced by v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildFrameStateInput().
FrameState()
template<class Next >
V<FrameState> REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::FrameState (V< FrameState > ig_index, const FrameStateOp & frame_state) [inline]
Definition at line 179 of file string-escape-analysis-reducer.h.
                                                               {
    LABEL_BLOCK(no_change) {
      return Next::ReduceInputGraphFrameState(ig_index, frame_state);
    }
    if (!v8_flags.turboshaft_string_concat_escape_analysis) goto no_change;
    if (!analyzer_.ShouldReconstructFrameState(ig_index)) goto no_change;
    return BuildFrameState(frame_state, ig_index);
  }
References v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::analyzer_, v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildFrameState(), LABEL_BLOCK, v8::internal::compiler::turboshaft::StringEscapeAnalyzer::ShouldReconstructFrameState(), and v8::internal::v8_flags.
Referenced by v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildFrameState().
GetElidedStringInput()
template<class Next >
ElidedStringPart v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::GetElidedStringInput (V< String > ig_index) [inline], [private]
Definition at line 380 of file string-escape-analysis-reducer.h.
                                                            {
    if (elided_strings_.contains(ig_index)) {
      return ElidedStringPart::Elided(ig_index);
    } else {
      return ElidedStringPart::NotElided(__ MapToNewGraph(ig_index));
    }
  }
References __, v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::ElidedStringPart::Elided(), v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::elided_strings_, and v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::ElidedStringPart::NotElided().
Referenced by v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::StringConcat().
StringConcat()
template<class Next >
V<String> REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::StringConcat (V< String > ig_index, const StringConcatOp & op) [inline]
Definition at line 164 of file string-escape-analysis-reducer.h.
                                                                       {
    LABEL_BLOCK(no_change) {
      return Next::ReduceInputGraphStringConcat(ig_index, op);
    }
    if (!v8_flags.turboshaft_string_concat_escape_analysis) goto no_change;
    if (analyzer_.IsEscaping(ig_index)) goto no_change;
    // We're eliding this StringConcat.
    ElidedStringPart left = GetElidedStringInput(op.left());
    ElidedStringPart right = GetElidedStringInput(op.right());
    elided_strings_.insert({ig_index, std::pair{left, right}});
    return V<String>::Invalid();
  }
References v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::analyzer_, v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::elided_strings_, v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::GetElidedStringInput(), v8::internal::compiler::turboshaft::V< T >::Invalid(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::IsEscaping(), LABEL_BLOCK, and v8::internal::v8_flags.
StringLength()
template<class Next >
V<Word32> REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::StringLength (V< Word32 > ig_index, const StringLengthOp & op) [inline]
Definition at line 191 of file string-escape-analysis-reducer.h.
                                                                       {
    LABEL_BLOCK(no_change) {
      return Next::ReduceInputGraphStringLength(ig_index, op);
    }
    if (!v8_flags.turboshaft_string_concat_escape_analysis) goto no_change;
    V<String> input_index = op.string();
    if (const StringConcatOp* input = __ input_graph()
                                          .Get(input_index)
                                          .template TryCast<StringConcatOp>();
        input && !analyzer_.IsEscaping(input_index)) {
      return __ UntagSmi(__ MapToNewGraph(input->length()));
    } else {
      goto no_change;
    }
  }
References __, v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::analyzer_, v8::internal::compiler::turboshaft::Get(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::IsEscaping(), LABEL_BLOCK, and v8::internal::v8_flags.
Member Data Documentation
analyzer_
template<class Next >
StringEscapeAnalyzer v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::analyzer_ {Asm().input_graph(), Asm().phase_zone()} [private]
Definition at line 388 of file string-escape-analysis-reducer.h.
Referenced by v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::Analyze(), v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildFrameState(), v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::FrameState(), v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::StringConcat(), and v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::StringLength().
deduplicators_
template<class Next >
SparseOpIndexSideTable<Deduplicator*> v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::deduplicators_ [private]
Initial value:
{Asm().phase_zone(),
                                                       &Asm().input_graph()}
Definition at line 395 of file string-escape-analysis-reducer.h.
Referenced by v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildFrameState().
elided_strings_
template<class Next >
ZoneAbslFlatHashMap<V<String>, std::pair<ElidedStringPart, ElidedStringPart> > v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::elided_strings_ {Asm().phase_zone()} [private]
Definition at line 392 of file string-escape-analysis-reducer.h.
Referenced by v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildFrameStateInput(), v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildMaybeElidedString(), v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::GetElidedStringInput(), and v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::StringConcat().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/string-escape-analysis-reducer.h