v8::internal::compiler::turboshaft::ExplicitTruncationReducer< Next > Class Template Reference
#include <explicit-truncation-reducer.h>
Public Member Functions
template<Opcode opcode, typename Continuation , typename... Ts>
OpIndex ReduceOperation (Ts... args)
Private Attributes
ZoneVector< MaybeRegisterRepresentation > inputs_rep_storage_
base::SmallVector< OperationStorageSlot, 32 > storage_
Detailed Description
template<class Next>
class v8::internal::compiler::turboshaft::ExplicitTruncationReducer< Next >
Definition at line 21 of file explicit-truncation-reducer.h.
Member Function Documentation
ReduceOperation()
template<class Next >
template<Opcode opcode, typename Continuation , typename... Ts>
OpIndex v8::internal::compiler::turboshaft::ExplicitTruncationReducer< Next >::ReduceOperation (Ts... args) [inline]
Definition at line 27 of file explicit-truncation-reducer.h.
                                      {
    // Construct a temporary operation. The operation is needed for generic
    // access to the inputs and the inputs representation.
    using Op = typename opcode_to_operation_map<opcode>::Op;
    Op* operation = CreateOperation<Op>(storage_, args...);
    base::Vector<const MaybeRegisterRepresentation> reps =
        operation->inputs_rep(inputs_rep_storage_);
    base::Vector<OpIndex> inputs = operation->inputs();
    bool has_truncation = false;
    for (size_t i = 0; i < reps.size(); ++i) {
      if (reps[i] == MaybeRegisterRepresentation::Word32()) {
        base::Vector<const RegisterRepresentation> actual_inputs_rep =
            Asm().input_graph().Get(inputs[i]).outputs_rep();
        // We ignore any input operation that produces more than one value.
        // These cannot be consumed directly and therefore require a projection.
        // Assumption: A projection never performs an implicit truncation from
        // word64 to word32.
        if (actual_inputs_rep.size() == 1 &&
            actual_inputs_rep[0] == RegisterRepresentation::Word64()) {
          has_truncation = true;
          inputs[i] = Next::ReduceChange(inputs[i], ChangeOp::Kind::kTruncate,
                                         ChangeOp::Assumption::kNoAssumption,
                                         RegisterRepresentation::Word64(),
                                         RegisterRepresentation::Word32());
        }
      }
    }
    if (!has_truncation) {
      // Just call the regular Reduce without any remapped values.
      return Continuation{this}.Reduce(args...);
    }
    Operation::IdentityMapper mapper;
    return operation->Explode(
        [this](auto... args) -> OpIndex {
          return Continuation{this}.Reduce(args...);
        },
        mapper);
  }
References v8::base::args, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::ExplicitTruncationReducer< Next >::inputs_rep_storage_, v8::internal::compiler::turboshaft::ChangeOp::kNoAssumption, v8::internal::compiler::turboshaft::ChangeOp::kTruncate, v8::base::Vector< T >::size(), v8::internal::compiler::turboshaft::ExplicitTruncationReducer< Next >::storage_, v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Word32(), v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word64().
Member Data Documentation
inputs_rep_storage_
template<class Next >
ZoneVector<MaybeRegisterRepresentation> v8::internal::compiler::turboshaft::ExplicitTruncationReducer< Next >::inputs_rep_storage_ [private]
Initial value:
{
      Asm().phase_zone()}
Definition at line 70 of file explicit-truncation-reducer.h.
Referenced by v8::internal::compiler::turboshaft::ExplicitTruncationReducer< Next >::ReduceOperation().
storage_
template<class Next >
base::SmallVector<OperationStorageSlot, 32> v8::internal::compiler::turboshaft::ExplicitTruncationReducer< Next >::storage_ [private]
Definition at line 72 of file explicit-truncation-reducer.h.
Referenced by v8::internal::compiler::turboshaft::ExplicitTruncationReducer< Next >::ReduceOperation().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/explicit-truncation-reducer.h