v8::internal::ClientObjectVisitor< Visitor > Class Template Reference
#include <visitors.h>
Public Member Functions
ClientObjectVisitor (Visitor *actual_visitor)
void VisitPointer (Tagged< HeapObject > host, ObjectSlot p) final
void VisitMapPointer (Tagged< HeapObject > host) final
void VisitPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) final
void VisitInstructionStreamPointer (Tagged< Code > host, InstructionStreamSlot slot) final
void VisitPointers (Tagged< HeapObject > host, MaybeObjectSlot start, MaybeObjectSlot end) final
void VisitCodeTarget (Tagged< InstructionStream > host, RelocInfo *rinfo) final
void VisitEmbeddedPointer (Tagged< InstructionStream > host, RelocInfo *rinfo) final
Static Private Member Functions
static bool IsSharedHeapObject (Tagged< Object > object)
Private Attributes
Visitor *const actual_visitor_
Detailed Description
template<typename Visitor = ObjectVisitorWithCageBases>
class v8::internal::ClientObjectVisitor< Visitor >
Definition at line 299 of file visitors.h.
Constructor & Destructor Documentation
ClientObjectVisitor()
template<typename Visitor = ObjectVisitorWithCageBases>
v8::internal::ClientObjectVisitor< Visitor >::ClientObjectVisitor (Visitor * actual_visitor) [inline], [explicit]
Definition at line 301 of file visitors.h.
      : ObjectVisitorWithCageBases(actual_visitor->cage_base(),
                                   actual_visitor->code_cage_base()),
        actual_visitor_(actual_visitor) {}
Member Function Documentation
IsSharedHeapObject()
template<typename Visitor >
bool v8::internal::ClientObjectVisitor< Visitor >::IsSharedHeapObject (Tagged< Object > object) [inline], [static], [private]
Definition at line 101 of file visitors-inl.h.
                                                                           {
  return IsHeapObject(object) &&
         HeapLayout::InWritableSharedSpace(Cast<HeapObject>(object));
}
References v8::internal::HeapLayout::InWritableSharedSpace(), and v8::internal::IsHeapObject().
Referenced by v8::internal::ClientObjectVisitor< Visitor >::VisitPointer().
VisitCodeTarget()
template<typename Visitor >
void v8::internal::ClientObjectVisitor< Visitor >::VisitCodeTarget (Tagged< InstructionStream > host, RelocInfo * rinfo) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 83 of file visitors-inl.h.
                                                      {
#if DEBUG
  Tagged<InstructionStream> target =
      InstructionStream::FromTargetAddress(rinfo->target_address());
  DCHECK(!HeapLayout::InWritableSharedSpace(target));
#endif
}
References v8::internal::DCHECK(), v8::internal::InstructionStream::FromTargetAddress(), v8::internal::HeapLayout::InWritableSharedSpace(), and v8::internal::RelocInfo::target_address().
VisitEmbeddedPointer()
template<typename Visitor >
void v8::internal::ClientObjectVisitor< Visitor >::VisitEmbeddedPointer (Tagged< InstructionStream > host, RelocInfo * rinfo) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 93 of file visitors-inl.h.
                                                      {
  if (!IsSharedHeapObject(rinfo->target_object(cage_base()))) return;
  actual_visitor_->VisitEmbeddedPointer(host, rinfo);
}
References v8::internal::RelocInfo::target_object().
VisitInstructionStreamPointer()
template<typename Visitor >
void v8::internal::ClientObjectVisitor< Visitor >::VisitInstructionStreamPointer (Tagged< Code > host, InstructionStreamSlot slot) [inline], [final], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 71 of file visitors-inl.h.
                                                   {
#if DEBUG
  Tagged<Object> istream_object = slot.load(code_cage_base());
  Tagged<InstructionStream> istream;
  if (istream_object.GetHeapObject(&istream)) {
    DCHECK(!HeapLayout::InWritableSharedSpace(istream));
  }
#endif
}
References v8::internal::DCHECK(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObject(), v8::internal::HeapLayout::InWritableSharedSpace(), and v8::internal::FullObjectSlot::load().
VisitMapPointer()
template<typename Visitor >
void v8::internal::ClientObjectVisitor< Visitor >::VisitMapPointer (Tagged< HeapObject > host) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 64 of file visitors-inl.h.
                             {
  if (!IsSharedHeapObject(host->map(cage_base()))) return;
  actual_visitor_->VisitMapPointer(host);
}
VisitPointer()
template<typename Visitor = ObjectVisitorWithCageBases>
void v8::internal::ClientObjectVisitor< Visitor >::VisitPointer (Tagged< HeapObject > host, ObjectSlot p) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 306 of file visitors.h.
                                                                 {
    if (!IsSharedHeapObject(p.load(cage_base()))) return;
    actual_visitor_->VisitPointer(host, p);
  }
References v8::internal::ClientObjectVisitor< Visitor >::actual_visitor_, v8::internal::ObjectVisitorWithCageBases::cage_base(), and v8::internal::ClientObjectVisitor< Visitor >::IsSharedHeapObject().
Referenced by v8::internal::ClientObjectVisitor< Visitor >::VisitPointers().
VisitPointers() [1/2]
template<typename Visitor = ObjectVisitorWithCageBases>
void v8::internal::ClientObjectVisitor< Visitor >::VisitPointers (Tagged< HeapObject > host, MaybeObjectSlot start, MaybeObjectSlot end) [inline], [final], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 326 of file visitors.h.
                                                {
    // At the moment, custom roots cannot contain weak pointers.
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
VisitPointers() [2/2]
template<typename Visitor = ObjectVisitorWithCageBases>
void v8::internal::ClientObjectVisitor< Visitor >::VisitPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) [inline], [final], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 313 of file visitors.h.
                                           {
    for (ObjectSlot p = start; p < end; ++p) {
      // The map slot should be handled in VisitMapPointer.
      DCHECK_NE(host->map_slot(), p);
      DCHECK(!HasWeakHeapObjectTag(p.load(cage_base())));
      VisitPointer(host, p);
    }
  }
References v8::internal::ObjectVisitorWithCageBases::cage_base(), v8::internal::DCHECK(), DCHECK_NE, v8::internal::compiler::end(), v8::internal::HasWeakHeapObjectTag(), and v8::internal::ClientObjectVisitor< Visitor >::VisitPointer().
Member Data Documentation
actual_visitor_
template<typename Visitor = ObjectVisitorWithCageBases>
Visitor* const v8::internal::ClientObjectVisitor< Visitor >::actual_visitor_ [private]
Definition at line 341 of file visitors.h.
Referenced by v8::internal::ClientObjectVisitor< Visitor >::VisitPointer().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/visitors.h
/mnt/V8SourceCode/src/objects/visitors-inl.h