v8::internal::ParserBase< Impl >::Target Class Reference
#include <parser-base.h>
Public Types
enum TargetType { TARGET_FOR_ANONYMOUS
, TARGET_FOR_NAMED_ONLY
 }
Public Member Functions
Target (ParserBase *parser, BreakableStatementT statement, ZonePtrList< const AstRawString > *labels, ZonePtrList< const AstRawString > *own_labels, TargetType target_type)
~Target ()
const Target * previous () const
const BreakableStatementT statement () const
const ZonePtrList< const AstRawString > * labels () const
const ZonePtrList< const AstRawString > * own_labels () const
bool is_iteration () const
bool is_target_for_anonymous () const
Private Attributes
Target **const stack_
const BreakableStatementT statement_
const ZonePtrList< const AstRawString > *const labels_
const ZonePtrList< const AstRawString > *const own_labels_
const TargetType target_type_
Target *const previous_
Detailed Description
template<typename Impl>
class v8::internal::ParserBase< Impl >::Target
Definition at line 375 of file parser-base.h.
Member Enumeration Documentation
TargetType
template<typename Impl >
enum v8::internal::ParserBase::Target::TargetType
Enumerator
TARGET_FOR_ANONYMOUS
TARGET_FOR_NAMED_ONLY
Definition at line 377 of file parser-base.h.
{ TARGET_FOR_ANONYMOUS, TARGET_FOR_NAMED_ONLY };
Constructor & Destructor Documentation
Target()
template<typename Impl >
v8::internal::ParserBase< Impl >::Target::Target (ParserBase * parser, BreakableStatementT statement, ZonePtrList< const AstRawString > * labels, ZonePtrList< const AstRawString > * own_labels, TargetType target_type) [inline]
Definition at line 379 of file parser-base.h.
        : stack_(parser->function_state_->target_stack_address()),
          statement_(statement),
          labels_(labels),
          own_labels_(own_labels),
          target_type_(target_type),
          previous_(*stack_) {
      DCHECK_IMPLIES(Impl::IsIterationStatement(statement_),
                     target_type == Target::TARGET_FOR_ANONYMOUS);
      DCHECK_IMPLIES(!Impl::IsIterationStatement(statement_),
                     own_labels == nullptr);
      *stack_ = this;
    }
References DCHECK_IMPLIES, v8::internal::ParserBase< Impl >::Target::own_labels(), v8::internal::ParserBase< Impl >::Target::stack_, v8::internal::ParserBase< Impl >::Target::statement_, and v8::internal::ParserBase< Impl >::Target::TARGET_FOR_ANONYMOUS.
 Target()
template<typename Impl >
v8::internal::ParserBase< Impl >::Target::~Target () [inline]
Definition at line 395 of file parser-base.h.
{ *stack_ = previous_; }
References v8::internal::ParserBase< Impl >::Target::previous_, and v8::internal::ParserBase< Impl >::Target::stack_.
Member Function Documentation
is_iteration()
template<typename Impl >
bool v8::internal::ParserBase< Impl >::Target::is_iteration () const [inline]
Definition at line 403 of file parser-base.h.
{ return Impl::IsIterationStatement(statement_); }
References v8::internal::ParserBase< Impl >::Target::statement_.
is_target_for_anonymous()
template<typename Impl >
bool v8::internal::ParserBase< Impl >::Target::is_target_for_anonymous () const [inline]
Definition at line 404 of file parser-base.h.
                                         {
      return target_type_ == TARGET_FOR_ANONYMOUS;
    }
References v8::internal::ParserBase< Impl >::Target::TARGET_FOR_ANONYMOUS, and v8::internal::ParserBase< Impl >::Target::target_type_.
labels()
template<typename Impl >
const ZonePtrList<const AstRawString>* v8::internal::ParserBase< Impl >::Target::labels () const [inline]
Definition at line 399 of file parser-base.h.
{ return labels_; }
References v8::internal::ParserBase< Impl >::Target::labels_.
own_labels()
template<typename Impl >
const ZonePtrList<const AstRawString>* v8::internal::ParserBase< Impl >::Target::own_labels () const [inline]
Definition at line 400 of file parser-base.h.
                                                              {
      return own_labels_;
    }
References v8::internal::ParserBase< Impl >::Target::own_labels_.
Referenced by v8::internal::ParserBase< Impl >::Target::Target().
previous()
template<typename Impl >
const Target* v8::internal::ParserBase< Impl >::Target::previous () const [inline]
Definition at line 397 of file parser-base.h.
{ return previous_; }
References v8::internal::ParserBase< Impl >::Target::previous_.
Referenced by v8::internal::ParserBase< Impl >::LookupBreakTarget(), v8::internal::ParserBase< Impl >::LookupContinueTarget(), and v8::internal::ParserBase< Impl >::TargetStackContainsLabel().
statement()
template<typename Impl >
const BreakableStatementT v8::internal::ParserBase< Impl >::Target::statement () const [inline]
Definition at line 398 of file parser-base.h.
{ return statement_; }
References v8::internal::ParserBase< Impl >::Target::statement_.
Member Data Documentation
labels_
template<typename Impl >
const ZonePtrList<const AstRawString>* const v8::internal::ParserBase< Impl >::Target::labels_ [private]
Definition at line 411 of file parser-base.h.
Referenced by v8::internal::ParserBase< Impl >::Target::labels().
own_labels_
template<typename Impl >
const ZonePtrList<const AstRawString>* const v8::internal::ParserBase< Impl >::Target::own_labels_ [private]
Definition at line 412 of file parser-base.h.
Referenced by v8::internal::ParserBase< Impl >::Target::own_labels().
previous_
template<typename Impl >
Target* const v8::internal::ParserBase< Impl >::Target::previous_ [private]
Definition at line 414 of file parser-base.h.
Referenced by v8::internal::ParserBase< Impl >::Target::previous(), and v8::internal::ParserBase< Impl >::Target::~Target().
stack_
template<typename Impl >
Target** const v8::internal::ParserBase< Impl >::Target::stack_ [private]
Definition at line 409 of file parser-base.h.
Referenced by v8::internal::ParserBase< Impl >::Target::Target(), and v8::internal::ParserBase< Impl >::Target::~Target().
statement_
template<typename Impl >
const BreakableStatementT v8::internal::ParserBase< Impl >::Target::statement_ [private]
Definition at line 410 of file parser-base.h.
Referenced by v8::internal::ParserBase< Impl >::Target::is_iteration(), v8::internal::ParserBase< Impl >::Target::statement(), and v8::internal::ParserBase< Impl >::Target::Target().
target_type_
template<typename Impl >
const TargetType v8::internal::ParserBase< Impl >::Target::target_type_ [private]
Definition at line 413 of file parser-base.h.
Referenced by v8::internal::ParserBase< Impl >::Target::is_target_for_anonymous().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/parsing/parser-base.h