v8::Worker Class Reference
#include <d8.h>
Classes
class WorkerThread
Public Member Functions
Worker (Isolate *parent_isolate, const char *script, bool flush_denormals)
~Worker ()
void PostMessage (std::unique_ptr< SerializationData > data)
std::unique_ptr< SerializationData > GetMessage (Isolate *requester)
std::unique_ptr< SerializationData > TryGetMessage ()
void Terminate ()
void TerminateAndWaitForThread (const i::ParkedScope &parked)
void EnterTerminatedState ()
bool IsTerminated () const
Static Public Member Functions
static bool StartWorkerThread (Isolate *requester, std::shared_ptr< Worker > worker, base::Thread::Priority priority)
static Worker * GetCurrentWorker ()
Static Public Attributes
static constexpr i::ExternalPointerTag kManagedTag = i::kD8WorkerTag
Private Types
enum class State {
kReady
, kPrepareRunning
, kRunning
, kTerminating
,
kTerminated
 }
Private Member Functions
bool is_running () const
void ProcessMessage (std::unique_ptr< SerializationData > data)
void ProcessMessages ()
void ExecuteInThread ()
Static Private Member Functions
static void PostMessageOut (const v8::FunctionCallbackInfo< v8::Value > &info)
static void ImportScripts (const v8::FunctionCallbackInfo< v8::Value > &info)
static void Close (const v8::FunctionCallbackInfo< v8::Value > &info)
static void SetCurrentWorker (Worker *worker)
Private Attributes
i::ParkingSemaphore out_semaphore_ {0}
SerializationDataQueue out_queue_
base::Thread * thread_ = nullptr
char * script_
bool flush_denormals_
std::atomic< State > state_
bool is_joined_ = false
i::ParkingSemaphore started_semaphore_ {0}
std::shared_ptr< TaskRunner > task_runner_
i::CancelableTaskManager * task_manager_
base::Mutex worker_mutex_
Isolate * isolate_ = nullptr
Isolate * parent_isolate_
Global< Context > context_
Friends
class ProcessMessageTask
class TerminateTask
Detailed Description
Definition at line 187 of file d8.h.
Member Enumeration Documentation
State
enum v8::Worker::State [strong], [private]
Enumerator
kReady
kPrepareRunning
kRunning
kTerminating
kTerminated
Definition at line 234 of file d8.h.
                   {
    kReady,
    kPrepareRunning,
    kRunning,
    kTerminating,
    kTerminated,
  };
Constructor & Destructor Documentation
Worker()
v8::Worker::Worker (Isolate * parent_isolate, const char * script, bool flush_denormals) [explicit]
Definition at line 5365 of file d8.cc.
    : script_(i::StrDup(script)),
      flush_denormals_(flush_denormals),
      parent_isolate_(parent_isolate) {
  state_.store(State::kReady);
}
References kReady, and state_.
 Worker()
v8::Worker::~Worker ()
Definition at line 5373 of file d8.cc.
                {
  CHECK(state_.load() == State::kTerminated);
  DCHECK_NULL(isolate_);
  delete thread_;
  thread_ = nullptr;
  delete[] script_;
  script_ = nullptr;
}
References CHECK, DCHECK_NULL, isolate_, kTerminated, script_, state_, and thread_.
Member Function Documentation
Close()
void v8::Worker::Close (const v8::FunctionCallbackInfo< v8::Value > & info) [static], [private]
Definition at line 5748 of file d8.cc.
                                                              {
  DCHECK(i::ValidateCallbackInfo(info));
  Isolate* isolate = info.GetIsolate();
  HandleScope handle_scope(isolate);
  DCHECK(info.Data()->IsExternal());
  Local<External> this_value = info.Data().As<External>();
  Worker* worker = static_cast<Worker*>(this_value->Value());
  worker->Terminate();
}
References v8::FunctionCallbackInfo< T >::Data(), DCHECK, v8::FunctionCallbackInfo< T >::GetIsolate(), Terminate(), and v8::internal::ValidateCallbackInfo().
Referenced by ExecuteInThread().
EnterTerminatedState()
void v8::Worker::EnterTerminatedState ()
Definition at line 5497 of file d8.cc.
                                  {
  base::MutexGuard lock_guard(&worker_mutex_);
  state_.store(State::kTerminated);
  CHECK(!is_running());
  task_runner_.reset();
  task_manager_ = nullptr;
}
References CHECK, is_running(), kTerminated, state_, task_manager_, task_runner_, and worker_mutex_.
Referenced by ExecuteInThread().
ExecuteInThread()
void v8::Worker::ExecuteInThread () [private]
Definition at line 5572 of file d8.cc.
                             {
  v8::base::FlushDenormalsScope denormals_scope(flush_denormals_);
  Isolate::CreateParams create_params;
  create_params.array_buffer_allocator = Shell::array_buffer_allocator;
  isolate_ = Isolate::New(create_params);
  // Make the Worker instance available to the whole thread.
  SetCurrentWorker(this);
  task_runner_ = g_default_platform->GetForegroundTaskRunner(isolate_);
  task_manager_ =
      reinterpret_cast<i::Isolate*>(isolate_)->cancelable_task_manager();
  auto expected = State::kPrepareRunning;
  CHECK(state_.compare_exchange_strong(expected, State::kRunning));
  // The Worker is now ready to receive messages.
  started_semaphore_.Signal();
  {
    Isolate::Scope isolate_scope(isolate_);
    D8Console console(isolate_);
    Shell::Initialize(isolate_, &console, false);
    PerIsolateData data(isolate_);
    CHECK(context_.IsEmpty());
    {
      HandleScope scope(isolate_);
      Local<Context> context;
      if (Shell::CreateEvaluationContext(isolate_).ToLocal(&context)) {
        context_.Reset(isolate_, context);
        CHECK(!context_.IsEmpty());
      }
    }
    if (!context_.IsEmpty()) {
      {
        bool success;
        PerIsolateData::RealmScope realm_scope(isolate_, context_);
        {
          HandleScope scope(isolate_);
          Local<Context> context = context_.Get(isolate_);
          Context::Scope context_scope(context);
          Local<Object> global = context->Global();
          Local<Value> this_value = External::New(isolate_, this);
          Local<FunctionTemplate> postmessage_fun_template =
              FunctionTemplate::New(isolate_, Worker::PostMessageOut,
                                    this_value);
          Local<Function> postmessage_fun;
          if (postmessage_fun_template->GetFunction(context).ToLocal(
                  &postmessage_fun)) {
            global
                ->Set(
                    context,
                    v8::String::NewFromUtf8Literal(
                        isolate_, "postMessage", NewStringType::kInternalized),
                    postmessage_fun)
                .FromJust();
          }
          Local<FunctionTemplate> close_fun_template =
              FunctionTemplate::New(isolate_, Worker::Close, this_value);
          Local<Function> close_fun;
          if (close_fun_template->GetFunction(context).ToLocal(&close_fun)) {
            global
                ->Set(context,
                      v8::String::NewFromUtf8Literal(
                          isolate_, "close", NewStringType::kInternalized),
                      close_fun)
                .FromJust();
          }
          Local<FunctionTemplate> importScripts_fun_template =
              FunctionTemplate::New(isolate_, Worker::ImportScripts,
                                    this_value);
          Local<Function> importScripts_fun;
          if (importScripts_fun_template->GetFunction(context).ToLocal(
                  &importScripts_fun)) {
            global
                ->Set(context,
                      v8::String::NewFromUtf8Literal(
                          isolate_, "importScripts",
                          NewStringType::kInternalized),
                      importScripts_fun)
                .FromJust();
          }
          // First run the script
          Local<String> file_name =
              String::NewFromUtf8Literal(isolate_, "unnamed");
          Local<String> source =
              String::NewFromUtf8(isolate_, script_).ToLocalChecked();
          success = Shell::ExecuteString(isolate_, source, file_name,
                                         Shell::kReportExceptions);
        }
        if (!Shell::FinishExecuting(isolate_, context_)) success = false;
        if (success) {
          bool handler_present;
          {
            HandleScope scope(isolate_);
            Local<Context> context = context_.Get(isolate_);
            Context::Scope context_scope(context);
            Local<Object> global = context->Global();
            // Check that there's a message handler
            MaybeLocal<Value> maybe_onmessage = global->Get(
                context,
                String::NewFromUtf8Literal(isolate_, "onmessage",
                                           NewStringType::kInternalized));
            Local<Value> onmessage;
            handler_present =
                maybe_onmessage.ToLocal(&onmessage) && onmessage->IsFunction();
          }
          if (handler_present) {
            // Now wait for messages.
            ProcessMessages();
          }
        }
      }
      Shell::CollectGarbage(isolate_);
    }
    EnterTerminatedState();
    Shell::ResetOnProfileEndListener(isolate_);
    context_.Reset();
    platform::NotifyIsolateShutdown(g_default_platform, isolate_);
  }
  isolate_->Dispose();
  isolate_ = nullptr;
  // Post nullptr to wake the thread waiting on GetMessage() if there is one.
  out_queue_.Enqueue(nullptr);
  out_semaphore_.Signal();
  // Also post an cleanup task to the parent isolate, so that it sees that this
  // worker is terminated and can clean it up in a thread-safe way.
  g_platform->GetForegroundTaskRunner(parent_isolate_)
      ->PostTask(std::make_unique<CleanUpWorkerTask>(parent_isolate_,
                                                     this->shared_from_this()));
}
References v8::Isolate::CreateParams::array_buffer_allocator, v8::Shell::array_buffer_allocator, CHECK, Close(), v8::Shell::CollectGarbage(), context_, v8::Shell::CreateEvaluationContext(), v8::Isolate::Dispose(), v8::SerializationDataQueue::Enqueue(), EnterTerminatedState(), v8::Shell::ExecuteString(), v8::Shell::FinishExecuting(), flush_denormals_, v8::anonymous_namespace{d8.cc}::g_default_platform, v8::anonymous_namespace{d8.cc}::g_platform, v8::Object::Get(), v8::Platform::GetForegroundTaskRunner(), v8::Context::Global(), ImportScripts(), v8::Shell::Initialize(), isolate_, v8::kInternalized, kPrepareRunning, v8::Shell::kReportExceptions, kRunning, v8::Isolate::New(), v8::FunctionTemplate::New(), v8::External::New(), v8::String::NewFromUtf8(), v8::String::NewFromUtf8Literal(), v8::platform::NotifyIsolateShutdown(), out_queue_, out_semaphore_, parent_isolate_, PostMessageOut(), ProcessMessages(), v8::Shell::ResetOnProfileEndListener(), script_, v8::Object::Set(), SetCurrentWorker(), v8::base::Semaphore::Signal(), started_semaphore_, state_, task_manager_, task_runner_, and v8::MaybeLocal< T >::ToLocal().
GetCurrentWorker()
Worker * v8::Worker::GetCurrentWorker () [static]
Definition at line 5570 of file d8.cc.
{ return current_worker_; }
References v8::anonymous_namespace{d8.cc}::current_worker_.
Referenced by v8::Shell::OnExit().
GetMessage()
std::unique_ptr< SerializationData > v8::Worker::GetMessage (Isolate * requester)
Definition at line 5452 of file d8.cc.
                                                                      {
  std::unique_ptr<SerializationData> result;
  while (!out_queue_.Dequeue(&result)) {
    // If the worker is no longer running, and there are no messages in the
    // queue, don't expect any more messages from it.
    if (!is_running()) break;
    out_semaphore_.ParkedWait(
        reinterpret_cast<i::Isolate*>(requester)->main_thread_local_isolate());
  }
  return result;
}
References v8::SerializationDataQueue::Dequeue(), is_running(), out_queue_, out_semaphore_, v8::internal::ParkingSemaphore::ParkedWait(), and v8::base::internal::result.
ImportScripts()
void v8::Worker::ImportScripts (const v8::FunctionCallbackInfo< v8::Value > & info) [static], [private]
Definition at line 5744 of file d8.cc.
                                                                      {
  Shell::ExecuteFile(info);
}
References v8::Shell::ExecuteFile().
Referenced by ExecuteInThread().
is_running()
bool v8::Worker::is_running () const [private]
Definition at line 5382 of file d8.cc.
{ return state_.load() == State::kRunning; }
References kRunning, and state_.
Referenced by EnterTerminatedState(), GetMessage(), PostMessage(), ProcessMessage(), and ProcessMessages().
IsTerminated()
bool v8::Worker::IsTerminated () const [inline]
Definition at line 225 of file d8.h.
{ return state_ == State::kTerminated; }
References kTerminated, and state_.
PostMessage()
void v8::Worker::PostMessage (std::unique_ptr< SerializationData > data)
Definition at line 5428 of file d8.cc.
                                                              {
  base::MutexGuard lock_guard(&worker_mutex_);
  if (!is_running()) return;
  std::unique_ptr<v8::Task> task(new ProcessMessageTask(
      task_manager_, shared_from_this(), std::move(data)));
  task_runner_->PostNonNestableTask(std::move(task));
}
References is_running(), ProcessMessageTask, task_manager_, task_runner_, and worker_mutex_.
PostMessageOut()
void v8::Worker::PostMessageOut (const v8::FunctionCallbackInfo< v8::Value > & info) [static], [private]
Definition at line 5717 of file d8.cc.
                                                                       {
  DCHECK(i::ValidateCallbackInfo(info));
  Isolate* isolate = info.GetIsolate();
  HandleScope handle_scope(isolate);
  if (info.Length() < 1) {
    ThrowError(isolate, "Invalid argument");
    return;
  }
  Local<Value> message = info[0];
  Local<Value> transfer = Undefined(isolate);
  std::unique_ptr<SerializationData> data =
      Shell::SerializeValue(isolate, message, transfer);
  if (data) {
    DCHECK(info.Data()->IsExternal());
    Local<External> this_value = info.Data().As<External>();
    Worker* worker = static_cast<Worker*>(this_value->Value());
    worker->out_queue_.Enqueue(std::move(data));
    worker->out_semaphore_.Signal();
    g_platform->GetForegroundTaskRunner(worker->parent_isolate_)
        ->PostTask(std::make_unique<CheckMessageFromWorkerTask>(
            worker->parent_isolate_, worker->shared_from_this()));
  }
}
References v8::FunctionCallbackInfo< T >::Data(), DCHECK, v8::SerializationDataQueue::Enqueue(), v8::anonymous_namespace{d8.cc}::g_platform, v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::Length(), out_queue_, v8::Shell::SerializeValue(), v8::anonymous_namespace{d8.cc}::ThrowError(), v8::Undefined(), and v8::internal::ValidateCallbackInfo().
Referenced by ExecuteInThread().
ProcessMessage()
void v8::Worker::ProcessMessage (std::unique_ptr< SerializationData > data) [private]
Definition at line 5505 of file d8.cc.
                                                                 {
  if (!is_running()) return;
  DCHECK_NOT_NULL(isolate_);
  HandleScope scope(isolate_);
  Local<Context> context = context_.Get(isolate_);
  Context::Scope context_scope(context);
  Local<Object> global = context->Global();
  // Get the message handler.
  MaybeLocal<Value> maybe_onmessage = global->Get(
      context, String::NewFromUtf8Literal(isolate_, "onmessage",
                                          NewStringType::kInternalized));
  Local<Value> onmessage;
  if (!maybe_onmessage.ToLocal(&onmessage) || !onmessage->IsFunction()) return;
  Local<Function> onmessage_fun = onmessage.As<Function>();
  v8::TryCatch try_catch(isolate_);
  try_catch.SetVerbose(true);
  Local<Value> value;
  if (Shell::DeserializeValue(isolate_, std::move(data)).ToLocal(&value)) {
    DCHECK(!isolate_->IsExecutionTerminating());
    Local<Object> event = Object::New(isolate_);
    event
        ->CreateDataProperty(
            context,
            String::NewFromUtf8Literal(isolate_, "data",
                                       NewStringType::kInternalized),
            value)
        .ToChecked();
    Local<Value> argv[] = {event};
    MaybeLocal<Value> result = onmessage_fun->Call(context, global, 1, argv);
    USE(result);
  }
  if (isolate_->IsExecutionTerminating()) {
    // Re-schedule an interrupt in case the worker is going to run more code
    // and never return to the event queue.
    isolate_->TerminateExecution();
  }
}
References v8::Local< T >::As(), context_, DCHECK, DCHECK_NOT_NULL, v8::Shell::DeserializeValue(), v8::Object::Get(), v8::Context::Global(), is_running(), v8::Isolate::IsExecutionTerminating(), isolate_, v8::kInternalized, v8::Object::New(), v8::String::NewFromUtf8Literal(), v8::base::internal::result, v8::Isolate::TerminateExecution(), v8::MaybeLocal< T >::ToLocal(), USE, and v8::internal::value.
ProcessMessages()
void v8::Worker::ProcessMessages () [private]
Definition at line 5545 of file d8.cc.
                             {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(isolate_);
  i::SaveAndSwitchContext saved_context(i_isolate, i::Context());
  SealHandleScope shs(isolate_);
  TryCatch try_catch(isolate_);
  try_catch.SetVerbose(true);
  while (is_running() && v8::platform::PumpMessageLoop(
                             g_default_platform, isolate_,
                             platform::MessageLoopBehavior::kWaitForWork)) {
    if (try_catch.HasCaught()) return;
    if (is_running()) {
      MicrotasksScope::PerformCheckpoint(isolate_);
    }
  }
}
References v8::anonymous_namespace{d8.cc}::g_default_platform, v8::TryCatch::HasCaught(), is_running(), isolate_, v8::platform::kWaitForWork, v8::MicrotasksScope::PerformCheckpoint(), v8::platform::PumpMessageLoop(), and v8::TryCatch::SetVerbose().
Referenced by v8::Shell::CompleteMessageLoop(), v8::Shell::EmptyMessageQueues(), and ExecuteInThread().
SetCurrentWorker()
void v8::Worker::SetCurrentWorker (Worker * worker) [static], [private]
Definition at line 5564 of file d8.cc.
                                            {
  CHECK_NULL(current_worker_);
  current_worker_ = worker;
}
References CHECK_NULL, and v8::anonymous_namespace{d8.cc}::current_worker_.
Referenced by ExecuteInThread().
StartWorkerThread()
bool v8::Worker::StartWorkerThread (Isolate * requester, std::shared_ptr< Worker > worker, base::Thread::Priority priority) [static]
Definition at line 5384 of file d8.cc.
                                                            {
  auto expected = State::kReady;
  CHECK(
      worker->state_.compare_exchange_strong(expected, State::kPrepareRunning));
  auto thread = new WorkerThread(worker, priority);
  worker->thread_ = thread;
  if (!thread->Start()) return false;
  // Wait until the worker is ready to receive messages.
  worker->started_semaphore_.ParkedWait(
      reinterpret_cast<i::Isolate*>(requester)->main_thread_local_isolate());
  Shell::AddRunningWorker(std::move(worker));
  return true;
}
References v8::Shell::AddRunningWorker(), CHECK, kPrepareRunning, and kReady.
Referenced by v8::Shell::WorkerNew().
Terminate()
void v8::Worker::Terminate ()
Definition at line 5484 of file d8.cc.
                       {
  base::MutexGuard lock_guard(&worker_mutex_);
  auto expected = State::kRunning;
  if (!state_.compare_exchange_strong(expected, State::kTerminating)) return;
  std::unique_ptr<v8::Task> task(
      new TerminateTask(task_manager_, shared_from_this()));
  task_runner_->PostTask(std::move(task));
  // Also schedule an interrupt in case the worker is running code and never
  // returning to the event queue. Since we checked the state before, and we are
  // holding the {worker_mutex_}, it's safe to access the isolate.
  isolate_->TerminateExecution();
}
References isolate_, kRunning, kTerminating, state_, task_manager_, task_runner_, v8::Isolate::TerminateExecution(), TerminateTask, and worker_mutex_.
Referenced by Close(), and TerminateAndWaitForThread().
TerminateAndWaitForThread()
void v8::Worker::TerminateAndWaitForThread (const i::ParkedScope & parked)
Definition at line 5472 of file d8.cc.
                                                                 {
  USE(parked);
  Terminate();
  {
    base::MutexGuard lock_guard(&worker_mutex_);
    // Prevent double-joining.
    if (is_joined_) return;
    is_joined_ = true;
  }
  thread_->Join();
}
References is_joined_, v8::base::Thread::Join(), Terminate(), thread_, USE, and worker_mutex_.
TryGetMessage()
std::unique_ptr< SerializationData > v8::Worker::TryGetMessage ()
Definition at line 5464 of file d8.cc.
                                                       {
  std::unique_ptr<SerializationData> result;
  if (!out_queue_.Dequeue(&result)) {
    return nullptr;
  }
  return result;
}
References v8::SerializationDataQueue::Dequeue(), out_queue_, and v8::base::internal::result.
Friends And Related Function Documentation
ProcessMessageTask
friend class ProcessMessageTask [friend]
Definition at line 231 of file d8.h.
Referenced by PostMessage().
TerminateTask
friend class TerminateTask [friend]
Definition at line 232 of file d8.h.
Referenced by Terminate().
Member Data Documentation
context_
Global<Context> v8::Worker::context_ [private]
Definition at line 291 of file d8.h.
Referenced by ExecuteInThread(), and ProcessMessage().
flush_denormals_
bool v8::Worker::flush_denormals_ [private]
Definition at line 271 of file d8.h.
Referenced by ExecuteInThread().
is_joined_
bool v8::Worker::is_joined_ = false [private]
Definition at line 273 of file d8.h.
Referenced by TerminateAndWaitForThread().
isolate_
Isolate* v8::Worker::isolate_ = nullptr [private]
Definition at line 287 of file d8.h.
Referenced by ExecuteInThread(), v8::Serializer::FinalizeTransfer(), v8::Deserializer::GetSharedArrayBufferFromId(), v8::Serializer::GetSharedArrayBufferId(), v8::Deserializer::GetWasmModuleFromId(), v8::Serializer::GetWasmModuleTransferId(), v8::Serializer::PrepareTransfer(), ProcessMessage(), ProcessMessages(), v8::Deserializer::ReadValue(), Terminate(), v8::Serializer::ThrowDataCloneError(), and ~Worker().
kManagedTag
constexpr i::ExternalPointerTag v8::Worker::kManagedTag = i::kD8WorkerTag [static], [constexpr]
Definition at line 189 of file d8.h.
out_queue_
SerializationDataQueue v8::Worker::out_queue_ [private]
Definition at line 267 of file d8.h.
Referenced by ExecuteInThread(), GetMessage(), PostMessageOut(), and TryGetMessage().
out_semaphore_
i::ParkingSemaphore v8::Worker::out_semaphore_ {0} [private]
Definition at line 266 of file d8.h.
Referenced by ExecuteInThread(), and GetMessage().
parent_isolate_
Isolate* v8::Worker::parent_isolate_ [private]
Definition at line 288 of file d8.h.
Referenced by ExecuteInThread().
script_
char* v8::Worker::script_ [private]
Definition at line 270 of file d8.h.
Referenced by ExecuteInThread(), and ~Worker().
started_semaphore_
i::ParkingSemaphore v8::Worker::started_semaphore_ {0} [private]
Definition at line 275 of file d8.h.
Referenced by ExecuteInThread().
state_
std::atomic<State> v8::Worker::state_ [private]
Definition at line 272 of file d8.h.
Referenced by EnterTerminatedState(), ExecuteInThread(), is_running(), IsTerminated(), Terminate(), Worker(), and ~Worker().
task_manager_
i::CancelableTaskManager* v8::Worker::task_manager_ [private]
Definition at line 279 of file d8.h.
Referenced by EnterTerminatedState(), ExecuteInThread(), PostMessage(), and Terminate().
task_runner_
std::shared_ptr<TaskRunner> v8::Worker::task_runner_ [private]
Definition at line 278 of file d8.h.
Referenced by EnterTerminatedState(), ExecuteInThread(), PostMessage(), and Terminate().
thread_
base::Thread* v8::Worker::thread_ = nullptr [private]
Definition at line 269 of file d8.h.
Referenced by TerminateAndWaitForThread(), and ~Worker().
worker_mutex_
base::Mutex v8::Worker::worker_mutex_ [private]
Definition at line 283 of file d8.h.
Referenced by EnterTerminatedState(), PostMessage(), Terminate(), and TerminateAndWaitForThread().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/d8/d8.h
/mnt/V8SourceCode/src/d8/d8.cc