v8::internal::compiler::PrepareUsesVisitor Class Reference
Public Member Functions
PrepareUsesVisitor (Scheduler *scheduler, TFGraph *graph, Zone *zone)
void Run ()
Private Member Functions
void InitializePlacement (Node *node)
void VisitInputs (Node *node)
bool Visited (Node *node)
Private Attributes
Scheduler * scheduler_
Schedule * schedule_
TFGraph * graph_
BitVector visited_
ZoneStack< Node * > stack_
Detailed Description
Definition at line 1301 of file scheduler.cc.
Constructor & Destructor Documentation
PrepareUsesVisitor()
v8::internal::compiler::PrepareUsesVisitor::PrepareUsesVisitor (Scheduler * scheduler, TFGraph * graph, Zone * zone) [inline], [explicit]
Definition at line 1303 of file scheduler.cc.
      : scheduler_(scheduler),
        schedule_(scheduler->schedule_),
        graph_(graph),
        visited_(static_cast<int>(graph_->NodeCount()), zone),
        stack_(zone) {}
Member Function Documentation
InitializePlacement()
void v8::internal::compiler::PrepareUsesVisitor::InitializePlacement (Node * node) [inline], [private]
Definition at line 1320 of file scheduler.cc.
                                       {
    TRACE("Pre #%d:%s\n", node->id(), node->op()->mnemonic());
    DCHECK(!Visited(node));
    if (scheduler_->InitializePlacement(node) == Scheduler::kFixed) {
      // Fixed nodes are always roots for schedule late.
      scheduler_->schedule_root_nodes_.push_back(node);
      if (!schedule_->IsScheduled(node)) {
        // Make sure root nodes are scheduled in their respective blocks.
        TRACE("Scheduling fixed position node #%d:%s\n", node->id(),
              node->op()->mnemonic());
        IrOpcode::Value opcode = node->opcode();
        BasicBlock* block =
            opcode == IrOpcode::kParameter
                ? schedule_->start()
                : schedule_->block(NodeProperties::GetControlInput(node));
        DCHECK_NOT_NULL(block);
        schedule_->AddNode(block, node);
      }
    }
    stack_.push(node);
    visited_.Add(node->id());
  }
References v8::internal::BitVector::Add(), v8::internal::compiler::Schedule::AddNode(), v8::internal::compiler::Schedule::block(), v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::Node::id(), v8::internal::compiler::Scheduler::InitializePlacement(), v8::internal::compiler::Schedule::IsScheduled(), v8::internal::compiler::Scheduler::kFixed, v8::internal::compiler::Operator::mnemonic(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::ZoneVector< T >::push_back(), schedule_, v8::internal::compiler::Scheduler::schedule_root_nodes_, scheduler_, stack_, v8::internal::compiler::Schedule::start(), v8::internal::TRACE(), Visited(), and visited_.
Referenced by Run(), and VisitInputs().
Run()
void v8::internal::compiler::PrepareUsesVisitor::Run () [inline]
Definition at line 1310 of file scheduler.cc.
             {
    InitializePlacement(graph_->end());
    while (!stack_.empty()) {
      Node* node = stack_.top();
      stack_.pop();
      VisitInputs(node);
    }
  }
References v8::internal::compiler::TFGraph::end(), graph_, InitializePlacement(), stack_, and VisitInputs().
Referenced by v8::internal::compiler::Scheduler::PrepareUses().
Visited()
bool v8::internal::compiler::PrepareUsesVisitor::Visited (Node * node) [inline], [private]
Definition at line 1363 of file scheduler.cc.
{ return visited_.Contains(node->id()); }
References v8::internal::BitVector::Contains(), v8::internal::compiler::Node::id(), and visited_.
Referenced by InitializePlacement(), and VisitInputs().
VisitInputs()
void v8::internal::compiler::PrepareUsesVisitor::VisitInputs (Node * node) [inline], [private]
Definition at line 1343 of file scheduler.cc.
                               {
    DCHECK_NE(scheduler_->GetPlacement(node), Scheduler::kUnknown);
    bool is_scheduled = schedule_->IsScheduled(node);
    std::optional<int> coupled_control_edge =
        scheduler_->GetCoupledControlEdge(node);
    for (auto edge : node->input_edges()) {
      Node* to = edge.to();
      DCHECK_EQ(node, edge.from());
      if (!Visited(to)) {
        InitializePlacement(to);
      }
      TRACE("PostEdge #%d:%s->#%d:%s\n", node->id(), node->op()->mnemonic(),
            to->id(), to->op()->mnemonic());
      DCHECK_NE(scheduler_->GetPlacement(to), Scheduler::kUnknown);
      if (!is_scheduled && edge.index() != coupled_control_edge) {
        scheduler_->IncrementUnscheduledUseCount(to, node);
      }
    }
  }
References DCHECK_EQ, DCHECK_NE, v8::internal::compiler::Scheduler::GetCoupledControlEdge(), v8::internal::compiler::Scheduler::GetPlacement(), v8::internal::compiler::Node::id(), v8::internal::compiler::Scheduler::IncrementUnscheduledUseCount(), InitializePlacement(), v8::internal::compiler::Node::input_edges(), v8::internal::compiler::Schedule::IsScheduled(), v8::internal::compiler::Scheduler::kUnknown, v8::internal::compiler::Operator::mnemonic(), v8::internal::compiler::Node::op(), schedule_, scheduler_, v8::internal::TRACE(), and Visited().
Referenced by Run().
Member Data Documentation
graph_
TFGraph* v8::internal::compiler::PrepareUsesVisitor::graph_ [private]
Definition at line 1367 of file scheduler.cc.
Referenced by Run().
schedule_
Schedule* v8::internal::compiler::PrepareUsesVisitor::schedule_ [private]
Definition at line 1366 of file scheduler.cc.
Referenced by InitializePlacement(), and VisitInputs().
scheduler_
Scheduler* v8::internal::compiler::PrepareUsesVisitor::scheduler_ [private]
Definition at line 1365 of file scheduler.cc.
Referenced by InitializePlacement(), and VisitInputs().
stack_
ZoneStack<Node*> v8::internal::compiler::PrepareUsesVisitor::stack_ [private]
Definition at line 1369 of file scheduler.cc.
Referenced by InitializePlacement(), and Run().
visited_
BitVector v8::internal::compiler::PrepareUsesVisitor::visited_ [private]
Definition at line 1368 of file scheduler.cc.
Referenced by InitializePlacement(), and Visited().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/scheduler.cc