v8::internal::MaybeObjectHandle Class Reference
#include <maybe-handles.h>
Public Member Functions
MaybeObjectHandle ()
MaybeObjectHandle (Tagged< MaybeObject > object, Isolate *isolate)
MaybeObjectHandle (Tagged< Object > object, Isolate *isolate)
MaybeObjectHandle (Tagged< Smi > object, Isolate *isolate)
MaybeObjectHandle (Tagged< MaybeObject > object, LocalHeap *local_heap)
MaybeObjectHandle (Tagged< Object > object, LocalHeap *local_heap)
MaybeObjectHandle (Tagged< Smi > object, LocalHeap *local_heap)
MaybeObjectHandle (Handle< Object > object)
Tagged< MaybeObject > operator* () const
Tagged< MaybeObject > operator-> () const
IndirectHandle< Object > object () const
bool is_identical_to (const MaybeObjectHandle &other) const
bool is_null () const
HeapObjectReferenceType reference_type () const
Static Public Member Functions
static MaybeObjectHandle Weak (Tagged< Object > object, Isolate *isolate)
static MaybeObjectHandle Weak (Handle< Object > object)
Private Member Functions
MaybeObjectHandle (Tagged< Object > object, HeapObjectReferenceType reference_type, Isolate *isolate)
MaybeObjectHandle (Handle< Object > object, HeapObjectReferenceType reference_type)
Private Attributes
HeapObjectReferenceType reference_type_
MaybeHandle< Object > handle_
Friends
class MaybeObjectDirectHandle
Detailed Description
Definition at line 111 of file maybe-handles.h.
Constructor & Destructor Documentation
MaybeObjectHandle() [1/10]
v8::internal::MaybeObjectHandle::MaybeObjectHandle () [inline]
Definition at line 113 of file maybe-handles.h.
      : reference_type_(HeapObjectReferenceType::STRONG) {}
Referenced by Weak().
MaybeObjectHandle() [2/10]
v8::internal::MaybeObjectHandle::MaybeObjectHandle (Tagged< MaybeObject > object, Isolate * isolate) [inline]
Definition at line 49 of file maybe-handles-inl.h.
                                                       {
  Tagged<HeapObject> heap_object;
  DCHECK(!object.IsCleared());
  if (object.GetHeapObjectIfWeak(&heap_object)) {
    handle_ = handle(heap_object, isolate);
    reference_type_ = HeapObjectReferenceType::WEAK;
  } else {
    handle_ = handle(Cast<Object>(object), isolate);
    reference_type_ = HeapObjectReferenceType::STRONG;
  }
}
MaybeObjectHandle() [3/10]
v8::internal::MaybeObjectHandle::MaybeObjectHandle (Tagged< Object > object, Isolate * isolate) [inline]
Definition at line 78 of file maybe-handles-inl.h.
    : reference_type_(HeapObjectReferenceType::STRONG),
      handle_(object, isolate) {}
MaybeObjectHandle() [4/10]
v8::internal::MaybeObjectHandle::MaybeObjectHandle (Tagged< Smi > object, Isolate * isolate) [inline]
Definition at line 82 of file maybe-handles-inl.h.
    : reference_type_(HeapObjectReferenceType::STRONG),
      handle_(object, isolate) {}
MaybeObjectHandle() [5/10]
v8::internal::MaybeObjectHandle::MaybeObjectHandle (Tagged< MaybeObject > object, LocalHeap * local_heap) [inline]
Definition at line 62 of file maybe-handles-inl.h.
                                                            {
  Tagged<HeapObject> heap_object;
  DCHECK(!object.IsCleared());
  if (object.GetHeapObjectIfWeak(&heap_object)) {
    handle_ = handle(heap_object, local_heap);
    reference_type_ = HeapObjectReferenceType::WEAK;
  } else {
    handle_ = handle(Cast<Object>(object), local_heap);
    reference_type_ = HeapObjectReferenceType::STRONG;
  }
}
References v8::internal::DCHECK(), v8::internal::handle(), handle_, reference_type_, STRONG, and WEAK.
MaybeObjectHandle() [6/10]
v8::internal::MaybeObjectHandle::MaybeObjectHandle (Tagged< Object > object, LocalHeap * local_heap) [inline]
Definition at line 86 of file maybe-handles-inl.h.
    : reference_type_(HeapObjectReferenceType::STRONG),
      handle_(object, local_heap) {}
MaybeObjectHandle() [7/10]
v8::internal::MaybeObjectHandle::MaybeObjectHandle (Tagged< Smi > object, LocalHeap * local_heap) [inline]
Definition at line 91 of file maybe-handles-inl.h.
    : reference_type_(HeapObjectReferenceType::STRONG),
      handle_(object, local_heap) {}
MaybeObjectHandle() [8/10]
v8::internal::MaybeObjectHandle::MaybeObjectHandle (Handle< Object > object) [inline], [explicit]
Definition at line 75 of file maybe-handles-inl.h.
    : reference_type_(HeapObjectReferenceType::STRONG), handle_(object) {}
MaybeObjectHandle() [9/10]
v8::internal::MaybeObjectHandle::MaybeObjectHandle (Tagged< Object > object, HeapObjectReferenceType reference_type, Isolate * isolate) [inline], [private]
Definition at line 95 of file maybe-handles-inl.h.
    : reference_type_(reference_type), handle_(handle(object, isolate)) {}
MaybeObjectHandle() [10/10]
v8::internal::MaybeObjectHandle::MaybeObjectHandle (Handle< Object > object, HeapObjectReferenceType reference_type) [inline], [private]
Definition at line 100 of file maybe-handles-inl.h.
    : reference_type_(reference_type), handle_(object) {}
Member Function Documentation
is_identical_to()
bool v8::internal::MaybeObjectHandle::is_identical_to (const MaybeObjectHandle & other) const [inline]
Definition at line 113 of file maybe-handles-inl.h.
                                                                            {
  Handle<Object> this_handle;
  Handle<Object> other_handle;
  return reference_type_ == other.reference_type_ &&
         handle_.ToHandle(&this_handle) ==
             other.handle_.ToHandle(&other_handle) &&
         this_handle.is_identical_to(other_handle);
}
References handle_, v8::internal::HandleBase::is_identical_to(), and reference_type_.
is_null()
bool v8::internal::MaybeObjectHandle::is_null () const [inline]
Definition at line 131 of file maybe-handles.h.
{ return handle_.is_null(); }
References handle_.
Referenced by v8::internal::operator<<(), and v8::internal::compiler::JSHeapBroker::ReadFeedbackForPropertyAccess().
object()
IndirectHandle< Object > v8::internal::MaybeObjectHandle::object () const [inline]
Definition at line 138 of file maybe-handles-inl.h.
                                                       {
  return handle_.ToHandleChecked();
}
References handle_.
Referenced by v8::internal::compiler::JSHeapBroker::ReadFeedbackForPropertyAccess(), and v8::internal::LoadIC::UpdateCaches().
operator*()
Tagged< MaybeObject > v8::internal::MaybeObjectHandle::operator* () const [inline]
Definition at line 122 of file maybe-handles-inl.h.
                                                       {
  if (reference_type_ == HeapObjectReferenceType::WEAK) {
    return MakeWeak(*handle_.ToHandleChecked());
  } else {
    return *handle_.ToHandleChecked();
  }
}
References handle_, v8::internal::MakeWeak(), reference_type_, and WEAK.
operator->()
Tagged< MaybeObject > v8::internal::MaybeObjectHandle::operator-> () const [inline]
Definition at line 130 of file maybe-handles-inl.h.
                                                        {
  if (reference_type_ == HeapObjectReferenceType::WEAK) {
    return MakeWeak(*handle_.ToHandleChecked());
  } else {
    return *handle_.ToHandleChecked();
  }
}
References handle_, v8::internal::MakeWeak(), reference_type_, and WEAK.
reference_type()
HeapObjectReferenceType v8::internal::MaybeObjectHandle::reference_type () const [inline]
Definition at line 133 of file maybe-handles.h.
{ return reference_type_; }
References reference_type_.
Weak() [1/2]
MaybeObjectHandle v8::internal::MaybeObjectHandle::Weak (Handle< Object > object) [inline], [static]
Definition at line 104 of file maybe-handles-inl.h.
                                                               {
  return MaybeObjectHandle(object, HeapObjectReferenceType::WEAK);
}
References MaybeObjectHandle(), and WEAK.
Weak() [2/2]
MaybeObjectHandle v8::internal::MaybeObjectHandle::Weak (Tagged< Object > object, Isolate * isolate) [inline], [static]
Definition at line 108 of file maybe-handles-inl.h.
                                                            {
  return MaybeObjectHandle(object, HeapObjectReferenceType::WEAK, isolate);
}
References MaybeObjectHandle(), and WEAK.
Referenced by v8::internal::LoadIC::ComputeHandler(), v8::internal::StoreIC::ComputeHandler(), v8::internal::StoreHandler::StoreGlobal(), v8::internal::StoreHandler::StoreOwnTransition(), and v8::internal::StoreHandler::StoreTransition().
Friends And Related Function Documentation
MaybeObjectDirectHandle
friend class MaybeObjectDirectHandle [friend]
Definition at line 142 of file maybe-handles.h.
Member Data Documentation
handle_
MaybeHandle<Object> v8::internal::MaybeObjectHandle::handle_ [private]
Definition at line 145 of file maybe-handles.h.
Referenced by is_identical_to(), v8::internal::MaybeObjectDirectHandle::is_identical_to(), is_null(), v8::internal::MaybeHandle< v8::internal::Map >::MaybeHandle(), MaybeObjectHandle(), object(), operator*(), and operator->().
reference_type_
HeapObjectReferenceType v8::internal::MaybeObjectHandle::reference_type_ [private]
Definition at line 144 of file maybe-handles.h.
Referenced by is_identical_to(), v8::internal::MaybeObjectDirectHandle::is_identical_to(), v8::internal::MaybeHandle< v8::internal::Map >::MaybeHandle(), MaybeObjectHandle(), operator*(), operator->(), and reference_type().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/handles/maybe-handles.h
/mnt/V8SourceCode/src/handles/maybe-handles-inl.h