v8::internal::wasm::DescriptorsSectionIterator::GlobalEntry Class Reference
#include <module-decoder-impl.h>
Public Member Functions
uint32_t global_index () const
bool has_parent () const
uint32_t Parent ()
Private Member Functions
GlobalEntry (DescriptorsSectionIterator *decoder, uint32_t max_global_index)
Private Attributes
uint32_t global_index_
Friends
class DescriptorsSectionIterator
Additional Inherited Members
Detailed Description
Definition at line 3180 of file module-decoder-impl.h.
Constructor & Destructor Documentation
GlobalEntry()
v8::internal::wasm::DescriptorsSectionIterator::GlobalEntry::GlobalEntry (DescriptorsSectionIterator * decoder, uint32_t max_global_index) [inline], [private]
Definition at line 3201 of file module-decoder-impl.h.
        : Entry(decoder) {
      const uint8_t* pos = decoder->pc();
      global_index_ = consume_u32v("global index");
      if (global_index_ > max_global_index) {
        decoder->errorf(pos, "global index %u is out of range", global_index_);
        return;
      }
      if (global_index_ < decoder->next_min_global_index_) {
        decoder->errorf(pos, "global index %u is not in ascending order",
                        global_index_);
        return;
      }
      decoder->next_min_global_index_ = global_index_ + 1;
      pos = decoder->pc();
      uint32_t num_parents = consume_u32v("parent count");
      if (num_parents > 1) {
        decoder->errorf(pos, "invalid parent count %u", num_parents);
        return;
      }
      if (num_parents == 0) ProceedToMethods();
    }
References v8::internal::wasm::DescriptorsSectionIterator::Entry::consume_u32v(), v8::internal::wasm::DescriptorsSectionIterator::Entry::decoder(), v8::internal::wasm::Decoder::errorf(), global_index_, v8::internal::wasm::DescriptorsSectionIterator::next_min_global_index_, v8::internal::wasm::Decoder::pc(), and v8::internal::wasm::DescriptorsSectionIterator::Entry::ProceedToMethods().
Member Function Documentation
global_index()
uint32_t v8::internal::wasm::DescriptorsSectionIterator::GlobalEntry::global_index () const [inline]
Definition at line 3182 of file module-decoder-impl.h.
{ return global_index_; }
References global_index_.
Referenced by v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Direct_Impl().
has_parent()
bool v8::internal::wasm::DescriptorsSectionIterator::GlobalEntry::has_parent () const [inline]
Definition at line 3184 of file module-decoder-impl.h.
{ return state() == State::kParentOrImport; }
References v8::internal::wasm::DescriptorsSectionIterator::Entry::kParentOrImport, and v8::internal::wasm::DescriptorsSectionIterator::Entry::state().
Referenced by v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Direct_Impl().
Parent()
uint32_t v8::internal::wasm::DescriptorsSectionIterator::GlobalEntry::Parent () [inline]
Definition at line 3185 of file module-decoder-impl.h.
                      {
      DCHECK_EQ(state(), State::kParentOrImport);
      const uint8_t* pos = decoder()->pc();
      uint32_t result = consume_u32v("parent");
      if (result >= global_index_) {
        decoder()->errorf(pos, "parent index %u must be lower than %u", result,
                          global_index_);
        return result;
      }
      ProceedToMethods();
      return result;
    }
References v8::internal::wasm::DescriptorsSectionIterator::Entry::consume_u32v(), DCHECK_EQ, v8::internal::wasm::DescriptorsSectionIterator::Entry::decoder(), v8::internal::wasm::Decoder::errorf(), global_index_, v8::internal::wasm::DescriptorsSectionIterator::Entry::kParentOrImport, v8::internal::wasm::Decoder::pc(), v8::internal::wasm::DescriptorsSectionIterator::Entry::ProceedToMethods(), v8::base::internal::result, and v8::internal::wasm::DescriptorsSectionIterator::Entry::state().
Referenced by v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Direct_Impl().
Friends And Related Function Documentation
DescriptorsSectionIterator
friend class DescriptorsSectionIterator [friend]
Definition at line 3199 of file module-decoder-impl.h.
Member Data Documentation
global_index_
uint32_t v8::internal::wasm::DescriptorsSectionIterator::GlobalEntry::global_index_ [private]
Definition at line 3224 of file module-decoder-impl.h.
Referenced by global_index(), GlobalEntry(), and Parent().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/module-decoder-impl.h