v8_inspector::protocol::StringUtil Class Reference
#include <string-util.h>
Static Public Member Functions
static String fromUTF8 (const uint8_t *data, size_t length)
static String fromUTF16LE (const uint16_t *data, size_t length)
static const uint8_t * CharactersLatin1 (const String &s)
static const uint8_t * CharactersUTF8 (const String &s)
static const uint16_t * CharactersUTF16 (const String &s)
static size_t CharacterCount (const String &s)
Detailed Description
Definition at line 28 of file string-util.h.
Member Function Documentation
CharacterCount()
static size_t v8_inspector::protocol::StringUtil::CharacterCount (const String & s) [inline], [static]
Definition at line 43 of file string-util.h.
{ return s.length(); }
References v8_inspector::String16::length().
CharactersLatin1()
static const uint8_t* v8_inspector::protocol::StringUtil::CharactersLatin1 (const String & s) [inline], [static]
Definition at line 38 of file string-util.h.
{ return nullptr; }
CharactersUTF16()
static const uint16_t* v8_inspector::protocol::StringUtil::CharactersUTF16 (const String & s) [inline], [static]
Definition at line 40 of file string-util.h.
                                                          {
    return s.characters16();
  }
References v8_inspector::String16::characters16().
CharactersUTF8()
static const uint8_t* v8_inspector::protocol::StringUtil::CharactersUTF8 (const String & s) [inline], [static]
Definition at line 39 of file string-util.h.
{ return nullptr; }
fromUTF16LE()
static String v8_inspector::protocol::StringUtil::fromUTF16LE (const uint16_t * data, size_t length) [inline], [static]
Definition at line 34 of file string-util.h.
                                                                 {
    return String16::fromUTF16LE(data, length);
  }
References v8_inspector::String16::fromUTF16LE(), and v8::internal::length.
fromUTF8()
static String v8_inspector::protocol::StringUtil::fromUTF8 (const uint8_t * data, size_t length) [inline], [static]
Definition at line 30 of file string-util.h.
                                                             {
    return String16::fromUTF8(reinterpret_cast<const char*>(data), length);
  }
References v8_inspector::String16::fromUTF8(), and v8::internal::length.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/inspector/string-util.h