v8::internal::compiler::turboshaft::ConditionWithHint Class Reference
#include <assembler.h>
Public Member Functions
ConditionWithHint (V< Word32 > condition, BranchHint hint=BranchHint::kNone)
template<typename T >
ConditionWithHint (T condition, BranchHint hint=BranchHint::kNone) requires(std
V< Word32 > condition () const
BranchHint hint () const
Private Attributes
V< Word32 > condition_
BranchHint hint_
Detailed Description
Definition at line 332 of file assembler.h.
Constructor & Destructor Documentation
ConditionWithHint() [1/2]
v8::internal::compiler::turboshaft::ConditionWithHint::ConditionWithHint (V< Word32 > condition, BranchHint hint = BranchHint::kNone) [inline]
Definition at line 334 of file assembler.h.
      : condition_(condition), hint_(hint) {}
ConditionWithHint() [2/2]
template<typename T >
v8::internal::compiler::turboshaft::ConditionWithHint::ConditionWithHint (T condition, BranchHint hint = BranchHint::kNone) [inline]
Definition at line 340 of file assembler.h.
      : ConditionWithHint(V<Word32>{condition}, hint) {}
Member Function Documentation
condition()
V<Word32> v8::internal::compiler::turboshaft::ConditionWithHint::condition () const [inline]
Definition at line 346 of file assembler.h.
{ return condition_; }
Referenced by v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Branch(), v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >::ControlFlowHelper_GotoIf(), v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >::ControlFlowHelper_GotoIfNot(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::GotoIf(), and v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::GotoIfNot().
hint()
BranchHint v8::internal::compiler::turboshaft::ConditionWithHint::hint () const [inline]
Definition at line 347 of file assembler.h.
{ return hint_; }
Referenced by v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Branch(), v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >::ControlFlowHelper_GotoIf(), v8::internal::compiler::turboshaft::GenericAssemblerOpInterface< Assembler >::ControlFlowHelper_GotoIfNot(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::GotoIf(), and v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::GotoIfNot().
Member Data Documentation
condition_
V<Word32> v8::internal::compiler::turboshaft::ConditionWithHint::condition_ [private]
Definition at line 350 of file assembler.h.
hint_
BranchHint v8::internal::compiler::turboshaft::ConditionWithHint::hint_ [private]
Definition at line 351 of file assembler.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/assembler.h