v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::NoSlackTrackingChangeDependency Class Reference
Public Member Functions
NoSlackTrackingChangeDependency (MapRef map)
bool IsValid (JSHeapBroker *broker) const override
void PrepareInstall (JSHeapBroker *) const override
void Install (JSHeapBroker *, PendingDependencies *) const override
Private Member Functions
size_t Hash () const override
bool Equals (const CompilationDependency *that) const override
Private Attributes
const MapRef map_
Additional Inherited Members
Detailed Description
Definition at line 1120 of file compilation-dependencies.cc.
Constructor & Destructor Documentation
NoSlackTrackingChangeDependency()
v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::NoSlackTrackingChangeDependency::NoSlackTrackingChangeDependency (MapRef map) [inline], [explicit]
Definition at line 1122 of file compilation-dependencies.cc.
      : CompilationDependency(kNoSlackTrackingChange), map_(map) {}
Member Function Documentation
Equals()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::NoSlackTrackingChangeDependency::Equals (const CompilationDependency * that) const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 1146 of file compilation-dependencies.cc.
                                                                {
    const NoSlackTrackingChangeDependency* const zat =
        that->AsNoSlackTrackingChange();
    return map_.equals(zat->map_);
  }
References map_.
Hash()
size_t v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::NoSlackTrackingChangeDependency::Hash () const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 1141 of file compilation-dependencies.cc.
                               {
    ObjectRef::Hash h;
    return base::hash_combine(h(map_));
  }
References h(), v8::internal::Hash(), and v8::base::hash_combine().
Install()
void v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::NoSlackTrackingChangeDependency::Install (JSHeapBroker * , PendingDependencies *) const [inline], [override]
Definition at line 1138 of file compilation-dependencies.cc.
{}
IsValid()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::NoSlackTrackingChangeDependency::IsValid (JSHeapBroker * broker) const [inline], [override], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 1125 of file compilation-dependencies.cc.
                                                    {
    if (map_.construction_counter() != 0 &&
        map_.object()->construction_counter() == 0) {
      // Slack tracking finished during compilation.
      return false;
    }
    return map_.UnusedPropertyFields() ==
               map_.object()->UnusedPropertyFields() &&
           map_.GetInObjectProperties() ==
               map_.object()->GetInObjectProperties();
  }
PrepareInstall()
void v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::NoSlackTrackingChangeDependency::PrepareInstall (JSHeapBroker *) const [inline], [override], [virtual]
Reimplemented from v8::internal::compiler::CompilationDependency.
Definition at line 1137 of file compilation-dependencies.cc.
{}
Member Data Documentation
map_
const MapRef v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::NoSlackTrackingChangeDependency::map_ [private]
Definition at line 1152 of file compilation-dependencies.cc.
Referenced by Equals().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/compilation-dependencies.cc