v8::internal::compiler::ContextAccess Class Reference
#include <js-operator.h>
Public Member Functions
ContextAccess (size_t depth, size_t index, bool immutable)
size_t depth () const
size_t index () const
bool immutable () const
Private Attributes
const bool immutable_
const uint16_t depth_
const uint32_t index_
Detailed Description
Definition at line 338 of file js-operator.h.
Constructor & Destructor Documentation
ContextAccess()
v8::internal::compiler::ContextAccess::ContextAccess (size_t depth, size_t index, bool immutable)
Definition at line 155 of file js-operator.cc.
    : immutable_(immutable),
      depth_(static_cast<uint16_t>(depth)),
      index_(static_cast<uint32_t>(index)) {
  DCHECK(depth <= std::numeric_limits<uint16_t>::max());
  DCHECK(index <= std::numeric_limits<uint32_t>::max());
}
References v8::internal::DCHECK(), depth(), and index().
Member Function Documentation
depth()
size_t v8::internal::compiler::ContextAccess::depth () const [inline]
Definition at line 342 of file js-operator.h.
{ return depth_; }
References depth_.
Referenced by ContextAccess(), v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContext(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadContext(), v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContextNoCell(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadContextNoCell(), v8::internal::compiler::JSContextSpecialization::ReduceJSStoreContext(), v8::internal::compiler::JSTypedLowering::ReduceJSStoreContext(), v8::internal::compiler::JSContextSpecialization::ReduceJSStoreContextNoCell(), v8::internal::compiler::JSTypedLowering::ReduceJSStoreContextNoCell(), v8::internal::compiler::JSContextSpecialization::SimplifyJSLoadContext(), v8::internal::compiler::JSContextSpecialization::SimplifyJSLoadContextNoCell(), v8::internal::compiler::JSContextSpecialization::SimplifyJSStoreContext(), and v8::internal::compiler::JSContextSpecialization::SimplifyJSStoreContextNoCell().
immutable()
bool v8::internal::compiler::ContextAccess::immutable () const [inline]
Definition at line 344 of file js-operator.h.
{ return immutable_; }
References immutable_.
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContext(), v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContextNoCell(), and v8::internal::compiler::JSContextSpecialization::SimplifyJSLoadContextNoCell().
index()
size_t v8::internal::compiler::ContextAccess::index () const [inline]
Definition at line 343 of file js-operator.h.
{ return index_; }
References index_.
Referenced by ContextAccess(), v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContext(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadContext(), v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContextNoCell(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadContextNoCell(), v8::internal::compiler::JSContextSpecialization::ReduceJSStoreContext(), v8::internal::compiler::JSTypedLowering::ReduceJSStoreContext(), v8::internal::compiler::JSTypedLowering::ReduceJSStoreContextNoCell(), v8::internal::compiler::JSContextSpecialization::SimplifyJSLoadContext(), v8::internal::compiler::JSContextSpecialization::SimplifyJSLoadContextNoCell(), v8::internal::compiler::JSContextSpecialization::SimplifyJSStoreContext(), and v8::internal::compiler::JSContextSpecialization::SimplifyJSStoreContextNoCell().
Member Data Documentation
depth_
const uint16_t v8::internal::compiler::ContextAccess::depth_ [private]
Definition at line 350 of file js-operator.h.
Referenced by depth().
immutable_
const bool v8::internal::compiler::ContextAccess::immutable_ [private]
Definition at line 349 of file js-operator.h.
Referenced by immutable().
index_
const uint32_t v8::internal::compiler::ContextAccess::index_ [private]
Definition at line 351 of file js-operator.h.
Referenced by index().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/js-operator.h
/mnt/V8SourceCode/src/compiler/js-operator.cc