v8::internal::compiler::JSGraphAssembler::CatchScope Class Reference
#include <graph-assembler.h>
Public Member Functions
~CatchScope ()
bool has_handler () const
bool is_outermost () const
CatchScope * parent () const
void set_has_handler (bool v)
void set_gasm (JSGraphAssembler *v)
bool has_exceptional_control_flow () const
void RegisterIfExceptionNode (Node *if_exception)
void MergeExceptionalPaths (TNode< Object > *exception_out, Effect *effect_out, Control *control_out)
Static Public Member Functions
static CatchScope Outermost (Zone *zone)
static CatchScope Inner (Zone *zone, JSGraphAssembler *gasm)
Private Member Functions
CatchScope (Zone *zone)
CatchScope (Zone *zone, JSGraphAssembler *gasm)
Private Attributes
JSGraphAssembler * gasm_ = nullptr
CatchScope *const parent_ = nullptr
bool has_handler_ = false
NodeVector if_exception_nodes_
Detailed Description
Definition at line 1127 of file graph-assembler.h.
Constructor & Destructor Documentation
CatchScope() [1/2]
v8::internal::compiler::JSGraphAssembler::CatchScope::CatchScope (Zone * zone) [inline], [explicit], [private]
Definition at line 1130 of file graph-assembler.h.
: if_exception_nodes_(zone) {}
CatchScope() [2/2]
v8::internal::compiler::JSGraphAssembler::CatchScope::CatchScope (Zone * zone, JSGraphAssembler * gasm) [inline], [private]
Definition at line 1133 of file graph-assembler.h.
        : gasm_(gasm),
          parent_(gasm->catch_scope_),
          has_handler_(true),
          if_exception_nodes_(zone) {
      DCHECK_NOT_NULL(gasm_);
      gasm_->catch_scope_ = this;
    }
References DCHECK_NOT_NULL.
 CatchScope()
v8::internal::compiler::JSGraphAssembler::CatchScope::~CatchScope () [inline]
Definition at line 1143 of file graph-assembler.h.
{ gasm_->catch_scope_ = parent_; }
Member Function Documentation
has_exceptional_control_flow()
bool v8::internal::compiler::JSGraphAssembler::CatchScope::has_exceptional_control_flow () const [inline]
Definition at line 1166 of file graph-assembler.h.
                                              {
      return !if_exception_nodes_.empty();
    }
has_handler()
bool v8::internal::compiler::JSGraphAssembler::CatchScope::has_handler () const [inline]
Definition at line 1150 of file graph-assembler.h.
{ return has_handler_; }
Inner()
static CatchScope v8::internal::compiler::JSGraphAssembler::CatchScope::Inner (Zone * zone, JSGraphAssembler * gasm) [inline], [static]
Definition at line 1146 of file graph-assembler.h.
                                                                {
      return {zone, gasm};
    }
Referenced by v8::internal::compiler::JSCallReducerAssembler::TryCatchBuilder0::Catch().
is_outermost()
bool v8::internal::compiler::JSGraphAssembler::CatchScope::is_outermost () const [inline]
Definition at line 1151 of file graph-assembler.h.
{ return parent_ == nullptr; }
MergeExceptionalPaths()
void v8::internal::compiler::JSGraphAssembler::CatchScope::MergeExceptionalPaths (TNode< Object > * exception_out, Effect * effect_out, Control * control_out) [inline]
Definition at line 1175 of file graph-assembler.h.
                                                     {
      DCHECK(has_handler());
      DCHECK(has_exceptional_control_flow());
      const int size = static_cast<int>(if_exception_nodes_.size());
      if (size == 1) {
        // No merge needed.
        Node* e = if_exception_nodes_.at(0);
        *exception_out = TNode<Object>::UncheckedCast(e);
        *effect_out = Effect(e);
        *control_out = Control(e);
      } else {
        DCHECK_GT(size, 1);
        Node* merge = gasm_->graph()->NewNode(gasm_->common()->Merge(size),
                                              size, if_exception_nodes_.data());
        // These phis additionally take {merge} as an input. Temporarily add
        // it to the list.
        if_exception_nodes_.push_back(merge);
        const int size_with_merge =
            static_cast<int>(if_exception_nodes_.size());
        Node* ephi = gasm_->graph()->NewNode(gasm_->common()->EffectPhi(size),
                                             size_with_merge,
                                             if_exception_nodes_.data());
        Node* phi = gasm_->graph()->NewNode(
            gasm_->common()->Phi(MachineRepresentation::kTagged, size),
            size_with_merge, if_exception_nodes_.data());
        if_exception_nodes_.pop_back();
        *exception_out = TNode<Object>::UncheckedCast(phi);
        *effect_out = Effect(ephi);
        *control_out = Control(merge);
      }
    }
References v8::internal::DCHECK(), DCHECK_GT, v8::internal::kTagged, size(), and v8::internal::TNode< T >::UncheckedCast().
Referenced by v8::internal::compiler::JSCallReducerAssembler::TryCatchBuilder0::Catch(), v8::internal::compiler::JSCallReducer::ReleaseEffectAndControlFromAssembler(), v8::internal::compiler::JSNativeContextSpecialization::ReleaseEffectAndControlFromAssembler(), and v8::internal::compiler::JSCallReducer::ReplaceWithSubgraph().
Outermost()
static CatchScope v8::internal::compiler::JSGraphAssembler::CatchScope::Outermost (Zone * zone) [inline], [static]
Definition at line 1145 of file graph-assembler.h.
{ return CatchScope{zone}; }
parent()
CatchScope* v8::internal::compiler::JSGraphAssembler::CatchScope::parent () const [inline]
Definition at line 1152 of file graph-assembler.h.
{ return parent_; }
RegisterIfExceptionNode()
void v8::internal::compiler::JSGraphAssembler::CatchScope::RegisterIfExceptionNode (Node * if_exception) [inline]
Definition at line 1170 of file graph-assembler.h.
                                                     {
      DCHECK(has_handler());
      if_exception_nodes_.push_back(if_exception);
    }
References v8::internal::DCHECK().
set_gasm()
void v8::internal::compiler::JSGraphAssembler::CatchScope::set_gasm (JSGraphAssembler * v) [inline]
Definition at line 1160 of file graph-assembler.h.
                                       {
      DCHECK(is_outermost());
      DCHECK_NOT_NULL(v);
      gasm_ = v;
    }
References v8::internal::DCHECK(), and DCHECK_NOT_NULL.
set_has_handler()
void v8::internal::compiler::JSGraphAssembler::CatchScope::set_has_handler (bool v) [inline]
Definition at line 1156 of file graph-assembler.h.
                                 {
      DCHECK(is_outermost());
      has_handler_ = v;
    }
References v8::internal::DCHECK().
Member Data Documentation
gasm_
JSGraphAssembler* v8::internal::compiler::JSGraphAssembler::CatchScope::gasm_ = nullptr [private]
Definition at line 1215 of file graph-assembler.h.
has_handler_
bool v8::internal::compiler::JSGraphAssembler::CatchScope::has_handler_ = false [private]
Definition at line 1217 of file graph-assembler.h.
if_exception_nodes_
NodeVector v8::internal::compiler::JSGraphAssembler::CatchScope::if_exception_nodes_ [private]
Definition at line 1218 of file graph-assembler.h.
parent_
CatchScope* const v8::internal::compiler::JSGraphAssembler::CatchScope::parent_ = nullptr [private]
Definition at line 1216 of file graph-assembler.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/graph-assembler.h