v8::internal::maglev::LoopOptimizationProcessor Class Reference
#include <maglev-post-hoc-optimizations-processors.h>
Public Member Functions
LoopOptimizationProcessor (MaglevCompilationInfo *info)
void PreProcessGraph (Graph *graph)
void PostPhiProcessing ()
void PostProcessBasicBlock (BasicBlock *block)
BlockProcessResult PreProcessBasicBlock (BasicBlock *block)
bool IsLoopPhi (Node *input)
bool CanHoist (Node *candidate)
ProcessResult Process (LoadTaggedFieldForContextSlotNoCells *ltf, const ProcessingState &state)
ProcessResult Process (LoadTaggedFieldForProperty *ltf, const ProcessingState &state)
ProcessResult Process (StringLength *len, const ProcessingState &state)
ProcessResult Process (LoadTypedArrayLength *len, const ProcessingState &state)
ProcessResult ProcessNamedLoad (Node *load, ValueNode *object, KnownNodeAspects::LoadedPropertyMapKey name)
ProcessResult Process (CheckMaps *maps, const ProcessingState &state)
template<typename NodeT >
ProcessResult Process (NodeT *node, const ProcessingState &state)
void PostProcessGraph (Graph *graph)
Public Attributes
Zone * zone
BasicBlock * current_block
const LoopEffects * loop_effects
bool was_deoptimized
Detailed Description
Definition at line 51 of file maglev-post-hoc-optimizations-processors.h.
Constructor & Destructor Documentation
LoopOptimizationProcessor()
v8::internal::maglev::LoopOptimizationProcessor::LoopOptimizationProcessor (MaglevCompilationInfo * info) [inline], [explicit]
Definition at line 53 of file maglev-post-hoc-optimizations-processors.h.
      : zone(info->zone()) {
    was_deoptimized =
        info->toplevel_compilation_unit()->feedback().was_once_deoptimized();
  }
References v8::internal::maglev::MaglevCompilationUnit::feedback(), v8::internal::maglev::MaglevCompilationInfo::toplevel_compilation_unit(), was_deoptimized, and v8::internal::compiler::FeedbackVectorRef::was_once_deoptimized().
Member Function Documentation
CanHoist()
bool v8::internal::maglev::LoopOptimizationProcessor::CanHoist (Node * candidate) [inline]
Definition at line 86 of file maglev-post-hoc-optimizations-processors.h.
                                 {
    DCHECK_EQ(candidate->input_count(), 1);
    DCHECK(current_block->is_loop());
    ValueNode* input = candidate->input(0).node();
    DCHECK(!IsLoopPhi(input));
    // For hoisting an instruction we need:
    // * A unique loop entry block.
    // * Inputs live before the loop (i.e., not defined inside the loop).
    // * No hoisting over checks (done eagerly by clearing loop_effects).
    // TODO(olivf): We should enforce loops having a unique entry block at graph
    // building time.
    if (current_block->predecessor_count() != 2) return false;
    BasicBlock* loop_entry = current_block->predecessor_at(0);
    if (loop_entry->successors().size() != 1) {
      return false;
    }
    if (IsConstantNode(input->opcode())) return true;
    return input->owner() != current_block;
  }
References current_block, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::maglev::NodeBase::input(), v8::internal::maglev::NodeBase::input_count(), v8::internal::maglev::BasicBlock::is_loop(), v8::internal::maglev::IsConstantNode(), IsLoopPhi(), v8::internal::maglev::Input::node(), v8::internal::maglev::NodeBase::opcode(), v8::internal::maglev::NodeBase::owner(), v8::internal::maglev::BasicBlock::predecessor_at(), v8::internal::maglev::BasicBlock::predecessor_count(), and v8::internal::maglev::BasicBlock::successors().
Referenced by Process(), and ProcessNamedLoad().
IsLoopPhi()
bool v8::internal::maglev::LoopOptimizationProcessor::IsLoopPhi (Node * input) [inline]
Definition at line 76 of file maglev-post-hoc-optimizations-processors.h.
                              {
    DCHECK(current_block->is_loop());
    if (auto phi = input->TryCast<Phi>()) {
      if (phi->is_loop_phi() && phi->merge_state() == current_block->state()) {
        return true;
      }
    }
    return false;
  }
References current_block, v8::internal::DCHECK(), v8::internal::maglev::BasicBlock::is_loop(), v8::internal::maglev::BasicBlock::state(), and v8::internal::maglev::NodeBase::TryCast().
Referenced by CanHoist(), Process(), and ProcessNamedLoad().
PostPhiProcessing()
void v8::internal::maglev::LoopOptimizationProcessor::PostPhiProcessing () [inline]
Definition at line 60 of file maglev-post-hoc-optimizations-processors.h.
{}
PostProcessBasicBlock()
void v8::internal::maglev::LoopOptimizationProcessor::PostProcessBasicBlock (BasicBlock * block) [inline]
Definition at line 62 of file maglev-post-hoc-optimizations-processors.h.
{}
PostProcessGraph()
void v8::internal::maglev::LoopOptimizationProcessor::PostProcessGraph (Graph * graph) [inline]
Definition at line 190 of file maglev-post-hoc-optimizations-processors.h.
{}
PreProcessBasicBlock()
BlockProcessResult v8::internal::maglev::LoopOptimizationProcessor::PreProcessBasicBlock (BasicBlock * block) [inline]
Definition at line 63 of file maglev-post-hoc-optimizations-processors.h.
                                                             {
    current_block = block;
    if (current_block->is_loop()) {
      loop_effects = current_block->state()->loop_effects();
      if (loop_effects) return BlockProcessResult::kContinue;
    } else {
      // TODO(olivf): Some dominance analysis would allow us to keep loop
      // effects longer than just the first block of the loop.
      loop_effects = nullptr;
    }
    return BlockProcessResult::kSkip;
  }
References current_block, v8::internal::maglev::BasicBlock::is_loop(), v8::internal::maglev::kContinue, v8::internal::maglev::kSkip, v8::internal::maglev::MergePointInterpreterFrameState::loop_effects(), loop_effects, and v8::internal::maglev::BasicBlock::state().
PreProcessGraph()
void v8::internal::maglev::LoopOptimizationProcessor::PreProcessGraph (Graph * graph) [inline]
Definition at line 59 of file maglev-post-hoc-optimizations-processors.h.
{}
Process() [1/6]
ProcessResult v8::internal::maglev::LoopOptimizationProcessor::Process (CheckMaps * maps, const ProcessingState & state) [inline]
Definition at line 155 of file maglev-post-hoc-optimizations-processors.h.
                                                                       {
    DCHECK(loop_effects);
    // Hoisting a check out of a loop can cause it to trigger more than actually
    // needed (i.e., if the loop is executed 0 times). This could lead to
    // deoptimization loops as there is no feedback to learn here. Thus, we
    // abort this optimization if the function deoptimized previously. Also, if
    // hoisting of this check fails we need to abort (and not continue) to
    // ensure we are not hoisting other instructions over it.
    if (was_deoptimized) return ProcessResult::kSkipBlock;
    ValueNode* object = maps->receiver_input().node();
    if (IsLoopPhi(object)) {
      return ProcessResult::kSkipBlock;
    }
    if (!loop_effects->unstable_aspects_cleared && CanHoist(maps)) {
      if (auto j = current_block->predecessor_at(0)
                       ->control_node()
                       ->TryCast<CheckpointedJump>()) {
        maps->SetEagerDeoptInfo(zone, j->eager_deopt_info()->top_frame(),
                                maps->eager_deopt_info()->feedback_to_update());
        return ProcessResult::kHoist;
      }
    }
    return ProcessResult::kSkipBlock;
  }
References CanHoist(), v8::internal::maglev::BasicBlock::control_node(), current_block, v8::internal::DCHECK(), IsLoopPhi(), v8::internal::maglev::kHoist, v8::internal::maglev::kSkipBlock, loop_effects, v8::internal::maglev::Input::node(), v8::internal::maglev::BasicBlock::predecessor_at(), v8::internal::maglev::CheckMaps::receiver_input(), v8::internal::maglev::NodeBase::TryCast(), v8::internal::maglev::LoopEffects::unstable_aspects_cleared, was_deoptimized, and zone.
Process() [2/6]
ProcessResult v8::internal::maglev::LoopOptimizationProcessor::Process (LoadTaggedFieldForContextSlotNoCells * ltf, const ProcessingState & state) [inline]
Definition at line 106 of file maglev-post-hoc-optimizations-processors.h.
                                                      {
    DCHECK(loop_effects);
    ValueNode* object = ltf->object_input().node();
    if (IsLoopPhi(object)) {
      return ProcessResult::kContinue;
    }
    auto key = std::tuple{object, ltf->offset()};
    if (!loop_effects->may_have_aliasing_contexts &&
        !loop_effects->unstable_aspects_cleared &&
        !loop_effects->context_slot_written.count(key) && CanHoist(ltf)) {
      return ProcessResult::kHoist;
    }
    return ProcessResult::kContinue;
  }
References CanHoist(), v8::internal::maglev::LoopEffects::context_slot_written, v8::internal::DCHECK(), IsLoopPhi(), v8::internal::maglev::kContinue, v8::internal::key, v8::internal::maglev::kHoist, loop_effects, v8::internal::maglev::LoopEffects::may_have_aliasing_contexts, v8::internal::maglev::Input::node(), v8::internal::maglev::AbstractLoadTaggedField< Derived >::object_input(), v8::internal::maglev::AbstractLoadTaggedField< Derived >::offset(), and v8::internal::maglev::LoopEffects::unstable_aspects_cleared.
Process() [3/6]
ProcessResult v8::internal::maglev::LoopOptimizationProcessor::Process (LoadTaggedFieldForProperty * ltf, const ProcessingState & state) [inline]
Definition at line 122 of file maglev-post-hoc-optimizations-processors.h.
                                                      {
    return ProcessNamedLoad(ltf, ltf->object_input().node(), ltf->name());
  }
References v8::internal::maglev::LoadTaggedFieldForProperty::name(), v8::internal::maglev::Input::node(), v8::internal::maglev::AbstractLoadTaggedField< Derived >::object_input(), and ProcessNamedLoad().
Process() [4/6]
ProcessResult v8::internal::maglev::LoopOptimizationProcessor::Process (LoadTypedArrayLength * len, const ProcessingState & state) [inline]
Definition at line 133 of file maglev-post-hoc-optimizations-processors.h.
                                                      {
    return ProcessNamedLoad(
        len, len->receiver_input().node(),
        KnownNodeAspects::LoadedPropertyMapKey::TypedArrayLength());
  }
References v8::internal::maglev::Input::node(), ProcessNamedLoad(), v8::internal::maglev::LoadTypedArrayLength::receiver_input(), and v8::internal::maglev::KnownNodeAspects::LoadedPropertyMapKey::TypedArrayLength().
Process() [5/6]
template<typename NodeT >
ProcessResult v8::internal::maglev::LoopOptimizationProcessor::Process (NodeT * node, const ProcessingState & state) [inline]
Definition at line 181 of file maglev-post-hoc-optimizations-processors.h.
                                                                   {
    // Ensure we are not hoisting over checks.
    if (node->properties().can_eager_deopt()) {
      loop_effects = nullptr;
      return ProcessResult::kSkipBlock;
    }
    return ProcessResult::kContinue;
  }
References v8::internal::maglev::OpProperties::can_eager_deopt(), v8::internal::maglev::kContinue, v8::internal::maglev::kSkipBlock, loop_effects, and v8::internal::maglev::NodeTMixin< Base, Derived >::properties().
Process() [6/6]
ProcessResult v8::internal::maglev::LoopOptimizationProcessor::Process (StringLength * len, const ProcessingState & state) [inline]
Definition at line 127 of file maglev-post-hoc-optimizations-processors.h.
                                                                         {
    return ProcessNamedLoad(
        len, len->object_input().node(),
        KnownNodeAspects::LoadedPropertyMapKey::StringLength());
  }
References v8::internal::maglev::Input::node(), v8::internal::maglev::StringLength::object_input(), ProcessNamedLoad(), and v8::internal::maglev::KnownNodeAspects::LoadedPropertyMapKey::StringLength().
ProcessNamedLoad()
ProcessResult v8::internal::maglev::LoopOptimizationProcessor::ProcessNamedLoad (Node * load, ValueNode * object, KnownNodeAspects::LoadedPropertyMapKey name) [inline]
Definition at line 140 of file maglev-post-hoc-optimizations-processors.h.
                                                                            {
    DCHECK(!load->properties().can_deopt());
    if (!loop_effects) return ProcessResult::kContinue;
    if (IsLoopPhi(object)) {
      return ProcessResult::kContinue;
    }
    if (!loop_effects->unstable_aspects_cleared &&
        !loop_effects->keys_cleared.count(name) &&
        !loop_effects->objects_written.count(object) && CanHoist(load)) {
      return ProcessResult::kHoist;
    }
    return ProcessResult::kContinue;
  }
References v8::internal::maglev::OpProperties::can_deopt(), CanHoist(), v8::internal::DCHECK(), IsLoopPhi(), v8::internal::maglev::kContinue, v8::internal::maglev::LoopEffects::keys_cleared, v8::internal::maglev::kHoist, loop_effects, v8::internal::name, v8::internal::maglev::LoopEffects::objects_written, v8::internal::maglev::NodeBase::properties(), and v8::internal::maglev::LoopEffects::unstable_aspects_cleared.
Referenced by Process().
Member Data Documentation
current_block
BasicBlock* v8::internal::maglev::LoopOptimizationProcessor::current_block
Definition at line 193 of file maglev-post-hoc-optimizations-processors.h.
Referenced by CanHoist(), IsLoopPhi(), PreProcessBasicBlock(), and Process().
loop_effects
const LoopEffects* v8::internal::maglev::LoopOptimizationProcessor::loop_effects
Definition at line 194 of file maglev-post-hoc-optimizations-processors.h.
Referenced by PreProcessBasicBlock(), Process(), and ProcessNamedLoad().
was_deoptimized
bool v8::internal::maglev::LoopOptimizationProcessor::was_deoptimized
Definition at line 195 of file maglev-post-hoc-optimizations-processors.h.
Referenced by LoopOptimizationProcessor(), and Process().
zone
Zone* v8::internal::maglev::LoopOptimizationProcessor::zone
Definition at line 192 of file maglev-post-hoc-optimizations-processors.h.
Referenced by Process().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-post-hoc-optimizations-processors.h