v8::internal::compiler::turboshaft::DeadCodeEliminationReducer< Next > Class Template Reference
#include <dead-code-elimination-reducer.h>
Public Types
using Adapter = UniformReducerAdapter< DeadCodeEliminationReducer, Next >
Public Member Functions
bool CanAutoInlineBlocksWithSinglePredecessor () const
void Analyze ()
V< None > REDUCE_INPUT_GRAPH() Branch (V< None > ig_index, const BranchOp &branch)
V< None > REDUCE_INPUT_GRAPH() Goto (V< None > ig_index, const GotoOp &gto)
template<typename Op , typename Continuation >
OpIndex ReduceInputGraphOperation (OpIndex ig_index, const Op &op)
bool IsLeafFunction () const
Private Member Functions
bool TryRewriteBranch (OpIndex index)
Private Attributes
std::optional< FixedOpIndexSidetable< OperationState::Liveness > > liveness_
SparseOpIndexSideTable< BlockIndex > branch_rewrite_targets_
DeadCodeAnalysis analyzer_
Detailed Description
template<class Next>
class v8::internal::compiler::turboshaft::DeadCodeEliminationReducer< Next >
Definition at line 418 of file dead-code-elimination-reducer.h.
Member Typedef Documentation
Adapter
template<class Next >
using v8::internal::compiler::turboshaft::DeadCodeEliminationReducer< Next >::Adapter = UniformReducerAdapter<DeadCodeEliminationReducer, Next>
Definition at line 423 of file dead-code-elimination-reducer.h.
Member Function Documentation
Analyze()
template<class Next >
void v8::internal::compiler::turboshaft::DeadCodeEliminationReducer< Next >::Analyze () [inline]
Definition at line 432 of file dead-code-elimination-reducer.h.
                 {
    // TODO(nicohartmann@): We might want to make this a flag.
    constexpr bool trace_analysis = false;
    std::tie(liveness_, branch_rewrite_targets_) =
        analyzer_.Run<trace_analysis>();
    Next::Analyze();
  }
References v8::internal::compiler::turboshaft::DeadCodeEliminationReducer< Next >::analyzer_, v8::internal::compiler::turboshaft::DeadCodeEliminationReducer< Next >::branch_rewrite_targets_, v8::internal::compiler::turboshaft::DeadCodeEliminationReducer< Next >::liveness_, and v8::internal::compiler::turboshaft::DeadCodeAnalysis::Run().
Branch()
template<class Next >
V<None> REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::DeadCodeEliminationReducer< Next >::Branch (V< None > ig_index, const BranchOp & branch) [inline]
Definition at line 440 of file dead-code-elimination-reducer.h.
                                                                               {
    if (TryRewriteBranch(ig_index)) return V<None>::Invalid();
    return Next::ReduceInputGraphBranch(ig_index, branch);
  }
References v8::internal::compiler::turboshaft::DeadCodeEliminationReducer< Next >::TryRewriteBranch().
CanAutoInlineBlocksWithSinglePredecessor()
template<class Next >
bool v8::internal::compiler::turboshaft::DeadCodeEliminationReducer< Next >::CanAutoInlineBlocksWithSinglePredecessor () const [inline]
Definition at line 430 of file dead-code-elimination-reducer.h.
{ return false; }
Goto()
template<class Next >
V<None> REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::DeadCodeEliminationReducer< Next >::Goto (V< None > ig_index, const GotoOp & gto) [inline]
Definition at line 445 of file dead-code-elimination-reducer.h.
                                                                        {
    if (TryRewriteBranch(ig_index)) return {};
    return Next::ReduceInputGraphGoto(ig_index, gto);
  }
References v8::internal::compiler::turboshaft::DeadCodeEliminationReducer< Next >::TryRewriteBranch().
IsLeafFunction()
template<class Next >
bool v8::internal::compiler::turboshaft::DeadCodeEliminationReducer< Next >::IsLeafFunction () const [inline]
Definition at line 458 of file dead-code-elimination-reducer.h.
{ return analyzer_.is_leaf_function(); }
References v8::internal::compiler::turboshaft::DeadCodeEliminationReducer< Next >::analyzer_, and v8::internal::compiler::turboshaft::DeadCodeAnalysis::is_leaf_function().
ReduceInputGraphOperation()
template<class Next >
template<typename Op , typename Continuation >
OpIndex v8::internal::compiler::turboshaft::DeadCodeEliminationReducer< Next >::ReduceInputGraphOperation (OpIndex ig_index, const Op & op) [inline]
Definition at line 451 of file dead-code-elimination-reducer.h.
                                                                    {
    if ((*liveness_)[ig_index] == OperationState::kDead) {
      return OpIndex::Invalid();
    }
    return Continuation{this}.ReduceInputGraph(ig_index, op);
  }
References v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::turboshaft::OperationState::kDead, and v8::internal::compiler::turboshaft::DeadCodeEliminationReducer< Next >::liveness_.
TryRewriteBranch()
template<class Next >
bool v8::internal::compiler::turboshaft::DeadCodeEliminationReducer< Next >::TryRewriteBranch (OpIndex index) [inline], [private]
Definition at line 461 of file dead-code-elimination-reducer.h.
                                       {
    const BlockIndex* goto_target;
    if (branch_rewrite_targets_.contains(index, &goto_target)) {
      Asm().Goto(Asm().MapToNewGraph(&Asm().input_graph().Get(*goto_target)));
      return true;
    }
    return false;
  }
References v8::internal::compiler::turboshaft::DeadCodeEliminationReducer< Next >::branch_rewrite_targets_, v8::internal::compiler::turboshaft::Get(), and v8::internal::index.
Referenced by v8::internal::compiler::turboshaft::DeadCodeEliminationReducer< Next >::Branch(), and v8::internal::compiler::turboshaft::DeadCodeEliminationReducer< Next >::Goto().
Member Data Documentation
analyzer_
template<class Next >
DeadCodeAnalysis v8::internal::compiler::turboshaft::DeadCodeEliminationReducer< Next >::analyzer_ [private]
Initial value:
{Asm().modifiable_input_graph(),
                             Asm().phase_zone()}
Definition at line 472 of file dead-code-elimination-reducer.h.
Referenced by v8::internal::compiler::turboshaft::DeadCodeEliminationReducer< Next >::Analyze(), and v8::internal::compiler::turboshaft::DeadCodeEliminationReducer< Next >::IsLeafFunction().
branch_rewrite_targets_
template<class Next >
SparseOpIndexSideTable<BlockIndex> v8::internal::compiler::turboshaft::DeadCodeEliminationReducer< Next >::branch_rewrite_targets_ [private]
Initial value:
{
      Asm().phase_zone(), &Asm().input_graph()}
Definition at line 470 of file dead-code-elimination-reducer.h.
Referenced by v8::internal::compiler::turboshaft::DeadCodeEliminationReducer< Next >::Analyze(), and v8::internal::compiler::turboshaft::DeadCodeEliminationReducer< Next >::TryRewriteBranch().
liveness_
template<class Next >
std::optional<FixedOpIndexSidetable<OperationState::Liveness> > v8::internal::compiler::turboshaft::DeadCodeEliminationReducer< Next >::liveness_ [private]
Definition at line 469 of file dead-code-elimination-reducer.h.
Referenced by v8::internal::compiler::turboshaft::DeadCodeEliminationReducer< Next >::Analyze(), and v8::internal::compiler::turboshaft::DeadCodeEliminationReducer< Next >::ReduceInputGraphOperation().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/dead-code-elimination-reducer.h