v8::internal::compiler::SourcePositionTable Class Reference
#include <compiler-source-position-table.h>
Classes
class Decorator
class Scope
Public Member Functions
SourcePositionTable (TFGraph *graph)
SourcePositionTable (const SourcePositionTable &)=delete
SourcePositionTable & operator= (const SourcePositionTable &)=delete
void AddDecorator ()
void RemoveDecorator ()
SourcePosition GetSourcePosition (Node *node) const
SourcePosition GetSourcePosition (NodeId id) const
void SetSourcePosition (Node *node, SourcePosition position)
void SetCurrentPosition (const SourcePosition &pos)
SourcePosition GetCurrentPosition () const
void Disable ()
void Enable ()
bool IsEnabled () const
void PrintJson (std::ostream &os) const
Static Private Member Functions
static SourcePosition UnknownSourcePosition (Zone *zone)
Private Attributes
TFGraph *const graph_
Decorator * decorator_
SourcePosition current_position_
NodeAuxData< SourcePosition, UnknownSourcePosition > table_
bool enabled_ = true
Detailed Description
Definition at line 16 of file compiler-source-position-table.h.
Constructor & Destructor Documentation
SourcePositionTable() [1/2]
v8::internal::compiler::SourcePositionTable::SourcePositionTable (TFGraph * graph) [explicit]
Definition at line 28 of file compiler-source-position-table.cc.
    : graph_(graph),
      decorator_(nullptr),
      current_position_(SourcePosition::Unknown()),
      table_(graph->zone()) {}
SourcePositionTable() [2/2]
v8::internal::compiler::SourcePositionTable::SourcePositionTable (const SourcePositionTable &) [delete]
Member Function Documentation
AddDecorator()
void v8::internal::compiler::SourcePositionTable::AddDecorator ()
Definition at line 34 of file compiler-source-position-table.cc.
                                       {
  DCHECK_NULL(decorator_);
  if (!enabled_) return;
  decorator_ = graph_->zone()->New<Decorator>(this);
  graph_->AddDecorator(decorator_);
}
References v8::internal::compiler::TFGraph::AddDecorator(), DCHECK_NULL, decorator_, enabled_, graph_, v8::internal::Zone::New(), and v8::internal::compiler::TFGraph::zone().
Referenced by v8::internal::compiler::PipelineImpl::InitializeHeapBroker(), v8::internal::compiler::RawMachineAssembler::RawMachineAssembler(), v8::internal::compiler::Revectorizer::TryRevectorize(), and v8::internal::compiler::UnrollLoop().
Disable()
void v8::internal::compiler::SourcePositionTable::Disable () [inline]
Definition at line 60 of file compiler-source-position-table.h.
{ enabled_ = false; }
Referenced by v8::internal::compiler::PipelineImpl::InitializeHeapBroker().
Enable()
void v8::internal::compiler::SourcePositionTable::Enable () [inline]
Definition at line 61 of file compiler-source-position-table.h.
{ enabled_ = true; }
GetCurrentPosition()
SourcePosition v8::internal::compiler::SourcePositionTable::GetCurrentPosition () const [inline]
Definition at line 58 of file compiler-source-position-table.h.
{ return current_position_; }
Referenced by v8::internal::compiler::RawMachineAssembler::GetCurrentExternalSourcePosition().
GetSourcePosition() [1/2]
SourcePosition v8::internal::compiler::SourcePositionTable::GetSourcePosition (Node * node) const
Definition at line 51 of file compiler-source-position-table.cc.
                                                                      {
  return table_.Get(node);
}
References table_.
Referenced by v8::internal::compiler::NodeCopier::CopyNodes(), v8::internal::compiler::JSInliningHeuristic::CreateOrReuseDispatch(), v8::internal::compiler::JSONGraphWriter::PrintNode(), v8::internal::compiler::GraphC1Visualizer::PrintSchedule(), v8::internal::compiler::JSInliner::ReduceJSCall(), v8::internal::compiler::RepresentationSelector::RunLowerPhase(), v8::internal::compiler::WasmGCLowering::UpdateSourcePosition(), and v8::internal::compiler::WasmGCOperatorReducer::UpdateSourcePosition().
GetSourcePosition() [2/2]
SourcePosition v8::internal::compiler::SourcePositionTable::GetSourcePosition (NodeId id) const
Definition at line 54 of file compiler-source-position-table.cc.
                                                                     {
  return table_.Get(id);
}
References table_.
IsEnabled()
bool v8::internal::compiler::SourcePositionTable::IsEnabled () const [inline]
Definition at line 63 of file compiler-source-position-table.h.
{ return enabled_; }
Referenced by SetSourcePosition().
operator=()
SourcePositionTable& v8::internal::compiler::SourcePositionTable::operator= (const SourcePositionTable &) [delete]
PrintJson()
void v8::internal::compiler::SourcePositionTable::PrintJson (std::ostream & os) const
Definition at line 64 of file compiler-source-position-table.cc.
                                                        {
  os << "{";
  bool needs_comma = false;
  for (auto i : table_) {
    SourcePosition pos = i.second;
    if (pos.IsKnown()) {
      if (needs_comma) {
        os << ",";
      }
      os << "\"" << i.first << "\" : ";
      pos.PrintJson(os);
      needs_comma = true;
    }
  }
  os << "}";
}
References v8::internal::SourcePosition::IsKnown(), v8::internal::SourcePosition::PrintJson(), and table_.
RemoveDecorator()
void v8::internal::compiler::SourcePositionTable::RemoveDecorator ()
Definition at line 41 of file compiler-source-position-table.cc.
                                          {
  if (!enabled_) {
    DCHECK_NULL(decorator_);
    return;
  }
  DCHECK_NOT_NULL(decorator_);
  graph_->RemoveDecorator(decorator_);
  decorator_ = nullptr;
}
References DCHECK_NOT_NULL, DCHECK_NULL, decorator_, enabled_, graph_, and v8::internal::compiler::TFGraph::RemoveDecorator().
Referenced by v8::internal::compiler::RawMachineAssembler::ExportForTest(), v8::internal::compiler::PipelineImpl::OptimizeTurbofanGraph(), v8::internal::compiler::Revectorizer::TryRevectorize(), and v8::internal::compiler::UnrollLoop().
SetCurrentPosition()
void v8::internal::compiler::SourcePositionTable::SetCurrentPosition (const SourcePosition & pos) [inline]
Definition at line 55 of file compiler-source-position-table.h.
                                                     {
    current_position_ = pos;
  }
Referenced by v8::internal::compiler::RawMachineAssembler::SetCurrentExternalSourcePosition().
SetSourcePosition()
void v8::internal::compiler::SourcePositionTable::SetSourcePosition (Node * node, SourcePosition position)
Definition at line 58 of file compiler-source-position-table.cc.
                                                                     {
  DCHECK(IsEnabled());
  table_.Set(node, position);
}
References v8::internal::DCHECK(), IsEnabled(), and table_.
Referenced by v8::internal::compiler::SourcePositionTable::Decorator::Decorate(), v8::internal::compiler::WasmGraphBuilder::SetSourcePosition(), v8::internal::compiler::WasmGCLowering::UpdateSourcePosition(), and v8::internal::compiler::WasmGCOperatorReducer::UpdateSourcePosition().
UnknownSourcePosition()
static SourcePosition v8::internal::compiler::SourcePositionTable::UnknownSourcePosition (Zone * zone) [inline], [static], [private]
Definition at line 70 of file compiler-source-position-table.h.
                                                          {
    return SourcePosition::Unknown();
  }
References v8::internal::SourcePosition::Unknown().
Member Data Documentation
current_position_
SourcePosition v8::internal::compiler::SourcePositionTable::current_position_ [private]
Definition at line 76 of file compiler-source-position-table.h.
Referenced by v8::internal::compiler::SourcePositionTable::Decorator::Decorate().
decorator_
Decorator* v8::internal::compiler::SourcePositionTable::decorator_ [private]
Definition at line 75 of file compiler-source-position-table.h.
Referenced by AddDecorator(), and RemoveDecorator().
enabled_
bool v8::internal::compiler::SourcePositionTable::enabled_ = true [private]
Definition at line 78 of file compiler-source-position-table.h.
Referenced by AddDecorator(), and RemoveDecorator().
graph_
TFGraph* const v8::internal::compiler::SourcePositionTable::graph_ [private]
Definition at line 74 of file compiler-source-position-table.h.
Referenced by AddDecorator(), and RemoveDecorator().
table_
NodeAuxData<SourcePosition, UnknownSourcePosition> v8::internal::compiler::SourcePositionTable::table_ [private]
Definition at line 77 of file compiler-source-position-table.h.
Referenced by GetSourcePosition(), PrintJson(), and SetSourcePosition().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/compiler-source-position-table.h
/mnt/V8SourceCode/src/compiler/compiler-source-position-table.cc