v8::internal::compiler::PipelineStatisticsBase Class Reference
#include <pipeline-statistics.h>
Classes
class CommonStats
Protected Types
using Base = PipelineStatisticsBase
Protected Member Functions
PipelineStatisticsBase (Zone *outer_zone, ZoneStats *zone_stats, std::shared_ptr< CompilationStatistics > compilation_stats, CodeKind code_kind)
~PipelineStatisticsBase ()
PipelineStatisticsBase (const PipelineStatisticsBase &)=delete
PipelineStatisticsBase & operator= (const PipelineStatisticsBase &)=delete
void BeginPhaseKind (const char *phase_kind_name)
void EndPhaseKind (CompilationStatistics::BasicStats *diff)
size_t OuterZoneSize ()
bool InPhaseKind ()
bool InPhase ()
void BeginPhase (const char *name)
void EndPhase (CompilationStatistics::BasicStats *diff)
CodeKind code_kind () const
const char * phase_kind_name () const
const char * phase_name () const
void set_function_name (std::string function_name)
Private Attributes
Zone *const outer_zone_
ZoneStats *const zone_stats_
const std::shared_ptr< CompilationStatistics > compilation_stats_
const CodeKind code_kind_
std::string function_name_
CommonStats total_stats_
const char * phase_kind_name_ = nullptr
CommonStats phase_kind_stats_
const char * phase_name_ = nullptr
CommonStats phase_stats_
Friends
class PhaseScope
Detailed Description
Definition at line 24 of file pipeline-statistics.h.
Member Typedef Documentation
Base
using v8::internal::compiler::PipelineStatisticsBase::Base = PipelineStatisticsBase [protected]
Definition at line 26 of file pipeline-statistics.h.
Constructor & Destructor Documentation
PipelineStatisticsBase() [1/2]
v8::internal::compiler::PipelineStatisticsBase::PipelineStatisticsBase (Zone * outer_zone, ZoneStats * zone_stats, std::shared_ptr< CompilationStatistics > compilation_stats, CodeKind code_kind) [protected]
Definition at line 65 of file pipeline-statistics.cc.
    : outer_zone_(outer_zone),
      zone_stats_(zone_stats),
      compilation_stats_(compilation_stats),
      code_kind_(code_kind) {
  total_stats_.Begin(this);
}
References v8::internal::compiler::PipelineStatisticsBase::CommonStats::Begin(), and total_stats_.
 PipelineStatisticsBase()
v8::internal::compiler::PipelineStatisticsBase::~PipelineStatisticsBase () [protected]
Definition at line 76 of file pipeline-statistics.cc.
                                                {
  CompilationStatistics::BasicStats diff;
  total_stats_.End(this, &diff);
  compilation_stats_->RecordTotalStats(diff);
}
References compilation_stats_, v8::internal::compiler::PipelineStatisticsBase::CommonStats::End(), and total_stats_.
PipelineStatisticsBase() [2/2]
v8::internal::compiler::PipelineStatisticsBase::PipelineStatisticsBase (const PipelineStatisticsBase &) [protected], [delete]
Member Function Documentation
BeginPhase()
void v8::internal::compiler::PipelineStatisticsBase::BeginPhase (const char * name) [protected]
Definition at line 95 of file pipeline-statistics.cc.
                                                              {
  DCHECK(InPhaseKind());
  phase_name_ = phase_name;
  phase_stats_.Begin(this);
}
References v8::internal::compiler::PipelineStatisticsBase::CommonStats::Begin(), v8::internal::DCHECK(), InPhaseKind(), phase_name(), phase_name_, and phase_stats_.
Referenced by v8::internal::compiler::TurbofanPipelineStatistics::BeginPhase().
BeginPhaseKind()
void v8::internal::compiler::PipelineStatisticsBase::BeginPhaseKind (const char * phase_kind_name) [protected]
Definition at line 82 of file pipeline-statistics.cc.
                                                                       {
  DCHECK(!InPhase());
  phase_kind_name_ = phase_kind_name;
  phase_kind_stats_.Begin(this);
}
References v8::internal::compiler::PipelineStatisticsBase::CommonStats::Begin(), v8::internal::DCHECK(), InPhase(), phase_kind_name(), phase_kind_name_, and phase_kind_stats_.
Referenced by v8::internal::compiler::TurbofanPipelineStatistics::BeginPhaseKind().
code_kind()
CodeKind v8::internal::compiler::PipelineStatisticsBase::code_kind () const [inline], [protected]
Definition at line 69 of file pipeline-statistics.h.
{ return code_kind_; }
References code_kind_.
Referenced by v8::internal::compiler::TurbofanPipelineStatistics::BeginPhase(), v8::internal::compiler::TurbofanPipelineStatistics::BeginPhaseKind(), v8::internal::compiler::TurbofanPipelineStatistics::EndPhase(), and v8::internal::compiler::TurbofanPipelineStatistics::EndPhaseKind().
EndPhase()
void v8::internal::compiler::PipelineStatisticsBase::EndPhase (CompilationStatistics::BasicStats * diff) [protected]
Definition at line 101 of file pipeline-statistics.cc.
                                                                           {
  DCHECK(InPhaseKind());
  phase_stats_.End(this, diff);
  compilation_stats_->RecordPhaseStats(phase_kind_name_, phase_name_, *diff);
}
References compilation_stats_, v8::internal::DCHECK(), v8::internal::compiler::PipelineStatisticsBase::CommonStats::End(), InPhaseKind(), phase_kind_name_, phase_name_, and phase_stats_.
Referenced by v8::internal::compiler::TurbofanPipelineStatistics::EndPhase().
EndPhaseKind()
void v8::internal::compiler::PipelineStatisticsBase::EndPhaseKind (CompilationStatistics::BasicStats * diff) [protected]
Definition at line 88 of file pipeline-statistics.cc.
                                           {
  DCHECK(!InPhase());
  phase_kind_stats_.End(this, diff);
  compilation_stats_->RecordPhaseKindStats(phase_kind_name_, *diff);
}
References compilation_stats_, v8::internal::DCHECK(), v8::internal::compiler::PipelineStatisticsBase::CommonStats::End(), InPhase(), phase_kind_name_, and phase_kind_stats_.
Referenced by v8::internal::compiler::TurbofanPipelineStatistics::EndPhaseKind().
InPhase()
bool v8::internal::compiler::PipelineStatisticsBase::InPhase () [inline], [protected]
Definition at line 65 of file pipeline-statistics.h.
{ return !!phase_stats_.scope_; }
References phase_stats_, and v8::internal::compiler::PipelineStatisticsBase::CommonStats::scope_.
Referenced by BeginPhaseKind(), and EndPhaseKind().
InPhaseKind()
bool v8::internal::compiler::PipelineStatisticsBase::InPhaseKind () [inline], [protected]
Definition at line 62 of file pipeline-statistics.h.
{ return !!phase_kind_stats_.scope_; }
References phase_kind_stats_, and v8::internal::compiler::PipelineStatisticsBase::CommonStats::scope_.
Referenced by BeginPhase(), v8::internal::compiler::TurbofanPipelineStatistics::BeginPhaseKind(), EndPhase(), and v8::internal::compiler::TurbofanPipelineStatistics::~TurbofanPipelineStatistics().
operator=()
PipelineStatisticsBase& v8::internal::compiler::PipelineStatisticsBase::operator= (const PipelineStatisticsBase &) [protected], [delete]
OuterZoneSize()
size_t v8::internal::compiler::PipelineStatisticsBase::OuterZoneSize () [inline], [protected]
Definition at line 41 of file pipeline-statistics.h.
                         {
    return static_cast<size_t>(outer_zone_->allocation_size());
  }
References v8::internal::Zone::allocation_size(), and outer_zone_.
Referenced by v8::internal::compiler::PipelineStatisticsBase::CommonStats::Begin(), and v8::internal::compiler::PipelineStatisticsBase::CommonStats::End().
phase_kind_name()
const char* v8::internal::compiler::PipelineStatisticsBase::phase_kind_name () const [inline], [protected]
Definition at line 70 of file pipeline-statistics.h.
{ return phase_kind_name_; }
References phase_kind_name_.
Referenced by BeginPhaseKind(), and v8::internal::compiler::TurbofanPipelineStatistics::EndPhaseKind().
phase_name()
const char* v8::internal::compiler::PipelineStatisticsBase::phase_name () const [inline], [protected]
Definition at line 71 of file pipeline-statistics.h.
{ return phase_name_; }
References phase_name_.
Referenced by BeginPhase(), v8::internal::compiler::TurbofanPipelineStatistics::BeginPhase(), and v8::internal::compiler::TurbofanPipelineStatistics::EndPhase().
set_function_name()
void v8::internal::compiler::PipelineStatisticsBase::set_function_name (std::string function_name) [inline], [protected]
Definition at line 73 of file pipeline-statistics.h.
                                                  {
    function_name_.assign(function_name);
  }
References function_name_.
Referenced by v8::internal::compiler::TurbofanPipelineStatistics::TurbofanPipelineStatistics().
Friends And Related Function Documentation
PhaseScope
friend class PhaseScope [friend]
Definition at line 64 of file pipeline-statistics.h.
Member Data Documentation
code_kind_
const CodeKind v8::internal::compiler::PipelineStatisticsBase::code_kind_ [private]
Definition at line 81 of file pipeline-statistics.h.
Referenced by code_kind().
compilation_stats_
const std::shared_ptr<CompilationStatistics> v8::internal::compiler::PipelineStatisticsBase::compilation_stats_ [private]
Definition at line 80 of file pipeline-statistics.h.
Referenced by EndPhase(), EndPhaseKind(), and ~PipelineStatisticsBase().
function_name_
std::string v8::internal::compiler::PipelineStatisticsBase::function_name_ [private]
Definition at line 82 of file pipeline-statistics.h.
Referenced by v8::internal::compiler::PipelineStatisticsBase::CommonStats::End(), and set_function_name().
outer_zone_
Zone* const v8::internal::compiler::PipelineStatisticsBase::outer_zone_ [private]
Definition at line 78 of file pipeline-statistics.h.
Referenced by OuterZoneSize().
phase_kind_name_
const char* v8::internal::compiler::PipelineStatisticsBase::phase_kind_name_ = nullptr [private]
Definition at line 88 of file pipeline-statistics.h.
Referenced by BeginPhaseKind(), EndPhase(), EndPhaseKind(), and phase_kind_name().
phase_kind_stats_
CommonStats v8::internal::compiler::PipelineStatisticsBase::phase_kind_stats_ [private]
Definition at line 89 of file pipeline-statistics.h.
Referenced by BeginPhaseKind(), EndPhaseKind(), and InPhaseKind().
phase_name_
const char* v8::internal::compiler::PipelineStatisticsBase::phase_name_ = nullptr [private]
Definition at line 92 of file pipeline-statistics.h.
Referenced by BeginPhase(), EndPhase(), and phase_name().
phase_stats_
CommonStats v8::internal::compiler::PipelineStatisticsBase::phase_stats_ [private]
Definition at line 93 of file pipeline-statistics.h.
Referenced by BeginPhase(), EndPhase(), and InPhase().
total_stats_
CommonStats v8::internal::compiler::PipelineStatisticsBase::total_stats_ [private]
Definition at line 85 of file pipeline-statistics.h.
Referenced by v8::internal::compiler::PipelineStatisticsBase::CommonStats::Begin(), PipelineStatisticsBase(), and ~PipelineStatisticsBase().
zone_stats_
ZoneStats* const v8::internal::compiler::PipelineStatisticsBase::zone_stats_ [private]
Definition at line 79 of file pipeline-statistics.h.
Referenced by v8::internal::compiler::PipelineStatisticsBase::CommonStats::Begin().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/pipeline-statistics.h
/mnt/V8SourceCode/src/compiler/pipeline-statistics.cc