v8::tracing::TracedValue Class Reference
#include <traced-value.h>
Public Member Functions
~TracedValue () override
TracedValue (const TracedValue &)=delete
TracedValue & operator= (const TracedValue &)=delete
void EndDictionary ()
void EndArray ()
void SetInteger (const char *name, int value)
void SetUnsignedInteger (const char *name, uint64_t value)
void SetDouble (const char *name, double value)
void SetBoolean (const char *name, bool value)
void SetString (const char *name, const char *value)
void SetString (const char *name, const std::string &value)
void SetString (const char *name, std::unique_ptr< char[]> value)
void SetValue (const char *name, TracedValue *value)
void SetValue (const char *name, std::unique_ptr< TracedValue > value)
void BeginDictionary (const char *name)
void BeginArray (const char *name)
void AppendInteger (int)
void AppendDouble (double)
void AppendBoolean (bool)
void AppendString (const char *)
void AppendString (const std::string &value)
void BeginArray ()
void BeginDictionary ()
void AppendAsTraceFormat (std::string *out) const override
Append the class info to the provided |out| string.
Static Public Member Functions
static std::unique_ptr< TracedValue > Create ()
Private Member Functions
TracedValue ()
void WriteComma ()
void WriteName (const char *name)
Private Attributes
std::string data_
bool first_item_
Detailed Description
Definition at line 20 of file traced-value.h.
Constructor & Destructor Documentation
 TracedValue()
v8::tracing::TracedValue::~TracedValue () [override]
Definition at line 83 of file traced-value.cc.
                          {
  DCHECK_CURRENT_CONTAINER_IS(kStackTypeDict);
  DEBUG_POP_CONTAINER();
  DCHECK_CONTAINER_STACK_DEPTH_EQ(0u);
}
References DCHECK_CONTAINER_STACK_DEPTH_EQ, DCHECK_CURRENT_CONTAINER_IS, and DEBUG_POP_CONTAINER.
TracedValue() [1/2]
v8::tracing::TracedValue::TracedValue (const TracedValue &) [delete]
TracedValue() [2/2]
v8::tracing::TracedValue::TracedValue () [private]
Definition at line 79 of file traced-value.cc.
                         : first_item_(true) {
  DEBUG_PUSH_CONTAINER(kStackTypeDict);
}
References DEBUG_PUSH_CONTAINER.
Referenced by Create().
Member Function Documentation
AppendAsTraceFormat()
void v8::tracing::TracedValue::AppendAsTraceFormat (std::string * out) const [override], [virtual]
Append the class info to the provided |out| string.
The appended data must be a valid JSON object. Strings must be properly quoted, and escaped. There is no processing applied to the content after it is appended.
Implements v8::ConvertableToTraceFormat.
Definition at line 214 of file traced-value.cc.
                                                          {
  *out += '{';
  *out += data_;
  *out += '}';
}
References data_.
AppendBoolean()
void v8::tracing::TracedValue::AppendBoolean (bool value)
Definition at line 157 of file traced-value.cc.
                                          {
  DCHECK_CURRENT_CONTAINER_IS(kStackTypeArray);
  WriteComma();
  data_ += value ? "true" : "false";
}
References data_, DCHECK_CURRENT_CONTAINER_IS, v8::internal::value, and WriteComma().
AppendDouble()
void v8::tracing::TracedValue::AppendDouble (double value)
Definition at line 150 of file traced-value.cc.
                                           {
  DCHECK_CURRENT_CONTAINER_IS(kStackTypeArray);
  WriteComma();
  base::EmbeddedVector<char, 100> buffer;
  data_ += internal::DoubleToStringView(value, buffer);
}
References data_, DCHECK_CURRENT_CONTAINER_IS, v8::internal::DoubleToStringView(), v8::internal::value, and WriteComma().
AppendInteger()
void v8::tracing::TracedValue::AppendInteger (int value)
Definition at line 144 of file traced-value.cc.
                                         {
  DCHECK_CURRENT_CONTAINER_IS(kStackTypeArray);
  WriteComma();
  data_ += std::to_string(value);
}
References data_, DCHECK_CURRENT_CONTAINER_IS, v8::internal::value, and WriteComma().
AppendString() [1/2]
void v8::tracing::TracedValue::AppendString (const char * value)
Definition at line 163 of file traced-value.cc.
                                                {
  DCHECK_CURRENT_CONTAINER_IS(kStackTypeArray);
  WriteComma();
  EscapeAndAppendString(value, &data_);
}
References data_, DCHECK_CURRENT_CONTAINER_IS, v8::tracing::anonymous_namespace{traced-value.cc}::EscapeAndAppendString(), v8::internal::value, and WriteComma().
AppendString() [2/2]
void v8::tracing::TracedValue::AppendString (const std::string & value) [inline]
Definition at line 59 of file traced-value.h.
{ AppendString(value.c_str()); }
References AppendString(), and v8::internal::value.
Referenced by AppendString().
BeginArray() [1/2]
void v8::tracing::TracedValue::BeginArray ()
Definition at line 177 of file traced-value.cc.
                             {
  DCHECK_CURRENT_CONTAINER_IS(kStackTypeArray);
  DEBUG_PUSH_CONTAINER(kStackTypeArray);
  WriteComma();
  data_ += '[';
  first_item_ = true;
}
References data_, DCHECK_CURRENT_CONTAINER_IS, DEBUG_PUSH_CONTAINER, first_item_, and WriteComma().
BeginArray() [2/2]
void v8::tracing::TracedValue::BeginArray (const char * name)
Definition at line 136 of file traced-value.cc.
                                             {
  DCHECK_CURRENT_CONTAINER_IS(kStackTypeDict);
  DEBUG_PUSH_CONTAINER(kStackTypeArray);
  WriteName(name);
  data_ += '[';
  first_item_ = true;
}
References data_, DCHECK_CURRENT_CONTAINER_IS, DEBUG_PUSH_CONTAINER, first_item_, name, and WriteName().
BeginDictionary() [1/2]
void v8::tracing::TracedValue::BeginDictionary ()
Definition at line 169 of file traced-value.cc.
                                  {
  DCHECK_CURRENT_CONTAINER_IS(kStackTypeArray);
  DEBUG_PUSH_CONTAINER(kStackTypeDict);
  WriteComma();
  data_ += '{';
  first_item_ = true;
}
References data_, DCHECK_CURRENT_CONTAINER_IS, DEBUG_PUSH_CONTAINER, first_item_, and WriteComma().
BeginDictionary() [2/2]
void v8::tracing::TracedValue::BeginDictionary (const char * name)
Definition at line 128 of file traced-value.cc.
                                                  {
  DCHECK_CURRENT_CONTAINER_IS(kStackTypeDict);
  DEBUG_PUSH_CONTAINER(kStackTypeDict);
  WriteName(name);
  data_ += '{';
  first_item_ = true;
}
References data_, DCHECK_CURRENT_CONTAINER_IS, DEBUG_PUSH_CONTAINER, first_item_, name, and WriteName().
Create()
std::unique_ptr< TracedValue > v8::tracing::TracedValue::Create () [static]
Definition at line 75 of file traced-value.cc.
                                               {
  return std::unique_ptr<TracedValue>(new TracedValue());
}
References TracedValue().
Referenced by v8::internal::CpuProfile::CpuProfile(), v8::internal::ICStats::Dump(), v8::internal::CpuProfile::FinishProfile(), v8::internal::CpuProfile::StreamPendingTraceEvents(), v8::internal::Script::TraceScriptRundown(), and v8::internal::Script::TraceScriptRundownSources().
EndArray()
void v8::tracing::TracedValue::EndArray ()
Definition at line 192 of file traced-value.cc.
                           {
  DCHECK_CURRENT_CONTAINER_IS(kStackTypeArray);
  DEBUG_POP_CONTAINER();
  data_ += ']';
  first_item_ = false;
}
References data_, DCHECK_CURRENT_CONTAINER_IS, DEBUG_POP_CONTAINER, and first_item_.
EndDictionary()
void v8::tracing::TracedValue::EndDictionary ()
Definition at line 185 of file traced-value.cc.
                                {
  DCHECK_CURRENT_CONTAINER_IS(kStackTypeDict);
  DEBUG_POP_CONTAINER();
  data_ += '}';
  first_item_ = false;
}
References data_, DCHECK_CURRENT_CONTAINER_IS, DEBUG_POP_CONTAINER, and first_item_.
operator=()
TracedValue& v8::tracing::TracedValue::operator= (const TracedValue &) [delete]
SetBoolean()
void v8::tracing::TracedValue::SetBoolean (const char * name, bool value)
Definition at line 108 of file traced-value.cc.
                                                         {
  DCHECK_CURRENT_CONTAINER_IS(kStackTypeDict);
  WriteName(name);
  data_ += value ? "true" : "false";
}
References data_, DCHECK_CURRENT_CONTAINER_IS, name, v8::internal::value, and WriteName().
SetDouble()
void v8::tracing::TracedValue::SetDouble (const char * name, double value)
Definition at line 101 of file traced-value.cc.
                                                          {
  DCHECK_CURRENT_CONTAINER_IS(kStackTypeDict);
  WriteName(name);
  base::EmbeddedVector<char, 100> buffer;
  data_ += internal::DoubleToStringView(value, buffer);
}
References data_, DCHECK_CURRENT_CONTAINER_IS, v8::internal::DoubleToStringView(), name, v8::internal::value, and WriteName().
SetInteger()
void v8::tracing::TracedValue::SetInteger (const char * name, int value)
Definition at line 89 of file traced-value.cc.
                                                        {
  DCHECK_CURRENT_CONTAINER_IS(kStackTypeDict);
  WriteName(name);
  data_ += std::to_string(value);
}
References data_, DCHECK_CURRENT_CONTAINER_IS, name, v8::internal::value, and WriteName().
SetString() [1/3]
void v8::tracing::TracedValue::SetString (const char * name, const char * value)
Definition at line 114 of file traced-value.cc.
                                                               {
  DCHECK_CURRENT_CONTAINER_IS(kStackTypeDict);
  WriteName(name);
  EscapeAndAppendString(value, &data_);
}
References data_, DCHECK_CURRENT_CONTAINER_IS, v8::tracing::anonymous_namespace{traced-value.cc}::EscapeAndAppendString(), name, v8::internal::value, and WriteName().
SetString() [2/3]
void v8::tracing::TracedValue::SetString (const char * name, const std::string & value) [inline]
Definition at line 42 of file traced-value.h.
                                                           {
    SetString(name, value.c_str());
  }
References name, and v8::internal::value.
SetString() [3/3]
void v8::tracing::TracedValue::SetString (const char * name, std::unique_ptr< char[]> value) [inline]
Definition at line 45 of file traced-value.h.
                                                                {
    SetString(name, value.get());
  }
References name, and v8::internal::value.
SetUnsignedInteger()
void v8::tracing::TracedValue::SetUnsignedInteger (const char * name, uint64_t value)
Definition at line 95 of file traced-value.cc.
                                                                     {
  DCHECK_CURRENT_CONTAINER_IS(kStackTypeDict);
  WriteName(name);
  data_ += std::to_string(value);
}
References data_, DCHECK_CURRENT_CONTAINER_IS, name, v8::internal::value, and WriteName().
SetValue() [1/2]
void v8::tracing::TracedValue::SetValue (const char * name, std::unique_ptr< TracedValue > value) [inline]
Definition at line 49 of file traced-value.h.
                                                                    {
    SetValue(name, value.get());
  }
References name, and v8::internal::value.
SetValue() [2/2]
void v8::tracing::TracedValue::SetValue (const char * name, TracedValue * value)
Definition at line 120 of file traced-value.cc.
                                                               {
  DCHECK_CURRENT_CONTAINER_IS(kStackTypeDict);
  WriteName(name);
  std::string tmp;
  value->AppendAsTraceFormat(&tmp);
  data_ += tmp;
}
References data_, DCHECK_CURRENT_CONTAINER_IS, name, v8::internal::string, v8::internal::value, and WriteName().
WriteComma()
void v8::tracing::TracedValue::WriteComma () [private]
Definition at line 199 of file traced-value.cc.
                             {
  if (first_item_) {
    first_item_ = false;
  } else {
    data_ += ',';
  }
}
References data_, and first_item_.
Referenced by AppendBoolean(), AppendDouble(), AppendInteger(), AppendString(), BeginArray(), BeginDictionary(), and WriteName().
WriteName()
void v8::tracing::TracedValue::WriteName (const char * name) [private]
Definition at line 207 of file traced-value.cc.
                                            {
  WriteComma();
  data_ += '"';
  data_ += name;
  data_ += "\":";
}
References data_, name, and WriteComma().
Referenced by BeginArray(), BeginDictionary(), SetBoolean(), SetDouble(), SetInteger(), SetString(), SetUnsignedInteger(), and SetValue().
Member Data Documentation
data_
std::string v8::tracing::TracedValue::data_ [private]
Definition at line 82 of file traced-value.h.
Referenced by AppendAsTraceFormat(), AppendBoolean(), AppendDouble(), AppendInteger(), AppendString(), BeginArray(), BeginDictionary(), EndArray(), EndDictionary(), SetBoolean(), SetDouble(), SetInteger(), SetString(), SetUnsignedInteger(), SetValue(), WriteComma(), and WriteName().
first_item_
bool v8::tracing::TracedValue::first_item_ [private]
Definition at line 83 of file traced-value.h.
Referenced by BeginArray(), BeginDictionary(), EndArray(), EndDictionary(), and WriteComma().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/tracing/traced-value.h
/mnt/V8SourceCode/src/tracing/traced-value.cc