v8::internal::compiler::PersistentMap< Key, Value, Hasher >::iterator Class Reference
#include <persistent-map.h>
Public Member Functions
const value_type operator* () const
iterator & operator++ ()
bool operator== (const iterator &other) const
bool operator!= (const iterator &other) const
bool operator< (const iterator &other) const
bool is_end () const
const Value & def_value ()
Static Public Member Functions
static iterator begin (const FocusedTree *tree, Value def_value)
static iterator end (Value def_value)
Private Member Functions
iterator (Value def_value)
Private Attributes
int level_
FocusedTree::more_iterator more_iter_
const FocusedTree * current_
std::array< const FocusedTree *, kHashBits > path_
Value def_value_
Detailed Description
template<class Key, class Value, class Hasher = base::hash<Key>>
class v8::internal::compiler::PersistentMap< Key, Value, Hasher >::iterator
Definition at line 248 of file persistent-map.h.
Constructor & Destructor Documentation
iterator()
template<class Key , class Value , class Hasher = base::hash<Key>>
v8::internal::compiler::PersistentMap< Key, Value, Hasher >::iterator::iterator (Value def_value) [inline], [explicit], [private]
Definition at line 337 of file persistent-map.h.
      : level_(0), current_(nullptr), def_value_(def_value) {}
Member Function Documentation
begin()
template<class Key , class Value , class Hasher = base::hash<Key>>
static iterator v8::internal::compiler::PersistentMap< Key, Value, Hasher >::iterator::begin (const FocusedTree * tree, Value def_value) [inline], [static]
Definition at line 316 of file persistent-map.h.
                                                                  {
    iterator i(def_value);
    i.current_ = FindLeftmost(tree, &i.level_, &i.path_);
    if (i.current_->more) {
      i.more_iter_ = i.current_->more->begin();
    }
    // Skip entries with default value. PersistentMap iterators must never point
    // to a default value.
    while (!i.is_end() && !((*i).second != def_value)) ++i;
    return i;
  }
References v8::internal::compiler::PersistentMap< Key, Value, Hasher >::FindLeftmost(), and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by v8::internal::compiler::PersistentMap< Key, Value, Hasher >::begin().
def_value()
template<class Key , class Value , class Hasher = base::hash<Key>>
const Value& v8::internal::compiler::PersistentMap< Key, Value, Hasher >::iterator::def_value () [inline]
Definition at line 314 of file persistent-map.h.
{ return def_value_; }
References v8::internal::compiler::PersistentMap< Key, Value, Hasher >::def_value_.
end()
template<class Key , class Value , class Hasher = base::hash<Key>>
static iterator v8::internal::compiler::PersistentMap< Key, Value, Hasher >::iterator::end (Value def_value) [inline], [static]
Definition at line 328 of file persistent-map.h.
{ return iterator(def_value); }
Referenced by v8::internal::compiler::PersistentMap< Key, Value, Hasher >::end().
is_end()
template<class Key , class Value , class Hasher = base::hash<Key>>
bool v8::internal::compiler::PersistentMap< Key, Value, Hasher >::iterator::is_end () const [inline]
Definition at line 312 of file persistent-map.h.
{ return current_ == nullptr; }
Referenced by v8::internal::compiler::PersistentMap< Key, Value, Hasher >::iterator::operator<(), and v8::internal::compiler::PersistentMap< Key, Value, Hasher >::iterator::operator==().
operator!=()
template<class Key , class Value , class Hasher = base::hash<Key>>
bool v8::internal::compiler::PersistentMap< Key, Value, Hasher >::iterator::operator!= (const iterator & other) const [inline]
Definition at line 300 of file persistent-map.h.
{ return !(*this == other); }
operator*()
template<class Key , class Value , class Hasher = base::hash<Key>>
const value_type v8::internal::compiler::PersistentMap< Key, Value, Hasher >::iterator::operator* () const [inline]
Definition at line 250 of file persistent-map.h.
                                     {
    if (current_->more) {
      return *more_iter_;
    } else {
      return current_->key_value;
    }
  }
operator++()
template<class Key , class Value , class Hasher = base::hash<Key>>
iterator& v8::internal::compiler::PersistentMap< Key, Value, Hasher >::iterator::operator++ () [inline]
Definition at line 258 of file persistent-map.h.
                         {
    do {
      if (!current_) {
        // Iterator is past the end.
        return *this;
      }
      if (current_->more) {
        DCHECK(more_iter_ != current_->more->end());
        ++more_iter_;
        if (more_iter_ != current_->more->end()) return *this;
      }
      if (level_ == 0) {
        *this = end(def_value_);
        return *this;
      }
      --level_;
      while (current_->key_hash[level_] == kRight || path_[level_] == nullptr) {
        if (level_ == 0) {
          *this = end(def_value_);
          return *this;
        }
        --level_;
      }
      const FocusedTree* first_right_alternative = path_[level_];
      level_++;
      current_ = FindLeftmost(first_right_alternative, &level_, &path_);
      if (current_->more) {
        more_iter_ = current_->more->begin();
      }
    } while (!((**this).second != def_value()));
    return *this;
  }
References v8::internal::DCHECK(), v8::internal::compiler::PersistentMap< Key, Value, Hasher >::def_value_, v8::internal::compiler::PersistentMap< Key, Value, Hasher >::end(), v8::internal::compiler::PersistentMap< Key, Value, Hasher >::FindLeftmost(), and v8::internal::compiler::PersistentMap< Key, Value, Hasher >::kRight.
operator<()
template<class Key , class Value , class Hasher = base::hash<Key>>
bool v8::internal::compiler::PersistentMap< Key, Value, Hasher >::iterator::operator< (const iterator & other) const [inline]
Definition at line 302 of file persistent-map.h.
                                              {
    if (is_end()) return false;
    if (other.is_end()) return true;
    if (current_->key_hash == other.current_->key_hash) {
      return (**this).first < (*other).first;
    } else {
      return current_->key_hash < other.current_->key_hash;
    }
  }
References v8::internal::compiler::PersistentMap< Key, Value, Hasher >::iterator::current_, v8::internal::compiler::PersistentMap< Key, Value, Hasher >::iterator::is_end(), and v8::internal::compiler::PersistentMap< Key, Value, Hasher >::FocusedTree::key_hash.
operator==()
template<class Key , class Value , class Hasher = base::hash<Key>>
bool v8::internal::compiler::PersistentMap< Key, Value, Hasher >::iterator::operator== (const iterator & other) const [inline]
Definition at line 291 of file persistent-map.h.
                                               {
    if (is_end()) return other.is_end();
    if (other.is_end()) return false;
    if (current_->key_hash != other.current_->key_hash) {
      return false;
    } else {
      return (**this).first == (*other).first;
    }
  }
References v8::internal::compiler::PersistentMap< Key, Value, Hasher >::iterator::current_, v8::internal::compiler::PersistentMap< Key, Value, Hasher >::iterator::is_end(), and v8::internal::compiler::PersistentMap< Key, Value, Hasher >::FocusedTree::key_hash.
Member Data Documentation
current_
template<class Key , class Value , class Hasher = base::hash<Key>>
const FocusedTree* v8::internal::compiler::PersistentMap< Key, Value, Hasher >::iterator::current_ [private]
Definition at line 333 of file persistent-map.h.
Referenced by v8::internal::compiler::PersistentMap< Key, Value, Hasher >::iterator::operator<(), and v8::internal::compiler::PersistentMap< Key, Value, Hasher >::iterator::operator==().
def_value_
template<class Key , class Value , class Hasher = base::hash<Key>>
Value v8::internal::compiler::PersistentMap< Key, Value, Hasher >::iterator::def_value_ [private]
Definition at line 335 of file persistent-map.h.
level_
template<class Key , class Value , class Hasher = base::hash<Key>>
int v8::internal::compiler::PersistentMap< Key, Value, Hasher >::iterator::level_ [private]
Definition at line 331 of file persistent-map.h.
more_iter_
template<class Key , class Value , class Hasher = base::hash<Key>>
FocusedTree::more_iterator v8::internal::compiler::PersistentMap< Key, Value, Hasher >::iterator::more_iter_ [private]
Definition at line 332 of file persistent-map.h.
path_
template<class Key , class Value , class Hasher = base::hash<Key>>
std::array<const FocusedTree*, kHashBits> v8::internal::compiler::PersistentMap< Key, Value, Hasher >::iterator::path_ [private]
Definition at line 334 of file persistent-map.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/persistent-map.h