v8::debug::Coverage::FunctionData Class Reference
#include <debug-interface.h>
Public Member Functions
MOVE_ONLY_NO_DEFAULT_CONSTRUCTOR (FunctionData)
int StartOffset () const
int EndOffset () const
uint32_t Count () const
MaybeLocal< String > Name () const
size_t BlockCount () const
bool HasBlockCoverage () const
BlockData GetBlockData (size_t i) const
Private Member Functions
FunctionData (i::CoverageFunction *function, std::shared_ptr< i::Coverage > coverage)
Private Attributes
i::CoverageFunction * function_
std::shared_ptr< i::Coverage > coverage_
Friends
class v8::debug::Coverage::ScriptData
Detailed Description
Definition at line 420 of file debug-interface.h.
Constructor & Destructor Documentation
FunctionData()
v8::debug::Coverage::FunctionData::FunctionData (i::CoverageFunction * function, std::shared_ptr< i::Coverage > coverage) [inline], [explicit], [private]
Definition at line 433 of file debug-interface.h.
        : function_(function), coverage_(std::move(coverage)) {}
Member Function Documentation
BlockCount()
size_t v8::debug::Coverage::FunctionData::BlockCount () const
Definition at line 1346 of file debug-interface.cc.
                                              {
  return function_->blocks.size();
}
Referenced by v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::coverageToProtocol(), and v8::Shell::WriteLcovData().
Count()
uint32_t v8::debug::Coverage::FunctionData::Count () const
Definition at line 1340 of file debug-interface.cc.
{ return function_->count; }
Referenced by v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::coverageToProtocol(), and v8::Shell::WriteLcovData().
EndOffset()
int v8::debug::Coverage::FunctionData::EndOffset () const
Definition at line 1338 of file debug-interface.cc.
{ return function_->end; }
Referenced by v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::coverageToProtocol(), and v8::Shell::WriteLcovData().
GetBlockData()
Coverage::BlockData v8::debug::Coverage::FunctionData::GetBlockData (size_t i) const
Definition at line 1354 of file debug-interface.cc.
                                                                   {
  return BlockData(&function_->blocks.at(i), coverage_);
}
References v8::debug::Coverage::coverage_.
Referenced by v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::coverageToProtocol(), and v8::Shell::WriteLcovData().
HasBlockCoverage()
bool v8::debug::Coverage::FunctionData::HasBlockCoverage () const
Definition at line 1350 of file debug-interface.cc.
                                                  {
  return function_->has_block_coverage;
}
Referenced by v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::coverageToProtocol().
MOVE_ONLY_NO_DEFAULT_CONSTRUCTOR()
v8::debug::Coverage::FunctionData::MOVE_ONLY_NO_DEFAULT_CONSTRUCTOR (FunctionData)
Name()
MaybeLocal< String > v8::debug::Coverage::FunctionData::Name () const
Definition at line 1342 of file debug-interface.cc.
                                                    {
  return ToApiHandle<String>(function_->name);
}
Referenced by v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::coverageToProtocol(), and v8::Shell::WriteLcovData().
StartOffset()
int v8::debug::Coverage::FunctionData::StartOffset () const
Definition at line 1336 of file debug-interface.cc.
{ return function_->start; }
Referenced by v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::coverageToProtocol(), and v8::Shell::WriteLcovData().
Friends And Related Function Documentation
v8::debug::Coverage::ScriptData
friend class v8::debug::Coverage::ScriptData [friend]
Definition at line 440 of file debug-interface.h.
Member Data Documentation
coverage_
std::shared_ptr<i::Coverage> v8::debug::Coverage::FunctionData::coverage_ [private]
Definition at line 438 of file debug-interface.h.
function_
i::CoverageFunction* v8::debug::Coverage::FunctionData::function_ [private]
Definition at line 437 of file debug-interface.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/debug/debug-interface.h
/mnt/V8SourceCode/src/debug/debug-interface.cc