v8::internal::wasm::gdb_server::Target Class Reference
#include <target.h>
Public Member Functions
Target (GdbServer *gdb_server)
Target (const Target &)=delete
Target & operator= (const Target &)=delete
void Run (Session *ses)
void Terminate ()
bool IsTerminated () const
void OnProgramBreak (Isolate *isolate, const std::vector< wasm_addr_t > &call_frames)
void OnException (Isolate *isolate, const std::vector< wasm_addr_t > &call_frames)
const std::vector< wasm_addr_t > GetCallStack () const
wasm_addr_t GetCurrentPc () const
Isolate * GetCurrentIsolate () const
Private Types
enum class ErrorCode { None = 0
, BadFormat = 1
, BadArgs = 2
, Failed = 3
 }
enum class ProcessPacketResult { Paused
, Continue
, Detach
, Kill
 }
enum class Status { Running
, WaitingForSuspension
, Suspended
, Terminated
 }
typedef std::map< std::string, std::string > QueryPropertyMap
Private Member Functions
void OnSuspended (Isolate *isolate, int signal, const std::vector< wasm_addr_t > &call_frames)
void InitQueryPropertyMap ()
void WaitForDebugEvent ()
void ProcessDebugEvent ()
void ProcessCommands ()
void Suspend ()
ProcessPacketResult ProcessPacket (Packet *pkt_in, Packet *pkt_out)
ErrorCode ProcessQueryPacket (const Packet *pkt_in, Packet *pkt_out)
void SetStopReply (Packet *pkt_out) const
void SetStatus (Status status, int8_t signal=0, std::vector< wasm_addr_t > call_frames_={}, Isolate *isolate=nullptr)
Private Attributes
GdbServer * gdb_server_
std::atomic< Status > status_
std::atomic< int8_t > cur_signal_
Session * session_
QueryPropertyMap query_properties_
bool debugger_initial_suspension_
v8::base::Semaphore semaphore_
v8::base::Mutex mutex_
Isolate * current_isolate_
std::vector< wasm_addr_t > call_frames_
Detailed Description
Definition at line 27 of file target.h.
Member Typedef Documentation
QueryPropertyMap
typedef std::map<std::string, std::string> v8::internal::wasm::gdb_server::Target::QueryPropertyMap [private]
Definition at line 113 of file target.h.
Member Enumeration Documentation
ErrorCode
enum v8::internal::wasm::gdb_server::Target::ErrorCode [strong], [private]
Enumerator
None
BadFormat
BadArgs
Failed
Definition at line 75 of file target.h.
{ None = 0, BadFormat = 1, BadArgs = 2, Failed = 3 };
ProcessPacketResult
enum v8::internal::wasm::gdb_server::Target::ProcessPacketResult [strong], [private]
Enumerator
Paused
Continue
Detach
Kill
Definition at line 77 of file target.h.
                                 {
    Paused, // The command was processed, debuggee still paused.
    Continue, // The debuggee should resume execution.
    Detach, // Request to detach from the debugger.
    Kill // Request to terminate the debuggee process.
  };
Status
enum v8::internal::wasm::gdb_server::Target::Status [strong], [private]
Enumerator
Running
WaitingForSuspension
Suspended
Terminated
Definition at line 96 of file target.h.
{ Running, WaitingForSuspension, Suspended, Terminated };
Constructor & Destructor Documentation
Target() [1/2]
v8::internal::wasm::gdb_server::Target::Target (GdbServer * gdb_server) [explicit]
Definition at line 26 of file target.cc.
    : gdb_server_(gdb_server),
      status_(Status::Running),
      cur_signal_(0),
      session_(nullptr),
      debugger_initial_suspension_(true),
      semaphore_(0),
      current_isolate_(nullptr) {
  InitQueryPropertyMap();
}
References InitQueryPropertyMap().
Target() [2/2]
v8::internal::wasm::gdb_server::Target::Target (const Target &) [delete]
Member Function Documentation
GetCallStack()
const std::vector< wasm_addr_t > v8::internal::wasm::gdb_server::Target::GetCallStack () const
Definition at line 685 of file target.cc.
                                                        {
  v8::base::MutexGuard guard(&mutex_);
  return call_frames_;
}
References call_frames_, and mutex_.
GetCurrentIsolate()
Isolate* v8::internal::wasm::gdb_server::Target::GetCurrentIsolate () const [inline]
Definition at line 51 of file target.h.
{ return current_isolate_; }
References current_isolate_.
GetCurrentPc()
wasm_addr_t v8::internal::wasm::gdb_server::Target::GetCurrentPc () const
Definition at line 691 of file target.cc.
                                       {
  v8::base::MutexGuard guard(&mutex_);
  wasm_addr_t pc{0};
  if (call_frames_.size() > 0) {
    pc = call_frames_[0];
  }
  return pc;
}
References call_frames_, and mutex_.
Referenced by ProcessPacket(), and SetStopReply().
InitQueryPropertyMap()
void v8::internal::wasm::gdb_server::Target::InitQueryPropertyMap () [private]
Definition at line 37 of file target.cc.
                                  {
  // Request LLDB to send packets up to 4000 bytes for bulk transfers.
  query_properties_["Supported"] =
      "PacketSize=1000;vContSupported-;qXfer:libraries:read+;wasm+;";
  query_properties_["Attached"] = "1";
  // There is only one register, named 'pc', in this architecture
  query_properties_["RegisterInfo0"] =
      "name:pc;alt-name:pc;bitsize:64;offset:0;encoding:uint;format:hex;set:"
      "General Purpose Registers;gcc:16;dwarf:16;generic:pc;";
  query_properties_["RegisterInfo1"] = "E45";
  // ProcessInfo for wasm32
  query_properties_["ProcessInfo"] =
      "pid:1;ppid:1;uid:1;gid:1;euid:1;egid:1;name:6c6c6462;triple:" +
      Mem2Hex("wasm32-unknown-unknown-wasm") + ";ptrsize:4;";
  query_properties_["Symbol"] = "OK";
  // Current thread info
  char buff[16];
  snprintf(buff, sizeof(buff), "QC%x", kThreadId);
  query_properties_["C"] = buff;
}
References v8::internal::wasm::gdb_server::kThreadId, v8::internal::wasm::gdb_server::Mem2Hex(), and query_properties_.
Referenced by Target().
IsTerminated()
bool v8::internal::wasm::gdb_server::Target::IsTerminated () const [inline]
Definition at line 38 of file target.h.
{ return status_ == Status::Terminated; }
References status_, and Terminated.
Referenced by ProcessCommands(), and Run().
OnException()
void v8::internal::wasm::gdb_server::Target::OnException (Isolate * isolate, const std::vector< wasm_addr_t > & call_frames)
Definition at line 71 of file target.cc.
                                                                    {
  OnSuspended(isolate, kSigSegv, call_frames);
}
References v8::internal::wasm::gdb_server::kSigSegv, and OnSuspended().
OnProgramBreak()
void v8::internal::wasm::gdb_server::Target::OnProgramBreak (Isolate * isolate, const std::vector< wasm_addr_t > & call_frames)
Definition at line 67 of file target.cc.
                                                                       {
  OnSuspended(isolate, kSigTrace, call_frames);
}
References v8::internal::wasm::gdb_server::kSigTrace, and OnSuspended().
OnSuspended()
void v8::internal::wasm::gdb_server::Target::OnSuspended (Isolate * isolate, int signal, const std::vector< wasm_addr_t > & call_frames) [private]
Definition at line 75 of file target.cc.
                                                                    {
  // This function will be called in the isolate thread, when the wasm
  // interpreter gets suspended.
  bool isWaitingForSuspension = (status_ == Status::WaitingForSuspension);
  SetStatus(Status::Suspended, signal, call_frames, isolate);
  if (isWaitingForSuspension) {
    // Wake the GdbServer thread that was blocked waiting for the Target
    // to suspend.
    semaphore_.Signal();
  } else if (session_) {
    session_->SignalThreadEvent();
  }
}
References semaphore_, session_, SetStatus(), v8::base::Semaphore::Signal(), v8::internal::wasm::gdb_server::Session::SignalThreadEvent(), status_, Suspended, and WaitingForSuspension.
Referenced by OnException(), and OnProgramBreak().
operator=()
Target& v8::internal::wasm::gdb_server::Target::operator= (const Target &) [delete]
ProcessCommands()
void v8::internal::wasm::gdb_server::Target::ProcessCommands () [private]
Definition at line 152 of file target.cc.
                             {
  // GDB-remote messages are processed in the GDBServer thread.
  if (IsTerminated()) {
    return;
  } else if (status_ != Status::Suspended) {
    // Don't process commands if we haven't stopped.
    return;
  }
  // Now we are ready to process commands.
  // Loop through packets until we process a continue packet or a detach.
  Packet recv, reply;
  while (session_->IsConnected()) {
    if (!session_->GetPacket(&recv)) {
      continue;
    }
    reply.Clear();
    ProcessPacketResult result = ProcessPacket(&recv, &reply);
    switch (result) {
      case ProcessPacketResult::Paused:
        session_->SendPacket(&reply);
        break;
      case ProcessPacketResult::Continue:
        DCHECK_EQ(status_, Status::Running);
        // If this is a continue type command, break out of this loop.
        gdb_server_->QuitMessageLoopOnPause();
        return;
      case ProcessPacketResult::Detach:
        SetStatus(Status::Running);
        session_->SendPacket(&reply);
        session_->Disconnect();
        gdb_server_->QuitMessageLoopOnPause();
        return;
      case ProcessPacketResult::Kill:
        session_->SendPacket(&reply);
        exit(-9);
      default:
        UNREACHABLE();
    }
  }
  if (!session_->IsConnected()) {
    debugger_initial_suspension_ = true;
  }
}
References v8::internal::wasm::gdb_server::Packet::Clear(), Continue, DCHECK_EQ, debugger_initial_suspension_, Detach, v8::internal::wasm::gdb_server::Session::Disconnect(), gdb_server_, v8::internal::wasm::gdb_server::Session::GetPacket(), v8::internal::wasm::gdb_server::Session::IsConnected(), IsTerminated(), Kill, Paused, ProcessPacket(), v8::internal::wasm::gdb_server::GdbServer::QuitMessageLoopOnPause(), v8::base::internal::result, Running, v8::internal::wasm::gdb_server::Session::SendPacket(), session_, SetStatus(), status_, Suspended, and v8::internal::UNREACHABLE().
Referenced by Run().
ProcessDebugEvent()
void v8::internal::wasm::gdb_server::Target::ProcessDebugEvent () [private]
Definition at line 113 of file target.cc.
                               {
  // Executed in the GdbServer thread
  if (status_ == Status::Running) {
    // Blocks, waiting for the engine to suspend.
    Suspend();
  }
  // Here, the wasm interpreter has suspended and we have updated the current
  // thread info.
  if (debugger_initial_suspension_) {
    // First time on a connection, we don't send the signal.
    // All other times, send the signal that triggered us.
    debugger_initial_suspension_ = false;
  } else {
    Packet pktOut;
    SetStopReply(&pktOut);
    session_->SendPacket(&pktOut, false);
  }
}
References debugger_initial_suspension_, Running, v8::internal::wasm::gdb_server::Session::SendPacket(), session_, SetStopReply(), status_, and Suspend().
Referenced by Run().
ProcessPacket()
Target::ProcessPacketResult v8::internal::wasm::gdb_server::Target::ProcessPacket (Packet * pkt_in, Packet * pkt_out) [private]
Definition at line 204 of file target.cc.
                                                                   {
  ErrorCode err = ErrorCode::None;
  // Clear the outbound message.
  pkt_out->Clear();
  // Set the sequence number, if present.
  int32_t seq = -1;
  if (pkt_in->GetSequence(&seq)) {
    pkt_out->SetSequence(seq);
  }
  // A GDB-remote packet begins with an upper- or lower-case letter, which
  // generally represents a single command.
  // The letters 'q' and 'Q' introduce a "General query packets" and are used
  // to extend the protocol with custom commands.
  // The format of GDB-remote commands is documented here:
  // https://sourceware.org/gdb/onlinedocs/gdb/Overview.html#Overview.
  char cmd;
  pkt_in->GetRawChar(&cmd);
  switch (cmd) {
    // Queries the reason the target halted.
    // IN : $?
    // OUT: A Stop-reply packet
    case '?':
      SetStopReply(pkt_out);
      break;
    // Resumes execution
    // IN : $c
    // OUT: A Stop-reply packet is sent later, when the execution halts.
    case 'c':
      SetStatus(Status::Running);
      return ProcessPacketResult::Continue;
    // Detaches the debugger from this target
    // IN : $D
    // OUT: $OK
    case 'D':
      TRACE_GDB_REMOTE("Requested Detach.\n");
      pkt_out->AddString("OK");
      return ProcessPacketResult::Detach;
    // Read general registers (We only support register 'pc' that contains
    // the current instruction pointer).
    // IN : $g
    // OUT: $xx...xx
    case 'g': {
      uint64_t pc = GetCurrentPc();
      pkt_out->AddBlock(&pc, sizeof(pc));
      break;
    }
    // Write general registers - NOT SUPPORTED
    // IN : $Gxx..xx
    // OUT: $ (empty string)
    case 'G': {
      break;
    }
    // Set thread for subsequent operations. For Wasm targets, we currently
    // assume that there is only one thread with id = kThreadId (= 1).
    // IN : $H(c/g)(-1,0,xxxx)
    // OUT: $OK
    case 'H': {
      // Type of the operation (m, M, g, G, ...)
      char operation;
      if (!pkt_in->GetRawChar(&operation)) {
        err = ErrorCode::BadFormat;
        break;
      }
      uint64_t thread_id;
      if (!pkt_in->GetNumberSep(&thread_id, 0)) {
        err = ErrorCode::BadFormat;
        break;
      }
      // Ignore, only one thread supported for now.
      pkt_out->AddString("OK");
      break;
    }
    // Kills the debuggee.
    // IN : $k
    // OUT: $OK
    case 'k':
      TRACE_GDB_REMOTE("Requested Kill.\n");
      pkt_out->AddString("OK");
      return ProcessPacketResult::Kill;
    // Reads {llll} addressable memory units starting at address {aaaa}.
    // IN : $maaaa,llll
    // OUT: $xx..xx
    case 'm': {
      uint64_t address;
      if (!pkt_in->GetNumberSep(&address, 0)) {
        err = ErrorCode::BadFormat;
        break;
      }
      wasm_addr_t wasm_addr(address);
      uint64_t len;
      if (!pkt_in->GetNumberSep(&len, 0)) {
        err = ErrorCode::BadFormat;
        break;
      }
      if (len > Transport::kBufSize / 2) {
        err = ErrorCode::BadArgs;
        break;
      }
      uint32_t length = static_cast<uint32_t>(len);
      uint8_t buff[Transport::kBufSize];
      if (wasm_addr.ModuleId() > 0) {
        uint32_t read =
            gdb_server_->GetWasmModuleBytes(wasm_addr, buff, length);
        if (read > 0) {
          pkt_out->AddBlock(buff, read);
        } else {
          err = ErrorCode::Failed;
        }
      } else {
        err = ErrorCode::BadArgs;
      }
      break;
    }
    // Writes {llll} addressable memory units starting at address {aaaa}.
    // IN : $Maaaa,llll:xx..xx
    // OUT: $OK
    case 'M': {
      // Writing to memory not supported for Wasm.
      err = ErrorCode::Failed;
      break;
    }
    // pN: Reads the value of register N.
    // IN : $pxx
    // OUT: $xx..xx
    case 'p': {
      uint64_t pc = GetCurrentPc();
      pkt_out->AddBlock(&pc, sizeof(pc));
    } break;
    case 'q': {
      err = ProcessQueryPacket(pkt_in, pkt_out);
      break;
    }
    // Single step
    // IN : $s
    // OUT: A Stop-reply packet is sent later, when the execution halts.
    case 's': {
      if (status_ == Status::Suspended) {
        gdb_server_->PrepareStep();
        SetStatus(Status::Running);
      }
      return ProcessPacketResult::Continue;
    }
    // Find out if the thread 'id' is alive.
    // IN : $T
    // OUT: $OK if alive, $Enn if thread is dead.
    case 'T': {
      uint64_t id;
      if (!pkt_in->GetNumberSep(&id, 0)) {
        err = ErrorCode::BadFormat;
        break;
      }
      if (id != kThreadId) {
        err = ErrorCode::BadArgs;
        break;
      }
      pkt_out->AddString("OK");
      break;
    }
    // Z: Adds a breakpoint
    // IN : $Z<type>,<addr>,<kind>
    // <type>: 0: sw breakpoint, 1: hw breakpoint, 2: watchpoint
    // OUT: $OK (success) or $Enn (error)
    case 'Z': {
      uint64_t breakpoint_type;
      uint64_t breakpoint_address;
      uint64_t breakpoint_kind;
      // Only software breakpoints are supported.
      if (!pkt_in->GetNumberSep(&breakpoint_type, 0) || breakpoint_type != 0 ||
          !pkt_in->GetNumberSep(&breakpoint_address, 0) ||
          !pkt_in->GetNumberSep(&breakpoint_kind, 0)) {
        err = ErrorCode::BadFormat;
        break;
      }
      wasm_addr_t wasm_breakpoint_addr(breakpoint_address);
      if (!gdb_server_->AddBreakpoint(wasm_breakpoint_addr.ModuleId(),
                                      wasm_breakpoint_addr.Offset())) {
        err = ErrorCode::Failed;
        break;
      }
      pkt_out->AddString("OK");
      break;
    }
    // z: Removes a breakpoint
    // IN : $z<type>,<addr>,<kind>
    // <type>: 0: sw breakpoint, 1: hw breakpoint, 2: watchpoint
    // OUT: $OK (success) or $Enn (error)
    case 'z': {
      uint64_t breakpoint_type;
      uint64_t breakpoint_address;
      uint64_t breakpoint_kind;
      if (!pkt_in->GetNumberSep(&breakpoint_type, 0) || breakpoint_type != 0 ||
          !pkt_in->GetNumberSep(&breakpoint_address, 0) ||
          !pkt_in->GetNumberSep(&breakpoint_kind, 0)) {
        err = ErrorCode::BadFormat;
        break;
      }
      wasm_addr_t wasm_breakpoint_addr(breakpoint_address);
      if (!gdb_server_->RemoveBreakpoint(wasm_breakpoint_addr.ModuleId(),
                                         wasm_breakpoint_addr.Offset())) {
        err = ErrorCode::Failed;
        break;
      }
      pkt_out->AddString("OK");
      break;
    }
    // If the command is not recognized, ignore it by sending an empty reply.
    default: {
      TRACE_GDB_REMOTE("Unknown command: %s\n", pkt_in->GetPayload());
    }
  }
  // If there is an error, return the error code instead of a payload
  if (err != ErrorCode::None) {
    pkt_out->Clear();
    pkt_out->AddRawChar('E');
    pkt_out->AddWord8(static_cast<uint8_t>(err));
  }
  return ProcessPacketResult::Paused;
}
References v8::internal::wasm::gdb_server::Packet::AddBlock(), v8::internal::wasm::gdb_server::GdbServer::AddBreakpoint(), v8::internal::wasm::gdb_server::Packet::AddRawChar(), v8::internal::wasm::gdb_server::Packet::AddString(), v8::internal::wasm::gdb_server::Packet::AddWord8(), BadArgs, BadFormat, v8::internal::wasm::gdb_server::Packet::Clear(), Continue, Detach, Failed, gdb_server_, GetCurrentPc(), v8::internal::wasm::gdb_server::Packet::GetNumberSep(), v8::internal::wasm::gdb_server::Packet::GetPayload(), v8::internal::wasm::gdb_server::Packet::GetRawChar(), v8::internal::wasm::gdb_server::Packet::GetSequence(), v8::internal::wasm::gdb_server::GdbServer::GetWasmModuleBytes(), v8::internal::wasm::gdb_server::Transport::kBufSize, Kill, v8::internal::wasm::gdb_server::kThreadId, v8::internal::length, v8::internal::wasm::gdb_server::wasm_addr_t::ModuleId(), None, v8::internal::wasm::gdb_server::wasm_addr_t::Offset(), Paused, v8::internal::wasm::gdb_server::GdbServer::PrepareStep(), ProcessQueryPacket(), v8::internal::wasm::gdb_server::GdbServer::RemoveBreakpoint(), Running, v8::internal::wasm::gdb_server::Packet::SetSequence(), SetStatus(), SetStopReply(), status_, Suspended, v8::internal::anonymous_namespace{thread-id.cc}::thread_id, and TRACE_GDB_REMOTE.
Referenced by ProcessCommands().
ProcessQueryPacket()
Target::ErrorCode v8::internal::wasm::gdb_server::Target::ProcessQueryPacket (const Packet * pkt_in, Packet * pkt_out) [private]
Definition at line 453 of file target.cc.
                                                              {
  const char* str = &pkt_in->GetPayload()[1];
  // Get first thread query
  // IN : $qfThreadInfo
  // OUT: $m<tid>
  //
  // Get next thread query
  // IN : $qsThreadInfo
  // OUT: $m<tid> or l to denote end of list.
  if (!strcmp(str, "fThreadInfo") || !strcmp(str, "sThreadInfo")) {
    if (str[0] == 'f') {
      pkt_out->AddString("m");
      pkt_out->AddNumberSep(kThreadId, 0);
    } else {
      pkt_out->AddString("l");
    }
    return ErrorCode::None;
  }
  // Get a list of loaded libraries
  // IN : $qXfer:libraries:read
  // OUT: an XML document which lists loaded libraries, with this format:
  // <library-list>
  // <library name="foo.wasm">
  // <section address="0x100000000"/>
  // </library>
  // <library name="bar.wasm">
  // <section address="0x200000000"/>
  // </library>
  // </library-list>
  // Note that LLDB must be compiled with libxml2 support to handle this packet.
  std::string tmp = "Xfer:libraries:read";
  if (!strncmp(str, tmp.data(), tmp.length())) {
    std::vector<GdbServer::WasmModuleInfo> modules =
        gdb_server_->GetLoadedModules(true);
    std::string result("l<library-list>");
    for (const auto& module : modules) {
      wasm_addr_t address(module.module_id, 0);
      char address_string[32];
      snprintf(address_string, sizeof(address_string), "%" PRIu64,
               static_cast<uint64_t>(address));
      result += "<library name=\"";
      result += module.module_name;
      result += "\"><section address=\"";
      result += address_string;
      result += "\"/></library>";
    }
    result += "</library-list>";
    pkt_out->AddString(result.c_str());
    return ErrorCode::None;
  }
  // Get the current call stack.
  // IN : $qWasmCallStack
  // OUT: $xx..xxyy..yyzz..zz (A sequence of uint64_t values represented as
  // consecutive 8-bytes blocks).
  std::vector<std::string> toks = StringSplit(str, ":;");
  if (toks[0] == "WasmCallStack") {
    std::vector<wasm_addr_t> call_stack_pcs = gdb_server_->GetWasmCallStack();
    std::vector<uint64_t> buffer;
    for (wasm_addr_t pc : call_stack_pcs) {
      buffer.push_back(pc);
    }
    pkt_out->AddBlock(buffer.data(),
                      static_cast<uint32_t>(sizeof(uint64_t) * buffer.size()));
    return ErrorCode::None;
  }
  // Get a Wasm global value in the Wasm module specified.
  // IN : $qWasmGlobal:frame_index;index
  // OUT: $xx..xx
  if (toks[0] == "WasmGlobal") {
    if (toks.size() == 3) {
      uint32_t frame_index =
          static_cast<uint32_t>(strtol(toks[1].data(), nullptr, 10));
      uint32_t index =
          static_cast<uint32_t>(strtol(toks[2].data(), nullptr, 10));
      uint8_t buff[16];
      uint32_t size = 0;
      if (gdb_server_->GetWasmGlobal(frame_index, index, buff, 16, &size)) {
        pkt_out->AddBlock(buff, size);
        return ErrorCode::None;
      } else {
        return ErrorCode::Failed;
      }
    }
    return ErrorCode::BadFormat;
  }
  // Get a Wasm local value in the stack frame specified.
  // IN : $qWasmLocal:frame_index;index
  // OUT: $xx..xx
  if (toks[0] == "WasmLocal") {
    if (toks.size() == 3) {
      uint32_t frame_index =
          static_cast<uint32_t>(strtol(toks[1].data(), nullptr, 10));
      uint32_t index =
          static_cast<uint32_t>(strtol(toks[2].data(), nullptr, 10));
      uint8_t buff[16];
      uint32_t size = 0;
      if (gdb_server_->GetWasmLocal(frame_index, index, buff, 16, &size)) {
        pkt_out->AddBlock(buff, size);
        return ErrorCode::None;
      } else {
        return ErrorCode::Failed;
      }
    }
    return ErrorCode::BadFormat;
  }
  // Get a Wasm local from the operand stack at the index specified.
  // IN : qWasmStackValue:frame_index;index
  // OUT: $xx..xx
  if (toks[0] == "WasmStackValue") {
    if (toks.size() == 3) {
      uint32_t frame_index =
          static_cast<uint32_t>(strtol(toks[1].data(), nullptr, 10));
      uint32_t index =
          static_cast<uint32_t>(strtol(toks[2].data(), nullptr, 10));
      uint8_t buff[16];
      uint32_t size = 0;
      if (gdb_server_->GetWasmStackValue(frame_index, index, buff, 16, &size)) {
        pkt_out->AddBlock(buff, size);
        return ErrorCode::None;
      } else {
        return ErrorCode::Failed;
      }
    }
    return ErrorCode::BadFormat;
  }
  // Read Wasm Memory.
  // IN : $qWasmMem:module_id;addr;len
  // OUT: $xx..xx
  if (toks[0] == "WasmMem") {
    if (toks.size() == 4) {
      uint32_t module_id = strtoul(toks[1].data(), nullptr, 10);
      uint32_t address = strtoul(toks[2].data(), nullptr, 16);
      uint32_t length = strtoul(toks[3].data(), nullptr, 16);
      if (length > Transport::kBufSize / 2) {
        return ErrorCode::BadArgs;
      }
      uint8_t buff[Transport::kBufSize];
      uint32_t read =
          gdb_server_->GetWasmMemory(module_id, address, buff, length);
      if (read > 0) {
        pkt_out->AddBlock(buff, read);
        return ErrorCode::None;
      } else {
        return ErrorCode::Failed;
      }
    }
    return ErrorCode::BadFormat;
  }
  // Read Wasm Data.
  // IN : $qWasmData:module_id;addr;len
  // OUT: $xx..xx
  if (toks[0] == "WasmData") {
    if (toks.size() == 4) {
      uint32_t module_id = strtoul(toks[1].data(), nullptr, 10);
      uint32_t address = strtoul(toks[2].data(), nullptr, 16);
      uint32_t length = strtoul(toks[3].data(), nullptr, 16);
      if (length > Transport::kBufSize / 2) {
        return ErrorCode::BadArgs;
      }
      uint8_t buff[Transport::kBufSize];
      uint32_t read =
          gdb_server_->GetWasmData(module_id, address, buff, length);
      if (read > 0) {
        pkt_out->AddBlock(buff, read);
        return ErrorCode::None;
      } else {
        return ErrorCode::Failed;
      }
    }
    return ErrorCode::BadFormat;
  }
  // No match so far, check the property cache.
  QueryPropertyMap::const_iterator it = query_properties_.find(toks[0]);
  if (it != query_properties_.end()) {
    pkt_out->AddString(it->second.data());
  }
  // If not found, just send an empty response.
  return ErrorCode::None;
}
References v8::internal::wasm::gdb_server::Packet::AddBlock(), v8::internal::wasm::gdb_server::Packet::AddNumberSep(), v8::internal::wasm::gdb_server::Packet::AddString(), BadArgs, BadFormat, Failed, gdb_server_, v8::internal::wasm::gdb_server::GdbServer::GetLoadedModules(), v8::internal::wasm::gdb_server::Packet::GetPayload(), v8::internal::wasm::gdb_server::GdbServer::GetWasmCallStack(), v8::internal::wasm::gdb_server::GdbServer::GetWasmData(), v8::internal::wasm::gdb_server::GdbServer::GetWasmGlobal(), v8::internal::wasm::gdb_server::GdbServer::GetWasmLocal(), v8::internal::wasm::gdb_server::GdbServer::GetWasmMemory(), v8::internal::wasm::gdb_server::GdbServer::GetWasmStackValue(), v8::internal::index, v8::internal::wasm::gdb_server::Transport::kBufSize, v8::internal::wasm::gdb_server::kThreadId, v8::internal::length, None, query_properties_, v8::base::internal::result, size(), v8::internal::string, and v8::internal::wasm::gdb_server::StringSplit().
Referenced by ProcessPacket().
Run()
void v8::internal::wasm::gdb_server::Target::Run (Session * ses)
Definition at line 91 of file target.cc.
                                 {
  // Executed in the GdbServer thread.
  session_ = session;
  do {
    WaitForDebugEvent();
    ProcessDebugEvent();
    ProcessCommands();
  } while (!IsTerminated() && session_->IsConnected());
  session_ = nullptr;
}
References v8::internal::wasm::gdb_server::Session::IsConnected(), IsTerminated(), ProcessCommands(), ProcessDebugEvent(), session_, and WaitForDebugEvent().
SetStatus()
void v8::internal::wasm::gdb_server::Target::SetStatus (Status status, int8_t signal = 0, std::vector< wasm_addr_t > call_frames_ = {}, Isolate * isolate = nullptr) [private]
Definition at line 670 of file target.cc.
                                                                             {
  v8::base::MutexGuard guard(&mutex_);
  DCHECK((status == Status::Suspended && signal != 0 &&
          call_frames.size() > 0 && isolate != nullptr) ||
         (status != Status::Suspended && signal == 0 &&
          call_frames.size() == 0 && isolate == nullptr));
  current_isolate_ = isolate;
  status_ = status;
  cur_signal_ = signal;
  call_frames_ = call_frames;
}
References call_frames_, cur_signal_, current_isolate_, v8::internal::DCHECK(), mutex_, v8::internal::status, status_, and Suspended.
Referenced by OnSuspended(), ProcessCommands(), ProcessPacket(), and Terminate().
SetStopReply()
void v8::internal::wasm::gdb_server::Target::SetStopReply (Packet * pkt_out) const [private]
Definition at line 650 of file target.cc.
                                               {
  pkt_out->AddRawChar('T');
  pkt_out->AddWord8(cur_signal_);
  // Adds 'thread-pcs:<pc1>,...,<pcN>;' A list of pc values for all threads that
  // currently exist in the process.
  char buff[64];
  snprintf(buff, sizeof(buff), "thread-pcs:%" PRIx64 ";",
           static_cast<uint64_t>(GetCurrentPc()));
  pkt_out->AddString(buff);
  // Adds 'thread:<tid>;' pair. Note that a terminating ';' is required.
  pkt_out->AddString("thread:");
  pkt_out->AddNumberSep(kThreadId, ';');
  // If the loaded modules have changed since the last stop packet, signals
  // that.
  if (gdb_server_->HasModuleListChanged()) pkt_out->AddString("library:;");
}
References v8::internal::wasm::gdb_server::Packet::AddNumberSep(), v8::internal::wasm::gdb_server::Packet::AddRawChar(), v8::internal::wasm::gdb_server::Packet::AddString(), v8::internal::wasm::gdb_server::Packet::AddWord8(), cur_signal_, gdb_server_, GetCurrentPc(), v8::internal::wasm::gdb_server::GdbServer::HasModuleListChanged(), and v8::internal::wasm::gdb_server::kThreadId.
Referenced by ProcessDebugEvent(), and ProcessPacket().
Suspend()
void v8::internal::wasm::gdb_server::Target::Suspend () [private]
Definition at line 135 of file target.cc.
                     {
  // Executed in the GdbServer thread
  if (status_ == Status::Running) {
    // TODO(paolosev) - this only suspends the wasm interpreter.
    gdb_server_->Suspend();
    status_ = Status::WaitingForSuspension;
  }
  while (status_ == Status::WaitingForSuspension) {
    if (semaphore_.WaitFor(base::TimeDelta::FromMilliseconds(500))) {
      // Here the wasm interpreter is suspended.
      return;
    }
  }
}
References v8::base::TimeDelta::FromMilliseconds(), gdb_server_, Running, semaphore_, status_, v8::internal::wasm::gdb_server::GdbServer::Suspend(), v8::base::Semaphore::WaitFor(), and WaitingForSuspension.
Referenced by ProcessDebugEvent().
Terminate()
void v8::internal::wasm::gdb_server::Target::Terminate ()
Definition at line 62 of file target.cc.
                       {
  // Executed in the Isolate thread, when the process shuts down.
  SetStatus(Status::Terminated);
}
References SetStatus(), and Terminated.
WaitForDebugEvent()
void v8::internal::wasm::gdb_server::Target::WaitForDebugEvent () [private]
Definition at line 102 of file target.cc.
                               {
  // Executed in the GdbServer thread.
  if (status_ == Status::Running) {
    // Wait for either:
    // * the thread to fault (or single-step)
    // * an interrupt from LLDB
    session_->WaitForDebugStubEvent();
  }
}
References Running, session_, status_, and v8::internal::wasm::gdb_server::Session::WaitForDebugStubEvent().
Referenced by Run().
Member Data Documentation
call_frames_
std::vector<wasm_addr_t> v8::internal::wasm::gdb_server::Target::call_frames_ [private]
Definition at line 131 of file target.h.
Referenced by GetCallStack(), GetCurrentPc(), and SetStatus().
cur_signal_
std::atomic<int8_t> v8::internal::wasm::gdb_server::Target::cur_signal_ [private]
Definition at line 107 of file target.h.
Referenced by SetStatus(), and SetStopReply().
current_isolate_
Isolate* v8::internal::wasm::gdb_server::Target::current_isolate_ [private]
Definition at line 128 of file target.h.
Referenced by GetCurrentIsolate(), and SetStatus().
debugger_initial_suspension_
bool v8::internal::wasm::gdb_server::Target::debugger_initial_suspension_ [private]
Definition at line 116 of file target.h.
Referenced by ProcessCommands(), and ProcessDebugEvent().
gdb_server_
GdbServer* v8::internal::wasm::gdb_server::Target::gdb_server_ [private]
Definition at line 102 of file target.h.
Referenced by ProcessCommands(), ProcessPacket(), ProcessQueryPacket(), SetStopReply(), and Suspend().
mutex_
v8::base::Mutex v8::internal::wasm::gdb_server::Target::mutex_ [mutable], [private]
Definition at line 121 of file target.h.
Referenced by GetCallStack(), GetCurrentPc(), and SetStatus().
query_properties_
QueryPropertyMap v8::internal::wasm::gdb_server::Target::query_properties_ [private]
Definition at line 114 of file target.h.
Referenced by InitQueryPropertyMap(), and ProcessQueryPacket().
semaphore_
v8::base::Semaphore v8::internal::wasm::gdb_server::Target::semaphore_ [private]
Definition at line 119 of file target.h.
Referenced by OnSuspended(), and Suspend().
session_
Session* v8::internal::wasm::gdb_server::Target::session_ [private]
Definition at line 110 of file target.h.
Referenced by OnSuspended(), ProcessCommands(), ProcessDebugEvent(), Run(), and WaitForDebugEvent().
status_
std::atomic<Status> v8::internal::wasm::gdb_server::Target::status_ [private]
Definition at line 104 of file target.h.
Referenced by IsTerminated(), OnSuspended(), ProcessCommands(), ProcessDebugEvent(), ProcessPacket(), SetStatus(), Suspend(), and WaitForDebugEvent().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/debug/wasm/gdb-server/target.h
/mnt/V8SourceCode/src/debug/wasm/gdb-server/target.cc