v8::internal::LiveObjectRange::iterator Class Reference
#include <live-object-range.h>
Public Types
using value_type = std::pair< Tagged< HeapObject >, int >
using pointer = const value_type *
using reference = const value_type &
using iterator_category = std::forward_iterator_tag
Public Member Functions
iterator ()
iterator (const PageMetadata *page)
iterator & operator++ ()
iterator operator++ (int)
bool operator== (iterator other) const
bool operator!= (iterator other) const
value_type operator* ()
Private Member Functions
bool AdvanceToNextMarkedObject ()
void AdvanceToNextValidObject ()
Private Attributes
const PageMetadata *const page_ = nullptr
const MarkBit::CellType *const cells_ = nullptr
const PtrComprCageBase cage_base_
MarkingBitmap::CellIndex current_cell_index_ = 0
MarkingBitmap::CellType current_cell_ = 0
Tagged< HeapObject > current_object_
Tagged< Map > current_map_
int current_size_ = 0
Detailed Description
Definition at line 19 of file live-object-range.h.
Member Typedef Documentation
iterator_category
using v8::internal::LiveObjectRange::iterator::iterator_category = std::forward_iterator_tag
Definition at line 24 of file live-object-range.h.
pointer
using v8::internal::LiveObjectRange::iterator::pointer = const value_type*
Definition at line 22 of file live-object-range.h.
reference
using v8::internal::LiveObjectRange::iterator::reference = const value_type&
Definition at line 23 of file live-object-range.h.
value_type
using v8::internal::LiveObjectRange::iterator::value_type = std::pair<Tagged<HeapObject>, int >
Definition at line 21 of file live-object-range.h.
Constructor & Destructor Documentation
iterator() [1/2]
v8::internal::LiveObjectRange::iterator::iterator () [inline]
Definition at line 17 of file live-object-range-inl.h.
: cage_base_(kNullAddress) {}
iterator() [2/2]
v8::internal::LiveObjectRange::iterator::iterator (const PageMetadata * page) [inline], [explicit]
Definition at line 19 of file live-object-range-inl.h.
    : page_(page),
      cells_(page->marking_bitmap()->cells()),
      cage_base_(page->heap()->isolate()),
      current_cell_index_(MarkingBitmap::IndexToCell(
          MarkingBitmap::AddressToIndex(page->area_start()))),
      current_cell_(cells_[current_cell_index_]) {
  AdvanceToNextValidObject();
}
References AdvanceToNextValidObject().
Member Function Documentation
AdvanceToNextMarkedObject()
bool v8::internal::LiveObjectRange::iterator::AdvanceToNextMarkedObject () [inline], [private]
Definition at line 53 of file live-object-range-inl.h.
                                                        {
  // The following block moves the iterator to the next cell from the current
  // object. This means skipping all possibly set mark bits (in case of black
  // allocation).
  if (!current_object_.is_null()) {
    // Compute an end address that is inclusive. This allows clearing the cell
    // up and including the end address. This works for one word fillers as
    // well as other objects.
    Address next_object = current_object_.address() + current_size_;
    current_object_ = HeapObject();
    if (MemoryChunk::IsAligned(next_object)) {
      return false;
    }
    // Area end may not be exactly aligned to kAlignment. We don't need to bail
    // out for area_end() though as we are guaranteed to have a bit for the
    // whole page.
    DCHECK_LE(next_object, page_->area_end());
    // Move to the corresponding cell of the end index.
    const auto next_markbit_index = MarkingBitmap::AddressToIndex(next_object);
    DCHECK_GE(MarkingBitmap::IndexToCell(next_markbit_index),
              current_cell_index_);
    current_cell_index_ = MarkingBitmap::IndexToCell(next_markbit_index);
    DCHECK_LT(current_cell_index_, MarkingBitmap::kCellsCount);
    // Mask out lower addresses in the cell.
    const MarkBit::CellType mask =
        MarkingBitmap::IndexInCellMask(next_markbit_index);
    current_cell_ = cells_[current_cell_index_] & ~(mask - 1);
  }
  // The next block finds any marked object starting from the current cell.
  const MemoryChunk* chunk = page_->Chunk();
  while (true) {
    if (current_cell_) {
      const auto trailing_zeros = base::bits::CountTrailingZeros(current_cell_);
      Address current_cell_base =
          chunk->address() + MarkingBitmap::CellToBase(current_cell_index_);
      Address object_address = current_cell_base + trailing_zeros * kTaggedSize;
      // The object may be a filler which we want to skip.
      current_object_ = HeapObject::FromAddress(object_address);
      current_map_ = current_object_->map(cage_base_, kAcquireLoad);
      DCHECK(MapWord::IsMapOrForwarded(current_map_));
      current_size_ = ALIGN_TO_ALLOCATION_ALIGNMENT(
          current_object_->SizeFromMap(current_map_));
      CHECK(page_->ContainsLimit(object_address + current_size_));
      return true;
    }
    if (++current_cell_index_ >= MarkingBitmap::kCellsCount) break;
    current_cell_ = cells_[current_cell_index_];
  }
  return false;
}
References v8::internal::MemoryChunk::address(), v8::internal::MarkingBitmap::AddressToIndex(), ALIGN_TO_ALLOCATION_ALIGNMENT, v8::internal::MemoryChunkMetadata::area_end(), v8::internal::MarkingBitmap::CellToBase(), CHECK, v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::MemoryChunkMetadata::ContainsLimit(), v8::base::bits::CountTrailingZeros(), v8::internal::DCHECK(), DCHECK_GE, DCHECK_LE, DCHECK_LT, v8::internal::HeapObject::FromAddress(), v8::internal::MarkingBitmap::IndexInCellMask(), v8::internal::MarkingBitmap::IndexToCell(), v8::internal::MemoryChunk::IsAligned(), v8::internal::MapWord::IsMapOrForwarded(), v8::kAcquireLoad, v8::internal::MarkingBitmap::kCellsCount, v8::internal::kTaggedSize, and v8::internal::LiveObjectRange::page_.
AdvanceToNextValidObject()
void v8::internal::LiveObjectRange::iterator::AdvanceToNextValidObject () [inline], [private]
Definition at line 40 of file live-object-range-inl.h.
                                                       {
  // If we found a regular object we are done. In case of free space, we
  // need to continue.
  //
  // Reading the instance type of the map is safe here even in the presence
  // of the mutator writing a new Map because Map objects are published with
  // release stores (or are otherwise read-only) and the map is retrieved in
  // `AdvanceToNextMarkedObject()` using an acquire load.
  while (AdvanceToNextMarkedObject() &&
         InstanceTypeChecker::IsFreeSpaceOrFiller(current_map_)) {
  }
}
References v8::internal::InstanceTypeChecker::IsFreeSpaceOrFiller().
Referenced by iterator().
operator!=()
bool v8::internal::LiveObjectRange::iterator::operator!= (iterator other) const [inline]
Definition at line 35 of file live-object-range.h.
{ return !(*this == other); }
operator*()
value_type v8::internal::LiveObjectRange::iterator::operator* () [inline]
Definition at line 37 of file live-object-range.h.
                           {
      return std::make_pair(current_object_, current_size_);
    }
References current_object_, and current_size_.
operator++() [1/2]
LiveObjectRange::iterator & v8::internal::LiveObjectRange::iterator::operator++ () [inline]
Definition at line 29 of file live-object-range-inl.h.
                                                             {
  AdvanceToNextValidObject();
  return *this;
}
operator++() [2/2]
LiveObjectRange::iterator v8::internal::LiveObjectRange::iterator::operator++ (int) [inline]
Definition at line 34 of file live-object-range-inl.h.
                                                               {
  iterator retval = *this;
  ++(*this);
  return retval;
}
operator==()
bool v8::internal::LiveObjectRange::iterator::operator== (iterator other) const [inline]
Definition at line 32 of file live-object-range.h.
                                          {
      return current_object_ == other.current_object_;
    }
References current_object_.
Member Data Documentation
cage_base_
const PtrComprCageBase v8::internal::LiveObjectRange::iterator::cage_base_ [private]
Definition at line 47 of file live-object-range.h.
cells_
const MarkBit::CellType* const v8::internal::LiveObjectRange::iterator::cells_ = nullptr [private]
Definition at line 46 of file live-object-range.h.
current_cell_
MarkingBitmap::CellType v8::internal::LiveObjectRange::iterator::current_cell_ = 0 [private]
Definition at line 49 of file live-object-range.h.
current_cell_index_
MarkingBitmap::CellIndex v8::internal::LiveObjectRange::iterator::current_cell_index_ = 0 [private]
Definition at line 48 of file live-object-range.h.
current_map_
Tagged<Map> v8::internal::LiveObjectRange::iterator::current_map_ [private]
Definition at line 51 of file live-object-range.h.
current_object_
Tagged<HeapObject> v8::internal::LiveObjectRange::iterator::current_object_ [private]
Definition at line 50 of file live-object-range.h.
Referenced by operator*(), and operator==().
current_size_
int v8::internal::LiveObjectRange::iterator::current_size_ = 0 [private]
Definition at line 52 of file live-object-range.h.
Referenced by operator*().
page_
const PageMetadata* const v8::internal::LiveObjectRange::iterator::page_ = nullptr [private]
Definition at line 45 of file live-object-range.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/live-object-range.h
/mnt/V8SourceCode/src/heap/live-object-range-inl.h