v8::internal::compiler::IteratingArrayBuiltinReducerAssembler Class Reference
Public Member Functions
IteratingArrayBuiltinReducerAssembler (JSCallReducer *reducer, Node *node)
TNode< Object > ReduceArrayPrototypeForEach (MapInference *inference, const bool has_stability_dependency, ElementsKind kind, SharedFunctionInfoRef shared)
TNode< Object > ReduceArrayPrototypeReduce (MapInference *inference, const bool has_stability_dependency, ElementsKind kind, ArrayReduceDirection direction, SharedFunctionInfoRef shared)
TNode< JSArray > ReduceArrayPrototypeMap (MapInference *inference, const bool has_stability_dependency, ElementsKind kind, SharedFunctionInfoRef shared, NativeContextRef native_context)
TNode< JSArray > ReduceArrayPrototypeFilter (MapInference *inference, const bool has_stability_dependency, ElementsKind kind, SharedFunctionInfoRef shared, NativeContextRef native_context)
TNode< Object > ReduceArrayPrototypeFind (MapInference *inference, const bool has_stability_dependency, ElementsKind kind, SharedFunctionInfoRef shared, NativeContextRef native_context, ArrayFindVariant variant)
TNode< Boolean > ReduceArrayPrototypeEverySome (MapInference *inference, const bool has_stability_dependency, ElementsKind kind, SharedFunctionInfoRef shared, NativeContextRef native_context, ArrayEverySomeVariant variant)
TNode< Object > ReduceArrayPrototypeAt (ZoneVector< MapRef > kinds, bool needs_fallback_builtin_call)
TNode< Object > ReduceArrayPrototypeIndexOfIncludes (ElementsKind kind, ArrayIndexOfIncludesVariant variant)
TNode< Number > ReduceArrayPrototypePush (MapInference *inference)
Private Member Functions
std::pair< TNode< Number >, TNode< Object > > SafeLoadElement (ElementsKind kind, TNode< JSArray > o, TNode< Number > index)
template<typename... Vars>
TNode< Object > MaybeSkipHole (TNode< Object > o, ElementsKind kind, GraphAssemblerLabel< sizeof...(Vars)> *continue_label, TNode< Vars >... vars)
TNode< Smi > LoadJSArrayLength (TNode< JSArray > array, ElementsKind kind)
void StoreJSArrayLength (TNode< JSArray > array, TNode< Number > value, ElementsKind kind)
void StoreFixedArrayBaseElement (TNode< FixedArrayBase > o, TNode< Number > index, TNode< Object > v, ElementsKind kind)
TNode< FixedArrayBase > LoadElements (TNode< JSObject > o)
TNode< Smi > LoadFixedArrayBaseLength (TNode< FixedArrayBase > o)
TNode< Boolean > HoleCheck (ElementsKind kind, TNode< Object > v)
Additional Inherited Members
Detailed Description
Definition at line 441 of file js-call-reducer.cc.
Constructor & Destructor Documentation
IteratingArrayBuiltinReducerAssembler()
v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::IteratingArrayBuiltinReducerAssembler (JSCallReducer * reducer, Node * node) [inline]
Definition at line 443 of file js-call-reducer.cc.
      : JSCallReducerAssembler(reducer, node) {
    DCHECK(v8_flags.turbo_inline_array_builtins);
  }
References v8::internal::DCHECK(), and v8::internal::v8_flags.
Member Function Documentation
HoleCheck()
TNode<Boolean> v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::HoleCheck (ElementsKind kind, TNode< Object > v) [inline], [private]
Definition at line 541 of file js-call-reducer.cc.
                                                               {
    return IsDoubleElementsKind(kind)
               ? NumberIsFloat64Hole(TNode<Number>::UncheckedCast(v))
               : IsTheHole(v);
  }
References v8::internal::IsDoubleElementsKind(), and v8::internal::compiler::JSGraphAssembler::NumberIsFloat64Hole().
Referenced by MaybeSkipHole(), and ReduceArrayPrototypeReduce().
LoadElements()
TNode<FixedArrayBase> v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::LoadElements (TNode< JSObject > o) [inline], [private]
Definition at line 534 of file js-call-reducer.cc.
                                                        {
    return LoadField<FixedArrayBase>(AccessBuilder::ForJSObjectElements(), o);
  }
References v8::internal::compiler::AccessBuilder::ForJSObjectElements().
Referenced by ReduceArrayPrototypeAt(), ReduceArrayPrototypeFilter(), ReduceArrayPrototypeIndexOfIncludes(), and ReduceArrayPrototypePush().
LoadFixedArrayBaseLength()
TNode<Smi> v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::LoadFixedArrayBaseLength (TNode< FixedArrayBase > o) [inline], [private]
Definition at line 537 of file js-call-reducer.cc.
                                                               {
    return LoadField<Smi>(AccessBuilder::ForFixedArrayLength(), o);
  }
References v8::internal::compiler::AccessBuilder::ForFixedArrayLength().
Referenced by ReduceArrayPrototypeFilter(), and ReduceArrayPrototypePush().
LoadJSArrayLength()
TNode<Smi> v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::LoadJSArrayLength (TNode< JSArray > array, ElementsKind kind) [inline], [private]
Definition at line 522 of file js-call-reducer.cc.
                                                                        {
    return LoadField<Smi>(AccessBuilder::ForJSArrayLength(kind), array);
  }
References v8::internal::compiler::AccessBuilder::ForJSArrayLength().
Referenced by ReduceArrayPrototypeAt(), ReduceArrayPrototypeEverySome(), ReduceArrayPrototypeFilter(), ReduceArrayPrototypeFind(), ReduceArrayPrototypeForEach(), ReduceArrayPrototypeIndexOfIncludes(), ReduceArrayPrototypeMap(), ReduceArrayPrototypePush(), ReduceArrayPrototypeReduce(), and SafeLoadElement().
MaybeSkipHole()
template<typename... Vars>
TNode<Object> v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::MaybeSkipHole (TNode< Object > o, ElementsKind kind, GraphAssemblerLabel< sizeof...(Vars)> * continue_label, TNode< Vars >... vars) [inline], [private]
Definition at line 505 of file js-call-reducer.cc.
                           {
    if (!IsHoleyElementsKind(kind)) return o;
    auto if_not_hole = MakeLabel(MachineRepresentationOf<Vars>::value...);
    BranchWithHint(HoleCheck(kind, o), continue_label, &if_not_hole,
                   BranchHint::kFalse, vars...);
    // The contract is that we don't leak "the hole" into "user JavaScript",
    // so we must rename the {element} here to explicitly exclude "the hole"
    // from the type of {element}.
    Bind(&if_not_hole);
    return TypeGuardNonInternal(o);
  }
References v8::internal::compiler::GraphAssembler::Bind(), v8::internal::compiler::GraphAssembler::BranchWithHint(), HoleCheck(), v8::internal::IsHoleyElementsKind(), v8::internal::kFalse, v8::internal::compiler::GraphAssembler::MakeLabel(), and v8::internal::compiler::JSCallReducerAssembler::TypeGuardNonInternal().
Referenced by ReduceArrayPrototypeEverySome(), ReduceArrayPrototypeFilter(), ReduceArrayPrototypeForEach(), ReduceArrayPrototypeMap(), and ReduceArrayPrototypeReduce().
ReduceArrayPrototypeAt()
TNode< Object > v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeAt (ZoneVector< MapRef > kinds, bool needs_fallback_builtin_call)
Definition at line 1375 of file js-call-reducer.cc.
                                                               {
  TNode<JSArray> receiver = ReceiverInputAs<JSArray>();
  TNode<Object> index = ArgumentOrZero(0);
  TNode<Number> index_num = CheckSmi(index);
  TNode<FixedArrayBase> elements = LoadElements(receiver);
  TNode<Map> receiver_map =
      TNode<Map>::UncheckedCast(LoadField(AccessBuilder::ForMap(), receiver));
  auto out = MakeLabel(MachineRepresentation::kTagged);
  for (MapRef map : maps) {
    DCHECK(map.supports_fast_array_iteration(broker()));
    auto correct_map_label = MakeLabel(), wrong_map_label = MakeLabel();
    TNode<Boolean> is_map_equal = ReferenceEqual(receiver_map, Constant(map));
    Branch(is_map_equal, &correct_map_label, &wrong_map_label);
    Bind(&correct_map_label);
    TNode<Number> length = LoadJSArrayLength(receiver, map.elements_kind());
    // If index is less than 0, then subtract from length.
    TNode<Boolean> cond = NumberLessThan(index_num, ZeroConstant());
    TNode<Number> real_index_num =
        SelectIf<Number>(cond)
            .Then(_ { return NumberAdd(length, index_num); })
            .Else(_ { return index_num; })
            .ExpectTrue() // Most common usage should be .at(-1)
            .Value();
    // Bound checking.
    GotoIf(NumberLessThan(real_index_num, ZeroConstant()), &out,
           UndefinedConstant());
    GotoIfNot(NumberLessThan(real_index_num, length), &out,
              UndefinedConstant());
    if (v8_flags.turbo_typer_hardening) {
      real_index_num = CheckBounds(real_index_num, length,
                                   CheckBoundsFlag::kAbortOnOutOfBounds);
    }
    // Retrieving element at index.
    TNode<Object> element = LoadElement<Object>(
        AccessBuilder::ForFixedArrayElement(map.elements_kind()), elements,
        real_index_num);
    if (IsHoleyElementsKind(map.elements_kind())) {
      // This case is needed in particular for HOLEY_DOUBLE_ELEMENTS: raw
      // doubles are stored in the FixedDoubleArray, and need to be converted to
      // HeapNumber or to Smi so that this function can return an Object. The
      // automatic converstion performed by
      // RepresentationChanger::GetTaggedRepresentationFor does not handle
      // holes, so we convert manually a potential hole here.
      element = ConvertHoleToUndefined(element, map.elements_kind());
    }
    Goto(&out, element);
    Bind(&wrong_map_label);
  }
  if (needs_fallback_builtin_call) {
    JSCallNode n(node_ptr());
    CallParameters const& p = n.Parameters();
    // We set SpeculationMode to kDisallowSpeculation to avoid infinite
    // recursion on the node we're creating (since, after all, it's calling
    // Array.Prototype.at).
    const Operator* op = javascript()->Call(
        JSCallNode::ArityForArgc(1), p.frequency(), p.feedback(),
        ConvertReceiverMode::kNotNullOrUndefined,
        SpeculationMode::kDisallowSpeculation, CallFeedbackRelation::kTarget);
    Node* fallback_builtin = node_ptr()->InputAt(0);
    TNode<Object> res = MayThrow(_ {
      return AddNode<Object>(graph()->NewNode(
          op, fallback_builtin, receiver, index, n.feedback_vector(),
          ContextInput(), n.frame_state(), effect(), control()));
    });
    Goto(&out, res);
  } else {
    Goto(&out, UndefinedConstant());
  }
  Bind(&out);
  return out.PhiAt<Object>(0);
}
References _, v8::internal::compiler::JSCallReducerAssembler::ArgumentOrZero(), v8::internal::compiler::JSCallOrConstructNode::ArityForArgc(), v8::internal::compiler::GraphAssembler::Bind(), v8::internal::compiler::GraphAssembler::Branch(), v8::internal::compiler::JSGraphAssembler::broker(), v8::internal::compiler::JSOperatorBuilder::Call(), v8::internal::compiler::JSCallReducerAssembler::CheckBounds(), v8::internal::compiler::JSCallReducerAssembler::CheckSmi(), v8::internal::compiler::JSGraphAssembler::Constant(), v8::internal::compiler::JSCallReducerAssembler::ContextInput(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::JSCallReducerAssembler::ConvertHoleToUndefined(), v8::internal::DCHECK(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::CallParameters::feedback(), v8::internal::compiler::JSCallOrConstructNode::feedback_vector(), v8::internal::compiler::AccessBuilder::ForFixedArrayElement(), v8::internal::compiler::AccessBuilder::ForMap(), v8::internal::compiler::JSNodeWrapperBase::frame_state(), v8::internal::compiler::CallParameters::frequency(), v8::internal::compiler::GraphAssembler::Goto(), v8::internal::compiler::GraphAssembler::GotoIf(), v8::internal::compiler::GraphAssembler::GotoIfNot(), v8::internal::compiler::GraphAssembler::graph(), v8::internal::index, v8::internal::compiler::Node::InputAt(), v8::internal::IsHoleyElementsKind(), v8::internal::compiler::JSGraphAssembler::javascript(), v8::internal::compiler::kAbortOnOutOfBounds, v8::internal::kDisallowSpeculation, v8::internal::kNotNullOrUndefined, v8::internal::kTagged, v8::internal::compiler::kTarget, v8::internal::length, LoadElements(), v8::internal::compiler::JSGraphAssembler::LoadField(), LoadJSArrayLength(), v8::internal::compiler::GraphAssembler::MakeLabel(), v8::internal::compiler::JSGraphAssembler::MayThrow(), v8::internal::compiler::JSCallReducerAssembler::node_ptr(), v8::internal::compiler::JSGraphAssembler::NumberAdd(), v8::internal::compiler::JSGraphAssembler::NumberLessThan(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::compiler::JSGraphAssembler::ReferenceEqual(), v8::internal::TNode< T >::UncheckedCast(), v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant(), and v8::internal::v8_flags.
Referenced by v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeAt().
ReduceArrayPrototypeEverySome()
TNode< Boolean > v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeEverySome (MapInference * inference, const bool has_stability_dependency, ElementsKind kind, SharedFunctionInfoRef shared, NativeContextRef native_context, ArrayEverySomeVariant variant)
Definition at line 2282 of file js-call-reducer.cc.
                                                                    {
  FrameState outer_frame_state = FrameStateInput();
  TNode<Context> context = ContextInput();
  TNode<Object> target = TargetInput();
  TNode<JSArray> receiver = ReceiverInputAs<JSArray>();
  TNode<Object> fncallback = ArgumentOrUndefined(0);
  TNode<Object> this_arg = ArgumentOrUndefined(1);
  TNode<Number> original_length = LoadJSArrayLength(receiver, kind);
  EverySomeFrameStateParams frame_state_params{
      jsgraph(), shared, context, target, outer_frame_state,
      receiver, fncallback, this_arg, original_length};
  ThrowIfNotCallable(
      fncallback,
      EverySomeLoopLazyFrameState(frame_state_params, ZeroConstant(), variant));
  auto out = MakeLabel(MachineRepresentation::kTagged);
  ForZeroUntil(original_length).Do([&](TNode<Number> k) {
    Checkpoint(EverySomeLoopEagerFrameState(frame_state_params, k, variant));
    MaybeInsertMapChecks(inference, has_stability_dependency);
    TNode<Object> element;
    std::tie(k, element) = SafeLoadElement(kind, receiver, k);
    auto continue_label = MakeLabel();
    element = MaybeSkipHole(element, kind, &continue_label);
    TNode<Object> v =
        JSCall3(fncallback, this_arg, element, k, receiver,
                EverySomeLoopLazyFrameState(frame_state_params, k, variant));
    if (variant == ArrayEverySomeVariant::kEvery) {
      GotoIfNot(ToBoolean(v), &out, FalseConstant());
    } else {
      DCHECK_EQ(variant, ArrayEverySomeVariant::kSome);
      GotoIf(ToBoolean(v), &out, TrueConstant());
    }
    Goto(&continue_label);
    Bind(&continue_label);
  });
  Goto(&out, (variant == ArrayEverySomeVariant::kEvery) ? TrueConstant()
                                                        : FalseConstant());
  Bind(&out);
  return out.PhiAt<Boolean>(0);
}
References v8::internal::compiler::JSCallReducerAssembler::ArgumentOrUndefined(), v8::internal::compiler::GraphAssembler::Bind(), v8::internal::compiler::GraphAssembler::Checkpoint(), v8::internal::compiler::JSCallReducerAssembler::ContextInput(), DCHECK_EQ, v8::internal::compiler::JSCallReducerAssembler::ForBuilder0::Do(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::EverySomeLoopEagerFrameState(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::EverySomeLoopLazyFrameState(), v8::internal::compiler::JSCallReducerAssembler::ForZeroUntil(), v8::internal::compiler::JSCallReducerAssembler::FrameStateInput(), v8::internal::compiler::GraphAssembler::Goto(), v8::internal::compiler::GraphAssembler::GotoIf(), v8::internal::compiler::GraphAssembler::GotoIfNot(), v8::internal::compiler::JSCallReducerAssembler::JSCall3(), v8::internal::compiler::JSGraphAssembler::jsgraph(), v8::internal::compiler::kEvery, v8::internal::compiler::kSome, v8::internal::kTagged, LoadJSArrayLength(), v8::internal::compiler::GraphAssembler::MakeLabel(), v8::internal::compiler::JSCallReducerAssembler::MaybeInsertMapChecks(), MaybeSkipHole(), SafeLoadElement(), v8::internal::compiler::JSCallReducerAssembler::TargetInput(), v8::internal::compiler::JSCallReducerAssembler::ThrowIfNotCallable(), and v8::internal::compiler::JSGraphAssembler::ToBoolean().
Referenced by v8::internal::compiler::JSCallReducer::ReduceArrayEvery(), and v8::internal::compiler::JSCallReducer::ReduceArraySome().
ReduceArrayPrototypeFilter()
TNode< JSArray > v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFilter (MapInference * inference, const bool has_stability_dependency, ElementsKind kind, SharedFunctionInfoRef shared, NativeContextRef native_context)
Definition at line 2034 of file js-call-reducer.cc.
                                     {
  FrameState outer_frame_state = FrameStateInput();
  TNode<Context> context = ContextInput();
  TNode<Object> target = TargetInput();
  TNode<JSArray> receiver = ReceiverInputAs<JSArray>();
  TNode<Object> fncallback = ArgumentOrUndefined(0);
  TNode<Object> this_arg = ArgumentOrUndefined(1);
  // The output array is packed (filter doesn't visit holes).
  ElementsKind filtered_kind = GetPackedElementsKind(kind);
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
  if (kind == ElementsKind::HOLEY_DOUBLE_ELEMENTS) {
    // Array may contain double-encoded undefineds that may be preserved by
    // the filter operation, so the output has to be holey, too.
    // TODO(nicohartmann, 385155404): We can consider starting with a
    // PACKED_DOUBLE_ELEMENTS and only transition to holey, when we actually
    // encounter an undefined.
    filtered_kind = ElementsKind::HOLEY_DOUBLE_ELEMENTS;
  }
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
  TNode<JSArray> a = AllocateEmptyJSArray(filtered_kind, native_context);
  TNode<Number> original_length = LoadJSArrayLength(receiver, kind);
  FilterFrameStateParams frame_state_params{
      jsgraph(), shared, context, target, outer_frame_state,
      receiver, fncallback, this_arg, a, original_length};
  // This frame state doesn't ever call the deopt continuation, it's only
  // necessary to specify a continuation in order to handle the exceptional
  // case. We don't have all the values available to completely fill out
  // the checkpoint parameters yet, but that's okay because it'll never be
  // called.
  TNode<Number> zero = ZeroConstant();
  ThrowIfNotCallable(fncallback, FilterLoopLazyFrameState(frame_state_params,
                                                          zero, zero, zero));
  TNode<Number> initial_a_length = zero;
  For1ZeroUntil(original_length, initial_a_length)
      .Do([&](TNode<Number> k, TNode<Object>* a_length_object) {
        TNode<Number> a_length = TNode<Number>::UncheckedCast(*a_length_object);
        Checkpoint(FilterLoopEagerFrameState(frame_state_params, k, a_length));
        MaybeInsertMapChecks(inference, has_stability_dependency);
        TNode<Object> element;
        std::tie(k, element) = SafeLoadElement(kind, receiver, k);
        auto continue_label = MakeLabel(MachineRepresentation::kTaggedSigned);
        element = MaybeSkipHole(element, kind, &continue_label, a_length);
        TNode<Object> v = JSCall3(
            fncallback, this_arg, element, k, receiver,
            FilterLoopLazyFrameState(frame_state_params, k, a_length, element));
        // We need an eager frame state for right after the callback function
        // returned, just in case an attempt to grow the output array fails.
        Checkpoint(FilterLoopEagerPostCallbackFrameState(frame_state_params, k,
                                                         a_length, element, v));
        GotoIfNot(ToBoolean(v), &continue_label, a_length);
        // Since the callback returned a trueish value, store the element in a.
        {
          TNode<Number> a_length1 = TypeGuardFixedArrayLength(a_length);
          TNode<FixedArrayBase> elements = LoadElements(a);
          elements = MaybeGrowFastElements(kind, FeedbackSource{}, a, elements,
                                           a_length1,
                                           LoadFixedArrayBaseLength(elements));
          TNode<Number> new_a_length = NumberInc(a_length1);
          StoreJSArrayLength(a, new_a_length, kind);
          StoreFixedArrayBaseElement(elements, a_length1, element, kind);
          Goto(&continue_label, new_a_length);
        }
        Bind(&continue_label);
        *a_length_object =
            TNode<Object>::UncheckedCast(continue_label.PhiAt(0));
      })
      .ValueIsUnused();
  return a;
}
References v8::internal::compiler::JSCallReducerAssembler::AllocateEmptyJSArray(), v8::internal::compiler::JSCallReducerAssembler::ArgumentOrUndefined(), v8::internal::compiler::GraphAssembler::Bind(), v8::internal::compiler::GraphAssembler::Checkpoint(), v8::internal::compiler::JSCallReducerAssembler::ContextInput(), v8::internal::compiler::JSCallReducerAssembler::ForBuilder1::Do(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FilterLoopEagerFrameState(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FilterLoopEagerPostCallbackFrameState(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FilterLoopLazyFrameState(), v8::internal::compiler::JSCallReducerAssembler::For1ZeroUntil(), v8::internal::compiler::JSCallReducerAssembler::FrameStateInput(), v8::internal::GetPackedElementsKind(), v8::internal::compiler::GraphAssembler::Goto(), v8::internal::compiler::GraphAssembler::GotoIfNot(), v8::internal::HOLEY_DOUBLE_ELEMENTS, v8::internal::compiler::JSCallReducerAssembler::JSCall3(), v8::internal::compiler::JSGraphAssembler::jsgraph(), v8::internal::kTaggedSigned, LoadElements(), LoadFixedArrayBaseLength(), LoadJSArrayLength(), v8::internal::compiler::GraphAssembler::MakeLabel(), v8::internal::compiler::JSGraphAssembler::MaybeGrowFastElements(), v8::internal::compiler::JSCallReducerAssembler::MaybeInsertMapChecks(), MaybeSkipHole(), v8::internal::native_context, v8::internal::compiler::JSCallReducerAssembler::NumberInc(), SafeLoadElement(), StoreFixedArrayBaseElement(), StoreJSArrayLength(), v8::internal::compiler::JSCallReducerAssembler::TargetInput(), v8::internal::compiler::JSCallReducerAssembler::ThrowIfNotCallable(), v8::internal::compiler::JSGraphAssembler::ToBoolean(), v8::internal::compiler::JSCallReducerAssembler::TypeGuardFixedArrayLength(), v8::internal::TNode< T >::UncheckedCast(), and v8::internal::zero.
Referenced by v8::internal::compiler::JSCallReducer::ReduceArrayFilter().
ReduceArrayPrototypeFind()
TNode< Object > v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFind (MapInference * inference, const bool has_stability_dependency, ElementsKind kind, SharedFunctionInfoRef shared, NativeContextRef native_context, ArrayFindVariant variant)
Definition at line 2180 of file js-call-reducer.cc.
                                                               {
  FrameState outer_frame_state = FrameStateInput();
  TNode<Context> context = ContextInput();
  TNode<Object> target = TargetInput();
  TNode<JSArray> receiver = ReceiverInputAs<JSArray>();
  TNode<Object> fncallback = ArgumentOrUndefined(0);
  TNode<Object> this_arg = ArgumentOrUndefined(1);
  TNode<Number> original_length = LoadJSArrayLength(receiver, kind);
  FindFrameStateParams frame_state_params{
      jsgraph(), shared, context, target, outer_frame_state,
      receiver, fncallback, this_arg, original_length};
  ThrowIfNotCallable(
      fncallback,
      FindLoopLazyFrameState(frame_state_params, ZeroConstant(), variant));
  const bool is_find_variant = (variant == ArrayFindVariant::kFind);
  auto out = MakeLabel(MachineRepresentation::kTagged);
  ForZeroUntil(original_length).Do([&](TNode<Number> k) {
    Checkpoint(FindLoopEagerFrameState(frame_state_params, k, variant));
    MaybeInsertMapChecks(inference, has_stability_dependency);
    TNode<Object> element;
    std::tie(k, element) = SafeLoadElement(kind, receiver, k);
    if (IsHoleyElementsKind(kind)) {
      element = ConvertHoleToUndefined(element, kind);
    }
    TNode<Object> if_found_value = is_find_variant ? element : k;
    TNode<Number> next_k = NumberInc(k);
    // The callback result states whether the desired element was found.
    TNode<Object> v =
        JSCall3(fncallback, this_arg, element, k, receiver,
                FindLoopAfterCallbackLazyFrameState(frame_state_params, next_k,
                                                    if_found_value, variant));
    GotoIf(ToBoolean(v), &out, if_found_value);
  });
  // If the loop completed, the element was not found.
  TNode<Object> if_not_found_value =
      is_find_variant ? TNode<Object>::UncheckedCast(UndefinedConstant())
                      : TNode<Object>::UncheckedCast(MinusOneConstant());
  Goto(&out, if_not_found_value);
  Bind(&out);
  return out.PhiAt<Object>(0);
}
References v8::internal::compiler::JSCallReducerAssembler::ArgumentOrUndefined(), v8::internal::compiler::GraphAssembler::Bind(), v8::internal::compiler::GraphAssembler::Checkpoint(), v8::internal::compiler::JSCallReducerAssembler::ContextInput(), v8::internal::compiler::JSCallReducerAssembler::ConvertHoleToUndefined(), v8::internal::compiler::JSCallReducerAssembler::ForBuilder0::Do(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FindLoopAfterCallbackLazyFrameState(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FindLoopEagerFrameState(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::FindLoopLazyFrameState(), v8::internal::compiler::JSCallReducerAssembler::ForZeroUntil(), v8::internal::compiler::JSCallReducerAssembler::FrameStateInput(), v8::internal::compiler::GraphAssembler::Goto(), v8::internal::compiler::GraphAssembler::GotoIf(), v8::internal::IsHoleyElementsKind(), v8::internal::compiler::JSCallReducerAssembler::JSCall3(), v8::internal::compiler::JSGraphAssembler::jsgraph(), v8::internal::compiler::kFind, v8::internal::kTagged, LoadJSArrayLength(), v8::internal::compiler::GraphAssembler::MakeLabel(), v8::internal::compiler::JSCallReducerAssembler::MaybeInsertMapChecks(), v8::internal::compiler::JSCallReducerAssembler::NumberInc(), SafeLoadElement(), v8::internal::compiler::JSCallReducerAssembler::TargetInput(), v8::internal::compiler::JSCallReducerAssembler::ThrowIfNotCallable(), v8::internal::compiler::JSGraphAssembler::ToBoolean(), v8::internal::TNode< T >::UncheckedCast(), and v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
Referenced by v8::internal::compiler::JSCallReducer::ReduceArrayFind(), and v8::internal::compiler::JSCallReducer::ReduceArrayFindIndex().
ReduceArrayPrototypeForEach()
TNode< Object > v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeForEach (MapInference * inference, const bool has_stability_dependency, ElementsKind kind, SharedFunctionInfoRef shared)
Definition at line 1623 of file js-call-reducer.cc.
                                                     {
  FrameState outer_frame_state = FrameStateInput();
  TNode<Context> context = ContextInput();
  TNode<Object> target = TargetInput();
  TNode<JSArray> receiver = ReceiverInputAs<JSArray>();
  TNode<Object> fncallback = ArgumentOrUndefined(0);
  TNode<Object> this_arg = ArgumentOrUndefined(1);
  TNode<Number> original_length = LoadJSArrayLength(receiver, kind);
  ForEachFrameStateParams frame_state_params{
      jsgraph(), shared, context, target, outer_frame_state,
      receiver, fncallback, this_arg, original_length};
  ThrowIfNotCallable(fncallback, ForEachLoopLazyFrameState(frame_state_params,
                                                           ZeroConstant()));
  ForZeroUntil(original_length).Do([&](TNode<Number> k) {
    Checkpoint(ForEachLoopEagerFrameState(frame_state_params, k));
    // Deopt if the map has changed during the iteration.
    MaybeInsertMapChecks(inference, has_stability_dependency);
    TNode<Object> element;
    std::tie(k, element) = SafeLoadElement(kind, receiver, k);
    auto continue_label = MakeLabel();
    element = MaybeSkipHole(element, kind, &continue_label);
    TNode<Number> next_k = NumberAdd(k, OneConstant());
    JSCall3(fncallback, this_arg, element, k, receiver,
            ForEachLoopLazyFrameState(frame_state_params, next_k));
    Goto(&continue_label);
    Bind(&continue_label);
  });
  return UndefinedConstant();
}
References v8::internal::compiler::JSCallReducerAssembler::ArgumentOrUndefined(), v8::internal::compiler::GraphAssembler::Bind(), v8::internal::compiler::GraphAssembler::Checkpoint(), v8::internal::compiler::JSCallReducerAssembler::ContextInput(), v8::internal::compiler::JSCallReducerAssembler::ForBuilder0::Do(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ForEachLoopEagerFrameState(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ForEachLoopLazyFrameState(), v8::internal::compiler::JSCallReducerAssembler::ForZeroUntil(), v8::internal::compiler::JSCallReducerAssembler::FrameStateInput(), v8::internal::compiler::GraphAssembler::Goto(), v8::internal::compiler::JSCallReducerAssembler::JSCall3(), v8::internal::compiler::JSGraphAssembler::jsgraph(), LoadJSArrayLength(), v8::internal::compiler::GraphAssembler::MakeLabel(), v8::internal::compiler::JSCallReducerAssembler::MaybeInsertMapChecks(), MaybeSkipHole(), v8::internal::compiler::JSGraphAssembler::NumberAdd(), SafeLoadElement(), v8::internal::compiler::JSCallReducerAssembler::TargetInput(), v8::internal::compiler::JSCallReducerAssembler::ThrowIfNotCallable(), and v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
Referenced by v8::internal::compiler::JSCallReducer::ReduceArrayForEach().
ReduceArrayPrototypeIndexOfIncludes()
TNode< Object > v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeIndexOfIncludes (ElementsKind kind, ArrayIndexOfIncludesVariant variant)
Definition at line 2382 of file js-call-reducer.cc.
                                                            {
  TNode<Context> context = ContextInput();
  TNode<JSArray> receiver = ReceiverInputAs<JSArray>();
  TNode<Object> search_element = ArgumentOrUndefined(0);
  TNode<Object> from_index = ArgumentOrZero(1);
  // TODO(jgruber): This currently only reduces to a stub call. Create a full
  // reduction (similar to other higher-order array builtins) instead of
  // lowering to a builtin call. E.g. Array.p.every and Array.p.some have almost
  // identical functionality.
  TNode<Number> length = LoadJSArrayLength(receiver, kind);
  TNode<FixedArrayBase> elements = LoadElements(receiver);
  const bool have_from_index = ArgumentCount() > 1;
  if (have_from_index) {
    TNode<Smi> from_index_smi = CheckSmi(from_index);
    // If the index is negative, it means the offset from the end and
    // therefore needs to be added to the length. If the result is still
    // negative, it needs to be clamped to 0.
    TNode<Boolean> cond = NumberLessThan(from_index_smi, ZeroConstant());
    from_index = SelectIf<Number>(cond)
                     .Then(_ {
                       return NumberMax(NumberAdd(length, from_index_smi),
                                        ZeroConstant());
                     })
                     .Else(_ { return from_index_smi; })
                     .ExpectFalse()
                     .Value();
  }
  return Call4(GetCallableForArrayIndexOfIncludes(variant, kind, isolate()),
               context, elements, search_element, length, from_index);
}
References _, v8::internal::compiler::JSCallReducerAssembler::ArgumentCount(), v8::internal::compiler::JSCallReducerAssembler::ArgumentOrUndefined(), v8::internal::compiler::JSCallReducerAssembler::ArgumentOrZero(), v8::internal::compiler::JSCallReducerAssembler::Call4(), v8::internal::compiler::JSCallReducerAssembler::CheckSmi(), v8::internal::compiler::JSCallReducerAssembler::ContextInput(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::GetCallableForArrayIndexOfIncludes(), v8::internal::compiler::JSGraphAssembler::isolate(), v8::internal::length, LoadElements(), LoadJSArrayLength(), v8::internal::compiler::JSGraphAssembler::NumberAdd(), v8::internal::compiler::JSGraphAssembler::NumberLessThan(), and v8::internal::compiler::JSGraphAssembler::NumberMax().
Referenced by v8::internal::compiler::JSCallReducer::ReduceArrayIncludes(), and v8::internal::compiler::JSCallReducer::ReduceArrayIndexOf().
ReduceArrayPrototypeMap()
TNode< JSArray > v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeMap (MapInference * inference, const bool has_stability_dependency, ElementsKind kind, SharedFunctionInfoRef shared, NativeContextRef native_context)
Definition at line 1892 of file js-call-reducer.cc.
                                     {
  FrameState outer_frame_state = FrameStateInput();
  TNode<Context> context = ContextInput();
  TNode<Object> target = TargetInput();
  TNode<JSArray> receiver = ReceiverInputAs<JSArray>();
  TNode<Object> fncallback = ArgumentOrUndefined(0);
  TNode<Object> this_arg = ArgumentOrUndefined(1);
  TNode<Number> original_length = LoadJSArrayLength(receiver, kind);
  // If the array length >= kMaxFastArrayLength, then CreateArray
  // will create a dictionary. We should deopt in this case, and make sure
  // not to attempt inlining again.
  original_length = CheckBounds(original_length,
                                NumberConstant(JSArray::kMaxFastArrayLength));
  // Even though {JSCreateArray} is not marked as {kNoThrow}, we can elide the
  // exceptional projections because it cannot throw with the given
  // parameters.
  TNode<Object> array_ctor =
      Constant(native_context.GetInitialJSArrayMap(broker(), kind)
                   .GetConstructor(broker()));
  MapFrameStateParams frame_state_params{
      jsgraph(), shared, context, target, outer_frame_state,
      receiver, fncallback, this_arg, {} /* TBD */, original_length};
  TNode<JSArray> a =
      CreateArrayNoThrow(array_ctor, original_length,
                         MapPreLoopLazyFrameState(frame_state_params));
  frame_state_params.a = a;
  ThrowIfNotCallable(fncallback,
                     MapLoopLazyFrameState(frame_state_params, ZeroConstant()));
  ForZeroUntil(original_length).Do([&](TNode<Number> k) {
    Checkpoint(MapLoopEagerFrameState(frame_state_params, k));
    MaybeInsertMapChecks(inference, has_stability_dependency);
    TNode<Object> element;
    std::tie(k, element) = SafeLoadElement(kind, receiver, k);
    auto continue_label = MakeLabel();
    element = MaybeSkipHole(element, kind, &continue_label);
    TNode<Object> v = JSCall3(fncallback, this_arg, element, k, receiver,
                              MapLoopLazyFrameState(frame_state_params, k));
    // The array {a} should be HOLEY_SMI_ELEMENTS because we'd only come into
    // this loop if the input array length is non-zero, and "new Array({x > 0})"
    // always produces a HOLEY array.
    MapRef holey_double_map =
        native_context.GetInitialJSArrayMap(broker(), HOLEY_DOUBLE_ELEMENTS);
    MapRef holey_map =
        native_context.GetInitialJSArrayMap(broker(), HOLEY_ELEMENTS);
    TransitionAndStoreElement(holey_double_map, holey_map, a, k, v);
    Goto(&continue_label);
    Bind(&continue_label);
  });
  return a;
}
References v8::internal::compiler::JSCallReducerAssembler::ArgumentOrUndefined(), v8::internal::compiler::GraphAssembler::Bind(), v8::internal::compiler::JSGraphAssembler::broker(), v8::internal::compiler::JSCallReducerAssembler::CheckBounds(), v8::internal::compiler::GraphAssembler::Checkpoint(), v8::internal::compiler::JSGraphAssembler::Constant(), v8::internal::compiler::JSCallReducerAssembler::ContextInput(), v8::internal::compiler::JSCallReducerAssembler::CreateArrayNoThrow(), v8::internal::compiler::JSCallReducerAssembler::ForBuilder0::Do(), v8::internal::compiler::JSCallReducerAssembler::ForZeroUntil(), v8::internal::compiler::JSCallReducerAssembler::FrameStateInput(), v8::internal::compiler::GraphAssembler::Goto(), v8::internal::HOLEY_DOUBLE_ELEMENTS, v8::internal::HOLEY_ELEMENTS, v8::internal::compiler::JSCallReducerAssembler::JSCall3(), v8::internal::compiler::JSGraphAssembler::jsgraph(), v8::internal::JSArray::kMaxFastArrayLength, LoadJSArrayLength(), v8::internal::compiler::GraphAssembler::MakeLabel(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::MapLoopEagerFrameState(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::MapLoopLazyFrameState(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::MapPreLoopLazyFrameState(), v8::internal::compiler::JSCallReducerAssembler::MaybeInsertMapChecks(), MaybeSkipHole(), v8::internal::native_context, v8::internal::compiler::JSGraphAssembler::NumberConstant(), SafeLoadElement(), v8::internal::compiler::JSCallReducerAssembler::TargetInput(), v8::internal::compiler::JSCallReducerAssembler::ThrowIfNotCallable(), and v8::internal::compiler::JSGraphAssembler::TransitionAndStoreElement().
Referenced by v8::internal::compiler::JSCallReducer::ReduceArrayMap().
ReduceArrayPrototypePush()
TNode< Number > v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypePush (MapInference * inference)
Definition at line 1461 of file js-call-reducer.cc.
                             {
  int const num_push_arguments = ArgumentCount();
  ZoneRefSet<Map> const& receiver_maps = inference->GetMaps();
  base::SmallVector<MachineRepresentation, 4> argument_reps;
  base::SmallVector<Node*, 4> argument_nodes;
  for (int i = 0; i < num_push_arguments; ++i) {
    argument_reps.push_back(MachineRepresentation::kTagged);
    argument_nodes.push_back(Argument(i));
  }
  TNode<JSArray> receiver = ReceiverInputAs<JSArray>();
  TNode<Map> receiver_map = LoadMap(receiver);
  auto double_label = MakeLabel(argument_reps);
  auto smi_label = MakeLabel(argument_reps);
  auto object_label = MakeLabel(argument_reps);
  for (size_t i = 0; i < receiver_maps.size(); i++) {
    MapRef map = receiver_maps[i];
    ElementsKind kind = map.elements_kind();
    if (i < receiver_maps.size() - 1) {
      TNode<Boolean> is_map_equal = ReferenceEqual(receiver_map, Constant(map));
      if (IsDoubleElementsKind(kind)) {
        GotoIf(is_map_equal, &double_label, argument_nodes);
      } else if (IsSmiElementsKind(kind)) {
        GotoIf(is_map_equal, &smi_label, argument_nodes);
      } else {
        GotoIf(is_map_equal, &object_label, argument_nodes);
      }
    } else {
      if (IsDoubleElementsKind(kind)) {
        Goto(&double_label, argument_nodes);
      } else if (IsSmiElementsKind(kind)) {
        Goto(&smi_label, argument_nodes);
      } else {
        Goto(&object_label, argument_nodes);
      }
    }
  }
  auto return_label = MakeLabel(MachineRepresentation::kTagged);
  auto build_array_push = [&](ElementsKind kind,
                              base::SmallVector<Node*, 1>& push_arguments) {
    // Only support PACKED_ELEMENTS and PACKED_DOUBLE_ELEMENTS, as "markers" of
    // what the elements array is (a FixedArray or FixedDoubleArray).
    DCHECK(kind == PACKED_ELEMENTS || kind == PACKED_DOUBLE_ELEMENTS);
    // Load the "length" property of the {receiver}.
    TNode<Smi> length = LoadJSArrayLength(receiver, kind);
    TNode<Number> return_value = length;
    // Check if we have any {values} to push.
    if (num_push_arguments > 0) {
      // Compute the resulting "length" of the {receiver}.
      TNode<Number> new_length = return_value =
          NumberAdd(length, NumberConstant(num_push_arguments));
      // Load the elements backing store of the {receiver}.
      TNode<FixedArrayBase> elements = LoadElements(receiver);
      TNode<Smi> elements_length = LoadFixedArrayBaseLength(elements);
      elements = MaybeGrowFastElements(
          kind, feedback(), receiver, elements,
          NumberAdd(length, NumberConstant(num_push_arguments - 1)),
          elements_length);
      // Update the JSArray::length field. Since this is observable,
      // there must be no other check after this.
      StoreJSArrayLength(receiver, new_length, kind);
      // Append the {values} to the {elements}.
      for (int i = 0; i < num_push_arguments; ++i) {
        StoreFixedArrayBaseElement(
            elements, NumberAdd(length, NumberConstant(i)),
            TNode<Object>::UncheckedCast(push_arguments[i]), kind);
      }
    }
    Goto(&return_label, return_value);
  };
  if (double_label.IsUsed()) {
    Bind(&double_label);
    base::SmallVector<Node*, 1> push_arguments(num_push_arguments);
    for (int i = 0; i < num_push_arguments; ++i) {
      Node* value =
          CheckNumber(TNode<Object>::UncheckedCast(double_label.PhiAt(i)));
      // Make sure we do not store signaling NaNs into double arrays.
      value = AddNode<Number>(
          graph()->NewNode(simplified()->NumberSilenceNaN(), value));
      push_arguments[i] = value;
    }
    build_array_push(PACKED_DOUBLE_ELEMENTS, push_arguments);
  }
  if (smi_label.IsUsed()) {
    Bind(&smi_label);
    base::SmallVector<Node*, 4> push_arguments(num_push_arguments);
    for (int i = 0; i < num_push_arguments; ++i) {
      Node* value = CheckSmi(TNode<Object>::UncheckedCast(smi_label.PhiAt(i)));
      push_arguments[i] = value;
    }
    Goto(&object_label, push_arguments);
  }
  if (object_label.IsUsed()) {
    Bind(&object_label);
    base::SmallVector<Node*, 1> push_arguments(num_push_arguments);
    for (int i = 0; i < num_push_arguments; ++i) {
      push_arguments[i] = object_label.PhiAt(i);
    }
    build_array_push(PACKED_ELEMENTS, push_arguments);
  }
  Bind(&return_label);
  return TNode<Number>::UncheckedCast(return_label.PhiAt(0));
}
References v8::internal::compiler::JSCallReducerAssembler::Argument(), v8::internal::compiler::JSCallReducerAssembler::ArgumentCount(), v8::internal::compiler::GraphAssembler::Bind(), v8::internal::compiler::JSCallReducerAssembler::CheckNumber(), v8::internal::compiler::JSCallReducerAssembler::CheckSmi(), v8::internal::compiler::JSGraphAssembler::Constant(), v8::internal::DCHECK(), v8::internal::compiler::MapRef::elements_kind(), v8::internal::compiler::JSCallReducerAssembler::feedback(), v8::internal::compiler::MapInference::GetMaps(), v8::internal::compiler::GraphAssembler::Goto(), v8::internal::compiler::GraphAssembler::GotoIf(), v8::internal::compiler::GraphAssembler::graph(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::IsDoubleElementsKind(), v8::internal::IsSmiElementsKind(), v8::internal::kTagged, v8::internal::length, LoadElements(), LoadFixedArrayBaseLength(), LoadJSArrayLength(), v8::internal::compiler::JSGraphAssembler::LoadMap(), v8::internal::compiler::GraphAssembler::MakeLabel(), v8::internal::compiler::JSGraphAssembler::MaybeGrowFastElements(), v8::internal::compiler::JSGraphAssembler::NumberAdd(), v8::internal::compiler::JSGraphAssembler::NumberConstant(), v8::internal::PACKED_DOUBLE_ELEMENTS, v8::internal::PACKED_ELEMENTS, v8::base::SmallVector< T, kSize, Allocator >::push_back(), v8::internal::compiler::JSGraphAssembler::ReferenceEqual(), v8::internal::compiler::JSGraphAssembler::simplified(), v8::internal::ZoneCompactSet< T >::size(), StoreFixedArrayBaseElement(), StoreJSArrayLength(), v8::internal::TNode< T >::UncheckedCast(), and v8::internal::value.
Referenced by v8::internal::compiler::JSCallReducer::ReduceArrayPrototypePush().
ReduceArrayPrototypeReduce()
TNode< Object > v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeReduce (MapInference * inference, const bool has_stability_dependency, ElementsKind kind, ArrayReduceDirection direction, SharedFunctionInfoRef shared)
Definition at line 1737 of file js-call-reducer.cc.
                                  {
  FrameState outer_frame_state = FrameStateInput();
  TNode<Context> context = ContextInput();
  TNode<Object> target = TargetInput();
  TNode<JSArray> receiver = ReceiverInputAs<JSArray>();
  TNode<Object> fncallback = ArgumentOrUndefined(0);
  ReduceFrameStateParams frame_state_params{
      jsgraph(), shared, direction, context, target, outer_frame_state};
  TNode<Number> original_length = LoadJSArrayLength(receiver, kind);
  // Set up variable behavior depending on the reduction kind (left/right).
  TNode<Number> k;
  StepFunction1 step;
  ConditionFunction1 cond;
  TNode<Number> zero = ZeroConstant();
  TNode<Number> one = OneConstant();
  if (direction == ArrayReduceDirection::kLeft) {
    k = zero;
    step = [&](TNode<Number> i) { return NumberAdd(i, one); };
    cond = [&](TNode<Number> i) { return NumberLessThan(i, original_length); };
  } else {
    k = NumberSubtract(original_length, one);
    step = [&](TNode<Number> i) { return NumberSubtract(i, one); };
    cond = [&](TNode<Number> i) { return NumberLessThanOrEqual(zero, i); };
  }
  ThrowIfNotCallable(
      fncallback, ReducePreLoopLazyFrameState(frame_state_params, receiver,
                                              fncallback, k, original_length));
  // Set initial accumulator value.
  TNode<Object> accumulator;
  if (ArgumentCount() > 1) {
    accumulator = Argument(1); // Initial value specified by the user.
  } else {
    // The initial value was not specified by the user. In this case, the first
    // (or last in the case of reduceRight) non-holey value of the array is
    // used. Loop until we find it. If not found, trigger a deopt.
    // TODO(jgruber): The deopt does not seem necessary. Instead we could simply
    // throw the TypeError here from optimized code.
    auto found_initial_element = MakeLabel(MachineRepresentation::kTagged,
                                           MachineRepresentation::kTagged);
    Forever(k, step).Do([&](TNode<Number> k) {
      Checkpoint(ReducePreLoopEagerFrameState(frame_state_params, receiver,
                                              fncallback, original_length));
      CheckIf(cond(k), DeoptimizeReason::kNoInitialElement);
      TNode<Object> element;
      std::tie(k, element) = SafeLoadElement(kind, receiver, k);
      auto continue_label = MakeLabel();
      GotoIf(HoleCheck(kind, element), &continue_label);
      Goto(&found_initial_element, k, TypeGuardNonInternal(element));
      Bind(&continue_label);
    });
    Unreachable(); // The loop is exited either by deopt or a jump to below.
    // TODO(jgruber): This manual fiddling with blocks could be avoided by
    // implementing a `break` mechanic for loop builders.
    Bind(&found_initial_element);
    k = step(found_initial_element.PhiAt<Number>(0));
    accumulator = found_initial_element.PhiAt<Object>(1);
  }
  TNode<Object> result =
      For1(k, cond, step, accumulator)
          .Do([&](TNode<Number> k, TNode<Object>* accumulator) {
            Checkpoint(ReduceLoopEagerFrameState(frame_state_params, receiver,
                                                 fncallback, k, original_length,
                                                 *accumulator));
            // Deopt if the map has changed during the iteration.
            MaybeInsertMapChecks(inference, has_stability_dependency);
            TNode<Object> element;
            std::tie(k, element) = SafeLoadElement(kind, receiver, k);
            auto continue_label = MakeLabel(MachineRepresentation::kTagged);
            element =
                MaybeSkipHole(element, kind, &continue_label, *accumulator);
            TNode<Number> next_k = step(k);
            TNode<Object> next_accumulator = JSCall4(
                fncallback, UndefinedConstant(), *accumulator, element, k,
                receiver,
                ReduceLoopLazyFrameState(frame_state_params, receiver,
                                         fncallback, next_k, original_length));
            Goto(&continue_label, next_accumulator);
            Bind(&continue_label);
            *accumulator = continue_label.PhiAt<Object>(0);
          })
          .Value();
  return result;
}
References v8::internal::compiler::JSCallReducerAssembler::Argument(), v8::internal::compiler::JSCallReducerAssembler::ArgumentCount(), v8::internal::compiler::JSCallReducerAssembler::ArgumentOrUndefined(), v8::internal::compiler::GraphAssembler::Bind(), v8::internal::compiler::JSGraphAssembler::CheckIf(), v8::internal::compiler::GraphAssembler::Checkpoint(), v8::internal::compiler::JSCallReducerAssembler::ContextInput(), v8::internal::compiler::JSCallReducerAssembler::ForBuilder0::Do(), v8::internal::compiler::JSCallReducerAssembler::ForBuilder1::Do(), v8::internal::compiler::JSCallReducerAssembler::For1(), v8::internal::compiler::JSCallReducerAssembler::Forever(), v8::internal::compiler::JSCallReducerAssembler::FrameStateInput(), v8::internal::compiler::GraphAssembler::Goto(), v8::internal::compiler::GraphAssembler::GotoIf(), HoleCheck(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::JSCallReducerAssembler::JSCall4(), v8::internal::compiler::JSGraphAssembler::jsgraph(), v8::internal::compiler::kLeft, v8::internal::kTagged, LoadJSArrayLength(), v8::internal::compiler::GraphAssembler::MakeLabel(), v8::internal::compiler::JSCallReducerAssembler::MaybeInsertMapChecks(), MaybeSkipHole(), v8::internal::compiler::JSGraphAssembler::NumberAdd(), v8::internal::compiler::JSGraphAssembler::NumberLessThan(), v8::internal::compiler::JSGraphAssembler::NumberLessThanOrEqual(), v8::internal::compiler::JSGraphAssembler::NumberSubtract(), one, v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ReduceLoopEagerFrameState(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ReduceLoopLazyFrameState(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ReducePreLoopEagerFrameState(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ReducePreLoopLazyFrameState(), v8::base::internal::result, SafeLoadElement(), v8::internal::compiler::JSCallReducerAssembler::TargetInput(), v8::internal::compiler::JSCallReducerAssembler::ThrowIfNotCallable(), v8::internal::compiler::JSCallReducerAssembler::TypeGuardNonInternal(), v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant(), v8::internal::compiler::GraphAssembler::Unreachable(), and v8::internal::zero.
Referenced by v8::internal::compiler::JSCallReducer::ReduceArrayReduce(), and v8::internal::compiler::JSCallReducer::ReduceArrayReduceRight().
SafeLoadElement()
std::pair<TNode<Number>, TNode<Object> > v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::SafeLoadElement (ElementsKind kind, TNode< JSArray > o, TNode< Number > index) [inline], [private]
Definition at line 486 of file js-call-reducer.cc.
                                                                               {
    // Make sure that the access is still in bounds, since the callback could
    // have changed the array's size.
    TNode<Number> length = LoadJSArrayLength(o, kind);
    index = CheckBounds(index, length);
    // Reload the elements pointer before calling the callback, since the
    // previous callback might have resized the array causing the elements
    // buffer to be re-allocated.
    TNode<HeapObject> elements =
        LoadField<HeapObject>(AccessBuilder::ForJSObjectElements(), o);
    TNode<Object> value = LoadElement<Object>(
        AccessBuilder::ForFixedArrayElement(kind), elements, index);
    return std::make_pair(index, value);
  }
References v8::internal::compiler::JSCallReducerAssembler::CheckBounds(), v8::internal::compiler::AccessBuilder::ForFixedArrayElement(), v8::internal::compiler::AccessBuilder::ForJSObjectElements(), v8::internal::index, v8::internal::length, LoadJSArrayLength(), and v8::internal::value.
Referenced by ReduceArrayPrototypeEverySome(), ReduceArrayPrototypeFilter(), ReduceArrayPrototypeFind(), ReduceArrayPrototypeForEach(), ReduceArrayPrototypeMap(), and ReduceArrayPrototypeReduce().
StoreFixedArrayBaseElement()
void v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::StoreFixedArrayBaseElement (TNode< FixedArrayBase > o, TNode< Number > index, TNode< Object > v, ElementsKind kind) [inline], [private]
Definition at line 529 of file js-call-reducer.cc.
                                                                      {
    StoreElement(AccessBuilder::ForFixedArrayElement(kind), o, index, v);
  }
References v8::internal::compiler::AccessBuilder::ForFixedArrayElement(), v8::internal::index, and v8::internal::compiler::JSGraphAssembler::StoreElement().
Referenced by ReduceArrayPrototypeFilter(), and ReduceArrayPrototypePush().
StoreJSArrayLength()
void v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::StoreJSArrayLength (TNode< JSArray > array, TNode< Number > value, ElementsKind kind) [inline], [private]
Definition at line 525 of file js-call-reducer.cc.
                                             {
    StoreField(AccessBuilder::ForJSArrayLength(kind), array, value);
  }
References v8::internal::compiler::AccessBuilder::ForJSArrayLength(), v8::internal::compiler::JSGraphAssembler::StoreField(), and v8::internal::value.
Referenced by ReduceArrayPrototypeFilter(), and ReduceArrayPrototypePush().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-call-reducer.cc