v8::base::time_internal::TimeBase< TimeClass > Class Template Reference
#include <time.h>
Public Member Functions
constexpr bool IsNull () const
constexpr bool IsMax () const
constexpr bool IsMin () const
int64_t ToInternalValue () const
constexpr TimeDelta since_origin () const
TimeClass & operator= (TimeClass other)
TimeDelta operator- (TimeClass other) const
TimeClass operator+ (TimeDelta delta) const
TimeClass operator- (TimeDelta delta) const
TimeClass & operator+= (TimeDelta delta)
TimeClass & operator-= (TimeDelta delta)
constexpr auto operator<=> (const TimeBase &) const =default
Static Public Member Functions
static TimeClass Max ()
static TimeClass Min ()
static TimeClass FromInternalValue (int64_t us)
Protected Member Functions
constexpr TimeBase (int64_t us)
Protected Attributes
int64_t us_
Additional Inherited Members
Detailed Description
template<class TimeClass>
class v8::base::time_internal::TimeBase< TimeClass >
Definition at line 236 of file time.h.
Constructor & Destructor Documentation
TimeBase()
template<class TimeClass >
constexpr v8::base::time_internal::TimeBase< TimeClass >::TimeBase (int64_t us) [inline], [explicit], [constexpr], [protected]
Definition at line 319 of file time.h.
: us_(us) {}
Member Function Documentation
FromInternalValue()
template<class TimeClass >
static TimeClass v8::base::time_internal::TimeBase< TimeClass >::FromInternalValue (int64_t us) [inline], [static]
Definition at line 316 of file time.h.
{ return TimeClass(us); }
IsMax()
template<class TimeClass >
constexpr bool v8::base::time_internal::TimeBase< TimeClass >::IsMax () const [inline], [constexpr]
Definition at line 262 of file time.h.
                               {
    return us_ == std::numeric_limits<int64_t>::max();
  }
References v8::base::time_internal::TimeBase< TimeClass >::us_.
IsMin()
template<class TimeClass >
constexpr bool v8::base::time_internal::TimeBase< TimeClass >::IsMin () const [inline], [constexpr]
Definition at line 265 of file time.h.
                               {
    return us_ == std::numeric_limits<int64_t>::min();
  }
References v8::base::time_internal::TimeBase< TimeClass >::us_.
IsNull()
template<class TimeClass >
constexpr bool v8::base::time_internal::TimeBase< TimeClass >::IsNull () const [inline], [constexpr]
Definition at line 250 of file time.h.
{ return us_ == 0; }
References v8::base::time_internal::TimeBase< TimeClass >::us_.
Referenced by v8::internal::CpuProfile::AddPath(), v8::base::ElapsedTimer::Elapsed(), heap::base::IncrementalMarkingSchedule::GetNextIncrementalStepDuration(), heap::base::IncrementalMarkingSchedule::GetTimeSinceLastConcurrentMarkingUpdate(), v8::base::ElapsedTimer::IsStarted(), heap::base::IncrementalMarkingSchedule::NotifyConcurrentMarkingStart(), heap::base::IncrementalMarkingSchedule::NotifyIncrementalMarkingStart(), v8::base::ElapsedTimer::Now(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::OnFinishedUnits(), v8::base::ElapsedTimer::Restart(), v8::base::ElapsedTimer::Resume(), v8::internal::CpuSampler::SampleStack(), v8::base::ElapsedTimer::Start(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::TriggerCachingAfterTimeout(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::TriggerOutstandingCallbacks().
Max()
template<class TimeClass >
static TimeClass v8::base::time_internal::TimeBase< TimeClass >::Max () [inline], [static]
Definition at line 254 of file time.h.
                         {
    return TimeClass(std::numeric_limits<int64_t>::max());
  }
Min()
template<class TimeClass >
static TimeClass v8::base::time_internal::TimeBase< TimeClass >::Min () [inline], [static]
Definition at line 257 of file time.h.
                         {
    return TimeClass(std::numeric_limits<int64_t>::min());
  }
operator+()
template<class TimeClass >
TimeClass v8::base::time_internal::TimeBase< TimeClass >::operator+ (TimeDelta delta) const [inline]
Definition at line 295 of file time.h.
                                             {
    return TimeClass(bits::SignedSaturatedAdd64(delta.delta_, us_));
  }
References v8::base::TimeDelta::delta_, v8::base::bits::SignedSaturatedAdd64(), and v8::base::time_internal::TimeBase< TimeClass >::us_.
operator+=()
template<class TimeClass >
TimeClass& v8::base::time_internal::TimeBase< TimeClass >::operator+= (TimeDelta delta) [inline]
Definition at line 303 of file time.h.
                                         {
    return static_cast<TimeClass&>(*this = (*this + delta));
  }
operator-() [1/2]
template<class TimeClass >
TimeDelta v8::base::time_internal::TimeBase< TimeClass >::operator- (TimeClass other) const [inline]
Definition at line 290 of file time.h.
                                             {
    return TimeDelta::FromMicroseconds(us_ - other.us_);
  }
References v8::base::TimeDelta::FromMicroseconds(), and v8::base::time_internal::TimeBase< TimeClass >::us_.
operator-() [2/2]
template<class TimeClass >
TimeClass v8::base::time_internal::TimeBase< TimeClass >::operator- (TimeDelta delta) const [inline]
Definition at line 298 of file time.h.
                                             {
    return TimeClass(-bits::SignedSaturatedSub64(delta.delta_, us_));
  }
References v8::base::TimeDelta::delta_, v8::base::bits::SignedSaturatedSub64(), and v8::base::time_internal::TimeBase< TimeClass >::us_.
operator-=()
template<class TimeClass >
TimeClass& v8::base::time_internal::TimeBase< TimeClass >::operator-= (TimeDelta delta) [inline]
Definition at line 306 of file time.h.
                                         {
    return static_cast<TimeClass&>(*this = (*this - delta));
  }
operator<=>()
template<class TimeClass >
constexpr auto v8::base::time_internal::TimeBase< TimeClass >::operator<=> (const TimeBase< TimeClass > &) const [constexpr], [default]
operator=()
template<class TimeClass >
TimeClass& v8::base::time_internal::TimeBase< TimeClass >::operator= (TimeClass other) [inline]
Definition at line 284 of file time.h.
                                        {
    us_ = other.us_;
    return *(static_cast<TimeClass*>(this));
  }
References v8::base::time_internal::TimeBase< TimeClass >::us_.
since_origin()
template<class TimeClass >
constexpr TimeDelta v8::base::time_internal::TimeBase< TimeClass >::since_origin () const [inline], [constexpr]
Definition at line 280 of file time.h.
                                           {
    return TimeDelta::FromMicroseconds(us_);
  }
References v8::base::TimeDelta::FromMicroseconds(), and v8::base::time_internal::TimeBase< TimeClass >::us_.
Referenced by v8::internal::CpuProfile::CpuProfile(), v8::internal::CpuProfile::FinishProfile(), v8::CpuProfile::GetEndTime(), v8::CpuProfile::GetSampleTimestamp(), v8::CpuProfile::GetStartTime(), v8::internal::CpuProfileJSONSerializer::SerializeImpl(), v8::internal::CpuProfileJSONSerializer::SerializeTimeDeltas(), v8_inspector::V8ProfilerAgentImpl::startPreciseCoverage(), v8_inspector::V8ProfilerAgentImpl::takePreciseCoverage(), and v8_inspector::V8ProfilerAgentImpl::triggerPreciseCoverageDeltaUpdate().
ToInternalValue()
template<class TimeClass >
int64_t v8::base::time_internal::TimeBase< TimeClass >::ToInternalValue () const [inline]
Definition at line 272 of file time.h.
{ return us_; }
References v8::base::time_internal::TimeBase< TimeClass >::us_.
Referenced by v8::platform::tracing::TracingController::CurrentCpuTimestampMicroseconds(), v8::platform::tracing::TracingController::CurrentTimestampMicroseconds(), v8::platform::anonymous_namespace{default-platform.cc}::DefaultTimeFunction(), and v8::base::RandomNumberGenerator::RandomNumberGenerator().
Member Data Documentation
us_
template<class TimeClass >
int64_t v8::base::time_internal::TimeBase< TimeClass >::us_ [protected]
Definition at line 322 of file time.h.
Referenced by v8::base::time_internal::TimeBase< TimeClass >::IsMax(), v8::base::time_internal::TimeBase< TimeClass >::IsMin(), v8::base::time_internal::TimeBase< TimeClass >::IsNull(), v8::base::time_internal::TimeBase< TimeClass >::operator+(), v8::base::time_internal::TimeBase< TimeClass >::operator-(), v8::base::time_internal::TimeBase< TimeClass >::operator=(), v8::base::time_internal::TimeBase< TimeClass >::since_origin(), and v8::base::time_internal::TimeBase< TimeClass >::ToInternalValue().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/base/platform/time.h