v8::internal::torque::Callable Class Reference
#include <declarable.h>
Public Member Functions
const std::string & ExternalName () const
const std::string & ReadableName () const
const Signature & signature () const
bool IsTransitioning () const
const NameVector & parameter_names () const
bool HasReturnValue () const
void IncrementReturns ()
bool HasReturns () const
std::optional< Statement * > body () const
bool IsExternal () const
virtual bool ShouldBeInlined (OutputType output_type) const
bool ShouldGenerateExternalCode (OutputType output_type) const
virtual std::string CCName () const
virtual std::string CCDebugName () const
Static Public Member Functions
static std::string PrefixNameForCCOutput (const std::string &name)
static std::string PrefixNameForCCDebugOutput (const std::string &name)
Protected Member Functions
Callable (Declarable::Kind kind, std::string external_name, std::string readable_name, Signature signature, std::optional< Statement * > body)
Private Attributes
std::string external_name_
std::string readable_name_
Signature signature_
size_t returns_
std::optional< Statement * > body_
Additional Inherited Members
Detailed Description
Definition at line 301 of file declarable.h.
Constructor & Destructor Documentation
Callable()
v8::internal::torque::Callable::Callable (Declarable::Kind kind, std::string external_name, std::string readable_name, Signature signature, std::optional< Statement * > body) [inline], [protected]
Definition at line 352 of file declarable.h.
      : Scope(kind),
        external_name_(std::move(external_name)),
        readable_name_(std::move(readable_name)),
        signature_(std::move(signature)),
        returns_(0),
        body_(body) {
    DCHECK(!body || *body);
  }
References body(), and v8::internal::DCHECK().
Member Function Documentation
body()
std::optional<Statement*> v8::internal::torque::Callable::body () const [inline]
Definition at line 316 of file declarable.h.
{ return body_; }
References body_.
Referenced by Callable(), v8::internal::torque::ImplementationVisitor::InlineMacro(), and v8::internal::torque::ImplementationVisitor::Visit().
CCDebugName()
virtual std::string v8::internal::torque::Callable::CCDebugName () const [inline], [virtual]
Reimplemented in v8::internal::torque::TorqueMacro, and v8::internal::torque::ExternMacro.
Definition at line 347 of file declarable.h.
                                        {
    return PrefixNameForCCDebugOutput(ExternalName());
  }
References ExternalName(), and PrefixNameForCCDebugOutput().
Referenced by v8::internal::torque::ImplementationVisitor::GenerateMacroFunctionDeclaration(), and v8::internal::torque::ImplementationVisitor::VisitMacroCommon().
CCName()
virtual std::string v8::internal::torque::Callable::CCName () const [inline], [virtual]
Reimplemented in v8::internal::torque::TorqueMacro, and v8::internal::torque::ExternMacro.
Definition at line 342 of file declarable.h.
                                   {
    return PrefixNameForCCOutput(ExternalName());
  }
References ExternalName(), and PrefixNameForCCOutput().
Referenced by v8::internal::torque::ImplementationVisitor::GenerateMacroFunctionDeclaration(), and v8::internal::torque::ImplementationVisitor::VisitMacroCommon().
ExternalName()
const std::string& v8::internal::torque::Callable::ExternalName () const [inline]
Definition at line 304 of file declarable.h.
{ return external_name_; }
References external_name_.
Referenced by v8::internal::torque::KytheData::AddFunctionDefinition(), CCDebugName(), v8::internal::torque::ExternMacro::CCDebugName(), v8::internal::torque::TorqueMacro::CCDebugName(), CCName(), v8::internal::torque::ExternMacro::CCName(), v8::internal::torque::TorqueMacro::CCName(), v8::internal::torque::ImplementationVisitor::GenerateBuiltinDefinitionsAndInterfaceDescriptors(), v8::internal::torque::ImplementationVisitor::GenerateExportedMacrosAssembler(), v8::internal::torque::ImplementationVisitor::GenerateMacroFunctionDeclaration(), v8::internal::torque::ImplementationVisitor::GetBuiltinCode(), and v8::internal::torque::ImplementationVisitor::Visit().
HasReturns()
bool v8::internal::torque::Callable::HasReturns () const [inline]
Definition at line 315 of file declarable.h.
{ return returns_; }
References returns_.
Referenced by v8::internal::torque::ImplementationVisitor::InlineMacro().
HasReturnValue()
bool v8::internal::torque::Callable::HasReturnValue () const [inline]
Definition at line 311 of file declarable.h.
                              {
    return !signature_.return_type->IsVoidOrNever();
  }
References v8::internal::torque::Type::IsVoidOrNever(), v8::internal::torque::Signature::return_type, and signature_.
Referenced by v8::internal::torque::ImplementationVisitor::Visit().
IncrementReturns()
void v8::internal::torque::Callable::IncrementReturns () [inline]
Definition at line 314 of file declarable.h.
{ ++returns_; }
References returns_.
Referenced by v8::internal::torque::ImplementationVisitor::Visit().
IsExternal()
bool v8::internal::torque::Callable::IsExternal () const [inline]
Definition at line 317 of file declarable.h.
{ return !body_.has_value(); }
References body_.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateBuiltinDefinitionsAndInterfaceDescriptors(), v8::internal::torque::ImplementationVisitor::GenerateCall(), v8::internal::torque::ImplementationVisitor::GetBuiltinCode(), and v8::internal::torque::ImplementationVisitor::Visit().
IsTransitioning()
bool v8::internal::torque::Callable::IsTransitioning () const [inline]
Definition at line 307 of file declarable.h.
{ return signature().transitioning; }
References signature(), and v8::internal::torque::Signature::transitioning.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateCall().
parameter_names()
const NameVector& v8::internal::torque::Callable::parameter_names () const [inline]
Definition at line 308 of file declarable.h.
                                            {
    return signature_.parameter_names;
  }
References v8::internal::torque::Signature::parameter_names, and signature_.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateBuiltinDefinitionsAndInterfaceDescriptors(), v8::internal::torque::ImplementationVisitor::GenerateExportedMacrosAssembler(), v8::internal::torque::ImplementationVisitor::GenerateMacroFunctionDeclaration(), v8::internal::torque::ImplementationVisitor::InlineMacro(), and v8::internal::torque::ImplementationVisitor::VisitMacroCommon().
PrefixNameForCCDebugOutput()
static std::string v8::internal::torque::Callable::PrefixNameForCCDebugOutput (const std::string & name) [inline], [static]
Definition at line 334 of file declarable.h.
                                                                     {
    // If a Torque macro requires a C++ runtime function to be generated, then
    // the generated function begins with this prefix to avoid any naming
    // collisions with the generated CSA function for the same macro.
    return "TqDebug" + name;
  }
References v8::internal::name.
Referenced by CCDebugName(), and v8::internal::torque::TorqueMacro::CCDebugName().
PrefixNameForCCOutput()
static std::string v8::internal::torque::Callable::PrefixNameForCCOutput (const std::string & name) [inline], [static]
Definition at line 327 of file declarable.h.
                                                                {
    // If a Torque macro requires a C++ runtime function to be generated, then
    // the generated function begins with this prefix to avoid any naming
    // collisions with the generated CSA function for the same macro.
    return "TqRuntime" + name;
  }
References v8::internal::name.
Referenced by CCName(), and v8::internal::torque::TorqueMacro::CCName().
ReadableName()
const std::string& v8::internal::torque::Callable::ReadableName () const [inline]
Definition at line 305 of file declarable.h.
{ return readable_name_; }
References readable_name_.
Referenced by v8::internal::torque::TorqueMacro::CCDebugName(), v8::internal::torque::TorqueMacro::CCName(), v8::internal::torque::ImplementationVisitor::GenerateCall(), v8::internal::torque::ImplementationVisitor::GenerateExportedMacrosAssembler(), v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::HandleDocumentSymbolRequest(), v8::internal::torque::ImplementationVisitor::InlineMacro(), v8::internal::torque::operator<<(), v8::internal::torque::ReportAllUnusedMacros(), and v8::internal::torque::Macro::ShouldBeInlined().
ShouldBeInlined()
virtual bool v8::internal::torque::Callable::ShouldBeInlined (OutputType output_type) const [inline], [virtual]
Reimplemented in v8::internal::torque::Method, and v8::internal::torque::Macro.
Definition at line 318 of file declarable.h.
                                                             {
    // C++ output doesn't support exiting to labels, so functions with labels in
    // the signature must be inlined.
    return output_type == OutputType::kCC && !signature().labels.empty();
  }
References v8::internal::torque::kCC, v8::internal::torque::Signature::labels, and signature().
Referenced by v8::internal::torque::ImplementationVisitor::GenerateCall(), v8::internal::torque::Macro::ShouldBeInlined(), and ShouldGenerateExternalCode().
ShouldGenerateExternalCode()
bool v8::internal::torque::Callable::ShouldGenerateExternalCode (OutputType output_type) const [inline]
Definition at line 323 of file declarable.h.
                                                                {
    return !ShouldBeInlined(output_type);
  }
References ShouldBeInlined().
signature()
const Signature& v8::internal::torque::Callable::signature () const [inline]
Definition at line 306 of file declarable.h.
{ return signature_; }
References signature_.
Referenced by v8::internal::torque::ImplementationVisitor::AddCallParameter(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::AddParameter(), v8::internal::torque::ImplementationVisitor::GenerateBuiltinDefinitionsAndInterfaceDescriptors(), v8::internal::torque::ImplementationVisitor::GenerateCall(), v8::internal::torque::ImplementationVisitor::GenerateExportedMacrosAssembler(), v8::internal::torque::ImplementationVisitor::GenerateMacroFunctionDeclaration(), v8::internal::torque::ImplementationVisitor::GetBuiltinCode(), v8::internal::torque::CallCsaMacroAndBranchInstruction::GetLabelValueDefinitionCount(), v8::internal::torque::CallIntrinsicInstruction::GetValueDefinitionCount(), v8::internal::torque::CallCsaMacroInstruction::GetValueDefinitionCount(), v8::internal::torque::CallCsaMacroAndBranchInstruction::GetValueDefinitionCount(), v8::internal::torque::CallBuiltinInstruction::GetValueDefinitionCount(), v8::internal::torque::CallRuntimeInstruction::GetValueDefinitionCount(), v8::internal::torque::ImplementationVisitor::InlineMacro(), v8::internal::torque::Intrinsic::Intrinsic(), v8::internal::torque::CallRuntimeInstruction::IsBlockTerminator(), IsTransitioning(), v8::internal::torque::Macro::Macro(), v8::internal::torque::operator<<(), ShouldBeInlined(), v8::internal::torque::Macro::ShouldBeInlined(), v8::internal::torque::Method::ShouldBeInlined(), v8::internal::torque::ImplementationVisitor::Visit(), and v8::internal::torque::ImplementationVisitor::VisitMacroCommon().
Member Data Documentation
body_
std::optional<Statement*> v8::internal::torque::Callable::body_ [private]
Definition at line 370 of file declarable.h.
Referenced by body(), and IsExternal().
external_name_
std::string v8::internal::torque::Callable::external_name_ [private]
Definition at line 366 of file declarable.h.
Referenced by ExternalName().
readable_name_
std::string v8::internal::torque::Callable::readable_name_ [private]
Definition at line 367 of file declarable.h.
Referenced by ReadableName().
returns_
size_t v8::internal::torque::Callable::returns_ [private]
Definition at line 369 of file declarable.h.
Referenced by HasReturns(), and IncrementReturns().
signature_
Signature v8::internal::torque::Callable::signature_ [private]
Definition at line 368 of file declarable.h.
Referenced by HasReturnValue(), parameter_names(), and signature().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/declarable.h