v8::VirtualAddressSpace Class Reference
Class to manage a virtual memory address space.
#include <v8-platform.h>
Public Types
using Address = uintptr_t
Public Member Functions
VirtualAddressSpace (size_t page_size, size_t allocation_granularity, Address base, size_t size, PagePermissions max_page_permissions)
virtual ~VirtualAddressSpace ()=default
size_t page_size () const
The page size used inside this space.
size_t allocation_granularity () const
The granularity of page allocations and, by extension, of subspace allocations.
Address base () const
The base address of the address space managed by this instance.
size_t size () const
The size of the address space managed by this instance.
PagePermissions max_page_permissions () const
The maximum page permissions that pages allocated inside this space can obtain.
bool Contains (Address address) const
Whether the |address| is inside the address space managed by this instance.
virtual void SetRandomSeed (int64_t seed)=0
Sets the random seed so that GetRandomPageAddress() will generate repeatable sequences of random addresses.
virtual Address RandomPageAddress ()=0
Returns a random address inside this address space, suitable for page allocations hints.
virtual V8_WARN_UNUSED_RESULT Address AllocatePages (Address hint, size_t size, size_t alignment, PagePermissions permissions)=0
virtual void FreePages (Address address, size_t size)=0
Frees previously allocated pages.
virtual V8_WARN_UNUSED_RESULT bool SetPagePermissions (Address address, size_t size, PagePermissions permissions)=0
Sets permissions of all allocated pages in the given range.
virtual V8_WARN_UNUSED_RESULT bool AllocateGuardRegion (Address address, size_t size)=0
Creates a guard region at the specified address.
virtual void FreeGuardRegion (Address address, size_t size)=0
Frees an existing guard region.
virtual V8_WARN_UNUSED_RESULT Address AllocateSharedPages (Address hint, size_t size, PagePermissions permissions, PlatformSharedMemoryHandle handle, uint64_t offset)=0
Allocates shared memory pages with the given permissions.
virtual void FreeSharedPages (Address address, size_t size)=0
Frees previously allocated shared pages.
virtual bool CanAllocateSubspaces ()=0
Whether this instance can allocate subspaces or not.
virtual std::unique_ptr< VirtualAddressSpace > AllocateSubspace (Address hint, size_t size, size_t alignment, PagePermissions max_page_permissions)=0
virtual V8_WARN_UNUSED_RESULT bool RecommitPages (Address address, size_t size, PagePermissions permissions)=0
Recommits discarded pages in the given range with given permissions.
virtual V8_WARN_UNUSED_RESULT bool DiscardSystemPages (Address address, size_t size)
Frees memory in the given [address, address + size) range.
virtual V8_WARN_UNUSED_RESULT bool DecommitPages (Address address, size_t size)=0
Decommits any wired memory pages in the given range, allowing the OS to reclaim them, and marks the region as inacessible (kNoAccess).
Static Public Attributes
static constexpr Address kNoHint = 0
Allocates private memory pages with the given alignment and permissions.
Private Attributes
const size_t page_size_
const size_t allocation_granularity_
const Address base_
const size_t size_
const PagePermissions max_page_permissions_
Detailed Description
Class to manage a virtual memory address space.
This class represents a contiguous region of virtual address space in which sub-spaces and (private or shared) memory pages can be allocated, freed, and modified. This interface is meant to eventually replace the PageAllocator interface, and can be used as an alternative in the meantime.
This API is not yet stable and may change without notice!
Definition at line 779 of file v8-platform.h.
Member Typedef Documentation
Address
using v8::VirtualAddressSpace::Address = uintptr_t
Definition at line 781 of file v8-platform.h.
Constructor & Destructor Documentation
VirtualAddressSpace()
v8::VirtualAddressSpace::VirtualAddressSpace (size_t page_size, size_t allocation_granularity, Address base, size_t size, PagePermissions max_page_permissions) [inline]
Definition at line 783 of file v8-platform.h.
      : page_size_(page_size),
        allocation_granularity_(allocation_granularity),
        base_(base),
        size_(size),
        max_page_permissions_(max_page_permissions) {}
 VirtualAddressSpace()
virtual v8::VirtualAddressSpace::~VirtualAddressSpace () [virtual], [default]
Member Function Documentation
AllocateGuardRegion()
virtual V8_WARN_UNUSED_RESULT bool v8::VirtualAddressSpace::AllocateGuardRegion (Address address, size_t size) [pure virtual]
Creates a guard region at the specified address.
Guard regions are guaranteed to cause a fault when accessed and generally do not count towards any memory consumption limits. Further, allocating guard regions can usually not fail in subspaces if the region does not overlap with another region, subspace, or page allocation.
Parameters
address The start address of the guard region. Must be aligned to the allocation_granularity().
size The size of the guard region in bytes. Must be a multiple of the allocation_granularity().
Returns
true on success, false otherwise.
Implemented in v8::base::LsanVirtualAddressSpace.
Referenced by v8::base::EmulatedVirtualAddressSubspace::AllocateGuardRegion().
AllocatePages()
virtual V8_WARN_UNUSED_RESULT Address v8::VirtualAddressSpace::AllocatePages (Address hint, size_t size, size_t alignment, PagePermissions permissions) [pure virtual]
Implemented in v8::base::LsanVirtualAddressSpace.
Referenced by v8::base::EmulatedVirtualAddressSubspace::AllocatePages(), v8::base::VirtualAddressSpacePageAllocator::AllocatePages(), v8::internal::SegmentedTable< Entry, size >::Initialize(), v8::internal::ExternalEntityTable< Entry, size >::Initialize(), and v8::internal::SegmentedTable< Entry, size >::TryAllocateSegment().
AllocateSharedPages()
virtual V8_WARN_UNUSED_RESULT Address v8::VirtualAddressSpace::AllocateSharedPages (Address hint, size_t size, PagePermissions permissions, PlatformSharedMemoryHandle handle, uint64_t offset) [pure virtual]
Allocates shared memory pages with the given permissions.
Parameters
hint Placement hint. See AllocatePages.
size The size of the allocation in bytes. Must be a multiple of the allocation_granularity().
permissions The page permissions of the newly allocated pages.
handle A platform-specific handle to a shared memory object. See the SharedMemoryHandleFromX routines above for ways to obtain these.
offset The offset in the shared memory object at which the mapping should start. Must be a multiple of the allocation_granularity().
Returns
the start address of the allocated pages on success, zero on failure.
Implemented in v8::base::LsanVirtualAddressSpace.
Referenced by v8::base::EmulatedVirtualAddressSubspace::AllocateSharedPages().
AllocateSubspace()
virtual std::unique_ptr<VirtualAddressSpace> v8::VirtualAddressSpace::AllocateSubspace (Address hint, size_t size, size_t alignment, PagePermissions max_page_permissions) [pure virtual]
Implemented in v8::base::LsanVirtualAddressSpace.
Referenced by v8::internal::SegmentedTable< Entry, size >::Initialize().
allocation_granularity()
size_t v8::VirtualAddressSpace::allocation_granularity () const [inline]
The granularity of page allocations and, by extension, of subspace allocations.
This is guaranteed to be a power of two and a multiple of the page_size(). In practice, this is equal to the page size on most OSes, but on Windows it is usually 64KB, while the page size is 4KB.
Returns
the allocation granularity in bytes.
Definition at line 811 of file v8-platform.h.
{ return allocation_granularity_; }
References allocation_granularity_.
Referenced by v8::internal::SegmentedTable< Entry, size >::Initialize().
base()
Address v8::VirtualAddressSpace::base () const [inline]
The base address of the address space managed by this instance.
Returns
the base address of this address space.
Definition at line 818 of file v8-platform.h.
{ return base_; }
References base_.
Referenced by Contains(), v8::internal::SegmentedTable< Entry, size >::FreeTableSegment(), v8::internal::ExternalEntityTable< Entry, size >::Initialize(), v8::internal::SegmentedTable< Entry, size >::is_initialized(), v8::internal::ExternalEntityTable< Entry, size >::SealReadOnlySegments(), v8::internal::ExternalEntityTable< Entry, size >::TearDown(), v8::internal::SegmentedTable< Entry, size >::TryAllocateSegment(), and v8::internal::ExternalEntityTable< Entry, size >::UnsealReadOnlySegments().
CanAllocateSubspaces()
virtual bool v8::VirtualAddressSpace::CanAllocateSubspaces () [pure virtual]
Whether this instance can allocate subspaces or not.
Returns
true if subspaces can be allocated, false if not.
Implemented in v8::base::LsanVirtualAddressSpace.
Referenced by v8::internal::SegmentedTable< Entry, size >::Initialize().
Contains()
bool v8::VirtualAddressSpace::Contains (Address address) const [inline]
Whether the |address| is inside the address space managed by this instance.
Returns
true if it is inside the address space, false if not.
Definition at line 840 of file v8-platform.h.
                                       {
    return (address >= base()) && (address < base() + size());
  }
References base(), and size().
DecommitPages()
virtual V8_WARN_UNUSED_RESULT bool v8::VirtualAddressSpace::DecommitPages (Address address, size_t size) [pure virtual]
Decommits any wired memory pages in the given range, allowing the OS to reclaim them, and marks the region as inacessible (kNoAccess).
The address range stays reserved and can be accessed again later by changing its permissions. However, in that case the memory content is guaranteed to be zero-initialized again. The memory must have been previously allocated by a call to AllocatePages.
Returns
true on success, false otherwise.
Implemented in v8::base::LsanVirtualAddressSpace.
Referenced by v8::base::EmulatedVirtualAddressSubspace::DecommitPages(), v8::base::VirtualAddressSpacePageAllocator::DecommitPages(), v8::base::EmulatedVirtualAddressSubspace::FreePages(), and v8::base::VirtualAddressSpacePageAllocator::ReleasePages().
DiscardSystemPages()
virtual V8_WARN_UNUSED_RESULT bool v8::VirtualAddressSpace::DiscardSystemPages (Address address, size_t size) [inline], [virtual]
Frees memory in the given [address, address + size) range.
address and size should be aligned to the page_size(). The next write to this memory area brings the memory transparently back. This should be treated as a hint to the OS that the pages are no longer needed. It does not guarantee that the pages will be discarded immediately or at all.
Returns
true on success, false otherwise. Since this method is only a hint, a successful invocation does not imply that pages have been removed.
Reimplemented in v8::base::LsanVirtualAddressSpace.
Definition at line 1056 of file v8-platform.h.
                                                                     {
    return true;
  }
Referenced by v8::base::EmulatedVirtualAddressSubspace::DiscardSystemPages(), and v8::base::VirtualAddressSpacePageAllocator::DiscardSystemPages().
FreeGuardRegion()
virtual void v8::VirtualAddressSpace::FreeGuardRegion (Address address, size_t size) [pure virtual]
Frees an existing guard region.
This function will terminate the process on failure as this implies a bug in the client. As such, there is no return value.
Parameters
address The start address of the guard region to free. This address must have previously been used as address parameter in a successful invocation of AllocateGuardRegion.
size The size in bytes of the guard region to free. This must match the size passed to AllocateGuardRegion when the region was created.
Implemented in v8::base::LsanVirtualAddressSpace.
Referenced by v8::base::EmulatedVirtualAddressSubspace::FreeGuardRegion().
FreePages()
virtual void v8::VirtualAddressSpace::FreePages (Address address, size_t size) [pure virtual]
Frees previously allocated pages.
This function will terminate the process on failure as this implies a bug in the client. As such, there is no return value.
Parameters
address The start address of the pages to free. This address must have been obtained through a call to AllocatePages.
size The size in bytes of the region to free. This must match the size passed to AllocatePages when the pages were allocated.
Implemented in v8::base::LsanVirtualAddressSpace.
Referenced by v8::base::EmulatedVirtualAddressSubspace::AllocatePages(), v8::base::EmulatedVirtualAddressSubspace::FreePages(), v8::base::VirtualAddressSpacePageAllocator::FreePages(), v8::internal::SegmentedTable< Entry, size >::FreeTableSegment(), v8::internal::ExternalEntityTable< Entry, size >::TearDown(), and v8::base::EmulatedVirtualAddressSubspace::~EmulatedVirtualAddressSubspace().
FreeSharedPages()
virtual void v8::VirtualAddressSpace::FreeSharedPages (Address address, size_t size) [pure virtual]
Frees previously allocated shared pages.
This function will terminate the process on failure as this implies a bug in the client. As such, there is no return value.
Parameters
address The start address of the pages to free. This address must have been obtained through a call to AllocateSharedPages.
size The size in bytes of the region to free. This must match the size passed to AllocateSharedPages when the pages were allocated.
Implemented in v8::base::LsanVirtualAddressSpace.
Referenced by v8::base::EmulatedVirtualAddressSubspace::AllocateSharedPages(), and v8::base::EmulatedVirtualAddressSubspace::FreeSharedPages().
max_page_permissions()
PagePermissions v8::VirtualAddressSpace::max_page_permissions () const [inline]
The maximum page permissions that pages allocated inside this space can obtain.
Returns
the maximum page permissions.
Definition at line 833 of file v8-platform.h.
{ return max_page_permissions_; }
References max_page_permissions_.
Referenced by v8::base::LsanVirtualAddressSpace::AllocateSubspace().
page_size()
size_t v8::VirtualAddressSpace::page_size () const [inline]
The page size used inside this space.
Guaranteed to be a power of two. Used as granularity for all page-related operations except for allocation, which use the allocation_granularity(), see below.
Returns
the page size in bytes.
Definition at line 801 of file v8-platform.h.
{ return page_size_; }
References page_size_.
RandomPageAddress()
virtual Address v8::VirtualAddressSpace::RandomPageAddress () [pure virtual]
Returns a random address inside this address space, suitable for page allocations hints.
Returns
a random address aligned to allocation_granularity().
Implemented in v8::base::LsanVirtualAddressSpace.
RecommitPages()
virtual V8_WARN_UNUSED_RESULT bool v8::VirtualAddressSpace::RecommitPages (Address address, size_t size, PagePermissions permissions) [pure virtual]
Recommits discarded pages in the given range with given permissions.
Discarded pages must be recommitted with their original permissions before they are used again.
Parameters
address The start address of the range. Must be aligned to page_size().
size The size in bytes of the range. Must be a multiple of page_size().
permissions The permissions for the range that the pages must have.
Returns
true on success, false otherwise.
Implemented in v8::base::LsanVirtualAddressSpace.
Referenced by v8::base::EmulatedVirtualAddressSubspace::RecommitPages(), and v8::base::VirtualAddressSpacePageAllocator::RecommitPages().
SetPagePermissions()
virtual V8_WARN_UNUSED_RESULT bool v8::VirtualAddressSpace::SetPagePermissions (Address address, size_t size, PagePermissions permissions) [pure virtual]
Sets permissions of all allocated pages in the given range.
This operation can fail due to OOM, in which case false is returned. If the operation fails for a reason other than OOM, this function will terminate the process as this implies a bug in the client.
Parameters
address The start address of the range. Must be aligned to page_size().
size The size in bytes of the range. Must be a multiple of page_size().
permissions The new permissions for the range.
Returns
true on success, false on OOM.
Implemented in v8::base::LsanVirtualAddressSpace.
Referenced by v8::base::EmulatedVirtualAddressSubspace::AllocatePages(), v8::internal::ExternalEntityTable< Entry, size >::SealReadOnlySegments(), v8::base::EmulatedVirtualAddressSubspace::SetPagePermissions(), v8::base::VirtualAddressSpacePageAllocator::SetPermissions(), and v8::internal::ExternalEntityTable< Entry, size >::UnsealReadOnlySegments().
SetRandomSeed()
virtual void v8::VirtualAddressSpace::SetRandomSeed (int64_t seed) [pure virtual]
Sets the random seed so that GetRandomPageAddress() will generate repeatable sequences of random addresses.
Parameters
The seed for the PRNG.
Implemented in v8::base::LsanVirtualAddressSpace.
Referenced by v8::internal::V8::Initialize().
size()
size_t v8::VirtualAddressSpace::size () const [inline]
The size of the address space managed by this instance.
Returns
the size of this address space in bytes.
Definition at line 825 of file v8-platform.h.
{ return size_; }
References size_.
Referenced by v8::base::LsanVirtualAddressSpace::AllocatePages(), v8::base::LsanVirtualAddressSpace::AllocateSharedPages(), v8::base::LsanVirtualAddressSpace::AllocateSubspace(), Contains(), v8::base::LsanVirtualAddressSpace::FreePages(), and v8::base::LsanVirtualAddressSpace::FreeSharedPages().
Member Data Documentation
allocation_granularity_
const size_t v8::VirtualAddressSpace::allocation_granularity_ [private]
Definition at line 1075 of file v8-platform.h.
Referenced by allocation_granularity().
base_
const Address v8::VirtualAddressSpace::base_ [private]
Definition at line 1076 of file v8-platform.h.
Referenced by base().
kNoHint
constexpr Address v8::VirtualAddressSpace::kNoHint = 0 [static], [constexpr]
Allocates private memory pages with the given alignment and permissions.
Parameters
hint If nonzero, the allocation is attempted to be placed at the given address first. If that fails, the allocation is attempted to be placed elsewhere, possibly nearby, but that is not guaranteed. Specifying zero for the hint always causes this function to choose a random address. The hint, if specified, must be aligned to the specified alignment.
size The size of the allocation in bytes. Must be a multiple of the allocation_granularity().
alignment The alignment of the allocation in bytes. Must be a multiple of the allocation_granularity() and should be a power of two.
permissions The page permissions of the newly allocated pages.
Returns
the start address of the allocated pages on success, zero on failure.
Definition at line 880 of file v8-platform.h.
Referenced by v8::internal::SegmentedTable< Entry, size >::Initialize(), and v8::internal::SegmentedTable< Entry, size >::TryAllocateSegment().
max_page_permissions_
const PagePermissions v8::VirtualAddressSpace::max_page_permissions_ [private]
Definition at line 1078 of file v8-platform.h.
Referenced by max_page_permissions().
page_size_
const size_t v8::VirtualAddressSpace::page_size_ [private]
Definition at line 1074 of file v8-platform.h.
Referenced by page_size().
size_
const size_t v8::VirtualAddressSpace::size_ [private]
Definition at line 1077 of file v8-platform.h.
Referenced by size().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/v8-platform.h