v8::internal::StringComparator Class Reference
#include <string-comparator.h>
Classes
class State
Public Member Functions
StringComparator ()=default
StringComparator (const StringComparator &)=delete
StringComparator & operator= (const StringComparator &)=delete
bool Equals (Tagged< String > string_1, Tagged< String > string_2, const SharedStringAccessGuardIfNeeded &access_guard)
Static Public Member Functions
template<typename Chars1 , typename Chars2 >
static bool Equals (State *state_1, State *state_2, int to_check)
Private Attributes
State state_1_
State state_2_
Detailed Description
Definition at line 16 of file string-comparator.h.
Constructor & Destructor Documentation
StringComparator() [1/2]
v8::internal::StringComparator::StringComparator () [inline], [default]
StringComparator() [2/2]
v8::internal::StringComparator::StringComparator (const StringComparator &) [delete]
Member Function Documentation
Equals() [1/2]
template<typename Chars1 , typename Chars2 >
static bool v8::internal::StringComparator::Equals (State * state_1, State * state_2, int to_check) [inline], [static]
Definition at line 56 of file string-comparator.h.
                                                                          {
    const Chars1* a = reinterpret_cast<const Chars1*>(state_1->buffer8_);
    const Chars2* b = reinterpret_cast<const Chars2*>(state_2->buffer8_);
    return CompareCharsEqual(a, b, to_check);
  }
References v8::internal::StringComparator::State::buffer8_, and v8::internal::CompareCharsEqual().
Referenced by v8::internal::String::SlowEquals().
Equals() [2/2]
bool v8::internal::StringComparator::Equals (Tagged< String > string_1, Tagged< String > string_2, const SharedStringAccessGuardIfNeeded & access_guard)
Definition at line 49 of file string-comparator.cc.
                                                         {
  int length = string_1->length();
  state_1_.Init(string_1, access_guard);
  state_2_.Init(string_2, access_guard);
  while (true) {
    int to_check = std::min(state_1_.length_, state_2_.length_);
    DCHECK(to_check > 0 && to_check <= length);
    bool is_equal;
    if (state_1_.is_one_byte_) {
      if (state_2_.is_one_byte_) {
        is_equal = Equals<uint8_t, uint8_t>(&state_1_, &state_2_, to_check);
      } else {
        is_equal = Equals<uint8_t, uint16_t>(&state_1_, &state_2_, to_check);
      }
    } else {
      if (state_2_.is_one_byte_) {
        is_equal = Equals<uint16_t, uint8_t>(&state_1_, &state_2_, to_check);
      } else {
        is_equal = Equals<uint16_t, uint16_t>(&state_1_, &state_2_, to_check);
      }
    }
    // Looping done.
    if (!is_equal) return false;
    length -= to_check;
    // Exit condition. Strings are equal.
    if (length == 0) return true;
    state_1_.Advance(to_check, access_guard);
    state_2_.Advance(to_check, access_guard);
  }
}
References v8::internal::StringComparator::State::Advance(), v8::internal::DCHECK(), v8::internal::StringComparator::State::Init(), v8::internal::StringComparator::State::is_one_byte_, v8::internal::length, v8::internal::StringComparator::State::length_, state_1_, and state_2_.
operator=()
StringComparator& v8::internal::StringComparator::operator= (const StringComparator &) [delete]
Member Data Documentation
state_1_
State v8::internal::StringComparator::state_1_ [private]
Definition at line 66 of file string-comparator.h.
Referenced by Equals().
state_2_
State v8::internal::StringComparator::state_2_ [private]
Definition at line 67 of file string-comparator.h.
Referenced by Equals().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/string-comparator.h
/mnt/V8SourceCode/src/objects/string-comparator.cc