v8::internal::wasm::AsyncStreamingDecoder::DecodeNumberOfFunctions Class Reference
Public Member Functions
DecodeNumberOfFunctions (SectionBuffer *section_buffer)
std::unique_ptr< DecodingState > NextWithValue (AsyncStreamingDecoder *streaming) override
Private Attributes
SectionBuffer *const section_buffer_
Additional Inherited Members
Detailed Description
Definition at line 499 of file streaming-decoder.cc.
Constructor & Destructor Documentation
DecodeNumberOfFunctions()
v8::internal::wasm::AsyncStreamingDecoder::DecodeNumberOfFunctions::DecodeNumberOfFunctions (SectionBuffer * section_buffer) [inline], [explicit]
Definition at line 501 of file streaming-decoder.cc.
      : DecodeVarInt32(v8_flags.max_wasm_functions, "functions count"),
        section_buffer_(section_buffer) {}
Member Function Documentation
NextWithValue()
std::unique_ptr< AsyncStreamingDecoder::DecodingState > v8::internal::wasm::AsyncStreamingDecoder::DecodeNumberOfFunctions::NextWithValue (AsyncStreamingDecoder * streaming) [override], [virtual]
Implements v8::internal::wasm::AsyncStreamingDecoder::DecodeVarInt32.
Definition at line 679 of file streaming-decoder.cc.
                                      {
  TRACE_STREAMING("DecodeNumberOfFunctions(%zu)\n", value_);
  // Copy the bytes we read into the section buffer.
  base::Vector<uint8_t> payload_buf = section_buffer_->payload();
  if (payload_buf.size() < bytes_consumed_) return streaming->ToErrorState();
  memcpy(payload_buf.begin(), buffer().begin(), bytes_consumed_);
  DCHECK_GE(kMaxInt, section_buffer_->module_offset() +
                         section_buffer_->payload_offset());
  int code_section_start = static_cast<int>(section_buffer_->module_offset() +
                                            section_buffer_->payload_offset());
  DCHECK_GE(kMaxInt, payload_buf.length());
  int code_section_len = static_cast<int>(payload_buf.length());
  DCHECK_GE(kMaxInt, value_);
  streaming->StartCodeSection(static_cast<int>(value_),
                              streaming->section_buffers_.back(),
                              code_section_start, code_section_len);
  if (!streaming->ok()) return nullptr;
  // {value} is the number of functions.
  if (value_ == 0) {
    if (payload_buf.size() != bytes_consumed_) {
      return streaming->ToErrorState();
    }
    return std::make_unique<DecodeSectionID>(streaming->module_offset());
  }
  return std::make_unique<DecodeFunctionLength>(
      section_buffer_, section_buffer_->payload_offset() + bytes_consumed_,
      value_);
}
References v8::base::Vector< T >::begin(), v8::internal::compiler::begin(), DCHECK_GE, v8::internal::kMaxInt, v8::base::Vector< T >::length(), v8::internal::wasm::AsyncStreamingDecoder::module_offset(), v8::internal::wasm::AsyncStreamingDecoder::ok(), v8::internal::wasm::AsyncStreamingDecoder::section_buffers_, v8::base::Vector< T >::size(), v8::internal::wasm::AsyncStreamingDecoder::StartCodeSection(), v8::internal::wasm::AsyncStreamingDecoder::ToErrorState(), and TRACE_STREAMING.
Member Data Documentation
section_buffer_
SectionBuffer* const v8::internal::wasm::AsyncStreamingDecoder::DecodeNumberOfFunctions::section_buffer_ [private]
Definition at line 509 of file streaming-decoder.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/streaming-decoder.cc