v8::internal::compiler::CommonNodeWrapperBase Class Reference
#include <common-operator.h>
Public Member Functions
constexpr CommonNodeWrapperBase (Node *node)
Effect effect () const
Control control () const
Additional Inherited Members
Detailed Description
Definition at line 687 of file common-operator.h.
Constructor & Destructor Documentation
CommonNodeWrapperBase()
constexpr v8::internal::compiler::CommonNodeWrapperBase::CommonNodeWrapperBase (Node * node) [inline], [explicit], [constexpr]
Definition at line 689 of file common-operator.h.
: NodeWrapper(node) {}
Member Function Documentation
control()
Control v8::internal::compiler::CommonNodeWrapperBase::control () const [inline]
Definition at line 698 of file common-operator.h.
                          {
    DCHECK_EQ(node()->op()->ControlInputCount(), 1);
    return Control{NodeProperties::GetControlInput(node())};
  }
References DCHECK_EQ, v8::internal::compiler::NodeProperties::GetControlInput(), and v8::internal::compiler::NodeWrapper::node().
effect()
Effect v8::internal::compiler::CommonNodeWrapperBase::effect () const [inline]
Definition at line 692 of file common-operator.h.
                        {
    DCHECK_EQ(node()->op()->EffectInputCount(), 1);
    return Effect{NodeProperties::GetEffectInput(node())};
  }
References DCHECK_EQ, v8::internal::compiler::NodeProperties::GetEffectInput(), and v8::internal::compiler::NodeWrapper::node().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/common-operator.h