v8::internal::NaryOperationSourceRanges Class Reference
#include <ast-source-ranges.h>
Public Member Functions
NaryOperationSourceRanges (Zone *zone, const SourceRange &range)
SourceRange GetRangeAtIndex (size_t index)
void AddRange (const SourceRange &range)
size_t RangeCount () const
SourceRange GetRange (SourceRangeKind kind) override
bool HasRange (SourceRangeKind kind) override
Private Attributes
ZoneVector< SourceRange > ranges_
Detailed Description
Definition at line 297 of file ast-source-ranges.h.
Constructor & Destructor Documentation
NaryOperationSourceRanges()
v8::internal::NaryOperationSourceRanges::NaryOperationSourceRanges (Zone * zone, const SourceRange & range) [inline]
Definition at line 299 of file ast-source-ranges.h.
      : ranges_(zone) {
    AddRange(range);
  }
References AddRange().
Member Function Documentation
AddRange()
void v8::internal::NaryOperationSourceRanges::AddRange (const SourceRange & range) [inline]
Definition at line 309 of file ast-source-ranges.h.
{ ranges_.push_back(range); }
References ranges_.
Referenced by v8::internal::Parser::AppendNaryOperationSourceRange(), and NaryOperationSourceRanges().
GetRange()
SourceRange v8::internal::NaryOperationSourceRanges::GetRange (SourceRangeKind kind) [inline], [override], [virtual]
Implements v8::internal::AstNodeSourceRanges.
Definition at line 312 of file ast-source-ranges.h.
{ UNREACHABLE(); }
References v8::internal::UNREACHABLE().
GetRangeAtIndex()
SourceRange v8::internal::NaryOperationSourceRanges::GetRangeAtIndex (size_t index) [inline]
Definition at line 304 of file ast-source-ranges.h.
                                            {
    DCHECK(index < ranges_.size());
    return ranges_[index];
  }
References v8::internal::DCHECK(), v8::internal::index, and ranges_.
Referenced by v8::internal::interpreter::BlockCoverageBuilder::AllocateNaryBlockCoverageSlot().
HasRange()
bool v8::internal::NaryOperationSourceRanges::HasRange (SourceRangeKind kind) [inline], [override], [virtual]
Implements v8::internal::AstNodeSourceRanges.
Definition at line 313 of file ast-source-ranges.h.
{ return false; }
RangeCount()
size_t v8::internal::NaryOperationSourceRanges::RangeCount () const [inline]
Definition at line 310 of file ast-source-ranges.h.
{ return ranges_.size(); }
References ranges_.
Referenced by v8::internal::Parser::AppendNaryOperationSourceRange().
Member Data Documentation
ranges_
ZoneVector<SourceRange> v8::internal::NaryOperationSourceRanges::ranges_ [private]
Definition at line 316 of file ast-source-ranges.h.
Referenced by AddRange(), GetRangeAtIndex(), and RangeCount().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ast/ast-source-ranges.h