v8::internal::compiler::ElementsTransitionWithMultipleSources Class Reference
#include <simplified-operator.h>
Public Member Functions
ElementsTransitionWithMultipleSources (ZoneRefSet< Map > sources, MapRef target, const FeedbackSource &feedback=FeedbackSource())
const ZoneRefSet< Map > & sources () const
MapRef target () const
const FeedbackSource & feedback () const
Private Attributes
ZoneRefSet< Map > sources_
const MapRef target_
FeedbackSource feedback_
Detailed Description
Definition at line 544 of file simplified-operator.h.
Constructor & Destructor Documentation
ElementsTransitionWithMultipleSources()
v8::internal::compiler::ElementsTransitionWithMultipleSources::ElementsTransitionWithMultipleSources (ZoneRefSet< Map > sources, MapRef target, const FeedbackSource & feedback = FeedbackSource()) [inline]
Definition at line 546 of file simplified-operator.h.
      : sources_(sources), target_(target), feedback_(feedback) {}
Member Function Documentation
feedback()
const FeedbackSource& v8::internal::compiler::ElementsTransitionWithMultipleSources::feedback () const [inline]
Definition at line 553 of file simplified-operator.h.
{ return feedback_; }
sources()
const ZoneRefSet<Map>& v8::internal::compiler::ElementsTransitionWithMultipleSources::sources () const [inline]
Definition at line 551 of file simplified-operator.h.
{ return sources_; }
Referenced by v8::internal::compiler::LoadElimination::ComputeLoopState(), v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), and v8::internal::compiler::LoadElimination::ReduceTransitionElementsKindOrCheckMap().
target()
MapRef v8::internal::compiler::ElementsTransitionWithMultipleSources::target () const [inline]
Definition at line 552 of file simplified-operator.h.
{ return target_; }
Referenced by v8::internal::compiler::LoadElimination::ComputeLoopState(), v8::internal::compiler::hash_value(), v8::internal::compiler::NodeProperties::InferMapsUnsafe(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode(), v8::internal::compiler::LoadElimination::ReduceTransitionElementsKindOrCheckMap(), and v8::internal::compiler::TypedOptimization::ReduceTransitionElementsKindOrCheckMap().
Member Data Documentation
feedback_
FeedbackSource v8::internal::compiler::ElementsTransitionWithMultipleSources::feedback_ [private]
Definition at line 558 of file simplified-operator.h.
sources_
ZoneRefSet<Map> v8::internal::compiler::ElementsTransitionWithMultipleSources::sources_ [private]
Definition at line 556 of file simplified-operator.h.
target_
const MapRef v8::internal::compiler::ElementsTransitionWithMultipleSources::target_ [private]
Definition at line 557 of file simplified-operator.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/simplified-operator.h