v8::internal::WasmMemoryObject Class Reference
#include <wasm-objects.h>
Public Member Functions
bool has_maximum_pages ()
bool is_memory64 () const
void SetNewBuffer (Isolate *isolate, Tagged< JSArrayBuffer > new_buffer)
void UpdateInstances (Isolate *isolate)
void FixUpResizableArrayBuffer (Tagged< JSArrayBuffer > new_buffer)
Static Public Member Functions
static V8_EXPORT_PRIVATE void UseInInstance (Isolate *isolate, DirectHandle< WasmMemoryObject > memory, DirectHandle< WasmTrustedInstanceData > trusted_instance_data, DirectHandle< WasmTrustedInstanceData > shared_trusted_instance_data, int memory_index_in_instance)
static V8_EXPORT_PRIVATE DirectHandle< WasmMemoryObject > New (Isolate *isolate, DirectHandle< JSArrayBuffer > buffer, int maximum, wasm::AddressType address_type)
static V8_EXPORT_PRIVATE MaybeDirectHandle< WasmMemoryObject > New (Isolate *isolate, int initial, int maximum, SharedFlag shared, wasm::AddressType address_type)
static DirectHandle< JSArrayBuffer > RefreshBuffer (Isolate *isolate, DirectHandle< WasmMemoryObject > memory, std::shared_ptr< BackingStore > new_backing_store)
static DirectHandle< JSArrayBuffer > RefreshSharedBuffer (Isolate *isolate, DirectHandle< WasmMemoryObject > memory, ResizableFlag resizable_by_js)
static V8_EXPORT_PRIVATE int32_t Grow (Isolate *, DirectHandle< WasmMemoryObject >, uint32_t pages)
static DirectHandle< JSArrayBuffer > ToFixedLengthBuffer (Isolate *isolate, DirectHandle< WasmMemoryObject > memory)
static DirectHandle< JSArrayBuffer > ToResizableBuffer (Isolate *isolate, DirectHandle< WasmMemoryObject > memory)
Static Public Attributes
static constexpr int kNoMaximum = -1
Detailed Description
Definition at line 348 of file wasm-objects.h.
Member Function Documentation
FixUpResizableArrayBuffer()
void v8::internal::WasmMemoryObject::FixUpResizableArrayBuffer (Tagged< JSArrayBuffer > new_buffer)
Definition at line 1048 of file wasm-objects.cc.
                                      {
  DCHECK(has_maximum_pages());
  DCHECK(new_buffer->is_resizable_by_js());
  DisallowGarbageCollection no_gc;
  if (new_buffer->is_shared()) new_buffer->set_byte_length(0);
  // Unlike JS-created resizable buffers, Wasm memories' backing store maximum
  // may differ from the exposed maximum.
  uintptr_t max_byte_length;
  if constexpr (kSystemPointerSize == 4) {
    // The spec says the maximum number of pages for 32-bit memories is 65536,
    // which means the maximum byte size is 65536 * 65536 (= 2^32), which is
    // UINT32_MAX+1. BackingStores, ArrayBuffers, and TypedArrays represent byte
    // lengths as uintptr_t, and UINT32_MAX+1 is not representable on 32bit.
    //
    // As a willful violation and gross hack, if we're exposing a Wasm memory
    // with an unrepresentable maximum, subtract one page size.
    uint64_t max_byte_length64 =
        static_cast<uint64_t>(maximum_pages()) * wasm::kWasmPageSize;
    if (max_byte_length64 > std::numeric_limits<uintptr_t>::max()) {
      max_byte_length64 =
          std::numeric_limits<uintptr_t>::max() - wasm::kWasmPageSize;
      CHECK(new_buffer->GetBackingStore()->max_byte_length() <=
            max_byte_length64);
    }
    max_byte_length = static_cast<uintptr_t>(max_byte_length64);
  } else {
    max_byte_length = maximum_pages() * wasm::kWasmPageSize;
  }
  new_buffer->set_max_byte_length(max_byte_length);
}
References CHECK, v8::internal::DCHECK(), has_maximum_pages(), v8::internal::kSystemPointerSize, v8::internal::wasm::kWasmPageSize, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by SetNewBuffer().
Grow()
int32_t v8::internal::WasmMemoryObject::Grow (Isolate * isolate, DirectHandle< WasmMemoryObject > memory_object, uint32_t pages) [static]
Definition at line 1146 of file wasm-objects.cc.
                                               {
  TRACE_EVENT0("v8.wasm", "wasm.GrowMemory");
  DirectHandle<JSArrayBuffer> old_buffer(memory_object->array_buffer(),
                                         isolate);
  std::shared_ptr<BackingStore> backing_store = old_buffer->GetBackingStore();
  // Wasm memory can grow, and Wasm memory always has a backing store.
  DCHECK_NOT_NULL(backing_store);
  // Check for maximum memory size.
  // Note: The {wasm::max_mem_pages()} limit is already checked in
  // {BackingStore::CopyWasmMemory}, and is irrelevant for
  // {GrowWasmMemoryInPlace} because memory is never allocated with more
  // capacity than that limit.
  size_t old_size = old_buffer->GetByteLength();
  DCHECK_EQ(0, old_size % wasm::kWasmPageSize);
  size_t old_pages = old_size / wasm::kWasmPageSize;
  size_t max_pages = memory_object->is_memory64() ? wasm::max_mem64_pages()
                                                  : wasm::max_mem32_pages();
  if (memory_object->has_maximum_pages()) {
    max_pages = std::min(max_pages,
                         static_cast<size_t>(memory_object->maximum_pages()));
  }
  DCHECK_GE(max_pages, old_pages);
  if (pages > max_pages - old_pages) return -1;
  const bool must_grow_in_place =
      old_buffer->is_shared() || backing_store->has_guard_regions() ||
      backing_store->is_resizable_by_js() || pages == 0;
  const bool try_grow_in_place =
      must_grow_in_place || !v8_flags.stress_wasm_memory_moving;
  std::optional<size_t> result_inplace =
      try_grow_in_place
          ? backing_store->GrowWasmMemoryInPlace(isolate, pages, max_pages)
          : std::nullopt;
  if (must_grow_in_place && !result_inplace.has_value()) {
    // There are different limits per platform, thus crash if the correctness
    // fuzzer is running.
    if (v8_flags.correctness_fuzzer_suppressions) {
      FATAL("could not grow wasm memory");
    }
    return -1;
  }
  // Handle shared memory first.
  if (old_buffer->is_shared()) {
    DCHECK(result_inplace.has_value());
    backing_store->BroadcastSharedWasmMemoryGrow(isolate);
    if (!old_buffer->is_resizable_by_js()) {
      // Broadcasting the update should update this memory object too.
      CHECK_NE(*old_buffer, memory_object->array_buffer());
    }
    size_t new_pages = result_inplace.value() + pages;
    // If the allocation succeeded, then this can't possibly overflow:
    size_t new_byte_length = new_pages * wasm::kWasmPageSize;
    // This is a less than check, as it is not guaranteed that the SAB
    // length here will be equal to the stashed length above as calls to
    // grow the same memory object can come in from different workers.
    // It is also possible that a call to Grow was in progress when
    // handling this call.
    CHECK_LE(new_byte_length, memory_object->array_buffer()->GetByteLength());
    // As {old_pages} was read racefully, we return here the synchronized
    // value provided by {GrowWasmMemoryInPlace}, to provide the atomic
    // read-modify-write behavior required by the spec.
    return static_cast<int32_t>(result_inplace.value()); // success
  }
  size_t new_pages = old_pages + pages;
  // Check for overflow (should be excluded via {max_pages} above).
  DCHECK_LE(old_pages, new_pages);
  // Check if the non-shared memory could grow in-place.
  if (result_inplace.has_value()) {
    if (memory_object->array_buffer()->is_resizable_by_js()) {
      memory_object->array_buffer()->set_byte_length(new_pages *
                                                     wasm::kWasmPageSize);
      memory_object->UpdateInstances(isolate);
    } else {
      RefreshBuffer(isolate, memory_object, std::move(backing_store));
    }
    DCHECK_EQ(result_inplace.value(), old_pages);
    return static_cast<int32_t>(result_inplace.value()); // success
  }
  DCHECK(!memory_object->array_buffer()->is_resizable_by_js());
  // We should only try growing by copying if we actually grow.
  DCHECK_LT(old_pages, new_pages);
  // Try allocating a new backing store and copying.
  // To avoid overall quadratic complexity of many small grow operations, we
  // grow by at least 0.5 MB + 12.5% of the existing memory size.
  // These numbers are kept small because we must be careful about address
  // space consumption on 32-bit platforms.
  size_t min_growth = old_pages + 8 + (old_pages >> 3);
  // First apply {min_growth}, then {max_pages}. The order is important, because
  // {min_growth} can be bigger than {max_pages}, and in that case we want to
  // cap to {max_pages}.
  size_t new_capacity = std::min(max_pages, std::max(new_pages, min_growth));
  DCHECK_LE(new_pages, new_capacity);
  std::unique_ptr<BackingStore> new_backing_store =
      backing_store->CopyWasmMemory(isolate, new_pages, new_capacity,
                                    memory_object->is_memory64()
                                        ? WasmMemoryFlag::kWasmMemory64
                                        : WasmMemoryFlag::kWasmMemory32);
  if (!new_backing_store) {
    // Crash on out-of-memory if the correctness fuzzer is running.
    if (v8_flags.correctness_fuzzer_suppressions) {
      FATAL("could not grow wasm memory");
    }
    // Set the non-determinism flag in the WasmEngine.
    wasm::WasmEngine::set_had_nondeterminism();
    return -1;
  }
  RefreshBuffer(isolate, memory_object, std::move(new_backing_store));
  return static_cast<int32_t>(old_pages); // success
}
References CHECK_LE, CHECK_NE, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, DCHECK_LE, DCHECK_LT, DCHECK_NOT_NULL, FATAL, v8::internal::kWasmMemory32, v8::internal::kWasmMemory64, v8::internal::wasm::kWasmPageSize, v8::internal::wasm::max_mem32_pages(), v8::internal::wasm::max_mem64_pages(), RefreshBuffer(), v8::internal::wasm::WasmEngine::set_had_nondeterminism(), TRACE_EVENT0, and v8::internal::v8_flags.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::MemoryGrow(), v8::internal::ResizeHelper(), v8::internal::RUNTIME_FUNCTION(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryGrowImpl().
has_maximum_pages()
bool v8::internal::WasmMemoryObject::has_maximum_pages () [inline]
Definition at line 638 of file wasm-objects-inl.h.
{ return maximum_pages() >= 0; }
Referenced by FixUpResizableArrayBuffer().
is_memory64()
bool v8::internal::WasmMemoryObject::is_memory64 () const [inline]
Definition at line 640 of file wasm-objects-inl.h.
                                         {
  return address_type() == wasm::AddressType::kI64;
}
References v8::internal::wasm::kI64.
New() [1/2]
DirectHandle< WasmMemoryObject > v8::internal::WasmMemoryObject::New (Isolate * isolate, DirectHandle< JSArrayBuffer > buffer, int maximum, wasm::AddressType address_type) [static]
Definition at line 878 of file wasm-objects.cc.
                                  {
  DirectHandle<JSFunction> memory_ctor(
      isolate->native_context()->wasm_memory_constructor(), isolate);
  auto memory_object = Cast<WasmMemoryObject>(
      isolate->factory()->NewJSObject(memory_ctor, AllocationType::kOld));
  memory_object->set_array_buffer(*buffer);
  memory_object->set_maximum_pages(maximum);
  memory_object->set_address_type(address_type);
  memory_object->set_padding_for_address_type_0(0);
  memory_object->set_padding_for_address_type_1(0);
#if TAGGED_SIZE_8_BYTES
  memory_object->set_padding_for_address_type_2(0);
#endif
  memory_object->set_instances(ReadOnlyRoots{isolate}.empty_weak_array_list());
  if (buffer->is_resizable_by_js()) {
    memory_object->FixUpResizableArrayBuffer(*buffer);
  }
  std::shared_ptr<BackingStore> backing_store = buffer->GetBackingStore();
  if (buffer->is_shared()) {
    // Only Wasm memory can be shared (in contrast to asm.js memory).
    CHECK(backing_store && backing_store->is_wasm_memory());
    backing_store->AttachSharedWasmMemoryObject(isolate, memory_object);
  } else if (backing_store) {
    CHECK(!backing_store->is_shared());
  }
  // Memorize a link from the JSArrayBuffer to its owning WasmMemoryObject
  // instance.
  DirectHandle<Symbol> symbol =
      isolate->factory()->array_buffer_wasm_memory_symbol();
  Object::SetProperty(isolate, buffer, symbol, memory_object).Check();
  return memory_object;
}
References CHECK, v8::internal::Isolate::factory(), v8::internal::kOld, v8::internal::Isolate::native_context(), v8::internal::Factory::NewJSObject(), and v8::internal::Object::SetProperty().
Referenced by v8::internal::wasm::InstanceBuilder::AllocateMemory(), v8::internal::wasm::InstanceBuilder::Build_Phase1(), New(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryImpl().
New() [2/2]
MaybeDirectHandle< WasmMemoryObject > v8::internal::WasmMemoryObject::New (Isolate * isolate, int initial, int maximum, SharedFlag shared, wasm::AddressType address_type) [static]
Definition at line 918 of file wasm-objects.cc.
                                  {
  bool has_maximum = maximum != kNoMaximum;
  int engine_maximum = address_type == wasm::AddressType::kI64
                           ? static_cast<int>(wasm::max_mem64_pages())
                           : static_cast<int>(wasm::max_mem32_pages());
  if (initial > engine_maximum) return {};
#ifdef V8_TARGET_ARCH_32_BIT
  // On 32-bit platforms we need an heuristic here to balance overall memory
  // and address space consumption.
  constexpr int kGBPages = 1024 * 1024 * 1024 / wasm::kWasmPageSize;
  // We allocate the smallest of the following sizes, but at least the initial
  // size:
  // 1) the module-defined maximum;
  // 2) 1GB;
  // 3) the engine maximum;
  int allocation_maximum = std::min(kGBPages, engine_maximum);
  int heuristic_maximum;
  if (initial > kGBPages) {
    // We always allocate at least the initial size.
    heuristic_maximum = initial;
  } else if (has_maximum) {
    // We try to reserve the maximum, but at most the allocation_maximum to
    // avoid OOMs.
    heuristic_maximum = std::min(maximum, allocation_maximum);
  } else if (shared == SharedFlag::kShared) {
    // If shared memory has no maximum, we use the allocation_maximum as an
    // implicit maximum.
    heuristic_maximum = allocation_maximum;
  } else {
    // If non-shared memory has no maximum, we only allocate the initial size
    // and then grow with realloc.
    heuristic_maximum = initial;
  }
#else
  int heuristic_maximum =
      has_maximum ? std::min(engine_maximum, maximum) : engine_maximum;
#endif
  std::unique_ptr<BackingStore> backing_store =
      BackingStore::AllocateWasmMemory(isolate, initial, heuristic_maximum,
                                       address_type == wasm::AddressType::kI32
                                           ? WasmMemoryFlag::kWasmMemory32
                                           : WasmMemoryFlag::kWasmMemory64,
                                       shared);
  if (!backing_store) return {};
  DirectHandle<JSArrayBuffer> buffer =
      shared == SharedFlag::kShared
          ? isolate->factory()->NewJSSharedArrayBuffer(std::move(backing_store))
          : isolate->factory()->NewJSArrayBuffer(std::move(backing_store));
  return New(isolate, buffer, maximum, address_type);
}
References v8::internal::Isolate::factory(), v8::internal::wasm::kI32, v8::internal::wasm::kI64, kNoMaximum, v8::internal::kShared, v8::internal::kWasmMemory32, v8::internal::kWasmMemory64, v8::internal::wasm::kWasmPageSize, v8::internal::wasm::max_mem32_pages(), v8::internal::wasm::max_mem64_pages(), New(), v8::internal::Factory::NewJSArrayBuffer(), and v8::internal::Factory::NewJSSharedArrayBuffer().
RefreshBuffer()
DirectHandle< JSArrayBuffer > v8::internal::WasmMemoryObject::RefreshBuffer (Isolate * isolate, DirectHandle< WasmMemoryObject > memory, std::shared_ptr< BackingStore > new_backing_store) [static]
Definition at line 1081 of file wasm-objects.cc.
                                                   {
  // Detach old and create a new one with the new backing store.
  DirectHandle<JSArrayBuffer> old_buffer(memory_object->array_buffer(),
                                         isolate);
#ifdef DEBUG
  void* old_data_pointer = old_buffer->backing_store();
  size_t old_byte_length = old_buffer->byte_length();
#endif
  JSArrayBuffer::Detach(old_buffer, true).Check();
  DirectHandle<JSArrayBuffer> new_buffer =
      isolate->factory()->NewJSArrayBuffer(std::move(new_backing_store));
#ifdef DEBUG
  bool data_pointer_unchanged = new_buffer->backing_store() == old_data_pointer;
  bool byte_length_unchanged = new_buffer->byte_length() == old_byte_length;
  bool resizability_changed =
      old_buffer->is_resizable_by_js() != new_buffer->is_resizable_by_js();
  // SetNewBuffer only calls UpdateInstances if resizability didn't change,
  // which depends on resizability changing not changing the data pointer or
  // byte length. See comment in SetNewBuffer.
  DCHECK_IMPLIES(resizability_changed,
                 data_pointer_unchanged && byte_length_unchanged);
#endif
  memory_object->SetNewBuffer(isolate, *new_buffer);
  // Memorize a link from the JSArrayBuffer to its owning WasmMemoryObject
  // instance.
  DirectHandle<Symbol> symbol =
      isolate->factory()->array_buffer_wasm_memory_symbol();
  Object::SetProperty(isolate, new_buffer, symbol, memory_object).Check();
  return new_buffer;
}
References DCHECK_IMPLIES, v8::internal::JSArrayBuffer::Detach(), v8::internal::Isolate::factory(), v8::internal::Factory::NewJSArrayBuffer(), and v8::internal::Object::SetProperty().
Referenced by Grow(), ToFixedLengthBuffer(), and ToResizableBuffer().
RefreshSharedBuffer()
DirectHandle< JSArrayBuffer > v8::internal::WasmMemoryObject::RefreshSharedBuffer (Isolate * isolate, DirectHandle< WasmMemoryObject > memory, ResizableFlag resizable_by_js) [static]
Definition at line 1115 of file wasm-objects.cc.
                                   {
  DirectHandle<JSArrayBuffer> old_buffer(memory_object->array_buffer(),
                                         isolate);
  std::shared_ptr<BackingStore> backing_store = old_buffer->GetBackingStore();
  // Wasm memory always has a BackingStore.
  CHECK_NOT_NULL(backing_store);
  CHECK(backing_store->is_wasm_memory());
  CHECK(backing_store->is_shared());
  // Keep a raw pointer to the backing store for a CHECK later one. Make it
  // {void*} so we do not accidentally try to use it for anything else.
  void* expected_backing_store = backing_store.get();
  DirectHandle<JSArrayBuffer> new_buffer =
      isolate->factory()->NewJSSharedArrayBuffer(std::move(backing_store));
  CHECK_EQ(expected_backing_store, new_buffer->GetBackingStore().get());
  if (resizable_by_js == ResizableFlag::kResizable) {
    new_buffer->set_is_resizable_by_js(true);
  }
  memory_object->SetNewBuffer(isolate, *new_buffer);
  // Memorize a link from the JSArrayBuffer to its owning WasmMemoryObject
  // instance.
  DirectHandle<Symbol> symbol =
      isolate->factory()->array_buffer_wasm_memory_symbol();
  Object::SetProperty(isolate, new_buffer, symbol, memory_object).Check();
  return new_buffer;
}
References CHECK, CHECK_EQ, CHECK_NOT_NULL, v8::internal::Isolate::factory(), v8::internal::kResizable, v8::internal::Factory::NewJSSharedArrayBuffer(), and v8::internal::Object::SetProperty().
Referenced by ToFixedLengthBuffer(), and ToResizableBuffer().
SetNewBuffer()
void v8::internal::WasmMemoryObject::SetNewBuffer (Isolate * isolate, Tagged< JSArrayBuffer > new_buffer)
Definition at line 996 of file wasm-objects.cc.
                                                                      {
  DisallowGarbageCollection no_gc;
  const bool new_buffer_is_resizable_by_js = new_buffer->is_resizable_by_js();
  if (new_buffer_is_resizable_by_js) {
    FixUpResizableArrayBuffer(*new_buffer);
  }
  Tagged<JSArrayBuffer> old_buffer = array_buffer();
  set_array_buffer(new_buffer);
  // Iterating and updating all instances is a slow operation, and is required
  // when the pointer to memory or size of memory changes.
  //
  // When refreshing the buffer for changing the resizability of the JS-exposed
  // (S)AB, both the data pointer and size stay the same, only the JS object
  // changes.
  //
  // When refreshing the buffer for growing a memory exposing a fixed-length
  // (S)AB (i.e. both the old and new buffers are !is_resizable_by_js()), the
  // size is changing, and updating the instances is needed.
  //
  // This function is never called in a way such that both the old and new
  // (S)ABs are resizable. Once a Wasm memory exposes a resizable (S)AB,
  // changing the size does not refresh the buffer.
  DCHECK(!old_buffer->is_resizable_by_js() ||
         !new_buffer->is_resizable_by_js());
  if (!old_buffer->is_resizable_by_js() && !new_buffer_is_resizable_by_js) {
    UpdateInstances(isolate);
  }
}
References v8::internal::DCHECK(), FixUpResizableArrayBuffer(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and UpdateInstances().
ToFixedLengthBuffer()
DirectHandle< JSArrayBuffer > v8::internal::WasmMemoryObject::ToFixedLengthBuffer (Isolate * isolate, DirectHandle< WasmMemoryObject > memory) [static]
Definition at line 1269 of file wasm-objects.cc.
                                                                    {
  DirectHandle<JSArrayBuffer> old_buffer(memory_object->array_buffer(),
                                         isolate);
  DCHECK(old_buffer->is_resizable_by_js());
  if (old_buffer->is_shared()) {
    return RefreshSharedBuffer(isolate, memory_object,
                               ResizableFlag::kNotResizable);
  }
  std::shared_ptr<BackingStore> backing_store = old_buffer->GetBackingStore();
  DCHECK_NOT_NULL(backing_store);
  backing_store->MakeWasmMemoryResizableByJS(false);
  return RefreshBuffer(isolate, memory_object, std::move(backing_store));
}
References v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::kNotResizable, RefreshBuffer(), and RefreshSharedBuffer().
Referenced by v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryToFixedLengthBufferImpl().
ToResizableBuffer()
DirectHandle< JSArrayBuffer > v8::internal::WasmMemoryObject::ToResizableBuffer (Isolate * isolate, DirectHandle< WasmMemoryObject > memory) [static]
Definition at line 1285 of file wasm-objects.cc.
                                                                    {
  // Resizable ArrayBuffers require a maximum size during creation. Mirror the
  // requirement when reflecting Wasm memory as a resizable buffer.
  DCHECK(memory_object->has_maximum_pages());
  DirectHandle<JSArrayBuffer> old_buffer(memory_object->array_buffer(),
                                         isolate);
  DCHECK(!old_buffer->is_resizable_by_js());
  if (old_buffer->is_shared()) {
    return RefreshSharedBuffer(isolate, memory_object,
                               ResizableFlag::kResizable);
  }
  std::shared_ptr<BackingStore> backing_store = old_buffer->GetBackingStore();
  DCHECK_NOT_NULL(backing_store);
  backing_store->MakeWasmMemoryResizableByJS(true);
  return RefreshBuffer(isolate, memory_object, std::move(backing_store));
}
References v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::kResizable, RefreshBuffer(), and RefreshSharedBuffer().
Referenced by v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryToResizableBufferImpl().
UpdateInstances()
void v8::internal::WasmMemoryObject::UpdateInstances (Isolate * isolate)
Definition at line 1026 of file wasm-objects.cc.
                                                       {
  DisallowGarbageCollection no_gc;
  Tagged<WeakArrayList> instances = this->instances();
  for (int i = 0, len = instances->length(); i < len; ++i) {
    Tagged<MaybeObject> elem = instances->Get(i);
    if (elem.IsCleared()) continue;
    Tagged<WasmInstanceObject> instance_object =
        Cast<WasmInstanceObject>(elem.GetHeapObjectAssumeWeak());
    Tagged<WasmTrustedInstanceData> trusted_data =
        instance_object->trusted_data(isolate);
    // TODO(clemens): Avoid the iteration by also remembering the memory index
    // if we ever see larger numbers of memories.
    Tagged<FixedArray> memory_objects = trusted_data->memory_objects();
    int num_memories = memory_objects->length();
    for (int mem_idx = 0; mem_idx < num_memories; ++mem_idx) {
      if (memory_objects->get(mem_idx) == *this) {
        SetInstanceMemory(trusted_data, array_buffer(), mem_idx);
      }
    }
  }
}
References v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectAssumeWeak(), v8::internal::instance_object, v8::internal::TaggedImpl< kRefType, StorageType >::IsCleared(), v8::internal::memory_objects, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::anonymous_namespace{wasm-objects.cc}::SetInstanceMemory().
Referenced by SetNewBuffer().
UseInInstance()
void v8::internal::WasmMemoryObject::UseInInstance (Isolate * isolate, DirectHandle< WasmMemoryObject > memory, DirectHandle< WasmTrustedInstanceData > trusted_instance_data, DirectHandle< WasmTrustedInstanceData > shared_trusted_instance_data, int memory_index_in_instance) [static]
Definition at line 978 of file wasm-objects.cc.
                                  {
  SetInstanceMemory(*trusted_instance_data, memory->array_buffer(),
                    memory_index_in_instance);
  if (!shared_trusted_instance_data.is_null()) {
    SetInstanceMemory(*shared_trusted_instance_data, memory->array_buffer(),
                      memory_index_in_instance);
  }
  DirectHandle<WeakArrayList> instances{memory->instances(), isolate};
  auto weak_instance_object = MaybeObjectDirectHandle::Weak(
      trusted_instance_data->instance_object(), isolate);
  instances = WeakArrayList::Append(isolate, instances, weak_instance_object);
  memory->set_instances(*instances);
}
References v8::internal::WeakArrayList::Append(), v8::internal::DirectHandle< T >::is_null(), v8::internal::anonymous_namespace{wasm-objects.cc}::SetInstanceMemory(), and v8::internal::MaybeObjectDirectHandle::Weak().
Referenced by v8::internal::wasm::InstanceBuilder::Build_Phase1_Infallible().
Member Data Documentation
kNoMaximum
constexpr int v8::internal::WasmMemoryObject::kNoMaximum = -1 [static], [constexpr]
Definition at line 427 of file wasm-objects.h.
Referenced by v8::internal::wasm::InstanceBuilder::AllocateMemory(), New(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryImpl().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-objects.h
/mnt/V8SourceCode/src/wasm/wasm-objects-inl.h
/mnt/V8SourceCode/src/wasm/wasm-objects.cc