v8::internal::maglev::GetKeyedGeneric Class Reference
#include <maglev-ir.h>
Public Member Functions
GetKeyedGeneric (uint64_t bitfield, const compiler::FeedbackSource &feedback)
compiler::FeedbackSource feedback () const
Input & context ()
Input & object_input ()
Input & key_input ()
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties = OpProperties::JSCall()
static constexpr Base::InputTypes kInputTypes
static constexpr int kContextIndex = 0
static constexpr int kObjectIndex = 1
static constexpr int kKeyIndex = 2
Private Types
using Base = FixedInputValueNodeT< 3, GetKeyedGeneric >
Private Attributes
const compiler::FeedbackSource feedback_
Additional Inherited Members
Detailed Description
Definition at line 9654 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::GetKeyedGeneric::Base = FixedInputValueNodeT<3, GetKeyedGeneric> [private]
Definition at line 9655 of file maglev-ir.h.
Constructor & Destructor Documentation
GetKeyedGeneric()
v8::internal::maglev::GetKeyedGeneric::GetKeyedGeneric (uint64_t bitfield, const compiler::FeedbackSource & feedback) [inline], [explicit]
Definition at line 9658 of file maglev-ir.h.
      : Base(bitfield), feedback_(feedback) {}
Member Function Documentation
context()
Input& v8::internal::maglev::GetKeyedGeneric::context () [inline]
Definition at line 9673 of file maglev-ir.h.
{ return input(kContextIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
feedback()
compiler::FeedbackSource v8::internal::maglev::GetKeyedGeneric::feedback () const [inline]
Definition at line 9668 of file maglev-ir.h.
{ return feedback_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::GetKeyedGeneric::GenerateCode (MaglevAssembler * , const ProcessingState &)
key_input()
Input& v8::internal::maglev::GetKeyedGeneric::key_input () [inline]
Definition at line 9675 of file maglev-ir.h.
{ return input(kKeyIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
MaxCallStackArgs()
int v8::internal::maglev::GetKeyedGeneric::MaxCallStackArgs () const
object_input()
Input& v8::internal::maglev::GetKeyedGeneric::object_input () [inline]
Definition at line 9674 of file maglev-ir.h.
{ return input(kObjectIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::GetKeyedGeneric::PrintParams (std::ostream & , MaglevGraphLabeller *) const [inline]
Definition at line 9680 of file maglev-ir.h.
{}
SetValueLocationConstraints()
void v8::internal::maglev::GetKeyedGeneric::SetValueLocationConstraints ()
Member Data Documentation
feedback_
const compiler::FeedbackSource v8::internal::maglev::GetKeyedGeneric::feedback_ [private]
Definition at line 9683 of file maglev-ir.h.
kContextIndex
constexpr int v8::internal::maglev::GetKeyedGeneric::kContextIndex = 0 [static], [constexpr]
Definition at line 9670 of file maglev-ir.h.
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::GetKeyedGeneric::kInputTypes [static], [constexpr]
Initial value:
{
      ValueRepresentation::kTagged, ValueRepresentation::kTagged,
      ValueRepresentation::kTagged}
Definition at line 9664 of file maglev-ir.h.
kKeyIndex
constexpr int v8::internal::maglev::GetKeyedGeneric::kKeyIndex = 2 [static], [constexpr]
Definition at line 9672 of file maglev-ir.h.
kObjectIndex
constexpr int v8::internal::maglev::GetKeyedGeneric::kObjectIndex = 1 [static], [constexpr]
Definition at line 9671 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::GetKeyedGeneric::kProperties = OpProperties::JSCall() [static], [constexpr]
Definition at line 9663 of file maglev-ir.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h