v8::internal::StoreHandler Class Reference
#include <handler-configuration.h>
Public Types
enum class Kind {
kField
, kConstField
, kAccessorFromPrototype
, kNativeDataProperty
,
kSharedStructField
, kApiSetter
, kGlobalProxy
, kNormal
,
kInterceptor
, kSlow
, kProxy
, kGeneric
,
kKindsNumber
 }
using KindBits = base::BitField< Kind, 0, 4 >
using DoAccessCheckOnLookupStartObjectBits = KindBits::Next< bool, 1 >
using LookupOnLookupStartObjectBits = DoAccessCheckOnLookupStartObjectBits::Next< bool, 1 >
using DescriptorBits = LookupOnLookupStartObjectBits::Next< unsigned, kDescriptorIndexBitCount >
using KeyedAccessStoreModeBits = LookupOnLookupStartObjectBits::Next< KeyedAccessStoreMode, 2 >
using IsInobjectBits = DescriptorBits::Next< bool, 1 >
using RepresentationBits = IsInobjectBits::Next< Representation::Kind, 3 >
using FieldIndexBits = RepresentationBits::Next< unsigned, kDescriptorIndexBitCount+1 >
Static Public Member Functions
static Handle< Smi > StoreField (Isolate *isolate, int descriptor, FieldIndex field_index, PropertyConstness constness, Representation representation)
static Handle< Smi > StoreSharedStructField (Isolate *isolate, int descriptor, FieldIndex field_index, Representation representation)
static MaybeObjectHandle StoreOwnTransition (Isolate *isolate, Handle< Map > transition_map)
static MaybeObjectHandle StoreTransition (Isolate *isolate, Handle< Map > transition_map)
static Handle< Smi > StoreNativeDataProperty (Isolate *isolate, int descriptor)
static DirectHandle< Smi > StoreAccessorFromPrototype (Isolate *isolate)
static DirectHandle< Smi > StoreApiSetter (Isolate *isolate)
static Handle< Object > StoreThroughPrototype (Isolate *isolate, DirectHandle< Map > receiver_map, DirectHandle< JSReceiver > holder, Tagged< Smi > smi_handler, MaybeObjectDirectHandle maybe_data1=MaybeObjectDirectHandle(), MaybeObjectDirectHandle maybe_data2=MaybeObjectDirectHandle())
static Handle< Object > StoreElementTransition (Isolate *isolate, DirectHandle< Map > receiver_map, DirectHandle< Map > transition, KeyedAccessStoreMode store_mode, MaybeDirectHandle< UnionOf< Smi, Cell >> prev_validity_cell=kNullMaybeHandle)
static Handle< Object > StoreProxy (Isolate *isolate, DirectHandle< Map > receiver_map, Handle< JSProxy > proxy, DirectHandle< JSReceiver > receiver)
static MaybeObjectHandle StoreGlobal (Handle< PropertyCell > cell)
static DirectHandle< Smi > StoreGlobalProxy (Isolate *isolate)
static Handle< Smi > StoreNormal (Isolate *isolate)
static Handle< Smi > StoreInterceptor (Isolate *isolate)
static Handle< Code > StoreSloppyArgumentsBuiltin (Isolate *isolate, KeyedAccessStoreMode mode)
static Handle< Code > StoreFastElementBuiltin (Isolate *isolate, KeyedAccessStoreMode mode)
static DirectHandle< Code > ElementsTransitionAndStoreBuiltin (Isolate *isolate, KeyedAccessStoreMode mode)
static Handle< Smi > StoreSlow (Isolate *isolate, KeyedAccessStoreMode store_mode=KeyedAccessStoreMode::kInBounds)
static Handle< Smi > StoreGeneric (Isolate *isolate)
static Tagged< Smi > StoreGeneric ()
static Handle< Smi > StoreProxy (Isolate *isolate)
static Tagged< Smi > StoreProxy ()
static KeyedAccessStoreMode GetKeyedAccessStoreMode (Tagged< MaybeObject > handler)
Static Private Member Functions
static Handle< Smi > StoreField (Isolate *isolate, Kind kind, int descriptor, FieldIndex field_index, Representation representation)
Additional Inherited Members
Detailed Description
Definition at line 250 of file handler-configuration.h.
Member Typedef Documentation
DescriptorBits
using v8::internal::StoreHandler::DescriptorBits = LookupOnLookupStartObjectBits::Next<unsigned, kDescriptorIndexBitCount>
Definition at line 286 of file handler-configuration.h.
DoAccessCheckOnLookupStartObjectBits
using v8::internal::StoreHandler::DoAccessCheckOnLookupStartObjectBits = KindBits::Next<bool, 1>
Definition at line 275 of file handler-configuration.h.
FieldIndexBits
using v8::internal::StoreHandler::FieldIndexBits = RepresentationBits::Next<unsigned, kDescriptorIndexBitCount + 1>
Definition at line 301 of file handler-configuration.h.
IsInobjectBits
using v8::internal::StoreHandler::IsInobjectBits = DescriptorBits::Next<bool, 1>
Definition at line 298 of file handler-configuration.h.
KeyedAccessStoreModeBits
using v8::internal::StoreHandler::KeyedAccessStoreModeBits = LookupOnLookupStartObjectBits::Next<KeyedAccessStoreMode, 2>
Definition at line 292 of file handler-configuration.h.
KindBits
using v8::internal::StoreHandler::KindBits = base::BitField<Kind, 0, 4>
Definition at line 270 of file handler-configuration.h.
LookupOnLookupStartObjectBits
using v8::internal::StoreHandler::LookupOnLookupStartObjectBits = DoAccessCheckOnLookupStartObjectBits::Next<bool, 1>
Definition at line 280 of file handler-configuration.h.
RepresentationBits
using v8::internal::StoreHandler::RepresentationBits = IsInobjectBits::Next<Representation::Kind, 3>
Definition at line 299 of file handler-configuration.h.
Member Enumeration Documentation
Kind
enum v8::internal::StoreHandler::Kind [strong]
Enumerator
kField
kConstField
kAccessorFromPrototype
kNativeDataProperty
kSharedStructField
kApiSetter
kGlobalProxy
kNormal
kInterceptor
kSlow
kProxy
kGeneric
kKindsNumber
Definition at line 255 of file handler-configuration.h.
                  {
    kField,
    kConstField,
    kAccessorFromPrototype,
    kNativeDataProperty,
    kSharedStructField,
    kApiSetter,
    kGlobalProxy,
    kNormal,
    kInterceptor,
    kSlow,
    kProxy,
    kGeneric, // Used for keyed stores with "1 map, many property names".
    kKindsNumber // Keep last
  };
Member Function Documentation
ElementsTransitionAndStoreBuiltin()
DirectHandle< Code > v8::internal::StoreHandler::ElementsTransitionAndStoreBuiltin (Isolate * isolate, KeyedAccessStoreMode mode) [inline], [static]
Definition at line 205 of file handler-configuration-inl.h.
                                                 {
  switch (mode) {
    case KeyedAccessStoreMode::kInBounds:
      return BUILTIN_CODE(isolate, ElementsTransitionAndStore_InBounds);
    case KeyedAccessStoreMode::kGrowAndHandleCOW:
      return BUILTIN_CODE(
          isolate, ElementsTransitionAndStore_NoTransitionGrowAndHandleCOW);
    case KeyedAccessStoreMode::kIgnoreTypedArrayOOB:
      return BUILTIN_CODE(
          isolate, ElementsTransitionAndStore_NoTransitionIgnoreTypedArrayOOB);
    case KeyedAccessStoreMode::kHandleCOW:
      return BUILTIN_CODE(isolate,
                          ElementsTransitionAndStore_NoTransitionHandleCOW);
    default:
      UNREACHABLE();
  }
}
References BUILTIN_CODE, v8::internal::kGrowAndHandleCOW, v8::internal::kHandleCOW, v8::internal::kIgnoreTypedArrayOOB, v8::internal::kInBounds, mode(), and v8::internal::UNREACHABLE().
Referenced by StoreElementTransition().
GetKeyedAccessStoreMode()
KeyedAccessStoreMode v8::internal::StoreHandler::GetKeyedAccessStoreMode (Tagged< MaybeObject > handler) [static]
Definition at line 261 of file handler-configuration.cc.
                                 {
  DisallowGarbageCollection no_gc;
  if (IsSmi(handler)) {
    int const raw_handler = handler.ToSmi().value();
    Kind const kind = KindBits::decode(raw_handler);
    // All the handlers except the Slow Handler that use tshe
    // KeyedAccessStoreMode, compute it using KeyedAccessStoreModeForBuiltin
    // method. Hence if any other Handler get to this path, just return
    // KeyedAccessStoreMode::kInBounds.
    if (kind != Kind::kSlow) {
      return KeyedAccessStoreMode::kInBounds;
    }
    KeyedAccessStoreMode store_mode =
        KeyedAccessStoreModeBits::decode(raw_handler);
    return store_mode;
  }
  return KeyedAccessStoreMode::kInBounds;
}
References v8::base::BitField< T, shift, size, U >::decode(), v8::internal::IsSmi(), v8::internal::kInBounds, kSlow, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::TaggedImpl< kRefType, StorageType >::ToSmi().
Referenced by v8::internal::FeedbackNexus::GetKeyedAccessStoreMode().
StoreAccessorFromPrototype()
DirectHandle< Smi > v8::internal::StoreHandler::StoreAccessorFromPrototype (Isolate * isolate) [inline], [static]
Definition at line 287 of file handler-configuration-inl.h.
                                                                           {
  int config = KindBits::encode(Kind::kAccessorFromPrototype);
  return direct_handle(Smi::FromInt(config), isolate);
}
References v8::internal::direct_handle(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::Smi::FromInt(), and kAccessorFromPrototype.
Referenced by v8::internal::StoreIC::ComputeHandler().
StoreApiSetter()
DirectHandle< Smi > v8::internal::StoreHandler::StoreApiSetter (Isolate * isolate) [inline], [static]
Definition at line 292 of file handler-configuration-inl.h.
                                                               {
  int config = KindBits::encode(Kind::kApiSetter);
  return direct_handle(Smi::FromInt(config), isolate);
}
References v8::internal::direct_handle(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::Smi::FromInt(), and kApiSetter.
Referenced by v8::internal::StoreIC::ComputeHandler().
StoreElementTransition()
Handle< Object > v8::internal::StoreHandler::StoreElementTransition (Isolate * isolate, DirectHandle< Map > receiver_map, DirectHandle< Map > transition, KeyedAccessStoreMode store_mode, MaybeDirectHandle< UnionOf< Smi, Cell >> prev_validity_cell = kNullMaybeHandle) [static]
Definition at line 282 of file handler-configuration.cc.
                                                              {
  DirectHandle<Code> code =
      ElementsTransitionAndStoreBuiltin(isolate, store_mode);
  DirectHandle<UnionOf<Smi, Cell>> validity_cell;
  if (!prev_validity_cell.ToHandle(&validity_cell)) {
    validity_cell =
        Map::GetOrCreatePrototypeChainValidityCell(receiver_map, isolate);
  }
  Handle<StoreHandler> handler = isolate->factory()->NewStoreHandler(1);
  handler->set_smi_handler(*code);
  handler->set_validity_cell(*validity_cell);
  handler->set_data1(MakeWeak(*transition));
  return handler;
}
References code, ElementsTransitionAndStoreBuiltin(), v8::internal::Isolate::factory(), v8::internal::Map::GetOrCreatePrototypeChainValidityCell(), v8::internal::MakeWeak(), v8::internal::Factory::NewStoreHandler(), and v8::internal::DataHandler::validity_cell().
Referenced by v8::internal::KeyedStoreIC::StoreElementPolymorphicHandlers().
StoreFastElementBuiltin()
Handle< Code > v8::internal::StoreHandler::StoreFastElementBuiltin (Isolate * isolate, KeyedAccessStoreMode mode) [inline], [static]
Definition at line 187 of file handler-configuration-inl.h.
                                                                              {
  switch (mode) {
    case KeyedAccessStoreMode::kInBounds:
      return BUILTIN_CODE(isolate, StoreFastElementIC_InBounds);
    case KeyedAccessStoreMode::kGrowAndHandleCOW:
      return BUILTIN_CODE(isolate,
                          StoreFastElementIC_NoTransitionGrowAndHandleCOW);
    case KeyedAccessStoreMode::kIgnoreTypedArrayOOB:
      return BUILTIN_CODE(isolate,
                          StoreFastElementIC_NoTransitionIgnoreTypedArrayOOB);
    case KeyedAccessStoreMode::kHandleCOW:
      return BUILTIN_CODE(isolate, StoreFastElementIC_NoTransitionHandleCOW);
    default:
      UNREACHABLE();
  }
}
References BUILTIN_CODE, v8::internal::kGrowAndHandleCOW, v8::internal::kHandleCOW, v8::internal::kIgnoreTypedArrayOOB, v8::internal::kInBounds, mode(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::KeyedStoreIC::StoreElementHandler().
StoreField() [1/2]
Handle< Smi > v8::internal::StoreHandler::StoreField (Isolate * isolate, int descriptor, FieldIndex field_index, PropertyConstness constness, Representation representation) [inline], [static]
Definition at line 263 of file handler-configuration-inl.h.
                                                                    {
  Kind kind = constness == PropertyConstness::kMutable ? Kind::kField
                                                       : Kind::kConstField;
  return StoreField(isolate, kind, descriptor, field_index, representation);
}
References kConstField, kField, and v8::internal::kMutable.
Referenced by v8::internal::StoreIC::ComputeHandler(), and StoreSharedStructField().
StoreField() [2/2]
Handle< Smi > v8::internal::StoreHandler::StoreField (Isolate * isolate, Kind kind, int descriptor, FieldIndex field_index, Representation representation) [inline], [static], [private]
Definition at line 248 of file handler-configuration-inl.h.
                                                                    {
  DCHECK(!representation.IsNone());
  DCHECK(kind == Kind::kField || kind == Kind::kConstField ||
         kind == Kind::kSharedStructField);
  int config = KindBits::encode(kind) |
               IsInobjectBits::encode(field_index.is_inobject()) |
               RepresentationBits::encode(representation.kind()) |
               DescriptorBits::encode(descriptor) |
               FieldIndexBits::encode(field_index.index());
  return handle(Smi::FromInt(config), isolate);
}
References v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::Smi::FromInt(), v8::internal::handle(), v8::internal::FieldIndex::index(), v8::internal::FieldIndex::is_inobject(), v8::internal::Representation::IsNone(), kConstField, kField, v8::internal::Representation::kind(), and kSharedStructField.
StoreGeneric() [1/2]
Tagged< Smi > v8::internal::StoreHandler::StoreGeneric () [inline], [static]
Definition at line 235 of file handler-configuration-inl.h.
                                       {
  return Smi::FromInt(KindBits::encode(Kind::kGeneric));
}
References v8::base::BitField< T, shift, size, U >::encode(), v8::internal::Smi::FromInt(), and kGeneric.
Referenced by v8::internal::FeedbackNexus::IsOneMapManyNames(), StoreGeneric(), and v8::internal::IC::UpdateOneMapManyNamesIC().
StoreGeneric() [2/2]
Handle< Smi > v8::internal::StoreHandler::StoreGeneric (Isolate * isolate) [inline], [static]
Definition at line 231 of file handler-configuration-inl.h.
                                                       {
  return handle(StoreGeneric(), isolate);
}
References v8::internal::handle(), and StoreGeneric().
StoreGlobal()
MaybeObjectHandle v8::internal::StoreHandler::StoreGlobal (Handle< PropertyCell > cell) [static]
Definition at line 415 of file handler-configuration.cc.
                                                                     {
  return MaybeObjectHandle::Weak(cell);
}
References v8::internal::MaybeObjectHandle::Weak().
Referenced by v8::internal::StoreIC::ComputeHandler().
StoreGlobalProxy()
DirectHandle< Smi > v8::internal::StoreHandler::StoreGlobalProxy (Isolate * isolate) [inline], [static]
Definition at line 152 of file handler-configuration-inl.h.
                                                                 {
  int config = KindBits::encode(Kind::kGlobalProxy);
  return direct_handle(Smi::FromInt(config), isolate);
}
References v8::internal::direct_handle(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::Smi::FromInt(), and kGlobalProxy.
Referenced by v8::internal::StoreIC::ComputeHandler().
StoreInterceptor()
Handle< Smi > v8::internal::StoreHandler::StoreInterceptor (Isolate * isolate) [inline], [static]
Definition at line 162 of file handler-configuration-inl.h.
                                                           {
  int config = KindBits::encode(Kind::kInterceptor);
  return handle(Smi::FromInt(config), isolate);
}
References v8::base::BitField< T, shift, size, U >::encode(), v8::internal::Smi::FromInt(), v8::internal::handle(), and kInterceptor.
Referenced by v8::internal::StoreIC::ComputeHandler().
StoreNativeDataProperty()
Handle< Smi > v8::internal::StoreHandler::StoreNativeDataProperty (Isolate * isolate, int descriptor) [inline], [static]
Definition at line 280 of file handler-configuration-inl.h.
                                                                  {
  int config = KindBits::encode(Kind::kNativeDataProperty) |
               DescriptorBits::encode(descriptor);
  return handle(Smi::FromInt(config), isolate);
}
References v8::base::BitField< T, shift, size, U >::encode(), v8::internal::Smi::FromInt(), v8::internal::handle(), and kNativeDataProperty.
Referenced by v8::internal::StoreIC::ComputeHandler().
StoreNormal()
Handle< Smi > v8::internal::StoreHandler::StoreNormal (Isolate * isolate) [inline], [static]
Definition at line 157 of file handler-configuration-inl.h.
                                                      {
  int config = KindBits::encode(Kind::kNormal);
  return handle(Smi::FromInt(config), isolate);
}
References v8::base::BitField< T, shift, size, U >::encode(), v8::internal::Smi::FromInt(), v8::internal::handle(), and kNormal.
Referenced by v8::internal::StoreIC::ComputeHandler().
StoreOwnTransition()
MaybeObjectHandle v8::internal::StoreHandler::StoreOwnTransition (Isolate * isolate, Handle< Map > transition_map) [static]
Definition at line 301 of file handler-configuration.cc.
                                                                               {
  bool is_dictionary_map = transition_map->is_dictionary_map();
#ifdef DEBUG
  if (!is_dictionary_map) {
    InternalIndex descriptor = transition_map->LastAdded();
    DirectHandle<DescriptorArray> descriptors(
        transition_map->instance_descriptors(isolate), isolate);
    PropertyDetails details = descriptors->GetDetails(descriptor);
    if (descriptors->GetKey(descriptor)->IsPrivate()) {
      DCHECK_EQ(DONT_ENUM, details.attributes());
    } else {
      DCHECK_EQ(NONE, details.attributes());
    }
    Representation representation = details.representation();
    DCHECK(!representation.IsNone());
  }
#endif
  // Declarative handlers don't support access checks.
  DCHECK(!transition_map->is_access_check_needed());
  // StoreOwnTransition does not involve any prototype checks.
  if (is_dictionary_map) {
    DCHECK(!IsJSGlobalObjectMap(*transition_map));
    int config = KindBits::encode(Kind::kNormal);
    return MaybeObjectHandle(Tagged<Object>(Smi::FromInt(config)), isolate);
  } else {
    return MaybeObjectHandle::Weak(transition_map);
  }
}
References v8::internal::PropertyDetails::attributes(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::DONT_ENUM, v8::base::BitField< T, shift, size, U >::encode(), v8::internal::Smi::FromInt(), v8::internal::Representation::IsNone(), kNormal, v8::internal::NONE, v8::internal::PropertyDetails::representation(), and v8::internal::MaybeObjectHandle::Weak().
Referenced by v8::internal::StoreIC::ComputeHandler().
StoreProxy() [1/3]
Tagged< Smi > v8::internal::StoreHandler::StoreProxy () [inline], [static]
Definition at line 243 of file handler-configuration-inl.h.
                                     {
  int config = KindBits::encode(Kind::kProxy);
  return Smi::FromInt(config);
}
References v8::base::BitField< T, shift, size, U >::encode(), v8::internal::Smi::FromInt(), and kProxy.
Referenced by v8::internal::StoreIC::ComputeHandler(), v8::internal::FeedbackNexus::GetKeyedAccessStoreMode(), v8::internal::KeyedStoreIC::StoreElementHandler(), and StoreProxy().
StoreProxy() [2/3]
Handle< Smi > v8::internal::StoreHandler::StoreProxy (Isolate * isolate) [inline], [static]
Definition at line 239 of file handler-configuration-inl.h.
                                                     {
  return handle(StoreProxy(), isolate);
}
References v8::internal::handle(), and StoreProxy().
StoreProxy() [3/3]
Handle< Object > v8::internal::StoreHandler::StoreProxy (Isolate * isolate, DirectHandle< Map > receiver_map, Handle< JSProxy > proxy, DirectHandle< JSReceiver > receiver) [static]
Definition at line 420 of file handler-configuration.cc.
                                                                           {
  Handle<Smi> smi_handler = StoreProxy(isolate);
  if (receiver.is_identical_to(proxy)) return smi_handler;
  return StoreThroughPrototype(isolate, receiver_map, proxy, *smi_handler,
                               MaybeObjectDirectHandle::Weak(proxy));
}
References v8::internal::DirectHandle< T >::is_identical_to(), v8::internal::DataHandler::smi_handler(), StoreProxy(), StoreThroughPrototype(), and v8::internal::MaybeObjectDirectHandle::Weak().
StoreSharedStructField()
Handle< Smi > v8::internal::StoreHandler::StoreSharedStructField (Isolate * isolate, int descriptor, FieldIndex field_index, Representation representation) [inline], [static]
Definition at line 272 of file handler-configuration-inl.h.
                                   {
  DCHECK(representation.Equals(Representation::Tagged()));
  return StoreField(isolate, Kind::kSharedStructField, descriptor, field_index,
                    representation);
}
References v8::internal::DCHECK(), v8::internal::Representation::Equals(), kSharedStructField, StoreField(), and v8::internal::Representation::Tagged().
Referenced by v8::internal::StoreIC::ComputeHandler().
StoreSloppyArgumentsBuiltin()
Handle< Code > v8::internal::StoreHandler::StoreSloppyArgumentsBuiltin (Isolate * isolate, KeyedAccessStoreMode mode) [inline], [static]
Definition at line 167 of file handler-configuration-inl.h.
                                                 {
  switch (mode) {
    case KeyedAccessStoreMode::kInBounds:
      return BUILTIN_CODE(isolate, KeyedStoreIC_SloppyArguments_InBounds);
    case KeyedAccessStoreMode::kGrowAndHandleCOW:
      return BUILTIN_CODE(
          isolate, KeyedStoreIC_SloppyArguments_NoTransitionGrowAndHandleCOW);
    case KeyedAccessStoreMode::kIgnoreTypedArrayOOB:
      return BUILTIN_CODE(
          isolate,
          KeyedStoreIC_SloppyArguments_NoTransitionIgnoreTypedArrayOOB);
    case KeyedAccessStoreMode::kHandleCOW:
      return BUILTIN_CODE(isolate,
                          KeyedStoreIC_SloppyArguments_NoTransitionHandleCOW);
    default:
      UNREACHABLE();
  }
}
References BUILTIN_CODE, v8::internal::kGrowAndHandleCOW, v8::internal::kHandleCOW, v8::internal::kIgnoreTypedArrayOOB, v8::internal::kInBounds, mode(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::KeyedStoreIC::StoreElementHandler().
StoreSlow()
Handle< Smi > v8::internal::StoreHandler::StoreSlow (Isolate * isolate, KeyedAccessStoreMode store_mode = KeyedAccessStoreMode::kInBounds) [inline], [static]
Definition at line 224 of file handler-configuration-inl.h.
                                                                     {
  int config = KindBits::encode(Kind::kSlow) |
               KeyedAccessStoreModeBits::encode(store_mode);
  return handle(Smi::FromInt(config), isolate);
}
References v8::base::BitField< T, shift, size, U >::encode(), v8::internal::Smi::FromInt(), v8::internal::handle(), and kSlow.
Referenced by v8::internal::StoreIC::ComputeHandler(), v8::internal::StoreIC::Store(), v8::internal::StoreGlobalIC::Store(), v8::internal::KeyedStoreIC::StoreElementHandler(), v8::internal::KeyedStoreIC::StoreElementPolymorphicHandlers(), and v8::internal::StoreIC::UpdateCaches().
StoreThroughPrototype()
Handle< Object > v8::internal::StoreHandler::StoreThroughPrototype (Isolate * isolate, DirectHandle< Map > receiver_map, DirectHandle< JSReceiver > holder, Tagged< Smi > smi_handler, MaybeObjectDirectHandle maybe_data1 = MaybeObjectDirectHandle(), MaybeObjectDirectHandle maybe_data2 = MaybeObjectDirectHandle()) [static]
Definition at line 388 of file handler-configuration.cc.
                                                                              {
  MaybeObjectDirectHandle data1;
  if (maybe_data1.is_null()) {
    data1 = MaybeObjectDirectHandle::Weak(holder);
  } else {
    data1 = maybe_data1;
  }
  int data_size = GetHandlerDataSize<StoreHandler>(
      isolate, &smi_handler, receiver_map, data1, maybe_data2);
  DirectHandle<UnionOf<Smi, Cell>> validity_cell =
      Map::GetOrCreatePrototypeChainValidityCell(receiver_map, isolate);
  Handle<StoreHandler> handler = isolate->factory()->NewStoreHandler(data_size);
  handler->set_smi_handler(smi_handler);
  handler->set_validity_cell(*validity_cell);
  InitPrototypeChecks(isolate, direct_handle(handler), receiver_map, data1,
                      maybe_data2);
  return handler;
}
References v8::internal::DataHandler::data1(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::Map::GetOrCreatePrototypeChainValidityCell(), v8::internal::anonymous_namespace{handler-configuration.cc}::InitPrototypeChecks(), v8::internal::MaybeObjectDirectHandle::is_null(), v8::internal::Factory::NewStoreHandler(), v8::internal::DataHandler::smi_handler(), v8::internal::DataHandler::validity_cell(), and v8::internal::MaybeObjectDirectHandle::Weak().
Referenced by v8::internal::StoreIC::ComputeHandler(), and StoreProxy().
StoreTransition()
MaybeObjectHandle v8::internal::StoreHandler::StoreTransition (Isolate * isolate, Handle< Map > transition_map) [static]
Definition at line 334 of file handler-configuration.cc.
                                                                            {
  bool is_dictionary_map = transition_map->is_dictionary_map();
  // We should not create transition handlers for fast prototype maps
  // because they are not reusable anyway.
  DCHECK_IMPLIES(transition_map->is_prototype_map(), is_dictionary_map);
#ifdef DEBUG
  if (!is_dictionary_map) {
    InternalIndex descriptor = transition_map->LastAdded();
    DirectHandle<DescriptorArray> descriptors(
        transition_map->instance_descriptors(isolate), isolate);
    // Private fields must be added via StoreOwnTransition handler.
    DCHECK(!descriptors->GetKey(descriptor)->IsPrivateName());
    PropertyDetails details = descriptors->GetDetails(descriptor);
    if (descriptors->GetKey(descriptor)->IsPrivate()) {
      DCHECK_EQ(DONT_ENUM, details.attributes());
    } else {
      DCHECK_EQ(NONE, details.attributes());
    }
    Representation representation = details.representation();
    DCHECK(!representation.IsNone());
  }
#endif
  // Declarative handlers don't support access checks.
  DCHECK(!transition_map->is_access_check_needed());
  // Get validity cell value if it is necessary for the handler.
  DirectHandle<UnionOf<Smi, Cell>> validity_cell;
  if (is_dictionary_map || !transition_map->IsPrototypeValidityCellValid()) {
    validity_cell =
        Map::GetOrCreatePrototypeChainValidityCell(transition_map, isolate);
  }
  if (is_dictionary_map) {
    DCHECK(!IsJSGlobalObjectMap(*transition_map));
    Handle<StoreHandler> handler = isolate->factory()->NewStoreHandler(0);
    // Store normal with enabled lookup on receiver.
    int config = KindBits::encode(Kind::kNormal) |
                 LookupOnLookupStartObjectBits::encode(true);
    handler->set_smi_handler(Smi::FromInt(config));
    handler->set_validity_cell(*validity_cell);
    return MaybeObjectHandle(handler);
  } else {
    // Ensure the transition map contains a valid prototype validity cell.
    if (!validity_cell.is_null()) {
      transition_map->set_prototype_validity_cell(*validity_cell,
                                                  kRelaxedStore);
    }
    return MaybeObjectHandle::Weak(transition_map);
  }
}
References v8::internal::PropertyDetails::attributes(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::DONT_ENUM, v8::base::BitField< T, shift, size, U >::encode(), v8::internal::Isolate::factory(), v8::internal::Smi::FromInt(), v8::internal::Map::GetOrCreatePrototypeChainValidityCell(), v8::internal::Representation::IsNone(), kNormal, v8::kRelaxedStore, v8::internal::Factory::NewStoreHandler(), v8::internal::NONE, v8::internal::PropertyDetails::representation(), v8::internal::DataHandler::validity_cell(), and v8::internal::MaybeObjectHandle::Weak().
Referenced by v8::internal::StoreIC::ComputeHandler().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ic/handler-configuration.h
/mnt/V8SourceCode/src/ic/handler-configuration-inl.h
/mnt/V8SourceCode/src/ic/handler-configuration.cc