v8::internal::wasm::WasmCodeRefScope Class Reference
#include <wasm-code-manager.h>
Public Member Functions
WasmCodeRefScope ()
WasmCodeRefScope (const WasmCodeRefScope &)=delete
WasmCodeRefScope & operator= (const WasmCodeRefScope &)=delete
~WasmCodeRefScope ()
Static Public Member Functions
static void AddRef (WasmCode *)
static WasmCode * AddRefIfNotDying (WasmCode *code)
Private Attributes
WasmCodeRefScope *const previous_scope_
std::vector< WasmCode * > code_ptrs_
Detailed Description
Definition at line 1277 of file wasm-code-manager.h.
Constructor & Destructor Documentation
WasmCodeRefScope() [1/2]
v8::internal::wasm::WasmCodeRefScope::WasmCodeRefScope ()
Definition at line 3033 of file wasm-code-manager.cc.
    : previous_scope_(current_code_refs_scope) {
  current_code_refs_scope = this;
}
References v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::current_code_refs_scope.
WasmCodeRefScope() [2/2]
v8::internal::wasm::WasmCodeRefScope::WasmCodeRefScope (const WasmCodeRefScope &) [delete]
 WasmCodeRefScope()
v8::internal::wasm::WasmCodeRefScope::~WasmCodeRefScope ()
Definition at line 3038 of file wasm-code-manager.cc.
                                    {
  DCHECK_EQ(this, current_code_refs_scope);
  current_code_refs_scope = previous_scope_;
  WasmCode::DecrementRefCount(base::VectorOf(code_ptrs_));
}
References code_ptrs_, v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::current_code_refs_scope, DCHECK_EQ, v8::internal::wasm::WasmCode::DecrementRefCount(), previous_scope_, and v8::base::VectorOf().
Member Function Documentation
AddRef()
void v8::internal::wasm::WasmCodeRefScope::AddRef (WasmCode * code) [static]
Definition at line 3045 of file wasm-code-manager.cc.
                                            {
  DCHECK_NOT_NULL(code);
  WasmCodeRefScope* current_scope = current_code_refs_scope;
  DCHECK_NOT_NULL(current_scope);
  current_scope->code_ptrs_.push_back(code);
  code->IncRef();
}
References code, code_ptrs_, v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::current_code_refs_scope, and DCHECK_NOT_NULL.
Referenced by v8::internal::wasm::NativeModule::GetCode(), v8::internal::wasm::WasmImportWrapperCache::Lookup(), v8::internal::wasm::NativeModule::Lookup(), v8::internal::wasm::NativeModule::PublishCodeLocked(), v8::internal::wasm::DebugInfoImpl::RecompileLiftoffWithBreakpoints(), v8::internal::wasm::NativeModule::ReinstallDebugCode(), v8::internal::wasm::NativeModule::RemoveCompiledCode(), v8::internal::wasm::WasmEngine::RemoveIsolate(), v8::internal::wasm::NativeModule::SnapshotAllOwnedCode(), and v8::internal::wasm::NativeModule::SnapshotCodeTable().
AddRefIfNotDying()
WasmCode * v8::internal::wasm::WasmCodeRefScope::AddRefIfNotDying (WasmCode * code) [static]
Definition at line 3054 of file wasm-code-manager.cc.
                                                           {
  DCHECK_NOT_NULL(code);
  WasmCodeRefScope* current_scope = current_code_refs_scope;
  DCHECK_NOT_NULL(current_scope);
  if (!code->IncRefIfNotDying()) return nullptr;
  current_scope->code_ptrs_.push_back(code);
  return code;
}
References code, code_ptrs_, v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::current_code_refs_scope, and DCHECK_NOT_NULL.
operator=()
WasmCodeRefScope& v8::internal::wasm::WasmCodeRefScope::operator= (const WasmCodeRefScope &) [delete]
Member Data Documentation
code_ptrs_
std::vector<WasmCode*> v8::internal::wasm::WasmCodeRefScope::code_ptrs_ [private]
Definition at line 1294 of file wasm-code-manager.h.
Referenced by AddRef(), AddRefIfNotDying(), and ~WasmCodeRefScope().
previous_scope_
WasmCodeRefScope* const v8::internal::wasm::WasmCodeRefScope::previous_scope_ [private]
Definition at line 1293 of file wasm-code-manager.h.
Referenced by ~WasmCodeRefScope().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-code-manager.h
/mnt/V8SourceCode/src/wasm/wasm-code-manager.cc