v8::internal::compiler::JSLoadNamedFromSuperNode Class Reference
#include <js-operator.h>
Public Member Functions
constexpr JSLoadNamedFromSuperNode (Node *node)
const NamedAccess & Parameters () const
Additional Inherited Members
Detailed Description
Definition at line 1578 of file js-operator.h.
Constructor & Destructor Documentation
JSLoadNamedFromSuperNode()
constexpr v8::internal::compiler::JSLoadNamedFromSuperNode::JSLoadNamedFromSuperNode (Node * node) [inline], [explicit], [constexpr]
Definition at line 1580 of file js-operator.h.
      : JSNodeWrapperBase(node) {
    DCHECK_EQ(IrOpcode::kJSLoadNamedFromSuper, node->opcode());
  }
References DCHECK_EQ, v8::internal::compiler::NodeWrapper::node(), and v8::internal::compiler::Node::opcode().
Member Function Documentation
Parameters()
const NamedAccess& v8::internal::compiler::JSLoadNamedFromSuperNode::Parameters () const [inline]
Definition at line 1585 of file js-operator.h.
{ return NamedAccessOf(node()->op()); }
References v8::internal::compiler::NamedAccessOf(), and v8::internal::compiler::NodeWrapper::node().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadNamedFromSuper().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h