v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer Class Reference
Static Public Member Functions
static void TraceStartBaselineCompile (Isolate *isolate, DirectHandle< SharedFunctionInfo > shared)
static void TraceStartMaglevCompile (Isolate *isolate, DirectHandle< JSFunction > function, bool osr, ConcurrencyMode mode)
static void TracePrepareJob (Isolate *isolate, OptimizedCompilationInfo *info, ConcurrencyMode mode)
static void TraceOptimizeOSRStarted (Isolate *isolate, DirectHandle< JSFunction > function, BytecodeOffset osr_offset, ConcurrencyMode mode)
static void TraceOptimizeOSRFinished (Isolate *isolate, DirectHandle< JSFunction > function, BytecodeOffset osr_offset)
static void TraceOptimizeOSRAvailable (Isolate *isolate, DirectHandle< JSFunction > function, BytecodeOffset osr_offset, ConcurrencyMode mode)
static void TraceOptimizeOSRUnavailable (Isolate *isolate, DirectHandle< JSFunction > function, BytecodeOffset osr_offset, ConcurrencyMode mode)
static void TraceFinishTurbofanCompile (Isolate *isolate, OptimizedCompilationInfo *info, double ms_creategraph, double ms_optimize, double ms_codegen)
static void TraceFinishBaselineCompile (Isolate *isolate, DirectHandle< SharedFunctionInfo > shared, double ms_timetaken)
static void TraceFinishMaglevCompile (Isolate *isolate, DirectHandle< JSFunction > function, bool osr, double ms_prepare, double ms_execute, double ms_finalize)
static void TraceAbortedMaglevCompile (Isolate *isolate, DirectHandle< JSFunction > function, BailoutReason bailout_reason)
static void TraceCompletedJob (Isolate *isolate, OptimizedCompilationInfo *info)
static void TraceAbortedJob (Isolate *isolate, OptimizedCompilationInfo *info, double ms_prepare, double ms_execute, double ms_finalize)
static void TraceOptimizedCodeCacheHit (Isolate *isolate, DirectHandle< JSFunction > function, BytecodeOffset osr_offset, CodeKind code_kind)
static void TraceOptimizeForAlwaysOpt (Isolate *isolate, DirectHandle< JSFunction > function, CodeKind code_kind)
static void TraceMarkForAlwaysOpt (Isolate *isolate, DirectHandle< JSFunction > function)
Static Private Member Functions
static void PrintTracePrefix (const CodeTracer::Scope &scope, const char *header, OptimizedCompilationInfo *info)
static void PrintTracePrefix (const CodeTracer::Scope &scope, const char *header, DirectHandle< JSFunction > function, CodeKind code_kind)
static void PrintTracePrefix (const CodeTracer::Scope &scope, const char *header, DirectHandle< SharedFunctionInfo > shared, CodeKind code_kind)
static void PrintTraceSuffix (const CodeTracer::Scope &scope)
Detailed Description
Definition at line 85 of file compiler.cc.
Member Function Documentation
PrintTracePrefix() [1/3]
static void v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::PrintTracePrefix (const CodeTracer::Scope & scope, const char * header, DirectHandle< JSFunction > function, CodeKind code_kind) [inline], [static], [private]
Definition at line 274 of file compiler.cc.
                                                   {
    PrintF(scope.file(), "[%s ", header);
    ShortPrint(*function, scope.file());
    PrintF(scope.file(), " (target %s)", CodeKindToString(code_kind));
  }
References v8::internal::CodeKindToString(), v8::internal::CodeTracer::Scope::file(), v8::internal::PrintF(), and v8::internal::ShortPrint().
PrintTracePrefix() [2/3]
static void v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::PrintTracePrefix (const CodeTracer::Scope & scope, const char * header, DirectHandle< SharedFunctionInfo > shared, CodeKind code_kind) [inline], [static], [private]
Definition at line 283 of file compiler.cc.
                                                   {
    PrintF(scope.file(), "[%s ", header);
    ShortPrint(*shared, scope.file());
    PrintF(scope.file(), " (target %s)", CodeKindToString(code_kind));
  }
References v8::internal::CodeKindToString(), v8::internal::CodeTracer::Scope::file(), v8::internal::PrintF(), and v8::internal::ShortPrint().
PrintTracePrefix() [3/3]
static void v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::PrintTracePrefix (const CodeTracer::Scope & scope, const char * header, OptimizedCompilationInfo * info) [inline], [static], [private]
Definition at line 268 of file compiler.cc.
                                                               {
    PrintTracePrefix(scope, header, info->closure(), info->code_kind());
  }
References v8::internal::OptimizedCompilationInfo::closure(), and v8::internal::OptimizedCompilationInfo::code_kind().
PrintTraceSuffix()
static void v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::PrintTraceSuffix (const CodeTracer::Scope & scope) [inline], [static], [private]
Definition at line 292 of file compiler.cc.
                                                             {
    PrintF(scope.file(), "]\n");
  }
References v8::internal::CodeTracer::Scope::file(), and v8::internal::PrintF().
TraceAbortedJob()
static void v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceAbortedJob (Isolate * isolate, OptimizedCompilationInfo * info, double ms_prepare, double ms_execute, double ms_finalize) [inline], [static]
Definition at line 219 of file compiler.cc.
                                                  {
    if (!v8_flags.trace_opt) return;
    CodeTracer::Scope scope(isolate->GetCodeTracer());
    PrintTracePrefix(scope, "aborted optimizing", info);
    if (info->is_osr()) PrintF(scope.file(), " OSR");
    PrintF(scope.file(), " because: %s",
           GetBailoutReason(info->bailout_reason()));
    PrintF(scope.file(), " - took %0.3f, %0.3f, %0.3f ms", ms_prepare,
           ms_execute, ms_finalize);
    PrintTraceSuffix(scope);
  }
References v8::internal::OptimizedCompilationInfo::bailout_reason(), v8::internal::CodeTracer::Scope::file(), v8::internal::GetBailoutReason(), v8::internal::Isolate::GetCodeTracer(), v8::internal::OptimizedCompilationInfo::is_osr(), v8::internal::PrintF(), and v8::internal::v8_flags.
TraceAbortedMaglevCompile()
static void v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceAbortedMaglevCompile (Isolate * isolate, DirectHandle< JSFunction > function, BailoutReason bailout_reason) [inline], [static]
Definition at line 200 of file compiler.cc.
                                                                      {
    if (!v8_flags.trace_opt) return;
    CodeTracer::Scope scope(isolate->GetCodeTracer());
    PrintTracePrefix(scope, "aborted compiling", function, CodeKind::MAGLEV);
    PrintF(scope.file(), " because: %s", GetBailoutReason(bailout_reason));
    PrintTraceSuffix(scope);
  }
References v8::internal::CodeTracer::Scope::file(), v8::internal::GetBailoutReason(), v8::internal::Isolate::GetCodeTracer(), v8::internal::PrintF(), and v8::internal::v8_flags.
TraceCompletedJob()
static void v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceCompletedJob (Isolate * isolate, OptimizedCompilationInfo * info) [inline], [static]
Definition at line 210 of file compiler.cc.
                                                                {
    if (!v8_flags.trace_opt) return;
    CodeTracer::Scope scope(isolate->GetCodeTracer());
    PrintTracePrefix(scope, "completed optimizing", info);
    if (info->is_osr()) PrintF(scope.file(), " OSR");
    PrintTraceSuffix(scope);
  }
References v8::internal::CodeTracer::Scope::file(), v8::internal::Isolate::GetCodeTracer(), v8::internal::OptimizedCompilationInfo::is_osr(), v8::internal::PrintF(), and v8::internal::v8_flags.
TraceFinishBaselineCompile()
static void v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceFinishBaselineCompile (Isolate * isolate, DirectHandle< SharedFunctionInfo > shared, double ms_timetaken) [inline], [static]
Definition at line 177 of file compiler.cc.
                           {
    if (!v8_flags.trace_baseline) return;
    CodeTracer::Scope scope(isolate->GetCodeTracer());
    PrintTracePrefix(scope, "completed compiling", shared, CodeKind::BASELINE);
    PrintF(scope.file(), " - took %0.3f ms", ms_timetaken);
    PrintTraceSuffix(scope);
  }
References v8::internal::CodeTracer::Scope::file(), v8::internal::Isolate::GetCodeTracer(), v8::internal::PrintF(), and v8::internal::v8_flags.
TraceFinishMaglevCompile()
static void v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceFinishMaglevCompile (Isolate * isolate, DirectHandle< JSFunction > function, bool osr, double ms_prepare, double ms_execute, double ms_finalize) [inline], [static]
Definition at line 187 of file compiler.cc.
                                                                              {
    if (!v8_flags.trace_opt) return;
    CodeTracer::Scope scope(isolate->GetCodeTracer());
    PrintTracePrefix(scope, "completed compiling", function, CodeKind::MAGLEV);
    if (osr) PrintF(scope.file(), " OSR");
    PrintF(scope.file(), " - took %0.3f, %0.3f, %0.3f ms", ms_prepare,
           ms_execute, ms_finalize);
    PrintTraceSuffix(scope);
  }
References v8::internal::CodeTracer::Scope::file(), v8::internal::Isolate::GetCodeTracer(), v8::internal::PrintF(), and v8::internal::v8_flags.
TraceFinishTurbofanCompile()
static void v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceFinishTurbofanCompile (Isolate * isolate, OptimizedCompilationInfo * info, double ms_creategraph, double ms_optimize, double ms_codegen) [inline], [static]
Definition at line 162 of file compiler.cc.
                                                            {
    DCHECK(v8_flags.trace_opt);
    DCHECK(info->IsOptimizing());
    CodeTracer::Scope scope(isolate->GetCodeTracer());
    PrintTracePrefix(scope, "completed compiling", info);
    if (info->is_osr()) PrintF(scope.file(), " OSR");
    PrintF(scope.file(), " - took %0.3f, %0.3f, %0.3f ms", ms_creategraph,
           ms_optimize, ms_codegen);
    PrintTraceSuffix(scope);
  }
References v8::internal::DCHECK(), v8::internal::CodeTracer::Scope::file(), v8::internal::Isolate::GetCodeTracer(), v8::internal::OptimizedCompilationInfo::is_osr(), v8::internal::OptimizedCompilationInfo::IsOptimizing(), v8::internal::PrintF(), and v8::internal::v8_flags.
TraceMarkForAlwaysOpt()
static void v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceMarkForAlwaysOpt (Isolate * isolate, DirectHandle< JSFunction > function) [inline], [static]
Definition at line 256 of file compiler.cc.
                                                                       {
    if (!v8_flags.trace_opt) return;
    CodeTracer::Scope scope(isolate->GetCodeTracer());
    PrintF(scope.file(), "[marking ");
    ShortPrint(*function, scope.file());
    PrintF(scope.file(),
           " for optimized recompilation because --always-turbofan");
    PrintF(scope.file(), "]\n");
  }
References v8::internal::CodeTracer::Scope::file(), v8::internal::Isolate::GetCodeTracer(), v8::internal::PrintF(), v8::internal::ShortPrint(), and v8::internal::v8_flags.
TraceOptimizedCodeCacheHit()
static void v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceOptimizedCodeCacheHit (Isolate * isolate, DirectHandle< JSFunction > function, BytecodeOffset osr_offset, CodeKind code_kind) [inline], [static]
Definition at line 233 of file compiler.cc.
                                                             {
    if (!v8_flags.trace_opt) return;
    CodeTracer::Scope scope(isolate->GetCodeTracer());
    PrintTracePrefix(scope, "found optimized code for", function, code_kind);
    if (IsOSR(osr_offset)) {
      PrintF(scope.file(), " at OSR bytecode offset %d", osr_offset.ToInt());
    }
    PrintTraceSuffix(scope);
  }
References v8::internal::CodeTracer::Scope::file(), v8::internal::Isolate::GetCodeTracer(), v8::internal::anonymous_namespace{compiler.cc}::IsOSR(), v8::internal::PrintF(), v8::internal::BytecodeOffset::ToInt(), and v8::internal::v8_flags.
TraceOptimizeForAlwaysOpt()
static void v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceOptimizeForAlwaysOpt (Isolate * isolate, DirectHandle< JSFunction > function, CodeKind code_kind) [inline], [static]
Definition at line 246 of file compiler.cc.
                                                            {
    if (!v8_flags.trace_opt) return;
    CodeTracer::Scope scope(isolate->GetCodeTracer());
    PrintTracePrefix(scope, "optimizing", function, code_kind);
    PrintF(scope.file(), " because --always-turbofan");
    PrintTraceSuffix(scope);
  }
References v8::internal::CodeTracer::Scope::file(), v8::internal::Isolate::GetCodeTracer(), v8::internal::PrintF(), and v8::internal::v8_flags.
TraceOptimizeOSRAvailable()
static void v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceOptimizeOSRAvailable (Isolate * isolate, DirectHandle< JSFunction > function, BytecodeOffset osr_offset, ConcurrencyMode mode) [inline], [static]
Definition at line 138 of file compiler.cc.
                                                              {
    if (!v8_flags.trace_osr) return;
    CodeTracer::Scope scope(isolate->GetCodeTracer());
    PrintF(scope.file(),
           "[OSR - available (compilation completed or cache hit). function: "
           "%s, osr offset: %d, mode: %s]\n",
           function->DebugNameCStr().get(), osr_offset.ToInt(), ToString(mode));
  }
References v8::internal::CodeTracer::Scope::file(), v8::internal::Isolate::GetCodeTracer(), mode(), v8::internal::PrintF(), v8::internal::BytecodeOffset::ToInt(), v8::internal::ToString(), and v8::internal::v8_flags.
TraceOptimizeOSRFinished()
static void v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceOptimizeOSRFinished (Isolate * isolate, DirectHandle< JSFunction > function, BytecodeOffset osr_offset) [inline], [static]
Definition at line 128 of file compiler.cc.
                                                                  {
    if (!v8_flags.trace_osr) return;
    CodeTracer::Scope scope(isolate->GetCodeTracer());
    PrintF(scope.file(),
           "[OSR - compilation finished. function: %s, osr offset: %d]\n",
           function->DebugNameCStr().get(), osr_offset.ToInt());
  }
References v8::internal::CodeTracer::Scope::file(), v8::internal::Isolate::GetCodeTracer(), v8::internal::PrintF(), v8::internal::BytecodeOffset::ToInt(), and v8::internal::v8_flags.
TraceOptimizeOSRStarted()
static void v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceOptimizeOSRStarted (Isolate * isolate, DirectHandle< JSFunction > function, BytecodeOffset osr_offset, ConcurrencyMode mode) [inline], [static]
Definition at line 116 of file compiler.cc.
                                                            {
    if (!v8_flags.trace_osr) return;
    CodeTracer::Scope scope(isolate->GetCodeTracer());
    PrintF(
        scope.file(),
        "[OSR - compilation started. function: %s, osr offset: %d, mode: %s]\n",
        function->DebugNameCStr().get(), osr_offset.ToInt(), ToString(mode));
  }
References v8::internal::CodeTracer::Scope::file(), v8::internal::Isolate::GetCodeTracer(), mode(), v8::internal::PrintF(), v8::internal::BytecodeOffset::ToInt(), v8::internal::ToString(), and v8::internal::v8_flags.
TraceOptimizeOSRUnavailable()
static void v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceOptimizeOSRUnavailable (Isolate * isolate, DirectHandle< JSFunction > function, BytecodeOffset osr_offset, ConcurrencyMode mode) [inline], [static]
Definition at line 150 of file compiler.cc.
                                                                {
    if (!v8_flags.trace_osr) return;
    CodeTracer::Scope scope(isolate->GetCodeTracer());
    PrintF(scope.file(),
           "[OSR - unavailable (failed or in progress). function: %s, osr "
           "offset: %d, mode: %s]\n",
           function->DebugNameCStr().get(), osr_offset.ToInt(), ToString(mode));
  }
References v8::internal::CodeTracer::Scope::file(), v8::internal::Isolate::GetCodeTracer(), mode(), v8::internal::PrintF(), v8::internal::BytecodeOffset::ToInt(), v8::internal::ToString(), and v8::internal::v8_flags.
TracePrepareJob()
static void v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TracePrepareJob (Isolate * isolate, OptimizedCompilationInfo * info, ConcurrencyMode mode) [inline], [static]
Definition at line 106 of file compiler.cc.
                                                    {
    if (!v8_flags.trace_opt || !info->IsOptimizing()) return;
    CodeTracer::Scope scope(isolate->GetCodeTracer());
    PrintTracePrefix(scope, "compiling method", info);
    if (info->is_osr()) PrintF(scope.file(), " OSR");
    PrintF(scope.file(), ", mode: %s", ToString(mode));
    PrintTraceSuffix(scope);
  }
References v8::internal::CodeTracer::Scope::file(), v8::internal::Isolate::GetCodeTracer(), v8::internal::OptimizedCompilationInfo::is_osr(), v8::internal::OptimizedCompilationInfo::IsOptimizing(), mode(), v8::internal::PrintF(), v8::internal::ToString(), and v8::internal::v8_flags.
TraceStartBaselineCompile()
static void v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceStartBaselineCompile (Isolate * isolate, DirectHandle< SharedFunctionInfo > shared) [inline], [static]
Definition at line 87 of file compiler.cc.
                                                                 {
    if (!v8_flags.trace_baseline) return;
    CodeTracer::Scope scope(isolate->GetCodeTracer());
    PrintTracePrefix(scope, "compiling method", shared, CodeKind::BASELINE);
    PrintTraceSuffix(scope);
  }
References v8::internal::Isolate::GetCodeTracer(), and v8::internal::v8_flags.
TraceStartMaglevCompile()
static void v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceStartMaglevCompile (Isolate * isolate, DirectHandle< JSFunction > function, bool osr, ConcurrencyMode mode) [inline], [static]
Definition at line 95 of file compiler.cc.
                                                                      {
    if (!v8_flags.trace_opt) return;
    CodeTracer::Scope scope(isolate->GetCodeTracer());
    PrintTracePrefix(scope, "compiling method", function, CodeKind::MAGLEV);
    if (osr) PrintF(scope.file(), " OSR");
    PrintF(scope.file(), ", mode: %s", ToString(mode));
    PrintTraceSuffix(scope);
  }
References v8::internal::CodeTracer::Scope::file(), v8::internal::Isolate::GetCodeTracer(), mode(), v8::internal::PrintF(), v8::internal::ToString(), and v8::internal::v8_flags.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/codegen/compiler.cc