v8::internal::interpreter::InterpreterAssembler Class Reference
#include <interpreter-assembler.h>
Classes
class RegListNodePair
Public Types
enum StackCheckBehavior { kEnableStackCheck
, kDisableStackCheck
 }
enum OnStackReplacementParams { kBaselineCodeIsCached
, kDefault
 }
Public Member Functions
InterpreterAssembler (compiler::CodeAssemblerState *state, Bytecode bytecode, OperandScale operand_scale)
~InterpreterAssembler ()
InterpreterAssembler (const InterpreterAssembler &)=delete
InterpreterAssembler & operator= (const InterpreterAssembler &)=delete
TNode< Uint32T > BytecodeOperandCount (int operand_index)
TNode< Uint32T > BytecodeOperandFlag8 (int operand_index)
TNode< Uint32T > BytecodeOperandFlag16 (int operand_index)
TNode< Uint32T > BytecodeOperandIdxInt32 (int operand_index)
TNode< UintPtrT > BytecodeOperandIdx (int operand_index)
TNode< Smi > BytecodeOperandIdxSmi (int operand_index)
TNode< TaggedIndex > BytecodeOperandIdxTaggedIndex (int operand_index)
TNode< Uint32T > BytecodeOperandUImm (int operand_index)
TNode< UintPtrT > BytecodeOperandUImmWord (int operand_index)
TNode< Smi > BytecodeOperandUImmSmi (int operand_index)
TNode< Int32T > BytecodeOperandImm (int operand_index)
TNode< IntPtrT > BytecodeOperandImmIntPtr (int operand_index)
TNode< Smi > BytecodeOperandImmSmi (int operand_index)
TNode< Uint32T > BytecodeOperandRuntimeId (int operand_index)
TNode< UintPtrT > BytecodeOperandNativeContextIndex (int operand_index)
TNode< Uint32T > BytecodeOperandIntrinsicId (int operand_index)
TNode< Object > GetAccumulator ()
void SetAccumulator (TNode< Object > value)
void ClobberAccumulator (TNode< Object > clobber_value)
TNode< Context > GetContext ()
void SetContext (TNode< Context > value)
TNode< Context > GetContextAtDepth (TNode< Context > context, TNode< Uint32T > depth)
TNode< FixedArray > ExportParametersAndRegisterFile (TNode< FixedArray > array, const RegListNodePair &registers)
TNode< FixedArray > ImportRegisterFile (TNode< FixedArray > array, const RegListNodePair &registers)
TNode< Object > LoadRegister (Register reg)
TNode< IntPtrT > LoadAndUntagRegister (Register reg)
TNode< Object > LoadRegisterAtOperandIndex (int operand_index)
std::pair< TNode< Object >, TNode< Object > > LoadRegisterPairAtOperandIndex (int operand_index)
void StoreRegister (TNode< Object > value, Register reg)
void StoreRegisterAtOperandIndex (TNode< Object > value, int operand_index)
void StoreRegisterPairAtOperandIndex (TNode< Object > value1, TNode< Object > value2, int operand_index)
void StoreRegisterTripleAtOperandIndex (TNode< Object > value1, TNode< Object > value2, TNode< Object > value3, int operand_index)
RegListNodePair GetRegisterListAtOperandIndex (int operand_index)
TNode< Object > LoadRegisterFromRegisterList (const RegListNodePair &reg_list, int index)
TNode< IntPtrT > RegisterLocationInRegisterList (const RegListNodePair &reg_list, int index)
TNode< Object > LoadConstantPoolEntryAtOperandIndex (int operand_index)
TNode< IntPtrT > LoadAndUntagConstantPoolEntryAtOperandIndex (int operand_index)
TNode< Object > LoadConstantPoolEntry (TNode< WordT > index)
TNode< IntPtrT > LoadAndUntagConstantPoolEntry (TNode< WordT > index)
TNode< JSFunction > LoadFunctionClosure ()
TNode< Union< FeedbackVector, Undefined > > LoadFeedbackVector ()
auto LoadFeedbackVectorOrUndefinedIfJitless ()
void CallJSAndDispatch (TNode< JSAny > function, TNode< Context > context, const RegListNodePair &args, ConvertReceiverMode receiver_mode)
template<class... TArgs>
void CallJSAndDispatch (TNode< JSAny > function, TNode< Context > context, TNode< Word32T > arg_count, ConvertReceiverMode receiver_mode, TArgs... args)
void CallJSWithSpreadAndDispatch (TNode< JSAny > function, TNode< Context > context, const RegListNodePair &args, TNode< UintPtrT > slot_id)
TNode< Object > Construct (TNode< JSAny > target, TNode< Context > context, TNode< JSAny > new_target, const RegListNodePair &args, TNode< UintPtrT > slot_id, TNode< Union< FeedbackVector, Undefined >> maybe_feedback_vector)
TNode< Object > ConstructWithSpread (TNode< JSAny > target, TNode< Context > context, TNode< JSAny > new_target, const RegListNodePair &args, TNode< UintPtrT > slot_id)
TNode< Object > ConstructForwardAllArgs (TNode< JSAny > target, TNode< Context > context, TNode< JSAny > new_target, TNode< TaggedIndex > slot_id)
template<class T = Object>
TNode< T > CallRuntimeN (TNode< Uint32T > function_id, TNode< Context > context, const RegListNodePair &args, int return_count)
void Jump (TNode< IntPtrT > jump_offset)
void JumpBackward (TNode< IntPtrT > jump_offset)
void JumpIfTaggedEqual (TNode< Object > lhs, TNode< Object > rhs, TNode< IntPtrT > jump_offset)
void JumpIfTaggedEqual (TNode< Object > lhs, TNode< Object > rhs, int operand_index)
void JumpIfTaggedEqualConstant (TNode< Object > lhs, TNode< Object > rhs, int operand_index)
void JumpIfTaggedNotEqual (TNode< Object > lhs, TNode< Object > rhs, TNode< IntPtrT > jump_offset)
void JumpIfTaggedNotEqual (TNode< Object > lhs, TNode< Object > rhs, int operand_index)
void JumpIfTaggedNotEqualConstant (TNode< Object > lhs, TNode< Object > rhs, int operand_index)
void UpdateInterruptBudgetOnReturn ()
TNode< Int32T > UpdateInterruptBudget (TNode< Int32T > weight)
void DecreaseInterruptBudget (TNode< Int32T > weight, StackCheckBehavior stack_check_behavior)
TNode< Int8T > LoadOsrState (TNode< FeedbackVector > feedback_vector)
void Dispatch ()
void DispatchWide (OperandScale operand_scale)
void DispatchToBytecode (TNode< WordT > target_bytecode, TNode< IntPtrT > new_bytecode_offset)
void DispatchToBytecodeWithOptionalStarLookahead (TNode< WordT > target_bytecode)
void Abort (AbortReason abort_reason)
void AbortIfWordNotEqual (TNode< WordT > lhs, TNode< WordT > rhs, AbortReason abort_reason)
void AbortIfRegisterCountInvalid (TNode< FixedArray > parameters_and_registers, TNode< IntPtrT > parameter_count, TNode< UintPtrT > register_count)
void OnStackReplacement (TNode< Context > context, TNode< FeedbackVector > feedback_vector, TNode< IntPtrT > relative_jump, TNode< Int32T > loop_depth, TNode< IntPtrT > feedback_slot, TNode< Int8T > osr_state, OnStackReplacementParams params)
TNode< IntPtrT > BytecodeOffset ()
Static Public Member Functions
static constexpr UpdateFeedbackMode DefaultUpdateFeedbackMode ()
Static Public Attributes
static constexpr int kFirstBytecodeOffset
Protected Member Functions
Bytecode bytecode () const
void ToNumberOrNumeric (Object::Conversion mode)
void StoreRegisterForShortStar (TNode< Object > value, TNode< WordT > opcode)
TNode< WordT > LoadBytecode (TNode< IntPtrT > bytecode_offset)
TNode< IntPtrT > LoadParameterCountWithoutReceiver ()
Static Protected Member Functions
static bool TargetSupportsUnalignedAccess ()
Private Member Functions
TNode< BytecodeArray > BytecodeArrayTaggedPointer ()
TNode< ExternalReference > DispatchTablePointer ()
TNode< Object > GetAccumulatorUnchecked ()
TNode< RawPtrT > GetInterpretedFramePointer ()
TNode< IntPtrT > RegisterLocation (Register reg)
TNode< IntPtrT > RegisterLocation (TNode< IntPtrT > reg_index)
TNode< IntPtrT > NextRegister (TNode< IntPtrT > reg_index)
TNode< Object > LoadRegister (TNode< IntPtrT > reg_index)
void StoreRegister (TNode< Object > value, TNode< IntPtrT > reg_index)
void CallPrologue ()
void CallEpilogue ()
void TraceBytecodeDispatch (TNode< WordT > target_bytecode)
void TraceBytecode (Runtime::FunctionId function_id)
TNode< IntPtrT > RegisterFrameOffset (TNode< IntPtrT > index)
TNode< IntPtrT > OperandOffset (int operand_index)
TNode< Word32T > BytecodeOperandReadUnaligned (int relative_offset, MachineType result_type)
TNode< Uint8T > BytecodeOperandUnsignedByte (int operand_index)
TNode< Int8T > BytecodeOperandSignedByte (int operand_index)
TNode< Uint16T > BytecodeOperandUnsignedShort (int operand_index)
TNode< Int16T > BytecodeOperandSignedShort (int operand_index)
TNode< Uint32T > BytecodeOperandUnsignedQuad (int operand_index)
TNode< Int32T > BytecodeOperandSignedQuad (int operand_index)
TNode< Int32T > BytecodeSignedOperand (int operand_index, OperandSize operand_size)
TNode< Uint32T > BytecodeUnsignedOperand (int operand_index, OperandSize operand_size)
TNode< IntPtrT > BytecodeOperandReg (int operand_index)
TNode< UintPtrT > BytecodeOperandConstantPoolIdx (int operand_index)
void JumpToOffset (TNode< IntPtrT > new_bytecode_offset)
void JumpConditional (TNode< BoolT > condition, TNode< IntPtrT > jump_offset)
void JumpConditionalByImmediateOperand (TNode< BoolT > condition, int operand_index)
void JumpConditionalByConstantOperand (TNode< BoolT > condition, int operand_index)
void SaveBytecodeOffset ()
TNode< IntPtrT > ReloadBytecodeOffset ()
TNode< IntPtrT > Advance ()
TNode< IntPtrT > Advance (int delta)
TNode< IntPtrT > Advance (TNode< IntPtrT > delta)
void StarDispatchLookahead (TNode< WordT > target_bytecode)
void InlineShortStar (TNode< WordT > target_bytecode)
void DispatchToBytecodeHandlerEntry (TNode< RawPtrT > handler_entry, TNode< IntPtrT > bytecode_offset)
int CurrentBytecodeSize () const
OperandScale operand_scale () const
Private Attributes
Bytecode bytecode_
OperandScale operand_scale_
CodeStubAssembler::TVariable< RawPtrT > interpreted_frame_pointer_
CodeStubAssembler::TVariable< BytecodeArray > bytecode_array_
CodeStubAssembler::TVariable< IntPtrT > bytecode_offset_
CodeStubAssembler::TVariable< ExternalReference > dispatch_table_
CodeStubAssembler::TVariable< Object > accumulator_
ImplicitRegisterUse implicit_register_use_
bool made_call_
bool reloaded_frame_ptr_
bool bytecode_array_valid_
Additional Inherited Members
Detailed Description
Definition at line 19 of file interpreter-assembler.h.
Member Enumeration Documentation
OnStackReplacementParams
enum v8::internal::interpreter::InterpreterAssembler::OnStackReplacementParams
Enumerator
kBaselineCodeIsCached
kDefault
Definition at line 301 of file interpreter-assembler.h.
                                {
    kBaselineCodeIsCached,
    kDefault,
  };
StackCheckBehavior
enum v8::internal::interpreter::InterpreterAssembler::StackCheckBehavior
Enumerator
kEnableStackCheck
kDisableStackCheck
Definition at line 265 of file interpreter-assembler.h.
                          {
    kEnableStackCheck,
    kDisableStackCheck,
  };
Constructor & Destructor Documentation
InterpreterAssembler() [1/2]
v8::internal::interpreter::InterpreterAssembler::InterpreterAssembler (compiler::CodeAssemblerState * state, Bytecode bytecode, OperandScale operand_scale)
Definition at line 26 of file interpreter-assembler.cc.
    : CodeStubAssembler(state),
      bytecode_(bytecode),
      operand_scale_(operand_scale),
      TVARIABLE_CONSTRUCTOR(interpreted_frame_pointer_),
      TVARIABLE_CONSTRUCTOR(bytecode_array_,
                            Parameter<BytecodeArray>(
                                InterpreterDispatchDescriptor::kBytecodeArray)),
      TVARIABLE_CONSTRUCTOR(
          bytecode_offset_,
          UncheckedParameter<IntPtrT>(
              InterpreterDispatchDescriptor::kBytecodeOffset)),
      TVARIABLE_CONSTRUCTOR(dispatch_table_,
                            UncheckedParameter<ExternalReference>(
                                InterpreterDispatchDescriptor::kDispatchTable)),
      TVARIABLE_CONSTRUCTOR(
          accumulator_,
          Parameter<Object>(InterpreterDispatchDescriptor::kAccumulator)),
      implicit_register_use_(ImplicitRegisterUse::kNone),
      made_call_(false),
      reloaded_frame_ptr_(false),
      bytecode_array_valid_(true) {
#ifdef V8_TRACE_UNOPTIMIZED
  TraceBytecode(Runtime::kTraceUnoptimizedBytecodeEntry);
#endif
  RegisterCallGenerationCallbacks([this] { CallPrologue(); },
                                  [this] { CallEpilogue(); });
  // Save the bytecode offset immediately if bytecode will make a call along
  // the critical path, or it is a return bytecode.
  if (Bytecodes::MakesCallAlongCriticalPath(bytecode) ||
      Bytecodes::Returns(bytecode)) {
    SaveBytecodeOffset();
  }
}
References bytecode(), CallEpilogue(), CallPrologue(), v8::internal::kNone, v8::internal::interpreter::Bytecodes::MakesCallAlongCriticalPath(), v8::internal::compiler::CodeAssembler::RegisterCallGenerationCallbacks(), v8::internal::interpreter::Bytecodes::Returns(), SaveBytecodeOffset(), and TraceBytecode().
 InterpreterAssembler()
v8::internal::interpreter::InterpreterAssembler::~InterpreterAssembler ()
Definition at line 64 of file interpreter-assembler.cc.
                                            {
  // If the following check fails the handler does not use the
  // accumulator in the way described in the bytecode definitions in
  // bytecodes.h.
  DCHECK_EQ(implicit_register_use_,
            Bytecodes::GetImplicitRegisterUse(bytecode_));
  UnregisterCallGenerationCallbacks();
}
References bytecode_, DCHECK_EQ, v8::internal::interpreter::Bytecodes::GetImplicitRegisterUse(), implicit_register_use_, and v8::internal::compiler::CodeAssembler::UnregisterCallGenerationCallbacks().
InterpreterAssembler() [2/2]
v8::internal::interpreter::InterpreterAssembler::InterpreterAssembler (const InterpreterAssembler &) [delete]
Member Function Documentation
Abort()
void v8::internal::interpreter::InterpreterAssembler::Abort (AbortReason abort_reason)
Definition at line 1387 of file interpreter-assembler.cc.
                                                         {
  TNode<Smi> abort_id = SmiConstant(abort_reason);
  CallRuntime(Runtime::kAbort, GetContext(), abort_id);
}
References v8::internal::compiler::CodeAssembler::CallRuntime(), GetContext(), and v8::internal::compiler::CodeAssembler::SmiConstant().
Referenced by AbortIfRegisterCountInvalid(), and AbortIfWordNotEqual().
AbortIfRegisterCountInvalid()
void v8::internal::interpreter::InterpreterAssembler::AbortIfRegisterCountInvalid (TNode< FixedArray > parameters_and_registers, TNode< IntPtrT > parameter_count, TNode< UintPtrT > register_count)
Definition at line 1545 of file interpreter-assembler.cc.
                                    {
  TNode<IntPtrT> array_size =
      LoadAndUntagFixedArrayBaseLength(parameters_and_registers);
  Label ok(this), abort(this, Label::kDeferred);
  Branch(UintPtrLessThanOrEqual(IntPtrAdd(parameter_count, register_count),
                                array_size),
         &ok, &abort);
  BIND(&abort);
  Abort(AbortReason::kInvalidParametersAndRegistersInGenerator);
  Goto(&ok);
  BIND(&ok);
}
References Abort(), v8::internal::compiler::CodeAssembler::Branch(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::CodeStubAssembler::LoadAndUntagFixedArrayBaseLength(), and v8::internal::CodeStubAssembler::UintPtrLessThanOrEqual.
Referenced by ExportParametersAndRegisterFile(), and ImportRegisterFile().
AbortIfWordNotEqual()
void v8::internal::interpreter::InterpreterAssembler::AbortIfWordNotEqual (TNode< WordT > lhs, TNode< WordT > rhs, AbortReason abort_reason)
Definition at line 1392 of file interpreter-assembler.cc.
                                                                         {
  Label ok(this), abort(this, Label::kDeferred);
  Branch(WordEqual(lhs, rhs), &ok, &abort);
  BIND(&abort);
  Abort(abort_reason);
  Goto(&ok);
  BIND(&ok);
}
References Abort(), v8::internal::compiler::CodeAssembler::Branch(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, and v8::internal::compiler::CodeAssembler::WordEqual().
Advance() [1/3]
TNode< IntPtrT > v8::internal::interpreter::InterpreterAssembler::Advance () [private]
Definition at line 1110 of file interpreter-assembler.cc.
                                             {
  return Advance(CurrentBytecodeSize());
}
References CurrentBytecodeSize().
Referenced by Advance(), Dispatch(), DispatchWide(), and InlineShortStar().
Advance() [2/3]
TNode< IntPtrT > v8::internal::interpreter::InterpreterAssembler::Advance (int delta) [private]
Definition at line 1114 of file interpreter-assembler.cc.
                                                      {
  return Advance(IntPtrConstant(delta));
}
References Advance(), and v8::internal::compiler::CodeAssembler::IntPtrConstant().
Advance() [3/3]
TNode< IntPtrT > v8::internal::interpreter::InterpreterAssembler::Advance (TNode< IntPtrT > delta) [private]
Definition at line 1118 of file interpreter-assembler.cc.
                                                                 {
  TNode<IntPtrT> next_offset = IntPtrAdd(BytecodeOffset(), delta);
  bytecode_offset_ = next_offset;
  return next_offset;
}
References bytecode_offset_, BytecodeOffset(), and v8::internal::compiler::CodeAssembler::IntPtrAdd().
bytecode()
Bytecode v8::internal::interpreter::InterpreterAssembler::bytecode () const [inline], [protected]
Definition at line 322 of file interpreter-assembler.h.
{ return bytecode_; }
Referenced by InterpreterAssembler(), LoadBytecode(), and OnStackReplacement().
BytecodeArrayTaggedPointer()
TNode< BytecodeArray > v8::internal::interpreter::InterpreterAssembler::BytecodeArrayTaggedPointer () [private]
Definition at line 132 of file interpreter-assembler.cc.
                                                                      {
  // Force a re-load of the bytecode array after every call in case the debugger
  // has been activated.
  if (!bytecode_array_valid_) {
    bytecode_array_ = CAST(LoadRegister(Register::bytecode_array()));
    bytecode_array_valid_ = true;
  }
  return bytecode_array_.value();
}
References v8::internal::interpreter::Register::bytecode_array(), bytecode_array_, bytecode_array_valid_, CAST, and LoadRegister().
Referenced by BytecodeOperandReadUnaligned(), BytecodeOperandSignedByte(), BytecodeOperandSignedQuad(), BytecodeOperandSignedShort(), BytecodeOperandUnsignedByte(), BytecodeOperandUnsignedQuad(), BytecodeOperandUnsignedShort(), DispatchToBytecodeHandlerEntry(), LoadBytecode(), LoadConstantPoolEntry(), LoadParameterCountWithoutReceiver(), OnStackReplacement(), and TraceBytecode().
BytecodeOffset()
TNode< IntPtrT > v8::internal::interpreter::InterpreterAssembler::BytecodeOffset ()
Definition at line 84 of file interpreter-assembler.cc.
                                                    {
  if (Bytecodes::MakesCallAlongCriticalPath(bytecode_) && made_call_ &&
      (bytecode_offset_.value() ==
       UncheckedParameter<IntPtrT>(
           InterpreterDispatchDescriptor::kBytecodeOffset))) {
    bytecode_offset_ = ReloadBytecodeOffset();
  }
  return bytecode_offset_.value();
}
References bytecode_, bytecode_offset_, made_call_, v8::internal::interpreter::Bytecodes::MakesCallAlongCriticalPath(), and ReloadBytecodeOffset().
Referenced by Advance(), BytecodeOperandReadUnaligned(), BytecodeOperandSignedByte(), BytecodeOperandSignedQuad(), BytecodeOperandSignedShort(), BytecodeOperandUnsignedByte(), BytecodeOperandUnsignedQuad(), BytecodeOperandUnsignedShort(), DispatchToBytecodeWithOptionalStarLookahead(), Jump(), JumpBackward(), SaveBytecodeOffset(), StarDispatchLookahead(), TraceBytecode(), and UpdateInterruptBudgetOnReturn().
BytecodeOperandConstantPoolIdx()
TNode< UintPtrT > v8::internal::interpreter::InterpreterAssembler::BytecodeOperandConstantPoolIdx (int operand_index) [private]
Definition at line 630 of file interpreter-assembler.cc.
                       {
  DCHECK_EQ(OperandType::kIdx,
            Bytecodes::GetOperandType(bytecode_, operand_index));
  OperandSize operand_size =
      Bytecodes::GetOperandSize(bytecode_, operand_index, operand_scale());
  return ChangeUint32ToWord(
      BytecodeUnsignedOperand(operand_index, operand_size));
}
References bytecode_, BytecodeUnsignedOperand(), v8::internal::compiler::CodeAssembler::ChangeUint32ToWord(), DCHECK_EQ, v8::internal::interpreter::Bytecodes::GetOperandSize(), v8::internal::interpreter::Bytecodes::GetOperandType(), and operand_scale().
Referenced by LoadConstantPoolEntryAtOperandIndex().
BytecodeOperandCount()
TNode< Uint32T > v8::internal::interpreter::InterpreterAssembler::BytecodeOperandCount (int operand_index)
Definition at line 546 of file interpreter-assembler.cc.
                                                                           {
  DCHECK_EQ(OperandType::kRegCount,
            Bytecodes::GetOperandType(bytecode_, operand_index));
  OperandSize operand_size =
      Bytecodes::GetOperandSize(bytecode_, operand_index, operand_scale());
  return BytecodeUnsignedOperand(operand_index, operand_size);
}
References bytecode_, BytecodeUnsignedOperand(), DCHECK_EQ, v8::internal::interpreter::Bytecodes::GetOperandSize(), v8::internal::interpreter::Bytecodes::GetOperandType(), and operand_scale().
Referenced by GetRegisterListAtOperandIndex().
BytecodeOperandFlag16()
TNode< Uint32T > v8::internal::interpreter::InterpreterAssembler::BytecodeOperandFlag16 (int operand_index)
Definition at line 563 of file interpreter-assembler.cc.
                                                                            {
  DCHECK_EQ(OperandType::kFlag16,
            Bytecodes::GetOperandType(bytecode_, operand_index));
  OperandSize operand_size =
      Bytecodes::GetOperandSize(bytecode_, operand_index, operand_scale());
  DCHECK_EQ(operand_size, OperandSize::kShort);
  return BytecodeUnsignedOperand(operand_index, operand_size);
}
References bytecode_, BytecodeUnsignedOperand(), DCHECK_EQ, v8::internal::interpreter::Bytecodes::GetOperandSize(), v8::internal::interpreter::Bytecodes::GetOperandType(), v8::internal::interpreter::kShort, and operand_scale().
BytecodeOperandFlag8()
TNode< Uint32T > v8::internal::interpreter::InterpreterAssembler::BytecodeOperandFlag8 (int operand_index)
Definition at line 554 of file interpreter-assembler.cc.
                                                                           {
  DCHECK_EQ(OperandType::kFlag8,
            Bytecodes::GetOperandType(bytecode_, operand_index));
  OperandSize operand_size =
      Bytecodes::GetOperandSize(bytecode_, operand_index, operand_scale());
  DCHECK_EQ(operand_size, OperandSize::kByte);
  return BytecodeUnsignedOperand(operand_index, operand_size);
}
References bytecode_, BytecodeUnsignedOperand(), DCHECK_EQ, v8::internal::interpreter::Bytecodes::GetOperandSize(), v8::internal::interpreter::Bytecodes::GetOperandType(), v8::internal::interpreter::kByte, and operand_scale().
BytecodeOperandIdx()
TNode< UintPtrT > v8::internal::interpreter::InterpreterAssembler::BytecodeOperandIdx (int operand_index)
Definition at line 615 of file interpreter-assembler.cc.
                                                                          {
  return ChangeUint32ToWord(BytecodeOperandIdxInt32(operand_index));
}
References BytecodeOperandIdxInt32(), and v8::internal::compiler::CodeAssembler::ChangeUint32ToWord().
Referenced by BytecodeOperandIdxSmi(), and ToNumberOrNumeric().
BytecodeOperandIdxInt32()
TNode< Uint32T > v8::internal::interpreter::InterpreterAssembler::BytecodeOperandIdxInt32 (int operand_index)
Definition at line 606 of file interpreter-assembler.cc.
                       {
  DCHECK_EQ(OperandType::kIdx,
            Bytecodes::GetOperandType(bytecode_, operand_index));
  OperandSize operand_size =
      Bytecodes::GetOperandSize(bytecode_, operand_index, operand_scale());
  return BytecodeUnsignedOperand(operand_index, operand_size);
}
References bytecode_, BytecodeUnsignedOperand(), DCHECK_EQ, v8::internal::interpreter::Bytecodes::GetOperandSize(), v8::internal::interpreter::Bytecodes::GetOperandType(), and operand_scale().
Referenced by BytecodeOperandIdx(), and BytecodeOperandIdxTaggedIndex().
BytecodeOperandIdxSmi()
TNode< Smi > v8::internal::interpreter::InterpreterAssembler::BytecodeOperandIdxSmi (int operand_index)
Definition at line 619 of file interpreter-assembler.cc.
                                                                        {
  return SmiTag(Signed(BytecodeOperandIdx(operand_index)));
}
References BytecodeOperandIdx(), v8::internal::compiler::CodeAssembler::Signed(), and v8::internal::CodeStubAssembler::SmiTag().
BytecodeOperandIdxTaggedIndex()
TNode< TaggedIndex > v8::internal::interpreter::InterpreterAssembler::BytecodeOperandIdxTaggedIndex (int operand_index)
Definition at line 623 of file interpreter-assembler.cc.
                       {
  TNode<IntPtrT> index =
      ChangeInt32ToIntPtr(Signed(BytecodeOperandIdxInt32(operand_index)));
  return IntPtrToTaggedIndex(index);
}
References BytecodeOperandIdxInt32(), v8::internal::compiler::CodeAssembler::ChangeInt32ToIntPtr(), v8::internal::index, v8::internal::CodeStubAssembler::IntPtrToTaggedIndex(), and v8::internal::compiler::CodeAssembler::Signed().
BytecodeOperandImm()
TNode< Int32T > v8::internal::interpreter::InterpreterAssembler::BytecodeOperandImm (int operand_index)
Definition at line 589 of file interpreter-assembler.cc.
                                                                        {
  DCHECK_EQ(OperandType::kImm,
            Bytecodes::GetOperandType(bytecode_, operand_index));
  OperandSize operand_size =
      Bytecodes::GetOperandSize(bytecode_, operand_index, operand_scale());
  return BytecodeSignedOperand(operand_index, operand_size);
}
References bytecode_, BytecodeSignedOperand(), DCHECK_EQ, v8::internal::interpreter::Bytecodes::GetOperandSize(), v8::internal::interpreter::Bytecodes::GetOperandType(), and operand_scale().
Referenced by BytecodeOperandImmIntPtr(), and BytecodeOperandImmSmi().
BytecodeOperandImmIntPtr()
TNode< IntPtrT > v8::internal::interpreter::InterpreterAssembler::BytecodeOperandImmIntPtr (int operand_index)
Definition at line 597 of file interpreter-assembler.cc.
                       {
  return ChangeInt32ToIntPtr(BytecodeOperandImm(operand_index));
}
References BytecodeOperandImm(), and v8::internal::compiler::CodeAssembler::ChangeInt32ToIntPtr().
BytecodeOperandImmSmi()
TNode< Smi > v8::internal::interpreter::InterpreterAssembler::BytecodeOperandImmSmi (int operand_index)
Definition at line 602 of file interpreter-assembler.cc.
                                                                        {
  return SmiFromInt32(BytecodeOperandImm(operand_index));
}
References BytecodeOperandImm(), and v8::internal::CodeStubAssembler::SmiFromInt32().
BytecodeOperandIntrinsicId()
TNode< Uint32T > v8::internal::interpreter::InterpreterAssembler::BytecodeOperandIntrinsicId (int operand_index)
Definition at line 669 of file interpreter-assembler.cc.
                       {
  DCHECK_EQ(OperandType::kIntrinsicId,
            Bytecodes::GetOperandType(bytecode_, operand_index));
  OperandSize operand_size =
      Bytecodes::GetOperandSize(bytecode_, operand_index, operand_scale());
  DCHECK_EQ(operand_size, OperandSize::kByte);
  return BytecodeUnsignedOperand(operand_index, operand_size);
}
References bytecode_, BytecodeUnsignedOperand(), DCHECK_EQ, v8::internal::interpreter::Bytecodes::GetOperandSize(), v8::internal::interpreter::Bytecodes::GetOperandType(), v8::internal::interpreter::kByte, and operand_scale().
BytecodeOperandNativeContextIndex()
TNode< UintPtrT > v8::internal::interpreter::InterpreterAssembler::BytecodeOperandNativeContextIndex (int operand_index)
Definition at line 659 of file interpreter-assembler.cc.
                       {
  DCHECK_EQ(OperandType::kNativeContextIndex,
            Bytecodes::GetOperandType(bytecode_, operand_index));
  OperandSize operand_size =
      Bytecodes::GetOperandSize(bytecode_, operand_index, operand_scale());
  return ChangeUint32ToWord(
      BytecodeUnsignedOperand(operand_index, operand_size));
}
References bytecode_, BytecodeUnsignedOperand(), v8::internal::compiler::CodeAssembler::ChangeUint32ToWord(), DCHECK_EQ, v8::internal::interpreter::Bytecodes::GetOperandSize(), v8::internal::interpreter::Bytecodes::GetOperandType(), and operand_scale().
BytecodeOperandReadUnaligned()
TNode< Word32T > v8::internal::interpreter::InterpreterAssembler::BytecodeOperandReadUnaligned (int relative_offset, MachineType result_type) [private]
Definition at line 392 of file interpreter-assembler.cc.
                                                  {
  static const int kMaxCount = 4;
  DCHECK(!TargetSupportsUnalignedAccess());
  int count;
  switch (result_type.representation()) {
    case MachineRepresentation::kWord16:
      count = 2;
      break;
    case MachineRepresentation::kWord32:
      count = 4;
      break;
    default:
      UNREACHABLE();
  }
  MachineType msb_type =
      result_type.IsSigned() ? MachineType::Int8() : MachineType::Uint8();
#if V8_TARGET_LITTLE_ENDIAN
  const int kStep = -1;
  int msb_offset = count - 1;
#elif V8_TARGET_BIG_ENDIAN
  const int kStep = 1;
  int msb_offset = 0;
#else
#error "Unknown Architecture"
#endif
  // Read the most signicant bytecode into bytes[0] and then in order
  // down to least significant in bytes[count - 1].
  DCHECK_LE(count, kMaxCount);
  TNode<Word32T> bytes[kMaxCount];
  for (int i = 0; i < count; i++) {
    MachineType machine_type = (i == 0) ? msb_type : MachineType::Uint8();
    TNode<IntPtrT> offset =
        IntPtrConstant(relative_offset + msb_offset + i * kStep);
    TNode<IntPtrT> array_offset = IntPtrAdd(BytecodeOffset(), offset);
    bytes[i] = UncheckedCast<Word32T>(
        Load(machine_type, BytecodeArrayTaggedPointer(), array_offset));
  }
  // Pack LSB to MSB.
  TNode<Word32T> result = bytes[--count];
  for (int i = 1; --count >= 0; i++) {
    TNode<Int32T> shift = Int32Constant(i * kBitsPerByte);
    TNode<Word32T> value = Word32Shl(bytes[count], shift);
    result = Word32Or(value, result);
  }
  return result;
}
References BytecodeArrayTaggedPointer(), BytecodeOffset(), v8::internal::DCHECK(), DCHECK_LE, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::MachineType::Int8(), v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::MachineType::IsSigned(), v8::internal::kBitsPerByte, v8::internal::kWord16, v8::internal::kWord32, v8::internal::compiler::CodeAssembler::Load(), v8::internal::wasm::machine_type(), v8::internal::MachineType::representation(), v8::base::internal::result, TargetSupportsUnalignedAccess(), v8::internal::MachineType::Uint8(), v8::internal::UNREACHABLE(), v8::internal::value, v8::internal::compiler::CodeAssembler::Word32Or(), and v8::internal::compiler::CodeAssembler::Word32Shl().
Referenced by BytecodeOperandSignedQuad(), BytecodeOperandSignedShort(), BytecodeOperandUnsignedQuad(), and BytecodeOperandUnsignedShort().
BytecodeOperandReg()
TNode< IntPtrT > v8::internal::interpreter::InterpreterAssembler::BytecodeOperandReg (int operand_index) [private]
Definition at line 640 of file interpreter-assembler.cc.
                                                                         {
  DCHECK(Bytecodes::IsRegisterOperandType(
      Bytecodes::GetOperandType(bytecode_, operand_index)));
  OperandSize operand_size =
      Bytecodes::GetOperandSize(bytecode_, operand_index, operand_scale());
  return ChangeInt32ToIntPtr(
      BytecodeSignedOperand(operand_index, operand_size));
}
References bytecode_, BytecodeSignedOperand(), v8::internal::compiler::CodeAssembler::ChangeInt32ToIntPtr(), v8::internal::DCHECK(), v8::internal::interpreter::Bytecodes::GetOperandSize(), v8::internal::interpreter::Bytecodes::GetOperandType(), v8::internal::interpreter::Bytecodes::IsRegisterOperandType(), and operand_scale().
Referenced by GetRegisterListAtOperandIndex(), LoadRegisterAtOperandIndex(), LoadRegisterPairAtOperandIndex(), StoreRegisterAtOperandIndex(), StoreRegisterPairAtOperandIndex(), and StoreRegisterTripleAtOperandIndex().
BytecodeOperandRuntimeId()
TNode< Uint32T > v8::internal::interpreter::InterpreterAssembler::BytecodeOperandRuntimeId (int operand_index)
Definition at line 649 of file interpreter-assembler.cc.
                       {
  DCHECK_EQ(OperandType::kRuntimeId,
            Bytecodes::GetOperandType(bytecode_, operand_index));
  OperandSize operand_size =
      Bytecodes::GetOperandSize(bytecode_, operand_index, operand_scale());
  DCHECK_EQ(operand_size, OperandSize::kShort);
  return BytecodeUnsignedOperand(operand_index, operand_size);
}
References bytecode_, BytecodeUnsignedOperand(), DCHECK_EQ, v8::internal::interpreter::Bytecodes::GetOperandSize(), v8::internal::interpreter::Bytecodes::GetOperandType(), v8::internal::interpreter::kShort, and operand_scale().
BytecodeOperandSignedByte()
TNode< Int8T > v8::internal::interpreter::InterpreterAssembler::BytecodeOperandSignedByte (int operand_index) [private]
Definition at line 382 of file interpreter-assembler.cc.
                       {
  DCHECK_LT(operand_index, Bytecodes::NumberOfOperands(bytecode_));
  DCHECK_EQ(OperandSize::kByte, Bytecodes::GetOperandSize(
                                    bytecode_, operand_index, operand_scale()));
  TNode<IntPtrT> operand_offset = OperandOffset(operand_index);
  return Load<Int8T>(BytecodeArrayTaggedPointer(),
                     IntPtrAdd(BytecodeOffset(), operand_offset));
}
References bytecode_, BytecodeArrayTaggedPointer(), BytecodeOffset(), DCHECK_EQ, DCHECK_LT, v8::internal::interpreter::Bytecodes::GetOperandSize(), v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::interpreter::kByte, v8::internal::interpreter::Bytecodes::NumberOfOperands(), operand_scale(), and OperandOffset().
Referenced by BytecodeSignedOperand().
BytecodeOperandSignedQuad()
TNode< Int32T > v8::internal::interpreter::InterpreterAssembler::BytecodeOperandSignedQuad (int operand_index) [private]
Definition at line 497 of file interpreter-assembler.cc.
                       {
  DCHECK_LT(operand_index, Bytecodes::NumberOfOperands(bytecode_));
  DCHECK_EQ(OperandSize::kQuad, Bytecodes::GetOperandSize(
                                    bytecode_, operand_index, operand_scale()));
  int operand_offset =
      Bytecodes::GetOperandOffset(bytecode_, operand_index, operand_scale());
  if (TargetSupportsUnalignedAccess()) {
    return Load<Int32T>(
        BytecodeArrayTaggedPointer(),
        IntPtrAdd(BytecodeOffset(), IntPtrConstant(operand_offset)));
  } else {
    return UncheckedCast<Int32T>(
        BytecodeOperandReadUnaligned(operand_offset, MachineType::Int32()));
  }
}
References bytecode_, BytecodeArrayTaggedPointer(), BytecodeOffset(), BytecodeOperandReadUnaligned(), DCHECK_EQ, DCHECK_LT, v8::internal::interpreter::Bytecodes::GetOperandOffset(), v8::internal::interpreter::Bytecodes::GetOperandSize(), v8::internal::MachineType::Int32(), v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::interpreter::kQuad, v8::internal::interpreter::Bytecodes::NumberOfOperands(), operand_scale(), and TargetSupportsUnalignedAccess().
Referenced by BytecodeSignedOperand().
BytecodeOperandSignedShort()
TNode< Int16T > v8::internal::interpreter::InterpreterAssembler::BytecodeOperandSignedShort (int operand_index) [private]
Definition at line 462 of file interpreter-assembler.cc.
                       {
  DCHECK_LT(operand_index, Bytecodes::NumberOfOperands(bytecode_));
  DCHECK_EQ(
      OperandSize::kShort,
      Bytecodes::GetOperandSize(bytecode_, operand_index, operand_scale()));
  int operand_offset =
      Bytecodes::GetOperandOffset(bytecode_, operand_index, operand_scale());
  if (TargetSupportsUnalignedAccess()) {
    return Load<Int16T>(
        BytecodeArrayTaggedPointer(),
        IntPtrAdd(BytecodeOffset(), IntPtrConstant(operand_offset)));
  } else {
    return UncheckedCast<Int16T>(
        BytecodeOperandReadUnaligned(operand_offset, MachineType::Int16()));
  }
}
References bytecode_, BytecodeArrayTaggedPointer(), BytecodeOffset(), BytecodeOperandReadUnaligned(), DCHECK_EQ, DCHECK_LT, v8::internal::interpreter::Bytecodes::GetOperandOffset(), v8::internal::interpreter::Bytecodes::GetOperandSize(), v8::internal::MachineType::Int16(), v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::interpreter::kShort, v8::internal::interpreter::Bytecodes::NumberOfOperands(), operand_scale(), and TargetSupportsUnalignedAccess().
Referenced by BytecodeSignedOperand().
BytecodeOperandUImm()
TNode< Uint32T > v8::internal::interpreter::InterpreterAssembler::BytecodeOperandUImm (int operand_index)
Definition at line 572 of file interpreter-assembler.cc.
                                                                          {
  DCHECK_EQ(OperandType::kUImm,
            Bytecodes::GetOperandType(bytecode_, operand_index));
  OperandSize operand_size =
      Bytecodes::GetOperandSize(bytecode_, operand_index, operand_scale());
  return BytecodeUnsignedOperand(operand_index, operand_size);
}
References bytecode_, BytecodeUnsignedOperand(), DCHECK_EQ, v8::internal::interpreter::Bytecodes::GetOperandSize(), v8::internal::interpreter::Bytecodes::GetOperandType(), and operand_scale().
Referenced by BytecodeOperandUImmSmi(), and BytecodeOperandUImmWord().
BytecodeOperandUImmSmi()
TNode< Smi > v8::internal::interpreter::InterpreterAssembler::BytecodeOperandUImmSmi (int operand_index)
Definition at line 585 of file interpreter-assembler.cc.
                                                                         {
  return SmiFromUint32(BytecodeOperandUImm(operand_index));
}
References BytecodeOperandUImm(), and v8::internal::CodeStubAssembler::SmiFromUint32().
BytecodeOperandUImmWord()
TNode< UintPtrT > v8::internal::interpreter::InterpreterAssembler::BytecodeOperandUImmWord (int operand_index)
Definition at line 580 of file interpreter-assembler.cc.
                       {
  return ChangeUint32ToWord(BytecodeOperandUImm(operand_index));
}
References BytecodeOperandUImm(), and v8::internal::compiler::CodeAssembler::ChangeUint32ToWord().
Referenced by JumpConditionalByImmediateOperand().
BytecodeOperandUnsignedByte()
TNode< Uint8T > v8::internal::interpreter::InterpreterAssembler::BytecodeOperandUnsignedByte (int operand_index) [private]
Definition at line 372 of file interpreter-assembler.cc.
                       {
  DCHECK_LT(operand_index, Bytecodes::NumberOfOperands(bytecode_));
  DCHECK_EQ(OperandSize::kByte, Bytecodes::GetOperandSize(
                                    bytecode_, operand_index, operand_scale()));
  TNode<IntPtrT> operand_offset = OperandOffset(operand_index);
  return Load<Uint8T>(BytecodeArrayTaggedPointer(),
                      IntPtrAdd(BytecodeOffset(), operand_offset));
}
References bytecode_, BytecodeArrayTaggedPointer(), BytecodeOffset(), DCHECK_EQ, DCHECK_LT, v8::internal::interpreter::Bytecodes::GetOperandSize(), v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::interpreter::kByte, v8::internal::interpreter::Bytecodes::NumberOfOperands(), operand_scale(), and OperandOffset().
Referenced by BytecodeUnsignedOperand().
BytecodeOperandUnsignedQuad()
TNode< Uint32T > v8::internal::interpreter::InterpreterAssembler::BytecodeOperandUnsignedQuad (int operand_index) [private]
Definition at line 480 of file interpreter-assembler.cc.
                       {
  DCHECK_LT(operand_index, Bytecodes::NumberOfOperands(bytecode_));
  DCHECK_EQ(OperandSize::kQuad, Bytecodes::GetOperandSize(
                                    bytecode_, operand_index, operand_scale()));
  int operand_offset =
      Bytecodes::GetOperandOffset(bytecode_, operand_index, operand_scale());
  if (TargetSupportsUnalignedAccess()) {
    return Load<Uint32T>(
        BytecodeArrayTaggedPointer(),
        IntPtrAdd(BytecodeOffset(), IntPtrConstant(operand_offset)));
  } else {
    return UncheckedCast<Uint32T>(
        BytecodeOperandReadUnaligned(operand_offset, MachineType::Uint32()));
  }
}
References bytecode_, BytecodeArrayTaggedPointer(), BytecodeOffset(), BytecodeOperandReadUnaligned(), DCHECK_EQ, DCHECK_LT, v8::internal::interpreter::Bytecodes::GetOperandOffset(), v8::internal::interpreter::Bytecodes::GetOperandSize(), v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::interpreter::kQuad, v8::internal::interpreter::Bytecodes::NumberOfOperands(), operand_scale(), TargetSupportsUnalignedAccess(), and v8::internal::MachineType::Uint32().
Referenced by BytecodeUnsignedOperand().
BytecodeOperandUnsignedShort()
TNode< Uint16T > v8::internal::interpreter::InterpreterAssembler::BytecodeOperandUnsignedShort (int operand_index) [private]
Definition at line 444 of file interpreter-assembler.cc.
                       {
  DCHECK_LT(operand_index, Bytecodes::NumberOfOperands(bytecode_));
  DCHECK_EQ(
      OperandSize::kShort,
      Bytecodes::GetOperandSize(bytecode_, operand_index, operand_scale()));
  int operand_offset =
      Bytecodes::GetOperandOffset(bytecode_, operand_index, operand_scale());
  if (TargetSupportsUnalignedAccess()) {
    return Load<Uint16T>(
        BytecodeArrayTaggedPointer(),
        IntPtrAdd(BytecodeOffset(), IntPtrConstant(operand_offset)));
  } else {
    return UncheckedCast<Uint16T>(
        BytecodeOperandReadUnaligned(operand_offset, MachineType::Uint16()));
  }
}
References bytecode_, BytecodeArrayTaggedPointer(), BytecodeOffset(), BytecodeOperandReadUnaligned(), DCHECK_EQ, DCHECK_LT, v8::internal::interpreter::Bytecodes::GetOperandOffset(), v8::internal::interpreter::Bytecodes::GetOperandSize(), v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::interpreter::kShort, v8::internal::interpreter::Bytecodes::NumberOfOperands(), operand_scale(), TargetSupportsUnalignedAccess(), and v8::internal::MachineType::Uint16().
Referenced by BytecodeUnsignedOperand().
BytecodeSignedOperand()
TNode< Int32T > v8::internal::interpreter::InterpreterAssembler::BytecodeSignedOperand (int operand_index, OperandSize operand_size) [private]
Definition at line 514 of file interpreter-assembler.cc.
                                                 {
  DCHECK(!Bytecodes::IsUnsignedOperandType(
      Bytecodes::GetOperandType(bytecode_, operand_index)));
  switch (operand_size) {
    case OperandSize::kByte:
      return BytecodeOperandSignedByte(operand_index);
    case OperandSize::kShort:
      return BytecodeOperandSignedShort(operand_index);
    case OperandSize::kQuad:
      return BytecodeOperandSignedQuad(operand_index);
    case OperandSize::kNone:
      UNREACHABLE();
  }
}
References bytecode_, BytecodeOperandSignedByte(), BytecodeOperandSignedQuad(), BytecodeOperandSignedShort(), v8::internal::DCHECK(), v8::internal::interpreter::Bytecodes::GetOperandType(), v8::internal::interpreter::Bytecodes::IsUnsignedOperandType(), v8::internal::interpreter::kByte, v8::internal::interpreter::kNone, v8::internal::interpreter::kQuad, v8::internal::interpreter::kShort, and v8::internal::UNREACHABLE().
Referenced by BytecodeOperandImm(), and BytecodeOperandReg().
BytecodeUnsignedOperand()
TNode< Uint32T > v8::internal::interpreter::InterpreterAssembler::BytecodeUnsignedOperand (int operand_index, OperandSize operand_size) [private]
Definition at line 530 of file interpreter-assembler.cc.
                                                 {
  DCHECK(Bytecodes::IsUnsignedOperandType(
      Bytecodes::GetOperandType(bytecode_, operand_index)));
  switch (operand_size) {
    case OperandSize::kByte:
      return BytecodeOperandUnsignedByte(operand_index);
    case OperandSize::kShort:
      return BytecodeOperandUnsignedShort(operand_index);
    case OperandSize::kQuad:
      return BytecodeOperandUnsignedQuad(operand_index);
    case OperandSize::kNone:
      UNREACHABLE();
  }
}
References bytecode_, BytecodeOperandUnsignedByte(), BytecodeOperandUnsignedQuad(), BytecodeOperandUnsignedShort(), v8::internal::DCHECK(), v8::internal::interpreter::Bytecodes::GetOperandType(), v8::internal::interpreter::Bytecodes::IsUnsignedOperandType(), v8::internal::interpreter::kByte, v8::internal::interpreter::kNone, v8::internal::interpreter::kQuad, v8::internal::interpreter::kShort, and v8::internal::UNREACHABLE().
Referenced by BytecodeOperandConstantPoolIdx(), BytecodeOperandCount(), BytecodeOperandFlag16(), BytecodeOperandFlag8(), BytecodeOperandIdxInt32(), BytecodeOperandIntrinsicId(), BytecodeOperandNativeContextIndex(), BytecodeOperandRuntimeId(), and BytecodeOperandUImm().
CallEpilogue()
void v8::internal::interpreter::InterpreterAssembler::CallEpilogue () [private]
Definition at line 727 of file interpreter-assembler.cc.
{}
Referenced by InterpreterAssembler().
CallJSAndDispatch() [1/2]
void v8::internal::interpreter::InterpreterAssembler::CallJSAndDispatch (TNode< JSAny > function, TNode< Context > context, const RegListNodePair & args, ConvertReceiverMode receiver_mode)
Definition at line 729 of file interpreter-assembler.cc.
                                       {
  DCHECK(Bytecodes::MakesCallAlongCriticalPath(bytecode_));
  DCHECK(Bytecodes::IsCallOrConstruct(bytecode_) ||
         bytecode_ == Bytecode::kInvokeIntrinsic);
  DCHECK_EQ(Bytecodes::GetReceiverMode(bytecode_), receiver_mode);
  TNode<Word32T> args_count = args.reg_count();
  if (receiver_mode == ConvertReceiverMode::kNullOrUndefined) {
    // Add receiver. It is not included in args as it is implicit.
    args_count = Int32Add(args_count, Int32Constant(kJSArgcReceiverSlots));
  }
  Builtin builtin = Builtins::InterpreterPushArgsThenCall(
      receiver_mode, InterpreterPushArgsMode::kOther);
  TailCallBuiltinThenBytecodeDispatch(builtin, context, args_count,
                                      args.base_reg_location(), function);
  // TailCallStubThenDispatch updates accumulator with result.
  implicit_register_use_ =
      implicit_register_use_ | ImplicitRegisterUse::kWriteAccumulator;
}
References v8::base::args, v8::internal::compiler::CodeAssembler::builtin(), bytecode_, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::interpreter::Bytecodes::GetReceiverMode(), implicit_register_use_, v8::internal::compiler::CodeAssembler::Int32Add(), v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::Builtins::InterpreterPushArgsThenCall(), v8::internal::interpreter::Bytecodes::IsCallOrConstruct(), v8::internal::kJSArgcReceiverSlots, v8::internal::kNullOrUndefined, v8::internal::kOther, v8::internal::interpreter::kWriteAccumulator, v8::internal::interpreter::Bytecodes::MakesCallAlongCriticalPath(), and v8::internal::compiler::CodeAssembler::TailCallBuiltinThenBytecodeDispatch().
CallJSAndDispatch() [2/2]
template<class... TArgs>
void v8::internal::interpreter::InterpreterAssembler::CallJSAndDispatch (TNode< JSAny > function, TNode< Context > context, TNode< Word32T > arg_count, ConvertReceiverMode receiver_mode, TArgs... args)
Definition at line 754 of file interpreter-assembler.cc.
                                                            {
  DCHECK(Bytecodes::MakesCallAlongCriticalPath(bytecode_));
  DCHECK(Bytecodes::IsCallOrConstruct(bytecode_) ||
         bytecode_ == Bytecode::kInvokeIntrinsic);
  DCHECK_EQ(Bytecodes::GetReceiverMode(bytecode_), receiver_mode);
  Builtin builtin = Builtins::Call();
  arg_count = JSParameterCount(arg_count);
  if (receiver_mode == ConvertReceiverMode::kNullOrUndefined) {
    // The first argument parameter (the receiver) is implied to be undefined.
    TailCallBuiltinThenBytecodeDispatch(builtin, context, function, arg_count,
                                        args..., UndefinedConstant());
  } else {
    TailCallBuiltinThenBytecodeDispatch(builtin, context, function, arg_count,
                                        args...);
  }
  // TailCallStubThenDispatch updates accumulator with result.
  implicit_register_use_ =
      implicit_register_use_ | ImplicitRegisterUse::kWriteAccumulator;
}
References v8::base::args, v8::internal::compiler::CodeAssembler::builtin(), bytecode_, v8::internal::Builtins::Call(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::interpreter::Bytecodes::GetReceiverMode(), implicit_register_use_, v8::internal::interpreter::Bytecodes::IsCallOrConstruct(), v8::internal::CodeStubAssembler::JSParameterCount(), v8::internal::kNullOrUndefined, v8::internal::interpreter::kWriteAccumulator, v8::internal::interpreter::Bytecodes::MakesCallAlongCriticalPath(), v8::internal::compiler::CodeAssembler::TailCallBuiltinThenBytecodeDispatch(), and v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
CallJSWithSpreadAndDispatch()
void v8::internal::interpreter::InterpreterAssembler::CallJSWithSpreadAndDispatch (TNode< JSAny > function, TNode< Context > context, const RegListNodePair & args, TNode< UintPtrT > slot_id)
Definition at line 795 of file interpreter-assembler.cc.
                             {
  DCHECK(Bytecodes::MakesCallAlongCriticalPath(bytecode_));
  DCHECK_EQ(Bytecodes::GetReceiverMode(bytecode_), ConvertReceiverMode::kAny);
#ifndef V8_JITLESS
  TNode<Union<FeedbackVector, Undefined>> maybe_feedback_vector =
      LoadFeedbackVector();
  LazyNode<JSAny> receiver = [=, this] {
    return CAST(LoadRegisterAtOperandIndex(1));
  };
  CollectCallFeedback(function, receiver, context, maybe_feedback_vector,
                      slot_id);
#endif // !V8_JITLESS
  Comment("call using CallWithSpread builtin");
  Builtin builtin = Builtins::InterpreterPushArgsThenCall(
      ConvertReceiverMode::kAny, InterpreterPushArgsMode::kWithFinalSpread);
  TNode<Word32T> args_count = args.reg_count();
  TailCallBuiltinThenBytecodeDispatch(builtin, context, args_count,
                                      args.base_reg_location(), function);
  // TailCallStubThenDispatch updates accumulator with result.
  implicit_register_use_ =
      implicit_register_use_ | ImplicitRegisterUse::kWriteAccumulator;
}
References v8::base::args, v8::internal::compiler::CodeAssembler::builtin(), bytecode_, CAST, v8::internal::compiler::CodeAssembler::Comment(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::interpreter::Bytecodes::GetReceiverMode(), implicit_register_use_, v8::internal::Builtins::InterpreterPushArgsThenCall(), v8::internal::kAny, v8::internal::kWithFinalSpread, v8::internal::interpreter::kWriteAccumulator, LoadFeedbackVector(), LoadRegisterAtOperandIndex(), v8::internal::interpreter::Bytecodes::MakesCallAlongCriticalPath(), and v8::internal::compiler::CodeAssembler::TailCallBuiltinThenBytecodeDispatch().
CallPrologue()
void v8::internal::interpreter::InterpreterAssembler::CallPrologue () [private]
Definition at line 713 of file interpreter-assembler.cc.
                                        {
  if (!Bytecodes::MakesCallAlongCriticalPath(bytecode_)) {
    // Bytecodes that make a call along the critical path save the bytecode
    // offset in the bytecode handler's prologue. For other bytecodes, if
    // there are multiple calls in the bytecode handler, you need to spill
    // before each of them, unless SaveBytecodeOffset has explicitly been called
    // in a path that dominates _all_ of those calls (which we don't track).
    SaveBytecodeOffset();
  }
  bytecode_array_valid_ = false;
  made_call_ = true;
}
References bytecode_, bytecode_array_valid_, made_call_, v8::internal::interpreter::Bytecodes::MakesCallAlongCriticalPath(), and SaveBytecodeOffset().
Referenced by InterpreterAssembler().
CallRuntimeN()
template<class T >
template V8_EXPORT_PRIVATE TNode< PairT< Object, Object > > v8::internal::interpreter::InterpreterAssembler::CallRuntimeN (TNode< Uint32T > function_id, TNode< Context > context, const RegListNodePair & args, int return_count)
Definition at line 1035 of file interpreter-assembler.cc.
                                                              {
  DCHECK(Bytecodes::MakesCallAlongCriticalPath(bytecode_));
  DCHECK(Bytecodes::IsCallRuntime(bytecode_));
  // Get the function entry from the function id.
  TNode<RawPtrT> function_table = ReinterpretCast<RawPtrT>(ExternalConstant(
      ExternalReference::runtime_function_table_address(isolate())));
  TNode<Word32T> function_offset =
      Int32Mul(function_id, Int32Constant(sizeof(Runtime::Function)));
  TNode<WordT> function =
      IntPtrAdd(function_table, ChangeUint32ToWord(function_offset));
  TNode<RawPtrT> function_entry = Load<RawPtrT>(
      function, IntPtrConstant(offsetof(Runtime::Function, entry)));
  Builtin centry = Builtins::InterpreterCEntry(return_count);
  return CallBuiltin<T>(centry, context, args.reg_count(),
                        args.base_reg_location(), function_entry);
}
References v8::base::args, bytecode_, v8::internal::compiler::CodeAssembler::ChangeUint32ToWord(), v8::internal::DCHECK(), v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::compiler::CodeAssembler::Int32Mul(), v8::internal::Builtins::InterpreterCEntry(), v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::interpreter::Bytecodes::IsCallRuntime(), v8::internal::compiler::CodeAssembler::isolate(), and v8::internal::interpreter::Bytecodes::MakesCallAlongCriticalPath().
ClobberAccumulator()
void v8::internal::interpreter::InterpreterAssembler::ClobberAccumulator (TNode< Object > clobber_value)
Definition at line 171 of file interpreter-assembler.cc.
                                                                         {
  DCHECK(Bytecodes::ClobbersAccumulator(bytecode_));
  implicit_register_use_ =
      implicit_register_use_ | ImplicitRegisterUse::kClobberAccumulator;
  accumulator_ = clobber_value;
}
References accumulator_, bytecode_, v8::internal::interpreter::Bytecodes::ClobbersAccumulator(), v8::internal::DCHECK(), implicit_register_use_, and v8::internal::interpreter::kClobberAccumulator.
Construct()
TNode< Object > v8::internal::interpreter::InterpreterAssembler::Construct (TNode< JSAny > target, TNode< Context > context, TNode< JSAny > new_target, const RegListNodePair & args, TNode< UintPtrT > slot_id, TNode< Union< FeedbackVector, Undefined >> maybe_feedback_vector)
Definition at line 823 of file interpreter-assembler.cc.
                                                                   {
  DCHECK(Bytecodes::MakesCallAlongCriticalPath(bytecode_));
  TVARIABLE(Object, var_result);
  TVARIABLE(AllocationSite, var_site);
  Label return_result(this), try_fast_construct(this), construct_generic(this),
      construct_array(this, &var_site);
  TNode<Word32T> args_count = JSParameterCount(args.reg_count());
  // TODO(42200059): Propagate TaggedIndex usage.
  CollectConstructFeedback(context, target, new_target, maybe_feedback_vector,
                           IntPtrToTaggedIndex(Signed(slot_id)),
                           UpdateFeedbackMode::kOptionalFeedback,
                           &try_fast_construct, &construct_array, &var_site);
  BIND(&try_fast_construct);
  {
    Comment("call using FastConstruct builtin");
    GotoIf(TaggedIsSmi(target), &construct_generic);
    GotoIfNot(IsJSFunction(CAST(target)), &construct_generic);
    var_result =
        CallBuiltin(Builtin::kInterpreterPushArgsThenFastConstructFunction,
                    context, args_count, args.base_reg_location(), target,
                    new_target, UndefinedConstant());
    Goto(&return_result);
  }
  BIND(&construct_generic);
  {
    // TODO(bmeurer): Remove the generic type_info parameter from the Construct.
    Comment("call using Construct builtin");
    Builtin builtin = Builtins::InterpreterPushArgsThenConstruct(
        InterpreterPushArgsMode::kOther);
    var_result =
        CallBuiltin(builtin, context, args_count, args.base_reg_location(),
                    target, new_target, UndefinedConstant());
    Goto(&return_result);
  }
  BIND(&construct_array);
  {
    // TODO(bmeurer): Introduce a dedicated builtin to deal with the Array
    // constructor feedback collection inside of Ignition.
    Comment("call using ConstructArray builtin");
    Builtin builtin = Builtins::InterpreterPushArgsThenConstruct(
        InterpreterPushArgsMode::kArrayFunction);
    var_result =
        CallBuiltin(builtin, context, args_count, args.base_reg_location(),
                    target, new_target, var_site.value());
    Goto(&return_result);
  }
  BIND(&return_result);
  return var_result.value();
}
References v8::base::args, v8::internal::compiler::CodeAssembler::builtin(), bytecode_, v8::internal::compiler::CodeAssembler::CallBuiltin(), CAST, v8::internal::compiler::CodeAssembler::Comment(), v8::internal::DCHECK(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::Builtins::InterpreterPushArgsThenConstruct(), v8::internal::CodeStubAssembler::IntPtrToTaggedIndex(), v8::internal::CodeStubAssembler::IsJSFunction(), v8::internal::CodeStubAssembler::JSParameterCount(), v8::internal::kArrayFunction, v8::internal::kOptionalFeedback, v8::internal::kOther, v8::internal::interpreter::Bytecodes::MakesCallAlongCriticalPath(), v8::internal::compiler::CodeAssembler::Signed(), v8::internal::CodeStubAssembler::TaggedIsSmi(), and v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
ConstructForwardAllArgs()
TNode< Object > v8::internal::interpreter::InterpreterAssembler::ConstructForwardAllArgs (TNode< JSAny > target, TNode< Context > context, TNode< JSAny > new_target, TNode< TaggedIndex > slot_id)
Definition at line 1010 of file interpreter-assembler.cc.
                                {
  DCHECK(Bytecodes::MakesCallAlongCriticalPath(bytecode_));
  TVARIABLE(Object, var_result);
  TVARIABLE(AllocationSite, var_site);
#ifndef V8_JITLESS
  Label construct(this);
  TNode<Union<FeedbackVector, Undefined>> maybe_feedback_vector =
      LoadFeedbackVector();
  GotoIf(IsUndefined(maybe_feedback_vector), &construct);
  CollectConstructFeedback(context, target, new_target, maybe_feedback_vector,
                           slot_id, UpdateFeedbackMode::kOptionalFeedback,
                           &construct, &construct, &var_site);
  BIND(&construct);
#endif // !V8_JITLESS
  return CallBuiltin(Builtin::kInterpreterForwardAllArgsThenConstruct, context,
                     target, new_target);
}
References bytecode_, v8::internal::compiler::CodeAssembler::CallBuiltin(), v8::internal::DCHECK(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::kOptionalFeedback, LoadFeedbackVector(), and v8::internal::interpreter::Bytecodes::MakesCallAlongCriticalPath().
ConstructWithSpread()
TNode< Object > v8::internal::interpreter::InterpreterAssembler::ConstructWithSpread (TNode< JSAny > target, TNode< Context > context, TNode< JSAny > new_target, const RegListNodePair & args, TNode< UintPtrT > slot_id)
Definition at line 881 of file interpreter-assembler.cc.
                                                          {
  // TODO(bmeurer): Unify this with the Construct bytecode feedback
  // above once we have a way to pass the AllocationSite to the Array
  // constructor _and_ spread the last argument at the same time.
  DCHECK(Bytecodes::MakesCallAlongCriticalPath(bytecode_));
#ifndef V8_JITLESS
  // TODO(syg): Is the feedback collection logic here the same as
  // CollectConstructFeedback?
  Label extra_checks(this, Label::kDeferred), construct(this);
  TNode<HeapObject> maybe_feedback_vector = LoadFeedbackVector();
  GotoIf(IsUndefined(maybe_feedback_vector), &construct);
  TNode<FeedbackVector> feedback_vector = CAST(maybe_feedback_vector);
  // Increment the call count.
  IncrementCallCount(feedback_vector, slot_id);
  // Check if we have monomorphic {new_target} feedback already.
  TNode<HeapObjectReference> feedback =
      CAST(LoadFeedbackVectorSlot(feedback_vector, slot_id));
  Branch(IsWeakReferenceToObject(feedback, new_target), &construct,
         &extra_checks);
  BIND(&extra_checks);
  {
    Label check_initialized(this), initialize(this), mark_megamorphic(this);
    // Check if it is a megamorphic {new_target}.
    Comment("check if megamorphic");
    TNode<BoolT> is_megamorphic = TaggedEqual(
        feedback,
        HeapConstantNoHole(FeedbackVector::MegamorphicSentinel(isolate())));
    GotoIf(is_megamorphic, &construct);
    Comment("check if weak reference");
    GotoIfNot(IsWeakOrCleared(feedback), &check_initialized);
    // If the weak reference is cleared, we have a new chance to become
    // monomorphic.
    Comment("check if weak reference is cleared");
    Branch(IsCleared(feedback), &initialize, &mark_megamorphic);
    BIND(&check_initialized);
    {
      // Check if it is uninitialized.
      Comment("check if uninitialized");
      TNode<BoolT> is_uninitialized =
          TaggedEqual(feedback, UninitializedSymbolConstant());
      Branch(is_uninitialized, &initialize, &mark_megamorphic);
    }
    BIND(&initialize);
    {
      Comment("check if function in same native context");
      GotoIf(TaggedIsSmi(new_target), &mark_megamorphic);
      // Check if the {new_target} is a JSFunction or JSBoundFunction
      // in the current native context.
      TVARIABLE(HeapObject, var_current, CAST(new_target));
      Label loop(this, &var_current), done_loop(this);
      Goto(&loop);
      BIND(&loop);
      {
        Label if_boundfunction(this), if_function(this);
        TNode<HeapObject> current = var_current.value();
        TNode<Uint16T> current_instance_type = LoadInstanceType(current);
        GotoIf(InstanceTypeEqual(current_instance_type, JS_BOUND_FUNCTION_TYPE),
               &if_boundfunction);
        Branch(IsJSFunctionInstanceType(current_instance_type), &if_function,
               &mark_megamorphic);
        BIND(&if_function);
        {
          // Check that the JSFunction {current} is in the current native
          // context.
          TNode<Context> current_context =
              CAST(LoadObjectField(current, JSFunction::kContextOffset));
          TNode<NativeContext> current_native_context =
              LoadNativeContext(current_context);
          Branch(
              TaggedEqual(LoadNativeContext(context), current_native_context),
              &done_loop, &mark_megamorphic);
        }
        BIND(&if_boundfunction);
        {
          // Continue with the [[BoundTargetFunction]] of {current}.
          var_current = LoadObjectField<HeapObject>(
              current, JSBoundFunction::kBoundTargetFunctionOffset);
          Goto(&loop);
        }
      }
      BIND(&done_loop);
      StoreWeakReferenceInFeedbackVector(feedback_vector, slot_id,
                                         CAST(new_target));
      ReportFeedbackUpdate(feedback_vector, slot_id,
                           "ConstructWithSpread:Initialize");
      Goto(&construct);
    }
    BIND(&mark_megamorphic);
    {
      // MegamorphicSentinel is an immortal immovable object so
      // write-barrier is not needed.
      Comment("transition to megamorphic");
      DCHECK(RootsTable::IsImmortalImmovable(RootIndex::kmegamorphic_symbol));
      StoreFeedbackVectorSlot(
          feedback_vector, slot_id,
          HeapConstantNoHole(FeedbackVector::MegamorphicSentinel(isolate())),
          SKIP_WRITE_BARRIER);
      ReportFeedbackUpdate(feedback_vector, slot_id,
                           "ConstructWithSpread:TransitionMegamorphic");
      Goto(&construct);
    }
  }
  BIND(&construct);
#endif // !V8_JITLESS
  Comment("call using ConstructWithSpread builtin");
  Builtin builtin = Builtins::InterpreterPushArgsThenConstruct(
      InterpreterPushArgsMode::kWithFinalSpread);
  TNode<Word32T> args_count = JSParameterCount(args.reg_count());
  return CallBuiltin(builtin, context, args_count, args.base_reg_location(),
                     target, new_target, UndefinedConstant());
}
References v8::base::args, v8::internal::compiler::CodeAssembler::Branch(), v8::internal::compiler::CodeAssembler::builtin(), bytecode_, v8::internal::compiler::CodeAssembler::CallBuiltin(), CAST, v8::internal::compiler::CodeAssembler::Comment(), v8::internal::DCHECK(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::compiler::CodeAssembler::HeapConstantNoHole(), v8::internal::CodeStubAssembler::IncrementCallCount(), v8::internal::CodeStubAssembler::InstanceTypeEqual(), v8::internal::Builtins::InterpreterPushArgsThenConstruct(), v8::internal::CodeStubAssembler::IsCleared(), v8::internal::RootsTable::IsImmortalImmovable(), v8::internal::CodeStubAssembler::IsJSFunctionInstanceType(), v8::internal::compiler::CodeAssembler::isolate(), v8::internal::CodeStubAssembler::IsWeakOrCleared(), v8::internal::CodeStubAssembler::IsWeakReferenceToObject(), v8::internal::CodeStubAssembler::JSParameterCount(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::kWithFinalSpread, LoadFeedbackVector(), v8::internal::CodeStubAssembler::LoadFeedbackVectorSlot(), v8::internal::CodeStubAssembler::LoadInstanceType(), v8::internal::CodeStubAssembler::LoadNativeContext(), v8::internal::CodeStubAssembler::LoadObjectField(), v8::internal::interpreter::Bytecodes::MakesCallAlongCriticalPath(), v8::internal::FeedbackVector::MegamorphicSentinel(), v8::internal::CodeStubAssembler::ReportFeedbackUpdate(), v8::internal::SKIP_WRITE_BARRIER, v8::internal::CodeStubAssembler::StoreFeedbackVectorSlot(), v8::internal::CodeStubAssembler::StoreWeakReferenceInFeedbackVector(), v8::internal::CodeStubAssembler::TaggedEqual(), v8::internal::CodeStubAssembler::TaggedIsSmi(), and v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
CurrentBytecodeSize()
int v8::internal::interpreter::InterpreterAssembler::CurrentBytecodeSize () const [private]
Definition at line 1670 of file interpreter-assembler.cc.
                                                    {
  return Bytecodes::Size(bytecode_, operand_scale_);
}
References bytecode_, operand_scale_, and v8::internal::interpreter::Bytecodes::Size().
Referenced by Advance(), and DecreaseInterruptBudget().
DecreaseInterruptBudget()
void v8::internal::interpreter::InterpreterAssembler::DecreaseInterruptBudget (TNode< Int32T > weight, StackCheckBehavior stack_check_behavior)
Definition at line 1082 of file interpreter-assembler.cc.
                                                                   {
  Comment("[ DecreaseInterruptBudget");
  Label done(this), interrupt_check(this);
  // Assert that the weight is positive.
  CSA_DCHECK(this, Int32GreaterThanOrEqual(weight, Int32Constant(0)));
  // Make sure we include the current bytecode in the budget calculation.
  TNode<Int32T> weight_after_bytecode =
      Int32Add(weight, Int32Constant(CurrentBytecodeSize()));
  TNode<Int32T> new_budget = UpdateInterruptBudget(weight_after_bytecode);
  Branch(Int32GreaterThanOrEqual(new_budget, Int32Constant(0)), &done,
         &interrupt_check);
  BIND(&interrupt_check);
  TNode<JSFunction> function = LoadFunctionClosure();
  CallRuntime(stack_check_behavior == kEnableStackCheck
                  ? Runtime::kBytecodeBudgetInterruptWithStackCheck_Ignition
                  : Runtime::kBytecodeBudgetInterrupt_Ignition,
              GetContext(), function);
  Goto(&done);
  BIND(&done);
  Comment("] DecreaseInterruptBudget");
}
References v8::internal::compiler::CodeAssembler::Branch(), v8::internal::compiler::CodeAssembler::CallRuntime(), v8::internal::compiler::CodeAssembler::Comment(), CurrentBytecodeSize(), GetContext(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::Int32Add(), v8::internal::compiler::CodeAssembler::Int32Constant(), kEnableStackCheck, LoadFunctionClosure(), and UpdateInterruptBudget().
Referenced by JumpBackward(), OnStackReplacement(), and UpdateInterruptBudgetOnReturn().
DefaultUpdateFeedbackMode()
static constexpr UpdateFeedbackMode v8::internal::interpreter::InterpreterAssembler::DefaultUpdateFeedbackMode () [inline], [static], [constexpr]
Definition at line 158 of file interpreter-assembler.h.
                                                                  {
#ifndef V8_JITLESS
    return UpdateFeedbackMode::kOptionalFeedback;
#else
    return UpdateFeedbackMode::kNoFeedback;
#endif // !V8_JITLESS
  }
References v8::internal::kNoFeedback, and v8::internal::kOptionalFeedback.
Dispatch()
void v8::internal::interpreter::InterpreterAssembler::Dispatch ()
Definition at line 1285 of file interpreter-assembler.cc.
                                    {
  Comment("========= Dispatch");
  DCHECK_IMPLIES(Bytecodes::MakesCallAlongCriticalPath(bytecode_), made_call_);
  TNode<IntPtrT> target_offset = Advance();
  TNode<WordT> target_bytecode = LoadBytecode(target_offset);
  DispatchToBytecodeWithOptionalStarLookahead(target_bytecode);
}
References Advance(), bytecode_, v8::internal::compiler::CodeAssembler::Comment(), DCHECK_IMPLIES, DispatchToBytecodeWithOptionalStarLookahead(), LoadBytecode(), made_call_, and v8::internal::interpreter::Bytecodes::MakesCallAlongCriticalPath().
Referenced by JumpConditional(), JumpConditionalByConstantOperand(), JumpConditionalByImmediateOperand(), and ToNumberOrNumeric().
DispatchTablePointer()
TNode< ExternalReference > v8::internal::interpreter::InterpreterAssembler::DispatchTablePointer () [private]
Definition at line 142 of file interpreter-assembler.cc.
                                                                    {
  if (Bytecodes::MakesCallAlongCriticalPath(bytecode_) && made_call_ &&
      (dispatch_table_.value() ==
       UncheckedParameter<ExternalReference>(
           InterpreterDispatchDescriptor::kDispatchTable))) {
    dispatch_table_ = ExternalConstant(
        ExternalReference::interpreter_dispatch_table_address(isolate()));
  }
  return dispatch_table_.value();
}
References bytecode_, dispatch_table_, v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::internal::compiler::CodeAssembler::isolate(), made_call_, and v8::internal::interpreter::Bytecodes::MakesCallAlongCriticalPath().
Referenced by DispatchToBytecode(), DispatchToBytecodeHandlerEntry(), and DispatchWide().
DispatchToBytecode()
void v8::internal::interpreter::InterpreterAssembler::DispatchToBytecode (TNode< WordT > target_bytecode, TNode< IntPtrT > new_bytecode_offset)
Definition at line 1301 of file interpreter-assembler.cc.
                                                                      {
  if (V8_IGNITION_DISPATCH_COUNTING_BOOL) {
    TraceBytecodeDispatch(target_bytecode);
  }
  TNode<RawPtrT> target_code_entry = Load<RawPtrT>(
      DispatchTablePointer(), TimesSystemPointerSize(target_bytecode));
  DispatchToBytecodeHandlerEntry(target_code_entry, new_bytecode_offset);
}
References DispatchTablePointer(), DispatchToBytecodeHandlerEntry(), v8::internal::CodeStubAssembler::TimesSystemPointerSize(), TraceBytecodeDispatch(), and V8_IGNITION_DISPATCH_COUNTING_BOOL.
Referenced by DispatchToBytecodeWithOptionalStarLookahead(), JumpToOffset(), and StarDispatchLookahead().
DispatchToBytecodeHandlerEntry()
void v8::internal::interpreter::InterpreterAssembler::DispatchToBytecodeHandlerEntry (TNode< RawPtrT > handler_entry, TNode< IntPtrT > bytecode_offset) [private]
Definition at line 1313 of file interpreter-assembler.cc.
                                                                  {
  TailCallBytecodeDispatch(
      InterpreterDispatchDescriptor{}, handler_entry, GetAccumulatorUnchecked(),
      bytecode_offset, BytecodeArrayTaggedPointer(), DispatchTablePointer());
}
References BytecodeArrayTaggedPointer(), DispatchTablePointer(), GetAccumulatorUnchecked(), and v8::internal::compiler::CodeAssembler::TailCallBytecodeDispatch().
Referenced by DispatchToBytecode(), and DispatchWide().
DispatchToBytecodeWithOptionalStarLookahead()
void v8::internal::interpreter::InterpreterAssembler::DispatchToBytecodeWithOptionalStarLookahead (TNode< WordT > target_bytecode)
Definition at line 1293 of file interpreter-assembler.cc.
                                  {
  if (Bytecodes::IsStarLookahead(bytecode_, operand_scale_)) {
    StarDispatchLookahead(target_bytecode);
  }
  DispatchToBytecode(target_bytecode, BytecodeOffset());
}
References bytecode_, BytecodeOffset(), DispatchToBytecode(), v8::internal::interpreter::Bytecodes::IsStarLookahead(), operand_scale_, and StarDispatchLookahead().
Referenced by Dispatch().
DispatchWide()
void v8::internal::interpreter::InterpreterAssembler::DispatchWide (OperandScale operand_scale)
Definition at line 1320 of file interpreter-assembler.cc.
                                                                  {
  // Dispatching a wide bytecode requires treating the prefix
  // bytecode a base pointer into the dispatch table and dispatching
  // the bytecode that follows relative to this base.
  //
  // Indices 0-255 correspond to bytecodes with operand_scale == 0
  // Indices 256-511 correspond to bytecodes with operand_scale == 1
  // Indices 512-767 correspond to bytecodes with operand_scale == 2
  DCHECK_IMPLIES(Bytecodes::MakesCallAlongCriticalPath(bytecode_), made_call_);
  TNode<IntPtrT> next_bytecode_offset = Advance(1);
  TNode<WordT> next_bytecode = LoadBytecode(next_bytecode_offset);
  if (V8_IGNITION_DISPATCH_COUNTING_BOOL) {
    TraceBytecodeDispatch(next_bytecode);
  }
  TNode<IntPtrT> base_index;
  switch (operand_scale) {
    case OperandScale::kDouble:
      base_index = IntPtrConstant(1 << kBitsPerByte);
      break;
    case OperandScale::kQuadruple:
      base_index = IntPtrConstant(2 << kBitsPerByte);
      break;
    default:
      UNREACHABLE();
  }
  TNode<WordT> target_index = IntPtrAdd(base_index, next_bytecode);
  TNode<RawPtrT> target_code_entry = Load<RawPtrT>(
      DispatchTablePointer(), TimesSystemPointerSize(target_index));
  DispatchToBytecodeHandlerEntry(target_code_entry, next_bytecode_offset);
}
References Advance(), bytecode_, DCHECK_IMPLIES, DispatchTablePointer(), DispatchToBytecodeHandlerEntry(), v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::kBitsPerByte, LoadBytecode(), made_call_, v8::internal::interpreter::Bytecodes::MakesCallAlongCriticalPath(), operand_scale(), v8::internal::CodeStubAssembler::TimesSystemPointerSize(), TraceBytecodeDispatch(), v8::internal::UNREACHABLE(), and V8_IGNITION_DISPATCH_COUNTING_BOOL.
ExportParametersAndRegisterFile()
TNode< FixedArray > v8::internal::interpreter::InterpreterAssembler::ExportParametersAndRegisterFile (TNode< FixedArray > array, const RegListNodePair & registers)
Definition at line 1563 of file interpreter-assembler.cc.
                                                               {
  // Store the formal parameters (without receiver) followed by the
  // registers into the generator's internal parameters_and_registers field.
  TNode<IntPtrT> parameter_count = LoadParameterCountWithoutReceiver();
  TNode<UintPtrT> register_count = ChangeUint32ToWord(registers.reg_count());
  if (v8_flags.debug_code) {
    CSA_DCHECK(this, IntPtrEqual(registers.base_reg_location(),
                                 RegisterLocation(Register(0))));
    AbortIfRegisterCountInvalid(array, parameter_count, register_count);
  }
  {
    TVARIABLE(IntPtrT, var_index);
    var_index = IntPtrConstant(0);
    // Iterate over parameters and write them into the array.
    Label loop(this, &var_index), done_loop(this);
    TNode<IntPtrT> reg_base =
        IntPtrConstant(Register::FromParameterIndex(0).ToOperand() + 1);
    Goto(&loop);
    BIND(&loop);
    {
      TNode<IntPtrT> index = var_index.value();
      GotoIfNot(UintPtrLessThan(index, parameter_count), &done_loop);
      TNode<IntPtrT> reg_index = IntPtrAdd(reg_base, index);
      TNode<Object> value = LoadRegister(reg_index);
      StoreFixedArrayElement(array, index, value);
      var_index = IntPtrAdd(index, IntPtrConstant(1));
      Goto(&loop);
    }
    BIND(&done_loop);
  }
  {
    // Iterate over register file and write values into array.
    // The mapping of register to array index must match that used in
    // BytecodeGraphBuilder::VisitResumeGenerator.
    TVARIABLE(IntPtrT, var_index);
    var_index = IntPtrConstant(0);
    Label loop(this, &var_index), done_loop(this);
    Goto(&loop);
    BIND(&loop);
    {
      TNode<IntPtrT> index = var_index.value();
      GotoIfNot(UintPtrLessThan(index, register_count), &done_loop);
      TNode<IntPtrT> reg_index =
          IntPtrSub(IntPtrConstant(Register(0).ToOperand()), index);
      TNode<Object> value = LoadRegister(reg_index);
      TNode<IntPtrT> array_index = IntPtrAdd(parameter_count, index);
      StoreFixedArrayElement(array, array_index, value);
      var_index = IntPtrAdd(index, IntPtrConstant(1));
      Goto(&loop);
    }
    BIND(&done_loop);
  }
  return array;
}
References AbortIfRegisterCountInvalid(), v8::internal::interpreter::InterpreterAssembler::RegListNodePair::base_reg_location(), v8::internal::compiler::CodeAssembler::ChangeUint32ToWord(), v8::internal::interpreter::Register::FromParameterIndex(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::index, v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::compiler::CodeAssembler::IntPtrEqual(), v8::internal::compiler::CodeAssembler::IntPtrSub(), LoadParameterCountWithoutReceiver(), LoadRegister(), v8::internal::interpreter::InterpreterAssembler::RegListNodePair::reg_count(), v8::internal::ETWJITInterface::Register(), RegisterLocation(), v8::internal::CodeStubAssembler::StoreFixedArrayElement(), v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::UintPtrLessThan(), v8::internal::v8_flags, and v8::internal::value.
GetAccumulator()
TNode< Object > v8::internal::interpreter::InterpreterAssembler::GetAccumulator ()
Definition at line 157 of file interpreter-assembler.cc.
                                                   {
  DCHECK(Bytecodes::ReadsAccumulator(bytecode_));
  implicit_register_use_ =
      implicit_register_use_ | ImplicitRegisterUse::kReadAccumulator;
  return GetAccumulatorUnchecked();
}
References bytecode_, v8::internal::DCHECK(), GetAccumulatorUnchecked(), implicit_register_use_, v8::internal::interpreter::kReadAccumulator, and v8::internal::interpreter::Bytecodes::ReadsAccumulator().
Referenced by InlineShortStar(), and ToNumberOrNumeric().
GetAccumulatorUnchecked()
TNode< Object > v8::internal::interpreter::InterpreterAssembler::GetAccumulatorUnchecked () [private]
Definition at line 153 of file interpreter-assembler.cc.
                                                            {
  return accumulator_.value();
}
References accumulator_.
Referenced by DispatchToBytecodeHandlerEntry(), GetAccumulator(), and TraceBytecode().
GetContext()
TNode< Context > v8::internal::interpreter::InterpreterAssembler::GetContext ()
Definition at line 178 of file interpreter-assembler.cc.
                                                {
  return CAST(LoadRegister(Register::current_context()));
}
References CAST, v8::internal::interpreter::Register::current_context(), and LoadRegister().
Referenced by Abort(), DecreaseInterruptBudget(), ToNumberOrNumeric(), and TraceBytecode().
GetContextAtDepth()
TNode< Context > v8::internal::interpreter::InterpreterAssembler::GetContextAtDepth (TNode< Context > context, TNode< Uint32T > depth)
Definition at line 186 of file interpreter-assembler.cc.
                                                                             {
  TVARIABLE(Context, cur_context, context);
  TVARIABLE(Uint32T, cur_depth, depth);
  Label context_found(this);
  Label context_search(this, {&cur_depth, &cur_context});
  // Fast path if the depth is 0.
  Branch(Word32Equal(depth, Int32Constant(0)), &context_found, &context_search);
  // Loop until the depth is 0.
  BIND(&context_search);
  {
    cur_depth = Unsigned(Int32Sub(cur_depth.value(), Int32Constant(1)));
    cur_context = CAST(
        LoadContextElementNoCell(cur_context.value(), Context::PREVIOUS_INDEX));
    Branch(Word32Equal(cur_depth.value(), Int32Constant(0)), &context_found,
           &context_search);
  }
  BIND(&context_found);
  return cur_context.value();
}
References v8::internal::compiler::CodeAssembler::Branch(), CAST, v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::compiler::CodeAssembler::Int32Sub(), v8::internal::Context::PREVIOUS_INDEX, v8::internal::compiler::CodeAssembler::Unsigned(), and v8::internal::compiler::CodeAssembler::Word32Equal().
GetInterpretedFramePointer()
TNode< RawPtrT > v8::internal::interpreter::InterpreterAssembler::GetInterpretedFramePointer () [private]
Definition at line 73 of file interpreter-assembler.cc.
                                                                {
  if (!interpreted_frame_pointer_.IsBound()) {
    interpreted_frame_pointer_ = LoadParentFramePointer();
  } else if (Bytecodes::MakesCallAlongCriticalPath(bytecode_) && made_call_ &&
             !reloaded_frame_ptr_) {
    interpreted_frame_pointer_ = LoadParentFramePointer();
    reloaded_frame_ptr_ = true;
  }
  return interpreted_frame_pointer_.value();
}
References bytecode_, interpreted_frame_pointer_, v8::internal::compiler::CodeAssembler::LoadParentFramePointer(), made_call_, v8::internal::interpreter::Bytecodes::MakesCallAlongCriticalPath(), and reloaded_frame_ptr_.
Referenced by LoadAndUntagRegister(), LoadRegister(), RegisterLocation(), SaveBytecodeOffset(), StoreRegister(), and StoreRegisterForShortStar().
GetRegisterListAtOperandIndex()
InterpreterAssembler::RegListNodePair v8::internal::interpreter::InterpreterAssembler::GetRegisterListAtOperandIndex (int operand_index)
Definition at line 266 of file interpreter-assembler.cc.
                                                                     {
  DCHECK(Bytecodes::IsRegisterListOperandType(
      Bytecodes::GetOperandType(bytecode_, operand_index)));
  DCHECK_EQ(OperandType::kRegCount,
            Bytecodes::GetOperandType(bytecode_, operand_index + 1));
  TNode<IntPtrT> base_reg = RegisterLocation(BytecodeOperandReg(operand_index));
  TNode<Uint32T> reg_count = BytecodeOperandCount(operand_index + 1);
  return RegListNodePair(base_reg, reg_count);
}
References bytecode_, BytecodeOperandCount(), BytecodeOperandReg(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::interpreter::Bytecodes::GetOperandType(), v8::internal::interpreter::Bytecodes::IsRegisterListOperandType(), and RegisterLocation().
ImportRegisterFile()
TNode< FixedArray > v8::internal::interpreter::InterpreterAssembler::ImportRegisterFile (TNode< FixedArray > array, const RegListNodePair & registers)
Definition at line 1632 of file interpreter-assembler.cc.
                                                               {
  TNode<IntPtrT> parameter_count = LoadParameterCountWithoutReceiver();
  TNode<UintPtrT> register_count = ChangeUint32ToWord(registers.reg_count());
  if (v8_flags.debug_code) {
    CSA_DCHECK(this, IntPtrEqual(registers.base_reg_location(),
                                 RegisterLocation(Register(0))));
    AbortIfRegisterCountInvalid(array, parameter_count, register_count);
  }
  TVARIABLE(IntPtrT, var_index, IntPtrConstant(0));
  // Iterate over array and write values into register file. Also erase the
  // array contents to not keep them alive artificially.
  Label loop(this, &var_index), done_loop(this);
  Goto(&loop);
  BIND(&loop);
  {
    TNode<IntPtrT> index = var_index.value();
    GotoIfNot(UintPtrLessThan(index, register_count), &done_loop);
    TNode<IntPtrT> array_index = IntPtrAdd(parameter_count, index);
    TNode<Object> value = LoadFixedArrayElement(array, array_index);
    TNode<IntPtrT> reg_index =
        IntPtrSub(IntPtrConstant(Register(0).ToOperand()), index);
    StoreRegister(value, reg_index);
    StoreFixedArrayElement(array, array_index, StaleRegisterConstant());
    var_index = IntPtrAdd(index, IntPtrConstant(1));
    Goto(&loop);
  }
  BIND(&done_loop);
  return array;
}
References AbortIfRegisterCountInvalid(), v8::internal::interpreter::InterpreterAssembler::RegListNodePair::base_reg_location(), v8::internal::compiler::CodeAssembler::ChangeUint32ToWord(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::index, v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::compiler::CodeAssembler::IntPtrEqual(), v8::internal::compiler::CodeAssembler::IntPtrSub(), v8::internal::CodeStubAssembler::LoadFixedArrayElement(), LoadParameterCountWithoutReceiver(), v8::internal::interpreter::InterpreterAssembler::RegListNodePair::reg_count(), v8::internal::ETWJITInterface::Register(), RegisterLocation(), v8::internal::CodeStubAssembler::StoreFixedArrayElement(), StoreRegister(), v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::UintPtrLessThan(), v8::internal::v8_flags, and v8::internal::value.
InlineShortStar()
void v8::internal::interpreter::InterpreterAssembler::InlineShortStar (TNode< WordT > target_bytecode) [private]
Definition at line 1261 of file interpreter-assembler.cc.
                                                                       {
  Bytecode previous_bytecode = bytecode_;
  ImplicitRegisterUse previous_acc_use = implicit_register_use_;
  // At this point we don't know statically what bytecode we're executing, but
  // kStar0 has the right attributes (namely, no operands) for any of the short
  // Star codes.
  bytecode_ = Bytecode::kStar0;
  implicit_register_use_ = ImplicitRegisterUse::kNone;
#ifdef V8_TRACE_UNOPTIMIZED
  TraceBytecode(Runtime::kTraceUnoptimizedBytecodeEntry);
#endif
  StoreRegisterForShortStar(GetAccumulator(), target_bytecode);
  DCHECK_EQ(implicit_register_use_,
            Bytecodes::GetImplicitRegisterUse(bytecode_));
  Advance();
  bytecode_ = previous_bytecode;
  implicit_register_use_ = previous_acc_use;
}
References Advance(), bytecode_, DCHECK_EQ, GetAccumulator(), v8::internal::interpreter::Bytecodes::GetImplicitRegisterUse(), implicit_register_use_, v8::internal::interpreter::kNone, StoreRegisterForShortStar(), and TraceBytecode().
Referenced by StarDispatchLookahead().
Jump()
void v8::internal::interpreter::InterpreterAssembler::Jump (TNode< IntPtrT > jump_offset)
Definition at line 1135 of file interpreter-assembler.cc.
                                                          {
  JumpToOffset(IntPtrAdd(BytecodeOffset(), jump_offset));
}
References BytecodeOffset(), v8::internal::compiler::CodeAssembler::IntPtrAdd(), and JumpToOffset().
Referenced by JumpConditional(), JumpConditionalByConstantOperand(), and JumpConditionalByImmediateOperand().
JumpBackward()
void v8::internal::interpreter::InterpreterAssembler::JumpBackward (TNode< IntPtrT > jump_offset)
Definition at line 1139 of file interpreter-assembler.cc.
                                                                  {
  DecreaseInterruptBudget(TruncateIntPtrToInt32(jump_offset),
                          kEnableStackCheck);
  JumpToOffset(IntPtrSub(BytecodeOffset(), jump_offset));
}
References BytecodeOffset(), DecreaseInterruptBudget(), v8::internal::compiler::CodeAssembler::IntPtrSub(), JumpToOffset(), kEnableStackCheck, and v8::internal::CodeStubAssembler::TruncateIntPtrToInt32().
Referenced by OnStackReplacement().
JumpConditional()
void v8::internal::interpreter::InterpreterAssembler::JumpConditional (TNode< BoolT > condition, TNode< IntPtrT > jump_offset) [private]
Definition at line 1145 of file interpreter-assembler.cc.
                                                                       {
  Label match(this), no_match(this);
  Branch(condition, &match, &no_match);
  BIND(&match);
  Jump(jump_offset);
  BIND(&no_match);
  Dispatch();
}
References v8::internal::compiler::CodeAssembler::Branch(), Dispatch(), and Jump().
Referenced by JumpIfTaggedEqual(), and JumpIfTaggedNotEqual().
JumpConditionalByConstantOperand()
void v8::internal::interpreter::InterpreterAssembler::JumpConditionalByConstantOperand (TNode< BoolT > condition, int operand_index) [private]
Definition at line 1168 of file interpreter-assembler.cc.
                                               {
  Label match(this), no_match(this);
  Branch(condition, &match, &no_match);
  BIND(&match);
  TNode<IntPtrT> jump_offset =
      LoadAndUntagConstantPoolEntryAtOperandIndex(operand_index);
  Jump(jump_offset);
  BIND(&no_match);
  Dispatch();
}
References v8::internal::compiler::CodeAssembler::Branch(), Dispatch(), Jump(), and LoadAndUntagConstantPoolEntryAtOperandIndex().
Referenced by JumpIfTaggedEqualConstant(), and JumpIfTaggedNotEqualConstant().
JumpConditionalByImmediateOperand()
void v8::internal::interpreter::InterpreterAssembler::JumpConditionalByImmediateOperand (TNode< BoolT > condition, int operand_index) [private]
Definition at line 1156 of file interpreter-assembler.cc.
                                               {
  Label match(this), no_match(this);
  Branch(condition, &match, &no_match);
  BIND(&match);
  TNode<IntPtrT> jump_offset = Signed(BytecodeOperandUImmWord(operand_index));
  Jump(jump_offset);
  BIND(&no_match);
  Dispatch();
}
References v8::internal::compiler::CodeAssembler::Branch(), BytecodeOperandUImmWord(), Dispatch(), Jump(), and v8::internal::compiler::CodeAssembler::Signed().
Referenced by JumpIfTaggedEqual(), and JumpIfTaggedNotEqual().
JumpIfTaggedEqual() [1/2]
void v8::internal::interpreter::InterpreterAssembler::JumpIfTaggedEqual (TNode< Object > lhs, TNode< Object > rhs, int operand_index)
Definition at line 1187 of file interpreter-assembler.cc.
                                                                {
  JumpConditionalByImmediateOperand(TaggedEqual(lhs, rhs), operand_index);
}
References JumpConditionalByImmediateOperand(), and v8::internal::CodeStubAssembler::TaggedEqual().
JumpIfTaggedEqual() [2/2]
void v8::internal::interpreter::InterpreterAssembler::JumpIfTaggedEqual (TNode< Object > lhs, TNode< Object > rhs, TNode< IntPtrT > jump_offset)
Definition at line 1181 of file interpreter-assembler.cc.
                                                                         {
  JumpConditional(TaggedEqual(lhs, rhs), jump_offset);
}
References JumpConditional(), and v8::internal::CodeStubAssembler::TaggedEqual().
JumpIfTaggedEqualConstant()
void v8::internal::interpreter::InterpreterAssembler::JumpIfTaggedEqualConstant (TNode< Object > lhs, TNode< Object > rhs, int operand_index)
Definition at line 1193 of file interpreter-assembler.cc.
                                                                        {
  JumpConditionalByConstantOperand(TaggedEqual(lhs, rhs), operand_index);
}
References JumpConditionalByConstantOperand(), and v8::internal::CodeStubAssembler::TaggedEqual().
JumpIfTaggedNotEqual() [1/2]
void v8::internal::interpreter::InterpreterAssembler::JumpIfTaggedNotEqual (TNode< Object > lhs, TNode< Object > rhs, int operand_index)
Definition at line 1205 of file interpreter-assembler.cc.
                                                                   {
  JumpConditionalByImmediateOperand(TaggedNotEqual(lhs, rhs), operand_index);
}
References JumpConditionalByImmediateOperand(), and v8::internal::CodeStubAssembler::TaggedNotEqual().
JumpIfTaggedNotEqual() [2/2]
void v8::internal::interpreter::InterpreterAssembler::JumpIfTaggedNotEqual (TNode< Object > lhs, TNode< Object > rhs, TNode< IntPtrT > jump_offset)
Definition at line 1199 of file interpreter-assembler.cc.
                                                                            {
  JumpConditional(TaggedNotEqual(lhs, rhs), jump_offset);
}
References JumpConditional(), and v8::internal::CodeStubAssembler::TaggedNotEqual().
JumpIfTaggedNotEqualConstant()
void v8::internal::interpreter::InterpreterAssembler::JumpIfTaggedNotEqualConstant (TNode< Object > lhs, TNode< Object > rhs, int operand_index)
Definition at line 1211 of file interpreter-assembler.cc.
                                                                           {
  JumpConditionalByConstantOperand(TaggedNotEqual(lhs, rhs), operand_index);
}
References JumpConditionalByConstantOperand(), and v8::internal::CodeStubAssembler::TaggedNotEqual().
JumpToOffset()
void v8::internal::interpreter::InterpreterAssembler::JumpToOffset (TNode< IntPtrT > new_bytecode_offset) [private]
Definition at line 1124 of file interpreter-assembler.cc.
                                                                          {
  DCHECK(!Bytecodes::IsStarLookahead(bytecode_, operand_scale_));
#ifdef V8_TRACE_UNOPTIMIZED
  TraceBytecode(Runtime::kTraceUnoptimizedBytecodeExit);
#endif
  bytecode_offset_ = new_bytecode_offset;
  TNode<RawPtrT> target_bytecode =
      UncheckedCast<RawPtrT>(LoadBytecode(new_bytecode_offset));
  DispatchToBytecode(target_bytecode, new_bytecode_offset);
}
References bytecode_, bytecode_offset_, v8::internal::DCHECK(), DispatchToBytecode(), v8::internal::interpreter::Bytecodes::IsStarLookahead(), LoadBytecode(), operand_scale_, and TraceBytecode().
Referenced by Jump(), and JumpBackward().
LoadAndUntagConstantPoolEntry()
TNode< IntPtrT > v8::internal::interpreter::InterpreterAssembler::LoadAndUntagConstantPoolEntry (TNode< WordT > index)
Definition at line 687 of file interpreter-assembler.cc.
                        {
  return SmiUntag(CAST(LoadConstantPoolEntry(index)));
}
References CAST, v8::internal::index, LoadConstantPoolEntry(), and v8::internal::CodeStubAssembler::SmiUntag().
LoadAndUntagConstantPoolEntryAtOperandIndex()
TNode< IntPtrT > v8::internal::interpreter::InterpreterAssembler::LoadAndUntagConstantPoolEntryAtOperandIndex (int operand_index)
Definition at line 699 of file interpreter-assembler.cc.
                       {
  return SmiUntag(CAST(LoadConstantPoolEntryAtOperandIndex(operand_index)));
}
References CAST, LoadConstantPoolEntryAtOperandIndex(), and v8::internal::CodeStubAssembler::SmiUntag().
Referenced by JumpConditionalByConstantOperand().
LoadAndUntagRegister()
TNode< IntPtrT > v8::internal::interpreter::InterpreterAssembler::LoadAndUntagRegister (Register reg)
Definition at line 237 of file interpreter-assembler.cc.
                                                                      {
  TNode<RawPtrT> base = GetInterpretedFramePointer();
  int index = reg.ToOperand() * kSystemPointerSize;
  if (SmiValuesAre32Bits()) {
#if V8_TARGET_LITTLE_ENDIAN
    index += 4;
#endif
    return ChangeInt32ToIntPtr(Load<Int32T>(base, IntPtrConstant(index)));
  } else {
    return SmiToIntPtr(CAST(LoadFullTagged(base, IntPtrConstant(index))));
  }
}
References CAST, v8::internal::compiler::CodeAssembler::ChangeInt32ToIntPtr(), GetInterpretedFramePointer(), v8::internal::index, v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::kSystemPointerSize, v8::internal::compiler::CodeAssembler::LoadFullTagged(), v8::internal::CodeStubAssembler::SmiToIntPtr(), v8::internal::SmiValuesAre32Bits(), and v8::internal::interpreter::Register::ToOperand().
Referenced by ReloadBytecodeOffset().
LoadBytecode()
TNode< WordT > v8::internal::interpreter::InterpreterAssembler::LoadBytecode (TNode< IntPtrT > bytecode_offset) [protected]
Definition at line 1217 of file interpreter-assembler.cc.
                                    {
  TNode<Uint8T> bytecode =
      Load<Uint8T>(BytecodeArrayTaggedPointer(), bytecode_offset);
  return ChangeUint32ToWord(bytecode);
}
References bytecode(), BytecodeArrayTaggedPointer(), and v8::internal::compiler::CodeAssembler::ChangeUint32ToWord().
Referenced by Dispatch(), DispatchWide(), JumpToOffset(), and StarDispatchLookahead().
LoadConstantPoolEntry()
TNode< Object > v8::internal::interpreter::InterpreterAssembler::LoadConstantPoolEntry (TNode< WordT > index)
Definition at line 679 of file interpreter-assembler.cc.
                                                                            {
  TNode<TrustedFixedArray> constant_pool = CAST(LoadProtectedPointerField(
      BytecodeArrayTaggedPointer(), BytecodeArray::kConstantPoolOffset));
  return CAST(LoadArrayElement(constant_pool,
                               OFFSET_OF_DATA_START(TrustedFixedArray),
                               UncheckedCast<IntPtrT>(index), 0));
}
References BytecodeArrayTaggedPointer(), CAST, v8::internal::constant_pool, v8::internal::index, v8::internal::CodeStubAssembler::LoadArrayElement(), v8::internal::CodeStubAssembler::LoadProtectedPointerField(), and OFFSET_OF_DATA_START.
Referenced by LoadAndUntagConstantPoolEntry(), and LoadConstantPoolEntryAtOperandIndex().
LoadConstantPoolEntryAtOperandIndex()
TNode< Object > v8::internal::interpreter::InterpreterAssembler::LoadConstantPoolEntryAtOperandIndex (int operand_index)
Definition at line 692 of file interpreter-assembler.cc.
                       {
  TNode<UintPtrT> index = BytecodeOperandConstantPoolIdx(operand_index);
  return LoadConstantPoolEntry(index);
}
References BytecodeOperandConstantPoolIdx(), v8::internal::index, and LoadConstantPoolEntry().
Referenced by LoadAndUntagConstantPoolEntryAtOperandIndex().
LoadFeedbackVector()
TNode< Union< FeedbackVector, Undefined > > v8::internal::interpreter::InterpreterAssembler::LoadFeedbackVector ()
Definition at line 709 of file interpreter-assembler.cc.
                                         {
  return CAST(LoadRegister(Register::feedback_vector()));
}
References CAST, v8::internal::interpreter::Register::feedback_vector(), and LoadRegister().
Referenced by CallJSWithSpreadAndDispatch(), ConstructForwardAllArgs(), ConstructWithSpread(), and ToNumberOrNumeric().
LoadFeedbackVectorOrUndefinedIfJitless()
auto v8::internal::interpreter::InterpreterAssembler::LoadFeedbackVectorOrUndefinedIfJitless () [inline]
Definition at line 150 of file interpreter-assembler.h.
                                                {
#ifndef V8_JITLESS
    return LoadFeedbackVector();
#else
    return UndefinedConstant();
#endif // V8_JITLESS
  }
References v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
LoadFunctionClosure()
TNode< JSFunction > v8::internal::interpreter::InterpreterAssembler::LoadFunctionClosure ()
Definition at line 704 of file interpreter-assembler.cc.
                                                            {
  return CAST(LoadRegister(Register::function_closure()));
}
References CAST, v8::internal::interpreter::Register::function_closure(), and LoadRegister().
Referenced by DecreaseInterruptBudget(), OnStackReplacement(), and UpdateInterruptBudget().
LoadOsrState()
TNode< Int8T > v8::internal::interpreter::InterpreterAssembler::LoadOsrState (TNode< FeedbackVector > feedback_vector)
Definition at line 1379 of file interpreter-assembler.cc.
                                           {
  // We're loading an 8-bit field, mask it.
  return UncheckedCast<Int8T>(Word32And(
      LoadObjectField<Int8T>(feedback_vector, FeedbackVector::kOsrStateOffset),
      0xFF));
}
References v8::internal::compiler::CodeAssembler::Word32And().
LoadParameterCountWithoutReceiver()
TNode< IntPtrT > v8::internal::interpreter::InterpreterAssembler::LoadParameterCountWithoutReceiver () [protected]
Definition at line 1224 of file interpreter-assembler.cc.
                                                                       {
  TNode<Int32T> parameter_count =
      LoadBytecodeArrayParameterCountWithoutReceiver(
          BytecodeArrayTaggedPointer());
  return ChangeInt32ToIntPtr(parameter_count);
}
References BytecodeArrayTaggedPointer(), v8::internal::compiler::CodeAssembler::ChangeInt32ToIntPtr(), and v8::internal::CodeStubAssembler::LoadBytecodeArrayParameterCountWithoutReceiver().
Referenced by ExportParametersAndRegisterFile(), and ImportRegisterFile().
LoadRegister() [1/2]
TNode< Object > v8::internal::interpreter::InterpreterAssembler::LoadRegister (Register reg)
Definition at line 232 of file interpreter-assembler.cc.
                                                             {
  return LoadFullTagged(GetInterpretedFramePointer(),
                        IntPtrConstant(reg.ToOperand() * kSystemPointerSize));
}
References GetInterpretedFramePointer(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::kSystemPointerSize, v8::internal::compiler::CodeAssembler::LoadFullTagged(), and v8::internal::interpreter::Register::ToOperand().
Referenced by BytecodeArrayTaggedPointer(), ExportParametersAndRegisterFile(), GetContext(), LoadFeedbackVector(), LoadFunctionClosure(), LoadRegisterAtOperandIndex(), and LoadRegisterPairAtOperandIndex().
LoadRegister() [2/2]
TNode< Object > v8::internal::interpreter::InterpreterAssembler::LoadRegister (TNode< IntPtrT > reg_index) [private]
Definition at line 227 of file interpreter-assembler.cc.
                                                                         {
  return LoadFullTagged(GetInterpretedFramePointer(),
                        RegisterFrameOffset(reg_index));
}
References GetInterpretedFramePointer(), v8::internal::compiler::CodeAssembler::LoadFullTagged(), and RegisterFrameOffset().
LoadRegisterAtOperandIndex()
TNode< Object > v8::internal::interpreter::InterpreterAssembler::LoadRegisterAtOperandIndex (int operand_index)
Definition at line 250 of file interpreter-assembler.cc.
                       {
  return LoadRegister(BytecodeOperandReg(operand_index));
}
References BytecodeOperandReg(), and LoadRegister().
Referenced by CallJSWithSpreadAndDispatch().
LoadRegisterFromRegisterList()
TNode< Object > v8::internal::interpreter::InterpreterAssembler::LoadRegisterFromRegisterList (const RegListNodePair & reg_list, int index)
Definition at line 276 of file interpreter-assembler.cc.
                                                {
  TNode<IntPtrT> location = RegisterLocationInRegisterList(reg_list, index);
  return LoadFullTagged(location);
}
References v8::internal::index, v8::internal::compiler::CodeAssembler::LoadFullTagged(), and RegisterLocationInRegisterList().
LoadRegisterPairAtOperandIndex()
std::pair< TNode< Object >, TNode< Object > > v8::internal::interpreter::InterpreterAssembler::LoadRegisterPairAtOperandIndex (int operand_index)
Definition at line 256 of file interpreter-assembler.cc.
                                                                      {
  DCHECK_EQ(OperandType::kRegPair,
            Bytecodes::GetOperandType(bytecode_, operand_index));
  TNode<IntPtrT> first_reg_index = BytecodeOperandReg(operand_index);
  TNode<IntPtrT> second_reg_index = NextRegister(first_reg_index);
  return std::make_pair(LoadRegister(first_reg_index),
                        LoadRegister(second_reg_index));
}
References bytecode_, BytecodeOperandReg(), DCHECK_EQ, v8::internal::interpreter::Bytecodes::GetOperandType(), LoadRegister(), and NextRegister().
NextRegister()
TNode< IntPtrT > v8::internal::interpreter::InterpreterAssembler::NextRegister (TNode< IntPtrT > reg_index) [private]
Definition at line 362 of file interpreter-assembler.cc.
                                                                          {
  // Register indexes are negative, so the next index is minus one.
  return Signed(IntPtrAdd(reg_index, IntPtrConstant(-1)));
}
References v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), and v8::internal::compiler::CodeAssembler::Signed().
Referenced by LoadRegisterPairAtOperandIndex(), StoreRegisterPairAtOperandIndex(), and StoreRegisterTripleAtOperandIndex().
OnStackReplacement()
void v8::internal::interpreter::InterpreterAssembler::OnStackReplacement (TNode< Context > context, TNode< FeedbackVector > feedback_vector, TNode< IntPtrT > relative_jump, TNode< Int32T > loop_depth, TNode< IntPtrT > feedback_slot, TNode< Int8T > osr_state, OnStackReplacementParams params)
Definition at line 1405 of file interpreter-assembler.cc.
                                     {
  // Three cases may cause us to attempt OSR, in the following order:
  //
  // 1) Presence of cached OSR Turbofan/Maglev code.
  // 2) The OSR urgency exceeds the current loop depth - in that case, trigger
  // a Turbofan/Maglev OSR compilation.
  // 3) Presence of cached OSR Sparkplug code.
  TVARIABLE(Object, maybe_target_code, SmiConstant(0));
  Label baseline(this), maybe_osr_to_opt(this), osr_to_opt(this),
      osr_to_sparkplug(this);
  // Case 1).
  {
    Label next(this);
    TNode<MaybeObject> maybe_cached_osr_code =
        LoadFeedbackVectorSlot(feedback_vector, feedback_slot);
    GotoIf(IsCleared(maybe_cached_osr_code), &next);
    maybe_target_code = GetHeapObjectAssumeWeak(maybe_cached_osr_code);
    // Is it marked_for_deoptimization? If yes, clear the slot.
    TNode<CodeWrapper> code_wrapper = CAST(maybe_target_code.value());
    maybe_target_code =
        LoadCodePointerFromObject(code_wrapper, CodeWrapper::kCodeOffset);
    GotoIfNot(IsMarkedForDeoptimization(CAST(maybe_target_code.value())),
              &osr_to_opt);
    StoreFeedbackVectorSlot(feedback_vector, Unsigned(feedback_slot),
                            ClearedValue(), UNSAFE_SKIP_WRITE_BARRIER);
    maybe_target_code = SmiConstant(0);
    Goto(&next);
    BIND(&next);
  }
  // Case 2).
  {
    static_assert(FeedbackVector::OsrUrgencyBits::kShift == 0);
    TNode<Int32T> osr_urgency = Word32And(
        osr_state, Int32Constant(FeedbackVector::OsrUrgencyBits::kMask));
    GotoIf(Uint32LessThan(loop_depth, osr_urgency), &maybe_osr_to_opt);
    Goto(&baseline);
    BIND(&maybe_osr_to_opt);
    {
      TNode<Uint16T> flags = LoadObjectField<Uint16T>(
          feedback_vector, FeedbackVector::kFlagsOffset);
      TNode<Word32T> in_progress = Word32And(
          flags, Int32Constant(FeedbackVector::OsrTieringInProgressBit::kMask));
      GotoIf(Word32Equal(in_progress, 0), &osr_to_opt);
      Goto(&baseline);
    }
    BIND(&baseline);
    // Case 3).
    if (params == OnStackReplacementParams::kBaselineCodeIsCached) {
      Goto(&osr_to_sparkplug);
    } else {
      DCHECK_EQ(params, OnStackReplacementParams::kDefault);
      TNode<SharedFunctionInfo> sfi = LoadObjectField<SharedFunctionInfo>(
          LoadFunctionClosure(), JSFunction::kSharedFunctionInfoOffset);
      GotoIf(SharedFunctionInfoHasBaselineCode(sfi), &osr_to_sparkplug);
      JumpBackward(relative_jump);
    }
  }
  BIND(&osr_to_opt);
  {
    TNode<BytecodeArray> bytecode = BytecodeArrayTaggedPointer();
    TNode<Uint32T> length = LoadAndUntagBytecodeArrayLength(bytecode);
    TNode<Uint32T> weight =
        Uint32Mul(length, Uint32Constant(v8_flags.osr_to_tierup));
    DecreaseInterruptBudget(Signed(weight), kDisableStackCheck);
    TNode<Smi> expected_param_count =
        SmiFromInt32(LoadBytecodeArrayParameterCount(bytecode));
    CallBuiltin(Builtin::kInterpreterOnStackReplacement, context,
                maybe_target_code.value(), expected_param_count);
    UpdateInterruptBudget(Int32Mul(Signed(weight), Int32Constant(-1)));
    JumpBackward(relative_jump);
  }
  BIND(&osr_to_sparkplug);
  {
    // We already compiled the baseline code, so we don't need to handle failed
    // compilation as in the Ignition -> Turbofan case. Therefore we can just
    // tailcall to the OSR builtin.
    SaveBytecodeOffset();
    TailCallBuiltin(Builtin::kInterpreterOnStackReplacement_ToBaseline,
                    context);
  }
}
References bytecode(), BytecodeArrayTaggedPointer(), v8::internal::compiler::CodeAssembler::CallBuiltin(), CAST, v8::internal::CodeStubAssembler::ClearedValue(), DCHECK_EQ, DecreaseInterruptBudget(), v8::internal::flags, v8::internal::CodeStubAssembler::GetHeapObjectAssumeWeak(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::compiler::CodeAssembler::Int32Mul(), v8::internal::CodeStubAssembler::IsCleared(), v8::internal::CodeStubAssembler::IsMarkedForDeoptimization(), JumpBackward(), kDisableStackCheck, v8::internal::length, v8::internal::CodeStubAssembler::LoadAndUntagBytecodeArrayLength(), v8::internal::CodeStubAssembler::LoadBytecodeArrayParameterCount(), v8::internal::CodeStubAssembler::LoadCodePointerFromObject(), v8::internal::CodeStubAssembler::LoadFeedbackVectorSlot(), LoadFunctionClosure(), SaveBytecodeOffset(), v8::internal::CodeStubAssembler::SharedFunctionInfoHasBaselineCode(), v8::internal::compiler::CodeAssembler::Signed(), v8::internal::compiler::CodeAssembler::SmiConstant(), v8::internal::CodeStubAssembler::SmiFromInt32(), v8::internal::CodeStubAssembler::StoreFeedbackVectorSlot(), v8::internal::compiler::CodeAssembler::TailCallBuiltin(), v8::internal::compiler::CodeAssembler::Uint32Constant(), v8::internal::compiler::CodeAssembler::Uint32Mul(), v8::internal::UNSAFE_SKIP_WRITE_BARRIER, v8::internal::compiler::CodeAssembler::Unsigned(), UpdateInterruptBudget(), v8::internal::v8_flags, v8::internal::compiler::CodeAssembler::Word32And(), and v8::internal::compiler::CodeAssembler::Word32Equal().
operand_scale()
OperandScale v8::internal::interpreter::InterpreterAssembler::operand_scale () const [inline], [private]
Definition at line 457 of file interpreter-assembler.h.
{ return operand_scale_; }
Referenced by BytecodeOperandConstantPoolIdx(), BytecodeOperandCount(), BytecodeOperandFlag16(), BytecodeOperandFlag8(), BytecodeOperandIdxInt32(), BytecodeOperandImm(), BytecodeOperandIntrinsicId(), BytecodeOperandNativeContextIndex(), BytecodeOperandReg(), BytecodeOperandRuntimeId(), BytecodeOperandSignedByte(), BytecodeOperandSignedQuad(), BytecodeOperandSignedShort(), BytecodeOperandUImm(), BytecodeOperandUnsignedByte(), BytecodeOperandUnsignedQuad(), BytecodeOperandUnsignedShort(), DispatchWide(), OperandOffset(), ReloadBytecodeOffset(), and SaveBytecodeOffset().
OperandOffset()
TNode< IntPtrT > v8::internal::interpreter::InterpreterAssembler::OperandOffset (int operand_index) [private]
Definition at line 367 of file interpreter-assembler.cc.
                                                                    {
  return IntPtrConstant(
      Bytecodes::GetOperandOffset(bytecode_, operand_index, operand_scale()));
}
References bytecode_, v8::internal::interpreter::Bytecodes::GetOperandOffset(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), and operand_scale().
Referenced by BytecodeOperandSignedByte(), and BytecodeOperandUnsignedByte().
operator=()
InterpreterAssembler& v8::internal::interpreter::InterpreterAssembler::operator= (const InterpreterAssembler &) [delete]
RegisterFrameOffset()
TNode< IntPtrT > v8::internal::interpreter::InterpreterAssembler::RegisterFrameOffset (TNode< IntPtrT > index) [private]
Definition at line 223 of file interpreter-assembler.cc.
                                                                             {
  return TimesSystemPointerSize(index);
}
References v8::internal::index, and v8::internal::CodeStubAssembler::TimesSystemPointerSize().
Referenced by LoadRegister(), RegisterLocation(), RegisterLocationInRegisterList(), StoreRegister(), and StoreRegisterForShortStar().
RegisterLocation() [1/2]
TNode< IntPtrT > v8::internal::interpreter::InterpreterAssembler::RegisterLocation (Register reg) [private]
Definition at line 219 of file interpreter-assembler.cc.
                                                                  {
  return RegisterLocation(IntPtrConstant(reg.ToOperand()));
}
References v8::internal::compiler::CodeAssembler::IntPtrConstant(), and v8::internal::interpreter::Register::ToOperand().
Referenced by ExportParametersAndRegisterFile(), GetRegisterListAtOperandIndex(), and ImportRegisterFile().
RegisterLocation() [2/2]
TNode< IntPtrT > v8::internal::interpreter::InterpreterAssembler::RegisterLocation (TNode< IntPtrT > reg_index) [private]
Definition at line 213 of file interpreter-assembler.cc.
                              {
  return Signed(
      IntPtrAdd(GetInterpretedFramePointer(), RegisterFrameOffset(reg_index)));
}
References GetInterpretedFramePointer(), v8::internal::compiler::CodeAssembler::IntPtrAdd(), RegisterFrameOffset(), and v8::internal::compiler::CodeAssembler::Signed().
RegisterLocationInRegisterList()
TNode< IntPtrT > v8::internal::interpreter::InterpreterAssembler::RegisterLocationInRegisterList (const RegListNodePair & reg_list, int index)
Definition at line 282 of file interpreter-assembler.cc.
                                                {
  CSA_DCHECK(this,
             Uint32GreaterThan(reg_list.reg_count(), Int32Constant(index)));
  TNode<IntPtrT> offset = RegisterFrameOffset(IntPtrConstant(index));
  // Register indexes are negative, so subtract index from base location to get
  // location.
  return Signed(IntPtrSub(reg_list.base_reg_location(), offset));
}
References v8::internal::interpreter::InterpreterAssembler::RegListNodePair::base_reg_location(), v8::internal::index, v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::compiler::CodeAssembler::IntPtrSub(), v8::internal::interpreter::InterpreterAssembler::RegListNodePair::reg_count(), RegisterFrameOffset(), and v8::internal::compiler::CodeAssembler::Signed().
Referenced by LoadRegisterFromRegisterList().
ReloadBytecodeOffset()
TNode< IntPtrT > v8::internal::interpreter::InterpreterAssembler::ReloadBytecodeOffset () [private]
Definition at line 94 of file interpreter-assembler.cc.
                                                          {
  TNode<IntPtrT> offset = LoadAndUntagRegister(Register::bytecode_offset());
  if (operand_scale() != OperandScale::kSingle) {
    // Add one to the offset such that it points to the actual bytecode rather
    // than the Wide / ExtraWide prefix bytecode.
    offset = IntPtrAdd(offset, IntPtrConstant(1));
  }
  return offset;
}
References v8::internal::interpreter::Register::bytecode_offset(), v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), LoadAndUntagRegister(), and operand_scale().
Referenced by BytecodeOffset().
SaveBytecodeOffset()
void v8::internal::interpreter::InterpreterAssembler::SaveBytecodeOffset () [private]
Definition at line 104 of file interpreter-assembler.cc.
                                              {
  TNode<IntPtrT> bytecode_offset = BytecodeOffset();
  if (operand_scale() != OperandScale::kSingle) {
    // Subtract one from the bytecode_offset such that it points to the Wide /
    // ExtraWide prefix bytecode.
    bytecode_offset = IntPtrSub(BytecodeOffset(), IntPtrConstant(1));
  }
  int store_offset =
      Register::bytecode_offset().ToOperand() * kSystemPointerSize;
  TNode<RawPtrT> base = GetInterpretedFramePointer();
  if (SmiValuesAre32Bits()) {
    int zero_offset = store_offset + 4;
    int payload_offset = store_offset;
#if V8_TARGET_LITTLE_ENDIAN
    std::swap(zero_offset, payload_offset);
#endif
    StoreNoWriteBarrier(MachineRepresentation::kWord32, base,
                        IntPtrConstant(zero_offset), Int32Constant(0));
    StoreNoWriteBarrier(MachineRepresentation::kWord32, base,
                        IntPtrConstant(payload_offset),
                        TruncateIntPtrToInt32(bytecode_offset));
  } else {
    StoreFullTaggedNoWriteBarrier(base, IntPtrConstant(store_offset),
                                  SmiTag(bytecode_offset));
  }
}
References v8::internal::interpreter::Register::bytecode_offset(), BytecodeOffset(), GetInterpretedFramePointer(), v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::compiler::CodeAssembler::IntPtrSub(), v8::internal::kSystemPointerSize, v8::internal::kWord32, operand_scale(), v8::internal::CodeStubAssembler::SmiTag(), v8::internal::SmiValuesAre32Bits(), v8::internal::compiler::CodeAssembler::StoreFullTaggedNoWriteBarrier(), v8::internal::compiler::CodeAssembler::StoreNoWriteBarrier(), v8::internal::interpreter::Register::ToOperand(), and v8::internal::CodeStubAssembler::TruncateIntPtrToInt32().
Referenced by CallPrologue(), InterpreterAssembler(), and OnStackReplacement().
SetAccumulator()
void v8::internal::interpreter::InterpreterAssembler::SetAccumulator (TNode< Object > value)
Definition at line 164 of file interpreter-assembler.cc.
                                                             {
  DCHECK(Bytecodes::WritesAccumulator(bytecode_));
  implicit_register_use_ =
      implicit_register_use_ | ImplicitRegisterUse::kWriteAccumulator;
  accumulator_ = value;
}
References accumulator_, bytecode_, v8::internal::DCHECK(), implicit_register_use_, v8::internal::interpreter::kWriteAccumulator, v8::internal::value, and v8::internal::interpreter::Bytecodes::WritesAccumulator().
Referenced by ToNumberOrNumeric().
SetContext()
void v8::internal::interpreter::InterpreterAssembler::SetContext (TNode< Context > value)
Definition at line 182 of file interpreter-assembler.cc.
                                                          {
  StoreRegister(value, Register::current_context());
}
References v8::internal::interpreter::Register::current_context(), StoreRegister(), and v8::internal::value.
StarDispatchLookahead()
void v8::internal::interpreter::InterpreterAssembler::StarDispatchLookahead (TNode< WordT > target_bytecode) [private]
Definition at line 1231 of file interpreter-assembler.cc.
                                                                             {
  Label do_inline_star(this), done(this);
  // Check whether the following opcode is one of the short Star codes. All
  // opcodes higher than the short Star variants are invalid, and invalid
  // opcodes are never deliberately written, so we can use a one-sided check.
  // This is no less secure than the normal-length Star handler, which performs
  // no validation on its operand.
  static_assert(static_cast<int>(Bytecode::kLastShortStar) + 1 ==
                static_cast<int>(Bytecode::kIllegal));
  static_assert(Bytecode::kIllegal == Bytecode::kLast);
  TNode<Int32T> first_short_star_bytecode =
      Int32Constant(static_cast<int>(Bytecode::kFirstShortStar));
  TNode<BoolT> is_star = Uint32GreaterThanOrEqual(
      TruncateWordToInt32(target_bytecode), first_short_star_bytecode);
  Branch(is_star, &do_inline_star, &done);
  BIND(&do_inline_star);
  {
    InlineShortStar(target_bytecode);
    // Rather than merging control flow to a single indirect jump, we can get
    // better branch prediction by duplicating it. This is because the
    // instruction following a merged X + StarN is a bad predictor of the
    // instruction following a non-merged X, and vice versa.
    DispatchToBytecode(LoadBytecode(BytecodeOffset()), BytecodeOffset());
  }
  BIND(&done);
}
References v8::internal::compiler::CodeAssembler::Branch(), BytecodeOffset(), DispatchToBytecode(), InlineShortStar(), v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::interpreter::kFirstShortStar, v8::internal::interpreter::kLast, v8::internal::interpreter::kLastShortStar, LoadBytecode(), and v8::internal::CodeStubAssembler::TruncateWordToInt32().
Referenced by DispatchToBytecodeWithOptionalStarLookahead().
StoreRegister() [1/2]
void v8::internal::interpreter::InterpreterAssembler::StoreRegister (TNode< Object > value, Register reg)
Definition at line 292 of file interpreter-assembler.cc.
                                                                          {
  StoreFullTaggedNoWriteBarrier(
      GetInterpretedFramePointer(),
      IntPtrConstant(reg.ToOperand() * kSystemPointerSize), value);
}
References GetInterpretedFramePointer(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::kSystemPointerSize, v8::internal::compiler::CodeAssembler::StoreFullTaggedNoWriteBarrier(), v8::internal::interpreter::Register::ToOperand(), and v8::internal::value.
Referenced by ImportRegisterFile(), SetContext(), StoreRegisterAtOperandIndex(), StoreRegisterPairAtOperandIndex(), and StoreRegisterTripleAtOperandIndex().
StoreRegister() [2/2]
void v8::internal::interpreter::InterpreterAssembler::StoreRegister (TNode< Object > value, TNode< IntPtrT > reg_index) [private]
Definition at line 298 of file interpreter-assembler.cc.
                                                                   {
  StoreFullTaggedNoWriteBarrier(GetInterpretedFramePointer(),
                                RegisterFrameOffset(reg_index), value);
}
References GetInterpretedFramePointer(), RegisterFrameOffset(), v8::internal::compiler::CodeAssembler::StoreFullTaggedNoWriteBarrier(), and v8::internal::value.
StoreRegisterAtOperandIndex()
void v8::internal::interpreter::InterpreterAssembler::StoreRegisterAtOperandIndex (TNode< Object > value, int operand_index)
Definition at line 333 of file interpreter-assembler.cc.
                                                                          {
  StoreRegister(value, BytecodeOperandReg(operand_index));
}
References BytecodeOperandReg(), StoreRegister(), and v8::internal::value.
StoreRegisterForShortStar()
void v8::internal::interpreter::InterpreterAssembler::StoreRegisterForShortStar (TNode< Object > value, TNode< WordT > opcode) [protected]
Definition at line 304 of file interpreter-assembler.cc.
                                                                          {
  DCHECK(Bytecodes::IsShortStar(bytecode_));
  implicit_register_use_ =
      implicit_register_use_ | ImplicitRegisterUse::kWriteShortStar;
  CSA_DCHECK(
      this, UintPtrGreaterThanOrEqual(opcode, UintPtrConstant(static_cast<int>(
                                                  Bytecode::kFirstShortStar))));
  CSA_DCHECK(
      this,
      UintPtrLessThanOrEqual(
          opcode, UintPtrConstant(static_cast<int>(Bytecode::kLastShortStar))));
  // Compute the constant that we can add to a Bytecode value to map the range
  // [Bytecode::kStar15, Bytecode::kStar0] to the range
  // [Register(15).ToOperand(), Register(0).ToOperand()].
  constexpr int short_star_to_operand =
      Register(0).ToOperand() - static_cast<int>(Bytecode::kStar0);
  // Make sure the values count in the right direction.
  static_assert(short_star_to_operand ==
                Register(1).ToOperand() - static_cast<int>(Bytecode::kStar1));
  TNode<IntPtrT> offset =
      IntPtrAdd(RegisterFrameOffset(Signed(opcode)),
                IntPtrConstant(short_star_to_operand * kSystemPointerSize));
  StoreFullTaggedNoWriteBarrier(GetInterpretedFramePointer(), offset, value);
}
References bytecode_, v8::internal::DCHECK(), GetInterpretedFramePointer(), implicit_register_use_, v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::interpreter::Bytecodes::IsShortStar(), v8::internal::interpreter::kFirstShortStar, v8::internal::interpreter::kLastShortStar, v8::internal::kSystemPointerSize, v8::internal::interpreter::kWriteShortStar, v8::internal::ETWJITInterface::Register(), RegisterFrameOffset(), v8::internal::compiler::CodeAssembler::Signed(), v8::internal::compiler::CodeAssembler::StoreFullTaggedNoWriteBarrier(), v8::internal::compiler::CodeAssembler::UintPtrConstant(), v8::internal::CodeStubAssembler::UintPtrLessThanOrEqual, and v8::internal::value.
Referenced by InlineShortStar().
StoreRegisterPairAtOperandIndex()
void v8::internal::interpreter::InterpreterAssembler::StoreRegisterPairAtOperandIndex (TNode< Object > value1, TNode< Object > value2, int operand_index)
Definition at line 338 of file interpreter-assembler.cc.
                                                                              {
  DCHECK_EQ(OperandType::kRegOutPair,
            Bytecodes::GetOperandType(bytecode_, operand_index));
  TNode<IntPtrT> first_reg_index = BytecodeOperandReg(operand_index);
  StoreRegister(value1, first_reg_index);
  TNode<IntPtrT> second_reg_index = NextRegister(first_reg_index);
  StoreRegister(value2, second_reg_index);
}
References bytecode_, BytecodeOperandReg(), DCHECK_EQ, v8::internal::interpreter::Bytecodes::GetOperandType(), NextRegister(), and StoreRegister().
StoreRegisterTripleAtOperandIndex()
void v8::internal::interpreter::InterpreterAssembler::StoreRegisterTripleAtOperandIndex (TNode< Object > value1, TNode< Object > value2, TNode< Object > value3, int operand_index)
Definition at line 349 of file interpreter-assembler.cc.
                       {
  DCHECK_EQ(OperandType::kRegOutTriple,
            Bytecodes::GetOperandType(bytecode_, operand_index));
  TNode<IntPtrT> first_reg_index = BytecodeOperandReg(operand_index);
  StoreRegister(value1, first_reg_index);
  TNode<IntPtrT> second_reg_index = NextRegister(first_reg_index);
  StoreRegister(value2, second_reg_index);
  TNode<IntPtrT> third_reg_index = NextRegister(second_reg_index);
  StoreRegister(value3, third_reg_index);
}
References bytecode_, BytecodeOperandReg(), DCHECK_EQ, v8::internal::interpreter::Bytecodes::GetOperandType(), NextRegister(), and StoreRegister().
TargetSupportsUnalignedAccess()
bool v8::internal::interpreter::InterpreterAssembler::TargetSupportsUnalignedAccess () [static], [protected]
Definition at line 1533 of file interpreter-assembler.cc.
                                                         {
#if V8_TARGET_ARCH_MIPS64 || V8_TARGET_ARCH_RISCV64 || V8_TARGET_ARCH_RISCV32
  return false;
#elif V8_TARGET_ARCH_IA32 || V8_TARGET_ARCH_X64 || V8_TARGET_ARCH_S390X || \
    V8_TARGET_ARCH_ARM || V8_TARGET_ARCH_ARM64 || V8_TARGET_ARCH_PPC64 || \
    V8_TARGET_ARCH_LOONG64
  return true;
#else
#error "Unknown Architecture"
#endif
}
Referenced by BytecodeOperandReadUnaligned(), BytecodeOperandSignedQuad(), BytecodeOperandSignedShort(), BytecodeOperandUnsignedQuad(), and BytecodeOperandUnsignedShort().
ToNumberOrNumeric()
void v8::internal::interpreter::InterpreterAssembler::ToNumberOrNumeric (Object::Conversion mode) [protected]
Definition at line 1674 of file interpreter-assembler.cc.
                                                                  {
  TNode<Object> object = GetAccumulator();
  TNode<Context> context = GetContext();
  TVARIABLE(Smi, var_type_feedback);
  TVARIABLE(Numeric, var_result);
  Label if_done(this), if_objectissmi(this), if_objectisheapnumber(this),
      if_objectisother(this, Label::kDeferred);
  GotoIf(TaggedIsSmi(object), &if_objectissmi);
  Branch(IsHeapNumber(CAST(object)), &if_objectisheapnumber, &if_objectisother);
  BIND(&if_objectissmi);
  {
    var_result = CAST(object);
    var_type_feedback = SmiConstant(BinaryOperationFeedback::kSignedSmall);
    Goto(&if_done);
  }
  BIND(&if_objectisheapnumber);
  {
    var_result = CAST(object);
    var_type_feedback = SmiConstant(BinaryOperationFeedback::kNumber);
    Goto(&if_done);
  }
  BIND(&if_objectisother);
  {
    auto builtin = Builtin::kNonNumberToNumber;
    if (mode == Object::Conversion::kToNumeric) {
      builtin = Builtin::kNonNumberToNumeric;
      // Special case for collecting BigInt feedback.
      Label not_bigint(this);
      GotoIfNot(IsBigInt(CAST(object)), &not_bigint);
      {
        var_result = CAST(object);
        var_type_feedback = SmiConstant(BinaryOperationFeedback::kBigInt);
        Goto(&if_done);
      }
      BIND(&not_bigint);
    }
    // Convert {object} by calling out to the appropriate builtin.
    var_result = CAST(CallBuiltin(builtin, context, object));
    var_type_feedback = SmiConstant(BinaryOperationFeedback::kAny);
    Goto(&if_done);
  }
  BIND(&if_done);
  // Record the type feedback collected for {object}.
  TNode<UintPtrT> slot_index = BytecodeOperandIdx(0);
  TNode<HeapObject> maybe_feedback_vector = LoadFeedbackVector();
  MaybeUpdateFeedback(var_type_feedback.value(), maybe_feedback_vector,
                      slot_index);
  SetAccumulator(var_result.value());
  Dispatch();
}
References v8::internal::compiler::CodeAssembler::Branch(), v8::internal::compiler::CodeAssembler::builtin(), BytecodeOperandIdx(), v8::internal::compiler::CodeAssembler::CallBuiltin(), CAST, Dispatch(), GetAccumulator(), GetContext(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::CodeStubAssembler::IsBigInt(), v8::internal::BinaryOperationFeedback::kAny, v8::internal::BinaryOperationFeedback::kBigInt, v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::BinaryOperationFeedback::kNumber, v8::internal::BinaryOperationFeedback::kSignedSmall, v8::internal::Object::kToNumeric, LoadFeedbackVector(), v8::internal::CodeStubAssembler::MaybeUpdateFeedback(), mode(), SetAccumulator(), v8::internal::compiler::CodeAssembler::SmiConstant(), and v8::internal::CodeStubAssembler::TaggedIsSmi().
TraceBytecode()
void v8::internal::interpreter::InterpreterAssembler::TraceBytecode (Runtime::FunctionId function_id) [private]
Definition at line 1500 of file interpreter-assembler.cc.
                                                                      {
  CallRuntime(function_id, GetContext(), BytecodeArrayTaggedPointer(),
              SmiTag(BytecodeOffset()), GetAccumulatorUnchecked());
}
References BytecodeArrayTaggedPointer(), BytecodeOffset(), v8::internal::compiler::CodeAssembler::CallRuntime(), GetAccumulatorUnchecked(), GetContext(), and v8::internal::CodeStubAssembler::SmiTag().
Referenced by InlineShortStar(), InterpreterAssembler(), and JumpToOffset().
TraceBytecodeDispatch()
void v8::internal::interpreter::InterpreterAssembler::TraceBytecodeDispatch (TNode< WordT > target_bytecode) [private]
Definition at line 1505 of file interpreter-assembler.cc.
                                                                             {
  TNode<ExternalReference> counters_table = ExternalConstant(
      ExternalReference::interpreter_dispatch_counters(isolate()));
  TNode<IntPtrT> source_bytecode_table_index = IntPtrConstant(
      static_cast<int>(bytecode_) * (static_cast<int>(Bytecode::kLast) + 1));
  TNode<WordT> counter_offset = TimesSystemPointerSize(
      IntPtrAdd(source_bytecode_table_index, target_bytecode));
  TNode<IntPtrT> old_counter = Load<IntPtrT>(counters_table, counter_offset);
  Label counter_ok(this), counter_saturated(this, Label::kDeferred);
  TNode<BoolT> counter_reached_max = WordEqual(
      old_counter, IntPtrConstant(std::numeric_limits<uintptr_t>::max()));
  Branch(counter_reached_max, &counter_saturated, &counter_ok);
  BIND(&counter_ok);
  {
    TNode<IntPtrT> new_counter = IntPtrAdd(old_counter, IntPtrConstant(1));
    StoreNoWriteBarrier(MachineType::PointerRepresentation(), counters_table,
                        counter_offset, new_counter);
    Goto(&counter_saturated);
  }
  BIND(&counter_saturated);
}
References v8::internal::compiler::CodeAssembler::Branch(), bytecode_, v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::compiler::CodeAssembler::isolate(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::interpreter::kLast, v8::internal::MachineType::PointerRepresentation(), v8::internal::compiler::CodeAssembler::StoreNoWriteBarrier(), v8::internal::CodeStubAssembler::TimesSystemPointerSize(), and v8::internal::compiler::CodeAssembler::WordEqual().
Referenced by DispatchToBytecode(), and DispatchWide().
UpdateInterruptBudget()
TNode< Int32T > v8::internal::interpreter::InterpreterAssembler::UpdateInterruptBudget (TNode< Int32T > weight)
Definition at line 1066 of file interpreter-assembler.cc.
                          {
  TNode<JSFunction> function = LoadFunctionClosure();
  TNode<FeedbackCell> feedback_cell =
      LoadObjectField<FeedbackCell>(function, JSFunction::kFeedbackCellOffset);
  TNode<Int32T> old_budget = LoadObjectField<Int32T>(
      feedback_cell, FeedbackCell::kInterruptBudgetOffset);
  // Update budget by |weight| and check if it reaches zero.
  TNode<Int32T> new_budget = Int32Sub(old_budget, weight);
  // Update budget.
  StoreObjectFieldNoWriteBarrier(
      feedback_cell, FeedbackCell::kInterruptBudgetOffset, new_budget);
  return new_budget;
}
References v8::internal::compiler::CodeAssembler::Int32Sub(), LoadFunctionClosure(), and v8::internal::CodeStubAssembler::StoreObjectFieldNoWriteBarrier().
Referenced by DecreaseInterruptBudget(), and OnStackReplacement().
UpdateInterruptBudgetOnReturn()
void v8::internal::interpreter::InterpreterAssembler::UpdateInterruptBudgetOnReturn ()
Definition at line 1354 of file interpreter-assembler.cc.
                                                         {
  // TODO(rmcilroy): Investigate whether it is worth supporting self
  // optimization of primitive functions like FullCodegen.
  // Update profiling count by the number of bytes between the end of the
  // current bytecode and the start of the first one, to simulate backedge to
  // start of function.
  //
  // With headers and current offset, the bytecode array layout looks like:
  //
  // <---------- simulated backedge ----------
  // | header | first bytecode | .... | return bytecode |
  // |<------ current offset ------->
  // ^ tagged bytecode array pointer
  //
  // UpdateInterruptBudget already handles adding the bytecode size to the
  // length of the back-edge, so we just have to correct for the non-zero offset
  // of the first bytecode.
  TNode<Int32T> profiling_weight =
      Int32Sub(TruncateIntPtrToInt32(BytecodeOffset()),
               Int32Constant(kFirstBytecodeOffset));
  DecreaseInterruptBudget(profiling_weight, kDisableStackCheck);
}
References BytecodeOffset(), DecreaseInterruptBudget(), v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::compiler::CodeAssembler::Int32Sub(), kDisableStackCheck, kFirstBytecodeOffset, and v8::internal::CodeStubAssembler::TruncateIntPtrToInt32().
Member Data Documentation
accumulator_
CodeStubAssembler::TVariable<Object> v8::internal::interpreter::InterpreterAssembler::accumulator_ [private]
Definition at line 465 of file interpreter-assembler.h.
Referenced by ClobberAccumulator(), GetAccumulatorUnchecked(), and SetAccumulator().
bytecode_
Bytecode v8::internal::interpreter::InterpreterAssembler::bytecode_ [private]
Definition at line 459 of file interpreter-assembler.h.
Referenced by BytecodeOffset(), BytecodeOperandConstantPoolIdx(), BytecodeOperandCount(), BytecodeOperandFlag16(), BytecodeOperandFlag8(), BytecodeOperandIdxInt32(), BytecodeOperandImm(), BytecodeOperandIntrinsicId(), BytecodeOperandNativeContextIndex(), BytecodeOperandReg(), BytecodeOperandRuntimeId(), BytecodeOperandSignedByte(), BytecodeOperandSignedQuad(), BytecodeOperandSignedShort(), BytecodeOperandUImm(), BytecodeOperandUnsignedByte(), BytecodeOperandUnsignedQuad(), BytecodeOperandUnsignedShort(), BytecodeSignedOperand(), BytecodeUnsignedOperand(), CallJSAndDispatch(), CallJSWithSpreadAndDispatch(), CallPrologue(), CallRuntimeN(), ClobberAccumulator(), Construct(), ConstructForwardAllArgs(), ConstructWithSpread(), CurrentBytecodeSize(), Dispatch(), DispatchTablePointer(), DispatchToBytecodeWithOptionalStarLookahead(), DispatchWide(), GetAccumulator(), GetInterpretedFramePointer(), GetRegisterListAtOperandIndex(), InlineShortStar(), JumpToOffset(), LoadRegisterPairAtOperandIndex(), OperandOffset(), SetAccumulator(), StoreRegisterForShortStar(), StoreRegisterPairAtOperandIndex(), StoreRegisterTripleAtOperandIndex(), TraceBytecodeDispatch(), and ~InterpreterAssembler().
bytecode_array_
CodeStubAssembler::TVariable<BytecodeArray> v8::internal::interpreter::InterpreterAssembler::bytecode_array_ [private]
Definition at line 462 of file interpreter-assembler.h.
Referenced by BytecodeArrayTaggedPointer().
bytecode_array_valid_
bool v8::internal::interpreter::InterpreterAssembler::bytecode_array_valid_ [private]
Definition at line 469 of file interpreter-assembler.h.
Referenced by BytecodeArrayTaggedPointer(), and CallPrologue().
bytecode_offset_
CodeStubAssembler::TVariable<IntPtrT> v8::internal::interpreter::InterpreterAssembler::bytecode_offset_ [private]
Definition at line 463 of file interpreter-assembler.h.
Referenced by Advance(), BytecodeOffset(), and JumpToOffset().
dispatch_table_
CodeStubAssembler::TVariable<ExternalReference> v8::internal::interpreter::InterpreterAssembler::dispatch_table_ [private]
Definition at line 464 of file interpreter-assembler.h.
Referenced by DispatchTablePointer().
implicit_register_use_
ImplicitRegisterUse v8::internal::interpreter::InterpreterAssembler::implicit_register_use_ [private]
Definition at line 466 of file interpreter-assembler.h.
Referenced by CallJSAndDispatch(), CallJSWithSpreadAndDispatch(), ClobberAccumulator(), GetAccumulator(), InlineShortStar(), SetAccumulator(), StoreRegisterForShortStar(), and ~InterpreterAssembler().
interpreted_frame_pointer_
CodeStubAssembler::TVariable<RawPtrT> v8::internal::interpreter::InterpreterAssembler::interpreted_frame_pointer_ [private]
Definition at line 461 of file interpreter-assembler.h.
Referenced by GetInterpretedFramePointer().
kFirstBytecodeOffset
constexpr int v8::internal::interpreter::InterpreterAssembler::kFirstBytecodeOffset [static], [constexpr]
Initial value:
=
      BytecodeArray::kHeaderSize - kHeapObjectTag
Definition at line 315 of file interpreter-assembler.h.
Referenced by UpdateInterruptBudgetOnReturn().
made_call_
bool v8::internal::interpreter::InterpreterAssembler::made_call_ [private]
Definition at line 467 of file interpreter-assembler.h.
Referenced by BytecodeOffset(), CallPrologue(), Dispatch(), DispatchTablePointer(), DispatchWide(), and GetInterpretedFramePointer().
operand_scale_
OperandScale v8::internal::interpreter::InterpreterAssembler::operand_scale_ [private]
Definition at line 460 of file interpreter-assembler.h.
Referenced by CurrentBytecodeSize(), DispatchToBytecodeWithOptionalStarLookahead(), and JumpToOffset().
reloaded_frame_ptr_
bool v8::internal::interpreter::InterpreterAssembler::reloaded_frame_ptr_ [private]
Definition at line 468 of file interpreter-assembler.h.
Referenced by GetInterpretedFramePointer().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/interpreter/interpreter-assembler.h
/mnt/V8SourceCode/src/interpreter/interpreter-assembler.cc