v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor Class Reference
Classes
class BFEntry
Static Public Member Functions
static void CompileFilter (Zone *zone, RegExpTree *tree, BytecodeAssembler &assembler, const ZoneMap< int, int > &quantifier_id_remapping, const ZoneMap< int, int > &lookaround_id_remapping)
Private Member Functions
FilterGroupsCompileVisitor (BytecodeAssembler &assembler, Zone *zone, const ZoneMap< int, int > &quantifier_id_remapping, const ZoneMap< int, int > &lookaround_id_remapping)
void * VisitDisjunction (RegExpDisjunction *node, void *) override
void * VisitAlternative (RegExpAlternative *node, void *) override
void * VisitClassRanges (RegExpClassRanges *node, void *) override
void * VisitClassSetOperand (RegExpClassSetOperand *node, void *) override
void * VisitClassSetExpression (RegExpClassSetExpression *node, void *) override
void * VisitAssertion (RegExpAssertion *node, void *) override
void * VisitAtom (RegExpAtom *node, void *) override
void * VisitText (RegExpText *node, void *) override
void * VisitQuantifier (RegExpQuantifier *node, void *) override
void * VisitCapture (RegExpCapture *node, void *) override
void * VisitGroup (RegExpGroup *node, void *) override
void * VisitLookaround (RegExpLookaround *node, void *) override
void * VisitBackReference (RegExpBackReference *node, void *) override
void * VisitEmpty (RegExpEmpty *node, void *) override
Private Attributes
Zone * zone_
BytecodeAssembler & assembler_
ZoneLinkedList< BFEntry > nodes_
bool can_compile_node_
const ZoneMap< int, int > & quantifier_id_remapping_
const ZoneMap< int, int > & lookaround_id_remapping_
Detailed Description
Definition at line 388 of file experimental-compiler.cc.
Constructor & Destructor Documentation
FilterGroupsCompileVisitor()
v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::FilterGroupsCompileVisitor (BytecodeAssembler & assembler, Zone * zone, const ZoneMap< int, int > & quantifier_id_remapping, const ZoneMap< int, int > & lookaround_id_remapping) [inline], [private]
Definition at line 424 of file experimental-compiler.cc.
      : zone_(zone),
        assembler_(assembler),
        nodes_(zone_),
        can_compile_node_(false),
        quantifier_id_remapping_(quantifier_id_remapping),
        lookaround_id_remapping_(lookaround_id_remapping) {}
Member Function Documentation
CompileFilter()
static void v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::CompileFilter (Zone * zone, RegExpTree * tree, BytecodeAssembler & assembler, const ZoneMap< int, int > & quantifier_id_remapping, const ZoneMap< int, int > & lookaround_id_remapping) [inline], [static]
Definition at line 390 of file experimental-compiler.cc.
                                                                              {
    /* To filter out groups that were not matched in the last iteration of a
     * quantifier, the regexp's AST is compiled using a special sets of
     * instructions: `FILTER_GROUP`, `FILTER_QUANTIFIER` and `FILTER_CHILD`.
     * They encode a simplified AST containing only the groups and quantifiers.
     * Each node is represented as either a `FILTER_GROUP` or a
     * `FILTER_QUANTIFIER` instruction, containing the index of the respective
     * group or quantifier, followed by a variable number of `FILTER_CHILD`
     * instructions each containing the index of their respective node in the
     * bytecode.
     *
     * The regexp's AST is traversed in breadth-first mode, compiling one node
     * at a time, while saving its children in a queue. */
    FilterGroupsCompileVisitor visitor(assembler, zone, quantifier_id_remapping,
                                       lookaround_id_remapping);
    tree->Accept(&visitor, nullptr);
    while (!visitor.nodes_.empty()) {
      auto& entry = visitor.nodes_.front();
      visitor.assembler_.Bind(entry.label);
      visitor.can_compile_node_ = true;
      entry.node->Accept(&visitor, nullptr);
      visitor.nodes_.pop_front();
    }
  }
References v8::internal::RegExpTree::Accept(), assembler_, v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::Bind(), can_compile_node_, and nodes_.
VisitAlternative()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::VisitAlternative (RegExpAlternative * node, void *) [inline], [override], [private]
Definition at line 441 of file experimental-compiler.cc.
                                                                  {
    for (RegExpTree* alt : *node->nodes()) {
      alt->Accept(this, nullptr);
    }
    return nullptr;
  }
References v8::internal::RegExpAlternative::nodes().
VisitAssertion()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::VisitAssertion (RegExpAssertion * node, void *) [inline], [override], [private]
Definition at line 461 of file experimental-compiler.cc.
                                                              {
    return nullptr;
  }
VisitAtom()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::VisitAtom (RegExpAtom * node, void *) [inline], [override], [private]
Definition at line 465 of file experimental-compiler.cc.
{ return nullptr; }
VisitBackReference()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::VisitBackReference (RegExpBackReference * node, void *) [inline], [override], [private]
Definition at line 521 of file experimental-compiler.cc.
                                                                      {
    return nullptr;
  }
VisitCapture()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::VisitCapture (RegExpCapture * node, void *) [inline], [override], [private]
Definition at line 486 of file experimental-compiler.cc.
                                                          {
    if (can_compile_node_) {
      assembler_.FilterGroup(node->index());
      can_compile_node_ = false;
      node->body()->Accept(this, nullptr);
    } else {
      nodes_.emplace_back(node);
      assembler_.FilterChild(nodes_.back().label);
    }
    return nullptr;
  }
References v8::internal::RegExpTree::Accept(), v8::internal::RegExpCapture::body(), and v8::internal::RegExpCapture::index().
VisitClassRanges()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::VisitClassRanges (RegExpClassRanges * node, void *) [inline], [override], [private]
Definition at line 448 of file experimental-compiler.cc.
                                                                  {
    return nullptr;
  }
VisitClassSetExpression()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::VisitClassSetExpression (RegExpClassSetExpression * node, void *) [inline], [override], [private]
Definition at line 456 of file experimental-compiler.cc.
                                                {
    return nullptr;
  }
VisitClassSetOperand()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::VisitClassSetOperand (RegExpClassSetOperand * node, void *) [inline], [override], [private]
Definition at line 452 of file experimental-compiler.cc.
                                                                          {
    return nullptr;
  }
VisitDisjunction()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::VisitDisjunction (RegExpDisjunction * node, void *) [inline], [override], [private]
Definition at line 434 of file experimental-compiler.cc.
                                                                  {
    for (RegExpTree* alt : *node->alternatives()) {
      alt->Accept(this, nullptr);
    }
    return nullptr;
  }
References v8::internal::RegExpDisjunction::alternatives().
VisitEmpty()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::VisitEmpty (RegExpEmpty * node, void *) [inline], [override], [private]
Definition at line 525 of file experimental-compiler.cc.
{ return nullptr; }
VisitGroup()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::VisitGroup (RegExpGroup * node, void *) [inline], [override], [private]
Definition at line 499 of file experimental-compiler.cc.
                                                      {
    node->body()->Accept(this, nullptr);
    return nullptr;
  }
References v8::internal::RegExpTree::Accept(), and v8::internal::RegExpGroup::body().
VisitLookaround()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::VisitLookaround (RegExpLookaround * node, void *) [inline], [override], [private]
Definition at line 504 of file experimental-compiler.cc.
                                                                {
    if (can_compile_node_) {
      assembler_.FilterLookaround(lookaround_id_remapping_.at(node->index()));
      can_compile_node_ = false;
      node->body()->Accept(this, nullptr);
    } else {
      if (node->CaptureRegisters().is_empty()) {
        return nullptr;
      }
      nodes_.emplace_back(node);
      assembler_.FilterChild(nodes_.back().label);
    }
    return nullptr;
  }
References v8::internal::RegExpTree::Accept(), v8::internal::RegExpLookaround::body(), v8::internal::RegExpLookaround::CaptureRegisters(), v8::internal::RegExpLookaround::index(), and v8::internal::Interval::is_empty().
VisitQuantifier()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::VisitQuantifier (RegExpQuantifier * node, void *) [inline], [override], [private]
Definition at line 469 of file experimental-compiler.cc.
                                                                {
    if (can_compile_node_) {
      assembler_.FilterQuantifier(quantifier_id_remapping_.at(node->index()));
      can_compile_node_ = false;
      node->body()->Accept(this, nullptr);
    } else {
      if (node->CaptureRegisters().is_empty()) {
        return nullptr;
      }
      nodes_.emplace_back(node);
      assembler_.FilterChild(nodes_.back().label);
    }
    return nullptr;
  }
References v8::internal::RegExpTree::Accept(), v8::internal::RegExpQuantifier::body(), v8::internal::RegExpQuantifier::CaptureRegisters(), v8::internal::RegExpQuantifier::index(), and v8::internal::Interval::is_empty().
VisitText()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::VisitText (RegExpText * node, void *) [inline], [override], [private]
Definition at line 467 of file experimental-compiler.cc.
{ return nullptr; }
Member Data Documentation
assembler_
BytecodeAssembler& v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::assembler_ [private]
Definition at line 538 of file experimental-compiler.cc.
Referenced by CompileFilter().
can_compile_node_
bool v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::can_compile_node_ [private]
Definition at line 544 of file experimental-compiler.cc.
Referenced by CompileFilter().
lookaround_id_remapping_
const ZoneMap<int, int>& v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::lookaround_id_remapping_ [private]
Definition at line 550 of file experimental-compiler.cc.
nodes_
ZoneLinkedList<BFEntry> v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::nodes_ [private]
Definition at line 539 of file experimental-compiler.cc.
Referenced by CompileFilter().
quantifier_id_remapping_
const ZoneMap<int, int>& v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::quantifier_id_remapping_ [private]
Definition at line 546 of file experimental-compiler.cc.
zone_
Zone* v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::zone_ [private]
Definition at line 536 of file experimental-compiler.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/regexp/experimental/experimental-compiler.cc