v8::internal::compiler::turboshaft::OpIndex Class Reference
#include <index.h>
Public Member Functions
constexpr OpIndex ()
template<typename T , typename C >
OpIndex (const ConstOrV< T, C > &)
constexpr uint32_t id () const
uint32_t hash () const
uint32_t offset () const
constexpr bool valid () const
uint32_t DecodeTurbofanNodeId () const
bool IsTurbofanNodeId () const
constexpr bool operator== (OpIndex other) const
constexpr bool operator!= (OpIndex other) const
constexpr bool operator< (OpIndex other) const
constexpr bool operator> (OpIndex other) const
constexpr bool operator<= (OpIndex other) const
constexpr bool operator>= (OpIndex other) const
Static Public Member Functions
static constexpr OpIndex FromOffset (uint32_t offset, uint32_t generation_bit)
static constexpr OpIndex Invalid ()
static OpIndex EncodeTurbofanNodeId (uint32_t id)
Protected Member Functions
constexpr OpIndex (uint32_t offset)
Protected Attributes
uint32_t offset_
Static Protected Attributes
static constexpr uint32_t kGenerationMaskShift = 1
static constexpr uint32_t kGenerationMask = 1 << kGenerationMaskShift
static constexpr uint32_t kUnmaskGenerationMask = ~kGenerationMask
static constexpr uint32_t kTurbofanNodeIdFlag = 1
Friends
class OperationBuffer
template<typename H >
H AbslHashValue (H h, const OpIndex &idx)
Detailed Description
Definition at line 39 of file index.h.
Constructor & Destructor Documentation
OpIndex() [1/3]
constexpr v8::internal::compiler::turboshaft::OpIndex::OpIndex (uint32_t offset) [inline], [explicit], [constexpr], [protected]
Definition at line 44 of file index.h.
                                              : offset_(offset) {
    SLOW_DCHECK(CheckInvariants());
  }
References SLOW_DCHECK.
OpIndex() [2/3]
constexpr v8::internal::compiler::turboshaft::OpIndex::OpIndex () [inline], [constexpr]
Definition at line 59 of file index.h.
: offset_(std::numeric_limits<uint32_t>::max()) {}
Referenced by EncodeTurbofanNodeId(), FromOffset(), and Invalid().
OpIndex() [3/3]
template<typename T , typename C >
v8::internal::compiler::turboshaft::OpIndex::OpIndex (const ConstOrV< T, C > &) [inline]
Definition at line 61 of file index.h.
                                 { // NOLINT(runtime/explicit)
    static_assert(base::tmp::lazy_false<T>::value,
                  "Cannot initialize OpIndex from ConstOrV<>. Did you forget "
                  "to resolve() it in the assembler?");
  }
Member Function Documentation
DecodeTurbofanNodeId()
uint32_t v8::internal::compiler::turboshaft::OpIndex::DecodeTurbofanNodeId () const [inline]
Definition at line 103 of file index.h.
                                        {
    DCHECK(IsTurbofanNodeId());
    return offset_ / sizeof(OperationStorageSlot);
  }
References v8::internal::DCHECK(), IsTurbofanNodeId(), and offset_.
Referenced by v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Run().
EncodeTurbofanNodeId()
static OpIndex v8::internal::compiler::turboshaft::OpIndex::EncodeTurbofanNodeId (uint32_t id) [inline], [static]
Definition at line 98 of file index.h.
                                                   {
    OpIndex result = OpIndex(id * sizeof(OperationStorageSlot));
    result.offset_ += kTurbofanNodeIdFlag;
    return result;
  }
References kTurbofanNodeIdFlag, OpIndex(), and v8::base::internal::result.
Referenced by v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
FromOffset()
static constexpr OpIndex v8::internal::compiler::turboshaft::OpIndex::FromOffset (uint32_t offset, uint32_t generation_bit) [inline], [static], [constexpr]
Definition at line 50 of file index.h.
                                                               {
#ifdef DEBUG
    DCHECK(generation_bit == 0 || generation_bit == 1);
    DCHECK_EQ(offset & kGenerationMask, 0);
    offset |= (generation_bit << kGenerationMaskShift);
#endif
    return OpIndex(offset);
  }
References v8::internal::DCHECK(), DCHECK_EQ, kGenerationMask, kGenerationMaskShift, offset(), and OpIndex().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::WasmPositionToOpIndex().
hash()
uint32_t v8::internal::compiler::turboshaft::OpIndex::hash () const [inline]
Definition at line 76 of file index.h.
                        {
    // It can be useful to hash OpIndex::Invalid(), so we have this `hash`
    // function, which returns the id, but without DCHECKing that Invalid is
    // valid.
    SLOW_DCHECK_IMPLIES(valid(), CheckInvariants());
    return offset_ / sizeof(OperationStorageSlot) / kSlotsPerId;
  }
References v8::internal::compiler::turboshaft::kSlotsPerId, offset_, SLOW_DCHECK_IMPLIES, and valid().
Referenced by v8::internal::compiler::turboshaft::OptionalOpIndex::hash(), v8::internal::compiler::turboshaft::hash_value(), and v8::internal::compiler::turboshaft::fast_hash< OpIndex >::operator()().
id()
constexpr uint32_t v8::internal::compiler::turboshaft::OpIndex::id () const [inline], [constexpr]
Definition at line 67 of file index.h.
                                {
    // Operations are stored at an offset that's a multiple of
    // `sizeof(OperationStorageSlot)`. In addition, an operation occupies at
    // least `kSlotsPerId` many `OperationSlot`s. Therefore, we can assign id's
    // by dividing by `kSlotsPerId`. A compact id space is important, because it
    // makes side-tables smaller.
    SLOW_DCHECK(CheckInvariants());
    return offset_ / sizeof(OperationStorageSlot) / kSlotsPerId;
  }
References v8::internal::compiler::turboshaft::kSlotsPerId, offset_, and SLOW_DCHECK.
Referenced by v8::internal::compiler::turboshaft::OperationBuffer::Allocate(), v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::Branch(), v8::internal::compiler::turboshaft::SLPTree::BuildTreeRec(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::CheckTurboshaftTypeOf(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::Finalize(), v8::internal::compiler::InstructionSelector::GetEffectLevel(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::GetTypeForPhiInput(), v8::internal::compiler::InstructionSelector::GetVirtualRegister(), v8::internal::compiler::InstructionSelector::InitializeCallBuffer(), v8::internal::compiler::InstructionSelector::IsDefined(), v8::internal::compiler::InstructionSelector::IsReallyUsed(), v8::internal::compiler::turboshaft::SLPTree::IsSideEffectFree(), v8::internal::compiler::InstructionSelector::IsSourcePositionUsed(), v8::internal::compiler::InstructionSelector::IsUsed(), v8::internal::compiler::InstructionSelector::MarkAsDefined(), v8::internal::compiler::InstructionSelector::MarkAsProtected(), v8::internal::compiler::InstructionSelector::MarkAsUsed(), v8::internal::compiler::turboshaft::OperationBuffer::Next(), v8::internal::compiler::turboshaft::Block::OpCountUpperBound(), v8::internal::compiler::turboshaft::operator<<(), v8::internal::compiler::turboshaft::OperationBuffer::Previous(), v8::internal::compiler::turboshaft::JSONTurboshaftGraphWriter::PrintEdges(), v8::internal::compiler::turboshaft::LoadOp::PrintInputs(), v8::internal::compiler::turboshaft::AtomicRMWOp::PrintInputs(), v8::internal::compiler::turboshaft::AtomicWord32PairOp::PrintInputs(), v8::internal::compiler::turboshaft::StoreOp::PrintInputs(), v8::internal::compiler::turboshaft::FrameStateOp::PrintOptions(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessBranchOnTarget(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessCheckTurboshaftTypeOf(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessPhi(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::RefineOperationType(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::RefineOperationType(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::RefineTypeKnowledge(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::RefineTypeKnowledgeNotNull(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::RefineTypesAfterBranch(), v8::internal::compiler::turboshaft::OperationBuffer::RemoveLast(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::RemoveLast(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::Run(), v8::internal::compiler::InstructionSelector::SetEffectLevel(), v8::internal::compiler::InstructionSelector::SetProtectedLoadToRemove(), v8::internal::compiler::turboshaft::OperationBuffer::SlotCount(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::TraceReductionResult(), v8::internal::compiler::InstructionSelector::VisitBlock(), v8::internal::compiler::InstructionSelector::VisitControl(), v8::internal::compiler::InstructionSelector::VisitDeoptimizeIf(), and v8::internal::compiler::turboshaft::OperationBuffer::ReplaceScope::~ReplaceScope().
Invalid()
static constexpr OpIndex v8::internal::compiler::turboshaft::OpIndex::Invalid () [inline], [static], [constexpr]
Definition at line 94 of file index.h.
{ return OpIndex(); }
References OpIndex().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayAtomicRMW(), v8::internal::wasm::TurboshaftGraphBuildingInterface::AsmjsLoadMem(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphGoto(), v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::AssertNotNull(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::AtomicRMW(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::AtomicRMW(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::BeginBlock(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::BeginBlock(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::Bind(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::BinOpImpl(), v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::Branch(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BrOnCastAbstract(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BrOnCastFailAbstract(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCallWasmFromWrapper(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildChangeInt32ToNumber(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildChangeTaggedToInt32(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildIndirectCallTargetAndImplicitArg(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildReceiverNode(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildSuspend(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildWasmToJSWrapper(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallAndMaybeCatchException(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin(), v8::internal::wasm::WasmGraphBuilderBase::CallC(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallRuntime(), v8::internal::wasm::WasmGraphBuilderBase::CallRuntime(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CreateFrameState(), v8::internal::compiler::turboshaft::IfElseCascadeToSwitchReducer< Next >::EmitSwitch(), v8::internal::compiler::turboshaft::AtomicRMWOp::expected(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ExternRefToString(), v8::internal::compiler::turboshaft::MemoryContentTable::Find(), v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::FindImpl(), v8::internal::compiler::InstructionSelector::FindProjection(), v8::internal::wasm::WasmWrapperTSGraphBuilder::FromJSFast(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::GetExtractOpIfNeeded(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::GetReducedInput(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::GlobalGet(), v8::internal::compiler::turboshaft::LoadOp::index(), v8::internal::compiler::turboshaft::StoreOp::index(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineMemCopy(), v8::internal::compiler::turboshaft::StoreOp::inputs_rep(), v8::internal::compiler::turboshaft::AssertTypesReducer< Next >::InsertTypeAssert(), v8::internal::compiler::turboshaft::V< T >::Invalid(), v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::Invalidate(), v8::internal::compiler::turboshaft::MemoryContentTable::Invalidate(), v8::internal::compiler::turboshaft::MemoryContentTable::InvalidateAtOffset(), v8::internal::compiler::turboshaft::MemoryContentTable::InvalidateMaybeAliasing(), v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::InvalidateMaybeAliasing(), v8::internal::wasm::TurboshaftGraphBuildingInterface::IsExternRefString(), v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::IsNull(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Load(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadProtectedPointerField(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadTrustedPointerField(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::LowerGlobalSetOrGet(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::MapToNewGraph(), v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::MaybeDuplicateShift(), v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::MaybeDuplicateWordBinop(), v8::internal::wasm::TurboshaftGraphBuildingInterface::MaybePhi(), v8::internal::wasm::TurboshaftGraphBuildingInterface::MemOrTableAddressToUintPtrOrOOBTrap(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::MergeOpIndices(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::NewLoopInvariantVariable(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::NewVariable(), v8::internal::compiler::turboshaft::OptionalOpIndex::Nullopt(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Phi(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Phi(), v8::internal::wasm::TurboshaftGraphBuildingInterface::PopControl(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessAnyConvertExtern(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessArrayLength(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessAssertNotNull(), v8::internal::compiler::turboshaft::RedundantStoreAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessCall(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessStringAsWtf16(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessStringPrepareForGetCodeUnit(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessStructGet(), v8::internal::compiler::turboshaft::TypedOptimizationsReducer< Next >::ReduceInputGraphBranch(), v8::internal::compiler::turboshaft::IfElseCascadeToSwitchReducer< Next >::ReduceInputGraphBranch(), v8::internal::compiler::turboshaft::DeadCodeEliminationReducer< Next >::ReduceInputGraphOperation(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::ReduceInputGraphOperation(), v8::internal::compiler::turboshaft::TypedOptimizationsReducer< Next >::ReduceInputGraphOperation(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceMemoryIndex(), v8::internal::wasm::TurboshaftGraphBuildingInterface::RefCastAbstract(), v8::internal::wasm::TurboshaftGraphBuildingInterface::RefTestAbstract(), v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::ResolveBase(), v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::Return(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Run(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Store(), v8::internal::compiler::turboshaft::LoadStoreSimplificationReducer< Next >::Store(), v8::internal::compiler::turboshaft::StoreStoreEliminationReducer< Next >::Store(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Store(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringNewWtf8ArrayImpl(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StructAtomicRMW(), v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::StructGet(), v8::internal::compiler::turboshaft::WasmLoadEliminationReducer< Next >::StructSet(), v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::StructSet(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::StructSet(), v8::internal::compiler::turboshaft::LateLoadEliminationReducer< Next >::TaggedBitcast(), v8::internal::wasm::WasmWrapperTSGraphBuilder::ToJS(), v8::internal::compiler::turboshaft::TypedOptimizationsReducer< Next >::TryAssembleConstantForType(), v8::internal::compiler::turboshaft::WasmInJSInliningReducer< Next >::TryInlineWasmCall(), v8::internal::compiler::turboshaft::TryMatchConditionalCompareChainShared(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::UnOpImpl(), valid(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitBlock(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitOpNoMappingUpdate(), v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::WasmTypeCast(), v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::WasmTypeCheck(), v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi(), and v8::internal::compiler::turboshaft::ScopedVar< T, Assembler >::~ScopedVar().
IsTurbofanNodeId()
bool v8::internal::compiler::turboshaft::OpIndex::IsTurbofanNodeId () const [inline]
Definition at line 107 of file index.h.
                                {
    return offset_ % sizeof(OperationStorageSlot) == kTurbofanNodeIdFlag;
  }
References kTurbofanNodeIdFlag, and offset_.
Referenced by DecodeTurbofanNodeId().
offset()
uint32_t v8::internal::compiler::turboshaft::OpIndex::offset () const [inline]
Definition at line 83 of file index.h.
                          {
    SLOW_DCHECK(CheckInvariants());
#ifdef DEBUG
    return offset_ & kUnmaskGenerationMask;
#else
    return offset_;
#endif
  }
References kUnmaskGenerationMask, offset_, and SLOW_DCHECK.
Referenced by v8::internal::compiler::turboshaft::OperationBuffer::Allocate(), v8::internal::compiler::turboshaft::SLPTree::CanBePacked(), FromOffset(), v8::internal::compiler::turboshaft::OperationBuffer::Get(), v8::internal::compiler::turboshaft::SLPTree::IsSideEffectFree(), v8::internal::compiler::turboshaft::OperationBuffer::Next(), v8::internal::compiler::turboshaft::OperationBuffer::Previous(), v8::internal::compiler::turboshaft::OperationBuffer::SlotCount(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::TryMatchBaseWithScaledIndexAndDisplacement(), v8::internal::compiler::TryMatchBaseWithScaledIndexAndDisplacement64(), and v8::internal::compiler::turboshaft::OperationBuffer::ReplaceScope::~ReplaceScope().
operator!=()
constexpr bool v8::internal::compiler::turboshaft::OpIndex::operator!= (OpIndex other) const [inline], [constexpr]
Definition at line 114 of file index.h.
                                                 {
    return offset_ != other.offset_;
  }
References offset_.
operator<()
constexpr bool v8::internal::compiler::turboshaft::OpIndex::operator< (OpIndex other) const [inline], [constexpr]
Definition at line 117 of file index.h.
                                                {
    return offset_ < other.offset_;
  }
References offset_.
operator<=()
constexpr bool v8::internal::compiler::turboshaft::OpIndex::operator<= (OpIndex other) const [inline], [constexpr]
Definition at line 123 of file index.h.
                                                 {
    return offset_ <= other.offset_;
  }
References offset_.
operator==()
constexpr bool v8::internal::compiler::turboshaft::OpIndex::operator== (OpIndex other) const [inline], [constexpr]
Definition at line 111 of file index.h.
                                                 {
    return offset_ == other.offset_;
  }
References offset_.
operator>()
constexpr bool v8::internal::compiler::turboshaft::OpIndex::operator> (OpIndex other) const [inline], [constexpr]
Definition at line 120 of file index.h.
                                                {
    return offset_ > other.offset_;
  }
References offset_.
operator>=()
constexpr bool v8::internal::compiler::turboshaft::OpIndex::operator>= (OpIndex other) const [inline], [constexpr]
Definition at line 126 of file index.h.
                                                 {
    return offset_ >= other.offset_;
  }
References offset_.
valid()
constexpr bool v8::internal::compiler::turboshaft::OpIndex::valid () const [inline], [constexpr]
Definition at line 92 of file index.h.
{ return *this != Invalid(); }
References Invalid().
Referenced by v8::internal::compiler::turboshaft::Graph::Add(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::AllocateBigInt(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayAtomicRMW(), v8::internal::compiler::turboshaft::Block::begin(), v8::internal::detail::BuiltinArgumentsTS< Assembler >::Iterator::Begin(), v8::internal::compiler::turboshaft::StringView::Begin(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BindBlockAndGeneratePhis(), v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::Branch(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildWasmToJSWrapper(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallAndMaybeCatchException(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin(), v8::internal::wasm::WasmWrapperTSGraphBuilder::CallBuiltin(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallIndirect(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallRef(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallRuntime(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallRuntimeImpl(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ConvertHeapObjectToFloat64OrDeopt(), v8::internal::compiler::turboshaft::WasmJSLoweringReducer< Next >::CreateFrameStateWithUpdatedBailoutId(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::CreateOldToNewMapping(), v8::internal::compiler::OperandGenerator::Define(), v8::internal::wasm::TurboshaftGraphBuildingInterface::Deopt(), v8::internal::wasm::TurboshaftGraphBuildingInterface::DeoptIfNot(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::EmitLoopSinglePredecessorBlock(), v8::internal::compiler::InstructionSelector::EmitPrepareArguments(), v8::internal::compiler::turboshaft::Block::end(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::Finalize(), v8::internal::compiler::turboshaft::Graph::Finalize(), v8::internal::compiler::turboshaft::FindCompareChain(), v8::internal::compiler::turboshaft::Block::FirstOperation(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::FixLoopPhi(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::FixLoopPhis(), v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::FixLoopPhis(), v8::internal::compiler::FlagsContinuation::FlagsContinuation(), v8::internal::compiler::IA32OperandGenerator::GenerateMemoryOperandInputs(), v8::internal::compiler::X64OperandGenerator::GenerateMemoryOperandInputs(), v8::internal::compiler::S390OperandGenerator::GenerateMemoryOperandInputs(), v8::internal::compiler::InstructionSelector::GetEffectLevel(), v8::internal::compiler::InstructionSelector::GetVirtualRegister(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::Goto(), hash(), v8::internal::compiler::InstructionSelector::InitializeCallBuffer(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineWasmCall(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::is_exclusive_user_of(), v8::internal::wasm::TurboshaftGraphBuildingInterface::IsArrayNewSegment(), v8::internal::compiler::turboshaft::Block::IsComplete(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::IsCompressed(), v8::internal::compiler::InstructionSelector::IsDefined(), v8::internal::compiler::InstructionSelector::IsReallyUsed(), v8::internal::wasm::TurboshaftGraphBuildingInterface::IsSimd128ZeroConstant(), v8::internal::compiler::InstructionSelector::IsUsed(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Load(), v8::internal::compiler::turboshaft::LoadEliminationReplacement::LoadElimination(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::MapToNewGraph(), v8::internal::compiler::InstructionSelector::MarkAsDefined(), v8::internal::compiler::InstructionSelector::MarkAsUsed(), v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::MaybeDuplicateCond(), v8::internal::compiler::turboshaft::MemoryContentTable::OnValueChange(), v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::OnValueChange(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::VariableTable::OnValueChange(), v8::internal::compiler::turboshaft::operator<<(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Parameter(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Phi(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessAnyConvertExtern(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessArrayLength(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessAssertNotNull(), v8::internal::compiler::turboshaft::RedundantStoreAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessLoad(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessStringAsWtf16(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessStringPrepareForGetCodeUnit(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessStructGet(), v8::internal::compiler::turboshaft::IfElseCascadeToSwitchReducer< Next >::ReduceInputGraphBranch(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::ReduceInputGraphOperation(), v8::internal::compiler::turboshaft::AssertTypesReducer< Next >::ReduceInputGraphOperation(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::ReduceInputGraphOperation(), v8::internal::compiler::turboshaft::TypedOptimizationsReducer< Next >::ReduceInputGraphOperation(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::RefineOperationType(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::RefineOperationType(), v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::Select(), v8::internal::compiler::InstructionSelector::SetEffectLevel(), v8::internal::wasm::TurboshaftGraphBuildingInterface::SetupControlFlowEdge(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Binop(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Constant(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128LoadTransform(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128ReplaceLane(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Shift(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Shuffle(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Splat(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Ternary(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Unary(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Store(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StructAtomicRMW(), v8::internal::compiler::turboshaft::WasmLoadEliminationReducer< Next >::StructGet(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StructNewImpl(), v8::internal::compiler::turboshaft::WasmLoadEliminationReducer< Next >::StructSet(), v8::internal::compiler::turboshaft::WasmInJSInliningReducer< Next >::TryInlineWasmCall(), v8::internal::compiler::OperandGenerator::Use(), v8::internal::compiler::InstructionSelector::VisitBlock(), v8::internal::compiler::InstructionSelector::VisitControl(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloatBinop(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitOpAndUpdateMapping(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitOpNoMappingUpdate(), and v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord32EqualImpl().
Friends And Related Function Documentation
AbslHashValue
template<typename H >
H AbslHashValue (H h, const OpIndex & idx) [friend]
Definition at line 162 of file index.h.
                                                  {
    return H::combine(std::move(h), idx.offset_);
  }
OperationBuffer
friend class OperationBuffer [friend]
Definition at line 47 of file index.h.
Member Data Documentation
kGenerationMask
constexpr uint32_t v8::internal::compiler::turboshaft::OpIndex::kGenerationMask = 1 << kGenerationMaskShift [static], [constexpr], [protected]
Definition at line 151 of file index.h.
Referenced by FromOffset().
kGenerationMaskShift
constexpr uint32_t v8::internal::compiler::turboshaft::OpIndex::kGenerationMaskShift = 1 [static], [constexpr], [protected]
Definition at line 150 of file index.h.
Referenced by FromOffset().
kTurbofanNodeIdFlag
constexpr uint32_t v8::internal::compiler::turboshaft::OpIndex::kTurbofanNodeIdFlag = 1 [static], [constexpr], [protected]
Definition at line 159 of file index.h.
Referenced by EncodeTurbofanNodeId(), and IsTurbofanNodeId().
kUnmaskGenerationMask
constexpr uint32_t v8::internal::compiler::turboshaft::OpIndex::kUnmaskGenerationMask = ~kGenerationMask [static], [constexpr], [protected]
Definition at line 152 of file index.h.
Referenced by offset().
offset_
uint32_t v8::internal::compiler::turboshaft::OpIndex::offset_ [protected]
Definition at line 157 of file index.h.
Referenced by DecodeTurbofanNodeId(), hash(), id(), IsTurbofanNodeId(), offset(), operator!=(), operator<(), operator<=(), operator==(), operator>(), and operator>=().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/index.h