v8::internal::CustomArguments< T > Class Template Reference
#include <api-arguments.h>
Public Member Functions
~CustomArguments () override
void IterateInstance (RootVisitor *v) override
Static Public Attributes
static constexpr int kReturnValueIndex = T::kReturnValueIndex
Protected Member Functions
CustomArguments (Isolate *isolate)
template<typename V >
Handle< V > GetReturnValue (Isolate *isolate) const
Isolate * isolate () const
FullObjectSlot slot_at (int index) const
Protected Attributes
Address values_ [T::kArgsLength]
Additional Inherited Members
Detailed Description
template<typename T>
class v8::internal::CustomArguments< T >
Definition at line 26 of file api-arguments.h.
Constructor & Destructor Documentation
 CustomArguments()
template<typename T >
v8::internal::CustomArguments< T >::~CustomArguments [override]
Definition at line 26 of file api-arguments-inl.h.
                                     {
  slot_at(kReturnValueIndex).store(Tagged<Object>(kHandleZapValue));
}
References v8::internal::kHandleZapValue.
CustomArguments()
template<typename T >
v8::internal::CustomArguments< T >::CustomArguments (Isolate * isolate) [inline], [explicit], [protected]
Definition at line 39 of file api-arguments.h.
      : CustomArgumentsBase(isolate) {}
Member Function Documentation
GetReturnValue()
template<typename T >
template<typename V >
Handle< V > v8::internal::CustomArguments< T >::GetReturnValue (Isolate * isolate) const [protected]
Definition at line 32 of file api-arguments-inl.h.
                                                                   {
  // Check the ReturnValue.
  FullObjectSlot slot = slot_at(kReturnValueIndex);
  DCHECK(Is<JSAny>(*slot));
  return Cast<V>(Handle<Object>(slot.location()));
}
References v8::internal::DCHECK(), and v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::location().
isolate()
template<typename T >
Isolate* v8::internal::CustomArguments< T >::isolate () const [inline], [protected]
Definition at line 45 of file api-arguments.h.
                                  {
    return reinterpret_cast<Isolate*>((*slot_at(T::kIsolateIndex)).ptr());
  }
References v8::internal::CustomArguments< T >::slot_at().
IterateInstance()
template<typename T >
void v8::internal::CustomArguments< T >::IterateInstance (RootVisitor * v) [inline], [override], [virtual]
Reimplemented from v8::internal::Relocatable.
Definition at line 33 of file api-arguments.h.
                                                       {
    v->VisitRootPointers(Root::kRelocatable, nullptr, slot_at(0),
                         slot_at(T::kArgsLength));
  }
References v8::internal::CustomArguments< T >::slot_at(), and v8::internal::RootVisitor::VisitRootPointers().
slot_at()
template<typename T >
FullObjectSlot v8::internal::CustomArguments< T >::slot_at (int index) const [inline], [protected]
Definition at line 49 of file api-arguments.h.
                                                 {
    // This allows index == T::kArgsLength so "one past the end" slots
    // can be retrieved for iterating purposes.
    DCHECK_LE(static_cast<unsigned>(index),
              static_cast<unsigned>(T::kArgsLength));
    return FullObjectSlot(values_ + index);
  }
References DCHECK_LE, v8::internal::index, and v8::internal::CustomArguments< T >::values_.
Referenced by v8::internal::CustomArguments< T >::isolate(), and v8::internal::CustomArguments< T >::IterateInstance().
Member Data Documentation
kReturnValueIndex
template<typename T >
constexpr int v8::internal::CustomArguments< T >::kReturnValueIndex = T::kReturnValueIndex [static], [constexpr]
Definition at line 28 of file api-arguments.h.
values_
template<typename T >
Address v8::internal::CustomArguments< T >::values_[T::kArgsLength] [protected]
Definition at line 57 of file api-arguments.h.
Referenced by v8::internal::CustomArguments< T >::slot_at().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/api/api-arguments.h
/mnt/V8SourceCode/src/api/api-arguments-inl.h