cppgc::internal::MarkingWorklists Class Reference
#include <marking-worklists.h>
Classes
struct ConcurrentMarkingBailoutItem
struct EphemeronPairItem
class ExternalMarkingWorklist
struct WeakCallbackItem
Public Types
using MarkingItem = cppgc::TraceDescriptor
using MarkingWorklist = heap::base::Worklist< MarkingItem, 512 >
using NotFullyConstructedWorklist = ExternalMarkingWorklist
using PreviouslyNotFullyConstructedWorklist = heap::base::Worklist< HeapObjectHeader *, 16 >
using WeakCallbackWorklist = heap::base::Worklist< WeakCallbackItem, 64 >
using WeakCustomCallbackWorklist = heap::base::Worklist< WeakCallbackItem, 16 >
using WriteBarrierWorklist = heap::base::Worklist< HeapObjectHeader *, 64 >
using ConcurrentMarkingBailoutWorklist = heap::base::Worklist< ConcurrentMarkingBailoutItem, 64 >
using EphemeronPairsWorklist = heap::base::Worklist< EphemeronPairItem, 64 >
using WeakContainersWorklist = ExternalMarkingWorklist
using RetraceMarkedObjectsWorklist = heap::base::Worklist< HeapObjectHeader *, 16 >
Public Member Functions
MarkingWorklist * marking_worklist ()
NotFullyConstructedWorklist * not_fully_constructed_worklist ()
PreviouslyNotFullyConstructedWorklist * previously_not_fully_constructed_worklist ()
WriteBarrierWorklist * write_barrier_worklist ()
WeakCallbackWorklist * weak_container_callback_worklist ()
WeakCallbackWorklist * parallel_weak_callback_worklist ()
WeakCustomCallbackWorklist * weak_custom_callback_worklist ()
const ConcurrentMarkingBailoutWorklist * concurrent_marking_bailout_worklist () const
ConcurrentMarkingBailoutWorklist * concurrent_marking_bailout_worklist ()
EphemeronPairsWorklist * discovered_ephemeron_pairs_worklist ()
EphemeronPairsWorklist * ephemeron_pairs_for_processing_worklist ()
WeakContainersWorklist * weak_containers_worklist ()
RetraceMarkedObjectsWorklist * retrace_marked_objects_worklist ()
void ClearForTesting ()
Static Public Attributes
static constexpr int kMutatorThreadId = 0
Private Attributes
MarkingWorklist marking_worklist_
NotFullyConstructedWorklist not_fully_constructed_worklist_
PreviouslyNotFullyConstructedWorklist previously_not_fully_constructed_worklist_
WriteBarrierWorklist write_barrier_worklist_
WeakCallbackWorklist weak_container_callback_worklist_
WeakCustomCallbackWorklist weak_custom_callback_worklist_
WeakCallbackWorklist parallel_weak_callback_worklist_
ConcurrentMarkingBailoutWorklist concurrent_marking_bailout_worklist_
EphemeronPairsWorklist discovered_ephemeron_pairs_worklist_
EphemeronPairsWorklist ephemeron_pairs_for_processing_worklist_
WeakContainersWorklist weak_containers_worklist_
RetraceMarkedObjectsWorklist retrace_marked_objects_worklist_
Detailed Description
Definition at line 18 of file marking-worklists.h.
Member Typedef Documentation
ConcurrentMarkingBailoutWorklist
using cppgc::internal::MarkingWorklists::ConcurrentMarkingBailoutWorklist = heap::base::Worklist<ConcurrentMarkingBailoutItem, 64 >
Definition at line 83 of file marking-worklists.h.
EphemeronPairsWorklist
using cppgc::internal::MarkingWorklists::EphemeronPairsWorklist = heap::base::Worklist<EphemeronPairItem, 64 >
Definition at line 86 of file marking-worklists.h.
MarkingItem
using cppgc::internal::MarkingWorklists::MarkingItem = cppgc::TraceDescriptor
Definition at line 51 of file marking-worklists.h.
MarkingWorklist
using cppgc::internal::MarkingWorklists::MarkingWorklist = heap::base::Worklist<MarkingItem, 512 >
Definition at line 72 of file marking-worklists.h.
NotFullyConstructedWorklist
using cppgc::internal::MarkingWorklists::NotFullyConstructedWorklist = ExternalMarkingWorklist
Definition at line 74 of file marking-worklists.h.
PreviouslyNotFullyConstructedWorklist
using cppgc::internal::MarkingWorklists::PreviouslyNotFullyConstructedWorklist = heap::base::Worklist<HeapObjectHeader*, 16 >
Definition at line 75 of file marking-worklists.h.
RetraceMarkedObjectsWorklist
using cppgc::internal::MarkingWorklists::RetraceMarkedObjectsWorklist = heap::base::Worklist<HeapObjectHeader*, 16 >
Definition at line 89 of file marking-worklists.h.
WeakCallbackWorklist
using cppgc::internal::MarkingWorklists::WeakCallbackWorklist = heap::base::Worklist<WeakCallbackItem, 64 >
Definition at line 77 of file marking-worklists.h.
WeakContainersWorklist
using cppgc::internal::MarkingWorklists::WeakContainersWorklist = ExternalMarkingWorklist
Definition at line 88 of file marking-worklists.h.
WeakCustomCallbackWorklist
using cppgc::internal::MarkingWorklists::WeakCustomCallbackWorklist = heap::base::Worklist<WeakCallbackItem, 16 >
Definition at line 79 of file marking-worklists.h.
WriteBarrierWorklist
using cppgc::internal::MarkingWorklists::WriteBarrierWorklist = heap::base::Worklist<HeapObjectHeader*, 64 >
Definition at line 81 of file marking-worklists.h.
Member Function Documentation
ClearForTesting()
void cppgc::internal::MarkingWorklists::ClearForTesting ()
Definition at line 13 of file marking-worklists.cc.
                                       {
  marking_worklist_.Clear();
  not_fully_constructed_worklist_.Clear();
  previously_not_fully_constructed_worklist_.Clear();
  write_barrier_worklist_.Clear();
  weak_container_callback_worklist_.Clear();
  parallel_weak_callback_worklist_.Clear();
  weak_custom_callback_worklist_.Clear();
  concurrent_marking_bailout_worklist_.Clear();
  discovered_ephemeron_pairs_worklist_.Clear();
  ephemeron_pairs_for_processing_worklist_.Clear();
  retrace_marked_objects_worklist_.Clear();
}
References heap::base::Worklist< EntryType, MinSegmentSize >::Clear(), cppgc::internal::MarkingWorklists::ExternalMarkingWorklist::Clear(), concurrent_marking_bailout_worklist_, discovered_ephemeron_pairs_worklist_, ephemeron_pairs_for_processing_worklist_, marking_worklist_, not_fully_constructed_worklist_, parallel_weak_callback_worklist_, previously_not_fully_constructed_worklist_, retrace_marked_objects_worklist_, weak_container_callback_worklist_, weak_custom_callback_worklist_, and write_barrier_worklist_.
Referenced by cppgc::internal::MarkerBase::ClearAllWorklistsForTesting().
concurrent_marking_bailout_worklist() [1/2]
ConcurrentMarkingBailoutWorklist* cppgc::internal::MarkingWorklists::concurrent_marking_bailout_worklist () [inline]
Definition at line 116 of file marking-worklists.h.
                                                                          {
    return &concurrent_marking_bailout_worklist_;
  }
References concurrent_marking_bailout_worklist_.
concurrent_marking_bailout_worklist() [2/2]
const ConcurrentMarkingBailoutWorklist* cppgc::internal::MarkingWorklists::concurrent_marking_bailout_worklist () const [inline]
Definition at line 112 of file marking-worklists.h.
            {
    return &concurrent_marking_bailout_worklist_;
  }
References concurrent_marking_bailout_worklist_.
discovered_ephemeron_pairs_worklist()
EphemeronPairsWorklist* cppgc::internal::MarkingWorklists::discovered_ephemeron_pairs_worklist () [inline]
Definition at line 119 of file marking-worklists.h.
                                                                {
    return &discovered_ephemeron_pairs_worklist_;
  }
References discovered_ephemeron_pairs_worklist_.
Referenced by cppgc::internal::MarkerBase::~MarkerBase().
ephemeron_pairs_for_processing_worklist()
EphemeronPairsWorklist* cppgc::internal::MarkingWorklists::ephemeron_pairs_for_processing_worklist () [inline]
Definition at line 122 of file marking-worklists.h.
                                                                    {
    return &ephemeron_pairs_for_processing_worklist_;
  }
References ephemeron_pairs_for_processing_worklist_.
marking_worklist()
MarkingWorklist* cppgc::internal::MarkingWorklists::marking_worklist () [inline]
Definition at line 92 of file marking-worklists.h.
{ return &marking_worklist_; }
References marking_worklist_.
Referenced by cppgc::internal::anonymous_namespace{concurrent-marker.cc}::HasWorkForConcurrentMarking(), cppgc::internal::MarkerBase::ProcessWeakness(), and cppgc::internal::anonymous_namespace{concurrent-marker.cc}::WorkSizeForConcurrentMarking().
not_fully_constructed_worklist()
NotFullyConstructedWorklist* cppgc::internal::MarkingWorklists::not_fully_constructed_worklist () [inline]
Definition at line 93 of file marking-worklists.h.
                                                                {
    return &not_fully_constructed_worklist_;
  }
References not_fully_constructed_worklist_.
Referenced by cppgc::internal::MarkerBase::JoinConcurrentMarkingIfNeeded(), and cppgc::internal::MarkerBase::~MarkerBase().
parallel_weak_callback_worklist()
WeakCallbackWorklist* cppgc::internal::MarkingWorklists::parallel_weak_callback_worklist () [inline]
Definition at line 106 of file marking-worklists.h.
                                                          {
    return &parallel_weak_callback_worklist_;
  }
References parallel_weak_callback_worklist_.
Referenced by cppgc::internal::MarkerBase::ProcessWeakness().
previously_not_fully_constructed_worklist()
PreviouslyNotFullyConstructedWorklist* cppgc::internal::MarkingWorklists::previously_not_fully_constructed_worklist () [inline]
Definition at line 97 of file marking-worklists.h.
                                              {
    return &previously_not_fully_constructed_worklist_;
  }
References previously_not_fully_constructed_worklist_.
Referenced by cppgc::internal::anonymous_namespace{concurrent-marker.cc}::HasWorkForConcurrentMarking(), and cppgc::internal::anonymous_namespace{concurrent-marker.cc}::WorkSizeForConcurrentMarking().
retrace_marked_objects_worklist()
RetraceMarkedObjectsWorklist* cppgc::internal::MarkingWorklists::retrace_marked_objects_worklist () [inline]
Definition at line 128 of file marking-worklists.h.
                                                                  {
    return &retrace_marked_objects_worklist_;
  }
References retrace_marked_objects_worklist_.
weak_container_callback_worklist()
WeakCallbackWorklist* cppgc::internal::MarkingWorklists::weak_container_callback_worklist () [inline]
Definition at line 103 of file marking-worklists.h.
                                                           {
    return &weak_container_callback_worklist_;
  }
References weak_container_callback_worklist_.
weak_containers_worklist()
WeakContainersWorklist* cppgc::internal::MarkingWorklists::weak_containers_worklist () [inline]
Definition at line 125 of file marking-worklists.h.
                                                     {
    return &weak_containers_worklist_;
  }
References weak_containers_worklist_.
Referenced by cppgc::internal::MarkerBase::~MarkerBase().
weak_custom_callback_worklist()
WeakCustomCallbackWorklist* cppgc::internal::MarkingWorklists::weak_custom_callback_worklist () [inline]
Definition at line 109 of file marking-worklists.h.
                                                              {
    return &weak_custom_callback_worklist_;
  }
References weak_custom_callback_worklist_.
write_barrier_worklist()
WriteBarrierWorklist* cppgc::internal::MarkingWorklists::write_barrier_worklist () [inline]
Definition at line 100 of file marking-worklists.h.
                                                 {
    return &write_barrier_worklist_;
  }
References write_barrier_worklist_.
Referenced by cppgc::internal::anonymous_namespace{concurrent-marker.cc}::HasWorkForConcurrentMarking(), and cppgc::internal::anonymous_namespace{concurrent-marker.cc}::WorkSizeForConcurrentMarking().
Member Data Documentation
concurrent_marking_bailout_worklist_
ConcurrentMarkingBailoutWorklist cppgc::internal::MarkingWorklists::concurrent_marking_bailout_worklist_ [private]
Definition at line 147 of file marking-worklists.h.
Referenced by ClearForTesting(), and concurrent_marking_bailout_worklist().
discovered_ephemeron_pairs_worklist_
EphemeronPairsWorklist cppgc::internal::MarkingWorklists::discovered_ephemeron_pairs_worklist_ [private]
Definition at line 148 of file marking-worklists.h.
Referenced by ClearForTesting(), and discovered_ephemeron_pairs_worklist().
ephemeron_pairs_for_processing_worklist_
EphemeronPairsWorklist cppgc::internal::MarkingWorklists::ephemeron_pairs_for_processing_worklist_ [private]
Definition at line 149 of file marking-worklists.h.
Referenced by ClearForTesting(), and ephemeron_pairs_for_processing_worklist().
kMutatorThreadId
constexpr int cppgc::internal::MarkingWorklists::kMutatorThreadId = 0 [static], [constexpr]
Definition at line 49 of file marking-worklists.h.
marking_worklist_
MarkingWorklist cppgc::internal::MarkingWorklists::marking_worklist_ [private]
Definition at line 135 of file marking-worklists.h.
Referenced by ClearForTesting(), and marking_worklist().
not_fully_constructed_worklist_
NotFullyConstructedWorklist cppgc::internal::MarkingWorklists::not_fully_constructed_worklist_ [private]
Definition at line 136 of file marking-worklists.h.
Referenced by ClearForTesting(), and not_fully_constructed_worklist().
parallel_weak_callback_worklist_
WeakCallbackWorklist cppgc::internal::MarkingWorklists::parallel_weak_callback_worklist_ [private]
Definition at line 146 of file marking-worklists.h.
Referenced by ClearForTesting(), and parallel_weak_callback_worklist().
previously_not_fully_constructed_worklist_
PreviouslyNotFullyConstructedWorklist cppgc::internal::MarkingWorklists::previously_not_fully_constructed_worklist_ [private]
Definition at line 138 of file marking-worklists.h.
Referenced by ClearForTesting(), and previously_not_fully_constructed_worklist().
retrace_marked_objects_worklist_
RetraceMarkedObjectsWorklist cppgc::internal::MarkingWorklists::retrace_marked_objects_worklist_ [private]
Definition at line 151 of file marking-worklists.h.
Referenced by ClearForTesting(), and retrace_marked_objects_worklist().
weak_container_callback_worklist_
WeakCallbackWorklist cppgc::internal::MarkingWorklists::weak_container_callback_worklist_ [private]
Definition at line 141 of file marking-worklists.h.
Referenced by ClearForTesting(), and weak_container_callback_worklist().
weak_containers_worklist_
WeakContainersWorklist cppgc::internal::MarkingWorklists::weak_containers_worklist_ [private]
Definition at line 150 of file marking-worklists.h.
Referenced by weak_containers_worklist().
weak_custom_callback_worklist_
WeakCustomCallbackWorklist cppgc::internal::MarkingWorklists::weak_custom_callback_worklist_ [private]
Definition at line 143 of file marking-worklists.h.
Referenced by ClearForTesting(), and weak_custom_callback_worklist().
write_barrier_worklist_
WriteBarrierWorklist cppgc::internal::MarkingWorklists::write_barrier_worklist_ [private]
Definition at line 139 of file marking-worklists.h.
Referenced by ClearForTesting(), and write_barrier_worklist().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/marking-worklists.h
/mnt/V8SourceCode/src/heap/cppgc/marking-worklists.cc