v8::internal::MaterializedObjectStore Class Reference
#include <materialized-object-store.h>
Public Member Functions
MaterializedObjectStore (Isolate *isolate)
DirectHandle< FixedArray > Get (Address fp)
void Set (Address fp, DirectHandle< FixedArray > materialized_objects)
bool Remove (Address fp)
Private Member Functions
Isolate * isolate () const
DirectHandle< FixedArray > GetStackEntries ()
DirectHandle< FixedArray > EnsureStackEntries (int size)
int StackIdToIndex (Address fp)
Private Attributes
Isolate * isolate_
std::vector< Address > frame_fps_
Detailed Description
Definition at line 18 of file materialized-object-store.h.
Constructor & Destructor Documentation
MaterializedObjectStore()
v8::internal::MaterializedObjectStore::MaterializedObjectStore (Isolate * isolate) [inline], [explicit]
Definition at line 20 of file materialized-object-store.h.
: isolate_(isolate) {}
Member Function Documentation
EnsureStackEntries()
DirectHandle< FixedArray > v8::internal::MaterializedObjectStore::EnsureStackEntries (int size) [private]
Definition at line 66 of file materialized-object-store.cc.
                {
  DirectHandle<FixedArray> array = GetStackEntries();
  if (array->length() >= length) {
    return array;
  }
  int new_length = length > 10 ? length : 10;
  if (new_length < 2 * array->length()) {
    new_length = 2 * array->length();
  }
  DirectHandle<FixedArray> new_array =
      isolate()->factory()->NewFixedArray(new_length, AllocationType::kOld);
  for (int i = 0; i < array->length(); i++) {
    new_array->set(i, array->get(i));
  }
  Tagged<HeapObject> undefined_value =
      ReadOnlyRoots(isolate()).undefined_value();
  for (int i = array->length(); i < length; i++) {
    new_array->set(i, undefined_value);
  }
  isolate()->heap()->SetRootMaterializedObjects(*new_array);
  return new_array;
}
References v8::internal::Isolate::factory(), GetStackEntries(), v8::internal::Isolate::heap(), isolate(), v8::internal::kOld, v8::internal::length, v8::internal::FactoryBase< Impl >::NewFixedArray(), and v8::internal::Heap::SetRootMaterializedObjects().
Referenced by Set().
Get()
DirectHandle< FixedArray > v8::internal::MaterializedObjectStore::Get (Address fp)
Definition at line 15 of file materialized-object-store.cc.
                                                                {
  int index = StackIdToIndex(fp);
  if (index == -1) {
    return Handle<FixedArray>::null();
  }
  DirectHandle<FixedArray> array = GetStackEntries();
  CHECK_GT(array->length(), index);
  return Cast<FixedArray>(Handle<Object>(array->get(index), isolate()));
}
References CHECK_GT, GetStackEntries(), v8::internal::index, isolate(), v8::internal::Handle< T >::null(), and StackIdToIndex().
Referenced by v8::internal::TranslatedState::StoreMaterializedValuesAndDeopt(), and v8::internal::TranslatedState::UpdateFromPreviouslyMaterializedObjects().
GetStackEntries()
DirectHandle< FixedArray > v8::internal::MaterializedObjectStore::GetStackEntries () [private]
Definition at line 61 of file materialized-object-store.cc.
                                                                  {
  return DirectHandle<FixedArray>(isolate()->heap()->materialized_objects(),
                                  isolate());
}
References heap(), and isolate().
Referenced by EnsureStackEntries(), and Get().
isolate()
Isolate* v8::internal::MaterializedObjectStore::isolate () const [inline], [private]
Definition at line 27 of file materialized-object-store.h.
{ return isolate_; }
References isolate_.
Referenced by EnsureStackEntries(), Get(), GetStackEntries(), and Remove().
Remove()
bool v8::internal::MaterializedObjectStore::Remove (Address fp)
Definition at line 37 of file materialized-object-store.cc.
                                               {
  auto it = std::find(frame_fps_.begin(), frame_fps_.end(), fp);
  if (it == frame_fps_.end()) return false;
  int index = static_cast<int>(std::distance(frame_fps_.begin(), it));
  frame_fps_.erase(it);
  Tagged<FixedArray> array = isolate()->heap()->materialized_objects();
  CHECK_LT(index, array->length());
  int fps_size = static_cast<int>(frame_fps_.size());
  for (int i = index; i < fps_size; i++) {
    array->set(i, array->get(i + 1));
  }
  array->set(fps_size, ReadOnlyRoots(isolate()).undefined_value());
  return true;
}
References CHECK_LT, frame_fps_, v8::internal::Isolate::heap(), v8::internal::index, and isolate().
Referenced by v8::internal::Deoptimizer::MaterializeHeapObjects(), and v8::internal::Isolate::UnwindAndFindHandler().
Set()
void v8::internal::MaterializedObjectStore::Set (Address fp, DirectHandle< FixedArray > materialized_objects)
Definition at line 25 of file materialized-object-store.cc.
                                                               {
  int index = StackIdToIndex(fp);
  if (index == -1) {
    index = static_cast<int>(frame_fps_.size());
    frame_fps_.push_back(fp);
  }
  DirectHandle<FixedArray> array = EnsureStackEntries(index + 1);
  array->set(index, *materialized_objects);
}
References EnsureStackEntries(), frame_fps_, v8::internal::index, and StackIdToIndex().
Referenced by v8::internal::TranslatedState::StoreMaterializedValuesAndDeopt().
StackIdToIndex()
int v8::internal::MaterializedObjectStore::StackIdToIndex (Address fp) [private]
Definition at line 54 of file materialized-object-store.cc.
                                                      {
  auto it = std::find(frame_fps_.begin(), frame_fps_.end(), fp);
  return it == frame_fps_.end()
             ? -1
             : static_cast<int>(std::distance(frame_fps_.begin(), it));
}
References frame_fps_.
Referenced by Get(), and Set().
Member Data Documentation
frame_fps_
std::vector<Address> v8::internal::MaterializedObjectStore::frame_fps_ [private]
Definition at line 34 of file materialized-object-store.h.
Referenced by Remove(), Set(), and StackIdToIndex().
isolate_
Isolate* v8::internal::MaterializedObjectStore::isolate_ [private]
Definition at line 33 of file materialized-object-store.h.
Referenced by isolate().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/deoptimizer/materialized-object-store.h
/mnt/V8SourceCode/src/deoptimizer/materialized-object-store.cc