v8::internal::VariableProxy Class Reference
#include <ast.h>
Classes
struct UnresolvedNext
Public Member Functions
bool IsValidReferenceExpression () const
DirectHandle< String > name () const
const AstRawString * raw_name () const
Variable * var () const
void set_var (Variable *v)
Scanner::Location location ()
bool is_assigned () const
void set_is_assigned ()
void clear_is_assigned ()
bool is_resolved () const
void set_is_resolved ()
bool is_new_target () const
void set_is_new_target ()
HoleCheckMode hole_check_mode () const
void set_needs_hole_check ()
bool IsPrivateName () const
void BindTo (Variable *var)
VariableProxy * next_unresolved ()
bool is_removed_from_unresolved () const
void mark_removed_from_unresolved ()
bool is_home_object () const
void set_is_home_object ()
Private Types
using IsAssignedField = Expression::NextBitField< bool, 1 >
using IsResolvedField = IsAssignedField::Next< bool, 1 >
using IsRemovedFromUnresolvedField = IsResolvedField::Next< bool, 1 >
using IsNewTargetField = IsRemovedFromUnresolvedField::Next< bool, 1 >
using IsHomeObjectField = IsNewTargetField::Next< bool, 1 >
using HoleCheckModeField = IsHomeObjectField::Next< HoleCheckMode, 1 >
Private Member Functions
VariableProxy (Variable *var, int start_position)
VariableProxy (const AstRawString *name, VariableKind variable_kind, int start_position)
VariableProxy (const VariableProxy *copy_from)
VariableProxy ** next ()
Private Attributes
friend Zone
xx xx xx xx xx xx xx xx xx
union {
 const AstRawString * raw_name_
 Variable * var_
};
VariableProxy * next_unresolved_
Friends
class AstNodeFactory
Additional Inherited Members
Detailed Description
Definition at line 1496 of file ast.h.
Member Typedef Documentation
HoleCheckModeField
using v8::internal::VariableProxy::HoleCheckModeField = IsHomeObjectField::Next<HoleCheckMode, 1> [private]
Definition at line 1614 of file ast.h.
IsAssignedField
using v8::internal::VariableProxy::IsAssignedField = Expression::NextBitField<bool, 1> [private]
Definition at line 1609 of file ast.h.
IsHomeObjectField
using v8::internal::VariableProxy::IsHomeObjectField = IsNewTargetField::Next<bool, 1> [private]
Definition at line 1613 of file ast.h.
IsNewTargetField
using v8::internal::VariableProxy::IsNewTargetField = IsRemovedFromUnresolvedField::Next<bool, 1> [private]
Definition at line 1612 of file ast.h.
IsRemovedFromUnresolvedField
using v8::internal::VariableProxy::IsRemovedFromUnresolvedField = IsResolvedField::Next<bool, 1> [private]
Definition at line 1611 of file ast.h.
IsResolvedField
using v8::internal::VariableProxy::IsResolvedField = IsAssignedField::Next<bool, 1> [private]
Definition at line 1610 of file ast.h.
Constructor & Destructor Documentation
VariableProxy() [1/3]
v8::internal::VariableProxy::VariableProxy (Variable * var, int start_position) [private]
Definition at line 154 of file ast.cc.
    : Expression(start_position, kVariableProxy),
      raw_name_(var->raw_name()),
      next_unresolved_(nullptr) {
  DCHECK(!var->is_this());
  bit_field_ |= IsAssignedField::encode(false) |
                IsResolvedField::encode(false) |
                HoleCheckModeField::encode(HoleCheckMode::kElided);
  BindTo(var);
}
References BindTo(), v8::internal::AstNode::bit_field_, v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::Variable::is_this(), v8::internal::kElided, and var().
VariableProxy() [2/3]
v8::internal::VariableProxy::VariableProxy (const AstRawString * name, VariableKind variable_kind, int start_position) [inline], [private]
Definition at line 1594 of file ast.h.
      : Expression(start_position, kVariableProxy),
        raw_name_(name),
        next_unresolved_(nullptr) {
    DCHECK_NE(THIS_VARIABLE, variable_kind);
    bit_field_ |= IsAssignedField::encode(false) |
                  IsResolvedField::encode(false) |
                  IsRemovedFromUnresolvedField::encode(false) |
                  IsHomeObjectField::encode(false) |
                  HoleCheckModeField::encode(HoleCheckMode::kElided);
  }
References v8::internal::AstNode::bit_field_, DCHECK_NE, v8::base::BitField< T, shift, size, U >::encode(), v8::internal::kElided, and v8::internal::THIS_VARIABLE.
VariableProxy() [3/3]
v8::internal::VariableProxy::VariableProxy (const VariableProxy * copy_from) [explicit], [private]
Definition at line 165 of file ast.cc.
    : Expression(copy_from->position(), kVariableProxy),
      next_unresolved_(nullptr) {
  bit_field_ = copy_from->bit_field_;
  DCHECK(!copy_from->is_resolved());
  raw_name_ = copy_from->raw_name_;
}
References v8::internal::AstNode::bit_field_, v8::internal::DCHECK(), is_resolved(), and raw_name_.
Member Function Documentation
BindTo()
void v8::internal::VariableProxy::BindTo (Variable * var)
Definition at line 173 of file ast.cc.
                                        {
  DCHECK_EQ(raw_name(), var->raw_name());
  set_var(var);
  set_is_resolved();
  var->set_is_used();
  if (is_assigned()) var->SetMaybeAssigned();
}
References DCHECK_EQ, is_assigned(), raw_name(), v8::internal::Variable::raw_name(), set_is_resolved(), v8::internal::Variable::set_is_used(), set_var(), v8::internal::Variable::SetMaybeAssigned(), and var().
Referenced by v8::internal::Parser::DeclareAndBindVariable(), v8::internal::Parser::DeclareBoundVariable(), v8::internal::Scope::ForceDynamicLookup(), v8::internal::Scope::ResolveTo(), and VariableProxy().
clear_is_assigned()
void v8::internal::VariableProxy::clear_is_assigned () [inline]
Definition at line 1526 of file ast.h.
                           {
    bit_field_ = IsAssignedField::update(bit_field_, false);
  }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::update().
Referenced by v8::internal::ArrowHeadParsingScope< Types >::ValidateAndCreateScope().
hole_check_mode()
HoleCheckMode v8::internal::VariableProxy::hole_check_mode () const [inline]
Definition at line 1540 of file ast.h.
                                        {
    HoleCheckMode mode = HoleCheckModeField::decode(bit_field_);
    DCHECK_IMPLIES(mode == HoleCheckMode::kRequired,
                   var()->binding_needs_init() ||
                       var()->local_if_not_shadowed()->binding_needs_init());
    return mode;
  }
References v8::internal::AstNode::bit_field_, DCHECK_IMPLIES, v8::base::BitField< T, shift, size, U >::decode(), v8::internal::kRequired, mode(), and var().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildAssignment(), and v8::internal::interpreter::BytecodeGenerator::VisitForTypeOfValue().
is_assigned()
bool v8::internal::VariableProxy::is_assigned () const [inline]
Definition at line 1519 of file ast.h.
{ return IsAssignedField::decode(bit_field_); }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by BindTo(), v8::internal::Scope::LookupWith(), and v8::internal::Scope::ResolvePreparsedVariable().
is_home_object()
bool v8::internal::VariableProxy::is_home_object () const [inline]
Definition at line 1566 of file ast.h.
{ return IsHomeObjectField::decode(bit_field_); }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::Scope::ResolveVariable().
is_new_target()
bool v8::internal::VariableProxy::is_new_target () const [inline]
Definition at line 1535 of file ast.h.
{ return IsNewTargetField::decode(bit_field_); }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::Parser::IsIdentifier(), and IsValidReferenceExpression().
is_removed_from_unresolved()
bool v8::internal::VariableProxy::is_removed_from_unresolved () const [inline]
Definition at line 1558 of file ast.h.
                                                    {
    return IsRemovedFromUnresolvedField::decode(bit_field_);
  }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::VariableProxy::UnresolvedNext::filter().
is_resolved()
bool v8::internal::VariableProxy::is_resolved () const [inline]
Definition at line 1530 of file ast.h.
{ return IsResolvedField::decode(bit_field_); }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::Scope::AddUnresolved(), v8::internal::PrivateNameScopeIterator::AddUnresolvedPrivateName(), v8::internal::interpreter::BytecodeGenerator::IsLocalVariableWithInternalizedStringHint(), v8::internal::ClassScope::LookupPrivateName(), raw_name(), v8::internal::Scope::ResolveVariable(), set_is_assigned(), set_var(), var(), and VariableProxy().
IsPrivateName()
bool v8::internal::VariableProxy::IsPrivateName () const [inline]
Definition at line 1552 of file ast.h.
{ return raw_name()->IsPrivateName(); }
References v8::internal::AstRawString::IsPrivateName(), and raw_name().
Referenced by v8::internal::PrivateNameScopeIterator::AddUnresolvedPrivateName(), and v8::internal::Scope::ForceDynamicLookup().
IsValidReferenceExpression()
bool v8::internal::VariableProxy::IsValidReferenceExpression () const [inline]
Definition at line 1498 of file ast.h.
{ return !is_new_target(); }
References is_new_target().
location()
Scanner::Location v8::internal::VariableProxy::location () [inline]
Definition at line 1515 of file ast.h.
                             {
    return Scanner::Location(position(), position() + raw_name()->length());
  }
References v8::internal::length, v8::internal::AstNode::position(), and raw_name().
Referenced by v8::internal::ArrowHeadParsingScope< Types >::ValidateAndCreateScope().
mark_removed_from_unresolved()
void v8::internal::VariableProxy::mark_removed_from_unresolved () [inline]
Definition at line 1562 of file ast.h.
                                      {
    bit_field_ = IsRemovedFromUnresolvedField::update(bit_field_, true);
  }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::update().
Referenced by v8::internal::Scope::DeleteUnresolved().
name()
DirectHandle<String> v8::internal::VariableProxy::name () const [inline]
Definition at line 1500 of file ast.h.
{ return raw_name()->string(); }
References raw_name(), and v8::internal::AstRawString::string().
next()
VariableProxy** v8::internal::VariableProxy::next () [inline], [private]
Definition at line 1621 of file ast.h.
{ return &next_unresolved_; }
References next_unresolved_.
Referenced by v8::internal::VariableProxy::UnresolvedNext::filter(), and v8::internal::VariableProxy::UnresolvedNext::next().
next_unresolved()
VariableProxy* v8::internal::VariableProxy::next_unresolved () [inline]
Definition at line 1557 of file ast.h.
{ return next_unresolved_; }
References next_unresolved_.
Referenced by v8::internal::ClassScope::ResolvePrivateNamesPartially().
raw_name()
const AstRawString* v8::internal::VariableProxy::raw_name () const [inline]
Definition at line 1501 of file ast.h.
                                       {
    return is_resolved() ? var_->raw_name() : raw_name_;
  }
References is_resolved(), v8::internal::Variable::raw_name(), raw_name_, and var_.
Referenced by BindTo(), v8::internal::PreParser::DeclareAndBindVariable(), v8::internal::Parser::DeclareAndBindVariable(), v8::internal::Scope::ForceDynamicLookup(), IsPrivateName(), v8::internal::Expression::IsUndefinedLiteral(), location(), v8::internal::Scope::Lookup(), v8::internal::ClassScope::LookupPrivateName(), v8::internal::Scope::LookupSloppyEval(), v8::internal::Scope::LookupWith(), name(), v8::internal::ParserBase< Impl >::ParseClassLiteral(), v8::internal::ParserBase< Impl >::ParseExpressionOrLabelledStatement(), v8::internal::Scope::ResolvePreparsedVariable(), and v8::internal::SuperCallReference::SuperCallReference().
set_is_assigned()
void v8::internal::VariableProxy::set_is_assigned () [inline]
Definition at line 1520 of file ast.h.
                         {
    bit_field_ = IsAssignedField::update(bit_field_, true);
    if (is_resolved()) {
      var()->SetMaybeAssigned();
    }
  }
References v8::internal::AstNode::bit_field_, is_resolved(), v8::internal::Variable::SetMaybeAssigned(), v8::base::BitField< T, shift, size, U >::update(), and var().
set_is_home_object()
void v8::internal::VariableProxy::set_is_home_object () [inline]
Definition at line 1568 of file ast.h.
                            {
    bit_field_ = IsHomeObjectField::update(bit_field_, true);
  }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::update().
Referenced by v8::internal::Parser::NewSuperPropertyReference().
set_is_new_target()
void v8::internal::VariableProxy::set_is_new_target () [inline]
Definition at line 1536 of file ast.h.
                           {
    bit_field_ = IsNewTargetField::update(bit_field_, true);
  }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::update().
set_is_resolved()
void v8::internal::VariableProxy::set_is_resolved () [inline]
Definition at line 1531 of file ast.h.
                         {
    bit_field_ = IsResolvedField::update(bit_field_, true);
  }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::update().
Referenced by BindTo().
set_needs_hole_check()
void v8::internal::VariableProxy::set_needs_hole_check () [inline]
Definition at line 1547 of file ast.h.
                              {
    bit_field_ =
        HoleCheckModeField::update(bit_field_, HoleCheckMode::kRequired);
  }
References v8::internal::AstNode::bit_field_, v8::internal::kRequired, and v8::base::BitField< T, shift, size, U >::update().
Referenced by v8::internal::anonymous_namespace{scopes.cc}::SetNeedsHoleCheck().
set_var()
void v8::internal::VariableProxy::set_var (Variable * v) [inline]
Definition at line 1509 of file ast.h.
                            {
    DCHECK(!is_resolved());
    DCHECK_NOT_NULL(v);
    var_ = v;
  }
References v8::internal::DCHECK(), DCHECK_NOT_NULL, is_resolved(), and var_.
Referenced by BindTo().
var()
Variable* v8::internal::VariableProxy::var () const [inline]
Definition at line 1505 of file ast.h.
                        {
    DCHECK(is_resolved());
    return var_;
  }
References v8::internal::DCHECK(), is_resolved(), and var_.
Referenced by BindTo(), v8::internal::interpreter::BytecodeGenerator::BuildAssignment(), v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), v8::internal::interpreter::BytecodeGenerator::BuildClassProperty(), v8::internal::ClassLiteralProperty::computed_name_var(), v8::internal::Parser::CreateForEachStatementTDZ(), v8::internal::Parser::CreateSyntheticContextVariableProxy(), v8::internal::Parser::DeclareClass(), v8::internal::Parser::DeclarePrivateClassMember(), v8::internal::Parser::DesugarLexicalBindingsInForStatement(), v8::internal::Property::GetAssignType(), v8::internal::interpreter::BytecodeGenerator::GetCachedLoadICSlot(), v8::internal::interpreter::BytecodeGenerator::GetCachedStoreICSlot(), v8::internal::Call::GetCallType(), hole_check_mode(), v8::internal::interpreter::BytecodeGenerator::IsLocalVariableWithInternalizedStringHint(), v8::internal::Expression::IsUndefinedLiteral(), v8::internal::Parser::ParseExportDefault(), v8::internal::ClassLiteralProperty::private_name_var(), set_is_assigned(), VariableProxy(), and v8::internal::interpreter::BytecodeGenerator::VisitForTypeOfValue().
Friends And Related Function Documentation
AstNodeFactory
friend class AstNodeFactory [friend]
Definition at line 1589 of file ast.h.
Member Data Documentation
union { ... } [private]
next_unresolved_
VariableProxy* v8::internal::VariableProxy::next_unresolved_ [private]
Definition at line 1622 of file ast.h.
Referenced by next(), and next_unresolved().
raw_name_
const AstRawString* v8::internal::VariableProxy::raw_name_
Definition at line 1617 of file ast.h.
Referenced by raw_name(), and VariableProxy().
var_
Variable* v8::internal::VariableProxy::var_
Definition at line 1618 of file ast.h.
Referenced by raw_name(), set_var(), and var().
Zone
friend v8::internal::VariableProxy::Zone [private]
Definition at line 1590 of file ast.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ast/ast.h
/mnt/V8SourceCode/src/ast/ast.cc