v8::internal::compiler::Dependable Class Reference
#include <escape-analysis.h>
Public Member Functions
Dependable (Zone *zone)
void AddDependency (Node *node)
void RevisitDependants (EffectGraphReducer *reducer)
Private Attributes
ZoneVector< Node * > dependants_
Detailed Description
Definition at line 108 of file escape-analysis.h.
Constructor & Destructor Documentation
Dependable()
v8::internal::compiler::Dependable::Dependable (Zone * zone) [inline], [explicit]
Definition at line 110 of file escape-analysis.h.
: dependants_(zone) {}
Member Function Documentation
AddDependency()
void v8::internal::compiler::Dependable::AddDependency (Node * node) [inline]
Definition at line 111 of file escape-analysis.h.
{ dependants_.push_back(node); }
References dependants_, and v8::internal::ZoneVector< T >::push_back().
Referenced by v8::internal::compiler::EscapeAnalysisTracker::Scope::GetVirtualObject(), and v8::internal::compiler::EscapeAnalysisTracker::Scope::InitVirtualObject().
RevisitDependants()
void v8::internal::compiler::Dependable::RevisitDependants (EffectGraphReducer * reducer) [inline]
Definition at line 112 of file escape-analysis.h.
                                                      {
    for (Node* node : dependants_) {
      reducer->Revisit(node);
    }
    dependants_.clear();
  }
References v8::internal::ZoneVector< T >::clear(), dependants_, and v8::internal::compiler::EffectGraphReducer::Revisit().
Member Data Documentation
dependants_
ZoneVector<Node*> v8::internal::compiler::Dependable::dependants_ [private]
Definition at line 120 of file escape-analysis.h.
Referenced by AddDependency(), and RevisitDependants().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/escape-analysis.h