v8::internal::compiler::FunctionalList< A > Class Template Reference
#include <functional-list.h>
Classes
struct Cons
class iterator
Public Member Functions
FunctionalList ()
bool operator== (const FunctionalList< A > &other) const
bool operator!= (const FunctionalList< A > &other) const
bool TriviallyEquals (const FunctionalList< A > &other) const
const A & Front () const
FunctionalList Rest () const
void DropFront ()
void PushFront (A a, Zone *zone)
void PushFront (A a, Zone *zone, FunctionalList hint)
void ResetToCommonAncestor (FunctionalList other)
size_t Size () const
void Clear ()
iterator begin () const
iterator end () const
Private Attributes
Cons * elements_
Detailed Description
template<class A>
class v8::internal::compiler::FunctionalList< A >
Definition at line 24 of file functional-list.h.
Constructor & Destructor Documentation
FunctionalList()
template<class A >
v8::internal::compiler::FunctionalList< A >::FunctionalList () [inline]
Definition at line 35 of file functional-list.h.
: elements_(nullptr) {}
Member Function Documentation
begin()
template<class A >
iterator v8::internal::compiler::FunctionalList< A >::begin () const [inline]
Definition at line 121 of file functional-list.h.
{ return iterator(elements_); }
References v8::internal::compiler::FunctionalList< A >::elements_.
Referenced by v8::internal::compiler::FunctionalList< A >::operator==().
Clear()
template<class A >
void v8::internal::compiler::FunctionalList< A >::Clear () [inline]
Definition at line 101 of file functional-list.h.
{ elements_ = nullptr; }
References v8::internal::compiler::FunctionalList< A >::elements_.
DropFront()
template<class A >
void v8::internal::compiler::FunctionalList< A >::DropFront () [inline]
Definition at line 67 of file functional-list.h.
                   {
    CHECK_GT(Size(), 0);
    elements_ = elements_->rest;
  }
References CHECK_GT, v8::internal::compiler::FunctionalList< A >::elements_, v8::internal::compiler::FunctionalList< A >::Cons::rest, and v8::internal::compiler::FunctionalList< A >::Size().
Referenced by v8::internal::compiler::FunctionalList< A >::ResetToCommonAncestor().
end()
template<class A >
iterator v8::internal::compiler::FunctionalList< A >::end () const [inline]
Definition at line 122 of file functional-list.h.
{ return iterator(nullptr); }
Front()
template<class A >
const A& v8::internal::compiler::FunctionalList< A >::Front () const [inline]
Definition at line 56 of file functional-list.h.
                         {
    DCHECK_GT(Size(), 0);
    return elements_->top;
  }
References DCHECK_GT, v8::internal::compiler::FunctionalList< A >::elements_, v8::internal::compiler::FunctionalList< A >::Size(), and v8::internal::compiler::FunctionalList< A >::Cons::top.
Referenced by v8::internal::compiler::ControlPathState< NodeState, node_uniqueness >::AddState(), and v8::internal::compiler::FunctionalList< A >::PushFront().
operator!=()
template<class A >
bool v8::internal::compiler::FunctionalList< A >::operator!= (const FunctionalList< A > & other) const [inline]
Definition at line 48 of file functional-list.h.
                                                        {
    return !(*this == other);
  }
operator==()
template<class A >
bool v8::internal::compiler::FunctionalList< A >::operator== (const FunctionalList< A > & other) const [inline]
Definition at line 37 of file functional-list.h.
                                                        {
    if (Size() != other.Size()) return false;
    iterator it = begin();
    iterator other_it = other.begin();
    while (true) {
      if (it == other_it) return true;
      if (*it != *other_it) return false;
      ++it;
      ++other_it;
    }
  }
References v8::internal::compiler::FunctionalList< A >::begin(), and v8::internal::compiler::FunctionalList< A >::Size().
PushFront() [1/2]
template<class A >
void v8::internal::compiler::FunctionalList< A >::PushFront (A a, Zone * zone) [inline]
Definition at line 72 of file functional-list.h.
                                  {
    elements_ = zone->New<Cons>(std::move(a), elements_);
  }
References v8::internal::compiler::FunctionalList< A >::elements_, and v8::internal::Zone::New().
Referenced by v8::internal::compiler::LoopVariableOptimizer::AddCmpToLimits(), v8::internal::compiler::ControlPathState< NodeState, node_uniqueness >::AddState(), v8::internal::compiler::ControlPathState< NodeState, node_uniqueness >::AddStateInNewBlock(), and v8::internal::compiler::FunctionalList< A >::PushFront().
PushFront() [2/2]
template<class A >
void v8::internal::compiler::FunctionalList< A >::PushFront (A a, Zone * zone, FunctionalList< A > hint) [inline]
Definition at line 78 of file functional-list.h.
                                                       {
    if (hint.Size() == Size() + 1 && hint.Front() == a &&
        hint.Rest() == *this) {
      *this = hint;
    } else {
      PushFront(a, zone);
    }
  }
References v8::internal::compiler::FunctionalList< A >::Front(), v8::internal::compiler::FunctionalList< A >::PushFront(), v8::internal::compiler::FunctionalList< A >::Rest(), and v8::internal::compiler::FunctionalList< A >::Size().
ResetToCommonAncestor()
template<class A >
void v8::internal::compiler::FunctionalList< A >::ResetToCommonAncestor (FunctionalList< A > other) [inline]
Definition at line 90 of file functional-list.h.
                                                   {
    while (other.Size() > Size()) other.DropFront();
    while (other.Size() < Size()) DropFront();
    while (elements_ != other.elements_) {
      DropFront();
      other.DropFront();
    }
  }
References v8::internal::compiler::FunctionalList< A >::DropFront(), v8::internal::compiler::FunctionalList< A >::elements_, and v8::internal::compiler::FunctionalList< A >::Size().
Referenced by v8::internal::compiler::LoopVariableOptimizer::VisitMerge().
Rest()
template<class A >
FunctionalList v8::internal::compiler::FunctionalList< A >::Rest () const [inline]
Definition at line 61 of file functional-list.h.
                              {
    FunctionalList result = *this;
    result.DropFront();
    return result;
  }
References v8::base::internal::result.
Referenced by v8::internal::compiler::FunctionalList< A >::PushFront().
Size()
template<class A >
size_t v8::internal::compiler::FunctionalList< A >::Size () const [inline]
Definition at line 99 of file functional-list.h.
{ return elements_ ? elements_->size : 0; }
References v8::internal::compiler::FunctionalList< A >::elements_, and v8::internal::compiler::FunctionalList< A >::Cons::size.
Referenced by v8::internal::compiler::FunctionalList< A >::DropFront(), v8::internal::compiler::FunctionalList< A >::Front(), v8::internal::compiler::FunctionalList< A >::operator==(), v8::internal::compiler::FunctionalList< A >::PushFront(), and v8::internal::compiler::FunctionalList< A >::ResetToCommonAncestor().
TriviallyEquals()
template<class A >
bool v8::internal::compiler::FunctionalList< A >::TriviallyEquals (const FunctionalList< A > & other) const [inline]
Definition at line 52 of file functional-list.h.
                                                             {
    return elements_ == other.elements_;
  }
References v8::internal::compiler::FunctionalList< A >::elements_.
Member Data Documentation
elements_
template<class A >
Cons* v8::internal::compiler::FunctionalList< A >::elements_ [private]
Definition at line 125 of file functional-list.h.
Referenced by v8::internal::compiler::FunctionalList< A >::begin(), v8::internal::compiler::FunctionalList< A >::Clear(), v8::internal::compiler::FunctionalList< A >::DropFront(), v8::internal::compiler::FunctionalList< A >::Front(), v8::internal::compiler::FunctionalList< A >::PushFront(), v8::internal::compiler::FunctionalList< A >::ResetToCommonAncestor(), v8::internal::compiler::FunctionalList< A >::Size(), and v8::internal::compiler::FunctionalList< A >::TriviallyEquals().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/functional-list.h