v8::internal::baseline::BytecodeOffsetTableBuilder Class Reference
#include <baseline-compiler.h>
Public Member Functions
void AddPosition (size_t pc_offset)
template<typename IsolateT >
Handle< TrustedByteArray > ToBytecodeOffsetTable (IsolateT *isolate)
void Reserve (size_t size)
Private Attributes
size_t previous_pc_ = 0
std::vector< uint8_t > bytes_
Detailed Description
Definition at line 30 of file baseline-compiler.h.
Member Function Documentation
AddPosition()
void v8::internal::baseline::BytecodeOffsetTableBuilder::AddPosition (size_t pc_offset) [inline]
Definition at line 32 of file baseline-compiler.h.
                                     {
    size_t pc_diff = pc_offset - previous_pc_;
    DCHECK_GE(pc_diff, 0);
    DCHECK_LE(pc_diff, std::numeric_limits<uint32_t>::max());
    base::VLQEncodeUnsigned(&bytes_, static_cast<uint32_t>(pc_diff));
    previous_pc_ = pc_offset;
  }
References bytes_, DCHECK_GE, DCHECK_LE, previous_pc_, and v8::base::VLQEncodeUnsigned().
Referenced by v8::internal::baseline::BaselineCompiler::AddPosition().
Reserve()
void v8::internal::baseline::BytecodeOffsetTableBuilder::Reserve (size_t size) [inline]
Definition at line 43 of file baseline-compiler.h.
{ bytes_.reserve(size); }
References bytes_, and size().
Referenced by v8::internal::baseline::BaselineCompiler::BaselineCompiler().
ToBytecodeOffsetTable()
template<typename IsolateT >
Handle< TrustedByteArray > v8::internal::baseline::BytecodeOffsetTableBuilder::ToBytecodeOffsetTable (IsolateT * isolate)
Definition at line 72 of file baseline-compiler.cc.
                       {
  if (bytes_.empty()) return isolate->factory()->empty_trusted_byte_array();
  Handle<TrustedByteArray> table =
      isolate->factory()->NewTrustedByteArray(static_cast<int>(bytes_.size()));
  MemCopy(table->begin(), bytes_.data(), bytes_.size());
  return table;
}
References bytes_, and v8::internal::MemCopy().
Referenced by v8::internal::baseline::BaselineCompiler::Build().
Member Data Documentation
bytes_
std::vector<uint8_t> v8::internal::baseline::BytecodeOffsetTableBuilder::bytes_ [private]
Definition at line 47 of file baseline-compiler.h.
Referenced by AddPosition(), Reserve(), and ToBytecodeOffsetTable().
previous_pc_
size_t v8::internal::baseline::BytecodeOffsetTableBuilder::previous_pc_ = 0 [private]
Definition at line 46 of file baseline-compiler.h.
Referenced by AddPosition().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/baseline/baseline-compiler.h
/mnt/V8SourceCode/src/baseline/baseline-compiler.cc