v8::internal::interpreter::HandlerTableBuilder Class Reference
#include <handler-table-builder.h>
Classes
struct Entry
Public Member Functions
HandlerTableBuilder (Zone *zone)
HandlerTableBuilder (const HandlerTableBuilder &)=delete
HandlerTableBuilder & operator= (const HandlerTableBuilder &)=delete
template<typename IsolateT >
DirectHandle< TrustedByteArray > ToHandlerTable (IsolateT *isolate)
int NewHandlerEntry ()
void SetTryRegionStart (int handler_id, size_t offset)
void SetTryRegionEnd (int handler_id, size_t offset)
void SetHandlerTarget (int handler_id, size_t offset)
void SetPrediction (int handler_id, HandlerTable::CatchPrediction prediction)
void SetContextRegister (int handler_id, Register reg)
Private Attributes
ZoneVector< Entry > entries_
Detailed Description
Definition at line 21 of file handler-table-builder.h.
Constructor & Destructor Documentation
HandlerTableBuilder() [1/2]
v8::internal::interpreter::HandlerTableBuilder::HandlerTableBuilder (Zone * zone) [explicit]
Definition at line 16 of file handler-table-builder.cc.
: entries_(zone) {}
HandlerTableBuilder() [2/2]
v8::internal::interpreter::HandlerTableBuilder::HandlerTableBuilder (const HandlerTableBuilder &) [delete]
Member Function Documentation
NewHandlerEntry()
int v8::internal::interpreter::HandlerTableBuilder::NewHandlerEntry ()
Definition at line 42 of file handler-table-builder.cc.
                                         {
  int handler_id = static_cast<int>(entries_.size());
  Entry entry = {0, 0, 0, Register::invalid_value(), HandlerTable::UNCAUGHT};
  entries_.push_back(entry);
  return handler_id;
}
References entries_, v8::internal::interpreter::Register::invalid_value(), and v8::internal::HandlerTable::UNCAUGHT.
operator=()
HandlerTableBuilder& v8::internal::interpreter::HandlerTableBuilder::operator= (const HandlerTableBuilder &) [delete]
SetContextRegister()
void v8::internal::interpreter::HandlerTableBuilder::SetContextRegister (int handler_id, Register reg)
Definition at line 73 of file handler-table-builder.cc.
                                                                         {
  entries_[handler_id].context = reg;
}
References entries_.
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::MarkTryBegin().
SetHandlerTarget()
void v8::internal::interpreter::HandlerTableBuilder::SetHandlerTarget (int handler_id, size_t offset)
Definition at line 62 of file handler-table-builder.cc.
                                                                        {
  DCHECK(Smi::IsValid(offset)); // Encoding of handler table requires this.
  entries_[handler_id].offset_target = offset;
}
References v8::internal::DCHECK(), entries_, and v8::internal::Smi::IsValid().
Referenced by v8::internal::interpreter::BytecodeArrayWriter::BindHandlerTarget().
SetPrediction()
void v8::internal::interpreter::HandlerTableBuilder::SetPrediction (int handler_id, HandlerTable::CatchPrediction prediction)
Definition at line 67 of file handler-table-builder.cc.
                                                            {
  entries_[handler_id].catch_prediction_ = prediction;
}
References entries_.
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::MarkHandler().
SetTryRegionEnd()
void v8::internal::interpreter::HandlerTableBuilder::SetTryRegionEnd (int handler_id, size_t offset)
Definition at line 56 of file handler-table-builder.cc.
                                                                       {
  DCHECK(Smi::IsValid(offset)); // Encoding of handler table requires this.
  entries_[handler_id].offset_end = offset;
}
References v8::internal::DCHECK(), entries_, and v8::internal::Smi::IsValid().
Referenced by v8::internal::interpreter::BytecodeArrayWriter::BindTryRegionEnd().
SetTryRegionStart()
void v8::internal::interpreter::HandlerTableBuilder::SetTryRegionStart (int handler_id, size_t offset)
Definition at line 50 of file handler-table-builder.cc.
                                                                         {
  DCHECK(Smi::IsValid(offset)); // Encoding of handler table requires this.
  entries_[handler_id].offset_start = offset;
}
References v8::internal::DCHECK(), entries_, and v8::internal::Smi::IsValid().
Referenced by v8::internal::interpreter::BytecodeArrayWriter::BindTryRegionStart().
ToHandlerTable()
template<typename IsolateT >
template DirectHandle< TrustedByteArray > v8::internal::interpreter::HandlerTableBuilder::ToHandlerTable (IsolateT * isolate)
Definition at line 19 of file handler-table-builder.cc.
                       {
  int handler_table_size = static_cast<int>(entries_.size());
  DirectHandle<TrustedByteArray> table_byte_array =
      isolate->factory()->NewTrustedByteArray(
          HandlerTable::LengthForRange(handler_table_size));
  HandlerTable table(*table_byte_array);
  for (int i = 0; i < handler_table_size; ++i) {
    Entry& entry = entries_[i];
    HandlerTable::CatchPrediction pred = entry.catch_prediction_;
    table.SetRangeStart(i, static_cast<int>(entry.offset_start));
    table.SetRangeEnd(i, static_cast<int>(entry.offset_end));
    table.SetRangeHandler(i, static_cast<int>(entry.offset_target), pred);
    table.SetRangeData(i, entry.context.index());
  }
  return table_byte_array;
}
References v8::internal::interpreter::HandlerTableBuilder::Entry::catch_prediction_, v8::internal::interpreter::HandlerTableBuilder::Entry::context, entries_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::interpreter::Register::index(), v8::internal::HandlerTable::LengthForRange(), v8::internal::interpreter::HandlerTableBuilder::Entry::offset_end, v8::internal::interpreter::HandlerTableBuilder::Entry::offset_start, v8::internal::interpreter::HandlerTableBuilder::Entry::offset_target, v8::internal::HandlerTable::SetRangeData(), v8::internal::HandlerTable::SetRangeEnd(), v8::internal::HandlerTable::SetRangeHandler(), and v8::internal::HandlerTable::SetRangeStart().
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::ToBytecodeArray().
Member Data Documentation
entries_
ZoneVector<Entry> v8::internal::interpreter::HandlerTableBuilder::entries_ [private]
Definition at line 55 of file handler-table-builder.h.
Referenced by NewHandlerEntry(), SetContextRegister(), SetHandlerTarget(), SetPrediction(), SetTryRegionEnd(), SetTryRegionStart(), and ToHandlerTable().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/interpreter/handler-table-builder.h
/mnt/V8SourceCode/src/interpreter/handler-table-builder.cc