v8::internal::wasm::DescriptorsSectionIterator::ProtoConfig Class Reference
#include <module-decoder-impl.h>
Public Member Functions
uint32_t import_index () const
Private Member Functions
ProtoConfig (DescriptorsSectionIterator *decoder, uint32_t max_import_index)
Private Attributes
uint32_t import_index_
Friends
class DescriptorsSectionIterator
Additional Inherited Members
Detailed Description
Definition at line 3160 of file module-decoder-impl.h.
Constructor & Destructor Documentation
ProtoConfig()
v8::internal::wasm::DescriptorsSectionIterator::ProtoConfig::ProtoConfig (DescriptorsSectionIterator * decoder, uint32_t max_import_index) [inline], [private]
Definition at line 3167 of file module-decoder-impl.h.
        : Entry(decoder) {
      const uint8_t* pos = decoder->pc();
      import_index_ = consume_u32v("import index");
      if (import_index_ > max_import_index) {
        decoder->errorf(pos, "import index %u is out of range", import_index_);
      }
      ProceedToMethods();
    }
References v8::internal::wasm::DescriptorsSectionIterator::Entry::consume_u32v(), v8::internal::wasm::DescriptorsSectionIterator::Entry::decoder(), v8::internal::wasm::Decoder::errorf(), import_index_, v8::internal::wasm::Decoder::pc(), and v8::internal::wasm::DescriptorsSectionIterator::Entry::ProceedToMethods().
Member Function Documentation
import_index()
uint32_t v8::internal::wasm::DescriptorsSectionIterator::ProtoConfig::import_index () const [inline]
Definition at line 3162 of file module-decoder-impl.h.
{ return import_index_; }
References import_index_.
Referenced by v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Modular_Impl().
Friends And Related Function Documentation
DescriptorsSectionIterator
friend class DescriptorsSectionIterator [friend]
Definition at line 3165 of file module-decoder-impl.h.
Member Data Documentation
import_index_
uint32_t v8::internal::wasm::DescriptorsSectionIterator::ProtoConfig::import_index_ [private]
Definition at line 3177 of file module-decoder-impl.h.
Referenced by import_index(), and ProtoConfig().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/module-decoder-impl.h