v8::UnboundScript Class Reference
A compiled JavaScript script, not yet tied to a Context.
#include <v8-script.h>
Public Member Functions
Local< Script > BindToCurrentContext ()
Binds the script to the currently entered context.
int GetId () const
Local< Value > GetScriptName ()
Local< Value > GetSourceURL ()
Data read from magic sourceURL comments.
Local< Value > GetSourceMappingURL ()
Data read from magic sourceMappingURL comments.
int GetLineNumber (int code_pos=0)
Returns zero based line number of the code_pos location in the script.
int GetColumnNumber (int code_pos=0)
Returns zero based column number of the code_pos location in the script.
Static Public Attributes
static const int kNoScriptId = 0
Detailed Description
A compiled JavaScript script, not yet tied to a Context.
Definition at line 60 of file v8-script.h.
Member Function Documentation
BindToCurrentContext()
Local< Script > v8::UnboundScript::BindToCurrentContext ()
Binds the script to the currently entered context.
Definition at line 1782 of file api.cc.
                                                  {
  auto function_info = Utils::OpenDirectHandle(this);
  // TODO(jgruber): Remove this DCHECK once Function::GetUnboundScript is gone.
  DCHECK(!i::HeapLayout::InReadOnlySpace(*function_info));
  i::Isolate* i_isolate = i::GetIsolateFromWritableObject(*function_info);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::DirectHandle<i::JSFunction> function =
      i::Factory::JSFunctionBuilder{i_isolate, function_info,
                                    i_isolate->native_context()}
          .Build();
  return ToApiHandle<Script>(function);
}
References DCHECK, v8::internal::GetIsolateFromWritableObject(), v8::internal::HeapLayout::InReadOnlySpace(), v8::internal::Isolate::native_context(), and v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::V8InspectorImpl::compileAndRunInternalScript().
GetColumnNumber()
int v8::UnboundScript::GetColumnNumber (int code_pos = 0)
Returns zero based column number of the code_pos location in the script.
-1 will be returned if no information available.
Definition at line 1823 of file api.cc.
                                               {
  auto obj = Utils::OpenDirectHandle(this);
  if (i::IsScript(obj->script())) {
    // TODO(jgruber): Remove this DCHECK once Function::GetUnboundScript is
    // gone.
    DCHECK(!i::HeapLayout::InReadOnlySpace(*obj));
    i::Isolate* i_isolate = i::GetIsolateFromWritableObject(*obj);
    EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
    ApiRuntimeCallStatsScope rcs_scope(
        i_isolate, RCCId::kAPI_UnboundScript_GetColumnNumber);
    i::DirectHandle<i::Script> script(i::Cast<i::Script>(obj->script()),
                                      i_isolate);
    return i::Script::GetColumnNumber(script, code_pos);
  } else {
    return -1;
  }
}
References DCHECK, v8::internal::Script::GetColumnNumber(), v8::internal::GetIsolateFromWritableObject(), v8::internal::HeapLayout::InReadOnlySpace(), v8::Utils::OpenDirectHandle(), and v8::internal::script.
GetId()
int v8::UnboundScript::GetId () const
Definition at line 1795 of file api.cc.
                               {
  auto function_info = Utils::OpenDirectHandle(this);
  // TODO(jgruber): Remove this DCHECK once Function::GetUnboundScript is gone.
  DCHECK(!i::HeapLayout::InReadOnlySpace(*function_info));
  ApiRuntimeCallStatsScope rcs_scope(
      i::GetIsolateFromWritableObject(*function_info),
      RCCId::kAPI_UnboundScript_GetId);
  return i::Cast<i::Script>(function_info->script())->id();
}
References DCHECK, v8::internal::GetIsolateFromWritableObject(), v8::internal::HeapLayout::InReadOnlySpace(), and v8::Utils::OpenDirectHandle().
GetLineNumber()
int v8::UnboundScript::GetLineNumber (int code_pos = 0)
Returns zero based line number of the code_pos location in the script.
-1 will be returned if no information available.
Definition at line 1805 of file api.cc.
                                             {
  auto obj = Utils::OpenDirectHandle(this);
  if (i::IsScript(obj->script())) {
    // TODO(jgruber): Remove this DCHECK once Function::GetUnboundScript is
    // gone.
    DCHECK(!i::HeapLayout::InReadOnlySpace(*obj));
    i::Isolate* i_isolate = i::GetIsolateFromWritableObject(*obj);
    EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
    ApiRuntimeCallStatsScope rcs_scope(i_isolate,
                                       RCCId::kAPI_UnboundScript_GetLineNumber);
    i::DirectHandle<i::Script> script(i::Cast<i::Script>(obj->script()),
                                      i_isolate);
    return i::Script::GetLineNumber(script, code_pos);
  } else {
    return -1;
  }
}
References DCHECK, v8::internal::GetIsolateFromWritableObject(), v8::internal::Script::GetLineNumber(), v8::internal::HeapLayout::InReadOnlySpace(), v8::Utils::OpenDirectHandle(), and v8::internal::script.
GetScriptName()
Local< Value > v8::UnboundScript::GetScriptName ()
Definition at line 1841 of file api.cc.
                                          {
  auto obj = Utils::OpenDirectHandle(this);
  if (i::IsScript(obj->script())) {
    // TODO(jgruber): Remove this DCHECK once Function::GetUnboundScript is
    // gone.
    DCHECK(!i::HeapLayout::InReadOnlySpace(*obj));
    i::Isolate* i_isolate = i::GetIsolateFromWritableObject(*obj);
    EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
    ApiRuntimeCallStatsScope rcs_scope(i_isolate,
                                       RCCId::kAPI_UnboundScript_GetName);
    i::Tagged<i::Object> name = i::Cast<i::Script>(obj->script())->name();
    return Utils::ToLocal(i::direct_handle(name, i_isolate));
  } else {
    return {};
  }
}
References DCHECK, v8::internal::direct_handle(), v8::internal::GetIsolateFromWritableObject(), v8::internal::HeapLayout::InReadOnlySpace(), name, and v8::Utils::OpenDirectHandle().
GetSourceMappingURL()
Local< Value > v8::UnboundScript::GetSourceMappingURL ()
Data read from magic sourceMappingURL comments.
Definition at line 1875 of file api.cc.
                                                {
  auto obj = Utils::OpenDirectHandle(this);
  if (i::IsScript(obj->script())) {
    // TODO(jgruber): Remove this DCHECK once Function::GetUnboundScript is
    // gone.
    DCHECK(!i::HeapLayout::InReadOnlySpace(*obj));
    i::Isolate* i_isolate = i::GetIsolateFromWritableObject(*obj);
    ApiRuntimeCallStatsScope rcs_scope(
        i_isolate, RCCId::kAPI_UnboundScript_GetSourceMappingURL);
    EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
    i::Tagged<i::Object> url =
        i::Cast<i::Script>(obj->script())->source_mapping_url();
    return Utils::ToLocal(i::direct_handle(url, i_isolate));
  } else {
    return {};
  }
}
References DCHECK, v8::internal::direct_handle(), v8::internal::GetIsolateFromWritableObject(), v8::internal::HeapLayout::InReadOnlySpace(), and v8::Utils::OpenDirectHandle().
GetSourceURL()
Local< Value > v8::UnboundScript::GetSourceURL ()
Data read from magic sourceURL comments.
Definition at line 1858 of file api.cc.
                                         {
  auto obj = Utils::OpenDirectHandle(this);
  if (i::IsScript(obj->script())) {
    // TODO(jgruber): Remove this DCHECK once Function::GetUnboundScript is
    // gone.
    DCHECK(!i::HeapLayout::InReadOnlySpace(*obj));
    i::Isolate* i_isolate = i::GetIsolateFromWritableObject(*obj);
    ApiRuntimeCallStatsScope rcs_scope(i_isolate,
                                       RCCId::kAPI_UnboundScript_GetSourceURL);
    EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
    i::Tagged<i::Object> url = i::Cast<i::Script>(obj->script())->source_url();
    return Utils::ToLocal(i::direct_handle(url, i_isolate));
  } else {
    return {};
  }
}
References DCHECK, v8::internal::direct_handle(), v8::internal::GetIsolateFromWritableObject(), v8::internal::HeapLayout::InReadOnlySpace(), and v8::Utils::OpenDirectHandle().
Member Data Documentation
kNoScriptId
const int v8::UnboundScript::kNoScriptId = 0 [static]
Definition at line 91 of file v8-script.h.
Referenced by v8::internal::SamplingHeapProfiler::AddStack(), v8_inspector::anonymous_namespace{value-mirror.cc}::LocationMirror::create(), v8::internal::Heap::CreateInitialMutableObjects(), v8::internal::SamplingHeapProfiler::AllocationNode::function_id(), v8_inspector::anonymous_namespace{value-mirror.cc}::getErrorProperty(), v8::internal::CodeEntry::GetHash(), v8_inspector::ValueMirror::getProperties(), v8::internal::CodeEntry::IsSameFunctionAs(), v8::internal::Heap::NextScriptId(), v8::Function::ScriptId(), and v8::internal::SamplingHeapProfiler::TranslateAllocationNode().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-script.h
/mnt/V8SourceCode/src/api/api.cc