v8::internal::maglev::BranchControlNode Class Reference
#include <maglev-ir.h>
Public Member Functions
BranchControlNode (uint64_t bitfield, BasicBlockRef *if_true_refs, BasicBlockRef *if_false_refs)
BasicBlock * if_true () const
BasicBlock * if_false () const
void set_if_true (BasicBlock *block)
void set_if_false (BasicBlock *block)
Private Attributes
BasicBlockRef if_true_
BasicBlockRef if_false_
Additional Inherited Members
Detailed Description
Definition at line 11258 of file maglev-ir.h.
Constructor & Destructor Documentation
BranchControlNode()
v8::internal::maglev::BranchControlNode::BranchControlNode (uint64_t bitfield, BasicBlockRef * if_true_refs, BasicBlockRef * if_false_refs) [inline]
Definition at line 11260 of file maglev-ir.h.
      : ConditionalControlNode(bitfield),
        if_true_(if_true_refs),
        if_false_(if_false_refs) {}
Member Function Documentation
if_false()
BasicBlock* v8::internal::maglev::BranchControlNode::if_false () const [inline]
Definition at line 11267 of file maglev-ir.h.
{ return if_false_.block_ptr(); }
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::PatchJumps(), and v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::PrintTargets().
if_true()
BasicBlock* v8::internal::maglev::BranchControlNode::if_true () const [inline]
Definition at line 11266 of file maglev-ir.h.
{ return if_true_.block_ptr(); }
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::PatchJumps(), and v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::PrintTargets().
set_if_false()
void v8::internal::maglev::BranchControlNode::set_if_false (BasicBlock * block) [inline]
Definition at line 11270 of file maglev-ir.h.
{ if_false_.set_block_ptr(block); }
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::PatchJumps().
set_if_true()
void v8::internal::maglev::BranchControlNode::set_if_true (BasicBlock * block) [inline]
Definition at line 11269 of file maglev-ir.h.
{ if_true_.set_block_ptr(block); }
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::PatchJumps().
Member Data Documentation
if_false_
BasicBlockRef v8::internal::maglev::BranchControlNode::if_false_ [private]
Definition at line 11274 of file maglev-ir.h.
if_true_
BasicBlockRef v8::internal::maglev::BranchControlNode::if_true_ [private]
Definition at line 11273 of file maglev-ir.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h