v8::internal::ReadOnlyHeapObjectIterator Class Reference
#include <read-only-heap.h>
Public Member Functions
ReadOnlyHeapObjectIterator (const ReadOnlyHeap *ro_heap)
ReadOnlyHeapObjectIterator (const ReadOnlySpace *ro_space)
Tagged< HeapObject > Next ()
Private Attributes
const ReadOnlySpace *const ro_space_
std::vector< ReadOnlyPageMetadata * >::const_iterator current_page_
ReadOnlyPageObjectIterator page_iterator_
Detailed Description
Definition at line 162 of file read-only-heap.h.
Constructor & Destructor Documentation
ReadOnlyHeapObjectIterator() [1/2]
v8::internal::ReadOnlyHeapObjectIterator::ReadOnlyHeapObjectIterator (const ReadOnlyHeap * ro_heap) [explicit]
Definition at line 225 of file read-only-heap.cc.
    : ReadOnlyHeapObjectIterator(ro_heap->read_only_space()) {}
ReadOnlyHeapObjectIterator() [2/2]
v8::internal::ReadOnlyHeapObjectIterator::ReadOnlyHeapObjectIterator (const ReadOnlySpace * ro_space) [explicit]
Definition at line 229 of file read-only-heap.cc.
    : ro_space_(ro_space),
      current_page_(ro_space->pages().begin()),
      page_iterator_(
          current_page_ == ro_space->pages().end() ? nullptr : *current_page_) {
}
Member Function Documentation
Next()
Tagged< HeapObject > v8::internal::ReadOnlyHeapObjectIterator::Next ()
Definition at line 237 of file read-only-heap.cc.
                                                    {
  while (current_page_ != ro_space_->pages().end()) {
    Tagged<HeapObject> obj = page_iterator_.Next();
    if (!obj.is_null()) return obj;
    ++current_page_;
    if (current_page_ == ro_space_->pages().end()) return Tagged<HeapObject>();
    page_iterator_.Reset(*current_page_);
  }
  DCHECK_EQ(current_page_, ro_space_->pages().end());
  return Tagged<HeapObject>();
}
References current_page_, DCHECK_EQ, v8::internal::Tagged< HeapObject >::is_null(), v8::internal::ReadOnlyPageObjectIterator::Next(), page_iterator_, v8::internal::ReadOnlySpace::pages(), v8::internal::ReadOnlyPageObjectIterator::Reset(), ro_space_, and v8::internal::Tagged< HeapObject >.
Referenced by v8::internal::CombinedHeapObjectIterator::Next(), v8::internal::ReadOnlyDeserializer::PostProcessNewObjects(), and v8::internal::ReadOnlySerializer::Serialize().
Member Data Documentation
current_page_
std::vector<ReadOnlyPageMetadata*>::const_iterator v8::internal::ReadOnlyHeapObjectIterator::current_page_ [private]
Definition at line 171 of file read-only-heap.h.
Referenced by Next().
page_iterator_
ReadOnlyPageObjectIterator v8::internal::ReadOnlyHeapObjectIterator::page_iterator_ [private]
Definition at line 172 of file read-only-heap.h.
Referenced by Next().
ro_space_
const ReadOnlySpace* const v8::internal::ReadOnlyHeapObjectIterator::ro_space_ [private]
Definition at line 170 of file read-only-heap.h.
Referenced by Next().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/read-only-heap.h
/mnt/V8SourceCode/src/heap/read-only-heap.cc