v8::internal::AllocationSite::BodyDescriptor Class Reference
#include <objects-body-descriptors-inl.h>
Static Public Member Functions
template<typename ObjectVisitor >
static void IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor *v)
static int SizeOf (Tagged< Map > map, Tagged< HeapObject > object)
Static Public Attributes
static constexpr int kCommonPointerFieldsStart = sizeof(HeapObjectLayout)
static constexpr int kCommonPointerFieldsEnd
Additional Inherited Members
Detailed Description
Definition at line 527 of file objects-body-descriptors-inl.h.
Member Function Documentation
IterateBody()
template<typename ObjectVisitor >
static void v8::internal::AllocationSite::BodyDescriptor::IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor * v) [inline], [static]
Definition at line 542 of file objects-body-descriptors-inl.h.
                                                                    {
    // Iterate over all the common pointer fields
    IteratePointers(obj, kCommonPointerFieldsStart, kCommonPointerFieldsEnd, v);
    // Skip PretenureDataOffset and PretenureCreateCount which are Int32 fields.
    // Visit weak_next only if it has weak_next field.
    if (object_size == sizeof(AllocationSiteWithWeakNext)) {
      IterateCustomWeakPointers(
          obj, offsetof(AllocationSiteWithWeakNext, weak_next_),
          sizeof(AllocationSiteWithWeakNext), v);
    }
  }
References v8::internal::BodyDescriptorBase::IterateCustomWeakPointers(), v8::internal::BodyDescriptorBase::IteratePointers(), kCommonPointerFieldsEnd, and kCommonPointerFieldsStart.
SizeOf()
static int v8::internal::AllocationSite::BodyDescriptor::SizeOf (Tagged< Map > map, Tagged< HeapObject > object) [inline], [static]
Definition at line 555 of file objects-body-descriptors-inl.h.
                                                                       {
    return map->instance_size();
  }
References v8::internal::HeapObjectLayout::map().
Member Data Documentation
kCommonPointerFieldsEnd
constexpr int v8::internal::AllocationSite::BodyDescriptor::kCommonPointerFieldsEnd [static], [constexpr]
Initial value:
=
      offsetof(AllocationSite, dependent_code_) + kTaggedSize
Definition at line 530 of file objects-body-descriptors-inl.h.
Referenced by IterateBody().
kCommonPointerFieldsStart
constexpr int v8::internal::AllocationSite::BodyDescriptor::kCommonPointerFieldsStart = sizeof(HeapObjectLayout) [static], [constexpr]
Definition at line 529 of file objects-body-descriptors-inl.h.
Referenced by IterateBody().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/objects-body-descriptors-inl.h