v8::internal::compiler::VariableTracker::Scope Class Reference
Public Member Functions
Scope (VariableTracker *tracker, Node *node, Reduction *reduction)
~Scope ()
Maybe< Node * > Get (Variable var)
void Set (Variable var, Node *node)
Private Attributes
VariableTracker * states_
State current_state_
Additional Inherited Members
Detailed Description
Definition at line 131 of file escape-analysis.cc.
Constructor & Destructor Documentation
Scope()
v8::internal::compiler::VariableTracker::Scope::Scope (VariableTracker * tracker, Node * node, Reduction * reduction)
Definition at line 411 of file escape-analysis.cc.
    : ReduceScope(node, reduction),
      states_(states),
      current_state_(states->zone_) {
  switch (node->opcode()) {
    case IrOpcode::kEffectPhi:
      current_state_ = states_->MergeInputs(node);
      break;
    default:
      int effect_inputs = node->op()->EffectInputCount();
      if (effect_inputs == 1) {
        current_state_ =
            states_->table_.Get(NodeProperties::GetEffectInput(node, 0));
      } else {
        DCHECK_EQ(0, effect_inputs);
      }
  }
}
References current_state_, DCHECK_EQ, v8::internal::compiler::Operator::EffectInputCount(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::VariableTracker::MergeInputs(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), states_, and v8::internal::compiler::VariableTracker::table_.
 Scope()
v8::internal::compiler::VariableTracker::Scope::~Scope ()
Definition at line 431 of file escape-analysis.cc.
                             {
  if (!reduction()->effect_changed() &&
      states_->table_.Get(current_node()) != current_state_) {
    reduction()->set_effect_changed();
  }
  states_->table_.Set(current_node(), current_state_);
}
Member Function Documentation
Get()
Maybe<Node*> v8::internal::compiler::VariableTracker::Scope::Get (Variable var) [inline]
Definition at line 135 of file escape-analysis.cc.
                                   {
      Node* node = current_state_.Get(var);
      if (node && node->opcode() == IrOpcode::kDead) {
        // TODO(turbofan): We use {Dead} as a sentinel for uninitialized memory.
        // Reading uninitialized memory can only happen in unreachable code. In
        // this case, we have to mark the object as escaping to avoid dead nodes
        // in the graph. This is a workaround that should be removed once we can
        // handle dead nodes everywhere.
        return Nothing<Node*>();
      }
      return Just(node);
    }
References v8::Just(), and v8::internal::compiler::Node::opcode().
Referenced by v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::anonymous_namespace{escape-analysis.cc}::CheckMapsHelper(), and v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode().
Set()
void v8::internal::compiler::VariableTracker::Scope::Set (Variable var, Node * node) [inline]
Definition at line 147 of file escape-analysis.cc.
{ current_state_.Set(var, node); }
Referenced by v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode().
Member Data Documentation
current_state_
State v8::internal::compiler::VariableTracker::Scope::current_state_ [private]
Definition at line 151 of file escape-analysis.cc.
Referenced by Scope().
states_
VariableTracker* v8::internal::compiler::VariableTracker::Scope::states_ [private]
Definition at line 150 of file escape-analysis.cc.
Referenced by Scope().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/escape-analysis.cc