v8::internal::compiler::SpeculativeBigIntAsNParameters Class Reference
#include <simplified-operator.h>
Public Member Functions
SpeculativeBigIntAsNParameters (int bits, const FeedbackSource &feedback)
int bits () const
const FeedbackSource & feedback () const
Private Attributes
int bits_
FeedbackSource feedback_
Detailed Description
Definition at line 657 of file simplified-operator.h.
Constructor & Destructor Documentation
SpeculativeBigIntAsNParameters()
v8::internal::compiler::SpeculativeBigIntAsNParameters::SpeculativeBigIntAsNParameters (int bits, const FeedbackSource & feedback) [inline]
Definition at line 659 of file simplified-operator.h.
      : bits_(bits), feedback_(feedback) {
    DCHECK_GE(bits_, 0);
    DCHECK_LE(bits_, 64);
  }
References DCHECK_GE, and DCHECK_LE.
Member Function Documentation
bits()
int v8::internal::compiler::SpeculativeBigIntAsNParameters::bits () const [inline]
Definition at line 665 of file simplified-operator.h.
{ return bits_; }
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), and v8::internal::compiler::operator==().
feedback()
const FeedbackSource& v8::internal::compiler::SpeculativeBigIntAsNParameters::feedback () const [inline]
Definition at line 666 of file simplified-operator.h.
{ return feedback_; }
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), and v8::internal::compiler::operator==().
Member Data Documentation
bits_
int v8::internal::compiler::SpeculativeBigIntAsNParameters::bits_ [private]
Definition at line 669 of file simplified-operator.h.
feedback_
FeedbackSource v8::internal::compiler::SpeculativeBigIntAsNParameters::feedback_ [private]
Definition at line 670 of file simplified-operator.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/simplified-operator.h