v8::internal::wasm::ContType Class Reference
#include <struct-types.h>
Public Member Functions
constexpr ContType (ModuleTypeIndex idx)
bool operator== (const ContType &other) const
ModuleTypeIndex contfun_typeindex () const
Private Attributes
ModuleTypeIndex index_
Detailed Description
Definition at line 356 of file struct-types.h.
Constructor & Destructor Documentation
ContType()
constexpr v8::internal::wasm::ContType::ContType (ModuleTypeIndex idx) [inline], [explicit], [constexpr]
Definition at line 358 of file struct-types.h.
: index_(idx) {}
Member Function Documentation
contfun_typeindex()
ModuleTypeIndex v8::internal::wasm::ContType::contfun_typeindex () const [inline]
Definition at line 364 of file struct-types.h.
{ return index_; }
References index_.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), v8::internal::wasm::ModuleDecoderImpl::FinalizeRecgroup(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::ValidContinuationSubtypeDefinition(), and v8::internal::wasm::WasmModuleBuilder::WriteTo().
operator==()
bool v8::internal::wasm::ContType::operator== (const ContType & other) const [inline]
Definition at line 360 of file struct-types.h.
                                               {
    return index_ == other.index_;
  }
References index_.
Member Data Documentation
index_
ModuleTypeIndex v8::internal::wasm::ContType::index_ [private]
Definition at line 368 of file struct-types.h.
Referenced by contfun_typeindex(), and operator==().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/struct-types.h