v8::internal::compiler::Typer::Visitor Class Reference
Public Member Functions
Visitor (Typer *typer, LoopVariableOptimizer *induction_vars)
const char * reducer_name () const override
Reduction Reduce (Node *node) override
Type TypeNode (Node *node)
Type TypeConstant (Handle< Object > value)
bool InductionVariablePhiTypeIsPrefixedPoint (InductionVariable *induction_var)
Private Types
enum ComparisonOutcomeFlags { kComparisonTrue = 1
, kComparisonFalse = 2
, kComparisonUndefined = 4
 }
using UnaryTyperFun = Type(*)(Type, Typer *t)
using BinaryTyperFun = Type(*)(Type, Type, Typer *t)
using ComparisonOutcome = base::Flags< ComparisonOutcomeFlags >
Private Member Functions
Type TypeOrNone (Node *node)
Type Operand (Node *node, int i)
Type Weaken (Node *node, Type current_type, Type previous_type)
Zone * zone ()
TFGraph * graph ()
JSHeapBroker * broker ()
void SetWeakened (NodeId node_id)
bool IsWeakened (NodeId node_id)
Type TypeUnaryOp (Node *node, UnaryTyperFun)
Type TypeBinaryOp (Node *node, BinaryTyperFun)
Type TypeUnaryOp (Type input, UnaryTyperFun)
Type TypeBinaryOp (Type left, Type right, BinaryTyperFun)
Reduction UpdateType (Node *node, Type current)
Static Private Member Functions
static Type BinaryNumberOpTyper (Type lhs, Type rhs, Typer *t, BinaryTyperFun f)
static ComparisonOutcome Invert (ComparisonOutcome, Typer *)
static Type FalsifyUndefined (ComparisonOutcome, Typer *)
static Type BitwiseNot (Type, Typer *)
static Type Decrement (Type, Typer *)
static Type Increment (Type, Typer *)
static Type Negate (Type, Typer *)
static Type ToPrimitive (Type, Typer *)
static Type ToBoolean (Type, Typer *)
static Type ToInteger (Type, Typer *)
static Type ToLength (Type, Typer *)
static Type ToName (Type, Typer *)
static Type ToNumber (Type, Typer *)
static Type ToNumberConvertBigInt (Type, Typer *)
static Type ToBigInt (Type, Typer *)
static Type ToBigIntConvertNumber (Type, Typer *)
static Type ToNumeric (Type, Typer *)
static Type ToObject (Type, Typer *)
static Type ToString (Type, Typer *)
static Type ObjectIsArrayBufferView (Type, Typer *)
static Type ObjectIsBigInt (Type, Typer *)
static Type ObjectIsCallable (Type, Typer *)
static Type ObjectIsConstructor (Type, Typer *)
static Type ObjectIsDetectableCallable (Type, Typer *)
static Type ObjectIsMinusZero (Type, Typer *)
static Type NumberIsMinusZero (Type, Typer *)
static Type ObjectIsNaN (Type, Typer *)
static Type NumberIsNaN (Type, Typer *)
static Type ObjectIsNonCallable (Type, Typer *)
static Type ObjectIsNumber (Type, Typer *)
static Type ObjectIsReceiver (Type, Typer *)
static Type ObjectIsSmi (Type, Typer *)
static Type ObjectIsString (Type, Typer *)
static Type ObjectIsSymbol (Type, Typer *)
static Type ObjectIsUndetectable (Type, Typer *)
static ComparisonOutcome JSCompareTyper (Type, Type, Typer *)
static ComparisonOutcome NumberCompareTyper (Type, Type, Typer *)
static Type JSCallTyper (Type, Typer *)
static Type NumberEqualTyper (Type, Type, Typer *)
static Type NumberLessThanTyper (Type, Type, Typer *)
static Type NumberLessThanOrEqualTyper (Type, Type, Typer *)
static Type BigIntCompareTyper (Type, Type, Typer *)
static Type ReferenceEqualTyper (Type, Type, Typer *)
static Type SameValueTyper (Type, Type, Typer *)
static Type SameValueNumbersOnlyTyper (Type, Type, Typer *)
static Type StringFromSingleCharCodeTyper (Type, Typer *)
static Type StringFromSingleCodePointTyper (Type, Typer *)
Private Attributes
Typer * typer_
LoopVariableOptimizer * induction_vars_
ZoneSet< NodeId > weakened_nodes_
Additional Inherited Members
Detailed Description
Definition at line 56 of file turbofan-typer.cc.
Member Typedef Documentation
BinaryTyperFun
using v8::internal::compiler::Typer::Visitor::BinaryTyperFun = Type (*)(Type, Type, Typer* t) [private]
Definition at line 320 of file turbofan-typer.cc.
ComparisonOutcome
using v8::internal::compiler::Typer::Visitor::ComparisonOutcome = base::Flags<ComparisonOutcomeFlags> [private]
Definition at line 335 of file turbofan-typer.cc.
UnaryTyperFun
using v8::internal::compiler::Typer::Visitor::UnaryTyperFun = Type (*)(Type, Typer* t) [private]
Definition at line 319 of file turbofan-typer.cc.
Member Enumeration Documentation
ComparisonOutcomeFlags
enum v8::internal::compiler::Typer::Visitor::ComparisonOutcomeFlags [private]
Enumerator
kComparisonTrue
kComparisonFalse
kComparisonUndefined
Definition at line 330 of file turbofan-typer.cc.
                              {
    kComparisonTrue = 1,
    kComparisonFalse = 2,
    kComparisonUndefined = 4
  };
Constructor & Destructor Documentation
Visitor()
v8::internal::compiler::Typer::Visitor::Visitor (Typer * typer, LoopVariableOptimizer * induction_vars) [inline], [explicit]
Definition at line 58 of file turbofan-typer.cc.
      : typer_(typer),
        induction_vars_(induction_vars),
        weakened_nodes_(typer->zone()) {}
Member Function Documentation
BigIntCompareTyper()
Type v8::internal::compiler::Typer::Visitor::BigIntCompareTyper (Type lhs, Type rhs, Typer * t) [static], [private]
Definition at line 2279 of file turbofan-typer.cc.
                                                                  {
  if (lhs.IsNone() || rhs.IsNone()) {
    return Type::None();
  }
  return Type::Boolean();
}
References v8::internal::compiler::Type::IsNone(), and v8::internal::compiler::turboshaft::Type::None().
BinaryNumberOpTyper()
Type v8::internal::compiler::Typer::Visitor::BinaryNumberOpTyper (Type lhs, Type rhs, Typer * t, BinaryTyperFun f) [static], [private]
Definition at line 537 of file turbofan-typer.cc.
                                                           {
  lhs = ToNumeric(lhs, t);
  rhs = ToNumeric(rhs, t);
  if (lhs.IsNone() || rhs.IsNone()) return Type::None();
  bool lhs_is_number = lhs.Is(Type::Number());
  bool rhs_is_number = rhs.Is(Type::Number());
  if (lhs_is_number && rhs_is_number) {
    return f(lhs, rhs, t);
  }
  // In order to maintain monotonicity, the following two conditions are
  // intentionally asymmetric.
  if (lhs_is_number) {
    return Type::Number();
  }
  if (lhs.Is(Type::BigInt())) {
    return Type::BigInt();
  }
  return Type::Numeric();
}
References v8::internal::compiler::Type::Is(), v8::internal::compiler::Type::IsNone(), and v8::internal::compiler::turboshaft::Type::None().
BitwiseNot()
Type v8::internal::compiler::Typer::Visitor::BitwiseNot (Type type, Typer * t) [static], [private]
Definition at line 579 of file turbofan-typer.cc.
                                                 {
  type = ToNumeric(type, t);
  if (type.Is(Type::Number())) {
    return NumberBitwiseXor(type, t->cache_->kSingletonMinusOne, t);
  }
  if (type.Is(Type::BigInt())) {
    return Type::BigInt();
  }
  return Type::Numeric();
}
References v8::internal::compiler::Typer::cache_, v8::internal::compiler::TypeCache::kSingletonMinusOne, and v8::internal::tracing::type.
broker()
JSHeapBroker* v8::internal::compiler::Typer::Visitor::broker () [inline], [private]
Definition at line 312 of file turbofan-typer.cc.
{ return typer_->broker(); }
References v8::internal::compiler::Typer::broker(), and typer_.
Decrement()
Type v8::internal::compiler::Typer::Visitor::Decrement (Type type, Typer * t) [static], [private]
Definition at line 590 of file turbofan-typer.cc.
                                                {
  type = ToNumeric(type, t);
  if (type.Is(Type::Number())) {
    return NumberSubtract(type, t->cache_->kSingletonOne, t);
  }
  if (type.Is(Type::BigInt())) {
    return Type::BigInt();
  }
  return Type::Numeric();
}
References v8::internal::compiler::Typer::cache_, v8::internal::compiler::TypeCache::kSingletonOne, and v8::internal::tracing::type.
FalsifyUndefined()
Type v8::internal::compiler::Typer::Visitor::FalsifyUndefined (ComparisonOutcome outcome, Typer * t) [static], [private]
Definition at line 568 of file turbofan-typer.cc.
                                                                       {
  if (outcome == 0) return Type::None();
  if ((outcome & kComparisonFalse) != 0 ||
      (outcome & kComparisonUndefined) != 0) {
    return (outcome & kComparisonTrue) != 0 ? Type::Boolean()
                                            : t->singleton_false_;
  }
  DCHECK_NE(0, outcome & kComparisonTrue);
  return t->singleton_true_;
}
References DCHECK_NE, v8::internal::compiler::turboshaft::Type::None(), v8::internal::compiler::Typer::singleton_false_, and v8::internal::compiler::Typer::singleton_true_.
graph()
TFGraph* v8::internal::compiler::Typer::Visitor::graph () [inline], [private]
Definition at line 311 of file turbofan-typer.cc.
{ return typer_->graph(); }
References v8::internal::compiler::Typer::graph(), and typer_.
Increment()
Type v8::internal::compiler::Typer::Visitor::Increment (Type type, Typer * t) [static], [private]
Definition at line 601 of file turbofan-typer.cc.
                                                {
  type = ToNumeric(type, t);
  if (type.Is(Type::Number())) {
    return NumberAdd(type, t->cache_->kSingletonOne, t);
  }
  if (type.Is(Type::BigInt())) {
    return Type::BigInt();
  }
  return Type::Numeric();
}
References v8::internal::compiler::Typer::cache_, v8::internal::compiler::TypeCache::kSingletonOne, and v8::internal::tracing::type.
InductionVariablePhiTypeIsPrefixedPoint()
bool v8::internal::compiler::Typer::Visitor::InductionVariablePhiTypeIsPrefixedPoint (InductionVariable * induction_var)
Definition at line 1057 of file turbofan-typer.cc.
                                      {
  Node* node = induction_var->phi();
  DCHECK_EQ(node->opcode(), IrOpcode::kInductionVariablePhi);
  Node* arith = node->InputAt(1);
  Type type = NodeProperties::GetType(node);
  Type initial_type = Operand(node, 0);
  Type arith_type = Operand(node, 1);
  Type increment_type = Operand(node, 2);
  // Intersect {type} with useful bounds.
  for (auto bound : induction_var->upper_bounds()) {
    Type bound_type = TypeOrNone(bound.bound);
    if (!bound_type.Is(typer_->cache_->kInteger)) continue;
    if (!bound_type.IsNone()) {
      bound_type = Type::Range(
          -V8_INFINITY,
          bound_type.Max() - (bound.kind == InductionVariable::kStrict),
          zone());
    }
    type = Type::Intersect(type, bound_type, typer_->zone());
  }
  for (auto bound : induction_var->lower_bounds()) {
    Type bound_type = TypeOrNone(bound.bound);
    if (!bound_type.Is(typer_->cache_->kInteger)) continue;
    if (!bound_type.IsNone()) {
      bound_type = Type::Range(
          bound_type.Min() + (bound.kind == InductionVariable::kStrict),
          +V8_INFINITY, typer_->zone());
    }
    type = Type::Intersect(type, bound_type, typer_->zone());
  }
  if (arith_type.IsNone()) {
    type = Type::None();
  } else {
    // We support a few additional type conversions on the lhs of the arithmetic
    // operation. This needs to be kept in sync with the corresponding code in
    // {LoopVariableOptimizer::TryGetInductionVariable}.
    Node* arith_input = arith->InputAt(0);
    switch (arith_input->opcode()) {
      case IrOpcode::kSpeculativeToNumber:
        type = typer_->operation_typer_.SpeculativeToNumber(type);
        break;
      case IrOpcode::kJSToNumber:
        type = typer_->operation_typer_.ToNumber(type);
        break;
      case IrOpcode::kJSToNumberConvertBigInt:
        type = typer_->operation_typer_.ToNumberConvertBigInt(type);
        break;
      default:
        break;
    }
    // Apply ordinary typing to the "increment" operation.
    // clang-format off
    switch (arith->opcode()) {
#define CASE(x) \
      case IrOpcode::k##x: \
        type = Type##x(type, increment_type); \
        break;
      CASE(JSAdd)
      CASE(JSSubtract)
      CASE(NumberAdd)
      CASE(NumberSubtract)
      CASE(SpeculativeNumberAdd)
      CASE(SpeculativeNumberSubtract)
      CASE(SpeculativeAdditiveSafeIntegerAdd)
      CASE(SpeculativeAdditiveSafeIntegerSubtract)
      CASE(SpeculativeSmallIntegerAdd)
      CASE(SpeculativeSmallIntegerSubtract)
#undef CASE
      default:
        UNREACHABLE();
    }
    // clang-format on
  }
  type = Type::Union(initial_type, type, typer_->zone());
  return type.Is(NodeProperties::GetType(node));
}
References v8::internal::compiler::Typer::cache_, CASE, DCHECK_EQ, v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Type::Intersect(), v8::internal::compiler::Type::Is(), v8::internal::compiler::Type::IsNone(), v8::internal::compiler::TypeCache::kInteger, v8::internal::compiler::InductionVariable::kStrict, v8::internal::compiler::InductionVariable::lower_bounds(), v8::internal::compiler::Type::Max(), v8::internal::compiler::Type::Min(), v8::internal::compiler::turboshaft::Type::None(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::Typer::operation_typer_, v8::internal::compiler::InductionVariable::phi(), v8::internal::compiler::Type::Range(), v8::internal::compiler::OperationTyper::ToNumber(), v8::internal::compiler::OperationTyper::ToNumberConvertBigInt(), v8::internal::tracing::type, v8::internal::compiler::Type::Union(), v8::internal::UNREACHABLE(), v8::internal::compiler::InductionVariable::upper_bounds(), V8_INFINITY, and v8::internal::compiler::Typer::zone().
Invert()
Typer::Visitor::ComparisonOutcome v8::internal::compiler::Typer::Visitor::Invert (ComparisonOutcome outcome, Typer * t) [static], [private]
Definition at line 559 of file turbofan-typer.cc.
                                         {
  ComparisonOutcome result(0);
  if ((outcome & kComparisonUndefined) != 0) result |= kComparisonUndefined;
  if ((outcome & kComparisonTrue) != 0) result |= kComparisonFalse;
  if ((outcome & kComparisonFalse) != 0) result |= kComparisonTrue;
  return result;
}
References v8::base::internal::result.
IsWeakened()
bool v8::internal::compiler::Typer::Visitor::IsWeakened (NodeId node_id) [inline], [private]
Definition at line 315 of file turbofan-typer.cc.
                                  {
    return weakened_nodes_.find(node_id) != weakened_nodes_.end();
  }
References weakened_nodes_.
JSCallTyper()
Type v8::internal::compiler::Typer::Visitor::JSCallTyper (Type fun, Typer * t) [static], [private]
Definition at line 1844 of file turbofan-typer.cc.
                                                 {
  if (!fun.IsHeapConstant() || !fun.AsHeapConstant()->Ref().IsJSFunction()) {
    return Type::NonInternal();
  }
  JSFunctionRef function = fun.AsHeapConstant()->Ref().AsJSFunction();
  if (!function.shared(t->broker()).HasBuiltinId()) {
    return Type::NonInternal();
  }
  switch (function.shared(t->broker()).builtin_id()) {
    case Builtin::kMathRandom:
      return Type::PlainNumber();
    case Builtin::kMathFloor:
    case Builtin::kMathCeil:
    case Builtin::kMathRound:
    case Builtin::kMathTrunc:
      return t->cache_->kIntegerOrMinusZeroOrNaN;
    // Unary math functions.
    case Builtin::kMathAbs:
    case Builtin::kMathExp:
      return Type::Union(Type::PlainNumber(), Type::NaN(), t->zone());
    case Builtin::kMathAcos:
    case Builtin::kMathAcosh:
    case Builtin::kMathAsin:
    case Builtin::kMathAsinh:
    case Builtin::kMathAtan:
    case Builtin::kMathAtanh:
    case Builtin::kMathCbrt:
    case Builtin::kMathCos:
    case Builtin::kMathExpm1:
    case Builtin::kMathFround:
    case Builtin::kMathLog:
    case Builtin::kMathLog1p:
    case Builtin::kMathLog10:
    case Builtin::kMathLog2:
    case Builtin::kMathSin:
    case Builtin::kMathSqrt:
    case Builtin::kMathTan:
      return Type::Number();
    case Builtin::kMathSign:
      return t->cache_->kMinusOneToOneOrMinusZeroOrNaN;
    // Binary math functions.
    case Builtin::kMathAtan2:
    case Builtin::kMathPow:
    case Builtin::kMathMax:
    case Builtin::kMathMin:
    case Builtin::kMathHypot:
      return Type::Number();
    case Builtin::kMathImul:
      return Type::Signed32();
    case Builtin::kMathClz32:
      return t->cache_->kZeroToThirtyTwo;
    // Date functions.
    case Builtin::kDateNow:
      return t->cache_->kTimeValueType;
    case Builtin::kDatePrototypeGetDate:
      return t->cache_->kJSDateDayType;
    case Builtin::kDatePrototypeGetDay:
      return t->cache_->kJSDateWeekdayType;
    case Builtin::kDatePrototypeGetFullYear:
      return t->cache_->kJSDateYearType;
    case Builtin::kDatePrototypeGetHours:
      return t->cache_->kJSDateHourType;
    case Builtin::kDatePrototypeGetMilliseconds:
      return Type::Union(Type::Range(0.0, 999.0, t->zone()), Type::NaN(),
                         t->zone());
    case Builtin::kDatePrototypeGetMinutes:
      return t->cache_->kJSDateMinuteType;
    case Builtin::kDatePrototypeGetMonth:
      return t->cache_->kJSDateMonthType;
    case Builtin::kDatePrototypeGetSeconds:
      return t->cache_->kJSDateSecondType;
    case Builtin::kDatePrototypeGetTime:
      return t->cache_->kJSDateValueType;
    // Symbol functions.
    case Builtin::kSymbolConstructor:
      return Type::Symbol();
    case Builtin::kSymbolPrototypeToString:
      return Type::String();
    case Builtin::kSymbolPrototypeValueOf:
      return Type::Symbol();
    // BigInt functions.
    case Builtin::kBigIntConstructor:
      return Type::BigInt();
    // Number functions.
    case Builtin::kNumberConstructor:
      return Type::Number();
    case Builtin::kNumberIsFinite:
    case Builtin::kNumberIsInteger:
    case Builtin::kNumberIsNaN:
    case Builtin::kNumberIsSafeInteger:
      return Type::Boolean();
    case Builtin::kNumberParseFloat:
      return Type::Number();
    case Builtin::kNumberParseInt:
      return t->cache_->kIntegerOrMinusZeroOrNaN;
    case Builtin::kNumberToString:
      return Type::String();
    // String functions.
    case Builtin::kStringConstructor:
      return Type::String();
    case Builtin::kStringPrototypeCharCodeAt:
      return Type::Union(Type::Range(0, kMaxUInt16, t->zone()), Type::NaN(),
                         t->zone());
    case Builtin::kStringCharAt:
      return Type::String();
    case Builtin::kStringPrototypeCodePointAt:
      return Type::Union(Type::Range(0.0, String::kMaxCodePoint, t->zone()),
                         Type::Undefined(), t->zone());
    case Builtin::kStringPrototypeConcat:
    case Builtin::kStringFromCharCode:
    case Builtin::kStringFromCodePoint:
      return Type::String();
    case Builtin::kStringPrototypeIndexOf:
    case Builtin::kStringPrototypeLastIndexOf:
      return Type::Range(-1.0, String::kMaxLength, t->zone());
    case Builtin::kStringPrototypeEndsWith:
    case Builtin::kStringPrototypeIncludes:
      return Type::Boolean();
    case Builtin::kStringRaw:
    case Builtin::kStringRepeat:
    case Builtin::kStringPrototypeSlice:
      return Type::String();
    case Builtin::kStringPrototypeStartsWith:
      return Type::Boolean();
    case Builtin::kStringPrototypeSubstr:
    case Builtin::kStringSubstring:
    case Builtin::kStringPrototypeToString:
#ifdef V8_INTL_SUPPORT
    case Builtin::kStringPrototypeToLowerCaseIntl:
    case Builtin::kStringPrototypeToUpperCaseIntl:
#else
    case Builtin::kStringPrototypeToLowerCase:
    case Builtin::kStringPrototypeToUpperCase:
#endif
    case Builtin::kStringPrototypeTrim:
    case Builtin::kStringPrototypeTrimEnd:
    case Builtin::kStringPrototypeTrimStart:
    case Builtin::kStringPrototypeValueOf:
      return Type::String();
    case Builtin::kStringPrototypeIterator:
    case Builtin::kStringIteratorPrototypeNext:
      return Type::OtherObject();
    case Builtin::kArrayPrototypeEntries:
    case Builtin::kArrayPrototypeKeys:
    case Builtin::kArrayPrototypeValues:
    case Builtin::kTypedArrayPrototypeEntries:
    case Builtin::kTypedArrayPrototypeKeys:
    case Builtin::kTypedArrayPrototypeValues:
    case Builtin::kArrayIteratorPrototypeNext:
    case Builtin::kMapIteratorPrototypeNext:
    case Builtin::kSetIteratorPrototypeNext:
      return Type::OtherObject();
    case Builtin::kTypedArrayPrototypeToStringTag:
      return Type::Union(Type::InternalizedString(), Type::Undefined(),
                         t->zone());
    // Array functions.
    case Builtin::kArrayIsArray:
      return Type::Boolean();
    case Builtin::kArrayConcat:
      return Type::Receiver();
    case Builtin::kArrayEvery:
      return Type::Boolean();
    case Builtin::kArrayPrototypeFill:
    case Builtin::kArrayFilter:
      return Type::Receiver();
    case Builtin::kArrayPrototypeFindIndex:
      return Type::Range(-1, kMaxSafeInteger, t->zone());
    case Builtin::kArrayForEach:
      return Type::Undefined();
    case Builtin::kArrayIncludes:
      return Type::Boolean();
    case Builtin::kArrayIndexOf:
      return Type::Range(-1, kMaxSafeInteger, t->zone());
    case Builtin::kArrayPrototypeJoin:
      return Type::String();
    case Builtin::kArrayPrototypeLastIndexOf:
      return Type::Range(-1, kMaxSafeInteger, t->zone());
    case Builtin::kArrayMap:
      return Type::Receiver();
    case Builtin::kArrayPush:
      return t->cache_->kPositiveSafeInteger;
    case Builtin::kArrayPrototypeReverse:
    case Builtin::kArrayPrototypeSlice:
      return Type::Receiver();
    case Builtin::kArraySome:
      return Type::Boolean();
    case Builtin::kArrayPrototypeSplice:
      return Type::Receiver();
    case Builtin::kArrayUnshift:
      return t->cache_->kPositiveSafeInteger;
    // ArrayBuffer functions.
    case Builtin::kArrayBufferIsView:
      return Type::Boolean();
    // Object functions.
    case Builtin::kObjectAssign:
      return Type::Receiver();
    case Builtin::kObjectCreate:
      return Type::OtherObject();
    case Builtin::kObjectIs:
    case Builtin::kObjectHasOwn:
    case Builtin::kObjectPrototypeHasOwnProperty:
    case Builtin::kObjectPrototypeIsPrototypeOf:
      return Type::Boolean();
    case Builtin::kObjectToString:
      return Type::String();
    case Builtin::kPromiseAll:
      return Type::Receiver();
    case Builtin::kPromisePrototypeThen:
      return Type::Receiver();
    case Builtin::kPromiseRace:
      return Type::Receiver();
    case Builtin::kPromiseReject:
      return Type::Receiver();
    case Builtin::kPromiseResolveTrampoline:
      return Type::Receiver();
    // RegExp functions.
    case Builtin::kRegExpPrototypeCompile:
      return Type::OtherObject();
    case Builtin::kRegExpPrototypeExec:
      return Type::Union(Type::Array(), Type::Null(), t->zone());
    case Builtin::kRegExpPrototypeTest:
      return Type::Boolean();
    case Builtin::kRegExpPrototypeToString:
      return Type::String();
    // Function functions.
    case Builtin::kFunctionPrototypeBind:
      return Type::BoundFunction();
    case Builtin::kFunctionPrototypeHasInstance:
      return Type::Boolean();
    // Global functions.
    case Builtin::kGlobalDecodeURI:
    case Builtin::kGlobalDecodeURIComponent:
    case Builtin::kGlobalEncodeURI:
    case Builtin::kGlobalEncodeURIComponent:
    case Builtin::kGlobalEscape:
    case Builtin::kGlobalUnescape:
      return Type::String();
    case Builtin::kGlobalIsFinite:
    case Builtin::kGlobalIsNaN:
      return Type::Boolean();
    // Map functions.
    case Builtin::kMapPrototypeClear:
    case Builtin::kMapPrototypeForEach:
      return Type::Undefined();
    case Builtin::kMapPrototypeDelete:
    case Builtin::kMapPrototypeHas:
      return Type::Boolean();
    case Builtin::kMapPrototypeEntries:
    case Builtin::kMapPrototypeKeys:
    case Builtin::kMapPrototypeSet:
    case Builtin::kMapPrototypeValues:
      return Type::OtherObject();
    // Set functions.
    case Builtin::kSetPrototypeAdd:
    case Builtin::kSetPrototypeEntries:
    case Builtin::kSetPrototypeValues:
      return Type::OtherObject();
    case Builtin::kSetPrototypeClear:
    case Builtin::kSetPrototypeForEach:
      return Type::Undefined();
    case Builtin::kSetPrototypeDelete:
    case Builtin::kSetPrototypeHas:
      return Type::Boolean();
    // WeakMap functions.
    case Builtin::kWeakMapPrototypeDelete:
    case Builtin::kWeakMapPrototypeHas:
      return Type::Boolean();
    case Builtin::kWeakMapPrototypeSet:
      return Type::OtherObject();
    // WeakSet functions.
    case Builtin::kWeakSetPrototypeAdd:
      return Type::OtherObject();
    case Builtin::kWeakSetPrototypeDelete:
    case Builtin::kWeakSetPrototypeHas:
      return Type::Boolean();
    default:
      return Type::NonInternal();
  }
}
References v8::internal::compiler::Type::AsHeapConstant(), v8::internal::compiler::Typer::broker(), v8::internal::compiler::Typer::cache_, v8::internal::compiler::Type::IsHeapConstant(), v8::internal::compiler::TypeCache::kIntegerOrMinusZeroOrNaN, v8::internal::compiler::TypeCache::kJSDateDayType, v8::internal::compiler::TypeCache::kJSDateHourType, v8::internal::compiler::TypeCache::kJSDateMinuteType, v8::internal::compiler::TypeCache::kJSDateMonthType, v8::internal::compiler::TypeCache::kJSDateSecondType, v8::internal::compiler::TypeCache::kJSDateValueType, v8::internal::compiler::TypeCache::kJSDateWeekdayType, v8::internal::compiler::TypeCache::kJSDateYearType, v8::internal::String::kMaxCodePoint, v8::internal::String::kMaxLength, v8::internal::kMaxSafeInteger, v8::internal::kMaxUInt16, v8::internal::compiler::TypeCache::kMinusOneToOneOrMinusZeroOrNaN, v8::internal::compiler::TypeCache::kPositiveSafeInteger, v8::internal::compiler::TypeCache::kTimeValueType, v8::internal::compiler::TypeCache::kZeroToThirtyTwo, v8::internal::compiler::Null, v8::internal::compiler::Type::Range(), v8::internal::compiler::HeapConstantType::Ref(), v8::internal::compiler::Undefined, v8::internal::compiler::Type::Union(), and v8::internal::compiler::Typer::zone().
JSCompareTyper()
Typer::Visitor::ComparisonOutcome v8::internal::compiler::Typer::Visitor::JSCompareTyper (Type lhs, Type rhs, Typer * t) [static], [private]
Definition at line 1319 of file turbofan-typer.cc.
                                                                           {
  lhs = ToPrimitive(lhs, t);
  rhs = ToPrimitive(rhs, t);
  if (lhs.Maybe(Type::String()) && rhs.Maybe(Type::String())) {
    return ComparisonOutcome(kComparisonTrue) |
           ComparisonOutcome(kComparisonFalse);
  }
  lhs = ToNumeric(lhs, t);
  rhs = ToNumeric(rhs, t);
  if (lhs.Is(Type::Number()) && rhs.Is(Type::Number())) {
    return NumberCompareTyper(lhs, rhs, t);
  }
  return ComparisonOutcome(kComparisonTrue) |
         ComparisonOutcome(kComparisonFalse) |
         ComparisonOutcome(kComparisonUndefined);
}
References v8::internal::compiler::Type::Is(), and v8::internal::compiler::Type::Maybe().
Negate()
Type v8::internal::compiler::Typer::Visitor::Negate (Type type, Typer * t) [static], [private]
Definition at line 612 of file turbofan-typer.cc.
                                             {
  type = ToNumeric(type, t);
  if (type.Is(Type::Number())) {
    return NumberMultiply(type, t->cache_->kSingletonMinusOne, t);
  }
  if (type.Is(Type::BigInt())) {
    return Type::BigInt();
  }
  return Type::Numeric();
}
References v8::internal::compiler::Typer::cache_, v8::internal::compiler::TypeCache::kSingletonMinusOne, and v8::internal::tracing::type.
NumberCompareTyper()
Typer::Visitor::ComparisonOutcome v8::internal::compiler::Typer::Visitor::NumberCompareTyper (Type lhs, Type rhs, Typer * t) [static], [private]
Definition at line 1338 of file turbofan-typer.cc.
                                                                               {
  DCHECK(lhs.Is(Type::Number()));
  DCHECK(rhs.Is(Type::Number()));
  if (lhs.IsNone() || rhs.IsNone()) return {};
  // Shortcut for NaNs.
  if (lhs.Is(Type::NaN()) || rhs.Is(Type::NaN())) return kComparisonUndefined;
  ComparisonOutcome result;
  if (lhs.IsHeapConstant() && rhs.Is(lhs)) {
    // Types are equal and are inhabited only by a single semantic value.
    result = kComparisonFalse;
  } else if (lhs.Min() >= rhs.Max()) {
    result = kComparisonFalse;
  } else if (lhs.Max() < rhs.Min()) {
    result = kComparisonTrue;
  } else {
    return ComparisonOutcome(kComparisonTrue) |
           ComparisonOutcome(kComparisonFalse) |
           ComparisonOutcome(kComparisonUndefined);
  }
  // Add the undefined if we could see NaN.
  if (lhs.Maybe(Type::NaN()) || rhs.Maybe(Type::NaN())) {
    result |= kComparisonUndefined;
  }
  return result;
}
References v8::internal::DCHECK(), v8::internal::compiler::Type::Is(), v8::internal::compiler::Type::IsHeapConstant(), v8::internal::compiler::Type::IsNone(), v8::internal::compiler::Type::Max(), v8::internal::compiler::Type::Maybe(), v8::internal::compiler::Type::Min(), and v8::base::internal::result.
NumberEqualTyper()
Type v8::internal::compiler::Typer::Visitor::NumberEqualTyper (Type lhs, Type rhs, Typer * t) [static], [private]
Definition at line 2262 of file turbofan-typer.cc.
                                                                {
  return JSEqualTyper(ToNumber(lhs, t), ToNumber(rhs, t), t);
}
References v8::internal::ToNumber().
NumberIsMinusZero()
Type v8::internal::compiler::Typer::Visitor::NumberIsMinusZero (Type type, Typer * t) [static], [private]
Definition at line 770 of file turbofan-typer.cc.
                                                        {
  CHECK(!type.IsNone());
  if (type.Is(Type::MinusZero())) return t->singleton_true_;
  if (!type.Maybe(Type::MinusZero())) return t->singleton_false_;
  return Type::Boolean();
}
References CHECK, v8::internal::compiler::Typer::singleton_false_, v8::internal::compiler::Typer::singleton_true_, and v8::internal::tracing::type.
NumberIsNaN()
Type v8::internal::compiler::Typer::Visitor::NumberIsNaN (Type type, Typer * t) [static], [private]
Definition at line 784 of file turbofan-typer.cc.
                                                  {
  CHECK(!type.IsNone());
  if (type.Is(Type::NaN())) return t->singleton_true_;
  if (!type.Maybe(Type::NaN())) return t->singleton_false_;
  return Type::Boolean();
}
References CHECK, v8::internal::compiler::Typer::singleton_false_, v8::internal::compiler::Typer::singleton_true_, and v8::internal::tracing::type.
NumberLessThanOrEqualTyper()
Type v8::internal::compiler::Typer::Visitor::NumberLessThanOrEqualTyper (Type lhs, Type rhs, Typer * t) [static], [private]
Definition at line 2273 of file turbofan-typer.cc.
                                                                          {
  return FalsifyUndefined(
      Invert(JSCompareTyper(ToNumber(rhs, t), ToNumber(lhs, t), t), t), t);
}
References v8::internal::ToNumber().
NumberLessThanTyper()
Type v8::internal::compiler::Typer::Visitor::NumberLessThanTyper (Type lhs, Type rhs, Typer * t) [static], [private]
Definition at line 2267 of file turbofan-typer.cc.
                                                                   {
  return FalsifyUndefined(
      NumberCompareTyper(ToNumber(lhs, t), ToNumber(rhs, t), t), t);
}
References v8::internal::ToNumber().
ObjectIsArrayBufferView()
Type v8::internal::compiler::Typer::Visitor::ObjectIsArrayBufferView (Type type, Typer * t) [static], [private]
Definition at line 721 of file turbofan-typer.cc.
                                                              {
  // TODO(turbofan): Introduce a Type::ArrayBufferView?
  CHECK(!type.IsNone());
  if (type.Is(Type::TypedArray())) return t->singleton_true_;
  if (!type.Maybe(Type::TypedArray()) && !type.Maybe(Type::OtherObject())) {
    return t->singleton_false_;
  }
  return Type::Boolean();
}
References CHECK, v8::internal::compiler::Typer::singleton_false_, v8::internal::compiler::Typer::singleton_true_, and v8::internal::tracing::type.
ObjectIsBigInt()
Type v8::internal::compiler::Typer::Visitor::ObjectIsBigInt (Type type, Typer * t) [static], [private]
Definition at line 731 of file turbofan-typer.cc.
                                                     {
  CHECK(!type.IsNone());
  if (type.Is(Type::BigInt())) return t->singleton_true_;
  if (!type.Maybe(Type::BigInt())) return t->singleton_false_;
  return Type::Boolean();
}
References CHECK, v8::internal::compiler::Typer::singleton_false_, v8::internal::compiler::Typer::singleton_true_, and v8::internal::tracing::type.
ObjectIsCallable()
Type v8::internal::compiler::Typer::Visitor::ObjectIsCallable (Type type, Typer * t) [static], [private]
Definition at line 738 of file turbofan-typer.cc.
                                                       {
  CHECK(!type.IsNone());
  if (type.Is(Type::Callable())) return t->singleton_true_;
  if (!type.Maybe(Type::Callable())) return t->singleton_false_;
  return Type::Boolean();
}
References CHECK, v8::internal::compiler::Typer::singleton_false_, v8::internal::compiler::Typer::singleton_true_, and v8::internal::tracing::type.
ObjectIsConstructor()
Type v8::internal::compiler::Typer::Visitor::ObjectIsConstructor (Type type, Typer * t) [static], [private]
Definition at line 745 of file turbofan-typer.cc.
                                                          {
  // TODO(turbofan): Introduce a Type::Constructor?
  CHECK(!type.IsNone());
  if (type.IsHeapConstant() &&
      type.AsHeapConstant()->Ref().map(t->broker()).is_constructor()) {
    return t->singleton_true_;
  }
  if (!type.Maybe(Type::Callable())) return t->singleton_false_;
  return Type::Boolean();
}
References v8::internal::compiler::Typer::broker(), CHECK, v8::internal::compiler::Typer::singleton_false_, v8::internal::compiler::Typer::singleton_true_, and v8::internal::tracing::type.
ObjectIsDetectableCallable()
Type v8::internal::compiler::Typer::Visitor::ObjectIsDetectableCallable (Type type, Typer * t) [static], [private]
Definition at line 756 of file turbofan-typer.cc.
                                                                 {
  CHECK(!type.IsNone());
  if (type.Is(Type::DetectableCallable())) return t->singleton_true_;
  if (!type.Maybe(Type::DetectableCallable())) return t->singleton_false_;
  return Type::Boolean();
}
References CHECK, v8::internal::compiler::Typer::singleton_false_, v8::internal::compiler::Typer::singleton_true_, and v8::internal::tracing::type.
ObjectIsMinusZero()
Type v8::internal::compiler::Typer::Visitor::ObjectIsMinusZero (Type type, Typer * t) [static], [private]
Definition at line 763 of file turbofan-typer.cc.
                                                        {
  CHECK(!type.IsNone());
  if (type.Is(Type::MinusZero())) return t->singleton_true_;
  if (!type.Maybe(Type::MinusZero())) return t->singleton_false_;
  return Type::Boolean();
}
References CHECK, v8::internal::compiler::Typer::singleton_false_, v8::internal::compiler::Typer::singleton_true_, and v8::internal::tracing::type.
ObjectIsNaN()
Type v8::internal::compiler::Typer::Visitor::ObjectIsNaN (Type type, Typer * t) [static], [private]
Definition at line 777 of file turbofan-typer.cc.
                                                  {
  CHECK(!type.IsNone());
  if (type.Is(Type::NaN())) return t->singleton_true_;
  if (!type.Maybe(Type::NaN())) return t->singleton_false_;
  return Type::Boolean();
}
References CHECK, v8::internal::compiler::Typer::singleton_false_, v8::internal::compiler::Typer::singleton_true_, and v8::internal::tracing::type.
ObjectIsNonCallable()
Type v8::internal::compiler::Typer::Visitor::ObjectIsNonCallable (Type type, Typer * t) [static], [private]
Definition at line 791 of file turbofan-typer.cc.
                                                          {
  CHECK(!type.IsNone());
  if (type.Is(Type::NonCallable())) return t->singleton_true_;
  if (!type.Maybe(Type::NonCallable())) return t->singleton_false_;
  return Type::Boolean();
}
References CHECK, v8::internal::compiler::Typer::singleton_false_, v8::internal::compiler::Typer::singleton_true_, and v8::internal::tracing::type.
ObjectIsNumber()
Type v8::internal::compiler::Typer::Visitor::ObjectIsNumber (Type type, Typer * t) [static], [private]
Definition at line 798 of file turbofan-typer.cc.
                                                     {
  CHECK(!type.IsNone());
  if (type.Is(Type::Number())) return t->singleton_true_;
  if (!type.Maybe(Type::Number())) return t->singleton_false_;
  return Type::Boolean();
}
References CHECK, v8::internal::compiler::Typer::singleton_false_, v8::internal::compiler::Typer::singleton_true_, and v8::internal::tracing::type.
ObjectIsReceiver()
Type v8::internal::compiler::Typer::Visitor::ObjectIsReceiver (Type type, Typer * t) [static], [private]
Definition at line 805 of file turbofan-typer.cc.
                                                       {
  CHECK(!type.IsNone());
  if (type.Is(Type::Receiver())) return t->singleton_true_;
  if (!type.Maybe(Type::Receiver())) return t->singleton_false_;
  return Type::Boolean();
}
References CHECK, v8::internal::compiler::Typer::singleton_false_, v8::internal::compiler::Typer::singleton_true_, and v8::internal::tracing::type.
ObjectIsSmi()
Type v8::internal::compiler::Typer::Visitor::ObjectIsSmi (Type type, Typer * t) [static], [private]
Definition at line 812 of file turbofan-typer.cc.
                                                  {
  if (!type.Maybe(Type::SignedSmall())) return t->singleton_false_;
  return Type::Boolean();
}
References v8::internal::compiler::Type::SignedSmall(), v8::internal::compiler::Typer::singleton_false_, and v8::internal::tracing::type.
ObjectIsString()
Type v8::internal::compiler::Typer::Visitor::ObjectIsString (Type type, Typer * t) [static], [private]
Definition at line 817 of file turbofan-typer.cc.
                                                     {
  CHECK(!type.IsNone());
  if (type.Is(Type::String())) return t->singleton_true_;
  if (!type.Maybe(Type::String())) return t->singleton_false_;
  return Type::Boolean();
}
References CHECK, v8::internal::compiler::Typer::singleton_false_, v8::internal::compiler::Typer::singleton_true_, and v8::internal::tracing::type.
ObjectIsSymbol()
Type v8::internal::compiler::Typer::Visitor::ObjectIsSymbol (Type type, Typer * t) [static], [private]
Definition at line 824 of file turbofan-typer.cc.
                                                     {
  CHECK(!type.IsNone());
  if (type.Is(Type::Symbol())) return t->singleton_true_;
  if (!type.Maybe(Type::Symbol())) return t->singleton_false_;
  return Type::Boolean();
}
References CHECK, v8::internal::compiler::Typer::singleton_false_, v8::internal::compiler::Typer::singleton_true_, and v8::internal::tracing::type.
ObjectIsUndetectable()
Type v8::internal::compiler::Typer::Visitor::ObjectIsUndetectable (Type type, Typer * t) [static], [private]
Definition at line 831 of file turbofan-typer.cc.
                                                           {
  CHECK(!type.IsNone());
  if (type.Is(Type::Undetectable())) return t->singleton_true_;
  if (!type.Maybe(Type::Undetectable())) return t->singleton_false_;
  return Type::Boolean();
}
References CHECK, v8::internal::compiler::Typer::singleton_false_, v8::internal::compiler::Typer::singleton_true_, and v8::internal::tracing::type.
Operand()
Type v8::internal::compiler::Typer::Visitor::Operand (Node * node, int i) [inline], [private]
Definition at line 303 of file turbofan-typer.cc.
                                  {
    Node* operand_node = NodeProperties::GetValueInput(node, i);
    return TypeOrNone(operand_node);
  }
References v8::internal::compiler::NodeProperties::GetValueInput(), and TypeOrNone().
Reduce()
Reduction v8::internal::compiler::Typer::Visitor::Reduce (Node * node) [inline], [override], [virtual]
Implements v8::internal::compiler::Reducer.
Definition at line 65 of file turbofan-typer.cc.
                                        {
    if (node->op()->ValueOutputCount() == 0) return NoChange();
    return UpdateType(node, TypeNode(node));
  }
References v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::Node::op(), TypeNode(), UpdateType(), and v8::internal::compiler::Operator::ValueOutputCount().
reducer_name()
const char* v8::internal::compiler::Typer::Visitor::reducer_name () const [inline], [override], [virtual]
Implements v8::internal::compiler::Reducer.
Definition at line 63 of file turbofan-typer.cc.
{ return "Typer"; }
ReferenceEqualTyper()
Type v8::internal::compiler::Typer::Visitor::ReferenceEqualTyper (Type lhs, Type rhs, Typer * t) [static], [private]
Definition at line 2341 of file turbofan-typer.cc.
                                                                   {
  if (lhs.IsHeapConstant() && rhs.Is(lhs)) {
    return t->singleton_true_;
  }
  return Type::Boolean();
}
References v8::internal::compiler::Type::Is(), v8::internal::compiler::Type::IsHeapConstant(), and v8::internal::compiler::Typer::singleton_true_.
SameValueNumbersOnlyTyper()
Type v8::internal::compiler::Typer::Visitor::SameValueNumbersOnlyTyper (Type lhs, Type rhs, Typer * t) [static], [private]
Definition at line 2358 of file turbofan-typer.cc.
                                                                         {
  return t->operation_typer()->SameValueNumbersOnly(lhs, rhs);
}
References v8::internal::compiler::Typer::operation_typer(), and v8::internal::compiler::OperationTyper::SameValueNumbersOnly().
SameValueTyper()
Type v8::internal::compiler::Typer::Visitor::SameValueTyper (Type lhs, Type rhs, Typer * t) [static], [private]
Definition at line 2353 of file turbofan-typer.cc.
                                                              {
  return t->operation_typer()->SameValue(lhs, rhs);
}
References v8::internal::compiler::Typer::operation_typer(), and v8::internal::compiler::OperationTyper::SameValue().
SetWeakened()
void v8::internal::compiler::Typer::Visitor::SetWeakened (NodeId node_id) [inline], [private]
Definition at line 314 of file turbofan-typer.cc.
{ weakened_nodes_.insert(node_id); }
References weakened_nodes_.
StringFromSingleCharCodeTyper()
Type v8::internal::compiler::Typer::Visitor::StringFromSingleCharCodeTyper (Type type, Typer * t) [static], [private]
Definition at line 2384 of file turbofan-typer.cc.
                                                                    {
  return Type::String();
}
StringFromSingleCodePointTyper()
Type v8::internal::compiler::Typer::Visitor::StringFromSingleCodePointTyper (Type type, Typer * t) [static], [private]
Definition at line 2388 of file turbofan-typer.cc.
                                                                     {
  return Type::String();
}
ToBigInt()
Type v8::internal::compiler::Typer::Visitor::ToBigInt (Type type, Typer * t) [static], [private]
Definition at line 686 of file turbofan-typer.cc.
                                               {
  return t->operation_typer_.ToBigInt(type);
}
References v8::internal::compiler::Typer::operation_typer_, v8::internal::compiler::OperationTyper::ToBigInt(), and v8::internal::tracing::type.
ToBigIntConvertNumber()
Type v8::internal::compiler::Typer::Visitor::ToBigIntConvertNumber (Type type, Typer * t) [static], [private]
Definition at line 691 of file turbofan-typer.cc.
                                                            {
  return t->operation_typer_.ToBigIntConvertNumber(type);
}
References v8::internal::compiler::Typer::operation_typer_, v8::internal::compiler::OperationTyper::ToBigIntConvertNumber(), and v8::internal::tracing::type.
ToBoolean()
Type v8::internal::compiler::Typer::Visitor::ToBoolean (Type type, Typer * t) [static], [private]
Definition at line 632 of file turbofan-typer.cc.
                                                {
  return t->operation_typer()->ToBoolean(type);
}
References v8::internal::compiler::Typer::operation_typer(), v8::internal::compiler::OperationTyper::ToBoolean(), and v8::internal::tracing::type.
ToInteger()
Type v8::internal::compiler::Typer::Visitor::ToInteger (Type type, Typer * t) [static], [private]
Definition at line 637 of file turbofan-typer.cc.
                                                {
  // ES6 section 7.1.4 ToInteger (argument)
  type = ToNumber(type, t);
  if (type.Is(t->cache_->kInteger)) return type;
  if (type.Is(t->cache_->kIntegerOrMinusZeroOrNaN)) {
    return Type::Union(Type::Intersect(type, t->cache_->kInteger, t->zone()),
                       t->cache_->kSingletonZero, t->zone());
  }
  return t->cache_->kInteger;
}
References v8::internal::compiler::Typer::cache_, v8::internal::compiler::Type::Intersect(), v8::internal::compiler::TypeCache::kInteger, v8::internal::compiler::TypeCache::kIntegerOrMinusZeroOrNaN, v8::internal::compiler::TypeCache::kSingletonZero, v8::internal::ToNumber(), v8::internal::tracing::type, v8::internal::compiler::Type::Union(), and v8::internal::compiler::Typer::zone().
ToLength()
Type v8::internal::compiler::Typer::Visitor::ToLength (Type type, Typer * t) [static], [private]
Definition at line 649 of file turbofan-typer.cc.
                                               {
  // ES6 section 7.1.15 ToLength (argument)
  type = ToInteger(type, t);
  if (type.IsNone()) return type;
  double min = type.Min();
  double max = type.Max();
  if (max <= 0.0) {
    return Type::Constant(0, t->zone());
  }
  if (min >= kMaxSafeInteger) {
    return Type::Constant(kMaxSafeInteger, t->zone());
  }
  if (min <= 0.0) min = 0.0;
  if (max >= kMaxSafeInteger) max = kMaxSafeInteger;
  return Type::Range(min, max, t->zone());
}
References v8::internal::compiler::Type::Constant(), v8::internal::kMaxSafeInteger, v8::internal::compiler::Type::Range(), v8::internal::tracing::type, and v8::internal::compiler::Typer::zone().
ToName()
Type v8::internal::compiler::Typer::Visitor::ToName (Type type, Typer * t) [static], [private]
Definition at line 667 of file turbofan-typer.cc.
                                             {
  // ES6 section 7.1.14 ToPropertyKey (argument)
  type = ToPrimitive(type, t);
  if (type.Is(Type::Name())) return type;
  if (type.Maybe(Type::Symbol())) return Type::Name();
  return ToString(type, t);
}
References v8::internal::compiler::ToString(), and v8::internal::tracing::type.
ToNumber()
Type v8::internal::compiler::Typer::Visitor::ToNumber (Type type, Typer * t) [static], [private]
Definition at line 676 of file turbofan-typer.cc.
                                               {
  return t->operation_typer_.ToNumber(type);
}
References v8::internal::compiler::Typer::operation_typer_, v8::internal::compiler::OperationTyper::ToNumber(), and v8::internal::tracing::type.
ToNumberConvertBigInt()
Type v8::internal::compiler::Typer::Visitor::ToNumberConvertBigInt (Type type, Typer * t) [static], [private]
Definition at line 681 of file turbofan-typer.cc.
                                                            {
  return t->operation_typer_.ToNumberConvertBigInt(type);
}
References v8::internal::compiler::Typer::operation_typer_, v8::internal::compiler::OperationTyper::ToNumberConvertBigInt(), and v8::internal::tracing::type.
ToNumeric()
Type v8::internal::compiler::Typer::Visitor::ToNumeric (Type type, Typer * t) [static], [private]
Definition at line 696 of file turbofan-typer.cc.
                                                {
  return t->operation_typer_.ToNumeric(type);
}
References v8::internal::compiler::Typer::operation_typer_, v8::internal::compiler::OperationTyper::ToNumeric(), and v8::internal::tracing::type.
ToObject()
Type v8::internal::compiler::Typer::Visitor::ToObject (Type type, Typer * t) [static], [private]
Definition at line 701 of file turbofan-typer.cc.
                                               {
  // ES6 section 7.1.13 ToObject (argument)
  if (type.Is(Type::Receiver())) return type;
  if (type.Is(Type::Primitive())) return Type::StringWrapperOrOtherObject();
  if (!type.Maybe(Type::OtherUndetectable())) {
    return Type::DetectableReceiver();
  }
  return Type::Receiver();
}
References v8::internal::tracing::type.
ToPrimitive()
Type v8::internal::compiler::Typer::Visitor::ToPrimitive (Type type, Typer * t) [static], [private]
Definition at line 625 of file turbofan-typer.cc.
                                                  {
  if (type.Is(Type::Primitive()) && !type.Maybe(Type::Receiver())) {
    return type;
  }
  return Type::Primitive();
}
References v8::internal::tracing::type.
ToString()
Type v8::internal::compiler::Typer::Visitor::ToString (Type type, Typer * t) [static], [private]
Definition at line 712 of file turbofan-typer.cc.
                                               {
  // ES6 section 7.1.12 ToString (argument)
  type = ToPrimitive(type, t);
  if (type.Is(Type::String())) return type;
  return Type::String();
}
References v8::internal::tracing::type.
TypeBinaryOp() [1/2]
Type v8::internal::compiler::Typer::Visitor::TypeBinaryOp (Node * node, BinaryTyperFun f) [inline], [private]
Definition at line 526 of file turbofan-typer.cc.
                                                            {
  Type left = Operand(node, 0);
  Type right = Operand(node, 1);
  return TypeBinaryOp(left, right, f);
}
TypeBinaryOp() [2/2]
Type v8::internal::compiler::Typer::Visitor::TypeBinaryOp (Type left, Type right, BinaryTyperFun f) [inline], [private]
Definition at line 532 of file turbofan-typer.cc.
                                                                       {
  return left.IsNone() || right.IsNone() ? Type::None()
                                         : f(left, right, typer_);
}
References v8::internal::compiler::Type::IsNone(), and v8::internal::compiler::turboshaft::Type::None().
TypeConstant()
Type v8::internal::compiler::Typer::Visitor::TypeConstant (Handle< Object > value)
Definition at line 2765 of file turbofan-typer.cc.
                                                    {
  return Type::Constant(typer_->broker(), value, zone());
}
References v8::internal::compiler::Typer::broker(), v8::internal::compiler::Type::Constant(), v8::internal::value, and v8::internal::compiler::Typer::zone().
TypeNode()
Type v8::internal::compiler::Typer::Visitor::TypeNode (Node * node) [inline]
Definition at line 70 of file turbofan-typer.cc.
                            {
    switch (node->opcode()) {
#define DECLARE_UNARY_CASE(x, ...) \
  case IrOpcode::k##x: \
    return Type##x(Operand(node, 0));
      JS_SIMPLE_UNOP_LIST(DECLARE_UNARY_CASE)
      SIMPLIFIED_NUMBER_UNOP_LIST(DECLARE_UNARY_CASE)
      SIMPLIFIED_BIGINT_UNOP_LIST(DECLARE_UNARY_CASE)
      SIMPLIFIED_SPECULATIVE_NUMBER_UNOP_LIST(DECLARE_UNARY_CASE)
      SIMPLIFIED_SPECULATIVE_BIGINT_UNOP_LIST(DECLARE_UNARY_CASE)
      DECLARE_UNARY_CASE(ChangeUint32ToUint64)
#undef DECLARE_UNARY_CASE
#define DECLARE_BINARY_CASE(x, ...) \
  case IrOpcode::k##x: \
    return Type##x(Operand(node, 0), Operand(node, 1));
      JS_SIMPLE_BINOP_LIST(DECLARE_BINARY_CASE)
      SIMPLIFIED_NUMBER_BINOP_LIST(DECLARE_BINARY_CASE)
      SIMPLIFIED_BIGINT_BINOP_LIST(DECLARE_BINARY_CASE)
      SIMPLIFIED_SPECULATIVE_NUMBER_BINOP_LIST(DECLARE_BINARY_CASE)
      SIMPLIFIED_SPECULATIVE_BIGINT_BINOP_LIST(DECLARE_BINARY_CASE)
      TYPER_SUPPORTED_MACHINE_BINOP_LIST(DECLARE_BINARY_CASE)
#undef DECLARE_BINARY_CASE
#define DECLARE_OTHER_CASE(x, ...) \
  case IrOpcode::k##x: \
    return Type##x(node);
      DECLARE_OTHER_CASE(Start)
      DECLARE_OTHER_CASE(IfException)
      COMMON_OP_LIST(DECLARE_OTHER_CASE)
      SIMPLIFIED_COMPARE_BINOP_LIST(DECLARE_OTHER_CASE)
      SIMPLIFIED_OTHER_OP_LIST(DECLARE_OTHER_CASE)
      JS_OBJECT_OP_LIST(DECLARE_OTHER_CASE)
      JS_CONTEXT_OP_LIST(DECLARE_OTHER_CASE)
      JS_OTHER_OP_LIST(DECLARE_OTHER_CASE)
#undef DECLARE_OTHER_CASE
#define DECLARE_IMPOSSIBLE_CASE(x, ...) case IrOpcode::k##x:
      DECLARE_IMPOSSIBLE_CASE(Loop)
      DECLARE_IMPOSSIBLE_CASE(Branch)
      DECLARE_IMPOSSIBLE_CASE(IfTrue)
      DECLARE_IMPOSSIBLE_CASE(IfFalse)
      DECLARE_IMPOSSIBLE_CASE(IfSuccess)
      DECLARE_IMPOSSIBLE_CASE(Switch)
      DECLARE_IMPOSSIBLE_CASE(IfValue)
      DECLARE_IMPOSSIBLE_CASE(IfDefault)
      DECLARE_IMPOSSIBLE_CASE(Merge)
      DECLARE_IMPOSSIBLE_CASE(Deoptimize)
      DECLARE_IMPOSSIBLE_CASE(DeoptimizeIf)
      DECLARE_IMPOSSIBLE_CASE(DeoptimizeUnless)
      DECLARE_IMPOSSIBLE_CASE(TrapIf)
      DECLARE_IMPOSSIBLE_CASE(TrapUnless)
      DECLARE_IMPOSSIBLE_CASE(Assert)
      DECLARE_IMPOSSIBLE_CASE(Return)
      DECLARE_IMPOSSIBLE_CASE(TailCall)
      DECLARE_IMPOSSIBLE_CASE(Terminate)
      DECLARE_IMPOSSIBLE_CASE(Throw)
      DECLARE_IMPOSSIBLE_CASE(End)
      SIMPLIFIED_CHANGE_OP_LIST(DECLARE_IMPOSSIBLE_CASE)
      SIMPLIFIED_CHECKED_OP_LIST(DECLARE_IMPOSSIBLE_CASE)
      IF_WASM(SIMPLIFIED_WASM_OP_LIST, DECLARE_IMPOSSIBLE_CASE)
      MACHINE_SIMD128_OP_LIST(DECLARE_IMPOSSIBLE_CASE)
      IF_WASM(MACHINE_SIMD256_OP_LIST, DECLARE_IMPOSSIBLE_CASE)
      MACHINE_UNOP_32_LIST(DECLARE_IMPOSSIBLE_CASE)
      DECLARE_IMPOSSIBLE_CASE(Word32Xor)
      DECLARE_IMPOSSIBLE_CASE(Word32Sar)
      DECLARE_IMPOSSIBLE_CASE(Word32Rol)
      DECLARE_IMPOSSIBLE_CASE(Word32Ror)
      DECLARE_IMPOSSIBLE_CASE(Int32AddWithOverflow)
      DECLARE_IMPOSSIBLE_CASE(Int32SubWithOverflow)
      DECLARE_IMPOSSIBLE_CASE(Int32Mul)
      DECLARE_IMPOSSIBLE_CASE(Int32MulWithOverflow)
      DECLARE_IMPOSSIBLE_CASE(Int32MulHigh)
      DECLARE_IMPOSSIBLE_CASE(Int32Div)
      DECLARE_IMPOSSIBLE_CASE(Int32Mod)
      DECLARE_IMPOSSIBLE_CASE(Uint32Mod)
      DECLARE_IMPOSSIBLE_CASE(Uint32MulHigh)
      DECLARE_IMPOSSIBLE_CASE(Word64Or)
      DECLARE_IMPOSSIBLE_CASE(Word64Xor)
      DECLARE_IMPOSSIBLE_CASE(Word64Sar)
      DECLARE_IMPOSSIBLE_CASE(Word64Rol)
      DECLARE_IMPOSSIBLE_CASE(Word64Ror)
      DECLARE_IMPOSSIBLE_CASE(Word64RolLowerable)
      DECLARE_IMPOSSIBLE_CASE(Word64RorLowerable)
      DECLARE_IMPOSSIBLE_CASE(Int64AddWithOverflow)
      DECLARE_IMPOSSIBLE_CASE(Int64SubWithOverflow)
      DECLARE_IMPOSSIBLE_CASE(Int64Mul)
      DECLARE_IMPOSSIBLE_CASE(Int64MulHigh)
      DECLARE_IMPOSSIBLE_CASE(Int64MulWithOverflow)
      DECLARE_IMPOSSIBLE_CASE(Int64Div)
      DECLARE_IMPOSSIBLE_CASE(Int64Mod)
      DECLARE_IMPOSSIBLE_CASE(Uint64Mod)
      DECLARE_IMPOSSIBLE_CASE(Uint64MulHigh)
      DECLARE_IMPOSSIBLE_CASE(Word64Equal)
      DECLARE_IMPOSSIBLE_CASE(Int32LessThan)
      DECLARE_IMPOSSIBLE_CASE(Int64LessThan)
      DECLARE_IMPOSSIBLE_CASE(Int64LessThanOrEqual)
      DECLARE_IMPOSSIBLE_CASE(Float32Equal)
      DECLARE_IMPOSSIBLE_CASE(Float32LessThan)
      DECLARE_IMPOSSIBLE_CASE(Float32LessThanOrEqual)
      DECLARE_IMPOSSIBLE_CASE(Float64Equal)
      DECLARE_IMPOSSIBLE_CASE(Float64LessThan)
      DECLARE_IMPOSSIBLE_CASE(Float64LessThanOrEqual)
      MACHINE_FLOAT32_BINOP_LIST(DECLARE_IMPOSSIBLE_CASE)
      MACHINE_FLOAT32_UNOP_LIST(DECLARE_IMPOSSIBLE_CASE)
      MACHINE_FLOAT64_BINOP_LIST(DECLARE_IMPOSSIBLE_CASE)
      MACHINE_FLOAT64_UNOP_LIST(DECLARE_IMPOSSIBLE_CASE)
      MACHINE_ATOMIC_OP_LIST(DECLARE_IMPOSSIBLE_CASE)
      DECLARE_IMPOSSIBLE_CASE(AbortCSADcheck)
      DECLARE_IMPOSSIBLE_CASE(DebugBreak)
      DECLARE_IMPOSSIBLE_CASE(Comment)
      DECLARE_IMPOSSIBLE_CASE(LoadImmutable)
      DECLARE_IMPOSSIBLE_CASE(StorePair)
      DECLARE_IMPOSSIBLE_CASE(Store)
      DECLARE_IMPOSSIBLE_CASE(StoreIndirectPointer)
      DECLARE_IMPOSSIBLE_CASE(StackSlot)
      DECLARE_IMPOSSIBLE_CASE(Word32Popcnt)
      DECLARE_IMPOSSIBLE_CASE(Word64Popcnt)
      DECLARE_IMPOSSIBLE_CASE(Word64Clz)
      DECLARE_IMPOSSIBLE_CASE(Word64Ctz)
      DECLARE_IMPOSSIBLE_CASE(Word64ClzLowerable)
      DECLARE_IMPOSSIBLE_CASE(Word64CtzLowerable)
      DECLARE_IMPOSSIBLE_CASE(Word64ReverseBits)
      DECLARE_IMPOSSIBLE_CASE(Word64ReverseBytes)
      DECLARE_IMPOSSIBLE_CASE(Simd128ReverseBytes)
      DECLARE_IMPOSSIBLE_CASE(Int64AbsWithOverflow)
      DECLARE_IMPOSSIBLE_CASE(BitcastTaggedToWord)
      DECLARE_IMPOSSIBLE_CASE(BitcastTaggedToWordForTagAndSmiBits)
      DECLARE_IMPOSSIBLE_CASE(BitcastWordToTagged)
      DECLARE_IMPOSSIBLE_CASE(BitcastWordToTaggedSigned)
      DECLARE_IMPOSSIBLE_CASE(TruncateFloat64ToWord32)
      DECLARE_IMPOSSIBLE_CASE(ChangeFloat32ToFloat64)
      DECLARE_IMPOSSIBLE_CASE(ChangeFloat64ToInt32)
      DECLARE_IMPOSSIBLE_CASE(ChangeFloat64ToInt64)
      DECLARE_IMPOSSIBLE_CASE(ChangeFloat64ToUint32)
      DECLARE_IMPOSSIBLE_CASE(ChangeFloat64ToUint64)
      DECLARE_IMPOSSIBLE_CASE(Float64SilenceNaN)
      DECLARE_IMPOSSIBLE_CASE(TruncateFloat64ToInt64)
      DECLARE_IMPOSSIBLE_CASE(TruncateFloat64ToUint32)
      DECLARE_IMPOSSIBLE_CASE(TruncateFloat32ToInt32)
      DECLARE_IMPOSSIBLE_CASE(TruncateFloat32ToUint32)
      DECLARE_IMPOSSIBLE_CASE(TryTruncateFloat32ToInt64)
      DECLARE_IMPOSSIBLE_CASE(TryTruncateFloat64ToInt64)
      DECLARE_IMPOSSIBLE_CASE(TryTruncateFloat32ToUint64)
      DECLARE_IMPOSSIBLE_CASE(TryTruncateFloat64ToUint64)
      DECLARE_IMPOSSIBLE_CASE(TryTruncateFloat64ToInt32)
      DECLARE_IMPOSSIBLE_CASE(TryTruncateFloat64ToUint32)
      DECLARE_IMPOSSIBLE_CASE(ChangeInt32ToFloat64)
      DECLARE_IMPOSSIBLE_CASE(BitcastWord32ToWord64)
      DECLARE_IMPOSSIBLE_CASE(ChangeInt32ToInt64)
      DECLARE_IMPOSSIBLE_CASE(ChangeInt64ToFloat64)
      DECLARE_IMPOSSIBLE_CASE(ChangeUint32ToFloat64)
      DECLARE_IMPOSSIBLE_CASE(ChangeFloat16RawBitsToFloat64)
      DECLARE_IMPOSSIBLE_CASE(TruncateFloat64ToFloat32)
      DECLARE_IMPOSSIBLE_CASE(TruncateFloat64ToFloat16RawBits)
      DECLARE_IMPOSSIBLE_CASE(TruncateInt64ToInt32)
      DECLARE_IMPOSSIBLE_CASE(RoundFloat64ToInt32)
      DECLARE_IMPOSSIBLE_CASE(RoundInt32ToFloat32)
      DECLARE_IMPOSSIBLE_CASE(RoundInt64ToFloat32)
      DECLARE_IMPOSSIBLE_CASE(RoundInt64ToFloat64)
      DECLARE_IMPOSSIBLE_CASE(RoundUint32ToFloat32)
      DECLARE_IMPOSSIBLE_CASE(RoundUint64ToFloat32)
      DECLARE_IMPOSSIBLE_CASE(RoundUint64ToFloat64)
      DECLARE_IMPOSSIBLE_CASE(BitcastFloat32ToInt32)
      DECLARE_IMPOSSIBLE_CASE(BitcastFloat64ToInt64)
      DECLARE_IMPOSSIBLE_CASE(BitcastInt32ToFloat32)
      DECLARE_IMPOSSIBLE_CASE(BitcastInt64ToFloat64)
      DECLARE_IMPOSSIBLE_CASE(Float64ExtractLowWord32)
      DECLARE_IMPOSSIBLE_CASE(Float64ExtractHighWord32)
      DECLARE_IMPOSSIBLE_CASE(Float64InsertLowWord32)
      DECLARE_IMPOSSIBLE_CASE(Float64InsertHighWord32)
      DECLARE_IMPOSSIBLE_CASE(Word32Select)
      DECLARE_IMPOSSIBLE_CASE(Word64Select)
      DECLARE_IMPOSSIBLE_CASE(Float32Select)
      DECLARE_IMPOSSIBLE_CASE(Float64Select)
      DECLARE_IMPOSSIBLE_CASE(LoadStackCheckOffset)
      DECLARE_IMPOSSIBLE_CASE(LoadFramePointer)
      IF_WASM(DECLARE_IMPOSSIBLE_CASE, LoadStackPointer)
      IF_WASM(DECLARE_IMPOSSIBLE_CASE, SetStackPointer)
      DECLARE_IMPOSSIBLE_CASE(LoadParentFramePointer)
      DECLARE_IMPOSSIBLE_CASE(LoadRootRegister)
      DECLARE_IMPOSSIBLE_CASE(UnalignedLoad)
      DECLARE_IMPOSSIBLE_CASE(UnalignedStore)
      DECLARE_IMPOSSIBLE_CASE(Int32PairAdd)
      DECLARE_IMPOSSIBLE_CASE(Int32PairSub)
      DECLARE_IMPOSSIBLE_CASE(Int32PairMul)
      DECLARE_IMPOSSIBLE_CASE(Word32PairShl)
      DECLARE_IMPOSSIBLE_CASE(Word32PairShr)
      DECLARE_IMPOSSIBLE_CASE(Word32PairSar)
      DECLARE_IMPOSSIBLE_CASE(ProtectedLoad)
      DECLARE_IMPOSSIBLE_CASE(ProtectedStore)
      DECLARE_IMPOSSIBLE_CASE(LoadTrapOnNull)
      DECLARE_IMPOSSIBLE_CASE(StoreTrapOnNull)
      DECLARE_IMPOSSIBLE_CASE(MemoryBarrier)
      DECLARE_IMPOSSIBLE_CASE(SignExtendWord8ToInt32)
      DECLARE_IMPOSSIBLE_CASE(SignExtendWord16ToInt32)
      DECLARE_IMPOSSIBLE_CASE(SignExtendWord8ToInt64)
      DECLARE_IMPOSSIBLE_CASE(SignExtendWord16ToInt64)
      DECLARE_IMPOSSIBLE_CASE(SignExtendWord32ToInt64)
      DECLARE_IMPOSSIBLE_CASE(StackPointerGreaterThan)
      DECLARE_IMPOSSIBLE_CASE(TraceInstruction)
#undef DECLARE_IMPOSSIBLE_CASE
      UNREACHABLE();
    }
  }
References COMMON_OP_LIST, DECLARE_BINARY_CASE, DECLARE_IMPOSSIBLE_CASE, DECLARE_OTHER_CASE, DECLARE_UNARY_CASE, IF_WASM, JS_CONTEXT_OP_LIST, JS_OBJECT_OP_LIST, JS_OTHER_OP_LIST, JS_SIMPLE_BINOP_LIST, JS_SIMPLE_UNOP_LIST, MACHINE_ATOMIC_OP_LIST, MACHINE_FLOAT32_BINOP_LIST, MACHINE_FLOAT32_UNOP_LIST, MACHINE_FLOAT64_BINOP_LIST, MACHINE_FLOAT64_UNOP_LIST, MACHINE_SIMD128_OP_LIST, MACHINE_SIMD256_OP_LIST, MACHINE_UNOP_32_LIST, v8::internal::compiler::Node::opcode(), SIMPLIFIED_BIGINT_BINOP_LIST, SIMPLIFIED_BIGINT_UNOP_LIST, SIMPLIFIED_CHANGE_OP_LIST, SIMPLIFIED_CHECKED_OP_LIST, SIMPLIFIED_COMPARE_BINOP_LIST, SIMPLIFIED_NUMBER_BINOP_LIST, SIMPLIFIED_NUMBER_UNOP_LIST, SIMPLIFIED_OTHER_OP_LIST, SIMPLIFIED_SPECULATIVE_BIGINT_BINOP_LIST, SIMPLIFIED_SPECULATIVE_BIGINT_UNOP_LIST, SIMPLIFIED_SPECULATIVE_NUMBER_BINOP_LIST, SIMPLIFIED_SPECULATIVE_NUMBER_UNOP_LIST, SIMPLIFIED_WASM_OP_LIST, v8::internal::wasm::liftoff::Store(), v8::internal::Terminate(), TYPER_SUPPORTED_MACHINE_BINOP_LIST, v8::internal::maglev::anonymous_namespace{maglev-ir-arm.cc}::Uint32Mod(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::Typer::Decorator::Decorate(), and Reduce().
TypeOrNone()
Type v8::internal::compiler::Typer::Visitor::TypeOrNone (Node * node) [inline], [private]
Definition at line 298 of file turbofan-typer.cc.
                              {
    return NodeProperties::IsTyped(node) ? NodeProperties::GetType(node)
                                         : Type::None();
  }
References v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::IsTyped(), and v8::internal::compiler::turboshaft::Type::None().
Referenced by Operand().
TypeUnaryOp() [1/2]
Type v8::internal::compiler::Typer::Visitor::TypeUnaryOp (Node * node, UnaryTyperFun f) [inline], [private]
Definition at line 517 of file turbofan-typer.cc.
                                                          {
  Type input = Operand(node, 0);
  return TypeUnaryOp(input, f);
}
TypeUnaryOp() [2/2]
Type v8::internal::compiler::Typer::Visitor::TypeUnaryOp (Type input, UnaryTyperFun f) [inline], [private]
Definition at line 522 of file turbofan-typer.cc.
                                                          {
  return input.IsNone() ? Type::None() : f(input, typer_);
}
References v8::internal::compiler::Type::IsNone(), and v8::internal::compiler::turboshaft::Type::None().
UpdateType()
Reduction v8::internal::compiler::Typer::Visitor::UpdateType (Node * node, Type current) [inline], [private]
Definition at line 437 of file turbofan-typer.cc.
                                                 {
    if (NodeProperties::IsTyped(node)) {
      // Widen the type of a previously typed node.
      Type previous = NodeProperties::GetType(node);
      if (node->opcode() == IrOpcode::kPhi ||
          node->opcode() == IrOpcode::kInductionVariablePhi) {
        // Speed up termination in the presence of range types:
        current = Weaken(node, current, previous);
      }
      if (V8_UNLIKELY(!previous.Is(current))) {
        AllowHandleDereference allow;
        std::ostringstream ostream;
        node->Print(ostream);
        FATAL("UpdateType error for node %s", ostream.str().c_str());
      }
      NodeProperties::SetType(node, current);
      if (!current.Is(previous)) {
        // If something changed, revisit all uses.
        return Changed(node);
      }
      return NoChange();
    } else {
      // No previous type, simply update the type.
      NodeProperties::SetType(node, current);
      return Changed(node);
    }
  }
References v8::internal::compiler::Reducer::Changed(), FATAL, v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::Type::Is(), v8::internal::compiler::NodeProperties::IsTyped(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::Node::Print(), v8::internal::compiler::NodeProperties::SetType(), V8_UNLIKELY, and Weaken().
Referenced by Reduce().
Weaken()
Type v8::internal::compiler::Typer::Visitor::Weaken (Node * node, Type current_type, Type previous_type) [private]
Definition at line 1618 of file turbofan-typer.cc.
                                                                           {
  static const double kWeakenMinLimits[] = {0.0,
                                            -1073741824.0,
                                            -2147483648.0,
                                            -4294967296.0,
                                            -8589934592.0,
                                            -17179869184.0,
                                            -34359738368.0,
                                            -68719476736.0,
                                            -137438953472.0,
                                            -274877906944.0,
                                            -549755813888.0,
                                            -1099511627776.0,
                                            -2199023255552.0,
                                            -4398046511104.0,
                                            -8796093022208.0,
                                            -17592186044416.0,
                                            -35184372088832.0,
                                            -70368744177664.0,
                                            -140737488355328.0,
                                            -281474976710656.0,
                                            -562949953421312.0};
  static const double kWeakenMaxLimits[] = {0.0,
                                            1073741823.0,
                                            2147483647.0,
                                            4294967295.0,
                                            8589934591.0,
                                            17179869183.0,
                                            34359738367.0,
                                            68719476735.0,
                                            137438953471.0,
                                            274877906943.0,
                                            549755813887.0,
                                            1099511627775.0,
                                            2199023255551.0,
                                            4398046511103.0,
                                            8796093022207.0,
                                            17592186044415.0,
                                            35184372088831.0,
                                            70368744177663.0,
                                            140737488355327.0,
                                            281474976710655.0,
                                            562949953421311.0};
  static_assert(arraysize(kWeakenMinLimits) == arraysize(kWeakenMaxLimits));
  // If the types have nothing to do with integers, return the types.
  Type const integer = typer_->cache_->kInteger;
  if (!previous_type.Maybe(integer)) {
    return current_type;
  }
  DCHECK(current_type.Maybe(integer));
  Type current_integer = Type::Intersect(current_type, integer, zone());
  Type previous_integer = Type::Intersect(previous_type, integer, zone());
  // Once we start weakening a node, we should always weaken.
  if (!IsWeakened(node->id())) {
    // Only weaken if there is range involved; we should converge quickly
    // for all other types (the exception is a union of many constants,
    // but we currently do not increase the number of constants in unions).
    Type previous = previous_integer.GetRange();
    Type current = current_integer.GetRange();
    if (current.IsInvalid() || previous.IsInvalid()) {
      return current_type;
    }
    // Range is involved => we are weakening.
    SetWeakened(node->id());
  }
  double current_min = current_integer.Min();
  double new_min = current_min;
  // Find the closest lower entry in the list of allowed
  // minima (or negative infinity if there is no such entry).
  if (current_min != previous_integer.Min()) {
    new_min = -V8_INFINITY;
    for (double const min : kWeakenMinLimits) {
      if (min <= current_min) {
        new_min = min;
        break;
      }
    }
  }
  double current_max = current_integer.Max();
  double new_max = current_max;
  // Find the closest greater entry in the list of allowed
  // maxima (or infinity if there is no such entry).
  if (current_max != previous_integer.Max()) {
    new_max = V8_INFINITY;
    for (double const max : kWeakenMaxLimits) {
      if (max >= current_max) {
        new_max = max;
        break;
      }
    }
  }
  return Type::Union(current_type,
                     Type::Range(new_min, new_max, typer_->zone()),
                     typer_->zone());
}
References arraysize, v8::internal::compiler::Typer::cache_, v8::internal::DCHECK(), v8::internal::compiler::Type::GetRange(), v8::internal::compiler::Node::id(), v8::internal::compiler::Type::Intersect(), v8::internal::compiler::Type::IsInvalid(), v8::internal::compiler::TypeCache::kInteger, v8::internal::compiler::Type::Max(), v8::internal::compiler::Type::Maybe(), v8::internal::compiler::Type::Min(), v8::internal::compiler::Type::Range(), v8::internal::compiler::Type::Union(), V8_INFINITY, and v8::internal::compiler::Typer::zone().
Referenced by UpdateType().
zone()
Zone* v8::internal::compiler::Typer::Visitor::zone () [inline], [private]
Definition at line 310 of file turbofan-typer.cc.
{ return typer_->zone(); }
References typer_, and v8::internal::compiler::Typer::zone().
Member Data Documentation
induction_vars_
LoopVariableOptimizer* v8::internal::compiler::Typer::Visitor::induction_vars_ [private]
Definition at line 281 of file turbofan-typer.cc.
typer_
Typer* v8::internal::compiler::Typer::Visitor::typer_ [private]
Definition at line 280 of file turbofan-typer.cc.
Referenced by broker(), graph(), and zone().
weakened_nodes_
ZoneSet<NodeId> v8::internal::compiler::Typer::Visitor::weakened_nodes_ [private]
Definition at line 282 of file turbofan-typer.cc.
Referenced by IsWeakened(), and SetWeakened().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turbofan-typer.cc