v8::internal::compiler::CodeAssemblerLabel Class Reference
#include <code-assembler.h>
Public Types
enum Type { kDeferred
, kNonDeferred
 }
Public Member Functions
CodeAssemblerLabel (CodeAssembler *assembler, CodeAssemblerLabel::Type type=CodeAssemblerLabel::kNonDeferred)
CodeAssemblerLabel (CodeAssembler *assembler, const CodeAssemblerVariableList &merged_variables, CodeAssemblerLabel::Type type=CodeAssemblerLabel::kNonDeferred)
CodeAssemblerLabel (CodeAssembler *assembler, size_t count, CodeAssemblerVariable *const *vars, CodeAssemblerLabel::Type type=CodeAssemblerLabel::kNonDeferred)
CodeAssemblerLabel (CodeAssembler *assembler, std::initializer_list< CodeAssemblerVariable * > vars, CodeAssemblerLabel::Type type=CodeAssemblerLabel::kNonDeferred)
CodeAssemblerLabel (CodeAssembler *assembler, CodeAssemblerVariable *merged_variable, CodeAssemblerLabel::Type type=CodeAssemblerLabel::kNonDeferred)
~CodeAssemblerLabel ()
CodeAssemblerLabel (const CodeAssemblerLabel &)=delete
CodeAssemblerLabel & operator= (const CodeAssemblerLabel &)=delete
bool is_bound () const
bool is_used () const
Private Member Functions
void Bind ()
void UpdateVariablesAfterBind ()
void MergeVariables ()
Private Attributes
bool bound_
size_t merge_count_
CodeAssemblerState * state_
RawMachineLabel * label_
std::map< CodeAssemblerVariable::Impl *, Node *, CodeAssemblerVariable::ImplComparator > variable_phis_
std::map< CodeAssemblerVariable::Impl *, std::vector< Node * >, CodeAssemblerVariable::ImplComparator > variable_merges_
Friends
class CodeAssembler
Detailed Description
Definition at line 1754 of file code-assembler.h.
Member Enumeration Documentation
Type
enum v8::internal::compiler::CodeAssemblerLabel::Type
Enumerator
kDeferred
kNonDeferred
Definition at line 1756 of file code-assembler.h.
{ kDeferred, kNonDeferred };
Constructor & Destructor Documentation
CodeAssemblerLabel() [1/6]
v8::internal::compiler::CodeAssemblerLabel::CodeAssemblerLabel (CodeAssembler * assembler, CodeAssemblerLabel::Type type = CodeAssemblerLabel::kNonDeferred) [inline], [explicit]
Definition at line 1758 of file code-assembler.h.
      : CodeAssemblerLabel(assembler, 0, nullptr, type) {}
CodeAssemblerLabel() [2/6]
v8::internal::compiler::CodeAssemblerLabel::CodeAssemblerLabel (CodeAssembler * assembler, const CodeAssemblerVariableList & merged_variables, CodeAssemblerLabel::Type type = CodeAssemblerLabel::kNonDeferred) [inline]
Definition at line 1762 of file code-assembler.h.
      : CodeAssemblerLabel(assembler, merged_variables.size(),
                           &(merged_variables[0]), type) {}
CodeAssemblerLabel() [3/6]
v8::internal::compiler::CodeAssemblerLabel::CodeAssemblerLabel (CodeAssembler * assembler, size_t count, CodeAssemblerVariable *const * vars, CodeAssemblerLabel::Type type = CodeAssemblerLabel::kNonDeferred)
Definition at line 1803 of file code-assembler.cc.
    : bound_(false),
      merge_count_(0),
      state_(assembler->state()),
      label_(nullptr) {
  label_ = assembler->zone()->New<RawMachineLabel>(
      type == kDeferred ? RawMachineLabel::kDeferred
                        : RawMachineLabel::kNonDeferred);
  for (size_t i = 0; i < vars_count; ++i) {
    variable_phis_[vars[i]->impl_] = nullptr;
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::CodeAssemblerVariable::impl_, kDeferred, v8::internal::compiler::RawMachineLabel::kDeferred, v8::internal::compiler::RawMachineLabel::kNonDeferred, label_, v8::internal::Zone::New(), v8::internal::tracing::type, variable_phis_, and v8::internal::compiler::CodeAssembler::zone().
CodeAssemblerLabel() [4/6]
v8::internal::compiler::CodeAssemblerLabel::CodeAssemblerLabel (CodeAssembler * assembler, std::initializer_list< CodeAssemblerVariable * > vars, CodeAssemblerLabel::Type type = CodeAssemblerLabel::kNonDeferred) [inline]
Definition at line 1772 of file code-assembler.h.
      : CodeAssemblerLabel(assembler, vars.size(), vars.begin(), type) {}
CodeAssemblerLabel() [5/6]
v8::internal::compiler::CodeAssemblerLabel::CodeAssemblerLabel (CodeAssembler * assembler, CodeAssemblerVariable * merged_variable, CodeAssemblerLabel::Type type = CodeAssemblerLabel::kNonDeferred) [inline]
Definition at line 1777 of file code-assembler.h.
      : CodeAssemblerLabel(assembler, 1, &merged_variable, type) {}
 CodeAssemblerLabel()
v8::internal::compiler::CodeAssemblerLabel::~CodeAssemblerLabel ()
Definition at line 1819 of file code-assembler.cc.
{ label_->~RawMachineLabel(); }
References label_, and v8::internal::compiler::RawMachineLabel::~RawMachineLabel().
CodeAssemblerLabel() [6/6]
v8::internal::compiler::CodeAssemblerLabel::CodeAssemblerLabel (const CodeAssemblerLabel &) [delete]
Member Function Documentation
Bind()
void v8::internal::compiler::CodeAssemblerLabel::Bind () [private]
Definition at line 1898 of file code-assembler.cc.
                              {
  DCHECK(!bound_);
  state_->raw_assembler_->Bind(label_);
  UpdateVariablesAfterBind();
}
References bound_, v8::internal::DCHECK(), label_, v8::internal::compiler::CodeAssemblerState::raw_assembler_, state_, and UpdateVariablesAfterBind().
Referenced by v8::internal::compiler::CodeAssembler::Bind().
is_bound()
bool v8::internal::compiler::CodeAssemblerLabel::is_bound () const [inline]
Definition at line 1788 of file code-assembler.h.
{ return bound_; }
Referenced by v8::internal::compiler::CodeAssembler::Branch().
is_used()
bool v8::internal::compiler::CodeAssemblerLabel::is_used () const [inline]
Definition at line 1789 of file code-assembler.h.
{ return merge_count_ != 0; }
Referenced by v8::internal::compiler::CodeAssembler::Branch(), and v8::internal::compiler::CodeAssemblerParameterizedLabelBase::is_used().
MergeVariables()
void v8::internal::compiler::CodeAssemblerLabel::MergeVariables () [private]
Definition at line 1821 of file code-assembler.cc.
                                        {
  ++merge_count_;
  for (CodeAssemblerVariable::Impl* var : state_->variables_) {
    size_t count = 0;
    Node* node = var->value_;
    if (node != nullptr) {
      auto i = variable_merges_.find(var);
      if (i != variable_merges_.end()) {
        i->second.push_back(node);
        count = i->second.size();
      } else {
        count = 1;
        variable_merges_[var] = std::vector<Node*>(1, node);
      }
    }
    // If the following asserts, then you've jumped to a label without a bound
    // variable along that path that expects to merge its value into a phi.
    // This can also occur if a label is bound that is never jumped to.
    DCHECK(variable_phis_.find(var) == variable_phis_.end() ||
           count == merge_count_);
    USE(count);
    // If the label is already bound, we already know the set of variables to
    // merge and phi nodes have already been created.
    if (bound_) {
      auto phi = variable_phis_.find(var);
      if (phi != variable_phis_.end()) {
        DCHECK_NOT_NULL(phi->second);
        state_->raw_assembler_->AppendPhiInput(phi->second, node);
      } else {
        auto i = variable_merges_.find(var);
        if (i != variable_merges_.end()) {
          // If the following assert fires, then you've declared a variable that
          // has the same bound value along all paths up until the point you
          // bound this label, but then later merged a path with a new value for
          // the variable after the label bind (it's not possible to add phis to
          // the bound label after the fact, just make sure to list the variable
          // in the label's constructor's list of merged variables).
#if DEBUG
          if (find_if(i->second.begin(), i->second.end(),
                      [node](Node* e) -> bool { return node != e; }) !=
              i->second.end()) {
            std::stringstream str;
            str << "Unmerged variable found when jumping to block. \n"
                << "# Variable: " << *var;
            if (bound_) {
              str << "\n# Target block: " << *label_->block();
            }
            str << "\n# Current Block: ";
            state_->PrintCurrentBlock(str);
            FATAL("%s", str.str().c_str());
          }
#endif // DEBUG
        }
      }
    }
  }
}
References v8::internal::compiler::RawMachineLabel::block(), bound_, v8::internal::DCHECK(), DCHECK_NOT_NULL, FATAL, label_, merge_count_, v8::internal::compiler::CodeAssemblerState::raw_assembler_, state_, USE, v8::internal::compiler::CodeAssemblerVariable::Impl::value_, variable_merges_, variable_phis_, and v8::internal::compiler::CodeAssemblerState::variables_.
Referenced by v8::internal::compiler::CodeAssembler::Branch(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::HandleException(), and v8::internal::compiler::CodeAssembler::Switch().
operator=()
CodeAssemblerLabel& v8::internal::compiler::CodeAssemblerLabel::operator= (const CodeAssemblerLabel &) [delete]
UpdateVariablesAfterBind()
void v8::internal::compiler::CodeAssemblerLabel::UpdateVariablesAfterBind () [private]
Definition at line 1904 of file code-assembler.cc.
                                                  {
  // Make sure that all variables that have changed along any path up to this
  // point are marked as merge variables.
  for (auto var : state_->variables_) {
    Node* shared_value = nullptr;
    auto i = variable_merges_.find(var);
    if (i != variable_merges_.end()) {
      for (auto value : i->second) {
        DCHECK_NOT_NULL(value);
        if (value != shared_value) {
          if (shared_value == nullptr) {
            shared_value = value;
          } else {
            variable_phis_[var] = nullptr;
          }
        }
      }
    }
  }
  for (auto var : variable_phis_) {
    CodeAssemblerVariable::Impl* var_impl = var.first;
    auto i = variable_merges_.find(var_impl);
#if DEBUG
    bool not_found = i == variable_merges_.end();
    if (not_found || i->second.size() != merge_count_) {
      std::stringstream str;
      str << "A variable that has been marked as beeing merged at the label"
          << "\n# doesn't have a bound value along all of the paths that "
          << "\n# have been merged into the label up to this point."
          << "\n#"
          << "\n# This can happen in the following cases:"
          << "\n# - By explicitly marking it so in the label constructor"
          << "\n# - By having seen different bound values at branches"
          << "\n#"
          << "\n# Merge count: expected=" << merge_count_
          << " vs. found=" << (not_found ? 0 : i->second.size())
          << "\n# Variable: " << *var_impl
          << "\n# Current Block: " << *label_->block();
      FATAL("%s", str.str().c_str());
    }
#endif // DEBUG
    Node* phi = state_->raw_assembler_->Phi(
        var.first->rep_, static_cast<int>(merge_count_), &(i->second[0]));
    variable_phis_[var_impl] = phi;
  }
  // Bind all variables to a merge phi, the common value along all paths or
  // null.
  for (auto var : state_->variables_) {
    auto i = variable_phis_.find(var);
    if (i != variable_phis_.end()) {
      var->value_ = i->second;
    } else {
      auto j = variable_merges_.find(var);
      if (j != variable_merges_.end() && j->second.size() == merge_count_) {
        var->value_ = j->second.back();
      } else {
        var->value_ = nullptr;
      }
    }
  }
  bound_ = true;
}
References v8::internal::compiler::RawMachineLabel::block(), bound_, DCHECK_NOT_NULL, FATAL, label_, merge_count_, v8::internal::compiler::CodeAssemblerState::raw_assembler_, state_, v8::internal::value, variable_merges_, variable_phis_, and v8::internal::compiler::CodeAssemblerState::variables_.
Referenced by Bind().
Friends And Related Function Documentation
CodeAssembler
friend class CodeAssembler [friend]
Definition at line 1792 of file code-assembler.h.
Member Data Documentation
bound_
bool v8::internal::compiler::CodeAssemblerLabel::bound_ [private]
Definition at line 1801 of file code-assembler.h.
Referenced by Bind(), MergeVariables(), and UpdateVariablesAfterBind().
label_
RawMachineLabel* v8::internal::compiler::CodeAssemblerLabel::label_ [private]
Definition at line 1804 of file code-assembler.h.
Referenced by Bind(), v8::internal::compiler::CodeAssembler::Branch(), CodeAssemblerLabel(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::HandleException(), MergeVariables(), v8::internal::compiler::CodeAssembler::Switch(), UpdateVariablesAfterBind(), and ~CodeAssemblerLabel().
merge_count_
size_t v8::internal::compiler::CodeAssemblerLabel::merge_count_ [private]
Definition at line 1802 of file code-assembler.h.
Referenced by MergeVariables(), and UpdateVariablesAfterBind().
state_
CodeAssemblerState* v8::internal::compiler::CodeAssemblerLabel::state_ [private]
Definition at line 1803 of file code-assembler.h.
Referenced by Bind(), MergeVariables(), and UpdateVariablesAfterBind().
variable_merges_
std::map<CodeAssemblerVariable::Impl*, std::vector<Node*>, CodeAssemblerVariable::ImplComparator> v8::internal::compiler::CodeAssemblerLabel::variable_merges_ [private]
Definition at line 1814 of file code-assembler.h.
Referenced by MergeVariables(), and UpdateVariablesAfterBind().
variable_phis_
std::map<CodeAssemblerVariable::Impl*, Node*, CodeAssemblerVariable::ImplComparator> v8::internal::compiler::CodeAssemblerLabel::variable_phis_ [private]
Definition at line 1809 of file code-assembler.h.
Referenced by CodeAssemblerLabel(), MergeVariables(), and UpdateVariablesAfterBind().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/code-assembler.h
/mnt/V8SourceCode/src/compiler/code-assembler.cc