v8::internal::compiler::turboshaft::WasmShuffleAnalyzer Class Reference
#include <wasm-shuffle-reducer.h>
Public Member Functions
WasmShuffleAnalyzer (Zone *phase_zone, const Graph &input_graph)
V8_EXPORT_PRIVATE void Run ()
void Process (const Operation &op)
void ProcessUnary (const Simd128UnaryOp &unop)
void ProcessBinary (const Simd128BinopOp &binop)
void ProcessShuffle (const Simd128ShuffleOp &shuffle_op)
void ProcessShuffleOfShuffle (const Simd128ShuffleOp &shuffle_op, const Simd128ShuffleOp &shuffle, uint8_t lower_limit, uint8_t upper_limit)
bool ShouldReduce () const
const DemandedElementAnalysis::DemandedElementMap & ops_to_reduce () const
std::optional< DemandedElementAnalysis::LaneBitSet > DemandedByteLanes (const Operation *op) const
bool ShouldRewriteShuffleToLow (const Simd128ShuffleOp *shuffle) const
bool DoesShuffleIntoLowHalf (const Simd128ShuffleOp *shuffle) const
bool DoesShuffleIntoHighHalf (const Simd128ShuffleOp *shuffle) const
const Graph & input_graph () const
Private Attributes
Zone * phase_zone_
const Graph & input_graph_
DemandedElementAnalysis demanded_element_analysis {phase_zone_, input_graph_}
SmallShuffleVector shift_shuffles_ {phase_zone_}
SmallShuffleVector low_half_shuffles_ {phase_zone_}
SmallShuffleVector high_half_shuffles_ {phase_zone_}
Detailed Description
Definition at line 76 of file wasm-shuffle-reducer.h.
Constructor & Destructor Documentation
WasmShuffleAnalyzer()
v8::internal::compiler::turboshaft::WasmShuffleAnalyzer::WasmShuffleAnalyzer (Zone * phase_zone, const Graph & input_graph) [inline]
Definition at line 88 of file wasm-shuffle-reducer.h.
      : phase_zone_(phase_zone), input_graph_(input_graph) {
    Run();
  }
References Run().
Member Function Documentation
DemandedByteLanes()
std::optional<DemandedElementAnalysis::LaneBitSet> v8::internal::compiler::turboshaft::WasmShuffleAnalyzer::DemandedByteLanes (const Operation * op) const [inline]
Definition at line 124 of file wasm-shuffle-reducer.h.
                                 {
    for (const auto& [narrow_op, lanes] : ops_to_reduce()) {
      if (op == narrow_op) {
        return lanes;
      }
    }
    return {};
  }
References ops_to_reduce().
DoesShuffleIntoHighHalf()
bool v8::internal::compiler::turboshaft::WasmShuffleAnalyzer::DoesShuffleIntoHighHalf (const Simd128ShuffleOp * shuffle) const [inline]
Definition at line 166 of file wasm-shuffle-reducer.h.
                                                                      {
    for (auto half_shuffle : high_half_shuffles_) {
      if (half_shuffle == shuffle) {
        return true;
      }
    }
    return false;
  }
References high_half_shuffles_.
DoesShuffleIntoLowHalf()
bool v8::internal::compiler::turboshaft::WasmShuffleAnalyzer::DoesShuffleIntoLowHalf (const Simd128ShuffleOp * shuffle) const [inline]
Definition at line 155 of file wasm-shuffle-reducer.h.
                                                                     {
    for (auto half_shuffle : low_half_shuffles_) {
      if (half_shuffle == shuffle) {
        return true;
      }
    }
    return false;
  }
References low_half_shuffles_.
input_graph()
const Graph& v8::internal::compiler::turboshaft::WasmShuffleAnalyzer::input_graph () const [inline]
Definition at line 187 of file wasm-shuffle-reducer.h.
{ return input_graph_; }
References input_graph_.
Referenced by ProcessShuffle(), and Run().
ops_to_reduce()
const DemandedElementAnalysis::DemandedElementMap& v8::internal::compiler::turboshaft::WasmShuffleAnalyzer::ops_to_reduce () const [inline]
Definition at line 120 of file wasm-shuffle-reducer.h.
                                                                         {
    return demanded_element_analysis.demanded_elements();
  }
References demanded_element_analysis, and v8::internal::compiler::turboshaft::DemandedElementAnalysis::demanded_elements().
Referenced by DemandedByteLanes().
Process()
void v8::internal::compiler::turboshaft::WasmShuffleAnalyzer::Process (const Operation & op)
Definition at line 94 of file wasm-shuffle-reducer.cc.
                                                     {
  if (ShouldSkipOperation(op)) {
    return;
  }
  if (auto* unop = op.TryCast<Simd128UnaryOp>()) {
    ProcessUnary(*unop);
    return;
  }
  if (auto* binop = op.TryCast<Simd128BinopOp>()) {
    ProcessBinary(*binop);
    return;
  }
  if (auto* shuffle_op = op.TryCast<Simd128ShuffleOp>()) {
    ProcessShuffle(*shuffle_op);
    return;
  }
}
References ProcessBinary(), ProcessShuffle(), ProcessUnary(), v8::internal::compiler::turboshaft::ShouldSkipOperation(), and v8::internal::compiler::turboshaft::Operation::TryCast().
Referenced by Run().
ProcessBinary()
void v8::internal::compiler::turboshaft::WasmShuffleAnalyzer::ProcessBinary (const Simd128BinopOp & binop)
Definition at line 119 of file wasm-shuffle-reducer.cc.
                                                                   {
  demanded_element_analysis.AddBinaryOp(binop, DemandedElementAnalysis::k8x16);
}
References v8::internal::compiler::turboshaft::DemandedElementAnalysis::AddBinaryOp(), demanded_element_analysis, and v8::internal::compiler::turboshaft::DemandedElementAnalysis::k8x16.
Referenced by Process().
ProcessShuffle()
void v8::internal::compiler::turboshaft::WasmShuffleAnalyzer::ProcessShuffle (const Simd128ShuffleOp & shuffle_op)
Definition at line 381 of file wasm-shuffle-reducer.cc.
                                                                        {
  if (shuffle.kind != Simd128ShuffleOp::Kind::kI8x16) {
    return;
  }
  const Operation& left = input_graph().Get(shuffle.left());
  const Operation& right = input_graph().Get(shuffle.right());
#if V8_ENABLE_WASM_DEINTERLEAVED_MEM_OPS
  auto* load_left = left.TryCast<LoadOp>();
  auto* load_right = right.TryCast<LoadOp>();
  // TODO(sparker): Handle I8x8 shuffles, which will likely mean that the input
  // to the shuffles are Simd128LoadTransformOp::Load64Zero.
  if (load_left && load_right) {
    ProcessShuffleOfLoads(shuffle, *load_left, *load_right);
    return;
  }
#endif // V8_ENABLE_WASM_DEINTERLEAVED_MEM_OPS
  auto* shuffle_left = left.TryCast<Simd128ShuffleOp>();
  auto* shuffle_right = right.TryCast<Simd128ShuffleOp>();
  if (!shuffle_left && !shuffle_right) {
    return;
  }
  constexpr uint8_t left_lower = 0;
  constexpr uint8_t left_upper = 15;
  constexpr uint8_t right_lower = 16;
  constexpr uint8_t right_upper = 31;
  if (shuffle_left && shuffle_left->kind == Simd128ShuffleOp::Kind::kI8x16 &&
      shuffle_left->saturated_use_count.IsOne()) {
    ProcessShuffleOfShuffle(*shuffle_left, shuffle, left_lower, left_upper);
  }
  if (shuffle_right && shuffle_right->kind == Simd128ShuffleOp::Kind::kI8x16 &&
      shuffle_right->saturated_use_count.IsOne()) {
    ProcessShuffleOfShuffle(*shuffle_right, shuffle, right_lower, right_upper);
  }
}
References v8::internal::compiler::turboshaft::Graph::Get(), input_graph(), ProcessShuffleOfShuffle(), and v8::internal::compiler::turboshaft::Operation::TryCast().
Referenced by Process().
ProcessShuffleOfShuffle()
void v8::internal::compiler::turboshaft::WasmShuffleAnalyzer::ProcessShuffleOfShuffle (const Simd128ShuffleOp & shuffle_op, const Simd128ShuffleOp & shuffle, uint8_t lower_limit, uint8_t upper_limit)
Definition at line 123 of file wasm-shuffle-reducer.cc.
                                              {
  // Suppose we have two 16-byte shuffles:
  // |---a1---|---b3---|--------|--------| shuffle_op = (a, b)
  //
  // |---a1---|---b3---|---c?---|---c?---| shuffle = (shf0, c)
  //
  // As only half of the shf0 is used, it means that half the work of shf0 is
  // wasted so, here, we try to reduce shf0 to a more narrow kind. In the case
  // above we can simply truncate shf0.shuffle but there are other situations
  // which involve more work:
  //
  // In the following case, shf0.shuffle needs to be shifted left so that it
  // writes the required lanes to the low half of the result. This then means
  // that shf1.shuffle needs to be updated to read from the low half.
  //
  // |--------|--------|---a1---|---b3---| shuffle_op = (a, b)
  //
  // |---a1---|---b3---|---c?---|---c?---| shuffle = (shf0, c)
  //
  struct ShuffleHelper {
    explicit ShuffleHelper(const uint8_t* shuffle) : shuffle(shuffle) {}
    const uint8_t* begin() const { return shuffle; }
    const uint8_t* midpoint() const {
      constexpr size_t half_lanes = kSimd128Size / 2;
      return shuffle + half_lanes;
    }
    const uint8_t* end() const { return shuffle + kSimd128Size; }
    const uint8_t* shuffle;
  };
  ShuffleHelper view(shuffle.shuffle);
  // Test whether the low half of the shuffle is within the inclusive range.
  auto all_low_half = [&view](uint8_t lower_limit, uint8_t upper_limit) {
    return std::all_of(view.begin(), view.midpoint(),
                       [lower_limit, upper_limit](uint8_t i) {
                         return i >= lower_limit && i <= upper_limit;
                       });
  };
  // Test whether the high half of the shuffle is within the inclusive range.
  auto all_high_half = [&view](uint8_t lower_limit, uint8_t upper_limit) {
    return std::all_of(view.midpoint(), view.end(),
                       [lower_limit, upper_limit](uint8_t i) {
                         return i >= lower_limit && i <= upper_limit;
                       });
  };
  // Test whether none of the low half of the shuffle contains lanes within the
  // inclusive range.
  auto none_low_half = [&view](uint8_t lower_limit, uint8_t upper_limit) {
    return std::none_of(view.begin(), view.midpoint(),
                        [lower_limit, upper_limit](uint8_t i) {
                          return i >= lower_limit && i <= upper_limit;
                        });
  };
  // Test whether none of the high half of the shuffle contains lanes within the
  // inclusive range.
  auto none_high_half = [&view](uint8_t lower_limit, uint8_t upper_limit) {
    return std::none_of(view.midpoint(), view.end(),
                        [lower_limit, upper_limit](uint8_t i) {
                          return i >= lower_limit && i <= upper_limit;
                        });
  };
  // lower_ and upper_limit and set from the caller depending on whether we're
  // examining the left or right operand of shuffle. So, here we check if
  // shuffle_op is being exclusively shuffled into the low or high half using
  // either the lower and upper limits of {0,15} or {16,31}.
  bool shf_into_low_half = all_low_half(lower_limit, upper_limit) &&
                           none_high_half(lower_limit, upper_limit);
  bool shf_into_high_half = all_high_half(lower_limit, upper_limit) &&
                            none_low_half(lower_limit, upper_limit);
  DCHECK(!(shf_into_low_half && shf_into_high_half));
  constexpr size_t quarter_lanes = kSimd128Size / 4;
  if (shf_into_low_half) {
    if (all_low_half(lower_limit + quarter_lanes, upper_limit)) {
      // Low half of shuffle is sourced from the high half of shuffle_op.
      demanded_element_analysis.RecordOp(&shuffle_op,
                                         DemandedElementAnalysis::k8x8Low);
      shift_shuffles_.push_back(&shuffle_op);
      low_half_shuffles_.push_back(&shuffle);
    } else if (all_low_half(lower_limit, upper_limit - quarter_lanes)) {
      // Low half of shuffle is sourced from the low half of shuffle_op.
      demanded_element_analysis.RecordOp(&shuffle_op,
                                         DemandedElementAnalysis::k8x8Low);
    }
  } else if (shf_into_high_half) {
    if (all_high_half(lower_limit + quarter_lanes, upper_limit)) {
      // High half of shuffle is sourced from the high half of shuffle_op.
      demanded_element_analysis.RecordOp(&shuffle_op,
                                         DemandedElementAnalysis::k8x8Low);
      shift_shuffles_.push_back(&shuffle_op);
      high_half_shuffles_.push_back(&shuffle);
    } else if (all_high_half(lower_limit, upper_limit - quarter_lanes)) {
      // High half of shuffle is sourced from the low half of shuffle_op.
      demanded_element_analysis.RecordOp(&shuffle_op,
                                         DemandedElementAnalysis::k8x8Low);
    }
  }
}
References v8::base::all_of(), v8::internal::compiler::begin(), v8::internal::DCHECK(), demanded_element_analysis, v8::internal::compiler::end(), high_half_shuffles_, v8::internal::compiler::turboshaft::DemandedElementAnalysis::k8x8Low, v8::internal::kSimd128Size, low_half_shuffles_, v8::base::none_of(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), v8::internal::compiler::turboshaft::DemandedElementAnalysis::RecordOp(), and shift_shuffles_.
Referenced by ProcessShuffle().
ProcessUnary()
void v8::internal::compiler::turboshaft::WasmShuffleAnalyzer::ProcessUnary (const Simd128UnaryOp & unop)
Definition at line 115 of file wasm-shuffle-reducer.cc.
                                                                 {
  demanded_element_analysis.AddUnaryOp(unop, DemandedElementAnalysis::k8x16);
}
References v8::internal::compiler::turboshaft::DemandedElementAnalysis::AddUnaryOp(), demanded_element_analysis, and v8::internal::compiler::turboshaft::DemandedElementAnalysis::k8x16.
Referenced by Process().
Run()
void v8::internal::compiler::turboshaft::WasmShuffleAnalyzer::Run ()
Definition at line 81 of file wasm-shuffle-reducer.cc.
                              {
  for (uint32_t processed = input_graph().block_count(); processed > 0;
       --processed) {
    BlockIndex block_index = static_cast<BlockIndex>(processed - 1);
    const Block& block = input_graph().Get(block_index);
    auto idx_range = input_graph().OperationIndices(block);
    for (auto it = idx_range.rbegin(); it != idx_range.rend(); ++it) {
      const Operation& op = input_graph().Get(*it);
      Process(op);
    }
  }
}
References v8::internal::compiler::turboshaft::Graph::Get(), input_graph(), v8::internal::compiler::turboshaft::Graph::OperationIndices(), and Process().
Referenced by WasmShuffleAnalyzer().
ShouldReduce()
bool v8::internal::compiler::turboshaft::WasmShuffleAnalyzer::ShouldReduce () const [inline]
Definition at line 112 of file wasm-shuffle-reducer.h.
                            {
    return !demanded_element_analysis.demanded_elements().empty()
#if V8_ENABLE_WASM_DEINTERLEAVED_MEM_OPS
           || !deinterleave_load_candidates_.empty()
#endif
        ;
  }
References demanded_element_analysis, v8::internal::compiler::turboshaft::DemandedElementAnalysis::demanded_elements(), and v8::internal::ZoneVector< T >::empty().
Referenced by v8::internal::compiler::turboshaft::WasmSimdPhase::Run().
ShouldRewriteShuffleToLow()
bool v8::internal::compiler::turboshaft::WasmShuffleAnalyzer::ShouldRewriteShuffleToLow (const Simd128ShuffleOp * shuffle) const [inline]
Definition at line 137 of file wasm-shuffle-reducer.h.
                                                                        {
    for (auto shift_shuffle : shift_shuffles_) {
      if (shift_shuffle == shuffle) {
        return true;
      }
    }
    return false;
  }
References shift_shuffles_.
Member Data Documentation
demanded_element_analysis
DemandedElementAnalysis v8::internal::compiler::turboshaft::WasmShuffleAnalyzer::demanded_element_analysis {phase_zone_, input_graph_} [private]
Definition at line 209 of file wasm-shuffle-reducer.h.
Referenced by ops_to_reduce(), ProcessBinary(), ProcessShuffleOfShuffle(), ProcessUnary(), and ShouldReduce().
high_half_shuffles_
SmallShuffleVector v8::internal::compiler::turboshaft::WasmShuffleAnalyzer::high_half_shuffles_ {phase_zone_} [private]
Definition at line 212 of file wasm-shuffle-reducer.h.
Referenced by DoesShuffleIntoHighHalf(), and ProcessShuffleOfShuffle().
input_graph_
const Graph& v8::internal::compiler::turboshaft::WasmShuffleAnalyzer::input_graph_ [private]
Definition at line 208 of file wasm-shuffle-reducer.h.
Referenced by input_graph().
low_half_shuffles_
SmallShuffleVector v8::internal::compiler::turboshaft::WasmShuffleAnalyzer::low_half_shuffles_ {phase_zone_} [private]
Definition at line 211 of file wasm-shuffle-reducer.h.
Referenced by DoesShuffleIntoLowHalf(), and ProcessShuffleOfShuffle().
phase_zone_
Zone* v8::internal::compiler::turboshaft::WasmShuffleAnalyzer::phase_zone_ [private]
Definition at line 207 of file wasm-shuffle-reducer.h.
shift_shuffles_
SmallShuffleVector v8::internal::compiler::turboshaft::WasmShuffleAnalyzer::shift_shuffles_ {phase_zone_} [private]
Definition at line 210 of file wasm-shuffle-reducer.h.
Referenced by ProcessShuffleOfShuffle(), and ShouldRewriteShuffleToLow().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/wasm-shuffle-reducer.h
/mnt/V8SourceCode/src/compiler/turboshaft/wasm-shuffle-reducer.cc