v8::internal::IdentityMap< V, AllocationPolicy >::Iterator Class Reference
#include <identity-map.h>
Public Member Functions
Iterator & operator++ ()
Tagged< Object > key () const
V * entry () const
V * operator* ()
V * operator-> ()
bool operator!= (const Iterator &other) const
bool operator== (const Iterator &other) const
Private Member Functions
Iterator (IdentityMap *map, int index)
Private Attributes
IdentityMap * map_
int index_
Friends
class IdentityMap
Detailed Description
template<typename V, class AllocationPolicy>
class v8::internal::IdentityMap< V, AllocationPolicy >::Iterator
Definition at line 174 of file identity-map.h.
Constructor & Destructor Documentation
Iterator()
template<typename V , class AllocationPolicy >
v8::internal::IdentityMap< V, AllocationPolicy >::Iterator::Iterator (IdentityMap * map, int index) [inline], [private]
Definition at line 198 of file identity-map.h.
: map_(map), index_(index) {}
Member Function Documentation
entry()
template<typename V , class AllocationPolicy >
V* v8::internal::IdentityMap< V, AllocationPolicy >::Iterator::entry () const [inline]
Definition at line 184 of file identity-map.h.
                     {
      return reinterpret_cast<V*>(map_->EntryAtIndex(index_));
    }
References v8::internal::IdentityMapBase::EntryAtIndex(), v8::internal::IdentityMap< V, AllocationPolicy >::Iterator::index_, and v8::internal::IdentityMap< V, AllocationPolicy >::Iterator::map_.
Referenced by v8::internal::IdentityMap< V, AllocationPolicy >::Iterator::operator*(), and v8::internal::IdentityMap< V, AllocationPolicy >::Iterator::operator->().
key()
template<typename V , class AllocationPolicy >
Tagged<Object> v8::internal::IdentityMap< V, AllocationPolicy >::Iterator::key () const [inline]
Definition at line 181 of file identity-map.h.
                               {
      return Tagged<Object>(map_->KeyAtIndex(index_));
    }
References v8::internal::IdentityMap< V, AllocationPolicy >::Iterator::index_, v8::internal::IdentityMapBase::KeyAtIndex(), v8::internal::IdentityMap< V, AllocationPolicy >::Iterator::map_, and v8::internal::Tagged< Object >.
operator!=()
template<typename V , class AllocationPolicy >
bool v8::internal::IdentityMap< V, AllocationPolicy >::Iterator::operator!= (const Iterator & other) const [inline]
Definition at line 190 of file identity-map.h.
                                                 {
      return index_ != other.index_;
    }
References v8::internal::IdentityMap< V, AllocationPolicy >::Iterator::index_.
operator*()
template<typename V , class AllocationPolicy >
V* v8::internal::IdentityMap< V, AllocationPolicy >::Iterator::operator* () [inline]
Definition at line 188 of file identity-map.h.
{ return entry(); }
References v8::internal::IdentityMap< V, AllocationPolicy >::Iterator::entry().
operator++()
template<typename V , class AllocationPolicy >
Iterator& v8::internal::IdentityMap< V, AllocationPolicy >::Iterator::operator++ () [inline]
Definition at line 176 of file identity-map.h.
                           {
      index_ = map_->NextIndex(index_);
      return *this;
    }
References v8::internal::IdentityMap< V, AllocationPolicy >::Iterator::index_, v8::internal::IdentityMap< V, AllocationPolicy >::Iterator::map_, and v8::internal::IdentityMapBase::NextIndex().
operator->()
template<typename V , class AllocationPolicy >
V* v8::internal::IdentityMap< V, AllocationPolicy >::Iterator::operator-> () [inline]
Definition at line 189 of file identity-map.h.
{ return entry(); }
References v8::internal::IdentityMap< V, AllocationPolicy >::Iterator::entry().
operator==()
template<typename V , class AllocationPolicy >
bool v8::internal::IdentityMap< V, AllocationPolicy >::Iterator::operator== (const Iterator & other) const [inline]
Definition at line 193 of file identity-map.h.
                                                 {
      return index_ == other.index_;
    }
References v8::internal::IdentityMap< V, AllocationPolicy >::Iterator::index_.
Friends And Related Function Documentation
IdentityMap
template<typename V , class AllocationPolicy >
friend class IdentityMap [friend]
Definition at line 203 of file identity-map.h.
Member Data Documentation
index_
template<typename V , class AllocationPolicy >
int v8::internal::IdentityMap< V, AllocationPolicy >::Iterator::index_ [private]
Definition at line 201 of file identity-map.h.
Referenced by v8::internal::IdentityMap< V, AllocationPolicy >::Iterator::entry(), v8::internal::IdentityMap< V, AllocationPolicy >::Iterator::key(), v8::internal::IdentityMap< V, AllocationPolicy >::Iterator::operator!=(), v8::internal::IdentityMap< V, AllocationPolicy >::Iterator::operator++(), and v8::internal::IdentityMap< V, AllocationPolicy >::Iterator::operator==().
map_
template<typename V , class AllocationPolicy >
IdentityMap* v8::internal::IdentityMap< V, AllocationPolicy >::Iterator::map_ [private]
Definition at line 200 of file identity-map.h.
Referenced by v8::internal::IdentityMap< V, AllocationPolicy >::Iterator::entry(), v8::internal::IdentityMap< V, AllocationPolicy >::Iterator::key(), and v8::internal::IdentityMap< V, AllocationPolicy >::Iterator::operator++().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/utils/identity-map.h