v8::internal::maglev::LoadGlobal Class Reference
#include <maglev-ir.h>
Public Member Functions
LoadGlobal (uint64_t bitfield, compiler::NameRef name, const compiler::FeedbackSource &feedback, TypeofMode typeof_mode)
compiler::NameRef name () const
compiler::FeedbackSource feedback () const
TypeofMode typeof_mode () const
Input & context ()
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties = OpProperties::JSCall()
static constexpr Base::InputTypes kInputTypes {ValueRepresentation::kTagged}
Private Types
using Base = FixedInputValueNodeT< 1, LoadGlobal >
Private Attributes
const compiler::NameRef name_
const compiler::FeedbackSource feedback_
const TypeofMode typeof_mode_
Additional Inherited Members
Detailed Description
Definition at line 9233 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::LoadGlobal::Base = FixedInputValueNodeT<1, LoadGlobal> [private]
Definition at line 9234 of file maglev-ir.h.
Constructor & Destructor Documentation
LoadGlobal()
v8::internal::maglev::LoadGlobal::LoadGlobal (uint64_t bitfield, compiler::NameRef name, const compiler::FeedbackSource & feedback, TypeofMode typeof_mode) [inline], [explicit]
Definition at line 9237 of file maglev-ir.h.
      : Base(bitfield),
        name_(name),
        feedback_(feedback),
        typeof_mode_(typeof_mode) {}
Member Function Documentation
context()
Input& v8::internal::maglev::LoadGlobal::context () [inline]
Definition at line 9254 of file maglev-ir.h.
{ return input(0); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
feedback()
compiler::FeedbackSource v8::internal::maglev::LoadGlobal::feedback () const [inline]
Definition at line 9251 of file maglev-ir.h.
{ return feedback_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::LoadGlobal::GenerateCode (MaglevAssembler * , const ProcessingState &)
MaxCallStackArgs()
int v8::internal::maglev::LoadGlobal::MaxCallStackArgs () const
name()
compiler::NameRef v8::internal::maglev::LoadGlobal::name () const [inline]
Definition at line 9250 of file maglev-ir.h.
{ return name_; }
Referenced by PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::LoadGlobal::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 7947 of file maglev-ir.cc.
                                                                        {
  os << "(" << *name().object() << ")";
}
References name(), and v8::internal::compiler::NameRef::object().
SetValueLocationConstraints()
void v8::internal::maglev::LoadGlobal::SetValueLocationConstraints ()
typeof_mode()
TypeofMode v8::internal::maglev::LoadGlobal::typeof_mode () const [inline]
Definition at line 9252 of file maglev-ir.h.
{ return typeof_mode_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
Member Data Documentation
feedback_
const compiler::FeedbackSource v8::internal::maglev::LoadGlobal::feedback_ [private]
Definition at line 9263 of file maglev-ir.h.
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::LoadGlobal::kInputTypes {ValueRepresentation::kTagged} [static], [constexpr]
Definition at line 9248 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::LoadGlobal::kProperties = OpProperties::JSCall() [static], [constexpr]
Definition at line 9246 of file maglev-ir.h.
name_
const compiler::NameRef v8::internal::maglev::LoadGlobal::name_ [private]
Definition at line 9262 of file maglev-ir.h.
typeof_mode_
const TypeofMode v8::internal::maglev::LoadGlobal::typeof_mode_ [private]
Definition at line 9264 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc