v8::internal::DirectHandleVector< T > Class Template Reference
#include <handles.h>
Public Types
using value_type = DirectHandle< T >
using reference = value_type &
using const_reference = const value_type &
using size_type = size_t
using difference_type = ptrdiff_t
using iterator = internal::WrappedIterator< typename vector_type::iterator, value_type >
using const_iterator = internal::WrappedIterator< typename vector_type::const_iterator, const value_type >
Public Member Functions
template<typename IsolateT >
DirectHandleVector (IsolateT *isolate)
template<typename IsolateT >
DirectHandleVector (IsolateT *isolate, size_t n)
template<typename IsolateT >
DirectHandleVector (IsolateT *isolate, std::initializer_list< value_type > init)
iterator begin () noexcept
const_iterator begin () const noexcept
iterator end () noexcept
const_iterator end () const noexcept
size_t size () const noexcept
bool empty () const noexcept
void reserve (size_t n)
void shrink_to_fit ()
DirectHandle< T > & operator[] (size_t n)
const DirectHandle< T > & operator[] (size_t n) const
DirectHandle< T > & at (size_t n)
const DirectHandle< T > & at (size_t n) const
DirectHandle< T > & front ()
const DirectHandle< T > & front () const
DirectHandle< T > & back ()
const DirectHandle< T > & back () const
DirectHandle< T > * data () noexcept
const DirectHandle< T > * data () const noexcept
iterator insert (const_iterator pos, const DirectHandle< T > &value)
template<typename InputIt >
iterator insert (const_iterator pos, InputIt first, InputIt last)
iterator insert (const_iterator pos, std::initializer_list< DirectHandle< T >> init)
DirectHandleVector< T > & operator= (std::initializer_list< value_type > init)
void push_back (const DirectHandle< T > &x)
void pop_back ()
template<typename... Args>
void emplace_back (Args &&... args)
void clear () noexcept
void resize (size_t n)
void resize (size_t n, const value_type &value)
void swap (DirectHandleVector< T > &other)
Private Types
using element_type = internal::DirectHandleUnchecked< T >
using vector_type = std::vector< element_type >
Private Attributes
vector_type backing_
Friends
bool operator== (const DirectHandleVector< T > &x, const DirectHandleVector< T > &y)
bool operator!= (const DirectHandleVector< T > &x, const DirectHandleVector< T > &y)
bool operator< (const DirectHandleVector< T > &x, const DirectHandleVector< T > &y)
bool operator> (const DirectHandleVector< T > &x, const DirectHandleVector< T > &y)
bool operator<= (const DirectHandleVector< T > &x, const DirectHandleVector< T > &y)
bool operator>= (const DirectHandleVector< T > &x, const DirectHandleVector< T > &y)
Detailed Description
template<typename T>
class v8::internal::DirectHandleVector< T >
Definition at line 837 of file handles.h.
Member Typedef Documentation
const_iterator
template<typename T >
using v8::internal::DirectHandleVector< T >::const_iterator = internal::WrappedIterator<typename vector_type::const_iterator, const value_type>
Definition at line 862 of file handles.h.
const_reference
template<typename T >
using v8::internal::DirectHandleVector< T >::const_reference = const value_type&
Definition at line 857 of file handles.h.
difference_type
template<typename T >
using v8::internal::DirectHandleVector< T >::difference_type = ptrdiff_t
Definition at line 859 of file handles.h.
element_type
template<typename T >
using v8::internal::DirectHandleVector< T >::element_type = internal::DirectHandleUnchecked<T> [private]
Definition at line 839 of file handles.h.
iterator
template<typename T >
using v8::internal::DirectHandleVector< T >::iterator = internal::WrappedIterator<typename vector_type::iterator, value_type>
Definition at line 860 of file handles.h.
reference
template<typename T >
using v8::internal::DirectHandleVector< T >::reference = value_type&
Definition at line 856 of file handles.h.
size_type
template<typename T >
using v8::internal::DirectHandleVector< T >::size_type = size_t
Definition at line 858 of file handles.h.
value_type
template<typename T >
using v8::internal::DirectHandleVector< T >::value_type = DirectHandle<T>
Definition at line 855 of file handles.h.
vector_type
template<typename T >
using v8::internal::DirectHandleVector< T >::vector_type = std::vector<element_type> [private]
Definition at line 851 of file handles.h.
Constructor & Destructor Documentation
DirectHandleVector() [1/3]
template<typename T >
template<typename IsolateT >
v8::internal::DirectHandleVector< T >::DirectHandleVector (IsolateT * isolate) [inline], [explicit]
Definition at line 882 of file handles.h.
: backing_() {}
DirectHandleVector() [2/3]
template<typename T >
template<typename IsolateT >
v8::internal::DirectHandleVector< T >::DirectHandleVector (IsolateT * isolate, size_t n) [inline]
Definition at line 884 of file handles.h.
: backing_(n) {}
DirectHandleVector() [3/3]
template<typename T >
template<typename IsolateT >
v8::internal::DirectHandleVector< T >::DirectHandleVector (IsolateT * isolate, std::initializer_list< value_type > init) [inline]
Definition at line 886 of file handles.h.
      : backing_() {
    if (init.size() == 0) return;
    backing_.reserve(init.size());
    backing_.insert(backing_.end(), init.begin(), init.end());
  }
References v8::internal::DirectHandleVector< T >::backing_.
Member Function Documentation
at() [1/2]
template<typename T >
DirectHandle<T>& v8::internal::DirectHandleVector< T >::at (size_t n) [inline]
Definition at line 909 of file handles.h.
{ return backing_.at(n); }
References v8::internal::DirectHandleVector< T >::backing_.
at() [2/2]
template<typename T >
const DirectHandle<T>& v8::internal::DirectHandleVector< T >::at (size_t n) const [inline]
Definition at line 910 of file handles.h.
{ return backing_.at(n); }
References v8::internal::DirectHandleVector< T >::backing_.
back() [1/2]
template<typename T >
DirectHandle<T>& v8::internal::DirectHandleVector< T >::back () [inline]
Definition at line 914 of file handles.h.
{ return backing_.back(); }
References v8::internal::DirectHandleVector< T >::backing_.
back() [2/2]
template<typename T >
const DirectHandle<T>& v8::internal::DirectHandleVector< T >::back () const [inline]
Definition at line 915 of file handles.h.
{ return backing_.back(); }
References v8::internal::DirectHandleVector< T >::backing_.
begin() [1/2]
template<typename T >
const_iterator v8::internal::DirectHandleVector< T >::begin () const [inline], [noexcept]
Definition at line 895 of file handles.h.
                                        {
    return const_iterator(backing_.begin());
  }
References v8::internal::DirectHandleVector< T >::backing_.
begin() [2/2]
template<typename T >
iterator v8::internal::DirectHandleVector< T >::begin () [inline], [noexcept]
Definition at line 894 of file handles.h.
{ return iterator(backing_.begin()); }
References v8::internal::DirectHandleVector< T >::backing_.
Referenced by v8::internal::KeyedStoreIC::StoreElementPolymorphicHandlers().
clear()
template<typename T >
void v8::internal::DirectHandleVector< T >::clear () [inline], [noexcept]
Definition at line 949 of file handles.h.
{ backing_.clear(); }
References v8::internal::DirectHandleVector< T >::backing_.
data() [1/2]
template<typename T >
const DirectHandle<T>* v8::internal::DirectHandleVector< T >::data () const [inline], [noexcept]
Definition at line 918 of file handles.h.
{ return backing_.data(); }
References v8::internal::DirectHandleVector< T >::backing_.
data() [2/2]
template<typename T >
DirectHandle<T>* v8::internal::DirectHandleVector< T >::data () [inline], [noexcept]
Definition at line 917 of file handles.h.
{ return backing_.data(); }
References v8::internal::DirectHandleVector< T >::backing_.
Referenced by v8::internal::SharedHeapDeserializer::DeserializeStringTable(), and v8::internal::RUNTIME_FUNCTION().
emplace_back()
template<typename T >
template<typename... Args>
void v8::internal::DirectHandleVector< T >::emplace_back (Args &&... args) [inline]
Definition at line 945 of file handles.h.
                                    {
    backing_.push_back(value_type{std::forward<Args>(args)...});
  }
References v8::base::args, and v8::internal::DirectHandleVector< T >::backing_.
Referenced by v8::internal::SharedHeapDeserializer::DeserializeStringTable(), and v8::internal::Isolate::MaybeInitializeVectorListFromHeap().
empty()
template<typename T >
bool v8::internal::DirectHandleVector< T >::empty () const [inline], [noexcept]
Definition at line 902 of file handles.h.
{ return backing_.empty(); }
References v8::internal::DirectHandleVector< T >::backing_.
end() [1/2]
template<typename T >
const_iterator v8::internal::DirectHandleVector< T >::end () const [inline], [noexcept]
Definition at line 899 of file handles.h.
{ return const_iterator(backing_.end()); }
References v8::internal::DirectHandleVector< T >::backing_.
end() [2/2]
template<typename T >
iterator v8::internal::DirectHandleVector< T >::end () [inline], [noexcept]
Definition at line 898 of file handles.h.
{ return iterator(backing_.end()); }
References v8::internal::DirectHandleVector< T >::backing_.
Referenced by v8::internal::KeyedStoreIC::StoreElementPolymorphicHandlers().
front() [1/2]
template<typename T >
DirectHandle<T>& v8::internal::DirectHandleVector< T >::front () [inline]
Definition at line 912 of file handles.h.
{ return backing_.front(); }
References v8::internal::DirectHandleVector< T >::backing_.
front() [2/2]
template<typename T >
const DirectHandle<T>& v8::internal::DirectHandleVector< T >::front () const [inline]
Definition at line 913 of file handles.h.
{ return backing_.front(); }
References v8::internal::DirectHandleVector< T >::backing_.
insert() [1/3]
template<typename T >
iterator v8::internal::DirectHandleVector< T >::insert (const_iterator pos, const DirectHandle< T > & value) [inline]
Definition at line 920 of file handles.h.
                                                                    {
    return iterator(backing_.insert(pos.base(), value));
  }
References v8::internal::DirectHandleVector< T >::backing_, v8::internal::WrappedIterator< Iterator, ElementType >::base(), and v8::internal::value.
insert() [2/3]
template<typename T >
template<typename InputIt >
iterator v8::internal::DirectHandleVector< T >::insert (const_iterator pos, InputIt first, InputIt last) [inline]
Definition at line 925 of file handles.h.
                                                                   {
    return iterator(backing_.insert(pos.base(), first, last));
  }
References v8::internal::DirectHandleVector< T >::backing_, and v8::internal::WrappedIterator< Iterator, ElementType >::base().
insert() [3/3]
template<typename T >
iterator v8::internal::DirectHandleVector< T >::insert (const_iterator pos, std::initializer_list< DirectHandle< T >> init) [inline]
Definition at line 929 of file handles.h.
                                                             {
    return iterator(backing_.insert(pos.base(), init.begin(), init.end()));
  }
References v8::internal::DirectHandleVector< T >::backing_, and v8::internal::WrappedIterator< Iterator, ElementType >::base().
operator=()
template<typename T >
DirectHandleVector<T>& v8::internal::DirectHandleVector< T >::operator= (std::initializer_list< value_type > init) [inline]
Definition at line 934 of file handles.h.
                                                                         {
    backing_.clear();
    backing_.reserve(init.size());
    backing_.insert(backing_.end(), init.begin(), init.end());
    return *this;
  }
References v8::internal::DirectHandleVector< T >::backing_.
operator[]() [1/2]
template<typename T >
DirectHandle<T>& v8::internal::DirectHandleVector< T >::operator[] (size_t n) [inline]
Definition at line 906 of file handles.h.
{ return backing_[n]; }
References v8::internal::DirectHandleVector< T >::backing_.
operator[]() [2/2]
template<typename T >
const DirectHandle<T>& v8::internal::DirectHandleVector< T >::operator[] (size_t n) const [inline]
Definition at line 907 of file handles.h.
{ return backing_[n]; }
References v8::internal::DirectHandleVector< T >::backing_.
pop_back()
template<typename T >
void v8::internal::DirectHandleVector< T >::pop_back () [inline]
Definition at line 942 of file handles.h.
{ backing_.pop_back(); }
References v8::internal::DirectHandleVector< T >::backing_.
push_back()
template<typename T >
void v8::internal::DirectHandleVector< T >::push_back (const DirectHandle< T > & x) [inline]
Definition at line 941 of file handles.h.
{ backing_.push_back(x); }
References v8::internal::DirectHandleVector< T >::backing_.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::BeginExecution(), v8::internal::anonymous_namespace{builtins-struct.cc}::CollectFieldsAndElements(), v8::internal::wasm::GetCustomSections(), v8::internal::SourceTextModule::GetStalledTopLevelAwaitMessages(), v8::internal::ClosureFeedbackCellArray::New(), v8::internal::ValueDeserializer::ReadJSObjectProperties(), and v8::internal::KeyedStoreIC::StoreElementPolymorphicHandlers().
reserve()
template<typename T >
void v8::internal::DirectHandleVector< T >::reserve (size_t n) [inline]
Definition at line 903 of file handles.h.
{ backing_.reserve(n); }
References v8::internal::DirectHandleVector< T >::backing_.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::BeginExecution(), v8::internal::SharedHeapDeserializer::DeserializeStringTable(), v8::internal::SourceTextModule::GetStalledTopLevelAwaitMessages(), v8::internal::ClosureFeedbackCellArray::New(), v8::internal::ValueDeserializer::ReadJSObjectProperties(), and v8::internal::KeyedStoreIC::StoreElementPolymorphicHandlers().
resize() [1/2]
template<typename T >
void v8::internal::DirectHandleVector< T >::resize (size_t n) [inline]
Definition at line 950 of file handles.h.
{ backing_.resize(n); }
References v8::internal::DirectHandleVector< T >::backing_.
resize() [2/2]
template<typename T >
void v8::internal::DirectHandleVector< T >::resize (size_t n, const value_type & value) [inline]
Definition at line 951 of file handles.h.
{ backing_.resize(n, value); }
References v8::internal::DirectHandleVector< T >::backing_, and v8::internal::value.
shrink_to_fit()
template<typename T >
void v8::internal::DirectHandleVector< T >::shrink_to_fit () [inline]
Definition at line 904 of file handles.h.
{ backing_.shrink_to_fit(); }
References v8::internal::DirectHandleVector< T >::backing_.
size()
template<typename T >
size_t v8::internal::DirectHandleVector< T >::size () const [inline], [noexcept]
Definition at line 901 of file handles.h.
{ return backing_.size(); }
References v8::internal::DirectHandleVector< T >::backing_.
Referenced by v8::internal::SharedHeapDeserializer::DeserializeStringTable(), v8::internal::anonymous_namespace{builtins-function.cc}::DoFunctionBind(), v8::internal::wasm::GetCustomSections(), v8::internal::SourceTextModule::GetStalledTopLevelAwaitMessages(), v8::internal::Isolate::MaybeInitializeVectorListFromHeap(), v8::internal::ValueDeserializer::ReadJSObjectProperties(), and v8::internal::RUNTIME_FUNCTION().
swap()
template<typename T >
void v8::internal::DirectHandleVector< T >::swap (DirectHandleVector< T > & other) [inline]
Definition at line 952 of file handles.h.
{ backing_.swap(other.backing_); }
References v8::internal::DirectHandleVector< T >::backing_.
Friends And Related Function Documentation
operator!=
template<typename T >
bool operator!= (const DirectHandleVector< T > & x, const DirectHandleVector< T > & y) [friend]
Definition at line 958 of file handles.h.
                                                         {
    return x.backing_ != y.backing_;
  }
operator<
template<typename T >
bool operator< (const DirectHandleVector< T > & x, const DirectHandleVector< T > & y) [friend]
Definition at line 962 of file handles.h.
                                                        {
    return x.backing_ < y.backing_;
  }
operator<=
template<typename T >
bool operator<= (const DirectHandleVector< T > & x, const DirectHandleVector< T > & y) [friend]
Definition at line 970 of file handles.h.
                                                         {
    return x.backing_ <= y.backing_;
  }
operator==
template<typename T >
bool operator== (const DirectHandleVector< T > & x, const DirectHandleVector< T > & y) [friend]
Definition at line 954 of file handles.h.
                                                         {
    return x.backing_ == y.backing_;
  }
operator>
template<typename T >
bool operator> (const DirectHandleVector< T > & x, const DirectHandleVector< T > & y) [friend]
Definition at line 966 of file handles.h.
                                                        {
    return x.backing_ > y.backing_;
  }
operator>=
template<typename T >
bool operator>= (const DirectHandleVector< T > & x, const DirectHandleVector< T > & y) [friend]
Definition at line 974 of file handles.h.
                                                         {
    return x.backing_ >= y.backing_;
  }
Member Data Documentation
backing_
template<typename T >
vector_type v8::internal::DirectHandleVector< T >::backing_ [private]
Definition at line 980 of file handles.h.
Referenced by v8::internal::DirectHandleVector< T >::at(), v8::internal::DirectHandleVector< T >::back(), v8::internal::DirectHandleVector< T >::begin(), v8::internal::DirectHandleVector< T >::clear(), v8::internal::DirectHandleVector< T >::data(), v8::internal::DirectHandleVector< T >::DirectHandleVector(), v8::internal::DirectHandleVector< T >::emplace_back(), v8::internal::DirectHandleVector< T >::empty(), v8::internal::DirectHandleVector< T >::end(), v8::internal::DirectHandleVector< T >::front(), v8::internal::DirectHandleVector< T >::insert(), v8::internal::DirectHandleVector< T >::operator=(), v8::internal::DirectHandleVector< T >::operator[](), v8::internal::DirectHandleVector< T >::pop_back(), v8::internal::DirectHandleVector< T >::push_back(), v8::internal::DirectHandleVector< T >::reserve(), v8::internal::DirectHandleVector< T >::resize(), v8::internal::DirectHandleVector< T >::shrink_to_fit(), v8::internal::DirectHandleVector< T >::size(), and v8::internal::DirectHandleVector< T >::swap().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/handles/handles.h