v8::TracedReferenceBase Class Reference
An indirect handle, where the indirect pointer points to a GlobalHandles node.
#include <v8-traced-handle.h>
Public Member Functions
void Reset ()
If non-empty, destroy the underlying storage cell.
Local< Data > Get (Isolate *isolate) const
Construct a Local<Data> from this handle.
bool IsEmptyThreadSafe () const
Returns true if this TracedReference is empty, i.e., has not been assigned an object.
Protected Member Functions
TracedReferenceBase ()=default
void SetSlotThreadSafe (internal::Address *new_val)
Update this reference in a thread-safe way.
const internal::Address * GetSlotThreadSafe () const
Get this reference in a thread-safe way.
void CheckValue () const
Friends
class internal::BasicTracedReferenceExtractor
template<typename F >
class Local
template<typename U >
bool operator== (const TracedReferenceBase &, const Local< U > &)
bool operator== (const TracedReferenceBase &, const TracedReferenceBase &)
Detailed Description
An indirect handle, where the indirect pointer points to a GlobalHandles node.
Definition at line 54 of file v8-traced-handle.h.
Constructor & Destructor Documentation
TracedReferenceBase()
v8::TracedReferenceBase::TracedReferenceBase () [inline], [protected], [default]
Member Function Documentation
CheckValue()
void v8::TracedReferenceBase::CheckValue () const [protected]
Definition at line 11862 of file api.cc.
                                           {
#ifdef V8_HOST_ARCH_64_BIT
  if (IsEmpty()) return;
  CHECK_NE(internal::kGlobalHandleZapValue,
           *reinterpret_cast<uint64_t*>(slot()));
#endif // V8_HOST_ARCH_64_BIT
}
References CHECK_NE, v8::api_internal::IndirectHandleBase::IsEmpty(), v8::internal::kGlobalHandleZapValue, and v8::api_internal::IndirectHandleBase::slot().
Get()
Local<Data> v8::TracedReferenceBase::Get (Isolate * isolate) const [inline]
Construct a Local<Data> from this handle.
Definition at line 68 of file v8-traced-handle.h.
                                                    {
    if (IsEmpty()) return Local<Data>();
    return Local<Data>::New(isolate, this->value<Data>());
  }
References v8::api_internal::IndirectHandleBase::IsEmpty(), and v8::Local< T >::New().
Referenced by v8::internal::CppGraphBuilderImpl::AddEdge(), and v8::internal::CppGraphBuilderImpl::VisitForVisibility().
GetSlotThreadSafe()
const internal::Address* v8::TracedReferenceBase::GetSlotThreadSafe () const [inline], [protected]
Get this reference in a thread-safe way.
Definition at line 93 of file v8-traced-handle.h.
                                                   {
    return reinterpret_cast<const std::atomic<internal::Address*>*>(&slot())
        ->load(std::memory_order_relaxed);
  }
References v8::api_internal::IndirectHandleBase::slot().
Referenced by v8::internal::BasicTracedReferenceExtractor::GetObjectSlotForMarking(), and IsEmptyThreadSafe().
IsEmptyThreadSafe()
bool v8::TracedReferenceBase::IsEmptyThreadSafe () const [inline]
Returns true if this TracedReference is empty, i.e., has not been assigned an object.
This version of IsEmpty is thread-safe.
Definition at line 77 of file v8-traced-handle.h.
{ return GetSlotThreadSafe() == nullptr; }
References GetSlotThreadSafe().
Referenced by v8::JSVisitor::Trace().
Reset()
void v8::TracedReferenceBase::Reset () [inline]
If non-empty, destroy the underlying storage cell.
|IsEmpty| will return true after this call.
Definition at line 309 of file v8-traced-handle.h.
                                {
  if (V8_UNLIKELY(IsEmpty())) {
    return;
  }
  internal::DisposeTracedReference(slot());
  SetSlotThreadSafe(nullptr);
}
References v8::internal::DisposeTracedReference(), v8::api_internal::IndirectHandleBase::IsEmpty(), SetSlotThreadSafe(), v8::api_internal::IndirectHandleBase::slot(), and V8_UNLIKELY.
SetSlotThreadSafe()
void v8::TracedReferenceBase::SetSlotThreadSafe (internal::Address * new_val) [inline], [protected]
Update this reference in a thread-safe way.
Definition at line 85 of file v8-traced-handle.h.
                                                   {
    reinterpret_cast<std::atomic<internal::Address*>*>(&slot())->store(
        new_val, std::memory_order_relaxed);
  }
References v8::api_internal::IndirectHandleBase::slot(), and store().
Referenced by Reset().
Friends And Related Function Documentation
internal::BasicTracedReferenceExtractor
friend class internal::BasicTracedReferenceExtractor [friend]
Definition at line 100 of file v8-traced-handle.h.
Local
template<typename F >
friend class Local [friend]
Definition at line 102 of file v8-traced-handle.h.
operator== [1/2]
template<typename U >
bool operator== (const TracedReferenceBase & lhs, const Local< U > & rhs) [friend]
Definition at line 323 of file v8-traced-handle.h.
                                                 {
  return internal::HandleHelper::EqualHandles(lhs, rhs);
}
operator== [2/2]
bool operator== (const TracedReferenceBase & lhs, const TracedReferenceBase & rhs) [friend]
Definition at line 317 of file v8-traced-handle.h.
                                                          {
  return internal::HandleHelper::EqualHandles(lhs, rhs);
}
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-traced-handle.h
/mnt/V8SourceCode/src/api/api.cc