v8::internal::compiler::JSGraph Class Reference
#include <js-graph.h>
Public Member Functions
JSGraph (Isolate *isolate, TFGraph *graph, CommonOperatorBuilder *common, JSOperatorBuilder *javascript, SimplifiedOperatorBuilder *simplified, MachineOperatorBuilder *machine)
JSGraph (const JSGraph &)=delete
JSGraph & operator= (const JSGraph &)=delete
Node * CEntryStubConstant (int result_size, ArgvMode argv_mode=ArgvMode::kStack, bool builtin_exit_frame=false)
TNode< Hole > PaddingConstant ()
TNode< Number > NoContextConstant ()
Node * HeapConstantNoHole (Handle< HeapObject > value)
Node * HeapConstantMaybeHole (Handle< HeapObject > value)
Node * HeapConstantHole (Handle< HeapObject > value)
Node * TrustedHeapConstant (Handle< HeapObject > value)
Node * ConstantNoHole (ObjectRef ref, JSHeapBroker *broker)
Node * ConstantMaybeHole (ObjectRef ref, JSHeapBroker *broker)
Node * ConstantMaybeHole (double value)
Node * ConstantNoHole (double value)
Node * ConstantMutableHeapNumber (HeapNumberRef ref, JSHeapBroker *broker)
TNode< Boolean > BooleanConstant (bool is_true)
Node * SmiConstant (int32_t immediate)
JSOperatorBuilder * javascript () const
SimplifiedOperatorBuilder * simplified () const
Isolate * isolate () const
Factory * factory () const
void GetCachedNodes (NodeVector *nodes)
Private Member Functions
Node * NumberConstant (double value)
Node * Constant (ObjectRef value, JSHeapBroker *broker)
Private Attributes
Isolate * isolate_
JSOperatorBuilder * javascript_
SimplifiedOperatorBuilder * simplified_
Additional Inherited Members
Detailed Description
Definition at line 27 of file js-graph.h.
Constructor & Destructor Documentation
JSGraph() [1/2]
v8::internal::compiler::JSGraph::JSGraph (Isolate * isolate, TFGraph * graph, CommonOperatorBuilder * common, JSOperatorBuilder * javascript, SimplifiedOperatorBuilder * simplified, MachineOperatorBuilder * machine) [inline]
Definition at line 29 of file js-graph.h.
      : MachineGraph(graph, common, machine),
        isolate_(isolate),
        javascript_(javascript),
        simplified_(simplified) {}
JSGraph() [2/2]
v8::internal::compiler::JSGraph::JSGraph (const JSGraph &) [delete]
Member Function Documentation
BooleanConstant()
TNode<Boolean> v8::internal::compiler::JSGraph::BooleanConstant (bool is_true) [inline]
Definition at line 94 of file js-graph.h.
                                               {
    return is_true ? TNode<Boolean>(TrueConstant())
                   : TNode<Boolean>(FalseConstant());
  }
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceJSFindNonDefaultConstructorOrConstruct(), and v8::internal::compiler::JSNativeContextSpecialization::ReduceJSHasInPrototypeChain().
CEntryStubConstant()
Node * v8::internal::compiler::JSGraph::CEntryStubConstant (int result_size, ArgvMode argv_mode = ArgvMode::kStack, bool builtin_exit_frame = false)
Definition at line 23 of file js-graph.cc.
                                                           {
  if (argv_mode == ArgvMode::kStack) {
    DCHECK(result_size >= 1 && result_size <= 3);
    if (!builtin_exit_frame) {
      Node** ptr = nullptr;
      if (result_size == 1) {
        ptr = &CEntryStub1Constant_;
      } else if (result_size == 2) {
        ptr = &CEntryStub2Constant_;
      } else {
        DCHECK_EQ(3, result_size);
        ptr = &CEntryStub3Constant_;
      }
      return GET_CACHED_FIELD(
          ptr, HeapConstantNoHole(CodeFactory::CEntry(
                   isolate(), result_size, argv_mode, builtin_exit_frame)));
    }
    Node** ptr = builtin_exit_frame ? &CEntryStub1WithBuiltinExitFrameConstant_
                                    : &CEntryStub1Constant_;
    return GET_CACHED_FIELD(
        ptr, HeapConstantNoHole(CodeFactory::CEntry(
                 isolate(), result_size, argv_mode, builtin_exit_frame)));
  }
  return HeapConstantNoHole(CodeFactory::CEntry(isolate(), result_size,
                                                argv_mode, builtin_exit_frame));
}
References v8::internal::CodeFactory::CEntry(), v8::internal::DCHECK(), DCHECK_EQ, GET_CACHED_FIELD, HeapConstantNoHole(), isolate(), and v8::internal::kStack.
Referenced by v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeShift(), and v8::internal::compiler::anonymous_namespace{js-typed-lowering.cc}::ReduceBuiltin().
Constant()
Node * v8::internal::compiler::JSGraph::Constant (ObjectRef value, JSHeapBroker * broker) [private]
Definition at line 68 of file js-graph.cc.
                                                           {
  if (ref.IsSmi()) return ConstantMaybeHole(ref.AsSmi());
  if (ref.IsHeapNumber()) {
    return ConstantMaybeHole(ref.AsHeapNumber().value());
  }
  switch (ref.AsHeapObject().GetHeapObjectType(broker).hole_type()) {
    case HoleType::kNone:
      break;
    case HoleType::kGeneric:
      return TheHoleConstant();
    case HoleType::kPropertyCellHole:
      return PropertyCellHoleConstant();
    case HoleType::kHashTableHole:
      return HashTableHoleConstant();
    case HoleType::kPromiseHole:
      return PromiseHoleConstant();
    case HoleType::kOptimizedOut:
      return OptimizedOutConstant();
    case HoleType::kStaleRegister:
      return StaleRegisterConstant();
    case HoleType::kUninitialized:
      return UninitializedConstant();
    case HoleType::kException:
    case HoleType::kTerminationException:
    case HoleType::kArgumentsMarker:
    case HoleType::kSelfReferenceMarker:
    case HoleType::kBasicBlockCountersMarker:
    case HoleType::kUndefinedContextCell:
      UNREACHABLE();
  }
  OddballType oddball_type =
      ref.AsHeapObject().GetHeapObjectType(broker).oddball_type();
  ReadOnlyRoots roots(isolate());
  if (oddball_type == OddballType::kUndefined) {
    DCHECK(IsUndefined(*ref.object(), roots));
    return UndefinedConstant();
  } else if (oddball_type == OddballType::kNull) {
    DCHECK(IsNull(*ref.object(), roots));
    return NullConstant();
  } else if (oddball_type == OddballType::kBoolean) {
    if (IsTrue(*ref.object(), roots)) {
      return TrueConstant();
    } else {
      DCHECK(IsFalse(*ref.object(), roots));
      return FalseConstant();
    }
  } else {
    return HeapConstantNoHole(ref.AsHeapObject().object());
  }
}
References broker(), ConstantMaybeHole(), v8::internal::DCHECK(), HeapConstantNoHole(), v8::internal::IsNull(), isolate(), v8::internal::compiler::kBoolean, v8::debug::kException, v8::internal::compiler::kGeneric, v8::internal::compiler::kNone, v8::internal::compiler::kNull, v8::internal::compiler::kUndefined, v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant(), and v8::internal::UNREACHABLE().
Referenced by ConstantMaybeHole(), and ConstantNoHole().
ConstantMaybeHole() [1/2]
Node * v8::internal::compiler::JSGraph::ConstantMaybeHole (double value)
Definition at line 131 of file js-graph.cc.
                                             {
  if (base::bit_cast<int64_t>(value) == base::bit_cast<int64_t>(0.0))
    return ZeroConstant();
  if (base::bit_cast<int64_t>(value) == base::bit_cast<int64_t>(1.0))
    return OneConstant();
  return NumberConstant(value);
}
References NumberConstant(), and v8::internal::value.
ConstantMaybeHole() [2/2]
Node * v8::internal::compiler::JSGraph::ConstantMaybeHole (ObjectRef ref, JSHeapBroker * broker)
Definition at line 64 of file js-graph.cc.
                                                                    {
  return Constant(ref, broker);
}
References broker(), and Constant().
Referenced by Constant(), ConstantNoHole(), v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral(), and v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteralElements().
ConstantMutableHeapNumber()
Node * v8::internal::compiler::JSGraph::ConstantMutableHeapNumber (HeapNumberRef ref, JSHeapBroker * broker)
Definition at line 121 of file js-graph.cc.
                                                               {
  return HeapConstantNoHole(ref.AsHeapObject().object());
}
References HeapConstantNoHole(), and v8::internal::compiler::HeapNumberRef::object().
ConstantNoHole() [1/2]
Node * v8::internal::compiler::JSGraph::ConstantNoHole (double value)
Definition at line 126 of file js-graph.cc.
                                          {
  CHECK_NE(base::bit_cast<uint64_t>(value), kHoleNanInt64);
  return ConstantMaybeHole(value);
}
References CHECK_NE, ConstantMaybeHole(), v8::internal::kHoleNanInt64, and v8::internal::value.
ConstantNoHole() [2/2]
Node * v8::internal::compiler::JSGraph::ConstantNoHole (ObjectRef ref, JSHeapBroker * broker)
Definition at line 51 of file js-graph.cc.
                                                                 {
  // This CHECK is security critical, we should never observe a hole
  // here. Please do not remove this! (crbug.com/1486789)
  CHECK(ref.IsSmi() || ref.IsHeapNumber() ||
        ref.AsHeapObject().GetHeapObjectType(broker).hole_type() ==
            HoleType::kNone);
  if (IsThinString(*ref.object())) {
    ref = MakeRefAssumeMemoryFence(broker,
                                   Cast<ThinString>(*ref.object())->actual());
  }
  return Constant(ref, broker);
}
References broker(), CHECK, Constant(), v8::internal::InstanceTypeChecker::IsThinString(), v8::internal::compiler::kNone, and v8::internal::compiler::MakeRefAssumeMemoryFence().
Referenced by v8::internal::compiler::JSCreateLowering::AllocateElements(), v8::internal::compiler::PropertyAccessBuilder::BuildCheckValue(), v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccessForTypedArrayOrRabGsabTypedArray(), v8::internal::compiler::JSTypedLowering::BuildGetModuleCell(), v8::internal::compiler::BytecodeGraphBuilder::BuildLoadFeedbackCell(), v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyLoad(), v8::internal::compiler::BytecodeGraphBuilder::CreateFeedbackVectorNode(), v8::internal::compiler::CreateJavaScriptBuiltinContinuationFrameState(), v8::internal::compiler::BytecodeGraphBuilder::CreateNativeContextNode(), v8::internal::compiler::JSInliningHeuristic::CreateOrReuseDispatch(), v8::internal::compiler::JSInliner::DetermineCallContext(), v8::internal::compiler::EscapeAnalysisReducer::Finalize(), v8::internal::compiler::PropertyAccessBuilder::FoldLoadDictPrototypeConstant(), v8::internal::compiler::JSNativeContextSpecialization::InlineApiCall(), v8::internal::compiler::JSNativeContextSpecialization::InlinePropertyGetterCall(), v8::internal::compiler::JSNativeContextSpecialization::InlinePropertySetterCall(), v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::PushRegularApiCallInputs(), v8::internal::compiler::JSCallReducer::ReduceArrayIteratorPrototypeNext(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeShift(), v8::internal::compiler::anonymous_namespace{js-typed-lowering.cc}::ReduceBuiltin(), v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpread(), v8::internal::compiler::JSCallReducer::ReduceDataViewAccess(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementLoadFromHeapConstant(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeCall(), v8::internal::compiler::JSIntrinsicLowering::ReduceGeneratorClose(), v8::internal::compiler::JSNativeContextSpecialization::ReduceGlobalAccess(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSInliner::ReduceJSCall(), v8::internal::compiler::JSTypedLowering::ReduceJSCall(), v8::internal::compiler::JSCallReducer::ReduceJSConstruct(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArguments(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArray(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateClosure(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateEmptyLiteralObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateIterResultObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateKeyValueArray(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateStringIterator(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSFindNonDefaultConstructorOrConstruct(), v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorRestoreContinuation(), v8::internal::compiler::JSContextSpecialization::ReduceJSGetImportMeta(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetSuperConstructor(), v8::internal::compiler::JSCreateLowering::ReduceJSGetTemplateObject(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf(), v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContext(), v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContextNoCell(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadGlobal(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadNamed(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSOrdinaryHasInstance(), v8::internal::compiler::JSContextSpecialization::ReduceJSStoreContext(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSStoreGlobal(), v8::internal::compiler::JSTypedLowering::ReduceJSToLength(), v8::internal::compiler::TypedOptimization::ReduceLoadField(), v8::internal::compiler::JSCallReducer::ReduceMathClz32(), v8::internal::compiler::JSNativeContextSpecialization::ReduceMegaDOMPropertyAccess(), v8::internal::compiler::JSCreateLowering::ReduceNewArray(), v8::internal::compiler::JSCallReducer::ReduceObjectGetPrototype(), v8::internal::compiler::JSContextSpecialization::ReduceParameter(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeCatch(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeFinally(), v8::internal::compiler::TypedOptimization::ReduceStringLength(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeEndsWith(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeStartsWith(), v8::internal::compiler::TypedOptimization::ReduceTypedArrayLength(), v8::internal::compiler::JSTypeHintLowering::ReduceUnaryOperation(), v8::internal::compiler::PropertyAccessBuilder::ResolveHolder(), v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteralElements(), v8::internal::compiler::PropertyAccessBuilder::TryFoldLoadConstantDataField(), v8::internal::compiler::anonymous_namespace{constant-folding-reducer.cc}::TryGetConstant(), v8::internal::compiler::JSCallReducer::TryReduceJSCallMathMinMaxWithArrayLike(), and v8::internal::compiler::TypedOptimization::TryReduceStringComparisonOfStringFromSingleCharCode().
factory()
Factory* v8::internal::compiler::JSGraph::factory () const [inline]
Definition at line 107 of file js-graph.h.
{ return isolate()->factory(); }
Referenced by v8::internal::compiler::JSTypedLowering::factory(), and v8::internal::compiler::LoadElimination::factory().
GetCachedNodes()
void v8::internal::compiler::JSGraph::GetCachedNodes (NodeVector * nodes)
Definition at line 181 of file js-graph.cc.
                                              {
  cache_.GetCachedNodes(nodes);
#define DO_CACHED_FIELD(name, ...) \
  if (name##_) nodes->push_back(name##_);
  CACHED_GLOBAL_LIST(DO_CACHED_FIELD)
  CACHED_CENTRY_LIST(DO_CACHED_FIELD)
#undef DO_CACHED_FIELD
}
References v8::internal::compiler::MachineGraph::cache_, CACHED_CENTRY_LIST, CACHED_GLOBAL_LIST, DO_CACHED_FIELD, and v8::internal::compiler::CommonNodeCache::GetCachedNodes().
HeapConstantHole()
Node * v8::internal::compiler::JSGraph::HeapConstantHole (Handle< HeapObject > value)
Definition at line 164 of file js-graph.cc.
                                                        {
  DCHECK(IsAnyHole(*value));
  Node** loc = cache_.FindHeapConstant(value);
  if (*loc == nullptr) {
    *loc = graph()->NewNode(common()->HeapConstant(value));
  }
  return *loc;
}
References v8::internal::compiler::MachineGraph::cache_, v8::internal::compiler::MachineGraph::common(), v8::internal::DCHECK(), v8::internal::compiler::CommonNodeCache::FindHeapConstant(), v8::internal::compiler::MachineGraph::graph(), v8::internal::IsAnyHole(), v8::internal::loc, v8::internal::compiler::TFGraph::NewNode(), and v8::internal::value.
HeapConstantMaybeHole()
Node * v8::internal::compiler::JSGraph::HeapConstantMaybeHole (Handle< HeapObject > value)
Definition at line 156 of file js-graph.cc.
                                                             {
  Node** loc = cache_.FindHeapConstant(value);
  if (*loc == nullptr) {
    *loc = graph()->NewNode(common()->HeapConstant(value));
  }
  return *loc;
}
References v8::internal::compiler::MachineGraph::cache_, v8::internal::compiler::MachineGraph::common(), v8::internal::compiler::CommonNodeCache::FindHeapConstant(), v8::internal::compiler::MachineGraph::graph(), v8::internal::loc, v8::internal::compiler::TFGraph::NewNode(), and v8::internal::value.
Referenced by v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::LowerCompareMapsWithoutLoad().
HeapConstantNoHole()
Node * v8::internal::compiler::JSGraph::HeapConstantNoHole (Handle< HeapObject > value)
Definition at line 147 of file js-graph.cc.
                                                          {
  CHECK(!IsAnyHole(*value));
  Node** loc = cache_.FindHeapConstant(value);
  if (*loc == nullptr) {
    *loc = graph()->NewNode(common()->HeapConstant(value));
  }
  return *loc;
}
References v8::internal::compiler::MachineGraph::cache_, CHECK, v8::internal::compiler::MachineGraph::common(), v8::internal::compiler::CommonNodeCache::FindHeapConstant(), v8::internal::compiler::MachineGraph::graph(), v8::internal::IsAnyHole(), v8::internal::loc, v8::internal::compiler::TFGraph::NewNode(), and v8::internal::value.
Referenced by CEntryStubConstant(), Constant(), ConstantMutableHeapNumber(), v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::PushRegularApiCallInputs(), v8::internal::compiler::JSTypedLowering::ReduceJSCall(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetIterator(), v8::internal::compiler::LoadElimination::ReduceLoadField(), v8::internal::compiler::JSNativeContextSpecialization::ReduceMegaDOMPropertyAccess(), v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeHasOwnProperty(), v8::internal::compiler::JSCallReducer::ReduceReflectGet(), and v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral().
isolate()
Isolate* v8::internal::compiler::JSGraph::isolate () const [inline]
Definition at line 106 of file js-graph.h.
{ return isolate_; }
Referenced by CEntryStubConstant(), Constant(), v8::internal::compiler::CreateStubBuiltinContinuationFrameState(), v8::internal::compiler::JSCreateLowering::factory(), v8::internal::compiler::SimplifiedOperatorReducer::factory(), v8::internal::compiler::TypedOptimization::factory(), v8::internal::compiler::JSGenericLowering::graph(), v8::internal::compiler::JSBinopReduction::isolate(), v8::internal::compiler::SimplifiedLowering::isolate(), v8::internal::compiler::AllocationBuilder::isolate(), v8::internal::compiler::BranchElimination::isolate(), v8::internal::compiler::BytecodeGraphBuilder::isolate(), v8::internal::compiler::CsaLoadElimination::isolate(), v8::internal::compiler::JSCallReducer::isolate(), v8::internal::compiler::JSContextSpecialization::isolate(), v8::internal::compiler::JSInliningHeuristic::isolate(), v8::internal::compiler::JSInliner::isolate(), v8::internal::compiler::JSIntrinsicLowering::isolate(), v8::internal::compiler::JSNativeContextSpecialization::isolate(), v8::internal::compiler::JSSpeculativeBinopBuilder::isolate(), v8::internal::compiler::JSTypeHintLowering::isolate(), v8::internal::compiler::JSTypedLowering::isolate(), v8::internal::compiler::LoadElimination::isolate(), v8::internal::compiler::PropertyAccessBuilder::isolate(), v8::internal::compiler::WasmLoadElimination::isolate(), v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::PushRegularApiCallInputs(), and v8::internal::compiler::RepresentationSelector::WriteBarrierKindFor().
javascript()
JSOperatorBuilder* v8::internal::compiler::JSGraph::javascript () const [inline]
Definition at line 104 of file js-graph.h.
{ return javascript_; }
Referenced by v8::internal::compiler::JSSpeculativeBinopBuilder::javascript(), v8::internal::compiler::BytecodeGraphBuilder::javascript(), v8::internal::compiler::JSCallReducer::javascript(), v8::internal::compiler::JSInliner::javascript(), v8::internal::compiler::JSIntrinsicLowering::javascript(), v8::internal::compiler::JSNativeContextSpecialization::javascript(), v8::internal::compiler::JSTypedLowering::javascript(), v8::internal::compiler::JSContextSpecialization::SimplifyJSLoadContext(), v8::internal::compiler::JSContextSpecialization::SimplifyJSLoadContextNoCell(), v8::internal::compiler::JSContextSpecialization::SimplifyJSStoreContext(), v8::internal::compiler::JSContextSpecialization::SimplifyJSStoreContextNoCell(), and v8::internal::compiler::TFPipelineData::TFPipelineData().
NoContextConstant()
TNode<Number> v8::internal::compiler::JSGraph::NoContextConstant () [inline]
Definition at line 49 of file js-graph.h.
{ return ZeroConstant(); }
NumberConstant()
Node * v8::internal::compiler::JSGraph::NumberConstant (double value) [private]
Definition at line 139 of file js-graph.cc.
                                          {
  Node** loc = cache_.FindNumberConstant(value);
  if (*loc == nullptr) {
    *loc = graph()->NewNode(common()->NumberConstant(value));
  }
  return *loc;
}
References v8::internal::compiler::MachineGraph::cache_, v8::internal::compiler::MachineGraph::common(), v8::internal::compiler::CommonNodeCache::FindNumberConstant(), v8::internal::compiler::MachineGraph::graph(), v8::internal::loc, v8::internal::compiler::TFGraph::NewNode(), and v8::internal::value.
Referenced by ConstantMaybeHole().
operator=()
JSGraph& v8::internal::compiler::JSGraph::operator= (const JSGraph &) [delete]
PaddingConstant()
TNode<Hole> v8::internal::compiler::JSGraph::PaddingConstant () [inline]
Definition at line 46 of file js-graph.h.
{ return TheHoleConstant(); }
Referenced by v8::internal::compiler::anonymous_namespace{js-typed-lowering.cc}::ReduceBuiltin().
simplified()
SimplifiedOperatorBuilder* v8::internal::compiler::JSGraph::simplified () const [inline]
Definition at line 105 of file js-graph.h.
{ return simplified_; }
Referenced by v8::internal::compiler::MapInference::InsertMapChecks(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::LowerCompareMapsWithoutLoad(), v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContext(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode(), v8::internal::compiler::JSTypeHintLowering::ReduceUnaryOperation(), v8::internal::compiler::AllocationBuilder::simplified(), v8::internal::compiler::JSSpeculativeBinopBuilder::simplified(), v8::internal::compiler::RepresentationChanger::simplified(), v8::internal::compiler::SimplifiedLowering::simplified(), v8::internal::compiler::BytecodeGraphBuilder::simplified(), v8::internal::compiler::JSCallReducer::simplified(), v8::internal::compiler::JSCreateLowering::simplified(), v8::internal::compiler::JSInliningHeuristic::simplified(), v8::internal::compiler::JSInliner::simplified(), v8::internal::compiler::JSIntrinsicLowering::simplified(), v8::internal::compiler::JSNativeContextSpecialization::simplified(), v8::internal::compiler::JSTypedLowering::simplified(), v8::internal::compiler::PropertyAccessBuilder::simplified(), v8::internal::compiler::RepresentationSelector::simplified(), v8::internal::compiler::SimplifiedOperatorReducer::simplified(), v8::internal::compiler::TypedOptimization::simplified(), v8::internal::compiler::TFPipelineData::TFPipelineData(), and v8::internal::compiler::RepresentationSelector::VisitNode().
SmiConstant()
Node* v8::internal::compiler::JSGraph::SmiConstant (int32_t immediate) [inline]
Definition at line 99 of file js-graph.h.
                                       {
    DCHECK(Smi::IsValid(immediate));
    return ConstantMaybeHole(immediate);
  }
References v8::internal::DCHECK(), and v8::internal::Smi::IsValid().
Referenced by v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateClosure(), and v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetIterator().
TrustedHeapConstant()
Node * v8::internal::compiler::JSGraph::TrustedHeapConstant (Handle< HeapObject > value)
Definition at line 173 of file js-graph.cc.
                                                           {
  DCHECK(IsTrustedObject(*value));
  // TODO(pthier): Consider also caching trusted constants. Right now they are
  // only used for RegExp data as part of RegExp literals and it should be
  // uncommon for the same literal to appear multiple times.
  return graph()->NewNode(common()->TrustedHeapConstant(value));
}
References v8::internal::compiler::MachineGraph::common(), v8::internal::DCHECK(), v8::internal::compiler::MachineGraph::graph(), v8::internal::compiler::TFGraph::NewNode(), and v8::internal::value.
Member Data Documentation
isolate_
Isolate* v8::internal::compiler::JSGraph::isolate_ [private]
Definition at line 157 of file js-graph.h.
javascript_
JSOperatorBuilder* v8::internal::compiler::JSGraph::javascript_ [private]
Definition at line 158 of file js-graph.h.
simplified_
SimplifiedOperatorBuilder* v8::internal::compiler::JSGraph::simplified_ [private]
Definition at line 159 of file js-graph.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/js-graph.h
/mnt/V8SourceCode/src/compiler/js-graph.cc