v8::internal::compiler::turboshaft::GraphVisitor< AfterNext > Class Template Reference
#include <copying-phase.h>
Classes
struct BlockToClone
Public Types
using Next = VariableReducer< AfterNext >
Public Member Functions
GraphVisitor ()
template<bool trace_reduction>
void VisitGraph ()
void Bind (Block *block)
void Finalize ()
const Block * current_input_block ()
bool * turn_loop_without_backedge_into_merge ()
void CloneBlockAndGoto (const Block *input_block)
void CloneAndInlineBlock (const Block *input_block)
bool InlineOp (OpIndex index, const Block *input_block)
template<bool can_be_invalid = false>
OpIndex MapToNewGraph (OpIndex old_index, int predecessor_index=-1)
template<bool can_be_invalid = false, typename T >
V< T > MapToNewGraph (V< T > old_index, int predecessor_index=-1)
Block * MapToNewGraph (const Block *block) const
template<typename FunctionType >
OpIndex ResolvePhi (const PhiOp &op, FunctionType &&map, RegisterRepresentation rep)
const Block * OriginForBlockStart (Block *block) const
template<class Set >
Block * CloneSubGraph (Set sub_graph, bool keep_loop_kinds, bool is_loop_after_peeling=false)
template<bool can_be_invalid = false>
OptionalOpIndex MapToNewGraph (OptionalOpIndex old_index, int predecessor_index=-1)
template<size_t expected_size>
base::SmallVector< OpIndex, expected_size > MapToNewGraph (base::Vector< const OpIndex > inputs)
Private Types
enum class CanHavePhis { kNo
, kYes
 }
enum class ForCloning { kNo
, kYes
 }
Private Member Functions
template<bool trace_reduction>
void VisitAllBlocks ()
template<bool trace_reduction>
void VisitBlock (const Block *input_block)
template<CanHavePhis can_have_phis, ForCloning for_cloning, bool trace_reduction>
void VisitBlockBody (const Block *input_block, int added_block_phi_input=-1)
template<bool trace_reduction>
bool VisitOpAndUpdateMapping (OpIndex index, const Block *input_block)
template<bool trace_reduction>
OpIndex VisitOpNoMappingUpdate (OpIndex index, const Block *input_block)
template<bool trace_reduction>
void VisitBlockTerminator (const Operation &terminator, const Block *input_block)
template<bool trace_reduction>
void ProcessWaitingCloningAndInlining ()
template<bool trace_reduction>
void InlineWaitingBlock ()
template<bool trace_reduction>
void DoCloneBlock (const Block *input_block, int added_block_phi_input, Block *output_block)
void TraceReductionStart (OpIndex index)
void TraceOperationSkipped ()
void TraceBlockUnreachable ()
void TraceReductionResult (Block *current_block, OpIndex first_output_index, OpIndex new_index)
void TraceBlockFinished ()
OpIndex AssembleOutputGraphGoto (const GotoOp &op)
OpIndex AssembleOutputGraphBranch (const BranchOp &op)
OpIndex AssembleOutputGraphSwitch (const SwitchOp &op)
OpIndex AssembleOutputGraphPhi (const PhiOp &op)
OpIndex AssembleOutputGraphPendingLoopPhi (const PendingLoopPhiOp &op)
OpIndex AssembleOutputGraphFrameState (const FrameStateOp &op)
OpIndex AssembleOutputGraphCall (const CallOp &op)
OpIndex AssembleOutputGraphDidntThrow (const DidntThrowOp &op)
V< None > AssembleOutputGraphCheckException (const CheckExceptionOp &op)
OpIndex AssembleOutputGraphParameter (const ParameterOp &param)
void CreateOldToNewMapping (OpIndex old_index, OpIndex new_index)
MaybeVariable GetVariableFor (OpIndex old_index) const
void SetVariableFor (OpIndex old_index, MaybeVariable var)
void FixLoopPhis (Block *input_graph_loop)
Private Attributes
Graph & input_graph_
OptimizedCompilationInfo * info_ = Asm().data()->info()
TickCounter *const tick_counter_ = info_ ? &info_->tick_counter() : nullptr
const Block * current_input_block_
FixedOpIndexSidetable< OpIndex > op_mapping_
FixedBlockSidetable< Block * > block_mapping_
bool current_block_needs_variables_ = false
bool turn_loop_without_backedge_into_merge_ = true
BitVector blocks_needing_variables_
FixedOpIndexSidetable< MaybeVariable > old_opindex_to_variables
Block * block_to_inline_now_ = nullptr
ZoneVector< BlockToClone > blocks_to_clone_
Friends
template<typename N >
class ReducerBaseForwarder
template<typename N >
class WasmRevecReducer
Detailed Description
template<class AfterNext>
class v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >
Definition at line 87 of file copying-phase.h.
Member Typedef Documentation
Next
template<class AfterNext >
using v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::Next = VariableReducer<AfterNext>
Definition at line 95 of file copying-phase.h.
Member Enumeration Documentation
CanHavePhis
template<class AfterNext >
enum v8::internal::compiler::turboshaft::GraphVisitor::CanHavePhis [strong], [private]
Enumerator
kNo
kYes
Definition at line 538 of file copying-phase.h.
{ kNo, kYes };
ForCloning
template<class AfterNext >
enum v8::internal::compiler::turboshaft::GraphVisitor::ForCloning [strong], [private]
Enumerator
kNo
kYes
Definition at line 539 of file copying-phase.h.
{ kNo, kYes };
Constructor & Destructor Documentation
GraphVisitor()
template<class AfterNext >
v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::GraphVisitor () [inline]
Definition at line 98 of file copying-phase.h.
      : input_graph_(Asm().modifiable_input_graph()),
        current_input_block_(nullptr),
        op_mapping_(Asm().input_graph().op_id_count(), OpIndex::Invalid(),
                    Asm().phase_zone(), &Asm().input_graph()),
        block_mapping_(Asm().input_graph().block_count(), nullptr,
                       Asm().phase_zone()),
        blocks_needing_variables_(Asm().input_graph().block_count(),
                                  Asm().phase_zone()),
        old_opindex_to_variables(Asm().input_graph().op_id_count(),
                                 Asm().phase_zone(), &Asm().input_graph()),
        blocks_to_clone_(Asm().phase_zone()) {
    Asm().output_graph().Reset();
  }
Member Function Documentation
AssembleOutputGraphBranch()
template<class AfterNext >
OpIndex v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphBranch (const BranchOp & op) [inline], [private]
Definition at line 832 of file copying-phase.h.
                                                                  {
    Block* if_true = MapToNewGraph(op.if_true);
    Block* if_false = MapToNewGraph(op.if_false);
    return Asm().ReduceBranch(MapToNewGraph(op.condition()), if_true, if_false,
                              op.hint);
  }
References v8::internal::compiler::turboshaft::BranchOp::condition(), v8::internal::compiler::turboshaft::BranchOp::hint, v8::internal::compiler::turboshaft::BranchOp::if_false, v8::internal::compiler::turboshaft::BranchOp::if_true, and v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::MapToNewGraph().
AssembleOutputGraphCall()
template<class AfterNext >
OpIndex v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphCall (const CallOp & op) [inline], [private]
Definition at line 863 of file copying-phase.h.
                                                    {
    V<CallTarget> callee = MapToNewGraph(op.callee());
    OptionalV<FrameState> frame_state = MapToNewGraph(op.frame_state());
    auto arguments = MapToNewGraph<16>(op.arguments());
    return Asm().ReduceCall(callee, frame_state, base::VectorOf(arguments),
                            op.descriptor, op.Effects());
  }
References v8::internal::compiler::turboshaft::CallOp::arguments(), v8::internal::compiler::turboshaft::CallOp::callee(), v8::internal::compiler::turboshaft::CallOp::descriptor, v8::internal::compiler::turboshaft::CallOp::Effects(), v8::internal::compiler::turboshaft::CallOp::frame_state(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::MapToNewGraph(), and v8::base::VectorOf().
AssembleOutputGraphCheckException()
template<class AfterNext >
V<None> v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphCheckException (const CheckExceptionOp & op) [inline], [private]
Definition at line 888 of file copying-phase.h.
                                                                        {
    Graph::OpIndexIterator it(op.didnt_throw_block->begin(),
                              &Asm().input_graph());
    Graph::OpIndexIterator end(op.didnt_throw_block->end(),
                               &Asm().input_graph());
    // To translate `CheckException` to the new graph, we reduce the throwing
    // operation (actually it's `DidntThrow` operation, but that triggers the
    // actual reduction) with a catch scope. If the reduction replaces the
    // throwing operation with other throwing operations, all of them will be
    // connected to the provided catch block. The reduction should automatically
    // bind a block that represents non-throwing control flow of the original
    // operation, so we can inline the rest of the `didnt_throw` block.
    {
      CatchScope scope(Asm(), MapToNewGraph(op.catch_block));
      DCHECK(Asm().input_graph().Get(*it).template Is<DidntThrowOp>());
      if (!Asm().InlineOp(*it, op.didnt_throw_block)) {
        return V<None>::Invalid();
      }
      ++it;
    }
    for (; it != end; ++it) {
      // Using `InlineOp` requires that the inlined operation is not emitted
      // multiple times. This is the case here because we just removed the
      // single predecessor of `didnt_throw_block`.
      if (!Asm().InlineOp(*it, op.didnt_throw_block)) {
        break;
      }
    }
    return V<None>::Invalid();
  }
References v8::internal::compiler::turboshaft::Block::begin(), v8::internal::compiler::turboshaft::CheckExceptionOp::catch_block, v8::internal::DCHECK(), v8::internal::compiler::turboshaft::CheckExceptionOp::didnt_throw_block, v8::internal::compiler::turboshaft::Block::end(), v8::internal::compiler::end(), v8::internal::compiler::turboshaft::Get(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::InlineOp(), v8::internal::compiler::turboshaft::V< T >::Invalid(), and v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::MapToNewGraph().
AssembleOutputGraphDidntThrow()
template<class AfterNext >
OpIndex v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphDidntThrow (const DidntThrowOp & op) [inline], [private]
Definition at line 870 of file copying-phase.h.
                                                                {
    const Operation& throwing_operation =
        Asm().input_graph().Get(op.throwing_operation());
    OpIndex result;
    switch (throwing_operation.opcode) {
#define CASE(Name) \
  case Opcode::k##Name: \
    result = Asm().ReduceInputGraph##Name(\
        op.throwing_operation(), throwing_operation.Cast<Name##Op>()); \
    break;
      TURBOSHAFT_THROWING_OPERATIONS_LIST(CASE)
#undef CASE
      default:
        UNREACHABLE();
    }
    return result;
  }
References CASE, v8::internal::compiler::turboshaft::Operation::opcode, v8::base::internal::result, v8::internal::compiler::turboshaft::DidntThrowOp::throwing_operation(), TURBOSHAFT_THROWING_OPERATIONS_LIST, and v8::internal::UNREACHABLE().
AssembleOutputGraphFrameState()
template<class AfterNext >
OpIndex v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphFrameState (const FrameStateOp & op) [inline], [private]
Definition at line 859 of file copying-phase.h.
                                                                          {
    auto inputs = MapToNewGraph<32>(op.inputs());
    return Asm().ReduceFrameState(base::VectorOf(inputs), op.inlined, op.data);
  }
References v8::internal::compiler::turboshaft::FrameStateOp::data, v8::internal::compiler::turboshaft::FrameStateOp::inlined, v8::internal::compiler::turboshaft::OperationT< Derived >::inputs(), and v8::base::VectorOf().
AssembleOutputGraphGoto()
template<class AfterNext >
OpIndex v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphGoto (const GotoOp & op) [inline], [private]
Definition at line 818 of file copying-phase.h.
                                                              {
    Block* destination = MapToNewGraph(op.destination);
    if (op.is_backedge) {
      DCHECK(destination->IsBound());
      DCHECK(destination->IsLoop());
      FixLoopPhis(op.destination);
    }
    // It is important that we first fix loop phis and then reduce the `Goto`,
    // because reducing the `Goto` can have side effects, in particular, it can
    // modify affect the SnapshotTable of `VariableReducer`, which is also used
    // by `FixLoopPhis()`.
    Asm().ReduceGoto(destination, op.is_backedge);
    return OpIndex::Invalid();
  }
References v8::internal::DCHECK(), v8::internal::compiler::turboshaft::GotoOp::destination, v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::FixLoopPhis(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::turboshaft::GotoOp::is_backedge, v8::internal::compiler::turboshaft::Block::IsBound(), v8::internal::compiler::turboshaft::Block::IsLoop(), and v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::MapToNewGraph().
AssembleOutputGraphParameter()
template<class AfterNext >
OpIndex v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphParameter (const ParameterOp & param) [inline], [private]
Definition at line 919 of file copying-phase.h.
                                                                 {
    // Calling the AssemblerOpInterface rather than the first Reduce method
    // in order to make use of the Parameter cache.
    return Asm().Parameter(param.parameter_index, param.rep, param.debug_name);
  }
References v8::internal::compiler::turboshaft::ParameterOp::debug_name, v8::internal::compiler::turboshaft::ParameterOp::parameter_index, and v8::internal::compiler::turboshaft::ParameterOp::rep.
AssembleOutputGraphPendingLoopPhi()
template<class AfterNext >
OpIndex v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphPendingLoopPhi (const PendingLoopPhiOp & op) [inline], [private]
Definition at line 856 of file copying-phase.h.
                                                                        {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
AssembleOutputGraphPhi()
template<class AfterNext >
OpIndex v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphPhi (const PhiOp & op) [inline], [private]
Definition at line 848 of file copying-phase.h.
                                                  {
    return ResolvePhi(
        op,
        [this](OpIndex ind, int predecessor_index, int old_index = 0) {
          return MapToNewGraph(ind, predecessor_index);
        },
        op.rep);
  }
References v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::MapToNewGraph(), v8::internal::compiler::turboshaft::PhiOp::rep, and v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::ResolvePhi().
AssembleOutputGraphSwitch()
template<class AfterNext >
OpIndex v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphSwitch (const SwitchOp & op) [inline], [private]
Definition at line 838 of file copying-phase.h.
                                                        {
    base::SmallVector<SwitchOp::Case, 16> cases;
    for (SwitchOp::Case c : op.cases) {
      cases.emplace_back(c.value, MapToNewGraph(c.destination), c.hint);
    }
    return Asm().ReduceSwitch(
        MapToNewGraph(op.input()),
        Asm().graph_zone()->CloneVector(base::VectorOf(cases)),
        MapToNewGraph(op.default_case), op.default_hint);
  }
References v8::internal::compiler::turboshaft::SwitchOp::cases, v8::internal::CloneVector(), v8::internal::compiler::turboshaft::SwitchOp::default_case, v8::internal::compiler::turboshaft::SwitchOp::default_hint, v8::internal::compiler::turboshaft::SwitchOp::Case::destination, v8::base::SmallVector< T, kSize, Allocator >::emplace_back(), v8::internal::compiler::turboshaft::SwitchOp::Case::hint, v8::internal::compiler::turboshaft::SwitchOp::input(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::MapToNewGraph(), v8::internal::compiler::turboshaft::SwitchOp::Case::value, and v8::base::VectorOf().
Bind()
template<class AfterNext >
void v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::Bind (Block * block) [inline]
Definition at line 132 of file copying-phase.h.
                          {
    Next::Bind(block);
    block->SetOrigin(current_input_block());
  }
References v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::Bind(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::current_input_block(), and v8::internal::compiler::turboshaft::Block::SetOrigin().
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitBlock().
CloneAndInlineBlock()
template<class AfterNext >
void v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::CloneAndInlineBlock (const Block * input_block) [inline]
Definition at line 200 of file copying-phase.h.
                                                     {
    if (Asm().generating_unreachable_operations()) return;
#ifdef DEBUG
    // Making sure that we didn't call CloneAndInlineBlock recursively.
    DCHECK(!is_in_recursive_inlining_);
    ScopedModification<bool> recursive_guard(&is_in_recursive_inlining_, true);
#endif
    // Computing which input of Phi operations to use when visiting
    // {input_block} (since {input_block} doesn't really have predecessors
    // anymore).
    int added_block_phi_input = input_block->GetPredecessorIndex(
        Asm().current_block()->OriginForBlockEnd());
    // There is no guarantees that {input_block} will be entirely removed just
    // because it's cloned/inlined, since it's possible that it has predecessors
    // for which this optimization didn't apply. As a result, we add it to
    // {blocks_needing_variables_}, so that if it's ever generated
    // normally, Variables are used when emitting its content, so that
    // they can later be merged when control flow merges with the current
    // version of {input_block} that we just cloned.
    blocks_needing_variables_.Add(input_block->index().id());
    ScopedModification<bool> set_true(&current_block_needs_variables_, true);
    VisitBlockBody<CanHavePhis::kYes, ForCloning::kYes, false>(
        input_block, added_block_phi_input);
  }
References v8::internal::BitVector::Add(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::blocks_needing_variables_, v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::current_block_needs_variables_, v8::internal::DCHECK(), v8::internal::compiler::turboshaft::Block::GetPredecessorIndex(), v8::internal::compiler::turboshaft::BlockIndex::id(), and v8::internal::compiler::turboshaft::Block::index().
CloneBlockAndGoto()
template<class AfterNext >
void v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::CloneBlockAndGoto (const Block * input_block) [inline]
Definition at line 173 of file copying-phase.h.
                                                   {
    Block* new_block =
        Asm().output_graph().NewBlock(input_block->kind(), input_block);
    // Computing which input of Phi operations to use when visiting
    // {input_block} (since {input_block} doesn't really have predecessors
    // anymore).
    int added_block_phi_input = input_block->GetPredecessorIndex(
        Asm().current_block()->OriginForBlockEnd());
    // There is no guarantees that {input_block} will be entirely removed just
    // because it's cloned/inlined, since it's possible that it has predecessors
    // for which this optimization didn't apply. As a result, we add it to
    // {blocks_needing_variables_}, so that if it's ever generated
    // normally, Variables are used when emitting its content, so that
    // they can later be merged when control flow merges with the current
    // version of {input_block} that we just cloned.
    blocks_needing_variables_.Add(input_block->index().id());
    Asm().Goto(new_block);
    blocks_to_clone_.push_back({input_block, added_block_phi_input, new_block});
  }
References v8::internal::BitVector::Add(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::blocks_needing_variables_, v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::blocks_to_clone_, v8::internal::compiler::turboshaft::Block::GetPredecessorIndex(), v8::internal::compiler::turboshaft::BlockIndex::id(), v8::internal::compiler::turboshaft::Block::index(), and v8::internal::compiler::turboshaft::Block::kind().
CloneSubGraph()
template<class AfterNext >
template<class Set >
Block* v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::CloneSubGraph (Set sub_graph, bool keep_loop_kinds, bool is_loop_after_peeling = false) [inline]
Definition at line 412 of file copying-phase.h.
                                                           {
    // The BlockIndex of the blocks of `sub_graph` should be sorted so that
    // visiting them in order is correct (all of the predecessors of a block
    // should always be visited before the block itself).
    DCHECK(std::is_sorted(sub_graph.begin(), sub_graph.end(),
                          [](const Block* a, const Block* b) {
                            return a->index().id() <= b->index().id();
                          }));
    // 1. Create new blocks, and update old->new mapping. This is required to
    // emit multiple times the blocks of {sub_graph}: if a block `B1` in
    // {sub_graph} ends with a Branch/Goto to a block `B2` that is also in
    // {sub_graph}, then this Branch/Goto should go to the version of `B2` that
    // this CloneSubGraph will insert, rather than to a version inserted by a
    // previous call to CloneSubGraph or the version that the regular
    // VisitAllBlock function will emit.
    ZoneVector<Block*> old_mappings(sub_graph.size(), Asm().phase_zone());
    for (auto&& [input_block, old_mapping] :
         base::zip(sub_graph, old_mappings)) {
      old_mapping = block_mapping_[input_block->index()];
      Block::Kind kind = keep_loop_kinds && input_block->IsLoop()
                             ? Block::Kind::kLoopHeader
                             : Block::Kind::kMerge;
      block_mapping_[input_block->index()] =
          Asm().output_graph().NewBlock(kind, input_block);
    }
    // 2. Visit block in correct order (begin to end)
    // Emit a goto to 1st block.
    Block* start = block_mapping_[(*sub_graph.begin())->index()];
#ifdef DEBUG
    if (is_loop_after_peeling) start->set_has_peeled_iteration();
#endif
    Asm().Goto(start);
    // Visiting `sub_graph`.
    for (const Block* block : sub_graph) {
      blocks_needing_variables_.Add(block->index().id());
      VisitBlock<false>(block);
      ProcessWaitingCloningAndInlining<false>();
    }
    // 3. Restore initial old->new mapping
    for (auto&& [input_block, old_mapping] :
         base::zip(sub_graph, old_mappings)) {
      block_mapping_[input_block->index()] = old_mapping;
    }
    return start;
  }
References v8::internal::BitVector::Add(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::block_mapping_, v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::blocks_needing_variables_, v8::internal::DCHECK(), v8::internal::index, v8::internal::compiler::turboshaft::Block::kLoopHeader, v8::internal::compiler::turboshaft::Block::kMerge, and v8::base::zip().
CreateOldToNewMapping()
template<class AfterNext >
void v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::CreateOldToNewMapping (OpIndex old_index, OpIndex new_index) [inline], [private]
Definition at line 925 of file copying-phase.h.
                                                                   {
    DCHECK(old_index.valid());
    DCHECK(Asm().input_graph().BelongsToThisGraph(old_index));
    DCHECK_IMPLIES(new_index.valid(),
                   Asm().output_graph().BelongsToThisGraph(new_index));
    if (current_block_needs_variables_) {
      MaybeVariable var = GetVariableFor(old_index);
      if (!var.has_value()) {
        MaybeRegisterRepresentation rep =
            Asm().input_graph().Get(old_index).outputs_rep().size() == 1
                ? static_cast<const MaybeRegisterRepresentation&>(
                      Asm().input_graph().Get(old_index).outputs_rep()[0])
                : MaybeRegisterRepresentation::None();
        var = Asm().NewLoopInvariantVariable(rep);
        SetVariableFor(old_index, *var);
      }
      Asm().SetVariable(*var, new_index);
      return;
    }
    DCHECK(!op_mapping_[old_index].valid());
    op_mapping_[old_index] = new_index;
  }
References v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::current_block_needs_variables_, v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::GetVariableFor(), v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::None(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::op_mapping_, v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::SetVariableFor(), and v8::internal::compiler::turboshaft::OpIndex::valid().
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitBlockBody(), and v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitOpAndUpdateMapping().
current_input_block()
template<class AfterNext >
const Block* v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::current_input_block () [inline]
Definition at line 161 of file copying-phase.h.
{ return current_input_block_; }
References v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::current_input_block_.
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::Bind().
DoCloneBlock()
template<class AfterNext >
template<bool trace_reduction>
void v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::DoCloneBlock (const Block * input_block, int added_block_phi_input, Block * output_block) [inline], [private]
Definition at line 753 of file copying-phase.h.
                                         {
    DCHECK_EQ(output_block->PredecessorCount(), 1);
    if constexpr (trace_reduction) {
      std::cout << "\nCloning old " << PrintAsBlockHeader{*input_block} << "\n";
      std::cout << "As new "
                << PrintAsBlockHeader{*output_block,
                                      Asm().output_graph().next_block_index()}
                << "\n";
    }
    ScopedModification<bool> set_true(&current_block_needs_variables_, true);
    Asm().BindReachable(output_block);
    VisitBlockBody<CanHavePhis::kYes, ForCloning::kYes, trace_reduction>(
        input_block, added_block_phi_input);
    if constexpr (trace_reduction) TraceBlockFinished();
  }
References v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::current_block_needs_variables_, DCHECK_EQ, v8::internal::compiler::turboshaft::Block::PredecessorCount(), and v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::TraceBlockFinished().
Finalize()
template<class AfterNext >
void v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::Finalize () [inline]
Definition at line 137 of file copying-phase.h.
                  {
    // Updating the source_positions.
    if (!Asm().input_graph().source_positions().empty()) {
      for (OpIndex index : Asm().output_graph().AllOperationIndices()) {
        OpIndex origin = Asm().output_graph().operation_origins()[index];
        Asm().output_graph().source_positions()[index] =
            origin.valid() ? Asm().input_graph().source_positions()[origin]
                           : SourcePosition::Unknown();
      }
    }
    // Updating the operation origins.
    NodeOriginTable* origins = Asm().data()->node_origins();
    if (origins) {
      for (OpIndex index : Asm().output_graph().AllOperationIndices()) {
        OpIndex origin = Asm().output_graph().operation_origins()[index];
        if (origin.valid()) {
          origins->SetNodeOrigin(index.id(), origin.id());
        }
      }
    }
    input_graph_.SwapWithCompanion();
  }
References v8::internal::compiler::turboshaft::OpIndex::id(), v8::internal::index, v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::input_graph_, v8::internal::compiler::NodeOriginTable::SetNodeOrigin(), v8::internal::compiler::turboshaft::Graph::SwapWithCompanion(), v8::internal::SourcePosition::Unknown(), and v8::internal::compiler::turboshaft::OpIndex::valid().
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitGraph().
FixLoopPhis()
template<class AfterNext >
void v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::FixLoopPhis (Block * input_graph_loop) [inline], [private]
Definition at line 959 of file copying-phase.h.
                                            {
    DCHECK(input_graph_loop->IsLoop());
    Block* output_graph_loop = MapToNewGraph(input_graph_loop);
    DCHECK(output_graph_loop->IsLoop());
    for (const Operation& op : Asm().input_graph().operations(
             input_graph_loop->begin(), input_graph_loop->end())) {
      if (auto* input_phi = op.TryCast<PhiOp>()) {
        OpIndex phi_index =
            MapToNewGraph<true>(Asm().input_graph().Index(*input_phi));
        if (!phi_index.valid() || !output_graph_loop->Contains(phi_index)) {
          // Unused phis are skipped, so they are not be mapped to anything in
          // the new graph. If the phi is reduced to an operation from a
          // different block, then there is no loop phi in the current loop
          // header to take care of.
          continue;
        }
        Asm().FixLoopPhi(*input_phi, phi_index, output_graph_loop);
      }
    }
  }
References v8::internal::compiler::turboshaft::Block::begin(), v8::internal::compiler::turboshaft::Block::Contains(), v8::internal::DCHECK(), v8::internal::compiler::turboshaft::Block::end(), v8::internal::compiler::turboshaft::Block::IsLoop(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::MapToNewGraph(), and v8::internal::compiler::turboshaft::OpIndex::valid().
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphGoto().
GetVariableFor()
template<class AfterNext >
MaybeVariable v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::GetVariableFor (OpIndex old_index) const [inline], [private]
Definition at line 950 of file copying-phase.h.
                                                        {
    return old_opindex_to_variables[old_index];
  }
References v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::old_opindex_to_variables.
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::CreateOldToNewMapping(), and v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::MapToNewGraph().
InlineOp()
template<class AfterNext >
bool v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::InlineOp (OpIndex index, const Block * input_block) [inline]
Definition at line 233 of file copying-phase.h.
                                                         {
    return VisitOpAndUpdateMapping<false>(index, input_block);
  }
References v8::internal::index.
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphCheckException().
InlineWaitingBlock()
template<class AfterNext >
template<bool trace_reduction>
void v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::InlineWaitingBlock () [inline], [private]
Definition at line 739 of file copying-phase.h.
                            {
    while (block_to_inline_now_) {
      Block* input_block = block_to_inline_now_;
      block_to_inline_now_ = nullptr;
      ScopedModification<bool> set_true(&current_block_needs_variables_, true);
      if constexpr (trace_reduction) {
        std::cout << "Inlining " << PrintAsBlockHeader{*input_block} << "\n";
      }
      VisitBlockBody<CanHavePhis::kNo, ForCloning::kNo, trace_reduction>(
          input_block);
    }
  }
References v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::block_to_inline_now_, and v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::current_block_needs_variables_.
MapToNewGraph() [1/5]
template<class AfterNext >
template<size_t expected_size>
base::SmallVector<OpIndex, expected_size> v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::MapToNewGraph (base::Vector< const OpIndex > inputs) [inline]
Definition at line 472 of file copying-phase.h.
                                        {
    base::SmallVector<OpIndex, expected_size> result;
    for (OpIndex input : inputs) {
      result.push_back(MapToNewGraph(input));
    }
    return result;
  }
References v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::MapToNewGraph(), and v8::base::internal::result.
MapToNewGraph() [2/5]
template<class AfterNext >
Block* v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::MapToNewGraph (const Block * block) const [inline]
Definition at line 269 of file copying-phase.h.
                                                 {
    Block* new_block = block_mapping_[block->index()];
    DCHECK_NOT_NULL(new_block);
    return new_block;
  }
References v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::block_mapping_, DCHECK_NOT_NULL, and v8::internal::compiler::turboshaft::Block::index().
MapToNewGraph() [3/5]
template<class AfterNext >
template<bool can_be_invalid = false>
OpIndex v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::MapToNewGraph (OpIndex old_index, int predecessor_index = -1) [inline]
Definition at line 238 of file copying-phase.h.
                                                                       {
    DCHECK(old_index.valid());
    OpIndex result = op_mapping_[old_index];
    if (!result.valid()) {
      // {op_mapping} doesn't have a mapping for {old_index}. The
      // VariableReducer should provide the mapping.
      MaybeVariable var = GetVariableFor(old_index);
      if constexpr (can_be_invalid) {
        if (!var.has_value()) {
          return OpIndex::Invalid();
        }
      }
      DCHECK(var.has_value());
      if (predecessor_index == -1) {
        result = Asm().GetVariable(var.value());
      } else {
        result = Asm().GetPredecessorValue(var.value(), predecessor_index);
      }
    }
    DCHECK_IMPLIES(!can_be_invalid, result.valid());
    return result;
  }
References v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::GetVariableFor(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::op_mapping_, v8::base::internal::result, and v8::internal::compiler::turboshaft::OpIndex::valid().
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphBranch(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphCall(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphCheckException(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphGoto(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphPhi(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphSwitch(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::FixLoopPhis(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::MapToNewGraph(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::OriginForBlockStart(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitBlock(), and v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitBlockBody().
MapToNewGraph() [4/5]
template<class AfterNext >
template<bool can_be_invalid = false>
OptionalOpIndex v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::MapToNewGraph (OptionalOpIndex old_index, int predecessor_index = -1) [inline]
Definition at line 465 of file copying-phase.h.
                                                            {
    if (!old_index.has_value()) return OptionalOpIndex::Nullopt();
    return MapToNewGraph<can_be_invalid>(old_index.value(), predecessor_index);
  }
References v8::internal::compiler::turboshaft::OptionalOpIndex::has_value(), v8::internal::compiler::turboshaft::OptionalOpIndex::Nullopt(), and v8::internal::compiler::turboshaft::OptionalOpIndex::value().
MapToNewGraph() [5/5]
template<class AfterNext >
template<bool can_be_invalid = false, typename T >
V<T> v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::MapToNewGraph (V< T > old_index, int predecessor_index = -1) [inline]
Definition at line 264 of file copying-phase.h.
                                                                 {
    return V<T>::Cast(MapToNewGraph<can_be_invalid>(
        static_cast<OpIndex>(old_index), predecessor_index));
  }
References v8::internal::compiler::turboshaft::V< T >::Cast().
OriginForBlockStart()
template<class AfterNext >
const Block* v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::OriginForBlockStart (Block * block) const [inline]
Definition at line 398 of file copying-phase.h.
                                                       {
    // Check that `block->origin_` is still valid as a block start and was not
    // changed to a semantically different block when inlining blocks.
    const Block* origin = block->origin_;
    if (origin && MapToNewGraph(origin) == block) return origin;
    return nullptr;
  }
References v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::MapToNewGraph(), and v8::internal::compiler::turboshaft::Block::origin_.
ProcessWaitingCloningAndInlining()
template<class AfterNext >
template<bool trace_reduction>
void v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::ProcessWaitingCloningAndInlining () [inline], [private]
Definition at line 727 of file copying-phase.h.
                                          {
    InlineWaitingBlock<trace_reduction>();
    while (!blocks_to_clone_.empty()) {
      BlockToClone item = blocks_to_clone_.back();
      blocks_to_clone_.pop_back();
      DoCloneBlock<trace_reduction>(
          item.input_block, item.added_block_phi_input, item.new_output_block);
      InlineWaitingBlock<trace_reduction>();
    }
  }
References v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::BlockToClone::added_block_phi_input, v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::blocks_to_clone_, v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::BlockToClone::input_block, and v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::BlockToClone::new_output_block.
ResolvePhi()
template<class AfterNext >
template<typename FunctionType >
OpIndex v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::ResolvePhi (const PhiOp & op, FunctionType && map, RegisterRepresentation rep) [inline]
Definition at line 276 of file copying-phase.h.
                                                 {
    if (op.input_count == 1) {
      // If, in the previous CopyingPhase, a loop header was turned into a
      // regular blocks, its PendingLoopPhis became Phis with a single input. We
      // can now just get rid of these Phis.
      return map(op.input(0), -1);
    }
    OpIndex ig_index = Asm().input_graph().Index(op);
    if (Asm().current_block()->IsLoop()) {
      DCHECK_EQ(op.input_count, 2);
      OpIndex og_index = map(op.input(0), -1);
      if (ig_index == op.input(PhiOp::kLoopPhiBackEdgeIndex)) {
        // Avoid emitting a Loop Phi which points to itself, instead
        // emit it's 0'th input.
        return og_index;
      }
      return Asm().PendingLoopPhi(og_index, rep);
    }
    base::Vector<const OpIndex> old_inputs = op.inputs();
    base::SmallVector<OpIndex, 64> new_inputs;
    int predecessor_count = Asm().current_block()->PredecessorCount();
    Block* old_pred = current_input_block_->LastPredecessor();
    Block* new_pred = Asm().current_block()->LastPredecessor();
    // Control predecessors might be missing after the optimization phase. So we
    // need to skip phi inputs that belong to control predecessors that have no
    // equivalent in the new graph.
    // We first assume that the order if the predecessors of the current block
    // did not change. If it did, {new_pred} won't be nullptr at the end of this
    // loop, and we'll instead fall back to the slower code below to compute the
    // inputs of the Phi.
    int predecessor_index = predecessor_count - 1;
    int old_index = static_cast<int>(old_inputs.size()) - 1;
    for (OpIndex input : base::Reversed(old_inputs)) {
      if (new_pred && new_pred->OriginForBlockEnd() == old_pred) {
        // Phis inputs have to come from predecessors. We thus have to
        // MapToNewGraph with {predecessor_index} so that we get an OpIndex that
        // is from a predecessor rather than one that comes from a Variable
        // merged in the current block.
        new_inputs.push_back(map(input, predecessor_index, old_index));
        new_pred = new_pred->NeighboringPredecessor();
        predecessor_index--;
      }
      old_pred = old_pred->NeighboringPredecessor();
      old_index--;
    }
    DCHECK_IMPLIES(new_pred == nullptr, old_pred == nullptr);
    if (new_pred != nullptr) {
      // If {new_pred} is not nullptr, then the order of the predecessors
      // changed. This should only happen with blocks that were introduced in
      // the previous graph. For instance, consider this (partial) dominator
      // tree:
      //
      // 7
      // 8
      // 10
      // 9
      // 11
      //
      // Where the predecessors of block 11 are blocks 9 and 10 (in that order).
      // In dominator visit order, block 10 will be visited before block 9.
      // Since blocks are added to predecessors when the predecessors are
      // visited, it means that in the new graph, the predecessors of block 11
      // are [10, 9] rather than [9, 10].
      // To account for this, we reorder the inputs of the Phi, and get rid of
      // inputs from blocks that vanished.
#ifdef DEBUG
      // To check that indices are set properly, we zap them in debug builds.
      for (auto& block : Asm().modifiable_input_graph().blocks()) {
        block.clear_custom_data();
      }
#endif
      uint32_t pos = current_input_block_->PredecessorCount() - 1;
      for (old_pred = current_input_block_->LastPredecessor();
           old_pred != nullptr; old_pred = old_pred->NeighboringPredecessor()) {
        // Store the current index of the {old_pred}.
        old_pred->set_custom_data(pos--, Block::CustomDataKind::kPhiInputIndex);
      }
      // Filling {new_inputs}: we iterate the new predecessors, and, for each
      // predecessor, we check the index of the input corresponding to the old
      // predecessor, and we put it next in {new_inputs}.
      new_inputs.clear();
      predecessor_index = predecessor_count - 1;
      for (new_pred = Asm().current_block()->LastPredecessor();
           new_pred != nullptr; new_pred = new_pred->NeighboringPredecessor()) {
        const Block* origin = new_pred->OriginForBlockEnd();
        DCHECK_NOT_NULL(origin);
        old_index =
            origin->get_custom_data(Block::CustomDataKind::kPhiInputIndex);
        OpIndex input = old_inputs[old_index];
        // Phis inputs have to come from predecessors. We thus have to
        // MapToNewGraph with {predecessor_index} so that we get an OpIndex that
        // is from a predecessor rather than one that comes from a Variable
        // merged in the current block.
        new_inputs.push_back(map(input, predecessor_index, old_index));
        predecessor_index--;
      }
    }
    DCHECK_EQ(new_inputs.size(), Asm().current_block()->PredecessorCount());
    if (new_inputs.size() == 1) {
      // This Operation used to be a Phi in a Merge, but since one (or more) of
      // the inputs of the merge have been removed, there is no need for a Phi
      // anymore.
      return new_inputs[0];
    }
    std::reverse(new_inputs.begin(), new_inputs.end());
    return Asm().ReducePhi(base::VectorOf(new_inputs), rep);
  }
References v8::base::SmallVector< T, kSize, Allocator >::begin(), v8::base::SmallVector< T, kSize, Allocator >::clear(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::current_input_block_, DCHECK_EQ, DCHECK_IMPLIES, DCHECK_NOT_NULL, v8::base::SmallVector< T, kSize, Allocator >::end(), v8::internal::compiler::turboshaft::Block::get_custom_data(), v8::internal::compiler::turboshaft::OperationT< Derived >::input(), v8::internal::compiler::turboshaft::Operation::input_count, v8::internal::compiler::turboshaft::OperationT< Derived >::inputs(), v8::internal::compiler::turboshaft::PhiOp::kLoopPhiBackEdgeIndex, v8::internal::compiler::turboshaft::Block::kPhiInputIndex, v8::internal::compiler::turboshaft::Block::LastPredecessor(), v8::internal::compiler::turboshaft::Block::NeighboringPredecessor(), v8::internal::compiler::turboshaft::Block::OriginForBlockEnd(), v8::internal::compiler::turboshaft::Block::PredecessorCount(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), v8::base::Reversed(), v8::internal::compiler::turboshaft::Block::set_custom_data(), v8::base::SmallVector< T, kSize, Allocator >::size(), v8::base::Vector< T >::size(), and v8::base::VectorOf().
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphPhi().
SetVariableFor()
template<class AfterNext >
void v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::SetVariableFor (OpIndex old_index, MaybeVariable var) [inline], [private]
Definition at line 954 of file copying-phase.h.
                                                            {
    DCHECK(!old_opindex_to_variables[old_index].has_value());
    old_opindex_to_variables[old_index] = var;
  }
References v8::internal::DCHECK(), and v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::old_opindex_to_variables.
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::CreateOldToNewMapping().
TraceBlockFinished()
template<class AfterNext >
void v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::TraceBlockFinished () [inline], [private]
Definition at line 813 of file copying-phase.h.
{ std::cout << "\n"; }
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::DoCloneBlock(), and v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitBlock().
TraceBlockUnreachable()
template<class AfterNext >
void v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::TraceBlockUnreachable () [inline], [private]
Definition at line 780 of file copying-phase.h.
{ std::cout << "> unreachable\n\n"; }
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitBlock().
TraceOperationSkipped()
template<class AfterNext >
void v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::TraceOperationSkipped () [inline], [private]
Definition at line 779 of file copying-phase.h.
{ std::cout << "> skipped\n\n"; }
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitOpNoMappingUpdate().
TraceReductionResult()
template<class AfterNext >
void v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::TraceReductionResult (Block * current_block, OpIndex first_output_index, OpIndex new_index) [inline], [private]
Definition at line 781 of file copying-phase.h.
                                               {
    if (new_index < first_output_index) {
      // The operation was replaced with an already existing one.
      std::cout << "> #n" << new_index.id() << "\n";
    }
    bool before_arrow = new_index >= first_output_index;
    for (const Operation& op : Asm().output_graph().operations(
             first_output_index, Asm().output_graph().next_operation_index())) {
      OpIndex index = Asm().output_graph().Index(op);
      const char* prefix;
      if (index == new_index) {
        prefix = ">";
        before_arrow = false;
      } else if (before_arrow) {
        prefix = " ";
      } else {
        prefix = " ";
      }
      std::cout << prefix << " n" << index.id() << ": "
                << PaddingSpace{5 - CountDecimalDigits(index.id())}
                << OperationPrintStyle{Asm().output_graph().Get(index), "#n"}
                << "\n";
      if (op.IsBlockTerminator() && Asm().current_block() &&
          Asm().current_block() != current_block) {
        current_block = &Asm().output_graph().Get(
            BlockIndex(current_block->index().id() + 1));
        std::cout << "new " << PrintAsBlockHeader{*current_block} << "\n";
      }
    }
    std::cout << "\n";
  }
References v8::internal::compiler::turboshaft::CountDecimalDigits(), v8::internal::compiler::turboshaft::OpIndex::id(), v8::internal::compiler::turboshaft::BlockIndex::id(), v8::internal::compiler::turboshaft::Block::index(), and v8::internal::index.
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitOpNoMappingUpdate().
TraceReductionStart()
template<class AfterNext >
void v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::TraceReductionStart (OpIndex index) [inline], [private]
Definition at line 773 of file copying-phase.h.
                                          {
    std::cout << " o" << index.id() << ": "
              << PaddingSpace{5 - CountDecimalDigits(index.id())}
              << OperationPrintStyle{Asm().input_graph().Get(index), "#o"}
              << "\n";
  }
References v8::internal::compiler::turboshaft::CountDecimalDigits(), and v8::internal::index.
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitOpNoMappingUpdate().
turn_loop_without_backedge_into_merge()
template<class AfterNext >
bool* v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::turn_loop_without_backedge_into_merge () [inline]
Definition at line 163 of file copying-phase.h.
                                                {
    return &turn_loop_without_backedge_into_merge_;
  }
References v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::turn_loop_without_backedge_into_merge_.
VisitAllBlocks()
template<class AfterNext >
template<bool trace_reduction>
void v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitAllBlocks () [inline], [private]
Definition at line 483 of file copying-phase.h.
                        {
    base::SmallVector<const Block*, 128> visit_stack;
    visit_stack.push_back(&Asm().input_graph().StartBlock());
    while (!visit_stack.empty()) {
      const Block* block = visit_stack.back();
      visit_stack.pop_back();
      VisitBlock<trace_reduction>(block);
      ProcessWaitingCloningAndInlining<trace_reduction>();
      for (Block* child = block->LastChild(); child != nullptr;
           child = child->NeighboringChild()) {
        visit_stack.push_back(child);
      }
    }
  }
References v8::base::SmallVector< T, kSize, Allocator >::back(), v8::base::SmallVector< T, kSize, Allocator >::empty(), v8::internal::compiler::turboshaft::DominatorForwardTreeNode< Derived >::LastChild(), v8::base::SmallVector< T, kSize, Allocator >::pop_back(), and v8::base::SmallVector< T, kSize, Allocator >::push_back().
VisitBlock()
template<class AfterNext >
template<bool trace_reduction>
void v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitBlock (const Block * input_block) [inline], [private]
Definition at line 501 of file copying-phase.h.
                                            {
    if (tick_counter_) tick_counter_->TickAndMaybeEnterSafepoint();
    Asm().SetCurrentOrigin(OpIndex::Invalid());
    current_block_needs_variables_ =
        blocks_needing_variables_.Contains(input_block->index().id());
    if constexpr (trace_reduction) {
      std::cout << "\nold " << PrintAsBlockHeader{*input_block} << "\n";
      std::cout << "new "
                << PrintAsBlockHeader{*MapToNewGraph(input_block),
                                      Asm().output_graph().next_block_index()}
                << "\n";
    }
    Block* new_block = MapToNewGraph(input_block);
    if (Asm().Bind(new_block)) {
      VisitBlockBody<CanHavePhis::kYes, ForCloning::kNo, trace_reduction>(
          input_block);
      if constexpr (trace_reduction) TraceBlockFinished();
    } else {
      if constexpr (trace_reduction) TraceBlockUnreachable();
    }
    // If we eliminate a loop backedge, we need to turn the loop into a
    // single-predecessor merge block.
    if (!turn_loop_without_backedge_into_merge_) return;
    const Operation& last_op = input_block->LastOperation(Asm().input_graph());
    if (auto* final_goto = last_op.TryCast<GotoOp>()) {
      if (final_goto->destination->IsLoop()) {
        if (input_block->index() >= final_goto->destination->index()) {
          Asm().FinalizeLoop(MapToNewGraph(final_goto->destination));
        } else {
          // We have a forward jump to a loop, rather than a backedge. We
          // don't need to do anything.
        }
      }
    }
  }
References v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::Bind(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::blocks_needing_variables_, v8::internal::BitVector::Contains(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::current_block_needs_variables_, v8::internal::compiler::turboshaft::BlockIndex::id(), v8::internal::compiler::turboshaft::Block::index(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::turboshaft::Block::LastOperation(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::MapToNewGraph(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::tick_counter_, v8::internal::TickCounter::TickAndMaybeEnterSafepoint(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::TraceBlockFinished(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::TraceBlockUnreachable(), v8::internal::compiler::turboshaft::Operation::TryCast(), and v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::turn_loop_without_backedge_into_merge_.
VisitBlockBody()
template<class AfterNext >
template<CanHavePhis can_have_phis, ForCloning for_cloning, bool trace_reduction>
void v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitBlockBody (const Block * input_block, int added_block_phi_input = -1) [inline], [private]
Definition at line 543 of file copying-phase.h.
                                                      {
    DCHECK_NOT_NULL(Asm().current_block());
    current_input_block_ = input_block;
    // Phis could be mutually recursive, for instance (in a loop header):
    //
    // p1 = phi(a, p2)
    // p2 = phi(b, p1)
    //
    // In this case, if we are currently unrolling the loop and visiting this
    // loop header that is now part of the loop body, then if we visit Phis
    // and emit new mapping (with CreateOldToNewMapping) as we go along, we
    // would visit p1 and emit a mapping saying "p1 = p2", and use this
    // mapping when visiting p2, then we'd map p2 to p2 instead of p1. To
    // overcome this issue, we first visit the Phis of the loop, emit the new
    // phis, and record the new mapping in a side-table ({new_phi_values}).
    // Then, we visit all of the operations of the loop and commit the new
    // mappings: phis were emitted before using the old mapping, and all of
    // the other operations will use the new mapping (as they should).
    //
    // Note that Phis are not always at the begining of blocks, but when they
    // aren't, they can't have inputs from the current block (except on their
    // backedge for loop phis, but they start as PendingLoopPhis without
    // backedge input), so visiting all Phis first is safe.
    // Visiting Phis and collecting their new OpIndices.
    base::SmallVector<OpIndex, 64> new_phi_values;
    if constexpr (can_have_phis == CanHavePhis::kYes) {
      for (OpIndex index : Asm().input_graph().OperationIndices(*input_block)) {
        if (ShouldSkipOperation(Asm().input_graph().Get(index))) continue;
        DCHECK_NOT_NULL(Asm().current_block());
        if (Asm().input_graph().Get(index).template Is<PhiOp>()) {
          OpIndex new_index;
          if constexpr (for_cloning == ForCloning::kYes) {
            // When cloning a block, it only has a single predecessor, and Phis
            // should therefore be removed and be replaced by the input
            // corresponding to this predecessor.
            DCHECK_NE(added_block_phi_input, -1);
            // This Phi has been cloned/inlined, and has thus now a single
            // predecessor, and shouldn't be a Phi anymore.
            new_index = MapToNewGraph(
                Asm().input_graph().Get(index).input(added_block_phi_input));
          } else {
            new_index =
                VisitOpNoMappingUpdate<trace_reduction>(index, input_block);
          }
          new_phi_values.push_back(new_index);
          if (!Asm().current_block()) {
            // A reducer has detected, based on the Phis of the block that were
            // visited so far, that we are in unreachable code (or, less likely,
            // decided, based on some Phis only, to jump away from this block?).
            return;
          }
        }
      }
    }
    DCHECK_NOT_NULL(Asm().current_block());
    // Visiting everything, updating Phi mappings, and emitting non-phi
    // operations.
    int phi_num = 0;
    bool stopped_early = false;
    for (OpIndex index : base::IterateWithoutLast(
             Asm().input_graph().OperationIndices(*input_block))) {
      if (ShouldSkipOperation(Asm().input_graph().Get(index))) continue;
      const Operation& op = Asm().input_graph().Get(index);
      if constexpr (can_have_phis == CanHavePhis::kYes) {
        if (op.Is<PhiOp>()) {
          CreateOldToNewMapping(index, new_phi_values[phi_num++]);
          continue;
        }
      }
      // Blocks with a single predecessor (for which CanHavePhis might be kNo)
      // can still have phis if they used to be loop header that were turned
      // into regular blocks.
      DCHECK_IMPLIES(op.Is<PhiOp>(), op.input_count == 1);
      if (!VisitOpAndUpdateMapping<trace_reduction>(index, input_block)) {
        stopped_early = true;
        break;
      }
    }
    // If the last operation of the loop above (= the one-before-last operation
    // of the block) was lowered to an unconditional deopt/trap/something like
    // that, then current_block will now be null, and there is no need visit the
    // last operation of the block.
    if (stopped_early || Asm().current_block() == nullptr) return;
    // The final operation (which should be a block terminator) of the block
    // is processed separately, because if it's a Goto to a block with a
    // single predecessor, we'll inline it. (we could have had a check `if (op
    // is a Goto)` in the loop above, but since this can only be true for the
    // last operation, we instead extracted it here to make things faster).
    const Operation& terminator =
        input_block->LastOperation(Asm().input_graph());
    DCHECK(terminator.IsBlockTerminator());
    VisitBlockTerminator<trace_reduction>(terminator, input_block);
  }
References v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::CreateOldToNewMapping(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::current_input_block_, v8::internal::DCHECK(), DCHECK_IMPLIES, DCHECK_NE, DCHECK_NOT_NULL, v8::internal::compiler::turboshaft::Get(), v8::internal::index, v8::internal::compiler::turboshaft::Operation::input_count, v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::turboshaft::Operation::IsBlockTerminator(), v8::base::IterateWithoutLast(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::kYes, v8::internal::compiler::turboshaft::Block::LastOperation(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::MapToNewGraph(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), and v8::internal::compiler::turboshaft::ShouldSkipOperation().
VisitBlockTerminator()
template<class AfterNext >
template<bool trace_reduction>
void v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitBlockTerminator (const Operation & terminator, const Block * input_block) [inline], [private]
Definition at line 711 of file copying-phase.h.
                                                      {
    if (Asm().CanAutoInlineBlocksWithSinglePredecessor() &&
        terminator.Is<GotoOp>()) {
      Block* destination = terminator.Cast<GotoOp>().destination;
      if (destination->PredecessorCount() == 1) {
        block_to_inline_now_ = destination;
        return;
      }
    }
    // Just going through the regular VisitOp function.
    OpIndex index = Asm().input_graph().Index(terminator);
    VisitOpAndUpdateMapping<trace_reduction>(index, input_block);
  }
References v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::block_to_inline_now_, v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::index, v8::internal::compiler::turboshaft::Operation::Is(), and v8::internal::compiler::turboshaft::Block::PredecessorCount().
VisitGraph()
template<class AfterNext >
template<bool trace_reduction>
void v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitGraph () [inline]
Definition at line 116 of file copying-phase.h.
                    {
    Asm().Analyze();
    // Creating initial old-to-new Block mapping.
    for (Block& input_block : Asm().modifiable_input_graph().blocks()) {
      block_mapping_[input_block.index()] = Asm().output_graph().NewBlock(
          input_block.IsLoop() ? Block::Kind::kLoopHeader : Block::Kind::kMerge,
          &input_block);
    }
    // Visiting the graph.
    VisitAllBlocks<trace_reduction>();
    Finalize();
  }
References v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::block_mapping_, v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::Finalize(), v8::internal::compiler::turboshaft::Block::kLoopHeader, and v8::internal::compiler::turboshaft::Block::kMerge.
VisitOpAndUpdateMapping()
template<class AfterNext >
template<bool trace_reduction>
bool v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitOpAndUpdateMapping (OpIndex index, const Block * input_block) [inline], [private]
Definition at line 644 of file copying-phase.h.
                                                                        {
    if (Asm().current_block() == nullptr) return false;
    OpIndex new_index =
        VisitOpNoMappingUpdate<trace_reduction>(index, input_block);
    const Operation& op = Asm().input_graph().Get(index);
    if (CanBeUsedAsInput(op) && new_index.valid()) {
      CreateOldToNewMapping(index, new_index);
    }
    return true;
  }
References v8::internal::compiler::turboshaft::CanBeUsedAsInput(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::CreateOldToNewMapping(), v8::internal::index, and v8::internal::compiler::turboshaft::OpIndex::valid().
VisitOpNoMappingUpdate()
template<class AfterNext >
template<bool trace_reduction>
OpIndex v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitOpNoMappingUpdate (OpIndex index, const Block * input_block) [inline], [private]
Definition at line 656 of file copying-phase.h.
                                                                          {
    Block* current_block = Asm().current_block();
    DCHECK_NOT_NULL(current_block);
    Asm().SetCurrentOrigin(index);
    current_block->SetOrigin(input_block);
    OpIndex first_output_index = Asm().output_graph().next_operation_index();
    USE(first_output_index);
    const Operation& op = Asm().input_graph().Get(index);
    if constexpr (trace_reduction) TraceReductionStart(index);
    if (ShouldSkipOperation(op)) {
      if constexpr (trace_reduction) TraceOperationSkipped();
      return OpIndex::Invalid();
    }
    OpIndex new_index;
    switch (op.opcode) {
#define EMIT_INSTR_CASE(Name) \
  case Opcode::k##Name: \
    if (MayThrow(Opcode::k##Name)) return OpIndex::Invalid(); \
    new_index = Asm().ReduceInputGraph##Name(index, op.Cast<Name##Op>()); \
    break;
      TURBOSHAFT_OPERATION_LIST(EMIT_INSTR_CASE)
#undef EMIT_INSTR_CASE
    }
    if constexpr (trace_reduction) {
      if (CanBeUsedAsInput(op) && !new_index.valid()) {
        TraceOperationSkipped();
      } else {
        TraceReductionResult(current_block, first_output_index, new_index);
      }
    }
#ifdef DEBUG
    DCHECK_IMPLIES(new_index.valid(),
                   Asm().output_graph().BelongsToThisGraph(new_index));
    if (V8_UNLIKELY(v8_flags.turboshaft_verify_reductions)) {
      if (new_index.valid()) {
        const Operation& new_op = Asm().output_graph().Get(new_index);
        if (!new_op.Is<TupleOp>()) {
          // Checking that the outputs_rep of the new operation are the same as
          // the old operation. (except for tuples, since they don't have
          // outputs_rep)
          DCHECK_EQ(new_op.outputs_rep().size(), op.outputs_rep().size());
          for (size_t i = 0; i < new_op.outputs_rep().size(); ++i) {
            DCHECK(new_op.outputs_rep()[i].AllowImplicitRepresentationChangeTo(
                op.outputs_rep()[i],
                Asm().output_graph().IsCreatedFromTurbofan()));
          }
        }
        Asm().Verify(index, new_index);
      }
    }
#endif // DEBUG
    return new_index;
  }
References v8::internal::compiler::turboshaft::CanBeUsedAsInput(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, DCHECK_NOT_NULL, EMIT_INSTR_CASE, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::turboshaft::Operation::opcode, v8::internal::compiler::turboshaft::Operation::outputs_rep(), v8::internal::compiler::turboshaft::Block::SetOrigin(), v8::internal::compiler::turboshaft::ShouldSkipOperation(), size(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::TraceOperationSkipped(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::TraceReductionResult(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::TraceReductionStart(), TURBOSHAFT_OPERATION_LIST, USE, v8::internal::v8_flags, V8_UNLIKELY, and v8::internal::compiler::turboshaft::OpIndex::valid().
Friends And Related Function Documentation
ReducerBaseForwarder
template<class AfterNext >
template<typename N >
friend class ReducerBaseForwarder [friend]
Definition at line 90 of file copying-phase.h.
WasmRevecReducer
template<class AfterNext >
template<typename N >
friend class WasmRevecReducer [friend]
Definition at line 92 of file copying-phase.h.
Member Data Documentation
block_mapping_
template<class AfterNext >
FixedBlockSidetable<Block*> v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::block_mapping_ [private]
Definition at line 990 of file copying-phase.h.
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::CloneSubGraph(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::MapToNewGraph(), and v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitGraph().
block_to_inline_now_
template<class AfterNext >
Block* v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::block_to_inline_now_ = nullptr [private]
Definition at line 1016 of file copying-phase.h.
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::InlineWaitingBlock(), and v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitBlockTerminator().
blocks_needing_variables_
template<class AfterNext >
BitVector v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::blocks_needing_variables_ [private]
Definition at line 1005 of file copying-phase.h.
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::CloneAndInlineBlock(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::CloneBlockAndGoto(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::CloneSubGraph(), and v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitBlock().
blocks_to_clone_
template<class AfterNext >
ZoneVector<BlockToClone> v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::blocks_to_clone_ [private]
Definition at line 1030 of file copying-phase.h.
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::CloneBlockAndGoto(), and v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::ProcessWaitingCloningAndInlining().
current_block_needs_variables_
template<class AfterNext >
bool v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::current_block_needs_variables_ = false [private]
Definition at line 995 of file copying-phase.h.
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::CloneAndInlineBlock(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::CreateOldToNewMapping(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::DoCloneBlock(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::InlineWaitingBlock(), and v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitBlock().
current_input_block_
template<class AfterNext >
const Block* v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::current_input_block_ [private]
Definition at line 984 of file copying-phase.h.
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::current_input_block(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::ResolvePhi(), and v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitBlockBody().
info_
template<class AfterNext >
OptimizedCompilationInfo* v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::info_ = Asm().data()->info() [private]
Definition at line 981 of file copying-phase.h.
input_graph_
template<class AfterNext >
Graph& v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::input_graph_ [private]
Definition at line 980 of file copying-phase.h.
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::Finalize().
old_opindex_to_variables
template<class AfterNext >
FixedOpIndexSidetable<MaybeVariable> v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::old_opindex_to_variables [private]
Definition at line 1008 of file copying-phase.h.
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::GetVariableFor(), and v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::SetVariableFor().
op_mapping_
template<class AfterNext >
FixedOpIndexSidetable<OpIndex> v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::op_mapping_ [private]
Definition at line 987 of file copying-phase.h.
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::CreateOldToNewMapping(), and v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::MapToNewGraph().
tick_counter_
template<class AfterNext >
TickCounter* const v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::tick_counter_ = info_ ? &info_->tick_counter() : nullptr [private]
Definition at line 982 of file copying-phase.h.
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitBlock().
turn_loop_without_backedge_into_merge_
template<class AfterNext >
bool v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::turn_loop_without_backedge_into_merge_ = true [private]
Definition at line 1001 of file copying-phase.h.
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::turn_loop_without_backedge_into_merge(), and v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitBlock().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/assembler.h
/mnt/V8SourceCode/src/compiler/turboshaft/copying-phase.h