v8::internal::EmbedderGraphImpl Class Reference
Classes
struct Edge
class V8NodeImpl
Public Member Functions
Node * V8Node (const v8::Local< v8::Value > &value) final
Returns a node corresponding to the given V8 value.
Node * V8Node (const v8::Local< v8::Data > &data) final
Returns a node corresponding to the given V8 value.
Node * AddNode (std::unique_ptr< Node > node) final
Adds the given node to the graph and takes ownership of the node.
void AddEdge (Node *from, Node *to, const char *name) final
Adds an edge that represents a strong reference from the given node |from| to the given node |to|.
void AddNativeSize (size_t size) final
Adds a count of bytes that are not associated with any particular Node.
size_t native_size () const
const std::vector< std::unique_ptr< Node > > & nodes ()
const std::vector< Edge > & edges ()
Private Attributes
std::vector< std::unique_ptr< Node > > nodes_
std::vector< Edge > edges_
size_t native_size_ = 0
Detailed Description
Definition at line 3005 of file heap-snapshot-generator.cc.
Member Function Documentation
AddEdge()
void v8::internal::EmbedderGraphImpl::AddEdge (Node * from, Node * to, const char * name) [inline], [final], [virtual]
Adds an edge that represents a strong reference from the given node |from| to the given node |to|.
The nodes must be added to the graph before calling this function.
If name is nullptr, the edge will have auto-increment indexes, otherwise it will be named accordingly.
Implements v8::EmbedderGraph.
Definition at line 3050 of file heap-snapshot-generator.cc.
                                                             {
    edges_.push_back({from, to, name});
  }
References edges_, and v8::internal::name.
AddNativeSize()
void v8::internal::EmbedderGraphImpl::AddNativeSize (size_t size) [inline], [final], [virtual]
Adds a count of bytes that are not associated with any particular Node.
An embedder may use this to represent the size of nodes which were omitted from this EmbedderGraph despite being retained by the graph, or other overhead costs. This number will contribute to the total size in a heap snapshot, without being represented in the object graph.
Reimplemented from v8::EmbedderGraph.
Definition at line 3054 of file heap-snapshot-generator.cc.
{ native_size_ += size; }
References native_size_, and size().
AddNode()
Node* v8::internal::EmbedderGraphImpl::AddNode (std::unique_ptr< Node > node) [inline], [final], [virtual]
Adds the given node to the graph and takes ownership of the node.
Returns a raw pointer to the node that is valid while the graph is alive.
Implements v8::EmbedderGraph.
Definition at line 3044 of file heap-snapshot-generator.cc.
                                                {
    Node* result = node.get();
    nodes_.push_back(std::move(node));
    return result;
  }
References nodes_, and v8::base::internal::result.
Referenced by V8Node().
edges()
const std::vector<Edge>& v8::internal::EmbedderGraphImpl::edges () [inline]
Definition at line 3058 of file heap-snapshot-generator.cc.
{ return edges_; }
References edges_.
native_size()
size_t v8::internal::EmbedderGraphImpl::native_size () const [inline]
Definition at line 3055 of file heap-snapshot-generator.cc.
{ return native_size_; }
References native_size_.
nodes()
const std::vector<std::unique_ptr<Node> >& v8::internal::EmbedderGraphImpl::nodes () [inline]
Definition at line 3057 of file heap-snapshot-generator.cc.
{ return nodes_; }
References nodes_.
V8Node() [1/2]
Node* v8::internal::EmbedderGraphImpl::V8Node (const v8::Local< v8::Data > & value) [inline], [final], [virtual]
Returns a node corresponding to the given V8 value.
Ownership is not transferred. The result pointer is valid while the graph is alive.
For API compatibility, this default implementation just checks that the data is a v8::Value and forward it to the variant that takes v8::Value, which is currently required to be implemented. In the future we'll remove the v8::Value variant, and make this variant that takes v8::Data abstract instead. If the embedder subclasses v8::EmbedderGraph and also use v8::TracedReference<v8::Data>, they must override this variant.
Reimplemented from v8::EmbedderGraph.
Definition at line 3038 of file heap-snapshot-generator.cc.
                                                  {
    DirectHandle<Object> object = v8::Utils::OpenDirectHandle(*data);
    DCHECK(!object.is_null());
    return AddNode(std::unique_ptr<Node>(new V8NodeImpl(*object)));
  }
References AddNode(), v8::internal::DCHECK(), and v8::Utils::OpenDirectHandle().
V8Node() [2/2]
Node* v8::internal::EmbedderGraphImpl::V8Node (const v8::Local< v8::Value > & value) [inline], [final], [virtual]
Returns a node corresponding to the given V8 value.
Ownership is not transferred. The result pointer is valid while the graph is alive.
For now the variant that takes v8::Data is not marked as abstract for compatibility, but embedders who subclass EmbedderGraph are expected to implement it. Then in the implementation of the variant that takes v8::Value, they can simply forward the call to the one that takes v8::Local<v8::Data>.
Implements v8::EmbedderGraph.
Definition at line 3033 of file heap-snapshot-generator.cc.
                                                    {
    v8::Local<v8::Data> data = value;
    return V8Node(data);
  }
References v8::internal::value.
Member Data Documentation
edges_
std::vector<Edge> v8::internal::EmbedderGraphImpl::edges_ [private]
Definition at line 3062 of file heap-snapshot-generator.cc.
Referenced by AddEdge(), and edges().
native_size_
size_t v8::internal::EmbedderGraphImpl::native_size_ = 0 [private]
Definition at line 3063 of file heap-snapshot-generator.cc.
Referenced by AddNativeSize(), and native_size().
nodes_
std::vector<std::unique_ptr<Node> > v8::internal::EmbedderGraphImpl::nodes_ [private]
Definition at line 3061 of file heap-snapshot-generator.cc.
Referenced by AddNode(), and nodes().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/profiler/heap-snapshot-generator.cc