v8_inspector::V8Console Class Reference
#include <v8-console.h>
Classes
class CommandLineAPIScope
Public Member Functions
v8::Local< v8::Object > createCommandLineAPI (v8::Local< v8::Context > context, int sessionId)
void installMemoryGetter (v8::Local< v8::Context > context, v8::Local< v8::Object > console)
void installAsyncStackTaggingAPI (v8::Local< v8::Context > context, v8::Local< v8::Object > console)
void cancelConsoleTask (TaskInfo *taskInfo)
std::map< void *, std::unique_ptr< TaskInfo > > & AllConsoleTasksForTest ()
V8Console (V8InspectorImpl *inspector)
Private Types
using CommandLineAPIData = std::pair< V8Console *, int >
Private Member Functions
void Debug (const v8::debug::ConsoleCallArguments &, const v8::debug::ConsoleContext &consoleContext) override
void Error (const v8::debug::ConsoleCallArguments &, const v8::debug::ConsoleContext &consoleContext) override
void Info (const v8::debug::ConsoleCallArguments &, const v8::debug::ConsoleContext &consoleContext) override
void Log (const v8::debug::ConsoleCallArguments &, const v8::debug::ConsoleContext &consoleContext) override
void Warn (const v8::debug::ConsoleCallArguments &, const v8::debug::ConsoleContext &consoleContext) override
void Dir (const v8::debug::ConsoleCallArguments &, const v8::debug::ConsoleContext &consoleContext) override
void DirXml (const v8::debug::ConsoleCallArguments &, const v8::debug::ConsoleContext &consoleContext) override
void Table (const v8::debug::ConsoleCallArguments &, const v8::debug::ConsoleContext &consoleContext) override
void Trace (const v8::debug::ConsoleCallArguments &, const v8::debug::ConsoleContext &consoleContext) override
void Group (const v8::debug::ConsoleCallArguments &, const v8::debug::ConsoleContext &consoleContext) override
void GroupCollapsed (const v8::debug::ConsoleCallArguments &, const v8::debug::ConsoleContext &consoleContext) override
void GroupEnd (const v8::debug::ConsoleCallArguments &, const v8::debug::ConsoleContext &consoleContext) override
void Clear (const v8::debug::ConsoleCallArguments &, const v8::debug::ConsoleContext &consoleContext) override
void Count (const v8::debug::ConsoleCallArguments &, const v8::debug::ConsoleContext &consoleContext) override
void CountReset (const v8::debug::ConsoleCallArguments &, const v8::debug::ConsoleContext &consoleContext) override
void Assert (const v8::debug::ConsoleCallArguments &, const v8::debug::ConsoleContext &consoleContext) override
void Profile (const v8::debug::ConsoleCallArguments &, const v8::debug::ConsoleContext &consoleContext) override
void ProfileEnd (const v8::debug::ConsoleCallArguments &, const v8::debug::ConsoleContext &consoleContext) override
void Time (const v8::debug::ConsoleCallArguments &, const v8::debug::ConsoleContext &consoleContext) override
void TimeLog (const v8::debug::ConsoleCallArguments &, const v8::debug::ConsoleContext &consoleContext) override
void TimeEnd (const v8::debug::ConsoleCallArguments &, const v8::debug::ConsoleContext &consoleContext) override
void TimeStamp (const v8::debug::ConsoleCallArguments &, const v8::debug::ConsoleContext &consoleContext) override
void memoryGetterCallback (const v8::FunctionCallbackInfo< v8::Value > &)
void memorySetterCallback (const v8::FunctionCallbackInfo< v8::Value > &)
void createTask (const v8::FunctionCallbackInfo< v8::Value > &)
void runTask (const v8::FunctionCallbackInfo< v8::Value > &)
void keysCallback (const v8::FunctionCallbackInfo< v8::Value > &, int sessionId)
void valuesCallback (const v8::FunctionCallbackInfo< v8::Value > &, int sessionId)
void debugFunctionCallback (const v8::FunctionCallbackInfo< v8::Value > &, int sessionId)
void undebugFunctionCallback (const v8::FunctionCallbackInfo< v8::Value > &, int sessionId)
void monitorFunctionCallback (const v8::FunctionCallbackInfo< v8::Value > &, int sessionId)
void unmonitorFunctionCallback (const v8::FunctionCallbackInfo< v8::Value > &, int sessionId)
void lastEvaluationResultCallback (const v8::FunctionCallbackInfo< v8::Value > &, int sessionId)
void inspectCallback (const v8::FunctionCallbackInfo< v8::Value > &, int sessionId)
void copyCallback (const v8::FunctionCallbackInfo< v8::Value > &, int sessionId)
void inspectedObject (const v8::FunctionCallbackInfo< v8::Value > &, int sessionId, unsigned num)
void inspectedObject0 (const v8::FunctionCallbackInfo< v8::Value > &info, int sessionId)
void inspectedObject1 (const v8::FunctionCallbackInfo< v8::Value > &info, int sessionId)
void inspectedObject2 (const v8::FunctionCallbackInfo< v8::Value > &info, int sessionId)
void inspectedObject3 (const v8::FunctionCallbackInfo< v8::Value > &info, int sessionId)
void inspectedObject4 (const v8::FunctionCallbackInfo< v8::Value > &info, int sessionId)
void queryObjectsCallback (const v8::FunctionCallbackInfo< v8::Value > &info, int sessionId)
v8::Local< v8::Private > taskInfoKey ()
v8::Local< v8::ObjectTemplate > taskTemplate ()
Static Private Member Functions
template<void(V8Console::*)(const v8::FunctionCallbackInfo< v8::Value > &) func>
static void call (const v8::FunctionCallbackInfo< v8::Value > &info)
template<void(V8Console::*)(const v8::FunctionCallbackInfo< v8::Value > &, int) func>
static void call (const v8::FunctionCallbackInfo< v8::Value > &info)
template<void(V8Console::*)(const v8::debug::ConsoleCallArguments &, const v8::debug::ConsoleContext &) func>
static void call (const v8::FunctionCallbackInfo< v8::Value > &info)
Private Attributes
V8InspectorImpl * m_inspector
std::map< void *, std::unique_ptr< TaskInfo > > m_tasks
v8::Global< v8::Private > m_taskInfoKey
v8::Global< v8::ObjectTemplate > m_taskTemplate
Friends
class TaskInfo
Detailed Description
Definition at line 29 of file v8-console.h.
Member Typedef Documentation
CommandLineAPIData
using v8_inspector::V8Console::CommandLineAPIData = std::pair<V8Console*, int> [private]
Definition at line 135 of file v8-console.h.
Constructor & Destructor Documentation
V8Console()
v8_inspector::V8Console::V8Console (V8InspectorImpl * inspector) [explicit]
Definition at line 222 of file v8-console.cc.
: m_inspector(inspector) {}
Member Function Documentation
AllConsoleTasksForTest()
std::map<void*, std::unique_ptr<TaskInfo> >& v8_inspector::V8Console::AllConsoleTasksForTest () [inline]
Definition at line 39 of file v8-console.h.
                                                                   {
    return m_tasks;
  }
References m_tasks.
Assert()
void v8_inspector::V8Console::Assert (const v8::debug::ConsoleCallArguments & info, const v8::debug::ConsoleContext & consoleContext) [override], [private], [virtual]
Reimplemented from v8::debug::ConsoleDelegate.
Definition at line 358 of file v8-console.cc.
                                                                    {
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.inspector"), "V8Console::Assert");
  ConsoleHelper helper(info, consoleContext, m_inspector);
  DCHECK(!helper.firstArgToBoolean(false));
  v8::Isolate* isolate = m_inspector->isolate();
  v8::LocalVector<v8::Value> arguments(isolate);
  for (int i = 1; i < info.Length(); ++i) arguments.push_back(info[i]);
  if (info.Length() < 2)
    arguments.push_back(toV8String(isolate, String16("console.assert")));
  helper.reportCall(ConsoleAPIType::kAssert,
                    {arguments.begin(), arguments.end()});
  m_inspector->debugger()->breakProgramOnAssert(helper.groupId());
}
References v8::LocalVector< T >::begin(), v8_inspector::V8Debugger::breakProgramOnAssert(), DCHECK, v8_inspector::V8InspectorImpl::debugger(), v8::LocalVector< T >::end(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8_inspector::V8InspectorImpl::isolate(), v8_inspector::kAssert, v8::debug::ConsoleCallArguments::Length(), m_inspector, v8::LocalVector< T >::push_back(), v8_inspector::toV8String(), TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT0.
call() [1/3]
template<void(V8Console::*)(const v8::FunctionCallbackInfo< v8::Value > &) func>
static void v8_inspector::V8Console::call (const v8::FunctionCallbackInfo< v8::Value > & info) [inline], [static], [private]
Definition at line 130 of file v8-console.h.
                                                                {
    V8Console* console =
        static_cast<V8Console*>(info.Data().As<v8::External>()->Value());
    (console->*func)(info);
  }
References v8::FunctionCallbackInfo< T >::Data().
call() [2/3]
template<void(V8Console::*)(const v8::FunctionCallbackInfo< v8::Value > &, int) func>
static void v8_inspector::V8Console::call (const v8::FunctionCallbackInfo< v8::Value > & info) [inline], [static], [private]
Definition at line 138 of file v8-console.h.
                                                                {
    CommandLineAPIData* data = static_cast<CommandLineAPIData*>(
        info.Data().As<v8::ArrayBuffer>()->GetBackingStore()->Data());
    (data->first->*func)(info, data->second);
  }
References v8::ArrayBuffer::Data(), and v8::FunctionCallbackInfo< T >::Data().
call() [3/3]
template<void(V8Console::*)(const v8::debug::ConsoleCallArguments &, const v8::debug::ConsoleContext &) func>
static void v8_inspector::V8Console::call (const v8::FunctionCallbackInfo< v8::Value > & info) [inline], [static], [private]
Definition at line 145 of file v8-console.h.
                                                                {
    CommandLineAPIData* data = static_cast<CommandLineAPIData*>(
        info.Data().As<v8::ArrayBuffer>()->GetBackingStore()->Data());
    v8::debug::ConsoleCallArguments args(info);
    (data->first->*func)(args, v8::debug::ConsoleContext());
  }
References v8::base::args, v8::ArrayBuffer::Data(), and v8::FunctionCallbackInfo< T >::Data().
cancelConsoleTask()
void v8_inspector::V8Console::cancelConsoleTask (TaskInfo * taskInfo)
Definition at line 593 of file v8-console.cc.
                                                    {
  m_inspector->asyncTaskCanceled(taskInfo->Id());
  m_tasks.erase(taskInfo->Id());
}
References v8_inspector::V8InspectorImpl::asyncTaskCanceled(), v8_inspector::TaskInfo::Id(), m_inspector, and m_tasks.
Referenced by v8_inspector::TaskInfo::Cancel().
Clear()
void v8_inspector::V8Console::Clear (const v8::debug::ConsoleCallArguments & info, const v8::debug::ConsoleContext & consoleContext) [override], [private], [virtual]
Reimplemented from v8::debug::ConsoleDelegate.
Definition at line 315 of file v8-console.cc.
                                                                   {
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.inspector"), "V8Console::Clear");
  ConsoleHelper helper(info, consoleContext, m_inspector);
  if (!helper.groupId()) return;
  m_inspector->client()->consoleClear(helper.groupId());
  helper.reportCallWithDefaultArgument(ConsoleAPIType::kClear,
                                       String16("console.clear"));
}
References v8_inspector::V8InspectorImpl::client(), v8_inspector::V8InspectorClient::consoleClear(), v8_inspector::kClear, m_inspector, TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT0.
copyCallback()
void v8_inspector::V8Console::copyCallback (const v8::FunctionCallbackInfo< v8::Value > & info, int sessionId) [private]
Definition at line 776 of file v8-console.cc.
                                            {
  if (info.Length() < 1) return;
  inspectImpl(info, info[0], sessionId, kCopyToClipboard, m_inspector);
}
References v8_inspector::inspectImpl(), v8_inspector::anonymous_namespace{v8-console.cc}::kCopyToClipboard, v8::FunctionCallbackInfo< T >::Length(), and m_inspector.
Count()
void v8_inspector::V8Console::Count (const v8::debug::ConsoleCallArguments & info, const v8::debug::ConsoleContext & consoleContext) [override], [private], [virtual]
Reimplemented from v8::debug::ConsoleDelegate.
Definition at line 325 of file v8-console.cc.
                                                                   {
  TRACE_EVENT_BEGIN0(TRACE_DISABLED_BY_DEFAULT("v8.inspector"),
                     "V8Console::Count");
  ConsoleHelper helper(info, consoleContext, m_inspector);
  String16 label =
      toProtocolString(m_inspector->isolate(), helper.firstArgToString());
  int count = helper.consoleMessageStorage()->count(helper.contextId(),
                                                    consoleContext.id(), label);
  helper.reportCallWithArgument(ConsoleAPIType::kCount,
                                label + ": " + String16::fromInteger(count));
  TRACE_EVENT_END2(TRACE_DISABLED_BY_DEFAULT("v8.inspector"),
                   "V8Console::Count", "label",
                   TRACE_STR_COPY(label.utf8().c_str()), "count", count);
}
References v8_inspector::String16::fromInteger(), v8::debug::ConsoleContext::id(), v8_inspector::V8InspectorImpl::isolate(), v8_inspector::kCount, m_inspector, v8_inspector::toProtocolString(), TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT_BEGIN0, TRACE_EVENT_END2, TRACE_STR_COPY, and v8_inspector::String16::utf8().
CountReset()
void v8_inspector::V8Console::CountReset (const v8::debug::ConsoleCallArguments & info, const v8::debug::ConsoleContext & consoleContext) [override], [private], [virtual]
Reimplemented from v8::debug::ConsoleDelegate.
Definition at line 341 of file v8-console.cc.
                                                                        {
  TRACE_EVENT_BEGIN0(TRACE_DISABLED_BY_DEFAULT("v8.inspector"),
                     "V8Console::CountReset");
  ConsoleHelper helper(info, consoleContext, m_inspector);
  String16 label =
      toProtocolString(m_inspector->isolate(), helper.firstArgToString());
  if (!helper.consoleMessageStorage()->countReset(helper.contextId(),
                                                  consoleContext.id(), label)) {
    helper.reportCallWithArgument(ConsoleAPIType::kWarning,
                                  "Count for '" + label + "' does not exist");
  }
  TRACE_EVENT_END1(TRACE_DISABLED_BY_DEFAULT("v8.inspector"),
                   "V8Console::CountReset", "label",
                   TRACE_STR_COPY(label.utf8().c_str()));
}
References v8::debug::ConsoleContext::id(), v8_inspector::V8InspectorImpl::isolate(), v8_inspector::kWarning, m_inspector, v8_inspector::toProtocolString(), TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT_BEGIN0, TRACE_EVENT_END1, TRACE_STR_COPY, and v8_inspector::String16::utf8().
createCommandLineAPI()
v8::Local< v8::Object > v8_inspector::V8Console::createCommandLineAPI (v8::Local< v8::Context > context, int sessionId)
Definition at line 849 of file v8-console.cc.
                                               {
  v8::Isolate* isolate = v8::Isolate::GetCurrent();
  v8::MicrotasksScope microtasksScope(context,
                                      v8::MicrotasksScope::kDoNotRunMicrotasks);
  v8::Local<v8::Object> commandLineAPI = v8::Object::New(isolate);
  bool success = commandLineAPI->SetPrototypeV2(context, v8::Null(isolate))
                     .FromMaybe(false);
  DCHECK(success);
  USE(success);
  v8::Local<v8::ArrayBuffer> data =
      v8::ArrayBuffer::New(isolate, sizeof(CommandLineAPIData));
  *static_cast<CommandLineAPIData*>(data->GetBackingStore()->Data()) =
      CommandLineAPIData(this, sessionId);
  createBoundFunctionProperty(context, commandLineAPI, data, "dir",
                              &V8Console::call<&V8Console::Dir>);
  createBoundFunctionProperty(context, commandLineAPI, data, "dirxml",
                              &V8Console::call<&V8Console::DirXml>);
  createBoundFunctionProperty(context, commandLineAPI, data, "profile",
                              &V8Console::call<&V8Console::Profile>);
  createBoundFunctionProperty(context, commandLineAPI, data, "profileEnd",
                              &V8Console::call<&V8Console::ProfileEnd>);
  createBoundFunctionProperty(context, commandLineAPI, data, "clear",
                              &V8Console::call<&V8Console::Clear>);
  createBoundFunctionProperty(context, commandLineAPI, data, "table",
                              &V8Console::call<&V8Console::Table>);
  createBoundFunctionProperty(context, commandLineAPI, data, "keys",
                              &V8Console::call<&V8Console::keysCallback>,
                              v8::SideEffectType::kHasNoSideEffect);
  createBoundFunctionProperty(context, commandLineAPI, data, "values",
                              &V8Console::call<&V8Console::valuesCallback>,
                              v8::SideEffectType::kHasNoSideEffect);
  createBoundFunctionProperty(
      context, commandLineAPI, data, "debug",
      &V8Console::call<&V8Console::debugFunctionCallback>);
  createBoundFunctionProperty(
      context, commandLineAPI, data, "undebug",
      &V8Console::call<&V8Console::undebugFunctionCallback>);
  createBoundFunctionProperty(
      context, commandLineAPI, data, "monitor",
      &V8Console::call<&V8Console::monitorFunctionCallback>);
  createBoundFunctionProperty(
      context, commandLineAPI, data, "unmonitor",
      &V8Console::call<&V8Console::unmonitorFunctionCallback>);
  createBoundFunctionProperty(context, commandLineAPI, data, "inspect",
                              &V8Console::call<&V8Console::inspectCallback>);
  createBoundFunctionProperty(context, commandLineAPI, data, "copy",
                              &V8Console::call<&V8Console::copyCallback>);
  createBoundFunctionProperty(
      context, commandLineAPI, data, "queryObjects",
      &V8Console::call<&V8Console::queryObjectsCallback>);
  createBoundFunctionProperty(
      context, commandLineAPI, data, "$_",
      &V8Console::call<&V8Console::lastEvaluationResultCallback>,
      v8::SideEffectType::kHasNoSideEffect);
  createBoundFunctionProperty(context, commandLineAPI, data, "$0",
                              &V8Console::call<&V8Console::inspectedObject0>,
                              v8::SideEffectType::kHasNoSideEffect);
  createBoundFunctionProperty(context, commandLineAPI, data, "$1",
                              &V8Console::call<&V8Console::inspectedObject1>,
                              v8::SideEffectType::kHasNoSideEffect);
  createBoundFunctionProperty(context, commandLineAPI, data, "$2",
                              &V8Console::call<&V8Console::inspectedObject2>,
                              v8::SideEffectType::kHasNoSideEffect);
  createBoundFunctionProperty(context, commandLineAPI, data, "$3",
                              &V8Console::call<&V8Console::inspectedObject3>,
                              v8::SideEffectType::kHasNoSideEffect);
  createBoundFunctionProperty(context, commandLineAPI, data, "$4",
                              &V8Console::call<&V8Console::inspectedObject4>,
                              v8::SideEffectType::kHasNoSideEffect);
  m_inspector->client()->installAdditionalCommandLineAPI(context,
                                                         commandLineAPI);
  return commandLineAPI;
}
References v8_inspector::V8InspectorImpl::client(), v8_inspector::anonymous_namespace{v8-console.cc}::createBoundFunctionProperty(), DCHECK, v8::Isolate::GetCurrent(), v8_inspector::V8InspectorClient::installAdditionalCommandLineAPI(), v8::MicrotasksScope::kDoNotRunMicrotasks, v8::kHasNoSideEffect, m_inspector, v8::Object::New(), v8::ArrayBuffer::New(), v8::Null(), v8::Object::SetPrototypeV2(), and USE.
Referenced by v8_inspector::InjectedScript::commandLineAPI().
createTask()
void v8_inspector::V8Console::createTask (const v8::FunctionCallbackInfo< v8::Value > & info) [private]
Definition at line 494 of file v8-console.cc.
                                                                      {
  v8::Isolate* isolate = info.GetIsolate();
  v8::debug::RecordAsyncStackTaggingCreateTaskCall(isolate);
  if (info.Length() < 1 || !info[0]->IsString() ||
      !info[0].As<v8::String>()->Length()) {
    isolate->ThrowError("First argument must be a non-empty string.");
    return;
  }
  v8::Local<v8::Object> task = taskTemplate()
                                   ->NewInstance(isolate->GetCurrentContext())
                                   .ToLocalChecked();
  auto taskInfo = std::make_unique<TaskInfo>(isolate, this, task);
  void* taskId = taskInfo->Id();
  auto [iter, inserted] = m_tasks.emplace(taskId, std::move(taskInfo));
  CHECK(inserted);
  String16 nameArgument = toProtocolString(isolate, info[0].As<v8::String>());
  StringView taskName =
      StringView(nameArgument.characters16(), nameArgument.length());
  m_inspector->asyncTaskScheduled(taskName, taskId, /* recurring */ true);
  info.GetReturnValue().Set(task);
}
References v8_inspector::V8InspectorImpl::asyncTaskScheduled(), v8_inspector::String16::characters16(), CHECK, v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::FunctionCallbackInfo< T >::Length(), v8::String::Length(), v8_inspector::String16::length(), m_inspector, m_tasks, v8::debug::RecordAsyncStackTaggingCreateTaskCall(), taskTemplate(), v8::Isolate::ThrowError(), and v8_inspector::toProtocolString().
Debug()
void v8_inspector::V8Console::Debug (const v8::debug::ConsoleCallArguments & info, const v8::debug::ConsoleContext & consoleContext) [override], [private], [virtual]
Reimplemented from v8::debug::ConsoleDelegate.
Definition at line 224 of file v8-console.cc.
                                                                   {
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.inspector"), "V8Console::Debug");
  ConsoleHelper(info, consoleContext, m_inspector)
      .reportCall(ConsoleAPIType::kDebug);
}
References v8_inspector::kDebug, m_inspector, TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT0.
debugFunctionCallback()
void v8_inspector::V8Console::debugFunctionCallback (const v8::FunctionCallbackInfo< v8::Value > & info, int sessionId) [private]
Definition at line 670 of file v8-console.cc.
                                                                {
  v8::debug::ConsoleCallArguments args(info);
  ConsoleHelper helper(args, v8::debug::ConsoleContext(), m_inspector);
  v8::Local<v8::Function> function;
  v8::Local<v8::String> condition;
  if (!helper.firstArgAsFunction().ToLocal(&function)) return;
  if (args.Length() > 1 && args[1]->IsString()) {
    condition = args[1].As<v8::String>();
  }
  setFunctionBreakpoint(helper, sessionId, function,
                        V8DebuggerAgentImpl::DebugCommandBreakpointSource,
                        condition, true);
}
References v8::base::args, v8_inspector::V8DebuggerAgentImpl::DebugCommandBreakpointSource, m_inspector, and v8_inspector::setFunctionBreakpoint().
Dir()
void v8_inspector::V8Console::Dir (const v8::debug::ConsoleCallArguments & info, const v8::debug::ConsoleContext & consoleContext) [override], [private], [virtual]
Reimplemented from v8::debug::ConsoleDelegate.
Definition at line 259 of file v8-console.cc.
                                                                 {
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.inspector"), "V8Console::Dir");
  ConsoleHelper(info, consoleContext, m_inspector)
      .reportCall(ConsoleAPIType::kDir);
}
References v8_inspector::kDir, m_inspector, TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT0.
DirXml()
void v8_inspector::V8Console::DirXml (const v8::debug::ConsoleCallArguments & info, const v8::debug::ConsoleContext & consoleContext) [override], [private], [virtual]
Reimplemented from v8::debug::ConsoleDelegate.
Definition at line 266 of file v8-console.cc.
                                                                    {
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.inspector"), "V8Console::DirXml");
  ConsoleHelper(info, consoleContext, m_inspector)
      .reportCall(ConsoleAPIType::kDirXML);
}
References v8_inspector::kDirXML, m_inspector, TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT0.
Error()
void v8_inspector::V8Console::Error (const v8::debug::ConsoleCallArguments & info, const v8::debug::ConsoleContext & consoleContext) [override], [private], [virtual]
Reimplemented from v8::debug::ConsoleDelegate.
Definition at line 231 of file v8-console.cc.
                                                                   {
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.inspector"), "V8Console::Error");
  ConsoleHelper(info, consoleContext, m_inspector)
      .reportCall(ConsoleAPIType::kError);
}
References v8_inspector::kError, m_inspector, TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT0.
Group()
void v8_inspector::V8Console::Group (const v8::debug::ConsoleCallArguments & info, const v8::debug::ConsoleContext & consoleContext) [override], [private], [virtual]
Reimplemented from v8::debug::ConsoleDelegate.
Definition at line 288 of file v8-console.cc.
                                                                   {
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.inspector"), "V8Console::Group");
  ConsoleHelper(info, consoleContext, m_inspector)
      .reportCallWithDefaultArgument(ConsoleAPIType::kStartGroup,
                                     String16("console.group"));
}
References v8_inspector::kStartGroup, m_inspector, TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT0.
GroupCollapsed()
void v8_inspector::V8Console::GroupCollapsed (const v8::debug::ConsoleCallArguments & info, const v8::debug::ConsoleContext & consoleContext) [override], [private], [virtual]
Reimplemented from v8::debug::ConsoleDelegate.
Definition at line 296 of file v8-console.cc.
                                                 {
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.inspector"),
               "V8Console::GroupCollapsed");
  ConsoleHelper(info, consoleContext, m_inspector)
      .reportCallWithDefaultArgument(ConsoleAPIType::kStartGroupCollapsed,
                                     String16("console.groupCollapsed"));
}
References v8_inspector::kStartGroupCollapsed, m_inspector, TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT0.
GroupEnd()
void v8_inspector::V8Console::GroupEnd (const v8::debug::ConsoleCallArguments & info, const v8::debug::ConsoleContext & consoleContext) [override], [private], [virtual]
Reimplemented from v8::debug::ConsoleDelegate.
Definition at line 306 of file v8-console.cc.
                                                                      {
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.inspector"),
               "V8Console::GroupEnd");
  ConsoleHelper(info, consoleContext, m_inspector)
      .reportCallWithDefaultArgument(ConsoleAPIType::kEndGroup,
                                     String16("console.groupEnd"));
}
References v8_inspector::kEndGroup, m_inspector, TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT0.
Info()
void v8_inspector::V8Console::Info (const v8::debug::ConsoleCallArguments & info, const v8::debug::ConsoleContext & consoleContext) [override], [private], [virtual]
Reimplemented from v8::debug::ConsoleDelegate.
Definition at line 238 of file v8-console.cc.
                                                                  {
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.inspector"), "V8Console::Info");
  ConsoleHelper(info, consoleContext, m_inspector)
      .reportCall(ConsoleAPIType::kInfo);
}
References v8_inspector::kInfo, m_inspector, TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT0.
inspectCallback()
void v8_inspector::V8Console::inspectCallback (const v8::FunctionCallbackInfo< v8::Value > & info, int sessionId) [private]
Definition at line 770 of file v8-console.cc.
                                               {
  if (info.Length() < 1) return;
  inspectImpl(info, info[0], sessionId, kRegular, m_inspector);
}
References v8_inspector::inspectImpl(), v8::FunctionCallbackInfo< T >::Length(), and m_inspector.
inspectedObject()
void v8_inspector::V8Console::inspectedObject (const v8::FunctionCallbackInfo< v8::Value > & info, int sessionId, unsigned num) [private]
Definition at line 805 of file v8-console.cc.
                                                             {
  DCHECK_GT(V8InspectorSessionImpl::kInspectedObjectBufferSize, num);
  v8::debug::ConsoleCallArguments args(info);
  ConsoleHelper helper(args, v8::debug::ConsoleContext(), m_inspector);
  if (V8InspectorSessionImpl* session = helper.session(sessionId)) {
    V8InspectorSession::Inspectable* object = session->inspectedObject(num);
    v8::Isolate* isolate = info.GetIsolate();
    if (object)
      info.GetReturnValue().Set(object->get(isolate->GetCurrentContext()));
    else
      info.GetReturnValue().Set(v8::Undefined(isolate));
  }
}
References v8::base::args, DCHECK_GT, v8_inspector::V8InspectorSession::Inspectable::get(), v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8_inspector::V8InspectorSessionImpl::kInspectedObjectBufferSize, m_inspector, and v8::Undefined().
Referenced by inspectedObject0(), inspectedObject1(), inspectedObject2(), inspectedObject3(), and inspectedObject4().
inspectedObject0()
void v8_inspector::V8Console::inspectedObject0 (const v8::FunctionCallbackInfo< v8::Value > & info, int sessionId) [inline], [private]
Definition at line 179 of file v8-console.h.
                                       {
    inspectedObject(info, sessionId, 0);
  }
References inspectedObject().
inspectedObject1()
void v8_inspector::V8Console::inspectedObject1 (const v8::FunctionCallbackInfo< v8::Value > & info, int sessionId) [inline], [private]
Definition at line 183 of file v8-console.h.
                                       {
    inspectedObject(info, sessionId, 1);
  }
References inspectedObject().
inspectedObject2()
void v8_inspector::V8Console::inspectedObject2 (const v8::FunctionCallbackInfo< v8::Value > & info, int sessionId) [inline], [private]
Definition at line 187 of file v8-console.h.
                                       {
    inspectedObject(info, sessionId, 2);
  }
References inspectedObject().
inspectedObject3()
void v8_inspector::V8Console::inspectedObject3 (const v8::FunctionCallbackInfo< v8::Value > & info, int sessionId) [inline], [private]
Definition at line 191 of file v8-console.h.
                                       {
    inspectedObject(info, sessionId, 3);
  }
References inspectedObject().
inspectedObject4()
void v8_inspector::V8Console::inspectedObject4 (const v8::FunctionCallbackInfo< v8::Value > & info, int sessionId) [inline], [private]
Definition at line 195 of file v8-console.h.
                                       {
    inspectedObject(info, sessionId, 4);
  }
References inspectedObject().
installAsyncStackTaggingAPI()
void v8_inspector::V8Console::installAsyncStackTaggingAPI (v8::Local< v8::Context > context, v8::Local< v8::Object > console)
Definition at line 837 of file v8-console.cc.
                                                                       {
  v8::Isolate* isolate = v8::Isolate::GetCurrent();
  v8::Local<v8::External> data = v8::External::New(isolate, this);
  v8::MicrotasksScope microtasksScope(context,
                                      v8::MicrotasksScope::kDoNotRunMicrotasks);
  createBoundFunctionProperty(context, console, data, "createTask",
                              &V8Console::call<&V8Console::createTask>);
}
References v8_inspector::anonymous_namespace{v8-console.cc}::createBoundFunctionProperty(), v8::Isolate::GetCurrent(), v8::MicrotasksScope::kDoNotRunMicrotasks, and v8::External::New().
Referenced by v8_inspector::InspectedContext::InspectedContext().
installMemoryGetter()
void v8_inspector::V8Console::installMemoryGetter (v8::Local< v8::Context > context, v8::Local< v8::Object > console)
Definition at line 820 of file v8-console.cc.
                                                               {
  v8::Isolate* isolate = v8::Isolate::GetCurrent();
  v8::Local<v8::External> data = v8::External::New(isolate, this);
  console->SetAccessorProperty(
      toV8StringInternalized(isolate, "memory"),
      v8::Function::New(
          context, &V8Console::call<&V8Console::memoryGetterCallback>, data, 0,
          v8::ConstructorBehavior::kThrow, v8::SideEffectType::kHasNoSideEffect)
          .ToLocalChecked(),
      v8::Function::New(context,
                        &V8Console::call<&V8Console::memorySetterCallback>,
                        data, 0, v8::ConstructorBehavior::kThrow)
          .ToLocalChecked(),
      static_cast<v8::PropertyAttribute>(v8::None));
}
References v8::Isolate::GetCurrent(), v8::kHasNoSideEffect, v8::kThrow, v8::External::New(), v8::Function::New(), v8::None, v8::Object::SetAccessorProperty(), and v8_inspector::toV8StringInternalized().
Referenced by v8_inspector::InspectedContext::InspectedContext().
keysCallback()
void v8_inspector::V8Console::keysCallback (const v8::FunctionCallbackInfo< v8::Value > & info, int sessionId) [private]
Definition at line 617 of file v8-console.cc.
                                            {
  v8::Isolate* isolate = info.GetIsolate();
  info.GetReturnValue().Set(v8::Array::New(isolate));
  v8::debug::ConsoleCallArguments args(info);
  ConsoleHelper helper(args, v8::debug::ConsoleContext(), m_inspector);
  v8::Local<v8::Object> obj;
  if (!helper.firstArgAsObject().ToLocal(&obj)) return;
  v8::Local<v8::Array> names;
  if (!obj->GetOwnPropertyNames(isolate->GetCurrentContext()).ToLocal(&names))
    return;
  info.GetReturnValue().Set(names);
}
References v8::base::args, v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::Object::GetOwnPropertyNames(), v8::FunctionCallbackInfo< T >::GetReturnValue(), m_inspector, and v8::Array::New().
lastEvaluationResultCallback()
void v8_inspector::V8Console::lastEvaluationResultCallback (const v8::FunctionCallbackInfo< v8::Value > & info, int sessionId) [private]
Definition at line 734 of file v8-console.cc.
                                                                {
  v8::debug::ConsoleCallArguments args(info);
  ConsoleHelper helper(args, v8::debug::ConsoleContext(), m_inspector);
  InjectedScript* injectedScript = helper.injectedScript(sessionId);
  if (!injectedScript) return;
  info.GetReturnValue().Set(injectedScript->lastEvaluationResult());
}
References v8::base::args, v8::FunctionCallbackInfo< T >::GetReturnValue(), v8_inspector::InjectedScript::lastEvaluationResult(), and m_inspector.
Log()
void v8_inspector::V8Console::Log (const v8::debug::ConsoleCallArguments & info, const v8::debug::ConsoleContext & consoleContext) [override], [private], [virtual]
Reimplemented from v8::debug::ConsoleDelegate.
Definition at line 245 of file v8-console.cc.
                                                                 {
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.inspector"), "V8Console::Log");
  ConsoleHelper(info, consoleContext, m_inspector)
      .reportCall(ConsoleAPIType::kLog);
}
References v8_inspector::kLog, m_inspector, TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT0.
memoryGetterCallback()
void v8_inspector::V8Console::memoryGetterCallback (const v8::FunctionCallbackInfo< v8::Value > & info) [private]
Definition at line 476 of file v8-console.cc.
                                                 {
  v8::Local<v8::Value> memoryValue;
  if (!m_inspector->client()
           ->memoryInfo(info.GetIsolate(),
                        info.GetIsolate()->GetCurrentContext())
           .ToLocal(&memoryValue))
    return;
  info.GetReturnValue().Set(memoryValue);
}
References v8_inspector::V8InspectorImpl::client(), v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), m_inspector, v8_inspector::V8InspectorClient::memoryInfo(), and v8::MaybeLocal< T >::ToLocal().
memorySetterCallback()
void v8_inspector::V8Console::memorySetterCallback (const v8::FunctionCallbackInfo< v8::Value > & info) [private]
Definition at line 487 of file v8-console.cc.
                                                 {
  // We can't make the attribute readonly as it breaks existing code that relies
  // on being able to assign to console.memory in strict mode. Instead, the
  // setter just ignores the passed value. http://crbug.com/468611
}
monitorFunctionCallback()
void v8_inspector::V8Console::monitorFunctionCallback (const v8::FunctionCallbackInfo< v8::Value > & info, int sessionId) [private]
Definition at line 696 of file v8-console.cc.
                                                                {
  v8::debug::ConsoleCallArguments args(info);
  ConsoleHelper helper(args, v8::debug::ConsoleContext(), m_inspector);
  v8::Local<v8::Function> function;
  if (!helper.firstArgAsFunction().ToLocal(&function)) return;
  v8::Local<v8::Value> name = function->GetName();
  if (!name->IsString() || !name.As<v8::String>()->Length())
    name = function->GetInferredName();
  String16 functionName =
      toProtocolStringWithTypeCheck(info.GetIsolate(), name);
  String16Builder builder;
  builder.append("console.log(\"function ");
  if (functionName.isEmpty())
    builder.append("(anonymous function)");
  else
    builder.append(functionName);
  builder.append(
      " called\" + (typeof arguments !== \"undefined\" && arguments.length > 0 "
      "? \" with arguments: \" + Array.prototype.join.call(arguments, \", \") "
      ": \"\")) && false");
  setFunctionBreakpoint(helper, sessionId, function,
                        V8DebuggerAgentImpl::MonitorCommandBreakpointSource,
                        toV8String(info.GetIsolate(), builder.toString()),
                        true);
}
References v8_inspector::String16Builder::append(), v8::base::args, v8::FunctionCallbackInfo< T >::GetIsolate(), v8_inspector::String16::isEmpty(), v8::String::Length(), m_inspector, v8_inspector::V8DebuggerAgentImpl::MonitorCommandBreakpointSource, name, v8_inspector::setFunctionBreakpoint(), v8_inspector::toProtocolStringWithTypeCheck(), v8_inspector::String16Builder::toString(), and v8_inspector::toV8String().
Profile()
void v8_inspector::V8Console::Profile (const v8::debug::ConsoleCallArguments & info, const v8::debug::ConsoleContext & consoleContext) [override], [private], [virtual]
Reimplemented from v8::debug::ConsoleDelegate.
Definition at line 374 of file v8-console.cc.
                                                                     {
  TRACE_EVENT_BEGIN0(TRACE_DISABLED_BY_DEFAULT("v8.inspector"),
                     "V8Console::Profile");
  ConsoleHelper helper(info, consoleContext, m_inspector);
  String16 title =
      toProtocolString(m_inspector->isolate(), helper.firstArgToString());
  helper.forEachSession([&title](V8InspectorSessionImpl* session) {
    session->profilerAgent()->consoleProfile(title);
  });
  TRACE_EVENT_END1(TRACE_DISABLED_BY_DEFAULT("v8.inspector"),
                   "V8Console::Profile", "title",
                   TRACE_STR_COPY(title.utf8().c_str()));
}
References v8_inspector::V8InspectorImpl::isolate(), m_inspector, v8_inspector::V8InspectorSessionImpl::profilerAgent(), v8_inspector::toProtocolString(), TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT_BEGIN0, TRACE_EVENT_END1, TRACE_STR_COPY, and v8_inspector::String16::utf8().
ProfileEnd()
void v8_inspector::V8Console::ProfileEnd (const v8::debug::ConsoleCallArguments & info, const v8::debug::ConsoleContext & consoleContext) [override], [private], [virtual]
Reimplemented from v8::debug::ConsoleDelegate.
Definition at line 389 of file v8-console.cc.
                                                                        {
  TRACE_EVENT_BEGIN0(TRACE_DISABLED_BY_DEFAULT("v8.inspector"),
                     "V8Console::ProfileEnd");
  ConsoleHelper helper(info, consoleContext, m_inspector);
  String16 title =
      toProtocolString(m_inspector->isolate(), helper.firstArgToString());
  helper.forEachSession([&title](V8InspectorSessionImpl* session) {
    session->profilerAgent()->consoleProfileEnd(title);
  });
  TRACE_EVENT_END1(TRACE_DISABLED_BY_DEFAULT("v8.inspector"),
                   "V8Console::ProfileEnd", "title",
                   TRACE_STR_COPY(title.utf8().c_str()));
}
References v8_inspector::V8InspectorImpl::isolate(), m_inspector, v8_inspector::V8InspectorSessionImpl::profilerAgent(), v8_inspector::toProtocolString(), TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT_BEGIN0, TRACE_EVENT_END1, TRACE_STR_COPY, and v8_inspector::String16::utf8().
queryObjectsCallback()
void v8_inspector::V8Console::queryObjectsCallback (const v8::FunctionCallbackInfo< v8::Value > & info, int sessionId) [private]
Definition at line 782 of file v8-console.cc.
                                                                {
  if (info.Length() < 1) return;
  v8::Local<v8::Value> arg = info[0];
  if (arg->IsFunction()) {
    v8::Isolate* isolate = info.GetIsolate();
    v8::TryCatch tryCatch(isolate);
    v8::Local<v8::Value> prototype;
    if (arg.As<v8::Function>()
            ->Get(isolate->GetCurrentContext(),
                  toV8StringInternalized(isolate, "prototype"))
            .ToLocal(&prototype) &&
        prototype->IsObject()) {
      arg = prototype;
    }
    if (tryCatch.HasCaught()) {
      tryCatch.ReThrow();
      return;
    }
  }
  inspectImpl(info, arg, sessionId, kQueryObjects, m_inspector);
}
References v8::Local< T >::As(), v8::Object::Get(), v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::TryCatch::HasCaught(), v8_inspector::inspectImpl(), v8::Value::IsFunction(), v8_inspector::anonymous_namespace{v8-console.cc}::kQueryObjects, v8::FunctionCallbackInfo< T >::Length(), m_inspector, v8::internal::prototype, v8::TryCatch::ReThrow(), and v8_inspector::toV8StringInternalized().
runTask()
void v8_inspector::V8Console::runTask (const v8::FunctionCallbackInfo< v8::Value > & info) [private]
Definition at line 522 of file v8-console.cc.
                                                                   {
  v8::Isolate* isolate = info.GetIsolate();
  if (info.Length() < 1 || !info[0]->IsFunction()) {
    isolate->ThrowError("First argument must be a function.");
    return;
  }
  v8::Local<v8::Function> function = info[0].As<v8::Function>();
  v8::Local<v8::Object> task = info.This();
  v8::Local<v8::Value> maybeTaskExternal;
  if (!task->GetPrivate(isolate->GetCurrentContext(), taskInfoKey())
           .ToLocal(&maybeTaskExternal)) {
    // An exception is already thrown.
    return;
  }
  if (!maybeTaskExternal->IsExternal()) {
    isolate->ThrowError("'run' called with illegal receiver.");
    return;
  }
  v8::Local<v8::External> taskExternal = maybeTaskExternal.As<v8::External>();
  TaskInfo* taskInfo = reinterpret_cast<TaskInfo*>(taskExternal->Value());
  m_inspector->asyncTaskStarted(taskInfo->Id());
  {
#ifdef V8_USE_PERFETTO
    TRACE_EVENT(TRACE_DISABLED_BY_DEFAULT("v8.inspector"), "V8Console::runTask",
                "data", ([&](perfetto::TracedValue context) {
                  uint64_t trace_id = v8::tracing::TraceId();
                  auto dict = std::move(context).WriteDictionary();
                  v8::CpuProfiler::CpuProfiler::CollectSample(isolate,
                                                              trace_id);
                  dict.Add("sampleTraceId", trace_id);
                }));
#endif // V8_USE_PERFETTO
    v8::Local<v8::Value> result;
    if (function
            ->Call(isolate->GetCurrentContext(), v8::Undefined(isolate), 0, {})
            .ToLocal(&result)) {
      info.GetReturnValue().Set(result);
    }
  }
  m_inspector->asyncTaskFinished(taskInfo->Id());
}
References v8::Local< T >::As(), v8_inspector::V8InspectorImpl::asyncTaskFinished(), v8_inspector::V8InspectorImpl::asyncTaskStarted(), v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::Value::IsExternal(), v8::FunctionCallbackInfo< T >::Length(), m_inspector, v8::base::internal::result, taskInfoKey(), v8::FunctionCallbackInfo< T >::This(), v8::Isolate::ThrowError(), TRACE_DISABLED_BY_DEFAULT, v8::tracing::TraceId(), and v8::Undefined().
Table()
void v8_inspector::V8Console::Table (const v8::debug::ConsoleCallArguments & info, const v8::debug::ConsoleContext & consoleContext) [override], [private], [virtual]
Reimplemented from v8::debug::ConsoleDelegate.
Definition at line 273 of file v8-console.cc.
                                                                   {
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.inspector"), "V8Console::Table");
  ConsoleHelper(info, consoleContext, m_inspector)
      .reportCall(ConsoleAPIType::kTable);
}
References v8_inspector::kTable, m_inspector, TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT0.
taskInfoKey()
v8::Local< v8::Private > v8_inspector::V8Console::taskInfoKey () [private]
Definition at line 569 of file v8-console.cc.
                                          {
  v8::Isolate* isolate = m_inspector->isolate();
  if (m_taskInfoKey.IsEmpty()) {
    m_taskInfoKey.Reset(isolate, v8::Private::New(isolate));
  }
  return m_taskInfoKey.Get(isolate);
}
References v8::PersistentBase< T >::Get(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8_inspector::V8InspectorImpl::isolate(), m_inspector, m_taskInfoKey, v8::Private::New(), and v8::PersistentBase< T >::Reset().
Referenced by runTask(), and v8_inspector::TaskInfo::TaskInfo().
taskTemplate()
v8::Local< v8::ObjectTemplate > v8_inspector::V8Console::taskTemplate () [private]
Definition at line 577 of file v8-console.cc.
                                                  {
  v8::Isolate* isolate = m_inspector->isolate();
  if (!m_taskTemplate.IsEmpty()) {
    return m_taskTemplate.Get(isolate);
  }
  v8::Local<v8::External> data = v8::External::New(isolate, this);
  v8::Local<v8::ObjectTemplate> taskTemplate = v8::ObjectTemplate::New(isolate);
  v8::Local<v8::FunctionTemplate> funcTemplate = v8::FunctionTemplate::New(
      isolate, &V8Console::call<&V8Console::runTask>, data);
  taskTemplate->Set(isolate, "run", funcTemplate);
  m_taskTemplate.Reset(isolate, taskTemplate);
  return taskTemplate;
}
References v8::PersistentBase< T >::Get(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8_inspector::V8InspectorImpl::isolate(), m_inspector, m_taskTemplate, v8::FunctionTemplate::New(), v8::ObjectTemplate::New(), v8::External::New(), and v8::PersistentBase< T >::Reset().
Referenced by createTask().
Time()
void v8_inspector::V8Console::Time (const v8::debug::ConsoleCallArguments & info, const v8::debug::ConsoleContext & consoleContext) [override], [private], [virtual]
Reimplemented from v8::debug::ConsoleDelegate.
Definition at line 404 of file v8-console.cc.
                                                                  {
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.inspector"), "V8Console::Time");
  ConsoleHelper helper(info, consoleContext, m_inspector);
  v8::Local<v8::String> label = helper.firstArgToString();
  String16 protocolLabel = toProtocolString(m_inspector->isolate(), label);
  if (!helper.consoleMessageStorage()->time(
          helper.contextId(), consoleContext.id(), protocolLabel)) {
    helper.reportCallWithArgument(
        ConsoleAPIType::kWarning,
        "Timer '" + protocolLabel + "' already exists");
    return;
  }
  m_inspector->client()->consoleTime(m_inspector->isolate(), label);
}
References v8_inspector::V8InspectorImpl::client(), v8_inspector::V8InspectorClient::consoleTime(), v8::debug::ConsoleContext::id(), v8_inspector::V8InspectorImpl::isolate(), v8_inspector::kWarning, m_inspector, v8_inspector::toProtocolString(), TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT0.
TimeEnd()
void v8_inspector::V8Console::TimeEnd (const v8::debug::ConsoleCallArguments & info, const v8::debug::ConsoleContext & consoleContext) [override], [private], [virtual]
Reimplemented from v8::debug::ConsoleDelegate.
Definition at line 439 of file v8-console.cc.
                                                                     {
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.inspector"), "V8Console::TimeEnd");
  ConsoleHelper helper(info, consoleContext, m_inspector);
  v8::Local<v8::String> label = helper.firstArgToString();
  String16 protocolLabel = toProtocolString(m_inspector->isolate(), label);
  std::optional<double> elapsed = helper.consoleMessageStorage()->timeEnd(
      helper.contextId(), consoleContext.id(), protocolLabel);
  if (!elapsed.has_value()) {
    helper.reportCallWithArgument(
        ConsoleAPIType::kWarning,
        "Timer '" + protocolLabel + "' does not exist");
    return;
  }
  m_inspector->client()->consoleTimeEnd(m_inspector->isolate(), label);
  String16 message =
      protocolLabel + ": " + String16::fromDouble(elapsed.value()) + " ms";
  helper.reportCallWithArgument(ConsoleAPIType::kTimeEnd, message);
}
References v8_inspector::V8InspectorImpl::client(), v8_inspector::V8InspectorClient::consoleTimeEnd(), v8_inspector::String16::fromDouble(), v8::debug::ConsoleContext::id(), v8_inspector::V8InspectorImpl::isolate(), v8_inspector::kTimeEnd, v8_inspector::kWarning, m_inspector, v8_inspector::toProtocolString(), TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT0.
TimeLog()
void v8_inspector::V8Console::TimeLog (const v8::debug::ConsoleCallArguments & info, const v8::debug::ConsoleContext & consoleContext) [override], [private], [virtual]
Reimplemented from v8::debug::ConsoleDelegate.
Definition at line 420 of file v8-console.cc.
                                                                     {
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.inspector"), "V8Console::TimeLog");
  ConsoleHelper helper(info, consoleContext, m_inspector);
  v8::Local<v8::String> label = helper.firstArgToString();
  String16 protocolLabel = toProtocolString(m_inspector->isolate(), label);
  std::optional<double> elapsed = helper.consoleMessageStorage()->timeLog(
      helper.contextId(), consoleContext.id(), protocolLabel);
  if (!elapsed.has_value()) {
    helper.reportCallWithArgument(
        ConsoleAPIType::kWarning,
        "Timer '" + protocolLabel + "' does not exist");
    return;
  }
  String16 message =
      protocolLabel + ": " + String16::fromDouble(elapsed.value()) + " ms";
  helper.reportCallAndReplaceFirstArgument(ConsoleAPIType::kLog, message);
}
References v8_inspector::String16::fromDouble(), v8::debug::ConsoleContext::id(), v8_inspector::V8InspectorImpl::isolate(), v8_inspector::kLog, v8_inspector::kWarning, m_inspector, v8_inspector::toProtocolString(), TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT0.
TimeStamp()
void v8_inspector::V8Console::TimeStamp (const v8::debug::ConsoleCallArguments & info, const v8::debug::ConsoleContext & consoleContext) [override], [private], [virtual]
Reimplemented from v8::debug::ConsoleDelegate.
Definition at line 459 of file v8-console.cc.
                                                                       {
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.inspector"),
               "V8Console::TimeStamp");
  ConsoleHelper helper(info, consoleContext, m_inspector);
  v8::Local<v8::String> label = helper.firstArgToString();
  v8::Isolate* isolate = m_inspector->isolate();
  v8::LocalVector<v8::Value> args(isolate);
  args.reserve(info.Length());
  for (int i = 0; i < info.Length(); i++) {
    args.push_back(info[i]);
  }
  m_inspector->client()->consoleTimeStampWithArgs(isolate, label, args);
}
References v8::base::args, v8_inspector::V8InspectorImpl::client(), v8_inspector::V8InspectorClient::consoleTimeStampWithArgs(), v8_inspector::V8InspectorImpl::isolate(), v8::debug::ConsoleCallArguments::Length(), m_inspector, TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT0.
Trace()
void v8_inspector::V8Console::Trace (const v8::debug::ConsoleCallArguments & info, const v8::debug::ConsoleContext & consoleContext) [override], [private], [virtual]
Reimplemented from v8::debug::ConsoleDelegate.
Definition at line 280 of file v8-console.cc.
                                                                   {
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.inspector"), "V8Console::Trace");
  ConsoleHelper(info, consoleContext, m_inspector)
      .reportCallWithDefaultArgument(ConsoleAPIType::kTrace,
                                     String16("console.trace"));
}
References v8_inspector::kTrace, m_inspector, TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT0.
undebugFunctionCallback()
void v8_inspector::V8Console::undebugFunctionCallback (const v8::FunctionCallbackInfo< v8::Value > & info, int sessionId) [private]
Definition at line 685 of file v8-console.cc.
                                                                {
  v8::debug::ConsoleCallArguments args(info);
  ConsoleHelper helper(args, v8::debug::ConsoleContext(), m_inspector);
  v8::Local<v8::Function> function;
  if (!helper.firstArgAsFunction().ToLocal(&function)) return;
  setFunctionBreakpoint(helper, sessionId, function,
                        V8DebuggerAgentImpl::DebugCommandBreakpointSource,
                        v8::Local<v8::String>(), false);
}
References v8::base::args, v8_inspector::V8DebuggerAgentImpl::DebugCommandBreakpointSource, m_inspector, and v8_inspector::setFunctionBreakpoint().
unmonitorFunctionCallback()
void v8_inspector::V8Console::unmonitorFunctionCallback (const v8::FunctionCallbackInfo< v8::Value > & info, int sessionId) [private]
Definition at line 723 of file v8-console.cc.
                                                                {
  v8::debug::ConsoleCallArguments args(info);
  ConsoleHelper helper(args, v8::debug::ConsoleContext(), m_inspector);
  v8::Local<v8::Function> function;
  if (!helper.firstArgAsFunction().ToLocal(&function)) return;
  setFunctionBreakpoint(helper, sessionId, function,
                        V8DebuggerAgentImpl::MonitorCommandBreakpointSource,
                        v8::Local<v8::String>(), false);
}
References v8::base::args, m_inspector, v8_inspector::V8DebuggerAgentImpl::MonitorCommandBreakpointSource, and v8_inspector::setFunctionBreakpoint().
valuesCallback()
void v8_inspector::V8Console::valuesCallback (const v8::FunctionCallbackInfo< v8::Value > & info, int sessionId) [private]
Definition at line 632 of file v8-console.cc.
                                              {
  v8::Isolate* isolate = info.GetIsolate();
  info.GetReturnValue().Set(v8::Array::New(isolate));
  v8::debug::ConsoleCallArguments args(info);
  ConsoleHelper helper(args, v8::debug::ConsoleContext(), m_inspector);
  v8::Local<v8::Object> obj;
  if (!helper.firstArgAsObject().ToLocal(&obj)) return;
  v8::Local<v8::Array> names;
  v8::Local<v8::Context> context = isolate->GetCurrentContext();
  if (!obj->GetOwnPropertyNames(context).ToLocal(&names)) return;
  v8::Local<v8::Array> values = v8::Array::New(isolate, names->Length());
  for (uint32_t i = 0; i < names->Length(); ++i) {
    v8::Local<v8::Value> key;
    if (!names->Get(context, i).ToLocal(&key)) continue;
    v8::Local<v8::Value> value;
    if (!obj->Get(context, key).ToLocal(&value)) continue;
    createDataProperty(context, values, i, value);
  }
  info.GetReturnValue().Set(values);
}
References v8::base::args, v8_inspector::createDataProperty(), v8::Object::Get(), v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::Object::GetOwnPropertyNames(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::key, v8::Array::Length(), m_inspector, v8::Array::New(), v8::MaybeLocal< T >::ToLocal(), and v8::internal::value.
Warn()
void v8_inspector::V8Console::Warn (const v8::debug::ConsoleCallArguments & info, const v8::debug::ConsoleContext & consoleContext) [override], [private], [virtual]
Reimplemented from v8::debug::ConsoleDelegate.
Definition at line 252 of file v8-console.cc.
                                                                  {
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.inspector"), "V8Console::Warn");
  ConsoleHelper(info, consoleContext, m_inspector)
      .reportCall(ConsoleAPIType::kWarning);
}
References v8_inspector::kWarning, m_inspector, TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT0.
Friends And Related Function Documentation
TaskInfo
friend class TaskInfo [friend]
Definition at line 82 of file v8-console.h.
Member Data Documentation
m_inspector
V8InspectorImpl* v8_inspector::V8Console::m_inspector [private]
Definition at line 212 of file v8-console.h.
Referenced by Assert(), cancelConsoleTask(), Clear(), copyCallback(), Count(), CountReset(), createCommandLineAPI(), createTask(), Debug(), debugFunctionCallback(), Dir(), DirXml(), Error(), Group(), GroupCollapsed(), GroupEnd(), Info(), inspectCallback(), inspectedObject(), keysCallback(), lastEvaluationResultCallback(), Log(), memoryGetterCallback(), monitorFunctionCallback(), Profile(), ProfileEnd(), queryObjectsCallback(), runTask(), Table(), taskInfoKey(), taskTemplate(), Time(), TimeEnd(), TimeLog(), TimeStamp(), Trace(), undebugFunctionCallback(), unmonitorFunctionCallback(), valuesCallback(), and Warn().
m_taskInfoKey
v8::Global<v8::Private> v8_inspector::V8Console::m_taskInfoKey [private]
Definition at line 220 of file v8-console.h.
Referenced by taskInfoKey().
m_tasks
std::map<void*, std::unique_ptr<TaskInfo> > v8_inspector::V8Console::m_tasks [private]
Definition at line 216 of file v8-console.h.
Referenced by AllConsoleTasksForTest(), cancelConsoleTask(), and createTask().
m_taskTemplate
v8::Global<v8::ObjectTemplate> v8_inspector::V8Console::m_taskTemplate [private]
Definition at line 225 of file v8-console.h.
Referenced by taskTemplate().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/inspector/v8-console.h
/mnt/V8SourceCode/src/inspector/v8-console.cc