v8::internal::compiler::JSCreateEmptyLiteralArrayNode Class Reference
#include <js-operator.h>
Public Member Functions
constexpr JSCreateEmptyLiteralArrayNode (Node *node)
const FeedbackParameter & Parameters () const
Additional Inherited Members
Detailed Description
Definition at line 1663 of file js-operator.h.
Constructor & Destructor Documentation
JSCreateEmptyLiteralArrayNode()
constexpr v8::internal::compiler::JSCreateEmptyLiteralArrayNode::JSCreateEmptyLiteralArrayNode (Node * node) [inline], [explicit], [constexpr]
Definition at line 1665 of file js-operator.h.
      : JSNodeWrapperBase(node) {
    DCHECK_EQ(IrOpcode::kJSCreateEmptyLiteralArray, node->opcode());
  }
References DCHECK_EQ, v8::internal::compiler::NodeWrapper::node(), and v8::internal::compiler::Node::opcode().
Member Function Documentation
Parameters()
const FeedbackParameter& v8::internal::compiler::JSCreateEmptyLiteralArrayNode::Parameters () const [inline]
Definition at line 1670 of file js-operator.h.
                                              {
    return FeedbackParameterOf(node()->op());
  }
References v8::internal::compiler::FeedbackParameterOf(), and v8::internal::compiler::NodeWrapper::node().
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateEmptyLiteralArray().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h