v8::internal::WasmSuspendingObject Class Reference
#include <wasm-objects.h>
Static Public Member Functions
static V8_EXPORT_PRIVATE DirectHandle< WasmSuspendingObject > New (Isolate *isolate, DirectHandle< JSReceiver > callable)
Detailed Description
Definition at line 1538 of file wasm-objects.h.
Member Function Documentation
New()
DirectHandle< WasmSuspendingObject > v8::internal::WasmSuspendingObject::New (Isolate * isolate, DirectHandle< JSReceiver > callable) [static]
Definition at line 822 of file wasm-objects.cc.
                                                         {
  DirectHandle<JSFunction> suspending_ctor(
      isolate->native_context()->wasm_suspending_constructor(), isolate);
  auto suspending_obj = Cast<WasmSuspendingObject>(
      isolate->factory()->NewJSObject(suspending_ctor));
  suspending_obj->set_callable(*callable);
  return suspending_obj;
}
References v8::internal::Isolate::factory(), v8::internal::Isolate::native_context(), and v8::internal::Factory::NewJSObject().
Referenced by v8::anonymous_namespace{wasm-js.cc}::WebAssemblySuspendingImpl().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-objects.h
/mnt/V8SourceCode/src/wasm/wasm-objects.cc