v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename > Class Template Reference
Public Member Functions
StoreLoadInfo (const Graph *graph, const Op *op)
std::optional< OffsetDiff > operator- (const StoreLoadInfo< Op > &rhs) const
bool IsValid () const
const Operation * index () const
uint64_t offset () const
const Op * op () const
Private Member Functions
void SetInvalid ()
Private Attributes
const Op * op_
const Operation * base_ = nullptr
const Operation * index_ = nullptr
uint64_t offset_
Detailed Description
template<typename Op, typename = std::enable_if_t< std::is_same_v<Op, StoreOp> || std::is_same_v<Op, LoadOp> || std::is_same_v<Op, Simd128LoadTransformOp>>>
class v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >
Definition at line 87 of file wasm-revec-reducer.cc.
Constructor & Destructor Documentation
StoreLoadInfo()
template<typename Op , typename = std::enable_if_t< std::is_same_v<Op, StoreOp> || std::is_same_v<Op, LoadOp> || std::is_same_v<Op, Simd128LoadTransformOp>>>
v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::StoreLoadInfo (const Graph * graph, const Op * op) [inline]
Definition at line 89 of file wasm-revec-reducer.cc.
      : op_(op), offset_(op->offset) {
    base_ = &graph->Get(op->base());
    if constexpr (std::is_same_v<Op, Simd128LoadTransformOp>) {
      DCHECK_EQ(offset_, 0);
      const WordBinopOp* add_op = base_->TryCast<WordBinopOp>();
      if (!add_op || add_op->kind != WordBinopOp::Kind::kAdd ||
          add_op->rep != WordRepresentation::Word64()) {
        SetInvalid();
        return;
      }
      base_ = &graph->Get(add_op->left());
      const ConstantOp* const_op =
          graph->Get(add_op->right()).TryCast<ConstantOp>();
      if (!const_op) {
        SetInvalid();
        return;
      }
      offset_ = const_op->word64();
      index_ = &(graph->Get(op->index()));
    } else {
      if (!op->index().has_value()) {
        SetInvalid();
        return;
      }
      index_ = &(graph->Get(op->index().value()));
    }
    if (const ChangeOp* change_op = index_->TryCast<ChangeOp>()) {
      if (change_op->kind != ChangeOp::Kind::kZeroExtend) {
        TRACE("ChangeOp kind not supported for revectorization\n");
        SetInvalid();
        return;
      }
      index_ = &graph->Get(change_op->input());
      // If index_ is constant, add the constant to offset_ and set index_ to
      // nullptr
      if (const ConstantOp* const_op = index_->TryCast<ConstantOp>()) {
        DCHECK_EQ(const_op->kind, ConstantOp::Kind::kWord32);
        // Exceed uint32 limits.
        if (offset_ > std::numeric_limits<uint32_t>::max() -
                          static_cast<uint32_t>(const_op->word32())) {
          SetInvalid();
          return;
        }
        offset_ += static_cast<uint32_t>(const_op->word32());
        index_ = nullptr;
      }
    } else { // memory64
      if (const ConstantOp* const_op = index_->TryCast<ConstantOp>()) {
        DCHECK_EQ(const_op->kind, ConstantOp::Kind::kWord64);
        // Exceed uint64 limits.
        if (offset_ > std::numeric_limits<uint64_t>::max() -
                          static_cast<uint64_t>(const_op->word64())) {
          SetInvalid();
          return;
        }
        offset_ += static_cast<uint64_t>(const_op->word64());
        index_ = nullptr;
      }
    }
  }
References v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::base_, DCHECK_EQ, graph(), v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::index_, v8::internal::compiler::turboshaft::WordBinopOp::kAdd, v8::internal::compiler::turboshaft::WordBinopOp::kind, v8::internal::compiler::turboshaft::ConstantOp::kWord32, v8::internal::compiler::turboshaft::ConstantOp::kWord64, v8::internal::compiler::turboshaft::ChangeOp::kZeroExtend, v8::internal::compiler::turboshaft::WordBinopOp::left(), v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::offset_, v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::op(), v8::internal::compiler::turboshaft::WordBinopOp::rep, v8::internal::compiler::turboshaft::WordBinopOp::right(), v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::SetInvalid(), v8::internal::TRACE(), v8::internal::compiler::turboshaft::Operation::TryCast(), v8::internal::compiler::turboshaft::WordRepresentation::Word64(), and v8::internal::compiler::turboshaft::ConstantOp::word64().
Member Function Documentation
index()
template<typename Op , typename = std::enable_if_t< std::is_same_v<Op, StoreOp> || std::is_same_v<Op, LoadOp> || std::is_same_v<Op, Simd128LoadTransformOp>>>
const Operation* v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::index () const [inline]
Definition at line 178 of file wasm-revec-reducer.cc.
{ return index_; }
References v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::index_.
Referenced by v8::internal::compiler::turboshaft::StoreInfoCompare::operator()().
IsValid()
template<typename Op , typename = std::enable_if_t< std::is_same_v<Op, StoreOp> || std::is_same_v<Op, LoadOp> || std::is_same_v<Op, Simd128LoadTransformOp>>>
bool v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::IsValid () const [inline]
Definition at line 176 of file wasm-revec-reducer.cc.
{ return op_ != nullptr; }
References v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::op_.
Referenced by v8::internal::compiler::turboshaft::SLPTree::BuildTreeRec(), v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::operator-(), and v8::internal::compiler::turboshaft::WasmRevecAnalyzer::ProcessBlock().
offset()
template<typename Op , typename = std::enable_if_t< std::is_same_v<Op, StoreOp> || std::is_same_v<Op, LoadOp> || std::is_same_v<Op, Simd128LoadTransformOp>>>
uint64_t v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::offset () const [inline]
Definition at line 179 of file wasm-revec-reducer.cc.
{ return offset_; }
References v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::offset_.
Referenced by v8::internal::compiler::turboshaft::StoreInfoCompare::operator()().
op()
template<typename Op , typename = std::enable_if_t< std::is_same_v<Op, StoreOp> || std::is_same_v<Op, LoadOp> || std::is_same_v<Op, Simd128LoadTransformOp>>>
const Op* v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::op () const [inline]
Definition at line 180 of file wasm-revec-reducer.cc.
{ return op_; }
References v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::op_.
Referenced by v8::internal::compiler::turboshaft::WasmRevecAnalyzer::ProcessBlock(), and v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::StoreLoadInfo().
operator-()
template<typename Op , typename = std::enable_if_t< std::is_same_v<Op, StoreOp> || std::is_same_v<Op, LoadOp> || std::is_same_v<Op, Simd128LoadTransformOp>>>
std::optional<OffsetDiff> v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::operator- (const StoreLoadInfo< Op > & rhs) const [inline]
Definition at line 153 of file wasm-revec-reducer.cc.
                                                                        {
    DCHECK(IsValid() && rhs.IsValid());
    bool calculatable = base_ == rhs.base_ && index_ == rhs.index_;
    if constexpr (std::is_same_v<Op, Simd128LoadTransformOp>) {
      calculatable &= (op_->load_kind == rhs.op_->load_kind &&
                       op_->transform_kind == rhs.op_->transform_kind);
    } else {
      calculatable &= (op_->kind == rhs.op_->kind);
    }
    if constexpr (std::is_same_v<Op, StoreOp>) {
      // TODO(v8:12716) If one store has a full write barrier and the other has
      // no write barrier, consider combine them with a full write barrier.
      calculatable &= (op_->write_barrier == rhs.op_->write_barrier);
    }
    if (calculatable) {
      return OffsetDiff(offset_, rhs.offset_);
    }
    return {};
  }
References v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::base_, v8::internal::DCHECK(), v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::index_, v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::IsValid(), v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::offset_, and v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::op_.
SetInvalid()
template<typename Op , typename = std::enable_if_t< std::is_same_v<Op, StoreOp> || std::is_same_v<Op, LoadOp> || std::is_same_v<Op, Simd128LoadTransformOp>>>
void v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::SetInvalid () [inline], [private]
Definition at line 183 of file wasm-revec-reducer.cc.
{ op_ = nullptr; }
References v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::op_.
Referenced by v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::StoreLoadInfo().
Member Data Documentation
base_
template<typename Op , typename = std::enable_if_t< std::is_same_v<Op, StoreOp> || std::is_same_v<Op, LoadOp> || std::is_same_v<Op, Simd128LoadTransformOp>>>
const Operation* v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::base_ = nullptr [private]
Definition at line 186 of file wasm-revec-reducer.cc.
Referenced by v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::operator-(), and v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::StoreLoadInfo().
index_
template<typename Op , typename = std::enable_if_t< std::is_same_v<Op, StoreOp> || std::is_same_v<Op, LoadOp> || std::is_same_v<Op, Simd128LoadTransformOp>>>
const Operation* v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::index_ = nullptr [private]
Definition at line 187 of file wasm-revec-reducer.cc.
Referenced by v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::index(), v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::operator-(), and v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::StoreLoadInfo().
offset_
template<typename Op , typename = std::enable_if_t< std::is_same_v<Op, StoreOp> || std::is_same_v<Op, LoadOp> || std::is_same_v<Op, Simd128LoadTransformOp>>>
uint64_t v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::offset_ [private]
Definition at line 188 of file wasm-revec-reducer.cc.
Referenced by v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::offset(), v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::operator-(), and v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::StoreLoadInfo().
op_
template<typename Op , typename = std::enable_if_t< std::is_same_v<Op, StoreOp> || std::is_same_v<Op, LoadOp> || std::is_same_v<Op, Simd128LoadTransformOp>>>
const Op* v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::op_ [private]
Definition at line 185 of file wasm-revec-reducer.cc.
Referenced by v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::IsValid(), v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::op(), v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::operator-(), and v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::SetInvalid().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/wasm-revec-reducer.cc