v8::internal::JSTemporalPlainDateTime Class Reference
#include <js-temporal-objects.h>
Static Public Member Functions
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainDateTime > Constructor (Isolate *isolate, DirectHandle< JSFunction > target, DirectHandle< HeapObject > new_target, DirectHandle< Object > iso_year, DirectHandle< Object > iso_month, DirectHandle< Object > iso_day, DirectHandle< Object > hour, DirectHandle< Object > minute, DirectHandle< Object > second, DirectHandle< Object > millisecond, DirectHandle< Object > microsecond, DirectHandle< Object > nanosecond, DirectHandle< Object > calendar_like)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainDateTime > WithPlainTime (Isolate *isolate, DirectHandle< JSTemporalPlainDateTime > date_time, DirectHandle< Object > temporal_time_like)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainDateTime > From (Isolate *isolate, DirectHandle< Object > item, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Smi > Compare (Isolate *isolate, DirectHandle< Object > one, DirectHandle< Object > two)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Oddball > Equals (Isolate *isolate, DirectHandle< JSTemporalPlainDateTime > plain_date, DirectHandle< Object > other)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainYearMonth > ToPlainYearMonth (Isolate *isolate, DirectHandle< JSTemporalPlainDateTime > date_time)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainMonthDay > ToPlainMonthDay (Isolate *isolate, DirectHandle< JSTemporalPlainDateTime > date_time)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalZonedDateTime > ToZonedDateTime (Isolate *isolate, DirectHandle< JSTemporalPlainDateTime > date_time, DirectHandle< Object > temporal_time_zone_like, DirectHandle< Object > options_obj)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainDateTime > WithPlainDate (Isolate *isolate, DirectHandle< JSTemporalPlainDateTime > date_time, DirectHandle< Object > temporal_date_date_like)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSReceiver > GetISOFields (Isolate *isolate, DirectHandle< JSTemporalPlainDateTime > date_time)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainDateTime > With (Isolate *isolate, DirectHandle< JSTemporalPlainDateTime > date_time, DirectHandle< Object > temporal_date_time_like, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > ToJSON (Isolate *isolate, DirectHandle< JSTemporalPlainDateTime > date_time)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > ToLocaleString (Isolate *isolate, DirectHandle< JSTemporalPlainDateTime > date_time, DirectHandle< Object > locales, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > ToString (Isolate *isolate, DirectHandle< JSTemporalPlainDateTime > date_time, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainDateTime > Round (Isolate *isolate, DirectHandle< JSTemporalPlainDateTime > date_time, DirectHandle< Object > round_to)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalDuration > Until (Isolate *isolate, DirectHandle< JSTemporalPlainDateTime > date_time, DirectHandle< Object > other, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalDuration > Since (Isolate *isolate, DirectHandle< JSTemporalPlainDateTime > date_time, DirectHandle< Object > other, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainDateTime > Add (Isolate *isolate, DirectHandle< JSTemporalPlainDateTime > date_time, DirectHandle< Object > temporal_duration_like, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainDateTime > Subtract (Isolate *isolate, DirectHandle< JSTemporalPlainDateTime > date_time, DirectHandle< Object > temporal_duration_like, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainDateTime > Now (Isolate *isolate, DirectHandle< Object > calendar_like, DirectHandle< Object > temporal_time_zone_like)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainDateTime > NowISO (Isolate *isolate, DirectHandle< Object > temporal_time_zone_like)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainDate > ToPlainDate (Isolate *isolate, DirectHandle< JSTemporalPlainDateTime > date_time)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainTime > ToPlainTime (Isolate *isolate, DirectHandle< JSTemporalPlainDateTime > date_time)
Detailed Description
Definition at line 351 of file js-temporal-objects.h.
Member Function Documentation
Add()
MaybeDirectHandle< JSTemporalPlainDateTime > v8::internal::JSTemporalPlainDateTime::Add (Isolate * isolate, DirectHandle< JSTemporalPlainDateTime > date_time, DirectHandle< Object > temporal_duration_like, DirectHandle< Object > options) [static]
Definition at line 2237 of file js-temporal-objects.cc.
                                                                               {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
Compare()
MaybeDirectHandle< Smi > v8::internal::JSTemporalPlainDateTime::Compare (Isolate * isolate, DirectHandle< Object > one, DirectHandle< Object > two) [static]
Definition at line 2081 of file js-temporal-objects.cc.
                                  {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
Constructor()
MaybeDirectHandle< JSTemporalPlainDateTime > v8::internal::JSTemporalPlainDateTime::Constructor (Isolate * isolate, DirectHandle< JSFunction > target, DirectHandle< HeapObject > new_target, DirectHandle< Object > iso_year, DirectHandle< Object > iso_month, DirectHandle< Object > iso_day, DirectHandle< Object > hour, DirectHandle< Object > minute, DirectHandle< Object > second, DirectHandle< Object > millisecond, DirectHandle< Object > microsecond, DirectHandle< Object > nanosecond, DirectHandle< Object > calendar_like) [static]
Definition at line 1947 of file js-temporal-objects.cc.
                                        {
  // 1. If NewTarget is undefined, then
  if (IsUndefined(*new_target)) {
    // a. Throw a TypeError exception.
    THROW_NEW_ERROR(isolate,
                    NewTypeError(MessageTemplate::kMethodInvokedOnWrongType,
                                 isolate->factory()->NewStringFromAsciiChecked(
                                     "Temporal.PlainDateTime")));
  }
  // 2. Set isoYear to ?ToIntegerWithTruncation(isoYear).
  double y = 0;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, y, temporal::ToIntegerWithTruncation(isolate, iso_year_obj),
      kNullMaybeHandle);
  // 3. Set isoMonth to ?ToIntegerWithTruncation(isoMonth).
  double m = 0;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, m, temporal::ToIntegerWithTruncation(isolate, iso_month_obj),
      kNullMaybeHandle);
  // 4. Set isoDay to ?ToIntegerWithTruncation(isoDay).
  double d = 0;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, d, temporal::ToIntegerWithTruncation(isolate, iso_day_obj),
      kNullMaybeHandle);
  // 5. If hour is undefined, set hour to 0; else set hour to ?
  // ToIntegerWithTruncation(hour).
  double hour = 0;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, hour, temporal::ToIntegerWithTruncation(isolate, hour_obj),
      kNullMaybeHandle);
  // 6. If minute is undefined, set minute to 0; else set minute to ?
  // ToIntegerWithTruncation(minute).
  double minute = 0;
  if (!IsUndefined(*minute_obj)) {
    MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate, minute, temporal::ToIntegerWithTruncation(isolate, minute_obj),
        kNullMaybeHandle);
  }
  // 7. If second is undefined, set second to 0; else set second to ?
  // ToIntegerWithTruncation(second).
  double second = 0;
  if (!IsUndefined(*second_obj)) {
    MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate, second, temporal::ToIntegerWithTruncation(isolate, second_obj),
        kNullMaybeHandle);
  }
  // 8. If millisecond is undefined, set millisecond to 0; else set millisecond
  // to ? ToIntegerWithTruncation(millisecond).
  double millisecond = 0;
  if (!IsUndefined(*millisecond_obj)) {
    MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate, millisecond,
        temporal::ToIntegerWithTruncation(isolate, millisecond_obj),
        kNullMaybeHandle);
  }
  // 9. If microsecond is undefined, set microsecond to 0; else set microsecond
  // to ? ToIntegerWithTruncation(microsecond).
  double microsecond = 0;
  if (!IsUndefined(*microsecond_obj)) {
    MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate, microsecond,
        temporal::ToIntegerWithTruncation(isolate, microsecond_obj),
        kNullMaybeHandle);
  }
  // 10. If nanosecond is undefined, set nanosecond to 0; else set nanosecond to
  // ? ToIntegerWithTruncation(nanosecond).
  double nanosecond = 0;
  if (!IsUndefined(*nanosecond_obj)) {
    MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate, nanosecond,
        temporal::ToIntegerWithTruncation(isolate, nanosecond_obj),
        kNullMaybeHandle);
  }
  // 11. If calendar is undefined, set calendar to "iso8601".
  temporal_rs::AnyCalendarKind calendar = temporal_rs::AnyCalendarKind::Iso;
  if (!IsUndefined(*calendar_like)) {
    // 12. If calendar is not a String, throw a TypeError exception.
    if (!IsString(*calendar_like)) {
      THROW_NEW_ERROR(isolate, NEW_TEMPORAL_INVALID_ARG_TYPE_ERROR());
    }
    // 13. Set calendar to ?CanonicalizeCalendar(calendar).
    MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate, calendar,
        temporal::CanonicalizeCalendar(isolate, Cast<String>(calendar_like)),
        kNullMaybeHandle);
  }
  // 14. If IsValidISODate(isoYear, isoMonth, isoDay) is false, throw a
  // RangeError exception.
  if (!temporal::IsValidIsoDate(y, m, d)) {
    THROW_NEW_ERROR(isolate, NEW_TEMPORAL_INVALID_ARG_RANGE_ERROR());
  }
  // 16. If IsValidTime(hour, minute, second, millisecond, microsecond,
  // nanosecond) is false, throw a RangeError exception.
  if (!temporal::IsValidTime(hour, minute, second, millisecond, microsecond,
                             nanosecond)) {
    THROW_NEW_ERROR(isolate, NEW_TEMPORAL_INVALID_ARG_RANGE_ERROR());
  }
  // Rest of the steps handled in Rust.
  // These static_casts are fine to perform since IsValid* will have constrained
  // these values to range already.
  // https://github.com/boa-dev/temporal/issues/334 for moving this logic into
  // the Rust code.
  auto rust_object = temporal_rs::PlainDateTime::try_new(
      static_cast<int32_t>(y), static_cast<uint8_t>(m), static_cast<uint8_t>(d),
      static_cast<uint8_t>(hour), static_cast<uint8_t>(minute),
      static_cast<uint8_t>(second), static_cast<uint16_t>(millisecond),
      static_cast<uint16_t>(microsecond), static_cast<uint16_t>(nanosecond),
      calendar);
  return ConstructRustWrappingType<JSTemporalPlainDateTime>(
      isolate, target, new_target, std::move(rust_object));
}
References v8::internal::temporal::CanonicalizeCalendar(), v8::internal::Isolate::factory(), v8::internal::temporal::IsValidIsoDate(), v8::internal::temporal::IsValidTime(), v8::internal::kNullMaybeHandle, MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::microsecond, NEW_TEMPORAL_INVALID_ARG_RANGE_ERROR, NEW_TEMPORAL_INVALID_ARG_TYPE_ERROR, v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), THROW_NEW_ERROR, v8::internal::temporal::ToIntegerWithTruncation(), and v8::internal::y.
Referenced by v8::internal::TEMPORAL_GET_RUST().
Equals()
MaybeDirectHandle< Oddball > v8::internal::JSTemporalPlainDateTime::Equals (Isolate * isolate, DirectHandle< JSTemporalPlainDateTime > plain_date, DirectHandle< Object > other) [static]
Definition at line 2088 of file js-temporal-objects.cc.
                                    {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
From()
MaybeDirectHandle< JSTemporalPlainDateTime > v8::internal::JSTemporalPlainDateTime::From (Isolate * isolate, DirectHandle< Object > item, DirectHandle< Object > options) [static]
Definition at line 2074 of file js-temporal-objects.cc.
                                      {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
GetISOFields()
static V8_WARN_UNUSED_RESULT MaybeDirectHandle<JSReceiver> v8::internal::JSTemporalPlainDateTime::GetISOFields (Isolate * isolate, DirectHandle< JSTemporalPlainDateTime > date_time) [static]
Now()
MaybeDirectHandle< JSTemporalPlainDateTime > v8::internal::JSTemporalPlainDateTime::Now (Isolate * isolate, DirectHandle< Object > calendar_like, DirectHandle< Object > temporal_time_zone_like) [static]
Definition at line 2215 of file js-temporal-objects.cc.
                                                  {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
NowISO()
MaybeDirectHandle< JSTemporalPlainDateTime > v8::internal::JSTemporalPlainDateTime::NowISO (Isolate * isolate, DirectHandle< Object > temporal_time_zone_like) [static]
Definition at line 2222 of file js-temporal-objects.cc.
                                                                    {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
Round()
MaybeDirectHandle< JSTemporalPlainDateTime > v8::internal::JSTemporalPlainDateTime::Round (Isolate * isolate, DirectHandle< JSTemporalPlainDateTime > date_time, DirectHandle< Object > round_to) [static]
Definition at line 2229 of file js-temporal-objects.cc.
                                       {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
Since()
MaybeDirectHandle< JSTemporalDuration > v8::internal::JSTemporalPlainDateTime::Since (Isolate * isolate, DirectHandle< JSTemporalPlainDateTime > date_time, DirectHandle< Object > other, DirectHandle< Object > options) [static]
Definition at line 2259 of file js-temporal-objects.cc.
                                                              {
  TEMPORAL_ENTER_FUNC();
  UNIMPLEMENTED();
}
References TEMPORAL_ENTER_FUNC, and v8::internal::UNIMPLEMENTED().
Subtract()
MaybeDirectHandle< JSTemporalPlainDateTime > v8::internal::JSTemporalPlainDateTime::Subtract (Isolate * isolate, DirectHandle< JSTemporalPlainDateTime > date_time, DirectHandle< Object > temporal_duration_like, DirectHandle< Object > options) [static]
Definition at line 2244 of file js-temporal-objects.cc.
                                                                               {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
ToJSON()
MaybeDirectHandle< String > v8::internal::JSTemporalPlainDateTime::ToJSON (Isolate * isolate, DirectHandle< JSTemporalPlainDateTime > date_time) [static]
Definition at line 2143 of file js-temporal-objects.cc.
                                                                       {
  return temporal::ISODateTimeToString(isolate, date_time,
                                       std::move(temporal::kToStringAuto),
                                       temporal_rs::DisplayCalendar::Auto);
}
References v8::internal::date_time, v8::internal::temporal::ISODateTimeToString(), and v8::internal::temporal::kToStringAuto.
ToLocaleString()
MaybeDirectHandle< String > v8::internal::JSTemporalPlainDateTime::ToLocaleString (Isolate * isolate, DirectHandle< JSTemporalPlainDateTime > date_time, DirectHandle< Object > locales, DirectHandle< Object > options) [static]
Definition at line 2151 of file js-temporal-objects.cc.
                                                                {
  return temporal::ISODateTimeToString(isolate, date_time,
                                       std::move(temporal::kToStringAuto),
                                       temporal_rs::DisplayCalendar::Auto);
}
References v8::internal::date_time, v8::internal::temporal::ISODateTimeToString(), and v8::internal::temporal::kToStringAuto.
ToPlainDate()
MaybeDirectHandle< JSTemporalPlainDate > v8::internal::JSTemporalPlainDateTime::ToPlainDate (Isolate * isolate, DirectHandle< JSTemporalPlainDateTime > date_time) [static]
Definition at line 2267 of file js-temporal-objects.cc.
                                                                       {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
ToPlainMonthDay()
MaybeDirectHandle< JSTemporalPlainMonthDay > v8::internal::JSTemporalPlainDateTime::ToPlainMonthDay (Isolate * isolate, DirectHandle< JSTemporalPlainDateTime > date_time) [static]
Definition at line 2119 of file js-temporal-objects.cc.
                                                                       {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
ToPlainTime()
MaybeDirectHandle< JSTemporalPlainTime > v8::internal::JSTemporalPlainDateTime::ToPlainTime (Isolate * isolate, DirectHandle< JSTemporalPlainDateTime > date_time) [static]
Definition at line 2273 of file js-temporal-objects.cc.
                                                                       {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
ToPlainYearMonth()
MaybeDirectHandle< JSTemporalPlainYearMonth > v8::internal::JSTemporalPlainDateTime::ToPlainYearMonth (Isolate * isolate, DirectHandle< JSTemporalPlainDateTime > date_time) [static]
Definition at line 2112 of file js-temporal-objects.cc.
                                                                       {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
ToString()
MaybeDirectHandle< String > v8::internal::JSTemporalPlainDateTime::ToString (Isolate * isolate, DirectHandle< JSTemporalPlainDateTime > date_time, DirectHandle< Object > options) [static]
Definition at line 2160 of file js-temporal-objects.cc.
                                      {
  const char method_name[] = "Temporal.DateTime.prototype.toString";
  // 3. Let resolvedOptions be ?GetOptionsObject(options).
  DirectHandle<JSReceiver> options;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, options, GetOptionsObject(isolate, options_obj, method_name));
  // 5. Let showCalendar be ?GetTemporalShowCalendarNameOption(resolvedOptions).
  temporal_rs::DisplayCalendar show_calendar;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, show_calendar,
      temporal::GetTemporalShowCalendarNameOption(isolate, options,
                                                  method_name),
      DirectHandle<String>());
  // 5. Let digits be ?GetTemporalFractionalSecondDigitsOption(resolvedOptions).
  temporal_rs::Precision digits;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, digits,
      temporal::GetTemporalFractionalSecondDigitsOption(isolate, options,
                                                        method_name),
      DirectHandle<String>());
  // 6. Let roundingMode be ? GetRoundingModeOption(resolvedOptions, trunc).
  RoundingMode rounding_mode;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, rounding_mode,
      temporal::GetRoundingModeOption(isolate, options, RoundingMode::Trunc,
                                      method_name),
      DirectHandle<String>());
  // 7. Let smallestUnit be ? GetTemporalUnitValuedOption(resolvedOptions,
  // "smallestUnit", time, unset).
  std::optional<Unit> smallest_unit;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, smallest_unit,
      temporal::GetTemporalUnit(isolate, options, "smallestUnit",
                                UnitGroup::kTime, std::nullopt, false,
                                method_name),
      DirectHandle<String>());
  // Rest of the steps handled in Rust
  auto rust_options = temporal_rs::ToStringRoundingOptions{
      .precision = digits,
      .smallest_unit = smallest_unit,
      .rounding_mode = rounding_mode,
  };
  return temporal::ISODateTimeToString(isolate, date_time,
                                       std::move(rust_options), show_calendar);
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::date_time, v8::internal::GetOptionsObject(), v8::internal::temporal::GetRoundingModeOption(), v8::internal::temporal::GetTemporalFractionalSecondDigitsOption(), v8::internal::temporal::GetTemporalShowCalendarNameOption(), v8::internal::temporal::GetTemporalUnit(), v8::internal::temporal::ISODateTimeToString(), and MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE.
ToZonedDateTime()
MaybeDirectHandle< JSTemporalZonedDateTime > v8::internal::JSTemporalPlainDateTime::ToZonedDateTime (Isolate * isolate, DirectHandle< JSTemporalPlainDateTime > date_time, DirectHandle< Object > temporal_time_zone_like, DirectHandle< Object > options_obj) [static]
Definition at line 2126 of file js-temporal-objects.cc.
                                      {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
Until()
MaybeDirectHandle< JSTemporalDuration > v8::internal::JSTemporalPlainDateTime::Until (Isolate * isolate, DirectHandle< JSTemporalPlainDateTime > date_time, DirectHandle< Object > other, DirectHandle< Object > options) [static]
Definition at line 2251 of file js-temporal-objects.cc.
                                                              {
  TEMPORAL_ENTER_FUNC();
  UNIMPLEMENTED();
}
References TEMPORAL_ENTER_FUNC, and v8::internal::UNIMPLEMENTED().
With()
MaybeDirectHandle< JSTemporalPlainDateTime > v8::internal::JSTemporalPlainDateTime::With (Isolate * isolate, DirectHandle< JSTemporalPlainDateTime > date_time, DirectHandle< Object > temporal_date_time_like, DirectHandle< Object > options) [static]
Definition at line 2095 of file js-temporal-objects.cc.
                                      {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
WithPlainDate()
MaybeDirectHandle< JSTemporalPlainDateTime > v8::internal::JSTemporalPlainDateTime::WithPlainDate (Isolate * isolate, DirectHandle< JSTemporalPlainDateTime > date_time, DirectHandle< Object > temporal_date_date_like) [static]
Definition at line 2136 of file js-temporal-objects.cc.
                                             {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
WithPlainTime()
MaybeDirectHandle< JSTemporalPlainDateTime > v8::internal::JSTemporalPlainDateTime::WithPlainTime (Isolate * isolate, DirectHandle< JSTemporalPlainDateTime > date_time, DirectHandle< Object > temporal_time_like) [static]
Definition at line 2104 of file js-temporal-objects.cc.
                                          {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-temporal-objects.h
/mnt/V8SourceCode/src/objects/js-temporal-objects.cc