v8::internal::maglev::StoreDoubleField Class Reference
#include <maglev-ir.h>
Public Member Functions
StoreDoubleField (uint64_t bitfield, int offset)
int offset () const
Input & object_input ()
Input & value_input ()
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties = OpProperties::CanWrite()
static constexpr Base::InputTypes kInputTypes
static constexpr int kObjectIndex = 0
static constexpr int kValueIndex = 1
Private Types
using Base = FixedInputNodeT< 2, StoreDoubleField >
Private Attributes
const int offset_
Additional Inherited Members
Detailed Description
Definition at line 8923 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::StoreDoubleField::Base = FixedInputNodeT<2, StoreDoubleField> [private]
Definition at line 8924 of file maglev-ir.h.
Constructor & Destructor Documentation
StoreDoubleField()
v8::internal::maglev::StoreDoubleField::StoreDoubleField (uint64_t bitfield, int offset) [inline], [explicit]
Definition at line 8927 of file maglev-ir.h.
      : Base(bitfield), offset_(offset) {}
Member Function Documentation
GenerateCode()
void v8::internal::maglev::StoreDoubleField::GenerateCode (MaglevAssembler * , const ProcessingState &)
object_input()
Input& v8::internal::maglev::StoreDoubleField::object_input () [inline]
Definition at line 8938 of file maglev-ir.h.
{ return input(kObjectIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
offset()
int v8::internal::maglev::StoreDoubleField::offset () const [inline]
Definition at line 8934 of file maglev-ir.h.
{ return offset_; }
Referenced by PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::StoreDoubleField::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8219 of file maglev-ir.cc.
                                                                              {
  os << "(0x" << std::hex << offset() << std::dec << ")";
}
References offset().
SetValueLocationConstraints()
void v8::internal::maglev::StoreDoubleField::SetValueLocationConstraints ()
value_input()
Input& v8::internal::maglev::StoreDoubleField::value_input () [inline]
Definition at line 8939 of file maglev-ir.h.
{ return input(kValueIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::StoreDoubleField::kInputTypes [static], [constexpr]
Initial value:
{
      ValueRepresentation::kTagged, ValueRepresentation::kFloat64}
Definition at line 8931 of file maglev-ir.h.
kObjectIndex
constexpr int v8::internal::maglev::StoreDoubleField::kObjectIndex = 0 [static], [constexpr]
Definition at line 8936 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::StoreDoubleField::kProperties = OpProperties::CanWrite() [static], [constexpr]
Definition at line 8930 of file maglev-ir.h.
kValueIndex
constexpr int v8::internal::maglev::StoreDoubleField::kValueIndex = 1 [static], [constexpr]
Definition at line 8937 of file maglev-ir.h.
offset_
const int v8::internal::maglev::StoreDoubleField::offset_ [private]
Definition at line 8946 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc