v8::RegExp Class Reference
An instance of the built-in RegExp constructor (ECMA-262, 15.10).
#include <v8-regexp.h>
Public Types
enum Flags {
kNone = 0
, kGlobal = 1 << 0
, kIgnoreCase = 1 << 1
, kMultiline = 1 << 2
,
kSticky = 1 << 3
, kUnicode = 1 << 4
, kDotAll = 1 << 5
, kLinear = 1 << 6
,
kHasIndices = 1 << 7
, kUnicodeSets = 1 << 8
 }
Regular expression flag bits.
Public Member Functions
V8_WARN_UNUSED_RESULT MaybeLocal< Object > Exec (Local< Context > context, Local< String > subject)
Executes the current RegExp instance on the given subject string.
Local< String > GetSource () const
Returns the value of the source property: a string representing the regular expression.
Flags GetFlags () const
Returns the flags bit field.
Static Public Member Functions
static V8_WARN_UNUSED_RESULT MaybeLocal< RegExp > New (Local< Context > context, Local< String > pattern, Flags flags)
Creates a regular expression from the given pattern string and the flags bit field.
static V8_WARN_UNUSED_RESULT MaybeLocal< RegExp > NewWithBacktrackLimit (Local< Context > context, Local< String > pattern, Flags flags, uint32_t backtrack_limit)
Like New, but additionally specifies a backtrack limit.
static RegExp * Cast (Value *value)
Static Public Attributes
static constexpr int kFlagCount = 9
Static Private Member Functions
static void CheckCast (Value *obj)
Additional Inherited Members
Detailed Description
An instance of the built-in RegExp constructor (ECMA-262, 15.10).
Definition at line 19 of file v8-regexp.h.
Member Enumeration Documentation
Flags
enum v8::RegExp::Flags
Regular expression flag bits.
They can be or'ed to enable a set of flags. The kLinear value ('l') is experimental and can only be used with --enable-experimental-regexp-engine. RegExps with kLinear flag are guaranteed to be executed in asymptotic linear time wrt. the length of the subject string.
Enumerator
kNone
kGlobal
kIgnoreCase
kMultiline
kSticky
kUnicode
kDotAll
kLinear
kHasIndices
kUnicodeSets
Definition at line 29 of file v8-regexp.h.
             {
    kNone = 0,
    kGlobal = 1 << 0,
    kIgnoreCase = 1 << 1,
    kMultiline = 1 << 2,
    kSticky = 1 << 3,
    kUnicode = 1 << 4,
    kDotAll = 1 << 5,
    kLinear = 1 << 6,
    kHasIndices = 1 << 7,
    kUnicodeSets = 1 << 8,
  };
Member Function Documentation
Cast()
static RegExp* v8::RegExp::Cast (Value * value) [inline], [static]
Definition at line 92 of file v8-regexp.h.
                                              {
#ifdef V8_ENABLE_CHECKS
    CheckCast(value);
#endif
    return static_cast<RegExp*>(value);
  }
References v8::internal::value.
CheckCast()
void v8::RegExp::CheckCast (v8::Value * that) [static], [private]
Definition at line 4165 of file api.cc.
                                      {
  auto obj = *Utils::OpenDirectHandle(that);
  Utils::ApiCheck(i::IsJSRegExp(obj), "v8::RegExp::Cast()",
                  "Value is not a RegExp");
}
References v8::Utils::ApiCheck(), and v8::Utils::OpenDirectHandle().
Exec()
MaybeLocal< v8::Object > v8::RegExp::Exec (Local< Context > context, Local< String > subject)
Executes the current RegExp instance on the given subject string.
Equivalent to RegExp.prototype.exec as described in
 https://tc39.es/ecma262/#sec-regexp.prototype.exec
On success, an Array containing the matched strings is returned. On failure, returns Null.
Note: modifies global context state, accessible e.g. through RegExp.input.
Definition at line 8066 of file api.cc.
                                                                 {
  PrepareForExecutionScope api_scope{context, RCCId::kAPI_RegExp_Exec};
  i::Isolate* i_isolate = api_scope.i_isolate();
  auto regexp = Utils::OpenHandle(this);
  auto subject_string = Utils::OpenDirectHandle(*subject);
  // TODO(jgruber): RegExpUtils::RegExpExec was not written with efficiency in
  // mind. It fetches the 'exec' property and then calls it through JSEntry.
  // Unfortunately, this is currently the only full implementation of
  // RegExp.prototype.exec available in C++.
  i::DirectHandle<i::JSAny> result;
  if (!i::RegExpUtils::RegExpExec(i_isolate, regexp, subject_string,
                                  i_isolate->factory()->undefined_value())
           .ToHandle(&result)) {
    return {};
  }
  // RegExp::Exec is documented to return Null on failure, but the return type
  // is `MaybeLocal<Object>` which cannot legally hold `Null`, thus the unsafe
  // `Utils::Convert<Object>`.
  // TODO(jgruber): Fix this.
  return api_scope.Escape(Utils::Convert<i::JSAny, Object>(result));
}
References v8::internal::Isolate::factory(), v8::Utils::OpenDirectHandle(), v8::Utils::OpenHandle(), v8::internal::RegExpUtils::RegExpExec(), and v8::base::internal::result.
GetFlags()
v8::RegExp::Flags v8::RegExp::GetFlags () const
Returns the flags bit field.
Definition at line 8061 of file api.cc.
                                       {
  auto obj = Utils::OpenDirectHandle(this);
  return RegExp::Flags(static_cast<int>(obj->flags()));
}
References v8::Utils::OpenDirectHandle().
GetSource()
Local< v8::String > v8::RegExp::GetSource () const
Returns the value of the source property: a string representing the regular expression.
Definition at line 8040 of file api.cc.
                                          {
  auto obj = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  return Utils::ToLocal(i::direct_handle(obj->EscapedPattern(), i_isolate));
}
References v8::internal::Isolate::Current(), v8::internal::direct_handle(), and v8::Utils::OpenDirectHandle().
New()
MaybeLocal< v8::RegExp > v8::RegExp::New (Local< Context > context, Local< String > pattern, Flags flags) [static]
Creates a regular expression from the given pattern string and the flags bit field.
May throw a JavaScript exception as described in ECMA-262, 15.10.4.1.
For example, RegExp::New(v8::String::New(`foo`), static_cast<RegExp::Flags>(kGlobal | kMultiline)) is equivalent to evaluating `/foo/gm`.
Definition at line 8015 of file api.cc.
                                                                           {
  PrepareForExecutionScope api_scope{context, RCCId::kAPI_RegExp_New};
  i::Isolate* i_isolate = api_scope.i_isolate();
  return api_scope.EscapeMaybe(
      i::JSRegExp::New(i_isolate, Utils::OpenDirectHandle(*pattern),
                       static_cast<i::JSRegExp::Flags>(flags)));
}
References v8::internal::Flags(), flags(), v8::internal::JSRegExp::New(), and v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::V8Regex::V8Regex().
NewWithBacktrackLimit()
MaybeLocal< v8::RegExp > v8::RegExp::NewWithBacktrackLimit (Local< Context > context, Local< String > pattern, Flags flags, uint32_t backtrack_limit) [static]
Like New, but additionally specifies a backtrack limit.
If the number of backtracks done in one Exec call hits the limit, a match failure is immediately returned.
Definition at line 8024 of file api.cc.
                              {
  Utils::ApiCheck(i::Smi::IsValid(backtrack_limit),
                  "v8::RegExp::NewWithBacktrackLimit",
                  "backtrack_limit is too large or too small");
  Utils::ApiCheck(backtrack_limit != i::JSRegExp::kNoBacktrackLimit,
                  "v8::RegExp::NewWithBacktrackLimit",
                  "Must set backtrack_limit");
  PrepareForExecutionScope api_scope{context, RCCId::kAPI_RegExp_New};
  i::Isolate* i_isolate = api_scope.i_isolate();
  return api_scope.EscapeMaybe(i::JSRegExp::New(
      i_isolate, Utils::OpenDirectHandle(*pattern),
      static_cast<i::JSRegExp::Flags>(flags), backtrack_limit));
}
References v8::Utils::ApiCheck(), v8::internal::Flags(), flags(), v8::internal::Smi::IsValid(), v8::internal::JSRegExp::kNoBacktrackLimit, v8::internal::JSRegExp::New(), and v8::Utils::OpenDirectHandle().
Member Data Documentation
kFlagCount
constexpr int v8::RegExp::kFlagCount = 9 [static], [constexpr]
Definition at line 42 of file v8-regexp.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-regexp.h
/mnt/V8SourceCode/src/api/api.cc