v8::internal::ProfilerCodeObserver Class Reference
#include <cpu-profiler.h>
Public Member Functions
ProfilerCodeObserver (Isolate *, CodeEntryStorage &)
void CodeEventHandler (const CodeEventsContainer &evt_rec) override
CodeEntryStorage * code_entries ()
InstructionStreamMap * instruction_stream_map ()
WeakCodeRegistry * weak_code_registry ()
size_t GetEstimatedMemoryUsage () const
void ClearCodeMap ()
Private Member Functions
void CodeEventHandlerInternal (const CodeEventsContainer &evt_rec)
void CreateEntriesForRuntimeCallStats ()
void LogBuiltins ()
ProfilerEventsProcessor * processor ()
void set_processor (ProfilerEventsProcessor *processor)
void clear_processor ()
Private Attributes
Isolate *const isolate_
CodeEntryStorage & code_entries_
InstructionStreamMap code_map_
WeakCodeRegistry weak_code_registry_
ProfilerEventsProcessor * processor_
Friends
class ProfilerEventsProcessor
Detailed Description
Definition at line 271 of file cpu-profiler.h.
Constructor & Destructor Documentation
ProfilerCodeObserver()
v8::internal::ProfilerCodeObserver::ProfilerCodeObserver (Isolate * isolate, CodeEntryStorage & storage) [explicit]
Definition at line 356 of file cpu-profiler.cc.
    : isolate_(isolate),
      code_entries_(storage),
      code_map_(storage),
      weak_code_registry_(isolate),
      processor_(nullptr) {
  CreateEntriesForRuntimeCallStats();
  LogBuiltins();
}
References CreateEntriesForRuntimeCallStats(), and LogBuiltins().
Member Function Documentation
clear_processor()
void v8::internal::ProfilerCodeObserver::clear_processor () [inline], [private]
Definition at line 299 of file cpu-profiler.h.
{ processor_ = nullptr; }
Referenced by v8::internal::ProfilerEventsProcessor::~ProfilerEventsProcessor().
ClearCodeMap()
void v8::internal::ProfilerCodeObserver::ClearCodeMap ()
Definition at line 367 of file cpu-profiler.cc.
                                        {
  weak_code_registry_.Clear();
  code_map_.Clear();
}
References v8::internal::InstructionStreamMap::Clear(), v8::internal::WeakCodeRegistry::Clear(), code_map_, and weak_code_registry_.
code_entries()
CodeEntryStorage* v8::internal::ProfilerCodeObserver::code_entries () [inline]
Definition at line 276 of file cpu-profiler.h.
{ return &code_entries_; }
CodeEventHandler()
void v8::internal::ProfilerCodeObserver::CodeEventHandler (const CodeEventsContainer & evt_rec) [override], [virtual]
Implements v8::internal::CodeEventObserver.
Definition at line 372 of file cpu-profiler.cc.
                                        {
  if (processor_) {
    processor_->CodeEventHandler(evt_rec);
    return;
  }
  CodeEventHandlerInternal(evt_rec);
}
References v8::internal::ProfilerEventsProcessor::CodeEventHandler(), CodeEventHandlerInternal(), and processor_.
CodeEventHandlerInternal()
void v8::internal::ProfilerCodeObserver::CodeEventHandlerInternal (const CodeEventsContainer & evt_rec) [private]
Definition at line 391 of file cpu-profiler.cc.
                                        {
  CodeEventsContainer record = evt_rec;
  switch (evt_rec.generic.type) {
#define PROFILER_TYPE_CASE(type, clss) \
  case CodeEventRecord::Type::type: \
    record.clss##_.UpdateCodeMap(&code_map_); \
    break;
    CODE_EVENTS_TYPE_LIST(PROFILER_TYPE_CASE)
#undef PROFILER_TYPE_CASE
    default:
      break;
  }
}
References CODE_EVENTS_TYPE_LIST, v8::internal::CodeEventsContainer::generic, PROFILER_TYPE_CASE, and v8::internal::CodeEventRecord::type.
Referenced by CodeEventHandler(), LogBuiltins(), and v8::internal::ProfilerEventsProcessor::ProcessCodeEvent().
CreateEntriesForRuntimeCallStats()
void v8::internal::ProfilerCodeObserver::CreateEntriesForRuntimeCallStats () [private]
Definition at line 408 of file cpu-profiler.cc.
                                                            {
#ifdef V8_RUNTIME_CALL_STATS
  RuntimeCallStats* rcs = isolate_->counters()->runtime_call_stats();
  for (int i = 0; i < RuntimeCallStats::kNumberOfCounters; ++i) {
    RuntimeCallCounter* counter = rcs->GetCounter(i);
    DCHECK(counter->name());
    auto entry = code_entries_.Create(LogEventListener::CodeTag::kFunction,
                                      counter->name(), "native V8Runtime");
    code_map_.AddCode(reinterpret_cast<Address>(counter), entry, 1);
  }
#endif // V8_RUNTIME_CALL_STATS
}
References v8::internal::InstructionStreamMap::AddCode(), code_entries_, code_map_, v8::internal::Isolate::counters(), v8::internal::CodeEntryStorage::Create(), v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, isolate_, v8::internal::torque::ls::kFunction, and v8::internal::Counters::runtime_call_stats().
Referenced by ProfilerCodeObserver().
GetEstimatedMemoryUsage()
size_t v8::internal::ProfilerCodeObserver::GetEstimatedMemoryUsage () const
Definition at line 381 of file cpu-profiler.cc.
                                                           {
  // To avoid race condition in codemap,
  // for now limit computation in kEagerLogging mode
  if (!processor_) {
    return sizeof(*this) + code_map_.GetEstimatedMemoryUsage() +
           code_entries_.strings().GetStringSize();
  }
  return 0;
}
References code_entries_, code_map_, v8::internal::InstructionStreamMap::GetEstimatedMemoryUsage(), v8::internal::StringsStorage::GetStringSize(), processor_, and v8::internal::CodeEntryStorage::strings().
instruction_stream_map()
InstructionStreamMap* v8::internal::ProfilerCodeObserver::instruction_stream_map () [inline]
Definition at line 277 of file cpu-profiler.h.
{ return &code_map_; }
LogBuiltins()
void v8::internal::ProfilerCodeObserver::LogBuiltins () [private]
Definition at line 421 of file cpu-profiler.cc.
                                       {
  Builtins* builtins = isolate_->builtins();
  DCHECK(builtins->is_initialized());
  for (Builtin builtin = Builtins::kFirst; builtin <= Builtins::kLast;
       ++builtin) {
#if V8_ENABLE_WEBASSEMBLY
    // We add the embedded data entry below.
    if (builtin == Builtin::kWasmToJsWrapperCSA) continue;
#endif
    CodeEventsContainer evt_rec(CodeEventRecord::Type::kReportBuiltin);
    ReportBuiltinEventRecord* rec = &evt_rec.ReportBuiltinEventRecord_;
    Tagged<Code> code = builtins->code(builtin);
    rec->instruction_start = code->instruction_start();
    rec->instruction_size = code->instruction_size();
    rec->builtin = builtin;
    CodeEventHandlerInternal(evt_rec);
  }
#if V8_ENABLE_WEBASSEMBLY
  // We can call the WasmToJS wrapper from the embedded blob
  CodeEventsContainer evt_rec(CodeEventRecord::Type::kReportBuiltin);
  ReportBuiltinEventRecord* rec = &evt_rec.ReportBuiltinEventRecord_;
  rec->instruction_start =
      Builtins::EmbeddedEntryOf(Builtin::kWasmToJsWrapperCSA);
  rec->instruction_size =
      EmbeddedData::FromBlob().InstructionSizeOf(Builtin::kWasmToJsWrapperCSA);
  rec->builtin = Builtin::kWasmToJsWrapperCSA;
  CodeEventHandlerInternal(evt_rec);
#endif
}
References v8::internal::ReportBuiltinEventRecord::builtin, v8::internal::Isolate::builtins(), v8::internal::Builtins::code(), code, CodeEventHandlerInternal(), v8::internal::DCHECK(), v8::internal::Builtins::EmbeddedEntryOf(), v8::internal::EmbeddedData::FromBlob(), v8::internal::ReportBuiltinEventRecord::instruction_size, v8::internal::ReportBuiltinEventRecord::instruction_start, v8::internal::EmbeddedData::InstructionSizeOf(), v8::internal::Builtins::is_initialized(), isolate_, v8::internal::Builtins::kFirst, and v8::internal::Builtins::kLast.
Referenced by ProfilerCodeObserver().
processor()
ProfilerEventsProcessor* v8::internal::ProfilerCodeObserver::processor () [inline], [private]
Definition at line 291 of file cpu-profiler.h.
{ return processor_; }
Referenced by v8::internal::ProfilerEventsProcessor::ProfilerEventsProcessor(), and v8::internal::ProfilerEventsProcessor::~ProfilerEventsProcessor().
set_processor()
void v8::internal::ProfilerCodeObserver::set_processor (ProfilerEventsProcessor * processor) [inline], [private]
Definition at line 294 of file cpu-profiler.h.
                                                         {
    processor_ = processor;
  }
Referenced by v8::internal::ProfilerEventsProcessor::ProfilerEventsProcessor().
weak_code_registry()
WeakCodeRegistry* v8::internal::ProfilerCodeObserver::weak_code_registry () [inline]
Definition at line 278 of file cpu-profiler.h.
{ return &weak_code_registry_; }
Friends And Related Function Documentation
ProfilerEventsProcessor
friend class ProfilerEventsProcessor [friend]
Definition at line 284 of file cpu-profiler.h.
Member Data Documentation
code_entries_
CodeEntryStorage& v8::internal::ProfilerCodeObserver::code_entries_ [private]
Definition at line 302 of file cpu-profiler.h.
Referenced by CreateEntriesForRuntimeCallStats(), and GetEstimatedMemoryUsage().
code_map_
InstructionStreamMap v8::internal::ProfilerCodeObserver::code_map_ [private]
Definition at line 303 of file cpu-profiler.h.
Referenced by ClearCodeMap(), CreateEntriesForRuntimeCallStats(), and GetEstimatedMemoryUsage().
isolate_
Isolate* const v8::internal::ProfilerCodeObserver::isolate_ [private]
Definition at line 301 of file cpu-profiler.h.
Referenced by CreateEntriesForRuntimeCallStats(), and LogBuiltins().
processor_
ProfilerEventsProcessor* v8::internal::ProfilerCodeObserver::processor_ [private]
Definition at line 305 of file cpu-profiler.h.
Referenced by CodeEventHandler(), and GetEstimatedMemoryUsage().
weak_code_registry_
WeakCodeRegistry v8::internal::ProfilerCodeObserver::weak_code_registry_ [private]
Definition at line 304 of file cpu-profiler.h.
Referenced by ClearCodeMap().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/profiler/cpu-profiler.h
/mnt/V8SourceCode/src/profiler/cpu-profiler.cc