v8::internal::ConsStringIterator Class Reference
#include <string.h>
Public Member Functions
ConsStringIterator ()=default
ConsStringIterator (Tagged< ConsString > cons_string, int offset=0)
ConsStringIterator (const ConsStringIterator &)=delete
ConsStringIterator & operator= (const ConsStringIterator &)=delete
void Reset (Tagged< ConsString > cons_string, int offset=0)
Tagged< String > Next (int *offset_out)
Private Member Functions
void PushLeft (Tagged< ConsString > string)
void PushRight (Tagged< ConsString > string)
void AdjustMaximumDepth ()
void Pop ()
bool StackBlown ()
V8_EXPORT_PRIVATE void Initialize (Tagged< ConsString > cons_string, int offset)
V8_EXPORT_PRIVATE Tagged< String > Continue (int *offset_out)
Tagged< String > NextLeaf (bool *blew_stack)
Tagged< String > Search (int *offset_out)
Static Private Member Functions
static int OffsetForDepth (int depth)
Private Attributes
Tagged< ConsString > frames_ [kStackSize]
Tagged< ConsString > root_
int depth_
int maximum_depth_
uint32_t consumed_
Static Private Attributes
static const int kStackSize = 32
static const int kDepthMask = kStackSize - 1
Detailed Description
Definition at line 1334 of file string.h.
Constructor & Destructor Documentation
ConsStringIterator() [1/3]
v8::internal::ConsStringIterator::ConsStringIterator () [inline], [default]
ConsStringIterator() [2/3]
v8::internal::ConsStringIterator::ConsStringIterator (Tagged< ConsString > cons_string, int offset = 0) [inline], [explicit]
Definition at line 1337 of file string.h.
                                                     {
    Reset(cons_string, offset);
  }
ConsStringIterator() [3/3]
v8::internal::ConsStringIterator::ConsStringIterator (const ConsStringIterator &) [delete]
Member Function Documentation
AdjustMaximumDepth()
void v8::internal::ConsStringIterator::AdjustMaximumDepth () [inline], [private]
Definition at line 1629 of file string-inl.h.
                                            {
  if (depth_ > maximum_depth_) maximum_depth_ = depth_;
}
Referenced by NextLeaf(), and Search().
Continue()
Tagged< String > v8::internal::ConsStringIterator::Continue (int * offset_out) [private]
Definition at line 2102 of file string.cc.
                                                           {
  DCHECK_NE(depth_, 0);
  DCHECK_EQ(0, *offset_out);
  bool blew_stack = StackBlown();
  Tagged<String> string;
  // Get the next leaf if there is one.
  if (!blew_stack) string = NextLeaf(&blew_stack);
  // Restart search from root.
  if (blew_stack) {
    DCHECK(string.is_null());
    string = Search(offset_out);
  }
  // Ensure future calls return null immediately.
  if (string.is_null()) Reset({});
  return string;
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, depth_, NextLeaf(), Reset(), Search(), StackBlown(), and v8::internal::string.
Initialize()
void v8::internal::ConsStringIterator::Initialize (Tagged< ConsString > cons_string, int offset) [private]
Definition at line 2091 of file string.cc.
                                                {
  DCHECK(!cons_string.is_null());
  root_ = cons_string;
  consumed_ = offset;
  // Force stack blown condition to trigger restart.
  depth_ = 1;
  maximum_depth_ = kStackSize + depth_;
  DCHECK(StackBlown());
}
References consumed_, v8::internal::DCHECK(), depth_, v8::internal::Tagged< HeapObject >::is_null(), kStackSize, maximum_depth_, root_, and StackBlown().
Next()
Tagged<String> v8::internal::ConsStringIterator::Next (int * offset_out) [inline]
Definition at line 1354 of file string.h.
                                              {
    *offset_out = 0;
    if (depth_ == 0) return Tagged<String>();
    return Continue(offset_out);
  }
Referenced by v8::internal::StringCharacterStream::HasMore(), v8::internal::StringComparator::State::Init(), v8::internal::String::IsConsStringEqualToImpl(), and v8::internal::StringCharacterStream::Reset().
NextLeaf()
Tagged< String > v8::internal::ConsStringIterator::NextLeaf (bool * blew_stack) [private]
Definition at line 2178 of file string.cc.
                                                            {
  while (true) {
    // Tree traversal complete.
    if (depth_ == 0) {
      *blew_stack = false;
      return {};
    }
    // We've lost track of higher nodes.
    if (StackBlown()) {
      *blew_stack = true;
      return {};
    }
    // Go right.
    Tagged<ConsString> cons_string = frames_[OffsetForDepth(depth_ - 1)];
    Tagged<String> string = cons_string->second();
    int32_t type = string->map()->instance_type();
    if ((type & kStringRepresentationMask) != kConsStringTag) {
      // Pop stack so next iteration is in correct place.
      Pop();
      uint32_t length = string->length();
      // Could be a flattened ConsString.
      if (length == 0) continue;
      consumed_ += length;
      return string;
    }
    cons_string = Cast<ConsString>(string);
    PushRight(cons_string);
    // Need to traverse all the way left.
    while (true) {
      // Continue left.
      string = cons_string->first();
      type = string->map()->instance_type();
      if ((type & kStringRepresentationMask) != kConsStringTag) {
        AdjustMaximumDepth();
        uint32_t length = string->length();
        if (length == 0) break; // Skip empty left-hand sides of ConsStrings.
        consumed_ += length;
        return string;
      }
      cons_string = Cast<ConsString>(string);
      PushLeft(cons_string);
    }
  }
  UNREACHABLE();
}
References AdjustMaximumDepth(), consumed_, depth_, frames_, v8::internal::kConsStringTag, v8::internal::kStringRepresentationMask, v8::internal::length, OffsetForDepth(), Pop(), PushLeft(), PushRight(), StackBlown(), v8::internal::string, v8::internal::tracing::type, and v8::internal::UNREACHABLE().
Referenced by Continue().
OffsetForDepth()
int v8::internal::ConsStringIterator::OffsetForDepth (int depth) [inline], [static], [private]
Definition at line 1618 of file string-inl.h.
{ return depth & kDepthMask; }
Referenced by NextLeaf().
operator=()
ConsStringIterator& v8::internal::ConsStringIterator::operator= (const ConsStringIterator &) [delete]
Pop()
void v8::internal::ConsStringIterator::Pop () [inline], [private]
Definition at line 1633 of file string-inl.h.
                             {
  DCHECK_GT(depth_, 0);
  DCHECK(depth_ <= maximum_depth_);
  depth_--;
}
References v8::internal::DCHECK(), and DCHECK_GT.
Referenced by NextLeaf(), and Search().
PushLeft()
void v8::internal::ConsStringIterator::PushLeft (Tagged< ConsString > string) [inline], [private]
Definition at line 1620 of file string-inl.h.
                                                           {
  frames_[depth_++ & kDepthMask] = string;
}
References v8::internal::String::string.
Referenced by NextLeaf(), and Search().
PushRight()
void v8::internal::ConsStringIterator::PushRight (Tagged< ConsString > string) [inline], [private]
Definition at line 1624 of file string-inl.h.
                                                            {
  // Inplace update.
  frames_[(depth_ - 1) & kDepthMask] = string;
}
Referenced by NextLeaf(), and Search().
Reset()
void v8::internal::ConsStringIterator::Reset (Tagged< ConsString > cons_string, int offset = 0) [inline]
Definition at line 1343 of file string.h.
                                                                    {
    depth_ = 0;
    // Next will always return nullptr.
    if (cons_string.is_null()) return;
    Initialize(cons_string, offset);
  }
References v8::internal::Tagged< HeapObject >::is_null().
Referenced by Continue(), v8::internal::StringComparator::State::Init(), v8::internal::StringCharacterStream::Reset(), and Search().
Search()
Tagged< String > v8::internal::ConsStringIterator::Search (int * offset_out) [private]
Definition at line 2119 of file string.cc.
                                                         {
  Tagged<ConsString> cons_string = root_;
  // Reset the stack, pushing the root string.
  depth_ = 1;
  maximum_depth_ = 1;
  frames_[0] = cons_string;
  const uint32_t consumed = consumed_;
  uint32_t offset = 0;
  while (true) {
    // Loop until the string is found which contains the target offset.
    Tagged<String> string = cons_string->first();
    uint32_t length = string->length();
    int32_t type;
    if (consumed < offset + length) {
      // Target offset is in the left branch.
      // Keep going if we're still in a ConString.
      type = string->map()->instance_type();
      if ((type & kStringRepresentationMask) == kConsStringTag) {
        cons_string = Cast<ConsString>(string);
        PushLeft(cons_string);
        continue;
      }
      // Tell the stack we're done descending.
      AdjustMaximumDepth();
    } else {
      // Descend right.
      // Update progress through the string.
      offset += length;
      // Keep going if we're still in a ConString.
      string = cons_string->second();
      type = string->map()->instance_type();
      if ((type & kStringRepresentationMask) == kConsStringTag) {
        cons_string = Cast<ConsString>(string);
        PushRight(cons_string);
        continue;
      }
      // Need this to be updated for the current string.
      length = string->length();
      // Account for the possibility of an empty right leaf.
      // This happens only if we have asked for an offset outside the string.
      if (length == 0) {
        // Reset so future operations will return null immediately.
        Reset({});
        return {};
      }
      // Tell the stack we're done descending.
      AdjustMaximumDepth();
      // Pop stack so next iteration is in correct place.
      Pop();
    }
    DCHECK_NE(length, 0);
    // Adjust return values and exit.
    consumed_ = offset + length;
    *offset_out = consumed - offset;
    return string;
  }
  UNREACHABLE();
}
References AdjustMaximumDepth(), consumed_, DCHECK_NE, depth_, frames_, v8::internal::kConsStringTag, v8::internal::kStringRepresentationMask, v8::internal::length, maximum_depth_, Pop(), PushLeft(), PushRight(), Reset(), root_, v8::internal::string, v8::internal::tracing::type, and v8::internal::UNREACHABLE().
Referenced by Continue().
StackBlown()
bool v8::internal::ConsStringIterator::StackBlown () [inline], [private]
Definition at line 1372 of file string.h.
{ return maximum_depth_ - depth_ == kStackSize; }
References v8::base::anonymous_namespace{platform-starboard.cc}::kStackSize.
Referenced by Continue(), Initialize(), and NextLeaf().
Member Data Documentation
consumed_
uint32_t v8::internal::ConsStringIterator::consumed_ [private]
Definition at line 1384 of file string.h.
Referenced by Initialize(), NextLeaf(), and Search().
depth_
int v8::internal::ConsStringIterator::depth_ [private]
Definition at line 1382 of file string.h.
Referenced by Continue(), Initialize(), NextLeaf(), and Search().
frames_
Tagged<ConsString> v8::internal::ConsStringIterator::frames_[kStackSize] [private]
Definition at line 1380 of file string.h.
Referenced by NextLeaf(), and Search().
kDepthMask
const int v8::internal::ConsStringIterator::kDepthMask = kStackSize - 1 [static], [private]
Definition at line 1363 of file string.h.
kStackSize
const int v8::internal::ConsStringIterator::kStackSize = 32 [static], [private]
Definition at line 1361 of file string.h.
Referenced by Initialize().
maximum_depth_
int v8::internal::ConsStringIterator::maximum_depth_ [private]
Definition at line 1383 of file string.h.
Referenced by Initialize(), and Search().
root_
Tagged<ConsString> v8::internal::ConsStringIterator::root_ [private]
Definition at line 1381 of file string.h.
Referenced by Initialize(), and Search().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/string.h
/mnt/V8SourceCode/src/objects/string-inl.h
/mnt/V8SourceCode/src/objects/string.cc