v8::internal::JSProxy Class Reference
#include <js-proxy.h>
Public Types
enum AccessKind { kGet
, kSet
 }
using IsRevocableBit = base::BitField< bool, 0, 1 >
Public Member Functions
bool is_revocable () const
bool IsRevoked () const
Static Public Member Functions
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSProxy > New (Isolate *isolate, DirectHandle< Object >, DirectHandle< Object >, bool revocable)
static void Revoke (DirectHandle< JSProxy > proxy)
static MaybeDirectHandle< JSPrototype > GetPrototype (DirectHandle< JSProxy > receiver)
static V8_WARN_UNUSED_RESULT Maybe< bool > SetPrototype (Isolate *isolate, DirectHandle< JSProxy > proxy, DirectHandle< Object > value, bool from_javascript, ShouldThrow should_throw)
static V8_WARN_UNUSED_RESULT Maybe< bool > IsExtensible (DirectHandle< JSProxy > proxy)
static V8_WARN_UNUSED_RESULT Maybe< bool > IsArray (DirectHandle< JSProxy > proxy)
static V8_WARN_UNUSED_RESULT Maybe< bool > PreventExtensions (DirectHandle< JSProxy > proxy, ShouldThrow should_throw)
static V8_WARN_UNUSED_RESULT Maybe< bool > GetOwnPropertyDescriptor (Isolate *isolate, DirectHandle< JSProxy > proxy, DirectHandle< Name > name, PropertyDescriptor *desc)
static V8_WARN_UNUSED_RESULT Maybe< bool > DefineOwnProperty (Isolate *isolate, DirectHandle< JSProxy > object, DirectHandle< Object > key, PropertyDescriptor *desc, Maybe< ShouldThrow > should_throw)
static V8_WARN_UNUSED_RESULT Maybe< bool > HasProperty (Isolate *isolate, DirectHandle< JSProxy > proxy, DirectHandle< Name > name)
static V8_WARN_UNUSED_RESULT Maybe< bool > CheckHasTrap (Isolate *isolate, DirectHandle< Name > name, DirectHandle< JSReceiver > target)
static V8_WARN_UNUSED_RESULT Maybe< bool > CheckDeleteTrap (Isolate *isolate, DirectHandle< Name > name, DirectHandle< JSReceiver > target)
static V8_WARN_UNUSED_RESULT MaybeHandle< JSAny > GetProperty (Isolate *isolate, DirectHandle< JSProxy > proxy, DirectHandle< Name > name, DirectHandle< JSAny > receiver, bool *was_found)
static MaybeHandle< JSAny > CheckGetSetTrapResult (Isolate *isolate, DirectHandle< Name > name, DirectHandle< JSReceiver > target, DirectHandle< Object > trap_result, AccessKind access_kind)
static V8_WARN_UNUSED_RESULT Maybe< bool > SetProperty (DirectHandle< JSProxy > proxy, DirectHandle< Name > name, DirectHandle< Object > value, DirectHandle< JSAny > receiver, Maybe< ShouldThrow > should_throw)
static V8_WARN_UNUSED_RESULT Maybe< bool > DeletePropertyOrElement (DirectHandle< JSProxy > proxy, DirectHandle< Name > name, LanguageMode language_mode)
static V8_WARN_UNUSED_RESULT Maybe< PropertyAttributes > GetPropertyAttributes (LookupIterator *it)
static Maybe< bool > SetPrivateSymbol (Isolate *isolate, DirectHandle< JSProxy > proxy, DirectHandle< Symbol > private_name, PropertyDescriptor *desc, Maybe< ShouldThrow > should_throw)
Static Public Attributes
static const int kMaxIterationLimit = 100 * 1024
static constexpr int kIsRevocableBit = IsRevocableBit::encode(true)
Detailed Description
Definition at line 23 of file js-proxy.h.
Member Typedef Documentation
IsRevocableBit
using v8::internal::JSProxy::IsRevocableBit = base::BitField<bool, 0, 1>
Definition at line 123 of file js-proxy.h.
Member Enumeration Documentation
AccessKind
enum v8::internal::JSProxy::AccessKind
Enumerator
kGet
kSet
Definition at line 82 of file js-proxy.h.
{ kGet, kSet };
Member Function Documentation
CheckDeleteTrap()
Maybe< bool > v8::internal::JSProxy::CheckDeleteTrap (Isolate * isolate, DirectHandle< Name > name, DirectHandle< JSReceiver > target) [static]
Definition at line 3087 of file objects.cc.
                                                                      {
  // 10. Let targetDesc be ? target.[[GetOwnProperty]](P).
  PropertyDescriptor target_desc;
  Maybe<bool> target_found =
      JSReceiver::GetOwnPropertyDescriptor(isolate, target, name, &target_desc);
  MAYBE_RETURN(target_found, Nothing<bool>());
  // 11. If targetDesc is undefined, return true.
  if (target_found.FromJust()) {
    // 12. If targetDesc.[[Configurable]] is false, throw a TypeError exception.
    if (!target_desc.configurable()) {
      isolate->Throw(*isolate->factory()->NewTypeError(
          MessageTemplate::kProxyDeletePropertyNonConfigurable, name));
      return Nothing<bool>();
    }
    // 13. Let extensibleTarget be ? IsExtensible(target).
    Maybe<bool> extensible_target = JSReceiver::IsExtensible(isolate, target);
    MAYBE_RETURN(extensible_target, Nothing<bool>());
    // 14. If extensibleTarget is false, throw a TypeError exception.
    if (!extensible_target.FromJust()) {
      isolate->Throw(*isolate->factory()->NewTypeError(
          MessageTemplate::kProxyDeletePropertyNonExtensible, name));
      return Nothing<bool>();
    }
  }
  return Just(true);
}
References v8::internal::PropertyDescriptor::configurable(), v8::internal::Isolate::factory(), v8::Maybe< T >::FromJust(), v8::internal::JSReceiver::GetOwnPropertyDescriptor(), v8::internal::JSReceiver::IsExtensible(), v8::Just(), MAYBE_RETURN, v8::internal::name, and v8::internal::Isolate::Throw().
Referenced by DeletePropertyOrElement(), and v8::internal::RUNTIME_FUNCTION().
CheckGetSetTrapResult()
MaybeHandle< JSAny > v8::internal::JSProxy::CheckGetSetTrapResult (Isolate * isolate, DirectHandle< Name > name, DirectHandle< JSReceiver > target, DirectHandle< Object > trap_result, AccessKind access_kind) [static]
Definition at line 1383 of file objects.cc.
                                                              {
  // 9. Let targetDesc be ? target.[[GetOwnProperty]](P).
  PropertyDescriptor target_desc;
  Maybe<bool> target_found =
      JSReceiver::GetOwnPropertyDescriptor(isolate, target, name, &target_desc);
  MAYBE_RETURN_NULL(target_found);
  // 10. If targetDesc is not undefined, then
  if (target_found.FromJust()) {
    // 10.a. If IsDataDescriptor(targetDesc) and targetDesc.[[Configurable]] is
    // false and targetDesc.[[Writable]] is false, then
    // 10.a.i. If SameValue(trapResult, targetDesc.[[Value]]) is false,
    // throw a TypeError exception.
    bool inconsistent = PropertyDescriptor::IsDataDescriptor(&target_desc) &&
                        !target_desc.configurable() &&
                        !target_desc.writable() &&
                        !Object::SameValue(*trap_result, *target_desc.value());
    if (inconsistent) {
      if (access_kind == kGet) {
        THROW_NEW_ERROR(
            isolate, NewTypeError(MessageTemplate::kProxyGetNonConfigurableData,
                                  name, target_desc.value(), trap_result));
      } else {
        isolate->Throw(*isolate->factory()->NewTypeError(
            MessageTemplate::kProxySetFrozenData, name));
        return {};
      }
    }
    // 10.b. If IsAccessorDescriptor(targetDesc) and targetDesc.[[Configurable]]
    // is false and targetDesc.[[Get]] is undefined, then
    // 10.b.i. If trapResult is not undefined, throw a TypeError exception.
    if (access_kind == kGet) {
      inconsistent = PropertyDescriptor::IsAccessorDescriptor(&target_desc) &&
                     !target_desc.configurable() &&
                     IsUndefined(*target_desc.get(), isolate) &&
                     !IsUndefined(*trap_result, isolate);
    } else {
      inconsistent = PropertyDescriptor::IsAccessorDescriptor(&target_desc) &&
                     !target_desc.configurable() &&
                     IsUndefined(*target_desc.set(), isolate);
    }
    if (inconsistent) {
      if (access_kind == kGet) {
        THROW_NEW_ERROR(
            isolate,
            NewTypeError(MessageTemplate::kProxyGetNonConfigurableAccessor,
                         name, trap_result));
      } else {
        isolate->Throw(*isolate->factory()->NewTypeError(
            MessageTemplate::kProxySetFrozenAccessor, name));
        return {};
      }
    }
  }
  return isolate->factory()->undefined_value();
}
References v8::internal::PropertyDescriptor::configurable(), v8::internal::Isolate::factory(), v8::Maybe< T >::FromJust(), v8::internal::PropertyDescriptor::get(), v8::internal::JSReceiver::GetOwnPropertyDescriptor(), v8::internal::PropertyDescriptor::IsAccessorDescriptor(), v8::internal::PropertyDescriptor::IsDataDescriptor(), kGet, MAYBE_RETURN_NULL, v8::internal::name, v8::internal::Object::SameValue(), v8::internal::PropertyDescriptor::set(), v8::internal::Isolate::Throw(), THROW_NEW_ERROR, v8::internal::PropertyDescriptor::value(), and v8::internal::PropertyDescriptor::writable().
Referenced by GetProperty(), v8::internal::RUNTIME_FUNCTION(), and SetProperty().
CheckHasTrap()
Maybe< bool > v8::internal::JSProxy::CheckHasTrap (Isolate * isolate, DirectHandle< Name > name, DirectHandle< JSReceiver > target) [static]
Definition at line 2962 of file objects.cc.
                                                                   {
  // 9a. Let targetDesc be ? target.[[GetOwnProperty]](P).
  PropertyDescriptor target_desc;
  Maybe<bool> target_found =
      JSReceiver::GetOwnPropertyDescriptor(isolate, target, name, &target_desc);
  MAYBE_RETURN(target_found, Nothing<bool>());
  // 9b. If targetDesc is not undefined, then:
  if (target_found.FromJust()) {
    // 9b i. If targetDesc.[[Configurable]] is false, throw a TypeError
    // exception.
    if (!target_desc.configurable()) {
      isolate->Throw(*isolate->factory()->NewTypeError(
          MessageTemplate::kProxyHasNonConfigurable, name));
      return Nothing<bool>();
    }
    // 9b ii. Let extensibleTarget be ? IsExtensible(target).
    Maybe<bool> extensible_target = JSReceiver::IsExtensible(isolate, target);
    MAYBE_RETURN(extensible_target, Nothing<bool>());
    // 9b iii. If extensibleTarget is false, throw a TypeError exception.
    if (!extensible_target.FromJust()) {
      isolate->Throw(*isolate->factory()->NewTypeError(
          MessageTemplate::kProxyHasNonExtensible, name));
      return Nothing<bool>();
    }
  }
  return Just(true);
}
References v8::internal::PropertyDescriptor::configurable(), v8::internal::Isolate::factory(), v8::Maybe< T >::FromJust(), v8::internal::JSReceiver::GetOwnPropertyDescriptor(), v8::internal::JSReceiver::IsExtensible(), v8::Just(), MAYBE_RETURN, v8::internal::name, and v8::internal::Isolate::Throw().
Referenced by HasProperty(), and v8::internal::RUNTIME_FUNCTION().
DefineOwnProperty()
Maybe< bool > v8::internal::JSProxy::DefineOwnProperty (Isolate * isolate, DirectHandle< JSProxy > object, DirectHandle< Object > key, PropertyDescriptor * desc, Maybe< ShouldThrow > should_throw) [static]
Definition at line 3351 of file objects.cc.
                                                                        {
  STACK_CHECK(isolate, Nothing<bool>());
  if (IsSymbol(*key) && Cast<Symbol>(key)->IsPrivate()) {
    DCHECK(!Cast<Symbol>(key)->IsPrivateName());
    return JSProxy::SetPrivateSymbol(isolate, proxy, Cast<Symbol>(key), desc,
                                     should_throw);
  }
  DirectHandle<String> trap_name = isolate->factory()->defineProperty_string();
  // 1. Assert: IsPropertyKey(P) is true.
  DCHECK(IsName(*key) || IsNumber(*key));
  // 2. Let handler be the value of the [[ProxyHandler]] internal slot of O.
  DirectHandle<Object> handler(proxy->handler(), isolate);
  // 3. If handler is null, throw a TypeError exception.
  // 4. Assert: Type(handler) is Object.
  if (proxy->IsRevoked()) {
    isolate->Throw(*isolate->factory()->NewTypeError(
        MessageTemplate::kProxyRevoked, trap_name));
    return Nothing<bool>();
  }
  // 5. Let target be the value of the [[ProxyTarget]] internal slot of O.
  DirectHandle<JSReceiver> target(Cast<JSReceiver>(proxy->target()), isolate);
  // 6. Let trap be ? GetMethod(handler, "defineProperty").
  DirectHandle<Object> trap;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, trap,
      Object::GetMethod(isolate, Cast<JSReceiver>(handler), trap_name),
      Nothing<bool>());
  // 7. If trap is undefined, then:
  if (IsUndefined(*trap, isolate)) {
    // 7a. Return target.[[DefineOwnProperty]](P, Desc).
    return JSReceiver::DefineOwnProperty(isolate, target, key, desc,
                                         should_throw);
  }
  // 8. Let descObj be FromPropertyDescriptor(Desc).
  DirectHandle<Object> desc_obj = desc->ToObject(isolate);
  // 9. Let booleanTrapResult be
  // ToBoolean(? Call(trap, handler, «target, P, descObj»)).
  DirectHandle<Name> property_name =
      IsName(*key) ? Cast<Name>(key)
                   : Cast<Name>(isolate->factory()->NumberToString(key));
  // Do not leak private property names.
  DCHECK(!property_name->IsPrivate());
  DirectHandle<Object> trap_result_obj;
  DirectHandle<Object> args[] = {target, property_name, desc_obj};
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, trap_result_obj,
      Execution::Call(isolate, trap, handler, base::VectorOf(args)),
      Nothing<bool>());
  // 10. If booleanTrapResult is false, return false.
  if (!Object::BooleanValue(*trap_result_obj, isolate)) {
    RETURN_FAILURE(isolate, GetShouldThrow(isolate, should_throw),
                   NewTypeError(MessageTemplate::kProxyTrapReturnedFalsishFor,
                                trap_name, property_name));
  }
  // 11. Let targetDesc be ? target.[[GetOwnProperty]](P).
  PropertyDescriptor target_desc;
  Maybe<bool> target_found =
      JSReceiver::GetOwnPropertyDescriptor(isolate, target, key, &target_desc);
  MAYBE_RETURN(target_found, Nothing<bool>());
  // 12. Let extensibleTarget be ? IsExtensible(target).
  Maybe<bool> maybe_extensible = JSReceiver::IsExtensible(isolate, target);
  MAYBE_RETURN(maybe_extensible, Nothing<bool>());
  bool extensible_target = maybe_extensible.FromJust();
  // 13. If Desc has a [[Configurable]] field and if Desc.[[Configurable]]
  // is false, then:
  // 13a. Let settingConfigFalse be true.
  // 14. Else let settingConfigFalse be false.
  bool setting_config_false = desc->has_configurable() && !desc->configurable();
  // 15. If targetDesc is undefined, then
  if (!target_found.FromJust()) {
    // 15a. If extensibleTarget is false, throw a TypeError exception.
    if (!extensible_target) {
      isolate->Throw(*isolate->factory()->NewTypeError(
          MessageTemplate::kProxyDefinePropertyNonExtensible, property_name));
      return Nothing<bool>();
    }
    // 15b. If settingConfigFalse is true, throw a TypeError exception.
    if (setting_config_false) {
      isolate->Throw(*isolate->factory()->NewTypeError(
          MessageTemplate::kProxyDefinePropertyNonConfigurable, property_name));
      return Nothing<bool>();
    }
  } else {
    // 16. Else targetDesc is not undefined,
    // 16a. If IsCompatiblePropertyDescriptor(extensibleTarget, Desc,
    // targetDesc) is false, throw a TypeError exception.
    Maybe<bool> valid = IsCompatiblePropertyDescriptor(
        isolate, extensible_target, desc, &target_desc, property_name,
        Just(kDontThrow));
    MAYBE_RETURN(valid, Nothing<bool>());
    if (!valid.FromJust()) {
      isolate->Throw(*isolate->factory()->NewTypeError(
          MessageTemplate::kProxyDefinePropertyIncompatible, property_name));
      return Nothing<bool>();
    }
    // 16b. If settingConfigFalse is true and targetDesc.[[Configurable]] is
    // true, throw a TypeError exception.
    if (setting_config_false && target_desc.configurable()) {
      isolate->Throw(*isolate->factory()->NewTypeError(
          MessageTemplate::kProxyDefinePropertyNonConfigurable, property_name));
      return Nothing<bool>();
    }
    // 16c. If IsDataDescriptor(targetDesc) is true,
    // targetDesc.[[Configurable]] is
    // false, and targetDesc.[[Writable]] is true, then
    if (PropertyDescriptor::IsDataDescriptor(&target_desc) &&
        !target_desc.configurable() && target_desc.writable()) {
      // 16c i. If Desc has a [[Writable]] field and Desc.[[Writable]] is false,
      // throw a TypeError exception.
      if (desc->has_writable() && !desc->writable()) {
        isolate->Throw(*isolate->factory()->NewTypeError(
            MessageTemplate::kProxyDefinePropertyNonConfigurableWritable,
            property_name));
        return Nothing<bool>();
      }
    }
  }
  // 17. Return true.
  return Just(true);
}
References v8::base::args, ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::Object::BooleanValue(), v8::internal::Execution::Call(), v8::internal::PropertyDescriptor::configurable(), v8::internal::DCHECK(), v8::internal::JSReceiver::DefineOwnProperty(), v8::internal::Isolate::factory(), v8::Maybe< T >::FromJust(), v8::internal::Object::GetMethod(), v8::internal::JSReceiver::GetOwnPropertyDescriptor(), v8::internal::GetShouldThrow(), v8::internal::PropertyDescriptor::has_configurable(), v8::internal::PropertyDescriptor::has_writable(), v8::internal::PropertyDescriptor::IsDataDescriptor(), v8::internal::JSReceiver::IsExtensible(), v8::internal::IsNumber(), v8::Just(), v8::internal::kDontThrow, v8::internal::key, MAYBE_RETURN, v8::internal::FactoryBase< Impl >::NumberToString(), RETURN_FAILURE, SetPrivateSymbol(), STACK_CHECK, v8::internal::Isolate::Throw(), v8::internal::PropertyDescriptor::ToObject(), v8::base::VectorOf(), and v8::internal::PropertyDescriptor::writable().
Referenced by v8::internal::anonymous_namespace{ic.cc}::DefineOwnDataProperty(), and v8::internal::JSReceiver::DefineOwnProperty().
DeletePropertyOrElement()
Maybe< bool > v8::internal::JSProxy::DeletePropertyOrElement (DirectHandle< JSProxy > proxy, DirectHandle< Name > name, LanguageMode language_mode) [static]
Definition at line 3043 of file objects.cc.
                                                                         {
  DCHECK(!name->IsPrivate());
  ShouldThrow should_throw =
      is_sloppy(language_mode) ? kDontThrow : kThrowOnError;
  Isolate* isolate = Isolate::Current();
  STACK_CHECK(isolate, Nothing<bool>());
  Factory* factory = isolate->factory();
  DirectHandle<String> trap_name = factory->deleteProperty_string();
  if (proxy->IsRevoked()) {
    isolate->Throw(
        *factory->NewTypeError(MessageTemplate::kProxyRevoked, trap_name));
    return Nothing<bool>();
  }
  DirectHandle<JSReceiver> target(Cast<JSReceiver>(proxy->target()), isolate);
  DirectHandle<JSReceiver> handler(Cast<JSReceiver>(proxy->handler()), isolate);
  DirectHandle<Object> trap;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, trap, Object::GetMethod(isolate, handler, trap_name),
      Nothing<bool>());
  if (IsUndefined(*trap, isolate)) {
    return JSReceiver::DeletePropertyOrElement(isolate, target, name,
                                               language_mode);
  }
  DirectHandle<Object> trap_result;
  DirectHandle<Object> args[] = {target, name};
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, trap_result,
      Execution::Call(isolate, trap, handler, base::VectorOf(args)),
      Nothing<bool>());
  if (!Object::BooleanValue(*trap_result, isolate)) {
    RETURN_FAILURE(isolate, should_throw,
                   NewTypeError(MessageTemplate::kProxyTrapReturnedFalsishFor,
                                trap_name, name));
  }
  // Enforce the invariant.
  return JSProxy::CheckDeleteTrap(isolate, name, target);
}
References v8::base::args, ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::Object::BooleanValue(), v8::internal::Execution::Call(), CheckDeleteTrap(), v8::internal::Isolate::Current(), v8::internal::DCHECK(), v8::internal::JSReceiver::DeletePropertyOrElement(), v8::internal::Isolate::factory(), v8::internal::Object::GetMethod(), v8::internal::is_sloppy(), v8::internal::kDontThrow, v8::internal::kThrowOnError, v8::internal::name, RETURN_FAILURE, STACK_CHECK, v8::internal::Isolate::Throw(), and v8::base::VectorOf().
Referenced by v8::internal::JSReceiver::DeleteProperty().
GetOwnPropertyDescriptor()
Maybe< bool > v8::internal::JSProxy::GetOwnPropertyDescriptor (Isolate * isolate, DirectHandle< JSProxy > proxy, DirectHandle< Name > name, PropertyDescriptor * desc) [static]
Definition at line 3524 of file objects.cc.
                                                                        {
  DCHECK(!name->IsPrivate());
  STACK_CHECK(isolate, Nothing<bool>());
  DirectHandle<String> trap_name =
      isolate->factory()->getOwnPropertyDescriptor_string();
  // 1. (Assert)
  // 2. Let handler be the value of the [[ProxyHandler]] internal slot of O.
  DirectHandle<Object> handler(proxy->handler(), isolate);
  // 3. If handler is null, throw a TypeError exception.
  // 4. Assert: Type(handler) is Object.
  if (proxy->IsRevoked()) {
    isolate->Throw(*isolate->factory()->NewTypeError(
        MessageTemplate::kProxyRevoked, trap_name));
    return Nothing<bool>();
  }
  // 5. Let target be the value of the [[ProxyTarget]] internal slot of O.
  DirectHandle<JSReceiver> target(Cast<JSReceiver>(proxy->target()), isolate);
  // 6. Let trap be ? GetMethod(handler, "getOwnPropertyDescriptor").
  DirectHandle<Object> trap;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, trap,
      Object::GetMethod(isolate, Cast<JSReceiver>(handler), trap_name),
      Nothing<bool>());
  // 7. If trap is undefined, then
  if (IsUndefined(*trap, isolate)) {
    // 7a. Return target.[[GetOwnProperty]](P).
    return JSReceiver::GetOwnPropertyDescriptor(isolate, target, name, desc);
  }
  // 8. Let trapResultObj be ? Call(trap, handler, «target, P»).
  Handle<JSAny> trap_result_obj;
  DirectHandle<Object> args[] = {target, name};
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, trap_result_obj,
      Cast<JSAny>(
          Execution::Call(isolate, trap, handler, base::VectorOf(args))),
      Nothing<bool>());
  // 9. If Type(trapResultObj) is neither Object nor Undefined, throw a
  // TypeError exception.
  if (!IsJSReceiver(*trap_result_obj) &&
      !IsUndefined(*trap_result_obj, isolate)) {
    isolate->Throw(*isolate->factory()->NewTypeError(
        MessageTemplate::kProxyGetOwnPropertyDescriptorInvalid, name));
    return Nothing<bool>();
  }
  // 10. Let targetDesc be ? target.[[GetOwnProperty]](P).
  PropertyDescriptor target_desc;
  Maybe<bool> found =
      JSReceiver::GetOwnPropertyDescriptor(isolate, target, name, &target_desc);
  MAYBE_RETURN(found, Nothing<bool>());
  // 11. If trapResultObj is undefined, then
  if (IsUndefined(*trap_result_obj, isolate)) {
    // 11a. If targetDesc is undefined, return undefined.
    if (!found.FromJust()) return Just(false);
    // 11b. If targetDesc.[[Configurable]] is false, throw a TypeError
    // exception.
    if (!target_desc.configurable()) {
      isolate->Throw(*isolate->factory()->NewTypeError(
          MessageTemplate::kProxyGetOwnPropertyDescriptorUndefined, name));
      return Nothing<bool>();
    }
    // 11c. Let extensibleTarget be ? IsExtensible(target).
    Maybe<bool> extensible_target = JSReceiver::IsExtensible(isolate, target);
    MAYBE_RETURN(extensible_target, Nothing<bool>());
    // 11d. (Assert)
    // 11e. If extensibleTarget is false, throw a TypeError exception.
    if (!extensible_target.FromJust()) {
      isolate->Throw(*isolate->factory()->NewTypeError(
          MessageTemplate::kProxyGetOwnPropertyDescriptorNonExtensible, name));
      return Nothing<bool>();
    }
    // 11f. Return undefined.
    return Just(false);
  }
  // 12. Let extensibleTarget be ? IsExtensible(target).
  Maybe<bool> extensible_target = JSReceiver::IsExtensible(isolate, target);
  MAYBE_RETURN(extensible_target, Nothing<bool>());
  // 13. Let resultDesc be ? ToPropertyDescriptor(trapResultObj).
  if (!PropertyDescriptor::ToPropertyDescriptor(isolate, trap_result_obj,
                                                desc)) {
    DCHECK(isolate->has_exception());
    return Nothing<bool>();
  }
  // 14. Call CompletePropertyDescriptor(resultDesc).
  PropertyDescriptor::CompletePropertyDescriptor(isolate, desc);
  // 15. Let valid be IsCompatiblePropertyDescriptor (extensibleTarget,
  // resultDesc, targetDesc).
  Maybe<bool> valid = IsCompatiblePropertyDescriptor(
      isolate, extensible_target.FromJust(), desc, &target_desc, name,
      Just(kDontThrow));
  MAYBE_RETURN(valid, Nothing<bool>());
  // 16. If valid is false, throw a TypeError exception.
  if (!valid.FromJust()) {
    isolate->Throw(*isolate->factory()->NewTypeError(
        MessageTemplate::kProxyGetOwnPropertyDescriptorIncompatible, name));
    return Nothing<bool>();
  }
  // 17. If resultDesc.[[Configurable]] is false, then
  if (!desc->configurable()) {
    // 17a. If targetDesc is undefined or targetDesc.[[Configurable]] is true:
    if (target_desc.is_empty() || target_desc.configurable()) {
      // 17a i. Throw a TypeError exception.
      isolate->Throw(*isolate->factory()->NewTypeError(
          MessageTemplate::kProxyGetOwnPropertyDescriptorNonConfigurable,
          name));
      return Nothing<bool>();
    }
    // 17b. If resultDesc has a [[Writable]] field and resultDesc.[[Writable]]
    // is false, then
    if (desc->has_writable() && !desc->writable()) {
      // 17b i. If targetDesc.[[Writable]] is true, throw a TypeError exception.
      if (target_desc.writable()) {
        isolate->Throw(*isolate->factory()->NewTypeError(
            MessageTemplate::
                kProxyGetOwnPropertyDescriptorNonConfigurableWritable,
            name));
        return Nothing<bool>();
      }
    }
  }
  // 18. Return resultDesc.
  return Just(true);
}
References v8::base::args, ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::Execution::Call(), v8::internal::PropertyDescriptor::CompletePropertyDescriptor(), v8::internal::PropertyDescriptor::configurable(), v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::Maybe< T >::FromJust(), v8::internal::Object::GetMethod(), v8::internal::JSReceiver::GetOwnPropertyDescriptor(), v8::internal::Isolate::has_exception(), v8::internal::PropertyDescriptor::has_writable(), v8::internal::PropertyDescriptor::is_empty(), v8::internal::JSReceiver::IsExtensible(), v8::Just(), v8::internal::kDontThrow, MAYBE_RETURN, v8::internal::name, STACK_CHECK, v8::internal::Isolate::Throw(), v8::internal::PropertyDescriptor::ToPropertyDescriptor(), v8::base::VectorOf(), and v8::internal::PropertyDescriptor::writable().
Referenced by v8::internal::FilterProxyKeys(), v8::internal::JSReceiver::GetOwnPropertyDescriptor(), GetPropertyAttributes(), and v8::internal::anonymous_namespace{builtins-object.cc}::ObjectLookupAccessor().
GetProperty()
MaybeHandle< JSAny > v8::internal::JSProxy::GetProperty (Isolate * isolate, DirectHandle< JSProxy > proxy, DirectHandle< Name > name, DirectHandle< JSAny > receiver, bool * was_found) [static]
Definition at line 1330 of file objects.cc.
                                                         {
  *was_found = true;
  DCHECK(!name->IsPrivate());
  STACK_CHECK(isolate, kNullMaybeHandle);
  DirectHandle<Name> trap_name = isolate->factory()->get_string();
  // 1. Assert: IsPropertyKey(P) is true.
  // 2. Let handler be the value of the [[ProxyHandler]] internal slot of O.
  DirectHandle<UnionOf<JSReceiver, Null>> handler(proxy->handler(), isolate);
  // 3. If handler is null, throw a TypeError exception.
  // 4. Assert: Type(handler) is Object.
  if (proxy->IsRevoked()) {
    THROW_NEW_ERROR(isolate,
                    NewTypeError(MessageTemplate::kProxyRevoked, trap_name));
  }
  // 5. Let target be the value of the [[ProxyTarget]] internal slot of O.
  DirectHandle<JSReceiver> target(Cast<JSReceiver>(proxy->target()), isolate);
  // 6. Let trap be ? GetMethod(handler, "get").
  DirectHandle<Object> trap;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, trap,
      Object::GetMethod(isolate, Cast<JSReceiver>(handler), trap_name));
  // 7. If trap is undefined, then
  if (IsUndefined(*trap, isolate)) {
    // 7.a Return target.[[Get]](P, Receiver).
    PropertyKey key(isolate, name);
    LookupIterator it(isolate, receiver, key, target);
    MaybeHandle<JSAny> result = Cast<JSAny>(Object::GetProperty(&it));
    *was_found = it.IsFound();
    return result;
  }
  // 8. Let trapResult be ? Call(trap, handler, «target, P, Receiver»).
  Handle<Object> trap_result;
  DirectHandle<Object> args[] = {target, name, receiver};
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, trap_result,
      Execution::Call(isolate, trap, handler, base::VectorOf(args)));
  MaybeHandle<JSAny> result =
      JSProxy::CheckGetSetTrapResult(isolate, name, target, trap_result, kGet);
  if (result.is_null()) {
    return result;
  }
  // 11. Return trap_result
  return Cast<JSAny>(trap_result);
}
References v8::base::args, ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Execution::Call(), CheckGetSetTrapResult(), v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::Object::GetMethod(), v8::internal::Object::GetProperty(), v8::internal::LookupIterator::IsFound(), v8::internal::key, kGet, v8::internal::kNullMaybeHandle, v8::internal::name, v8::base::internal::result, STACK_CHECK, THROW_NEW_ERROR, and v8::base::VectorOf().
Referenced by v8::internal::Object::GetProperty().
GetPropertyAttributes()
Maybe< PropertyAttributes > v8::internal::JSProxy::GetPropertyAttributes (LookupIterator * it) [static]
Definition at line 3130 of file objects.cc.
                                                                           {
  PropertyDescriptor desc;
  Maybe<bool> found = JSProxy::GetOwnPropertyDescriptor(
      it->isolate(), it->GetHolder<JSProxy>(), it->GetName(), &desc);
  MAYBE_RETURN(found, Nothing<PropertyAttributes>());
  if (!found.FromJust()) return Just(ABSENT);
  return Just(desc.ToAttributes());
}
References v8::internal::ABSENT, v8::Maybe< T >::FromJust(), v8::internal::LookupIterator::GetHolder(), v8::internal::LookupIterator::GetName(), GetOwnPropertyDescriptor(), v8::internal::LookupIterator::isolate(), v8::Just(), MAYBE_RETURN, and v8::internal::PropertyDescriptor::ToAttributes().
Referenced by v8::internal::JSReceiver::GetPropertyAttributes(), and v8::internal::anonymous_namespace{runtime-forin.cc}::HasEnumerableProperty().
GetPrototype()
MaybeDirectHandle< JSPrototype > v8::internal::JSProxy::GetPrototype (DirectHandle< JSProxy > receiver) [static]
Definition at line 1460 of file objects.cc.
                                 {
  Isolate* isolate = Isolate::Current();
  DirectHandle<String> trap_name = isolate->factory()->getPrototypeOf_string();
  STACK_CHECK(isolate, {});
  // 1. Let handler be the value of the [[ProxyHandler]] internal slot.
  // 2. If handler is null, throw a TypeError exception.
  // 3. Assert: Type(handler) is Object.
  // 4. Let target be the value of the [[ProxyTarget]] internal slot.
  if (proxy->IsRevoked()) {
    THROW_NEW_ERROR(isolate,
                    NewTypeError(MessageTemplate::kProxyRevoked, trap_name));
  }
  DirectHandle<JSReceiver> target(Cast<JSReceiver>(proxy->target()), isolate);
  DirectHandle<JSReceiver> handler(Cast<JSReceiver>(proxy->handler()), isolate);
  // 5. Let trap be ? GetMethod(handler, "getPrototypeOf").
  DirectHandle<Object> trap;
  ASSIGN_RETURN_ON_EXCEPTION(isolate, trap,
                             Object::GetMethod(isolate, handler, trap_name));
  // 6. If trap is undefined, then return target.[[GetPrototypeOf]]().
  if (IsUndefined(*trap, isolate)) {
    return JSReceiver::GetPrototype(isolate, target);
  }
  // 7. Let handlerProto be ? Call(trap, handler, «target»).
  DirectHandle<Object> args[] = {target};
  DirectHandle<Object> handler_proto_result;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, handler_proto_result,
      Execution::Call(isolate, trap, handler, base::VectorOf(args)));
  // 8. If Type(handlerProto) is neither Object nor Null, throw a TypeError.
  DirectHandle<JSPrototype> handler_proto;
  if (!TryCast(handler_proto_result, &handler_proto)) {
    THROW_NEW_ERROR(isolate,
                    NewTypeError(MessageTemplate::kProxyGetPrototypeOfInvalid));
  }
  // 9. Let extensibleTarget be ? IsExtensible(target).
  Maybe<bool> is_extensible = JSReceiver::IsExtensible(isolate, target);
  MAYBE_RETURN(is_extensible, {});
  // 10. If extensibleTarget is true, return handlerProto.
  if (is_extensible.FromJust()) return handler_proto;
  // 11. Let targetProto be ? target.[[GetPrototypeOf]]().
  DirectHandle<JSPrototype> target_proto;
  ASSIGN_RETURN_ON_EXCEPTION(isolate, target_proto,
                             JSReceiver::GetPrototype(isolate, target));
  // 12. If SameValue(handlerProto, targetProto) is false, throw a TypeError.
  if (!Object::SameValue(*handler_proto, *target_proto)) {
    THROW_NEW_ERROR(
        isolate,
        NewTypeError(MessageTemplate::kProxyGetPrototypeOfNonExtensible));
  }
  // 13. Return handlerProto.
  return handler_proto;
}
References v8::base::args, ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Execution::Call(), v8::internal::Isolate::Current(), v8::internal::Isolate::factory(), v8::internal::Object::GetMethod(), v8::internal::JSReceiver::GetPrototype(), v8::internal::is_extensible, v8::internal::JSReceiver::IsExtensible(), MAYBE_RETURN, v8::internal::Object::SameValue(), STACK_CHECK, THROW_NEW_ERROR, v8::internal::TryCast(), and v8::base::VectorOf().
Referenced by v8::internal::PrototypeIterator::AdvanceFollowingProxiesIgnoringAccessChecks(), v8::internal::anonymous_namespace{runtime-forin.cc}::HasEnumerableProperty(), and v8::internal::anonymous_namespace{builtins-object.cc}::ObjectLookupAccessor().
HasProperty()
Maybe< bool > v8::internal::JSProxy::HasProperty (Isolate * isolate, DirectHandle< JSProxy > proxy, DirectHandle< Name > name) [static]
Definition at line 2918 of file objects.cc.
                                                          {
  DCHECK(!name->IsPrivate());
  STACK_CHECK(isolate, Nothing<bool>());
  // 1. (Assert)
  // 2. Let handler be the value of the [[ProxyHandler]] internal slot of O.
  DirectHandle<Object> handler(proxy->handler(), isolate);
  // 3. If handler is null, throw a TypeError exception.
  // 4. Assert: Type(handler) is Object.
  if (proxy->IsRevoked()) {
    isolate->Throw(*isolate->factory()->NewTypeError(
        MessageTemplate::kProxyRevoked, isolate->factory()->has_string()));
    return Nothing<bool>();
  }
  // 5. Let target be the value of the [[ProxyTarget]] internal slot of O.
  DirectHandle<JSReceiver> target(Cast<JSReceiver>(proxy->target()), isolate);
  // 6. Let trap be ? GetMethod(handler, "has").
  DirectHandle<Object> trap;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, trap,
      Object::GetMethod(isolate, Cast<JSReceiver>(handler),
                        isolate->factory()->has_string()),
      Nothing<bool>());
  // 7. If trap is undefined, then
  if (IsUndefined(*trap, isolate)) {
    // 7a. Return target.[[HasProperty]](P).
    return JSReceiver::HasProperty(isolate, target, name);
  }
  // 8. Let booleanTrapResult be ToBoolean(? Call(trap, handler, «target, P»)).
  DirectHandle<Object> trap_result_obj;
  DirectHandle<Object> args[] = {target, name};
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, trap_result_obj,
      Execution::Call(isolate, trap, handler, base::VectorOf(args)),
      Nothing<bool>());
  bool boolean_trap_result = Object::BooleanValue(*trap_result_obj, isolate);
  // 9. If booleanTrapResult is false, then:
  if (!boolean_trap_result) {
    MAYBE_RETURN(JSProxy::CheckHasTrap(isolate, name, target), Nothing<bool>());
  }
  // 10. Return booleanTrapResult.
  return Just(boolean_trap_result);
}
References v8::base::args, ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::Object::BooleanValue(), v8::internal::Execution::Call(), CheckHasTrap(), v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::Object::GetMethod(), v8::internal::JSReceiver::HasProperty(), v8::Just(), MAYBE_RETURN, v8::internal::name, STACK_CHECK, v8::internal::Isolate::Throw(), and v8::base::VectorOf().
Referenced by v8::internal::Object::GetProperty(), and v8::internal::JSReceiver::HasProperty().
is_revocable()
bool v8::internal::JSProxy::is_revocable () const [inline]
Definition at line 25 of file js-proxy-inl.h.
{ return IsRevocableBit::decode(flags()); }
References v8::internal::flags.
IsArray()
Maybe< bool > v8::internal::JSProxy::IsArray (DirectHandle< JSProxy > proxy) [static]
Definition at line 2897 of file objects.cc.
                                                        {
  Isolate* isolate = Isolate::Current();
  DirectHandle<JSReceiver> object = Cast<JSReceiver>(proxy);
  for (int i = 0; i < JSProxy::kMaxIterationLimit; i++) {
    proxy = Cast<JSProxy>(object);
    if (proxy->IsRevoked()) {
      isolate->Throw(*isolate->factory()->NewTypeError(
          MessageTemplate::kProxyRevoked,
          isolate->factory()->NewStringFromAsciiChecked("IsArray")));
      return Nothing<bool>();
    }
    object = direct_handle(Cast<JSReceiver>(proxy->target()), isolate);
    if (IsJSArray(*object)) return Just(true);
    if (!IsJSProxy(*object)) return Just(false);
  }
  // Too deep recursion, throw a RangeError.
  isolate->StackOverflow();
  return Nothing<bool>();
}
References v8::internal::Isolate::Current(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::Just(), kMaxIterationLimit, v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), v8::internal::Isolate::StackOverflow(), and v8::internal::Isolate::Throw().
Referenced by v8::internal::Object::IsArray().
IsExtensible()
Maybe< bool > v8::internal::JSProxy::IsExtensible (DirectHandle< JSProxy > proxy) [static]
Definition at line 3697 of file objects.cc.
                                                             {
  Isolate* isolate = Isolate::Current();
  STACK_CHECK(isolate, Nothing<bool>());
  Factory* factory = isolate->factory();
  DirectHandle<String> trap_name = factory->isExtensible_string();
  if (proxy->IsRevoked()) {
    isolate->Throw(
        *factory->NewTypeError(MessageTemplate::kProxyRevoked, trap_name));
    return Nothing<bool>();
  }
  DirectHandle<JSReceiver> target(Cast<JSReceiver>(proxy->target()), isolate);
  DirectHandle<JSReceiver> handler(Cast<JSReceiver>(proxy->handler()), isolate);
  DirectHandle<Object> trap;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, trap, Object::GetMethod(isolate, handler, trap_name),
      Nothing<bool>());
  if (IsUndefined(*trap, isolate)) {
    return JSReceiver::IsExtensible(isolate, target);
  }
  DirectHandle<Object> trap_result;
  DirectHandle<Object> args[] = {target};
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, trap_result,
      Execution::Call(isolate, trap, handler, base::VectorOf(args)),
      Nothing<bool>());
  // Enforce the invariant.
  Maybe<bool> target_result = JSReceiver::IsExtensible(isolate, target);
  MAYBE_RETURN(target_result, Nothing<bool>());
  if (target_result.FromJust() != Object::BooleanValue(*trap_result, isolate)) {
    isolate->Throw(
        *factory->NewTypeError(MessageTemplate::kProxyIsExtensibleInconsistent,
                               factory->ToBoolean(target_result.FromJust())));
    return Nothing<bool>();
  }
  return target_result;
}
References v8::base::args, ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::Object::BooleanValue(), v8::internal::Execution::Call(), v8::internal::Isolate::Current(), v8::internal::Isolate::factory(), v8::Maybe< T >::FromJust(), v8::internal::Object::GetMethod(), v8::internal::JSReceiver::IsExtensible(), MAYBE_RETURN, STACK_CHECK, v8::internal::Isolate::Throw(), v8::internal::FactoryBase< Impl >::ToBoolean(), and v8::base::VectorOf().
Referenced by v8::internal::JSReceiver::IsExtensible().
IsRevoked()
bool v8::internal::JSProxy::IsRevoked () const [inline]
Definition at line 27 of file js-proxy-inl.h.
{ return !IsJSReceiver(handler()); }
New()
MaybeDirectHandle< JSProxy > v8::internal::JSProxy::New (Isolate * isolate, DirectHandle< Object > target, DirectHandle< Object > handler, bool revocable) [static]
Definition at line 3116 of file objects.cc.
                                                        {
  if (!IsJSReceiver(*target)) {
    THROW_NEW_ERROR(isolate, NewTypeError(MessageTemplate::kProxyNonObject));
  }
  if (!IsJSReceiver(*handler)) {
    THROW_NEW_ERROR(isolate, NewTypeError(MessageTemplate::kProxyNonObject));
  }
  return isolate->factory()->NewJSProxy(Cast<JSReceiver>(target),
                                        Cast<JSReceiver>(handler), revocable);
}
References v8::internal::Isolate::factory(), v8::internal::Factory::NewJSProxy(), and THROW_NEW_ERROR.
Referenced by v8::Proxy::New().
PreventExtensions()
Maybe< bool > v8::internal::JSProxy::PreventExtensions (DirectHandle< JSProxy > proxy, ShouldThrow should_throw) [static]
Definition at line 3651 of file objects.cc.
                                                                 {
  Isolate* isolate = Isolate::Current();
  STACK_CHECK(isolate, Nothing<bool>());
  Factory* factory = isolate->factory();
  DirectHandle<String> trap_name = factory->preventExtensions_string();
  if (proxy->IsRevoked()) {
    isolate->Throw(
        *factory->NewTypeError(MessageTemplate::kProxyRevoked, trap_name));
    return Nothing<bool>();
  }
  DirectHandle<JSReceiver> target(Cast<JSReceiver>(proxy->target()), isolate);
  DirectHandle<JSReceiver> handler(Cast<JSReceiver>(proxy->handler()), isolate);
  DirectHandle<Object> trap;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, trap, Object::GetMethod(isolate, handler, trap_name),
      Nothing<bool>());
  if (IsUndefined(*trap, isolate)) {
    return JSReceiver::PreventExtensions(isolate, target, should_throw);
  }
  DirectHandle<Object> trap_result;
  DirectHandle<Object> args[] = {target};
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, trap_result,
      Execution::Call(isolate, trap, handler, base::VectorOf(args)),
      Nothing<bool>());
  if (!Object::BooleanValue(*trap_result, isolate)) {
    RETURN_FAILURE(
        isolate, should_throw,
        NewTypeError(MessageTemplate::kProxyTrapReturnedFalsish, trap_name));
  }
  // Enforce the invariant.
  Maybe<bool> target_result = JSReceiver::IsExtensible(isolate, target);
  MAYBE_RETURN(target_result, Nothing<bool>());
  if (target_result.FromJust()) {
    isolate->Throw(*factory->NewTypeError(
        MessageTemplate::kProxyPreventExtensionsExtensible));
    return Nothing<bool>();
  }
  return Just(true);
}
References v8::base::args, ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::Object::BooleanValue(), v8::internal::Execution::Call(), v8::internal::Isolate::Current(), v8::internal::Isolate::factory(), v8::Maybe< T >::FromJust(), v8::internal::Object::GetMethod(), v8::internal::JSReceiver::IsExtensible(), v8::Just(), MAYBE_RETURN, v8::internal::JSReceiver::PreventExtensions(), RETURN_FAILURE, STACK_CHECK, v8::internal::Isolate::Throw(), and v8::base::VectorOf().
Referenced by v8::internal::JSReceiver::PreventExtensions().
Revoke()
void v8::internal::JSProxy::Revoke (DirectHandle< JSProxy > proxy) [static]
Definition at line 2881 of file objects.cc.
                                                {
  Isolate* isolate = Isolate::Current();
  // If this fails then some Proxy allocation code path that created
  // revocable Proxies didn't set the bit correctly.
  CHECK(JSProxy::IsRevocableBit::decode(proxy->flags()));
  // ES#sec-proxy-revocation-functions
  if (!proxy->IsRevoked()) {
    // 5. Set p.[[ProxyTarget]] to null.
    proxy->set_target(ReadOnlyRoots(isolate).null_value());
    // 6. Set p.[[ProxyHandler]] to null.
    proxy->set_handler(ReadOnlyRoots(isolate).null_value());
  }
  DCHECK(proxy->IsRevoked());
}
References CHECK, v8::internal::Isolate::Current(), v8::internal::DCHECK(), and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::Proxy::Revoke().
SetPrivateSymbol()
Maybe< bool > v8::internal::JSProxy::SetPrivateSymbol (Isolate * isolate, DirectHandle< JSProxy > proxy, DirectHandle< Symbol > private_name, PropertyDescriptor * desc, Maybe< ShouldThrow > should_throw) [static]
Definition at line 3477 of file objects.cc.
                                                                       {
  // Despite the generic name, this can only add private data properties.
  if (!PropertyDescriptor::IsDataDescriptor(desc) ||
      desc->ToAttributes() != DONT_ENUM) {
    RETURN_FAILURE(isolate, GetShouldThrow(isolate, should_throw),
                   NewTypeError(MessageTemplate::kProxyPrivate));
  }
  DCHECK(proxy->map()->is_dictionary_map());
  DirectHandle<Object> value =
      desc->has_value() ? desc->value()
                        : Cast<Object>(isolate->factory()->undefined_value());
  LookupIterator it(isolate, proxy, private_name, proxy);
  if (it.IsFound()) {
    DCHECK_EQ(LookupIterator::DATA, it.state());
    DCHECK_EQ(DONT_ENUM, it.property_attributes());
    // We are not tracking constness for private symbols added to JSProxy
    // objects.
    DCHECK_EQ(PropertyConstness::kMutable, it.property_details().constness());
    it.WriteDataValue(value, false);
    return Just(true);
  }
  PropertyDetails details(PropertyKind::kData, DONT_ENUM,
                          PropertyConstness::kMutable);
  if constexpr (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
    DirectHandle<SwissNameDictionary> dict(proxy->property_dictionary_swiss(),
                                           isolate);
    DirectHandle<SwissNameDictionary> result =
        SwissNameDictionary::Add(isolate, dict, private_name, value, details);
    if (!dict.is_identical_to(result)) proxy->SetProperties(*result);
  } else {
    DirectHandle<NameDictionary> dict(proxy->property_dictionary(), isolate);
    DirectHandle<NameDictionary> result =
        NameDictionary::Add(isolate, dict, private_name, value, details);
    if (!dict.is_identical_to(result)) proxy->SetProperties(*result);
  }
  return Just(true);
}
References v8::bigint::Add(), v8::internal::PropertyDetails::constness(), v8::internal::LookupIterator::DATA, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::DONT_ENUM, v8::internal::Isolate::factory(), v8::internal::GetShouldThrow(), v8::internal::PropertyDescriptor::has_value(), v8::internal::DirectHandle< T >::is_identical_to(), v8::internal::PropertyDescriptor::IsDataDescriptor(), v8::internal::LookupIterator::IsFound(), v8::Just(), v8::internal::kData, v8::internal::kMutable, v8::internal::LookupIterator::property_attributes(), v8::internal::LookupIterator::property_details(), v8::base::internal::result, RETURN_FAILURE, v8::internal::LookupIterator::state(), v8::internal::PropertyDescriptor::ToAttributes(), V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL, v8::internal::value, v8::internal::PropertyDescriptor::value(), and v8::internal::LookupIterator::WriteDataValue().
Referenced by v8::internal::JSReceiver::AddPrivateField(), DefineOwnProperty(), and v8::Object::SetPrivate().
SetProperty()
Maybe< bool > v8::internal::JSProxy::SetProperty (DirectHandle< JSProxy > proxy, DirectHandle< Name > name, DirectHandle< Object > value, DirectHandle< JSAny > receiver, Maybe< ShouldThrow > should_throw) [static]
Definition at line 2991 of file objects.cc.
                                                                  {
  DCHECK(!name->IsPrivate());
  Isolate* isolate = Isolate::Current();
  STACK_CHECK(isolate, Nothing<bool>());
  Factory* factory = isolate->factory();
  DirectHandle<String> trap_name = factory->set_string();
  if (proxy->IsRevoked()) {
    isolate->Throw(
        *factory->NewTypeError(MessageTemplate::kProxyRevoked, trap_name));
    return Nothing<bool>();
  }
  DirectHandle<JSReceiver> target(Cast<JSReceiver>(proxy->target()), isolate);
  DirectHandle<JSReceiver> handler(Cast<JSReceiver>(proxy->handler()), isolate);
  DirectHandle<Object> trap;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, trap, Object::GetMethod(isolate, handler, trap_name),
      Nothing<bool>());
  if (IsUndefined(*trap, isolate)) {
    PropertyKey key(isolate, name);
    LookupIterator it(isolate, receiver, key, target);
    return Object::SetSuperProperty(&it, value, StoreOrigin::kMaybeKeyed,
                                    should_throw);
  }
  DirectHandle<Object> trap_result;
  DirectHandle<Object> args[] = {target, name, value, receiver};
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, trap_result,
      Execution::Call(isolate, trap, handler, base::VectorOf(args)),
      Nothing<bool>());
  if (!Object::BooleanValue(*trap_result, isolate)) {
    RETURN_FAILURE(isolate, GetShouldThrow(isolate, should_throw),
                   NewTypeError(MessageTemplate::kProxyTrapReturnedFalsishFor,
                                trap_name, name));
  }
  MaybeDirectHandle<Object> result =
      JSProxy::CheckGetSetTrapResult(isolate, name, target, value, kSet);
  if (result.is_null()) {
    return Nothing<bool>();
  }
  return Just(true);
}
References v8::base::args, ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::Object::BooleanValue(), v8::internal::Execution::Call(), CheckGetSetTrapResult(), v8::internal::Isolate::Current(), v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::Object::GetMethod(), v8::internal::GetShouldThrow(), v8::Just(), v8::internal::key, v8::internal::kMaybeKeyed, kSet, v8::internal::name, v8::base::internal::result, RETURN_FAILURE, v8::internal::Object::SetSuperProperty(), STACK_CHECK, v8::internal::Isolate::Throw(), v8::internal::value, and v8::base::VectorOf().
Referenced by v8::internal::Object::SetPropertyInternal().
SetPrototype()
Maybe< bool > v8::internal::JSProxy::SetPrototype (Isolate * isolate, DirectHandle< JSProxy > proxy, DirectHandle< Object > value, bool from_javascript, ShouldThrow should_throw) [static]
Definition at line 4880 of file objects.cc.
                                                            {
  STACK_CHECK(isolate, Nothing<bool>());
  DirectHandle<Name> trap_name = isolate->factory()->setPrototypeOf_string();
  // 1. Assert: Either Type(V) is Object or Type(V) is Null.
  DCHECK(IsJSReceiver(*value) || IsNull(*value, isolate));
  // 2. Let handler be the value of the [[ProxyHandler]] internal slot of O.
  DirectHandle<Object> handler(proxy->handler(), isolate);
  // 3. If handler is null, throw a TypeError exception.
  // 4. Assert: Type(handler) is Object.
  if (proxy->IsRevoked()) {
    isolate->Throw(*isolate->factory()->NewTypeError(
        MessageTemplate::kProxyRevoked, trap_name));
    return Nothing<bool>();
  }
  // 5. Let target be the value of the [[ProxyTarget]] internal slot.
  DirectHandle<JSReceiver> target(Cast<JSReceiver>(proxy->target()), isolate);
  // 6. Let trap be ? GetMethod(handler, "getPrototypeOf").
  DirectHandle<Object> trap;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, trap,
      Object::GetMethod(isolate, Cast<JSReceiver>(handler), trap_name),
      Nothing<bool>());
  // 7. If trap is undefined, then return target.[[SetPrototypeOf]]().
  if (IsUndefined(*trap, isolate)) {
    return JSReceiver::SetPrototype(isolate, target, value, from_javascript,
                                    should_throw);
  }
  // 8. Let booleanTrapResult be ToBoolean(? Call(trap, handler, «target, V»)).
  DirectHandle<Object> args[] = {target, value};
  DirectHandle<Object> trap_result;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, trap_result,
      Execution::Call(isolate, trap, handler, base::VectorOf(args)),
      Nothing<bool>());
  bool bool_trap_result = Object::BooleanValue(*trap_result, isolate);
  // 9. If booleanTrapResult is false, return false.
  if (!bool_trap_result) {
    RETURN_FAILURE(
        isolate, should_throw,
        NewTypeError(MessageTemplate::kProxyTrapReturnedFalsish, trap_name));
  }
  // 10. Let extensibleTarget be ? IsExtensible(target).
  Maybe<bool> is_extensible = JSReceiver::IsExtensible(isolate, target);
  if (is_extensible.IsNothing()) return Nothing<bool>();
  // 11. If extensibleTarget is true, return true.
  if (is_extensible.FromJust()) {
    if (bool_trap_result) return Just(true);
    RETURN_FAILURE(
        isolate, should_throw,
        NewTypeError(MessageTemplate::kProxyTrapReturnedFalsish, trap_name));
  }
  // 12. Let targetProto be ? target.[[GetPrototypeOf]]().
  DirectHandle<Object> target_proto;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(isolate, target_proto,
                                   JSReceiver::GetPrototype(isolate, target),
                                   Nothing<bool>());
  // 13. If SameValue(V, targetProto) is false, throw a TypeError exception.
  if (bool_trap_result && !Object::SameValue(*value, *target_proto)) {
    isolate->Throw(*isolate->factory()->NewTypeError(
        MessageTemplate::kProxySetPrototypeOfNonExtensible));
    return Nothing<bool>();
  }
  // 14. Return true.
  return Just(true);
}
References v8::base::args, ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::Object::BooleanValue(), v8::internal::Execution::Call(), v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::Object::GetMethod(), v8::internal::JSReceiver::GetPrototype(), v8::internal::is_extensible, v8::internal::JSReceiver::IsExtensible(), v8::internal::IsNull(), v8::Just(), RETURN_FAILURE, v8::internal::Object::SameValue(), v8::internal::JSReceiver::SetPrototype(), STACK_CHECK, v8::internal::Isolate::Throw(), v8::internal::value, and v8::base::VectorOf().
Referenced by v8::internal::JSReceiver::SetPrototype(), and v8::anonymous_namespace{api.cc}::SetPrototypeImpl().
Member Data Documentation
kIsRevocableBit
constexpr int v8::internal::JSProxy::kIsRevocableBit = IsRevocableBit::encode(true) [static], [constexpr]
Definition at line 125 of file js-proxy.h.
kMaxIterationLimit
const int v8::internal::JSProxy::kMaxIterationLimit = 100 * 1024 [static]
Definition at line 106 of file js-proxy.h.
Referenced by v8::internal::PrototypeIterator::AdvanceFollowingProxiesIgnoringAccessChecks(), and IsArray().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-proxy.h
/mnt/V8SourceCode/src/objects/js-proxy-inl.h
/mnt/V8SourceCode/src/objects/objects.cc