v8::internal::ZoneCompactSet< T > Class Template Reference
#include <zone-compact-set.h>
Classes
class const_iterator
Public Member Functions
ZoneCompactSet ()
ZoneCompactSet (T handle)
ZoneCompactSet (std::initializer_list< T > handles, Zone *zone)
ZoneCompactSet (const ZoneCompactSet &other) V8_NOEXCEPT=default
ZoneCompactSet & operator= (const ZoneCompactSet &other) V8_NOEXCEPT=default
ZoneCompactSet (ZoneCompactSet &&other) V8_NOEXCEPT=default
ZoneCompactSet & operator= (ZoneCompactSet &&other) V8_NOEXCEPT=default
template<class It , typename = typename std::iterator_traits<It>::iterator_category>
ZoneCompactSet (It first, It last, Zone *zone)
ZoneCompactSet< T > Clone (Zone *zone) const
bool is_empty () const
size_t size () const
T at (size_t i) const
T operator[] (size_t i) const
void insert (T handle, Zone *zone)
void Union (ZoneCompactSet< T > const &other, Zone *zone)
bool contains (ZoneCompactSet< T > const &other) const
bool contains (T handle) const
void remove (T handle, Zone *zone)
void clear ()
const_iterator begin () const
const_iterator end () const
Private Types
enum Tag { kSingletonTag = 0
, kEmptyTag = 1
, kListTag = 2
 }
using Traits = ZoneCompactSetTraits< T >
using handle_type = typename Traits::handle_type
using data_type = typename Traits::data_type
using List = base::Vector< data_type * >
using PointerWithPayload = base::PointerWithPayload< void, Tag, 2 >
Private Member Functions
bool is_singleton () const
bool is_list () const
List const * list () const
data_type * singleton () const
List * NewList (size_t size, Zone *zone)
Static Private Member Functions
static PointerWithPayload EmptyValue ()
Private Attributes
PointerWithPayload data_
Friends
bool operator== (ZoneCompactSet< T > const &lhs, ZoneCompactSet< T > const &rhs)
bool operator!= (ZoneCompactSet< T > const &lhs, ZoneCompactSet< T > const &rhs)
uintptr_t hash_value (ZoneCompactSet< T > const &set)
Detailed Description
template<typename T>
class v8::internal::ZoneCompactSet< T >
Definition at line 52 of file zone-compact-set.h.
Member Typedef Documentation
data_type
template<typename T >
using v8::internal::ZoneCompactSet< T >::data_type = typename Traits::data_type [private]
Definition at line 58 of file zone-compact-set.h.
handle_type
template<typename T >
using v8::internal::ZoneCompactSet< T >::handle_type = typename Traits::handle_type [private]
Definition at line 57 of file zone-compact-set.h.
List
template<typename T >
using v8::internal::ZoneCompactSet< T >::List = base::Vector<data_type*> [private]
Definition at line 275 of file zone-compact-set.h.
PointerWithPayload
template<typename T >
using v8::internal::ZoneCompactSet< T >::PointerWithPayload = base::PointerWithPayload<void, Tag, 2> [private]
Definition at line 276 of file zone-compact-set.h.
Traits
template<typename T >
using v8::internal::ZoneCompactSet< T >::Traits = ZoneCompactSetTraits<T> [private]
Definition at line 56 of file zone-compact-set.h.
Member Enumeration Documentation
Tag
template<typename T >
enum v8::internal::ZoneCompactSet::Tag [private]
Enumerator
kSingletonTag
kEmptyTag
kListTag
Definition at line 273 of file zone-compact-set.h.
{ kSingletonTag = 0, kEmptyTag = 1, kListTag = 2 };
Constructor & Destructor Documentation
ZoneCompactSet() [1/6]
template<typename T >
v8::internal::ZoneCompactSet< T >::ZoneCompactSet () [inline]
Definition at line 61 of file zone-compact-set.h.
: data_(kEmptyTag) {}
ZoneCompactSet() [2/6]
template<typename T >
v8::internal::ZoneCompactSet< T >::ZoneCompactSet (T handle) [inline], [explicit]
Definition at line 62 of file zone-compact-set.h.
      : data_(Traits::HandleToPointer(handle), kSingletonTag) {}
ZoneCompactSet() [3/6]
template<typename T >
v8::internal::ZoneCompactSet< T >::ZoneCompactSet (std::initializer_list< T > handles, Zone * zone) [inline], [explicit]
Definition at line 64 of file zone-compact-set.h.
      : ZoneCompactSet(handles.begin(), handles.end(), zone) {}
ZoneCompactSet() [4/6]
template<typename T >
v8::internal::ZoneCompactSet< T >::ZoneCompactSet (const ZoneCompactSet< T > & other) [default]
ZoneCompactSet() [5/6]
template<typename T >
v8::internal::ZoneCompactSet< T >::ZoneCompactSet (ZoneCompactSet< T > && other) [default]
ZoneCompactSet() [6/6]
template<typename T >
template<class It , typename = typename std::iterator_traits<It>::iterator_category>
v8::internal::ZoneCompactSet< T >::ZoneCompactSet (It first, It last, Zone * zone) [inline], [explicit]
Definition at line 74 of file zone-compact-set.h.
                                                         {
    auto size = last - first;
    if (size == 0) {
      data_ = EmptyValue();
    } else if (size == 1) {
      data_ =
          PointerWithPayload(Traits::HandleToPointer(*first), kSingletonTag);
    } else {
      List* list = NewList(size, zone);
      auto list_it = list->begin();
      for (auto it = first; it != last; ++it) {
        *list_it = Traits::HandleToPointer(*it);
        list_it++;
      }
      std::sort(list->begin(), list->end());
      data_ = PointerWithPayload(list, kListTag);
    }
  }
References v8::base::Vector< T >::begin(), v8::internal::ZoneCompactSet< T >::data_, v8::internal::ZoneCompactSet< T >::EmptyValue(), v8::base::Vector< T >::end(), v8::internal::ZoneCompactSet< T >::kListTag, v8::internal::ZoneCompactSet< T >::kSingletonTag, v8::internal::ZoneCompactSet< T >::list(), v8::internal::ZoneCompactSet< T >::NewList(), v8::internal::ZoneCompactSet< T >::size(), and v8::base::sort().
Member Function Documentation
at()
template<typename T >
T v8::internal::ZoneCompactSet< T >::at (size_t i) const [inline]
Definition at line 105 of file zone-compact-set.h.
                       {
    DCHECK_NE(kEmptyTag, data_.GetPayload());
    if (is_singleton()) {
      DCHECK_EQ(0u, i);
      return Traits::PointerToHandle(singleton());
    }
    return Traits::PointerToHandle(list()->at(static_cast<int>(i)));
  }
References v8::internal::ZoneCompactSet< T >::data_, DCHECK_EQ, DCHECK_NE, v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::GetPayload(), v8::internal::ZoneCompactSet< T >::is_singleton(), v8::internal::ZoneCompactSet< T >::kEmptyTag, v8::internal::ZoneCompactSet< T >::list(), and v8::internal::ZoneCompactSet< T >::singleton().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildCompareMaps(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::CanInlineArrayIteratingBuiltin(), v8::internal::compiler::LoadElimination::AliasStateInfo::MayAlias(), v8::internal::operator<<(), v8::internal::ZoneCompactSet< T >::operator[](), and v8::internal::ZoneCompactSet< T >::Union().
begin()
template<typename T >
ZoneCompactSet< T >::const_iterator v8::internal::ZoneCompactSet< T >::begin [inline]
Definition at line 356 of file zone-compact-set.h.
                                                                        {
  return ZoneCompactSet<T>::const_iterator(this, 0);
}
Referenced by v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::AllOfInstanceTypesUnsafe(), v8::internal::compiler::AnyMapIsHeapNumber(), v8::internal::maglev::MaglevGraphBuilder::BuildTestUndetectable(), v8::internal::ZoneCompactSet< T >::Clone(), v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeHasOwnProperty(), v8::internal::maglev::NodeInfo::SetPossibleMaps(), and v8::internal::maglev::MaglevGraphBuilder::TryReduceArrayIteratingBuiltin().
clear()
template<typename T >
void v8::internal::ZoneCompactSet< T >::clear () [inline]
Definition at line 245 of file zone-compact-set.h.
{ data_ = EmptyValue(); }
References v8::internal::ZoneCompactSet< T >::data_, and v8::internal::ZoneCompactSet< T >::EmptyValue().
Referenced by v8::internal::maglev::NodeInfo::ClearUnstableMaps(), and v8::internal::maglev::NodeInfo::MergeWith().
Clone()
template<typename T >
ZoneCompactSet<T> v8::internal::ZoneCompactSet< T >::Clone (Zone * zone) const [inline]
Definition at line 93 of file zone-compact-set.h.
                                            {
    return ZoneCompactSet<T>(begin(), end(), zone);
  }
References v8::internal::ZoneCompactSet< T >::begin(), and v8::internal::ZoneCompactSet< T >::end().
contains() [1/2]
template<typename T >
bool v8::internal::ZoneCompactSet< T >::contains (T handle) const [inline]
Definition at line 190 of file zone-compact-set.h.
                                {
    if (is_empty()) return false;
    data_type* pointer = Traits::HandleToPointer(handle);
    if (is_singleton()) {
      return singleton() == pointer;
    }
    const List* list = this->list();
    DCHECK(std::is_sorted(list->begin(), list->end()));
    return std::binary_search(list->begin(), list->end(), pointer);
  }
References v8::base::Vector< T >::begin(), v8::internal::DCHECK(), v8::base::Vector< T >::end(), v8::internal::handle(), v8::internal::ZoneCompactSet< T >::is_empty(), v8::internal::ZoneCompactSet< T >::is_singleton(), v8::internal::ZoneCompactSet< T >::list(), and v8::internal::ZoneCompactSet< T >::singleton().
contains() [2/2]
template<typename T >
bool v8::internal::ZoneCompactSet< T >::contains (ZoneCompactSet< T > const & other) const [inline]
Definition at line 163 of file zone-compact-set.h.
                                                      {
    if (data_ == other.data_) return true;
    if (is_empty()) return false;
    if (other.is_empty()) return true;
    if (is_singleton()) {
      DCHECK_IMPLIES(other.is_singleton(), other.singleton() != singleton());
      return false;
    }
    const List* list = this->list();
    DCHECK(std::is_sorted(list->begin(), list->end()));
    if (other.is_singleton()) {
      return std::binary_search(list->begin(), list->end(), other.singleton());
    }
    DCHECK(other.is_list());
    DCHECK(std::is_sorted(other.list()->begin(), other.list()->end()));
    // For each element in the `other` list, find the matching element in this
    // list. Since both lists are sorted, each search candidate will be larger
    // than the previous, and each found element will be the lower bound for
    // the search of the next element.
    auto it = list->begin();
    for (const data_type* pointer : *other.list()) {
      it = std::lower_bound(it, list->end(), pointer);
      if (it == list->end() || *it != pointer) return false;
    }
    return true;
  }
References v8::base::Vector< T >::begin(), v8::internal::ZoneCompactSet< T >::data_, v8::internal::DCHECK(), DCHECK_IMPLIES, v8::base::Vector< T >::end(), v8::internal::ZoneCompactSet< T >::is_empty(), v8::internal::ZoneCompactSet< T >::is_list(), v8::internal::ZoneCompactSet< T >::is_singleton(), v8::internal::ZoneCompactSet< T >::list(), and v8::internal::ZoneCompactSet< T >::singleton().
Referenced by v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::anonymous_namespace{escape-analysis.cc}::CheckMapsHelper(), v8::internal::compiler::LoadElimination::ComputeLoopState(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::NodeInfoIncludes(), v8::internal::compiler::LoadElimination::ReduceCheckMaps(), v8::internal::compiler::LoadElimination::ReduceCompareMaps(), v8::internal::compiler::LoadElimination::ReduceEnsureWritableFastElements(), v8::internal::compiler::LoadElimination::ReduceMapGuard(), v8::internal::compiler::LoadElimination::ReduceTransitionElementsKind(), v8::internal::compiler::LoadElimination::ReduceTransitionElementsKindOrCheckMap(), v8::internal::compiler::ElementAccessFeedback::Refine(), and v8::internal::maglev::MaglevGraphBuilder::TryReduceArrayIteratingBuiltin().
EmptyValue()
template<typename T >
static PointerWithPayload v8::internal::ZoneCompactSet< T >::EmptyValue () [inline], [static], [private]
Definition at line 298 of file zone-compact-set.h.
                                         {
    return PointerWithPayload(nullptr, kEmptyTag);
  }
References v8::internal::ZoneCompactSet< T >::kEmptyTag.
Referenced by v8::internal::ZoneCompactSet< T >::clear(), v8::internal::ZoneCompactSet< T >::is_empty(), v8::internal::ZoneCompactSet< T >::remove(), and v8::internal::ZoneCompactSet< T >::ZoneCompactSet().
end()
template<typename T >
ZoneCompactSet< T >::const_iterator v8::internal::ZoneCompactSet< T >::end [inline]
Definition at line 361 of file zone-compact-set.h.
                                                                      {
  return ZoneCompactSet<T>::const_iterator(this, size());
}
References size().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::AllOfInstanceTypesUnsafe(), v8::internal::compiler::AnyMapIsHeapNumber(), v8::internal::maglev::MaglevGraphBuilder::BuildTestUndetectable(), v8::internal::ZoneCompactSet< T >::Clone(), and v8::internal::maglev::MaglevGraphBuilder::TryReduceArrayIteratingBuiltin().
insert()
template<typename T >
void v8::internal::ZoneCompactSet< T >::insert (T handle, Zone * zone) [inline]
Definition at line 116 of file zone-compact-set.h.
                                    {
    data_type* const value = Traits::HandleToPointer(handle);
    if (is_empty()) {
      data_ = PointerWithPayload(value, kSingletonTag);
    } else if (is_singleton()) {
      if (singleton() == value) return;
      List* list = NewList(2, zone);
      if (singleton() < value) {
        (*list)[0] = singleton();
        (*list)[1] = value;
      } else {
        (*list)[0] = value;
        (*list)[1] = singleton();
      }
      data_ = PointerWithPayload(list, kListTag);
    } else {
      const List* current_list = list();
      auto it =
          std::lower_bound(current_list->begin(), current_list->end(), value);
      if (it != current_list->end() && *it == value) {
        // Already in the list.
        return;
      }
      // Otherwise, lower_bound returned the insertion position to keep the list
      // sorted.
      DCHECK(it == current_list->end() || *it > value);
      // We need to copy the list to mutate it, so that trivial copies of the
      // data_ pointer don't observe changes to the list.
      // TODO(leszeks): Avoid copying on every insertion by introducing some
      // concept of mutable/immutable/frozen/CoW sets.
      List* new_list = NewList(current_list->size() + 1, zone);
      auto new_it = new_list->begin();
      new_it = std::copy(current_list->begin(), it, new_it);
      *new_it++ = value;
      new_it = std::copy(it, current_list->end(), new_it);
      DCHECK_EQ(new_it, new_list->end());
      DCHECK(std::is_sorted(new_list->begin(), new_list->end()));
      data_ = PointerWithPayload(new_list, kListTag);
    }
  }
References v8::base::Vector< T >::begin(), v8::internal::ZoneCompactSet< T >::data_, v8::internal::DCHECK(), DCHECK_EQ, v8::base::Vector< T >::end(), v8::internal::handle(), v8::internal::ZoneCompactSet< T >::is_empty(), v8::internal::ZoneCompactSet< T >::is_singleton(), v8::internal::ZoneCompactSet< T >::kListTag, v8::internal::ZoneCompactSet< T >::kSingletonTag, v8::internal::ZoneCompactSet< T >::list(), v8::internal::ZoneCompactSet< T >::NewList(), v8::internal::ZoneCompactSet< T >::singleton(), v8::base::Vector< T >::size(), and v8::internal::value.
Referenced by v8::internal::compiler::PropertyAccessBuilder::BuildCheckMaps(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::KnownMapsMerger::InsertMap(), v8::internal::compiler::LoadElimination::ReduceTransitionAndStoreElement(), v8::internal::compiler::LoadElimination::ReduceTransitionElementsKind(), v8::internal::compiler::LoadElimination::ReduceTransitionElementsKindOrCheckMap(), and v8::internal::ZoneCompactSet< T >::Union().
is_empty()
template<typename T >
bool v8::internal::ZoneCompactSet< T >::is_empty () const [inline]
Definition at line 97 of file zone-compact-set.h.
{ return data_ == EmptyValue(); }
References v8::internal::ZoneCompactSet< T >::data_, and v8::internal::ZoneCompactSet< T >::EmptyValue().
Referenced by v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::CompareMapAgainstMultipleMaps(), v8::internal::ZoneCompactSet< T >::contains(), v8::internal::ZoneCompactSet< T >::insert(), v8::internal::ZoneCompactSet< T >::remove(), v8::internal::ZoneCompactSet< T >::size(), v8::internal::maglev::MaglevGraphBuilder::TryBuildNamedAccess(), and v8::internal::maglev::MaglevGraphBuilder::TryReduceDatePrototypeGetField().
is_list()
template<typename T >
bool v8::internal::ZoneCompactSet< T >::is_list () const [inline], [private]
Definition at line 279 of file zone-compact-set.h.
{ return data_.GetPayload() == kListTag; }
References v8::internal::ZoneCompactSet< T >::data_, v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::GetPayload(), and v8::internal::ZoneCompactSet< T >::kListTag.
Referenced by v8::internal::ZoneCompactSet< T >::contains(), and v8::internal::ZoneCompactSet< T >::list().
is_singleton()
template<typename T >
bool v8::internal::ZoneCompactSet< T >::is_singleton () const [inline], [private]
Definition at line 278 of file zone-compact-set.h.
{ return data_.GetPayload() == kSingletonTag; }
References v8::internal::ZoneCompactSet< T >::data_, v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::GetPayload(), and v8::internal::ZoneCompactSet< T >::kSingletonTag.
Referenced by v8::internal::ZoneCompactSet< T >::at(), v8::internal::ZoneCompactSet< T >::contains(), v8::internal::ZoneCompactSet< T >::insert(), v8::internal::ZoneCompactSet< T >::remove(), and v8::internal::ZoneCompactSet< T >::size().
list()
template<typename T >
List const* v8::internal::ZoneCompactSet< T >::list () const [inline], [private]
Definition at line 281 of file zone-compact-set.h.
                           {
    DCHECK(is_list());
    return static_cast<List const*>(data_.GetPointerWithKnownPayload(kListTag));
  }
References v8::internal::ZoneCompactSet< T >::data_, v8::internal::DCHECK(), v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::GetPointerWithKnownPayload(), v8::internal::ZoneCompactSet< T >::is_list(), and v8::internal::ZoneCompactSet< T >::kListTag.
Referenced by v8::internal::ZoneCompactSet< T >::at(), v8::internal::ZoneCompactSet< T >::contains(), v8::internal::ZoneCompactSet< T >::insert(), v8::internal::ZoneCompactSet< T >::remove(), v8::internal::ZoneCompactSet< T >::size(), and v8::internal::ZoneCompactSet< T >::ZoneCompactSet().
NewList()
template<typename T >
List* v8::internal::ZoneCompactSet< T >::NewList (size_t size, Zone * zone) [inline], [private]
Definition at line 291 of file zone-compact-set.h.
                                         {
    // We need to allocate both the List, and the backing store of the list, in
    // the zone, so that we have a List pointer and not an on-stack List (which
    // we can't use in the `data_` pointer).
    return zone->New<List>(zone->AllocateArray<data_type*>(size), size);
  }
References v8::internal::Zone::AllocateArray(), v8::internal::Zone::New(), and v8::internal::ZoneCompactSet< T >::size().
Referenced by v8::internal::ZoneCompactSet< T >::insert(), v8::internal::ZoneCompactSet< T >::remove(), and v8::internal::ZoneCompactSet< T >::ZoneCompactSet().
operator=() [1/2]
template<typename T >
ZoneCompactSet& v8::internal::ZoneCompactSet< T >::operator= (const ZoneCompactSet< T > & other) [default]
operator=() [2/2]
template<typename T >
ZoneCompactSet& v8::internal::ZoneCompactSet< T >::operator= (ZoneCompactSet< T > && other) [default]
operator[]()
template<typename T >
T v8::internal::ZoneCompactSet< T >::operator[] (size_t i) const [inline]
Definition at line 114 of file zone-compact-set.h.
{ return at(i); }
References v8::internal::ZoneCompactSet< T >::at().
remove()
template<typename T >
void v8::internal::ZoneCompactSet< T >::remove (T handle, Zone * zone) [inline]
Definition at line 201 of file zone-compact-set.h.
                                    {
    if (is_empty()) return;
    data_type* pointer = Traits::HandleToPointer(handle);
    if (is_singleton()) {
      if (singleton() == pointer) {
        data_ = EmptyValue();
      }
      return;
    }
    const List* current_list = list();
    auto found_it =
        std::lower_bound(current_list->begin(), current_list->end(), pointer);
    if (found_it == current_list->end() || *found_it != pointer) {
      // Not in the list.
      return;
    }
    // Otherwise, lower_bound returned the location of the value.
    // Drop back down to singleton mode if the size will drops to 1 -- this is
    // needed to ensure that comparisons are correct. We never have to drop down
    // from list to zero size.
    DCHECK_GE(current_list->size(), 2);
    if (current_list->size() == 2) {
      data_type* other_value;
      if (found_it == current_list->begin()) {
        other_value = current_list->at(1);
      } else {
        other_value = current_list->at(0);
      }
      data_ = PointerWithPayload(other_value, kSingletonTag);
      return;
    }
    // We need to copy the list to mutate it, so that trivial copies of the
    // data_ pointer don't observe changes to the list.
    List* new_list = NewList(current_list->size() - 1, zone);
    auto new_it = new_list->begin();
    new_it = std::copy(current_list->begin(), found_it, new_it);
    new_it = std::copy(found_it + 1, current_list->end(), new_it);
    DCHECK_EQ(new_it, new_list->end());
    DCHECK(std::is_sorted(new_list->begin(), new_list->end()));
    data_ = PointerWithPayload(new_list, kListTag);
  }
References v8::base::Vector< T >::at(), v8::base::Vector< T >::begin(), v8::internal::ZoneCompactSet< T >::data_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, v8::internal::ZoneCompactSet< T >::EmptyValue(), v8::base::Vector< T >::end(), v8::internal::handle(), v8::internal::ZoneCompactSet< T >::is_empty(), v8::internal::ZoneCompactSet< T >::is_singleton(), v8::internal::ZoneCompactSet< T >::kListTag, v8::internal::ZoneCompactSet< T >::kSingletonTag, v8::internal::ZoneCompactSet< T >::list(), v8::internal::ZoneCompactSet< T >::NewList(), v8::internal::ZoneCompactSet< T >::singleton(), and v8::base::Vector< T >::size().
Referenced by v8::internal::compiler::LoadElimination::ReduceTransitionElementsKind(), and v8::internal::compiler::LoadElimination::ReduceTransitionElementsKindOrCheckMap().
singleton()
template<typename T >
data_type* v8::internal::ZoneCompactSet< T >::singleton () const [inline], [private]
Definition at line 286 of file zone-compact-set.h.
                               {
    return static_cast<data_type*>(
        data_.GetPointerWithKnownPayload(kSingletonTag));
  }
References v8::internal::ZoneCompactSet< T >::data_, v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::GetPointerWithKnownPayload(), and v8::internal::ZoneCompactSet< T >::kSingletonTag.
Referenced by v8::internal::ZoneCompactSet< T >::at(), v8::internal::ZoneCompactSet< T >::contains(), v8::internal::ZoneCompactSet< T >::insert(), and v8::internal::ZoneCompactSet< T >::remove().
size()
template<typename T >
size_t v8::internal::ZoneCompactSet< T >::size () const [inline]
Definition at line 99 of file zone-compact-set.h.
                      {
    if (is_empty()) return 0;
    if (is_singleton()) return 1;
    return list()->size();
  }
References v8::internal::ZoneCompactSet< T >::is_empty(), v8::internal::ZoneCompactSet< T >::is_singleton(), v8::internal::ZoneCompactSet< T >::list(), and v8::base::Vector< T >::size().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildCompareMaps(), v8::internal::maglev::MaglevGraphBuilder::BuildTestUndetectable(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::CanInlineArrayIteratingBuiltin(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::CanInlineArrayIteratingBuiltin(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::CanInlineArrayResizingBuiltin(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::CompareMapAgainstMultipleMaps(), v8::internal::compiler::SimplifiedOperatorBuilder::CompareMaps(), v8::internal::maglev::MaglevGraphBuilder::gvn_hash_value(), v8::internal::compiler::SimplifiedOperatorBuilder::MapGuard(), v8::internal::compiler::LoadElimination::AliasStateInfo::MayAlias(), v8::internal::ZoneCompactSet< T >::NewList(), v8::internal::ZoneCompactSet< T >::const_iterator::operator++(), v8::internal::operator<<(), v8::internal::compiler::LoadElimination::AbstractMaps::Print(), v8::internal::compiler::turboshaft::PrintMapSet(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypePush(), v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), v8::internal::compiler::JSCallReducer::ReduceCollectionIteratorPrototypeNext(), v8::internal::compiler::LoadElimination::ReduceLoadField(), v8::internal::compiler::JSCallReducer::ReduceObjectGetPrototype(), v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeHasOwnProperty(), v8::internal::compiler::ElementAccessFeedback::Refine(), v8::internal::maglev::NodeInfo::SetPossibleMaps(), v8::internal::maglev::MaglevGraphBuilder::TryReduceArrayIteratingBuiltin(), v8::internal::ZoneCompactSet< T >::Union(), and v8::internal::ZoneCompactSet< T >::ZoneCompactSet().
Union()
template<typename T >
void v8::internal::ZoneCompactSet< T >::Union (ZoneCompactSet< T > const & other, Zone * zone) [inline]
Definition at line 157 of file zone-compact-set.h.
                                                         {
    for (size_t i = 0; i < other.size(); ++i) {
      insert(other.at(i), zone);
    }
  }
References v8::internal::ZoneCompactSet< T >::at(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::ZoneCompactSet< T >::insert(), and v8::internal::ZoneCompactSet< T >::size().
Referenced by v8::internal::maglev::NodeInfo::MergeWith().
Friends And Related Function Documentation
hash_value
template<typename T >
uintptr_t hash_value (ZoneCompactSet< T > const & set) [friend]
Definition at line 264 of file zone-compact-set.h.
                                                            {
    return set.data_.raw();
  }
operator!=
template<typename T >
bool operator!= (ZoneCompactSet< T > const & lhs, ZoneCompactSet< T > const & rhs) [friend]
Definition at line 259 of file zone-compact-set.h.
                                                       {
    return !(lhs == rhs);
  }
operator==
template<typename T >
bool operator== (ZoneCompactSet< T > const & lhs, ZoneCompactSet< T > const & rhs) [friend]
Definition at line 247 of file zone-compact-set.h.
                                                       {
    if (lhs.data_ == rhs.data_) return true;
    if (lhs.is_list() && rhs.is_list()) {
      List const* const lhs_list = lhs.list();
      List const* const rhs_list = rhs.list();
      return std::equal(lhs_list->begin(), lhs_list->end(), rhs_list->begin(),
                        rhs_list->end());
    }
    return false;
  }
Member Data Documentation
data_
template<typename T >
PointerWithPayload v8::internal::ZoneCompactSet< T >::data_ [private]
Definition at line 302 of file zone-compact-set.h.
Referenced by v8::internal::ZoneCompactSet< T >::at(), v8::internal::ZoneCompactSet< T >::clear(), v8::internal::ZoneCompactSet< T >::contains(), v8::internal::ZoneCompactSet< T >::insert(), v8::internal::ZoneCompactSet< T >::is_empty(), v8::internal::ZoneCompactSet< T >::is_list(), v8::internal::ZoneCompactSet< T >::is_singleton(), v8::internal::ZoneCompactSet< T >::list(), v8::internal::ZoneCompactSet< T >::remove(), v8::internal::ZoneCompactSet< T >::singleton(), and v8::internal::ZoneCompactSet< T >::ZoneCompactSet().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/zone/zone-compact-set.h