cppgc::internal::PlatformAwareObjectStartBitmap Class Reference
#include <object-start-bitmap.h>
Public Member Functions
template<AccessMode = AccessMode::kNonAtomic>
void SetBit (ConstAddress)
template<AccessMode = AccessMode::kNonAtomic>
void ClearBit (ConstAddress)
Static Private Member Functions
template<AccessMode >
static bool ShouldForceNonAtomic ()
Additional Inherited Members
Detailed Description
Definition at line 227 of file object-start-bitmap.h.
Member Function Documentation
ClearBit()
template<AccessMode mode>
void cppgc::internal::PlatformAwareObjectStartBitmap::ClearBit (ConstAddress header_address) [inline]
Definition at line 262 of file object-start-bitmap.h.
                                                                         {
  if (ShouldForceNonAtomic<mode>()) {
    ObjectStartBitmap::ClearBit<AccessMode::kNonAtomic>(header_address);
    return;
  }
  ObjectStartBitmap::ClearBit<mode>(header_address);
}
Referenced by cppgc::internal::anonymous_namespace{sweeper.cc}::SweepNormalPage().
SetBit()
template<AccessMode mode>
void cppgc::internal::PlatformAwareObjectStartBitmap::SetBit (ConstAddress header_address) [inline]
Definition at line 253 of file object-start-bitmap.h.
                                                                       {
  if (ShouldForceNonAtomic<mode>()) {
    ObjectStartBitmap::SetBit<AccessMode::kNonAtomic>(header_address);
    return;
  }
  ObjectStartBitmap::SetBit<mode>(header_address);
}
Referenced by cppgc::internal::anonymous_namespace{object-allocator.cc}::AddToFreeList(), cppgc::internal::ObjectAllocator::AllocateObjectOnSpace(), and cppgc::internal::anonymous_namespace{explicit-management.cc}::Shrink().
ShouldForceNonAtomic()
template<AccessMode mode>
bool cppgc::internal::PlatformAwareObjectStartBitmap::ShouldForceNonAtomic [static], [private]
Definition at line 242 of file object-start-bitmap.h.
                                                          {
#if defined(V8_HOST_ARCH_ARM)
  // Use non-atomic accesses on ARMv7 when marking is not active.
  if (mode == AccessMode::kAtomic) {
    if (V8_LIKELY(!WriteBarrier::IsEnabled())) return true;
  }
#endif // defined(V8_HOST_ARCH_ARM)
  return false;
}
References cppgc::internal::WriteBarrier::IsEnabled(), cppgc::internal::kAtomic, mode(), and V8_LIKELY.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc/object-start-bitmap.h