v8::internal::IncrementalMarkingJob Class Reference
#include <incremental-marking-job.h>
Classes
class Task
Public Member Functions
IncrementalMarkingJob (Heap *heap)
IncrementalMarkingJob (const IncrementalMarkingJob &)=delete
IncrementalMarkingJob & operator= (const IncrementalMarkingJob &)=delete
void ScheduleTask (TaskPriority priority=TaskPriority::kUserBlocking)
std::optional< v8::base::TimeDelta > AverageTimeToTask () const
std::optional< v8::base::TimeDelta > CurrentTimeToTask () const
Private Attributes
Heap *const heap_
const std::shared_ptr< v8::TaskRunner > user_blocking_task_runner_
const std::shared_ptr< v8::TaskRunner > user_visible_task_runner_
base::Mutex mutex_
v8::base::TimeTicks scheduled_time_
bool pending_task_ = false
Detailed Description
Definition at line 22 of file incremental-marking-job.h.
Constructor & Destructor Documentation
IncrementalMarkingJob() [1/2]
v8::internal::IncrementalMarkingJob::IncrementalMarkingJob (Heap * heap) [explicit]
Definition at line 46 of file incremental-marking-job.cc.
    : heap_(heap),
      user_blocking_task_runner_(
          heap->GetForegroundTaskRunner(TaskPriority::kUserBlocking)),
      user_visible_task_runner_(
          heap->GetForegroundTaskRunner(TaskPriority::kUserVisible)) {
  CHECK(v8_flags.incremental_marking_task);
}
References CHECK, v8::kUserBlocking, v8::kUserVisible, and v8::internal::v8_flags.
IncrementalMarkingJob() [2/2]
v8::internal::IncrementalMarkingJob::IncrementalMarkingJob (const IncrementalMarkingJob &) [delete]
Member Function Documentation
AverageTimeToTask()
std::optional< v8::base::TimeDelta > v8::internal::IncrementalMarkingJob::AverageTimeToTask () const
Definition at line 157 of file incremental-marking-job.cc.
          {
  return heap_->tracer()->AverageTimeToIncrementalMarkingTask();
}
References v8::internal::GCTracer::AverageTimeToIncrementalMarkingTask(), heap_, and v8::internal::Heap::tracer().
Referenced by v8::internal::IncrementalMarking::TryInitializeTaskTimeout().
CurrentTimeToTask()
std::optional< base::TimeDelta > v8::internal::IncrementalMarkingJob::CurrentTimeToTask () const
Definition at line 146 of file incremental-marking-job.cc.
          {
  std::optional<base::TimeDelta> current_time_to_task;
  if (pending_task_) {
    const auto now = base::TimeTicks::Now();
    DCHECK_GE(now, scheduled_time_);
    current_time_to_task.emplace(now - scheduled_time_);
  }
  return current_time_to_task;
}
References DCHECK_GE, v8::base::TimeTicks::Now(), pending_task_, and scheduled_time_.
Referenced by v8::internal::IncrementalMarking::TryInitializeTaskTimeout().
operator=()
IncrementalMarkingJob& v8::internal::IncrementalMarkingJob::operator= (const IncrementalMarkingJob &) [delete]
ScheduleTask()
void v8::internal::IncrementalMarkingJob::ScheduleTask (TaskPriority priority = TaskPriority::kUserBlocking)
Definition at line 55 of file incremental-marking-job.cc.
                                                              {
  base::MutexGuard guard(&mutex_);
  if (pending_task_ || heap_->IsTearingDown()) {
    return;
  }
  IncrementalMarking* incremental_marking = heap_->incremental_marking();
  v8::TaskRunner* task_runner =
      v8_flags.incremental_marking_start_user_visible &&
              incremental_marking->IsStopped() &&
              (priority != TaskPriority::kUserBlocking)
          ? user_visible_task_runner_.get()
          : user_blocking_task_runner_.get();
  const bool non_nestable_tasks_enabled =
      task_runner->NonNestableTasksEnabled();
  auto task = std::make_unique<Task>(heap_->isolate(), this,
                                     non_nestable_tasks_enabled
                                         ? StackState::kNoHeapPointers
                                         : StackState::kMayContainHeapPointers);
  if (non_nestable_tasks_enabled) {
    task_runner->PostNonNestableTask(std::move(task));
  } else {
    task_runner->PostTask(std::move(task));
  }
  pending_task_ = true;
  scheduled_time_ = v8::base::TimeTicks::Now();
  if (V8_UNLIKELY(v8_flags.trace_incremental_marking)) {
    heap_->isolate()->PrintWithTimestamp(
        "[IncrementalMarking] Job: Schedule\n");
  }
}
References heap_, v8::internal::Heap::incremental_marking(), v8::internal::Heap::isolate(), v8::internal::IncrementalMarking::IsStopped(), v8::internal::Heap::IsTearingDown(), v8::kUserBlocking, mutex_, v8::TaskRunner::NonNestableTasksEnabled(), v8::base::TimeTicks::Now(), pending_task_, v8::TaskRunner::PostNonNestableTask(), v8::TaskRunner::PostTask(), scheduled_time_, user_blocking_task_runner_, user_visible_task_runner_, v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::internal::IncrementalMarkingJob::Task::RunInternal(), v8::internal::IncrementalMarking::ShouldWaitForTask(), and v8::internal::IncrementalMarking::StartMarkingMajor().
Member Data Documentation
heap_
Heap* const v8::internal::IncrementalMarkingJob::heap_ [private]
Definition at line 43 of file incremental-marking-job.h.
Referenced by AverageTimeToTask(), v8::internal::IncrementalMarkingJob::Task::RunInternal(), and ScheduleTask().
mutex_
base::Mutex v8::internal::IncrementalMarkingJob::mutex_ [mutable], [private]
Definition at line 46 of file incremental-marking-job.h.
Referenced by v8::internal::IncrementalMarkingJob::Task::RunInternal(), and ScheduleTask().
pending_task_
bool v8::internal::IncrementalMarkingJob::pending_task_ = false [private]
Definition at line 48 of file incremental-marking-job.h.
Referenced by CurrentTimeToTask(), v8::internal::IncrementalMarkingJob::Task::RunInternal(), and ScheduleTask().
scheduled_time_
v8::base::TimeTicks v8::internal::IncrementalMarkingJob::scheduled_time_ [private]
Definition at line 47 of file incremental-marking-job.h.
Referenced by CurrentTimeToTask(), v8::internal::IncrementalMarkingJob::Task::RunInternal(), and ScheduleTask().
user_blocking_task_runner_
const std::shared_ptr<v8::TaskRunner> v8::internal::IncrementalMarkingJob::user_blocking_task_runner_ [private]
Definition at line 44 of file incremental-marking-job.h.
Referenced by ScheduleTask().
user_visible_task_runner_
const std::shared_ptr<v8::TaskRunner> v8::internal::IncrementalMarkingJob::user_visible_task_runner_ [private]
Definition at line 45 of file incremental-marking-job.h.
Referenced by ScheduleTask().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/incremental-marking-job.h
/mnt/V8SourceCode/src/heap/incremental-marking-job.cc