v8::internal::AstNodeFactory Class Reference
#include <ast.h>
Public Member Functions
AstNodeFactory (AstValueFactory *ast_value_factory, Zone *zone)
AstNodeFactory * ast_node_factory ()
AstValueFactory * ast_value_factory () const
VariableDeclaration * NewVariableDeclaration (int pos)
NestedVariableDeclaration * NewNestedVariableDeclaration (Scope *scope, int pos)
FunctionDeclaration * NewFunctionDeclaration (FunctionLiteral *fun, int pos)
Block * NewBlock (int capacity, bool ignore_completion_value)
Block * NewBlock (bool ignore_completion_value, bool is_breakable)
Block * NewBlock (bool ignore_completion_value, const ScopedPtrList< Statement > &statements)
Block * NewParameterInitializationBlock (const ScopedPtrList< Statement > &statements)
SwitchStatement * NewSwitchStatement (Expression *tag, int pos)
ForEachStatement * NewForEachStatement (ForEachStatement::VisitMode visit_mode, int pos)
ForOfStatement * NewForOfStatement (int pos, IteratorType type)
ExpressionStatement * NewExpressionStatement (Expression *expression, int pos)
ContinueStatement * NewContinueStatement (IterationStatement *target, int pos)
BreakStatement * NewBreakStatement (BreakableStatement *target, int pos)
ReturnStatement * NewReturnStatement (Expression *expression, int pos, int end_position=ReturnStatement::kFunctionLiteralReturnPosition)
ReturnStatement * NewAsyncReturnStatement (Expression *expression, int pos, int end_position=ReturnStatement::kFunctionLiteralReturnPosition)
ReturnStatement * NewSyntheticAsyncReturnStatement (Expression *expression, int pos, int end_position=ReturnStatement::kFunctionLiteralReturnPosition)
WithStatement * NewWithStatement (Scope *scope, Expression *expression, Statement *statement, int pos)
IfStatement * NewIfStatement (Expression *condition, Statement *then_statement, Statement *else_statement, int pos)
TryCatchStatement * NewTryCatchStatement (Block *try_block, Scope *scope, Block *catch_block, int pos)
TryCatchStatement * NewTryCatchStatementForReThrow (Block *try_block, Scope *scope, Block *catch_block, int pos)
TryCatchStatement * NewTryCatchStatementForAsyncAwait (Block *try_block, Scope *scope, Block *catch_block, int pos)
TryCatchStatement * NewTryCatchStatementForReplAsyncAwait (Block *try_block, Scope *scope, Block *catch_block, int pos)
TryFinallyStatement * NewTryFinallyStatement (Block *try_block, Block *finally_block, int pos)
DebuggerStatement * NewDebuggerStatement (int pos)
class EmptyStatement * EmptyStatement ()
class ThisExpression * ThisExpression ()
class ThisExpression * NewThisExpression (int pos)
class FailureExpression * FailureExpression ()
SloppyBlockFunctionStatement * NewSloppyBlockFunctionStatement (int pos, Variable *var, Token::Value init)
CaseClause * NewCaseClause (Expression *label, const ScopedPtrList< Statement > &statements)
Literal * NewStringLiteral (const AstRawString *string, int pos)
Literal * NewConsStringLiteral (AstConsString *string, int pos)
Literal * NewNumberLiteral (double number, int pos)
Literal * NewSmiLiteral (int number, int pos)
Literal * NewBigIntLiteral (AstBigInt bigint, int pos)
Literal * NewBooleanLiteral (bool b, int pos)
Literal * NewNullLiteral (int pos)
Literal * NewUndefinedLiteral (int pos)
Literal * NewTheHoleLiteral ()
ObjectLiteral * NewObjectLiteral (const ScopedPtrList< ObjectLiteral::Property > &properties, uint32_t boilerplate_properties, int pos, bool has_rest_property, Variable *home_object=nullptr)
ObjectLiteral::Property * NewObjectLiteralProperty (Expression *key, Expression *value, ObjectLiteralProperty::Kind kind, bool is_computed_name)
ObjectLiteral::Property * NewObjectLiteralProperty (Expression *key, Expression *value, bool is_computed_name)
RegExpLiteral * NewRegExpLiteral (const AstRawString *pattern, int flags, int pos)
ArrayLiteral * NewArrayLiteral (const ScopedPtrList< Expression > &values, int pos)
ArrayLiteral * NewArrayLiteral (const ScopedPtrList< Expression > &values, int first_spread_index, int pos)
VariableProxy * NewVariableProxy (Variable *var, int start_position=kNoSourcePosition)
VariableProxy * NewVariableProxy (const AstRawString *name, VariableKind variable_kind, int start_position=kNoSourcePosition)
VariableProxy * CopyVariableProxy (VariableProxy *proxy)
Variable * CopyVariable (Variable *variable)
OptionalChain * NewOptionalChain (Expression *expression)
Property * NewProperty (Expression *obj, Expression *key, int pos, bool optional_chain=false)
Call * NewCall (Expression *expression, const ScopedPtrList< Expression > &arguments, int pos, bool has_spread, int eval_scope_info_index=0, bool optional_chain=false)
SuperCallForwardArgs * NewSuperCallForwardArgs (SuperCallReference *expression, int pos)
Call * NewTaggedTemplate (Expression *expression, const ScopedPtrList< Expression > &arguments, int pos)
CallNew * NewCallNew (Expression *expression, const ScopedPtrList< Expression > &arguments, int pos, bool has_spread)
CallRuntime * NewCallRuntime (Runtime::FunctionId id, const ScopedPtrList< Expression > &arguments, int pos)
CallRuntime * NewCallRuntime (const Runtime::Function *function, const ScopedPtrList< Expression > &arguments, int pos)
UnaryOperation * NewUnaryOperation (Token::Value op, Expression *expression, int pos)
BinaryOperation * NewBinaryOperation (Token::Value op, Expression *left, Expression *right, int pos)
NaryOperation * NewNaryOperation (Token::Value op, Expression *first, size_t initial_subsequent_size)
CountOperation * NewCountOperation (Token::Value op, bool is_prefix, Expression *expr, int pos)
CompareOperation * NewCompareOperation (Token::Value op, Expression *left, Expression *right, int pos)
Spread * NewSpread (Expression *expression, int pos, int expr_pos)
ConditionalChain * NewConditionalChain (size_t initial_size, int pos)
Conditional * NewConditional (Expression *condition, Expression *then_expression, Expression *else_expression, int position)
Assignment * NewAssignment (Token::Value op, Expression *target, Expression *value, int pos)
Suspend * NewYield (Expression *expression, int pos, Suspend::OnAbruptResume on_abrupt_resume)
YieldStar * NewYieldStar (Expression *expression, int pos)
Await * NewAwait (Expression *expression, int pos)
Throw * NewThrow (Expression *exception, int pos)
FunctionLiteral * NewFunctionLiteral (const AstRawString *name, DeclarationScope *scope, const ScopedPtrList< Statement > &body, int expected_property_count, int parameter_count, int function_length, FunctionLiteral::ParameterFlag has_duplicate_parameters, FunctionSyntaxKind function_syntax_kind, FunctionLiteral::EagerCompileHint eager_compile_hint, int position, bool has_braces, int function_literal_id, ProducedPreparseData *produced_preparse_data=nullptr)
FunctionLiteral * NewScriptOrEvalFunctionLiteral (DeclarationScope *scope, const ScopedPtrList< Statement > &body, int expected_property_count, int parameter_count)
AutoAccessorInfo * NewAutoAccessorInfo (FunctionLiteral *generated_getter, FunctionLiteral *generated_setter, VariableProxy *accessor_storage_name_proxy)
ClassLiteral::Property * NewClassLiteralProperty (Expression *key, Expression *value, ClassLiteralProperty::Kind kind, bool is_static, bool is_computed_name, bool is_private)
ClassLiteral::Property * NewClassLiteralProperty (Expression *key, Expression *value, AutoAccessorInfo *auto_accessor_info, bool is_static, bool is_computed_name, bool is_private)
ClassLiteral::StaticElement * NewClassLiteralStaticElement (ClassLiteral::Property *property)
ClassLiteral::StaticElement * NewClassLiteralStaticElement (Block *static_block)
ClassLiteral * NewClassLiteral (ClassScope *scope, Expression *extends, FunctionLiteral *constructor, ZonePtrList< ClassLiteral::Property > *public_members, ZonePtrList< ClassLiteral::Property > *private_members, FunctionLiteral *static_initializer, FunctionLiteral *instance_members_initializer_function, int start_position, int end_position, bool has_static_computed_names, bool is_anonymous, Variable *home_object, Variable *static_home_object)
NativeFunctionLiteral * NewNativeFunctionLiteral (const AstRawString *name, v8::Extension *extension, int pos)
SuperPropertyReference * NewSuperPropertyReference (VariableProxy *home_object_var, int pos)
SuperCallReference * NewSuperCallReference (VariableProxy *new_target_var, VariableProxy *this_function_var, int pos)
EmptyParentheses * NewEmptyParentheses (int pos)
GetTemplateObject * NewGetTemplateObject (const ZonePtrList< const AstRawString > *cooked_strings, const ZonePtrList< const AstRawString > *raw_strings, int pos)
TemplateLiteral * NewTemplateLiteral (const ZonePtrList< const AstRawString > *string_parts, const ZonePtrList< Expression > *substitutions, int pos)
ImportCallExpression * NewImportCallExpression (Expression *specifier, ModuleImportPhase phase, int pos)
ImportCallExpression * NewImportCallExpression (Expression *specifier, ModuleImportPhase phase, Expression *import_options, int pos)
InitializeClassMembersStatement * NewInitializeClassMembersStatement (ZonePtrList< ClassLiteral::Property > *args, int pos)
InitializeClassStaticElementsStatement * NewInitializeClassStaticElementsStatement (ZonePtrList< ClassLiteral::StaticElement > *args, int pos)
AutoAccessorGetterBody * NewAutoAccessorGetterBody (VariableProxy *name_proxy, int pos)
AutoAccessorSetterBody * NewAutoAccessorSetterBody (VariableProxy *name_proxy, int pos)
Zone * zone () const
Private Attributes
Zone * zone_
AstValueFactory * ast_value_factory_
class EmptyStatement * empty_statement_
class ThisExpression * this_expression_
class FailureExpression * failure_expression_
Detailed Description
Definition at line 3027 of file ast.h.
Constructor & Destructor Documentation
AstNodeFactory()
v8::internal::AstNodeFactory::AstNodeFactory (AstValueFactory * ast_value_factory, Zone * zone) [inline]
Definition at line 3029 of file ast.h.
      : zone_(zone),
        ast_value_factory_(ast_value_factory),
        empty_statement_(zone->New<class EmptyStatement>()),
        this_expression_(zone->New<class ThisExpression>(kNoSourcePosition)),
        failure_expression_(zone->New<class FailureExpression>()) {}
Member Function Documentation
ast_node_factory()
AstNodeFactory* v8::internal::AstNodeFactory::ast_node_factory () [inline]
Definition at line 3036 of file ast.h.
{ return this; }
ast_value_factory()
AstValueFactory* v8::internal::AstNodeFactory::ast_value_factory () const [inline]
Definition at line 3037 of file ast.h.
{ return ast_value_factory_; }
References ast_value_factory_.
Referenced by v8::internal::DeclarationScope::AnalyzePartially().
CopyVariable()
Variable* v8::internal::AstNodeFactory::CopyVariable (Variable * variable) [inline]
Definition at line 3315 of file ast.h.
                                             {
    return zone_->New<Variable>(variable);
  }
References v8::internal::Zone::New(), and zone_.
Referenced by v8::internal::DeclarationScope::AnalyzePartially().
CopyVariableProxy()
VariableProxy* v8::internal::AstNodeFactory::CopyVariableProxy (VariableProxy * proxy) [inline]
Definition at line 3311 of file ast.h.
                                                         {
    return zone_->New<VariableProxy>(proxy);
  }
References v8::internal::Zone::New(), and zone_.
Referenced by v8::internal::Scope::AnalyzePartially(), and v8::internal::ClassScope::MigrateUnresolvedPrivateNameTail().
EmptyStatement()
class EmptyStatement* v8::internal::AstNodeFactory::EmptyStatement () [inline]
Definition at line 3190 of file ast.h.
                                         {
    return empty_statement_;
  }
References empty_statement_.
Referenced by NewSloppyBlockFunctionStatement().
FailureExpression()
class FailureExpression* v8::internal::AstNodeFactory::FailureExpression () [inline]
Definition at line 3210 of file ast.h.
                                               {
    return failure_expression_;
  }
References failure_expression_.
NewArrayLiteral() [1/2]
ArrayLiteral* v8::internal::AstNodeFactory::NewArrayLiteral (const ScopedPtrList< Expression > & values, int first_spread_index, int pos) [inline]
Definition at line 3293 of file ast.h.
                                                                 {
    return zone_->New<ArrayLiteral>(zone_, values, first_spread_index, pos);
  }
References v8::internal::Zone::New(), and zone_.
NewArrayLiteral() [2/2]
ArrayLiteral* v8::internal::AstNodeFactory::NewArrayLiteral (const ScopedPtrList< Expression > & values, int pos) [inline]
Definition at line 3288 of file ast.h.
                                         {
    return zone_->New<ArrayLiteral>(zone_, values, -1, pos);
  }
References v8::internal::Zone::New(), and zone_.
NewAssignment()
Assignment* v8::internal::AstNodeFactory::NewAssignment (Token::Value op, Expression * target, Expression * value, int pos) [inline]
Definition at line 3415 of file ast.h.
                                     {
    DCHECK(Token::IsAssignmentOp(op));
    DCHECK_NOT_NULL(target);
    DCHECK_NOT_NULL(value);
    if (op != Token::kInit && target->IsVariableProxy()) {
      target->AsVariableProxy()->set_is_assigned();
    }
    if (op == Token::kAssign || op == Token::kInit) {
      return zone_->New<Assignment>(AstNode::kAssignment, op, target, value,
                                    pos);
    } else {
      return zone_->New<CompoundAssignment>(
          op, target, value, pos,
          NewBinaryOperation(Token::BinaryOpForAssignment(op), target, value,
                             pos + 1));
    }
  }
References v8::internal::Token::BinaryOpForAssignment(), v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::Token::IsAssignmentOp(), v8::internal::Zone::New(), NewBinaryOperation(), v8::internal::value, and zone_.
Referenced by v8::internal::DeclarationScope::HoistSloppyBlockFunctions(), and v8::internal::Processor::SetResult().
NewAsyncReturnStatement()
ReturnStatement* v8::internal::AstNodeFactory::NewAsyncReturnStatement (Expression * expression, int pos, int end_position = ReturnStatement::kFunctionLiteralReturnPosition) [inline]
Definition at line 3124 of file ast.h.
                                                                        {
    return zone_->New<ReturnStatement>(
        expression, ReturnStatement::kAsyncReturn, pos, end_position);
  }
References v8::internal::ReturnStatement::kAsyncReturn, v8::internal::Zone::New(), and zone_.
NewAutoAccessorGetterBody()
AutoAccessorGetterBody* v8::internal::AstNodeFactory::NewAutoAccessorGetterBody (VariableProxy * name_proxy, int pos) [inline]
Definition at line 3594 of file ast.h.
                                                             {
    return zone_->New<AutoAccessorGetterBody>(name_proxy, pos);
  }
References v8::internal::Zone::New(), and zone_.
NewAutoAccessorInfo()
AutoAccessorInfo* v8::internal::AstNodeFactory::NewAutoAccessorInfo (FunctionLiteral * generated_getter, FunctionLiteral * generated_setter, VariableProxy * accessor_storage_name_proxy) [inline]
Definition at line 3489 of file ast.h.
                                                  {
    return zone_->New<AutoAccessorInfo>(generated_getter, generated_setter,
                                        accessor_storage_name_proxy);
  }
References v8::internal::Zone::New(), and zone_.
NewAutoAccessorSetterBody()
AutoAccessorSetterBody* v8::internal::AstNodeFactory::NewAutoAccessorSetterBody (VariableProxy * name_proxy, int pos) [inline]
Definition at line 3599 of file ast.h.
                                                             {
    return zone_->New<AutoAccessorSetterBody>(name_proxy, pos);
  }
References v8::internal::Zone::New(), and zone_.
NewAwait()
Await* v8::internal::AstNodeFactory::NewAwait (Expression * expression, int pos) [inline]
Definition at line 3448 of file ast.h.
                                                   {
    if (!expression) expression = NewUndefinedLiteral(pos);
    return zone_->New<Await>(expression, pos);
  }
References v8::internal::Zone::New(), NewUndefinedLiteral(), and zone_.
NewBigIntLiteral()
Literal* v8::internal::AstNodeFactory::NewBigIntLiteral (AstBigInt bigint, int pos) [inline]
Definition at line 3241 of file ast.h.
                                                       {
    return zone_->New<Literal>(bigint, pos);
  }
References v8::internal::Zone::New(), and zone_.
NewBinaryOperation()
BinaryOperation* v8::internal::AstNodeFactory::NewBinaryOperation (Token::Value op, Expression * left, Expression * right, int pos) [inline]
Definition at line 3373 of file ast.h.
                                               {
    return zone_->New<BinaryOperation>(op, left, right, pos);
  }
References v8::internal::Zone::New(), and zone_.
Referenced by NewAssignment().
NewBlock() [1/3]
Block* v8::internal::AstNodeFactory::NewBlock (bool ignore_completion_value, bool is_breakable) [inline]
Definition at line 3057 of file ast.h.
                                                                   {
    return zone_->New<Block>(ignore_completion_value, is_breakable, false);
  }
References v8::internal::Zone::New(), and zone_.
NewBlock() [2/3]
Block* v8::internal::AstNodeFactory::NewBlock (bool ignore_completion_value, const ScopedPtrList< Statement > & statements) [inline]
Definition at line 3061 of file ast.h.
                                                              {
    Block* result = NewBlock(ignore_completion_value, false);
    result->InitializeStatements(statements, zone_);
    return result;
  }
References NewBlock(), v8::base::internal::result, and zone_.
NewBlock() [3/3]
Block* v8::internal::AstNodeFactory::NewBlock (int capacity, bool ignore_completion_value) [inline]
Definition at line 3052 of file ast.h.
                                                              {
    return zone_->New<Block>(zone_, capacity, ignore_completion_value, false,
                             false);
  }
References v8::internal::Zone::New(), and zone_.
Referenced by v8::internal::Processor::AssignUndefinedBefore(), and NewBlock().
NewBooleanLiteral()
Literal* v8::internal::AstNodeFactory::NewBooleanLiteral (bool b, int pos) [inline]
Definition at line 3245 of file ast.h.
                                              {
    return zone_->New<Literal>(b, pos);
  }
References v8::internal::Zone::New(), and zone_.
NewBreakStatement()
BreakStatement* v8::internal::AstNodeFactory::NewBreakStatement (BreakableStatement * target, int pos) [inline]
Definition at line 3113 of file ast.h.
                                                                         {
    return zone_->New<BreakStatement>(target, pos);
  }
References v8::internal::Zone::New(), and zone_.
NewCall()
Call* v8::internal::AstNodeFactory::NewCall (Expression * expression, const ScopedPtrList< Expression > & arguments, int pos, bool has_spread, int eval_scope_info_index = 0, bool optional_chain = false) [inline]
Definition at line 3328 of file ast.h.
                                             {
    DCHECK_IMPLIES(eval_scope_info_index > 0, !optional_chain);
    return zone_->New<Call>(zone_, expression, arguments, pos, has_spread,
                            eval_scope_info_index, optional_chain);
  }
References DCHECK_IMPLIES, v8::internal::Zone::New(), and zone_.
NewCallNew()
CallNew* v8::internal::AstNodeFactory::NewCallNew (Expression * expression, const ScopedPtrList< Expression > & arguments, int pos, bool has_spread) [inline]
Definition at line 3348 of file ast.h.
                                       {
    return zone_->New<CallNew>(zone_, expression, arguments, pos, has_spread);
  }
References v8::internal::Zone::New(), and zone_.
NewCallRuntime() [1/2]
CallRuntime* v8::internal::AstNodeFactory::NewCallRuntime (const Runtime::Function * function, const ScopedPtrList< Expression > & arguments, int pos) [inline]
Definition at line 3361 of file ast.h.
                                       {
    return zone_->New<CallRuntime>(zone_, function, arguments, pos);
  }
References v8::internal::Zone::New(), and zone_.
NewCallRuntime() [2/2]
CallRuntime* v8::internal::AstNodeFactory::NewCallRuntime (Runtime::FunctionId id, const ScopedPtrList< Expression > & arguments, int pos) [inline]
Definition at line 3354 of file ast.h.
                                       {
    return zone_->New<CallRuntime>(zone_, Runtime::FunctionForId(id), arguments,
                                   pos);
  }
References v8::internal::Runtime::FunctionForId(), v8::internal::Zone::New(), and zone_.
NewCaseClause()
CaseClause* v8::internal::AstNodeFactory::NewCaseClause (Expression * label, const ScopedPtrList< Statement > & statements) [inline]
Definition at line 3220 of file ast.h.
                                                                        {
    return zone_->New<CaseClause>(zone_, label, statements);
  }
References v8::internal::Zone::New(), and zone_.
NewClassLiteral()
ClassLiteral* v8::internal::AstNodeFactory::NewClassLiteral (ClassScope * scope, Expression * extends, FunctionLiteral * constructor, ZonePtrList< ClassLiteral::Property > * public_members, ZonePtrList< ClassLiteral::Property > * private_members, FunctionLiteral * static_initializer, FunctionLiteral * instance_members_initializer_function, int start_position, int end_position, bool has_static_computed_names, bool is_anonymous, Variable * home_object, Variable * static_home_object) [inline]
Definition at line 3520 of file ast.h.
                                                                              {
    return zone_->New<ClassLiteral>(
        scope, extends, constructor, public_members, private_members,
        static_initializer, instance_members_initializer_function,
        start_position, end_position, has_static_computed_names, is_anonymous,
        home_object, static_home_object);
  }
References v8::internal::Zone::New(), and zone_.
NewClassLiteralProperty() [1/2]
ClassLiteral::Property* v8::internal::AstNodeFactory::NewClassLiteralProperty (Expression * key, Expression * value, AutoAccessorInfo * auto_accessor_info, bool is_static, bool is_computed_name, bool is_private) [inline]
Definition at line 3502 of file ast.h.
                                                              {
    return zone_->New<ClassLiteral::Property>(key, value, auto_accessor_info,
                                              is_static, is_computed_name,
                                              is_private);
  }
References v8::internal::key, v8::internal::Zone::New(), v8::internal::value, and zone_.
NewClassLiteralProperty() [2/2]
ClassLiteral::Property* v8::internal::AstNodeFactory::NewClassLiteralProperty (Expression * key, Expression * value, ClassLiteralProperty::Kind kind, bool is_static, bool is_computed_name, bool is_private) [inline]
Definition at line 3496 of file ast.h.
                                                              {
    return zone_->New<ClassLiteral::Property>(key, value, kind, is_static,
                                              is_computed_name, is_private);
  }
References v8::internal::key, v8::internal::Zone::New(), v8::internal::value, and zone_.
NewClassLiteralStaticElement() [1/2]
ClassLiteral::StaticElement* v8::internal::AstNodeFactory::NewClassLiteralStaticElement (Block * static_block) [inline]
Definition at line 3515 of file ast.h.
                           {
    return zone_->New<ClassLiteral::StaticElement>(static_block);
  }
References v8::internal::Zone::New(), and zone_.
NewClassLiteralStaticElement() [2/2]
ClassLiteral::StaticElement* v8::internal::AstNodeFactory::NewClassLiteralStaticElement (ClassLiteral::Property * property) [inline]
Definition at line 3510 of file ast.h.
                                      {
    return zone_->New<ClassLiteral::StaticElement>(property);
  }
References v8::internal::Zone::New(), and zone_.
NewCompareOperation()
CompareOperation* v8::internal::AstNodeFactory::NewCompareOperation (Token::Value op, Expression * left, Expression * right, int pos) [inline]
Definition at line 3392 of file ast.h.
                                                 {
    return zone_->New<CompareOperation>(op, left, right, pos);
  }
References v8::internal::Zone::New(), and zone_.
NewConditional()
Conditional* v8::internal::AstNodeFactory::NewConditional (Expression * condition, Expression * then_expression, Expression * else_expression, int position) [inline]
Definition at line 3407 of file ast.h.
                                            {
    return zone_->New<Conditional>(condition, then_expression, else_expression,
                                   position);
  }
References v8::internal::Zone::New(), and zone_.
NewConditionalChain()
ConditionalChain* v8::internal::AstNodeFactory::NewConditionalChain (size_t initial_size, int pos) [inline]
Definition at line 3403 of file ast.h.
                                                                      {
    return zone_->New<ConditionalChain>(zone_, initial_size, pos);
  }
References v8::internal::Zone::New(), and zone_.
NewConsStringLiteral()
Literal* v8::internal::AstNodeFactory::NewConsStringLiteral (AstConsString * string, int pos) [inline]
Definition at line 3230 of file ast.h.
                                                                {
    DCHECK_NOT_NULL(string);
    return zone_->New<Literal>(string, pos);
  }
References DCHECK_NOT_NULL, v8::internal::Zone::New(), v8::internal::string, and zone_.
NewContinueStatement()
ContinueStatement* v8::internal::AstNodeFactory::NewContinueStatement (IterationStatement * target, int pos) [inline]
Definition at line 3109 of file ast.h.
                                                                               {
    return zone_->New<ContinueStatement>(target, pos);
  }
References v8::internal::Zone::New(), and zone_.
NewCountOperation()
CountOperation* v8::internal::AstNodeFactory::NewCountOperation (Token::Value op, bool is_prefix, Expression * expr, int pos) [inline]
Definition at line 3385 of file ast.h.
                                             {
    return zone_->New<CountOperation>(op, is_prefix, expr, pos);
  }
References v8::internal::Zone::New(), and zone_.
NewDebuggerStatement()
DebuggerStatement* v8::internal::AstNodeFactory::NewDebuggerStatement (int pos) [inline]
Definition at line 3186 of file ast.h.
                                                   {
    return zone_->New<DebuggerStatement>(pos);
  }
References v8::internal::Zone::New(), and zone_.
NewEmptyParentheses()
EmptyParentheses* v8::internal::AstNodeFactory::NewEmptyParentheses (int pos) [inline]
Definition at line 3553 of file ast.h.
                                                 {
    return zone_->New<EmptyParentheses>(pos);
  }
References v8::internal::Zone::New(), and zone_.
NewExpressionStatement()
ExpressionStatement* v8::internal::AstNodeFactory::NewExpressionStatement (Expression * expression, int pos) [inline]
Definition at line 3105 of file ast.h.
                                                                               {
    return zone_->New<ExpressionStatement>(expression, pos);
  }
References v8::internal::Zone::New(), and zone_.
Referenced by v8::internal::DeclarationScope::HoistSloppyBlockFunctions().
NewForEachStatement()
ForEachStatement* v8::internal::AstNodeFactory::NewForEachStatement (ForEachStatement::VisitMode visit_mode, int pos) [inline]
Definition at line 3088 of file ast.h.
                                                 {
    switch (visit_mode) {
      case ForEachStatement::ENUMERATE: {
        return zone_->New<ForInStatement>(pos);
      }
      case ForEachStatement::ITERATE: {
        return zone_->New<ForOfStatement>(pos, IteratorType::kNormal);
      }
    }
    UNREACHABLE();
  }
References v8::internal::ForEachStatement::ENUMERATE, v8::internal::ForEachStatement::ITERATE, v8::internal::kNormal, v8::internal::Zone::New(), v8::internal::UNREACHABLE(), and zone_.
NewForOfStatement()
ForOfStatement* v8::internal::AstNodeFactory::NewForOfStatement (int pos, IteratorType type) [inline]
Definition at line 3101 of file ast.h.
                                                                {
    return zone_->New<ForOfStatement>(pos, type);
  }
References v8::internal::Zone::New(), v8::internal::tracing::type, and zone_.
NewFunctionDeclaration()
FunctionDeclaration* v8::internal::AstNodeFactory::NewFunctionDeclaration (FunctionLiteral * fun, int pos) [inline]
Definition at line 3048 of file ast.h.
                                                                             {
    return zone_->New<FunctionDeclaration>(fun, pos);
  }
References v8::internal::Zone::New(), and zone_.
NewFunctionLiteral()
FunctionLiteral* v8::internal::AstNodeFactory::NewFunctionLiteral (const AstRawString * name, DeclarationScope * scope, const ScopedPtrList< Statement > & body, int expected_property_count, int parameter_count, int function_length, FunctionLiteral::ParameterFlag has_duplicate_parameters, FunctionSyntaxKind function_syntax_kind, FunctionLiteral::EagerCompileHint eager_compile_hint, int position, bool has_braces, int function_literal_id, ProducedPreparseData * produced_preparse_data = nullptr) [inline]
Definition at line 3457 of file ast.h.
                                                              {
    return zone_->New<FunctionLiteral>(
        zone_, name ? ast_value_factory_->NewConsString(name) : nullptr,
        ast_value_factory_, scope, body, expected_property_count,
        parameter_count, function_length, function_syntax_kind,
        has_duplicate_parameters, eager_compile_hint, position, has_braces,
        function_literal_id, produced_preparse_data);
  }
References ast_value_factory_, v8::internal::function_literal_id, v8::internal::has_duplicate_parameters, v8::internal::name, v8::internal::Zone::New(), v8::internal::AstValueFactory::NewConsString(), and zone_.
NewGetTemplateObject()
GetTemplateObject* v8::internal::AstNodeFactory::NewGetTemplateObject (const ZonePtrList< const AstRawString > * cooked_strings, const ZonePtrList< const AstRawString > * raw_strings, int pos) [inline]
Definition at line 3557 of file ast.h.
                                                                   {
    return zone_->New<GetTemplateObject>(cooked_strings, raw_strings, pos);
  }
References v8::internal::Zone::New(), and zone_.
NewIfStatement()
IfStatement* v8::internal::AstNodeFactory::NewIfStatement (Expression * condition, Statement * then_statement, Statement * else_statement, int pos) [inline]
Definition at line 3145 of file ast.h.
                                                                  {
    return zone_->New<IfStatement>(condition, then_statement, else_statement,
                                   pos);
  }
References v8::internal::Zone::New(), and zone_.
NewImportCallExpression() [1/2]
ImportCallExpression* v8::internal::AstNodeFactory::NewImportCallExpression (Expression * specifier, ModuleImportPhase phase, Expression * import_options, int pos) [inline]
Definition at line 3575 of file ast.h.
                                                         {
    return zone_->New<ImportCallExpression>(specifier, phase, import_options,
                                            pos);
  }
References v8::internal::Zone::New(), and zone_.
NewImportCallExpression() [2/2]
ImportCallExpression* v8::internal::AstNodeFactory::NewImportCallExpression (Expression * specifier, ModuleImportPhase phase, int pos) [inline]
Definition at line 3569 of file ast.h.
                                                         {
    return zone_->New<ImportCallExpression>(specifier, phase, pos);
  }
References v8::internal::Zone::New(), and zone_.
NewInitializeClassMembersStatement()
InitializeClassMembersStatement* v8::internal::AstNodeFactory::NewInitializeClassMembersStatement (ZonePtrList< ClassLiteral::Property > * args, int pos) [inline]
Definition at line 3583 of file ast.h.
                                                        {
    return zone_->New<InitializeClassMembersStatement>(args, pos);
  }
References v8::base::args, v8::internal::Zone::New(), and zone_.
NewInitializeClassStaticElementsStatement()
InitializeClassStaticElementsStatement* v8::internal::AstNodeFactory::NewInitializeClassStaticElementsStatement (ZonePtrList< ClassLiteral::StaticElement > * args, int pos) [inline]
Definition at line 3589 of file ast.h.
                                                             {
    return zone_->New<InitializeClassStaticElementsStatement>(args, pos);
  }
References v8::base::args, v8::internal::Zone::New(), and zone_.
NewNaryOperation()
NaryOperation* v8::internal::AstNodeFactory::NewNaryOperation (Token::Value op, Expression * first, size_t initial_subsequent_size) [inline]
Definition at line 3380 of file ast.h.
                                                                  {
    return zone_->New<NaryOperation>(zone_, op, first, initial_subsequent_size);
  }
References v8::internal::Zone::New(), and zone_.
NewNativeFunctionLiteral()
NativeFunctionLiteral* v8::internal::AstNodeFactory::NewNativeFunctionLiteral (const AstRawString * name, v8::Extension * extension, int pos) [inline]
Definition at line 3535 of file ast.h.
                                                           {
    return zone_->New<NativeFunctionLiteral>(name, extension, pos);
  }
References v8::internal::name, v8::internal::Zone::New(), and zone_.
NewNestedVariableDeclaration()
NestedVariableDeclaration* v8::internal::AstNodeFactory::NewNestedVariableDeclaration (Scope * scope, int pos) [inline]
Definition at line 3043 of file ast.h.
                                                                   {
    return zone_->New<NestedVariableDeclaration>(scope, pos);
  }
References v8::internal::Zone::New(), and zone_.
Referenced by v8::internal::PreParser::DeclareVariableName().
NewNullLiteral()
Literal* v8::internal::AstNodeFactory::NewNullLiteral (int pos) [inline]
Definition at line 3249 of file ast.h.
                                   {
    return zone_->New<Literal>(Literal::kNull, pos);
  }
References v8::internal::Literal::kNull, v8::internal::Zone::New(), and zone_.
NewNumberLiteral()
Literal * v8::internal::AstNodeFactory::NewNumberLiteral (double number, int pos)
Definition at line 1142 of file ast.cc.
                                                                {
  int int_value;
  if (DoubleToSmiInteger(number, &int_value)) {
    return NewSmiLiteral(int_value, pos);
  }
  return zone_->New<Literal>(number, pos);
}
References v8::internal::DoubleToSmiInteger(), v8::internal::Zone::New(), NewSmiLiteral(), and zone_.
NewObjectLiteral()
ObjectLiteral* v8::internal::AstNodeFactory::NewObjectLiteral (const ScopedPtrList< ObjectLiteral::Property > & properties, uint32_t boilerplate_properties, int pos, bool has_rest_property, Variable * home_object = nullptr) [inline]
Definition at line 3261 of file ast.h.
                                       {
    return zone_->New<ObjectLiteral>(zone_, properties, boilerplate_properties,
                                     pos, has_rest_property, home_object);
  }
References v8::internal::Zone::New(), and zone_.
NewObjectLiteralProperty() [1/2]
ObjectLiteral::Property* v8::internal::AstNodeFactory::NewObjectLiteralProperty (Expression * key, Expression * value, bool is_computed_name) [inline]
Definition at line 3276 of file ast.h.
                                                                           {
    return zone_->New<ObjectLiteral::Property>(ast_value_factory_, key, value,
                                               is_computed_name);
  }
References ast_value_factory_, v8::internal::key, v8::internal::Zone::New(), v8::internal::value, and zone_.
NewObjectLiteralProperty() [2/2]
ObjectLiteral::Property* v8::internal::AstNodeFactory::NewObjectLiteralProperty (Expression * key, Expression * value, ObjectLiteralProperty::Kind kind, bool is_computed_name) [inline]
Definition at line 3269 of file ast.h.
                             {
    return zone_->New<ObjectLiteral::Property>(key, value, kind,
                                               is_computed_name);
  }
References v8::internal::key, v8::internal::Zone::New(), v8::internal::value, and zone_.
NewOptionalChain()
OptionalChain* v8::internal::AstNodeFactory::NewOptionalChain (Expression * expression) [inline]
Definition at line 3319 of file ast.h.
                                                          {
    return zone_->New<OptionalChain>(expression);
  }
References v8::internal::Zone::New(), and zone_.
NewParameterInitializationBlock()
Block* v8::internal::AstNodeFactory::NewParameterInitializationBlock (const ScopedPtrList< Statement > & statements) [inline]
Definition at line 3068 of file ast.h.
                                                  {
    Block* result = zone_->New<Block>(
        /* ignore_completion_value */ true, /* is_breakable */ false,
        /* is_initialization_block_for_parameters */ true);
    result->InitializeStatements(statements, zone_);
    return result;
  }
References v8::internal::Zone::New(), v8::base::internal::result, and zone_.
NewProperty()
Property* v8::internal::AstNodeFactory::NewProperty (Expression * obj, Expression * key, int pos, bool optional_chain = false) [inline]
Definition at line 3323 of file ast.h.
                                                     {
    return zone_->New<Property>(obj, key, pos, optional_chain);
  }
References v8::internal::key, v8::internal::Zone::New(), and zone_.
NewRegExpLiteral()
RegExpLiteral* v8::internal::AstNodeFactory::NewRegExpLiteral (const AstRawString * pattern, int flags, int pos) [inline]
Definition at line 3283 of file ast.h.
                                           {
    return zone_->New<RegExpLiteral>(pattern, flags, pos);
  }
References v8::internal::flags, v8::internal::Zone::New(), and zone_.
NewReturnStatement()
ReturnStatement* v8::internal::AstNodeFactory::NewReturnStatement (Expression * expression, int pos, int end_position = ReturnStatement::kFunctionLiteralReturnPosition) [inline]
Definition at line 3117 of file ast.h.
                                                                        {
    return zone_->New<ReturnStatement>(expression, ReturnStatement::kNormal,
                                       pos, end_position);
  }
References v8::internal::ReturnStatement::kNormal, v8::internal::Zone::New(), and zone_.
Referenced by v8::internal::Rewriter::RewriteBody().
NewScriptOrEvalFunctionLiteral()
FunctionLiteral* v8::internal::AstNodeFactory::NewScriptOrEvalFunctionLiteral (DeclarationScope * scope, const ScopedPtrList< Statement > & body, int expected_property_count, int parameter_count) [inline]
Definition at line 3477 of file ast.h.
                                                        {
    return zone_->New<FunctionLiteral>(
        zone_, ast_value_factory_->empty_cons_string(), ast_value_factory_,
        scope, body, expected_property_count, parameter_count, parameter_count,
        FunctionSyntaxKind::kAnonymousExpression,
        FunctionLiteral::kNoDuplicateParameters,
        FunctionLiteral::kShouldLazyCompile, 0, /* has_braces */ false,
        kFunctionLiteralIdTopLevel);
  }
References ast_value_factory_, v8::internal::AstValueFactory::empty_cons_string(), v8::internal::kAnonymousExpression, v8::internal::kFunctionLiteralIdTopLevel, v8::internal::FunctionLiteral::kNoDuplicateParameters, v8::internal::FunctionLiteral::kShouldLazyCompile, v8::internal::Zone::New(), and zone_.
NewSloppyBlockFunctionStatement()
SloppyBlockFunctionStatement* v8::internal::AstNodeFactory::NewSloppyBlockFunctionStatement (int pos, Variable * var, Token::Value init) [inline]
Definition at line 3214 of file ast.h.
                                               {
    return zone_->New<SloppyBlockFunctionStatement>(pos, var, init,
                                                    EmptyStatement());
  }
References EmptyStatement(), v8::internal::Zone::New(), and zone_.
Referenced by v8::internal::PreParser::DeclareFunction().
NewSmiLiteral()
Literal* v8::internal::AstNodeFactory::NewSmiLiteral (int number, int pos) [inline]
Definition at line 3237 of file ast.h.
                                              {
    return zone_->New<Literal>(number, pos);
  }
References v8::internal::Zone::New(), and zone_.
Referenced by NewNumberLiteral().
NewSpread()
Spread* v8::internal::AstNodeFactory::NewSpread (Expression * expression, int pos, int expr_pos) [inline]
Definition at line 3399 of file ast.h.
                                                                   {
    return zone_->New<Spread>(expression, pos, expr_pos);
  }
References v8::internal::Zone::New(), and zone_.
NewStringLiteral()
Literal* v8::internal::AstNodeFactory::NewStringLiteral (const AstRawString * string, int pos) [inline]
Definition at line 3225 of file ast.h.
                                                                 {
    DCHECK_NOT_NULL(string);
    return zone_->New<Literal>(string, pos);
  }
References DCHECK_NOT_NULL, v8::internal::Zone::New(), v8::internal::string, and zone_.
NewSuperCallForwardArgs()
SuperCallForwardArgs* v8::internal::AstNodeFactory::NewSuperCallForwardArgs (SuperCallReference * expression, int pos) [inline]
Definition at line 3337 of file ast.h.
                                                         {
    return zone_->New<SuperCallForwardArgs>(zone_, expression, pos);
  }
References v8::internal::Zone::New(), and zone_.
NewSuperCallReference()
SuperCallReference* v8::internal::AstNodeFactory::NewSuperCallReference (VariableProxy * new_target_var, VariableProxy * this_function_var, int pos) [inline]
Definition at line 3546 of file ast.h.
                                                     {
    return zone_->New<SuperCallReference>(new_target_var, this_function_var,
                                          pos);
  }
References v8::internal::Zone::New(), and zone_.
NewSuperPropertyReference()
SuperPropertyReference* v8::internal::AstNodeFactory::NewSuperPropertyReference (VariableProxy * home_object_var, int pos) [inline]
Definition at line 3541 of file ast.h.
                                               {
    return zone_->New<SuperPropertyReference>(home_object_var, pos);
  }
References v8::internal::Zone::New(), and zone_.
NewSwitchStatement()
SwitchStatement* v8::internal::AstNodeFactory::NewSwitchStatement (Expression * tag, int pos) [inline]
Definition at line 3084 of file ast.h.
                                                                {
    return zone_->New<SwitchStatement>(zone_, tag, pos);
  }
References v8::internal::Zone::New(), and zone_.
NewSyntheticAsyncReturnStatement()
ReturnStatement* v8::internal::AstNodeFactory::NewSyntheticAsyncReturnStatement (Expression * expression, int pos, int end_position = ReturnStatement::kFunctionLiteralReturnPosition) [inline]
Definition at line 3131 of file ast.h.
                                                                        {
    return zone_->New<ReturnStatement>(
        expression, ReturnStatement::kSyntheticAsyncReturn, pos, end_position);
  }
References v8::internal::ReturnStatement::kSyntheticAsyncReturn, v8::internal::Zone::New(), and zone_.
NewTaggedTemplate()
Call* v8::internal::AstNodeFactory::NewTaggedTemplate (Expression * expression, const ScopedPtrList< Expression > & arguments, int pos) [inline]
Definition at line 3342 of file ast.h.
                                                                               {
    return zone_->New<Call>(zone_, expression, arguments, pos,
                            Call::TaggedTemplateTag::kTrue);
  }
References v8::internal::Call::kTrue, v8::internal::Zone::New(), and zone_.
NewTemplateLiteral()
TemplateLiteral* v8::internal::AstNodeFactory::NewTemplateLiteral (const ZonePtrList< const AstRawString > * string_parts, const ZonePtrList< Expression > * substitutions, int pos) [inline]
Definition at line 3563 of file ast.h.
                                                             {
    return zone_->New<TemplateLiteral>(string_parts, substitutions, pos);
  }
References v8::internal::Zone::New(), and zone_.
NewTheHoleLiteral()
Literal* v8::internal::AstNodeFactory::NewTheHoleLiteral () [inline]
Definition at line 3257 of file ast.h.
                               {
    return zone_->New<Literal>(Literal::kTheHole, kNoSourcePosition);
  }
References v8::internal::kNoSourcePosition, v8::internal::Literal::kTheHole, v8::internal::Zone::New(), and zone_.
NewThisExpression()
class ThisExpression* v8::internal::AstNodeFactory::NewThisExpression (int pos) [inline]
Definition at line 3205 of file ast.h.
                                                   {
    DCHECK_NE(pos, kNoSourcePosition);
    return zone_->New<class ThisExpression>(pos);
  }
References DCHECK_NE, v8::internal::kNoSourcePosition, v8::internal::Zone::New(), and zone_.
NewThrow()
Throw* v8::internal::AstNodeFactory::NewThrow (Expression * exception, int pos) [inline]
Definition at line 3453 of file ast.h.
                                                  {
    return zone_->New<Throw>(exception, pos);
  }
References v8::internal::Zone::New(), and zone_.
NewTryCatchStatement()
TryCatchStatement* v8::internal::AstNodeFactory::NewTryCatchStatement (Block * try_block, Scope * scope, Block * catch_block, int pos) [inline]
Definition at line 3151 of file ast.h.
                                                                       {
    return zone_->New<TryCatchStatement>(try_block, scope, catch_block,
                                         HandlerTable::CAUGHT, pos);
  }
References v8::internal::HandlerTable::CAUGHT, v8::internal::Zone::New(), and zone_.
NewTryCatchStatementForAsyncAwait()
TryCatchStatement* v8::internal::AstNodeFactory::NewTryCatchStatementForAsyncAwait (Block * try_block, Scope * scope, Block * catch_block, int pos) [inline]
Definition at line 3165 of file ast.h.
                                                                {
    return zone_->New<TryCatchStatement>(try_block, scope, catch_block,
                                         HandlerTable::ASYNC_AWAIT, pos);
  }
References v8::internal::HandlerTable::ASYNC_AWAIT, v8::internal::Zone::New(), and zone_.
NewTryCatchStatementForReplAsyncAwait()
TryCatchStatement* v8::internal::AstNodeFactory::NewTryCatchStatementForReplAsyncAwait (Block * try_block, Scope * scope, Block * catch_block, int pos) [inline]
Definition at line 3173 of file ast.h.
                                                                    {
    return zone_->New<TryCatchStatement>(
        try_block, scope, catch_block, HandlerTable::UNCAUGHT_ASYNC_AWAIT, pos);
  }
References v8::internal::Zone::New(), v8::internal::HandlerTable::UNCAUGHT_ASYNC_AWAIT, and zone_.
NewTryCatchStatementForReThrow()
TryCatchStatement* v8::internal::AstNodeFactory::NewTryCatchStatementForReThrow (Block * try_block, Scope * scope, Block * catch_block, int pos) [inline]
Definition at line 3157 of file ast.h.
                                                             {
    return zone_->New<TryCatchStatement>(try_block, scope, catch_block,
                                         HandlerTable::UNCAUGHT, pos);
  }
References v8::internal::Zone::New(), v8::internal::HandlerTable::UNCAUGHT, and zone_.
NewTryFinallyStatement()
TryFinallyStatement* v8::internal::AstNodeFactory::NewTryFinallyStatement (Block * try_block, Block * finally_block, int pos) [inline]
Definition at line 3181 of file ast.h.
                                                                             {
    return zone_->New<TryFinallyStatement>(try_block, finally_block, pos);
  }
References v8::internal::Zone::New(), and zone_.
NewUnaryOperation()
UnaryOperation* v8::internal::AstNodeFactory::NewUnaryOperation (Token::Value op, Expression * expression, int pos) [inline]
Definition at line 3367 of file ast.h.
                                             {
    return zone_->New<UnaryOperation>(op, expression, pos);
  }
References v8::internal::Zone::New(), and zone_.
NewUndefinedLiteral()
Literal* v8::internal::AstNodeFactory::NewUndefinedLiteral (int pos) [inline]
Definition at line 3253 of file ast.h.
                                        {
    return zone_->New<Literal>(Literal::kUndefined, pos);
  }
References v8::internal::Literal::kUndefined, v8::internal::Zone::New(), and zone_.
Referenced by v8::internal::Processor::AssignUndefinedBefore(), NewAwait(), and NewYield().
NewVariableDeclaration()
VariableDeclaration* v8::internal::AstNodeFactory::NewVariableDeclaration (int pos) [inline]
Definition at line 3039 of file ast.h.
                                                       {
    return zone_->New<VariableDeclaration>(pos);
  }
References v8::internal::Zone::New(), and zone_.
Referenced by v8::internal::DeclarationScope::HoistSloppyBlockFunctions(), and v8::internal::BaseConsumedPreparseData< Data >::RestoreDataForScope().
NewVariableProxy() [1/2]
VariableProxy* v8::internal::AstNodeFactory::NewVariableProxy (const AstRawString * name, VariableKind variable_kind, int start_position = kNoSourcePosition) [inline]
Definition at line 3303 of file ast.h.
                                                                          {
    DCHECK_NOT_NULL(name);
    return zone_->New<VariableProxy>(name, variable_kind, start_position);
  }
References DCHECK_NOT_NULL, v8::internal::name, v8::internal::Zone::New(), and zone_.
NewVariableProxy() [2/2]
VariableProxy* v8::internal::AstNodeFactory::NewVariableProxy (Variable * var, int start_position = kNoSourcePosition) [inline]
Definition at line 3298 of file ast.h.
                                                                          {
    return zone_->New<VariableProxy>(var, start_position);
  }
References v8::internal::Zone::New(), and zone_.
Referenced by v8::internal::PreParser::ExpressionFromPrivateName(), v8::internal::DeclarationScope::HoistSloppyBlockFunctions(), v8::internal::Scope::NewUnresolved(), v8::internal::Rewriter::RewriteBody(), and v8::internal::Processor::SetResult().
NewWithStatement()
WithStatement* v8::internal::AstNodeFactory::NewWithStatement (Scope * scope, Expression * expression, Statement * statement, int pos) [inline]
Definition at line 3138 of file ast.h.
                                           {
    return zone_->New<WithStatement>(scope, expression, statement, pos);
  }
References v8::internal::Zone::New(), and zone_.
NewYield()
Suspend* v8::internal::AstNodeFactory::NewYield (Expression * expression, int pos, Suspend::OnAbruptResume on_abrupt_resume) [inline]
Definition at line 3438 of file ast.h.
                                                            {
    if (!expression) expression = NewUndefinedLiteral(pos);
    return zone_->New<Yield>(expression, pos, on_abrupt_resume);
  }
References v8::internal::Zone::New(), NewUndefinedLiteral(), and zone_.
NewYieldStar()
YieldStar* v8::internal::AstNodeFactory::NewYieldStar (Expression * expression, int pos) [inline]
Definition at line 3444 of file ast.h.
                                                           {
    return zone_->New<YieldStar>(expression, pos);
  }
References v8::internal::Zone::New(), and zone_.
ThisExpression()
class ThisExpression* v8::internal::AstNodeFactory::ThisExpression () [inline]
Definition at line 3194 of file ast.h.
                                         {
    // Clear any previously set "parenthesized" flag on this_expression_ so this
    // particular token does not inherit the it. The flag is used to check
    // during arrow function head parsing whether we came from parenthesized
    // exprssion parsing, since additional arrow function verification was done
    // there. It does not matter whether a flag is unset after arrow head
    // verification, so clearing at this point is fine.
    this_expression_->clear_parenthesized();
    return this_expression_;
  }
References v8::internal::Expression::clear_parenthesized(), and this_expression_.
zone()
Zone* v8::internal::AstNodeFactory::zone () const [inline]
Definition at line 3604 of file ast.h.
{ return zone_; }
References zone_.
Referenced by v8::internal::Scope::NewUnresolved().
Member Data Documentation
ast_value_factory_
AstValueFactory* v8::internal::AstNodeFactory::ast_value_factory_ [private]
Definition at line 3612 of file ast.h.
Referenced by ast_value_factory(), NewFunctionLiteral(), NewObjectLiteralProperty(), and NewScriptOrEvalFunctionLiteral().
empty_statement_
class EmptyStatement* v8::internal::AstNodeFactory::empty_statement_ [private]
Definition at line 3613 of file ast.h.
Referenced by EmptyStatement().
failure_expression_
class FailureExpression* v8::internal::AstNodeFactory::failure_expression_ [private]
Definition at line 3615 of file ast.h.
Referenced by FailureExpression().
this_expression_
class ThisExpression* v8::internal::AstNodeFactory::this_expression_ [private]
Definition at line 3614 of file ast.h.
Referenced by ThisExpression().
zone_
Zone* v8::internal::AstNodeFactory::zone_ [private]
Definition at line 3611 of file ast.h.
Referenced by CopyVariable(), CopyVariableProxy(), NewArrayLiteral(), NewAssignment(), NewAsyncReturnStatement(), NewAutoAccessorGetterBody(), NewAutoAccessorInfo(), NewAutoAccessorSetterBody(), NewAwait(), NewBigIntLiteral(), NewBinaryOperation(), NewBlock(), NewBooleanLiteral(), NewBreakStatement(), NewCall(), NewCallNew(), NewCallRuntime(), NewCaseClause(), NewClassLiteral(), NewClassLiteralProperty(), NewClassLiteralStaticElement(), NewCompareOperation(), NewConditional(), NewConditionalChain(), NewConsStringLiteral(), NewContinueStatement(), NewCountOperation(), NewDebuggerStatement(), NewEmptyParentheses(), NewExpressionStatement(), NewForEachStatement(), NewForOfStatement(), NewFunctionDeclaration(), NewFunctionLiteral(), NewGetTemplateObject(), NewIfStatement(), NewImportCallExpression(), NewInitializeClassMembersStatement(), NewInitializeClassStaticElementsStatement(), NewNaryOperation(), NewNativeFunctionLiteral(), NewNestedVariableDeclaration(), NewNullLiteral(), NewNumberLiteral(), NewObjectLiteral(), NewObjectLiteralProperty(), NewOptionalChain(), NewParameterInitializationBlock(), NewProperty(), NewRegExpLiteral(), NewReturnStatement(), NewScriptOrEvalFunctionLiteral(), NewSloppyBlockFunctionStatement(), NewSmiLiteral(), NewSpread(), NewStringLiteral(), NewSuperCallForwardArgs(), NewSuperCallReference(), NewSuperPropertyReference(), NewSwitchStatement(), NewSyntheticAsyncReturnStatement(), NewTaggedTemplate(), NewTemplateLiteral(), NewTheHoleLiteral(), NewThisExpression(), NewThrow(), NewTryCatchStatement(), NewTryCatchStatementForAsyncAwait(), NewTryCatchStatementForReplAsyncAwait(), NewTryCatchStatementForReThrow(), NewTryFinallyStatement(), NewUnaryOperation(), NewUndefinedLiteral(), NewVariableDeclaration(), NewVariableProxy(), NewWithStatement(), NewYield(), NewYieldStar(), and zone().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ast/ast.h
/mnt/V8SourceCode/src/ast/ast.cc