v8::internal::AsmJsCompilationJob Class Reference
Public Member Functions
AsmJsCompilationJob (ParseInfo *parse_info, FunctionLiteral *literal, AccountingAllocator *allocator)
AsmJsCompilationJob (const AsmJsCompilationJob &)=delete
AsmJsCompilationJob & operator= (const AsmJsCompilationJob &)=delete
Protected Member Functions
Status ExecuteJobImpl () final
Status FinalizeJobImpl (DirectHandle< SharedFunctionInfo > shared_info, Isolate *isolate) final
Status FinalizeJobImpl (DirectHandle< SharedFunctionInfo > shared_info, LocalIsolate *isolate) final
Private Member Functions
void RecordHistograms (Isolate *isolate)
Private Attributes
AccountingAllocator * allocator_
Zone zone_
UnoptimizedCompilationInfo compilation_info_
wasm::ZoneBuffer * module_
wasm::ZoneBuffer * asm_offsets_
wasm::AsmJsParser::StdlibSet stdlib_uses_
double compile_time_
int module_source_size_
Additional Inherited Members
Detailed Description
Definition at line 191 of file asm-js.cc.
Constructor & Destructor Documentation
AsmJsCompilationJob() [1/2]
v8::internal::AsmJsCompilationJob::AsmJsCompilationJob (ParseInfo * parse_info, FunctionLiteral * literal, AccountingAllocator * allocator) [inline], [explicit]
Definition at line 193 of file asm-js.cc.
      : UnoptimizedCompilationJob(parse_info->stack_limit(), parse_info,
                                  &compilation_info_),
        allocator_(allocator),
        zone_(allocator, ZONE_NAME),
        compilation_info_(&zone_, parse_info, literal),
        module_(nullptr),
        asm_offsets_(nullptr),
        compile_time_(0),
        module_source_size_(0) {}
AsmJsCompilationJob() [2/2]
v8::internal::AsmJsCompilationJob::AsmJsCompilationJob (const AsmJsCompilationJob &) [delete]
Member Function Documentation
ExecuteJobImpl()
UnoptimizedCompilationJob::Status v8::internal::AsmJsCompilationJob::ExecuteJobImpl () [final], [protected], [virtual]
Implements v8::internal::UnoptimizedCompilationJob.
Definition at line 231 of file asm-js.cc.
                                                                    {
  DisallowHeapAccess no_heap_access;
  // Step 1: Translate asm.js module to WebAssembly module.
  Zone* compile_zone = &zone_;
  Zone translate_zone(allocator_, ZONE_NAME);
  Utf16CharacterStream* stream = parse_info()->character_stream();
  std::optional<AllowHandleDereference> allow_deref;
  if (stream->can_access_heap()) {
    allow_deref.emplace();
  }
  stream->Seek(compilation_info()->literal()->start_position());
  wasm::AsmJsParser parser(&translate_zone, stack_limit(), stream);
  if (!parser.Run()) {
    if (!v8_flags.suppress_asm_messages) {
      ReportCompilationFailure(parse_info(), parser.failure_location(),
                               parser.failure_message());
    }
    return FAILED;
  }
  module_ = compile_zone->New<wasm::ZoneBuffer>(compile_zone);
  parser.module_builder()->WriteTo(module_);
  if (module_->size() > v8_flags.wasm_max_module_size) {
    if (!v8_flags.suppress_asm_messages) {
      ReportCompilationFailure(
          parse_info(), parser.failure_location(),
          "Module size exceeds engine's supported maximum");
    }
    return FAILED;
  }
  asm_offsets_ = compile_zone->New<wasm::ZoneBuffer>(compile_zone);
  parser.module_builder()->WriteAsmJsOffsetTable(asm_offsets_);
  stdlib_uses_ = *parser.stdlib_uses();
  module_source_size_ = compilation_info()->literal()->end_position() -
                        compilation_info()->literal()->start_position();
  return SUCCEEDED;
}
References allocator_, asm_offsets_, v8::internal::Utf16CharacterStream::can_access_heap(), v8::internal::ParseInfo::character_stream(), v8::internal::UnoptimizedCompilationJob::compilation_info(), v8::internal::FunctionLiteral::end_position(), v8::internal::CompilationJob::FAILED, v8::internal::wasm::AsmJsParser::failure_location(), v8::internal::wasm::AsmJsParser::failure_message(), v8::internal::UnoptimizedCompilationInfo::literal(), module_, v8::internal::wasm::AsmJsParser::module_builder(), module_source_size_, v8::internal::Zone::New(), v8::internal::UnoptimizedCompilationJob::parse_info(), v8::internal::anonymous_namespace{asm-js.cc}::ReportCompilationFailure(), v8::internal::wasm::AsmJsParser::Run(), v8::internal::Utf16CharacterStream::Seek(), v8::internal::wasm::ZoneBuffer::size(), v8::internal::UnoptimizedCompilationJob::stack_limit(), v8::internal::FunctionLiteral::start_position(), v8::internal::wasm::AsmJsParser::stdlib_uses(), stdlib_uses_, v8::internal::CompilationJob::SUCCEEDED, v8::internal::v8_flags, v8::internal::wasm::WasmModuleBuilder::WriteAsmJsOffsetTable(), v8::internal::wasm::WasmModuleBuilder::WriteTo(), zone_, and ZONE_NAME.
FinalizeJobImpl() [1/2]
UnoptimizedCompilationJob::Status v8::internal::AsmJsCompilationJob::FinalizeJobImpl (DirectHandle< SharedFunctionInfo > shared_info, Isolate * isolate) [final], [protected], [virtual]
Implements v8::internal::UnoptimizedCompilationJob.
Definition at line 271 of file asm-js.cc.
                                                                    {
  // Step 2: Compile and decode the WebAssembly module.
  base::ElapsedTimer compile_timer;
  compile_timer.Start();
  DirectHandle<HeapNumber> uses_bitset =
      isolate->factory()->NewHeapNumberFromBits(stdlib_uses_.ToIntegral());
  // The result is a compiled module and serialized standard library uses.
  wasm::ErrorThrower thrower(isolate, "AsmJs::Compile");
  Handle<Script> script(Cast<Script>(shared_info->script()), isolate);
  Handle<AsmWasmData> result =
      wasm::GetWasmEngine()
          ->SyncCompileTranslatedAsmJs(
              isolate, &thrower, base::OwnedCopyOf(*module_), script,
              base::VectorOf(*asm_offsets_), uses_bitset,
              shared_info->language_mode())
          .ToHandleChecked();
  DCHECK(!thrower.error());
  compile_time_ = compile_timer.Elapsed().InMillisecondsF();
  compilation_info()->SetAsmWasmData(result);
  RecordHistograms(isolate);
  ReportCompilationSuccess(script, shared_info->StartPosition(), compile_time_,
                           module_->size());
  return SUCCEEDED;
}
References asm_offsets_, v8::internal::UnoptimizedCompilationJob::compilation_info(), compile_time_, v8::internal::DCHECK(), v8::base::ElapsedTimer::Elapsed(), v8::internal::wasm::ErrorThrower::error(), v8::internal::Isolate::factory(), v8::internal::wasm::GetWasmEngine(), v8::base::TimeDelta::InMillisecondsF(), module_, v8::internal::FactoryBase< Impl >::NewHeapNumberFromBits(), v8::base::OwnedCopyOf(), RecordHistograms(), v8::internal::anonymous_namespace{asm-js.cc}::ReportCompilationSuccess(), v8::base::internal::result, v8::internal::script, v8::internal::UnoptimizedCompilationInfo::SetAsmWasmData(), v8::internal::wasm::ZoneBuffer::size(), v8::base::ElapsedTimer::Start(), stdlib_uses_, v8::internal::CompilationJob::SUCCEEDED, v8::internal::wasm::WasmEngine::SyncCompileTranslatedAsmJs(), v8::base::EnumSet< E, T >::ToIntegral(), and v8::base::VectorOf().
FinalizeJobImpl() [2/2]
Status v8::internal::AsmJsCompilationJob::FinalizeJobImpl (DirectHandle< SharedFunctionInfo > shared_info, LocalIsolate * isolate) [inline], [final], [protected], [virtual]
Implements v8::internal::UnoptimizedCompilationJob.
Definition at line 212 of file asm-js.cc.
                                                      {
    return CompilationJob::RETRY_ON_MAIN_THREAD;
  }
References v8::internal::CompilationJob::RETRY_ON_MAIN_THREAD.
operator=()
AsmJsCompilationJob& v8::internal::AsmJsCompilationJob::operator= (const AsmJsCompilationJob &) [delete]
RecordHistograms()
void v8::internal::AsmJsCompilationJob::RecordHistograms (Isolate * isolate) [private]
Definition at line 301 of file asm-js.cc.
                                                           {
  isolate->counters()->asm_module_size_bytes()->AddSample(module_source_size_);
}
References v8::internal::Isolate::counters(), and module_source_size_.
Referenced by FinalizeJobImpl().
Member Data Documentation
allocator_
AccountingAllocator* v8::internal::AsmJsCompilationJob::allocator_ [private]
Definition at line 220 of file asm-js.cc.
Referenced by ExecuteJobImpl().
asm_offsets_
wasm::ZoneBuffer* v8::internal::AsmJsCompilationJob::asm_offsets_ [private]
Definition at line 224 of file asm-js.cc.
Referenced by ExecuteJobImpl(), and FinalizeJobImpl().
compilation_info_
UnoptimizedCompilationInfo v8::internal::AsmJsCompilationJob::compilation_info_ [private]
Definition at line 222 of file asm-js.cc.
compile_time_
double v8::internal::AsmJsCompilationJob::compile_time_ [private]
Definition at line 227 of file asm-js.cc.
Referenced by FinalizeJobImpl().
module_
wasm::ZoneBuffer* v8::internal::AsmJsCompilationJob::module_ [private]
Definition at line 223 of file asm-js.cc.
Referenced by ExecuteJobImpl(), and FinalizeJobImpl().
module_source_size_
int v8::internal::AsmJsCompilationJob::module_source_size_ [private]
Definition at line 228 of file asm-js.cc.
Referenced by ExecuteJobImpl(), and RecordHistograms().
stdlib_uses_
wasm::AsmJsParser::StdlibSet v8::internal::AsmJsCompilationJob::stdlib_uses_ [private]
Definition at line 225 of file asm-js.cc.
Referenced by ExecuteJobImpl(), and FinalizeJobImpl().
zone_
Zone v8::internal::AsmJsCompilationJob::zone_ [private]
Definition at line 221 of file asm-js.cc.
Referenced by ExecuteJobImpl().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/asmjs/asm-js.cc