v8::internal::QuickCheckDetails Class Reference
#include <regexp-compiler.h>
Classes
struct Position
Public Member Functions
QuickCheckDetails ()
QuickCheckDetails (int characters)
bool Rationalize (bool one_byte)
void Merge (QuickCheckDetails *other, int from_index)
void Advance (int by, bool one_byte)
void Clear ()
bool cannot_match ()
void set_cannot_match ()
int characters () const
void set_characters (int characters)
Position * positions (int index)
const Position * positions (int index) const
uint32_t mask ()
uint32_t value ()
Private Attributes
int characters_
Position positions_ [4]
uint32_t mask_
uint32_t value_
bool cannot_match_
Detailed Description
Definition at line 62 of file regexp-compiler.h.
Constructor & Destructor Documentation
QuickCheckDetails() [1/2]
v8::internal::QuickCheckDetails::QuickCheckDetails () [inline]
Definition at line 64 of file regexp-compiler.h.
      : characters_(0), mask_(0), value_(0), cannot_match_(false) {}
QuickCheckDetails() [2/2]
v8::internal::QuickCheckDetails::QuickCheckDetails (int characters) [inline], [explicit]
Definition at line 66 of file regexp-compiler.h.
      : characters_(characters), mask_(0), value_(0), cannot_match_(false) {}
Member Function Documentation
Advance()
void v8::internal::QuickCheckDetails::Advance (int by, bool one_byte)
Definition at line 1811 of file regexp-compiler.cc.
                                                     {
  if (by >= characters_ || by < 0) {
    DCHECK_IMPLIES(by < 0, characters_ == 0);
    Clear();
    return;
  }
  DCHECK_LE(characters_ - by, 4);
  DCHECK_LE(characters_, 4);
  for (int i = 0; i < characters_ - by; i++) {
    positions_[i] = positions_[by + i];
  }
  for (int i = characters_ - by; i < characters_; i++) {
    positions_[i].mask = 0;
    positions_[i].value = 0;
    positions_[i].determines_perfectly = false;
  }
  characters_ -= by;
  // We could change mask_ and value_ here but we would never advance unless
  // they had already been used in a check and they won't be used again because
  // it would gain us nothing. So there's no point.
}
References characters_, Clear(), DCHECK_IMPLIES, DCHECK_LE, v8::internal::QuickCheckDetails::Position::determines_perfectly, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::QuickCheckDetails::Position::mask, positions_, and v8::internal::QuickCheckDetails::Position::value.
Referenced by v8::internal::Trace::AdvanceCurrentPositionInTrace().
cannot_match()
bool v8::internal::QuickCheckDetails::cannot_match () [inline]
Definition at line 74 of file regexp-compiler.h.
{ return cannot_match_; }
References cannot_match_.
Referenced by v8::internal::ChoiceNode::EmitChoices(), v8::internal::RegExpNode::EmitQuickCheck(), and v8::internal::TextNode::GetQuickCheckDetails().
characters()
int v8::internal::QuickCheckDetails::characters () const [inline]
Definition at line 82 of file regexp-compiler.h.
{ return characters_; }
References characters_.
Referenced by v8::internal::anonymous_namespace{regexp-compiler.cc}::DeterminedAlready(), v8::internal::RegExpNode::EmitQuickCheck(), v8::internal::TextNode::GetQuickCheckDetails(), v8::internal::ChoiceNode::GetQuickCheckDetails(), v8::internal::Trace::is_trivial(), and set_characters().
Clear()
void v8::internal::QuickCheckDetails::Clear ()
Definition at line 1802 of file regexp-compiler.cc.
                              {
  for (int i = 0; i < characters_; i++) {
    positions_[i].mask = 0;
    positions_[i].value = 0;
    positions_[i].determines_perfectly = false;
  }
  characters_ = 0;
}
References characters_, v8::internal::QuickCheckDetails::Position::determines_perfectly, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::QuickCheckDetails::Position::mask, positions_, and v8::internal::QuickCheckDetails::Position::value.
Referenced by Advance(), and v8::internal::ChoiceNode::EmitChoices().
mask()
uint32_t v8::internal::QuickCheckDetails::mask () [inline]
Definition at line 94 of file regexp-compiler.h.
{ return mask_; }
References mask_.
Referenced by v8::internal::RegExpNode::EmitQuickCheck().
Merge()
void v8::internal::QuickCheckDetails::Merge (QuickCheckDetails * other, int from_index)
Definition at line 1833 of file regexp-compiler.cc.
                                                                      {
  DCHECK(characters_ == other->characters_);
  if (other->cannot_match_) {
    return;
  }
  if (cannot_match_) {
    *this = *other;
    return;
  }
  for (int i = from_index; i < characters_; i++) {
    QuickCheckDetails::Position* pos = positions(i);
    QuickCheckDetails::Position* other_pos = other->positions(i);
    if (pos->mask != other_pos->mask || pos->value != other_pos->value ||
        !other_pos->determines_perfectly) {
      // Our mask-compare operation will be approximate unless we have the
      // exact same operation on both sides of the alternation.
      pos->determines_perfectly = false;
    }
    pos->mask &= other_pos->mask;
    pos->value &= pos->mask;
    other_pos->value &= pos->mask;
    uint32_t differing_bits = (pos->value ^ other_pos->value);
    pos->mask &= ~differing_bits;
    pos->value &= pos->mask;
  }
}
References cannot_match_, characters_, v8::internal::DCHECK(), v8::internal::QuickCheckDetails::Position::determines_perfectly, v8::internal::QuickCheckDetails::Position::mask, positions(), and v8::internal::QuickCheckDetails::Position::value.
Referenced by v8::internal::ChoiceNode::GetQuickCheckDetails().
positions() [1/2]
Position* v8::internal::QuickCheckDetails::positions (int index) [inline]
Definition at line 84 of file regexp-compiler.h.
                                 {
    DCHECK_LE(0, index);
    DCHECK_GT(characters_, index);
    return positions_ + index;
  }
References characters_, DCHECK_GT, DCHECK_LE, v8::internal::index, and positions_.
Referenced by v8::internal::anonymous_namespace{regexp-compiler.cc}::DeterminedAlready(), v8::internal::TextNode::GetQuickCheckDetails(), and Merge().
positions() [2/2]
const Position* v8::internal::QuickCheckDetails::positions (int index) const [inline]
Definition at line 89 of file regexp-compiler.h.
                                             {
    DCHECK_LE(0, index);
    DCHECK_GT(characters_, index);
    return positions_ + index;
  }
References characters_, DCHECK_GT, DCHECK_LE, v8::internal::index, and positions_.
Rationalize()
bool v8::internal::QuickCheckDetails::Rationalize (bool one_byte)
Definition at line 1486 of file regexp-compiler.cc.
                                            {
  bool found_useful_op = false;
  const uint32_t char_mask = CharMask(asc);
  mask_ = 0;
  value_ = 0;
  int char_shift = 0;
  for (int i = 0; i < characters_; i++) {
    Position* pos = &positions_[i];
    if ((pos->mask & String::kMaxOneByteCharCode) != 0) {
      found_useful_op = true;
    }
    mask_ |= (pos->mask & char_mask) << char_shift;
    value_ |= (pos->value & char_mask) << char_shift;
    char_shift += asc ? 8 : 16;
  }
  return found_useful_op;
}
References characters_, v8::internal::anonymous_namespace{regexp-compiler.cc}::CharMask(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::String::kMaxOneByteCharCode, v8::internal::QuickCheckDetails::Position::mask, mask_, positions_, v8::internal::QuickCheckDetails::Position::value, and value_.
Referenced by v8::internal::RegExpNode::EmitQuickCheck().
set_cannot_match()
void v8::internal::QuickCheckDetails::set_cannot_match () [inline]
Definition at line 75 of file regexp-compiler.h.
{ cannot_match_ = true; }
References cannot_match_.
Referenced by v8::internal::TextNode::GetQuickCheckDetails(), and v8::internal::AssertionNode::GetQuickCheckDetails().
set_characters()
void v8::internal::QuickCheckDetails::set_characters (int characters) [inline]
Definition at line 83 of file regexp-compiler.h.
{ characters_ = characters; }
References characters(), and characters_.
Referenced by v8::internal::ChoiceNode::EmitChoices().
value()
uint32_t v8::internal::QuickCheckDetails::value () [inline]
Definition at line 95 of file regexp-compiler.h.
{ return value_; }
References value_.
Referenced by v8::internal::RegExpNode::EmitQuickCheck().
Member Data Documentation
cannot_match_
bool v8::internal::QuickCheckDetails::cannot_match_ [private]
Definition at line 107 of file regexp-compiler.h.
Referenced by cannot_match(), Merge(), and set_cannot_match().
characters_
int v8::internal::QuickCheckDetails::characters_ [private]
Definition at line 100 of file regexp-compiler.h.
Referenced by Advance(), characters(), Clear(), Merge(), positions(), Rationalize(), and set_characters().
mask_
uint32_t v8::internal::QuickCheckDetails::mask_ [private]
Definition at line 103 of file regexp-compiler.h.
Referenced by mask(), and Rationalize().
positions_
Position v8::internal::QuickCheckDetails::positions_[4] [private]
Definition at line 101 of file regexp-compiler.h.
Referenced by Advance(), Clear(), positions(), and Rationalize().
value_
uint32_t v8::internal::QuickCheckDetails::value_ [private]
Definition at line 104 of file regexp-compiler.h.
Referenced by Rationalize(), and value().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-compiler.h
/mnt/V8SourceCode/src/regexp/regexp-compiler.cc