v8::internal::Sweeper::ConcurrentMinorSweeper Class Reference
Public Member Functions
ConcurrentMinorSweeper (Sweeper *sweeper)
bool ConcurrentSweepSpace (JobDelegate *delegate)
bool ConcurrentSweepPromotedPages (JobDelegate *delegate)
Private Attributes
Sweeper *const sweeper_
LocalSweeper local_sweeper_
Detailed Description
Definition at line 80 of file sweeper.cc.
Constructor & Destructor Documentation
ConcurrentMinorSweeper()
v8::internal::Sweeper::ConcurrentMinorSweeper::ConcurrentMinorSweeper (Sweeper * sweeper) [inline], [explicit]
Definition at line 82 of file sweeper.cc.
      : sweeper_(sweeper), local_sweeper_(sweeper_) {}
Member Function Documentation
ConcurrentSweepPromotedPages()
bool v8::internal::Sweeper::ConcurrentMinorSweeper::ConcurrentSweepPromotedPages (JobDelegate * delegate) [inline]
Definition at line 97 of file sweeper.cc.
                                                           {
    if (local_sweeper_.ParallelIteratePromotedPages(delegate)) return true;
    TRACE_GC_NOTE("Sweeper::ConcurrentMinorSweeper Preempted");
    return false;
  }
References local_sweeper_, v8::internal::Sweeper::LocalSweeper::ParallelIteratePromotedPages(), and TRACE_GC_NOTE.
Referenced by v8::internal::Sweeper::MinorSweeperJob::RunImpl().
ConcurrentSweepSpace()
bool v8::internal::Sweeper::ConcurrentMinorSweeper::ConcurrentSweepSpace (JobDelegate * delegate) [inline]
Definition at line 85 of file sweeper.cc.
                                                   {
    DCHECK(IsValidSweepingSpace(kNewSpace));
    while (!delegate->ShouldYield()) {
      PageMetadata* page = sweeper_->GetSweepingPageSafe(kNewSpace);
      if (page == nullptr) return true;
      local_sweeper_.ParallelSweepPage(page, kNewSpace,
                                       SweepingMode::kLazyOrConcurrent);
    }
    TRACE_GC_NOTE("Sweeper::ConcurrentMinorSweeper Preempted");
    return false;
  }
References v8::internal::DCHECK(), v8::internal::Sweeper::GetSweepingPageSafe(), v8::internal::Sweeper::IsValidSweepingSpace(), v8::internal::Sweeper::kLazyOrConcurrent, v8::internal::kNewSpace, local_sweeper_, v8::internal::Sweeper::LocalSweeper::ParallelSweepPage(), v8::JobDelegate::ShouldYield(), sweeper_, and TRACE_GC_NOTE.
Referenced by v8::internal::Sweeper::MinorSweeperJob::RunImpl().
Member Data Documentation
local_sweeper_
LocalSweeper v8::internal::Sweeper::ConcurrentMinorSweeper::local_sweeper_ [private]
Definition at line 105 of file sweeper.cc.
Referenced by ConcurrentSweepPromotedPages(), and ConcurrentSweepSpace().
sweeper_
Sweeper* const v8::internal::Sweeper::ConcurrentMinorSweeper::sweeper_ [private]
Definition at line 104 of file sweeper.cc.
Referenced by ConcurrentSweepSpace().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/sweeper.cc