v8::internal::ContinuationRecord Class Reference
Public Types
enum Type {
kObject
, kArray
, kObjectResume_FastIterable
, kObjectResume_SlowIterable
,
kObjectResume_Uninitialized
, kArrayResume
, kArrayResume_Holey
, kArrayResume_WithInterrupts
,
kArrayResume_Holey_WithInterrupts
, kSimpleObject
, kObjectKey
 }
using ObjectT = UnionOf< JSAny, FixedArrayBase >
Public Member Functions
Type type () const
Tagged< ObjectT > object () const
Tagged< JSAny > simple_object () const
Tagged< JSArray > js_array () const
Tagged< FixedArrayBase > array_elements () const
Tagged< JSObject > js_object () const
Tagged< String > object_key () const
uint32_t array_index () const
uint32_t array_length () const
uint16_t object_descriptor_idx () const
uint16_t object_nof_descriptors () const
uint8_t object_in_object_properties () const
uint8_t object_in_object_properties_start () const
Tagged< DescriptorArray > object_descriptors () const
bool object_key_comma () const
Static Public Member Functions
static constexpr ContinuationRecord ForSimpleObject (Tagged< JSAny > obj)
static constexpr ContinuationRecord ForJSAny (Tagged< JSAny > obj, FastJsonStringifierResult result)
static constexpr ContinuationRecord ForJSArray (Tagged< JSAny > obj)
template<ElementsKind kind, bool with_interrupt_check>
static constexpr ContinuationRecord ForJSArrayResume (Tagged< FixedArrayBase > obj, uint32_t index, uint32_t length)
static constexpr ContinuationRecord ForJSObject (Tagged< JSAny > obj)
template<DescriptorArray::FastIterableState fast_iterable_state>
static constexpr ContinuationRecord ForJSObjectResume (Tagged< JSAny > obj, uint16_t descriptor_idx, uint16_t nof_descriptors, uint8_t in_object_properties, uint8_t in_object_properties_start, Tagged< DescriptorArray > descriptors)
static constexpr ContinuationRecord ForObjectKey (Tagged< String > key, bool comma)
static constexpr bool IsObjectResumeType (Type type)
static constexpr bool IsArrayResumeType (Type type)
Private Member Functions
constexpr ContinuationRecord (Type type, Tagged< ObjectT > obj, uint32_t index, uint32_t length)
constexpr ContinuationRecord (Type type, Tagged< ObjectT > obj, uint16_t descriptor_idx, uint16_t nof_descriptors, uint8_t in_object_properties, uint8_t in_object_properties_start, Tagged< DescriptorArray > descriptors)
constexpr ContinuationRecord (Type type, Tagged< ObjectT > obj, bool comma)
Static Private Member Functions
static constexpr Type ContinuationTypeFromResult (FastJsonStringifierResult result)
static consteval Type ContinuationTypeForArray (ElementsKind kind, bool with_interrupt_check)
Private Attributes
Type type_
Tagged< ObjectT > object_
xx xx xx xx xx xx xx xx xx
union {
 struct {
  uint32_t index
  uint32_t length
 } js_array_
 struct {
  uint16_t descriptor_idx
  uint16_t nof_descriptors
  uint8_t in_object_properties
  uint8_t in_object_properties_start
  Tagged< DescriptorArray > descriptors
 } js_object_
 struct {
  bool comma
 } object_key_
};
Detailed Description
Definition at line 1952 of file json-stringifier.cc.
Member Typedef Documentation
ObjectT
using v8::internal::ContinuationRecord::ObjectT = UnionOf<JSAny, FixedArrayBase>
Definition at line 1974 of file json-stringifier.cc.
Member Enumeration Documentation
Type
enum v8::internal::ContinuationRecord::Type
Enumerator
kObject
kArray
kObjectResume_FastIterable
kObjectResume_SlowIterable
kObjectResume_Uninitialized
kArrayResume
kArrayResume_Holey
kArrayResume_WithInterrupts
kArrayResume_Holey_WithInterrupts
kSimpleObject
kObjectKey
Definition at line 1954 of file json-stringifier.cc.
            {
    kObject,
    kArray,
    kObjectResume_FastIterable,
    kObjectResume_SlowIterable,
    kObjectResume_Uninitialized,
    kArrayResume,
    kArrayResume_Holey,
    kArrayResume_WithInterrupts,
    kArrayResume_Holey_WithInterrupts,
    kSimpleObject, // Resume after encoding change.
                    // Object is any simple object that can be serialized
                    // successfully with TrySerializeSimpleObject().
    kObjectKey // For encoding changes triggered by object keys.
                    // This is required (instead of simply resuming with the
                    // object/index that triggered the change), to avoid
                    // re-serializing '{' if the first property key triggered
                    // the change.
  };
Constructor & Destructor Documentation
ContinuationRecord() [1/3]
constexpr v8::internal::ContinuationRecord::ContinuationRecord (Type type, Tagged< ObjectT > obj, uint32_t index, uint32_t length) [inline], [constexpr], [private]
Definition at line 2097 of file json-stringifier.cc.
      : type_(type), object_(obj), js_array_({index, length}) {}
References index, and length.
Referenced by ForJSAny(), ForJSArray(), ForJSArrayResume(), ForJSObject(), ForJSObjectResume(), ForObjectKey(), and ForSimpleObject().
ContinuationRecord() [2/3]
constexpr v8::internal::ContinuationRecord::ContinuationRecord (Type type, Tagged< ObjectT > obj, uint16_t descriptor_idx, uint16_t nof_descriptors, uint8_t in_object_properties, uint8_t in_object_properties_start, Tagged< DescriptorArray > descriptors) [inline], [constexpr], [private]
Definition at line 2100 of file json-stringifier.cc.
      : type_(type),
        object_(obj),
        js_object_({descriptor_idx, nof_descriptors, in_object_properties,
                    in_object_properties_start, descriptors}) {}
References descriptor_idx, descriptors, in_object_properties, in_object_properties_start, and nof_descriptors.
ContinuationRecord() [3/3]
constexpr v8::internal::ContinuationRecord::ContinuationRecord (Type type, Tagged< ObjectT > obj, bool comma) [inline], [constexpr], [private]
Definition at line 2110 of file json-stringifier.cc.
      : type_(type), object_(obj), object_key_{comma} {}
Member Function Documentation
array_elements()
Tagged<FixedArrayBase> v8::internal::ContinuationRecord::array_elements () const [inline]
Definition at line 2037 of file json-stringifier.cc.
                                                {
    DCHECK(IsArrayResumeType(type()));
    return Cast<FixedArrayBase>(object_);
  }
References v8::internal::DCHECK(), IsArrayResumeType(), object_, and type().
Referenced by v8::internal::FastJsonStringifier< Char >::SerializeObject().
array_index()
uint32_t v8::internal::ContinuationRecord::array_index () const [inline]
Definition at line 2050 of file json-stringifier.cc.
                               {
    DCHECK(IsArrayResumeType(type()));
    return js_array_.index;
  }
References v8::internal::DCHECK(), IsArrayResumeType(), js_array_, and type().
Referenced by v8::internal::FastJsonStringifier< Char >::SerializeObject().
array_length()
uint32_t v8::internal::ContinuationRecord::array_length () const [inline]
Definition at line 2054 of file json-stringifier.cc.
                                {
    DCHECK(IsArrayResumeType(type()));
    return js_array_.length;
  }
References v8::internal::DCHECK(), IsArrayResumeType(), js_array_, and type().
Referenced by v8::internal::FastJsonStringifier< Char >::SerializeObject().
ContinuationTypeForArray()
static consteval Type v8::internal::ContinuationRecord::ContinuationTypeForArray (ElementsKind kind, bool with_interrupt_check) [inline], [static], [private]
Definition at line 2121 of file json-stringifier.cc.
                                                                            {
    DCHECK(IsObjectElementsKind(kind));
    if (IsHoleyElementsKind(kind)) {
      if (with_interrupt_check) {
        return kArrayResume_Holey_WithInterrupts;
      } else {
        return kArrayResume_Holey;
      }
    } else {
      if (with_interrupt_check) {
        return kArrayResume_WithInterrupts;
      } else {
        return kArrayResume;
      }
    }
  }
References v8::internal::DCHECK(), v8::internal::IsHoleyElementsKind(), v8::internal::IsObjectElementsKind(), kArrayResume, kArrayResume_Holey, kArrayResume_Holey_WithInterrupts, and kArrayResume_WithInterrupts.
Referenced by ForJSArrayResume().
ContinuationTypeFromResult()
static constexpr Type v8::internal::ContinuationRecord::ContinuationTypeFromResult (FastJsonStringifierResult result) [inline], [static], [constexpr], [private]
Definition at line 2113 of file json-stringifier.cc.
                                        {
    DCHECK(result == JS_OBJECT || result == JS_ARRAY);
    static_assert(JS_OBJECT - 1 == Type::kObject);
    static_assert(JS_ARRAY - 1 == Type::kArray);
    return static_cast<Type>(result - 1);
  }
References v8::internal::DCHECK(), v8::internal::JS_ARRAY, v8::internal::JS_OBJECT, and v8::base::internal::result.
Referenced by ForJSAny().
ForJSAny()
static constexpr ContinuationRecord v8::internal::ContinuationRecord::ForJSAny (Tagged< JSAny > obj, FastJsonStringifierResult result) [inline], [static], [constexpr]
Definition at line 1979 of file json-stringifier.cc.
                                                           {
    return ContinuationRecord(ContinuationTypeFromResult(result), obj, 0, 0);
  }
References ContinuationRecord(), ContinuationTypeFromResult(), and v8::base::internal::result.
Referenced by v8::internal::FastJsonStringifier< Char >::ResumeJSObject(), v8::internal::FastJsonStringifier< Char >::SerializeFixedArrayElement(), and v8::internal::FastJsonStringifier< Char >::SerializeObject().
ForJSArray()
static constexpr ContinuationRecord v8::internal::ContinuationRecord::ForJSArray (Tagged< JSAny > obj) [inline], [static], [constexpr]
Definition at line 1983 of file json-stringifier.cc.
                                                                    {
    DCHECK(Is<JSArray>(obj));
    return ContinuationRecord(Type::kArray, obj, 0, 0);
  }
References ContinuationRecord(), and v8::internal::DCHECK().
Referenced by v8::internal::FastJsonStringifier< Char >::ResumeJSObject().
ForJSArrayResume()
template<ElementsKind kind, bool with_interrupt_check>
static constexpr ContinuationRecord v8::internal::ContinuationRecord::ForJSArrayResume (Tagged< FixedArrayBase > obj, uint32_t index, uint32_t length) [inline], [static], [constexpr]
Definition at line 1988 of file json-stringifier.cc.
                                                                   {
    return ContinuationRecord(
        ContinuationTypeForArray(kind, with_interrupt_check), obj, index,
        length);
  }
References ContinuationRecord(), ContinuationTypeForArray(), index, and length.
ForJSObject()
static constexpr ContinuationRecord v8::internal::ContinuationRecord::ForJSObject (Tagged< JSAny > obj) [inline], [static], [constexpr]
Definition at line 1994 of file json-stringifier.cc.
                                                                     {
    DCHECK(Is<JSObject>(obj));
    return ContinuationRecord(Type::kObject, obj, 0, 0, 0, 0,
                              Tagged<DescriptorArray>());
  }
References ContinuationRecord(), and v8::internal::DCHECK().
Referenced by v8::internal::FastJsonStringifier< Char >::ResumeJSObject().
ForJSObjectResume()
template<DescriptorArray::FastIterableState fast_iterable_state>
static constexpr ContinuationRecord v8::internal::ContinuationRecord::ForJSObjectResume (Tagged< JSAny > obj, uint16_t descriptor_idx, uint16_t nof_descriptors, uint8_t in_object_properties, uint8_t in_object_properties_start, Tagged< DescriptorArray > descriptors) [inline], [static], [constexpr]
Definition at line 2000 of file json-stringifier.cc.
                                           {
    DCHECK(Is<JSObject>(obj));
    Type type;
    using enum DescriptorArray::FastIterableState;
    switch (fast_iterable_state) {
      case kJsonFast:
        type = Type::kObjectResume_FastIterable;
        break;
      case kJsonSlow:
        type = Type::kObjectResume_SlowIterable;
        break;
      case kUnknown:
        type = Type::kObjectResume_Uninitialized;
        break;
    }
    return ContinuationRecord(type, obj, descriptor_idx, nof_descriptors,
                              in_object_properties, in_object_properties_start,
                              descriptors);
  }
References ContinuationRecord(), v8::internal::DCHECK(), descriptor_idx, descriptors, in_object_properties, in_object_properties_start, v8::internal::kUnknown, nof_descriptors, and type().
ForObjectKey()
static constexpr ContinuationRecord v8::internal::ContinuationRecord::ForObjectKey (Tagged< String > key, bool comma) [inline], [static], [constexpr]
Definition at line 2022 of file json-stringifier.cc.
                                                               {
    return ContinuationRecord(Type::kObjectKey, key, comma);
  }
References comma, ContinuationRecord(), and v8::internal::key.
Referenced by v8::internal::FastJsonStringifier< Char >::ResumeJSObject().
ForSimpleObject()
static constexpr ContinuationRecord v8::internal::ContinuationRecord::ForSimpleObject (Tagged< JSAny > obj) [inline], [static], [constexpr]
Definition at line 1976 of file json-stringifier.cc.
                                                                         {
    return ContinuationRecord(Type::kSimpleObject, obj, 0, 0);
  }
References ContinuationRecord().
Referenced by v8::internal::FastJsonStringifier< Char >::ResumeJSObject(), v8::internal::FastJsonStringifier< Char >::SerializeFixedArrayElement(), and v8::internal::FastJsonStringifier< Char >::SerializeObject().
IsArrayResumeType()
static constexpr bool v8::internal::ContinuationRecord::IsArrayResumeType (Type type) [inline], [static], [constexpr]
Definition at line 2090 of file json-stringifier.cc.
                                                     {
    return type == Type::kArrayResume || type == Type::kArrayResume_Holey ||
           type == Type::kArrayResume_WithInterrupts ||
           type == Type::kArrayResume_Holey_WithInterrupts;
  }
References type().
Referenced by array_elements(), array_index(), and array_length().
IsObjectResumeType()
static constexpr bool v8::internal::ContinuationRecord::IsObjectResumeType (Type type) [inline], [static], [constexpr]
Definition at line 2085 of file json-stringifier.cc.
                                                      {
    return type == Type::kObjectResume_FastIterable ||
           type == Type::kObjectResume_SlowIterable ||
           type == Type::kObjectResume_Uninitialized;
  }
References type().
Referenced by js_object(), object_descriptor_idx(), object_descriptors(), object_in_object_properties(), object_in_object_properties_start(), object_nof_descriptors(), and v8::internal::requires().
js_array()
Tagged<JSArray> v8::internal::ContinuationRecord::js_array () const [inline]
Definition at line 2033 of file json-stringifier.cc.
                                   {
    DCHECK_EQ(type(), Type::kArray);
    return Cast<JSArray>(object_);
  }
References DCHECK_EQ, object_, and type().
Referenced by v8::internal::FastJsonStringifier< Char >::SerializeObject().
js_object()
Tagged<JSObject> v8::internal::ContinuationRecord::js_object () const [inline]
Definition at line 2041 of file json-stringifier.cc.
                                     {
    DCHECK(type() == Type::kObject || IsObjectResumeType(type()));
    return Cast<JSObject>(object_);
  }
References v8::internal::DCHECK(), IsObjectResumeType(), object_, and type().
Referenced by v8::internal::FastJsonStringifier< Char >::SerializeObject().
object()
Tagged<ObjectT> v8::internal::ContinuationRecord::object () const [inline]
Definition at line 2028 of file json-stringifier.cc.
{ return object_; }
References object_.
Referenced by v8::internal::FastJsonStringifier< Char >::CheckCycle().
object_descriptor_idx()
uint16_t v8::internal::ContinuationRecord::object_descriptor_idx () const [inline]
Definition at line 2059 of file json-stringifier.cc.
                                         {
    DCHECK(IsObjectResumeType(type()));
    return js_object_.descriptor_idx;
  }
References v8::internal::DCHECK(), IsObjectResumeType(), js_object_, and type().
Referenced by v8::internal::FastJsonStringifier< Char >::SerializeObject().
object_descriptors()
Tagged<DescriptorArray> v8::internal::ContinuationRecord::object_descriptors () const [inline]
Definition at line 2075 of file json-stringifier.cc.
                                                     {
    DCHECK(IsObjectResumeType(type()));
    return js_object_.descriptors;
  }
References v8::internal::DCHECK(), IsObjectResumeType(), js_object_, and type().
Referenced by v8::internal::FastJsonStringifier< Char >::SerializeObject().
object_in_object_properties()
uint8_t v8::internal::ContinuationRecord::object_in_object_properties () const [inline]
Definition at line 2067 of file json-stringifier.cc.
                                              {
    DCHECK(IsObjectResumeType(type()));
    return js_object_.in_object_properties;
  }
References v8::internal::DCHECK(), IsObjectResumeType(), js_object_, and type().
Referenced by v8::internal::FastJsonStringifier< Char >::SerializeObject().
object_in_object_properties_start()
uint8_t v8::internal::ContinuationRecord::object_in_object_properties_start () const [inline]
Definition at line 2071 of file json-stringifier.cc.
                                                    {
    DCHECK(IsObjectResumeType(type()));
    return js_object_.in_object_properties_start;
  }
References v8::internal::DCHECK(), IsObjectResumeType(), js_object_, and type().
Referenced by v8::internal::FastJsonStringifier< Char >::SerializeObject().
object_key()
Tagged<String> v8::internal::ContinuationRecord::object_key () const [inline]
Definition at line 2045 of file json-stringifier.cc.
                                    {
    DCHECK_EQ(type(), Type::kObjectKey);
    return Cast<String>(object_);
  }
References DCHECK_EQ, object_, and type().
Referenced by v8::internal::requires().
object_key_comma()
bool v8::internal::ContinuationRecord::object_key_comma () const [inline]
Definition at line 2080 of file json-stringifier.cc.
                                {
    DCHECK_EQ(type(), Type::kObjectKey);
    return object_key_.comma;
  }
References DCHECK_EQ, object_key_, and type().
Referenced by v8::internal::requires().
object_nof_descriptors()
uint16_t v8::internal::ContinuationRecord::object_nof_descriptors () const [inline]
Definition at line 2063 of file json-stringifier.cc.
                                          {
    DCHECK(IsObjectResumeType(type()));
    return js_object_.nof_descriptors;
  }
References v8::internal::DCHECK(), IsObjectResumeType(), js_object_, and type().
Referenced by v8::internal::FastJsonStringifier< Char >::SerializeObject().
simple_object()
Tagged<JSAny> v8::internal::ContinuationRecord::simple_object () const [inline]
Definition at line 2029 of file json-stringifier.cc.
                                      {
    DCHECK_EQ(type(), Type::kSimpleObject);
    return Cast<JSAny>(object_);
  }
References DCHECK_EQ, object_, and type().
Referenced by v8::internal::requires().
type()
Type v8::internal::ContinuationRecord::type () const [inline]
Definition at line 2027 of file json-stringifier.cc.
{ return type_; }
References type_.
Referenced by array_elements(), array_index(), array_length(), v8::internal::FastJsonStringifier< Char >::CheckCycle(), ForJSObjectResume(), IsArrayResumeType(), IsObjectResumeType(), js_array(), js_object(), object_descriptor_idx(), object_descriptors(), object_in_object_properties(), object_in_object_properties_start(), object_key(), object_key_comma(), object_nof_descriptors(), v8::internal::requires(), v8::internal::FastJsonStringifier< Char >::SerializeObject(), and simple_object().
Member Data Documentation
union { ... } [private]
comma
bool v8::internal::ContinuationRecord::comma
Definition at line 2154 of file json-stringifier.cc.
Referenced by ForObjectKey().
descriptor_idx
uint16_t v8::internal::ContinuationRecord::descriptor_idx
Definition at line 2147 of file json-stringifier.cc.
Referenced by ContinuationRecord(), and ForJSObjectResume().
descriptors
Tagged<DescriptorArray> v8::internal::ContinuationRecord::descriptors
Definition at line 2151 of file json-stringifier.cc.
Referenced by ContinuationRecord(), and ForJSObjectResume().
in_object_properties
uint8_t v8::internal::ContinuationRecord::in_object_properties
Definition at line 2149 of file json-stringifier.cc.
Referenced by ContinuationRecord(), and ForJSObjectResume().
in_object_properties_start
uint8_t v8::internal::ContinuationRecord::in_object_properties_start
Definition at line 2150 of file json-stringifier.cc.
Referenced by ContinuationRecord(), and ForJSObjectResume().
index
uint32_t v8::internal::ContinuationRecord::index
Definition at line 2143 of file json-stringifier.cc.
Referenced by ContinuationRecord(), and ForJSArrayResume().
struct { ... } v8::internal::ContinuationRecord::js_array_
Referenced by array_index(), and array_length().
struct { ... } v8::internal::ContinuationRecord::js_object_
Referenced by object_descriptor_idx(), object_descriptors(), object_in_object_properties(), object_in_object_properties_start(), and object_nof_descriptors().
length
uint32_t v8::internal::ContinuationRecord::length
Definition at line 2144 of file json-stringifier.cc.
Referenced by ContinuationRecord(), and ForJSArrayResume().
nof_descriptors
uint16_t v8::internal::ContinuationRecord::nof_descriptors
Definition at line 2148 of file json-stringifier.cc.
Referenced by ContinuationRecord(), and ForJSObjectResume().
object_
Tagged<ObjectT> v8::internal::ContinuationRecord::object_ [private]
Definition at line 2140 of file json-stringifier.cc.
Referenced by array_elements(), js_array(), js_object(), object(), object_key(), and simple_object().
struct { ... } v8::internal::ContinuationRecord::object_key_
Referenced by object_key_comma().
type_
Type v8::internal::ContinuationRecord::type_ [private]
Definition at line 2139 of file json-stringifier.cc.
Referenced by type().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/json/json-stringifier.cc