v8::internal::compiler::MachineOperatorBuilder::AlignmentRequirements Class Reference
#include <machine-operator.h>
Public Types
enum UnalignedAccessSupport { kNoSupport
, kSomeSupport
, kFullSupport
 }
Public Member Functions
bool IsUnalignedLoadSupported (MachineRepresentation rep) const
bool IsUnalignedStoreSupported (MachineRepresentation rep) const
bool HasFullUnalignedSupport () const
Static Public Member Functions
static AlignmentRequirements FullUnalignedAccessSupport ()
static AlignmentRequirements NoUnalignedAccessSupport ()
static AlignmentRequirements SomeUnalignedAccessUnsupported (base::EnumSet< MachineRepresentation > unalignedLoadUnsupportedTypes, base::EnumSet< MachineRepresentation > unalignedStoreUnsupportedTypes)
Private Member Functions
AlignmentRequirements (AlignmentRequirements::UnalignedAccessSupport unalignedAccessSupport, base::EnumSet< MachineRepresentation > unalignedLoadUnsupportedTypes=base::EnumSet< MachineRepresentation >(), base::EnumSet< MachineRepresentation > unalignedStoreUnsupportedTypes=base::EnumSet< MachineRepresentation >())
bool IsUnalignedSupported (base::EnumSet< MachineRepresentation > unsupported, MachineRepresentation rep) const
Private Attributes
const AlignmentRequirements::UnalignedAccessSupport unalignedSupport_
const base::EnumSet< MachineRepresentation > unalignedLoadUnsupportedTypes_
const base::EnumSet< MachineRepresentation > unalignedStoreUnsupportedTypes_
Detailed Description
Definition at line 428 of file machine-operator.h.
Member Enumeration Documentation
UnalignedAccessSupport
enum v8::internal::compiler::MachineOperatorBuilder::AlignmentRequirements::UnalignedAccessSupport
Enumerator
kNoSupport
kSomeSupport
kFullSupport
Definition at line 430 of file machine-operator.h.
{ kNoSupport, kSomeSupport, kFullSupport };
Constructor & Destructor Documentation
AlignmentRequirements()
v8::internal::compiler::MachineOperatorBuilder::AlignmentRequirements::AlignmentRequirements (AlignmentRequirements::UnalignedAccessSupport unalignedAccessSupport, base::EnumSet< MachineRepresentation > unalignedLoadUnsupportedTypes = base::EnumSet<MachineRepresentation>(), base::EnumSet< MachineRepresentation > unalignedStoreUnsupportedTypes = base::EnumSet<MachineRepresentation>()) [inline], [explicit], [private]
Definition at line 458 of file machine-operator.h.
        : unalignedSupport_(unalignedAccessSupport),
          unalignedLoadUnsupportedTypes_(unalignedLoadUnsupportedTypes),
          unalignedStoreUnsupportedTypes_(unalignedStoreUnsupportedTypes) {}
Member Function Documentation
FullUnalignedAccessSupport()
static AlignmentRequirements v8::internal::compiler::MachineOperatorBuilder::AlignmentRequirements::FullUnalignedAccessSupport () [inline], [static]
Definition at line 444 of file machine-operator.h.
                                                              {
      return AlignmentRequirements(kFullSupport);
    }
HasFullUnalignedSupport()
bool v8::internal::compiler::MachineOperatorBuilder::AlignmentRequirements::HasFullUnalignedSupport () const [inline]
Definition at line 440 of file machine-operator.h.
                                         {
      return unalignedSupport_ == kFullSupport;
    }
Referenced by v8::internal::compiler::turboshaft::SupportedOperations::HasFullUnalignedSupport().
IsUnalignedLoadSupported()
bool v8::internal::compiler::MachineOperatorBuilder::AlignmentRequirements::IsUnalignedLoadSupported (MachineRepresentation rep) const [inline]
Definition at line 432 of file machine-operator.h.
                                                                   {
      return IsUnalignedSupported(unalignedLoadUnsupportedTypes_, rep);
    }
Referenced by v8::internal::compiler::turboshaft::SupportedOperations::IsUnalignedLoadSupported(), and v8::internal::compiler::InstructionSelector::VisitNode().
IsUnalignedStoreSupported()
bool v8::internal::compiler::MachineOperatorBuilder::AlignmentRequirements::IsUnalignedStoreSupported (MachineRepresentation rep) const [inline]
Definition at line 436 of file machine-operator.h.
                                                                    {
      return IsUnalignedSupported(unalignedStoreUnsupportedTypes_, rep);
    }
Referenced by v8::internal::compiler::turboshaft::SupportedOperations::IsUnalignedStoreSupported().
IsUnalignedSupported()
bool v8::internal::compiler::MachineOperatorBuilder::AlignmentRequirements::IsUnalignedSupported (base::EnumSet< MachineRepresentation > unsupported, MachineRepresentation rep) const [inline], [private]
Definition at line 468 of file machine-operator.h.
                                                               {
      // All accesses of bytes in memory are aligned.
      DCHECK_NE(MachineRepresentation::kWord8, rep);
      switch (unalignedSupport_) {
        case kFullSupport:
          return true;
        case kNoSupport:
          return false;
        case kSomeSupport:
          return !unsupported.contains(rep);
      }
      UNREACHABLE();
    }
References v8::base::EnumSet< E, T >::contains(), DCHECK_NE, v8::internal::kWord8, and v8::internal::UNREACHABLE().
NoUnalignedAccessSupport()
static AlignmentRequirements v8::internal::compiler::MachineOperatorBuilder::AlignmentRequirements::NoUnalignedAccessSupport () [inline], [static]
Definition at line 447 of file machine-operator.h.
                                                            {
      return AlignmentRequirements(kNoSupport);
    }
SomeUnalignedAccessUnsupported()
static AlignmentRequirements v8::internal::compiler::MachineOperatorBuilder::AlignmentRequirements::SomeUnalignedAccessUnsupported (base::EnumSet< MachineRepresentation > unalignedLoadUnsupportedTypes, base::EnumSet< MachineRepresentation > unalignedStoreUnsupportedTypes) [inline], [static]
Definition at line 450 of file machine-operator.h.
                                                                           {
      return AlignmentRequirements(kSomeSupport, unalignedLoadUnsupportedTypes,
                                   unalignedStoreUnsupportedTypes);
    }
Referenced by v8::internal::compiler::InstructionSelector::AlignmentRequirements().
Member Data Documentation
unalignedLoadUnsupportedTypes_
const base::EnumSet<MachineRepresentation> v8::internal::compiler::MachineOperatorBuilder::AlignmentRequirements::unalignedLoadUnsupportedTypes_ [private]
Definition at line 484 of file machine-operator.h.
unalignedStoreUnsupportedTypes_
const base::EnumSet<MachineRepresentation> v8::internal::compiler::MachineOperatorBuilder::AlignmentRequirements::unalignedStoreUnsupportedTypes_ [private]
Definition at line 485 of file machine-operator.h.
unalignedSupport_
const AlignmentRequirements::UnalignedAccessSupport v8::internal::compiler::MachineOperatorBuilder::AlignmentRequirements::unalignedSupport_ [private]
Definition at line 483 of file machine-operator.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/machine-operator.h