v8::internal::AssemblerRISCVB Class Reference
#include <extension-riscv-b.h>
Public Member Functions
void sh1add (Register rd, Register rs1, Register rs2)
void sh2add (Register rd, Register rs1, Register rs2)
void sh3add (Register rd, Register rs1, Register rs2)
void andn (Register rd, Register rs1, Register rs2)
void orn (Register rd, Register rs1, Register rs2)
void xnor (Register rd, Register rs1, Register rs2)
void clz (Register rd, Register rs)
void ctz (Register rd, Register rs)
void cpop (Register rd, Register rs)
void max (Register rd, Register rs1, Register rs2)
void maxu (Register rd, Register rs1, Register rs2)
void min (Register rd, Register rs1, Register rs2)
void minu (Register rd, Register rs1, Register rs2)
void sextb (Register rd, Register rs)
void sexth (Register rd, Register rs)
void zexth (Register rd, Register rs)
void rol (Register rd, Register rs1, Register rs2)
void ror (Register rd, Register rs1, Register rs2)
void rori (Register rd, Register rs1, uint8_t shamt)
void orcb (Register rd, Register rs)
void rev8 (Register rd, Register rs)
void bclr (Register rd, Register rs1, Register rs2)
void bclri (Register rd, Register rs1, uint8_t shamt)
void bext (Register rd, Register rs1, Register rs2)
void bexti (Register rd, Register rs1, uint8_t shamt)
void binv (Register rd, Register rs1, Register rs2)
void binvi (Register rd, Register rs1, uint8_t shamt)
void bset (Register rd, Register rs1, Register rs2)
void bseti (Register rd, Register rs1, uint8_t shamt)
Additional Inherited Members
Detailed Description
Definition at line 15 of file extension-riscv-b.h.
Member Function Documentation
andn()
void v8::internal::AssemblerRISCVB::andn (Register rd, Register rs1, Register rs2)
Definition at line 39 of file extension-riscv-b.cc.
                                                                  {
  GenInstrALU_rr(0b0100000, 0b111, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_rr().
bclr()
void v8::internal::AssemblerRISCVB::bclr (Register rd, Register rs1, Register rs2)
Definition at line 141 of file extension-riscv-b.cc.
                                                                  {
  GenInstrALU_rr(0b0100100, 0b001, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_rr().
bclri()
void v8::internal::AssemblerRISCVB::bclri (Register rd, Register rs1, uint8_t shamt)
Definition at line 145 of file extension-riscv-b.cc.
                                                                   {
#ifdef V8_TARGET_ARCH_RISCV64
  GenInstrIShift(0b010010, 0b001, OP_IMM, rd, rs, shamt);
#else
  GenInstrIShiftW(0b0100100, 0b001, OP_IMM, rd, rs, shamt);
#endif
}
References v8::internal::AssemblerRiscvBase::GenInstrIShift(), v8::internal::AssemblerRiscvBase::GenInstrIShiftW(), and v8::internal::OP_IMM.
bext()
void v8::internal::AssemblerRISCVB::bext (Register rd, Register rs1, Register rs2)
Definition at line 152 of file extension-riscv-b.cc.
                                                                  {
  GenInstrALU_rr(0b0100100, 0b101, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_rr().
bexti()
void v8::internal::AssemblerRISCVB::bexti (Register rd, Register rs1, uint8_t shamt)
Definition at line 155 of file extension-riscv-b.cc.
                                                                    {
#ifdef V8_TARGET_ARCH_RISCV64
  GenInstrIShift(0b010010, 0b101, OP_IMM, rd, rs1, shamt);
#else
  GenInstrIShiftW(0b0100100, 0b101, OP_IMM, rd, rs1, shamt);
#endif
}
References v8::internal::AssemblerRiscvBase::GenInstrIShift(), v8::internal::AssemblerRiscvBase::GenInstrIShiftW(), and v8::internal::OP_IMM.
binv()
void v8::internal::AssemblerRISCVB::binv (Register rd, Register rs1, Register rs2)
Definition at line 162 of file extension-riscv-b.cc.
                                                                  {
  GenInstrALU_rr(0b0110100, 0b001, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_rr().
binvi()
void v8::internal::AssemblerRISCVB::binvi (Register rd, Register rs1, uint8_t shamt)
Definition at line 165 of file extension-riscv-b.cc.
                                                                    {
#ifdef V8_TARGET_ARCH_RISCV64
  GenInstrIShift(0b011010, 0b001, OP_IMM, rd, rs1, shamt);
#else
  GenInstrIShiftW(0b0110100, 0b001, OP_IMM, rd, rs1, shamt);
#endif
}
References v8::internal::AssemblerRiscvBase::GenInstrIShift(), v8::internal::AssemblerRiscvBase::GenInstrIShiftW(), and v8::internal::OP_IMM.
bset()
void v8::internal::AssemblerRISCVB::bset (Register rd, Register rs1, Register rs2)
Definition at line 172 of file extension-riscv-b.cc.
                                                                  {
  GenInstrALU_rr(0b0010100, 0b001, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_rr().
bseti()
void v8::internal::AssemblerRISCVB::bseti (Register rd, Register rs1, uint8_t shamt)
Definition at line 175 of file extension-riscv-b.cc.
                                                                    {
#ifdef V8_TARGET_ARCH_RISCV64
  GenInstrIShift(0b001010, 0b001, OP_IMM, rd, rs1, shamt);
#else
  GenInstrIShiftW(0b0010100, 0b001, OP_IMM, rd, rs1, shamt);
#endif
}
References v8::internal::AssemblerRiscvBase::GenInstrIShift(), v8::internal::AssemblerRiscvBase::GenInstrIShiftW(), and v8::internal::OP_IMM.
clz()
void v8::internal::AssemblerRISCVB::clz (Register rd, Register rs)
Definition at line 49 of file extension-riscv-b.cc.
                                                  {
  GenInstrIShiftW(0b0110000, 0b001, OP_IMM, rd, rs, 0);
}
References v8::internal::AssemblerRiscvBase::GenInstrIShiftW(), and v8::internal::OP_IMM.
cpop()
void v8::internal::AssemblerRISCVB::cpop (Register rd, Register rs)
Definition at line 55 of file extension-riscv-b.cc.
                                                   {
  GenInstrIShiftW(0b0110000, 0b001, OP_IMM, rd, rs, 2);
}
References v8::internal::AssemblerRiscvBase::GenInstrIShiftW(), and v8::internal::OP_IMM.
Referenced by v8::internal::MacroAssembler::Popcnt32().
ctz()
void v8::internal::AssemblerRISCVB::ctz (Register rd, Register rs)
Definition at line 52 of file extension-riscv-b.cc.
                                                  {
  GenInstrIShiftW(0b0110000, 0b001, OP_IMM, rd, rs, 1);
}
References v8::internal::AssemblerRiscvBase::GenInstrIShiftW(), and v8::internal::OP_IMM.
max()
void v8::internal::AssemblerRISCVB::max (Register rd, Register rs1, Register rs2)
Definition at line 70 of file extension-riscv-b.cc.
                                                                 {
  GenInstrALU_rr(0b0000101, 0b110, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_rr().
maxu()
void v8::internal::AssemblerRISCVB::maxu (Register rd, Register rs1, Register rs2)
Definition at line 73 of file extension-riscv-b.cc.
                                                                  {
  GenInstrALU_rr(0b0000101, 0b111, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_rr().
min()
void v8::internal::AssemblerRISCVB::min (Register rd, Register rs1, Register rs2)
Definition at line 76 of file extension-riscv-b.cc.
                                                                 {
  GenInstrALU_rr(0b0000101, 0b100, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_rr().
minu()
void v8::internal::AssemblerRISCVB::minu (Register rd, Register rs1, Register rs2)
Definition at line 79 of file extension-riscv-b.cc.
                                                                  {
  GenInstrALU_rr(0b0000101, 0b101, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_rr().
orcb()
void v8::internal::AssemblerRISCVB::orcb (Register rd, Register rs)
Definition at line 105 of file extension-riscv-b.cc.
                                                   {
  GenInstrI(0b101, OP_IMM, rd, rs, 0b001010000111);
}
References v8::internal::AssemblerRiscvBase::GenInstrI(), and v8::internal::OP_IMM.
orn()
void v8::internal::AssemblerRISCVB::orn (Register rd, Register rs1, Register rs2)
Definition at line 42 of file extension-riscv-b.cc.
                                                                 {
  GenInstrALU_rr(0b0100000, 0b110, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_rr().
rev8()
void v8::internal::AssemblerRISCVB::rev8 (Register rd, Register rs)
Definition at line 132 of file extension-riscv-b.cc.
                                                   {
#ifdef V8_TARGET_ARCH_RISCV64
  GenInstrI(0b101, OP_IMM, rd, rs, 0b011010111000);
#else
  GenInstrI(0b101, OP_IMM, rd, rs, 0b011010011000);
#endif
}
References v8::internal::AssemblerRiscvBase::GenInstrI(), and v8::internal::OP_IMM.
rol()
void v8::internal::AssemblerRISCVB::rol (Register rd, Register rs1, Register rs2)
Definition at line 97 of file extension-riscv-b.cc.
                                                                 {
  GenInstrR(0b0110000, 0b001, OP, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrR(), and v8::internal::OP.
ror()
void v8::internal::AssemblerRISCVB::ror (Register rd, Register rs1, Register rs2)
Definition at line 101 of file extension-riscv-b.cc.
                                                                 {
  GenInstrR(0b0110000, 0b101, OP, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrR(), and v8::internal::OP.
rori()
void v8::internal::AssemblerRISCVB::rori (Register rd, Register rs1, uint8_t shamt)
Definition at line 109 of file extension-riscv-b.cc.
                                                                   {
#ifdef V8_TARGET_ARCH_RISCV64
  DCHECK(is_uint6(shamt));
  GenInstrI(0b101, OP_IMM, rd, rs1, 0b011000000000 | shamt);
#else
  DCHECK(is_uint5(shamt));
  GenInstrI(0b101, OP_IMM, rd, rs1, 0b011000000000 | shamt);
#endif
}
References v8::internal::DCHECK(), v8::internal::AssemblerRiscvBase::GenInstrI(), and v8::internal::OP_IMM.
sextb()
void v8::internal::AssemblerRISCVB::sextb (Register rd, Register rs)
Definition at line 83 of file extension-riscv-b.cc.
                                                    {
  GenInstrIShiftW(0b0110000, 0b001, OP_IMM, rd, rs, 0b100);
}
References v8::internal::AssemblerRiscvBase::GenInstrIShiftW(), and v8::internal::OP_IMM.
sexth()
void v8::internal::AssemblerRISCVB::sexth (Register rd, Register rs)
Definition at line 86 of file extension-riscv-b.cc.
                                                    {
  GenInstrIShiftW(0b0110000, 0b001, OP_IMM, rd, rs, 0b101);
}
References v8::internal::AssemblerRiscvBase::GenInstrIShiftW(), and v8::internal::OP_IMM.
sh1add()
void v8::internal::AssemblerRISCVB::sh1add (Register rd, Register rs1, Register rs2)
Definition at line 11 of file extension-riscv-b.cc.
                                                                    {
  GenInstrALU_rr(0b0010000, 0b010, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_rr().
Referenced by v8::internal::MacroAssembler::CalcScaledAddress().
sh2add()
void v8::internal::AssemblerRISCVB::sh2add (Register rd, Register rs1, Register rs2)
Definition at line 14 of file extension-riscv-b.cc.
                                                                    {
  GenInstrALU_rr(0b0010000, 0b100, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_rr().
Referenced by v8::internal::MacroAssembler::CalcScaledAddress().
sh3add()
void v8::internal::AssemblerRISCVB::sh3add (Register rd, Register rs1, Register rs2)
Definition at line 17 of file extension-riscv-b.cc.
                                                                    {
  GenInstrALU_rr(0b0010000, 0b110, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_rr().
Referenced by v8::internal::MacroAssembler::CalcScaledAddress().
xnor()
void v8::internal::AssemblerRISCVB::xnor (Register rd, Register rs1, Register rs2)
Definition at line 45 of file extension-riscv-b.cc.
                                                                  {
  GenInstrALU_rr(0b0100000, 0b100, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_rr().
zexth()
void v8::internal::AssemblerRISCVB::zexth (Register rd, Register rs)
Definition at line 89 of file extension-riscv-b.cc.
                                                    {
#ifdef V8_TARGET_ARCH_RISCV64
  GenInstrALUW_rr(0b0000100, 0b100, rd, rs, zero_reg);
#else
  GenInstrALU_rr(0b0000100, 0b100, rd, rs, zero_reg);
#endif
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_rr(), and v8::internal::AssemblerRiscvBase::GenInstrALUW_rr().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/riscv/extension-riscv-b.h
/mnt/V8SourceCode/src/codegen/riscv/extension-riscv-b.cc