v8::Context::BackupIncumbentScope Class Reference
Stack-allocated class to support the backup incumbent settings object stack.
#include <v8-context.h>
Public Member Functions
BackupIncumbentScope (Local< Context > backup_incumbent_context)
|backup_incumbent_context| is pushed onto the backup incumbent settings object stack.
~BackupIncumbentScope ()
Private Member Functions
uintptr_t JSStackComparableAddressPrivate () const
Private Attributes
Local< Context > backup_incumbent_context_
uintptr_t js_stack_comparable_address_ = 0
const BackupIncumbentScope * prev_ = nullptr
Friends
class internal::Isolate
Detailed Description
Stack-allocated class to support the backup incumbent settings object stack.
 https://html.spec.whatwg.org/multipage/webappapis.html#backup-incumbent-settings-object-stack
Definition at line 402 of file v8-context.h.
Constructor & Destructor Documentation
BackupIncumbentScope()
v8::Context::BackupIncumbentScope::BackupIncumbentScope (Local< Context > backup_incumbent_context) [explicit]
|backup_incumbent_context| is pushed onto the backup incumbent settings object stack.
Definition at line 855 of file api.cc.
    : backup_incumbent_context_(backup_incumbent_context) {
  DCHECK(!backup_incumbent_context_.IsEmpty());
  i::Isolate* i_isolate = i::Isolate::Current();
  js_stack_comparable_address_ =
      i::SimulatorStack::RegisterJSStackComparableAddress(i_isolate);
  prev_ = i_isolate->top_backup_incumbent_scope();
  i_isolate->set_top_backup_incumbent_scope(this);
  // Enforce slow incumbent computation in order to make it find this
  // BackupIncumbentScope.
  i_isolate->clear_topmost_script_having_context();
}
References backup_incumbent_context_, v8::internal::Isolate::clear_topmost_script_having_context(), v8::internal::Isolate::Current(), DCHECK, v8::api_internal::IndirectHandleBase::IsEmpty(), js_stack_comparable_address_, prev_, v8::internal::SimulatorStack::RegisterJSStackComparableAddress(), v8::internal::Isolate::set_top_backup_incumbent_scope(), and v8::internal::Isolate::top_backup_incumbent_scope().
 BackupIncumbentScope()
v8::Context::BackupIncumbentScope::~BackupIncumbentScope ()
Definition at line 872 of file api.cc.
                                                   {
  i::Isolate* i_isolate = i::Isolate::Current();
  i::SimulatorStack::UnregisterJSStackComparableAddress(i_isolate);
  i_isolate->set_top_backup_incumbent_scope(prev_);
}
References v8::internal::Isolate::Current(), v8::internal::Isolate::set_top_backup_incumbent_scope(), and v8::internal::SimulatorStack::UnregisterJSStackComparableAddress().
Member Function Documentation
JSStackComparableAddressPrivate()
uintptr_t v8::Context::BackupIncumbentScope::JSStackComparableAddressPrivate () const [inline], [private]
Definition at line 414 of file v8-context.h.
                                                      {
      return js_stack_comparable_address_;
    }
Referenced by v8::internal::Isolate::GetIncumbentContextSlow().
Friends And Related Function Documentation
internal::Isolate
friend class internal::Isolate [friend]
Definition at line 412 of file v8-context.h.
Member Data Documentation
backup_incumbent_context_
Local<Context> v8::Context::BackupIncumbentScope::backup_incumbent_context_ [private]
Definition at line 418 of file v8-context.h.
Referenced by BackupIncumbentScope(), and v8::internal::Isolate::GetIncumbentContextSlow().
js_stack_comparable_address_
uintptr_t v8::Context::BackupIncumbentScope::js_stack_comparable_address_ = 0 [private]
Definition at line 419 of file v8-context.h.
Referenced by BackupIncumbentScope().
prev_
const BackupIncumbentScope* v8::Context::BackupIncumbentScope::prev_ = nullptr [private]
Definition at line 420 of file v8-context.h.
Referenced by BackupIncumbentScope().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-context.h
/mnt/V8SourceCode/src/api/api.cc