v8::ScriptOriginOptions Class Reference
The optional attributes of ScriptOrigin.
#include <v8-message.h>
Public Member Functions
ScriptOriginOptions (bool is_shared_cross_origin=false, bool is_opaque=false, bool is_wasm=false, bool is_module=false)
ScriptOriginOptions (int flags)
bool IsSharedCrossOrigin () const
bool IsOpaque () const
bool IsWasm () const
bool IsModule () const
int Flags () const
Private Types
enum { kIsSharedCrossOrigin = 1
, kIsOpaque = 1 << 1
, kIsWasm = 1 << 2
, kIsModule = 1 << 3
 }
Private Attributes
const int flags_
Detailed Description
The optional attributes of ScriptOrigin.
Definition at line 29 of file v8-message.h.
Member Enumeration Documentation
anonymous enum
anonymous enum [private]
Enumerator
kIsSharedCrossOrigin
kIsOpaque
kIsWasm
kIsModule
Definition at line 51 of file v8-message.h.
       {
    kIsSharedCrossOrigin = 1,
    kIsOpaque = 1 << 1,
    kIsWasm = 1 << 2,
    kIsModule = 1 << 3
  };
Constructor & Destructor Documentation
ScriptOriginOptions() [1/2]
v8::ScriptOriginOptions::ScriptOriginOptions (bool is_shared_cross_origin = false, bool is_opaque = false, bool is_wasm = false, bool is_module = false) [inline]
Definition at line 31 of file v8-message.h.
      : flags_((is_shared_cross_origin ? kIsSharedCrossOrigin : 0) |
               (is_wasm ? kIsWasm : 0) | (is_opaque ? kIsOpaque : 0) |
               (is_module ? kIsModule : 0)) {}
ScriptOriginOptions() [2/2]
v8::ScriptOriginOptions::ScriptOriginOptions (int flags) [inline]
Definition at line 37 of file v8-message.h.
      : flags_(flags &
               (kIsSharedCrossOrigin | kIsOpaque | kIsWasm | kIsModule)) {}
Member Function Documentation
Flags()
int v8::ScriptOriginOptions::Flags () const [inline]
Definition at line 48 of file v8-message.h.
{ return flags_; }
References flags_.
Referenced by v8::internal::ScriptCacheKey::MatchesScript(), v8::internal::anonymous_namespace{compilation-cache-table.cc}::ScriptHash(), and v8::internal::Script::set_origin_options().
IsModule()
bool v8::ScriptOriginOptions::IsModule () const [inline]
Definition at line 46 of file v8-message.h.
{ return (flags_ & kIsModule) != 0; }
References flags_, and kIsModule.
Referenced by v8::internal::anonymous_namespace{compiler.cc}::CanBackgroundCompile(), v8::ScriptCompiler::Compile(), v8::ScriptCompiler::CompileModule(), v8::ScriptCompiler::CompileUnboundScript(), v8::internal::BackgroundCompileTask::FinalizeScript(), v8::debug::GetScriptOrigin(), v8::GetScriptOriginForScript(), v8::internal::anonymous_namespace{compiler.cc}::GetSharedFunctionInfoForScriptImpl(), v8::internal::SerializedCodeData::SourceHash(), and v8::internal::anonymous_namespace{compiler.cc}::StressBackgroundCompileThread::StressBackgroundCompileThread().
IsOpaque()
bool v8::ScriptOriginOptions::IsOpaque () const [inline]
Definition at line 44 of file v8-message.h.
{ return (flags_ & kIsOpaque) != 0; }
References flags_, and kIsOpaque.
Referenced by v8::debug::GetScriptOrigin(), and v8::GetScriptOriginForScript().
IsSharedCrossOrigin()
bool v8::ScriptOriginOptions::IsSharedCrossOrigin () const [inline]
Definition at line 41 of file v8-message.h.
                                   {
    return (flags_ & kIsSharedCrossOrigin) != 0;
  }
References flags_, and kIsSharedCrossOrigin.
Referenced by v8::debug::GetScriptOrigin(), and v8::GetScriptOriginForScript().
IsWasm()
bool v8::ScriptOriginOptions::IsWasm () const [inline]
Definition at line 45 of file v8-message.h.
{ return (flags_ & kIsWasm) != 0; }
References flags_, and kIsWasm.
Referenced by v8::internal::Compiler::GetSharedFunctionInfoForStreamedScript().
Member Data Documentation
flags_
const int v8::ScriptOriginOptions::flags_ [private]
Definition at line 57 of file v8-message.h.
Referenced by Flags(), IsModule(), IsOpaque(), IsSharedCrossOrigin(), and IsWasm().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/v8-message.h