v8::internal::PointerToIndexHashMap< Type > Class Template Reference
#include <address-map.h>
Public Types
using Entry = base::TemplateHashMapEntry< uintptr_t, uint32_t >
Public Member Functions
void Set (Type value, uint32_t index)
Maybe< uint32_t > Get (Type value) const
Private Member Functions
uintptr_t Key (Address value)
uintptr_t Key (Tagged< HeapObject > value)
Static Private Member Functions
static uintptr_t Key (Type value)
static uint32_t Hash (uintptr_t key)
Additional Inherited Members
Detailed Description
template<typename Type>
class v8::internal::PointerToIndexHashMap< Type >
Definition at line 17 of file address-map.h.
Member Typedef Documentation
Entry
template<typename Type >
using v8::internal::PointerToIndexHashMap< Type >::Entry = base::TemplateHashMapEntry<uintptr_t, uint32_t>
Definition at line 22 of file address-map.h.
Member Function Documentation
Get()
template<typename Type >
Maybe<uint32_t> v8::internal::PointerToIndexHashMap< Type >::Get (Type value) const [inline]
Definition at line 29 of file address-map.h.
                                               {
    uintptr_t key = Key(value);
    Entry* entry = Lookup(key, Hash(key));
    if (entry == nullptr) return Nothing<uint32_t>();
    return Just(entry->value);
  }
References v8::internal::PointerToIndexHashMap< Type >::Hash(), v8::Just(), v8::internal::key, v8::internal::PointerToIndexHashMap< Type >::Key(), v8::base::TemplateHashMapImpl< uintptr_t, uint32_t, base::KeyEqualityMatcher< intptr_t >, base::DefaultAllocationPolicy >::Lookup(), v8::base::TemplateHashMapEntry< Key, Value >::value, and v8::internal::value.
Referenced by v8::internal::ExternalReferenceEncoder::Encode(), v8::internal::ExternalReferenceEncoder::ExternalReferenceEncoder(), v8::internal::ExternalReferenceEncoder::NameOfAddress(), v8::internal::RootIndexMap::RootIndexMap(), and v8::internal::ExternalReferenceEncoder::TryEncode().
Hash()
template<typename Type >
static uint32_t v8::internal::PointerToIndexHashMap< Type >::Hash (uintptr_t key) [inline], [static], [private]
Definition at line 39 of file address-map.h.
{ return static_cast<uint32_t>(key); }
References v8::internal::key.
Referenced by v8::internal::PointerToIndexHashMap< Type >::Get(), and v8::internal::PointerToIndexHashMap< Type >::Set().
Key() [1/3]
uintptr_t v8::internal::PointerToIndexHashMap< Address >::Key (Address value) [inline], [private]
Definition at line 43 of file address-map.h.
                                                                  {
  return static_cast<uintptr_t>(value);
}
References v8::internal::value.
Key() [2/3]
uintptr_t v8::internal::PointerToIndexHashMap< Tagged< HeapObject > >::Key (Tagged< HeapObject > value) [inline], [private]
Definition at line 48 of file address-map.h.
                              {
  return value.ptr();
}
References v8::internal::value.
Key() [3/3]
template<typename Type >
static uintptr_t v8::internal::PointerToIndexHashMap< Type >::Key (Type value) [inline], [static], [private]
Referenced by v8::internal::PointerToIndexHashMap< Type >::Get(), and v8::internal::PointerToIndexHashMap< Type >::Set().
Set()
template<typename Type >
void v8::internal::PointerToIndexHashMap< Type >::Set (Type value, uint32_t index) [inline]
Definition at line 24 of file address-map.h.
                                              {
    uintptr_t key = Key(value);
    LookupOrInsert(key, Hash(key))->value = index;
  }
References v8::internal::PointerToIndexHashMap< Type >::Hash(), v8::internal::index, v8::internal::key, v8::internal::PointerToIndexHashMap< Type >::Key(), v8::base::TemplateHashMapImpl< uintptr_t, uint32_t, base::KeyEqualityMatcher< intptr_t >, base::DefaultAllocationPolicy >::LookupOrInsert(), v8::base::TemplateHashMapEntry< Key, Value >::value, and v8::internal::value.
Referenced by v8::internal::ExternalReferenceEncoder::ExternalReferenceEncoder(), and v8::internal::RootIndexMap::RootIndexMap().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/utils/address-map.h