v8::CppHeapExternal Class Reference
A JavaScript value that wraps a cppgc::GarbageCollected<T> object allocated on the managed C++ heap (CppHeap).
#include <v8-cpp-heap-external.h>
Public Member Functions
template<typename T >
T * Value (Isolate *isolate, CppHeapPointerTagRange tag_range) const
Static Public Member Functions
template<typename T >
static Local< CppHeapExternal > New (Isolate *isolate, T *value, CppHeapPointerTag tag)
static CppHeapExternal * Cast (Data *data)
Private Member Functions
void * ValueImpl (Isolate *, CppHeapPointerTagRange tag_range) const
Static Private Member Functions
static void CheckCast (v8::Data *obj)
static Local< CppHeapExternal > NewImpl (Isolate *isolate, void *value, CppHeapPointerTag tag)
Detailed Description
A JavaScript value that wraps a cppgc::GarbageCollected<T> object allocated on the managed C++ heap (CppHeap).
This type of value is mainly used to associate C++ data structures which aren't exposed to JavaScript with JavaScript objects.
Definition at line 23 of file v8-cpp-heap-external.h.
Member Function Documentation
Cast()
static CppHeapExternal* v8::CppHeapExternal::Cast (Data * data) [inline], [static]
Definition at line 33 of file v8-cpp-heap-external.h.
                                                     {
#ifdef V8_ENABLE_CHECKS
    CheckCast(data);
#endif
    return static_cast<CppHeapExternal*>(data);
  }
CheckCast()
void v8::CppHeapExternal::CheckCast (v8::Data * obj) [static], [private]
Definition at line 4007 of file api.cc.
                                              {
  Utils::ApiCheck(that->IsCppHeapExternal(), "v8::CppHeapExternal::Cast",
                  "Value is not a CppHeapExternal");
}
References v8::Utils::ApiCheck(), and v8::Data::IsCppHeapExternal().
New()
template<typename T >
static Local<CppHeapExternal> v8::CppHeapExternal::New (Isolate * isolate, T * value, CppHeapPointerTag tag) [inline], [static]
Definition at line 26 of file v8-cpp-heap-external.h.
                                                           {
    static_assert(cppgc::IsGarbageCollectedTypeV<T>,
                  "Object must be of type GarbageCollected.");
    return NewImpl(isolate, value, tag);
  }
References v8::internal::value.
NewImpl()
Local< CppHeapExternal > v8::CppHeapExternal::NewImpl (Isolate * isolate, void * value, CppHeapPointerTag tag) [static], [private]
Definition at line 7455 of file api.cc.
                                                                           {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  ApiRuntimeCallStatsScope rcs_scope(i_isolate,
                                     RCCId::kAPI_CppHeapExternal_New);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::DirectHandle<i::CppHeapExternalObject> external =
      i_isolate->factory()->NewCppHeapExternal();
  i::CppHeapObjectWrapper(*external).SetCppHeapWrappable(i_isolate, value, tag);
  return Utils::CppHeapExternalToLocal(external);
}
References v8::internal::Isolate::factory(), v8::internal::Factory::NewCppHeapExternal(), v8::internal::CppHeapObjectWrapper::SetCppHeapWrappable(), and v8::internal::value.
Value()
template<typename T >
T* v8::CppHeapExternal::Value (Isolate * isolate, CppHeapPointerTagRange tag_range) const [inline]
Definition at line 41 of file v8-cpp-heap-external.h.
                                                                     {
    static_assert(cppgc::IsGarbageCollectedTypeV<T>,
                  "Object must be of type GarbageCollected.");
    return static_cast<T*>(ValueImpl(isolate, tag_range));
  }
ValueImpl()
void * v8::CppHeapExternal::ValueImpl (v8::Isolate * isolate, CppHeapPointerTagRange tag_range) const [private]
Definition at line 7468 of file api.cc.
                                                                         {
  DCHECK_LE(tag_range.lower_bound, tag_range.upper_bound);
  auto self = Utils::OpenDirectHandle(this);
  return i::CppHeapObjectWrapper(*self).GetCppHeapWrappable(
      reinterpret_cast<i::Isolate*>(isolate), tag_range);
}
References DCHECK_LE, v8::internal::CppHeapObjectWrapper::GetCppHeapWrappable(), v8::CppHeapPointerTagRange::lower_bound, v8::Utils::OpenDirectHandle(), and v8::CppHeapPointerTagRange::upper_bound.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-cpp-heap-external.h
/mnt/V8SourceCode/src/api/api.cc