v8::internal::maglev::DeoptFrame Class Reference
#include <maglev-ir.h>
Classes
struct BuiltinContinuationFrameData
struct ConstructInvokeStubFrameData
struct InlinedArgumentsFrameData
struct InterpretedFrameData
Public Types
enum class FrameType { kInterpretedFrame
, kInlinedArgumentsFrame
, kConstructInvokeStubFrame
, kBuiltinContinuationFrame
 }
using FrameData = base::DiscriminatedUnion< FrameType, InterpretedFrameData, InlinedArgumentsFrameData, ConstructInvokeStubFrameData, BuiltinContinuationFrameData >
Public Member Functions
DeoptFrame (FrameData &&data, DeoptFrame *parent)
DeoptFrame (const FrameData &data, DeoptFrame *parent)
FrameType type () const
DeoptFrame * parent ()
const DeoptFrame * parent () const
const InterpretedDeoptFrame & as_interpreted () const
const InlinedArgumentsDeoptFrame & as_inlined_arguments () const
const ConstructInvokeStubDeoptFrame & as_construct_stub () const
const BuiltinContinuationDeoptFrame & as_builtin_continuation () const
InterpretedDeoptFrame & as_interpreted ()
InlinedArgumentsDeoptFrame & as_inlined_arguments ()
ConstructInvokeStubDeoptFrame & as_construct_stub ()
BuiltinContinuationDeoptFrame & as_builtin_continuation ()
bool IsJsFrame () const
const MaglevCompilationUnit & GetCompilationUnit () const
BytecodeOffset GetBytecodeOffset () const
SourcePosition GetSourcePosition () const
compiler::SharedFunctionInfoRef GetSharedFunctionInfo () const
compiler::BytecodeArrayRef GetBytecodeArray () const
VirtualObjectList GetVirtualObjects () const
Protected Member Functions
DeoptFrame (InterpretedFrameData &&data, DeoptFrame *parent)
DeoptFrame (InlinedArgumentsFrameData &&data, DeoptFrame *parent)
DeoptFrame (ConstructInvokeStubFrameData &&data, DeoptFrame *parent)
DeoptFrame (BuiltinContinuationFrameData &&data, DeoptFrame *parent)
Protected Attributes
FrameData data_
DeoptFrame *const parent_
Detailed Description
Definition at line 1511 of file maglev-ir.h.
Member Typedef Documentation
FrameData
using v8::internal::maglev::DeoptFrame::FrameData = base::DiscriminatedUnion< FrameType, InterpretedFrameData, InlinedArgumentsFrameData, ConstructInvokeStubFrameData, BuiltinContinuationFrameData>
Definition at line 1549 of file maglev-ir.h.
Member Enumeration Documentation
FrameType
enum v8::internal::maglev::DeoptFrame::FrameType [strong]
Enumerator
kInterpretedFrame
kInlinedArgumentsFrame
kConstructInvokeStubFrame
kBuiltinContinuationFrame
Definition at line 1513 of file maglev-ir.h.
                       {
    kInterpretedFrame,
    kInlinedArgumentsFrame,
    kConstructInvokeStubFrame,
    kBuiltinContinuationFrame,
  };
Constructor & Destructor Documentation
DeoptFrame() [1/6]
v8::internal::maglev::DeoptFrame::DeoptFrame (FrameData && data, DeoptFrame * parent) [inline]
Definition at line 1553 of file maglev-ir.h.
      : data_(std::move(data)), parent_(parent) {}
DeoptFrame() [2/6]
v8::internal::maglev::DeoptFrame::DeoptFrame (const FrameData & data, DeoptFrame * parent) [inline]
Definition at line 1556 of file maglev-ir.h.
      : data_(data), parent_(parent) {}
DeoptFrame() [3/6]
v8::internal::maglev::DeoptFrame::DeoptFrame (InterpretedFrameData && data, DeoptFrame * parent) [inline], [protected]
Definition at line 1581 of file maglev-ir.h.
      : data_(std::move(data)), parent_(parent) {}
DeoptFrame() [4/6]
v8::internal::maglev::DeoptFrame::DeoptFrame (InlinedArgumentsFrameData && data, DeoptFrame * parent) [inline], [protected]
Definition at line 1583 of file maglev-ir.h.
      : data_(std::move(data)), parent_(parent) {}
DeoptFrame() [5/6]
v8::internal::maglev::DeoptFrame::DeoptFrame (ConstructInvokeStubFrameData && data, DeoptFrame * parent) [inline], [protected]
Definition at line 1585 of file maglev-ir.h.
      : data_(std::move(data)), parent_(parent) {}
DeoptFrame() [6/6]
v8::internal::maglev::DeoptFrame::DeoptFrame (BuiltinContinuationFrameData && data, DeoptFrame * parent) [inline], [protected]
Definition at line 1587 of file maglev-ir.h.
      : data_(std::move(data)), parent_(parent) {}
Member Function Documentation
as_builtin_continuation() [1/2]
BuiltinContinuationDeoptFrame & v8::internal::maglev::DeoptFrame::as_builtin_continuation () [inline]
Definition at line 1751 of file maglev-ir.h.
                                                                          {
  DCHECK_EQ(type(), FrameType::kBuiltinContinuationFrame);
  return static_cast<BuiltinContinuationDeoptFrame&>(*this);
}
References DCHECK_EQ, kBuiltinContinuationFrame, and type().
as_builtin_continuation() [2/2]
const BuiltinContinuationDeoptFrame & v8::internal::maglev::DeoptFrame::as_builtin_continuation () const [inline]
Definition at line 1747 of file maglev-ir.h.
                                          {
  DCHECK_EQ(type(), FrameType::kBuiltinContinuationFrame);
  return static_cast<const BuiltinContinuationDeoptFrame&>(*this);
}
References DCHECK_EQ, kBuiltinContinuationFrame, and type().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildLazyDeopt(), v8::internal::maglev::MaxCallDepthProcessor::ConservativeFrameSize(), GetBytecodeOffset(), IsJsFrame(), and v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::RecursiveBuildDeoptFrame().
as_construct_stub() [1/2]
ConstructInvokeStubDeoptFrame & v8::internal::maglev::DeoptFrame::as_construct_stub () [inline]
Definition at line 1709 of file maglev-ir.h.
                                                                    {
  DCHECK_EQ(type(), FrameType::kConstructInvokeStubFrame);
  return static_cast<ConstructInvokeStubDeoptFrame&>(*this);
}
References DCHECK_EQ, kConstructInvokeStubFrame, and type().
as_construct_stub() [2/2]
const ConstructInvokeStubDeoptFrame & v8::internal::maglev::DeoptFrame::as_construct_stub () const [inline]
Definition at line 1703 of file maglev-ir.h.
          {
  DCHECK_EQ(type(), FrameType::kConstructInvokeStubFrame);
  return static_cast<const ConstructInvokeStubDeoptFrame&>(*this);
}
References DCHECK_EQ, kConstructInvokeStubFrame, and type().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildLazyDeopt(), GetCompilationUnit(), GetSourcePosition(), and v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::RecursiveBuildDeoptFrame().
as_inlined_arguments() [1/2]
InlinedArgumentsDeoptFrame & v8::internal::maglev::DeoptFrame::as_inlined_arguments () [inline]
Definition at line 1669 of file maglev-ir.h.
                                                                    {
  DCHECK_EQ(type(), FrameType::kInlinedArgumentsFrame);
  return static_cast<InlinedArgumentsDeoptFrame&>(*this);
}
References DCHECK_EQ, kInlinedArgumentsFrame, and type().
as_inlined_arguments() [2/2]
const InlinedArgumentsDeoptFrame & v8::internal::maglev::DeoptFrame::as_inlined_arguments () const [inline]
Definition at line 1664 of file maglev-ir.h.
          {
  DCHECK_EQ(type(), FrameType::kInlinedArgumentsFrame);
  return static_cast<const InlinedArgumentsDeoptFrame&>(*this);
}
References DCHECK_EQ, kInlinedArgumentsFrame, and type().
Referenced by v8::internal::maglev::MaglevGraphBuilder::AddInlinedArgumentsToDeoptFrame(), v8::internal::maglev::MaxCallDepthProcessor::ConservativeFrameSize(), GetCompilationUnit(), and v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::RecursiveBuildDeoptFrame().
as_interpreted() [1/2]
InterpretedDeoptFrame & v8::internal::maglev::DeoptFrame::as_interpreted () [inline]
Definition at line 1630 of file maglev-ir.h.
                                                         {
  DCHECK_EQ(type(), FrameType::kInterpretedFrame);
  return static_cast<InterpretedDeoptFrame&>(*this);
}
References DCHECK_EQ, kInterpretedFrame, and type().
as_interpreted() [2/2]
const InterpretedDeoptFrame & v8::internal::maglev::DeoptFrame::as_interpreted () const [inline]
Definition at line 1626 of file maglev-ir.h.
                                                                     {
  DCHECK_EQ(type(), FrameType::kInterpretedFrame);
  return static_cast<const InterpretedDeoptFrame&>(*this);
}
References DCHECK_EQ, kInterpretedFrame, and type().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildLazyDeopt(), v8::internal::maglev::MaxCallDepthProcessor::ConservativeFrameSize(), GetBytecodeOffset(), GetCompilationUnit(), v8::internal::maglev::LazyDeoptInfo::GetFrameForExceptionHandler(), GetSourcePosition(), GetVirtualObjects(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::RecursiveBuildDeoptFrame(), and v8::internal::maglev::MaxCallDepthProcessor::UpdateMaxDeoptedStackSize().
GetBytecodeArray()
compiler::BytecodeArrayRef v8::internal::maglev::DeoptFrame::GetBytecodeArray () const [inline]
Definition at line 1818 of file maglev-ir.h.
                                                                   {
  return GetCompilationUnit().bytecode();
}
References v8::internal::maglev::MaglevCompilationUnit::bytecode(), and GetCompilationUnit().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildSingleDeoptFrame().
GetBytecodeOffset()
BytecodeOffset v8::internal::maglev::DeoptFrame::GetBytecodeOffset () const [inline]
Definition at line 1783 of file maglev-ir.h.
                                                          {
  switch (type()) {
    case DeoptFrame::FrameType::kInterpretedFrame:
      return as_interpreted().bytecode_position();
    case DeoptFrame::FrameType::kInlinedArgumentsFrame:
      DCHECK_NOT_NULL(parent());
      return parent()->GetBytecodeOffset();
    case DeoptFrame::FrameType::kConstructInvokeStubFrame:
      return BytecodeOffset::None();
    case DeoptFrame::FrameType::kBuiltinContinuationFrame:
      return Builtins::GetContinuationBytecodeOffset(
          as_builtin_continuation().builtin_id());
  }
}
References as_builtin_continuation(), as_interpreted(), v8::internal::maglev::InterpretedDeoptFrame::bytecode_position(), DCHECK_NOT_NULL, GetBytecodeOffset(), v8::internal::Builtins::GetContinuationBytecodeOffset(), kBuiltinContinuationFrame, kConstructInvokeStubFrame, kInlinedArgumentsFrame, kInterpretedFrame, v8::internal::BytecodeOffset::None(), parent(), and type().
Referenced by GetBytecodeOffset().
GetCompilationUnit()
const MaglevCompilationUnit & v8::internal::maglev::DeoptFrame::GetCompilationUnit () const [inline]
Definition at line 1770 of file maglev-ir.h.
                                                                         {
  switch (type()) {
    case DeoptFrame::FrameType::kInterpretedFrame:
      return as_interpreted().unit();
    case DeoptFrame::FrameType::kInlinedArgumentsFrame:
      return as_inlined_arguments().unit();
    case DeoptFrame::FrameType::kConstructInvokeStubFrame:
      return as_construct_stub().unit();
    case DeoptFrame::FrameType::kBuiltinContinuationFrame:
      return parent()->GetCompilationUnit();
  }
}
References as_construct_stub(), as_inlined_arguments(), as_interpreted(), GetCompilationUnit(), kBuiltinContinuationFrame, kConstructInvokeStubFrame, kInlinedArgumentsFrame, kInterpretedFrame, parent(), type(), v8::internal::maglev::InterpretedDeoptFrame::unit(), v8::internal::maglev::InlinedArgumentsDeoptFrame::unit(), and v8::internal::maglev::ConstructInvokeStubDeoptFrame::unit().
Referenced by v8::internal::maglev::MaglevInliner::BuildInlineFunction(), GetBytecodeArray(), GetCompilationUnit(), and GetSharedFunctionInfo().
GetSharedFunctionInfo()
compiler::SharedFunctionInfoRef v8::internal::maglev::DeoptFrame::GetSharedFunctionInfo () const [inline]
Definition at line 1813 of file maglev-ir.h.
          {
  return GetCompilationUnit().shared_function_info();
}
References GetCompilationUnit(), and v8::internal::maglev::MaglevCompilationUnit::shared_function_info().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildSingleDeoptFrame().
GetSourcePosition()
SourcePosition v8::internal::maglev::DeoptFrame::GetSourcePosition () const [inline]
Definition at line 1798 of file maglev-ir.h.
                                                          {
  switch (type()) {
    case DeoptFrame::FrameType::kInterpretedFrame:
      return as_interpreted().source_position();
    case DeoptFrame::FrameType::kInlinedArgumentsFrame:
      DCHECK_NOT_NULL(parent());
      return parent()->GetSourcePosition();
    case DeoptFrame::FrameType::kConstructInvokeStubFrame:
      return as_construct_stub().source_position();
    case DeoptFrame::FrameType::kBuiltinContinuationFrame:
      DCHECK_NOT_NULL(parent());
      return parent()->GetSourcePosition();
  }
}
References as_construct_stub(), as_interpreted(), DCHECK_NOT_NULL, GetSourcePosition(), kBuiltinContinuationFrame, kConstructInvokeStubFrame, kInlinedArgumentsFrame, kInterpretedFrame, parent(), v8::internal::maglev::InterpretedDeoptFrame::source_position(), v8::internal::maglev::ConstructInvokeStubDeoptFrame::source_position(), and type().
Referenced by v8::internal::maglev::MaglevInliner::BuildInlineFunction(), and GetSourcePosition().
GetVirtualObjects()
VirtualObjectList v8::internal::maglev::DeoptFrame::GetVirtualObjects () const [inline]
Definition at line 1276 of file maglev-interpreter-frame-state.h.
                                                             {
  if (type() == DeoptFrame::FrameType::kInterpretedFrame) {
    return as_interpreted().frame_state()->virtual_objects();
  }
  DCHECK_NOT_NULL(parent());
  return parent()->GetVirtualObjects();
}
References as_interpreted(), DCHECK_NOT_NULL, v8::internal::maglev::InterpretedDeoptFrame::frame_state(), GetVirtualObjects(), kInterpretedFrame, parent(), type(), and v8::internal::maglev::CompactInterpreterFrameState::virtual_objects().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildEagerDeopt(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildLazyDeopt(), and GetVirtualObjects().
IsJsFrame()
bool v8::internal::maglev::DeoptFrame::IsJsFrame () const [inline]
Definition at line 1756 of file maglev-ir.h.
                                        {
  // This must be in sync with TRANSLATION_JS_FRAME_OPCODE_LIST in
  // translation-opcode.h or bad things happen.
  switch (data_.tag()) {
    case FrameType::kInterpretedFrame:
      return true;
    case FrameType::kBuiltinContinuationFrame:
      return as_builtin_continuation().is_javascript();
    case FrameType::kConstructInvokeStubFrame:
    case FrameType::kInlinedArgumentsFrame:
      return false;
  }
}
References as_builtin_continuation(), data_, v8::internal::maglev::BuiltinContinuationDeoptFrame::is_javascript(), kBuiltinContinuationFrame, kConstructInvokeStubFrame, kInlinedArgumentsFrame, kInterpretedFrame, and v8::base::DiscriminatedUnion< TagEnum, Ts >::tag().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::anonymous_namespace{maglev-code-generator.cc}::GetFrameCount().
parent() [1/2]
DeoptFrame* v8::internal::maglev::DeoptFrame::parent () [inline]
Definition at line 1560 of file maglev-ir.h.
{ return parent_; }
References parent_.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildLazyDeopt(), GetBytecodeOffset(), GetCompilationUnit(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::anonymous_namespace{maglev-code-generator.cc}::GetFrameCount(), v8::internal::maglev::LazyDeoptInfo::GetFrameForExceptionHandler(), GetSourcePosition(), GetVirtualObjects(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::RecursiveBuildDeoptFrame(), and v8::internal::maglev::MaxCallDepthProcessor::UpdateMaxDeoptedStackSize().
parent() [2/2]
const DeoptFrame* v8::internal::maglev::DeoptFrame::parent () const [inline]
Definition at line 1561 of file maglev-ir.h.
{ return parent_; }
References parent_.
type()
FrameType v8::internal::maglev::DeoptFrame::type () const [inline]
Definition at line 1559 of file maglev-ir.h.
{ return data_.tag(); }
References data_, and v8::base::DiscriminatedUnion< TagEnum, Ts >::tag().
Referenced by as_builtin_continuation(), as_construct_stub(), as_inlined_arguments(), as_interpreted(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildLazyDeopt(), v8::internal::maglev::MaxCallDepthProcessor::ConservativeFrameSize(), GetBytecodeOffset(), GetCompilationUnit(), v8::internal::maglev::LazyDeoptInfo::GetFrameForExceptionHandler(), GetSourcePosition(), GetVirtualObjects(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::RecursiveBuildDeoptFrame(), and v8::internal::maglev::MaxCallDepthProcessor::UpdateMaxDeoptedStackSize().
Member Data Documentation
data_
FrameData v8::internal::maglev::DeoptFrame::data_ [protected]
Definition at line 1590 of file maglev-ir.h.
Referenced by v8::internal::maglev::InterpretedDeoptFrame::data(), v8::internal::maglev::InlinedArgumentsDeoptFrame::data(), v8::internal::maglev::ConstructInvokeStubDeoptFrame::data(), v8::internal::maglev::BuiltinContinuationDeoptFrame::data(), IsJsFrame(), and type().
parent_
DeoptFrame* const v8::internal::maglev::DeoptFrame::parent_ [protected]
Definition at line 1591 of file maglev-ir.h.
Referenced by parent().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-interpreter-frame-state.h