v8::internal::MemoryAllocator Class Reference
#include <memory-allocator.h>
Classes
struct MemoryChunkAllocationResult
Public Types
enum class AllocationMode { kRegular
, kUsePool
 }
enum class FreeMode { kImmediately
, kPool
 }
Public Member Functions
V8_EXPORT_PRIVATE MemoryAllocator (Isolate *isolate, v8::PageAllocator *code_page_allocator, v8::PageAllocator *trusted_page_allocator, size_t max_capacity)
V8_EXPORT_PRIVATE void TearDown ()
V8_EXPORT_PRIVATE PageMetadata * AllocatePage (MemoryAllocator::AllocationMode alloc_mode, Space *space, Executability executable)
V8_EXPORT_PRIVATE LargePageMetadata * AllocateLargePage (LargeObjectSpace *space, size_t object_size, Executability executable, AllocationHint hint)
bool ResizeLargePage (LargePageMetadata *page, size_t old_object_size, size_t new_object_size)
ReadOnlyPageMetadata * AllocateReadOnlyPage (ReadOnlySpace *space, Address hint=kNullAddress)
std::unique_ptr<::v8::PageAllocator::SharedMemoryMapping > RemapSharedPage (::v8::PageAllocator::SharedMemory *shared_memory, Address new_address)
V8_EXPORT_PRIVATE void Free (MemoryAllocator::FreeMode mode, MutablePageMetadata *chunk)
void FreeReadOnlyPage (ReadOnlyPageMetadata *chunk)
void FreeLargePagesPooled (std::vector< LargePageMetadata * > pages)
size_t Size () const
size_t SizeExecutable () const
size_t Available () const
bool IsOutsideAllocatedSpace (Address address) const
bool IsOutsideAllocatedSpace (Address address, Executability executable) const
void PartialFreeMemory (MemoryChunkMetadata *chunk, Address start_free, size_t bytes_to_free, Address new_area_end)
v8::PageAllocator * data_page_allocator ()
v8::PageAllocator * code_page_allocator ()
v8::PageAllocator * trusted_page_allocator ()
v8::PageAllocator * page_allocator (AllocationSpace space)
PagePool * pool ()
void UnregisterReadOnlyPage (ReadOnlyPageMetadata *page)
Address HandleAllocationFailure (Executability executable)
V8_EXPORT_PRIVATE const MemoryChunk * LookupChunkContainingAddress (Address addr) const
V8_EXPORT_PRIVATE const MemoryChunk * LookupChunkContainingAddressInSafepoint (Address addr) const
void RecordMemoryChunkCreated (const MemoryChunk *chunk)
void RecordMemoryChunkDestroyed (const MemoryChunk *chunk)
V8_EXPORT_PRIVATE size_t GetPooledChunksCount ()
V8_EXPORT_PRIVATE size_t GetSharedPooledChunksCount ()
V8_EXPORT_PRIVATE size_t GetTotalPooledChunksCount ()
V8_EXPORT_PRIVATE void ReleasePooledChunksImmediately ()
Static Public Member Functions
static void InitializeOncePerProcess ()
static intptr_t GetCommitPageSize ()
static intptr_t GetCommitPageSizeBits ()
static void DeleteMemoryChunk (MutablePageMetadata *metadata)
Private Member Functions
V8_WARN_UNUSED_RESULT std::optional< MemoryChunkAllocationResult > AllocateUninitializedChunk (BaseSpace *space, size_t area_size, Executability executable, PageSize page_size, AllocationHint hint)
V8_WARN_UNUSED_RESULT std::optional< MemoryChunkAllocationResult > AllocateUninitializedChunkAt (BaseSpace *space, size_t area_size, Executability executable, Address hint, PageSize page_size, AllocationHint allocation_hint)
Address AllocateAlignedMemory (size_t chunk_size, size_t area_size, size_t alignment, AllocationSpace space, Executability executable, void *hint, VirtualMemory *controller, PageSize page_size, AllocationHint allocation_hint)
V8_WARN_UNUSED_RESULT bool SetPermissionsOnExecutableMemoryChunk (VirtualMemory *vm, Address start, size_t reserved_size)
void FreeMemoryRegion (v8::PageAllocator *page_allocator, Address addr, size_t size)
void PreFreeMemory (MutablePageMetadata *chunk)
void PerformFreeMemory (MutablePageMetadata *chunk)
std::optional< MemoryChunkAllocationResult > AllocateUninitializedPageFromPool (Space *space)
std::optional< MemoryChunkAllocationResult > TryAllocateUninitializedLargePageFromPool (Space *space, size_t chunk_size)
PageMetadata * InitializePagesInChunk (int chunk_id, int pages_in_chunk, PagedSpace *space)
void UpdateAllocatedSpaceLimits (Address low, Address high, Executability executable)
void UnregisterMutableMemoryChunk (MutablePageMetadata *chunk)
void UnregisterSharedMemoryChunk (MemoryChunkMetadata *chunk)
void UnregisterMemoryChunk (MemoryChunkMetadata *chunk, Executability executable=NOT_EXECUTABLE)
void RegisterReadOnlyMemory (ReadOnlyPageMetadata *page)
DISALLOW_IMPLICIT_CONSTRUCTORS (MemoryAllocator)
Static Private Member Functions
static size_t ComputeChunkSize (size_t area_size, AllocationSpace space)
Private Attributes
Isolate * isolate_
v8::PageAllocator * data_page_allocator_
v8::PageAllocator * code_page_allocator_
v8::PageAllocator * trusted_page_allocator_
size_t capacity_
std::atomic< size_t > size_ = 0
std::atomic< size_t > size_executable_ = 0
std::atomic< Address > lowest_not_executable_ever_allocated_
std::atomic< Address > highest_not_executable_ever_allocated_ {kNullAddress}
std::atomic< Address > lowest_executable_ever_allocated_
std::atomic< Address > highest_executable_ever_allocated_ {kNullAddress}
std::optional< VirtualMemory > reserved_chunk_at_virtual_memory_limit_
PagePool * pool_
std::unordered_set< const MemoryChunk *, base::hash< const MemoryChunk * > > normal_pages_
std::set< const MemoryChunk * > large_pages_
base::Mutex chunks_mutex_
Static Private Attributes
static V8_EXPORT_PRIVATE size_t commit_page_size_ = 0
static V8_EXPORT_PRIVATE size_t commit_page_size_bits_ = 0
Friends
class heap::TestCodePageAllocatorScope
class heap::TestMemoryAllocatorScope
Detailed Description
Definition at line 47 of file memory-allocator.h.
Member Enumeration Documentation
AllocationMode
enum v8::internal::MemoryAllocator::AllocationMode [strong]
Enumerator
kRegular
kUsePool
Definition at line 49 of file memory-allocator.h.
                            {
    // Regular allocation path. Does not use pool.
    kRegular,
    // Uses the pool for allocation first.
    kUsePool,
  };
FreeMode
enum v8::internal::MemoryAllocator::FreeMode [strong]
Enumerator
kImmediately
kPool
Definition at line 57 of file memory-allocator.h.
                      {
    // Frees page immediately on the main thread.
    kImmediately,
    // Pool page.
    kPool,
  };
Constructor & Destructor Documentation
MemoryAllocator()
v8::internal::MemoryAllocator::MemoryAllocator (Isolate * isolate, v8::PageAllocator * code_page_allocator, v8::PageAllocator * trusted_page_allocator, size_t max_capacity)
Definition at line 39 of file memory-allocator.cc.
    : isolate_(isolate),
      data_page_allocator_(isolate->page_allocator()),
      code_page_allocator_(code_page_allocator),
      trusted_page_allocator_(trusted_page_allocator),
      capacity_(RoundUp(capacity, PageMetadata::kPageSize)) {
  DCHECK_NOT_NULL(data_page_allocator_);
  DCHECK_NOT_NULL(code_page_allocator_);
  DCHECK_NOT_NULL(trusted_page_allocator_);
  pool_ = isolate_->isolate_group()->page_pool();
}
References code_page_allocator_, data_page_allocator_, DCHECK_NOT_NULL, isolate_, v8::internal::Isolate::isolate_group(), v8::internal::IsolateGroup::page_pool(), pool_, and trusted_page_allocator_.
Member Function Documentation
AllocateAlignedMemory()
Address v8::internal::MemoryAllocator::AllocateAlignedMemory (size_t chunk_size, size_t area_size, size_t alignment, AllocationSpace space, Executability executable, void * hint, VirtualMemory * controller, PageSize page_size, AllocationHint allocation_hint) [private]
Definition at line 93 of file memory-allocator.cc.
                                                                        {
  DCHECK_EQ(space == CODE_SPACE || space == CODE_LO_SPACE,
            executable == EXECUTABLE);
  v8::PageAllocator* page_allocator = this->page_allocator(space);
  DCHECK_LT(area_size, chunk_size);
  PageAllocator::Permission permissions =
      executable == EXECUTABLE
          ? MutablePageMetadata::GetCodeModificationPermission()
          : PageAllocator::kReadWrite;
  v8::PageAllocator::AllocationHint page_allocation_hint =
      v8::PageAllocator::AllocationHint().WithAddress(address_hint);
  if (hint.MayGrow()) {
    page_allocation_hint = page_allocation_hint.WithMayGrow();
  }
  VirtualMemory reservation(page_allocator, chunk_size, page_allocation_hint,
                            alignment, permissions);
  if (!reservation.IsReserved()) return HandleAllocationFailure(executable);
  // We cannot use the last chunk in the address space because we would
  // overflow when comparing top and limit if this chunk is used for a
  // linear allocation area.
  if ((reservation.address() + static_cast<Address>(chunk_size)) == 0u) {
    CHECK(!reserved_chunk_at_virtual_memory_limit_);
    reserved_chunk_at_virtual_memory_limit_ = std::move(reservation);
    CHECK(reserved_chunk_at_virtual_memory_limit_);
    // Retry reserve virtual memory.
    reservation = VirtualMemory(page_allocator, chunk_size,
                                page_allocation_hint, alignment, permissions);
    if (!reservation.IsReserved()) return HandleAllocationFailure(executable);
  }
  Address base = reservation.address();
  if (executable == EXECUTABLE) {
    ThreadIsolation::RegisterJitPage(base, chunk_size);
  }
  UpdateAllocatedSpaceLimits(base, base + chunk_size, executable);
  *controller = std::move(reservation);
  return base;
}
References v8::internal::VirtualMemory::address(), CHECK, v8::internal::CODE_LO_SPACE, v8::internal::CODE_SPACE, DCHECK_EQ, DCHECK_LT, v8::internal::EXECUTABLE, v8::internal::MutablePageMetadata::GetCodeModificationPermission(), HandleAllocationFailure(), v8::internal::VirtualMemory::IsReserved(), v8::PageAllocator::kReadWrite, v8::internal::AllocationHint::MayGrow(), page_allocator(), v8::internal::ThreadIsolation::RegisterJitPage(), reserved_chunk_at_virtual_memory_limit_, space, UpdateAllocatedSpaceLimits(), v8::PageAllocator::AllocationHint::WithAddress(), and v8::PageAllocator::AllocationHint::WithMayGrow().
Referenced by AllocateUninitializedChunkAt().
AllocateLargePage()
LargePageMetadata * v8::internal::MemoryAllocator::AllocateLargePage (LargeObjectSpace * space, size_t object_size, Executability executable, AllocationHint hint)
Definition at line 490 of file memory-allocator.cc.
                                                                           {
  std::optional<MemoryChunkAllocationResult> chunk_info;
  if (IsPagePoolSupportedForLargeSpace(space)) {
    chunk_info = TryAllocateUninitializedLargePageFromPool(space, object_size);
  }
  if (!chunk_info) {
    chunk_info = AllocateUninitializedChunk(space, object_size, executable,
                                            PageSize::kLarge, hint);
  }
  if (!chunk_info) return nullptr;
  LargePageMetadata* metadata;
  if (chunk_info->optional_metadata) {
    metadata = new (chunk_info->optional_metadata) LargePageMetadata(
        isolate_->heap(), space, chunk_info->size, chunk_info->area_start,
        chunk_info->area_end, std::move(chunk_info->reservation), executable);
  } else {
    metadata = new LargePageMetadata(
        isolate_->heap(), space, chunk_info->size, chunk_info->area_start,
        chunk_info->area_end, std::move(chunk_info->reservation), executable);
  }
  MemoryChunk* chunk;
  MemoryChunk::MainThreadFlags flags = metadata->InitialFlags(executable);
  if (executable) {
    RwxMemoryWriteScope scope("Initialize a new MemoryChunk.");
    chunk = new (chunk_info->chunk) MemoryChunk(flags, metadata);
  } else {
    chunk = new (chunk_info->chunk) MemoryChunk(flags, metadata);
  }
#ifdef DEBUG
  if (chunk->executable()) RegisterExecutableMemoryChunk(metadata);
#endif // DEBUG
  RecordMemoryChunkCreated(chunk);
  return metadata;
}
References AllocateUninitializedChunk(), v8::internal::MemoryChunk::executable(), v8::internal::flags, v8::internal::Isolate::heap(), v8::internal::LargePageMetadata::InitialFlags(), isolate_, v8::internal::anonymous_namespace{memory-allocator.cc}::IsPagePoolSupportedForLargeSpace(), v8::internal::kLarge, RecordMemoryChunkCreated(), space, and TryAllocateUninitializedLargePageFromPool().
Referenced by v8::internal::LargeObjectSpace::AllocateLargePage().
AllocatePage()
PageMetadata * v8::internal::MemoryAllocator::AllocatePage (MemoryAllocator::AllocationMode alloc_mode, Space * space, Executability executable)
Definition at line 390 of file memory-allocator.cc.
                              {
  const size_t size =
      MemoryChunkLayout::AllocatableMemoryInMemoryChunk(space->identity());
  std::optional<MemoryChunkAllocationResult> chunk_info;
  if (alloc_mode == AllocationMode::kUsePool) {
    DCHECK_EQ(executable, NOT_EXECUTABLE);
    chunk_info = AllocateUninitializedPageFromPool(space);
  }
  if (!chunk_info) {
    chunk_info = AllocateUninitializedChunk(
        space, size, executable, PageSize::kRegular, AllocationHint());
  }
  if (!chunk_info) return nullptr;
  PageMetadata* metadata;
  if (chunk_info->optional_metadata) {
    metadata = new (chunk_info->optional_metadata) PageMetadata(
        isolate_->heap(), space, chunk_info->size, chunk_info->area_start,
        chunk_info->area_end, std::move(chunk_info->reservation));
  } else {
    metadata = new PageMetadata(isolate_->heap(), space, chunk_info->size,
                                chunk_info->area_start, chunk_info->area_end,
                                std::move(chunk_info->reservation));
  }
  MemoryChunk* chunk;
  MemoryChunk::MainThreadFlags flags = metadata->InitialFlags(executable);
  if (v8_flags.black_allocated_pages && space->identity() != NEW_SPACE &&
      space->identity() != NEW_LO_SPACE &&
      isolate_->heap()->incremental_marking()->black_allocation()) {
    // Disable the write barrier for objects pointing to this page. We don't
    // need to trigger the barrier for pointers to old black-allocated pages,
    // since those are never considered for evacuation. However, we have to
    // keep the old->shared remembered set across multiple GCs, so those
    // pointers still need to be recorded.
    if (!IsAnySharedSpace(space->identity())) {
      flags &= ~MemoryChunk::POINTERS_TO_HERE_ARE_INTERESTING;
    }
    // And mark the page as black allocated.
    flags |= MemoryChunk::BLACK_ALLOCATED;
  }
  if (executable) {
    RwxMemoryWriteScope scope("Initialize a new MemoryChunk.");
    chunk = new (chunk_info->chunk) MemoryChunk(flags, metadata);
  } else {
    chunk = new (chunk_info->chunk) MemoryChunk(flags, metadata);
  }
#ifdef DEBUG
  if (chunk->executable()) RegisterExecutableMemoryChunk(metadata);
#endif // DEBUG
  DCHECK(metadata->IsLivenessClear());
  space->InitializePage(metadata);
  RecordMemoryChunkCreated(chunk);
  return metadata;
}
References v8::internal::MemoryChunkLayout::AllocatableMemoryInMemoryChunk(), AllocateUninitializedChunk(), AllocateUninitializedPageFromPool(), v8::internal::MemoryChunk::BLACK_ALLOCATED, v8::internal::IncrementalMarking::black_allocation(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::MemoryChunk::executable(), v8::internal::flags, v8::internal::Isolate::heap(), v8::internal::Heap::incremental_marking(), v8::internal::MutablePageMetadata::InitialFlags(), v8::internal::IsAnySharedSpace(), v8::internal::MutablePageMetadata::IsLivenessClear(), isolate_, v8::internal::kRegular, kUsePool, v8::internal::NEW_LO_SPACE, v8::internal::NEW_SPACE, v8::internal::NOT_EXECUTABLE, RecordMemoryChunkCreated(), size(), space, and v8::internal::v8_flags.
Referenced by v8::internal::SemiSpace::AllocateFreshPage().
AllocateReadOnlyPage()
ReadOnlyPageMetadata * v8::internal::MemoryAllocator::AllocateReadOnlyPage (ReadOnlySpace * space, Address hint = kNullAddress)
Definition at line 451 of file memory-allocator.cc.
                                        {
  DCHECK_EQ(space->identity(), RO_SPACE);
  size_t size = MemoryChunkLayout::AllocatableMemoryInMemoryChunk(RO_SPACE);
  std::optional<MemoryChunkAllocationResult> chunk_info =
      AllocateUninitializedChunkAt(space, size, NOT_EXECUTABLE, hint,
                                   PageSize::kRegular, AllocationHint());
  if (!chunk_info) {
    return nullptr;
  }
  CHECK_NULL(chunk_info->optional_metadata);
  ReadOnlyPageMetadata* metadata = new ReadOnlyPageMetadata(
      isolate_->heap(), space, chunk_info->size, chunk_info->area_start,
      chunk_info->area_end, std::move(chunk_info->reservation));
  new (chunk_info->chunk) MemoryChunk(metadata->InitialFlags(), metadata);
#ifdef V8_ENABLE_SANDBOX_HARDWARE_SUPPORT
  SandboxHardwareSupport::RegisterReadOnlyMemoryInsideSandbox(
      metadata->ChunkAddress(), metadata->size(),
      PageAllocator::Permission::kReadWrite);
#endif // V8_ENABLE_SANDBOX_HARDWARE_SUPPORT
  return metadata;
}
References v8::internal::MemoryChunkLayout::AllocatableMemoryInMemoryChunk(), AllocateUninitializedChunkAt(), CHECK_NULL, v8::internal::MemoryChunkMetadata::ChunkAddress(), DCHECK_EQ, v8::internal::Isolate::heap(), v8::internal::ReadOnlyPageMetadata::InitialFlags(), isolate_, v8::internal::kRegular, v8::internal::NOT_EXECUTABLE, v8::internal::RO_SPACE, v8::internal::MemoryChunkMetadata::size(), size(), and space.
Referenced by v8::internal::ReadOnlySpace::AllocateNextPage(), v8::internal::ReadOnlySpace::AllocateNextPageAt(), and v8::internal::ReadOnlySpace::EnsureSpaceForAllocation().
AllocateUninitializedChunk()
V8_WARN_UNUSED_RESULT std::optional<MemoryChunkAllocationResult> v8::internal::MemoryAllocator::AllocateUninitializedChunk (BaseSpace * space, size_t area_size, Executability executable, PageSize page_size, AllocationHint hint) [inline], [private]
Definition at line 245 of file memory-allocator.h.
                                                  {
    return AllocateUninitializedChunkAt(space, area_size, executable,
                                        kNullAddress, page_size, hint);
  }
References AllocateUninitializedChunkAt(), v8::internal::kNullAddress, and space.
Referenced by AllocateLargePage(), and AllocatePage().
AllocateUninitializedChunkAt()
std::optional< MemoryAllocator::MemoryChunkAllocationResult > v8::internal::MemoryAllocator::AllocateUninitializedChunkAt (BaseSpace * space, size_t area_size, Executability executable, Address hint, PageSize page_size, AllocationHint allocation_hint) [private]
Definition at line 171 of file memory-allocator.cc.
                                                                              {
#ifndef V8_COMPRESS_POINTERS
  // When pointer compression is enabled, spaces are expected to be at a
  // predictable address (see mkgrokdump) so we don't supply a hint and rely on
  // the deterministic behaviour of the BoundedPageAllocator.
  if (hint == kNullAddress) {
    hint = reinterpret_cast<Address>(
        AlignedAddress(isolate_->heap()->GetRandomMmapAddr(),
                       MemoryChunk::GetAlignmentForAllocation()));
  }
#endif
  VirtualMemory reservation;
  size_t chunk_size = ComputeChunkSize(area_size, space->identity());
  DCHECK_EQ(chunk_size % GetCommitPageSize(), 0);
  Address base = AllocateAlignedMemory(
      chunk_size, area_size, MemoryChunk::GetAlignmentForAllocation(),
      space->identity(), executable, reinterpret_cast<void*>(hint),
      &reservation, page_size, allocation_hint);
  if (base == kNullAddress) return {};
  size_ += reservation.size();
  // Update executable memory size.
  if (executable == EXECUTABLE) {
    size_executable_ += reservation.size();
  }
  if (heap::ShouldZapGarbage()) {
    if (executable == EXECUTABLE) {
      CodePageMemoryModificationScopeForDebugging memory_write_scope(
          isolate_->heap(), &reservation,
          base::AddressRegion(base, chunk_size));
      heap::ZapBlock(base, chunk_size, kZapValue);
    } else {
      DCHECK_EQ(executable, NOT_EXECUTABLE);
      // Zap both page header and object area at once. No guard page in-between.
      heap::ZapBlock(base, chunk_size, kZapValue);
    }
  }
  LOG(isolate_,
      NewEvent("MemoryChunk", reinterpret_cast<void*>(base), chunk_size));
  Address area_start = base + MemoryChunkLayout::ObjectStartOffsetInMemoryChunk(
                                  space->identity());
  Address area_end = area_start + area_size;
  return MemoryChunkAllocationResult{
      reinterpret_cast<void*>(base), nullptr, chunk_size, area_start, area_end,
      std::move(reservation),
  };
}
References AlignedAddress(), AllocateAlignedMemory(), ComputeChunkSize(), DCHECK_EQ, v8::internal::EXECUTABLE, v8::internal::MemoryChunk::GetAlignmentForAllocation(), GetCommitPageSize(), v8::internal::Heap::GetRandomMmapAddr(), v8::internal::Isolate::heap(), isolate_, v8::internal::kNullAddress, v8::internal::kZapValue, LOG, v8::internal::NOT_EXECUTABLE, v8::internal::MemoryChunkLayout::ObjectStartOffsetInMemoryChunk(), v8::internal::heap::ShouldZapGarbage(), v8::internal::VirtualMemory::size(), size_, size_executable_, space, and v8::internal::heap::ZapBlock().
Referenced by AllocateReadOnlyPage(), and AllocateUninitializedChunk().
AllocateUninitializedPageFromPool()
std::optional< MemoryAllocator::MemoryChunkAllocationResult > v8::internal::MemoryAllocator::AllocateUninitializedPageFromPool (Space * space) [private]
Definition at line 575 of file memory-allocator.cc.
                                                               {
  MemoryChunkMetadata* chunk_metadata = pool()->Remove(isolate_);
  if (chunk_metadata == nullptr) return {};
  const int size = MutablePageMetadata::kPageSize;
  const Address start = chunk_metadata->ChunkAddress();
  const Address area_start =
      start +
      MemoryChunkLayout::ObjectStartOffsetInMemoryChunk(space->identity());
  const Address area_end = start + size;
  // Pooled pages are always regular data pages.
  DCHECK_NE(CODE_SPACE, space->identity());
  DCHECK_NE(TRUSTED_SPACE, space->identity());
  VirtualMemory reservation(data_page_allocator(), start, size);
  if (heap::ShouldZapGarbage()) {
    heap::ZapBlock(start, size, kZapValue);
  }
  size_ += size;
  UpdateAllocatedSpaceLimits(start, start + size,
                             Executability::NOT_EXECUTABLE);
  return MemoryChunkAllocationResult{
      chunk_metadata->Chunk(), chunk_metadata, size, area_start, area_end,
      std::move(reservation),
  };
}
References v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::MemoryChunkMetadata::ChunkAddress(), v8::internal::CODE_SPACE, data_page_allocator(), DCHECK_NE, isolate_, v8::internal::MutablePageMetadata::kPageSize, v8::internal::kZapValue, v8::internal::NOT_EXECUTABLE, v8::internal::MemoryChunkLayout::ObjectStartOffsetInMemoryChunk(), pool(), v8::internal::PagePool::Remove(), v8::internal::heap::ShouldZapGarbage(), size(), size_, space, v8::internal::TRUSTED_SPACE, UpdateAllocatedSpaceLimits(), and v8::internal::heap::ZapBlock().
Referenced by AllocatePage().
Available()
size_t v8::internal::MemoryAllocator::Available () const [inline]
Definition at line 117 of file memory-allocator.h.
                           {
    const size_t size = Size();
    return capacity_ < size ? 0 : capacity_ - size;
  }
References capacity_, Size(), and size().
Referenced by v8::internal::Heap::Available(), and v8::internal::Heap::RecordStats().
code_page_allocator()
v8::PageAllocator* v8::internal::MemoryAllocator::code_page_allocator () [inline]
Definition at line 165 of file memory-allocator.h.
{ return code_page_allocator_; }
References code_page_allocator_.
ComputeChunkSize()
size_t v8::internal::MemoryAllocator::ComputeChunkSize (size_t area_size, AllocationSpace space) [static], [private]
Definition at line 153 of file memory-allocator.cc.
                                                                {
  //
  // +----------------------------+<- base aligned at MemoryChunk::kAlignment
  // | Header |
  // +----------------------------+<- area_start_ (base + area_start_)
  // | Area |
  // +----------------------------+<- area_end_ (area_start + area_size)
  // | Committed but not used |
  // +----------------------------+<- base + chunk_size
  //
  return ::RoundUp(
      MemoryChunkLayout::ObjectStartOffsetInMemoryChunk(space) + area_size,
      GetCommitPageSize());
}
References GetCommitPageSize(), v8::internal::MemoryChunkLayout::ObjectStartOffsetInMemoryChunk(), RoundUp(), and space.
Referenced by AllocateUninitializedChunkAt().
data_page_allocator()
v8::PageAllocator* v8::internal::MemoryAllocator::data_page_allocator () [inline]
Definition at line 161 of file memory-allocator.h.
{ return data_page_allocator_; }
References data_page_allocator_.
Referenced by AllocateUninitializedPageFromPool(), and TryAllocateUninitializedLargePageFromPool().
DeleteMemoryChunk()
void v8::internal::MemoryAllocator::DeleteMemoryChunk (MutablePageMetadata * metadata) [static]
Definition at line 716 of file memory-allocator.cc.
                                                                     {
  DCHECK(metadata->reserved_memory()->IsReserved());
  DCHECK(!metadata->Chunk()->InReadOnlySpace());
  // The Metadata contains a VirtualMemory reservation and the destructor will
  // release the MemoryChunk.
  DiscardSealedMemoryScope discard_scope("Deleting a memory chunk");
  if (metadata->IsLargePage()) {
    delete reinterpret_cast<LargePageMetadata*>(metadata);
  } else {
    delete reinterpret_cast<PageMetadata*>(metadata);
  }
}
References v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::DCHECK(), v8::internal::MemoryChunk::InReadOnlySpace(), v8::internal::MutablePageMetadata::IsLargePage(), v8::internal::VirtualMemory::IsReserved(), and v8::internal::MemoryChunkMetadata::reserved_memory().
Referenced by v8::internal::PagePool::Add(), v8::internal::PagePool::LargePagePoolImpl::Add(), FreeLargePagesPooled(), and PerformFreeMemory().
DISALLOW_IMPLICIT_CONSTRUCTORS()
v8::internal::MemoryAllocator::DISALLOW_IMPLICIT_CONSTRUCTORS (MemoryAllocator) [private]
Free()
void v8::internal::MemoryAllocator::Free (MemoryAllocator::FreeMode mode, MutablePageMetadata * chunk)
Definition at line 344 of file memory-allocator.cc.
                                                                {
  MemoryChunk* chunk = chunk_metadata->Chunk();
  RecordMemoryChunkDestroyed(chunk);
  PreFreeMemory(chunk_metadata);
  chunk_metadata->ReleaseAllAllocatedMemory();
  switch (mode) {
    case FreeMode::kImmediately:
      PerformFreeMemory(chunk_metadata);
      break;
    case FreeMode::kPool:
      // Ensure that we only ever put pages with their markbits cleared into the
      // pool. This is necessary because `PreFreeMemory` doesn't clear the
      // marking bitmap and the marking bitmap is reused when this page is taken
      // out of the pool again.
      DCHECK(chunk_metadata->IsLivenessClear());
      DCHECK_EQ(chunk_metadata->size(),
                static_cast<size_t>(MutablePageMetadata::kPageSize));
      DCHECK_EQ(chunk->executable(), NOT_EXECUTABLE);
      // The chunks added to this queue will be cached until memory reducing GC.
      pool()->Add(isolate_, chunk_metadata);
      break;
  }
}
References v8::internal::PagePool::Add(), v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::MemoryChunk::executable(), v8::internal::MutablePageMetadata::IsLivenessClear(), isolate_, kImmediately, v8::internal::MutablePageMetadata::kPageSize, kPool, mode(), v8::internal::NOT_EXECUTABLE, PerformFreeMemory(), pool(), PreFreeMemory(), RecordMemoryChunkDestroyed(), v8::internal::MutablePageMetadata::ReleaseAllAllocatedMemory(), and v8::internal::MemoryChunkMetadata::size().
Referenced by v8::internal::MarkCompactCollector::Finish(), v8::internal::NewLargeObjectSpace::FreeDeadObjects(), v8::internal::SemiSpace::RewindPages(), v8::internal::MinorMarkSweepCollector::StartSweepNewSpace(), v8::internal::MinorMarkSweepCollector::SweepNewLargeSpace(), v8::internal::LargeObjectSpace::TearDown(), and v8::internal::SemiSpace::~SemiSpace().
FreeLargePagesPooled()
void v8::internal::MemoryAllocator::FreeLargePagesPooled (std::vector< LargePageMetadata * > pages)
Definition at line 370 of file memory-allocator.cc.
                                               {
  for (LargePageMetadata* page : large_pages) {
    MemoryChunk* chunk = page->Chunk();
    RecordMemoryChunkDestroyed(chunk);
    PreFreeMemory(page);
    page->ReleaseAllAllocatedMemory();
  }
  // Try to add all large pages to the page pool. Large pages successfully added
  // to the pool will be removed from the vector.
  pool()->AddLarge(isolate_, large_pages);
  // Pages remaining in the vector couldn't be added to the large page pool.
  // Free those immediately now.
  for (LargePageMetadata* page : large_pages) {
    MemoryAllocator::DeleteMemoryChunk(page);
  }
}
References v8::internal::PagePool::AddLarge(), DeleteMemoryChunk(), isolate_, pool(), PreFreeMemory(), and RecordMemoryChunkDestroyed().
Referenced by v8::internal::NewLargeObjectSpace::FreeDeadObjects().
FreeMemoryRegion()
void v8::internal::MemoryAllocator::FreeMemoryRegion (v8::PageAllocator * page_allocator, Address addr, size_t size) [private]
Definition at line 88 of file memory-allocator.cc.
                                                                  {
  FreePages(page_allocator, reinterpret_cast<void*>(base), size);
}
References v8::internal::FreePages(), page_allocator(), and size().
Referenced by FreeReadOnlyPage().
FreeReadOnlyPage()
void v8::internal::MemoryAllocator::FreeReadOnlyPage (ReadOnlyPageMetadata * chunk)
Definition at line 304 of file memory-allocator.cc.
                                                                  {
  DCHECK(!chunk->Chunk()->IsFlagSet(MemoryChunk::PRE_FREED));
  LOG(isolate_, DeleteEvent("MemoryChunk", chunk));
  UnregisterSharedMemoryChunk(chunk);
  v8::PageAllocator* allocator = page_allocator(RO_SPACE);
  VirtualMemory* reservation = chunk->reserved_memory();
  if (reservation->IsReserved()) {
    reservation->Free();
  } else {
    // Only read-only pages can have a non-initialized reservation object. This
    // happens when the pages are remapped to multiple locations and where the
    // reservation would therefore be invalid.
    FreeMemoryRegion(allocator, chunk->ChunkAddress(),
                     RoundUp(chunk->size(), allocator->AllocatePageSize()));
  }
  delete chunk;
}
References v8::PageAllocator::AllocatePageSize(), v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::MemoryChunkMetadata::ChunkAddress(), v8::internal::DCHECK(), v8::internal::VirtualMemory::Free(), FreeMemoryRegion(), v8::internal::MemoryChunk::IsFlagSet(), isolate_, v8::internal::VirtualMemory::IsReserved(), LOG, page_allocator(), v8::internal::MemoryChunk::PRE_FREED, v8::internal::MemoryChunkMetadata::reserved_memory(), v8::internal::RO_SPACE, RoundUp(), v8::internal::MemoryChunkMetadata::size(), and UnregisterSharedMemoryChunk().
Referenced by v8::internal::ReadOnlySpace::TearDown().
GetCommitPageSize()
static intptr_t v8::internal::MemoryAllocator::GetCommitPageSize () [inline], [static]
Definition at line 68 of file memory-allocator.h.
                                                {
    DCHECK_LT(0, commit_page_size_);
    return commit_page_size_;
  }
References commit_page_size_, and DCHECK_LT.
Referenced by v8::internal::SemiSpace::AddRangeToActiveSystemPages(), v8::internal::PagedSpaceBase::AddRangeToActiveSystemPages(), AllocateUninitializedChunkAt(), ComputeChunkSize(), v8::internal::Sweeper::ComputeDiscardMemoryArea(), v8::internal::CodeRange::GetWritableReservedAreaSize(), PartialFreeMemory(), v8::internal::PagedSpaceBase::ReduceActiveSystemPages(), ResizeLargePage(), SetPermissionsOnExecutableMemoryChunk(), v8::internal::LargeObjectSpace::ShrinkPageToObjectSize(), v8::internal::ReadOnlyPageMetadata::ShrinkToHighWaterMark(), and v8::internal::LargeObjectSpace::UpdateAccountingAfterResizingObject().
GetCommitPageSizeBits()
static intptr_t v8::internal::MemoryAllocator::GetCommitPageSizeBits () [inline], [static]
Definition at line 73 of file memory-allocator.h.
                                                    {
    DCHECK_LT(0, commit_page_size_bits_);
    return commit_page_size_bits_;
  }
References commit_page_size_bits_, and DCHECK_LT.
Referenced by v8::internal::SemiSpace::AddRangeToActiveSystemPages(), v8::internal::PagedSpaceBase::AddRangeToActiveSystemPages(), v8::internal::MutablePageMetadata::CommittedPhysicalMemory(), v8::internal::MutablePageMetadata::MutablePageMetadata(), v8::internal::Sweeper::RawSweep(), and v8::internal::Sweeper::SweepEmptyNewSpacePage().
GetPooledChunksCount()
size_t v8::internal::MemoryAllocator::GetPooledChunksCount ()
Definition at line 72 of file memory-allocator.cc.
                                             {
  return pool()->GetCount(isolate_);
}
References v8::internal::PagePool::GetCount(), isolate_, and pool().
Referenced by v8::internal::Sweeper::EnsureMajorCompleted(), v8::internal::GCTracer::Print(), v8::internal::GCTracer::PrintNVP(), and v8::internal::Heap::PrintShortHeapStatistics().
GetSharedPooledChunksCount()
size_t v8::internal::MemoryAllocator::GetSharedPooledChunksCount ()
Definition at line 76 of file memory-allocator.cc.
                                                   {
  return pool()->GetSharedCount();
}
References v8::internal::PagePool::GetSharedCount(), and pool().
Referenced by v8::internal::GCTracer::PrintNVP().
GetTotalPooledChunksCount()
size_t v8::internal::MemoryAllocator::GetTotalPooledChunksCount ()
Definition at line 80 of file memory-allocator.cc.
                                                  {
  return pool()->GetTotalCount();
}
References v8::internal::PagePool::GetTotalCount(), and pool().
Referenced by v8::internal::GCTracer::PrintNVP().
HandleAllocationFailure()
Address v8::internal::MemoryAllocator::HandleAllocationFailure (Executability executable)
Definition at line 142 of file memory-allocator.cc.
                                                                         {
  Heap* heap = isolate_->heap();
  if (!heap->deserialization_complete()) {
    heap->FatalProcessOutOfMemory(
        executable == EXECUTABLE
            ? "Executable MemoryChunk allocation failed during deserialization."
            : "MemoryChunk allocation failed during deserialization.");
  }
  return kNullAddress;
}
References v8::internal::EXECUTABLE, v8::internal::Isolate::heap(), isolate_, and v8::internal::kNullAddress.
Referenced by AllocateAlignedMemory().
InitializeOncePerProcess()
void v8::internal::MemoryAllocator::InitializeOncePerProcess () [static]
Definition at line 627 of file memory-allocator.cc.
                                               {
  commit_page_size_ = v8_flags.v8_os_page_size > 0
                          ? v8_flags.v8_os_page_size * KB
                          : CommitPageSize();
  CHECK(base::bits::IsPowerOfTwo(commit_page_size_));
  commit_page_size_bits_ = base::bits::WhichPowerOfTwo(commit_page_size_);
}
References CHECK, commit_page_size_, commit_page_size_bits_, v8::internal::CommitPageSize(), v8::base::bits::IsPowerOfTwo(), v8::internal::KB, v8::internal::v8_flags, and v8::base::bits::WhichPowerOfTwo().
Referenced by v8::internal::Heap::InitializeOncePerProcess().
InitializePagesInChunk()
PageMetadata* v8::internal::MemoryAllocator::InitializePagesInChunk (int chunk_id, int pages_in_chunk, PagedSpace * space) [private]
IsOutsideAllocatedSpace() [1/2]
bool v8::internal::MemoryAllocator::IsOutsideAllocatedSpace (Address address) const [inline]
Definition at line 127 of file memory-allocator.h.
                                                                {
    return IsOutsideAllocatedSpace(address, NOT_EXECUTABLE) &&
           IsOutsideAllocatedSpace(address, EXECUTABLE);
  }
References v8::internal::EXECUTABLE, and v8::internal::NOT_EXECUTABLE.
IsOutsideAllocatedSpace() [2/2]
bool v8::internal::MemoryAllocator::IsOutsideAllocatedSpace (Address address, Executability executable) const [inline]
Definition at line 131 of file memory-allocator.h.
                                                                         {
    switch (executable) {
      case NOT_EXECUTABLE:
        return address < lowest_not_executable_ever_allocated_ ||
               address >= highest_not_executable_ever_allocated_;
      case EXECUTABLE:
        return address < lowest_executable_ever_allocated_ ||
               address >= highest_executable_ever_allocated_;
    }
  }
References v8::internal::EXECUTABLE, highest_executable_ever_allocated_, highest_not_executable_ever_allocated_, lowest_executable_ever_allocated_, lowest_not_executable_ever_allocated_, and v8::internal::NOT_EXECUTABLE.
LookupChunkContainingAddress()
const MemoryChunk * v8::internal::MemoryAllocator::LookupChunkContainingAddress (Address addr) const
Definition at line 654 of file memory-allocator.cc.
                        {
  base::MutexGuard guard(&chunks_mutex_);
  return LookupChunkContainingAddressInSafepoint(addr);
}
References chunks_mutex_, and LookupChunkContainingAddressInSafepoint().
LookupChunkContainingAddressInSafepoint()
const MemoryChunk * v8::internal::MemoryAllocator::LookupChunkContainingAddressInSafepoint (Address addr) const
Definition at line 660 of file memory-allocator.cc.
                        {
  // All threads should be either parked or in a safepoint whenever this method
  // is called, thus pages cannot be allocated or freed at the same time and a
  // mutex is not required here.
  // As the address may not correspond to a valid heap object, the chunk we
  // obtain below is not necessarily a valid chunk.
  MemoryChunk* chunk = MemoryChunk::FromAddress(addr);
  // Check if it corresponds to a known normal or large page.
  if (auto normal_page_it = normal_pages_.find(chunk);
      normal_page_it != normal_pages_.end()) {
    // The chunk is a normal page.
    // auto* normal_page = PageMetadata::cast(chunk);
    DCHECK_LE((*normal_page_it)->address(), addr);
    if (chunk->Metadata()->Contains(addr)) return chunk;
  } else if (auto large_page_it = large_pages_.upper_bound(chunk);
             large_page_it != large_pages_.begin()) {
    // The chunk could be inside a large page.
    DCHECK_IMPLIES(large_page_it != large_pages_.end(),
                   addr < (*large_page_it)->address());
    auto* large_page_chunk = *std::next(large_page_it, -1);
    DCHECK_NOT_NULL(large_page_chunk);
    DCHECK_LE(large_page_chunk->address(), addr);
    if (large_page_chunk->Metadata()->Contains(addr)) return large_page_chunk;
  }
  // Not found in any page.
  return nullptr;
}
References v8::internal::MemoryChunkMetadata::Contains(), DCHECK_IMPLIES, DCHECK_LE, DCHECK_NOT_NULL, v8::internal::MemoryChunk::FromAddress(), large_pages_, v8::internal::MemoryChunk::Metadata(), and normal_pages_.
Referenced by LookupChunkContainingAddress().
page_allocator()
v8::PageAllocator* v8::internal::MemoryAllocator::page_allocator (AllocationSpace space) [inline]
Definition at line 176 of file memory-allocator.h.
                                                         {
    switch (space) {
      case CODE_SPACE:
      case CODE_LO_SPACE:
        return code_page_allocator_;
      case TRUSTED_SPACE:
      case SHARED_TRUSTED_SPACE:
      case TRUSTED_LO_SPACE:
      case SHARED_TRUSTED_LO_SPACE:
        return trusted_page_allocator_;
      default:
        return data_page_allocator_;
    }
  }
References v8::internal::CODE_LO_SPACE, code_page_allocator_, v8::internal::CODE_SPACE, data_page_allocator_, v8::internal::SHARED_TRUSTED_LO_SPACE, v8::internal::SHARED_TRUSTED_SPACE, space, v8::internal::TRUSTED_LO_SPACE, trusted_page_allocator_, and v8::internal::TRUSTED_SPACE.
Referenced by AllocateAlignedMemory(), FreeMemoryRegion(), FreeReadOnlyPage(), v8::internal::ReadOnlySpace::SetPermissionsForPages(), and v8::internal::Sweeper::ZeroOrDiscardUnusedMemory().
PartialFreeMemory()
void v8::internal::MemoryAllocator::PartialFreeMemory (MemoryChunkMetadata * chunk, Address start_free, size_t bytes_to_free, Address new_area_end)
Definition at line 230 of file memory-allocator.cc.
                                                              {
  VirtualMemory* reservation = chunk->reserved_memory();
  DCHECK(reservation->IsReserved());
  chunk->set_size(chunk->size() - bytes_to_free);
  chunk->set_area_end(new_area_end);
  if (chunk->Chunk()->IsFlagSet(MemoryChunk::IS_EXECUTABLE)) {
    // Add guard page at the end.
    size_t page_size = GetCommitPageSize();
    DCHECK_EQ(0, chunk->area_end() % static_cast<Address>(page_size));
    DCHECK_EQ(chunk->ChunkAddress() + chunk->size(), chunk->area_end());
    if ((V8_HEAP_USE_PTHREAD_JIT_WRITE_PROTECT ||
         V8_HEAP_USE_BECORE_JIT_WRITE_PROTECT) &&
        !isolate_->jitless()) {
      DCHECK(isolate_->RequiresCodeRange());
      DiscardSealedMemoryScope discard_scope("Partially free memory.");
      reservation->DiscardSystemPages(chunk->area_end(), page_size);
    } else {
      CHECK(reservation->SetPermissions(chunk->area_end(), page_size,
                                        PageAllocator::kNoAccess));
    }
  }
  // On e.g. Windows, a reservation may be larger than a page and releasing
  // partially starting at |start_free| will also release the potentially
  // unused part behind the current page.
  const size_t released_bytes = reservation->Release(start_free);
  DCHECK_GE(size_, released_bytes);
  size_ -= released_bytes;
}
References v8::internal::MemoryChunkMetadata::area_end(), CHECK, v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::MemoryChunkMetadata::ChunkAddress(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, v8::internal::VirtualMemory::DiscardSystemPages(), GetCommitPageSize(), v8::internal::MemoryChunk::IS_EXECUTABLE, v8::internal::MemoryChunk::IsFlagSet(), isolate_, v8::internal::VirtualMemory::IsReserved(), v8::internal::Isolate::jitless(), v8::PageAllocator::kNoAccess, v8::internal::VirtualMemory::Release(), v8::internal::Isolate::RequiresCodeRange(), v8::internal::MemoryChunkMetadata::reserved_memory(), v8::internal::MemoryChunkMetadata::set_area_end(), v8::internal::MemoryChunkMetadata::set_size(), v8::internal::VirtualMemory::SetPermissions(), v8::internal::MemoryChunkMetadata::size(), size_, V8_HEAP_USE_BECORE_JIT_WRITE_PROTECT, and V8_HEAP_USE_PTHREAD_JIT_WRITE_PROTECT.
Referenced by v8::internal::LargeObjectSpace::ShrinkPageToObjectSize(), and v8::internal::ReadOnlyPageMetadata::ShrinkToHighWaterMark().
PerformFreeMemory()
void v8::internal::MemoryAllocator::PerformFreeMemory (MutablePageMetadata * chunk) [private]
Definition at line 336 of file memory-allocator.cc.
                                                                           {
  DCHECK(chunk_metadata->Chunk()->IsFlagSet(MemoryChunk::UNREGISTERED));
  DCHECK(chunk_metadata->Chunk()->IsFlagSet(MemoryChunk::PRE_FREED));
  DCHECK(!chunk_metadata->Chunk()->InReadOnlySpace());
  DeleteMemoryChunk(chunk_metadata);
}
References v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::DCHECK(), DeleteMemoryChunk(), v8::internal::MemoryChunk::InReadOnlySpace(), v8::internal::MemoryChunk::IsFlagSet(), v8::internal::MemoryChunk::PRE_FREED, and v8::internal::MemoryChunk::UNREGISTERED.
Referenced by Free().
pool()
PagePool* v8::internal::MemoryAllocator::pool () [inline]
Definition at line 191 of file memory-allocator.h.
{ return pool_; }
References pool_.
Referenced by AllocateUninitializedPageFromPool(), Free(), FreeLargePagesPooled(), v8::internal::Heap::GarbageCollectionPrologueInSafepoint(), GetPooledChunksCount(), GetSharedPooledChunksCount(), GetTotalPooledChunksCount(), ReleasePooledChunksImmediately(), v8::internal::Heap::TearDown(), TearDown(), and TryAllocateUninitializedLargePageFromPool().
PreFreeMemory()
void v8::internal::MemoryAllocator::PreFreeMemory (MutablePageMetadata * chunk) [private]
Definition at line 325 of file memory-allocator.cc.
                                                                       {
  MemoryChunk* chunk = chunk_metadata->Chunk();
  DCHECK(!chunk->IsFlagSet(MemoryChunk::PRE_FREED));
  LOG(isolate_, DeleteEvent("MemoryChunk", chunk_metadata));
  UnregisterMutableMemoryChunk(chunk_metadata);
  isolate_->heap()->RememberUnmappedPage(
      reinterpret_cast<Address>(chunk_metadata),
      chunk->IsEvacuationCandidate());
  chunk->SetFlagSlow(MemoryChunk::PRE_FREED);
}
References v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::DCHECK(), v8::internal::Isolate::heap(), v8::internal::MemoryChunk::IsEvacuationCandidate(), v8::internal::MemoryChunk::IsFlagSet(), isolate_, LOG, v8::internal::MemoryChunk::PRE_FREED, v8::internal::Heap::RememberUnmappedPage(), v8::internal::MemoryChunk::SetFlagSlow(), and UnregisterMutableMemoryChunk().
Referenced by Free(), and FreeLargePagesPooled().
RecordMemoryChunkCreated()
void v8::internal::MemoryAllocator::RecordMemoryChunkCreated (const MemoryChunk * chunk)
Definition at line 689 of file memory-allocator.cc.
                                                                       {
  base::MutexGuard guard(&chunks_mutex_);
  if (chunk->IsLargePage()) {
    auto result = large_pages_.insert(chunk);
    USE(result);
    DCHECK(result.second);
  } else {
    auto result = normal_pages_.insert(chunk);
    USE(result);
    DCHECK(result.second);
  }
}
References chunks_mutex_, v8::internal::DCHECK(), v8::internal::MemoryChunk::IsLargePage(), large_pages_, normal_pages_, v8::base::internal::result, and USE.
Referenced by AllocateLargePage(), and AllocatePage().
RecordMemoryChunkDestroyed()
void v8::internal::MemoryAllocator::RecordMemoryChunkDestroyed (const MemoryChunk * chunk)
Definition at line 702 of file memory-allocator.cc.
                                                                         {
  base::MutexGuard guard(&chunks_mutex_);
  if (chunk->IsLargePage()) {
    auto size = large_pages_.erase(chunk);
    USE(size);
    DCHECK_EQ(1u, size);
  } else {
    auto size = normal_pages_.erase(chunk);
    USE(size);
    DCHECK_EQ(1u, size);
  }
}
References chunks_mutex_, DCHECK_EQ, v8::internal::MemoryChunk::IsLargePage(), large_pages_, normal_pages_, size(), and USE.
Referenced by Free(), and FreeLargePagesPooled().
RegisterReadOnlyMemory()
void v8::internal::MemoryAllocator::RegisterReadOnlyMemory (ReadOnlyPageMetadata * page) [private]
ReleasePooledChunksImmediately()
void v8::internal::MemoryAllocator::ReleasePooledChunksImmediately ()
Definition at line 84 of file memory-allocator.cc.
                                                     {
  pool()->ReleaseImmediately(isolate_);
}
References isolate_, pool(), and v8::internal::PagePool::ReleaseImmediately().
Referenced by v8::internal::Sweeper::EnsureMajorCompleted().
RemapSharedPage()
std::unique_ptr<::v8::PageAllocator::SharedMemoryMapping > v8::internal::MemoryAllocator::RemapSharedPage (::v8::PageAllocator::SharedMemory * shared_memory, Address new_address)
Definition at line 478 of file memory-allocator.cc.
                                                                     {
  return shared_memory->RemapTo(reinterpret_cast<void*>(new_address));
}
References v8::PageAllocator::SharedMemory::RemapTo().
ResizeLargePage()
bool v8::internal::MemoryAllocator::ResizeLargePage (LargePageMetadata * page, size_t old_object_size, size_t new_object_size)
Definition at line 534 of file memory-allocator.cc.
                                                              {
  const size_t old_reservation_size = page->reservation_.size();
  const size_t old_page_end = page->reservation_.end();
  const Address new_area_end = page->area_start() + new_object_size;
  const Address new_page_end = RoundUp(new_area_end, GetCommitPageSize());
  const size_t new_page_size = new_page_end - page->ChunkAddress();
  if (old_page_end == new_page_end) {
    // We were able to grow the object without growing its owning page.
    page->set_area_end(new_area_end);
    return true;
  }
  // Currently we only support growing.
  DCHECK_LT(old_page_end, new_page_end);
  if (!page->reservation_.Resize(page->ChunkAddress(), new_page_size,
                                 PageAllocator::kReadWrite)) {
    return false;
  }
  page->set_area_end(new_area_end);
  page->set_size(new_page_size);
#if DEBUG
  AllocationSpace space = page->owner_identity();
  DCHECK(space == NEW_LO_SPACE || space == LO_SPACE);
#endif // DEBUG
  UpdateAllocatedSpaceLimits(page->ChunkAddress(), new_page_end,
                             Executability::NOT_EXECUTABLE);
  size_ -= old_reservation_size;
  size_ += page->reservation_.size();
  return true;
}
References v8::internal::MemoryChunkMetadata::area_start(), v8::internal::MemoryChunkMetadata::ChunkAddress(), v8::internal::DCHECK(), DCHECK_LT, v8::internal::VirtualMemory::end(), GetCommitPageSize(), v8::PageAllocator::kReadWrite, v8::internal::LO_SPACE, v8::internal::NEW_LO_SPACE, v8::internal::NOT_EXECUTABLE, v8::internal::MutablePageMetadata::owner_identity(), v8::internal::MemoryChunkMetadata::reservation_, v8::internal::VirtualMemory::Resize(), RoundUp(), v8::internal::MemoryChunkMetadata::set_area_end(), v8::internal::MemoryChunkMetadata::set_size(), v8::internal::VirtualMemory::size(), size_, space, and UpdateAllocatedSpaceLimits().
Referenced by v8::internal::HeapAllocator::TryResizeLargeObject().
SetPermissionsOnExecutableMemoryChunk()
bool v8::internal::MemoryAllocator::SetPermissionsOnExecutableMemoryChunk (VirtualMemory * vm, Address start, size_t reserved_size) [private]
Definition at line 635 of file memory-allocator.cc.
                                                                               {
  // All addresses and sizes must be aligned to the commit page size.
  DCHECK(IsAligned(start, GetCommitPageSize()));
  DCHECK_EQ(0, chunk_size % GetCommitPageSize());
  if (isolate_->RequiresCodeRange()) {
    // The pages of the code range are already mapped RWX, we just need to
    // recommit them.
    return vm->RecommitPages(start, chunk_size,
                             PageAllocator::kReadWriteExecute);
  } else {
    return vm->SetPermissions(
        start, chunk_size,
        MutablePageMetadata::GetCodeModificationPermission());
  }
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::MutablePageMetadata::GetCodeModificationPermission(), GetCommitPageSize(), IsAligned(), isolate_, v8::PageAllocator::kReadWriteExecute, v8::internal::VirtualMemory::RecommitPages(), v8::internal::Isolate::RequiresCodeRange(), and v8::internal::VirtualMemory::SetPermissions().
Size()
size_t v8::internal::MemoryAllocator::Size () const [inline]
Definition at line 111 of file memory-allocator.h.
{ return size_; }
References size_.
Referenced by Available(), v8::internal::Heap::CanExpandOldGeneration(), v8::internal::Heap::RecordStats(), v8::internal::GCTracer::StartInSafepoint(), and v8::internal::GCTracer::StopInSafepoint().
SizeExecutable()
size_t v8::internal::MemoryAllocator::SizeExecutable () const [inline]
Definition at line 114 of file memory-allocator.h.
{ return size_executable_; }
References size_executable_.
Referenced by v8::internal::Heap::CommittedMemoryExecutable().
TearDown()
void v8::internal::MemoryAllocator::TearDown ()
Definition at line 54 of file memory-allocator.cc.
                               {
  DCHECK_EQ(pool()->GetCount(isolate_), 0);
  // Check that spaces were torn down before MemoryAllocator.
  DCHECK_EQ(size_, 0u);
  // TODO(gc) this will be true again when we fix FreeMemory.
  // DCHECK_EQ(0, size_executable_);
  capacity_ = 0;
  if (reserved_chunk_at_virtual_memory_limit_) {
    reserved_chunk_at_virtual_memory_limit_->Free();
  }
  code_page_allocator_ = nullptr;
  data_page_allocator_ = nullptr;
  trusted_page_allocator_ = nullptr;
}
References capacity_, code_page_allocator_, data_page_allocator_, DCHECK_EQ, isolate_, pool(), reserved_chunk_at_virtual_memory_limit_, size_, and trusted_page_allocator_.
Referenced by v8::internal::Heap::TearDown().
trusted_page_allocator()
v8::PageAllocator* v8::internal::MemoryAllocator::trusted_page_allocator () [inline]
Definition at line 171 of file memory-allocator.h.
                                            {
    return trusted_page_allocator_;
  }
References trusted_page_allocator_.
TryAllocateUninitializedLargePageFromPool()
std::optional< MemoryAllocator::MemoryChunkAllocationResult > v8::internal::MemoryAllocator::TryAllocateUninitializedLargePageFromPool (Space * space, size_t chunk_size) [private]
Definition at line 601 of file memory-allocator.cc.
                                                                               {
  const size_t object_start_offset =
      MemoryChunkLayout::ObjectStartOffsetInMemoryChunk(space->identity());
  // Select a pooled large page which can store |object_size| bytes. In case the
  // page is larger than necessary, the next full GC will trim down its size.
  MemoryChunkMetadata* chunk_metadata =
      pool()->RemoveLarge(isolate_, object_start_offset + object_size);
  if (chunk_metadata == nullptr) return {};
  const Address start = chunk_metadata->ChunkAddress();
  const size_t size = chunk_metadata->size();
  const Address area_start = start + object_start_offset;
  const Address area_end = start + size;
  VirtualMemory reservation(data_page_allocator(), start, size);
  if (heap::ShouldZapGarbage()) {
    heap::ZapBlock(start, size, kZapValue);
  }
  size_ += size;
  UpdateAllocatedSpaceLimits(start, start + size,
                             Executability::NOT_EXECUTABLE);
  return MemoryChunkAllocationResult{
      chunk_metadata->Chunk(), chunk_metadata, size, area_start, area_end,
      std::move(reservation),
  };
}
References v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::MemoryChunkMetadata::ChunkAddress(), data_page_allocator(), isolate_, v8::internal::kZapValue, v8::internal::NOT_EXECUTABLE, v8::internal::MemoryChunkLayout::ObjectStartOffsetInMemoryChunk(), pool(), v8::internal::PagePool::RemoveLarge(), v8::internal::heap::ShouldZapGarbage(), v8::internal::MemoryChunkMetadata::size(), size(), size_, space, UpdateAllocatedSpaceLimits(), and v8::internal::heap::ZapBlock().
Referenced by AllocateLargePage().
UnregisterMemoryChunk()
void v8::internal::MemoryAllocator::UnregisterMemoryChunk (MemoryChunkMetadata * chunk, Executability executable = NOT_EXECUTABLE) [private]
Definition at line 271 of file memory-allocator.cc.
                                                                      {
  MemoryChunk* chunk = chunk_metadata->Chunk();
  DCHECK(!chunk->IsFlagSet(MemoryChunk::UNREGISTERED));
  VirtualMemory* reservation = chunk_metadata->reserved_memory();
  const size_t size =
      reservation->IsReserved() ? reservation->size() : chunk_metadata->size();
  DCHECK_GE(size_, static_cast<size_t>(size));
  size_ -= size;
  if (executable == EXECUTABLE) {
    DCHECK_GE(size_executable_, size);
    size_executable_ -= size;
#ifdef DEBUG
    UnregisterExecutableMemoryChunk(
        static_cast<MutablePageMetadata*>(chunk_metadata));
#endif // DEBUG
    ThreadIsolation::UnregisterJitPage(chunk->address(),
                                       chunk_metadata->size());
  }
  chunk->SetFlagSlow(MemoryChunk::UNREGISTERED);
}
References v8::internal::MemoryChunk::address(), v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::DCHECK(), DCHECK_GE, v8::internal::EXECUTABLE, v8::internal::MemoryChunk::IsFlagSet(), v8::internal::VirtualMemory::IsReserved(), v8::internal::MemoryChunkMetadata::reserved_memory(), v8::internal::MemoryChunk::SetFlagSlow(), v8::internal::MemoryChunkMetadata::size(), v8::internal::VirtualMemory::size(), size(), size_, size_executable_, v8::internal::MemoryChunk::UNREGISTERED, and v8::internal::ThreadIsolation::UnregisterJitPage().
Referenced by UnregisterMutableMemoryChunk(), and UnregisterReadOnlyPage().
UnregisterMutableMemoryChunk()
void v8::internal::MemoryAllocator::UnregisterMutableMemoryChunk (MutablePageMetadata * chunk) [private]
Definition at line 295 of file memory-allocator.cc.
                                                                             {
  UnregisterMemoryChunk(chunk, chunk->Chunk()->executable());
}
References v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::MemoryChunk::executable(), and UnregisterMemoryChunk().
Referenced by PreFreeMemory().
UnregisterReadOnlyPage()
void v8::internal::MemoryAllocator::UnregisterReadOnlyPage (ReadOnlyPageMetadata * page)
Definition at line 299 of file memory-allocator.cc.
                                                                       {
  DCHECK(!page->Chunk()->executable());
  UnregisterMemoryChunk(page, NOT_EXECUTABLE);
}
References v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::DCHECK(), v8::internal::MemoryChunk::executable(), v8::internal::NOT_EXECUTABLE, and UnregisterMemoryChunk().
UnregisterSharedMemoryChunk()
void v8::internal::MemoryAllocator::UnregisterSharedMemoryChunk (MemoryChunkMetadata * chunk) [private]
Definition at line 263 of file memory-allocator.cc.
                                                                            {
  VirtualMemory* reservation = chunk->reserved_memory();
  const size_t size =
      reservation->IsReserved() ? reservation->size() : chunk->size();
  DCHECK_GE(size_, static_cast<size_t>(size));
  size_ -= size;
}
References DCHECK_GE, v8::internal::VirtualMemory::IsReserved(), v8::internal::MemoryChunkMetadata::reserved_memory(), v8::internal::MemoryChunkMetadata::size(), v8::internal::VirtualMemory::size(), size(), and size_.
Referenced by FreeReadOnlyPage().
UpdateAllocatedSpaceLimits()
void v8::internal::MemoryAllocator::UpdateAllocatedSpaceLimits (Address low, Address high, Executability executable) [inline], [private]
Definition at line 299 of file memory-allocator.h.
                                                            {
    // The use of atomic primitives does not guarantee correctness (wrt.
    // desired semantics) by default. The loop here ensures that we update the
    // values only if they did not change in between.
    Address ptr;
    switch (executable) {
      case NOT_EXECUTABLE:
        ptr = lowest_not_executable_ever_allocated_.load(
            std::memory_order_relaxed);
        while ((low < ptr) &&
               !lowest_not_executable_ever_allocated_.compare_exchange_weak(
                   ptr, low, std::memory_order_acq_rel)) {
        }
        ptr = highest_not_executable_ever_allocated_.load(
            std::memory_order_relaxed);
        while ((high > ptr) &&
               !highest_not_executable_ever_allocated_.compare_exchange_weak(
                   ptr, high, std::memory_order_acq_rel)) {
        }
        break;
      case EXECUTABLE:
        ptr = lowest_executable_ever_allocated_.load(std::memory_order_relaxed);
        while ((low < ptr) &&
               !lowest_executable_ever_allocated_.compare_exchange_weak(
                   ptr, low, std::memory_order_acq_rel)) {
        }
        ptr =
            highest_executable_ever_allocated_.load(std::memory_order_relaxed);
        while ((high > ptr) &&
               !highest_executable_ever_allocated_.compare_exchange_weak(
                   ptr, high, std::memory_order_acq_rel)) {
        }
        break;
    }
  }
References v8::internal::EXECUTABLE, highest_executable_ever_allocated_, highest_not_executable_ever_allocated_, lowest_executable_ever_allocated_, lowest_not_executable_ever_allocated_, and v8::internal::NOT_EXECUTABLE.
Referenced by AllocateAlignedMemory(), AllocateUninitializedPageFromPool(), ResizeLargePage(), and TryAllocateUninitializedLargePageFromPool().
Friends And Related Function Documentation
heap::TestCodePageAllocatorScope
friend class heap::TestCodePageAllocatorScope [friend]
Definition at line 424 of file memory-allocator.h.
heap::TestMemoryAllocatorScope
friend class heap::TestMemoryAllocatorScope [friend]
Definition at line 425 of file memory-allocator.h.
Member Data Documentation
capacity_
size_t v8::internal::MemoryAllocator::capacity_ [private]
Definition at line 381 of file memory-allocator.h.
Referenced by Available(), and TearDown().
chunks_mutex_
base::Mutex v8::internal::MemoryAllocator::chunks_mutex_ [mutable], [private]
Definition at line 419 of file memory-allocator.h.
Referenced by LookupChunkContainingAddress(), RecordMemoryChunkCreated(), and RecordMemoryChunkDestroyed().
code_page_allocator_
v8::PageAllocator* v8::internal::MemoryAllocator::code_page_allocator_ [private]
Definition at line 372 of file memory-allocator.h.
Referenced by code_page_allocator(), MemoryAllocator(), page_allocator(), and TearDown().
commit_page_size_
size_t v8::internal::MemoryAllocator::commit_page_size_ = 0 [static], [private]
Definition at line 421 of file memory-allocator.h.
Referenced by GetCommitPageSize(), and InitializeOncePerProcess().
commit_page_size_bits_
size_t v8::internal::MemoryAllocator::commit_page_size_bits_ = 0 [static], [private]
Definition at line 422 of file memory-allocator.h.
Referenced by GetCommitPageSizeBits(), and InitializeOncePerProcess().
data_page_allocator_
v8::PageAllocator* v8::internal::MemoryAllocator::data_page_allocator_ [private]
Definition at line 365 of file memory-allocator.h.
Referenced by data_page_allocator(), MemoryAllocator(), page_allocator(), and TearDown().
highest_executable_ever_allocated_
std::atomic<Address> v8::internal::MemoryAllocator::highest_executable_ever_allocated_ {kNullAddress} [private]
Definition at line 400 of file memory-allocator.h.
Referenced by IsOutsideAllocatedSpace(), and UpdateAllocatedSpaceLimits().
highest_not_executable_ever_allocated_
std::atomic<Address> v8::internal::MemoryAllocator::highest_not_executable_ever_allocated_ {kNullAddress} [private]
Definition at line 397 of file memory-allocator.h.
Referenced by IsOutsideAllocatedSpace(), and UpdateAllocatedSpaceLimits().
isolate_
Isolate* v8::internal::MemoryAllocator::isolate_ [private]
Definition at line 360 of file memory-allocator.h.
Referenced by AllocateLargePage(), AllocatePage(), AllocateReadOnlyPage(), AllocateUninitializedChunkAt(), AllocateUninitializedPageFromPool(), Free(), FreeLargePagesPooled(), FreeReadOnlyPage(), GetPooledChunksCount(), HandleAllocationFailure(), MemoryAllocator(), PartialFreeMemory(), PreFreeMemory(), ReleasePooledChunksImmediately(), SetPermissionsOnExecutableMemoryChunk(), TearDown(), and TryAllocateUninitializedLargePageFromPool().
large_pages_
std::set<const MemoryChunk*> v8::internal::MemoryAllocator::large_pages_ [private]
Definition at line 417 of file memory-allocator.h.
Referenced by LookupChunkContainingAddressInSafepoint(), RecordMemoryChunkCreated(), and RecordMemoryChunkDestroyed().
lowest_executable_ever_allocated_
std::atomic<Address> v8::internal::MemoryAllocator::lowest_executable_ever_allocated_ [private]
Initial value:
{
      static_cast<Address>(-1ll)}
Definition at line 398 of file memory-allocator.h.
Referenced by IsOutsideAllocatedSpace(), and UpdateAllocatedSpaceLimits().
lowest_not_executable_ever_allocated_
std::atomic<Address> v8::internal::MemoryAllocator::lowest_not_executable_ever_allocated_ [private]
Initial value:
{
      static_cast<Address>(-1ll)}
Definition at line 395 of file memory-allocator.h.
Referenced by IsOutsideAllocatedSpace(), and UpdateAllocatedSpaceLimits().
normal_pages_
std::unordered_set<const MemoryChunk*, base::hash<const MemoryChunk*> > v8::internal::MemoryAllocator::normal_pages_ [private]
Definition at line 416 of file memory-allocator.h.
Referenced by LookupChunkContainingAddressInSafepoint(), RecordMemoryChunkCreated(), and RecordMemoryChunkDestroyed().
pool_
PagePool* v8::internal::MemoryAllocator::pool_ [private]
Definition at line 403 of file memory-allocator.h.
Referenced by MemoryAllocator(), and pool().
reserved_chunk_at_virtual_memory_limit_
std::optional<VirtualMemory> v8::internal::MemoryAllocator::reserved_chunk_at_virtual_memory_limit_ [private]
Definition at line 402 of file memory-allocator.h.
Referenced by AllocateAlignedMemory(), and TearDown().
size_
std::atomic<size_t> v8::internal::MemoryAllocator::size_ = 0 [private]
Definition at line 384 of file memory-allocator.h.
Referenced by AllocateUninitializedChunkAt(), AllocateUninitializedPageFromPool(), PartialFreeMemory(), ResizeLargePage(), Size(), TearDown(), TryAllocateUninitializedLargePageFromPool(), UnregisterMemoryChunk(), and UnregisterSharedMemoryChunk().
size_executable_
std::atomic<size_t> v8::internal::MemoryAllocator::size_executable_ = 0 [private]
Definition at line 386 of file memory-allocator.h.
Referenced by AllocateUninitializedChunkAt(), SizeExecutable(), and UnregisterMemoryChunk().
trusted_page_allocator_
v8::PageAllocator* v8::internal::MemoryAllocator::trusted_page_allocator_ [private]
Definition at line 378 of file memory-allocator.h.
Referenced by MemoryAllocator(), page_allocator(), TearDown(), and trusted_page_allocator().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/memory-allocator.h
/mnt/V8SourceCode/src/heap/memory-allocator.cc