v8::internal::LinkageLocation Class Reference
#include <linkage-location.h>
Public Member Functions
bool operator== (const LinkageLocation &other) const
bool operator!= (const LinkageLocation &other) const
MachineType GetType () const
int GetSizeInPointers () const
int32_t GetLocation () const
bool IsNullRegister () const
NO_INLINE_FOR_ARM64_MSVC bool IsRegister () const
bool IsAnyRegister () const
bool IsCallerFrameSlot () const
bool IsCalleeFrameSlot () const
int32_t AsRegister () const
int32_t AsCallerFrameSlot () const
int32_t AsCalleeFrameSlot () const
Static Public Member Functions
static bool IsSameLocation (const LinkageLocation &a, const LinkageLocation &b)
static LinkageLocation ForNullRegister (int32_t reg, MachineType type=MachineType::None())
static LinkageLocation ForAnyRegister (MachineType type=MachineType::None())
static LinkageLocation ForRegister (int32_t reg, MachineType type=MachineType::None())
static LinkageLocation ForCallerFrameSlot (int32_t slot, MachineType type)
static LinkageLocation ForCalleeFrameSlot (int32_t slot, MachineType type)
static LinkageLocation ForSavedCallerReturnAddress ()
static LinkageLocation ForSavedCallerFramePtr ()
static LinkageLocation ForSavedCallerConstantPool ()
static LinkageLocation ForSavedCallerFunction ()
static LinkageLocation ConvertToTailCallerLocation (LinkageLocation caller_location, int stack_param_delta)
Private Types
enum LocationType { REGISTER
, STACK_SLOT
 }
using TypeField = base::BitField< LocationType, 0, 1 >
using LocationField = TypeField::Next< int32_t, 31 >
Private Member Functions
LinkageLocation (LocationType type, int32_t location, MachineType machine_type)
Private Attributes
int32_t bit_field_
MachineType machine_type_
Static Private Attributes
static constexpr int32_t ANY_REGISTER = -1
static constexpr int32_t MAX_STACK_SLOT = 32767
Detailed Description
Definition at line 25 of file linkage-location.h.
Member Typedef Documentation
LocationField
using v8::internal::LinkageLocation::LocationField = TypeField::Next<int32_t, 31> [private]
Definition at line 159 of file linkage-location.h.
TypeField
using v8::internal::LinkageLocation::TypeField = base::BitField<LocationType, 0, 1> [private]
Definition at line 158 of file linkage-location.h.
Member Enumeration Documentation
LocationType
enum v8::internal::LinkageLocation::LocationType [private]
Enumerator
REGISTER
STACK_SLOT
Definition at line 156 of file linkage-location.h.
{ REGISTER, STACK_SLOT };
Constructor & Destructor Documentation
LinkageLocation()
v8::internal::LinkageLocation::LinkageLocation (LocationType type, int32_t location, MachineType machine_type) [inline], [private]
Definition at line 164 of file linkage-location.h.
                                            {
    bit_field_ = TypeField::encode(type) |
                 // {location} can be -1 (ANY_REGISTER).
                 ((static_cast<uint32_t>(location) << LocationField::kShift) &
                  LocationField::kMask);
    machine_type_ = machine_type;
  }
References bit_field_, v8::base::BitField< T, shift, size, U >::encode(), v8::base::BitField< T, shift, size, U >::kMask, v8::base::BitField< T, shift, size, U >::kShift, v8::internal::wasm::machine_type(), machine_type_, and v8::internal::tracing::type.
Referenced by ConvertToTailCallerLocation(), ForAnyRegister(), ForCalleeFrameSlot(), ForCallerFrameSlot(), ForNullRegister(), and ForRegister().
Member Function Documentation
AsCalleeFrameSlot()
int32_t v8::internal::LinkageLocation::AsCalleeFrameSlot () const [inline]
Definition at line 150 of file linkage-location.h.
                                    {
    DCHECK(IsCalleeFrameSlot());
    return GetLocation();
  }
References v8::internal::DCHECK(), GetLocation(), and IsCalleeFrameSlot().
Referenced by v8::internal::compiler::OperandGenerator::ToDualLocationUnallocatedOperand(), and v8::internal::compiler::OperandGenerator::ToUnallocatedOperand().
AsCallerFrameSlot()
int32_t v8::internal::LinkageLocation::AsCallerFrameSlot () const [inline]
Definition at line 146 of file linkage-location.h.
                                    {
    DCHECK(IsCallerFrameSlot());
    return GetLocation();
  }
References v8::internal::DCHECK(), GetLocation(), and IsCallerFrameSlot().
Referenced by v8::internal::compiler::CallDescriptor::CanTailCall(), and v8::internal::compiler::OperandGenerator::ToUnallocatedOperand().
AsRegister()
int32_t v8::internal::LinkageLocation::AsRegister () const [inline]
Definition at line 142 of file linkage-location.h.
                             {
    DCHECK(IsRegister());
    return GetLocation();
  }
References v8::internal::DCHECK(), GetLocation(), and IsRegister().
Referenced by v8::internal::wasm::LiftoffAssembler::PrepareCall(), v8::internal::compiler::OperandGenerator::ToDualLocationUnallocatedOperand(), and v8::internal::compiler::OperandGenerator::ToUnallocatedOperand().
ConvertToTailCallerLocation()
static LinkageLocation v8::internal::LinkageLocation::ConvertToTailCallerLocation (LinkageLocation caller_location, int stack_param_delta) [inline], [static]
Definition at line 107 of file linkage-location.h.
                                                              {
    if (!caller_location.IsRegister()) {
      return LinkageLocation(STACK_SLOT,
                             caller_location.GetLocation() + stack_param_delta,
                             caller_location.GetType());
    }
    return caller_location;
  }
References GetLocation(), GetType(), IsRegister(), LinkageLocation(), and STACK_SLOT.
Referenced by v8::internal::compiler::InstructionSelector::InitializeCallBuffer().
ForAnyRegister()
static LinkageLocation v8::internal::LinkageLocation::ForAnyRegister (MachineType type = MachineType::None()) [inline], [static]
Definition at line 54 of file linkage-location.h.
                                            {
    return LinkageLocation(REGISTER, ANY_REGISTER, type);
  }
References ANY_REGISTER, LinkageLocation(), REGISTER, and v8::internal::tracing::type.
Referenced by v8::internal::compiler::Linkage::GetBytecodeDispatchCallDescriptor(), v8::internal::compiler::Linkage::GetCEntryStubCallDescriptor(), v8::internal::compiler::Linkage::GetSimplifiedCDescriptor(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), and v8::internal::compiler::GetWasmCallDescriptor().
ForCalleeFrameSlot()
static LinkageLocation v8::internal::LinkageLocation::ForCalleeFrameSlot (int32_t slot, MachineType type) [inline], [static]
Definition at line 70 of file linkage-location.h.
                                                                            {
    // TODO(titzer): bailout instead of crashing here.
    DCHECK(slot >= 0 && slot < LinkageLocation::MAX_STACK_SLOT);
    return LinkageLocation(STACK_SLOT, slot, type);
  }
References v8::internal::DCHECK(), LinkageLocation(), MAX_STACK_SLOT, STACK_SLOT, and v8::internal::tracing::type.
Referenced by ForSavedCallerConstantPool(), ForSavedCallerFramePtr(), ForSavedCallerFunction(), ForSavedCallerReturnAddress(), v8::internal::compiler::Linkage::GetOsrValueLocation(), and v8::internal::compiler::Linkage::GetParameterSecondaryLocation().
ForCallerFrameSlot()
static LinkageLocation v8::internal::LinkageLocation::ForCallerFrameSlot (int32_t slot, MachineType type) [inline], [static]
Definition at line 65 of file linkage-location.h.
                                                                            {
    DCHECK_GT(0, slot);
    return LinkageLocation(STACK_SLOT, slot, type);
  }
References DCHECK_GT, LinkageLocation(), STACK_SLOT, and v8::internal::tracing::type.
Referenced by v8::internal::compiler::BuildParameterLocations(), v8::internal::compiler::Linkage::GetBytecodeDispatchCallDescriptor(), v8::internal::compiler::Linkage::GetCEntryStubCallDescriptor(), v8::internal::compiler::Linkage::GetJSCallDescriptor(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), and v8::internal::wasm::LinkageLocationAllocator::Next().
ForNullRegister()
static LinkageLocation v8::internal::LinkageLocation::ForNullRegister (int32_t reg, MachineType type = MachineType::None()) [inline], [static]
Definition at line 49 of file linkage-location.h.
                                                         {
    return LinkageLocation(REGISTER, reg, type);
  }
References LinkageLocation(), REGISTER, and v8::internal::tracing::type.
ForRegister()
static LinkageLocation v8::internal::LinkageLocation::ForRegister (int32_t reg, MachineType type = MachineType::None()) [inline], [static]
Definition at line 59 of file linkage-location.h.
                                                                           {
    DCHECK_LE(0, reg);
    return LinkageLocation(REGISTER, reg, type);
  }
References DCHECK_LE, LinkageLocation(), REGISTER, and v8::internal::tracing::type.
Referenced by v8::internal::compiler::BuildParameterLocations(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::ExceptionLocation(), v8::internal::compiler::Linkage::GetSimplifiedCDescriptor(), v8::internal::wasm::IterateSignatureImpl(), v8::internal::wasm::LinkageLocationAllocator::Next(), and v8::internal::compiler::anonymous_namespace{linkage.cc}::regloc().
ForSavedCallerConstantPool()
static LinkageLocation v8::internal::LinkageLocation::ForSavedCallerConstantPool () [inline], [static]
Definition at line 92 of file linkage-location.h.
                                                      {
    DCHECK(V8_EMBEDDED_CONSTANT_POOL_BOOL);
    return ForCalleeFrameSlot((StandardFrameConstants::kCallerPCOffset -
                               StandardFrameConstants::kConstantPoolOffset) /
                                  kSystemPointerSize,
                              MachineType::AnyTagged());
  }
References v8::internal::MachineType::AnyTagged(), v8::internal::DCHECK(), ForCalleeFrameSlot(), v8::internal::CommonFrameConstants::kCallerPCOffset, v8::internal::CommonFrameConstants::kConstantPoolOffset, v8::internal::kSystemPointerSize, and V8_EMBEDDED_CONSTANT_POOL_BOOL.
ForSavedCallerFramePtr()
static LinkageLocation v8::internal::LinkageLocation::ForSavedCallerFramePtr () [inline], [static]
Definition at line 85 of file linkage-location.h.
                                                  {
    return ForCalleeFrameSlot((StandardFrameConstants::kCallerPCOffset -
                               StandardFrameConstants::kCallerFPOffset) /
                                  kSystemPointerSize,
                              MachineType::Pointer());
  }
References ForCalleeFrameSlot(), v8::internal::CommonFrameConstants::kCallerFPOffset, v8::internal::CommonFrameConstants::kCallerPCOffset, v8::internal::kSystemPointerSize, and v8::internal::MachineType::Pointer().
ForSavedCallerFunction()
static LinkageLocation v8::internal::LinkageLocation::ForSavedCallerFunction () [inline], [static]
Definition at line 100 of file linkage-location.h.
                                                  {
    return ForCalleeFrameSlot((StandardFrameConstants::kCallerPCOffset -
                               StandardFrameConstants::kFunctionOffset) /
                                  kSystemPointerSize,
                              MachineType::AnyTagged());
  }
References v8::internal::MachineType::AnyTagged(), ForCalleeFrameSlot(), v8::internal::CommonFrameConstants::kCallerPCOffset, v8::internal::StandardFrameConstants::kFunctionOffset, and v8::internal::kSystemPointerSize.
Referenced by v8::internal::compiler::Linkage::GetJSCallDescriptor().
ForSavedCallerReturnAddress()
static LinkageLocation v8::internal::LinkageLocation::ForSavedCallerReturnAddress () [inline], [static]
Definition at line 78 of file linkage-location.h.
                                                       {
    return ForCalleeFrameSlot((StandardFrameConstants::kCallerPCOffset -
                               StandardFrameConstants::kCallerPCOffset) /
                                  kSystemPointerSize,
                              MachineType::Pointer());
  }
References ForCalleeFrameSlot(), v8::internal::CommonFrameConstants::kCallerPCOffset, v8::internal::kSystemPointerSize, and v8::internal::MachineType::Pointer().
Referenced by v8::internal::compiler::InstructionSelector::InitializeCallBuffer().
GetLocation()
int32_t v8::internal::LinkageLocation::GetLocation () const [inline]
Definition at line 123 of file linkage-location.h.
                              {
    // We can't use LocationField::decode here because it doesn't work for
    // negative values!
    return static_cast<int32_t>(bit_field_ & LocationField::kMask) >>
           LocationField::kShift;
  }
References bit_field_, v8::base::BitField< T, shift, size, U >::kMask, and v8::base::BitField< T, shift, size, U >::kShift.
Referenced by AsCalleeFrameSlot(), AsCallerFrameSlot(), AsRegister(), ConvertToTailCallerLocation(), v8::internal::compiler::CallDescriptor::GetOffsetToFirstUnusedStackSlot(), v8::internal::compiler::CallDescriptor::GetOffsetToReturns(), v8::internal::compiler::CallDescriptor::GetTaggedParameterSlots(), IsAnyRegister(), IsCalleeFrameSlot(), IsCallerFrameSlot(), and IsNullRegister().
GetSizeInPointers()
int v8::internal::LinkageLocation::GetSizeInPointers () const [inline]
Definition at line 119 of file linkage-location.h.
                                {
    return ElementSizeInPointers(GetType().representation());
  }
References v8::internal::ElementSizeInPointers(), and GetType().
Referenced by v8::internal::compiler::CallDescriptor::GetOffsetToFirstUnusedStackSlot(), v8::internal::compiler::CallDescriptor::GetTaggedParameterSlots(), and v8::internal::compiler::InstructionSelector::InitializeCallBuffer().
GetType()
MachineType v8::internal::LinkageLocation::GetType () const [inline]
Definition at line 117 of file linkage-location.h.
{ return machine_type_; }
References machine_type_.
Referenced by ConvertToTailCallerLocation(), GetSizeInPointers(), v8::internal::compiler::CallDescriptor::GetTaggedParameterSlots(), v8::internal::compiler::InstructionSelector::InitializeCallBuffer(), and v8::internal::compiler::OperandGenerator::ToUnallocatedOperand().
IsAnyRegister()
bool v8::internal::LinkageLocation::IsAnyRegister () const [inline]
Definition at line 136 of file linkage-location.h.
                             {
    return IsRegister() && GetLocation() == ANY_REGISTER;
  }
References ANY_REGISTER, GetLocation(), and IsRegister().
Referenced by v8::internal::compiler::InstructionSelector::InitializeCallBuffer(), and v8::internal::compiler::OperandGenerator::ToUnallocatedOperand().
IsCalleeFrameSlot()
bool v8::internal::LinkageLocation::IsCalleeFrameSlot () const [inline]
Definition at line 140 of file linkage-location.h.
{ return !IsRegister() && GetLocation() >= 0; }
References GetLocation(), and IsRegister().
Referenced by AsCalleeFrameSlot(), v8::internal::compiler::OperandGenerator::ToDualLocationUnallocatedOperand(), and v8::internal::compiler::OperandGenerator::ToUnallocatedOperand().
IsCallerFrameSlot()
bool v8::internal::LinkageLocation::IsCallerFrameSlot () const [inline]
Definition at line 139 of file linkage-location.h.
{ return !IsRegister() && GetLocation() < 0; }
References GetLocation(), and IsRegister().
Referenced by AsCallerFrameSlot(), v8::internal::compiler::CallDescriptor::CanTailCall(), v8::internal::compiler::CallDescriptor::GetOffsetToFirstUnusedStackSlot(), v8::internal::compiler::CallDescriptor::GetOffsetToReturns(), and v8::internal::compiler::OperandGenerator::ToUnallocatedOperand().
IsNullRegister()
bool v8::internal::LinkageLocation::IsNullRegister () const [inline]
Definition at line 130 of file linkage-location.h.
                              {
    return IsRegister() && GetLocation() < ANY_REGISTER;
  }
References ANY_REGISTER, GetLocation(), and IsRegister().
Referenced by v8::internal::compiler::InstructionSelector::InitializeCallBuffer(), and v8::internal::compiler::OperandGenerator::ToUnallocatedOperand().
IsRegister()
NO_INLINE_FOR_ARM64_MSVC bool v8::internal::LinkageLocation::IsRegister () const [inline]
Definition at line 133 of file linkage-location.h.
                                                   {
    return TypeField::decode(bit_field_) == REGISTER;
  }
References bit_field_, v8::base::BitField< T, shift, size, U >::decode(), and REGISTER.
Referenced by AsRegister(), ConvertToTailCallerLocation(), v8::internal::compiler::CallDescriptor::GetOffsetToFirstUnusedStackSlot(), v8::internal::compiler::CallDescriptor::GetOffsetToReturns(), v8::internal::compiler::CallDescriptor::GetTaggedParameterSlots(), v8::internal::compiler::InstructionSelector::InitializeCallBuffer(), IsAnyRegister(), IsCalleeFrameSlot(), IsCallerFrameSlot(), IsNullRegister(), and v8::internal::compiler::OperandGenerator::ToDualLocationUnallocatedOperand().
IsSameLocation()
static bool v8::internal::LinkageLocation::IsSameLocation (const LinkageLocation & a, const LinkageLocation & b) [inline], [static]
Definition at line 36 of file linkage-location.h.
                                                       {
    // Different MachineTypes may end up at the same physical location. With the
    // sub-type check we make sure that types like {AnyTagged} and
    // {TaggedPointer} which would end up with the same physical location are
    // considered equal here.
    return (a.bit_field_ == b.bit_field_) &&
           (IsSubtype(a.machine_type_.representation(),
                      b.machine_type_.representation()) ||
            IsSubtype(b.machine_type_.representation(),
                      a.machine_type_.representation()));
  }
References bit_field_, v8::internal::IsSubtype(), machine_type_, and v8::internal::MachineType::representation().
Referenced by v8::internal::compiler::CallDescriptor::CanTailCall().
operator!=()
bool v8::internal::LinkageLocation::operator!= (const LinkageLocation & other) const [inline]
Definition at line 32 of file linkage-location.h.
                                                      {
    return !(*this == other);
  }
operator==()
bool v8::internal::LinkageLocation::operator== (const LinkageLocation & other) const [inline]
Definition at line 27 of file linkage-location.h.
                                                      {
    return bit_field_ == other.bit_field_ &&
           machine_type_ == other.machine_type_;
  }
References bit_field_, and machine_type_.
Member Data Documentation
ANY_REGISTER
constexpr int32_t v8::internal::LinkageLocation::ANY_REGISTER = -1 [static], [constexpr], [private]
Definition at line 161 of file linkage-location.h.
Referenced by ForAnyRegister(), IsAnyRegister(), and IsNullRegister().
bit_field_
int32_t v8::internal::LinkageLocation::bit_field_ [private]
Definition at line 173 of file linkage-location.h.
Referenced by GetLocation(), IsRegister(), IsSameLocation(), LinkageLocation(), and operator==().
machine_type_
MachineType v8::internal::LinkageLocation::machine_type_ [private]
Definition at line 174 of file linkage-location.h.
Referenced by GetType(), IsSameLocation(), LinkageLocation(), and operator==().
MAX_STACK_SLOT
constexpr int32_t v8::internal::LinkageLocation::MAX_STACK_SLOT = 32767 [static], [constexpr], [private]
Definition at line 162 of file linkage-location.h.
Referenced by ForCalleeFrameSlot().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/codegen/linkage-location.h