v8::internal::maglev::FixedInputNodeTMixin< InputCount, Base, Derived > Class Template Reference
#include <maglev-ir.h>
Inherits v8::internal::maglev::NodeTMixin< Base, Derived >.
Inherited by v8::internal::maglev::AbstractLoadTaggedField< LoadTaggedFieldForContextSlotNoCells >, v8::internal::maglev::AbstractLoadTaggedField< LoadTaggedFieldForProperty >, v8::internal::maglev::AbstractLoadTaggedField< LoadTaggedField >, v8::internal::maglev::BranchControlNodeT< 2, BranchIfFloat64Compare >, v8::internal::maglev::BranchControlNodeT< 1, BranchIfUndefinedOrNull >, v8::internal::maglev::BranchControlNodeT< 1, BranchIfRootConstant >, v8::internal::maglev::BranchControlNodeT< 1, BranchIfJSReceiver >, v8::internal::maglev::BranchControlNodeT< 1, BranchIfFloat64IsHole >, v8::internal::maglev::BranchControlNodeT< 1, BranchIfUndetectable >, v8::internal::maglev::BranchControlNodeT< 1, BranchIfToBooleanTrue >, v8::internal::maglev::BranchControlNodeT< 2, BranchIfReferenceEqual >, v8::internal::maglev::BranchControlNodeT< 1, BranchIfInt32ToBooleanTrue >, v8::internal::maglev::BranchControlNodeT< 2, BranchIfInt32Compare >, v8::internal::maglev::BranchControlNodeT< 2, BranchIfUint32Compare >, v8::internal::maglev::BranchControlNodeT< 1, BranchIfIntPtrToBooleanTrue >, v8::internal::maglev::BranchControlNodeT< 1, BranchIfTypeOf >, v8::internal::maglev::BranchControlNodeT< 1, BranchIfSmi >, v8::internal::maglev::BranchControlNodeT< 1, BranchIfFloat64ToBooleanTrue >, v8::internal::maglev::TerminalControlNodeT< 0, Deopt >, v8::internal::maglev::TerminalControlNodeT< 0, Abort >, v8::internal::maglev::TerminalControlNodeT< 1, Return >, v8::internal::maglev::UnconditionalControlNodeT< JumpLoop >, v8::internal::maglev::UnconditionalControlNodeT< CheckpointedJump >, v8::internal::maglev::UnconditionalControlNodeT< Jump >, v8::internal::maglev::AbstractLoadTaggedField< Derived >, v8::internal::maglev::AllocateElementsArray, v8::internal::maglev::AllocationBlock, v8::internal::maglev::ArgumentsElements, v8::internal::maglev::ArgumentsLength, v8::internal::maglev::AssertInt32, v8::internal::maglev::BinaryWithFeedbackNode< Derived, kOperation >, v8::internal::maglev::BuiltinSeqOneByteStringCharCodeAt, v8::internal::maglev::BuiltinStringFromCharCode, v8::internal::maglev::BuiltinStringPrototypeCharCodeOrCodePointAt, v8::internal::maglev::CallWithArrayLike, v8::internal::maglev::ChangeInt32ToFloat64, v8::internal::maglev::ChangeIntPtrToFloat64, v8::internal::maglev::ChangeUint32ToFloat64, v8::internal::maglev::CheckCacheIndicesNotCleared, v8::internal::maglev::CheckConstructResult, v8::internal::maglev::CheckDerivedConstructResult, v8::internal::maglev::CheckDetectableCallable, v8::internal::maglev::CheckDynamicValue, v8::internal::maglev::CheckFloat64SameValue, v8::internal::maglev::CheckHeapObject, v8::internal::maglev::CheckHoleyFloat64IsSmi, v8::internal::maglev::CheckHoleyFloat64NotHole, v8::internal::maglev::CheckInstanceType, v8::internal::maglev::CheckInt32Condition, v8::internal::maglev::CheckInt32IsSmi, v8::internal::maglev::CheckIntPtrIsSmi, v8::internal::maglev::CheckJSDataViewBounds, v8::internal::maglev::CheckJSReceiverOrNullOrUndefined, v8::internal::maglev::CheckMaps, v8::internal::maglev::CheckMapsWithAlreadyLoadedMap, v8::internal::maglev::CheckMapsWithMigration, v8::internal::maglev::CheckMapsWithMigrationAndDeopt, v8::internal::maglev::CheckNotHole, v8::internal::maglev::CheckNumber, v8::internal::maglev::CheckSeqOneByteString, v8::internal::maglev::CheckSmi, v8::internal::maglev::CheckString, v8::internal::maglev::CheckStringOrOddball, v8::internal::maglev::CheckStringOrStringWrapper, v8::internal::maglev::CheckSymbol, v8::internal::maglev::CheckTypedArrayBounds, v8::internal::maglev::CheckTypedArrayNotDetached, v8::internal::maglev::CheckUint32IsSmi, v8::internal::maglev::CheckValue, v8::internal::maglev::CheckValueEqualsInt32, v8::internal::maglev::CheckValueEqualsString, v8::internal::maglev::CheckedHoleyFloat64ToFloat64, v8::internal::maglev::CheckedInt32ToUint32, v8::internal::maglev::CheckedIntPtrToInt32, v8::internal::maglev::CheckedIntPtrToUint32, v8::internal::maglev::CheckedInternalizedString, v8::internal::maglev::CheckedNumberOrOddballToHoleyFloat64, v8::internal::maglev::CheckedNumberToInt32, v8::internal::maglev::CheckedNumberToUint8Clamped, v8::internal::maglev::CheckedObjectToIndex, v8::internal::maglev::CheckedSmiDecrement, v8::internal::maglev::CheckedSmiIncrement, v8::internal::maglev::CheckedSmiSizedInt32, v8::internal::maglev::CheckedSmiTagFloat64, v8::internal::maglev::CheckedSmiTagInt32, v8::internal::maglev::CheckedSmiTagIntPtr, v8::internal::maglev::CheckedSmiTagUint32, v8::internal::maglev::CheckedSmiUntag, v8::internal::maglev::CheckedTruncateFloat64ToInt32, v8::internal::maglev::CheckedTruncateFloat64ToUint32, v8::internal::maglev::CheckedTruncateNumberOrOddballToInt32, v8::internal::maglev::CheckedUint32ToInt32, v8::internal::maglev::ConsStringMap, v8::internal::maglev::Constant, v8::internal::maglev::ConstantGapMove, v8::internal::maglev::ConvertHoleToUndefined, v8::internal::maglev::ConvertReceiver, v8::internal::maglev::CreateArrayLiteral, v8::internal::maglev::CreateClosure, v8::internal::maglev::CreateFastArrayElements, v8::internal::maglev::CreateFunctionContext, v8::internal::maglev::CreateObjectLiteral, v8::internal::maglev::CreateRegExpLiteral, v8::internal::maglev::CreateShallowArrayLiteral, v8::internal::maglev::CreateShallowObjectLiteral, v8::internal::maglev::DebugBreak, v8::internal::maglev::DefineKeyedOwnGeneric, v8::internal::maglev::DefineNamedOwnGeneric, v8::internal::maglev::DeleteProperty, v8::internal::maglev::EnsureWritableFastElements, v8::internal::maglev::ExtendPropertiesBackingStore, v8::internal::maglev::FastCreateClosure, v8::internal::maglev::Float64Abs, v8::internal::maglev::Float64BinaryNode< Derived, kOperation >, v8::internal::maglev::Float64BinaryNodeWithCall< Derived, kOperation >, v8::internal::maglev::Float64Compare, v8::internal::maglev::Float64Constant, v8::internal::maglev::Float64CountLeadingZeros, v8::internal::maglev::Float64Ieee754Unary, v8::internal::maglev::Float64Negate, v8::internal::maglev::Float64Round, v8::internal::maglev::Float64ToBoolean, v8::internal::maglev::Float64ToHeapNumberForField, v8::internal::maglev::Float64ToTagged, v8::internal::maglev::Float64ToUint8Clamped, v8::internal::maglev::ForInNext, v8::internal::maglev::ForInPrepare, v8::internal::maglev::FunctionEntryStackCheck, v8::internal::maglev::GapMove, v8::internal::maglev::GeneratorRestoreRegister, v8::internal::maglev::GetContinuationPreservedEmbedderData, v8::internal::maglev::GetIterator, v8::internal::maglev::GetKeyedGeneric, v8::internal::maglev::GetSecondReturnedValue, v8::internal::maglev::GetTemplateObject, v8::internal::maglev::HandleNoHeapWritesInterrupt, v8::internal::maglev::HasInPrototypeChain, v8::internal::maglev::HoleyFloat64IsHole, v8::internal::maglev::HoleyFloat64ToMaybeNanFloat64, v8::internal::maglev::HoleyFloat64ToTagged, v8::internal::maglev::Identity, v8::internal::maglev::InitialValue, v8::internal::maglev::InlinedAllocation, v8::internal::maglev::Int32AbsWithOverflow, v8::internal::maglev::Int32BinaryNode< Derived, kOperation >, v8::internal::maglev::Int32BinaryWithOverflowNode< Derived, kOperation >, v8::internal::maglev::Int32BitwiseNot, v8::internal::maglev::Int32Compare, v8::internal::maglev::Int32Constant, v8::internal::maglev::Int32CountLeadingZeros, v8::internal::maglev::Int32ShiftRightLogical, v8::internal::maglev::Int32ToBoolean, v8::internal::maglev::Int32ToNumber, v8::internal::maglev::Int32ToUint8Clamped, v8::internal::maglev::Int32UnaryWithOverflowNode< Derived, kOperation >, v8::internal::maglev::IntPtrConstant, v8::internal::maglev::IntPtrToBoolean, v8::internal::maglev::IntPtrToNumber, v8::internal::maglev::LoadDoubleDataViewElement, v8::internal::maglev::LoadDoubleField, v8::internal::maglev::LoadEnumCacheLength, v8::internal::maglev::LoadFixedArrayElement, v8::internal::maglev::LoadFixedDoubleArrayElement, v8::internal::maglev::LoadFloat64, v8::internal::maglev::LoadGlobal, v8::internal::maglev::LoadHoleyFixedDoubleArrayElement, v8::internal::maglev::LoadHoleyFixedDoubleArrayElementCheckedNotHole, v8::internal::maglev::LoadInt32, v8::internal::maglev::LoadNamedFromSuperGeneric, v8::internal::maglev::LoadNamedGeneric, v8::internal::maglev::LoadSignedIntDataViewElement, v8::internal::maglev::LoadTaggedFieldByFieldIndex, v8::internal::maglev::LoadTaggedFieldForContextSlot, v8::internal::maglev::LoadTypedArrayLength, v8::internal::maglev::LogicalNot, v8::internal::maglev::MapPrototypeGet, v8::internal::maglev::MapPrototypeGetInt32Key, v8::internal::maglev::MaybeGrowFastElements, v8::internal::maglev::MigrateMapIfNeeded, v8::internal::maglev::NumberToString, v8::internal::maglev::ReduceInterruptBudgetForLoop, v8::internal::maglev::ReduceInterruptBudgetForReturn, v8::internal::maglev::RegisterInput, v8::internal::maglev::RestLength, v8::internal::maglev::RootConstant, v8::internal::maglev::SeqOneByteStringAt, v8::internal::maglev::SetContinuationPreservedEmbedderData, v8::internal::maglev::SetKeyedGeneric, v8::internal::maglev::SetNamedGeneric, v8::internal::maglev::SetPendingMessage, v8::internal::maglev::SetPrototypeHas, v8::internal::maglev::SmiConstant, v8::internal::maglev::SmiCountLeadingZeros, v8::internal::maglev::StoreContextSlotWithWriteBarrier, v8::internal::maglev::StoreDoubleDataViewElement, v8::internal::maglev::StoreDoubleField, v8::internal::maglev::StoreFixedArrayElementNoWriteBarrier, v8::internal::maglev::StoreFixedArrayElementWithWriteBarrier, v8::internal::maglev::StoreFixedDoubleArrayElement, v8::internal::maglev::StoreFloat64, v8::internal::maglev::StoreGlobal, v8::internal::maglev::StoreInArrayLiteralGeneric, v8::internal::maglev::StoreInt32, v8::internal::maglev::StoreMap, v8::internal::maglev::StoreSignedIntDataViewElement, v8::internal::maglev::StoreTaggedFieldNoWriteBarrier, v8::internal::maglev::StoreTaggedFieldWithWriteBarrier, v8::internal::maglev::StoreTrustedPointerFieldWithWriteBarrier, v8::internal::maglev::StringAt, v8::internal::maglev::StringConcat, v8::internal::maglev::StringEqual, v8::internal::maglev::StringLength, v8::internal::maglev::TaggedEqual, v8::internal::maglev::TaggedIndexConstant, v8::internal::maglev::TaggedNotEqual, v8::internal::maglev::TestInstanceOf, v8::internal::maglev::TestTypeOf, v8::internal::maglev::TestUndetectable, v8::internal::maglev::ThrowIfNotCallable, v8::internal::maglev::ThrowIfNotSuperConstructor, v8::internal::maglev::ThrowReferenceErrorIfHole, v8::internal::maglev::ThrowSuperAlreadyCalledIfNotHole, v8::internal::maglev::ThrowSuperNotCalledIfHole, v8::internal::maglev::ToBoolean, v8::internal::maglev::ToBooleanLogicalNot, v8::internal::maglev::ToName, v8::internal::maglev::ToNumberOrNumeric, v8::internal::maglev::ToObject, v8::internal::maglev::ToString, v8::internal::maglev::TransitionAndStoreArrayElement, v8::internal::maglev::TransitionElementsKind, v8::internal::maglev::TransitionElementsKindOrCheckMap, v8::internal::maglev::TruncateNumberOrOddballToInt32, v8::internal::maglev::TrustedConstant, v8::internal::maglev::TryOnStackReplacement, v8::internal::maglev::Uint32Constant, v8::internal::maglev::Uint32ToNumber, v8::internal::maglev::Uint32ToUint8Clamped, v8::internal::maglev::UnaryWithFeedbackNode< Derived, kOperation >, v8::internal::maglev::UncheckedNumberOrOddballToFloat64, v8::internal::maglev::UnsafeInt32ToUint32, v8::internal::maglev::UnsafeSmiTagInt32, v8::internal::maglev::UnsafeSmiTagIntPtr, v8::internal::maglev::UnsafeSmiTagUint32, v8::internal::maglev::UnsafeSmiUntag, v8::internal::maglev::UnwrapStringWrapper, v8::internal::maglev::UpdateJSArrayLength, and v8::internal::maglev::VirtualObject.
Public Member Functions
constexpr bool has_inputs () const
constexpr uint16_t input_count () const
constexpr auto end ()
void VerifyInputs (MaglevGraphLabeller *graph_labeller) const
Static Public Attributes
static constexpr size_t kInputCount = InputCount
Protected Types
using InputTypes = detail::ArrayWrapper< kInputCount >
Protected Member Functions
template<typename... Args>
FixedInputNodeTMixin (uint64_t bitfield, Args &&... args)
Protected Attributes
detail::YouNeedToDefineAnInputTypesArrayInYourDerivedClass kInputTypes
Additional Inherited Members
Detailed Description
template<size_t InputCount, typename Base, typename Derived>
class v8::internal::maglev::FixedInputNodeTMixin< InputCount, Base, Derived >
Definition at line 2987 of file maglev-ir.h.
Member Typedef Documentation
InputTypes
template<size_t InputCount, typename Base , typename Derived >
using v8::internal::maglev::FixedInputNodeTMixin< InputCount, Base, Derived >::InputTypes = detail::ArrayWrapper<kInputCount> [protected]
Definition at line 3026 of file maglev-ir.h.
Constructor & Destructor Documentation
FixedInputNodeTMixin()
template<size_t InputCount, typename Base , typename Derived >
template<typename... Args>
v8::internal::maglev::FixedInputNodeTMixin< InputCount, Base, Derived >::FixedInputNodeTMixin (uint64_t bitfield, Args &&... args) [inline], [explicit], [protected]
Definition at line 3030 of file maglev-ir.h.
      : NodeTMixin<Base, Derived>(bitfield, std::forward<Args>(args)...) {
    DCHECK_EQ(this->NodeBase::input_count(), kInputCount);
  }
References DCHECK_EQ, and v8::internal::maglev::NodeBase::input_count().
Member Function Documentation
end()
template<size_t InputCount, typename Base , typename Derived >
constexpr auto v8::internal::maglev::FixedInputNodeTMixin< InputCount, Base, Derived >::end () [inline], [constexpr]
Definition at line 2994 of file maglev-ir.h.
                       {
    return std::make_reverse_iterator(&this->input(input_count() - 1));
  }
References v8::internal::maglev::FixedInputNodeTMixin< InputCount, Base, Derived >::input_count().
has_inputs()
template<size_t InputCount, typename Base , typename Derived >
constexpr bool v8::internal::maglev::FixedInputNodeTMixin< InputCount, Base, Derived >::has_inputs () const [inline], [constexpr]
Definition at line 2992 of file maglev-ir.h.
{ return input_count() > 0; }
References v8::internal::maglev::FixedInputNodeTMixin< InputCount, Base, Derived >::input_count().
input_count()
template<size_t InputCount, typename Base , typename Derived >
constexpr uint16_t v8::internal::maglev::FixedInputNodeTMixin< InputCount, Base, Derived >::input_count () const [inline], [constexpr]
Definition at line 2993 of file maglev-ir.h.
{ return kInputCount; }
References v8::internal::maglev::FixedInputNodeTMixin< InputCount, Base, Derived >::kInputCount.
Referenced by v8::internal::maglev::FixedInputNodeTMixin< InputCount, Base, Derived >::end(), v8::internal::maglev::FixedInputNodeTMixin< InputCount, Base, Derived >::has_inputs(), and v8::internal::maglev::CallWithArrayLike::VerifyInputs().
VerifyInputs()
template<size_t InputCount, typename Base , typename Derived >
void v8::internal::maglev::FixedInputNodeTMixin< InputCount, Base, Derived >::VerifyInputs (MaglevGraphLabeller * graph_labeller) const [inline]
Definition at line 2998 of file maglev-ir.h.
                                                               {
    if constexpr (kInputCount != 0) {
      static_assert(
          std::is_same_v<const InputTypes, decltype(Derived::kInputTypes)>);
      static_assert(kInputCount == Derived::kInputTypes.size());
      for (int i = 0; i < static_cast<int>(kInputCount); ++i) {
        CheckValueInputIs(this, i, Derived::kInputTypes[i], graph_labeller);
      }
    }
  }
References v8::internal::maglev::CheckValueInputIs(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::maglev::FixedInputNodeTMixin< InputCount, Base, Derived >::kInputCount, and size().
Referenced by v8::internal::maglev::InlinedAllocation::VerifyInputs(), and v8::internal::maglev::StoreTaggedFieldNoWriteBarrier::VerifyInputs().
Member Data Documentation
kInputCount
template<size_t InputCount, typename Base , typename Derived >
constexpr size_t v8::internal::maglev::FixedInputNodeTMixin< InputCount, Base, Derived >::kInputCount = InputCount [static], [constexpr]
Definition at line 2989 of file maglev-ir.h.
Referenced by v8::internal::maglev::FixedInputNodeTMixin< InputCount, Base, Derived >::input_count(), and v8::internal::maglev::FixedInputNodeTMixin< InputCount, Base, Derived >::VerifyInputs().
kInputTypes
template<size_t InputCount, typename Base , typename Derived >
detail::YouNeedToDefineAnInputTypesArrayInYourDerivedClass v8::internal::maglev::FixedInputNodeTMixin< InputCount, Base, Derived >::kInputTypes [protected]
Definition at line 3027 of file maglev-ir.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h