v8_inspector::anonymous_namespace{v8-console-message.cc}::V8ValueStringBuilder Class Reference
Static Public Member Functions
static String16 toString (v8::Local< v8::Value > value, v8::Local< v8::Context > context)
Private Types
enum { IgnoreNull = 1 << 0
, IgnoreUndefined = 1 << 1
 }
Private Member Functions
V8ValueStringBuilder (v8::Local< v8::Context > context)
bool append (v8::Local< v8::Value > value, unsigned ignoreOptions=0)
bool append (v8::Local< v8::Array > array)
bool append (v8::Local< v8::Symbol > symbol)
bool append (v8::Local< v8::BigInt > bigint)
bool append (v8::Local< v8::String > string)
String16 toString ()
Private Attributes
uint32_t m_arrayLimit
v8::Isolate * m_isolate
String16Builder m_builder
v8::LocalVector< v8::Array > m_visitedArrays
v8::TryCatch m_tryCatch
v8::Local< v8::Context > m_context
Detailed Description
Definition at line 72 of file v8-console-message.cc.
Member Enumeration Documentation
anonymous enum
anonymous enum [private]
Enumerator
IgnoreNull
IgnoreUndefined
Definition at line 82 of file v8-console-message.cc.
       {
    IgnoreNull = 1 << 0,
    IgnoreUndefined = 1 << 1,
  };
Constructor & Destructor Documentation
V8ValueStringBuilder()
v8_inspector::anonymous_namespace{v8-console-message.cc}::V8ValueStringBuilder::V8ValueStringBuilder (v8::Local< v8::Context > context) [inline], [explicit], [private]
Definition at line 87 of file v8-console-message.cc.
      : m_arrayLimit(maxArrayItemsLimit),
        m_isolate(v8::Isolate::GetCurrent()),
        m_visitedArrays(v8::Isolate::GetCurrent()),
        m_tryCatch(v8::Isolate::GetCurrent()),
        m_context(context) {}
Member Function Documentation
append() [1/5]
bool v8_inspector::anonymous_namespace{v8-console-message.cc}::V8ValueStringBuilder::append (v8::Local< v8::Array > array) [inline], [private]
Definition at line 131 of file v8-console-message.cc.
                                      {
    for (const auto& it : m_visitedArrays) {
      if (it == array) return true;
    }
    uint32_t length = array->Length();
    if (length > m_arrayLimit) return false;
    if (m_visitedArrays.size() > maxStackDepthLimit) return false;
    bool result = true;
    m_arrayLimit -= length;
    m_visitedArrays.push_back(array);
    for (uint32_t i = 0; i < length; ++i) {
      if (i) m_builder.append(',');
      v8::Local<v8::Value> value;
      if (!array->Get(m_context, i).ToLocal(&value)) continue;
      if (!append(value, IgnoreNull | IgnoreUndefined)) {
        result = false;
        break;
      }
    }
    m_visitedArrays.pop_back();
    return result;
  }
References v8::Object::Get(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::Array::Length(), v8::internal::length, v8_inspector::anonymous_namespace{v8-console-message.cc}::maxStackDepthLimit, v8::base::internal::result, v8::MaybeLocal< T >::ToLocal(), and v8::internal::value.
append() [2/5]
bool v8_inspector::anonymous_namespace{v8-console-message.cc}::V8ValueStringBuilder::append (v8::Local< v8::BigInt > bigint) [inline], [private]
Definition at line 162 of file v8-console-message.cc.
                                        {
    v8::Local<v8::String> bigint_string;
    if (!bigint->ToString(m_context).ToLocal(&bigint_string)) return false;
    bool result = append(bigint_string);
    if (m_tryCatch.HasCaught()) return false;
    m_builder.append('n');
    return result;
  }
References v8::base::internal::result.
append() [3/5]
bool v8_inspector::anonymous_namespace{v8-console-message.cc}::V8ValueStringBuilder::append (v8::Local< v8::String > string) [inline], [private]
Definition at line 171 of file v8-console-message.cc.
                                        {
    if (m_tryCatch.HasCaught()) return false;
    if (!string.IsEmpty()) {
      m_builder.append(toProtocolString(m_isolate, string));
    }
    return true;
  }
References v8_inspector::toProtocolString().
append() [4/5]
bool v8_inspector::anonymous_namespace{v8-console-message.cc}::V8ValueStringBuilder::append (v8::Local< v8::Symbol > symbol) [inline], [private]
Definition at line 155 of file v8-console-message.cc.
                                        {
    m_builder.append("Symbol(");
    bool result = append(symbol->Description(m_isolate), IgnoreUndefined);
    m_builder.append(')');
    return result;
  }
References v8::base::internal::result.
append() [5/5]
bool v8_inspector::anonymous_namespace{v8-console-message.cc}::V8ValueStringBuilder::append (v8::Local< v8::Value > value, unsigned ignoreOptions = 0) [inline], [private]
Definition at line 94 of file v8-console-message.cc.
                                                                  {
    if (value.IsEmpty()) return true;
    if ((ignoreOptions & IgnoreNull) && value->IsNull()) return true;
    if ((ignoreOptions & IgnoreUndefined) && value->IsUndefined()) return true;
    if (value->IsBigIntObject()) {
      value = value.As<v8::BigIntObject>()->ValueOf();
    } else if (value->IsBooleanObject()) {
      value =
          v8::Boolean::New(m_isolate, value.As<v8::BooleanObject>()->ValueOf());
    } else if (value->IsNumberObject()) {
      value =
          v8::Number::New(m_isolate, value.As<v8::NumberObject>()->ValueOf());
    } else if (value->IsStringObject()) {
      value = value.As<v8::StringObject>()->ValueOf();
    } else if (value->IsSymbolObject()) {
      value = value.As<v8::SymbolObject>()->ValueOf();
    }
    if (value->IsString()) return append(value.As<v8::String>());
    if (value->IsBigInt()) return append(value.As<v8::BigInt>());
    if (value->IsSymbol()) return append(value.As<v8::Symbol>());
    if (value->IsArray()) return append(value.As<v8::Array>());
    if (value->IsProxy()) {
      m_builder.append("[object Proxy]");
      return true;
    }
    if (value->IsObject() && !value->IsDate() && !value->IsFunction() &&
        !value->IsNativeError() && !value->IsRegExp()) {
      v8::Local<v8::Object> object = value.As<v8::Object>();
      v8::Local<v8::String> stringValue;
      if (object->ObjectProtoToString(m_context).ToLocal(&stringValue))
        return append(stringValue);
    }
    v8::Local<v8::String> stringValue;
    if (!value->ToString(m_context).ToLocal(&stringValue)) return false;
    return append(stringValue);
  }
References v8::Boolean::New(), v8::Number::New(), v8::Object::ObjectProtoToString(), v8::internal::value, v8::NumberObject::ValueOf(), and v8::BooleanObject::ValueOf().
Referenced by toString().
toString() [1/2]
String16 v8_inspector::anonymous_namespace{v8-console-message.cc}::V8ValueStringBuilder::toString () [inline], [private]
Definition at line 179 of file v8-console-message.cc.
                      {
    if (m_tryCatch.HasCaught()) return String16();
    return m_builder.toString();
  }
toString() [2/2]
static String16 v8_inspector::anonymous_namespace{v8-console-message.cc}::V8ValueStringBuilder::toString (v8::Local< v8::Value > value, v8::Local< v8::Context > context) [inline], [static]
Definition at line 74 of file v8-console-message.cc.
                                                       {
    V8ValueStringBuilder builder(context);
    if (!builder.append(value)) return String16();
    return builder.toString();
  }
References append(), toString(), and v8::internal::value.
Referenced by toString().
Member Data Documentation
m_arrayLimit
uint32_t v8_inspector::anonymous_namespace{v8-console-message.cc}::V8ValueStringBuilder::m_arrayLimit [private]
Definition at line 184 of file v8-console-message.cc.
m_builder
String16Builder v8_inspector::anonymous_namespace{v8-console-message.cc}::V8ValueStringBuilder::m_builder [private]
Definition at line 186 of file v8-console-message.cc.
m_context
v8::Local<v8::Context> v8_inspector::anonymous_namespace{v8-console-message.cc}::V8ValueStringBuilder::m_context [private]
Definition at line 189 of file v8-console-message.cc.
m_isolate
v8::Isolate* v8_inspector::anonymous_namespace{v8-console-message.cc}::V8ValueStringBuilder::m_isolate [private]
Definition at line 185 of file v8-console-message.cc.
m_tryCatch
v8::TryCatch v8_inspector::anonymous_namespace{v8-console-message.cc}::V8ValueStringBuilder::m_tryCatch [private]
Definition at line 188 of file v8-console-message.cc.
m_visitedArrays
v8::LocalVector<v8::Array> v8_inspector::anonymous_namespace{v8-console-message.cc}::V8ValueStringBuilder::m_visitedArrays [private]
Definition at line 187 of file v8-console-message.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/inspector/v8-console-message.cc