v8::internal::compiler::GraphAssemblerLabel< VarCount > Class Template Reference
#include <graph-assembler.h>
Public Member Functions
size_t Count ()
Node * PhiAt (size_t index)
template<typename T >
TNode< T > PhiAt (size_t index)
bool IsUsed () const
GraphAssemblerLabel (GraphAssemblerLabelType type, int loop_nesting_level, Array< MachineRepresentation > reps)
~GraphAssemblerLabel ()
Private Types
using Helper = detail::GraphAssemblerHelper< VarCount >
template<typename T >
using Array = typename Helper::template Array< T >
Private Member Functions
void SetBound ()
bool IsBound () const
bool IsDeferred () const
bool IsLoop () const
Private Attributes
bool is_bound_ = false
const GraphAssemblerLabelType type_
const int loop_nesting_level_
size_t merged_count_ = 0
Node * effect_
Node * control_
Array< Node * > bindings_
const Array< MachineRepresentation > representations_
Static Private Attributes
static constexpr bool kIsDynamic = Helper::kIsDynamic
Friends
class GraphAssembler
Detailed Description
template<size_t VarCount>
class v8::internal::compiler::GraphAssemblerLabel< VarCount >
Definition at line 192 of file graph-assembler.h.
Member Typedef Documentation
Array
template<size_t VarCount>
template<typename T >
using v8::internal::compiler::GraphAssemblerLabel< VarCount >::Array = typename Helper::template Array<T> [private]
Definition at line 195 of file graph-assembler.h.
Helper
template<size_t VarCount>
using v8::internal::compiler::GraphAssemblerLabel< VarCount >::Helper = detail::GraphAssemblerHelper<VarCount> [private]
Definition at line 193 of file graph-assembler.h.
Constructor & Destructor Documentation
GraphAssemblerLabel()
template<size_t VarCount>
v8::internal::compiler::GraphAssemblerLabel< VarCount >::GraphAssemblerLabel (GraphAssemblerLabelType type, int loop_nesting_level, Array< MachineRepresentation > reps) [inline]
Definition at line 212 of file graph-assembler.h.
      : type_(type),
        loop_nesting_level_(loop_nesting_level),
        bindings_(Helper::InitNodeArray(reps)),
        representations_(std::move(reps)) {}
 GraphAssemblerLabel()
template<size_t VarCount>
v8::internal::compiler::GraphAssemblerLabel< VarCount >::~GraphAssemblerLabel () [inline]
Definition at line 219 of file graph-assembler.h.
{ DCHECK(IsBound() || merged_count_ == 0); }
References v8::internal::DCHECK(), v8::internal::compiler::GraphAssemblerLabel< VarCount >::IsBound(), and v8::internal::compiler::GraphAssemblerLabel< VarCount >::merged_count_.
Member Function Documentation
Count()
template<size_t VarCount>
size_t v8::internal::compiler::GraphAssemblerLabel< VarCount >::Count () [inline]
Definition at line 199 of file graph-assembler.h.
{ return representations_.size(); }
References v8::internal::compiler::GraphAssemblerLabel< VarCount >::representations_.
Referenced by v8::internal::compiler::GraphAssembler::Bind().
IsBound()
template<size_t VarCount>
bool v8::internal::compiler::GraphAssemblerLabel< VarCount >::IsBound () const [inline], [private]
Definition at line 228 of file graph-assembler.h.
{ return is_bound_; }
References v8::internal::compiler::GraphAssemblerLabel< VarCount >::is_bound_.
Referenced by v8::internal::compiler::GraphAssemblerLabel< VarCount >::SetBound(), and v8::internal::compiler::GraphAssemblerLabel< VarCount >::~GraphAssemblerLabel().
IsDeferred()
template<size_t VarCount>
bool v8::internal::compiler::GraphAssemblerLabel< VarCount >::IsDeferred () const [inline], [private]
Definition at line 229 of file graph-assembler.h.
                          {
    return type_ == GraphAssemblerLabelType::kDeferred;
  }
References v8::internal::compiler::kDeferred, and v8::internal::compiler::GraphAssemblerLabel< VarCount >::type_.
Referenced by v8::internal::compiler::GraphAssembler::BranchWithCriticalSafetyCheck().
IsLoop()
template<size_t VarCount>
bool v8::internal::compiler::GraphAssemblerLabel< VarCount >::IsLoop () const [inline], [private]
Definition at line 232 of file graph-assembler.h.
{ return type_ == GraphAssemblerLabelType::kLoop; }
References v8::internal::compiler::kLoop, and v8::internal::compiler::GraphAssemblerLabel< VarCount >::type_.
Referenced by v8::internal::compiler::GraphAssembler::Bind().
IsUsed()
template<size_t VarCount>
bool v8::internal::compiler::GraphAssemblerLabel< VarCount >::IsUsed () const [inline]
Definition at line 210 of file graph-assembler.h.
{ return merged_count_ > 0; }
References v8::internal::compiler::GraphAssemblerLabel< VarCount >::merged_count_.
PhiAt() [1/2]
template<size_t VarCount>
Node * v8::internal::compiler::GraphAssemblerLabel< VarCount >::PhiAt (size_t index)
Definition at line 679 of file graph-assembler.h.
                                                       {
  DCHECK(IsBound());
  DCHECK_LT(index, Count());
  return bindings_[index];
}
References v8::internal::DCHECK(), DCHECK_LT, and v8::internal::index.
Referenced by v8::internal::compiler::GraphAssemblerLabel< VarCount >::PhiAt().
PhiAt() [2/2]
template<size_t VarCount>
template<typename T >
TNode<T> v8::internal::compiler::GraphAssemblerLabel< VarCount >::PhiAt (size_t index) [inline]
Definition at line 204 of file graph-assembler.h.
                               {
    // TODO(jgruber): Investigate issues on ptr compression bots and enable.
    // DCHECK(IsMachineRepresentationOf<T>(representations_[index]));
    return TNode<T>::UncheckedCast(PhiAt(index));
  }
References v8::internal::index, v8::internal::compiler::GraphAssemblerLabel< VarCount >::PhiAt(), and v8::internal::TNode< T >::UncheckedCast().
SetBound()
template<size_t VarCount>
void v8::internal::compiler::GraphAssemblerLabel< VarCount >::SetBound () [inline], [private]
Definition at line 224 of file graph-assembler.h.
                  {
    DCHECK(!IsBound());
    is_bound_ = true;
  }
References v8::internal::DCHECK(), v8::internal::compiler::GraphAssemblerLabel< VarCount >::is_bound_, and v8::internal::compiler::GraphAssemblerLabel< VarCount >::IsBound().
Referenced by v8::internal::compiler::GraphAssembler::Bind().
Friends And Related Function Documentation
GraphAssembler
template<size_t VarCount>
friend class GraphAssembler [friend]
Definition at line 222 of file graph-assembler.h.
Member Data Documentation
bindings_
template<size_t VarCount>
Array<Node*> v8::internal::compiler::GraphAssemblerLabel< VarCount >::bindings_ [private]
Definition at line 240 of file graph-assembler.h.
Referenced by v8::internal::compiler::GraphAssembler::Bind().
control_
template<size_t VarCount>
Node* v8::internal::compiler::GraphAssemblerLabel< VarCount >::control_ [private]
Definition at line 239 of file graph-assembler.h.
Referenced by v8::internal::compiler::GraphAssembler::Bind().
effect_
template<size_t VarCount>
Node* v8::internal::compiler::GraphAssemblerLabel< VarCount >::effect_ [private]
Definition at line 238 of file graph-assembler.h.
Referenced by v8::internal::compiler::GraphAssembler::Bind().
is_bound_
template<size_t VarCount>
bool v8::internal::compiler::GraphAssemblerLabel< VarCount >::is_bound_ = false [private]
Definition at line 234 of file graph-assembler.h.
Referenced by v8::internal::compiler::GraphAssemblerLabel< VarCount >::IsBound(), and v8::internal::compiler::GraphAssemblerLabel< VarCount >::SetBound().
kIsDynamic
template<size_t VarCount>
constexpr bool v8::internal::compiler::GraphAssemblerLabel< VarCount >::kIsDynamic = Helper::kIsDynamic [static], [constexpr], [private]
Definition at line 196 of file graph-assembler.h.
loop_nesting_level_
template<size_t VarCount>
const int v8::internal::compiler::GraphAssemblerLabel< VarCount >::loop_nesting_level_ [private]
Definition at line 236 of file graph-assembler.h.
Referenced by v8::internal::compiler::GraphAssembler::Bind().
merged_count_
template<size_t VarCount>
size_t v8::internal::compiler::GraphAssemblerLabel< VarCount >::merged_count_ = 0 [private]
Definition at line 237 of file graph-assembler.h.
Referenced by v8::internal::compiler::GraphAssembler::Bind(), v8::internal::compiler::GraphAssemblerLabel< VarCount >::IsUsed(), and v8::internal::compiler::GraphAssemblerLabel< VarCount >::~GraphAssemblerLabel().
representations_
template<size_t VarCount>
const Array<MachineRepresentation> v8::internal::compiler::GraphAssemblerLabel< VarCount >::representations_ [private]
Definition at line 241 of file graph-assembler.h.
Referenced by v8::internal::compiler::GraphAssemblerLabel< VarCount >::Count().
type_
template<size_t VarCount>
const GraphAssemblerLabelType v8::internal::compiler::GraphAssemblerLabel< VarCount >::type_ [private]
Definition at line 235 of file graph-assembler.h.
Referenced by v8::internal::compiler::GraphAssemblerLabel< VarCount >::IsDeferred(), and v8::internal::compiler::GraphAssemblerLabel< VarCount >::IsLoop().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/graph-assembler.h