v8::internal::ConsumedPreparseData Class Reference
#include <preparse-data.h>
Public Member Functions
virtual ~ConsumedPreparseData ()=default
ConsumedPreparseData (const ConsumedPreparseData &)=delete
ConsumedPreparseData & operator= (const ConsumedPreparseData &)=delete
virtual ProducedPreparseData * GetDataForSkippableFunction (Zone *zone, int start_position, int *end_position, int *num_parameters, int *function_length, int *num_inner_functions, bool *uses_super_property, LanguageMode *language_mode)=0
virtual void RestoreScopeAllocationData (DeclarationScope *scope, AstValueFactory *ast_value_factory, Zone *zone)=0
Static Public Member Functions
static V8_EXPORT_PRIVATE std::unique_ptr< ConsumedPreparseData > For (Isolate *isolate, Handle< PreparseData > data)
static V8_EXPORT_PRIVATE std::unique_ptr< ConsumedPreparseData > For (LocalIsolate *isolate, Handle< PreparseData > data)
static std::unique_ptr< ConsumedPreparseData > For (Zone *zone, ZonePreparseData *data)
Protected Member Functions
ConsumedPreparseData ()=default
Detailed Description
Definition at line 278 of file preparse-data.h.
Constructor & Destructor Documentation
 ConsumedPreparseData()
virtual v8::internal::ConsumedPreparseData::~ConsumedPreparseData () [virtual], [default]
ConsumedPreparseData() [1/2]
v8::internal::ConsumedPreparseData::ConsumedPreparseData (const ConsumedPreparseData &) [delete]
ConsumedPreparseData() [2/2]
v8::internal::ConsumedPreparseData::ConsumedPreparseData () [protected], [default]
Member Function Documentation
For() [1/3]
std::unique_ptr< ConsumedPreparseData > v8::internal::ConsumedPreparseData::For (Isolate * isolate, Handle< PreparseData > data) [static]
Definition at line 842 of file preparse-data.cc.
                                                 {
  return ConsumedPreparseData::For(isolate->main_thread_local_isolate(), data);
}
References v8::internal::Isolate::main_thread_local_isolate().
Referenced by v8::internal::Compiler::Compile(), and v8::internal::BackgroundCompileTask::Run().
For() [2/3]
std::unique_ptr< ConsumedPreparseData > v8::internal::ConsumedPreparseData::For (LocalIsolate * isolate, Handle< PreparseData > data) [static]
Definition at line 847 of file preparse-data.cc.
                                                      {
  DCHECK(!data.is_null());
  return std::make_unique<OnHeapConsumedPreparseData>(isolate, data);
}
References v8::internal::DCHECK(), and v8::internal::HandleBase::is_null().
For() [3/3]
std::unique_ptr< ConsumedPreparseData > v8::internal::ConsumedPreparseData::For (Zone * zone, ZonePreparseData * data) [static]
Definition at line 853 of file preparse-data.cc.
                                        {
  if (data == nullptr) return {};
  return std::make_unique<ZoneConsumedPreparseData>(zone, data);
}
GetDataForSkippableFunction()
virtual ProducedPreparseData* v8::internal::ConsumedPreparseData::GetDataForSkippableFunction (Zone * zone, int start_position, int * end_position, int * num_parameters, int * function_length, int * num_inner_functions, bool * uses_super_property, LanguageMode * language_mode) [pure virtual]
Implemented in v8::internal::BaseConsumedPreparseData< Data >, v8::internal::BaseConsumedPreparseData< Tagged< PreparseData > >, and v8::internal::BaseConsumedPreparseData< ZoneVectorWrapper >.
Referenced by v8::internal::Parser::SkipFunction().
operator=()
ConsumedPreparseData& v8::internal::ConsumedPreparseData::operator= (const ConsumedPreparseData &) [delete]
RestoreScopeAllocationData()
virtual void v8::internal::ConsumedPreparseData::RestoreScopeAllocationData (DeclarationScope * scope, AstValueFactory * ast_value_factory, Zone * zone) [pure virtual]
Implemented in v8::internal::BaseConsumedPreparseData< Data >, v8::internal::BaseConsumedPreparseData< Tagged< PreparseData > >, and v8::internal::BaseConsumedPreparseData< ZoneVectorWrapper >.
Referenced by v8::internal::DeclarationScope::Analyze().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/parsing/preparse-data.h
/mnt/V8SourceCode/src/parsing/preparse-data.cc