v8::internal::anonymous_namespace{elements.cc}::FastFrozenObjectElementsAccessor< Subclass, KindTraits > Class Template Reference
Public Types
using BackingStore = typename KindTraits::BackingStore
Static Public Member Functions
static void SetImpl (DirectHandle< JSObject > holder, InternalIndex entry, Tagged< Object > value)
static void SetImpl (Tagged< FixedArrayBase > backing_store, InternalIndex entry, Tagged< Object > value)
static void SetImpl (Tagged< FixedArrayBase > backing_store, InternalIndex entry, Tagged< Object > value, WriteBarrierMode mode)
static Tagged< Object > RemoveElement (Isolate *isolate, DirectHandle< JSArray > receiver, Where remove_position)
static void DeleteImpl (Isolate *isolate, DirectHandle< JSObject > obj, InternalIndex entry)
static void DeleteAtEnd (Isolate *isolate, DirectHandle< JSObject > obj, DirectHandle< BackingStore > backing_store, uint32_t entry)
static void DeleteCommon (Isolate *isolate, DirectHandle< JSObject > obj, uint32_t entry, DirectHandle< FixedArrayBase > store)
static Tagged< Object > PopImpl (Isolate *isolate, DirectHandle< JSArray > receiver)
static Maybe< uint32_t > PushImpl (Isolate *isolate, DirectHandle< JSArray > receiver, BuiltinArguments *args, uint32_t push_size)
static Maybe< bool > AddImpl (Isolate *isolate, DirectHandle< JSObject > object, uint32_t index, DirectHandle< Object > value, PropertyAttributes attributes, uint32_t new_capacity)
static Maybe< bool > SetLengthImpl (Isolate *isolate, DirectHandle< JSArray > array, uint32_t length, DirectHandle< FixedArrayBase > backing_store)
static void ReconfigureImpl (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > store, InternalIndex entry, DirectHandle< Object > value, PropertyAttributes attributes)
Additional Inherited Members
Detailed Description
template<typename Subclass, typename KindTraits>
class v8::internal::anonymous_namespace{elements.cc}::FastFrozenObjectElementsAccessor< Subclass, KindTraits >
Definition at line 3101 of file elements.cc.
Member Typedef Documentation
BackingStore
template<typename Subclass , typename KindTraits >
using v8::internal::anonymous_namespace{elements.cc}::FastFrozenObjectElementsAccessor< Subclass, KindTraits >::BackingStore = typename KindTraits::BackingStore
Definition at line 3104 of file elements.cc.
Member Function Documentation
AddImpl()
template<typename Subclass , typename KindTraits >
static Maybe<bool> v8::internal::anonymous_namespace{elements.cc}::FastFrozenObjectElementsAccessor< Subclass, KindTraits >::AddImpl (Isolate * isolate, DirectHandle< JSObject > object, uint32_t index, DirectHandle< Object > value, PropertyAttributes attributes, uint32_t new_capacity) [inline], [static]
Definition at line 3155 of file elements.cc.
                                                    {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
DeleteAtEnd()
template<typename Subclass , typename KindTraits >
static void v8::internal::anonymous_namespace{elements.cc}::FastFrozenObjectElementsAccessor< Subclass, KindTraits >::DeleteAtEnd (Isolate * isolate, DirectHandle< JSObject > obj, DirectHandle< BackingStore > backing_store, uint32_t entry) [inline], [static]
Definition at line 3133 of file elements.cc.
                                          {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
DeleteCommon()
template<typename Subclass , typename KindTraits >
static void v8::internal::anonymous_namespace{elements.cc}::FastFrozenObjectElementsAccessor< Subclass, KindTraits >::DeleteCommon (Isolate * isolate, DirectHandle< JSObject > obj, uint32_t entry, DirectHandle< FixedArrayBase > store) [inline], [static]
Definition at line 3139 of file elements.cc.
                                                                               {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
DeleteImpl()
template<typename Subclass , typename KindTraits >
static void v8::internal::anonymous_namespace{elements.cc}::FastFrozenObjectElementsAccessor< Subclass, KindTraits >::DeleteImpl (Isolate * isolate, DirectHandle< JSObject > obj, InternalIndex entry) [inline], [static]
Definition at line 3128 of file elements.cc.
                                              {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
PopImpl()
template<typename Subclass , typename KindTraits >
static Tagged<Object> v8::internal::anonymous_namespace{elements.cc}::FastFrozenObjectElementsAccessor< Subclass, KindTraits >::PopImpl (Isolate * isolate, DirectHandle< JSArray > receiver) [inline], [static]
Definition at line 3144 of file elements.cc.
                                                                {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
PushImpl()
template<typename Subclass , typename KindTraits >
static Maybe<uint32_t> v8::internal::anonymous_namespace{elements.cc}::FastFrozenObjectElementsAccessor< Subclass, KindTraits >::PushImpl (Isolate * isolate, DirectHandle< JSArray > receiver, BuiltinArguments * args, uint32_t push_size) [inline], [static]
Definition at line 3149 of file elements.cc.
                                                                              {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
ReconfigureImpl()
template<typename Subclass , typename KindTraits >
static void v8::internal::anonymous_namespace{elements.cc}::FastFrozenObjectElementsAccessor< Subclass, KindTraits >::ReconfigureImpl (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > store, InternalIndex entry, DirectHandle< Object > value, PropertyAttributes attributes) [inline], [static]
Definition at line 3168 of file elements.cc.
                                                             {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
RemoveElement()
template<typename Subclass , typename KindTraits >
static Tagged<Object> v8::internal::anonymous_namespace{elements.cc}::FastFrozenObjectElementsAccessor< Subclass, KindTraits >::RemoveElement (Isolate * isolate, DirectHandle< JSArray > receiver, Where remove_position) [inline], [static]
Definition at line 3122 of file elements.cc.
                                                             {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
SetImpl() [1/3]
template<typename Subclass , typename KindTraits >
static void v8::internal::anonymous_namespace{elements.cc}::FastFrozenObjectElementsAccessor< Subclass, KindTraits >::SetImpl (DirectHandle< JSObject > holder, InternalIndex entry, Tagged< Object > value) [inline], [static]
Definition at line 3106 of file elements.cc.
                                                   {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
SetImpl() [2/3]
template<typename Subclass , typename KindTraits >
static void v8::internal::anonymous_namespace{elements.cc}::FastFrozenObjectElementsAccessor< Subclass, KindTraits >::SetImpl (Tagged< FixedArrayBase > backing_store, InternalIndex entry, Tagged< Object > value) [inline], [static]
Definition at line 3111 of file elements.cc.
                                                                        {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
SetImpl() [3/3]
template<typename Subclass , typename KindTraits >
static void v8::internal::anonymous_namespace{elements.cc}::FastFrozenObjectElementsAccessor< Subclass, KindTraits >::SetImpl (Tagged< FixedArrayBase > backing_store, InternalIndex entry, Tagged< Object > value, WriteBarrierMode mode) [inline], [static]
Definition at line 3116 of file elements.cc.
                                                    {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
SetLengthImpl()
template<typename Subclass , typename KindTraits >
static Maybe<bool> v8::internal::anonymous_namespace{elements.cc}::FastFrozenObjectElementsAccessor< Subclass, KindTraits >::SetLengthImpl (Isolate * isolate, DirectHandle< JSArray > array, uint32_t length, DirectHandle< FixedArrayBase > backing_store) [inline], [static]
Definition at line 3162 of file elements.cc.
                                                                               {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/elements.cc