cppgc::internal::SameThreadEnabledCheckingPolicy< kCheckOffHeapAssignments > Class Template Reference
#include <pointer-policies.h>
Classes
struct CheckPointersImplTrampoline
struct CheckPointersImplTrampoline< T, true >
Protected Member Functions
template<typename T >
void CheckPointer (RawPointer raw_pointer)
template<typename T >
void CheckPointer (const T *ptr)
Additional Inherited Members
Detailed Description
template<bool kCheckOffHeapAssignments>
class cppgc::internal::SameThreadEnabledCheckingPolicy< kCheckOffHeapAssignments >
Definition at line 130 of file pointer-policies.h.
Member Function Documentation
CheckPointer() [1/2]
template<bool kCheckOffHeapAssignments>
template<typename T >
void cppgc::internal::SameThreadEnabledCheckingPolicy< kCheckOffHeapAssignments >::CheckPointer (const T * ptr) [inline], [protected]
Definition at line 152 of file pointer-policies.h.
                                  {
    if (!ptr || (kSentinelPointer == ptr)) {
      return;
    }
    CheckPointersImplTrampoline<T>::Call(this, ptr);
  }
References cppgc::kSentinelPointer.
CheckPointer() [2/2]
template<bool kCheckOffHeapAssignments>
template<typename T >
void cppgc::internal::SameThreadEnabledCheckingPolicy< kCheckOffHeapAssignments >::CheckPointer (RawPointer raw_pointer) [inline], [protected]
Definition at line 134 of file pointer-policies.h.
                                                      {
    if (raw_pointer.IsCleared() || raw_pointer.IsSentinel()) {
      return;
    }
    CheckPointersImplTrampoline<T>::Call(
        this, static_cast<const T*>(raw_pointer.Load()));
  }
References cppgc::internal::RawPointer::IsCleared(), cppgc::internal::RawPointer::IsSentinel(), and cppgc::internal::RawPointer::Load().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/cppgc/internal/pointer-policies.h