v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl Class Reference
Classes
struct PublishState
Public Types
enum CancellationPolicy { kCancelUnconditionally
, kCancelInitialCompilation
 }
Public Member Functions
CompilationStateImpl (const std::shared_ptr< NativeModule > &native_module, std::shared_ptr< Counters > async_counters, WasmDetectedFeatures detected_features)
~CompilationStateImpl ()
void InitCompileJob ()
void CancelCompilation (CancellationPolicy)
bool cancelled () const
void ApplyCompilationHintToInitialProgress (const WasmCompilationHint &hint, size_t hint_idx)
void ApplyPgoInfoToInitialProgress (ProfileInformation *pgo_info)
void ApplyPgoInfoLate (ProfileInformation *pgo_info)
void InitializeCompilationProgress (ProfileInformation *pgo_info)
void InitializeCompilationProgressAfterDeserialization (base::Vector< const int > lazy_functions, base::Vector< const int > eager_functions)
void InitializeCompilationUnits (std::unique_ptr< CompilationUnitBuilder > builder)
void InitializeCompilationUnitForSingleFunction (CompilationUnitBuilder *builder, int func_index)
void AddCallback (std::unique_ptr< CompilationEventCallback > callback)
void CommitCompilationUnits (base::Vector< WasmCompilationUnit > baseline_units, base::Vector< WasmCompilationUnit > top_tier_units)
void CommitTopTierCompilationUnit (WasmCompilationUnit)
void AddTopTierPriorityCompilationUnit (WasmCompilationUnit, size_t)
CompilationUnitQueues::Queue * GetQueueForCompileTask (int task_id)
std::optional< WasmCompilationUnit > GetNextCompilationUnit (CompilationUnitQueues::Queue *, CompilationTier tier)
void OnFinishedUnits (base::Vector< WasmCode * >)
void OnCompilationStopped (WasmDetectedFeatures detected)
void SchedulePublishCompilationResults (std::vector< UnpublishedWasmCode > unpublished_code, CompilationTier tier)
WasmDetectedFeatures detected_features () const
V8_WARN_UNUSED_RESULT WasmDetectedFeatures UpdateDetectedFeatures (WasmDetectedFeatures)
size_t NumOutstandingCompilations (CompilationTier tier) const
void SetError ()
void WaitForCompilationEvent (CompilationEvent event)
void TierUpAllFunctions ()
void AllowAnotherTopTierJob (uint32_t func_index)
void AllowAnotherTopTierJobForAllFunctions ()
bool failed () const
bool baseline_compilation_finished () const
Counters * counters () const
void SetWireBytesStorage (std::shared_ptr< WireBytesStorage > wire_bytes_storage)
std::shared_ptr< WireBytesStorage > GetWireBytesStorage () const
void set_compilation_id (int compilation_id)
size_t EstimateCurrentMemoryConsumption () const
void TriggerCachingAfterTimeout ()
std::vector< WasmCode * > PublishCode (base::Vector< UnpublishedWasmCode > codes)
Private Types
using RequiredBaselineTierField = base::BitField8< ExecutionTier, 0, 2 >
using RequiredTopTierField = base::BitField8< ExecutionTier, 2, 2 >
using ReachedTierField = base::BitField8< ExecutionTier, 4, 2 >
Private Member Functions
void TriggerOutstandingCallbacks ()
void TriggerCallbacks (base::EnumSet< CompilationEvent >)
void PublishCompilationResults (std::vector< UnpublishedWasmCode > unpublished_code)
Private Attributes
NativeModule *const native_module_
std::weak_ptr< NativeModule > const native_module_weak_
const std::shared_ptr< Counters > async_counters_
std::atomic< bool > compile_failed_ {false}
std::atomic< bool > compile_cancelled_ {false}
CompilationUnitQueues compilation_unit_queues_
base::Mutex mutex_
std::unique_ptr< JobHandle > baseline_compile_job_
std::unique_ptr< JobHandle > top_tier_compile_job_
int compilation_id_ = kInvalidCompilationID
std::atomic< WasmDetectedFeatures > detected_features_
std::shared_ptr< WireBytesStorage > wire_bytes_storage_
base::Mutex callbacks_mutex_
std::vector< std::unique_ptr< CompilationEventCallback > > callbacks_
base::EnumSet< CompilationEvent > finished_events_
int outstanding_baseline_units_ = 0
size_t bytes_since_last_chunk_ = 0
base::OwnedVector< uint8_t > compilation_progress_
base::TimeTicks last_top_tier_compilation_timestamp_
PublishState publish_state_ [CompilationTier::kNumTiers]
Static Private Attributes
static constexpr int kInvalidCompilationID = -1
Detailed Description
Definition at line 568 of file module-compiler.cc.
Member Typedef Documentation
ReachedTierField
using v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::ReachedTierField = base::BitField8<ExecutionTier, 4, 2> [private]
Definition at line 831 of file module-compiler.cc.
RequiredBaselineTierField
using v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::RequiredBaselineTierField = base::BitField8<ExecutionTier, 0, 2> [private]
Definition at line 829 of file module-compiler.cc.
RequiredTopTierField
using v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::RequiredTopTierField = base::BitField8<ExecutionTier, 2, 2> [private]
Definition at line 830 of file module-compiler.cc.
Member Enumeration Documentation
CancellationPolicy
enum v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::CancellationPolicy
Enumerator
kCancelUnconditionally
kCancelInitialCompilation
Definition at line 589 of file module-compiler.cc.
{ kCancelUnconditionally, kCancelInitialCompilation };
Constructor & Destructor Documentation
CompilationStateImpl()
v8::internal::wasm::CompilationStateImpl::CompilationStateImpl (const std::shared_ptr< NativeModule > & native_module, std::shared_ptr< Counters > async_counters, WasmDetectedFeatures detected_features)
Definition at line 3564 of file module-compiler.cc.
    : native_module_(native_module.get()),
      native_module_weak_(std::move(native_module)),
      async_counters_(std::move(async_counters)),
      compilation_unit_queues_(native_module->num_imported_functions(),
                               native_module->num_declared_functions()),
      detected_features_(detected_features) {}
 CompilationStateImpl()
v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::~CompilationStateImpl () [inline]
Definition at line 573 of file module-compiler.cc.
                          {
    if (baseline_compile_job_->IsValid()) {
      baseline_compile_job_->CancelAndDetach();
    }
    if (top_tier_compile_job_->IsValid()) {
      top_tier_compile_job_->CancelAndDetach();
    }
  }
Referenced by v8::internal::wasm::CompilationState::~CompilationState().
Member Function Documentation
AddCallback()
void v8::internal::wasm::CompilationStateImpl::AddCallback (std::unique_ptr< CompilationEventCallback > callback)
Definition at line 3937 of file module-compiler.cc.
                                                      {
  base::MutexGuard callbacks_guard(&callbacks_mutex_);
  // Immediately trigger events that already happened.
  for (auto event : {CompilationEvent::kFinishedBaselineCompilation,
                     CompilationEvent::kFailedCompilation}) {
    if (finished_events_.contains(event)) {
      callback->call(event);
    }
  }
  constexpr base::EnumSet<CompilationEvent> kFinalEvents{
      CompilationEvent::kFailedCompilation};
  if (!finished_events_.contains_any(kFinalEvents)) {
    callbacks_.emplace_back(std::move(callback));
  }
}
References callbacks_, callbacks_mutex_, v8::base::EnumSet< E, T >::contains(), v8::base::EnumSet< E, T >::contains_any(), finished_events_, v8::internal::wasm::kFailedCompilation, and v8::internal::wasm::kFinishedBaselineCompilation.
Referenced by v8::internal::wasm::CompilationState::AddCallback().
AddTopTierPriorityCompilationUnit()
void v8::internal::wasm::CompilationStateImpl::AddTopTierPriorityCompilationUnit (WasmCompilationUnit unit, size_t priority)
Definition at line 3977 of file module-compiler.cc.
                                               {
  compilation_unit_queues_.AddTopTierPriorityUnit(unit, priority);
  // We should not have a {CodeSpaceWriteScope} open at this point, as
  // {NotifyConcurrencyIncrease} can spawn new threads which could inherit PKU
  // permissions (which would be a security issue).
  top_tier_compile_job_->NotifyConcurrencyIncrease();
}
References v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::AddTopTierPriorityUnit(), compilation_unit_queues_, and top_tier_compile_job_.
AllowAnotherTopTierJob()
void v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::AllowAnotherTopTierJob (uint32_t func_index) [inline]
Definition at line 666 of file module-compiler.cc.
                                                   {
    compilation_unit_queues_.AllowAnotherTopTierJob(func_index);
    // Reset the stored priority; otherwise triggers might be ignored if the
    // priority is not bumped to the next power of two.
    TypeFeedbackStorage* feedback = &native_module_->module()->type_feedback;
    base::MutexGuard mutex_guard(&feedback->mutex);
    feedback->feedback_for_function[func_index].tierup_priority = 0;
  }
References v8::internal::wasm::TypeFeedbackStorage::feedback_for_function, and v8::internal::wasm::TypeFeedbackStorage::mutex.
Referenced by v8::internal::wasm::CompilationState::AllowAnotherTopTierJob().
AllowAnotherTopTierJobForAllFunctions()
void v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::AllowAnotherTopTierJobForAllFunctions () [inline]
Definition at line 675 of file module-compiler.cc.
                                               {
    const WasmModule* module = native_module_->module();
    uint32_t fn_start = module->num_imported_functions;
    uint32_t fn_end = fn_start + module->num_declared_functions;
    base::MutexGuard mutex_guard(&module->type_feedback.mutex);
    std::unordered_map<uint32_t, FunctionTypeFeedback>& feedback_map =
        module->type_feedback.feedback_for_function;
    for (uint32_t i = fn_start; i < fn_end; i++) {
      compilation_unit_queues_.AllowAnotherTopTierJob(i);
      // Reset the stored priority; otherwise triggers might be ignored if the
      // priority is not bumped to the next power of two.
      if (auto it = feedback_map.find(i); it != feedback_map.end()) {
        it->second.tierup_priority = 0;
      }
    }
  }
References v8::internal::wasm::TypeFeedbackStorage::feedback_for_function, v8::internal::wasm::TypeFeedbackStorage::mutex, v8::internal::wasm::WasmModule::num_declared_functions, v8::internal::wasm::WasmModule::num_imported_functions, and v8::internal::wasm::WasmModule::type_feedback.
Referenced by v8::internal::wasm::CompilationState::AllowAnotherTopTierJobForAllFunctions().
ApplyCompilationHintToInitialProgress()
void v8::internal::wasm::CompilationStateImpl::ApplyCompilationHintToInitialProgress (const WasmCompilationHint & hint, size_t hint_idx)
Definition at line 3613 of file module-compiler.cc.
                                                      {
  // Get old information.
  uint8_t& progress = compilation_progress_[hint_idx];
  ExecutionTier old_baseline_tier = RequiredBaselineTierField::decode(progress);
  ExecutionTier old_top_tier = RequiredTopTierField::decode(progress);
  // Compute new information.
  ExecutionTier new_baseline_tier =
      ApplyHintToExecutionTier(hint.baseline_tier, old_baseline_tier);
  ExecutionTier new_top_tier =
      ApplyHintToExecutionTier(hint.top_tier, old_top_tier);
  switch (hint.strategy) {
    case WasmCompilationHintStrategy::kDefault:
      // Be careful not to switch from lazy to non-lazy.
      if (old_baseline_tier == ExecutionTier::kNone) {
        new_baseline_tier = ExecutionTier::kNone;
      }
      if (old_top_tier == ExecutionTier::kNone) {
        new_top_tier = ExecutionTier::kNone;
      }
      break;
    case WasmCompilationHintStrategy::kLazy:
      new_baseline_tier = ExecutionTier::kNone;
      new_top_tier = ExecutionTier::kNone;
      break;
    case WasmCompilationHintStrategy::kEager:
      // Nothing to do, use the encoded (new) tiers.
      break;
    case WasmCompilationHintStrategy::kLazyBaselineEagerTopTier:
      new_baseline_tier = ExecutionTier::kNone;
      break;
  }
  if (new_top_tier == ExecutionTier::kLiftoff &&
      new_baseline_tier == ExecutionTier::kTurbofan) {
    // The top tier shouldn't be lower than the baseline tier (or it should be
    // ::None).
    new_top_tier = ExecutionTier::kTurbofan;
  }
  progress = RequiredBaselineTierField::update(progress, new_baseline_tier);
  progress = RequiredTopTierField::update(progress, new_top_tier);
  // Update counter for outstanding baseline units.
  outstanding_baseline_units_ += (new_baseline_tier != ExecutionTier::kNone) -
                                 (old_baseline_tier != ExecutionTier::kNone);
}
References v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ApplyHintToExecutionTier(), v8::internal::wasm::WasmCompilationHint::baseline_tier, compilation_progress_, v8::base::BitField< T, shift, size, U >::decode(), v8::internal::wasm::kDefault, v8::internal::wasm::kEager, v8::internal::wasm::kLazy, v8::internal::wasm::kLazyBaselineEagerTopTier, v8::internal::wasm::kLiftoff, v8::internal::wasm::kNone, v8::internal::wasm::kTurbofan, outstanding_baseline_units_, v8::internal::wasm::WasmCompilationHint::strategy, v8::internal::wasm::WasmCompilationHint::top_tier, and v8::base::BitField< T, shift, size, U >::update().
Referenced by InitializeCompilationProgress().
ApplyPgoInfoLate()
void v8::internal::wasm::CompilationStateImpl::ApplyPgoInfoLate (ProfileInformation * pgo_info)
Definition at line 3702 of file module-compiler.cc.
                                                                        {
  TRACE_EVENT0("v8.wasm", "wasm.ApplyPgoInfo");
  const WasmModule* module = native_module_->module();
  CompilationUnitBuilder builder{native_module_};
  base::MutexGuard guard(&callbacks_mutex_);
  // Functions that were executed in the profiling run are eagerly compiled to
  // Liftoff (in the background).
  for (int func_index : pgo_info->executed_functions()) {
    uint8_t& progress =
        compilation_progress_[declared_function_index(module, func_index)];
    ExecutionTier old_baseline_tier =
        RequiredBaselineTierField::decode(progress);
    // If the function is already marked for eager compilation, we are good.
    if (old_baseline_tier != ExecutionTier::kNone) continue;
    // If we already compiled Liftoff or TurboFan code, we are also good.
    ExecutionTier reached_tier = ReachedTierField::decode(progress);
    if (reached_tier >= ExecutionTier::kLiftoff) continue;
    // Set the baseline tier to Liftoff and schedule a compilation unit.
    progress =
        RequiredBaselineTierField::update(progress, ExecutionTier::kLiftoff);
    // Add this as a "top tier unit" since it does not contribute to initial
    // compilation ("baseline finished" might already be triggered).
    // TODO(clemensb): Rename "baseline finished" to "initial compile finished".
    // TODO(clemensb): Avoid scheduling both a Liftoff and a TurboFan unit, or
    // prioritize Liftoff when executing the units.
    builder.AddTopTierUnit(func_index, ExecutionTier::kLiftoff);
  }
  // Functions that were tiered up during PGO generation are eagerly compiled to
  // TurboFan in the background.
  for (int func_index : pgo_info->tiered_up_functions()) {
    uint8_t& progress =
        compilation_progress_[declared_function_index(module, func_index)];
    ExecutionTier old_baseline_tier =
        RequiredBaselineTierField::decode(progress);
    ExecutionTier old_top_tier = RequiredTopTierField::decode(progress);
    // If the function is already marked for eager or background compilation to
    // TurboFan, we are good.
    if (old_baseline_tier == ExecutionTier::kTurbofan) continue;
    if (old_top_tier == ExecutionTier::kTurbofan) continue;
    // If we already compiled TurboFan code, we are also good.
    ExecutionTier reached_tier = ReachedTierField::decode(progress);
    if (reached_tier == ExecutionTier::kTurbofan) continue;
    // Set top tier to TurboFan and schedule a compilation unit.
    progress = RequiredTopTierField::update(progress, ExecutionTier::kTurbofan);
    builder.AddTopTierUnit(func_index, ExecutionTier::kTurbofan);
  }
  builder.Commit();
}
References callbacks_mutex_, compilation_progress_, v8::internal::wasm::declared_function_index(), v8::base::BitField< T, shift, size, U >::decode(), v8::internal::wasm::ProfileInformation::executed_functions(), v8::internal::wasm::kLiftoff, v8::internal::wasm::kNone, v8::internal::wasm::kTurbofan, v8::internal::wasm::NativeModule::module(), native_module_, v8::internal::wasm::ProfileInformation::tiered_up_functions(), TRACE_EVENT0, and v8::base::BitField< T, shift, size, U >::update().
ApplyPgoInfoToInitialProgress()
void v8::internal::wasm::CompilationStateImpl::ApplyPgoInfoToInitialProgress (ProfileInformation * pgo_info)
Definition at line 3662 of file module-compiler.cc.
                                  {
  // Functions that were executed in the profiling run are eagerly compiled to
  // Liftoff.
  const WasmModule* module = native_module_->module();
  for (int func_index : pgo_info->executed_functions()) {
    uint8_t& progress =
        compilation_progress_[declared_function_index(module, func_index)];
    ExecutionTier old_baseline_tier =
        RequiredBaselineTierField::decode(progress);
    // If the function is already marked for eager compilation, we are good.
    if (old_baseline_tier != ExecutionTier::kNone) continue;
    // Set the baseline tier to Liftoff, so we eagerly compile to Liftoff.
    // TODO(13288): Compile Liftoff code in the background, if lazy compilation
    // is enabled.
    progress =
        RequiredBaselineTierField::update(progress, ExecutionTier::kLiftoff);
    ++outstanding_baseline_units_;
  }
  // Functions that were tiered up during PGO generation are eagerly compiled to
  // TurboFan (in the background, not blocking instantiation).
  for (int func_index : pgo_info->tiered_up_functions()) {
    uint8_t& progress =
        compilation_progress_[declared_function_index(module, func_index)];
    ExecutionTier old_baseline_tier =
        RequiredBaselineTierField::decode(progress);
    ExecutionTier old_top_tier = RequiredTopTierField::decode(progress);
    // If the function is already marked for eager or background compilation to
    // TurboFan, we are good.
    if (old_baseline_tier == ExecutionTier::kTurbofan) continue;
    if (old_top_tier == ExecutionTier::kTurbofan) continue;
    // Set top tier to TurboFan, so we eagerly trigger compilation in the
    // background.
    progress = RequiredTopTierField::update(progress, ExecutionTier::kTurbofan);
  }
}
References compilation_progress_, v8::internal::wasm::declared_function_index(), v8::base::BitField< T, shift, size, U >::decode(), v8::internal::wasm::ProfileInformation::executed_functions(), v8::internal::wasm::kLiftoff, v8::internal::wasm::kNone, v8::internal::wasm::kTurbofan, v8::internal::wasm::NativeModule::module(), native_module_, outstanding_baseline_units_, v8::internal::wasm::ProfileInformation::tiered_up_functions(), and v8::base::BitField< T, shift, size, U >::update().
Referenced by InitializeCompilationProgress().
baseline_compilation_finished()
bool v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::baseline_compilation_finished () const [inline]
Definition at line 696 of file module-compiler.cc.
                                             {
    base::MutexGuard guard(&callbacks_mutex_);
    return outstanding_baseline_units_ == 0;
  }
Referenced by v8::internal::wasm::CompilationState::baseline_compilation_finished().
CancelCompilation()
void v8::internal::wasm::CompilationStateImpl::CancelCompilation (CompilationStateImpl::CancellationPolicy cancellation_policy)
Definition at line 3590 of file module-compiler.cc.
                                                                {
  base::MutexGuard callbacks_guard(&callbacks_mutex_);
  if (cancellation_policy == kCancelInitialCompilation &&
      finished_events_.contains(
          CompilationEvent::kFinishedBaselineCompilation)) {
    // Initial compilation already finished; cannot be cancelled.
    return;
  }
  // std::memory_order_relaxed is sufficient because no other state is
  // synchronized with |compile_cancelled_|.
  compile_cancelled_.store(true, std::memory_order_relaxed);
  // No more callbacks after abort.
  callbacks_.clear();
}
References callbacks_, callbacks_mutex_, compile_cancelled_, v8::base::EnumSet< E, T >::contains(), finished_events_, kCancelInitialCompilation, and v8::internal::wasm::kFinishedBaselineCompilation.
Referenced by v8::internal::wasm::CompilationState::CancelCompilation(), v8::internal::wasm::CompilationState::CancelInitialCompilation(), and v8::internal::wasm::AsyncCompileJob::~AsyncCompileJob().
cancelled()
bool v8::internal::wasm::CompilationStateImpl::cancelled () const
Definition at line 3609 of file module-compiler.cc.
                                           {
  return compile_cancelled_.load(std::memory_order_relaxed);
}
References compile_cancelled_.
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::BackgroundCompileScope::cancelled().
CommitCompilationUnits()
void v8::internal::wasm::CompilationStateImpl::CommitCompilationUnits (base::Vector< WasmCompilationUnit > baseline_units, base::Vector< WasmCompilationUnit > top_tier_units)
Definition at line 3954 of file module-compiler.cc.
                                                    {
  base::MutexGuard guard{&mutex_};
  if (!baseline_units.empty() || !top_tier_units.empty()) {
    compilation_unit_queues_.AddUnits(baseline_units, top_tier_units,
                                      native_module_->module());
  }
  if (!baseline_units.empty()) {
    DCHECK(baseline_compile_job_->IsValid());
    baseline_compile_job_->NotifyConcurrencyIncrease();
  }
  if (!top_tier_units.empty()) {
    DCHECK(top_tier_compile_job_->IsValid());
    top_tier_compile_job_->NotifyConcurrencyIncrease();
  }
}
References v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::AddUnits(), baseline_compile_job_, compilation_unit_queues_, v8::internal::DCHECK(), v8::base::Vector< T >::empty(), v8::internal::wasm::NativeModule::module(), mutex_, native_module_, and top_tier_compile_job_.
Referenced by CommitTopTierCompilationUnit().
CommitTopTierCompilationUnit()
void v8::internal::wasm::CompilationStateImpl::CommitTopTierCompilationUnit (WasmCompilationUnit unit)
Definition at line 3972 of file module-compiler.cc.
                              {
  CommitCompilationUnits({}, {&unit, 1});
}
References CommitCompilationUnits().
counters()
Counters* v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::counters () const [inline]
Definition at line 701 of file module-compiler.cc.
{ return async_counters_.get(); }
Referenced by InitializeCompilationProgressAfterDeserialization().
detected_features()
WasmDetectedFeatures v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::detected_features () const [inline]
Definition at line 649 of file module-compiler.cc.
                                                 {
    return detected_features_.load(std::memory_order_relaxed);
  }
Referenced by v8::internal::wasm::CompilationState::detected_features(), and OnCompilationStopped().
EstimateCurrentMemoryConsumption()
size_t v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::EstimateCurrentMemoryConsumption () const
Definition at line 846 of file module-compiler.cc.
                                                                    {
  UPDATE_WHEN_CLASS_CHANGES(CompilationStateImpl, 456);
  size_t result = sizeof(CompilationStateImpl);
  {
    base::MutexGuard guard{&mutex_};
    result += compilation_unit_queues_.EstimateCurrentMemoryConsumption();
  }
  // To read the size of {callbacks_} and {compilation_progress_}, we'd
  // need to acquire the {callbacks_mutex_}, which can cause deadlocks
  // when that mutex is already held elsewhere and another thread calls
  // into this function. So we rely on heuristics and informed guesses
  // instead: {compilation_progress_} contains an entry for every declared
  // function in the module...
  result += sizeof(uint8_t) * native_module_->module()->num_declared_functions;
  // ...and there are typically no more than a handful of {callbacks_}.
  constexpr size_t kAssumedNumberOfCallbacks = 4;
  constexpr size_t size_of_vector =
      kAssumedNumberOfCallbacks *
      sizeof(std::unique_ptr<CompilationEventCallback>);
  // Concrete subclasses of CompilationEventCallback will be bigger, but we
  // can't know that here.
  constexpr size_t size_of_payload =
      kAssumedNumberOfCallbacks * sizeof(CompilationEventCallback);
  result += size_of_vector + size_of_payload;
  if (v8_flags.trace_wasm_offheap_memory) {
    PrintF("CompilationStateImpl: %zu\n", result);
  }
  return result;
}
References v8::internal::PrintF(), v8::base::internal::result, UPDATE_WHEN_CLASS_CHANGES, and v8::internal::v8_flags.
Referenced by v8::internal::wasm::CompilationState::EstimateCurrentMemoryConsumption().
failed()
bool v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::failed () const [inline]
Definition at line 692 of file module-compiler.cc.
                      {
    return compile_failed_.load(std::memory_order_relaxed);
  }
Referenced by v8::internal::wasm::CompilationState::failed(), and InitializeCompilationProgress().
GetNextCompilationUnit()
std::optional< WasmCompilationUnit > v8::internal::wasm::CompilationStateImpl::GetNextCompilationUnit (CompilationUnitQueues::Queue * queue, CompilationTier tier)
Definition at line 3991 of file module-compiler.cc.
                                                             {
  return compilation_unit_queues_.GetNextUnit(queue, tier);
}
References compilation_unit_queues_, and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::GetNextUnit().
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ExecuteCompilationUnits().
GetQueueForCompileTask()
CompilationUnitQueues::Queue * v8::internal::wasm::CompilationStateImpl::GetQueueForCompileTask (int task_id)
Definition at line 3986 of file module-compiler.cc.
                 {
  return compilation_unit_queues_.GetQueueForTask(task_id);
}
References compilation_unit_queues_, and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::GetQueueForTask().
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ExecuteCompilationUnits().
GetWireBytesStorage()
std::shared_ptr<WireBytesStorage> v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::GetWireBytesStorage () const [inline]
Definition at line 709 of file module-compiler.cc.
                                                              {
    base::MutexGuard guard(&mutex_);
    DCHECK_NOT_NULL(wire_bytes_storage_);
    return wire_bytes_storage_;
  }
References DCHECK_NOT_NULL.
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ExecuteCompilationUnits(), and v8::internal::wasm::CompilationState::GetWireBytesStorage().
InitCompileJob()
void v8::internal::wasm::CompilationStateImpl::InitCompileJob ()
Definition at line 3575 of file module-compiler.cc.
                                          {
  DCHECK_NULL(baseline_compile_job_);
  DCHECK_NULL(top_tier_compile_job_);
  // Create the job, but don't spawn workers yet. This will happen on
  // {NotifyConcurrencyIncrease}.
  baseline_compile_job_ = V8::GetCurrentPlatform()->CreateJob(
      TaskPriority::kUserVisible,
      std::make_unique<BackgroundCompileJob>(
          native_module_weak_, async_counters_, CompilationTier::kBaseline));
  top_tier_compile_job_ = V8::GetCurrentPlatform()->CreateJob(
      TaskPriority::kUserVisible,
      std::make_unique<BackgroundCompileJob>(
          native_module_weak_, async_counters_, CompilationTier::kTopTier));
}
References async_counters_, baseline_compile_job_, v8::Platform::CreateJob(), DCHECK_NULL, v8::internal::V8::GetCurrentPlatform(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::kBaseline, v8::internal::wasm::anonymous_namespace{module-compiler.cc}::kTopTier, v8::kUserVisible, native_module_weak_, and top_tier_compile_job_.
Referenced by v8::internal::wasm::CompilationState::InitCompileJob().
InitializeCompilationProgress()
void v8::internal::wasm::CompilationStateImpl::InitializeCompilationProgress (ProfileInformation * pgo_info)
Definition at line 3757 of file module-compiler.cc.
                                  {
  DCHECK(!failed());
  base::MutexGuard guard(&callbacks_mutex_);
  if (!v8_flags.wasm_jitless) {
    auto* module = native_module_->module();
    DCHECK_EQ(0, outstanding_baseline_units_);
    // Compute the default compilation progress for all functions, and set it.
    const ExecutionTierPair default_tiers = GetDefaultTiersPerModule(
        native_module_, native_module_->IsInDebugState(), IsLazyModule(module));
    const uint8_t default_progress =
        RequiredBaselineTierField::encode(default_tiers.baseline_tier) |
        RequiredTopTierField::encode(default_tiers.top_tier) |
        ReachedTierField::encode(ExecutionTier::kNone);
    DCHECK_NULL(compilation_progress_);
    compilation_progress_ = base::OwnedVector<uint8_t>::New(
        module->num_declared_functions, default_progress);
    if (default_tiers.baseline_tier != ExecutionTier::kNone) {
      outstanding_baseline_units_ += module->num_declared_functions;
    }
    // Apply compilation hints, if enabled.
    if (native_module_->enabled_features().has_compilation_hints()) {
      size_t num_hints = std::min(module->compilation_hints.size(),
                                  size_t{module->num_declared_functions});
      for (size_t hint_idx = 0; hint_idx < num_hints; ++hint_idx) {
        const auto& hint = module->compilation_hints[hint_idx];
        ApplyCompilationHintToInitialProgress(hint, hint_idx);
      }
    }
    // Transform --wasm-eager-tier-up-function, if given, into a fake
    // compilation hint.
    if (V8_UNLIKELY(
            v8_flags.wasm_eager_tier_up_function >= 0 &&
            static_cast<uint32_t>(v8_flags.wasm_eager_tier_up_function) >=
                module->num_imported_functions &&
            static_cast<uint32_t>(v8_flags.wasm_eager_tier_up_function) <
                module->functions.size())) {
      uint32_t func_idx =
          v8_flags.wasm_eager_tier_up_function - module->num_imported_functions;
      WasmCompilationHint hint{WasmCompilationHintStrategy::kEager,
                               WasmCompilationHintTier::kOptimized,
                               WasmCompilationHintTier::kOptimized};
      ApplyCompilationHintToInitialProgress(hint, func_idx);
    }
  }
  // Apply PGO information, if available.
  if (pgo_info) ApplyPgoInfoToInitialProgress(pgo_info);
  // Trigger callbacks if module needs no baseline or top tier compilation. This
  // can be the case for an empty or fully lazy module.
  TriggerOutstandingCallbacks();
}
References ApplyCompilationHintToInitialProgress(), ApplyPgoInfoToInitialProgress(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ExecutionTierPair::baseline_tier, callbacks_mutex_, compilation_progress_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NULL, v8::internal::wasm::NativeModule::enabled_features(), v8::base::BitField< T, shift, size, U >::encode(), failed(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::GetDefaultTiersPerModule(), v8::internal::wasm::NativeModule::IsInDebugState(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::IsLazyModule(), v8::internal::wasm::kEager, v8::internal::wasm::kNone, v8::internal::wasm::kOptimized, v8::internal::wasm::NativeModule::module(), native_module_, v8::base::OwnedVector< T >::New(), outstanding_baseline_units_, v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ExecutionTierPair::top_tier, TriggerOutstandingCallbacks(), v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::InitializeCompilation(), and v8::internal::wasm::InitializeCompilationForTesting().
InitializeCompilationProgressAfterDeserialization()
void v8::internal::wasm::CompilationStateImpl::InitializeCompilationProgressAfterDeserialization (base::Vector< const int > lazy_functions, base::Vector< const int > eager_functions)
Definition at line 3869 of file module-compiler.cc.
                                           {
  TRACE_EVENT2("v8.wasm", "wasm.CompilationAfterDeserialization",
               "num_lazy_functions", lazy_functions.size(),
               "num_eager_functions", eager_functions.size());
  std::optional<TimedHistogramScope> lazy_compile_time_scope;
  if (base::TimeTicks::IsHighResolution()) {
    lazy_compile_time_scope.emplace(
        counters()->wasm_compile_after_deserialize());
  }
  auto* module = native_module_->module();
  {
    base::MutexGuard guard(&callbacks_mutex_);
    DCHECK_NULL(compilation_progress_);
    // Initialize the compilation progress as if everything was
    // TurboFan-compiled.
    constexpr uint8_t kProgressAfterTurbofanDeserialization =
        RequiredBaselineTierField::encode(ExecutionTier::kLiftoff) |
        RequiredTopTierField::encode(ExecutionTier::kTurbofan) |
        ReachedTierField::encode(ExecutionTier::kTurbofan);
    compilation_progress_ = base::OwnedVector<uint8_t>::New(
        module->num_declared_functions, kProgressAfterTurbofanDeserialization);
    // Update compilation state for lazy functions.
    constexpr uint8_t kProgressForLazyFunctions =
        RequiredBaselineTierField::encode(ExecutionTier::kNone) |
        RequiredTopTierField::encode(ExecutionTier::kNone) |
        ReachedTierField::encode(ExecutionTier::kNone);
    for (auto func_index : lazy_functions) {
      compilation_progress_[declared_function_index(module, func_index)] =
          kProgressForLazyFunctions;
    }
    // Update compilation state for eagerly compiled functions.
    constexpr bool kNotLazy = false;
    ExecutionTierPair default_tiers = GetDefaultTiersPerModule(
        native_module_, native_module_->IsInDebugState(), kNotLazy);
    uint8_t progress_for_eager_functions =
        RequiredBaselineTierField::encode(default_tiers.baseline_tier) |
        RequiredTopTierField::encode(default_tiers.top_tier) |
        ReachedTierField::encode(ExecutionTier::kNone);
    for (auto func_index : eager_functions) {
      // Check that {func_index} is not contained in {lazy_functions}.
      DCHECK_EQ(
          compilation_progress_[declared_function_index(module, func_index)],
          kProgressAfterTurbofanDeserialization);
      compilation_progress_[declared_function_index(module, func_index)] =
          progress_for_eager_functions;
    }
    DCHECK_NE(ExecutionTier::kNone, default_tiers.baseline_tier);
    outstanding_baseline_units_ += eager_functions.size();
    // Baseline compilation is done if we do not have any Liftoff functions to
    // compile.
    if (eager_functions.empty() || v8_flags.wasm_lazy_compilation) {
      finished_events_.Add(CompilationEvent::kFinishedBaselineCompilation);
    }
  }
  auto builder = std::make_unique<CompilationUnitBuilder>(native_module_);
  InitializeCompilationUnits(std::move(builder));
  if (!v8_flags.wasm_lazy_compilation) {
    WaitForCompilationEvent(CompilationEvent::kFinishedBaselineCompilation);
  }
}
References v8::base::EnumSet< E, T >::Add(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ExecutionTierPair::baseline_tier, callbacks_mutex_, compilation_progress_, counters(), DCHECK_EQ, DCHECK_NE, DCHECK_NULL, v8::internal::wasm::declared_function_index(), v8::base::BitField< T, shift, size, U >::encode(), finished_events_, v8::internal::wasm::anonymous_namespace{module-compiler.cc}::GetDefaultTiersPerModule(), InitializeCompilationUnits(), v8::base::TimeTicks::IsHighResolution(), v8::internal::wasm::NativeModule::IsInDebugState(), v8::internal::wasm::kFinishedBaselineCompilation, v8::internal::wasm::kLiftoff, v8::internal::wasm::kNone, v8::internal::wasm::kTurbofan, v8::internal::wasm::NativeModule::module(), native_module_, v8::base::OwnedVector< T >::New(), outstanding_baseline_units_, v8::base::Vector< T >::size(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ExecutionTierPair::top_tier, TRACE_EVENT2, v8::internal::v8_flags, and WaitForCompilationEvent().
Referenced by v8::internal::wasm::CompilationState::InitializeAfterDeserialization().
InitializeCompilationUnitForSingleFunction()
void v8::internal::wasm::CompilationStateImpl::InitializeCompilationUnitForSingleFunction (CompilationUnitBuilder * builder, int func_index)
Definition at line 3817 of file module-compiler.cc.
                                                         {
  if (v8_flags.wasm_jitless) return;
  // Only during streaming compilation, we reach here without holding
  // `callbacks_mutex_`.
  // This avoids the observed overhead of taking the lock once per function.
  // This is correct (data-race free), because the only mutation of
  // `compilation_progress_` before reading it here without holding the lock is
  // when initializing the compilation during parsing of the code section
  // header (see `InitializeCompilationProgress` and
  // `AsyncStreamingProcessor::ProcessCodeSectionHeader`), which must happen
  // before processing functions.
  // Also, this read here happens exactly once per function, only for the
  // initial compilation, and all accesses to `compilation_progress_` thereafter
  // are synchronized via `callbacks_mutex_`.
  uint8_t function_progress = compilation_progress_[declared_function_index(
      native_module_->module(), function_index)];
  ExecutionTier required_baseline_tier =
      CompilationStateImpl::RequiredBaselineTierField::decode(
          function_progress);
  ExecutionTier required_top_tier =
      CompilationStateImpl::RequiredTopTierField::decode(function_progress);
  ExecutionTier reached_tier =
      CompilationStateImpl::ReachedTierField::decode(function_progress);
  if (reached_tier < required_baseline_tier) {
    builder->AddBaselineUnit(function_index, required_baseline_tier);
  }
  if (reached_tier < required_top_tier &&
      required_baseline_tier != required_top_tier) {
    builder->AddTopTierUnit(function_index, required_top_tier);
  }
}
References v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitBuilder::AddBaselineUnit(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitBuilder::AddTopTierUnit(), compilation_progress_, v8::internal::wasm::declared_function_index(), v8::base::BitField< T, shift, size, U >::decode(), v8::internal::wasm::NativeModule::module(), native_module_, and v8::internal::v8_flags.
Referenced by InitializeCompilationUnits().
InitializeCompilationUnits()
void v8::internal::wasm::CompilationStateImpl::InitializeCompilationUnits (std::unique_ptr< CompilationUnitBuilder > builder)
Definition at line 3852 of file module-compiler.cc.
                                                   {
  if (v8_flags.wasm_jitless) return;
  {
    base::MutexGuard guard(&callbacks_mutex_);
    const WasmModule* module = native_module_->module();
    DCHECK_EQ(module->num_declared_functions, compilation_progress_.size());
    int start = module->num_imported_functions;
    int end = start + module->num_declared_functions;
    for (int func_index = start; func_index < end; ++func_index) {
      InitializeCompilationUnitForSingleFunction(builder.get(), func_index);
    }
  }
  builder->Commit();
}
References callbacks_mutex_, compilation_progress_, DCHECK_EQ, v8::internal::compiler::end(), InitializeCompilationUnitForSingleFunction(), v8::internal::wasm::NativeModule::module(), native_module_, v8::internal::wasm::WasmModule::num_declared_functions, v8::internal::wasm::WasmModule::num_imported_functions, v8::base::OwnedVector< T >::size(), and v8::internal::v8_flags.
Referenced by InitializeCompilationProgressAfterDeserialization().
NumOutstandingCompilations()
size_t v8::internal::wasm::CompilationStateImpl::NumOutstandingCompilations (CompilationTier tier) const
Definition at line 4321 of file module-compiler.cc.
                                {
  return compilation_unit_queues_.GetSizeForTier(tier);
}
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::BackgroundCompileJob::GetMaxConcurrency().
OnCompilationStopped()
void v8::internal::wasm::CompilationStateImpl::OnCompilationStopped (WasmDetectedFeatures detected)
Definition at line 4229 of file module-compiler.cc.
                                            {
  WasmDetectedFeatures new_detected_features =
      UpdateDetectedFeatures(detected_features);
  if (new_detected_features.empty()) return;
  // New detected features can only happen during eager compilation or if lazy
  // validation is enabled.
  // The exceptions are currently stringref and imported strings, which are only
  // detected on top-tier compilation.
  DCHECK(!v8_flags.wasm_lazy_compilation || v8_flags.wasm_lazy_validation ||
         (new_detected_features -
          WasmDetectedFeatures{{WasmDetectedFeature::stringref,
                                WasmDetectedFeature::imported_strings_utf8,
                                WasmDetectedFeature::imported_strings}})
             .empty());
  // TODO(clemensb): Fix reporting of late detected features (relevant for lazy
  // validation and for stringref).
}
References v8::internal::DCHECK(), detected_features(), v8::base::EnumSet< E, T >::empty(), UpdateDetectedFeatures(), and v8::internal::v8_flags.
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ExecuteCompilationUnits().
OnFinishedUnits()
void v8::internal::wasm::CompilationStateImpl::OnFinishedUnits (base::Vector< WasmCode * > code_vector)
Definition at line 3996 of file module-compiler.cc.
                                       {
  TRACE_EVENT1(TRACE_DISABLED_BY_DEFAULT("v8.wasm.detailed"),
               "wasm.OnFinishedUnits", "units", code_vector.size());
  base::MutexGuard guard(&callbacks_mutex_);
  // Assume an order of execution tiers that represents the quality of their
  // generated code.
  static_assert(ExecutionTier::kNone < ExecutionTier::kLiftoff &&
                    ExecutionTier::kLiftoff < ExecutionTier::kTurbofan,
                "Assume an order on execution tiers");
  if (!v8_flags.wasm_jitless) {
    DCHECK_EQ(compilation_progress_.size(),
              native_module_->module()->num_declared_functions);
  }
  bool has_top_tier_code = false;
  for (size_t i = 0; i < code_vector.size(); i++) {
    WasmCode* code = code_vector[i];
    DCHECK_NOT_NULL(code);
    DCHECK_LT(code->index(), native_module_->num_functions());
    has_top_tier_code |= code->tier() == ExecutionTier::kTurbofan;
    if (code->index() <
        static_cast<int>(native_module_->num_imported_functions())) {
      // Import wrapper.
      DCHECK_EQ(code->tier(), ExecutionTier::kTurbofan);
      outstanding_baseline_units_--;
    } else {
      // Function.
      DCHECK_NE(code->tier(), ExecutionTier::kNone);
      // Read function's compilation progress.
      // This view on the compilation progress may differ from the actually
      // compiled code. Any lazily compiled function does not contribute to the
      // compilation progress but may publish code to the code manager.
      uint8_t& function_progress =
          compilation_progress_[declared_function_index(
              native_module_->module(), code->index())];
      ExecutionTier required_baseline_tier =
          RequiredBaselineTierField::decode(function_progress);
      ExecutionTier reached_tier = ReachedTierField::decode(function_progress);
      // Check whether required baseline or top tier are reached.
      if (reached_tier < required_baseline_tier &&
          required_baseline_tier <= code->tier()) {
        DCHECK_GT(outstanding_baseline_units_, 0);
        outstanding_baseline_units_--;
      }
      if (code->tier() == ExecutionTier::kTurbofan) {
        bytes_since_last_chunk_ += code->instructions().size();
      }
      // Update function's compilation progress.
      if (code->tier() > reached_tier) {
        function_progress =
            ReachedTierField::update(function_progress, code->tier());
      }
      // Allow another top tier compilation if deopts are enabled and the
      // currently installed code object is a liftoff object.
      // Ideally, this would be done only if the code->tier() ==
      // ExecutionTier::Liftoff as the code object for which we run this
      // function should be the same as the one installed on the native_module.
      // This is unfortunately not the case as installing a code object on the
      // native module and updating the compilation_progress_ and the
      // CompilationUnitQueues::top_tier_compiled_ are not synchronized.
      // Note: GetCode() acquires the NativeModule::allocation_mutex_, so this
      // could cause deadlocks if any other place acquires
      // NativeModule::allocation_mutex_ first and then
      // CompilationStateImpl::callbacks_mutex_!
      const bool is_liftoff = code->tier() == ExecutionTier::kLiftoff;
      auto published_code_is_liftoff = [this](int index) {
        WasmCode* code = native_module_->GetCode(index);
        if (code == nullptr) return false;
        return code->is_liftoff();
      };
      if (v8_flags.wasm_deopt &&
          (is_liftoff || published_code_is_liftoff(code->index()))) {
        // Setting the reached tier below the baseline tier would create an
        // inconsistent state and has actually led to crashes before (see
        // https://crbug.com/379086474).
        DCHECK_LE(required_baseline_tier, ExecutionTier::kLiftoff);
        function_progress = ReachedTierField::update(function_progress,
                                                     ExecutionTier::kLiftoff);
        compilation_unit_queues_.AllowAnotherTopTierJob(code->index());
      }
      DCHECK_LE(0, outstanding_baseline_units_);
    }
  }
  // Update the {last_top_tier_compilation_timestamp_} if it is set (i.e. a
  // delayed task has already been spawned).
  if (has_top_tier_code && !last_top_tier_compilation_timestamp_.IsNull()) {
    last_top_tier_compilation_timestamp_ = base::TimeTicks::Now();
  }
  TriggerOutstandingCallbacks();
}
References v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::AllowAnotherTopTierJob(), bytes_since_last_chunk_, callbacks_mutex_, code, compilation_progress_, compilation_unit_queues_, DCHECK_EQ, DCHECK_GT, DCHECK_LE, DCHECK_LT, DCHECK_NE, DCHECK_NOT_NULL, v8::internal::wasm::declared_function_index(), v8::base::BitField< T, shift, size, U >::decode(), v8::internal::wasm::NativeModule::GetCode(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::base::time_internal::TimeBase< TimeClass >::IsNull(), v8::internal::wasm::kLiftoff, v8::internal::wasm::kNone, v8::internal::wasm::kTurbofan, last_top_tier_compilation_timestamp_, v8::internal::wasm::NativeModule::module(), native_module_, v8::base::TimeTicks::Now(), v8::internal::wasm::WasmModule::num_declared_functions, v8::internal::wasm::NativeModule::num_functions(), v8::internal::wasm::NativeModule::num_imported_functions(), outstanding_baseline_units_, v8::base::Vector< T >::size(), v8::base::OwnedVector< T >::size(), TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT1, TriggerOutstandingCallbacks(), v8::base::BitField< T, shift, size, U >::update(), and v8::internal::v8_flags.
PublishCode()
std::vector< WasmCode * > v8::internal::wasm::CompilationStateImpl::PublishCode (base::Vector< UnpublishedWasmCode > codes)
Definition at line 4276 of file module-compiler.cc.
                                          {
  WasmCodeRefScope code_ref_scope;
  std::vector<WasmCode*> published_code =
      native_module_->PublishCode(std::move(code));
  // Defer logging code in case wire bytes were not fully received yet.
  if (native_module_->log_code() && native_module_->HasWireBytes()) {
    GetWasmEngine()->LogCode(base::VectorOf(published_code));
  }
  OnFinishedUnits(base::VectorOf(published_code));
  return published_code;
}
References code, v8::internal::wasm::GetWasmEngine(), v8::internal::wasm::WasmEngine::LogCode(), and v8::base::VectorOf().
Referenced by v8::internal::wasm::CompilationState::PublishCode().
PublishCompilationResults()
void v8::internal::wasm::CompilationStateImpl::PublishCompilationResults (std::vector< UnpublishedWasmCode > unpublished_code) [private]
Definition at line 4261 of file module-compiler.cc.
                                                     {
  if (unpublished_code.empty()) return;
#if DEBUG
  // We don't compile import wrappers eagerly.
  for (const auto& [code, assumptions] : unpublished_code) {
    int func_index = code->index();
    DCHECK_LE(native_module_->num_imported_functions(), func_index);
    DCHECK_LT(func_index, native_module_->num_functions());
  }
#endif
  PublishCode(base::VectorOf(unpublished_code));
}
References code, DCHECK_LE, DCHECK_LT, and v8::base::VectorOf().
SchedulePublishCompilationResults()
void v8::internal::wasm::CompilationStateImpl::SchedulePublishCompilationResults (std::vector< UnpublishedWasmCode > unpublished_code, CompilationTier tier)
Definition at line 4290 of file module-compiler.cc.
                                                                           {
  PublishState& state = publish_state_[tier];
  {
    base::MutexGuard guard(&state.mutex_);
    if (state.publisher_running_) {
      // Add new code to the queue and return.
      state.publish_queue_.reserve(state.publish_queue_.size() +
                                   unpublished_code.size());
      for (auto& c : unpublished_code) {
        state.publish_queue_.emplace_back(std::move(c));
      }
      return;
    }
    state.publisher_running_ = true;
  }
  while (true) {
    PublishCompilationResults(std::move(unpublished_code));
    unpublished_code.clear();
    // Keep publishing new code that came in.
    base::MutexGuard guard(&state.mutex_);
    DCHECK(state.publisher_running_);
    if (state.publish_queue_.empty()) {
      state.publisher_running_ = false;
      return;
    }
    unpublished_code.swap(state.publish_queue_);
  }
}
References v8::internal::DCHECK(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::PublishState::mutex_, v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::PublishState::publish_queue_, and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::PublishState::publisher_running_.
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ExecuteCompilationUnits().
set_compilation_id()
void v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::set_compilation_id (int compilation_id) [inline]
Definition at line 715 of file module-compiler.cc.
                                              {
    DCHECK_EQ(compilation_id_, kInvalidCompilationID);
    compilation_id_ = compilation_id;
  }
References DCHECK_EQ.
Referenced by v8::internal::wasm::CompilationState::set_compilation_id().
SetError()
void v8::internal::wasm::CompilationStateImpl::SetError ()
Definition at line 4326 of file module-compiler.cc.
                                    {
  compile_cancelled_.store(true, std::memory_order_relaxed);
  if (compile_failed_.exchange(true, std::memory_order_relaxed)) {
    return; // Already failed before.
  }
  base::MutexGuard callbacks_guard(&callbacks_mutex_);
  TriggerOutstandingCallbacks();
  callbacks_.clear();
}
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ExecuteCompilationUnits(), and v8::internal::wasm::CompilationState::SetError().
SetWireBytesStorage()
void v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::SetWireBytesStorage (std::shared_ptr< WireBytesStorage > wire_bytes_storage) [inline]
Definition at line 703 of file module-compiler.cc.
                                                          {
    base::MutexGuard guard(&mutex_);
    wire_bytes_storage_ = std::move(wire_bytes_storage);
  }
Referenced by v8::internal::wasm::CompilationState::SetWireBytesStorage().
TierUpAllFunctions()
void v8::internal::wasm::CompilationStateImpl::TierUpAllFunctions ()
Definition at line 4355 of file module-compiler.cc.
                                              {
  const WasmModule* module = native_module_->module();
  uint32_t num_wasm_functions = module->num_declared_functions;
  WasmCodeRefScope code_ref_scope;
  CompilationUnitBuilder builder(native_module_);
  for (uint32_t i = 0; i < num_wasm_functions; ++i) {
    int func_index = module->num_imported_functions + i;
    WasmCode* code = native_module_->GetCode(func_index);
    if (!code || !code->is_turbofan()) {
      builder.AddTopTierUnit(func_index, ExecutionTier::kTurbofan);
    }
  }
  builder.Commit();
  // Join the compilation, until no compilation units are left anymore.
  class DummyDelegate final : public JobDelegate {
    bool ShouldYield() override { return false; }
    bool IsJoiningThread() const override { return true; }
    void NotifyConcurrencyIncrease() override { UNIMPLEMENTED(); }
    uint8_t GetTaskId() override { return kMainTaskId; }
  };
  DummyDelegate delegate;
  ExecuteCompilationUnits(native_module_weak_, async_counters_.get(), &delegate,
                          CompilationTier::kTopTier);
  // We cannot wait for other compilation threads to finish, so we explicitly
  // compile all functions which are not yet available as TurboFan code.
  for (uint32_t i = 0; i < num_wasm_functions; ++i) {
    uint32_t func_index = module->num_imported_functions + i;
    WasmCode* code = native_module_->GetCode(func_index);
    if (!code || !code->is_turbofan()) {
      wasm::GetWasmEngine()->CompileFunction(async_counters_.get(),
                                             native_module_, func_index,
                                             wasm::ExecutionTier::kTurbofan);
    }
  }
}
References v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitBuilder::AddTopTierUnit(), code, v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitBuilder::Commit(), v8::internal::wasm::WasmEngine::CompileFunction(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ExecuteCompilationUnits(), v8::internal::wasm::GetWasmEngine(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::anonymous_namespace{module-compiler.cc}::kMainTaskId, v8::internal::wasm::anonymous_namespace{module-compiler.cc}::kTopTier, v8::internal::wasm::kTurbofan, v8::internal::wasm::WasmModule::num_declared_functions, v8::internal::wasm::WasmModule::num_imported_functions, and v8::internal::UNIMPLEMENTED().
Referenced by v8::internal::wasm::CompilationState::TierUpAllFunctions().
TriggerCachingAfterTimeout()
void v8::internal::wasm::CompilationStateImpl::TriggerCachingAfterTimeout ()
Definition at line 4197 of file module-compiler.cc.
                                                      {
  base::MutexGuard guard{&callbacks_mutex_};
  // It can happen that we reached the hard threshold while waiting for the
  // timeout to expire. In that case, {bytes_since_last_chunk_} might be zero
  // and there is nothing new to cache.
  if (bytes_since_last_chunk_ == 0) return;
  DCHECK(!last_top_tier_compilation_timestamp_.IsNull());
  base::TimeTicks caching_time =
      last_top_tier_compilation_timestamp_ +
      base::TimeDelta::FromMilliseconds(v8_flags.wasm_caching_timeout_ms);
  base::TimeDelta time_until_caching = caching_time - base::TimeTicks::Now();
  // If we are still half a millisecond or more away from the timeout,
  // reschedule the task. Otherwise, call the caching callback.
  if (time_until_caching >= base::TimeDelta::FromMicroseconds(500)) {
    int ms_remaining =
        static_cast<int>(time_until_caching.InMillisecondsRoundedUp());
    DCHECK_LE(1, ms_remaining);
    V8::GetCurrentPlatform()->PostDelayedTaskOnWorkerThread(
        TaskPriority::kUserVisible,
        std::make_unique<TriggerCodeCachingAfterTimeoutTask>(
            native_module_weak_),
        ms_remaining);
    return;
  }
  TriggerCallbacks({CompilationEvent::kFinishedCompilationChunk});
  last_top_tier_compilation_timestamp_ = {};
  bytes_since_last_chunk_ = 0;
}
References bytes_since_last_chunk_, callbacks_mutex_, v8::internal::DCHECK(), DCHECK_LE, v8::base::TimeDelta::FromMicroseconds(), v8::base::TimeDelta::FromMilliseconds(), v8::internal::V8::GetCurrentPlatform(), v8::base::TimeDelta::InMillisecondsRoundedUp(), v8::base::time_internal::TimeBase< TimeClass >::IsNull(), v8::internal::wasm::kFinishedCompilationChunk, v8::kUserVisible, last_top_tier_compilation_timestamp_, native_module_weak_, v8::base::TimeTicks::Now(), v8::Platform::PostDelayedTaskOnWorkerThread(), TriggerCallbacks(), and v8::internal::v8_flags.
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::TriggerCodeCachingAfterTimeoutTask::Run().
TriggerCallbacks()
void v8::internal::wasm::CompilationStateImpl::TriggerCallbacks (base::EnumSet< CompilationEvent > events) [private]
Definition at line 4164 of file module-compiler.cc.
                                          {
  if (events.empty()) return;
  // Don't trigger past events again.
  events -= finished_events_;
  // There can be multiple compilation chunks, thus do not store this.
  finished_events_ |= events - CompilationEvent::kFinishedCompilationChunk;
  for (auto event :
       {std::make_pair(CompilationEvent::kFailedCompilation,
                       "wasm.CompilationFailed"),
        std::make_pair(CompilationEvent::kFinishedBaselineCompilation,
                       "wasm.BaselineFinished"),
        std::make_pair(CompilationEvent::kFinishedCompilationChunk,
                       "wasm.CompilationChunkFinished")}) {
    if (!events.contains(event.first)) continue;
    DCHECK_NE(compilation_id_, kInvalidCompilationID);
    TRACE_EVENT1("v8.wasm", event.second, "id", compilation_id_);
    for (auto& callback : callbacks_) {
      callback->call(event.first);
    }
  }
  if (outstanding_baseline_units_ == 0) {
    auto new_end = std::remove_if(
        callbacks_.begin(), callbacks_.end(), [](const auto& callback) {
          return callback->release_after_final_event();
        });
    callbacks_.erase(new_end, callbacks_.end());
  }
}
References callbacks_, compilation_id_, v8::base::EnumSet< E, T >::contains(), DCHECK_NE, v8::base::EnumSet< E, T >::empty(), finished_events_, v8::internal::wasm::kFailedCompilation, v8::internal::wasm::kFinishedBaselineCompilation, v8::internal::wasm::kFinishedCompilationChunk, kInvalidCompilationID, outstanding_baseline_units_, and TRACE_EVENT1.
Referenced by TriggerCachingAfterTimeout(), and TriggerOutstandingCallbacks().
TriggerOutstandingCallbacks()
void v8::internal::wasm::CompilationStateImpl::TriggerOutstandingCallbacks () [private]
Definition at line 4117 of file module-compiler.cc.
                                                       {
  callbacks_mutex_.AssertHeld();
  base::EnumSet<CompilationEvent> triggered_events;
  if (outstanding_baseline_units_ == 0) {
    triggered_events.Add(CompilationEvent::kFinishedBaselineCompilation);
  }
  // For dynamic tiering, trigger "compilation chunk finished" after a new chunk
  // of size {v8_flags.wasm_caching_threshold}.
  if (v8_flags.wasm_dynamic_tiering &&
      static_cast<size_t>(v8_flags.wasm_caching_threshold) <=
          bytes_since_last_chunk_) {
    // Trigger caching immediately if
    // - there is no timeout,
    // - the hard threshold was reached, or
    // - we are running single-threaded.
    if (v8_flags.single_threaded || v8_flags.wasm_caching_timeout_ms <= 0 ||
        static_cast<size_t>(v8_flags.wasm_caching_hard_threshold) <=
            bytes_since_last_chunk_) {
      triggered_events.Add(CompilationEvent::kFinishedCompilationChunk);
      bytes_since_last_chunk_ = 0;
    } else if (last_top_tier_compilation_timestamp_.IsNull()) {
      // Trigger a task after the given timeout; that task will only trigger
      // caching if no new code was added until then. Otherwise, it will
      // re-schedule itself.
      V8::GetCurrentPlatform()->PostDelayedTaskOnWorkerThread(
          TaskPriority::kUserVisible,
          std::make_unique<TriggerCodeCachingAfterTimeoutTask>(
              native_module_weak_),
          1e-3 * v8_flags.wasm_caching_timeout_ms);
      // Set the timestamp (will be updated by {OnFinishedUnits} if more
      // top-tier compilation finished before the delayed task is being run).
      last_top_tier_compilation_timestamp_ = base::TimeTicks::Now();
    }
  }
  if (compile_failed_.load(std::memory_order_relaxed)) {
    // *Only* trigger the "failed" event.
    triggered_events =
        base::EnumSet<CompilationEvent>({CompilationEvent::kFailedCompilation});
  }
  TriggerCallbacks(triggered_events);
}
References v8::base::EnumSet< E, T >::Add(), v8::base::Mutex::AssertHeld(), bytes_since_last_chunk_, callbacks_mutex_, compile_failed_, v8::internal::V8::GetCurrentPlatform(), v8::base::time_internal::TimeBase< TimeClass >::IsNull(), v8::internal::wasm::kFailedCompilation, v8::internal::wasm::kFinishedBaselineCompilation, v8::internal::wasm::kFinishedCompilationChunk, v8::kUserVisible, last_top_tier_compilation_timestamp_, native_module_weak_, v8::base::TimeTicks::Now(), outstanding_baseline_units_, v8::Platform::PostDelayedTaskOnWorkerThread(), TriggerCallbacks(), and v8::internal::v8_flags.
Referenced by InitializeCompilationProgress(), and OnFinishedUnits().
UpdateDetectedFeatures()
WasmDetectedFeatures v8::internal::wasm::CompilationStateImpl::UpdateDetectedFeatures (WasmDetectedFeatures detected_features)
Definition at line 4249 of file module-compiler.cc.
                                            {
  WasmDetectedFeatures old_features =
      detected_features_.load(std::memory_order_relaxed);
  while (!detected_features_.compare_exchange_weak(
      old_features, old_features | detected_features,
      std::memory_order_relaxed)) {
    // Retry with updated {old_features}.
  }
  return detected_features - old_features;
}
Referenced by OnCompilationStopped(), and v8::internal::wasm::CompilationState::UpdateDetectedFeatures().
WaitForCompilationEvent()
void v8::internal::wasm::CompilationStateImpl::WaitForCompilationEvent (CompilationEvent event)
Definition at line 4337 of file module-compiler.cc.
                                   {
  switch (expect_event) {
    case CompilationEvent::kFinishedBaselineCompilation:
      if (baseline_compile_job_->IsValid()) baseline_compile_job_->Join();
      break;
    default:
      // Waiting on other CompilationEvent doesn't make sense.
      UNREACHABLE();
  }
#ifdef DEBUG
  base::EnumSet<CompilationEvent> events{expect_event,
                                         CompilationEvent::kFailedCompilation};
  base::MutexGuard guard(&callbacks_mutex_);
  DCHECK(finished_events_.contains_any(events));
#endif
}
References v8::internal::DCHECK(), v8::internal::wasm::kFailedCompilation, v8::internal::wasm::kFinishedBaselineCompilation, and v8::internal::UNREACHABLE().
Referenced by InitializeCompilationProgressAfterDeserialization().
Member Data Documentation
async_counters_
const std::shared_ptr<Counters> v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::async_counters_ [private]
Definition at line 744 of file module-compiler.cc.
Referenced by InitCompileJob().
baseline_compile_job_
std::unique_ptr<JobHandle> v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::baseline_compile_job_ [private]
Definition at line 762 of file module-compiler.cc.
Referenced by CommitCompilationUnits(), and InitCompileJob().
bytes_since_last_chunk_
size_t v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::bytes_since_last_chunk_ = 0 [private]
Definition at line 802 of file module-compiler.cc.
Referenced by OnFinishedUnits(), TriggerCachingAfterTimeout(), and TriggerOutstandingCallbacks().
callbacks_
std::vector<std::unique_ptr<CompilationEventCallback> > v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::callbacks_ [private]
Definition at line 793 of file module-compiler.cc.
Referenced by AddCallback(), CancelCompilation(), and TriggerCallbacks().
callbacks_mutex_
base::Mutex v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::callbacks_mutex_ [mutable], [private]
Definition at line 787 of file module-compiler.cc.
Referenced by AddCallback(), ApplyPgoInfoLate(), CancelCompilation(), InitializeCompilationProgress(), InitializeCompilationProgressAfterDeserialization(), InitializeCompilationUnits(), OnFinishedUnits(), TriggerCachingAfterTimeout(), and TriggerOutstandingCallbacks().
compilation_id_
int v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::compilation_id_ = kInvalidCompilationID [private]
Definition at line 767 of file module-compiler.cc.
Referenced by TriggerCallbacks().
compilation_progress_
base::OwnedVector<uint8_t> v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::compilation_progress_ [private]
Definition at line 809 of file module-compiler.cc.
Referenced by ApplyCompilationHintToInitialProgress(), ApplyPgoInfoLate(), ApplyPgoInfoToInitialProgress(), InitializeCompilationProgress(), InitializeCompilationProgressAfterDeserialization(), InitializeCompilationUnitForSingleFunction(), InitializeCompilationUnits(), and OnFinishedUnits().
compilation_unit_queues_
CompilationUnitQueues v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::compilation_unit_queues_ [private]
Definition at line 754 of file module-compiler.cc.
Referenced by AddTopTierPriorityCompilationUnit(), CommitCompilationUnits(), GetNextCompilationUnit(), GetQueueForCompileTask(), and OnFinishedUnits().
compile_cancelled_
std::atomic<bool> v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::compile_cancelled_ {false} [private]
Definition at line 752 of file module-compiler.cc.
Referenced by CancelCompilation(), and cancelled().
compile_failed_
std::atomic<bool> v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::compile_failed_ {false} [private]
Definition at line 748 of file module-compiler.cc.
Referenced by TriggerOutstandingCallbacks().
detected_features_
std::atomic<WasmDetectedFeatures> v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::detected_features_ [private]
Definition at line 771 of file module-compiler.cc.
finished_events_
base::EnumSet<CompilationEvent> v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::finished_events_ [private]
Definition at line 796 of file module-compiler.cc.
Referenced by AddCallback(), CancelCompilation(), InitializeCompilationProgressAfterDeserialization(), and TriggerCallbacks().
kInvalidCompilationID
constexpr int v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::kInvalidCompilationID = -1 [static], [constexpr], [private]
Definition at line 766 of file module-compiler.cc.
Referenced by TriggerCallbacks().
last_top_tier_compilation_timestamp_
base::TimeTicks v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::last_top_tier_compilation_timestamp_ [private]
Definition at line 815 of file module-compiler.cc.
Referenced by OnFinishedUnits(), TriggerCachingAfterTimeout(), and TriggerOutstandingCallbacks().
mutex_
base::Mutex v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::mutex_ [mutable], [private]
Definition at line 758 of file module-compiler.cc.
Referenced by CommitCompilationUnits().
native_module_
NativeModule* const v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::native_module_ [private]
Definition at line 742 of file module-compiler.cc.
Referenced by ApplyPgoInfoLate(), ApplyPgoInfoToInitialProgress(), CommitCompilationUnits(), InitializeCompilationProgress(), InitializeCompilationProgressAfterDeserialization(), InitializeCompilationUnitForSingleFunction(), InitializeCompilationUnits(), and OnFinishedUnits().
native_module_weak_
std::weak_ptr<NativeModule> const v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::native_module_weak_ [private]
Definition at line 743 of file module-compiler.cc.
Referenced by InitCompileJob(), TriggerCachingAfterTimeout(), and TriggerOutstandingCallbacks().
outstanding_baseline_units_
int v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::outstanding_baseline_units_ = 0 [private]
Definition at line 798 of file module-compiler.cc.
Referenced by ApplyCompilationHintToInitialProgress(), ApplyPgoInfoToInitialProgress(), InitializeCompilationProgress(), InitializeCompilationProgressAfterDeserialization(), OnFinishedUnits(), TriggerCallbacks(), and TriggerOutstandingCallbacks().
publish_state_
PublishState v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::publish_state_[CompilationTier::kNumTiers] [private]
Definition at line 826 of file module-compiler.cc.
top_tier_compile_job_
std::unique_ptr<JobHandle> v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::top_tier_compile_job_ [private]
Definition at line 763 of file module-compiler.cc.
Referenced by AddTopTierPriorityCompilationUnit(), CommitCompilationUnits(), and InitCompileJob().
wire_bytes_storage_
std::shared_ptr<WireBytesStorage> v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::wire_bytes_storage_ [private]
Definition at line 779 of file module-compiler.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/module-compiler.cc