v8::internal::compiler::BasicBlock Class Reference
#include <schedule.h>
Classes
class Id
Public Types
enum Control {
kNone
, kGoto
, kCall
, kBranch
,
kSwitch
, kDeoptimize
, kTailCall
, kReturn
,
kThrow
 }
using value_type = Node *
using iterator = NodeVector::iterator
using const_iterator = NodeVector::const_iterator
using reverse_iterator = NodeVector::reverse_iterator
Public Member Functions
BasicBlock (Zone *zone, Id id)
BasicBlock (const BasicBlock &)=delete
BasicBlock & operator= (const BasicBlock &)=delete
Id id () const
void Print ()
BasicBlockVector & predecessors ()
const BasicBlockVector & predecessors () const
size_t PredecessorCount () const
BasicBlock * PredecessorAt (size_t index)
void ClearPredecessors ()
void AddPredecessor (BasicBlock *predecessor)
void RemovePredecessor (size_t index)
BasicBlockVector & successors ()
const BasicBlockVector & successors () const
size_t SuccessorCount () const
BasicBlock * SuccessorAt (size_t index)
void ClearSuccessors ()
void AddSuccessor (BasicBlock *successor)
bool empty () const
size_t size () const
Node * NodeAt (size_t index)
size_t NodeCount () const
value_type & front ()
value_type const & front () const
iterator begin ()
iterator end ()
void RemoveNode (iterator it)
const_iterator begin () const
const_iterator end () const
reverse_iterator rbegin ()
reverse_iterator rend ()
void AddNode (Node *node)
template<class InputIterator >
void InsertNodes (iterator insertion_point, InputIterator insertion_start, InputIterator insertion_end)
void TrimNodes (iterator new_end)
void ResetRPOInfo ()
Control control () const
void set_control (Control control)
Node * control_input () const
void set_control_input (Node *control_input)
bool deferred () const
void set_deferred (bool deferred)
int32_t dominator_depth () const
void set_dominator_depth (int32_t depth)
BasicBlock * dominator () const
void set_dominator (BasicBlock *dominator)
BasicBlock * rpo_next () const
void set_rpo_next (BasicBlock *rpo_next)
BasicBlock * loop_header () const
void set_loop_header (BasicBlock *loop_header)
BasicBlock * loop_end () const
void set_loop_end (BasicBlock *loop_end)
int32_t loop_depth () const
void set_loop_depth (int32_t loop_depth)
int32_t loop_number () const
void set_loop_number (int32_t loop_number)
int32_t rpo_number () const
void set_rpo_number (int32_t rpo_number)
NodeVector * nodes ()
bool IsLoopHeader () const
bool LoopContains (BasicBlock *block) const
Static Public Member Functions
static BasicBlock * GetCommonDominator (BasicBlock *b1, BasicBlock *b2)
Private Attributes
int32_t loop_number_
int32_t rpo_number_
bool deferred_
int32_t dominator_depth_
BasicBlock * dominator_
BasicBlock * rpo_next_
BasicBlock * loop_header_
BasicBlock * loop_end_
int32_t loop_depth_
Control control_
Node * control_input_
NodeVector nodes_
BasicBlockVector successors_
BasicBlockVector predecessors_
Id id_
Detailed Description
Definition at line 29 of file schedule.h.
Member Typedef Documentation
const_iterator
using v8::internal::compiler::BasicBlock::const_iterator = NodeVector::const_iterator
Definition at line 105 of file schedule.h.
iterator
using v8::internal::compiler::BasicBlock::iterator = NodeVector::iterator
Definition at line 99 of file schedule.h.
reverse_iterator
using v8::internal::compiler::BasicBlock::reverse_iterator = NodeVector::reverse_iterator
Definition at line 109 of file schedule.h.
value_type
using v8::internal::compiler::BasicBlock::value_type = Node*
Definition at line 90 of file schedule.h.
Member Enumeration Documentation
Control
enum v8::internal::compiler::BasicBlock::Control
Enumerator
kNone
kGoto
kCall
kBranch
kSwitch
kDeoptimize
kTailCall
kReturn
kThrow
Definition at line 33 of file schedule.h.
               {
    kNone, // Control not initialized yet.
    kGoto, // Goto a single successor block.
    kCall, // Call with continuation as first successor, exception
                  // second.
    kBranch, // Branch if true to first successor, otherwise second.
    kSwitch, // Table dispatch to one of the successor blocks.
    kDeoptimize, // Return a value from this method.
    kTailCall, // Tail call another method from this method.
    kReturn, // Return a value from this method.
    kThrow // Throw an exception.
  };
Constructor & Destructor Documentation
BasicBlock() [1/2]
v8::internal::compiler::BasicBlock::BasicBlock (Zone * zone, Id id)
Definition at line 15 of file schedule.cc.
    : loop_number_(-1),
      rpo_number_(-1),
      deferred_(false),
      dominator_depth_(-1),
      dominator_(nullptr),
      rpo_next_(nullptr),
      loop_header_(nullptr),
      loop_end_(nullptr),
      loop_depth_(0),
      control_(kNone),
      control_input_(nullptr),
      nodes_(zone),
      successors_(zone),
      predecessors_(zone),
#if DEBUG
      debug_info_(AssemblerDebugInfo(nullptr, nullptr, -1)),
#endif
#ifdef LOG_BUILTIN_BLOCK_COUNT
      pgo_execution_count_(0),
#endif
      id_(id) {
}
References v8::internal::kNone.
BasicBlock() [2/2]
v8::internal::compiler::BasicBlock::BasicBlock (const BasicBlock &) [delete]
Member Function Documentation
AddNode()
void v8::internal::compiler::BasicBlock::AddNode (Node * node)
Definition at line 60 of file schedule.cc.
{ nodes_.push_back(node); }
References nodes_, and v8::internal::ZoneVector< T >::push_back().
Referenced by v8::internal::compiler::Schedule::AddNode(), v8::internal::compiler::RawMachineAssembler::Branch(), v8::internal::compiler::Schedule::MovePhis(), and v8::internal::compiler::RawMachineAssembler::OptimizeControlFlow().
AddPredecessor()
void v8::internal::compiler::BasicBlock::AddPredecessor (BasicBlock * predecessor)
Definition at line 52 of file schedule.cc.
                                                       {
  predecessors_.push_back(predecessor);
}
References predecessors_, and v8::internal::ZoneVector< T >::push_back().
Referenced by v8::internal::compiler::Schedule::AddSuccessor().
AddSuccessor()
void v8::internal::compiler::BasicBlock::AddSuccessor (BasicBlock * successor)
Definition at line 48 of file schedule.cc.
                                                   {
  successors_.push_back(successor);
}
References v8::internal::ZoneVector< T >::push_back(), and successors_.
Referenced by v8::internal::compiler::Schedule::AddSuccessor(), and v8::internal::compiler::Schedule::MoveSuccessors().
begin() [1/2]
iterator v8::internal::compiler::BasicBlock::begin () [inline]
Definition at line 100 of file schedule.h.
{ return nodes_.begin(); }
Referenced by v8::internal::compiler::Schedule::EliminateRedundantPhiNodes(), v8::internal::compiler::FindInsertionPoint(), v8::internal::compiler::Schedule::MovePhis(), v8::internal::compiler::RawMachineAssembler::OptimizeControlFlow(), v8::internal::compiler::GraphC1Visualizer::PrintSchedule(), and v8::internal::compiler::anonymous_namespace{turbofan-graph-visualizer.cc}::PrintScheduledGraph().
begin() [2/2]
const_iterator v8::internal::compiler::BasicBlock::begin () const [inline]
Definition at line 106 of file schedule.h.
{ return nodes_.begin(); }
ClearPredecessors()
void v8::internal::compiler::BasicBlock::ClearPredecessors () [inline]
Definition at line 77 of file schedule.h.
{ predecessors_.clear(); }
Referenced by v8::internal::compiler::RawMachineAssembler::OptimizeControlFlow().
ClearSuccessors()
void v8::internal::compiler::BasicBlock::ClearSuccessors () [inline]
Definition at line 86 of file schedule.h.
{ successors_.clear(); }
Referenced by v8::internal::compiler::Schedule::MoveSuccessors(), and v8::internal::compiler::RawMachineAssembler::OptimizeControlFlow().
control()
Control v8::internal::compiler::BasicBlock::control () const [inline]
Definition at line 126 of file schedule.h.
{ return control_; }
Referenced by v8::internal::compiler::Schedule::AddBranch(), v8::internal::compiler::Schedule::AddCall(), v8::internal::compiler::Schedule::AddDeoptimize(), v8::internal::compiler::Schedule::AddGoto(), v8::internal::compiler::Schedule::AddReturn(), v8::internal::compiler::Schedule::AddSwitch(), v8::internal::compiler::Schedule::AddTailCall(), v8::internal::compiler::Schedule::AddThrow(), v8::internal::compiler::Schedule::InsertBranch(), v8::internal::compiler::Schedule::InsertSwitch(), v8::internal::compiler::BasicBlockInstrumentor::Instrument(), v8::internal::compiler::RawMachineAssembler::OptimizeControlFlow(), v8::internal::compiler::GraphC1Visualizer::PrintSchedule(), set_control(), and v8::internal::compiler::BasicBlockCallGraphProfiler::StoreCallGraph().
control_input()
Node* v8::internal::compiler::BasicBlock::control_input () const [inline]
Definition at line 129 of file schedule.h.
{ return control_input_; }
Referenced by v8::internal::compiler::HasDominatingDef(), v8::internal::compiler::Schedule::InsertBranch(), v8::internal::compiler::Schedule::InsertSwitch(), v8::internal::compiler::RawMachineAssembler::OptimizeControlFlow(), v8::internal::compiler::GraphC1Visualizer::PrintSchedule(), v8::internal::compiler::anonymous_namespace{turbofan-graph-visualizer.cc}::PrintScheduledGraph(), v8::internal::compiler::ScheduleVerifier::Run(), set_control_input(), and v8::internal::compiler::BasicBlockCallGraphProfiler::StoreCallGraph().
deferred()
bool v8::internal::compiler::BasicBlock::deferred () const [inline]
Definition at line 132 of file schedule.h.
{ return deferred_; }
Referenced by v8::internal::compiler::InstructionBlockFor(), v8::internal::compiler::RawMachineAssembler::OptimizeControlFlow(), v8::internal::compiler::Schedule::PropagateDeferredMark(), and v8::internal::compiler::Scheduler::PropagateImmediateDominators().
dominator()
BasicBlock* v8::internal::compiler::BasicBlock::dominator () const [inline]
Definition at line 138 of file schedule.h.
{ return dominator_; }
Referenced by v8::internal::compiler::Dominates(), GetCommonDominator(), v8::internal::compiler::Scheduler::GetCommonDominator(), v8::internal::compiler::ScheduleLateNodeVisitor::GetHoistBlock(), v8::internal::compiler::HasDominatingDef(), v8::internal::compiler::InstructionBlockFor(), v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::IsClosebyDominator(), v8::internal::compiler::GraphC1Visualizer::PrintSchedule(), v8::internal::compiler::Scheduler::PropagateImmediateDominators(), v8::internal::compiler::ScheduleVerifier::Run(), and v8::internal::compiler::ScheduleLateNodeVisitor::SplitNode().
dominator_depth()
int32_t v8::internal::compiler::BasicBlock::dominator_depth () const [inline]
Definition at line 135 of file schedule.h.
{ return dominator_depth_; }
Referenced by GetCommonDominator(), v8::internal::compiler::Scheduler::GetCommonDominator(), v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::IsClosebyDominator(), v8::internal::compiler::Scheduler::PropagateImmediateDominators(), v8::internal::compiler::ScheduleEarlyNodeVisitor::PropagateMinimumPositionToNode(), v8::internal::compiler::ScheduleEarlyNodeVisitor::VisitNode(), and v8::internal::compiler::ScheduleLateNodeVisitor::VisitNode().
empty()
bool v8::internal::compiler::BasicBlock::empty () const [inline]
Definition at line 91 of file schedule.h.
{ return nodes_.empty(); }
Referenced by v8::internal::compiler::InstructionBlockFor().
end() [1/2]
iterator v8::internal::compiler::BasicBlock::end () [inline]
Definition at line 101 of file schedule.h.
{ return nodes_.end(); }
Referenced by v8::internal::compiler::FindInsertionPoint(), v8::internal::compiler::GraphC1Visualizer::PrintSchedule(), v8::internal::compiler::anonymous_namespace{turbofan-graph-visualizer.cc}::PrintScheduledGraph(), and TrimNodes().
end() [2/2]
const_iterator v8::internal::compiler::BasicBlock::end () const [inline]
Definition at line 107 of file schedule.h.
{ return nodes_.end(); }
front() [1/2]
value_type& v8::internal::compiler::BasicBlock::front () [inline]
Definition at line 96 of file schedule.h.
{ return nodes_.front(); }
Referenced by v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::BlockKind(), v8::internal::compiler::InstructionBlockFor(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
front() [2/2]
value_type const& v8::internal::compiler::BasicBlock::front () const [inline]
Definition at line 97 of file schedule.h.
{ return nodes_.front(); }
GetCommonDominator()
BasicBlock * v8::internal::compiler::BasicBlock::GetCommonDominator (BasicBlock * b1, BasicBlock * b2) [static]
Definition at line 99 of file schedule.cc.
                                                                         {
  while (b1 != b2) {
    if (b1->dominator_depth() < b2->dominator_depth()) {
      b2 = b2->dominator();
    } else {
      b1 = b1->dominator();
    }
  }
  return b1;
}
References dominator(), and dominator_depth().
Referenced by v8::internal::compiler::Scheduler::PropagateImmediateDominators(), and v8::internal::compiler::ScheduleLateNodeVisitor::VisitNode().
id()
Id v8::internal::compiler::BasicBlock::id () const [inline]
Definition at line 62 of file schedule.h.
{ return id_; }
Referenced by v8::internal::compiler::Schedule::AddNode(), v8::internal::compiler::StringBuilderOptimizer::BlockShouldFinalizeStringBuilders(), v8::internal::compiler::CFGBuilder::BuildBlockForNode(), v8::internal::compiler::SpecialRPONumberer::ComputeAndInsertSpecialRPO(), v8::internal::compiler::SpecialRPONumberer::ComputeLoopInfo(), v8::internal::compiler::Scheduler::GetCommonDominator(), v8::internal::compiler::Scheduler::GetCommonDominatorIfCached(), v8::internal::compiler::StringBuilderOptimizer::GetStringBuildersToFinalize(), v8::internal::compiler::BasicBlockInstrumentor::Instrument(), v8::internal::compiler::ScheduleLateNodeVisitor::IsMarked(), v8::internal::compiler::RawMachineAssembler::MakeReschedulable(), v8::internal::compiler::ScheduleLateNodeVisitor::Mark(), v8::internal::compiler::Scheduler::MovePlannedNodes(), v8::internal::compiler::operator<<(), v8::internal::compiler::RawMachineAssembler::OptimizeControlFlow(), v8::internal::compiler::Schedule::PlanNode(), v8::internal::compiler::Scheduler::PropagateImmediateDominators(), v8::internal::compiler::ScheduleEarlyNodeVisitor::PropagateMinimumPositionToNode(), v8::internal::compiler::ScheduleVerifier::Run(), v8::internal::compiler::ScheduleLateNodeVisitor::ScheduleNode(), v8::internal::compiler::ScheduleLateNodeVisitor::SplitNode(), v8::internal::compiler::BasicBlockCallGraphProfiler::StoreCallGraph(), v8::internal::compiler::CFGBuilder::TraceConnect(), v8::internal::compiler::ScheduleEarlyNodeVisitor::VisitNode(), and v8::internal::compiler::ScheduleLateNodeVisitor::VisitNode().
InsertNodes()
template<class InputIterator >
void v8::internal::compiler::BasicBlock::InsertNodes (iterator insertion_point, InputIterator insertion_start, InputIterator insertion_end) [inline]
Definition at line 115 of file schedule.h.
                                                {
    nodes_.insert(insertion_point, insertion_start, insertion_end);
  }
Referenced by v8::internal::compiler::BasicBlockInstrumentor::Instrument().
IsLoopHeader()
bool v8::internal::compiler::BasicBlock::IsLoopHeader () const [inline]
Definition at line 167 of file schedule.h.
{ return loop_end_ != nullptr; }
Referenced by v8::internal::compiler::StringBuilderOptimizer::CheckPreviousNodeUses(), v8::internal::compiler::SpecialRPONumberer::ComputeAndInsertSpecialRPO(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::FixLoopPhis(), v8::internal::compiler::ScheduleLateNodeVisitor::GetHoistBlock(), v8::internal::compiler::GetLoopEndRpo(), v8::internal::compiler::StringBuilderOptimizer::IsLoopPhi(), v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::IsPhiContainingGivenInputs(), v8::internal::compiler::anonymous_namespace{turbofan-graph-visualizer.cc}::PrintScheduledGraph(), v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::ValidControlFlowForStringBuilder(), and v8::internal::compiler::StringBuilderOptimizer::VisitNode().
loop_depth()
int32_t v8::internal::compiler::BasicBlock::loop_depth () const [inline]
Definition at line 150 of file schedule.h.
{ return loop_depth_; }
Referenced by v8::internal::compiler::SpecialRPONumberer::ComputeAndInsertSpecialRPO(), v8::internal::compiler::GraphC1Visualizer::PrintSchedule(), v8::internal::compiler::anonymous_namespace{turbofan-graph-visualizer.cc}::PrintScheduledGraph(), set_loop_depth(), v8::internal::compiler::ScheduleLateNodeVisitor::SplitNode(), and v8::internal::compiler::ScheduleLateNodeVisitor::VisitNode().
loop_end()
BasicBlock* v8::internal::compiler::BasicBlock::loop_end () const [inline]
Definition at line 147 of file schedule.h.
{ return loop_end_; }
Referenced by v8::internal::compiler::SpecialRPONumberer::ComputeAndInsertSpecialRPO(), v8::internal::compiler::GetLoopEndRpo(), v8::internal::compiler::anonymous_namespace{turbofan-graph-visualizer.cc}::PrintScheduledGraph(), and set_loop_end().
loop_header()
BasicBlock* v8::internal::compiler::BasicBlock::loop_header () const [inline]
Definition at line 144 of file schedule.h.
{ return loop_header_; }
Referenced by v8::internal::compiler::SpecialRPONumberer::ComputeAndInsertSpecialRPO(), v8::internal::compiler::ScheduleLateNodeVisitor::GetHoistBlock(), v8::internal::compiler::InstructionBlockFor(), v8::internal::compiler::anonymous_namespace{turbofan-graph-visualizer.cc}::PrintScheduledGraph(), and set_loop_header().
loop_number()
int32_t v8::internal::compiler::BasicBlock::loop_number () const [inline]
Definition at line 153 of file schedule.h.
{ return loop_number_; }
Referenced by v8::internal::compiler::SpecialRPONumberer::ComputeAndInsertSpecialRPO(), v8::internal::compiler::SpecialRPONumberer::GetLoopNumber(), and v8::internal::compiler::SpecialRPONumberer::HasLoopNumber().
LoopContains()
bool v8::internal::compiler::BasicBlock::LoopContains (BasicBlock * block) const
Definition at line 39 of file schedule.cc.
                                                     {
  // RPO numbers must be initialized.
  DCHECK_LE(0, rpo_number_);
  DCHECK_LE(0, block->rpo_number_);
  if (loop_end_ == nullptr) return false; // This is not a loop.
  return block->rpo_number_ >= rpo_number_ &&
         block->rpo_number_ < loop_end_->rpo_number_;
}
References DCHECK_LE, loop_end_, and rpo_number_.
Referenced by v8::internal::compiler::StringBuilderOptimizer::CheckNodeUses(), v8::internal::compiler::StringBuilderOptimizer::FinalizeStringBuilders(), v8::internal::compiler::StringBuilderOptimizer::LoopContains(), v8::internal::compiler::RawMachineAssembler::MakeReschedulable(), v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::ValidControlFlowForStringBuilder(), and v8::internal::compiler::StringBuilderOptimizer::VisitNode().
NodeAt()
Node* v8::internal::compiler::BasicBlock::NodeAt (size_t index) [inline]
Definition at line 93 of file schedule.h.
{ return nodes_[index]; }
References v8::internal::index.
Referenced by v8::internal::compiler::Schedule::EliminateRedundantPhiNodes(), v8::internal::compiler::HasDominatingDef(), v8::internal::compiler::Schedule::MovePhis(), v8::internal::compiler::RawMachineAssembler::OptimizeControlFlow(), and v8::internal::compiler::ScheduleVerifier::Run().
NodeCount()
size_t v8::internal::compiler::BasicBlock::NodeCount () const [inline]
Definition at line 94 of file schedule.h.
{ return nodes_.size(); }
Referenced by v8::internal::compiler::CheckInputsDominate(), v8::internal::compiler::Schedule::EliminateRedundantPhiNodes(), v8::internal::compiler::HasDominatingDef(), v8::internal::compiler::Schedule::MovePhis(), v8::internal::compiler::RawMachineAssembler::OptimizeControlFlow(), and v8::internal::compiler::ScheduleVerifier::Run().
nodes()
NodeVector* v8::internal::compiler::BasicBlock::nodes () [inline]
Definition at line 159 of file schedule.h.
{ return &nodes_; }
Referenced by v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::ComesBeforeInBlock(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::FixLoopPhis().
operator=()
BasicBlock& v8::internal::compiler::BasicBlock::operator= (const BasicBlock &) [delete]
PredecessorAt()
BasicBlock* v8::internal::compiler::BasicBlock::PredecessorAt (size_t index) [inline]
Definition at line 76 of file schedule.h.
{ return predecessors_[index]; }
References v8::internal::index.
Referenced by v8::internal::compiler::CheckInputsDominate(), v8::internal::compiler::SpecialRPONumberer::ComputeLoopInfo(), v8::internal::compiler::RawMachineAssembler::MakeReschedulable(), v8::internal::compiler::RawMachineAssembler::OptimizeControlFlow(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
PredecessorCount()
size_t v8::internal::compiler::BasicBlock::PredecessorCount () const [inline]
Definition at line 75 of file schedule.h.
{ return predecessors_.size(); }
Referenced by v8::internal::compiler::SpecialRPONumberer::ComputeLoopInfo(), v8::internal::compiler::Schedule::EliminateRedundantPhiNodes(), v8::internal::compiler::Schedule::EnsureCFGWellFormedness(), v8::internal::compiler::Schedule::EnsureSplitEdgeForm(), v8::internal::compiler::InstructionBlockFor(), v8::internal::compiler::RawMachineAssembler::MakeReschedulable(), v8::internal::compiler::operator<<(), v8::internal::compiler::RawMachineAssembler::OptimizeControlFlow(), and v8::internal::compiler::Schedule::PropagateDeferredMark().
predecessors() [1/2]
BasicBlockVector& v8::internal::compiler::BasicBlock::predecessors () [inline]
Definition at line 73 of file schedule.h.
{ return predecessors_; }
Referenced by v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::ComputePredecessors(), v8::internal::compiler::Schedule::EnsureSplitEdgeForm(), v8::internal::compiler::InstructionBlockFor(), v8::internal::compiler::ScheduleLateNodeVisitor::MarkBlock(), v8::internal::compiler::Schedule::MoveSuccessors(), v8::internal::compiler::operator<<(), v8::internal::compiler::GraphC1Visualizer::PrintSchedule(), v8::internal::compiler::anonymous_namespace{turbofan-graph-visualizer.cc}::PrintScheduledGraph(), v8::internal::compiler::Schedule::PropagateDeferredMark(), v8::internal::compiler::Scheduler::PropagateImmediateDominators(), and v8::internal::compiler::ScheduleVerifier::Run().
predecessors() [2/2]
const BasicBlockVector& v8::internal::compiler::BasicBlock::predecessors () const [inline]
Definition at line 74 of file schedule.h.
{ return predecessors_; }
Print()
void v8::internal::compiler::BasicBlock::Print ()
Definition at line 110 of file schedule.cc.
{ StdoutStream{} << *this << "\n"; }
rbegin()
reverse_iterator v8::internal::compiler::BasicBlock::rbegin () [inline]
Definition at line 110 of file schedule.h.
{ return nodes_.rbegin(); }
RemoveNode()
void v8::internal::compiler::BasicBlock::RemoveNode (iterator it) [inline]
Definition at line 103 of file schedule.h.
{ nodes_.erase(it); }
Referenced by v8::internal::compiler::Schedule::EliminateRedundantPhiNodes(), v8::internal::compiler::Schedule::MovePhis(), and v8::internal::compiler::RawMachineAssembler::OptimizeControlFlow().
RemovePredecessor()
void v8::internal::compiler::BasicBlock::RemovePredecessor (size_t index)
Definition at line 56 of file schedule.cc.
                                               {
  predecessors_.erase(predecessors_.begin() + index);
}
References v8::internal::ZoneVector< T >::begin(), v8::internal::ZoneVector< T >::erase(), v8::internal::index, and predecessors_.
rend()
reverse_iterator v8::internal::compiler::BasicBlock::rend () [inline]
Definition at line 111 of file schedule.h.
{ return nodes_.rend(); }
ResetRPOInfo()
void v8::internal::compiler::BasicBlock::ResetRPOInfo ()
Definition at line 87 of file schedule.cc.
                              {
  loop_number_ = -1;
  rpo_number_ = -1;
  dominator_depth_ = -1;
  dominator_ = nullptr;
  rpo_next_ = nullptr;
  loop_header_ = nullptr;
  loop_end_ = nullptr;
  loop_depth_ = 0;
}
References dominator_, dominator_depth_, loop_depth_, loop_end_, loop_header_, loop_number_, rpo_next_, and rpo_number_.
rpo_next()
BasicBlock* v8::internal::compiler::BasicBlock::rpo_next () const [inline]
Definition at line 141 of file schedule.h.
{ return rpo_next_; }
Referenced by v8::internal::compiler::SpecialRPONumberer::ComputeAndInsertSpecialRPO(), v8::internal::compiler::Scheduler::FuseFloatingControl(), v8::internal::compiler::Scheduler::GenerateDominatorTree(), v8::internal::compiler::Scheduler::PropagateImmediateDominators(), and v8::internal::compiler::SpecialRPONumberer::SerializeRPOIntoSchedule().
rpo_number()
int32_t v8::internal::compiler::BasicBlock::rpo_number () const [inline]
Definition at line 156 of file schedule.h.
{ return rpo_number_; }
Referenced by v8::internal::compiler::CheckInputsDominate(), v8::internal::compiler::SpecialRPONumberer::ComputeAndInsertSpecialRPO(), v8::internal::compiler::GetLoopEndRpo(), v8::internal::compiler::GetRpo(), v8::internal::compiler::BasicBlockInstrumentor::Instrument(), v8::internal::compiler::RawMachineAssembler::MakeReschedulable(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Map(), v8::internal::compiler::GraphC1Visualizer::PrintSchedule(), v8::internal::compiler::anonymous_namespace{turbofan-graph-visualizer.cc}::PrintScheduledGraph(), v8::internal::compiler::Schedule::PropagateDeferredMark(), v8::internal::compiler::SpecialRPONumberer::Push(), v8::internal::compiler::ScheduleVerifier::Run(), set_rpo_number(), v8::internal::compiler::BasicBlockCallGraphProfiler::StoreCallGraph(), and v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::ValidControlFlowForStringBuilder().
set_control()
void v8::internal::compiler::BasicBlock::set_control (Control control)
Definition at line 62 of file schedule.cc.
{ control_ = control; }
References control(), and control_.
Referenced by v8::internal::compiler::Schedule::AddBranch(), v8::internal::compiler::Schedule::AddCall(), v8::internal::compiler::Schedule::AddDeoptimize(), v8::internal::compiler::Schedule::AddGoto(), v8::internal::compiler::Schedule::AddReturn(), v8::internal::compiler::Schedule::AddSwitch(), v8::internal::compiler::Schedule::AddTailCall(), v8::internal::compiler::Schedule::AddThrow(), v8::internal::compiler::Schedule::InsertBranch(), v8::internal::compiler::Schedule::InsertSwitch(), and v8::internal::compiler::RawMachineAssembler::OptimizeControlFlow().
set_control_input()
void v8::internal::compiler::BasicBlock::set_control_input (Node * control_input)
Definition at line 64 of file schedule.cc.
                                                      {
  if (!nodes_.empty() && control_input == nodes_.back()) {
    nodes_.pop_back();
  }
  control_input_ = control_input;
}
References v8::internal::ZoneVector< T >::back(), control_input(), control_input_, v8::internal::ZoneVector< T >::empty(), nodes_, and v8::internal::ZoneVector< T >::pop_back().
Referenced by v8::internal::compiler::RawMachineAssembler::OptimizeControlFlow(), and v8::internal::compiler::Schedule::SetControlInput().
set_deferred()
void v8::internal::compiler::BasicBlock::set_deferred (bool deferred) [inline]
Definition at line 133 of file schedule.h.
{ deferred_ = deferred; }
Referenced by v8::internal::compiler::RawMachineAssembler::Bind(), v8::internal::compiler::CFGBuilder::ConnectBranch(), v8::internal::compiler::CFGBuilder::ConnectCall(), v8::internal::compiler::CFGBuilder::ConnectSwitch(), v8::internal::compiler::RawMachineAssembler::OptimizeControlFlow(), v8::internal::compiler::Schedule::PropagateDeferredMark(), and v8::internal::compiler::Scheduler::PropagateImmediateDominators().
set_dominator()
void v8::internal::compiler::BasicBlock::set_dominator (BasicBlock * dominator) [inline]
Definition at line 139 of file schedule.h.
{ dominator_ = dominator; }
Referenced by v8::internal::compiler::Scheduler::PropagateImmediateDominators().
set_dominator_depth()
void v8::internal::compiler::BasicBlock::set_dominator_depth (int32_t depth) [inline]
Definition at line 136 of file schedule.h.
{ dominator_depth_ = depth; }
Referenced by v8::internal::compiler::Scheduler::GenerateDominatorTree(), and v8::internal::compiler::Scheduler::PropagateImmediateDominators().
set_loop_depth()
void v8::internal::compiler::BasicBlock::set_loop_depth (int32_t loop_depth)
Definition at line 71 of file schedule.cc.
                                                  {
  loop_depth_ = loop_depth;
}
References loop_depth(), and loop_depth_.
Referenced by v8::internal::compiler::SpecialRPONumberer::ComputeAndInsertSpecialRPO().
set_loop_end()
void v8::internal::compiler::BasicBlock::set_loop_end (BasicBlock * loop_end)
Definition at line 79 of file schedule.cc.
{ loop_end_ = loop_end; }
References loop_end(), and loop_end_.
Referenced by v8::internal::compiler::SpecialRPONumberer::ComputeAndInsertSpecialRPO().
set_loop_header()
void v8::internal::compiler::BasicBlock::set_loop_header (BasicBlock * loop_header)
Definition at line 81 of file schedule.cc.
                                                        {
  loop_header_ = loop_header;
}
References loop_header(), and loop_header_.
Referenced by v8::internal::compiler::SpecialRPONumberer::ComputeAndInsertSpecialRPO().
set_loop_number()
void v8::internal::compiler::BasicBlock::set_loop_number (int32_t loop_number) [inline]
Definition at line 154 of file schedule.h.
{ loop_number_ = loop_number; }
Referenced by v8::internal::compiler::SpecialRPONumberer::SetLoopNumber().
set_rpo_next()
void v8::internal::compiler::BasicBlock::set_rpo_next (BasicBlock * rpo_next) [inline]
Definition at line 142 of file schedule.h.
{ rpo_next_ = rpo_next; }
Referenced by v8::internal::compiler::SpecialRPONumberer::PushFront().
set_rpo_number()
void v8::internal::compiler::BasicBlock::set_rpo_number (int32_t rpo_number)
Definition at line 75 of file schedule.cc.
                                                  {
  rpo_number_ = rpo_number;
}
References rpo_number(), and rpo_number_.
Referenced by v8::internal::compiler::SpecialRPONumberer::ComputeAndInsertSpecialRPO(), v8::internal::compiler::SpecialRPONumberer::Push(), and v8::internal::compiler::SpecialRPONumberer::SerializeRPOIntoSchedule().
size()
size_t v8::internal::compiler::BasicBlock::size () const [inline]
Definition at line 92 of file schedule.h.
{ return nodes_.size(); }
SuccessorAt()
BasicBlock* v8::internal::compiler::BasicBlock::SuccessorAt (size_t index) [inline]
Definition at line 85 of file schedule.h.
{ return successors_[index]; }
References v8::internal::index.
Referenced by v8::internal::compiler::SpecialRPONumberer::ComputeAndInsertSpecialRPO(), v8::internal::compiler::SpecialRPONumberer::ComputeLoopInfo(), v8::internal::compiler::RawMachineAssembler::OptimizeControlFlow(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), and v8::internal::compiler::ScheduleVerifier::Run().
SuccessorCount()
size_t v8::internal::compiler::BasicBlock::SuccessorCount () const [inline]
Definition at line 84 of file schedule.h.
{ return successors_.size(); }
Referenced by v8::internal::compiler::SpecialRPONumberer::ComputeAndInsertSpecialRPO(), v8::internal::compiler::SpecialRPONumberer::ComputeSpecialRPO(), v8::internal::compiler::Schedule::EnsureSplitEdgeForm(), v8::internal::compiler::InstructionBlockFor(), v8::internal::compiler::RawMachineAssembler::OptimizeControlFlow(), v8::internal::compiler::anonymous_namespace{turbofan-graph-visualizer.cc}::PrintScheduledGraph(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::ScheduleVerifier::Run(), and v8::internal::compiler::ScheduleLateNodeVisitor::SplitNode().
successors() [1/2]
BasicBlockVector& v8::internal::compiler::BasicBlock::successors () [inline]
Definition at line 82 of file schedule.h.
{ return successors_; }
Referenced by v8::internal::compiler::StringBuilderOptimizer::FinalizeStringBuilders(), v8::internal::compiler::InstructionBlockFor(), v8::internal::compiler::BasicBlockInstrumentor::Instrument(), v8::internal::compiler::Schedule::MoveSuccessors(), v8::internal::compiler::operator<<(), v8::internal::compiler::GraphC1Visualizer::PrintSchedule(), v8::internal::compiler::anonymous_namespace{turbofan-graph-visualizer.cc}::PrintScheduledGraph(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::ScheduleVerifier::Run(), and v8::internal::compiler::ScheduleLateNodeVisitor::SplitNode().
successors() [2/2]
const BasicBlockVector& v8::internal::compiler::BasicBlock::successors () const [inline]
Definition at line 83 of file schedule.h.
{ return successors_; }
TrimNodes()
void v8::internal::compiler::BasicBlock::TrimNodes (iterator new_end)
Definition at line 85 of file schedule.cc.
{ nodes_.erase(new_end, end()); }
References end(), v8::internal::ZoneVector< T >::erase(), and nodes_.
Member Data Documentation
control_
Control v8::internal::compiler::BasicBlock::control_ [private]
Definition at line 187 of file schedule.h.
Referenced by set_control().
control_input_
Node* v8::internal::compiler::BasicBlock::control_input_ [private]
Definition at line 188 of file schedule.h.
Referenced by set_control_input().
deferred_
bool v8::internal::compiler::BasicBlock::deferred_ [private]
Definition at line 177 of file schedule.h.
dominator_
BasicBlock* v8::internal::compiler::BasicBlock::dominator_ [private]
Definition at line 179 of file schedule.h.
Referenced by ResetRPOInfo().
dominator_depth_
int32_t v8::internal::compiler::BasicBlock::dominator_depth_ [private]
Definition at line 178 of file schedule.h.
Referenced by ResetRPOInfo().
id_
Id v8::internal::compiler::BasicBlock::id_ [private]
Definition at line 199 of file schedule.h.
loop_depth_
int32_t v8::internal::compiler::BasicBlock::loop_depth_ [private]
Definition at line 185 of file schedule.h.
Referenced by ResetRPOInfo(), and set_loop_depth().
loop_end_
BasicBlock* v8::internal::compiler::BasicBlock::loop_end_ [private]
Definition at line 184 of file schedule.h.
Referenced by LoopContains(), ResetRPOInfo(), and set_loop_end().
loop_header_
BasicBlock* v8::internal::compiler::BasicBlock::loop_header_ [private]
Definition at line 181 of file schedule.h.
Referenced by ResetRPOInfo(), and set_loop_header().
loop_number_
int32_t v8::internal::compiler::BasicBlock::loop_number_ [private]
Definition at line 175 of file schedule.h.
Referenced by ResetRPOInfo().
nodes_
NodeVector v8::internal::compiler::BasicBlock::nodes_ [private]
Definition at line 189 of file schedule.h.
Referenced by AddNode(), set_control_input(), and TrimNodes().
predecessors_
BasicBlockVector v8::internal::compiler::BasicBlock::predecessors_ [private]
Definition at line 192 of file schedule.h.
Referenced by AddPredecessor(), and RemovePredecessor().
rpo_next_
BasicBlock* v8::internal::compiler::BasicBlock::rpo_next_ [private]
Definition at line 180 of file schedule.h.
Referenced by ResetRPOInfo().
rpo_number_
int32_t v8::internal::compiler::BasicBlock::rpo_number_ [private]
Definition at line 176 of file schedule.h.
Referenced by LoopContains(), ResetRPOInfo(), and set_rpo_number().
successors_
BasicBlockVector v8::internal::compiler::BasicBlock::successors_ [private]
Definition at line 191 of file schedule.h.
Referenced by AddSuccessor().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/schedule.h
/mnt/V8SourceCode/src/compiler/schedule.cc