v8::internal::BitVector Class Reference
#include <bit-vector.h>
Classes
union DataStorage
class Iterator
Public Member Functions
BitVector ()=default
BitVector (int length, Zone *zone)
BitVector (const BitVector &other, Zone *zone)
BitVector (const BitVector &)=delete
BitVector & operator= (const BitVector &)=delete
BitVector (BitVector &&other) V8_NOEXCEPT
BitVector & operator= (BitVector &&other) V8_NOEXCEPT
void CopyFrom (const BitVector &other)
void Resize (int new_length, Zone *zone)
bool Contains (int i) const
void Add (int i)
void AddAll ()
void Remove (int i)
void Union (const BitVector &other)
bool UnionIsChanged (const BitVector &other)
void Intersect (const BitVector &other)
bool IntersectIsChanged (const BitVector &other)
void Subtract (const BitVector &other)
void Clear ()
bool IsEmpty () const
bool Equals (const BitVector &other) const
int Count () const
int length () const
Iterator begin () const
Iterator end () const
Static Public Attributes
static constexpr int kDataBits = kBitsPerSystemPointer
static constexpr int kDataBitShift = kBitsPerSystemPointerLog2
Private Member Functions
bool is_inline () const
int data_length () const
Static Private Member Functions
static int word (int index)
static uintptr_t bit (int index)
Private Attributes
int length_ = 0
DataStorage data_ {0}
uintptr_t * data_begin_ = &data_.inline_
uintptr_t * data_end_ = &data_.inline_ + 1
Detailed Description
Definition at line 16 of file bit-vector.h.
Constructor & Destructor Documentation
BitVector() [1/5]
v8::internal::BitVector::BitVector () [default]
BitVector() [2/5]
v8::internal::BitVector::BitVector (int length, Zone * zone) [inline]
Definition at line 109 of file bit-vector.h.
                                    : length_(length) {
    DCHECK_LE(0, length);
    int data_length = (length + kDataBits - 1) >> kDataBitShift;
    if (data_length > 1) {
      data_.ptr_ = zone->AllocateArray<uintptr_t>(data_length);
      std::fill_n(data_.ptr_, data_length, 0);
      data_begin_ = data_.ptr_;
      data_end_ = data_begin_ + data_length;
    }
  }
References v8::internal::Zone::AllocateArray(), DCHECK_LE, and v8::internal::length.
BitVector() [3/5]
v8::internal::BitVector::BitVector (const BitVector & other, Zone * zone) [inline]
Definition at line 120 of file bit-vector.h.
      : length_(other.length_), data_(other.data_.inline_) {
    if (!other.is_inline()) {
      int data_length = other.data_length();
      DCHECK_LT(1, data_length);
      data_.ptr_ = zone->AllocateArray<uintptr_t>(data_length);
      data_begin_ = data_.ptr_;
      data_end_ = data_begin_ + data_length;
      std::copy_n(other.data_begin_, data_length, data_begin_);
    }
  }
References v8::internal::Zone::AllocateArray(), data_begin_, data_length(), DCHECK_LT, and is_inline().
BitVector() [4/5]
v8::internal::BitVector::BitVector (const BitVector &) [delete]
BitVector() [5/5]
v8::internal::BitVector::BitVector (BitVector && other) [inline]
Definition at line 136 of file bit-vector.h.
{ *this = std::move(other); }
Member Function Documentation
Add()
void v8::internal::BitVector::Add (int i) [inline]
Definition at line 185 of file bit-vector.h.
                  {
    DCHECK(i >= 0 && i < length());
    data_begin_[word(i)] |= bit(i);
  }
References v8::internal::DCHECK(), and v8::internal::length.
Referenced by v8::internal::GrowableBitVector::Add(), v8::internal::compiler::BytecodeLoopAssignments::Add(), v8::internal::compiler::BytecodeLoopAssignments::AddList(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::AnalyzeLoopAssignment(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::CloneAndInlineBlock(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::CloneBlockAndGoto(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::CloneSubGraph(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::CreateMergeSnapshot(), v8::internal::compiler::LoopPeeler::EliminateLoopExits(), v8::internal::baseline::BaselineCompiler::EnsureLabel(), v8::internal::compiler::PrepareUsesVisitor::InitializePlacement(), v8::internal::compiler::ScheduleLateNodeVisitor::Mark(), v8::internal::compiler::AllNodes::Mark(), v8::internal::compiler::BytecodeLivenessState::MarkAccumulatorLive(), v8::internal::compiler::RegisterAllocationData::MarkAllocated(), v8::internal::compiler::InstructionSelector::MarkAsDefined(), v8::internal::compiler::InstructionSelector::MarkAsUsed(), v8::internal::compiler::RegisterAllocationData::MarkFixedUse(), v8::internal::baseline::BaselineCompiler::MarkIndirectJumpTarget(), v8::internal::compiler::BytecodeLivenessState::MarkRegisterLive(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessBranchOnTarget(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::RefineTypeKnowledge(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::RefineTypeKnowledgeNotNull(), v8::internal::compiler::ScheduleVerifier::Run(), v8::internal::compiler::Deduplicator::SeenBefore(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::StartNewSnapshotFor(), and v8::internal::compiler::InstructionSequence::ValidateSSA().
AddAll()
void v8::internal::BitVector::AddAll () [inline]
Definition at line 190 of file bit-vector.h.
                {
    // TODO(leszeks): This sets bits outside of the length of this bit-vector,
    // which is observable if we resize it or copy from it. If this is a
    // problem, we should clear the high bits either on add, or on resize/copy.
    memset(data_begin_, -1, sizeof(*data_begin_) * data_length());
  }
Referenced by v8::internal::compiler::BytecodeLivenessState::MarkAllLive().
begin()
Iterator v8::internal::BitVector::begin () const [inline]
Definition at line 259 of file bit-vector.h.
{ return Iterator(this, Iterator::kStartTag); }
Referenced by v8::internal::GrowableBitVector::begin(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::PopControl().
bit()
static uintptr_t v8::internal::BitVector::bit (int index) [inline], [static], [private]
Definition at line 282 of file bit-vector.h.
                                            {
    return uintptr_t{1} << (index & (kDataBits - 1));
  }
References v8::internal::index.
Clear()
void v8::internal::BitVector::Clear () [inline]
Definition at line 245 of file bit-vector.h.
{ std::fill_n(data_begin_, data_length(), 0); }
Referenced by v8::internal::GrowableBitVector::Clear(), and v8::internal::compiler::ScheduleLateNodeVisitor::SplitNode().
Contains()
bool v8::internal::BitVector::Contains (int i) const [inline]
Definition at line 180 of file bit-vector.h.
                             {
    DCHECK(i >= 0 && i < length());
    return (data_begin_[word(i)] & bit(i)) != 0;
  }
References v8::internal::DCHECK(), and v8::internal::length.
Referenced by v8::internal::compiler::BytecodeLivenessState::AccumulatorIsLive(), v8::internal::maglev::MaglevGraphBuilder::BuildBody(), v8::internal::maglev::MaglevGraphBuilder::BuildMergeStates(), v8::internal::compiler::SpecialRPONumberer::ComputeAndInsertSpecialRPO(), v8::internal::GrowableBitVector::Contains(), v8::internal::compiler::BytecodeLoopAssignments::ContainsLocal(), v8::internal::compiler::BytecodeLoopAssignments::ContainsParameter(), v8::internal::compiler::LoopPeeler::EliminateLoopExits(), v8::internal::baseline::BaselineCompiler::EnsureLabel(), v8::internal::compiler::RegisterAllocationData::HasFixedUse(), v8::internal::compiler::InstructionSelector::IsDefined(), v8::internal::baseline::BaselineCompiler::IsIndirectJumpTarget(), v8::internal::baseline::BaselineCompiler::IsJumpTarget(), v8::internal::compiler::ScheduleLateNodeVisitor::IsMarked(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::IsReachable(), v8::internal::compiler::AllNodes::IsReachable(), v8::internal::compiler::InstructionSelector::IsReallyUsed(), v8::internal::compiler::InstructionSelector::IsUsed(), v8::internal::wasm::TurboshaftGraphBuildingInterface::Loop(), v8::internal::compiler::AllNodes::Mark(), v8::internal::compiler::BytecodeLivenessState::RegisterIsLive(), v8::internal::compiler::ScheduleVerifier::Run(), v8::internal::compiler::Deduplicator::SeenBefore(), v8::internal::compiler::InstructionSequence::ValidateSSA(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitBlock(), v8::internal::compiler::PrepareUsesVisitor::Visited(), and v8::internal::maglev::MaglevGraphBuilder::VisitSingleBytecode().
CopyFrom()
void v8::internal::BitVector::CopyFrom (const BitVector & other) [inline]
Definition at line 155 of file bit-vector.h.
                                        {
    DCHECK_EQ(other.length(), length());
    DCHECK_EQ(is_inline(), other.is_inline());
    std::copy_n(other.data_begin_, data_length(), data_begin_);
  }
References data_begin_, DCHECK_EQ, is_inline(), v8::internal::length, and length().
Referenced by v8::internal::compiler::BytecodeLivenessState::CopyFrom(), and v8::internal::compiler::ScheduleVerifier::Run().
Count()
int v8::internal::BitVector::Count () const
Definition at line 30 of file bit-vector.cc.
                           {
  auto accumulate_popcnt = [](int cnt, uintptr_t word) -> int {
    return cnt + base::bits::CountPopulation(word);
  };
  return std::accumulate(data_begin_, data_end_, 0, accumulate_popcnt);
}
References v8::base::bits::CountPopulation(), data_begin_, data_end_, and word().
Referenced by v8::internal::compiler::BytecodeLivenessState::live_value_count().
data_length()
int v8::internal::BitVector::data_length () const [inline], [private]
Definition at line 276 of file bit-vector.h.
{ return static_cast<int>(data_end_ - data_begin_); }
Referenced by BitVector().
end()
Iterator v8::internal::BitVector::end () const [inline]
Definition at line 261 of file bit-vector.h.
{ return Iterator(this, Iterator::kEndTag); }
Referenced by v8::internal::GrowableBitVector::end(), v8::internal::compiler::BytecodeLivenessState::Iterator::Iterator(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::PopControl().
Equals()
bool v8::internal::BitVector::Equals (const BitVector & other) const [inline]
Definition at line 251 of file bit-vector.h.
                                            {
    return std::equal(data_begin_, data_end_, other.data_begin_);
  }
References data_begin_, and v8::internal::equal.
Referenced by v8::internal::compiler::BytecodeLivenessState::Equals(), and v8::internal::GrowableBitVector::Equals().
Intersect()
void v8::internal::BitVector::Intersect (const BitVector & other) [inline]
Definition at line 220 of file bit-vector.h.
                                         {
    DCHECK(other.length() == length());
    for (int i = 0; i < data_length(); i++) {
      data_begin_[i] &= other.data_begin_[i];
    }
  }
References data_begin_, v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::length, and length().
IntersectIsChanged()
bool v8::internal::BitVector::IntersectIsChanged (const BitVector & other) [inline]
Definition at line 227 of file bit-vector.h.
                                                  {
    DCHECK(other.length() == length());
    bool changed = false;
    for (int i = 0; i < data_length(); i++) {
      uintptr_t old_data = data_begin_[i];
      data_begin_[i] &= other.data_begin_[i];
      if (data_begin_[i] != old_data) changed = true;
    }
    return changed;
  }
References data_begin_, v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::length, and length().
Referenced by v8::internal::compiler::ScheduleVerifier::Run().
is_inline()
bool v8::internal::BitVector::is_inline () const [inline], [private]
Definition at line 275 of file bit-vector.h.
{ return data_begin_ == &data_.inline_; }
Referenced by BitVector(), and CopyFrom().
IsEmpty()
bool v8::internal::BitVector::IsEmpty () const [inline]
Definition at line 247 of file bit-vector.h.
                       {
    return std::all_of(data_begin_, data_end_, std::logical_not<uintptr_t>{});
  }
References v8::base::all_of().
Referenced by v8::internal::GrowableBitVector::IsEmpty().
length()
int v8::internal::BitVector::length () const [inline]
Definition at line 257 of file bit-vector.h.
{ return length_; }
Referenced by CopyFrom(), v8::internal::GrowableBitVector::InBitsRange(), Intersect(), IntersectIsChanged(), v8::internal::compiler::AllNodes::IsReachable(), v8::internal::GrowableBitVector::length(), v8::internal::compiler::BytecodeLivenessState::MarkRegisterDead(), v8::internal::compiler::BytecodeLivenessState::MarkRegisterLive(), v8::internal::compiler::BytecodeLivenessState::register_count(), v8::internal::compiler::BytecodeLivenessState::RegisterIsLive(), v8::internal::compiler::Deduplicator::SeenBefore(), v8::internal::compiler::ScheduleLateNodeVisitor::SplitNode(), Subtract(), Union(), and UnionIsChanged().
operator=() [1/2]
BitVector& v8::internal::BitVector::operator= (BitVector && other) [inline]
Definition at line 138 of file bit-vector.h.
                                                      {
    length_ = other.length_;
    data_ = other.data_;
    if (other.is_inline()) {
      data_begin_ = &data_.inline_;
      data_end_ = data_begin_ + other.data_length();
    } else {
      data_begin_ = other.data_begin_;
      data_end_ = other.data_end_;
      // Reset other to inline.
      other.length_ = 0;
      other.data_begin_ = &other.data_.inline_;
      other.data_end_ = other.data_begin_ + 1;
    }
    return *this;
  }
operator=() [2/2]
BitVector& v8::internal::BitVector::operator= (const BitVector &) [delete]
Remove()
void v8::internal::BitVector::Remove (int i) [inline]
Definition at line 197 of file bit-vector.h.
                     {
    DCHECK(i >= 0 && i < length());
    data_begin_[word(i)] &= ~bit(i);
  }
References v8::internal::DCHECK(), and v8::internal::length.
Referenced by v8::internal::compiler::BytecodeLivenessState::MarkAccumulatorDead(), v8::internal::compiler::BytecodeLivenessState::MarkRegisterDead(), v8::internal::compiler::ScheduleVerifier::Run(), and v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::StartNewSnapshotFor().
Resize()
void v8::internal::BitVector::Resize (int new_length, Zone * zone) [inline]
Definition at line 161 of file bit-vector.h.
                                          {
    DCHECK_GT(new_length, length());
    int old_data_length = data_length();
    DCHECK_LE(1, old_data_length);
    int new_data_length = (new_length + kDataBits - 1) >> kDataBitShift;
    if (new_data_length > old_data_length) {
      uintptr_t* new_data = zone->AllocateArray<uintptr_t>(new_data_length);
      // Copy over the data.
      std::copy_n(data_begin_, old_data_length, new_data);
      // Zero out the rest of the data.
      std::fill(new_data + old_data_length, new_data + new_data_length, 0);
      data_begin_ = new_data;
      data_end_ = new_data + new_data_length;
    }
    length_ = new_length;
  }
References v8::internal::Zone::AllocateArray(), DCHECK_GT, DCHECK_LE, and v8::internal::length.
Referenced by v8::internal::GrowableBitVector::Grow(), v8::internal::compiler::Deduplicator::SeenBefore(), and v8::internal::compiler::ScheduleLateNodeVisitor::SplitNode().
Subtract()
void v8::internal::BitVector::Subtract (const BitVector & other) [inline]
Definition at line 238 of file bit-vector.h.
                                        {
    DCHECK(other.length() == length());
    for (int i = 0; i < data_length(); i++) {
      data_begin_[i] &= ~other.data_begin_[i];
    }
  }
References data_begin_, v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::length, and length().
Union()
void v8::internal::BitVector::Union (const BitVector & other) [inline]
Definition at line 202 of file bit-vector.h.
                                     {
    DCHECK_EQ(other.length(), length());
    for (int i = 0; i < data_length(); i++) {
      data_begin_[i] |= other.data_begin_[i];
    }
  }
References data_begin_, DCHECK_EQ, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::length, and length().
Referenced by v8::internal::compiler::BytecodeLivenessState::Union(), and v8::internal::compiler::BytecodeLoopAssignments::Union().
UnionIsChanged()
bool v8::internal::BitVector::UnionIsChanged (const BitVector & other) [inline]
Definition at line 209 of file bit-vector.h.
                                              {
    DCHECK(other.length() == length());
    bool changed = false;
    for (int i = 0; i < data_length(); i++) {
      uintptr_t old_data = data_begin_[i];
      data_begin_[i] |= other.data_begin_[i];
      if (data_begin_[i] != old_data) changed = true;
    }
    return changed;
  }
References data_begin_, v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::length, and length().
Referenced by v8::internal::compiler::BytecodeLivenessState::UnionIsChanged().
word()
static int v8::internal::BitVector::word (int index) [inline], [static], [private]
Definition at line 278 of file bit-vector.h.
                                       {
    V8_ASSUME(index >= 0);
    return index >> kDataBitShift;
  }
References v8::internal::index, and V8_ASSUME.
Referenced by Count().
Member Data Documentation
data_
DataStorage v8::internal::BitVector::data_ {0} [private]
Definition at line 287 of file bit-vector.h.
data_begin_
uintptr_t* v8::internal::BitVector::data_begin_ = &data_.inline_ [private]
Definition at line 288 of file bit-vector.h.
Referenced by BitVector(), CopyFrom(), Count(), Equals(), Intersect(), IntersectIsChanged(), Subtract(), Union(), and UnionIsChanged().
data_end_
uintptr_t* v8::internal::BitVector::data_end_ = &data_.inline_ + 1 [private]
Definition at line 289 of file bit-vector.h.
Referenced by Count().
kDataBits
constexpr int v8::internal::BitVector::kDataBits = kBitsPerSystemPointer [static], [constexpr]
Definition at line 104 of file bit-vector.h.
kDataBitShift
constexpr int v8::internal::BitVector::kDataBitShift = kBitsPerSystemPointerLog2 [static], [constexpr]
Definition at line 105 of file bit-vector.h.
length_
int v8::internal::BitVector::length_ = 0 [private]
Definition at line 286 of file bit-vector.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/utils/bit-vector.h
/mnt/V8SourceCode/src/utils/bit-vector.cc