cppgc::internal::HeapBase Class Reference
#include <heap-base.h>
Public Types
using StackSupport = cppgc::Heap::StackSupport
using MarkingType = cppgc::Heap::MarkingType
using SweepingType = cppgc::Heap::SweepingType
Public Member Functions
HeapBase (std::shared_ptr< cppgc::Platform > platform, const std::vector< std::unique_ptr< CustomSpaceBase >> &custom_spaces, StackSupport stack_support, MarkingType marking_support, SweepingType sweeping_support, GarbageCollector &garbage_collector)
virtual ~HeapBase ()
HeapBase (const HeapBase &)=delete
HeapBase & operator= (const HeapBase &)=delete
RawHeap & raw_heap ()
const RawHeap & raw_heap () const
cppgc::Platform * platform ()
const cppgc::Platform * platform () const
FatalOutOfMemoryHandler & oom_handler ()
const FatalOutOfMemoryHandler & oom_handler () const
PageBackend * page_backend ()
const PageBackend * page_backend () const
StatsCollector * stats_collector ()
const StatsCollector * stats_collector () const
PreFinalizerHandler * prefinalizer_handler ()
const PreFinalizerHandler * prefinalizer_handler () const
MarkerBase * marker () const
std::unique_ptr< MarkerBase > & GetMarkerRefForTesting ()
Compactor & compactor ()
ObjectAllocator & object_allocator ()
const ObjectAllocator & object_allocator () const
Sweeper & sweeper ()
const Sweeper & sweeper () const
PersistentRegion & GetStrongPersistentRegion ()
const PersistentRegion & GetStrongPersistentRegion () const
PersistentRegion & GetWeakPersistentRegion ()
const PersistentRegion & GetWeakPersistentRegion () const
CrossThreadPersistentRegion & GetStrongCrossThreadPersistentRegion ()
const CrossThreadPersistentRegion & GetStrongCrossThreadPersistentRegion () const
CrossThreadPersistentRegion & GetWeakCrossThreadPersistentRegion ()
const CrossThreadPersistentRegion & GetWeakCrossThreadPersistentRegion () const
size_t ObjectPayloadSize () const
virtual heap::base::Stack * stack ()
StackSupport stack_support () const
virtual void set_override_stack_state (EmbedderStackState state)=0
virtual void clear_overridden_stack_state ()=0
void Terminate ()
virtual bool IsGCForbidden () const
bool in_atomic_pause () const
HeapStatistics CollectStatistics (HeapStatistics::DetailLevel)
EmbedderStackState stack_state_of_prev_gc () const
void SetStackStateOfPrevGC (EmbedderStackState stack_state)
void SetInAtomicPauseForTesting (bool value)
virtual void StartIncrementalGarbageCollectionForTesting ()=0
virtual void FinalizeIncrementalGarbageCollectionForTesting (EmbedderStackState)=0
void SetMetricRecorder (std::unique_ptr< MetricRecorder > histogram_recorder)
virtual bool CurrentThreadIsHeapThread () const
MarkingType marking_support () const
SweepingType sweeping_support () const
bool incremental_marking_supported () const
bool generational_gc_supported () const
StickyBits sticky_bits () const
HeapObjectNameForUnnamedObject name_of_unnamed_object () const
void set_name_of_unnamed_object (HeapObjectNameForUnnamedObject value)
bool HasMoveListeners () const
void CallMoveListeners (Address from, Address to, size_t size_including_header)
void RegisterMoveListener (MoveListener *listener)
void UnregisterMoveListener (MoveListener *listener)
void set_incremental_marking_in_progress (bool value)
void EnterNoGCScope ()
void LeaveNoGCScope ()
void EnterDisallowGCScope ()
void LeaveDisallowGCScope ()
Static Public Member Functions
static HeapBase & From (cppgc::HeapHandle &heap_handle)
static const HeapBase & From (const cppgc::HeapHandle &heap_handle)
Protected Member Functions
virtual void FinalizeIncrementalGarbageCollectionIfNeeded (cppgc::Heap::StackState)=0
virtual bool IsGCAllowed () const
bool in_no_gc_scope () const
bool IsMarking () const
size_t ExecutePreFinalizers ()
PageAllocator * page_allocator () const
Static Protected Member Functions
static std::unique_ptr< PageBackend > InitializePageBackend (PageAllocator &allocator)
Protected Attributes
int heap_thread_id_ = v8::base::OS::GetCurrentThreadId()
RawHeap raw_heap_
std::shared_ptr< cppgc::Platform > platform_
std::unique_ptr< FatalOutOfMemoryHandler > oom_handler_
std::unique_ptr< PageBackend > page_backend_
HeapRegistry::Subscription heap_registry_subscription_ {*this}
std::unique_ptr< StatsCollector > stats_collector_
std::unique_ptr< heap::base::Stack > stack_
std::unique_ptr< PreFinalizerHandler > prefinalizer_handler_
std::unique_ptr< MarkerBase > marker_
Compactor compactor_
ObjectAllocator object_allocator_
Sweeper sweeper_
PersistentRegion strong_persistent_region_
PersistentRegion weak_persistent_region_
CrossThreadPersistentRegion strong_cross_thread_persistent_region_
CrossThreadPersistentRegion weak_cross_thread_persistent_region_
ProcessHeapStatisticsUpdater::AllocationObserverImpl allocation_observer_for_PROCESS_HEAP_STATISTICS_
size_t no_gc_scope_ = 0
size_t disallow_gc_scope_ = 0
const StackSupport stack_support_
EmbedderStackState stack_state_of_prev_gc_
bool in_atomic_pause_ = false
MarkingType marking_support_
SweepingType sweeping_support_
HeapObjectNameForUnnamedObject name_for_unnamed_object_
std::vector< MoveListener * > move_listeners_
Friends
class MarkerBase::IncrementalMarkingTask
class cppgc::subtle::DisallowGarbageCollectionScope
class cppgc::testing::Heap
Detailed Description
Definition at line 82 of file heap-base.h.
Member Typedef Documentation
MarkingType
using cppgc::internal::HeapBase::MarkingType = cppgc::Heap::MarkingType
Definition at line 85 of file heap-base.h.
StackSupport
using cppgc::internal::HeapBase::StackSupport = cppgc::Heap::StackSupport
Definition at line 84 of file heap-base.h.
SweepingType
using cppgc::internal::HeapBase::SweepingType = cppgc::Heap::SweepingType
Definition at line 86 of file heap-base.h.
Constructor & Destructor Documentation
HeapBase() [1/2]
cppgc::internal::HeapBase::HeapBase (std::shared_ptr< cppgc::Platform > platform, const std::vector< std::unique_ptr< CustomSpaceBase >> & custom_spaces, StackSupport stack_support, MarkingType marking_support, SweepingType sweeping_support, GarbageCollector & garbage_collector)
Definition at line 99 of file heap-base.cc.
    : raw_heap_(this, custom_spaces),
      platform_(std::move(platform)),
      oom_handler_(std::make_unique<FatalOutOfMemoryHandler>(this)),
#if defined(LEAK_SANITIZER)
      lsan_page_allocator_(std::make_unique<v8::base::LsanPageAllocator>(
          platform_->GetPageAllocator())),
#endif // LEAK_SANITIZER
      page_backend_(InitializePageBackend(*page_allocator())),
      stats_collector_(std::make_unique<StatsCollector>(platform_.get())),
      stack_(std::make_unique<heap::base::Stack>()),
      prefinalizer_handler_(std::make_unique<PreFinalizerHandler>(*this)),
      compactor_(raw_heap_),
      object_allocator_(raw_heap_, *page_backend_, *stats_collector_,
                        *prefinalizer_handler_, *oom_handler_,
                        garbage_collector),
      sweeper_(*this),
      strong_persistent_region_(*this, *oom_handler_),
      weak_persistent_region_(*this, *oom_handler_),
      strong_cross_thread_persistent_region_(*oom_handler_),
      weak_cross_thread_persistent_region_(*oom_handler_),
#if defined(CPPGC_YOUNG_GENERATION)
      remembered_set_(*this),
#endif // defined(CPPGC_YOUNG_GENERATION)
      stack_support_(stack_support),
      marking_support_(marking_support),
      sweeping_support_(sweeping_support) {
  stats_collector_->RegisterObserver(
      &allocation_observer_for_PROCESS_HEAP_STATISTICS_);
  stack_->SetStackStart();
}
References allocation_observer_for_PROCESS_HEAP_STATISTICS_, stack_, and stats_collector_.
 HeapBase()
cppgc::internal::HeapBase::~HeapBase () [virtual], [default]
HeapBase() [2/2]
cppgc::internal::HeapBase::HeapBase (const HeapBase &) [delete]
Member Function Documentation
CallMoveListeners()
void cppgc::internal::HeapBase::CallMoveListeners (Address from, Address to, size_t size_including_header)
Definition at line 322 of file heap-base.cc.
                                                               {
  for (const auto& listener : move_listeners_) {
    listener->OnMove(from, to, size_including_header);
  }
}
References move_listeners_.
clear_overridden_stack_state()
virtual void cppgc::internal::HeapBase::clear_overridden_stack_state () [pure virtual]
Implemented in v8::internal::CppHeap, and cppgc::internal::Heap.
Referenced by cppgc::testing::OverrideEmbedderStackStateScope::~OverrideEmbedderStackStateScope().
CollectStatistics()
HeapStatistics cppgc::internal::HeapBase::CollectStatistics (HeapStatistics::DetailLevel detail_level)
Definition at line 299 of file heap-base.cc.
                                            {
  if (detail_level == HeapStatistics::DetailLevel::kBrief) {
    const size_t pooled_memory = page_backend_->page_pool().PooledMemory();
    const size_t committed_memory =
        stats_collector_->allocated_memory_size() + pooled_memory;
    const size_t resident_memory =
        stats_collector_->resident_memory_size() + pooled_memory;
    return {committed_memory,
            resident_memory,
            stats_collector_->allocated_object_size(),
            pooled_memory,
            HeapStatistics::DetailLevel::kBrief,
            {},
            {}};
  }
  sweeper_.FinishIfRunning();
  object_allocator_.ResetLinearAllocationBuffers();
  return HeapStatisticsCollector().CollectDetailedStatistics(this);
}
References cppgc::internal::HeapStatisticsCollector::CollectDetailedStatistics(), cppgc::internal::Sweeper::FinishIfRunning(), object_allocator_, page_backend_, cppgc::internal::ObjectAllocator::ResetLinearAllocationBuffers(), stats_collector_, and sweeper_.
Referenced by v8::CppHeap::CollectStatistics().
compactor()
Compactor& cppgc::internal::HeapBase::compactor () [inline]
Definition at line 133 of file heap-base.h.
{ return compactor_; }
Referenced by cppgc::internal::MarkerBase::ClearAllWorklistsForTesting(), cppgc::testing::StandaloneTestingHeap::ForceCompactionForNextGarbageCollection(), and cppgc::internal::anonymous_namespace{concurrent-marker.cc}::ConcurrentMarkingTask::Run().
CurrentThreadIsHeapThread()
bool cppgc::internal::HeapBase::CurrentThreadIsHeapThread () const [virtual]
Reimplemented in v8::internal::CppHeap.
Definition at line 351 of file heap-base.cc.
                                               {
  return heap_thread_id_ == v8::base::OS::GetCurrentThreadId();
}
References v8::base::OS::GetCurrentThreadId(), and heap_thread_id_.
Referenced by cppgc::internal::SameThreadEnabledCheckingPolicyBase::CheckPointerImpl(), cppgc::internal::PreFinalizerHandler::CurrentThreadIsCreationThread(), and v8::internal::CppHeap::CurrentThreadIsHeapThread().
EnterDisallowGCScope()
void cppgc::internal::HeapBase::EnterDisallowGCScope () [inline]
Definition at line 258 of file heap-base.h.
{ ++disallow_gc_scope_; }
EnterNoGCScope()
void cppgc::internal::HeapBase::EnterNoGCScope () [inline]
Definition at line 252 of file heap-base.h.
{ ++no_gc_scope_; }
ExecutePreFinalizers()
size_t cppgc::internal::HeapBase::ExecutePreFinalizers () [protected]
Definition at line 161 of file heap-base.cc.
                                      {
#ifdef CPPGC_ALLOW_ALLOCATIONS_IN_PREFINALIZERS
  // Allocations in pre finalizers should not trigger another GC.
  cppgc::subtle::NoGarbageCollectionScope no_gc_scope(*this);
#else
  // Pre finalizers are forbidden from allocating objects.
  cppgc::subtle::DisallowGarbageCollectionScope no_gc_scope(*this);
#endif // CPPGC_ALLOW_ALLOCATIONS_IN_PREFINALIZERS
  prefinalizer_handler_->InvokePreFinalizers();
  return prefinalizer_handler_->ExtractBytesAllocatedInPrefinalizers();
}
References prefinalizer_handler_.
Referenced by v8::internal::CppHeap::CompactAndSweep(), cppgc::internal::Heap::FinalizeGarbageCollectionImpl(), and Terminate().
FinalizeIncrementalGarbageCollectionForTesting()
virtual void cppgc::internal::HeapBase::FinalizeIncrementalGarbageCollectionForTesting (EmbedderStackState) [pure virtual]
Implemented in cppgc::internal::Heap, and v8::internal::CppHeap.
Referenced by cppgc::testing::StandaloneTestingHeap::FinalizeGarbageCollection().
FinalizeIncrementalGarbageCollectionIfNeeded()
virtual void cppgc::internal::HeapBase::FinalizeIncrementalGarbageCollectionIfNeeded (cppgc::Heap::StackState) [protected], [pure virtual]
Implemented in cppgc::internal::Heap, and v8::internal::CppHeap.
Referenced by cppgc::internal::MarkerBase::IncrementalMarkingTask::Run().
From() [1/2]
static const HeapBase& cppgc::internal::HeapBase::From (const cppgc::HeapHandle & heap_handle) [inline], [static]
Definition at line 91 of file heap-base.h.
                                                                  {
    return static_cast<const HeapBase&>(heap_handle);
  }
From() [2/2]
static HeapBase& cppgc::internal::HeapBase::From (cppgc::HeapHandle & heap_handle) [inline], [static]
Definition at line 88 of file heap-base.h.
                                                      {
    return static_cast<HeapBase&>(heap_handle);
  }
Referenced by cppgc::internal::WriteBarrier::DijkstraMarkingBarrierRangeSlow(), cppgc::subtle::DisallowGarbageCollectionScope::Enter(), cppgc::subtle::NoGarbageCollectionScope::Enter(), cppgc::testing::StandaloneTestingHeap::FinalizeGarbageCollection(), cppgc::testing::StandaloneTestingHeap::ForceCompactionForNextGarbageCollection(), cppgc::internal::ExplicitManagementImpl::FreeUnreferencedObject(), cppgc::internal::anonymous_namespace{explicit-management.cc}::InGC(), cppgc::subtle::DisallowGarbageCollectionScope::IsGarbageCollectionAllowed(), cppgc::subtle::HeapState::IsInAtomicPause(), cppgc::subtle::HeapState::IsMarking(), cppgc::subtle::HeapState::IsSweeping(), cppgc::subtle::HeapState::IsSweepingOnOwningThread(), cppgc::subtle::DisallowGarbageCollectionScope::Leave(), cppgc::subtle::NoGarbageCollectionScope::Leave(), cppgc::testing::OverrideEmbedderStackStateScope::OverrideEmbedderStackStateScope(), cppgc::testing::StandaloneTestingHeap::PerformMarkingStep(), cppgc::subtle::HeapState::PreviousGCWasConservative(), cppgc::testing::StandaloneTestingHeap::StartGarbageCollection(), cppgc::testing::StandaloneTestingHeap::ToggleMainThreadMarking(), and cppgc::testing::OverrideEmbedderStackStateScope::~OverrideEmbedderStackStateScope().
generational_gc_supported()
bool cppgc::internal::HeapBase::generational_gc_supported () const [inline]
Definition at line 218 of file heap-base.h.
                                         {
    const bool supported = is_young_generation_enabled();
#if defined(CPPGC_YOUNG_GENERATION)
    DCHECK_IMPLIES(supported, YoungGenerationEnabler::IsEnabled());
#endif // defined(CPPGC_YOUNG_GENERATION)
    return supported;
  }
References DCHECK_IMPLIES.
Referenced by v8::internal::MinorMarkSweepCollector::ClearNonLiveReferences(), v8::internal::Heap::CompleteSweepingYoung(), cppgc::internal::ExplicitManagementImpl::FreeUnreferencedObject(), v8::internal::CppHeap::InitializeMarking(), v8::internal::TracedHandles::IsCppGCHostOld(), cppgc::internal::MarkerBase::MarkerBase(), cppgc::internal::anonymous_namespace{object-allocator.cc}::MarkRangeAsYoung(), v8::internal::MinorMarkSweepCollector::MarkRootsFromTracedHandles(), v8::internal::CppHeap::RememberCrossHeapReferenceIfNeeded(), v8::internal::CppHeap::ResetCrossHeapRememberedSet(), cppgc::internal::Heap::StartGarbageCollection(), Terminate(), v8::internal::CppHeap::VisitCrossHeapRememberedSetIfNeeded(), and cppgc::internal::ConservativeMarkingVisitor::VisitInConstructionConservatively().
GetMarkerRefForTesting()
std::unique_ptr<MarkerBase>& cppgc::internal::HeapBase::GetMarkerRefForTesting () [inline]
Definition at line 131 of file heap-base.h.
{ return marker_; }
GetStrongCrossThreadPersistentRegion() [1/2]
CrossThreadPersistentRegion& cppgc::internal::HeapBase::GetStrongCrossThreadPersistentRegion () [inline]
Definition at line 153 of file heap-base.h.
                                                                      {
    return strong_cross_thread_persistent_region_;
  }
Referenced by cppgc::internal::StrongCrossThreadPersistentPolicy::GetPersistentRegion(), cppgc::internal::MarkerBase::MarkStrongCrossThreadRoots(), and cppgc::internal::MarkerBase::VisitCrossThreadRoots().
GetStrongCrossThreadPersistentRegion() [2/2]
const CrossThreadPersistentRegion& cppgc::internal::HeapBase::GetStrongCrossThreadPersistentRegion () const [inline]
Definition at line 156 of file heap-base.h.
            {
    return strong_cross_thread_persistent_region_;
  }
GetStrongPersistentRegion() [1/2]
PersistentRegion& cppgc::internal::HeapBase::GetStrongPersistentRegion () [inline]
Definition at line 141 of file heap-base.h.
                                                {
    return strong_persistent_region_;
  }
Referenced by cppgc::internal::StrongPersistentPolicy::GetPersistentRegion(), and cppgc::internal::MarkerBase::VisitLocalRoots().
GetStrongPersistentRegion() [2/2]
const PersistentRegion& cppgc::internal::HeapBase::GetStrongPersistentRegion () const [inline]
Definition at line 144 of file heap-base.h.
                                                            {
    return strong_persistent_region_;
  }
GetWeakCrossThreadPersistentRegion() [1/2]
CrossThreadPersistentRegion& cppgc::internal::HeapBase::GetWeakCrossThreadPersistentRegion () [inline]
Definition at line 160 of file heap-base.h.
                                                                    {
    return weak_cross_thread_persistent_region_;
  }
Referenced by cppgc::internal::WeakCrossThreadPersistentPolicy::GetPersistentRegion(), and cppgc::internal::MarkerBase::ProcessCrossThreadWeaknessIfNeeded().
GetWeakCrossThreadPersistentRegion() [2/2]
const CrossThreadPersistentRegion& cppgc::internal::HeapBase::GetWeakCrossThreadPersistentRegion () const [inline]
Definition at line 163 of file heap-base.h.
            {
    return weak_cross_thread_persistent_region_;
  }
GetWeakPersistentRegion() [1/2]
PersistentRegion& cppgc::internal::HeapBase::GetWeakPersistentRegion () [inline]
Definition at line 147 of file heap-base.h.
                                              {
    return weak_persistent_region_;
  }
Referenced by cppgc::internal::WeakPersistentPolicy::GetPersistentRegion(), and cppgc::internal::MarkerBase::ProcessWeakness().
GetWeakPersistentRegion() [2/2]
const PersistentRegion& cppgc::internal::HeapBase::GetWeakPersistentRegion () const [inline]
Definition at line 150 of file heap-base.h.
                                                          {
    return weak_persistent_region_;
  }
HasMoveListeners()
bool cppgc::internal::HeapBase::HasMoveListeners () const [inline]
Definition at line 242 of file heap-base.h.
{ return !move_listeners_.empty(); }
in_atomic_pause()
bool cppgc::internal::HeapBase::in_atomic_pause () const [inline]
Definition at line 188 of file heap-base.h.
{ return in_atomic_pause_; }
Referenced by cppgc::subtle::HeapState::IsInAtomicPause().
in_no_gc_scope()
bool cppgc::internal::HeapBase::in_no_gc_scope () const [inline], [protected]
Definition at line 276 of file heap-base.h.
{ return no_gc_scope_ > 0; }
Referenced by cppgc::internal::Heap::FinalizeGarbageCollectionImpl(), v8::internal::CppHeap::FinalizeIncrementalGarbageCollectionForTesting(), cppgc::internal::Heap::FinalizeIncrementalGarbageCollectionForTesting(), cppgc::internal::Heap::FinalizeIncrementalGarbageCollectionIfRunning(), IsGCAllowed(), cppgc::internal::Heap::StartGarbageCollection(), cppgc::internal::Heap::StartIncrementalGarbageCollection(), v8::internal::CppHeap::StartIncrementalGarbageCollectionForTesting(), and cppgc::internal::Heap::StartIncrementalGarbageCollectionForTesting().
incremental_marking_supported()
bool cppgc::internal::HeapBase::incremental_marking_supported () const [inline]
Definition at line 214 of file heap-base.h.
                                             {
    return marking_support_ != MarkingType::kAtomic;
  }
Referenced by v8::internal::CppHeap::ShouldFinalizeIncrementalMarking().
InitializePageBackend()
std::unique_ptr< PageBackend > cppgc::internal::HeapBase::InitializePageBackend (PageAllocator & allocator) [static], [protected]
Definition at line 150 of file heap-base.cc.
                              {
#if defined(CPPGC_CAGED_HEAP)
  auto& caged_heap = CagedHeap::Instance();
  return std::make_unique<PageBackend>(caged_heap.page_allocator(),
                                       caged_heap.page_allocator());
#else // !CPPGC_CAGED_HEAP
  return std::make_unique<PageBackend>(allocator, allocator);
#endif // !CPPGC_CAGED_HEAP
}
References cppgc::internal::CagedHeap::Instance().
IsGCAllowed()
bool cppgc::internal::HeapBase::IsGCAllowed () const [protected], [virtual]
Reimplemented in v8::internal::CppHeap.
Definition at line 345 of file heap-base.cc.
                                 {
  // GC is prohibited in a GC forbidden scope, or when currently sweeping an
  // object.
  return !sweeper().IsSweepingOnMutatorThread() && !in_no_gc_scope();
}
References in_no_gc_scope(), cppgc::internal::Sweeper::IsSweepingOnMutatorThread(), and sweeper().
Referenced by cppgc::internal::Heap::CollectGarbage(), v8::internal::CppHeap::IsDetachedGCAllowed(), and v8::internal::CppHeap::IsGCAllowed().
IsGCForbidden()
bool cppgc::internal::HeapBase::IsGCForbidden () const [virtual]
Reimplemented in v8::internal::CppHeap.
Definition at line 343 of file heap-base.cc.
{ return disallow_gc_scope_ > 0; }
References disallow_gc_scope_.
Referenced by cppgc::internal::Heap::FinalizeGarbageCollectionImpl(), cppgc::internal::ObjectAllocator::in_disallow_gc_scope(), v8::internal::CppHeap::IsGCForbidden(), and Terminate().
IsMarking()
bool cppgc::internal::HeapBase::IsMarking () const [inline], [protected]
Definition at line 278 of file heap-base.h.
{ return marker_.get(); }
Referenced by cppgc::internal::Heap::CollectGarbage(), v8::internal::CppHeap::CollectGarbageForTesting(), v8::internal::CppHeap::CreateCppMarkingState(), v8::internal::CppHeap::CreateCppMarkingStateForMutatorThread(), cppgc::internal::Heap::EnableGenerationalGC(), cppgc::internal::Heap::FinalizeGarbageCollectionImpl(), v8::internal::CppHeap::FinalizeIncrementalGarbageCollectionForTesting(), cppgc::internal::Heap::FinalizeIncrementalGarbageCollectionForTesting(), cppgc::internal::Heap::FinalizeIncrementalGarbageCollectionIfRunning(), cppgc::internal::Heap::StartGarbageCollection(), cppgc::internal::Heap::StartIncrementalGarbageCollection(), v8::internal::CppHeap::StartIncrementalGarbageCollectionForTesting(), cppgc::internal::Heap::StartIncrementalGarbageCollectionForTesting(), and Terminate().
LeaveDisallowGCScope()
void cppgc::internal::HeapBase::LeaveDisallowGCScope () [inline]
Definition at line 259 of file heap-base.h.
                              {
    DCHECK_GT(disallow_gc_scope_, 0);
    --disallow_gc_scope_;
  }
References DCHECK_GT.
LeaveNoGCScope()
void cppgc::internal::HeapBase::LeaveNoGCScope () [inline]
Definition at line 253 of file heap-base.h.
                        {
    DCHECK_GT(no_gc_scope_, 0);
    --no_gc_scope_;
  }
References DCHECK_GT.
marker()
MarkerBase* cppgc::internal::HeapBase::marker () const [inline]
Definition at line 130 of file heap-base.h.
{ return marker_.get(); }
Referenced by v8::internal::CppHeap::CreateCppMarkingState(), v8::internal::CppHeap::CreateCppMarkingStateForMutatorThread(), cppgc::internal::Compactor::EnableForNextGCForTesting(), v8::internal::CppHeap::EnterFinalPause(), cppgc::subtle::HeapState::IsMarking(), cppgc::testing::StandaloneTestingHeap::PerformMarkingStep(), and cppgc::testing::StandaloneTestingHeap::ToggleMainThreadMarking().
marking_support()
MarkingType cppgc::internal::HeapBase::marking_support () const [inline]
Definition at line 211 of file heap-base.h.
{ return marking_support_; }
Referenced by v8::internal::CppHeap::SelectMarkingType().
name_of_unnamed_object()
HeapObjectNameForUnnamedObject cppgc::internal::HeapBase::name_of_unnamed_object () const [inline]
Definition at line 233 of file heap-base.h.
                                                                {
    return name_for_unnamed_object_;
  }
object_allocator() [1/2]
ObjectAllocator& cppgc::internal::HeapBase::object_allocator () [inline]
Definition at line 135 of file heap-base.h.
{ return object_allocator_; }
Referenced by v8::internal::CppHeap::CppHeap(), cppgc::Heap::GetAllocationHandle(), v8::CppHeap::GetAllocationHandle(), cppgc::internal::Heap::Heap(), cppgc::internal::PreFinalizerHandler::InvokePreFinalizers(), Terminate(), and cppgc::internal::MarkerBase::VisitLocalRoots().
object_allocator() [2/2]
const ObjectAllocator& cppgc::internal::HeapBase::object_allocator () const [inline]
Definition at line 136 of file heap-base.h.
{ return object_allocator_; }
ObjectPayloadSize()
size_t cppgc::internal::HeapBase::ObjectPayloadSize () const
Definition at line 145 of file heap-base.cc.
                                         {
  return ObjectSizeCounter().GetSize(const_cast<RawHeap&>(raw_heap()));
}
References raw_heap().
oom_handler() [1/2]
FatalOutOfMemoryHandler& cppgc::internal::HeapBase::oom_handler () [inline]
Definition at line 110 of file heap-base.h.
{ return *oom_handler_.get(); }
Referenced by v8::internal::CppHeap::AttachIsolate(), and v8::internal::CppHeap::DetachIsolate().
oom_handler() [2/2]
const FatalOutOfMemoryHandler& cppgc::internal::HeapBase::oom_handler () const [inline]
Definition at line 111 of file heap-base.h.
                                                     {
    return *oom_handler_.get();
  }
operator=()
HeapBase& cppgc::internal::HeapBase::operator= (const HeapBase &) [delete]
page_allocator()
PageAllocator * cppgc::internal::HeapBase::page_allocator () const [protected]
Definition at line 137 of file heap-base.cc.
                                              {
#if defined(LEAK_SANITIZER)
  return lsan_page_allocator_.get();
#else // !LEAK_SANITIZER
  return platform_->GetPageAllocator();
#endif // !LEAK_SANITIZER
}
References platform_.
page_backend() [1/2]
PageBackend* cppgc::internal::HeapBase::page_backend () [inline]
Definition at line 115 of file heap-base.h.
{ return page_backend_.get(); }
Referenced by cppgc::internal::SameThreadEnabledCheckingPolicyBase::CheckPointerImpl(), and cppgc::internal::Sweeper::SweeperImpl::NotifyDone().
page_backend() [2/2]
const PageBackend* cppgc::internal::HeapBase::page_backend () const [inline]
Definition at line 116 of file heap-base.h.
{ return page_backend_.get(); }
platform() [1/2]
cppgc::Platform* cppgc::internal::HeapBase::platform () [inline]
Definition at line 107 of file heap-base.h.
{ return platform_.get(); }
Referenced by v8::internal::CppHeap::AttachIsolate(), v8::internal::CppHeap::CollectCustomSpaceStatisticsAtLastGC(), and v8::internal::CppHeap::EnableDetachedGarbageCollectionsForTesting().
platform() [2/2]
const cppgc::Platform* cppgc::internal::HeapBase::platform () const [inline]
Definition at line 108 of file heap-base.h.
{ return platform_.get(); }
prefinalizer_handler() [1/2]
PreFinalizerHandler* cppgc::internal::HeapBase::prefinalizer_handler () [inline]
Definition at line 123 of file heap-base.h.
                                              {
    return prefinalizer_handler_.get();
  }
Referenced by cppgc::internal::SameThreadEnabledCheckingPolicyBase::CheckPointerImpl().
prefinalizer_handler() [2/2]
const PreFinalizerHandler* cppgc::internal::HeapBase::prefinalizer_handler () const [inline]
Definition at line 126 of file heap-base.h.
                                                          {
    return prefinalizer_handler_.get();
  }
raw_heap() [1/2]
RawHeap& cppgc::internal::HeapBase::raw_heap () [inline]
Definition at line 104 of file heap-base.h.
{ return raw_heap_; }
Referenced by v8::internal::CppHeap::CollectCustomSpaceStatisticsAtLastGC(), v8::internal::CppHeap::InitializeMarking(), ObjectPayloadSize(), cppgc::internal::MarkingVerifierBase::ReportDifferences(), cppgc::internal::MarkingVerifierBase::Run(), cppgc::internal::Heap::StartGarbageCollection(), and Terminate().
raw_heap() [2/2]
const RawHeap& cppgc::internal::HeapBase::raw_heap () const [inline]
Definition at line 105 of file heap-base.h.
{ return raw_heap_; }
RegisterMoveListener()
void cppgc::internal::HeapBase::RegisterMoveListener (MoveListener * listener)
Definition at line 329 of file heap-base.cc.
                                                          {
  // Registering the same listener multiple times would work, but probably
  // indicates a mistake in the component requesting the registration.
  DCHECK_EQ(std::find(move_listeners_.begin(), move_listeners_.end(), listener),
            move_listeners_.end());
  move_listeners_.push_back(listener);
}
References DCHECK_EQ, and move_listeners_.
set_incremental_marking_in_progress()
void cppgc::internal::HeapBase::set_incremental_marking_in_progress (bool value) [inline]
Definition at line 248 of file heap-base.h.
                                                       {
    is_incremental_marking_in_progress_ = value;
  }
References v8::internal::value.
set_name_of_unnamed_object()
void cppgc::internal::HeapBase::set_name_of_unnamed_object (HeapObjectNameForUnnamedObject value) [inline]
Definition at line 236 of file heap-base.h.
                                                                        {
    name_for_unnamed_object_ = value;
  }
References v8::internal::value.
Referenced by cppgc::internal::ClassNameAsHeapObjectNameScope::ClassNameAsHeapObjectNameScope().
set_override_stack_state()
virtual void cppgc::internal::HeapBase::set_override_stack_state (EmbedderStackState state) [pure virtual]
Implemented in cppgc::internal::Heap, and v8::internal::CppHeap.
Referenced by cppgc::testing::OverrideEmbedderStackStateScope::OverrideEmbedderStackStateScope().
SetInAtomicPauseForTesting()
void cppgc::internal::HeapBase::SetInAtomicPauseForTesting (bool value) [inline]
Definition at line 199 of file heap-base.h.
{ in_atomic_pause_ = value; }
References v8::internal::value.
SetMetricRecorder()
void cppgc::internal::HeapBase::SetMetricRecorder (std::unique_ptr< MetricRecorder > histogram_recorder) [inline]
Definition at line 205 of file heap-base.h.
                                                                           {
    stats_collector_->SetMetricRecorder(std::move(histogram_recorder));
  }
Referenced by v8::internal::CppHeap::AttachIsolate(), and v8::internal::CppHeap::DetachIsolate().
SetStackStateOfPrevGC()
void cppgc::internal::HeapBase::SetStackStateOfPrevGC (EmbedderStackState stack_state) [inline]
Definition at line 195 of file heap-base.h.
                                                             {
    stack_state_of_prev_gc_ = stack_state;
  }
Referenced by cppgc::internal::MarkerBase::LeaveAtomicPause().
stack()
virtual heap::base::Stack* cppgc::internal::HeapBase::stack () [inline], [virtual]
Reimplemented in v8::internal::CppHeap.
Definition at line 174 of file heap-base.h.
{ return stack_.get(); }
Referenced by cppgc::internal::Heap::FinalizeGarbageCollection(), cppgc::internal::MarkingVerifierBase::Run(), v8::internal::CppHeap::stack(), and cppgc::internal::MarkerBase::VisitLocalRoots().
stack_state_of_prev_gc()
EmbedderStackState cppgc::internal::HeapBase::stack_state_of_prev_gc () const [inline]
Definition at line 192 of file heap-base.h.
                                                    {
    return stack_state_of_prev_gc_;
  }
Referenced by v8::internal::CppHeap::CompactAndSweep(), and cppgc::subtle::HeapState::PreviousGCWasConservative().
stack_support()
StackSupport cppgc::internal::HeapBase::stack_support () const [inline]
Definition at line 176 of file heap-base.h.
{ return stack_support_; }
Referenced by cppgc::internal::MarkerBase::IncrementalMarkingTask::Post().
StartIncrementalGarbageCollectionForTesting()
virtual void cppgc::internal::HeapBase::StartIncrementalGarbageCollectionForTesting () [pure virtual]
Implemented in cppgc::internal::Heap, and v8::internal::CppHeap.
Referenced by cppgc::testing::StandaloneTestingHeap::StartGarbageCollection().
stats_collector() [1/2]
StatsCollector* cppgc::internal::HeapBase::stats_collector () [inline]
Definition at line 118 of file heap-base.h.
{ return stats_collector_.get(); }
Referenced by v8::internal::CppHeap::AdvanceMarking(), v8::internal::CppHeap::CompactAndSweep(), cppgc::internal::Compactor::CompactSpacesIfEnabled(), v8::internal::CppHeap::CppHeap(), cppgc::internal::BasePage::Destroy(), cppgc::internal::MarkerBase::EnterAtomicPause(), cppgc::internal::Heap::FinalizeGarbageCollectionImpl(), cppgc::internal::Heap::FinalizeIncrementalGarbageCollectionIfNeeded(), cppgc::internal::MutatorMarkingState::FlushDiscoveredEphemeronPairs(), cppgc::internal::ExplicitManagementImpl::FreeUnreferencedObject(), v8::internal::CppHeap::InitializeMarking(), cppgc::internal::PreFinalizerHandler::InvokePreFinalizers(), cppgc::internal::MarkerBase::LeaveAtomicPause(), cppgc::internal::anonymous_namespace{concurrent-marker.cc}::ConcurrentMarkingTask::ProcessWorklists(), cppgc::internal::MarkerBase::ProcessWorklistsWithDeadline(), cppgc::internal::MarkerBase::IncrementalMarkingTask::Run(), cppgc::internal::anonymous_namespace{concurrent-marker.cc}::ConcurrentMarkingTask::Run(), cppgc::internal::anonymous_namespace{explicit-management.cc}::Shrink(), cppgc::internal::Sweeper::SweeperImpl::Start(), cppgc::internal::Heap::StartGarbageCollection(), cppgc::internal::MarkerBase::StartMarking(), Terminate(), and cppgc::internal::LargePage::TryCreate().
stats_collector() [2/2]
const StatsCollector* cppgc::internal::HeapBase::stats_collector () const [inline]
Definition at line 119 of file heap-base.h.
                                                {
    return stats_collector_.get();
  }
sticky_bits()
StickyBits cppgc::internal::HeapBase::sticky_bits () const [inline]
Definition at line 226 of file heap-base.h.
                                 {
    return generational_gc_supported() ? StickyBits::kEnabled
                                       : StickyBits::kDisabled;
  }
References cppgc::internal::kDisabled, and cppgc::internal::kEnabled.
Referenced by cppgc::internal::Compactor::CompactSpacesIfEnabled().
sweeper() [1/2]
Sweeper& cppgc::internal::HeapBase::sweeper () [inline]
Definition at line 138 of file heap-base.h.
{ return sweeper_; }
Referenced by v8::internal::CppHeap::CollectCustomSpaceStatisticsAtLastGC(), v8::internal::CppHeap::CollectGarbageForTesting(), v8::internal::CppHeap::CompactAndSweep(), IsGCAllowed(), cppgc::subtle::HeapState::IsSweeping(), cppgc::subtle::HeapState::IsSweepingOnOwningThread(), Terminate(), and cppgc::internal::ObjectAllocator::TryRefillLinearAllocationBuffer().
sweeper() [2/2]
const Sweeper& cppgc::internal::HeapBase::sweeper () const [inline]
Definition at line 139 of file heap-base.h.
{ return sweeper_; }
sweeping_support()
SweepingType cppgc::internal::HeapBase::sweeping_support () const [inline]
Definition at line 212 of file heap-base.h.
{ return sweeping_support_; }
Referenced by v8::internal::CppHeap::SelectSweepingType().
Terminate()
void cppgc::internal::HeapBase::Terminate ()
Definition at line 224 of file heap-base.cc.
                         {
  CHECK(!IsMarking());
  CHECK(!IsGCForbidden());
  // Cannot use IsGCAllowed() as `Terminate()` will be invoked after detaching
  // which implies GC is prohibited at this point.
  CHECK(!sweeper().IsSweepingOnMutatorThread());
  sweeper().FinishIfRunning();
#if defined(CPPGC_YOUNG_GENERATION)
  if (generational_gc_supported()) {
    DCHECK(is_young_generation_enabled());
    HeapHandle::is_young_generation_enabled_ = false;
    YoungGenerationEnabler::Disable();
  }
#endif // defined(CPPGC_YOUNG_GENERATION)
  constexpr size_t kMaxTerminationGCs = 20;
  size_t gc_count = 0;
  bool more_termination_gcs_needed = false;
  do {
    // Clear root sets.
    strong_persistent_region_.ClearAllUsedNodes();
    weak_persistent_region_.ClearAllUsedNodes();
    {
      PersistentRegionLock guard;
      strong_cross_thread_persistent_region_.ClearAllUsedNodes();
      weak_cross_thread_persistent_region_.ClearAllUsedNodes();
    }
#if defined(CPPGC_YOUNG_GENERATION)
    if (generational_gc_supported()) {
      // Unmark the heap so that the sweeper destructs all objects.
      // TODO(chromium:1029379): Merge two heap iterations (unmarking +
      // sweeping) into forced finalization.
      SequentialUnmarker unmarker(raw_heap());
    }
#endif // defined(CPPGC_YOUNG_GENERATION)
    in_atomic_pause_ = true;
    stats_collector()->NotifyMarkingStarted(CollectionType::kMajor,
                                            GCConfig::MarkingType::kAtomic,
                                            GCConfig::IsForcedGC::kForced);
    object_allocator().ResetLinearAllocationBuffers();
    stats_collector()->NotifyMarkingCompleted(0);
    ExecutePreFinalizers();
    // TODO(chromium:1029379): Prefinalizers may black-allocate objects (under a
    // compile-time option). Run sweeping with forced finalization here.
    sweeper().Start({SweepingConfig::SweepingType::kAtomic,
                     SweepingConfig::CompactableSpaceHandling::kSweep});
    in_atomic_pause_ = false;
    sweeper().FinishIfRunning();
    more_termination_gcs_needed =
        strong_persistent_region_.NodesInUse() ||
        weak_persistent_region_.NodesInUse() || [this]() {
          PersistentRegionLock guard;
          return strong_cross_thread_persistent_region_.NodesInUse() ||
                 weak_cross_thread_persistent_region_.NodesInUse();
        }();
    gc_count++;
  } while (more_termination_gcs_needed && (gc_count < kMaxTerminationGCs));
  CHECK_EQ(0u, strong_persistent_region_.NodesInUse());
  CHECK_EQ(0u, weak_persistent_region_.NodesInUse());
  {
    PersistentRegionLock guard;
    CHECK_EQ(0u, strong_cross_thread_persistent_region_.NodesInUse());
    CHECK_EQ(0u, weak_cross_thread_persistent_region_.NodesInUse());
  }
  CHECK_LE(gc_count, kMaxTerminationGCs);
  object_allocator().ResetLinearAllocationBuffers();
  disallow_gc_scope_++;
}
References CHECK, CHECK_EQ, CHECK_LE, cppgc::internal::PersistentRegionBase::ClearAllUsedNodes(), cppgc::internal::CrossThreadPersistentRegion::ClearAllUsedNodes(), DCHECK, disallow_gc_scope_, ExecutePreFinalizers(), cppgc::internal::Sweeper::FinishIfRunning(), generational_gc_supported(), in_atomic_pause_, cppgc::HeapHandle::is_young_generation_enabled(), cppgc::HeapHandle::is_young_generation_enabled_, IsGCForbidden(), IsMarking(), cppgc::Heap::kAtomic, cppgc::internal::MarkingConfig::kForced, cppgc::internal::kMajor, cppgc::internal::SweepingConfig::kSweep, cppgc::internal::PersistentRegionBase::NodesInUse(), cppgc::internal::CrossThreadPersistentRegion::NodesInUse(), cppgc::internal::StatsCollector::NotifyMarkingCompleted(), cppgc::internal::StatsCollector::NotifyMarkingStarted(), object_allocator(), raw_heap(), cppgc::internal::ObjectAllocator::ResetLinearAllocationBuffers(), cppgc::internal::Sweeper::Start(), stats_collector(), strong_cross_thread_persistent_region_, strong_persistent_region_, sweeper(), weak_cross_thread_persistent_region_, and weak_persistent_region_.
Referenced by v8::internal::CppHeap::Terminate().
UnregisterMoveListener()
void cppgc::internal::HeapBase::UnregisterMoveListener (MoveListener * listener)
Definition at line 337 of file heap-base.cc.
                                                            {
  auto it =
      std::remove(move_listeners_.begin(), move_listeners_.end(), listener);
  move_listeners_.erase(it, move_listeners_.end());
}
References move_listeners_.
Friends And Related Function Documentation
cppgc::subtle::DisallowGarbageCollectionScope
friend class cppgc::subtle::DisallowGarbageCollectionScope [friend]
Definition at line 346 of file heap-base.h.
cppgc::testing::Heap
friend class cppgc::testing::Heap [friend]
Definition at line 347 of file heap-base.h.
MarkerBase::IncrementalMarkingTask
friend class MarkerBase::IncrementalMarkingTask [friend]
Definition at line 345 of file heap-base.h.
Member Data Documentation
allocation_observer_for_PROCESS_HEAP_STATISTICS_
ProcessHeapStatisticsUpdater::AllocationObserverImpl cppgc::internal::HeapBase::allocation_observer_for_PROCESS_HEAP_STATISTICS_ [protected]
Definition at line 322 of file heap-base.h.
Referenced by HeapBase().
compactor_
Compactor cppgc::internal::HeapBase::compactor_ [protected]
Definition at line 312 of file heap-base.h.
Referenced by v8::internal::CppHeap::CompactAndSweep(), v8::internal::CppHeap::EnterFinalPause(), and v8::internal::CppHeap::InitializeMarking().
disallow_gc_scope_
size_t cppgc::internal::HeapBase::disallow_gc_scope_ = 0 [protected]
Definition at line 328 of file heap-base.h.
Referenced by IsGCForbidden(), and Terminate().
heap_registry_subscription_
HeapRegistry::Subscription cppgc::internal::HeapBase::heap_registry_subscription_ {*this} [protected]
Definition at line 305 of file heap-base.h.
heap_thread_id_
int cppgc::internal::HeapBase::heap_thread_id_ = v8::base::OS::GetCurrentThreadId() [protected]
Definition at line 292 of file heap-base.h.
Referenced by CurrentThreadIsHeapThread(), and v8::internal::CppHeap::StartDetachingIsolate().
in_atomic_pause_
bool cppgc::internal::HeapBase::in_atomic_pause_ = false [protected]
Definition at line 334 of file heap-base.h.
Referenced by v8::internal::CppHeap::AdvanceMarking(), v8::internal::CppHeap::CompactAndSweep(), v8::internal::CppHeap::EnterFinalPause(), v8::internal::CppHeap::EnterProcessGlobalAtomicPause(), cppgc::internal::Heap::FinalizeGarbageCollectionImpl(), v8::internal::CppHeap::FinishMarkingAndProcessWeakness(), v8::internal::CppHeap::ProcessCrossThreadWeakness(), v8::internal::CppHeap::ReEnableConcurrentMarking(), and Terminate().
marker_
std::unique_ptr<MarkerBase> cppgc::internal::HeapBase::marker_ [protected]
Definition at line 310 of file heap-base.h.
Referenced by v8::internal::CppHeap::AdvanceMarking(), v8::internal::CppHeap::EnterFinalPause(), v8::internal::CppHeap::EnterProcessGlobalAtomicPause(), cppgc::internal::Heap::FinalizeGarbageCollectionImpl(), v8::internal::CppHeap::FinishConcurrentMarkingIfNeeded(), v8::internal::CppHeap::FinishMarkingAndProcessWeakness(), v8::internal::CppHeap::InitializeMarking(), v8::internal::CppHeap::last_bytes_marked(), v8::internal::CppHeap::ProcessCrossThreadWeakness(), v8::internal::CppHeap::ReEnableConcurrentMarking(), cppgc::internal::Heap::StartGarbageCollection(), v8::internal::CppHeap::StartMarking(), and v8::internal::CppHeap::WriteBarrier().
marking_support_
MarkingType cppgc::internal::HeapBase::marking_support_ [protected]
Definition at line 337 of file heap-base.h.
Referenced by cppgc::internal::Heap::CollectGarbage(), cppgc::internal::Heap::FinalizeIncrementalGarbageCollectionIfRunning(), cppgc::internal::Heap::StartIncrementalGarbageCollection(), and v8::internal::CppHeap::UpdateGCCapabilitiesFromFlags().
move_listeners_
std::vector<MoveListener*> cppgc::internal::HeapBase::move_listeners_ [protected]
Definition at line 343 of file heap-base.h.
Referenced by CallMoveListeners(), RegisterMoveListener(), and UnregisterMoveListener().
name_for_unnamed_object_
HeapObjectNameForUnnamedObject cppgc::internal::HeapBase::name_for_unnamed_object_ [protected]
Initial value:
=
      HeapObjectNameForUnnamedObject::kUseHiddenName
Definition at line 340 of file heap-base.h.
no_gc_scope_
size_t cppgc::internal::HeapBase::no_gc_scope_ = 0 [protected]
Definition at line 327 of file heap-base.h.
Referenced by v8::internal::CppHeap::AttachIsolate(), v8::internal::CppHeap::CppHeap(), v8::internal::CppHeap::DetachIsolate(), and v8::internal::CppHeap::EnableDetachedGarbageCollectionsForTesting().
object_allocator_
ObjectAllocator cppgc::internal::HeapBase::object_allocator_ [protected]
Definition at line 313 of file heap-base.h.
Referenced by CollectStatistics().
oom_handler_
std::unique_ptr<FatalOutOfMemoryHandler> cppgc::internal::HeapBase::oom_handler_ [protected]
Definition at line 296 of file heap-base.h.
page_backend_
std::unique_ptr<PageBackend> cppgc::internal::HeapBase::page_backend_ [protected]
Definition at line 302 of file heap-base.h.
Referenced by CollectStatistics(), and v8::internal::CppHeap::UpdateGCCapabilitiesFromFlags().
platform_
std::shared_ptr<cppgc::Platform> cppgc::internal::HeapBase::platform_ [protected]
Definition at line 295 of file heap-base.h.
Referenced by cppgc::internal::Heap::Heap(), v8::internal::CppHeap::InitializeMarking(), page_allocator(), and cppgc::internal::Heap::StartGarbageCollection().
prefinalizer_handler_
std::unique_ptr<PreFinalizerHandler> cppgc::internal::HeapBase::prefinalizer_handler_ [protected]
Definition at line 309 of file heap-base.h.
Referenced by ExecutePreFinalizers().
raw_heap_
RawHeap cppgc::internal::HeapBase::raw_heap_ [protected]
Definition at line 294 of file heap-base.h.
stack_
std::unique_ptr<heap::base::Stack> cppgc::internal::HeapBase::stack_ [protected]
Definition at line 308 of file heap-base.h.
Referenced by v8::internal::CppHeap::AttachIsolate(), and HeapBase().
stack_state_of_prev_gc_
EmbedderStackState cppgc::internal::HeapBase::stack_state_of_prev_gc_ [protected]
Initial value:
=
      EmbedderStackState::kNoHeapPointers
Definition at line 331 of file heap-base.h.
stack_support_
const StackSupport cppgc::internal::HeapBase::stack_support_ [protected]
Definition at line 330 of file heap-base.h.
stats_collector_
std::unique_ptr<StatsCollector> cppgc::internal::HeapBase::stats_collector_ [protected]
Definition at line 307 of file heap-base.h.
Referenced by CollectStatistics(), v8::internal::CppHeap::FinishMarkingAndProcessWeakness(), v8::internal::CppHeap::GetMetricRecorder(), and HeapBase().
strong_cross_thread_persistent_region_
CrossThreadPersistentRegion cppgc::internal::HeapBase::strong_cross_thread_persistent_region_ [protected]
Definition at line 318 of file heap-base.h.
Referenced by Terminate().
strong_persistent_region_
PersistentRegion cppgc::internal::HeapBase::strong_persistent_region_ [protected]
Definition at line 316 of file heap-base.h.
Referenced by Terminate().
sweeper_
Sweeper cppgc::internal::HeapBase::sweeper_ [protected]
Definition at line 314 of file heap-base.h.
Referenced by v8::internal::CppHeap::CollectGarbage(), CollectStatistics(), cppgc::internal::Heap::FinalizeGarbageCollectionImpl(), v8::internal::CppHeap::FinalizeIncrementalGarbageCollectionForTesting(), cppgc::internal::Heap::FinalizeIncrementalGarbageCollectionForTesting(), v8::internal::CppHeap::FinishAtomicSweepingIfRunning(), v8::internal::CppHeap::FinishSweepingIfOutOfWork(), v8::internal::CppHeap::FinishSweepingIfRunning(), v8::internal::CppHeap::InitializeMarking(), v8::internal::CppHeap::StartDetachingIsolate(), cppgc::internal::Heap::StartGarbageCollection(), and cppgc::internal::Heap::~Heap().
sweeping_support_
SweepingType cppgc::internal::HeapBase::sweeping_support_ [protected]
Definition at line 338 of file heap-base.h.
Referenced by cppgc::internal::Heap::CollectGarbage(), cppgc::internal::Heap::FinalizeIncrementalGarbageCollectionIfRunning(), cppgc::internal::Heap::StartIncrementalGarbageCollection(), and v8::internal::CppHeap::UpdateGCCapabilitiesFromFlags().
weak_cross_thread_persistent_region_
CrossThreadPersistentRegion cppgc::internal::HeapBase::weak_cross_thread_persistent_region_ [protected]
Definition at line 319 of file heap-base.h.
Referenced by Terminate().
weak_persistent_region_
PersistentRegion cppgc::internal::HeapBase::weak_persistent_region_ [protected]
Definition at line 317 of file heap-base.h.
Referenced by Terminate().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/heap-base.h
/mnt/V8SourceCode/src/heap/cppgc/heap-base.cc