v8::internal::baseline::BaselineBatchCompilerJob Class Reference
Public Member Functions
BaselineBatchCompilerJob (Isolate *isolate, DirectHandle< WeakFixedArray > task_queue, int batch_size)
void Compile (LocalIsolate *local_isolate)
void Install (Isolate *isolate)
Private Attributes
std::vector< BaselineCompilerTask > tasks_
std::unique_ptr< PersistentHandles > handles_
Detailed Description
Definition at line 97 of file baseline-batch-compiler.cc.
Constructor & Destructor Documentation
BaselineBatchCompilerJob()
v8::internal::baseline::BaselineBatchCompilerJob::BaselineBatchCompilerJob (Isolate * isolate, DirectHandle< WeakFixedArray > task_queue, int batch_size) [inline]
Definition at line 99 of file baseline-batch-compiler.cc.
                                           {
    handles_ = isolate->NewPersistentHandles();
    tasks_.reserve(batch_size);
    for (int i = 0; i < batch_size; i++) {
      Tagged<MaybeObject> maybe_sfi = task_queue->get(i);
      // TODO(victorgomes): Do I need to clear the value?
      task_queue->set(i, ClearedValue(isolate));
      Tagged<HeapObject> obj;
      // Skip functions where weak reference is no longer valid.
      if (!maybe_sfi.GetHeapObjectIfWeak(&obj)) continue;
      // Skip functions where the bytecode has been flushed.
      Tagged<SharedFunctionInfo> shared = Cast<SharedFunctionInfo>(obj);
      if (!CanCompileWithConcurrentBaseline(shared, isolate)) continue;
      // Skip functions that are already being compiled.
      if (shared->is_sparkplug_compiling()) continue;
      tasks_.emplace_back(isolate, handles_.get(), shared);
    }
    if (v8_flags.trace_baseline) {
      CodeTracer::Scope scope(isolate->GetCodeTracer());
      PrintF(scope.file(), "[Concurrent Sparkplug] compiling %zu functions\n",
             tasks_.size());
    }
  }
References v8::internal::baseline::CanCompileWithConcurrentBaseline(), v8::internal::ClearedValue(), v8::internal::CodeTracer::Scope::file(), v8::internal::Isolate::GetCodeTracer(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectIfWeak(), handles_, v8::internal::Isolate::NewPersistentHandles(), v8::internal::PrintF(), tasks_, and v8::internal::v8_flags.
Member Function Documentation
Compile()
void v8::internal::baseline::BaselineBatchCompilerJob::Compile (LocalIsolate * local_isolate) [inline]
Definition at line 126 of file baseline-batch-compiler.cc.
                                            {
    local_isolate->heap()->AttachPersistentHandles(std::move(handles_));
    for (auto& task : tasks_) {
      task.Compile(local_isolate);
    }
    // Get the handle back since we'd need them to install the code later.
    handles_ = local_isolate->heap()->DetachPersistentHandles();
  }
References v8::internal::LocalHeap::AttachPersistentHandles(), v8::internal::LocalHeap::DetachPersistentHandles(), handles_, v8::internal::LocalIsolate::heap(), and tasks_.
Install()
void v8::internal::baseline::BaselineBatchCompilerJob::Install (Isolate * isolate) [inline]
Definition at line 136 of file baseline-batch-compiler.cc.
                                 {
    HandleScope local_scope(isolate);
    for (auto& task : tasks_) {
      task.Install(isolate);
    }
  }
References tasks_.
Member Data Documentation
handles_
std::unique_ptr<PersistentHandles> v8::internal::baseline::BaselineBatchCompilerJob::handles_ [private]
Definition at line 145 of file baseline-batch-compiler.cc.
Referenced by BaselineBatchCompilerJob(), and Compile().
tasks_
std::vector<BaselineCompilerTask> v8::internal::baseline::BaselineBatchCompilerJob::tasks_ [private]
Definition at line 144 of file baseline-batch-compiler.cc.
Referenced by BaselineBatchCompilerJob(), Compile(), and Install().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/baseline/baseline-batch-compiler.cc