v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor Class Reference
Classes
class Deduplicator
struct GeneratorSplitEdge
class NoThrowingScopeRequired
class ThrowingScope
Public Types
using AssemblerT = TSAssembler< BlockOriginTrackingReducer, TurbolevEarlyLoweringReducer, MachineOptimizationReducer, VariableReducer, RequiredOptimizationReducer, ValueNumberingReducer >
Public Member Functions
GraphBuildingNodeProcessor (PipelineData *data, Graph &graph, Zone *temp_zone, maglev::MaglevCompilationUnit *maglev_compilation_unit, std::optional< BailoutReason > *bailout)
void PreProcessGraph (maglev::Graph *graph)
void PostProcessGraph (maglev::Graph *graph)
bool IsMaglevMainGeneratorSwitchBlock (const maglev::BasicBlock *maglev_block)
void PostProcessBasicBlock (maglev::BasicBlock *maglev_block)
maglev::BlockProcessResult PreProcessBasicBlock (maglev::BasicBlock *maglev_block)
void ComputePredecessorPermutations (maglev::BasicBlock *maglev_block, Block *turboshaft_block, bool skip_backedge, bool ignore_last_predecessor)
void StartExceptionBlock (maglev::BasicBlock *maglev_catch_handler)
void StartSinglePredecessorExceptionBlock (maglev::BasicBlock *maglev_catch_handler, Block *turboshaft_catch_handler)
void InsertTaggingForPhis (maglev::BasicBlock *maglev_catch_handler)
void StartMultiPredecessorExceptionBlock (maglev::BasicBlock *maglev_catch_handler, Block *turboshaft_catch_handler)
void TagExceptionPhiInputsForBlock (Block *old_block, maglev::BasicBlock *maglev_catch_handler, Block *turboshaft_catch_handler)
void EmitLoopSinglePredecessorBlock (maglev::BasicBlock *maglev_loop_header)
void PostPhiProcessing ()
maglev::ProcessResult Process (maglev::Constant *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::RootConstant *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::Int32Constant *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::Uint32Constant *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::IntPtrConstant *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::Float64Constant *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::SmiConstant *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::TaggedIndexConstant *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::TrustedConstant *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::InitialValue *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::RegisterInput *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::FunctionEntryStackCheck *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::Phi *node, const maglev::ProcessingState &state)
V< Any > MakePhiMaybePermuteInputs (maglev::ValueNode *maglev_node, int maglev_input_count, OptionalV< Any > additional_input=OptionalV< Any >::Nullopt())
maglev::ProcessResult Process (maglev::Call *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CallKnownJSFunction *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CallKnownApiFunction *node, const maglev::ProcessingState &state)
V< Any > GenerateBuiltinCall (maglev::NodeBase *node, Builtin builtin, OptionalV< FrameState > frame_state, base::Vector< const OpIndex > arguments, std::optional< int > stack_arg_count=std::nullopt)
maglev::ProcessResult Process (maglev::CallBuiltin *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CallRuntime *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::ThrowReferenceErrorIfHole *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::ThrowIfNotSuperConstructor *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::ThrowSuperAlreadyCalledIfNotHole *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::ThrowSuperNotCalledIfHole *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::ThrowIfNotCallable *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CreateFunctionContext *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::FastCreateClosure *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CreateClosure *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CallWithArrayLike *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CallWithSpread *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CallForwardVarargs *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::Construct *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::ConstructWithSpread *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckConstructResult *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckDerivedConstructResult *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::SetKeyedGeneric *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::GetKeyedGeneric *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::SetNamedGeneric *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::LoadNamedGeneric *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::LoadNamedFromSuperGeneric *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::LoadGlobal *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::StoreGlobal *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::DefineKeyedOwnGeneric *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::DefineNamedOwnGeneric *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::GetIterator *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CreateShallowObjectLiteral *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CreateShallowArrayLiteral *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::StoreInArrayLiteralGeneric *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::MapPrototypeGet *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::MapPrototypeGetInt32Key *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::SetPrototypeHas *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::TestInstanceOf *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::DeleteProperty *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::ToName *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CreateRegExpLiteral *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::GetTemplateObject *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CreateObjectLiteral *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CreateFastArrayElements *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CreateArrayLiteral *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::ForInPrepare *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::ForInNext *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckSmi *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckInt32IsSmi *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckUint32IsSmi *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckIntPtrIsSmi *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckHoleyFloat64IsSmi *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckNumber *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckHeapObject *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckedNumberToInt32 *node, const maglev::ProcessingState &state)
void CheckMaps (V< Object > receiver_input, V< FrameState > frame_state, OptionalV< Map > object_map, const FeedbackSource &feedback, const compiler::ZoneRefSet< Map > &maps, bool check_heap_object, CheckMapsFlags flags)
maglev::ProcessResult Process (maglev::CheckMaps *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckMapsWithAlreadyLoadedMap *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckMapsWithMigration *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckMapsWithMigrationAndDeopt *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::MigrateMapIfNeeded *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckValue *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckValueEqualsInt32 *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckFloat64SameValue *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckString *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckSeqOneByteString *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckStringOrStringWrapper *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckStringOrOddball *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckSymbol *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckInstanceType *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckDynamicValue *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckedSmiSizedInt32 *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckNotHole *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckHoleyFloat64NotHole *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckInt32Condition *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::AllocationBlock *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::InlinedAllocation *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::EnsureWritableFastElements *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::MaybeGrowFastElements *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::ExtendPropertiesBackingStore *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::TransitionAndStoreArrayElement *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::TransitionElementsKindOrCheckMap *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::TransitionElementsKind *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::HasInPrototypeChain *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::UpdateJSArrayLength *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::AllocateElementsArray *node, const maglev::ProcessingState &state)
template<typename Node >
maglev::ProcessResult StringConcatHelper (Node *node, V< String > left, V< String > right)
maglev::ProcessResult Process (maglev::StringConcat *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::UnwrapStringWrapper *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::ConsStringMap *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::StringEqual *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::StringLength *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::StringAt *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::SeqOneByteStringAt *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckedInternalizedString *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckValueEqualsString *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::BuiltinStringFromCharCode *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::BuiltinStringPrototypeCharCodeOrCodePointAt *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::BuiltinSeqOneByteStringCharCodeAt *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::ToString *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::NumberToString *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::ArgumentsLength *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::ArgumentsElements *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::RestLength *node, const maglev::ProcessingState &state)
template<typename T >
maglev::ProcessResult Process (maglev::AbstractLoadTaggedField< T > *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::LoadTaggedFieldForContextSlot *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::LoadDoubleField *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::LoadFloat64 *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::LoadInt32 *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::LoadFixedArrayElement *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::LoadFixedDoubleArrayElement *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::LoadHoleyFixedDoubleArrayElement *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::LoadHoleyFixedDoubleArrayElementCheckedNotHole *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::StoreTaggedFieldNoWriteBarrier *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::StoreTaggedFieldWithWriteBarrier *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::StoreContextSlotWithWriteBarrier *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::StoreDoubleField *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::StoreTrustedPointerFieldWithWriteBarrier *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::StoreFixedArrayElementNoWriteBarrier *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::StoreFixedArrayElementWithWriteBarrier *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::StoreFixedDoubleArrayElement *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::StoreMap *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::StoreFloat64 *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::StoreInt32 *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::LoadEnumCacheLength *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckCacheIndicesNotCleared *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::LoadTaggedFieldByFieldIndex *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::LoadTypedArrayLength *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckTypedArrayBounds *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::LoadUnsignedIntTypedArrayElement *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::LoadSignedIntTypedArrayElement *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::LoadDoubleTypedArrayElement *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::LoadUnsignedIntConstantTypedArrayElement *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::LoadSignedIntConstantTypedArrayElement *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::LoadDoubleConstantTypedArrayElement *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::StoreIntTypedArrayElement *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::StoreDoubleTypedArrayElement *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::StoreIntConstantTypedArrayElement *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::StoreDoubleConstantTypedArrayElement *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckJSDataViewBounds *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::LoadSignedIntDataViewElement *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::LoadDoubleDataViewElement *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::StoreSignedIntDataViewElement *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::StoreDoubleDataViewElement *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckTypedArrayNotDetached *node, const maglev::ProcessingState &state)
void BuildJump (maglev::BasicBlock *target)
maglev::ProcessResult Process (maglev::Jump *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckpointedJump *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::JumpLoop *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::Int32Compare *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::Float64Compare *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::TaggedEqual *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::TaggedNotEqual *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::TestUndetectable *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::TestTypeOf *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckDetectableCallable *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckJSReceiverOrNullOrUndefined *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::BranchIfToBooleanTrue *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::BranchIfInt32Compare *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::BranchIfUint32Compare *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::BranchIfFloat64Compare *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::BranchIfInt32ToBooleanTrue *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::BranchIfIntPtrToBooleanTrue *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::BranchIfFloat64ToBooleanTrue *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::BranchIfFloat64IsHole *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::BranchIfReferenceEqual *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::BranchIfRootConstant *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::BranchIfUndefinedOrNull *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::BranchIfUndetectable *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::BranchIfSmi *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::BranchIfJSReceiver *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::Switch *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckedSmiUntag *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::UnsafeSmiUntag *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckedSmiTagInt32 *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckedSmiTagUint32 *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckedSmiTagIntPtr *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckedSmiTagFloat64 *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::UnsafeSmiTagInt32 *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::UnsafeSmiTagUint32 *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::UnsafeSmiTagIntPtr *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::Int32IncrementWithOverflow *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::Int32DecrementWithOverflow *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::Int32NegateWithOverflow *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::Int32CountLeadingZeros *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::SmiCountLeadingZeros *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::Float64CountLeadingZeros *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::Int32ShiftRightLogical *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::Int32BitwiseNot *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::Int32AbsWithOverflow *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::Float64Negate *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::Float64Abs *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::Float64Round *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::Float64Ieee754Unary *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckedSmiIncrement *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckedSmiDecrement *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::ToNumberOrNumeric *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::LogicalNot *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::ToBooleanLogicalNot *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::ToBoolean *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::Int32ToBoolean *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::IntPtrToBoolean *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::Float64ToBoolean *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::Int32ToNumber *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::Uint32ToNumber *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::IntPtrToNumber *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::Float64ToTagged *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::HoleyFloat64ToTagged *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::Float64ToHeapNumberForField *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::HoleyFloat64IsHole *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckedNumberOrOddballToFloat64 *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckedNumberOrOddballToHoleyFloat64 *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::UncheckedNumberOrOddballToFloat64 *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::TruncateUint32ToInt32 *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckedInt32ToUint32 *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckedIntPtrToUint32 *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckedUint32ToInt32 *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckedIntPtrToInt32 *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::UnsafeInt32ToUint32 *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckedObjectToIndex *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::ChangeInt32ToFloat64 *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::ChangeUint32ToFloat64 *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::ChangeIntPtrToFloat64 *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckedTruncateFloat64ToInt32 *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckedTruncateFloat64ToUint32 *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckedTruncateNumberOrOddballToInt32 *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::TruncateNumberOrOddballToInt32 *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::TruncateFloat64ToInt32 *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::HoleyFloat64ToMaybeNanFloat64 *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckedHoleyFloat64ToFloat64 *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::ConvertHoleToUndefined *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::ConvertReceiver *node, const maglev::ProcessingState &state)
V< Word32 > Int32ToUint8Clamped (V< Word32 > value)
V< Word32 > Float64ToUint8Clamped (V< Float64 > value)
maglev::ProcessResult Process (maglev::Int32ToUint8Clamped *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::Uint32ToUint8Clamped *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::Float64ToUint8Clamped *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::CheckedNumberToUint8Clamped *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::ToObject *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::Return *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::Deopt *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::SetPendingMessage *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::GeneratorStore *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::GeneratorRestoreRegister *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::Abort *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::Identity *node, const maglev::ProcessingState &)
maglev::ProcessResult Process (maglev::Dead *, const maglev::ProcessingState &)
maglev::ProcessResult Process (maglev::DebugBreak *, const maglev::ProcessingState &)
maglev::ProcessResult Process (maglev::GapMove *, const maglev::ProcessingState &)
maglev::ProcessResult Process (maglev::ConstantGapMove *, const maglev::ProcessingState &)
maglev::ProcessResult Process (maglev::VirtualObject *, const maglev::ProcessingState &)
maglev::ProcessResult Process (maglev::GetSecondReturnedValue *node, const maglev::ProcessingState &state)
maglev::ProcessResult Process (maglev::TryOnStackReplacement *, const maglev::ProcessingState &)
maglev::ProcessResult Process (maglev::ReduceInterruptBudgetForReturn *, const maglev::ProcessingState &)
maglev::ProcessResult Process (maglev::ReduceInterruptBudgetForLoop *node, const maglev::ProcessingState &)
maglev::ProcessResult Process (maglev::HandleNoHeapWritesInterrupt *node, const maglev::ProcessingState &)
maglev::ProcessResult Process (maglev::AssertInt32 *node, const maglev::ProcessingState &)
maglev::ProcessResult Process (maglev::CallSelf *, const maglev::ProcessingState &)
maglev::ProcessResult Process (maglev::CallCPPBuiltin *, const maglev::ProcessingState &)
maglev::ProcessResult Process (maglev::UnsafeTruncateUint32ToInt32 *, const maglev::ProcessingState &)
maglev::ProcessResult Process (maglev::UnsafeTruncateFloat64ToInt32 *, const maglev::ProcessingState &)
maglev::ProcessResult Process (maglev::BranchIfTypeOf *, const maglev::ProcessingState &)
AssemblerT & Asm ()
Zone * temp_zone ()
Zone * graph_zone ()
bool IsMapped (const maglev::NodeBase *node) const
Static Public Attributes
static constexpr int kMinClampedUint8 = 0
static constexpr int kMaxClampedUint8 = 255
Private Types
enum class Sign { kSigned
, kUnsigned
 }
Private Member Functions
OptionalV< FrameState > BuildFrameState (maglev::EagerDeoptInfo *eager_deopt_info)
OptionalV< FrameState > BuildFrameState (maglev::LazyDeoptInfo *lazy_deopt_info)
OptionalV< FrameState > BuildParentFrameState (maglev::DeoptFrame &frame, const maglev::VirtualObjectList &virtual_objects)
OptionalV< FrameState > BuildFrameState (maglev::ConstructInvokeStubDeoptFrame &frame, const maglev::VirtualObjectList &virtual_objects)
OptionalV< FrameState > BuildFrameState (maglev::InlinedArgumentsDeoptFrame &frame, const maglev::VirtualObjectList &virtual_objects)
OptionalV< FrameState > BuildFrameState (maglev::BuiltinContinuationDeoptFrame &frame, const maglev::VirtualObjectList &virtual_objects)
OptionalV< FrameState > BuildFrameState (maglev::InterpretedDeoptFrame &frame, const maglev::VirtualObjectList &virtual_objects, interpreter::Register result_location, int result_size)
void AddDeoptInput (FrameStateData::Builder &builder, const maglev::VirtualObjectList &virtual_objects, const maglev::ValueNode *node)
void AddDeoptInput (FrameStateData::Builder &builder, const maglev::VirtualObjectList &virtual_objects, const maglev::ValueNode *node, interpreter::Register reg, interpreter::Register result_location, int result_size)
void AddVirtualObjectInput (FrameStateData::Builder &builder, const maglev::VirtualObjectList &virtual_objects, const maglev::VirtualObject *vobj)
void AddVirtualObjectNestedValue (FrameStateData::Builder &builder, const maglev::VirtualObjectList &virtual_objects, const maglev::ValueNode *value)
OutputFrameStateCombine ComputeCombine (maglev::InterpretedDeoptFrame &frame, interpreter::Register result_location, int result_size)
const FrameStateInfo * MakeFrameStateInfo (maglev::InterpretedDeoptFrame &maglev_frame, OutputFrameStateCombine combine)
const FrameStateInfo * MakeFrameStateInfo (maglev::InlinedArgumentsDeoptFrame &maglev_frame)
const FrameStateInfo * MakeFrameStateInfo (maglev::ConstructInvokeStubDeoptFrame &maglev_frame)
const FrameStateInfo * MakeFrameStateInfo (maglev::BuiltinContinuationDeoptFrame &maglev_frame)
SharedFunctionInfoRef GetSharedFunctionInfo (const maglev::DeoptFrame &deopt_frame)
template<typename rep >
V< Word32 > ConvertCompare (maglev::Input left_input, maglev::Input right_input, ::Operation operation, Sign sign)
V< Word32 > ConvertInt32Compare (maglev::Input left_input, maglev::Input right_input, maglev::AssertCondition condition, bool *negate_result)
V< Word32 > RootEqual (maglev::Input input, RootIndex root)
void DeoptIfInt32IsNotSmi (maglev::Input maglev_input, V< FrameState > frame_state, const compiler::FeedbackSource &feedback)
void DeoptIfInt32IsNotSmi (V< Word32 > input, V< FrameState > frame_state, const compiler::FeedbackSource &feedback)
std::pair< V< WordPtr >, V< Object > > GetTypedArrayDataAndBasePointers (V< JSTypedArray > typed_array)
V< Untagged > BuildTypedArrayLoad (V< JSTypedArray > typed_array, V< Word32 > index, ElementsKind kind)
V< Untagged > BuildConstantTypedArrayLoad (compiler::JSTypedArrayRef typed_array, V< Word32 > index, ElementsKind kind)
void BuildTypedArrayStore (V< JSTypedArray > typed_array, V< Word32 > index, V< Untagged > value, ElementsKind kind)
void BuildConstantTypedArrayStore (compiler::JSTypedArrayRef typed_array, V< Word32 > index, V< Untagged > value, ElementsKind kind)
V< Number > Float64ToTagged (V< Float64 > input, maglev::Float64ToTagged::ConversionMode conversion_mode)
V< NumberOrUndefined > HoleyFloat64ToTagged (V< Float64 > input, maglev::HoleyFloat64ToTagged::ConversionMode conversion_mode)
void FixLoopPhis (maglev::BasicBlock *loop)
RegisterRepresentation RegisterRepresentationFor (maglev::ValueRepresentation value_rep)
V< Boolean > ConvertWord32ToJSBool (V< Word32 > b, bool flip=false)
V< Boolean > ConvertWordPtrToJSBool (V< WordPtr > b, bool flip=false)
V< Word32 > ToBit (maglev::Input input, TruncateJSPrimitiveToUntaggedOp::InputAssumptions assumptions)
V< Word32 > Float64ToBit (V< Float64 > input)
LazyDeoptOnThrow ShouldLazyDeoptOnThrow (maglev::NodeBase *node)
template<typename Function >
void IterCatchHandlerPhis (const maglev::BasicBlock *catch_block, Function &&callback)
OpIndex MapPhiInput (const maglev::Input input, int input_index)
OpIndex MapPhiInput (const maglev::NodeBase *node, int input_index)
template<typename T >
V< T > Map (const maglev::Input input, bool can_be_invalid=true)
OpIndex Map (const maglev::Input input, bool can_be_invalid=true)
OpIndex Map (const maglev::NodeBase *node, bool can_be_invalid=true)
Block * Map (const maglev::BasicBlock *block)
void SetMap (maglev::NodeBase *node, V< Any > idx)
void SetMapMaybeMultiReturn (maglev::NodeBase *node, V< Any > idx)
void RecordRepresentation (OpIndex idx, maglev::ValueRepresentation repr)
V< NativeContext > native_context ()
Private Attributes
PipelineData * data_
Zone * temp_zone_
Isolate * isolate_ = data_->isolate()
LocalIsolate * local_isolate_ = isolate_->AsLocalIsolate()
JSHeapBroker * broker_ = data_->broker()
LocalFactory * local_factory_ = local_isolate_->factory()
AssemblerT assembler_
maglev::MaglevCompilationUnit * maglev_compilation_unit_
ZoneUnorderedMap< const maglev::NodeBase *, OpIndex > node_mapping_
ZoneUnorderedMap< const maglev::BasicBlock *, Block * > block_mapping_
ZoneUnorderedMap< int, Variable > regs_to_vars_
V< HeapObject > undefined_value_
Deduplicator deduplicator_
V< Object > catch_block_begin_ = V<Object>::Invalid()
ZoneUnorderedMap< const maglev::BasicBlock *, Block * > loop_single_edge_predecessors_
base::SmallVector< OpIndex, 16 > loop_phis_first_input_
int loop_phis_first_input_index_ = -1
V< Object > second_return_value_ = V<Object>::Invalid()
ZoneAbslFlatHashMap< OpIndex, maglev::ValueRepresentation > maglev_representations_
GeneratorAnalyzer generator_analyzer_
bool is_visiting_generator_main_switch_ = false
bool on_generator_switch_loop_ = false
Variable header_switch_input_
V< Word32 > loop_default_generator_value_ = V<Word32>::Invalid()
V< Object > dummy_object_input_ = V<Object>::Invalid()
V< Word32 > dummy_word32_input_ = V<Word32>::Invalid()
V< Float64 > dummy_float64_input_ = V<Float64>::Invalid()
maglev::NodeBase * maglev_generator_context_node_ = nullptr
Variable generator_context_
std::unordered_map< const maglev::BasicBlock *, std::vector< GeneratorSplitEdge > > pre_loop_generator_blocks_
V< NativeContext > native_context_ = V<NativeContext>::Invalid()
V< Object > new_target_param_ = V<Object>::Invalid()
base::SmallVector< int, 16 > predecessor_permutation_
std::optional< BailoutReason > * bailout_
Static Private Attributes
static constexpr int kDefaultSwitchVarValue = -1
Detailed Description
Definition at line 482 of file turbolev-graph-builder.cc.
Member Typedef Documentation
AssemblerT
using v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::AssemblerT = TSAssembler<BlockOriginTrackingReducer, TurbolevEarlyLoweringReducer, MachineOptimizationReducer, VariableReducer, RequiredOptimizationReducer, ValueNumberingReducer>
Definition at line 484 of file turbolev-graph-builder.cc.
Member Enumeration Documentation
Sign
enum v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Sign [strong], [private]
Enumerator
kSigned
kUnsigned
Definition at line 5523 of file turbolev-graph-builder.cc.
{ kSigned, kUnsigned };
Constructor & Destructor Documentation
GraphBuildingNodeProcessor()
v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::GraphBuildingNodeProcessor (PipelineData * data, Graph & graph, Zone * temp_zone, maglev::MaglevCompilationUnit * maglev_compilation_unit, std::optional< BailoutReason > * bailout) [inline]
Definition at line 489 of file turbolev-graph-builder.cc.
      : data_(data),
        temp_zone_(temp_zone),
        assembler_(data, graph, graph, temp_zone),
        maglev_compilation_unit_(maglev_compilation_unit),
        node_mapping_(temp_zone),
        block_mapping_(temp_zone),
        regs_to_vars_(temp_zone),
        loop_single_edge_predecessors_(temp_zone),
        maglev_representations_(temp_zone),
        generator_analyzer_(temp_zone,
                            maglev_compilation_unit_->graph_labeller()),
        bailout_(bailout) {}
Member Function Documentation
AddDeoptInput() [1/2]
void v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::AddDeoptInput (FrameStateData::Builder & builder, const maglev::VirtualObjectList & virtual_objects, const maglev::ValueNode * node) [inline], [private]
Definition at line 5200 of file turbolev-graph-builder.cc.
                                                  {
    while (node->Is<maglev::Identity>()) {
      node = node->input(0).node();
    }
    if (const maglev::InlinedAllocation* alloc =
            node->TryCast<maglev::InlinedAllocation>()) {
      DCHECK(alloc->HasBeenAnalysed());
      if (alloc->HasBeenElided()) {
        AddVirtualObjectInput(builder, virtual_objects,
                              virtual_objects.FindAllocatedWith(alloc));
        return;
      }
AddDeoptInput() [2/2]
void v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::AddDeoptInput (FrameStateData::Builder & builder, const maglev::VirtualObjectList & virtual_objects, const maglev::ValueNode * node, interpreter::Register reg, interpreter::Register result_location, int result_size) [inline], [private]
Definition at line 5218 of file turbolev-graph-builder.cc.
                                                                           {
    if (result_location.is_valid() && maglev::LazyDeoptInfo::InReturnValues(
                                          reg, result_location, result_size)) {
      builder.AddUnusedRegister();
    } else {
AddVirtualObjectInput()
void v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::AddVirtualObjectInput (FrameStateData::Builder & builder, const maglev::VirtualObjectList & virtual_objects, const maglev::VirtualObject * vobj) [inline], [private]
Definition at line 5230 of file turbolev-graph-builder.cc.
                                                              {
    if (vobj->type() == maglev::VirtualObject::kHeapNumber) {
      // We need to add HeapNumbers as dematerialized HeapNumbers (rather than
      // simply NumberConstant), because they could be mutable HeapNumber
      // fields, in which case we don't want GVN to merge them.
      constexpr int kNumberOfField = 2; // map + value
      builder.AddDematerializedObject(deduplicator_.CreateUnduplicatableId().id,
                                      kNumberOfField);
      builder.AddInput(MachineType::AnyTagged(),
                       __ HeapConstant(local_factory_->heap_number_map()));
      builder.AddInput(MachineType::Float64(),
                       __ Float64Constant(vobj->number()));
      return;
    }
    Deduplicator::DuplicatedId dup_id = deduplicator_.GetDuplicatedId(vobj);
    if (dup_id.duplicated) {
      builder.AddDematerializedObjectReference(dup_id.id);
      return;
    }
    switch (vobj->type()) {
      case maglev::VirtualObject::kHeapNumber:
        // Handled above
        UNREACHABLE();
      case maglev::VirtualObject::kConsString:
        // TODO(olivf): Support elided maglev cons strings in turbolev.
        UNREACHABLE();
      case maglev::VirtualObject::kFixedDoubleArray: {
        constexpr int kMapAndLengthFieldCount = 2;
        uint32_t length = vobj->double_elements_length();
        uint32_t field_count = length + kMapAndLengthFieldCount;
        builder.AddDematerializedObject(dup_id.id, field_count);
        builder.AddInput(
            MachineType::AnyTagged(),
            __ HeapConstantNoHole(local_factory_->fixed_double_array_map()));
        builder.AddInput(MachineType::AnyTagged(),
                         __ SmiConstant(Smi::FromInt(length)));
        FixedDoubleArrayRef elements = vobj->double_elements();
        for (uint32_t i = 0; i < length; i++) {
          i::Float64 value = elements.GetFromImmutableFixedDoubleArray(i);
          if (value.is_hole_nan()) {
            builder.AddInput(
                MachineType::AnyTagged(),
                __ HeapConstantHole(local_factory_->the_hole_value()));
          } else {
            builder.AddInput(MachineType::AnyTagged(),
                             __ NumberConstant(value.get_scalar()));
          }
        }
        return;
      }
      case maglev::VirtualObject::kDefault:
        constexpr int kMapFieldCount = 1;
        uint32_t field_count = vobj->slot_count() + kMapFieldCount;
        builder.AddDematerializedObject(dup_id.id, field_count);
        builder.AddInput(MachineType::AnyTagged(),
                         __ HeapConstantNoHole(vobj->map().object()));
        vobj->ForEachInput([&](maglev::ValueNode* value_node) {
          AddVirtualObjectNestedValue(builder, virtual_objects, value_node);
        });
AddVirtualObjectNestedValue()
void v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::AddVirtualObjectNestedValue (FrameStateData::Builder & builder, const maglev::VirtualObjectList & virtual_objects, const maglev::ValueNode * value) [inline], [private]
Definition at line 5297 of file turbolev-graph-builder.cc.
                                    {
    if (maglev::IsConstantNode(value->opcode())) {
      switch (value->opcode()) {
        case maglev::Opcode::kConstant:
          builder.AddInput(
              MachineType::AnyTagged(),
              __ HeapConstant(value->Cast<maglev::Constant>()->ref().object()));
          break;
        case maglev::Opcode::kFloat64Constant:
          builder.AddInput(
              MachineType::AnyTagged(),
              __ NumberConstant(value->Cast<maglev::Float64Constant>()
                                    ->value()
                                    .get_scalar()));
          break;
        case maglev::Opcode::kInt32Constant:
          builder.AddInput(
              MachineType::AnyTagged(),
              __ NumberConstant(value->Cast<maglev::Int32Constant>()->value()));
          break;
        case maglev::Opcode::kUint32Constant:
          builder.AddInput(MachineType::AnyTagged(),
                           __ NumberConstant(
                               value->Cast<maglev::Uint32Constant>()->value()));
          break;
        case maglev::Opcode::kIntPtrConstant:
          builder.AddInput(MachineType::AnyTagged(),
                           __ NumberConstant(
                               value->Cast<maglev::IntPtrConstant>()->value()));
          break;
        case maglev::Opcode::kRootConstant:
          builder.AddInput(
              MachineType::AnyTagged(),
              (__ HeapConstant(Cast<HeapObject>(isolate_->root_handle(
                  value->Cast<maglev::RootConstant>()->index())))));
          break;
        case maglev::Opcode::kSmiConstant:
          builder.AddInput(
              MachineType::AnyTagged(),
              __ SmiConstant(value->Cast<maglev::SmiConstant>()->value()));
          break;
        case maglev::Opcode::kTrustedConstant:
          builder.AddInput(
              MachineType::AnyTagged(),
              __ TrustedHeapConstant(
                  value->Cast<maglev::TrustedConstant>()->object().object()));
          break;
        case maglev::Opcode::kTaggedIndexConstant:
        default:
          UNREACHABLE();
      }
      return;
    }
    // Special nodes.
    switch (value->opcode()) {
      case maglev::Opcode::kArgumentsElements:
        builder.AddArgumentsElements(
            value->Cast<maglev::ArgumentsElements>()->type());
        break;
      case maglev::Opcode::kArgumentsLength:
        builder.AddArgumentsLength();
        break;
      case maglev::Opcode::kRestLength:
        builder.AddRestLength();
        break;
      case maglev::Opcode::kVirtualObject:
        UNREACHABLE();
      default:
        AddDeoptInput(builder, virtual_objects, value);
Asm()
AssemblerT& v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Asm () [inline]
Definition at line 4895 of file turbolev-graph-builder.cc.
{ return assembler_; }
Referenced by StartMultiPredecessorExceptionBlock().
BuildConstantTypedArrayLoad()
V<Untagged> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::BuildConstantTypedArrayLoad (compiler::JSTypedArrayRef typed_array, V< Word32 > index, ElementsKind kind) [inline], [private]
Definition at line 5650 of file turbolev-graph-builder.cc.
                                                                              {
    // Using the 0 as the base pointer is fine, since the typed array is not on
    // the heap.
    DCHECK(!typed_array.is_on_heap());
    return __ LoadTypedElement(
        __ HeapConstant(typed_array.object()), __ SmiConstant(Smi::zero()),
Referenced by Process().
BuildConstantTypedArrayStore()
void v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::BuildConstantTypedArrayStore (compiler::JSTypedArrayRef typed_array, V< Word32 > index, V< Untagged > value, ElementsKind kind) [inline], [private]
Definition at line 5670 of file turbolev-graph-builder.cc.
                                                       {
    // Using the 0 as the base pointer is fine, since the typed array is not on
    // the heap.
    DCHECK(!typed_array.is_on_heap());
    __ StoreTypedElement(
        __ HeapConstant(typed_array.object()), __ SmiConstant(Smi::zero()),
        __ WordPtrConstant(reinterpret_cast<uintptr_t>(typed_array.data_ptr())),
Referenced by Process().
BuildFrameState() [1/6]
OptionalV<FrameState> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::BuildFrameState (maglev::BuiltinContinuationDeoptFrame & frame, const maglev::VirtualObjectList & virtual_objects) [inline], [private]
Definition at line 5058 of file turbolev-graph-builder.cc.
                                                      {
    FrameStateData::Builder builder;
    if (frame.parent() != nullptr) {
      OptionalV<FrameState> parent_frame =
          BuildParentFrameState(*frame.parent(), virtual_objects);
      if (!parent_frame.has_value()) return OptionalV<FrameState>::Nullopt();
      builder.AddParentFrameState(parent_frame.value());
    }
    // Closure
    if (frame.is_javascript()) {
      builder.AddInput(MachineType::AnyTagged(),
                       __ HeapConstant(frame.javascript_target().object()));
    } else {
      builder.AddUnusedRegister();
    }
    // Parameters
    for (maglev::ValueNode* param : frame.parameters()) {
      AddDeoptInput(builder, virtual_objects, param);
    }
    // Extra fixed JS frame parameters. These are at the end since JS builtins
    // push their parameters in reverse order.
    constexpr int kExtraFixedJSFrameParameters =
        V8_JS_LINKAGE_INCLUDES_DISPATCH_HANDLE_BOOL ? 4 : 3;
    if (frame.is_javascript()) {
      DCHECK_EQ(Builtins::CallInterfaceDescriptorFor(frame.builtin_id())
                    .GetRegisterParameterCount(),
                kExtraFixedJSFrameParameters);
      static_assert(kExtraFixedJSFrameParameters ==
                    3 + (V8_JS_LINKAGE_INCLUDES_DISPATCH_HANDLE_BOOL ? 1 : 0));
      // kJavaScriptCallTargetRegister
      builder.AddInput(MachineType::AnyTagged(),
                       __ HeapConstant(frame.javascript_target().object()));
      // kJavaScriptCallNewTargetRegister
      builder.AddInput(MachineType::AnyTagged(), undefined_value_);
      // kJavaScriptCallArgCountRegister
      builder.AddInput(
          MachineType::AnyTagged(),
          __ SmiConstant(Smi::FromInt(
              Builtins::GetStackParameterCount(frame.builtin_id()))));
#ifdef V8_JS_LINKAGE_INCLUDES_DISPATCH_HANDLE
      // kJavaScriptCallDispatchHandleRegister
      builder.AddInput(
          MachineType::AnyTagged(),
          __ SmiConstant(Smi::FromInt(kInvalidDispatchHandle.value())));
#endif
    }
    // Context
    AddDeoptInput(builder, virtual_objects, frame.context());
    if (builder.Inputs().size() >
        std::numeric_limits<decltype(Operation::input_count)>::max() - 1) {
      *bailout_ = BailoutReason::kTooManyArguments;
      return OptionalV<FrameState>::Nullopt();
    }
    const FrameStateInfo* frame_state_info = MakeFrameStateInfo(frame);
    return __ FrameState(
BuildFrameState() [2/6]
OptionalV<FrameState> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::BuildFrameState (maglev::ConstructInvokeStubDeoptFrame & frame, const maglev::VirtualObjectList & virtual_objects) [inline], [private]
Definition at line 4980 of file turbolev-graph-builder.cc.
                                                      {
    FrameStateData::Builder builder;
    if (frame.parent() != nullptr) {
      OptionalV<FrameState> parent_frame =
          BuildParentFrameState(*frame.parent(), virtual_objects);
      if (!parent_frame.has_value()) return OptionalV<FrameState>::Nullopt();
      builder.AddParentFrameState(parent_frame.value());
    }
    // Closure
    // TODO(dmercadier): ConstructInvokeStub frames don't have a Closure input,
    // but the instruction selector assumes that they do and that it should be
    // skipped. We thus use SmiConstant(0) as a fake Closure input here, but it
    // would be nicer to fix the instruction selector to not require this input
    // at all for such frames.
    V<Any> fake_closure_input = __ SmiZeroConstant();
    builder.AddInput(MachineType::AnyTagged(), fake_closure_input);
    // Parameters
    AddDeoptInput(builder, virtual_objects, frame.receiver());
    // Context
    AddDeoptInput(builder, virtual_objects, frame.context());
    if (builder.Inputs().size() >
        std::numeric_limits<decltype(Operation::input_count)>::max() - 1) {
      *bailout_ = BailoutReason::kTooManyArguments;
      return OptionalV<FrameState>::Nullopt();
    }
    const FrameStateInfo* frame_state_info = MakeFrameStateInfo(frame);
    return __ FrameState(
BuildFrameState() [3/6]
OptionalV<FrameState> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::BuildFrameState (maglev::EagerDeoptInfo * eager_deopt_info) [inline], [private]
Definition at line 4907 of file turbolev-graph-builder.cc.
        :
  OptionalV<FrameState> BuildFrameState(
      maglev::EagerDeoptInfo* eager_deopt_info) {
    deduplicator_.Reset();
    // Eager deopts don't have a result location/size.
    const interpreter::Register result_location =
        interpreter::Register::invalid_value();
    const int result_size = 0;
    const maglev::VirtualObjectList virtual_objects =
        eager_deopt_info->top_frame().GetVirtualObjects();
    switch (eager_deopt_info->top_frame().type()) {
      case maglev::DeoptFrame::FrameType::kInterpretedFrame:
        return BuildFrameState(eager_deopt_info->top_frame().as_interpreted(),
                               virtual_objects, result_location, result_size);
      case maglev::DeoptFrame::FrameType::kBuiltinContinuationFrame:
        return BuildFrameState(
            eager_deopt_info->top_frame().as_builtin_continuation(),
            virtual_objects);
      case maglev::DeoptFrame::FrameType::kInlinedArgumentsFrame:
      case maglev::DeoptFrame::FrameType::kConstructInvokeStubFrame:
BuildFrameState() [4/6]
OptionalV<FrameState> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::BuildFrameState (maglev::InlinedArgumentsDeoptFrame & frame, const maglev::VirtualObjectList & virtual_objects) [inline], [private]
Definition at line 5018 of file turbolev-graph-builder.cc.
                                                      {
    FrameStateData::Builder builder;
    if (frame.parent() != nullptr) {
      OptionalV<FrameState> parent_frame =
          BuildParentFrameState(*frame.parent(), virtual_objects);
      if (!parent_frame.has_value()) return OptionalV<FrameState>::Nullopt();
      builder.AddParentFrameState(parent_frame.value());
    }
    // Closure
    AddDeoptInput(builder, virtual_objects, frame.closure());
    // Parameters
    for (const maglev::ValueNode* arg : frame.arguments()) {
      AddDeoptInput(builder, virtual_objects, arg);
    }
    // Context
    // TODO(dmercadier): InlinedExtraArguments frames don't have a Context
    // input, but the instruction selector assumes that they do and that it
    // should be skipped. We thus use SmiConstant(0) as a fake Context input
    // here, but it would be nicer to fix the instruction selector to not
    // require this input at all for such frames.
    V<Any> fake_context_input = __ SmiZeroConstant();
    builder.AddInput(MachineType::AnyTagged(), fake_context_input);
    if (builder.Inputs().size() >
        std::numeric_limits<decltype(Operation::input_count)>::max() - 1) {
      *bailout_ = BailoutReason::kTooManyArguments;
      return OptionalV<FrameState>::Nullopt();
    }
    const FrameStateInfo* frame_state_info = MakeFrameStateInfo(frame);
    return __ FrameState(
BuildFrameState() [5/6]
OptionalV<FrameState> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::BuildFrameState (maglev::InterpretedDeoptFrame & frame, const maglev::VirtualObjectList & virtual_objects, interpreter::Register result_location, int result_size) [inline], [private]
Definition at line 5125 of file turbolev-graph-builder.cc.
                                                            {
    DCHECK_EQ(result_size != 0, result_location.is_valid());
    FrameStateData::Builder builder;
    if (frame.parent() != nullptr) {
      OptionalV<FrameState> parent_frame =
          BuildParentFrameState(*frame.parent(), virtual_objects);
      if (!parent_frame.has_value()) return OptionalV<FrameState>::Nullopt();
      builder.AddParentFrameState(parent_frame.value());
    }
    // Closure
    AddDeoptInput(builder, virtual_objects, frame.closure());
    // Parameters
    frame.frame_state()->ForEachParameter(
        frame.unit(), [&](maglev::ValueNode* value, interpreter::Register reg) {
          AddDeoptInput(builder, virtual_objects, value, reg, result_location,
                        result_size);
        });
    // Context
    AddDeoptInput(builder, virtual_objects,
                  frame.frame_state()->context(frame.unit()));
    // Locals
    // ForEachLocal in Maglev skips over dead registers, but we still need to
    // call AddUnusedRegister on the Turboshaft FrameStateData Builder.
    // {local_index} is used to keep track of such unused registers.
    // Among the variables not included in ForEachLocal is the Accumulator (but
    // this is fine since there is an entry in the state specifically for the
    // accumulator later).
    int local_index = 0;
    frame.frame_state()->ForEachLocal(
        frame.unit(), [&](maglev::ValueNode* value, interpreter::Register reg) {
          while (local_index < reg.index()) {
            builder.AddUnusedRegister();
            local_index++;
          }
          AddDeoptInput(builder, virtual_objects, value, reg, result_location,
                        result_size);
          local_index++;
        });
    for (; local_index < frame.unit().register_count(); local_index++) {
      builder.AddUnusedRegister();
    }
    // Accumulator
    if (frame.frame_state()->liveness()->AccumulatorIsLive()) {
      AddDeoptInput(builder, virtual_objects,
                    frame.frame_state()->accumulator(frame.unit()),
                    interpreter::Register::virtual_accumulator(),
                    result_location, result_size);
    } else {
      builder.AddUnusedRegister();
    }
    OutputFrameStateCombine combine =
        ComputeCombine(frame, result_location, result_size);
    if (builder.Inputs().size() >
        std::numeric_limits<decltype(Operation::input_count)>::max() - 1) {
      *bailout_ = BailoutReason::kTooManyArguments;
      return OptionalV<FrameState>::Nullopt();
    }
    const FrameStateInfo* frame_state_info = MakeFrameStateInfo(frame, combine);
    return __ FrameState(
BuildFrameState() [6/6]
OptionalV<FrameState> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::BuildFrameState (maglev::LazyDeoptInfo * lazy_deopt_info) [inline], [private]
Definition at line 4931 of file turbolev-graph-builder.cc.
                                            {
    deduplicator_.Reset();
    const maglev::VirtualObjectList virtual_objects =
        lazy_deopt_info->top_frame().GetVirtualObjects();
    switch (lazy_deopt_info->top_frame().type()) {
      case maglev::DeoptFrame::FrameType::kInterpretedFrame:
        return BuildFrameState(
            lazy_deopt_info->top_frame().as_interpreted(), virtual_objects,
            lazy_deopt_info->result_location(), lazy_deopt_info->result_size());
      case maglev::DeoptFrame::FrameType::kConstructInvokeStubFrame:
        return BuildFrameState(lazy_deopt_info->top_frame().as_construct_stub(),
                               virtual_objects);
      case maglev::DeoptFrame::FrameType::kBuiltinContinuationFrame:
        return BuildFrameState(
            lazy_deopt_info->top_frame().as_builtin_continuation(),
            virtual_objects);
      case maglev::DeoptFrame::FrameType::kInlinedArgumentsFrame:
BuildJump()
void v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::BuildJump (maglev::BasicBlock * target) [inline]
Definition at line 3434 of file turbolev-graph-builder.cc.
                                           {
    Block* destination = Map(target);
    if (target->is_loop() && (target->predecessor_count() > 2 ||
                              generator_analyzer_.HeaderIsBypassed(target))) {
      // This loop has multiple forward edges in Maglev, so we'll create an
      // extra block in Turboshaft that will be the only predecessor.
      auto it = loop_single_edge_predecessors_.find(target);
      if (it != loop_single_edge_predecessors_.end()) {
        destination = it->second;
      } else {
        Block* loop_only_pred = __ NewBlock();
        loop_single_edge_predecessors_[target] = loop_only_pred;
        destination = loop_only_pred;
      }
    }
    __ Goto(destination);
  }
References __, generator_analyzer_, v8::internal::compiler::turboshaft::GeneratorAnalyzer::HeaderIsBypassed(), v8::internal::maglev::BasicBlock::is_loop(), loop_single_edge_predecessors_, Map(), and v8::internal::maglev::BasicBlock::predecessor_count().
Referenced by EmitLoopSinglePredecessorBlock(), and Process().
BuildParentFrameState()
OptionalV<FrameState> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::BuildParentFrameState (maglev::DeoptFrame & frame, const maglev::VirtualObjectList & virtual_objects) [inline], [private]
Definition at line 4955 of file turbolev-graph-builder.cc.
                                                      {
    // Only the topmost frame should have a valid result_location and
    // result_size. One reason for this is that, in Maglev, the PokeAt is not an
    // attribute of the DeoptFrame but rather of the LazyDeoptInfo (to which the
    // topmost frame is attached).
    const interpreter::Register result_location =
        interpreter::Register::invalid_value();
    const int result_size = 0;
    switch (frame.type()) {
      case maglev::DeoptFrame::FrameType::kInterpretedFrame:
        return BuildFrameState(frame.as_interpreted(), virtual_objects,
                               result_location, result_size);
      case maglev::DeoptFrame::FrameType::kConstructInvokeStubFrame:
        return BuildFrameState(frame.as_construct_stub(), virtual_objects);
      case maglev::DeoptFrame::FrameType::kInlinedArgumentsFrame:
        return BuildFrameState(frame.as_inlined_arguments(), virtual_objects);
      case maglev::DeoptFrame::FrameType::kBuiltinContinuationFrame:
        return BuildFrameState(frame.as_builtin_continuation(),
BuildTypedArrayLoad()
V<Untagged> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::BuildTypedArrayLoad (V< JSTypedArray > typed_array, V< Word32 > index, ElementsKind kind) [inline], [private]
Definition at line 5641 of file turbolev-graph-builder.cc.
           {data_pointer, base_pointer};
  }
  V<Untagged> BuildTypedArrayLoad(V<JSTypedArray> typed_array, V<Word32> index,
                                  ElementsKind kind) {
    auto [data_pointer, base_pointer] =
        GetTypedArrayDataAndBasePointers(typed_array);
    return __ LoadTypedElement(typed_array, base_pointer, data_pointer,
Referenced by Process().
BuildTypedArrayStore()
void v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::BuildTypedArrayStore (V< JSTypedArray > typed_array, V< Word32 > index, V< Untagged > value, ElementsKind kind) [inline], [private]
Definition at line 5661 of file turbolev-graph-builder.cc.
                                                                  {
    auto [data_pointer, base_pointer] =
        GetTypedArrayDataAndBasePointers(typed_array);
    __ StoreTypedElement(typed_array, base_pointer, data_pointer,
Referenced by Process().
CheckMaps()
void v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::CheckMaps (V< Object > receiver_input, V< FrameState > frame_state, OptionalV< Map > object_map, const FeedbackSource & feedback, const compiler::ZoneRefSet< Map > & maps, bool check_heap_object, CheckMapsFlags flags) [inline]
Definition at line 2362 of file turbolev-graph-builder.cc.
                                       {
    Label<> done(this);
    if (check_heap_object) {
      OpIndex is_smi = __ IsSmi(receiver_input);
      if (AnyMapIsHeapNumber(maps)) {
        // Smis count as matching the HeapNumber map, so we're done.
        GOTO_IF(is_smi, done);
      } else {
        __ DeoptimizeIf(is_smi, frame_state, DeoptimizeReason::kWrongMap,
                        feedback);
      }
    }
#ifdef DEBUG
    if (flags & CheckMapsFlag::kTryMigrateInstance) {
      bool has_migration_targets = false;
      for (MapRef map : maps) {
        if (map.object()->is_migration_target()) {
          has_migration_targets = true;
          break;
        }
      }
      DCHECK(has_migration_targets);
    }
#endif // DEBUG
    __ CheckMaps(V<HeapObject>::Cast(receiver_input), frame_state, object_map,
                 maps, flags, feedback);
    if (done.has_incoming_jump()) {
      GOTO(done);
      BIND(done);
    }
  }
References __, v8::internal::compiler::AnyMapIsHeapNumber(), v8::internal::DCHECK(), v8::internal::flags, v8::internal::compiler::turboshaft::LabelBase< loop, Ts >::has_incoming_jump(), v8::internal::IsSmi(), and v8::internal::compiler::kTryMigrateInstance.
Referenced by Process().
ComputeCombine()
OutputFrameStateCombine v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ComputeCombine (maglev::InterpretedDeoptFrame & frame, interpreter::Register result_location, int result_size) [inline], [private]
Definition at line 5413 of file turbolev-graph-builder.cc.
                                                          {
    if (result_size == 0) {
      return OutputFrameStateCombine::Ignore();
    }
ComputePredecessorPermutations()
void v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ComputePredecessorPermutations (maglev::BasicBlock * maglev_block, Block * turboshaft_block, bool skip_backedge, bool ignore_last_predecessor) [inline]
Definition at line 670 of file turbolev-graph-builder.cc.
                                                                    {
    // This function is only called for loops that need a "single block
    // predecessor" (from EmitLoopSinglePredecessorBlock). The backedge should
    // always be skipped in thus cases. Additionally, this means that when
    // even when {maglev_block} is a loop, {turboshaft_block} shouldn't and
    // should instead be the new single forward predecessor of the loop.
    DCHECK_EQ(skip_backedge, maglev_block->is_loop());
    DCHECK(!turboshaft_block->IsLoop());
    DCHECK(maglev_block->has_phi());
    DCHECK(turboshaft_block->IsBound());
    DCHECK_EQ(__ current_block(), turboshaft_block);
    // Collecting the Maglev predecessors.
    base::SmallVector<const maglev::BasicBlock*, 16> maglev_predecessors;
    maglev_predecessors.resize(maglev_block->predecessor_count());
    for (int i = 0; i < maglev_block->predecessor_count() - skip_backedge;
         ++i) {
      maglev_predecessors[i] = maglev_block->predecessor_at(i);
    }
    predecessor_permutation_.clear();
    predecessor_permutation_.resize(maglev_block->predecessor_count(),
                                    Block::kInvalidPredecessorIndex);
    int index = turboshaft_block->PredecessorCount() - 1;
    // Iterating predecessors from the end (because it's simpler and more
    // efficient in Turboshaft).
    for (const Block* pred : turboshaft_block->PredecessorsIterable()) {
      if (ignore_last_predecessor &&
          index == turboshaft_block->PredecessorCount() - 1) {
        // When generator resumes bypass loop headers, we add an additional
        // predecessor to the header's predecessor (called {pred_for_generator}
        // in EmitLoopSinglePredecessorBlock). This block doesn't have Maglev
        // origin, we thus have to skip it here. To compensate,
        // MakePhiMaybePermuteInputs will take an additional input for these
        // cases.
        index--;
        continue;
      }
      // Finding out to which Maglev predecessor {pred} corresponds.
      const maglev::BasicBlock* orig = __ GetMaglevOrigin(pred);
      auto orig_index = *base::index_of(maglev_predecessors, orig);
      predecessor_permutation_[orig_index] = index;
      index--;
    }
    DCHECK_EQ(index, -1);
  }
References __, v8::base::SmallVector< T, kSize, Allocator >::clear(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::maglev::BasicBlock::has_phi(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::base::index_of(), v8::internal::maglev::BasicBlock::is_loop(), v8::internal::compiler::turboshaft::Block::IsBound(), v8::internal::compiler::turboshaft::Block::IsLoop(), v8::internal::compiler::turboshaft::Block::kInvalidPredecessorIndex, v8::internal::maglev::BasicBlock::predecessor_at(), v8::internal::maglev::BasicBlock::predecessor_count(), predecessor_permutation_, v8::internal::compiler::turboshaft::Block::PredecessorCount(), v8::internal::compiler::turboshaft::Block::PredecessorsIterable(), and v8::base::SmallVector< T, kSize, Allocator >::resize().
Referenced by EmitLoopSinglePredecessorBlock(), and PreProcessBasicBlock().
ConvertCompare()
template<typename rep >
V<Word32> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ConvertCompare (maglev::Input left_input, maglev::Input right_input, ::Operation operation, Sign sign) [inline], [private]
Definition at line 5525 of file turbolev-graph-builder.cc.
                  { kSigned, kUnsigned };
  template <typename rep>
  V<Word32> ConvertCompare(maglev::Input left_input, maglev::Input right_input,
                           ::Operation operation, Sign sign) {
    DCHECK_IMPLIES(
        (std::is_same_v<rep, Float64> || std::is_same_v<rep, Float32>),
        sign == Sign::kSigned);
    ComparisonOp::Kind kind;
    bool swap_inputs = false;
    switch (operation) {
      case ::Operation::kEqual:
      case ::Operation::kStrictEqual:
        kind = ComparisonOp::Kind::kEqual;
        break;
      case ::Operation::kLessThan:
        kind = sign == Sign::kSigned ? ComparisonOp::Kind::kSignedLessThan
                                     : ComparisonOp::Kind::kUnsignedLessThan;
        break;
      case ::Operation::kLessThanOrEqual:
        kind = sign == Sign::kSigned
                   ? ComparisonOp::Kind::kSignedLessThanOrEqual
                   : ComparisonOp::Kind::kUnsignedLessThanOrEqual;
        break;
      case ::Operation::kGreaterThan:
        kind = sign == Sign::kSigned ? ComparisonOp::Kind::kSignedLessThan
                                     : ComparisonOp::Kind::kUnsignedLessThan;
        swap_inputs = true;
        break;
      case ::Operation::kGreaterThanOrEqual:
        kind = sign == Sign::kSigned
                   ? ComparisonOp::Kind::kSignedLessThanOrEqual
                   : ComparisonOp::Kind::kUnsignedLessThanOrEqual;
        swap_inputs = true;
        break;
      default:
        UNREACHABLE();
    }
    V<rep> left = Map(left_input);
    V<rep> right = Map(right_input);
References v8::internal::compiler::kSigned, and v8::internal::compiler::kUnsigned.
ConvertInt32Compare()
V<Word32> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ConvertInt32Compare (maglev::Input left_input, maglev::Input right_input, maglev::AssertCondition condition, bool * negate_result) [inline], [private]
Definition at line 5566 of file turbolev-graph-builder.cc.
                                                     {
    ComparisonOp::Kind kind;
    bool swap_inputs = false;
    switch (condition) {
      case maglev::AssertCondition::kEqual:
        kind = ComparisonOp::Kind::kEqual;
        break;
      case maglev::AssertCondition::kNotEqual:
        kind = ComparisonOp::Kind::kEqual;
        *negate_result = true;
        break;
      case maglev::AssertCondition::kLessThan:
        kind = ComparisonOp::Kind::kSignedLessThan;
        break;
      case maglev::AssertCondition::kLessThanEqual:
        kind = ComparisonOp::Kind::kSignedLessThanOrEqual;
        break;
      case maglev::AssertCondition::kGreaterThan:
        kind = ComparisonOp::Kind::kSignedLessThan;
        swap_inputs = true;
        break;
      case maglev::AssertCondition::kGreaterThanEqual:
        kind = ComparisonOp::Kind::kSignedLessThanOrEqual;
        swap_inputs = true;
        break;
      case maglev::AssertCondition::kUnsignedLessThan:
        kind = ComparisonOp::Kind::kUnsignedLessThan;
        break;
      case maglev::AssertCondition::kUnsignedLessThanEqual:
        kind = ComparisonOp::Kind::kUnsignedLessThanOrEqual;
        break;
      case maglev::AssertCondition::kUnsignedGreaterThan:
        kind = ComparisonOp::Kind::kUnsignedLessThan;
        swap_inputs = true;
        break;
      case maglev::AssertCondition::kUnsignedGreaterThanEqual:
        kind = ComparisonOp::Kind::kUnsignedLessThanOrEqual;
        swap_inputs = true;
        break;
    }
    V<Word32> left = Map(left_input);
    V<Word32> right = Map(right_input);
Referenced by Process().
ConvertWord32ToJSBool()
V<Boolean> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ConvertWord32ToJSBool (V< Word32 > b, bool flip = false) [inline], [private]
Definition at line 5790 of file turbolev-graph-builder.cc.
                                                                   {
    V<Boolean> true_idx = __ HeapConstant(local_factory_->true_value());
    V<Boolean> false_idx = __ HeapConstant(local_factory_->false_value());
    if (flip) std::swap(true_idx, false_idx);
References __, and v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged().
Referenced by Process().
ConvertWordPtrToJSBool()
V<Boolean> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ConvertWordPtrToJSBool (V< WordPtr > b, bool flip = false) [inline], [private]
Definition at line 5798 of file turbolev-graph-builder.cc.
                                                                     {
    V<Boolean> true_idx = __ HeapConstant(local_factory_->true_value());
    V<Boolean> false_idx = __ HeapConstant(local_factory_->false_value());
    if (flip) std::swap(true_idx, false_idx);
    return __ Select(__ WordPtrEqual(b, __ WordPtrConstant(0)), false_idx,
DeoptIfInt32IsNotSmi() [1/2]
void v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::DeoptIfInt32IsNotSmi (maglev::Input maglev_input, V< FrameState > frame_state, const compiler::FeedbackSource & feedback) [inline], [private]
Definition at line 5619 of file turbolev-graph-builder.cc.
                                                                    {
Referenced by Process().
DeoptIfInt32IsNotSmi() [2/2]
void v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::DeoptIfInt32IsNotSmi (V< Word32 > input, V< FrameState > frame_state, const compiler::FeedbackSource & feedback) [inline], [private]
Definition at line 5625 of file turbolev-graph-builder.cc.
                                                                    {
    // TODO(dmercadier): is there no higher level way of doing this?
    V<Tuple<Word32, Word32>> add = __ Int32AddCheckOverflow(input, input);
EmitLoopSinglePredecessorBlock()
void v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::EmitLoopSinglePredecessorBlock (maglev::BasicBlock * maglev_loop_header) [inline]
Definition at line 863 of file turbolev-graph-builder.cc.
                                                                            {
    DCHECK(maglev_loop_header->is_loop());
    bool has_special_generator_handling = false;
    V<Word32> switch_var_first_input;
    if (pre_loop_generator_blocks_.contains(maglev_loop_header)) {
      // This loop header used to be bypassed by generator resume edges. It will
      // now act as a secondary switch for the generator resumes.
      std::vector<GeneratorSplitEdge>& generator_preds =
          pre_loop_generator_blocks_[maglev_loop_header];
      // {generator_preds} contains all of the edges that were bypassing this
      // loop header. Rather than adding that many predecessors to the loop
      // header, will create a single predecessor, {pred_for_generator}, to
      // which all of the edges of {generator_preds} will go.
      Block* pred_for_generator = __ NewBlock();
      for (GeneratorSplitEdge pred : generator_preds) {
        __ Bind(pred.pre_loop_dst);
        __ SetVariable(header_switch_input_,
                       __ Word32Constant(pred.switch_value));
        __ Goto(pred_for_generator);
      }
      __ Bind(pred_for_generator);
      switch_var_first_input = __ GetVariable(header_switch_input_);
      DCHECK(switch_var_first_input.valid());
      BuildJump(maglev_loop_header);
      has_special_generator_handling = true;
      on_generator_switch_loop_ = true;
    }
    DCHECK(loop_single_edge_predecessors_.contains(maglev_loop_header));
    Block* loop_pred = loop_single_edge_predecessors_[maglev_loop_header];
    __ Bind(loop_pred);
    if (maglev_loop_header->has_phi()) {
      ComputePredecessorPermutations(maglev_loop_header, loop_pred, true,
                                     has_special_generator_handling);
      // Now we need to emit Phis (one per loop phi in {block}, which should
      // contain the same input except for the backedge).
      loop_phis_first_input_.clear();
      loop_phis_first_input_index_ = 0;
      for (maglev::Phi* phi : *maglev_loop_header->phis()) {
        constexpr int kSkipBackedge = 1;
        int input_count = phi->input_count() - kSkipBackedge;
        if (has_special_generator_handling) {
          // Adding an input to the Phis to account for the additional
          // generator-related predecessor.
          V<Any> additional_input;
          switch (phi->value_representation()) {
            case maglev::ValueRepresentation::kTagged:
              additional_input = dummy_object_input_;
              break;
            case maglev::ValueRepresentation::kInt32:
            case maglev::ValueRepresentation::kUint32:
              additional_input = dummy_word32_input_;
              break;
            case maglev::ValueRepresentation::kFloat64:
            case maglev::ValueRepresentation::kHoleyFloat64:
              additional_input = dummy_float64_input_;
              break;
            case maglev::ValueRepresentation::kIntPtr:
              // Maglev doesn't have IntPtr Phis.
              UNREACHABLE();
          }
          loop_phis_first_input_.push_back(
              MakePhiMaybePermuteInputs(phi, input_count, additional_input));
        } else {
          loop_phis_first_input_.push_back(
              MakePhiMaybePermuteInputs(phi, input_count));
        }
      }
    }
    if (has_special_generator_handling) {
      // We now emit the Phi that will be used in the loop's main switch.
      base::SmallVector<OpIndex, 16> inputs;
      constexpr int kSkipGeneratorPredecessor = 1;
      // We insert a default input for all of the non-generator predecessor.
      int input_count_without_generator =
          loop_pred->PredecessorCount() - kSkipGeneratorPredecessor;
      DCHECK(loop_default_generator_value_.valid());
      inputs.insert(inputs.begin(), input_count_without_generator,
                    loop_default_generator_value_);
      // And we insert the "true" input for the generator predecessor (which is
      // {pred_for_generator} above).
      DCHECK(switch_var_first_input.valid());
      inputs.push_back(switch_var_first_input);
      __ SetVariable(
          header_switch_input_,
          __ Phi(base::VectorOf(inputs), RegisterRepresentation::Word32()));
    }
    // Actually jumping to the loop.
    __ Goto(Map(maglev_loop_header));
  }
References __, v8::base::SmallVector< T, kSize, Allocator >::begin(), BuildJump(), ComputePredecessorPermutations(), v8::internal::DCHECK(), dummy_float64_input_, dummy_object_input_, dummy_word32_input_, v8::internal::maglev::BasicBlock::has_phi(), header_switch_input_, v8::internal::compiler::turboshaft::detail::input_count(), v8::base::SmallVector< T, kSize, Allocator >::insert(), v8::internal::maglev::BasicBlock::is_loop(), v8::internal::maglev::kFloat64, v8::internal::maglev::kHoleyFloat64, v8::internal::maglev::kInt32, v8::internal::maglev::kIntPtr, v8::internal::maglev::kTagged, v8::internal::maglev::kUint32, loop_default_generator_value_, loop_phis_first_input_, loop_phis_first_input_index_, loop_single_edge_predecessors_, MakePhiMaybePermuteInputs(), Map(), on_generator_switch_loop_, v8::internal::maglev::BasicBlock::phis(), pre_loop_generator_blocks_, v8::internal::compiler::turboshaft::Block::PredecessorCount(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), v8::internal::UNREACHABLE(), v8::internal::compiler::turboshaft::OpIndex::valid(), v8::base::VectorOf(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word32().
Referenced by PreProcessBasicBlock().
FixLoopPhis()
void v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::FixLoopPhis (maglev::BasicBlock * loop) [inline], [private]
Definition at line 5744 of file turbolev-graph-builder.cc.
                                           {
    DCHECK(loop->is_loop());
    if (!loop->has_phi()) return;
    for (maglev::Phi* maglev_phi : *loop->phis()) {
      // Note that we've already emited the backedge Goto, which means that
      // we're currently not in a block, which means that we need to pass
      // can_be_invalid=false to `Map`, otherwise it will think that we're
      // currently emitting unreachable operations and return
      // OpIndex::Invalid().
      constexpr bool kIndexCanBeInvalid = false;
      OpIndex phi_index = Map(maglev_phi, kIndexCanBeInvalid);
      PendingLoopPhiOp& pending_phi =
          __ output_graph().Get(phi_index).Cast<PendingLoopPhiOp>();
      __ output_graph().Replace<PhiOp>(
          phi_index,
          base::VectorOf(
              {pending_phi.first(),
               Map(maglev_phi -> backedge_input(), kIndexCanBeInvalid)}),
Referenced by Process().
Float64ToBit()
V<Word32> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Float64ToBit (V< Float64 > input) [inline], [private]
Definition at line 5829 of file turbolev-graph-builder.cc.
                                           {
Referenced by Process().
Float64ToTagged()
V<Number> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Float64ToTagged (V< Float64 > input, maglev::Float64ToTagged::ConversionMode conversion_mode) [inline], [private]
Definition at line 5683 of file turbolev-graph-builder.cc.
                                                           {
    // Float64ToTagged's conversion mode is used to control whether integer
    // floats should be converted to Smis or to HeapNumbers: kCanonicalizeSmi
    // means that they can be converted to Smis, and otherwise they should
    // remain HeapNumbers.
    ConvertUntaggedToJSPrimitiveOp::JSPrimitiveKind kind =
        conversion_mode ==
                maglev::Float64ToTagged::ConversionMode::kCanonicalizeSmi
            ? ConvertUntaggedToJSPrimitiveOp::JSPrimitiveKind::kNumber
            : ConvertUntaggedToJSPrimitiveOp::JSPrimitiveKind::kHeapNumber;
    return V<Number>::Cast(__ ConvertUntaggedToJSPrimitive(
        input, kind, RegisterRepresentation::Float64(),
Referenced by InsertTaggingForPhis().
Float64ToUint8Clamped()
V<Word32> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Float64ToUint8Clamped (V< Float64 > value) [inline]
Definition at line 4626 of file turbolev-graph-builder.cc.
                                                    {
    ScopedVar<Word32, AssemblerT> result(this);
    IF (__ Float64LessThan(value, kMinClampedUint8)) {
      result = __ Word32Constant(kMinClampedUint8);
    } ELSE IF (__ Float64LessThan(kMaxClampedUint8, value)) {
      result = __ Word32Constant(kMaxClampedUint8);
    } ELSE {
      // Note that this case handles values that are in range of Clamped Uint8
      // and NaN. The order of the IF/ELSE-IF/ELSE in this function is so that
      // we do indeed end up here for NaN.
      result = __ JSTruncateFloat64ToWord32(__ Float64RoundTiesEven(value));
GenerateBuiltinCall()
V<Any> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::GenerateBuiltinCall (maglev::NodeBase * node, Builtin builtin, OptionalV< FrameState > frame_state, base::Vector< const OpIndex > arguments, std::optional< int > stack_arg_count = std::nullopt) [inline]
Definition at line 1432 of file turbolev-graph-builder.cc.
                                                     {
    ThrowingScope throwing_scope(this, node);
    DCHECK(!TooManyArgumentsForCall(arguments.size()));
    Callable callable = Builtins::CallableFor(isolate_, builtin);
    const CallInterfaceDescriptor& descriptor = callable.descriptor();
    CallDescriptor* call_descriptor = Linkage::GetStubCallDescriptor(
        graph_zone(), descriptor,
        stack_arg_count.has_value() ? stack_arg_count.value()
                                    : descriptor.GetStackParameterCount(),
        frame_state.valid() ? CallDescriptor::kNeedsFrameState
                            : CallDescriptor::kNoFlags);
    V<Code> stub_code = __ HeapConstant(callable.code());
    LazyDeoptOnThrow lazy_deopt_on_throw = ShouldLazyDeoptOnThrow(node);
    return __ Call(stub_code, frame_state, base::VectorOf(arguments),
                   TSCallDescriptor::Create(call_descriptor, CanThrow::kYes,
                                            lazy_deopt_on_throw, graph_zone()));
  }
References __, v8::internal::Builtins::CallableFor(), v8::internal::Callable::code(), v8::internal::compiler::turboshaft::TSCallDescriptor::Create(), v8::internal::DCHECK(), v8::internal::Callable::descriptor(), v8::internal::CallInterfaceDescriptor::GetStackParameterCount(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), graph_zone(), isolate_, v8::internal::compiler::CallDescriptor::kNeedsFrameState, v8::internal::compiler::CallDescriptor::kNoFlags, v8::internal::compiler::kYes, ShouldLazyDeoptOnThrow(), v8::base::Vector< T >::size(), v8::internal::compiler::turboshaft::TooManyArgumentsForCall(), v8::internal::compiler::turboshaft::OptionalOpIndex::valid(), and v8::base::VectorOf().
Referenced by Process().
GetSharedFunctionInfo()
SharedFunctionInfoRef v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::GetSharedFunctionInfo (const maglev::DeoptFrame & deopt_frame) [inline], [private]
Definition at line 5508 of file turbolev-graph-builder.cc.
                                           {
    switch (deopt_frame.type()) {
      case maglev::DeoptFrame::FrameType::kInterpretedFrame:
        return deopt_frame.as_interpreted().unit().shared_function_info();
      case maglev::DeoptFrame::FrameType::kInlinedArgumentsFrame:
        return deopt_frame.as_inlined_arguments().unit().shared_function_info();
      case maglev::DeoptFrame::FrameType::kConstructInvokeStubFrame:
        return deopt_frame.as_construct_stub().unit().shared_function_info();
      case maglev::DeoptFrame::FrameType::kBuiltinContinuationFrame:
        return GetSharedFunctionInfo(*deopt_frame.parent());
GetTypedArrayDataAndBasePointers()
std::pair<V<WordPtr>, V<Object> > v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::GetTypedArrayDataAndBasePointers (V< JSTypedArray > typed_array) [inline], [private]
Definition at line 5633 of file turbolev-graph-builder.cc.
                                   {
    V<WordPtr> data_pointer = __ LoadField<WordPtr>(
        typed_array, AccessBuilder::ForJSTypedArrayExternalPointer());
    V<Object> base_pointer = __ LoadField<Object>(
graph_zone()
Zone* v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::graph_zone () [inline]
Definition at line 4897 of file turbolev-graph-builder.cc.
{ return assembler_; }
References assembler_.
Referenced by GenerateBuiltinCall(), and Process().
HoleyFloat64ToTagged()
V<NumberOrUndefined> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::HoleyFloat64ToTagged (V< Float64 > input, maglev::HoleyFloat64ToTagged::ConversionMode conversion_mode) [inline], [private]
Definition at line 5701 of file turbolev-graph-builder.cc.
                                                                {
    Label<NumberOrUndefined> done(this);
    if (conversion_mode ==
        maglev::HoleyFloat64ToTagged::ConversionMode::kCanonicalizeSmi) {
      // ConvertUntaggedToJSPrimitive cannot at the same time canonicalize smis
      // and handle holes. We thus manually insert a smi check when the
      // conversion_mode is CanonicalizeSmi.
      IF (__ Float64IsSmi(input)) {
        V<Word32> as_int32 = __ TruncateFloat64ToInt32OverflowUndefined(input);
        V<Smi> as_smi = V<Smi>::Cast(__ ConvertUntaggedToJSPrimitive(
            as_int32, ConvertUntaggedToJSPrimitiveOp::JSPrimitiveKind::kSmi,
            RegisterRepresentation::Word32(),
            ConvertUntaggedToJSPrimitiveOp::InputInterpretation::kSigned,
            CheckForMinusZeroMode::kDontCheckForMinusZero));
        GOTO(done, as_smi);
      }
    }
    V<NumberOrUndefined> as_obj =
        V<NumberOrUndefined>::Cast(__ ConvertUntaggedToJSPrimitive(
            input,
            ConvertUntaggedToJSPrimitiveOp::JSPrimitiveKind::
                kHeapNumberOrUndefined,
            RegisterRepresentation::Float64(),
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
            ConvertUntaggedToJSPrimitiveOp::InputInterpretation::
                kDoubleOrUndefinedOrHole,
#else
            ConvertUntaggedToJSPrimitiveOp::InputInterpretation::kDoubleOrHole,
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
            CheckForMinusZeroMode::kCheckForMinusZero));
    if (done.has_incoming_jump()) {
      GOTO(done, as_obj);
      BIND(done, result);
      return result;
    } else {
      // Avoid creating a new block if {as_obj} is the only possible return
      // value.
Referenced by InsertTaggingForPhis().
InsertTaggingForPhis()
void v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::InsertTaggingForPhis (maglev::BasicBlock * maglev_catch_handler) [inline]
Definition at line 766 of file turbolev-graph-builder.cc.
                                                                    {
    DCHECK(maglev_catch_handler->has_phi());
    IterCatchHandlerPhis(maglev_catch_handler, [&](interpreter::Register owner,
                                                   Variable var) {
      DCHECK_NE(owner, interpreter::Register::virtual_accumulator());
      V<Any> ts_idx = __ GetVariable(var);
      DCHECK(maglev_representations_.contains(ts_idx));
      switch (maglev_representations_[ts_idx]) {
        case maglev::ValueRepresentation::kTagged:
          // Already tagged, nothing to do.
          break;
        case maglev::ValueRepresentation::kInt32:
          __ SetVariable(var, __ ConvertInt32ToNumber(V<Word32>::Cast(ts_idx)));
          break;
        case maglev::ValueRepresentation::kUint32:
          __ SetVariable(var,
                         __ ConvertUint32ToNumber(V<Word32>::Cast(ts_idx)));
          break;
        case maglev::ValueRepresentation::kFloat64:
          __ SetVariable(
              var,
              Float64ToTagged(
                  V<Float64>::Cast(ts_idx),
                  maglev::Float64ToTagged::ConversionMode::kCanonicalizeSmi));
          break;
        case maglev::ValueRepresentation::kHoleyFloat64:
          __ SetVariable(
              var, HoleyFloat64ToTagged(V<Float64>::Cast(ts_idx),
                                        maglev::HoleyFloat64ToTagged::
                                            ConversionMode::kCanonicalizeSmi));
          break;
        case maglev::ValueRepresentation::kIntPtr:
          __ SetVariable(var,
                         __ ConvertIntPtrToNumber(V<WordPtr>::Cast(ts_idx)));
      }
    });
  }
References __, v8::internal::DCHECK(), DCHECK_NE, Float64ToTagged(), v8::internal::maglev::BasicBlock::has_phi(), HoleyFloat64ToTagged(), IterCatchHandlerPhis(), v8::internal::maglev::Float64ToTagged::kCanonicalizeSmi, v8::internal::maglev::kFloat64, v8::internal::maglev::kHoleyFloat64, v8::internal::maglev::kInt32, v8::internal::maglev::kIntPtr, v8::internal::maglev::kTagged, v8::internal::maglev::kUint32, maglev_representations_, and v8::internal::interpreter::Register::virtual_accumulator().
Referenced by StartSinglePredecessorExceptionBlock(), and TagExceptionPhiInputsForBlock().
Int32ToUint8Clamped()
V<Word32> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Int32ToUint8Clamped (V< Word32 > value) [inline]
Definition at line 4615 of file turbolev-graph-builder.cc.
                                                 {
    ScopedVar<Word32, AssemblerT> result(this);
    IF (__ Int32LessThan(value, kMinClampedUint8)) {
      result = __ Word32Constant(kMinClampedUint8);
    } ELSE IF (__ Int32LessThan(value, kMaxClampedUint8)) {
      result = value;
    } ELSE {
      result = __ Word32Constant(kMaxClampedUint8);
References __, kMaxClampedUint8, kMinClampedUint8, v8::base::internal::result, and v8::internal::value.
IsMaglevMainGeneratorSwitchBlock()
bool v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::IsMaglevMainGeneratorSwitchBlock (const maglev::BasicBlock * maglev_block) [inline]
Definition at line 573 of file turbolev-graph-builder.cc.
                                            {
    if (!generator_analyzer_.has_header_bypasses()) return false;
    constexpr int kMainSwitchBlockId = 2;
    bool is_main_switch_block = maglev_block->id() == kMainSwitchBlockId;
    DCHECK_IMPLIES(is_main_switch_block,
                   maglev_block->control_node()->Is<maglev::Switch>());
    return is_main_switch_block;
  }
References v8::internal::maglev::BasicBlock::control_node(), DCHECK_IMPLIES, generator_analyzer_, v8::internal::compiler::turboshaft::GeneratorAnalyzer::has_header_bypasses(), v8::internal::maglev::BasicBlock::id(), and v8::internal::maglev::NodeBase::Is().
Referenced by PreProcessBasicBlock().
IsMapped()
bool v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::IsMapped (const maglev::NodeBase * node) const [inline]
Definition at line 4899 of file turbolev-graph-builder.cc.
                    { return temp_zone_; }
  Zone* graph_zone() { return Asm().output_graph().graph_zone(); }
  bool IsMapped(const maglev::NodeBase* node) const {
    if (V8_UNLIKELY(node == maglev_generator_context_node_)) {
      return true;
References temp_zone_.
IterCatchHandlerPhis()
template<typename Function >
void v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::IterCatchHandlerPhis (const maglev::BasicBlock * catch_block, Function && callback) [inline], [private]
Definition at line 5955 of file turbolev-graph-builder.cc.
                                                 {
    DCHECK_NOT_NULL(catch_block);
    DCHECK(catch_block->has_phi());
    for (auto phi : *catch_block->phis()) {
      DCHECK(phi->is_exception_phi());
      interpreter::Register owner = phi->owner();
      if (owner == interpreter::Register::virtual_accumulator()) {
        // The accumulator exception phi corresponds to the exception object
        // rather than whatever value the accumulator contained before the
        // throwing operation. We don't need to iterate here, since there is
        // special handling when processing Phis to use `catch_block_begin_`
        // for it instead of a Variable.
        continue;
      }
      auto it = regs_to_vars_.find(owner.index());
      Variable var;
      if (it == regs_to_vars_.end()) {
        // We use a LoopInvariantVariable: if loop phis were needed, then the
        // Maglev value would already be a loop Phi, and we wouldn't need
        // Turboshaft to automatically insert a loop phi.
        var = __ NewLoopInvariantVariable(RegisterRepresentation::Tagged());
        regs_to_vars_.insert({owner.index(), var});
      } else {
        var = it->second;
      }
Referenced by InsertTaggingForPhis().
MakeFrameStateInfo() [1/4]
const FrameStateInfo* v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::MakeFrameStateInfo (maglev::BuiltinContinuationDeoptFrame & maglev_frame) [inline], [private]
Definition at line 5480 of file turbolev-graph-builder.cc.
                                                         {
    FrameStateType type = maglev_frame.is_javascript()
                              ? FrameStateType::kJavaScriptBuiltinContinuation
                              : FrameStateType::kBuiltinContinuation;
    uint16_t parameter_count =
        static_cast<uint16_t>(maglev_frame.parameters().length());
    if (maglev_frame.is_javascript()) {
      constexpr int kExtraFixedJSFrameParameters =
          V8_JS_LINKAGE_INCLUDES_DISPATCH_HANDLE_BOOL ? 4 : 3;
      DCHECK_EQ(Builtins::CallInterfaceDescriptorFor(maglev_frame.builtin_id())
                    .GetRegisterParameterCount(),
                kExtraFixedJSFrameParameters);
      parameter_count += kExtraFixedJSFrameParameters;
    }
    Handle<SharedFunctionInfo> shared_info =
        GetSharedFunctionInfo(maglev_frame).object();
    constexpr int kLocalCount = 0;
    constexpr uint16_t kMaxArguments = 0;
    FrameStateFunctionInfo* info = graph_zone()->New<FrameStateFunctionInfo>(
        type, parameter_count, kMaxArguments, kLocalCount, shared_info,
        kNullMaybeHandle);
    return graph_zone()->New<FrameStateInfo>(
MakeFrameStateInfo() [2/4]
const FrameStateInfo* v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::MakeFrameStateInfo (maglev::ConstructInvokeStubDeoptFrame & maglev_frame) [inline], [private]
Definition at line 5462 of file turbolev-graph-builder.cc.
                                                         {
    FrameStateType type = FrameStateType::kConstructInvokeStub;
    Handle<SharedFunctionInfo> shared_info =
        maglev_frame.unit().shared_function_info().object();
    Handle<BytecodeArray> bytecode_array =
        maglev_frame.unit().bytecode().object();
    constexpr uint16_t kParameterCount = 1; // Only 1 parameter: the receiver.
    constexpr uint16_t kMaxArguments = 0;
    constexpr int kLocalCount = 0;
    FrameStateFunctionInfo* info = graph_zone()->New<FrameStateFunctionInfo>(
        type, kParameterCount, kMaxArguments, kLocalCount, shared_info,
        bytecode_array);
MakeFrameStateInfo() [3/4]
const FrameStateInfo* v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::MakeFrameStateInfo (maglev::InlinedArgumentsDeoptFrame & maglev_frame) [inline], [private]
Definition at line 5442 of file turbolev-graph-builder.cc.
                                                      {
    FrameStateType type = FrameStateType::kInlinedExtraArguments;
    uint16_t parameter_count =
        static_cast<uint16_t>(maglev_frame.arguments().size());
    uint16_t max_arguments = 0;
    int local_count = 0;
    Handle<SharedFunctionInfo> shared_info =
        maglev_frame.unit().shared_function_info().object();
    Handle<BytecodeArray> bytecode_array =
        maglev_frame.unit().bytecode().object();
    FrameStateFunctionInfo* info = graph_zone()->New<FrameStateFunctionInfo>(
        type, parameter_count, max_arguments, local_count, shared_info,
        bytecode_array);
    return graph_zone()->New<FrameStateInfo>(maglev_frame.bytecode_position(),
MakeFrameStateInfo() [4/4]
const FrameStateInfo* v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::MakeFrameStateInfo (maglev::InterpretedDeoptFrame & maglev_frame, OutputFrameStateCombine combine) [inline], [private]
Definition at line 5423 of file turbolev-graph-builder.cc.
                                       {
    FrameStateType type = FrameStateType::kUnoptimizedFunction;
    uint16_t parameter_count = maglev_frame.unit().parameter_count();
    uint16_t max_arguments = maglev_frame.unit().max_arguments();
    int local_count = maglev_frame.unit().register_count();
    Handle<SharedFunctionInfo> shared_info =
        maglev_frame.unit().shared_function_info().object();
    Handle<BytecodeArray> bytecode_array =
        maglev_frame.unit().bytecode().object();
    FrameStateFunctionInfo* info = graph_zone()->New<FrameStateFunctionInfo>(
        type, parameter_count, max_arguments, local_count, shared_info,
        bytecode_array);
MakePhiMaybePermuteInputs()
V<Any> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::MakePhiMaybePermuteInputs (maglev::ValueNode * maglev_node, int maglev_input_count, OptionalV< Any > additional_input = OptionalV<Any>::Nullopt()) [inline]
Definition at line 1228 of file turbolev-graph-builder.cc.
                                                                 {
    DCHECK(!predecessor_permutation_.empty());
    base::SmallVector<OpIndex, 16> inputs;
    // Note that it's important to use `current_block()->PredecessorCount()` as
    // the size of {inputs}, because some Maglev predecessors could have been
    // dropped by Turboshaft during the translation (and thus, `input_count`
    // might be too much).
    inputs.resize(__ current_block()->PredecessorCount(), {});
    for (int i = 0; i < maglev_input_count; ++i) {
      if (predecessor_permutation_[i] != Block::kInvalidPredecessorIndex) {
        inputs[predecessor_permutation_[i]] =
            MapPhiInput(maglev_node->input(i), predecessor_permutation_[i]);
      }
    }
    if (additional_input.has_value()) {
      // When a loop header was bypassed by a generator resume, we insert an
      // additional predecessor to the loop, and thus need an additional input
      // for the Phis.
      inputs[inputs.size() - 1] = additional_input.value();
    }
    return __ Phi(
        base::VectorOf(inputs),
        RegisterRepresentationFor(maglev_node->value_representation()));
  }
References __, v8::internal::DCHECK(), v8::base::SmallVector< T, kSize, Allocator >::empty(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::maglev::NodeBase::input(), v8::internal::compiler::turboshaft::Block::kInvalidPredecessorIndex, MapPhiInput(), predecessor_permutation_, RegisterRepresentationFor(), v8::base::SmallVector< T, kSize, Allocator >::resize(), v8::base::SmallVector< T, kSize, Allocator >::size(), v8::internal::maglev::ValueNode::value_representation(), and v8::base::VectorOf().
Referenced by EmitLoopSinglePredecessorBlock(), and Process().
Map() [1/4]
Block* v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Map (const maglev::BasicBlock * block) [inline], [private]
Definition at line 6029 of file turbolev-graph-builder.cc.
Map() [2/4]
template<typename T >
V<T> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Map (const maglev::Input input, bool can_be_invalid = true) [inline], [private]
Definition at line 6008 of file turbolev-graph-builder.cc.
Referenced by BuildJump(), EmitLoopSinglePredecessorBlock(), PreProcessBasicBlock(), Process(), and StartExceptionBlock().
Map() [3/4]
OpIndex v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Map (const maglev::Input input, bool can_be_invalid = true) [inline], [private]
Definition at line 6011 of file turbolev-graph-builder.cc.
                                                                {
    return V<T>::Cast(Map(input.node(), can_be_invalid));
  }
References v8::internal::compiler::turboshaft::V< T >::Cast(), v8::internal::compiler::Map, and v8::internal::maglev::Input::node().
Map() [4/4]
OpIndex v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Map (const maglev::NodeBase * node, bool can_be_invalid = true) [inline], [private]
Definition at line 6014 of file turbolev-graph-builder.cc.
                                                                   {
    return Map(input.node(), can_be_invalid);
  }
  OpIndex Map(const maglev::NodeBase* node, bool can_be_invalid = true) {
    // If {can_be_invalid} is true (which it should be in most cases) and we're
    // currently in unreachable code, then `OpIndex::Invalid` is returned. The
    // only case where `can_be_invalid` is false is FixLoopPhis: this is called
    // after having emitted the backedge Goto, which means that we are in
    // unreachable code, but we know that the mappings should still exist.
    if (can_be_invalid && __ generating_unreachable_operations()) {
      return OpIndex::Invalid();
    }
    if (V8_UNLIKELY(node == maglev_generator_context_node_)) {
      return __ GetVariable(generator_context_);
    }
References v8::internal::compiler::Map, and v8::internal::maglev::Input::node().
MapPhiInput() [1/2]
OpIndex v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::MapPhiInput (const maglev::Input input, int input_index) [inline], [private]
Definition at line 5987 of file turbolev-graph-builder.cc.
Referenced by MakePhiMaybePermuteInputs().
MapPhiInput() [2/2]
OpIndex v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::MapPhiInput (const maglev::NodeBase * node, int input_index) [inline], [private]
Definition at line 5990 of file turbolev-graph-builder.cc.
                                                                {
    return MapPhiInput(input.node(), input_index);
  }
  OpIndex MapPhiInput(const maglev::NodeBase* node, int input_index) {
    if (V8_UNLIKELY(node == maglev_generator_context_node_)) {
      OpIndex generator_context = __ GetVariable(generator_context_);
      if (__ current_block()->Contains(generator_context)) {
        DCHECK(!__ current_block()->IsLoop());
        DCHECK(__ output_graph().Get(generator_context).Is<PhiOp>());
        // If {generator_context} is a Phi defined in the current block and it's
        // used as input for another Phi, then we need to use it's value from
        // the correct predecessor, since a Phi can't be an input to another Phi
        // in the same block.
        return __ GetPredecessorValue(generator_context_, input_index);
      }
      return generator_context;
References v8::internal::maglev::Input::node().
native_context()
V<NativeContext> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::native_context () [inline], [private]
Definition at line 6061 of file turbolev-graph-builder.cc.
                                    {
Referenced by Process(), and StringConcatHelper().
PostPhiProcessing()
void v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::PostPhiProcessing () [inline]
Definition at line 967 of file turbolev-graph-builder.cc.
                           {
    // Loop headers that are bypassed because of generators need to be turned
    // into secondary generator switches (so as to not be bypassed anymore).
    // Concretely, we split the loop headers in half by inserting a Switch right
    // after the loop phis have been emitted. Here is a visual representation of
    // what's happening:
    //
    // Before:
    //
    // | ----------------------------
    // | | |
    // | | |
    // v v |
    // +------------------------+ |
    // | phi_1(...) | |
    // | ... | |
    // | phi_k(...) | |
    // | <some op 1> | |
    // | ... | |
    // | <some op n> | |
    // | Branch | |
    // +------------------------+ |
    // | |
    // | |
    // v |
    //
    //
    // After:
    //
    //
    // | -----------------------------------
    // | | |
    // | | |
    // v v |
    // +------------------------+ |
    // | phi_1(...) | |
    // | ... | |
    // | phi_k(...) | |
    // | Switch | |
    // +------------------------+ |
    // / | | \ |
    // / | | \ |
    // / | | \ |
    // v v v v |
    // +------------------+ |
    // | <some op 1> | |
    // | ... | |
    // | <some op n> | |
    // | Branch | |
    // +------------------+ |
    // | |
    // | |
    // v |
    //
    //
    // Since `PostPhiProcessing` is called right after all phis have been
    // emitted, now is thus the time to split the loop header.
    if (on_generator_switch_loop_) {
      const maglev::BasicBlock* maglev_loop_header = __ maglev_input_block();
      DCHECK(maglev_loop_header->is_loop());
      std::vector<GeneratorSplitEdge>& generator_preds =
          pre_loop_generator_blocks_[maglev_loop_header];
      compiler::turboshaft::SwitchOp::Case* cases =
          __ output_graph().graph_zone()
              -> AllocateArray<compiler::turboshaft::SwitchOp::Case>(
                               generator_preds.size());
      for (int i = 0; static_cast<unsigned int>(i) < generator_preds.size();
           i++) {
        GeneratorSplitEdge pred = generator_preds[i];
        cases[i] = {pred.switch_value, pred.inside_loop_target,
                    BranchHint::kNone};
      }
      Block* default_block = __ NewBlock();
      __ Switch(__ GetVariable(header_switch_input_),
                base::VectorOf(cases, generator_preds.size()), default_block);
      // We now bind {default_block}. It will contain the rest of the loop
      // header. The MaglevGraphProcessor will continue to visit the header's
      // body as if nothing happened.
      __ Bind(default_block);
    }
    on_generator_switch_loop_ = false;
  }
References __, v8::internal::DCHECK(), header_switch_input_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::GeneratorSplitEdge::inside_loop_target, v8::internal::maglev::BasicBlock::is_loop(), v8::internal::kNone, on_generator_switch_loop_, pre_loop_generator_blocks_, v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::GeneratorSplitEdge::switch_value, and v8::base::VectorOf().
PostProcessBasicBlock()
void v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::PostProcessBasicBlock (maglev::BasicBlock * maglev_block) [inline]
Definition at line 583 of file turbolev-graph-builder.cc.
{}
PostProcessGraph()
void v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::PostProcessGraph (maglev::Graph * graph) [inline]
Definition at line 556 of file turbolev-graph-builder.cc.
                                            {
    // It can happen that some Maglev loops don't actually loop (the backedge
    // isn't actually reachable). We can't know this when emitting the header in
    // Turboshaft, which means that we still emit the header, but then we never
    // come around to calling FixLoopPhis on it. So, once we've generated the
    // whole Turboshaft graph, we go over all loop headers, and if some turn out
    // to not be headers, we turn them into regular merge blocks (and patch
    // their PendingLoopPhis).
    for (Block& block : __ output_graph().blocks()) {
      if (block.IsLoop() && block.PredecessorCount() == 1) {
        __ output_graph().TurnLoopIntoMerge(&block);
      }
    }
  }
References __.
PreProcessBasicBlock()
maglev::BlockProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::PreProcessBasicBlock (maglev::BasicBlock * maglev_block) [inline]
Definition at line 584 of file turbolev-graph-builder.cc.
                                      {
    // Note that it's important to call SetMaglevInputBlock before calling Bind,
    // so that BlockOriginTrackingReducer::Bind records the correct predecessor
    // for the current block.
    __ SetMaglevInputBlock(maglev_block);
    is_visiting_generator_main_switch_ =
        IsMaglevMainGeneratorSwitchBlock(maglev_block);
    Block* turboshaft_block = Map(maglev_block);
    if (__ current_block() != nullptr) {
      // The first block for Constants doesn't end with a Jump, so we add one
      // now.
      __ Goto(turboshaft_block);
    }
#ifdef DEBUG
    loop_phis_first_input_.clear();
    loop_phis_first_input_index_ = -1;
    catch_block_begin_ = V<Object>::Invalid();
#endif
    if (maglev_block->is_loop() &&
        (loop_single_edge_predecessors_.contains(maglev_block) ||
         pre_loop_generator_blocks_.contains(maglev_block))) {
      EmitLoopSinglePredecessorBlock(maglev_block);
    }
    if (maglev_block->is_exception_handler_block()) {
      StartExceptionBlock(maglev_block);
      return maglev::BlockProcessResult::kContinue;
    }
    // SetMaglevInputBlock should have been called before calling Bind, and the
    // current `maglev_input_block` should thus already be `maglev_block`.
    DCHECK_EQ(__ maglev_input_block(), maglev_block);
    if (!__ Bind(turboshaft_block)) {
      // The current block is not reachable.
      return maglev::BlockProcessResult::kContinue;
    }
    if (maglev_block->is_loop()) {
      // The "permutation" stuff that comes afterwards in this function doesn't
      // apply to loops, since loops always have 2 predecessors in Turboshaft,
      // and in both Turboshaft and Maglev, the backedge is always the last
      // predecessors, so we never need to reorder phi inputs.
      return maglev::BlockProcessResult::kContinue;
    } else if (maglev_block->is_exception_handler_block()) {
      // We need to emit the CatchBlockBegin at the begining of this block. Note
      // that if this block has multiple predecessors (because multiple throwing
      // operations are caught by the same catch handler), then edge splitting
      // will have already created CatchBlockBegin operations in the
      // predecessors, and calling `__ CatchBlockBegin` now will actually only
      // emit a Phi of the CatchBlockBegin of the predecessors (which is exactly
      // what we want). See the comment above CatchBlockBegin in
      // TurboshaftAssemblerOpInterface.
      catch_block_begin_ = __ CatchBlockBegin();
    }
    // Because of edge splitting in Maglev (which happens on Bind rather than on
    // Goto), predecessors in the Maglev graph are not always ordered by their
    // position in the graph (ie, block 4 could be the second predecessor and
    // block 5 the first one). However, since we're processing the graph "in
    // order" (because that's how the maglev GraphProcessor works), predecessors
    // in the Turboshaft graph will be ordered by their position in the graph.
    // Additionally, optimizations during the translation (like constant folding
    // by MachineOptimizationReducer) could change control flow and remove
    // predecessors (by changing a Branch into a Goto for instance).
    // We thus compute in {predecessor_permutation_} a map from Maglev
    // predecessor index to Turboshaft predecessor index, and we'll use this
    // later when emitting Phis to reorder their inputs.
    predecessor_permutation_.clear();
    if (maglev_block->has_phi() &&
        // We ignore this for exception phis since they have no inputs in Maglev
        // anyways, and in Turboshaft we rely on {regs_to_vars_} to populate
        // their inputs (and also, Maglev exception blocks have no
        // predecessors).
        !maglev_block->is_exception_handler_block()) {
      ComputePredecessorPermutations(maglev_block, turboshaft_block, false,
                                     false);
    }
    return maglev::BlockProcessResult::kContinue;
  }
References __, catch_block_begin_, v8::base::SmallVector< T, kSize, Allocator >::clear(), ComputePredecessorPermutations(), DCHECK_EQ, EmitLoopSinglePredecessorBlock(), v8::internal::maglev::BasicBlock::has_phi(), v8::internal::compiler::turboshaft::V< T >::Invalid(), v8::internal::maglev::BasicBlock::is_exception_handler_block(), v8::internal::maglev::BasicBlock::is_loop(), is_visiting_generator_main_switch_, IsMaglevMainGeneratorSwitchBlock(), v8::internal::maglev::kContinue, loop_phis_first_input_, loop_phis_first_input_index_, loop_single_edge_predecessors_, Map(), pre_loop_generator_blocks_, predecessor_permutation_, and StartExceptionBlock().
PreProcessGraph()
void v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::PreProcessGraph (maglev::Graph * graph) [inline]
Definition at line 506 of file turbolev-graph-builder.cc.
                                           {
    for (maglev::BasicBlock* block : *graph) {
      block_mapping_[block] =
          block->is_loop() ? __ NewLoopHeader() : __ NewBlock();
    }
    // Constants are not in a block in Maglev but are in Turboshaft. We bind a
    // block now, so that Constants can then be emitted.
    __ Bind(__ NewBlock());
    // Initializing undefined constant so that we don't need to recreate it too
    // often.
    undefined_value_ = __ HeapConstant(local_factory_->undefined_value());
    if (maglev_compilation_unit_->bytecode()
            .incoming_new_target_or_generator_register()
            .is_valid()) {
      // The Maglev graph might contain a RegisterInput for
      // kJavaScriptCallNewTargetRegister later in the graph, which in
      // Turboshaft is represented as a Parameter. We create this Parameter
      // here, because the Instruction Selector tends to be unhappy when
      // Parameters are defined late in the graph.
      int new_target_index = Linkage::GetJSCallNewTargetParamIndex(
          maglev_compilation_unit_->parameter_count());
      new_target_param_ = __ Parameter(
          new_target_index, RegisterRepresentation::Tagged(), "%new.target");
    }
    if (graph->has_resumable_generator()) {
      generator_analyzer_.Analyze(graph);
      dummy_object_input_ = __ SmiZeroConstant();
      dummy_word32_input_ = __ Word32Constant(0);
      dummy_float64_input_ = __ Float64Constant(0);
      header_switch_input_ = __ NewVariable(RegisterRepresentation::Word32());
      loop_default_generator_value_ = __ Word32Constant(kDefaultSwitchVarValue);
      generator_context_ =
          __ NewLoopInvariantVariable(RegisterRepresentation::Tagged());
      __ SetVariable(generator_context_, __ NoContextConstant());
    }
    // Maglev nodes often don't have the NativeContext as input, but instead
    // rely on the MaglevAssembler to provide it during code generation, unlike
    // Turboshaft nodes, which need the NativeContext as an explicit input if
    // they use it. We thus emit a single NativeContext constant here, which we
    // reuse later to construct Turboshaft nodes.
    native_context_ =
        __ HeapConstant(broker_->target_native_context().object());
  }
References __, v8::internal::compiler::turboshaft::GeneratorAnalyzer::Analyze(), block_mapping_, broker_, v8::internal::maglev::MaglevCompilationUnit::bytecode(), dummy_float64_input_, dummy_object_input_, dummy_word32_input_, generator_analyzer_, generator_context_, v8::internal::compiler::Linkage::GetJSCallNewTargetParamIndex(), graph(), header_switch_input_, v8::internal::compiler::BytecodeArrayRef::incoming_new_target_or_generator_register(), v8::internal::interpreter::Register::is_valid(), kDefaultSwitchVarValue, local_factory_, loop_default_generator_value_, maglev_compilation_unit_, native_context_, new_target_param_, v8::internal::compiler::NativeContextRef::object(), v8::internal::maglev::MaglevCompilationUnit::parameter_count(), v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), v8::internal::compiler::JSHeapBroker::target_native_context(), undefined_value_, and v8::internal::compiler::turboshaft::RegisterRepresentation::Word32().
Process() [1/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::Abort * node, const maglev::ProcessingState & state) [inline]
Definition at line 4748 of file turbolev-graph-builder.cc.
                                                                    {
    __ RuntimeAbort(node->reason());
    // TODO(dmercadier): remove this `Unreachable` once RuntimeAbort is marked
    // as a block terminator.
Process() [2/269]
template<typename T >
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::AbstractLoadTaggedField< T > * node, const maglev::ProcessingState & state) [inline]
Definition at line 2948 of file turbolev-graph-builder.cc.
                                                                    {
    V<Object> value =
        __ LoadTaggedField(Map(node->object_input()), node->offset());
    SetMap(node, value);
    if (generator_analyzer_.has_header_bypasses() &&
        maglev_generator_context_node_ == nullptr &&
        node->object_input().node()->template Is<maglev::RegisterInput>() &&
        node->offset() == JSGeneratorObject::kContextOffset) {
      // This is loading the context of a generator for the 1st time. We save it
      // in {generator_context_} for later use.
      __ SetVariable(generator_context_, value);
      maglev_generator_context_node_ = node;
    }
    return maglev::ProcessResult::kContinue;
  }
References __, generator_analyzer_, generator_context_, v8::internal::compiler::turboshaft::GeneratorAnalyzer::has_header_bypasses(), v8::internal::maglev::kContinue, maglev_generator_context_node_, Map(), v8::internal::maglev::Input::node(), v8::internal::maglev::AbstractLoadTaggedField< Derived >::object_input(), v8::internal::maglev::AbstractLoadTaggedField< Derived >::offset(), SetMap(), and v8::internal::value.
Process() [3/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::AllocateElementsArray * node, const maglev::ProcessingState & state) [inline]
Definition at line 2710 of file turbolev-graph-builder.cc.
                                                                    {
    V<Word32> length = Map(node->length_input());
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    // Note that {length} cannot be negative (Maglev inserts a check before
    // AllocateElementsArray to ensure this).
    __ DeoptimizeIfNot(
        __ Uint32LessThan(length, JSArray::kInitialMaxFastElementArray),
        frame_state, DeoptimizeReason::kGreaterThanMaxFastElementArray,
        node->eager_deopt_info()->feedback_to_update());
    RETURN_IF_UNREACHABLE();
    SetMap(node,
           __ NewArray(__ ChangeUint32ToUintPtr(length),
                       NewArrayOp::Kind::kObject, node->allocation_type()));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::AllocateElementsArray::allocation_type(), GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::kContinue, v8::internal::JSArray::kInitialMaxFastElementArray, v8::internal::compiler::turboshaft::NewArrayOp::kObject, v8::internal::length, v8::internal::maglev::AllocateElementsArray::length_input(), Map(), v8::internal::NewArray(), RETURN_IF_UNREACHABLE, and SetMap().
Process() [4/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::AllocationBlock * node, const maglev::ProcessingState & state) [inline]
Definition at line 2603 of file turbolev-graph-builder.cc.
                                                                    {
    DCHECK(
        node->is_used()); // Should have been dead-code eliminated otherwise.
    int size = 0;
    for (auto alloc : node->allocation_list()) {
      if (!alloc->HasBeenAnalysed() || alloc->HasEscaped()) {
        alloc->set_offset(size);
        size += alloc->size();
      }
    }
    node->set_size(size);
    SetMap(node, __ FinishInitialization(__ Allocate<HeapObject>(
                     size, node->allocation_type(), kTaggedAligned)));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::AllocationBlock::allocation_list(), v8::internal::maglev::AllocationBlock::allocation_type(), v8::internal::DCHECK(), v8::internal::maglev::kContinue, v8::internal::kTaggedAligned, v8::internal::maglev::AllocationBlock::set_size(), SetMap(), and size().
Process() [5/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::ArgumentsElements * node, const maglev::ProcessingState & state) [inline]
Definition at line 2934 of file turbolev-graph-builder.cc.
                                                                    {
    SetMap(node, __ NewArgumentsElements(Map(node->arguments_count_input()),
                                         node->type(),
                                         node->formal_parameter_count()));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::ArgumentsElements::arguments_count_input(), v8::internal::maglev::ArgumentsElements::formal_parameter_count(), v8::internal::maglev::kContinue, Map(), SetMap(), and v8::internal::maglev::ArgumentsElements::type().
Process() [6/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::ArgumentsLength * node, const maglev::ProcessingState & state) [inline]
Definition at line 2925 of file turbolev-graph-builder.cc.
                                                                    {
    // TODO(dmercadier): ArgumentsLength in Maglev returns a raw Word32, while
    // in Turboshaft, it returns a Smi. We thus untag this Smi here to match
    // Maglev's behavior, but it would be more efficient to change Turboshaft's
    // ArgumentsLength operation to return a raw Word32 as well.
    SetMap(node, __ UntagSmi(__ ArgumentsLength()));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::kContinue, and SetMap().
Process() [7/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::AssertInt32 * node, const maglev::ProcessingState &) [inline]
Definition at line 4847 of file turbolev-graph-builder.cc.
                                                              {
    bool negate_result = false;
    V<Word32> cmp = ConvertInt32Compare(node->left_input(), node->right_input(),
                                        node->condition(), &negate_result);
    Label<> abort(this);
    Label<> end(this);
    if (negate_result) {
      GOTO_IF(cmp, abort);
    } else {
      GOTO_IF_NOT(cmp, abort);
    }
    GOTO(end);
    BIND(abort);
    __ RuntimeAbort(node->reason());
    __ Unreachable();
Process() [8/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::BranchIfFloat64Compare * node, const maglev::ProcessingState & state) [inline]
Definition at line 3656 of file turbolev-graph-builder.cc.
                                                                    {
    V<Word32> condition =
        ConvertCompare<Float64>(node->left_input(), node->right_input(),
                                node->operation(), Sign::kSigned);
    __ Branch(condition, Map(node->if_true()), Map(node->if_false()));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::kContinue, kSigned, v8::internal::maglev::BranchIfFloat64Compare::left_input(), Map(), v8::internal::maglev::BranchIfFloat64Compare::operation(), and v8::internal::maglev::BranchIfFloat64Compare::right_input().
Process() [9/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::BranchIfFloat64IsHole * node, const maglev::ProcessingState & state) [inline]
Definition at line 3686 of file turbolev-graph-builder.cc.
                                                                    {
    V<Word32> condition = __ Float64IsHole(Map(node->condition_input()));
    __ Branch(condition, Map(node->if_true()), Map(node->if_false()));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::BranchIfFloat64IsHole::condition_input(), v8::internal::maglev::kContinue, and Map().
Process() [10/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::BranchIfFloat64ToBooleanTrue * node, const maglev::ProcessingState & state) [inline]
Definition at line 3680 of file turbolev-graph-builder.cc.
                                                                    {
    V<Word32> condition = Float64ToBit(Map(node->condition_input()));
    __ Branch(condition, Map(node->if_true()), Map(node->if_false()));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::BranchIfFloat64ToBooleanTrue::condition_input(), Float64ToBit(), v8::internal::maglev::kContinue, and Map().
Process() [11/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::BranchIfInt32Compare * node, const maglev::ProcessingState & state) [inline]
Definition at line 3640 of file turbolev-graph-builder.cc.
                                                                    {
    V<Word32> condition =
        ConvertCompare<Word32>(node->left_input(), node->right_input(),
                               node->operation(), Sign::kSigned);
    __ Branch(condition, Map(node->if_true()), Map(node->if_false()));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::kContinue, kSigned, v8::internal::maglev::BranchIfInt32Compare::left_input(), Map(), v8::internal::maglev::BranchIfInt32Compare::operation(), and v8::internal::maglev::BranchIfInt32Compare::right_input().
Process() [12/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::BranchIfInt32ToBooleanTrue * node, const maglev::ProcessingState & state) [inline]
Definition at line 3664 of file turbolev-graph-builder.cc.
                                                                    {
    V<Word32> condition = Map(node->condition_input());
    __ Branch(condition, Map(node->if_true()), Map(node->if_false()));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::BranchIfInt32ToBooleanTrue::condition_input(), v8::internal::maglev::kContinue, and Map().
Process() [13/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::BranchIfIntPtrToBooleanTrue * node, const maglev::ProcessingState & state) [inline]
Definition at line 3671 of file turbolev-graph-builder.cc.
                                                                    {
    V<Word32> condition =
        __ Equal(Map(node->condition_input()), __ IntPtrConstant(0),
                 RegisterRepresentation::WordPtr());
    __ Branch(condition, Map(node->if_false()), Map(node->if_true()));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::BranchIfIntPtrToBooleanTrue::condition_input(), v8::internal::compiler::IntPtrConstant(), v8::internal::maglev::kContinue, Map(), and v8::internal::compiler::turboshaft::RegisterRepresentation::WordPtr().
Process() [14/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::BranchIfJSReceiver * node, const maglev::ProcessingState & state) [inline]
Definition at line 3747 of file turbolev-graph-builder.cc.
                                                                    {
    __ GotoIf(__ IsSmi(Map(node->condition_input())), Map(node->if_false()));
    __ Branch(__ JSAnyIsNotPrimitive(Map(node->condition_input())),
              Map(node->if_true()), Map(node->if_false()));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::BranchIfJSReceiver::condition_input(), v8::internal::IsSmi(), v8::internal::maglev::kContinue, and Map().
Process() [15/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::BranchIfReferenceEqual * node, const maglev::ProcessingState & state) [inline]
Definition at line 3703 of file turbolev-graph-builder.cc.
                                                                    {
    V<Word32> condition =
        __ TaggedEqual(Map(node->left_input()), Map(node->right_input()));
    __ Branch(condition, Map(node->if_true()), Map(node->if_false()));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::kContinue, v8::internal::maglev::BranchIfReferenceEqual::left_input(), Map(), and v8::internal::maglev::BranchIfReferenceEqual::right_input().
Process() [16/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::BranchIfRootConstant * node, const maglev::ProcessingState & state) [inline]
Definition at line 3710 of file turbolev-graph-builder.cc.
                                                                    {
    V<Word32> condition =
        RootEqual(node->condition_input(), node->root_index());
    __ Branch(condition, Map(node->if_true()), Map(node->if_false()));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::BranchIfRootConstant::condition_input(), v8::internal::maglev::kContinue, Map(), v8::internal::maglev::BranchIfRootConstant::root_index(), and RootEqual().
Process() [17/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::BranchIfSmi * node, const maglev::ProcessingState & state) [inline]
Definition at line 3741 of file turbolev-graph-builder.cc.
                                                                    {
    __ Branch(__ IsSmi(Map(node->condition_input())), Map(node->if_true()),
              Map(node->if_false()));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::BranchIfSmi::condition_input(), v8::internal::IsSmi(), v8::internal::maglev::kContinue, and Map().
Process() [18/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::BranchIfToBooleanTrue * node, const maglev::ProcessingState & state) [inline]
Definition at line 3630 of file turbolev-graph-builder.cc.
                                                                    {
    TruncateJSPrimitiveToUntaggedOp::InputAssumptions assumption =
        node->check_type() == maglev::CheckType::kCheckHeapObject
            ? TruncateJSPrimitiveToUntaggedOp::InputAssumptions::kObject
            : TruncateJSPrimitiveToUntaggedOp::InputAssumptions::kHeapObject;
    V<Word32> condition = ToBit(node->condition_input(), assumption);
    __ Branch(condition, Map(node->if_true()), Map(node->if_false()));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::BranchIfToBooleanTrue::check_type(), v8::internal::maglev::BranchIfToBooleanTrue::condition_input(), v8::internal::maglev::kCheckHeapObject, v8::internal::maglev::kContinue, v8::internal::compiler::turboshaft::TruncateJSPrimitiveToUntaggedOp::kHeapObject, v8::internal::compiler::turboshaft::TruncateJSPrimitiveToUntaggedOp::kObject, Map(), and ToBit().
Process() [19/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::BranchIfTypeOf * , const maglev::ProcessingState &) [inline]
Definition at line 4890 of file turbolev-graph-builder.cc.
                                                              {
    UNREACHABLE();
  }
  maglev::ProcessResult Process(maglev::BranchIfTypeOf*,
References v8::internal::UNREACHABLE().
Process() [20/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::BranchIfUint32Compare * node, const maglev::ProcessingState & state) [inline]
Definition at line 3648 of file turbolev-graph-builder.cc.
                                                                    {
    V<Word32> condition =
        ConvertCompare<Word32>(node->left_input(), node->right_input(),
                               node->operation(), Sign::kUnsigned);
    __ Branch(condition, Map(node->if_true()), Map(node->if_false()));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::kContinue, kUnsigned, v8::internal::maglev::BranchIfUint32Compare::left_input(), Map(), v8::internal::maglev::BranchIfUint32Compare::operation(), and v8::internal::maglev::BranchIfUint32Compare::right_input().
Process() [21/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::BranchIfUndefinedOrNull * node, const maglev::ProcessingState & state) [inline]
Definition at line 3717 of file turbolev-graph-builder.cc.
                                                                    {
    __ GotoIf(RootEqual(node->condition_input(), RootIndex::kUndefinedValue),
              Map(node->if_true()));
    __ Branch(RootEqual(node->condition_input(), RootIndex::kNullValue),
              Map(node->if_true()), Map(node->if_false()));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::BranchIfUndefinedOrNull::condition_input(), v8::internal::maglev::kContinue, and RootEqual().
Process() [22/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::BranchIfUndetectable * node, const maglev::ProcessingState & state) [inline]
Definition at line 3725 of file turbolev-graph-builder.cc.
                                                                    {
    ObjectIsOp::InputAssumptions assumption;
    switch (node->check_type()) {
      case maglev::CheckType::kCheckHeapObject:
        assumption = ObjectIsOp::InputAssumptions::kNone;
        break;
      case maglev::CheckType::kOmitHeapObjectCheck:
        assumption = ObjectIsOp::InputAssumptions::kHeapObject;
        break;
    }
    __ Branch(__ ObjectIs(Map(node->condition_input()),
                          ObjectIsOp::Kind::kUndetectable, assumption),
              Map(node->if_true()), Map(node->if_false()));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::BranchIfUndetectable::check_type(), v8::internal::maglev::BranchIfUndetectable::condition_input(), v8::internal::maglev::kCheckHeapObject, v8::internal::maglev::kContinue, v8::internal::compiler::turboshaft::ObjectIsOp::kHeapObject, v8::internal::compiler::turboshaft::ObjectIsOp::kNone, v8::internal::maglev::kOmitHeapObjectCheck, v8::internal::compiler::turboshaft::ObjectIsOp::kUndetectable, and Map().
Process() [23/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::BuiltinSeqOneByteStringCharCodeAt * node, const maglev::ProcessingState & state) [inline]
Definition at line 2876 of file turbolev-graph-builder.cc.
                                                                    {
    // TODO(leszeks): Change to seq-one-byte-specialized once
    // CheckSeqOneByteString checks for seq one-byte.
    SetMap(node, __ StringCharCodeAt(
                     Map(node->string_input()),
                     __ ChangeUint32ToUintPtr(Map(node->index_input()))));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::BuiltinSeqOneByteStringCharCodeAt::index_input(), v8::internal::maglev::kContinue, Map(), SetMap(), and v8::internal::maglev::BuiltinSeqOneByteStringCharCodeAt::string_input().
Process() [24/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::BuiltinStringFromCharCode * node, const maglev::ProcessingState & state) [inline]
Definition at line 2853 of file turbolev-graph-builder.cc.
                                                                    {
    SetMap(node, __ ConvertCharCodeToString(Map(node->code_input())));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::BuiltinStringFromCharCode::code_input(), v8::internal::maglev::kContinue, Map(), and SetMap().
Process() [25/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::BuiltinStringPrototypeCharCodeOrCodePointAt * node, const maglev::ProcessingState & state) [inline]
Definition at line 2858 of file turbolev-graph-builder.cc.
                                          {
    if (node->mode() == maglev::BuiltinStringPrototypeCharCodeOrCodePointAt::
                            Mode::kCharCodeAt) {
      SetMap(node, __ StringCharCodeAt(
                       Map(node->string_input()),
                       __ ChangeUint32ToUintPtr(Map(node->index_input()))));
    } else {
      DCHECK_EQ(node->mode(),
                maglev::BuiltinStringPrototypeCharCodeOrCodePointAt::Mode::
                    kCodePointAt);
      SetMap(node, __ StringCodePointAt(
                       Map(node->string_input()),
                       __ ChangeUint32ToUintPtr(Map(node->index_input()))));
    }
    return maglev::ProcessResult::kContinue;
  }
References __, DCHECK_EQ, v8::internal::maglev::BuiltinStringPrototypeCharCodeOrCodePointAt::index_input(), v8::internal::maglev::kContinue, Map(), v8::internal::maglev::BuiltinStringPrototypeCharCodeOrCodePointAt::mode(), SetMap(), and v8::internal::maglev::BuiltinStringPrototypeCharCodeOrCodePointAt::string_input().
Process() [26/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::Call * node, const maglev::ProcessingState & state) [inline]
Definition at line 1258 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
    V<Object> function = Map(node->function());
    V<Context> context = Map(node->context());
    Builtin builtin;
    switch (node->target_type()) {
      case maglev::Call::TargetType::kAny:
        switch (node->receiver_mode()) {
          case ConvertReceiverMode::kNullOrUndefined:
            builtin = Builtin::kCall_ReceiverIsNullOrUndefined;
            break;
          case ConvertReceiverMode::kNotNullOrUndefined:
            builtin = Builtin::kCall_ReceiverIsNotNullOrUndefined;
            break;
          case ConvertReceiverMode::kAny:
            builtin = Builtin::kCall_ReceiverIsAny;
            break;
        }
        break;
      case maglev::Call::TargetType::kJSFunction:
        switch (node->receiver_mode()) {
          case ConvertReceiverMode::kNullOrUndefined:
            builtin = Builtin::kCallFunction_ReceiverIsNullOrUndefined;
            break;
          case ConvertReceiverMode::kNotNullOrUndefined:
            builtin = Builtin::kCallFunction_ReceiverIsNotNullOrUndefined;
            break;
          case ConvertReceiverMode::kAny:
            builtin = Builtin::kCallFunction_ReceiverIsAny;
            break;
        }
        break;
    }
    base::SmallVector<OpIndex, 16> arguments;
    arguments.push_back(function);
    arguments.push_back(__ Word32Constant(node->num_args()));
    for (auto arg : node->args()) {
      arguments.push_back(Map(arg));
    }
    arguments.push_back(context);
    GENERATE_AND_MAP_BUILTIN_CALL(node, builtin, frame_state,
                                  base::VectorOf(arguments), node->num_args());
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::Call::args(), v8::internal::maglev::Call::context(), v8::internal::maglev::Call::function(), GENERATE_AND_MAP_BUILTIN_CALL, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::kAny, v8::internal::maglev::Call::kAny, v8::internal::maglev::kContinue, v8::internal::maglev::Call::kJSFunction, v8::internal::kNotNullOrUndefined, v8::internal::kNullOrUndefined, Map(), v8::internal::maglev::Call::num_args(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), v8::internal::maglev::Call::receiver_mode(), v8::internal::maglev::Call::target_type(), and v8::base::VectorOf().
Process() [27/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CallBuiltin * node, const maglev::ProcessingState & state) [inline]
Definition at line 1455 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
    base::SmallVector<OpIndex, 16> arguments;
    for (int i = 0; i < node->InputCountWithoutContext(); i++) {
      arguments.push_back(Map(node->input(i)));
    }
    if (node->has_feedback()) {
      V<Any> feedback_slot;
      switch (node->slot_type()) {
        case maglev::CallBuiltin::kTaggedIndex:
          feedback_slot = __ TaggedIndexConstant(node->feedback().index());
          break;
        case maglev::CallBuiltin::kSmi:
          feedback_slot = __ WordPtrConstant(node->feedback().index());
          break;
      }
      arguments.push_back(feedback_slot);
      arguments.push_back(__ HeapConstant(node->feedback().vector));
    }
    auto descriptor = Builtins::CallInterfaceDescriptorFor(node->builtin());
    if (descriptor.HasContextParameter()) {
      arguments.push_back(Map(node->context_input()));
    }
    int stack_arg_count =
        node->InputCountWithoutContext() - node->InputsInRegisterCount();
    if (node->has_feedback()) {
      // We might need to take the feedback slot and vector into account for
      // {stack_arg_count}. There are three possibilities:
      // 1. Feedback slot and vector are in register.
      // 2. Feedback slot is in register and vector is on stack.
      // 3. Feedback slot and vector are on stack.
      int slot_index = node->InputCountWithoutContext();
      int vector_index = slot_index + 1;
      if (vector_index < descriptor.GetRegisterParameterCount()) {
        // stack_arg_count is already correct.
      } else if (vector_index == descriptor.GetRegisterParameterCount()) {
        // feedback vector is on the stack
        stack_arg_count += 1;
      } else {
        // feedback slot and vector on the stack
        stack_arg_count += 2;
      }
    }
    BAILOUT_IF_TOO_MANY_ARGUMENTS_FOR_CALL(arguments.size());
    V<Any> call_idx =
        GenerateBuiltinCall(node, node->builtin(), frame_state,
                            base::VectorOf(arguments), stack_arg_count);
    SetMapMaybeMultiReturn(node, call_idx);
    return maglev::ProcessResult::kContinue;
  }
References __, BAILOUT_IF_TOO_MANY_ARGUMENTS_FOR_CALL, v8::internal::maglev::CallBuiltin::builtin(), v8::internal::Builtins::CallInterfaceDescriptorFor(), v8::internal::maglev::CallBuiltin::context_input(), v8::internal::maglev::CallBuiltin::feedback(), GenerateBuiltinCall(), GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::CallBuiltin::has_feedback(), v8::internal::compiler::FeedbackSource::index(), v8::internal::maglev::CallBuiltin::InputCountWithoutContext(), v8::internal::maglev::CallBuiltin::InputsInRegisterCount(), v8::internal::maglev::kContinue, v8::internal::maglev::CallBuiltin::kSmi, v8::internal::maglev::CallBuiltin::kTaggedIndex, Map(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), SetMapMaybeMultiReturn(), v8::base::SmallVector< T, kSize, Allocator >::size(), v8::internal::maglev::CallBuiltin::slot_type(), v8::internal::compiler::FeedbackSource::vector, and v8::base::VectorOf().
Process() [28/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CallCPPBuiltin * , const maglev::ProcessingState &) [inline]
Definition at line 4878 of file turbolev-graph-builder.cc.
Process() [29/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CallForwardVarargs * node, const maglev::ProcessingState & state) [inline]
Definition at line 1758 of file turbolev-graph-builder.cc.
                                                                    {
    ThrowingScope throwing_scope(this, node);
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
    V<JSFunction> function = Map(node->function());
    V<Context> context = Map(node->context());
    base::SmallVector<V<Object>, 16> arguments;
    for (auto arg : node->args()) {
      arguments.push_back(Map(arg));
    }
    DCHECK_EQ(node->num_args(), arguments.size());
    Builtin builtin;
    switch (node->target_type()) {
      case maglev::Call::TargetType::kJSFunction:
        builtin = Builtin::kCallFunctionForwardVarargs;
        break;
      case maglev::Call::TargetType::kAny:
        builtin = Builtin::kCallForwardVarargs;
        break;
    }
    V<Object> call = __ CallBuiltin_CallForwardVarargs(
        isolate_, graph_zone(), builtin, frame_state, context, function,
        node->num_args(), node->start_index(), base::VectorOf(arguments),
        ShouldLazyDeoptOnThrow(node));
    SetMap(node, call);
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::CallForwardVarargs::args(), v8::internal::maglev::CallForwardVarargs::context(), DCHECK_EQ, v8::internal::maglev::CallForwardVarargs::function(), GET_FRAME_STATE_MAYBE_ABORT, graph_zone(), isolate_, v8::internal::maglev::Call::kAny, v8::internal::maglev::kContinue, v8::internal::maglev::Call::kJSFunction, Map(), v8::internal::maglev::CallForwardVarargs::num_args(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), SetMap(), ShouldLazyDeoptOnThrow(), v8::base::SmallVector< T, kSize, Allocator >::size(), v8::internal::maglev::CallForwardVarargs::start_index(), v8::internal::maglev::CallForwardVarargs::target_type(), and v8::base::VectorOf().
Process() [30/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CallKnownApiFunction * node, const maglev::ProcessingState & state) [inline]
Definition at line 1381 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
    if (node->inline_builtin()) {
      DCHECK(v8_flags.maglev_inline_api_calls);
      // TODO(dmercadier, 40912714, 42203760): The flag maglev_inline_api_calls
      // is currently experimental, and it's not clear at this point if it will
      // even become non-experimental, so we currently don't support it in the
      // Maglev->Turboshaft translation. Note that a quick-fix would be to treat
      // kNoProfilingInlined like kNoProfiling, although this would be slower
      // than desired.
      UNIMPLEMENTED();
    }
    V<Object> target =
        __ HeapConstant(node->function_template_info().AsHeapObject().object());
    ApiFunction function(node->function_template_info().callback(broker_));
    ExternalReference function_ref = ExternalReference::Create(
        &function, ExternalReference::DIRECT_API_CALL);
    base::SmallVector<OpIndex, 16> arguments;
    arguments.push_back(__ ExternalConstant(function_ref));
    arguments.push_back(__ Word32Constant(node->num_args()));
    arguments.push_back(target);
    arguments.push_back(Map(node->receiver()));
    for (maglev::Input arg : node->args()) {
      arguments.push_back(Map(arg));
    }
    arguments.push_back(Map(node->context()));
    Builtin builtin;
    switch (node->mode()) {
      case maglev::CallKnownApiFunction::Mode::kNoProfiling:
        builtin = Builtin::kCallApiCallbackOptimizedNoProfiling;
        break;
      case maglev::CallKnownApiFunction::Mode::kNoProfilingInlined:
        // Handled earlier when checking `node->inline_builtin()`.
        UNREACHABLE();
      case maglev::CallKnownApiFunction::Mode::kGeneric:
        builtin = Builtin::kCallApiCallbackOptimized;
        break;
    }
    int stack_arg_count = node->num_args() + /* implicit receiver */ 1;
    GENERATE_AND_MAP_BUILTIN_CALL(node, builtin, frame_state,
                                  base::VectorOf(arguments), stack_arg_count);
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::CallKnownApiFunction::args(), broker_, v8::internal::compiler::FunctionTemplateInfoRef::callback(), v8::internal::maglev::CallKnownApiFunction::context(), v8::internal::ExternalReference::Create(), v8::internal::DCHECK(), v8::internal::ExternalReference::DIRECT_API_CALL, v8::internal::maglev::CallKnownApiFunction::function_template_info(), GENERATE_AND_MAP_BUILTIN_CALL, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::CallKnownApiFunction::inline_builtin(), v8::internal::maglev::kContinue, Map(), v8::internal::maglev::CallKnownApiFunction::mode(), v8::internal::maglev::CallKnownApiFunction::num_args(), v8::internal::compiler::FunctionTemplateInfoRef::object(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), v8::internal::maglev::CallKnownApiFunction::receiver(), v8::internal::compiler::UNIMPLEMENTED(), v8::internal::UNREACHABLE(), v8::internal::v8_flags, and v8::base::VectorOf().
Process() [31/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CallKnownJSFunction * node, const maglev::ProcessingState & state) [inline]
Definition at line 1307 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
    V<Object> callee = Map(node->closure());
    int actual_parameter_count = JSParameterCount(node->num_args());
    if (node->shared_function_info().HasBuiltinId()) {
      // Note that there is no need for a ThrowingScope here:
      // GenerateBuiltinCall takes care of creating one.
      base::SmallVector<OpIndex, 16> arguments;
      arguments.push_back(callee);
      arguments.push_back(Map(node->new_target()));
      arguments.push_back(__ Word32Constant(actual_parameter_count));
#ifdef V8_JS_LINKAGE_INCLUDES_DISPATCH_HANDLE
      arguments.push_back(
          __ Word32Constant(kPlaceholderDispatchHandle.value()));
#endif
      arguments.push_back(Map(node->receiver()));
      for (int i = 0; i < node->num_args(); i++) {
        arguments.push_back(Map(node->arg(i)));
      }
      // Setting missing arguments to Undefined.
      for (int i = actual_parameter_count; i < node->expected_parameter_count();
           i++) {
        arguments.push_back(undefined_value_);
      }
      arguments.push_back(Map(node->context()));
      GENERATE_AND_MAP_BUILTIN_CALL(
          node, node->shared_function_info().builtin_id(), frame_state,
          base::VectorOf(arguments),
          std::max<int>(actual_parameter_count,
                        node->expected_parameter_count()));
    } else {
      ThrowingScope throwing_scope(this, node);
      base::SmallVector<OpIndex, 16> arguments;
      arguments.push_back(Map(node->receiver()));
      for (int i = 0; i < node->num_args(); i++) {
        arguments.push_back(Map(node->arg(i)));
      }
      // Setting missing arguments to Undefined.
      for (int i = actual_parameter_count; i < node->expected_parameter_count();
           i++) {
        arguments.push_back(undefined_value_);
      }
      arguments.push_back(Map(node->new_target()));
      arguments.push_back(__ Word32Constant(actual_parameter_count));
#ifdef V8_JS_LINKAGE_INCLUDES_DISPATCH_HANDLE
      arguments.push_back(
          __ Word32Constant(kPlaceholderDispatchHandle.value()));
#endif
      // Load the context from {callee}.
      OpIndex context =
          __ LoadField(callee, AccessBuilder::ForJSFunctionContext());
      arguments.push_back(context);
      const CallDescriptor* descriptor = Linkage::GetJSCallDescriptor(
          graph_zone(), false,
          std::max<int>(actual_parameter_count,
                        node->expected_parameter_count()),
          CallDescriptor::kNeedsFrameState | CallDescriptor::kCanUseRoots);
      LazyDeoptOnThrow lazy_deopt_on_throw = ShouldLazyDeoptOnThrow(node);
      BAILOUT_IF_TOO_MANY_ARGUMENTS_FOR_CALL(arguments.size());
      SetMap(node, __ Call(V<CallTarget>::Cast(callee), frame_state,
                           base::VectorOf(arguments),
                           TSCallDescriptor::Create(descriptor, CanThrow::kYes,
                                                    lazy_deopt_on_throw,
                                                    graph_zone())));
    }
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::CallKnownJSFunction::arg(), BAILOUT_IF_TOO_MANY_ARGUMENTS_FOR_CALL, v8::internal::compiler::SharedFunctionInfoRef::builtin_id(), v8::internal::maglev::CallKnownJSFunction::closure(), v8::internal::maglev::CallKnownJSFunction::context(), v8::internal::compiler::turboshaft::TSCallDescriptor::Create(), v8::internal::maglev::CallKnownJSFunction::expected_parameter_count(), v8::internal::compiler::AccessBuilder::ForJSFunctionContext(), GENERATE_AND_MAP_BUILTIN_CALL, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::compiler::Linkage::GetJSCallDescriptor(), graph_zone(), v8::internal::JSParameterCount(), v8::internal::compiler::CallDescriptor::kCanUseRoots, v8::internal::maglev::kContinue, v8::internal::compiler::CallDescriptor::kNeedsFrameState, v8::internal::kPlaceholderDispatchHandle(), v8::internal::compiler::kYes, Map(), v8::internal::maglev::CallKnownJSFunction::new_target(), v8::internal::maglev::CallKnownJSFunction::num_args(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), v8::internal::maglev::CallKnownJSFunction::receiver(), SetMap(), v8::internal::maglev::CallKnownJSFunction::shared_function_info(), ShouldLazyDeoptOnThrow(), v8::base::SmallVector< T, kSize, Allocator >::size(), undefined_value_, v8::base::StrongAlias< TagType, UnderlyingType >::value(), and v8::base::VectorOf().
Process() [32/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CallRuntime * node, const maglev::ProcessingState & state) [inline]
Definition at line 1512 of file turbolev-graph-builder.cc.
                                                                    {
    ThrowingScope throwing_scope(this, node);
    LazyDeoptOnThrow lazy_deopt_on_throw = ShouldLazyDeoptOnThrow(node);
    auto c_entry_stub = __ CEntryStubConstant(isolate_, node->ReturnCount());
    CallDescriptor* call_descriptor = Linkage::GetRuntimeCallDescriptor(
        graph_zone(), node->function_id(), node->num_args(),
        Operator::kNoProperties, CallDescriptor::kNeedsFrameState,
        lazy_deopt_on_throw);
    base::SmallVector<OpIndex, 16> arguments;
    for (int i = 0; i < node->num_args(); i++) {
      arguments.push_back(Map(node->arg(i)));
    }
    arguments.push_back(
        __ ExternalConstant(ExternalReference::Create(node->function_id())));
    arguments.push_back(__ Word32Constant(node->num_args()));
    arguments.push_back(Map(node->context()));
    OptionalV<FrameState> frame_state = OptionalV<FrameState>::Nullopt();
    if (call_descriptor->NeedsFrameState()) {
      GET_FRAME_STATE_MAYBE_ABORT(frame_state_value, node->lazy_deopt_info());
      frame_state = frame_state_value;
    }
    DCHECK_IMPLIES(lazy_deopt_on_throw == LazyDeoptOnThrow::kYes,
                   frame_state.has_value());
    BAILOUT_IF_TOO_MANY_ARGUMENTS_FOR_CALL(arguments.size());
    V<Any> call_idx =
        __ Call(c_entry_stub, frame_state, base::VectorOf(arguments),
                TSCallDescriptor::Create(call_descriptor, CanThrow::kYes,
                                         lazy_deopt_on_throw, graph_zone()));
    SetMapMaybeMultiReturn(node, call_idx);
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::CallRuntime::arg(), BAILOUT_IF_TOO_MANY_ARGUMENTS_FOR_CALL, v8::internal::maglev::CallRuntime::context(), v8::internal::compiler::turboshaft::TSCallDescriptor::Create(), v8::internal::ExternalReference::Create(), DCHECK_IMPLIES, v8::internal::maglev::CallRuntime::function_id(), GET_FRAME_STATE_MAYBE_ABORT, v8::internal::compiler::Linkage::GetRuntimeCallDescriptor(), graph_zone(), v8::internal::compiler::turboshaft::OptionalOpIndex::has_value(), isolate_, v8::internal::maglev::kContinue, v8::internal::compiler::CallDescriptor::kNeedsFrameState, v8::internal::compiler::Operator::kNoProperties, v8::internal::compiler::kYes, Map(), v8::internal::compiler::CallDescriptor::NeedsFrameState(), v8::internal::compiler::turboshaft::OptionalV< T >::Nullopt(), v8::internal::maglev::CallRuntime::num_args(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), v8::internal::maglev::CallRuntime::ReturnCount(), SetMapMaybeMultiReturn(), ShouldLazyDeoptOnThrow(), v8::base::SmallVector< T, kSize, Allocator >::size(), and v8::base::VectorOf().
Process() [33/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CallSelf * , const maglev::ProcessingState &) [inline]
Definition at line 4869 of file turbolev-graph-builder.cc.
                                                              {
    // CallSelf nodes are only created when Maglev is the top-tier compiler
    // (which can't be the case here, since we're currently compiling for
Process() [34/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CallWithArrayLike * node, const maglev::ProcessingState & state) [inline]
Definition at line 1718 of file turbolev-graph-builder.cc.
                                                                    {
    ThrowingScope throwing_scope(this, node);
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
    V<Context> context = Map(node->context());
    V<Object> function = Map(node->function());
    V<Object> receiver = Map(node->receiver());
    V<Object> arguments_list = Map(node->arguments_list());
    SetMap(node, __ CallBuiltin_CallWithArrayLike(
                     isolate_, graph_zone(), frame_state, context, receiver,
                     function, arguments_list, ShouldLazyDeoptOnThrow(node)));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::CallWithArrayLike::arguments_list(), v8::internal::maglev::CallWithArrayLike::context(), v8::internal::maglev::CallWithArrayLike::function(), GET_FRAME_STATE_MAYBE_ABORT, graph_zone(), isolate_, v8::internal::maglev::kContinue, Map(), v8::internal::maglev::CallWithArrayLike::receiver(), SetMap(), and ShouldLazyDeoptOnThrow().
Process() [35/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CallWithSpread * node, const maglev::ProcessingState & state) [inline]
Definition at line 1735 of file turbolev-graph-builder.cc.
                                                                    {
    ThrowingScope throwing_scope(this, node);
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
    V<Context> context = Map(node->context());
    V<Object> function = Map(node->function());
    V<Object> spread = Map(node->spread());
    base::SmallVector<V<Object>, 16> arguments_no_spread;
    for (auto arg : node->args_no_spread()) {
      arguments_no_spread.push_back(Map(arg));
    }
    SetMap(node, __ CallBuiltin_CallWithSpread(
                     isolate_, graph_zone(), frame_state, context, function,
                     node->num_args_no_spread(), spread,
                     base::VectorOf(arguments_no_spread),
                     ShouldLazyDeoptOnThrow(node)));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::CallWithSpread::args_no_spread(), v8::internal::maglev::CallWithSpread::context(), v8::internal::maglev::CallWithSpread::function(), GET_FRAME_STATE_MAYBE_ABORT, graph_zone(), isolate_, v8::internal::maglev::kContinue, Map(), v8::internal::maglev::CallWithSpread::num_args_no_spread(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), SetMap(), ShouldLazyDeoptOnThrow(), v8::internal::maglev::CallWithSpread::spread(), and v8::base::VectorOf().
Process() [36/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::ChangeInt32ToFloat64 * node, const maglev::ProcessingState & state) [inline]
Definition at line 4447 of file turbolev-graph-builder.cc.
                                                            : result);
    return maglev::ProcessResult::kContinue;
  }
  maglev::ProcessResult Process(maglev::ChangeInt32ToFloat64* node,
                                const maglev::ProcessingState& state) {
Process() [37/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::ChangeIntPtrToFloat64 * node, const maglev::ProcessingState & state) [inline]
Definition at line 4458 of file turbolev-graph-builder.cc.
                                                                    {
Process() [38/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::ChangeUint32ToFloat64 * node, const maglev::ProcessingState & state) [inline]
Definition at line 4452 of file turbolev-graph-builder.cc.
                                                                    {
Process() [39/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckCacheIndicesNotCleared * node, const maglev::ProcessingState & state) [inline]
Definition at line 3182 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    // If the cache length is zero, we don't have any indices, so we know this
    // is ok even though the indices are the empty array.
    IF_NOT (__ Word32Equal(Map(node->length_input()), 0)) {
      // Otherwise, an empty array with non-zero required length is not valid.
      V<Word32> condition =
          RootEqual(node->indices_input(), RootIndex::kEmptyFixedArray);
      __ DeoptimizeIf(condition, frame_state,
                      DeoptimizeReason::kWrongEnumIndices,
                      node->eager_deopt_info()->feedback_to_update());
    }
    return maglev::ProcessResult::kContinue;
  }
References __, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::CheckCacheIndicesNotCleared::indices_input(), v8::internal::maglev::kContinue, v8::internal::maglev::CheckCacheIndicesNotCleared::length_input(), Map(), RootEqual(), and v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal().
Process() [40/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckConstructResult * node, const maglev::ProcessingState & state) [inline]
Definition at line 1854 of file turbolev-graph-builder.cc.
                                                                    {
    SetMap(node, __ CheckConstructResult(Map(node->construct_result_input()),
                                         Map(node->implicit_receiver_input())));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::CheckConstructResult::construct_result_input(), v8::internal::maglev::CheckConstructResult::implicit_receiver_input(), v8::internal::maglev::kContinue, Map(), and SetMap().
Process() [41/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckDerivedConstructResult * node, const maglev::ProcessingState & state) [inline]
Definition at line 1860 of file turbolev-graph-builder.cc.
                                                                    {
    ThrowingScope throwing_scope(this, node);
    V<Object> construct_result = Map(node->construct_result_input());
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
    __ CheckDerivedConstructResult(construct_result, frame_state,
                                   native_context(),
                                   ShouldLazyDeoptOnThrow(node));
    SetMap(node, construct_result);
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::CheckDerivedConstructResult::construct_result_input(), GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::kContinue, Map(), native_context(), SetMap(), and ShouldLazyDeoptOnThrow().
Process() [42/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckDetectableCallable * node, const maglev::ProcessingState & state) [inline]
Definition at line 3582 of file turbolev-graph-builder.cc.
                                                                    {
    V<Object> receiver = Map(node->receiver_input());
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    ObjectIsOp::InputAssumptions assumptions;
    switch (node->check_type()) {
      case maglev::CheckType::kCheckHeapObject:
        assumptions = ObjectIsOp::InputAssumptions::kNone;
        break;
      case maglev::CheckType::kOmitHeapObjectCheck:
        assumptions = ObjectIsOp::InputAssumptions::kHeapObject;
        break;
    }
    __ DeoptimizeIfNot(
        __ ObjectIs(receiver, ObjectIsOp::Kind::kDetectableCallable,
                    assumptions),
        frame_state, DeoptimizeReason::kNotDetectableReceiver,
        node->eager_deopt_info()->feedback_to_update());
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::CheckDetectableCallable::check_type(), GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::kCheckHeapObject, v8::internal::maglev::kContinue, v8::internal::compiler::turboshaft::ObjectIsOp::kDetectableCallable, v8::internal::compiler::turboshaft::ObjectIsOp::kHeapObject, v8::internal::compiler::turboshaft::ObjectIsOp::kNone, v8::internal::maglev::kOmitHeapObjectCheck, Map(), and v8::internal::maglev::CheckDetectableCallable::receiver_input().
Process() [43/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckDynamicValue * node, const maglev::ProcessingState & state) [inline]
Definition at line 2554 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    __ DeoptimizeIfNot(
        __ TaggedEqual(Map(node->first_input()), Map(node->second_input())),
        frame_state, node->deoptimize_reason(),
        node->eager_deopt_info()->feedback_to_update());
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::CheckDynamicValue::first_input(), GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::kContinue, Map(), and v8::internal::maglev::CheckDynamicValue::second_input().
Process() [44/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckedHoleyFloat64ToFloat64 * node, const maglev::ProcessingState & state) [inline]
Definition at line 4553 of file turbolev-graph-builder.cc.
                                                                    {
    V<Float64> input = Map(node->input());
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    __ DeoptimizeIf(__ Float64IsHole(input), frame_state,
                    DeoptimizeReason::kHole,
                    node->eager_deopt_info()->feedback_to_update());
Process() [45/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckedInt32ToUint32 * node, const maglev::ProcessingState & state) [inline]
Definition at line 4370 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    __ DeoptimizeIf(__ Int32LessThan(Map(node->input()), 0), frame_state,
                    DeoptimizeReason::kNotUint32,
                    node->eager_deopt_info()->feedback_to_update());
Process() [46/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckedInternalizedString * node, const maglev::ProcessingState & state) [inline]
Definition at line 2836 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    SetMap(node, __ CheckedInternalizedString(
                     Map(node->object_input()), frame_state,
                     node->check_type() == maglev::CheckType::kCheckHeapObject,
                     node->eager_deopt_info()->feedback_to_update()));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::CheckedInternalizedString::check_type(), GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::kCheckHeapObject, v8::internal::maglev::kContinue, Map(), v8::internal::maglev::CheckedInternalizedString::object_input(), and SetMap().
Process() [47/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckedIntPtrToInt32 * node, const maglev::ProcessingState & state) [inline]
Definition at line 4405 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    // TODO(388844115): Rename the IntPtr in Maglev to make it clear it's
    // non-negative.
    __ DeoptimizeIfNot(
        __ UintPtrLessThanOrEqual(Map(node->input()),
                                  std::numeric_limits<int32_t>::max()),
        frame_state, DeoptimizeReason::kNotInt32,
        node->eager_deopt_info()->feedback_to_update());
    SetMap(node, __ Word32SignHintSigned(
Process() [48/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckedIntPtrToUint32 * node, const maglev::ProcessingState & state) [inline]
Definition at line 4380 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    // TODO(388844115): Rename the IntPtr in Maglev to make it clear it's
    // non-negative.
    __ DeoptimizeIfNot(
        __ UintPtrLessThanOrEqual(Map(node->input()),
                                  std::numeric_limits<uint32_t>::max()),
        frame_state, DeoptimizeReason::kNotUint32,
        node->eager_deopt_info()->feedback_to_update());
    SetMap(node, __ Word32SignHintUnsigned(
Process() [49/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckedNumberOrOddballToFloat64 * node, const maglev::ProcessingState & state) [inline]
Definition at line 4308 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    ConvertJSPrimitiveToUntaggedOrDeoptOp::JSPrimitiveKind kind;
    switch (node->conversion_type()) {
      case maglev::TaggedToFloat64ConversionType::kOnlyNumber:
        kind = ConvertJSPrimitiveToUntaggedOrDeoptOp::JSPrimitiveKind::kNumber;
        break;
      case maglev::TaggedToFloat64ConversionType::kNumberOrBoolean:
        kind = ConvertJSPrimitiveToUntaggedOrDeoptOp::JSPrimitiveKind::
            kNumberOrBoolean;
        break;
      case maglev::TaggedToFloat64ConversionType::kNumberOrOddball:
        kind = ConvertJSPrimitiveToUntaggedOrDeoptOp::JSPrimitiveKind::
            kNumberOrOddball;
        break;
    }
    SetMap(node,
           __ ConvertJSPrimitiveToUntaggedOrDeopt(
               Map(node->input()), frame_state, kind,
               ConvertJSPrimitiveToUntaggedOrDeoptOp::UntaggedKind::kFloat64,
               CheckForMinusZeroMode::kCheckForMinusZero,
Process() [50/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckedNumberOrOddballToHoleyFloat64 * node, const maglev::ProcessingState & state) [inline]
Definition at line 4333 of file turbolev-graph-builder.cc.
                                          {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    SetMap(
        node,
        __ ConvertJSPrimitiveToUntaggedOrDeopt(
            Map(node->input()), frame_state,
            ConvertJSPrimitiveToUntaggedOrDeoptOp::JSPrimitiveKind::
                kNumberOrOddball,
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
            ConvertJSPrimitiveToUntaggedOrDeoptOp::UntaggedKind::kHoleyFloat64,
#else
            ConvertJSPrimitiveToUntaggedOrDeoptOp::UntaggedKind::kFloat64,
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
            CheckForMinusZeroMode::kCheckForMinusZero,
Process() [51/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckedNumberToInt32 * node, const maglev::ProcessingState & state) [inline]
Definition at line 2343 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    V<Object> input = Map(node->input());
    ScopedVar<Word32, AssemblerT> value(this);
    IF (__ IsSmi(input)) {
      value = __ UntagSmi(V<Smi>::Cast(input));
    } ELSE {
      __ DeoptimizeIfNot(__ IsHeapNumberMap(__ LoadMapField(input)),
                         frame_state, DeoptimizeReason::kNotInt32,
                         node->eager_deopt_info()->feedback_to_update());
      value = __ ChangeFloat64ToInt32OrDeopt(
          __ LoadHeapNumberValue(V<HeapNumber>::Cast(input)), frame_state,
          CheckForMinusZeroMode::kCheckForMinusZero,
          node->eager_deopt_info()->feedback_to_update());
    }
    SetMap(node, value);
    return maglev::ProcessResult::kContinue;
  }
References __, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::CheckedNumberToInt32::input(), v8::internal::IsSmi(), v8::internal::compiler::kCheckForMinusZero, v8::internal::maglev::kContinue, Map(), SetMap(), and v8::internal::value.
Process() [52/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckedNumberToUint8Clamped * node, const maglev::ProcessingState & state) [inline]
Definition at line 4663 of file turbolev-graph-builder.cc.
                                                                    {
    ScopedVar<Word32, AssemblerT> result(this);
    V<Object> value = Map(node->input());
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    IF (__ IsSmi(value)) {
      result = Int32ToUint8Clamped(__ UntagSmi(V<Smi>::Cast(value)));
    } ELSE {
      V<i::Map> map = __ LoadMapField(value);
      __ DeoptimizeIfNot(
          __ TaggedEqual(map,
                         __ HeapConstant(local_factory_->heap_number_map())),
          frame_state, DeoptimizeReason::kNotAHeapNumber,
          node->eager_deopt_info()->feedback_to_update());
      result = Float64ToUint8Clamped(
          __ LoadHeapNumberValue(V<HeapNumber>::Cast(value)));
    }
    RETURN_IF_UNREACHABLE();
Process() [53/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckedObjectToIndex * node, const maglev::ProcessingState & state) [inline]
Definition at line 4425 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    const FeedbackSource& feedback =
        node->eager_deopt_info()->feedback_to_update();
    OpIndex result = __ ConvertJSPrimitiveToUntaggedOrDeopt(
        Map(node->object_input()), frame_state,
        ConvertJSPrimitiveToUntaggedOrDeoptOp::JSPrimitiveKind::kNumberOrString,
        ConvertJSPrimitiveToUntaggedOrDeoptOp::UntaggedKind::kArrayIndex,
        CheckForMinusZeroMode::kCheckForMinusZero, feedback);
    if constexpr (Is64()) {
      // ArrayIndex is 32-bit in Maglev, but 64 in Turboshaft. This means that
      // we have to convert it to 32-bit before the following `SetMap`, and we
      // thus have to check that it actually fits in a Uint32.
      __ DeoptimizeIfNot(__ Uint64LessThanOrEqual(
                             result, std::numeric_limits<uint32_t>::max()),
                         frame_state, DeoptimizeReason::kNotInt32, feedback);
      RETURN_IF_UNREACHABLE();
    }
Process() [54/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckedSmiDecrement * node, const maglev::ProcessingState & state) [inline]
Definition at line 4147 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    V<Smi> result;
    if constexpr (SmiValuesAre31Bits()) {
      result = __ BitcastWord32ToSmi(__ Word32SignedSubDeoptOnOverflow(
          __ BitcastSmiToWord32(Map(node->value_input())),
          Smi::FromInt(1).ptr(), frame_state,
          node->eager_deopt_info()->feedback_to_update()));
    } else {
      result = __ BitcastWordPtrToSmi(__ WordPtrSignedSubDeoptOnOverflow(
          __ BitcastSmiToWordPtr(Map(node->value_input())),
          Smi::FromInt(1).ptr(), frame_state,
          node->eager_deopt_info()->feedback_to_update()));
    }
Process() [55/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckedSmiIncrement * node, const maglev::ProcessingState & state) [inline]
Definition at line 4126 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    V<Smi> result;
    if constexpr (SmiValuesAre31Bits()) {
      result = __ BitcastWord32ToSmi(__ Word32SignedAddDeoptOnOverflow(
          __ BitcastSmiToWord32(Map(node->value_input())),
          Smi::FromInt(1).ptr(), frame_state,
          node->eager_deopt_info()->feedback_to_update()));
    } else {
      // Remember that 32-bit Smis are stored in the upper 32 bits of 64-bit
      // qwords. We thus perform a 64-bit addition rather than a 32-bit one,
      // despite Smis being only 32 bits.
      result = __ BitcastWordPtrToSmi(__ WordPtrSignedAddDeoptOnOverflow(
          __ BitcastSmiToWordPtr(Map(node->value_input())),
          Smi::FromInt(1).ptr(), frame_state,
          node->eager_deopt_info()->feedback_to_update()));
    }
Process() [56/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckedSmiSizedInt32 * node, const maglev::ProcessingState & state) [inline]
Definition at line 2563 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    DeoptIfInt32IsNotSmi(node->input(), frame_state,
                         node->eager_deopt_info()->feedback_to_update());
    SetMap(node, Map(node->input()));
    return maglev::ProcessResult::kContinue;
  }
References DeoptIfInt32IsNotSmi(), GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::CheckedSmiSizedInt32::input(), v8::internal::maglev::kContinue, Map(), and SetMap().
Process() [57/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckedSmiTagFloat64 * node, const maglev::ProcessingState & state) [inline]
Definition at line 3892 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    V<Word32> as_int32 = __ ChangeFloat64ToInt32OrDeopt(
        Map(node->input()), frame_state,
        CheckForMinusZeroMode::kCheckForMinusZero,
        node->eager_deopt_info()->feedback_to_update());
    SetMap(
        node,
        __ ConvertUntaggedToJSPrimitiveOrDeopt(
            as_int32, frame_state,
            ConvertUntaggedToJSPrimitiveOrDeoptOp::JSPrimitiveKind::kSmi,
            RegisterRepresentation::Word32(),
            ConvertUntaggedToJSPrimitiveOrDeoptOp::InputInterpretation::kSigned,
            node->eager_deopt_info()->feedback_to_update()));
    return maglev::ProcessResult::kContinue;
  }
References __, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::CheckedSmiTagFloat64::input(), v8::internal::compiler::kCheckForMinusZero, v8::internal::maglev::kContinue, v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOrDeoptOp::kSigned, v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOrDeoptOp::kSmi, Map(), SetMap(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word32().
Process() [58/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckedSmiTagInt32 * node, const maglev::ProcessingState & state) [inline]
Definition at line 3851 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    SetMap(
        node,
        __ ConvertUntaggedToJSPrimitiveOrDeopt(
            Map(node->input()), frame_state,
            ConvertUntaggedToJSPrimitiveOrDeoptOp::JSPrimitiveKind::kSmi,
            RegisterRepresentation::Word32(),
            ConvertUntaggedToJSPrimitiveOrDeoptOp::InputInterpretation::kSigned,
            node->eager_deopt_info()->feedback_to_update()));
    return maglev::ProcessResult::kContinue;
  }
References __, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::CheckedSmiTagInt32::input(), v8::internal::maglev::kContinue, v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOrDeoptOp::kSigned, v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOrDeoptOp::kSmi, Map(), SetMap(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word32().
Process() [59/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckedSmiTagIntPtr * node, const maglev::ProcessingState & state) [inline]
Definition at line 3878 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    SetMap(
        node,
        __ ConvertUntaggedToJSPrimitiveOrDeopt(
            Map(node->input()), frame_state,
            ConvertUntaggedToJSPrimitiveOrDeoptOp::JSPrimitiveKind::kSmi,
            RegisterRepresentation::WordPtr(),
            ConvertUntaggedToJSPrimitiveOrDeoptOp::InputInterpretation::kSigned,
            node->eager_deopt_info()->feedback_to_update()));
    return maglev::ProcessResult::kContinue;
  }
References __, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::CheckedSmiTagIntPtr::input(), v8::internal::maglev::kContinue, v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOrDeoptOp::kSigned, v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOrDeoptOp::kSmi, Map(), SetMap(), and v8::internal::compiler::turboshaft::RegisterRepresentation::WordPtr().
Process() [60/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckedSmiTagUint32 * node, const maglev::ProcessingState & state) [inline]
Definition at line 3864 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    SetMap(node,
           __ ConvertUntaggedToJSPrimitiveOrDeopt(
               Map(node->input()), frame_state,
               ConvertUntaggedToJSPrimitiveOrDeoptOp::JSPrimitiveKind::kSmi,
               RegisterRepresentation::Word32(),
               ConvertUntaggedToJSPrimitiveOrDeoptOp::InputInterpretation::
                   kUnsigned,
               node->eager_deopt_info()->feedback_to_update()));
    return maglev::ProcessResult::kContinue;
  }
References __, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::CheckedSmiTagUint32::input(), v8::internal::maglev::kContinue, v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOrDeoptOp::kSmi, v8::internal::compiler::kUnsigned, Map(), SetMap(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word32().
Process() [61/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckedSmiUntag * node, const maglev::ProcessingState & state) [inline]
Definition at line 3838 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    SetMap(node,
           __ CheckedSmiUntag(Map(node->input()), frame_state,
                              node->eager_deopt_info()->feedback_to_update()));
    return maglev::ProcessResult::kContinue;
  }
References __, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::CheckedSmiUntag::input(), v8::internal::maglev::kContinue, Map(), and SetMap().
Process() [62/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckedTruncateFloat64ToInt32 * node, const maglev::ProcessingState & state) [inline]
Definition at line 4464 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    SetMap(node, __ ChangeFloat64ToInt32OrDeopt(
                     Map(node->input()), frame_state,
                     CheckForMinusZeroMode::kCheckForMinusZero,
Process() [63/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckedTruncateFloat64ToUint32 * node, const maglev::ProcessingState & state) [inline]
Definition at line 4473 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    SetMap(node, __ ChangeFloat64ToUint32OrDeopt(
                     Map(node->input()), frame_state,
                     CheckForMinusZeroMode::kCheckForMinusZero,
Process() [64/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckedTruncateNumberOrOddballToInt32 * node, const maglev::ProcessingState & state) [inline]
Definition at line 4482 of file turbolev-graph-builder.cc.
                                          {
    TruncateJSPrimitiveToUntaggedOrDeoptOp::InputRequirement input_requirement;
    switch (node->conversion_type()) {
      case maglev::TaggedToFloat64ConversionType::kOnlyNumber:
        input_requirement =
            TruncateJSPrimitiveToUntaggedOrDeoptOp::InputRequirement::kNumber;
        break;
      case maglev::TaggedToFloat64ConversionType::kNumberOrBoolean:
        input_requirement = TruncateJSPrimitiveToUntaggedOrDeoptOp::
            InputRequirement::kNumberOrBoolean;
        break;
      case maglev::TaggedToFloat64ConversionType::kNumberOrOddball:
        input_requirement = TruncateJSPrimitiveToUntaggedOrDeoptOp::
            InputRequirement::kNumberOrOddball;
        break;
    }
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    SetMap(
        node,
        __ TruncateJSPrimitiveToUntaggedOrDeopt(
            Map(node->input()), frame_state,
            TruncateJSPrimitiveToUntaggedOrDeoptOp::UntaggedKind::kInt32,
Process() [65/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckedUint32ToInt32 * node, const maglev::ProcessingState & state) [inline]
Definition at line 4395 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    __ DeoptimizeIf(__ Int32LessThan(Map(node->input()), 0), frame_state,
                    DeoptimizeReason::kNotInt32,
                    node->eager_deopt_info()->feedback_to_update());
Process() [66/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckFloat64SameValue * node, const maglev::ProcessingState & state) [inline]
Definition at line 2464 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    __ DeoptimizeIfNot(__ Float64SameValue(Map(node->target_input()),
                                           node->value().get_scalar()),
                       frame_state, node->deoptimize_reason(),
                       node->eager_deopt_info()->feedback_to_update());
    return maglev::ProcessResult::kContinue;
  }
References __, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::Float64::get_scalar(), v8::internal::maglev::kContinue, Map(), v8::internal::maglev::CheckFloat64SameValue::target_input(), and v8::internal::maglev::CheckFloat64SameValue::value().
Process() [67/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckHeapObject * node, const maglev::ProcessingState & state) [inline]
Definition at line 2335 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    __ DeoptimizeIf(__ ObjectIsSmi(Map(node->receiver_input())), frame_state,
                    DeoptimizeReason::kSmi,
                    node->eager_deopt_info()->feedback_to_update());
    return maglev::ProcessResult::kContinue;
  }
References __, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::kContinue, v8::internal::compiler::kSmi, Map(), and v8::internal::maglev::CheckHeapObject::receiver_input().
Process() [68/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckHoleyFloat64IsSmi * node, const maglev::ProcessingState & state) [inline]
Definition at line 2307 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    V<Word32> w32 = __ ChangeFloat64ToInt32OrDeopt(
        Map(node->input()), frame_state,
        CheckForMinusZeroMode::kCheckForMinusZero,
        node->eager_deopt_info()->feedback_to_update());
    if (!SmiValuesAre32Bits()) {
      DeoptIfInt32IsNotSmi(w32, frame_state,
                           node->eager_deopt_info()->feedback_to_update());
    }
    return maglev::ProcessResult::kContinue;
  }
References __, DeoptIfInt32IsNotSmi(), GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::CheckHoleyFloat64IsSmi::input(), v8::internal::compiler::kCheckForMinusZero, v8::internal::maglev::kContinue, Map(), and v8::internal::SmiValuesAre32Bits().
Process() [69/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckHoleyFloat64NotHole * node, const maglev::ProcessingState & state) [inline]
Definition at line 2579 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    __ DeoptimizeIf(__ Float64IsHole(Map(node->float64_input())), frame_state,
                    DeoptimizeReason::kHole,
                    node->eager_deopt_info()->feedback_to_update());
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::CheckHoleyFloat64NotHole::float64_input(), GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::kContinue, and Map().
Process() [70/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckInstanceType * node, const maglev::ProcessingState & state) [inline]
Definition at line 2543 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    __ CheckInstanceType(
        Map(node->receiver_input()), frame_state,
        node->eager_deopt_info()->feedback_to_update(),
        node->first_instance_type(), node->last_instance_type(),
        node->check_type() != maglev::CheckType::kOmitHeapObjectCheck);
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::CheckInstanceType::check_type(), v8::internal::maglev::CheckInstanceType::first_instance_type(), GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::kContinue, v8::internal::maglev::kOmitHeapObjectCheck, v8::internal::maglev::CheckInstanceType::last_instance_type(), Map(), and v8::internal::maglev::CheckInstanceType::receiver_input().
Process() [71/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckInt32Condition * node, const maglev::ProcessingState & state) [inline]
Definition at line 2587 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    bool negate_result = false;
    V<Word32> cmp = ConvertInt32Compare(node->left_input(), node->right_input(),
                                        node->condition(), &negate_result);
    if (negate_result) {
      __ DeoptimizeIf(cmp, frame_state, node->deoptimize_reason(),
                      node->eager_deopt_info()->feedback_to_update());
    } else {
      __ DeoptimizeIfNot(cmp, frame_state, node->deoptimize_reason(),
                         node->eager_deopt_info()->feedback_to_update());
    }
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::CheckInt32Condition::condition(), ConvertInt32Compare(), GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::kContinue, v8::internal::maglev::CheckInt32Condition::left_input(), and v8::internal::maglev::CheckInt32Condition::right_input().
Process() [72/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckInt32IsSmi * node, const maglev::ProcessingState & state) [inline]
Definition at line 2279 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    DeoptIfInt32IsNotSmi(node->input(), frame_state,
                         node->eager_deopt_info()->feedback_to_update());
    return maglev::ProcessResult::kContinue;
  }
References DeoptIfInt32IsNotSmi(), GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::CheckInt32IsSmi::input(), and v8::internal::maglev::kContinue.
Process() [73/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckIntPtrIsSmi * node, const maglev::ProcessingState & state) [inline]
Definition at line 2295 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    __ DeoptimizeIfNot(
        __ UintPtrLessThanOrEqual(Map(node->input()), Smi::kMaxValue),
        frame_state, DeoptimizeReason::kNotASmi,
        node->eager_deopt_info()->feedback_to_update());
    // TODO(388844115): Rename the IntPtr in Maglev to make it clear it's
    // non-negative.
    return maglev::ProcessResult::kContinue;
  }
References __, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::CheckIntPtrIsSmi::input(), v8::internal::maglev::kContinue, v8::internal::Smi::kMaxValue, and Map().
Process() [74/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckJSDataViewBounds * node, const maglev::ProcessingState & state) [inline]
Definition at line 3332 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    // Normal DataView (backed by AB / SAB) or non-length tracking backed by
    // GSAB.
    V<WordPtr> byte_length =
        __ LoadField<WordPtr>(Map<JSTypedArray>(node->receiver_input()),
                              AccessBuilder::ForJSDataViewByteLength());
    int element_size = ExternalArrayElementSize(node->element_type());
    if (element_size > 1) {
      // For element_size larger than 1, we need to make sure that {index} is
      // less than {byte_length}, but also that {index+element_size} is less
      // than {byte_length}. We do this by subtracting {element_size-1} from
      // {byte_length}: if the resulting length is greater than 0, then we can
      // just treat {element_size} as 1 and check if {index} is less than this
      // new {byte_length}.
      DCHECK(element_size == 2 || element_size == 4 || element_size == 8);
      byte_length = __ WordPtrSub(byte_length, element_size - 1);
      __ DeoptimizeIf(__ IntPtrLessThan(byte_length, 0), frame_state,
                      DeoptimizeReason::kOutOfBounds,
                      node->eager_deopt_info()->feedback_to_update());
    }
    __ DeoptimizeIfNot(
        __ Uint32LessThan(Map<Word32>(node->index_input()),
                          __ TruncateWordPtrToWord32(byte_length)),
        frame_state, DeoptimizeReason::kOutOfBounds,
        node->eager_deopt_info()->feedback_to_update());
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::DCHECK(), v8::internal::maglev::CheckJSDataViewBounds::element_type(), v8::internal::compiler::ExternalArrayElementSize(), v8::internal::compiler::AccessBuilder::ForJSDataViewByteLength(), GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::CheckJSDataViewBounds::index_input(), v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::IntPtrLessThan(), v8::internal::maglev::kContinue, v8::internal::wasm::anonymous_namespace{wasm-external-refs.cc}::kOutOfBounds, and v8::internal::maglev::CheckJSDataViewBounds::receiver_input().
Process() [75/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckJSReceiverOrNullOrUndefined * node, const maglev::ProcessingState & state) [inline]
Definition at line 3606 of file turbolev-graph-builder.cc.
                                                                    {
    V<Object> object = Map(node->object_input());
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    ObjectIsOp::InputAssumptions assumptions;
    switch (node->check_type()) {
      case maglev::CheckType::kCheckHeapObject:
        assumptions = ObjectIsOp::InputAssumptions::kNone;
        break;
      case maglev::CheckType::kOmitHeapObjectCheck:
        assumptions = ObjectIsOp::InputAssumptions::kHeapObject;
        break;
    }
    __ DeoptimizeIfNot(
        __ ObjectIs(object, ObjectIsOp::Kind::kReceiverOrNullOrUndefined,
                    assumptions),
        frame_state, DeoptimizeReason::kNotAJavaScriptObjectOrNullOrUndefined,
        node->eager_deopt_info()->feedback_to_update());
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::CheckJSReceiverOrNullOrUndefined::check_type(), GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::kCheckHeapObject, v8::internal::maglev::kContinue, v8::internal::compiler::turboshaft::ObjectIsOp::kHeapObject, v8::internal::compiler::turboshaft::ObjectIsOp::kNone, v8::internal::maglev::kOmitHeapObjectCheck, v8::internal::compiler::turboshaft::ObjectIsOp::kReceiverOrNullOrUndefined, Map(), and v8::internal::maglev::CheckJSReceiverOrNullOrUndefined::object_input().
Process() [76/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckMaps * node, const maglev::ProcessingState & state) [inline]
Definition at line 2399 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    CheckMaps(Map(node->receiver_input()), frame_state, {},
              node->eager_deopt_info()->feedback_to_update(),
              node->maps().Clone(graph_zone()),
              node->check_type() == maglev::CheckType::kCheckHeapObject,
              CheckMapsFlag::kNone);
    return maglev::ProcessResult::kContinue;
  }
References v8::internal::maglev::CheckMaps::check_type(), CheckMaps(), GET_FRAME_STATE_MAYBE_ABORT, graph_zone(), v8::internal::maglev::kCheckHeapObject, v8::internal::maglev::kContinue, v8::internal::compiler::kNone, Map(), v8::internal::maglev::CheckMaps::maps(), and v8::internal::maglev::CheckMaps::receiver_input().
Process() [77/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckMapsWithAlreadyLoadedMap * node, const maglev::ProcessingState & state) [inline]
Definition at line 2409 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    CheckMaps(Map(node->object_input()), frame_state, Map(node->map_input()),
              node->eager_deopt_info()->feedback_to_update(),
              node->maps().Clone(graph_zone()), /*check_heap_object*/ false,
              CheckMapsFlag::kNone);
    return maglev::ProcessResult::kContinue;
  }
References CheckMaps(), GET_FRAME_STATE_MAYBE_ABORT, graph_zone(), v8::internal::maglev::kContinue, v8::internal::compiler::kNone, Map(), v8::internal::maglev::CheckMapsWithAlreadyLoadedMap::map_input(), v8::internal::maglev::CheckMapsWithAlreadyLoadedMap::maps(), and v8::internal::maglev::CheckMapsWithAlreadyLoadedMap::object_input().
Process() [78/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckMapsWithMigration * node, const maglev::ProcessingState & state) [inline]
Definition at line 2418 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    CheckMaps(Map(node->receiver_input()), frame_state, {},
              node->eager_deopt_info()->feedback_to_update(),
              node->maps().Clone(graph_zone()),
              node->check_type() == maglev::CheckType::kCheckHeapObject,
              CheckMapsFlag::kTryMigrateInstance);
    return maglev::ProcessResult::kContinue;
  }
References v8::internal::maglev::CheckMapsWithMigration::check_type(), CheckMaps(), GET_FRAME_STATE_MAYBE_ABORT, graph_zone(), v8::internal::maglev::kCheckHeapObject, v8::internal::maglev::kContinue, v8::internal::compiler::kTryMigrateInstance, Map(), v8::internal::maglev::CheckMapsWithMigration::maps(), and v8::internal::maglev::CheckMapsWithMigration::receiver_input().
Process() [79/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckMapsWithMigrationAndDeopt * node, const maglev::ProcessingState & state) [inline]
Definition at line 2428 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    CheckMaps(Map(node->receiver_input()), frame_state, {},
              node->eager_deopt_info()->feedback_to_update(),
              node->maps().Clone(graph_zone()),
              node->check_type() == maglev::CheckType::kCheckHeapObject,
              CheckMapsFlag::kTryMigrateInstanceAndDeopt);
    return maglev::ProcessResult::kContinue;
  }
References v8::internal::maglev::CheckMapsWithMigrationAndDeopt::check_type(), CheckMaps(), GET_FRAME_STATE_MAYBE_ABORT, graph_zone(), v8::internal::maglev::kCheckHeapObject, v8::internal::maglev::kContinue, v8::internal::compiler::kTryMigrateInstanceAndDeopt, Map(), v8::internal::maglev::CheckMapsWithMigrationAndDeopt::maps(), and v8::internal::maglev::CheckMapsWithMigrationAndDeopt::receiver_input().
Process() [80/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckNotHole * node, const maglev::ProcessingState & state) [inline]
Definition at line 2571 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    __ DeoptimizeIf(RootEqual(node->object_input(), RootIndex::kTheHoleValue),
                    frame_state, DeoptimizeReason::kHole,
                    node->eager_deopt_info()->feedback_to_update());
    return maglev::ProcessResult::kContinue;
  }
References __, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::kContinue, v8::internal::maglev::CheckNotHole::object_input(), and RootEqual().
Process() [81/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckNumber * node, const maglev::ProcessingState & state) [inline]
Definition at line 2320 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    V<Object> input = Map(node->receiver_input());
    V<Word32> check;
    if (node->mode() == Object::Conversion::kToNumeric) {
      check = __ ObjectIsNumberOrBigInt(input);
    } else {
      DCHECK_EQ(node->mode(), Object::Conversion::kToNumber);
      check = __ ObjectIsNumber(input);
    }
    __ DeoptimizeIfNot(check, frame_state, DeoptimizeReason::kNotANumber,
                       node->eager_deopt_info()->feedback_to_update());
    return maglev::ProcessResult::kContinue;
  }
References __, DCHECK_EQ, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::kContinue, v8::internal::Object::kToNumber, v8::internal::Object::kToNumeric, Map(), v8::internal::maglev::CheckNumber::mode(), and v8::internal::maglev::CheckNumber::receiver_input().
Process() [82/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckpointedJump * node, const maglev::ProcessingState & state) [inline]
Definition at line 3457 of file turbolev-graph-builder.cc.
                                                                    {
    BuildJump(node->target());
    return maglev::ProcessResult::kContinue;
  }
References BuildJump(), and v8::internal::maglev::kContinue.
Process() [83/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckSeqOneByteString * node, const maglev::ProcessingState & state) [inline]
Definition at line 2486 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    ObjectIsOp::InputAssumptions input_assumptions =
        node->check_type() == maglev::CheckType::kCheckHeapObject
            ? ObjectIsOp::InputAssumptions::kNone
            : ObjectIsOp::InputAssumptions::kHeapObject;
    // TODO(leszeks): Tighter check.
    V<Word32> check = __ ObjectIs(Map(node->receiver_input()),
                                  ObjectIsOp::Kind::kString, input_assumptions);
    __ DeoptimizeIfNot(check, frame_state, DeoptimizeReason::kNotAString,
                       node->eager_deopt_info()->feedback_to_update());
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::CheckSeqOneByteString::check_type(), GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::kCheckHeapObject, v8::internal::maglev::kContinue, v8::internal::compiler::turboshaft::ObjectIsOp::kHeapObject, v8::internal::compiler::turboshaft::ObjectIsOp::kNone, v8::internal::compiler::turboshaft::ObjectIsOp::kString, Map(), and v8::internal::maglev::CheckSeqOneByteString::receiver_input().
Process() [84/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckSmi * node, const maglev::ProcessingState & state) [inline]
Definition at line 2271 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    __ DeoptimizeIfNot(__ ObjectIsSmi(Map(node->receiver_input())), frame_state,
                       DeoptimizeReason::kNotASmi,
                       node->eager_deopt_info()->feedback_to_update());
    return maglev::ProcessResult::kContinue;
  }
References __, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::kContinue, Map(), and v8::internal::maglev::CheckSmi::receiver_input().
Process() [85/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckString * node, const maglev::ProcessingState & state) [inline]
Definition at line 2473 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    ObjectIsOp::InputAssumptions input_assumptions =
        node->check_type() == maglev::CheckType::kCheckHeapObject
            ? ObjectIsOp::InputAssumptions::kNone
            : ObjectIsOp::InputAssumptions::kHeapObject;
    V<Word32> check = __ ObjectIs(Map(node->receiver_input()),
                                  ObjectIsOp::Kind::kString, input_assumptions);
    __ DeoptimizeIfNot(check, frame_state, DeoptimizeReason::kNotAString,
                       node->eager_deopt_info()->feedback_to_update());
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::CheckString::check_type(), GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::kCheckHeapObject, v8::internal::maglev::kContinue, v8::internal::compiler::turboshaft::ObjectIsOp::kHeapObject, v8::internal::compiler::turboshaft::ObjectIsOp::kNone, v8::internal::compiler::turboshaft::ObjectIsOp::kString, Map(), and v8::internal::maglev::CheckString::receiver_input().
Process() [86/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckStringOrOddball * node, const maglev::ProcessingState & state) [inline]
Definition at line 2515 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    ObjectIsOp::InputAssumptions input_assumptions =
        node->check_type() == maglev::CheckType::kCheckHeapObject
            ? ObjectIsOp::InputAssumptions::kNone
            : ObjectIsOp::InputAssumptions::kHeapObject;
    V<Word32> check =
        __ ObjectIs(Map(node->receiver_input()),
                    ObjectIsOp::Kind::kStringOrOddball, input_assumptions);
    __ DeoptimizeIfNot(check, frame_state,
                       DeoptimizeReason::kNotAStringOrOddball,
                       node->eager_deopt_info()->feedback_to_update());
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::CheckStringOrOddball::check_type(), GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::kCheckHeapObject, v8::internal::maglev::kContinue, v8::internal::compiler::turboshaft::ObjectIsOp::kHeapObject, v8::internal::compiler::turboshaft::ObjectIsOp::kNone, v8::internal::compiler::turboshaft::ObjectIsOp::kStringOrOddball, Map(), and v8::internal::maglev::CheckStringOrOddball::receiver_input().
Process() [87/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckStringOrStringWrapper * node, const maglev::ProcessingState & state) [inline]
Definition at line 2500 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    ObjectIsOp::InputAssumptions input_assumptions =
        node->check_type() == maglev::CheckType::kCheckHeapObject
            ? ObjectIsOp::InputAssumptions::kNone
            : ObjectIsOp::InputAssumptions::kHeapObject;
    V<Word32> check = __ ObjectIs(Map(node->receiver_input()),
                                  ObjectIsOp::Kind::kStringOrStringWrapper,
                                  input_assumptions);
    __ DeoptimizeIfNot(check, frame_state,
                       DeoptimizeReason::kNotAStringOrStringWrapper,
                       node->eager_deopt_info()->feedback_to_update());
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::CheckStringOrStringWrapper::check_type(), GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::kCheckHeapObject, v8::internal::maglev::kContinue, v8::internal::compiler::turboshaft::ObjectIsOp::kHeapObject, v8::internal::compiler::turboshaft::ObjectIsOp::kNone, v8::internal::compiler::turboshaft::ObjectIsOp::kStringOrStringWrapper, Map(), and v8::internal::maglev::CheckStringOrStringWrapper::receiver_input().
Process() [88/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckSymbol * node, const maglev::ProcessingState & state) [inline]
Definition at line 2530 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    ObjectIsOp::InputAssumptions input_assumptions =
        node->check_type() == maglev::CheckType::kCheckHeapObject
            ? ObjectIsOp::InputAssumptions::kNone
            : ObjectIsOp::InputAssumptions::kHeapObject;
    V<Word32> check = __ ObjectIs(Map(node->receiver_input()),
                                  ObjectIsOp::Kind::kSymbol, input_assumptions);
    __ DeoptimizeIfNot(check, frame_state, DeoptimizeReason::kNotASymbol,
                       node->eager_deopt_info()->feedback_to_update());
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::CheckSymbol::check_type(), GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::kCheckHeapObject, v8::internal::maglev::kContinue, v8::internal::compiler::turboshaft::ObjectIsOp::kHeapObject, v8::internal::compiler::turboshaft::ObjectIsOp::kNone, v8::internal::compiler::turboshaft::ObjectIsOp::kSymbol, Map(), and v8::internal::maglev::CheckSymbol::receiver_input().
Process() [89/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckTypedArrayBounds * node, const maglev::ProcessingState & state) [inline]
Definition at line 3219 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    __ DeoptimizeIfNot(
        __ UintPtrLessThan(__ ChangeUint32ToUintPtr(Map(node->index_input())),
                           Map(node->length_input())),
        frame_state, DeoptimizeReason::kOutOfBounds,
        node->eager_deopt_info()->feedback_to_update());
    return maglev::ProcessResult::kContinue;
  }
References __, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::CheckTypedArrayBounds::index_input(), v8::internal::maglev::kContinue, v8::internal::wasm::anonymous_namespace{wasm-external-refs.cc}::kOutOfBounds, v8::internal::maglev::CheckTypedArrayBounds::length_input(), Map(), and v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::UintPtrLessThan().
Process() [90/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckTypedArrayNotDetached * node, const maglev::ProcessingState & state) [inline]
Definition at line 3423 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    __ DeoptimizeIf(
        __ ArrayBufferIsDetached(Map<JSArrayBufferView>(node->object_input())),
        frame_state, DeoptimizeReason::kArrayBufferWasDetached,
        node->eager_deopt_info()->feedback_to_update());
    return maglev::ProcessResult::kContinue;
  }
References __, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::kContinue, and v8::internal::maglev::CheckTypedArrayNotDetached::object_input().
Process() [91/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckUint32IsSmi * node, const maglev::ProcessingState & state) [inline]
Definition at line 2286 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    __ DeoptimizeIfNot(__ Uint32LessThan(Map(node->input()), Smi::kMaxValue),
                       frame_state, DeoptimizeReason::kNotASmi,
                       node->eager_deopt_info()->feedback_to_update());
    return maglev::ProcessResult::kContinue;
  }
References __, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::CheckUint32IsSmi::input(), v8::internal::maglev::kContinue, v8::internal::Smi::kMaxValue, and Map().
Process() [92/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckValue * node, const maglev::ProcessingState & state) [inline]
Definition at line 2447 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    __ DeoptimizeIfNot(__ TaggedEqual(Map(node->target_input()),
                                      __ HeapConstant(node->value().object())),
                       frame_state, node->deoptimize_reason(),
                       node->eager_deopt_info()->feedback_to_update());
    return maglev::ProcessResult::kContinue;
  }
References __, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::kContinue, Map(), v8::internal::compiler::HeapObjectRef::object(), v8::internal::maglev::CheckValue::target_input(), and v8::internal::maglev::CheckValue::value().
Process() [93/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckValueEqualsInt32 * node, const maglev::ProcessingState & state) [inline]
Definition at line 2456 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    __ DeoptimizeIfNot(__ Word32Equal(Map(node->target_input()), node->value()),
                       frame_state, node->deoptimize_reason(),
                       node->eager_deopt_info()->feedback_to_update());
    return maglev::ProcessResult::kContinue;
  }
References __, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::kContinue, Map(), v8::internal::maglev::CheckValueEqualsInt32::target_input(), v8::internal::maglev::CheckValueEqualsInt32::value(), and v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal().
Process() [94/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CheckValueEqualsString * node, const maglev::ProcessingState & state) [inline]
Definition at line 2845 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    __ CheckValueEqualsString(Map(node->target_input()), node->value(),
                              frame_state,
                              node->eager_deopt_info()->feedback_to_update());
    return maglev::ProcessResult::kContinue;
  }
References __, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::kContinue, Map(), v8::internal::maglev::CheckValueEqualsString::target_input(), and v8::internal::maglev::CheckValueEqualsString::value().
Process() [95/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::ConsStringMap * node, const maglev::ProcessingState & state) [inline]
Definition at line 2796 of file turbolev-graph-builder.cc.
                                                                    {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
Process() [96/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::Constant * node, const maglev::ProcessingState & state) [inline]
Definition at line 1054 of file turbolev-graph-builder.cc.
                                                                    {
    SetMap(node, __ HeapConstant(node->object().object()));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::kContinue, v8::internal::maglev::Constant::object(), v8::internal::compiler::HeapObjectRef::object(), and SetMap().
Process() [97/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::ConstantGapMove * , const maglev::ProcessingState &) [inline]
Definition at line 4781 of file turbolev-graph-builder.cc.
                                                              {
    // ConstantGapMove nodes are created by Maglev's register allocator, which
Process() [98/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::Construct * node, const maglev::ProcessingState & state) [inline]
Definition at line 1790 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
    base::SmallVector<OpIndex, 16> arguments;
    arguments.push_back(Map(node->function()));
    arguments.push_back(Map(node->new_target()));
    arguments.push_back(__ Word32Constant(node->num_args()));
#ifndef V8_TARGET_ARCH_ARM64
    arguments.push_back(__ WordPtrConstant(node->feedback().index()));
    arguments.push_back(__ HeapConstant(node->feedback().vector));
#endif
    for (auto arg : node->args()) {
      arguments.push_back(Map(arg));
    }
    arguments.push_back(Map(node->context()));
#ifndef V8_TARGET_ARCH_ARM64
    // Construct_WithFeedback can't be called from Turbofan on Arm64, because of
    // the stack alignment requirements: the feedback vector is dropped by
    // Construct_WithFeedback while the other arguments are passed through to
    // Construct. As a result, when the feedback vector is pushed on the stack,
    // it should be padded to 16-bytes, but there is no way to express this in
    // Turbofan.
    // Anyways, long-term we'll want to feedback-specialize Construct in the
    // frontend (ie, probably in Maglev), so we don't really need to adapt
    // Turbofan to be able to call Construct_WithFeedback on Arm64.
    static constexpr int kFeedbackVector = 1;
    int stack_arg_count = node->num_args() + kFeedbackVector;
    Builtin builtin = Builtin::kConstruct_WithFeedback;
#else
    int stack_arg_count = node->num_args();
    Builtin builtin = Builtin::kConstruct;
#endif
    GENERATE_AND_MAP_BUILTIN_CALL(node, builtin, frame_state,
                                  base::VectorOf(arguments), stack_arg_count);
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::Construct::args(), v8::internal::maglev::Construct::context(), v8::internal::maglev::Construct::feedback(), v8::internal::maglev::Construct::function(), GENERATE_AND_MAP_BUILTIN_CALL, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::compiler::FeedbackSource::index(), v8::internal::maglev::kContinue, Map(), v8::internal::maglev::Construct::new_target(), v8::internal::maglev::Construct::num_args(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), v8::internal::compiler::FeedbackSource::vector, and v8::base::VectorOf().
Process() [99/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::ConstructWithSpread * node, const maglev::ProcessingState & state) [inline]
Definition at line 1833 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
    base::SmallVector<OpIndex, 16> arguments;
    arguments.push_back(Map(node->function()));
    arguments.push_back(Map(node->new_target()));
    arguments.push_back(__ Word32Constant(node->num_args_no_spread()));
    arguments.push_back(Map(node->spread()));
    for (auto arg : node->args_no_spread()) {
      arguments.push_back(Map(arg));
    }
    arguments.push_back(Map(node->context()));
    GENERATE_AND_MAP_BUILTIN_CALL(node, Builtin::kConstructWithSpread,
                                  frame_state, base::VectorOf(arguments),
                                  node->num_args_no_spread());
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::ConstructWithSpread::args_no_spread(), v8::internal::maglev::ConstructWithSpread::context(), v8::internal::maglev::ConstructWithSpread::function(), GENERATE_AND_MAP_BUILTIN_CALL, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::kContinue, Map(), v8::internal::maglev::ConstructWithSpread::new_target(), v8::internal::maglev::ConstructWithSpread::num_args_no_spread(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), v8::internal::maglev::ConstructWithSpread::spread(), and v8::base::VectorOf().
Process() [100/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::ConvertHoleToUndefined * node, const maglev::ProcessingState & state) [inline]
Definition at line 4565 of file turbolev-graph-builder.cc.
                                                                    {
    V<Word32> cond = RootEqual(node->object_input(), RootIndex::kTheHoleValue);
    SetMap(node,
           __ Select(cond, undefined_value_, Map<Object>(node->object_input()),
                     RegisterRepresentation::Tagged(), BranchHint::kNone,
Process() [101/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::ConvertReceiver * node, const maglev::ProcessingState & state) [inline]
Definition at line 4574 of file turbolev-graph-builder.cc.
                                                                    {
    NoThrowingScopeRequired no_throws(node);
    Label<Object> done(this);
    Label<> non_js_receiver(this);
    V<Object> receiver = Map(node->receiver_input());
    GOTO_IF(__ IsSmi(receiver), non_js_receiver);
    GOTO_IF(__ JSAnyIsNotPrimitive(V<HeapObject>::Cast(receiver)), done,
            receiver);
    if (node->mode() != ConvertReceiverMode::kNotNullOrUndefined) {
      Label<> convert_global_proxy(this);
      GOTO_IF(__ RootEqual(receiver, RootIndex::kUndefinedValue, isolate_),
              convert_global_proxy);
      GOTO_IF_NOT(__ RootEqual(receiver, RootIndex::kNullValue, isolate_),
                  non_js_receiver);
      GOTO(convert_global_proxy);
      BIND(convert_global_proxy);
      GOTO(done,
           __ HeapConstant(
               node->native_context().global_proxy_object(broker_).object()));
    } else {
      GOTO(non_js_receiver);
    }
    BIND(non_js_receiver);
    GOTO(done, __ CallBuiltin_ToObject(
                   isolate_, __ HeapConstant(node->native_context().object()),
                   V<JSPrimitive>::Cast(receiver)));
    BIND(done, result);
    SetMap(node, result);
Process() [102/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CreateArrayLiteral * node, const maglev::ProcessingState & state) [inline]
Definition at line 2222 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
    OpIndex arguments[] = {__ HeapConstant(node->feedback().vector),
                           __ TaggedIndexConstant(node->feedback().index()),
                           __ HeapConstant(node->constant_elements().object()),
                           __ SmiConstant(Smi::FromInt(node->flags())),
                           native_context()};
    GENERATE_AND_MAP_BUILTIN_CALL(node,
                                  Builtin::kCreateArrayFromSlowBoilerplate,
                                  frame_state, base::VectorOf(arguments));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::CreateArrayLiteral::constant_elements(), v8::internal::maglev::CreateArrayLiteral::feedback(), v8::internal::maglev::CreateArrayLiteral::flags(), v8::internal::Smi::FromInt(), GENERATE_AND_MAP_BUILTIN_CALL, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::compiler::FeedbackSource::index(), v8::internal::maglev::kContinue, native_context(), v8::internal::compiler::HeapObjectRef::object(), v8::internal::compiler::FeedbackSource::vector, and v8::base::VectorOf().
Process() [103/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CreateClosure * node, const maglev::ProcessingState & state) [inline]
Definition at line 1694 of file turbolev-graph-builder.cc.
                                                                    {
    NoThrowingScopeRequired no_throws(node);
    V<Context> context = Map(node->context());
    V<SharedFunctionInfo> shared_function_info =
        __ HeapConstant(node->shared_function_info().object());
    V<FeedbackCell> feedback_cell =
        __ HeapConstant(node->feedback_cell().object());
    V<JSFunction> closure;
    if (node->pretenured()) {
      closure = __ CallRuntime_NewClosure_Tenured(
          isolate_, context, shared_function_info, feedback_cell);
    } else {
      closure = __ CallRuntime_NewClosure(isolate_, context,
                                          shared_function_info, feedback_cell);
    }
    SetMap(node, closure);
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::CreateClosure::context(), v8::internal::maglev::CreateClosure::feedback_cell(), isolate_, v8::internal::maglev::kContinue, Map(), v8::internal::compiler::FeedbackCellRef::object(), v8::internal::compiler::SharedFunctionInfoRef::object(), v8::internal::maglev::CreateClosure::pretenured(), SetMap(), and v8::internal::maglev::CreateClosure::shared_function_info().
Process() [104/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CreateFastArrayElements * node, const maglev::ProcessingState & state) [inline]
Definition at line 2213 of file turbolev-graph-builder.cc.
                                                                    {
    V<Word32> length = Map(node->length_input());
    SetMap(node,
           __ NewArray(__ ChangeInt32ToIntPtr(length),
                       NewArrayOp::Kind::kObject, node->allocation_type()));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::CreateFastArrayElements::allocation_type(), v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::ChangeInt32ToIntPtr(), v8::internal::maglev::kContinue, v8::internal::compiler::turboshaft::NewArrayOp::kObject, v8::internal::length, v8::internal::maglev::CreateFastArrayElements::length_input(), Map(), v8::internal::NewArray(), and SetMap().
Process() [105/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CreateFunctionContext * node, const maglev::ProcessingState & state) [inline]
Definition at line 1657 of file turbolev-graph-builder.cc.
                                                                    {
    ThrowingScope throwing_scope(this, node);
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
    V<Context> context = Map(node->context());
    V<ScopeInfo> scope_info = __ HeapConstant(node->scope_info().object());
    if (node->scope_type() == FUNCTION_SCOPE) {
      SetMap(node, __ CallBuiltin_FastNewFunctionContextFunction(
                       isolate_, frame_state, context, scope_info,
                       node->slot_count(), ShouldLazyDeoptOnThrow(node)));
    } else {
      DCHECK_EQ(node->scope_type(), EVAL_SCOPE);
      SetMap(node, __ CallBuiltin_FastNewFunctionContextEval(
                       isolate_, frame_state, context, scope_info,
                       node->slot_count(), ShouldLazyDeoptOnThrow(node)));
    }
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::CreateFunctionContext::context(), DCHECK_EQ, v8::internal::EVAL_SCOPE, v8::internal::FUNCTION_SCOPE, GET_FRAME_STATE_MAYBE_ABORT, isolate_, v8::internal::maglev::kContinue, Map(), v8::internal::compiler::ScopeInfoRef::object(), v8::internal::maglev::CreateFunctionContext::scope_info(), v8::internal::maglev::CreateFunctionContext::scope_type(), SetMap(), ShouldLazyDeoptOnThrow(), and v8::internal::maglev::CreateFunctionContext::slot_count().
Process() [106/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CreateObjectLiteral * node, const maglev::ProcessingState & state) [inline]
Definition at line 2197 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
    OpIndex arguments[] = {
        __ HeapConstant(node->feedback().vector),
        __ TaggedIndexConstant(node->feedback().index()),
        __ HeapConstant(node->boilerplate_descriptor().object()),
        __ SmiConstant(Smi::FromInt(node->flags())), native_context()};
    GENERATE_AND_MAP_BUILTIN_CALL(node,
                                  Builtin::kCreateObjectFromSlowBoilerplate,
                                  frame_state, base::VectorOf(arguments));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::CreateObjectLiteral::boilerplate_descriptor(), v8::internal::maglev::CreateObjectLiteral::feedback(), v8::internal::maglev::CreateObjectLiteral::flags(), v8::internal::Smi::FromInt(), GENERATE_AND_MAP_BUILTIN_CALL, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::compiler::FeedbackSource::index(), v8::internal::maglev::kContinue, native_context(), v8::internal::compiler::ObjectBoilerplateDescriptionRef::object(), v8::internal::compiler::FeedbackSource::vector, and v8::base::VectorOf().
Process() [107/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CreateRegExpLiteral * node, const maglev::ProcessingState & state) [inline]
Definition at line 2168 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
    OpIndex arguments[] = {__ HeapConstant(node->feedback().vector),
                           __ TaggedIndexConstant(node->feedback().index()),
                           __ HeapConstant(node->pattern().object()),
                           __ SmiConstant(Smi::FromInt(node->flags())),
                           native_context()};
    GENERATE_AND_MAP_BUILTIN_CALL(node, Builtin::kCreateRegExpLiteral,
                                  frame_state, base::VectorOf(arguments));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::CreateRegExpLiteral::feedback(), v8::internal::maglev::CreateRegExpLiteral::flags(), v8::internal::Smi::FromInt(), GENERATE_AND_MAP_BUILTIN_CALL, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::compiler::FeedbackSource::index(), v8::internal::maglev::kContinue, native_context(), v8::internal::compiler::StringRef::object(), v8::internal::maglev::CreateRegExpLiteral::pattern(), v8::internal::compiler::FeedbackSource::vector, and v8::base::VectorOf().
Process() [108/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CreateShallowArrayLiteral * node, const maglev::ProcessingState & state) [inline]
Definition at line 2046 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
    OpIndex arguments[] = {__ HeapConstant(node->feedback().vector),
                           __ TaggedIndexConstant(node->feedback().index()),
                           __ HeapConstant(node->constant_elements().object()),
                           __ SmiConstant(Smi::FromInt(node->flags())),
                           native_context()};
    GENERATE_AND_MAP_BUILTIN_CALL(node, Builtin::kCreateShallowArrayLiteral,
                                  frame_state, base::VectorOf(arguments));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::CreateShallowArrayLiteral::constant_elements(), v8::internal::maglev::CreateShallowArrayLiteral::feedback(), v8::internal::maglev::CreateShallowArrayLiteral::flags(), v8::internal::Smi::FromInt(), GENERATE_AND_MAP_BUILTIN_CALL, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::compiler::FeedbackSource::index(), v8::internal::maglev::kContinue, native_context(), v8::internal::compiler::HeapObjectRef::object(), v8::internal::compiler::FeedbackSource::vector, and v8::base::VectorOf().
Process() [109/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::CreateShallowObjectLiteral * node, const maglev::ProcessingState & state) [inline]
Definition at line 2031 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
    OpIndex arguments[] = {
        __ HeapConstant(node->feedback().vector),
        __ TaggedIndexConstant(node->feedback().index()),
        __ HeapConstant(node->boilerplate_descriptor().object()),
        __ SmiConstant(Smi::FromInt(node->flags())), native_context()};
    GENERATE_AND_MAP_BUILTIN_CALL(node, Builtin::kCreateShallowObjectLiteral,
                                  frame_state, base::VectorOf(arguments));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::CreateShallowObjectLiteral::boilerplate_descriptor(), v8::internal::maglev::CreateShallowObjectLiteral::feedback(), v8::internal::maglev::CreateShallowObjectLiteral::flags(), v8::internal::Smi::FromInt(), GENERATE_AND_MAP_BUILTIN_CALL, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::compiler::FeedbackSource::index(), v8::internal::maglev::kContinue, native_context(), v8::internal::compiler::ObjectBoilerplateDescriptionRef::object(), v8::internal::compiler::FeedbackSource::vector, and v8::base::VectorOf().
Process() [110/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::Dead * , const maglev::ProcessingState &) [inline]
Definition at line 4763 of file turbolev-graph-builder.cc.
                                                                         {
    // Nothing to do; `Dead` is in Maglev to kill a node when removing it
Process() [111/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::DebugBreak * , const maglev::ProcessingState &) [inline]
Definition at line 4769 of file turbolev-graph-builder.cc.
                                                              {
Process() [112/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::DefineKeyedOwnGeneric * node, const maglev::ProcessingState & state) [inline]
Definition at line 1984 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
    OpIndex arguments[] = {Map(node->object_input()),
                           Map(node->key_input()),
                           Map(node->value_input()),
                           Map(node->flags_input()),
                           __ TaggedIndexConstant(node->feedback().index()),
                           __ HeapConstant(node->feedback().vector),
                           Map(node->context())};
    GENERATE_AND_MAP_BUILTIN_CALL(node, Builtin::kDefineKeyedOwnIC, frame_state,
                                  base::VectorOf(arguments));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::DefineKeyedOwnGeneric::context(), v8::internal::maglev::DefineKeyedOwnGeneric::feedback(), v8::internal::maglev::DefineKeyedOwnGeneric::flags_input(), GENERATE_AND_MAP_BUILTIN_CALL, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::compiler::FeedbackSource::index(), v8::internal::maglev::kContinue, v8::internal::maglev::DefineKeyedOwnGeneric::key_input(), Map(), v8::internal::maglev::DefineKeyedOwnGeneric::object_input(), v8::internal::maglev::DefineKeyedOwnGeneric::value_input(), v8::internal::compiler::FeedbackSource::vector, and v8::base::VectorOf().
Process() [113/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::DefineNamedOwnGeneric * node, const maglev::ProcessingState & state) [inline]
Definition at line 2001 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
    OpIndex arguments[] = {Map(node->object_input()),
                           __ HeapConstant(node->name().object()),
                           Map(node->value_input()),
                           __ TaggedIndexConstant(node->feedback().index()),
                           __ HeapConstant(node->feedback().vector),
                           Map(node->context())};
    GENERATE_AND_MAP_BUILTIN_CALL(node, Builtin::kDefineNamedOwnIC, frame_state,
                                  base::VectorOf(arguments));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::DefineNamedOwnGeneric::context(), v8::internal::maglev::DefineNamedOwnGeneric::feedback(), GENERATE_AND_MAP_BUILTIN_CALL, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::compiler::FeedbackSource::index(), v8::internal::maglev::kContinue, Map(), v8::internal::maglev::DefineNamedOwnGeneric::name(), v8::internal::compiler::NameRef::object(), v8::internal::maglev::DefineNamedOwnGeneric::object_input(), v8::internal::maglev::DefineNamedOwnGeneric::value_input(), v8::internal::compiler::FeedbackSource::vector, and v8::base::VectorOf().
Process() [114/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::DeleteProperty * node, const maglev::ProcessingState & state) [inline]
Definition at line 2143 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
    OpIndex arguments[] = {
        Map(node->object()), Map(node->key()),
        __ SmiConstant(Smi::FromInt(static_cast<int>(node->mode()))),
        Map(node->context())};
    GENERATE_AND_MAP_BUILTIN_CALL(node, Builtin::kDeleteProperty, frame_state,
                                  base::VectorOf(arguments));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::DeleteProperty::context(), v8::internal::Smi::FromInt(), GENERATE_AND_MAP_BUILTIN_CALL, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::kContinue, v8::internal::maglev::DeleteProperty::key(), Map(), v8::internal::maglev::DeleteProperty::mode(), v8::internal::maglev::DeleteProperty::object(), and v8::base::VectorOf().
Process() [115/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::Deopt * node, const maglev::ProcessingState & state) [inline]
Definition at line 4702 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    __ Deoptimize(frame_state, node->deoptimize_reason(),
Process() [116/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::EnsureWritableFastElements * node, const maglev::ProcessingState & state) [inline]
Definition at line 2629 of file turbolev-graph-builder.cc.
                                                                    {
    SetMap(node, __ EnsureWritableFastElements(Map(node->object_input()),
                                               Map(node->elements_input())));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::EnsureWritableFastElements::elements_input(), v8::internal::maglev::kContinue, Map(), v8::internal::maglev::EnsureWritableFastElements::object_input(), and SetMap().
Process() [117/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::ExtendPropertiesBackingStore * node, const maglev::ProcessingState & state) [inline]
Definition at line 2650 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    SetMap(node, __ ExtendPropertiesBackingStore(
                     Map(node->property_array_input()),
                     Map(node->object_input()), node->old_length(), frame_state,
                     node->eager_deopt_info()->feedback_to_update()));
    return maglev::ProcessResult::kContinue;
  }
References __, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::kContinue, Map(), v8::internal::maglev::ExtendPropertiesBackingStore::object_input(), v8::internal::maglev::ExtendPropertiesBackingStore::old_length(), v8::internal::maglev::ExtendPropertiesBackingStore::property_array_input(), and SetMap().
Process() [118/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::FastCreateClosure * node, const maglev::ProcessingState & state) [inline]
Definition at line 1677 of file turbolev-graph-builder.cc.
                                                                    {
    NoThrowingScopeRequired no_throws(node);
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
    V<Context> context = Map(node->context());
    V<SharedFunctionInfo> shared_function_info =
        __ HeapConstant(node->shared_function_info().object());
    V<FeedbackCell> feedback_cell =
        __ HeapConstant(node->feedback_cell().object());
    SetMap(node,
           __ CallBuiltin_FastNewClosure(isolate_, frame_state, context,
                                         shared_function_info, feedback_cell));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::FastCreateClosure::context(), v8::internal::maglev::FastCreateClosure::feedback_cell(), GET_FRAME_STATE_MAYBE_ABORT, isolate_, v8::internal::maglev::kContinue, Map(), v8::internal::compiler::FeedbackCellRef::object(), v8::internal::compiler::SharedFunctionInfoRef::object(), SetMap(), and v8::internal::maglev::FastCreateClosure::shared_function_info().
Process() [119/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::Float64Abs * node, const maglev::ProcessingState & state) [inline]
Definition at line 4084 of file turbolev-graph-builder.cc.
                                                                    {
Process() [120/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::Float64Compare * node, const maglev::ProcessingState & state) [inline]
Definition at line 3481 of file turbolev-graph-builder.cc.
                                                                    {
    V<Word32> bool_res =
        ConvertCompare<Float64>(node->left_input(), node->right_input(),
                                node->operation(), Sign::kSigned);
    SetMap(node, ConvertWord32ToJSBool(bool_res));
    return maglev::ProcessResult::kContinue;
  }
References ConvertWord32ToJSBool(), v8::internal::maglev::kContinue, kSigned, v8::internal::maglev::Float64Compare::left_input(), v8::internal::maglev::Float64Compare::operation(), v8::internal::maglev::Float64Compare::right_input(), and SetMap().
Process() [121/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::Float64Constant * node, const maglev::ProcessingState & state) [inline]
Definition at line 1083 of file turbolev-graph-builder.cc.
                                                                    {
    SetMap(node, __ Float64Constant(node->value()));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::kContinue, SetMap(), and v8::internal::maglev::Float64Constant::value().
Process() [122/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::Float64CountLeadingZeros * node, const maglev::ProcessingState & state) [inline]
Definition at line 3989 of file turbolev-graph-builder.cc.
                                                                    {
    SetMap(node, __ Word32CountLeadingZeros(
                     __ JSTruncateFloat64ToWord32(Map(node->input()))));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::Float64CountLeadingZeros::input(), v8::internal::maglev::kContinue, Map(), and SetMap().
Process() [123/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::Float64Ieee754Unary * node, const maglev::ProcessingState & state) [inline]
Definition at line 4111 of file turbolev-graph-builder.cc.
                                                                    {
    FloatUnaryOp::Kind kind;
    switch (node->ieee_function()) {
#define CASE(MathName, ExpName, EnumName) \
  case maglev::Float64Ieee754Unary::Ieee754Function::k##EnumName: \
    kind = FloatUnaryOp::Kind::k##EnumName; \
    break;
      IEEE_754_UNARY_LIST(CASE)
#undef CASE
    }
Process() [124/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::Float64Negate * node, const maglev::ProcessingState & state) [inline]
Definition at line 4079 of file turbolev-graph-builder.cc.
                                                                    {
Process() [125/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::Float64Round * node, const maglev::ProcessingState & state) [inline]
Definition at line 4089 of file turbolev-graph-builder.cc.
                                                                    {
    if (node->kind() == maglev::Float64Round::Kind::kFloor) {
      SetMap(node, __ Float64RoundDown(Map(node->input())));
    } else if (node->kind() == maglev::Float64Round::Kind::kCeil) {
      SetMap(node, __ Float64RoundUp(Map(node->input())));
    } else {
      DCHECK_EQ(node->kind(), maglev::Float64Round::Kind::kNearest);
      // Nearest rounds to +infinity on ties. We emulate this by rounding up and
      // adjusting if the difference exceeds 0.5 (like SimplifiedLowering does
      // for lower Float64Round).
      OpIndex input = Map(node->input());
      ScopedVar<Float64, AssemblerT> result(this, __ Float64RoundUp(input));
      IF_NOT (__ Float64LessThanOrEqual(__ Float64Sub(result, 0.5), input)) {
        result = __ Float64Sub(result, 1.0);
      }
      SetMap(node, result);
Process() [126/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::Float64ToBoolean * node, const maglev::ProcessingState & state) [inline]
Definition at line 4256 of file turbolev-graph-builder.cc.
                                                                    {
    V<Word32> condition = Float64ToBit(Map(node->value()));
Process() [127/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::Float64ToHeapNumberForField * node, const maglev::ProcessingState & state) [inline]
Definition at line 4290 of file turbolev-graph-builder.cc.
                                                                    {
    // We don't use ConvertUntaggedToJSPrimitive but instead the lower level
    // AllocateHeapNumberWithValue helper, because ConvertUntaggedToJSPrimitive
    // can be GVNed, which we don't want for Float64ToHeapNumberForField, since
    // it creates a mutable HeapNumber, that will then be owned by an object
    // field.
    SetMap(node, __ AllocateHeapNumberWithValue(Map(node->input()),
Process() [128/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::Float64ToTagged * node, const maglev::ProcessingState & state) [inline]
Definition at line 4279 of file turbolev-graph-builder.cc.
                                                                    {
Process() [129/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::Float64ToUint8Clamped * node, const maglev::ProcessingState & state) [inline]
Definition at line 4658 of file turbolev-graph-builder.cc.
                                                                    {
Process() [130/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::ForInNext * node, const maglev::ProcessingState & state) [inline]
Definition at line 2254 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
    OpIndex arguments[] = {__ WordPtrConstant(node->feedback().index()),
                           Map(node->receiver()),
                           Map(node->cache_array()),
                           Map(node->cache_type()),
                           Map(node->cache_index()),
                           __ HeapConstant(node->feedback().vector),
                           Map(node->context())};
    GENERATE_AND_MAP_BUILTIN_CALL(node, Builtin::kForInNext, frame_state,
                                  base::VectorOf(arguments));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::ForInNext::cache_array(), v8::internal::maglev::ForInNext::cache_index(), v8::internal::maglev::ForInNext::cache_type(), v8::internal::maglev::ForInNext::context(), v8::internal::maglev::ForInNext::feedback(), GENERATE_AND_MAP_BUILTIN_CALL, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::compiler::FeedbackSource::index(), v8::internal::maglev::kContinue, Map(), v8::internal::maglev::ForInNext::receiver(), v8::internal::compiler::FeedbackSource::vector, and v8::base::VectorOf().
Process() [131/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::ForInPrepare * node, const maglev::ProcessingState & state) [inline]
Definition at line 2238 of file turbolev-graph-builder.cc.
                                                                    {
    OpIndex arguments[] = {Map(node->enumerator()),
                           __ TaggedIndexConstant(node->feedback().index()),
                           __ HeapConstant(node->feedback().vector),
                           Map(node->context())};
    V<Any> call =
        GenerateBuiltinCall(node, Builtin::kForInPrepare,
                            OptionalV<turboshaft::FrameState>::Nullopt(),
                            base::VectorOf(arguments));
    SetMap(node, __ Projection(call, 0, RegisterRepresentation::Tagged()));
    second_return_value_ = V<Object>::Cast(
        __ Projection(call, 1, RegisterRepresentation::Tagged()));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::compiler::turboshaft::V< T >::Cast(), v8::internal::maglev::ForInPrepare::context(), v8::internal::maglev::ForInPrepare::enumerator(), v8::internal::maglev::ForInPrepare::feedback(), GenerateBuiltinCall(), v8::internal::compiler::FeedbackSource::index(), v8::internal::maglev::kContinue, Map(), second_return_value_, SetMap(), v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), v8::internal::compiler::FeedbackSource::vector, and v8::base::VectorOf().
Process() [132/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::FunctionEntryStackCheck * node, const maglev::ProcessingState & state) [inline]
Definition at line 1171 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
    __ JSFunctionEntryStackCheck(native_context(), frame_state);
    return maglev::ProcessResult::kContinue;
  }
References __, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::kContinue, and native_context().
Process() [133/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::GapMove * , const maglev::ProcessingState &) [inline]
Definition at line 4775 of file turbolev-graph-builder.cc.
                                                              {
    // GapMove nodes are created by Maglev's register allocator, which
Process() [134/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::GeneratorRestoreRegister * node, const maglev::ProcessingState & state) [inline]
Definition at line 4733 of file turbolev-graph-builder.cc.
                                                                    {
    V<FixedArray> array = Map(node->array_input());
    V<Object> result =
        __ LoadTaggedField(array, FixedArray::OffsetOfElementAt(node->index()));
    __ Store(array, Map(node->stale_input()), StoreOp::Kind::TaggedBase(),
             MemoryRepresentation::TaggedSigned(),
             WriteBarrierKind::kNoWriteBarrier,
             FixedArray::OffsetOfElementAt(node->index()));
    SetMap(node, result);
Process() [135/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::GeneratorStore * node, const maglev::ProcessingState & state) [inline]
Definition at line 4720 of file turbolev-graph-builder.cc.
                                                                    {
    base::SmallVector<OpIndex, 32> parameters_and_registers;
    int num_parameters_and_registers = node->num_parameters_and_registers();
    for (int i = 0; i < num_parameters_and_registers; i++) {
      parameters_and_registers.push_back(
          Map(node->parameters_and_registers(i)));
    }
    __ GeneratorStore(Map(node->context_input()), Map(node->generator_input()),
                      parameters_and_registers, node->suspend_id(),
Process() [136/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::GetIterator * node, const maglev::ProcessingState & state) [inline]
Definition at line 2017 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
    OpIndex arguments[] = {
        Map(node->receiver()), __ TaggedIndexConstant(node->load_slot()),
        __ TaggedIndexConstant(node->call_slot()),
        __ HeapConstant(node->feedback()), Map(node->context())};
    GENERATE_AND_MAP_BUILTIN_CALL(node, Builtin::kGetIteratorWithFeedback,
                                  frame_state, base::VectorOf(arguments));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::GetIterator::call_slot(), v8::internal::maglev::GetIterator::context(), v8::internal::maglev::GetIterator::feedback(), GENERATE_AND_MAP_BUILTIN_CALL, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::kContinue, v8::internal::maglev::GetIterator::load_slot(), Map(), v8::internal::maglev::GetIterator::receiver(), and v8::base::VectorOf().
Process() [137/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::GetKeyedGeneric * node, const maglev::ProcessingState & state) [inline]
Definition at line 1887 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
    OpIndex arguments[] = {Map(node->object_input()), Map(node->key_input()),
                           __ TaggedIndexConstant(node->feedback().index()),
                           __ HeapConstant(node->feedback().vector),
                           Map(node->context())};
    GENERATE_AND_MAP_BUILTIN_CALL(node, Builtin::kKeyedLoadIC, frame_state,
                                  base::VectorOf(arguments));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::GetKeyedGeneric::context(), v8::internal::maglev::GetKeyedGeneric::feedback(), GENERATE_AND_MAP_BUILTIN_CALL, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::compiler::FeedbackSource::index(), v8::internal::maglev::kContinue, v8::internal::maglev::GetKeyedGeneric::key_input(), Map(), v8::internal::maglev::GetKeyedGeneric::object_input(), v8::internal::compiler::FeedbackSource::vector, and v8::base::VectorOf().
Process() [138/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::GetSecondReturnedValue * node, const maglev::ProcessingState & state) [inline]
Definition at line 4794 of file turbolev-graph-builder.cc.
                                                                    {
    DCHECK(second_return_value_.valid());
    SetMap(node, second_return_value_);
#ifdef DEBUG
    second_return_value_ = V<Object>::Invalid();
#endif
Process() [139/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::GetTemplateObject * node, const maglev::ProcessingState & state) [inline]
Definition at line 2183 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
    OpIndex arguments[] = {
        __ HeapConstant(node->shared_function_info().object()),
        Map(node->description()), __ WordPtrConstant(node->feedback().index()),
        __ HeapConstant(node->feedback().vector), native_context()};
    GENERATE_AND_MAP_BUILTIN_CALL(node, Builtin::kGetTemplateObject,
                                  frame_state, base::VectorOf(arguments));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::GetTemplateObject::description(), v8::internal::maglev::GetTemplateObject::feedback(), GENERATE_AND_MAP_BUILTIN_CALL, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::compiler::FeedbackSource::index(), v8::internal::maglev::kContinue, Map(), native_context(), v8::internal::compiler::SharedFunctionInfoRef::object(), v8::internal::maglev::GetTemplateObject::shared_function_info(), v8::internal::compiler::FeedbackSource::vector, and v8::base::VectorOf().
Process() [140/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::HandleNoHeapWritesInterrupt * node, const maglev::ProcessingState &) [inline]
Definition at line 4822 of file turbolev-graph-builder.cc.
                                                              {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
Process() [141/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::HasInPrototypeChain * node, const maglev::ProcessingState & state) [inline]
Definition at line 2691 of file turbolev-graph-builder.cc.
                                                                    {
    ThrowingScope throwing_scope(this, node);
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
    SetMap(node, __ HasInPrototypeChain(Map(node->object()), node->prototype(),
                                        frame_state, native_context(),
                                        ShouldLazyDeoptOnThrow(node)));
    return maglev::ProcessResult::kContinue;
  }
References __, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::kContinue, Map(), native_context(), v8::internal::maglev::HasInPrototypeChain::object(), v8::internal::maglev::HasInPrototypeChain::prototype(), SetMap(), and ShouldLazyDeoptOnThrow().
Process() [142/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::HoleyFloat64IsHole * node, const maglev::ProcessingState & state) [inline]
Definition at line 4302 of file turbolev-graph-builder.cc.
                                                                    {
Process() [143/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::HoleyFloat64ToMaybeNanFloat64 * node, const maglev::ProcessingState & state) [inline]
Definition at line 4529 of file turbolev-graph-builder.cc.
                                                                    {
Process() [144/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::HoleyFloat64ToTagged * node, const maglev::ProcessingState & state) [inline]
Definition at line 4284 of file turbolev-graph-builder.cc.
                                                                    {
    SetMap(node,
Process() [145/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::Identity * node, const maglev::ProcessingState &) [inline]
Definition at line 4757 of file turbolev-graph-builder.cc.
                                                              {
Process() [146/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::InitialValue * node, const maglev::ProcessingState & state) [inline]
Definition at line 1105 of file turbolev-graph-builder.cc.
                                                                    {
    // TODO(dmercadier): InitialValues are much simpler in Maglev because they
    // are mapped directly to interpreter registers, whereas Turbofan changes
    // the indices, making everything more complex. We should try to have the
    // same InitialValues in Turboshaft as in Maglev, in order to simplify
    // things.
#ifdef DEBUG
    // We cannot use strdup or something that simple for {debug_name}, because
    // it has to be zone allocated rather than heap-allocated, since it won't be
    // freed and this would thus cause a leak.
    std::string reg_string_name = node->source().ToString();
    base::Vector<char> debug_name_arr =
        graph_zone()->NewVector<char>(reg_string_name.length() + /* \n */ 1);
    snprintf(debug_name_arr.data(), debug_name_arr.length(), "%s",
             reg_string_name.c_str());
    char* debug_name = debug_name_arr.data();
#else
    char* debug_name = nullptr;
#endif
    interpreter::Register source = node->source();
    V<Object> value;
    if (source.is_function_closure()) {
      // The function closure is a Parameter rather than an OsrValue even when
      // OSR-compiling.
      value = __ Parameter(Linkage::kJSCallClosureParamIndex,
                           RegisterRepresentation::Tagged(), debug_name);
    } else if (maglev_compilation_unit_->is_osr()) {
      int index;
      if (source.is_current_context()) {
        index = Linkage::kOsrContextSpillSlotIndex;
      } else if (source == interpreter::Register::virtual_accumulator()) {
        index = Linkage::kOsrAccumulatorRegisterIndex;
      } else if (source.is_parameter()) {
        index = source.ToParameterIndex();
      } else {
        // For registers, recreate the index computed by FillWithOsrValues in
        // BytecodeGraphBuilder.
        index = source.index() + InterpreterFrameConstants::kExtraSlotCount +
                maglev_compilation_unit_->parameter_count();
      }
      value = __ OsrValue(index);
    } else {
      int index = source.ToParameterIndex();
      if (source.is_current_context()) {
        index = Linkage::GetJSCallContextParamIndex(
            maglev_compilation_unit_->parameter_count());
      } else {
        index = source.ToParameterIndex();
      }
      value = __ Parameter(index, RegisterRepresentation::Tagged(), debug_name);
    }
    SetMap(node, value);
    return maglev::ProcessResult::kContinue;
  }
References __, v8::base::Vector< T >::data(), v8::internal::compiler::Linkage::GetJSCallContextParamIndex(), graph_zone(), v8::internal::interpreter::Register::index(), v8::internal::index, v8::internal::interpreter::Register::is_current_context(), v8::internal::interpreter::Register::is_function_closure(), v8::internal::maglev::MaglevCompilationUnit::is_osr(), v8::internal::interpreter::Register::is_parameter(), v8::internal::maglev::kContinue, v8::internal::compiler::Linkage::kJSCallClosureParamIndex, v8::internal::compiler::Linkage::kOsrAccumulatorRegisterIndex, v8::internal::compiler::Linkage::kOsrContextSpillSlotIndex, v8::base::Vector< T >::length(), maglev_compilation_unit_, v8::internal::Zone::NewVector(), v8::internal::maglev::MaglevCompilationUnit::parameter_count(), SetMap(), v8::internal::maglev::InitialValue::source(), v8::internal::string, v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), v8::internal::interpreter::Register::ToParameterIndex(), v8::internal::interpreter::Register::ToString(), v8::internal::value, and v8::internal::interpreter::Register::virtual_accumulator().
Process() [147/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::InlinedAllocation * node, const maglev::ProcessingState & state) [inline]
Definition at line 2619 of file turbolev-graph-builder.cc.
                                                                    {
    DCHECK(node->HasBeenAnalysed() &&
           node->HasEscaped()); // Would have been removed otherwise.
    V<HeapObject> alloc = Map(node->allocation_block());
    SetMap(node, __ BitcastWordPtrToHeapObject(__ WordPtrAdd(
                     __ BitcastHeapObjectToWordPtr(alloc), node->offset())));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::InlinedAllocation::allocation_block(), v8::internal::DCHECK(), v8::internal::maglev::InlinedAllocation::HasBeenAnalysed(), v8::internal::maglev::InlinedAllocation::HasEscaped(), v8::internal::maglev::kContinue, Map(), v8::internal::maglev::InlinedAllocation::offset(), and SetMap().
Process() [148/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::Int32AbsWithOverflow * node, const maglev::ProcessingState & state) [inline]
Definition at line 4060 of file turbolev-graph-builder.cc.
                                                                    {
    V<Word32> input = Map(node->input());
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    ScopedVar<Word32, AssemblerT> result(this, input);
    IF (__ Int32LessThan(input, 0)) {
      V<Tuple<Word32, Word32>> result_with_ovf =
          __ Int32MulCheckOverflow(input, -1);
      __ DeoptimizeIf(__ Projection<1>(result_with_ovf), frame_state,
                      DeoptimizeReason::kOverflow,
                      node->eager_deopt_info()->feedback_to_update());
      result = __ Projection<0>(result_with_ovf);
    }
Process() [149/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::Int32BitwiseNot * node, const maglev::ProcessingState & state) [inline]
Definition at line 4053 of file turbolev-graph-builder.cc.
                                                                    {
    // Turboshaft doesn't have a bitwise Not operator; we instead use "^ -1".
    SetMap(node, __ Word32BitwiseXor(Map(node->value_input()),
Process() [150/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::Int32Compare * node, const maglev::ProcessingState & state) [inline]
Definition at line 3473 of file turbolev-graph-builder.cc.
                                                                    {
    V<Word32> bool_res =
        ConvertCompare<Word32>(node->left_input(), node->right_input(),
                               node->operation(), Sign::kSigned);
    SetMap(node, ConvertWord32ToJSBool(bool_res));
    return maglev::ProcessResult::kContinue;
  }
References ConvertWord32ToJSBool(), v8::internal::maglev::kContinue, kSigned, v8::internal::maglev::Int32Compare::left_input(), v8::internal::maglev::Int32Compare::operation(), v8::internal::maglev::Int32Compare::right_input(), and SetMap().
Process() [151/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::Int32Constant * node, const maglev::ProcessingState & state) [inline]
Definition at line 1066 of file turbolev-graph-builder.cc.
                                                                    {
    SetMap(node, __ Word32Constant(node->value()));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::kContinue, SetMap(), and v8::internal::maglev::Int32Constant::value().
Process() [152/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::Int32CountLeadingZeros * node, const maglev::ProcessingState & state) [inline]
Definition at line 3979 of file turbolev-graph-builder.cc.
                                                                    {
    SetMap(node, __ Word32CountLeadingZeros(Map(node->input())));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::Int32CountLeadingZeros::input(), v8::internal::maglev::kContinue, Map(), and SetMap().
Process() [153/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::Int32DecrementWithOverflow * node, const maglev::ProcessingState & state) [inline]
Definition at line 3956 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    // Turboshaft doesn't have a dedicated Decrement operation; we use a regular
    // addition instead.
    SetMap(node, __ Word32SignedSubDeoptOnOverflow(
                     Map(node->value_input()), 1, frame_state,
                     node->eager_deopt_info()->feedback_to_update()));
    return maglev::ProcessResult::kContinue;
  }
References __, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::kContinue, Map(), and SetMap().
Process() [154/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::Int32IncrementWithOverflow * node, const maglev::ProcessingState & state) [inline]
Definition at line 3946 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    // Turboshaft doesn't have a dedicated Increment operation; we use a regular
    // addition instead.
    SetMap(node, __ Word32SignedAddDeoptOnOverflow(
                     Map(node->value_input()), 1, frame_state,
                     node->eager_deopt_info()->feedback_to_update()));
    return maglev::ProcessResult::kContinue;
  }
References __, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::kContinue, Map(), and SetMap().
Process() [155/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::Int32NegateWithOverflow * node, const maglev::ProcessingState & state) [inline]
Definition at line 3966 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    // Turboshaft doesn't have an Int32NegateWithOverflow operation, but
    // Turbofan emits multiplications by -1 for this, so using this as well
    // here.
    SetMap(node, __ Word32SignedMulDeoptOnOverflow(
                     Map(node->value_input()), -1, frame_state,
                     node->eager_deopt_info()->feedback_to_update(),
                     CheckForMinusZeroMode::kCheckForMinusZero));
    return maglev::ProcessResult::kContinue;
  }
References __, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::compiler::kCheckForMinusZero, v8::internal::maglev::kContinue, Map(), and SetMap().
Process() [156/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::Int32ShiftRightLogical * node, const maglev::ProcessingState & state) [inline]
Definition at line 4038 of file turbolev-graph-builder.cc.
                                                                    {
    V<Word32> right = Map(node->right_input());
    if (!SupportedOperations::word32_shift_is_safe()) {
      // JavaScript spec says that the right-hand side of a shift should be
      // taken modulo 32. Some architectures do this automatically, some
      // don't. For those that don't, which do this modulo 32 with a `& 0x1f`.
      right = __ Word32BitwiseAnd(right, 0x1f);
    }
    V<Word32> ts_op =
        __ Word32ShiftRightLogical(Map(node->left_input()), right);
References __, v8::internal::maglev::Int32ShiftRightLogical::left_input(), Map(), v8::internal::maglev::Int32ShiftRightLogical::right_input(), and SetMap().
Process() [157/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::Int32ToBoolean * node, const maglev::ProcessingState & state) [inline]
Definition at line 4244 of file turbolev-graph-builder.cc.
                                                                    {
Process() [158/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::Int32ToNumber * node, const maglev::ProcessingState & state) [inline]
Definition at line 4262 of file turbolev-graph-builder.cc.
                                                                    {
Process() [159/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::Int32ToUint8Clamped * node, const maglev::ProcessingState & state) [inline]
Definition at line 4641 of file turbolev-graph-builder.cc.
                                                                    {
Process() [160/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::IntPtrConstant * node, const maglev::ProcessingState & state) [inline]
Definition at line 1077 of file turbolev-graph-builder.cc.
                                                                    {
    SetMap(node, __ WordPtrConstant(node->value()));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::kContinue, SetMap(), and v8::internal::maglev::IntPtrConstant::value().
Process() [161/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::IntPtrToBoolean * node, const maglev::ProcessingState & state) [inline]
Definition at line 4250 of file turbolev-graph-builder.cc.
                                                                    {
Process() [162/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::IntPtrToNumber * node, const maglev::ProcessingState & state) [inline]
Definition at line 4273 of file turbolev-graph-builder.cc.
                                                                    {
Process() [163/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::Jump * node, const maglev::ProcessingState & state) [inline]
Definition at line 3452 of file turbolev-graph-builder.cc.
                                                                    {
    BuildJump(node->target());
    return maglev::ProcessResult::kContinue;
  }
References BuildJump(), and v8::internal::maglev::kContinue.
Process() [164/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::JumpLoop * node, const maglev::ProcessingState & state) [inline]
Definition at line 3463 of file turbolev-graph-builder.cc.
                                                                    {
    if (header_switch_input_.valid()) {
      __ SetVariable(header_switch_input_, loop_default_generator_value_);
    }
    __ Goto(Map(node->target()));
    FixLoopPhis(node->target());
    return maglev::ProcessResult::kContinue;
  }
References __, FixLoopPhis(), header_switch_input_, v8::internal::maglev::kContinue, loop_default_generator_value_, and Map().
Process() [165/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::LoadDoubleConstantTypedArrayElement * node, const maglev::ProcessingState & state) [inline]
Definition at line 3273 of file turbolev-graph-builder.cc.
                                          {
    DCHECK_EQ(node->elements_kind(),
              any_of(FLOAT32_ELEMENTS, FLOAT64_ELEMENTS));
    V<Float> value = V<Float>::Cast(BuildConstantTypedArrayLoad(
        node->typed_array(), Map<Word32>(node->index_input()),
        node->elements_kind()));
    if (node->elements_kind() == FLOAT32_ELEMENTS) {
      value = __ ChangeFloat32ToFloat64(V<Float32>::Cast(value));
    }
    SetMap(node, value);
    return maglev::ProcessResult::kContinue;
  }
References __, BuildConstantTypedArrayLoad(), v8::internal::compiler::turboshaft::V< T >::Cast(), DCHECK_EQ, v8::internal::maglev::FLOAT32_ELEMENTS, v8::internal::maglev::kContinue, SetMap(), and v8::internal::value.
Process() [166/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::LoadDoubleDataViewElement * node, const maglev::ProcessingState & state) [inline]
Definition at line 3377 of file turbolev-graph-builder.cc.
                                                                    {
    V<JSDataView> data_view = Map<JSDataView>(node->object_input());
    V<WordPtr> storage = __ LoadField<WordPtr>(
        data_view, AccessBuilder::ForJSDataViewDataPointer());
    V<Word32> is_little_endian =
        ToBit(node->is_little_endian_input(),
              TruncateJSPrimitiveToUntaggedOp::InputAssumptions::kObject);
    SetMap(node,
           __ LoadDataViewElement(
               data_view, storage,
               __ ChangeUint32ToUintPtr(Map<Word32>(node->index_input())),
               is_little_endian, ExternalArrayType::kExternalFloat64Array));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::compiler::AccessBuilder::ForJSDataViewDataPointer(), v8::internal::maglev::LoadDoubleDataViewElement::index_input(), v8::internal::maglev::LoadDoubleDataViewElement::is_little_endian_input(), v8::internal::maglev::kContinue, v8::internal::kExternalFloat64Array, v8::internal::compiler::turboshaft::TruncateJSPrimitiveToUntaggedOp::kObject, v8::internal::maglev::LoadDoubleDataViewElement::object_input(), SetMap(), and ToBit().
Process() [167/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::LoadDoubleField * node, const maglev::ProcessingState & state) [inline]
Definition at line 3007 of file turbolev-graph-builder.cc.
                                                                    {
    V<HeapNumber> field = __ LoadTaggedField<HeapNumber>(
        Map(node->object_input()), node->offset());
    SetMap(node, __ LoadHeapNumberValue(field));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::kContinue, Map(), v8::internal::maglev::LoadDoubleField::object_input(), v8::internal::maglev::LoadDoubleField::offset(), and SetMap().
Process() [168/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::LoadDoubleTypedArrayElement * node, const maglev::ProcessingState & state) [inline]
Definition at line 3244 of file turbolev-graph-builder.cc.
                                                                    {
    DCHECK_EQ(node->elements_kind(),
              any_of(FLOAT32_ELEMENTS, FLOAT64_ELEMENTS));
    V<Float> value = V<Float>::Cast(BuildTypedArrayLoad(
        Map<JSTypedArray>(node->object_input()),
        Map<Word32>(node->index_input()), node->elements_kind()));
    if (node->elements_kind() == FLOAT32_ELEMENTS) {
      value = __ ChangeFloat32ToFloat64(V<Float32>::Cast(value));
    }
    SetMap(node, value);
    return maglev::ProcessResult::kContinue;
  }
References __, BuildTypedArrayLoad(), v8::internal::compiler::turboshaft::V< T >::Cast(), DCHECK_EQ, v8::internal::maglev::FLOAT32_ELEMENTS, v8::internal::maglev::kContinue, SetMap(), and v8::internal::value.
Process() [169/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::LoadEnumCacheLength * node, const maglev::ProcessingState & state) [inline]
Definition at line 3171 of file turbolev-graph-builder.cc.
                                                                    {
    V<Word32> bitfield3 =
        __ LoadField<Word32>(V<i::Map>::Cast(Map(node->map_input())),
                             AccessBuilder::ForMapBitField3());
    V<Word32> length = __ Word32ShiftRightLogical(
        __ Word32BitwiseAnd(bitfield3, Map::Bits3::EnumLengthBits::kMask),
        Map::Bits3::EnumLengthBits::kShift);
    SetMap(node, length);
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::compiler::AccessBuilder::ForMapBitField3(), v8::internal::maglev::kContinue, v8::internal::length, Map(), v8::internal::maglev::LoadEnumCacheLength::map_input(), and SetMap().
Process() [170/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::LoadFixedArrayElement * node, const maglev::ProcessingState & state) [inline]
Definition at line 3026 of file turbolev-graph-builder.cc.
                                                                    {
    SetMap(node, __ LoadFixedArrayElement(
                     Map(node->elements_input()),
                     __ ChangeInt32ToIntPtr(Map(node->index_input()))));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::ChangeInt32ToIntPtr(), v8::internal::maglev::LoadFixedArrayElement::elements_input(), v8::internal::maglev::LoadFixedArrayElement::index_input(), v8::internal::maglev::kContinue, Map(), and SetMap().
Process() [171/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::LoadFixedDoubleArrayElement * node, const maglev::ProcessingState & state) [inline]
Definition at line 3033 of file turbolev-graph-builder.cc.
                                                                    {
    SetMap(node, __ LoadFixedDoubleArrayElement(
                     Map(node->elements_input()),
                     __ ChangeInt32ToIntPtr(Map(node->index_input()))));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::ChangeInt32ToIntPtr(), v8::internal::maglev::LoadFixedDoubleArrayElement::elements_input(), v8::internal::maglev::LoadFixedDoubleArrayElement::index_input(), v8::internal::maglev::kContinue, Map(), and SetMap().
Process() [172/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::LoadFloat64 * node, const maglev::ProcessingState & state) [inline]
Definition at line 3014 of file turbolev-graph-builder.cc.
                                                                    {
    SetMap(node, __ Load(Map(node->object_input()), LoadOp::Kind::TaggedBase(),
                         MemoryRepresentation::Float64(), node->offset()));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::compiler::turboshaft::MemoryRepresentation::Float64(), v8::internal::maglev::kContinue, v8::Load(), Map(), v8::internal::maglev::LoadFloat64::object_input(), v8::internal::maglev::LoadFloat64::offset(), SetMap(), and v8::internal::compiler::turboshaft::LoadOp::Kind::TaggedBase().
Process() [173/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::LoadGlobal * node, const maglev::ProcessingState & state) [inline]
Definition at line 1946 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
    OpIndex arguments[] = {__ HeapConstant(node->name().object()),
                           __ TaggedIndexConstant(node->feedback().index()),
                           __ HeapConstant(node->feedback().vector),
                           Map(node->context())};
    Builtin builtin;
    switch (node->typeof_mode()) {
      case TypeofMode::kInside:
        builtin = Builtin::kLoadGlobalICInsideTypeof;
        break;
      case TypeofMode::kNotInside:
        builtin = Builtin::kLoadGlobalIC;
        break;
    }
    GENERATE_AND_MAP_BUILTIN_CALL(node, builtin, frame_state,
                                  base::VectorOf(arguments));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::LoadGlobal::context(), v8::internal::maglev::LoadGlobal::feedback(), GENERATE_AND_MAP_BUILTIN_CALL, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::compiler::FeedbackSource::index(), v8::internal::maglev::kContinue, v8::internal::kInside, v8::internal::kNotInside, Map(), v8::internal::maglev::LoadGlobal::name(), v8::internal::compiler::NameRef::object(), v8::internal::maglev::LoadGlobal::typeof_mode(), v8::internal::compiler::FeedbackSource::vector, and v8::base::VectorOf().
Process() [174/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::LoadHoleyFixedDoubleArrayElement * node, const maglev::ProcessingState & state) [inline]
Definition at line 3040 of file turbolev-graph-builder.cc.
                                                                    {
    SetMap(node, __ LoadFixedDoubleArrayElement(
                     Map(node->elements_input()),
                     __ ChangeInt32ToIntPtr(Map(node->index_input()))));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::ChangeInt32ToIntPtr(), v8::internal::maglev::LoadHoleyFixedDoubleArrayElement::elements_input(), v8::internal::maglev::LoadHoleyFixedDoubleArrayElement::index_input(), v8::internal::maglev::kContinue, Map(), and SetMap().
Process() [175/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::LoadHoleyFixedDoubleArrayElementCheckedNotHole * node, const maglev::ProcessingState & state) [inline]
Definition at line 3047 of file turbolev-graph-builder.cc.
                                          {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    V<Float64> result = __ LoadFixedDoubleArrayElement(
        Map(node->elements_input()),
        __ ChangeInt32ToIntPtr(Map(node->index_input())));
    __ DeoptimizeIf(__ Float64IsHole(result), frame_state,
                    DeoptimizeReason::kHole,
                    node->eager_deopt_info()->feedback_to_update());
    SetMap(node, result);
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::ChangeInt32ToIntPtr(), v8::internal::maglev::LoadHoleyFixedDoubleArrayElementCheckedNotHole::elements_input(), GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::LoadHoleyFixedDoubleArrayElementCheckedNotHole::index_input(), v8::internal::maglev::kContinue, Map(), v8::base::internal::result, and SetMap().
Process() [176/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::LoadInt32 * node, const maglev::ProcessingState & state) [inline]
Definition at line 3020 of file turbolev-graph-builder.cc.
                                                                    {
    SetMap(node, __ Load(Map(node->object_input()), LoadOp::Kind::TaggedBase(),
                         MemoryRepresentation::Int32(), node->offset()));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::compiler::turboshaft::MemoryRepresentation::Int32(), v8::internal::maglev::kContinue, v8::Load(), Map(), v8::internal::maglev::LoadInt32::object_input(), v8::internal::maglev::LoadInt32::offset(), SetMap(), and v8::internal::compiler::turboshaft::LoadOp::Kind::TaggedBase().
Process() [177/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::LoadNamedFromSuperGeneric * node, const maglev::ProcessingState & state) [inline]
Definition at line 1930 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
    OpIndex arguments[] = {Map(node->receiver()),
                           Map(node->lookup_start_object()),
                           __ HeapConstant(node->name().object()),
                           __ TaggedIndexConstant(node->feedback().index()),
                           __ HeapConstant(node->feedback().vector),
                           Map(node->context())};
    GENERATE_AND_MAP_BUILTIN_CALL(node, Builtin::kLoadSuperIC, frame_state,
                                  base::VectorOf(arguments));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::LoadNamedFromSuperGeneric::context(), v8::internal::maglev::LoadNamedFromSuperGeneric::feedback(), GENERATE_AND_MAP_BUILTIN_CALL, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::compiler::FeedbackSource::index(), v8::internal::maglev::kContinue, v8::internal::maglev::LoadNamedFromSuperGeneric::lookup_start_object(), Map(), v8::internal::maglev::LoadNamedFromSuperGeneric::name(), v8::internal::compiler::NameRef::object(), v8::internal::maglev::LoadNamedFromSuperGeneric::receiver(), v8::internal::compiler::FeedbackSource::vector, and v8::base::VectorOf().
Process() [178/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::LoadNamedGeneric * node, const maglev::ProcessingState & state) [inline]
Definition at line 1916 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
    OpIndex arguments[] = {
        Map(node->object_input()), __ HeapConstant(node->name().object()),
        __ TaggedIndexConstant(node->feedback().index()),
        __ HeapConstant(node->feedback().vector), Map(node->context())};
    GENERATE_AND_MAP_BUILTIN_CALL(node, Builtin::kLoadIC, frame_state,
                                  base::VectorOf(arguments));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::LoadNamedGeneric::context(), v8::internal::maglev::LoadNamedGeneric::feedback(), GENERATE_AND_MAP_BUILTIN_CALL, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::compiler::FeedbackSource::index(), v8::internal::maglev::kContinue, Map(), v8::internal::maglev::LoadNamedGeneric::name(), v8::internal::compiler::NameRef::object(), v8::internal::maglev::LoadNamedGeneric::object_input(), v8::internal::compiler::FeedbackSource::vector, and v8::base::VectorOf().
Process() [179/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::LoadSignedIntConstantTypedArrayElement * node, const maglev::ProcessingState & state) [inline]
Definition at line 3265 of file turbolev-graph-builder.cc.
                                          {
    SetMap(node, BuildConstantTypedArrayLoad(node->typed_array(),
                                             Map<Word32>(node->index_input()),
                                             node->elements_kind()));
    return maglev::ProcessResult::kContinue;
  }
References BuildConstantTypedArrayLoad(), v8::internal::maglev::kContinue, and SetMap().
Process() [180/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::LoadSignedIntDataViewElement * node, const maglev::ProcessingState & state) [inline]
Definition at line 3363 of file turbolev-graph-builder.cc.
                                                                    {
    V<JSDataView> data_view = Map<JSDataView>(node->object_input());
    V<WordPtr> storage = __ LoadField<WordPtr>(
        data_view, AccessBuilder::ForJSDataViewDataPointer());
    V<Word32> is_little_endian =
        ToBit(node->is_little_endian_input(),
              TruncateJSPrimitiveToUntaggedOp::InputAssumptions::kObject);
    SetMap(node, __ LoadDataViewElement(
                     data_view, storage,
                     __ ChangeUint32ToUintPtr(Map<Word32>(node->index_input())),
                     is_little_endian, node->type()));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::compiler::AccessBuilder::ForJSDataViewDataPointer(), v8::internal::maglev::LoadSignedIntDataViewElement::index_input(), v8::internal::maglev::LoadSignedIntDataViewElement::is_little_endian_input(), v8::internal::maglev::kContinue, v8::internal::compiler::turboshaft::TruncateJSPrimitiveToUntaggedOp::kObject, v8::internal::maglev::LoadSignedIntDataViewElement::object_input(), SetMap(), ToBit(), and v8::internal::maglev::LoadSignedIntDataViewElement::type().
Process() [181/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::LoadSignedIntTypedArrayElement * node, const maglev::ProcessingState & state) [inline]
Definition at line 3237 of file turbolev-graph-builder.cc.
                                                                    {
    SetMap(node, BuildTypedArrayLoad(Map<JSTypedArray>(node->object_input()),
                                     Map<Word32>(node->index_input()),
                                     node->elements_kind()));
    return maglev::ProcessResult::kContinue;
  }
References BuildTypedArrayLoad(), v8::internal::maglev::kContinue, and SetMap().
Process() [182/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::LoadTaggedFieldByFieldIndex * node, const maglev::ProcessingState & state) [inline]
Definition at line 3197 of file turbolev-graph-builder.cc.
                                                                    {
    SetMap(node,
           __ LoadFieldByIndex(Map(node->object_input()),
                               __ UntagSmi(Map<Smi>(node->index_input()))));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::LoadTaggedFieldByFieldIndex::index_input(), v8::internal::maglev::kContinue, Map(), v8::internal::maglev::LoadTaggedFieldByFieldIndex::object_input(), and SetMap().
Process() [183/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::LoadTaggedFieldForContextSlot * node, const maglev::ProcessingState & state) [inline]
Definition at line 2966 of file turbolev-graph-builder.cc.
                                                                    {
    V<Context> script_context = V<Context>::Cast(Map(node->context()));
    V<Object> value = __ LoadTaggedField(script_context, node->offset());
    ScopedVar<Object, AssemblerT> result(this, value);
    IF_NOT (__ IsSmi(value)) {
      V<i::Map> value_map = __ LoadMapField(value);
      IF (UNLIKELY(__ TaggedEqual(
              value_map,
              __ HeapConstant(local_factory_->context_cell_map())))) {
        V<ContextCell> slot = V<ContextCell>::Cast(value);
        V<Word32> slot_state =
            __ LoadField<Word32>(slot, AccessBuilder::ForContextCellState());
        static_assert(ContextCell::State::kConst == 0);
        static_assert(ContextCell::State::kSmi == 1);
        IF (__ Int32LessThanOrEqual(slot_state,
                                    __ Word32Constant(ContextCell::kSmi))) {
          result = __ LoadField<Object>(
              slot, AccessBuilder::ForContextCellTaggedValue());
        } ELSE {
          IF (__ Word32Equal(slot_state,
                             __ Word32Constant(ContextCell::kInt32))) {
            result = V<Number>::Cast(__ ConvertUntaggedToJSPrimitive(
                __ LoadField<Word32>(slot,
                                     AccessBuilder::ForContextCellInt32Value()),
                ConvertUntaggedToJSPrimitiveOp::JSPrimitiveKind::kNumber,
                RegisterRepresentation::Word32(),
                ConvertUntaggedToJSPrimitiveOp::InputInterpretation::kSigned,
                CheckForMinusZeroMode::kDontCheckForMinusZero));
          } ELSE {
            result = __ AllocateHeapNumberWithValue(
                __ LoadField<Float64>(
                    slot, AccessBuilder::ForContextCellFloat64Value()),
                isolate_->factory());
          }
        }
      }
    }
    SetMap(node, result);
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::compiler::turboshaft::V< T >::Cast(), v8::internal::maglev::LoadTaggedFieldForContextSlot::context(), v8::internal::Isolate::factory(), v8::internal::compiler::AccessBuilder::ForContextCellFloat64Value(), v8::internal::compiler::AccessBuilder::ForContextCellInt32Value(), v8::internal::compiler::AccessBuilder::ForContextCellState(), v8::internal::compiler::AccessBuilder::ForContextCellTaggedValue(), isolate_, v8::internal::IsSmi(), v8::internal::maglev::kContinue, v8::internal::compiler::kDontCheckForMinusZero, v8::internal::ContextCell::kInt32, v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOp::kNumber, v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOp::kSigned, v8::internal::compiler::kSmi, v8::internal::ContextCell::kSmi, local_factory_, Map(), v8::internal::maglev::LoadTaggedFieldForContextSlot::offset(), v8::base::internal::result, SetMap(), v8::internal::value, v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), and v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal().
Process() [184/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::LoadTypedArrayLength * node, const maglev::ProcessingState & state) [inline]
Definition at line 3205 of file turbolev-graph-builder.cc.
                                                                    {
    V<WordPtr> length =
        __ LoadField<WordPtr>(Map<JSTypedArray>(node->receiver_input()),
                              AccessBuilder::ForJSTypedArrayByteLength());
    int shift_size = ElementsKindToShiftSize(node->elements_kind());
    if (shift_size > 0) {
      DCHECK(shift_size == 1 || shift_size == 2 || shift_size == 3);
      length = __ WordPtrShiftRightLogical(length, shift_size);
    }
    SetMap(node, length);
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::DCHECK(), v8::internal::maglev::LoadTypedArrayLength::elements_kind(), v8::internal::ElementsKindToShiftSize(), v8::internal::compiler::AccessBuilder::ForJSTypedArrayByteLength(), v8::internal::maglev::kContinue, v8::internal::length, v8::internal::maglev::LoadTypedArrayLength::receiver_input(), and SetMap().
Process() [185/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::LoadUnsignedIntConstantTypedArrayElement * node, const maglev::ProcessingState & state) [inline]
Definition at line 3257 of file turbolev-graph-builder.cc.
                                          {
    SetMap(node, BuildConstantTypedArrayLoad(node->typed_array(),
                                             Map<Word32>(node->index_input()),
                                             node->elements_kind()));
    return maglev::ProcessResult::kContinue;
  }
References BuildConstantTypedArrayLoad(), v8::internal::maglev::kContinue, and SetMap().
Process() [186/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::LoadUnsignedIntTypedArrayElement * node, const maglev::ProcessingState & state) [inline]
Definition at line 3230 of file turbolev-graph-builder.cc.
                                                                    {
    SetMap(node, BuildTypedArrayLoad(Map<JSTypedArray>(node->object_input()),
                                     Map<Word32>(node->index_input()),
                                     node->elements_kind()));
    return maglev::ProcessResult::kContinue;
  }
References BuildTypedArrayLoad(), v8::internal::maglev::kContinue, and SetMap().
Process() [187/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::LogicalNot * node, const maglev::ProcessingState & state) [inline]
Definition at line 4208 of file turbolev-graph-builder.cc.
                                                                    {
    V<Word32> condition = __ TaggedEqual(
        Map(node->value()), __ HeapConstant(local_factory_->true_value()));
Process() [188/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::MapPrototypeGet * node, const maglev::ProcessingState & state) [inline]
Definition at line 2077 of file turbolev-graph-builder.cc.
                                                                    {
    V<Object> table = Map(node->table_input());
    V<Smi> key = Map(node->key_input());
    V<Smi> entry = __ FindOrderedHashMapEntry(table, key);
    ScopedVar<Object, AssemblerT> result(this, undefined_value_);
    IF_NOT (__ TaggedEqual(entry, __ SmiConstant(Smi::FromInt(-1)))) {
      result =
          __ LoadElement(table, AccessBuilderTS::ForOrderedHashMapEntryValue(),
                         __ ChangeInt32ToIntPtr(__ UntagSmi(entry)));
    }
    SetMap(node, result);
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::ChangeInt32ToIntPtr(), v8::internal::Smi::FromInt(), v8::internal::maglev::kContinue, v8::internal::key, v8::internal::maglev::MapPrototypeGet::key_input(), Map(), v8::base::internal::result, SetMap(), v8::internal::maglev::MapPrototypeGet::table_input(), and undefined_value_.
Process() [189/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::MapPrototypeGetInt32Key * node, const maglev::ProcessingState & state) [inline]
Definition at line 2096 of file turbolev-graph-builder.cc.
                                                                    {
    V<Object> table = Map(node->table_input());
    V<Word32> key = Map(node->key_input());
    V<WordPtr> entry = __ FindOrderedHashMapEntryForInt32Key(table, key);
    ScopedVar<Object, AssemblerT> result(this, undefined_value_);
    IF_NOT (__ Word32Equal(__ TruncateWordPtrToWord32(entry), -1)) {
      result = __ LoadElement(
          table, AccessBuilderTS::ForOrderedHashMapEntryValue(), entry);
    }
    SetMap(node, result);
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::kContinue, v8::internal::key, v8::internal::maglev::MapPrototypeGetInt32Key::key_input(), Map(), v8::base::internal::result, SetMap(), v8::internal::maglev::MapPrototypeGetInt32Key::table_input(), undefined_value_, and v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal().
Process() [190/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::MaybeGrowFastElements * node, const maglev::ProcessingState & state) [inline]
Definition at line 2635 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    GrowFastElementsMode mode =
        IsDoubleElementsKind(node->elements_kind())
            ? GrowFastElementsMode::kDoubleElements
            : GrowFastElementsMode::kSmiOrObjectElements;
    SetMap(node, __ MaybeGrowFastElements(
                     Map(node->object_input()), Map(node->elements_input()),
                     Map(node->index_input()),
                     Map(node->elements_length_input()), frame_state, mode,
                     node->eager_deopt_info()->feedback_to_update()));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::MaybeGrowFastElements::elements_input(), v8::internal::maglev::MaybeGrowFastElements::elements_kind(), v8::internal::maglev::MaybeGrowFastElements::elements_length_input(), GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::MaybeGrowFastElements::index_input(), v8::internal::IsDoubleElementsKind(), v8::internal::maglev::kContinue, v8::internal::compiler::kDoubleElements, v8::internal::compiler::kSmiOrObjectElements, Map(), mode(), v8::internal::maglev::MaybeGrowFastElements::object_input(), and SetMap().
Process() [191/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::MigrateMapIfNeeded * node, const maglev::ProcessingState & state) [inline]
Definition at line 2438 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    SetMap(node,
           __ MigrateMapIfNeeded(
               Map(node->object_input()), Map(node->map_input()), frame_state,
               node->eager_deopt_info()->feedback_to_update()));
    return maglev::ProcessResult::kContinue;
  }
References __, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::kContinue, Map(), v8::internal::maglev::MigrateMapIfNeeded::map_input(), v8::internal::maglev::MigrateMapIfNeeded::object_input(), and SetMap().
Process() [192/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::NumberToString * node, const maglev::ProcessingState & state) [inline]
Definition at line 2916 of file turbolev-graph-builder.cc.
                                                                    {
    NoThrowingScopeRequired no_throws(node);
    SetMap(node,
           __ CallBuiltin_NumberToString(isolate_, Map(node->value_input())));
    return maglev::ProcessResult::kContinue;
  }
References __, isolate_, v8::internal::maglev::kContinue, Map(), SetMap(), and v8::internal::maglev::NumberToString::value_input().
Process() [193/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::Phi * node, const maglev::ProcessingState & state) [inline]
Definition at line 1178 of file turbolev-graph-builder.cc.
                                                                    {
    int input_count = node->input_count();
    RegisterRepresentation rep =
        RegisterRepresentationFor(node->value_representation());
    if (node->is_exception_phi()) {
      if (node->owner() == interpreter::Register::virtual_accumulator()) {
        DCHECK(catch_block_begin_.valid());
        SetMap(node, catch_block_begin_);
      } else {
        Variable var = regs_to_vars_[node->owner().index()];
        SetMap(node, __ GetVariable(var));
        // {var} won't be used anymore once we've created the mapping from
        // {node} to its value. We thus reset it, in order to avoid Phis being
        // created for {var} at later merge points.
        __ SetVariable(var, V<Object>::Invalid());
      }
      return maglev::ProcessResult::kContinue;
    }
    if (__ current_block()->IsLoop()) {
      DCHECK(state.block()->is_loop());
      OpIndex first_phi_input;
      if (state.block()->predecessor_count() > 2 ||
          generator_analyzer_.HeaderIsBypassed(state.block())) {
        // This loop has multiple forward edges in Maglev, so we should have
        // created an intermediate block in Turboshaft, which will be the only
        // predecessor of the Turboshaft loop, and from which we'll find the
        // first input for this loop phi.
        DCHECK_EQ(loop_phis_first_input_.size(),
                  static_cast<size_t>(state.block()->phis()->LengthForTest()));
        DCHECK_GE(loop_phis_first_input_index_, 0);
        DCHECK_LT(loop_phis_first_input_index_, loop_phis_first_input_.size());
        DCHECK(loop_single_edge_predecessors_.contains(state.block()));
        DCHECK_EQ(loop_single_edge_predecessors_[state.block()],
                  __ current_block()->LastPredecessor());
        first_phi_input = loop_phis_first_input_[loop_phis_first_input_index_];
        loop_phis_first_input_index_++;
      } else {
        DCHECK_EQ(input_count, 2);
        DCHECK_EQ(state.block()->predecessor_count(), 2);
        DCHECK(loop_phis_first_input_.empty());
        first_phi_input = Map(node->input(0));
      }
      SetMap(node, __ PendingLoopPhi(first_phi_input, rep));
    } else {
      SetMap(node, MakePhiMaybePermuteInputs(node, input_count));
    }
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::ProcessingState::block(), catch_block_begin_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, DCHECK_LT, generator_analyzer_, v8::internal::compiler::turboshaft::GeneratorAnalyzer::HeaderIsBypassed(), v8::internal::interpreter::Register::index(), v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::maglev::Phi::is_exception_phi(), v8::internal::maglev::BasicBlock::is_loop(), v8::internal::maglev::kContinue, v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::LengthForTest(), loop_phis_first_input_, loop_phis_first_input_index_, loop_single_edge_predecessors_, MakePhiMaybePermuteInputs(), Map(), v8::internal::maglev::Phi::owner(), v8::internal::maglev::BasicBlock::phis(), v8::internal::maglev::BasicBlock::predecessor_count(), RegisterRepresentationFor(), regs_to_vars_, SetMap(), and v8::internal::interpreter::Register::virtual_accumulator().
Process() [194/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::ReduceInterruptBudgetForLoop * node, const maglev::ProcessingState &) [inline]
Definition at line 4816 of file turbolev-graph-builder.cc.
                                                              {
    // ReduceInterruptBudgetForLoop nodes are not emitted by Maglev when it is
Process() [195/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::ReduceInterruptBudgetForReturn * , const maglev::ProcessingState &) [inline]
Definition at line 4811 of file turbolev-graph-builder.cc.
                                                              {
Process() [196/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::RegisterInput * node, const maglev::ProcessingState & state) [inline]
Definition at line 1160 of file turbolev-graph-builder.cc.
                                                                    {
    DCHECK(maglev_compilation_unit_->bytecode()
               .incoming_new_target_or_generator_register()
               .is_valid());
    DCHECK_EQ(node->input(), kJavaScriptCallNewTargetRegister);
    DCHECK(new_target_param_.valid());
    SetMap(node, new_target_param_);
    return maglev::ProcessResult::kContinue;
  }
References v8::internal::maglev::MaglevCompilationUnit::bytecode(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::BytecodeArrayRef::incoming_new_target_or_generator_register(), v8::internal::maglev::RegisterInput::input(), v8::internal::interpreter::Register::is_valid(), v8::internal::maglev::kContinue, v8::internal::kJavaScriptCallNewTargetRegister, maglev_compilation_unit_, new_target_param_, and SetMap().
Process() [197/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::RestLength * node, const maglev::ProcessingState & state) [inline]
Definition at line 2941 of file turbolev-graph-builder.cc.
                                                                    {
    SetMap(node, __ RestLength(node->formal_parameter_count()));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::RestLength::formal_parameter_count(), v8::internal::maglev::kContinue, and SetMap().
Process() [198/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::Return * node, const maglev::ProcessingState & state) [inline]
Definition at line 4696 of file turbolev-graph-builder.cc.
                                                                    {
Process() [199/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::RootConstant * node, const maglev::ProcessingState & state) [inline]
Definition at line 1059 of file turbolev-graph-builder.cc.
                                                                    {
    SetMap(node, __ HeapConstant(MakeRef(broker_, node->DoReify(local_isolate_))
                                     .AsHeapObject()
                                     .object()));
    return maglev::ProcessResult::kContinue;
  }
References __, broker_, v8::internal::maglev::RootConstant::DoReify(), v8::internal::maglev::kContinue, local_isolate_, v8::internal::compiler::MakeRef(), and SetMap().
Process() [200/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::SeqOneByteStringAt * node, const maglev::ProcessingState & state) [inline]
Definition at line 2826 of file turbolev-graph-builder.cc.
                                                                    {
    // TODO(leszeks): Change to seq-one-byte-specialized once
    // CheckSeqOneByteString checks for seq one-byte.
    V<Word32> char_code =
        __ StringCharCodeAt(Map(node->string_input()),
                            __ ChangeUint32ToUintPtr(Map(node->index_input())));
    SetMap(node, __ ConvertCharCodeToString(char_code));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::SeqOneByteStringAt::index_input(), v8::internal::maglev::kContinue, Map(), SetMap(), and v8::internal::maglev::SeqOneByteStringAt::string_input().
Process() [201/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::SetKeyedGeneric * node, const maglev::ProcessingState & state) [inline]
Definition at line 1872 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
    OpIndex arguments[] = {Map(node->object_input()),
                           Map(node->key_input()),
                           Map(node->value_input()),
                           __ TaggedIndexConstant(node->feedback().index()),
                           __ HeapConstant(node->feedback().vector),
                           Map(node->context())};
    GENERATE_AND_MAP_BUILTIN_CALL(node, Builtin::kKeyedStoreIC, frame_state,
                                  base::VectorOf(arguments));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::SetKeyedGeneric::context(), v8::internal::maglev::SetKeyedGeneric::feedback(), GENERATE_AND_MAP_BUILTIN_CALL, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::compiler::FeedbackSource::index(), v8::internal::maglev::kContinue, v8::internal::maglev::SetKeyedGeneric::key_input(), Map(), v8::internal::maglev::SetKeyedGeneric::object_input(), v8::internal::maglev::SetKeyedGeneric::value_input(), v8::internal::compiler::FeedbackSource::vector, and v8::base::VectorOf().
Process() [202/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::SetNamedGeneric * node, const maglev::ProcessingState & state) [inline]
Definition at line 1901 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
    OpIndex arguments[] = {Map(node->object_input()),
                           __ HeapConstant(node->name().object()),
                           Map(node->value_input()),
                           __ TaggedIndexConstant(node->feedback().index()),
                           __ HeapConstant(node->feedback().vector),
                           Map(node->context())};
    GENERATE_AND_MAP_BUILTIN_CALL(node, Builtin::kStoreIC, frame_state,
                                  base::VectorOf(arguments));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::SetNamedGeneric::context(), v8::internal::maglev::SetNamedGeneric::feedback(), GENERATE_AND_MAP_BUILTIN_CALL, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::compiler::FeedbackSource::index(), v8::internal::maglev::kContinue, Map(), v8::internal::maglev::SetNamedGeneric::name(), v8::internal::compiler::NameRef::object(), v8::internal::maglev::SetNamedGeneric::object_input(), v8::internal::maglev::SetNamedGeneric::value_input(), v8::internal::compiler::FeedbackSource::vector, and v8::base::VectorOf().
Process() [203/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::SetPendingMessage * node, const maglev::ProcessingState & state) [inline]
Definition at line 4710 of file turbolev-graph-builder.cc.
                                                                    {
    V<WordPtr> message_address = __ ExternalConstant(
        ExternalReference::address_of_pending_message(isolate_));
    V<Object> old_message = __ LoadMessage(message_address);
    __ StoreMessage(message_address, Map(node->value()));
Process() [204/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::SetPrototypeHas * node, const maglev::ProcessingState & state) [inline]
Definition at line 2114 of file turbolev-graph-builder.cc.
                                                                    {
    V<Object> table = Map(node->table_input());
    V<Smi> key = Map(node->key_input());
    V<Smi> entry = __ FindOrderedHashSetEntry(table, key);
    ScopedVar<Object, AssemblerT> result(
        this, __ HeapConstant(local_factory_->true_value()));
    IF (__ TaggedEqual(entry, __ SmiConstant(Smi::FromInt(-1)))) {
      result = __ HeapConstant(local_factory_->false_value());
    }
    SetMap(node, result);
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::Smi::FromInt(), v8::internal::maglev::kContinue, v8::internal::key, v8::internal::maglev::SetPrototypeHas::key_input(), local_factory_, Map(), v8::base::internal::result, SetMap(), and v8::internal::maglev::SetPrototypeHas::table_input().
Process() [205/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::SmiConstant * node, const maglev::ProcessingState & state) [inline]
Definition at line 1088 of file turbolev-graph-builder.cc.
                                                                    {
    SetMap(node, __ SmiConstant(node->value()));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::kContinue, SetMap(), and v8::internal::maglev::SmiConstant::value().
Process() [206/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::SmiCountLeadingZeros * node, const maglev::ProcessingState & state) [inline]
Definition at line 3984 of file turbolev-graph-builder.cc.
                                                                    {
    SetMap(node, __ Word32CountLeadingZeros(__ UntagSmi(Map(node->input()))));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::SmiCountLeadingZeros::input(), v8::internal::maglev::kContinue, Map(), and SetMap().
Process() [207/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::StoreContextSlotWithWriteBarrier * node, const maglev::ProcessingState & state) [inline]
Definition at line 3077 of file turbolev-graph-builder.cc.
                                                                    {
    V<Context> context = V<i::Context>::Cast(Map(node->context_input()));
    V<Object> new_value = Map(node->new_value_input());
    V<Object> old_value = __ LoadTaggedField(context, node->offset());
    IF (__ IsSmi(old_value)) {
      __ Store(context, new_value, StoreOp::Kind::TaggedBase(),
               MemoryRepresentation::AnyTagged(),
               WriteBarrierKind::kFullWriteBarrier, node->offset(), false);
    } ELSE {
      V<i::Map> value_map = __ LoadMapField(old_value);
      IF (UNLIKELY(__ TaggedEqual(
              value_map,
              __ HeapConstant(local_factory_->context_cell_map())))) {
        GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
        __ CallBuiltin_DetachContextCell(isolate_, frame_state, context,
                                         new_value,
                                         __ WordPtrConstant(node->index()));
      } ELSE {
        __ Store(context, new_value, StoreOp::Kind::TaggedBase(),
                 MemoryRepresentation::AnyTagged(),
                 WriteBarrierKind::kFullWriteBarrier, node->offset(), false);
      }
    }
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::compiler::turboshaft::MemoryRepresentation::AnyTagged(), v8::internal::compiler::turboshaft::V< T >::Cast(), v8::internal::maglev::StoreContextSlotWithWriteBarrier::context_input(), GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::StoreContextSlotWithWriteBarrier::index(), isolate_, v8::internal::IsSmi(), v8::internal::maglev::kContinue, v8::internal::compiler::kFullWriteBarrier, local_factory_, Map(), v8::internal::maglev::StoreContextSlotWithWriteBarrier::new_value_input(), v8::internal::maglev::StoreContextSlotWithWriteBarrier::offset(), v8::internal::wasm::liftoff::Store(), and v8::internal::compiler::turboshaft::LoadOp::Kind::TaggedBase().
Process() [208/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::StoreDoubleConstantTypedArrayElement * node, const maglev::ProcessingState & state) [inline]
Definition at line 3317 of file turbolev-graph-builder.cc.
                                          {
    DCHECK_EQ(node->elements_kind(),
              any_of(FLOAT32_ELEMENTS, FLOAT64_ELEMENTS));
    V<Float> value = Map<Float>(node->value_input());
    if (node->elements_kind() == FLOAT32_ELEMENTS) {
      value = __ TruncateFloat64ToFloat32(Map(node->value_input()));
    }
    BuildConstantTypedArrayStore(node->typed_array(),
                                 Map<Word32>(node->index_input()), value,
                                 node->elements_kind());
    return maglev::ProcessResult::kContinue;
  }
References __, BuildConstantTypedArrayStore(), DCHECK_EQ, v8::internal::maglev::FLOAT32_ELEMENTS, v8::internal::maglev::kContinue, Map(), and v8::internal::value.
Process() [209/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::StoreDoubleDataViewElement * node, const maglev::ProcessingState & state) [inline]
Definition at line 3407 of file turbolev-graph-builder.cc.
                                                                    {
    V<JSDataView> data_view = Map<JSDataView>(node->object_input());
    V<WordPtr> storage = __ LoadField<WordPtr>(
        data_view, AccessBuilder::ForJSDataViewDataPointer());
    V<Word32> is_little_endian =
        ToBit(node->is_little_endian_input(),
              TruncateJSPrimitiveToUntaggedOp::InputAssumptions::kObject);
    __ StoreDataViewElement(
        data_view, storage,
        __ ChangeUint32ToUintPtr(Map<Word32>(node->index_input())),
        Map<Float64>(node->value_input()), is_little_endian,
        ExternalArrayType::kExternalFloat64Array);
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::compiler::AccessBuilder::ForJSDataViewDataPointer(), v8::internal::maglev::StoreDoubleDataViewElement::index_input(), v8::internal::maglev::StoreDoubleDataViewElement::is_little_endian_input(), v8::internal::maglev::kContinue, v8::internal::kExternalFloat64Array, v8::internal::compiler::turboshaft::TruncateJSPrimitiveToUntaggedOp::kObject, v8::internal::maglev::StoreDoubleDataViewElement::object_input(), ToBit(), and v8::internal::maglev::StoreDoubleDataViewElement::value_input().
Process() [210/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::StoreDoubleField * node, const maglev::ProcessingState & state) [inline]
Definition at line 3103 of file turbolev-graph-builder.cc.
                                                                    {
    V<HeapNumber> field = __ LoadTaggedField<HeapNumber>(
        Map(node->object_input()), node->offset());
    __ StoreField(field, AccessBuilder::ForHeapNumberValue(),
                  Map(node->value_input()));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::compiler::AccessBuilder::ForHeapNumberValue(), v8::internal::maglev::kContinue, Map(), v8::internal::maglev::StoreDoubleField::object_input(), v8::internal::maglev::StoreDoubleField::offset(), and v8::internal::maglev::StoreDoubleField::value_input().
Process() [211/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::StoreDoubleTypedArrayElement * node, const maglev::ProcessingState & state) [inline]
Definition at line 3296 of file turbolev-graph-builder.cc.
                                                                    {
    DCHECK_EQ(node->elements_kind(),
              any_of(FLOAT32_ELEMENTS, FLOAT64_ELEMENTS));
    V<Float> value = Map<Float>(node->value_input());
    if (node->elements_kind() == FLOAT32_ELEMENTS) {
      value = __ TruncateFloat64ToFloat32(Map(node->value_input()));
    }
    BuildTypedArrayStore(Map<JSTypedArray>(node->object_input()),
                         Map<Word32>(node->index_input()), value,
                         node->elements_kind());
    return maglev::ProcessResult::kContinue;
  }
References __, BuildTypedArrayStore(), DCHECK_EQ, v8::internal::maglev::FLOAT32_ELEMENTS, v8::internal::maglev::kContinue, Map(), and v8::internal::value.
Process() [212/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::StoreFixedArrayElementNoWriteBarrier * node, const maglev::ProcessingState & state) [inline]
Definition at line 3121 of file turbolev-graph-builder.cc.
                                          {
    __ StoreFixedArrayElement(Map(node->elements_input()),
                              __ ChangeInt32ToIntPtr(Map(node->index_input())),
                              Map(node->value_input()),
                              WriteBarrierKind::kNoWriteBarrier);
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::ChangeInt32ToIntPtr(), v8::internal::maglev::StoreFixedArrayElementNoWriteBarrier::elements_input(), v8::internal::maglev::StoreFixedArrayElementNoWriteBarrier::index_input(), v8::internal::maglev::kContinue, v8::internal::compiler::kNoWriteBarrier, Map(), and v8::internal::maglev::StoreFixedArrayElementNoWriteBarrier::value_input().
Process() [213/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::StoreFixedArrayElementWithWriteBarrier * node, const maglev::ProcessingState & state) [inline]
Definition at line 3130 of file turbolev-graph-builder.cc.
                                          {
    __ StoreFixedArrayElement(Map(node->elements_input()),
                              __ ChangeInt32ToIntPtr(Map(node->index_input())),
                              Map(node->value_input()),
                              WriteBarrierKind::kFullWriteBarrier);
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::ChangeInt32ToIntPtr(), v8::internal::maglev::StoreFixedArrayElementWithWriteBarrier::elements_input(), v8::internal::maglev::StoreFixedArrayElementWithWriteBarrier::index_input(), v8::internal::maglev::kContinue, v8::internal::compiler::kFullWriteBarrier, Map(), and v8::internal::maglev::StoreFixedArrayElementWithWriteBarrier::value_input().
Process() [214/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::StoreFixedDoubleArrayElement * node, const maglev::ProcessingState & state) [inline]
Definition at line 3139 of file turbolev-graph-builder.cc.
                                                                    {
    __ StoreFixedDoubleArrayElement(
        Map(node->elements_input()),
        __ ChangeInt32ToIntPtr(Map(node->index_input())),
        Map(node->value_input()));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::ChangeInt32ToIntPtr(), v8::internal::maglev::StoreFixedDoubleArrayElement::elements_input(), v8::internal::maglev::StoreFixedDoubleArrayElement::index_input(), v8::internal::maglev::kContinue, Map(), and v8::internal::maglev::StoreFixedDoubleArrayElement::value_input().
Process() [215/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::StoreFloat64 * node, const maglev::ProcessingState & state) [inline]
Definition at line 3155 of file turbolev-graph-builder.cc.
                                                                    {
    __ Store(Map(node->object_input()), Map(node->value_input()),
             StoreOp::Kind::TaggedBase(), MemoryRepresentation::Float64(),
             WriteBarrierKind::kNoWriteBarrier, node->offset());
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::compiler::turboshaft::MemoryRepresentation::Float64(), v8::internal::maglev::kContinue, v8::internal::compiler::kNoWriteBarrier, Map(), v8::internal::maglev::StoreFloat64::object_input(), v8::internal::maglev::StoreFloat64::offset(), v8::internal::wasm::liftoff::Store(), v8::internal::compiler::turboshaft::LoadOp::Kind::TaggedBase(), and v8::internal::maglev::StoreFloat64::value_input().
Process() [216/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::StoreGlobal * node, const maglev::ProcessingState & state) [inline]
Definition at line 1970 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
    OpIndex arguments[] = {
        __ HeapConstant(node->name().object()), Map(node->value()),
        __ TaggedIndexConstant(node->feedback().index()),
        __ HeapConstant(node->feedback().vector), Map(node->context())};
    GENERATE_AND_MAP_BUILTIN_CALL(node, Builtin::kStoreGlobalIC, frame_state,
                                  base::VectorOf(arguments));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::StoreGlobal::context(), v8::internal::maglev::StoreGlobal::feedback(), GENERATE_AND_MAP_BUILTIN_CALL, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::compiler::FeedbackSource::index(), v8::internal::maglev::kContinue, Map(), v8::internal::maglev::StoreGlobal::name(), v8::internal::compiler::NameRef::object(), v8::internal::maglev::StoreGlobal::value(), v8::internal::compiler::FeedbackSource::vector, and v8::base::VectorOf().
Process() [217/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::StoreInArrayLiteralGeneric * node, const maglev::ProcessingState & state) [inline]
Definition at line 2061 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
    OpIndex arguments[] = {Map(node->object_input()),
                           Map(node->name_input()),
                           Map(node->value_input()),
                           __ TaggedIndexConstant(node->feedback().index()),
                           __ HeapConstant(node->feedback().vector),
                           native_context()};
    GENERATE_AND_MAP_BUILTIN_CALL(node, Builtin::kStoreInArrayLiteralIC,
                                  frame_state, base::VectorOf(arguments));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::StoreInArrayLiteralGeneric::feedback(), GENERATE_AND_MAP_BUILTIN_CALL, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::compiler::FeedbackSource::index(), v8::internal::maglev::kContinue, Map(), v8::internal::maglev::StoreInArrayLiteralGeneric::name_input(), native_context(), v8::internal::maglev::StoreInArrayLiteralGeneric::object_input(), v8::internal::maglev::StoreInArrayLiteralGeneric::value_input(), v8::internal::compiler::FeedbackSource::vector, and v8::base::VectorOf().
Process() [218/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::StoreInt32 * node, const maglev::ProcessingState & state) [inline]
Definition at line 3162 of file turbolev-graph-builder.cc.
                                                                    {
    __ Store(Map(node->object_input()), Map(node->value_input()),
             StoreOp::Kind::TaggedBase(), MemoryRepresentation::Int32(),
             WriteBarrierKind::kNoWriteBarrier, node->offset());
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::compiler::turboshaft::MemoryRepresentation::Int32(), v8::internal::maglev::kContinue, v8::internal::compiler::kNoWriteBarrier, Map(), v8::internal::maglev::StoreInt32::object_input(), v8::internal::maglev::StoreInt32::offset(), v8::internal::wasm::liftoff::Store(), v8::internal::compiler::turboshaft::LoadOp::Kind::TaggedBase(), and v8::internal::maglev::StoreInt32::value_input().
Process() [219/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::StoreIntConstantTypedArrayElement * node, const maglev::ProcessingState & state) [inline]
Definition at line 3310 of file turbolev-graph-builder.cc.
                                                                    {
    BuildConstantTypedArrayStore(
        node->typed_array(), Map<Word32>(node->index_input()),
        Map<Untagged>(node->value_input()), node->elements_kind());
    return maglev::ProcessResult::kContinue;
  }
References BuildConstantTypedArrayStore(), and v8::internal::maglev::kContinue.
Process() [220/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::StoreIntTypedArrayElement * node, const maglev::ProcessingState & state) [inline]
Definition at line 3288 of file turbolev-graph-builder.cc.
                                                                    {
    BuildTypedArrayStore(Map<JSTypedArray>(node->object_input()),
                         Map<Word32>(node->index_input()),
                         Map<Untagged>(node->value_input()),
                         node->elements_kind());
    return maglev::ProcessResult::kContinue;
  }
References BuildTypedArrayStore(), and v8::internal::maglev::kContinue.
Process() [221/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::StoreMap * node, const maglev::ProcessingState & state) [inline]
Definition at line 3147 of file turbolev-graph-builder.cc.
                                                                    {
    __ Store(Map(node->object_input()), __ HeapConstant(node->map().object()),
             StoreOp::Kind::TaggedBase(), MemoryRepresentation::TaggedPointer(),
             WriteBarrierKind::kMapWriteBarrier, HeapObject::kMapOffset,
             /*maybe_initializing_or_transitioning*/ true);
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::kContinue, v8::internal::HeapObject::kMapOffset, v8::internal::compiler::kMapWriteBarrier, v8::internal::maglev::StoreMap::map(), Map(), v8::internal::compiler::MapRef::object(), v8::internal::maglev::StoreMap::object_input(), v8::internal::wasm::liftoff::Store(), v8::internal::compiler::turboshaft::LoadOp::Kind::TaggedBase(), and v8::internal::compiler::turboshaft::MemoryRepresentation::TaggedPointer().
Process() [222/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::StoreSignedIntDataViewElement * node, const maglev::ProcessingState & state) [inline]
Definition at line 3393 of file turbolev-graph-builder.cc.
                                                                    {
    V<JSDataView> data_view = Map<JSDataView>(node->object_input());
    V<WordPtr> storage = __ LoadField<WordPtr>(
        data_view, AccessBuilder::ForJSDataViewDataPointer());
    V<Word32> is_little_endian =
        ToBit(node->is_little_endian_input(),
              TruncateJSPrimitiveToUntaggedOp::InputAssumptions::kObject);
    __ StoreDataViewElement(
        data_view, storage,
        __ ChangeUint32ToUintPtr(Map<Word32>(node->index_input())),
        Map<Word32>(node->value_input()), is_little_endian, node->type());
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::compiler::AccessBuilder::ForJSDataViewDataPointer(), v8::internal::maglev::StoreSignedIntDataViewElement::index_input(), v8::internal::maglev::StoreSignedIntDataViewElement::is_little_endian_input(), v8::internal::maglev::kContinue, v8::internal::compiler::turboshaft::TruncateJSPrimitiveToUntaggedOp::kObject, v8::internal::maglev::StoreSignedIntDataViewElement::object_input(), ToBit(), v8::internal::maglev::StoreSignedIntDataViewElement::type(), and v8::internal::maglev::StoreSignedIntDataViewElement::value_input().
Process() [223/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::StoreTaggedFieldNoWriteBarrier * node, const maglev::ProcessingState & state) [inline]
Definition at line 3061 of file turbolev-graph-builder.cc.
                                                                    {
    __ Store(Map(node->object_input()), Map(node->value_input()),
             StoreOp::Kind::TaggedBase(), MemoryRepresentation::AnyTagged(),
             WriteBarrierKind::kNoWriteBarrier, node->offset(),
             node->initializing_or_transitioning());
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::compiler::turboshaft::MemoryRepresentation::AnyTagged(), v8::internal::maglev::StoreTaggedFieldNoWriteBarrier::initializing_or_transitioning(), v8::internal::maglev::kContinue, v8::internal::compiler::kNoWriteBarrier, Map(), v8::internal::maglev::StoreTaggedFieldNoWriteBarrier::object_input(), v8::internal::maglev::StoreTaggedFieldNoWriteBarrier::offset(), v8::internal::wasm::liftoff::Store(), v8::internal::compiler::turboshaft::LoadOp::Kind::TaggedBase(), and v8::internal::maglev::StoreTaggedFieldNoWriteBarrier::value_input().
Process() [224/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::StoreTaggedFieldWithWriteBarrier * node, const maglev::ProcessingState & state) [inline]
Definition at line 3069 of file turbolev-graph-builder.cc.
                                                                    {
    __ Store(Map(node->object_input()), Map(node->value_input()),
             StoreOp::Kind::TaggedBase(), MemoryRepresentation::AnyTagged(),
             WriteBarrierKind::kFullWriteBarrier, node->offset(),
             node->initializing_or_transitioning());
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::compiler::turboshaft::MemoryRepresentation::AnyTagged(), v8::internal::maglev::StoreTaggedFieldWithWriteBarrier::initializing_or_transitioning(), v8::internal::maglev::kContinue, v8::internal::compiler::kFullWriteBarrier, Map(), v8::internal::maglev::StoreTaggedFieldWithWriteBarrier::object_input(), v8::internal::maglev::StoreTaggedFieldWithWriteBarrier::offset(), v8::internal::wasm::liftoff::Store(), v8::internal::compiler::turboshaft::LoadOp::Kind::TaggedBase(), and v8::internal::maglev::StoreTaggedFieldWithWriteBarrier::value_input().
Process() [225/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::StoreTrustedPointerFieldWithWriteBarrier * node, const maglev::ProcessingState & state) [inline]
Definition at line 3111 of file turbolev-graph-builder.cc.
                                          {
    __ Store(Map(node->object_input()), Map(node->value_input()),
             StoreOp::Kind::TaggedBase(),
             MemoryRepresentation::IndirectPointer(),
             WriteBarrierKind::kIndirectPointerWriteBarrier, node->offset(),
             node->initializing_or_transitioning(), node->tag());
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::compiler::turboshaft::MemoryRepresentation::IndirectPointer(), v8::internal::maglev::StoreTrustedPointerFieldWithWriteBarrier::initializing_or_transitioning(), v8::internal::maglev::kContinue, v8::internal::compiler::kIndirectPointerWriteBarrier, Map(), v8::internal::maglev::StoreTrustedPointerFieldWithWriteBarrier::object_input(), v8::internal::maglev::StoreTrustedPointerFieldWithWriteBarrier::offset(), v8::internal::wasm::liftoff::Store(), v8::internal::maglev::StoreTrustedPointerFieldWithWriteBarrier::tag(), v8::internal::compiler::turboshaft::LoadOp::Kind::TaggedBase(), and v8::internal::maglev::StoreTrustedPointerFieldWithWriteBarrier::value_input().
Process() [226/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::StringAt * node, const maglev::ProcessingState & state) [inline]
Definition at line 2818 of file turbolev-graph-builder.cc.
                                                                    {
    V<Word32> char_code =
        __ StringCharCodeAt(Map(node->string_input()),
                            __ ChangeUint32ToUintPtr(Map(node->index_input())));
    SetMap(node, __ ConvertCharCodeToString(char_code));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::StringAt::index_input(), v8::internal::maglev::kContinue, Map(), SetMap(), and v8::internal::maglev::StringAt::string_input().
Process() [227/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::StringConcat * node, const maglev::ProcessingState & state) [inline]
Definition at line 2775 of file turbolev-graph-builder.cc.
                                                                    {
    V<String> left = Map(node->lhs());
    V<String> right = Map(node->rhs());
    return StringConcatHelper(node, left, right);
  }
References v8::internal::maglev::StringConcat::lhs(), Map(), v8::internal::maglev::StringConcat::rhs(), and StringConcatHelper().
Process() [228/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::StringEqual * node, const maglev::ProcessingState & state) [inline]
Definition at line 2800 of file turbolev-graph-builder.cc.
                                                                    {
    if (node->inputs() == maglev::StringEqualInputs::kStringsOrOddballs) {
      // TODO(marja): Can we get rid of the StringOrOddballStrictEqual operator,
      // by handling the oddballs somewhere and delegating strings to
      // StringEqual?
      SetMap(node,
             __ StringOrOddballStrictEqual(Map(node->lhs()), Map(node->rhs())));
    } else {
      SetMap(node, __ StringEqual(Map(node->lhs()), Map(node->rhs())));
    }
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::StringEqual::inputs(), v8::internal::maglev::kContinue, v8::internal::maglev::kStringsOrOddballs, v8::internal::maglev::StringEqual::lhs(), Map(), v8::internal::maglev::StringEqual::rhs(), and SetMap().
Process() [229/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::StringLength * node, const maglev::ProcessingState & state) [inline]
Definition at line 2813 of file turbolev-graph-builder.cc.
                                                                    {
    SetMap(node, __ StringLength(Map(node->object_input())));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::kContinue, Map(), v8::internal::maglev::StringLength::object_input(), SetMap(), and v8::anonymous_namespace{api.cc}::StringLength().
Process() [230/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::Switch * node, const maglev::ProcessingState & state) [inline]
Definition at line 3755 of file turbolev-graph-builder.cc.
                                                                    {
    if (is_visiting_generator_main_switch_) {
      // This is the main resume-switch for a generator, and some of its target
      // bypass loop headers. We need to re-route the destinations to the
      // bypassed loop headers, where secondary switches will be inserted.
      compiler::turboshaft::SwitchOp::Case* cases =
          __ output_graph().graph_zone()
              -> AllocateArray<compiler::turboshaft::SwitchOp::Case>(
                               node->size());
      DCHECK_EQ(0, node->value_base());
      for (int i = 0; i < node->size(); i++) {
        maglev::BasicBlock* target = node->targets()[i].block_ptr();
        if (generator_analyzer_.JumpBypassesHeader(target)) {
          Block* new_dst = __ NewBlock();
          const maglev::BasicBlock* innermost_bypassed_header =
              generator_analyzer_.GetInnermostBypassedHeader(target);
          pre_loop_generator_blocks_[innermost_bypassed_header].push_back(
              {new_dst, Map(target), i});
          // {innermost_bypassed_header} is only the innermost bypassed header.
          // We also need to record bypasses of outer headers. In the end, we
          // want this main Switch to go to before the outermost header, which
          // will dispatch to the next inner loop, and so on until the innermost
          // loop header and then to the initial destination.
          for (const maglev::BasicBlock* bypassed_header =
                   generator_analyzer_.GetLoopHeader(innermost_bypassed_header);
               bypassed_header != nullptr;
               bypassed_header =
                   generator_analyzer_.GetLoopHeader(bypassed_header)) {
            Block* prev_loop_dst = __ NewBlock();
            pre_loop_generator_blocks_[bypassed_header].push_back(
                {prev_loop_dst, new_dst, i});
            new_dst = prev_loop_dst;
          }
          cases[i] = {i, new_dst, BranchHint::kNone};
        } else {
          cases[i] = {i, Map(target), BranchHint::kNone};
        }
      }
      Block* default_block = __ NewBlock();
      __ Switch(Map(node->value()), base::VectorOf(cases, node->size()),
                default_block);
      __ Bind(default_block);
      __ Unreachable();
      return maglev::ProcessResult::kContinue;
    }
    compiler::turboshaft::SwitchOp::Case* cases =
        __ output_graph().graph_zone()
            -> AllocateArray<compiler::turboshaft::SwitchOp::Case>(
                             node->size());
    int case_value_base = node->value_base();
    for (int i = 0; i < node->size(); i++) {
      cases[i] = {i + case_value_base, Map(node->targets()[i].block_ptr()),
                  BranchHint::kNone};
    }
    Block* default_block;
    bool emit_default_block = false;
    if (node->has_fallthrough()) {
      default_block = Map(state.next_block());
    } else {
      default_block = __ NewBlock();
      emit_default_block = true;
    }
    __ Switch(Map(node->value()), base::VectorOf(cases, node->size()),
              default_block);
    if (emit_default_block) {
      __ Bind(default_block);
      __ Unreachable();
    }
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::BasicBlockRef::block_ptr(), DCHECK_EQ, generator_analyzer_, v8::internal::compiler::turboshaft::GeneratorAnalyzer::GetInnermostBypassedHeader(), v8::internal::compiler::turboshaft::GeneratorAnalyzer::GetLoopHeader(), v8::internal::maglev::Switch::has_fallthrough(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, is_visiting_generator_main_switch_, v8::internal::compiler::turboshaft::GeneratorAnalyzer::JumpBypassesHeader(), v8::internal::maglev::kContinue, v8::internal::kNone, Map(), v8::internal::maglev::ProcessingState::next_block(), pre_loop_generator_blocks_, v8::internal::maglev::Switch::size(), v8::internal::maglev::Switch::targets(), v8::internal::maglev::Switch::value(), v8::internal::maglev::Switch::value_base(), and v8::base::VectorOf().
Process() [231/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::TaggedEqual * node, const maglev::ProcessingState & state) [inline]
Definition at line 3489 of file turbolev-graph-builder.cc.
                                                                    {
    SetMap(node, ConvertWord32ToJSBool(
                     __ TaggedEqual(Map(node->lhs()), Map(node->rhs()))));
    return maglev::ProcessResult::kContinue;
  }
References __, ConvertWord32ToJSBool(), v8::internal::maglev::kContinue, v8::internal::maglev::TaggedEqual::lhs(), Map(), v8::internal::maglev::TaggedEqual::rhs(), and SetMap().
Process() [232/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::TaggedIndexConstant * node, const maglev::ProcessingState & state) [inline]
Definition at line 1093 of file turbolev-graph-builder.cc.
                                                                    {
    // TODO(dmercadier): should this really be a SmiConstant, or rather a
    // Word32Constant?
    SetMap(node, __ SmiConstant(i::Tagged<Smi>(node->value().ptr())));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::kContinue, v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), SetMap(), and v8::internal::maglev::TaggedIndexConstant::value().
Process() [233/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::TaggedNotEqual * node, const maglev::ProcessingState & state) [inline]
Definition at line 3495 of file turbolev-graph-builder.cc.
                                                                    {
    SetMap(node, ConvertWord32ToJSBool(
                     __ TaggedEqual(Map(node->lhs()), Map(node->rhs())),
                     /*flip*/ true));
    return maglev::ProcessResult::kContinue;
  }
References __, ConvertWord32ToJSBool(), v8::internal::maglev::kContinue, v8::internal::maglev::TaggedNotEqual::lhs(), Map(), v8::internal::maglev::TaggedNotEqual::rhs(), and SetMap().
Process() [234/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::TestInstanceOf * node, const maglev::ProcessingState & state) [inline]
Definition at line 2131 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
    OpIndex arguments[] = {Map(node->object()), Map(node->callable()),
                           Map(node->context())};
    GENERATE_AND_MAP_BUILTIN_CALL(node, Builtin::kInstanceOf, frame_state,
                                  base::VectorOf(arguments));
    return maglev::ProcessResult::kContinue;
  }
References v8::internal::maglev::TestInstanceOf::callable(), v8::internal::maglev::TestInstanceOf::context(), GENERATE_AND_MAP_BUILTIN_CALL, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::kContinue, Map(), v8::internal::maglev::TestInstanceOf::object(), and v8::base::VectorOf().
Process() [235/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::TestTypeOf * node, const maglev::ProcessingState & state) [inline]
Definition at line 3518 of file turbolev-graph-builder.cc.
                                                                    {
    V<Object> input = Map(node->value());
    V<Boolean> result;
    switch (node->literal()) {
      case interpreter::TestTypeOfFlags::LiteralFlag::kNumber:
        result = ConvertWord32ToJSBool(
            __ ObjectIs(input, ObjectIsOp::Kind::kNumber,
                        ObjectIsOp::InputAssumptions::kNone));
        break;
      case interpreter::TestTypeOfFlags::LiteralFlag::kString:
        result = ConvertWord32ToJSBool(
            __ ObjectIs(input, ObjectIsOp::Kind::kString,
                        ObjectIsOp::InputAssumptions::kNone));
        break;
      case interpreter::TestTypeOfFlags::LiteralFlag::kSymbol:
        result = ConvertWord32ToJSBool(
            __ ObjectIs(input, ObjectIsOp::Kind::kSymbol,
                        ObjectIsOp::InputAssumptions::kNone));
        break;
      case interpreter::TestTypeOfFlags::LiteralFlag::kBigInt:
        result = ConvertWord32ToJSBool(
            __ ObjectIs(input, ObjectIsOp::Kind::kBigInt,
                        ObjectIsOp::InputAssumptions::kNone));
        break;
      case interpreter::TestTypeOfFlags::LiteralFlag::kFunction:
        result = ConvertWord32ToJSBool(
            __ ObjectIs(input, ObjectIsOp::Kind::kDetectableCallable,
                        ObjectIsOp::InputAssumptions::kNone));
        break;
      case interpreter::TestTypeOfFlags::LiteralFlag::kBoolean:
        result = __ Select(__ RootEqual(input, RootIndex::kTrueValue, isolate_),
                           __ HeapConstant(local_factory_->true_value()),
                           ConvertWord32ToJSBool(__ RootEqual(
                               input, RootIndex::kFalseValue, isolate_)),
                           RegisterRepresentation::Tagged(), BranchHint::kNone,
                           SelectOp::Implementation::kBranch);
        break;
      case interpreter::TestTypeOfFlags::LiteralFlag::kUndefined:
        result = __ Select(__ RootEqual(input, RootIndex::kNullValue, isolate_),
                           __ HeapConstant(local_factory_->false_value()),
                           ConvertWord32ToJSBool(__ ObjectIs(
                               input, ObjectIsOp::Kind::kUndetectable,
                               ObjectIsOp::InputAssumptions::kNone)),
                           RegisterRepresentation::Tagged(), BranchHint::kNone,
                           SelectOp::Implementation::kBranch);
        break;
      case interpreter::TestTypeOfFlags::LiteralFlag::kObject:
        result = __ Select(__ ObjectIs(input, ObjectIsOp::Kind::kNonCallable,
                                       ObjectIsOp::InputAssumptions::kNone),
                           __ HeapConstant(local_factory_->true_value()),
                           ConvertWord32ToJSBool(__ RootEqual(
                               input, RootIndex::kNullValue, isolate_)),
                           RegisterRepresentation::Tagged(), BranchHint::kNone,
                           SelectOp::Implementation::kBranch);
        break;
      case interpreter::TestTypeOfFlags::LiteralFlag::kOther:
        UNREACHABLE(); // Should never be emitted.
    }
    SetMap(node, result);
    return maglev::ProcessResult::kContinue;
  }
References __, ConvertWord32ToJSBool(), isolate_, v8::internal::compiler::turboshaft::ObjectIsOp::kBigInt, v8::internal::compiler::turboshaft::SelectOp::kBranch, v8::internal::maglev::kContinue, v8::internal::compiler::turboshaft::ObjectIsOp::kDetectableCallable, v8::internal::torque::ls::kFunction, v8::internal::compiler::turboshaft::ObjectIsOp::kNonCallable, v8::internal::kNone, v8::internal::compiler::turboshaft::ObjectIsOp::kNone, v8::internal::compiler::turboshaft::ObjectIsOp::kNumber, v8::internal::compiler::turboshaft::ObjectIsOp::kString, v8::internal::compiler::turboshaft::ObjectIsOp::kSymbol, v8::internal::compiler::turboshaft::ObjectIsOp::kUndetectable, v8::internal::maglev::TestTypeOf::literal(), local_factory_, Map(), v8::base::internal::result, RootEqual(), SetMap(), v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), v8::internal::UNREACHABLE(), and v8::internal::maglev::TestTypeOf::value().
Process() [236/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::TestUndetectable * node, const maglev::ProcessingState & state) [inline]
Definition at line 3502 of file turbolev-graph-builder.cc.
                                                                    {
    ObjectIsOp::InputAssumptions assumption;
    switch (node->check_type()) {
      case maglev::CheckType::kCheckHeapObject:
        assumption = ObjectIsOp::InputAssumptions::kNone;
        break;
      case maglev::CheckType::kOmitHeapObjectCheck:
        assumption = ObjectIsOp::InputAssumptions::kHeapObject;
        break;
    }
    SetMap(node, ConvertWord32ToJSBool(
                     __ ObjectIs(Map(node->value()),
                                 ObjectIsOp::Kind::kUndetectable, assumption)));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::TestUndetectable::check_type(), ConvertWord32ToJSBool(), v8::internal::maglev::kCheckHeapObject, v8::internal::maglev::kContinue, v8::internal::compiler::turboshaft::ObjectIsOp::kHeapObject, v8::internal::compiler::turboshaft::ObjectIsOp::kNone, v8::internal::maglev::kOmitHeapObjectCheck, v8::internal::compiler::turboshaft::ObjectIsOp::kUndetectable, Map(), SetMap(), and v8::internal::maglev::TestUndetectable::value().
Process() [237/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::ThrowIfNotCallable * node, const maglev::ProcessingState & state) [inline]
Definition at line 1636 of file turbolev-graph-builder.cc.
                                                                    {
    ThrowingScope throwing_scope(this, node);
    V<Object> value = Map(node->value());
    IF_NOT (LIKELY(__ ObjectIsCallable(value))) {
      GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
      __ CallRuntime_ThrowCalledNonCallable(
          isolate_, frame_state, native_context(), ShouldLazyDeoptOnThrow(node),
          value);
      // TODO(dmercadier): use RuntimeAbort here instead of Unreachable.
      // However, before doing so, RuntimeAbort should be changed so that 1)
      // it's a block terminator and 2) it doesn't call the runtime when
      // v8_flags.trap_on_abort is true.
      __ Unreachable();
    }
    return maglev::ProcessResult::kContinue;
  }
References __, GET_FRAME_STATE_MAYBE_ABORT, isolate_, v8::internal::maglev::kContinue, Map(), native_context(), ShouldLazyDeoptOnThrow(), v8::internal::maglev::ThrowIfNotCallable::value(), and v8::internal::value.
Process() [238/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::ThrowIfNotSuperConstructor * node, const maglev::ProcessingState & state) [inline]
Definition at line 1571 of file turbolev-graph-builder.cc.
                                                                    {
    ThrowingScope throwing_scope(this, node);
    V<HeapObject> constructor = Map(node->constructor());
    V<i::Map> map = __ LoadMapField(constructor);
    static_assert(Map::kBitFieldOffsetEnd + 1 - Map::kBitFieldOffset == 1);
    V<Word32> bitfield =
        __ template LoadField<Word32>(map, AccessBuilder::ForMapBitField());
    IF_NOT (LIKELY(__ Word32BitwiseAnd(bitfield,
                                       Map::Bits1::IsConstructorBit::kMask))) {
      GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
      __ CallRuntime_ThrowNotSuperConstructor(
          isolate_, frame_state, native_context(), ShouldLazyDeoptOnThrow(node),
          constructor, Map(node->function()));
      // TODO(dmercadier): use RuntimeAbort here instead of Unreachable.
      // However, before doing so, RuntimeAbort should be changed so that 1)
      // it's a block terminator and 2) it doesn't call the runtime when
      // v8_flags.trap_on_abort is true.
      __ Unreachable();
    }
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::ThrowIfNotSuperConstructor::constructor(), v8::internal::compiler::AccessBuilder::ForMapBitField(), v8::internal::maglev::ThrowIfNotSuperConstructor::function(), GET_FRAME_STATE_MAYBE_ABORT, isolate_, v8::internal::maglev::kContinue, Map(), native_context(), and ShouldLazyDeoptOnThrow().
Process() [239/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::ThrowReferenceErrorIfHole * node, const maglev::ProcessingState & state) [inline]
Definition at line 1553 of file turbolev-graph-builder.cc.
                                                                    {
    ThrowingScope throwing_scope(this, node);
    IF (UNLIKELY(RootEqual(node->value(), RootIndex::kTheHoleValue))) {
      GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
      __ CallRuntime_ThrowAccessedUninitializedVariable(
          isolate_, frame_state, native_context(), ShouldLazyDeoptOnThrow(node),
          __ HeapConstant(node->name().object()));
      // TODO(dmercadier): use RuntimeAbort here instead of Unreachable.
      // However, before doing so, RuntimeAbort should be changed so that 1)
      // it's a block terminator and 2) it doesn't call the runtime when
      // v8_flags.trap_on_abort is true.
      __ Unreachable();
    }
    return maglev::ProcessResult::kContinue;
  }
References __, GET_FRAME_STATE_MAYBE_ABORT, isolate_, v8::internal::maglev::kContinue, v8::internal::maglev::ThrowReferenceErrorIfHole::name(), native_context(), v8::internal::compiler::NameRef::object(), RootEqual(), ShouldLazyDeoptOnThrow(), and v8::internal::maglev::ThrowReferenceErrorIfHole::value().
Process() [240/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::ThrowSuperAlreadyCalledIfNotHole * node, const maglev::ProcessingState & state) [inline]
Definition at line 1596 of file turbolev-graph-builder.cc.
                                                                    {
    ThrowingScope throwing_scope(this, node);
    IF_NOT (LIKELY(__ RootEqual(Map(node->value()), RootIndex::kTheHoleValue,
                                isolate_))) {
      GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
      __ CallRuntime_ThrowSuperAlreadyCalledError(isolate_, frame_state,
                                                  native_context(),
                                                  ShouldLazyDeoptOnThrow(node));
      // TODO(dmercadier): use RuntimeAbort here instead of Unreachable.
      // However, before doing so, RuntimeAbort should be changed so that 1)
      // it's a block terminator and 2) it doesn't call the runtime when
      // v8_flags.trap_on_abort is true.
      __ Unreachable();
    }
    return maglev::ProcessResult::kContinue;
  }
References __, GET_FRAME_STATE_MAYBE_ABORT, isolate_, v8::internal::maglev::kContinue, Map(), native_context(), RootEqual(), ShouldLazyDeoptOnThrow(), and v8::internal::maglev::ThrowSuperAlreadyCalledIfNotHole::value().
Process() [241/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::ThrowSuperNotCalledIfHole * node, const maglev::ProcessingState & state) [inline]
Definition at line 1616 of file turbolev-graph-builder.cc.
                                                                    {
    ThrowingScope throwing_scope(this, node);
    IF (UNLIKELY(__ RootEqual(Map(node->value()), RootIndex::kTheHoleValue,
                              isolate_))) {
      GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
      __ CallRuntime_ThrowSuperNotCalled(isolate_, frame_state,
                                         native_context(),
                                         ShouldLazyDeoptOnThrow(node));
      // TODO(dmercadier): use RuntimeAbort here instead of Unreachable.
      // However, before doing so, RuntimeAbort should be changed so that 1)
      // it's a block terminator and 2) it doesn't call the runtime when
      // v8_flags.trap_on_abort is true.
      __ Unreachable();
    }
    return maglev::ProcessResult::kContinue;
  }
References __, GET_FRAME_STATE_MAYBE_ABORT, isolate_, v8::internal::maglev::kContinue, Map(), native_context(), RootEqual(), ShouldLazyDeoptOnThrow(), and v8::internal::maglev::ThrowSuperNotCalledIfHole::value().
Process() [242/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::ToBoolean * node, const maglev::ProcessingState & state) [inline]
Definition at line 4227 of file turbolev-graph-builder.cc.
                                                                    {
    TruncateJSPrimitiveToUntaggedOp::InputAssumptions input_assumptions;
    switch (node->check_type()) {
      case maglev::CheckType::kCheckHeapObject:
        input_assumptions =
            TruncateJSPrimitiveToUntaggedOp::InputAssumptions::kObject;
        break;
      case maglev::CheckType::kOmitHeapObjectCheck:
        input_assumptions =
            TruncateJSPrimitiveToUntaggedOp::InputAssumptions::kHeapObject;
        break;
    }
    SetMap(node,
Process() [243/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::ToBooleanLogicalNot * node, const maglev::ProcessingState & state) [inline]
Definition at line 4216 of file turbolev-graph-builder.cc.
                                                                    {
    TruncateJSPrimitiveToUntaggedOp::InputAssumptions assumption =
        node->check_type() == maglev::CheckType::kCheckHeapObject
            ? TruncateJSPrimitiveToUntaggedOp::InputAssumptions::kObject
            : TruncateJSPrimitiveToUntaggedOp::InputAssumptions::kHeapObject;
    V<Word32> condition = ToBit(node->value(), assumption);
Process() [244/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::ToName * node, const maglev::ProcessingState & state) [inline]
Definition at line 2157 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
    OpIndex arguments[] = {Map(node->value_input()), Map(node->context())};
    GENERATE_AND_MAP_BUILTIN_CALL(node, Builtin::kToName, frame_state,
                                  base::VectorOf(arguments));
    return maglev::ProcessResult::kContinue;
  }
References v8::internal::maglev::ToName::context(), GENERATE_AND_MAP_BUILTIN_CALL, GET_FRAME_STATE_MAYBE_ABORT, v8::internal::maglev::kContinue, Map(), v8::internal::maglev::ToName::value_input(), and v8::base::VectorOf().
Process() [245/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::ToNumberOrNumeric * node, const maglev::ProcessingState & state) [inline]
Definition at line 4198 of file turbolev-graph-builder.cc.
                                                                    {
    ThrowingScope throwing_scope(this, node);
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
    SetMap(node, __ ToNumberOrNumeric(Map(node->value_input()), frame_state,
                                      native_context(), node->mode(),
References __, GET_FRAME_STATE_MAYBE_ABORT, Map(), v8::internal::maglev::ToNumberOrNumeric::mode(), native_context(), SetMap(), ShouldLazyDeoptOnThrow(), and v8::internal::maglev::ToNumberOrNumeric::value_input().
Process() [246/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::ToObject * node, const maglev::ProcessingState & state) [inline]
Definition at line 4685 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
    OpIndex arguments[] = {Map(node->value_input()), Map(node->context())};
    GENERATE_AND_MAP_BUILTIN_CALL(node, Builtin::kToObject, frame_state,
                                  base::VectorOf(arguments));
Process() [247/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::ToString * node, const maglev::ProcessingState & state) [inline]
Definition at line 2885 of file turbolev-graph-builder.cc.
                                                                    {
    ThrowingScope throwing_scope(this, node);
    Label<String> done(this);
    V<Object> value = Map(node->value_input());
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
    GOTO_IF(__ ObjectIsString(value), done, V<String>::Cast(value));
    IF_NOT (__ IsSmi(value)) {
      if (node->mode() == maglev::ToString::ConversionMode::kConvertSymbol) {
        V<i::Map> map = __ LoadMapField(value);
        V<Word32> instance_type = __ LoadInstanceTypeField(map);
        IF (__ Word32Equal(instance_type, SYMBOL_TYPE)) {
          GOTO(done, __ CallRuntime_SymbolDescriptiveString(
                         isolate_, frame_state, Map(node->context()),
                         V<Symbol>::Cast(value), ShouldLazyDeoptOnThrow(node)));
        }
      }
    }
    GOTO(done,
         __ CallBuiltin_ToString(isolate_, frame_state, Map(node->context()),
                                 value, ShouldLazyDeoptOnThrow(node)));
    BIND(done, result);
    SetMap(node, result);
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::ToString::context(), GET_FRAME_STATE_MAYBE_ABORT, isolate_, v8::internal::IsSmi(), v8::internal::maglev::kContinue, Map(), v8::internal::maglev::ToString::mode(), v8::base::internal::result, SetMap(), ShouldLazyDeoptOnThrow(), v8::internal::value, v8::internal::maglev::ToString::value_input(), and v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal().
Process() [248/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::TransitionAndStoreArrayElement * node, const maglev::ProcessingState & state) [inline]
Definition at line 2660 of file turbolev-graph-builder.cc.
                                                                    {
    __ TransitionAndStoreArrayElement(
        Map(node->array_input()),
        __ ChangeInt32ToIntPtr(Map(node->index_input())),
        Map(node->value_input()),
        TransitionAndStoreArrayElementOp::Kind::kElement,
        node->fast_map().object(), node->double_map().object());
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::TransitionAndStoreArrayElement::array_input(), v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::ChangeInt32ToIntPtr(), v8::internal::maglev::TransitionAndStoreArrayElement::double_map(), v8::internal::maglev::TransitionAndStoreArrayElement::fast_map(), v8::internal::maglev::TransitionAndStoreArrayElement::index_input(), v8::internal::maglev::kContinue, v8::internal::compiler::turboshaft::TransitionAndStoreArrayElementOp::kElement, Map(), v8::internal::compiler::MapRef::object(), and v8::internal::maglev::TransitionAndStoreArrayElement::value_input().
Process() [249/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::TransitionElementsKind * node, const maglev::ProcessingState & state) [inline]
Definition at line 2683 of file turbolev-graph-builder.cc.
                                                                    {
    SetMap(node, __ TransitionMultipleElementsKind(
                     Map(node->object_input()), Map(node->map_input()),
                     node->transition_sources(), node->transition_target()));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::kContinue, Map(), v8::internal::maglev::TransitionElementsKind::map_input(), v8::internal::maglev::TransitionElementsKind::object_input(), SetMap(), v8::internal::maglev::TransitionElementsKind::transition_sources(), and v8::internal::maglev::TransitionElementsKind::transition_target().
Process() [250/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::TransitionElementsKindOrCheckMap * node, const maglev::ProcessingState & state) [inline]
Definition at line 2671 of file turbolev-graph-builder.cc.
                                                                    {
    GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->eager_deopt_info());
    ZoneRefSet<i::Map> sources(node->transition_sources().begin(),
                               node->transition_sources().end(), graph_zone());
    __ TransitionElementsKindOrCheckMap(
        Map(node->object_input()), Map(node->map_input()), frame_state,
        ElementsTransitionWithMultipleSources(
            sources, node->transition_target(),
            node->eager_deopt_info()->feedback_to_update()));
    return maglev::ProcessResult::kContinue;
  }
References __, GET_FRAME_STATE_MAYBE_ABORT, graph_zone(), v8::internal::maglev::kContinue, Map(), v8::internal::maglev::TransitionElementsKindOrCheckMap::map_input(), v8::internal::maglev::TransitionElementsKindOrCheckMap::object_input(), v8::internal::maglev::TransitionElementsKindOrCheckMap::transition_sources(), and v8::internal::maglev::TransitionElementsKindOrCheckMap::transition_target().
Process() [251/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::TruncateFloat64ToInt32 * node, const maglev::ProcessingState & state) [inline]
Definition at line 4524 of file turbolev-graph-builder.cc.
                                                                    {
Process() [252/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::TruncateNumberOrOddballToInt32 * node, const maglev::ProcessingState & state) [inline]
Definition at line 4509 of file turbolev-graph-builder.cc.
                                                                    {
    // In Maglev, TruncateNumberOrOddballToInt32 does the same thing for both
    // NumberOrOddball and Number; except when debug_code is enabled: then,
    // Maglev inserts runtime checks ensuring that the input is indeed a Number
    // or NumberOrOddball. Turboshaft doesn't typically introduce such runtime
    // checks, so we instead just lower both Number and NumberOrOddball to the
    // NumberOrOddball variant.
    SetMap(node, __ TruncateJSPrimitiveToUntagged(
                     Map(node->input()),
                     TruncateJSPrimitiveToUntaggedOp::UntaggedKind::kInt32,
                     TruncateJSPrimitiveToUntaggedOp::InputAssumptions::
Process() [253/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::TruncateUint32ToInt32 * node, const maglev::ProcessingState & state) [inline]
Definition at line 4364 of file turbolev-graph-builder.cc.
                                                                    {
    // This doesn't matter in Turboshaft: both Uint32 and Int32 are Word32.
Process() [254/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::TrustedConstant * node, const maglev::ProcessingState & state) [inline]
Definition at line 1100 of file turbolev-graph-builder.cc.
                                                                    {
    SetMap(node, __ TrustedHeapConstant(node->object().object()));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::kContinue, v8::internal::compiler::HeapObjectRef::object(), v8::internal::maglev::TrustedConstant::object(), and SetMap().
Process() [255/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::TryOnStackReplacement * , const maglev::ProcessingState &) [inline]
Definition at line 4806 of file turbolev-graph-builder.cc.
                                                              {
Process() [256/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::Uint32Constant * node, const maglev::ProcessingState & state) [inline]
Definition at line 1071 of file turbolev-graph-builder.cc.
                                                                    {
    SetMap(node, __ Word32SignHintUnsigned(__ Word32Constant(node->value())));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::kContinue, SetMap(), and v8::internal::maglev::Uint32Constant::value().
Process() [257/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::Uint32ToNumber * node, const maglev::ProcessingState & state) [inline]
Definition at line 4267 of file turbolev-graph-builder.cc.
                                                                    {
Process() [258/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::Uint32ToUint8Clamped * node, const maglev::ProcessingState & state) [inline]
Definition at line 4646 of file turbolev-graph-builder.cc.
                                                                    {
    ScopedVar<Word32, AssemblerT> result(this);
    V<Word32> value = Map(node->input());
    IF (__ Uint32LessThan(value, kMaxClampedUint8)) {
      result = value;
    } ELSE {
      result = __ Word32Constant(kMaxClampedUint8);
    }
Process() [259/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::UncheckedNumberOrOddballToFloat64 * node, const maglev::ProcessingState & state) [inline]
Definition at line 4352 of file turbolev-graph-builder.cc.
                                                                    {
    // `node->conversion_type()` doesn't matter here, since for both HeapNumbers
    // and Oddballs, the Float64 value is at the same index (and this node never
    // deopts, regardless of its input).
    SetMap(node, __ ConvertJSPrimitiveToUntagged(
                     Map(node->input()),
                     ConvertJSPrimitiveToUntaggedOp::UntaggedKind::kFloat64,
                     ConvertJSPrimitiveToUntaggedOp::InputAssumptions::
Process() [260/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::UnsafeInt32ToUint32 * node, const maglev::ProcessingState & state) [inline]
Definition at line 4420 of file turbolev-graph-builder.cc.
                                                                    {
Process() [261/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::UnsafeSmiTagInt32 * node, const maglev::ProcessingState & state) [inline]
Definition at line 3909 of file turbolev-graph-builder.cc.
                                                                    {
    SetMap(node, __ TagSmi(Map(node->input())));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::UnsafeSmiTagInt32::input(), v8::internal::maglev::kContinue, Map(), and SetMap().
Process() [262/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::UnsafeSmiTagIntPtr * node, const maglev::ProcessingState & state) [inline]
Definition at line 3920 of file turbolev-graph-builder.cc.
                                                                    {
    // TODO(388844115): Rename the IntPtr in Maglev to make it clear it's
    // non-negative.
    SetMap(node, __ TagSmi(__ TruncateWordPtrToWord32(Map(node->input()))));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::UnsafeSmiTagIntPtr::input(), v8::internal::maglev::kContinue, Map(), and SetMap().
Process() [263/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::UnsafeSmiTagUint32 * node, const maglev::ProcessingState & state) [inline]
Definition at line 3914 of file turbolev-graph-builder.cc.
                                                                    {
    SetMap(node, __ TagSmi(Map(node->input())));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::UnsafeSmiTagUint32::input(), v8::internal::maglev::kContinue, Map(), and SetMap().
Process() [264/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::UnsafeSmiUntag * node, const maglev::ProcessingState & state) [inline]
Definition at line 3846 of file turbolev-graph-builder.cc.
                                                                    {
    SetMap(node, __ UntagSmi(Map(node->input())));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::UnsafeSmiUntag::input(), v8::internal::maglev::kContinue, Map(), and SetMap().
Process() [265/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::UnsafeTruncateFloat64ToInt32 * , const maglev::ProcessingState &) [inline]
Definition at line 4886 of file turbolev-graph-builder.cc.
                                                              {
    UNREACHABLE();
  }
  maglev::ProcessResult Process(maglev::UnsafeTruncateFloat64ToInt32*,
References v8::internal::UNREACHABLE().
Process() [266/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::UnsafeTruncateUint32ToInt32 * , const maglev::ProcessingState &) [inline]
Definition at line 4882 of file turbolev-graph-builder.cc.
                                                              {
    UNREACHABLE();
  }
  maglev::ProcessResult Process(maglev::UnsafeTruncateUint32ToInt32*,
References v8::internal::UNREACHABLE().
Process() [267/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::UnwrapStringWrapper * node, const maglev::ProcessingState & state) [inline]
Definition at line 2781 of file turbolev-graph-builder.cc.
                                                                    {
    V<HeapObject> string_or_wrapper = Map(node->value_input());
    ScopedVar<String, AssemblerT> string(this);
    IF (__ ObjectIsString(string_or_wrapper)) {
      string = V<String>::Cast(string_or_wrapper);
    } ELSE {
      string = V<String>::Cast(
          __ LoadTaggedField(V<JSPrimitiveWrapper>::Cast(string_or_wrapper),
                             JSPrimitiveWrapper::kValueOffset));
    }
    SetMap(node, string);
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::compiler::turboshaft::V< T >::Cast(), v8::internal::maglev::kContinue, Map(), SetMap(), v8::internal::string, and v8::internal::maglev::UnwrapStringWrapper::value_input().
Process() [268/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::UpdateJSArrayLength * node, const maglev::ProcessingState & state) [inline]
Definition at line 2702 of file turbolev-graph-builder.cc.
                                                                    {
    SetMap(node, __ UpdateJSArrayLength(Map(node->length_input()),
                                        Map(node->object_input()),
                                        Map(node->index_input())));
    return maglev::ProcessResult::kContinue;
  }
References __, v8::internal::maglev::UpdateJSArrayLength::index_input(), v8::internal::maglev::kContinue, v8::internal::maglev::UpdateJSArrayLength::length_input(), Map(), v8::internal::maglev::UpdateJSArrayLength::object_input(), and SetMap().
Process() [269/269]
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process (maglev::VirtualObject * , const maglev::ProcessingState &) [inline]
Definition at line 4788 of file turbolev-graph-builder.cc.
                                                              {
RecordRepresentation()
void v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::RecordRepresentation (OpIndex idx, maglev::ValueRepresentation repr) [inline], [private]
Definition at line 6055 of file turbolev-graph-builder.cc.
                                                                         {
    DCHECK_IMPLIES(maglev_representations_.contains(idx),
RegisterRepresentationFor()
RegisterRepresentation v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::RegisterRepresentationFor (maglev::ValueRepresentation value_rep) [inline], [private]
Definition at line 5766 of file turbolev-graph-builder.cc.
                                           {
    switch (value_rep) {
      case maglev::ValueRepresentation::kTagged:
        return RegisterRepresentation::Tagged();
      case maglev::ValueRepresentation::kInt32:
      case maglev::ValueRepresentation::kUint32:
        return RegisterRepresentation::Word32();
      case maglev::ValueRepresentation::kFloat64:
      case maglev::ValueRepresentation::kHoleyFloat64:
        return RegisterRepresentation::Float64();
      case maglev::ValueRepresentation::kIntPtr:
Referenced by MakePhiMaybePermuteInputs(), and Process().
RootEqual()
V<Word32> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::RootEqual (maglev::Input input, RootIndex root) [inline], [private]
Definition at line 5615 of file turbolev-graph-builder.cc.
Referenced by Process().
SetMap()
void v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::SetMap (maglev::NodeBase * node, V< Any > idx) [inline], [private]
Definition at line 6031 of file turbolev-graph-builder.cc.
                                            { return block_mapping_[block]; }
  void SetMap(maglev::NodeBase* node, V<Any> idx) {
    if (__ generating_unreachable_operations()) return;
    DCHECK(idx.valid());
Referenced by Process(), and StringConcatHelper().
SetMapMaybeMultiReturn()
void v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::SetMapMaybeMultiReturn (maglev::NodeBase * node, V< Any > idx) [inline], [private]
Definition at line 6038 of file turbolev-graph-builder.cc.
                                                                {
    const Operation& op = __ output_graph().Get(idx);
    if (const TupleOp* tuple = op.TryCast<TupleOp>()) {
      // If the call returned multiple values, then in Maglev, {node} is
      // used as the 1st returned value, and a GetSecondReturnedValue node is
      // used to access the 2nd value. We thus call `SetMap` with the 1st
      // projection of the call, and record the 2nd projection in
      // {second_return_value_}, which we'll use when translating
      // GetSecondReturnedValue.
      DCHECK_EQ(tuple->input_count, 2);
      SetMap(node, tuple->input(0));
      second_return_value_ = tuple->input<Object>(1);
    } else {
Referenced by Process().
ShouldLazyDeoptOnThrow()
LazyDeoptOnThrow v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ShouldLazyDeoptOnThrow (maglev::NodeBase * node) [inline], [private]
Definition at line 5833 of file turbolev-graph-builder.cc.
                                                                {
    if (!node->properties().can_throw()) return LazyDeoptOnThrow::kNo;
    const maglev::ExceptionHandlerInfo* info = node->exception_handler_info();
Referenced by GenerateBuiltinCall(), Process(), and StringConcatHelper().
StartExceptionBlock()
void v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::StartExceptionBlock (maglev::BasicBlock * maglev_catch_handler) [inline]
Definition at line 739 of file turbolev-graph-builder.cc.
                                                                   {
    Block* turboshaft_catch_handler = Map(maglev_catch_handler);
    if (turboshaft_catch_handler->PredecessorCount() == 0) {
      // Some Assembler optimizations made this catch handler not be actually
      // reachable.
      return;
    }
    if (turboshaft_catch_handler->PredecessorCount() == 1) {
      StartSinglePredecessorExceptionBlock(maglev_catch_handler,
                                           turboshaft_catch_handler);
    } else {
      StartMultiPredecessorExceptionBlock(maglev_catch_handler,
                                          turboshaft_catch_handler);
    }
  }
References Map(), v8::internal::compiler::turboshaft::Block::PredecessorCount(), StartMultiPredecessorExceptionBlock(), and StartSinglePredecessorExceptionBlock().
Referenced by PreProcessBasicBlock().
StartMultiPredecessorExceptionBlock()
void v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::StartMultiPredecessorExceptionBlock (maglev::BasicBlock * maglev_catch_handler, Block * turboshaft_catch_handler) [inline]
Definition at line 804 of file turbolev-graph-builder.cc.
                                       {
    if (!maglev_catch_handler->has_phi()) {
      // The very simple case: the catch handler didn't have any Phis, we don't
      // have to do anything complex.
      if (!__ Bind(turboshaft_catch_handler)) return;
      catch_block_begin_ = __ CatchBlockBegin();
      return;
    }
    // Inserting the tagging in all of the predecessors.
    auto predecessors = turboshaft_catch_handler->Predecessors();
    turboshaft_catch_handler->ResetAllPredecessors();
    base::SmallVector<V<Object>, 16> catch_block_begins;
    for (Block* predecessor : predecessors) {
      // Recording the CatchBlockBegin of this predecessor.
      V<Object> catch_begin = predecessor->begin();
      DCHECK(Asm().Get(catch_begin).template Is<CatchBlockBeginOp>());
      catch_block_begins.push_back(catch_begin);
      TagExceptionPhiInputsForBlock(predecessor, maglev_catch_handler,
                                    turboshaft_catch_handler);
    }
    // Finally binding the catch handler.
    __ Bind(turboshaft_catch_handler);
    // We now need to insert a Phi for the CatchBlockBegins of the
    // predecessors (usually, we would just call `__ CatchBlockbegin`, which
    // takes care of creating a Phi node if necessary, but this won't work here,
    // because this mechanisms expects the CatchBlockBegin to be the 1st
    // instruction of the predecessors, and it isn't the case since the
    // predecessors are now the blocks with the tagging).
    catch_block_begin_ = __ Phi(base::VectorOf(catch_block_begins));
  }
References __, Asm(), catch_block_begin_, v8::internal::DCHECK(), v8::internal::compiler::turboshaft::Get(), v8::internal::maglev::BasicBlock::has_phi(), v8::internal::compiler::turboshaft::Block::Predecessors(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), v8::internal::compiler::turboshaft::Block::ResetAllPredecessors(), TagExceptionPhiInputsForBlock(), and v8::base::VectorOf().
Referenced by StartExceptionBlock().
StartSinglePredecessorExceptionBlock()
void v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::StartSinglePredecessorExceptionBlock (maglev::BasicBlock * maglev_catch_handler, Block * turboshaft_catch_handler) [inline]
Definition at line 754 of file turbolev-graph-builder.cc.
                                       {
    if (!__ Bind(turboshaft_catch_handler)) return;
    catch_block_begin_ = __ CatchBlockBegin();
    if (!maglev_catch_handler->has_phi()) return;
    InsertTaggingForPhis(maglev_catch_handler);
  }
References __, catch_block_begin_, v8::internal::maglev::BasicBlock::has_phi(), and InsertTaggingForPhis().
Referenced by StartExceptionBlock().
StringConcatHelper()
template<typename Node >
maglev::ProcessResult v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::StringConcatHelper (Node * node, V< String > left, V< String > right) [inline]
Definition at line 2729 of file turbolev-graph-builder.cc.
                                                            {
    // When coming from Turbofan, StringConcat is always guarded by a check that
    // the length is less than String::kMaxLength, which prevents StringConcat
    // from ever throwing (and as a consequence of this, it does not need a
    // Context input). This is not the case for Maglev. To mimic Turbofan's
    // behavior, we thus insert here a length check.
    // TODO(dmercadier): I'm not convinced that these checks make a lot of
    // sense, since they make the graph bigger, and throwing before the builtin
    // call to StringConcat isn't super important since throwing is not supposed
    // to be fast. We should consider just calling the builtin and letting it
    // throw. With LazyDeopOnThrow, this is currently a bit verbose to
    // implement, so we should first find a way to have this LazyDeoptOnThrow
    // without adding a member to all throwing operations (like adding
    // LazyDeoptOnThrow in FrameStateOp).
    ThrowingScope throwing_scope(this, node);
    V<Word32> left_len = __ StringLength(left);
    V<Word32> right_len = __ StringLength(right);
    V<Tuple<Word32, Word32>> len_and_ovf =
        __ Int32AddCheckOverflow(left_len, right_len);
    V<Word32> len = __ Projection<0>(len_and_ovf);
    V<Word32> ovf = __ Projection<1>(len_and_ovf);
    Label<> throw_invalid_length(this);
    Label<> done(this);
    GOTO_IF(UNLIKELY(ovf), throw_invalid_length);
    GOTO_IF(LIKELY(__ Uint32LessThanOrEqual(len, String::kMaxLength)), done);
    GOTO(throw_invalid_length);
    BIND(throw_invalid_length);
    {
      GET_FRAME_STATE_MAYBE_ABORT(frame_state, node->lazy_deopt_info());
      __ CallRuntime_ThrowInvalidStringLength(isolate_, frame_state,
                                              native_context(),
                                              ShouldLazyDeoptOnThrow(node));
      // We should not return from Throw.
      __ Unreachable();
    }
    BIND(done);
    SetMap(node, __ StringConcat(__ TagSmi(len), left, right));
    return maglev::ProcessResult::kContinue;
  }
References __, GET_FRAME_STATE_MAYBE_ABORT, isolate_, v8::internal::maglev::kContinue, v8::internal::String::kMaxLength, native_context(), SetMap(), ShouldLazyDeoptOnThrow(), and v8::anonymous_namespace{api.cc}::StringLength().
Referenced by Process().
TagExceptionPhiInputsForBlock()
void v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::TagExceptionPhiInputsForBlock (Block * old_block, maglev::BasicBlock * maglev_catch_handler, Block * turboshaft_catch_handler) [inline]
Definition at line 840 of file turbolev-graph-builder.cc.
                                                                      {
    DCHECK(maglev_catch_handler->has_phi());
    // We start by patching in-place the predecessors final Goto of {old_block}
    // to jump to a new block (in which we'll insert the tagging).
    Block* new_block = __ NewBlock();
    const GotoOp& old_goto =
        old_block->LastOperation(__ output_graph()).Cast<GotoOp>();
    DCHECK_EQ(old_goto.destination, turboshaft_catch_handler);
    __ output_graph().Replace<GotoOp>(__ output_graph().Index(old_goto),
                                      new_block, /* is_backedge */ false);
    __ AddPredecessor(old_block, new_block, false);
    // Now, we bind the new block and insert the taggings
    __ BindReachable(new_block);
    InsertTaggingForPhis(maglev_catch_handler);
    // Finally, we just go from this block to the catch handler.
    __ Goto(turboshaft_catch_handler);
  }
References __, v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::GotoOp::destination, v8::internal::maglev::BasicBlock::has_phi(), InsertTaggingForPhis(), and v8::internal::compiler::turboshaft::Block::LastOperation().
Referenced by StartMultiPredecessorExceptionBlock().
temp_zone()
Zone* v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::temp_zone () [inline]
Definition at line 4896 of file turbolev-graph-builder.cc.
{ return assembler_; }
ToBit()
V<Word32> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ToBit (maglev::Input input, TruncateJSPrimitiveToUntaggedOp::InputAssumptions assumptions) [inline], [private]
Definition at line 5808 of file turbolev-graph-builder.cc.
                                                                   {
    // TODO(dmercadier): {input} in Maglev is of type Object (like, any
    // HeapObject or Smi). However, the implementation of ToBoolean in Maglev is
    // identical to the lowering of TruncateJSPrimitiveToUntaggedOp(kBit) in
    // Turboshaft (which is done in MachineLoweringReducer), so we're using
    // TruncateJSPrimitiveToUntaggedOp with a non-JSPrimitive input (but it
    // still works). We should avoid doing this to avoid any confusion. Renaming
    // TruncateJSPrimitiveToUntagged to TruncateObjectToUntagged might be the
    // proper fix, in particular because it seems that the Turbofan input to
    // this operation is indeed an Object rather than a JSPrimitive (since
    // we use this operation in the regular TF->TS graph builder to translate
    // TruncateTaggedToBit and TruncateTaggedPointerToBit).
    return V<Word32>::Cast(__ TruncateJSPrimitiveToUntagged(
Referenced by Process().
Member Data Documentation
assembler_
AssemblerT v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::assembler_ [private]
Definition at line 6072 of file turbolev-graph-builder.cc.
Referenced by graph_zone().
bailout_
std::optional<BailoutReason>* v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::bailout_ [private]
Definition at line 6179 of file turbolev-graph-builder.cc.
block_mapping_
ZoneUnorderedMap<const maglev::BasicBlock*, Block*> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::block_mapping_ [private]
Definition at line 6075 of file turbolev-graph-builder.cc.
Referenced by PreProcessGraph().
broker_
JSHeapBroker* v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::broker_ = data_->broker() [private]
Definition at line 6070 of file turbolev-graph-builder.cc.
Referenced by PreProcessGraph(), and Process().
catch_block_begin_
V<Object> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::catch_block_begin_ = V<Object>::Invalid() [private]
Definition at line 6091 of file turbolev-graph-builder.cc.
Referenced by PreProcessBasicBlock(), Process(), StartMultiPredecessorExceptionBlock(), and StartSinglePredecessorExceptionBlock().
data_
PipelineData* v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::data_ [private]
Definition at line 6066 of file turbolev-graph-builder.cc.
deduplicator_
Deduplicator v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::deduplicator_ [private]
Definition at line 6083 of file turbolev-graph-builder.cc.
dummy_float64_input_
V<Float64> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::dummy_float64_input_ = V<Float64>::Invalid() [private]
Definition at line 6152 of file turbolev-graph-builder.cc.
Referenced by EmitLoopSinglePredecessorBlock(), and PreProcessGraph().
dummy_object_input_
V<Object> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::dummy_object_input_ = V<Object>::Invalid() [private]
Definition at line 6150 of file turbolev-graph-builder.cc.
Referenced by EmitLoopSinglePredecessorBlock(), and PreProcessGraph().
dummy_word32_input_
V<Word32> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::dummy_word32_input_ = V<Word32>::Invalid() [private]
Definition at line 6151 of file turbolev-graph-builder.cc.
Referenced by EmitLoopSinglePredecessorBlock(), and PreProcessGraph().
generator_analyzer_
GeneratorAnalyzer v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::generator_analyzer_ [private]
Definition at line 6128 of file turbolev-graph-builder.cc.
Referenced by BuildJump(), IsMaglevMainGeneratorSwitchBlock(), PreProcessGraph(), and Process().
generator_context_
Variable v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::generator_context_ [private]
Definition at line 6165 of file turbolev-graph-builder.cc.
Referenced by PreProcessGraph(), and Process().
header_switch_input_
Variable v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::header_switch_input_ [private]
Definition at line 6140 of file turbolev-graph-builder.cc.
Referenced by EmitLoopSinglePredecessorBlock(), PostPhiProcessing(), PreProcessGraph(), and Process().
is_visiting_generator_main_switch_
bool v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::is_visiting_generator_main_switch_ = false [private]
Definition at line 6133 of file turbolev-graph-builder.cc.
Referenced by PreProcessBasicBlock(), and Process().
isolate_
Isolate* v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::isolate_ = data_->isolate() [private]
Definition at line 6068 of file turbolev-graph-builder.cc.
Referenced by GenerateBuiltinCall(), Process(), and StringConcatHelper().
kDefaultSwitchVarValue
constexpr int v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::kDefaultSwitchVarValue = -1 [static], [constexpr], [private]
Definition at line 6129 of file turbolev-graph-builder.cc.
Referenced by PreProcessGraph().
kMaxClampedUint8
constexpr int v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::kMaxClampedUint8 = 255 [static], [constexpr]
Definition at line 4614 of file turbolev-graph-builder.cc.
Referenced by Int32ToUint8Clamped().
kMinClampedUint8
constexpr int v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::kMinClampedUint8 = 0 [static], [constexpr]
Definition at line 4613 of file turbolev-graph-builder.cc.
Referenced by Int32ToUint8Clamped().
local_factory_
LocalFactory* v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::local_factory_ = local_isolate_->factory() [private]
Definition at line 6071 of file turbolev-graph-builder.cc.
Referenced by PreProcessGraph(), and Process().
local_isolate_
LocalIsolate* v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::local_isolate_ = isolate_->AsLocalIsolate() [private]
Definition at line 6069 of file turbolev-graph-builder.cc.
Referenced by Process().
loop_default_generator_value_
V<Word32> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::loop_default_generator_value_ = V<Word32>::Invalid() [private]
Definition at line 6145 of file turbolev-graph-builder.cc.
Referenced by EmitLoopSinglePredecessorBlock(), PreProcessGraph(), and Process().
loop_phis_first_input_
base::SmallVector<OpIndex, 16> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::loop_phis_first_input_ [private]
Definition at line 6107 of file turbolev-graph-builder.cc.
Referenced by EmitLoopSinglePredecessorBlock(), PreProcessBasicBlock(), and Process().
loop_phis_first_input_index_
int v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::loop_phis_first_input_index_ = -1 [private]
Definition at line 6108 of file turbolev-graph-builder.cc.
Referenced by EmitLoopSinglePredecessorBlock(), PreProcessBasicBlock(), and Process().
loop_single_edge_predecessors_
ZoneUnorderedMap<const maglev::BasicBlock*, Block*> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::loop_single_edge_predecessors_ [private]
Definition at line 6100 of file turbolev-graph-builder.cc.
Referenced by BuildJump(), EmitLoopSinglePredecessorBlock(), PreProcessBasicBlock(), and Process().
maglev_compilation_unit_
maglev::MaglevCompilationUnit* v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::maglev_compilation_unit_ [private]
Definition at line 6073 of file turbolev-graph-builder.cc.
Referenced by PreProcessGraph(), and Process().
maglev_generator_context_node_
maglev::NodeBase* v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::maglev_generator_context_node_ = nullptr [private]
Definition at line 6164 of file turbolev-graph-builder.cc.
Referenced by Process().
maglev_representations_
ZoneAbslFlatHashMap<OpIndex, maglev::ValueRepresentation> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::maglev_representations_ [private]
Definition at line 6126 of file turbolev-graph-builder.cc.
Referenced by InsertTaggingForPhis().
native_context_
V<NativeContext> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::native_context_ = V<NativeContext>::Invalid() [private]
Definition at line 6175 of file turbolev-graph-builder.cc.
Referenced by PreProcessGraph().
new_target_param_
V<Object> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::new_target_param_ = V<Object>::Invalid() [private]
Definition at line 6176 of file turbolev-graph-builder.cc.
Referenced by PreProcessGraph(), and Process().
node_mapping_
ZoneUnorderedMap<const maglev::NodeBase*, OpIndex> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::node_mapping_ [private]
Definition at line 6074 of file turbolev-graph-builder.cc.
on_generator_switch_loop_
bool v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::on_generator_switch_loop_ = false [private]
Definition at line 6137 of file turbolev-graph-builder.cc.
Referenced by EmitLoopSinglePredecessorBlock(), and PostPhiProcessing().
pre_loop_generator_blocks_
std::unordered_map<const maglev::BasicBlock*, std::vector<GeneratorSplitEdge> > v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::pre_loop_generator_blocks_ [private]
Definition at line 6173 of file turbolev-graph-builder.cc.
Referenced by EmitLoopSinglePredecessorBlock(), PostPhiProcessing(), PreProcessBasicBlock(), and Process().
predecessor_permutation_
base::SmallVector<int, 16> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::predecessor_permutation_ [private]
Definition at line 6177 of file turbolev-graph-builder.cc.
Referenced by ComputePredecessorPermutations(), MakePhiMaybePermuteInputs(), and PreProcessBasicBlock().
regs_to_vars_
ZoneUnorderedMap<int, Variable> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::regs_to_vars_ [private]
Definition at line 6076 of file turbolev-graph-builder.cc.
Referenced by Process().
second_return_value_
V<Object> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::second_return_value_ = V<Object>::Invalid() [private]
Definition at line 6117 of file turbolev-graph-builder.cc.
Referenced by Process().
temp_zone_
Zone* v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::temp_zone_ [private]
Definition at line 6067 of file turbolev-graph-builder.cc.
Referenced by IsMapped().
undefined_value_
V<HeapObject> v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::undefined_value_ [private]
Definition at line 6078 of file turbolev-graph-builder.cc.
Referenced by PreProcessGraph(), and Process().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/turbolev-graph-builder.cc