v8::tracing::TracingCategoryObserver Class Reference
#include <tracing-category-observer.h>
Public Types
enum Mode { ENABLED_BY_NATIVE = 1 << 0
, ENABLED_BY_TRACING = 1 << 1
, ENABLED_BY_SAMPLING = 1 << 2
 }
Public Member Functions
void OnTraceEnabled () final
void OnTraceDisabled () final
Static Public Member Functions
static void SetUp ()
static void TearDown ()
Static Private Attributes
static TracingCategoryObserver * instance_ = nullptr
Detailed Description
Definition at line 14 of file tracing-category-observer.h.
Member Enumeration Documentation
Mode
enum v8::tracing::TracingCategoryObserver::Mode
Enumerator
ENABLED_BY_NATIVE
ENABLED_BY_TRACING
ENABLED_BY_SAMPLING
Definition at line 21 of file tracing-category-observer.h.
            {
    ENABLED_BY_NATIVE = 1 << 0,
    ENABLED_BY_TRACING = 1 << 1,
    ENABLED_BY_SAMPLING = 1 << 2,
  };
Member Function Documentation
OnTraceDisabled()
void v8::tracing::TracingCategoryObserver::OnTraceDisabled () [final], [virtual]
Implements v8::TracingController::TraceStateObserver.
Definition at line 89 of file tracing-category-observer.cc.
                                              {
#endif
  i::TracingFlags::runtime_stats.fetch_and(
      ~(ENABLED_BY_TRACING | ENABLED_BY_SAMPLING), std::memory_order_relaxed);
  i::TracingFlags::gc.fetch_and(~ENABLED_BY_TRACING, std::memory_order_relaxed);
  i::TracingFlags::gc_stats.fetch_and(~ENABLED_BY_TRACING,
                                      std::memory_order_relaxed);
  i::TracingFlags::ic_stats.fetch_and(~ENABLED_BY_TRACING,
                                      std::memory_order_relaxed);
}
References ENABLED_BY_SAMPLING, ENABLED_BY_TRACING, v8::internal::TracingFlags::gc, v8::internal::TracingFlags::gc_stats, v8::internal::TracingFlags::ic_stats, and v8::internal::TracingFlags::runtime_stats.
OnTraceEnabled()
void v8::tracing::TracingCategoryObserver::OnTraceEnabled () [final], [virtual]
Implements v8::TracingController::TraceStateObserver.
Definition at line 44 of file tracing-category-observer.cc.
                                             {
#endif
  bool enabled = false;
  TRACE_EVENT_CATEGORY_GROUP_ENABLED(
      TRACE_DISABLED_BY_DEFAULT("v8.runtime_stats"), &enabled);
  if (enabled) {
    i::TracingFlags::runtime_stats.fetch_or(ENABLED_BY_TRACING,
                                            std::memory_order_relaxed);
  }
  TRACE_EVENT_CATEGORY_GROUP_ENABLED(
      TRACE_DISABLED_BY_DEFAULT("v8.runtime_stats_sampling"), &enabled);
  if (enabled) {
    i::TracingFlags::runtime_stats.fetch_or(ENABLED_BY_SAMPLING,
                                            std::memory_order_relaxed);
  }
  TRACE_EVENT_CATEGORY_GROUP_ENABLED(TRACE_DISABLED_BY_DEFAULT("v8.gc"),
                                     &enabled);
  if (enabled) {
    i::TracingFlags::gc.fetch_or(ENABLED_BY_TRACING, std::memory_order_relaxed);
  }
  TRACE_EVENT_CATEGORY_GROUP_ENABLED(TRACE_DISABLED_BY_DEFAULT("v8.gc_stats"),
                                     &enabled);
  if (enabled) {
    i::TracingFlags::gc_stats.fetch_or(ENABLED_BY_TRACING,
                                       std::memory_order_relaxed);
  }
  TRACE_EVENT_CATEGORY_GROUP_ENABLED(TRACE_DISABLED_BY_DEFAULT("v8.ic_stats"),
                                     &enabled);
  if (enabled) {
    i::TracingFlags::ic_stats.fetch_or(ENABLED_BY_TRACING,
                                       std::memory_order_relaxed);
  }
  TRACE_EVENT_CATEGORY_GROUP_ENABLED(TRACE_DISABLED_BY_DEFAULT("v8.zone_stats"),
                                     &enabled);
  if (enabled) {
    i::TracingFlags::zone_stats.fetch_or(ENABLED_BY_TRACING,
                                         std::memory_order_relaxed);
  }
}
References ENABLED_BY_SAMPLING, ENABLED_BY_TRACING, v8::internal::TracingFlags::gc, v8::internal::TracingFlags::gc_stats, v8::internal::TracingFlags::ic_stats, v8::internal::TracingFlags::runtime_stats, TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT_CATEGORY_GROUP_ENABLED, and v8::internal::TracingFlags::zone_stats.
SetUp()
void v8::tracing::TracingCategoryObserver::SetUp () [static]
Definition at line 18 of file tracing-category-observer.cc.
                                    {
  TracingCategoryObserver::instance_ = new TracingCategoryObserver();
#if defined(V8_USE_PERFETTO)
  TrackEvent::AddSessionObserver(instance_);
  // Fire the observer if tracing is already in progress.
  if (TrackEvent::IsEnabled()) instance_->OnStart({});
#else
  i::V8::GetCurrentPlatform()->GetTracingController()->AddTraceStateObserver(
      TracingCategoryObserver::instance_);
#endif
}
References v8::TracingController::AddTraceStateObserver(), v8::internal::V8::GetCurrentPlatform(), v8::Platform::GetTracingController(), and instance_.
Referenced by v8::internal::V8::InitializePlatform().
TearDown()
void v8::tracing::TracingCategoryObserver::TearDown () [static]
Definition at line 30 of file tracing-category-observer.cc.
                                       {
#if defined(V8_USE_PERFETTO)
  TrackEvent::RemoveSessionObserver(TracingCategoryObserver::instance_);
#else
  i::V8::GetCurrentPlatform()->GetTracingController()->RemoveTraceStateObserver(
      TracingCategoryObserver::instance_);
#endif
  delete TracingCategoryObserver::instance_;
}
References v8::internal::V8::GetCurrentPlatform(), v8::Platform::GetTracingController(), instance_, and v8::TracingController::RemoveTraceStateObserver().
Referenced by v8::internal::V8::DisposePlatform().
Member Data Documentation
instance_
TracingCategoryObserver * v8::tracing::TracingCategoryObserver::instance_ = nullptr [static], [private]
Definition at line 41 of file tracing-category-observer.h.
Referenced by SetUp(), and TearDown().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/tracing/tracing-category-observer.h
/mnt/V8SourceCode/src/tracing/tracing-category-observer.cc