v8::internal::TimerEventScope< TimerEvent > Class Template Reference
#include <log.h>
Public Member Functions
TimerEventScope (Isolate *isolate)
~TimerEventScope ()
Private Member Functions
void LogTimerEvent (v8::LogEventStatus se)
Private Attributes
Isolate * isolate_
Detailed Description
template<class TimerEvent>
class v8::internal::TimerEventScope< TimerEvent >
Definition at line 413 of file log.h.
Constructor & Destructor Documentation
TimerEventScope()
template<class TimerEvent >
v8::internal::TimerEventScope< TimerEvent >::TimerEventScope (Isolate * isolate) [inline], [explicit]
Definition at line 415 of file log.h.
                                             : isolate_(isolate) {
    LogTimerEvent(v8::LogEventStatus::kStart);
  }
References v8::kStart, and v8::internal::anonymous_namespace{builtins-console.cc}::LogTimerEvent().
 TimerEventScope()
template<class TimerEvent >
v8::internal::TimerEventScope< TimerEvent >::~TimerEventScope () [inline]
Definition at line 419 of file log.h.
{ LogTimerEvent(v8::LogEventStatus::kEnd); }
References v8_inspector::anonymous_namespace{value-mirror.cc}::kEnd, and v8::internal::anonymous_namespace{builtins-console.cc}::LogTimerEvent().
Member Function Documentation
LogTimerEvent()
template<class TimerEvent >
void v8::internal::TimerEventScope< TimerEvent >::LogTimerEvent (v8::LogEventStatus se) [private]
Definition at line 32 of file log-inl.h.
                                                                   {
  V8FileLogger::CallEventLogger(isolate_, TimerEvent::name(), se,
                                TimerEvent::expose_to_api());
}
References v8::internal::V8FileLogger::CallEventLogger(), and name.
Member Data Documentation
isolate_
template<class TimerEvent >
Isolate* v8::internal::TimerEventScope< TimerEvent >::isolate_ [private]
Definition at line 423 of file log.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/logging/log.h
/mnt/V8SourceCode/src/logging/log-inl.h