v8::internal::CodeDataSource Class Reference
#include <code-data-source.h>
Public Member Functions
void OnSetup (const SetupArgs &) override
void OnStart (const StartArgs &) override
void OnStop (const StopArgs &) override
const perfetto::protos::gen::V8Config & config () const
Static Public Member Functions
static void Register ()
Private Types
using Base = DataSource< CodeDataSource, CodeDataSourceTraits >
Private Attributes
perfetto::protos::gen::V8Config config_
Detailed Description
Definition at line 41 of file code-data-source.h.
Member Typedef Documentation
Base
using v8::internal::CodeDataSource::Base = DataSource<CodeDataSource, CodeDataSourceTraits> [private]
Definition at line 53 of file code-data-source.h.
Member Function Documentation
config()
const perfetto::protos::gen::V8Config& v8::internal::CodeDataSource::config () const [inline]
Definition at line 50 of file code-data-source.h.
{ return config_; }
References config_.
OnSetup()
void v8::internal::CodeDataSource::OnSetup (const SetupArgs & args) [override]
Definition at line 283 of file code-data-source.cc.
                                                  {
  config_.ParseFromString(args.config->v8_config_raw());
}
References v8::base::args, and config_.
OnStart()
void v8::internal::CodeDataSource::OnStart (const StartArgs &) [override]
Definition at line 287 of file code-data-source.cc.
                                             {
  PerfettoLogger::OnCodeDataSourceStart();
}
References v8::internal::PerfettoLogger::OnCodeDataSourceStart().
OnStop()
void v8::internal::CodeDataSource::OnStop (const StopArgs &) [override]
Definition at line 291 of file code-data-source.cc.
                                           {
  PerfettoLogger::OnCodeDataSourceStop();
}
References v8::internal::PerfettoLogger::OnCodeDataSourceStop().
Register()
void v8::internal::CodeDataSource::Register () [static]
Definition at line 277 of file code-data-source.cc.
                              {
  perfetto::DataSourceDescriptor desc;
  desc.set_name("dev.v8.code");
  Base::Register(desc);
}
References v8::internal::ETWJITInterface::Register().
Referenced by v8::internal::V8::Initialize().
Member Data Documentation
config_
perfetto::protos::gen::V8Config v8::internal::CodeDataSource::config_ [private]
Definition at line 55 of file code-data-source.h.
Referenced by config(), and OnSetup().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/tracing/code-data-source.h
/mnt/V8SourceCode/src/tracing/code-data-source.cc