v8::internal::FlatStringReader Class Reference
#include <string.h>
Public Member Functions
FlatStringReader (Isolate *isolate, DirectHandle< String > str)
void PostGarbageCollection () override
base::uc32 Get (uint32_t index) const
template<typename Char >
Char Get (uint32_t index) const
uint32_t length () const
Private Attributes
DirectHandle< String > str_
bool is_one_byte_
uint32_t const length_
const void * start_
Additional Inherited Members
Detailed Description
Definition at line 1315 of file string.h.
Constructor & Destructor Documentation
FlatStringReader()
v8::internal::FlatStringReader::FlatStringReader (Isolate * isolate, DirectHandle< String > str)
Definition at line 2068 of file string.cc.
    : Relocatable(isolate), str_(str), length_(str->length()) {
#if DEBUG
  // Check that this constructor is called only from the main thread.
  DCHECK_EQ(ThreadId::Current(), isolate->thread_id());
#endif
  PostGarbageCollection();
}
References v8::internal::ThreadId::Current(), DCHECK_EQ, PostGarbageCollection(), and v8::internal::Isolate::thread_id().
Member Function Documentation
Get() [1/2]
base::uc32 v8::internal::FlatStringReader::Get (uint32_t index) const [inline]
Definition at line 539 of file string-inl.h.
                                                   {
  if (is_one_byte_) {
    return Get<uint8_t>(index);
  } else {
    return Get<base::uc16>(index);
  }
}
References v8::internal::index, and is_one_byte_.
Referenced by v8::internal::JSRegExp::FlagsFromString(), and v8::internal::anonymous_namespace{call-site-info.cc}::StringEndsWithMethodName().
Get() [2/2]
template<typename Char >
Char v8::internal::FlatStringReader::Get (uint32_t index) const [inline]
Definition at line 548 of file string-inl.h.
                                               {
  DCHECK_EQ(is_one_byte_, sizeof(Char) == 1);
  DCHECK_LT(index, length_);
  if (sizeof(Char) == 1) {
    return static_cast<Char>(static_cast<const uint8_t*>(start_)[index]);
  } else {
    return static_cast<Char>(static_cast<const base::uc16*>(start_)[index]);
  }
}
References DCHECK_EQ, DCHECK_LT, v8::internal::index, is_one_byte_, length_, and start_.
length()
uint32_t v8::internal::FlatStringReader::length () const [inline]
Definition at line 1322 of file string.h.
{ return length_; }
References v8::internal::String::length_.
Referenced by v8::internal::anonymous_namespace{call-site-info.cc}::StringEndsWithMethodName().
PostGarbageCollection()
void v8::internal::FlatStringReader::PostGarbageCollection () [override], [virtual]
Reimplemented from v8::internal::Relocatable.
Definition at line 2077 of file string.cc.
                                             {
  DCHECK(str_->IsFlat());
  DisallowGarbageCollection no_gc;
  // This does not actually prevent the vector from being relocated later.
  String::FlatContent content = str_->GetFlatContent(no_gc);
  DCHECK(content.IsFlat());
  is_one_byte_ = content.IsOneByte();
  if (is_one_byte_) {
    start_ = content.ToOneByteVector().begin();
  } else {
    start_ = content.ToUC16Vector().begin();
  }
}
References v8::base::Vector< T >::begin(), v8::internal::DCHECK(), is_one_byte_, v8::internal::String::FlatContent::IsFlat(), v8::internal::String::FlatContent::IsOneByte(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, start_, str_, v8::internal::String::FlatContent::ToOneByteVector(), and v8::internal::String::FlatContent::ToUC16Vector().
Referenced by FlatStringReader().
Member Data Documentation
is_one_byte_
bool v8::internal::FlatStringReader::is_one_byte_ [private]
Definition at line 1326 of file string.h.
Referenced by Get(), and PostGarbageCollection().
length_
uint32_t const v8::internal::FlatStringReader::length_ [private]
Definition at line 1327 of file string.h.
Referenced by Get().
start_
const void* v8::internal::FlatStringReader::start_ [private]
Definition at line 1328 of file string.h.
Referenced by Get(), and PostGarbageCollection().
str_
DirectHandle<String> v8::internal::FlatStringReader::str_ [private]
Definition at line 1325 of file string.h.
Referenced by PostGarbageCollection().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/string.h
/mnt/V8SourceCode/src/objects/string-inl.h
/mnt/V8SourceCode/src/objects/string.cc