v8::internal::maglev::ConstructWithSpread Class Reference
#include <maglev-ir.h>
Public Member Functions
ConstructWithSpread (uint64_t bitfield, compiler::FeedbackSource feedback, ValueNode *function, ValueNode *new_target, ValueNode *context)
Input & function ()
const Input & function () const
Input & new_target ()
const Input & new_target () const
Input & context ()
const Input & context () const
int num_args () const
int num_args_no_spread () const
Input & arg (int i)
void set_arg (int i, ValueNode *node)
Input & spread ()
auto args_no_spread ()
compiler::FeedbackSource feedback () const
void VerifyInputs (MaglevGraphLabeller *graph_labeller) const
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr int kFunctionIndex = 0
static constexpr int kNewTargetIndex = 1
static constexpr int kContextIndex = 2
static constexpr int kFixedInputCount = 3
static constexpr OpProperties kProperties = OpProperties::JSCall()
Private Types
using Base = ValueNodeT< ConstructWithSpread >
Private Attributes
const compiler::FeedbackSource feedback_
Additional Inherited Members
Detailed Description
Definition at line 10679 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::ConstructWithSpread::Base = ValueNodeT<ConstructWithSpread> [private]
Definition at line 10680 of file maglev-ir.h.
Constructor & Destructor Documentation
ConstructWithSpread()
v8::internal::maglev::ConstructWithSpread::ConstructWithSpread (uint64_t bitfield, compiler::FeedbackSource feedback, ValueNode * function, ValueNode * new_target, ValueNode * context) [inline]
Definition at line 10691 of file maglev-ir.h.
      : Base(bitfield), feedback_(feedback) {
    set_input(kFunctionIndex, function);
    set_input(kNewTargetIndex, new_target);
    set_input(kContextIndex, context);
  }
Member Function Documentation
arg()
Input& v8::internal::maglev::ConstructWithSpread::arg (int i) [inline]
Definition at line 10713 of file maglev-ir.h.
{ return input(i + kFixedInputCount); }
args_no_spread()
auto v8::internal::maglev::ConstructWithSpread::args_no_spread () [inline]
Definition at line 10721 of file maglev-ir.h.
                        {
    return base::make_iterator_range(
        std::make_reverse_iterator(&arg(-1)),
        std::make_reverse_iterator(&arg(num_args_no_spread() - 1)));
  }
References v8::base::make_iterator_range().
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
context() [1/2]
Input& v8::internal::maglev::ConstructWithSpread::context () [inline]
Definition at line 10706 of file maglev-ir.h.
{ return input(kContextIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
context() [2/2]
const Input& v8::internal::maglev::ConstructWithSpread::context () const [inline]
Definition at line 10707 of file maglev-ir.h.
{ return input(kContextIndex); }
feedback()
compiler::FeedbackSource v8::internal::maglev::ConstructWithSpread::feedback () const [inline]
Definition at line 10726 of file maglev-ir.h.
{ return feedback_; }
function() [1/2]
Input& v8::internal::maglev::ConstructWithSpread::function () [inline]
Definition at line 10702 of file maglev-ir.h.
{ return input(kFunctionIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
function() [2/2]
const Input& v8::internal::maglev::ConstructWithSpread::function () const [inline]
Definition at line 10703 of file maglev-ir.h.
{ return input(kFunctionIndex); }
GenerateCode()
void v8::internal::maglev::ConstructWithSpread::GenerateCode (MaglevAssembler * , const ProcessingState &)
MaxCallStackArgs()
int v8::internal::maglev::ConstructWithSpread::MaxCallStackArgs () const
new_target() [1/2]
Input& v8::internal::maglev::ConstructWithSpread::new_target () [inline]
Definition at line 10704 of file maglev-ir.h.
{ return input(kNewTargetIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
new_target() [2/2]
const Input& v8::internal::maglev::ConstructWithSpread::new_target () const [inline]
Definition at line 10705 of file maglev-ir.h.
{ return input(kNewTargetIndex); }
num_args()
int v8::internal::maglev::ConstructWithSpread::num_args () const [inline]
Definition at line 10708 of file maglev-ir.h.
{ return input_count() - kFixedInputCount; }
References v8::internal::compiler::turboshaft::detail::input_count().
num_args_no_spread()
int v8::internal::maglev::ConstructWithSpread::num_args_no_spread () const [inline]
Definition at line 10709 of file maglev-ir.h.
                                 {
    DCHECK_GT(num_args(), 0);
    return num_args() - 1;
  }
References DCHECK_GT.
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::ConstructWithSpread::PrintParams (std::ostream & , MaglevGraphLabeller *) const [inline]
Definition at line 10735 of file maglev-ir.h.
{}
set_arg()
void v8::internal::maglev::ConstructWithSpread::set_arg (int i, ValueNode * node) [inline]
Definition at line 10714 of file maglev-ir.h.
                                       {
    set_input(i + kFixedInputCount, node);
  }
SetValueLocationConstraints()
void v8::internal::maglev::ConstructWithSpread::SetValueLocationConstraints ()
spread()
Input& v8::internal::maglev::ConstructWithSpread::spread () [inline]
Definition at line 10717 of file maglev-ir.h.
                  {
    // Spread is the last argument/input.
    return input(input_count() - 1);
  }
References v8::internal::compiler::turboshaft::detail::input_count().
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
VerifyInputs()
void v8::internal::maglev::ConstructWithSpread::VerifyInputs (MaglevGraphLabeller * graph_labeller) const
Definition at line 1037 of file maglev-ir.cc.
                                               {
  for (int i = 0; i < input_count(); i++) {
    CheckValueInputIs(this, i, ValueRepresentation::kTagged, graph_labeller);
  }
}
References v8::internal::maglev::CheckValueInputIs(), v8::internal::compiler::turboshaft::detail::input_count(), and v8::internal::maglev::kTagged.
Member Data Documentation
feedback_
const compiler::FeedbackSource v8::internal::maglev::ConstructWithSpread::feedback_ [private]
Definition at line 10738 of file maglev-ir.h.
kContextIndex
constexpr int v8::internal::maglev::ConstructWithSpread::kContextIndex = 2 [static], [constexpr]
Definition at line 10686 of file maglev-ir.h.
kFixedInputCount
constexpr int v8::internal::maglev::ConstructWithSpread::kFixedInputCount = 3 [static], [constexpr]
Definition at line 10687 of file maglev-ir.h.
kFunctionIndex
constexpr int v8::internal::maglev::ConstructWithSpread::kFunctionIndex = 0 [static], [constexpr]
Definition at line 10684 of file maglev-ir.h.
kNewTargetIndex
constexpr int v8::internal::maglev::ConstructWithSpread::kNewTargetIndex = 1 [static], [constexpr]
Definition at line 10685 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::ConstructWithSpread::kProperties = OpProperties::JSCall() [static], [constexpr]
Definition at line 10700 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc