v8::internal::Isolate Class Reference
#include <isolate.h>
Classes
class EnableRoAllocationForSnapshotScope
class EntryStackItem
class ExceptionScope
class PerIsolateThreadData
struct PromiseHandler
struct PromiseHookFields
class ThreadDataTable
Public Types
enum class ExceptionHandlerType { kJavaScriptHandler
, kExternalTryCatch
, kNone
 }
enum PrintStackMode { kPrintStackConcise
, kPrintStackVerbose
 }
enum CatchType {
NOT_CAUGHT
, CAUGHT_BY_JAVASCRIPT
, CAUGHT_BY_EXTERNAL
, CAUGHT_BY_PROMISE
,
CAUGHT_BY_ASYNC_AWAIT
 }
enum class KnownPrototype { kNone
, kObject
, kArray
, kString
 }
using HandleScopeType = HandleScope
Public Member Functions
Isolate (const Isolate &)=delete
Isolate & operator= (const Isolate &)=delete
void * operator new (size_t)=delete
void operator delete (void *)=delete
void SetUpFromReadOnlyArtifacts (ReadOnlyArtifacts *artifacts)
void set_read_only_heap (ReadOnlyHeap *ro_heap)
v8::PageAllocator * page_allocator () const
bool IsCurrent () const
void InitializeLoggingAndCounters ()
bool InitializeCounters ()
bool InitWithoutSnapshot ()
bool InitWithSnapshot (SnapshotData *startup_snapshot_data, SnapshotData *read_only_snapshot_data, SnapshotData *shared_heap_snapshot_data, bool can_rehash)
bool IsInUse ()
void ReleaseSharedPtrs ()
void ClearSerializerData ()
void UpdateLogObjectRelocation ()
void Enter ()
void Exit ()
PerIsolateThreadData * FindOrAllocatePerThreadDataForThisThread ()
PerIsolateThreadData * FindPerThreadDataForThisThread ()
PerIsolateThreadData * FindPerThreadDataForThread (ThreadId thread_id)
void DiscardPerThreadDataForThisThread ()
base::RecursiveMutex * break_access ()
base::Mutex * feedback_vector_access ()
base::Mutex * internalized_string_access ()
base::Mutex * full_transition_array_access ()
base::Mutex * shared_function_info_access ()
base::Mutex * map_updater_access ()
base::Mutex * boilerplate_migration_access ()
ReadOnlyArtifacts * read_only_artifacts () const
StringTable * string_table () const
StringForwardingTable * string_forwarding_table () const
SharedStructTypeRegistry * shared_struct_type_registry () const
Address get_address_from_id (IsolateAddressId id)
Tagged< Context > context () const
void set_context (Tagged< Context > context)
Tagged< Context > * context_address ()
Tagged< Context > topmost_script_having_context () const
void set_topmost_script_having_context (Tagged< Context > context)
void clear_topmost_script_having_context ()
Tagged< Context > * topmost_script_having_context_address ()
void set_thread_id (ThreadId id)
ThreadId thread_id () const
void InstallConditionalFeatures (DirectHandle< NativeContext > context)
bool IsSharedArrayBufferConstructorEnabled (DirectHandle< NativeContext > context)
bool IsWasmStringRefEnabled (DirectHandle< NativeContext > context)
bool IsWasmImportedStringsEnabled (DirectHandle< NativeContext > context)
bool IsWasmJSPIRequested (DirectHandle< NativeContext > context)
bool IsWasmJSPIEnabled (DirectHandle< NativeContext > context)
bool IsCompileHintsMagicEnabled (Handle< NativeContext > context)
v8::TryCatch * try_catch_handler ()
Tagged< Object > exception ()
void set_exception (Tagged< Object > exception_obj)
void clear_exception ()
void clear_internal_exception ()
bool has_exception ()
void clear_pending_message ()
Tagged< Object > pending_message ()
bool has_pending_message ()
void set_pending_message (Tagged< Object > message_obj)
ExceptionHandlerType TopExceptionHandlerType (Tagged< Object > exception)
bool is_catchable_by_javascript (Tagged< Object > exception)
bool is_catchable_by_wasm (Tagged< Object > exception)
bool is_execution_terminating ()
Address c_function ()
Address * c_entry_fp_address ()
Address * handler_address ()
Address * c_function_address ()
void RegisterDeserializerStarted ()
void RegisterDeserializerFinished ()
bool has_active_deserializer () const
Address js_entry_sp ()
Address * js_entry_sp_address ()
std::vector< MemoryRange > * GetCodePages () const
void SetCodePages (std::vector< MemoryRange > *new_code_pages)
Handle< JSGlobalObject > global_object ()
Handle< JSGlobalProxy > global_proxy ()
void FreeThreadResources ()
bool WalkCallStackAndPromiseTree (MaybeDirectHandle< JSPromise > rejected_promise, const std::function< void(PromiseHandler)> &callback)
void SetCaptureStackTraceForUncaughtExceptions (bool capture, int frame_limit, StackTrace::StackTraceOptions options)
bool get_capture_stack_trace_for_uncaught_exceptions () const
void SetAbortOnUncaughtExceptionCallback (v8::Isolate::AbortOnUncaughtExceptionCallback callback)
void PrintCurrentStackTrace (std::ostream &out, PrintCurrentStackTraceFilterCallback should_include_frame_callback=nullptr)
void PrintStack (StringStream *accumulator, PrintStackMode mode=kPrintStackVerbose)
void PrintStack (FILE *out, PrintStackMode mode=kPrintStackVerbose)
DirectHandle< String > StackTraceString ()
V8_NOINLINE void PushStackTraceAndDie (void *ptr1=nullptr, void *ptr2=nullptr, void *ptr3=nullptr, void *ptr4=nullptr, void *ptr5=nullptr, void *ptr6=nullptr)
V8_NOINLINE void PushParamsAndDie (void *ptr1=nullptr, void *ptr2=nullptr, void *ptr3=nullptr, void *ptr4=nullptr, void *ptr5=nullptr, void *ptr6=nullptr)
V8_NOINLINE void PushStackTraceAndContinue (void *ptr1=nullptr, void *ptr2=nullptr, void *ptr3=nullptr, void *ptr4=nullptr, void *ptr5=nullptr, void *ptr6=nullptr)
V8_NOINLINE void PushParamsAndContinue (void *ptr1=nullptr, void *ptr2=nullptr, void *ptr3=nullptr, void *ptr4=nullptr, void *ptr5=nullptr, void *ptr6=nullptr)
DirectHandle< StackTraceInfo > CaptureDetailedStackTrace (int limit, StackTrace::StackTraceOptions options)
MaybeDirectHandle< JSObject > CaptureAndSetErrorStack (DirectHandle< JSObject > error_object, FrameSkipMode mode, Handle< Object > caller)
Handle< StackTraceInfo > GetDetailedStackTrace (DirectHandle< JSReceiver > error_object)
Handle< FixedArray > GetSimpleStackTrace (DirectHandle< JSReceiver > error_object)
DirectHandle< String > CurrentScriptNameOrSourceURL ()
MaybeDirectHandle< Script > CurrentReferrerScript ()
bool GetStackTraceLimit (Isolate *isolate, int *result)
Address GetAbstractPC (int *line, int *column)
bool MayAccess (DirectHandle< NativeContext > accessing_context, DirectHandle< JSObject > receiver)
void SetFailedAccessCheckCallback (v8::FailedAccessCheckCallback callback)
V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > ReportFailedAccessCheck (DirectHandle< JSObject > receiver)
Tagged< Object > Throw (Tagged< Object > exception, MessageLocation *location=nullptr)
Tagged< Object > ThrowAt (DirectHandle< JSObject > exception, MessageLocation *location)
Tagged< Object > ThrowIllegalOperation ()
void FatalProcessOutOfHeapMemory (const char *location)
void set_console_delegate (debug::ConsoleDelegate *delegate)
debug::ConsoleDelegate * console_delegate ()
void set_async_event_delegate (debug::AsyncEventDelegate *delegate)
void OnAsyncFunctionSuspended (DirectHandle< JSPromise > promise, DirectHandle< JSPromise > parent)
void OnPromiseThen (DirectHandle< JSPromise > promise)
void OnPromiseBefore (DirectHandle< JSPromise > promise)
void OnPromiseAfter (DirectHandle< JSPromise > promise)
void OnStackTraceCaptured (DirectHandle< StackTraceInfo > stack_trace)
void OnTerminationDuringRunMicrotasks ()
Tagged< Object > ReThrow (Tagged< Object > exception)
Tagged< Object > ReThrow (Tagged< Object > exception, Tagged< Object > message)
Tagged< Object > UnwindAndFindHandler ()
CatchType PredictExceptionCatcher ()
void ReportPendingMessages (bool report=true)
bool ComputeLocation (MessageLocation *target)
bool ComputeLocationFromException (MessageLocation *target, DirectHandle< Object > exception)
bool ComputeLocationFromSimpleStackTrace (MessageLocation *target, DirectHandle< Object > exception)
bool ComputeLocationFromDetailedStackTrace (MessageLocation *target, DirectHandle< Object > exception)
Handle< JSMessageObject > CreateMessage (DirectHandle< Object > exception, MessageLocation *location)
DirectHandle< JSMessageObject > CreateMessageOrAbort (DirectHandle< Object > exception, MessageLocation *location)
Handle< JSMessageObject > CreateMessageFromException (DirectHandle< Object > exception)
Tagged< Object > StackOverflow ()
Tagged< Object > TerminateExecution ()
void CancelTerminateExecution ()
void RequestInterrupt (InterruptCallback callback, void *data)
void InvokeApiInterruptCallbacks ()
void RequestInvalidateNoProfilingProtector ()
void Iterate (RootVisitor *v)
void Iterate (RootVisitor *v, ThreadLocalTop *t)
char * Iterate (RootVisitor *v, char *t)
void IterateThread (ThreadVisitor *v, char *t)
Handle< NativeContext > native_context ()
Tagged< NativeContext > raw_native_context ()
DirectHandle< NativeContext > GetIncumbentContext ()
DirectHandle< NativeContext > GetIncumbentContextSlow ()
void RegisterTryCatchHandler (v8::TryCatch *that)
void UnregisterTryCatchHandler (v8::TryCatch *that)
char * ArchiveThread (char *to)
char * RestoreThread (char *from)
void SetDetailedSourcePositionsForProfiling (bool value)
bool detailed_source_positions_for_profiling () const
Bootstrapper * bootstrapper ()
Counters * counters ()
const std::shared_ptr< Counters > & async_counters ()
const std::shared_ptr< metrics::Recorder > & metrics_recorder ()
TieringManager * tiering_manager ()
CompilationCache * compilation_cache ()
V8FileLogger * v8_file_logger () const
StackGuard * stack_guard ()
Heap * heap ()
const Heap * heap () const
ReadOnlyHeap * read_only_heap () const
const IsolateData * isolate_data () const
IsolateData * isolate_data ()
Address cage_base () const
Address code_cage_base () const
IsolateGroup * isolate_group () const
Address isolate_root () const
RootsTable & roots_table ()
const RootsTable & roots_table () const
base::AddressRegion root_register_addressable_region () const
Tagged< Object > root (RootIndex index) const
Handle< Object > root_handle (RootIndex index)
ExternalReferenceTable * external_reference_table ()
ExternalReferenceTable * external_reference_table_unsafe ()
Address * builtin_entry_table ()
Address * builtin_table ()
Address * builtin_tier0_table ()
bool IsBuiltinTableHandleLocation (Address *handle_location)
StubCache * load_stub_cache () const
StubCache * store_stub_cache () const
StubCache * define_own_stub_cache () const
Deoptimizer * GetAndClearCurrentDeoptimizer ()
void set_current_deoptimizer (Deoptimizer *deoptimizer)
bool deoptimizer_lazy_throw () const
void set_deoptimizer_lazy_throw (bool value)
void InitializeThreadLocal ()
ThreadLocalTop * thread_local_top ()
ThreadLocalTop const * thread_local_top () const
uint8_t error_message_param ()
MaterializedObjectStore * materialized_object_store () const
DescriptorLookupCache * descriptor_lookup_cache () const
HandleScopeData * handle_scope_data ()
HandleScopeImplementer * handle_scope_implementer () const
UnicodeCache * unicode_cache () const
InnerPointerToCodeCache * inner_pointer_to_code_cache ()
GlobalHandles * global_handles () const
TracedHandles * traced_handles ()
EternalHandles * eternal_handles () const
ThreadManager * thread_manager () const
bigint::Processor * bigint_processor ()
unibrow::Mapping< unibrow::Ecma262UnCanonicalize > * jsregexp_uncanonicalize ()
unibrow::Mapping< unibrow::CanonicalizationRange > * jsregexp_canonrange ()
unibrow::Mapping< unibrow::Ecma262Canonicalize > * regexp_macro_assembler_canonicalize ()
RuntimeState * runtime_state ()
Builtins * builtins ()
BuiltinsEffectsAnalyzer * builtins_effects_analyzer ()
void set_builtins_effects_analyzer (BuiltinsEffectsAnalyzer *builtins_effects_analyzer)
RegExpStack * regexp_stack () const
int32_t * regexp_static_result_offsets_vector () const
void set_regexp_static_result_offsets_vector (int32_t *value)
Address address_of_regexp_static_result_offsets_vector () const
std::unordered_set< int32_t * > & active_dynamic_regexp_result_vectors ()
std::vector< int > * regexp_indices ()
size_t total_regexp_code_generated () const
void IncreaseTotalRegexpCodeGenerated (DirectHandle< HeapObject > code)
Debug * debug () const
bool is_profiling () const
void SetIsProfiling (bool enabled)
bool should_check_side_effects () const
DebugInfo::ExecutionMode debug_execution_mode () const
void set_debug_execution_mode (DebugInfo::ExecutionMode debug_execution_mode)
Logger * logger () const
v8::internal::Factory * factory ()
void SetData (uint32_t slot, void *data)
void * GetData (uint32_t slot) const
bool serializer_enabled () const
void enable_serializer ()
bool snapshot_available () const
bool IsDead () const
void SignalFatalError ()
bool use_optimizer ()
bool initialized_from_snapshot ()
bool NeedsSourcePositions () const
bool IsLoggingCodeCreation () const
bool InFastCCall () const
bool AllowsCodeCompaction () const
bool NeedsDetailedOptimizedCodeLineInfo () const
bool is_best_effort_code_coverage () const
bool is_precise_count_code_coverage () const
bool is_precise_binary_code_coverage () const
bool is_block_count_code_coverage () const
bool is_block_binary_code_coverage () const
bool is_block_code_coverage () const
bool is_binary_code_coverage () const
bool is_count_code_coverage () const
void SetFeedbackVectorsForProfilingTools (Tagged< Object > value)
void MaybeInitializeVectorListFromHeap ()
double time_millis_since_init () const
DateCache * date_cache () const
void set_date_cache (DateCache *date_cache)
Tagged< Smi > date_cache_stamp () const
Tagged< Smi > GetDateCacheStampAndRecordUsage ()
void IncreaseDateCacheStampAndInvalidateProtector ()
KnownPrototype IsArrayOrObjectOrStringPrototype (Tagged< JSObject > object)
void UpdateNoElementsProtectorOnSetElement (DirectHandle< JSObject > object)
void UpdateNoElementsProtectorOnSetLength (DirectHandle< JSObject > object)
void UpdateProtectorsOnSetPrototype (DirectHandle< JSObject > object, DirectHandle< Object > new_prototype)
void UpdateNoElementsProtectorOnSetPrototype (DirectHandle< JSObject > object)
void UpdateTypedArraySpeciesLookupChainProtectorOnSetPrototype (DirectHandle< JSObject > object)
void UpdateNumberStringNotRegexpLikeProtectorOnSetPrototype (DirectHandle< JSObject > object)
void UpdateNoElementsProtectorOnNormalizeElements (DirectHandle< JSObject > object)
void UpdateStringWrapperToPrimitiveProtectorOnSetPrototype (DirectHandle< JSObject > object, DirectHandle< Object > new_prototype)
bool IsInitialArrayPrototype (Tagged< JSArray > array)
std::unique_ptr< PersistentHandles > NewPersistentHandles ()
PersistentHandlesList * persistent_handles_list () const
bool concurrent_recompilation_enabled ()
void IncreaseConcurrentOptimizationPriority (CodeKind kind, Tagged< SharedFunctionInfo > function)
OptimizingCompileDispatcher * optimizing_compile_dispatcher ()
OptimizingCompileDispatcher * SetOptimizingCompileDispatcherForTesting (OptimizingCompileDispatcher *dispatcher)
void AbortConcurrentOptimization (BlockingBehavior blocking_behavior)
int id () const
bool was_locker_ever_used () const
void set_was_locker_ever_used ()
std::shared_ptr< CompilationStatistics > GetTurboStatistics ()
CodeTracer * GetCodeTracer ()
void DumpAndResetStats ()
void DumpAndResetBuiltinsProfileData ()
uint64_t * stress_deopt_count_address ()
void set_force_slow_path (bool v)
bool force_slow_path () const
bool * force_slow_path_address ()
bool jitless () const
void set_stack_size (size_t v)
size_t stack_size ()
base::RandomNumberGenerator * random_number_generator ()
base::RandomNumberGenerator * fuzzer_rng ()
int GenerateIdentityHash (uint32_t mask)
int NextOptimizationId ()
unsigned NextModuleAsyncEvaluationOrdinal ()
void AddCallCompletedCallback (CallCompletedCallback callback)
void RemoveCallCompletedCallback (CallCompletedCallback callback)
void FireCallCompletedCallback (MicrotaskQueue *microtask_queue)
void AddBeforeCallEnteredCallback (BeforeCallEnteredCallback callback)
void RemoveBeforeCallEnteredCallback (BeforeCallEnteredCallback callback)
void FireBeforeCallEnteredCallback ()
void SetPromiseRejectCallback (PromiseRejectCallback callback)
void ReportPromiseReject (DirectHandle< JSPromise > promise, DirectHandle< Object > value, v8::PromiseRejectEvent event)
void SetTerminationOnExternalTryCatch ()
DirectHandle< Symbol > SymbolFor (RootIndex dictionary_index, Handle< String > name, bool private_symbol)
void SetUseCounterCallback (v8::Isolate::UseCounterCallback callback)
void CountUsage (v8::Isolate::UseCounterFeature feature)
void CountUsage (base::Vector< const v8::Isolate::UseCounterFeature > features)
int GetNextScriptId ()
uint32_t next_unique_sfi_id () const
uint32_t GetAndIncNextUniqueSfiId ()
bool HasContextPromiseHooks () const
Address promise_hook_flags_address ()
Address promise_hook_address ()
Address async_event_delegate_address ()
Address javascript_execution_assert_address ()
void IncrementJavascriptExecutionCounter ()
Address handle_scope_implementer_address ()
void SetReleaseCppHeapCallback (v8::Isolate::ReleaseCppHeapCallback callback)
void RunReleaseCppHeapCallback (std::unique_ptr< v8::CppHeap > cpp_heap)
void SetPromiseHook (PromiseHook hook)
void RunPromiseHook (PromiseHookType type, DirectHandle< JSPromise > promise, DirectHandle< Object > parent)
void RunAllPromiseHooks (PromiseHookType type, DirectHandle< JSPromise > promise, DirectHandle< Object > parent)
void UpdatePromiseHookProtector ()
void PromiseHookStateUpdated ()
void AddDetachedContext (DirectHandle< Context > context)
void CheckDetachedContextsAfterGC ()
void DetachGlobal (DirectHandle< Context > env)
std::vector< Tagged< Object > > * startup_object_cache ()
std::vector< Tagged< Object > > * shared_heap_object_cache ()
bool IsGeneratingEmbeddedBuiltins () const
BuiltinsConstantsTableBuilder * builtins_constants_table_builder () const
size_t HashIsolateForEmbeddedBlob ()
const uint8_t * embedded_blob_code () const
uint32_t embedded_blob_code_size () const
const uint8_t * embedded_blob_data () const
uint32_t embedded_blob_data_size () const
bool is_short_builtin_calls_enabled () const
void set_array_buffer_allocator (v8::ArrayBuffer::Allocator *allocator)
v8::ArrayBuffer::Allocator * array_buffer_allocator () const
void set_array_buffer_allocator_shared (std::shared_ptr< v8::ArrayBuffer::Allocator > allocator)
std::shared_ptr< v8::ArrayBuffer::Allocator > array_buffer_allocator_shared () const
size_t * array_buffer_max_size_address ()
FutexWaitListNode * futex_wait_list_node ()
CancelableTaskManager * cancelable_task_manager ()
const AstStringConstants * ast_string_constants () const
interpreter::Interpreter * interpreter () const
compiler::PerIsolateCompilerCache * compiler_cache () const
void set_compiler_utils (compiler::PerIsolateCompilerCache *cache, Zone *zone)
AccountingAllocator * allocator ()
LazyCompileDispatcher * lazy_compile_dispatcher () const
bool IsInCreationContext (Tagged< JSObject > object, uint32_t index)
void ClearKeptObjects ()
void SetHostImportModuleDynamicallyCallback (HostImportModuleDynamicallyCallback callback)
void SetHostImportModuleWithPhaseDynamicallyCallback (HostImportModuleWithPhaseDynamicallyCallback callback)
MaybeDirectHandle< JSPromise > RunHostImportModuleDynamicallyCallback (MaybeDirectHandle< Script > maybe_referrer, Handle< Object > specifier, ModuleImportPhase phase, MaybeDirectHandle< Object > maybe_import_options_argument)
void SetHostInitializeImportMetaObjectCallback (HostInitializeImportMetaObjectCallback callback)
MaybeHandle< JSObject > RunHostInitializeImportMetaObjectCallback (DirectHandle< SourceTextModule > module)
void SetHostCreateShadowRealmContextCallback (HostCreateShadowRealmContextCallback callback)
MaybeDirectHandle< NativeContext > RunHostCreateShadowRealmContextCallback ()
bool IsJSApiWrapperNativeError (DirectHandle< JSReceiver > obj)
void RegisterEmbeddedFileWriter (EmbeddedFileWriterInterface *writer)
int LookupOrAddExternallyCompiledFilename (const char *filename)
const char * GetExternallyCompiledFilename (int index) const
int GetExternallyCompiledFilenameCount () const
void PrepareBuiltinSourcePositionMap ()
void SetPrepareStackTraceCallback (PrepareStackTraceCallback callback)
MaybeDirectHandle< Object > RunPrepareStackTraceCallback (DirectHandle< NativeContext >, DirectHandle< JSObject > Error, DirectHandle< JSArray > sites)
bool HasPrepareStackTraceCallback () const
void SetAddCrashKeyCallback (AddCrashKeyCallback callback)
void AddCrashKey (CrashKeyId id, const std::string &value)
bool interpreted_frames_native_stack () const
void SetIsLoading (bool is_loading)
void set_code_coverage_mode (debug::CoverageMode coverage_mode)
debug::CoverageMode code_coverage_mode () const
void SetPriority (v8::Isolate::Priority priority)
v8::Isolate::Priority priority ()
bool is_backgrounded ()
bool EfficiencyModeEnabled ()
bool EfficiencyModeEnabledForTiering ()
bool BatterySaverModeEnabled ()
bool MemorySaverModeEnabled ()
PRINTF_FORMAT (2, 3) void PrintWithTimestamp(const char *format
void set_allow_atomics_wait (bool set)
bool allow_atomics_wait ()
bool flush_denormals () const
void RegisterManagedPtrDestructor (ManagedPtrDestructor *finalizer)
void UnregisterManagedPtrDestructor (ManagedPtrDestructor *finalizer)
size_t elements_deletion_counter ()
void set_elements_deletion_counter (size_t value)
const v8::Context::BackupIncumbentScope * top_backup_incumbent_scope () const
void set_top_backup_incumbent_scope (const v8::Context::BackupIncumbentScope *top_backup_incumbent_scope)
void SetIdle (bool is_idle)
void CollectSourcePositionsForAllBytecodeArrays ()
void AddCodeMemoryChunk (MutablePageMetadata *chunk)
void RemoveCodeMemoryChunk (MutablePageMetadata *chunk)
void AddCodeRange (Address begin, size_t length_in_bytes)
bool RequiresCodeRange () const
v8::metrics::Recorder::ContextId GetOrRegisterRecorderContextId (DirectHandle< NativeContext > context)
MaybeLocal< v8::Context > GetContextFromRecorderContextId (v8::metrics::Recorder::ContextId id)
void UpdateLongTaskStats ()
v8::metrics::LongTaskStats * GetCurrentLongTaskStats ()
LocalIsolate * main_thread_local_isolate ()
Isolate * AsIsolate ()
LocalIsolate * AsLocalIsolate ()
Isolate * GetMainThreadIsolateUnsafe ()
LocalHeap * main_thread_local_heap ()
LocalHeap * CurrentLocalHeap ()
Address continuation_preserved_embedder_data_address ()
bool is_shared_space_isolate () const
Isolate * shared_space_isolate () const
bool has_shared_space () const
GlobalSafepoint * global_safepoint () const
bool owns_shareable_data ()
bool log_object_relocation () const
bool OwnsStringTables () const
bool IsOnCentralStack ()
void LocalsBlockListCacheRehash ()
void LocalsBlockListCacheSet (DirectHandle< ScopeInfo > scope_info, DirectHandle< ScopeInfo > outer_scope_info, DirectHandle< StringSet > locals_blocklist)
Tagged< Object > LocalsBlockListCacheGet (DirectHandle< ScopeInfo > scope_info)
void VerifyStaticRoots ()
bool enable_ro_allocation_for_snapshot () const
void set_battery_saver_mode_enabled (bool battery_saver_mode_enabled)
void set_memory_saver_mode_enabled (bool memory_saver_mode_enabled)
std::list< std::unique_ptr< detail::WaiterQueueNode > > & async_waiter_queue_nodes ()
void ReportExceptionFunctionCallback (DirectHandle< JSReceiver > receiver, DirectHandle< FunctionTemplateInfo > function, v8::ExceptionContext callback_kind)
void ReportExceptionPropertyCallback (DirectHandle< JSReceiver > holder, DirectHandle< Name > name, v8::ExceptionContext callback_kind)
void SetExceptionPropagationCallback (ExceptionPropagationCallback callback)
bool IsFrozen () const
void Freeze (bool is_frozen)
std::shared_ptr< v8::TaskRunner > task_runner () const
void PrintNumberStringCacheStats (const char *comment, bool final_summary)
Static Public Member Functions
static void InitializeOncePerProcess ()
static Isolate * New ()
static Isolate * New (IsolateGroup *isolate_group)
static void Deinitialize (Isolate *isolate)
static void Free (Isolate *isolate)
static void Delete (Isolate *isolate)
static PerIsolateThreadData * CurrentPerIsolateThreadData ()
static Isolate * Current ()
static void SetCurrent (Isolate *isolate)
static Address c_entry_fp (ThreadLocalTop *thread)
static Address handler (ThreadLocalTop *thread)
static uint32_t c_entry_fp_offset ()
static int ArchiveSpacePerThread ()
static Isolate * FromHeap (const Heap *heap)
constexpr static size_t isolate_root_bias ()
static Isolate * FromRootAddress (Address isolate_root)
static constexpr uint32_t thread_in_wasm_flag_address_offset ()
constexpr static uint32_t context_offset ()
constexpr static uint32_t central_stack_sp_offset ()
constexpr static uint32_t central_stack_limit_offset ()
static uint32_t error_message_param_offset ()
static std::string GetTurboCfgFileName (Isolate *isolate)
static const uint8_t * CurrentEmbeddedBlobCode ()
static uint32_t CurrentEmbeddedBlobCodeSize ()
static const uint8_t * CurrentEmbeddedBlobData ()
static uint32_t CurrentEmbeddedBlobDataSize ()
static bool CurrentEmbeddedBlobIsBinaryEmbedded ()
static base::AddressRegion GetShortBuiltinsCallRegion ()
static Address load_from_stack_count_address (const char *function_name)
static Address store_to_stack_count_address (const char *function_name)
static void IterateRegistersAndStackOfSimulator (::heap::base::StackVisitor *visitor)
Static Public Attributes
static const int kUC16AlphabetSize = 256
static const int kBMMaxShift = 250
static const int kJSRegexpStaticOffsetsVectorSize = 128
Private Types
using InterruptEntry = std::pair< InterruptCallback, void * >
Private Member Functions
Isolate (IsolateGroup *isolate_group)
~Isolate ()
bool Init (SnapshotData *startup_snapshot_data, SnapshotData *read_only_snapshot_data, SnapshotData *shared_heap_snapshot_data, bool can_rehash)
void CheckIsolateLayout ()
void InitializeCodeRanges ()
void AddCodeMemoryRange (MemoryRange range)
Isolate * ForSandbox ()
void FireCallCompletedCallbackInternal (MicrotaskQueue *microtask_queue)
void Deinit ()
void FillCache ()
bool PropagateExceptionToExternalTryCatch (ExceptionHandlerType top_handler)
void NotifyExceptionPropagationCallback ()
bool HasIsolatePromiseHooks () const
bool HasAsyncEventDelegate () const
void AddCrashKeysForIsolateAndHeapPointers ()
bool IsOnCentralStack (Address addr)
MaybeDirectHandle< FixedArray > GetImportAttributesFromArgument (MaybeDirectHandle< Object > maybe_import_options_argument)
void InitializeNextUniqueSfiId (uint32_t id)
void InitializeDefaultEmbeddedBlob ()
void CreateAndSetEmbeddedBlob ()
void InitializeIsShortBuiltinCallsEnabled ()
void MaybeRemapEmbeddedBuiltinsIntoCodeRange ()
void TearDownEmbeddedBlob ()
void SetEmbeddedBlob (const uint8_t *code, uint32_t code_size, const uint8_t *data, uint32_t data_size)
void ClearEmbeddedBlob ()
void InitializeBuiltinJSDispatchTable ()
void * operator new (size_t, void *ptr)
Static Private Member Functions
static Isolate * Allocate (IsolateGroup *isolate_group)
static void RemoveContextIdCallback (const v8::WeakCallbackInfo< void > &data)
static void SetIsolateThreadLocals (Isolate *isolate, PerIsolateThreadData *data)
Private Attributes
IsolateData isolate_data_
bool is_shared_space_isolate_ {false}
IsolateGroup * isolate_group_
Heap heap_
ReadOnlyHeap * read_only_heap_ = nullptr
std::unique_ptr< StringTable > string_table_
std::unique_ptr< StringForwardingTable > string_forwarding_table_
const int id_
std::atomic< EntryStackItem * > entry_stack_ = nullptr
int stack_trace_nesting_level_ = 0
std::atomic< bool > was_locker_ever_used_ {false}
StringStream * incomplete_message_ = nullptr
Address isolate_addresses_ [kIsolateAddressCount+1] = {}
Bootstrapper * bootstrapper_ = nullptr
TieringManager * tiering_manager_ = nullptr
CompilationCache * compilation_cache_ = nullptr
std::shared_ptr< Counters > async_counters_
base::RecursiveMutex break_access_
base::Mutex feedback_vector_access_
base::Mutex internalized_string_access_
base::Mutex full_transition_array_access_
base::Mutex shared_function_info_access_
base::Mutex map_updater_access_
base::Mutex boilerplate_migration_access_
V8FileLogger * v8_file_logger_ = nullptr
StubCache * load_stub_cache_ = nullptr
StubCache * store_stub_cache_ = nullptr
StubCache * define_own_stub_cache_ = nullptr
Deoptimizer * current_deoptimizer_ = nullptr
bool deoptimizer_lazy_throw_ = false
MaterializedObjectStore * materialized_object_store_ = nullptr
bool capture_stack_trace_for_uncaught_exceptions_ = false
int stack_trace_for_uncaught_exceptions_frame_limit_ = 0
StackTrace::StackTraceOptions stack_trace_for_uncaught_exceptions_options_
DescriptorLookupCache * descriptor_lookup_cache_ = nullptr
HandleScopeImplementer * handle_scope_implementer_ = nullptr
UnicodeCache * unicode_cache_ = nullptr
AccountingAllocator * allocator_ = nullptr
InnerPointerToCodeCache * inner_pointer_to_code_cache_ = nullptr
GlobalHandles * global_handles_ = nullptr
TracedHandles traced_handles_
EternalHandles * eternal_handles_ = nullptr
ThreadManager * thread_manager_ = nullptr
bigint::Processor * bigint_processor_ = nullptr
RuntimeState runtime_state_
Builtins builtins_
BuiltinsEffectsAnalyzer * builtins_effects_analyzer_ = nullptr
SetupIsolateDelegate * setup_delegate_ = nullptr
unibrow::Mapping< unibrow::Ecma262UnCanonicalize > jsregexp_uncanonicalize_
unibrow::Mapping< unibrow::CanonicalizationRange > jsregexp_canonrange_
unibrow::Mapping< unibrow::Ecma262Canonicalize > regexp_macro_assembler_canonicalize_
RegExpStack * regexp_stack_ = nullptr
std::vector< int > regexp_indices_
std::unordered_set< int32_t * > active_dynamic_regexp_result_vectors_
DateCache * date_cache_ = nullptr
base::RandomNumberGenerator * random_number_generator_ = nullptr
base::RandomNumberGenerator * fuzzer_rng_ = nullptr
v8::Isolate::ReleaseCppHeapCallback release_cpp_heap_callback_ = nullptr
PromiseHook promise_hook_ = nullptr
HostImportModuleDynamicallyCallback host_import_module_dynamically_callback_
HostImportModuleWithPhaseDynamicallyCallback host_import_module_with_phase_dynamically_callback_ = nullptr
std::atomic< debug::CoverageMode > code_coverage_mode_
std::atomic< bool > battery_saver_mode_enabled_ = false
std::atomic< bool > memory_saver_mode_enabled_ = false
HostInitializeImportMetaObjectCallback host_initialize_import_meta_object_callback_ = nullptr
HostCreateShadowRealmContextCallback host_create_shadow_realm_context_callback_ = nullptr
bool serializer_enabled_ = false
bool has_fatal_error_ = false
bool initialized_from_snapshot_ = false
bool is_short_builtin_calls_enabled_ = false
std::atomic< v8::Isolate::Priority > priority_
bool owns_shareable_data_ = true
bool log_object_relocation_ = false
double time_millis_at_init_ = 0
Debug * debug_ = nullptr
Logger * logger_ = nullptr
const AstStringConstants * ast_string_constants_ = nullptr
interpreter::Interpreter * interpreter_ = nullptr
compiler::PerIsolateCompilerCache * compiler_cache_ = nullptr
Zone * compiler_zone_ = nullptr
std::unique_ptr< LazyCompileDispatcher > lazy_compile_dispatcher_
std::queue< InterruptEntry > api_interrupts_queue_
bool detailed_source_positions_for_profiling_
bool preprocessing_exception_ = false
OptimizingCompileDispatcher * optimizing_compile_dispatcher_ = nullptr
std::unique_ptr< PersistentHandlesList > persistent_handles_list_
uint64_t stress_deopt_count_ = 0
bool force_slow_path_ = false
bool enable_ro_allocation_for_snapshot_ = false
bool initialized_ = false
bool jitless_ = false
std::atomic< int > next_optimization_id_ = 0
std::atomic< uint32_t > next_unique_sfi_id_
unsigned next_module_async_evaluation_ordinal_
std::vector< BeforeCallEnteredCallback > before_call_entered_callbacks_
std::vector< CallCompletedCallback > call_completed_callbacks_
v8::Isolate::UseCounterCallback use_counter_callback_ = nullptr
std::shared_ptr< CompilationStatistics > turbo_statistics_
std::shared_ptr< metrics::Recorder > metrics_recorder_
uintptr_t last_recorder_context_id_ = 0
std::unordered_map< uintptr_t, v8::Global< v8::Context > > recorder_context_id_map_
size_t last_long_task_stats_counter_ = 0
v8::metrics::LongTaskStats long_task_stats_
std::vector< Tagged< Object > > startup_object_cache_
std::vector< Tagged< Object > > shared_heap_object_cache_
BuiltinsConstantsTableBuilder * builtins_constants_table_builder_ = nullptr
const uint8_t * embedded_blob_code_ = nullptr
uint32_t embedded_blob_code_size_ = 0
const uint8_t * embedded_blob_data_ = nullptr
uint32_t embedded_blob_data_size_ = 0
v8::ArrayBuffer::Allocator * array_buffer_allocator_ = nullptr
std::shared_ptr< v8::ArrayBuffer::Allocator > array_buffer_allocator_shared_
size_t array_buffer_max_size_ = 0
std::shared_ptr< v8::TaskRunner > task_runner_
FutexWaitListNode futex_wait_list_node_
CancelableTaskManager * cancelable_task_manager_ = nullptr
debug::ConsoleDelegate * console_delegate_ = nullptr
debug::AsyncEventDelegate * async_event_delegate_ = nullptr
uint32_t promise_hook_flags_ = 0
uint32_t current_async_task_id_ = 0
std::unique_ptr< LocalIsolate > main_thread_local_isolate_
v8::Isolate::AbortOnUncaughtExceptionCallback abort_on_uncaught_exception_callback_ = nullptr
bool allow_atomics_wait_ = true
bool flush_denormals_ = false
base::Mutex managed_ptr_destructors_mutex_
ManagedPtrDestructor * managed_ptr_destructors_head_ = nullptr
size_t total_regexp_code_generated_ = 0
size_t elements_deletion_counter_ = 0
std::unique_ptr< TracingCpuProfilerImpl > tracing_cpu_profiler_
EmbeddedFileWriterInterface * embedded_file_writer_ = nullptr
PrepareStackTraceCallback prepare_stack_trace_callback_ = nullptr
base::Mutex thread_data_table_mutex_
ThreadDataTable thread_data_table_
std::optional< Isolate * > shared_space_isolate_
std::unique_ptr< SharedStructTypeRegistry > shared_struct_type_registry_
std::list< std::unique_ptr< detail::WaiterQueueNode > > async_waiter_queue_nodes_
std::unique_ptr< GlobalSafepoint > global_safepoint_
Isolate * global_safepoint_prev_client_isolate_ = nullptr
Isolate * global_safepoint_next_client_isolate_ = nullptr
std::atomic< std::vector< MemoryRange > * > code_pages_ {nullptr}
std::vector< MemoryRange > code_pages_buffer1_
std::vector< MemoryRange > code_pages_buffer2_
base::Mutex code_pages_mutex_
size_t stack_size_
AddCrashKeyCallback add_crash_key_callback_ = nullptr
bool is_frozen_ = false
Friends
class GlobalSafepoint
class heap::HeapTester
class IsolateForPointerCompression
class IsolateForSandbox
class IsolateGroup
class TestSerializer
class SharedHeapNoClientsTest
Detailed Description
Definition at line 595 of file isolate.h.
Member Typedef Documentation
HandleScopeType
using v8::internal::Isolate::HandleScopeType = HandleScope
Definition at line 605 of file isolate.h.
InterruptEntry
using v8::internal::Isolate::InterruptEntry = std::pair<InterruptCallback, void*> [private]
Definition at line 2752 of file isolate.h.
Member Enumeration Documentation
CatchType
enum v8::internal::Isolate::CatchType
Enumerator
NOT_CAUGHT
CAUGHT_BY_JAVASCRIPT
CAUGHT_BY_EXTERNAL
CAUGHT_BY_PROMISE
CAUGHT_BY_ASYNC_AWAIT
Definition at line 1090 of file isolate.h.
                 {
    NOT_CAUGHT,
    CAUGHT_BY_JAVASCRIPT,
    CAUGHT_BY_EXTERNAL,
    CAUGHT_BY_PROMISE,
    CAUGHT_BY_ASYNC_AWAIT,
  };
ExceptionHandlerType
enum v8::internal::Isolate::ExceptionHandlerType [strong]
Enumerator
kJavaScriptHandler
kExternalTryCatch
kNone
Definition at line 891 of file isolate.h.
                                  {
    kJavaScriptHandler,
    kExternalTryCatch,
    kNone
  };
KnownPrototype
enum v8::internal::Isolate::KnownPrototype [strong]
Enumerator
kNone
kObject
kArray
kString
Definition at line 1691 of file isolate.h.
{ kNone, kObject, kArray, kString };
PrintStackMode
enum v8::internal::Isolate::PrintStackMode
Enumerator
kPrintStackConcise
kPrintStackVerbose
Definition at line 991 of file isolate.h.
{ kPrintStackConcise, kPrintStackVerbose };
Constructor & Destructor Documentation
Isolate() [1/2]
v8::internal::Isolate::Isolate (const Isolate &) [delete]
Referenced by Allocate().
Isolate() [2/2]
v8::internal::Isolate::Isolate (IsolateGroup * isolate_group) [explicit], [private]
Definition at line 4241 of file isolate.cc.
    : isolate_data_(this, isolate_group),
      isolate_group_(isolate_group),
      id_(isolate_counter.fetch_add(1, std::memory_order_relaxed)),
      allocator_(new TracingAccountingAllocator(this)),
      traced_handles_(this),
      builtins_(this),
#if defined(DEBUG) || defined(VERIFY_HEAP)
      num_active_deserializers_(0),
#endif
      logger_(new Logger()),
      detailed_source_positions_for_profiling_(v8_flags.detailed_line_info),
      persistent_handles_list_(new PersistentHandlesList()),
      jitless_(v8_flags.jitless),
      next_unique_sfi_id_(0),
      next_module_async_evaluation_ordinal_(
          SourceTextModule::kFirstAsyncEvaluationOrdinal),
      cancelable_task_manager_(new CancelableTaskManager()),
#if defined(V8_ENABLE_ETW_STACK_WALKING)
      etw_tracing_enabled_(false),
      etw_trace_interpreted_frames_(v8_flags.interpreted_frames_native_stack),
      etw_in_rundown_(false),
#endif // V8_ENABLE_ETW_STACK_WALKING
      stack_size_(v8_flags.stack_size * KB) {
  TRACE_ISOLATE(constructor);
  CheckIsolateLayout();
  // ThreadManager is initialized early to support locking an isolate
  // before it is entered.
  thread_manager_ = new ThreadManager(this);
  handle_scope_data()->Initialize();
#define ISOLATE_INIT_EXECUTE(type, name, initial_value) \
  name##_ = (initial_value);
  ISOLATE_INIT_LIST(ISOLATE_INIT_EXECUTE)
#undef ISOLATE_INIT_EXECUTE
#define ISOLATE_INIT_ARRAY_EXECUTE(type, name, length) \
  memset(name##_, 0, sizeof(type) * length);
  ISOLATE_INIT_ARRAY_LIST(ISOLATE_INIT_ARRAY_EXECUTE)
#undef ISOLATE_INIT_ARRAY_EXECUTE
  InitializeLoggingAndCounters();
  debug_ = new Debug(this);
  InitializeDefaultEmbeddedBlob();
#if V8_ENABLE_WEBASSEMBLY
  // If we are in production V8 and not in mksnapshot we have to pass the
  // landing pad builtin to the WebAssembly TrapHandler.
  // TODO(ahaas): Isolate creation is the earliest point in time when builtins
  // are available, so we cannot set the landing pad earlier at the moment.
  // However, if builtins ever get loaded during process initialization time,
  // then the initialization of the trap handler landing pad should also go
  // there.
  // TODO(ahaas): The code of the landing pad does not have to be a builtin,
  // we could also just move it to the trap handler, and implement it e.g. with
  // inline assembly. It's not clear if that's worth it.
  if (Isolate::CurrentEmbeddedBlobCodeSize()) {
    Address landing_pad =
        Builtins::EmbeddedEntryOf(Builtin::kWasmTrapHandlerLandingPad);
    i::trap_handler::SetLandingPad(landing_pad);
  }
#endif // V8_ENABLE_WEBASSEMBLY
  MicrotaskQueue::SetUpDefaultMicrotaskQueue(this);
}
References CheckIsolateLayout(), CurrentEmbeddedBlobCodeSize(), debug_, v8::internal::Builtins::EmbeddedEntryOf(), handle_scope_data(), v8::internal::HandleScopeData::Initialize(), InitializeDefaultEmbeddedBlob(), InitializeLoggingAndCounters(), ISOLATE_INIT_ARRAY_EXECUTE, ISOLATE_INIT_ARRAY_LIST, ISOLATE_INIT_EXECUTE, ISOLATE_INIT_LIST, v8::internal::trap_handler::SetLandingPad(), v8::internal::MicrotaskQueue::SetUpDefaultMicrotaskQueue(), thread_manager_, and TRACE_ISOLATE.
 Isolate()
v8::internal::Isolate::~Isolate () [private]
Definition at line 4758 of file isolate.cc.
                  {
  TRACE_ISOLATE(destructor);
  DCHECK_NULL(current_deoptimizer_);
  // The entry stack must be empty when we get here.
  DCHECK(entry_stack_ == nullptr ||
         entry_stack_.load()->previous_item == nullptr);
  delete entry_stack_;
  entry_stack_ = nullptr;
  delete date_cache_;
  date_cache_ = nullptr;
  delete regexp_stack_;
  regexp_stack_ = nullptr;
  delete descriptor_lookup_cache_;
  descriptor_lookup_cache_ = nullptr;
  delete load_stub_cache_;
  load_stub_cache_ = nullptr;
  delete store_stub_cache_;
  store_stub_cache_ = nullptr;
  delete define_own_stub_cache_;
  define_own_stub_cache_ = nullptr;
  delete materialized_object_store_;
  materialized_object_store_ = nullptr;
  delete v8_file_logger_;
  v8_file_logger_ = nullptr;
  delete handle_scope_implementer_;
  handle_scope_implementer_ = nullptr;
  delete code_tracer();
  set_code_tracer(nullptr);
  delete compilation_cache_;
  compilation_cache_ = nullptr;
  delete bootstrapper_;
  bootstrapper_ = nullptr;
  delete thread_manager_;
  thread_manager_ = nullptr;
  bigint_processor_->Destroy();
  delete global_handles_;
  global_handles_ = nullptr;
  delete eternal_handles_;
  eternal_handles_ = nullptr;
#if V8_ENABLE_WEBASSEMBLY
  wasm::WasmEngine::FreeAllOrphanedGlobalHandles(wasm_orphaned_handle_);
#endif
  delete string_stream_debug_object_cache_;
  string_stream_debug_object_cache_ = nullptr;
  delete random_number_generator_;
  random_number_generator_ = nullptr;
  delete fuzzer_rng_;
  fuzzer_rng_ = nullptr;
  delete debug_;
  debug_ = nullptr;
  delete cancelable_task_manager_;
  cancelable_task_manager_ = nullptr;
  delete allocator_;
  allocator_ = nullptr;
  DCHECK_NULL(builtins_effects_analyzer_);
  // Assert that |default_microtask_queue_| is the last MicrotaskQueue instance.
  DCHECK_IMPLIES(default_microtask_queue_,
                 default_microtask_queue_ == default_microtask_queue_->next());
  delete default_microtask_queue_;
  default_microtask_queue_ = nullptr;
  // isolate_group_ released in caller, to ensure that all member destructors
  // run before potentially unmapping the isolate's VirtualMemoryArea.
}
References allocator_, bigint_processor_, bootstrapper_, builtins_effects_analyzer_, cancelable_task_manager_, compilation_cache_, current_deoptimizer_, date_cache_, v8::internal::DCHECK(), DCHECK_IMPLIES, DCHECK_NULL, debug_, define_own_stub_cache_, descriptor_lookup_cache_, v8::bigint::Processor::Destroy(), entry_stack_, eternal_handles_, v8::internal::wasm::WasmEngine::FreeAllOrphanedGlobalHandles(), fuzzer_rng_, global_handles_, handle_scope_implementer_, load_stub_cache_, materialized_object_store_, random_number_generator_, regexp_stack_, store_stub_cache_, thread_manager_, TRACE_ISOLATE, and v8_file_logger_.
Referenced by Deinitialize().
Member Function Documentation
AbortConcurrentOptimization()
void v8::internal::Isolate::AbortConcurrentOptimization (BlockingBehavior blocking_behavior)
Definition at line 6186 of file isolate.cc.
                                                                   {
  if (concurrent_recompilation_enabled()) {
    DisallowGarbageCollection no_recursive_gc;
    optimizing_compile_dispatcher()->Flush(behavior);
  }
#ifdef V8_ENABLE_MAGLEV
  if (maglev_concurrent_dispatcher()->is_enabled()) {
    DisallowGarbageCollection no_recursive_gc;
    maglev_concurrent_dispatcher()->Flush(behavior);
  }
#endif
}
References concurrent_recompilation_enabled(), v8::internal::OptimizingCompileDispatcher::Flush(), and optimizing_compile_dispatcher().
Referenced by v8::Isolate::ClearCachesForTesting(), v8::Isolate::ContextDisposedNotification(), v8::internal::Deoptimizer::DeoptimizeAll(), v8::internal::Deoptimizer::DeoptimizeAllOptimizedCodeWithFunction(), and v8::internal::anonymous_namespace{heap.cc}::FreeCachesOnMemoryPressure().
active_dynamic_regexp_result_vectors()
std::unordered_set<int32_t*>& v8::internal::Isolate::active_dynamic_regexp_result_vectors () [inline]
Definition at line 1487 of file isolate.h.
                                                                     {
    return active_dynamic_regexp_result_vectors_;
  }
Referenced by v8::internal::RegExpResultVector::Allocate(), and v8::internal::RegExpResultVector::Free().
AddBeforeCallEnteredCallback()
void v8::internal::Isolate::AddBeforeCallEnteredCallback (BeforeCallEnteredCallback callback)
Definition at line 6496 of file isolate.cc.
                                                                             {
  auto pos = std::find(before_call_entered_callbacks_.begin(),
                       before_call_entered_callbacks_.end(), callback);
  if (pos != before_call_entered_callbacks_.end()) return;
  before_call_entered_callbacks_.push_back(callback);
}
References before_call_entered_callbacks_.
Referenced by v8::Isolate::AddBeforeCallEnteredCallback().
AddCallCompletedCallback()
void v8::internal::Isolate::AddCallCompletedCallback (CallCompletedCallback callback)
Definition at line 6511 of file isolate.cc.
                                                                     {
  auto pos = std::find(call_completed_callbacks_.begin(),
                       call_completed_callbacks_.end(), callback);
  if (pos != call_completed_callbacks_.end()) return;
  call_completed_callbacks_.push_back(callback);
}
References call_completed_callbacks_.
Referenced by v8::Isolate::AddCallCompletedCallback().
AddCodeMemoryChunk()
void v8::internal::Isolate::AddCodeMemoryChunk (MutablePageMetadata * chunk)
Definition at line 7531 of file isolate.cc.
                                                           {
  // We only keep track of individual code pages/allocations if we are on arm32,
  // because on x64 and arm64 we have a code range which makes this unnecessary.
#if defined(V8_TARGET_ARCH_ARM)
  void* new_page_start = reinterpret_cast<void*>(chunk->area_start());
  size_t new_page_size = chunk->area_size();
  MemoryRange new_range{new_page_start, new_page_size};
  AddCodeMemoryRange(new_range);
#endif // !defined(V8_TARGET_ARCH_ARM)
}
References AddCodeMemoryRange(), v8::internal::MemoryChunkMetadata::area_size(), and v8::internal::MemoryChunkMetadata::area_start().
Referenced by v8::internal::Heap::NotifyOldGenerationExpansion().
AddCodeMemoryRange()
void v8::internal::Isolate::AddCodeMemoryRange (MemoryRange range) [private]
Definition at line 7496 of file isolate.cc.
                                                  {
  base::MutexGuard guard(&code_pages_mutex_);
  std::vector<MemoryRange>* old_code_pages = GetCodePages();
  DCHECK_NOT_NULL(old_code_pages);
#ifdef DEBUG
  auto overlapping = [range](const MemoryRange& a) {
    return Overlapping(range, a);
  };
  DCHECK_EQ(old_code_pages->end(),
            std::find_if(old_code_pages->begin(), old_code_pages->end(),
                         overlapping));
#endif
  std::vector<MemoryRange>* new_code_pages;
  if (old_code_pages == &code_pages_buffer1_) {
    new_code_pages = &code_pages_buffer2_;
  } else {
    new_code_pages = &code_pages_buffer1_;
  }
  // Copy all existing data from the old vector to the new vector and insert the
  // new page.
  new_code_pages->clear();
  new_code_pages->reserve(old_code_pages->size() + 1);
  std::merge(old_code_pages->begin(), old_code_pages->end(), &range, &range + 1,
             std::back_inserter(*new_code_pages),
             [](const MemoryRange& a, const MemoryRange& b) {
               return a.start < b.start;
             });
  // Atomically switch out the pointer
  SetCodePages(new_code_pages);
}
References code_pages_buffer1_, code_pages_buffer2_, code_pages_mutex_, DCHECK_EQ, DCHECK_NOT_NULL, GetCodePages(), and SetCodePages().
Referenced by AddCodeMemoryChunk(), and AddCodeRange().
AddCodeRange()
void v8::internal::Isolate::AddCodeRange (Address begin, size_t length_in_bytes)
Definition at line 7544 of file isolate.cc.
                                                                {
  AddCodeMemoryRange(
      MemoryRange{reinterpret_cast<void*>(begin), length_in_bytes});
}
References AddCodeMemoryRange(), and v8::internal::Factory::begin.
Referenced by v8::internal::Heap::SetUp().
AddCrashKey()
void v8::internal::Isolate::AddCrashKey (CrashKeyId id, const std::string & value) [inline]
Definition at line 2075 of file isolate.h.
                                                          {
    if (add_crash_key_callback_) {
      add_crash_key_callback_(id, value);
    }
  }
References v8::internal::value.
AddCrashKeysForIsolateAndHeapPointers()
void v8::internal::Isolate::AddCrashKeysForIsolateAndHeapPointers () [private]
Definition at line 5337 of file isolate.cc.
                                                    {
  DCHECK_NOT_NULL(add_crash_key_callback_);
  const uintptr_t isolate_address = reinterpret_cast<uintptr_t>(this);
  add_crash_key_callback_(v8::CrashKeyId::kIsolateAddress,
                          ToHexString(isolate_address));
  const uintptr_t ro_space_firstpage_address =
      heap()->read_only_space()->FirstPageAddress();
  add_crash_key_callback_(v8::CrashKeyId::kReadonlySpaceFirstPageAddress,
                          ToHexString(ro_space_firstpage_address));
  const uintptr_t old_space_firstpage_address =
      heap()->old_space()->FirstPageAddress();
  add_crash_key_callback_(v8::CrashKeyId::kOldSpaceFirstPageAddress,
                          ToHexString(old_space_firstpage_address));
  if (heap()->code_range_base()) {
    const uintptr_t code_range_base_address = heap()->code_range_base();
    add_crash_key_callback_(v8::CrashKeyId::kCodeRangeBaseAddress,
                            ToHexString(code_range_base_address));
  }
  if (heap()->code_space()->first_page()) {
    const uintptr_t code_space_firstpage_address =
        heap()->code_space()->FirstPageAddress();
    add_crash_key_callback_(v8::CrashKeyId::kCodeSpaceFirstPageAddress,
                            ToHexString(code_space_firstpage_address));
  }
  const v8::StartupData* data = Snapshot::DefaultSnapshotBlob();
  // TODO(cbruni): Implement strategy to infrequently collect this.
  const uint32_t v8_snapshot_checksum_calculated = 0;
  add_crash_key_callback_(v8::CrashKeyId::kSnapshotChecksumCalculated,
                          ToHexString(v8_snapshot_checksum_calculated));
  const uint32_t v8_snapshot_checksum_expected =
      Snapshot::GetExpectedChecksum(data);
  add_crash_key_callback_(v8::CrashKeyId::kSnapshotChecksumExpected,
                          ToHexString(v8_snapshot_checksum_expected));
}
References add_crash_key_callback_, v8::internal::Heap::code_range_base(), v8::internal::Heap::code_space(), DCHECK_NOT_NULL, v8::internal::Snapshot::DefaultSnapshotBlob(), v8::internal::ReadOnlySpace::FirstPageAddress(), v8::internal::Snapshot::GetExpectedChecksum(), heap(), v8::kCodeRangeBaseAddress, v8::kCodeSpaceFirstPageAddress, v8::kIsolateAddress, v8::kOldSpaceFirstPageAddress, v8::kReadonlySpaceFirstPageAddress, v8::kSnapshotChecksumCalculated, v8::kSnapshotChecksumExpected, v8::internal::Heap::old_space(), v8::internal::Heap::read_only_space(), and v8::internal::anonymous_namespace{isolate.cc}::ToHexString().
Referenced by SetAddCrashKeyCallback().
AddDetachedContext()
void v8::internal::Isolate::AddDetachedContext (DirectHandle< Context > context)
Definition at line 7197 of file isolate.cc.
                                                              {
  HandleScope scope(this);
  Handle<WeakArrayList> detached_contexts = factory()->detached_contexts();
  detached_contexts = WeakArrayList::AddToEnd(
      this, detached_contexts, MaybeObjectDirectHandle::Weak(context),
      Smi::zero());
  heap()->set_detached_contexts(*detached_contexts);
}
References v8::internal::WeakArrayList::AddToEnd(), context(), factory(), heap(), v8::internal::MaybeObjectDirectHandle::Weak(), and v8::internal::Smi::zero().
Referenced by DetachGlobal().
address_of_regexp_static_result_offsets_vector()
Address v8::internal::Isolate::address_of_regexp_static_result_offsets_vector () const [inline]
Definition at line 1483 of file isolate.h.
                                                                 {
    return isolate_data()->regexp_static_result_offsets_vector_address();
  }
Allocate()
Isolate * v8::internal::Isolate::Allocate (IsolateGroup * isolate_group) [static], [private]
Definition at line 4169 of file isolate.cc.
                                              {
  // v8::V8::Initialize() must be called before creating any isolates.
  DCHECK_NOT_NULL(V8::GetCurrentPlatform());
  // Allocate Isolate itself on C++ heap, ensuring page alignment.
  void* isolate_ptr = base::AlignedAlloc(sizeof(Isolate), kMinimumOSPageSize);
  // IsolateAllocator manages the virtual memory resources for the Isolate.
  Isolate* isolate = new (isolate_ptr) Isolate(group);
#ifdef DEBUG
  non_disposed_isolates_++;
#endif // DEBUG
  return isolate;
}
References v8::base::AlignedAlloc(), DCHECK_NOT_NULL, v8::internal::V8::GetCurrentPlatform(), v8::internal::Factory::isolate(), Isolate(), and kMinimumOSPageSize.
Referenced by New().
allocator()
AccountingAllocator* v8::internal::Isolate::allocator () [inline]
Definition at line 2019 of file isolate.h.
{ return allocator_; }
Referenced by v8::internal::compiler::turboshaft::PipelineData::allocator(), v8::internal::SourceTextModule::AsyncModuleExecutionFulfilled(), v8::internal::compiler::turboshaft::BuildWithTurboshaftAssemblerImpl(), v8::internal::KeyAccumulator::CollectOwnJSProxyKeys(), v8::internal::Compiler::CollectSourcePositions(), v8::internal::RegExp::Compile(), v8::internal::Compiler::Compile(), v8::internal::compiler::CompileCWasmEntry(), v8::internal::anonymous_namespace{experimental.cc}::CompileImpl(), v8::internal::RegExpImpl::CompileIrregexp(), v8::internal::anonymous_namespace{compiler.cc}::CompileToplevel(), v8::internal::SourceTextModule::Evaluate(), v8::internal::anonymous_namespace{experimental.cc}::ExecRawImpl(), v8::internal::compiler::Pipeline::GenerateCodeForTesting(), v8::Isolate::GetHeapStatistics(), v8::internal::Module::GetModuleNamespace(), v8::internal::SourceTextModule::GetStalledTopLevelAwaitMessages(), v8::internal::Module::Instantiate(), v8::internal::Module::IsGraphAsync(), PrintStack(), v8::internal::Heap::RecordStats(), v8::internal::compiler::PerIsolateCompilerCache::Setup(), StackTraceString(), v8::internal::anonymous_namespace{liveedit.cc}::TranslateSourcePositionTable(), and v8::internal::anonymous_namespace{runtime-test-wasm.cc}::ValidateFunctionNowIfNeeded().
allow_atomics_wait()
bool v8::internal::Isolate::allow_atomics_wait () [inline]
Definition at line 2171 of file isolate.h.
{ return allow_atomics_wait_; }
Referenced by v8::internal::wasm::WasmInterpreterRuntime::AllowsAtomicsWait(), v8::internal::DoWait(), and v8::internal::RUNTIME_FUNCTION().
AllowsCodeCompaction()
bool v8::internal::Isolate::AllowsCodeCompaction () const
Definition at line 6244 of file isolate.cc.
                                         {
  return v8_flags.compact_code_space && logger()->allows_code_compaction();
}
References v8::internal::Logger::allows_code_compaction(), logger(), and v8::internal::v8_flags.
Referenced by v8::internal::MarkCompactCollector::StartCompaction().
ArchiveSpacePerThread()
static int v8::internal::Isolate::ArchiveSpacePerThread () [inline], [static]
Definition at line 962 of file isolate.h.
{ return sizeof(ThreadLocalTop); }
Referenced by v8::internal::ArchiveSpacePerThread().
ArchiveThread()
char * v8::internal::Isolate::ArchiveThread (char * to)
Definition at line 3822 of file isolate.cc.
                                     {
  MemCopy(to, reinterpret_cast<char*>(thread_local_top()),
          sizeof(ThreadLocalTop));
  return to + sizeof(ThreadLocalTop);
}
References v8::internal::MemCopy(), and thread_local_top().
Referenced by v8::internal::ThreadManager::EagerlyArchiveThread().
array_buffer_allocator()
v8::ArrayBuffer::Allocator* v8::internal::Isolate::array_buffer_allocator () const [inline]
Definition at line 1978 of file isolate.h.
                                                         {
    return array_buffer_allocator_;
  }
Referenced by v8::internal::BackingStore::Allocate(), v8::internal::Heap::AllocateExternalBackingStore(), v8::internal::anonymous_namespace{builtins-arraybuffer.cc}::ArrayBufferTransfer(), v8::Isolate::GetArrayBufferAllocator(), v8::ArrayBuffer::MaybeNew(), v8::internal::BackingStore::SetAllocatorFromIsolate(), and v8::internal::anonymous_namespace{builtins-arraybuffer.cc}::TryAllocateBackingStore().
array_buffer_allocator_shared()
std::shared_ptr<v8::ArrayBuffer::Allocator> v8::internal::Isolate::array_buffer_allocator_shared () const [inline]
Definition at line 1986 of file isolate.h.
            {
    return array_buffer_allocator_shared_;
  }
Referenced by v8::internal::BackingStore::SetAllocatorFromIsolate().
array_buffer_max_size_address()
size_t* v8::internal::Isolate::array_buffer_max_size_address () [inline]
Definition at line 1991 of file isolate.h.
                                          {
    if (array_buffer_max_size_ == 0) {
      array_buffer_max_size_ = array_buffer_allocator_->MaxAllocationSize();
    }
    return &array_buffer_max_size_;
  }
AsIsolate()
Isolate* v8::internal::Isolate::AsIsolate () [inline]
Definition at line 2227 of file isolate.h.
{ return this; }
AsLocalIsolate()
LocalIsolate* v8::internal::Isolate::AsLocalIsolate () [inline]
Definition at line 2228 of file isolate.h.
{ return main_thread_local_isolate(); }
Referenced by v8::ScriptCompiler::CachedData::CompatibilityCheck(), v8::internal::CodeSerializer::Deserialize(), v8::internal::BackgroundCompileTask::FinalizeScript(), and v8::internal::compiler::JSHeapBroker::local_isolate_or_isolate().
ast_string_constants()
const AstStringConstants* v8::internal::Isolate::ast_string_constants () const [inline]
Definition at line 2004 of file isolate.h.
                                                         {
    return ast_string_constants_;
  }
async_counters()
const std::shared_ptr<Counters>& v8::internal::Isolate::async_counters () [inline]
Definition at line 1197 of file isolate.h.
                                                  {
    // Make sure InitializeCounters() has been called.
    DCHECK_NOT_NULL(async_counters_.get());
    return async_counters_;
  }
References DCHECK_NOT_NULL.
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompileNativeModule(), v8::internal::wasm::WasmImportWrapperCache::LazyInitialize(), v8::internal::wasm::WasmCodeManager::NewNativeModule(), and v8::internal::wasm::AsyncCompileJob::PrepareAndStartCompile::RunInForeground().
async_event_delegate_address()
Address v8::internal::Isolate::async_event_delegate_address () [inline]
Definition at line 1888 of file isolate.h.
                                         {
    return reinterpret_cast<Address>(&async_event_delegate_);
  }
async_waiter_queue_nodes()
std::list< std::unique_ptr< detail::WaiterQueueNode > > & v8::internal::Isolate::async_waiter_queue_nodes ()
Definition at line 7736 of file isolate.cc.
                                  {
  return async_waiter_queue_nodes_;
}
References async_waiter_queue_nodes_.
Referenced by v8::internal::JSSynchronizationPrimitive::CleanupAsyncWaiterLists(), v8::internal::detail::AsyncWaiterQueueNode< T >::NewLockedAsyncWaiterStoredInIsolate(), and v8::internal::detail::AsyncWaiterQueueNode< T >::RemoveFromAsyncWaiterQueueList().
BatterySaverModeEnabled()
bool v8::internal::Isolate::BatterySaverModeEnabled () [inline]
Definition at line 2151 of file isolate.h.
                                 {
    if (V8_UNLIKELY(v8_flags.battery_saver_mode.value().has_value())) {
      return *v8_flags.battery_saver_mode.value();
    }
    return V8_UNLIKELY(battery_saver_mode_enabled_);
  }
References v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::internal::anonymous_namespace{runtime-compiler.cc}::CompileOptimizedOSRFromMaglev(), v8::internal::TieringManager::MaybeOptimizeFrame(), v8::internal::TieringManager::ShouldOptimize(), and v8::internal::Heap::ShouldOptimizeForBattery().
bigint_processor()
bigint::Processor* v8::internal::Isolate::bigint_processor () [inline]
Definition at line 1439 of file isolate.h.
{ return bigint_processor_; }
Referenced by v8::internal::BigInt::Divide(), v8::internal::BigInt::Multiply(), v8::internal::MutableBigInt_AbsoluteDivAndCanonicalize(), v8::internal::MutableBigInt_AbsoluteModAndCanonicalize(), v8::internal::MutableBigInt_AbsoluteMulAndCanonicalize(), v8::internal::BigInt::Remainder(), and v8::internal::BigInt::ToString().
boilerplate_migration_access()
base::Mutex* v8::internal::Isolate::boilerplate_migration_access () [inline]
Definition at line 785 of file isolate.h.
                                            {
    return &boilerplate_migration_access_;
  }
Referenced by v8::internal::anonymous_namespace{runtime-literals.cc}::JSObjectWalkVisitor< ContextObject >::StructureWalk().
bootstrapper()
Bootstrapper* v8::internal::Isolate::bootstrapper () [inline]
Definition at line 1193 of file isolate.h.
{ return bootstrapper_; }
Referenced by v8::internal::compiler::CanBeImmediate(), v8::internal::Genesis::CompileExtension(), v8::internal::Map::CopyForPreventExtensions(), v8::internal::Map::CopyReplaceDescriptors(), v8::internal::ThreadManager::EagerlyArchiveThread(), v8::internal::ThreadManager::FreeThreadResources(), v8::internal::interpreter::BytecodeGenerator::GenerateBytecode(), v8::internal::Debug::HandleDebugBreak(), v8::internal::compiler::Loong64OperandConverter::InputImmediate(), v8::internal::compiler::PPCOperandConverter::InputImmediate(), v8::internal::compiler::RiscvOperandConverter::InputImmediate(), v8::internal::LookupIterator::InternalUpdateProtector(), v8::InvokeBootstrapper< i::NativeContext >::Invoke(), v8::InvokeBootstrapper< i::JSGlobalProxy >::Invoke(), v8::internal::Heap::IterateRoots(), v8::internal::V8FileLogger::MapEvent(), MayAccess(), v8::internal::JSObject::OptimizeAsPrototype(), v8::internal::JSFunction::RequestOptimization(), v8::internal::ThreadManager::RestoreThread(), v8::internal::Snapshot::SerializeDeserializeAndVerifyForTesting(), v8::internal::anonymous_namespace{js-function.cc}::SetInstancePrototype(), Throw(), v8::internal::compiler::Arm64OperandConverter::ToImmediate(), v8::internal::compiler::X64OperandConverter::ToImmediate(), v8::internal::anonymous_namespace{property-descriptor.cc}::ToPropertyDescriptorFastPath(), v8::internal::Map::TransitionToAccessorProperty(), v8::internal::Map::TransitionToDataProperty(), and v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord32EqualImpl().
break_access()
base::RecursiveMutex* v8::internal::Isolate::break_access () [inline]
Definition at line 751 of file isolate.h.
{ return &break_access_; }
Referenced by v8::internal::ExecutionAccess::Lock(), v8::internal::ExecutionAccess::TryLock(), and v8::internal::ExecutionAccess::Unlock().
builtin_entry_table()
Address* v8::internal::Isolate::builtin_entry_table () [inline]
Definition at line 1298 of file isolate.h.
{ return isolate_data_.builtin_entry_table(); }
Referenced by v8::internal::Builtins::EntryOf(), and v8::internal::MacroAssembler::MacroAssemblerBase().
builtin_table()
Address* v8::internal::Isolate::builtin_table () [inline]
Definition at line 1320 of file isolate.h.
{ return isolate_data_.builtin_table(); }
Referenced by v8::internal::Builtins::EmitCodeCreateEvents(), and IsBuiltinTableHandleLocation().
builtin_tier0_table()
Address* v8::internal::Isolate::builtin_tier0_table () [inline]
Definition at line 1321 of file isolate.h.
                                           {
    return isolate_data_.builtin_tier0_table();
  }
builtins()
Builtins* v8::internal::Isolate::builtins () [inline]
Definition at line 1458 of file isolate.h.
{ return &builtins_; }
Referenced by v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildWithMacroAssembler(), v8::internal::compiler::turboshaft::BuiltinCodeHandle(), v8::internal::Genesis::builtins(), v8::internal::Builtins::CallableFor(), v8::internal::MacroAssembler::CallBuiltin(), v8::internal::CodeFactory::CEntry(), v8::internal::StubCache::Clear(), v8::internal::V8FileLogger::CodeCreateEvent(), v8::internal::Builtins::CreateInterpreterEntryTrampolineForProfiling(), v8::internal::StartupDeserializer::DeserializeIntoIsolate(), v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::Deoptimizer::DoComputeConstructCreateStubFrame(), v8::internal::Deoptimizer::DoComputeConstructInvokeStubFrame(), v8::internal::Deoptimizer::DoComputeUnoptimizedFrame(), v8::internal::Deoptimizer::EnsureValidReturnAddress(), v8::internal::BuiltinsConstantsTableBuilder::Finalize(), v8::internal::wasm::JSToWasmWrapperCompilationUnit::Finalize(), v8::internal::anonymous_namespace{isolate.cc}::FinalizeBuiltinCodeObjects(), v8::internal::anonymous_namespace{embedded-data.cc}::FinalizeEmbeddedCodeTargets(), v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_JSEntryVariant(), v8::internal::anonymous_namespace{builtins-riscv.cc}::GenerateExceptionHandlingLandingPad(), v8::internal::interpreter::Interpreter::GetBytecodeHandler(), v8::internal::SharedFunctionInfo::GetCode(), v8::Isolate::GetJSEntryStubs(), v8::internal::WasmExportedFunction::GetWrapper(), HashIsolateForEmbeddedBlob(), Init(), v8::internal::interpreter::Interpreter::Initialize(), v8::internal::Builtins::InitializeIsolateDataTables(), v8::internal::anonymous_namespace{isolate.cc}::IsBuiltinFunction(), v8::internal::Heap::IterateBuiltins(), v8::internal::ExistingCodeLogger::LogBuiltins(), v8::internal::ProfilerCodeObserver::LogBuiltins(), v8::internal::ExistingCodeLogger::LogCodeObject(), v8::internal::WasmJSFunction::New(), v8::NewContext(), v8::internal::EmbeddedData::NewFromIsolate(), v8::internal::SetupIsolateDelegate::PopulateWithPlaceholders(), PrepareBuiltinSourcePositionMap(), v8::internal::SetupIsolateDelegate::ReplacePlaceholders(), v8::internal::SetupIsolateDelegate::SetupBuiltinsInternal(), v8::internal::MacroAssembler::TailCallBuiltin(), v8::internal::EntryFrame::unchecked_code(), v8::internal::ConstructEntryFrame::unchecked_code(), UnwindAndFindHandler(), and v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::Verify().
builtins_constants_table_builder()
BuiltinsConstantsTableBuilder* v8::internal::Isolate::builtins_constants_table_builder () const [inline]
Definition at line 1941 of file isolate.h.
                                                                          {
    return builtins_constants_table_builder_;
  }
Referenced by v8::internal::MacroAssemblerBase::IndirectLoadConstant().
builtins_effects_analyzer()
BuiltinsEffectsAnalyzer* v8::internal::Isolate::builtins_effects_analyzer () [inline]
Definition at line 1459 of file isolate.h.
                                                       {
    return builtins_effects_analyzer_;
  }
Referenced by main(), v8::internal::compiler::turboshaft::CsaEffectsComputationPhase::Run(), and v8::internal::BuiltinsEffectsAnalyzer::TearDown().
c_entry_fp()
static Address v8::internal::Isolate::c_entry_fp (ThreadLocalTop * thread) [inline], [static]
Definition at line 904 of file isolate.h.
                                                    {
    return thread->c_entry_fp_;
  }
References v8::internal::ThreadLocalTop::c_entry_fp_.
Referenced by v8::internal::ProfilerEventsProcessor::AddDeoptStack(), v8::internal::anonymous_namespace{runtime-wasm.cc}::GetWasmInstanceDataOnStackTop(), v8::internal::StackFrameIteratorForProfiler::IsValidTop(), PrintStack(), v8::internal::StackFrameIterator::Reset(), and v8::internal::StackFrameIteratorForProfiler::StackFrameIteratorForProfiler().
c_entry_fp_address()
Address* v8::internal::Isolate::c_entry_fp_address () [inline]
Definition at line 910 of file isolate.h.
                                       {
    return &thread_local_top()->c_entry_fp_;
  }
Referenced by v8::internal::wasm::WasmInterpreterRuntime::CallWasmToJSBuiltin(), and v8::internal::ConservativePinningScope::ConservativePinningScope().
c_entry_fp_offset()
static uint32_t v8::internal::Isolate::c_entry_fp_offset () [inline], [static]
Definition at line 913 of file isolate.h.
                                      {
    return static_cast<uint32_t>(OFFSET_OF(Isolate, isolate_data_) +
                                 OFFSET_OF(IsolateData, thread_local_top_) +
                                 OFFSET_OF(ThreadLocalTop, c_entry_fp_) -
                                 isolate_root_bias());
  }
References OFFSET_OF.
Referenced by v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCapiCallWrapper().
c_function()
Address v8::internal::Isolate::c_function () [inline]
Definition at line 908 of file isolate.h.
{ return thread_local_top()->c_function_; }
Referenced by v8::internal::TickSample::GetStackSample().
c_function_address()
Address* v8::internal::Isolate::c_function_address () [inline]
Definition at line 920 of file isolate.h.
                                       {
    return &thread_local_top()->c_function_;
  }
cage_base()
Address v8::internal::Isolate::cage_base () const [inline]
Definition at line 1228 of file isolate.h.
                            {
    DCHECK_IMPLIES(!COMPRESS_POINTERS_BOOL,
                   isolate_data()->cage_base() == kNullAddress);
    return isolate_data()->cage_base();
  }
References COMPRESS_POINTERS_BOOL, DCHECK_IMPLIES, and v8::internal::kNullAddress.
Referenced by v8::internal::ReadOnlyHeapImageDeserializer::AllocatePage(), v8::internal::LocalIsolate::cage_base(), v8::internal::ReadOnlyHeapImageDeserializer::DeserializeReadOnlyRootsTable(), v8::internal::ReadOnlySpace::EnsurePage(), IncreaseTotalRegexpCodeGenerated(), Init(), v8::internal::anonymous_namespace{isolate.cc}::PredictException(), and SetIsolateThreadLocals().
cancelable_task_manager()
CancelableTaskManager* v8::internal::Isolate::cancelable_task_manager () [inline]
Definition at line 2000 of file isolate.h.
                                                   {
    return cancelable_task_manager_;
  }
Referenced by v8::internal::MinorGCJob::CancelTaskIfScheduled(), Deinit(), v8::internal::JSAtomicsMutex::HandleAsyncNotify(), v8::internal::JSAtomicsCondition::HandleAsyncNotify(), v8::internal::JSAtomicsMutex::HandleAsyncTimeout(), v8::internal::JSAtomicsCondition::HandleAsyncTimeout(), v8::internal::JSAtomicsMutex::LockAsyncSlowPath(), and v8::internal::JSAtomicsCondition::WaitAsync().
CancelTerminateExecution()
void v8::internal::Isolate::CancelTerminateExecution ()
Definition at line 1963 of file isolate.cc.
                                       {
  if (!is_execution_terminating()) return;
  clear_internal_exception();
  if (try_catch_handler()) try_catch_handler()->ResetInternal();
}
References clear_internal_exception(), is_execution_terminating(), v8::TryCatch::ResetInternal(), and try_catch_handler().
Referenced by v8::Isolate::CancelTerminateExecution(), v8::internal::Debug::StopSideEffectCheckMode(), and UnwindAndFindHandler().
CaptureAndSetErrorStack()
MaybeDirectHandle< JSObject > v8::internal::Isolate::CaptureAndSetErrorStack (DirectHandle< JSObject > error_object, FrameSkipMode mode, Handle< Object > caller)
Definition at line 1449 of file isolate.cc.
                           {
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.stack_trace"), __func__);
  Handle<UnionOf<Undefined, FixedArray>> call_site_infos_or_formatted_stack =
      factory()->undefined_value();
  // Capture the "simple stack trace" for the error.stack property,
  // which can be disabled by setting Error.stackTraceLimit to a non
  // number value or simply deleting the property. If the inspector
  // is active, and requests more stack frames than the JavaScript
  // program itself, we collect up to the maximum.
  int stack_trace_limit = 0;
  if (GetStackTraceLimit(this, &stack_trace_limit)) {
    int limit = stack_trace_limit;
    if (capture_stack_trace_for_uncaught_exceptions_ &&
        !(stack_trace_for_uncaught_exceptions_options_ &
          StackTrace::kExposeFramesAcrossSecurityOrigins)) {
      // Collect up to the maximum of what the JavaScript program and
      // the inspector want. There's a special case here where the API
      // can ask the stack traces to also include cross-origin frames,
      // in which case we collect a separate trace below. Note that
      // the inspector doesn't use this option, so we could as well
      // just deprecate this in the future.
      if (limit < stack_trace_for_uncaught_exceptions_frame_limit_) {
        limit = stack_trace_for_uncaught_exceptions_frame_limit_;
      }
    }
    call_site_infos_or_formatted_stack =
        CaptureSimpleStackTrace(this, limit, mode, caller);
  }
  DirectHandle<Object> error_stack = call_site_infos_or_formatted_stack;
  // Next is the inspector part: Depending on whether we got a "simple
  // stack trace" above and whether that's usable (meaning the API
  // didn't request to include cross-origin frames), we remember the
  // cap for the stack trace (either a positive limit indicating that
  // the Error.stackTraceLimit value was below what was requested via
  // the API, or a negative limit to indicate the opposite), or we
  // collect a "detailed stack trace" eagerly and stash that away.
  if (capture_stack_trace_for_uncaught_exceptions_) {
    DirectHandle<StackTraceInfo> stack_trace;
    if (IsUndefined(*call_site_infos_or_formatted_stack, this) ||
        (stack_trace_for_uncaught_exceptions_options_ &
         StackTrace::kExposeFramesAcrossSecurityOrigins)) {
      stack_trace = CaptureDetailedStackTrace(
          stack_trace_for_uncaught_exceptions_frame_limit_,
          stack_trace_for_uncaught_exceptions_options_);
    } else {
      auto call_site_infos =
          Cast<FixedArray>(call_site_infos_or_formatted_stack);
      stack_trace = GetDetailedStackTraceFromCallSiteInfos(
          this, call_site_infos,
          stack_trace_for_uncaught_exceptions_frame_limit_);
      if (stack_trace_limit < call_site_infos->length()) {
        call_site_infos_or_formatted_stack = FixedArray::RightTrimOrEmpty(
            this, call_site_infos, stack_trace_limit);
      }
      // Notify the debugger.
      OnStackTraceCaptured(stack_trace);
    }
    error_stack = factory()->NewErrorStackData(
        call_site_infos_or_formatted_stack, stack_trace);
  }
  RETURN_ON_EXCEPTION(
      this,
      Object::SetProperty(this, error_object, factory()->error_stack_symbol(),
                          error_stack, StoreOrigin::kMaybeKeyed,
                          Just(ShouldThrow::kThrowOnError)));
  return error_object;
}
References capture_stack_trace_for_uncaught_exceptions_, CaptureDetailedStackTrace(), v8::internal::anonymous_namespace{isolate.cc}::CaptureSimpleStackTrace(), factory(), v8::internal::anonymous_namespace{isolate.cc}::GetDetailedStackTraceFromCallSiteInfos(), GetStackTraceLimit(), v8::Just(), v8::StackTrace::kExposeFramesAcrossSecurityOrigins, v8::internal::kMaybeKeyed, v8::internal::kThrowOnError, v8::internal::Factory::length, mode(), v8::internal::Factory::NewErrorStackData(), OnStackTraceCaptured(), RETURN_ON_EXCEPTION, v8::internal::Object::SetProperty(), stack_trace_for_uncaught_exceptions_frame_limit_, stack_trace_for_uncaught_exceptions_options_, TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT0.
Referenced by v8::internal::ErrorUtils::CaptureStackTrace(), and v8::internal::ErrorUtils::Construct().
CaptureDetailedStackTrace()
DirectHandle< StackTraceInfo > v8::internal::Isolate::CaptureDetailedStackTrace (int limit, StackTrace::StackTraceOptions options)
Definition at line 1622 of file isolate.cc.
                                                    {
  TRACE_EVENT_BEGIN1(TRACE_DISABLED_BY_DEFAULT("v8.stack_trace"), __func__,
                     "maxFrameCount", limit);
  StackFrameBuilder builder(this, limit);
  VisitStack(this, &builder, options);
  auto frames = builder.Build();
  TRACE_EVENT_END1(TRACE_DISABLED_BY_DEFAULT("v8.stack_trace"), __func__,
                   "frameCount", frames->length());
  auto stack_trace = factory()->NewStackTraceInfo(frames);
  OnStackTraceCaptured(stack_trace);
  return stack_trace;
}
References factory(), v8::internal::Factory::NewStackTraceInfo(), OnStackTraceCaptured(), TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT_BEGIN1, TRACE_EVENT_END1, and v8::internal::anonymous_namespace{isolate.cc}::VisitStack().
Referenced by CaptureAndSetErrorStack(), CreateMessage(), and v8::StackTrace::CurrentStackTrace().
central_stack_limit_offset()
constexpr static uint32_t v8::internal::Isolate::central_stack_limit_offset () [inline], [static], [constexpr]
Definition at line 1381 of file isolate.h.
                                                         {
    return static_cast<uintptr_t>(
        OFFSET_OF(Isolate, isolate_data_) +
        OFFSET_OF(IsolateData, thread_local_top_) +
        OFFSET_OF(ThreadLocalTop, central_stack_limit_) - isolate_root_bias());
  }
References OFFSET_OF.
Referenced by v8::internal::wasm::WasmGraphBuilderBase::BuildSwitchToTheCentralStack().
central_stack_sp_offset()
constexpr static uint32_t v8::internal::Isolate::central_stack_sp_offset () [inline], [static], [constexpr]
Definition at line 1374 of file isolate.h.
                                                      {
    return static_cast<uintptr_t>(OFFSET_OF(Isolate, isolate_data_) +
                                  OFFSET_OF(IsolateData, thread_local_top_) +
                                  OFFSET_OF(ThreadLocalTop, central_stack_sp_) -
                                  isolate_root_bias());
  }
References OFFSET_OF.
Referenced by v8::internal::wasm::WasmGraphBuilderBase::BuildSwitchToTheCentralStack().
CheckDetachedContextsAfterGC()
void v8::internal::Isolate::CheckDetachedContextsAfterGC ()
Definition at line 7206 of file isolate.cc.
                                           {
  HandleScope scope(this);
  DirectHandle<WeakArrayList> detached_contexts =
      factory()->detached_contexts();
  int length = detached_contexts->length();
  if (length == 0) return;
  int new_length = 0;
  for (int i = 0; i < length; i += 2) {
    Tagged<MaybeObject> context = detached_contexts->Get(i);
    DCHECK(context.IsWeakOrCleared());
    if (!context.IsCleared()) {
      int mark_sweeps = detached_contexts->Get(i + 1).ToSmi().value();
      detached_contexts->Set(new_length, context);
      detached_contexts->Set(new_length + 1, Smi::FromInt(mark_sweeps + 1));
      new_length += 2;
    }
  }
  detached_contexts->set_length(new_length);
  while (new_length < length) {
    detached_contexts->Set(new_length, Smi::zero());
    ++new_length;
  }
  if (v8_flags.trace_detached_contexts) {
    PrintF("%d detached contexts are collected out of %d\n",
           length - new_length, length);
    for (int i = 0; i < new_length; i += 2) {
      Tagged<MaybeObject> context = detached_contexts->Get(i);
      int mark_sweeps = detached_contexts->Get(i + 1).ToSmi().value();
      DCHECK(context.IsWeakOrCleared());
      if (mark_sweeps > 3) {
        PrintF("detached context %p\n survived %d GCs (leak?)\n",
               reinterpret_cast<void*>(context.ptr()), mark_sweeps);
      }
    }
  }
}
References context(), v8::internal::DCHECK(), factory(), v8::internal::Smi::FromInt(), v8::internal::Factory::length, v8::internal::PrintF(), v8::internal::v8_flags, and v8::internal::Smi::zero().
Referenced by v8::internal::Heap::CollectGarbage().
CheckIsolateLayout()
void v8::internal::Isolate::CheckIsolateLayout () [private]
Definition at line 4310 of file isolate.cc.
                                 {
#ifdef V8_ENABLE_SANDBOX
  static_assert(static_cast<int>(OFFSET_OF(ExternalPointerTable, base_)) ==
                Internals::kExternalPointerTableBasePointerOffset);
  static_assert(static_cast<int>(OFFSET_OF(TrustedPointerTable, base_)) ==
                Internals::kTrustedPointerTableBasePointerOffset);
  static_assert(static_cast<int>(sizeof(ExternalPointerTable)) ==
                Internals::kExternalPointerTableSize);
  static_assert(static_cast<int>(sizeof(TrustedPointerTable)) ==
                Internals::kTrustedPointerTableSize);
#endif
  static_assert(OFFSET_OF(Isolate, isolate_data_) == 0);
  static_assert(
      static_cast<int>(OFFSET_OF(Isolate, isolate_data_.stack_guard_)) ==
      Internals::kIsolateStackGuardOffset);
  static_assert(
      static_cast<int>(OFFSET_OF(Isolate, isolate_data_.is_marking_flag_)) ==
      Internals::kVariousBooleanFlagsOffset);
  static_assert(static_cast<int>(
                    OFFSET_OF(Isolate, isolate_data_.error_message_param_)) ==
                Internals::kErrorMessageParamOffset);
  static_assert(static_cast<int>(OFFSET_OF(
                    Isolate, isolate_data_.builtin_tier0_entry_table_)) ==
                Internals::kBuiltinTier0EntryTableOffset);
  static_assert(static_cast<int>(
                    OFFSET_OF(Isolate, isolate_data_.builtin_tier0_table_)) ==
                Internals::kBuiltinTier0TableOffset);
  static_assert(static_cast<int>(
                    OFFSET_OF(Isolate, isolate_data_.new_allocation_info_)) ==
                Internals::kNewAllocationInfoOffset);
  static_assert(static_cast<int>(
                    OFFSET_OF(Isolate, isolate_data_.old_allocation_info_)) ==
                Internals::kOldAllocationInfoOffset);
  static_assert(static_cast<int>(
                    OFFSET_OF(Isolate, isolate_data_.fast_c_call_caller_fp_)) ==
                Internals::kIsolateFastCCallCallerFpOffset);
  static_assert(static_cast<int>(
                    OFFSET_OF(Isolate, isolate_data_.fast_c_call_caller_pc_)) ==
                Internals::kIsolateFastCCallCallerPcOffset);
  static_assert(
      static_cast<int>(OFFSET_OF(Isolate, isolate_data_.cage_base_)) ==
      Internals::kIsolateCageBaseOffset);
  static_assert(static_cast<int>(OFFSET_OF(
                    Isolate, isolate_data_.long_task_stats_counter_)) ==
                Internals::kIsolateLongTaskStatsCounterOffset);
  static_assert(
      static_cast<int>(OFFSET_OF(Isolate, isolate_data_.stack_guard_)) ==
      Internals::kIsolateStackGuardOffset);
  static_assert(
      static_cast<int>(OFFSET_OF(Isolate, isolate_data_.thread_local_top_)) ==
      Internals::kIsolateThreadLocalTopOffset);
  static_assert(
      static_cast<int>(OFFSET_OF(Isolate, isolate_data_.handle_scope_data_)) ==
      Internals::kIsolateHandleScopeDataOffset);
  static_assert(
      static_cast<int>(OFFSET_OF(Isolate, isolate_data_.embedder_data_)) ==
      Internals::kIsolateEmbedderDataOffset);
#ifdef V8_COMPRESS_POINTERS
  static_assert(static_cast<int>(OFFSET_OF(
                    Isolate, isolate_data_.external_pointer_table_)) ==
                Internals::kIsolateExternalPointerTableOffset);
  static_assert(static_cast<int>(OFFSET_OF(
                    Isolate, isolate_data_.shared_external_pointer_table_)) ==
                Internals::kIsolateSharedExternalPointerTableAddressOffset);
#endif
#ifdef V8_ENABLE_SANDBOX
  static_assert(
      static_cast<int>(OFFSET_OF(Isolate, isolate_data_.trusted_cage_base_)) ==
      Internals::kIsolateTrustedCageBaseOffset);
  static_assert(static_cast<int>(
                    OFFSET_OF(Isolate, isolate_data_.trusted_pointer_table_)) ==
                Internals::kIsolateTrustedPointerTableOffset);
  static_assert(static_cast<int>(OFFSET_OF(
                    Isolate, isolate_data_.shared_trusted_pointer_table_)) ==
                Internals::kIsolateSharedTrustedPointerTableAddressOffset);
  static_assert(static_cast<int>(OFFSET_OF(
                    Isolate, isolate_data_.code_pointer_table_base_address_)) ==
                Internals::kIsolateCodePointerTableBaseAddressOffset);
#endif
  static_assert(static_cast<int>(OFFSET_OF(
                    Isolate, isolate_data_.api_callback_thunk_argument_)) ==
                Internals::kIsolateApiCallbackThunkArgumentOffset);
  static_assert(
      static_cast<int>(OFFSET_OF(
          Isolate, isolate_data_.continuation_preserved_embedder_data_)) ==
      Internals::kContinuationPreservedEmbedderDataOffset);
  static_assert(static_cast<int>(OFFSET_OF(
                    Isolate, isolate_data_.js_dispatch_table_base_)) ==
                Internals::kJSDispatchTableOffset);
  static_assert(
      static_cast<int>(OFFSET_OF(Isolate, isolate_data_.roots_table_)) ==
      Internals::kIsolateRootsOffset);
  CHECK(IsAligned(reinterpret_cast<Address>(&isolate_data_),
                  kIsolateDataAlignment));
  static_assert(Internals::kStackGuardSize == sizeof(StackGuard));
  static_assert(Internals::kBuiltinTier0TableSize ==
                Builtins::kBuiltinTier0Count * kSystemPointerSize);
  static_assert(Internals::kBuiltinTier0EntryTableSize ==
                Builtins::kBuiltinTier0Count * kSystemPointerSize);
  // Ensure that certain hot IsolateData fields fall into the same CPU cache
  // line.
  constexpr size_t kCacheLineSize = 64;
  static_assert(OFFSET_OF(Isolate, isolate_data_) == 0);
  // Fields written on every CEntry/CallApiCallback/CallApiGetter call.
  // See MacroAssembler::EnterExitFrame/LeaveExitFrame.
  constexpr size_t kCEntryFPCacheLine = RoundDown<kCacheLineSize>(
      OFFSET_OF(IsolateData, thread_local_top_.c_entry_fp_));
  static_assert(kCEntryFPCacheLine ==
                RoundDown<kCacheLineSize>(
                    OFFSET_OF(IsolateData, thread_local_top_.c_function_)));
  static_assert(kCEntryFPCacheLine ==
                RoundDown<kCacheLineSize>(
                    OFFSET_OF(IsolateData, thread_local_top_.context_)));
  static_assert(
      kCEntryFPCacheLine ==
      RoundDown<kCacheLineSize>(OFFSET_OF(
          IsolateData, thread_local_top_.topmost_script_having_context_)));
  static_assert(kCEntryFPCacheLine ==
                RoundDown<kCacheLineSize>(
                    OFFSET_OF(IsolateData, thread_local_top_.last_api_entry_)));
  // Fields written on every MacroAssembler::CallCFunction call.
  static_assert(RoundDown<kCacheLineSize>(
                    OFFSET_OF(IsolateData, fast_c_call_caller_fp_)) ==
                RoundDown<kCacheLineSize>(
                    OFFSET_OF(IsolateData, fast_c_call_caller_pc_)));
  // LinearAllocationArea objects must not cross cache line boundary.
  static_assert(
      RoundDown<kCacheLineSize>(OFFSET_OF(IsolateData, new_allocation_info_)) ==
      RoundDown<kCacheLineSize>(OFFSET_OF(IsolateData, new_allocation_info_) +
                                sizeof(LinearAllocationArea) - 1));
  static_assert(
      RoundDown<kCacheLineSize>(OFFSET_OF(IsolateData, old_allocation_info_)) ==
      RoundDown<kCacheLineSize>(OFFSET_OF(IsolateData, old_allocation_info_) +
                                sizeof(LinearAllocationArea) - 1));
}
References v8::internal::IsolateData::api_callback_thunk_argument_, v8::internal::IsolateData::builtin_tier0_entry_table_, v8::internal::IsolateData::builtin_tier0_table_, v8::internal::IsolateData::cage_base_, CHECK, v8::internal::IsolateData::continuation_preserved_embedder_data_, v8::internal::IsolateData::embedder_data_, v8::internal::IsolateData::error_message_param_, v8::internal::IsolateData::fast_c_call_caller_fp_, v8::internal::IsolateData::fast_c_call_caller_pc_, v8::internal::IsolateData::handle_scope_data_, v8::internal::IsolateData::is_marking_flag_, IsAligned(), isolate_data_, v8::internal::IsolateData::js_dispatch_table_base_, v8::internal::Builtins::kBuiltinTier0Count, v8::internal::Internals::kBuiltinTier0EntryTableOffset, v8::internal::Internals::kBuiltinTier0EntryTableSize, v8::internal::Internals::kBuiltinTier0TableOffset, v8::internal::Internals::kBuiltinTier0TableSize, v8::internal::Internals::kContinuationPreservedEmbedderDataOffset, v8::internal::Internals::kErrorMessageParamOffset, v8::internal::Internals::kExternalPointerTableBasePointerOffset, v8::internal::Internals::kExternalPointerTableSize, v8::internal::Internals::kIsolateApiCallbackThunkArgumentOffset, v8::internal::Internals::kIsolateCageBaseOffset, v8::internal::kIsolateDataAlignment, v8::internal::Internals::kIsolateEmbedderDataOffset, v8::internal::Internals::kIsolateFastCCallCallerFpOffset, v8::internal::Internals::kIsolateFastCCallCallerPcOffset, v8::internal::Internals::kIsolateHandleScopeDataOffset, v8::internal::Internals::kIsolateLongTaskStatsCounterOffset, v8::internal::Internals::kIsolateRootsOffset, v8::internal::Internals::kIsolateStackGuardOffset, v8::internal::Internals::kIsolateThreadLocalTopOffset, v8::internal::Internals::kJSDispatchTableOffset, v8::internal::Internals::kNewAllocationInfoOffset, v8::internal::Internals::kOldAllocationInfoOffset, v8::internal::Internals::kStackGuardSize, v8::internal::kSystemPointerSize, v8::internal::Internals::kTrustedPointerTableBasePointerOffset, v8::internal::Internals::kTrustedPointerTableSize, v8::internal::Internals::kVariousBooleanFlagsOffset, v8::internal::IsolateData::long_task_stats_counter_, v8::internal::IsolateData::new_allocation_info_, OFFSET_OF, v8::internal::IsolateData::old_allocation_info_, v8::internal::IsolateData::roots_table_, v8::internal::IsolateData::stack_guard_, and v8::internal::IsolateData::thread_local_top_.
Referenced by Isolate().
clear_exception()
void v8::internal::Isolate::clear_exception () [inline]
Definition at line 120 of file isolate-inl.h.
                              {
  clear_internal_exception();
  if (try_catch_handler()) try_catch_handler()->Reset();
}
References clear_internal_exception(), v8::TryCatch::Reset(), and try_catch_handler().
Referenced by v8::internal::KeyAccumulator::AddKey(), v8::internal::wasm::WasmEngine::AsyncInstantiate(), v8::internal::Debug::CheckBreakPoint(), v8::internal::anonymous_namespace{wasm-debug.cc}::CheckBreakPoint(), v8::internal::anonymous_namespace{compiler.cc}::CompileScriptOnBothBackgroundAndMainThread(), v8::internal::anonymous_namespace{debug.cc}::CompileTopLevel(), v8::internal::anonymous_namespace{compiler.cc}::CompileTurbofan(), v8::internal::Genesis::ConfigureApiObject(), v8::internal::JSWrappedFunction::Create(), v8::internal::IntlMathematicalValue::From(), wasm::anonymous_namespace{c-api.cc}::GetProperException(), v8::internal::wasm::WasmInterpreterRuntime::HandleException(), Init(), InitializeThreadLocal(), v8::internal::AsmJs::InstantiateAsmWasm(), v8::internal::anonymous_namespace{execution.cc}::Invoke(), v8::internal::ErrorUtils::MakeGenericError(), v8::Context::NewRemoteContext(), v8::internal::JSPromise::Resolve(), RunHostImportModuleDynamicallyCallback(), v8::internal::RUNTIME_FUNCTION(), v8::internal::ErrorUtils::ShadowRealmConstructTypeErrorCopy(), and wasm::FuncData::v8_callback().
clear_internal_exception()
void v8::internal::Isolate::clear_internal_exception () [inline]
Definition at line 115 of file isolate-inl.h.
                                       {
  DCHECK(!IsException(thread_local_top()->exception_, this));
  thread_local_top()->exception_ = ReadOnlyRoots(this).the_hole_value();
}
References v8::internal::DCHECK(), v8::internal::ThreadLocalTop::exception_, and thread_local_top().
Referenced by CancelTerminateExecution(), clear_exception(), v8::PrepareForExecutionScope::ClearInternalException(), v8::internal::Isolate::ExceptionScope::ExceptionScope(), v8::internal::anonymous_namespace{compiler.cc}::FailAndClearException(), v8::internal::JSAsyncDisposableStack::NextDisposeAsyncIteration(), v8::Isolate::ThrowException(), and UnwindAndFindHandler().
clear_pending_message()
void v8::internal::Isolate::clear_pending_message () [inline]
Definition at line 96 of file isolate-inl.h.
                                    {
  set_pending_message(ReadOnlyRoots(this).the_hole_value());
}
References set_pending_message().
Referenced by Init(), InitializeThreadLocal(), v8::internal::anonymous_namespace{execution.cc}::Invoke(), v8::internal::ErrorUtils::MakeGenericError(), v8::internal::MoveMessageToPromise(), v8::internal::JSAsyncDisposableStack::NextDisposeAsyncIteration(), v8::internal::MessageHandler::ReportMessage(), ReportPendingMessages(), and v8::internal::ErrorUtils::ShadowRealmConstructTypeErrorCopy().
clear_topmost_script_having_context()
void v8::internal::Isolate::clear_topmost_script_having_context () [inline]
Definition at line 63 of file isolate-inl.h.
                                                  {
  static_assert(Context::kNoContext == 0);
  thread_local_top()->topmost_script_having_context_ = Context();
}
References v8::internal::Context::kNoContext, thread_local_top(), and v8::internal::ThreadLocalTop::topmost_script_having_context_.
Referenced by v8::Context::BackupIncumbentScope::BackupIncumbentScope(), v8::internal::MarkCompactCollector::ClearNonLiveReferences(), v8::internal::ExternalCallbackScope::ExternalCallbackScope(), UnwindAndFindHandler(), and v8::internal::ExternalCallbackScope::~ExternalCallbackScope().
ClearEmbeddedBlob()
void v8::internal::Isolate::ClearEmbeddedBlob () [private]
Definition at line 360 of file isolate.cc.
                                {
  CHECK(enable_embedded_blob_refcounting_);
  CHECK_EQ(embedded_blob_code_, CurrentEmbeddedBlobCode());
  CHECK_EQ(embedded_blob_code_, StickyEmbeddedBlobCode());
  CHECK_EQ(embedded_blob_data_, CurrentEmbeddedBlobData());
  CHECK_EQ(embedded_blob_data_, StickyEmbeddedBlobData());
  embedded_blob_code_ = nullptr;
  embedded_blob_code_size_ = 0;
  embedded_blob_data_ = nullptr;
  embedded_blob_data_size_ = 0;
  current_embedded_blob_code_.store(nullptr, std::memory_order_relaxed);
  current_embedded_blob_code_size_.store(0, std::memory_order_relaxed);
  current_embedded_blob_data_.store(nullptr, std::memory_order_relaxed);
  current_embedded_blob_data_size_.store(0, std::memory_order_relaxed);
  sticky_embedded_blob_code_ = nullptr;
  sticky_embedded_blob_code_size_ = 0;
  sticky_embedded_blob_data_ = nullptr;
  sticky_embedded_blob_data_size_ = 0;
}
References CHECK, CHECK_EQ, v8::internal::anonymous_namespace{isolate.cc}::current_embedded_blob_code_(), v8::internal::anonymous_namespace{isolate.cc}::current_embedded_blob_code_size_(), v8::internal::anonymous_namespace{isolate.cc}::current_embedded_blob_data_(), v8::internal::anonymous_namespace{isolate.cc}::current_embedded_blob_data_size_(), CurrentEmbeddedBlobCode(), CurrentEmbeddedBlobData(), embedded_blob_code_, embedded_blob_code_size_, embedded_blob_data_, embedded_blob_data_size_, v8::internal::anonymous_namespace{isolate.cc}::enable_embedded_blob_refcounting_, v8::internal::anonymous_namespace{isolate.cc}::sticky_embedded_blob_code_, v8::internal::anonymous_namespace{isolate.cc}::sticky_embedded_blob_code_size_, v8::internal::anonymous_namespace{isolate.cc}::sticky_embedded_blob_data_, v8::internal::anonymous_namespace{isolate.cc}::sticky_embedded_blob_data_size_, v8::internal::anonymous_namespace{isolate.cc}::StickyEmbeddedBlobCode(), and v8::internal::anonymous_namespace{isolate.cc}::StickyEmbeddedBlobData().
Referenced by TearDownEmbeddedBlob().
ClearKeptObjects()
void v8::internal::Isolate::ClearKeptObjects ()
Definition at line 6804 of file isolate.cc.
{ heap()->ClearKeptObjects(); }
References v8::internal::Heap::ClearKeptObjects(), and heap().
Referenced by v8::Isolate::ClearKeptObjects(), and v8::internal::MicrotaskQueue::PerformCheckpointInternal().
ClearSerializerData()
void v8::internal::Isolate::ClearSerializerData ()
Definition at line 4460 of file isolate.cc.
                                  {
  delete external_reference_map_;
  external_reference_map_ = nullptr;
}
Referenced by v8::Isolate::ClearCachesForTesting(), Deinit(), and v8::internal::anonymous_namespace{heap.cc}::FreeCachesOnMemoryPressure().
code_cage_base()
Address v8::internal::Isolate::code_cage_base () const [inline]
Definition at line 1237 of file isolate.h.
                                 {
#ifdef V8_EXTERNAL_CODE_SPACE
    return code_cage_base_;
#else
    return cage_base();
#endif // V8_EXTERNAL_CODE_SPACE
  }
Referenced by v8::internal::LocalIsolate::code_cage_base(), Init(), v8::internal::StackFrame::IteratePc(), and SetIsolateThreadLocals().
code_coverage_mode()
debug::CoverageMode v8::internal::Isolate::code_coverage_mode () const [inline]
Definition at line 2116 of file isolate.h.
                                               {
    return code_coverage_mode_.load(std::memory_order_relaxed);
  }
Referenced by v8::internal::anonymous_namespace{debug-coverage.cc}::CollectAndMaybeResetCounts(), v8::internal::Coverage::CollectPrecise(), and v8::internal::Coverage::SelectMode().
CollectSourcePositionsForAllBytecodeArrays()
void v8::internal::Isolate::CollectSourcePositionsForAllBytecodeArrays ()
Definition at line 7309 of file isolate.cc.
                                                         {
  if (!initialized_) return;
  HandleScope scope(this);
  std::vector<Handle<SharedFunctionInfo>> sfis;
  {
    HeapObjectIterator iterator(heap());
    for (Tagged<HeapObject> obj = iterator.Next(); !obj.is_null();
         obj = iterator.Next()) {
      if (!IsSharedFunctionInfo(obj)) continue;
      Tagged<SharedFunctionInfo> sfi = Cast<SharedFunctionInfo>(obj);
      // If the script is a Smi, then the SharedFunctionInfo is in
      // the process of being deserialized.
      Tagged<Object> script = sfi->raw_script(kAcquireLoad);
      if (IsSmi(script)) {
        DCHECK_EQ(script, Smi::uninitialized_deserialization_value());
        continue;
      }
      if (!sfi->CanCollectSourcePosition(this)) continue;
      sfis.push_back(Handle<SharedFunctionInfo>(sfi, this));
    }
  }
  for (auto sfi : sfis) {
    SharedFunctionInfo::EnsureSourcePositionsAvailable(this, sfi);
  }
}
References DCHECK_EQ, v8::internal::SharedFunctionInfo::EnsureSourcePositionsAvailable(), heap(), initialized_, v8::internal::Tagged< HeapObject >::is_null(), v8::internal::IsSmi(), v8::kAcquireLoad, v8::internal::HeapObjectIterator::Next(), v8::internal::script, and v8::internal::Smi::uninitialized_deserialization_value().
Referenced by v8::internal::Coverage::SelectMode(), v8::internal::V8FileLogger::UpdateIsLogging(), and v8::internal::Debug::UpdateState().
compilation_cache()
CompilationCache* v8::internal::Isolate::compilation_cache () [inline]
Definition at line 1206 of file isolate.h.
{ return compilation_cache_; }
Referenced by v8::Isolate::ClearCachesForTesting(), v8::internal::RegExp::Compile(), v8::internal::Heap::CreateInitialMutableObjects(), v8::internal::anonymous_namespace{heap.cc}::FreeCachesOnMemoryPressure(), v8::internal::Compiler::GetFunctionFromEval(), v8::internal::anonymous_namespace{compiler.cc}::GetSharedFunctionInfoForScriptImpl(), v8::internal::Compiler::GetSharedFunctionInfoForStreamedScript(), v8::internal::Compiler::GetWrappedFunction(), v8::internal::Heap::IterateRoots(), v8::internal::LiveEdit::PatchScript(), v8::internal::BackgroundMergeTask::SetUpOnMainThread(), v8::internal::MarkCompactCollector::StartMarking(), and v8::internal::Debug::UpdateState().
compiler_cache()
compiler::PerIsolateCompilerCache* v8::internal::Isolate::compiler_cache () const [inline]
Definition at line 2010 of file isolate.h.
                                                          {
    return compiler_cache_;
  }
Referenced by v8::internal::compiler::PerIsolateCompilerCache::Setup().
ComputeLocation()
bool v8::internal::Isolate::ComputeLocation (MessageLocation * target)
Definition at line 2964 of file isolate.cc.
                                                     {
  DebuggableStackFrameIterator it(this);
  if (it.done()) return false;
    // Compute the location from the function and the relocation info of the
    // baseline code. For optimized code this will use the deoptimization
    // information to get canonical location information.
#if V8_ENABLE_WEBASSEMBLY
  wasm::WasmCodeRefScope code_ref_scope;
#endif // V8_ENABLE_WEBASSEMBLY
  FrameSummary summary = it.GetTopValidFrame();
  Handle<SharedFunctionInfo> shared;
  Handle<Object> script = summary.script();
  if (!IsScript(*script) ||
      IsUndefined(Cast<Script>(*script)->source(), this)) {
    return false;
  }
  if (summary.IsJavaScript()) {
    shared = handle(summary.AsJavaScript().function()->shared(), this);
  }
  if (summary.AreSourcePositionsAvailable()) {
    int pos = summary.SourcePosition();
    *target = MessageLocation(Cast<Script>(script), pos, pos + 1, shared);
  } else {
    *target =
        MessageLocation(Cast<Script>(script), shared, summary.code_offset());
  }
  return true;
}
References v8::internal::FrameSummary::AreSourcePositionsAvailable(), v8::internal::FrameSummary::code_offset(), v8::internal::DebuggableStackFrameIterator::done(), v8::internal::DebuggableStackFrameIterator::GetTopValidFrame(), v8::internal::handle(), v8::internal::FrameSummary::script(), v8::internal::script, and v8::internal::FrameSummary::SourcePosition().
Referenced by CreateMessage(), and Throw().
ComputeLocationFromDetailedStackTrace()
bool v8::internal::Isolate::ComputeLocationFromDetailedStackTrace (MessageLocation * target, DirectHandle< Object > exception)
Definition at line 3037 of file isolate.cc.
                                                             {
  if (!IsJSReceiver(*exception)) return false;
  DirectHandle<StackTraceInfo> stack_trace =
      GetDetailedStackTrace(Cast<JSReceiver>(exception));
  if (stack_trace.is_null() || stack_trace->length() == 0) {
    return false;
  }
  DirectHandle<StackFrameInfo> info(stack_trace->get(0), this);
  const int pos = StackFrameInfo::GetSourcePosition(info);
  *target = MessageLocation(handle(info->script(), this), pos, pos + 1);
  return true;
}
References exception(), GetDetailedStackTrace(), v8::internal::StackFrameInfo::GetSourcePosition(), v8::internal::handle(), and v8::internal::DirectHandle< T >::is_null().
Referenced by CreateMessageFromException().
ComputeLocationFromException()
bool v8::internal::Isolate::ComputeLocationFromException (MessageLocation * target, DirectHandle< Object > exception)
Definition at line 2994 of file isolate.cc.
                                                                           {
  if (!IsJSObject(*exception)) return false;
  DirectHandle<Name> start_pos_symbol = factory()->error_start_pos_symbol();
  DirectHandle<Object> start_pos = JSReceiver::GetDataProperty(
      this, Cast<JSObject>(exception), start_pos_symbol);
  if (!IsSmi(*start_pos)) return false;
  int start_pos_value = Cast<Smi>(*start_pos).value();
  DirectHandle<Name> end_pos_symbol = factory()->error_end_pos_symbol();
  DirectHandle<Object> end_pos = JSReceiver::GetDataProperty(
      this, Cast<JSObject>(exception), end_pos_symbol);
  if (!IsSmi(*end_pos)) return false;
  int end_pos_value = Cast<Smi>(*end_pos).value();
  DirectHandle<Name> script_symbol = factory()->error_script_symbol();
  DirectHandle<Object> script = JSReceiver::GetDataProperty(
      this, Cast<JSObject>(exception), script_symbol);
  if (!IsScript(*script)) return false;
  Handle<Script> cast_script(Cast<Script>(*script), this);
  *target = MessageLocation(cast_script, start_pos_value, end_pos_value);
  return true;
}
References exception(), factory(), v8::internal::JSReceiver::GetDataProperty(), v8::internal::IsSmi(), and v8::internal::script.
Referenced by CreateMessage(), and CreateMessageFromException().
ComputeLocationFromSimpleStackTrace()
bool v8::internal::Isolate::ComputeLocationFromSimpleStackTrace (MessageLocation * target, DirectHandle< Object > exception)
Definition at line 3020 of file isolate.cc.
                                                             {
  if (!IsJSReceiver(*exception)) {
    return false;
  }
  DirectHandle<FixedArray> call_site_infos =
      GetSimpleStackTrace(Cast<JSReceiver>(exception));
  for (int i = 0; i < call_site_infos->length(); ++i) {
    DirectHandle<CallSiteInfo> call_site_info(
        Cast<CallSiteInfo>(call_site_infos->get(i)), this);
    if (CallSiteInfo::ComputeLocation(call_site_info, target)) {
      return true;
    }
  }
  return false;
}
References v8::internal::CallSiteInfo::ComputeLocation(), exception(), GetSimpleStackTrace(), and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by CreateMessage().
concurrent_recompilation_enabled()
bool v8::internal::Isolate::concurrent_recompilation_enabled () [inline]
Definition at line 1745 of file isolate.h.
                                          {
    // Thread is only available with flag enabled.
    DCHECK(optimizing_compile_dispatcher_ == nullptr ||
           v8_flags.concurrent_recompilation);
    return optimizing_compile_dispatcher_ != nullptr;
  }
References v8::internal::DCHECK(), and v8::internal::v8_flags.
Referenced by AbortConcurrentOptimization(), v8::internal::Compiler::Compile(), v8::internal::Compiler::CompileOptimized(), v8::internal::anonymous_namespace{runtime-compiler.cc}::CompileOptimizedOSR(), v8::internal::anonymous_namespace{runtime-compiler.cc}::CompileOptimizedOSRFromMaglev(), Deinit(), v8::internal::anonymous_namespace{runtime-test.cc}::FinalizeOptimization(), v8::internal::StackGuard::HandleInterrupts(), v8::internal::anonymous_namespace{runtime-test.cc}::OptimizeFunctionOnNextCall(), v8::internal::JSFunction::RequestOptimization(), v8::Shell::RunMain(), v8::internal::Code::SetMarkedForDeoptimization(), and v8::internal::anonymous_namespace{compiler.cc}::SpawnDuplicateConcurrentJobForStressTesting().
console_delegate()
debug::ConsoleDelegate* v8::internal::Isolate::console_delegate () [inline]
Definition at line 1060 of file isolate.h.
{ return console_delegate_; }
Referenced by v8::internal::anonymous_namespace{builtins-console.cc}::ConsoleCall(), v8::Shell::ProfilerTriggerSample(), and v8::Shell::ResetOnProfileEndListener().
context()
Tagged<Context> v8::internal::Isolate::context () const [inline]
Definition at line 815 of file isolate.h.
{ return thread_local_top()->context_; }
Referenced by AddDetachedContext(), v8::internal::wasm::WasmExecutionTimer::AddSample(), v8::internal::anonymous_namespace{runtime-wasm.cc}::AllocateFeedbackVector(), v8::internal::wasm::WasmEngine::AsyncCompile(), v8::internal::BUILTIN(), v8::internal::anonymous_namespace{isolate.cc}::CallsCatchMethod(), CheckDetachedContextsAfterGC(), v8::internal::Genesis::CompileExtension(), v8::internal::CompileGlobalEval(), v8::Isolate::ContextDisposedNotification(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::ConvertElementsWithCapacity(), v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::CopyElementsHandleImpl(), CountUsage(), v8::internal::anonymous_namespace{builtins-intl.cc}::CreateBoundFunction(), v8::internal::anonymous_namespace{runtime-scopes.cc}::DeclareEvalHelper(), v8::internal::DEF_HEAP_OBJECT_PREDICATE(), v8::Context::Enter(), v8::internal::anonymous_namespace{accessors.cc}::FindCaller(), v8::internal::wasm::AsyncCompileJob::FinishCompile(), v8::internal::FunctionCallbackArguments::FunctionCallbackArguments(), v8::internal::anonymous_namespace{ic.cc}::GetCloneModeForMapPreCheck(), v8::internal::anonymous_namespace{ic.cc}::GetCloneTargetMap(), v8::internal::anonymous_namespace{gc-tracer.cc}::GetContextId(), v8::Isolate::GetCurrentContext(), v8::internal::JSReceiver::GetDataProperty(), v8::internal::JSFunction::GetDerivedRabGsabDataViewMap(), v8::internal::JSFunction::GetDerivedRabGsabTypedArrayMap(), GetIncumbentContextSlow(), GetOrRegisterRecorderContextId(), v8::internal::Map::GetPrototypeChainRootMap(), v8::internal::Object::GetPrototypeChainRootMap(), v8::internal::GetShouldThrow(), v8::internal::TickSample::GetStackSample(), global_object(), global_proxy(), v8::Isolate::InContext(), InstallConditionalFeatures(), v8::internal::anonymous_namespace{execution.cc}::Invoke(), IsSharedArrayBufferConstructorEnabled(), IsWasmImportedStringsEnabled(), IsWasmJSPIEnabled(), IsWasmJSPIRequested(), IsWasmStringRefEnabled(), v8::internal::anonymous_namespace{runtime-scopes.cc}::LoadLookupSlot(), native_context(), v8::internal::anonymous_namespace{execution.cc}::NewScriptContext(), v8::internal::anonymous_namespace{runtime-scopes.cc}::NewSloppyArguments(), v8::internal::FrameFunctionIterator::next(), v8::internal::Intl::NumberToLocaleString(), v8::internal::StringStream::PrintPrototype(), raw_native_context(), ReportFailedAccessCheck(), RestoreThread(), RunPrepareStackTraceCallback(), v8::internal::RUNTIME_FUNCTION(), v8::internal::SaveContext::SaveContext(), set_context(), set_topmost_script_having_context(), v8::internal::anonymous_namespace{builtins-array.cc}::Slow_ArrayConcat(), v8::internal::Intl::StringLocaleCompare(), v8::internal::JSDateTimeFormat::TemporalToLocaleString(), v8::internal::anonymous_namespace{runtime-wasm.cc}::ThrowTableOutOfBounds(), v8::internal::JSDateTimeFormat::ToLocaleDateTime(), v8::internal::Map::TransitionElementsTo(), v8::internal::anonymous_namespace{builtins-atomics-synchronization.cc}::UnlockAsyncLockedMutexFromPromiseHandler(), UnwindAndFindHandler(), v8::internal::JSDateTimeFormat::UnwrapDateTimeFormat(), v8::internal::JSNumberFormat::UnwrapNumberFormat(), v8::internal::anonymous_namespace{isolate.cc}::VisitStack(), and v8::internal::anonymous_namespace{isolate.cc}::WalkPromiseTreeInternal().
context_address()
Tagged<Context>* v8::internal::Isolate::context_address () [inline]
Definition at line 817 of file isolate.h.
{ return &thread_local_top()->context_; }
context_offset()
constexpr static uint32_t v8::internal::Isolate::context_offset () [inline], [static], [constexpr]
Definition at line 1366 of file isolate.h.
                                             {
    return static_cast<uint32_t>(
        OFFSET_OF(Isolate, isolate_data_) +
        OFFSET_OF(IsolateData, thread_local_top_) +
        OFFSET_OF(ThreadLocalTop, context_) -
        isolate_root_bias());
  }
References OFFSET_OF.
Referenced by v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildJSFastApiCallWrapper(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi().
continuation_preserved_embedder_data_address()
Address v8::internal::Isolate::continuation_preserved_embedder_data_address () [inline]
Definition at line 2319 of file isolate.h.
                                                         {
    return reinterpret_cast<Address>(
        &isolate_data_.continuation_preserved_embedder_data_);
  }
Referenced by Iterate().
counters()
Counters* v8::internal::Isolate::counters () [inline]
Definition at line 1195 of file isolate.h.
{ return async_counters().get(); }
Referenced by v8::internal::wasm::WasmEngine::AddIsolate(), v8::internal::ExternalReferenceTable::AddNativeCodeStatsCounters(), v8::internal::BackingStore::Allocate(), v8::internal::wasm::InstanceBuilder::Build(), v8::Function::Call(), v8::Object::CallAsConstructor(), v8::Object::CallAsFunction(), v8::internal::MarkCompactCollector::ClearNonLiveReferences(), v8::internal::Compiler::CollectSourcePositions(), v8::internal::Compiler::Compile(), v8::internal::compiler::CompileCWasmEntry(), v8::internal::wasm::CompileLazy(), v8::internal::anonymous_namespace{compiler.cc}::CompileMaglev(), v8::internal::anonymous_namespace{compiler.cc}::CompileToplevel(), v8::internal::anonymous_namespace{compiler.cc}::CompileTurbofan_NotConcurrent(), v8::internal::wasm::WasmImportWrapperCache::CompileWasmJsFastCallWrapper(), v8::internal::wasm::WasmImportWrapperCache::CompileWrapper(), v8::internal::ProfilerCodeObserver::CreateEntriesForRuntimeCallStats(), v8::internal::wasm::AsyncStreamingProcessor::Deserialize(), v8::internal::CodeSerializer::Deserialize(), v8::internal::ContextDeserializer::DeserializeContext(), v8::internal::wasm::DeserializeNativeModule(), DetachGlobal(), v8::internal::Deoptimizer::DoComputeOutputFrames(), DumpAndResetStats(), v8::internal::GlobalSafepoint::EnterGlobalSafepointScope(), v8::Module::Evaluate(), v8::internal::anonymous_namespace{runtime-regexp.cc}::ExperimentalOneshotExec(), v8::internal::wasm::JSToWasmWrapperCompilationUnit::Finalize(), v8::internal::compiler::CodeAssemblerTurboshaftCompilationJob::FinalizeCode(), v8::internal::compiler::PipelineCompilationJob::FinalizeJobImpl(), v8::internal::wasm::AsyncCompileJob::FinishCompile(), v8::internal::CodeSerializer::FinishOffThreadDeserialize(), v8::internal::CodeStubAssembler::Float64ToString(), v8::internal::Heap::GarbageCollectionEpilogue(), v8::internal::compiler::Pipeline::GenerateCodeForTesting(), v8::internal::compiler::Pipeline::GenerateCodeForTurboshaftBuiltin(), v8::internal::compiler::Pipeline::GenerateTurboshaftCodeForTesting(), v8::internal::SmiStringCache::Get(), v8::internal::DoubleStringCache::Get(), v8::internal::anonymous_namespace{compiler.cc}::ScriptCompileTimerScope::GetCacheBehaviourTimedHistogram(), v8::internal::StatisticsExtension::GetCounters(), v8::internal::anonymous_namespace{keys.cc}::GetFastEnumPropertyKeys(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::GetOrCompileNewNativeModule(), v8::internal::anonymous_namespace{compiler.cc}::GetSharedFunctionInfoForScriptImpl(), v8::internal::TickSample::GetStackSample(), v8::internal::Compiler::GetWrappedFunction(), v8::internal::StackGuard::HandleInterrupts(), v8::internal::FastKeyAccumulator::InitializeFastPropertyEnumCache(), v8::internal::CompilationCacheEval::Lookup(), v8::internal::CompilationCacheRegExp::Lookup(), v8::internal::CompilationCacheScript::Lookup(), v8::Isolate::LowMemoryNotification(), v8::internal::Heap::MarkCompactEpilogue(), v8::internal::MaybeDecompress(), v8::Function::NewInstanceWithSideEffectType(), v8::internal::Factory::NewMapImpl(), v8::internal::wasm::WasmEngine::NewNativeModule(), v8::internal::Debug::NotifyDebuggerPausedEventSent(), v8::internal::wasm::AsyncStreamingProcessor::OnFinishedStream(), v8::internal::Heap::PerformGarbageCollection(), v8::internal::compiler::CodeAssemblerCompilationJob::PrepareJobImpl(), v8::internal::compiler::PipelineCompilationJob::PrepareJobImpl(), v8::internal::compiler::CodeAssembler::BuiltinCompilationScheduler::QueueJob(), v8::internal::anonymous_namespace{regexp-interpreter.cc}::RawMatch(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::RecordCompilationMethod(), v8::internal::TurbofanCompilationJob::RecordCompilationStats(), v8::internal::GCTracer::RecordGCPhasesHistograms(), v8::internal::AsmJsCompilationJob::RecordHistograms(), v8::internal::anonymous_namespace{backing-store.cc}::RecordStatus(), v8::internal::anonymous_namespace{runtime-regexp.cc}::RegExpExec(), v8::internal::wasm::WasmEngine::ReportLiveCodeForGC(), v8::internal::MemoryMeasurement::ReportResults(), v8::Script::Run(), v8::internal::RUNTIME_FUNCTION(), v8::internal::V8FileLogger::RuntimeCallTimerEvent(), v8::internal::GCTracer::Scope::Scope(), v8::internal::Heap::SelectGarbageCollector(), v8::internal::CodeSerializer::Serialize(), v8::internal::StubCache::Set(), v8::Isolate::SetCounterFunction(), v8::Isolate::SetCreateHistogramFunction(), v8::internal::CodeStubAssembler::SmiToString(), v8::internal::wasm::AsyncCompileJob::Start(), v8::internal::IncrementalMarking::Start(), v8::internal::MinorMarkSweepCollector::StartSweepNewSpace(), v8::internal::MinorMarkSweepCollector::StartSweepNewSpaceWithStickyBits(), v8::internal::GCTracer::StopCycle(), v8::internal::CollectionBarrier::StopTimeToCollectionTimer(), v8::internal::wasm::WasmEngine::SyncCompile(), v8::internal::wasm::WasmEngine::SyncCompileTranslatedAsmJs(), v8::internal::wasm::WasmEngine::SyncValidate(), v8::internal::wasm::TierUpNowForTesting(), and v8::internal::AccessorAssembler::TryProbeStubCache().
CountUsage() [1/2]
void v8::internal::Isolate::CountUsage (base::Vector< const v8::Isolate::UseCounterFeature > features)
Definition at line 7157 of file isolate.cc.
                                                           {
  // The counter callback
  // - may cause the embedder to call into V8, which is not generally possible
  // during GC.
  // - requires a current native context, which may not always exist.
  // TODO(jgruber): Consider either removing the native context requirement in
  // blink, or passing it to the callback explicitly.
  if (heap_.gc_state() == Heap::NOT_IN_GC && !context().is_null()) {
    DCHECK(IsContext(context()));
    DCHECK(IsNativeContext(context()->native_context()));
    if (use_counter_callback_) {
      HandleScope handle_scope(this);
      for (auto feature : features) {
        use_counter_callback_(reinterpret_cast<v8::Isolate*>(this), feature);
      }
    }
  } else {
    heap_.IncrementDeferredCounts(features);
  }
}
References context(), v8::internal::DCHECK(), v8::internal::Heap::gc_state(), heap_, v8::internal::Heap::IncrementDeferredCounts(), native_context(), v8::internal::Heap::NOT_IN_GC, and use_counter_callback_.
CountUsage() [2/2]
void v8::internal::Isolate::CountUsage (v8::Isolate::UseCounterFeature feature)
Definition at line 7153 of file isolate.cc.
                                                           {
  CountUsage(base::VectorOf({feature}));
}
References v8::base::VectorOf().
Referenced by v8::internal::BUILTIN(), v8::internal::Heap::CollectGarbage(), v8::internal::anonymous_namespace{compiler.cc}::CompileTurbofan(), v8::internal::JSDateTimeFormat::CreateDateTimeFormat(), v8::internal::anonymous_namespace{builtins-function.cc}::CreateDynamicFunction(), v8::internal::wasm::AsyncCompileJob::CreateNativeModule(), v8::internal::anonymous_namespace{builtins-intl.cc}::DisallowCallConstructor(), v8::internal::TranslatedState::DoUpdateFeedback(), v8::internal::LookupIterator::ExtendingNonExtensible(), v8::internal::JSDateTimeFormat::FormatRange(), v8::internal::JSDateTimeFormat::FormatRangeToParts(), v8::internal::ErrorUtils::FormatStackTrace(), GetStackTraceLimit(), v8::internal::LookupIterator::InternalUpdateProtector(), v8::internal::anonymous_namespace{builtins-intl.cc}::LegacyFormatConstructor(), v8::internal::JSV8BreakIterator::New(), v8::internal::JSNumberFormat::New(), v8::internal::anonymous_namespace{builtins-object.cc}::ObjectDefineAccessor(), v8::internal::DateParser::Parse(), v8::internal::wasm::PublishDetectedFeatures(), v8::debug::RecordAsyncStackTaggingCreateTaskCall(), v8::internal::BackgroundCompileTask::ReportStatistics(), v8::internal::Heap::ReportStatisticsAfterGC(), v8::internal::RUNTIME_FUNCTION(), v8::internal::JSArrayBuffer::Setup(), v8::internal::JSFunction::ToString(), v8::internal::LookupIterator::TransitionToAccessorPair(), UpdateNoElementsProtectorOnSetElement(), v8::internal::Parser::UpdateStatistics(), and v8::internal::Object::WriteToReadOnlyProperty().
CreateAndSetEmbeddedBlob()
void v8::internal::Isolate::CreateAndSetEmbeddedBlob () [private]
Definition at line 5205 of file isolate.cc.
                                       {
  base::MutexGuard guard(current_embedded_blob_refcount_mutex_.Pointer());
  PrepareBuiltinSourcePositionMap();
  // If a sticky blob has been set, we reuse it.
  if (StickyEmbeddedBlobCode() != nullptr) {
    CHECK_EQ(embedded_blob_code(), StickyEmbeddedBlobCode());
    CHECK_EQ(embedded_blob_data(), StickyEmbeddedBlobData());
    CHECK_EQ(CurrentEmbeddedBlobCode(), StickyEmbeddedBlobCode());
    CHECK_EQ(CurrentEmbeddedBlobData(), StickyEmbeddedBlobData());
  } else {
    // Create and set a new embedded blob.
    uint8_t* code;
    uint32_t code_size;
    uint8_t* data;
    uint32_t data_size;
    OffHeapInstructionStream::CreateOffHeapOffHeapInstructionStream(
        this, &code, &code_size, &data, &data_size);
    CHECK_EQ(0, current_embedded_blob_refs_);
    const uint8_t* const_code = const_cast<const uint8_t*>(code);
    const uint8_t* const_data = const_cast<const uint8_t*>(data);
    SetEmbeddedBlob(const_code, code_size, const_data, data_size);
    current_embedded_blob_refs_++;
    SetStickyEmbeddedBlob(code, code_size, data, data_size);
  }
  MaybeRemapEmbeddedBuiltinsIntoCodeRange();
  FinalizeBuiltinCodeObjects(this);
}
References CHECK_EQ, code, v8::internal::OffHeapInstructionStream::CreateOffHeapOffHeapInstructionStream(), v8::internal::anonymous_namespace{isolate.cc}::current_embedded_blob_refcount_mutex_, v8::internal::anonymous_namespace{isolate.cc}::current_embedded_blob_refs_, CurrentEmbeddedBlobCode(), CurrentEmbeddedBlobData(), embedded_blob_code(), embedded_blob_data(), v8::internal::anonymous_namespace{isolate.cc}::FinalizeBuiltinCodeObjects(), MaybeRemapEmbeddedBuiltinsIntoCodeRange(), v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Pointer(), PrepareBuiltinSourcePositionMap(), SetEmbeddedBlob(), v8::internal::anonymous_namespace{isolate.cc}::SetStickyEmbeddedBlob(), v8::internal::anonymous_namespace{isolate.cc}::StickyEmbeddedBlobCode(), and v8::internal::anonymous_namespace{isolate.cc}::StickyEmbeddedBlobData().
Referenced by Init().
CreateMessage()
Handle< JSMessageObject > v8::internal::Isolate::CreateMessage (DirectHandle< Object > exception, MessageLocation * location)
Definition at line 3053 of file isolate.cc.
                                                                          {
  DirectHandle<StackTraceInfo> stack_trace;
  if (capture_stack_trace_for_uncaught_exceptions_) {
    if (IsJSObject(*exception)) {
      // First, check whether a stack trace is already present on this object.
      // It maybe an Error, or the embedder may have stored a stack trace using
      // Exception::CaptureStackTrace().
      // If the lookup fails, we fall through and capture the stack trace
      // at this throw site.
      stack_trace = GetDetailedStackTrace(Cast<JSObject>(exception));
    }
    if (stack_trace.is_null()) {
      // Not an error object, we capture stack and location at throw site.
      stack_trace = CaptureDetailedStackTrace(
          stack_trace_for_uncaught_exceptions_frame_limit_,
          stack_trace_for_uncaught_exceptions_options_);
    }
  }
  MessageLocation computed_location;
  if (location == nullptr &&
      (ComputeLocationFromException(&computed_location, exception) ||
       ComputeLocationFromSimpleStackTrace(&computed_location, exception) ||
       ComputeLocation(&computed_location))) {
    location = &computed_location;
  }
  return MessageHandler::MakeMessageObject(this,
                                           MessageTemplate::kUncaughtException,
                                           location, exception, stack_trace);
}
References capture_stack_trace_for_uncaught_exceptions_, CaptureDetailedStackTrace(), ComputeLocation(), ComputeLocationFromException(), ComputeLocationFromSimpleStackTrace(), exception(), GetDetailedStackTrace(), v8::internal::DirectHandle< T >::is_null(), v8::internal::MessageHandler::MakeMessageObject(), stack_trace_for_uncaught_exceptions_frame_limit_, and stack_trace_for_uncaught_exceptions_options_.
Referenced by v8::Exception::CreateMessage(), and CreateMessageOrAbort().
CreateMessageFromException()
Handle< JSMessageObject > v8::internal::Isolate::CreateMessageFromException (DirectHandle< Object > exception)
Definition at line 3085 of file isolate.cc.
                                    {
  DirectHandle<StackTraceInfo> stack_trace;
  if (IsJSError(*exception)) {
    stack_trace = GetDetailedStackTrace(Cast<JSObject>(exception));
  }
  MessageLocation* location = nullptr;
  MessageLocation computed_location;
  if (ComputeLocationFromException(&computed_location, exception) ||
      ComputeLocationFromDetailedStackTrace(&computed_location, exception)) {
    location = &computed_location;
  }
  return MessageHandler::MakeMessageObject(this,
                                           MessageTemplate::kPlaceholderOnly,
                                           location, exception, stack_trace);
}
References ComputeLocationFromDetailedStackTrace(), ComputeLocationFromException(), exception(), GetDetailedStackTrace(), and v8::internal::MessageHandler::MakeMessageObject().
Referenced by v8::debug::CreateMessageFromException().
CreateMessageOrAbort()
DirectHandle< JSMessageObject > v8::internal::Isolate::CreateMessageOrAbort (DirectHandle< Object > exception, MessageLocation * location)
Definition at line 2065 of file isolate.cc.
                                                               {
  DirectHandle<JSMessageObject> message_obj =
      CreateMessage(exception, location);
  // If the abort-on-uncaught-exception flag is specified, and if the
  // embedder didn't specify a custom uncaught exception callback,
  // or if the custom callback determined that V8 should abort, then
  // abort.
  // Cache the flag on a static so that we can modify the value looked up below
  // in the presence of read-only flags.
  static bool abort_on_uncaught_exception =
      v8_flags.abort_on_uncaught_exception;
  if (abort_on_uncaught_exception) {
    CatchType prediction = PredictExceptionCatcher();
    if ((prediction == NOT_CAUGHT || prediction == CAUGHT_BY_EXTERNAL) &&
        (!abort_on_uncaught_exception_callback_ ||
         abort_on_uncaught_exception_callback_(
             reinterpret_cast<v8::Isolate*>(this)))) {
      // Prevent endless recursion.
      abort_on_uncaught_exception = false;
      // This flag is intended for use by JavaScript developers, so
      // print a user-friendly stack trace (not an internal one).
      PrintF(stderr, "%s\n\nFROM\n",
             MessageHandler::GetLocalizedMessage(this, message_obj).get());
      std::ostringstream stack_trace_stream;
      PrintCurrentStackTrace(stack_trace_stream);
      PrintF(stderr, "%s", stack_trace_stream.str().c_str());
      base::OS::Abort();
    }
  }
  return message_obj;
}
References v8::base::OS::Abort(), abort_on_uncaught_exception_callback_, CAUGHT_BY_EXTERNAL, CreateMessage(), exception(), v8::internal::MessageHandler::GetLocalizedMessage(), NOT_CAUGHT, PredictExceptionCatcher(), PrintCurrentStackTrace(), v8::internal::PrintF(), and v8::internal::v8_flags.
Referenced by v8::internal::RUNTIME_FUNCTION(), and Throw().
Current()
Isolate * v8::internal::Isolate::Current () [inline], [static]
Definition at line 35 of file isolate-inl.h.
                                    {
  Isolate* isolate = TryGetCurrent();
  DCHECK_NOT_NULL(isolate);
  return isolate;
}
References DCHECK_NOT_NULL, and v8::internal::Factory::isolate().
Referenced by _v8_internal_Print_Code(), _v8_internal_Print_OnlyCode(), _v8_internal_Print_StackTrace(), _v8_internal_Print_TransitionTree(), v8::internal::WasmScript::AddBreakpointToInfo(), v8::internal::wasm::NativeModule::AddCodeForTesting(), v8::internal::anonymous_namespace{compilation-cache-table.cc}::AddToJSFunctionMap(), v8::internal::wasm::gdb_server::GdbServer::AddWasmModule(), v8::Context::AllowCodeGenerationFromStrings(), v8::internal::wasm::array_copy_wrapper(), v8::internal::wasm::array_fill_wrapper(), v8::Map::AsArray(), v8::Set::AsArray(), v8::Context::BackupIncumbentScope::BackupIncumbentScope(), v8::ArrayBufferView::Buffer(), v8::WasmMemoryObject::Buffer(), v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildJSFastApiCallWrapper(), v8::Object::CallAsConstructor(), v8::Object::CallAsFunction(), v8::debug::CallFunctionOn(), v8::internal::MutableBigInt::Canonicalize(), v8::Exception::CaptureStackTrace(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::CheckForWellKnownImport(), v8::Map::Clear(), v8::Set::Clear(), v8::internal::WasmScript::ClearAllBreakpoints(), v8::internal::WasmScript::ClearBreakPoint(), v8::internal::WasmScript::ClearBreakPointById(), v8::internal::BreakIterator::ClearDebugBreak(), v8::internal::WasmTableObject::ClearDispatchTable(), v8::Object::Clone(), v8::internal::wasm::ResolvedWasmImport::ComputeKind(), v8::internal::CallSiteInfo::ComputeLocation(), v8::internal::CallSiteInfo::ComputeSourcePosition(), v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::CopyElementsHandleSlow(), v8::debug::PropertyIterator::Create(), v8::ScriptCompiler::CreateCodeCacheForFunction(), v8::Object::CreateDataProperty(), v8::debug::Script::DebugId(), v8::internal::DebugScope::DebugScope(), v8::Context::DeepFreeze(), v8::internal::DEF_HEAP_OBJECT_PREDICATE(), v8::internal::JSObject::DefineOwnAccessorIgnoreAttributes(), v8::Object::DefineOwnProperty(), v8::Object::DefineProperty(), v8::internal::JSObject::DefinePropertyOrElementIgnoreAttributes(), v8::internal::JSWeakCollection::Delete(), v8::Map::Delete(), v8::Set::Delete(), v8::Object::Delete(), v8::internal::JSReceiver::DeleteNormalizedProperty(), v8::Object::DeletePrivate(), v8::internal::JSProxy::DeletePropertyOrElement(), v8::internal::Deoptimizer::DeoptimizeFunction(), v8::internal::JSArrayBuffer::Detach(), v8::ArrayBuffer::Detach(), v8::Context::DetachGlobal(), v8::EmbedderDataFor(), v8::debug::Script::EndColumn(), v8::debug::Script::EndLine(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::EnforceBigIntUint64(), v8::Context::Enter(), Enter(), v8::Value::Equals(), v8::internal::Context::ErrorMessageForCodeGenerationFromStrings(), v8::internal::Context::ErrorMessageForWasmCodeGeneration(), v8::Module::Evaluate(), v8::Context::Exit(), v8::Function::Experimental_IsNopFunction(), v8::internal::V8HeapExplorer::ExtractPropertyReferences(), v8::Object::FindInstanceInPrototypeChain(), v8::internal::JSPromise::Fulfill(), v8::debug::GeneratorObject::Function(), v8::Message::Get(), v8::FixedArray::Get(), v8::Function::GetBoundFunction(), v8::internal::BreakIterator::GetBreakLocation(), v8::internal::JSMessageObject::GetColumnNumber(), v8::internal::CallSiteInfo::GetColumnNumber(), v8::WasmModuleObject::GetCompiledModule(), v8::Script::GetCompileHintsCollector(), v8::Object::GetConstructorName(), v8::internal::JSReceiver::GetContextForMicrotask(), v8::metrics::Recorder::GetContextId(), v8::debug::GetContextId(), v8::Object::GetCreationContext(), v8::Object::GetCreationContextChecked(), v8::Isolate::GetCurrent(), v8::Context::GetDataFromSnapshotOnce(), v8::debug::GetDateDescription(), v8::internal::BreakIterator::GetDebugBreakType(), v8::debug::GetDebuggingId(), v8::Function::GetDebugName(), v8::internal::CallSiteInfo::GetEnclosingColumnNumber(), v8::internal::CallSiteInfo::GetEnclosingLineNumber(), v8::Message::GetEndColumn(), v8::Message::GetEndPosition(), v8::internal::JSWeakCollection::GetEntries(), v8::internal::CallSiteInfo::GetEvalOrigin(), v8::Module::GetException(), v8::anonymous_namespace{api.cc}::GetExternalResourceFromForwardingTable(), v8::Context::GetExtrasBindingObject(), v8::internal::CallSiteInfo::GetFunctionDebugName(), v8::debug::GetFunctionDescription(), v8::StackFrame::GetFunctionName(), v8::internal::CallSiteInfo::GetFunctionName(), v8::internal::JavaScriptFrame::GetFunctions(), v8::Proxy::GetHandler(), v8::Value::GetHash(), v8::Object::GetIdentityHash(), v8::ModuleRequest::GetImportAttributes(), v8::Function::GetInferredName(), v8::internal::JSMessageObject::GetLineNumber(), v8::internal::CallSiteInfo::GetLineNumber(), v8::Message::GetLineNumber(), v8::StackFrame::GetLocation(), v8::debug::GetMessageFromPromise(), v8::internal::CallSiteInfo::GetMethodName(), v8::internal::compiler::GetModuleContext(), v8::Module::GetModuleNamespace(), v8::Module::GetModuleRequests(), v8::Function::GetName(), v8::internal::anonymous_namespace{debug-property-iterator.cc}::GetNativeAccessorDescriptorInternal(), v8::internal::WasmInternalFunction::GetOrCreateExternal(), v8::internal::Script::GetPositionInfo(), v8::debug::Script::GetPossibleBreakpoints(), v8::debug::GetPrivateMembers(), v8::Script::GetProducedCompileHints(), v8::Object::GetPropertyAttributes(), v8::internal::Object::GetPropertyWithDefinedGetter(), v8::internal::JSProxy::GetPrototype(), v8::Object::GetPrototypeV2(), v8::internal::Name::GetRawHashFromForwardingTable(), v8::Object::GetRealNamedPropertyAttributes(), v8::Object::GetRealNamedPropertyAttributesInPrototypeChain(), v8::internal::WasmGlobalObject::GetRef(), v8::Script::GetResourceName(), v8::internal::CallSiteInfo::GetScript(), v8::Function::GetScriptColumnNumber(), v8::internal::CallSiteInfo::GetScriptHash(), v8::Function::GetScriptLineNumber(), v8::Function::GetScriptLocation(), v8::StackFrame::GetScriptName(), v8::internal::CallSiteInfo::GetScriptName(), v8::StackFrame::GetScriptNameOrSourceURL(), v8::internal::CallSiteInfo::GetScriptNameOrSourceURL(), v8::Function::GetScriptOrigin(), v8::Message::GetScriptOrigin(), v8::StackFrame::GetScriptSource(), v8::internal::CallSiteInfo::GetScriptSource(), v8::StackFrame::GetScriptSourceMappingURL(), v8::internal::CallSiteInfo::GetScriptSourceMappingURL(), v8::Context::GetSecurityToken(), v8::debug::Script::GetSha256Hash(), v8::RegExp::GetSource(), v8::internal::JSMessageObject::GetSource(), v8::Message::GetSource(), v8::internal::JSMessageObject::GetSourceLine(), v8::Message::GetSourceLine(), v8::debug::Script::GetSourceOffset(), v8::internal::StackFrameInfo::GetSourcePosition(), v8::ModuleRequest::GetSpecifier(), v8::Message::GetStackTrace(), v8::Exception::GetStackTrace(), v8::Message::GetStartColumn(), v8::Message::GetStartPosition(), v8::Proxy::GetTarget(), v8::debug::AccessorPair::getter(), v8::internal::CallSiteInfo::GetTypeName(), v8::Module::GetUnboundModuleScript(), v8::Script::GetUnboundScript(), v8::Message::GetWasmFunctionIndex(), v8::Context::Global(), v8::debug::GlobalLexicalScopeNames(), v8::Map::Has(), v8::Set::Has(), v8::Object::Has(), v8::internal::JSObject::HasEnumerableElements(), v8::Promise::HasHandler(), v8::FunctionTemplate::HasInstance(), v8::Object::HasOwnProperty(), v8::internal::JSArray::HasReadOnlyLengthSlowPath(), v8::Object::HasRealIndexedProperty(), v8::Object::HasRealNamedCallbackProperty(), v8::Object::HasRealNamedProperty(), v8::internal::HoleyElementsUsage(), Init(), v8::anonymous_namespace{d8.cc}::InitializeModuleEmbedderData(), v8::Value::InstanceOf(), v8::Module::InstantiateModule(), v8::internal::ApiNatives::InstantiateRemoteObject(), v8::Value::Int32Value(), v8::Value::IntegerValue(), v8::internal::JSGlobalObject::InvalidatePropertyCell(), v8::internal::InvokeFinalizationRegistryCleanupFromTask(), v8::internal::maglev::MaglevCompilationInfo::is_detached(), v8::internal::JSProxy::IsArray(), v8::Context::IsCodeGenerationFromStringsAllowed(), v8::internal::JSProxy::IsExtensible(), v8::Module::IsGraphAsync(), v8::internal::AllocationSite::IsNested(), v8::Message::IsOpaque(), v8::Message::IsSharedCrossOrigin(), v8::Array::Iterate(), v8::internal::Object::IterationHasObservableEffects(), v8::internal::Context::Lookup(), v8::internal::CompilationCacheTable::LookupEval(), v8::internal::CompilationCacheTable::LookupRegExp(), v8::internal::Map::MapPrint(), v8::ObjectTemplate::MarkAsUndetectable(), v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::MaybeUnparkForPrint::MaybeUnparkForPrint(), v8::internal::JSObject::MigrateSlowToFast(), v8::debug::Script::Name(), v8::internal::JSObject::New(), v8::internal::WasmInterpreterObject::New(), v8::DataView::New(), v8::Float16Array::New(), v8::Function::New(), v8::BigInt::NewFromWords(), v8::internal::DictionaryTemplateInfo::NewInstance(), v8::DictionaryTemplate::NewInstance(), v8::Function::NewInstanceWithSideEffectType(), v8::Value::NumberValue(), v8::ObjectSetAccessor(), v8::anonymous_namespace{api.cc}::ObjectTemplateSetNamedPropertyHandler(), v8::internal::JSObject::OptimizeAsPrototype(), v8::internal::JSProxy::PreventExtensions(), v8::Object::PreviewEntries(), v8::internal::JSObject::PrintElementsTransition(), v8::internal::JSObject::PrintInstanceMigration(), v8::internal::StringStream::PrintObject(), v8::internal::PrototypeBenefitsFromNormalization(), v8::internal::CompilationCacheTable::PutEval(), v8::HeapProfiler::QueryObjects(), v8::ValueDeserializer::ReadHeader(), v8::internal::JSPromise::Reject(), v8::Promise::Resolver::Reject(), v8::internal::WeakArrayList::RemoveOne(), v8::internal::anonymous_namespace{asm-js.cc}::Report(), v8::internal::anonymous_namespace{isolate.cc}::ReportBootstrappingException(), v8::internal::JSObject::RequireSlowElements(), v8::internal::JSPromise::Resolve(), v8::Promise::Resolver::Resolve(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::ResolveBoundJSFastApiFunction(), v8::internal::wasm::ResolvedWasmImport::ResolvedWasmImport(), v8::Promise::Result(), v8::internal::JSProxy::Revoke(), v8::Script::Run(), v8::internal::wasm::Handlers< Compressed >::s2s_RefStructGet(), v8::internal::wasm::Handlers< Compressed >::s2s_Throw(), v8::debug::GeneratorObject::Script(), v8::internal::JSWeakCollection::Set(), v8::Object::Set(), v8::internal::AllocationSite::set_memento_found_count(), v8::Context::SetAbortScriptExecution(), v8::ObjectTemplate::SetAccessCheckCallback(), v8::ObjectTemplate::SetAccessCheckCallbackAndHandler(), v8::internal::JSObject::SetAccessor(), v8::Object::SetAccessorProperty(), v8::Context::SetAlignedPointerInEmbedderData(), v8::Object::SetAlignedPointerInInternalField(), v8::Object::SetAlignedPointerInInternalFields(), v8::internal::anonymous_namespace{wasm-debug.cc}::SetBreakOnEntryFlag(), v8::debug::Script::SetBreakpoint(), v8::internal::WasmScript::SetBreakPointForFunction(), v8::ObjectTemplate::SetCallAsFunctionHandler(), v8::ObjectTemplate::SetCodeLike(), v8::debug::SetContextId(), v8::internal::BreakIterator::SetDebugBreak(), v8::debug::SetFunctionBreakpoint(), v8::ObjectTemplate::SetHandler(), v8::ObjectTemplate::SetImmutableProto(), v8::internal::anonymous_namespace{wasm-objects.cc}::SetInstanceMemory(), v8::debug::Script::SetInstrumentationBreakpoint(), v8::Object::SetIntegrityLevel(), v8::ObjectTemplate::SetInternalFieldCount(), v8::internal::JSArray::SetLengthWouldNormalize(), v8::Context::SetMicrotaskQueue(), v8::internal::JSObject::SetNormalizedElement(), v8::internal::JSObject::SetNormalizedProperty(), v8::internal::JSObject::SetOwnElementIgnoreAttributes(), v8::internal::JSObject::SetOwnPropertyIgnoreAttributes(), v8::Object::SetPrivate(), v8::Context::SetPromiseHooks(), v8::internal::JSProxy::SetProperty(), v8::internal::Object::SetPropertyWithDefinedSetter(), v8::anonymous_namespace{api.cc}::SetPrototypeImpl(), v8::debug::Script::SetScriptSource(), v8::debug::AccessorPair::setter(), v8::Context::SlowGetAlignedPointerFromEmbedderData(), v8::Object::SlowGetAlignedPointerFromInternalField(), v8::Context::SlowGetEmbedderData(), v8::Object::SlowGetInternalField(), v8::internal::JSObject::SlowReverseLookup(), v8::debug::Script::Source(), v8::internal::JSGeneratorObject::source_position(), v8::debug::Script::SourceMappingURL(), v8::Module::SourceOffsetToLocation(), v8::debug::Script::SourceURL(), v8::Promise::State(), v8::debug::GeneratorObject::SuspendedLocation(), v8::internal::wasm::WasmInterpreterRuntime::TableInit(), v8::Value::ToDetailString(), v8::Date::ToISOString(), v8::Date::ToUTCString(), v8::internal::Script::TraceScriptRundown(), v8::internal::Script::TraceScriptRundownSources(), v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::TryCopyElementsFastNumber(), v8::Value::Uint32Value(), v8::internal::CompilationCacheTable::UpdateEval(), v8::internal::wasm::WasmInterpreterRuntime::UpdateMemoryAddress(), v8::internal::ValidateFunctionCallbackInfo(), v8::internal::ValidatePropertyCallbackInfo(), v8::NumberObject::ValueOf(), v8::BigIntObject::ValueOf(), v8::BooleanObject::ValueOf(), v8::StringObject::ValueOf(), v8::SymbolObject::ValueOf(), v8::ValueSerializer::WriteValue(), v8::Context::BackupIncumbentScope::~BackupIncumbentScope(), and v8::internal::LocalHeap::~LocalHeap().
CurrentEmbeddedBlobCode()
const uint8_t * v8::internal::Isolate::CurrentEmbeddedBlobCode () [static]
Definition at line 395 of file isolate.cc.
                                                {
  return current_embedded_blob_code_.load(std::memory_order_relaxed);
}
References v8::internal::anonymous_namespace{isolate.cc}::current_embedded_blob_code_().
Referenced by ClearEmbeddedBlob(), CreateAndSetEmbeddedBlob(), v8::internal::FreeCurrentEmbeddedBlob(), v8::internal::EmbeddedData::FromBlob(), v8::internal::InstructionStream::FromTargetAddress(), v8::internal::CodeRange::GetPreferredRegion(), GetShortBuiltinsCallRegion(), v8::internal::OffHeapInstructionStream::PcIsOffHeap(), TearDownEmbeddedBlob(), v8::internal::OffHeapInstructionStream::TryGetAddressForHashing(), and v8::internal::OffHeapInstructionStream::TryLookupCode().
CurrentEmbeddedBlobCodeSize()
uint32_t v8::internal::Isolate::CurrentEmbeddedBlobCodeSize () [static]
Definition at line 400 of file isolate.cc.
                                              {
  return current_embedded_blob_code_size_.load(std::memory_order_relaxed);
}
References v8::internal::anonymous_namespace{isolate.cc}::current_embedded_blob_code_size_().
Referenced by v8::internal::FreeCurrentEmbeddedBlob(), v8::internal::EmbeddedData::FromBlob(), v8::internal::InstructionStream::FromTargetAddress(), v8::internal::CodeRange::GetPreferredRegion(), GetShortBuiltinsCallRegion(), and Isolate().
CurrentEmbeddedBlobData()
const uint8_t * v8::internal::Isolate::CurrentEmbeddedBlobData () [static]
Definition at line 405 of file isolate.cc.
                                                {
  return current_embedded_blob_data_.load(std::memory_order_relaxed);
}
References v8::internal::anonymous_namespace{isolate.cc}::current_embedded_blob_data_().
Referenced by ClearEmbeddedBlob(), CreateAndSetEmbeddedBlob(), v8::internal::FreeCurrentEmbeddedBlob(), v8::internal::EmbeddedData::FromBlob(), and TearDownEmbeddedBlob().
CurrentEmbeddedBlobDataSize()
uint32_t v8::internal::Isolate::CurrentEmbeddedBlobDataSize () [static]
Definition at line 410 of file isolate.cc.
                                              {
  return current_embedded_blob_data_size_.load(std::memory_order_relaxed);
}
References v8::internal::anonymous_namespace{isolate.cc}::current_embedded_blob_data_size_().
Referenced by v8::internal::FreeCurrentEmbeddedBlob(), and v8::internal::EmbeddedData::FromBlob().
CurrentEmbeddedBlobIsBinaryEmbedded()
bool v8::internal::Isolate::CurrentEmbeddedBlobIsBinaryEmbedded () [static]
Definition at line 312 of file isolate.cc.
                                                  {
  // In some situations, we must be able to rely on the embedded blob being
  // immortal immovable. This is the case if the blob is binary-embedded.
  // See blob lifecycle controls above for descriptions of when the current
  // embedded blob may change (e.g. in tests or mksnapshot). If the blob is
  // binary-embedded, it is immortal immovable.
  const uint8_t* code =
      current_embedded_blob_code_.load(std::memory_order_relaxed);
  if (code == nullptr) return false;
  return code == DefaultEmbeddedBlobCode();
}
References code, v8::internal::anonymous_namespace{isolate.cc}::current_embedded_blob_code_(), and v8::internal::DefaultEmbeddedBlobCode().
Referenced by v8::internal::init_memcopy_functions().
CurrentLocalHeap()
LocalHeap * v8::internal::Isolate::CurrentLocalHeap ()
Definition at line 7608 of file isolate.cc.
                                     {
  LocalHeap* local_heap = LocalHeap::Current();
  if (local_heap) return local_heap;
  DCHECK_EQ(ThreadId::Current(), thread_id());
  return main_thread_local_heap();
}
References v8::internal::ThreadId::Current(), DCHECK_EQ, main_thread_local_heap(), and thread_id().
CurrentPerIsolateThreadData()
Isolate::PerIsolateThreadData * v8::internal::Isolate::CurrentPerIsolateThreadData () [inline], [static]
Definition at line 30 of file isolate-inl.h.
                                     {
  return g_current_per_isolate_thread_data_;
}
Referenced by Deinitialize(), Enter(), Exit(), and Init().
CurrentReferrerScript()
MaybeDirectHandle< Script > v8::internal::Isolate::CurrentReferrerScript ()
Definition at line 1704 of file isolate.cc.
                                                         {
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.stack_trace"), __func__);
  CurrentScriptStackVisitor visitor{};
  VisitStack(this, &visitor);
  DirectHandle<Script> script;
  if (!visitor.CurrentScript().ToHandle(&script)) {
    return MaybeDirectHandle<Script>();
  }
  return direct_handle(script->GetEvalOrigin(), this);
}
References v8::internal::direct_handle(), v8::internal::script, TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT0, and v8::internal::anonymous_namespace{isolate.cc}::VisitStack().
Referenced by v8::Isolate::GetCurrentHostDefinedOptions().
CurrentScriptNameOrSourceURL()
DirectHandle< String > v8::internal::Isolate::CurrentScriptNameOrSourceURL ()
Definition at line 1697 of file isolate.cc.
                                                           {
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.stack_trace"), __func__);
  CurrentScriptNameStackVisitor visitor(this);
  VisitStack(this, &visitor);
  return visitor.CurrentScriptNameOrSourceURL();
}
References TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT0, and v8::internal::anonymous_namespace{isolate.cc}::VisitStack().
Referenced by v8::StackTrace::CurrentScriptNameOrSourceURL().
date_cache()
DateCache* v8::internal::Isolate::date_cache () const [inline]
Definition at line 1645 of file isolate.h.
{ return date_cache_; }
Referenced by v8::Isolate::DateTimeConfigurationChangeNotification(), v8::internal::JSDate::DoGetField(), v8::debug::GetDateDescription(), v8::internal::ParseDateTimeString(), set_date_cache(), v8::internal::anonymous_namespace{builtins-date.cc}::SetLocalDateValue(), v8::internal::JSDate::SetValue(), v8::Date::ToISOString(), v8::Date::ToUTCString(), and v8::internal::JSDate::UpdateFieldsAfterDeserialization().
date_cache_stamp()
Tagged<Smi> v8::internal::Isolate::date_cache_stamp () const [inline]
Definition at line 1654 of file isolate.h.
                                       {
    return Smi::FromInt(isolate_data()->date_cache_stamp_);
  }
References v8::internal::Smi::FromInt().
Referenced by v8::internal::JSDate::DoGetField().
debug()
Debug* v8::internal::Isolate::debug () const [inline]
Definition at line 1500 of file isolate.h.
{ return debug_; }
Referenced by v8::internal::wasm::gdb_server::WasmModuleDebug::AddBreakpoint(), v8::internal::SharedFunctionInfo::BreakAtEntry(), v8::debug::BreakRightNow(), v8::internal::Execution::CallBuiltin(), v8::debug::CallFunctionOn(), v8::internal::FunctionCallbackArguments::CallOrConstruct(), v8::debug::CanBreakProgram(), v8::debug::ChangeBreakOnException(), v8::internal::WasmScript::CheckBreakPoints(), v8::debug::ClearStepping(), v8::internal::Heap::InsertIntoRememberedSetFromCode::DebugBreakAtEntry(), v8::internal::wasm::gdb_server::GdbServer::DebugDelegate::DebugDelegate(), v8::internal::Heap::InsertIntoRememberedSetFromCode::DebugGetCoverageInfo(), Deinit(), v8::internal::Deoptimizer::Deoptimizer(), v8::internal::wasm::DeserializeNativeModule(), v8::internal::JSDisposableStackBase::DisposeResources(), v8::internal::ThreadManager::EagerlyArchiveThread(), v8::internal::DebugEvaluate::Evaluate(), v8::internal::anonymous_namespace{runtime-wasm.cc}::ExecuteWasmDebugBreaks(), v8::internal::anonymous_namespace{compiler.cc}::FinalizeUnoptimizedCompilation(), v8::internal::wasm::AsyncCompileJob::FinishCompile(), v8::internal::ThreadManager::FreeThreadResources(), v8::internal::FUNCTION_REFERENCE_WITH_TYPE(), v8::internal::Genesis::Genesis(), v8::debug::GetDebuggingId(), v8::internal::SharedFunctionInfo::GetDebugInfo(), v8::internal::GetFunctionPrototype(), v8::debug::GetIsolateId(), v8::internal::anonymous_namespace{compiler.cc}::GetOrCompileOptimized(), v8::debug::Script::GetPossibleBreakpoints(), v8::internal::DebugStackTraceIterator::GetReturnValue(), v8::internal::Debug::GetSourceBreakLocations(), v8::internal::DebugEvaluate::Global(), v8::internal::SharedFunctionInfo::HasBreakInfo(), v8::internal::SharedFunctionInfo::HasCoverageInfo(), v8::internal::SharedFunctionInfo::HasDebugInfo(), v8::internal::wasm::WasmEngine::ImportNativeModule(), v8::internal::ThreadManager::InitThread(), v8::internal::InvokeAccessorGetterCallback(), v8::internal::anonymous_namespace{api.cc}::InvokeFunctionCallback(), v8::internal::wasm::DebugInfoImpl::IsFrameBlackboxed(), v8::internal::anonymous_namespace{debug.cc}::IsJSFunctionAndNeedsTrampoline(), v8::internal::wasm::DebugInfoImpl::IsStepping(), v8::internal::Heap::IterateRoots(), v8::internal::DebugEvaluate::Local(), v8::internal::MoveMessageToPromise(), v8::internal::WasmTrustedInstanceData::New(), v8::Function::NewInstanceWithSideEffectType(), v8::debug::NotifyDebuggerPausedEventSent(), OnPromiseThen(), v8::internal::LiveEdit::PatchScript(), v8::internal::Compiler::PostInstantiation(), v8::internal::DebugStackTraceIterator::PrepareRestart(), v8::debug::PrepareRestartFrame(), v8::internal::wasm::gdb_server::WasmModuleDebug::PrepareStep(), v8::debug::PrepareStep(), PromiseHookStateUpdated(), v8::internal::JSPromise::Reject(), v8::debug::RemoveBreakpoint(), v8::internal::wasm::gdb_server::WasmModuleDebug::RemoveBreakpoint(), v8::debug::ResetBlackboxedStateCache(), v8::internal::JSPromise::Resolve(), v8::internal::ThreadManager::RestoreThread(), v8::internal::Coverage::SelectMode(), v8::debug::Script::SetBreakpoint(), v8::debug::SetBreakPointsActive(), v8::debug::SetDebugDelegate(), v8::debug::SetFunctionBreakpoint(), v8::debug::Script::SetInstrumentationBreakpoint(), v8::debug::SetIsolateId(), v8::debug::SetReturnValue(), v8::debug::Script::SetScriptSource(), v8::debug::SetTerminateOnResume(), v8::internal::wasm::WasmEngine::SyncCompile(), Throw(), v8::internal::PendingCompilationErrorHandler::ThrowPendingError(), v8::internal::Script::TraceScriptRundown(), v8::internal::Script::TraceScriptRundownSources(), v8::internal::SharedFunctionInfo::TryGetDebugInfo(), UnwindAndFindHandler(), and v8::internal::DebugEvaluate::WithTopmostArguments().
debug_execution_mode()
DebugInfo::ExecutionMode v8::internal::Isolate::debug_execution_mode () const [inline]
Definition at line 1524 of file isolate.h.
                                                      {
    return should_check_side_effects() ? DebugInfo::kSideEffects
                                       : DebugInfo::kBreakpoints;
  }
References v8::internal::DebugInfo::kBreakpoints, and v8::internal::DebugInfo::kSideEffects.
Referenced by v8::internal::Debug::PerformSideEffectCheck(), v8::internal::Debug::PerformSideEffectCheckAtBytecode(), v8::internal::Debug::PerformSideEffectCheckForAccessor(), v8::internal::Debug::PerformSideEffectCheckForCallback(), v8::internal::Debug::PerformSideEffectCheckForInterceptor(), v8::internal::Debug::PerformSideEffectCheckForObject(), v8::internal::Debug::StartSideEffectCheckMode(), v8::internal::Debug::StopSideEffectCheckMode(), v8::internal::Debug::UpdateDebugInfosForExecutionMode(), and v8::internal::Debug::UpdateHookOnFunctionCall().
define_own_stub_cache()
StubCache* v8::internal::Isolate::define_own_stub_cache () const [inline]
Definition at line 1329 of file isolate.h.
{ return define_own_stub_cache_; }
Referenced by v8::internal::ExternalReferenceTable::AddStubCache(), v8::internal::anonymous_namespace{heap.cc}::ClearStubCaches(), v8::internal::IC::stub_cache(), and v8::internal::AccessorAssembler::StoreICParameters::stub_cache().
Deinit()
void v8::internal::Isolate::Deinit () [private]
Definition at line 4476 of file isolate.cc.
                     {
  TRACE_ISOLATE(deinit);
#if defined(V8_USE_PERFETTO)
  PerfettoLogger::UnregisterIsolate(this);
#endif // defined(V8_USE_PERFETTO)
  // All client isolates should already be detached when the shared heap isolate
  // tears down.
  if (is_shared_space_isolate()) {
    global_safepoint()->AssertNoClientsOnTearDown();
  }
  if (has_shared_space() && !is_shared_space_isolate()) {
    IgnoreLocalGCRequests ignore_gc_requests(heap());
    main_thread_local_heap()->ExecuteMainThreadWhileParked([this]() {
      shared_space_isolate()->global_safepoint()->clients_mutex_.Lock();
    });
  }
  // We start with the heap tear down so that releasing managed objects does
  // not cause a GC.
  heap_.StartTearDown();
  DisallowGarbageCollection no_gc;
  IgnoreLocalGCRequests ignore_gc_requests(heap());
#if V8_ENABLE_WEBASSEMBLY && V8_ENABLE_DRUMBRAKE
  if (v8_flags.wasm_jitless) {
    wasm::WasmInterpreter::NotifyIsolateDisposal(this);
  } else if (v8_flags.wasm_enable_exec_time_histograms &&
             v8_flags.slow_histograms) {
    wasm_execution_timer_->Terminate();
  }
#endif // V8_ENABLE_WEBASSEMBLY && V8_ENABLE_DRUMBRAKE
  tracing_cpu_profiler_.reset();
  if (v8_flags.stress_sampling_allocation_profiler > 0) {
    heap()->heap_profiler()->StopSamplingHeapProfiler();
  }
  metrics_recorder_->NotifyIsolateDisposal();
  recorder_context_id_map_.clear();
  FutexEmulation::IsolateDeinit(this);
  if (v8_flags.harmony_struct) {
    JSSynchronizationPrimitive::IsolateDeinit(this);
  } else {
    DCHECK(async_waiter_queue_nodes_.empty());
  }
  debug()->Unload();
#if V8_ENABLE_WEBASSEMBLY
  wasm::GetWasmEngine()->DeleteCompileJobsOnIsolate(this);
  BackingStore::RemoveSharedWasmMemoryObjects(this);
#endif // V8_ENABLE_WEBASSEMBLY
  if (concurrent_recompilation_enabled()) {
    optimizing_compile_dispatcher_->StartTearDown();
  }
  if (v8_flags.print_deopt_stress) {
    PrintF(stdout, "=== Stress deopt counter: %" PRIu64 "\n",
           stress_deopt_count_);
  }
  // We must stop the logger before we tear down other components.
  sampler::Sampler* sampler = v8_file_logger_->sampler();
  if (sampler && sampler->IsActive()) sampler->Stop();
  v8_file_logger_->StopProfilerThread();
  FreeThreadResources();
  // Stop concurrent tasks before destroying resources since they might still
  // use those.
  cancelable_task_manager()->CancelAndWait();
  // Delete any remaining RegExpResultVector instances.
  for (int32_t* v : active_dynamic_regexp_result_vectors_) {
    delete[] v;
  }
  active_dynamic_regexp_result_vectors_.clear();
  // Cancel all compiler tasks.
#ifdef V8_ENABLE_SPARKPLUG
  delete baseline_batch_compiler_;
  baseline_batch_compiler_ = nullptr;
#endif // V8_ENABLE_SPARKPLUG
#ifdef V8_ENABLE_MAGLEV
  delete maglev_concurrent_dispatcher_;
  maglev_concurrent_dispatcher_ = nullptr;
#endif // V8_ENABLE_MAGLEV
  if (lazy_compile_dispatcher_) {
    lazy_compile_dispatcher_->AbortAll();
    lazy_compile_dispatcher_.reset();
  }
  if (concurrent_recompilation_enabled()) {
    optimizing_compile_dispatcher_->FinishTearDown();
    delete optimizing_compile_dispatcher_;
    optimizing_compile_dispatcher_ = nullptr;
  }
  // At this point there are no more background threads left in this isolate.
  heap_.safepoint()->AssertMainThreadIsOnlyThread();
  // Tear down data that requires the shared heap before detaching.
  heap_.TearDownWithSharedHeap();
  DumpAndResetBuiltinsProfileData();
  // Detach from the shared heap isolate and then unlock the mutex.
  if (has_shared_space() && !is_shared_space_isolate()) {
    GlobalSafepoint* global_safepoint =
        this->shared_space_isolate()->global_safepoint();
    global_safepoint->RemoveClient(this);
    global_safepoint->clients_mutex_.Unlock();
  }
  shared_space_isolate_.reset();
  // Since there are no other threads left, we can lock this mutex without any
  // ceremony. This signals to the tear down code that we are in a safepoint.
  base::RecursiveMutexGuard safepoint(&heap_.safepoint()->local_heaps_mutex_);
  ReleaseSharedPtrs();
  builtins_.TearDown();
  bootstrapper_->TearDown();
  if (tiering_manager_ != nullptr) {
    delete tiering_manager_;
    tiering_manager_ = nullptr;
  }
#if USE_SIMULATOR
  delete simulator_data_;
  simulator_data_ = nullptr;
#endif
  // After all concurrent tasks are stopped, we know for sure that stats aren't
  // updated anymore.
  DumpAndResetStats();
  // Contains zones that should be released to the page pool before the heap is
  // torn down.
  delete ast_string_constants_;
  ast_string_constants_ = nullptr;
  heap_.TearDown();
  isolate_group()->RemoveIsolate(this);
  delete inner_pointer_to_code_cache_;
  inner_pointer_to_code_cache_ = nullptr;
  main_thread_local_isolate_.reset();
  FILE* logfile = v8_file_logger_->TearDownAndGetLogFile();
  if (logfile != nullptr) base::Fclose(logfile);
#if defined(V8_ENABLE_ETW_STACK_WALKING)
  if (v8_flags.enable_etw_stack_walking ||
      v8_flags.enable_etw_by_custom_filter_only) {
    ETWJITInterface::RemoveIsolate(this);
  }
#endif // defined(V8_ENABLE_ETW_STACK_WALKING)
#if V8_ENABLE_WEBASSEMBLY
  wasm::GetWasmEngine()->RemoveIsolate(this);
  delete wasm_code_look_up_cache_;
  wasm_code_look_up_cache_ = nullptr;
#endif // V8_ENABLE_WEBASSEMBLY
  TearDownEmbeddedBlob();
  delete interpreter_;
  interpreter_ = nullptr;
  delete logger_;
  logger_ = nullptr;
  delete root_index_map_;
  root_index_map_ = nullptr;
  delete compiler_zone_;
  compiler_zone_ = nullptr;
  compiler_cache_ = nullptr;
  SetCodePages(nullptr);
  ClearSerializerData();
  if (OwnsStringTables()) {
    string_forwarding_table()->TearDown();
  } else {
    DCHECK_NULL(string_table_.get());
    DCHECK_NULL(string_forwarding_table_.get());
  }
  if (!is_shared_space_isolate()) {
    DCHECK_NULL(shared_struct_type_registry_.get());
  }
#ifdef V8_COMPRESS_POINTERS
  external_pointer_table().TearDownSpace(
      heap()->young_external_pointer_space());
  external_pointer_table().TearDownSpace(heap()->old_external_pointer_space());
  external_pointer_table().DetachSpaceFromReadOnlySegments(
      heap()->read_only_external_pointer_space());
  external_pointer_table().TearDownSpace(
      heap()->read_only_external_pointer_space());
  external_pointer_table().TearDown();
  if (owns_shareable_data()) {
    shared_external_pointer_table().TearDownSpace(
        shared_external_pointer_space());
    shared_external_pointer_table().TearDown();
    delete isolate_data_.shared_external_pointer_table_;
    isolate_data_.shared_external_pointer_table_ = nullptr;
    delete shared_external_pointer_space_;
    shared_external_pointer_space_ = nullptr;
  }
  cpp_heap_pointer_table().TearDownSpace(heap()->cpp_heap_pointer_space());
  cpp_heap_pointer_table().TearDown();
#endif // V8_COMPRESS_POINTERS
#ifdef V8_ENABLE_SANDBOX
  trusted_pointer_table().TearDownSpace(heap()->trusted_pointer_space());
  trusted_pointer_table().TearDown();
  if (owns_shareable_data()) {
    shared_trusted_pointer_table().TearDownSpace(
        shared_trusted_pointer_space());
    shared_trusted_pointer_table().TearDown();
    delete isolate_data_.shared_trusted_pointer_table_;
    isolate_data_.shared_trusted_pointer_table_ = nullptr;
    delete shared_trusted_pointer_space_;
    shared_trusted_pointer_space_ = nullptr;
  }
  IsolateGroup::current()->code_pointer_table()->TearDownSpace(
      heap()->code_pointer_space());
#endif // V8_ENABLE_SANDBOX
#ifdef V8_ENABLE_LEAPTIERING
  IsolateGroup::current()->js_dispatch_table()->TearDownSpace(
      heap()->js_dispatch_table_space());
#endif // V8_ENABLE_LEAPTIERING
  {
    base::MutexGuard lock_guard(&thread_data_table_mutex_);
    thread_data_table_.RemoveAllThreads();
  }
}
References active_dynamic_regexp_result_vectors_, v8::internal::IsolateSafepoint::AssertMainThreadIsOnlyThread(), v8::internal::GlobalSafepoint::AssertNoClientsOnTearDown(), ast_string_constants_, async_waiter_queue_nodes_, bootstrapper_, builtins_, cancelable_task_manager(), v8::internal::CancelableTaskManager::CancelAndWait(), ClearSerializerData(), v8::internal::GlobalSafepoint::clients_mutex_, compiler_cache_, compiler_zone_, concurrent_recompilation_enabled(), v8::internal::IsolateGroup::current(), v8::internal::DCHECK(), DCHECK_NULL, debug(), v8::internal::wasm::WasmEngine::DeleteCompileJobsOnIsolate(), DumpAndResetBuiltinsProfileData(), DumpAndResetStats(), v8::internal::LocalHeap::ExecuteMainThreadWhileParked(), v8::base::Fclose(), v8::internal::OptimizingCompileDispatcher::FinishTearDown(), FreeThreadResources(), v8::internal::wasm::GetWasmEngine(), global_safepoint(), has_shared_space(), heap(), heap_, v8::internal::Heap::heap_profiler(), inner_pointer_to_code_cache_, interpreter_, is_shared_space_isolate(), v8::sampler::Sampler::IsActive(), isolate_data_, isolate_group(), v8::internal::FutexEmulation::IsolateDeinit(), v8::internal::JSSynchronizationPrimitive::IsolateDeinit(), lazy_compile_dispatcher_, v8::internal::IsolateSafepoint::local_heaps_mutex_, v8::base::RecursiveMutex::Lock(), logger_, main_thread_local_heap(), main_thread_local_isolate_, metrics_recorder_, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::wasm::WasmInterpreter::NotifyIsolateDisposal(), optimizing_compile_dispatcher_, owns_shareable_data(), OwnsStringTables(), v8::internal::PrintF(), recorder_context_id_map_, ReleaseSharedPtrs(), v8::internal::Isolate::ThreadDataTable::RemoveAllThreads(), v8::internal::GlobalSafepoint::RemoveClient(), v8::internal::ETWJITInterface::RemoveIsolate(), v8::internal::IsolateGroup::RemoveIsolate(), v8::internal::wasm::WasmEngine::RemoveIsolate(), v8::internal::Heap::safepoint(), v8::internal::V8FileLogger::sampler(), SetCodePages(), shared_space_isolate(), shared_space_isolate_, shared_struct_type_registry_, v8::internal::OptimizingCompileDispatcher::StartTearDown(), v8::internal::Heap::StartTearDown(), v8::sampler::Sampler::Stop(), v8::internal::V8FileLogger::StopProfilerThread(), v8::internal::HeapProfiler::StopSamplingHeapProfiler(), stress_deopt_count_, string_forwarding_table(), string_forwarding_table_, string_table_, v8::internal::Builtins::TearDown(), v8::internal::Heap::TearDown(), v8::internal::Bootstrapper::TearDown(), v8::internal::StringForwardingTable::TearDown(), v8::internal::V8FileLogger::TearDownAndGetLogFile(), TearDownEmbeddedBlob(), v8::internal::Heap::TearDownWithSharedHeap(), thread_data_table_, thread_data_table_mutex_, tiering_manager_, TRACE_ISOLATE, tracing_cpu_profiler_, v8::internal::Debug::Unload(), v8::base::RecursiveMutex::Unlock(), v8::internal::PerfettoLogger::UnregisterIsolate(), v8_file_logger_, and v8::internal::v8_flags.
Referenced by Deinitialize().
Deinitialize()
void v8::internal::Isolate::Deinitialize (Isolate * isolate) [static]
Definition at line 4191 of file isolate.cc.
                                           {
  DCHECK_NOT_NULL(isolate);
  // v8::V8::Dispose() must only be called after deleting all isolates.
  DCHECK_NOT_NULL(V8::GetCurrentPlatform());
  // Temporarily set this isolate as current so that various parts of
  // the isolate can access it in their destructors without having a
  // direct pointer. We don't use Enter/Exit here to avoid
  // initializing the thread data.
  PerIsolateThreadData* saved_data = isolate->CurrentPerIsolateThreadData();
  Isolate* saved_isolate = isolate->TryGetCurrent();
  SetIsolateThreadLocals(isolate, nullptr);
  isolate->set_thread_id(ThreadId::Current());
  isolate->heap()->SetStackStart();
  isolate->Deinit();
#ifdef DEBUG
  non_disposed_isolates_--;
#endif // DEBUG
  IsolateGroup* group = isolate->isolate_group();
  isolate->~Isolate();
  // Only release the group once all other Isolate members have been destroyed.
  group->Release();
  // Restore the previous current isolate.
  SetIsolateThreadLocals(saved_isolate, saved_data);
}
References v8::internal::ThreadId::Current(), CurrentPerIsolateThreadData(), DCHECK_NOT_NULL, Deinit(), v8::internal::V8::GetCurrentPlatform(), heap(), v8::internal::Factory::isolate(), isolate_group(), v8::internal::IsolateGroup::Release(), set_thread_id(), SetIsolateThreadLocals(), v8::internal::Heap::SetStackStart(), and ~Isolate().
Referenced by v8::Isolate::Deinitialize(), and Delete().
Delete()
void v8::internal::Isolate::Delete (Isolate * isolate) [static]
Definition at line 4185 of file isolate.cc.
                                     {
  Deinitialize(isolate);
  Free(isolate);
}
References Deinitialize(), Free(), and v8::internal::Factory::isolate().
Referenced by v8::Isolate::Dispose(), v8::internal::Snapshot::SerializeDeserializeAndVerifyForTesting(), and v8::internal::SnapshotCreatorImpl::~SnapshotCreatorImpl().
deoptimizer_lazy_throw()
bool v8::internal::Isolate::deoptimizer_lazy_throw () const [inline]
Definition at line 1341 of file isolate.h.
{ return deoptimizer_lazy_throw_; }
Referenced by v8::internal::Deoptimizer::Deoptimizer().
descriptor_lookup_cache()
DescriptorLookupCache* v8::internal::Isolate::descriptor_lookup_cache () const [inline]
Definition at line 1404 of file isolate.h.
                                                         {
    return descriptor_lookup_cache_;
  }
Referenced by v8::internal::SnapshotCreatorImpl::CreateBlob(), v8::internal::Heap::CreateInitialMutableObjects(), v8::internal::Heap::MarkCompactPrologue(), and v8::internal::DescriptorArray::SearchWithCache().
DetachGlobal()
void v8::internal::Isolate::DetachGlobal (DirectHandle< Context > env)
Definition at line 7244 of file isolate.cc.
                                                    {
  counters()->errors_thrown_per_context()->AddSample(
      env->native_context()->GetErrorsThrown());
  ReadOnlyRoots roots(this);
  DirectHandle<JSGlobalProxy> global_proxy(env->global_proxy(), this);
  // NOTE: Turbofan's JSNativeContextSpecialization and Maglev depend on
  // DetachGlobal causing a map change.
  JSObject::ForceSetPrototype(this, global_proxy, factory()->null_value());
  // Detach the global object from the native context by making its map
  // contextless (use the global metamap instead of the contextful one).
  global_proxy->map()->set_map(this, roots.meta_map());
  global_proxy->map()->set_constructor_or_back_pointer(roots.null_value(),
                                                       kRelaxedStore);
  if (v8_flags.track_detached_contexts) AddDetachedContext(env);
  DCHECK(global_proxy->IsDetached());
  env->native_context()->set_microtask_queue(this, nullptr);
}
References AddDetachedContext(), counters(), v8::internal::DCHECK(), factory(), v8::internal::JSObject::ForceSetPrototype(), global_proxy(), v8::kRelaxedStore, and v8::internal::v8_flags.
Referenced by v8::Context::DetachGlobal().
detailed_source_positions_for_profiling()
bool v8::internal::Isolate::detailed_source_positions_for_profiling () const [inline]
Definition at line 1175 of file isolate.h.
                                                       {
    return detailed_source_positions_for_profiling_;
  }
Referenced by NeedsDetailedOptimizedCodeLineInfo().
DiscardPerThreadDataForThisThread()
void v8::internal::Isolate::DiscardPerThreadDataForThisThread ()
Definition at line 565 of file isolate.cc.
                                                {
  ThreadId thread_id = ThreadId::TryGetCurrent();
  if (thread_id.IsValid()) {
    DCHECK_NE(thread_manager_->mutex_owner_.load(std::memory_order_relaxed),
              thread_id);
    base::MutexGuard lock_guard(&thread_data_table_mutex_);
    PerIsolateThreadData* per_thread = thread_data_table_.Lookup(thread_id);
    if (per_thread) {
      DCHECK(!per_thread->thread_state_);
      thread_data_table_.Remove(per_thread);
    }
  }
}
References v8::internal::DCHECK(), DCHECK_NE, v8::internal::ThreadId::IsValid(), v8::internal::Isolate::ThreadDataTable::Lookup(), v8::internal::ThreadManager::mutex_owner_, v8::internal::Isolate::ThreadDataTable::Remove(), thread_data_table_, thread_data_table_mutex_, thread_id(), thread_manager_, v8::internal::Isolate::PerIsolateThreadData::thread_state_, and v8::internal::ThreadId::TryGetCurrent().
Referenced by v8::Isolate::DiscardThreadSpecificMetadata().
DumpAndResetBuiltinsProfileData()
void v8::internal::Isolate::DumpAndResetBuiltinsProfileData ()
Definition at line 6158 of file isolate.cc.
                                              {
  if (BasicBlockProfiler::Get()->HasData(this)) {
    if (v8_flags.turbo_profiling_output) {
      FILE* f = std::fopen(v8_flags.turbo_profiling_output, "w");
      if (f == nullptr) {
        FATAL("Unable to open file \"%s\" for writing.\n",
              v8_flags.turbo_profiling_output.value());
      }
      OFStream pgo_stream(f);
      BasicBlockProfiler::Get()->Log(this, pgo_stream);
    } else {
      StdoutStream out;
      BasicBlockProfiler::Get()->Print(this, out);
    }
    BasicBlockProfiler::Get()->ResetCounts(this);
  } else {
    // Only log builtins PGO data if v8 was built with
    // v8_enable_builtins_profiling=true
    CHECK_NULL(v8_flags.turbo_profiling_output);
  }
}
References CHECK_NULL, FATAL, v8::internal::BasicBlockProfiler::Get(), v8::internal::BasicBlockProfiler::Log(), v8::internal::BasicBlockProfiler::Print(), v8::internal::BasicBlockProfiler::ResetCounts(), and v8::internal::v8_flags.
Referenced by Deinit().
DumpAndResetStats()
void v8::internal::Isolate::DumpAndResetStats ()
Definition at line 6079 of file isolate.cc.
                                {
  if (v8_flags.trace_turbo_stack_accesses) {
    StdoutStream os;
    uint64_t total_loads = 0;
    uint64_t total_stores = 0;
    os << "=== Stack access counters === " << std::endl;
    if (!stack_access_count_map) {
      os << "No stack accesses in optimized/wasm functions found.";
    } else {
      DCHECK_NOT_NULL(stack_access_count_map);
      os << "Number of optimized/wasm stack-access functions: "
         << stack_access_count_map->size() << std::endl;
      for (auto it = stack_access_count_map->cbegin();
           it != stack_access_count_map->cend(); it++) {
        std::string function_name((*it).first);
        std::pair<uint64_t, uint64_t> per_func_count = (*it).second;
        os << "Name: " << function_name << ", Loads: " << per_func_count.first
           << ", Stores: " << per_func_count.second << std::endl;
        total_loads += per_func_count.first;
        total_stores += per_func_count.second;
      }
      os << "Total Loads: " << total_loads << ", Total Stores: " << total_stores
         << std::endl;
      stack_access_count_map = nullptr;
    }
  }
  if (turbo_statistics_ != nullptr) {
    DCHECK(v8_flags.turbo_stats || v8_flags.turbo_stats_nvp);
    StdoutStream os;
    if (v8_flags.turbo_stats) {
      AsPrintableStatistics ps = {"Turbofan", *turbo_statistics_, false};
      os << ps << std::endl;
    }
    if (v8_flags.turbo_stats_nvp) {
      AsPrintableStatistics ps = {"Turbofan", *turbo_statistics_, true};
      os << ps << std::endl;
    }
    turbo_statistics_.reset();
  }
#ifdef V8_ENABLE_MAGLEV
  if (maglev_statistics_ != nullptr) {
    DCHECK(v8_flags.maglev_stats || v8_flags.maglev_stats_nvp);
    StdoutStream os;
    if (v8_flags.maglev_stats) {
      AsPrintableStatistics ps = {"Maglev", *maglev_statistics_, false};
      os << ps << std::endl;
    }
    if (v8_flags.maglev_stats_nvp) {
      AsPrintableStatistics ps = {"Maglev", *maglev_statistics_, true};
      os << ps << std::endl;
    }
    maglev_statistics_.reset();
  }
#endif // V8_ENABLE_MAGLEV
#if V8_ENABLE_WEBASSEMBLY
  // TODO(7424): There is no public API for the {WasmEngine} yet. So for now we
  // just dump and reset the engines statistics together with the Isolate.
  if (v8_flags.turbo_stats_wasm) {
    wasm::GetWasmEngine()->DumpAndResetTurboStatistics();
  }
#endif // V8_ENABLE_WEBASSEMBLY
  if (v8_flags.trace_number_string_cache) {
    PrintNumberStringCacheStats("DumpAndResetStats", true);
  }
#if V8_RUNTIME_CALL_STATS
  if (V8_UNLIKELY(TracingFlags::runtime_stats.load(std::memory_order_relaxed) ==
                  v8::tracing::TracingCategoryObserver::ENABLED_BY_NATIVE)) {
    counters()->worker_thread_runtime_call_stats()->AddToMainTable(
        counters()->runtime_call_stats());
    counters()->runtime_call_stats()->Print();
    counters()->runtime_call_stats()->Reset();
  }
#endif // V8_RUNTIME_CALL_STATS
}
References counters(), v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::wasm::WasmEngine::DumpAndResetTurboStatistics(), v8::tracing::TracingCategoryObserver::ENABLED_BY_NATIVE, v8::internal::wasm::GetWasmEngine(), PrintNumberStringCacheStats(), v8::internal::Counters::runtime_call_stats(), v8::internal::TracingFlags::runtime_stats, v8::internal::anonymous_namespace{isolate.cc}::stack_access_count_map, v8::internal::string, turbo_statistics_, v8::internal::v8_flags, V8_UNLIKELY, and v8::internal::Counters::worker_thread_runtime_call_stats().
Referenced by Deinit(), and v8::Isolate::DumpAndResetStats().
EfficiencyModeEnabled()
bool v8::internal::Isolate::EfficiencyModeEnabled () [inline]
Definition at line 2134 of file isolate.h.
                               {
    if (V8_UNLIKELY(v8_flags.efficiency_mode.value().has_value())) {
      return *v8_flags.efficiency_mode.value();
    }
    return priority_ != v8::Isolate::Priority::kUserBlocking;
  }
References v8::Isolate::kUserBlocking, v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::internal::Heap::ShouldUseBackgroundThreads().
EfficiencyModeEnabledForTiering()
bool v8::internal::Isolate::EfficiencyModeEnabledForTiering () [inline]
Definition at line 2142 of file isolate.h.
                                         {
    return v8_flags.efficiency_mode_for_tiering_heuristics &&
           EfficiencyModeEnabled();
  }
References v8::internal::v8_flags.
Referenced by v8::internal::anonymous_namespace{runtime-compiler.cc}::CompileOptimizedOSR(), v8::internal::anonymous_namespace{runtime-compiler.cc}::CompileOptimizedOSRFromMaglev(), v8::internal::baseline::BaselineBatchCompiler::concurrent(), v8::internal::TieringManager::MaybeOptimizeFrame(), v8::internal::TieringManager::ShouldOptimize(), and v8::internal::OptimizingCompileTaskExecutor::TryQueueForOptimization().
elements_deletion_counter()
size_t v8::internal::Isolate::elements_deletion_counter () [inline]
Definition at line 2181 of file isolate.h.
{ return elements_deletion_counter_; }
Referenced by v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::DeleteCommon().
embedded_blob_code()
const uint8_t * v8::internal::Isolate::embedded_blob_code () const
Definition at line 381 of file isolate.cc.
                                                 {
  return embedded_blob_code_;
}
References embedded_blob_code_.
Referenced by CreateAndSetEmbeddedBlob(), v8::internal::Builtins::CreateInterpreterEntryTrampolineForProfiling(), v8::internal::anonymous_namespace{isolate.cc}::FinalizeBuiltinCodeObjects(), v8::internal::EmbeddedData::FromBlob(), InitializeCodeRanges(), v8::internal::CodeDataSourceIncrementalState::InternIsolate(), v8::internal::OffHeapInstructionStream::PcIsOffHeap(), TearDownEmbeddedBlob(), v8::internal::OffHeapInstructionStream::TryGetAddressForHashing(), and v8::internal::OffHeapInstructionStream::TryLookupCode().
embedded_blob_code_size()
uint32_t v8::internal::Isolate::embedded_blob_code_size () const
Definition at line 384 of file isolate.cc.
                                                {
  return embedded_blob_code_size_;
}
References embedded_blob_code_size_.
Referenced by v8::internal::Builtins::CreateInterpreterEntryTrampolineForProfiling(), v8::internal::anonymous_namespace{isolate.cc}::FinalizeBuiltinCodeObjects(), v8::internal::EmbeddedData::FromBlob(), InitializeCodeRanges(), v8::internal::CodeDataSourceIncrementalState::InternIsolate(), and TearDownEmbeddedBlob().
embedded_blob_data()
const uint8_t * v8::internal::Isolate::embedded_blob_data () const
Definition at line 387 of file isolate.cc.
                                                 {
  return embedded_blob_data_;
}
References embedded_blob_data_.
Referenced by CreateAndSetEmbeddedBlob(), v8::internal::anonymous_namespace{isolate.cc}::FinalizeBuiltinCodeObjects(), v8::internal::EmbeddedData::FromBlob(), and TearDownEmbeddedBlob().
embedded_blob_data_size()
uint32_t v8::internal::Isolate::embedded_blob_data_size () const
Definition at line 390 of file isolate.cc.
                                                {
  return embedded_blob_data_size_;
}
References embedded_blob_data_size_.
Referenced by v8::internal::anonymous_namespace{isolate.cc}::FinalizeBuiltinCodeObjects(), v8::internal::EmbeddedData::FromBlob(), and TearDownEmbeddedBlob().
enable_ro_allocation_for_snapshot()
bool v8::internal::Isolate::enable_ro_allocation_for_snapshot () const [inline]
Definition at line 2418 of file isolate.h.
                                                 {
    return enable_ro_allocation_for_snapshot_;
  }
enable_serializer()
void v8::internal::Isolate::enable_serializer () [inline]
Definition at line 1577 of file isolate.h.
{ serializer_enabled_ = true; }
Referenced by v8::internal::SnapshotCreatorImpl::InitInternal(), and v8::internal::Snapshot::SerializeDeserializeAndVerifyForTesting().
Enter()
void v8::internal::Isolate::Enter ()
Definition at line 5990 of file isolate.cc.
                    {
  Isolate* current_isolate = nullptr;
  PerIsolateThreadData* current_data = CurrentPerIsolateThreadData();
#ifdef V8_ENABLE_CHECKS
  // No different thread must have entered the isolate. Allow re-entering.
  ThreadId thread_id = ThreadId::Current();
  if (current_thread_id_.IsValid()) {
    CHECK_EQ(current_thread_id_, thread_id);
  } else {
    CHECK_EQ(0, current_thread_counter_);
    current_thread_id_ = thread_id;
  }
  current_thread_counter_++;
#endif
  // Set the stack start for the main thread that enters the isolate.
  heap()->SetStackStart();
  if (current_data != nullptr) {
    current_isolate = current_data->isolate_;
    DCHECK_NOT_NULL(current_isolate);
    if (current_isolate == this) {
      DCHECK(Current() == this);
      auto entry_stack = entry_stack_.load();
      DCHECK_NOT_NULL(entry_stack);
      DCHECK(entry_stack->previous_thread_data == nullptr ||
             entry_stack->previous_thread_data->thread_id() ==
                 ThreadId::Current());
      // Same thread re-enters the isolate, no need to re-init anything.
      entry_stack->entry_count++;
      return;
    }
  }
  PerIsolateThreadData* data = FindOrAllocatePerThreadDataForThisThread();
  DCHECK_NOT_NULL(data);
  DCHECK(data->isolate_ == this);
  EntryStackItem* item =
      new EntryStackItem(current_data, current_isolate, entry_stack_);
  entry_stack_ = item;
  SetIsolateThreadLocals(this, data);
  // In case it's the first time some thread enters the isolate.
  set_thread_id(data->thread_id());
}
References CHECK_EQ, Current(), v8::internal::ThreadId::Current(), CurrentPerIsolateThreadData(), v8::internal::DCHECK(), DCHECK_NOT_NULL, entry_stack_, FindOrAllocatePerThreadDataForThisThread(), heap(), v8::internal::Isolate::PerIsolateThreadData::isolate_, set_thread_id(), SetIsolateThreadLocals(), v8::internal::Heap::SetStackStart(), v8::internal::Isolate::PerIsolateThreadData::thread_id(), and thread_id().
Referenced by v8::Isolate::Enter(), v8::internal::SnapshotCreatorImpl::InitInternal(), and v8::internal::Snapshot::SerializeDeserializeAndVerifyForTesting().
error_message_param()
uint8_t v8::internal::Isolate::error_message_param () [inline]
Definition at line 1394 of file isolate.h.
{ return isolate_data_.error_message_param_; }
Referenced by v8::internal::Builtins::NameForStackTrace(), and v8::internal::RUNTIME_FUNCTION().
error_message_param_offset()
static uint32_t v8::internal::Isolate::error_message_param_offset () [inline], [static]
Definition at line 1388 of file isolate.h.
                                               {
    return static_cast<uint32_t>(OFFSET_OF(Isolate, isolate_data_) +
                                 OFFSET_OF(IsolateData, error_message_param_) -
                                 isolate_root_bias());
  }
References OFFSET_OF.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::SetDataViewOpForErrorMessage().
eternal_handles()
EternalHandles* v8::internal::Isolate::eternal_handles () const [inline]
Definition at line 1435 of file isolate.h.
{ return eternal_handles_; }
Referenced by v8::internal::SerializedHandleChecker::CheckGlobalAndEternalHandles(), v8::internal::Heap::CollectAllAvailableGarbage(), v8::api_internal::Eternalize(), v8::internal::Heap::IterateRoots(), and v8::internal::Heap::PerformGarbageCollection().
exception()
Tagged< Object > v8::internal::Isolate::exception () [inline]
Definition at line 104 of file isolate-inl.h.
                                  {
  CHECK(has_exception());
  DCHECK(!IsException(thread_local_top()->exception_, this));
  return thread_local_top()->exception_;
}
References CHECK, v8::internal::DCHECK(), v8::internal::ThreadLocalTop::exception_, has_exception(), and thread_local_top().
Referenced by v8::internal::anonymous_namespace{messages.cc}::AppendErrorString(), v8::internal::wasm::WasmEngine::AsyncInstantiate(), v8::internal::Debug::CheckBreakPoint(), v8::internal::anonymous_namespace{compiler.cc}::CompileScriptOnBothBackgroundAndMainThread(), ComputeLocationFromDetailedStackTrace(), ComputeLocationFromException(), ComputeLocationFromSimpleStackTrace(), v8::internal::Genesis::ConfigureApiObject(), v8::internal::JSWrappedFunction::Create(), CreateMessage(), CreateMessageFromException(), CreateMessageOrAbort(), v8::internal::SyntheticModule::Evaluate(), v8::internal::ErrorUtils::FormatStackTrace(), v8::internal::wasm::WasmInterpreterRuntime::HandleException(), is_catchable_by_javascript(), is_catchable_by_wasm(), v8::internal::SourceTextModule::MaybeHandleEvaluationException(), v8::internal::JSAsyncDisposableStack::NextDisposeAsyncIteration(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::InstantiateBytesResultResolver::OnInstantiationSucceeded(), PropagateExceptionToExternalTryCatch(), ReportExceptionFunctionCallback(), ReportExceptionPropertyCallback(), v8::internal::MessageHandler::ReportMessage(), ReportPendingMessages(), v8::internal::JSPromise::Resolve(), ReThrow(), RunHostCreateShadowRealmContextCallback(), RunHostImportModuleDynamicallyCallback(), v8::internal::RUNTIME_FUNCTION(), v8::internal::ErrorUtils::ShadowRealmConstructTypeErrorCopy(), v8::AsyncHooks::ShellPromiseHook(), StackOverflow(), Throw(), ThrowAt(), TopExceptionHandlerType(), UnwindAndFindHandler(), and wasm::FuncData::v8_callback().
Exit()
void v8::internal::Isolate::Exit ()
Definition at line 6039 of file isolate.cc.
                   {
  auto current_entry_stack = entry_stack_.load();
  DCHECK_NOT_NULL(current_entry_stack);
  DCHECK(current_entry_stack->previous_thread_data == nullptr ||
         current_entry_stack->previous_thread_data->thread_id() ==
             ThreadId::Current());
#ifdef V8_ENABLE_CHECKS
  // The current thread must have entered the isolate.
  CHECK_EQ(current_thread_id_, ThreadId::Current());
  if (--current_thread_counter_ == 0) current_thread_id_ = ThreadId::Invalid();
#endif
  if (--current_entry_stack->entry_count > 0) return;
  DCHECK_NOT_NULL(CurrentPerIsolateThreadData());
  DCHECK(CurrentPerIsolateThreadData()->isolate_ == this);
  // Pop the stack.
  entry_stack_ = current_entry_stack->previous_item;
  PerIsolateThreadData* previous_thread_data =
      current_entry_stack->previous_thread_data;
  Isolate* previous_isolate = current_entry_stack->previous_isolate;
  delete current_entry_stack;
  // Reinit the current thread for the isolate it was running before this one.
  SetIsolateThreadLocals(previous_isolate, previous_thread_data);
}
References CHECK_EQ, v8::internal::ThreadId::Current(), CurrentPerIsolateThreadData(), v8::internal::DCHECK(), DCHECK_NOT_NULL, entry_stack_, v8::internal::ThreadId::Invalid(), and SetIsolateThreadLocals().
Referenced by v8::Isolate::Exit(), v8::internal::Snapshot::SerializeDeserializeAndVerifyForTesting(), and v8::internal::SnapshotCreatorImpl::~SnapshotCreatorImpl().
external_reference_table()
ExternalReferenceTable* v8::internal::Isolate::external_reference_table () [inline]
Definition at line 1288 of file isolate.h.
                                                     {
    DCHECK(isolate_data()->external_reference_table()->is_initialized());
    return isolate_data()->external_reference_table();
  }
References v8::internal::DCHECK().
Referenced by v8::internal::StartupDeserializer::DeserializeAndCheckExternalReferenceTable(), v8::internal::ExternalReferenceEncoder::ExternalReferenceEncoder(), v8::internal::ExternalReferenceEncoder::NameOfAddress(), and v8::internal::StartupSerializer::StartupSerializer().
external_reference_table_unsafe()
ExternalReferenceTable* v8::internal::Isolate::external_reference_table_unsafe () [inline]
Definition at line 1293 of file isolate.h.
                                                            {
    // The table may only be partially initialized at this point.
    return isolate_data()->external_reference_table();
  }
Referenced by v8::internal::ObjectPostProcessor::GetAnyExternalReferenceAt().
factory()
v8::internal::Factory* v8::internal::Isolate::factory () [inline]
Definition at line 1553 of file isolate.h.
                               {
    // Upcast to the privately inherited base-class using c-style casts to avoid
    // undefined behavior (as static_cast cannot cast across private bases).
    return (v8::internal::Factory*)this;
  }
Referenced by v8::internal::SourceCodeCache::Add(), v8::internal::Object::Add(), v8::internal::wasm::gdb_server::WasmModuleDebug::AddBreakpoint(), v8::internal::WasmScript::AddBreakpointToInfo(), v8::internal::JSObject::AddDataElement(), v8::internal::ApiNatives::AddDataProperty(), v8::internal::Object::AddDataProperty(), v8::internal::PrototypeInfo::AddDerivedMap(), v8::internal::anonymous_namespace{runtime-classes.cc}::AddDescriptorsByTemplate(), AddDetachedContext(), v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::AddElementsToKeyAccumulatorImpl(), v8::internal::anonymous_namespace{runtime-debug.cc}::AddIteratorInternalProperties(), v8::internal::KeyAccumulator::AddKey(), v8::internal::anonymous_namespace{js-relative-time-format.cc}::AddLiteral(), v8::Isolate::AddMessageListenerWithErrorLevel(), v8::internal::anonymous_namespace{js-date-time-format.cc}::AddPartForFormatRange(), v8::anonymous_namespace{api.cc}::AddPropertiesAndElementsToObject(), v8::internal::JSObject::AddProperty(), v8::internal::anonymous_namespace{api-natives.cc}::AddPropertyToPropertyList(), v8::internal::anonymous_namespace{compilation-cache-table.cc}::AddToJSFunctionMap(), v8::internal::FeedbackVector::AddToVectorsForProfilingTools(), v8::internal::anonymous_namespace{js-relative-time-format.cc}::AddUnit(), v8::internal::AddWasmInstanceObjectInternalProperties(), v8::internal::AddWasmModuleObjectInternalProperties(), v8::internal::AddWasmTableObjectInternalProperties(), v8::ValueSerializer::Delegate::AdoptSharedValueConveyor(), v8::internal::PrototypeIterator::Advance(), v8::internal::PrototypeIterator::AdvanceFollowingProxies(), v8::internal::SmallOrderedHashTable< Derived >::Allocate(), v8::internal::OrderedHashTable< Derived, entrysize >::Allocate(), v8::internal::HeapObject::AllocateAndInstallJSDispatchHandle(), v8::internal::WasmStruct::AllocateDescriptorUninitialized(), v8::internal::anonymous_namespace{runtime-wasm.cc}::AllocateFeedbackVector(), v8::internal::FunctionTemplateInfo::AllocateFunctionTemplateRareData(), v8::internal::Heap::AllocateMap(), v8::internal::WasmStruct::AllocatePrototype(), v8::internal::TranslatedState::AllocateStorageFor(), v8::internal::JSObject::AllocateStorageForMap(), v8::internal::JSArray::AnythingToArrayLength(), v8::internal::WeakArrayList::Append(), v8::internal::LookupIterator::ApplyTransitionToDataProperty(), v8::internal::anonymous_namespace{asm-js.cc}::AreStdlibMembersValid(), v8::internal::PendingCompilationErrorHandler::MessageDetails::ArgString(), v8::internal::anonymous_namespace{accessors.cc}::ArgumentsFromDeoptInfo(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::ArgumentToCompileOptions(), v8::internal::anonymous_namespace{builtins-arraybuffer.cc}::ArrayBufferTransfer(), v8::internal::ArrayConstructInitializeElements(), v8::internal::wasm::WasmInterpreterRuntime::ArrayNewUninitialized(), v8::internal::JSArray::ArraySetLength(), v8::internal::Object::ArraySpeciesConstructor(), v8::internal::anonymous_namespace{compilation-cache-table.cc}::EvalCacheKey::AsHandle(), v8::internal::ScriptCacheKey::AsHandle(), v8::internal::NumberDictionaryBaseShape::AsHandle(), v8::internal::Map::AsLanguageMode(), v8::internal::anonymous_namespace{objects.cc}::AsStringOrEmpty(), v8::internal::SourceTextModule::AsyncModuleExecutionFulfilled(), v8::internal::RegExpImpl::AtomCompile(), v8::internal::BuiltinArguments::atOrUndefined(), v8::internal::Arguments< arguments_type >::atOrUndefined(), v8::internal::anonymous_namespace{intl-objects.cc}::AvailableUnits(), v8::internal::JSLocale::BaseName(), v8::internal::JSTemporalDuration::Blank(), v8::internal::compiler::CodeAssembler::BooleanConstant(), v8::internal::Debug::Break(), v8::internal::wasm::InstanceBuilder::Build_Phase1(), v8::internal::anonymous_namespace{messages.cc}::BuildDefaultCallSite(), v8::internal::JSRegExpResultIndices::BuildIndices(), v8::internal::Factory::JSFunctionBuilder::BuildRaw(), v8::internal::BUILTIN(), v8::internal::anonymous_namespace{template-objects.cc}::CachedTemplateMatches(), v8::internal::wasm::WasmInterpreterRuntime::CallExternalJSFunction(), v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder::CallSiteBuilder(), v8::internal::wasm::WasmInterpreterRuntime::CallWasmToJSBuiltin(), v8::internal::anonymous_namespace{wasm-objects.cc}::CanonicalizeHeapNumber(), v8::internal::anonymous_namespace{wasm-objects.cc}::CanonicalizeSmi(), CaptureAndSetErrorStack(), CaptureDetailedStackTrace(), v8::internal::ErrorUtils::CaptureStackTrace(), v8::Promise::Catch(), v8::internal::anonymous_namespace{builtins-sharedarraybuffer.cc}::CheckAtomicsPauseIterationNumber(), v8::internal::WasmScript::CheckBreakPoints(), v8::internal::Debug::CheckBreakPointsForLocations(), v8::internal::Object::CheckContextualStoreToJSGlobalObject(), v8::internal::JSProxy::CheckDeleteTrap(), CheckDetachedContextsAfterGC(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::CheckForWellKnownImport(), v8::internal::JSProxy::CheckGetSetTrapResult(), v8::internal::JSProxy::CheckHasTrap(), v8::internal::JSDisposableStackBase::CheckValueAndGetDisposeMethod(), v8::internal::JSFinalizationRegistry::Cleanup(), v8::internal::PropertyCell::ClearAndInvalidate(), v8::internal::BreakPointInfo::ClearBreakPoint(), v8::Object::Clone(), v8::internal::CloneObjectSlowPath(), v8::internal::ExternalLogEventListener::CodeCreateEvent(), v8::internal::CoerceOptionsToObject(), v8::internal::anonymous_namespace{debug-coverage.cc}::CollectAndMaybeResetCounts(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::CollectElementIndicesImpl(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::CollectElementIndicesImpl(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::CollectElementIndicesImpl(), v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::CollectElementIndicesImpl(), v8::internal::anonymous_namespace{builtins-struct.cc}::CollectFieldsAndElements(), v8::internal::anonymous_namespace{keys.cc}::CollectKeysFromDictionary(), v8::internal::KeyAccumulator::CollectOwnJSProxyKeys(), v8::internal::anonymous_namespace{keys.cc}::CombineKeys(), v8::internal::ObjectDeserializer::CommitPostProcessedObjects(), v8::internal::anonymous_namespace{js-number-format.cc}::CompactDisplayString(), v8::internal::TransitionArray::CompactPrototypeTransitionArray(), v8::internal::RegExp::Compile(), v8::internal::CompiledReplacement::Compile(), v8::internal::Genesis::CompileExtension(), v8::ScriptCompiler::CompileFunction(), v8::internal::CompileGlobalEval(), v8::ScriptCompiler::CompileModule(), v8::internal::PropertyDescriptor::CompletePropertyDescriptor(), ComputeLocationFromException(), v8::internal::ElementsAccessor::Concat(), v8::String::Concat(), v8::internal::anonymous_namespace{api-natives.cc}::ConfigureInstance(), v8::internal::anonymous_namespace{builtins-console.cc}::ConsoleCall(), v8::internal::anonymous_namespace{js-locale.cc}::Construct(), v8::internal::ErrorUtils::Construct(), v8::internal::anonymous_namespace{runtime-regexp.cc}::ConstructNamedCaptureGroupsObject(), v8::internal::JSTemporalInstant::Constructor(), v8::internal::JSTemporalPlainTime::Constructor(), v8::internal::JSTemporalPlainMonthDay::Constructor(), v8::internal::JSTemporalPlainYearMonth::Constructor(), v8::internal::JSTemporalPlainDate::Constructor(), v8::internal::JSTemporalPlainDateTime::Constructor(), v8::internal::JSTemporalDuration::Constructor(), v8::internal::anonymous_namespace{js-number-format.cc}::ConstructParts(), v8::internal::JSSegments::Containing(), v8::internal::DebugEvaluate::ContextBuilder::ContextBuilder(), v8::internal::anonymous_namespace{builtins-string.cc}::ConvertCase(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::ConvertElementsWithCapacity(), v8::internal::OrderedHashSet::ConvertToKeysArray(), v8::internal::Object::ConvertToLength(), v8::internal::Intl::ConvertToLower(), v8::internal::Intl::ConvertToUpper(), v8::internal::AccessorPair::Copy(), v8::internal::Map::CopyAsElementsKind(), v8::internal::anonymous_namespace{externalize-string-extension.cc}::CopyConsStringToOld(), v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::CopyElementsHandleImpl(), v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::CopyElementsHandleSlow(), v8::internal::JSFunctionOrBoundFunctionOrWrappedFunction::CopyNameAndLength(), v8::internal::anonymous_namespace{basic-block-profiler.cc}::CopyStringToJSHeap(), v8::internal::PreparseDataBuilder::ByteData::CopyToHeap(), v8::internal::BasicBlockProfilerData::CopyToJSHeap(), v8::internal::DescriptorArray::CopyUpToAddAttributes(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::ContextProxyPrototype::Create(), v8::internal::DictionaryTemplateInfo::Create(), v8::internal::JSSegments::Create(), v8::internal::JSWrappedFunction::Create(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::IndexedDebugProxy< T, id, Provider >::Create(), v8::internal::JSSegmentIterator::Create(), v8::internal::ArrayProxy::Create(), v8::internal::JSRawJson::Create(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::LocalsProxy::Create(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::StackProxy::Create(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::ContextProxy::Create(), v8::internal::JSFunction::CreateAndAttachFeedbackVector(), v8::internal::JSDataObjectBuilder::CreateAndInitialiseObject(), v8::internal::ApiNatives::CreateApiFunction(), v8::internal::anonymous_namespace{intl-objects.cc}::CreateArrayFromList(), v8::internal::anonymous_namespace{runtime-literals.cc}::CreateArrayLiteral(), v8::internal::CreateArrayMap(), v8::internal::FeedbackNexus::CreateArrayOfSize(), v8::internal::SnapshotCreatorImpl::CreateBlob(), v8::internal::anonymous_namespace{builtins-intl.cc}::CreateBoundFunction(), v8::internal::Debug::CreateBreakInfo(), v8::internal::RegExp::CreateCaptureNameMap(), v8::internal::anonymous_namespace{runtime-classes.cc}::CreateClassPrototype(), v8::internal::compiler::JSCallReducer::CreateClosureFromBuiltinSharedFunctionInfo(), v8::internal::compiler::PromiseBuiltinReducerAssembler::CreateClosureFromBuiltinSharedFunctionInfo(), v8::internal::anonymous_namespace{js-plural-rules.cc}::CreateDataPropertyForOptions(), v8::internal::anonymous_namespace{js-collator.cc}::CreateDataPropertyForOptions(), v8::internal::JSDateTimeFormat::CreateDateTimeFormat(), v8::internal::CreateDummyWasmLookAlikeForFuzzing(), v8::internal::CreateElementDictionary(), v8::CreateEnvironment(), v8::internal::SourceTextModule::CreateExport(), v8::internal::anonymous_namespace{externalize-string-extension.cc}::CreateExternalizableString(), v8::internal::ScopeInfo::CreateForBootstrapping(), v8::internal::CreateFuncRefMap(), v8::internal::anonymous_namespace{bootstrapper.cc}::CreateFunction(), v8::internal::anonymous_namespace{bootstrapper.cc}::CreateFunctionForBuiltinWithPrototype(), v8::internal::wasm::CreateFunctionForCompileTimeImport(), v8::internal::Heap::CreateImportantReadOnlyObjects(), v8::internal::Heap::CreateInitialMutableObjects(), v8::internal::JSSharedStruct::CreateInstanceMap(), v8::anonymous_namespace{api.cc}::CreateInterceptorInfo(), v8::internal::anonymous_namespace{code-serializer.cc}::CreateInterpreterDataForDeserializedCode(), v8::internal::Heap::CreateLateReadOnlyJSReceiverMaps(), v8::internal::Object::CreateListFromArrayLike(), v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::CreateListFromArrayLikeImpl(), v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::CreateListFromArrayLikeImpl(), v8::internal::anonymous_namespace{bootstrapper.cc}::CreateLiteralObjectMapFromCache(), v8::internal::Genesis::CreateObjectFunction(), v8::internal::anonymous_namespace{runtime-literals.cc}::CreateObjectLiteral(), v8::internal::Heap::CreateReadOnlyApiObjects(), v8::internal::Heap::CreateReadOnlyObjects(), v8::internal::JSAtomicsMutex::CreateResultObject(), v8::internal::JSSegments::CreateSegmentDataObject(), v8::internal::anonymous_namespace{setup-heap-internal.cc}::CreateSharedFunctionInfo(), v8::internal::anonymous_namespace{bootstrapper.cc}::CreateSharedFunctionInfoForBuiltin(), v8::internal::anonymous_namespace{bootstrapper.cc}::CreateSharedObjectConstructor(), v8::internal::Factory::CreateSloppyFunctionMap(), v8::internal::Genesis::CreateSloppyModeFunctionMaps(), v8::internal::anonymous_namespace{templates.cc}::CreateSlowJSObjectWithProperties(), v8::internal::Factory::CreateStrictFunctionMap(), v8::internal::Genesis::CreateStrictModeFunctionMaps(), v8::internal::CreateStructMap(), v8::Module::CreateSyntheticModule(), v8::internal::CreateWasmObject(), v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::CreateWasmScript(), v8::internal::anonymous_namespace{js-number-format.cc}::CurrencyDisplayString(), v8::internal::anonymous_namespace{js-number-format.cc}::CurrencySignString(), v8::internal::JSV8BreakIterator::Current(), v8::internal::anonymous_namespace{js-date-time-format.cc}::DateTimeStyleAsString(), v8::internal::SharedFunctionInfo::DebugName(), v8::internal::anonymous_namespace{runtime-scopes.cc}::DeclareEvalHelper(), v8::internal::Uri::Decode(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::DefaultReferenceValue(), v8::internal::wasm::anonymous_namespace{constant-expression-interface.cc}::DefaultValueForType(), v8::internal::anonymous_namespace{runtime-classes.cc}::DefineClass(), v8::internal::Runtime::DefineObjectOwnProperty(), v8::internal::JSObject::DefineOwnAccessorIgnoreAttributes(), v8::internal::JSArray::DefineOwnProperty(), v8::internal::JSProxy::DefineOwnProperty(), v8::internal::JSReceiver::DefineProperties(), v8::internal::JSReceiver::DefineProperty(), v8::internal::JSReceiver::DeleteProperty(), v8::internal::JSProxy::DeletePropertyOrElement(), v8::internal::compiler::CompilationDependencies::DependOnArrayBufferDetachingProtector(), v8::internal::compiler::CompilationDependencies::DependOnArrayIteratorProtector(), v8::internal::compiler::CompilationDependencies::DependOnArraySpeciesProtector(), v8::internal::compiler::CompilationDependencies::DependOnMegaDOMProtector(), v8::internal::compiler::CompilationDependencies::DependOnNoDateTimeConfigurationChangeProtector(), v8::internal::compiler::CompilationDependencies::DependOnNoElementsProtector(), v8::internal::compiler::CompilationDependencies::DependOnNoProfilingProtector(), v8::internal::compiler::CompilationDependencies::DependOnNoUndetectableObjectsProtector(), v8::internal::compiler::CompilationDependencies::DependOnPromiseHookProtector(), v8::internal::compiler::CompilationDependencies::DependOnPromiseSpeciesProtector(), v8::internal::compiler::CompilationDependencies::DependOnPromiseThenProtector(), v8::internal::compiler::CompilationDependencies::DependOnStringWrapperToPrimitiveProtector(), DetachGlobal(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::DirectCollectElementIndicesImpl(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::DirectCollectElementIndicesImpl(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::DirectCollectElementIndicesImpl(), v8::internal::anonymous_namespace{builtins-intl.cc}::DisallowCallConstructor(), v8::internal::SharedFunctionInfo::DiscardCompiled(), v8::internal::anonymous_namespace{js-duration-format.cc}::DisplayToString(), v8::internal::JSDisposableStackBase::DisposeResources(), v8::internal::anonymous_namespace{builtins-function.cc}::DoFunctionBind(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::DoReturn(), v8::internal::DoWait(), v8::internal::wasm::WasmInterpreterRuntime::ElemDrop(), v8::internal::BoyerMooreLookahead::EmitSkipInstructions(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitUseLookupTable(), v8::internal::DeoptimizationData::Empty(), v8::internal::Uri::Encode(), v8::internal::anonymous_namespace{runtime-wasm.cc}::EncodeWtf8(), v8::internal::MicrotaskQueue::EnqueueMicrotask(), v8::internal::MemoryMeasurement::EnqueueRequest(), v8::internal::EmbedderDataArray::EnsureCapacity(), v8::internal::FixedArrayBuilder::EnsureCapacity(), v8::internal::JSFunction::EnsureClosureFeedbackCellArray(), v8::internal::TransitionsAccessor::EnsureHasFullTransitionArray(), v8::internal::JSFunction::EnsureHasInitialMap(), v8::internal::baseline::BaselineBatchCompiler::EnsureQueueCapacity(), v8::internal::wasm::WasmInterpreterThread::EnsureRefStackSpace(), v8::internal::WeakArrayList::EnsureSpace(), v8::internal::MaterializedObjectStore::EnsureStackEntries(), v8::internal::RegExpResultsCache::Enter(), v8::internal::JSTemporalInstant::EpochMilliseconds(), v8::internal::JSTemporalInstant::Equals(), v8::internal::Context::ErrorMessageForCodeGenerationFromStrings(), v8::internal::Context::ErrorMessageForWasmCodeGeneration(), v8::internal::anonymous_namespace{uri.cc}::EscapePrivate(), v8::internal::anonymous_namespace{js-regexp.cc}::EscapeRegExpSource(), v8::internal::SyntheticModule::Evaluate(), v8::internal::Module::Evaluate(), v8::internal::SourceTextModule::Evaluate(), v8::internal::wasm::EvaluateConstantExpression(), v8::RegExp::Exec(), v8::internal::RegExp::Exec_Single(), v8::internal::SourceTextModule::ExecuteAsyncModule(), v8::internal::wasm::InstanceBuilder::ExecuteStartFunction(), v8::internal::anonymous_namespace{runtime-wasm.cc}::ExecuteWasmDebugBreaks(), v8::internal::WasmModuleObject::ExtractUtf8StringFromModuleBytes(), v8::internal::compiler::turboshaft::AssertTypesReducer< Next >::factory(), v8::internal::interpreter::IntrinsicsGenerator::factory(), v8::internal::JsonParser< Char >::factory(), v8::internal::JsonStringifier::factory(), v8::internal::IncrementalStringBuilder::factory(), v8::internal::compiler::CodeAssembler::factory(), v8::internal::compiler::JSCallReducer::factory(), v8::internal::compiler::JSCreateLowering::factory(), v8::internal::compiler::JSNativeContextSpecialization::factory(), v8::internal::compiler::SimplifiedOperatorReducer::factory(), v8::internal::compiler::TypedOptimization::factory(), v8::internal::Genesis::factory(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::FailAssert(), v8::internal::JSDisplayNames::FallbackAsString(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::FastApiCall(), v8::internal::FastGetOwnValuesOrEntries(), v8::internal::FastIterateArray(), v8::internal::anonymous_namespace{json-stringifier.cc}::FastJsonStringify(), v8::internal::SourceTextModule::FetchStarExports(), v8::internal::LookupIterator::FetchValue(), v8::internal::anonymous_namespace{js-date-time-format.cc}::FieldPositionIteratorToArray(), v8::internal::DebugPropertyIterator::FillKeysForCurrentPrototypeAndStage(), v8::internal::anonymous_namespace{runtime-test.cc}::FillUpOneNewSpacePage(), v8::internal::BuiltinsConstantsTableBuilder::Finalize(), v8::internal::wasm::JSToWasmWrapperCompilationUnit::Finalize(), v8::internal::anonymous_namespace{isolate.cc}::FinalizeBuiltinCodeObjects(), v8::internal::AsmJsCompilationJob::FinalizeJobImpl(), v8::internal::BackgroundCompileTask::FinalizeScript(), v8::internal::DebugInfo::FindBreakPointInfo(), v8::internal::Debug::FindInnermostContainingFunctionInfo(), v8::internal::wasm::AsyncCompileJob::FinishCompile(), v8::internal::CodeSerializer::FinishOffThreadDeserialize(), v8::internal::JSV8BreakIterator::First(), v8::internal::FoldedMutableHeapNumberAllocation::FoldedMutableHeapNumberAllocation(), v8::internal::MessageFormatter::Format(), v8::internal::anonymous_namespace{js-relative-time-format.cc}::FormatCommon(), v8::internal::ErrorUtils::FormatStackTrace(), v8::internal::anonymous_namespace{js-date-time-format.cc}::FormattedDateIntervalToJSArray(), v8::internal::anonymous_namespace{js-list-format.cc}::FormattedListToJSArray(), v8::internal::FormattedListToJSArray(), v8::internal::anonymous_namespace{builtins-console.cc}::Formatter(), v8::internal::anonymous_namespace{js-relative-time-format.cc}::FormatToJSArray(), v8::internal::anonymous_namespace{js-number-format.cc}::FormatToJSArray(), v8::internal::JSDateTimeFormat::FormatToParts(), v8::internal::IntlMathematicalValue::From(), v8::internal::Managed< CppType >::From(), v8::internal::TrustedManaged< CppType >::From(), v8::FromCData(), v8::internal::BigInt::FromInt64(), v8::internal::ObjectBuiltinsAssembler::FromPropertyDescriptor(), v8::internal::BigInt::FromSerializedDigits(), v8::internal::BigInt::FromUint64(), v8::internal::JSPromise::Fulfill(), v8::internal::compiler::CodeGenerator::GenerateDeoptimizationData(), v8::internal::anonymous_namespace{builtins-array.cc}::GenericArrayPop(), v8::internal::anonymous_namespace{builtins-array.cc}::GenericArrayPush(), v8::internal::RegExpUtils::GenericCaptureGetter(), v8::internal::Genesis::Genesis(), v8::internal::Context::Get(), v8::internal::SmiStringCache::Get(), v8::internal::DoubleStringCache::Get(), v8::internal::FixedDoubleArray::get(), v8::internal::BaseCollectionsAssembler::GetAddFunction(), v8::debug::GetBigIntDescription(), v8::debug::anonymous_namespace{debug-interface.cc}::GetBigIntStringPresentationHandle(), v8::internal::GetBoolOption(), v8::internal::DebugInfo::GetBreakPoints(), v8::debug::GetBuiltin(), v8::internal::anonymous_namespace{js-date-time-format.cc}::GetCalendar(), v8::internal::RegExpBytecodeGenerator::GetCode(), v8::internal::AccessorPair::GetComponent(), v8::internal::anonymous_namespace{js-objects.cc}::GetConstructorHelper(), v8::internal::wasm::GetCustomSections(), v8::internal::JSReceiver::GetDataProperty(), v8::debug::GetDateDescription(), v8::Function::GetDebugName(), v8::internal::JSFunction::GetDebugName(), v8::internal::JSFunction::GetDerivedMap(), v8::internal::anonymous_namespace{isolate.cc}::GetDetailedStackTraceFromCallSiteInfos(), v8::internal::interpreter::Interpreter::GetDispatchCountersObject(), v8::internal::anonymous_namespace{js-duration-format.cc}::GetDurationUnitOptions(), v8::internal::WasmArray::GetElement(), v8::internal::JSWeakCollection::GetEntries(), v8::internal::SmiStringCache::GetEntryFor(), v8::internal::DoubleStringCache::GetEntryFor(), v8::internal::ErrorUtils::GetErrorStackProperty(), v8::internal::WasmExceptionPackage::GetExceptionTag(), v8::internal::WasmExceptionPackage::GetExceptionValues(), v8::internal::JSModuleNamespace::GetExport(), v8::internal::wasm::GetExports(), v8::internal::GetFeedbackSlotType(), v8::internal::ErrorUtils::GetFormattedStack(), v8::internal::anonymous_namespace{accessors.cc}::GetFrameArguments(), v8::internal::ScopeIterator::GetFunctionDebugName(), v8::internal::CallSiteInfo::GetFunctionDebugName(), v8::internal::anonymous_namespace{debug-evaluate.cc}::GetFunctionInfo(), v8::CpuProfileNode::GetFunctionName(), v8::internal::CallSiteInfo::GetFunctionName(), v8::internal::GetFunctionPrototype(), v8::internal::JSSegmenter::GetGranularityString(), v8::internal::Debug::GetHitBreakPoints(), v8::internal::JSLocale::GetHourCycles(), v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::GetImpl(), GetImportAttributesFromArgument(), v8::internal::wasm::GetImports(), v8::Function::GetInferredName(), v8::internal::anonymous_namespace{api-natives.cc}::anonymous_namespace{api-natives.cc}::GetInstancePrototype(), v8::internal::Runtime::GetInternalProperties(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::GetIterableLength(), v8::internal::anonymous_namespace{runtime-debug.cc}::GetJSPositionInfo(), v8::internal::KeyAccumulator::GetKeys(), v8::internal::FastKeyAccumulator::GetKeysWithPrototypeInfoCache(), v8::internal::GetKeywordValuesFromLocale(), v8::internal::RegExpUtils::GetLastIndex(), v8::internal::Accessors::GetLegacyFunctionArguments(), v8::internal::Accessors::GetLegacyFunctionCaller(), v8::internal::Object::GetLengthFromArrayLike(), v8::internal::Debug::GetLoadedScripts(), v8::debug::GetMessageFromPromise(), v8::internal::Object::GetMethod(), v8::internal::CallSiteInfo::GetMethodName(), v8::internal::Module::GetModuleNamespace(), v8::Module::GetModuleRequests(), v8::Function::GetName(), v8::HeapGraphEdge::GetName(), v8::HeapGraphNode::GetName(), v8::internal::PropertyKey::GetName(), v8::internal::JSBoundFunction::GetName(), v8::internal::JSFunction::GetName(), v8::internal::JSWrappedFunction::GetName(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::NamedDebugProxy< T, id, Provider >::GetNameTable(), v8::internal::anonymous_namespace{debug-property-iterator.cc}::GetNativeAccessorDescriptorInternal(), v8::internal::wasm::WasmInterpreterRuntime::GetNullValue(), v8::internal::Intl::GetNumberingSystem(), v8::internal::JSLocale::GetNumberingSystems(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::DebugWasmScopeIterator::GetObject(), v8::internal::GetOptionsObject(), v8::internal::Debug::GetOrCreateDebugInfo(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::GetOrCreateDebugMaps(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::GetOrCreateDebugProxyMap(), v8::internal::WasmTrustedInstanceData::GetOrCreateFuncRef(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::GetOrCreateInstanceProxyCache(), v8::internal::Map::GetOrCreatePrototypeChainValidityCell(), v8::internal::Map::GetOrCreatePrototypeInfo(), v8::internal::FunctionTemplateInfo::GetOrCreateSharedFunctionInfo(), v8::internal::anonymous_namespace{keys.cc}::GetOwnEnumPropertyDictionaryKeys(), v8::internal::FastKeyAccumulator::GetOwnKeysWithUninitializedEnumLength(), v8::internal::JSProxy::GetOwnPropertyDescriptor(), v8::internal::anonymous_namespace{builtins-object.cc}::GetOwnPropertyKeys(), v8::internal::GetOwnValuesOrEntries(), v8::internal::CommonFrameWithJSLinkage::GetParameters(), v8::internal::BuiltinExitFrame::GetParameters(), v8::internal::ApiCallbackExitFrame::GetParameters(), wasm::anonymous_namespace{c-api.cc}::GetProperException(), v8::internal::JSProxy::GetProperty(), v8::internal::JSReceiver::GetProperty(), v8::internal::Object::GetProperty(), v8::internal::JSModuleNamespace::GetPropertyAttributes(), v8::Object::GetPropertyNames(), v8::internal::Object::GetPropertyWithAccessor(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyWithInterceptorInternal(), v8::internal::JSProxy::GetPrototype(), v8::internal::DebugStackTraceIterator::GetReceiver(), v8::internal::temporal::GetRoundingIncrementOption(), v8::anonymous_namespace{api.cc}::GetScriptDetails(), v8::internal::CallSiteInfo::GetScriptHash(), v8::internal::Script::GetScriptHash(), v8::CpuProfileNode::GetScriptResourceName(), v8::ValueDeserializer::Delegate::GetSharedArrayBufferFromId(), v8::ValueSerializer::Delegate::GetSharedArrayBufferId(), v8::ValueDeserializer::Delegate::GetSharedValueConveyor(), GetSimpleStackTrace(), v8::internal::Debug::GetSourceBreakLocations(), v8::internal::SharedFunctionInfo::GetSourceCode(), v8::internal::SharedFunctionInfo::GetSourceCodeHarmony(), v8::internal::JSMessageObject::GetSourceLine(), v8::internal::anonymous_namespace{messages.cc}::GetStackFrames(), GetStackTraceLimit(), v8::internal::SourceTextModule::GetStalledTopLevelAwaitMessages(), v8::internal::GetStringOption(), v8::internal::GetStringOrBooleanOption(), v8::internal::LookupIterator::GetStringPropertyValue(), v8::internal::String::GetSubstitution(), v8::internal::TemplateObjectDescription::GetTemplateObject(), v8::internal::temporal::GetTemporalFractionalSecondDigitsOption(), v8::internal::temporal::GetTemporalUnit(), v8::internal::anonymous_namespace{wasm-js.cc}::GetterName(), v8::internal::JSLocale::GetTextInfo(), v8::internal::Intl::GetTimeZoneIndex(), v8::internal::Intl::GetTimeZoneOffsetTransitionNanoseconds(), v8::internal::JSLocale::GetTimeZones(), v8::CpuProfile::GetTitle(), v8::internal::wasm::GetTypeForFunction(), v8::internal::wasm::GetTypeForGlobal(), v8::internal::wasm::GetTypeForMemory(), v8::internal::wasm::GetTypeForTable(), v8::internal::CallSiteInfo::GetTypeName(), v8::internal::TranslatedValue::GetValue(), v8::internal::anonymous_namespace{deoptimized-frame-info.cc}::GetValueForDebugger(), v8::ValueDeserializer::Delegate::GetWasmModuleFromId(), v8::internal::JSLocale::GetWeekInfo(), v8::internal::WasmTableObject::Grow(), v8::internal::TransitionArray::GrowPrototypeTransitionArray(), v8::internal::anonymous_namespace{builtins-api.cc}::HandleApiCallHelper(), v8::internal::JSAtomicsMutex::HandleAsyncNotify(), v8::internal::JSAtomicsCondition::HandleAsyncNotify(), v8::internal::JSAtomicsMutex::HandleAsyncTimeout(), v8::internal::Debug::HandleDebugBreak(), v8::internal::JSDisposableStackBase::HandleErrorInDisposal(), v8::internal::anonymous_namespace{builtins-typed-array.cc}::HandleOptionsBag(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::HasDefaultToNumberBehaviour(), v8::internal::anonymous_namespace{runtime-forin.cc}::HasEnumerableProperty(), v8::internal::ErrorUtils::HasErrorStackSymbolOwnProperty(), v8::internal::JSProxy::HasProperty(), v8::internal::Runtime::HasProperty(), v8::internal::JSArray::HasReadOnlyLengthSlowPath(), v8::internal::JSDateTimeFormat::HourCycleAsString(), v8::internal::anonymous_namespace{js-date-time-format.cc}::IcuDateFieldIdToDateType(), v8::internal::anonymous_namespace{js-list-format.cc}::IcuFieldIdToType(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::IndexedDebugProxy< T, id, Provider >::IndexedEnumerator(), v8::internal::String::IndexOf(), Init(), v8::internal::JSMap::Initialize(), v8::internal::JSSet::Initialize(), v8::internal::JSArray::Initialize(), v8::internal::ExperimentalRegExp::Initialize(), v8::internal::JSRegExp::Initialize(), v8::internal::Oddball::Initialize(), v8::internal::Genesis::InitializeCallSiteBuiltins(), v8::internal::anonymous_namespace{log.cc}::InitializeCodeEvent(), v8::internal::Genesis::InitializeConsole(), v8::internal::MathRandom::InitializeContext(), v8::internal::wasm::InitializeElementSegment(), v8::internal::FastKeyAccumulator::InitializeFastPropertyEnumCache(), v8::internal::Genesis::InitializeGlobal(), v8::internal::Genesis::InitializeIteratorFunctions(), v8::internal::JSDisposableStackBase::InitializeJSDisposableStackBase(), v8::internal::JSDataObjectBuilder::InitializeMapFromZero(), v8::internal::DescriptorArray::InitializeOrChangeEnumCache(), v8::internal::wasm::WasmInterpreterRuntime::InitializeRefLocalsRefs(), v8::internal::anonymous_namespace{intl-objects.cc}::InnerAddElement(), v8::internal::SourceTextModule::InnerModuleEvaluation(), v8::internal::StringTable::InsertEmptyStringForBootstrapping(), v8::internal::TransitionsAccessor::InsertHelper(), v8::internal::Genesis::InstallABunchOfRandomThings(), InstallConditionalFeatures(), v8::internal::anonymous_namespace{bootstrapper.cc}::InstallConstant(), v8::internal::anonymous_namespace{builtins-console.cc}::InstallContextFunction(), v8::internal::SharedFunctionInfo::InstallDebugBytecode(), v8::internal::InstallError(), v8::internal::anonymous_namespace{bootstrapper.cc}::InstallFunction(), v8::internal::anonymous_namespace{bootstrapper.cc}::InstallFunctionAtSymbol(), v8::internal::anonymous_namespace{bootstrapper.cc}::InstallFunctionWithBuiltinId(), v8::internal::Genesis::InstallGlobalThisBinding(), v8::internal::Compiler::InstallInterpreterTrampolineCopy(), v8::internal::WasmJs::InstallJSPromiseIntegration(), v8::internal::WasmJs::InstallModule(), v8::internal::Genesis::InstallSpecialObjects(), v8::internal::anonymous_namespace{bootstrapper.cc}::InstallSpeciesGetter(), v8::internal::anonymous_namespace{bootstrapper.cc}::InstallToStringTag(), v8::internal::anonymous_namespace{bootstrapper.cc}::InstallTrueValuedProperty(), v8::internal::WasmJs::InstallTypeReflection(), v8::internal::InstallWithIntrinsicDefaultProto(), v8::internal::Object::InstanceOf(), v8::FunctionTemplate::InstanceTemplate(), v8::internal::AsmJs::InstantiateAsmWasm(), v8::internal::anonymous_namespace{api-natives.cc}::InstantiateFunction(), v8::internal::anonymous_namespace{api-natives.cc}::InstantiateObject(), v8::internal::ApiNatives::InstantiateRemoteObject(), v8::internal::JsonParseInternalizer::Internalize(), v8::internal::JsonParseInternalizer::InternalizeJsonProperty(), v8::internal::PropertyCell::InvalidateAndReplaceEntry(), v8::internal::anonymous_namespace{execution.cc}::Invoke(), v8::internal::RegExpImpl::IrregexpInitialize(), is_catchable_by_wasm(), v8::internal::JSProxy::IsArray(), v8::internal::anonymous_namespace{builtins-array.cc}::IsConcatSpreadable(), v8::internal::JSProxy::IsExtensible(), v8::internal::Name::IsInteresting(), v8::internal::Accessors::IsJSObjectFieldAccessor(), v8::internal::RegExpUtils::IsUnmodifiedRegExp(), v8::internal::wasm::IsWasmCodegenAllowed(), v8::internal::temporal::anonymous_namespace{js-temporal-helpers.cc}::IterateDurationRecordFieldsTable(), v8::internal::anonymous_namespace{builtins-array.cc}::IterateElements(), v8::internal::wasm::JSToWasmObject(), v8::internal::wasm::WasmInterpreterRuntime::JSToWasmObject(), v8::internal::Heap::KeepDuringJob(), v8::internal::JSLocale::Language(), v8::internal::JSDisplayNames::LanguageDisplayAsString(), v8::internal::String::LastIndexOf(), v8::internal::anonymous_namespace{builtins-intl.cc}::LegacyFormatConstructor(), v8::internal::Intl::LegacyUnwrapReceiver(), v8::internal::LoadIC::Load(), v8::internal::LoadHandler::LoadFromPrototype(), v8::internal::LoadHandler::LoadFullChain(), v8::internal::anonymous_namespace{runtime-scopes.cc}::LoadLookupSlot(), v8::internal::LoadHandler::LoadNonExistent(), v8::internal::wasm::InstanceBuilder::LoadTableSegments(), v8::internal::DebugEvaluate::Local(), v8::internal::anonymous_namespace{intl-objects.cc}::LocaleConvertCase(), LocalsBlockListCacheSet(), v8::internal::JSAtomicsMutex::LockAsync(), v8::internal::JSAtomicsMutex::LockAsyncWrapperForWait(), v8::internal::JSAtomicsMutex::LockOrEnqueuePromise(), v8::internal::ExistingCodeLogger::LogExistingFunction(), v8::internal::CompilationCacheRegExp::Lookup(), v8::internal::wasm::InstanceBuilder::LookupImportAsm(), v8::internal::LookupIterator::LookupIterator(), v8::internal::CompilationCacheTable::LookupRegExp(), v8::internal::Accessors::MakeAccessor(), v8::anonymous_namespace{api.cc}::MakeAccessorInfo(), v8::internal::wasm::JSPrototypesSetup::MakeConstructor(), v8::internal::JSObject::MakeElementsWritable(), v8::internal::MakeEntryPair(), v8::internal::ErrorUtils::MakeGenericError(), v8::internal::MessageHandler::MakeMessageObject(), v8::internal::anonymous_namespace{runtime-debug.cc}::MakeRangeObject(), v8::anonymous_namespace{api.cc}::MapAsArray(), v8::internal::anonymous_namespace{builtins-typed-array.cc}::MapOptionToEnum(), v8::internal::ScriptCacheKey::MatchesScript(), v8::internal::TranslatedState::MaterializeHeapNumber(), v8::internal::ScopeIterator::MaterializeScopeDetails(), v8::internal::WasmDispatchTable::MaybeGrowUsesList(), v8::internal::SourceTextModule::MaybeHandleEvaluationException(), v8::ArrayBuffer::MaybeNew(), v8::SharedArrayBuffer::MaybeNew(), v8::internal::FeedbackVector::MegaDOMSentinel(), v8::internal::FeedbackVector::MegamorphicSentinel(), v8::internal::anonymous_namespace{js-objects.cc}::MigrateFastToFast(), v8::internal::anonymous_namespace{js-objects.cc}::MigrateFastToSlow(), v8::internal::JSObject::MigrateSlowToFast(), v8::internal::MoveMessageToPromise(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::NamedDebugProxy< T, id, Provider >::NamedEnumerator(), v8::internal::JSObject::New(), v8::internal::WasmInterpreterObject::New(), v8::internal::WasmTrustedInstanceData::New(), v8::Map::New(), v8::Set::New(), v8::Object::New(), v8::internal::NormalizedMapCache::New(), v8::internal::WasmCapiFunction::New(), v8::BooleanObject::New(), v8::internal::WasmJSFunction::New(), v8::internal::WasmTagObject::New(), v8::internal::WasmMemoryObject::New(), v8::internal::WasmSuspendingObject::New(), v8::internal::JSV8BreakIterator::New(), v8::internal::JSDisplayNames::New(), v8::internal::JSDurationFormat::New(), v8::internal::JSListFormat::New(), v8::internal::JSPluralRules::New(), v8::internal::JSRelativeTimeFormat::New(), v8::internal::JSSegmenter::New(), v8::internal::JSCollator::New(), v8::internal::JSNumberFormat::New(), v8::internal::JSLocale::New(), v8::internal::WasmDescriptorOptions::New(), v8::internal::JSProxy::New(), v8::internal::ClosureFeedbackCellArray::New(), v8::internal::FeedbackVector::New(), v8::internal::JSRegExp::New(), v8::internal::WasmValueObject::New(), v8::internal::WasmExceptionPackage::New(), v8::internal::WasmExportedFunction::New(), v8::internal::WasmGlobalObject::New(), v8::internal::WasmTableObject::New(), v8::NumberObject::New(), v8::Number::New(), v8::internal::RegExpMatchInfo::New(), v8::internal::DeoptimizationData::New(), v8::internal::WasmExceptionTag::New(), v8::PrimitiveArray::New(), v8::internal::TrustedPodArray< T >::New(), v8::internal::PodArray< T >::New(), v8::internal::WasmDispatchTable::New(), v8::Array::New(), v8::Integer::New(), v8::ObjectTemplate::New(), v8::Symbol::New(), v8::Private::New(), v8::ArrayBuffer::New(), v8::SharedArrayBuffer::New(), v8::internal::AsmWasmData::New(), v8::internal::WasmModuleObject::New(), v8::External::New(), v8::DataView::New(), v8::Float16Array::New(), v8::Promise::Resolver::New(), v8::internal::ErrorUtils::NewCalledNonCallableError(), v8::internal::ErrorUtils::NewConstructedNonConstructable(), v8::internal::anonymous_namespace{runtime-internal.cc}::NewError(), v8::String::NewExternalOneByte(), v8::String::NewExternalTwoByte(), v8::internal::FeedbackVector::NewForTesting(), v8::internal::MutableBigInt::NewFromDouble(), v8::internal::WasmMemoryMapDescriptor::NewFromFileDescriptor(), v8::internal::MutableBigInt::NewFromInt(), v8::Integer::NewFromUnsigned(), v8::String::NewFromUtf8Literal(), v8::CppHeapExternal::NewImpl(), v8::internal::DictionaryTemplateInfo::NewInstance(), v8::internal::ErrorUtils::NewIteratorError(), v8::internal::anonymous_namespace{runtime-regexp.cc}::NewJSArrayWithElements(), v8::anonymous_namespace{wasm-js.cc}::NewPromisingWasmExportedFunction(), v8::internal::anonymous_namespace{execution.cc}::NewScriptContext(), v8::internal::anonymous_namespace{runtime-scopes.cc}::NewSloppyArguments(), v8::internal::Object::NewStorageFor(), v8::internal::anonymous_namespace{factory.cc}::NewStringFromBytes(), v8::internal::Factory::NewSuppressedErrorAtDisposal(), v8::internal::Factory::NewSurrogatePairString(), v8::internal::JSObject::NewWithMap(), v8::internal::JSSegmentIterator::Next(), v8::internal::JSV8BreakIterator::Next(), v8::internal::anonymous_namespace{builtins-string.cc}::NextCodePoint(), v8::internal::JSAsyncDisposableStack::NextDisposeAsyncIteration(), v8::internal::Intl::Normalize(), v8::internal::anonymous_namespace{objects.cc}::NoSideEffectsErrorToString(), v8::internal::Object::NoSideEffectsToMaybeString(), v8::internal::BigInt::NoSideEffectsToString(), v8::internal::Object::NoSideEffectsToString(), v8::internal::anonymous_namespace{js-number-format.cc}::NotationAsString(), NotifyExceptionPropagationCallback(), v8::internal::Intl::NumberFieldToType(), v8::internal::NumberFormatRange(), v8::internal::JSLocale::Numeric(), v8::internal::JSRelativeTimeFormat::NumericAsString(), v8::internal::JSObject::ObjectCreate(), v8::internal::JSDisplayNames::Of(), v8::internal::Debug::OnException(), OnPromiseAfter(), OnPromiseBefore(), v8::internal::RegExpBytecodePeepholeOptimization::OptimizeBytecode(), v8::internal::Object::OrdinaryHasInstance(), v8::JSON::Parse(), v8::internal::anonymous_namespace{js-number-format.cc}::PartitionNumberRangePattern(), v8::internal::LiveEdit::PatchScript(), v8::internal::anonymous_namespace{builtins-callsite.cc}::PositiveNumberOrNull(), v8::internal::SeqSubStringKey< SeqString >::PrepareForInsertion(), v8::internal::InternalizedStringKey::PrepareForInsertion(), v8::internal::WasmJs::PrepareForSnapshot(), v8::internal::SyntheticModule::PrepareInstantiate(), v8::internal::Debug::PrepareStep(), v8::internal::LookupIterator::PrepareTransitionToDataProperty(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::PrependElementIndicesImpl(), v8::internal::JSProxy::PreventExtensions(), v8::internal::JSObject::PreventExtensionsWithTransition(), PrintCurrentStackTrace(), v8::internal::CallPrinter::PrintLiteral(), PrintNumberStringCacheStats(), v8::internal::CodeStubAssembler::PrintToStream(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::wasm::InstanceBuilder::ProcessExports(), v8::internal::wasm::InstanceBuilder::ProcessImportedGlobal(), v8::internal::PropertyKey::PropertyKey(), v8::FunctionTemplate::PrototypeTemplate(), v8::internal::wasm::WasmInterpreterThread::RaiseException(), v8::internal::DebugPropertyIterator::raw_name(), v8::internal::Map::RawCopy(), v8::internal::ValueDeserializer::ReadDenseJSArray(), v8::internal::JSObject::ReadFromOptionsBag(), v8::internal::ValueDeserializer::ReadHeader(), v8::ValueDeserializer::ReadHeader(), v8::ValueDeserializer::Delegate::ReadHostObject(), v8::internal::ValueDeserializer::ReadJSArrayBuffer(), v8::internal::ValueDeserializer::ReadJSArrayBufferView(), v8::internal::ValueDeserializer::ReadJSError(), v8::internal::ValueDeserializer::ReadJSMap(), v8::internal::ValueDeserializer::ReadJSObject(), v8::internal::ValueDeserializer::ReadJSObjectProperties(), v8::internal::ValueDeserializer::ReadJSPrimitiveWrapper(), v8::internal::ValueDeserializer::ReadJSSet(), v8::internal::ValueDeserializer::ReadObject(), v8::internal::ValueDeserializer::ReadObjectInternal(), v8::internal::ValueDeserializer::ReadObjectUsingEntireBufferForLegacyFormat(), v8::internal::ValueDeserializer::ReadObjectWrapper(), v8::internal::ValueDeserializer::ReadOneByteString(), v8::internal::ValueDeserializer::ReadSparseJSArray(), v8::internal::ValueDeserializer::ReadTwoByteString(), v8::internal::ValueDeserializer::ReadUtf8String(), v8::internal::WasmObject::ReadValueAt(), v8::internal::anonymous_namespace{isolate.cc}::ReceiverIsForwardingHandler(), v8::internal::anonymous_namespace{elements.cc}::SlowSloppyArgumentsElementsAccessor::ReconfigureImpl(), v8::internal::anonymous_namespace{keys.cc}::ReduceFixedArrayTo(), v8::internal::WasmMemoryObject::RefreshBuffer(), v8::internal::WasmMemoryObject::RefreshSharedBuffer(), v8::internal::ExternalLogEventListener::RegExpCodeCreateEvent(), v8::internal::RegExpUtils::RegExpExec(), v8::internal::anonymous_namespace{runtime-regexp.cc}::RegExpReplace(), v8::internal::JSLocale::Region(), v8::internal::SharedStructTypeRegistry::RegisterNoThrow(), v8::internal::wasm::ErrorThrower::Reify(), v8::internal::DeoptimizationLiteral::Reify(), v8::internal::JSPromise::Reject(), v8::internal::Debug::RemoveBreakpoint(), v8::internal::anonymous_namespace{asm-js.cc}::Report(), ReportExceptionFunctionCallback(), v8::internal::MessageHandler::ReportMessage(), v8::internal::MessageHandler::ReportMessageNoExceptions(), v8::internal::SourceTextModule::Reset(), v8::internal::ResizeHelper(), v8::internal::JSPromise::Resolve(), v8::internal::FutexEmulation::ResolveAsyncWaiterPromise(), v8::internal::JSCollator::ResolvedOptions(), v8::internal::JSDateTimeFormat::ResolvedOptions(), v8::internal::JSDisplayNames::ResolvedOptions(), v8::internal::JSDurationFormat::ResolvedOptions(), v8::internal::JSListFormat::ResolvedOptions(), v8::internal::JSNumberFormat::ResolvedOptions(), v8::internal::JSPluralRules::ResolvedOptions(), v8::internal::JSRelativeTimeFormat::ResolvedOptions(), v8::internal::JSSegmenter::ResolvedOptions(), v8::internal::JSV8BreakIterator::ResolvedOptions(), v8::internal::SyntheticModule::ResolveExport(), v8::internal::SourceTextModule::ResolveExport(), v8::internal::SourceTextModule::ResolveExportUsingStarExports(), v8::internal::SourceTextModule::ResolveImport(), v8::internal::TranslatedState::ResolveStringConcat(), v8::internal::JSTemporalInstant::Round(), v8::internal::JSNumberFormat::RoundingIncrement(), v8::internal::JSNumberFormat::RoundingModeString(), v8::internal::JSNumberFormat::RoundingPriorityString(), RunHostCreateShadowRealmContextCallback(), RunHostImportModuleDynamicallyCallback(), RunHostInitializeImportMetaObjectCallback(), v8::internal::SourceTextModule::RunInitializationCode(), v8::internal::RUNTIME_FUNCTION(), v8::internal::ScopeIterator::ScopeObject(), v8::internal::JSLocale::Script(), v8::internal::anonymous_namespace{runtime-debug.cc}::ScriptLocationFromLine(), v8::internal::FunctionTemplateInfo::SealAndPrepareForPromotionToReadOnly(), v8::internal::anonymous_namespace{runtime-regexp.cc}::SearchRegExpMultiple(), v8::internal::ZonePreparseData::Serialize(), v8::internal::JsonStringifier::Serialize_(), v8::internal::JsonStringifier::SerializeArrayLikeSlow(), v8::internal::JsonStringifier::SerializeJSProxy(), v8::internal::Context::Set(), v8::internal::SmiStringCache::Set(), v8::internal::DoubleStringCache::Set(), v8::internal::Factory::CodeBuilder::set_empty_source_position_table(), v8::ObjectTemplate::SetAccessCheckCallback(), v8::ObjectTemplate::SetAccessCheckCallbackAndHandler(), v8::Object::SetAccessorProperty(), v8::internal::RegExpUtils::SetAdvancedStringIndex(), v8::anonymous_namespace{api.cc}::SetAsArray(), v8::internal::anonymous_namespace{js-atomics-synchronization.cc}::SetAsyncUnlockHandlers(), v8::internal::BreakPointInfo::SetBreakPoint(), v8::internal::DebugInfo::SetBreakPoint(), v8::internal::Debug::SetBreakpointForFunction(), v8::internal::Debug::SetBreakPointForScript(), v8::ObjectTemplate::SetCallAsFunctionHandler(), v8::FunctionTemplate::SetCallHandler(), v8::internal::wasm::FrameState::SetCaughtException(), v8::internal::anonymous_namespace{builtins-date.cc}::SetDateValue(), v8::internal::SyntheticModule::SetExport(), v8::internal::ErrorUtils::SetFormattedStack(), v8::debug::SetFunctionBreakpoint(), v8::internal::WasmTableObject::SetFunctionTablePlaceholder(), v8::debug::Script::SetInstrumentationBreakpoint(), v8::internal::RegExpUtils::SetLastIndex(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::SetLengthImpl(), v8::internal::anonymous_namespace{elements.cc}::FastNonextensibleObjectElementsAccessor< Subclass, KindTraits >::SetLengthImpl(), v8::internal::anonymous_namespace{elements.cc}::FastSealedObjectElementsAccessor< Subclass, KindTraits >::SetLengthImpl(), v8::internal::anonymous_namespace{builtins-array.cc}::SetLengthProperty(), v8::internal::anonymous_namespace{builtins-date.cc}::SetLocalDateValue(), v8::internal::JSFunction::SetName(), v8::internal::JSObject::SetNormalizedProperty(), v8::internal::Intl::SetNumberFormatDigitOptions(), v8::internal::PrototypeInfo::SetObjectCreateMap(), v8::internal::Runtime::SetObjectProperty(), v8::internal::JSProxy::SetPrivateSymbol(), v8::Context::SetPromiseHooks(), v8::internal::JSProxy::SetProperty(), v8::internal::Object::SetPropertyWithAccessor(), v8::internal::JSFunction::SetPrototype(), v8::internal::JSObject::SetPrototype(), v8::internal::JSProxy::SetPrototype(), v8::internal::anonymous_namespace{wasm-js.cc}::SetterName(), v8::internal::anonymous_namespace{wasm-js.cc}::SetupConstructor(), v8::internal::anonymous_namespace{execution.cc}::InvokeParams::SetUpForCall(), v8::internal::anonymous_namespace{execution.cc}::InvokeParams::SetUpForNew(), v8::internal::anonymous_namespace{execution.cc}::InvokeParams::SetUpForRunMicrotasks(), v8::internal::anonymous_namespace{execution.cc}::InvokeParams::SetUpForTryCall(), v8::internal::ScopeIterator::SetVariableValue(), v8::internal::ImportedFunctionEntry::SetWasmToWrapper(), v8::internal::ErrorUtils::ShadowRealmConstructTypeErrorCopy(), v8::internal::SwissNameDictionary::ShallowCopy(), v8::internal::anonymous_namespace{js-number-format.cc}::SignDisplayString(), v8::internal::SimpleInstallFunction(), v8::internal::anonymous_namespace{bootstrapper.cc}::SimpleInstallGetter(), v8::internal::anonymous_namespace{bootstrapper.cc}::SimpleInstallGetterSetter(), v8::internal::SliceHelper(), v8::internal::anonymous_namespace{builtins-array.cc}::Slow_ArrayConcat(), v8::internal::Intl::SourceString(), v8::internal::Object::SpeciesConstructor(), v8::internal::CodeStubAssembler::SpeciesConstructor(), StackOverflow(), v8::TryCatch::StackTrace(), StackTraceString(), v8::internal::CpuProfiler::StartProfiling(), v8::internal::anonymous_namespace{asm-js.cc}::StdlibMathMember(), v8::internal::Debug::StopSideEffectCheckMode(), v8::internal::StoreIC::Store(), v8::internal::KeyedStoreIC::StoreElementHandler(), v8::internal::StoreHandler::StoreElementTransition(), v8::internal::TranslatedState::StoreMaterializedValuesAndDeopt(), v8::internal::StoreHandler::StoreThroughPrototype(), v8::internal::StoreHandler::StoreTransition(), v8::internal::anonymous_namespace{runtime-strings.cc}::StringAdd_StringConstant_Internalize(), v8::internal::JSRegExp::StringFromFlags(), v8::internal::JsonStringifier::Stringify(), v8::JSON::Stringify(), v8::internal::StringReplaceGlobalAtomRegExpWithString(), v8::internal::StringReplaceGlobalRegExpWithEmptyString(), v8::internal::StringReplaceOneCharWithString(), v8::internal::wasm::WasmInterpreterRuntime::StructNewUninitialized(), v8::internal::anonymous_namespace{runtime-literals.cc}::JSObjectWalkVisitor< ContextObject >::StructureWalk(), v8::internal::JSDisplayNames::StyleAsString(), v8::internal::JSListFormat::StyleAsString(), v8::internal::anonymous_namespace{js-number-format.cc}::StyleAsString(), v8::internal::anonymous_namespace{js-relative-time-format.cc}::StyleAsString(), v8::internal::anonymous_namespace{js-duration-format.cc}::StyleToString(), v8::internal::anonymous_namespace{runtime-classes.cc}::SubstituteValues(), v8::internal::Intl::SupportedValuesOf(), SymbolFor(), v8::internal::TF_BUILTIN(), v8::internal::anonymous_namespace{builtins-bigint.cc}::ThisBigIntValue(), ThrowAt(), v8::internal::ValueSerializer::ThrowDataCloneError(), v8::internal::anonymous_namespace{value-serializer.cc}::ThrowDeserializationExceptionIfNonePending(), v8::internal::anonymous_namespace{factory.cc}::ThrowInvalidEncodedStringBytes(), v8::internal::ErrorUtils::ThrowLoadFromNullOrUndefined(), v8::internal::anonymous_namespace{runtime-classes.cc}::ThrowNotSuperConstructor(), v8::internal::PendingCompilationErrorHandler::ThrowPendingError(), v8::internal::RegExp::ThrowRegExpException(), v8::internal::ErrorUtils::ThrowSpreadArgError(), v8::internal::anonymous_namespace{runtime-wasm.cc}::ThrowWasmSuspendError(), v8::internal::JSDateTimeFormat::TimeZoneId(), v8::internal::JSDateTimeFormat::TimeZoneIdToString(), v8::Value::ToArrayIndex(), v8::Value::ToBoolean(), v8::internal::anonymous_namespace{js-duration-format.cc}::ToDurationRecord(), v8::internal::ArrayList::ToFixedArray(), v8::internal::Name::ToFunctionName(), v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::ToHandle(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::ToInternalString(), v8::Date::ToISOString(), v8::internal::JSDateTimeFormat::ToLocaleDateTime(), v8::internal::BigInt::ToNumber(), v8::internal::PropertyDescriptor::ToObject(), v8::internal::Object::ToObjectImpl(), v8::internal::PropertyDescriptor::ToPropertyDescriptor(), v8::internal::PropertyDescriptor::ToPropertyDescriptorObject(), v8::internal::ReplacementStringBuilder::ToString(), v8::internal::StringStream::ToString(), v8::internal::IntlMathematicalValue::ToString(), v8::internal::Intl::ToString(), v8::internal::BigInt::ToString(), v8::internal::JSBoundFunction::ToString(), v8::internal::JSFunction::ToString(), v8::internal::JSLocale::ToString(), v8::internal::JSTemporalInstant::ToString(), v8::internal::JSWrappedFunction::ToString(), v8::internal::ErrorUtils::ToString(), v8::internal::temporal::ToTemporalPartialDurationRecord(), v8::internal::temporal::ToTemporalTimeRecord(), v8::Date::ToUTCString(), v8::internal::wasm::anonymous_namespace{wasm-module.cc}::ToValueTypeString(), v8::internal::JSNumberFormat::TrailingZeroDisplayString(), v8::internal::Map::TransitionToAccessorProperty(), v8::internal::SamplingHeapProfiler::TranslateAllocationNode(), v8::internal::JSPromise::TriggerPromiseReactions(), v8::internal::anonymous_namespace{js-number-format.cc}::TrimWhiteSpaceOrLineTerminator(), v8::internal::SeqString::Truncate(), v8::internal::anonymous_namespace{ic.cc}::TryConvertKey(), v8::internal::anonymous_namespace{builtins-array.cc}::TryFastArrayFill(), v8::internal::anonymous_namespace{isolate.cc}::TryGetCurrentTaskPromise(), v8::internal::JSListFormat::TypeAsString(), v8::internal::JSPluralRules::TypeAsString(), v8::internal::Object::TypeOf(), v8::internal::anonymous_namespace{uri.cc}::UnescapeSlow(), v8::internal::anonymous_namespace{js-locale.cc}::UnicodeKeywordValue(), v8::internal::FeedbackVector::UninitializedSentinel(), v8::internal::anonymous_namespace{js-relative-time-format.cc}::UnitAsString(), v8::internal::anonymous_namespace{js-number-format.cc}::UnitDisplayString(), v8::internal::wasm::WasmInterpreterRuntime::UnpackException(), v8::internal::UnscopableLookup(), v8::internal::JSDateTimeFormat::UnwrapDateTimeFormat(), v8::internal::JSNumberFormat::UnwrapNumberFormat(), v8::internal::IC::update_lookup_start_object_map(), v8::internal::WasmTableObject::UpdateDispatchTable(), v8::internal::TranslatedState::UpdateFromPreviouslyMaterializedObjects(), v8::internal::IC::UpdateMegaDOMIC(), v8::internal::anonymous_namespace{js-number-format.cc}::UseGroupingFromSkeleton(), v8::anonymous_namespace{wasm-js.cc}::v8_str(), v8::internal::JSTypedArray::Validate(), v8::internal::JSReceiver::ValidateAndApplyPropertyDescriptor(), v8::internal::Intl::ValidateAndCanonicalizeUnicodeLocaleId(), v8::Isolate::ValidateAndCanonicalizeUnicodeLocaleId(), v8::internal::ValidateAtomicAccess(), v8::internal::ValidateIntegerTypedArray(), v8::internal::ObjectCacheIndexMap::Values(), v8::internal::VectorToByteArray(), v8::internal::anonymous_namespace{intl-objects.cc}::VectorToJSArray(), wasm::VecToString(), v8::internal::ScopeIterator::VisitLocals(), v8::internal::ScopeIterator::VisitLocalScope(), v8::internal::FutexEmulation::WaitAsync(), v8::internal::JSAtomicsCondition::WaitAsync(), WalkCallStackAndPromiseTree(), v8::internal::anonymous_namespace{isolate.cc}::WalkPromiseTreeInternal(), wasm::anonymous_namespace{c-api.cc}::WasmRefToV8(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::WasmSimd128ToString(), v8::internal::wasm::WasmToJSObject(), v8::internal::ScopeIterator::WithContextExtension(), v8::internal::DebugEvaluate::WithTopmostArguments(), v8::internal::ValueSerializer::WriteHostObject(), v8::internal::ValueSerializer::WriteJSArrayBuffer(), v8::internal::ValueSerializer::WriteJSError(), v8::internal::ValueSerializer::WriteJSMap(), and v8::internal::ValueSerializer::WriteJSSet().
FatalProcessOutOfHeapMemory()
void v8::internal::Isolate::FatalProcessOutOfHeapMemory (const char * location) [inline]
Definition at line 1053 of file isolate.h.
                                                         {
    heap()->FatalProcessOutOfMemory(location);
  }
References heap().
feedback_vector_access()
base::Mutex* v8::internal::Isolate::feedback_vector_access () [inline]
Definition at line 754 of file isolate.h.
{ return &feedback_vector_access_; }
FillCache()
void v8::internal::Isolate::FillCache () [private]
FindOrAllocatePerThreadDataForThisThread()
Isolate::PerIsolateThreadData * v8::internal::Isolate::FindOrAllocatePerThreadDataForThisThread ()
Definition at line 547 of file isolate.cc.
                                                  {
  ThreadId thread_id = ThreadId::Current();
  PerIsolateThreadData* per_thread = nullptr;
  {
    base::MutexGuard lock_guard(&thread_data_table_mutex_);
    per_thread = thread_data_table_.Lookup(thread_id);
    if (per_thread == nullptr) {
      if (v8_flags.adjust_os_scheduling_parameters) {
        base::OS::AdjustSchedulingParams();
      }
      per_thread = new PerIsolateThreadData(this, thread_id);
      thread_data_table_.Insert(per_thread);
    }
    DCHECK(thread_data_table_.Lookup(thread_id) == per_thread);
  }
  return per_thread;
}
References v8::base::OS::AdjustSchedulingParams(), v8::internal::ThreadId::Current(), v8::internal::DCHECK(), v8::internal::Isolate::ThreadDataTable::Insert(), v8::internal::Isolate::ThreadDataTable::Lookup(), thread_data_table_, thread_data_table_mutex_, thread_id(), and v8::internal::v8_flags.
Referenced by v8::internal::ThreadManager::ArchiveThread(), Enter(), v8::internal::StackGuard::FreeThreadResources(), and v8::internal::StackGuard::InitThread().
FindPerThreadDataForThisThread()
Isolate::PerIsolateThreadData * v8::internal::Isolate::FindPerThreadDataForThisThread ()
Definition at line 579 of file isolate.cc.
                                                                     {
  ThreadId thread_id = ThreadId::Current();
  return FindPerThreadDataForThread(thread_id);
}
References v8::internal::ThreadId::Current(), FindPerThreadDataForThread(), and thread_id().
Referenced by v8::internal::ThreadManager::IsArchived(), and v8::internal::ThreadManager::RestoreThread().
FindPerThreadDataForThread()
Isolate::PerIsolateThreadData * v8::internal::Isolate::FindPerThreadDataForThread (ThreadId thread_id)
Definition at line 584 of file isolate.cc.
                        {
  PerIsolateThreadData* per_thread = nullptr;
  {
    base::MutexGuard lock_guard(&thread_data_table_mutex_);
    per_thread = thread_data_table_.Lookup(thread_id);
  }
  return per_thread;
}
References v8::internal::Isolate::ThreadDataTable::Lookup(), thread_data_table_, thread_data_table_mutex_, and thread_id().
Referenced by FindPerThreadDataForThisThread().
FireBeforeCallEnteredCallback()
void v8::internal::Isolate::FireBeforeCallEnteredCallback () [inline]
Definition at line 205 of file isolate-inl.h.
                                            {
  for (auto& callback : before_call_entered_callbacks_) {
    callback(reinterpret_cast<v8::Isolate*>(this));
  }
}
References before_call_entered_callbacks_.
FireCallCompletedCallback()
void v8::internal::Isolate::FireCallCompletedCallback (MicrotaskQueue * microtask_queue) [inline]
Definition at line 1831 of file isolate.h.
                                                                  {
    if (!thread_local_top()->CallDepthIsZero()) return;
    FireCallCompletedCallbackInternal(microtask_queue);
  }
FireCallCompletedCallbackInternal()
void v8::internal::Isolate::FireCallCompletedCallbackInternal (MicrotaskQueue * microtask_queue) [private]
Definition at line 6525 of file isolate.cc.
                                     {
  DCHECK(thread_local_top()->CallDepthIsZero());
  bool perform_checkpoint =
      microtask_queue &&
      microtask_queue->microtasks_policy() == v8::MicrotasksPolicy::kAuto &&
      !is_execution_terminating();
  v8::Isolate* isolate = reinterpret_cast<v8::Isolate*>(this);
  if (perform_checkpoint) microtask_queue->PerformCheckpoint(isolate);
  if (call_completed_callbacks_.empty()) return;
  // Fire callbacks. Increase call depth to prevent recursive callbacks.
  v8::Isolate::SuppressMicrotaskExecutionScope suppress(isolate);
  std::vector<CallCompletedCallback> callbacks(call_completed_callbacks_);
  for (auto& callback : callbacks) {
    callback(reinterpret_cast<v8::Isolate*>(this));
  }
}
References call_completed_callbacks_, v8::internal::DCHECK(), is_execution_terminating(), v8::internal::Factory::isolate(), v8::kAuto, v8::internal::MicrotaskQueue::microtasks_policy(), v8::internal::MicrotaskQueue::PerformCheckpoint(), and thread_local_top().
flush_denormals()
bool v8::internal::Isolate::flush_denormals () const [inline]
Definition at line 2173 of file isolate.h.
{ return flush_denormals_; }
Referenced by v8::internal::LazyCompileDispatcher::DoBackgroundWork(), v8::internal::BackgroundCompileTask::Run(), v8::internal::baseline::ConcurrentBaselineCompiler::JobDispatcher::Run(), and v8::internal::OptimizingCompileTaskExecutor::CompileTask::Run().
force_slow_path()
bool v8::internal::Isolate::force_slow_path () const [inline]
Definition at line 1788 of file isolate.h.
{ return force_slow_path_; }
Referenced by v8::internal::anonymous_namespace{builtins-array.cc}::CanUseFastArrayModification(), v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::HoleyPrototypeLookupRequired(), and v8::internal::RegExpUtils::IsUnmodifiedRegExp().
force_slow_path_address()
bool* v8::internal::Isolate::force_slow_path_address () [inline]
Definition at line 1789 of file isolate.h.
{ return &force_slow_path_; }
ForSandbox()
Isolate* v8::internal::Isolate::ForSandbox () [inline], [private]
Definition at line 2491 of file isolate.h.
{ return this; }
Free()
void v8::internal::Isolate::Free (Isolate * isolate) [static]
Definition at line 4221 of file isolate.cc.
                                   {
  DCHECK_NOT_NULL(isolate);
  // Free the memory allocated for the Isolate.
  base::AlignedFree(isolate);
}
References v8::base::AlignedFree(), DCHECK_NOT_NULL, and v8::internal::Factory::isolate().
Referenced by Delete(), and v8::Isolate::Free().
FreeThreadResources()
void v8::internal::Isolate::FreeThreadResources () [inline]
Definition at line 963 of file isolate.h.
{ thread_local_top()->Free(); }
Referenced by Deinit(), and v8::internal::ThreadManager::FreeThreadResources().
Freeze()
void v8::internal::Isolate::Freeze (bool is_frozen) [inline]
Definition at line 2456 of file isolate.h.
                              {
    is_frozen_ = is_frozen;
    if (v8_flags.memory_reducer_respects_frozen_state && IsFrozen()) {
      // We will either finalize an ongoing GC, or simply do a GC to reclaim
      // any unreachable memory.
      heap()->FinalizeIncrementalMarkingAtomicallyIfRunning(
          i::GarbageCollectionReason::kFrozen);
      heap()->EnsureSweepingCompleted(
          Heap::SweepingForcedFinalizationMode::kUnifiedHeap);
    }
  }
References heap(), v8::internal::Heap::kUnifiedHeap, and v8::internal::v8_flags.
Referenced by v8::Isolate::Freeze().
FromHeap()
static Isolate* v8::internal::Isolate::FromHeap (const Heap * heap) [inline], [static]
Definition at line 1217 of file isolate.h.
                                             {
    return reinterpret_cast<Isolate*>(reinterpret_cast<Address>(heap) -
                                      OFFSET_OF(Isolate, heap_));
  }
References heap(), and OFFSET_OF.
Referenced by v8::internal::AllocationTracker::AllocationEvent(), v8::internal::MemoryController< Trait >::BoundAllocationLimit(), v8::internal::ReplacementStringBuilder::EnsureCapacity(), v8::internal::V8HeapExplorer::ExtractJSObjectReferences(), v8::internal::GetIsolateFromHeapObject(), v8::internal::GetIsolateFromWritableObject(), v8::internal::V8HeapExplorer::GetStrongGcSubrootName(), v8::internal::MemoryController< Trait >::GrowingFactor(), v8::internal::V8HeapExplorer::isolate(), v8::internal::Heap::isolate(), and v8::internal::ReplacementStringBuilder::ToString().
FromRootAddress()
static Isolate* v8::internal::Isolate::FromRootAddress (Address isolate_root) [inline], [static]
Definition at line 1261 of file isolate.h.
                                                        {
    return reinterpret_cast<Isolate*>(isolate_root - isolate_root_bias());
  }
full_transition_array_access()
base::Mutex* v8::internal::Isolate::full_transition_array_access () [inline]
Definition at line 764 of file isolate.h.
                                            {
    return &full_transition_array_access_;
  }
Referenced by v8::internal::TransitionsAccessor::ForEachTransitionTo(), v8::internal::TransitionsAccessor::ForEachTransitionWithKey(), v8::internal::TransitionsAccessor::InsertHelper(), v8::internal::TransitionsAccessor::PutPrototypeTransition(), v8::internal::TransitionsAccessor::SearchSpecial(), and v8::internal::TransitionsAccessor::SearchTransition().
futex_wait_list_node()
FutexWaitListNode* v8::internal::Isolate::futex_wait_list_node () [inline]
Definition at line 1998 of file isolate.h.
{ return &futex_wait_list_node_; }
Referenced by v8::internal::StackGuard::RequestInterrupt(), and v8::internal::FutexEmulation::WaitSync().
fuzzer_rng()
base::RandomNumberGenerator * v8::internal::Isolate::fuzzer_rng ()
Definition at line 6431 of file isolate.cc.
                                               {
  if (fuzzer_rng_ == nullptr) {
    int64_t seed = v8_flags.fuzzer_random_seed;
    if (seed == 0) {
      seed = random_number_generator()->initial_seed();
    }
    fuzzer_rng_ = new base::RandomNumberGenerator(seed);
  }
  return fuzzer_rng_;
}
References fuzzer_rng_, v8::base::RandomNumberGenerator::initial_seed(), random_number_generator(), and v8::internal::v8_flags.
Referenced by v8::internal::MarkCompactCollector::CollectEvacuationCandidates(), v8::internal::EvacuateVisitorBase::EvacuateVisitorBase(), v8::internal::StressScavengeObserver::NextLimit(), and v8::internal::Heap::NextStressMarkingLimit().
GenerateIdentityHash()
int v8::internal::Isolate::GenerateIdentityHash (uint32_t mask)
Definition at line 6444 of file isolate.cc.
                                               {
  int hash;
  int attempts = 0;
  do {
    hash = random_number_generator()->NextInt() & mask;
  } while (hash == 0 && attempts++ < 30);
  return hash != 0 ? hash : 1;
}
References v8::base::RandomNumberGenerator::NextInt(), and random_number_generator().
Referenced by v8::internal::JSReceiver::CreateIdentityHash(), and v8::internal::Factory::NewSymbolInternal().
get_address_from_id()
Address v8::internal::Isolate::get_address_from_id (IsolateAddressId id)
Definition at line 596 of file isolate.cc.
                                                        {
  return isolate_addresses_[id];
}
References id(), and isolate_addresses_.
Referenced by v8::internal::ExternalReferenceTable::AddIsolateAddresses(), and v8::internal::ExternalReference::Create().
get_capture_stack_trace_for_uncaught_exceptions()
bool v8::internal::Isolate::get_capture_stack_trace_for_uncaught_exceptions () const
Definition at line 3689 of file isolate.cc.
                                                                    {
  return capture_stack_trace_for_uncaught_exceptions_;
}
References capture_stack_trace_for_uncaught_exceptions_.
Referenced by v8::Shell::PromiseRejectCallback().
GetAbstractPC()
Address v8::internal::Isolate::GetAbstractPC (int * line, int * column)
Definition at line 1548 of file isolate.cc.
                                                     {
  JavaScriptStackFrameIterator it(this);
  if (it.done()) {
    *line = -1;
    *column = -1;
    return kNullAddress;
  }
  JavaScriptFrame* frame = it.frame();
  DCHECK(!frame->is_builtin());
  DirectHandle<SharedFunctionInfo> shared(frame->function()->shared(), this);
  SharedFunctionInfo::EnsureSourcePositionsAvailable(this, shared);
  int position = frame->position();
  Tagged<Object> maybe_script = frame->function()->shared()->script();
  if (IsScript(maybe_script)) {
    DirectHandle<Script> script(Cast<Script>(maybe_script), this);
    Script::PositionInfo info;
    Script::GetPositionInfo(script, position, &info);
    *line = info.line + 1;
    *column = info.column + 1;
  } else {
    *line = position;
    *column = -1;
  }
  if (frame->is_unoptimized()) {
    UnoptimizedJSFrame* iframe = static_cast<UnoptimizedJSFrame*>(frame);
    Address bytecode_start =
        iframe->GetBytecodeArray()->GetFirstBytecodeAddress();
    return bytecode_start + iframe->GetBytecodeOffset();
  }
  return frame->pc();
}
References v8::internal::Script::PositionInfo::column, v8::internal::DCHECK(), v8::internal::JavaScriptStackFrameIterator::done(), v8::internal::SharedFunctionInfo::EnsureSourcePositionsAvailable(), v8::internal::JavaScriptStackFrameIterator::frame(), v8::internal::JavaScriptFrame::function(), v8::internal::UnoptimizedJSFrame::GetBytecodeArray(), v8::internal::UnoptimizedJSFrame::GetBytecodeOffset(), v8::internal::Script::GetPositionInfo(), v8::internal::StackFrame::is_builtin(), v8::internal::JavaScriptFrame::is_unoptimized(), v8::internal::kNullAddress, v8::internal::Script::PositionInfo::line, v8::internal::StackFrame::pc(), v8::internal::CommonFrame::position(), and v8::internal::script.
Referenced by v8::internal::V8FileLogger::ICEvent(), and v8::internal::V8FileLogger::MapEvent().
GetAndClearCurrentDeoptimizer()
Deoptimizer* v8::internal::Isolate::GetAndClearCurrentDeoptimizer () [inline]
Definition at line 1330 of file isolate.h.
                                               {
    Deoptimizer* result = current_deoptimizer_;
    CHECK_NOT_NULL(result);
    current_deoptimizer_ = nullptr;
    return result;
  }
References CHECK_NOT_NULL, and v8::base::internal::result.
Referenced by v8::internal::Deoptimizer::Grab().
GetAndIncNextUniqueSfiId()
uint32_t v8::internal::Isolate::GetAndIncNextUniqueSfiId () [inline]
Definition at line 1863 of file isolate.h.
                                      {
    return next_unique_sfi_id_.fetch_add(1, std::memory_order_relaxed);
  }
Referenced by v8::internal::ObjectPostProcessor::PostProcessSharedFunctionInfo().
GetCodePages()
std::vector< MemoryRange > * v8::internal::Isolate::GetCodePages () const
Definition at line 3138 of file isolate.cc.
                                                    {
  return code_pages_.load(std::memory_order_acquire);
}
References code_pages_.
Referenced by AddCodeMemoryRange(), v8::Isolate::CopyCodePages(), InitializeCodeRanges(), and RemoveCodeMemoryChunk().
GetCodeTracer()
CodeTracer * v8::internal::Isolate::GetCodeTracer ()
Definition at line 6217 of file isolate.cc.
                                   {
  if (code_tracer() == nullptr) set_code_tracer(new CodeTracer(id()));
  return code_tracer();
}
Referenced by v8::internal::baseline::BaselineBatchCompilerJob::BaselineBatchCompilerJob(), v8::internal::RegExpImpl::Compile(), v8::internal::anonymous_namespace{runtime-compiler.cc}::CompileOptimizedOSRFromMaglev(), v8::internal::SharedFunctionInfo::DisableOptimization(), v8::internal::SharedFunctionInfo::DiscardCompiledMetadata(), v8::internal::maglev::MaglevCompiler::GenerateCode(), v8::internal::compiler::TFPipelineData::GetCodeTracer(), v8::internal::compiler::turboshaft::PipelineData::GetCodeTracer(), v8::internal::baseline::BaselineCompilerTask::Install(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::IsSupportedWasmFastApiFunction(), v8::internal::wasm::JSToWasmWrapperCompilationUnit::JSToWasmWrapperCompilationUnit(), v8::internal::compiler::PrintCode(), v8::internal::compiler::anonymous_namespace{pipeline.cc}::PrintFunctionSource(), v8::internal::compiler::anonymous_namespace{pipeline.cc}::PrintInlinedFunctionInfo(), v8::internal::baseline::BaselineBatchCompiler::ShouldCompileBatch(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceAbortedJob(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceAbortedMaglevCompile(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceCompletedJob(), v8::internal::Deoptimizer::TraceDeoptAll(), v8::internal::Deoptimizer::TraceEvictFromOptimizedCodeCache(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceFinishBaselineCompile(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceFinishMaglevCompile(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceFinishTurbofanCompile(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceMarkForAlwaysOpt(), v8::internal::Deoptimizer::TraceMarkForDeoptimization(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceOptimizedCodeCacheHit(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceOptimizeForAlwaysOpt(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceOptimizeOSRAvailable(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceOptimizeOSRFinished(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceOptimizeOSRStarted(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceOptimizeOSRUnavailable(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TracePrepareJob(), v8::internal::anonymous_namespace{tiering-manager.cc}::TraceRecompile(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceStartBaselineCompile(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceStartMaglevCompile(), and v8::internal::anonymous_namespace{tiering-manager.cc}::TrySetOsrUrgency().
GetContextFromRecorderContextId()
MaybeLocal< v8::Context > v8::internal::Isolate::GetContextFromRecorderContextId (v8::metrics::Recorder::ContextId id)
Definition at line 7578 of file isolate.cc.
                                   {
  auto result = recorder_context_id_map_.find(id.id_);
  if (result == recorder_context_id_map_.end() || result->second.IsEmpty())
    return MaybeLocal<v8::Context>();
  return result->second.Get(reinterpret_cast<v8::Isolate*>(this));
}
References id_, recorder_context_id_map_, and v8::base::internal::result.
Referenced by v8::metrics::Recorder::GetContext().
GetCurrentLongTaskStats()
v8::metrics::LongTaskStats * v8::internal::Isolate::GetCurrentLongTaskStats ()
Definition at line 7593 of file isolate.cc.
                                                         {
  UpdateLongTaskStats();
  return &long_task_stats_;
}
References long_task_stats_, and UpdateLongTaskStats().
Referenced by v8::metrics::LongTaskStats::Get(), and v8::internal::GCTracer::StopObservablePause().
GetData()
void* v8::internal::Isolate::GetData (uint32_t slot) const [inline]
Definition at line 1570 of file isolate.h.
                                     {
    DCHECK_LT(slot, Internals::kNumIsolateDataSlots);
    return isolate_data_.embedder_data_[slot];
  }
References DCHECK_LT, and v8::internal::Internals::kNumIsolateDataSlots.
GetDateCacheStampAndRecordUsage()
Tagged<Smi> v8::internal::Isolate::GetDateCacheStampAndRecordUsage () [inline]
Definition at line 1659 of file isolate.h.
                                                {
    isolate_data()->is_date_cache_used_ = true;
    return date_cache_stamp();
  }
Referenced by v8::internal::JSDate::SetCachedFields().
GetDetailedStackTrace()
Handle< StackTraceInfo > v8::internal::Isolate::GetDetailedStackTrace (DirectHandle< JSReceiver > error_object)
Definition at line 1522 of file isolate.cc.
                                                 {
  ErrorUtils::StackPropertyLookupResult lookup =
      ErrorUtils::GetErrorStackProperty(this, maybe_error_object);
  if (!IsErrorStackData(*lookup.error_stack)) return {};
  return handle(Cast<ErrorStackData>(lookup.error_stack)->stack_trace(), this);
}
References v8::internal::ErrorUtils::StackPropertyLookupResult::error_stack, v8::internal::ErrorUtils::GetErrorStackProperty(), and v8::internal::handle().
Referenced by ComputeLocationFromDetailedStackTrace(), CreateMessage(), CreateMessageFromException(), and v8::Exception::GetStackTrace().
GetExternallyCompiledFilename()
const char * v8::internal::Isolate::GetExternallyCompiledFilename (int index) const
Definition at line 6891 of file isolate.cc.
                                                                  {
  if (embedded_file_writer_ != nullptr) {
    return embedded_file_writer_->GetExternallyCompiledFilename(index);
  }
  return "";
}
References embedded_file_writer_, v8::internal::EmbeddedFileWriterInterface::GetExternallyCompiledFilename(), and v8::internal::index.
Referenced by v8::internal::compiler::RawMachineAssembler::GetCurrentExternalSourcePosition().
GetExternallyCompiledFilenameCount()
int v8::internal::Isolate::GetExternallyCompiledFilenameCount () const
Definition at line 6898 of file isolate.cc.
                                                      {
  if (embedded_file_writer_ != nullptr) {
    return embedded_file_writer_->GetExternallyCompiledFilenameCount();
  }
  return 0;
}
References embedded_file_writer_, and v8::internal::EmbeddedFileWriterInterface::GetExternallyCompiledFilenameCount().
GetImportAttributesFromArgument()
MaybeDirectHandle< FixedArray > v8::internal::Isolate::GetImportAttributesFromArgument (MaybeDirectHandle< Object > maybe_import_options_argument) [private]
Definition at line 6707 of file isolate.cc.
                                                             {
  DirectHandle<FixedArray> import_attributes_array =
      factory()->empty_fixed_array();
  DirectHandle<Object> import_options_argument;
  if (!maybe_import_options_argument.ToHandle(&import_options_argument) ||
      IsUndefined(*import_options_argument)) {
    return import_attributes_array;
  }
  // The parser shouldn't have allowed the second argument to import() if
  // the flag wasn't enabled.
  DCHECK(v8_flags.harmony_import_attributes);
  if (!IsJSReceiver(*import_options_argument)) {
    this->Throw(
        *factory()->NewTypeError(MessageTemplate::kNonObjectImportArgument));
    return MaybeDirectHandle<FixedArray>();
  }
  DirectHandle<JSReceiver> import_options_argument_receiver =
      Cast<JSReceiver>(import_options_argument);
  DirectHandle<Object> import_attributes_object;
  if (v8_flags.harmony_import_attributes) {
    DirectHandle<Name> with_key = factory()->with_string();
    if (!JSReceiver::GetProperty(this, import_options_argument_receiver,
                                 with_key)
             .ToHandle(&import_attributes_object)) {
      // This can happen if the property has a getter function that throws
      // an error.
      return MaybeDirectHandle<FixedArray>();
    }
  }
  // If there is no 'with' option in the options bag, it's not an error. Just do
  // the import() as if no attributes were provided.
  if (IsUndefined(*import_attributes_object)) return import_attributes_array;
  if (!IsJSReceiver(*import_attributes_object)) {
    this->Throw(
        *factory()->NewTypeError(MessageTemplate::kNonObjectAttributesOption));
    return MaybeDirectHandle<FixedArray>();
  }
  DirectHandle<JSReceiver> import_attributes_object_receiver =
      Cast<JSReceiver>(import_attributes_object);
  DirectHandle<FixedArray> attribute_keys;
  if (!KeyAccumulator::GetKeys(this, import_attributes_object_receiver,
                               KeyCollectionMode::kOwnOnly, ENUMERABLE_STRINGS,
                               GetKeysConversion::kConvertToString)
           .ToHandle(&attribute_keys)) {
    // This happens if the attributes object is a Proxy whose ownKeys() or
    // getOwnPropertyDescriptor() trap throws.
    return MaybeDirectHandle<FixedArray>();
  }
  bool has_non_string_attribute = false;
  // The attributes will be passed to the host in the form: [key1,
  // value1, key2, value2, ...].
  constexpr size_t kAttributeEntrySizeForDynamicImport = 2;
  import_attributes_array = factory()->NewFixedArray(static_cast<int>(
      attribute_keys->length() * kAttributeEntrySizeForDynamicImport));
  for (int i = 0; i < attribute_keys->length(); i++) {
    DirectHandle<String> attribute_key(Cast<String>(attribute_keys->get(i)),
                                       this);
    DirectHandle<Object> attribute_value;
    if (!Object::GetPropertyOrElement(this, import_attributes_object_receiver,
                                      attribute_key)
             .ToHandle(&attribute_value)) {
      // This can happen if the property has a getter function that throws
      // an error.
      return MaybeDirectHandle<FixedArray>();
    }
    if (!IsString(*attribute_value)) {
      has_non_string_attribute = true;
    }
    import_attributes_array->set((i * kAttributeEntrySizeForDynamicImport),
                                 *attribute_key);
    import_attributes_array->set((i * kAttributeEntrySizeForDynamicImport) + 1,
                                 *attribute_value);
  }
  if (has_non_string_attribute) {
    this->Throw(*factory()->NewTypeError(
        MessageTemplate::kNonStringImportAttributeValue));
    return MaybeDirectHandle<FixedArray>();
  }
  return import_attributes_array;
}
References v8::internal::DCHECK(), v8::internal::ENUMERABLE_STRINGS, factory(), v8::internal::KeyAccumulator::GetKeys(), v8::internal::JSReceiver::GetProperty(), v8::internal::Object::GetPropertyOrElement(), v8::internal::kConvertToString, v8::internal::kOwnOnly, v8::internal::FactoryBase< Impl >::NewFixedArray(), Throw(), v8::internal::MaybeDirectHandle< T >::ToHandle(), v8::anonymous_namespace{api.cc}::ToHandle(), and v8::internal::v8_flags.
Referenced by RunHostImportModuleDynamicallyCallback().
GetIncumbentContext()
DirectHandle< NativeContext > v8::internal::Isolate::GetIncumbentContext () [inline]
Definition at line 68 of file isolate-inl.h.
                                                         {
  Tagged<Context> maybe_topmost_script_having_context =
      topmost_script_having_context();
  if (V8_LIKELY(!maybe_topmost_script_having_context.is_null())) {
    // The topmost script-having context value is guaranteed to be valid only
    // inside the Api callback however direct calls of Api callbacks from
    // builtins or optimized code do not change the current VM state, so we
    // allow JS VM state too.
    DCHECK(current_vm_state() == EXTERNAL || // called from C++ code
           current_vm_state() == JS); // called from JS code directly
    Tagged<NativeContext> incumbent_context =
        maybe_topmost_script_having_context->native_context();
    DCHECK_EQ(incumbent_context, *GetIncumbentContextSlow());
    return direct_handle(incumbent_context, this);
  }
  return GetIncumbentContextSlow();
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::direct_handle(), v8::EXTERNAL, GetIncumbentContextSlow(), v8::internal::Tagged< HeapObject >::is_null(), v8::JS, topmost_script_having_context(), and V8_LIKELY.
Referenced by v8::internal::wasm::WasmEngine::CreateAsyncCompileJob(), v8::Isolate::GetIncumbentContext(), and v8::internal::ValidateFunctionCallbackInfo().
GetIncumbentContextSlow()
DirectHandle< NativeContext > v8::internal::Isolate::GetIncumbentContextSlow ()
Definition at line 3783 of file isolate.cc.
                                                             {
  JavaScriptStackFrameIterator it(this);
  // 1st candidate: most-recently-entered author function's context
  // if it's newer than the last Context::BackupIncumbentScope entry.
  //
  // NOTE: This code assumes that the stack grows downward.
  Address top_backup_incumbent =
      top_backup_incumbent_scope()
          ? top_backup_incumbent_scope()->JSStackComparableAddressPrivate()
          : 0;
  if (!it.done() &&
      (!top_backup_incumbent || it.frame()->sp() < top_backup_incumbent)) {
    Tagged<Context> context = Cast<Context>(it.frame()->context());
    // If the topmost_script_having_context is set then it must be correct.
    if (DEBUG_BOOL && !topmost_script_having_context().is_null()) {
      DCHECK_EQ(topmost_script_having_context()->native_context(),
                context->native_context());
    }
    return DirectHandle<NativeContext>(context->native_context(), this);
  }
  DCHECK(topmost_script_having_context().is_null());
  // 2nd candidate: the last Context::Scope's incumbent context if any.
  if (top_backup_incumbent_scope()) {
    v8::Local<v8::Context> incumbent_context =
        top_backup_incumbent_scope()->backup_incumbent_context_;
    return Utils::OpenDirectHandle(*incumbent_context);
  }
  // Last candidate: the entered context or microtask context.
  // Given that there is no other author function is running, there must be
  // no cross-context function running, then the incumbent realm must match
  // the entry realm.
  v8::Local<v8::Context> entered_context =
      reinterpret_cast<v8::Isolate*>(this)->GetEnteredOrMicrotaskContext();
  return Utils::OpenDirectHandle(*entered_context);
}
References v8::Context::BackupIncumbentScope::backup_incumbent_context_, context(), v8::internal::JavaScriptFrame::context(), v8::internal::DCHECK(), DCHECK_EQ, DEBUG_BOOL, v8::internal::JavaScriptStackFrameIterator::done(), v8::internal::JavaScriptStackFrameIterator::frame(), v8::Context::BackupIncumbentScope::JSStackComparableAddressPrivate(), native_context(), v8::Utils::OpenDirectHandle(), v8::internal::StackFrame::sp(), top_backup_incumbent_scope(), and topmost_script_having_context().
Referenced by GetIncumbentContext().
GetMainThreadIsolateUnsafe()
Isolate* v8::internal::Isolate::GetMainThreadIsolateUnsafe () [inline]
Definition at line 2229 of file isolate.h.
{ return this; }
Referenced by v8::internal::DeclarationScope::AllocateScopeInfos(), and v8::internal::SharedFunctionInfo::GetBytecodeArray().
GetNextScriptId()
int v8::internal::Isolate::GetNextScriptId ()
Definition at line 7179 of file isolate.cc.
{ return heap()->NextScriptId(); }
References heap(), and v8::internal::Heap::NextScriptId().
Referenced by v8::internal::Factory::CloneScript(), v8::internal::UnoptimizedCompileFlags::ForToplevelCompile(), and v8::internal::LocalIsolate::GetNextScriptId().
GetOrRegisterRecorderContextId()
v8::metrics::Recorder::ContextId v8::internal::Isolate::GetOrRegisterRecorderContextId (DirectHandle< NativeContext > context)
Definition at line 7553 of file isolate.cc.
                                         {
  if (serializer_enabled_) return v8::metrics::Recorder::ContextId::Empty();
  i::Tagged<i::Object> id = context->recorder_context_id();
  if (IsNullOrUndefined(id)) {
    CHECK_LT(last_recorder_context_id_, i::Smi::kMaxValue);
    context->set_recorder_context_id(
        i::Smi::FromIntptr(++last_recorder_context_id_));
    v8::HandleScope handle_scope(reinterpret_cast<v8::Isolate*>(this));
    auto result = recorder_context_id_map_.emplace(
        std::piecewise_construct,
        std::forward_as_tuple(last_recorder_context_id_),
        std::forward_as_tuple(reinterpret_cast<v8::Isolate*>(this),
                              ToApiHandle<v8::Context>(context)));
    result.first->second.SetWeak(
        reinterpret_cast<void*>(last_recorder_context_id_),
        RemoveContextIdCallback, v8::WeakCallbackType::kParameter);
    return v8::metrics::Recorder::ContextId(last_recorder_context_id_);
  } else {
    DCHECK(IsSmi(id));
    return v8::metrics::Recorder::ContextId(
        static_cast<uintptr_t>(i::Smi::ToInt(id)));
  }
}
References CHECK_LT, context(), v8::internal::DCHECK(), v8::metrics::Recorder::ContextId::Empty(), v8::internal::Smi::FromIntptr(), v8::internal::IsNullOrUndefined(), v8::internal::IsSmi(), v8::internal::Smi::kMaxValue, v8::kParameter, last_recorder_context_id_, recorder_context_id_map_, RemoveContextIdCallback(), v8::base::internal::result, serializer_enabled_, and v8::internal::Smi::ToInt().
Referenced by v8::internal::wasm::AsyncCompileJob::AsyncCompileJob(), v8::internal::wasm::DeserializeNativeModule(), v8::metrics::Recorder::GetContextId(), v8::internal::anonymous_namespace{gc-tracer.cc}::GetContextId(), v8::internal::wasm::InstantiateToInstanceObject(), v8::internal::wasm::WasmEngine::SyncCompile(), and v8::internal::wasm::WasmEngine::SyncValidate().
GetShortBuiltinsCallRegion()
base::AddressRegion v8::internal::Isolate::GetShortBuiltinsCallRegion () [static]
Definition at line 415 of file isolate.cc.
                                                      {
  // Update calculations below if the assert fails.
  static_assert(kMaxPCRelativeCodeRangeInMB <= 4096);
  if (kMaxPCRelativeCodeRangeInMB == 0) {
    // Return empty region if pc-relative calls/jumps are not supported.
    return base::AddressRegion(kNullAddress, 0);
  }
  constexpr size_t max_size = std::numeric_limits<size_t>::max();
  if (uint64_t{kMaxPCRelativeCodeRangeInMB} * MB > max_size) {
    // The whole addressable space is reachable with pc-relative calls/jumps.
    return base::AddressRegion(kNullAddress, max_size);
  }
  constexpr size_t radius = kMaxPCRelativeCodeRangeInMB * MB;
  DCHECK_LT(CurrentEmbeddedBlobCodeSize(), radius);
  Address embedded_blob_code_start =
      reinterpret_cast<Address>(CurrentEmbeddedBlobCode());
  if (embedded_blob_code_start == kNullAddress) {
    // Return empty region if there's no embedded blob.
    return base::AddressRegion(kNullAddress, 0);
  }
  Address embedded_blob_code_end =
      embedded_blob_code_start + CurrentEmbeddedBlobCodeSize();
  Address region_start =
      (embedded_blob_code_end > radius) ? (embedded_blob_code_end - radius) : 0;
  Address region_end = embedded_blob_code_start + radius;
  if (region_end < embedded_blob_code_start) {
    region_end = static_cast<Address>(-1);
  }
  return base::AddressRegion(region_start, region_end - region_start);
}
References CurrentEmbeddedBlobCode(), CurrentEmbeddedBlobCodeSize(), DCHECK_LT, v8::internal::kMaxPCRelativeCodeRangeInMB, v8::internal::kNullAddress, and v8::internal::MB.
Referenced by InitializeIsShortBuiltinCallsEnabled(), and MaybeRemapEmbeddedBuiltinsIntoCodeRange().
GetSimpleStackTrace()
Handle< FixedArray > v8::internal::Isolate::GetSimpleStackTrace (DirectHandle< JSReceiver > error_object)
Definition at line 1530 of file isolate.cc.
                                                 {
  ErrorUtils::StackPropertyLookupResult lookup =
      ErrorUtils::GetErrorStackProperty(this, maybe_error_object);
  if (IsFixedArray(*lookup.error_stack)) {
    return Cast<FixedArray>(lookup.error_stack);
  }
  if (!IsErrorStackData(*lookup.error_stack)) {
    return factory()->empty_fixed_array();
  }
  auto error_stack_data = Cast<ErrorStackData>(lookup.error_stack);
  if (!error_stack_data->HasCallSiteInfos()) {
    return factory()->empty_fixed_array();
  }
  return handle(error_stack_data->call_site_infos(), this);
}
References v8::internal::ErrorUtils::StackPropertyLookupResult::error_stack, factory(), v8::internal::ErrorUtils::GetErrorStackProperty(), and v8::internal::handle().
Referenced by ComputeLocationFromSimpleStackTrace().
GetStackTraceLimit()
bool v8::internal::Isolate::GetStackTraceLimit (Isolate * isolate, int * result)
Definition at line 1715 of file isolate.cc.
                                                              {
  if (v8_flags.correctness_fuzzer_suppressions) return false;
  DirectHandle<JSObject> error = isolate->error_function();
  DirectHandle<String> key = isolate->factory()->stackTraceLimit_string();
  DirectHandle<Object> stack_trace_limit =
      JSReceiver::GetDataProperty(isolate, error, key);
  if (!IsNumber(*stack_trace_limit)) return false;
  // Ensure that limit is not negative.
  *result = std::max(
      FastD2IChecked(Object::NumberValue(Cast<Number>(*stack_trace_limit))), 0);
  if (*result != v8_flags.stack_trace_limit) {
    isolate->CountUsage(v8::Isolate::kErrorStackTraceLimit);
  }
  return true;
}
References CountUsage(), factory(), v8::internal::FastD2IChecked(), v8::internal::JSReceiver::GetDataProperty(), v8::internal::IsNumber(), v8::internal::Factory::isolate(), v8::Isolate::kErrorStackTraceLimit, v8::internal::key, v8::internal::Object::NumberValue(), v8::base::internal::result, and v8::internal::v8_flags.
Referenced by CaptureAndSetErrorStack(), and v8::Isolate::GetStackTraceLimit().
GetTurboCfgFileName()
std::string v8::internal::Isolate::GetTurboCfgFileName (Isolate * isolate) [static]
Definition at line 7182 of file isolate.cc.
                                                       {
  if (const char* filename = v8_flags.trace_turbo_cfg_file) return filename;
  std::ostringstream os;
  os << "turbo-" << base::OS::GetCurrentProcessId() << "-";
  if (isolate != nullptr) {
    os << isolate->id();
  } else {
    os << "any";
  }
  os << ".cfg";
  return os.str();
}
References v8::base::OS::GetCurrentProcessId(), id(), v8::internal::Factory::isolate(), and v8::internal::v8_flags.
Referenced by Init(), and v8::internal::V8::Initialize().
GetTurboStatistics()
std::shared_ptr< CompilationStatistics > v8::internal::Isolate::GetTurboStatistics ()
Definition at line 6199 of file isolate.cc.
                                                                 {
  if (turbo_statistics_ == nullptr) {
    turbo_statistics_.reset(new CompilationStatistics());
  }
  return turbo_statistics_;
}
References turbo_statistics_.
Referenced by v8::internal::compiler::anonymous_namespace{pipeline.cc}::CreatePipelineStatistics(), v8::internal::compiler::Pipeline::GenerateCodeForTesting(), v8::internal::compiler::Pipeline::GenerateTurboshaftCodeForTesting(), and v8::internal::compiler::CodeAssemblerCompilationJob::PrepareJobImpl().
global_handles()
GlobalHandles* v8::internal::Isolate::global_handles () const [inline]
Definition at line 1431 of file isolate.h.
{ return global_handles_; }
Referenced by v8::internal::SnapshotCreatorImpl::AddContext(), v8::internal::ValueDeserializer::AddObjectWithID(), v8::internal::wasm::AsyncCompileJob::AsyncCompileJob(), v8::internal::SerializedHandleChecker::CheckGlobalAndEternalHandles(), v8::internal::MarkCompactCollector::ClearNonLiveReferences(), v8::internal::MinorMarkSweepCollector::ClearNonLiveReferences(), v8::internal::Heap::CollectAllAvailableGarbage(), v8::internal::MinorMarkSweepCollector::CollectGarbage(), v8::internal::ScavengerCollector::CollectGarbage(), v8::internal::Heap::CollectGarbage(), v8::internal::V8HeapExplorer::CollectTemporaryGlobalObjectsTags(), v8::internal::wasm::AsyncStreamingProcessor::Deserialize(), v8::internal::wasm::FrameState::DisposeCaughtExceptionsArray(), v8::internal::MemoryMeasurement::EnqueueRequest(), v8::internal::baseline::BaselineBatchCompiler::EnsureQueueCapacity(), v8::internal::wasm::WasmInterpreterThread::EnsureRefStackSpace(), v8::internal::MarkCompactCollector::Finish(), v8::internal::Managed< CppType >::From(), v8::internal::TrustedManaged< CppType >::From(), v8::internal::Heap::GarbageCollectionEpilogueInSafepoint(), v8::api_internal::GlobalizeReference(), v8::internal::DebugInfoCollection::Insert(), v8::internal::Heap::IterateRoots(), v8::internal::Heap::IterateWeakGlobalHandles(), wasm::RefImpl< Ref, JSType >::make(), v8::internal::wasm::anonymous_namespace{wasm-interpreter.cc}::MakeWeak(), v8::internal::IncrementalMarking::MarkRoots(), v8::internal::MinorMarkSweepCollector::MarkRoots(), v8::internal::Heap::PerformGarbageCollection(), v8::internal::wasm::AsyncCompileJob::PrepareRuntimeObjects(), v8::internal::Heap::RecordStats(), v8::internal::CrossHeapRememberedSet::RememberReferenceIfNeeded(), v8::internal::CrossHeapRememberedSet::Reset(), v8::internal::wasm::FrameState::SetCaughtException(), v8::internal::SnapshotCreatorImpl::SetDefaultContext(), v8::internal::Heap::TotalGlobalHandlesSize(), v8::internal::WeakCodeRegistry::Track(), v8::internal::ValueDeserializer::TransferArrayBuffer(), v8::internal::Heap::UsedGlobalHandlesSize(), v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::WeakScriptHandle::WeakScriptHandle(), and v8::internal::wasm::AsyncCompileJob::~AsyncCompileJob().
global_object()
Handle< JSGlobalObject > v8::internal::Isolate::global_object () [inline]
Definition at line 211 of file isolate-inl.h.
                                              {
  return handle(context()->global_object(), this);
}
References context(), and v8::internal::handle().
Referenced by v8::internal::Genesis::CompileExtension(), v8::internal::anonymous_namespace{builtins-function.cc}::DoFunctionBind(), v8::Context::Global(), v8::internal::WasmJs::Install(), v8::internal::WasmJs::InstallModule(), v8::internal::LoadGlobalIC::Load(), v8::internal::LookupForRead(), v8::internal::WasmJs::PrepareForSnapshot(), and v8::internal::StoreGlobalIC::Store().
global_proxy()
Handle< JSGlobalProxy > v8::internal::Isolate::global_proxy () [inline]
Definition at line 215 of file isolate-inl.h.
                                            {
  return handle(context()->global_proxy(), this);
}
References context(), and v8::internal::handle().
Referenced by v8::internal::Object::ConvertReceiver(), DetachGlobal(), v8::internal::LookupForRead(), and v8::Script::Run().
global_safepoint()
GlobalSafepoint* v8::internal::Isolate::global_safepoint () const [inline]
Definition at line 2345 of file isolate.h.
{ return global_safepoint_.get(); }
Referenced by v8::internal::MarkCompactCollector::ClearNonLiveReferences(), v8::internal::anonymous_namespace{heap.cc}::ClearStubCaches(), Deinit(), v8::internal::Heap::FreeLinearAllocationAreas(), v8::internal::Heap::GarbageCollectionEpilogueInSafepoint(), v8::internal::GlobalSafepointScope::GlobalSafepointScope(), Init(), v8::internal::IsolateSafepoint::InitiateGlobalSafepointScope(), v8::internal::Heap::IterateRootsIncludingClients(), v8::internal::Heap::MakeLinearAllocationAreasIterable(), v8::internal::MarkCompactCollector::MarkObjectsFromClientHeaps(), v8::internal::MarkCompactCollector::MarkRoots(), v8::internal::MarkCompactCollector::MarkRootsFromConservativeStack(), v8::internal::IncrementalMarking::PauseBlackAllocation(), v8::internal::Heap::PauseConcurrentThreadsInClients(), v8::internal::Heap::PerformGarbageCollection(), v8::internal::Heap::PerformHeapVerification(), v8::internal::MarkCompactCollector::PinPreciseRootsIfNeeded(), v8::internal::IncrementalMarking::StartBlackAllocation(), v8::internal::IsolateSafepoint::TryInitiateGlobalSafepointScope(), v8::internal::MarkCompactCollector::UpdatePointersInClientHeaps(), and v8::internal::GlobalSafepointScope::~GlobalSafepointScope().
handle_scope_data()
HandleScopeData* v8::internal::Isolate::handle_scope_data () [inline]
Definition at line 1408 of file isolate.h.
                                                 {
    return &isolate_data_.handle_scope_data_;
  }
Referenced by v8::internal::HandleScopeImplementer::ArchiveThread(), v8::internal::HandleScopeImplementer::BeginPersistentScope(), v8::internal::HandleScope::CloseScope(), v8::internal::HandleScope::CreateHandle(), v8::internal::HandleScope::current_level_address(), v8::internal::HandleScope::current_limit_address(), v8::internal::HandleScope::current_next_address(), v8::internal::HandleScope::DeleteExtensions(), v8::internal::PersistentHandlesScope::Detach(), v8::internal::HandleScopeImplementer::DetachPersistent(), v8::internal::HandleScope::Extend(), v8::internal::HandleScope::HandleScope(), v8::HandleScope::Initialize(), Isolate(), v8::internal::HandleScopeImplementer::Iterate(), v8::internal::HandleScope::NumberOfHandles(), v8::internal::LocalHandleScope::OpenMainThreadScope(), v8::internal::PersistentHandlesScope::PersistentHandlesScope(), v8::internal::HandleScopeImplementer::RestoreThread(), v8::SealHandleScope::SealHandleScope(), v8::HandleScope::~HandleScope(), v8::internal::PersistentHandlesScope::~PersistentHandlesScope(), and v8::SealHandleScope::~SealHandleScope().
handle_scope_implementer()
HandleScopeImplementer* v8::internal::Isolate::handle_scope_implementer () const [inline]
Definition at line 1412 of file isolate.h.
                                                           {
    DCHECK(handle_scope_implementer_);
    return handle_scope_implementer_;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::Builtins::AllowDynamicFunction(), v8::internal::Heap::CheckHandleCount(), v8::internal::anonymous_namespace{builtins-function.cc}::CreateDynamicFunction(), v8::internal::HandleScope::DeleteExtensions(), v8::internal::ThreadManager::EagerlyArchiveThread(), v8::Context::Enter(), v8::internal::wasm::InstanceBuilder::ExecuteStartFunction(), v8::Context::Exit(), v8::internal::HandleScope::Extend(), v8::internal::ThreadManager::FreeThreadResources(), v8::Isolate::GetEnteredOrMicrotaskContext(), v8::internal::PersistentHandlesScope::IsActive(), v8::internal::Heap::IterateRoots(), v8::internal::Heap::IterateRootsForPrecisePinning(), v8::internal::HandleScope::NumberOfHandles(), v8::internal::ThreadManager::RestoreThread(), v8::internal::MicrotaskQueue::RunMicrotasks(), v8::internal::RUNTIME_FUNCTION(), and v8::Context::SetMicrotaskQueue().
handle_scope_implementer_address()
Address v8::internal::Isolate::handle_scope_implementer_address () [inline]
Definition at line 1900 of file isolate.h.
                                             {
    return reinterpret_cast<Address>(&handle_scope_implementer_);
  }
handler()
static Address v8::internal::Isolate::handler (ThreadLocalTop * thread) [inline], [static]
Definition at line 907 of file isolate.h.
{ return thread->handler_; }
References v8::internal::ThreadLocalTop::handler_.
Referenced by v8::internal::TickSample::GetStackSample(), v8::internal::StackFrameIteratorForProfiler::IsValidTop(), PropagateExceptionToExternalTryCatch(), v8::internal::anonymous_namespace{isolate.cc}::ReceiverIsForwardingHandler(), v8::internal::StackFrameIterator::Reset(), TopExceptionHandlerType(), v8::internal::anonymous_namespace{isolate.cc}::TryGetCurrentTaskPromise(), and UnwindAndFindHandler().
handler_address()
Address* v8::internal::Isolate::handler_address () [inline]
Definition at line 919 of file isolate.h.
{ return &thread_local_top()->handler_; }
has_active_deserializer()
bool v8::internal::Isolate::has_active_deserializer () const [inline]
Definition at line 942 of file isolate.h.
{ UNREACHABLE(); }
References v8::internal::UNREACHABLE().
Referenced by v8::internal::MarkCompactCollector::ClearFullMapTransitions(), v8::internal::TransitionArray::GetTargetIfExists(), and v8::internal::LocalIsolate::has_active_deserializer().
has_exception()
bool v8::internal::Isolate::has_exception () [inline]
Definition at line 125 of file isolate-inl.h.
                            {
  ThreadLocalTop* top = thread_local_top();
  DCHECK(!IsException(top->exception_, this));
  return !IsTheHole(top->exception_, this);
}
References v8::internal::DCHECK(), v8::internal::ThreadLocalTop::exception_, and thread_local_top().
Referenced by v8::internal::KeyAccumulator::AddKey(), v8::internal::anonymous_namespace{messages.cc}::AppendErrorString(), v8::internal::JSArray::ArraySetLength(), v8::internal::wasm::WasmEngine::AsyncInstantiate(), v8::internal::wasm::InstanceBuilder::Build_Phase1(), v8::CALLBACK_SETTER(), v8::internal::wasm::WasmInterpreterRuntime::CallExternalJSFunction(), v8::internal::Debug::CheckBreakPoint(), v8::internal::Compiler::CollectSourcePositions(), v8::internal::BigInt::CompareToString(), v8::internal::ExperimentalRegExp::Compile(), v8::internal::RegExp::Compile(), v8::internal::Compiler::Compile(), v8::WasmModuleObject::Compile(), v8::internal::anonymous_namespace{experimental.cc}::CompileImpl(), v8::internal::anonymous_namespace{compiler.cc}::CompileMaglev(), v8::internal::Compiler::CompileOptimized(), v8::internal::anonymous_namespace{debug.cc}::CompileTopLevel(), v8::internal::anonymous_namespace{compiler.cc}::CompileTurbofan(), v8::internal::anonymous_namespace{compiler.cc}::CompileTurbofan_NotConcurrent(), v8::internal::wasm::InstanceBuilder::ConfigurePrototypes_Modular(), v8::internal::anonymous_namespace{builtins-console.cc}::ConsoleCall(), v8::internal::JSWrappedFunction::Create(), v8::internal::JSRawJson::Create(), v8::internal::CreateWasmObject(), v8::internal::anonymous_namespace{runtime-scopes.cc}::DeclareEvalHelper(), v8::internal::anonymous_namespace{runtime-classes.cc}::DefineClass(), v8::internal::anonymous_namespace{builtins-function.cc}::DoFunctionBind(), v8::internal::RegExp::EnsureFullyCompiled(), v8::internal::SharedFunctionInfo::EnsureSourcePositionsAvailable(), v8::internal::BigInt::EqualToString(), v8::internal::DebugEvaluate::Evaluate(), exception(), v8::internal::ExperimentalRegExp::Exec(), v8::internal::RegExp::Exec_Single(), v8::internal::NativeRegExpMacroAssembler::Execute(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteFunction(), v8::internal::wasm::InstanceBuilder::ExecuteStartFunction(), v8::internal::anonymous_namespace{compiler.cc}::FailWithPreparedException(), v8::internal::anonymous_namespace{json-stringifier.cc}::FastJsonStringify(), v8::internal::Compiler::FinalizeBackgroundCompileTask(), v8::internal::LazyCompileDispatcher::FinishNow(), v8::internal::MessageFormatter::Format(), v8::internal::ErrorUtils::FormatStackTrace(), v8::internal::ThreadManager::FreeThreadResources(), v8::internal::PropertyCallbackArguments::GetBooleanReturnValue(), v8::internal::FastKeyAccumulator::GetKeys(), v8::internal::JSProxy::GetOwnPropertyDescriptor(), v8::internal::JSReceiver::GetOwnPropertyDescriptor(), v8::internal::JSObject::GetPropertyAttributesWithFailedAccessCheck(), v8::internal::wasm::WasmInterpreterRuntime::HandleException(), v8::Isolate::HasPendingException(), v8::internal::JsonStringifier::InitializeReplacer(), v8::internal::Genesis::InstallExtension(), v8::internal::wasm::JSPrototypesSetup::InstallMethodImpl(), v8::internal::AsmJs::InstantiateAsmWasm(), v8::internal::wasm::InstantiateToInstanceObject(), v8::internal::anonymous_namespace{execution.cc}::Invoke(), v8::internal::anonymous_namespace{execution.cc}::InvokeWithTryCatch(), v8::internal::RegExpImpl::IrregexpExec(), v8::internal::RegExpImpl::IrregexpExecRaw(), v8::internal::anonymous_namespace{runtime-scopes.cc}::LoadLookupSlot(), v8::internal::DebugEvaluate::Local(), v8::internal::Context::Lookup(), v8::Promise::Resolver::New(), v8::Array::New(), v8::Context::NewRemoteContext(), v8::internal::ExperimentalRegExp::OneshotExec(), v8::internal::Debug::OnThrow(), v8::internal::wasm::WasmInterpreterThread::RaiseException(), v8::internal::ValueDeserializer::ReadObject(), v8::internal::ValueDeserializer::ReadObjectWrapper(), v8::internal::RegExpGlobalExecRunner::RegExpGlobalExecRunner(), v8::internal::MessageHandler::ReportMessage(), v8::internal::SourceTextModule::ResolveExport(), v8::internal::SourceTextModule::ResolveExportUsingStarExports(), v8::internal::SourceTextModule::ResolveImport(), ReThrow(), v8::internal::wasm::InterpreterHandle::RunExecutionLoop(), RunHostImportModuleDynamicallyCallback(), RunHostInitializeImportMetaObjectCallback(), v8::internal::SourceTextModule::RunInitializationCode(), v8::internal::MicrotaskQueue::RunMicrotasks(), v8::internal::RUNTIME_FUNCTION(), v8::internal::ErrorUtils::ShadowRealmConstructTypeErrorCopy(), v8::AsyncHooks::ShellPromiseHook(), v8::internal::Debug::StopSideEffectCheckMode(), v8::internal::anonymous_namespace{runtime-scopes.cc}::StoreLookupSlot(), v8::internal::JsonStringifier::Stringify(), Throw(), v8::internal::anonymous_namespace{value-serializer.cc}::ThrowDeserializationExceptionIfNonePending(), v8::internal::wasm::WasmInterpreterRuntime::ThrowException(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::TransferPrototype(), v8::internal::wasm::WasmInterpreterRuntime::WasmArrayCopy(), v8::internal::wasm::WasmInterpreterRuntime::WasmArrayInitSegment(), v8::internal::wasm::WasmInterpreterRuntime::WasmArrayNewSegment(), v8::internal::wasm::WasmInterpreterRuntime::WasmJSToWasmObject(), v8::internal::wasm::ClearThreadInWasmScope::~ClearThreadInWasmScope(), v8::internal::wasm::ErrorThrower::~ErrorThrower(), and v8::MicrotasksScope::~MicrotasksScope().
has_pending_message()
bool v8::internal::Isolate::has_pending_message () [inline]
Definition at line 100 of file isolate-inl.h.
                                  {
  return !IsTheHole(pending_message(), this);
}
References pending_message().
Referenced by v8::internal::MoveMessageToPromise(), PropagateExceptionToExternalTryCatch(), and ReThrow().
has_shared_space()
bool v8::internal::Isolate::has_shared_space () const [inline]
Definition at line 2343 of file isolate.h.
{ return shared_space_isolate_.value(); }
Referenced by v8::internal::SnapshotCreatorImpl::CreateBlob(), Deinit(), v8::internal::EvacuationAllocator::EvacuationAllocator(), Init(), v8::internal::Scavenger::ScavengePage(), v8::internal::Snapshot::SerializeDeserializeAndVerifyForTesting(), v8::internal::HeapAllocator::Setup(), v8::internal::LocalHeap::SetUpSharedMarking(), v8::internal::Heap::SetUpSpaces(), v8::internal::SharedHeapSerializer::ShouldReconstructSharedHeapObjectCacheForTesting(), and v8::internal::ValueSerializer::WriteSharedObject().
HasAsyncEventDelegate()
bool v8::internal::Isolate::HasAsyncEventDelegate () const [inline], [private]
Definition at line 2560 of file isolate.h.
                                     {
    return PromiseHookFields::HasAsyncEventDelegate::decode(
        promise_hook_flags_);
  }
Referenced by OnAsyncFunctionSuspended(), OnPromiseAfter(), OnPromiseBefore(), OnPromiseThen(), OnStackTraceCaptured(), and RunAllPromiseHooks().
HasContextPromiseHooks()
bool v8::internal::Isolate::HasContextPromiseHooks () const [inline]
Definition at line 1875 of file isolate.h.
                                      {
    return PromiseHookFields::HasContextPromiseHook::decode(
        promise_hook_flags_);
  }
Referenced by v8::internal::JSPromise::Fulfill(), and RunAllPromiseHooks().
HashIsolateForEmbeddedBlob()
size_t v8::internal::Isolate::HashIsolateForEmbeddedBlob ()
Definition at line 447 of file isolate.cc.
                                           {
  DCHECK(builtins_.is_initialized());
  DCHECK(Builtins::AllBuiltinsAreIsolateIndependent());
  DisallowGarbageCollection no_gc;
  static constexpr size_t kSeed = 0;
  size_t hash = kSeed;
  // Hash static entries of the roots table.
  hash = base::hash_combine(hash, V8_STATIC_ROOTS_BOOL);
#if V8_STATIC_ROOTS_BOOL
  hash = base::hash_combine(hash,
                            static_cast<int>(RootIndex::kReadOnlyRootsCount));
  RootIndex i = RootIndex::kFirstReadOnlyRoot;
  for (auto ptr : StaticReadOnlyRootsPointerTable) {
    hash = base::hash_combine(ptr, hash);
    ++i;
  }
#endif // V8_STATIC_ROOTS_BOOL
  // Hash data sections of builtin code objects.
  for (Builtin builtin = Builtins::kFirst; builtin <= Builtins::kLast;
       ++builtin) {
#if V8_ENABLE_GEARBOX
    if (Builtins::IsGearboxPlaceholder(builtin)) {
      // When v8 enables gearbox for builtins, there are 3 builtin objects for a
      // builtin, one is generic variant, another one is ISX variant, and final
      // one is a placeholder, it will be set as either generic or ISX variant
      // at runtime. Therefore v8 will modify the contents of the placeholder
      // code object when it is being launched, so we didn't take it into the
      // hash calculation, otherwise it will cause hash check failed.
      continue;
    }
#endif
    Tagged<Code> code = builtins()->code(builtin);
    DCHECK(Internals::HasHeapObjectTag(code.ptr()));
    uint8_t* const code_ptr = reinterpret_cast<uint8_t*>(code.address());
    // These static asserts ensure we don't miss relevant fields. We don't hash
    // instruction_start, but other data fields must remain the same.
    static_assert(Code::kEndOfStrongFieldsOffset ==
                  Code::kInstructionStartOffset);
#ifndef V8_ENABLE_SANDBOX
    static_assert(
        Code::kInstructionStartOffsetEnd + 1 +
            (V8_ENABLE_LEAPTIERING_BOOL ? kJSDispatchHandleSize : 0) ==
        Code::kFlagsOffset);
#endif
    static_assert(Code::kFlagsOffsetEnd + 1 == Code::kInstructionSizeOffset);
    static_assert(Code::kInstructionSizeOffsetEnd + 1 ==
                  Code::kMetadataSizeOffset);
    static_assert(Code::kMetadataSizeOffsetEnd + 1 ==
                  Code::kInlinedBytecodeSizeOffset);
    static_assert(Code::kInlinedBytecodeSizeOffsetEnd + 1 ==
                  Code::kOsrOffsetOffset);
    static_assert(Code::kOsrOffsetOffsetEnd + 1 ==
                  Code::kHandlerTableOffsetOffset);
    static_assert(Code::kHandlerTableOffsetOffsetEnd + 1 ==
                  Code::kUnwindingInfoOffsetOffset);
    static_assert(Code::kUnwindingInfoOffsetOffsetEnd + 1 ==
                  Code::kConstantPoolOffsetOffset);
    static_assert(Code::kConstantPoolOffsetOffsetEnd + 1 ==
                  Code::kCodeCommentsOffsetOffset);
    static_assert(Code::kCodeCommentsOffsetOffsetEnd + 1 ==
                  Code::kJumpTableInfoOffsetOffset);
    static_assert(Code::kJumpTableInfoOffsetOffsetEnd + 1 ==
                  Code::kParameterCountOffset);
    static_assert(Code::kParameterCountOffsetEnd + 1 == Code::kBuiltinIdOffset);
    static_assert(Code::kBuiltinIdOffsetEnd + 1 == Code::kUnalignedSize);
    static constexpr int kStartOffset = Code::kFlagsOffset;
    for (int j = kStartOffset; j < Code::kUnalignedSize; j++) {
      hash = base::hash_combine(hash, size_t{code_ptr[j]});
    }
  }
  // The builtins constants table is also tightly tied to embedded builtins.
  hash = base::hash_combine(
      hash, static_cast<size_t>(heap_.builtins_constants_table()->length()));
  return hash;
}
References v8::internal::Builtins::AllBuiltinsAreIsolateIndependent(), builtins(), builtins_, v8::internal::Builtins::code(), code, v8::internal::DCHECK(), v8::base::hash_combine(), v8::internal::Internals::HasHeapObjectTag(), heap_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::Builtins::is_initialized(), v8::internal::Builtins::kFirst, v8::internal::kFirstReadOnlyRoot, v8::internal::kJSDispatchHandleSize, v8::internal::Builtins::kLast, v8::internal::kReadOnlyRootsCount, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, V8_ENABLE_LEAPTIERING_BOOL, and V8_STATIC_ROOTS_BOOL.
Referenced by v8::internal::EmbeddedData::NewFromIsolate().
HasIsolatePromiseHooks()
bool v8::internal::Isolate::HasIsolatePromiseHooks () const [inline], [private]
Definition at line 2555 of file isolate.h.
                                      {
    return PromiseHookFields::HasIsolatePromiseHook::decode(
        promise_hook_flags_);
  }
Referenced by RunAllPromiseHooks(), and RunPromiseHook().
HasPrepareStackTraceCallback()
bool v8::internal::Isolate::HasPrepareStackTraceCallback () const
Definition at line 6926 of file isolate.cc.
                                                 {
  return prepare_stack_trace_callback_ != nullptr;
}
References prepare_stack_trace_callback_.
Referenced by v8::internal::ErrorUtils::FormatStackTrace().
heap() [1/2]
Heap* v8::internal::Isolate::heap () [inline]
Definition at line 1214 of file isolate.h.
{ return &heap_; }
Referenced by _v8_internal_Print_Code(), _v8_internal_Print_OnlyCode(), v8::internal::MarkingBarrier::ActivateAll(), v8::internal::MarkingBarrier::ActivateShared(), v8::internal::SnapshotCreatorImpl::AddContext(), AddCrashKeysForIsolateAndHeapPointers(), v8::internal::SnapshotCreatorImpl::AddData(), AddDetachedContext(), v8::Isolate::AddGCEpilogueCallback(), v8::Isolate::AddGCPrologueCallback(), v8::internal::wasm::WasmEngine::AddIsolate(), v8::internal::CppHeap::MetricRecorderAdapter::AddMainThreadEvent(), v8::Isolate::AddMessageListenerWithErrorLevel(), v8::Isolate::AddNearHeapLimitCallback(), v8::internal::BuiltinsConstantsTableBuilder::AddObject(), v8::internal::AddToWeakNativeContextList(), v8::Isolate::AdjustAmountOfExternalAllocatedMemoryImpl(), v8::internal::BackingStore::Allocate(), v8::internal::MemoryAllocator::AllocateLargePage(), v8::internal::MemoryAllocator::AllocatePage(), v8::internal::MemoryAllocator::AllocateReadOnlyPage(), v8::internal::MemoryAllocator::AllocateUninitializedChunkAt(), v8::internal::Factory::AllocationTypeForInPlaceInternalizableString(), v8::internal::Factory::allocator(), v8::internal::wasm::array_copy_wrapper(), v8::internal::wasm::array_fill_wrapper(), v8::internal::CppHeap::AttachIsolate(), v8::Isolate::AutomaticallyRestoreInitialHeapLimit(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuiltinAssemblerOptions(), v8::internal::BuiltinsConstantsTableBuilder::BuiltinsConstantsTableBuilder(), v8::internal::compiler::AllocationBuilder::CanAllocateArray(), v8::internal::compiler::AllocationBuilder::CanAllocateSloppyArgumentElements(), v8::internal::MutableBigInt::Canonicalize(), v8::internal::Heap::CanReferenceHeapObject(), v8::internal::wasm::WasmInterpreterRuntime::CheckIndirectCallSignature(), v8::internal::StartupSerializer::CheckNoDirtyFinalizationRegistries(), v8::internal::anonymous_namespace{constants-table-builder.cc}::CheckPreconditionsForPatching(), ClearKeptObjects(), v8::internal::anonymous_namespace{global-handles.cc}::ClearListOfYoungNodesImpl(), v8::internal::Snapshot::ClearReconstructableDataForSerialization(), v8::internal::wasm::TypeCanonicalizer::ClearWasmCanonicalTypesForTesting(), v8::internal::anonymous_namespace{debug-coverage.cc}::CollectAndMaybeResetCounts(), v8::internal::CodeStatistics::CollectCodeStatistics(), v8::internal::CppHeap::CollectGarbage(), v8::internal::Heap::CollectGarbageShared(), v8::internal::OptimizedCompilationJob::CollectRetainedMaps(), CollectSourcePositionsForAllBytecodeArrays(), v8::internal::compiler::CompilationDependencies::Commit(), v8::internal::ObjectDeserializer::CommitPostProcessedObjects(), v8::internal::anonymous_namespace{compiler.cc}::CompileTurbofan_Concurrent(), v8::internal::TracedHandles::ComputeWeaknessForYoungObjects(), v8::Isolate::ContextDisposedNotification(), v8::internal::anonymous_namespace{snapshot.cc}::ConvertSerializedObjectsToFixedArray(), v8::internal::ScopeInfo::CopyElements(), v8::internal::WeakArrayList::CopyElements(), v8::internal::TaggedArrayBase< Derived, ShapeT, Super >::CopyElements(), v8::internal::PropertyArray::CopyElements(), v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::CopyToReadOnlyHeap(), v8::internal::SnapshotCreatorImpl::CreateBlob(), v8::internal::Bootstrapper::CreateEnvironment(), v8::internal::JSArrayBuffer::CreateExtension(), v8::internal::HandleScope::CreateHandle(), v8::internal::ReadOnlyHeap::CreateInitialHeapForBootstrapping(), v8::internal::wasm::CreateMapForType(), v8::internal::OffHeapInstructionStream::CreateOffHeapOffHeapInstructionStream(), v8::internal::Heap::CreateReadOnlyHeapObjects(), v8::internal::MarkingBarrier::DeactivateAll(), v8::ExternalMemoryAccounter::Decrease(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::DecreaseLength(), v8::internal::DEF_GETTER(), v8::internal::AssemblerOptions::Default(), v8::MeasureMemoryDelegate::Default(), Deinit(), Deinitialize(), v8::HeapSnapshot::Delete(), v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::DeleteAtEnd(), v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::DeleteDeadObjects(), v8::internal::anonymous_namespace{runtime-object.cc}::DeleteProperty(), v8::internal::Deoptimizer::Deoptimizer(), v8::internal::ReadOnlyDeserializer::DeserializeIntoIsolate(), v8::internal::StartupDeserializer::DeserializeIntoIsolate(), v8::internal::JSArrayBuffer::DetachInternal(), v8::internal::Debug::DiscardAllBaselineCode(), v8::internal::Debug::DiscardBaselineCode(), v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::Deoptimizer::DoComputeConstructCreateStubFrame(), v8::internal::Deoptimizer::DoComputeConstructInvokeStubFrame(), v8::internal::Deoptimizer::DoComputeUnoptimizedFrame(), v8::internal::StringTable::DropOldData(), v8::internal::wasm::WasmExportWrapperCache::EnsureCapacity(), v8::internal::TemplateInfo::EnsureHasSerialNumber(), v8::internal::MaterializedObjectStore::EnsureStackEntries(), v8::internal::Deoptimizer::EnsureValidReturnAddress(), Enter(), v8::internal::CppHeap::EnterFinalPause(), v8::internal::GlobalSafepoint::EnterGlobalSafepointScope(), v8::internal::anonymous_namespace{liveedit.cc}::FunctionDataMap::Fill(), v8::internal::BuiltinsConstantsTableBuilder::Finalize(), v8::internal::BackgroundCompileTask::FinalizeScript(), v8::internal::Sweeper::FinishMajorJobs(), v8::internal::CppHeap::FinishMarkingAndProcessWeakness(), v8::internal::Sweeper::FinishMinorJobs(), v8::internal::CodeSerializer::FinishOffThreadDeserialize(), v8::internal::Heap::FreeLinearAllocationAreas(), v8::internal::Heap::GarbageCollectionEpilogueInSafepoint(), v8::internal::Generate_InterpreterEnterBytecode(), v8::internal::Genesis::Genesis(), v8::internal::wasm::WasmExportWrapperCache::Get(), v8::internal::SamplingHeapProfiler::GetAllocationProfile(), v8::internal::JSTypedArray::GetBuffer(), v8::internal::anonymous_namespace{mark-compact.cc}::GetCodeFlushMode(), v8::Isolate::GetCodeRange(), v8::internal::StatisticsExtension::GetCounters(), v8::internal::BasicBlockProfiler::GetCoverageBitmap(), v8::Isolate::GetCppHeap(), v8::internal::TracedHandles::GetCppHeapIfUnifiedYoungGC(), v8::Isolate::GetDataFromSnapshotOnce(), v8::internal::Debug::GetFunctionDebuggingId(), v8::Isolate::GetHeapCodeAndMetadataStatistics(), v8::Isolate::GetHeapObjectStatisticsAtLastGC(), v8::Isolate::GetHeapSpaceStatistics(), v8::Isolate::GetHeapStatistics(), v8::internal::Debug::GetLoadedScripts(), GetNextScriptId(), v8::internal::TranslatedValue::GetRawValue(), v8::internal::TickSample::GetStackSample(), v8::ExternalMemoryAccounter::GetTotalAmountOfExternalAllocatedMemoryForTesting(), v8::internal::anonymous_namespace{cpp-heap.cc}::GetV8MarkingWorklists(), v8::internal::MemoryAllocator::HandleAllocationFailure(), v8::internal::StackGuard::HandleInterrupts(), v8::internal::BasicBlockProfiler::HasData(), v8::internal::PerClientSafepointData::heap(), v8::internal::Genesis::heap(), v8::internal::HeapAllocator::heap_for_allocation(), v8::internal::ETWJITInterface::EtwIsolateOperations::HeapGcSafeTryFindCodeForInnerPointer(), v8::internal::ETWJITInterface::EtwIsolateOperations::HeapReadOnlySpaceWritable(), Init(), v8::Isolate::Initialize(), v8::internal::ReadOnlyArtifacts::Initialize(), v8::internal::TranslatedState::InitializeJSObjectAt(), v8::internal::CppHeap::InitializeMarking(), v8::internal::TranslatedState::InitializeObjectWithTaggedFieldsAt(), v8::internal::IsolateSafepoint::InitiateGlobalSafepointScopeRaw(), v8::internal::Debug::InstallDebugBreakTrampoline(), v8::internal::Factory::InternalizeExternalString(), v8::internal::CodeDataSourceIncrementalState::InternIsolate(), v8::internal::anonymous_namespace{heap.cc}::InvokeExternalCallbacks(), v8::internal::GlobalHandles::InvokeSecondPassPhantomCallbacks(), is_catchable_by_javascript(), v8::internal::anonymous_namespace{frames.cc}::IsInterpreterFramePc(), v8::internal::ManualOptimizationTable::IsMarkedForManualOptimization(), v8::internal::AllocationSite::IsNested(), v8::internal::MarkCompactCollector::IsUnmarkedSharedHeapObject(), v8::internal::PersistentHandlesList::Iterate(), v8::internal::StringTable::IterateElements(), v8::internal::Heap::IterateRootsIncludingClients(), v8::internal::wasm::WasmImportWrapperCache::LazyInitialize(), v8::internal::JSObject::LazyRegisterPrototypeUser(), v8::internal::GlobalSafepoint::LeaveGlobalSafepointScope(), v8::internal::ObjectDeserializer::LinkAllocationSites(), LocalsBlockListCacheGet(), LocalsBlockListCacheRehash(), LocalsBlockListCacheSet(), v8::internal::BasicBlockProfiler::Log(), v8::internal::V8FileLogger::LogAccessorCallbacks(), v8::internal::V8FileLogger::LogAllMaps(), v8::internal::ExistingCodeLogger::LogCodeObjects(), v8::internal::ExistingCodeLogger::LogCompiledFunctions(), v8::internal::Context::Lookup(), v8::Isolate::LowMemoryNotification(), v8::internal::maglev::MaglevCompilationInfo::MaglevCompilationInfo(), v8::internal::String::MakeExternal(), v8::internal::String::MakeExternalDuringGC(), v8::internal::Heap::MakeLinearAllocationAreasIterable(), v8::internal::ManualOptimizationTable::MarkFunctionForManualOptimization(), v8::internal::MarkCompactCollector::MarkObjectsFromClientHeap(), v8::internal::MarkCompactCollector::MarkRoots(), v8::internal::MarkCompactCollector::MarkRootsFromConservativeStack(), v8::internal::Deoptimizer::MaterializeHeapObjects(), MaybeInitializeVectorListFromHeap(), v8::Isolate::MeasureMemory(), v8::Isolate::MemoryPressureNotification(), v8::internal::anonymous_namespace{string.cc}::MigrateExternalString(), v8::internal::anonymous_namespace{string.cc}::MigrateExternalStringResource(), v8::internal::anonymous_namespace{js-objects.cc}::MigrateFastToFast(), v8::internal::anonymous_namespace{js-objects.cc}::MigrateFastToSlow(), v8::internal::TaggedArrayBase< Derived, ShapeT, Super >::MoveElements(), v8::internal::WasmTrustedInstanceData::New(), v8::internal::WasmJSFunction::New(), v8::internal::Factory::NewAllocationSite(), v8::internal::Factory::NewExternalStringFromOneByte(), v8::internal::Factory::NewExternalStringFromTwoByte(), v8::internal::Factory::NewFillerObject(), v8::internal::wasm::WasmCodeManager::NewNativeModule(), v8::internal::Factory::NewTransitionArray(), v8::internal::anonymous_namespace{deoptimizer.cc}::DeoptimizableCodeIterator::Next(), v8::internal::StringTable::NotifyElementsRemoved(), v8::Isolate::NumberOfTrackedHeapObjectTypes(), v8::internal::compiler::JSHeapBroker::ObjectMayBeUninitialized(), v8::internal::ReadOnlyHeap::OnCreateHeapObjectsComplete(), OnTerminationDuringRunMicrotasks(), v8::internal::OptimizedCompilationInfo::OptimizedCompilationInfo(), v8::internal::IncrementalMarking::PauseBlackAllocation(), v8::internal::Heap::PauseConcurrentThreadsInClients(), v8::internal::Heap::PerformHeapVerification(), v8::internal::MarkCompactCollector::PinPreciseRootsIfNeeded(), v8::internal::GlobalHandles::PostGarbageCollectionProcessing(), v8::internal::anonymous_namespace{deserializer.cc}::PostProcessExternalString(), v8::internal::MemoryAllocator::PreFreeMemory(), v8::internal::wasm::TypeCanonicalizer::PrepareForCanonicalTypeId(), v8::internal::compiler::CodeAssemblerCompilationJob::PrepareJobImpl(), v8::internal::compiler::PipelineCompilationJob::PrepareJobImpl(), v8::internal::BasicBlockProfiler::Print(), v8::internal::Factory::ProcessNewScript(), v8::internal::TracedHandles::ProcessWeakYoungObjects(), v8::internal::ProfilingScope::ProfilingScope(), v8::internal::MarkingBarrier::PublishAll(), v8::internal::OptimizedCompilationJob::RegisterWeakObjectsInOptimizedCode(), v8::internal::anonymous_namespace{objects.cc}::RehashObjectHashTableAndGCIfNeeded(), v8::internal::ReadOnlyArtifacts::ReinstallReadOnlySpace(), v8::internal::MaterializedObjectStore::Remove(), v8::internal::GlobalSafepoint::RemoveClient(), v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::RemoveElement(), v8::Isolate::RemoveGCEpilogueCallback(), v8::Isolate::RemoveGCPrologueCallback(), v8::Isolate::RemoveMessageListeners(), v8::Isolate::RemoveNearHeapLimitCallback(), v8::internal::CppHeap::ReportBufferedAllocationSizeIfPossible(), v8::internal::StringForwardingTable::Reset(), v8::internal::BasicBlockProfiler::ResetCounts(), v8::internal::TracedHandles::ResetDeadNodes(), v8::internal::TracedHandles::ResetYoungDeadNodes(), v8::internal::ResizeHelper(), v8::internal::maglev::MaglevCodeGenerator::RetainedMaps(), ReThrow(), v8::internal::TaggedArrayBase< Derived, ShapeT, Super >::RightTrim(), v8::internal::anonymous_namespace{bigint.cc}::RightTrimString(), v8::internal::Sweeper::MajorSweeperJob::Run(), v8::internal::Sweeper::MinorSweeperJob::Run(), v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::Run(), v8::internal::StressConcurrentAllocationTask::RunInternal(), v8::internal::IncrementalMarkingJob::Task::RunInternal(), v8::internal::MinorGCJob::Task::RunInternal(), v8::internal::IdleTaskOnContextDispose::RunInternal(), v8::Shell::RunMain(), v8::internal::RUNTIME_FUNCTION(), v8::internal::SafepointScope::SafepointScope(), v8::internal::anonymous_namespace{startup-serializer.cc}::SanitizeIsolateScope::SanitizeIsolateScope(), v8::internal::MemoryMeasurement::ScheduleGCTask(), v8::internal::anonymous_namespace{runtime-regexp.cc}::SearchRegExpMultiple(), v8::internal::Coverage::SelectMode(), v8::internal::Snapshot::SerializeDeserializeAndVerifyForTesting(), v8::internal::SerializedHandleChecker::SerializedHandleChecker(), v8::internal::Serializer::SerializeReadOnlyObjectReference(), v8::internal::StartupSerializer::SerializeStrongReferences(), v8::internal::StartupSerializer::SerializeWeakReferencesAndDeferred(), v8::internal::SmiStringCache::Set(), v8::internal::DoubleStringCache::Set(), v8::internal::anonymous_namespace{js-atomics-synchronization.cc}::SetAsyncUnlockHandlers(), v8::internal::SnapshotCreatorImpl::SetDefaultContext(), v8::Isolate::SetEmbedderRootsHandler(), SetFeedbackVectorsForProfilingTools(), v8::Isolate::SetGetExternallyAllocatedMemoryInBytesCallback(), SetIsLoading(), SetPriority(), v8::internal::ExternalOneByteString::SetResource(), v8::internal::ExternalTwoByteString::SetResource(), SetTerminationOnExternalTryCatch(), v8::internal::ReadOnlyHeap::SetUp(), v8::internal::SetupIsolateDelegate::SetupHeapInternal(), v8::internal::LocalHeap::SetUpSharedMarking(), v8::internal::Heap::SetUpSpaces(), v8::internal::SnapshotCreatorImpl::SnapshotCreatorImpl(), v8::internal::anonymous_namespace{elements.cc}::SortIndices(), v8::internal::CppHeap::stack(), StackOverflow(), v8::internal::CppHeap::StartDetachingIsolate(), v8::internal::Debug::StartSideEffectCheckMode(), v8::internal::IncrementalMarking::Stop(), v8::internal::Debug::StopSideEffectCheckMode(), v8::internal::StringReplaceGlobalRegExpWithEmptyString(), v8::internal::StringReplaceGlobalRegExpWithString(), v8::internal::TracedHandles::SupportsClearingWeakNonLiveWrappers(), SymbolFor(), Throw(), ThrowIllegalOperation(), v8::internal::V8FileLogger::Time(), v8::internal::Object::ToBoolean(), v8::internal::ArrayList::ToFixedArray(), v8::internal::PropertyDescriptor::ToObject(), v8::internal::anonymous_namespace{regexp.cc}::TooMuchRegExpCode(), TopExceptionHandlerType(), v8::internal::anonymous_namespace{mark-compact.cc}::TraceEvacuation(), v8::internal::SeqString::Truncate(), v8::internal::BackingStore::TryAllocateAndPartiallyCommitMemory(), v8::internal::GlobalDictionary::TryFindPropertyCellForConcurrentLookupIterator(), v8::internal::RegExpResultsCache_MatchGlobalAtom::TryGet(), v8::internal::RegExpResultsCache_MatchGlobalAtom::TryInsert(), v8::internal::Factory::TryNewFixedArray(), v8::internal::IdleTaskOnContextDispose::TryRunMinorGC(), v8::internal::SwissNameDictionary::TryValueAt(), v8::internal::TurbofanStubWithContextFrame::unchecked_code(), v8::internal::StubFrame::unchecked_code(), v8::internal::JSObject::UpdateAllocationSite(), v8::internal::anonymous_namespace{global-handles.cc}::UpdateListOfYoungNodesImpl(), UpdateLogObjectRelocation(), v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointers(), v8::internal::MarkCompactCollector::UpdatePointersInClientHeap(), v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::ValidateContents(), v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::Verify(), v8::internal::ReadOnlyArtifacts::VerifyHeapAndSpaceRelationships(), v8::internal::JSAtomicsCondition::WaitAsync(), v8::internal::MarkingBarrier::Write(), v8::internal::anonymous_namespace{scavenger.cc}::YoungGenerationConservativeStackVisitor::YoungGenerationConservativeStackVisitor(), v8::internal::FoldedMutableHeapNumberAllocator::~FoldedMutableHeapNumberAllocator(), v8::internal::SnapshotCreatorImpl::~SnapshotCreatorImpl(), and wasm::StoreImpl::~StoreImpl().
heap() [2/2]
const Heap* v8::internal::Isolate::heap () const [inline]
Definition at line 1215 of file isolate.h.
{ return &heap_; }
id()
int v8::internal::Isolate::id () const [inline]
Definition at line 1767 of file isolate.h.
{ return id_; }
Referenced by get_address_from_id(), GetTurboCfgFileName(), v8::internal::CodeDataSourceIncrementalState::InternIsolate(), v8::internal::CodeDataSourceIncrementalState::InternJsScript(), and v8::internal::wasm::WasmEngine::ReportLiveCodeForGC().
IncreaseConcurrentOptimizationPriority()
void v8::internal::Isolate::IncreaseConcurrentOptimizationPriority (CodeKind kind, Tagged< SharedFunctionInfo > function)
Definition at line 6180 of file isolate.cc.
                                                        {
  DCHECK_EQ(kind, CodeKind::TURBOFAN_JS);
  optimizing_compile_dispatcher()->Prioritize(function);
}
References DCHECK_EQ, optimizing_compile_dispatcher(), and v8::internal::OptimizingCompileDispatcher::Prioritize().
Referenced by v8::internal::TieringManager::MaybeOptimizeFrame().
IncreaseDateCacheStampAndInvalidateProtector()
void v8::internal::Isolate::IncreaseDateCacheStampAndInvalidateProtector ()
Definition at line 6307 of file isolate.cc.
                                                           {
  // There's no need to update stamp and invalidate the protector since there
  // were no JSDate instances created yet and thus such a configuration change
  // is not observable anyway.
  if (!isolate_data()->is_date_cache_used_) return;
  if (isolate_data()->date_cache_stamp_ < Smi::kMaxValue) {
    ++isolate_data()->date_cache_stamp_;
  } else {
    isolate_data()->date_cache_stamp_ = 1;
  }
  if (Protectors::IsNoDateTimeConfigurationChangeIntact(this)) {
    Protectors::InvalidateNoDateTimeConfigurationChange(this);
  }
}
References v8::internal::IsolateData::date_cache_stamp_, isolate_data(), and v8::internal::Smi::kMaxValue.
Referenced by v8::Isolate::DateTimeConfigurationChangeNotification().
IncreaseTotalRegexpCodeGenerated()
void v8::internal::Isolate::IncreaseTotalRegexpCodeGenerated (DirectHandle< HeapObject > code)
Definition at line 6228 of file isolate.cc.
                                                                            {
  PtrComprCageBase cage_base(this);
  DCHECK(IsCode(*code, cage_base) || IsTrustedByteArray(*code, cage_base));
  total_regexp_code_generated_ += code->Size(cage_base);
}
References cage_base(), code, v8::internal::DCHECK(), and total_regexp_code_generated_.
Referenced by v8::internal::RegExpCompiler::Assemble().
IncrementJavascriptExecutionCounter()
void v8::internal::Isolate::IncrementJavascriptExecutionCounter () [inline]
Definition at line 1896 of file isolate.h.
                                             {
    javascript_execution_counter_++;
  }
Referenced by v8::internal::anonymous_namespace{execution.cc}::Invoke().
InFastCCall()
bool v8::internal::Isolate::InFastCCall () const [inline]
Definition at line 194 of file isolate-inl.h.
                                {
  return isolate_data()->fast_c_call_caller_fp() != kNullAddress;
}
References v8::internal::IsolateData::fast_c_call_caller_fp(), isolate_data(), and v8::internal::kNullAddress.
Referenced by v8::internal::CppHeap::IsGCForbidden().
Init()
bool v8::internal::Isolate::Init (SnapshotData * startup_snapshot_data, SnapshotData * read_only_snapshot_data, SnapshotData * shared_heap_snapshot_data, bool can_rehash) [private]
Definition at line 5520 of file isolate.cc.
                                                                             {
  TRACE_ISOLATE(init);
#ifdef V8_COMPRESS_POINTERS_IN_SHARED_CAGE
  CHECK_EQ(V8HeapCompressionScheme::base(), cage_base());
#endif // V8_COMPRESS_POINTERS_IN_SHARED_CAGE
  const bool create_heap_objects = (shared_heap_snapshot_data == nullptr);
  // We either have both or none.
  DCHECK_EQ(create_heap_objects, startup_snapshot_data == nullptr);
  DCHECK_EQ(create_heap_objects, read_only_snapshot_data == nullptr);
  EnableRoAllocationForSnapshotScope enable_ro_allocation(this);
  base::ElapsedTimer timer;
  if (create_heap_objects && v8_flags.profile_deserialization) timer.Start();
  time_millis_at_init_ = heap_.MonotonicallyIncreasingTimeInMs();
  task_runner_ = V8::GetCurrentPlatform()->GetForegroundTaskRunner(
      reinterpret_cast<v8::Isolate*>(this));
  isolate_group()->AddIsolate(this);
  Isolate* const use_shared_space_isolate =
      isolate_group()->shared_space_isolate();
  CHECK_IMPLIES(is_shared_space_isolate_, V8_CAN_CREATE_SHARED_HEAP_BOOL);
  stress_deopt_count_ = v8_flags.deopt_every_n_times;
  force_slow_path_ = v8_flags.force_slow_path;
  flush_denormals_ = base::FPU::GetFlushDenormals();
  has_fatal_error_ = false;
  // The initialization process does not handle memory exhaustion.
  AlwaysAllocateScope always_allocate(heap());
#define ASSIGN_ELEMENT(CamelName, hacker_name) \
  isolate_addresses_[IsolateAddressId::k##CamelName##Address] = \
      reinterpret_cast<Address>(hacker_name##_address());
  FOR_EACH_ISOLATE_ADDRESS_NAME(ASSIGN_ELEMENT)
#undef ASSIGN_ELEMENT
  // We need to initialize code_pages_ before any on-heap code is allocated to
  // make sure we record all code allocations.
  InitializeCodeRanges();
  compilation_cache_ = new CompilationCache(this);
  descriptor_lookup_cache_ = new DescriptorLookupCache();
  global_handles_ = new GlobalHandles(this);
  eternal_handles_ = new EternalHandles();
  bootstrapper_ = new Bootstrapper(this);
  handle_scope_implementer_ = new HandleScopeImplementer(this);
  load_stub_cache_ = new StubCache(this);
  store_stub_cache_ = new StubCache(this);
  define_own_stub_cache_ = new StubCache(this);
  materialized_object_store_ = new MaterializedObjectStore(this);
  regexp_stack_ = new RegExpStack();
  isolate_data()->set_regexp_static_result_offsets_vector(
      jsregexp_static_offsets_vector());
  date_cache_ = new DateCache();
  interpreter_ = new interpreter::Interpreter(this);
  bigint_processor_ = bigint::Processor::New(new BigIntPlatform(this));
  if (is_shared_space_isolate_) {
    global_safepoint_ = std::make_unique<GlobalSafepoint>(this);
  }
  if (v8_flags.lazy_compile_dispatcher) {
    lazy_compile_dispatcher_ = std::make_unique<LazyCompileDispatcher>(
        this, V8::GetCurrentPlatform(), v8_flags.stack_size);
  }
#ifdef V8_ENABLE_SPARKPLUG
  baseline_batch_compiler_ = new baseline::BaselineBatchCompiler(this);
#endif // V8_ENABLE_SPARKPLUG
#ifdef V8_ENABLE_MAGLEV
  maglev_concurrent_dispatcher_ = new maglev::MaglevConcurrentDispatcher(this);
#endif // V8_ENABLE_MAGLEV
#if USE_SIMULATOR
  simulator_data_ = new SimulatorData;
#endif
  // Enable logging before setting up the heap
  v8_file_logger_->SetUp(this);
  metrics_recorder_ = std::make_shared<metrics::Recorder>();
  {
    // Ensure that the thread has a valid stack guard. The v8::Locker object
    // will ensure this too, but we don't have to use lockers if we are only
    // using one thread.
    ExecutionAccess lock(this);
    stack_guard()->InitThread(lock);
  }
  // Create LocalIsolate/LocalHeap for the main thread and set state to Running.
  main_thread_local_isolate_.reset(new LocalIsolate(this, ThreadKind::kMain));
  {
    IgnoreLocalGCRequests ignore_gc_requests(heap());
    main_thread_local_heap()->Unpark();
  }
  // Requires a LocalHeap to be set up to register a GC epilogue callback.
  inner_pointer_to_code_cache_ = new InnerPointerToCodeCache(this);
#if V8_ENABLE_WEBASSEMBLY
  wasm_code_look_up_cache_ = new wasm::WasmCodeLookupCache;
#endif // V8_ENABLE_WEBASSEMBLY
  // Lock clients_mutex_ in order to prevent shared GCs from other clients
  // during deserialization.
  std::optional<base::RecursiveMutexGuard> clients_guard;
  if (use_shared_space_isolate && !is_shared_space_isolate()) {
    clients_guard.emplace(
        &use_shared_space_isolate->global_safepoint()->clients_mutex_);
    use_shared_space_isolate->global_safepoint()->AppendClient(this);
  }
  shared_space_isolate_ = use_shared_space_isolate;
  isolate_data_.is_shared_space_isolate_flag_ = is_shared_space_isolate();
  isolate_data_.uses_shared_heap_flag_ = has_shared_space();
  if (use_shared_space_isolate && !is_shared_space_isolate() &&
      use_shared_space_isolate->heap()
          ->incremental_marking()
          ->IsMajorMarking()) {
    heap_.SetIsMarkingFlag(true);
  }
  // Set up the object heap.
  DCHECK(!heap_.HasBeenSetUp());
  heap_.SetUp(main_thread_local_heap());
  InitializeIsShortBuiltinCallsEnabled();
  if (!create_heap_objects) {
    // Must be done before deserializing RO space, since RO space may contain
    // builtin Code objects which point into the (potentially remapped)
    // embedded blob.
    MaybeRemapEmbeddedBuiltinsIntoCodeRange();
  }
  {
    // Must be done before deserializing RO space since the deserialization
    // process refers to these data structures.
    isolate_data_.external_reference_table()->InitIsolateIndependent(
        isolate_group()->external_ref_table());
#ifdef V8_COMPRESS_POINTERS
    external_pointer_table().Initialize();
    external_pointer_table().InitializeSpace(
        heap()->read_only_external_pointer_space());
    external_pointer_table().AttachSpaceToReadOnlySegments(
        heap()->read_only_external_pointer_space());
    external_pointer_table().InitializeSpace(
        heap()->young_external_pointer_space());
    external_pointer_table().InitializeSpace(
        heap()->old_external_pointer_space());
    cpp_heap_pointer_table().Initialize();
    cpp_heap_pointer_table().InitializeSpace(heap()->cpp_heap_pointer_space());
#endif // V8_COMPRESS_POINTERS
#ifdef V8_ENABLE_SANDBOX
    trusted_pointer_table().Initialize();
    trusted_pointer_table().InitializeSpace(heap()->trusted_pointer_space());
#endif // V8_ENABLE_SANDBOX
  }
  isolate_group()->SetupReadOnlyHeap(this, read_only_snapshot_data, can_rehash);
  heap_.SetUpSpaces(isolate_data_.new_allocation_info_,
                    isolate_data_.old_allocation_info_);
  DCHECK_EQ(this, Isolate::Current());
  PerIsolateThreadData* const current_data = CurrentPerIsolateThreadData();
  DCHECK_EQ(current_data->isolate(), this);
  SetIsolateThreadLocals(this, current_data);
  if (OwnsStringTables()) {
    string_table_ = std::make_unique<StringTable>(this);
    string_forwarding_table_ = std::make_unique<StringForwardingTable>(this);
  } else {
    // Only refer to shared string table after attaching to the shared isolate.
    DCHECK(has_shared_space());
    DCHECK(!is_shared_space_isolate());
    DCHECK_NOT_NULL(string_table());
    DCHECK_NOT_NULL(string_forwarding_table());
  }
#ifdef V8_EXTERNAL_CODE_SPACE
  {
    VirtualMemoryCage* code_cage;
    if (heap_.code_range()) {
      code_cage = heap_.code_range();
    } else {
      CHECK(jitless_);
      // In jitless mode the code space pages will be allocated in the main
      // pointer compression cage.
      code_cage = isolate_group_->GetPtrComprCage();
    }
    code_cage_base_ = ExternalCodeCompressionScheme::PrepareCageBaseAddress(
        code_cage->base());
    if (COMPRESS_POINTERS_IN_MULTIPLE_CAGES_BOOL) {
      // .. now that it's available, initialize the thread-local base.
      ExternalCodeCompressionScheme::InitBase(code_cage_base_);
    }
    CHECK_EQ(ExternalCodeCompressionScheme::base(), code_cage_base_);
    // Ensure that ExternalCodeCompressionScheme is applicable to all objects
    // stored in the code cage.
    using ComprScheme = ExternalCodeCompressionScheme;
    Address base = code_cage->base() + kHeapObjectTag;
    Address last = base + code_cage->size() - kTaggedSize;
    Address upper_bound = base + kPtrComprCageReservationSize - kTaggedSize;
    PtrComprCageBase code_cage_base{code_cage_base_};
    CHECK_EQ(base,
             ComprScheme::DecompressTagged(ComprScheme::CompressAny(base)));
    CHECK_EQ(last,
             ComprScheme::DecompressTagged(ComprScheme::CompressAny(last)));
    CHECK_EQ(upper_bound, ComprScheme::DecompressTagged(
                              ComprScheme::CompressAny(upper_bound)));
  }
#endif // V8_EXTERNAL_CODE_SPACE
  isolate_data_.external_reference_table()->Init(this);
#ifdef V8_COMPRESS_POINTERS
  if (owns_shareable_data()) {
    isolate_data_.shared_external_pointer_table_ = new ExternalPointerTable();
    shared_external_pointer_space_ = new ExternalPointerTable::Space();
    shared_external_pointer_table().Initialize();
    shared_external_pointer_table().InitializeSpace(
        shared_external_pointer_space());
  } else {
    DCHECK(has_shared_space());
    isolate_data_.shared_external_pointer_table_ =
        shared_space_isolate()->isolate_data_.shared_external_pointer_table_;
    shared_external_pointer_space_ =
        shared_space_isolate()->shared_external_pointer_space_;
  }
#endif // V8_COMPRESS_POINTERS
#ifdef V8_ENABLE_SANDBOX
  IsolateGroup::current()->code_pointer_table()->InitializeSpace(
      heap()->code_pointer_space());
  if (owns_shareable_data()) {
    isolate_data_.shared_trusted_pointer_table_ = new TrustedPointerTable();
    shared_trusted_pointer_space_ = new TrustedPointerTable::Space();
    shared_trusted_pointer_table().Initialize();
    shared_trusted_pointer_table().InitializeSpace(
        shared_trusted_pointer_space());
  } else {
    DCHECK(has_shared_space());
    isolate_data_.shared_trusted_pointer_table_ =
        shared_space_isolate()->isolate_data_.shared_trusted_pointer_table_;
    shared_trusted_pointer_space_ =
        shared_space_isolate()->shared_trusted_pointer_space_;
  }
#endif // V8_ENABLE_SANDBOX
#ifdef V8_ENABLE_LEAPTIERING
  IsolateGroup::current()->js_dispatch_table()->InitializeSpace(
      heap()->js_dispatch_table_space());
#endif // V8_ENABLE_LEAPTIERING
#if V8_ENABLE_WEBASSEMBLY
  wasm::GetWasmEngine()->AddIsolate(this);
#endif // V8_ENABLE_WEBASSEMBLY
#if defined(V8_ENABLE_ETW_STACK_WALKING)
  if (v8_flags.enable_etw_stack_walking ||
      v8_flags.enable_etw_by_custom_filter_only) {
    ETWJITInterface::AddIsolate(this);
  }
#endif // defined(V8_ENABLE_ETW_STACK_WALKING)
  if (setup_delegate_ == nullptr) {
    setup_delegate_ = new SetupIsolateDelegate;
  }
  if (!v8_flags.inline_new) heap_.DisableInlineAllocation();
  if (!setup_delegate_->SetupHeap(this, create_heap_objects)) {
    V8::FatalProcessOutOfMemory(this, "heap object creation");
  }
  if (create_heap_objects) {
    // Terminate the startup and shared heap object caches so we can iterate.
    startup_object_cache_.push_back(ReadOnlyRoots(this).undefined_value());
    shared_heap_object_cache_.push_back(ReadOnlyRoots(this).undefined_value());
  }
  InitializeThreadLocal();
  // Profiler has to be created after ThreadLocal is initialized
  // because it makes use of interrupts.
  tracing_cpu_profiler_.reset(new TracingCpuProfilerImpl(this));
  bootstrapper_->Initialize(create_heap_objects);
  if (create_heap_objects) {
    builtins_constants_table_builder_ = new BuiltinsConstantsTableBuilder(this);
    if (v8_flags.concurrent_builtin_generation) {
      optimizing_compile_dispatcher_ = new OptimizingCompileDispatcher(
          this, isolate_group_->optimizing_compile_task_executor());
      optimizing_compile_dispatcher_->set_finalize(false);
    }
    setup_delegate_->SetupBuiltins(this, true);
    if (v8_flags.concurrent_builtin_generation) {
      delete optimizing_compile_dispatcher_;
      optimizing_compile_dispatcher_ = nullptr;
    }
    builtins_constants_table_builder_->Finalize();
    delete builtins_constants_table_builder_;
    builtins_constants_table_builder_ = nullptr;
    CreateAndSetEmbeddedBlob();
  } else {
    setup_delegate_->SetupBuiltins(this, false);
  }
  // Initialize custom memcopy and memmove functions (must happen after
  // embedded blob setup).
  init_memcopy_functions();
  if ((v8_flags.trace_turbo || v8_flags.trace_turbo_graph ||
       v8_flags.turbo_profiling) &&
      !v8_flags.concurrent_turbo_tracing) {
    PrintF("Concurrent recompilation has been disabled for tracing.\n");
  } else if (OptimizingCompileDispatcher::Enabled()) {
    optimizing_compile_dispatcher_ = new OptimizingCompileDispatcher(
        this, isolate_group_->optimizing_compile_task_executor());
  }
  // Initialize before deserialization since collections may occur,
  // clearing/updating ICs (and thus affecting tiering decisions).
  tiering_manager_ = new TieringManager(this);
  if (!create_heap_objects) {
    // If we are deserializing, read the state into the now-empty heap.
    SharedHeapDeserializer shared_heap_deserializer(
        this, shared_heap_snapshot_data, can_rehash);
    shared_heap_deserializer.DeserializeIntoIsolate();
    StartupDeserializer startup_deserializer(this, startup_snapshot_data,
                                             can_rehash);
    startup_deserializer.DeserializeIntoIsolate();
  }
  InitializeBuiltinJSDispatchTable();
  if (DEBUG_BOOL) VerifyStaticRoots();
  load_stub_cache_->Initialize();
  store_stub_cache_->Initialize();
  define_own_stub_cache_->Initialize();
  interpreter_->Initialize();
  heap_.NotifyDeserializationComplete();
  delete setup_delegate_;
  setup_delegate_ = nullptr;
  Builtins::InitializeIsolateDataTables(this);
  // Extra steps in the logger after the heap has been set up.
  v8_file_logger_->LateSetup(this);
#ifdef DEBUG
  // Verify that the current heap state (usually deserialized from the snapshot)
  // is compatible with the embedded blob. If this DCHECK fails, we've likely
  // loaded a snapshot generated by a different V8 version or build-time
  // configuration.
  if (!IsolateIsCompatibleWithEmbeddedBlob(this)) {
    FATAL(
        "The Isolate is incompatible with the embedded blob. This is usually "
        "caused by incorrect usage of mksnapshot. When generating custom "
        "snapshots, embedders must ensure they pass the same flags as during "
        "the V8 build process (e.g.: --turbo-instruction-scheduling).");
  }
#endif // DEBUG
  if (v8_flags.print_builtin_code) builtins()->PrintBuiltinCode();
  if (v8_flags.print_builtin_size) builtins()->PrintBuiltinSize();
  // Finish initialization of ThreadLocal after deserialization is done.
  clear_exception();
  clear_pending_message();
  // Quiet the heap NaN if needed on target platform.
  if (!create_heap_objects)
    Assembler::QuietNaN(ReadOnlyRoots(this).nan_value());
  if (v8_flags.trace_turbo) {
    // Create an empty file.
    std::ofstream(GetTurboCfgFileName(this).c_str(), std::ios_base::trunc);
  }
  isolate_data_.continuation_preserved_embedder_data_ =
      *factory()->undefined_value();
  {
    HandleScope scope(this);
    ast_string_constants_ = new AstStringConstants(this, HashSeed(this));
  }
  initialized_from_snapshot_ = !create_heap_objects;
  if (v8_flags.stress_sampling_allocation_profiler > 0) {
    uint64_t sample_interval = v8_flags.stress_sampling_allocation_profiler;
    int stack_depth = 128;
    v8::HeapProfiler::SamplingFlags sampling_flags =
        v8::HeapProfiler::SamplingFlags::kSamplingForceGC;
    heap()->heap_profiler()->StartSamplingHeapProfiler(
        sample_interval, stack_depth, sampling_flags);
  }
  if (create_heap_objects && v8_flags.profile_deserialization) {
    double ms = timer.Elapsed().InMillisecondsF();
    PrintF("[Initializing isolate from scratch took %0.3f ms]\n", ms);
  }
  if (initialized_from_snapshot_) {
    SLOW_DCHECK(SharedFunctionInfo::UniqueIdsAreUnique(this));
  }
  if (v8_flags.harmony_struct) {
    // Initialize or get the struct type registry shared by all isolates.
    if (is_shared_space_isolate()) {
      shared_struct_type_registry_ =
          std::make_unique<SharedStructTypeRegistry>();
    } else {
      DCHECK_NOT_NULL(shared_struct_type_registry());
    }
  }
#ifdef V8_ENABLE_WEBASSEMBLY
#if V8_STATIC_ROOTS_BOOL
  // Protect the payload of wasm null.
  if (!page_allocator()->DecommitPages(
          reinterpret_cast<void*>(factory()->wasm_null()->payload()),
          WasmNull::kSize - kTaggedSize)) {
    V8::FatalProcessOutOfMemory(this, "decommitting WasmNull payload");
  }
#endif // V8_STATIC_ROOTS_BOOL
#endif // V8_ENABLE_WEBASSEMBLY
  // Isolate initialization allocates long living objects that should be
  // pretenured to old space.
  DCHECK_IMPLIES(heap()->new_space(), heap()->new_space()->Size() == 0);
  DCHECK_IMPLIES(heap()->new_lo_space(), heap()->new_lo_space()->Size() == 0);
  DCHECK_EQ(heap()->gc_count(), 0);
#if defined(V8_ENABLE_ETW_STACK_WALKING)
  if (v8_flags.enable_etw_stack_walking ||
      v8_flags.enable_etw_by_custom_filter_only) {
    ETWJITInterface::MaybeSetHandlerNow(this);
  }
#endif // defined(V8_ENABLE_ETW_STACK_WALKING)
#if defined(V8_USE_PERFETTO)
  PerfettoLogger::RegisterIsolate(this);
#endif // defined(V8_USE_PERFETTO)
  initialized_ = true;
  return true;
}
References v8::internal::ETWJITInterface::AddIsolate(), v8::internal::IsolateGroup::AddIsolate(), v8::internal::wasm::WasmEngine::AddIsolate(), v8::internal::GlobalSafepoint::AppendClient(), ASSIGN_ELEMENT, ast_string_constants_, v8::internal::V8HeapCompressionSchemeImpl< Cage >::base(), v8::internal::VirtualMemoryCage::base(), bigint_processor_, bootstrapper_, builtins(), builtins_constants_table_builder_, cage_base(), CHECK, CHECK_EQ, CHECK_IMPLIES, clear_exception(), clear_pending_message(), v8::internal::GlobalSafepoint::clients_mutex_, code_cage_base(), v8::internal::Heap::code_range(), compilation_cache_, COMPRESS_POINTERS_IN_MULTIPLE_CAGES_BOOL, v8::internal::IsolateData::continuation_preserved_embedder_data_, CreateAndSetEmbeddedBlob(), Current(), v8::internal::IsolateGroup::current(), CurrentPerIsolateThreadData(), date_cache_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, DCHECK_NOT_NULL, DEBUG_BOOL, define_own_stub_cache_, descriptor_lookup_cache_, v8::internal::SharedHeapDeserializer::DeserializeIntoIsolate(), v8::internal::StartupDeserializer::DeserializeIntoIsolate(), v8::internal::Heap::DisableInlineAllocation(), v8::base::ElapsedTimer::Elapsed(), v8::internal::OptimizingCompileDispatcher::Enabled(), eternal_handles_, v8::internal::IsolateData::external_reference_table(), factory(), FATAL, v8::internal::V8::FatalProcessOutOfMemory(), v8::internal::BuiltinsConstantsTableBuilder::Finalize(), flush_denormals_, FOR_EACH_ISOLATE_ADDRESS_NAME, force_slow_path_, v8::internal::V8::GetCurrentPlatform(), v8::base::FPU::GetFlushDenormals(), v8::Platform::GetForegroundTaskRunner(), GetTurboCfgFileName(), v8::internal::wasm::GetWasmEngine(), global_handles_, global_safepoint(), global_safepoint_, handle_scope_implementer_, has_fatal_error_, has_shared_space(), v8::internal::Heap::HasBeenSetUp(), v8::internal::HashSeed(), heap(), heap_, v8::internal::Heap::heap_profiler(), v8::internal::Heap::incremental_marking(), v8::internal::ExternalReferenceTable::Init(), v8::internal::init_memcopy_functions(), v8::internal::StubCache::Initialize(), v8::internal::interpreter::Interpreter::Initialize(), v8::internal::Bootstrapper::Initialize(), InitializeBuiltinJSDispatchTable(), InitializeCodeRanges(), initialized_, initialized_from_snapshot_, v8::internal::Builtins::InitializeIsolateDataTables(), InitializeIsShortBuiltinCallsEnabled(), InitializeThreadLocal(), v8::internal::ExternalReferenceTable::InitIsolateIndependent(), v8::internal::StackGuard::InitThread(), v8::base::TimeDelta::InMillisecondsF(), inner_pointer_to_code_cache_, interpreter_, is_shared_space_isolate(), is_shared_space_isolate_, v8::internal::IsolateData::is_shared_space_isolate_flag_, v8::internal::IncrementalMarking::IsMajorMarking(), v8::internal::Isolate::PerIsolateThreadData::isolate(), isolate_data(), isolate_data_, isolate_group(), isolate_group_, jitless_, v8::internal::kHeapObjectTag, v8::internal::kMain, v8::internal::WasmNull::kSize, v8::internal::kTaggedSize, v8::internal::V8FileLogger::LateSetup(), lazy_compile_dispatcher_, load_stub_cache_, main_thread_local_heap(), main_thread_local_isolate_, materialized_object_store_, MaybeRemapEmbeddedBuiltinsIntoCodeRange(), v8::internal::ETWJITInterface::MaybeSetHandlerNow(), metrics_recorder_, v8::internal::Heap::MonotonicallyIncreasingTimeInMs(), v8::bigint::Processor::New(), v8::internal::IsolateData::new_allocation_info_, v8::internal::Heap::NotifyDeserializationComplete(), v8::internal::IsolateData::old_allocation_info_, optimizing_compile_dispatcher_, v8::internal::IsolateGroup::optimizing_compile_task_executor(), owns_shareable_data(), OwnsStringTables(), page_allocator(), v8::internal::Builtins::PrintBuiltinCode(), v8::internal::Builtins::PrintBuiltinSize(), v8::internal::PrintF(), v8::internal::AssemblerBase::QuietNaN(), regexp_stack_, v8::internal::PerfettoLogger::RegisterIsolate(), v8::internal::OptimizingCompileDispatcher::set_finalize(), v8::internal::IsolateData::set_regexp_static_result_offsets_vector(), v8::internal::Heap::SetIsMarkingFlag(), SetIsolateThreadLocals(), v8::internal::V8FileLogger::SetUp(), v8::internal::Heap::SetUp(), setup_delegate_, v8::internal::SetupIsolateDelegate::SetupBuiltins(), v8::internal::SetupIsolateDelegate::SetupHeap(), v8::internal::IsolateGroup::SetupReadOnlyHeap(), v8::internal::Heap::SetUpSpaces(), shared_heap_object_cache_, shared_space_isolate(), v8::internal::IsolateGroup::shared_space_isolate(), shared_space_isolate_, shared_struct_type_registry(), shared_struct_type_registry_, v8::internal::VirtualMemoryCage::size(), SLOW_DCHECK, stack_guard(), v8::base::ElapsedTimer::Start(), v8::internal::HeapProfiler::StartSamplingHeapProfiler(), startup_object_cache_, store_stub_cache_, stress_deopt_count_, string_forwarding_table(), string_forwarding_table_, string_table(), string_table_, task_runner_, tiering_manager_, time_millis_at_init_, TRACE_ISOLATE, tracing_cpu_profiler_, v8::internal::LocalHeap::Unpark(), v8::internal::IsolateData::uses_shared_heap_flag_, V8_CAN_CREATE_SHARED_HEAP_BOOL, v8_file_logger_, v8::internal::v8_flags, and VerifyStaticRoots().
Referenced by InitWithoutSnapshot(), and InitWithSnapshot().
InitializeBuiltinJSDispatchTable()
void v8::internal::Isolate::InitializeBuiltinJSDispatchTable () [private]
Definition at line 7759 of file isolate.cc.
                                               {
#ifdef V8_ENABLE_LEAPTIERING
  // Ideally these entries would be created when the read only heap is
  // initialized. However, since builtins are deserialized later, we need to
  // patch it up here. Also, we need a mutex so the shared read only heaps space
  // is not initialized multiple times. This must be blocking as no isolate
  // should be allowed to proceed until the table is initialized.
  base::MutexGuard guard(read_only_dispatch_entries_mutex_.Pointer());
  JSDispatchTable* jdt = IsolateGroup::current()->js_dispatch_table();
  bool needs_initialization =
      !V8_STATIC_DISPATCH_HANDLES_BOOL ||
      jdt->PreAllocatedEntryNeedsInitialization(
          read_only_heap_->js_dispatch_table_space(),
          builtin_dispatch_handle(JSBuiltinDispatchHandleRoot::Idx::kFirst));
  if (needs_initialization) {
    std::optional<JSDispatchTable::UnsealReadOnlySegmentScope> unseal_scope;
    if (V8_STATIC_DISPATCH_HANDLES_BOOL) {
      unseal_scope.emplace(jdt);
    }
    for (JSBuiltinDispatchHandleRoot::Idx idx =
             JSBuiltinDispatchHandleRoot::kFirst;
         idx < JSBuiltinDispatchHandleRoot::kCount;
         idx = static_cast<JSBuiltinDispatchHandleRoot::Idx>(
             static_cast<int>(idx) + 1)) {
      Builtin builtin = JSBuiltinDispatchHandleRoot::to_builtin(idx);
      DCHECK(Builtins::IsIsolateIndependent(builtin));
      Tagged<Code> code = builtins_.code(builtin);
      DCHECK(code->entrypoint_tag() == CodeEntrypointTag::kJSEntrypointTag);
      // TODO(olivf, 40931165): It might be more robust to get the static
      // parameter count of this builtin.
      int parameter_count = code->parameter_count();
#if V8_STATIC_DISPATCH_HANDLES_BOOL
      JSDispatchHandle handle = builtin_dispatch_handle(builtin);
      jdt->InitializePreAllocatedEntry(
          read_only_heap_->js_dispatch_table_space(), handle, code,
          parameter_count);
#else
      CHECK_LT(idx, JSBuiltinDispatchHandleRoot::kTableSize);
      JSDispatchHandle handle = jdt->AllocateAndInitializeEntry(
          read_only_heap_->js_dispatch_table_space(), parameter_count, code);
      isolate_data_.builtin_dispatch_table()[idx] = handle;
#endif // V8_STATIC_DISPATCH_HANDLES_BOOL
    }
  }
#endif
}
References builtins_, CHECK_LT, v8::internal::Builtins::code(), code, v8::internal::IsolateGroup::current(), v8::internal::DCHECK(), v8::internal::handle(), v8::internal::Builtins::IsIsolateIndependent(), isolate_data_, v8::internal::kJSEntrypointTag, v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Pointer(), v8::internal::read_only_dispatch_entries_mutex_, and read_only_heap_.
Referenced by Init().
InitializeCodeRanges()
void v8::internal::Isolate::InitializeCodeRanges () [private]
Definition at line 5377 of file isolate.cc.
                                   {
  DCHECK_NULL(GetCodePages());
  MemoryRange embedded_range{
      reinterpret_cast<const void*>(embedded_blob_code()),
      embedded_blob_code_size()};
  code_pages_buffer1_.push_back(embedded_range);
  SetCodePages(&code_pages_buffer1_);
}
References code_pages_buffer1_, DCHECK_NULL, embedded_blob_code(), embedded_blob_code_size(), GetCodePages(), and SetCodePages().
Referenced by Init().
InitializeCounters()
bool v8::internal::Isolate::InitializeCounters ()
Definition at line 5130 of file isolate.cc.
                                 {
  if (async_counters_) return false;
  async_counters_ = std::make_shared<Counters>(this);
  return true;
}
References async_counters_.
Referenced by InitializeLoggingAndCounters().
initialized_from_snapshot()
bool v8::internal::Isolate::initialized_from_snapshot () [inline]
Definition at line 1588 of file isolate.h.
{ return initialized_from_snapshot_; }
Referenced by v8::internal::Genesis::Genesis(), and v8::internal::Bootstrapper::LogAllMaps().
InitializeDefaultEmbeddedBlob()
void v8::internal::Isolate::InitializeDefaultEmbeddedBlob () [private]
Definition at line 5180 of file isolate.cc.
                                            {
  const uint8_t* code = DefaultEmbeddedBlobCode();
  uint32_t code_size = DefaultEmbeddedBlobCodeSize();
  const uint8_t* data = DefaultEmbeddedBlobData();
  uint32_t data_size = DefaultEmbeddedBlobDataSize();
  if (StickyEmbeddedBlobCode() != nullptr) {
    base::MutexGuard guard(current_embedded_blob_refcount_mutex_.Pointer());
    // Check again now that we hold the lock.
    if (StickyEmbeddedBlobCode() != nullptr) {
      code = StickyEmbeddedBlobCode();
      code_size = StickyEmbeddedBlobCodeSize();
      data = StickyEmbeddedBlobData();
      data_size = StickyEmbeddedBlobDataSize();
      current_embedded_blob_refs_++;
    }
  }
  if (code_size == 0) {
    CHECK_EQ(0, data_size);
  } else {
    SetEmbeddedBlob(code, code_size, data, data_size);
  }
}
References CHECK_EQ, code, v8::internal::anonymous_namespace{isolate.cc}::current_embedded_blob_refcount_mutex_, v8::internal::anonymous_namespace{isolate.cc}::current_embedded_blob_refs_, v8::internal::DefaultEmbeddedBlobCode(), v8::internal::DefaultEmbeddedBlobCodeSize(), v8::internal::DefaultEmbeddedBlobData(), v8::internal::DefaultEmbeddedBlobDataSize(), v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Pointer(), SetEmbeddedBlob(), v8::internal::anonymous_namespace{isolate.cc}::StickyEmbeddedBlobCode(), v8::internal::anonymous_namespace{isolate.cc}::StickyEmbeddedBlobCodeSize(), v8::internal::anonymous_namespace{isolate.cc}::StickyEmbeddedBlobData(), and v8::internal::anonymous_namespace{isolate.cc}::StickyEmbeddedBlobDataSize().
Referenced by Isolate().
InitializeIsShortBuiltinCallsEnabled()
void v8::internal::Isolate::InitializeIsShortBuiltinCallsEnabled () [private]
Definition at line 5238 of file isolate.cc.
                                                   {
  if (V8_SHORT_BUILTIN_CALLS_BOOL && v8_flags.short_builtin_calls) {
#if defined(V8_OS_ANDROID)
    // On Android, the check is not operative to detect memory, and re-embedded
    // builtins don't have a memory cost.
    is_short_builtin_calls_enabled_ = true;
#else
    // Check if the system has more than 4GB of physical memory by comparing the
    // old space size with respective threshold value.
    is_short_builtin_calls_enabled_ = (heap_.MaxOldGenerationSize() >=
                                       kShortBuiltinCallsOldSpaceSizeThreshold);
#endif // defined(V8_OS_ANDROID)
    // Additionally, enable if there is already a process-wide CodeRange that
    // has re-embedded builtins.
    if (COMPRESS_POINTERS_BOOL) {
      CodeRange* code_range = isolate_group()->GetCodeRange();
      if (code_range && code_range->embedded_blob_code_copy() != nullptr) {
        is_short_builtin_calls_enabled_ = true;
      }
    }
    if (V8_ENABLE_NEAR_CODE_RANGE_BOOL) {
      // The short builtin calls could still be enabled if allocated code range
      // is close enough to embedded builtins so that the latter could be
      // reached using pc-relative (short) calls/jumps.
      is_short_builtin_calls_enabled_ |=
          GetShortBuiltinsCallRegion().contains(heap_.code_region());
    }
  }
}
References v8::internal::Heap::code_region(), COMPRESS_POINTERS_BOOL, v8::base::AddressRegion::contains(), v8::internal::CodeRange::embedded_blob_code_copy(), v8::internal::IsolateGroup::GetCodeRange(), GetShortBuiltinsCallRegion(), heap_, is_short_builtin_calls_enabled_, isolate_group(), v8::internal::kShortBuiltinCallsOldSpaceSizeThreshold, v8::internal::Heap::MaxOldGenerationSize(), V8_ENABLE_NEAR_CODE_RANGE_BOOL, v8::internal::v8_flags, and V8_SHORT_BUILTIN_CALLS_BOOL.
Referenced by Init().
InitializeLoggingAndCounters()
void v8::internal::Isolate::InitializeLoggingAndCounters ()
Definition at line 5136 of file isolate.cc.
                                           {
  if (v8_file_logger_ == nullptr) {
    v8_file_logger_ = new V8FileLogger(this);
  }
  InitializeCounters();
}
References InitializeCounters(), and v8_file_logger_.
Referenced by v8::internal::Serializer::InitializeCodeAddressMap(), Isolate(), PrintStack(), and v8::Isolate::SetJitCodeEventHandler().
InitializeNextUniqueSfiId()
void v8::internal::Isolate::InitializeNextUniqueSfiId (uint32_t id) [inline], [private]
Definition at line 2794 of file isolate.h.
                                              {
    uint32_t expected = 0; // Called at most once per Isolate on startup.
    bool successfully_exchanged = next_unique_sfi_id_.compare_exchange_strong(
        expected, id, std::memory_order_relaxed, std::memory_order_relaxed);
    CHECK(successfully_exchanged);
  }
References CHECK.
Referenced by SetUpFromReadOnlyArtifacts().
InitializeOncePerProcess()
void v8::internal::Isolate::InitializeOncePerProcess () [static]
Definition at line 594 of file isolate.cc.
{ Heap::InitializeOncePerProcess(); }
References v8::internal::Heap::InitializeOncePerProcess().
Referenced by v8::internal::V8::Initialize().
InitializeThreadLocal()
void v8::internal::Isolate::InitializeThreadLocal ()
Definition at line 4846 of file isolate.cc.
                                    {
  thread_local_top()->Initialize(this);
  // This method might be called on a thread that's not bound to any Isolate
  // and thus pointer compression schemes might have cage base value unset.
  // So, allow heap access here to let the checks work.
  i::PtrComprCageAccessScope ptr_compr_cage_access_scope(this);
  clear_exception();
  clear_pending_message();
}
References clear_exception(), clear_pending_message(), v8::internal::ThreadLocalTop::Initialize(), and thread_local_top().
Referenced by Init(), and v8::internal::ThreadManager::InitThread().
InitWithoutSnapshot()
bool v8::internal::Isolate::InitWithoutSnapshot ()
Definition at line 5314 of file isolate.cc.
                                  {
  return Init(nullptr, nullptr, nullptr, false);
}
References Init().
Referenced by v8::internal::SnapshotCreatorImpl::InitInternal().
InitWithSnapshot()
bool v8::internal::Isolate::InitWithSnapshot (SnapshotData * startup_snapshot_data, SnapshotData * read_only_snapshot_data, SnapshotData * shared_heap_snapshot_data, bool can_rehash)
Definition at line 5318 of file isolate.cc.
                                                {
  DCHECK_NOT_NULL(startup_snapshot_data);
  DCHECK_NOT_NULL(read_only_snapshot_data);
  DCHECK_NOT_NULL(shared_heap_snapshot_data);
  return Init(startup_snapshot_data, read_only_snapshot_data,
              shared_heap_snapshot_data, can_rehash);
}
References DCHECK_NOT_NULL, and Init().
Referenced by v8::internal::Snapshot::Initialize().
inner_pointer_to_code_cache()
InnerPointerToCodeCache* v8::internal::Isolate::inner_pointer_to_code_cache () [inline]
Definition at line 1419 of file isolate.h.
                                                         {
    return inner_pointer_to_code_cache_;
  }
Referenced by v8::internal::anonymous_namespace{frames.cc}::GetContainingCode(), v8::internal::TypedFrame::Iterate(), v8::internal::MaglevFrame::Iterate(), v8::internal::CommonFrame::IterateTurbofanJSOptimizedFrame(), and UnwindAndFindHandler().
InstallConditionalFeatures()
void v8::internal::Isolate::InstallConditionalFeatures (DirectHandle< NativeContext > context)
Definition at line 3698 of file isolate.cc.
                                                                            {
  DirectHandle<JSGlobalObject> global =
      direct_handle(context->global_object(), this);
  // If some fuzzer decided to make the global object non-extensible, then
  // we can't install any features (and would CHECK-fail if we tried).
  if (!global->map()->is_extensible()) return;
  DirectHandle<String> sab_name = factory()->SharedArrayBuffer_string();
  if (IsSharedArrayBufferConstructorEnabled(context)) {
    if (!JSObject::HasRealNamedProperty(this, global, sab_name)
             .FromMaybe(true)) {
      JSObject::AddProperty(this, global, factory()->SharedArrayBuffer_string(),
                            shared_array_buffer_fun(), DONT_ENUM);
    }
  }
}
References v8::internal::JSObject::AddProperty(), context(), v8::internal::direct_handle(), v8::internal::DONT_ENUM, factory(), v8::internal::JSObject::HasRealNamedProperty(), and IsSharedArrayBufferConstructorEnabled().
Referenced by v8::CALLBACK_SETTER().
internalized_string_access()
base::Mutex* v8::internal::Isolate::internalized_string_access () [inline]
Definition at line 758 of file isolate.h.
                                          {
    return &internalized_string_access_;
  }
Referenced by v8::internal::String::MakeExternal(), and v8::internal::SharedStringAccessGuardIfNeeded::SharedStringAccessGuardIfNeeded().
interpreted_frames_native_stack()
bool v8::internal::Isolate::interpreted_frames_native_stack () const [inline]
Definition at line 2106 of file isolate.h.
                                               {
    return v8_flags.interpreted_frames_native_stack;
  }
References v8::internal::v8_flags.
Referenced by v8::internal::ETWJITInterface::EventHandler(), v8::internal::anonymous_namespace{code-serializer.cc}::FinalizeDeserialization(), v8::internal::anonymous_namespace{compiler.cc}::FinalizeUnoptimizedCompilation(), v8::internal::Compiler::InstallInterpreterTrampolineCopy(), v8::internal::anonymous_namespace{frames.cc}::IsInterpreterFramePc(), v8::internal::SharedFunctionInfo::set_interpreter_data(), and v8::internal::anonymous_namespace{perfetto-logger.cc}::WriteJsCode().
interpreter()
interpreter::Interpreter* v8::internal::Isolate::interpreter () const [inline]
Definition at line 2008 of file isolate.h.
{ return interpreter_; }
Referenced by v8::internal::IgnitionStatisticsExtension::GetIgnitionDispatchCounters().
InvokeApiInterruptCallbacks()
void v8::internal::Isolate::InvokeApiInterruptCallbacks ()
Definition at line 1975 of file isolate.cc.
                                          {
  RCS_SCOPE(this, RuntimeCallCounterId::kInvokeApiInterruptCallbacks);
  // Note: callback below should be called outside of execution access lock.
  while (true) {
    InterruptEntry entry;
    {
      ExecutionAccess access(this);
      if (api_interrupts_queue_.empty()) return;
      entry = api_interrupts_queue_.front();
      api_interrupts_queue_.pop();
    }
    VMState<EXTERNAL> state(this);
    HandleScope handle_scope(this);
    entry.first(reinterpret_cast<v8::Isolate*>(this), entry.second);
  }
}
References api_interrupts_queue_, and RCS_SCOPE.
Referenced by v8::internal::StackGuard::HandleInterrupts().
is_backgrounded()
bool v8::internal::Isolate::is_backgrounded () [inline]
Definition at line 2123 of file isolate.h.
                         {
    return priority_ == v8::Isolate::Priority::kBestEffort;
  }
References v8::Isolate::kBestEffort.
is_best_effort_code_coverage()
bool v8::internal::Isolate::is_best_effort_code_coverage () const [inline]
Definition at line 1600 of file isolate.h.
                                            {
    return code_coverage_mode() == debug::CoverageMode::kBestEffort;
  }
References v8::debug::kBestEffort.
Referenced by v8::internal::FeedbackVector::AddToVectorsForProfilingTools(), v8::internal::Coverage::CollectPrecise(), v8::internal::JSFunction::InitializeFeedbackCell(), v8::internal::FeedbackVector::New(), and v8::internal::UnoptimizedCompileFlags::UnoptimizedCompileFlags().
is_binary_code_coverage()
bool v8::internal::Isolate::is_binary_code_coverage () const [inline]
Definition at line 1624 of file isolate.h.
                                       {
    return is_precise_binary_code_coverage() || is_block_binary_code_coverage();
  }
is_block_binary_code_coverage()
bool v8::internal::Isolate::is_block_binary_code_coverage () const [inline]
Definition at line 1616 of file isolate.h.
                                             {
    return code_coverage_mode() == debug::CoverageMode::kBlockBinary;
  }
References v8::debug::kBlockBinary.
Referenced by v8::internal::Coverage::CollectPrecise().
is_block_code_coverage()
bool v8::internal::Isolate::is_block_code_coverage () const [inline]
Definition at line 1620 of file isolate.h.
                                      {
    return is_block_count_code_coverage() || is_block_binary_code_coverage();
  }
Referenced by v8::internal::UnoptimizedCompileFlags::UnoptimizedCompileFlags().
is_block_count_code_coverage()
bool v8::internal::Isolate::is_block_count_code_coverage () const [inline]
Definition at line 1612 of file isolate.h.
                                            {
    return code_coverage_mode() == debug::CoverageMode::kBlockCount;
  }
References v8::debug::kBlockCount.
is_catchable_by_javascript()
bool v8::internal::Isolate::is_catchable_by_javascript (Tagged< Object > exception) [inline]
Definition at line 190 of file isolate-inl.h.
                                                                 {
  return exception != ReadOnlyRoots(heap()).termination_exception();
}
References exception(), and heap().
Referenced by v8::internal::SourceTextModule::AsyncModuleExecutionRejected(), v8::internal::JSDisposableStackBase::HandleErrorInDisposal(), is_catchable_by_wasm(), v8::internal::SourceTextModule::MaybeHandleEvaluationException(), v8::internal::JSAsyncDisposableStack::NextDisposeAsyncIteration(), PropagateExceptionToExternalTryCatch(), v8::internal::Module::RecordError(), ReportPendingMessages(), v8::internal::JSPromise::Resolve(), Throw(), TopExceptionHandlerType(), and UnwindAndFindHandler().
is_catchable_by_wasm()
bool v8::internal::Isolate::is_catchable_by_wasm (Tagged< Object > exception) [inline]
Definition at line 198 of file isolate-inl.h.
                                                           {
  if (!is_catchable_by_javascript(exception)) return false;
  if (!IsJSObject(exception)) return true;
  return !LookupIterator::HasInternalMarkerProperty(
      this, Cast<JSReceiver>(exception), factory()->wasm_uncatchable_symbol());
}
References exception(), factory(), v8::internal::LookupIterator::HasInternalMarkerProperty(), and is_catchable_by_javascript().
Referenced by v8::internal::wasm::WasmInterpreterRuntime::HandleException(), and UnwindAndFindHandler().
is_count_code_coverage()
bool v8::internal::Isolate::is_count_code_coverage () const [inline]
Definition at line 1628 of file isolate.h.
                                      {
    return is_precise_count_code_coverage() || is_block_count_code_coverage();
  }
is_execution_terminating()
bool v8::internal::Isolate::is_execution_terminating () [inline]
Definition at line 131 of file isolate-inl.h.
                                       {
  return thread_local_top()->exception_ ==
         i::ReadOnlyRoots(this).termination_exception();
}
References v8::internal::ThreadLocalTop::exception_, and thread_local_top().
Referenced by v8::internal::anonymous_namespace{messages.cc}::AppendErrorString(), v8::internal::wasm::WasmEngine::AsyncInstantiate(), v8::CALLBACK_SETTER(), CancelTerminateExecution(), v8::internal::anonymous_namespace{builtins-console.cc}::ConsoleCall(), v8::debug::PropertyIterator::Create(), v8::CreateEnvironment(), v8::EnterV8BasicScope::EnterV8BasicScope(), v8::EnterV8InternalScope< HandleScopeClass, do_callback >::EnterV8InternalScope(), v8::internal::SourceTextModule::ExecuteAsyncModule(), v8::Shell::ExecuteString(), FireCallCompletedCallbackInternal(), v8::internal::SourceTextModule::InnerModuleEvaluation(), v8::internal::AsmJs::InstantiateAsmWasm(), v8::internal::InvokeFinalizationRegistryCleanupFromTask(), v8::internal::anonymous_namespace{execution.cc}::InvokeWithTryCatch(), v8::Isolate::IsExecutionTerminating(), OnTerminationDuringRunMicrotasks(), v8::PrepareForDebugInterfaceExecutionScope::PrepareForDebugInterfaceExecutionScope(), v8::Object::PreviewEntries(), v8::internal::MemoryMeasurement::ReportResults(), RunHostImportModuleDynamicallyCallback(), v8::internal::MicrotaskQueue::RunMicrotasks(), SetTerminationOnExternalTryCatch(), v8::internal::Debug::StopSideEffectCheckMode(), and v8::MicrotasksScope::~MicrotasksScope().
is_precise_binary_code_coverage()
bool v8::internal::Isolate::is_precise_binary_code_coverage () const [inline]
Definition at line 1608 of file isolate.h.
                                               {
    return code_coverage_mode() == debug::CoverageMode::kPreciseBinary;
  }
References v8::debug::kPreciseBinary.
Referenced by v8::internal::Coverage::CollectPrecise().
is_precise_count_code_coverage()
bool v8::internal::Isolate::is_precise_count_code_coverage () const [inline]
Definition at line 1604 of file isolate.h.
                                              {
    return code_coverage_mode() == debug::CoverageMode::kPreciseCount;
  }
References v8::debug::kPreciseCount.
Referenced by use_optimizer().
is_profiling()
bool v8::internal::Isolate::is_profiling () const [inline]
Definition at line 1502 of file isolate.h.
                            {
    return isolate_data_.execution_mode_ &
           IsolateExecutionModeFlag::kIsProfiling;
  }
References v8::internal::kIsProfiling.
Referenced by v8::internal::compiler::CompilationDependencies::DependOnNoProfilingProtector(), v8::internal::V8FileLogger::is_logging(), IsLoggingCodeCreation(), and NeedsSourcePositions().
is_shared_space_isolate()
bool v8::internal::Isolate::is_shared_space_isolate () const [inline]
Definition at line 2332 of file isolate.h.
{ return is_shared_space_isolate_; }
Referenced by v8::internal::Heap::ExternalStringTable::AddString(), v8::internal::MarkCompactCollector::ClearNonLiveReferences(), v8::internal::anonymous_namespace{mark-compact.cc}::ClearSharedStructTypeRegistryJobItem::ClearSharedStructTypeRegistryJobItem(), v8::internal::anonymous_namespace{heap.cc}::ClearStubCaches(), Deinit(), Init(), v8::internal::WriteBarrier::MarkingFromCode(), v8::internal::MarkCompactCollector::MarkObjectsFromClientHeaps(), v8::internal::MarkCompactCollector::MarkRoots(), v8::internal::MarkCompactCollector::MarkRootsFromConservativeStack(), v8::internal::IncrementalMarking::OldGenerationSizeOfObjects(), v8::internal::Heap::PerformGarbageCollection(), v8::internal::MarkCompactCollector::PinPreciseRootsIfNeeded(), v8::Shell::QuitOnce(), v8::internal::MarkCompactCollector::RecordSlot(), v8::internal::PagedSpaceAllocatorPolicy::RefillLab(), v8::internal::IsolateGroup::RemoveIsolate(), v8::internal::Sweeper::MajorSweeperJob::Run(), v8::internal::Sweeper::MinorSweeperJob::Run(), v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::Run(), v8::internal::SafepointScope::SafepointScope(), v8::internal::LocalHeap::SetUpSharedMarking(), v8::internal::Heap::SetUpSpaces(), v8::internal::WriteBarrier::SharedMarkingFromCode(), and v8::internal::MarkCompactCollector::UpdatePointersInClientHeaps().
is_short_builtin_calls_enabled()
bool v8::internal::Isolate::is_short_builtin_calls_enabled () const [inline]
Definition at line 1966 of file isolate.h.
                                              {
    return V8_SHORT_BUILTIN_CALLS_BOOL && is_short_builtin_calls_enabled_;
  }
References V8_SHORT_BUILTIN_CALLS_BOOL.
Referenced by v8::internal::baseline::anonymous_namespace{baseline-compiler.cc}::BaselineAssemblerOptions(), v8::internal::AssemblerOptions::Default(), v8::internal::EmbeddedData::FromBlobForPc(), MaybeRemapEmbeddedBuiltinsIntoCodeRange(), v8::internal::OffHeapInstructionStream::PcIsOffHeap(), TearDownEmbeddedBlob(), v8::internal::OffHeapInstructionStream::TryGetAddressForHashing(), and v8::internal::OffHeapInstructionStream::TryLookupCode().
IsArrayOrObjectOrStringPrototype()
Isolate::KnownPrototype v8::internal::Isolate::IsArrayOrObjectOrStringPrototype (Tagged< JSObject > object)
Definition at line 6324 of file isolate.cc.
                             {
  Tagged<Map> metamap = object->map(this)->map(this);
  Tagged<NativeContext> native_context = metamap->native_context();
  if (native_context->initial_object_prototype() == object) {
    return KnownPrototype::kObject;
  } else if (native_context->initial_array_prototype() == object) {
    return KnownPrototype::kArray;
  } else if (native_context->initial_string_prototype() == object) {
    return KnownPrototype::kString;
  }
  return KnownPrototype::kNone;
}
References kArray, kNone, kObject, kString, and native_context().
Referenced by UpdateNoElementsProtectorOnSetElement().
IsBuiltinTableHandleLocation()
bool v8::internal::Isolate::IsBuiltinTableHandleLocation (Address * handle_location)
Definition at line 3851 of file isolate.cc.
                                                                   {
  FullObjectSlot location(handle_location);
  FullObjectSlot first_root(builtin_table());
  FullObjectSlot last_root(first_root + Builtins::kBuiltinCount);
  if (location >= last_root) return false;
  if (location < first_root) return false;
  return true;
}
References builtin_table(), and v8::internal::Builtins::kBuiltinCount.
Referenced by v8::internal::compiler::JSHeapBroker::IsCanonicalHandle().
IsCompileHintsMagicEnabled()
bool v8::internal::Isolate::IsCompileHintsMagicEnabled (Handle< NativeContext > context)
IsCurrent()
bool v8::internal::Isolate::IsCurrent () const [inline]
Definition at line 41 of file isolate-inl.h.
{ return this == TryGetCurrent(); }
IsDead()
bool v8::internal::Isolate::IsDead () const [inline]
Definition at line 1583 of file isolate.h.
{ return has_fatal_error_; }
Referenced by v8::Isolate::IsDead().
IsFrozen()
bool v8::internal::Isolate::IsFrozen () const [inline]
Definition at line 2454 of file isolate.h.
{ return is_frozen_; }
IsGeneratingEmbeddedBuiltins()
bool v8::internal::Isolate::IsGeneratingEmbeddedBuiltins () const [inline]
Definition at line 1937 of file isolate.h.
                                            {
    return builtins_constants_table_builder() != nullptr;
  }
Referenced by v8::internal::BuiltinsConstantsTableBuilder::AddObject(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuiltinAssemblerOptions(), v8::internal::anonymous_namespace{constants-table-builder.cc}::CheckPreconditionsForPatching(), v8::internal::AssemblerOptions::Default(), v8::internal::BuiltinsConstantsTableBuilder::Finalize(), v8::internal::OptimizingCompileOutputQueue::InstallGeneratedBuiltins(), and v8::internal::compiler::BasicBlockInstrumentor::Instrument().
IsInCreationContext()
bool v8::internal::Isolate::IsInCreationContext (Tagged< JSObject > object, uint32_t index)
Definition at line 6338 of file isolate.cc.
                                                                         {
  DisallowGarbageCollection no_gc;
  Tagged<Map> metamap = object->map(this)->map(this);
  // Filter out native-context independent objects.
  if (metamap == ReadOnlyRoots(this).meta_map()) return false;
  Tagged<NativeContext> native_context = metamap->native_context();
  return native_context->GetNoCell(index) == object;
}
References v8::internal::index, native_context(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::anonymous_namespace{ic.cc}::AllowConvertHoleElementToUndefined(), v8::internal::LookupIterator::InternalUpdateProtector(), v8::internal::compiler::JSHeapBroker::IsArrayOrObjectPrototype(), and IsInitialArrayPrototype().
IsInitialArrayPrototype()
bool v8::internal::Isolate::IsInitialArrayPrototype (Tagged< JSArray > array) [inline]
Definition at line 228 of file isolate-inl.h.
                                                           {
  DisallowGarbageCollection no_gc;
  return IsInCreationContext(array, Context::INITIAL_ARRAY_PROTOTYPE_INDEX);
}
References IsInCreationContext(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::anonymous_namespace{builtins-array.cc}::IsJSArrayWithAddableFastElements().
IsInUse()
bool v8::internal::Isolate::IsInUse () [inline]
Definition at line 715 of file isolate.h.
{ return entry_stack_ != nullptr; }
Referenced by v8::Isolate::Deinitialize(), v8::Isolate::Dispose(), and v8::Isolate::IsInUse().
IsJSApiWrapperNativeError()
bool v8::internal::Isolate::IsJSApiWrapperNativeError (DirectHandle< JSReceiver > obj)
Definition at line 6877 of file isolate.cc.
                                                                    {
  return is_js_api_wrapper_native_error_callback_ != nullptr &&
         is_js_api_wrapper_native_error_callback_(
             reinterpret_cast<v8::Isolate*>(this), Utils::ToLocal(obj));
}
IsLoggingCodeCreation()
bool v8::internal::Isolate::IsLoggingCodeCreation () const
Definition at line 6238 of file isolate.cc.
                                          {
  return v8_file_logger()->is_listening_to_code_events() || is_profiling() ||
         v8_flags.log_function_events ||
         logger()->is_listening_to_code_events();
}
References v8::internal::Logger::is_listening_to_code_events(), v8::internal::V8FileLogger::is_listening_to_code_events(), is_profiling(), logger(), v8_file_logger(), and v8::internal::v8_flags.
Referenced by v8::internal::Builtins::EmitCodeCreateEvents(), v8::internal::wasm::JSToWasmWrapperCompilationUnit::Finalize(), v8::internal::anonymous_namespace{code-serializer.cc}::FinalizeDeserialization(), v8::internal::Compiler::LogFunctionCompilation(), v8::internal::wasm::WasmCode::ShouldBeLogged(), and UpdateLogObjectRelocation().
isolate_data() [1/2]
IsolateData* v8::internal::Isolate::isolate_data () [inline]
Definition at line 1223 of file isolate.h.
{ return &isolate_data_; }
isolate_data() [2/2]
const IsolateData* v8::internal::Isolate::isolate_data () const [inline]
Definition at line 1222 of file isolate.h.
{ return &isolate_data_; }
Referenced by v8::Isolate::GetContinuationPreservedEmbedderData(), v8::Isolate::GetContinuationPreservedEmbedderDataV2(), v8::internal::TickSample::GetStackSample(), v8::internal::wasm::grow_stack(), IncreaseDateCacheStampAndInvalidateProtector(), v8::internal::WriteBarrier::IndirectPointerMarkingFromCode(), InFastCCall(), Init(), v8::internal::Builtins::InitializeIsolateDataTables(), v8::internal::anonymous_namespace{execution.cc}::Invoke(), v8::internal::InvokeAccessorGetterCallback(), v8::internal::Heap::IsMarkingFlagAddress(), v8::internal::Heap::IsMinorMarkingFlagAddress(), v8::internal::wasm::load_old_fp(), v8::internal::Heap::NewSpaceAllocationLimitAddress(), v8::internal::Heap::NewSpaceAllocationTopAddress(), v8::internal::StackFrameIterator::Reset(), v8::internal::wasm::return_switch(), v8::internal::MicrotaskQueue::RunMicrotasks(), v8::internal::RUNTIME_FUNCTION(), v8::Isolate::SetContinuationPreservedEmbedderData(), v8::Isolate::SetContinuationPreservedEmbedderDataV2(), v8::internal::Heap::SetIsMarkingFlag(), v8::internal::Heap::SetIsMinorMarkingFlag(), v8::internal::wasm::shrink_stack(), v8::internal::StackFrameIteratorForProfiler::StackFrameIteratorForProfiler(), v8::internal::wasm::switch_from_the_central_stack_for_js(), v8::internal::wasm::switch_stacks(), v8::internal::wasm::switch_to_the_central_stack_for_js(), UnwindAndFindHandler(), and v8::internal::SemiSpace::~SemiSpace().
isolate_group()
IsolateGroup* v8::internal::Isolate::isolate_group () const [inline]
Definition at line 1245 of file isolate.h.
{ return isolate_group_; }
Referenced by v8::internal::IsolateGroup::AddIsolate(), v8::internal::BackingStore::Allocate(), v8::internal::ConcurrentUnifiedHeapMarkingVisitor::ConcurrentUnifiedHeapMarkingVisitor(), v8::internal::ReadOnlyHeap::CreateInitialHeapForBootstrapping(), Deinit(), Deinitialize(), v8::internal::ETWJITInterface::EventHandler(), v8::Isolate::GetGroup(), Init(), v8::internal::ReadOnlyHeap::InitFromIsolate(), v8::internal::ReadOnlyArtifacts::Initialize(), InitializeIsShortBuiltinCallsEnabled(), v8::internal::MemoryAllocator::MemoryAllocator(), page_allocator(), v8::internal::PagePool::ReleaseOnTearDown(), SetIsolateThreadLocals(), v8::internal::ReadOnlyHeap::SetUp(), v8::internal::Heap::SetUp(), v8::internal::IsolateGroup::SetupReadOnlyHeap(), and v8::internal::BackingStore::TryAllocateAndPartiallyCommitMemory().
isolate_root()
Address v8::internal::Isolate::isolate_root () const [inline]
Definition at line 1257 of file isolate.h.
{ return isolate_data()->isolate_root(); }
Referenced by v8::internal::compiler::WasmGraphBuilder::BuildLoadIsolateRoot(), v8::internal::wasm::WasmInterpreterRuntime::CallWasmToJSBuiltin(), and v8::internal::MacroAssemblerBase::RootRegisterOffsetForExternalReference().
isolate_root_bias()
constexpr static size_t v8::internal::Isolate::isolate_root_bias () [inline], [static], [constexpr]
Definition at line 1258 of file isolate.h.
                                              {
    return OFFSET_OF(Isolate, isolate_data_) + IsolateData::kIsolateRootBias;
  }
References v8::internal::IsolateData::kIsolateRootBias, and OFFSET_OF.
IsOnCentralStack() [1/2]
bool v8::internal::Isolate::IsOnCentralStack () [inline]
Definition at line 2385 of file isolate.h.
{ return true; }
Referenced by v8::internal::Heap::CollectGarbage(), v8::internal::wasm::grow_stack(), v8::internal::RUNTIME_FUNCTION(), Throw(), and UnwindAndFindHandler().
IsOnCentralStack() [2/2]
bool v8::internal::Isolate::IsOnCentralStack (Address addr) [inline], [private]
Definition at line 2570 of file isolate.h.
{ return true; }
IsSharedArrayBufferConstructorEnabled()
bool v8::internal::Isolate::IsSharedArrayBufferConstructorEnabled (DirectHandle< NativeContext > context)
Definition at line 3714 of file isolate.cc.
                                         {
  if (!v8_flags.enable_sharedarraybuffer_per_context) return true;
  if (sharedarraybuffer_constructor_enabled_callback()) {
    v8::Local<v8::Context> api_context = v8::Utils::ToLocal(context);
    return sharedarraybuffer_constructor_enabled_callback()(api_context);
  }
  return false;
}
References context(), and v8::internal::v8_flags.
Referenced by InstallConditionalFeatures().
IsWasmImportedStringsEnabled()
bool v8::internal::Isolate::IsWasmImportedStringsEnabled (DirectHandle< NativeContext > context)
Definition at line 3768 of file isolate.cc.
                                         {
#ifdef V8_ENABLE_WEBASSEMBLY
  v8::WasmImportedStringsEnabledCallback callback =
      wasm_imported_strings_enabled_callback();
  if (callback) {
    v8::Local<v8::Context> api_context = v8::Utils::ToLocal(context);
    if (callback(api_context)) return true;
  }
  return v8_flags.experimental_wasm_imported_strings;
#else
  return false;
#endif
}
References context(), and v8::internal::v8_flags.
Referenced by v8::internal::wasm::WasmEnabledFeatures::FromContext().
IsWasmJSPIEnabled()
bool v8::internal::Isolate::IsWasmJSPIEnabled (DirectHandle< NativeContext > context)
Definition at line 3759 of file isolate.cc.
                                                                   {
#ifdef V8_ENABLE_WEBASSEMBLY
  return IsWasmJSPIRequested(context) &&
         context->is_wasm_jspi_installed() != Smi::zero();
#else
  return false;
#endif
}
References context(), IsWasmJSPIRequested(), and v8::internal::Smi::zero().
Referenced by v8::internal::wasm::WasmEnabledFeatures::FromContext().
IsWasmJSPIRequested()
bool v8::internal::Isolate::IsWasmJSPIRequested (DirectHandle< NativeContext > context)
Definition at line 3742 of file isolate.cc.
                                                                     {
#ifdef V8_ENABLE_WEBASSEMBLY
  if (v8_flags.wasm_jitless) return false;
  v8::WasmJSPIEnabledCallback jspi_callback = wasm_jspi_enabled_callback();
  if (jspi_callback) {
    v8::Local<v8::Context> api_context = v8::Utils::ToLocal(context);
    if (jspi_callback(api_context)) return true;
  }
  // Otherwise use the runtime flag.
  return v8_flags.experimental_wasm_jspi;
#else
  return false;
#endif
}
References context(), and v8::internal::v8_flags.
Referenced by v8::internal::WasmJs::InstallConditionalFeatures(), and IsWasmJSPIEnabled().
IsWasmStringRefEnabled()
bool v8::internal::Isolate::IsWasmStringRefEnabled (DirectHandle< NativeContext > context)
Definition at line 3725 of file isolate.cc.
                                                                        {
#ifdef V8_ENABLE_WEBASSEMBLY
  // If Wasm imported strings are explicitly enabled via a callback, also enable
  // stringref.
  v8::WasmImportedStringsEnabledCallback callback_imported_strings =
      wasm_imported_strings_enabled_callback();
  if (callback_imported_strings) {
    v8::Local<v8::Context> api_context = v8::Utils::ToLocal(context);
    if (callback_imported_strings(api_context)) return true;
  }
  // Otherwise use the runtime flag.
  return v8_flags.experimental_wasm_stringref;
#else
  return false;
#endif
}
References context(), and v8::internal::v8_flags.
Referenced by v8::internal::wasm::WasmEnabledFeatures::FromContext().
Iterate() [1/3]
void v8::internal::Isolate::Iterate (RootVisitor * v)
Definition at line 659 of file isolate.cc.
                                    {
  ThreadLocalTop* current_t = thread_local_top();
  Iterate(v, current_t);
}
References thread_local_top().
Referenced by v8::internal::ThreadManager::Iterate(), Iterate(), and v8::internal::Heap::IterateStackRoots().
Iterate() [2/3]
char * v8::internal::Isolate::Iterate (RootVisitor * v, char * t)
Definition at line 600 of file isolate.cc.
                                                           {
  ThreadLocalTop* thread = reinterpret_cast<ThreadLocalTop*>(thread_storage);
  Iterate(v, thread);
  // Normally, ThreadLocalTop::topmost_script_having_context_ is visited weakly
  // but in order to simplify handling of frozen threads we just clear it.
  // Otherwise, we'd need to traverse the thread_storage again just to find this
  // one field.
  thread->topmost_script_having_context_ = Context();
  return thread_storage + sizeof(ThreadLocalTop);
}
References Iterate(), and v8::internal::ThreadLocalTop::topmost_script_having_context_.
Iterate() [3/3]
void v8::internal::Isolate::Iterate (RootVisitor * v, ThreadLocalTop * t)
Definition at line 616 of file isolate.cc.
                                                            {
  // Visit the roots from the top for a given thread.
  v->VisitRootPointer(Root::kStackRoots, nullptr,
                      FullObjectSlot(&thread->exception_));
  v->VisitRootPointer(Root::kStackRoots, nullptr,
                      FullObjectSlot(&thread->pending_message_));
  v->VisitRootPointer(Root::kStackRoots, nullptr,
                      FullObjectSlot(&thread->context_));
  for (v8::TryCatch* block = thread->try_catch_handler_; block != nullptr;
       block = block->next_) {
    // TODO(3770): Make TryCatch::exception_ an Address (and message_obj_ too).
    v->VisitRootPointer(
        Root::kStackRoots, nullptr,
        FullObjectSlot(reinterpret_cast<Address>(&(block->exception_))));
    v->VisitRootPointer(
        Root::kStackRoots, nullptr,
        FullObjectSlot(reinterpret_cast<Address>(&(block->message_obj_))));
  }
  v->VisitRootPointer(
      Root::kStackRoots, nullptr,
      FullObjectSlot(continuation_preserved_embedder_data_address()));
  // Iterate over pointers on native execution stack.
#if V8_ENABLE_WEBASSEMBLY
  wasm::WasmCodeRefScope wasm_code_ref_scope;
  for (const std::unique_ptr<wasm::StackMemory>& stack : wasm_stacks_) {
    if (stack->IsActive()) {
      continue;
    }
    stack->Iterate(v, this);
  }
  StackFrameIterator it(this, thread, StackFrameIterator::FirstStackOnly{});
#else
  StackFrameIterator it(this, thread);
#endif
  for (; !it.done(); it.Advance()) {
    it.frame()->Iterate(v);
  }
}
References v8::internal::ThreadLocalTop::context_, continuation_preserved_embedder_data_address(), v8::internal::ThreadLocalTop::exception_, v8::TryCatch::next_, v8::internal::ThreadLocalTop::pending_message_, v8::internal::stack, v8::internal::ThreadLocalTop::try_catch_handler_, and v8::internal::RootVisitor::VisitRootPointer().
IterateRegistersAndStackOfSimulator()
void v8::internal::Isolate::IterateRegistersAndStackOfSimulator (::heap::base::StackVisitor * visitor) [static]
Definition at line 3885 of file isolate.cc.
                                   {
  Isolate* isolate = Isolate::TryGetCurrent();
  if (!isolate) return;
  SimulatorStack::IterateRegistersAndStack(isolate, visitor);
}
References v8::internal::Factory::isolate(), v8::internal::SimulatorStack::IterateRegistersAndStack(), and v8::Isolate::TryGetCurrent().
Referenced by v8::internal::CppHeap::AttachIsolate(), and v8::internal::LocalHeap::LocalHeap().
IterateThread()
void v8::internal::Isolate::IterateThread (ThreadVisitor * v, char * t)
Definition at line 611 of file isolate.cc.
                                                     {
  ThreadLocalTop* thread = reinterpret_cast<ThreadLocalTop*>(t);
  v->VisitThread(this, thread);
}
References v8::internal::ThreadVisitor::VisitThread().
Referenced by v8::internal::ThreadManager::IterateArchivedThreads().
javascript_execution_assert_address()
Address v8::internal::Isolate::javascript_execution_assert_address () [inline]
Definition at line 1892 of file isolate.h.
                                                {
    return reinterpret_cast<Address>(&javascript_execution_assert_);
  }
jitless()
bool v8::internal::Isolate::jitless () const [inline]
Definition at line 1791 of file isolate.h.
{ return jitless_; }
Referenced by v8::internal::MemoryAllocator::PartialFreeMemory().
js_entry_sp()
Address v8::internal::Isolate::js_entry_sp () [inline]
Definition at line 946 of file isolate.h.
{ return thread_local_top()->js_entry_sp_; }
Referenced by v8::internal::TickSample::GetStackSample(), and SetIdle().
js_entry_sp_address()
Address* v8::internal::Isolate::js_entry_sp_address () [inline]
Definition at line 947 of file isolate.h.
                                        {
    return &thread_local_top()->js_entry_sp_;
  }
Referenced by v8::internal::wasm::WasmInterpreterRuntime::CallWasmToJSBuiltin().
jsregexp_canonrange()
unibrow::Mapping<unibrow::CanonicalizationRange>* v8::internal::Isolate::jsregexp_canonrange () [inline]
Definition at line 1446 of file isolate.h.
                                                                      {
    return &jsregexp_canonrange_;
  }
Referenced by v8::internal::CharacterRange::AddCaseEquivalents().
jsregexp_uncanonicalize()
unibrow::Mapping<unibrow::Ecma262UnCanonicalize>* v8::internal::Isolate::jsregexp_uncanonicalize () [inline]
Definition at line 1442 of file isolate.h.
                                                                          {
    return &jsregexp_uncanonicalize_;
  }
Referenced by v8::internal::CharacterRange::AddCaseEquivalents(), and v8::internal::anonymous_namespace{regexp-compiler.cc}::GetCaseIndependentLetters().
lazy_compile_dispatcher()
LazyCompileDispatcher* v8::internal::Isolate::lazy_compile_dispatcher () const [inline]
Definition at line 2021 of file isolate.h.
                                                         {
    return lazy_compile_dispatcher_.get();
  }
Referenced by v8::internal::Compiler::Compile().
load_from_stack_count_address()
Address v8::internal::Isolate::load_from_stack_count_address (const char * function_name) [static]
Definition at line 7658 of file isolate.cc.
                                                                        {
  DCHECK_NOT_NULL(function_name);
  if (!stack_access_count_map) {
    stack_access_count_map = new MapOfLoadsAndStoresPerFunction{};
  }
  auto& map = *stack_access_count_map;
  std::string name(function_name);
  // It is safe to return the address of std::map values.
  // Only iterators and references to the erased elements are invalidated.
  return reinterpret_cast<Address>(&map[name].first);
}
References DCHECK_NOT_NULL, v8::internal::name, v8::internal::anonymous_namespace{isolate.cc}::stack_access_count_map, and v8::internal::string.
Referenced by v8::internal::ExternalReference::address_of_load_from_stack_count().
load_stub_cache()
StubCache* v8::internal::Isolate::load_stub_cache () const [inline]
Definition at line 1327 of file isolate.h.
{ return load_stub_cache_; }
Referenced by v8::internal::ExternalReferenceTable::AddStubCache(), v8::internal::anonymous_namespace{heap.cc}::ClearStubCaches(), and v8::internal::IC::stub_cache().
LocalsBlockListCacheGet()
Tagged< Object > v8::internal::Isolate::LocalsBlockListCacheGet (DirectHandle< ScopeInfo > scope_info)
Definition at line 7718 of file isolate.cc.
                                        {
  DisallowGarbageCollection no_gc;
  if (!IsEphemeronHashTable(heap()->locals_block_list_cache())) {
    return ReadOnlyRoots(this).the_hole_value();
  }
  Tagged<Object> maybe_value =
      Cast<EphemeronHashTable>(heap()->locals_block_list_cache())
          ->Lookup(scope_info);
  if (IsTuple2(maybe_value)) return Cast<Tuple2>(maybe_value)->value2();
  CHECK(IsStringSet(maybe_value) || IsTheHole(maybe_value));
  return maybe_value;
}
References CHECK, heap(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::DebugEvaluate::ContextBuilder::ContextBuilder(), v8::internal::Context::Lookup(), and v8::internal::ScopeIterator::TryParseAndRetrieveScopes().
LocalsBlockListCacheRehash()
void v8::internal::Isolate::LocalsBlockListCacheRehash ()
Definition at line 7683 of file isolate.cc.
                                         {
  if (IsEphemeronHashTable(heap()->locals_block_list_cache())) {
    Tagged<EphemeronHashTable> cache =
        Cast<EphemeronHashTable>(heap()->locals_block_list_cache());
    cache->Rehash(this);
  }
}
References heap().
Referenced by v8::internal::LiveEdit::PatchScript().
LocalsBlockListCacheSet()
void v8::internal::Isolate::LocalsBlockListCacheSet (DirectHandle< ScopeInfo > scope_info, DirectHandle< ScopeInfo > outer_scope_info, DirectHandle< StringSet > locals_blocklist)
Definition at line 7690 of file isolate.cc.
                                              {
  Handle<EphemeronHashTable> cache;
  if (IsEphemeronHashTable(heap()->locals_block_list_cache())) {
    cache = handle(Cast<EphemeronHashTable>(heap()->locals_block_list_cache()),
                   this);
  } else {
    CHECK(IsUndefined(heap()->locals_block_list_cache()));
    constexpr int kInitialCapacity = 8;
    cache = EphemeronHashTable::New(this, kInitialCapacity);
  }
  DCHECK(IsEphemeronHashTable(*cache));
  DirectHandle<Object> value;
  if (!outer_scope_info.is_null()) {
    value = factory()->NewTuple2(outer_scope_info, locals_blocklist,
                                 AllocationType::kYoung);
  } else {
    value = locals_blocklist;
  }
  CHECK(!value.is_null());
  cache = EphemeronHashTable::Put(cache, scope_info, value);
  heap()->set_locals_block_list_cache(*cache);
}
References CHECK, v8::internal::DCHECK(), factory(), v8::internal::handle(), heap(), v8::internal::DirectHandle< T >::is_null(), v8::internal::kYoung, v8::internal::anonymous_namespace{intl-objects.cc}::New(), v8::internal::Factory::NewTuple2(), and v8::internal::value.
Referenced by v8::internal::anonymous_namespace{debug-scopes.cc}::LocalBlocklistsCollector::CollectAndStore(), v8::internal::DebugEvaluate::ContextBuilder::ContextBuilder(), and v8::internal::anonymous_namespace{debug-scopes.cc}::LocalBlocklistsCollector::StoreFunctionBlocklists().
log_object_relocation()
bool v8::internal::Isolate::log_object_relocation () const [inline]
Definition at line 2357 of file isolate.h.
{ return log_object_relocation_; }
Referenced by v8::internal::ScavengerCollector::CollectGarbage().
logger()
Logger* v8::internal::Isolate::logger () const [inline]
Definition at line 1534 of file isolate.h.
{ return logger_; }
Referenced by AllowsCodeCompaction(), v8::internal::CodeAddressMap::CodeAddressMap(), v8::internal::anonymous_namespace{compiler.cc}::FinalizeUnoptimizedCompilation(), IsLoggingCodeCreation(), v8::internal::V8FileLogger::LateSetup(), v8::internal::V8FileLogger::logger(), v8::internal::ProfilingScope::ProfilingScope(), v8::internal::anonymous_namespace{perfetto-logger.cc}::IsolateRegistry::Register(), v8::internal::V8FileLogger::SetUp(), v8::internal::ExternalLogEventListener::StartListening(), v8::internal::ExternalLogEventListener::StopListening(), v8::internal::anonymous_namespace{perfetto-logger.cc}::IsolateRegistry::Unregister(), v8::internal::CodeAddressMap::~CodeAddressMap(), and v8::internal::ProfilingScope::~ProfilingScope().
LookupOrAddExternallyCompiledFilename()
int v8::internal::Isolate::LookupOrAddExternallyCompiledFilename (const char * filename)
Definition at line 6883 of file isolate.cc.
                                                                       {
  if (embedded_file_writer_ != nullptr) {
    return embedded_file_writer_->LookupOrAddExternallyCompiledFilename(
        filename);
  }
  return 0;
}
References embedded_file_writer_, and v8::internal::EmbeddedFileWriterInterface::LookupOrAddExternallyCompiledFilename().
Referenced by v8::internal::compiler::RawMachineAssembler::SetCurrentExternalSourcePosition().
main_thread_local_heap()
LocalHeap * v8::internal::Isolate::main_thread_local_heap ()
Definition at line 7604 of file isolate.cc.
                                           {
  return main_thread_local_isolate()->heap();
}
References v8::internal::LocalIsolate::heap(), and main_thread_local_isolate().
Referenced by v8::internal::BackgroundMergeTask::CompleteMergeInForeground(), v8::internal::HandleScope::CreateHandle(), CurrentLocalHeap(), Deinit(), v8::internal::Parser::DoParseProgram(), v8::internal::GlobalSafepoint::EnterGlobalSafepointScope(), v8::internal::StackGuard::HandleInterrupts(), Init(), v8::internal::IsolateSafepoint::InitiateGlobalSafepointScope(), v8::internal::JsonParser< Char >::JsonParser(), v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::MaybeUnparkForPrint::MaybeUnparkForPrint(), v8::internal::RelocatingCharacterStream::RelocatingCharacterStream(), v8::Shell::RunMain(), SetIsolateThreadLocals(), v8::internal::JsonStringifier::SimplePropertyKeyCache::SimplePropertyKeyCache(), v8::internal::RelocatingCharacterStream::~RelocatingCharacterStream(), and v8::internal::JsonStringifier::SimplePropertyKeyCache::~SimplePropertyKeyCache().
main_thread_local_isolate()
LocalIsolate* v8::internal::Isolate::main_thread_local_isolate () [inline]
Definition at line 2223 of file isolate.h.
                                            {
    return main_thread_local_isolate_.get();
  }
Referenced by v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildWithMacroAssembler(), v8::internal::Compiler::CollectSourcePositions(), v8::internal::anonymous_namespace{compiler.cc}::CompileMaglev(), v8::internal::anonymous_namespace{compiler.cc}::CompileScriptOnBothBackgroundAndMainThread(), v8::internal::anonymous_namespace{compiler.cc}::CompileTurbofan_NotConcurrent(), v8::internal::ConsumedPreparseData::For(), v8::internal::maglev::MaglevCodeGenerator::Generate(), v8::internal::compiler::Pipeline::GenerateCodeForTesting(), v8::internal::Assembler::GetCode(), main_thread_local_heap(), v8::internal::parsing::ParseFunction(), v8::internal::parsing::ParseProgram(), v8::internal::compiler::CodeAssembler::BuiltinCompilationScheduler::QueueJob(), v8::Shell::QuitOnce(), v8::internal::MapUpdater::ReconfigureToDataField(), v8::internal::BackgroundCompileTask::RunOnMainThread(), v8::internal::Snapshot::SerializeDeserializeAndVerifyForTesting(), SetIsolateThreadLocals(), and v8::internal::OptimizingCompileDispatcher::WaitUntilCompilationJobsDone().
map_updater_access()
base::Mutex* v8::internal::Isolate::map_updater_access () [inline]
Definition at line 775 of file isolate.h.
{ return &map_updater_access_; }
Referenced by v8::internal::MapUpdater::CompleteInobjectSlackTracking(), v8::internal::MapUpdater::ReconfigureToDataField(), and v8::internal::MapUpdater::Update().
materialized_object_store()
MaterializedObjectStore* v8::internal::Isolate::materialized_object_store () const [inline]
Definition at line 1400 of file isolate.h.
                                                             {
    return materialized_object_store_;
  }
Referenced by v8::internal::Deoptimizer::MaterializeHeapObjects(), v8::internal::TranslatedState::StoreMaterializedValuesAndDeopt(), and v8::internal::TranslatedState::UpdateFromPreviouslyMaterializedObjects().
MayAccess()
bool v8::internal::Isolate::MayAccess (DirectHandle< NativeContext > accessing_context, DirectHandle< JSObject > receiver)
Definition at line 1824 of file isolate.cc.
                                                         {
  DCHECK(IsJSGlobalProxy(*receiver) || IsAccessCheckNeeded(*receiver));
  // Check for compatibility between the security tokens in the
  // current lexical context and the accessed object.
  // During bootstrapping, callback functions are not enabled yet.
  if (bootstrapper()->IsActive()) return true;
  {
    DisallowGarbageCollection no_gc;
    if (IsJSGlobalProxy(*receiver)) {
      std::optional<Tagged<Object>> receiver_context =
          Cast<JSGlobalProxy>(*receiver)->GetCreationContext();
      if (!receiver_context) return false;
      if (*receiver_context == *accessing_context) return true;
      if (Cast<Context>(*receiver_context)->security_token() ==
          accessing_context->security_token())
        return true;
    }
  }
  HandleScope scope(this);
  DirectHandle<Object> data;
  v8::AccessCheckCallback callback = nullptr;
  {
    DisallowGarbageCollection no_gc;
    Tagged<AccessCheckInfo> access_check_info =
        AccessCheckInfo::Get(this, receiver);
    if (access_check_info.is_null()) return false;
    Tagged<Object> fun_obj = access_check_info->callback();
    callback = v8::ToCData<v8::AccessCheckCallback, kApiAccessCheckCallbackTag>(
        this, fun_obj);
    data = direct_handle(access_check_info->data(), this);
  }
  {
    // Leaving JavaScript.
    VMState<EXTERNAL> state(this);
    return callback(v8::Utils::ToLocal(accessing_context),
                    v8::Utils::ToLocal(receiver), v8::Utils::ToLocal(data));
  }
}
References bootstrapper(), v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::AccessCheckInfo::Get(), v8::internal::Tagged< HeapObject >::is_null(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::Builtins::AllowDynamicFunction(), v8::internal::KeyAccumulator::CollectOwnKeys(), v8::internal::GetHomeObjectPrototype(), v8::internal::anonymous_namespace{builtins-api.cc}::HandleApiCallHelper(), v8::internal::LookupIterator::HasAccess(), v8::internal::PrototypeIterator::HasAccess(), v8::internal::JSObject::IsExtensible(), v8::internal::JSObject::PreventExtensions(), v8::internal::JSObject::PreventExtensionsWithTransition(), v8::internal::JSObject::SetPrototype(), and v8::internal::FastKeyAccumulator::TryPrototypeInfoCache().
MaybeInitializeVectorListFromHeap()
void v8::internal::Isolate::MaybeInitializeVectorListFromHeap ()
Definition at line 6267 of file isolate.cc.
                                                {
  if (!IsUndefined(heap()->feedback_vectors_for_profiling_tools(), this)) {
    // Already initialized, return early.
    DCHECK(IsArrayList(heap()->feedback_vectors_for_profiling_tools()));
    return;
  }
  // Collect existing feedback vectors.
  DirectHandleVector<FeedbackVector> vectors(this);
  {
    HeapObjectIterator heap_iterator(heap());
    for (Tagged<HeapObject> current_obj = heap_iterator.Next();
         !current_obj.is_null(); current_obj = heap_iterator.Next()) {
      if (!IsFeedbackVector(current_obj)) continue;
      Tagged<FeedbackVector> vector = Cast<FeedbackVector>(current_obj);
      Tagged<SharedFunctionInfo> shared = vector->shared_function_info();
      // No need to preserve the feedback vector for non-user-visible functions.
      if (!shared->IsSubjectToDebugging()) continue;
      vectors.emplace_back(vector, this);
    }
  }
  // Add collected feedback vectors to the root list lest we lose them to GC.
  DirectHandle<ArrayList> list =
      ArrayList::New(this, static_cast<int>(vectors.size()));
  for (const auto& vector : vectors) list = ArrayList::Add(this, list, vector);
  SetFeedbackVectorsForProfilingTools(*list);
}
References v8::internal::ArrayList::Add(), v8::internal::DCHECK(), v8::internal::DirectHandleVector< T >::emplace_back(), heap(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::ArrayList::New(), v8::internal::HeapObjectIterator::Next(), SetFeedbackVectorsForProfilingTools(), and v8::internal::DirectHandleVector< T >::size().
Referenced by v8::internal::Coverage::SelectMode().
MaybeRemapEmbeddedBuiltinsIntoCodeRange()
void v8::internal::Isolate::MaybeRemapEmbeddedBuiltinsIntoCodeRange () [private]
Definition at line 5268 of file isolate.cc.
                                                      {
  if (!is_short_builtin_calls_enabled() || !RequiresCodeRange()) {
    return;
  }
  if (V8_ENABLE_NEAR_CODE_RANGE_BOOL &&
      GetShortBuiltinsCallRegion().contains(heap_.code_region())) {
    // The embedded builtins are within the pc-relative reach from the code
    // range, so there's no need to remap embedded builtins.
    return;
  }
  CHECK_NOT_NULL(embedded_blob_code_);
  CHECK_NE(embedded_blob_code_size_, 0);
  DCHECK_NOT_NULL(heap_.code_range_);
  embedded_blob_code_ = heap_.code_range_->RemapEmbeddedBuiltins(
      this, embedded_blob_code_, embedded_blob_code_size_);
  CHECK_NOT_NULL(embedded_blob_code_);
  // The un-embedded code blob is already a part of the registered code range
  // so it's not necessary to register it again.
}
References CHECK_NE, CHECK_NOT_NULL, v8::internal::Heap::code_range_, v8::internal::Heap::code_region(), v8::base::contains(), DCHECK_NOT_NULL, embedded_blob_code_, embedded_blob_code_size_, GetShortBuiltinsCallRegion(), heap_, is_short_builtin_calls_enabled(), RequiresCodeRange(), and V8_ENABLE_NEAR_CODE_RANGE_BOOL.
Referenced by CreateAndSetEmbeddedBlob(), and Init().
MemorySaverModeEnabled()
bool v8::internal::Isolate::MemorySaverModeEnabled () [inline]
Definition at line 2158 of file isolate.h.
                                {
    if (v8_flags.optimize_for_size) {
      return true;
    }
    if (V8_UNLIKELY(v8_flags.memory_saver_mode.value().has_value())) {
      return *v8_flags.memory_saver_mode.value();
    }
    return V8_UNLIKELY(memory_saver_mode_enabled_);
  }
References v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::internal::GlobalHandles::PostGarbageCollectionProcessing(), v8::internal::SmiStringCache::Set(), v8::internal::DoubleStringCache::Set(), and v8::internal::Heap::ShouldOptimizeForMemoryUsage().
metrics_recorder()
const std::shared_ptr<metrics::Recorder>& v8::internal::Isolate::metrics_recorder () [inline]
Definition at line 1202 of file isolate.h.
                                                           {
    return metrics_recorder_;
  }
Referenced by v8::internal::wasm::InstanceBuilder::Build(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompileNativeModule(), v8::internal::wasm::DeserializeNativeModule(), v8::internal::wasm::AsyncCompileJob::FinishCompile(), v8::internal::anonymous_namespace{gc-tracer.cc}::FlushBatchedEvents(), v8::internal::wasm::AsyncStreamingProcessor::OnFinishedStream(), v8::internal::GCTracer::ReportFullCycleToRecorder(), v8::internal::GCTracer::ReportIncrementalMarkingStepToRecorder(), v8::internal::GCTracer::ReportIncrementalSweepingStepToRecorder(), v8::internal::GCTracer::ReportYoungCycleToRecorder(), v8::internal::wasm::AsyncCompileJob::PrepareAndStartCompile::RunInForeground(), v8::Isolate::SetMetricsRecorder(), v8::internal::wasm::AsyncCompileJob::Start(), v8::internal::wasm::WasmEngine::SyncCompile(), v8::internal::wasm::WasmEngine::SyncCompileTranslatedAsmJs(), and v8::internal::wasm::WasmEngine::SyncValidate().
native_context()
Handle< NativeContext > v8::internal::Isolate::native_context () [inline]
Definition at line 48 of file isolate-inl.h.
                                              {
  DCHECK(!context().is_null());
  return handle(context()->native_context(), this);
}
References context(), v8::internal::DCHECK(), and v8::internal::handle().
Referenced by v8::internal::anonymous_namespace{js-atomics-synchronization.cc}::AddPromiseToNativeContext(), v8::internal::Object::ArraySpeciesConstructor(), v8::internal::Map::AsLanguageMode(), v8::internal::wasm::WasmEngine::AsyncCompile(), v8::internal::detail::AsyncWaiterQueueNode< T >::AsyncWaiterQueueNode(), v8::UnboundScript::BindToCurrentContext(), v8::internal::BUILTIN(), v8::internal::Debug::CheckBreakPoint(), v8::internal::JSDisposableStackBase::CheckValueAndGetDisposeMethod(), v8::internal::CloneObjectSlowPath(), v8::internal::KeyAccumulator::CollectOwnKeys(), v8::internal::CompileGlobalEval(), v8::debug::CompileInspectorScript(), v8::internal::anonymous_namespace{compiler.cc}::CompileToplevel(), v8::internal::anonymous_namespace{js-locale.cc}::Construct(), v8::Isolate::ContextDisposedNotification(), CountUsage(), v8::internal::JSSegments::Create(), v8::internal::JSSegmentIterator::Create(), v8::internal::anonymous_namespace{bootstrapper.cc}::CreateFunctionForBuiltin(), v8::internal::anonymous_namespace{bootstrapper.cc}::CreateFunctionForBuiltinWithoutPrototype(), v8::internal::anonymous_namespace{bootstrapper.cc}::CreateFunctionForBuiltinWithPrototype(), v8::internal::wasm::CreateFunctionForCompileTimeImport(), v8::internal::anonymous_namespace{bootstrapper.cc}::CreateLiteralObjectMapFromCache(), v8::internal::anonymous_namespace{runtime-literals.cc}::CreateObjectLiteral(), v8::internal::JSSegments::CreateSegmentDataObject(), v8::internal::anonymous_namespace{bootstrapper.cc}::CreateSharedObjectConstructor(), v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::CreateWasmScript(), v8::internal::wasm::DeserializeNativeModule(), v8::Isolate::EnqueueMicrotask(), v8::internal::MicrotaskQueue::EnqueueMicrotask(), v8::internal::SyntheticModule::Evaluate(), v8::debug::EvaluateGlobal(), v8::internal::SourceTextModule::ExecuteAsyncModule(), v8::internal::SourceTextModule::ExecuteModule(), v8::internal::SourceTextModule::FinishInstantiate(), v8::internal::wasm::WasmEnabledFeatures::FromIsolate(), v8::debug::GetBuiltin(), v8::internal::anonymous_namespace{gc-tracer.cc}::GetContextId(), v8::internal::wasm::GetExports(), v8::FunctionTemplate::GetFunction(), v8::internal::GetHomeObjectPrototype(), v8::internal::wasm::GetImports(), GetIncumbentContextSlow(), v8::internal::anonymous_namespace{api-natives.cc}::GetIntrinsic(), v8::internal::Map::GetObjectCreateMap(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::GetOrCreateDebugMaps(), v8::internal::DebugEvaluate::Global(), v8::internal::anonymous_namespace{builtins-api.cc}::HandleApiCallHelper(), v8::internal::wasm::WasmInterpreterRuntime::HandleException(), v8::internal::LookupIterator::HasAccess(), v8::internal::PrototypeIterator::HasAccess(), v8::internal::Genesis::InitializeCallSiteBuiltins(), v8::internal::Genesis::InitializeConsole(), v8::internal::Genesis::InitializeIteratorFunctions(), v8::internal::JSDataObjectBuilder::InitializeMapFromZero(), v8::internal::anonymous_namespace{handler-configuration.cc}::InitPrototypeChecksImpl(), v8::internal::SourceTextModule::InnerExecuteAsyncModule(), v8::internal::InstallError(), v8::internal::InstallWithIntrinsicDefaultProto(), v8::internal::anonymous_namespace{api-natives.cc}::InstantiateObject(), v8::internal::wasm::InstantiateToInstanceObject(), v8::internal::anonymous_namespace{execution.cc}::Invoke(), IsArrayOrObjectOrStringPrototype(), v8::internal::JSObject::IsExtensible(), IsInCreationContext(), v8::internal::anonymous_namespace{builtins-array.cc}::IsSimpleArray(), v8::internal::DebugEvaluate::Local(), v8::internal::wasm::JSPrototypesSetup::MakeConstructor(), v8::internal::WasmTrustedInstanceData::New(), v8::internal::WasmCapiFunction::New(), v8::internal::WasmJSFunction::New(), v8::internal::WasmTagObject::New(), v8::internal::WasmMemoryObject::New(), v8::internal::WasmSuspendingObject::New(), v8::internal::WasmDescriptorOptions::New(), v8::internal::WasmExceptionPackage::New(), v8::internal::WasmExportedFunction::New(), v8::internal::WasmGlobalObject::New(), v8::internal::WasmTableObject::New(), v8::internal::WasmMemoryMapDescriptor::NewFromAnonymous(), v8::internal::WasmMemoryMapDescriptor::NewFromFileDescriptor(), v8::internal::Factory::NewFunctionForTesting(), v8::internal::Factory::NewJSArrayForTemplateLiteralArray(), v8::internal::Factory::NewJSDisposableStackBase(), v8::internal::anonymous_namespace{runtime-scopes.cc}::NewSloppyArguments(), v8::internal::JSSegmentIterator::Next(), v8::internal::JSAsyncDisposableStack::NextDisposeAsyncIteration(), v8::internal::Debug::OnDebugBreak(), v8::internal::Debug::OnException(), v8::internal::Debug::OnInstrumentationBreak(), v8::internal::JSObject::PreventExtensions(), v8::internal::JSObject::PreventExtensionsWithTransition(), v8::internal::Debug::ProcessCompileEvent(), v8::internal::wasm::InstanceBuilder::ProcessExports(), v8::internal::anonymous_namespace{js-atomics-synchronization.cc}::RemovePromiseFromNativeContext(), v8::internal::JSPromise::Resolve(), RunAllPromiseHooks(), RunHostCreateShadowRealmContextCallback(), RunHostImportModuleDynamicallyCallback(), RunHostInitializeImportMetaObjectCallback(), v8::internal::SourceTextModule::RunInitializationCode(), v8::internal::anonymous_namespace{js-atomics-synchronization.cc}::SetAsyncUnlockHandlers(), v8::internal::RegExp::SetLastMatchInfo(), v8::Context::SetPromiseHooks(), v8::internal::JSObject::SetPrototype(), v8::internal::Debug::StartSideEffectCheckMode(), v8::internal::Debug::StopSideEffectCheckMode(), v8::internal::wasm::WasmEngine::SyncCompile(), v8::internal::wasm::WasmEngine::SyncValidate(), v8::internal::Object::ToObjectImpl(), v8::internal::Script::TraceScriptRundown(), v8::internal::JSPromise::TriggerPromiseReactions(), v8::internal::FastKeyAccumulator::TryPrototypeInfoCache(), v8::internal::FutexEmulation::WaitAsync(), and v8::internal::JSAtomicsCondition::WaitAsync().
NeedsDetailedOptimizedCodeLineInfo()
bool v8::internal::Isolate::NeedsDetailedOptimizedCodeLineInfo () const
Definition at line 6234 of file isolate.cc.
                                                       {
  return NeedsSourcePositions() || detailed_source_positions_for_profiling();
}
References detailed_source_positions_for_profiling(), and NeedsSourcePositions().
Referenced by v8::internal::maglev::MaglevCompilationInfo::MaglevCompilationInfo(), v8::internal::OptimizedCompilationInfo::OptimizedCompilationInfo(), and v8::internal::UnoptimizedCompileFlags::UnoptimizedCompileFlags().
NeedsSourcePositions()
bool v8::internal::Isolate::NeedsSourcePositions () const
Definition at line 6248 of file isolate.cc.
                                         {
  return
      // Static conditions.
      v8_flags.trace_deopt || v8_flags.trace_turbo ||
      v8_flags.trace_turbo_graph || v8_flags.turbo_profiling ||
      v8_flags.print_maglev_code || v8_flags.perf_prof || v8_flags.log_maps ||
      v8_flags.log_ic || v8_flags.log_function_events ||
      v8_flags.heap_snapshot_on_oom ||
      // Dynamic conditions; changing any of these conditions triggers source
      // position collection for the entire heap
      // (CollectSourcePositionsForAllBytecodeArrays).
      is_profiling() || debug_->is_active() || v8_file_logger_->is_logging();
}
References debug_, v8::internal::Debug::is_active(), v8::internal::V8FileLogger::is_logging(), is_profiling(), v8_file_logger_, and v8::internal::v8_flags.
Referenced by v8::internal::BackgroundMergeTask::CompleteMergeInForeground(), v8::internal::anonymous_namespace{code-serializer.cc}::CreateInterpreterDataForDeserializedCode(), v8::internal::anonymous_namespace{code-serializer.cc}::FinalizeDeserialization(), v8::internal::anonymous_namespace{compiler.cc}::FinalizeUnoptimizedCompilation(), v8::internal::anonymous_namespace{compiler.cc}::FinalizeUnoptimizedScriptCompilation(), NeedsDetailedOptimizedCodeLineInfo(), and v8::internal::Script::SetSource().
New() [1/2]
Isolate * v8::internal::Isolate::New () [static]
Definition at line 4163 of file isolate.cc.
{ return New(IsolateGroup::AcquireDefault()); }
References v8::internal::IsolateGroup::AcquireDefault().
Referenced by v8::Isolate::Allocate(), and v8::internal::Snapshot::SerializeDeserializeAndVerifyForTesting().
New() [2/2]
Isolate * v8::internal::Isolate::New (IsolateGroup * isolate_group) [static]
Definition at line 4166 of file isolate.cc.
{ return Allocate(group); }
References Allocate().
NewPersistentHandles()
std::unique_ptr< PersistentHandles > v8::internal::Isolate::NewPersistentHandles ()
Definition at line 6075 of file isolate.cc.
                                                               {
  return std::make_unique<PersistentHandles>(this);
}
Referenced by v8::internal::baseline::BaselineBatchCompilerJob::BaselineBatchCompilerJob(), and v8::internal::LocalHeap::EnsurePersistentHandles().
next_unique_sfi_id()
uint32_t v8::internal::Isolate::next_unique_sfi_id () const [inline]
Definition at line 1860 of file isolate.h.
                                      {
    return next_unique_sfi_id_.load(std::memory_order_relaxed);
  }
Referenced by v8::internal::ReadOnlyHeap::SetUp().
NextModuleAsyncEvaluationOrdinal()
unsigned v8::internal::Isolate::NextModuleAsyncEvaluationOrdinal () [inline]
Definition at line 1822 of file isolate.h.
                                              {
    // For simplicity, V8 allows this ordinal to overflow. Overflow will result
    // in incorrect module loading behavior for module graphs with top-level
    // await.
    return next_module_async_evaluation_ordinal_++;
  }
Referenced by v8::internal::SourceTextModule::InnerModuleEvaluation().
NextOptimizationId()
int v8::internal::Isolate::NextOptimizationId () [inline]
Definition at line 1804 of file isolate.h.
                           {
    int id = next_optimization_id_.load();
    while (true) {
      int next_id = id + 1;
      if (!Smi::IsValid(next_id)) next_id = 0;
      if (next_optimization_id_.compare_exchange_strong(id, next_id)) {
        return id;
      }
    }
  }
References v8::internal::Smi::IsValid().
NotifyExceptionPropagationCallback()
void v8::internal::Isolate::NotifyExceptionPropagationCallback () [private]
Definition at line 4903 of file isolate.cc.
                                                 {
  DCHECK_NOT_NULL(exception_propagation_callback_);
  // Try to figure out whether the exception was thrown directly from an
  // Api callback and if it's the case then call the
  // |exception_propagation_callback_| with relevant data.
  ExternalCallbackScope* ext_callback_scope = external_callback_scope();
  StackFrameIterator it(this);
  if (it.done() && !ext_callback_scope) {
    // The exception was thrown directly by embedder code without crossing
    // "C++ -> JS" or "C++ -> Api callback" boundary.
    return;
  }
  if (it.done() ||
      (ext_callback_scope &&
       ext_callback_scope->JSStackComparableAddress() < it.frame()->fp())) {
    // There were no crossings of "C++ -> JS" boundary at all or they happened
    // earlier than the last crossing of the "C++ -> Api callback" boundary.
    // In this case all the data about Api callback is available in the
    // |ext_callback_scope| object.
    DCHECK_NOT_NULL(ext_callback_scope);
    v8::ExceptionContext kind = ext_callback_scope->exception_context();
    switch (kind) {
      case v8::ExceptionContext::kConstructor:
      case v8::ExceptionContext::kOperation: {
        DCHECK_NOT_NULL(ext_callback_scope->callback_info());
        auto callback_info =
            reinterpret_cast<const v8::FunctionCallbackInfo<v8::Value>*>(
                ext_callback_scope->callback_info());
        DirectHandle<JSReceiver> receiver =
            Utils::OpenDirectHandle(*callback_info->This());
        DirectHandle<FunctionTemplateInfo> function_template_info(
            GetTargetFunctionTemplateInfo(*callback_info), this);
        ReportExceptionFunctionCallback(receiver, function_template_info, kind);
        return;
      }
      case v8::ExceptionContext::kAttributeGet:
      case v8::ExceptionContext::kAttributeSet:
      case v8::ExceptionContext::kIndexedQuery:
      case v8::ExceptionContext::kIndexedGetter:
      case v8::ExceptionContext::kIndexedDescriptor:
      case v8::ExceptionContext::kIndexedSetter:
      case v8::ExceptionContext::kIndexedDefiner:
      case v8::ExceptionContext::kIndexedDeleter:
      case v8::ExceptionContext::kNamedQuery:
      case v8::ExceptionContext::kNamedGetter:
      case v8::ExceptionContext::kNamedDescriptor:
      case v8::ExceptionContext::kNamedSetter:
      case v8::ExceptionContext::kNamedDefiner:
      case v8::ExceptionContext::kNamedDeleter:
      case v8::ExceptionContext::kNamedEnumerator: {
        DCHECK_NOT_NULL(ext_callback_scope->callback_info());
        auto callback_info =
            reinterpret_cast<const v8::PropertyCallbackInfo<v8::Value>*>(
                ext_callback_scope->callback_info());
        // Allow usages of v8::PropertyCallbackInfo<T>::Holder() for now.
        // TODO(https://crbug.com/333672197): remove.
        START_ALLOW_USE_DEPRECATED()
        DirectHandle<Object> holder =
            Utils::OpenDirectHandle(*callback_info->Holder());
        Handle<Object> maybe_name =
            PropertyCallbackArguments::GetPropertyKeyHandle(*callback_info);
        DirectHandle<Name> name =
            IsSmi(*maybe_name)
                ? factory()->SizeToString(
                      PropertyCallbackArguments::GetPropertyIndex(
                          *callback_info))
                : Cast<Name>(maybe_name);
        DCHECK(IsJSReceiver(*holder));
        // Allow usages of v8::PropertyCallbackInfo<T>::Holder() for now.
        // TODO(https://crbug.com/333672197): remove.
        END_ALLOW_USE_DEPRECATED()
        // Currently we call only ApiGetters from JS code.
        ReportExceptionPropertyCallback(Cast<JSReceiver>(holder), name, kind);
        return;
      }
      case v8::ExceptionContext::kUnknown:
        DCHECK_WITH_MSG(kind != v8::ExceptionContext::kUnknown,
                        "ExternalCallbackScope should not use "
                        "v8::ExceptionContext::kUnknown exception context");
        return;
    }
    UNREACHABLE();
  }
  // There were no crossings of "C++ -> Api callback" boundary or they
  // happened before crossing the "C++ -> JS" boundary.
  // In this case all the data about Api callback is available in the
  // topmost "JS -> Api callback" frame (ApiCallbackExitFrame or
  // ApiAccessorExitFrame).
  DCHECK(!it.done());
  StackFrame::Type frame_type = it.frame()->type();
  switch (frame_type) {
    case StackFrame::API_CALLBACK_EXIT: {
      ApiCallbackExitFrame* frame = ApiCallbackExitFrame::cast(it.frame());
      DirectHandle<JSReceiver> receiver(Cast<JSReceiver>(frame->receiver()),
                                        this);
      DirectHandle<FunctionTemplateInfo> function_template_info =
          frame->GetFunctionTemplateInfo();
      v8::ExceptionContext callback_kind =
          frame->IsConstructor() ? v8::ExceptionContext::kConstructor
                                 : v8::ExceptionContext::kOperation;
      ReportExceptionFunctionCallback(receiver, function_template_info,
                                      callback_kind);
      return;
    }
    case StackFrame::API_ACCESSOR_EXIT: {
      ApiAccessorExitFrame* frame = ApiAccessorExitFrame::cast(it.frame());
      DirectHandle<Object> holder(frame->holder(), this);
      DirectHandle<Name> name(frame->property_name(), this);
      DCHECK(IsJSReceiver(*holder));
      // Currently we call only ApiGetters from JS code.
      ReportExceptionPropertyCallback(Cast<JSReceiver>(holder), name,
                                      v8::ExceptionContext::kAttributeGet);
      return;
    }
    case StackFrame::TURBOFAN_JS:
      // This must be a fast Api call.
      CHECK(it.frame()->InFastCCall());
      // TODO(ishell): support fast Api calls.
      return;
    case StackFrame::EXIT:
    case StackFrame::BUILTIN_EXIT:
      // This is a regular runtime function or C++ builtin.
      return;
#if V8_ENABLE_WEBASSEMBLY
    case StackFrame::WASM:
    case StackFrame::WASM_SEGMENT_START:
      // No more info.
      return;
#endif // V8_ENABLE_WEBASSEMBLY
    default:
      // Other types are not expected, so just hard-crash.
      CHECK_NE(frame_type, frame_type);
  }
}
References v8::internal::ExternalCallbackScope::callback_info(), v8::internal::ApiCallbackExitFrame::cast(), v8::internal::ApiAccessorExitFrame::cast(), CHECK, CHECK_NE, v8::internal::DCHECK(), DCHECK_NOT_NULL, DCHECK_WITH_MSG, v8::internal::StackFrameIteratorBase::done(), END_ALLOW_USE_DEPRECATED, v8::internal::ExternalCallbackScope::exception_context(), factory(), v8::internal::StackFrame::fp(), v8::internal::StackFrameIterator::frame(), v8::internal::ApiCallbackExitFrame::GetFunctionTemplateInfo(), v8::internal::PropertyCallbackArguments::GetPropertyIndex(), v8::internal::PropertyCallbackArguments::GetPropertyKeyHandle(), v8::internal::anonymous_namespace{isolate.cc}::GetTargetFunctionTemplateInfo(), v8::internal::ApiAccessorExitFrame::holder(), v8::internal::StackFrame::InFastCCall(), v8::internal::ApiCallbackExitFrame::IsConstructor(), v8::internal::IsSmi(), v8::internal::ExternalCallbackScope::JSStackComparableAddress(), v8::kAttributeGet, v8::kAttributeSet, v8::kConstructor, v8::kIndexedDefiner, v8::kIndexedDeleter, v8::kIndexedDescriptor, v8::kIndexedGetter, v8::kIndexedQuery, v8::kIndexedSetter, v8::kNamedDefiner, v8::kNamedDeleter, v8::kNamedDescriptor, v8::kNamedEnumerator, v8::kNamedGetter, v8::kNamedQuery, v8::kNamedSetter, v8::kOperation, v8::kUnknown, v8::internal::name, v8::Utils::OpenDirectHandle(), v8::internal::ApiAccessorExitFrame::property_name(), v8::internal::ApiCallbackExitFrame::receiver(), ReportExceptionFunctionCallback(), ReportExceptionPropertyCallback(), v8::internal::Factory::SizeToString(), START_ALLOW_USE_DEPRECATED, v8::internal::StackFrame::type(), and v8::internal::UNREACHABLE().
Referenced by Throw().
OnAsyncFunctionSuspended()
void v8::internal::Isolate::OnAsyncFunctionSuspended (DirectHandle< JSPromise > promise, DirectHandle< JSPromise > parent)
Definition at line 7008 of file isolate.cc.
                                                                       {
  DCHECK(!promise->has_async_task_id());
  RunAllPromiseHooks(PromiseHookType::kInit, promise, parent);
  if (HasAsyncEventDelegate()) {
    DCHECK_NE(nullptr, async_event_delegate_);
    current_async_task_id_ =
        JSPromise::GetNextAsyncTaskId(current_async_task_id_);
    promise->set_async_task_id(current_async_task_id_);
    async_event_delegate_->AsyncEventOccurred(debug::kDebugAwait,
                                              promise->async_task_id(), false);
  }
}
References async_event_delegate_, v8::debug::AsyncEventDelegate::AsyncEventOccurred(), current_async_task_id_, v8::internal::DCHECK(), DCHECK_NE, v8::internal::JSPromise::GetNextAsyncTaskId(), HasAsyncEventDelegate(), v8::debug::kDebugAwait, v8::kInit, and RunAllPromiseHooks().
OnPromiseAfter()
void v8::internal::Isolate::OnPromiseAfter (DirectHandle< JSPromise > promise)
Definition at line 7074 of file isolate.cc.
                                                            {
  RunPromiseHook(PromiseHookType::kAfter, promise,
                 factory()->undefined_value());
  if (HasAsyncEventDelegate()) {
    if (promise->has_async_task_id()) {
      async_event_delegate_->AsyncEventOccurred(
          debug::kDebugDidHandle, promise->async_task_id(), false);
    }
  }
}
References async_event_delegate_, v8::debug::AsyncEventDelegate::AsyncEventOccurred(), factory(), HasAsyncEventDelegate(), v8::kAfter, v8::debug::kDebugDidHandle, and RunPromiseHook().
Referenced by OnTerminationDuringRunMicrotasks().
OnPromiseBefore()
void v8::internal::Isolate::OnPromiseBefore (DirectHandle< JSPromise > promise)
Definition at line 7063 of file isolate.cc.
                                                             {
  RunPromiseHook(PromiseHookType::kBefore, promise,
                 factory()->undefined_value());
  if (HasAsyncEventDelegate()) {
    if (promise->has_async_task_id()) {
      async_event_delegate_->AsyncEventOccurred(
          debug::kDebugWillHandle, promise->async_task_id(), false);
    }
  }
}
References async_event_delegate_, v8::debug::AsyncEventDelegate::AsyncEventOccurred(), factory(), HasAsyncEventDelegate(), v8::kBefore, v8::debug::kDebugWillHandle, and RunPromiseHook().
OnPromiseThen()
void v8::internal::Isolate::OnPromiseThen (DirectHandle< JSPromise > promise)
Definition at line 7022 of file isolate.cc.
                                                           {
  if (!HasAsyncEventDelegate()) return;
  Maybe<debug::DebugAsyncActionType> action_type =
      Nothing<debug::DebugAsyncActionType>();
  for (JavaScriptStackFrameIterator frame_it(this); !frame_it.done();
       frame_it.Advance()) {
    std::vector<Handle<SharedFunctionInfo>> infos;
    frame_it.frame()->GetFunctions(&infos);
    for (auto it = infos.rbegin(); it != infos.rend(); ++it) {
      DirectHandle<SharedFunctionInfo> info = *it;
      if (info->HasBuiltinId()) {
        // We should not report PromiseThen and PromiseCatch which is called
        // indirectly, e.g. Promise.all calls Promise.then internally.
        switch (info->builtin_id()) {
          case Builtin::kPromisePrototypeCatch:
            action_type = Just(debug::kDebugPromiseCatch);
            continue;
          case Builtin::kPromisePrototypeFinally:
            action_type = Just(debug::kDebugPromiseFinally);
            continue;
          case Builtin::kPromisePrototypeThen:
            action_type = Just(debug::kDebugPromiseThen);
            continue;
          default:
            return;
        }
      }
      if (info->IsUserJavaScript() && action_type.IsJust()) {
        DCHECK(!promise->has_async_task_id());
        current_async_task_id_ =
            JSPromise::GetNextAsyncTaskId(current_async_task_id_);
        promise->set_async_task_id(current_async_task_id_);
        async_event_delegate_->AsyncEventOccurred(action_type.FromJust(),
                                                  promise->async_task_id(),
                                                  debug()->IsBlackboxed(info));
      }
      return;
    }
  }
}
References async_event_delegate_, v8::debug::AsyncEventDelegate::AsyncEventOccurred(), current_async_task_id_, v8::internal::DCHECK(), debug(), v8::internal::JavaScriptStackFrameIterator::done(), v8::Maybe< T >::FromJust(), v8::internal::JSPromise::GetNextAsyncTaskId(), HasAsyncEventDelegate(), v8::Maybe< T >::IsJust(), v8::Just(), v8::debug::kDebugPromiseCatch, v8::debug::kDebugPromiseFinally, and v8::debug::kDebugPromiseThen.
OnStackTraceCaptured()
void v8::internal::Isolate::OnStackTraceCaptured (DirectHandle< StackTraceInfo > stack_trace)
Definition at line 7085 of file isolate.cc.
                                                                           {
  if (HasAsyncEventDelegate()) {
    async_event_delegate_->AsyncEventOccurred(debug::kDebugStackTraceCaptured,
                                              stack_trace->id(), false);
  }
}
References async_event_delegate_, v8::debug::AsyncEventDelegate::AsyncEventOccurred(), HasAsyncEventDelegate(), and v8::debug::kDebugStackTraceCaptured.
Referenced by CaptureAndSetErrorStack(), and CaptureDetailedStackTrace().
OnTerminationDuringRunMicrotasks()
void v8::internal::Isolate::OnTerminationDuringRunMicrotasks ()
Definition at line 7092 of file isolate.cc.
                                               {
  DCHECK(is_execution_terminating());
  // This performs cleanup for when RunMicrotasks (in
  // builtins-microtask-queue-gen.cc) is aborted via a termination exception.
  // This has to be kept in sync with the code in said file. Currently this
  // includes:
  //
  // (1) Resetting the |current_microtask| slot on the Isolate to avoid leaking
  // memory (and also to keep |current_microtask| not being undefined as an
  // indicator that we're currently pumping the microtask queue).
  // (2) Empty the promise stack to avoid leaking memory.
  // (3) If the |current_microtask| is a promise reaction or resolve thenable
  // job task, then signal the async event delegate and debugger that the
  // microtask finished running.
  //
  // Reset the |current_microtask| global slot.
  DirectHandle<Microtask> current_microtask(
      Cast<Microtask>(heap()->current_microtask()), this);
  heap()->set_current_microtask(ReadOnlyRoots(this).undefined_value());
  if (IsPromiseReactionJobTask(*current_microtask)) {
    auto promise_reaction_job_task =
        Cast<PromiseReactionJobTask>(current_microtask);
    DirectHandle<HeapObject> promise_or_capability(
        promise_reaction_job_task->promise_or_capability(), this);
    if (IsPromiseCapability(*promise_or_capability)) {
      promise_or_capability = direct_handle(
          Cast<PromiseCapability>(promise_or_capability)->promise(), this);
    }
    if (IsJSPromise(*promise_or_capability)) {
      OnPromiseAfter(Cast<JSPromise>(promise_or_capability));
    }
  } else if (IsPromiseResolveThenableJobTask(*current_microtask)) {
    auto promise_resolve_thenable_job_task =
        Cast<PromiseResolveThenableJobTask>(current_microtask);
    DirectHandle<JSPromise> promise_to_resolve(
        promise_resolve_thenable_job_task->promise_to_resolve(), this);
    OnPromiseAfter(promise_to_resolve);
  }
  SetTerminationOnExternalTryCatch();
}
References v8::internal::DCHECK(), v8::internal::direct_handle(), heap(), is_execution_terminating(), OnPromiseAfter(), and SetTerminationOnExternalTryCatch().
Referenced by v8::internal::MicrotaskQueue::RunMicrotasks().
operator delete()
void v8::internal::Isolate::operator delete (void *) [delete]
operator new() [1/2]
void* v8::internal::Isolate::operator new (size_t) [delete]
operator new() [2/2]
void* v8::internal::Isolate::operator new (size_t , void * ptr) [inline], [private]
Definition at line 2967 of file isolate.h.
{ return ptr; }
operator=()
Isolate& v8::internal::Isolate::operator= (const Isolate &) [delete]
optimizing_compile_dispatcher()
OptimizingCompileDispatcher* v8::internal::Isolate::optimizing_compile_dispatcher () [inline]
Definition at line 1755 of file isolate.h.
                                                               {
    DCHECK_NOT_NULL(optimizing_compile_dispatcher_);
    return optimizing_compile_dispatcher_;
  }
References DCHECK_NOT_NULL.
Referenced by AbortConcurrentOptimization(), v8::internal::compiler::CodeAssembler::BuiltinCompilationScheduler::AwaitAndFinalizeCurrentBatch(), v8::internal::anonymous_namespace{compiler.cc}::CompileTurbofan_Concurrent(), v8::internal::anonymous_namespace{runtime-test.cc}::FinalizeOptimization(), v8::internal::StackGuard::HandleInterrupts(), IncreaseConcurrentOptimizationPriority(), v8::internal::compiler::CodeAssembler::BuiltinCompilationScheduler::QueueJob(), v8::internal::OptimizingCompileTaskExecutor::RunCompilationJob(), and v8::Shell::RunMain().
owns_shareable_data()
bool v8::internal::Isolate::owns_shareable_data () [inline]
Definition at line 2355 of file isolate.h.
{ return owns_shareable_data_; }
Referenced by Deinit(), and Init().
OwnsStringTables()
bool v8::internal::Isolate::OwnsStringTables () const [inline]
Definition at line 2361 of file isolate.h.
                                {
    return !v8_flags.shared_string_table || is_shared_space_isolate();
  }
References v8::internal::v8_flags.
Referenced by v8::internal::MarkCompactCollector::ClearNonLiveReferences(), Deinit(), Init(), v8::internal::Heap::IterateRoots(), and v8::internal::StringTableInsertionKey::PrepareForInsertion().
page_allocator()
v8::PageAllocator * v8::internal::Isolate::page_allocator () const
Definition at line 4237 of file isolate.cc.
                                               {
  return isolate_group()->page_allocator();
}
References isolate_group(), and v8::internal::IsolateGroup::page_allocator().
Referenced by Init(), and v8::internal::Heap::SetUp().
pending_message()
Tagged< Object > v8::internal::Isolate::pending_message () [inline]
Definition at line 92 of file isolate-inl.h.
                                        {
  return thread_local_top()->pending_message_;
}
References v8::internal::ThreadLocalTop::pending_message_, and thread_local_top().
Referenced by has_pending_message(), v8::internal::MoveMessageToPromise(), PropagateExceptionToExternalTryCatch(), ReportExceptionFunctionCallback(), ReportExceptionPropertyCallback(), ReportPendingMessages(), and Throw().
persistent_handles_list()
PersistentHandlesList* v8::internal::Isolate::persistent_handles_list () const [inline]
Definition at line 1727 of file isolate.h.
                                                         {
    return persistent_handles_list_.get();
  }
Referenced by v8::internal::Heap::IterateRoots(), v8::internal::PersistentHandles::PersistentHandles(), and v8::internal::PersistentHandles::~PersistentHandles().
PredictExceptionCatcher()
Isolate::CatchType v8::internal::Isolate::PredictExceptionCatcher ()
Definition at line 2904 of file isolate.cc.
                                                  {
  if (TopExceptionHandlerType(Tagged<Object>()) ==
      ExceptionHandlerType::kExternalTryCatch) {
    return CAUGHT_BY_EXTERNAL;
  }
  // Search for an exception handler by performing a full walk over the stack.
  for (StackFrameSummaryIterator iter(this); !iter.done(); iter.Advance()) {
    Isolate::CatchType prediction = PredictExceptionCatchAtFrame(iter);
    if (prediction != NOT_CAUGHT) return prediction;
  }
  // Handler not found.
  return NOT_CAUGHT;
}
References CAUGHT_BY_EXTERNAL, kExternalTryCatch, NOT_CAUGHT, v8::internal::anonymous_namespace{isolate.cc}::PredictExceptionCatchAtFrame(), and TopExceptionHandlerType().
Referenced by CreateMessageOrAbort(), and v8::internal::Debug::OnThrow().
PrepareBuiltinSourcePositionMap()
void v8::internal::Isolate::PrepareBuiltinSourcePositionMap ()
Definition at line 6905 of file isolate.cc.
                                              {
  if (embedded_file_writer_ != nullptr) {
    return embedded_file_writer_->PrepareBuiltinSourcePositionMap(
        this->builtins());
  }
}
References builtins(), embedded_file_writer_, and v8::internal::EmbeddedFileWriterInterface::PrepareBuiltinSourcePositionMap().
Referenced by CreateAndSetEmbeddedBlob().
PrintCurrentStackTrace()
void v8::internal::Isolate::PrintCurrentStackTrace (std::ostream & out, PrintCurrentStackTraceFilterCallback should_include_frame_callback = nullptr)
Definition at line 2925 of file isolate.cc.
                                                                        {
  DirectHandle<FixedArray> frames = CaptureSimpleStackTrace(
      this, FixedArray::kMaxLength, SKIP_NONE, factory()->undefined_value());
  IncrementalStringBuilder builder(this);
  for (int i = 0; i < frames->length(); ++i) {
    DirectHandle<CallSiteInfo> frame(Cast<CallSiteInfo>(frames->get(i)), this);
    if (should_include_frame_callback) {
      Tagged<Object> raw_script_name = frame->GetScriptNameOrSourceURL();
      v8::Local<v8::String> script_name_local;
      v8::Isolate* v8_isolate = reinterpret_cast<v8::Isolate*>(this);
      if (IsString(raw_script_name)) {
        DirectHandle<String> script_name =
            Handle<String>(Cast<String>(raw_script_name), this);
        script_name_local = v8::Utils::ToLocal(script_name);
      } else {
        script_name_local = v8::String::Empty(v8_isolate);
      }
      if (should_include_frame_callback(v8_isolate, script_name_local)) {
        SerializeCallSiteInfo(this, frame, &builder);
      } else {
        builder.AppendString("<redacted>");
      }
    } else {
      SerializeCallSiteInfo(this, frame, &builder);
    }
    if (i != frames->length() - 1) builder.AppendCharacter('\n');
  }
  DirectHandle<String> stack_trace = builder.Finish().ToHandleChecked();
  stack_trace->PrintOn(out);
}
References v8::internal::IncrementalStringBuilder::AppendCharacter(), v8::internal::IncrementalStringBuilder::AppendString(), v8::internal::anonymous_namespace{isolate.cc}::CaptureSimpleStackTrace(), v8::String::Empty(), factory(), v8::internal::IncrementalStringBuilder::Finish(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::FixedArray::kMaxLength, v8::internal::SerializeCallSiteInfo(), and v8::internal::SKIP_NONE.
Referenced by CreateMessageOrAbort(), and v8::Message::PrintCurrentStackTrace().
PRINTF_FORMAT()
v8::internal::Isolate::PRINTF_FORMAT (2 , 3) const
PrintNumberStringCacheStats()
void v8::internal::Isolate::PrintNumberStringCacheStats (const char * comment, bool final_summary)
Definition at line 7808 of file isolate.cc.
                                                              {
#define FETCH_COUNTER(name) \
  uint32_t name = static_cast<uint32_t>(counters()->name()->Get());
  FETCH_COUNTER(write_barriers)
  FETCH_COUNTER(number_string_cache_smi_probes)
  FETCH_COUNTER(number_string_cache_smi_misses)
  FETCH_COUNTER(number_string_cache_double_probes)
  FETCH_COUNTER(number_string_cache_double_misses)
#undef FETCH_COUNTER
  PrintF("=== NumberToString cache usage stats (%s):\n", comment);
  if (final_summary && write_barriers == 0) {
    // If write barriers count is zero, then it's most likely because
    // builtins are compiled without --native-code-counters.
    PrintF(
        "=== WARNING: empty stats! Ensure gn args contain: "
        "`v8_enable_snapshot_native_code_counters = true`\n");
  }
  double smi_miss_rate =
      number_string_cache_smi_probes
          ? static_cast<double>(number_string_cache_smi_misses) /
                number_string_cache_smi_probes
          : 0;
  double double_miss_rate =
      number_string_cache_double_probes
          ? static_cast<double>(number_string_cache_double_misses) /
                number_string_cache_double_probes
          : 0;
  PrintF("=== SmiStringCache miss rate: %.6f (%d / %d)\n", //
         smi_miss_rate, number_string_cache_smi_misses,
         number_string_cache_smi_probes);
  PrintF("=== DoubleStringCache miss rate: %.6f (%d / %d)\n", //
         double_miss_rate, number_string_cache_double_misses,
         number_string_cache_double_probes);
  uint32_t smi_string_cache_capacity =
      factory()->smi_string_cache()->capacity();
  uint32_t smi_string_used_entries =
      factory()->smi_string_cache()->GetUsedEntriesCount();
  uint32_t double_string_cache_capacity =
      factory()->double_string_cache()->capacity();
  uint32_t double_string_used_entries =
      factory()->double_string_cache()->GetUsedEntriesCount();
  double smi_cache_utilization_rate =
      static_cast<double>(smi_string_used_entries) / smi_string_cache_capacity;
  double double_cache_utilization_rate =
      static_cast<double>(double_string_used_entries) /
      double_string_cache_capacity;
  PrintF("=== SmiStringCache utilization: %.6f (%d / %d)\n", //
         smi_cache_utilization_rate, smi_string_used_entries,
         smi_string_cache_capacity);
  PrintF("=== DoubleStringCache utilization: %.6f (%d / %d)\n", //
         double_cache_utilization_rate, double_string_used_entries,
         double_string_cache_capacity);
  if (final_summary) {
    PrintF("=== --smi-string-cache-size=%d\n",
           v8_flags.smi_string_cache_size.value());
    PrintF("=== --double-string-cache-size=%d\n",
           v8_flags.double_string_cache_size.value());
  }
  PrintF("\n");
}
References factory(), FETCH_COUNTER, v8::internal::PrintF(), and v8::internal::v8_flags.
Referenced by DumpAndResetStats().
PrintStack() [1/2]
void v8::internal::Isolate::PrintStack (FILE * out, PrintStackMode mode = kPrintStackVerbose)
Definition at line 1735 of file isolate.cc.
                                                       {
  if (stack_trace_nesting_level_ == 0) {
    stack_trace_nesting_level_++;
    StringStream::ClearMentionedObjectCache(this);
    HeapStringAllocator allocator;
    StringStream accumulator(&allocator);
    incomplete_message_ = &accumulator;
    PrintStack(&accumulator, mode);
    accumulator.OutputToFile(out);
    InitializeLoggingAndCounters();
    accumulator.Log(this);
    incomplete_message_ = nullptr;
    stack_trace_nesting_level_ = 0;
  } else if (stack_trace_nesting_level_ == 1) {
    stack_trace_nesting_level_++;
    base::OS::PrintError(
        "\n\nAttempt to print stack while printing stack (double fault)\n");
    base::OS::PrintError(
        "If you are lucky you may find a partial stack dump on stdout.\n\n");
    incomplete_message_->OutputToFile(out);
  }
}
References allocator(), v8::internal::StringStream::ClearMentionedObjectCache(), incomplete_message_, InitializeLoggingAndCounters(), v8::internal::StringStream::Log(), mode(), v8::internal::StringStream::OutputToFile(), PrintStack(), and stack_trace_nesting_level_.
PrintStack() [2/2]
void v8::internal::Isolate::PrintStack (StringStream * accumulator, PrintStackMode mode = kPrintStackVerbose)
Definition at line 1766 of file isolate.cc.
                                                                       {
  HandleScope scope(this);
  DCHECK(accumulator->IsMentionedObjectCacheClear(this));
  // Avoid printing anything if there are no frames.
  if (c_entry_fp(thread_local_top()) == 0) return;
  accumulator->Add(
      "\n==== JS stack trace =========================================\n\n");
  PrintFrames(this, accumulator, StackFrame::OVERVIEW);
  if (mode == kPrintStackVerbose) {
    accumulator->Add(
        "\n==== Details ================================================\n\n");
    PrintFrames(this, accumulator, StackFrame::DETAILS);
    accumulator->PrintMentionedObjectCache(this);
  }
  accumulator->Add("=====================\n\n");
}
References v8::internal::StringStream::Add(), c_entry_fp(), v8::internal::DCHECK(), v8::internal::StackFrame::DETAILS, kPrintStackVerbose, mode(), v8::internal::StackFrame::OVERVIEW, v8::internal::PrintFrames(), v8::internal::StringStream::PrintMentionedObjectCache(), and thread_local_top().
Referenced by _v8_internal_Print_StackTrace(), v8::internal::Heap::AllocationTrackerForDebugging::AllocationEvent(), PrintStack(), v8::internal::StackTraceFailureMessage::StackTraceFailureMessage(), StackTraceString(), Throw(), ThrowIllegalOperation(), and v8::D8Console::Trace().
priority()
v8::Isolate::Priority v8::internal::Isolate::priority () [inline]
Definition at line 2122 of file isolate.h.
{ return priority_; }
Referenced by SetPriority(), v8::internal::Heap::ShouldOptimizeForMemoryUsage(), and v8::internal::GCTracer::StartCycle().
promise_hook_address()
Address v8::internal::Isolate::promise_hook_address () [inline]
Definition at line 1884 of file isolate.h.
                                 {
    return reinterpret_cast<Address>(&promise_hook_);
  }
promise_hook_flags_address()
Address v8::internal::Isolate::promise_hook_flags_address () [inline]
Definition at line 1880 of file isolate.h.
                                       {
    return reinterpret_cast<Address>(&promise_hook_flags_);
  }
PromiseHookStateUpdated()
void v8::internal::Isolate::PromiseHookStateUpdated ()
Definition at line 6572 of file isolate.cc.
                                      {
  promise_hook_flags_ =
      (promise_hook_flags_ & PromiseHookFields::HasContextPromiseHook::kMask) |
      PromiseHookFields::HasIsolatePromiseHook::encode(promise_hook_) |
      PromiseHookFields::HasAsyncEventDelegate::encode(async_event_delegate_) |
      PromiseHookFields::IsDebugActive::encode(debug()->is_active());
  if (promise_hook_flags_ != 0) {
    UpdatePromiseHookProtector();
  }
}
References async_event_delegate_, debug(), v8::base::BitField< T, shift, size, U >::encode(), v8::base::BitField< T, shift, size, U >::kMask, promise_hook_, promise_hook_flags_, and UpdatePromiseHookProtector().
Referenced by SetPromiseHook(), and v8::internal::Debug::UpdateState().
PropagateExceptionToExternalTryCatch()
bool v8::internal::Isolate::PropagateExceptionToExternalTryCatch (ExceptionHandlerType top_handler) [private]
Definition at line 4865 of file isolate.cc.
                                      {
  Tagged<Object> exception = this->exception();
  if (top_handler == ExceptionHandlerType::kJavaScriptHandler) return false;
  if (top_handler == ExceptionHandlerType::kNone) return true;
  DCHECK_EQ(ExceptionHandlerType::kExternalTryCatch, top_handler);
  if (!is_catchable_by_javascript(exception)) {
    SetTerminationOnExternalTryCatch();
  } else {
    v8::TryCatch* handler = try_catch_handler();
    DCHECK(IsJSMessageObject(pending_message()) ||
           IsTheHole(pending_message(), this));
    handler->can_continue_ = true;
    handler->exception_ = reinterpret_cast<void*>(exception.ptr());
    // Propagate to the external try-catch only if we got an actual message.
    if (!has_pending_message()) return true;
    handler->message_obj_ = reinterpret_cast<void*>(pending_message().ptr());
  }
  return true;
}
References v8::internal::DCHECK(), DCHECK_EQ, exception(), handler(), has_pending_message(), is_catchable_by_javascript(), kExternalTryCatch, kJavaScriptHandler, kNone, pending_message(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), SetTerminationOnExternalTryCatch(), and try_catch_handler().
Referenced by ReportPendingMessages(), and Throw().
PushParamsAndContinue()
void v8::internal::Isolate::PushParamsAndContinue (void * ptr1 = nullptr, void * ptr2 = nullptr, void * ptr3 = nullptr, void * ptr4 = nullptr, void * ptr5 = nullptr, void * ptr6 = nullptr)
Definition at line 726 of file isolate.cc.
                                                                        {
  StackTraceFailureMessage message(
      this, StackTraceFailureMessage::kDontIncludeStackTrace,
      {ptr1, ptr2, ptr3, ptr4, ptr5, ptr6});
  message.Print();
  V8::GetCurrentPlatform()->DumpWithoutCrashing();
}
References v8::Platform::DumpWithoutCrashing(), v8::internal::V8::GetCurrentPlatform(), v8::internal::StackTraceFailureMessage::kDontIncludeStackTrace, and v8::internal::StackTraceFailureMessage::Print().
PushParamsAndDie()
void v8::internal::Isolate::PushParamsAndDie (void * ptr1 = nullptr, void * ptr2 = nullptr, void * ptr3 = nullptr, void * ptr4 = nullptr, void * ptr5 = nullptr, void * ptr6 = nullptr)
Definition at line 708 of file isolate.cc.
                                                       {
  StackTraceFailureMessage message(
      this, StackTraceFailureMessage::kDontIncludeStackTrace,
      {ptr1, ptr2, ptr3, ptr4, ptr5, ptr6});
  message.Print();
  base::OS::Abort();
}
References v8::base::OS::Abort(), v8::internal::StackTraceFailureMessage::kDontIncludeStackTrace, and v8::internal::StackTraceFailureMessage::Print().
Referenced by v8::internal::FeedbackNexus::ic_state(), and v8::internal::anonymous_namespace{compiler.cc}::VerifyCodeMerge().
PushStackTraceAndContinue()
void v8::internal::Isolate::PushStackTraceAndContinue (void * ptr1 = nullptr, void * ptr2 = nullptr, void * ptr3 = nullptr, void * ptr4 = nullptr, void * ptr5 = nullptr, void * ptr6 = nullptr)
Definition at line 717 of file isolate.cc.
                                                                            {
  StackTraceFailureMessage message(this,
                                   StackTraceFailureMessage::kIncludeStackTrace,
                                   {ptr1, ptr2, ptr3, ptr4, ptr5, ptr6});
  message.Print();
  V8::GetCurrentPlatform()->DumpWithoutCrashing();
}
References v8::Platform::DumpWithoutCrashing(), v8::internal::V8::GetCurrentPlatform(), v8::internal::StackTraceFailureMessage::kIncludeStackTrace, and v8::internal::StackTraceFailureMessage::Print().
PushStackTraceAndDie()
void v8::internal::Isolate::PushStackTraceAndDie (void * ptr1 = nullptr, void * ptr2 = nullptr, void * ptr3 = nullptr, void * ptr4 = nullptr, void * ptr5 = nullptr, void * ptr6 = nullptr)
Definition at line 699 of file isolate.cc.
                                                                       {
  StackTraceFailureMessage message(this,
                                   StackTraceFailureMessage::kIncludeStackTrace,
                                   {ptr1, ptr2, ptr3, ptr4, ptr5, ptr6});
  message.Print();
  base::OS::Abort();
}
References v8::base::OS::Abort(), v8::internal::StackTraceFailureMessage::kIncludeStackTrace, and v8::internal::StackTraceFailureMessage::Print().
Referenced by v8::internal::CodeSerializer::FinishOffThreadDeserialize(), v8::internal::LookupIterator::GetRootForNonJSReceiver(), v8::internal::parsing::ParseFunction(), and v8::internal::MapUpdater::TryUpdateNoLock().
random_number_generator()
base::RandomNumberGenerator * v8::internal::Isolate::random_number_generator ()
Definition at line 6425 of file isolate.cc.
                                                            {
  // TODO(bmeurer) Initialized lazily because it depends on flags; can
  // be fixed once the default isolate cleanup is done.
  return ensure_rng_exists(&random_number_generator_, v8_flags.random_seed);
}
References v8::internal::ensure_rng_exists(), random_number_generator_, and v8::internal::v8_flags.
Referenced by v8::internal::wasm::WasmEngine::AsyncCompile(), fuzzer_rng(), GenerateIdentityHash(), v8::internal::Heap::InitializeHashSeed(), and v8::internal::MathRandom::RefillCache().
raw_native_context()
Tagged< NativeContext > v8::internal::Isolate::raw_native_context () [inline]
Definition at line 53 of file isolate-inl.h.
                                                  {
  DCHECK(!context().is_null());
  return context()->native_context();
}
References context(), and v8::internal::DCHECK().
Referenced by v8::internal::JSPromise::Fulfill(), v8::internal::anonymous_namespace{api-natives.cc}::IsSimpleInstantiation(), v8::internal::Factory::NewContextfulMapForCurrentContext(), v8::internal::Factory::NewJSArrayWithUnverifiedElements(), v8::internal::Factory::NewJSWeakMap(), v8::internal::Heap::NotifyContextDisposed(), v8::internal::anonymous_namespace{property-descriptor.cc}::ToPropertyDescriptorFastPath(), and UnwindAndFindHandler().
read_only_artifacts()
ReadOnlyArtifacts* v8::internal::Isolate::read_only_artifacts () const [inline]
Definition at line 789 of file isolate.h.
                                                 {
    ReadOnlyArtifacts* artifacts = isolate_group()->read_only_artifacts();
    DCHECK_NOT_NULL(artifacts);
    return artifacts;
  }
References DCHECK_NOT_NULL.
Referenced by v8::internal::ObjectPostProcessor::Finalize().
read_only_heap()
ReadOnlyHeap* v8::internal::Isolate::read_only_heap () const [inline]
Definition at line 1216 of file isolate.h.
{ return read_only_heap_; }
Referenced by v8::internal::SnapshotCreatorImpl::CreateBlob(), v8::internal::ReadOnlyDeserializer::DeserializeIntoIsolate(), v8::internal::anonymous_namespace{read-only-serializer.cc}::Encode(), v8::internal::LocalIsolate::read_only_heap(), v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlySegmentForSerialization::ReadOnlySegmentForSerialization(), v8::internal::ReadOnlyHeapImageDeserializer::ro_space(), v8::internal::SetupIsolateDelegate::SetupHeapInternal(), v8::internal::ReadOnlyArtifacts::VerifyHeapAndSpaceRelationships(), VerifyStaticRoots(), and v8::internal::SnapshotCreatorImpl::~SnapshotCreatorImpl().
regexp_indices()
std::vector<int>* v8::internal::Isolate::regexp_indices () [inline]
Definition at line 1493 of file isolate.h.
{ return &regexp_indices_; }
Referenced by v8::internal::anonymous_namespace{runtime-regexp.cc}::GetRewoundRegexpIndicesList(), and v8::internal::anonymous_namespace{runtime-regexp.cc}::TruncateRegexpIndicesList().
regexp_macro_assembler_canonicalize()
unibrow::Mapping<unibrow::Ecma262Canonicalize>* v8::internal::Isolate::regexp_macro_assembler_canonicalize () [inline]
Definition at line 1451 of file isolate.h.
                                        {
    return &regexp_macro_assembler_canonicalize_;
  }
Referenced by v8::internal::RegExpMacroAssembler::CaseInsensitiveCompareUnicode(), v8::internal::RegExpDisjunction::RationalizeConsecutiveAtoms(), and v8::internal::RegExpDisjunction::SortConsecutiveAtoms().
regexp_stack()
RegExpStack* v8::internal::Isolate::regexp_stack () const [inline]
Definition at line 1471 of file isolate.h.
{ return regexp_stack_; }
Referenced by v8::internal::ThreadManager::EagerlyArchiveThread(), v8::internal::ThreadManager::FreeThreadResources(), v8::internal::NativeRegExpMacroAssembler::GrowStack(), and v8::internal::ThreadManager::RestoreThread().
regexp_static_result_offsets_vector()
int32_t* v8::internal::Isolate::regexp_static_result_offsets_vector () const [inline]
Definition at line 1475 of file isolate.h.
                                                       {
    return isolate_data()->regexp_static_result_offsets_vector();
  }
Referenced by v8::internal::RegExpResultVectorScope::Initialize().
RegisterDeserializerFinished()
void v8::internal::Isolate::RegisterDeserializerFinished () [inline]
Definition at line 941 of file isolate.h.
{}
Referenced by v8::internal::LocalIsolate::RegisterDeserializerFinished().
RegisterDeserializerStarted()
void v8::internal::Isolate::RegisterDeserializerStarted () [inline]
Definition at line 940 of file isolate.h.
{}
Referenced by v8::internal::LocalIsolate::RegisterDeserializerStarted().
RegisterEmbeddedFileWriter()
void v8::internal::Isolate::RegisterEmbeddedFileWriter (EmbeddedFileWriterInterface * writer) [inline]
Definition at line 2049 of file isolate.h.
                                                                       {
    embedded_file_writer_ = writer;
  }
Referenced by main().
RegisterManagedPtrDestructor()
void v8::internal::Isolate::RegisterManagedPtrDestructor (ManagedPtrDestructor * finalizer)
Definition at line 3860 of file isolate.cc.
                                                                           {
  base::MutexGuard lock(&managed_ptr_destructors_mutex_);
  DCHECK_NULL(destructor->prev_);
  DCHECK_NULL(destructor->next_);
  if (managed_ptr_destructors_head_) {
    managed_ptr_destructors_head_->prev_ = destructor;
  }
  destructor->next_ = managed_ptr_destructors_head_;
  managed_ptr_destructors_head_ = destructor;
}
References DCHECK_NULL, managed_ptr_destructors_head_, managed_ptr_destructors_mutex_, v8::internal::ManagedPtrDestructor::next_, and v8::internal::ManagedPtrDestructor::prev_.
Referenced by v8::internal::Managed< CppType >::From(), and v8::internal::TrustedManaged< CppType >::From().
RegisterTryCatchHandler()
void v8::internal::Isolate::RegisterTryCatchHandler (v8::TryCatch * that)
Definition at line 664 of file isolate.cc.
                                                      {
  thread_local_top()->try_catch_handler_ = that;
}
References thread_local_top(), and v8::internal::ThreadLocalTop::try_catch_handler_.
Referenced by v8::TryCatch::TryCatch().
ReleaseSharedPtrs()
void v8::internal::Isolate::ReleaseSharedPtrs ()
Definition at line 3835 of file isolate.cc.
                                {
  base::MutexGuard lock(&managed_ptr_destructors_mutex_);
  while (managed_ptr_destructors_head_) {
    ManagedPtrDestructor* l = managed_ptr_destructors_head_;
    ManagedPtrDestructor* n = nullptr;
    managed_ptr_destructors_head_ = nullptr;
    for (; l != nullptr; l = n) {
      l->external_memory_accounter_.Decrease(
          reinterpret_cast<v8::Isolate*>(this), l->estimated_size_);
      l->destructor_(l->shared_ptr_ptr_);
      n = l->next_;
      delete l;
    }
  }
}
References v8::internal::compiler::turboshaft::l, managed_ptr_destructors_head_, and managed_ptr_destructors_mutex_.
Referenced by Deinit().
RemoveBeforeCallEnteredCallback()
void v8::internal::Isolate::RemoveBeforeCallEnteredCallback (BeforeCallEnteredCallback callback)
Definition at line 6503 of file isolate.cc.
                                        {
  auto pos = std::find(before_call_entered_callbacks_.begin(),
                       before_call_entered_callbacks_.end(), callback);
  if (pos == before_call_entered_callbacks_.end()) return;
  before_call_entered_callbacks_.erase(pos);
}
References before_call_entered_callbacks_.
Referenced by v8::Isolate::RemoveBeforeCallEnteredCallback().
RemoveCallCompletedCallback()
void v8::internal::Isolate::RemoveCallCompletedCallback (CallCompletedCallback callback)
Definition at line 6518 of file isolate.cc.
                                                                        {
  auto pos = std::find(call_completed_callbacks_.begin(),
                       call_completed_callbacks_.end(), callback);
  if (pos == call_completed_callbacks_.end()) return;
  call_completed_callbacks_.erase(pos);
}
References call_completed_callbacks_.
Referenced by v8::Isolate::RemoveCallCompletedCallback().
RemoveCodeMemoryChunk()
void v8::internal::Isolate::RemoveCodeMemoryChunk (MutablePageMetadata * chunk)
Definition at line 7616 of file isolate.cc.
                                                              {
  // We only keep track of individual code pages/allocations if we are on arm32,
  // because on x64 and arm64 we have a code range which makes this unnecessary.
#if defined(V8_TARGET_ARCH_ARM)
  void* removed_page_start = reinterpret_cast<void*>(chunk->area_start());
  std::vector<MemoryRange>* old_code_pages = GetCodePages();
  DCHECK_NOT_NULL(old_code_pages);
  std::vector<MemoryRange>* new_code_pages;
  if (old_code_pages == &code_pages_buffer1_) {
    new_code_pages = &code_pages_buffer2_;
  } else {
    new_code_pages = &code_pages_buffer1_;
  }
  // Copy all existing data from the old vector to the new vector except the
  // removed page.
  new_code_pages->clear();
  new_code_pages->reserve(old_code_pages->size() - 1);
  std::remove_copy_if(old_code_pages->begin(), old_code_pages->end(),
                      std::back_inserter(*new_code_pages),
                      [removed_page_start](const MemoryRange& range) {
                        return range.start == removed_page_start;
                      });
  DCHECK_EQ(old_code_pages->size(), new_code_pages->size() + 1);
  // Atomically switch out the pointer
  SetCodePages(new_code_pages);
#endif // !defined(V8_TARGET_ARCH_ARM)
}
References v8::internal::MemoryChunkMetadata::area_start(), code_pages_buffer1_, code_pages_buffer2_, DCHECK_EQ, DCHECK_NOT_NULL, GetCodePages(), and SetCodePages().
Referenced by v8::internal::CodeLargeObjectSpace::RemovePage().
RemoveContextIdCallback()
void v8::internal::Isolate::RemoveContextIdCallback (const v8::WeakCallbackInfo< void > & data) [static], [private]
Definition at line 7598 of file isolate.cc.
                                                                          {
  Isolate* isolate = reinterpret_cast<Isolate*>(data.GetIsolate());
  uintptr_t context_id = reinterpret_cast<uintptr_t>(data.GetParameter());
  isolate->recorder_context_id_map_.erase(context_id);
}
References v8::WeakCallbackInfo< T >::GetIsolate(), v8::WeakCallbackInfo< T >::GetParameter(), v8::internal::Factory::isolate(), and recorder_context_id_map_.
Referenced by GetOrRegisterRecorderContextId().
ReportExceptionFunctionCallback()
void v8::internal::Isolate::ReportExceptionFunctionCallback (DirectHandle< JSReceiver > receiver, DirectHandle< FunctionTemplateInfo > function, v8::ExceptionContext callback_kind)
Definition at line 5051 of file isolate.cc.
                                          {
  DCHECK(exception_context == v8::ExceptionContext::kConstructor ||
         exception_context == v8::ExceptionContext::kOperation);
  DCHECK_NOT_NULL(exception_propagation_callback_);
  // Ignore exceptions that we can't extend.
  if (!IsJSReceiver(this->exception())) return;
  DirectHandle<JSReceiver> exception(Cast<JSReceiver>(this->exception()), this);
  DirectHandle<Object> maybe_message(pending_message(), this);
  DirectHandle<String> property_name =
      IsUndefined(function->class_name(), this)
          ? factory()->empty_string()
          : Handle<String>(Cast<String>(function->class_name()), this);
  DirectHandle<String> interface_name =
      IsUndefined(function->interface_name(), this)
          ? factory()->empty_string()
          : Handle<String>(Cast<String>(function->interface_name()), this);
  if (exception_context != ExceptionContext::kConstructor) {
    exception_context =
        static_cast<ExceptionContext>(function->exception_context());
  }
  {
    v8::Isolate* v8_isolate = reinterpret_cast<v8::Isolate*>(this);
    // Ignore any exceptions thrown inside the callback and rethrow the
    // original exception/message.
    TryCatch try_catch(v8_isolate);
    exception_propagation_callback_(v8::ExceptionPropagationMessage(
        v8_isolate, v8::Utils::ToLocal(exception),
        v8::Utils::ToLocal(interface_name), v8::Utils::ToLocal(property_name),
        exception_context));
    try_catch.Reset();
  }
  ReThrow(*exception, *maybe_message);
}
References v8::internal::DCHECK(), DCHECK_NOT_NULL, exception(), factory(), v8::kConstructor, v8::kOperation, pending_message(), v8::TryCatch::Reset(), and ReThrow().
Referenced by NotifyExceptionPropagationCallback().
ReportExceptionPropertyCallback()
void v8::internal::Isolate::ReportExceptionPropertyCallback (DirectHandle< JSReceiver > holder, DirectHandle< Name > name, v8::ExceptionContext callback_kind)
Definition at line 5094 of file isolate.cc.
                                          {
  DCHECK_NOT_NULL(exception_propagation_callback_);
  if (!IsJSReceiver(this->exception())) return;
  DirectHandle<JSReceiver> exception(Cast<JSReceiver>(this->exception()), this);
  DirectHandle<Object> maybe_message(pending_message(), this);
  DirectHandle<String> property_name;
  std::ignore = Name::ToFunctionName(this, name).ToHandle(&property_name);
  DirectHandle<String> interface_name =
      JSReceiver::GetConstructorName(this, holder);
  {
    v8::Isolate* v8_isolate = reinterpret_cast<v8::Isolate*>(this);
    // Ignore any exceptions thrown inside the callback and rethrow the
    // original exception/message.
    TryCatch try_catch(v8_isolate);
    exception_propagation_callback_(v8::ExceptionPropagationMessage(
        v8_isolate, v8::Utils::ToLocal(exception),
        v8::Utils::ToLocal(interface_name), v8::Utils::ToLocal(property_name),
        exception_context));
    try_catch.Reset();
  }
  ReThrow(*exception, *maybe_message);
}
References DCHECK_NOT_NULL, exception(), v8::internal::JSReceiver::GetConstructorName(), wasm::ignore(), v8::internal::name, pending_message(), v8::TryCatch::Reset(), ReThrow(), and v8::internal::Name::ToFunctionName().
Referenced by NotifyExceptionPropagationCallback().
ReportFailedAccessCheck()
MaybeDirectHandle< Object > v8::internal::Isolate::ReportFailedAccessCheck (DirectHandle< JSObject > receiver)
Definition at line 1790 of file isolate.cc.
                                     {
  if (!thread_local_top()->failed_access_check_callback_) {
    THROW_NEW_ERROR(this, NewTypeError(MessageTemplate::kNoAccess));
  }
  DCHECK(IsAccessCheckNeeded(*receiver));
  DCHECK(!context().is_null());
  // Get the data object from access check info.
  HandleScope scope(this);
  DirectHandle<Object> data;
  {
    DisallowGarbageCollection no_gc;
    Tagged<AccessCheckInfo> access_check_info =
        AccessCheckInfo::Get(this, receiver);
    if (access_check_info.is_null()) {
      no_gc.Release();
      THROW_NEW_ERROR(this, NewTypeError(MessageTemplate::kNoAccess));
    }
    data = direct_handle(access_check_info->data(), this);
  }
  {
    // Leaving JavaScript.
    VMState<EXTERNAL> state(this);
    thread_local_top()->failed_access_check_callback_(
        v8::Utils::ToLocal(receiver), v8::ACCESS_HAS, v8::Utils::ToLocal(data));
  }
  RETURN_VALUE_IF_EXCEPTION(this, {});
  // Throw exception even the callback forgot to do so.
  THROW_NEW_ERROR(this, NewTypeError(MessageTemplate::kNoAccess));
}
References v8::ACCESS_HAS, context(), v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::ThreadLocalTop::failed_access_check_callback_, v8::internal::AccessCheckInfo::Get(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::PerThreadAssertScopeEmpty< kAllow, kTypes >::Release(), RETURN_VALUE_IF_EXCEPTION, thread_local_top(), and THROW_NEW_ERROR.
Referenced by v8::internal::JSReceiver::AddPrivateField(), v8::internal::JSReceiver::CheckPrivateNameStore(), v8::internal::JSObject::DefineOwnAccessorIgnoreAttributes(), v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(), v8::internal::JSReceiver::DeleteProperty(), v8::internal::GetHomeObjectPrototype(), v8::internal::JSObject::GetPropertyAttributesWithFailedAccessCheck(), v8::internal::JSObject::GetPropertyWithFailedAccessCheck(), v8::internal::anonymous_namespace{builtins-api.cc}::HandleApiCallHelper(), v8::internal::anonymous_namespace{builtins-object.cc}::ObjectLookupAccessor(), v8::internal::JSReceiver::OrdinaryDefineOwnProperty(), v8::internal::JSObject::PreventExtensions(), v8::internal::JSObject::PreventExtensionsWithTransition(), v8::internal::JSObject::SetAccessor(), v8::internal::JSObject::SetPropertyWithFailedAccessCheck(), and v8::internal::JSObject::SetPrototype().
ReportPendingMessages()
void v8::internal::Isolate::ReportPendingMessages (bool report = true)
Definition at line 3146 of file isolate.cc.
                                               {
  Tagged<Object> exception_obj = exception();
  ExceptionHandlerType top_handler = TopExceptionHandlerType(exception_obj);
  // Try to propagate the exception to an external v8::TryCatch handler. If
  // propagation was unsuccessful, then we will get another chance at reporting
  // the pending message if the exception is re-thrown.
  bool has_been_propagated = PropagateExceptionToExternalTryCatch(top_handler);
  if (!has_been_propagated) return;
  if (!report) return;
  DCHECK(AllowExceptions::IsAllowed(this));
  // The embedder might run script in response to an exception.
  AllowJavascriptExecutionDebugOnly allow_script(this);
  // Clear the pending message object early to avoid endless recursion.
  Tagged<Object> message_obj = pending_message();
  clear_pending_message();
  // For uncatchable exceptions we do nothing. If needed, the exception and the
  // message have already been propagated to v8::TryCatch.
  if (!is_catchable_by_javascript(exception_obj)) return;
  // Determine whether the message needs to be reported to all message handlers
  // depending on whether the topmost external v8::TryCatch is verbose. We know
  // there's no JavaScript handler on top; if there was, we would've returned
  // early.
  DCHECK_NE(ExceptionHandlerType::kJavaScriptHandler, top_handler);
  bool should_report_exception;
  if (top_handler == ExceptionHandlerType::kExternalTryCatch) {
    should_report_exception = try_catch_handler()->is_verbose_;
  } else {
    should_report_exception = true;
  }
  // Actually report the pending message to all message handlers.
  if (!IsTheHole(message_obj, this) && should_report_exception) {
    HandleScope scope(this);
    DirectHandle<JSMessageObject> message(Cast<JSMessageObject>(message_obj),
                                          this);
    Handle<Script> script(message->script(), this);
    // Clear the exception and restore it afterwards, otherwise
    // CollectSourcePositions will abort.
    {
      ExceptionScope exception_scope(this);
      JSMessageObject::EnsureSourcePositionsAvailable(this, message);
    }
    int start_pos = message->GetStartPosition();
    int end_pos = message->GetEndPosition();
    MessageLocation location(script, start_pos, end_pos);
    MessageHandler::ReportMessage(this, &location, message);
  }
}
References clear_pending_message(), v8::internal::DCHECK(), DCHECK_NE, v8::internal::JSMessageObject::EnsureSourcePositionsAvailable(), exception(), is_catchable_by_javascript(), v8::TryCatch::is_verbose_, kExternalTryCatch, kJavaScriptHandler, pending_message(), PropagateExceptionToExternalTryCatch(), v8::internal::MessageHandler::ReportMessage(), v8::internal::script, TopExceptionHandlerType(), and try_catch_handler().
Referenced by v8::ScriptCompiler::Compile(), v8::ScriptCompiler::CompileModule(), v8::internal::anonymous_namespace{compiler.cc}::GetSharedFunctionInfoForScriptImpl(), v8::internal::Compiler::GetWrappedFunction(), and v8::internal::anonymous_namespace{execution.cc}::Invoke().
ReportPromiseReject()
void v8::internal::Isolate::ReportPromiseReject (DirectHandle< JSPromise > promise, DirectHandle< Object > value, v8::PromiseRejectEvent event)
Definition at line 7140 of file isolate.cc.
                                                              {
  if (promise_reject_callback_ == nullptr) return;
  promise_reject_callback_(v8::PromiseRejectMessage(
      v8::Utils::PromiseToLocal(promise), event, v8::Utils::ToLocal(value)));
}
References v8::internal::value.
Referenced by v8::internal::JSPromise::Reject().
RequestInterrupt()
void v8::internal::Isolate::RequestInterrupt (InterruptCallback callback, void * data)
Definition at line 1969 of file isolate.cc.
                                                                     {
  ExecutionAccess access(this);
  api_interrupts_queue_.push(InterruptEntry(callback, data));
  stack_guard()->RequestApiInterrupt();
}
References api_interrupts_queue_, and stack_guard().
Referenced by v8::internal::TracingCpuProfilerImpl::OnTraceDisabled(), v8::internal::TracingCpuProfilerImpl::OnTraceEnabled(), v8::Isolate::RequestInterrupt(), v8::internal::ETWJITInterface::EtwIsolateOperations::RequestInterrupt(), and RequestInvalidateNoProfilingProtector().
RequestInvalidateNoProfilingProtector()
void v8::internal::Isolate::RequestInvalidateNoProfilingProtector ()
Definition at line 1992 of file isolate.cc.
                                                    {
  // This request might be triggered from arbitrary thread but protector
  // invalidation must happen on the main thread, so use Api interrupt
  // to achieve that.
  RequestInterrupt(
      [](v8::Isolate* isolate, void*) {
        Isolate* i_isolate = reinterpret_cast<Isolate*>(isolate);
        if (Protectors::IsNoProfilingIntact(i_isolate)) {
          Protectors::InvalidateNoProfiling(i_isolate);
        }
      },
      nullptr);
}
References v8::internal::Factory::isolate(), and RequestInterrupt().
RequiresCodeRange()
bool v8::internal::Isolate::RequiresCodeRange () const
Definition at line 7549 of file isolate.cc.
                                      {
  return kPlatformRequiresCodeRange && !jitless_;
}
References jitless_, and v8::internal::kPlatformRequiresCodeRange.
Referenced by MaybeRemapEmbeddedBuiltinsIntoCodeRange(), v8::internal::MemoryAllocator::PartialFreeMemory(), v8::internal::MemoryAllocator::SetPermissionsOnExecutableMemoryChunk(), and v8::internal::Heap::SetUp().
RestoreThread()
char * v8::internal::Isolate::RestoreThread (char * from)
Definition at line 3828 of file isolate.cc.
                                       {
  MemCopy(reinterpret_cast<char*>(thread_local_top()), from,
          sizeof(ThreadLocalTop));
  DCHECK(context().is_null() || IsContext(context()));
  return from + sizeof(ThreadLocalTop);
}
References context(), v8::internal::DCHECK(), v8::internal::Factory::from, v8::internal::MemCopy(), and thread_local_top().
Referenced by v8::internal::ThreadManager::RestoreThread().
ReThrow() [1/2]
Tagged< Object > v8::internal::Isolate::ReThrow (Tagged< Object > exception)
Definition at line 2217 of file isolate.cc.
                                                        {
  DCHECK(!has_exception());
  // Set the exception being re-thrown.
  set_exception(exception);
  return ReadOnlyRoots(heap()).exception();
}
References v8::internal::DCHECK(), exception(), has_exception(), heap(), and set_exception().
Referenced by v8::internal::JSDisposableStackBase::DisposeResources(), ReportExceptionFunctionCallback(), ReportExceptionPropertyCallback(), ReThrow(), and v8::internal::RUNTIME_FUNCTION().
ReThrow() [2/2]
Tagged< Object > v8::internal::Isolate::ReThrow (Tagged< Object > exception, Tagged< Object > message)
Definition at line 2225 of file isolate.cc.
                                                        {
  DCHECK(!has_exception());
  DCHECK(!has_pending_message());
  set_pending_message(message);
  return ReThrow(exception);
}
References v8::internal::DCHECK(), exception(), has_exception(), has_pending_message(), ReThrow(), and set_pending_message().
root()
Tagged<Object> v8::internal::Isolate::root (RootIndex index) const [inline]
Definition at line 1280 of file isolate.h.
                                             {
    return Tagged<Object>(roots_table()[index]);
  }
References v8::internal::index, and v8::internal::Tagged< Object >.
Referenced by v8::internal::CreateFuncRefMap(), v8::internal::V8HeapExplorer::GetStrongGcSubrootName(), v8::internal::MacroAssemblerBase::ReadOnlyRootPtr(), v8::internal::LocalIsolate::root(), and v8::internal::RootIndexMap::RootIndexMap().
root_handle()
Handle<Object> v8::internal::Isolate::root_handle (RootIndex index) [inline]
Definition at line 1284 of file isolate.h.
                                              {
    return Handle<Object>(&roots_table()[index]);
  }
References v8::internal::index.
Referenced by v8::internal::compiler::turboshaft::TurbolevEarlyLoweringReducer< Next >::CheckInstanceType(), v8::internal::compiler::CodeAssembler::LoadRoot(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadRoot(), v8::internal::compiler::CodeAssembler::LoadRootMapWord(), v8::internal::LocalIsolate::root_handle(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::RootEqual(), and SymbolFor().
root_register_addressable_region()
base::AddressRegion v8::internal::Isolate::root_register_addressable_region () const [inline]
Definition at line 1275 of file isolate.h.
                                                             {
    return base::AddressRegion(reinterpret_cast<Address>(&isolate_data_),
                               sizeof(IsolateData));
  }
Referenced by v8::internal::MacroAssemblerBase::IsAddressableThroughRootRegister().
roots_table() [1/2]
RootsTable& v8::internal::Isolate::roots_table () [inline]
Definition at line 1265 of file isolate.h.
{ return isolate_data()->roots(); }
Referenced by v8::internal::BuiltinsConstantsTableBuilder::AddObject(), v8::internal::OrderedHashTable< Derived, entrysize >::Allocate(), v8::internal::compiler::CanBeImmediate(), v8::internal::anonymous_namespace{constants-table-builder.cc}::CheckPreconditionsForPatching(), v8::internal::Factory::EmptyStringRootIsInitialized(), v8::internal::ReadOnlyHeap::InitializeFromIsolateRoots(), v8::internal::ReadOnlyHeap::InitializeIsolateRoots(), v8::internal::compiler::Loong64OperandConverter::InputImmediate(), v8::internal::compiler::PPCOperandConverter::InputImmediate(), v8::internal::compiler::RiscvOperandConverter::InputImmediate(), v8::internal::compiler::CodeGenerator::IsMaterializableFromRoot(), v8::internal::Factory::NewHeapNumberForCodeAssembler(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::OperandForDeopt(), v8::internal::LocalIsolate::roots_table(), v8::internal::Heap::roots_table(), v8::internal::RUNTIME_FUNCTION(), v8::internal::compiler::Arm64OperandConverter::ToImmediate(), v8::internal::compiler::X64OperandConverter::ToImmediate(), UnwindAndFindHandler(), v8::internal::compiler::turboshaft::ValueNeedsWriteBarrier(), v8::internal::compiler::anonymous_namespace{memory-lowering.cc}::ValueNeedsWriteBarrier(), VerifyStaticRoots(), v8::internal::RootsSerializer::VisitRootPointers(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord32EqualImpl(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord64EqualImpl(), and v8::internal::compiler::RepresentationSelector::WriteBarrierKindFor().
roots_table() [2/2]
const RootsTable& v8::internal::Isolate::roots_table () const [inline]
Definition at line 1266 of file isolate.h.
{ return isolate_data()->roots(); }
RunAllPromiseHooks()
void v8::internal::Isolate::RunAllPromiseHooks (PromiseHookType type, DirectHandle< JSPromise > promise, DirectHandle< Object > parent)
Definition at line 6986 of file isolate.cc.
                                                              {
#ifdef V8_ENABLE_JAVASCRIPT_PROMISE_HOOKS
  if (HasContextPromiseHooks()) {
    native_context()->RunPromiseHook(type, promise, parent);
  }
#endif
  if (HasIsolatePromiseHooks() || HasAsyncEventDelegate()) {
    RunPromiseHook(type, promise, parent);
  }
}
References HasAsyncEventDelegate(), HasContextPromiseHooks(), HasIsolatePromiseHooks(), native_context(), RunPromiseHook(), and v8::internal::tracing::type.
Referenced by v8::internal::Factory::NewJSPromise(), OnAsyncFunctionSuspended(), and v8::internal::JSPromise::Reject().
RunHostCreateShadowRealmContextCallback()
MaybeDirectHandle< NativeContext > v8::internal::Isolate::RunHostCreateShadowRealmContextCallback ()
Definition at line 6841 of file isolate.cc.
                                                 {
  if (host_create_shadow_realm_context_callback_ == nullptr) {
    DirectHandle<Object> exception =
        factory()->NewError(error_function(), MessageTemplate::kUnsupported);
    Throw(*exception);
    return kNullMaybeHandle;
  }
  v8::Local<v8::Context> api_context = v8::Utils::ToLocal(native_context());
  v8::Local<v8::Context> shadow_realm_context;
  API_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      this, shadow_realm_context,
      host_create_shadow_realm_context_callback_(api_context),
      MaybeDirectHandle<NativeContext>());
  DirectHandle<Context> shadow_realm_context_handle =
      v8::Utils::OpenDirectHandle(*shadow_realm_context);
  DCHECK(IsNativeContext(*shadow_realm_context_handle));
  shadow_realm_context_handle->set_scope_info(
      ReadOnlyRoots(this).shadow_realm_scope_info());
  return Cast<NativeContext>(shadow_realm_context_handle);
}
References API_ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::DCHECK(), exception(), factory(), host_create_shadow_realm_context_callback_, v8::internal::kNullMaybeHandle, v8::internal::kUnsupported, native_context(), v8::internal::Factory::NewError(), v8::Utils::OpenDirectHandle(), and Throw().
RunHostImportModuleDynamicallyCallback()
MaybeDirectHandle< JSPromise > v8::internal::Isolate::RunHostImportModuleDynamicallyCallback (MaybeDirectHandle< Script > maybe_referrer, Handle< Object > specifier, ModuleImportPhase phase, MaybeDirectHandle< Object > maybe_import_options_argument)
Definition at line 6604 of file isolate.cc.
                                                             {
  DCHECK(!is_execution_terminating());
  v8::Local<v8::Context> api_context = v8::Utils::ToLocal(native_context());
  switch (phase) {
    case ModuleImportPhase::kEvaluation:
      if (host_import_module_dynamically_callback_ == nullptr &&
          host_import_module_with_phase_dynamically_callback_ == nullptr) {
        DirectHandle<Object> exception = factory()->NewError(
            error_function(), MessageTemplate::kUnsupported);
        return NewRejectedPromise(this, api_context, exception);
      }
      break;
    case ModuleImportPhase::kSource:
      if (host_import_module_with_phase_dynamically_callback_ == nullptr) {
        DirectHandle<Object> exception = factory()->NewError(
            error_function(), MessageTemplate::kUnsupported);
        return NewRejectedPromise(this, api_context, exception);
      }
      break;
  }
  DirectHandle<String> specifier_str;
  MaybeDirectHandle<String> maybe_specifier = Object::ToString(this, specifier);
  if (!maybe_specifier.ToHandle(&specifier_str)) {
    if (is_execution_terminating()) {
      return MaybeDirectHandle<JSPromise>();
    }
    DirectHandle<Object> exception(this->exception(), this);
    clear_exception();
    return NewRejectedPromise(this, api_context, exception);
  }
  DCHECK(!has_exception());
  v8::Local<v8::Promise> promise;
  DirectHandle<FixedArray> import_attributes_array;
  if (!GetImportAttributesFromArgument(maybe_import_options_argument)
           .ToHandle(&import_attributes_array)) {
    if (is_execution_terminating()) {
      return MaybeDirectHandle<JSPromise>();
    }
    DirectHandle<Object> exception(this->exception(), this);
    clear_exception();
    return NewRejectedPromise(this, api_context, exception);
  }
  DirectHandle<FixedArray> host_defined_options;
  DirectHandle<Object> resource_name;
  if (maybe_referrer.is_null()) {
    host_defined_options = factory()->empty_fixed_array();
    resource_name = factory()->null_value();
  } else {
    DirectHandle<Script> referrer = maybe_referrer.ToHandleChecked();
    host_defined_options =
        direct_handle(referrer->host_defined_options(), this);
    resource_name = direct_handle(referrer->name(), this);
  }
  switch (phase) {
    case ModuleImportPhase::kEvaluation:
      // TODO(42204365): Deprecate HostImportModuleDynamicallyCallback once
      // HostImportModuleWithPhaseDynamicallyCallback is stable.
      if (host_import_module_with_phase_dynamically_callback_ != nullptr) {
        API_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
            this, promise,
            host_import_module_with_phase_dynamically_callback_(
                api_context, v8::Utils::ToLocal(host_defined_options),
                v8::Utils::ToLocal(resource_name),
                v8::Utils::ToLocal(specifier_str), phase,
                ToApiHandle<v8::FixedArray>(import_attributes_array)),
            MaybeDirectHandle<JSPromise>());
      } else {
        API_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
            this, promise,
            host_import_module_dynamically_callback_(
                api_context, v8::Utils::ToLocal(host_defined_options),
                v8::Utils::ToLocal(resource_name),
                v8::Utils::ToLocal(specifier_str),
                ToApiHandle<v8::FixedArray>(import_attributes_array)),
            MaybeDirectHandle<JSPromise>());
      }
      break;
    case ModuleImportPhase::kSource:
      CHECK(v8_flags.js_source_phase_imports);
      CHECK_NOT_NULL(host_import_module_with_phase_dynamically_callback_);
      API_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
          this, promise,
          host_import_module_with_phase_dynamically_callback_(
              api_context, v8::Utils::ToLocal(host_defined_options),
              v8::Utils::ToLocal(resource_name),
              v8::Utils::ToLocal(specifier_str), phase,
              ToApiHandle<v8::FixedArray>(import_attributes_array)),
          MaybeDirectHandle<JSPromise>());
      break;
    default:
      UNREACHABLE();
  }
  return v8::Utils::OpenDirectHandle(*promise);
}
References API_ASSIGN_RETURN_ON_EXCEPTION_VALUE, CHECK, CHECK_NOT_NULL, clear_exception(), v8::internal::DCHECK(), v8::internal::direct_handle(), exception(), factory(), GetImportAttributesFromArgument(), has_exception(), host_import_module_dynamically_callback_, host_import_module_with_phase_dynamically_callback_, is_execution_terminating(), v8::internal::MaybeDirectHandle< T >::is_null(), v8::kEvaluation, v8::kSource, v8::internal::kUnsupported, native_context(), v8::internal::Factory::NewError(), v8::internal::anonymous_namespace{isolate.cc}::NewRejectedPromise(), v8::Utils::OpenDirectHandle(), v8::internal::MaybeDirectHandle< T >::ToHandle(), v8::anonymous_namespace{api.cc}::ToHandle(), v8::internal::MaybeDirectHandle< T >::ToHandleChecked(), v8::Value::ToString(), v8::internal::UNREACHABLE(), and v8::internal::v8_flags.
RunHostInitializeImportMetaObjectCallback()
MaybeHandle< JSObject > v8::internal::Isolate::RunHostInitializeImportMetaObjectCallback (DirectHandle< SourceTextModule > module)
Definition at line 6816 of file isolate.cc.
                                           {
  CHECK(IsTheHole(module->import_meta(kAcquireLoad), this));
  Handle<JSObject> import_meta = factory()->NewJSObjectWithNullProto();
  if (host_initialize_import_meta_object_callback_ != nullptr) {
    v8::Local<v8::Context> api_context = v8::Utils::ToLocal(native_context());
    host_initialize_import_meta_object_callback_(
        api_context, Utils::ToLocal(Cast<Module>(module)),
        v8::Local<v8::Object>::Cast(v8::Utils::ToLocal(import_meta)));
    if (has_exception()) return {};
  }
  return import_meta;
}
References CHECK, factory(), has_exception(), host_initialize_import_meta_object_callback_, v8::kAcquireLoad, native_context(), and v8::internal::Factory::NewJSObjectWithNullProto().
Referenced by v8::internal::SourceTextModule::GetImportMeta().
RunPrepareStackTraceCallback()
MaybeDirectHandle< Object > v8::internal::Isolate::RunPrepareStackTraceCallback (DirectHandle< NativeContext > context, DirectHandle< JSObject > Error, DirectHandle< JSArray > sites)
Definition at line 6863 of file isolate.cc.
                                 {
  v8::Local<v8::Context> api_context = Utils::ToLocal(context);
  v8::Local<v8::Value> stack;
  API_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      this, stack,
      prepare_stack_trace_callback_(api_context, Utils::ToLocal(error),
                                    Utils::ToLocal(sites)),
      MaybeDirectHandle<Object>());
  return Utils::OpenDirectHandle(*stack);
}
References API_ASSIGN_RETURN_ON_EXCEPTION_VALUE, context(), v8::Utils::OpenDirectHandle(), prepare_stack_trace_callback_, and v8::internal::stack.
Referenced by v8::internal::ErrorUtils::FormatStackTrace().
RunPromiseHook()
void v8::internal::Isolate::RunPromiseHook (PromiseHookType type, DirectHandle< JSPromise > promise, DirectHandle< Object > parent)
Definition at line 6999 of file isolate.cc.
                                                          {
  if (!HasIsolatePromiseHooks()) return;
  DCHECK(promise_hook_ != nullptr);
  promise_hook_(type, v8::Utils::PromiseToLocal(promise),
                v8::Utils::ToLocal(parent));
}
References v8::internal::DCHECK(), HasIsolatePromiseHooks(), promise_hook_, and v8::internal::tracing::type.
Referenced by OnPromiseAfter(), OnPromiseBefore(), v8::internal::JSPromise::Resolve(), and RunAllPromiseHooks().
RunReleaseCppHeapCallback()
void v8::internal::Isolate::RunReleaseCppHeapCallback (std::unique_ptr< v8::CppHeap > cpp_heap)
Definition at line 6975 of file isolate.cc.
                                                                         {
  if (release_cpp_heap_callback_) {
    release_cpp_heap_callback_(std::move(cpp_heap));
  }
}
References release_cpp_heap_callback_.
Referenced by v8::internal::Heap::TearDown().
runtime_state()
RuntimeState* v8::internal::Isolate::runtime_state () [inline]
Definition at line 1456 of file isolate.h.
{ return &runtime_state_; }
Referenced by v8::internal::Runtime::RuntimeFunctionTable().
serializer_enabled()
bool v8::internal::Isolate::serializer_enabled () const [inline]
Definition at line 1575 of file isolate.h.
{ return serializer_enabled_; }
Referenced by v8::internal::IncrementalMarking::CanBeStarted(), v8::internal::Compiler::CompileOptimizedOSR(), v8::ScriptCompiler::CreateCodeCache(), v8::ScriptCompiler::CreateCodeCacheForFunction(), v8::internal::AssemblerOptions::Default(), v8::internal::ReadOnlyHeap::DeserializeIntoIsolate(), v8::internal::compiler::Pipeline::GenerateCodeForTurboshaftBuiltin(), v8::internal::Genesis::Genesis(), v8::HandleScope::Initialize(), v8::internal::Bootstrapper::InstallExtensions(), v8::internal::Heap::IterateRoots(), v8::internal::compiler::CodeAssemblerCompilationJob::ShouldOptimizeJumps(), and v8::internal::MarkCompactCollector::StartCompaction().
set_allow_atomics_wait()
void v8::internal::Isolate::set_allow_atomics_wait (bool set) [inline]
Definition at line 2170 of file isolate.h.
{ allow_atomics_wait_ = set; }
Referenced by v8::Isolate::Initialize(), and v8::Isolate::SetAllowAtomicsWait().
set_array_buffer_allocator()
void v8::internal::Isolate::set_array_buffer_allocator (v8::ArrayBuffer::Allocator * allocator) [inline]
Definition at line 1975 of file isolate.h.
                                                                     {
    array_buffer_allocator_ = allocator;
  }
Referenced by v8::Isolate::Initialize(), v8::internal::Snapshot::SerializeDeserializeAndVerifyForTesting(), and v8::internal::SnapshotCreatorImpl::SnapshotCreatorImpl().
set_array_buffer_allocator_shared()
void v8::internal::Isolate::set_array_buffer_allocator_shared (std::shared_ptr< v8::ArrayBuffer::Allocator > allocator) [inline]
Definition at line 1982 of file isolate.h.
                                                       {
    array_buffer_allocator_shared_ = std::move(allocator);
  }
Referenced by v8::Isolate::Initialize(), and v8::internal::SnapshotCreatorImpl::SnapshotCreatorImpl().
set_async_event_delegate()
void v8::internal::Isolate::set_async_event_delegate (debug::AsyncEventDelegate * delegate) [inline]
Definition at line 1062 of file isolate.h.
                                                                   {
    async_event_delegate_ = delegate;
    PromiseHookStateUpdated();
  }
set_battery_saver_mode_enabled()
void v8::internal::Isolate::set_battery_saver_mode_enabled (bool battery_saver_mode_enabled) [inline]
Definition at line 2422 of file isolate.h.
                                                                       {
    battery_saver_mode_enabled_ = battery_saver_mode_enabled;
  }
Referenced by v8::Isolate::SetBatterySaverMode().
set_builtins_effects_analyzer()
void v8::internal::Isolate::set_builtins_effects_analyzer (BuiltinsEffectsAnalyzer * builtins_effects_analyzer) [inline]
Definition at line 1462 of file isolate.h.
                                                          {
    // One of builtins_effects_analyzer_ and builtins_effects_analyzer should be
    // nullptr, but not both.
    DCHECK((builtins_effects_analyzer_ == nullptr) ^
           (builtins_effects_analyzer == nullptr));
    builtins_effects_analyzer_ = builtins_effects_analyzer;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::BuiltinsEffectsAnalyzer::Setup(), and v8::internal::BuiltinsEffectsAnalyzer::TearDown().
set_code_coverage_mode()
void v8::internal::Isolate::set_code_coverage_mode (debug::CoverageMode coverage_mode) [inline]
Definition at line 2113 of file isolate.h.
                                                               {
    code_coverage_mode_.store(coverage_mode, std::memory_order_relaxed);
  }
Referenced by v8::internal::Coverage::SelectMode().
set_compiler_utils()
void v8::internal::Isolate::set_compiler_utils (compiler::PerIsolateCompilerCache * cache, Zone * zone) [inline]
Definition at line 2013 of file isolate.h.
                                      {
    compiler_cache_ = cache;
    compiler_zone_ = zone;
  }
Referenced by v8::internal::compiler::PerIsolateCompilerCache::Setup().
set_console_delegate()
void v8::internal::Isolate::set_console_delegate (debug::ConsoleDelegate * delegate) [inline]
Definition at line 1057 of file isolate.h.
                                                            {
    console_delegate_ = delegate;
  }
Referenced by v8::debug::SetConsoleDelegate().
set_context()
void v8::internal::Isolate::set_context (Tagged< Context > context) [inline]
Definition at line 43 of file isolate-inl.h.
                                                 {
  DCHECK(context.is_null() || IsContext(context));
  thread_local_top()->context_ = context;
}
References context(), v8::internal::ThreadLocalTop::context_, v8::internal::DCHECK(), and thread_local_top().
Referenced by v8::internal::anonymous_namespace{runtime-wasm.cc}::AllocateFeedbackVector(), v8::CallDepthScope< do_callback >::CallDepthScope(), v8::internal::Genesis::CreateRoots(), v8::Context::Enter(), v8::Context::Exit(), v8::internal::Genesis::Genesis(), v8::internal::RUNTIME_FUNCTION(), v8::internal::SaveAndSwitchContext::SaveAndSwitchContext(), v8::internal::anonymous_namespace{runtime-wasm.cc}::ThrowTableOutOfBounds(), wasm::FuncData::v8_callback(), and v8::internal::SaveContext::~SaveContext().
set_current_deoptimizer()
void v8::internal::Isolate::set_current_deoptimizer (Deoptimizer * deoptimizer) [inline]
Definition at line 1336 of file isolate.h.
                                                         {
    DCHECK_NULL(current_deoptimizer_);
    DCHECK_NOT_NULL(deoptimizer);
    current_deoptimizer_ = deoptimizer;
  }
References DCHECK_NOT_NULL, and DCHECK_NULL.
Referenced by v8::internal::Deoptimizer::New().
set_date_cache()
void v8::internal::Isolate::set_date_cache (DateCache * date_cache)
Definition at line 6300 of file isolate.cc.
                                                  {
  if (date_cache != date_cache_) {
    delete date_cache_;
  }
  date_cache_ = date_cache;
}
References date_cache(), and date_cache_.
set_debug_execution_mode()
void v8::internal::Isolate::set_debug_execution_mode (DebugInfo::ExecutionMode debug_execution_mode) [inline]
Definition at line 1528 of file isolate.h.
                                                                             {
    bool check_side_effects = debug_execution_mode == DebugInfo::kSideEffects;
    isolate_data_.execution_mode_.set(
        IsolateExecutionModeFlag::kCheckSideEffects, check_side_effects);
  }
References v8::internal::kCheckSideEffects, and v8::internal::DebugInfo::kSideEffects.
Referenced by v8::internal::Debug::StartSideEffectCheckMode(), and v8::internal::Debug::StopSideEffectCheckMode().
set_deoptimizer_lazy_throw()
void v8::internal::Isolate::set_deoptimizer_lazy_throw (bool value) [inline]
Definition at line 1342 of file isolate.h.
                                              {
    deoptimizer_lazy_throw_ = value;
  }
References v8::internal::value.
Referenced by v8::internal::Deoptimizer::Deoptimizer(), and UnwindAndFindHandler().
set_elements_deletion_counter()
void v8::internal::Isolate::set_elements_deletion_counter (size_t value) [inline]
Definition at line 2182 of file isolate.h.
                                                   {
    elements_deletion_counter_ = value;
  }
References v8::internal::value.
Referenced by v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::DeleteCommon().
set_exception()
void v8::internal::Isolate::set_exception (Tagged< Object > exception_obj) [inline]
Definition at line 110 of file isolate-inl.h.
                                                        {
  DCHECK(!IsException(exception_obj, this));
  thread_local_top()->exception_ = exception_obj;
}
References v8::internal::DCHECK(), v8::internal::ThreadLocalTop::exception_, and thread_local_top().
Referenced by v8::internal::wasm::WasmInterpreterRuntime::CallWasmToJSBuiltin(), ReThrow(), v8::internal::RUNTIME_FUNCTION(), v8::AsyncHooks::ShellPromiseHook(), and Throw().
set_force_slow_path()
void v8::internal::Isolate::set_force_slow_path (bool v) [inline]
Definition at line 1787 of file isolate.h.
{ force_slow_path_ = v; }
set_memory_saver_mode_enabled()
void v8::internal::Isolate::set_memory_saver_mode_enabled (bool memory_saver_mode_enabled) [inline]
Definition at line 2426 of file isolate.h.
                                                                     {
    memory_saver_mode_enabled_ = memory_saver_mode_enabled;
  }
Referenced by v8::Isolate::SetMemorySaverMode().
set_pending_message()
void v8::internal::Isolate::set_pending_message (Tagged< Object > message_obj) [inline]
Definition at line 87 of file isolate-inl.h.
                                                            {
  DCHECK(IsTheHole(message_obj, this) || IsJSMessageObject(message_obj));
  thread_local_top()->pending_message_ = message_obj;
}
References v8::internal::DCHECK(), v8::internal::ThreadLocalTop::pending_message_, and thread_local_top().
Referenced by clear_pending_message(), ReThrow(), and Throw().
set_read_only_heap()
void v8::internal::Isolate::set_read_only_heap (ReadOnlyHeap * ro_heap) [inline]
Definition at line 682 of file isolate.h.
{ read_only_heap_ = ro_heap; }
set_regexp_static_result_offsets_vector()
void v8::internal::Isolate::set_regexp_static_result_offsets_vector (int32_t * value) [inline]
Definition at line 1478 of file isolate.h.
                                                               {
    DCHECK_EQ(value == nullptr,
              regexp_static_result_offsets_vector() != nullptr);
    isolate_data()->set_regexp_static_result_offsets_vector(value);
  }
References DCHECK_EQ, and v8::internal::value.
Referenced by v8::internal::RegExpResultVectorScope::Initialize(), and v8::internal::RegExpResultVectorScope::~RegExpResultVectorScope().
set_stack_size()
void v8::internal::Isolate::set_stack_size (size_t v) [inline]
Definition at line 1793 of file isolate.h.
{ stack_size_ = v; }
Referenced by v8::Isolate::Initialize(), and v8::Isolate::SetStackLimit().
set_thread_id()
void v8::internal::Isolate::set_thread_id (ThreadId id) [inline]
Definition at line 833 of file isolate.h.
                                         {
    thread_local_top()->thread_id_.store(id, std::memory_order_relaxed);
  }
Referenced by Deinitialize(), and Enter().
set_top_backup_incumbent_scope()
void v8::internal::Isolate::set_top_backup_incumbent_scope (const v8::Context::BackupIncumbentScope * top_backup_incumbent_scope) [inline]
Definition at line 2193 of file isolate.h.
                                                                       {
    thread_local_top()->top_backup_incumbent_scope_ =
        top_backup_incumbent_scope;
  }
Referenced by v8::Context::BackupIncumbentScope::BackupIncumbentScope(), and v8::Context::BackupIncumbentScope::~BackupIncumbentScope().
set_topmost_script_having_context()
void v8::internal::Isolate::set_topmost_script_having_context (Tagged< Context > context) [inline]
Definition at line 58 of file isolate-inl.h.
                                                                       {
  DCHECK(context.is_null() || IsContext(context));
  thread_local_top()->topmost_script_having_context_ = context;
}
References context(), v8::internal::DCHECK(), thread_local_top(), and v8::internal::ThreadLocalTop::topmost_script_having_context_.
Referenced by v8::internal::SaveContext::~SaveContext().
set_was_locker_ever_used()
void v8::internal::Isolate::set_was_locker_ever_used () [inline]
Definition at line 1772 of file isolate.h.
                                  {
    was_locker_ever_used_.store(true, std::memory_order_relaxed);
  }
Referenced by v8::Locker::Initialize().
SetAbortOnUncaughtExceptionCallback()
void v8::internal::Isolate::SetAbortOnUncaughtExceptionCallback (v8::Isolate::AbortOnUncaughtExceptionCallback callback)
Definition at line 3693 of file isolate.cc.
                                                        {
  abort_on_uncaught_exception_callback_ = callback;
}
References abort_on_uncaught_exception_callback_.
Referenced by v8::Isolate::SetAbortOnUncaughtExceptionCallback().
SetAddCrashKeyCallback()
void v8::internal::Isolate::SetAddCrashKeyCallback (AddCrashKeyCallback callback)
Definition at line 6963 of file isolate.cc.
                                                                 {
  add_crash_key_callback_ = callback;
  // Log the initial set of data.
  AddCrashKeysForIsolateAndHeapPointers();
}
References add_crash_key_callback_, and AddCrashKeysForIsolateAndHeapPointers().
Referenced by v8::Isolate::SetAddCrashKeyCallback().
SetCaptureStackTraceForUncaughtExceptions()
void v8::internal::Isolate::SetCaptureStackTraceForUncaughtExceptions (bool capture, int frame_limit, StackTrace::StackTraceOptions options)
Definition at line 3682 of file isolate.cc.
                                                                        {
  capture_stack_trace_for_uncaught_exceptions_ = capture;
  stack_trace_for_uncaught_exceptions_frame_limit_ = frame_limit;
  stack_trace_for_uncaught_exceptions_options_ = options;
}
References capture_stack_trace_for_uncaught_exceptions_, stack_trace_for_uncaught_exceptions_frame_limit_, and stack_trace_for_uncaught_exceptions_options_.
Referenced by v8::internal::wasm::gdb_server::GdbServer::DebugDelegate::DebugDelegate(), and v8::Isolate::SetCaptureStackTraceForUncaughtExceptions().
SetCodePages()
void v8::internal::Isolate::SetCodePages (std::vector< MemoryRange > * new_code_pages)
Definition at line 3142 of file isolate.cc.
                                                                 {
  code_pages_.store(new_code_pages, std::memory_order_release);
}
References code_pages_.
Referenced by AddCodeMemoryRange(), Deinit(), InitializeCodeRanges(), and RemoveCodeMemoryChunk().
SetCurrent()
void v8::internal::Isolate::SetCurrent (Isolate * isolate) [static]
Definition at line 539 of file isolate.cc.
{ g_current_isolate_ = isolate; }
Referenced by v8::internal::LocalHeap::LocalHeap(), v8::internal::SetCurrentIsolateScope::SetCurrentIsolateScope(), SetIsolateThreadLocals(), v8::internal::LocalHeap::~LocalHeap(), and v8::internal::SetCurrentIsolateScope::~SetCurrentIsolateScope().
SetData()
void v8::internal::Isolate::SetData (uint32_t slot, void * data) [inline]
Definition at line 1566 of file isolate.h.
                                          {
    DCHECK_LT(slot, Internals::kNumIsolateDataSlots);
    isolate_data_.embedder_data_[slot] = data;
  }
References DCHECK_LT, and v8::internal::Internals::kNumIsolateDataSlots.
SetDetailedSourcePositionsForProfiling()
void v8::internal::Isolate::SetDetailedSourcePositionsForProfiling (bool value) [inline]
Definition at line 1168 of file isolate.h.
                                                          {
    if (value) {
      CollectSourcePositionsForAllBytecodeArrays();
    }
    detailed_source_positions_for_profiling_ = value;
  }
References v8::internal::value.
SetEmbeddedBlob()
void v8::internal::Isolate::SetEmbeddedBlob (const uint8_t * code, uint32_t code_size, const uint8_t * data, uint32_t data_size) [private]
Definition at line 324 of file isolate.cc.
                                                                       {
  CHECK_NOT_NULL(code);
  CHECK_NOT_NULL(data);
  embedded_blob_code_ = code;
  embedded_blob_code_size_ = code_size;
  embedded_blob_data_ = data;
  embedded_blob_data_size_ = data_size;
  current_embedded_blob_code_.store(code, std::memory_order_relaxed);
  current_embedded_blob_code_size_.store(code_size, std::memory_order_relaxed);
  current_embedded_blob_data_.store(data, std::memory_order_relaxed);
  current_embedded_blob_data_size_.store(data_size, std::memory_order_relaxed);
#ifdef DEBUG
  // Verify that the contents of the embedded blob are unchanged from
  // serialization-time, just to ensure the compiler isn't messing with us.
  EmbeddedData d = EmbeddedData::FromBlob();
  if (d.EmbeddedBlobDataHash() != d.CreateEmbeddedBlobDataHash()) {
    FATAL(
        "Embedded blob data section checksum verification failed. This "
        "indicates that the embedded blob has been modified since compilation "
        "time.");
  }
  if (v8_flags.text_is_readable) {
    if (d.EmbeddedBlobCodeHash() != d.CreateEmbeddedBlobCodeHash()) {
      FATAL(
          "Embedded blob code section checksum verification failed. This "
          "indicates that the embedded blob has been modified since "
          "compilation time. A common cause is a debugging breakpoint set "
          "within builtin code.");
    }
  }
#endif // DEBUG
}
References CHECK_NOT_NULL, code, v8::internal::EmbeddedData::CreateEmbeddedBlobCodeHash(), v8::internal::EmbeddedData::CreateEmbeddedBlobDataHash(), v8::internal::anonymous_namespace{isolate.cc}::current_embedded_blob_code_(), v8::internal::anonymous_namespace{isolate.cc}::current_embedded_blob_code_size_(), v8::internal::anonymous_namespace{isolate.cc}::current_embedded_blob_data_(), v8::internal::anonymous_namespace{isolate.cc}::current_embedded_blob_data_size_(), embedded_blob_code_, embedded_blob_code_size_, embedded_blob_data_, embedded_blob_data_size_, v8::internal::EmbeddedData::EmbeddedBlobCodeHash(), v8::internal::EmbeddedData::EmbeddedBlobDataHash(), FATAL, v8::internal::EmbeddedData::FromBlob(), and v8::internal::v8_flags.
Referenced by CreateAndSetEmbeddedBlob(), and InitializeDefaultEmbeddedBlob().
SetExceptionPropagationCallback()
void v8::internal::Isolate::SetExceptionPropagationCallback (ExceptionPropagationCallback callback)
Definition at line 5125 of file isolate.cc.
                                           {
  exception_propagation_callback_ = callback;
}
Referenced by v8::Isolate::SetExceptionPropagationCallback().
SetFailedAccessCheckCallback()
void v8::internal::Isolate::SetFailedAccessCheckCallback (v8::FailedAccessCheckCallback callback)
Definition at line 1785 of file isolate.cc.
                                          {
  thread_local_top()->failed_access_check_callback_ = callback;
}
References v8::internal::ThreadLocalTop::failed_access_check_callback_, and thread_local_top().
Referenced by v8::Isolate::SetFailedAccessCheckCallbackFunction().
SetFeedbackVectorsForProfilingTools()
void v8::internal::Isolate::SetFeedbackVectorsForProfilingTools (Tagged< Object > value)
Definition at line 6262 of file isolate.cc.
                                                                      {
  DCHECK(IsUndefined(value, this) || IsArrayList(value));
  heap()->set_feedback_vectors_for_profiling_tools(value);
}
References v8::internal::DCHECK(), heap(), and v8::internal::value.
Referenced by v8::internal::FeedbackVector::AddToVectorsForProfilingTools(), v8::internal::Coverage::CollectPrecise(), MaybeInitializeVectorListFromHeap(), v8::internal::anonymous_namespace{startup-serializer.cc}::SanitizeIsolateScope::SanitizeIsolateScope(), and v8::internal::Coverage::SelectMode().
SetHostCreateShadowRealmContextCallback()
void v8::internal::Isolate::SetHostCreateShadowRealmContextCallback (HostCreateShadowRealmContextCallback callback)
Definition at line 6835 of file isolate.cc.
                                                   {
  host_create_shadow_realm_context_callback_ = callback;
}
References host_create_shadow_realm_context_callback_.
Referenced by v8::Isolate::SetHostCreateShadowRealmContextCallback().
SetHostImportModuleDynamicallyCallback()
void v8::internal::Isolate::SetHostImportModuleDynamicallyCallback (HostImportModuleDynamicallyCallback callback)
Definition at line 6806 of file isolate.cc.
                                                  {
  host_import_module_dynamically_callback_ = callback;
}
References host_import_module_dynamically_callback_.
Referenced by v8::Isolate::SetHostImportModuleDynamicallyCallback().
SetHostImportModuleWithPhaseDynamicallyCallback()
void v8::internal::Isolate::SetHostImportModuleWithPhaseDynamicallyCallback (HostImportModuleWithPhaseDynamicallyCallback callback)
Definition at line 6811 of file isolate.cc.
                                                           {
  host_import_module_with_phase_dynamically_callback_ = callback;
}
References host_import_module_with_phase_dynamically_callback_.
Referenced by v8::Isolate::SetHostImportModuleWithPhaseDynamicallyCallback().
SetHostInitializeImportMetaObjectCallback()
void v8::internal::Isolate::SetHostInitializeImportMetaObjectCallback (HostInitializeImportMetaObjectCallback callback)
Definition at line 6830 of file isolate.cc.
                                                     {
  host_initialize_import_meta_object_callback_ = callback;
}
References host_initialize_import_meta_object_callback_.
Referenced by v8::Isolate::SetHostInitializeImportMetaObjectCallback().
SetIdle()
void v8::internal::Isolate::SetIdle (bool is_idle)
Definition at line 7298 of file isolate.cc.
                                  {
  StateTag state = current_vm_state();
  if (js_entry_sp() != kNullAddress) return;
  DCHECK(state == EXTERNAL || state == IDLE);
  if (is_idle) {
    set_current_vm_state(IDLE);
  } else if (state == IDLE) {
    set_current_vm_state(EXTERNAL);
  }
}
References v8::internal::DCHECK(), v8::EXTERNAL, v8::IDLE, js_entry_sp(), and v8::internal::kNullAddress.
Referenced by v8::Isolate::SetIdle().
SetIsLoading()
void v8::internal::Isolate::SetIsLoading (bool is_loading)
Definition at line 7264 of file isolate.cc.
                                          {
  if (is_loading) {
    heap()->NotifyLoadingStarted();
  } else {
    heap()->NotifyLoadingEnded();
  }
  if (v8_flags.trace_rail) {
    // TODO(crbug.com/373688984): Switch to a trace flag for loading state.
    PrintIsolate(this, "RAIL mode: %s\n", is_loading ? "LOAD" : "ANIMATION");
  }
}
References heap(), v8::internal::Heap::NotifyLoadingEnded(), v8::internal::Heap::NotifyLoadingStarted(), v8::internal::PrintIsolate(), and v8::internal::v8_flags.
Referenced by v8::Isolate::SetIsLoading().
SetIsolateThreadLocals()
void v8::internal::Isolate::SetIsolateThreadLocals (Isolate * isolate, PerIsolateThreadData * data) [static], [private]
Definition at line 4732 of file isolate.cc.
                                                                 {
  Isolate::SetCurrent(isolate);
  g_current_per_isolate_thread_data_ = data;
#ifdef V8_COMPRESS_POINTERS_IN_MULTIPLE_CAGES
  V8HeapCompressionScheme::InitBase(isolate ? isolate->cage_base()
                                            : kNullAddress);
  IsolateGroup::set_current(isolate ? isolate->isolate_group() : nullptr);
#ifdef V8_EXTERNAL_CODE_SPACE
  ExternalCodeCompressionScheme::InitBase(isolate ? isolate->code_cage_base()
                                                  : kNullAddress);
#endif
#ifdef V8_ENABLE_SANDBOX
  Sandbox::set_current(isolate ? isolate->isolate_group()->sandbox() : nullptr);
#endif
#endif // V8_COMPRESS_POINTERS_IN_MULTIPLE_CAGES
  if (isolate && isolate->main_thread_local_isolate()) {
    WriteBarrier::SetForThread(
        isolate->main_thread_local_heap()->marking_barrier());
  } else {
    WriteBarrier::SetForThread(nullptr);
  }
}
References cage_base(), code_cage_base(), v8::internal::V8HeapCompressionSchemeImpl< Cage >::InitBase(), v8::internal::Factory::isolate(), isolate_group(), v8::internal::kNullAddress, main_thread_local_heap(), main_thread_local_isolate(), v8::internal::LocalHeap::marking_barrier(), SetCurrent(), and v8::internal::WriteBarrier::SetForThread().
Referenced by Deinitialize(), Enter(), Exit(), and Init().
SetIsProfiling()
void v8::internal::Isolate::SetIsProfiling (bool enabled) [inline]
Definition at line 1507 of file isolate.h.
                                    {
    if (enabled) {
      CollectSourcePositionsForAllBytecodeArrays();
      RequestInvalidateNoProfilingProtector();
    }
    isolate_data_.execution_mode_.set(IsolateExecutionModeFlag::kIsProfiling,
                                      enabled);
    UpdateLogObjectRelocation();
  }
References v8::internal::kIsProfiling.
Referenced by v8::internal::ProfilingScope::ProfilingScope(), and v8::internal::ProfilingScope::~ProfilingScope().
SetOptimizingCompileDispatcherForTesting()
OptimizingCompileDispatcher * v8::internal::Isolate::SetOptimizingCompileDispatcherForTesting (OptimizingCompileDispatcher * dispatcher)
Definition at line 6070 of file isolate.cc.
                                             {
  return std::exchange(optimizing_compile_dispatcher_, dispatcher);
}
References optimizing_compile_dispatcher_.
SetPrepareStackTraceCallback()
void v8::internal::Isolate::SetPrepareStackTraceCallback (PrepareStackTraceCallback callback)
Definition at line 6922 of file isolate.cc.
                                                                             {
  prepare_stack_trace_callback_ = callback;
}
References prepare_stack_trace_callback_.
Referenced by v8::Isolate::SetPrepareStackTraceCallback().
SetPriority()
void v8::internal::Isolate::SetPriority (v8::Isolate::Priority priority)
Definition at line 7276 of file isolate.cc.
                                                    {
  priority_ = priority;
  heap()->tracer()->UpdateCurrentEventPriority(priority_);
  if (priority_ == v8::Isolate::Priority::kBestEffort) {
    heap()->ActivateMemoryReducerIfNeeded();
  }
}
References v8::internal::Heap::ActivateMemoryReducerIfNeeded(), heap(), v8::Isolate::kBestEffort, priority(), priority_, v8::internal::Heap::tracer(), and v8::internal::GCTracer::UpdateCurrentEventPriority().
Referenced by v8::Isolate::SetPriority().
SetPromiseHook()
void v8::internal::Isolate::SetPromiseHook (PromiseHook hook)
Definition at line 6981 of file isolate.cc.
                                             {
  promise_hook_ = hook;
  PromiseHookStateUpdated();
}
References promise_hook_, and PromiseHookStateUpdated().
Referenced by v8::Isolate::SetPromiseHook().
SetPromiseRejectCallback()
void v8::internal::Isolate::SetPromiseRejectCallback (PromiseRejectCallback callback)
Definition at line 7136 of file isolate.cc.
                                                                     {
  promise_reject_callback_ = callback;
}
Referenced by v8::Isolate::SetPromiseRejectCallback().
SetReleaseCppHeapCallback()
void v8::internal::Isolate::SetReleaseCppHeapCallback (v8::Isolate::ReleaseCppHeapCallback callback)
Definition at line 6970 of file isolate.cc.
                                              {
  release_cpp_heap_callback_ = callback;
}
References release_cpp_heap_callback_.
Referenced by v8::Isolate::SetReleaseCppHeapCallbackForTesting().
SetTerminationOnExternalTryCatch()
void v8::internal::Isolate::SetTerminationOnExternalTryCatch ()
Definition at line 4856 of file isolate.cc.
                                               {
  DCHECK_IMPLIES(v8_flags.strict_termination_checks,
                 is_execution_terminating());
  if (try_catch_handler() == nullptr) return;
  try_catch_handler()->can_continue_ = false;
  try_catch_handler()->exception_ = reinterpret_cast<void*>(
      ReadOnlyRoots(heap()).termination_exception().ptr());
}
References v8::TryCatch::can_continue_, DCHECK_IMPLIES, v8::TryCatch::exception_, heap(), is_execution_terminating(), try_catch_handler(), and v8::internal::v8_flags.
Referenced by OnTerminationDuringRunMicrotasks(), and PropagateExceptionToExternalTryCatch().
SetUpFromReadOnlyArtifacts()
void v8::internal::Isolate::SetUpFromReadOnlyArtifacts (ReadOnlyArtifacts * artifacts)
Definition at line 4227 of file isolate.cc.
                                                                     {
  DCHECK_NOT_NULL(artifacts);
  InitializeNextUniqueSfiId(artifacts->initial_next_unique_sfi_id());
  DCHECK_NOT_NULL(artifacts->read_only_heap());
  DCHECK_IMPLIES(read_only_heap_ != nullptr,
                 read_only_heap_ == artifacts->read_only_heap());
  read_only_heap_ = artifacts->read_only_heap();
  heap_.SetUpFromReadOnlyHeap(read_only_heap_);
}
References DCHECK_IMPLIES, DCHECK_NOT_NULL, heap_, v8::internal::ReadOnlyArtifacts::initial_next_unique_sfi_id(), InitializeNextUniqueSfiId(), v8::internal::ReadOnlyArtifacts::read_only_heap(), read_only_heap_, and v8::internal::Heap::SetUpFromReadOnlyHeap().
Referenced by v8::internal::ReadOnlyHeap::CreateInitialHeapForBootstrapping(), and v8::internal::ReadOnlyHeap::SetUp().
SetUseCounterCallback()
void v8::internal::Isolate::SetUseCounterCallback (v8::Isolate::UseCounterCallback callback)
Definition at line 7148 of file isolate.cc.
                                                                        {
  DCHECK(!use_counter_callback_);
  use_counter_callback_ = callback;
}
References v8::internal::DCHECK(), and use_counter_callback_.
shared_function_info_access()
base::Mutex* v8::internal::Isolate::shared_function_info_access () [inline]
Definition at line 770 of file isolate.h.
                                           {
    return &shared_function_info_access_;
  }
Referenced by v8::internal::DebugInfoCollection::DeleteIndex(), v8::internal::DebugInfoCollection::Insert(), v8::internal::SharedFunctionInfo::InstallDebugBytecode(), and v8::internal::SharedFunctionInfo::UninstallDebugBytecode().
shared_heap_object_cache()
std::vector<Tagged<Object> >* v8::internal::Isolate::shared_heap_object_cache () [inline]
Definition at line 1929 of file isolate.h.
                                                        {
    if (OwnsStringTables()) {
      return &shared_heap_object_cache_;
    } else {
      return &shared_space_isolate()->shared_heap_object_cache_;
    }
  }
Referenced by v8::internal::SerializerDeserializer::IterateSharedHeapObjectCache(), v8::internal::SharedHeapSerializer::ReconstructSharedHeapObjectCacheForTesting(), and v8::internal::SharedHeapSerializer::SerializeUsingSharedHeapObjectCache().
shared_space_isolate()
Isolate* v8::internal::Isolate::shared_space_isolate () const [inline]
Definition at line 2335 of file isolate.h.
                                        {
    DCHECK(has_shared_space());
    Isolate* isolate = shared_space_isolate_.value();
    DCHECK(has_shared_space());
    return isolate;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::MarkingBarrier::ActivateShared(), v8::internal::Heap::CanReferenceHeapObject(), v8::internal::Heap::CollectGarbageShared(), Deinit(), v8::internal::GlobalSafepoint::EnterGlobalSafepointScope(), v8::internal::Sweeper::FinishMajorJobs(), v8::internal::Sweeper::FinishMinorJobs(), v8::internal::HeapAllocator::heap_for_allocation(), Init(), v8::internal::MarkCompactCollector::IsUnmarkedSharedHeapObject(), v8::internal::Heap::IterateConservativeStackRoots(), v8::internal::String::MakeExternal(), v8::internal::Map::MapPrint(), v8::internal::SharedHeapSerializer::ReconstructSharedHeapObjectCacheForTesting(), v8::internal::Sweeper::MajorSweeperJob::Run(), v8::internal::Sweeper::MinorSweeperJob::Run(), v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::Run(), v8::internal::SharedHeapSerializer::SerializeUsingSharedHeapObjectCache(), v8::internal::LocalHeap::SetUpSharedMarking(), v8::internal::Heap::SetUpSpaces(), v8::internal::IsolateSafepoint::shared_space_isolate(), v8::internal::IncrementalMarking::Stop(), and v8::internal::MarkingBarrier::Write().
shared_struct_type_registry()
SharedStructTypeRegistry* v8::internal::Isolate::shared_struct_type_registry () const [inline]
Definition at line 806 of file isolate.h.
                                                                {
    return is_shared_space_isolate()
               ? shared_struct_type_registry_.get()
               : shared_space_isolate()->shared_struct_type_registry_.get();
  }
Referenced by v8::internal::MarkCompactCollector::ClearNonLiveReferences(), v8::internal::anonymous_namespace{mark-compact.cc}::ClearSharedStructTypeRegistryJobItem::ClearSharedStructTypeRegistryJobItem(), Init(), and v8::internal::Heap::IterateWeakRoots().
should_check_side_effects()
bool v8::internal::Isolate::should_check_side_effects () const [inline]
Definition at line 1519 of file isolate.h.
                                         {
    return isolate_data_.execution_mode_ &
           IsolateExecutionModeFlag::kCheckSideEffects;
  }
References v8::internal::kCheckSideEffects.
Referenced by v8::internal::FunctionCallbackArguments::CallOrConstruct(), v8::internal::InvokeAccessorGetterCallback(), v8::internal::anonymous_namespace{api.cc}::InvokeFunctionCallback(), v8::Function::NewInstanceWithSideEffectType(), and v8::internal::anonymous_namespace{execution.cc}::NewScriptContext().
SignalFatalError()
void v8::internal::Isolate::SignalFatalError () [inline]
Definition at line 1584 of file isolate.h.
{ has_fatal_error_ = true; }
Referenced by v8::Utils::ReportApiFailure(), and v8::Utils::ReportOOMFailure().
snapshot_available()
bool v8::internal::Isolate::snapshot_available () const [inline]
Definition at line 1579 of file isolate.h.
                                  {
    return snapshot_blob_ != nullptr && snapshot_blob_->raw_size != 0;
  }
Referenced by v8::internal::Snapshot::Initialize(), and v8::internal::Snapshot::NewContextFromSnapshot().
stack_guard()
StackGuard* v8::internal::Isolate::stack_guard () [inline]
Definition at line 1213 of file isolate.h.
{ return isolate_data()->stack_guard(); }
Referenced by v8::internal::IncrementalMarking::AdvanceOnAllocation(), v8::internal::CollectionBarrier::AwaitCollectionBackground(), v8::internal::anonymous_namespace{runtime-internal.cc}::BytecodeBudgetInterruptWithStackCheck(), v8::Isolate::CancelTerminateExecution(), wasm::CheckAndHandleInterrupts(), v8::internal::NativeRegExpMacroAssembler::CheckStackGuardState(), v8::internal::Compiler::CollectSourcePositions(), v8::internal::Deoptimizer::DoComputeOutputFrames(), v8::internal::ThreadManager::EagerlyArchiveThread(), v8::internal::ThreadManager::FreeThreadResources(), v8::internal::wasm::grow_stack(), v8::internal::anonymous_namespace{regexp-interpreter.cc}::HandleInterrupts(), v8::internal::StackLimitCheck::HandleStackOverflowAndTerminationRequest(), v8::internal::StackLimitCheck::HasOverflowed(), Init(), v8::Isolate::Initialize(), v8::internal::IsolateSafepoint::InitiateGlobalSafepointScopeRaw(), v8::internal::ThreadManager::InitThread(), v8::internal::StackLimitCheck::InterruptRequested(), v8::internal::InterruptsScope::InterruptsScope(), v8::internal::StackLimitCheck::JsHasOverflowed(), v8::internal::wasm::WasmEngine::LogCode(), v8::internal::wasm::WasmEngine::LogWrapperCode(), v8::internal::Heap::MemoryPressureNotification(), v8::internal::Debug::OnThrow(), v8::internal::RegExpParser::ParseRegExpFromHeapString(), v8::internal::PretenuringHandler::ProcessPretenuringFeedback(), v8::internal::OptimizingCompileDispatcher::QueueFinishedJob(), v8::internal::MinorMarkSweepCollector::RequestGC(), RequestInterrupt(), v8::internal::Heap::ResetAllAllocationSitesDependentCode(), v8::internal::ThreadManager::RestoreThread(), v8::internal::anonymous_namespace{tracing-cpu-profiler.cc}::RunInterruptsTask::Run(), v8::internal::baseline::ConcurrentBaselineCompiler::JobDispatcher::Run(), v8::internal::maglev::MaglevConcurrentDispatcher::JobTask::Run(), v8::internal::IncrementalMarkingJob::Task::RunInternal(), v8::internal::RUNTIME_FUNCTION(), v8::internal::JsonStringifier::Serialize_(), v8::internal::JsonStringifier::SerializeFixedArrayWithInterruptCheck(), v8::Isolate::SetStackLimit(), v8::internal::wasm::shrink_stack(), StackOverflow(), v8::internal::Heap::StartIncrementalMarkingIfAllocationLimitIsReached(), v8::internal::StressScavengeObserver::Step(), v8::internal::IncrementalMarking::Stop(), v8::internal::wasm::switch_from_the_central_stack(), v8::internal::wasm::switch_from_the_central_stack_for_js(), v8::internal::wasm::switch_to_the_central_stack(), v8::internal::wasm::switch_to_the_central_stack_for_js(), v8::Isolate::TerminateExecution(), v8::internal::wasm::WasmEngine::TriggerGC(), UnwindAndFindHandler(), v8::internal::FutexEmulation::WaitSync(), v8::internal::StackLimitCheck::WasmHasOverflowed(), v8::internal::wasm::WasmInterpreterRuntime::WasmStackCheck(), and v8::internal::DebugScope::~DebugScope().
stack_size()
size_t v8::internal::Isolate::stack_size () [inline]
Definition at line 1794 of file isolate.h.
{ return stack_size_; }
StackOverflow()
Tagged< Object > v8::internal::Isolate::StackOverflow ()
Definition at line 1871 of file isolate.cc.
                                      {
  // Whoever calls this method should not have overflown the stack limit by too
  // much. Otherwise we risk actually running out of stack space.
  // We allow for up to 8kB overflow, because we typically allow up to 4KB
  // overflow per frame in generated code, but might call through more smaller
  // frames until we reach this method.
  // If this DCHECK fails, one of the frames on the stack should be augmented by
  // an additional stack check.
#if defined(V8_USE_ADDRESS_SANITIZER) || defined(MEMORY_SANITIZER)
  // Allow for a bit more overflow in sanitizer builds, because C++ frames take
  // significantly more space there.
  DCHECK_GE(GetCurrentStackPosition(), stack_guard()->real_climit() - 64 * KB);
#elif (defined(V8_TARGET_ARCH_RISCV64) || defined(V8_TARGET_ARCH_RISCV32)) && \
    defined(USE_SIMULATOR)
  // Allow for more overflow on riscv simulator, because C++ frames take more
  // there.
  DCHECK_GE(GetCurrentStackPosition(), stack_guard()->real_climit() - 12 * KB);
#elif defined(ENABLE_SLOW_DCHECKS) && V8_HAS_ATTRIBUTE_TRIVIAL_ABI
  // In this configuration, direct handles are not trivially copyable. This
  // prevents some C++ compiler optimizations and uses more stack space.
  DCHECK_GE(GetCurrentStackPosition(), stack_guard()->real_climit() - 10 * KB);
#else
  DCHECK_GE(GetCurrentStackPosition(), stack_guard()->real_climit() - 8 * KB);
#endif
  if (v8_flags.correctness_fuzzer_suppressions) {
    FATAL("Aborting on stack overflow");
  }
#if USE_SIMULATOR
  // Adjust the stack limit back to the real limit in case it was temporarily
  // modified to reflect an overflow in the C stack (see
  // AdjustStackLimitForSimulator).
  stack_guard()->ResetStackLimitForSimulator();
#endif
  DisallowJavascriptExecution no_js(this);
  HandleScope scope(this);
  DirectHandle<JSFunction> fun = range_error_function();
  DirectHandle<Object> msg = factory()->NewStringFromAsciiChecked(
      MessageFormatter::TemplateString(MessageTemplate::kStackOverflow));
  DirectHandle<Object> options = factory()->undefined_value();
  DirectHandle<Object> no_caller;
  DirectHandle<JSObject> exception;
  ASSIGN_RETURN_FAILURE_ON_EXCEPTION(
      this, exception,
      ErrorUtils::Construct(this, fun, fun, msg, options, SKIP_NONE, no_caller,
                            ErrorUtils::StackTraceCollection::kEnabled));
  JSObject::AddProperty(this, exception, factory()->wasm_uncatchable_symbol(),
                        factory()->true_value(), NONE);
  Throw(*exception);
#ifdef VERIFY_HEAP
  if (v8_flags.verify_heap && v8_flags.stress_compaction) {
    heap()->CollectAllGarbage(GCFlag::kNoFlags,
                              GarbageCollectionReason::kTesting);
  }
#endif // VERIFY_HEAP
  return ReadOnlyRoots(heap()).exception();
}
References v8::internal::JSObject::AddProperty(), ASSIGN_RETURN_FAILURE_ON_EXCEPTION, v8::internal::Heap::CollectAllGarbage(), v8::internal::ErrorUtils::Construct(), DCHECK_GE, exception(), factory(), FATAL, v8::internal::GetCurrentStackPosition(), heap(), v8::internal::KB, v8::internal::ErrorUtils::kEnabled, v8::internal::kNoFlags, v8::internal::kTesting, v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), v8::internal::NONE, v8::internal::SKIP_NONE, stack_guard(), v8::internal::MessageFormatter::TemplateString(), Throw(), and v8::internal::v8_flags.
Referenced by v8::internal::PrototypeIterator::AdvanceFollowingProxiesIgnoringAccessChecks(), v8::internal::wasm::WasmInterpreterRuntime::BeginExecution(), v8::internal::anonymous_namespace{runtime-internal.cc}::BytecodeBudgetInterruptWithStackCheck(), v8::internal::NativeRegExpMacroAssembler::CheckStackGuardState(), v8::internal::Compiler::CompileSharedWithBaseline(), v8::internal::NativeRegExpMacroAssembler::Execute(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteFunction(), v8::Shell::ExecuteString(), v8::internal::anonymous_namespace{compiler.cc}::FailWithPreparedException(), v8::internal::Object::GetPropertyWithDefinedGetter(), v8::internal::StackLimitCheck::HandleStackOverflowAndTerminationRequest(), v8::internal::anonymous_namespace{execution.cc}::Invoke(), v8::internal::JSProxy::IsArray(), v8::internal::Intl::NumberToLocaleString(), v8::internal::wasm::WasmInterpreterRuntime::PrepareTailCall(), v8::internal::RUNTIME_FUNCTION(), v8::internal::JsonStringifier::StackPush(), v8::internal::anonymous_namespace{runtime-literals.cc}::JSObjectWalkVisitor< ContextObject >::StructureWalk(), v8::internal::anonymous_namespace{regexp-interpreter.cc}::ThrowStackOverflow(), and v8::internal::wasm::WasmInterpreterRuntime::WasmStackCheck().
StackTraceString()
DirectHandle< String > v8::internal::Isolate::StackTraceString ()
Definition at line 674 of file isolate.cc.
                                               {
  if (stack_trace_nesting_level_ == 0) {
    stack_trace_nesting_level_++;
    HeapStringAllocator allocator;
    StringStream::ClearMentionedObjectCache(this);
    StringStream accumulator(&allocator);
    incomplete_message_ = &accumulator;
    PrintStack(&accumulator);
    DirectHandle<String> stack_trace = accumulator.ToString(this);
    incomplete_message_ = nullptr;
    stack_trace_nesting_level_ = 0;
    return stack_trace;
  } else if (stack_trace_nesting_level_ == 1) {
    stack_trace_nesting_level_++;
    base::OS::PrintError(
        "\n\nAttempt to print stack while printing stack (double fault)\n");
    base::OS::PrintError(
        "If you are lucky you may find a partial stack dump on stdout.\n\n");
    incomplete_message_->OutputToStdOut();
    return factory()->empty_string();
  } else {
    base::OS::Abort();
  }
}
References v8::base::OS::Abort(), allocator(), v8::internal::StringStream::ClearMentionedObjectCache(), factory(), incomplete_message_, v8::internal::StringStream::OutputToStdOut(), PrintStack(), stack_trace_nesting_level_, and v8::internal::StringStream::ToString().
startup_object_cache()
std::vector<Tagged<Object> >* v8::internal::Isolate::startup_object_cache () [inline]
Definition at line 1922 of file isolate.h.
                                                    {
    return &startup_object_cache_;
  }
Referenced by v8::internal::SerializerDeserializer::IterateStartupObjectCache().
store_stub_cache()
StubCache* v8::internal::Isolate::store_stub_cache () const [inline]
Definition at line 1328 of file isolate.h.
{ return store_stub_cache_; }
Referenced by v8::internal::ExternalReferenceTable::AddStubCache(), v8::internal::anonymous_namespace{heap.cc}::ClearStubCaches(), v8::internal::IC::stub_cache(), and v8::internal::AccessorAssembler::StoreICParameters::stub_cache().
store_to_stack_count_address()
Address v8::internal::Isolate::store_to_stack_count_address (const char * function_name) [static]
Definition at line 7671 of file isolate.cc.
                                                                       {
  DCHECK_NOT_NULL(function_name);
  if (!stack_access_count_map) {
    stack_access_count_map = new MapOfLoadsAndStoresPerFunction{};
  }
  auto& map = *stack_access_count_map;
  std::string name(function_name);
  // It is safe to return the address of std::map values.
  // Only iterators and references to the erased elements are invalidated.
  return reinterpret_cast<Address>(&map[name].second);
}
References DCHECK_NOT_NULL, v8::internal::name, v8::internal::anonymous_namespace{isolate.cc}::stack_access_count_map, and v8::internal::string.
Referenced by v8::internal::ExternalReference::address_of_store_to_stack_count().
stress_deopt_count_address()
uint64_t* v8::internal::Isolate::stress_deopt_count_address () [inline]
Definition at line 1785 of file isolate.h.
{ return &stress_deopt_count_; }
string_forwarding_table()
StringForwardingTable* v8::internal::Isolate::string_forwarding_table () const [inline]
Definition at line 800 of file isolate.h.
                                                         {
    return OwnsStringTables()
               ? string_forwarding_table_.get()
               : shared_space_isolate()->string_forwarding_table_.get();
  }
Referenced by Deinit(), v8::internal::StringForwardingTable::GetForwardStringAddress(), v8::internal::Name::GetRawHashFromForwardingTable(), v8::internal::StringForwardingTable::GetRawHashStatic(), Init(), v8::internal::StringTable::LookupString(), v8::internal::anonymous_namespace{string-table.cc}::SetInternalizedReference(), and v8::internal::StringTable::Data::TryStringToIndexOrLookupExisting().
string_table()
StringTable* v8::internal::Isolate::string_table () const [inline]
Definition at line 796 of file isolate.h.
                                    {
    return OwnsStringTables() ? string_table_.get()
                              : shared_space_isolate()->string_table_.get();
  }
Referenced by v8::internal::Heap::CreateImportantReadOnlyObjects(), v8::internal::SharedHeapDeserializer::DeserializeStringTable(), v8::Isolate::GetHeapStatistics(), Init(), v8::internal::Heap::IterateWeakRoots(), v8::internal::SharedHeapSerializer::SerializeStringTable(), and v8::internal::StringTable::Data::TryStringToIndexOrLookupExisting().
SymbolFor()
DirectHandle< Symbol > v8::internal::Isolate::SymbolFor (RootIndex dictionary_index, Handle< String > name, bool private_symbol)
Definition at line 6461 of file isolate.cc.
                                                             {
  DirectHandle<String> key = factory()->InternalizeString(name);
  Handle<RegisteredSymbolTable> dictionary =
      Cast<RegisteredSymbolTable>(root_handle(dictionary_index));
  InternalIndex entry = dictionary->FindEntry(this, key);
  DirectHandle<Symbol> symbol;
  if (entry.is_not_found()) {
    symbol =
        private_symbol ? factory()->NewPrivateSymbol() : factory()->NewSymbol();
    symbol->set_description(*key);
    dictionary = RegisteredSymbolTable::Add(this, dictionary, key, symbol);
    switch (dictionary_index) {
      case RootIndex::kPublicSymbolTable:
        symbol->set_is_in_public_symbol_table(true);
        heap()->set_public_symbol_table(*dictionary);
        break;
      case RootIndex::kApiSymbolTable:
        heap()->set_api_symbol_table(*dictionary);
        break;
      case RootIndex::kApiPrivateSymbolTable:
        heap()->set_api_private_symbol_table(*dictionary);
        break;
      default:
        UNREACHABLE();
    }
  } else {
    symbol =
        DirectHandle<Symbol>(Cast<Symbol>(dictionary->ValueAt(entry)), this);
  }
  return symbol;
}
References v8::internal::RegisteredSymbolTable::Add(), factory(), heap(), v8::internal::Factory::InternalizeString(), v8::internal::InternalIndex::is_not_found(), v8::internal::key, v8::internal::name, v8::internal::Factory::NewPrivateSymbol(), v8::internal::Factory::NewSymbol(), root_handle(), and v8::internal::UNREACHABLE().
Referenced by v8::Symbol::For(), v8::Symbol::ForApi(), and v8::Private::ForApi().
task_runner()
std::shared_ptr<v8::TaskRunner> v8::internal::Isolate::task_runner () const [inline]
Definition at line 2471 of file isolate.h.
{ return task_runner_; }
TearDownEmbeddedBlob()
void v8::internal::Isolate::TearDownEmbeddedBlob () [private]
Definition at line 5290 of file isolate.cc.
                                   {
  // Nothing to do in case the blob is embedded into the binary or unset.
  if (StickyEmbeddedBlobCode() == nullptr) return;
  if (!is_short_builtin_calls_enabled()) {
    CHECK_EQ(embedded_blob_code(), StickyEmbeddedBlobCode());
    CHECK_EQ(embedded_blob_data(), StickyEmbeddedBlobData());
  }
  CHECK_EQ(CurrentEmbeddedBlobCode(), StickyEmbeddedBlobCode());
  CHECK_EQ(CurrentEmbeddedBlobData(), StickyEmbeddedBlobData());
  base::MutexGuard guard(current_embedded_blob_refcount_mutex_.Pointer());
  current_embedded_blob_refs_--;
  if (current_embedded_blob_refs_ == 0 && enable_embedded_blob_refcounting_) {
    // We own the embedded blob and are the last holder. Free it.
    OffHeapInstructionStream::FreeOffHeapOffHeapInstructionStream(
        const_cast<uint8_t*>(CurrentEmbeddedBlobCode()),
        embedded_blob_code_size(),
        const_cast<uint8_t*>(CurrentEmbeddedBlobData()),
        embedded_blob_data_size());
    ClearEmbeddedBlob();
  }
}
References CHECK_EQ, ClearEmbeddedBlob(), v8::internal::anonymous_namespace{isolate.cc}::current_embedded_blob_refcount_mutex_, v8::internal::anonymous_namespace{isolate.cc}::current_embedded_blob_refs_, CurrentEmbeddedBlobCode(), CurrentEmbeddedBlobData(), embedded_blob_code(), embedded_blob_code_size(), embedded_blob_data(), embedded_blob_data_size(), v8::internal::anonymous_namespace{isolate.cc}::enable_embedded_blob_refcounting_, v8::internal::OffHeapInstructionStream::FreeOffHeapOffHeapInstructionStream(), is_short_builtin_calls_enabled(), v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Pointer(), v8::internal::anonymous_namespace{isolate.cc}::StickyEmbeddedBlobCode(), and v8::internal::anonymous_namespace{isolate.cc}::StickyEmbeddedBlobData().
Referenced by Deinit().
TerminateExecution()
Tagged< Object > v8::internal::Isolate::TerminateExecution ()
Definition at line 1959 of file isolate.cc.
                                           {
  return Throw(ReadOnlyRoots(this).termination_exception());
}
References Throw().
Referenced by v8::internal::BigInt::Divide(), v8::internal::StackGuard::HandleInterrupts(), v8::internal::StackLimitCheck::HandleStackOverflowAndTerminationRequest(), v8::internal::BigInt::Multiply(), v8::internal::Debug::OnThrow(), v8::internal::Debug::PerformSideEffectCheck(), v8::internal::Debug::PerformSideEffectCheckAtBytecode(), v8::internal::Debug::PerformSideEffectCheckForAccessor(), v8::internal::Debug::PerformSideEffectCheckForCallback(), v8::internal::Debug::PerformSideEffectCheckForInterceptor(), v8::internal::Debug::PerformSideEffectCheckForObject(), v8::internal::BigInt::Remainder(), v8::internal::Terminate(), v8::Shell::TerminateNow(), v8::internal::BigInt::ToString(), and v8::internal::wasm::WasmInterpreterRuntime::WasmStackCheck().
thread_id()
ThreadId v8::internal::Isolate::thread_id () const [inline]
Definition at line 836 of file isolate.h.
                                    {
    return thread_local_top()->thread_id_.load(std::memory_order_relaxed);
  }
Referenced by v8::internal::BuiltinsConstantsTableBuilder::AddObject(), v8::internal::AstStringConstants::AstStringConstants(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Check(), v8::internal::Compiler::CollectSourcePositions(), v8::internal::Compiler::Compile(), v8::internal::compiler::CodeAssembler::BuiltinCompilationScheduler::CompileCode(), v8::internal::anonymous_namespace{compiler.cc}::CompileToplevel(), v8::internal::HandleScope::CreateHandle(), CurrentLocalHeap(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Dcheck(), v8::internal::JSObject::DictionaryPropertyAt(), DiscardPerThreadDataForThisThread(), Enter(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::FailAssert(), v8::internal::UnoptimizedCompilationJob::FinalizeJob(), v8::internal::OptimizedCompilationJob::FinalizeJob(), FindOrAllocatePerThreadDataForThisThread(), FindPerThreadDataForThisThread(), FindPerThreadDataForThread(), v8::internal::FlatStringReader::FlatStringReader(), v8::internal::ExternalOneByteString::GetChars(), v8::internal::ExternalTwoByteString::GetChars(), v8::internal::OptimizingCompileDispatcher::HasJobs(), v8::internal::Heap::IsMainThread(), v8::internal::Isolate::ThreadDataTable::Lookup(), v8::Isolate::MemoryPressureNotification(), v8::internal::MutexGuardIfOffThread< Isolate >::MutexGuardIfOffThread(), v8::internal::OptimizedCompilationJob::PrepareJob(), v8::internal::OptimizingCompileInputQueue::Prioritize(), v8::internal::TransitionsAccessor::PutPrototypeTransition(), v8::internal::CpuProfilesCollection::RemoveProfile(), v8::internal::BackgroundCompileTask::Run(), v8::internal::SetupIsolateDelegate::SetupBuiltinsInternal(), v8::internal::compiler::JSHeapBroker::StackHasOverflowed(), and v8::internal::VMStateIfMainThread< tag >::VMStateIfMainThread().
thread_in_wasm_flag_address_offset()
static constexpr uint32_t v8::internal::Isolate::thread_in_wasm_flag_address_offset () [inline], [static], [constexpr]
Definition at line 1353 of file isolate.h.
                                                                 {
    // For WebAssembly trap handlers there is a flag in thread-local storage
    // which indicates that the executing thread executes WebAssembly code. To
    // access this flag directly from generated code, we store a pointer to the
    // flag in ThreadLocalTop in thread_in_wasm_flag_address_. This function
    // here returns the offset of that member from {isolate_root()}.
    return static_cast<uint32_t>(
        OFFSET_OF(Isolate, isolate_data_) +
        OFFSET_OF(IsolateData, thread_local_top_) +
        OFFSET_OF(ThreadLocalTop, thread_in_wasm_flag_address_) -
        isolate_root_bias());
  }
References OFFSET_OF.
Referenced by v8::internal::compiler::WasmGraphBuilder::BuildModifyThreadInWasmFlag(), v8::internal::wasm::WasmGraphBuilderBase::BuildModifyThreadInWasmFlag(), v8::internal::compiler::turboshaft::WasmInJSInliningReducer< Next >::Call(), v8::internal::anonymous_namespace{builtins-riscv.cc}::GenerateExceptionHandlingLandingPad(), v8::internal::anonymous_namespace{builtins-riscv.cc}::JSToWasmWrapperHelper(), v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::ModifyThreadInWasmFlagScope::ModifyThreadInWasmFlagScope(), and v8::internal::wasm::WasmWrapperTSGraphBuilder::ModifyThreadInWasmFlagScope::ModifyThreadInWasmFlagScope().
thread_local_top() [1/2]
ThreadLocalTop* v8::internal::Isolate::thread_local_top () [inline]
Definition at line 1346 of file isolate.h.
                                     {
    return &isolate_data_.thread_local_top_;
  }
Referenced by v8::internal::ProfilerEventsProcessor::AddCurrentStack(), v8::internal::ProfilerEventsProcessor::AddDeoptStack(), v8::internal::Debug::AllFramesOnStackAreBlackboxed(), ArchiveThread(), v8::internal::wasm::WasmInterpreterRuntime::CallWasmToJSBuiltin(), v8::internal::DebugStackTraceIterator::CanBeRestarted(), clear_internal_exception(), clear_topmost_script_having_context(), v8::internal::DebugInfo::ClearBreakInfo(), v8::internal::Deoptimizer::DeoptimizeMarkedCode(), v8::internal::Debug::DiscardAllBaselineCode(), v8::internal::Debug::DiscardBaselineCode(), exception(), v8::internal::anonymous_namespace{wasm-interpreter-runtime.cc}::FindInterpreterEntryFramePointer(), FireCallCompletedCallbackInternal(), v8::internal::HandleScopeImplementer::Free(), v8::internal::GetShouldThrow(), v8::internal::TickSample::GetStackSample(), v8::internal::anonymous_namespace{runtime-wasm.cc}::GetWasmInstanceDataOnStackTop(), has_exception(), v8::Isolate::HasPendingException(), InitializeThreadLocal(), is_execution_terminating(), Iterate(), pending_message(), v8::internal::anonymous_namespace{isolate.cc}::PredictExceptionCatchAtFrame(), v8::internal::Debug::PrepareFunctionForDebugExecution(), PrintStack(), v8::internal::MarkCompactCollector::ProcessTopOptimizedFrame(), RegisterTryCatchHandler(), ReportFailedAccessCheck(), v8::internal::wasm::WasmEngine::ReportLiveCodeFromStackForGC(), RestoreThread(), set_context(), set_exception(), set_pending_message(), set_topmost_script_having_context(), SetFailedAccessCheckCallback(), v8::internal::FinalizationRegistryCleanupTask::SlowAssertNoActiveJavaScript(), v8::internal::StackFrameIteratorForProfiler::StackFrameIteratorForProfiler(), v8::Isolate::SuppressMicrotaskExecutionScope::SuppressMicrotaskExecutionScope(), v8::internal::wasm::switch_from_the_central_stack(), v8::internal::wasm::switch_from_the_central_stack_for_js(), v8::internal::wasm::switch_to_the_central_stack(), v8::internal::wasm::switch_to_the_central_stack_for_js(), Throw(), TopExceptionHandlerType(), UnregisterTryCatchHandler(), UnwindAndFindHandler(), and v8::internal::StackLimitCheck::WasmHasOverflowed().
thread_local_top() [2/2]
ThreadLocalTop const* v8::internal::Isolate::thread_local_top () const [inline]
Definition at line 1349 of file isolate.h.
                                                 {
    return &isolate_data_.thread_local_top_;
  }
thread_manager()
ThreadManager* v8::internal::Isolate::thread_manager () const [inline]
Definition at line 1437 of file isolate.h.
{ return thread_manager_; }
Referenced by v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::CheckNoArchivedThreads(), v8::internal::DebugInfo::ClearBreakInfo(), v8::internal::CppHeap::CurrentThreadIsHeapThread(), v8::internal::Deoptimizer::DeoptimizeMarkedCode(), v8::internal::Debug::DiscardAllBaselineCode(), v8::internal::Debug::DiscardBaselineCode(), v8::internal::anonymous_namespace{liveedit.cc}::FunctionDataMap::Fill(), v8::HandleScope::Initialize(), v8::Unlocker::Initialize(), v8::Locker::Initialize(), v8::Locker::IsLocked(), v8::internal::Heap::IterateRoots(), v8::Isolate::MemoryPressureNotification(), v8::internal::Debug::PrepareFunctionForDebugExecution(), v8::Shell::QuitOnce(), v8::internal::StartupSerializer::SerializeStrongReferences(), v8::internal::FinalizationRegistryCleanupTask::SlowAssertNoActiveJavaScript(), v8::Locker::~Locker(), and v8::Unlocker::~Unlocker().
Throw()
Tagged< Object > v8::internal::Isolate::Throw (Tagged< Object > exception, MessageLocation * location = nullptr)
Definition at line 2100 of file isolate.cc.
                                                         {
  if (has_exception()) {
    // A termination exception may have been thrown while preparing
    // {raw_exception}, e.g. by the near heap limit callback
    // (crbug.com/409487530).
    // In this case ignore the current error and propagate the termination
    // exception instead. Any other kind of exception is unexpected.
    DCHECK(IsTerminationException(exception()));
    return ReadOnlyRoots(heap()).exception();
  }
  DCHECK_IMPLIES(IsHole(raw_exception),
                 raw_exception == ReadOnlyRoots{this}.termination_exception());
  CHECK(IsOnCentralStack());
#if V8_ENABLE_WEBASSEMBLY
  trap_handler::AssertThreadNotInWasm();
#endif
  HandleScope scope(this);
  DirectHandle<Object> exception(raw_exception, this);
  if (v8_flags.print_all_exceptions) {
    PrintF("=========================================================\n");
    PrintF("Exception thrown:\n");
    if (location) {
      DirectHandle<Script> script = location->script();
      DirectHandle<Object> name(script->GetNameOrSourceURL(), this);
      PrintF("at ");
      if (IsString(*name) && Cast<String>(*name)->length() > 0) {
        Cast<String>(*name)->PrintOn(stdout);
      } else {
        PrintF("<anonymous>");
      }
// Script::GetLineNumber and Script::GetColumnNumber can allocate on the heap to
// initialize the line_ends array, so be careful when calling them.
#ifdef DEBUG
      if (AllowGarbageCollection::IsAllowed()) {
#else
      if ((false)) {
#endif
        Script::PositionInfo start_pos;
        Script::PositionInfo end_pos;
        Script::GetPositionInfo(script, location->start_pos(), &start_pos);
        Script::GetPositionInfo(script, location->end_pos(), &end_pos);
        PrintF(", %d:%d - %d:%d\n", start_pos.line + 1, start_pos.column + 1,
               end_pos.line + 1, end_pos.column + 1);
      } else {
        PrintF(", line %d\n", script->GetLineNumber(location->start_pos()) + 1);
      }
    }
    Print(*exception);
    PrintF("Stack Trace:\n");
    PrintStack(stdout);
    PrintF("=========================================================\n");
  }
  // Determine whether a message needs to be created for the given exception
  // depending on the following criteria:
  // 1) External v8::TryCatch missing: Always create a message because any
  // JavaScript handler for a finally-block might re-throw to top-level.
  // 2) External v8::TryCatch exists: Only create a message if the handler
  // captures messages or is verbose (which reports despite the catch).
  // 3) ReThrow from v8::TryCatch: The message from a previous throw still
  // exists and we preserve it instead of creating a new message.
  bool requires_message = try_catch_handler() == nullptr ||
                          try_catch_handler()->is_verbose_ ||
                          try_catch_handler()->capture_message_;
  bool rethrowing_message = thread_local_top()->rethrowing_message_;
  thread_local_top()->rethrowing_message_ = false;
  // Notify debugger of exception.
  if (is_catchable_by_javascript(*exception)) {
    DirectHandle<Object> message(pending_message(), this);
    std::optional<Tagged<Object>> maybe_exception = debug()->OnThrow(exception);
    if (maybe_exception.has_value()) {
      return *maybe_exception;
    }
    // Restore the message in case it was clobbered by debugger.
    set_pending_message(*message);
  }
  // Generate the message if required.
  if (requires_message && !rethrowing_message) {
    MessageLocation computed_location;
    // If no location was specified we try to use a computed one instead.
    if (location == nullptr && ComputeLocation(&computed_location)) {
      location = &computed_location;
    }
    if (bootstrapper()->IsActive()) {
      // It's not safe to try to make message objects or collect stack traces
      // while the bootstrapper is active since the infrastructure may not have
      // been properly initialized.
      ReportBootstrappingException(exception, location);
    } else {
      DirectHandle<Object> message_obj =
          CreateMessageOrAbort(exception, location);
      set_pending_message(*message_obj);
    }
  }
  // Set the exception being thrown.
  set_exception(*exception);
  PropagateExceptionToExternalTryCatch(TopExceptionHandlerType(*exception));
  if (v8_flags.experimental_report_exceptions_from_callbacks &&
      exception_propagation_callback_ && !rethrowing_message &&
      !preprocessing_exception_) {
    // Don't preprocess exceptions that might happen inside
    // |exception_propagation_callback_|.
    preprocessing_exception_ = true;
    NotifyExceptionPropagationCallback();
    preprocessing_exception_ = false;
  }
  return ReadOnlyRoots(heap()).exception();
}
References v8::internal::trap_handler::AssertThreadNotInWasm(), bootstrapper(), v8::TryCatch::capture_message_, CHECK, v8::internal::Script::PositionInfo::column, ComputeLocation(), CreateMessageOrAbort(), v8::internal::DCHECK(), DCHECK_IMPLIES, debug(), v8::internal::MessageLocation::end_pos(), exception(), v8::internal::Script::GetPositionInfo(), has_exception(), heap(), is_catchable_by_javascript(), v8::TryCatch::is_verbose_, IsOnCentralStack(), v8::internal::Script::PositionInfo::line, v8::internal::name, NotifyExceptionPropagationCallback(), v8::internal::Debug::OnThrow(), pending_message(), preprocessing_exception_, v8::internal::Print(), v8::internal::PrintF(), PrintStack(), PropagateExceptionToExternalTryCatch(), v8::internal::anonymous_namespace{isolate.cc}::ReportBootstrappingException(), v8::internal::ThreadLocalTop::rethrowing_message_, v8::internal::MessageLocation::script(), v8::internal::script, set_exception(), set_pending_message(), v8::internal::MessageLocation::start_pos(), thread_local_top(), TopExceptionHandlerType(), try_catch_handler(), and v8::internal::v8_flags.
Referenced by v8::ValueSerializer::Delegate::AdoptSharedValueConveyor(), v8::internal::JSArray::AnythingToArrayLength(), v8::internal::wasm::WasmInterpreterRuntime::CallExternalJSFunction(), v8::internal::Object::CheckContextualStoreToJSGlobalObject(), v8::internal::JSProxy::CheckDeleteTrap(), v8::internal::JSProxy::CheckGetSetTrapResult(), v8::internal::JSProxy::CheckHasTrap(), v8::internal::KeyAccumulator::CollectOwnJSProxyKeys(), v8::internal::CompileGlobalEval(), v8::internal::anonymous_namespace{externalize-string-extension.cc}::CopyConsStringToOld(), v8::internal::JSProxy::DefineOwnProperty(), v8::internal::JSReceiver::DeleteProperty(), v8::internal::JSProxy::DeletePropertyOrElement(), v8::internal::JSDisposableStackBase::DisposeResources(), v8::internal::FastGetOwnValuesOrEntries(), GetImportAttributesFromArgument(), v8::internal::JSProxy::GetOwnPropertyDescriptor(), v8::internal::JSModuleNamespace::GetPropertyAttributes(), v8::ValueDeserializer::Delegate::GetSharedArrayBufferFromId(), v8::ValueSerializer::Delegate::GetSharedArrayBufferId(), v8::ValueDeserializer::Delegate::GetSharedValueConveyor(), v8::ValueDeserializer::Delegate::GetWasmModuleFromId(), v8::internal::anonymous_namespace{builtins-typed-array.cc}::HandleOptionsBag(), v8::internal::JSProxy::HasProperty(), v8::internal::SourceTextModule::InnerModuleEvaluation(), v8::internal::JSProxy::IsArray(), v8::internal::JSProxy::IsExtensible(), v8::internal::anonymous_namespace{builtins-array.cc}::IterateElements(), v8::internal::wasm::WasmInterpreterRuntime::JSToWasmObject(), v8::internal::anonymous_namespace{builtins-typed-array.cc}::MapOptionToEnum(), v8::internal::WasmGlobalObject::New(), v8::internal::anonymous_namespace{execution.cc}::NewScriptContext(), v8::internal::anonymous_namespace{builtins-string.cc}::NextCodePoint(), v8::internal::JSProxy::PreventExtensions(), v8::internal::JSObject::PreventExtensionsWithTransition(), v8::internal::wasm::WasmInterpreterThread::RaiseException(), v8::internal::ValueDeserializer::ReadHeader(), v8::ValueDeserializer::ReadHeader(), v8::ValueDeserializer::Delegate::ReadHostObject(), v8::internal::ValueDeserializer::ReadObject(), v8::internal::ValueDeserializer::ReadObjectUsingEntireBufferForLegacyFormat(), v8::internal::ValueDeserializer::ReadObjectWrapper(), RunHostCreateShadowRealmContextCallback(), v8::internal::RUNTIME_FUNCTION(), v8::internal::JsonStringifier::Serialize_(), v8::internal::JsonStringifier::SerializeArrayLikeSlow(), v8::internal::JsonStringifier::SerializeJSPrimitiveWrapper(), v8::internal::JsonStringifier::SerializeJSProxy(), v8::internal::SyntheticModule::SetExport(), v8::internal::JSProxy::SetProperty(), v8::internal::JSProxy::SetPrototype(), StackOverflow(), v8::internal::JsonStringifier::StackPush(), v8::internal::Debug::StopSideEffectCheckMode(), TerminateExecution(), ThrowAt(), v8::internal::ValueSerializer::ThrowDataCloneError(), v8::internal::anonymous_namespace{value-serializer.cc}::ThrowDeserializationExceptionIfNonePending(), v8::internal::anonymous_namespace{runtime-internal.cc}::ThrowError(), v8::internal::wasm::WasmInterpreterRuntime::ThrowException(), v8::Isolate::ThrowException(), ThrowIllegalOperation(), v8::internal::anonymous_namespace{factory.cc}::ThrowInvalidEncodedStringBytes(), v8::internal::ErrorUtils::ThrowLoadFromNullOrUndefined(), v8::internal::anonymous_namespace{runtime-wasm.cc}::ThrowWasmSuspendError(), v8::internal::PropertyDescriptor::ToPropertyDescriptor(), wasm::FuncData::v8_callback(), v8::internal::ValidateAtomicAccess(), v8::internal::ValueSerializer::WriteHostObject(), and v8::internal::wasm::ErrorThrower::~ErrorThrower().
ThrowAt()
Tagged< Object > v8::internal::Isolate::ThrowAt (DirectHandle< JSObject > exception, MessageLocation * location)
Definition at line 1934 of file isolate.cc.
                                                           {
  DirectHandle<Name> key_start_pos = factory()->error_start_pos_symbol();
  Object::SetProperty(this, exception, key_start_pos,
                      direct_handle(Smi::FromInt(location->start_pos()), this),
                      StoreOrigin::kMaybeKeyed,
                      Just(ShouldThrow::kThrowOnError))
      .Check();
  DirectHandle<Name> key_end_pos = factory()->error_end_pos_symbol();
  Object::SetProperty(this, exception, key_end_pos,
                      direct_handle(Smi::FromInt(location->end_pos()), this),
                      StoreOrigin::kMaybeKeyed,
                      Just(ShouldThrow::kThrowOnError))
      .Check();
  DirectHandle<Name> key_script = factory()->error_script_symbol();
  Object::SetProperty(this, exception, key_script, location->script(),
                      StoreOrigin::kMaybeKeyed,
                      Just(ShouldThrow::kThrowOnError))
      .Check();
  return Throw(*exception, location);
}
References v8::internal::direct_handle(), v8::internal::MessageLocation::end_pos(), exception(), factory(), v8::internal::Smi::FromInt(), v8::Just(), v8::internal::kMaybeKeyed, v8::internal::kThrowOnError, v8::internal::MessageLocation::script(), v8::internal::Object::SetProperty(), v8::internal::MessageLocation::start_pos(), and Throw().
Referenced by v8::internal::anonymous_namespace{execution.cc}::NewScriptContext(), v8::internal::SyntheticModule::ResolveExport(), v8::internal::SourceTextModule::ResolveExport(), v8::internal::SourceTextModule::ResolveExportUsingStarExports(), v8::internal::ErrorUtils::ThrowLoadFromNullOrUndefined(), v8::internal::PendingCompilationErrorHandler::ThrowPendingError(), and v8::internal::ErrorUtils::ThrowSpreadArgError().
ThrowIllegalOperation()
Tagged< Object > v8::internal::Isolate::ThrowIllegalOperation ()
Definition at line 2920 of file isolate.cc.
                                              {
  if (v8_flags.stack_trace_on_illegal) PrintStack(stdout);
  return Throw(ReadOnlyRoots(heap()).illegal_access_string());
}
References heap(), PrintStack(), Throw(), and v8::internal::v8_flags.
Referenced by v8::internal::anonymous_namespace{execution.cc}::Invoke().
tiering_manager()
TieringManager* v8::internal::Isolate::tiering_manager () [inline]
Definition at line 1205 of file isolate.h.
{ return tiering_manager_; }
Referenced by v8::internal::anonymous_namespace{runtime-internal.cc}::BytecodeBudgetInterrupt(), v8::internal::anonymous_namespace{runtime-internal.cc}::BytecodeBudgetInterruptWithStackCheck(), and v8::internal::IC::OnFeedbackChanged().
time_millis_since_init()
double v8::internal::Isolate::time_millis_since_init () const [inline]
Definition at line 1641 of file isolate.h.
                                        {
    return heap_.MonotonicallyIncreasingTimeInMs() - time_millis_at_init_;
  }
Referenced by v8::internal::TracingAccountingAllocator::Dump(), v8::internal::ObjectStats::Dump(), v8::internal::GCTracer::Print(), v8::internal::ObjectStats::PrintJSON(), and v8::internal::anonymous_namespace{mark-compact.cc}::TraceEvacuation().
top_backup_incumbent_scope()
const v8::Context::BackupIncumbentScope* v8::internal::Isolate::top_backup_incumbent_scope () const [inline]
Definition at line 2190 of file isolate.h.
                                                                          {
    return thread_local_top()->top_backup_incumbent_scope_;
  }
Referenced by v8::Context::BackupIncumbentScope::BackupIncumbentScope(), and GetIncumbentContextSlow().
TopExceptionHandlerType()
Isolate::ExceptionHandlerType v8::internal::Isolate::TopExceptionHandlerType (Tagged< Object > exception)
Definition at line 3104 of file isolate.cc.
                              {
  DCHECK_NE(ReadOnlyRoots(heap()).the_hole_value(), exception);
  Address js_handler = Isolate::handler(thread_local_top());
  Address external_handler = thread_local_top()->try_catch_handler_address();
  // A handler cannot be on top if it doesn't exist. For uncatchable exceptions,
  // the JavaScript handler cannot be on top.
  if (js_handler == kNullAddress || !is_catchable_by_javascript(exception)) {
    if (external_handler == kNullAddress) {
      return ExceptionHandlerType::kNone;
    }
    return ExceptionHandlerType::kExternalTryCatch;
  }
  if (external_handler == kNullAddress) {
    return ExceptionHandlerType::kJavaScriptHandler;
  }
  // The exception has been externally caught if and only if there is an
  // external handler which is on top of the top-most JS_ENTRY handler.
  //
  // Note, that finally clauses would re-throw an exception unless it's aborted
  // by jumps in control flow (like return, break, etc.) and we'll have another
  // chance to set proper v8::TryCatch later.
  DCHECK_NE(kNullAddress, external_handler);
  DCHECK_NE(kNullAddress, js_handler);
  if (external_handler < js_handler) {
    return ExceptionHandlerType::kExternalTryCatch;
  }
  return ExceptionHandlerType::kJavaScriptHandler;
}
References DCHECK_NE, exception(), handler(), heap(), is_catchable_by_javascript(), kExternalTryCatch, kJavaScriptHandler, kNone, v8::internal::kNullAddress, thread_local_top(), and v8::internal::ThreadLocalTop::try_catch_handler_address().
Referenced by PredictExceptionCatcher(), ReportPendingMessages(), Throw(), and WalkCallStackAndPromiseTree().
topmost_script_having_context()
Tagged<Context> v8::internal::Isolate::topmost_script_having_context () const [inline]
Definition at line 823 of file isolate.h.
                                                        {
    return thread_local_top()->topmost_script_having_context_;
  }
Referenced by v8::internal::MarkCompactCollector::ClearNonLiveReferences(), GetIncumbentContext(), GetIncumbentContextSlow(), and v8::internal::SaveContext::SaveContext().
topmost_script_having_context_address()
Tagged<Context>* v8::internal::Isolate::topmost_script_having_context_address () [inline]
Definition at line 828 of file isolate.h.
                                                           {
    return &thread_local_top()->topmost_script_having_context_;
  }
total_regexp_code_generated()
size_t v8::internal::Isolate::total_regexp_code_generated () const [inline]
Definition at line 1495 of file isolate.h.
                                             {
    return total_regexp_code_generated_;
  }
Referenced by v8::internal::anonymous_namespace{regexp.cc}::TooMuchRegExpCode().
traced_handles()
TracedHandles* v8::internal::Isolate::traced_handles () [inline]
Definition at line 1433 of file isolate.h.
{ return &traced_handles_; }
Referenced by v8::internal::CppHeap::AttachIsolate(), v8::internal::SerializedHandleChecker::CheckGlobalAndEternalHandles(), v8::internal::MarkCompactCollector::ClearNonLiveReferences(), v8::internal::MinorMarkSweepCollector::ClearNonLiveReferences(), v8::internal::ScavengerCollector::CollectGarbage(), v8::internal::V8HeapExplorer::CollectTemporaryGlobalObjectsTags(), v8::internal::CppHeap::CompactAndSweep(), v8::internal::CppHeap::FinishSweepingIfRunning(), v8::internal::GlobalizeTracedReference(), v8::internal::Heap::IterateRoots(), v8::internal::Heap::IterateWeakGlobalHandles(), v8::internal::MinorMarkSweepCollector::MarkRoots(), v8::internal::MinorMarkSweepCollector::MarkRootsFromTracedHandles(), v8::internal::IncrementalMarking::StartMarkingMajor(), v8::internal::Heap::TotalGlobalHandlesSize(), and v8::internal::Heap::UsedGlobalHandlesSize().
try_catch_handler()
v8::TryCatch* v8::internal::Isolate::try_catch_handler () [inline]
Definition at line 865 of file isolate.h.
                                  {
    return thread_local_top()->try_catch_handler_;
  }
Referenced by CancelTerminateExecution(), clear_exception(), v8::internal::ThreadManager::FreeThreadResources(), v8::internal::anonymous_namespace{isolate.cc}::PredictExceptionCatchAtFrame(), PropagateExceptionToExternalTryCatch(), ReportPendingMessages(), SetTerminationOnExternalTryCatch(), and Throw().
unicode_cache()
UnicodeCache* v8::internal::Isolate::unicode_cache () const [inline]
Definition at line 1417 of file isolate.h.
{ return unicode_cache_; }
UnregisterManagedPtrDestructor()
void v8::internal::Isolate::UnregisterManagedPtrDestructor (ManagedPtrDestructor * finalizer)
Definition at line 3871 of file isolate.cc.
                                                                             {
  base::MutexGuard lock(&managed_ptr_destructors_mutex_);
  if (destructor->prev_) {
    destructor->prev_->next_ = destructor->next_;
  } else {
    DCHECK_EQ(destructor, managed_ptr_destructors_head_);
    managed_ptr_destructors_head_ = destructor->next_;
  }
  if (destructor->next_) destructor->next_->prev_ = destructor->prev_;
  destructor->prev_ = nullptr;
  destructor->next_ = nullptr;
}
References DCHECK_EQ, managed_ptr_destructors_head_, managed_ptr_destructors_mutex_, v8::internal::ManagedPtrDestructor::next_, and v8::internal::ManagedPtrDestructor::prev_.
Referenced by v8::internal::anonymous_namespace{managed.cc}::ManagedObjectFinalizerSecondPass().
UnregisterTryCatchHandler()
void v8::internal::Isolate::UnregisterTryCatchHandler (v8::TryCatch * that)
Definition at line 668 of file isolate.cc.
                                                        {
  DCHECK_EQ(thread_local_top()->try_catch_handler_, that);
  thread_local_top()->try_catch_handler_ = that->next_;
  SimulatorStack::UnregisterJSStackComparableAddress(this);
}
References DCHECK_EQ, v8::TryCatch::next_, thread_local_top(), v8::internal::ThreadLocalTop::try_catch_handler_, and v8::internal::SimulatorStack::UnregisterJSStackComparableAddress().
UnwindAndFindHandler()
Tagged< Object > v8::internal::Isolate::UnwindAndFindHandler ()
Definition at line 2254 of file isolate.cc.
                                             {
  // TODO(v8:12676): Fix gcmole failures in this function.
  DisableGCMole no_gcmole;
  DisallowGarbageCollection no_gc;
  // The topmost_script_having_context value becomes outdated after frames
  // unwinding.
  clear_topmost_script_having_context();
#if V8_ENABLE_WEBASSEMBLY
  // Create the {SetThreadInWasmFlagScope} first in this function so that its
  // destructor gets called after all the other destructors. It is important
  // that the destructor sets the thread-in-wasm flag after all other
  // destructors. The other destructors may cause exceptions, e.g. ASan on
  // Windows, which would invalidate the thread-in-wasm flag when the wasm trap
  // handler handles such non-wasm exceptions.
  SetThreadInWasmFlagScope set_thread_in_wasm_flag_scope;
#endif // V8_ENABLE_WEBASSEMBLY
  Tagged<Object> exception = this->exception();
  auto FoundHandler = [&](StackFrameIterator& iter, Tagged<Context> context,
                          Address instruction_start, intptr_t handler_offset,
                          Address constant_pool_address, Address handler_sp,
                          Address handler_fp, int num_frames_above_handler) {
    // Store information to be consumed by the CEntry.
    thread_local_top()->pending_handler_context_ = context;
    thread_local_top()->pending_handler_entrypoint_ =
        instruction_start + handler_offset;
    thread_local_top()->pending_handler_constant_pool_ = constant_pool_address;
    thread_local_top()->pending_handler_fp_ = handler_fp;
    thread_local_top()->pending_handler_sp_ = handler_sp;
    thread_local_top()->num_frames_above_pending_handler_ =
        num_frames_above_handler;
#if V8_ENABLE_WEBASSEMBLY
    // If the exception was caught in a different stack, process all
    // intermediate stack switches.
    // This cannot be done during unwinding because the stack switching state
    // must stay consistent with the thread local top (see crbug.com/406053619).
    wasm::StackMemory* active_stack = isolate_data_.active_stack();
    if (active_stack != nullptr) {
      wasm::StackMemory* parent = nullptr;
      Tagged<HeapObject> suspender = *roots_table().active_suspender();
      while (active_stack != iter.wasm_stack()) {
        parent = active_stack->jmpbuf()->parent;
        SBXCHECK_EQ(parent->jmpbuf()->state, wasm::JumpBuffer::Inactive);
        SwitchStacks(active_stack, parent);
        // Unconditionally update the active suspender as well. This assumes
        // that suspenders contain exactly one stack each.
        // Note: this is only needed for --stress-wasm-stack-switching.
        // Otherwise the exception should have been caught by the JSPI builtin.
        // TODO(388533754): Revisit this for core stack-switching when the
        // suspender can encapsulate multiple stacks.
        suspender = Tagged<WasmSuspenderObject>::cast(suspender)->parent();
        parent->jmpbuf()->state = wasm::JumpBuffer::Active;
        RetireWasmStack(active_stack);
        active_stack = parent;
      }
      if (parent) {
        // We switched at least once, update the active continuation.
        isolate_data_.set_active_stack(active_stack);
        roots_table().slot(RootIndex::kActiveSuspender).store(suspender);
      }
    }
    // The unwinder is running on the central stack. If the target frame is in a
    // secondary stack, update the central stack flags and the stack limit.
    Address stack_address =
        handler_sp != kNullAddress ? handler_sp : handler_fp;
    if (!IsOnCentralStack(stack_address)) {
      thread_local_top()->is_on_central_stack_flag_ = false;
      iter.wasm_stack()->ShrinkTo(stack_address);
      uintptr_t limit =
          reinterpret_cast<uintptr_t>(iter.wasm_stack()->jslimit());
      stack_guard()->SetStackLimitForStackSwitching(limit);
      iter.wasm_stack()->clear_stack_switch_info();
    }
    // Regardless of the stack that the handler belongs to, these fields should
    // be cleared.
    thread_local_top()->secondary_stack_limit_ = 0;
    thread_local_top()->secondary_stack_sp_ = 0;
#endif
    // Return and clear exception. The contract is that:
    // (1) the exception is stored in one place (no duplication), and
    // (2) within generated-code land, that one place is the return register.
    // If/when we unwind back into C++ (returning to the JSEntry stub,
    // or to Execution::CallWasm), the returned exception will be sent
    // back to isolate->set_exception(...).
    clear_internal_exception();
    return exception;
  };
  // Special handling of termination exceptions, uncatchable by JavaScript and
  // Wasm code, we unwind the handlers until the top ENTRY handler is found.
  bool catchable_by_js = is_catchable_by_javascript(exception);
  if (!catchable_by_js && !context().is_null()) {
    // Because the array join stack will not pop the elements when throwing the
    // uncatchable terminate exception, we need to clear the array join stack to
    // avoid leaving the stack in an invalid state.
    // See also CycleProtectedArrayJoin.
    raw_native_context()->set_array_join_stack(
        ReadOnlyRoots(this).undefined_value());
  }
  // Compute handler and stack unwinding information by performing a full walk
  // over the stack and dispatching according to the frame type.
  int visited_frames = 0;
  for (StackFrameIterator iter(this, thread_local_top());;
       iter.Advance(), visited_frames++) {
#if V8_ENABLE_WEBASSEMBLY
    if (iter.frame()->type() == StackFrame::STACK_SWITCH) {
      if (catchable_by_js && iter.frame()->LookupCode()->builtin_id() !=
                                 Builtin::kJSToWasmStressSwitchStacksAsm) {
        Tagged<Code> code =
            builtins()->code(Builtin::kWasmReturnPromiseOnSuspendAsm);
        HandlerTable table(code);
        Address instruction_start =
            code->InstructionStart(this, iter.frame()->pc());
        int handler_offset = table.LookupReturn(0);
        return FoundHandler(iter, Context(), instruction_start, handler_offset,
                            kNullAddress, iter.frame()->sp(),
                            iter.frame()->fp(), visited_frames);
      } else {
        // Just walk across the stack switch here. We only process it once we
        // have reached the handler.
        continue;
      }
    }
#endif
    // Handler must exist.
    DCHECK(!iter.done());
    StackFrame* frame = iter.frame();
    // The debugger implements the "restart frame" feature by throwing a
    // terminate exception. Check and if we need to restart `frame`,
    // jump into the `RestartFrameTrampoline` builtin instead of
    // a catch handler.
    // Optimized frames take a detour via the deoptimizer before also jumping
    // to the `RestartFrameTrampoline` builtin.
    if (debug()->ShouldRestartFrame(frame->id())) {
      CancelTerminateExecution();
      CHECK(!catchable_by_js);
      CHECK(frame->is_javascript());
      if (frame->is_optimized_js()) {
        Tagged<Code> code = frame->LookupCode();
        // The debugger triggers lazy deopt for the "to-be-restarted" frame
        // immediately when the CDP event arrives while paused.
        CHECK(code->marked_for_deoptimization());
        set_deoptimizer_lazy_throw(true);
        // Jump directly to the optimized frames return, to immediately fall
        // into the deoptimizer.
        const int offset =
            static_cast<int>(frame->pc() - code->instruction_start());
        // Compute the stack pointer from the frame pointer. This ensures that
        // argument slots on the stack are dropped as returning would.
        // Note: Needed by the deoptimizer to rematerialize frames.
        Address return_sp = frame->fp() +
                            StandardFrameConstants::kFixedFrameSizeAboveFp -
                            code->stack_slots() * kSystemPointerSize;
        return FoundHandler(iter, Context(), code->instruction_start(), offset,
                            code->constant_pool(), return_sp, frame->fp(),
                            visited_frames);
      }
      debug()->clear_restart_frame();
      Tagged<Code> code = *BUILTIN_CODE(this, RestartFrameTrampoline);
      return FoundHandler(iter, Context(), code->instruction_start(), 0,
                          code->constant_pool(), kNullAddress, frame->fp(),
                          visited_frames);
    }
    switch (frame->type()) {
      case StackFrame::ENTRY:
      case StackFrame::CONSTRUCT_ENTRY: {
        // For JSEntry frames we always have a handler.
        StackHandler* handler = frame->top_handler();
        // Restore the next handler.
        thread_local_top()->handler_ = handler->next_address();
        // Gather information from the handler.
        Tagged<Code> code = frame->LookupCode();
        HandlerTable table(code);
        return FoundHandler(iter, Context(),
                            code->InstructionStart(this, frame->pc()),
                            table.LookupReturn(0), code->constant_pool(),
                            handler->address() + StackHandlerConstants::kSize,
                            0, visited_frames);
      }
#if V8_ENABLE_WEBASSEMBLY
      case StackFrame::C_WASM_ENTRY: {
#if V8_ENABLE_DRUMBRAKE
        if (v8_flags.wasm_jitless) {
          StackHandler* handler = frame->top_handler();
          thread_local_top()->handler_ = handler->next_address();
          Tagged<Code> code =
              frame->LookupCode(); // WasmInterpreterCWasmEntry.
          HandlerTable table(code);
          Address instruction_start = code->InstructionStart(this, frame->pc());
          // Compute the stack pointer from the frame pointer. This ensures that
          // argument slots on the stack are dropped as returning would.
          Address return_sp = *reinterpret_cast<Address*>(
              frame->fp() + WasmInterpreterCWasmEntryConstants::kSPFPOffset);
          const int handler_offset = table.LookupReturn(0);
          if (trap_handler::IsThreadInWasm()) {
            trap_handler::ClearThreadInWasm();
          }
          return FoundHandler(iter, Context(), instruction_start,
                              handler_offset, code->constant_pool(), return_sp,
                              frame->fp(), visited_frames);
        }
#endif // V8_ENABLE_DRUMBRAKE
        StackHandler* handler = frame->top_handler();
        thread_local_top()->handler_ = handler->next_address();
        Tagged<Code> code = frame->LookupCode();
        HandlerTable table(code);
        Address instruction_start = code->instruction_start();
        int return_offset = static_cast<int>(frame->pc() - instruction_start);
        int handler_offset = table.LookupReturn(return_offset);
        DCHECK_NE(-1, handler_offset);
        // Compute the stack pointer from the frame pointer. This ensures that
        // argument slots on the stack are dropped as returning would.
        Address return_sp = frame->fp() +
                            StandardFrameConstants::kFixedFrameSizeAboveFp -
                            code->stack_slots() * kSystemPointerSize;
        return FoundHandler(iter, Context(), instruction_start, handler_offset,
                            code->constant_pool(), return_sp, frame->fp(),
                            visited_frames);
      }
#if V8_ENABLE_DRUMBRAKE
      case StackFrame::WASM_INTERPRETER_ENTRY: {
        if (trap_handler::IsThreadInWasm()) {
          trap_handler::ClearThreadInWasm();
        }
      } break;
#endif // V8_ENABLE_DRUMBRAKE
      case StackFrame::WASM:
      case StackFrame::WASM_SEGMENT_START: {
        if (!is_catchable_by_wasm(exception)) break;
        WasmFrame* wasm_frame = static_cast<WasmFrame*>(frame);
        wasm::WasmCode* wasm_code =
            wasm::GetWasmCodeManager()->LookupCode(this, frame->pc());
        int offset = wasm_frame->LookupExceptionHandlerInTable();
        if (offset < 0) break;
        // Compute the stack pointer from the frame pointer. This ensures that
        // argument slots on the stack are dropped as returning would.
        // The stack slot count needs to be adjusted for Liftoff frames. It has
        // two components: the fixed frame slots, and the maximum number of
        // registers pushed on top of the frame in out-of-line code. We know
        // that we are not currently in an OOL call, because OOL calls don't
        // have exception handlers. So we subtract the OOL spill count from the
        // total stack slot count to compute the actual frame size:
        int stack_slots = wasm_code->stack_slots() - wasm_code->ool_spills();
        Address return_sp = frame->fp() +
                            StandardFrameConstants::kFixedFrameSizeAboveFp -
                            stack_slots * kSystemPointerSize;
#if V8_ENABLE_DRUMBRAKE
        // Transitioning from JS To Wasm.
        if (v8_flags.wasm_enable_exec_time_histograms &&
            v8_flags.slow_histograms && !v8_flags.wasm_jitless) {
          // Start measuring the time spent running Wasm for jitted Wasm.
          wasm_execution_timer()->Start();
        }
#endif // V8_ENABLE_DRUMBRAKE
        // This is going to be handled by WebAssembly, so we need to set the TLS
        // flag. The {SetThreadInWasmFlagScope} will set the flag after all
        // destructors have been executed.
        set_thread_in_wasm_flag_scope.Enable();
        return FoundHandler(iter, Context(), wasm_code->instruction_start(),
                            offset, wasm_code->constant_pool(), return_sp,
                            frame->fp(), visited_frames);
      }
      case StackFrame::WASM_LIFTOFF_SETUP: {
        // The WasmLiftoffFrameSetup builtin doesn't throw, and doesn't call
        // out to user code that could throw.
        UNREACHABLE();
      }
#endif // V8_ENABLE_WEBASSEMBLY
      case StackFrame::MAGLEV:
      case StackFrame::TURBOFAN_JS: {
        // For optimized frames we perform a lookup in the handler table.
        if (!catchable_by_js) break;
        OptimizedJSFrame* opt_frame = static_cast<OptimizedJSFrame*>(frame);
        int offset = opt_frame->LookupExceptionHandlerInTable(nullptr, nullptr);
        if (offset < 0) break;
        // The code might be an optimized code or a turbofanned builtin.
        Tagged<Code> code = frame->LookupCode();
        // Compute the stack pointer from the frame pointer. This ensures
        // that argument slots on the stack are dropped as returning would.
        Address return_sp = frame->fp() +
                            StandardFrameConstants::kFixedFrameSizeAboveFp -
                            code->stack_slots() * kSystemPointerSize;
        // TODO(bmeurer): Turbofanned BUILTIN frames appear as TURBOFAN_JS,
        // but do not have a code kind of TURBOFAN_JS.
        if (CodeKindCanDeoptimize(code->kind()) &&
            code->marked_for_deoptimization()) {
          // If the target code is lazy deoptimized, we jump to the original
          // return address, but we make a note that we are throwing, so
          // that the deoptimizer can do the right thing.
          offset = static_cast<int>(frame->pc() - code->instruction_start());
          set_deoptimizer_lazy_throw(true);
        }
        return FoundHandler(
            iter, Context(), code->InstructionStart(this, frame->pc()), offset,
            code->constant_pool(), return_sp, frame->fp(), visited_frames);
      }
      case StackFrame::STUB: {
        // Some stubs are able to handle exceptions.
        if (!catchable_by_js) break;
        StubFrame* stub_frame = static_cast<StubFrame*>(frame);
#if V8_ENABLE_WEBASSEMBLY
        DCHECK_NULL(wasm::GetWasmCodeManager()->LookupCode(this, frame->pc()));
#endif // V8_ENABLE_WEBASSEMBLY
        // The code might be a dynamically generated stub or a turbofanned
        // embedded builtin.
        Tagged<Code> code = stub_frame->LookupCode();
        if (!code->is_turbofanned() || !code->has_handler_table()) {
          break;
        }
        int offset = stub_frame->LookupExceptionHandlerInTable();
        if (offset < 0) break;
        // Compute the stack pointer from the frame pointer. This ensures
        // that argument slots on the stack are dropped as returning would.
        Address return_sp = frame->fp() +
                            StandardFrameConstants::kFixedFrameSizeAboveFp -
                            code->stack_slots() * kSystemPointerSize;
        return FoundHandler(
            iter, Context(), code->InstructionStart(this, frame->pc()), offset,
            code->constant_pool(), return_sp, frame->fp(), visited_frames);
      }
      case StackFrame::INTERPRETED:
      case StackFrame::BASELINE: {
        // For interpreted frame we perform a range lookup in the handler table.
        if (!catchable_by_js) break;
        UnoptimizedJSFrame* js_frame = UnoptimizedJSFrame::cast(frame);
        int register_slots = UnoptimizedFrameConstants::RegisterStackSlotCount(
            js_frame->GetBytecodeArray()->register_count());
        int context_reg = 0; // Will contain register index holding context.
        int offset =
            js_frame->LookupExceptionHandlerInTable(&context_reg, nullptr);
        if (offset < 0) break;
        // Compute the stack pointer from the frame pointer. This ensures that
        // argument slots on the stack are dropped as returning would.
        // Note: This is only needed for interpreted frames that have been
        // materialized by the deoptimizer. If there is a handler frame
        // in between then {frame->sp()} would already be correct.
        Address return_sp = frame->fp() -
                            InterpreterFrameConstants::kFixedFrameSizeFromFp -
                            register_slots * kSystemPointerSize;
        // Patch the bytecode offset in the interpreted frame to reflect the
        // position of the exception handler. The special builtin below will
        // take care of continuing to dispatch at that position. Also restore
        // the correct context for the handler from the interpreter register.
        Tagged<Context> context =
            Cast<Context>(js_frame->ReadInterpreterRegister(context_reg));
        DCHECK(IsContext(context));
        if (frame->is_baseline()) {
          BaselineFrame* sp_frame = BaselineFrame::cast(js_frame);
          Tagged<Code> code = sp_frame->LookupCode();
          intptr_t pc_offset = sp_frame->GetPCForBytecodeOffset(offset);
          // Patch the context register directly on the frame, so that we don't
          // need to have a context read + write in the baseline code.
          sp_frame->PatchContext(context);
          return FoundHandler(iter, Context(), code->instruction_start(),
                              pc_offset, code->constant_pool(), return_sp,
                              sp_frame->fp(), visited_frames);
        } else {
          InterpretedFrame::cast(js_frame)->PatchBytecodeOffset(
              static_cast<int>(offset));
          Tagged<Code> code = *BUILTIN_CODE(this, InterpreterEnterAtBytecode);
          // We subtract a frame from visited_frames because otherwise the
          // shadow stack will drop the underlying interpreter entry trampoline
          // in which the handler runs.
          //
          // An interpreted frame cannot be the first frame we look at
          // because at a minimum, an exit frame into C++ has to separate
          // it and the context in which this C++ code runs.
          CHECK_GE(visited_frames, 1);
          return FoundHandler(iter, context, code->instruction_start(), 0,
                              code->constant_pool(), return_sp, frame->fp(),
                              visited_frames - 1);
        }
      }
      case StackFrame::BUILTIN: {
        // For builtin frames we are guaranteed not to find a handler.
        if (catchable_by_js) {
          CHECK_EQ(-1, BuiltinFrame::cast(frame)->LookupExceptionHandlerInTable(
                           nullptr, nullptr));
        }
        break;
      }
      case StackFrame::INTERNAL: {
        auto code = frame->GcSafeLookupCode();
        if (code->builtin_id() ==
            Builtin::kDeoptimizationEntry_LazyAfterFastCall) {
          // Deoptimization Entry builtin does the exception handling for the
          // fast API if the fast API caller was marked for deoptimization.
          // Therefore, even though `frame->fp()` says that we are coming from
          // the Deoptimization Entry builtin, we have to do the stack unwinding
          // as if we come from the fast call. The return address of the fast
          // call is still stored in the isolate, so we can just load it from
          // there.
          Address fast_call_pc = isolate_data()->fast_c_call_caller_pc();
          std::optional<Tagged<GcSafeCode>> result =
              inner_pointer_to_code_cache()->GetCacheEntry(fast_call_pc)->code;
          CHECK(!result->is_null());
          Tagged<GcSafeCode> caller_code = result.value();
          int caller_offset =
              caller_code->GetOffsetFromInstructionStart(this, fast_call_pc);
          // Check if there is actually an exception handler registered at the
          // return address of the fast call. If so, then we tell the
          // deoptimizer of the exception and just return the the Deotimization
          // Entry. Otherwise we iterate the stack further to find a handler.
          HandlerTable table(caller_code->UnsafeCastToCode());
          int handler_offset = table.LookupReturn(caller_offset);
          if (handler_offset < 0) {
            break;
          }
          // If the target code is lazy deoptimized, we jump to the original
          // return address, but we make a note that we are throwing, so
          // that the deoptimizer can do the right thing.
          int offset =
              static_cast<int>(frame->pc() - code->instruction_start());
          set_deoptimizer_lazy_throw(true);
          return FoundHandler(iter, Context(),
                              code->InstructionStart(this, frame->pc()), offset,
                              code->constant_pool(), frame->sp(), frame->fp(),
                              visited_frames);
        }
        break;
      }
      case StackFrame::JAVASCRIPT_BUILTIN_CONTINUATION_WITH_CATCH: {
        // Builtin continuation frames with catch can handle exceptions.
        if (!catchable_by_js) break;
        JavaScriptBuiltinContinuationWithCatchFrame* js_frame =
            JavaScriptBuiltinContinuationWithCatchFrame::cast(frame);
        js_frame->SetException(exception);
        // Reconstruct the stack pointer from the frame pointer.
        Address return_sp = js_frame->fp() - js_frame->GetSPToFPDelta();
        Tagged<Code> code = js_frame->LookupCode();
        return FoundHandler(iter, Context(), code->instruction_start(), 0,
                            code->constant_pool(), return_sp, frame->fp(),
                            visited_frames);
      }
      default:
        // All other types can not handle exception.
        break;
    }
    if (frame->is_optimized_js()) {
      // Remove per-frame stored materialized objects.
      bool removed = materialized_object_store_->Remove(frame->fp());
      USE(removed);
      // If there were any materialized objects, the code should be
      // marked for deopt.
      DCHECK_IMPLIES(removed, frame->LookupCode()->marked_for_deoptimization());
    }
  }
  UNREACHABLE();
} // namespace internal
References v8::internal::wasm::JumpBuffer::Active, v8::internal::IsolateData::active_stack(), v8::internal::StackFrameIterator::Advance(), BUILTIN, BUILTIN_CODE, builtins(), CancelTerminateExecution(), v8::internal::TaggedImpl< HeapObjectReferenceType::STRONG, Address >::cast(), v8::internal::UnoptimizedJSFrame::cast(), v8::internal::InterpretedFrame::cast(), v8::internal::BaselineFrame::cast(), v8::internal::BuiltinFrame::cast(), v8::internal::JavaScriptBuiltinContinuationWithCatchFrame::cast(), CHECK, CHECK_EQ, CHECK_GE, clear_internal_exception(), v8::internal::Debug::clear_restart_frame(), clear_topmost_script_having_context(), v8::internal::trap_handler::ClearThreadInWasm(), v8::internal::Builtins::code(), v8::internal::InnerPointerToCodeCache::InnerPointerToCodeCacheEntry::code, code, v8::internal::CodeKindCanDeoptimize(), v8::internal::wasm::WasmCode::constant_pool(), CONSTRUCT_ENTRY, context(), v8::internal::DCHECK(), DCHECK_IMPLIES, DCHECK_NE, DCHECK_NULL, debug(), v8::internal::StackFrameIteratorBase::done(), ENTRY, exception(), v8::internal::IsolateData::fast_c_call_caller_pc(), v8::internal::StackFrame::fp(), v8::internal::StackFrameIterator::frame(), v8::internal::StackFrame::GcSafeLookupCode(), v8::internal::UnoptimizedJSFrame::GetBytecodeArray(), v8::internal::InnerPointerToCodeCache::GetCacheEntry(), v8::internal::BaselineFrame::GetPCForBytecodeOffset(), v8::internal::JavaScriptBuiltinContinuationFrame::GetSPToFPDelta(), v8::internal::wasm::GetWasmCodeManager(), handler(), v8::internal::ThreadLocalTop::handler_, v8::internal::StackFrame::id(), v8::internal::wasm::JumpBuffer::Inactive, inner_pointer_to_code_cache(), v8::internal::wasm::WasmCode::instruction_start(), v8::internal::StackFrame::is_baseline(), is_catchable_by_javascript(), is_catchable_by_wasm(), v8::internal::StackFrame::is_javascript(), v8::internal::ThreadLocalTop::is_on_central_stack_flag_, v8::internal::StackFrame::is_optimized_js(), isolate_data(), isolate_data_, IsOnCentralStack(), v8::internal::trap_handler::IsThreadInWasm(), v8::internal::wasm::StackMemory::jmpbuf(), v8::internal::CommonFrameConstants::kFixedFrameSizeAboveFp, v8::internal::StandardFrameConstants::kFixedFrameSizeFromFp, v8::internal::kNullAddress, v8::internal::StackHandlerConstants::kSize, v8::internal::kSystemPointerSize, v8::internal::StackFrame::LookupCode(), v8::internal::wasm::WasmCodeManager::LookupCode(), v8::internal::StubFrame::LookupExceptionHandlerInTable(), v8::internal::OptimizedJSFrame::LookupExceptionHandlerInTable(), v8::internal::UnoptimizedJSFrame::LookupExceptionHandlerInTable(), v8::internal::HandlerTable::LookupReturn(), materialized_object_store_, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::ThreadLocalTop::num_frames_above_pending_handler_, v8::internal::wasm::WasmCode::ool_spills(), v8::internal::wasm::JumpBuffer::parent, v8::internal::InterpretedFrame::PatchBytecodeOffset(), v8::internal::BaselineFrame::PatchContext(), v8::internal::StackFrame::pc(), v8::internal::ThreadLocalTop::pending_handler_constant_pool_, v8::internal::ThreadLocalTop::pending_handler_context_, v8::internal::ThreadLocalTop::pending_handler_entrypoint_, v8::internal::ThreadLocalTop::pending_handler_fp_, v8::internal::ThreadLocalTop::pending_handler_sp_, raw_native_context(), v8::internal::UnoptimizedJSFrame::ReadInterpreterRegister(), v8::internal::UnoptimizedFrameConstants::RegisterStackSlotCount(), v8::internal::MaterializedObjectStore::Remove(), v8::base::internal::result, roots_table(), SBXCHECK_EQ, v8::internal::ThreadLocalTop::secondary_stack_limit_, v8::internal::ThreadLocalTop::secondary_stack_sp_, v8::internal::IsolateData::set_active_stack(), set_deoptimizer_lazy_throw(), v8::internal::JavaScriptBuiltinContinuationWithCatchFrame::SetException(), v8::internal::StackGuard::SetStackLimitForStackSwitching(), v8::internal::RootsTable::slot(), v8::internal::StackFrame::sp(), stack_guard(), v8::internal::wasm::WasmCode::stack_slots(), v8::internal::wasm::JumpBuffer::state, v8::internal::FullObjectSlot::store(), v8::internal::anonymous_namespace{builtins-riscv.cc}::SwitchStacks(), thread_local_top(), v8::internal::StackFrame::top_handler(), v8::internal::StackFrame::type(), v8::internal::UNREACHABLE(), USE, and v8::internal::v8_flags.
Referenced by v8::internal::RUNTIME_FUNCTION().
UpdateLogObjectRelocation()
void v8::internal::Isolate::UpdateLogObjectRelocation ()
Definition at line 4467 of file isolate.cc.
                                        {
  log_object_relocation_ =
      v8_flags.verify_predictable || IsLoggingCodeCreation() ||
      v8_file_logger()->is_logging() ||
      (heap()->heap_profiler() != nullptr &&
       heap()->heap_profiler()->is_tracking_object_moves()) ||
      heap()->has_heap_object_allocation_tracker();
}
References v8::internal::Heap::has_heap_object_allocation_tracker(), heap(), v8::internal::Heap::heap_profiler(), v8::internal::V8FileLogger::is_logging(), v8::internal::HeapProfiler::is_tracking_object_moves(), IsLoggingCodeCreation(), log_object_relocation_, v8_file_logger(), and v8::internal::v8_flags.
Referenced by v8::internal::Heap::AddHeapObjectAllocationTracker(), v8::internal::HeapProfiler::ClearHeapObjectMap(), v8::internal::Heap::RemoveHeapObjectAllocationTracker(), v8::internal::V8FileLogger::SetCodeEventHandler(), v8::internal::HeapProfiler::StartHeapObjectsTracking(), v8::internal::HeapProfiler::TakeSnapshot(), v8::internal::V8FileLogger::TearDownAndGetLogFile(), and v8::internal::V8FileLogger::UpdateIsLogging().
UpdateLongTaskStats()
void v8::internal::Isolate::UpdateLongTaskStats ()
Definition at line 7586 of file isolate.cc.
                                  {
  if (last_long_task_stats_counter_ != isolate_data_.long_task_stats_counter_) {
    last_long_task_stats_counter_ = isolate_data_.long_task_stats_counter_;
    long_task_stats_ = v8::metrics::LongTaskStats{};
  }
}
References isolate_data_, last_long_task_stats_counter_, long_task_stats_, and v8::internal::IsolateData::long_task_stats_counter_.
Referenced by GetCurrentLongTaskStats().
UpdateNoElementsProtectorOnNormalizeElements()
void v8::internal::Isolate::UpdateNoElementsProtectorOnNormalizeElements (DirectHandle< JSObject > object) [inline]
Definition at line 1714 of file isolate.h.
                                     {
    UpdateNoElementsProtectorOnSetElement(object);
  }
Referenced by v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::NormalizeImpl().
UpdateNoElementsProtectorOnSetElement()
void v8::internal::Isolate::UpdateNoElementsProtectorOnSetElement (DirectHandle< JSObject > object)
Definition at line 6347 of file isolate.cc.
                                   {
  DisallowGarbageCollection no_gc;
  if (!object->map()->is_prototype_map()) return;
  if (!Protectors::IsNoElementsIntact(this)) return;
  KnownPrototype obj_type = IsArrayOrObjectOrStringPrototype(*object);
  if (obj_type == KnownPrototype::kNone) return;
  if (obj_type == KnownPrototype::kObject) {
    this->CountUsage(v8::Isolate::kObjectPrototypeHasElements);
  } else if (obj_type == KnownPrototype::kArray) {
    this->CountUsage(v8::Isolate::kArrayPrototypeHasElements);
  }
  Protectors::InvalidateNoElements(this);
}
References CountUsage(), IsArrayOrObjectOrStringPrototype(), kArray, v8::Isolate::kArrayPrototypeHasElements, kNone, kObject, v8::Isolate::kObjectPrototypeHasElements, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
UpdateNoElementsProtectorOnSetLength()
void v8::internal::Isolate::UpdateNoElementsProtectorOnSetLength (DirectHandle< JSObject > object) [inline]
Definition at line 1700 of file isolate.h.
                                                                           {
    UpdateNoElementsProtectorOnSetElement(object);
  }
Referenced by v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::GrowCapacityAndConvertImpl(), and v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::GrowCapacityAndConvertImpl().
UpdateNoElementsProtectorOnSetPrototype()
void v8::internal::Isolate::UpdateNoElementsProtectorOnSetPrototype (DirectHandle< JSObject > object) [inline]
Definition at line 1707 of file isolate.h.
                                                                              {
    UpdateNoElementsProtectorOnSetElement(object);
  }
Referenced by UpdateProtectorsOnSetPrototype().
UpdateNumberStringNotRegexpLikeProtectorOnSetPrototype()
void v8::internal::Isolate::UpdateNumberStringNotRegexpLikeProtectorOnSetPrototype (DirectHandle< JSObject > object)
Definition at line 6380 of file isolate.cc.
                                   {
  if (!Protectors::IsNumberStringNotRegexpLikeIntact(this)) {
    return;
  }
  // We need to protect the prototype chain of `Number.prototype` and
  // `String.prototype`.
  // Since `Object.prototype.__proto__` is not writable, we can assume it
  // doesn't occur here. We detect `Number.prototype` and `String.prototype` by
  // checking for a prototype that is a JSPrimitiveWrapper. This is a safe
  // approximation. Using JSPrimitiveWrapper as prototype should be
  // sufficiently rare.
  DCHECK(!IsJSObjectPrototype(*object));
  if (object->map()->is_prototype_map() && (IsJSPrimitiveWrapper(*object))) {
    Protectors::InvalidateNumberStringNotRegexpLike(this);
  }
}
References v8::internal::DCHECK().
Referenced by UpdateProtectorsOnSetPrototype().
UpdatePromiseHookProtector()
void v8::internal::Isolate::UpdatePromiseHookProtector ()
Definition at line 6565 of file isolate.cc.
                                         {
  if (Protectors::IsPromiseHookIntact(this)) {
    HandleScope scope(this);
    Protectors::InvalidatePromiseHook(this);
  }
}
Referenced by PromiseHookStateUpdated().
UpdateProtectorsOnSetPrototype()
void v8::internal::Isolate::UpdateProtectorsOnSetPrototype (DirectHandle< JSObject > object, DirectHandle< Object > new_prototype)
Definition at line 6362 of file isolate.cc.
                                                                       {
  UpdateNoElementsProtectorOnSetPrototype(object);
  UpdateTypedArraySpeciesLookupChainProtectorOnSetPrototype(object);
  UpdateNumberStringNotRegexpLikeProtectorOnSetPrototype(object);
  UpdateStringWrapperToPrimitiveProtectorOnSetPrototype(object, new_prototype);
}
References UpdateNoElementsProtectorOnSetPrototype(), UpdateNumberStringNotRegexpLikeProtectorOnSetPrototype(), UpdateStringWrapperToPrimitiveProtectorOnSetPrototype(), and UpdateTypedArraySpeciesLookupChainProtectorOnSetPrototype().
Referenced by v8::internal::WasmStruct::AllocatePrototype(), v8::internal::anonymous_namespace{runtime-classes.cc}::InitClassPrototype(), and v8::internal::JSObject::SetPrototype().
UpdateStringWrapperToPrimitiveProtectorOnSetPrototype()
void v8::internal::Isolate::UpdateStringWrapperToPrimitiveProtectorOnSetPrototype (DirectHandle< JSObject > object, DirectHandle< Object > new_prototype)
Definition at line 6398 of file isolate.cc.
                                                                       {
  if (!Protectors::IsStringWrapperToPrimitiveIntact(this)) {
    return;
  }
  // We can have a custom @@toPrimitive on a string wrapper also if we subclass
  // String and the subclass (or one of its subclasses) defines its own
  // @@toPrimitive. Thus we invalidate the protector whenever we detect
  // subclassing String - it should be reasonably rare.
  if (IsStringWrapper(*object) || IsStringWrapper(*new_prototype)) {
    Protectors::InvalidateStringWrapperToPrimitive(this);
  }
}
Referenced by UpdateProtectorsOnSetPrototype().
UpdateTypedArraySpeciesLookupChainProtectorOnSetPrototype()
void v8::internal::Isolate::UpdateTypedArraySpeciesLookupChainProtectorOnSetPrototype (DirectHandle< JSObject > object)
Definition at line 6370 of file isolate.cc.
                                   {
  // Setting the __proto__ of TypedArray constructor could change TypedArray's
  // @@species. So we need to invalidate the @@species protector.
  if (IsTypedArrayConstructor(*object) &&
      Protectors::IsTypedArraySpeciesLookupChainIntact(this)) {
    Protectors::InvalidateTypedArraySpeciesLookupChain(this);
  }
}
Referenced by UpdateProtectorsOnSetPrototype().
use_optimizer()
bool v8::internal::Isolate::use_optimizer ()
Definition at line 6222 of file isolate.cc.
                            {
  // TODO(v8:7700): Update this predicate for a world with multiple tiers.
  return (v8_flags.turbofan || v8_flags.maglev) && !serializer_enabled_ &&
         CpuFeatures::SupportsOptimizer() && !is_precise_count_code_coverage();
}
References is_precise_count_code_coverage(), serializer_enabled_, v8::internal::CpuFeatures::SupportsOptimizer(), and v8::internal::v8_flags.
Referenced by v8::internal::TieringManager::OnInterruptTick().
v8_file_logger()
V8FileLogger* v8::internal::Isolate::v8_file_logger () const [inline]
Definition at line 1207 of file isolate.h.
                                       {
    // Call InitializeLoggingAndCounters() if logging is needed before
    // the isolate is fully initialized.
    DCHECK_NOT_NULL(v8_file_logger_);
    return v8_file_logger_;
  }
References DCHECK_NOT_NULL.
Referenced by v8::internal::Profiler::Disengage(), v8::internal::Profiler::Engage(), IsLoggingCodeCreation(), v8::Shell::LogGetAndStop(), v8::internal::ProfilingScope::ProfilingScope(), v8::internal::ETWJITInterface::EtwIsolateOperations::ResetEtwCodeEventHandler(), v8::internal::ETWJITInterface::EtwIsolateOperations::SetEtwCodeEventHandler(), v8::Isolate::SetJitCodeEventHandler(), and UpdateLogObjectRelocation().
VerifyStaticRoots()
void v8::internal::Isolate::VerifyStaticRoots ()
Definition at line 5418 of file isolate.cc.
                                {
#if V8_STATIC_ROOTS_BOOL
#define STATIC_ROOTS_FAILED_MSG \
  "Read-only heap layout changed. Run `tools/dev/gen-static-roots.py` to " \
  "update static-roots.h."
  static_assert(static_cast<int>(RootIndex::kReadOnlyRootsCount) ==
                    StaticReadOnlyRootsPointerTable.size(),
                STATIC_ROOTS_FAILED_MSG);
  auto& roots = roots_table();
  RootIndex idx = RootIndex::kFirstReadOnlyRoot;
  for (Tagged_t cmp_ptr : StaticReadOnlyRootsPointerTable) {
    Address the_root = roots[idx];
    Address ptr = V8HeapCompressionScheme::DecompressTagged(cmp_ptr);
    CHECK_WITH_MSG(the_root == ptr, STATIC_ROOTS_FAILED_MSG);
    ++idx;
  }
  idx = RootIndex::kFirstReadOnlyRoot;
#define CHECK_NAME(_1, _2, CamelName) \
  CHECK_WITH_MSG(StaticReadOnlyRoot::k##CamelName == \
                     V8HeapCompressionScheme::CompressObject(roots[idx]), \
                 STATIC_ROOTS_FAILED_MSG); \
  ++idx;
  STRONG_READ_ONLY_ROOT_LIST(CHECK_NAME)
#undef CHECK_NAME
  // Check if instance types to map range mappings are still valid.
  //
  // Is##type(map) may be computed by checking if the map pointer lies in a
  // statically known range of addresses, whereas Is##type(instance_type) is the
  // definitive source of truth. If they disagree it means that a particular
  // entry in InstanceTypeChecker::kUniqueMapRangeOfInstanceTypeRangeList is out
  // of date. This can also happen if an instance type is starting to be used by
  // more maps.
  //
  // If this check fails either re-arrange allocations in the read-only heap
  // such that the static map range is restored (consult static-roots.h for a
  // sorted list of addresses) or remove the offending entry from the list.
  for (idx = RootIndex::kFirstRoot; idx <= RootIndex::kLastRoot; ++idx) {
    Tagged<Object> obj = roots_table().slot(idx).load(this);
    if (obj.ptr() == kNullAddress || !IsMap(obj)) continue;
    Tagged<Map> map = Cast<Map>(obj);
#define INSTANCE_TYPE_CHECKER_SINGLE(type, _) \
  CHECK_EQ(InstanceTypeChecker::Is##type(map), \
           InstanceTypeChecker::Is##type(map->instance_type()));
    INSTANCE_TYPE_CHECKERS_SINGLE(INSTANCE_TYPE_CHECKER_SINGLE)
#undef INSTANCE_TYPE_CHECKER_SINGLE
#define INSTANCE_TYPE_CHECKER_RANGE(type, _1, _2) \
  CHECK_EQ(InstanceTypeChecker::Is##type(map), \
           InstanceTypeChecker::Is##type(map->instance_type()));
    INSTANCE_TYPE_CHECKERS_RANGE(INSTANCE_TYPE_CHECKER_RANGE)
#undef INSTANCE_TYPE_CHECKER_RANGE
    // This limit is used in various places as a fast IsJSReceiver check.
    CHECK_IMPLIES(
        InstanceTypeChecker::IsPrimitiveHeapObject(map->instance_type()),
        V8HeapCompressionScheme::CompressObject(map.ptr()) <
            InstanceTypeChecker::kNonJsReceiverMapLimit);
    CHECK_IMPLIES(InstanceTypeChecker::IsJSReceiver(map->instance_type()),
                  V8HeapCompressionScheme::CompressObject(map.ptr()) >=
                      InstanceTypeChecker::kNonJsReceiverMapLimit);
    CHECK(InstanceTypeChecker::kNonJsReceiverMapLimit <
          read_only_heap()->read_only_space()->Size());
    if (InstanceTypeChecker::IsString(map->instance_type())) {
      CHECK_EQ(InstanceTypeChecker::IsString(map),
               InstanceTypeChecker::IsString(map->instance_type()));
      CHECK_EQ(InstanceTypeChecker::IsSeqString(map),
               InstanceTypeChecker::IsSeqString(map->instance_type()));
      CHECK_EQ(InstanceTypeChecker::IsExternalString(map),
               InstanceTypeChecker::IsExternalString(map->instance_type()));
      CHECK_EQ(
          InstanceTypeChecker::IsUncachedExternalString(map),
          InstanceTypeChecker::IsUncachedExternalString(map->instance_type()));
      CHECK_EQ(InstanceTypeChecker::IsInternalizedString(map),
               InstanceTypeChecker::IsInternalizedString(map->instance_type()));
      CHECK_EQ(InstanceTypeChecker::IsConsString(map),
               InstanceTypeChecker::IsConsString(map->instance_type()));
      CHECK_EQ(InstanceTypeChecker::IsSlicedString(map),
               InstanceTypeChecker::IsSlicedString(map->instance_type()));
      CHECK_EQ(InstanceTypeChecker::IsThinString(map),
               InstanceTypeChecker::IsThinString(map->instance_type()));
      CHECK_EQ(InstanceTypeChecker::IsOneByteString(map),
               InstanceTypeChecker::IsOneByteString(map->instance_type()));
      CHECK_EQ(InstanceTypeChecker::IsTwoByteString(map),
               InstanceTypeChecker::IsTwoByteString(map->instance_type()));
      CHECK_EQ(InstanceTypeChecker::IsSharedString(map),
               InstanceTypeChecker::IsSharedString(map->instance_type()));
    }
  }
  // Sanity check the API
  CHECK_EQ(
      v8::internal::Internals::GetRoot(reinterpret_cast<v8::Isolate*>(this),
                                       static_cast<int>(RootIndex::kNullValue)),
      ReadOnlyRoots(this).null_value().ptr());
#undef STATIC_ROOTS_FAILED_MSG
#endif // V8_STATIC_ROOTS_BOOL
}
References CHECK, CHECK_EQ, CHECK_IMPLIES, CHECK_WITH_MSG, v8::internal::V8HeapCompressionSchemeImpl< Cage >::CompressObject(), v8::internal::V8HeapCompressionSchemeImpl< Cage >::DecompressTagged(), v8::internal::Internals::GetRoot(), INSTANCE_TYPE_CHECKERS_RANGE, INSTANCE_TYPE_CHECKERS_SINGLE, v8::internal::InstanceTypeChecker::IsConsString(), v8::internal::InstanceTypeChecker::IsExternalString(), v8::internal::InstanceTypeChecker::IsInternalizedString(), v8::internal::InstanceTypeChecker::IsOneByteString(), v8::internal::InstanceTypeChecker::IsSeqString(), v8::internal::InstanceTypeChecker::IsSharedString(), v8::internal::InstanceTypeChecker::IsSlicedString(), v8::internal::InstanceTypeChecker::IsThinString(), v8::internal::InstanceTypeChecker::IsTwoByteString(), v8::internal::InstanceTypeChecker::IsUncachedExternalString(), v8::internal::kFirstReadOnlyRoot, v8::internal::kFirstRoot, v8::internal::kLastRoot, v8::internal::InstanceTypeChecker::kNonJsReceiverMapLimit, v8::internal::kNullAddress, v8::internal::kReadOnlyRootsCount, v8::internal::FullObjectSlot::load(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), read_only_heap(), roots_table(), v8::internal::RootsTable::slot(), STATIC_ROOTS_FAILED_MSG, and STRONG_READ_ONLY_ROOT_LIST.
Referenced by Init(), and v8::internal::SetupIsolateDelegate::SetupHeapInternal().
WalkCallStackAndPromiseTree()
bool v8::internal::Isolate::WalkCallStackAndPromiseTree (MaybeDirectHandle< JSPromise > rejected_promise, const std::function< void(PromiseHandler)> & callback)
Definition at line 3557 of file isolate.cc.
                                                       {
  bool is_promise_rejection = false;
  DirectHandle<JSPromise> promise;
  if (rejected_promise.ToHandle(&promise)) {
    is_promise_rejection = true;
    // If the promise has reactions, follow them and assume we are done. If
    // it has no reactions, assume promise is returned up the call stack and
    // trace accordingly. If the promise is not pending, it has no reactions
    // and is probably the result of a call to Promise.reject().
    if (promise->status() != Promise::kPending) {
      // Ignore this promise; set to null
      rejected_promise = MaybeDirectHandle<JSPromise>();
    } else if (IsSmi(promise->reactions())) {
      // Also check that there is no outer promise
      DirectHandle<Symbol> key = factory()->promise_handled_by_symbol();
      if (!IsJSPromise(*JSObject::GetDataProperty(this, promise, key))) {
        // Ignore this promise; set to null
        rejected_promise = MaybeDirectHandle<JSPromise>();
      }
    }
  }
  if (!is_promise_rejection && TopExceptionHandlerType(Tagged<Object>()) ==
                                   ExceptionHandlerType::kExternalTryCatch) {
    return true; // caught by external
  }
  // Search for an exception handler by performing a full walk over the stack.
  for (StackFrameSummaryIterator iter(this); !iter.done(); iter.Advance()) {
    Isolate::CatchType prediction = PredictExceptionCatchAtFrame(iter);
    bool caught;
    if (rejected_promise.is_null()) {
      switch (prediction) {
        case NOT_CAUGHT:
          // Uncaught unless this is a promise rejection and the code will call
          // .catch()
          caught = is_promise_rejection && CallsCatchMethod(iter);
          break;
        case CAUGHT_BY_ASYNC_AWAIT:
          // Uncaught unless this is a promise rejection and the code will call
          // .catch()
          caught = is_promise_rejection && CallsCatchMethod(iter);
          // Exceptions turn into promise rejections here
          is_promise_rejection = true;
          break;
        case CAUGHT_BY_PROMISE:
          // Exceptions turn into promise rejections here
          // TODO(leese): Perhaps we can handle the case where the reject method
          // is called in the promise constructor and it is still on the stack
          // by ignoring all try/catches on the stack until we get to the right
          // CAUGHT_BY_PROMISE?
          is_promise_rejection = true;
          caught = false;
          break;
        case CAUGHT_BY_EXTERNAL:
          caught = !is_promise_rejection;
          break;
        case CAUGHT_BY_JAVASCRIPT:
          caught = true;
          // Unless this is a promise rejection and the function is not async...
          DCHECK(iter.has_frame_summary());
          const FrameSummary& summary = iter.frame_summary();
          if (is_promise_rejection && summary.IsJavaScript()) {
            // If the catch happens in an async function, assume it will
            // await this promise. Alternately, if the code will call .catch,
            // assume it is on this promise.
            caught = IsAsyncFunction(iter.frame_summary()
                                         .AsJavaScript()
                                         .function()
                                         ->shared()
                                         ->kind()) ||
                     CallsCatchMethod(iter);
          }
          break;
      }
    } else {
      // The frame that calls the reject handler will not catch that promise
      // regardless of what else it does. We will trace where this rejection
      // goes according to its reaction callbacks, but we first need to handle
      // the topmost debuggable frame just to ensure there is a debuggable
      // frame and to permit ignore listing there.
      caught = false;
    }
    if (iter.frame()->is_javascript()) {
      bool debuggable = false;
      DCHECK(iter.has_frame_summary());
      const FrameSummary& summary = iter.frame_summary();
      if (summary.IsJavaScript()) {
        const auto& info = summary.AsJavaScript().function()->shared();
        if (info->IsSubjectToDebugging()) {
          callback({*info, false});
          debuggable = true;
        }
      }
      // Ignore the rest of the call stack if this is a rejection and the
      // promise has handlers; we will trace where the rejection goes instead
      // of where it came from.
      if (debuggable && !rejected_promise.is_null()) {
        break;
      }
    }
    if (caught) {
      return true;
    }
  }
  if (rejected_promise.is_null()) {
    // Now follow promises if this is a promise reaction job.
    rejected_promise = TryGetCurrentTaskPromise(this);
  }
  if (rejected_promise.ToHandle(&promise)) {
    return WalkPromiseTreeInternal(this, promise, callback);
  }
  // Nothing caught.
  return false;
}
References v8::internal::anonymous_namespace{isolate.cc}::CallsCatchMethod(), CAUGHT_BY_ASYNC_AWAIT, CAUGHT_BY_EXTERNAL, CAUGHT_BY_JAVASCRIPT, CAUGHT_BY_PROMISE, v8::internal::DCHECK(), factory(), v8::internal::MaybeDirectHandle< T >::is_null(), v8::internal::IsAsyncFunction(), v8::internal::IsSmi(), kExternalTryCatch, v8::internal::key, v8::Promise::kPending, NOT_CAUGHT, v8::internal::anonymous_namespace{isolate.cc}::PredictExceptionCatchAtFrame(), v8::internal::MaybeDirectHandle< T >::ToHandle(), TopExceptionHandlerType(), v8::internal::anonymous_namespace{isolate.cc}::TryGetCurrentTaskPromise(), and v8::internal::anonymous_namespace{isolate.cc}::WalkPromiseTreeInternal().
Referenced by v8::internal::Debug::OnException().
was_locker_ever_used()
bool v8::internal::Isolate::was_locker_ever_used () const [inline]
Definition at line 1769 of file isolate.h.
                                    {
    return was_locker_ever_used_.load(std::memory_order_relaxed);
  }
Referenced by v8::internal::CppHeap::CurrentThreadIsHeapThread(), v8::HandleScope::Initialize(), v8::Isolate::MemoryPressureNotification(), v8::internal::CpuSampler::SampleStack(), and v8::internal::Ticker::SampleStack().
Friends And Related Function Documentation
GlobalSafepoint
friend class GlobalSafepoint [friend]
Definition at line 2980 of file isolate.h.
heap::HeapTester
friend class heap::HeapTester [friend]
Definition at line 2981 of file isolate.h.
IsolateForPointerCompression
friend class IsolateForPointerCompression [friend]
Definition at line 2982 of file isolate.h.
IsolateForSandbox
friend class IsolateForSandbox [friend]
Definition at line 2983 of file isolate.h.
IsolateGroup
friend class IsolateGroup [friend]
Definition at line 2984 of file isolate.h.
SharedHeapNoClientsTest
friend class SharedHeapNoClientsTest [friend]
Definition at line 2986 of file isolate.h.
TestSerializer
friend class TestSerializer [friend]
Definition at line 2985 of file isolate.h.
Member Data Documentation
abort_on_uncaught_exception_callback_
v8::Isolate::AbortOnUncaughtExceptionCallback v8::internal::Isolate::abort_on_uncaught_exception_callback_ = nullptr [private]
Definition at line 2871 of file isolate.h.
Referenced by CreateMessageOrAbort(), and SetAbortOnUncaughtExceptionCallback().
active_dynamic_regexp_result_vectors_
std::unordered_set<int32_t*> v8::internal::Isolate::active_dynamic_regexp_result_vectors_ [private]
Definition at line 2644 of file isolate.h.
Referenced by Deinit().
add_crash_key_callback_
AddCrashKeyCallback v8::internal::Isolate::add_crash_key_callback_ = nullptr [private]
Definition at line 2958 of file isolate.h.
Referenced by AddCrashKeysForIsolateAndHeapPointers(), and SetAddCrashKeyCallback().
allocator_
AccountingAllocator* v8::internal::Isolate::allocator_ = nullptr [private]
Definition at line 2620 of file isolate.h.
Referenced by ~Isolate().
allow_atomics_wait_
bool v8::internal::Isolate::allow_atomics_wait_ = true [private]
Definition at line 2873 of file isolate.h.
api_interrupts_queue_
std::queue<InterruptEntry> v8::internal::Isolate::api_interrupts_queue_ [private]
Definition at line 2753 of file isolate.h.
Referenced by InvokeApiInterruptCallbacks(), and RequestInterrupt().
array_buffer_allocator_
v8::ArrayBuffer::Allocator* v8::internal::Isolate::array_buffer_allocator_ = nullptr [private]
Definition at line 2852 of file isolate.h.
array_buffer_allocator_shared_
std::shared_ptr<v8::ArrayBuffer::Allocator> v8::internal::Isolate::array_buffer_allocator_shared_ [private]
Definition at line 2853 of file isolate.h.
array_buffer_max_size_
size_t v8::internal::Isolate::array_buffer_max_size_ = 0 [private]
Definition at line 2854 of file isolate.h.
ast_string_constants_
const AstStringConstants* v8::internal::Isolate::ast_string_constants_ = nullptr [private]
Definition at line 2735 of file isolate.h.
Referenced by Deinit(), and Init().
async_counters_
std::shared_ptr<Counters> v8::internal::Isolate::async_counters_ [private]
Definition at line 2598 of file isolate.h.
Referenced by InitializeCounters().
async_event_delegate_
debug::AsyncEventDelegate* v8::internal::Isolate::async_event_delegate_ = nullptr [private]
Definition at line 2864 of file isolate.h.
Referenced by OnAsyncFunctionSuspended(), OnPromiseAfter(), OnPromiseBefore(), OnPromiseThen(), OnStackTraceCaptured(), and PromiseHookStateUpdated().
async_waiter_queue_nodes_
std::list<std::unique_ptr<detail::WaiterQueueNode> > v8::internal::Isolate::async_waiter_queue_nodes_ [private]
Definition at line 2925 of file isolate.h.
Referenced by async_waiter_queue_nodes(), and Deinit().
battery_saver_mode_enabled_
std::atomic<bool> v8::internal::Isolate::battery_saver_mode_enabled_ = false [private]
Definition at line 2657 of file isolate.h.
before_call_entered_callbacks_
std::vector<BeforeCallEnteredCallback> v8::internal::Isolate::before_call_entered_callbacks_ [private]
Definition at line 2805 of file isolate.h.
Referenced by AddBeforeCallEnteredCallback(), FireBeforeCallEnteredCallback(), and RemoveBeforeCallEnteredCallback().
bigint_processor_
bigint::Processor* v8::internal::Isolate::bigint_processor_ = nullptr [private]
Definition at line 2626 of file isolate.h.
Referenced by Init(), and ~Isolate().
boilerplate_migration_access_
base::Mutex v8::internal::Isolate::boilerplate_migration_access_ [private]
Definition at line 2605 of file isolate.h.
bootstrapper_
Bootstrapper* v8::internal::Isolate::bootstrapper_ = nullptr [private]
Definition at line 2595 of file isolate.h.
Referenced by Deinit(), Init(), and ~Isolate().
break_access_
base::RecursiveMutex v8::internal::Isolate::break_access_ [private]
Definition at line 2599 of file isolate.h.
builtins_
Builtins v8::internal::Isolate::builtins_ [private]
Definition at line 2628 of file isolate.h.
Referenced by Deinit(), HashIsolateForEmbeddedBlob(), and InitializeBuiltinJSDispatchTable().
builtins_constants_table_builder_
BuiltinsConstantsTableBuilder* v8::internal::Isolate::builtins_constants_table_builder_ = nullptr [private]
Definition at line 2834 of file isolate.h.
Referenced by Init().
builtins_effects_analyzer_
BuiltinsEffectsAnalyzer* v8::internal::Isolate::builtins_effects_analyzer_ = nullptr [private]
Definition at line 2629 of file isolate.h.
Referenced by ~Isolate().
call_completed_callbacks_
std::vector<CallCompletedCallback> v8::internal::Isolate::call_completed_callbacks_ [private]
Definition at line 2808 of file isolate.h.
Referenced by AddCallCompletedCallback(), FireCallCompletedCallbackInternal(), and RemoveCallCompletedCallback().
cancelable_task_manager_
CancelableTaskManager* v8::internal::Isolate::cancelable_task_manager_ = nullptr [private]
Definition at line 2860 of file isolate.h.
Referenced by ~Isolate().
capture_stack_trace_for_uncaught_exceptions_
bool v8::internal::Isolate::capture_stack_trace_for_uncaught_exceptions_ = false [private]
Definition at line 2613 of file isolate.h.
Referenced by CaptureAndSetErrorStack(), CreateMessage(), get_capture_stack_trace_for_uncaught_exceptions(), and SetCaptureStackTraceForUncaughtExceptions().
code_coverage_mode_
std::atomic<debug::CoverageMode> v8::internal::Isolate::code_coverage_mode_ [private]
Initial value:
{
      debug::CoverageMode::kBestEffort}
Definition at line 2654 of file isolate.h.
code_pages_
std::atomic<std::vector<MemoryRange>*> v8::internal::Isolate::code_pages_ {nullptr} [private]
Definition at line 2936 of file isolate.h.
Referenced by GetCodePages(), and SetCodePages().
code_pages_buffer1_
std::vector<MemoryRange> v8::internal::Isolate::code_pages_buffer1_ [private]
Definition at line 2937 of file isolate.h.
Referenced by AddCodeMemoryRange(), InitializeCodeRanges(), and RemoveCodeMemoryChunk().
code_pages_buffer2_
std::vector<MemoryRange> v8::internal::Isolate::code_pages_buffer2_ [private]
Definition at line 2938 of file isolate.h.
Referenced by AddCodeMemoryRange(), and RemoveCodeMemoryChunk().
code_pages_mutex_
base::Mutex v8::internal::Isolate::code_pages_mutex_ [private]
Definition at line 2940 of file isolate.h.
Referenced by AddCodeMemoryRange().
compilation_cache_
CompilationCache* v8::internal::Isolate::compilation_cache_ = nullptr [private]
Definition at line 2597 of file isolate.h.
Referenced by Init(), and ~Isolate().
compiler_cache_
compiler::PerIsolateCompilerCache* v8::internal::Isolate::compiler_cache_ = nullptr [private]
Definition at line 2739 of file isolate.h.
Referenced by Deinit().
compiler_zone_
Zone* v8::internal::Isolate::compiler_zone_ = nullptr [private]
Definition at line 2742 of file isolate.h.
Referenced by Deinit().
console_delegate_
debug::ConsoleDelegate* v8::internal::Isolate::console_delegate_ = nullptr [private]
Definition at line 2862 of file isolate.h.
current_async_task_id_
uint32_t v8::internal::Isolate::current_async_task_id_ = 0 [private]
Definition at line 2866 of file isolate.h.
Referenced by OnAsyncFunctionSuspended(), and OnPromiseThen().
current_deoptimizer_
Deoptimizer* v8::internal::Isolate::current_deoptimizer_ = nullptr [private]
Definition at line 2610 of file isolate.h.
Referenced by ~Isolate().
date_cache_
DateCache* v8::internal::Isolate::date_cache_ = nullptr [private]
Definition at line 2645 of file isolate.h.
Referenced by Init(), set_date_cache(), and ~Isolate().
debug_
Debug* v8::internal::Isolate::debug_ = nullptr [private]
Definition at line 2732 of file isolate.h.
Referenced by Isolate(), NeedsSourcePositions(), and ~Isolate().
define_own_stub_cache_
StubCache* v8::internal::Isolate::define_own_stub_cache_ = nullptr [private]
Definition at line 2609 of file isolate.h.
Referenced by Init(), and ~Isolate().
deoptimizer_lazy_throw_
bool v8::internal::Isolate::deoptimizer_lazy_throw_ = false [private]
Definition at line 2611 of file isolate.h.
descriptor_lookup_cache_
DescriptorLookupCache* v8::internal::Isolate::descriptor_lookup_cache_ = nullptr [private]
Definition at line 2617 of file isolate.h.
Referenced by Init(), and ~Isolate().
detailed_source_positions_for_profiling_
bool v8::internal::Isolate::detailed_source_positions_for_profiling_ [private]
Definition at line 2774 of file isolate.h.
elements_deletion_counter_
size_t v8::internal::Isolate::elements_deletion_counter_ = 0 [private]
Definition at line 2881 of file isolate.h.
embedded_blob_code_
const uint8_t* v8::internal::Isolate::embedded_blob_code_ = nullptr [private]
Definition at line 2847 of file isolate.h.
Referenced by ClearEmbeddedBlob(), embedded_blob_code(), MaybeRemapEmbeddedBuiltinsIntoCodeRange(), and SetEmbeddedBlob().
embedded_blob_code_size_
uint32_t v8::internal::Isolate::embedded_blob_code_size_ = 0 [private]
Definition at line 2848 of file isolate.h.
Referenced by ClearEmbeddedBlob(), embedded_blob_code_size(), MaybeRemapEmbeddedBuiltinsIntoCodeRange(), and SetEmbeddedBlob().
embedded_blob_data_
const uint8_t* v8::internal::Isolate::embedded_blob_data_ = nullptr [private]
Definition at line 2849 of file isolate.h.
Referenced by ClearEmbeddedBlob(), embedded_blob_data(), and SetEmbeddedBlob().
embedded_blob_data_size_
uint32_t v8::internal::Isolate::embedded_blob_data_size_ = 0 [private]
Definition at line 2850 of file isolate.h.
Referenced by ClearEmbeddedBlob(), embedded_blob_data_size(), and SetEmbeddedBlob().
embedded_file_writer_
EmbeddedFileWriterInterface* v8::internal::Isolate::embedded_file_writer_ = nullptr [private]
Definition at line 2885 of file isolate.h.
Referenced by GetExternallyCompiledFilename(), GetExternallyCompiledFilenameCount(), LookupOrAddExternallyCompiledFilename(), and PrepareBuiltinSourcePositionMap().
enable_ro_allocation_for_snapshot_
bool v8::internal::Isolate::enable_ro_allocation_for_snapshot_ = false [private]
Definition at line 2787 of file isolate.h.
entry_stack_
std::atomic<EntryStackItem*> v8::internal::Isolate::entry_stack_ = nullptr [private]
Definition at line 2590 of file isolate.h.
Referenced by Enter(), Exit(), and ~Isolate().
eternal_handles_
EternalHandles* v8::internal::Isolate::eternal_handles_ = nullptr [private]
Definition at line 2624 of file isolate.h.
Referenced by Init(), and ~Isolate().
feedback_vector_access_
base::Mutex v8::internal::Isolate::feedback_vector_access_ [private]
Definition at line 2600 of file isolate.h.
flush_denormals_
bool v8::internal::Isolate::flush_denormals_ = false [private]
Definition at line 2874 of file isolate.h.
Referenced by Init().
force_slow_path_
bool v8::internal::Isolate::force_slow_path_ = false [private]
Definition at line 2784 of file isolate.h.
Referenced by Init().
full_transition_array_access_
base::Mutex v8::internal::Isolate::full_transition_array_access_ [private]
Definition at line 2602 of file isolate.h.
futex_wait_list_node_
FutexWaitListNode v8::internal::Isolate::futex_wait_list_node_ [private]
Definition at line 2858 of file isolate.h.
fuzzer_rng_
base::RandomNumberGenerator* v8::internal::Isolate::fuzzer_rng_ = nullptr [private]
Definition at line 2647 of file isolate.h.
Referenced by fuzzer_rng(), and ~Isolate().
global_handles_
GlobalHandles* v8::internal::Isolate::global_handles_ = nullptr [private]
Definition at line 2622 of file isolate.h.
Referenced by Init(), and ~Isolate().
global_safepoint_
std::unique_ptr<GlobalSafepoint> v8::internal::Isolate::global_safepoint_ [private]
Definition at line 2929 of file isolate.h.
Referenced by Init().
global_safepoint_next_client_isolate_
Isolate* v8::internal::Isolate::global_safepoint_next_client_isolate_ = nullptr [private]
Definition at line 2932 of file isolate.h.
Referenced by v8::internal::GlobalSafepoint::AppendClient(), v8::internal::GlobalSafepoint::IterateClientIsolates(), and v8::internal::GlobalSafepoint::RemoveClient().
global_safepoint_prev_client_isolate_
Isolate* v8::internal::Isolate::global_safepoint_prev_client_isolate_ = nullptr [private]
Definition at line 2931 of file isolate.h.
Referenced by v8::internal::GlobalSafepoint::AppendClient(), and v8::internal::GlobalSafepoint::RemoveClient().
handle_scope_implementer_
HandleScopeImplementer* v8::internal::Isolate::handle_scope_implementer_ = nullptr [private]
Definition at line 2618 of file isolate.h.
Referenced by Init(), and ~Isolate().
has_fatal_error_
bool v8::internal::Isolate::has_fatal_error_ = false [private]
Definition at line 2696 of file isolate.h.
Referenced by Init().
heap_
Heap v8::internal::Isolate::heap_ [private]
Definition at line 2582 of file isolate.h.
Referenced by CountUsage(), Deinit(), HashIsolateForEmbeddedBlob(), Init(), InitializeIsShortBuiltinCallsEnabled(), MaybeRemapEmbeddedBuiltinsIntoCodeRange(), and SetUpFromReadOnlyArtifacts().
host_create_shadow_realm_context_callback_
HostCreateShadowRealmContextCallback v8::internal::Isolate::host_create_shadow_realm_context_callback_ = nullptr [private]
Definition at line 2673 of file isolate.h.
Referenced by RunHostCreateShadowRealmContextCallback(), and SetHostCreateShadowRealmContextCallback().
host_import_module_dynamically_callback_
HostImportModuleDynamicallyCallback v8::internal::Isolate::host_import_module_dynamically_callback_ [private]
Initial value:
=
      nullptr
Definition at line 2650 of file isolate.h.
Referenced by RunHostImportModuleDynamicallyCallback(), and SetHostImportModuleDynamicallyCallback().
host_import_module_with_phase_dynamically_callback_
HostImportModuleWithPhaseDynamicallyCallback v8::internal::Isolate::host_import_module_with_phase_dynamically_callback_ = nullptr [private]
Definition at line 2653 of file isolate.h.
Referenced by RunHostImportModuleDynamicallyCallback(), and SetHostImportModuleWithPhaseDynamicallyCallback().
host_initialize_import_meta_object_callback_
HostInitializeImportMetaObjectCallback v8::internal::Isolate::host_initialize_import_meta_object_callback_ = nullptr [private]
Definition at line 2671 of file isolate.h.
Referenced by RunHostInitializeImportMetaObjectCallback(), and SetHostInitializeImportMetaObjectCallback().
id_
const int v8::internal::Isolate::id_ [private]
Definition at line 2589 of file isolate.h.
Referenced by GetContextFromRecorderContextId().
incomplete_message_
StringStream* v8::internal::Isolate::incomplete_message_ = nullptr [private]
Definition at line 2593 of file isolate.h.
Referenced by PrintStack(), and StackTraceString().
initialized_
bool v8::internal::Isolate::initialized_ = false [private]
Definition at line 2789 of file isolate.h.
Referenced by CollectSourcePositionsForAllBytecodeArrays(), and Init().
initialized_from_snapshot_
bool v8::internal::Isolate::initialized_from_snapshot_ = false [private]
Definition at line 2699 of file isolate.h.
Referenced by Init().
inner_pointer_to_code_cache_
InnerPointerToCodeCache* v8::internal::Isolate::inner_pointer_to_code_cache_ = nullptr [private]
Definition at line 2621 of file isolate.h.
Referenced by Deinit(), and Init().
internalized_string_access_
base::Mutex v8::internal::Isolate::internalized_string_access_ [private]
Definition at line 2601 of file isolate.h.
interpreter_
interpreter::Interpreter* v8::internal::Isolate::interpreter_ = nullptr [private]
Definition at line 2737 of file isolate.h.
Referenced by Deinit(), and Init().
is_frozen_
bool v8::internal::Isolate::is_frozen_ = false [private]
Definition at line 2978 of file isolate.h.
is_shared_space_isolate_
bool v8::internal::Isolate::is_shared_space_isolate_ {false} [private]
Definition at line 2579 of file isolate.h.
Referenced by v8::internal::IsolateGroup::AddIsolate(), and Init().
is_short_builtin_calls_enabled_
bool v8::internal::Isolate::is_short_builtin_calls_enabled_ = false [private]
Definition at line 2702 of file isolate.h.
Referenced by InitializeIsShortBuiltinCallsEnabled().
isolate_addresses_
Address v8::internal::Isolate::isolate_addresses_[kIsolateAddressCount+1] = {} [private]
Definition at line 2594 of file isolate.h.
Referenced by get_address_from_id().
isolate_data_
IsolateData v8::internal::Isolate::isolate_data_ [private]
Definition at line 2576 of file isolate.h.
Referenced by CheckIsolateLayout(), Deinit(), Init(), InitializeBuiltinJSDispatchTable(), UnwindAndFindHandler(), and UpdateLongTaskStats().
isolate_group_
IsolateGroup* v8::internal::Isolate::isolate_group_ [private]
Definition at line 2581 of file isolate.h.
Referenced by Init().
jitless_
bool v8::internal::Isolate::jitless_ = false [private]
Definition at line 2790 of file isolate.h.
Referenced by Init(), and RequiresCodeRange().
jsregexp_canonrange_
unibrow::Mapping<unibrow::CanonicalizationRange> v8::internal::Isolate::jsregexp_canonrange_ [private]
Definition at line 2636 of file isolate.h.
jsregexp_uncanonicalize_
unibrow::Mapping<unibrow::Ecma262UnCanonicalize> v8::internal::Isolate::jsregexp_uncanonicalize_ [private]
Definition at line 2635 of file isolate.h.
kBMMaxShift
const int v8::internal::Isolate::kBMMaxShift = 250 [static]
Definition at line 1153 of file isolate.h.
kJSRegexpStaticOffsetsVectorSize
const int v8::internal::Isolate::kJSRegexpStaticOffsetsVectorSize = 128 [static]
Definition at line 1559 of file isolate.h.
Referenced by v8::internal::RegExpResultVectorScope::Initialize(), v8::internal::RegExpBuiltinsAssembler::LoadOrAllocateRegExpResultVector(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal_Batched(), and v8::internal::RegExpGlobalExecRunner::RegExpGlobalExecRunner().
kUC16AlphabetSize
const int v8::internal::Isolate::kUC16AlphabetSize = 256 [static]
Definition at line 1152 of file isolate.h.
last_long_task_stats_counter_
size_t v8::internal::Isolate::last_long_task_stats_counter_ = 0 [private]
Definition at line 2821 of file isolate.h.
Referenced by UpdateLongTaskStats().
last_recorder_context_id_
uintptr_t v8::internal::Isolate::last_recorder_context_id_ = 0 [private]
Definition at line 2817 of file isolate.h.
Referenced by GetOrRegisterRecorderContextId().
lazy_compile_dispatcher_
std::unique_ptr<LazyCompileDispatcher> v8::internal::Isolate::lazy_compile_dispatcher_ [private]
Definition at line 2744 of file isolate.h.
Referenced by Deinit(), and Init().
load_stub_cache_
StubCache* v8::internal::Isolate::load_stub_cache_ = nullptr [private]
Definition at line 2607 of file isolate.h.
Referenced by Init(), and ~Isolate().
log_object_relocation_
bool v8::internal::Isolate::log_object_relocation_ = false [private]
Definition at line 2713 of file isolate.h.
Referenced by UpdateLogObjectRelocation().
logger_
Logger* v8::internal::Isolate::logger_ = nullptr [private]
Definition at line 2733 of file isolate.h.
Referenced by Deinit().
long_task_stats_
v8::metrics::LongTaskStats v8::internal::Isolate::long_task_stats_ [private]
Definition at line 2822 of file isolate.h.
Referenced by GetCurrentLongTaskStats(), and UpdateLongTaskStats().
main_thread_local_isolate_
std::unique_ptr<LocalIsolate> v8::internal::Isolate::main_thread_local_isolate_ [private]
Definition at line 2868 of file isolate.h.
Referenced by Deinit(), and Init().
managed_ptr_destructors_head_
ManagedPtrDestructor* v8::internal::Isolate::managed_ptr_destructors_head_ = nullptr [private]
Definition at line 2877 of file isolate.h.
Referenced by RegisterManagedPtrDestructor(), ReleaseSharedPtrs(), and UnregisterManagedPtrDestructor().
managed_ptr_destructors_mutex_
base::Mutex v8::internal::Isolate::managed_ptr_destructors_mutex_ [private]
Definition at line 2876 of file isolate.h.
Referenced by RegisterManagedPtrDestructor(), ReleaseSharedPtrs(), and UnregisterManagedPtrDestructor().
map_updater_access_
base::Mutex v8::internal::Isolate::map_updater_access_ [private]
Definition at line 2604 of file isolate.h.
materialized_object_store_
MaterializedObjectStore* v8::internal::Isolate::materialized_object_store_ = nullptr [private]
Definition at line 2612 of file isolate.h.
Referenced by Init(), UnwindAndFindHandler(), and ~Isolate().
memory_saver_mode_enabled_
std::atomic<bool> v8::internal::Isolate::memory_saver_mode_enabled_ = false [private]
Definition at line 2658 of file isolate.h.
metrics_recorder_
std::shared_ptr<metrics::Recorder> v8::internal::Isolate::metrics_recorder_ [private]
Definition at line 2816 of file isolate.h.
Referenced by Deinit(), and Init().
next_module_async_evaluation_ordinal_
unsigned v8::internal::Isolate::next_module_async_evaluation_ordinal_ [private]
Definition at line 2802 of file isolate.h.
next_optimization_id_
std::atomic<int> v8::internal::Isolate::next_optimization_id_ = 0 [private]
Definition at line 2792 of file isolate.h.
next_unique_sfi_id_
std::atomic<uint32_t> v8::internal::Isolate::next_unique_sfi_id_ [private]
Definition at line 2800 of file isolate.h.
optimizing_compile_dispatcher_
OptimizingCompileDispatcher* v8::internal::Isolate::optimizing_compile_dispatcher_ = nullptr [private]
Definition at line 2777 of file isolate.h.
Referenced by Deinit(), Init(), and SetOptimizingCompileDispatcherForTesting().
owns_shareable_data_
bool v8::internal::Isolate::owns_shareable_data_ = true [private]
Definition at line 2711 of file isolate.h.
Referenced by v8::internal::IsolateGroup::AddIsolate().
persistent_handles_list_
std::unique_ptr<PersistentHandlesList> v8::internal::Isolate::persistent_handles_list_ [private]
Definition at line 2779 of file isolate.h.
prepare_stack_trace_callback_
PrepareStackTraceCallback v8::internal::Isolate::prepare_stack_trace_callback_ = nullptr [private]
Definition at line 2887 of file isolate.h.
Referenced by HasPrepareStackTraceCallback(), RunPrepareStackTraceCallback(), and SetPrepareStackTraceCallback().
preprocessing_exception_
bool v8::internal::Isolate::preprocessing_exception_ = false [private]
Definition at line 2775 of file isolate.h.
Referenced by Throw().
priority_
std::atomic<v8::Isolate::Priority> v8::internal::Isolate::priority_ [private]
Initial value:
=
      v8::Isolate::Priority::kUserBlocking
Definition at line 2706 of file isolate.h.
Referenced by SetPriority().
promise_hook_
PromiseHook v8::internal::Isolate::promise_hook_ = nullptr [private]
Definition at line 2649 of file isolate.h.
Referenced by PromiseHookStateUpdated(), RunPromiseHook(), and SetPromiseHook().
promise_hook_flags_
uint32_t v8::internal::Isolate::promise_hook_flags_ = 0 [private]
Definition at line 2865 of file isolate.h.
Referenced by PromiseHookStateUpdated().
random_number_generator_
base::RandomNumberGenerator* v8::internal::Isolate::random_number_generator_ = nullptr [private]
Definition at line 2646 of file isolate.h.
Referenced by random_number_generator(), and ~Isolate().
read_only_heap_
ReadOnlyHeap* v8::internal::Isolate::read_only_heap_ = nullptr [private]
Definition at line 2583 of file isolate.h.
Referenced by InitializeBuiltinJSDispatchTable(), and SetUpFromReadOnlyArtifacts().
recorder_context_id_map_
std::unordered_map<uintptr_t, v8::Global<v8::Context> > v8::internal::Isolate::recorder_context_id_map_ [private]
Definition at line 2819 of file isolate.h.
Referenced by Deinit(), GetContextFromRecorderContextId(), GetOrRegisterRecorderContextId(), and RemoveContextIdCallback().
regexp_indices_
std::vector<int> v8::internal::Isolate::regexp_indices_ [private]
Definition at line 2641 of file isolate.h.
regexp_macro_assembler_canonicalize_
unibrow::Mapping<unibrow::Ecma262Canonicalize> v8::internal::Isolate::regexp_macro_assembler_canonicalize_ [private]
Definition at line 2638 of file isolate.h.
regexp_stack_
RegExpStack* v8::internal::Isolate::regexp_stack_ = nullptr [private]
Definition at line 2640 of file isolate.h.
Referenced by Init(), and ~Isolate().
release_cpp_heap_callback_
v8::Isolate::ReleaseCppHeapCallback v8::internal::Isolate::release_cpp_heap_callback_ = nullptr [private]
Definition at line 2648 of file isolate.h.
Referenced by RunReleaseCppHeapCallback(), and SetReleaseCppHeapCallback().
runtime_state_
RuntimeState v8::internal::Isolate::runtime_state_ [private]
Definition at line 2627 of file isolate.h.
serializer_enabled_
bool v8::internal::Isolate::serializer_enabled_ = false [private]
Definition at line 2693 of file isolate.h.
Referenced by GetOrRegisterRecorderContextId(), and use_optimizer().
setup_delegate_
SetupIsolateDelegate* v8::internal::Isolate::setup_delegate_ = nullptr [private]
Definition at line 2630 of file isolate.h.
Referenced by Init().
shared_function_info_access_
base::Mutex v8::internal::Isolate::shared_function_info_access_ [private]
Definition at line 2603 of file isolate.h.
shared_heap_object_cache_
std::vector<Tagged<Object> > v8::internal::Isolate::shared_heap_object_cache_ [private]
Definition at line 2830 of file isolate.h.
Referenced by Init().
shared_space_isolate_
std::optional<Isolate*> v8::internal::Isolate::shared_space_isolate_ [private]
Definition at line 2904 of file isolate.h.
Referenced by Deinit(), and Init().
shared_struct_type_registry_
std::unique_ptr<SharedStructTypeRegistry> v8::internal::Isolate::shared_struct_type_registry_ [private]
Definition at line 2909 of file isolate.h.
Referenced by Deinit(), and Init().
stack_size_
size_t v8::internal::Isolate::stack_size_ [private]
Definition at line 2944 of file isolate.h.
stack_trace_for_uncaught_exceptions_frame_limit_
int v8::internal::Isolate::stack_trace_for_uncaught_exceptions_frame_limit_ = 0 [private]
Definition at line 2614 of file isolate.h.
Referenced by CaptureAndSetErrorStack(), CreateMessage(), and SetCaptureStackTraceForUncaughtExceptions().
stack_trace_for_uncaught_exceptions_options_
StackTrace::StackTraceOptions v8::internal::Isolate::stack_trace_for_uncaught_exceptions_options_ [private]
Initial value:
=
      StackTrace::kOverview
Definition at line 2615 of file isolate.h.
Referenced by CaptureAndSetErrorStack(), CreateMessage(), and SetCaptureStackTraceForUncaughtExceptions().
stack_trace_nesting_level_
int v8::internal::Isolate::stack_trace_nesting_level_ = 0 [private]
Definition at line 2591 of file isolate.h.
Referenced by PrintStack(), and StackTraceString().
startup_object_cache_
std::vector<Tagged<Object> > v8::internal::Isolate::startup_object_cache_ [private]
Definition at line 2824 of file isolate.h.
Referenced by Init().
store_stub_cache_
StubCache* v8::internal::Isolate::store_stub_cache_ = nullptr [private]
Definition at line 2608 of file isolate.h.
Referenced by Init(), and ~Isolate().
stress_deopt_count_
uint64_t v8::internal::Isolate::stress_deopt_count_ = 0 [private]
Definition at line 2782 of file isolate.h.
Referenced by Deinit(), and Init().
string_forwarding_table_
std::unique_ptr<StringForwardingTable> v8::internal::Isolate::string_forwarding_table_ [private]
Definition at line 2587 of file isolate.h.
Referenced by Deinit(), and Init().
string_table_
std::unique_ptr<StringTable> v8::internal::Isolate::string_table_ [private]
Definition at line 2586 of file isolate.h.
Referenced by Deinit(), and Init().
task_runner_
std::shared_ptr<v8::TaskRunner> v8::internal::Isolate::task_runner_ [private]
Definition at line 2856 of file isolate.h.
Referenced by Init().
thread_data_table_
ThreadDataTable v8::internal::Isolate::thread_data_table_ [private]
Definition at line 2901 of file isolate.h.
Referenced by Deinit(), DiscardPerThreadDataForThisThread(), FindOrAllocatePerThreadDataForThisThread(), and FindPerThreadDataForThread().
thread_data_table_mutex_
base::Mutex v8::internal::Isolate::thread_data_table_mutex_ [private]
Definition at line 2900 of file isolate.h.
Referenced by Deinit(), DiscardPerThreadDataForThisThread(), FindOrAllocatePerThreadDataForThisThread(), and FindPerThreadDataForThread().
thread_manager_
ThreadManager* v8::internal::Isolate::thread_manager_ = nullptr [private]
Definition at line 2625 of file isolate.h.
Referenced by DiscardPerThreadDataForThisThread(), Isolate(), and ~Isolate().
tiering_manager_
TieringManager* v8::internal::Isolate::tiering_manager_ = nullptr [private]
Definition at line 2596 of file isolate.h.
Referenced by Deinit(), and Init().
time_millis_at_init_
double v8::internal::Isolate::time_millis_at_init_ = 0 [private]
Definition at line 2722 of file isolate.h.
Referenced by Init().
total_regexp_code_generated_
size_t v8::internal::Isolate::total_regexp_code_generated_ = 0 [private]
Definition at line 2879 of file isolate.h.
Referenced by IncreaseTotalRegexpCodeGenerated().
traced_handles_
TracedHandles v8::internal::Isolate::traced_handles_ [private]
Definition at line 2623 of file isolate.h.
tracing_cpu_profiler_
std::unique_ptr<TracingCpuProfilerImpl> v8::internal::Isolate::tracing_cpu_profiler_ [private]
Definition at line 2883 of file isolate.h.
Referenced by Deinit(), and Init().
turbo_statistics_
std::shared_ptr<CompilationStatistics> v8::internal::Isolate::turbo_statistics_ [private]
Definition at line 2812 of file isolate.h.
Referenced by DumpAndResetStats(), and GetTurboStatistics().
unicode_cache_
UnicodeCache* v8::internal::Isolate::unicode_cache_ = nullptr [private]
Definition at line 2619 of file isolate.h.
use_counter_callback_
v8::Isolate::UseCounterCallback v8::internal::Isolate::use_counter_callback_ = nullptr [private]
Definition at line 2810 of file isolate.h.
Referenced by CountUsage(), and SetUseCounterCallback().
v8_file_logger_
V8FileLogger* v8::internal::Isolate::v8_file_logger_ = nullptr [private]
Definition at line 2606 of file isolate.h.
Referenced by Deinit(), Init(), InitializeLoggingAndCounters(), NeedsSourcePositions(), and ~Isolate().
was_locker_ever_used_
std::atomic<bool> v8::internal::Isolate::was_locker_ever_used_ {false} [private]
Definition at line 2592 of file isolate.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/isolate.h
/mnt/V8SourceCode/src/execution/isolate-inl.h
/mnt/V8SourceCode/src/execution/isolate.cc