v8::internal::MarkingVisitorBase< ConcreteVisitor > Class Template Reference
#include <marking-visitor.h>
Public Types
using Base = ConcurrentHeapVisitor< ConcreteVisitor >
Public Member Functions
MarkingVisitorBase (MarkingWorklists::Local *local_marking_worklists, WeakObjects::Local *local_weak_objects, Heap *heap, unsigned mark_compact_epoch, base::EnumSet< CodeFlushMode > code_flush_mode, bool should_keep_ages_unchanged, uint16_t code_flushing_increase)
size_t VisitDescriptorArrayStrongly (Tagged< Map > map, Tagged< DescriptorArray > object, MaybeObjectSize)
size_t VisitDescriptorArray (Tagged< Map > map, Tagged< DescriptorArray > object, MaybeObjectSize)
size_t VisitEphemeronHashTable (Tagged< Map > map, Tagged< EphemeronHashTable > object, MaybeObjectSize)
size_t VisitFixedArray (Tagged< Map > map, Tagged< FixedArray > object, MaybeObjectSize)
size_t VisitJSArrayBuffer (Tagged< Map > map, Tagged< JSArrayBuffer > object, MaybeObjectSize)
size_t VisitJSFunction (Tagged< Map > map, Tagged< JSFunction > object, MaybeObjectSize)
size_t VisitJSWeakRef (Tagged< Map > map, Tagged< JSWeakRef > object, MaybeObjectSize)
size_t VisitMap (Tagged< Map > map, Tagged< Map > object, MaybeObjectSize)
size_t VisitSharedFunctionInfo (Tagged< Map > map, Tagged< SharedFunctionInfo > object, MaybeObjectSize)
size_t VisitTransitionArray (Tagged< Map > map, Tagged< TransitionArray > object, MaybeObjectSize)
size_t VisitWeakCell (Tagged< Map > map, Tagged< WeakCell > object, MaybeObjectSize)
void VisitMapPointer (Tagged< HeapObject > host) final
void VisitPointer (Tagged< HeapObject > host, ObjectSlot p) final
void VisitPointer (Tagged< HeapObject > host, MaybeObjectSlot p) final
void VisitPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) final
void VisitPointers (Tagged< HeapObject > host, MaybeObjectSlot start, MaybeObjectSlot end) final
void VisitInstructionStreamPointer (Tagged< Code > host, InstructionStreamSlot slot) final
void VisitEmbeddedPointer (Tagged< InstructionStream > host, RelocInfo *rinfo) final
void VisitCodeTarget (Tagged< InstructionStream > host, RelocInfo *rinfo) final
void VisitCustomWeakPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) final
void VisitExternalPointer (Tagged< HeapObject > host, ExternalPointerSlot slot) override
void VisitCppHeapPointer (Tagged< HeapObject > host, CppHeapPointerSlot slot) override
void VisitIndirectPointer (Tagged< HeapObject > host, IndirectPointerSlot slot, IndirectPointerMode mode) final
void VisitTrustedPointerTableEntry (Tagged< HeapObject > host, IndirectPointerSlot slot) final
void VisitJSDispatchTableEntry (Tagged< HeapObject > host, JSDispatchHandle handle) override
void VisitProtectedPointer (Tagged< TrustedObject > host, ProtectedPointerSlot slot) final
void VisitProtectedPointer (Tagged< TrustedObject > host, ProtectedMaybeObjectSlot slot) final
void SynchronizePageAccess (Tagged< HeapObject > heap_object) const
bool MarkObject (Tagged< HeapObject > host, Tagged< HeapObject > obj, MarkingHelper::WorklistTarget target_worklist)
void SetKeyToValues (KeyToValues *key_to_values)
Static Public Member Functions
static constexpr bool ShouldVisitReadOnlyMapPointer ()
static constexpr bool CanEncounterFillerOrFreeSpace ()
static constexpr bool IsTrivialWeakReferenceValue (Tagged< HeapObject > host, Tagged< HeapObject > heap_object)
Protected Member Functions
template<typename THeapObjectSlot >
void ProcessStrongHeapObject (Tagged< HeapObject > host, THeapObjectSlot slot, Tagged< HeapObject > heap_object)
template<typename THeapObjectSlot >
void ProcessWeakHeapObject (Tagged< HeapObject > host, THeapObjectSlot slot, Tagged< HeapObject > heap_object)
template<typename TSlot >
void VisitPointersImpl (Tagged< HeapObject > host, TSlot start, TSlot end)
template<typename TSlot >
void VisitStrongPointerImpl (Tagged< HeapObject > host, TSlot slot)
void VisitDescriptorsForMap (Tagged< Map > map)
size_t VisitFixedArrayWithProgressTracker (Tagged< Map > map, Tagged< FixedArray > object, MarkingProgressTracker &progress_tracker)
bool ShouldFlushCode (Tagged< SharedFunctionInfo > sfi) const
bool ShouldFlushBaselineCode (Tagged< JSFunction > js_function) const
bool HasBytecodeArrayForFlushing (Tagged< SharedFunctionInfo > sfi) const
bool IsOld (Tagged< SharedFunctionInfo > sfi) const
void MakeOlder (Tagged< SharedFunctionInfo > sfi) const
Protected Attributes
MarkingWorklists::Local *const local_marking_worklists_
WeakObjects::Local *const local_weak_objects_
KeyToValues * key_to_values_ = nullptr
Heap *const heap_
const unsigned mark_compact_epoch_
const base::EnumSet< CodeFlushMode > code_flush_mode_
const bool should_keep_ages_unchanged_
const uint16_t code_flushing_increase_
const bool isolate_in_background_
Additional Inherited Members
Detailed Description
template<typename ConcreteVisitor>
class v8::internal::MarkingVisitorBase< ConcreteVisitor >
Definition at line 46 of file marking-visitor.h.
Member Typedef Documentation
Base
template<typename ConcreteVisitor >
using v8::internal::MarkingVisitorBase< ConcreteVisitor >::Base = ConcurrentHeapVisitor<ConcreteVisitor>
Definition at line 48 of file marking-visitor.h.
Constructor & Destructor Documentation
MarkingVisitorBase()
template<typename ConcreteVisitor >
v8::internal::MarkingVisitorBase< ConcreteVisitor >::MarkingVisitorBase (MarkingWorklists::Local * local_marking_worklists, WeakObjects::Local * local_weak_objects, Heap * heap, unsigned mark_compact_epoch, base::EnumSet< CodeFlushMode > code_flush_mode, bool should_keep_ages_unchanged, uint16_t code_flushing_increase) [inline]
Definition at line 50 of file marking-visitor.h.
      : ConcurrentHeapVisitor<ConcreteVisitor>(heap->isolate()),
        local_marking_worklists_(local_marking_worklists),
        local_weak_objects_(local_weak_objects),
        heap_(heap),
        mark_compact_epoch_(mark_compact_epoch),
        code_flush_mode_(code_flush_mode),
        should_keep_ages_unchanged_(should_keep_ages_unchanged),
        code_flushing_increase_(code_flushing_increase),
        isolate_in_background_(heap->isolate()->is_backgrounded())
#ifdef V8_COMPRESS_POINTERS
        ,
        external_pointer_table_(&heap->isolate()->external_pointer_table()),
        shared_external_pointer_table_(
            &heap->isolate()->shared_external_pointer_table()),
        shared_external_pointer_space_(
            heap->isolate()->shared_external_pointer_space()),
        cpp_heap_pointer_table_(&heap->isolate()->cpp_heap_pointer_table())
#endif // V8_COMPRESS_POINTERS
#ifdef V8_ENABLE_SANDBOX
        ,
        trusted_pointer_table_(&heap->isolate()->trusted_pointer_table()),
        shared_trusted_pointer_table_(
            &heap->isolate()->shared_trusted_pointer_table())
#endif // V8_ENABLE_SANDBOX
  {
  }
Member Function Documentation
CanEncounterFillerOrFreeSpace()
template<typename ConcreteVisitor >
static constexpr bool v8::internal::MarkingVisitorBase< ConcreteVisitor >::CanEncounterFillerOrFreeSpace () [inline], [static], [constexpr]
Definition at line 188 of file marking-visitor.h.
                                                                  {
    return false;
  }
HasBytecodeArrayForFlushing()
template<typename ConcreteVisitor >
bool v8::internal::MarkingVisitorBase< ConcreteVisitor >::HasBytecodeArrayForFlushing (Tagged< SharedFunctionInfo > sfi) const [protected]
Definition at line 435 of file marking-visitor-inl.h.
                                          {
  if (IsFlushingDisabled(code_flush_mode_)) return false;
  // TODO(rmcilroy): Enable bytecode flushing for resumable functions.
  if (IsResumableFunction(sfi->kind()) || !sfi->allows_lazy_compilation()) {
    return false;
  }
  // Get a snapshot of the function data field, and if it is a bytecode array,
  // check if it is old. Note, this is done this way since this function can be
  // called by the concurrent marker.
  Tagged<Object> data = sfi->GetTrustedData(heap_->isolate());
  if (IsCode(data)) {
    Tagged<Code> baseline_code = Cast<Code>(data);
    DCHECK_EQ(baseline_code->kind(), CodeKind::BASELINE);
    // If baseline code flushing isn't enabled and we have baseline data on SFI
    // we cannot flush baseline / bytecode.
    if (!IsBaselineCodeFlushingEnabled(code_flush_mode_)) return false;
    data = baseline_code->bytecode_or_interpreter_data();
  } else if (!IsByteCodeFlushingEnabled(code_flush_mode_)) {
    // If bytecode flushing isn't enabled and there is no baseline code there is
    // nothing to flush.
    return false;
  }
  return IsBytecodeArray(data);
}
References DCHECK_EQ, v8::internal::IsBaselineCodeFlushingEnabled(), v8::internal::IsByteCodeFlushingEnabled(), v8::internal::IsFlushingDisabled(), and v8::internal::IsResumableFunction().
IsOld()
template<typename ConcreteVisitor >
bool v8::internal::MarkingVisitorBase< ConcreteVisitor >::IsOld (Tagged< SharedFunctionInfo > sfi) const [protected]
Definition at line 473 of file marking-visitor-inl.h.
                                          {
  if (v8_flags.flush_code_based_on_time) {
    return sfi->age() >= v8_flags.bytecode_old_time;
  } else if (v8_flags.flush_code_based_on_tab_visibility) {
    return isolate_in_background_ ||
           V8_UNLIKELY(sfi->age() == SharedFunctionInfo::kMaxAge);
  } else {
    return sfi->age() >= v8_flags.bytecode_old_age;
  }
}
References v8::internal::SharedFunctionInfo::kMaxAge, v8::internal::v8_flags, and V8_UNLIKELY.
IsTrivialWeakReferenceValue()
template<typename ConcreteVisitor >
constexpr bool v8::internal::MarkingVisitorBase< ConcreteVisitor >::IsTrivialWeakReferenceValue (Tagged< HeapObject > host, Tagged< HeapObject > heap_object) [inline], [static], [constexpr]
Definition at line 90 of file marking-visitor-inl.h.
                                                             {
  return !IsMap(heap_object) ||
         !(IsMap(host) || IsTransitionArray(host) || IsDescriptorArray(host));
}
MakeOlder()
template<typename ConcreteVisitor >
void v8::internal::MarkingVisitorBase< ConcreteVisitor >::MakeOlder (Tagged< SharedFunctionInfo > sfi) const [protected]
Definition at line 486 of file marking-visitor-inl.h.
                                          {
  if (v8_flags.flush_code_based_on_time) {
    if (code_flushing_increase_ == 0) {
      return;
    }
    uint16_t current_age;
    uint16_t updated_age;
    do {
      current_age = sfi->age();
      // When the age is 0, it was reset by the function prologue in
      // Ignition/Sparkplug. But that might have been some time after the last
      // full GC. So in this case we don't increment the value like we normally
      // would but just set the age to 1. All non-0 values can be incremented as
      // expected (we add the number of seconds since the last GC) as they were
      // definitely last executed before the last full GC.
      updated_age = current_age == 0
                        ? 1
                        : SaturateAdd(current_age, code_flushing_increase_);
    } while (sfi->CompareExchangeAge(current_age, updated_age) != current_age);
  } else if (v8_flags.flush_code_based_on_tab_visibility) {
    // No need to increment age.
  } else {
    uint16_t age = sfi->age();
    if (age < v8_flags.bytecode_old_age) {
      sfi->CompareExchangeAge(age, age + 1);
    }
    DCHECK_LE(sfi->age(), v8_flags.bytecode_old_age);
  }
}
References DCHECK_LE, v8::internal::SaturateAdd(), and v8::internal::v8_flags.
MarkObject()
template<typename ConcreteVisitor >
bool v8::internal::MarkingVisitorBase< ConcreteVisitor >::MarkObject (Tagged< HeapObject > host, Tagged< HeapObject > obj, MarkingHelper::WorklistTarget target_worklist) [inline]
Definition at line 46 of file marking-visitor-inl.h.
                                                 {
  DCHECK(heap_->Contains(object));
  SynchronizePageAccess(object);
  concrete_visitor()->AddStrongReferenceForReferenceSummarizer(retainer,
                                                               object);
  return MarkingHelper::TryMarkAndPush(heap_, local_marking_worklists_,
                                       concrete_visitor()->marking_state(),
                                       target_worklist, object);
}
References v8::internal::DCHECK(), and v8::internal::MarkingHelper::TryMarkAndPush().
Referenced by v8::internal::ConcurrentMarkingVisitor::ProcessEphemeron().
ProcessStrongHeapObject()
template<typename ConcreteVisitor >
template<typename THeapObjectSlot >
void v8::internal::MarkingVisitorBase< ConcreteVisitor >::ProcessStrongHeapObject (Tagged< HeapObject > host, THeapObjectSlot slot, Tagged< HeapObject > heap_object) [protected]
Definition at line 62 of file marking-visitor-inl.h.
                                    {
  SynchronizePageAccess(heap_object);
  const auto target_worklist =
      MarkingHelper::ShouldMarkObject(heap_, heap_object);
  if (!target_worklist) {
    return;
  }
  // TODO(chromium:1495151): Remove after diagnosing.
  if (V8_UNLIKELY(!MemoryChunk::FromHeapObject(heap_object)->IsMarking() &&
                  IsFreeSpaceOrFiller(
                      heap_object, ObjectVisitorWithCageBases::cage_base()))) {
    heap_->isolate()->PushStackTraceAndDie(
        reinterpret_cast<void*>(host->map().ptr()),
        reinterpret_cast<void*>(host->address()),
        reinterpret_cast<void*>(slot.address()),
        reinterpret_cast<void*>(MemoryChunkMetadata::FromHeapObject(heap_object)
                                    ->owner()
                                    ->identity()));
  }
  MarkObject(host, heap_object, target_worklist.value());
  concrete_visitor()->RecordSlot(host, slot, heap_object);
}
References v8::internal::Tagged< HeapObject >::address(), v8::internal::ObjectVisitorWithCageBases::cage_base(), v8::internal::MemoryChunkMetadata::FromHeapObject(), v8::internal::MemoryChunk::FromHeapObject(), v8::internal::BaseSpace::identity(), v8::internal::InstanceTypeChecker::IsFreeSpaceOrFiller(), v8::internal::MemoryChunkMetadata::owner(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::internal::MarkingHelper::ShouldMarkObject(), and V8_UNLIKELY.
Referenced by v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitMapPointer().
ProcessWeakHeapObject()
template<typename ConcreteVisitor >
template<typename THeapObjectSlot >
void v8::internal::MarkingVisitorBase< ConcreteVisitor >::ProcessWeakHeapObject (Tagged< HeapObject > host, THeapObjectSlot slot, Tagged< HeapObject > heap_object) [protected]
Definition at line 100 of file marking-visitor-inl.h.
                                    {
  SynchronizePageAccess(heap_object);
  concrete_visitor()->AddWeakReferenceForReferenceSummarizer(host, heap_object);
  const auto target_worklist =
      MarkingHelper::ShouldMarkObject(heap_, heap_object);
  if (!target_worklist) {
    return;
  }
  if (concrete_visitor()->marking_state()->IsMarked(heap_object)) {
    // Weak references with live values are directly processed here to
    // reduce the processing time of weak cells during the main GC
    // pause.
    concrete_visitor()->RecordSlot(host, slot, heap_object);
  } else {
    // If we do not know about liveness of the value, we have to process
    // the reference when we know the liveness of the whole transitive
    // closure.
    // Distinguish trivial cases (non involving custom weakness) from
    // non-trivial ones. The latter are maps in host objects of type Map,
    // TransitionArray and DescriptorArray.
    if constexpr (SlotHoldsTrustedPointerV<THeapObjectSlot>) {
      local_weak_objects_->weak_references_trusted_local.Push(
          TrustedObjectAndSlot{host, slot});
    } else if (V8_LIKELY(IsTrivialWeakReferenceValue(host, heap_object))) {
      local_weak_objects_->weak_references_trivial_local.Push(
          HeapObjectAndSlot{host, slot});
    } else {
      local_weak_objects_->weak_references_non_trivial_local.Push(
          HeapObjectAndSlot{host, slot});
    }
  }
}
SetKeyToValues()
template<typename ConcreteVisitor >
void v8::internal::MarkingVisitorBase< ConcreteVisitor >::SetKeyToValues (KeyToValues * key_to_values) [inline]
Definition at line 195 of file marking-visitor.h.
                                                  {
    DCHECK_NULL(key_to_values_);
    key_to_values_ = key_to_values;
  }
References DCHECK_NULL, and v8::internal::MarkingVisitorBase< ConcreteVisitor >::key_to_values_.
ShouldFlushBaselineCode()
template<typename ConcreteVisitor >
bool v8::internal::MarkingVisitorBase< ConcreteVisitor >::ShouldFlushBaselineCode (Tagged< JSFunction > js_function) const [protected]
Definition at line 519 of file marking-visitor-inl.h.
                                          {
  if (!IsBaselineCodeFlushingEnabled(code_flush_mode_)) return false;
  // Do a raw read for shared and code fields here since this function may be
  // called on a concurrent thread. JSFunction itself should be fully
  // initialized here but the SharedFunctionInfo, InstructionStream objects may
  // not be initialized. We read using acquire loads to defend against that.
  Tagged<Object> maybe_shared =
      ACQUIRE_READ_FIELD(js_function, JSFunction::kSharedFunctionInfoOffset);
  if (!IsSharedFunctionInfo(maybe_shared)) return false;
  // See crbug.com/v8/11972 for more details on acquire / release semantics for
  // code field. We don't use release stores when copying code pointers from
  // SFI / FV to JSFunction but it is safe in practice.
  Tagged<Object> maybe_code =
      js_function->raw_code(heap_->isolate(), kAcquireLoad);
#ifdef THREAD_SANITIZER
  // This is needed because TSAN does not process the memory fence
  // emitted after page initialization.
  MemoryChunk::FromAddress(maybe_code.ptr())->SynchronizedLoad();
#endif
  if (!IsCode(maybe_code)) return false;
  Tagged<Code> code = Cast<Code>(maybe_code);
  if (code->kind() != CodeKind::BASELINE) return false;
  Tagged<SharedFunctionInfo> shared = Cast<SharedFunctionInfo>(maybe_shared);
  return HasBytecodeArrayForFlushing(shared) && ShouldFlushCode(shared);
}
References ACQUIRE_READ_FIELD, code, v8::internal::MemoryChunk::FromAddress(), v8::internal::IsBaselineCodeFlushingEnabled(), v8::kAcquireLoad, and v8::internal::TaggedImpl< kRefType, StorageType >::ptr().
ShouldFlushCode()
template<typename ConcreteVisitor >
bool v8::internal::MarkingVisitorBase< ConcreteVisitor >::ShouldFlushCode (Tagged< SharedFunctionInfo > sfi) const [protected]
Definition at line 465 of file marking-visitor-inl.h.
                                          {
  // This method is used both for flushing bytecode and baseline code.
  // During last resort GCs and stress testing we consider all code old.
  return IsOld(sfi) || V8_UNLIKELY(IsForceFlushingEnabled(code_flush_mode_));
}
References v8::internal::IsForceFlushingEnabled(), and V8_UNLIKELY.
ShouldVisitReadOnlyMapPointer()
template<typename ConcreteVisitor >
static constexpr bool v8::internal::MarkingVisitorBase< ConcreteVisitor >::ShouldVisitReadOnlyMapPointer () [inline], [static], [constexpr]
Definition at line 184 of file marking-visitor.h.
                                                                  {
    return false;
  }
SynchronizePageAccess()
template<typename ConcreteVisitor >
void v8::internal::MarkingVisitorBase< ConcreteVisitor >::SynchronizePageAccess (Tagged< HeapObject > heap_object) const [inline]
Definition at line 170 of file marking-visitor.h.
                                                                   {
#ifdef THREAD_SANITIZER
    // This is needed because TSAN does not process the memory fence
    // emitted after page initialization.
    MemoryChunk::FromHeapObject(heap_object)->SynchronizedLoad();
#endif
  }
References v8::internal::MemoryChunk::FromHeapObject().
VisitCodeTarget()
template<typename ConcreteVisitor >
void v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitCodeTarget (Tagged< InstructionStream > host, RelocInfo * rinfo) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 207 of file marking-visitor-inl.h.
                                                      {
  DCHECK(RelocInfo::IsCodeTargetMode(rinfo->rmode()));
  Tagged<InstructionStream> target =
      InstructionStream::FromTargetAddress(rinfo->target_address());
  const auto target_worklist = MarkingHelper::ShouldMarkObject(heap_, target);
  if (!target_worklist) {
    return;
  }
  MarkObject(host, target, target_worklist.value());
  concrete_visitor()->RecordRelocSlot(host, rinfo, target);
}
VisitCppHeapPointer()
template<typename ConcreteVisitor >
void v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitCppHeapPointer (Tagged< HeapObject > host, CppHeapPointerSlot slot) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 258 of file marking-visitor-inl.h.
                                                      {
#ifdef V8_COMPRESS_POINTERS
  const ExternalPointerHandle handle = slot.Relaxed_LoadHandle();
  if (handle == kNullExternalPointerHandle) {
    return;
  }
  CppHeapPointerTable* table = cpp_heap_pointer_table_;
  CppHeapPointerTable::Space* space = heap_->cpp_heap_pointer_space();
  table->Mark(space, handle, slot.address());
#endif // V8_COMPRESS_POINTERS
  if (auto cpp_heap_pointer =
          slot.try_load(heap_->isolate(), kAnyCppHeapPointer)) {
    local_marking_worklists_->cpp_marking_state()->MarkAndPush(
        reinterpret_cast<void*>(cpp_heap_pointer));
  }
}
References v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::address(), v8::internal::handle(), v8::kAnyCppHeapPointer(), v8::internal::kNullExternalPointerHandle, space, and v8::internal::CppHeapPointerSlot::try_load().
VisitCustomWeakPointers()
template<typename ConcreteVisitor >
void v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitCustomWeakPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 140 of file marking-visitor.h.
                                                     {
    // Weak list pointers should be ignored during marking. The lists are
    // reconstructed after GC.
  }
VisitDescriptorArray()
template<typename ConcreteVisitor >
size_t v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitDescriptorArray (Tagged< Map > map, Tagged< DescriptorArray > object, MaybeObjectSize maybe_object_size) [inline]
Definition at line 772 of file marking-visitor-inl.h.
                                       {
  if (!concrete_visitor()->CanUpdateValuesInHeap()) {
    // If we cannot update the values in the heap, we just treat the array
    // strongly.
    return VisitDescriptorArrayStrongly(map, array, maybe_object_size);
  }
  // The markbit is not used anymore. This is different from a checked
  // transition in that the array is re-added to the worklist and thus there's
  // many invocations of this transition. All cases (roots, marking via map,
  // write barrier) are handled here as they all update the state accordingly.
  const auto [start, end] =
      DescriptorArrayMarkingState::AcquireDescriptorRangeToMark(
          mark_compact_epoch_, array);
  if (start != end) {
    DCHECK_LT(start, end);
    VisitPointers(array, MaybeObjectSlot(array->GetDescriptorSlot(start)),
                  MaybeObjectSlot(array->GetDescriptorSlot(end)));
    if (start == 0) {
      // We are processing the object the first time. Visit the header and
      // return a size for accounting.
      size_t size = DescriptorArray::BodyDescriptor::SizeOf(map, array);
      VisitPointers(array, array->GetFirstPointerSlot(),
                    array->GetDescriptorSlot(0));
      concrete_visitor()
          ->template VisitMapPointerIfNeeded<VisitorId::kVisitDescriptorArray>(
              array);
      return size;
    }
  }
  return 0;
}
References v8::internal::DescriptorArrayMarkingState::AcquireDescriptorRangeToMark(), DCHECK_LT, v8::internal::compiler::end(), size(), and v8::internal::torque::SizeOf().
VisitDescriptorArrayStrongly()
template<typename ConcreteVisitor >
size_t v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitDescriptorArrayStrongly (Tagged< Map > map, Tagged< DescriptorArray > object, MaybeObjectSize) [inline]
Definition at line 758 of file marking-visitor-inl.h.
                                                                     {
  this->template VisitMapPointerIfNeeded<VisitorId::kVisitDescriptorArray>(
      array);
  const int size = DescriptorArray::BodyDescriptor::SizeOf(map, array);
  VisitPointers(array, array->GetFirstPointerSlot(),
                array->GetDescriptorSlot(0));
  VisitPointers(array, MaybeObjectSlot(array->GetDescriptorSlot(0)),
                MaybeObjectSlot(
                    array->GetDescriptorSlot(array->number_of_descriptors())));
  return size;
}
References size(), and v8::internal::torque::SizeOf().
VisitDescriptorsForMap()
template<typename ConcreteVisitor >
void v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitDescriptorsForMap (Tagged< Map > map) [inline], [protected]
Definition at line 808 of file marking-visitor-inl.h.
                     {
  if (!concrete_visitor()->CanUpdateValuesInHeap() || !map->CanTransition())
    return;
  // Maps that can transition share their descriptor arrays and require
  // special visiting logic to avoid memory leaks.
  // Since descriptor arrays are potentially shared, ensure that only the
  // descriptors that belong to this map are marked. The first time a
  // non-empty descriptor array is marked, its header is also visited. The
  // slot holding the descriptor array will be implicitly recorded when the
  // pointer fields of this map are visited.
  Tagged<Object> maybe_descriptors =
      TaggedField<Object, Map::kInstanceDescriptorsOffset>::Acquire_Load(
          heap_->isolate(), map);
  // If the descriptors are a Smi, then this Map is in the process of being
  // deserialized, and doesn't yet have an initialized descriptor field.
  if (IsSmi(maybe_descriptors)) {
    DCHECK_EQ(maybe_descriptors, Smi::uninitialized_deserialization_value());
    return;
  }
  Tagged<DescriptorArray> descriptors =
      Cast<DescriptorArray>(maybe_descriptors);
  // Synchronize reading of page flags for tsan.
  SynchronizePageAccess(descriptors);
  // Normal processing of descriptor arrays through the pointers iteration that
  // follows this call:
  // - Array in read only space;
  // - Array in a black allocated page;
  // - StrongDescriptor array;
  if (HeapLayout::InReadOnlySpace(descriptors) ||
      IsStrongDescriptorArray(descriptors)) {
    return;
  }
  if (v8_flags.black_allocated_pages &&
      HeapLayout::InBlackAllocatedPage(descriptors)) {
    return;
  }
  const int number_of_own_descriptors = map->NumberOfOwnDescriptors();
  if (number_of_own_descriptors) {
    // It is possible that the concurrent marker observes the
    // number_of_own_descriptors out of sync with the descriptors. In that
    // case the marking write barrier for the descriptor array will ensure
    // that all required descriptors are marked. The concurrent marker
    // just should avoid crashing in that case. That's why we need the
    // std::min<int>() below.
    const auto descriptors_to_mark = std::min<int>(
        number_of_own_descriptors, descriptors->number_of_descriptors());
    concrete_visitor()->marking_state()->TryMark(descriptors);
    if (DescriptorArrayMarkingState::TryUpdateIndicesToMark(
            mark_compact_epoch_, descriptors, descriptors_to_mark)) {
#ifdef DEBUG
      const auto target_worklist =
          MarkingHelper::ShouldMarkObject(heap_, descriptors);
      DCHECK(target_worklist);
      DCHECK_EQ(target_worklist.value(),
                MarkingHelper::WorklistTarget::kRegular);
#endif // DEBUG
      local_marking_worklists_->Push(descriptors);
    }
  }
}
References v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Acquire_Load(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::HeapLayout::InBlackAllocatedPage(), v8::internal::HeapLayout::InReadOnlySpace(), v8::internal::IsSmi(), v8::internal::MarkingHelper::kRegular, v8::internal::MarkingHelper::ShouldMarkObject(), v8::internal::DescriptorArrayMarkingState::TryUpdateIndicesToMark(), v8::internal::Smi::uninitialized_deserialization_value(), and v8::internal::v8_flags.
VisitEmbeddedPointer()
template<typename ConcreteVisitor >
void v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitEmbeddedPointer (Tagged< InstructionStream > host, RelocInfo * rinfo) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 183 of file marking-visitor-inl.h.
                                                      {
  DCHECK(RelocInfo::IsEmbeddedObjectMode(rinfo->rmode()));
  Tagged<HeapObject> object =
      rinfo->target_object(ObjectVisitorWithCageBases::cage_base());
  const auto target_worklist = MarkingHelper::ShouldMarkObject(heap_, object);
  if (!target_worklist) {
    return;
  }
  if (!concrete_visitor()->marking_state()->IsMarked(object)) {
    Tagged<Code> code = UncheckedCast<Code>(host->raw_code(kAcquireLoad));
    if (code->IsWeakObject(object)) {
      local_weak_objects_->weak_objects_in_code_local.Push(
          HeapObjectAndCode{object, code});
      concrete_visitor()->AddWeakReferenceForReferenceSummarizer(host, object);
    } else {
      MarkObject(host, object, target_worklist.value());
    }
  }
  concrete_visitor()->RecordRelocSlot(host, rinfo, object);
}
References v8::internal::ObjectVisitorWithCageBases::cage_base(), v8::internal::DCHECK(), v8::internal::RelocInfo::IsEmbeddedObjectMode(), v8::internal::RelocInfo::rmode(), v8::internal::MarkingHelper::ShouldMarkObject(), and v8::internal::RelocInfo::target_object().
VisitEphemeronHashTable()
template<typename ConcreteVisitor >
size_t v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitEphemeronHashTable (Tagged< Map > map, Tagged< EphemeronHashTable > object, MaybeObjectSize) [inline]
Definition at line 641 of file marking-visitor-inl.h.
                                                                        {
  local_weak_objects_->ephemeron_hash_tables_local.Push(table);
  const bool use_key_to_values = key_to_values_ != nullptr;
  for (InternalIndex i : table->IterateEntries()) {
    ObjectSlot key_slot =
        table->RawFieldOfElementAt(EphemeronHashTable::EntryToIndex(i));
    Tagged<HeapObject> key = Cast<HeapObject>(table->KeyAt(i, kRelaxedLoad));
    SynchronizePageAccess(key);
    concrete_visitor()->RecordSlot(table, key_slot, key);
    concrete_visitor()->AddWeakReferenceForReferenceSummarizer(table, key);
    ObjectSlot value_slot =
        table->RawFieldOfElementAt(EphemeronHashTable::EntryToValueIndex(i));
    // Objects in the shared heap are prohibited from being used as keys in
    // WeakMaps and WeakSets and therefore cannot be ephemeron keys. See also
    // MarkCompactCollector::ProcessEphemeron.
    DCHECK(!HeapLayout::InWritableSharedSpace(key));
    if (MarkingHelper::IsMarkedOrAlwaysLive(
            heap_, concrete_visitor()->marking_state(), key)) {
      VisitPointer(table, value_slot);
    } else {
      Tagged<Object> value_obj = table->ValueAt(i);
      if (IsHeapObject(value_obj)) {
        Tagged<HeapObject> value = Cast<HeapObject>(value_obj);
        SynchronizePageAccess(value);
        concrete_visitor()->RecordSlot(table, value_slot, value);
        concrete_visitor()->AddWeakReferenceForReferenceSummarizer(table,
                                                                   value);
        const auto target_worklist =
            MarkingHelper::ShouldMarkObject(heap_, value);
        if (!target_worklist) {
          continue;
        }
        // Revisit ephemerons with both key and value unreachable at end
        // of concurrent marking cycle.
        if (concrete_visitor()->marking_state()->IsUnmarked(value)) {
          if (V8_LIKELY(!use_key_to_values)) {
            local_weak_objects_->next_ephemerons_local.Push(
                Ephemeron{key, value});
          } else {
            auto it = key_to_values_->try_emplace(key).first;
            it->second.push_back(value);
          }
        }
      }
    }
  }
  return table->SizeFromMap(map);
}
References v8::internal::DCHECK(), v8::internal::HeapLayout::InWritableSharedSpace(), v8::internal::IsHeapObject(), v8::internal::MarkingHelper::IsMarkedOrAlwaysLive(), v8::internal::key, v8::kRelaxedLoad, v8::internal::MarkingHelper::ShouldMarkObject(), V8_LIKELY, and v8::internal::value.
VisitExternalPointer()
template<typename ConcreteVisitor >
void v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitExternalPointer (Tagged< HeapObject > host, ExternalPointerSlot slot) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 222 of file marking-visitor-inl.h.
                                                       {
#ifdef V8_COMPRESS_POINTERS
  DCHECK(!slot.tag_range().IsEmpty());
  if (slot.HasExternalPointerHandle()) {
    ExternalPointerHandle handle = slot.Relaxed_LoadHandle();
    ExternalPointerTable* table;
    ExternalPointerTable::Space* space;
    if (IsSharedExternalPointerType(slot.tag_range())) {
      table = shared_external_pointer_table_;
      space = shared_external_pointer_space_;
    } else {
      table = external_pointer_table_;
      if (v8_flags.sticky_mark_bits) {
        // Everything is considered old during major GC.
        DCHECK(!HeapLayout::InYoungGeneration(host));
        if (handle == kNullExternalPointerHandle) return;
        // The object may either be in young or old EPT.
        if (table->Contains(heap_->young_external_pointer_space(), handle)) {
          space = heap_->young_external_pointer_space();
        } else {
          DCHECK(table->Contains(heap_->old_external_pointer_space(), handle));
          space = heap_->old_external_pointer_space();
        }
      } else {
        space = HeapLayout::InYoungGeneration(host)
                    ? heap_->young_external_pointer_space()
                    : heap_->old_external_pointer_space();
      }
    }
    table->Mark(space, handle, slot.address());
  }
#endif // V8_COMPRESS_POINTERS
}
VisitFixedArray()
template<typename ConcreteVisitor >
size_t v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitFixedArray (Tagged< Map > map, Tagged< FixedArray > object, MaybeObjectSize maybe_object_size) [inline]
Definition at line 613 of file marking-visitor-inl.h.
                                       {
  MarkingProgressTracker& progress_tracker =
      MutablePageMetadata::FromHeapObject(object)->marking_progress_tracker();
  return concrete_visitor()->CanUpdateValuesInHeap() &&
                 progress_tracker.IsEnabled()
             ? VisitFixedArrayWithProgressTracker(map, object, progress_tracker)
             : Base::VisitFixedArray(map, object, maybe_object_size);
}
References v8::internal::MutablePageMetadata::FromHeapObject(), v8::internal::MarkingProgressTracker::IsEnabled(), and v8::internal::MutablePageMetadata::marking_progress_tracker().
VisitFixedArrayWithProgressTracker()
template<typename ConcreteVisitor >
size_t v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitFixedArrayWithProgressTracker (Tagged< Map > map, Tagged< FixedArray > object, MarkingProgressTracker & progress_tracker) [inline], [protected]
Definition at line 554 of file marking-visitor-inl.h.
                                              {
  static_assert(kMaxRegularHeapObjectSize % kTaggedSize == 0);
  static constexpr size_t kMaxQueuedWorklistItems = 8u;
  DCHECK(concrete_visitor()->marking_state()->IsMarked(object));
  const size_t size = FixedArray::BodyDescriptor::SizeOf(map, object);
  const size_t chunk = progress_tracker.GetNextChunkToMark();
  const size_t total_chunks = progress_tracker.TotalNumberOfChunks();
  size_t start = 0;
  size_t end = 0;
  if (chunk == 0) {
    // We just started marking the fixed array. Push the total number of chunks
    // to the marking worklist and publish it so that other markers can
    // participate.
    if (const auto target_worklist =
            MarkingHelper::ShouldMarkObject(heap_, object)) {
      DCHECK_EQ(target_worklist.value(),
                MarkingHelper::WorklistTarget::kRegular);
      const size_t scheduled_chunks =
          std::min(total_chunks, kMaxQueuedWorklistItems);
      DCHECK_GT(scheduled_chunks, 0);
      for (size_t i = 1; i < scheduled_chunks; ++i) {
        local_marking_worklists_->Push(object);
        // Publish each chunk into a new segment so that other markers would be
        // able to steal work. This is probabilistic (a single marker can be
        // fast and steal multiple segments), but it works well in practice.
        local_marking_worklists_->ShareWork();
      }
    }
    concrete_visitor()
        ->template VisitMapPointerIfNeeded<VisitorId::kVisitFixedArray>(object);
    start = FixedArray::BodyDescriptor::kStartOffset;
    end = std::min(size, MarkingProgressTracker::kChunkSize);
  } else {
    start = chunk * MarkingProgressTracker::kChunkSize;
    end = std::min(size, start + MarkingProgressTracker::kChunkSize);
  }
  // Repost the task if needed.
  if (chunk + kMaxQueuedWorklistItems < total_chunks) {
    if (const auto target_worklist =
            MarkingHelper::ShouldMarkObject(heap_, object)) {
      local_marking_worklists_->Push(object);
      local_marking_worklists_->ShareWork();
    }
  }
  if (start < end) {
    VisitPointers(object,
                  Cast<HeapObject>(object)->RawField(static_cast<int>(start)),
                  Cast<HeapObject>(object)->RawField(static_cast<int>(end)));
  }
  return end - start;
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GT, v8::internal::compiler::end(), v8::internal::MarkingProgressTracker::GetNextChunkToMark(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::MarkingProgressTracker::kChunkSize, v8::internal::kMaxRegularHeapObjectSize, v8::internal::MarkingHelper::kRegular, v8::internal::SuffixRangeBodyDescriptor< HeapObject::kHeaderSize >::kStartOffset, v8::internal::kTaggedSize, v8::internal::MarkingHelper::ShouldMarkObject(), size(), v8::internal::FixedArray::BodyDescriptor::SizeOf(), and v8::internal::MarkingProgressTracker::TotalNumberOfChunks().
VisitIndirectPointer()
template<typename ConcreteVisitor >
void v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitIndirectPointer (Tagged< HeapObject > host, IndirectPointerSlot slot, IndirectPointerMode mode) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 277 of file marking-visitor-inl.h.
                              {
#ifdef V8_ENABLE_SANDBOX
  if (mode == IndirectPointerMode::kStrong) {
    // Load the referenced object (if the slot is initialized) and mark it as
    // alive if necessary. Indirect pointers never have to be added to a
    // remembered set because the referenced object will update the pointer
    // table entry when it is relocated.
    // The marker might visit objects whose trusted pointers to each other
    // are not yet or no longer accessible, so we must handle those here.
    Tagged<Object> value = slot.Relaxed_Load_AllowUnpublished(heap_->isolate());
    if (IsHeapObject(value)) {
      Tagged<HeapObject> obj = Cast<HeapObject>(value);
      SynchronizePageAccess(obj);
      const auto target_worklist = MarkingHelper::ShouldMarkObject(heap_, obj);
      if (!target_worklist) {
        return;
      }
      MarkObject(host, obj, target_worklist.value());
    }
  }
#else
  UNREACHABLE();
#endif
}
VisitInstructionStreamPointer()
template<typename ConcreteVisitor >
void v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitInstructionStreamPointer (Tagged< Code > host, InstructionStreamSlot slot) [inline], [final], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 132 of file marking-visitor.h.
                                                           {
    VisitStrongPointerImpl(host, slot);
  }
References v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitStrongPointerImpl().
VisitJSArrayBuffer()
template<typename ConcreteVisitor >
size_t v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitJSArrayBuffer (Tagged< Map > map, Tagged< JSArrayBuffer > object, MaybeObjectSize maybe_object_size) [inline]
Definition at line 629 of file marking-visitor-inl.h.
                                       {
  object->MarkExtension();
  return Base::VisitJSArrayBuffer(map, object, maybe_object_size);
}
VisitJSDispatchTableEntry()
template<typename ConcreteVisitor >
void v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitJSDispatchTableEntry (Tagged< HeapObject > host, JSDispatchHandle handle) [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 311 of file marking-visitor-inl.h.
                                                      {
#ifdef V8_ENABLE_LEAPTIERING
  JSDispatchTable* jdt = IsolateGroup::current()->js_dispatch_table();
#ifdef DEBUG
  JSDispatchTable::Space* space = heap_->js_dispatch_table_space();
  JSDispatchTable::Space* ro_space =
      heap_->isolate()->read_only_heap()->js_dispatch_table_space();
  jdt->VerifyEntry(handle, space, ro_space);
#endif // DEBUG
  jdt->Mark(handle);
  // The code objects referenced from a dispatch table entry are treated as weak
  // references for the purpose of bytecode/baseline flushing, so they are not
  // marked here. See also VisitJSFunction below.
#endif // V8_ENABLE_LEAPTIERING
}
References v8::internal::IsolateGroup::current(), v8::internal::handle(), and space.
VisitJSFunction()
template<typename ConcreteVisitor >
size_t v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitJSFunction (Tagged< Map > map, Tagged< JSFunction > object, MaybeObjectSize maybe_object_size) [inline]
Definition at line 335 of file marking-visitor-inl.h.
                                       {
  if (ShouldFlushBaselineCode(js_function)) {
    DCHECK(IsBaselineCodeFlushingEnabled(code_flush_mode_));
#ifndef V8_ENABLE_LEAPTIERING
    local_weak_objects_->baseline_flushing_candidates_local.Push(js_function);
#endif // !V8_ENABLE_LEAPTIERING
    return Base::VisitJSFunction(map, js_function, maybe_object_size);
  }
  // We're not flushing the Code, so mark it as alive.
#ifdef V8_ENABLE_LEAPTIERING
  // Here we can see JSFunctions that aren't fully initialized (e.g. during
  // deserialization) so we need to check for the null handle.
  JSDispatchHandle handle(
      js_function->Relaxed_ReadField<JSDispatchHandle::underlying_type>(
          JSFunction::kDispatchHandleOffset));
  if (handle != kNullJSDispatchHandle) {
    Tagged<HeapObject> obj =
        IsolateGroup::current()->js_dispatch_table()->GetCode(handle);
    // TODO(saelo): maybe factor out common code with VisitIndirectPointer
    // into a helper routine?
    SynchronizePageAccess(obj);
    const auto target_worklist = MarkingHelper::ShouldMarkObject(heap_, obj);
    if (target_worklist) {
      MarkObject(js_function, obj, target_worklist.value());
    }
  }
#else
#ifdef V8_ENABLE_SANDBOX
  VisitIndirectPointer(js_function,
                       js_function->RawIndirectPointerField(
                           JSFunction::kCodeOffset, kCodeIndirectPointerTag),
                       IndirectPointerMode::kStrong);
#else
  VisitPointer(js_function, js_function->RawField(JSFunction::kCodeOffset));
#endif // V8_ENABLE_SANDBOX
#endif // V8_ENABLE_LEAPTIERING
  // TODO(mythria): Consider updating the check for ShouldFlushBaselineCode to
  // also include cases where there is old bytecode even when there is no
  // baseline code and remove this check here.
  if (IsByteCodeFlushingEnabled(code_flush_mode_) &&
      js_function->NeedsResetDueToFlushedBytecode(heap_->isolate())) {
    local_weak_objects_->flushed_js_functions_local.Push(js_function);
  }
  return Base::VisitJSFunction(map, js_function, maybe_object_size);
}
References v8::internal::IsolateGroup::current(), v8::internal::DCHECK(), v8::internal::handle(), v8::internal::IsBaselineCodeFlushingEnabled(), v8::internal::IsByteCodeFlushingEnabled(), v8::internal::kNullJSDispatchHandle(), v8::internal::kStrong, v8::internal::anonymous_namespace{traced-handles.cc}::MarkObject(), and v8::internal::MarkingHelper::ShouldMarkObject().
VisitJSWeakRef()
template<typename ConcreteVisitor >
size_t v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitJSWeakRef (Tagged< Map > map, Tagged< JSWeakRef > object, MaybeObjectSize maybe_object_size) [inline]
Definition at line 699 of file marking-visitor-inl.h.
                                       {
  if (IsHeapObject(weak_ref->target())) {
    Tagged<HeapObject> target = Cast<HeapObject>(weak_ref->target());
    SynchronizePageAccess(target);
    concrete_visitor()->AddWeakReferenceForReferenceSummarizer(weak_ref,
                                                               target);
    if (MarkingHelper::IsMarkedOrAlwaysLive(
            heap_, concrete_visitor()->marking_state(), target)) {
      // Record the slot inside the JSWeakRef, since the VisitJSWeakRef above
      // didn't visit it.
      ObjectSlot slot = weak_ref->RawField(JSWeakRef::kTargetOffset);
      concrete_visitor()->RecordSlot(weak_ref, slot, target);
    } else {
      // JSWeakRef points to a potentially dead object. We have to process them
      // when we know the liveness of the whole transitive closure.
      local_weak_objects_->js_weak_refs_local.Push(weak_ref);
    }
  }
  return Base::VisitJSWeakRef(map, weak_ref, maybe_object_size);
}
References v8::internal::IsHeapObject(), and v8::internal::MarkingHelper::IsMarkedOrAlwaysLive().
VisitMap()
template<typename ConcreteVisitor >
size_t v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitMap (Tagged< Map > map, Tagged< Map > object, MaybeObjectSize maybe_object_size) [inline]
Definition at line 876 of file marking-visitor-inl.h.
                                                                              {
  VisitDescriptorsForMap(map);
  // Mark the pointer fields of the Map. If there is a transitions array, it has
  // been marked already, so it is fine that one of these fields contains a
  // pointer to it.
  return Base::VisitMap(meta_map, map, maybe_object_size);
}
VisitMapPointer()
template<typename ConcreteVisitor >
void v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitMapPointer (Tagged< HeapObject > host) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 113 of file marking-visitor.h.
                                                      {
    Tagged<Map> map = host->map(ObjectVisitorWithCageBases::cage_base());
    ProcessStrongHeapObject(host, host->map_slot(), map);
  }
References v8::internal::ObjectVisitorWithCageBases::cage_base(), and v8::internal::MarkingVisitorBase< ConcreteVisitor >::ProcessStrongHeapObject().
VisitPointer() [1/2]
template<typename ConcreteVisitor >
void v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitPointer (Tagged< HeapObject > host, MaybeObjectSlot p) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 120 of file marking-visitor.h.
                                                       {
    VisitPointersImpl(host, p, p + 1);
  }
References v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitPointersImpl().
VisitPointer() [2/2]
template<typename ConcreteVisitor >
void v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitPointer (Tagged< HeapObject > host, ObjectSlot p) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 117 of file marking-visitor.h.
                                                                           {
    VisitPointersImpl(host, p, p + 1);
  }
References v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitPointersImpl().
VisitPointers() [1/2]
template<typename ConcreteVisitor >
void v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitPointers (Tagged< HeapObject > host, MaybeObjectSlot start, MaybeObjectSlot end) [inline], [final], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 128 of file marking-visitor.h.
                                                          {
    VisitPointersImpl(host, start, end);
  }
References v8::internal::compiler::end(), and v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitPointersImpl().
VisitPointers() [2/2]
template<typename ConcreteVisitor >
void v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) [inline], [final], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 124 of file marking-visitor.h.
                                                     {
    VisitPointersImpl(host, start, end);
  }
References v8::internal::compiler::end(), and v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitPointersImpl().
VisitPointersImpl()
template<typename ConcreteVisitor >
template<typename TSlot >
void v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitPointersImpl (Tagged< HeapObject > host, TSlot start, TSlot end) [inline], [protected]
Definition at line 139 of file marking-visitor-inl.h.
                                                     {
  using THeapObjectSlot = typename TSlot::THeapObjectSlot;
  for (TSlot slot = start; slot < end; ++slot) {
    typename TSlot::TObject object;
    if constexpr (SlotHoldsTrustedPointerV<TSlot>) {
      // The fast check doesn't support the trusted cage, so skip it.
      object = slot.Relaxed_Load();
    } else {
      const std::optional<Tagged<Object>> optional_object =
          this->GetObjectFilterReadOnlyAndSmiFast(slot);
      if (!optional_object) {
        continue;
      }
      object = *optional_object;
    }
    Tagged<HeapObject> heap_object;
    if (object.GetHeapObjectIfStrong(&heap_object)) {
      // If the reference changes concurrently from strong to weak, the write
      // barrier will treat the weak reference as strong, so we won't miss the
      // weak reference.
      ProcessStrongHeapObject(host, THeapObjectSlot(slot), heap_object);
    } else if (TSlot::kCanBeWeak && object.GetHeapObjectIfWeak(&heap_object)) {
      ProcessWeakHeapObject(host, THeapObjectSlot(slot), heap_object);
    }
  }
}
References v8::internal::compiler::end().
Referenced by v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitPointer(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitPointers(), and v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitProtectedPointer().
VisitProtectedPointer() [1/2]
template<typename ConcreteVisitor >
void v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitProtectedPointer (Tagged< TrustedObject > host, ProtectedMaybeObjectSlot slot) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 165 of file marking-visitor.h.
                                                                            {
    VisitPointersImpl(host, slot, slot + 1);
  }
References v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitPointersImpl().
VisitProtectedPointer() [2/2]
template<typename ConcreteVisitor >
void v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitProtectedPointer (Tagged< TrustedObject > host, ProtectedPointerSlot slot) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 160 of file marking-visitor.h.
                                                                        {
    VisitStrongPointerImpl(host, slot);
  }
References v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitStrongPointerImpl().
VisitSharedFunctionInfo()
template<typename ConcreteVisitor >
size_t v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitSharedFunctionInfo (Tagged< Map > map, Tagged< SharedFunctionInfo > object, MaybeObjectSize maybe_object_size) [inline]
Definition at line 389 of file marking-visitor-inl.h.
                                       {
  const bool can_flush_bytecode = HasBytecodeArrayForFlushing(shared_info);
  // We found a BytecodeArray that can be flushed. Increment the age of the SFI.
  if (can_flush_bytecode && !should_keep_ages_unchanged_) {
    MakeOlder(shared_info);
  }
  if (!can_flush_bytecode || !ShouldFlushCode(shared_info)) {
    // If the SharedFunctionInfo doesn't have old bytecode visit the function
    // data strongly.
#ifdef V8_ENABLE_SANDBOX
    VisitIndirectPointer(shared_info,
                         shared_info->RawIndirectPointerField(
                             SharedFunctionInfo::kTrustedFunctionDataOffset,
                             kUnknownIndirectPointerTag),
                         IndirectPointerMode::kStrong);
#else
    VisitPointer(
        shared_info,
        shared_info->RawField(SharedFunctionInfo::kTrustedFunctionDataOffset));
#endif
    VisitPointer(shared_info,
                 shared_info->RawField(
                     SharedFunctionInfo::kUntrustedFunctionDataOffset));
  } else if (!IsByteCodeFlushingEnabled(code_flush_mode_)) {
    // If bytecode flushing is disabled but baseline code flushing is enabled
    // then we have to visit the bytecode but not the baseline code.
    DCHECK(IsBaselineCodeFlushingEnabled(code_flush_mode_));
    Tagged<Code> baseline_code = shared_info->baseline_code(kAcquireLoad);
    // Visit the bytecode hanging off baseline code.
    VisitProtectedPointer(
        baseline_code, baseline_code->RawProtectedPointerField(
                           Code::kDeoptimizationDataOrInterpreterDataOffset));
    local_weak_objects_->code_flushing_candidates_local.Push(shared_info);
  } else {
    // In other cases, record as a flushing candidate since we have old
    // bytecode.
    local_weak_objects_->code_flushing_candidates_local.Push(shared_info);
  }
  return Base::VisitSharedFunctionInfo(map, shared_info, maybe_object_size);
}
References v8::internal::DCHECK(), v8::internal::IsBaselineCodeFlushingEnabled(), v8::internal::IsByteCodeFlushingEnabled(), v8::kAcquireLoad, v8::internal::kStrong, and v8::internal::kUnknownIndirectPointerTag.
VisitStrongPointerImpl()
template<typename ConcreteVisitor >
template<typename TSlot >
void v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitStrongPointerImpl (Tagged< HeapObject > host, TSlot slot) [inline], [protected]
Definition at line 171 of file marking-visitor-inl.h.
                                         {
  static_assert(!TSlot::kCanBeWeak);
  using THeapObjectSlot = typename TSlot::THeapObjectSlot;
  typename TSlot::TObject object = slot.Relaxed_Load();
  Tagged<HeapObject> heap_object;
  if (object.GetHeapObject(&heap_object)) {
    ProcessStrongHeapObject(host, THeapObjectSlot(slot), heap_object);
  }
}
Referenced by v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitInstructionStreamPointer(), and v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitProtectedPointer().
VisitTransitionArray()
template<typename ConcreteVisitor >
size_t v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitTransitionArray (Tagged< Map > map, Tagged< TransitionArray > object, MaybeObjectSize maybe_object_size) [inline]
Definition at line 886 of file marking-visitor-inl.h.
                                       {
  local_weak_objects_->transition_arrays_local.Push(array);
  return Base::VisitTransitionArray(map, array, maybe_object_size);
}
VisitTrustedPointerTableEntry()
template<typename ConcreteVisitor >
void v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitTrustedPointerTableEntry (Tagged< HeapObject > host, IndirectPointerSlot slot) [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 305 of file marking-visitor-inl.h.
                                                       {
  concrete_visitor()->MarkPointerTableEntry(host, slot);
}
VisitWeakCell()
template<typename ConcreteVisitor >
size_t v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitWeakCell (Tagged< Map > map, Tagged< WeakCell > object, MaybeObjectSize maybe_object_size) [inline]
Definition at line 723 of file marking-visitor-inl.h.
                                       {
  Tagged<HeapObject> target = weak_cell->relaxed_target();
  Tagged<HeapObject> unregister_token = weak_cell->relaxed_unregister_token();
  SynchronizePageAccess(target);
  SynchronizePageAccess(unregister_token);
  if (MarkingHelper::IsMarkedOrAlwaysLive(
          heap_, concrete_visitor()->marking_state(), target) &&
      MarkingHelper::IsMarkedOrAlwaysLive(
          heap_, concrete_visitor()->marking_state(), unregister_token)) {
    // Record the slots inside the WeakCell, since its IterateBody doesn't visit
    // it.
    ObjectSlot slot = weak_cell->RawField(WeakCell::kTargetOffset);
    concrete_visitor()->RecordSlot(weak_cell, slot, target);
    slot = weak_cell->RawField(WeakCell::kUnregisterTokenOffset);
    concrete_visitor()->RecordSlot(weak_cell, slot, unregister_token);
  } else {
    // WeakCell points to a potentially dead object or a dead unregister
    // token. We have to process them when we know the liveness of the whole
    // transitive closure.
    local_weak_objects_->weak_cells_local.Push(weak_cell);
    concrete_visitor()->AddWeakReferenceForReferenceSummarizer(weak_cell,
                                                               target);
    concrete_visitor()->AddWeakReferenceForReferenceSummarizer(
        weak_cell, unregister_token);
  }
  return Base::VisitWeakCell(map, weak_cell, maybe_object_size);
}
References v8::internal::MarkingHelper::IsMarkedOrAlwaysLive().
Member Data Documentation
code_flush_mode_
template<typename ConcreteVisitor >
const base::EnumSet<CodeFlushMode> v8::internal::MarkingVisitorBase< ConcreteVisitor >::code_flush_mode_ [protected]
Definition at line 236 of file marking-visitor.h.
code_flushing_increase_
template<typename ConcreteVisitor >
const uint16_t v8::internal::MarkingVisitorBase< ConcreteVisitor >::code_flushing_increase_ [protected]
Definition at line 238 of file marking-visitor.h.
heap_
template<typename ConcreteVisitor >
Heap* const v8::internal::MarkingVisitorBase< ConcreteVisitor >::heap_ [protected]
Definition at line 234 of file marking-visitor.h.
Referenced by v8::internal::ConcurrentMarkingVisitor::ProcessEphemeron().
isolate_in_background_
template<typename ConcreteVisitor >
const bool v8::internal::MarkingVisitorBase< ConcreteVisitor >::isolate_in_background_ [protected]
Definition at line 239 of file marking-visitor.h.
key_to_values_
template<typename ConcreteVisitor >
KeyToValues* v8::internal::MarkingVisitorBase< ConcreteVisitor >::key_to_values_ = nullptr [protected]
Definition at line 233 of file marking-visitor.h.
Referenced by v8::internal::MarkingVisitorBase< ConcreteVisitor >::SetKeyToValues().
local_marking_worklists_
template<typename ConcreteVisitor >
MarkingWorklists::Local* const v8::internal::MarkingVisitorBase< ConcreteVisitor >::local_marking_worklists_ [protected]
Definition at line 231 of file marking-visitor.h.
local_weak_objects_
template<typename ConcreteVisitor >
WeakObjects::Local* const v8::internal::MarkingVisitorBase< ConcreteVisitor >::local_weak_objects_ [protected]
Definition at line 232 of file marking-visitor.h.
Referenced by v8::internal::ConcurrentMarkingVisitor::ProcessEphemeron().
mark_compact_epoch_
template<typename ConcreteVisitor >
const unsigned v8::internal::MarkingVisitorBase< ConcreteVisitor >::mark_compact_epoch_ [protected]
Definition at line 235 of file marking-visitor.h.
should_keep_ages_unchanged_
template<typename ConcreteVisitor >
const bool v8::internal::MarkingVisitorBase< ConcreteVisitor >::should_keep_ages_unchanged_ [protected]
Definition at line 237 of file marking-visitor.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/marking-visitor.h
/mnt/V8SourceCode/src/heap/marking-visitor-inl.h