v8::internal::ArrayBoilerplateDescription Class Reference
#include <literal-objects.h>
Public Types
using BodyDescriptor = StructBodyDescriptor
Public Member Functions
ElementsKind elements_kind () const
void set_elements_kind (ElementsKind kind)
bool is_empty () const
void BriefPrintDetails (std::ostream &os)
Detailed Description
Definition at line 82 of file literal-objects.h.
Member Typedef Documentation
BodyDescriptor
using v8::internal::ArrayBoilerplateDescription::BodyDescriptor = StructBodyDescriptor
Definition at line 95 of file literal-objects.h.
Member Function Documentation
BriefPrintDetails()
void v8::internal::ArrayBoilerplateDescription::BriefPrintDetails (std::ostream & os)
Definition at line 832 of file literal-objects.cc.
                                                                  {
  os << " " << ElementsKindToString(elements_kind()) << ", "
     << Brief(constant_elements());
}
References elements_kind(), and v8::internal::ElementsKindToString().
elements_kind()
kStaticElementsTemplateOffset kInstancePropertiesTemplateOffset kInstanceComputedPropertiesOffset ElementsKind v8::internal::ArrayBoilerplateDescription::elements_kind () const [inline]
Definition at line 115 of file literal-objects-inl.h.
                                                              {
  return static_cast<ElementsKind>(flags());
}
References v8::internal::flags.
Referenced by BriefPrintDetails().
is_empty()
bool v8::internal::ArrayBoilerplateDescription::is_empty () const [inline]
Definition at line 123 of file literal-objects-inl.h.
                                                 {
  return constant_elements()->length() == 0;
}
set_elements_kind()
void v8::internal::ArrayBoilerplateDescription::set_elements_kind (ElementsKind kind) [inline]
Definition at line 119 of file literal-objects-inl.h.
                                                                     {
  set_flags(kind);
}
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/literal-objects.h
/mnt/V8SourceCode/src/objects/literal-objects-inl.h
/mnt/V8SourceCode/src/objects/literal-objects.cc