v8::internal::compiler::FrameOffset Class Reference
#include <frame.h>
Public Member Functions
bool from_stack_pointer ()
bool from_frame_pointer ()
int offset ()
Static Public Member Functions
static FrameOffset FromStackPointer (int offset)
static FrameOffset FromFramePointer (int offset)
Private Member Functions
FrameOffset (int offset)
Private Attributes
int offset_
Static Private Attributes
static const int kFromSp = 1
static const int kFromFp = 0
Detailed Description
Definition at line 212 of file frame.h.
Constructor & Destructor Documentation
FrameOffset()
v8::internal::compiler::FrameOffset::FrameOffset (int offset) [inline], [explicit], [private]
Definition at line 229 of file frame.h.
: offset_(offset) {}
Referenced by FromFramePointer(), and FromStackPointer().
Member Function Documentation
from_frame_pointer()
bool v8::internal::compiler::FrameOffset::from_frame_pointer () [inline]
Definition at line 215 of file frame.h.
{ return (offset_ & 1) == kFromFp; }
References kFromFp, and offset_.
Referenced by v8::internal::compiler::CodeGenerator::AssembleConstructFrame(), and v8::internal::compiler::Arm64OperandConverter::SlotToMemOperand().
from_stack_pointer()
bool v8::internal::compiler::FrameOffset::from_stack_pointer () [inline]
Definition at line 214 of file frame.h.
{ return (offset_ & 1) == kFromSp; }
References kFromSp, and offset_.
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::ArmOperandConverter::SlotToMemOperand(), v8::internal::compiler::Loong64OperandConverter::SlotToMemOperand(), v8::internal::compiler::MipsOperandConverter::SlotToMemOperand(), v8::internal::compiler::PPCOperandConverter::SlotToMemOperand(), v8::internal::compiler::RiscvOperandConverter::SlotToMemOperand(), v8::internal::compiler::S390OperandConverter::SlotToMemOperand(), v8::internal::compiler::Arm64OperandConverter::SlotToMemOperand(), v8::internal::compiler::IA32OperandConverter::SlotToOperand(), and v8::internal::compiler::X64OperandConverter::SlotToOperand().
FromFramePointer()
static FrameOffset v8::internal::compiler::FrameOffset::FromFramePointer (int offset) [inline], [static]
Definition at line 223 of file frame.h.
                                                         {
    DCHECK_EQ(0, offset & 1);
    return FrameOffset(offset | kFromFp);
  }
References DCHECK_EQ, FrameOffset(), kFromFp, and offset().
Referenced by v8::internal::compiler::FrameAccessState::GetFrameOffset().
FromStackPointer()
static FrameOffset v8::internal::compiler::FrameOffset::FromStackPointer (int offset) [inline], [static]
Definition at line 218 of file frame.h.
                                                         {
    DCHECK_EQ(0, offset & 1);
    return FrameOffset(offset | kFromSp);
  }
References DCHECK_EQ, FrameOffset(), kFromSp, and offset().
Referenced by v8::internal::compiler::FrameAccessState::GetFrameOffset(), and v8::internal::compiler::Arm64OperandConverter::SlotToMemOperand().
offset()
int v8::internal::compiler::FrameOffset::offset () [inline]
Definition at line 216 of file frame.h.
{ return offset_ & ~1; }
References offset_.
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::CodeGenerator::AssembleConstructFrame(), FromFramePointer(), FromStackPointer(), v8::internal::compiler::ArmOperandConverter::SlotToMemOperand(), v8::internal::compiler::Loong64OperandConverter::SlotToMemOperand(), v8::internal::compiler::MipsOperandConverter::SlotToMemOperand(), v8::internal::compiler::PPCOperandConverter::SlotToMemOperand(), v8::internal::compiler::RiscvOperandConverter::SlotToMemOperand(), v8::internal::compiler::S390OperandConverter::SlotToMemOperand(), v8::internal::compiler::Arm64OperandConverter::SlotToMemOperand(), v8::internal::compiler::IA32OperandConverter::SlotToOperand(), and v8::internal::compiler::X64OperandConverter::SlotToOperand().
Member Data Documentation
kFromFp
const int v8::internal::compiler::FrameOffset::kFromFp = 0 [static], [private]
Definition at line 234 of file frame.h.
Referenced by from_frame_pointer(), and FromFramePointer().
kFromSp
const int v8::internal::compiler::FrameOffset::kFromSp = 1 [static], [private]
Definition at line 233 of file frame.h.
Referenced by from_stack_pointer(), and FromStackPointer().
offset_
int v8::internal::compiler::FrameOffset::offset_ [private]
Definition at line 231 of file frame.h.
Referenced by from_frame_pointer(), from_stack_pointer(), and offset().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/frame.h