v8::Symbol Class Reference
A JavaScript symbol (ECMA-262 edition 6)
#include <v8-primitive.h>
Public Member Functions
Local< Value > Description (Isolate *isolate) const
Returns the description string of the symbol, or undefined if none.
Static Public Member Functions
static Local< Symbol > New (Isolate *isolate, Local< String > description=Local< String >())
Create a symbol.
static Local< Symbol > For (Isolate *isolate, Local< String > description)
Access global symbol registry.
static Local< Symbol > ForApi (Isolate *isolate, Local< String > description)
Retrieve a global symbol.
static Local< Symbol > GetAsyncIterator (Isolate *isolate)
static Local< Symbol > GetHasInstance (Isolate *isolate)
static Local< Symbol > GetIsConcatSpreadable (Isolate *isolate)
static Local< Symbol > GetIterator (Isolate *isolate)
static Local< Symbol > GetMatch (Isolate *isolate)
static Local< Symbol > GetReplace (Isolate *isolate)
static Local< Symbol > GetSearch (Isolate *isolate)
static Local< Symbol > GetSplit (Isolate *isolate)
static Local< Symbol > GetToPrimitive (Isolate *isolate)
static Local< Symbol > GetToStringTag (Isolate *isolate)
static Local< Symbol > GetUnscopables (Isolate *isolate)
static Local< Symbol > GetDispose (Isolate *isolate)
static Local< Symbol > GetAsyncDispose (Isolate *isolate)
static Symbol * Cast (Data *data)
Private Member Functions
Symbol ()
Static Private Member Functions
static void CheckCast (Data *that)
Detailed Description
A JavaScript symbol (ECMA-262 edition 6)
Definition at line 778 of file v8-primitive.h.
Constructor & Destructor Documentation
Symbol()
v8::Symbol::Symbol () [private]
Member Function Documentation
Cast()
static Symbol* v8::Symbol::Cast (Data * data) [inline], [static]
Definition at line 823 of file v8-primitive.h.
                                            {
#ifdef V8_ENABLE_CHECKS
    CheckCast(data);
#endif
    return static_cast<Symbol*>(data);
  }
CheckCast()
void v8::Symbol::CheckCast (v8::Data * that) [static], [private]
Definition at line 3892 of file api.cc.
                                     {
  auto obj = Utils::OpenDirectHandle(that);
  Utils::ApiCheck(i::IsSymbol(*obj), "v8::Symbol::Cast",
                  "Value is not a Symbol");
}
References v8::Utils::ApiCheck(), and v8::Utils::OpenDirectHandle().
Description()
Local< Value > v8::Symbol::Description (Isolate * isolate) const
Returns the description string of the symbol, or undefined if none.
Definition at line 6169 of file api.cc.
                                                          {
  auto sym = Utils::OpenDirectHandle(this);
  i::Isolate* isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  return Utils::ToLocal(i::direct_handle(sym->description(), isolate));
}
References v8::internal::direct_handle(), and v8::Utils::OpenDirectHandle().
Referenced by v8::Private::Name().
For()
Local< Symbol > v8::Symbol::For (Isolate * isolate, Local< String > description) [static]
Access global symbol registry.
Note that symbols created this way are never collected, so they should only be used for statically fixed properties. Also, there is only one global name space for the descriptions used as keys. To minimize the potential for clashes, use qualified names as keys.
Definition at line 9469 of file api.cc.
                                                                   {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  auto i_name = Utils::OpenHandle(*name);
  return Utils::ToLocal(
      i_isolate->SymbolFor(i::RootIndex::kPublicSymbolTable, i_name, false));
}
References name, v8::Utils::OpenHandle(), and v8::internal::Isolate::SymbolFor().
ForApi()
Local< Symbol > v8::Symbol::ForApi (Isolate * isolate, Local< String > description) [static]
Retrieve a global symbol.
Similar to |For|, but using a separate registry that is not accessible by (and cannot clash with) JavaScript code.
Definition at line 9477 of file api.cc.
                                                                      {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  auto i_name = Utils::OpenHandle(*name);
  return Utils::ToLocal(
      i_isolate->SymbolFor(i::RootIndex::kApiSymbolTable, i_name, false));
}
References name, v8::Utils::OpenHandle(), and v8::internal::Isolate::SymbolFor().
GetAsyncDispose()
static Local<Symbol> v8::Symbol::GetAsyncDispose (Isolate * isolate) [static]
GetAsyncIterator()
static Local<Symbol> v8::Symbol::GetAsyncIterator (Isolate * isolate) [static]
GetDispose()
static Local<Symbol> v8::Symbol::GetDispose (Isolate * isolate) [static]
GetHasInstance()
static Local<Symbol> v8::Symbol::GetHasInstance (Isolate * isolate) [static]
GetIsConcatSpreadable()
static Local<Symbol> v8::Symbol::GetIsConcatSpreadable (Isolate * isolate) [static]
GetIterator()
static Local<Symbol> v8::Symbol::GetIterator (Isolate * isolate) [static]
GetMatch()
static Local<Symbol> v8::Symbol::GetMatch (Isolate * isolate) [static]
GetReplace()
static Local<Symbol> v8::Symbol::GetReplace (Isolate * isolate) [static]
GetSearch()
static Local<Symbol> v8::Symbol::GetSearch (Isolate * isolate) [static]
GetSplit()
static Local<Symbol> v8::Symbol::GetSplit (Isolate * isolate) [static]
GetToPrimitive()
static Local<Symbol> v8::Symbol::GetToPrimitive (Isolate * isolate) [static]
GetToStringTag()
static Local<Symbol> v8::Symbol::GetToStringTag (Isolate * isolate) [static]
Referenced by v8::Shell::CreateGlobalTemplate().
GetUnscopables()
static Local<Symbol> v8::Symbol::GetUnscopables (Isolate * isolate) [static]
New()
Local< Symbol > v8::Symbol::New (Isolate * isolate, Local< String > description = Local<String>()) [static]
Create a symbol.
If description is not empty, it will be used as the description.
Definition at line 9460 of file api.cc.
                                                                   {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  ApiRuntimeCallStatsScope rcs_scope(i_isolate, RCCId::kAPI_Symbol_New);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::DirectHandle<i::Symbol> result = i_isolate->factory()->NewSymbol();
  if (!name.IsEmpty()) result->set_description(*Utils::OpenDirectHandle(*name));
  return Utils::ToLocal(result);
}
References v8::internal::Isolate::factory(), name, v8::internal::Factory::NewSymbol(), v8::Utils::OpenDirectHandle(), and v8::base::internal::result.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-primitive.h
/mnt/V8SourceCode/src/api/api.cc