v8::internal::GCTracer::RecordGCPhasesInfo Class Reference
#include <gc-tracer.h>
Public Types
enum class Mode { None
, Scavenger
, Finalize
 }
Public Member Functions
RecordGCPhasesInfo (Heap *heap, GarbageCollector collector, GarbageCollectionReason reason)
Mode mode () const
const char * trace_event_name () const
TimedHistogram * type_timer () const
TimedHistogram * type_priority_timer () const
Private Attributes
Mode mode_
const char * trace_event_name_
TimedHistogram * type_timer_
TimedHistogram * type_priority_timer_
Detailed Description
Definition at line 255 of file gc-tracer.h.
Member Enumeration Documentation
Mode
enum v8::internal::GCTracer::RecordGCPhasesInfo::Mode [strong]
Enumerator
None
Scavenger
Finalize
Definition at line 260 of file gc-tracer.h.
{ None, Scavenger, Finalize };
Constructor & Destructor Documentation
RecordGCPhasesInfo()
v8::internal::GCTracer::RecordGCPhasesInfo::RecordGCPhasesInfo (Heap * heap, GarbageCollector collector, GarbageCollectionReason reason)
Definition at line 96 of file gc-tracer.cc.
                                                                            {
  if (Heap::IsYoungGenerationCollector(collector)) {
    type_timer_ = nullptr;
    type_priority_timer_ = nullptr;
    if (!v8_flags.minor_ms) {
      mode_ = Mode::Scavenger;
      trace_event_name_ = "V8.GCScavenger";
    } else {
      mode_ = Mode::None;
      trace_event_name_ = "V8.GCMinorMS";
    }
  } else {
    DCHECK_EQ(GarbageCollector::MARK_COMPACTOR, collector);
    Counters* counters = heap->isolate()->counters();
    const bool in_background = heap->isolate()->is_backgrounded();
    const bool is_incremental = !heap->incremental_marking()->IsStopped();
    mode_ = Mode::None;
    // The following block selects histogram counters to emit. The trace event
    // name should be changed when metrics are updated.
    //
    // Memory reducing GCs take priority over memory measurement GCs. They can
    // happen at the same time when measuring memory is folded into a memory
    // reducing GC.
    if (is_incremental) {
      if (heap->ShouldReduceMemory()) {
        type_timer_ = counters->gc_finalize_incremental_memory_reducing();
        type_priority_timer_ =
            in_background
                ? counters->gc_finalize_incremental_memory_reducing_background()
                : counters
                      ->gc_finalize_incremental_memory_reducing_foreground();
        trace_event_name_ = "V8.GCFinalizeMCReduceMemory";
      } else if (reason == GarbageCollectionReason::kMeasureMemory) {
        type_timer_ = counters->gc_finalize_incremental_memory_measure();
        type_priority_timer_ =
            in_background
                ? counters->gc_finalize_incremental_memory_measure_background()
                : counters->gc_finalize_incremental_memory_measure_foreground();
        trace_event_name_ = "V8.GCFinalizeMCMeasureMemory";
      } else {
        type_timer_ = counters->gc_finalize_incremental_regular();
        type_priority_timer_ =
            in_background
                ? counters->gc_finalize_incremental_regular_background()
                : counters->gc_finalize_incremental_regular_foreground();
        trace_event_name_ = "V8.GCFinalizeMC";
        mode_ = Mode::Finalize;
      }
    } else {
      trace_event_name_ = "V8.GCCompactor";
      if (heap->ShouldReduceMemory()) {
        type_timer_ = counters->gc_finalize_non_incremental_memory_reducing();
        type_priority_timer_ =
            in_background
                ? counters
                      ->gc_finalize_non_incremental_memory_reducing_background()
                : counters
                      ->gc_finalize_non_incremental_memory_reducing_foreground();
      } else if (reason == GarbageCollectionReason::kMeasureMemory) {
        type_timer_ = counters->gc_finalize_non_incremental_memory_measure();
        type_priority_timer_ =
            in_background
                ? counters
                      ->gc_finalize_non_incremental_memory_measure_background()
                : counters
                      ->gc_finalize_non_incremental_memory_measure_foreground();
      } else {
        type_timer_ = counters->gc_finalize_non_incremental_regular();
        type_priority_timer_ =
            in_background
                ? counters->gc_finalize_non_incremental_regular_background()
                : counters->gc_finalize_non_incremental_regular_foreground();
      }
    }
  }
}
References DCHECK_EQ, v8::internal::Heap::IsYoungGenerationCollector(), v8::internal::kMeasureMemory, v8::internal::MARK_COMPACTOR, v8::None, Scavenger, and v8::internal::v8_flags.
Member Function Documentation
mode()
Mode v8::internal::GCTracer::RecordGCPhasesInfo::mode () const [inline]
Definition at line 262 of file gc-tracer.h.
{ return mode_; }
Referenced by v8::internal::Heap::CollectGarbage().
trace_event_name()
const char* v8::internal::GCTracer::RecordGCPhasesInfo::trace_event_name () const [inline]
Definition at line 263 of file gc-tracer.h.
{ return trace_event_name_; }
Referenced by v8::internal::Heap::CollectGarbage().
type_priority_timer()
TimedHistogram* v8::internal::GCTracer::RecordGCPhasesInfo::type_priority_timer () const [inline]
Definition at line 267 of file gc-tracer.h.
{ return type_priority_timer_; }
Referenced by v8::internal::Heap::CollectGarbage().
type_timer()
TimedHistogram* v8::internal::GCTracer::RecordGCPhasesInfo::type_timer () const [inline]
Definition at line 266 of file gc-tracer.h.
{ return type_timer_; }
Referenced by v8::internal::Heap::CollectGarbage().
Member Data Documentation
mode_
Mode v8::internal::GCTracer::RecordGCPhasesInfo::mode_ [private]
Definition at line 270 of file gc-tracer.h.
trace_event_name_
const char* v8::internal::GCTracer::RecordGCPhasesInfo::trace_event_name_ [private]
Definition at line 271 of file gc-tracer.h.
type_priority_timer_
TimedHistogram* v8::internal::GCTracer::RecordGCPhasesInfo::type_priority_timer_ [private]
Definition at line 273 of file gc-tracer.h.
type_timer_
TimedHistogram* v8::internal::GCTracer::RecordGCPhasesInfo::type_timer_ [private]
Definition at line 272 of file gc-tracer.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/gc-tracer.h
/mnt/V8SourceCode/src/heap/gc-tracer.cc