v8::internal::compiler::GetIteratorParameters Class Reference
#include <js-operator.h>
Public Member Functions
GetIteratorParameters (const FeedbackSource &load_feedback, const FeedbackSource &call_feedback)
FeedbackSource const & loadFeedback () const
FeedbackSource const & callFeedback () const
Private Attributes
FeedbackSource const load_feedback_
FeedbackSource const call_feedback_
Detailed Description
Definition at line 794 of file js-operator.h.
Constructor & Destructor Documentation
GetIteratorParameters()
v8::internal::compiler::GetIteratorParameters::GetIteratorParameters (const FeedbackSource & load_feedback, const FeedbackSource & call_feedback) [inline]
Definition at line 796 of file js-operator.h.
      : load_feedback_(load_feedback), call_feedback_(call_feedback) {}
Member Function Documentation
callFeedback()
FeedbackSource const& v8::internal::compiler::GetIteratorParameters::callFeedback () const [inline]
Definition at line 801 of file js-operator.h.
{ return call_feedback_; }
References call_feedback_.
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), and v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetIterator().
loadFeedback()
FeedbackSource const& v8::internal::compiler::GetIteratorParameters::loadFeedback () const [inline]
Definition at line 800 of file js-operator.h.
{ return load_feedback_; }
References load_feedback_.
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), and v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetIterator().
Member Data Documentation
call_feedback_
FeedbackSource const v8::internal::compiler::GetIteratorParameters::call_feedback_ [private]
Definition at line 805 of file js-operator.h.
Referenced by callFeedback().
load_feedback_
FeedbackSource const v8::internal::compiler::GetIteratorParameters::load_feedback_ [private]
Definition at line 804 of file js-operator.h.
Referenced by loadFeedback().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h