v8::internal::RegExpInstruction::LookaroundPayload Class Reference
#include <experimental-bytecode.h>
Public Member Functions
LookaroundPayload ()=default
LookaroundPayload (uint32_t lookaround_index, bool is_positive, RegExpLookaround::Type type)
uint32_t index () const
bool is_positive () const
RegExpLookaround::Type type () const
Private Types
using IsPositive = base::BitField< bool, 0, 1 >
using Type = IsPositive::Next< RegExpLookaround::Type, 1 >
using LookaroundIndex = Type::Next< uint32_t, 30 >
Private Attributes
uint32_t payload_
Detailed Description
Definition at line 127 of file experimental-bytecode.h.
Member Typedef Documentation
IsPositive
using v8::internal::RegExpInstruction::LookaroundPayload::IsPositive = base::BitField<bool, 0, 1> [private]
Definition at line 142 of file experimental-bytecode.h.
LookaroundIndex
using v8::internal::RegExpInstruction::LookaroundPayload::LookaroundIndex = Type::Next<uint32_t, 30> [private]
Definition at line 144 of file experimental-bytecode.h.
Type
using v8::internal::RegExpInstruction::LookaroundPayload::Type = IsPositive::Next<RegExpLookaround::Type, 1> [private]
Definition at line 143 of file experimental-bytecode.h.
Constructor & Destructor Documentation
LookaroundPayload() [1/2]
v8::internal::RegExpInstruction::LookaroundPayload::LookaroundPayload () [default]
LookaroundPayload() [2/2]
v8::internal::RegExpInstruction::LookaroundPayload::LookaroundPayload (uint32_t lookaround_index, bool is_positive, RegExpLookaround::Type type) [inline]
Definition at line 130 of file experimental-bytecode.h.
        : payload_(Type::update(
              IsPositive::update(LookaroundIndex::encode(lookaround_index),
                                 is_positive),
              type)) {}
Member Function Documentation
index()
uint32_t v8::internal::RegExpInstruction::LookaroundPayload::index () const [inline]
Definition at line 137 of file experimental-bytecode.h.
{ return LookaroundIndex::decode(payload_); }
References v8::base::BitField< T, shift, size, U >::decode(), and payload_.
Referenced by v8::internal::operator<<(), and v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::RunActiveThread().
is_positive()
bool v8::internal::RegExpInstruction::LookaroundPayload::is_positive () const [inline]
Definition at line 138 of file experimental-bytecode.h.
{ return IsPositive::decode(payload_); }
References v8::base::BitField< T, shift, size, U >::decode(), and payload_.
Referenced by v8::internal::operator<<(), and v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::RunActiveThread().
type()
RegExpLookaround::Type v8::internal::RegExpInstruction::LookaroundPayload::type () const [inline]
Definition at line 139 of file experimental-bytecode.h.
{ return Type::decode(payload_); }
References v8::base::BitField< T, shift, size, U >::decode(), and payload_.
Referenced by v8::internal::operator<<().
Member Data Documentation
payload_
uint32_t v8::internal::RegExpInstruction::LookaroundPayload::payload_ [private]
Definition at line 146 of file experimental-bytecode.h.
Referenced by index(), is_positive(), and type().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/regexp/experimental/experimental-bytecode.h