v8::Script Class Reference
A compiled JavaScript script, tied to a Context which was active when the script was compiled.
#include <v8-script.h>
Public Member Functions
V8_WARN_UNUSED_RESULT MaybeLocal< Value > Run (Local< Context > context)
Runs the script returning the resulting value.
V8_WARN_UNUSED_RESULT MaybeLocal< Value > Run (Local< Context > context, Local< Data > host_defined_options)
Local< UnboundScript > GetUnboundScript ()
Returns the corresponding context-unbound script.
Local< Value > GetResourceName ()
The name that was passed by the embedder as ResourceName to the ScriptOrigin.
Use GetCompileHintsCollector instead std::vector< int > GetProducedCompileHints () const
If the script was compiled, returns the positions of lazy functions which were eventually compiled and executed.
Local< CompileHintsCollector > GetCompileHintsCollector () const
Get a compile hints collector object which we can use later for retrieving compile hints (= positions of lazy functions which were compiled and executed).
Static Public Member Functions
static V8_WARN_UNUSED_RESULT MaybeLocal< Script > Compile (Local< Context > context, Local< String > source, ScriptOrigin *origin=nullptr)
A shorthand for ScriptCompiler::Compile().
Detailed Description
A compiled JavaScript script, tied to a Context which was active when the script was compiled.
Definition at line 353 of file v8-script.h.
Member Function Documentation
Compile()
MaybeLocal< Script > v8::Script::Compile (Local< Context > context, Local< String > source, ScriptOrigin * origin = nullptr) [static]
A shorthand for ScriptCompiler::Compile().
Definition at line 2760 of file api.cc.
                                                         {
  if (origin) {
    ScriptCompiler::Source script_source(source, *origin);
    return ScriptCompiler::Compile(context, &script_source);
  }
  ScriptCompiler::Source script_source(source);
  return ScriptCompiler::Compile(context, &script_source);
}
References v8::ScriptCompiler::Compile().
Referenced by v8::Shell::Stringify().
GetCompileHintsCollector()
Local< CompileHintsCollector > v8::Script::GetCompileHintsCollector () const
Get a compile hints collector object which we can use later for retrieving compile hints (= positions of lazy functions which were compiled and executed).
Definition at line 2025 of file api.cc.
                                                                    {
  i::DisallowGarbageCollection no_gc;
  auto func = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  i::Tagged<i::SharedFunctionInfo> sfi = func->shared();
  CHECK(IsScript(sfi->script()));
  i::DirectHandle<i::Script> script(i::Cast<i::Script>(sfi->script()),
                                    i_isolate);
  return ToApiHandle<CompileHintsCollector>(script);
}
References CHECK, v8::internal::Isolate::Current(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::Utils::OpenDirectHandle(), and v8::internal::script.
GetProducedCompileHints()
std::vector< int > v8::Script::GetProducedCompileHints () const
If the script was compiled, returns the positions of lazy functions which were eventually compiled and executed.
Definition at line 2002 of file api.cc.
                                                     {
  i::DisallowGarbageCollection no_gc;
  auto func = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  i::Tagged<i::SharedFunctionInfo> sfi = func->shared();
  CHECK(IsScript(sfi->script()));
  i::Tagged<i::Script> script = i::Cast<i::Script>(sfi->script());
  i::Tagged<i::Object> maybe_array_list =
      script->compiled_lazy_function_positions();
  std::vector<int> result;
  if (!IsUndefined(maybe_array_list, i_isolate)) {
    i::Tagged<i::ArrayList> array_list =
        i::Cast<i::ArrayList>(maybe_array_list);
    result.reserve(array_list->length());
    for (int i = 0; i < array_list->length(); ++i) {
      i::Tagged<i::Object> item = array_list->get(i);
      CHECK(IsSmi(item));
      result.push_back(i::Smi::ToInt(item));
    }
  }
  return result;
}
References CHECK, v8::internal::Isolate::Current(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::IsSmi(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::Utils::OpenDirectHandle(), v8::base::internal::result, v8::internal::script, and v8::internal::Smi::ToInt().
GetResourceName()
Local< Value > v8::Script::GetResourceName ()
The name that was passed by the embedder as ResourceName to the ScriptOrigin.
This can be either a v8::String or v8::Undefined.
Definition at line 1992 of file api.cc.
                                     {
  i::DisallowGarbageCollection no_gc;
  auto func = Utils::OpenDirectHandle(this);
  i::Tagged<i::SharedFunctionInfo> sfi = func->shared();
  CHECK(IsScript(sfi->script()));
  i::Isolate* i_isolate = i::Isolate::Current();
  return ToApiHandle<Value>(
      i::direct_handle(i::Cast<i::Script>(sfi->script())->name(), i_isolate));
}
References CHECK, v8::internal::Isolate::Current(), v8::internal::direct_handle(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::Utils::OpenDirectHandle().
GetUnboundScript()
Local< UnboundScript > v8::Script::GetUnboundScript ()
Returns the corresponding context-unbound script.
Definition at line 1983 of file api.cc.
                                              {
  i::DisallowGarbageCollection no_gc;
  auto obj = Utils::OpenDirectHandle(this);
  i::DirectHandle<i::SharedFunctionInfo> sfi(obj->shared(),
                                             i::Isolate::Current());
  DCHECK(!i::HeapLayout::InReadOnlySpace(*sfi));
  return ToApiHandle<UnboundScript>(sfi);
}
References v8::internal::Isolate::Current(), DCHECK, v8::internal::HeapLayout::InReadOnlySpace(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::Utils::OpenDirectHandle().
Run() [1/2]
MaybeLocal< Value > v8::Script::Run (Local< Context > context)
Runs the script returning the resulting value.
It will be run in the context in which it was created (ScriptCompiler::CompileBound or UnboundScript::BindToCurrentContext()).
Definition at line 1928 of file api.cc.
                                                    {
  return Run(context, Local<Data>());
}
Run() [2/2]
MaybeLocal< Value > v8::Script::Run (Local< Context > context, Local< Data > host_defined_options)
Definition at line 1932 of file api.cc.
                                                                {
  auto i_isolate = i::Isolate::Current();
  TRACE_EVENT_CALL_STATS_SCOPED(i_isolate, "v8", "V8.Execute");
  EnterV8Scope<InternalEscapableScope> api_scope{i_isolate, context,
                                                 RCCId::kAPI_Script_Run};
  i::TimerEventScope<i::TimerEventExecute> timer_scope(i_isolate);
  i::NestedTimedHistogramScope execute_timer(i_isolate->counters()->execute(),
                                             i_isolate);
  i::AggregatingHistogramTimerScope histogram_timer(
      i_isolate->counters()->compile_lazy());
#if defined(V8_ENABLE_ETW_STACK_WALKING)
  // In case ETW has been activated, tasks to log existing code are
  // created. But in case the task runner does not run those before
  // starting to execute code (as it happens in d8, that will run
  // first the code from prompt), then that code will not have
  // JIT instrumentation on time.
  //
  // To avoid this, on running scripts check first if JIT code log is
  // pending and generate immediately.
  if (i::v8_flags.enable_etw_stack_walking ||
      i::v8_flags.enable_etw_by_custom_filter_only) {
    i::ETWJITInterface::MaybeSetHandlerNow(i_isolate);
  }
#endif // V8_ENABLE_ETW_STACK_WALKING
  auto fun = i::Cast<i::JSFunction>(Utils::OpenDirectHandle(this));
  i::DirectHandle<i::Object> receiver = i_isolate->global_proxy();
  // TODO(cbruni, chromium:1244145): Remove once migrated to the context.
  i::DirectHandle<i::Object> options(
      i::Cast<i::Script>(fun->shared()->script())->host_defined_options(),
      i_isolate);
  return api_scope.EscapeMaybe(
      i::Execution::CallScript(i_isolate, fun, receiver, options));
}
References v8::internal::Execution::CallScript(), v8::internal::Isolate::counters(), v8::internal::Isolate::Current(), v8::internal::Isolate::global_proxy(), v8::internal::ETWJITInterface::MaybeSetHandlerNow(), v8::Utils::OpenDirectHandle(), TRACE_EVENT_CALL_STATS_SCOPED, and v8::internal::v8_flags.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-script.h
/mnt/V8SourceCode/src/api/api.cc