v8::internal::FastJsonStringifier< Char > Class Template Reference
Public Member Functions
FastJsonStringifier (Isolate *isolate)
size_t ResultLength () const
template<typename DstChar >
void CopyResultTo (DstChar *out_buffer)
FastJsonStringifierResult SerializeObject (Tagged< JSAny > object, const DisallowGarbageCollection &no_gc)
template<typename OldChar >
requires (sizeof(OldChar)< sizeof(Char)) V8_NOINLINE FastJsonStringifierResult ResumeFrom(FastJsonStringifier< OldChar > &old_stringifier
Public Attributes
const DisallowGarbageCollection & no_gc
Private Types
using FastIterableState = DescriptorArray::FastIterableState
Private Member Functions
void SeparatorUnchecked (bool comma)
void Separator (bool comma)
void SerializeSmi (Tagged< Smi > object)
void SerializeDouble (double number)
template<bool no_escaping>
FastJsonStringifierObjectKeyResult SerializeObjectKey (Tagged< String > key, bool comma, const DisallowGarbageCollection &no_gc)
template<typename StringT , bool no_escaping>
FastJsonStringifierObjectKeyResult SerializeObjectKey (Tagged< String > key, bool comma, const DisallowGarbageCollection &no_gc)
template<typename StringT >
FastJsonStringifierResult SerializeString (Tagged< HeapObject > str, const DisallowGarbageCollection &no_gc)
FastJsonStringifierResult TrySerializeSimpleObject (Tagged< JSAny > object)
FastJsonStringifierResult SerializeObject (ContinuationRecord cont, const DisallowGarbageCollection &no_gc)
V8_NOINLINE FastJsonStringifierResult SerializeJSPrimitiveWrapper (Tagged< JSPrimitiveWrapper > obj, const DisallowGarbageCollection &no_gc)
FastJsonStringifierResult SerializeJSObject (Tagged< JSObject > obj, const DisallowGarbageCollection &no_gc)
template<DescriptorArray::FastIterableState fast_iterable_state>
FastJsonStringifierResult ResumeJSObject (Tagged< JSObject > obj, uint16_t start_descriptor_idx, uint16_t nof_descriptors, uint8_t in_object_properties, uint8_t in_object_properties_start, Tagged< DescriptorArray > descriptors, bool comma, const DisallowGarbageCollection &no_gc)
FastJsonStringifierResult SerializeJSArray (Tagged< JSArray > array)
template<ElementsKind kind>
FastJsonStringifierResult SerializeFixedArrayWithInterruptCheck (Tagged< FixedArrayBase > elements, uint32_t start_index, uint32_t length)
template<ElementsKind kind>
FastJsonStringifierResult SerializeFixedArray (Tagged< FixedArrayBase > array, uint32_t start_idx, uint32_t length)
template<ElementsKind kind, bool with_interrupt_checks, typename T >
FastJsonStringifierResult SerializeFixedArrayElement (Tagged< T > elements, uint32_t i, uint32_t length)
V8_NOINLINE FastJsonStringifierResult HandleInterruptAndCheckCycle ()
V8_NOINLINE bool CheckCycle ()
void EnsureCapacity (size_t size)
template<typename SrcChar >
void AppendCharacterUnchecked (SrcChar c)
template<typename SrcChar >
void AppendCharacter (SrcChar c)
template<size_t N>
void AppendCStringLiteralUnchecked (const char(&literal)[N])
template<size_t N>
void AppendCStringLiteral (const char(&literal)[N])
void AppendCStringUnchecked (const char *chars, size_t len)
void AppendCStringUnchecked (const char *chars)
void AppendStringUnchecked (std::string_view str)
void AppendCString (const char *chars, size_t len)
void AppendCString (const char *chars)
void AppendString (std::string_view str)
template<typename SrcChar >
requires (sizeof(SrcChar)==sizeof(uint8_t)) inline bool AppendString(const SrcChar *chars
template<typename SrcChar >
void AppendStringNoEscapes (const SrcChar *chars, size_t length, const DisallowGarbageCollection &no_gc)
template<typename SrcChar >
requires (sizeof(SrcChar)==sizeof(uint8_t)) bool AppendStringScalar(const SrcChar *chars
template<typename SrcChar >
requires (sizeof(SrcChar)==sizeof(uint8_t)) inline bool AppendStringSWAR(const SrcChar *chars
template<typename SrcChar >
requires (sizeof(SrcChar)==sizeof(uint8_t)) inline bool AppendStringSIMD(const SrcChar *chars
template<typename SrcChar >
requires (sizeof(SrcChar)==sizeof(base::uc16)) inline bool AppendString(const SrcChar *chars
Private Attributes
size_t length
size_t const DisallowGarbageCollection & no_gc
size_t size_t start
size_t size_t size_t uncopied_src_index
size_t size_t size_t const DisallowGarbageCollection & no_gc
Isolate * isolate_
OutBuffer< Char > buffer_
base::SmallVector< ContinuationRecord, 16 > stack_
Tagged< HeapObject > initial_jsobject_proto_
Tagged< HeapObject > initial_jsarray_proto_
Static Private Attributes
static constexpr bool is_one_byte = sizeof(Char) == sizeof(uint8_t)
static constexpr uint32_t kGlobalInterruptBudget = 200000
static constexpr uint32_t kArrayInterruptLength = 4000
Friends
template<typename >
class FastJsonStringifier
Detailed Description
template<typename Char>
class v8::internal::FastJsonStringifier< Char >
Definition at line 2160 of file json-stringifier.cc.
Member Typedef Documentation
FastIterableState
template<typename Char >
using v8::internal::FastJsonStringifier< Char >::FastIterableState = DescriptorArray::FastIterableState [private]
Definition at line 2305 of file json-stringifier.cc.
Constructor & Destructor Documentation
FastJsonStringifier()
template<typename Char >
v8::internal::FastJsonStringifier< Char >::FastJsonStringifier (Isolate * isolate) [explicit]
Definition at line 2355 of file json-stringifier.cc.
    : isolate_(isolate), buffer_(isolate->allocator()) {}
Member Function Documentation
AppendCharacter()
template<typename Char >
template<typename SrcChar >
void v8::internal::FastJsonStringifier< Char >::AppendCharacter (SrcChar c) [inline], [private]
Definition at line 2232 of file json-stringifier.cc.
                                            {
    EnsureCapacity(1);
    AppendCharacterUnchecked(c);
  }
References v8::internal::FastJsonStringifier< Char >::AppendCharacterUnchecked(), and v8::internal::FastJsonStringifier< Char >::EnsureCapacity().
Referenced by v8::internal::FastJsonStringifier< Char >::Separator().
AppendCharacterUnchecked()
template<typename Char >
template<typename SrcChar >
void v8::internal::FastJsonStringifier< Char >::AppendCharacterUnchecked (SrcChar c) [inline], [private]
Definition at line 2228 of file json-stringifier.cc.
                                                     {
    buffer_.AppendCharacter(c);
  }
References v8::internal::FastJsonStringifier< Char >::buffer_.
Referenced by v8::internal::FastJsonStringifier< Char >::AppendCharacter(), v8::internal::FastJsonStringifier< Char >::AppendCStringLiteralUnchecked(), and v8::internal::FastJsonStringifier< Char >::SeparatorUnchecked().
AppendCString() [1/2]
template<typename Char >
void v8::internal::FastJsonStringifier< Char >::AppendCString (const char * chars) [inline], [private]
Definition at line 2267 of file json-stringifier.cc.
                                                  {
    AppendCString(chars, strlen(chars));
  }
References v8::internal::FastJsonStringifier< Char >::AppendCString().
AppendCString() [2/2]
template<typename Char >
void v8::internal::FastJsonStringifier< Char >::AppendCString (const char * chars, size_t len) [inline], [private]
Definition at line 2263 of file json-stringifier.cc.
                                                              {
    EnsureCapacity(len);
    AppendCStringUnchecked(chars, len);
  }
References v8::internal::FastJsonStringifier< Char >::AppendCStringUnchecked(), and v8::internal::FastJsonStringifier< Char >::EnsureCapacity().
Referenced by v8::internal::FastJsonStringifier< Char >::AppendCString(), and v8::internal::FastJsonStringifier< Char >::AppendString().
AppendCStringLiteral()
template<typename Char >
template<size_t N>
void v8::internal::FastJsonStringifier< Char >::AppendCStringLiteral (const char(&) literal[N]) [inline], [private]
Definition at line 2246 of file json-stringifier.cc.
                                                                {
    // Note that the literal contains the zero char.
    constexpr size_t length = N - 1;
    static_assert(length > 0);
    EnsureCapacity(length);
    AppendCStringLiteralUnchecked(literal);
  }
References v8::internal::FastJsonStringifier< Char >::AppendCStringLiteralUnchecked(), v8::internal::FastJsonStringifier< Char >::EnsureCapacity(), v8::internal::FastJsonStringifier< Char >::length, and v8::internal::N.
AppendCStringLiteralUnchecked()
template<typename Char >
template<size_t N>
void v8::internal::FastJsonStringifier< Char >::AppendCStringLiteralUnchecked (const char(&) literal[N]) [inline], [private]
Definition at line 2237 of file json-stringifier.cc.
                                                                         {
    // Note that the literal contains the zero char.
    constexpr size_t length = N - 1;
    static_assert(length > 0);
    if constexpr (length == 1) return AppendCharacterUnchecked(literal[0]);
    const uint8_t* chars = reinterpret_cast<const uint8_t*>(literal);
    buffer_.Append(chars, length);
  }
References v8::internal::FastJsonStringifier< Char >::AppendCharacterUnchecked(), v8::internal::FastJsonStringifier< Char >::buffer_, v8::internal::FastJsonStringifier< Char >::length, and v8::internal::N.
Referenced by v8::internal::FastJsonStringifier< Char >::AppendCStringLiteral().
AppendCStringUnchecked() [1/2]
template<typename Char >
void v8::internal::FastJsonStringifier< Char >::AppendCStringUnchecked (const char * chars) [inline], [private]
Definition at line 2257 of file json-stringifier.cc.
                                                           {
    AppendCStringUnchecked(chars, strlen(chars));
  }
References v8::internal::FastJsonStringifier< Char >::AppendCStringUnchecked().
AppendCStringUnchecked() [2/2]
template<typename Char >
void v8::internal::FastJsonStringifier< Char >::AppendCStringUnchecked (const char * chars, size_t len) [inline], [private]
Definition at line 2254 of file json-stringifier.cc.
                                                                       {
    buffer_.Append(reinterpret_cast<const unsigned char*>(chars), len);
  }
References v8::internal::FastJsonStringifier< Char >::buffer_.
Referenced by v8::internal::FastJsonStringifier< Char >::AppendCString(), v8::internal::FastJsonStringifier< Char >::AppendCStringUnchecked(), and v8::internal::FastJsonStringifier< Char >::AppendStringUnchecked().
AppendString()
template<typename Char >
void v8::internal::FastJsonStringifier< Char >::AppendString (std::string_view str) [inline], [private]
Definition at line 2270 of file json-stringifier.cc.
                                                  {
    AppendCString(str.data(), str.length());
  }
References v8::internal::FastJsonStringifier< Char >::AppendCString().
AppendStringNoEscapes()
template<typename Char >
template<typename SrcChar >
void v8::internal::FastJsonStringifier< Char >::AppendStringNoEscapes (const SrcChar * chars, size_t length, const DisallowGarbageCollection & no_gc) [inline], [private]
Definition at line 3322 of file json-stringifier.cc.
                                            {
  buffer_.Append(chars, length);
}
References v8::internal::length.
AppendStringUnchecked()
template<typename Char >
void v8::internal::FastJsonStringifier< Char >::AppendStringUnchecked (std::string_view str) [inline], [private]
Definition at line 2260 of file json-stringifier.cc.
                                                           {
    AppendCStringUnchecked(str.data(), str.length());
  }
References v8::internal::FastJsonStringifier< Char >::AppendCStringUnchecked().
CheckCycle()
template<typename Char >
bool v8::internal::FastJsonStringifier< Char >::CheckCycle [private]
Definition at line 3291 of file json-stringifier.cc.
                                           {
  std::unordered_set<Address> set;
  for (uint32_t i = 0; i < stack_.size(); i++) {
    ContinuationRecord rec = stack_[i];
    if (rec.type() == ContinuationRecord::kObjectKey ||
        rec.type() == ContinuationRecord::kSimpleObject)
      continue;
    Tagged<Object> obj = rec.object();
    if (V8_UNLIKELY(set.find(obj.ptr()) != set.end())) {
      return true;
    }
    set.insert(obj.ptr());
  }
  return false;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::ContinuationRecord::kObjectKey, v8::internal::ContinuationRecord::kSimpleObject, v8::internal::ContinuationRecord::object(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::internal::ContinuationRecord::type(), and V8_UNLIKELY.
CopyResultTo()
template<typename Char >
template<typename DstChar >
void v8::internal::FastJsonStringifier< Char >::CopyResultTo (DstChar * out_buffer) [inline]
Definition at line 2166 of file json-stringifier.cc.
                                         {
    buffer_.CopyTo(out_buffer);
  }
References v8::internal::FastJsonStringifier< Char >::buffer_.
Referenced by v8::internal::anonymous_namespace{json-stringifier.cc}::FastJsonStringify().
EnsureCapacity()
template<typename Char >
void v8::internal::FastJsonStringifier< Char >::EnsureCapacity (size_t size) [inline], [private]
Definition at line 2226 of file json-stringifier.cc.
{ buffer_.EnsureCapacity(size); }
References v8::internal::FastJsonStringifier< Char >::buffer_, and size().
Referenced by v8::internal::FastJsonStringifier< Char >::AppendCharacter(), v8::internal::FastJsonStringifier< Char >::AppendCString(), and v8::internal::FastJsonStringifier< Char >::AppendCStringLiteral().
HandleInterruptAndCheckCycle()
template<typename Char >
FastJsonStringifierResult v8::internal::FastJsonStringifier< Char >::HandleInterruptAndCheckCycle [private]
Definition at line 3266 of file json-stringifier.cc.
                                                        {
  StackLimitCheck interrupt_check(isolate_);
  {
    // A TerminationException can actually trigger a GC when allocating the
    // message object. We don't touch any of the heap objects after we
    // encountered an exception, so this is fine.
    AllowGarbageCollection allow_gc;
    if (V8_UNLIKELY(interrupt_check.InterruptRequested() &&
                    IsException(isolate_->stack_guard()->HandleInterrupts(
                                    StackGuard::InterruptLevel::kNoGC),
                                isolate_))) {
      return EXCEPTION;
    }
  }
  if (V8_UNLIKELY(CheckCycle())) {
    // TODO(pthier): Construct exception message on fast-path and avoid falling
    // back to slow path just to handle the exception.
    return SLOW_PATH;
  }
  return SUCCESS;
}
References v8::internal::EXCEPTION, v8::internal::StackLimitCheck::InterruptRequested(), v8::internal::StackGuard::kNoGC, v8::internal::SLOW_PATH, v8::internal::SUCCESS, and V8_UNLIKELY.
requires() [1/6]
template<typename Char >
template<typename OldChar >
v8::internal::FastJsonStringifier< Char >::requires () &
requires() [2/6]
template<typename Char >
template<typename SrcChar >
v8::internal::FastJsonStringifier< Char >::requires (sizeof(SrcChar) = = sizeof(base::uc16)) const [private]
requires() [3/6]
template<typename Char >
template<typename SrcChar >
v8::internal::FastJsonStringifier< Char >::requires (sizeof(SrcChar) = = sizeof(uint8_t)) const [private]
requires() [4/6]
template<typename Char >
template<typename SrcChar >
v8::internal::FastJsonStringifier< Char >::requires (sizeof(SrcChar) = = sizeof(uint8_t)) const [private]
requires() [5/6]
template<typename Char >
template<typename SrcChar >
v8::internal::FastJsonStringifier< Char >::requires (sizeof(SrcChar) = = sizeof(uint8_t)) const [private]
requires() [6/6]
template<typename Char >
template<typename SrcChar >
v8::internal::FastJsonStringifier< Char >::requires (sizeof(SrcChar) = = sizeof(uint8_t)) const [private]
ResultLength()
template<typename Char >
size_t v8::internal::FastJsonStringifier< Char >::ResultLength () const [inline]
Definition at line 2164 of file json-stringifier.cc.
{ return buffer_.length(); }
References v8::internal::FastJsonStringifier< Char >::buffer_.
Referenced by v8::internal::anonymous_namespace{json-stringifier.cc}::FastJsonStringify().
ResumeJSObject()
template<typename Char >
template<DescriptorArray::FastIterableState fast_iterable_state>
FastJsonStringifierResult v8::internal::FastJsonStringifier< Char >::ResumeJSObject (Tagged< JSObject > obj, uint16_t start_descriptor_idx, uint16_t nof_descriptors, uint8_t in_object_properties, uint8_t in_object_properties_start, Tagged< DescriptorArray > descriptors, bool comma, const DisallowGarbageCollection & no_gc) [inline], [private]
Definition at line 2772 of file json-stringifier.cc.
                                                        {
  PtrComprCageBase cage_base = GetPtrComprCageBase();
  InternalIndex::Range range{start_descriptor_idx, nof_descriptors};
  for (InternalIndex i : range) {
    // We don't deal with dictionary mode objects on the fast-path, so the index
    // is guaranteed to be less than uint16_t::max.
    static_assert(kMaxNumberOfDescriptors <
                  std::numeric_limits<uint16_t>::max());
    DCHECK_LE(i.as_uint32(), kMaxNumberOfDescriptors);
    const uint16_t descriptor_idx = static_cast<uint16_t>(i.as_uint32());
    Tagged<Name> name = descriptors->GetKey(i);
    int property_index;
    if constexpr (fast_iterable_state != FastIterableState::kJsonFast) {
      if (V8_UNLIKELY(IsSymbol(name))) {
        if constexpr (fast_iterable_state == FastIterableState::kUnknown) {
          descriptors->set_fast_iterable(FastIterableState::kJsonSlow);
        }
        continue;
      }
      PropertyDetails details = descriptors->GetDetails(i);
      if (V8_UNLIKELY(details.IsDontEnum())) {
        if constexpr (fast_iterable_state == FastIterableState::kUnknown) {
          descriptors->set_fast_iterable(FastIterableState::kJsonSlow);
        }
        continue;
      }
      if (V8_UNLIKELY(details.location() != PropertyLocation::kField)) {
        descriptors->set_fast_iterable(FastIterableState::kJsonSlow);
        return SLOW_PATH;
      }
      DCHECK_EQ(PropertyKind::kData, details.kind());
      property_index = details.field_index();
    } else {
      DCHECK_EQ(descriptor_idx, descriptors->GetDetails(i).field_index());
      property_index = descriptor_idx;
    }
    const bool is_inobject = property_index < in_object_properties;
    Tagged<JSAny> property;
    if (is_inobject) {
      int offset = (in_object_properties_start + property_index) * kTaggedSize;
      property = TaggedField<JSAny>::Relaxed_Load(cage_base, obj, offset);
    } else {
      property_index -= in_object_properties;
      property = obj->property_array(cage_base)->get(cage_base, property_index);
    }
    DCHECK(IsInternalizedString(name));
    Tagged<String> key_name = Cast<String>(name);
    if (V8_UNLIKELY(IsUndefined(property) || IsSymbol(property))) {
      if constexpr (fast_iterable_state == FastIterableState::kUnknown) {
        // Even if we don't serialize the key, check if it is fast iterable to
        // avoid false positives in DescriptorArray::fast_iterable.
        if (!IsFastKey(key_name, no_gc)) {
          descriptors->set_fast_iterable(FastIterableState::kJsonSlow);
        }
      }
      continue;
    }
    FastJsonStringifierObjectKeyResult key_result;
    if constexpr (fast_iterable_state == FastIterableState::kJsonFast) {
      V8_INLINE_STATEMENT key_result =
          SerializeObjectKey<true>(key_name, comma, no_gc);
      DCHECK_EQ(key_result, FastJsonStringifierObjectKeyResult::kSuccess);
    } else {
      key_result = SerializeObjectKey<false>(key_name, comma, no_gc);
      if (V8_UNLIKELY(key_result !=
                      FastJsonStringifierObjectKeyResult::kSuccess)) {
        descriptors->set_fast_iterable(FastIterableState::kJsonSlow);
        if constexpr (is_one_byte) {
          if (key_result ==
              FastJsonStringifierObjectKeyResult::kChangeEncoding) {
            stack_.emplace_back(
                ContinuationRecord::ForJSObjectResume<fast_iterable_state>(
                    obj, descriptor_idx + 1, nof_descriptors,
                    in_object_properties, in_object_properties_start,
                    descriptors));
            if (IsJSObject(property)) {
              stack_.emplace_back(ContinuationRecord::ForJSObject(property));
            } else if (IsJSArray(property)) {
              stack_.emplace_back(ContinuationRecord::ForJSArray(property));
            } else {
              stack_.emplace_back(
                  ContinuationRecord::ForSimpleObject(property));
            }
            stack_.emplace_back(
                ContinuationRecord::ForObjectKey(key_name, comma));
            return CHANGE_ENCODING;
          }
        } else {
          DCHECK_NE(key_result,
                    FastJsonStringifierObjectKeyResult::kChangeEncoding);
        }
      }
    }
    // TrySerializeSimpleObject won't trigger GCs. See DisableGCMole scopes in
    // SerializeJSPrimitiveWrapper for explanation.
    DisableGCMole no_gc_mole;
    FastJsonStringifierResult result;
    if constexpr (fast_iterable_state == FastIterableState::kJsonFast) {
      V8_INLINE_STATEMENT result = TrySerializeSimpleObject(property);
    } else {
      result = TrySerializeSimpleObject(property);
    }
    switch (result) {
      case SUCCESS:
        comma = true;
        break;
      case UNDEFINED:
        break;
      case JS_OBJECT:
      case JS_ARRAY:
        stack_.push_back(
            ContinuationRecord::ForJSObjectResume<fast_iterable_state>(
                obj, descriptor_idx + 1, nof_descriptors, in_object_properties,
                in_object_properties_start, descriptors));
        stack_.push_back(ContinuationRecord::ForJSAny(property, result));
        return result;
      case CHANGE_ENCODING:
        if constexpr (is_one_byte) {
          stack_.push_back(
              ContinuationRecord::ForJSObjectResume<fast_iterable_state>(
                  obj, descriptor_idx + 1, nof_descriptors,
                  in_object_properties, in_object_properties_start,
                  descriptors));
          stack_.push_back(ContinuationRecord::ForSimpleObject(property));
          return result;
        } else {
          UNREACHABLE();
        }
      case SLOW_PATH:
      case EXCEPTION:
        return result;
    }
  }
  AppendCharacter('}');
  if constexpr (fast_iterable_state == FastIterableState::kUnknown) {
    if (nof_descriptors == descriptors->number_of_descriptors()) {
      descriptors->set_fast_iterable_if(FastIterableState::kJsonFast,
                                        FastIterableState::kUnknown);
    }
  }
  return SUCCESS;
}
References v8::internal::CHANGE_ENCODING, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LE, DCHECK_NE, v8::internal::EXCEPTION, v8::internal::PropertyDetails::field_index(), v8::internal::ContinuationRecord::ForJSAny(), v8::internal::ContinuationRecord::ForJSArray(), v8::internal::ContinuationRecord::ForJSObject(), v8::internal::ContinuationRecord::ForObjectKey(), v8::internal::ContinuationRecord::ForSimpleObject(), v8::internal::GetPtrComprCageBase(), v8::internal::PropertyDetails::IsDontEnum(), v8::internal::anonymous_namespace{json-stringifier.cc}::IsFastKey(), v8::internal::InstanceTypeChecker::IsInternalizedString(), v8::internal::JS_ARRAY, v8::internal::JS_OBJECT, v8::internal::kChangeEncoding, v8::internal::kData, v8::internal::kField, v8::internal::PropertyDetails::kind(), v8::internal::kMaxNumberOfDescriptors, v8::internal::kSuccess, v8::internal::kTaggedSize, v8::internal::PropertyDetails::location(), v8::internal::name, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Relaxed_Load(), v8::base::internal::result, v8::internal::SLOW_PATH, v8::internal::SUCCESS, v8::internal::UNDEFINED, v8::internal::UNREACHABLE(), V8_INLINE_STATEMENT, and V8_UNLIKELY.
Separator()
template<typename Char >
void v8::internal::FastJsonStringifier< Char >::Separator (bool comma) [inline], [private]
Definition at line 2184 of file json-stringifier.cc.
                                       {
    if (comma) AppendCharacter(',');
  }
References v8::internal::FastJsonStringifier< Char >::AppendCharacter().
SeparatorUnchecked()
template<typename Char >
void v8::internal::FastJsonStringifier< Char >::SeparatorUnchecked (bool comma) [inline], [private]
Definition at line 2181 of file json-stringifier.cc.
                                                {
    if (comma) AppendCharacterUnchecked(',');
  }
References v8::internal::FastJsonStringifier< Char >::AppendCharacterUnchecked().
SerializeDouble()
template<typename Char >
void v8::internal::FastJsonStringifier< Char >::SerializeDouble (double number) [private]
Definition at line 2371 of file json-stringifier.cc.
                                                             {
  if (V8_UNLIKELY(std::isinf(number) || std::isnan(number))) {
    AppendCStringLiteral("null");
    return;
  }
  static constexpr uint32_t kBufferSize = 100;
  char chars[kBufferSize];
  base::Vector<char> buffer(chars, kBufferSize);
  std::string_view str = DoubleToStringView(number, buffer);
  AppendString(str);
}
References v8::internal::DoubleToStringView(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::kBufferSize, and V8_UNLIKELY.
SerializeFixedArray()
template<typename Char >
template<ElementsKind kind>
FastJsonStringifierResult v8::internal::FastJsonStringifier< Char >::SerializeFixedArray (Tagged< FixedArrayBase > array, uint32_t start_idx, uint32_t length) [inline], [private]
Definition at line 3007 of file json-stringifier.cc.
                                                                            {
  using ArrayT = std::conditional_t<IsDoubleElementsKind(kind),
                                    FixedDoubleArray, FixedArray>;
  for (uint32_t i = start_index; i < length; i++) {
    FastJsonStringifierResult result = SerializeFixedArrayElement<kind, false>(
        Cast<ArrayT>(elements), i, length);
    if (result != SUCCESS) return result;
  }
  AppendCharacter(']');
  return SUCCESS;
}
References v8::internal::IsDoubleElementsKind(), v8::internal::length, v8::base::internal::result, and v8::internal::SUCCESS.
SerializeFixedArrayElement()
template<typename Char >
template<ElementsKind kind, bool with_interrupt_checks, typename T >
FastJsonStringifierResult v8::internal::FastJsonStringifier< Char >::SerializeFixedArrayElement (Tagged< T > elements, uint32_t i, uint32_t length) [inline], [private]
Definition at line 3023 of file json-stringifier.cc.
                                                     {
  if constexpr (IsHoleyElementsKind(kind)) {
    if (elements->is_the_hole(isolate_, i)) {
      EnsureCapacity(5 /* "null" + optional comma */);
      SeparatorUnchecked(i > 0);
      AppendCStringLiteralUnchecked("null");
      return SUCCESS;
    }
  }
  DCHECK(!elements->is_the_hole(isolate_, i));
  Separator(i > 0);
  if constexpr (IsSmiElementsKind(kind)) {
    SerializeSmi(Cast<Smi>(elements->get(i)));
  } else if constexpr (IsDoubleElementsKind(kind)) {
    SerializeDouble(elements->get_scalar(i));
  } else {
    Tagged<JSAny> obj = Cast<JSAny>(elements->get(i));
    // TrySerializeSimpleObject won't trigger GCs. See DisableGCMole scopes in
    // SerializeJSPrimitiveWrapper for explanation.
    DisableGCMole no_gc_mole;
    FastJsonStringifierResult result;
    V8_INLINE_STATEMENT result = TrySerializeSimpleObject(obj);
    switch (result) {
      case UNDEFINED:
        AppendCStringLiteral("null");
        return SUCCESS;
      case CHANGE_ENCODING:
        if constexpr (is_one_byte) {
          DCHECK(IsString(obj) || IsStringWrapper(obj));
          stack_.push_back(
              ContinuationRecord::ForJSArrayResume<kind, with_interrupt_checks>(
                  elements, i + 1, length));
          stack_.push_back(ContinuationRecord::ForSimpleObject(obj));
          return result;
        } else {
          UNREACHABLE();
        }
      case JS_OBJECT:
      case JS_ARRAY:
        stack_.push_back(
            ContinuationRecord::ForJSArrayResume<kind, with_interrupt_checks>(
                elements, i + 1, length));
        stack_.push_back(ContinuationRecord::ForJSAny(obj, result));
        return result;
      case SUCCESS:
      case SLOW_PATH:
      case EXCEPTION:
        return result;
    }
    UNREACHABLE();
  }
  return SUCCESS;
}
References v8::internal::CHANGE_ENCODING, v8::internal::DCHECK(), v8::internal::EXCEPTION, v8::internal::ContinuationRecord::ForJSAny(), v8::internal::ContinuationRecord::ForSimpleObject(), v8::internal::IsDoubleElementsKind(), v8::internal::IsHoleyElementsKind(), v8::internal::IsSmiElementsKind(), v8::internal::JS_ARRAY, v8::internal::JS_OBJECT, v8::internal::length, v8::base::internal::result, v8::internal::SLOW_PATH, v8::internal::SUCCESS, v8::internal::UNDEFINED, v8::internal::UNREACHABLE(), and V8_INLINE_STATEMENT.
SerializeFixedArrayWithInterruptCheck()
template<typename Char >
template<ElementsKind kind>
FastJsonStringifierResult v8::internal::FastJsonStringifier< Char >::SerializeFixedArrayWithInterruptCheck (Tagged< FixedArrayBase > elements, uint32_t start_index, uint32_t length) [private]
Definition at line 2962 of file json-stringifier.cc.
                                                                            {
  using ArrayT = std::conditional_t<IsDoubleElementsKind(kind),
                                    FixedDoubleArray, FixedArray>;
  StackLimitCheck interrupt_check(isolate_);
  uint32_t limit = std::min(length, kArrayInterruptLength);
  constexpr uint32_t kMaxAllowedFastPackedLength =
      std::numeric_limits<uint32_t>::max() - kArrayInterruptLength;
  static_assert(FixedArray::kMaxLength < kMaxAllowedFastPackedLength);
  // GCMole doesn't handle kNoGC interrupts correctly.
  DisableGCMole no_gc_mole;
  uint32_t i = start_index;
  while (true) {
    for (; i < limit; i++) {
      FastJsonStringifierResult result = SerializeFixedArrayElement<kind, true>(
          Cast<ArrayT>(elements), i, length);
      if (result != SUCCESS) return result;
    }
    if (i >= length) {
      AppendCharacter(']');
      return SUCCESS;
    }
    DCHECK_LT(limit, kMaxAllowedFastPackedLength);
    limit = std::min(length, limit + kArrayInterruptLength);
    {
      // A TerminationException can actually trigger a GC when allocating the
      // message object. We don't touch any of the heap objects after we
      // encountered an exception, so this is fine.
      AllowGarbageCollection allow_gc;
      if (interrupt_check.InterruptRequested() &&
          IsException(isolate_->stack_guard()->HandleInterrupts(
                          StackGuard::InterruptLevel::kNoGC),
                      isolate_)) {
        return EXCEPTION;
      }
    }
  }
  UNREACHABLE();
}
References DCHECK_LT, v8::internal::EXCEPTION, v8::internal::StackLimitCheck::InterruptRequested(), v8::internal::IsDoubleElementsKind(), v8::internal::FixedArray::kMaxLength, v8::internal::StackGuard::kNoGC, v8::internal::length, v8::base::internal::result, v8::internal::SUCCESS, and v8::internal::UNREACHABLE().
SerializeJSArray()
template<typename Char >
FastJsonStringifierResult v8::internal::FastJsonStringifier< Char >::SerializeJSArray (Tagged< JSArray > array) [private]
Definition at line 2924 of file json-stringifier.cc.
                           {
  if (V8_UNLIKELY(!CanFastSerializeJSArrayFastPath(
          array, initial_jsarray_proto_, isolate_))) {
    return SLOW_PATH;
  }
  AppendCharacter('[');
  uint32_t length = static_cast<uint32_t>(Object::NumberValue(array->length()));
  Tagged<FixedArrayBase> elements = array->elements();
  switch (array->GetElementsKind()) {
#define CASE(kind) \
  case kind: \
    if constexpr (IsHoleyElementsKind(kind)) { \
      if (V8_UNLIKELY(!Protectors::IsNoElementsIntact(isolate_))) { \
        return SLOW_PATH; \
      } \
    } \
    if (V8_UNLIKELY(length > kArrayInterruptLength)) { \
      return SerializeFixedArrayWithInterruptCheck<kind>(elements, 0, length); \
    } else { \
      return SerializeFixedArray<kind>(elements, 0, length); \
    }
    CASE(PACKED_SMI_ELEMENTS)
    CASE(PACKED_ELEMENTS)
    CASE(PACKED_DOUBLE_ELEMENTS)
    CASE(HOLEY_SMI_ELEMENTS)
    CASE(HOLEY_ELEMENTS)
    CASE(HOLEY_DOUBLE_ELEMENTS)
#undef CASE
    default:
      return SLOW_PATH;
  }
  UNREACHABLE();
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::CanFastSerializeJSArrayFastPath(), CASE, v8::internal::HOLEY_DOUBLE_ELEMENTS, v8::internal::HOLEY_ELEMENTS, v8::internal::HOLEY_SMI_ELEMENTS, v8::internal::length, v8::internal::Object::NumberValue(), v8::internal::PACKED_DOUBLE_ELEMENTS, v8::internal::PACKED_ELEMENTS, v8::internal::PACKED_SMI_ELEMENTS, v8::internal::SLOW_PATH, v8::internal::UNREACHABLE(), and V8_UNLIKELY.
SerializeJSObject()
template<typename Char >
FastJsonStringifierResult v8::internal::FastJsonStringifier< Char >::SerializeJSObject (Tagged< JSObject > obj, const DisallowGarbageCollection & no_gc) [inline], [private]
Definition at line 2742 of file json-stringifier.cc.
                                                                  {
  Tagged<Map> map = obj->map();
  if (V8_UNLIKELY(!CanFastSerializeJSObjectFastPath(
          obj, initial_jsobject_proto_, map, isolate_))) {
    return SLOW_PATH;
  }
  AppendCharacter('{');
  const uint16_t nof_descriptors = map->NumberOfOwnDescriptors();
  const uint8_t in_object_properties = map->GetInObjectProperties();
  const uint8_t in_object_properties_start =
      map->GetInObjectPropertiesStartInWords();
  const Tagged<DescriptorArray> descriptors = map->instance_descriptors();
  FastIterableState fast_iterable_state = descriptors->fast_iterable();
  switch (fast_iterable_state) {
#define CASE(state) \
  case FastIterableState::state: \
    return ResumeJSObject<FastIterableState::state>(\
        obj, 0, nof_descriptors, in_object_properties, \
        in_object_properties_start, descriptors, false, no_gc)
    CASE(kUnknown);
    CASE(kJsonFast);
    CASE(kJsonSlow);
#undef CASE
  }
  UNREACHABLE();
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::CanFastSerializeJSObjectFastPath(), CASE, v8::internal::kUnknown, v8::internal::SLOW_PATH, v8::internal::UNREACHABLE(), and V8_UNLIKELY.
SerializeJSPrimitiveWrapper()
template<typename Char >
FastJsonStringifierResult v8::internal::FastJsonStringifier< Char >::SerializeJSPrimitiveWrapper (Tagged< JSPrimitiveWrapper > obj, const DisallowGarbageCollection & no_gc) [private]
Definition at line 2644 of file json-stringifier.cc.
                                                                            {
  // TODO(pthier): Consider extending IsStringWrapperToPrimitive to also cover
  // toString() and all JSPrimitiveWrappers to avoid some of the checks here.
  if (V8_UNLIKELY(MayHaveInterestingProperties(isolate_, obj))) {
    return SLOW_PATH;
  }
  Tagged<JSAny> raw = obj->value();
  if (IsSymbol(raw)) {
    // Symbol object wrapper is treated as a regular object.
    Tagged<Map> map = obj->map();
    // Check that object has no own properties.
    if (V8_UNLIKELY(!obj->HasFastProperties())) return SLOW_PATH;
    if (V8_UNLIKELY(map->NumberOfOwnDescriptors() != 0)) return SLOW_PATH;
    // Check that object has no elements.
    auto roots = ReadOnlyRoots(isolate_);
    auto elements = obj->elements();
    if (V8_UNLIKELY(elements != roots.empty_fixed_array() &&
                    elements != roots.empty_slow_element_dictionary())) {
      return SLOW_PATH;
    }
    AppendCStringLiteral("{}");
    return SUCCESS;
  } else if (IsString(raw)) {
    if (V8_UNLIKELY(!Protectors::IsStringWrapperToPrimitiveIntact(isolate_))) {
      return SLOW_PATH;
    }
    // We only fetch data properties in GetBuiltin, but GCMole doesn't know
    // that and assumes GCs can happen.
    DisableGCMole no_gc_mole;
    // Check that toString() on the prototype chain is the expected builtin.
    if (V8_UNLIKELY(
            GetBuiltin(isolate_, obj, isolate_->factory()->toString_string()) !=
            Builtin::kStringPrototypeToString)) {
      return SLOW_PATH;
    }
    Tagged<String> string = Cast<String>(raw);
    while (true) {
      FastJsonStringifierResult result =
          string->DispatchToSpecificType(absl::Overload{
              [&](Tagged<SeqOneByteString> str) {
                return SerializeString<SeqOneByteString>(str, no_gc);
              },
              [&](Tagged<SeqTwoByteString> str) {
                return SerializeString<SeqTwoByteString>(str, no_gc);
              },
              [&](Tagged<ExternalOneByteString> str) {
                return SerializeString<ExternalOneByteString>(str, no_gc);
              },
              [&](Tagged<ExternalTwoByteString> str) {
                return SerializeString<ExternalTwoByteString>(str, no_gc);
              },
              [&](Tagged<ThinString> str) {
                string = str->actual();
                // UNDEFINED is misused here to indicate that we continue after
                // unwrapping.
                return UNDEFINED;
              },
              [&](Tagged<ConsString> str) { return SLOW_PATH; },
              [&](Tagged<SlicedString> str) { return SLOW_PATH; }});
      if (V8_LIKELY(result != UNDEFINED)) return result;
    }
    UNREACHABLE();
  } else if (IsNumber(raw)) {
    // We only fetch data properties in GetBuiltin, but GCMole doesn't know
    // that and assumes GCs can happen.
    DisableGCMole no_gc_mole;
    // Check that valueOf() on the prototype chain is the expected builtin.
    if (V8_UNLIKELY(
            GetBuiltin(isolate_, obj, isolate_->factory()->valueOf_string()) !=
            Builtin::kNumberPrototypeValueOf)) {
      return SLOW_PATH;
    }
    if (IsSmi(raw)) {
      SerializeSmi(Cast<Smi>(raw));
      return SUCCESS;
    }
    DCHECK(IsHeapNumber(raw));
    SerializeDouble(Cast<HeapNumber>(raw)->value());
    return SUCCESS;
  } else if (IsBoolean(raw)) {
    if (IsTrue(raw, isolate_)) {
      AppendCStringLiteral("true");
    } else {
      AppendCStringLiteral("false");
    }
    return SUCCESS;
  } else if (IsBigInt(raw)) {
    return SLOW_PATH;
  }
  UNREACHABLE();
}
References v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::GetBuiltin(), v8::internal::IsNumber(), v8::internal::IsSmi(), v8::internal::MayHaveInterestingProperties(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, v8::internal::SLOW_PATH, v8::internal::SUCCESS, v8::internal::UNDEFINED, v8::internal::UNREACHABLE(), V8_LIKELY, V8_UNLIKELY, and v8::internal::value.
SerializeObject() [1/2]
template<typename Char >
FastJsonStringifierResult v8::internal::FastJsonStringifier< Char >::SerializeObject (ContinuationRecord cont, const DisallowGarbageCollection & no_gc) [private]
Definition at line 3183 of file json-stringifier.cc.
                                                                     {
  // GCMole doesn't handle kNoGC interrupts correctly.
  DisableGCMole no_gc_mole;
  uint32_t interrupt_budget = kGlobalInterruptBudget;
  FastJsonStringifierResult result;
  while (true) {
    --interrupt_budget;
    if (V8_UNLIKELY(interrupt_budget == 0)) {
      result = HandleInterruptAndCheckCycle();
      if (V8_UNLIKELY(result != SUCCESS)) return result;
      interrupt_budget = kGlobalInterruptBudget;
    }
    switch (cont.type()) {
      case ContinuationRecord::kObject: {
        result = SerializeJSObject(cont.js_object(), no_gc);
        break;
      }
      case ContinuationRecord::kObjectResume_Uninitialized: {
        result = ResumeJSObject<FastIterableState::kUnknown>(
            cont.js_object(), cont.object_descriptor_idx(),
            cont.object_nof_descriptors(), cont.object_in_object_properties(),
            cont.object_in_object_properties_start(), cont.object_descriptors(),
            true, no_gc);
        break;
      }
      case ContinuationRecord::kObjectResume_FastIterable: {
        result = ResumeJSObject<FastIterableState::kJsonFast>(
            cont.js_object(), cont.object_descriptor_idx(),
            cont.object_nof_descriptors(), cont.object_in_object_properties(),
            cont.object_in_object_properties_start(), cont.object_descriptors(),
            true, no_gc);
        break;
      }
      case ContinuationRecord::kObjectResume_SlowIterable: {
        result = ResumeJSObject<FastIterableState::kJsonSlow>(
            cont.js_object(), cont.object_descriptor_idx(),
            cont.object_nof_descriptors(), cont.object_in_object_properties(),
            cont.object_in_object_properties_start(), cont.object_descriptors(),
            true, no_gc);
        break;
      }
      case ContinuationRecord::kArray: {
        result = SerializeJSArray(cont.js_array());
        break;
      }
      case ContinuationRecord::kArrayResume: {
        result = SerializeFixedArray<PACKED_ELEMENTS>(
            cont.array_elements(), cont.array_index(), cont.array_length());
        break;
      }
      case ContinuationRecord::kArrayResume_Holey: {
        result = SerializeFixedArray<HOLEY_ELEMENTS>(
            cont.array_elements(), cont.array_index(), cont.array_length());
        break;
      }
      case ContinuationRecord::kArrayResume_WithInterrupts: {
        result = SerializeFixedArrayWithInterruptCheck<PACKED_ELEMENTS>(
            cont.array_elements(), cont.array_index(), cont.array_length());
        break;
      }
      case ContinuationRecord::kArrayResume_Holey_WithInterrupts: {
        result = SerializeFixedArrayWithInterruptCheck<HOLEY_ELEMENTS>(
            cont.array_elements(), cont.array_index(), cont.array_length());
        break;
      }
      default:
        UNREACHABLE();
    }
    static_assert(SUCCESS == 0);
    static_assert(JS_OBJECT == 1);
    static_assert(JS_ARRAY == 2);
    if (V8_UNLIKELY(result > JS_ARRAY)) return result;
    if (stack_.empty()) return SUCCESS;
    cont = stack_.back();
    stack_.pop_back();
  }
}
References v8::internal::ContinuationRecord::array_elements(), v8::internal::ContinuationRecord::array_index(), v8::internal::ContinuationRecord::array_length(), v8::internal::JS_ARRAY, v8::internal::ContinuationRecord::js_array(), v8::internal::JS_OBJECT, v8::internal::ContinuationRecord::js_object(), v8::internal::ContinuationRecord::kArray, v8::internal::ContinuationRecord::kArrayResume, v8::internal::ContinuationRecord::kArrayResume_Holey, v8::internal::ContinuationRecord::kArrayResume_Holey_WithInterrupts, v8::internal::ContinuationRecord::kArrayResume_WithInterrupts, v8::internal::ContinuationRecord::kObject, v8::internal::ContinuationRecord::kObjectResume_FastIterable, v8::internal::ContinuationRecord::kObjectResume_SlowIterable, v8::internal::ContinuationRecord::kObjectResume_Uninitialized, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::ContinuationRecord::object_descriptor_idx(), v8::internal::ContinuationRecord::object_descriptors(), v8::internal::ContinuationRecord::object_in_object_properties(), v8::internal::ContinuationRecord::object_in_object_properties_start(), v8::internal::ContinuationRecord::object_nof_descriptors(), v8::base::internal::result, v8::internal::SUCCESS, v8::internal::ContinuationRecord::type(), v8::internal::UNREACHABLE(), and V8_UNLIKELY.
SerializeObject() [2/2]
template<typename Char >
FastJsonStringifierResult v8::internal::FastJsonStringifier< Char >::SerializeObject (Tagged< JSAny > object, const DisallowGarbageCollection & no_gc) [inline]
Definition at line 3131 of file json-stringifier.cc.
                                                                  {
  // Initial checks if using the fast-path is possible in general.
  if (!object.IsSmi() && (IsJSObject(object) || IsJSArray(object))) {
    Tagged<HeapObject> obj = Cast<HeapObject>(object);
    // Load initial JSObject/JSArray prototypes from native context.
    Tagged<Map> meta_map = obj->map()->map();
    // Don't deal with context-less meta maps.
    if (V8_UNLIKELY(meta_map == ReadOnlyRoots(isolate_).meta_map())) {
      return SLOW_PATH;
    }
    Tagged<NativeContext> native_context = meta_map->native_context();
    initial_jsobject_proto_ = native_context->initial_object_prototype();
    initial_jsarray_proto_ = native_context->initial_array_prototype();
    // Prototypes don't have interesting properties (toJSON).
    if (V8_UNLIKELY(
            initial_jsarray_proto_->map()->may_have_interesting_properties())) {
      return SLOW_PATH;
    }
    if (V8_UNLIKELY(initial_jsobject_proto_->map()
                        ->may_have_interesting_properties())) {
      return SLOW_PATH;
    }
    // JSArray's prototype is the initial object prototype.
    Tagged<HeapObject> jsarray_proto_proto =
        initial_jsarray_proto_->map()->prototype();
    if (V8_UNLIKELY(jsarray_proto_proto != initial_jsobject_proto_)) {
      return SLOW_PATH;
    }
  }
  // TrySerializeSimpleObject won't trigger GCs. See DisableGCMole scopes in
  // SerializeJSPrimitiveWrapper for explanation.
  DisableGCMole no_gc_mole;
  // Serialize object.
  FastJsonStringifierResult result = TrySerializeSimpleObject(object);
  if constexpr (is_one_byte) {
    if (V8_UNLIKELY(result == CHANGE_ENCODING)) {
      DCHECK(IsString(object) || IsStringWrapper(object));
      stack_.push_back(ContinuationRecord::ForSimpleObject(object));
      return result;
    }
  } else {
    DCHECK_NE(result, CHANGE_ENCODING);
  }
  if (result != JS_OBJECT && result != JS_ARRAY) {
    return result;
  }
  return SerializeObject(ContinuationRecord::ForJSAny(object, result), no_gc);
}
References v8::internal::CHANGE_ENCODING, v8::internal::DCHECK(), DCHECK_NE, v8::internal::ContinuationRecord::ForJSAny(), v8::internal::ContinuationRecord::ForSimpleObject(), v8::internal::IsSmi(), v8::internal::JS_ARRAY, v8::internal::JS_OBJECT, v8::internal::native_context, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::SerializeObject(), v8::internal::SLOW_PATH, and V8_UNLIKELY.
Referenced by v8::internal::anonymous_namespace{json-stringifier.cc}::FastJsonStringify().
SerializeObjectKey() [1/2]
template<typename Char >
template<bool no_escaping>
FastJsonStringifierObjectKeyResult v8::internal::FastJsonStringifier< Char >::SerializeObjectKey (Tagged< String > key, bool comma, const DisallowGarbageCollection & no_gc) [private]
Definition at line 2386 of file json-stringifier.cc.
                                                                            {
#if V8_STATIC_ROOTS_BOOL
  // This is slightly faster than the switch over instance types.
  ReadOnlyRoots roots(isolate_);
  Tagged<Map> map = key->map();
  if (map == roots.internalized_one_byte_string_map()) {
    V8_INLINE_STATEMENT return SerializeObjectKey<SeqOneByteString,
                                                  no_escaping>(key, comma,
                                                               no_gc);
  } else if (map == roots.external_internalized_one_byte_string_map() ||
             map ==
                 roots.uncached_external_internalized_one_byte_string_map()) {
    V8_INLINE_STATEMENT return SerializeObjectKey<ExternalOneByteString,
                                                  no_escaping>(key, comma,
                                                               no_gc);
  } else {
    if constexpr (is_one_byte) {
      DCHECK(InstanceTypeChecker::IsTwoByteString(map));
      // no_escaping implies that all keys are one-byte.
      if constexpr (no_escaping) {
        UNREACHABLE();
      } else {
        return FastJsonStringifierObjectKeyResult::kChangeEncoding;
      }
    } else {
      if (map == roots.internalized_two_byte_string_map()) {
        return SerializeObjectKey<SeqTwoByteString, no_escaping>(key, comma,
                                                                 no_gc);
      } else if (
          map == roots.external_internalized_two_byte_string_map() ||
          map == roots.uncached_external_internalized_two_byte_string_map()) {
        return SerializeObjectKey<ExternalTwoByteString, no_escaping>(
            key, comma, no_gc);
      }
    }
  }
#else
  InstanceType instance_type = key->map()->instance_type();
  switch (instance_type) {
    case INTERNALIZED_ONE_BYTE_STRING_TYPE:
      V8_INLINE_STATEMENT return SerializeObjectKey<SeqOneByteString,
                                                    no_escaping>(key, comma,
                                                                 no_gc);
    case EXTERNAL_INTERNALIZED_ONE_BYTE_STRING_TYPE:
    case UNCACHED_EXTERNAL_INTERNALIZED_ONE_BYTE_STRING_TYPE:
      V8_INLINE_STATEMENT return SerializeObjectKey<ExternalOneByteString,
                                                    no_escaping>(key, comma,
                                                                 no_gc);
    case INTERNALIZED_TWO_BYTE_STRING_TYPE:
      return SerializeObjectKey<SeqTwoByteString, no_escaping>(key, comma,
                                                               no_gc);
    case EXTERNAL_INTERNALIZED_TWO_BYTE_STRING_TYPE:
    case UNCACHED_EXTERNAL_INTERNALIZED_TWO_BYTE_STRING_TYPE:
      return SerializeObjectKey<ExternalTwoByteString, no_escaping>(key, comma,
                                                                    no_gc);
    default:
      UNREACHABLE();
  }
#endif
  UNREACHABLE();
}
References v8::internal::DCHECK(), v8::internal::EXTERNAL_INTERNALIZED_ONE_BYTE_STRING_TYPE, v8::internal::EXTERNAL_INTERNALIZED_TWO_BYTE_STRING_TYPE, v8::internal::INTERNALIZED_ONE_BYTE_STRING_TYPE, v8::internal::INTERNALIZED_TWO_BYTE_STRING_TYPE, v8::internal::InstanceTypeChecker::IsTwoByteString(), v8::internal::kChangeEncoding, v8::internal::key, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::UNCACHED_EXTERNAL_INTERNALIZED_ONE_BYTE_STRING_TYPE, v8::internal::UNCACHED_EXTERNAL_INTERNALIZED_TWO_BYTE_STRING_TYPE, v8::internal::UNREACHABLE(), and V8_INLINE_STATEMENT.
SerializeObjectKey() [2/2]
template<typename Char >
template<typename StringT , bool no_escaping>
FastJsonStringifierObjectKeyResult v8::internal::FastJsonStringifier< Char >::SerializeObjectKey (Tagged< String > key, bool comma, const DisallowGarbageCollection & no_gc) [private]
Definition at line 2460 of file json-stringifier.cc.
                                                                            {
  using StringChar = StringT::Char;
  if constexpr (is_one_byte && sizeof(StringChar) == 2) {
    // no_escaping is only possible if we have already seen all the keys in a
    // map. But it is not possible we have seen a two-byte string and are still
    // in one-byte mode.
    if constexpr (no_escaping) {
      UNREACHABLE();
    } else {
      return FastJsonStringifierObjectKeyResult::kChangeEncoding;
    }
  } else {
    Tagged<StringT> string = Cast<StringT>(obj);
    const StringChar* chars;
    if constexpr (requires { string->GetChars(no_gc); }) {
      chars = string->GetChars(no_gc);
    } else {
      chars = string->GetChars();
    }
    const uint32_t length = string->length();
    size_t max_length;
    if constexpr (no_escaping) {
      max_length = length;
    } else {
      max_length = MaxEscapedStringLength(length);
    }
    max_length += 4 /* optional comma + 2x double quote + colon */;
    EnsureCapacity(max_length);
    SeparatorUnchecked(comma);
    AppendCharacterUnchecked('"');
    FastJsonStringifierObjectKeyResult result;
    if constexpr (no_escaping) {
      DCHECK(IsFastKey(obj, no_gc));
      SLOW_DCHECK(String::DoesNotContainEscapeCharacters(obj));
      AppendStringNoEscapes(chars, length, no_gc);
      result = FastJsonStringifierObjectKeyResult::kSuccess;
    } else {
      bool needs_escaping = AppendString(chars, length, no_gc);
      DCHECK_IMPLIES(needs_escaping, !IsFastKey(obj, no_gc));
      SLOW_DCHECK(needs_escaping !=
                  String::DoesNotContainEscapeCharacters(obj));
      result = sizeof(StringChar) == 1 && !needs_escaping
                   ? FastJsonStringifierObjectKeyResult::kSuccess
                   : FastJsonStringifierObjectKeyResult::kSlow;
    }
    AppendCharacterUnchecked('"');
    AppendCharacterUnchecked(':');
    return result;
  }
}
References v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::String::DoesNotContainEscapeCharacters(), v8::internal::anonymous_namespace{json-stringifier.cc}::IsFastKey(), v8::internal::kChangeEncoding, v8::internal::kSlow, v8::internal::kSuccess, v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::MaxEscapedStringLength(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::requires(), v8::base::internal::result, SLOW_DCHECK, and v8::internal::UNREACHABLE().
SerializeSmi()
template<typename Char >
void v8::internal::FastJsonStringifier< Char >::SerializeSmi (Tagged< Smi > object) [inline], [private]
Definition at line 2359 of file json-stringifier.cc.
                                                               {
  static_assert(Smi::kMaxValue <= 2147483647);
  static_assert(Smi::kMinValue >= -2147483648);
  // sizeof(string) includes \0.
  static constexpr uint32_t kBufferSize = sizeof("-2147483648") - 1;
  char chars[kBufferSize];
  base::Vector<char> buffer(chars, kBufferSize);
  std::string_view str = IntToStringView(object.value(), buffer);
  AppendString(str);
}
References v8::internal::IntToStringView(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::kBufferSize, v8::internal::Smi::kMaxValue, v8::internal::Smi::kMinValue, and v8::internal::value.
SerializeString()
template<typename Char >
template<typename StringT >
FastJsonStringifierResult v8::internal::FastJsonStringifier< Char >::SerializeString (Tagged< HeapObject > str, const DisallowGarbageCollection & no_gc) [inline], [private]
Definition at line 2514 of file json-stringifier.cc.
                                                                    {
  using StringChar = StringT::Char;
  if constexpr (is_one_byte && sizeof(StringChar) == 2) {
    return CHANGE_ENCODING;
  } else {
    Tagged<StringT> string = Cast<StringT>(obj);
    const StringChar* chars;
    if constexpr (requires { string->GetChars(no_gc); }) {
      chars = string->GetChars(no_gc);
    } else {
      chars = string->GetChars();
    }
    const uint32_t length = string->length();
    EnsureCapacity(MaxEscapedStringLength(length) + 2 /* 2x double quote */);
    AppendCharacterUnchecked('"');
    AppendString(chars, length, no_gc);
    AppendCharacterUnchecked('"');
    return SUCCESS;
  }
}
References v8::internal::CHANGE_ENCODING, v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::MaxEscapedStringLength(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::requires(), and v8::internal::SUCCESS.
TrySerializeSimpleObject()
template<typename Char >
FastJsonStringifierResult v8::internal::FastJsonStringifier< Char >::TrySerializeSimpleObject (Tagged< JSAny > object) [private]
Definition at line 2537 of file json-stringifier.cc.
                          {
  DisallowGarbageCollection no_gc;
  // GCMole doesn't handle kNoGC interrupts correctly.
  DisableGCMole no_gc_mole;
  if (IsSmi(object)) {
    SerializeSmi(Cast<Smi>(object));
    return SUCCESS;
  }
  Tagged<HeapObject> obj = Cast<HeapObject>(object);
  Tagged<Map> map = obj->map();
  InstanceType instance_type = map->instance_type();
  switch (instance_type) {
    case INTERNALIZED_ONE_BYTE_STRING_TYPE:
    case SEQ_ONE_BYTE_STRING_TYPE:
      return SerializeString<SeqOneByteString>(obj, no_gc);
    case EXTERNAL_INTERNALIZED_ONE_BYTE_STRING_TYPE:
    case UNCACHED_EXTERNAL_INTERNALIZED_ONE_BYTE_STRING_TYPE:
    case EXTERNAL_ONE_BYTE_STRING_TYPE:
    case UNCACHED_EXTERNAL_ONE_BYTE_STRING_TYPE:
      return SerializeString<ExternalOneByteString>(obj, no_gc);
    case THIN_ONE_BYTE_STRING_TYPE: {
      Tagged<String> actual = Cast<ThinString>(obj)->actual();
      if (IsExternalString(actual)) {
        return SerializeString<ExternalOneByteString>(actual, no_gc);
      } else {
        return SerializeString<SeqOneByteString>(actual, no_gc);
      }
    }
    case INTERNALIZED_TWO_BYTE_STRING_TYPE:
    case SEQ_TWO_BYTE_STRING_TYPE:
      return SerializeString<SeqTwoByteString>(obj, no_gc);
    case EXTERNAL_INTERNALIZED_TWO_BYTE_STRING_TYPE:
    case UNCACHED_EXTERNAL_INTERNALIZED_TWO_BYTE_STRING_TYPE:
    case EXTERNAL_TWO_BYTE_STRING_TYPE:
    case UNCACHED_EXTERNAL_TWO_BYTE_STRING_TYPE:
      return SerializeString<ExternalTwoByteString>(obj, no_gc);
    case THIN_TWO_BYTE_STRING_TYPE: {
      if constexpr (is_one_byte) {
        return CHANGE_ENCODING;
      } else {
        Tagged<String> actual = Cast<ThinString>(obj)->actual();
        if (IsExternalString(actual)) {
          return SerializeString<ExternalTwoByteString>(actual, no_gc);
        } else {
          return SerializeString<SeqTwoByteString>(actual, no_gc);
        }
      }
    }
    case HEAP_NUMBER_TYPE:
      SerializeDouble(Cast<HeapNumber>(obj)->value());
      return SUCCESS;
    case ODDBALL_TYPE:
      switch (Cast<Oddball>(obj)->kind()) {
        case Oddball::kFalse:
          AppendCStringLiteral("false");
          return SUCCESS;
        case Oddball::kTrue:
          AppendCStringLiteral("true");
          return SUCCESS;
        case Oddball::kNull:
          AppendCStringLiteral("null");
          return SUCCESS;
        default:
          return UNDEFINED;
      }
    case SYMBOL_TYPE:
      return UNDEFINED;
    case JS_PRIMITIVE_WRAPPER_TYPE:
      return SerializeJSPrimitiveWrapper(Cast<JSPrimitiveWrapper>(obj), no_gc);
    case JS_OBJECT_TYPE:
      return JS_OBJECT;
    case JS_ARRAY_TYPE:
      return JS_ARRAY;
    default:
      return SLOW_PATH;
  }
  UNREACHABLE();
}
References v8::internal::CHANGE_ENCODING, v8::internal::EXTERNAL_INTERNALIZED_ONE_BYTE_STRING_TYPE, v8::internal::EXTERNAL_INTERNALIZED_TWO_BYTE_STRING_TYPE, v8::internal::EXTERNAL_ONE_BYTE_STRING_TYPE, v8::internal::EXTERNAL_TWO_BYTE_STRING_TYPE, v8::internal::INTERNALIZED_ONE_BYTE_STRING_TYPE, v8::internal::INTERNALIZED_TWO_BYTE_STRING_TYPE, v8::internal::InstanceTypeChecker::IsExternalString(), v8::internal::IsSmi(), v8::internal::JS_ARRAY, v8::internal::JS_OBJECT, v8::internal::Oddball::kFalse, v8::internal::Oddball::kNull, v8::internal::Oddball::kTrue, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::SEQ_ONE_BYTE_STRING_TYPE, v8::internal::SEQ_TWO_BYTE_STRING_TYPE, v8::internal::SLOW_PATH, v8::internal::SUCCESS, v8::internal::THIN_ONE_BYTE_STRING_TYPE, v8::internal::THIN_TWO_BYTE_STRING_TYPE, v8::internal::UNCACHED_EXTERNAL_INTERNALIZED_ONE_BYTE_STRING_TYPE, v8::internal::UNCACHED_EXTERNAL_INTERNALIZED_TWO_BYTE_STRING_TYPE, v8::internal::UNCACHED_EXTERNAL_ONE_BYTE_STRING_TYPE, v8::internal::UNCACHED_EXTERNAL_TWO_BYTE_STRING_TYPE, v8::internal::UNDEFINED, v8::internal::UNREACHABLE(), and v8::internal::value.
Friends And Related Function Documentation
FastJsonStringifier
template<typename Char >
template<typename >
friend class FastJsonStringifier [friend]
Definition at line 2316 of file json-stringifier.cc.
Member Data Documentation
buffer_
template<typename Char >
OutBuffer<Char> v8::internal::FastJsonStringifier< Char >::buffer_ [private]
Definition at line 2310 of file json-stringifier.cc.
Referenced by v8::internal::FastJsonStringifier< Char >::AppendCharacterUnchecked(), v8::internal::FastJsonStringifier< Char >::AppendCStringLiteralUnchecked(), v8::internal::FastJsonStringifier< Char >::AppendCStringUnchecked(), v8::internal::FastJsonStringifier< Char >::CopyResultTo(), v8::internal::FastJsonStringifier< Char >::EnsureCapacity(), and v8::internal::FastJsonStringifier< Char >::ResultLength().
initial_jsarray_proto_
template<typename Char >
Tagged<HeapObject> v8::internal::FastJsonStringifier< Char >::initial_jsarray_proto_ [private]
Definition at line 2314 of file json-stringifier.cc.
Referenced by v8::internal::requires().
initial_jsobject_proto_
template<typename Char >
Tagged<HeapObject> v8::internal::FastJsonStringifier< Char >::initial_jsobject_proto_ [private]
Definition at line 2313 of file json-stringifier.cc.
Referenced by v8::internal::requires().
is_one_byte
template<typename Char >
constexpr bool v8::internal::FastJsonStringifier< Char >::is_one_byte = sizeof(Char) == sizeof(uint8_t) [static], [constexpr], [private]
Definition at line 2179 of file json-stringifier.cc.
isolate_
template<typename Char >
Isolate* v8::internal::FastJsonStringifier< Char >::isolate_ [private]
Definition at line 2309 of file json-stringifier.cc.
kArrayInterruptLength
template<typename Char >
constexpr uint32_t v8::internal::FastJsonStringifier< Char >::kArrayInterruptLength = 4000 [static], [constexpr], [private]
Definition at line 2307 of file json-stringifier.cc.
kGlobalInterruptBudget
template<typename Char >
constexpr uint32_t v8::internal::FastJsonStringifier< Char >::kGlobalInterruptBudget = 200000 [static], [constexpr], [private]
Definition at line 2306 of file json-stringifier.cc.
length
template<typename Char >
size_t v8::internal::FastJsonStringifier< Char >::length [private]
Definition at line 2276 of file json-stringifier.cc.
Referenced by v8::internal::FastJsonStringifier< Char >::AppendCStringLiteral(), and v8::internal::FastJsonStringifier< Char >::AppendCStringLiteralUnchecked().
no_gc [1/3]
template<typename Char >
size_t const DisallowGarbageCollection & v8::internal::FastJsonStringifier< Char >::no_gc
Definition at line 2176 of file json-stringifier.cc.
no_gc [2/3]
template<typename Char >
size_t const DisallowGarbageCollection& v8::internal::FastJsonStringifier< Char >::no_gc [private]
Definition at line 2277 of file json-stringifier.cc.
no_gc [3/3]
template<typename Char >
size_t size_t size_t const DisallowGarbageCollection& v8::internal::FastJsonStringifier< Char >::no_gc [private]
Definition at line 2287 of file json-stringifier.cc.
stack_
template<typename Char >
base::SmallVector<ContinuationRecord, 16> v8::internal::FastJsonStringifier< Char >::stack_ [private]
Definition at line 2311 of file json-stringifier.cc.
Referenced by v8::internal::requires().
start
template<typename Char >
size_t size_t v8::internal::FastJsonStringifier< Char >::start [private]
Definition at line 2285 of file json-stringifier.cc.
uncopied_src_index
template<typename Char >
size_t size_t size_t v8::internal::FastJsonStringifier< Char >::uncopied_src_index [private]
Definition at line 2286 of file json-stringifier.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/json/json-stringifier.cc