v8::internal::StatsCounter Class Reference
#include <counters.h>
Public Member Functions
const char * name () const
void Set (int value)
int Get ()
void Increment (int value=1)
void Decrement (int value=1)
V8_EXPORT_PRIVATE bool Enabled ()
std::atomic< int > * GetInternalPointer ()
Private Member Functions
void Initialize (const char *name, Counters *counters)
V8_NOINLINE V8_EXPORT_PRIVATE std::atomic< int > * SetupPtrFromStatsTable ()
void Reset ()
std::atomic< int > * GetPtr ()
Private Attributes
Counters * counters_ = nullptr
const char * name_ = nullptr
std::atomic< std::atomic< int > * > ptr_ {nullptr}
Friends
class Counters
class CountersInitializer
class StatsCounterResetter
Detailed Description
Definition at line 100 of file counters.h.
Member Function Documentation
Decrement()
void v8::internal::StatsCounter::Decrement (int value = 1) [inline]
Definition at line 111 of file counters.h.
                                {
    GetPtr()->fetch_sub(value, std::memory_order_relaxed);
  }
References GetPtr(), and v8::internal::value.
Enabled()
bool v8::internal::StatsCounter::Enabled ()
Definition at line 32 of file counters.cc.
{ return GetPtr() != &unused_counter_dump; }
References GetPtr(), and v8::internal::anonymous_namespace{counters.cc}::unused_counter_dump.
Referenced by v8::internal::AddCounter(), v8::internal::CodeStubAssembler::DecrementCounter(), v8::internal::MacroAssembler::EmitDecrementCounter(), v8::internal::MacroAssembler::EmitIncrementCounter(), v8::internal::ExternalReferenceTable::GetStatsCounterAddress(), v8::internal::CodeStubAssembler::IncrementCounter(), and v8::internal::CodeStubAssembler::SetCounter().
Get()
int v8::internal::StatsCounter::Get () [inline]
Definition at line 105 of file counters.h.
{ return GetPtr()->load(); }
References GetPtr().
GetInternalPointer()
std::atomic<int>* v8::internal::StatsCounter::GetInternalPointer () [inline]
Definition at line 122 of file counters.h.
{ return GetPtr(); }
References GetPtr().
Referenced by v8::internal::AddCounter(), v8::internal::ExternalReference::Create(), and v8::internal::ExternalReferenceTable::GetStatsCounterAddress().
GetPtr()
std::atomic<int>* v8::internal::StatsCounter::GetPtr () [inline], [private]
Definition at line 144 of file counters.h.
                           {
    auto* ptr = ptr_.load(std::memory_order_acquire);
    if (V8_LIKELY(ptr)) return ptr;
    return SetupPtrFromStatsTable();
  }
References ptr_, SetupPtrFromStatsTable(), and V8_LIKELY.
Referenced by Decrement(), Enabled(), Get(), GetInternalPointer(), Increment(), and Set().
Increment()
void v8::internal::StatsCounter::Increment (int value = 1) [inline]
Definition at line 107 of file counters.h.
                                {
    GetPtr()->fetch_add(value, std::memory_order_relaxed);
  }
References GetPtr(), and v8::internal::value.
Initialize()
void v8::internal::StatsCounter::Initialize (const char * name, Counters * counters) [inline], [private]
Definition at line 129 of file counters.h.
                                                        {
    DCHECK_NULL(counters_);
    DCHECK_NOT_NULL(counters);
    // Counter names always start with "c:V8.".
    DCHECK_EQ(0, memcmp(name, "c:V8.", 5));
    counters_ = counters;
    name_ = name;
  }
References counters_, DCHECK_EQ, DCHECK_NOT_NULL, DCHECK_NULL, name(), and name_.
Referenced by v8::internal::CountersInitializer::Visit().
name()
const char* v8::internal::StatsCounter::name () const [inline]
Definition at line 102 of file counters.h.
{ return name_; }
References name_.
Referenced by Initialize().
Reset()
void v8::internal::StatsCounter::Reset () [inline], [private]
Definition at line 141 of file counters.h.
{ ptr_.store(nullptr, std::memory_order_relaxed); }
References ptr_.
Referenced by v8::internal::StatsCounterResetter::VisitStatsCounter().
Set()
void v8::internal::StatsCounter::Set (int value) [inline]
Definition at line 104 of file counters.h.
{ GetPtr()->store(value, std::memory_order_relaxed); }
References GetPtr(), and v8::internal::value.
SetupPtrFromStatsTable()
std::atomic< int > * v8::internal::StatsCounter::SetupPtrFromStatsTable () [private]
Definition at line 34 of file counters.cc.
                                                     {
  // {Init} must have been called.
  DCHECK_NOT_NULL(counters_);
  DCHECK_NOT_NULL(name_);
  int* location = counters_->FindLocation(name_);
  std::atomic<int>* ptr =
      location ? base::AsAtomicPtr(location) : &unused_counter_dump;
#ifdef DEBUG
  std::atomic<int>* old_ptr = ptr_.exchange(ptr, std::memory_order_release);
  DCHECK_IMPLIES(old_ptr, old_ptr == ptr);
#else
  ptr_.store(ptr, std::memory_order_release);
#endif
  return ptr;
}
References v8::base::AsAtomicPtr(), counters_, DCHECK_IMPLIES, DCHECK_NOT_NULL, v8::internal::Counters::FindLocation(), name_, ptr_, and v8::internal::anonymous_namespace{counters.cc}::unused_counter_dump.
Referenced by GetPtr().
Friends And Related Function Documentation
Counters
friend class Counters [friend]
Definition at line 125 of file counters.h.
CountersInitializer
friend class CountersInitializer [friend]
Definition at line 126 of file counters.h.
StatsCounterResetter
friend class StatsCounterResetter [friend]
Definition at line 127 of file counters.h.
Member Data Documentation
counters_
Counters* v8::internal::StatsCounter::counters_ = nullptr [private]
Definition at line 150 of file counters.h.
Referenced by Initialize(), and SetupPtrFromStatsTable().
name_
const char* v8::internal::StatsCounter::name_ = nullptr [private]
Definition at line 151 of file counters.h.
Referenced by Initialize(), name(), and SetupPtrFromStatsTable().
ptr_
std::atomic<std::atomic<int>*> v8::internal::StatsCounter::ptr_ {nullptr} [private]
Definition at line 153 of file counters.h.
Referenced by GetPtr(), Reset(), and SetupPtrFromStatsTable().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/logging/counters.h
/mnt/V8SourceCode/src/logging/counters.cc