v8::internal::wasm::ModuleDisassembler Class Reference
#include <wasm-disassembler-impl.h>
Public Member Functions
V8_EXPORT_PRIVATE ModuleDisassembler (MultiLineStringBuilder &out, const WasmModule *module, NamesProvider *names, const ModuleWireBytes wire_bytes, AccountingAllocator *allocator, std::unique_ptr< OffsetsProvider > offsets_provider={}, std::vector< int > *function_body_offsets=nullptr)
V8_EXPORT_PRIVATE ~ModuleDisassembler ()
V8_EXPORT_PRIVATE void PrintTypeDefinition (uint32_t type_index, Indentation indendation, IndexAsComment index_as_comment)
V8_EXPORT_PRIVATE void PrintModule (Indentation indentation, size_t max_mb)
Private Member Functions
void PrintImportName (const WasmImport &import)
void PrintExportName (ImportExportKindCode kind, uint32_t index)
void PrintMutableType (bool mutability, ValueType type)
void PrintTable (const WasmTable &table)
void PrintMemory (const WasmMemory &memory)
void PrintGlobal (const WasmGlobal &global)
void PrintInitExpression (const ConstantExpression &init, ValueType expected_type)
void PrintTagSignature (const FunctionSig *sig)
void PrintString (WireBytesRef ref)
void PrintStringAsJSON (WireBytesRef ref)
void LineBreakOrSpace (bool break_lines, Indentation indentation, uint32_t byte_offset)
Private Attributes
MultiLineStringBuilder & out_
const WasmModule * module_
NamesProvider * names_
const ModuleWireBytes wire_bytes_
const uint8_t * start_
Zone zone_
std::unique_ptr< OffsetsProvider > offsets_
std::vector< int > * function_body_offsets_
Detailed Description
Definition at line 294 of file wasm-disassembler-impl.h.
Constructor & Destructor Documentation
ModuleDisassembler()
v8::internal::wasm::ModuleDisassembler::ModuleDisassembler (MultiLineStringBuilder & out, const WasmModule * module, NamesProvider * names, const ModuleWireBytes wire_bytes, AccountingAllocator * allocator, std::unique_ptr< OffsetsProvider > offsets_provider = {}, std::vector< int > * function_body_offsets = nullptr)
Definition at line 764 of file wasm-disassembler.cc.
    : out_(out),
      module_(module),
      names_(names),
      wire_bytes_(wire_bytes),
      start_(wire_bytes_.start()),
      zone_(allocator, "disassembler zone"),
      offsets_(offsets_provider.release()),
      function_body_offsets_(function_body_offsets) {
  if (!offsets_) {
    offsets_ = std::make_unique<OffsetsProvider>();
    offsets_->CollectOffsets(module, wire_bytes_.module_bytes());
  }
}
References v8::internal::wasm::ModuleWireBytes::module_bytes(), offsets_, and wire_bytes_.
 ModuleDisassembler()
v8::internal::wasm::ModuleDisassembler::~ModuleDisassembler () [default]
Member Function Documentation
LineBreakOrSpace()
void v8::internal::wasm::ModuleDisassembler::LineBreakOrSpace (bool break_lines, Indentation indentation, uint32_t byte_offset) [private]
Definition at line 1268 of file wasm-disassembler.cc.
                                                                {
  if (break_lines) {
    out_.NextLine(byte_offset);
    out_ << indentation.Extra(2);
  } else {
    out_ << " ";
  }
}
References v8::internal::wasm::Indentation::Extra(), v8::internal::wasm::MultiLineStringBuilder::NextLine(), and out_.
Referenced by PrintTypeDefinition().
PrintExportName()
void v8::internal::wasm::ModuleDisassembler::PrintExportName (ImportExportKindCode kind, uint32_t index) [private]
Definition at line 1152 of file wasm-disassembler.cc.
                                                         {
  for (const WasmExport& ex : module_->export_table) {
    if (ex.kind != kind || ex.index != index) continue;
    out_ << " (export \"";
    PrintStringAsJSON(ex.name);
    out_ << "\")";
  }
}
References v8::internal::wasm::WasmModule::export_table, v8::internal::index, v8::internal::wasm::WasmExport::index, v8::internal::wasm::WasmExport::kind, module_, v8::internal::wasm::WasmExport::name, out_, and PrintStringAsJSON().
Referenced by PrintModule().
PrintGlobal()
void v8::internal::wasm::ModuleDisassembler::PrintGlobal (const WasmGlobal & global) [private]
Definition at line 1181 of file wasm-disassembler.cc.
                                                             {
  out_ << " ";
  if (global.shared) out_ << "shared ";
  PrintMutableType(global.mutability, global.type);
}
References v8::internal::wasm::WasmGlobal::mutability, out_, PrintMutableType(), v8::internal::wasm::WasmGlobal::shared, and v8::internal::wasm::WasmGlobal::type.
Referenced by PrintModule().
PrintImportName()
void v8::internal::wasm::ModuleDisassembler::PrintImportName (const WasmImport & import) [private]
Definition at line 1144 of file wasm-disassembler.cc.
                                                                 {
  out_ << " (import \"";
  PrintString(import.module_name);
  out_ << "\" \"";
  PrintString(import.field_name);
  out_ << "\")";
}
References out_, and PrintString().
Referenced by PrintModule().
PrintInitExpression()
void v8::internal::wasm::ModuleDisassembler::PrintInitExpression (const ConstantExpression & init, ValueType expected_type) [private]
Definition at line 1187 of file wasm-disassembler.cc.
                                                                      {
  switch (init.kind()) {
    case ConstantExpression::Kind::kEmpty:
      break;
    case ConstantExpression::Kind::kI32Const:
      out_ << " (i32.const " << init.i32_value() << ")";
      break;
    case ConstantExpression::Kind::kRefNull:
      out_ << " (ref.null ";
      names_->PrintHeapType(out_, init.type());
      out_ << ")";
      break;
    case ConstantExpression::Kind::kRefFunc:
      out_ << " (ref.func ";
      names_->PrintFunctionName(out_, init.index(), NamesProvider::kDevTools);
      out_ << ")";
      break;
    case ConstantExpression::Kind::kWireBytesRef:
      WireBytesRef ref = init.wire_bytes_ref();
      const uint8_t* start = start_ + ref.offset();
      const uint8_t* end = start_ + ref.end_offset();
      auto sig = FixedSizeSignature<ValueType>::Returns(expected_type);
      WasmDetectedFeatures detected;
      FunctionBodyDisassembler d(&zone_, module_, 0, false, &detected, &sig,
                                 start, end, ref.offset(), wire_bytes_, names_);
      d.DecodeGlobalInitializer(out_);
      break;
  }
}
References v8::internal::wasm::FunctionBodyDisassembler::DecodeGlobalInitializer(), v8::internal::compiler::end(), v8::internal::wasm::WireBytesRef::end_offset(), v8::internal::wasm::ConstantExpression::i32_value(), v8::internal::wasm::ConstantExpression::index(), v8::internal::wasm::NamesProvider::kDevTools, v8::internal::wasm::ConstantExpression::kEmpty, v8::internal::wasm::ConstantExpression::kI32Const, v8::internal::wasm::ConstantExpression::kind(), v8::internal::wasm::ConstantExpression::kRefFunc, v8::internal::wasm::ConstantExpression::kRefNull, v8::internal::wasm::ConstantExpression::kWireBytesRef, module_, names_, v8::internal::wasm::WireBytesRef::offset(), out_, v8::internal::wasm::NamesProvider::PrintFunctionName(), v8::internal::wasm::NamesProvider::PrintHeapType(), v8::internal::FixedSizeSignature< T, kNumReturns, kNumParams >::Returns(), v8::internal::sig, start_, v8::internal::wasm::ConstantExpression::type(), wire_bytes_, v8::internal::wasm::ConstantExpression::wire_bytes_ref(), and zone_.
Referenced by PrintModule().
PrintMemory()
void v8::internal::wasm::ModuleDisassembler::PrintMemory (const WasmMemory & memory) [private]
Definition at line 1175 of file wasm-disassembler.cc.
                                                             {
  out_ << " " << memory.initial_pages;
  if (memory.has_maximum_pages) out_ << " " << memory.maximum_pages;
  if (memory.is_shared) out_ << " shared";
}
References v8::internal::wasm::WasmMemory::has_maximum_pages, v8::internal::wasm::WasmMemory::initial_pages, v8::internal::wasm::WasmMemory::is_shared, v8::internal::wasm::WasmMemory::maximum_pages, and out_.
Referenced by PrintModule().
PrintModule()
void v8::internal::wasm::ModuleDisassembler::PrintModule (Indentation indentation, size_t max_mb)
Definition at line 845 of file wasm-disassembler.cc.
                                                                           {
  // 0. General infrastructure.
  // We don't store import/export information on {WasmTag} currently.
  size_t num_tags = module_->tags.size();
  std::vector<bool> exported_tags(num_tags, false);
  for (const WasmExport& ex : module_->export_table) {
    if (ex.kind == kExternalTag) exported_tags[ex.index] = true;
  }
  // I. Module name.
  out_ << indentation << "(module";
  if (module_->name.is_set()) {
    out_ << " $";
    const uint8_t* name_start = start_ + module_->name.offset();
    out_.write(name_start, module_->name.length());
  }
  indentation.increase();
  // II. Types
  uint32_t recgroup_index = 0;
  OffsetsProvider::RecGroup recgroup = offsets_->recgroup(recgroup_index++);
  bool in_explicit_recgroup = false;
  for (uint32_t i = 0; i < module_->types.size(); i++) {
    // No need to check {recgroup.valid()}, as the comparison will simply
    // never be true otherwise.
    while (i == recgroup.start_type_index) {
      out_.NextLine(recgroup.offset);
      out_ << indentation << "(rec";
      if V8_UNLIKELY (recgroup.end_type_index == i) {
        // Empty recgroup.
        out_ << ")";
        DCHECK(!in_explicit_recgroup);
        recgroup = offsets_->recgroup(recgroup_index++);
        continue;
      } else {
        in_explicit_recgroup = true;
        indentation.increase();
        break;
      }
    }
    if (kSkipFunctionTypesInTypeSection &&
        module_->has_signature(ModuleTypeIndex{i}) && !in_explicit_recgroup) {
      continue;
    }
    PrintTypeDefinition(i, indentation, kIndicesAsComments);
    if (in_explicit_recgroup && i == recgroup.end_type_index - 1) {
      in_explicit_recgroup = false;
      indentation.decrease();
      // The end of a recgroup is implicit in the wire bytes, so repeat the
      // previous line's offset for it.
      uint32_t offset = out_.current_line_bytecode_offset();
      out_.NextLine(offset);
      out_ << indentation << ")";
      recgroup = offsets_->recgroup(recgroup_index++);
    }
  }
  while (recgroup.valid()) {
    // There could be empty recgroups at the end of the type section.
    DCHECK_GE(recgroup.start_type_index, module_->types.size());
    DCHECK_EQ(recgroup.start_type_index, recgroup.end_type_index);
    out_.NextLine(recgroup.offset);
    out_ << indentation << "(rec)";
    recgroup = offsets_->recgroup(recgroup_index++);
  }
  // III. Imports
  for (uint32_t i = 0; i < module_->import_table.size(); i++) {
    const WasmImport& import = module_->import_table[i];
    out_.NextLine(offsets_->import_offset(i));
    out_ << indentation;
    switch (import.kind) {
      case kExternalTable: {
        out_ << "(table ";
        names_->PrintTableName(out_, import.index, kIndicesAsComments);
        const WasmTable& table = module_->tables[import.index];
        if (table.exported) PrintExportName(kExternalTable, import.index);
        PrintImportName(import);
        PrintTable(table);
        break;
      }
      case kExternalFunction: {
        out_ << "(func ";
        names_->PrintFunctionName(out_, import.index, NamesProvider::kDevTools,
                                  kIndicesAsComments);
        const WasmFunction& func = module_->functions[import.index];
        if (func.exported) PrintExportName(kExternalFunction, import.index);
        PrintImportName(import);
        PrintSignatureOneLine(out_, func.sig, import.index, names_, false);
        break;
      }
      case kExternalGlobal: {
        out_ << "(global ";
        names_->PrintGlobalName(out_, import.index, kIndicesAsComments);
        const WasmGlobal& global = module_->globals[import.index];
        if (global.exported) PrintExportName(kExternalGlobal, import.index);
        PrintImportName(import);
        PrintGlobal(global);
        break;
      }
      case kExternalMemory:
        out_ << "(memory ";
        names_->PrintMemoryName(out_, import.index, kIndicesAsComments);
        if (module_->memories[import.index].exported) {
          PrintExportName(kExternalMemory, 0);
        }
        PrintImportName(import);
        PrintMemory(module_->memories[import.index]);
        break;
      case kExternalTag:
        out_ << "(tag ";
        names_->PrintTagName(out_, import.index, kIndicesAsComments);
        PrintImportName(import);
        if (exported_tags[import.index]) {
          PrintExportName(kExternalTag, import.index);
        }
        PrintTagSignature(module_->tags[import.index].sig);
        break;
    }
    out_ << ")";
  }
  // IV. Tables
  for (uint32_t i = module_->num_imported_tables; i < module_->tables.size();
       i++) {
    const WasmTable& table = module_->tables[i];
    DCHECK(!table.imported);
    out_.NextLine(offsets_->table_offset(i));
    out_ << indentation << "(table ";
    names_->PrintTableName(out_, i, kIndicesAsComments);
    if (table.exported) PrintExportName(kExternalTable, i);
    PrintTable(table);
    out_ << ")";
  }
  // V. Memories
  uint32_t num_memories = static_cast<uint32_t>(module_->memories.size());
  for (uint32_t memory_index = 0; memory_index < num_memories; ++memory_index) {
    const WasmMemory& memory = module_->memories[memory_index];
    if (memory.imported) continue;
    out_.NextLine(offsets_->memory_offset());
    out_ << indentation << "(memory ";
    names_->PrintMemoryName(out_, memory_index, kIndicesAsComments);
    if (memory.exported) PrintExportName(kExternalMemory, memory_index);
    PrintMemory(memory);
    out_ << ")";
  }
  // VI.Tags
  for (uint32_t i = module_->num_imported_tags; i < module_->tags.size(); i++) {
    const WasmTag& tag = module_->tags[i];
    out_.NextLine(offsets_->tag_offset(i));
    out_ << indentation << "(tag ";
    names_->PrintTagName(out_, i, kIndicesAsComments);
    if (exported_tags[i]) PrintExportName(kExternalTag, i);
    PrintTagSignature(tag.sig);
    out_ << ")";
  }
  // VII. String literals
  size_t num_strings = module_->stringref_literals.size();
  for (uint32_t i = 0; i < num_strings; i++) {
    const WasmStringRefLiteral lit = module_->stringref_literals[i];
    out_.NextLine(offsets_->string_offset(i));
    out_ << indentation << "(string \"";
    PrintString(lit.source);
    out_ << '"';
    if (kIndicesAsComments) out_ << " (;" << i << ";)";
    out_ << ")";
  }
  // VIII. Globals
  for (uint32_t i = module_->num_imported_globals; i < module_->globals.size();
       i++) {
    const WasmGlobal& global = module_->globals[i];
    DCHECK(!global.imported);
    out_.NextLine(offsets_->global_offset(i));
    out_ << indentation << "(global ";
    names_->PrintGlobalName(out_, i, kIndicesAsComments);
    if (global.exported) PrintExportName(kExternalGlobal, i);
    PrintGlobal(global);
    PrintInitExpression(global.init, global.type);
    out_ << ")";
  }
  // IX. Start
  if (module_->start_function_index >= 0) {
    out_.NextLine(offsets_->start_offset());
    out_ << indentation << "(start ";
    names_->PrintFunctionName(out_, module_->start_function_index,
                              NamesProvider::kDevTools);
    out_ << ")";
  }
  // X. Elements
  for (uint32_t i = 0; i < module_->elem_segments.size(); i++) {
    const WasmElemSegment& elem = module_->elem_segments[i];
    out_.NextLine(offsets_->element_offset(i));
    out_ << indentation << "(elem ";
    names_->PrintElementSegmentName(out_, i, kIndicesAsComments);
    if (elem.status == WasmElemSegment::kStatusDeclarative) {
      out_ << " declare";
    } else if (elem.status == WasmElemSegment::kStatusActive) {
      if (elem.table_index != 0) {
        out_ << " (table ";
        names_->PrintTableName(out_, elem.table_index);
        out_ << ")";
      }
      PrintInitExpression(elem.offset, kWasmI32);
    }
    out_ << " ";
    if (elem.shared) out_ << "shared ";
    names_->PrintValueType(out_, elem.type);
    WasmDetectedFeatures unused_detected_features;
    ModuleDecoderImpl decoder(
        WasmEnabledFeatures::All(), wire_bytes_.module_bytes(),
        ModuleOrigin::kWasmOrigin, &unused_detected_features);
    decoder.consume_bytes(elem.elements_wire_bytes_offset);
    for (size_t j = 0; j < elem.element_count; j++) {
      ConstantExpression entry = decoder.consume_element_segment_entry(
          const_cast<WasmModule*>(module_), elem);
      PrintInitExpression(entry, elem.type);
    }
    out_ << ")";
  }
  // For the FunctionBodyDisassembler, we flip the convention: {NextLine} is
  // now called *after* printing something, instead of before.
  if (out_.length() != 0) out_.NextLine(0);
  // XI. Code / function bodies.
  if (function_body_offsets_ != nullptr) {
    size_t num_defined_functions =
        module_->functions.size() - module_->num_imported_functions;
    function_body_offsets_->reserve(num_defined_functions * 2);
  }
  for (uint32_t i = module_->num_imported_functions;
       i < module_->functions.size(); i++) {
    const WasmFunction* func = &module_->functions[i];
    out_.set_current_line_bytecode_offset(func->code.offset());
    out_ << indentation << "(func ";
    names_->PrintFunctionName(out_, i, NamesProvider::kDevTools,
                              kIndicesAsComments);
    if (func->exported) PrintExportName(kExternalFunction, i);
    PrintSignatureOneLine(out_, func->sig, i, names_, true, kIndicesAsComments);
    out_.NextLine(func->code.offset());
    bool shared = module_->type(func->sig_index).is_shared;
    WasmDetectedFeatures detected;
    base::Vector<const uint8_t> code = wire_bytes_.GetFunctionBytes(func);
    FunctionBodyDisassembler d(&zone_, module_, i, shared, &detected, func->sig,
                               code.begin(), code.end(), func->code.offset(),
                               wire_bytes_, names_);
    uint32_t first_instruction_offset;
    d.DecodeAsWat(out_, indentation, FunctionBodyDisassembler::kSkipHeader,
                  &first_instruction_offset);
    if (function_body_offsets_ != nullptr) {
      function_body_offsets_->push_back(first_instruction_offset);
      function_body_offsets_->push_back(d.pc_offset());
    }
    if (out_.ApproximateSizeMB() > max_mb) {
      out_ << "<truncated...>";
      return;
    }
  }
  // XII. Data
  for (uint32_t i = 0; i < module_->data_segments.size(); i++) {
    const WasmDataSegment& data = module_->data_segments[i];
    out_.set_current_line_bytecode_offset(offsets_->data_offset(i));
    out_ << indentation << "(data";
    if (!kSkipDataSegmentNames) {
      out_ << " ";
      names_->PrintDataSegmentName(out_, i, kIndicesAsComments);
    }
    if (data.shared) out_ << " shared";
    if (data.active) {
      ValueType type = module_->memories[data.memory_index].is_memory64()
                           ? kWasmI64
                           : kWasmI32;
      PrintInitExpression(data.dest_addr, type);
    }
    out_ << " \"";
    PrintString(data.source);
    out_ << "\")";
    out_.NextLine(0);
    if (out_.ApproximateSizeMB() > max_mb) {
      out_ << "<truncated...>";
      return;
    }
  }
  indentation.decrease();
  out_.set_current_line_bytecode_offset(
      static_cast<uint32_t>(wire_bytes_.length()));
  out_ << indentation << ")"; // End of the module.
  out_.NextLine(0);
}
References v8::internal::wasm::WasmDataSegment::active, v8::internal::wasm::WasmEnabledFeatures::All(), v8::internal::wasm::MultiLineStringBuilder::ApproximateSizeMB(), code, v8::internal::wasm::WasmFunction::code, v8::internal::wasm::Decoder::consume_bytes(), v8::internal::wasm::ModuleDecoderImpl::consume_element_segment_entry(), v8::internal::wasm::MultiLineStringBuilder::current_line_bytecode_offset(), v8::internal::wasm::WasmModule::data_segments, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, v8::internal::wasm::FunctionBodyDisassembler::DecodeAsWat(), v8::internal::wasm::Indentation::decrease(), v8::internal::wasm::WasmDataSegment::dest_addr, v8::internal::wasm::WasmModule::elem_segments, v8::internal::wasm::WasmElemSegment::element_count, v8::internal::wasm::WasmElemSegment::elements_wire_bytes_offset, v8::internal::wasm::OffsetsProvider::RecGroup::end_type_index, v8::internal::wasm::WasmModule::export_table, v8::internal::wasm::WasmFunction::exported, v8::internal::wasm::WasmGlobal::exported, v8::internal::wasm::WasmMemory::exported, v8::internal::wasm::WasmTable::exported, function_body_offsets_, v8::internal::wasm::WasmModule::functions, v8::internal::wasm::ModuleWireBytes::GetFunctionBytes(), v8::internal::wasm::WasmModule::globals, v8::internal::wasm::WasmModule::has_signature(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::WasmModule::import_table, v8::internal::wasm::WasmGlobal::imported, v8::internal::wasm::WasmMemory::imported, v8::internal::wasm::WasmTable::imported, v8::internal::wasm::Indentation::increase(), v8::internal::index, v8::internal::wasm::WasmExport::index, v8::internal::wasm::WasmGlobal::init, v8::internal::wasm::WireBytesRef::is_set(), v8::internal::wasm::TypeDefinition::is_shared, v8::internal::wasm::NamesProvider::kDevTools, v8::internal::wasm::kExternalFunction, v8::internal::wasm::kExternalGlobal, v8::internal::wasm::kExternalMemory, v8::internal::wasm::kExternalTable, v8::internal::wasm::kExternalTag, v8::internal::wasm::WasmExport::kind, v8::internal::wasm::kIndicesAsComments, v8::internal::wasm::kSkipDataSegmentNames, v8::internal::wasm::kSkipFunctionTypesInTypeSection, v8::internal::wasm::FunctionBodyDisassembler::kSkipHeader, v8::internal::wasm::WasmElemSegment::kStatusActive, v8::internal::wasm::WasmElemSegment::kStatusDeclarative, v8::internal::wasm::kWasmI32, v8::internal::wasm::kWasmI64, v8::internal::wasm::kWasmOrigin, v8::internal::wasm::StringBuilder::length(), v8::internal::wasm::WireBytesRef::length(), v8::internal::wasm::ModuleWireBytes::length(), v8::internal::wasm::WasmModule::memories, v8::internal::wasm::WasmDataSegment::memory_index, module_, v8::internal::wasm::ModuleWireBytes::module_bytes(), v8::internal::wasm::WasmModule::name, names_, v8::internal::wasm::MultiLineStringBuilder::NextLine(), v8::internal::wasm::WasmModule::num_imported_functions, v8::internal::wasm::WasmModule::num_imported_globals, v8::internal::wasm::WasmModule::num_imported_tables, v8::internal::wasm::WasmModule::num_imported_tags, v8::internal::wasm::OffsetsProvider::RecGroup::offset, v8::internal::wasm::WireBytesRef::offset(), v8::internal::wasm::WasmElemSegment::offset, offsets_, out_, v8::internal::wasm::Decoder::pc_offset(), v8::internal::wasm::NamesProvider::PrintDataSegmentName(), v8::internal::wasm::NamesProvider::PrintElementSegmentName(), PrintExportName(), v8::internal::wasm::NamesProvider::PrintFunctionName(), PrintGlobal(), v8::internal::wasm::NamesProvider::PrintGlobalName(), PrintImportName(), PrintInitExpression(), PrintMemory(), v8::internal::wasm::NamesProvider::PrintMemoryName(), v8::internal::wasm::PrintSignatureOneLine(), PrintString(), PrintTable(), v8::internal::wasm::NamesProvider::PrintTableName(), v8::internal::wasm::NamesProvider::PrintTagName(), PrintTagSignature(), PrintTypeDefinition(), v8::internal::wasm::NamesProvider::PrintValueType(), v8::internal::wasm::MultiLineStringBuilder::set_current_line_bytecode_offset(), v8::internal::wasm::WasmDataSegment::shared, v8::internal::wasm::WasmElemSegment::shared, v8::internal::wasm::WasmFunction::sig, v8::internal::wasm::WasmTag::sig, v8::internal::wasm::WasmFunction::sig_index, v8::internal::wasm::WasmStringRefLiteral::source, v8::internal::wasm::WasmDataSegment::source, start_, v8::internal::wasm::WasmModule::start_function_index, v8::internal::wasm::OffsetsProvider::RecGroup::start_type_index, v8::internal::wasm::WasmElemSegment::status, v8::internal::wasm::WasmModule::stringref_literals, v8::internal::wasm::WasmElemSegment::table_index, v8::internal::wasm::WasmModule::tables, v8::internal::tables, v8::internal::wasm::WasmModule::tags, v8::internal::tracing::type, v8::internal::wasm::WasmGlobal::type, v8::internal::wasm::WasmElemSegment::type, v8::internal::wasm::WasmModule::type(), v8::internal::wasm::WasmModule::types, V8_UNLIKELY, v8::internal::wasm::OffsetsProvider::RecGroup::valid(), wire_bytes_, v8::internal::wasm::StringBuilder::write(), and zone_.
Referenced by v8::internal::wasm::Disassemble().
PrintMutableType()
void v8::internal::wasm::ModuleDisassembler::PrintMutableType (bool mutability, ValueType type) [private]
Definition at line 1162 of file wasm-disassembler.cc.
                                                                         {
  if (mutability) out_ << "(mut ";
  names_->PrintValueType(out_, type);
  if (mutability) out_ << ")";
}
References names_, out_, v8::internal::wasm::NamesProvider::PrintValueType(), and v8::internal::tracing::type.
Referenced by PrintGlobal(), and PrintTypeDefinition().
PrintString()
void v8::internal::wasm::ModuleDisassembler::PrintString (WireBytesRef ref) [private]
Definition at line 1227 of file wasm-disassembler.cc.
                                                     {
  PrintStringRaw(out_, start_ + ref.offset(), start_ + ref.end_offset());
}
References v8::internal::wasm::WireBytesRef::end_offset(), v8::internal::wasm::WireBytesRef::offset(), out_, v8::internal::wasm::PrintStringRaw(), and start_.
Referenced by PrintImportName(), and PrintModule().
PrintStringAsJSON()
void v8::internal::wasm::ModuleDisassembler::PrintStringAsJSON (WireBytesRef ref) [private]
Definition at line 1233 of file wasm-disassembler.cc.
                                                           {
  i::wasm::PrintStringAsJSON(out_, start_, ref);
}
References out_, v8::internal::wasm::PrintStringAsJSON(), and start_.
Referenced by PrintExportName().
PrintTable()
void v8::internal::wasm::ModuleDisassembler::PrintTable (const WasmTable & table) [private]
Definition at line 1168 of file wasm-disassembler.cc.
                                                          {
  if (table.shared) out_ << " shared";
  out_ << " " << table.initial_size << " ";
  if (table.has_maximum_size) out_ << table.maximum_size << " ";
  names_->PrintValueType(out_, table.type);
}
References v8::internal::wasm::WasmTable::has_maximum_size, v8::internal::wasm::WasmTable::initial_size, v8::internal::wasm::WasmTable::maximum_size, names_, out_, v8::internal::wasm::NamesProvider::PrintValueType(), v8::internal::wasm::WasmTable::shared, and v8::internal::wasm::WasmTable::type.
Referenced by PrintModule().
PrintTagSignature()
void v8::internal::wasm::ModuleDisassembler::PrintTagSignature (const FunctionSig * sig) [private]
Definition at line 1219 of file wasm-disassembler.cc.
                                                                 {
  for (uint32_t i = 0; i < sig->parameter_count(); i++) {
    out_ << " (param ";
    names_->PrintValueType(out_, sig->GetParam(i));
    out_ << ")";
  }
}
References names_, out_, v8::internal::wasm::NamesProvider::PrintValueType(), and v8::internal::sig.
Referenced by PrintModule().
PrintTypeDefinition()
void v8::internal::wasm::ModuleDisassembler::PrintTypeDefinition (uint32_t type_index, Indentation indendation, IndexAsComment index_as_comment)
Definition at line 785 of file wasm-disassembler.cc.
                                                                              {
  uint32_t offset = offsets_->type_offset(type_index);
  out_.NextLine(offset);
  out_ << indentation << "(type ";
  names_->PrintTypeName(out_, type_index, index_as_comment);
  const TypeDefinition& type = module_->types[type_index];
  bool has_super = type.supertype != kNoSuperType;
  if (has_super) {
    out_ << " (sub ";
    if (type.is_final) out_ << "final ";
    names_->PrintHeapType(out_,
                          HeapType::Index(type.supertype, type.is_shared,
                                          static_cast<RefTypeKind>(type.kind)));
  }
  if (type.kind == TypeDefinition::kArray) {
    const ArrayType* atype = type.array_type;
    out_ << " (array";
    if (type.is_shared) out_ << " shared";
    out_ << " (field ";
    PrintMutableType(atype->mutability(), atype->element_type());
    out_ << ")"; // Closes "(field ...".
  } else if (type.kind == TypeDefinition::kStruct) {
    const StructType* stype = type.struct_type;
    out_ << " (struct";
    if (type.is_shared) out_ << " shared";
    bool break_lines = stype->field_count() > 2;
    for (uint32_t i = 0; i < stype->field_count(); i++) {
      LineBreakOrSpace(break_lines, indentation, offset);
      out_ << "(field ";
      names_->PrintFieldName(out_, type_index, i);
      out_ << " ";
      PrintMutableType(stype->mutability(i), stype->field(i));
      out_ << ")";
    }
  } else if (type.kind == TypeDefinition::kFunction) {
    const FunctionSig* sig = type.function_sig;
    out_ << " (func";
    if (type.is_shared) out_ << " shared";
    bool break_lines = sig->parameter_count() + sig->return_count() > 2;
    for (uint32_t i = 0; i < sig->parameter_count(); i++) {
      LineBreakOrSpace(break_lines, indentation, offset);
      out_ << "(param ";
      names_->PrintLocalName(out_, type_index, i);
      out_ << " ";
      names_->PrintValueType(out_, sig->GetParam(i));
      out_ << ")";
    }
    for (uint32_t i = 0; i < sig->return_count(); i++) {
      LineBreakOrSpace(break_lines, indentation, offset);
      out_ << "(result ";
      names_->PrintValueType(out_, sig->GetReturn(i));
      out_ << ")";
    }
  }
  // Closes "(type", "(sub", and "(array" / "(struct" / "(func".
  out_ << (has_super ? ")))" : "))");
}
References v8::internal::wasm::ArrayType::element_type(), v8::internal::wasm::StructType::field(), v8::internal::wasm::StructTypeBase::field_count(), v8::internal::wasm::HeapType::Index(), v8::internal::wasm::TypeDefinition::kArray, v8::internal::wasm::TypeDefinition::kFunction, v8::internal::wasm::kNoSuperType, v8::internal::wasm::TypeDefinition::kStruct, LineBreakOrSpace(), module_, v8::internal::wasm::ArrayTypeBase::mutability(), v8::internal::wasm::StructTypeBase::mutability(), names_, v8::internal::wasm::MultiLineStringBuilder::NextLine(), offsets_, out_, v8::internal::wasm::NamesProvider::PrintFieldName(), v8::internal::wasm::NamesProvider::PrintHeapType(), v8::internal::wasm::NamesProvider::PrintLocalName(), PrintMutableType(), v8::internal::wasm::NamesProvider::PrintTypeName(), v8::internal::wasm::NamesProvider::PrintValueType(), v8::internal::sig, v8::internal::tracing::type, and v8::internal::wasm::WasmModule::types.
Referenced by PrintModule().
Member Data Documentation
function_body_offsets_
std::vector<int>* v8::internal::wasm::ModuleDisassembler::function_body_offsets_ [private]
Definition at line 331 of file wasm-disassembler-impl.h.
Referenced by PrintModule().
module_
const WasmModule* v8::internal::wasm::ModuleDisassembler::module_ [private]
Definition at line 325 of file wasm-disassembler-impl.h.
Referenced by PrintExportName(), PrintInitExpression(), PrintModule(), and PrintTypeDefinition().
names_
NamesProvider* v8::internal::wasm::ModuleDisassembler::names_ [private]
Definition at line 326 of file wasm-disassembler-impl.h.
Referenced by PrintInitExpression(), PrintModule(), PrintMutableType(), PrintTable(), PrintTagSignature(), and PrintTypeDefinition().
offsets_
std::unique_ptr<OffsetsProvider> v8::internal::wasm::ModuleDisassembler::offsets_ [private]
Definition at line 330 of file wasm-disassembler-impl.h.
Referenced by ModuleDisassembler(), PrintModule(), and PrintTypeDefinition().
out_
MultiLineStringBuilder& v8::internal::wasm::ModuleDisassembler::out_ [private]
Definition at line 324 of file wasm-disassembler-impl.h.
Referenced by LineBreakOrSpace(), PrintExportName(), PrintGlobal(), PrintImportName(), PrintInitExpression(), PrintMemory(), PrintModule(), PrintMutableType(), PrintString(), PrintStringAsJSON(), PrintTable(), PrintTagSignature(), and PrintTypeDefinition().
start_
const uint8_t* v8::internal::wasm::ModuleDisassembler::start_ [private]
Definition at line 328 of file wasm-disassembler-impl.h.
Referenced by PrintInitExpression(), PrintModule(), PrintString(), and PrintStringAsJSON().
wire_bytes_
const ModuleWireBytes v8::internal::wasm::ModuleDisassembler::wire_bytes_ [private]
Definition at line 327 of file wasm-disassembler-impl.h.
Referenced by ModuleDisassembler(), PrintInitExpression(), and PrintModule().
zone_
Zone v8::internal::wasm::ModuleDisassembler::zone_ [private]
Definition at line 329 of file wasm-disassembler-impl.h.
Referenced by PrintInitExpression(), and PrintModule().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-disassembler-impl.h
/mnt/V8SourceCode/src/wasm/wasm-disassembler.cc