v8::internal::RelocIteratorBase< RelocInfoT > Class Template Reference
#include <reloc-info.h>
Public Member Functions
RelocIteratorBase (RelocIteratorBase &&) V8_NOEXCEPT=default
RelocIteratorBase (const RelocIteratorBase &)=delete
RelocIteratorBase & operator= (const RelocIteratorBase &)=delete
bool done () const
void next ()
RelocInfoT * rinfo ()
Static Public Attributes
static constexpr int kAllModesMask = -1
Protected Member Functions
RelocIteratorBase (RelocInfoT reloc_info, const uint8_t *pos, const uint8_t *end, int mode_mask)
bool SetMode (RelocInfo::Mode mode)
RelocInfo::Mode GetMode () const
void Advance (int bytes=1)
int AdvanceGetTag ()
void AdvanceReadLongPCJump ()
void AdvanceReadPC ()
void AdvanceReadInt ()
void ReadShortTaggedPC ()
void ReadShortData ()
Protected Attributes
const uint8_t * pos_
const uint8_t *const end_
RelocInfoT rinfo_
bool done_ = false
const int mode_mask_
Detailed Description
template<typename RelocInfoT>
class v8::internal::RelocIteratorBase< RelocInfoT >
Definition at line 514 of file reloc-info.h.
Constructor & Destructor Documentation
RelocIteratorBase() [1/3]
template<typename RelocInfoT >
v8::internal::RelocIteratorBase< RelocInfoT >::RelocIteratorBase (RelocIteratorBase< RelocInfoT > &&) [default]
RelocIteratorBase() [2/3]
template<typename RelocInfoT >
v8::internal::RelocIteratorBase< RelocInfoT >::RelocIteratorBase (const RelocIteratorBase< RelocInfoT > &) [delete]
RelocIteratorBase() [3/3]
template<typename RelocInfoT >
v8::internal::RelocIteratorBase< RelocInfoT >::RelocIteratorBase (RelocInfoT reloc_info, const uint8_t * pos, const uint8_t * end, int mode_mask) [inline], [protected]
Definition at line 53 of file reloc-info-inl.h.
    : pos_(pos), end_(end), rinfo_(reloc_info), mode_mask_(mode_mask) {
  DCHECK_EQ(reloc_info.rmode(), RelocInfo::NO_INFO);
  DCHECK_EQ(reloc_info.data(), 0);
  // Relocation info is read backwards.
  DCHECK_GE(pos_, end_);
  if (mode_mask_ == 0) pos_ = end_;
  next();
}
References DCHECK_EQ, DCHECK_GE, v8::internal::RelocIteratorBase< RelocInfoT >::end_, v8::internal::RelocIteratorBase< RelocInfoT >::mode_mask_, v8::internal::RelocIteratorBase< RelocInfoT >::next(), v8::internal::RelocInfo::NO_INFO, and v8::internal::RelocIteratorBase< RelocInfoT >::pos_.
Member Function Documentation
Advance()
template<typename RelocInfoT >
void v8::internal::RelocIteratorBase< RelocInfoT >::Advance (int bytes = 1) [inline], [protected]
Definition at line 547 of file reloc-info.h.
{ pos_ -= bytes; }
References v8::internal::RelocIteratorBase< RelocInfoT >::pos_.
AdvanceGetTag()
template<typename RelocInfoT >
int v8::internal::RelocIteratorBase< RelocInfoT >::AdvanceGetTag () [inline], [protected]
Definition at line 548 of file reloc-info.h.
{ return *--pos_ & detail::kTagMask; }
References v8::internal::detail::kTagMask, and v8::internal::RelocIteratorBase< RelocInfoT >::pos_.
AdvanceReadInt()
template<typename RelocInfoT >
void v8::internal::RelocIteratorBase< RelocInfoT >::AdvanceReadInt [protected]
Definition at line 105 of file reloc-info.cc.
                                                   {
  int x = 0;
  for (int i = 0; i < kIntSize; i++) {
    x |= static_cast<int>(*--pos_) << i * kBitsPerByte;
  }
  rinfo_.data_ = x;
}
References v8::internal::kBitsPerByte, and v8::internal::kIntSize.
AdvanceReadLongPCJump()
template<typename RelocInfoT >
void v8::internal::RelocIteratorBase< RelocInfoT >::AdvanceReadLongPCJump [protected]
Definition at line 114 of file reloc-info.cc.
                                                          {
  // Read the 32-kSmallPCDeltaBits most significant bits of the
  // pc jump as a VLQ encoded integer.
  uint32_t pc_jump = base::VLQDecodeUnsigned([this] { return *--pos_; });
  // The least significant kSmallPCDeltaBits bits will be added
  // later.
  rinfo_.pc_ += pc_jump << kSmallPCDeltaBits;
}
References v8::internal::detail::kSmallPCDeltaBits, and v8::base::VLQDecodeUnsigned().
AdvanceReadPC()
template<typename RelocInfoT >
void v8::internal::RelocIteratorBase< RelocInfoT >::AdvanceReadPC () [inline], [protected]
Definition at line 550 of file reloc-info.h.
{ rinfo_.pc_ += *--pos_; }
References v8::internal::RelocIteratorBase< RelocInfoT >::pos_, and v8::internal::RelocIteratorBase< RelocInfoT >::rinfo_.
done()
template<typename RelocInfoT >
bool v8::internal::RelocIteratorBase< RelocInfoT >::done () const [inline]
Definition at line 522 of file reloc-info.h.
{ return done_; }
References v8::internal::RelocIteratorBase< RelocInfoT >::done_.
Referenced by v8::internal::wasm::NativeModule::AddCodeForTesting(), v8::internal::wasm::NativeModule::AddCodeWithCodeSpace(), v8::internal::wasm::WasmImportWrapperCache::ModificationScope::AddWrapper(), v8::internal::ProfilerListener::AttachDeoptInlinedFrames(), v8::internal::compiler::CheckNoDeprecatedMaps(), v8::internal::Code::ClearEmbeddedObjectsAndJSDispatchHandles(), v8::internal::maglev::MaglevCodeGenerator::CollectRetainedMaps(), v8::internal::OptimizedCompilationJob::CollectRetainedMaps(), v8::internal::wasm::NativeModuleDeserializer::CopyAndRelocate(), v8::internal::wasm::WasmCode::Disassemble(), v8::internal::anonymous_namespace{embedded-data.cc}::EnsureRelocatable(), v8::internal::anonymous_namespace{embedded-data.cc}::FinalizeEmbeddedCodeTargets(), v8::internal::Deoptimizer::GetDeoptInfo(), v8::internal::Assembler::GrowBuffer(), v8::internal::Code::IsIsolateIndependent(), v8::internal::ObjectStatsCollectorImpl::RecordVirtualCodeDetails(), v8::internal::InstructionStream::Relocate(), v8::internal::InstructionStream::RelocateFromDesc(), v8::internal::InstructionStream::RelocateFromDescWriteBarriers(), v8::internal::SetupIsolateDelegate::ReplacePlaceholders(), v8::internal::RelocIteratorBase< RelocInfoT >::rinfo(), v8::internal::wasm::WasmCode::Validate(), v8::internal::ObjectVisitor::VisitRelocInfo(), and v8::internal::wasm::NativeModuleSerializer::WriteCode().
GetMode()
template<typename RelocInfoT >
RelocInfo::Mode v8::internal::RelocIteratorBase< RelocInfoT >::GetMode () const [inline], [protected]
Definition at line 542 of file reloc-info.h.
                                {
    return static_cast<RelocInfo::Mode>((*pos_ >> detail::kTagBits) &
                                        ((1 << detail::kLongTagBits) - 1));
  }
References v8::internal::detail::kLongTagBits, v8::internal::detail::kTagBits, and v8::internal::RelocIteratorBase< RelocInfoT >::pos_.
next()
template<typename RelocInfoT >
void v8::internal::RelocIteratorBase< RelocInfoT >::next
Definition at line 130 of file reloc-info.cc.
                                         {
  DCHECK(!done());
  // Basically, do the opposite of RelocInfoWriter::Write.
  // Reading of data is as far as possible avoided for unwanted modes,
  // but we must always update the pc.
  //
  // We exit this loop by returning when we find a mode we want.
  while (pos_ > end_) {
    int tag = AdvanceGetTag();
    if (tag == kEmbeddedObjectTag) {
      ReadShortTaggedPC();
      if (SetMode(RelocInfo::FULL_EMBEDDED_OBJECT)) return;
    } else if (tag == kCodeTargetTag) {
      ReadShortTaggedPC();
      if (SetMode(RelocInfo::CODE_TARGET)) return;
    } else if (tag == kWasmStubCallTag) {
      ReadShortTaggedPC();
      if (SetMode(RelocInfo::WASM_STUB_CALL)) return;
    } else {
      DCHECK_EQ(tag, kDefaultTag);
      RelocInfo::Mode rmode = GetMode();
      if (rmode == RelocInfo::PC_JUMP) {
        AdvanceReadLongPCJump();
      } else {
        AdvanceReadPC();
        if (RelocInfo::IsDeoptReason(rmode)) {
          Advance();
          if (SetMode(rmode)) {
            ReadShortData();
            return;
          }
        } else if (RelocInfo::IsConstPool(rmode) ||
                   RelocInfo::IsVeneerPool(rmode) ||
                   RelocInfo::IsDeoptId(rmode) ||
                   RelocInfo::IsDeoptPosition(rmode) ||
                   RelocInfo::IsDeoptNodeId(rmode)) {
          if (SetMode(rmode)) {
            AdvanceReadInt();
            return;
          }
          Advance(kIntSize);
        } else if (SetMode(static_cast<RelocInfo::Mode>(rmode))) {
          return;
        }
      }
    }
  }
  done_ = true;
}
References v8::internal::RelocInfo::CODE_TARGET, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::RelocInfo::FULL_EMBEDDED_OBJECT, v8::internal::RelocInfo::IsConstPool(), v8::internal::RelocInfo::IsDeoptId(), v8::internal::RelocInfo::IsDeoptNodeId(), v8::internal::RelocInfo::IsDeoptPosition(), v8::internal::RelocInfo::IsDeoptReason(), v8::internal::RelocInfo::IsVeneerPool(), v8::internal::detail::kCodeTargetTag, v8::internal::detail::kDefaultTag, v8::internal::detail::kEmbeddedObjectTag, v8::internal::kIntSize, v8::internal::detail::kWasmStubCallTag, v8::internal::RelocInfo::PC_JUMP, and v8::internal::RelocInfo::WASM_STUB_CALL.
Referenced by v8::internal::wasm::NativeModule::AddCodeForTesting(), v8::internal::anonymous_namespace{embedded-data.cc}::FinalizeEmbeddedCodeTargets(), v8::internal::RelocIteratorBase< RelocInfoT >::RelocIteratorBase(), v8::internal::ObjectVisitor::VisitRelocInfo(), and v8::internal::wasm::NativeModuleSerializer::WriteCode().
operator=()
template<typename RelocInfoT >
RelocIteratorBase& v8::internal::RelocIteratorBase< RelocInfoT >::operator= (const RelocIteratorBase< RelocInfoT > &) [delete]
ReadShortData()
template<typename RelocInfoT >
void v8::internal::RelocIteratorBase< RelocInfoT >::ReadShortData [inline], [protected]
Definition at line 124 of file reloc-info.cc.
                                                         {
  uint8_t unsigned_b = *pos_;
  rinfo_.data_ = unsigned_b;
}
ReadShortTaggedPC()
template<typename RelocInfoT >
void v8::internal::RelocIteratorBase< RelocInfoT >::ReadShortTaggedPC () [inline], [protected]
Definition at line 553 of file reloc-info.h.
{ rinfo_.pc_ += *pos_ >> detail::kTagBits; }
References v8::internal::detail::kTagBits, v8::internal::RelocIteratorBase< RelocInfoT >::pos_, and v8::internal::RelocIteratorBase< RelocInfoT >::rinfo_.
rinfo()
template<typename RelocInfoT >
RelocInfoT* v8::internal::RelocIteratorBase< RelocInfoT >::rinfo () [inline]
Definition at line 526 of file reloc-info.h.
                      {
    DCHECK(!done());
    return &rinfo_;
  }
References v8::internal::DCHECK(), v8::internal::RelocIteratorBase< RelocInfoT >::done(), and v8::internal::RelocIteratorBase< RelocInfoT >::rinfo_.
Referenced by v8::internal::wasm::NativeModule::AddCodeForTesting(), v8::internal::anonymous_namespace{embedded-data.cc}::FinalizeEmbeddedCodeTargets(), v8::internal::ObjectVisitor::VisitRelocInfo(), and v8::internal::wasm::NativeModuleSerializer::WriteCode().
SetMode()
template<typename RelocInfoT >
bool v8::internal::RelocIteratorBase< RelocInfoT >::SetMode (RelocInfo::Mode mode) [inline], [protected]
Definition at line 536 of file reloc-info.h.
                                   {
    if ((mode_mask_ & (1 << mode)) == 0) return false;
    rinfo_.rmode_ = mode;
    return true;
  }
References mode(), v8::internal::RelocIteratorBase< RelocInfoT >::mode_mask_, and v8::internal::RelocIteratorBase< RelocInfoT >::rinfo_.
Member Data Documentation
done_
template<typename RelocInfoT >
bool v8::internal::RelocIteratorBase< RelocInfoT >::done_ = false [protected]
Definition at line 559 of file reloc-info.h.
Referenced by v8::internal::RelocIteratorBase< RelocInfoT >::done().
end_
template<typename RelocInfoT >
const uint8_t* const v8::internal::RelocIteratorBase< RelocInfoT >::end_ [protected]
Definition at line 557 of file reloc-info.h.
Referenced by v8::internal::RelocIteratorBase< RelocInfoT >::RelocIteratorBase().
kAllModesMask
template<typename RelocInfoT >
constexpr int v8::internal::RelocIteratorBase< RelocInfoT >::kAllModesMask = -1 [static], [constexpr]
Definition at line 516 of file reloc-info.h.
mode_mask_
template<typename RelocInfoT >
const int v8::internal::RelocIteratorBase< RelocInfoT >::mode_mask_ [protected]
Definition at line 560 of file reloc-info.h.
Referenced by v8::internal::RelocIteratorBase< RelocInfoT >::RelocIteratorBase(), and v8::internal::RelocIteratorBase< RelocInfoT >::SetMode().
pos_
template<typename RelocInfoT >
const uint8_t* v8::internal::RelocIteratorBase< RelocInfoT >::pos_ [protected]
Definition at line 556 of file reloc-info.h.
Referenced by v8::internal::RelocIteratorBase< RelocInfoT >::Advance(), v8::internal::RelocIteratorBase< RelocInfoT >::AdvanceGetTag(), v8::internal::RelocIteratorBase< RelocInfoT >::AdvanceReadPC(), v8::internal::RelocIteratorBase< RelocInfoT >::GetMode(), v8::internal::RelocIteratorBase< RelocInfoT >::ReadShortTaggedPC(), and v8::internal::RelocIteratorBase< RelocInfoT >::RelocIteratorBase().
rinfo_
template<typename RelocInfoT >
RelocInfoT v8::internal::RelocIteratorBase< RelocInfoT >::rinfo_ [protected]
Definition at line 558 of file reloc-info.h.
Referenced by v8::internal::RelocIteratorBase< RelocInfoT >::AdvanceReadPC(), v8::internal::RelocIteratorBase< RelocInfoT >::ReadShortTaggedPC(), v8::internal::RelocIteratorBase< RelocInfoT >::rinfo(), and v8::internal::RelocIteratorBase< RelocInfoT >::SetMode().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/reloc-info.h
/mnt/V8SourceCode/src/codegen/reloc-info-inl.h
/mnt/V8SourceCode/src/codegen/reloc-info.cc