disasm::NameConverter Class Reference
#include <disasm.h>
Public Member Functions
virtual ~NameConverter ()=default
virtual const char * NameOfCPURegister (int reg) const
virtual const char * NameOfByteCPURegister (int reg) const
virtual const char * NameOfXMMRegister (int reg) const
virtual const char * NameOfAddress (uint8_t *addr) const
virtual const char * NameOfConstant (uint8_t *addr) const
virtual const char * NameInCode (uint8_t *addr) const
virtual const char * RootRelativeName (int offset) const
Protected Attributes
v8::base::EmbeddedVector< char, 128 > tmp_buffer_
Detailed Description
Definition at line 15 of file disasm.h.
Constructor & Destructor Documentation
 NameConverter()
virtual disasm::NameConverter::~NameConverter () [virtual], [default]
Member Function Documentation
NameInCode()
const char * disasm::NameConverter::NameInCode (uint8_t * addr) const [virtual]
Definition at line 3338 of file disasm-riscv.cc.
                                                         {
  // The default name converter is called for unknown code. So we will not try
  // to access any memory.
  return "";
}
NameOfAddress()
const char * disasm::NameConverter::NameOfAddress (uint8_t * addr) const [virtual]
Definition at line 3316 of file disasm-riscv.cc.
                                                            {
  v8::base::SNPrintF(tmp_buffer_, "%p", static_cast<void*>(addr));
  return tmp_buffer_.begin();
}
References v8::base::Vector< T >::begin(), v8::base::SNPrintF(), and tmp_buffer_.
Referenced by NameOfConstant(), v8::internal::Decoder< V >::PrintBranchOffset(), v8::internal::Decoder< V >::PrintImm20J(), and v8::internal::Decoder< V >::PrintTarget().
NameOfByteCPURegister()
const char * disasm::NameConverter::NameOfByteCPURegister (int reg) const [virtual]
Definition at line 3333 of file disasm-riscv.cc.
                                                              {
  UNREACHABLE(); // RISC-V does not have the concept of a byte register.
  // return "nobytereg";
}
References UNREACHABLE.
NameOfConstant()
const char * disasm::NameConverter::NameOfConstant (uint8_t * addr) const [virtual]
Definition at line 3321 of file disasm-riscv.cc.
                                                             {
  return NameOfAddress(addr);
}
References NameOfAddress().
NameOfCPURegister()
const char * disasm::NameConverter::NameOfCPURegister (int reg) const [virtual]
Definition at line 3325 of file disasm-riscv.cc.
                                                          {
  return v8::internal::Registers::Name(reg);
}
References v8::internal::Registers::Name().
Referenced by v8::internal::TranslatedState::CreateNextTranslatedValue(), v8::internal::DeoptimizationFrameTranslationPrintSingleOpcode(), and v8::internal::Decoder< V >::PrintRegister().
NameOfXMMRegister()
const char * disasm::NameConverter::NameOfXMMRegister (int reg) const [virtual]
Definition at line 3329 of file disasm-riscv.cc.
                                                          {
  return v8::internal::FPURegisters::Name(reg);
}
References v8::internal::FPURegisters::Name().
Referenced by v8::internal::Decoder< V >::PrintFPURegister().
RootRelativeName()
virtual const char* disasm::NameConverter::RootRelativeName (int offset) const [inline], [virtual]
Definition at line 29 of file disasm.h.
{ UNREACHABLE(); }
References UNREACHABLE.
Member Data Documentation
tmp_buffer_
v8::base::EmbeddedVector<char, 128> disasm::NameConverter::tmp_buffer_ [protected]
Definition at line 32 of file disasm.h.
Referenced by NameOfAddress().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/diagnostics/disasm.h
/mnt/V8SourceCode/src/diagnostics/riscv/disasm-riscv.cc