v8::internal::AsmJsScanner Class Reference
#include <asm-scanner.h>
Public Types
enum { kLocalsStart = -10000
, kGlobalsStart = 256
 }
using token_t = int32_t
Public Member Functions
AsmJsScanner (Utf16CharacterStream *stream)
token_t Token () const
size_t Position () const
void Next ()
void Rewind ()
const std::string & GetIdentifierString () const
bool IsPrecededByNewline () const
void Seek (size_t pos)
void EnterLocalScope ()
void EnterGlobalScope ()
void ResetLocals ()
bool IsLocal () const
bool IsGlobal () const
bool IsUnsigned () const
uint32_t AsUnsigned () const
bool IsDouble () const
double AsDouble () const
Static Public Member Functions
static bool IsLocal (token_t token)
static bool IsGlobal (token_t token)
static size_t LocalIndex (token_t token)
static size_t GlobalIndex (token_t token)
Static Public Attributes
static constexpr base::uc32 kEndOfInputU
Private Member Functions
void ConsumeIdentifier (base::uc32 ch)
void ConsumeNumber (base::uc32 ch)
bool ConsumeCComment ()
void ConsumeCPPComment ()
void ConsumeString (base::uc32 quote)
void ConsumeCompareOrShift (base::uc32 ch)
bool IsIdentifierStart (base::uc32 ch)
bool IsIdentifierPart (base::uc32 ch)
bool IsNumberStart (base::uc32 ch)
Private Attributes
Utf16CharacterStream * stream_
token_t token_
token_t preceding_token_
token_t next_token_
size_t position_
size_t preceding_position_
size_t next_position_
bool rewind_
std::string identifier_string_
bool in_local_scope_
std::unordered_map< std::string, token_t > local_names_
std::unordered_map< std::string, token_t > global_names_
std::unordered_map< std::string, token_t > property_names_
int global_count_
double double_value_
uint32_t unsigned_value_
bool preceded_by_newline_
Detailed Description
Definition at line 30 of file asm-scanner.h.
Member Typedef Documentation
token_t
using v8::internal::AsmJsScanner::token_t = int32_t
Definition at line 32 of file asm-scanner.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
kLocalsStart
kGlobalsStart
Definition at line 108 of file asm-scanner.h.
       {
    // [-10000-kMaxIdentifierCount, -10000) :: Local identifiers (counting
    // backwards)
    // [-10000 .. -1) :: Builtin tokens like keywords
    // (also includes some special
    // ones like end of input)
    // 0 .. 255 :: Single char tokens
    // 256 .. 256+kMaxIdentifierCount :: Global identifiers
    kLocalsStart = -10000,
#define V(name, _junk1, _junk2, _junk3) kToken_##name,
    STDLIB_MATH_FUNCTION_LIST(V)
    STDLIB_ARRAY_TYPE_LIST(V)
#undef V
#define V(name, _junk1) kToken_##name,
    STDLIB_MATH_VALUE_LIST(V)
#undef V
#define V(name) kToken_##name,
    STDLIB_OTHER_LIST(V)
    KEYWORD_NAME_LIST(V)
#undef V
#define V(rawname, name) kToken_##name,
    LONG_SYMBOL_NAME_LIST(V)
#undef V
#define V(name, value, string_name) name = value,
    SPECIAL_TOKEN_LIST(V)
#undef V
    kGlobalsStart = 256,
  };
Constructor & Destructor Documentation
AsmJsScanner()
v8::internal::AsmJsScanner::AsmJsScanner (Utf16CharacterStream * stream) [explicit]
Definition at line 24 of file asm-scanner.cc.
    : stream_(stream),
      token_(kUninitialized),
      preceding_token_(kUninitialized),
      next_token_(kUninitialized),
      position_(0),
      preceding_position_(0),
      next_position_(0),
      rewind_(false),
      in_local_scope_(false),
      global_count_(0),
      double_value_(0.0),
      unsigned_value_(0),
      preceded_by_newline_(false) {
#define V(name, _junk1, _junk2, _junk3) property_names_[#name] = kToken_##name;
  STDLIB_MATH_FUNCTION_LIST(V)
  STDLIB_ARRAY_TYPE_LIST(V)
#undef V
#define V(name, _junk1) property_names_[#name] = kToken_##name;
  STDLIB_MATH_VALUE_LIST(V)
#undef V
#define V(name) property_names_[#name] = kToken_##name;
  STDLIB_OTHER_LIST(V)
#undef V
#define V(name) global_names_[#name] = kToken_##name;
  KEYWORD_NAME_LIST(V)
#undef V
  Next();
}
References KEYWORD_NAME_LIST, v8::internal::kUninitialized, Next(), STDLIB_ARRAY_TYPE_LIST, STDLIB_MATH_FUNCTION_LIST, STDLIB_MATH_VALUE_LIST, and STDLIB_OTHER_LIST.
Member Function Documentation
AsDouble()
double v8::internal::AsmJsScanner::AsDouble () const [inline]
Definition at line 102 of file asm-scanner.h.
                          {
    DCHECK(IsDouble());
    return double_value_;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::wasm::AsmJsParser::CheckForDouble(), and Next().
AsUnsigned()
uint32_t v8::internal::AsmJsScanner::AsUnsigned () const [inline]
Definition at line 97 of file asm-scanner.h.
                              {
    DCHECK(IsUnsigned());
    return unsigned_value_;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::wasm::AsmJsParser::CheckForUnsigned(), v8::internal::wasm::AsmJsParser::CheckForUnsignedBelow(), v8::internal::wasm::AsmJsParser::CheckForZero(), Next(), and v8::internal::wasm::AsmJsParser::PeekForZero().
ConsumeCComment()
bool v8::internal::AsmJsScanner::ConsumeCComment () [private]
Definition at line 383 of file asm-scanner.cc.
                                   {
  for (;;) {
    base::uc32 ch = stream_->Advance();
    while (ch == '*') {
      ch = stream_->Advance();
      if (ch == '/') {
        return true;
      }
    }
    if (ch == '\n') {
      preceded_by_newline_ = true;
    }
    if (ch == kEndOfInputU) {
      return false;
    }
  }
}
References v8::internal::Utf16CharacterStream::Advance(), kEndOfInputU, preceded_by_newline_, and stream_.
Referenced by Next().
ConsumeCompareOrShift()
void v8::internal::AsmJsScanner::ConsumeCompareOrShift (base::uc32 ch) [private]
Definition at line 430 of file asm-scanner.cc.
                                                    {
  base::uc32 next_ch = stream_->Advance();
  if (next_ch == '=') {
    switch (ch) {
      case '<':
        token_ = kToken_LE;
        break;
      case '>':
        token_ = kToken_GE;
        break;
      case '=':
        token_ = kToken_EQ;
        break;
      case '!':
        token_ = kToken_NE;
        break;
      default:
        UNREACHABLE();
    }
  } else if (ch == '<' && next_ch == '<') {
    token_ = kToken_SHL;
  } else if (ch == '>' && next_ch == '>') {
    if (stream_->Advance() == '>') {
      token_ = kToken_SHR;
    } else {
      token_ = kToken_SAR;
      stream_->Back();
    }
  } else {
    stream_->Back();
    token_ = ch;
  }
}
References v8::internal::Utf16CharacterStream::Advance(), v8::internal::Utf16CharacterStream::Back(), stream_, token_, and v8::internal::UNREACHABLE().
Referenced by Next().
ConsumeCPPComment()
void v8::internal::AsmJsScanner::ConsumeCPPComment () [private]
Definition at line 401 of file asm-scanner.cc.
                                     {
  for (;;) {
    base::uc32 ch = stream_->Advance();
    if (ch == '\n') {
      preceded_by_newline_ = true;
      return;
    }
    if (ch == kEndOfInputU) {
      return;
    }
  }
}
References v8::internal::Utf16CharacterStream::Advance(), kEndOfInputU, preceded_by_newline_, and stream_.
Referenced by Next().
ConsumeIdentifier()
void v8::internal::AsmJsScanner::ConsumeIdentifier (base::uc32 ch) [private]
Definition at line 227 of file asm-scanner.cc.
                                                {
  // Consume characters while still part of the identifier.
  identifier_string_.clear();
  while (IsIdentifierPart(ch)) {
    identifier_string_ += ch;
    ch = stream_->Advance();
  }
  // Go back one for next time.
  stream_->Back();
  // Decode what the identifier means.
  if (preceding_token_ == '.') {
    auto i = property_names_.find(identifier_string_);
    if (i != property_names_.end()) {
      token_ = i->second;
      return;
    }
  } else {
    {
      auto i = local_names_.find(identifier_string_);
      if (i != local_names_.end()) {
        token_ = i->second;
        return;
      }
    }
    if (!in_local_scope_) {
      auto i = global_names_.find(identifier_string_);
      if (i != global_names_.end()) {
        token_ = i->second;
        return;
      }
    }
  }
  if (preceding_token_ == '.') {
    CHECK_LT(global_count_, kMaxIdentifierCount);
    token_ = kGlobalsStart + global_count_++;
    property_names_[identifier_string_] = token_;
  } else if (in_local_scope_) {
    CHECK_LT(local_names_.size(), kMaxIdentifierCount);
    token_ = kLocalsStart - static_cast<token_t>(local_names_.size());
    local_names_[identifier_string_] = token_;
  } else {
    CHECK_LT(global_count_, kMaxIdentifierCount);
    token_ = kGlobalsStart + global_count_++;
    global_names_[identifier_string_] = token_;
  }
}
References v8::internal::Utf16CharacterStream::Advance(), v8::internal::Utf16CharacterStream::Back(), CHECK_LT, global_count_, global_names_, identifier_string_, in_local_scope_, IsIdentifierPart(), kGlobalsStart, kLocalsStart, v8::internal::anonymous_namespace{asm-scanner.cc}::kMaxIdentifierCount, local_names_, preceding_token_, property_names_, stream_, and token_.
Referenced by Next().
ConsumeNumber()
void v8::internal::AsmJsScanner::ConsumeNumber (base::uc32 ch) [private]
Definition at line 282 of file asm-scanner.cc.
                                            {
  std::string number;
  number.assign(1, ch);
  bool has_dot = ch == '.';
  bool has_prefix = false;
  for (;;) {
    ch = stream_->Advance();
    if ((ch >= '0' && ch <= '9') || (ch >= 'a' && ch <= 'f') ||
        (ch >= 'A' && ch <= 'F') || ch == '.' || ch == 'b' || ch == 'o' ||
        ch == 'x' ||
        ((ch == '-' || ch == '+') && !has_prefix &&
         (number[number.size() - 1] == 'e' ||
          number[number.size() - 1] == 'E'))) {
      // TODO(bradnelson): Test weird cases ending in -.
      if (ch == '.') {
        has_dot = true;
      }
      if (ch == 'b' || ch == 'o' || ch == 'x') {
        has_prefix = true;
      }
      number.push_back(ch);
    } else {
      break;
    }
  }
  stream_->Back();
  // Special case the most common number.
  if (number.size() == 1 && number[0] == '0') {
    unsigned_value_ = 0;
    token_ = kUnsigned;
    return;
  }
  // Pick out dot.
  if (number.size() == 1 && number[0] == '.') {
    token_ = '.';
    return;
  }
  // Decode numbers, with seperate paths for prefixes and implicit octals.
  if (has_prefix && number[0] == '0') {
    // "0[xob]" by itself is a parse error.
    if (number.size() <= 2) {
      token_ = kParseError;
      return;
    }
    switch (number[1]) {
      case 'b':
        double_value_ = BinaryStringToDouble(
            base::Vector<const uint8_t>::cast(base::VectorOf(number)));
        break;
      case 'o':
        double_value_ = OctalStringToDouble(
            base::Vector<const uint8_t>::cast(base::VectorOf(number)));
        break;
      case 'x':
        double_value_ = HexStringToDouble(
            base::Vector<const uint8_t>::cast(base::VectorOf(number)));
        break;
      default:
        // If there is a prefix character, but it's not the second character,
        // then there's a parse error somewhere.
        token_ = kParseError;
        break;
    }
  } else if (number[0] == '0' && !has_prefix && IsValidImplicitOctal(number)) {
    double_value_ = ImplicitOctalStringToDouble(
        base::Vector<const uint8_t>::cast(base::VectorOf(number)));
  } else {
    double_value_ = StringToDouble(
        base::Vector<const uint8_t>::cast(base::VectorOf(number)),
        NO_CONVERSION_FLAG);
  }
  if (std::isnan(double_value_)) {
    // Check if string to number conversion didn't consume all the characters.
    // This happens if the character filter let through something invalid
    // like: 0123ef for example.
    // TODO(bradnelson): Check if this happens often enough to be a perf
    // problem.
    if (number[0] == '.') {
      for (size_t k = 1; k < number.size(); ++k) {
        stream_->Back();
      }
      token_ = '.';
      return;
    }
    // Anything else that doesn't parse is an error.
    token_ = kParseError;
    return;
  }
  if (has_dot || trunc(double_value_) != double_value_) {
    token_ = kDouble;
  } else {
    // Exceeding safe integer range is an error.
    if (double_value_ > static_cast<double>(kMaxUInt32)) {
      token_ = kParseError;
      return;
    }
    unsigned_value_ = static_cast<uint32_t>(double_value_);
    token_ = kUnsigned;
  }
}
References v8::internal::Utf16CharacterStream::Advance(), v8::internal::Utf16CharacterStream::Back(), v8::internal::BinaryStringToDouble(), double_value_, v8::internal::HexStringToDouble(), v8::internal::ImplicitOctalStringToDouble(), v8::internal::anonymous_namespace{asm-scanner.cc}::IsValidImplicitOctal(), v8::internal::kMaxUInt32, v8::internal::NO_CONVERSION_FLAG, v8::internal::OctalStringToDouble(), stream_, v8::internal::string, v8::internal::StringToDouble(), token_, unsigned_value_, and v8::base::VectorOf().
Referenced by Next().
ConsumeString()
void v8::internal::AsmJsScanner::ConsumeString (base::uc32 quote) [private]
Definition at line 414 of file asm-scanner.cc.
                                               {
  // Only string allowed is 'use asm' / "use asm".
  const char* expected = "use asm";
  for (; *expected != '\0'; ++expected) {
    if (stream_->Advance() != static_cast<base::uc32>(*expected)) {
      token_ = kParseError;
      return;
    }
  }
  if (stream_->Advance() != quote) {
    token_ = kParseError;
    return;
  }
  token_ = kToken_UseAsm;
}
References v8::internal::Utf16CharacterStream::Advance(), stream_, and token_.
Referenced by Next().
EnterGlobalScope()
void v8::internal::AsmJsScanner::EnterGlobalScope () [inline]
Definition at line 73 of file asm-scanner.h.
{ in_local_scope_ = false; }
Referenced by v8::internal::wasm::AsmJsParser::ValidateFunctionLocals(), and v8::internal::wasm::AsmJsParser::ValidateFunctionParams().
EnterLocalScope()
void v8::internal::AsmJsScanner::EnterLocalScope () [inline]
Definition at line 72 of file asm-scanner.h.
{ in_local_scope_ = true; }
Referenced by v8::internal::wasm::AsmJsParser::ValidateFunctionLocals(), and v8::internal::wasm::AsmJsParser::ValidateFunctionParams().
GetIdentifierString()
const std::string& v8::internal::AsmJsScanner::GetIdentifierString () const [inline]
Definition at line 47 of file asm-scanner.h.
                                               {
    // Identifier strings don't work after a rewind.
    DCHECK(!rewind_);
    return identifier_string_;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::wasm::AsmJsParser::CopyCurrentIdentifierString().
GlobalIndex()
static size_t v8::internal::AsmJsScanner::GlobalIndex (token_t token) [inline], [static]
Definition at line 88 of file asm-scanner.h.
                                           {
    DCHECK(IsGlobal(token));
    return token - kGlobalsStart;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::wasm::AsmJsParser::GetVarInfo().
IsDouble()
bool v8::internal::AsmJsScanner::IsDouble () const [inline]
Definition at line 101 of file asm-scanner.h.
{ return Token() == kDouble; }
Referenced by v8::internal::wasm::AsmJsParser::CheckForDouble().
IsGlobal() [1/2]
bool v8::internal::AsmJsScanner::IsGlobal () const [inline]
Definition at line 79 of file asm-scanner.h.
{ return IsGlobal(Token()); }
References IsGlobal().
Referenced by v8::internal::wasm::AsmJsParser::AssignmentExpression(), v8::internal::wasm::AsmJsParser::BreakStatement(), v8::internal::wasm::AsmJsParser::CallExpression(), v8::internal::wasm::AsmJsParser::ContinueStatement(), v8::internal::wasm::AsmJsParser::ExpressionStatement(), v8::internal::wasm::AsmJsParser::GetVarInfo(), v8::internal::wasm::AsmJsParser::Identifier(), IsGlobal(), v8::internal::wasm::AsmJsParser::LabelledStatement(), v8::internal::wasm::AsmJsParser::PeekCall(), v8::internal::wasm::AsmJsParser::ValidateExport(), v8::internal::wasm::AsmJsParser::ValidateFloatCoercion(), v8::internal::wasm::AsmJsParser::ValidateFunction(), v8::internal::wasm::AsmJsParser::ValidateFunctionLocals(), v8::internal::wasm::AsmJsParser::ValidateFunctionParams(), v8::internal::wasm::AsmJsParser::ValidateFunctionTable(), v8::internal::wasm::AsmJsParser::ValidateModuleParameters(), and v8::internal::wasm::AsmJsParser::ValidateModuleVar().
IsGlobal() [2/2]
static bool v8::internal::AsmJsScanner::IsGlobal (token_t token) [inline], [static]
Definition at line 81 of file asm-scanner.h.
{ return token >= kGlobalsStart; }
IsIdentifierPart()
bool v8::internal::AsmJsScanner::IsIdentifierPart (base::uc32 ch) [private]
Definition at line 469 of file asm-scanner.cc.
                                               {
  return IsAsciiIdentifier(ch);
}
References v8::internal::IsAsciiIdentifier().
Referenced by ConsumeIdentifier().
IsIdentifierStart()
bool v8::internal::AsmJsScanner::IsIdentifierStart (base::uc32 ch) [private]
Definition at line 464 of file asm-scanner.cc.
                                                {
  return base::IsInRange(AsciiAlphaToLower(ch), 'a', 'z') || ch == '_' ||
         ch == '$';
}
References v8::internal::AsciiAlphaToLower().
Referenced by Next().
IsLocal() [1/2]
bool v8::internal::AsmJsScanner::IsLocal () const [inline]
Definition at line 78 of file asm-scanner.h.
{ return IsLocal(Token()); }
References IsLocal().
Referenced by v8::internal::wasm::AsmJsParser::AssignmentExpression(), v8::internal::wasm::AsmJsParser::BreakStatement(), v8::internal::wasm::AsmJsParser::CallExpression(), v8::internal::wasm::AsmJsParser::ContinueStatement(), v8::internal::wasm::AsmJsParser::ExpressionStatement(), v8::internal::wasm::AsmJsParser::GetVarInfo(), v8::internal::wasm::AsmJsParser::Identifier(), IsLocal(), v8::internal::wasm::AsmJsParser::LabelledStatement(), v8::internal::wasm::AsmJsParser::ValidateExport(), v8::internal::wasm::AsmJsParser::ValidateFunctionLocals(), and v8::internal::wasm::AsmJsParser::ValidateFunctionParams().
IsLocal() [2/2]
static bool v8::internal::AsmJsScanner::IsLocal (token_t token) [inline], [static]
Definition at line 80 of file asm-scanner.h.
{ return token <= kLocalsStart; }
IsNumberStart()
bool v8::internal::AsmJsScanner::IsNumberStart (base::uc32 ch) [private]
Definition at line 473 of file asm-scanner.cc.
                                            {
  return ch == '.' || IsDecimalDigit(ch);
}
References v8::internal::IsDecimalDigit().
Referenced by Next().
IsPrecededByNewline()
bool v8::internal::AsmJsScanner::IsPrecededByNewline () const [inline]
Definition at line 54 of file asm-scanner.h.
                                   {
    // Newline tracking doesn't work if you back up.
    DCHECK(!rewind_);
    return preceded_by_newline_;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::wasm::AsmJsParser::SkipSemicolon().
IsUnsigned()
bool v8::internal::AsmJsScanner::IsUnsigned () const [inline]
Definition at line 96 of file asm-scanner.h.
{ return Token() == kUnsigned; }
Referenced by v8::internal::wasm::AsmJsParser::CheckForUnsigned(), v8::internal::wasm::AsmJsParser::CheckForUnsignedBelow(), v8::internal::wasm::AsmJsParser::CheckForZero(), and v8::internal::wasm::AsmJsParser::PeekForZero().
LocalIndex()
static size_t v8::internal::AsmJsScanner::LocalIndex (token_t token) [inline], [static]
Definition at line 84 of file asm-scanner.h.
                                          {
    DCHECK(IsLocal(token));
    return -(token - kLocalsStart);
  }
References v8::internal::DCHECK().
Referenced by v8::internal::wasm::AsmJsParser::GetVarInfo().
Next()
void v8::internal::AsmJsScanner::Next ()
Definition at line 54 of file asm-scanner.cc.
                        {
  if (rewind_) {
    preceding_token_ = token_;
    preceding_position_ = position_;
    token_ = next_token_;
    position_ = next_position_;
    next_token_ = kUninitialized;
    next_position_ = 0;
    rewind_ = false;
    return;
  }
  if (token_ == kEndOfInput || token_ == kParseError) {
    return;
  }
#if DEBUG
  if (v8_flags.trace_asm_scanner) {
    if (Token() == kDouble) {
      PrintF("%lf ", AsDouble());
    } else if (Token() == kUnsigned) {
      PrintF("%" PRIu32 " ", AsUnsigned());
    } else {
      std::string name = Name(Token());
      PrintF("%s ", name.c_str());
    }
  }
#endif
  preceded_by_newline_ = false;
  preceding_token_ = token_;
  preceding_position_ = position_;
  for (;;) {
    position_ = stream_->pos();
    base::uc32 ch = stream_->Advance();
    switch (ch) {
      case ' ':
      case '\t':
      case '\r':
        // Ignore whitespace.
        break;
      case '\n':
        // Track when we've passed a newline for optional semicolon support,
        // but keep scanning.
        preceded_by_newline_ = true;
        break;
      case kEndOfInputU:
        token_ = kEndOfInput;
        return;
      case '\'':
      case '"':
        ConsumeString(ch);
        return;
      case '/':
        ch = stream_->Advance();
        if (ch == '/') {
          ConsumeCPPComment();
        } else if (ch == '*') {
          if (!ConsumeCComment()) {
            token_ = kParseError;
            return;
          }
        } else {
          stream_->Back();
          token_ = '/';
          return;
        }
        // Breaks out of switch, but loops again (i.e. the case when we parsed
        // a comment, but need to continue to look for the next token).
        break;
      case '<':
      case '>':
      case '=':
      case '!':
        ConsumeCompareOrShift(ch);
        return;
#define V(single_char_token) case single_char_token:
        SIMPLE_SINGLE_TOKEN_LIST(V)
#undef V
        // Use fixed token IDs for ASCII.
        token_ = ch;
        return;
      default:
        if (IsIdentifierStart(ch)) {
          ConsumeIdentifier(ch);
        } else if (IsNumberStart(ch)) {
          ConsumeNumber(ch);
        } else {
          // TODO(bradnelson): Support unicode (probably via UnicodeCache).
          token_ = kParseError;
        }
        return;
    }
  }
}
References v8::internal::Utf16CharacterStream::Advance(), AsDouble(), AsUnsigned(), v8::internal::Utf16CharacterStream::Back(), ConsumeCComment(), ConsumeCompareOrShift(), ConsumeCPPComment(), ConsumeIdentifier(), ConsumeNumber(), ConsumeString(), IsIdentifierStart(), IsNumberStart(), kEndOfInputU, v8::internal::kUninitialized, v8::internal::name, next_position_, next_token_, v8::internal::Utf16CharacterStream::pos(), position_, preceded_by_newline_, preceding_position_, preceding_token_, v8::internal::PrintF(), rewind_, SIMPLE_SINGLE_TOKEN_LIST, stream_, v8::internal::string, Token(), token_, and v8::internal::v8_flags.
Referenced by AsmJsScanner(), v8::internal::wasm::AsmJsParser::AssignmentExpression(), v8::internal::wasm::AsmJsParser::Check(), v8::internal::wasm::AsmJsParser::CheckForDouble(), v8::internal::wasm::AsmJsParser::CheckForUnsigned(), v8::internal::wasm::AsmJsParser::CheckForUnsignedBelow(), v8::internal::wasm::AsmJsParser::CheckForZero(), v8::internal::wasm::AsmJsParser::Consume(), v8::internal::wasm::AsmJsParser::ExpressionStatement(), v8::internal::wasm::AsmJsParser::GatherCases(), v8::internal::wasm::AsmJsParser::LabelledStatement(), v8::internal::wasm::AsmJsParser::PeekCall(), v8::internal::wasm::AsmJsParser::ScanToClosingParenthesis(), Seek(), v8::internal::wasm::AsmJsParser::UnaryExpression(), v8::internal::wasm::AsmJsParser::ValidateFloatCoercion(), and v8::internal::wasm::AsmJsParser::ValidateModuleVarImport().
Position()
size_t v8::internal::AsmJsScanner::Position () const [inline]
Definition at line 39 of file asm-scanner.h.
{ return position_; }
Referenced by v8::internal::wasm::AsmJsParser::BitwiseORExpression(), v8::internal::wasm::AsmJsParser::ForStatement(), v8::internal::wasm::AsmJsParser::GatherCases(), v8::internal::wasm::AsmJsParser::Loop(), v8::internal::wasm::AsmJsParser::ShiftExpression(), v8::internal::wasm::AsmJsParser::UnaryExpression(), v8::internal::wasm::AsmJsParser::ValidateCall(), v8::internal::wasm::AsmJsParser::ValidateFloatCoercion(), and v8::internal::wasm::AsmJsParser::ValidateFunction().
ResetLocals()
void v8::internal::AsmJsScanner::ResetLocals ()
Definition at line 174 of file asm-scanner.cc.
{ local_names_.clear(); }
References local_names_.
Referenced by v8::internal::wasm::AsmJsParser::ValidateFunction().
Rewind()
void v8::internal::AsmJsScanner::Rewind ()
Definition at line 158 of file asm-scanner.cc.
                          {
  DCHECK_NE(kUninitialized, preceding_token_);
  // TODO(bradnelson): Currently rewinding needs to leave in place the
  // preceding newline state (in case a |0 ends a line).
  // This is weird and stateful, fix me.
  DCHECK(!rewind_);
  next_token_ = token_;
  next_position_ = position_;
  token_ = preceding_token_;
  position_ = preceding_position_;
  preceding_token_ = kUninitialized;
  preceding_position_ = 0;
  rewind_ = true;
  identifier_string_.clear();
}
References v8::internal::DCHECK(), DCHECK_NE, identifier_string_, v8::internal::kUninitialized, next_position_, next_token_, position_, preceding_position_, preceding_token_, rewind_, and token_.
Referenced by v8::internal::wasm::AsmJsParser::AssignmentExpression(), v8::internal::wasm::AsmJsParser::BitwiseORExpression(), v8::internal::wasm::AsmJsParser::ExpressionStatement(), v8::internal::wasm::AsmJsParser::MultiplicativeExpression(), v8::internal::wasm::AsmJsParser::PeekCall(), v8::internal::wasm::AsmJsParser::ShiftExpression(), and v8::internal::wasm::AsmJsParser::ValidateHeapAccess().
Seek()
void v8::internal::AsmJsScanner::Seek (size_t pos)
Definition at line 215 of file asm-scanner.cc.
                                  {
  stream_->Seek(pos);
  preceding_token_ = kUninitialized;
  token_ = kUninitialized;
  next_token_ = kUninitialized;
  preceding_position_ = 0;
  position_ = 0;
  next_position_ = 0;
  rewind_ = false;
  Next();
}
References v8::internal::kUninitialized, Next(), next_position_, next_token_, position_, preceding_position_, preceding_token_, rewind_, v8::internal::Utf16CharacterStream::Seek(), stream_, and token_.
Referenced by v8::internal::wasm::AsmJsParser::ForStatement(), and v8::internal::wasm::AsmJsParser::GatherCases().
Token()
token_t v8::internal::AsmJsScanner::Token () const [inline]
Definition at line 37 of file asm-scanner.h.
{ return token_; }
Referenced by v8::internal::wasm::AsmJsParser::AssignmentExpression(), v8::internal::wasm::AsmJsParser::CallExpression(), v8::internal::wasm::AsmJsParser::Check(), v8::internal::wasm::AsmJsParser::Consume(), v8::internal::wasm::AsmJsParser::EqualityExpression(), v8::internal::wasm::AsmJsParser::LabelledStatement(), Next(), v8::internal::wasm::AsmJsParser::Peek(), v8::internal::wasm::AsmJsParser::PeekCall(), v8::internal::wasm::AsmJsParser::RelationalExpression(), v8::internal::wasm::AsmJsParser::ShiftExpression(), and v8::internal::wasm::AsmJsParser::ValidateFloatCoercion().
Member Data Documentation
double_value_
double v8::internal::AsmJsScanner::double_value_ [private]
Definition at line 156 of file asm-scanner.h.
Referenced by ConsumeNumber().
global_count_
int v8::internal::AsmJsScanner::global_count_ [private]
Definition at line 155 of file asm-scanner.h.
Referenced by ConsumeIdentifier().
global_names_
std::unordered_map<std::string, token_t> v8::internal::AsmJsScanner::global_names_ [private]
Definition at line 153 of file asm-scanner.h.
Referenced by ConsumeIdentifier().
identifier_string_
std::string v8::internal::AsmJsScanner::identifier_string_ [private]
Definition at line 150 of file asm-scanner.h.
Referenced by ConsumeIdentifier(), and Rewind().
in_local_scope_
bool v8::internal::AsmJsScanner::in_local_scope_ [private]
Definition at line 151 of file asm-scanner.h.
Referenced by ConsumeIdentifier().
kEndOfInputU
constexpr base::uc32 v8::internal::AsmJsScanner::kEndOfInputU [static], [constexpr]
Initial value:
=
      static_cast<base::uc32>(kEndOfInput)
Definition at line 138 of file asm-scanner.h.
Referenced by ConsumeCComment(), ConsumeCPPComment(), and Next().
local_names_
std::unordered_map<std::string, token_t> v8::internal::AsmJsScanner::local_names_ [private]
Definition at line 152 of file asm-scanner.h.
Referenced by ConsumeIdentifier(), and ResetLocals().
next_position_
size_t v8::internal::AsmJsScanner::next_position_ [private]
Definition at line 148 of file asm-scanner.h.
Referenced by Next(), Rewind(), and Seek().
next_token_
token_t v8::internal::AsmJsScanner::next_token_ [private]
Definition at line 145 of file asm-scanner.h.
Referenced by Next(), Rewind(), and Seek().
position_
size_t v8::internal::AsmJsScanner::position_ [private]
Definition at line 146 of file asm-scanner.h.
Referenced by Next(), Rewind(), and Seek().
preceded_by_newline_
bool v8::internal::AsmJsScanner::preceded_by_newline_ [private]
Definition at line 158 of file asm-scanner.h.
Referenced by ConsumeCComment(), ConsumeCPPComment(), and Next().
preceding_position_
size_t v8::internal::AsmJsScanner::preceding_position_ [private]
Definition at line 147 of file asm-scanner.h.
Referenced by Next(), Rewind(), and Seek().
preceding_token_
token_t v8::internal::AsmJsScanner::preceding_token_ [private]
Definition at line 144 of file asm-scanner.h.
Referenced by ConsumeIdentifier(), Next(), Rewind(), and Seek().
property_names_
std::unordered_map<std::string, token_t> v8::internal::AsmJsScanner::property_names_ [private]
Definition at line 154 of file asm-scanner.h.
Referenced by ConsumeIdentifier().
rewind_
bool v8::internal::AsmJsScanner::rewind_ [private]
Definition at line 149 of file asm-scanner.h.
Referenced by Next(), Rewind(), and Seek().
stream_
Utf16CharacterStream* v8::internal::AsmJsScanner::stream_ [private]
Definition at line 142 of file asm-scanner.h.
Referenced by ConsumeCComment(), ConsumeCompareOrShift(), ConsumeCPPComment(), ConsumeIdentifier(), ConsumeNumber(), ConsumeString(), Next(), and Seek().
token_
token_t v8::internal::AsmJsScanner::token_ [private]
Definition at line 143 of file asm-scanner.h.
Referenced by ConsumeCompareOrShift(), ConsumeIdentifier(), ConsumeNumber(), ConsumeString(), Next(), Rewind(), and Seek().
unsigned_value_
uint32_t v8::internal::AsmJsScanner::unsigned_value_ [private]
Definition at line 157 of file asm-scanner.h.
Referenced by ConsumeNumber().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/asmjs/asm-scanner.h
/mnt/V8SourceCode/src/asmjs/asm-scanner.cc