v8::internal::ObjectDescriptor< IsolateT > Class Template Reference
Public Member Functions
void IncComputedCount ()
void IncPropertiesCount ()
void IncElementsCount ()
ObjectDescriptor (int property_slack)
bool HasDictionaryProperties () const
Handle< Object > properties_template () const
Handle< NumberDictionary > elements_template () const
Handle< FixedArray > computed_properties () const
void CreateTemplates (IsolateT *isolate)
void AddConstant (IsolateT *isolate, DirectHandle< Name > name, DirectHandle< Object > value, PropertyAttributes attribs)
void AddNamedProperty (IsolateT *isolate, Handle< Name > name, ClassBoilerplate::ValueKind value_kind, int value_index)
void AddIndexedProperty (IsolateT *isolate, uint32_t element, ClassBoilerplate::ValueKind value_kind, int value_index)
void AddComputed (ClassBoilerplate::ValueKind value_kind, int key_index)
void UpdateNextEnumerationIndex (int value_index)
void Finalize (IsolateT *isolate)
Private Member Functions
Handle< NameDictionary > properties_dictionary_template () const
Handle< SwissNameDictionary > properties_ordered_dictionary_template () const
Private Attributes
const int property_slack_
int property_count_ = 0
int next_enumeration_index_ = PropertyDetails::kInitialIndex
int element_count_ = 0
int computed_count_ = 0
int current_computed_index_ = 0
Handle< DescriptorArray > descriptor_array_template_
Handle< HeapObject > properties_dictionary_template_
Handle< NumberDictionary > elements_dictionary_template_
Handle< FixedArray > computed_properties_
Handle< Object > temp_handle_
Detailed Description
template<typename IsolateT>
class v8::internal::ObjectDescriptor< IsolateT >
Definition at line 465 of file literal-objects.cc.
Constructor & Destructor Documentation
ObjectDescriptor()
template<typename IsolateT >
v8::internal::ObjectDescriptor< IsolateT >::ObjectDescriptor (int property_slack) [inline], [explicit]
Definition at line 471 of file literal-objects.cc.
      : property_slack_(property_slack) {}
Member Function Documentation
AddComputed()
template<typename IsolateT >
void v8::internal::ObjectDescriptor< IsolateT >::AddComputed (ClassBoilerplate::ValueKind value_kind, int key_index) [inline]
Definition at line 594 of file literal-objects.cc.
                                                                        {
    int value_index = key_index + 1;
    UpdateNextEnumerationIndex(value_index);
    int flags = EncodeComputedEntry(value_kind, key_index);
    computed_properties_->set(current_computed_index_++, Smi::FromInt(flags));
  }
References v8::internal::ObjectDescriptor< IsolateT >::computed_properties_, v8::internal::ObjectDescriptor< IsolateT >::current_computed_index_, v8::internal::anonymous_namespace{literal-objects.cc}::EncodeComputedEntry(), v8::internal::flags, v8::internal::Smi::FromInt(), and v8::internal::ObjectDescriptor< IsolateT >::UpdateNextEnumerationIndex().
Referenced by v8::internal::ClassBoilerplate::New().
AddConstant()
template<typename IsolateT >
void v8::internal::ObjectDescriptor< IsolateT >::AddConstant (IsolateT * isolate, DirectHandle< Name > name, DirectHandle< Object > value, PropertyAttributes attribs) [inline]
Definition at line 534 of file literal-objects.cc.
                                                                           {
    bool is_accessor = IsAccessorInfo(*value);
    DCHECK(!IsAccessorPair(*value));
    if (HasDictionaryProperties()) {
      PropertyKind kind =
          is_accessor ? i::PropertyKind::kAccessor : i::PropertyKind::kData;
      int enum_order = V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL
                           ? kDummyEnumerationIndex
                           : next_enumeration_index_++;
      PropertyDetails details(kind, attribs, PropertyCellType::kNoCell,
                              enum_order);
      if (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
        properties_dictionary_template_ =
            DictionaryAddNoUpdateNextEnumerationIndex(
                isolate, properties_ordered_dictionary_template(), name, value,
                details);
      } else {
        properties_dictionary_template_ =
            DictionaryAddNoUpdateNextEnumerationIndex(
                isolate, properties_dictionary_template(), name, value,
                details);
      }
    } else {
      Descriptor d = is_accessor
                         ? Descriptor::AccessorConstant(name, value, attribs)
                         : Descriptor::DataConstant(name, value, attribs);
      descriptor_array_template_->Append(&d);
    }
  }
References v8::internal::Descriptor::AccessorConstant(), v8::internal::Descriptor::DataConstant(), v8::internal::DCHECK(), v8::internal::ObjectDescriptor< IsolateT >::descriptor_array_template_, v8::internal::anonymous_namespace{literal-objects.cc}::DictionaryAddNoUpdateNextEnumerationIndex(), v8::internal::ObjectDescriptor< IsolateT >::HasDictionaryProperties(), v8::internal::kData, v8::internal::anonymous_namespace{literal-objects.cc}::kDummyEnumerationIndex, v8::internal::kNoCell, v8::internal::name, v8::internal::ObjectDescriptor< IsolateT >::next_enumeration_index_, v8::internal::ObjectDescriptor< IsolateT >::properties_dictionary_template(), v8::internal::ObjectDescriptor< IsolateT >::properties_dictionary_template_, v8::internal::ObjectDescriptor< IsolateT >::properties_ordered_dictionary_template(), V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL, and v8::internal::value.
Referenced by v8::internal::ClassBoilerplate::New().
AddIndexedProperty()
template<typename IsolateT >
void v8::internal::ObjectDescriptor< IsolateT >::AddIndexedProperty (IsolateT * isolate, uint32_t element, ClassBoilerplate::ValueKind value_kind, int value_index) [inline]
Definition at line 586 of file literal-objects.cc.
                                           {
    Tagged<Smi> value = Smi::FromInt(value_index);
    AddToDictionaryTemplate(isolate, elements_dictionary_template_, element,
                            value_index, value_kind, value);
  }
References v8::internal::anonymous_namespace{literal-objects.cc}::AddToDictionaryTemplate(), v8::internal::ObjectDescriptor< IsolateT >::elements_dictionary_template_, v8::internal::Smi::FromInt(), and v8::internal::value.
Referenced by v8::internal::ClassBoilerplate::New().
AddNamedProperty()
template<typename IsolateT >
void v8::internal::ObjectDescriptor< IsolateT >::AddNamedProperty (IsolateT * isolate, Handle< Name > name, ClassBoilerplate::ValueKind value_kind, int value_index) [inline]
Definition at line 565 of file literal-objects.cc.
                                         {
    Tagged<Smi> value = Smi::FromInt(value_index);
    if (HasDictionaryProperties()) {
      UpdateNextEnumerationIndex(value_index);
      if (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
        AddToDictionaryTemplate(isolate,
                                properties_ordered_dictionary_template(), name,
                                value_index, value_kind, value);
      } else {
        AddToDictionaryTemplate(isolate, properties_dictionary_template(), name,
                                value_index, value_kind, value);
      }
    } else {
      temp_handle_.PatchValue(value);
      AddToDescriptorArrayTemplate(isolate, descriptor_array_template_, name,
                                   value_kind, temp_handle_);
    }
  }
References v8::internal::anonymous_namespace{literal-objects.cc}::AddToDescriptorArrayTemplate(), v8::internal::anonymous_namespace{literal-objects.cc}::AddToDictionaryTemplate(), v8::internal::ObjectDescriptor< IsolateT >::descriptor_array_template_, v8::internal::Smi::FromInt(), v8::internal::ObjectDescriptor< IsolateT >::HasDictionaryProperties(), v8::internal::name, v8::internal::Handle< T >::PatchValue(), v8::internal::ObjectDescriptor< IsolateT >::properties_dictionary_template(), v8::internal::ObjectDescriptor< IsolateT >::properties_ordered_dictionary_template(), v8::internal::ObjectDescriptor< IsolateT >::temp_handle_, v8::internal::ObjectDescriptor< IsolateT >::UpdateNextEnumerationIndex(), V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL, and v8::internal::value.
Referenced by v8::internal::ClassBoilerplate::New().
computed_properties()
template<typename IsolateT >
Handle<FixedArray> v8::internal::ObjectDescriptor< IsolateT >::computed_properties () const [inline]
Definition at line 488 of file literal-objects.cc.
                                                 {
    return computed_properties_;
  }
References v8::internal::ObjectDescriptor< IsolateT >::computed_properties_.
Referenced by v8::internal::ClassBoilerplate::New().
CreateTemplates()
template<typename IsolateT >
void v8::internal::ObjectDescriptor< IsolateT >::CreateTemplates (IsolateT * isolate) [inline]
Definition at line 492 of file literal-objects.cc.
                                          {
    auto* factory = isolate->factory();
    descriptor_array_template_ = factory->empty_descriptor_array();
    if (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
      properties_dictionary_template_ =
          factory->empty_swiss_property_dictionary();
    } else {
      properties_dictionary_template_ = factory->empty_property_dictionary();
    }
    if (property_count_ || computed_count_ || property_slack_) {
      if (HasDictionaryProperties()) {
        int need_space_for =
            property_count_ + computed_count_ + property_slack_;
        if (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
          properties_dictionary_template_ =
              isolate->factory()->NewSwissNameDictionary(need_space_for,
                                                         AllocationType::kOld);
        } else {
          properties_dictionary_template_ = NameDictionary::New(
              isolate, need_space_for, AllocationType::kOld);
        }
      } else {
        descriptor_array_template_ = DescriptorArray::Allocate(
            isolate, 0, property_count_ + property_slack_,
            AllocationType::kOld);
      }
    }
    elements_dictionary_template_ =
        element_count_ || computed_count_
            ? NumberDictionary::New(isolate, element_count_ + computed_count_,
                                    AllocationType::kOld)
            : factory->empty_slow_element_dictionary();
    computed_properties_ =
        computed_count_
            ? factory->NewFixedArray(computed_count_, AllocationType::kOld)
            : factory->empty_fixed_array();
    temp_handle_ = handle(Smi::zero(), isolate);
  }
References v8::internal::DescriptorArray::Allocate(), v8::internal::ObjectDescriptor< IsolateT >::computed_count_, v8::internal::ObjectDescriptor< IsolateT >::computed_properties_, v8::internal::ObjectDescriptor< IsolateT >::descriptor_array_template_, v8::internal::ObjectDescriptor< IsolateT >::element_count_, v8::internal::ObjectDescriptor< IsolateT >::elements_dictionary_template_, v8::internal::handle(), v8::internal::ObjectDescriptor< IsolateT >::HasDictionaryProperties(), v8::internal::kOld, v8::internal::anonymous_namespace{intl-objects.cc}::New(), v8::internal::NameDictionary::New(), v8::internal::ObjectDescriptor< IsolateT >::properties_dictionary_template_, v8::internal::ObjectDescriptor< IsolateT >::property_count_, v8::internal::ObjectDescriptor< IsolateT >::property_slack_, v8::internal::ObjectDescriptor< IsolateT >::temp_handle_, V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL, and v8::internal::Smi::zero().
Referenced by v8::internal::ClassBoilerplate::New().
elements_template()
template<typename IsolateT >
Handle<NumberDictionary> v8::internal::ObjectDescriptor< IsolateT >::elements_template () const [inline]
Definition at line 484 of file literal-objects.cc.
                                                     {
    return elements_dictionary_template_;
  }
References v8::internal::ObjectDescriptor< IsolateT >::elements_dictionary_template_.
Referenced by v8::internal::ClassBoilerplate::New().
Finalize()
template<typename IsolateT >
void v8::internal::ObjectDescriptor< IsolateT >::Finalize (IsolateT * isolate) [inline]
Definition at line 608 of file literal-objects.cc.
                                   {
    if (HasDictionaryProperties()) {
      DCHECK_EQ(current_computed_index_, computed_properties_->length());
      if (!V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
        properties_dictionary_template()->set_next_enumeration_index(
            next_enumeration_index_);
      }
    } else {
      DCHECK(descriptor_array_template_->IsSortedNoDuplicates());
    }
  }
References v8::internal::ObjectDescriptor< IsolateT >::computed_properties_, v8::internal::ObjectDescriptor< IsolateT >::current_computed_index_, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::ObjectDescriptor< IsolateT >::descriptor_array_template_, v8::internal::ObjectDescriptor< IsolateT >::HasDictionaryProperties(), v8::internal::ObjectDescriptor< IsolateT >::next_enumeration_index_, v8::internal::ObjectDescriptor< IsolateT >::properties_dictionary_template(), and V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL.
Referenced by v8::internal::ClassBoilerplate::New().
HasDictionaryProperties()
template<typename IsolateT >
bool v8::internal::ObjectDescriptor< IsolateT >::HasDictionaryProperties () const [inline]
Definition at line 474 of file literal-objects.cc.
                                       {
    return computed_count_ > 0 ||
           (property_count_ + property_slack_) > kMaxNumberOfDescriptors;
  }
References v8::internal::ObjectDescriptor< IsolateT >::computed_count_, v8::internal::kMaxNumberOfDescriptors, v8::internal::ObjectDescriptor< IsolateT >::property_count_, and v8::internal::ObjectDescriptor< IsolateT >::property_slack_.
Referenced by v8::internal::ObjectDescriptor< IsolateT >::AddConstant(), v8::internal::ObjectDescriptor< IsolateT >::AddNamedProperty(), v8::internal::ObjectDescriptor< IsolateT >::CreateTemplates(), v8::internal::ObjectDescriptor< IsolateT >::Finalize(), and v8::internal::ObjectDescriptor< IsolateT >::properties_template().
IncComputedCount()
template<typename IsolateT >
void v8::internal::ObjectDescriptor< IsolateT >::IncComputedCount () [inline]
Definition at line 467 of file literal-objects.cc.
{ ++computed_count_; }
References v8::internal::ObjectDescriptor< IsolateT >::computed_count_.
Referenced by v8::internal::ClassBoilerplate::New().
IncElementsCount()
template<typename IsolateT >
void v8::internal::ObjectDescriptor< IsolateT >::IncElementsCount () [inline]
Definition at line 469 of file literal-objects.cc.
{ ++element_count_; }
References v8::internal::ObjectDescriptor< IsolateT >::element_count_.
Referenced by v8::internal::ClassBoilerplate::New().
IncPropertiesCount()
template<typename IsolateT >
void v8::internal::ObjectDescriptor< IsolateT >::IncPropertiesCount () [inline]
Definition at line 468 of file literal-objects.cc.
{ ++property_count_; }
References v8::internal::ObjectDescriptor< IsolateT >::property_count_.
Referenced by v8::internal::ClassBoilerplate::New().
properties_dictionary_template()
template<typename IsolateT >
Handle<NameDictionary> v8::internal::ObjectDescriptor< IsolateT >::properties_dictionary_template () const [inline], [private]
Definition at line 621 of file literal-objects.cc.
                                                                {
    return Cast<NameDictionary>(properties_dictionary_template_);
  }
References v8::internal::ObjectDescriptor< IsolateT >::properties_dictionary_template_.
Referenced by v8::internal::ObjectDescriptor< IsolateT >::AddConstant(), v8::internal::ObjectDescriptor< IsolateT >::AddNamedProperty(), and v8::internal::ObjectDescriptor< IsolateT >::Finalize().
properties_ordered_dictionary_template()
template<typename IsolateT >
Handle<SwissNameDictionary> v8::internal::ObjectDescriptor< IsolateT >::properties_ordered_dictionary_template () const [inline], [private]
Definition at line 625 of file literal-objects.cc.
                                                                             {
    return Cast<SwissNameDictionary>(properties_dictionary_template_);
  }
References v8::internal::ObjectDescriptor< IsolateT >::properties_dictionary_template_.
Referenced by v8::internal::ObjectDescriptor< IsolateT >::AddConstant(), and v8::internal::ObjectDescriptor< IsolateT >::AddNamedProperty().
properties_template()
template<typename IsolateT >
Handle<Object> v8::internal::ObjectDescriptor< IsolateT >::properties_template () const [inline]
Definition at line 479 of file literal-objects.cc.
                                             {
    return HasDictionaryProperties() ? properties_dictionary_template_
                                     : Cast<Object>(descriptor_array_template_);
  }
References v8::internal::ObjectDescriptor< IsolateT >::descriptor_array_template_, v8::internal::ObjectDescriptor< IsolateT >::HasDictionaryProperties(), and v8::internal::ObjectDescriptor< IsolateT >::properties_dictionary_template_.
Referenced by v8::internal::ClassBoilerplate::New().
UpdateNextEnumerationIndex()
template<typename IsolateT >
void v8::internal::ObjectDescriptor< IsolateT >::UpdateNextEnumerationIndex (int value_index) [inline]
Definition at line 602 of file literal-objects.cc.
                                                   {
    int current_index = ComputeEnumerationIndex(value_index);
    DCHECK_LE(next_enumeration_index_, current_index);
    next_enumeration_index_ = current_index + 1;
  }
References v8::internal::anonymous_namespace{literal-objects.cc}::ComputeEnumerationIndex(), DCHECK_LE, and v8::internal::ObjectDescriptor< IsolateT >::next_enumeration_index_.
Referenced by v8::internal::ObjectDescriptor< IsolateT >::AddComputed(), and v8::internal::ObjectDescriptor< IsolateT >::AddNamedProperty().
Member Data Documentation
computed_count_
template<typename IsolateT >
int v8::internal::ObjectDescriptor< IsolateT >::computed_count_ = 0 [private]
Definition at line 633 of file literal-objects.cc.
Referenced by v8::internal::ObjectDescriptor< IsolateT >::CreateTemplates(), v8::internal::ObjectDescriptor< IsolateT >::HasDictionaryProperties(), and v8::internal::ObjectDescriptor< IsolateT >::IncComputedCount().
computed_properties_
template<typename IsolateT >
Handle<FixedArray> v8::internal::ObjectDescriptor< IsolateT >::computed_properties_ [private]
Definition at line 642 of file literal-objects.cc.
Referenced by v8::internal::ObjectDescriptor< IsolateT >::AddComputed(), v8::internal::ObjectDescriptor< IsolateT >::computed_properties(), v8::internal::ObjectDescriptor< IsolateT >::CreateTemplates(), and v8::internal::ObjectDescriptor< IsolateT >::Finalize().
current_computed_index_
template<typename IsolateT >
int v8::internal::ObjectDescriptor< IsolateT >::current_computed_index_ = 0 [private]
Definition at line 634 of file literal-objects.cc.
Referenced by v8::internal::ObjectDescriptor< IsolateT >::AddComputed(), and v8::internal::ObjectDescriptor< IsolateT >::Finalize().
descriptor_array_template_
template<typename IsolateT >
Handle<DescriptorArray> v8::internal::ObjectDescriptor< IsolateT >::descriptor_array_template_ [private]
Definition at line 636 of file literal-objects.cc.
Referenced by v8::internal::ObjectDescriptor< IsolateT >::AddConstant(), v8::internal::ObjectDescriptor< IsolateT >::AddNamedProperty(), v8::internal::ObjectDescriptor< IsolateT >::CreateTemplates(), v8::internal::ObjectDescriptor< IsolateT >::Finalize(), and v8::internal::ObjectDescriptor< IsolateT >::properties_template().
element_count_
template<typename IsolateT >
int v8::internal::ObjectDescriptor< IsolateT >::element_count_ = 0 [private]
Definition at line 632 of file literal-objects.cc.
Referenced by v8::internal::ObjectDescriptor< IsolateT >::CreateTemplates(), and v8::internal::ObjectDescriptor< IsolateT >::IncElementsCount().
elements_dictionary_template_
template<typename IsolateT >
Handle<NumberDictionary> v8::internal::ObjectDescriptor< IsolateT >::elements_dictionary_template_ [private]
Definition at line 641 of file literal-objects.cc.
Referenced by v8::internal::ObjectDescriptor< IsolateT >::AddIndexedProperty(), v8::internal::ObjectDescriptor< IsolateT >::CreateTemplates(), and v8::internal::ObjectDescriptor< IsolateT >::elements_template().
next_enumeration_index_
template<typename IsolateT >
int v8::internal::ObjectDescriptor< IsolateT >::next_enumeration_index_ = PropertyDetails::kInitialIndex [private]
Definition at line 631 of file literal-objects.cc.
Referenced by v8::internal::ObjectDescriptor< IsolateT >::AddConstant(), v8::internal::ObjectDescriptor< IsolateT >::Finalize(), and v8::internal::ObjectDescriptor< IsolateT >::UpdateNextEnumerationIndex().
properties_dictionary_template_
template<typename IsolateT >
Handle<HeapObject> v8::internal::ObjectDescriptor< IsolateT >::properties_dictionary_template_ [private]
Definition at line 639 of file literal-objects.cc.
Referenced by v8::internal::ObjectDescriptor< IsolateT >::AddConstant(), v8::internal::ObjectDescriptor< IsolateT >::CreateTemplates(), v8::internal::ObjectDescriptor< IsolateT >::properties_dictionary_template(), v8::internal::ObjectDescriptor< IsolateT >::properties_ordered_dictionary_template(), and v8::internal::ObjectDescriptor< IsolateT >::properties_template().
property_count_
template<typename IsolateT >
int v8::internal::ObjectDescriptor< IsolateT >::property_count_ = 0 [private]
Definition at line 630 of file literal-objects.cc.
Referenced by v8::internal::ObjectDescriptor< IsolateT >::CreateTemplates(), v8::internal::ObjectDescriptor< IsolateT >::HasDictionaryProperties(), and v8::internal::ObjectDescriptor< IsolateT >::IncPropertiesCount().
property_slack_
template<typename IsolateT >
const int v8::internal::ObjectDescriptor< IsolateT >::property_slack_ [private]
Definition at line 629 of file literal-objects.cc.
Referenced by v8::internal::ObjectDescriptor< IsolateT >::CreateTemplates(), and v8::internal::ObjectDescriptor< IsolateT >::HasDictionaryProperties().
temp_handle_
template<typename IsolateT >
Handle<Object> v8::internal::ObjectDescriptor< IsolateT >::temp_handle_ [private]
Definition at line 644 of file literal-objects.cc.
Referenced by v8::internal::ObjectDescriptor< IsolateT >::AddNamedProperty(), and v8::internal::ObjectDescriptor< IsolateT >::CreateTemplates().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/literal-objects.cc