v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::ClassFieldOffsetGenerator Class Reference
Public Member Functions
ClassFieldOffsetGenerator (std::ostream &header, std::ostream &inline_header, const ClassType *type, std::string gen_name, const ClassType *parent, bool use_templates=true)
void WriteField (const Field &f, const std::string &size_string) override
void WriteFieldOffsetGetter (const Field &f) override
void WriteMarker (const std::string &marker) override
Static Private Member Functions
static std::string FirstFieldStart (const ClassType *type, const ClassType *parent, bool use_templates=true)
Private Attributes
std::ostream & hdr_
std::ostream & inl_
std::string previous_field_end_
std::string gen_name_
Additional Inherited Members
Detailed Description
Definition at line 4022 of file implementation-visitor.cc.
Constructor & Destructor Documentation
ClassFieldOffsetGenerator()
v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::ClassFieldOffsetGenerator::ClassFieldOffsetGenerator (std::ostream & header, std::ostream & inline_header, const ClassType * type, std::string gen_name, const ClassType * parent, bool use_templates = true) [inline]
Definition at line 4024 of file implementation-visitor.cc.
      : FieldOffsetsGenerator(type),
        hdr_(header),
        inl_(inline_header),
        previous_field_end_(FirstFieldStart(type, parent, use_templates)),
        gen_name_(gen_name) {}
Member Function Documentation
FirstFieldStart()
static std::string v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::ClassFieldOffsetGenerator::FirstFieldStart (const ClassType * type, const ClassType * parent, bool use_templates = true) [inline], [static], [private]
Definition at line 4070 of file implementation-visitor.cc.
                                                                {
    std::string parent_name = use_templates ? "P" : parent->name();
    if (type->IsLayoutDefinedInCpp()) {
      // TODO(leszeks): Hacked in support for some classes (e.g.
      // HeapObject) being mirrored by a *Layout class. Remove once
      // everything is ported to layout classes.
      if (parent_name == "HeapObject" || parent_name == "TrustedObject" ||
          parent_name == "Struct") {
        parent_name += "Layout";
      }
      return "sizeof(" + parent_name + ")";
    }
    if (parent && parent->IsShape()) {
      return parent_name + "::kSize";
    }
    return parent_name + "::kHeaderSize";
  }
References v8::internal::torque::ClassType::IsShape(), v8::internal::torque::AggregateType::name(), v8::internal::string, and v8::internal::tracing::type.
WriteField()
void v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::ClassFieldOffsetGenerator::WriteField (const Field & f, const std::string & size_string) [inline], [override], [virtual]
Implements v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FieldOffsetsGenerator.
Definition at line 4033 of file implementation-visitor.cc.
                                                                         {
    hdr_ << " // " << f.pos << "\n";
    std::string field = "k" + CamelifyString(f.name_and_type.name) + "Offset";
    std::string field_end = field + "End";
    hdr_ << " static constexpr int " << field << " = " << previous_field_end_
         << ";\n";
    hdr_ << " static constexpr int " << field_end << " = " << field << " + "
         << size_string << " - 1;\n";
    previous_field_end_ = field_end + " + 1";
  }
References v8::internal::torque::CamelifyString(), v8::internal::torque::NameAndType::name, v8::internal::torque::Field::name_and_type, v8::internal::torque::Field::pos, and v8::internal::string.
WriteFieldOffsetGetter()
void v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::ClassFieldOffsetGenerator::WriteFieldOffsetGetter (const Field & f) [inline], [override], [virtual]
Implements v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FieldOffsetsGenerator.
Definition at line 4044 of file implementation-visitor.cc.
                                                       {
    // A static constexpr int is more convenient than a getter if the offset is
    // known.
    DCHECK(!f.offset.has_value());
    std::string function_name = CamelifyString(f.name_and_type.name) + "Offset";
    std::vector<cpp::TemplateParameter> params = {cpp::TemplateParameter("D"),
                                                  cpp::TemplateParameter("P")};
    cpp::Class owner(std::move(params), gen_name_);
    auto getter = cpp::Function::DefaultGetter("int", &owner, function_name);
    getter.PrintDeclaration(hdr_);
    getter.PrintDefinition(inl_, [&](std::ostream& stream) {
      // Item 1 in a flattened slice is the offset.
      stream << " return static_cast<int>(std::get<1>("
             << Callable::PrefixNameForCCOutput(type_->GetSliceMacroName(f))
             << "(*static_cast<const D*>(this))));\n";
    });
  }
References v8::internal::torque::CamelifyString(), v8::internal::DCHECK(), v8::internal::torque::NameAndType::name, v8::internal::torque::Field::name_and_type, v8::internal::torque::Field::offset, and v8::internal::string.
WriteMarker()
void v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::ClassFieldOffsetGenerator::WriteMarker (const std::string & marker) [inline], [override], [virtual]
Implements v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FieldOffsetsGenerator.
Definition at line 4064 of file implementation-visitor.cc.
                                                     {
    hdr_ << " static constexpr int " << marker << " = " << previous_field_end_
         << ";\n";
  }
Member Data Documentation
gen_name_
std::string v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::ClassFieldOffsetGenerator::gen_name_ [private]
Definition at line 4096 of file implementation-visitor.cc.
hdr_
std::ostream& v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::ClassFieldOffsetGenerator::hdr_ [private]
Definition at line 4093 of file implementation-visitor.cc.
inl_
std::ostream& v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::ClassFieldOffsetGenerator::inl_ [private]
Definition at line 4094 of file implementation-visitor.cc.
previous_field_end_
std::string v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::ClassFieldOffsetGenerator::previous_field_end_ [private]
Definition at line 4095 of file implementation-visitor.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/implementation-visitor.cc