v8::String::Utf8Value Class Reference
Converts an object to a null-terminated UTF-8-encoded character array.
#include <v8-primitive.h>
Public Member Functions
Utf8Value (Isolate *isolate, Local< v8::Value > obj)
~Utf8Value ()
char * operator* ()
const char * operator* () const
size_t length () const
Utf8Value (const Utf8Value &)=delete
void operator= (const Utf8Value &)=delete
Private Attributes
char * str_
size_t length_
Detailed Description
Converts an object to a null-terminated UTF-8-encoded character array.
Useful if you want to print the object. If conversion to a string fails (e.g. due to an exception in the toString() method of the object) then the length() method returns 0 and the * operator returns NULL.
WARNING: This will unconditionally copy the contents of the JavaScript string, and should be avoided in situations where performance is a concern. Consider using WriteUtf8() instead.
Definition at line 647 of file v8-primitive.h.
Constructor & Destructor Documentation
Utf8Value() [1/2]
v8::String::Utf8Value::Utf8Value (v8::Isolate * v8_isolate, Local< v8::Value > obj)
Definition at line 11054 of file api.cc.
    : str_(nullptr), length_(0) {
  if (obj.IsEmpty()) return;
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  Local<Context> context = v8_isolate->GetCurrentContext();
  EnterV8BasicScope api_scope(i_isolate);
  i::HandleScope scope(i_isolate);
  TryCatch try_catch(v8_isolate);
  Local<String> str;
  if (!obj->ToString(context).ToLocal(&str)) return;
  length_ = str->Utf8LengthV2(v8_isolate);
  str_ = i::NewArray<char>(length_ + 1);
  int flags = String::WriteFlags::kNullTerminate |
              String::WriteFlags::kReplaceInvalidUtf8;
  str->WriteUtf8V2(v8_isolate, str_, length_ + 1, flags);
}
References flags(), v8::Isolate::GetCurrentContext(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8::String::WriteFlags::kNullTerminate, v8::String::WriteFlags::kReplaceInvalidUtf8, length_, str_, and v8::Value::ToString().
 Utf8Value()
v8::String::Utf8Value::~Utf8Value ()
Definition at line 11071 of file api.cc.
{ i::DeleteArray(str_); }
Utf8Value() [2/2]
v8::String::Utf8Value::Utf8Value (const Utf8Value &) [delete]
Member Function Documentation
length()
size_t v8::String::Utf8Value::length () const [inline]
Definition at line 653 of file v8-primitive.h.
{ return length_; }
Referenced by v8::internal::anonymous_namespace{js-locale.cc}::ApplyOptionsToTag(), v8::anonymous_namespace{d8-console.cc}::GetTimerLabel(), v8::ExecArgs::Init(), v8::Shell::RunShell(), v8::anonymous_namespace{d8-console.cc}::WriteToFile(), and v8::WriteToFile().
operator*() [1/2]
char* v8::String::Utf8Value::operator* () [inline]
Definition at line 651 of file v8-primitive.h.
{ return str_; }
operator*() [2/2]
const char* v8::String::Utf8Value::operator* () const [inline]
Definition at line 652 of file v8-primitive.h.
{ return str_; }
operator=()
void v8::String::Utf8Value::operator= (const Utf8Value &) [delete]
Member Data Documentation
length_
size_t v8::String::Utf8Value::length_ [private]
Definition at line 661 of file v8-primitive.h.
Referenced by Utf8Value().
str_
char* v8::String::Utf8Value::str_ [private]
Definition at line 660 of file v8-primitive.h.
Referenced by Utf8Value().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-primitive.h
/mnt/V8SourceCode/src/api/api.cc