v8::internal::maglev::CreateShallowArrayLiteral Class Reference
#include <maglev-ir.h>
Public Member Functions
CreateShallowArrayLiteral (uint64_t bitfield, compiler::HeapObjectRef constant_elements, const compiler::FeedbackSource &feedback, int flags)
compiler::HeapObjectRef constant_elements ()
compiler::FeedbackSource feedback () const
int flags () const
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties
Private Types
using Base = FixedInputValueNodeT< 0, CreateShallowArrayLiteral >
Private Attributes
const compiler::HeapObjectRef constant_elements_
const compiler::FeedbackSource feedback_
const int flags_
Additional Inherited Members
Detailed Description
Definition at line 5699 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::CreateShallowArrayLiteral::Base = FixedInputValueNodeT<0, CreateShallowArrayLiteral> [private]
Definition at line 5701 of file maglev-ir.h.
Constructor & Destructor Documentation
CreateShallowArrayLiteral()
v8::internal::maglev::CreateShallowArrayLiteral::CreateShallowArrayLiteral (uint64_t bitfield, compiler::HeapObjectRef constant_elements, const compiler::FeedbackSource & feedback, int flags) [inline], [explicit]
Definition at line 5704 of file maglev-ir.h.
      : Base(bitfield),
        constant_elements_(constant_elements),
        feedback_(feedback),
        flags_(flags) {}
Member Function Documentation
constant_elements()
compiler::HeapObjectRef v8::internal::maglev::CreateShallowArrayLiteral::constant_elements () [inline]
Definition at line 5713 of file maglev-ir.h.
{ return constant_elements_; }
References constant_elements_.
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
feedback()
compiler::FeedbackSource v8::internal::maglev::CreateShallowArrayLiteral::feedback () const [inline]
Definition at line 5714 of file maglev-ir.h.
{ return feedback_; }
References feedback_.
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
flags()
int v8::internal::maglev::CreateShallowArrayLiteral::flags () const [inline]
Definition at line 5715 of file maglev-ir.h.
{ return flags_; }
References flags_.
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::CreateShallowArrayLiteral::GenerateCode (MaglevAssembler * , const ProcessingState &)
MaxCallStackArgs()
int v8::internal::maglev::CreateShallowArrayLiteral::MaxCallStackArgs () const
PrintParams()
void v8::internal::maglev::CreateShallowArrayLiteral::PrintParams (std::ostream & , MaglevGraphLabeller *) const [inline]
Definition at line 5724 of file maglev-ir.h.
{}
SetValueLocationConstraints()
void v8::internal::maglev::CreateShallowArrayLiteral::SetValueLocationConstraints ()
Member Data Documentation
constant_elements_
const compiler::HeapObjectRef v8::internal::maglev::CreateShallowArrayLiteral::constant_elements_ [private]
Definition at line 5727 of file maglev-ir.h.
Referenced by constant_elements().
feedback_
const compiler::FeedbackSource v8::internal::maglev::CreateShallowArrayLiteral::feedback_ [private]
Definition at line 5728 of file maglev-ir.h.
Referenced by feedback().
flags_
const int v8::internal::maglev::CreateShallowArrayLiteral::flags_ [private]
Definition at line 5729 of file maglev-ir.h.
Referenced by flags().
kProperties
constexpr OpProperties v8::internal::maglev::CreateShallowArrayLiteral::kProperties [static], [constexpr]
Initial value:
=
      OpProperties::GenericRuntimeOrBuiltinCall()
Definition at line 5718 of file maglev-ir.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h