v8::internal::String::Match Class Reference
#include <string.h>
Public Types
enum CaptureState { UNMATCHED
, MATCHED
 }
Public Member Functions
virtual DirectHandle< String > GetMatch ()=0
virtual DirectHandle< String > GetPrefix ()=0
virtual DirectHandle< String > GetSuffix ()=0
virtual int CaptureCount ()=0
virtual bool HasNamedCaptures ()=0
virtual MaybeDirectHandle< String > GetCapture (int i, bool *capture_exists)=0
virtual MaybeDirectHandle< String > GetNamedCapture (DirectHandle< String > name, CaptureState *state)=0
virtual ~Match ()=default
Detailed Description
Definition at line 362 of file string.h.
Member Enumeration Documentation
CaptureState
enum v8::internal::String::Match::CaptureState
Enumerator
UNMATCHED
MATCHED
Definition at line 370 of file string.h.
{ UNMATCHED, MATCHED };
Constructor & Destructor Documentation
 Match()
virtual v8::internal::String::Match::~Match () [virtual], [default]
Member Function Documentation
CaptureCount()
virtual int v8::internal::String::Match::CaptureCount () [pure virtual]
Implemented in v8::internal::anonymous_namespace{runtime-regexp.cc}::VectorBackedMatch, and v8::internal::anonymous_namespace{runtime-regexp.cc}::MatchInfoBackedMatch.
Referenced by v8::internal::String::GetSubstitution().
GetCapture()
virtual MaybeDirectHandle<String> v8::internal::String::Match::GetCapture (int i, bool * capture_exists) [pure virtual]
Implemented in v8::internal::anonymous_namespace{runtime-regexp.cc}::VectorBackedMatch, and v8::internal::anonymous_namespace{runtime-regexp.cc}::MatchInfoBackedMatch.
Referenced by v8::internal::String::GetSubstitution().
GetMatch()
virtual DirectHandle<String> v8::internal::String::Match::GetMatch () [pure virtual]
Implemented in v8::internal::anonymous_namespace{runtime-regexp.cc}::VectorBackedMatch, and v8::internal::anonymous_namespace{runtime-regexp.cc}::MatchInfoBackedMatch.
Referenced by v8::internal::String::GetSubstitution().
GetNamedCapture()
virtual MaybeDirectHandle<String> v8::internal::String::Match::GetNamedCapture (DirectHandle< String > name, CaptureState * state) [pure virtual]
Implemented in v8::internal::anonymous_namespace{runtime-regexp.cc}::VectorBackedMatch, and v8::internal::anonymous_namespace{runtime-regexp.cc}::MatchInfoBackedMatch.
Referenced by v8::internal::String::GetSubstitution().
GetPrefix()
virtual DirectHandle<String> v8::internal::String::Match::GetPrefix () [pure virtual]
Implemented in v8::internal::anonymous_namespace{runtime-regexp.cc}::VectorBackedMatch, and v8::internal::anonymous_namespace{runtime-regexp.cc}::MatchInfoBackedMatch.
Referenced by v8::internal::String::GetSubstitution().
GetSuffix()
virtual DirectHandle<String> v8::internal::String::Match::GetSuffix () [pure virtual]
Implemented in v8::internal::anonymous_namespace{runtime-regexp.cc}::VectorBackedMatch, and v8::internal::anonymous_namespace{runtime-regexp.cc}::MatchInfoBackedMatch.
Referenced by v8::internal::String::GetSubstitution().
HasNamedCaptures()
virtual bool v8::internal::String::Match::HasNamedCaptures () [pure virtual]
Implemented in v8::internal::anonymous_namespace{runtime-regexp.cc}::VectorBackedMatch, and v8::internal::anonymous_namespace{runtime-regexp.cc}::MatchInfoBackedMatch.
Referenced by v8::internal::String::GetSubstitution().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/string.h