v8::internal::wasm::ModuleDecoderImpl Class Reference
#include <module-decoder-impl.h>
Classes
struct DataSegmentHeader
struct LimitsByte
Public Member Functions
ModuleDecoderImpl (WasmEnabledFeatures enabled_features, base::Vector< const uint8_t > wire_bytes, ModuleOrigin origin, WasmDetectedFeatures *detected_features, ITracer *tracer=ITracer::NoTrace)
void onFirstError () override
void DecodeModuleHeader (base::Vector< const uint8_t > bytes)
bool CheckSectionOrder (SectionCode section_code)
void DecodeSection (SectionCode section_code, base::Vector< const uint8_t > bytes, uint32_t offset)
TypeDefinition consume_base_type_definition (bool is_descriptor, bool is_shared)
TypeDefinition consume_described_type (bool is_descriptor, bool is_shared)
TypeDefinition consume_describing_type (size_t current_type_index, bool is_shared)
TypeDefinition consume_shared_type (size_t current_type_index)
TypeDefinition consume_subtype_definition (size_t current_type_index)
void DecodeTypeSection ()
void FinalizeRecgroup (uint32_t group_size, TypeCanonicalizer *type_canon)
void DecodeImportSection ()
void DecodeFunctionSection ()
void DecodeTableSection ()
void DecodeMemorySection ()
void UpdateComputedMemoryInformation ()
void DecodeGlobalSection ()
void DecodeExportSection ()
void DecodeStartSection ()
void DecodeElementSection ()
void DecodeCodeSection ()
void StartCodeSection (WireBytesRef section_bytes)
bool CheckFunctionsCount (uint32_t functions_count, uint32_t error_offset)
void DecodeFunctionBody (uint32_t func_index, uint32_t length, uint32_t offset)
bool CheckDataSegmentsCount (uint32_t data_segments_count)
void DecodeDataSection ()
void DecodeNameSection ()
void DecodeDescriptorsSection ()
void DecodeSourceMappingURLSection ()
void DecodeExternalDebugInfoSection ()
void DecodeBuildIdSection ()
void DecodeInstTraceSection ()
void DecodeCompilationHintsSection ()
void DecodeBranchHintsSection ()
void DecodeDataCountSection ()
void DecodeTagSection ()
void DecodeStringRefSection ()
bool CheckMismatchedCounts ()
ModuleResult FinishDecoding ()
ModuleResult DecodeModule (bool validate_functions)
FunctionResult DecodeSingleFunctionForTesting (Zone *zone, ModuleWireBytes wire_bytes, const WasmModule *module)
const FunctionSig * DecodeFunctionSignatureForTesting (Zone *zone, const uint8_t *start)
ConstantExpression DecodeInitExprForTesting (ValueType expected)
ConstantExpression consume_element_segment_entry (WasmModule *module, const WasmElemSegment &segment)
const std::shared_ptr< WasmModule > & shared_module () const
Static Public Member Functions
static constexpr const char * TypeKindName (uint8_t kind)
Private Types
enum LimitsByteType { kMemory
, kTable
 }
enum ResizableLimitsType : bool { k32BitLimits
, k64BitLimits
 }
Private Member Functions
bool has_seen_unordered_section (SectionCode section_code)
void set_seen_unordered_section (SectionCode section_code)
uint32_t off (const uint8_t *ptr)
void CalculateGlobalOffsets (WasmModule *module)
ModuleTypeIndex consume_sig_index (WasmModule *module, const FunctionSig **sig)
ModuleTypeIndex consume_tag_sig_index (WasmModule *module, const FunctionSig **sig)
uint32_t consume_count (const char *name, size_t maximum)
uint32_t consume_func_index (WasmModule *module, WasmFunction **func)
uint32_t consume_global_index (WasmModule *module, WasmGlobal **global)
uint32_t consume_table_index (WasmModule *module, WasmTable **table)
uint32_t consume_tag_index (WasmModule *module, WasmTag **tag)
template<typename T >
uint32_t consume_index (const char *name, std::vector< T > *vector, T **ptr)
template<LimitsByteType limits_type>
LimitsByte consume_limits_byte ()
void consume_table_flags (WasmTable *table)
void consume_memory_flags (WasmMemory *memory)
std::pair< bool, bool > consume_global_flags ()
void consume_resizable_limits (const char *name, const char *units, uint32_t max_initial, uint32_t *initial, bool has_maximum, uint64_t max_maximum, uint64_t *maximum, ResizableLimitsType type)
bool expect_u8 (const char *name, uint8_t expected)
ConstantExpression consume_init_expr (WasmModule *module, ValueType expected, bool is_shared, bool *ends_with_struct_new=nullptr)
bool consume_mutability ()
ValueType consume_value_type (const WasmModule *module=nullptr)
HeapType consume_heap_type ()
ValueType consume_storage_type ()
const FunctionSig * consume_sig (Zone *zone)
const StructType * consume_struct (Zone *zone, bool is_descriptor, bool is_shared)
const ArrayType * consume_array (Zone *zone)
uint32_t consume_exception_attribute ()
WasmElemSegment consume_element_segment_header ()
DataSegmentHeader consume_data_segment_header ()
uint32_t consume_element_func_index (WasmModule *module, ValueType expected)
Private Attributes
const WasmEnabledFeatures enabled_features_
WasmDetectedFeatures *const detected_features_
const std::shared_ptr< WasmModule > module_
const uint8_t * module_start_ = nullptr
const uint8_t * module_end_ = nullptr
ITracer * tracer_
uint8_t next_ordered_section_ = kFirstSectionInModule
uint32_t seen_unordered_sections_ = 0
AccountingAllocator allocator_
Zone init_expr_zone_ {&allocator_, `constant expr. zone`}
std::vector< std::tuple< uint32_t, uint32_t, uint32_t > > inst_traces_
Additional Inherited Members
Detailed Description
Definition at line 311 of file module-decoder-impl.h.
Member Enumeration Documentation
LimitsByteType
enum v8::internal::wasm::ModuleDecoderImpl::LimitsByteType [private]
Enumerator
kMemory
kTable
Definition at line 2200 of file module-decoder-impl.h.
{ kMemory, kTable };
ResizableLimitsType
enum v8::internal::wasm::ModuleDecoderImpl::ResizableLimitsType : bool [private]
Enumerator
k32BitLimits
k64BitLimits
Definition at line 2285 of file module-decoder-impl.h.
: bool { k32BitLimits, k64BitLimits };
Constructor & Destructor Documentation
ModuleDecoderImpl()
v8::internal::wasm::ModuleDecoderImpl::ModuleDecoderImpl (WasmEnabledFeatures enabled_features, base::Vector< const uint8_t > wire_bytes, ModuleOrigin origin, WasmDetectedFeatures * detected_features, ITracer * tracer = ITracer::NoTrace) [inline]
Definition at line 313 of file module-decoder-impl.h.
      : Decoder(wire_bytes),
        enabled_features_(enabled_features),
        detected_features_(detected_features),
        module_(std::make_shared<WasmModule>(origin)),
        module_start_(wire_bytes.begin()),
        module_end_(wire_bytes.end()),
        tracer_(tracer) {}
Member Function Documentation
CalculateGlobalOffsets()
void v8::internal::wasm::ModuleDecoderImpl::CalculateGlobalOffsets (WasmModule * module) [inline], [private]
Definition at line 2072 of file module-decoder-impl.h.
                                                  {
    if (module->globals.empty() || module->untagged_globals_buffer_size != 0 ||
        module->tagged_globals_buffer_size != 0) {
      // This function has already been executed before, so we don't have to
      // execute it again.
      return;
    }
    uint32_t untagged_offset = 0;
    uint32_t tagged_offset = 0;
    uint32_t num_imported_mutable_globals = 0;
    for (WasmGlobal& global : module->globals) {
      if (global.mutability && global.imported) {
        global.index = num_imported_mutable_globals++;
      } else if (global.type.is_reference()) {
        global.offset = tagged_offset;
        // All entries in the tagged_globals_buffer have size 1.
        tagged_offset++;
      } else {
        int size = global.type.value_kind_size();
        untagged_offset = (untagged_offset + size - 1) & ~(size - 1); // align
        global.offset = untagged_offset;
        untagged_offset += size;
      }
    }
    module->untagged_globals_buffer_size = untagged_offset;
    module->tagged_globals_buffer_size = tagged_offset;
  }
References v8::internal::wasm::WasmModule::globals, v8::internal::wasm::WasmGlobal::imported, v8::internal::wasm::WasmGlobal::index, v8::internal::wasm::ValueTypeBase::is_reference(), v8::internal::wasm::WasmGlobal::mutability, v8::internal::wasm::WasmGlobal::offset, size(), v8::internal::wasm::WasmModule::tagged_globals_buffer_size, v8::internal::wasm::WasmGlobal::type, v8::internal::wasm::WasmModule::untagged_globals_buffer_size, and v8::internal::wasm::ValueTypeBase::value_kind_size().
Referenced by DecodeCodeSection(), FinishDecoding(), and StartCodeSection().
CheckDataSegmentsCount()
bool v8::internal::wasm::ModuleDecoderImpl::CheckDataSegmentsCount (uint32_t data_segments_count) [inline]
Definition at line 1495 of file module-decoder-impl.h.
                                                            {
    if (has_seen_unordered_section(kDataCountSectionCode) &&
        data_segments_count != module_->num_declared_data_segments) {
      errorf(pc(), "data segments count %u mismatch (%u expected)",
             data_segments_count, module_->num_declared_data_segments);
      return false;
    }
    return true;
  }
References v8::internal::wasm::Decoder::errorf(), has_seen_unordered_section(), v8::internal::wasm::kDataCountSectionCode, module_, and v8::internal::wasm::Decoder::pc().
Referenced by CheckMismatchedCounts(), and DecodeDataSection().
CheckFunctionsCount()
bool v8::internal::wasm::ModuleDecoderImpl::CheckFunctionsCount (uint32_t functions_count, uint32_t error_offset) [inline]
Definition at line 1473 of file module-decoder-impl.h.
                                                                            {
    if (functions_count != module_->num_declared_functions) {
      errorf(error_offset, "function body count %u mismatch (%u expected)",
             functions_count, module_->num_declared_functions);
      return false;
    }
    return true;
  }
References v8::internal::wasm::Decoder::errorf(), and module_.
Referenced by DecodeCodeSection().
CheckMismatchedCounts()
bool v8::internal::wasm::ModuleDecoderImpl::CheckMismatchedCounts () [inline]
Definition at line 1910 of file module-decoder-impl.h.
                               {
    // The declared vs. defined function count is normally checked when
    // decoding the code section, but we have to check it here too in case the
    // code section is absent.
    if (module_->num_declared_functions != 0) {
      DCHECK_LT(module_->num_imported_functions, module_->functions.size());
      // We know that the code section has been decoded if the first
      // non-imported function has its code set.
      if (!module_->functions[module_->num_imported_functions].code.is_set()) {
        errorf(pc(), "function count is %u, but code section is absent",
               module_->num_declared_functions);
        return false;
      }
    }
    // Perform a similar check for the DataCount and Data sections, where data
    // segments are declared but the Data section is absent.
    if (!CheckDataSegmentsCount(
            static_cast<uint32_t>(module_->data_segments.size()))) {
      return false;
    }
    return true;
  }
References CheckDataSegmentsCount(), DCHECK_LT, v8::internal::wasm::Decoder::errorf(), module_, and v8::internal::wasm::Decoder::pc().
Referenced by FinishDecoding().
CheckSectionOrder()
bool v8::internal::wasm::ModuleDecoderImpl::CheckSectionOrder (SectionCode section_code) [inline]
Definition at line 358 of file module-decoder-impl.h.
                                                   {
    // Check the order of ordered sections.
    if (section_code >= kFirstSectionInModule &&
        section_code < kFirstUnorderedSection) {
      if (section_code < next_ordered_section_) {
        errorf(pc(), "unexpected section <%s>", SectionName(section_code));
        return false;
      }
      next_ordered_section_ = section_code + 1;
      return true;
    }
    // Ignore ordering problems in unknown / custom sections. Even allow them to
    // appear multiple times. As optional sections we use them on a "best
    // effort" basis.
    if (section_code == kUnknownSectionCode) return true;
    if (section_code > kLastKnownModuleSection) return true;
    // The rest is standardized unordered sections; they are checked more
    // thoroughly..
    DCHECK_LE(kFirstUnorderedSection, section_code);
    DCHECK_GE(kLastKnownModuleSection, section_code);
    // Check that unordered sections don't appear multiple times.
    if (has_seen_unordered_section(section_code)) {
      errorf(pc(), "Multiple %s sections not allowed",
             SectionName(section_code));
      return false;
    }
    set_seen_unordered_section(section_code);
    // Define a helper to ensure that sections <= {before} appear before the
    // current unordered section, and everything >= {after} appears after it.
    auto check_order = [this, section_code](SectionCode before,
                                            SectionCode after) -> bool {
      DCHECK_LT(before, after);
      if (next_ordered_section_ > after) {
        errorf(pc(), "The %s section must appear before the %s section",
               SectionName(section_code), SectionName(after));
        return false;
      }
      if (next_ordered_section_ <= before) next_ordered_section_ = before + 1;
      return true;
    };
    // Now check the ordering constraints of specific unordered sections.
    switch (section_code) {
      case kDataCountSectionCode:
        return check_order(kElementSectionCode, kCodeSectionCode);
      case kTagSectionCode:
        return check_order(kMemorySectionCode, kGlobalSectionCode);
      case kStringRefSectionCode:
        // TODO(12868): If there's a tag section, assert that we're after the
        // tag section.
        return check_order(kMemorySectionCode, kGlobalSectionCode);
      case kInstTraceSectionCode:
        // Custom section following code.metadata tool convention containing
        // offsets specifying where trace marks should be emitted.
        // Be lenient with placement of instruction trace section. All except
        // first occurrence after function section and before code section are
        // ignored.
        return true;
      default:
        return true;
    }
  }
References DCHECK_GE, DCHECK_LE, DCHECK_LT, v8::internal::wasm::Decoder::errorf(), has_seen_unordered_section(), v8::internal::wasm::kCodeSectionCode, v8::internal::wasm::kDataCountSectionCode, v8::internal::wasm::kElementSectionCode, v8::internal::wasm::kFirstSectionInModule, v8::internal::wasm::kFirstUnorderedSection, v8::internal::wasm::kGlobalSectionCode, v8::internal::wasm::kInstTraceSectionCode, v8::internal::wasm::kLastKnownModuleSection, v8::internal::wasm::kMemorySectionCode, v8::internal::wasm::kStringRefSectionCode, v8::internal::wasm::kTagSectionCode, v8::internal::wasm::kUnknownSectionCode, next_ordered_section_, v8::internal::wasm::Decoder::pc(), v8::internal::wasm::SectionName(), and set_seen_unordered_section().
Referenced by DecodeSection(), and StartCodeSection().
consume_array()
const ArrayType* v8::internal::wasm::ModuleDecoderImpl::consume_array (Zone * zone) [inline], [private]
Definition at line 2616 of file module-decoder-impl.h.
                                             {
    ValueType element_type = consume_storage_type();
    bool mutability = consume_mutability();
    if (tracer_) tracer_->NextLine();
    if (failed()) return nullptr;
    return zone->New<ArrayType>(element_type, mutability);
  }
References consume_mutability(), consume_storage_type(), v8::internal::wasm::Decoder::failed(), v8::internal::Zone::New(), v8::internal::wasm::ITracer::NextLine(), and tracer_.
Referenced by consume_base_type_definition().
consume_base_type_definition()
TypeDefinition v8::internal::wasm::ModuleDecoderImpl::consume_base_type_definition (bool is_descriptor, bool is_shared) [inline]
Definition at line 563 of file module-decoder-impl.h.
                                                              {
    const bool is_final = true;
    uint8_t kind = consume_u8(" kind", tracer_);
    if (tracer_) {
      tracer_->Description(": ");
      tracer_->Description(TypeKindName(kind));
    }
    switch (kind) {
      case kWasmFunctionTypeCode: {
        const FunctionSig* sig = consume_sig(&module_->signature_zone);
        if (sig == nullptr) {
          CHECK(!ok());
          return {};
        }
        return {sig, kNoSuperType, is_final, is_shared};
      }
      case kWasmStructTypeCode: {
        module_->is_wasm_gc = true;
        const StructType* type =
            consume_struct(&module_->signature_zone, is_descriptor, is_shared);
        if (type == nullptr) {
          CHECK(!ok());
          return {};
        }
        return {type, kNoSuperType, is_final, is_shared};
      }
      case kWasmArrayTypeCode: {
        module_->is_wasm_gc = true;
        const ArrayType* type = consume_array(&module_->signature_zone);
        if (type == nullptr) {
          CHECK(!ok());
          return {};
        }
        return {type, kNoSuperType, is_final, is_shared};
      }
      case kWasmContTypeCode: {
        if (!enabled_features_.has_wasmfx()) {
          error(pc() - 1,
                "core stack switching not enabled (enable with "
                "--experimental-wasm-wasmfx)");
          return {};
        }
        const uint8_t* pos = pc();
        HeapType hp = consume_heap_type();
        if (!hp.is_index()) {
          error(pos, "cont type must refer to a signature index");
          return {};
        }
        ContType* type = module_->signature_zone.New<ContType>(hp.ref_index());
        return {type, kNoSuperType, is_final, is_shared};
      }
      default:
        if (tracer_) tracer_->NextLine();
        errorf(pc() - 1, "unknown type form: %d", kind);
        return {};
    }
  }
References CHECK, consume_array(), consume_heap_type(), consume_sig(), consume_struct(), v8::internal::wasm::Decoder::consume_u8(), v8::internal::wasm::ITracer::Description(), enabled_features_, v8::internal::wasm::Decoder::error(), v8::internal::wasm::Decoder::errorf(), v8::internal::wasm::HeapType::is_index(), v8::internal::is_shared, v8::internal::wasm::kNoSuperType, v8::internal::wasm::kWasmArrayTypeCode, v8::internal::wasm::kWasmContTypeCode, v8::internal::wasm::kWasmFunctionTypeCode, v8::internal::wasm::kWasmStructTypeCode, module_, v8::internal::wasm::ITracer::NextLine(), v8::internal::wasm::Decoder::ok(), v8::internal::wasm::Decoder::pc(), v8::internal::wasm::HeapType::ref_index(), v8::internal::sig, tracer_, v8::internal::tracing::type, and TypeKindName().
Referenced by consume_described_type().
consume_count()
uint32_t v8::internal::wasm::ModuleDecoderImpl::consume_count (const char * name, size_t maximum) [inline], [private]
Definition at line 2133 of file module-decoder-impl.h.
                                                           {
    const uint8_t* p = pc_;
    uint32_t count = consume_u32v(name, tracer_);
    if (tracer_) {
      tracer_->Description(count);
      if (count == 1) {
        tracer_->Description(": ");
      } else {
        tracer_->NextLine();
      }
    }
    if (count > maximum) {
      errorf(p, "%s of %u exceeds internal limit of %zu", name, count, maximum);
      return 0;
    }
    return count;
  }
References v8::internal::wasm::Decoder::consume_u32v(), v8::internal::wasm::ITracer::Description(), v8::internal::wasm::Decoder::errorf(), v8::internal::wasm::name(), v8::internal::wasm::ITracer::NextLine(), v8::internal::wasm::Decoder::pc_, and tracer_.
Referenced by consume_element_segment_header(), consume_sig(), consume_struct(), consume_subtype_definition(), DecodeDataCountSection(), DecodeDataSection(), DecodeElementSection(), DecodeExportSection(), DecodeFunctionSection(), DecodeGlobalSection(), DecodeImportSection(), DecodeMemorySection(), DecodeStringRefSection(), DecodeTableSection(), DecodeTagSection(), and DecodeTypeSection().
consume_data_segment_header()
DataSegmentHeader v8::internal::wasm::ModuleDecoderImpl::consume_data_segment_header () [inline], [private]
Definition at line 2782 of file module-decoder-impl.h.
                                                  {
    const uint8_t* pos = pc();
    uint32_t flag = consume_u32v("flag", tracer_);
    if (flag & ~0b1011) {
      errorf(pos, "illegal flag value %u", flag);
      return {};
    }
    uint32_t status_flag = flag & 0b11;
    if (tracer_) {
      tracer_->Description(": ");
      tracer_->Description(
          status_flag == SegmentFlags::kActiveNoIndex ? "active no index"
          : status_flag == SegmentFlags::kPassive ? "passive"
          : status_flag == SegmentFlags::kActiveWithIndex ? "active with index"
                                                          : "unknown");
    }
    if (status_flag != SegmentFlags::kActiveNoIndex &&
        status_flag != SegmentFlags::kPassive &&
        status_flag != SegmentFlags::kActiveWithIndex) {
      errorf(pos, "illegal flag value %u", flag);
      return {};
    }
    bool is_shared = flag & 0b1000;
    if (V8_UNLIKELY(is_shared && !enabled_features_.has_shared())) {
      errorf(pos, "illegal flag value %u.", flag);
      return {};
    }
    if (V8_UNLIKELY(is_shared)) {
      // TODO(42204563): Support shared data segments.
      error(pos, "shared data segments are not supported yet.");
      return {};
    }
    if (is_shared) module_->has_shared_part = true;
    if (tracer_) {
      if (is_shared) tracer_->Description(" shared");
      tracer_->NextLine();
    }
    bool is_active = status_flag == SegmentFlags::kActiveNoIndex ||
                     status_flag == SegmentFlags::kActiveWithIndex;
    uint32_t mem_index = status_flag == SegmentFlags::kActiveWithIndex
                             ? consume_u32v("memory index", tracer_)
                             : 0;
    ConstantExpression offset;
    if (is_active) {
      size_t num_memories = module_->memories.size();
      if (mem_index >= num_memories) {
        errorf(pos,
               "invalid memory index %u for data section (having %zu memor%s)",
               mem_index, num_memories, num_memories == 1 ? "y" : "ies");
        return {};
      }
      ValueType expected_type =
          module_->memories[mem_index].is_memory64() ? kWasmI64 : kWasmI32;
      offset = consume_init_expr(module_.get(), expected_type, is_shared);
    }
    return {is_active, is_shared, mem_index, offset};
  }
References consume_init_expr(), v8::internal::wasm::Decoder::consume_u32v(), v8::internal::wasm::ITracer::Description(), enabled_features_, v8::internal::wasm::Decoder::error(), v8::internal::wasm::Decoder::errorf(), v8::internal::is_shared, v8::internal::wasm::kActiveNoIndex, v8::internal::wasm::kActiveWithIndex, v8::internal::wasm::kPassive, v8::internal::wasm::kWasmI32, v8::internal::wasm::kWasmI64, module_, v8::internal::wasm::ITracer::NextLine(), v8::internal::wasm::Decoder::pc(), tracer_, and V8_UNLIKELY.
Referenced by DecodeDataSection().
consume_described_type()
TypeDefinition v8::internal::wasm::ModuleDecoderImpl::consume_described_type (bool is_descriptor, bool is_shared) [inline]
Definition at line 626 of file module-decoder-impl.h.
                                                                            {
    uint8_t kind = read_u8<Decoder::FullValidationTag>(pc(), "type kind");
    if (kind == kWasmDescriptorCode) {
      if (!enabled_features_.has_custom_descriptors()) {
        error(pc(),
              "descriptor types need --experimental-wasm-custom-descriptors");
        return {};
      }
      detected_features_->add_custom_descriptors();
      consume_bytes(1, " described_by", tracer_);
      const uint8_t* pos = pc();
      uint32_t descriptor = consume_u32v("descriptor", tracer_);
      if (descriptor >= module_->types.size()) {
        errorf(pos, "descriptor type index %u is out of bounds", descriptor);
        return {};
      }
      if (tracer_) tracer_->NextLine();
      TypeDefinition type =
          consume_base_type_definition(is_descriptor, is_shared);
      if (type.kind != TypeDefinition::kStruct) {
        error(pos - 1, "'descriptor' may only be used with structs");
        return {};
      }
      type.descriptor = ModuleTypeIndex{descriptor};
      return type;
    } else {
      return consume_base_type_definition(is_descriptor, is_shared);
    }
  }
References consume_base_type_definition(), v8::internal::wasm::Decoder::consume_bytes(), v8::internal::wasm::Decoder::consume_u32v(), detected_features_, enabled_features_, v8::internal::wasm::Decoder::error(), v8::internal::wasm::Decoder::errorf(), v8::internal::is_shared, v8::internal::wasm::TypeDefinition::kStruct, v8::internal::wasm::kWasmDescriptorCode, module_, v8::internal::wasm::ITracer::NextLine(), v8::internal::wasm::Decoder::pc(), tracer_, and v8::internal::tracing::type.
Referenced by consume_describing_type().
consume_describing_type()
TypeDefinition v8::internal::wasm::ModuleDecoderImpl::consume_describing_type (size_t current_type_index, bool is_shared) [inline]
Definition at line 656 of file module-decoder-impl.h.
                                                         {
    uint8_t kind = read_u8<Decoder::FullValidationTag>(pc(), "type kind");
    if (kind == kWasmDescribesCode) {
      if (!enabled_features_.has_custom_descriptors()) {
        error(pc(),
              "descriptor types need --experimental-wasm-custom-descriptors");
        return {};
      }
      detected_features_->add_custom_descriptors();
      consume_bytes(1, " describes", tracer_);
      const uint8_t* pos = pc();
      uint32_t describes = consume_u32v("describes", tracer_);
      if (describes >= current_type_index) {
        error(pos, "types can only describe previously-declared types");
        return {};
      }
      if (tracer_) tracer_->NextLine();
      TypeDefinition type = consume_described_type(true, is_shared);
      if (type.kind != TypeDefinition::kStruct) {
        error(pos - 1, "'describes' may only be used with structs");
        return {};
      }
      type.describes = ModuleTypeIndex{describes};
      return type;
    } else {
      return consume_described_type(false, is_shared);
    }
  }
References v8::internal::wasm::Decoder::consume_bytes(), consume_described_type(), v8::internal::wasm::Decoder::consume_u32v(), detected_features_, enabled_features_, v8::internal::wasm::Decoder::error(), v8::internal::is_shared, v8::internal::wasm::TypeDefinition::kStruct, v8::internal::wasm::kWasmDescribesCode, v8::internal::wasm::ITracer::NextLine(), v8::internal::wasm::Decoder::pc(), tracer_, and v8::internal::tracing::type.
Referenced by consume_shared_type().
consume_element_func_index()
uint32_t v8::internal::wasm::ModuleDecoderImpl::consume_element_func_index (WasmModule * module, ValueType expected) [inline], [private]
Definition at line 2851 of file module-decoder-impl.h.
                                                                              {
    WasmFunction* func = nullptr;
    const uint8_t* initial_pc = pc();
    uint32_t index = consume_func_index(module, &func);
    if (tracer_) tracer_->NextLine();
    if (failed()) return index;
    DCHECK_NOT_NULL(func);
    DCHECK_EQ(index, func->func_index);
    ValueType entry_type =
        ValueType::Ref(func->sig_index, module->type(func->sig_index).is_shared,
                       RefTypeKind::kFunction);
    if (V8_LIKELY(expected == kWasmFuncRef &&
                  !enabled_features_.has_shared())) {
      DCHECK(module->type(func->sig_index).kind == TypeDefinition::kFunction);
      DCHECK(IsSubtypeOf(entry_type, expected, module));
    } else if (V8_UNLIKELY(!IsSubtypeOf(entry_type, expected, module))) {
      errorf(initial_pc,
             "Invalid type in element entry: expected %s, got %s instead.",
             expected.name().c_str(), entry_type.name().c_str());
      return index;
    }
    func->declared = true;
    return index;
  }
References consume_func_index(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NOT_NULL, v8::internal::wasm::WasmFunction::declared, enabled_features_, v8::internal::wasm::Decoder::errorf(), v8::internal::wasm::Decoder::failed(), v8::internal::wasm::WasmFunction::func_index, v8::internal::index, v8::internal::wasm::TypeDefinition::is_shared, v8::internal::wasm::IsSubtypeOf(), v8::internal::wasm::kFunction, v8::internal::wasm::TypeDefinition::kFunction, v8::internal::wasm::TypeDefinition::kind, v8::internal::wasm::kWasmFuncRef, v8::internal::wasm::ValueTypeBase::name(), v8::internal::wasm::ITracer::NextLine(), v8::internal::wasm::Decoder::pc(), v8::internal::wasm::ValueType::Ref(), v8::internal::wasm::WasmFunction::sig_index, tracer_, v8::internal::wasm::WasmModule::type(), V8_LIKELY, and V8_UNLIKELY.
Referenced by consume_element_segment_entry().
consume_element_segment_entry()
ConstantExpression v8::internal::wasm::ModuleDecoderImpl::consume_element_segment_entry (WasmModule * module, const WasmElemSegment & segment) [inline]
Definition at line 2041 of file module-decoder-impl.h.
                                                          {
    if (segment.element_type == WasmElemSegment::kExpressionElements) {
      return consume_init_expr(module, segment.type, segment.shared);
    } else {
      return ConstantExpression::RefFunc(
          consume_element_func_index(module, segment.type));
    }
  }
References consume_element_func_index(), consume_init_expr(), v8::internal::wasm::WasmElemSegment::element_type, v8::internal::wasm::WasmElemSegment::kExpressionElements, v8::internal::wasm::ConstantExpression::RefFunc(), v8::internal::wasm::WasmElemSegment::shared, and v8::internal::wasm::WasmElemSegment::type.
Referenced by DecodeElementSection(), and v8::internal::wasm::ModuleDisassembler::PrintModule().
consume_element_segment_header()
WasmElemSegment v8::internal::wasm::ModuleDecoderImpl::consume_element_segment_header () [inline], [private]
Definition at line 2636 of file module-decoder-impl.h.
                                                   {
    const uint8_t* pos = pc();
    // The mask for the bit in the flag which indicates if the segment is
    // active or not (0 is active).
    constexpr uint8_t kNonActiveMask = 1 << 0;
    // The mask for the bit in the flag which indicates:
    // - for active tables, if the segment has an explicit table index field.
    // - for non-active tables, whether the table is declarative (vs. passive).
    constexpr uint8_t kHasTableIndexOrIsDeclarativeMask = 1 << 1;
    // The mask for the bit in the flag which indicates if the functions of this
    // segment are defined as function indices (0) or constant expressions (1).
    constexpr uint8_t kExpressionsAsElementsMask = 1 << 2;
    // The mask for the bit which denotes whether this segment is shared.
    constexpr uint8_t kSharedFlag = 1 << 3;
    constexpr uint8_t kFullMask = kNonActiveMask |
                                  kHasTableIndexOrIsDeclarativeMask |
                                  kExpressionsAsElementsMask | kSharedFlag;
    uint32_t flag = consume_u32v("flag", tracer_);
    if ((flag & kFullMask) != flag) {
      errorf(pos, "illegal flag value %u", flag);
      return {};
    }
    bool is_shared = flag & kSharedFlag;
    if (is_shared && !enabled_features_.has_shared()) {
      errorf(pos, "illegal flag value %u", flag);
      return {};
    }
    if (is_shared) {
      // TODO(42204563): Support shared element segments.
      error(pos, "shared element segments are not supported yet.");
      return {};
    }
    if (is_shared) module_->has_shared_part = true;
    const WasmElemSegment::Status status =
        (flag & kNonActiveMask) ? (flag & kHasTableIndexOrIsDeclarativeMask)
                                      ? WasmElemSegment::kStatusDeclarative
                                      : WasmElemSegment::kStatusPassive
                                : WasmElemSegment::kStatusActive;
    const bool is_active = status == WasmElemSegment::kStatusActive;
    if (tracer_) {
      tracer_->Description(": ");
      tracer_->Description(status == WasmElemSegment::kStatusActive ? "active"
                           : status == WasmElemSegment::kStatusPassive
                               ? "passive,"
                               : "declarative,");
    }
    WasmElemSegment::ElementType element_type =
        flag & kExpressionsAsElementsMask
            ? WasmElemSegment::kExpressionElements
            : WasmElemSegment::kFunctionIndexElements;
    const bool has_table_index =
        is_active && (flag & kHasTableIndexOrIsDeclarativeMask);
    uint32_t table_index = 0;
    if (has_table_index) {
      table_index = consume_u32v(", table index", tracer_);
      if (tracer_) tracer_->Description(table_index);
    }
    if (V8_UNLIKELY(is_active && table_index >= module_->tables.size())) {
      // If `has_table_index`, we have an explicit table index. Otherwise, we
      // always have the implicit table index 0.
      errorf(pos, "out of bounds%s table index %u",
             has_table_index ? "" : " implicit", table_index);
      return {};
    }
    ValueType table_type =
        is_active ? module_->tables[table_index].type : kWasmBottom;
    ConstantExpression offset;
    if (is_active) {
      if (tracer_) {
        tracer_->Description(", offset:");
        tracer_->NextLine();
      }
      offset = consume_init_expr(
          module_.get(),
          module_->tables[table_index].is_table64() ? kWasmI64 : kWasmI32,
          is_shared);
      // Failed to parse offset initializer, return early.
      if (failed()) return {};
    }
    // Denotes an active segment without table index, type, or element kind.
    const bool backwards_compatible_mode =
        is_active && !(flag & kHasTableIndexOrIsDeclarativeMask);
    ValueType type;
    if (element_type == WasmElemSegment::kExpressionElements) {
      if (backwards_compatible_mode) {
        type = kWasmFuncRef;
      } else {
        if (tracer_) tracer_->Description(" element type:");
        type = consume_value_type(module_.get());
        if (failed()) return {};
      }
    } else {
      if (!backwards_compatible_mode) {
        // We have to check that there is an element kind of type Function. All
        // other element kinds are not valid yet.
        if (tracer_) tracer_->Description(" ");
        uint8_t val = consume_u8("element type: function", tracer_);
        if (V8_UNLIKELY(static_cast<ImportExportKindCode>(val) !=
                        kExternalFunction)) {
          errorf(pos, "illegal element kind 0x%x. Must be 0x%x", val,
                 kExternalFunction);
          return {};
        }
      }
      type = kWasmFuncRef.AsNonNull();
    }
    if (V8_UNLIKELY(is_active &&
                    !IsSubtypeOf(type, table_type, this->module_.get()))) {
      errorf(pos,
             "Element segment of type %s is not a subtype of referenced "
             "table %u (of type %s)",
             type.name().c_str(), table_index, table_type.name().c_str());
      return {};
    }
    // TODO(14616): Is this too restrictive?
    if (V8_UNLIKELY(is_active &&
                    (is_shared != module_->tables[table_index].shared))) {
      error(pos,
            "Shared (resp. non-shared) element segments must refer to shared "
            "(resp. non-shared) tables");
      return {};
    }
    uint32_t num_elem =
        consume_count(" number of elements", max_table_init_entries());
    if (is_active) {
      return {is_shared, type, table_index, std::move(offset),
              element_type, num_elem, pc_offset()};
    } else {
      return {status, is_shared, type, element_type, num_elem, pc_offset()};
    }
  }
References v8::internal::wasm::IndependentHeapType::AsNonNull(), consume_count(), consume_init_expr(), v8::internal::wasm::Decoder::consume_u32v(), v8::internal::wasm::Decoder::consume_u8(), consume_value_type(), v8::internal::wasm::ITracer::Description(), enabled_features_, v8::internal::wasm::Decoder::error(), v8::internal::wasm::Decoder::errorf(), v8::internal::wasm::Decoder::failed(), v8::internal::is_shared, v8::internal::wasm::IsSubtypeOf(), v8::internal::wasm::WasmElemSegment::kExpressionElements, v8::internal::wasm::kExternalFunction, v8::internal::wasm::WasmElemSegment::kFunctionIndexElements, v8::internal::wasm::WasmElemSegment::kStatusActive, v8::internal::wasm::WasmElemSegment::kStatusDeclarative, v8::internal::wasm::WasmElemSegment::kStatusPassive, v8::internal::wasm::kWasmBottom, v8::internal::wasm::kWasmFuncRef, v8::internal::wasm::kWasmI32, v8::internal::wasm::kWasmI64, v8::internal::wasm::max_table_init_entries(), module_, v8::internal::wasm::ValueTypeBase::name(), v8::internal::wasm::ITracer::NextLine(), v8::internal::wasm::Decoder::pc(), v8::internal::wasm::Decoder::pc_offset(), v8::internal::status, tracer_, v8::internal::tracing::type, and V8_UNLIKELY.
Referenced by DecodeElementSection().
consume_exception_attribute()
uint32_t v8::internal::wasm::ModuleDecoderImpl::consume_exception_attribute () [inline], [private]
Definition at line 2625 of file module-decoder-impl.h.
                                         {
    const uint8_t* pos = pc_;
    uint32_t attribute = consume_u32v("exception attribute");
    if (tracer_) tracer_->Bytes(pos, static_cast<uint32_t>(pc_ - pos));
    if (attribute != kExceptionAttribute) {
      errorf(pos, "exception attribute %u not supported", attribute);
      return 0;
    }
    return attribute;
  }
References v8::internal::wasm::ITracer::Bytes(), v8::internal::wasm::Decoder::consume_u32v(), v8::internal::wasm::Decoder::errorf(), v8::internal::wasm::kExceptionAttribute, v8::internal::wasm::Decoder::pc_, and tracer_.
Referenced by DecodeImportSection(), and DecodeTagSection().
consume_func_index()
uint32_t v8::internal::wasm::ModuleDecoderImpl::consume_func_index (WasmModule * module, WasmFunction ** func) [inline], [private]
Definition at line 2151 of file module-decoder-impl.h.
                                                                       {
    return consume_index("function", &module->functions, func);
  }
References consume_index(), and v8::internal::wasm::WasmModule::functions.
Referenced by consume_element_func_index(), DecodeExportSection(), and DecodeStartSection().
consume_global_flags()
std::pair<bool, bool> v8::internal::wasm::ModuleDecoderImpl::consume_global_flags () [inline], [private]
Definition at line 2260 of file module-decoder-impl.h.
                                             {
    uint8_t flags = consume_u8("global flags");
    if (flags & ~0b11) {
      errorf(pc() - 1, "invalid global flags 0x%x", flags);
      return {false, false};
    }
    bool mutability = flags & 0b1;
    bool shared = flags & 0b10;
    if (tracer_) {
      tracer_->Bytes(pc_ - 1, 1); // The flags byte.
      if (shared) tracer_->Description(" shared");
      tracer_->Description(mutability ? " mutable" : " immutable");
    }
    if (shared && !enabled_features_.has_shared()) {
      errorf(pc() - 1, "invalid global flags 0x%x", flags);
      return {false, false};
    }
    if (shared) {
      // TODO(42204563): Support shared globals.
      error(pc() - 1, "shared globals are not supported yet");
      return {false, false};
    }
    return {mutability, shared};
  }
References v8::internal::wasm::ITracer::Bytes(), v8::internal::wasm::Decoder::consume_u8(), v8::internal::wasm::ITracer::Description(), enabled_features_, v8::internal::wasm::Decoder::error(), v8::internal::wasm::Decoder::errorf(), v8::internal::flags, v8::internal::wasm::Decoder::pc(), v8::internal::wasm::Decoder::pc_, and tracer_.
Referenced by DecodeGlobalSection(), and DecodeImportSection().
consume_global_index()
uint32_t v8::internal::wasm::ModuleDecoderImpl::consume_global_index (WasmModule * module, WasmGlobal ** global) [inline], [private]
Definition at line 2155 of file module-decoder-impl.h.
                                                                         {
    return consume_index("global", &module->globals, global);
  }
References consume_index(), and v8::internal::wasm::WasmModule::globals.
Referenced by DecodeExportSection().
consume_heap_type()
HeapType v8::internal::wasm::ModuleDecoderImpl::consume_heap_type () [inline], [private]
Definition at line 2527 of file module-decoder-impl.h.
                               {
    auto [heap_type, length] =
        value_type_reader::read_heap_type<FullValidationTag>(
            this, pc_,
            module_->origin == kWasmOrigin ? enabled_features_
                                           : WasmEnabledFeatures::None(),
            detected_features_);
    value_type_reader::ValidateHeapType<FullValidationTag>(
        this, pc_, module_.get(), heap_type);
    if (tracer_) {
      tracer_->Bytes(pc_, length);
      tracer_->Description(heap_type);
    }
    consume_bytes(length, "heap type");
    return heap_type;
  }
References v8::internal::wasm::ITracer::Bytes(), v8::internal::wasm::Decoder::consume_bytes(), v8::internal::wasm::ITracer::Description(), detected_features_, enabled_features_, v8::internal::wasm::kWasmOrigin, v8::internal::length, module_, v8::internal::wasm::WasmEnabledFeatures::None(), v8::internal::wasm::Decoder::pc_, and tracer_.
Referenced by consume_base_type_definition().
consume_index()
template<typename T >
uint32_t v8::internal::wasm::ModuleDecoderImpl::consume_index (const char * name, std::vector< T > * vector, T ** ptr) [inline], [private]
Definition at line 2168 of file module-decoder-impl.h.
                                                                          {
    const uint8_t* pos = pc_;
    uint32_t index = consume_u32v("index", tracer_);
    if (tracer_) {
      tracer_->Description(": ");
      tracer_->Description(index);
    }
    if (index >= vector->size()) {
      errorf(pos, "%s index %u out of bounds (%d entr%s)", name, index,
             static_cast<int>(vector->size()),
             vector->size() == 1 ? "y" : "ies");
      *ptr = nullptr;
      return 0;
    }
    *ptr = &(*vector)[index];
    return index;
  }
References v8::internal::wasm::Decoder::consume_u32v(), v8::internal::wasm::ITracer::Description(), v8::internal::wasm::Decoder::errorf(), v8::internal::index, v8::internal::wasm::name(), v8::internal::wasm::Decoder::pc_, and tracer_.
Referenced by consume_func_index(), consume_global_index(), consume_table_index(), and consume_tag_index().
consume_init_expr()
ConstantExpression v8::internal::wasm::ModuleDecoderImpl::consume_init_expr (WasmModule * module, ValueType expected, bool is_shared, bool * ends_with_struct_new = nullptr) [inline], [private]
Definition at line 2345 of file module-decoder-impl.h.
                                                                             {
    // The error message mimics the one generated by the {WasmFullDecoder}.
#define TYPE_CHECK(found) \
  if (V8_UNLIKELY(!IsSubtypeOf(found, expected, module))) { \
    errorf(pc() + 1, \
           "type error in constant expression[0] (expected %s, got %s)", \
           expected.name().c_str(), found.name().c_str()); \
    return {}; \
  }
    if (tracer_) tracer_->NextLineIfNonEmpty();
    // To avoid initializing a {WasmFullDecoder} for the most common
    // expressions, we replicate their decoding and validation here. The
    // manually handled cases correspond to {ConstantExpression}'s kinds.
    // We need to make sure to check that the expression ends in {kExprEnd};
    // otherwise, it is just the first operand of a composite expression, and we
    // fall back to the default case.
    if (!more()) {
      error("Beyond end of code");
      return {};
    }
    switch (static_cast<WasmOpcode>(*pc())) {
      case kExprI32Const: {
        auto [value, length] =
            read_i32v<FullValidationTag>(pc() + 1, "i32.const");
        if (V8_UNLIKELY(failed())) return {};
        if (V8_LIKELY(lookahead(1 + length, kExprEnd))) {
          TYPE_CHECK(kWasmI32)
          if (tracer_) {
            tracer_->InitializerExpression(pc_, pc_ + length + 2, kWasmI32);
          }
          consume_bytes(length + 2);
          return ConstantExpression::I32Const(value);
        }
        break;
      }
      case kExprRefFunc: {
        auto [index, length] =
            read_u32v<FullValidationTag>(pc() + 1, "ref.func");
        if (V8_UNLIKELY(failed())) return {};
        if (V8_LIKELY(lookahead(1 + length, kExprEnd))) {
          if (V8_UNLIKELY(index >= module->functions.size())) {
            errorf(pc() + 1, "function index %u out of bounds", index);
            return {};
          }
          ModuleTypeIndex functype{module->functions[index].sig_index};
          bool functype_is_shared = module->type(functype).is_shared;
          ValueType type = ValueType::Ref(functype, functype_is_shared,
                                          RefTypeKind::kFunction)
                               .AsExactIfEnabled(enabled_features_);
          TYPE_CHECK(type)
          if (V8_UNLIKELY(is_shared && !type.is_shared())) {
            error(pc(), "ref.func does not have a shared type");
            return {};
          }
          module->functions[index].declared = true;
          if (tracer_) {
            tracer_->InitializerExpression(pc_, pc_ + length + 2, type);
          }
          consume_bytes(length + 2);
          return ConstantExpression::RefFunc(index);
        }
        break;
      }
      case kExprRefNull: {
        auto [type, length] =
            value_type_reader::read_heap_type<FullValidationTag>(
                this, pc() + 1, enabled_features_, detected_features_);
        value_type_reader::ValidateHeapType<FullValidationTag>(this, pc_,
                                                               module, type);
        if (V8_UNLIKELY(failed())) return {};
        value_type_reader::Populate(&type, module);
        if (V8_LIKELY(lookahead(1 + length, kExprEnd))) {
          TYPE_CHECK(ValueType::RefNull(type))
          if (V8_UNLIKELY(is_shared && !type.is_shared())) {
            error(pc(), "ref.null does not have a shared type");
            return {};
          }
          if (tracer_) {
            tracer_->InitializerExpression(pc_, pc_ + length + 2,
                                           ValueType::RefNull(type));
          }
          consume_bytes(length + 2);
          return ConstantExpression::RefNull(type);
        }
        break;
      }
      default:
        break;
    }
#undef TYPE_CHECK
    auto sig = FixedSizeSignature<ValueType>::Returns(expected);
    FunctionBody body(&sig, this->pc_offset(), pc_, end_, is_shared);
    WasmDetectedFeatures detected;
    ConstantExpression result;
    {
      // We need a scope for the decoder because its destructor resets some Zone
      // elements, which has to be done before we reset the Zone afterwards.
      WasmFullDecoder<Decoder::FullValidationTag, ConstantExpressionInterface,
                      kConstantExpression>
          decoder(&init_expr_zone_, module, enabled_features_, &detected, body,
                  module);
      uint32_t offset = this->pc_offset();
      decoder.DecodeFunctionBody();
      if (tracer_) {
        // In case of error, decoder.end() is set to the position right before
        // the byte(s) that caused the error. For debugging purposes, we should
        // print these bytes, but we don't know how many of them there are, so
        // for now we have to guess. For more accurate behavior, we'd have to
        // pass {num_invalid_bytes} to every {decoder->DecodeError()} call.
        static constexpr size_t kInvalidBytesGuess = 4;
        const uint8_t* end =
            decoder.ok() ? decoder.end()
                         : std::min(decoder.end() + kInvalidBytesGuess, end_);
        tracer_->InitializerExpression(pc_, end, expected);
      }
      this->pc_ = decoder.end();
      if (decoder.failed()) {
        error(decoder.error().offset(), decoder.error().message().c_str());
        return {};
      }
      if (!decoder.interface().end_found()) {
        error("constant expression is missing 'end'");
        return {};
      }
      result = ConstantExpression::WireBytes(
          offset, static_cast<uint32_t>(decoder.end() - decoder.start()));
      if (ends_with_struct_new) {
        *ends_with_struct_new = decoder.interface().ends_with_struct_new();
      }
    }
    // We reset the zone here; its memory is not used anymore, and we do not
    // want memory from all constant expressions to add up.
    init_expr_zone_.Reset();
    return result;
  }
References v8::internal::wasm::ValueType::AsExactIfEnabled(), v8::internal::wasm::Decoder::consume_bytes(), detected_features_, enabled_features_, v8::internal::wasm::Decoder::end(), v8::internal::wasm::Decoder::end_, v8::internal::wasm::Decoder::error(), v8::internal::wasm::Decoder::errorf(), v8::internal::wasm::Decoder::failed(), v8::internal::wasm::WasmModule::functions, v8::internal::wasm::ConstantExpression::I32Const(), v8::internal::index, init_expr_zone_, v8::internal::wasm::ITracer::InitializerExpression(), v8::internal::is_shared, v8::internal::wasm::TypeDefinition::is_shared, v8::internal::wasm::kConstantExpression, v8::internal::wasm::kFunction, v8::internal::wasm::kWasmI32, v8::internal::length, v8::internal::wasm::Decoder::lookahead(), v8::internal::wasm::Decoder::more(), v8::internal::wasm::ITracer::NextLineIfNonEmpty(), v8::internal::wasm::Decoder::pc(), v8::internal::wasm::Decoder::pc_, v8::internal::wasm::Decoder::pc_offset(), v8::internal::wasm::value_type_reader::Populate(), v8::internal::wasm::ValueType::Ref(), v8::internal::wasm::ConstantExpression::RefFunc(), v8::internal::wasm::ConstantExpression::RefNull(), v8::internal::wasm::ValueType::RefNull(), v8::internal::Zone::Reset(), v8::base::internal::result, v8::internal::FixedSizeSignature< T, kNumReturns, kNumParams >::Returns(), v8::internal::sig, tracer_, v8::internal::tracing::type, v8::internal::wasm::WasmModule::type(), TYPE_CHECK, V8_LIKELY, V8_UNLIKELY, v8::internal::value, and v8::internal::wasm::ConstantExpression::WireBytes().
Referenced by consume_data_segment_header(), consume_element_segment_entry(), consume_element_segment_header(), DecodeGlobalSection(), DecodeInitExprForTesting(), and DecodeTableSection().
consume_limits_byte()
template<LimitsByteType limits_type>
LimitsByte v8::internal::wasm::ModuleDecoderImpl::consume_limits_byte () [inline], [private]
Definition at line 2203 of file module-decoder-impl.h.
                                   {
    if (tracer_) tracer_->Bytes(pc_, 1);
    LimitsByte limits{consume_u8(
        limits_type == kMemory ? "memory limits flags" : "table limits flags")};
    if (!limits.is_valid()) {
      errorf(pc() - 1, "invalid %s limits flags 0x%x",
             limits_type == kMemory ? "memory" : "table", limits.flags);
    }
    if (limits.is_shared()) {
      if constexpr (limits_type == kMemory) {
        // V8 does not support shared memory without a maximum.
        if (!limits.has_maximum()) {
          error(pc() - 1, "shared memory must have a maximum defined");
        }
        // TODO(42204563): Implement proper handling of shared memories when
        // Shared Everything is enabled.
      } else if (!enabled_features_.has_shared()) { // table
        error(pc() - 1, "invalid table limits flags");
      } else {
        // TODO(42204563): Support shared tables.
        error(pc() - 1, "shared tables are not supported yet");
      }
    }
    if (tracer_) {
      if (limits.is_shared()) tracer_->Description(" shared");
      if (limits.is_64bit()) {
        tracer_->Description(limits_type == kMemory ? " mem64" : " table64");
      }
      tracer_->Description(limits.has_maximum() ? " with maximum"
                                                : " no maximum");
      tracer_->NextLine();
    }
    return limits;
  }
References v8::internal::wasm::ITracer::Bytes(), v8::internal::wasm::Decoder::consume_u8(), v8::internal::wasm::ITracer::Description(), enabled_features_, v8::internal::wasm::Decoder::error(), v8::internal::wasm::Decoder::errorf(), kMemory, v8::internal::wasm::ITracer::NextLine(), v8::internal::wasm::Decoder::pc(), v8::internal::wasm::Decoder::pc_, and tracer_.
consume_memory_flags()
void v8::internal::wasm::ModuleDecoderImpl::consume_memory_flags (WasmMemory * memory) [inline], [private]
Definition at line 2250 of file module-decoder-impl.h.
                                                {
    LimitsByte limits = consume_limits_byte<kMemory>();
    memory->has_maximum_pages = limits.has_maximum();
    memory->is_shared = limits.is_shared();
    memory->address_type = limits.address_type();
    if (memory->is_shared) detected_features_->add_shared_memory();
    if (memory->is_memory64()) detected_features_->add_memory64();
  }
References v8::internal::wasm::ModuleDecoderImpl::LimitsByte::address_type(), v8::internal::wasm::WasmMemory::address_type, detected_features_, v8::internal::wasm::ModuleDecoderImpl::LimitsByte::has_maximum(), v8::internal::wasm::WasmMemory::has_maximum_pages, v8::internal::wasm::WasmMemory::is_memory64(), v8::internal::wasm::ModuleDecoderImpl::LimitsByte::is_shared(), and v8::internal::wasm::WasmMemory::is_shared.
Referenced by DecodeImportSection(), and DecodeMemorySection().
consume_mutability()
bool v8::internal::wasm::ModuleDecoderImpl::consume_mutability () [inline], [private]
Definition at line 2495 of file module-decoder-impl.h.
                            {
    if (tracer_) tracer_->Bytes(pc_, 1);
    uint8_t val = consume_u8("mutability");
    if (tracer_) {
      tracer_->Description(val == 0 ? " immutable"
                           : val == 1 ? " mutable"
                                      : " invalid");
    }
    if (val > 1) error(pc_ - 1, "invalid mutability");
    return val != 0;
  }
References v8::internal::wasm::ITracer::Bytes(), v8::internal::wasm::Decoder::consume_u8(), v8::internal::wasm::ITracer::Description(), v8::internal::wasm::Decoder::error(), v8::internal::wasm::Decoder::pc_, and tracer_.
Referenced by consume_array(), and consume_struct().
consume_resizable_limits()
void v8::internal::wasm::ModuleDecoderImpl::consume_resizable_limits (const char * name, const char * units, uint32_t max_initial, uint32_t * initial, bool has_maximum, uint64_t max_maximum, uint64_t * maximum, ResizableLimitsType type) [inline], [private]
Definition at line 2286 of file module-decoder-impl.h.
                                                                         {
    const uint8_t* pos = pc();
    // Note that even if we read the values as 64-bit value, all V8 limits are
    // still within uint32_t range.
    uint64_t initial_64 = type == k64BitLimits
                              ? consume_u64v("initial size", tracer_)
                              : consume_u32v("initial size", tracer_);
    if (initial_64 > max_initial) {
      errorf(pos,
             "initial %s size (%" PRIu64
             " %s) is larger than implementation limit (%u %s)",
             name, initial_64, units, max_initial, units);
    }
    *initial = static_cast<uint32_t>(initial_64);
    if (tracer_) {
      tracer_->Description(*initial);
      tracer_->NextLine();
    }
    if (has_maximum) {
      pos = pc();
      uint64_t maximum_64 = type == k64BitLimits
                                ? consume_u64v("maximum size", tracer_)
                                : consume_u32v("maximum size", tracer_);
      if (maximum_64 > max_maximum) {
        errorf(pos,
               "maximum %s size (%" PRIu64
               " %s) is larger than implementation limit (%" PRIu64 " %s)",
               name, maximum_64, units, max_maximum, units);
      }
      if (maximum_64 < *initial) {
        errorf(pos,
               "maximum %s size (%" PRIu64 " %s) is less than initial (%u %s)",
               name, maximum_64, units, *initial, units);
      }
      *maximum = maximum_64;
      if (tracer_) {
        tracer_->Description(*maximum);
        tracer_->NextLine();
      }
    } else {
      *maximum = max_initial;
    }
  }
References v8::internal::wasm::Decoder::consume_u32v(), v8::internal::wasm::Decoder::consume_u64v(), v8::internal::wasm::ITracer::Description(), v8::internal::wasm::Decoder::errorf(), k64BitLimits, v8::internal::wasm::name(), v8::internal::wasm::ITracer::NextLine(), v8::internal::wasm::Decoder::pc(), tracer_, and v8::internal::tracing::type.
Referenced by DecodeImportSection(), DecodeMemorySection(), and DecodeTableSection().
consume_shared_type()
TypeDefinition v8::internal::wasm::ModuleDecoderImpl::consume_shared_type (size_t current_type_index) [inline]
Definition at line 686 of file module-decoder-impl.h.
                                                                {
    uint8_t kind = read_u8<Decoder::FullValidationTag>(pc(), "type kind");
    if (kind == kSharedFlagCode) {
      if (!enabled_features_.has_shared()) {
        errorf(pc() - 1,
               "unknown type form: %d, enable with --experimental-wasm-shared",
               kind);
        return {};
      }
      module_->has_shared_part = true;
      consume_bytes(1, " shared", tracer_);
      TypeDefinition type = consume_describing_type(current_type_index, true);
      DCHECK(type.is_shared);
      if (type.kind == TypeDefinition::kFunction ||
          type.kind == TypeDefinition::kCont) {
        // TODO(42204563): Support shared functions/continuations.
        error(pc() - 1, "shared functions/continuations are not supported yet");
        return {};
      }
      return type;
    } else {
      return consume_describing_type(current_type_index, false);
    }
  }
References v8::internal::wasm::Decoder::consume_bytes(), consume_describing_type(), v8::internal::DCHECK(), enabled_features_, v8::internal::wasm::Decoder::error(), v8::internal::wasm::Decoder::errorf(), v8::internal::wasm::TypeDefinition::kCont, v8::internal::wasm::TypeDefinition::kFunction, v8::internal::wasm::kSharedFlagCode, module_, v8::internal::wasm::Decoder::pc(), tracer_, and v8::internal::tracing::type.
Referenced by consume_subtype_definition().
consume_sig()
const FunctionSig* v8::internal::wasm::ModuleDecoderImpl::consume_sig (Zone * zone) [inline], [private]
Definition at line 2560 of file module-decoder-impl.h.
                                             {
    if (tracer_) tracer_->NextLine();
    // Parse parameter types.
    uint32_t param_count =
        consume_count("param count", kV8MaxWasmFunctionParams);
    // We don't know the return count yet, so decode the parameters into a
    // temporary SmallVector. This needs to be copied over into the permanent
    // storage later.
    base::SmallVector<ValueType, 8> params{param_count};
    for (uint32_t i = 0; i < param_count; ++i) {
      params[i] = consume_value_type();
      if (tracer_) tracer_->NextLineIfFull();
    }
    if (tracer_) tracer_->NextLineIfNonEmpty();
    // Parse return types.
    uint32_t return_count =
        consume_count("return count", kV8MaxWasmFunctionReturns);
    if (return_count > 1) {
      detected_features_->add_multi_value();
    }
    // Now that we know the param count and the return count, we can allocate
    // the permanent storage.
    ValueType* sig_storage =
        zone->AllocateArray<ValueType>(param_count + return_count);
    // Note: Returns come first in the signature storage.
    std::copy_n(params.begin(), param_count, sig_storage + return_count);
    for (uint32_t i = 0; i < return_count; ++i) {
      sig_storage[i] = consume_value_type();
      if (tracer_) tracer_->NextLineIfFull();
    }
    if (tracer_) tracer_->NextLineIfNonEmpty();
    return zone->New<FunctionSig>(return_count, param_count, sig_storage);
  }
References v8::internal::Zone::AllocateArray(), consume_count(), consume_value_type(), detected_features_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::kV8MaxWasmFunctionParams, v8::internal::wasm::kV8MaxWasmFunctionReturns, v8::internal::Zone::New(), v8::internal::wasm::ITracer::NextLine(), v8::internal::wasm::ITracer::NextLineIfFull(), v8::internal::wasm::ITracer::NextLineIfNonEmpty(), and tracer_.
Referenced by consume_base_type_definition(), DecodeFunctionSignatureForTesting(), and DecodeSingleFunctionForTesting().
consume_sig_index()
ModuleTypeIndex v8::internal::wasm::ModuleDecoderImpl::consume_sig_index (WasmModule * module, const FunctionSig ** sig) [inline], [private]
Definition at line 2100 of file module-decoder-impl.h.
                                                             {
    const uint8_t* pos = pc_;
    ModuleTypeIndex sig_index{consume_u32v("signature index")};
    if (tracer_) tracer_->Bytes(pos, static_cast<uint32_t>(pc_ - pos));
    if (!module->has_signature(sig_index)) {
      errorf(pos, "no signature at index %u (%d types)", sig_index.index,
             static_cast<int>(module->types.size()));
      *sig = nullptr;
      return {};
    }
    *sig = module->signature(sig_index);
    if (tracer_) {
      tracer_->Description(*sig);
      tracer_->NextLine();
    }
    return sig_index;
  }
References v8::internal::wasm::ITracer::Bytes(), v8::internal::wasm::Decoder::consume_u32v(), v8::internal::wasm::ITracer::Description(), v8::internal::wasm::Decoder::errorf(), v8::internal::wasm::WasmModule::has_signature(), v8::internal::wasm::ITracer::NextLine(), v8::internal::wasm::Decoder::pc_, v8::internal::sig, v8::internal::wasm::WasmModule::signature(), tracer_, and v8::internal::wasm::WasmModule::types.
Referenced by consume_tag_sig_index(), DecodeFunctionSection(), and DecodeImportSection().
consume_storage_type()
ValueType v8::internal::wasm::ModuleDecoderImpl::consume_storage_type () [inline], [private]
Definition at line 2545 of file module-decoder-impl.h.
                                   {
    uint8_t opcode = read_u8<FullValidationTag>(this->pc());
    switch (opcode) {
      case kI8Code:
        consume_bytes(1, " i8", tracer_);
        return kWasmI8;
      case kI16Code:
        consume_bytes(1, " i16", tracer_);
        return kWasmI16;
      default:
        // It is not a packed type, so it has to be a value type.
        return consume_value_type();
    }
  }
References v8::internal::wasm::Decoder::consume_bytes(), consume_value_type(), v8::internal::wasm::kI16Code, v8::internal::wasm::kI8Code, v8::internal::wasm::kWasmI16, v8::internal::wasm::kWasmI8, v8::internal::wasm::Decoder::pc(), and tracer_.
Referenced by consume_array(), and consume_struct().
consume_struct()
const StructType* v8::internal::wasm::ModuleDecoderImpl::consume_struct (Zone * zone, bool is_descriptor, bool is_shared) [inline], [private]
Definition at line 2596 of file module-decoder-impl.h.
                                                   {
    uint32_t field_count =
        consume_count(", field count", kV8MaxWasmStructFields);
    if (failed()) return nullptr;
    ValueType* fields = zone->AllocateArray<ValueType>(field_count);
    bool* mutabilities = zone->AllocateArray<bool>(field_count);
    for (uint32_t i = 0; ok() && i < field_count; ++i) {
      fields[i] = consume_storage_type();
      mutabilities[i] = consume_mutability();
      if (tracer_) tracer_->NextLine();
    }
    if (failed()) return nullptr;
    uint32_t* offsets = zone->AllocateArray<uint32_t>(field_count);
    StructType* result = zone->New<StructType>(
        field_count, offsets, fields, mutabilities, is_descriptor, is_shared);
    result->InitializeOffsets();
    return result;
  }
References v8::internal::Zone::AllocateArray(), consume_count(), consume_mutability(), consume_storage_type(), v8::internal::wasm::Decoder::failed(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::is_shared, v8::internal::wasm::kV8MaxWasmStructFields, v8::internal::Zone::New(), v8::internal::wasm::ITracer::NextLine(), v8::internal::wasm::Decoder::ok(), v8::base::internal::result, and tracer_.
Referenced by consume_base_type_definition().
consume_subtype_definition()
TypeDefinition v8::internal::wasm::ModuleDecoderImpl::consume_subtype_definition (size_t current_type_index) [inline]
Definition at line 713 of file module-decoder-impl.h.
                                                                       {
    uint8_t kind = read_u8<Decoder::FullValidationTag>(pc(), "type kind");
    if (kind == kWasmSubtypeCode || kind == kWasmSubtypeFinalCode) {
      module_->is_wasm_gc = true;
      bool is_final = kind == kWasmSubtypeFinalCode;
      consume_bytes(1, is_final ? " subtype final, " : " subtype extensible, ",
                    tracer_);
      constexpr uint32_t kMaximumSupertypes = 1;
      uint32_t supertype_count =
          consume_count("supertype count", kMaximumSupertypes);
      uint32_t supertype = kNoSuperType.index;
      if (supertype_count == 1) {
        supertype = consume_u32v("supertype", tracer_);
        if (supertype >= current_type_index) {
          errorf("type %u: invalid supertype %u", current_type_index,
                 supertype);
          return {};
        }
        if (tracer_) {
          tracer_->Description(supertype);
          tracer_->NextLine();
        }
      }
      TypeDefinition type = consume_shared_type(current_type_index);
      type.supertype = ModuleTypeIndex{supertype};
      type.is_final = is_final;
      return type;
    } else {
      return consume_shared_type(current_type_index);
    }
  }
References v8::internal::wasm::Decoder::consume_bytes(), consume_count(), consume_shared_type(), v8::internal::wasm::Decoder::consume_u32v(), v8::internal::wasm::ITracer::Description(), v8::internal::wasm::Decoder::errorf(), v8::internal::wasm::TypeIndex::index, v8::internal::wasm::kNoSuperType, v8::internal::wasm::kWasmSubtypeCode, v8::internal::wasm::kWasmSubtypeFinalCode, module_, v8::internal::wasm::ITracer::NextLine(), v8::internal::wasm::Decoder::pc(), tracer_, and v8::internal::tracing::type.
Referenced by DecodeTypeSection().
consume_table_flags()
void v8::internal::wasm::ModuleDecoderImpl::consume_table_flags (WasmTable * table) [inline], [private]
Definition at line 2241 of file module-decoder-impl.h.
                                             {
    LimitsByte limits = consume_limits_byte<kTable>();
    table->has_maximum_size = limits.has_maximum();
    table->shared = limits.is_shared();
    table->address_type = limits.address_type();
    if (table->is_table64()) detected_features_->add_memory64();
  }
References v8::internal::wasm::ModuleDecoderImpl::LimitsByte::address_type(), v8::internal::wasm::WasmTable::address_type, detected_features_, v8::internal::wasm::ModuleDecoderImpl::LimitsByte::has_maximum(), v8::internal::wasm::WasmTable::has_maximum_size, v8::internal::wasm::ModuleDecoderImpl::LimitsByte::is_shared(), v8::internal::wasm::WasmTable::is_table64(), and v8::internal::wasm::WasmTable::shared.
Referenced by DecodeImportSection(), and DecodeTableSection().
consume_table_index()
uint32_t v8::internal::wasm::ModuleDecoderImpl::consume_table_index (WasmModule * module, WasmTable ** table) [inline], [private]
Definition at line 2159 of file module-decoder-impl.h.
                                                                      {
    return consume_index("table", &module->tables, table);
  }
References consume_index(), and v8::internal::wasm::WasmModule::tables.
Referenced by DecodeExportSection().
consume_tag_index()
uint32_t v8::internal::wasm::ModuleDecoderImpl::consume_tag_index (WasmModule * module, WasmTag ** tag) [inline], [private]
Definition at line 2163 of file module-decoder-impl.h.
                                                                {
    return consume_index("tag", &module->tags, tag);
  }
References consume_index(), and v8::internal::wasm::WasmModule::tags.
Referenced by DecodeExportSection().
consume_tag_sig_index()
ModuleTypeIndex v8::internal::wasm::ModuleDecoderImpl::consume_tag_sig_index (WasmModule * module, const FunctionSig ** sig) [inline], [private]
Definition at line 2119 of file module-decoder-impl.h.
                                                                 {
    const uint8_t* pos = pc_;
    ModuleTypeIndex sig_index = consume_sig_index(module, sig);
    if (!enabled_features_.has_wasmfx() && *sig &&
        (*sig)->return_count() != 0) {
      errorf(pos, "tag signature %u has non-void return", sig_index);
      *sig = nullptr;
      return {};
    }
    return sig_index;
  }
References consume_sig_index(), enabled_features_, v8::internal::wasm::Decoder::errorf(), v8::internal::wasm::Decoder::pc_, and v8::internal::sig.
Referenced by DecodeImportSection(), and DecodeTagSection().
consume_value_type()
ValueType v8::internal::wasm::ModuleDecoderImpl::consume_value_type (const WasmModule * module = nullptr) [inline], [private]
Definition at line 2509 of file module-decoder-impl.h.
                                                                   {
    auto [result, length] =
        value_type_reader::read_value_type<FullValidationTag>(
            this, pc_,
            module_->origin == kWasmOrigin ? enabled_features_
                                           : WasmEnabledFeatures::None(),
            detected_features_);
    value_type_reader::ValidateValueType<FullValidationTag>(
        this, pc_, module_.get(), result);
    if (ok() && module) value_type_reader::Populate(&result, module);
    if (tracer_) {
      tracer_->Bytes(pc_, length);
      tracer_->Description(result);
    }
    consume_bytes(length, "value type");
    return result;
  }
References v8::internal::wasm::ITracer::Bytes(), v8::internal::wasm::Decoder::consume_bytes(), v8::internal::wasm::ITracer::Description(), detected_features_, enabled_features_, v8::internal::wasm::kWasmOrigin, v8::internal::length, module_, v8::internal::wasm::WasmEnabledFeatures::None(), v8::internal::wasm::Decoder::ok(), v8::internal::wasm::Decoder::pc_, v8::internal::wasm::value_type_reader::Populate(), v8::base::internal::result, and tracer_.
Referenced by consume_element_segment_header(), consume_sig(), consume_storage_type(), DecodeGlobalSection(), DecodeImportSection(), and DecodeTableSection().
DecodeBranchHintsSection()
void v8::internal::wasm::ModuleDecoderImpl::DecodeBranchHintsSection () [inline]
Definition at line 1794 of file module-decoder-impl.h.
                                  {
    TRACE("DecodeBranchHints module+%d\n", static_cast<int>(pc_ - start_));
    detected_features_->add_branch_hinting();
    if (!has_seen_unordered_section(kBranchHintsSectionCode)) {
      set_seen_unordered_section(kBranchHintsSectionCode);
      // Use an inner decoder so that errors don't fail the outer decoder.
      Decoder inner(start_, pc_, end_, buffer_offset_);
      BranchHintInfo branch_hints;
      uint32_t func_count = inner.consume_u32v("number of functions");
      // Keep track of the previous function index to validate the ordering
      int64_t last_func_idx = -1;
      for (uint32_t i = 0; i < func_count; i++) {
        uint32_t func_idx = inner.consume_u32v("function index");
        if (int64_t{func_idx} <= last_func_idx) {
          inner.errorf("Invalid function index: %d", func_idx);
          break;
        }
        last_func_idx = func_idx;
        uint32_t num_hints = inner.consume_u32v("number of hints");
        BranchHintMap func_branch_hints;
        TRACE("DecodeBranchHints[%d] module+%d\n", func_idx,
              static_cast<int>(inner.pc() - inner.start()));
        // Keep track of the previous branch offset to validate the ordering
        int64_t last_br_off = -1;
        for (uint32_t j = 0; j < num_hints; ++j) {
          uint32_t br_off = inner.consume_u32v("branch instruction offset");
          if (int64_t{br_off} <= last_br_off) {
            inner.errorf("Invalid branch offset: %d", br_off);
            break;
          }
          last_br_off = br_off;
          uint32_t data_size = inner.consume_u32v("data size");
          if (data_size != 1) {
            inner.errorf("Invalid data size: %#x. Expected 1.", data_size);
            break;
          }
          uint32_t br_dir = inner.consume_u8("branch direction");
          TRACE("DecodeBranchHints[%d][%d] module+%d\n", func_idx, br_off,
                static_cast<int>(inner.pc() - inner.start()));
          BranchHint hint;
          switch (br_dir) {
            case 0:
              hint = BranchHint::kFalse;
              break;
            case 1:
              hint = BranchHint::kTrue;
              break;
            default:
              hint = BranchHint::kNone;
              inner.errorf(inner.pc(), "Invalid branch hint %#x", br_dir);
              break;
          }
          if (!inner.ok()) {
            break;
          }
          func_branch_hints.insert(br_off, hint);
        }
        if (!inner.ok()) {
          break;
        }
        branch_hints.emplace(func_idx, std::move(func_branch_hints));
      }
      // Extra unexpected bytes are an error.
      if (inner.more()) {
        inner.errorf("Unexpected extra bytes: %d\n",
                     static_cast<int>(inner.pc() - inner.start()));
      }
      // If everything went well, accept the hints for the module.
      if (inner.ok()) {
        module_->branch_hints = std::move(branch_hints);
      }
    }
    // Skip the whole branch hints section in the outer decoder.
    consume_bytes(static_cast<uint32_t>(end_ - start_), nullptr);
  }
References v8::internal::wasm::Decoder::buffer_offset_, v8::internal::wasm::Decoder::consume_bytes(), v8::internal::wasm::Decoder::consume_u32v(), v8::internal::wasm::Decoder::consume_u8(), detected_features_, v8::internal::wasm::Decoder::end_, v8::internal::wasm::Decoder::errorf(), has_seen_unordered_section(), v8::internal::wasm::BranchHintMap::insert(), v8::internal::wasm::kBranchHintsSectionCode, v8::internal::kFalse, v8::internal::kNone, v8::internal::kTrue, module_, v8::internal::wasm::Decoder::more(), v8::internal::wasm::Decoder::ok(), v8::internal::wasm::Decoder::pc(), v8::internal::wasm::Decoder::pc_, set_seen_unordered_section(), v8::internal::wasm::Decoder::start(), v8::internal::wasm::Decoder::start_, and v8::internal::TRACE().
Referenced by DecodeSection().
DecodeBuildIdSection()
void v8::internal::wasm::ModuleDecoderImpl::DecodeBuildIdSection () [inline]
Definition at line 1622 of file module-decoder-impl.h.
                              {
    Decoder inner(start_, pc_, end_, buffer_offset_);
    WireBytesRef build_id =
        consume_string(&inner, unibrow::Utf8Variant::kLossyUtf8, "build_id");
    if (inner.ok()) {
      module_->build_id = build_id;
      set_seen_unordered_section(kBuildIdSectionCode);
    }
    consume_bytes(static_cast<uint32_t>(end_ - start_), nullptr);
  }
References v8::internal::wasm::Decoder::buffer_offset_, v8::internal::wasm::Decoder::consume_bytes(), v8::internal::wasm::consume_string(), v8::internal::wasm::Decoder::end_, v8::internal::wasm::kBuildIdSectionCode, unibrow::kLossyUtf8, module_, v8::internal::wasm::Decoder::ok(), v8::internal::wasm::Decoder::pc_, set_seen_unordered_section(), and v8::internal::wasm::Decoder::start_.
Referenced by DecodeSection().
DecodeCodeSection()
void v8::internal::wasm::ModuleDecoderImpl::DecodeCodeSection () [inline]
Definition at line 1403 of file module-decoder-impl.h.
                           {
    // Make sure global offset were calculated before they get accessed during
    // function compilation.
    CalculateGlobalOffsets(module_.get());
    uint32_t code_section_start = pc_offset();
    uint32_t functions_count = consume_u32v("functions count", tracer_);
    if (tracer_) {
      tracer_->Description(functions_count);
      tracer_->NextLine();
    }
    CheckFunctionsCount(functions_count, code_section_start);
    auto inst_traces_it = this->inst_traces_.begin();
    std::vector<std::pair<uint32_t, uint32_t>> inst_traces;
    for (uint32_t i = 0; ok() && i < functions_count; ++i) {
      int function_index = module_->num_imported_functions + i;
      if (tracer_) {
        tracer_->Description("function #");
        tracer_->FunctionName(function_index);
        tracer_->NextLine();
      }
      const uint8_t* pos = pc();
      uint32_t size = consume_u32v("body size", tracer_);
      if (tracer_) {
        tracer_->Description(size);
        tracer_->NextLine();
      }
      if (size > kV8MaxWasmFunctionSize) {
        errorf(pos, "size %u > maximum function size %zu", size,
               kV8MaxWasmFunctionSize);
        return;
      }
      uint32_t offset = pc_offset();
      consume_bytes(size, "function body");
      if (failed()) break;
      DecodeFunctionBody(function_index, size, offset);
      // Now that the function has been decoded, we can compute module offsets.
      for (; inst_traces_it != this->inst_traces_.end() &&
             std::get<0>(*inst_traces_it) == i;
           ++inst_traces_it) {
        uint32_t trace_offset = offset + std::get<1>(*inst_traces_it);
        uint32_t mark_id = std::get<2>(*inst_traces_it);
        std::pair<uint32_t, uint32_t> trace_mark = {trace_offset, mark_id};
        inst_traces.push_back(trace_mark);
      }
    }
    // If we have actually decoded traces and they were all decoded without
    // error, then we can move them to the module. If any errors are found, it
    // is safe to throw away all traces.
    if (V8_UNLIKELY(!inst_traces.empty() &&
                    inst_traces_it == this->inst_traces_.end())) {
      // This adds an invalid entry at the end of the traces. An invalid entry
      // is defined as having an module offset of 0 and a markid of 0.
      inst_traces.push_back({0, 0});
      this->module_->inst_traces = std::move(inst_traces);
    }
    DCHECK_GE(pc_offset(), code_section_start);
    module_->code = {code_section_start, pc_offset() - code_section_start};
  }
References CalculateGlobalOffsets(), CheckFunctionsCount(), v8::internal::wasm::Decoder::consume_bytes(), v8::internal::wasm::Decoder::consume_u32v(), DCHECK_GE, DecodeFunctionBody(), v8::internal::wasm::ITracer::Description(), v8::internal::wasm::Decoder::errorf(), v8::internal::wasm::Decoder::failed(), v8::internal::wasm::ITracer::FunctionName(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, inst_traces_, v8::internal::wasm::kV8MaxWasmFunctionSize, module_, v8::internal::wasm::ITracer::NextLine(), v8::internal::wasm::Decoder::ok(), v8::internal::wasm::Decoder::pc(), v8::internal::wasm::Decoder::pc_offset(), size(), v8::internal::this, tracer_, and V8_UNLIKELY.
Referenced by DecodeSection().
DecodeCompilationHintsSection()
void v8::internal::wasm::ModuleDecoderImpl::DecodeCompilationHintsSection () [inline]
Definition at line 1698 of file module-decoder-impl.h.
                                       {
    TRACE("DecodeCompilationHints module+%d\n", static_cast<int>(pc_ - start_));
    // TODO(frgossen): Find a way to report compilation hint errors as warnings.
    // All except first occurrence after function section and before code
    // section are ignored.
    const bool before_function_section =
        next_ordered_section_ <= kFunctionSectionCode;
    const bool after_code_section = next_ordered_section_ > kCodeSectionCode;
    if (before_function_section || after_code_section ||
        has_seen_unordered_section(kCompilationHintsSectionCode)) {
      return;
    }
    set_seen_unordered_section(kCompilationHintsSectionCode);
    // TODO(frgossen) Propagate errors to outer decoder in experimental phase.
    // We should use an inner decoder later and propagate its errors as
    // warnings.
    Decoder& decoder = *this;
    // Decoder decoder(start_, pc_, end_, buffer_offset_);
    // Ensure exactly one compilation hint per function.
    uint32_t hint_count = decoder.consume_u32v("compilation hint count");
    if (hint_count != module_->num_declared_functions) {
      decoder.errorf(decoder.pc(), "Expected %u compilation hints (%u found)",
                     module_->num_declared_functions, hint_count);
    }
    // Decode sequence of compilation hints.
    if (decoder.ok()) {
      module_->compilation_hints.reserve(hint_count);
    }
    for (uint32_t i = 0; decoder.ok() && i < hint_count; i++) {
      TRACE("DecodeCompilationHints[%d] module+%d\n", i,
            static_cast<int>(pc_ - start_));
      // Compilation hints are encoded in one byte each.
      // +-------+----------+---------------+----------+
      // | 2 bit | 2 bit | 2 bit | 2 bit |
      // | ... | Top tier | Baseline tier | Strategy |
      // +-------+----------+---------------+----------+
      uint8_t hint_byte = decoder.consume_u8("compilation hint");
      if (!decoder.ok()) break;
      // Validate the hint_byte.
      // For the compilation strategy, all 2-bit values are valid. For the tier,
      // only 0x0, 0x1, and 0x2 are allowed.
      static_assert(
          static_cast<int>(WasmCompilationHintTier::kDefault) == 0 &&
              static_cast<int>(WasmCompilationHintTier::kBaseline) == 1 &&
              static_cast<int>(WasmCompilationHintTier::kOptimized) == 2,
          "The check below assumes that 0x03 is the only invalid 2-bit number "
          "for a compilation tier");
      if (((hint_byte >> 2) & 0x03) == 0x03 ||
          ((hint_byte >> 4) & 0x03) == 0x03) {
        decoder.errorf(decoder.pc(),
                       "Invalid compilation hint %#04x (invalid tier 0x03)",
                       hint_byte);
        break;
      }
      // Decode compilation hint.
      WasmCompilationHint hint;
      hint.strategy =
          static_cast<WasmCompilationHintStrategy>(hint_byte & 0x03);
      hint.baseline_tier =
          static_cast<WasmCompilationHintTier>((hint_byte >> 2) & 0x03);
      hint.top_tier =
          static_cast<WasmCompilationHintTier>((hint_byte >> 4) & 0x03);
      // Ensure that the top tier never downgrades a compilation result. If
      // baseline and top tier are the same compilation will be invoked only
      // once.
      if (hint.top_tier < hint.baseline_tier &&
          hint.top_tier != WasmCompilationHintTier::kDefault) {
        decoder.errorf(decoder.pc(),
                       "Invalid compilation hint %#04x (forbidden downgrade)",
                       hint_byte);
      }
      // Happily accept compilation hint.
      if (decoder.ok()) {
        module_->compilation_hints.push_back(std::move(hint));
      }
    }
    // If section was invalid reset compilation hints.
    if (decoder.failed()) {
      module_->compilation_hints.clear();
    }
    // @TODO(frgossen) Skip the whole compilation hints section in the outer
    // decoder if inner decoder was used.
    // consume_bytes(static_cast<uint32_t>(end_ - start_), nullptr);
  }
References v8::internal::wasm::WasmCompilationHint::baseline_tier, v8::internal::wasm::Decoder::consume_u32v(), v8::internal::wasm::Decoder::consume_u8(), v8::internal::wasm::Decoder::errorf(), v8::internal::wasm::Decoder::failed(), has_seen_unordered_section(), v8::internal::wasm::kBaseline, v8::internal::wasm::kCodeSectionCode, v8::internal::wasm::kCompilationHintsSectionCode, v8::internal::wasm::kDefault, v8::internal::wasm::kFunctionSectionCode, v8::internal::wasm::kOptimized, module_, next_ordered_section_, v8::internal::wasm::Decoder::ok(), v8::internal::wasm::Decoder::pc(), v8::internal::wasm::Decoder::pc_, set_seen_unordered_section(), v8::internal::wasm::Decoder::start_, v8::internal::wasm::WasmCompilationHint::strategy, v8::internal::wasm::WasmCompilationHint::top_tier, and v8::internal::TRACE().
Referenced by DecodeSection().
DecodeDataCountSection()
void v8::internal::wasm::ModuleDecoderImpl::DecodeDataCountSection () [inline]
Definition at line 1871 of file module-decoder-impl.h.
                                {
    module_->num_declared_data_segments =
        consume_count("data segments count", kV8MaxWasmDataSegments);
    if (tracer_) tracer_->NextLineIfNonEmpty();
  }
References consume_count(), v8::internal::wasm::kV8MaxWasmDataSegments, module_, v8::internal::wasm::ITracer::NextLineIfNonEmpty(), and tracer_.
Referenced by DecodeSection().
DecodeDataSection()
void v8::internal::wasm::ModuleDecoderImpl::DecodeDataSection () [inline]
Definition at line 1512 of file module-decoder-impl.h.
                           {
    uint32_t data_segments_count =
        consume_count("data segments count", kV8MaxWasmDataSegments);
    if (!CheckDataSegmentsCount(data_segments_count)) return;
    module_->data_segments.reserve(data_segments_count);
    for (uint32_t i = 0; i < data_segments_count; ++i) {
      TRACE("DecodeDataSegment[%d] module+%d\n", i,
            static_cast<int>(pc_ - start_));
      if (tracer_) tracer_->DataOffset(pc_offset());
      DataSegmentHeader header = consume_data_segment_header();
      uint32_t source_length = consume_u32v("source size", tracer_);
      if (tracer_) {
        tracer_->Description(source_length);
        tracer_->NextLine();
      }
      uint32_t source_offset = pc_offset();
      if (tracer_) {
        tracer_->Bytes(pc_, source_length);
        tracer_->Description("segment data");
        tracer_->NextLine();
      }
      consume_bytes(source_length, "segment data");
      if (failed()) break;
      module_->data_segments.emplace_back(
          header.is_active, header.is_shared, header.memory_index,
          header.dest_addr, WireBytesRef{source_offset, source_length});
    }
  }
References v8::internal::wasm::ITracer::Bytes(), CheckDataSegmentsCount(), v8::internal::wasm::Decoder::consume_bytes(), consume_count(), consume_data_segment_header(), v8::internal::wasm::Decoder::consume_u32v(), v8::internal::wasm::ITracer::DataOffset(), v8::internal::wasm::ITracer::Description(), v8::internal::wasm::ModuleDecoderImpl::DataSegmentHeader::dest_addr, v8::internal::wasm::Decoder::failed(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::ModuleDecoderImpl::DataSegmentHeader::is_active, v8::internal::wasm::ModuleDecoderImpl::DataSegmentHeader::is_shared, v8::internal::wasm::kV8MaxWasmDataSegments, v8::internal::wasm::ModuleDecoderImpl::DataSegmentHeader::memory_index, module_, v8::internal::wasm::ITracer::NextLine(), v8::internal::wasm::Decoder::pc_, v8::internal::wasm::Decoder::pc_offset(), v8::internal::wasm::Decoder::start_, v8::internal::TRACE(), and tracer_.
Referenced by DecodeSection().
DecodeDescriptorsSection()
void v8::internal::wasm::ModuleDecoderImpl::DecodeDescriptorsSection () [inline]
Definition at line 1586 of file module-decoder-impl.h.
                                  {
    if (enabled_features_.has_custom_descriptors() &&
        !has_seen_unordered_section(kDescriptorsSectionCode)) {
      set_seen_unordered_section(kDescriptorsSectionCode);
      module_->descriptors_section = {buffer_offset_,
                                      static_cast<uint32_t>(end_ - start_)};
    }
    consume_bytes(static_cast<uint32_t>(end_ - start_), nullptr);
  }
References v8::internal::wasm::Decoder::buffer_offset_, v8::internal::wasm::Decoder::consume_bytes(), enabled_features_, v8::internal::wasm::Decoder::end_, has_seen_unordered_section(), v8::internal::wasm::kDescriptorsSectionCode, module_, set_seen_unordered_section(), and v8::internal::wasm::Decoder::start_.
Referenced by DecodeSection().
DecodeElementSection()
void v8::internal::wasm::ModuleDecoderImpl::DecodeElementSection () [inline]
Definition at line 1382 of file module-decoder-impl.h.
                              {
    uint32_t segment_count =
        consume_count("segment count", wasm::max_table_size());
    for (uint32_t i = 0; i < segment_count; ++i) {
      if (tracer_) tracer_->ElementOffset(pc_offset());
      WasmElemSegment segment = consume_element_segment_header();
      if (tracer_) tracer_->NextLineIfNonEmpty();
      if (failed()) return;
      DCHECK_NE(segment.type, kWasmBottom);
      for (uint32_t j = 0; j < segment.element_count; j++) {
        // Just run validation on elements; do not store them anywhere. We will
        // decode them again from wire bytes as needed.
        consume_element_segment_entry(module_.get(), segment);
        if (failed()) return;
      }
      module_->elem_segments.push_back(std::move(segment));
    }
  }
References consume_count(), consume_element_segment_entry(), consume_element_segment_header(), DCHECK_NE, v8::internal::wasm::WasmElemSegment::element_count, v8::internal::wasm::ITracer::ElementOffset(), v8::internal::wasm::Decoder::failed(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::kWasmBottom, v8::internal::wasm::max_table_size(), module_, v8::internal::wasm::ITracer::NextLineIfNonEmpty(), v8::internal::wasm::Decoder::pc_offset(), tracer_, and v8::internal::wasm::WasmElemSegment::type.
Referenced by DecodeSection().
DecodeExportSection()
void v8::internal::wasm::ModuleDecoderImpl::DecodeExportSection () [inline]
Definition at line 1256 of file module-decoder-impl.h.
                             {
    uint32_t export_table_count =
        consume_count("exports count", kV8MaxWasmExports);
    module_->export_table.reserve(export_table_count);
    for (uint32_t i = 0; ok() && i < export_table_count; ++i) {
      TRACE("DecodeExportTable[%d] module+%d\n", i,
            static_cast<int>(pc_ - start_));
      if (tracer_) {
        tracer_->Description("export #");
        tracer_->Description(i);
        tracer_->NextLine();
      }
      WireBytesRef name = consume_utf8_string(this, "field name", tracer_);
      const uint8_t* kind_pos = pc();
      ImportExportKindCode kind =
          static_cast<ImportExportKindCode>(consume_u8("kind", tracer_));
      module_->export_table.push_back(WasmExport{.name = name, .kind = kind});
      WasmExport* exp = &module_->export_table.back();
      if (tracer_) {
        tracer_->Description(": ");
        tracer_->Description(ExternalKindName(exp->kind));
        tracer_->Description(" ");
      }
      switch (kind) {
        case kExternalFunction: {
          WasmFunction* func = nullptr;
          exp->index = consume_func_index(module_.get(), &func);
          if (failed()) break;
          DCHECK_NOT_NULL(func);
          module_->num_exported_functions++;
          func->exported = true;
          // Exported functions are considered "declared".
          func->declared = true;
          break;
        }
        case kExternalTable: {
          WasmTable* table = nullptr;
          exp->index = consume_table_index(module_.get(), &table);
          if (table) table->exported = true;
          break;
        }
        case kExternalMemory: {
          const uint8_t* index_pos = pc();
          exp->index = consume_u32v("memory index", tracer_);
          size_t num_memories = module_->memories.size();
          if (exp->index >= module_->memories.size()) {
            errorf(index_pos,
                   "invalid exported memory index %u (having %zu memor%s)",
                   exp->index, num_memories, num_memories == 1 ? "y" : "ies");
            break;
          }
          module_->memories[exp->index].exported = true;
          break;
        }
        case kExternalGlobal: {
          WasmGlobal* global = nullptr;
          exp->index = consume_global_index(module_.get(), &global);
          if (global) {
            global->exported = true;
          }
          break;
        }
        case kExternalTag: {
          WasmTag* tag = nullptr;
          exp->index = consume_tag_index(module_.get(), &tag);
          break;
        }
        default:
          errorf(kind_pos, "invalid export kind 0x%02x", exp->kind);
          break;
      }
      if (tracer_) tracer_->NextLine();
    }
    // Check for duplicate exports (except for asm.js).
    if (ok() && module_->origin == kWasmOrigin &&
        module_->export_table.size() > 1) {
      std::vector<WasmExport> sorted_exports(module_->export_table);
      auto cmp_less = [this](const WasmExport& a, const WasmExport& b) {
        // Return true if a < b.
        if (a.name.length() != b.name.length()) {
          return a.name.length() < b.name.length();
        }
        const uint8_t* left =
            start() + GetBufferRelativeOffset(a.name.offset());
        const uint8_t* right =
            start() + GetBufferRelativeOffset(b.name.offset());
        return memcmp(left, right, a.name.length()) < 0;
      };
      std::stable_sort(sorted_exports.begin(), sorted_exports.end(), cmp_less);
      auto it = sorted_exports.begin();
      WasmExport* last = &*it++;
      for (auto end = sorted_exports.end(); it != end; last = &*it++) {
        DCHECK(!cmp_less(*it, *last)); // Vector must be sorted.
        if (!cmp_less(*last, *it)) {
          const uint8_t* pc =
              start() + GetBufferRelativeOffset(it->name.offset());
          TruncatedUserString<> name(pc, it->name.length());
          errorf(pc, "Duplicate export name '%.*s' for %s %d and %s %d",
                 name.length(), name.start(), ExternalKindName(last->kind),
                 last->index, ExternalKindName(it->kind), it->index);
          break;
        }
      }
    }
  }
References consume_count(), consume_func_index(), consume_global_index(), consume_table_index(), consume_tag_index(), v8::internal::wasm::Decoder::consume_u32v(), v8::internal::wasm::Decoder::consume_u8(), v8::internal::wasm::consume_utf8_string(), v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::wasm::WasmFunction::declared, v8::internal::wasm::ITracer::Description(), v8::internal::wasm::Decoder::end(), v8::internal::wasm::Decoder::errorf(), v8::base::ieee754::exp(), v8::internal::wasm::WasmFunction::exported, v8::internal::wasm::WasmGlobal::exported, v8::internal::wasm::WasmTable::exported, v8::internal::wasm::ExternalKindName(), v8::internal::wasm::Decoder::failed(), v8::internal::wasm::Decoder::GetBufferRelativeOffset(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::WasmExport::index, v8::internal::wasm::kExternalFunction, v8::internal::wasm::kExternalGlobal, v8::internal::wasm::kExternalMemory, v8::internal::wasm::kExternalTable, v8::internal::wasm::kExternalTag, v8::internal::wasm::WasmExport::kind, v8::internal::wasm::kV8MaxWasmExports, v8::internal::wasm::kWasmOrigin, v8::internal::wasm::WireBytesRef::length(), module_, v8::internal::wasm::name(), v8::internal::wasm::WasmExport::name, v8::internal::wasm::ITracer::NextLine(), v8::internal::wasm::WireBytesRef::offset(), v8::internal::wasm::Decoder::ok(), v8::internal::wasm::Decoder::pc(), v8::internal::wasm::Decoder::pc_, v8::internal::wasm::Decoder::start(), v8::internal::wasm::Decoder::start_, v8::internal::TRACE(), and tracer_.
Referenced by DecodeSection().
DecodeExternalDebugInfoSection()
void v8::internal::wasm::ModuleDecoderImpl::DecodeExternalDebugInfoSection () [inline]
Definition at line 1610 of file module-decoder-impl.h.
                                        {
    Decoder inner(start_, pc_, end_, buffer_offset_);
    WireBytesRef url =
        wasm::consume_utf8_string(&inner, "external symbol file", tracer_);
    if (inner.ok()) {
      module_->debug_symbols[WasmDebugSymbols::Type::ExternalDWARF] = {
          WasmDebugSymbols::Type::ExternalDWARF, url};
      set_seen_unordered_section(kExternalDebugInfoSectionCode);
    }
    consume_bytes(static_cast<uint32_t>(end_ - start_), nullptr);
  }
References v8::internal::wasm::Decoder::buffer_offset_, v8::internal::wasm::Decoder::consume_bytes(), v8::internal::wasm::consume_utf8_string(), v8::internal::wasm::Decoder::end_, v8::internal::wasm::kExternalDebugInfoSectionCode, module_, v8::internal::wasm::Decoder::ok(), v8::internal::wasm::Decoder::pc_, set_seen_unordered_section(), v8::internal::wasm::Decoder::start_, and tracer_.
Referenced by DecodeSection().
DecodeFunctionBody()
void v8::internal::wasm::ModuleDecoderImpl::DecodeFunctionBody (uint32_t func_index, uint32_t length, uint32_t offset) [inline]
Definition at line 1482 of file module-decoder-impl.h.
                                           {
    WasmFunction* function = &module_->functions[func_index];
    function->code = {offset, length};
    constexpr uint32_t kSmallFunctionThreshold = 50;
    if (length < kSmallFunctionThreshold) {
      ++module_->num_small_functions;
    }
    if (tracer_) {
      tracer_->FunctionBody(function, pc_ - (pc_offset() - offset));
    }
  }
References v8::internal::wasm::ITracer::FunctionBody(), v8::internal::length, module_, v8::internal::wasm::Decoder::pc_, v8::internal::wasm::Decoder::pc_offset(), and tracer_.
Referenced by DecodeCodeSection().
DecodeFunctionSection()
void v8::internal::wasm::ModuleDecoderImpl::DecodeFunctionSection () [inline]
Definition at line 1083 of file module-decoder-impl.h.
                               {
    uint32_t functions_count =
        consume_count("functions count", v8_flags.max_wasm_functions);
    DCHECK_EQ(module_->functions.size(), module_->num_imported_functions);
    uint32_t total_function_count =
        module_->num_imported_functions + functions_count;
    module_->functions.resize(total_function_count);
    module_->num_declared_functions = functions_count;
    // Also initialize the {validated_functions} bitset here, now that we know
    // the number of declared functions.
    DCHECK_NULL(module_->validated_functions);
    module_->validated_functions =
        std::make_unique<std::atomic<uint8_t>[]>((functions_count + 7) / 8);
    if (is_asmjs_module(module_.get())) {
      // Mark all asm.js functions as valid by design (it's faster to do this
      // here than to check this in {WasmModule::function_was_validated}).
      std::fill_n(module_->validated_functions.get(), (functions_count + 7) / 8,
                  0xff);
    }
    for (uint32_t func_index = module_->num_imported_functions;
         func_index < total_function_count; ++func_index) {
      WasmFunction* function = &module_->functions[func_index];
      function->func_index = func_index;
      if (tracer_) tracer_->FunctionName(func_index);
      function->sig_index = consume_sig_index(module_.get(), &function->sig);
      if (!ok()) return;
    }
  }
References consume_count(), consume_sig_index(), DCHECK_EQ, DCHECK_NULL, v8::internal::wasm::ITracer::FunctionName(), v8::internal::wasm::is_asmjs_module(), module_, v8::internal::wasm::Decoder::ok(), tracer_, and v8::internal::v8_flags.
Referenced by DecodeSection().
DecodeFunctionSignatureForTesting()
const FunctionSig* v8::internal::wasm::ModuleDecoderImpl::DecodeFunctionSignatureForTesting (Zone * zone, const uint8_t * start) [inline]
Definition at line 2026 of file module-decoder-impl.h.
                                                                             {
    pc_ = start;
    if (!expect_u8("type form", kWasmFunctionTypeCode)) return nullptr;
    const FunctionSig* result = consume_sig(zone);
    return ok() ? result : nullptr;
  }
References consume_sig(), expect_u8(), v8::internal::wasm::kWasmFunctionTypeCode, v8::internal::wasm::Decoder::ok(), v8::internal::wasm::Decoder::pc_, v8::base::internal::result, and v8::internal::wasm::Decoder::start().
DecodeGlobalSection()
void v8::internal::wasm::ModuleDecoderImpl::DecodeGlobalSection () [inline]
Definition at line 1221 of file module-decoder-impl.h.
                             {
    uint32_t globals_count = consume_count("globals count", kV8MaxWasmGlobals);
    uint32_t imported_globals = static_cast<uint32_t>(module_->globals.size());
    // It is important to not resize the globals vector from the beginning,
    // because we use its current size when decoding the initializer.
    module_->globals.reserve(imported_globals + globals_count);
    for (uint32_t i = 0; ok() && i < globals_count; ++i) {
      TRACE("DecodeGlobal[%d] module+%d\n", i, static_cast<int>(pc_ - start_));
      if (tracer_) tracer_->GlobalOffset(pc_offset());
      const uint8_t* pos = pc_;
      ValueType type = consume_value_type(module_.get());
      auto [mutability, shared] = consume_global_flags();
      if (failed()) return;
      if (shared && !type.is_shared()) {
        CHECK(enabled_features_.has_shared());
        errorf(pos, "Shared global %i must have shared type, actual type %s",
               i + imported_globals, type.name().c_str());
        return;
      }
      // Validation that {type} and {shared} are compatible will happen in
      // {consume_init_expr}.
      bool ends_with_struct_new = false;
      ConstantExpression init =
          consume_init_expr(module_.get(), type, shared, &ends_with_struct_new);
      module_->globals.push_back(
          WasmGlobal{.type = type,
                     .mutability = mutability,
                     .init = init,
                     .index = 0, // set later in CalculateGlobalOffsets
                     .shared = shared,
                     .initializer_ends_with_struct_new = ends_with_struct_new});
      if (shared) module_->has_shared_part = true;
    }
  }
References CHECK, consume_count(), consume_global_flags(), consume_init_expr(), consume_value_type(), enabled_features_, v8::internal::wasm::Decoder::errorf(), v8::internal::wasm::Decoder::failed(), v8::internal::wasm::ITracer::GlobalOffset(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::ConstantExpression::index(), v8::internal::wasm::kV8MaxWasmGlobals, module_, v8::internal::wasm::Decoder::ok(), v8::internal::wasm::Decoder::pc_, v8::internal::wasm::Decoder::pc_offset(), v8::internal::wasm::Decoder::start_, v8::internal::TRACE(), tracer_, v8::internal::tracing::type, and v8::internal::wasm::WasmGlobal::type.
Referenced by DecodeSection().
DecodeImportSection()
void v8::internal::wasm::ModuleDecoderImpl::DecodeImportSection () [inline]
Definition at line 932 of file module-decoder-impl.h.
                             {
    uint32_t import_table_count =
        consume_count("imports count", kV8MaxWasmImports);
    module_->import_table.reserve(import_table_count);
    for (uint32_t i = 0; ok() && i < import_table_count; ++i) {
      TRACE("DecodeImportTable[%d] module+%d\n", i,
            static_cast<int>(pc_ - start_));
      if (tracer_) tracer_->ImportOffset(pc_offset());
      const uint8_t* pos = pc_;
      WireBytesRef module_name =
          consume_utf8_string(this, "module name", tracer_);
      WireBytesRef field_name =
          consume_utf8_string(this, "field name", tracer_);
      ImportExportKindCode kind =
          static_cast<ImportExportKindCode>(consume_u8("kind", tracer_));
      if (tracer_) {
        tracer_->Description(": ");
        tracer_->Description(ExternalKindName(kind));
      }
      module_->import_table.push_back(WasmImport{
          .module_name = module_name, .field_name = field_name, .kind = kind});
      WasmImport* import = &module_->import_table.back();
      switch (kind) {
        case kExternalFunction: {
          // ===== Imported function ===========================================
          import->index = static_cast<uint32_t>(module_->functions.size());
          module_->num_imported_functions++;
          module_->functions.push_back(WasmFunction{
              .func_index = import->index,
              .imported = true,
          });
          WasmFunction* function = &module_->functions.back();
          function->sig_index =
              consume_sig_index(module_.get(), &function->sig);
          break;
        }
        case kExternalTable: {
          // ===== Imported table ==============================================
          import->index = static_cast<uint32_t>(module_->tables.size());
          const uint8_t* type_position = pc();
          ValueType type = consume_value_type(module_.get());
          if (!type.is_object_reference()) {
            errorf(type_position, "Invalid table type %s", type.name().c_str());
            break;
          }
          module_->num_imported_tables++;
          module_->tables.push_back(WasmTable{
              .type = type,
              .imported = true,
          });
          WasmTable* table = &module_->tables.back();
          consume_table_flags(table);
          DCHECK_IMPLIES(table->shared,
                         enabled_features_.has_shared() || !ok());
          if (table->shared && enabled_features_.has_shared()) {
            module_->has_shared_part = true;
            if (!type.is_shared()) {
              errorf(type_position,
                     "Shared table %i must have shared element type, actual "
                     "type %s",
                     i, type.name().c_str());
              break;
            }
          }
          // Note that we should not throw an error if the declared maximum size
          // is oob. We will instead fail when growing at runtime.
          uint64_t kNoMaximum = kMaxUInt64;
          consume_resizable_limits(
              "table", "elements", wasm::max_table_size(), &table->initial_size,
              table->has_maximum_size, kNoMaximum, &table->maximum_size,
              table->is_table64() ? k64BitLimits : k32BitLimits);
          break;
        }
        case kExternalMemory: {
          // ===== Imported memory =============================================
          static_assert(kV8MaxWasmMemories <= kMaxUInt32);
          if (module_->memories.size() >= kV8MaxWasmMemories - 1) {
            errorf("At most %u imported memories are supported",
                   kV8MaxWasmMemories);
            break;
          }
          uint32_t mem_index = static_cast<uint32_t>(module_->memories.size());
          import->index = mem_index;
          module_->memories.emplace_back();
          WasmMemory* external_memory = &module_->memories.back();
          external_memory->imported = true;
          external_memory->index = mem_index;
          consume_memory_flags(external_memory);
          uint32_t max_pages = external_memory->is_memory64()
                                   ? kSpecMaxMemory64Pages
                                   : kSpecMaxMemory32Pages;
          consume_resizable_limits(
              "memory", "pages", max_pages, &external_memory->initial_pages,
              external_memory->has_maximum_pages, max_pages,
              &external_memory->maximum_pages,
              external_memory->is_memory64() ? k64BitLimits : k32BitLimits);
          break;
        }
        case kExternalGlobal: {
          // ===== Imported global =============================================
          import->index = static_cast<uint32_t>(module_->globals.size());
          ValueType type = consume_value_type(module_.get());
          auto [mutability, shared] = consume_global_flags();
          if (V8_UNLIKELY(failed())) break;
          if (V8_UNLIKELY(shared && !type.is_shared())) {
            error("shared imported global must have shared type");
            break;
          }
          module_->globals.push_back(
              WasmGlobal{.type = type,
                         .mutability = mutability,
                         .index = 0, // set later in CalculateGlobalOffsets
                         .shared = shared,
                         .imported = true});
          module_->num_imported_globals++;
          DCHECK_EQ(module_->globals.size(), module_->num_imported_globals);
          if (shared) module_->has_shared_part = true;
          if (mutability) module_->num_imported_mutable_globals++;
          if (tracer_) tracer_->NextLine();
          break;
        }
        case kExternalTag: {
          // ===== Imported tag ================================================
          import->index = static_cast<uint32_t>(module_->tags.size());
          module_->num_imported_tags++;
          const WasmTagSig* tag_sig = nullptr;
          consume_exception_attribute(); // Attribute ignored for now.
          ModuleTypeIndex sig_index =
              consume_tag_sig_index(module_.get(), &tag_sig);
          module_->tags.emplace_back(tag_sig, sig_index);
          break;
        }
        default:
          errorf(pos, "unknown import kind 0x%02x", kind);
          break;
      }
    }
    if (module_->memories.size() > 1) {
      detected_features_->add_multi_memory();
      if (v8_flags.wasm_jitless) {
        error("Multiple memories not supported in Wasm jitless mode");
      }
    }
    UpdateComputedMemoryInformation();
    module_->type_feedback.well_known_imports.Initialize(
        module_->num_imported_functions);
    if (tracer_) tracer_->ImportsDone(module_.get());
  }
References consume_count(), consume_exception_attribute(), consume_global_flags(), consume_memory_flags(), consume_resizable_limits(), consume_sig_index(), consume_table_flags(), consume_tag_sig_index(), v8::internal::wasm::Decoder::consume_u8(), v8::internal::wasm::consume_utf8_string(), consume_value_type(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::wasm::ITracer::Description(), detected_features_, enabled_features_, v8::internal::wasm::Decoder::error(), v8::internal::wasm::Decoder::errorf(), v8::internal::wasm::ExternalKindName(), v8::internal::wasm::Decoder::failed(), v8::internal::wasm::WasmFunction::func_index, v8::internal::wasm::WasmMemory::has_maximum_pages, v8::internal::wasm::WasmTable::has_maximum_size, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::WasmMemory::imported, v8::internal::wasm::ITracer::ImportOffset(), v8::internal::wasm::ITracer::ImportsDone(), v8::internal::wasm::WasmMemory::index, v8::internal::wasm::WasmMemory::initial_pages, v8::internal::wasm::WasmTable::initial_size, v8::internal::wasm::WasmMemory::is_memory64(), v8::internal::wasm::WasmTable::is_table64(), k32BitLimits, k64BitLimits, v8::internal::wasm::kExternalFunction, v8::internal::wasm::kExternalGlobal, v8::internal::wasm::kExternalMemory, v8::internal::wasm::kExternalTable, v8::internal::wasm::kExternalTag, v8::internal::kMaxUInt32, v8::internal::kMaxUInt64, v8::internal::wasm::kNoMaximum, v8::internal::wasm::kSpecMaxMemory32Pages, v8::internal::wasm::kSpecMaxMemory64Pages, v8::internal::wasm::kV8MaxWasmImports, v8::internal::wasm::kV8MaxWasmMemories, v8::internal::wasm::max_table_size(), v8::internal::wasm::WasmMemory::maximum_pages, v8::internal::wasm::WasmTable::maximum_size, module_, v8::internal::wasm::WasmImport::module_name, v8::internal::wasm::ITracer::NextLine(), v8::internal::wasm::Decoder::ok(), v8::internal::wasm::Decoder::pc(), v8::internal::wasm::Decoder::pc_, v8::internal::wasm::Decoder::pc_offset(), v8::internal::wasm::WasmTable::shared, v8::internal::wasm::Decoder::start_, v8::internal::TRACE(), tracer_, v8::internal::tracing::type, v8::internal::wasm::WasmGlobal::type, v8::internal::wasm::WasmTable::type, UpdateComputedMemoryInformation(), v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by DecodeSection().
DecodeInitExprForTesting()
ConstantExpression v8::internal::wasm::ModuleDecoderImpl::DecodeInitExprForTesting (ValueType expected) [inline]
Definition at line 2034 of file module-decoder-impl.h.
                                                                  {
    constexpr bool kIsShared = false; // TODO(14616): Extend this.
    return consume_init_expr(module_.get(), expected, kIsShared);
  }
References consume_init_expr(), and module_.
DecodeInstTraceSection()
void v8::internal::wasm::ModuleDecoderImpl::DecodeInstTraceSection () [inline]
Definition at line 1633 of file module-decoder-impl.h.
                                {
    TRACE("DecodeInstTrace module+%d\n", static_cast<int>(pc_ - start_));
    if (!has_seen_unordered_section(kInstTraceSectionCode)) {
      set_seen_unordered_section(kInstTraceSectionCode);
      // Use an inner decoder so that errors don't fail the outer decoder.
      Decoder inner(start_, pc_, end_, buffer_offset_);
      std::vector<std::tuple<uint32_t, uint32_t, uint32_t>> inst_traces;
      uint32_t func_count = inner.consume_u32v("number of functions");
      // Keep track of the previous function index to validate the ordering.
      int64_t last_func_idx = -1;
      for (uint32_t i = 0; i < func_count; i++) {
        uint32_t func_idx = inner.consume_u32v("function index");
        if (int64_t{func_idx} <= last_func_idx) {
          inner.errorf("Invalid function index: %d", func_idx);
          break;
        }
        last_func_idx = func_idx;
        uint32_t num_traces = inner.consume_u32v("number of trace marks");
        TRACE("DecodeInstTrace[%d] module+%d\n", func_idx,
              static_cast<int>(inner.pc() - inner.start()));
        // Keep track of the previous offset to validate the ordering.
        int64_t last_func_off = -1;
        for (uint32_t j = 0; j < num_traces; ++j) {
          uint32_t func_off = inner.consume_u32v("function offset");
          uint32_t mark_size = inner.consume_u32v("mark size");
          uint32_t trace_mark_id = 0;
          // Build the mark id from the individual bytes.
          for (uint32_t k = 0; k < mark_size; k++) {
            trace_mark_id |= inner.consume_u8("trace mark id") << k * 8;
          }
          if (int64_t{func_off} <= last_func_off) {
            inner.errorf("Invalid branch offset: %d", func_off);
            break;
          }
          last_func_off = func_off;
          TRACE("DecodeInstTrace[%d][%d] module+%d\n", func_idx, func_off,
                static_cast<int>(inner.pc() - inner.start()));
          // Store the function index, function offset, and mark id into a
          // temporary 3-tuple. This will later be translated to a module
          // offset and mark id.
          std::tuple<uint32_t, uint32_t, uint32_t> mark_tuple = {
              func_idx, func_off, trace_mark_id};
          inst_traces.push_back(mark_tuple);
        }
      }
      // Extra unexpected bytes are an error.
      if (inner.more()) {
        inner.errorf("Unexpected extra bytes: %d\n",
                     static_cast<int>(inner.pc() - inner.start()));
      }
      // If everything went well, accept the traces for the module.
      if (inner.ok()) {
        this->inst_traces_ = std::move(inst_traces);
      }
    }
    // Skip the whole instruction trace section in the outer decoder.
    consume_bytes(static_cast<uint32_t>(end_ - start_), nullptr);
  }
References v8::internal::wasm::Decoder::buffer_offset_, v8::internal::wasm::Decoder::consume_bytes(), v8::internal::wasm::Decoder::consume_u32v(), v8::internal::wasm::Decoder::consume_u8(), v8::internal::wasm::Decoder::end_, v8::internal::wasm::Decoder::errorf(), has_seen_unordered_section(), inst_traces_, v8::internal::wasm::kInstTraceSectionCode, v8::internal::wasm::Decoder::more(), v8::internal::wasm::Decoder::ok(), v8::internal::wasm::Decoder::pc(), v8::internal::wasm::Decoder::pc_, set_seen_unordered_section(), v8::internal::wasm::Decoder::start(), v8::internal::wasm::Decoder::start_, and v8::internal::TRACE().
Referenced by DecodeSection().
DecodeMemorySection()
void v8::internal::wasm::ModuleDecoderImpl::DecodeMemorySection () [inline]
Definition at line 1177 of file module-decoder-impl.h.
                             {
    const uint8_t* mem_count_pc = pc();
    static_assert(kV8MaxWasmMemories <= kMaxUInt32);
    // Use {kV8MaxWasmMemories} here, but only allow for >1 memory if
    // multi-memory is enabled (checked below). This allows for better error
    // messages.
    uint32_t memory_count = consume_count("memory count", kV8MaxWasmMemories);
    size_t imported_memories = module_->memories.size();
    DCHECK_GE(kV8MaxWasmMemories, imported_memories);
    if (memory_count > kV8MaxWasmMemories - imported_memories) {
      errorf(mem_count_pc,
             "Exceeding maximum number of memories (%u; declared %u, "
             "imported %zu)",
             kV8MaxWasmMemories, memory_count, imported_memories);
    }
    module_->memories.resize(imported_memories + memory_count);
    for (uint32_t i = 0; ok() && i < memory_count; i++) {
      WasmMemory* memory = module_->memories.data() + imported_memories + i;
      memory->index = static_cast<uint32_t>(imported_memories + i);
      if (tracer_) tracer_->MemoryOffset(pc_offset());
      consume_memory_flags(memory);
      uint32_t max_pages =
          memory->is_memory64() ? kSpecMaxMemory64Pages : kSpecMaxMemory32Pages;
      consume_resizable_limits(
          "memory", "pages", max_pages, &memory->initial_pages,
          memory->has_maximum_pages, max_pages, &memory->maximum_pages,
          memory->is_memory64() ? k64BitLimits : k32BitLimits);
    }
    if (module_->memories.size() > 1) {
      detected_features_->add_multi_memory();
      if (v8_flags.wasm_jitless) {
        error("Multiple memories not supported in Wasm jitless mode");
      }
    }
    UpdateComputedMemoryInformation();
  }
References consume_count(), consume_memory_flags(), consume_resizable_limits(), DCHECK_GE, detected_features_, v8::internal::wasm::Decoder::error(), v8::internal::wasm::Decoder::errorf(), v8::internal::wasm::WasmMemory::has_maximum_pages, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::WasmMemory::index, v8::internal::wasm::WasmMemory::initial_pages, v8::internal::wasm::WasmMemory::is_memory64(), k32BitLimits, k64BitLimits, v8::internal::kMaxUInt32, v8::internal::wasm::kSpecMaxMemory32Pages, v8::internal::wasm::kSpecMaxMemory64Pages, v8::internal::wasm::kV8MaxWasmMemories, v8::internal::wasm::WasmMemory::maximum_pages, v8::internal::wasm::ITracer::MemoryOffset(), module_, v8::internal::wasm::Decoder::ok(), v8::internal::wasm::Decoder::pc(), v8::internal::wasm::Decoder::pc_offset(), tracer_, UpdateComputedMemoryInformation(), and v8::internal::v8_flags.
Referenced by DecodeSection().
DecodeModule()
ModuleResult v8::internal::wasm::ModuleDecoderImpl::DecodeModule (bool validate_functions) [inline]
Definition at line 1948 of file module-decoder-impl.h.
                                                     {
    // Keep a reference to the wire bytes, in case this decoder gets reset on
    // error.
    base::Vector<const uint8_t> wire_bytes(start_, end_ - start_);
    size_t max_size = max_module_size();
    if (wire_bytes.size() > max_size) {
      return ModuleResult{WasmError{0, "size > maximum module size (%zu): %zu",
                                    max_size, wire_bytes.size()}};
    }
    DecodeModuleHeader(wire_bytes);
    if (failed()) return toResult(nullptr);
    static constexpr uint32_t kWasmHeaderSize = 8;
    Decoder section_iterator_decoder(start_ + kWasmHeaderSize, end_,
                                     kWasmHeaderSize);
    WasmSectionIterator section_iter(&section_iterator_decoder, tracer_);
    while (ok()) {
      if (section_iter.section_code() != SectionCode::kUnknownSectionCode) {
        uint32_t offset = static_cast<uint32_t>(section_iter.payload().begin() -
                                                wire_bytes.begin());
        DecodeSection(section_iter.section_code(), section_iter.payload(),
                      offset);
        if (!ok()) break;
      }
      if (!section_iter.more()) break;
      section_iter.advance(true);
    }
    // Check for module structure errors before validating function bodies, to
    // produce consistent error message independent of whether validation
    // happens here or later.
    if (section_iterator_decoder.failed()) {
      return section_iterator_decoder.toResult(nullptr);
    }
    ModuleResult result = FinishDecoding();
    if (!result.failed() && validate_functions) {
      std::function<bool(int)> kNoFilter;
      if (WasmError validation_error =
              ValidateFunctions(module_.get(), enabled_features_, wire_bytes,
                                kNoFilter, detected_features_)) {
        result = ModuleResult{validation_error};
      }
    }
    if (v8_flags.dump_wasm_module) DumpModule(wire_bytes, result.ok());
    return result;
  }
References v8::internal::wasm::WasmSectionIterator::advance(), v8::base::Vector< T >::begin(), v8::internal::bool, DecodeModuleHeader(), DecodeSection(), detected_features_, v8::internal::wasm::DumpModule(), enabled_features_, v8::internal::wasm::Decoder::end_, v8::internal::wasm::Decoder::failed(), FinishDecoding(), v8::internal::wasm::kUnknownSectionCode, v8::internal::wasm::max_module_size(), module_, v8::internal::wasm::WasmSectionIterator::more(), v8::internal::wasm::Decoder::ok(), v8::internal::wasm::WasmSectionIterator::payload(), v8::base::internal::result, v8::internal::wasm::WasmSectionIterator::section_code(), v8::base::Vector< T >::size(), v8::internal::wasm::Decoder::start_, v8::internal::wasm::Decoder::toResult(), tracer_, v8::internal::v8_flags, and v8::internal::wasm::ValidateFunctions().
DecodeModuleHeader()
void v8::internal::wasm::ModuleDecoderImpl::DecodeModuleHeader (base::Vector< const uint8_t > bytes) [inline]
Definition at line 329 of file module-decoder-impl.h.
                                                           {
    if (failed()) return;
    Reset(bytes);
    const uint8_t* pos = pc_;
    uint32_t magic_word = consume_u32("wasm magic", tracer_);
    if (tracer_) tracer_->NextLine();
#define BYTES(x) (x & 0xFF), (x >> 8) & 0xFF, (x >> 16) & 0xFF, (x >> 24) & 0xFF
    if (magic_word != kWasmMagic) {
      errorf(pos,
             "expected magic word %02x %02x %02x %02x, "
             "found %02x %02x %02x %02x",
             BYTES(kWasmMagic), BYTES(magic_word));
    }
    pos = pc_;
    {
      uint32_t magic_version = consume_u32("wasm version", tracer_);
      if (tracer_) tracer_->NextLine();
      if (magic_version != kWasmVersion) {
        errorf(pos,
               "expected version %02x %02x %02x %02x, "
               "found %02x %02x %02x %02x",
               BYTES(kWasmVersion), BYTES(magic_version));
      }
    }
#undef BYTES
  }
References BYTES, v8::internal::wasm::Decoder::consume_u32(), v8::internal::wasm::Decoder::errorf(), v8::internal::wasm::Decoder::failed(), v8::internal::wasm::kWasmMagic, v8::internal::wasm::kWasmVersion, v8::internal::wasm::ITracer::NextLine(), v8::internal::wasm::Decoder::pc_, v8::internal::wasm::Decoder::Reset(), and tracer_.
Referenced by DecodeModule().
DecodeNameSection()
void v8::internal::wasm::ModuleDecoderImpl::DecodeNameSection () [inline]
Definition at line 1546 of file module-decoder-impl.h.
                           {
    if (tracer_) {
      tracer_->NameSection(
          pc_, end_, buffer_offset_ + static_cast<uint32_t>(pc_ - start_));
    }
    // TODO(titzer): find a way to report name errors as warnings.
    // Ignore all but the first occurrence of name section.
    if (!has_seen_unordered_section(kNameSectionCode)) {
      set_seen_unordered_section(kNameSectionCode);
      module_->name_section = {buffer_offset_,
                               static_cast<uint32_t>(end_ - start_)};
      // Use an inner decoder so that errors don't fail the outer decoder.
      Decoder inner(start_, pc_, end_, buffer_offset_);
      // Decode all name subsections.
      // Be lenient with their order.
      while (inner.ok() && inner.more()) {
        uint8_t name_type = inner.consume_u8("name type");
        if (name_type & 0x80) inner.error("name type if not varuint7");
        uint32_t name_payload_len = inner.consume_u32v("name payload length");
        if (!inner.checkAvailable(name_payload_len)) break;
        // Decode module name, ignore the rest.
        // Function and local names will be decoded when needed.
        if (name_type == NameSectionKindCode::kModuleCode) {
          WireBytesRef name =
              consume_string(&inner, unibrow::Utf8Variant::kLossyUtf8,
                             "module name", ITracer::NoTrace);
          if (inner.ok() && validate_utf8(&inner, name)) {
            module_->name = name;
          }
        } else {
          inner.consume_bytes(name_payload_len, "name subsection payload");
        }
      }
    }
    // Skip the whole names section in the outer decoder.
    consume_bytes(static_cast<uint32_t>(end_ - start_), nullptr);
  }
References v8::internal::wasm::Decoder::buffer_offset_, v8::internal::wasm::Decoder::checkAvailable(), v8::internal::wasm::Decoder::consume_bytes(), v8::internal::wasm::consume_string(), v8::internal::wasm::Decoder::consume_u32v(), v8::internal::wasm::Decoder::consume_u8(), v8::internal::wasm::Decoder::end_, v8::internal::wasm::Decoder::error(), has_seen_unordered_section(), unibrow::kLossyUtf8, v8::internal::wasm::kModuleCode, v8::internal::wasm::kNameSectionCode, module_, v8::internal::wasm::Decoder::more(), v8::internal::wasm::name(), v8::internal::wasm::ITracer::NameSection(), v8::internal::wasm::ITracer::NoTrace, v8::internal::wasm::Decoder::ok(), v8::internal::wasm::Decoder::pc_, set_seen_unordered_section(), v8::internal::wasm::Decoder::start_, tracer_, and v8::internal::wasm::validate_utf8().
Referenced by DecodeSection().
DecodeSection()
void v8::internal::wasm::ModuleDecoderImpl::DecodeSection (SectionCode section_code, base::Vector< const uint8_t > bytes, uint32_t offset) [inline]
Definition at line 425 of file module-decoder-impl.h.
                                                                       {
    if (failed()) return;
    Reset(bytes, offset);
    TRACE("Section: %s\n", SectionName(section_code));
    TRACE("Decode Section %p - %p\n", bytes.begin(), bytes.end());
    if (!CheckSectionOrder(section_code)) return;
    switch (section_code) {
      case kUnknownSectionCode:
        break;
      case kTypeSectionCode:
        DecodeTypeSection();
        break;
      case kImportSectionCode:
        DecodeImportSection();
        break;
      case kFunctionSectionCode:
        DecodeFunctionSection();
        break;
      case kTableSectionCode:
        DecodeTableSection();
        break;
      case kMemorySectionCode:
        DecodeMemorySection();
        break;
      case kGlobalSectionCode:
        DecodeGlobalSection();
        break;
      case kExportSectionCode:
        DecodeExportSection();
        break;
      case kStartSectionCode:
        DecodeStartSection();
        break;
      case kCodeSectionCode:
        DecodeCodeSection();
        break;
      case kElementSectionCode:
        DecodeElementSection();
        break;
      case kDataSectionCode:
        DecodeDataSection();
        break;
      case kNameSectionCode:
        DecodeNameSection();
        break;
      case kSourceMappingURLSectionCode:
        DecodeSourceMappingURLSection();
        break;
      case kDebugInfoSectionCode:
        module_->debug_symbols[WasmDebugSymbols::Type::EmbeddedDWARF] = {
            WasmDebugSymbols::Type::EmbeddedDWARF, {}};
        consume_bytes(static_cast<uint32_t>(end_ - start_), ".debug_info");
        break;
      case kExternalDebugInfoSectionCode:
        DecodeExternalDebugInfoSection();
        break;
      case kBuildIdSectionCode:
        DecodeBuildIdSection();
        break;
      case kInstTraceSectionCode:
        if (enabled_features_.has_instruction_tracing()) {
          DecodeInstTraceSection();
        } else {
          // Ignore this section when feature is disabled. It is an optional
          // custom section anyways.
          consume_bytes(static_cast<uint32_t>(end_ - start_), nullptr);
        }
        break;
      case kCompilationHintsSectionCode:
        // TODO(jkummerow): We're missing tracing support for well-known
        // custom sections. This confuses `wami --full-hexdump` e.g.
        // for the modules created by
        // mjsunit/wasm/compilation-hints-streaming-compilation.js.
        if (enabled_features_.has_compilation_hints()) {
          DecodeCompilationHintsSection();
        } else {
          // Ignore this section when feature was disabled. It is an optional
          // custom section anyways.
          consume_bytes(static_cast<uint32_t>(end_ - start_), nullptr);
        }
        break;
      case kBranchHintsSectionCode:
        if (enabled_features_.has_branch_hinting()) {
          DecodeBranchHintsSection();
        } else {
          // Ignore this section when feature was disabled. It is an optional
          // custom section anyways.
          consume_bytes(static_cast<uint32_t>(end_ - start_), nullptr);
        }
        break;
      case kDescriptorsSectionCode:
        DecodeDescriptorsSection();
        break;
      case kDataCountSectionCode:
        DecodeDataCountSection();
        break;
      case kTagSectionCode:
        DecodeTagSection();
        break;
      case kStringRefSectionCode:
        if (enabled_features_.has_stringref()) {
          DecodeStringRefSection();
        } else {
          errorf(pc(),
                 "unexpected section <%s> (enable with "
                 "--experimental-wasm-stringref)",
                 SectionName(section_code));
        }
        break;
      default:
        errorf(pc(), "unexpected section <%s>", SectionName(section_code));
        return;
    }
    if (pc() != bytes.end()) {
      const char* msg = pc() < bytes.end() ? "shorter" : "longer";
      errorf(pc(),
             "section was %s than expected size "
             "(%zu bytes expected, %zu decoded)",
             msg, bytes.size(), static_cast<size_t>(pc() - bytes.begin()));
    }
  }
References v8::base::Vector< T >::begin(), CheckSectionOrder(), v8::internal::wasm::Decoder::consume_bytes(), DecodeBranchHintsSection(), DecodeBuildIdSection(), DecodeCodeSection(), DecodeCompilationHintsSection(), DecodeDataCountSection(), DecodeDataSection(), DecodeDescriptorsSection(), DecodeElementSection(), DecodeExportSection(), DecodeExternalDebugInfoSection(), DecodeFunctionSection(), DecodeGlobalSection(), DecodeImportSection(), DecodeInstTraceSection(), DecodeMemorySection(), DecodeNameSection(), DecodeSourceMappingURLSection(), DecodeStartSection(), DecodeStringRefSection(), DecodeTableSection(), DecodeTagSection(), DecodeTypeSection(), enabled_features_, v8::base::Vector< T >::end(), v8::internal::wasm::Decoder::end_, v8::internal::wasm::Decoder::errorf(), v8::internal::wasm::Decoder::failed(), v8::internal::wasm::kBranchHintsSectionCode, v8::internal::wasm::kBuildIdSectionCode, v8::internal::wasm::kCodeSectionCode, v8::internal::wasm::kCompilationHintsSectionCode, v8::internal::wasm::kDataCountSectionCode, v8::internal::wasm::kDataSectionCode, v8::internal::wasm::kDebugInfoSectionCode, v8::internal::wasm::kDescriptorsSectionCode, v8::internal::wasm::kElementSectionCode, v8::internal::wasm::kExportSectionCode, v8::internal::wasm::kExternalDebugInfoSectionCode, v8::internal::wasm::kFunctionSectionCode, v8::internal::wasm::kGlobalSectionCode, v8::internal::wasm::kImportSectionCode, v8::internal::wasm::kInstTraceSectionCode, v8::internal::wasm::kMemorySectionCode, v8::internal::wasm::kNameSectionCode, v8::internal::wasm::kSourceMappingURLSectionCode, v8::internal::wasm::kStartSectionCode, v8::internal::wasm::kStringRefSectionCode, v8::internal::wasm::kTableSectionCode, v8::internal::wasm::kTagSectionCode, v8::internal::wasm::kTypeSectionCode, v8::internal::wasm::kUnknownSectionCode, module_, v8::internal::wasm::Decoder::pc(), v8::internal::wasm::Decoder::Reset(), v8::internal::wasm::SectionName(), v8::base::Vector< T >::size(), v8::internal::wasm::Decoder::start_, and v8::internal::TRACE().
Referenced by DecodeModule().
DecodeSingleFunctionForTesting()
FunctionResult v8::internal::wasm::ModuleDecoderImpl::DecodeSingleFunctionForTesting (Zone * zone, ModuleWireBytes wire_bytes, const WasmModule * module) [inline]
Definition at line 2001 of file module-decoder-impl.h.
                                                                          {
    DCHECK(ok());
    pc_ = start_;
    expect_u8("type form", kWasmFunctionTypeCode);
    WasmFunction function;
    function.sig = consume_sig(zone);
    function.code = {off(pc_), static_cast<uint32_t>(end_ - pc_)};
    if (!ok()) return FunctionResult{std::move(error_)};
    constexpr bool kShared = false;
    FunctionBody body{function.sig, off(pc_), pc_, end_, kShared};
    WasmDetectedFeatures unused_detected_features;
    DecodeResult result = ValidateFunctionBody(zone, enabled_features_, module,
                                               &unused_detected_features, body);
    if (result.failed()) return FunctionResult{std::move(result).error()};
    return FunctionResult{std::make_unique<WasmFunction>(function)};
  }
References consume_sig(), v8::internal::DCHECK(), enabled_features_, v8::internal::wasm::Decoder::end_, v8::internal::wasm::Result< T >::error(), v8::internal::wasm::Decoder::error_, expect_u8(), v8::internal::wasm::kWasmFunctionTypeCode, off(), v8::internal::wasm::Decoder::ok(), v8::internal::wasm::Decoder::pc_, v8::base::internal::result, v8::internal::wasm::FunctionBody::sig, v8::internal::wasm::WasmFunction::sig, v8::internal::wasm::Decoder::start_, and v8::internal::wasm::ValidateFunctionBody().
DecodeSourceMappingURLSection()
void v8::internal::wasm::ModuleDecoderImpl::DecodeSourceMappingURLSection () [inline]
Definition at line 1596 of file module-decoder-impl.h.
                                       {
    Decoder inner(start_, pc_, end_, buffer_offset_);
    WireBytesRef url =
        wasm::consume_utf8_string(&inner, "module name", tracer_);
    if (inner.ok() &&
        module_->debug_symbols[WasmDebugSymbols::Type::SourceMap].type ==
            WasmDebugSymbols::None) {
      module_->debug_symbols[WasmDebugSymbols::Type::SourceMap] = {
          WasmDebugSymbols::Type::SourceMap, url};
    }
    set_seen_unordered_section(kSourceMappingURLSectionCode);
    consume_bytes(static_cast<uint32_t>(end_ - start_), nullptr);
  }
References v8::internal::wasm::Decoder::buffer_offset_, v8::internal::wasm::Decoder::consume_bytes(), v8::internal::wasm::consume_utf8_string(), v8::internal::wasm::Decoder::end_, v8::internal::wasm::kSourceMappingURLSectionCode, module_, v8::internal::wasm::WasmDebugSymbols::None, v8::internal::wasm::Decoder::ok(), v8::internal::wasm::Decoder::pc_, set_seen_unordered_section(), v8::internal::wasm::Decoder::start_, and tracer_.
Referenced by DecodeSection().
DecodeStartSection()
void v8::internal::wasm::ModuleDecoderImpl::DecodeStartSection () [inline]
Definition at line 1370 of file module-decoder-impl.h.
                            {
    if (tracer_) tracer_->StartOffset(pc_offset());
    WasmFunction* func;
    const uint8_t* pos = pc_;
    module_->start_function_index = consume_func_index(module_.get(), &func);
    if (tracer_) tracer_->NextLine();
    if (func &&
        (func->sig->parameter_count() > 0 || func->sig->return_count() > 0)) {
      error(pos, "invalid start function: non-zero parameter or return count");
    }
  }
References consume_func_index(), v8::internal::wasm::Decoder::error(), module_, v8::internal::wasm::ITracer::NextLine(), v8::internal::Signature< T >::parameter_count(), v8::internal::wasm::Decoder::pc_, v8::internal::wasm::Decoder::pc_offset(), v8::internal::Signature< T >::return_count(), v8::internal::wasm::WasmFunction::sig, v8::internal::wasm::ITracer::StartOffset(), and tracer_.
Referenced by DecodeSection().
DecodeStringRefSection()
void v8::internal::wasm::ModuleDecoderImpl::DecodeStringRefSection () [inline]
Definition at line 1890 of file module-decoder-impl.h.
                                {
    uint32_t deferred = consume_count("deferred string literal count",
                                      kV8MaxWasmStringLiterals);
    if (deferred) {
      errorf(pc(), "Invalid deferred string literal count %u (expected 0)",
             deferred);
    }
    uint32_t immediate = consume_count("string literal count",
                                       kV8MaxWasmStringLiterals - deferred);
    for (uint32_t i = 0; ok() && i < immediate; ++i) {
      TRACE("DecodeStringLiteral[%d] module+%d\n", i,
            static_cast<int>(pc_ - start_));
      if (tracer_) tracer_->StringOffset(pc_offset());
      // TODO(12868): Throw if the string's utf-16 length > String::kMaxLength.
      WireBytesRef pos = wasm::consume_string(this, unibrow::Utf8Variant::kWtf8,
                                              "string literal", tracer_);
      module_->stringref_literals.emplace_back(pos);
    }
  }
References consume_count(), v8::internal::wasm::consume_string(), v8::internal::wasm::Decoder::errorf(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::kV8MaxWasmStringLiterals, module_, v8::internal::wasm::Decoder::ok(), v8::internal::wasm::Decoder::pc(), v8::internal::wasm::Decoder::pc_, v8::internal::wasm::Decoder::pc_offset(), v8::internal::wasm::Decoder::start_, v8::internal::wasm::ITracer::StringOffset(), v8::internal::TRACE(), and tracer_.
Referenced by DecodeSection().
DecodeTableSection()
void v8::internal::wasm::ModuleDecoderImpl::DecodeTableSection () [inline]
Definition at line 1113 of file module-decoder-impl.h.
                            {
    static_assert(kV8MaxWasmTables <= kMaxUInt32);
    uint32_t table_count = consume_count("table count", kV8MaxWasmTables);
    for (uint32_t i = 0; ok() && i < table_count; i++) {
      if (tracer_) tracer_->TableOffset(pc_offset());
      module_->tables.emplace_back();
      WasmTable* table = &module_->tables.back();
      const uint8_t* type_position = pc();
      bool has_initializer = false;
      if (read_u8<Decoder::FullValidationTag>(
              pc(), "table-with-initializer byte") == 0x40) {
        consume_bytes(1, "with-initializer ", tracer_);
        has_initializer = true;
        type_position++;
        uint8_t reserved = consume_u8("reserved-byte", tracer_);
        if (reserved != 0) {
          error(type_position, "Reserved byte must be 0x00");
          break;
        }
        type_position++;
      }
      ValueType table_type = consume_value_type(module_.get());
      if (!table_type.is_object_reference()) {
        error(type_position, "Only reference types can be used as table types");
        break;
      }
      if (!has_initializer && !table_type.is_defaultable()) {
        errorf(type_position,
               "Table of non-defaultable table %s needs initial value",
               table_type.name().c_str());
        break;
      }
      table->type = table_type;
      consume_table_flags(table);
      DCHECK_IMPLIES(table->shared, enabled_features_.has_shared() || !ok());
      if (table->shared && enabled_features_.has_shared()) {
        module_->has_shared_part = true;
        if (!table_type.is_shared()) {
          errorf(
              type_position,
              "Shared table %i must have shared element type, actual type %s",
              i + module_->num_imported_tables, table_type.name().c_str());
          break;
        }
      }
      // Note that we should not throw an error if the declared maximum size is
      // oob. We will instead fail when growing at runtime.
      uint64_t kNoMaximum = kMaxUInt64;
      consume_resizable_limits(
          "table", "elements", wasm::max_table_size(), &table->initial_size,
          table->has_maximum_size, kNoMaximum, &table->maximum_size,
          table->is_table64() ? k64BitLimits : k32BitLimits);
      if (has_initializer) {
        table->initial_value =
            consume_init_expr(module_.get(), table_type, table->shared);
      }
    }
  }
References v8::internal::wasm::Decoder::consume_bytes(), consume_count(), consume_init_expr(), consume_resizable_limits(), consume_table_flags(), v8::internal::wasm::Decoder::consume_u8(), consume_value_type(), DCHECK_IMPLIES, enabled_features_, v8::internal::wasm::Decoder::error(), v8::internal::wasm::Decoder::errorf(), v8::internal::wasm::WasmTable::has_maximum_size, v8::internal::wasm::WasmTable::initial_size, v8::internal::wasm::WasmTable::initial_value, v8::internal::wasm::ValueTypeBase::is_defaultable(), v8::internal::wasm::ValueTypeBase::is_object_reference(), v8::internal::wasm::ValueTypeBase::is_shared(), v8::internal::wasm::WasmTable::is_table64(), k32BitLimits, k64BitLimits, v8::internal::kMaxUInt32, v8::internal::kMaxUInt64, v8::internal::wasm::kNoMaximum, v8::internal::wasm::kV8MaxWasmTables, v8::internal::wasm::max_table_size(), v8::internal::wasm::WasmTable::maximum_size, module_, v8::internal::wasm::ValueTypeBase::name(), v8::internal::wasm::Decoder::ok(), v8::internal::wasm::Decoder::pc(), v8::internal::wasm::Decoder::pc_offset(), v8::internal::wasm::WasmTable::shared, v8::internal::wasm::ITracer::TableOffset(), tracer_, and v8::internal::wasm::WasmTable::type.
Referenced by DecodeSection().
DecodeTagSection()
void v8::internal::wasm::ModuleDecoderImpl::DecodeTagSection () [inline]
Definition at line 1877 of file module-decoder-impl.h.
                          {
    uint32_t tag_count = consume_count("tag count", kV8MaxWasmTags);
    for (uint32_t i = 0; ok() && i < tag_count; ++i) {
      TRACE("DecodeTag[%d] module+%d\n", i, static_cast<int>(pc_ - start_));
      if (tracer_) tracer_->TagOffset(pc_offset());
      const WasmTagSig* tag_sig = nullptr;
      consume_exception_attribute(); // Attribute ignored for now.
      ModuleTypeIndex sig_index =
          consume_tag_sig_index(module_.get(), &tag_sig);
      module_->tags.emplace_back(tag_sig, sig_index);
    }
  }
References consume_count(), consume_exception_attribute(), consume_tag_sig_index(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::kV8MaxWasmTags, module_, v8::internal::wasm::Decoder::ok(), v8::internal::wasm::Decoder::pc_, v8::internal::wasm::Decoder::pc_offset(), v8::internal::wasm::Decoder::start_, v8::internal::wasm::ITracer::TagOffset(), v8::internal::TRACE(), and tracer_.
Referenced by DecodeSection().
DecodeTypeSection()
void v8::internal::wasm::ModuleDecoderImpl::DecodeTypeSection () [inline]
Definition at line 745 of file module-decoder-impl.h.
                           {
    TypeCanonicalizer* type_canon = GetTypeCanonicalizer();
    uint32_t types_count = consume_count("types count", kV8MaxWasmTypes);
    for (uint32_t i = 0; ok() && i < types_count; ++i) {
      TRACE("DecodeType[%d] module+%d\n", i, static_cast<int>(pc_ - start_));
      uint8_t kind = read_u8<Decoder::FullValidationTag>(pc(), "type kind");
      size_t initial_size = module_->types.size();
      uint32_t group_size = 1;
      if (kind == kWasmRecursiveTypeGroupCode) {
        module_->is_wasm_gc = true;
        uint32_t rec_group_offset = pc_offset();
        consume_bytes(1, "rec. group definition", tracer_);
        if (tracer_) tracer_->NextLine();
        group_size = consume_count("recursive group size", kV8MaxWasmTypes);
        if (tracer_) tracer_->RecGroupOffset(rec_group_offset, group_size);
      }
      if (initial_size + group_size > kV8MaxWasmTypes) {
        errorf(pc(), "Type definition count exceeds maximum %zu",
               kV8MaxWasmTypes);
        return;
      }
      // We need to resize types before decoding the type definitions in this
      // group, so that the correct type size is visible to type definitions.
      module_->types.resize(initial_size + group_size);
      for (uint32_t j = 0; j < group_size; j++) {
        if (tracer_) tracer_->TypeOffset(pc_offset());
        TypeDefinition type = consume_subtype_definition(initial_size + j);
        if (failed()) return;
        module_->types[initial_size + j] = type;
      }
      FinalizeRecgroup(group_size, type_canon);
      if (kind == kWasmRecursiveTypeGroupCode && tracer_) {
        tracer_->Description("end of rec. group");
        tracer_->NextLine();
      }
    }
  }
References v8::internal::wasm::Decoder::consume_bytes(), consume_count(), consume_subtype_definition(), v8::internal::wasm::ITracer::Description(), v8::internal::wasm::Decoder::errorf(), v8::internal::wasm::Decoder::failed(), FinalizeRecgroup(), v8::internal::wasm::GetTypeCanonicalizer(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::kV8MaxWasmTypes, v8::internal::wasm::kWasmRecursiveTypeGroupCode, module_, v8::internal::wasm::ITracer::NextLine(), v8::internal::wasm::Decoder::ok(), v8::internal::wasm::Decoder::pc(), v8::internal::wasm::Decoder::pc_, v8::internal::wasm::Decoder::pc_offset(), v8::internal::wasm::ITracer::RecGroupOffset(), v8::internal::wasm::Decoder::start_, v8::internal::TRACE(), tracer_, v8::internal::tracing::type, and v8::internal::wasm::ITracer::TypeOffset().
Referenced by DecodeSection().
expect_u8()
bool v8::internal::wasm::ModuleDecoderImpl::expect_u8 (const char * name, uint8_t expected) [inline], [private]
Definition at line 2335 of file module-decoder-impl.h.
                                                     {
    const uint8_t* pos = pc();
    uint8_t value = consume_u8(name);
    if (value != expected) {
      errorf(pos, "expected %s 0x%02x, got 0x%02x", name, expected, value);
      return false;
    }
    return true;
  }
References v8::internal::wasm::Decoder::consume_u8(), v8::internal::wasm::Decoder::errorf(), v8::internal::wasm::name(), v8::internal::wasm::Decoder::pc(), and v8::internal::value.
Referenced by DecodeFunctionSignatureForTesting(), and DecodeSingleFunctionForTesting().
FinalizeRecgroup()
void v8::internal::wasm::ModuleDecoderImpl::FinalizeRecgroup (uint32_t group_size, TypeCanonicalizer * type_canon) [inline]
Definition at line 784 of file module-decoder-impl.h.
                                                                            {
    // Now that we have decoded the entire recgroup, check its validity,
    // initialize additional data, and canonicalize it:
    // - check supertype validity
    // - propagate subtyping depths
    // - validate is_shared bits and set up RefTypeKind fields
    WasmModule* module = module_.get();
    uint32_t end_index = static_cast<uint32_t>(module->types.size());
    uint32_t start_index = end_index - group_size;
    for (uint32_t i = start_index; ok() && i < end_index; ++i) {
      TypeDefinition& type_def = module_->types[i];
      bool is_shared = type_def.is_shared;
      switch (type_def.kind) {
        case TypeDefinition::kFunction: {
          base::Vector<const ValueType> all = type_def.function_sig->all();
          size_t count = all.size();
          ValueType* storage = const_cast<ValueType*>(all.begin());
          for (uint32_t j = 0; j < count; j++) {
            value_type_reader::Populate(&storage[j], module);
            ValueType type = storage[j];
            if (is_shared && !type.is_shared()) {
              DCHECK(enabled_features_.has_shared());
              uint32_t retcount =
                  static_cast<uint32_t>(type_def.function_sig->return_count());
              const char* param_or_return =
                  j < retcount ? "return" : "parameter";
              uint32_t index = j < retcount ? j : j - retcount;
              // {pc_} isn't very accurate, it's pointing at the end of the
              // recgroup. So to ease debugging, we print the type's index.
              errorf(pc_,
                     "Type %u: shared signature must have shared %s types, "
                     "actual type for %s %d is %s",
                     i, param_or_return, param_or_return, index,
                     type.name().c_str());
              return;
            }
          }
          break;
        }
        case TypeDefinition::kStruct: {
          size_t count = type_def.struct_type->field_count();
          ValueType* storage =
              const_cast<ValueType*>(type_def.struct_type->fields().begin());
          for (uint32_t j = 0; j < count; j++) {
            value_type_reader::Populate(&storage[j], module);
            ValueType type = storage[j];
            if (is_shared && !type.is_shared()) {
              errorf(pc_,
                     "Type %u: shared struct must have shared field types, "
                     "actual type for field %d is %s",
                     i, j, type.name().c_str());
              return;
            }
          }
          if (type_def.descriptor.valid()) {
            const TypeDefinition& descriptor =
                module->type(type_def.descriptor);
            if (descriptor.describes.index != i) {
              uint32_t d = type_def.descriptor.index;
              errorf(pc_,
                     "Type %u has descriptor %u but %u doesn't describe %u", i,
                     d, d, i);
              return;
            }
            if (descriptor.is_shared != type_def.is_shared) {
              errorf(pc_,
                     "Type %u and its descriptor %u must have same sharedness",
                     i, type_def.descriptor.index);
              return;
            }
          }
          if (type_def.describes.valid()) {
            if (module->type(type_def.describes).descriptor.index != i) {
              uint32_t d = type_def.describes.index;
              errorf(pc_,
                     "Type %u describes %u but %u isn't a descriptor for %u", i,
                     d, d, i);
              return;
            }
          }
          break;
        }
        case TypeDefinition::kArray: {
          value_type_reader::Populate(
              const_cast<ArrayType*>(type_def.array_type)
                  ->element_type_writable_ptr(),
              module);
          ValueType type = type_def.array_type->element_type();
          if (is_shared && !type.is_shared()) {
            errorf(pc_,
                   "Type %u: shared array must have shared element type, "
                   "actual element type is %s",
                   i, type.name().c_str());
            return;
          }
          break;
        }
        case TypeDefinition::kCont: {
          ModuleTypeIndex contfun_typeid =
              type_def.cont_type->contfun_typeindex();
          const TypeDefinition contfun_type =
              module_->types[contfun_typeid.index];
          if (contfun_type.kind != TypeDefinition::kFunction) {
            errorf(pc_,
                   "Type %u: cont type must refer to a signature index, "
                   "actual type is %s",
                   i, module_->heap_type(contfun_typeid).name().c_str());
            return;
          }
          if (is_shared && !contfun_type.is_shared) {
            errorf(pc_,
                   "Type %u: shared cont type must refer to a shared signature,"
                   " actual type is %s",
                   module_->heap_type(contfun_typeid).name().c_str());
            return;
          }
          break;
        }
      }
    }
    module->isorecursive_canonical_type_ids.resize(end_index);
    type_canon->AddRecursiveGroup(module, group_size);
    for (uint32_t i = start_index; ok() && i < end_index; ++i) {
      TypeDefinition& type_def = module_->types[i];
      ModuleTypeIndex explicit_super = type_def.supertype;
      if (!explicit_super.valid()) continue; // No supertype.
      DCHECK_LT(explicit_super.index, i); // Checked during decoding.
      uint32_t depth = module->type(explicit_super).subtyping_depth + 1;
      type_def.subtyping_depth = depth;
      DCHECK_GE(depth, 0);
      if (depth > kV8MaxRttSubtypingDepth) {
        errorf("type %u: subtyping depth is greater than allowed", i);
        return;
      }
      // This check is technically redundant; we include for the improved error
      // message.
      if (module->type(explicit_super).is_final) {
        errorf("type %u extends final type %u", i, explicit_super.index);
        return;
      }
      if (!ValidSubtypeDefinition(ModuleTypeIndex{i}, explicit_super, module)) {
        errorf("type %u has invalid explicit supertype %u", i,
               explicit_super.index);
        return;
      }
    }
  }
References v8::internal::wasm::TypeCanonicalizer::AddRecursiveGroup(), v8::internal::Signature< T >::all(), all, v8::internal::wasm::TypeDefinition::array_type, v8::internal::wasm::TypeDefinition::cont_type, v8::internal::wasm::ContType::contfun_typeindex(), v8::internal::DCHECK(), DCHECK_GE, DCHECK_LT, v8::internal::wasm::TypeDefinition::describes, v8::internal::wasm::TypeDefinition::descriptor, v8::internal::wasm::ArrayType::element_type(), v8::internal::wasm::ArrayType::element_type_writable_ptr(), enabled_features_, v8::internal::wasm::Decoder::errorf(), v8::internal::wasm::StructTypeBase::field_count(), v8::internal::wasm::StructType::fields(), v8::internal::wasm::TypeDefinition::function_sig, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::wasm::TypeIndex::index, v8::internal::wasm::TypeDefinition::is_final, v8::internal::is_shared, v8::internal::wasm::TypeDefinition::is_shared, v8::internal::wasm::WasmModule::isorecursive_canonical_type_ids, v8::internal::wasm::TypeDefinition::kArray, v8::internal::wasm::TypeDefinition::kCont, v8::internal::wasm::TypeDefinition::kFunction, v8::internal::wasm::TypeDefinition::kind, v8::internal::wasm::TypeDefinition::kStruct, v8::internal::wasm::kV8MaxRttSubtypingDepth, module_, v8::internal::wasm::Decoder::ok(), v8::internal::wasm::Decoder::pc_, v8::internal::wasm::value_type_reader::Populate(), v8::internal::Signature< T >::return_count(), v8::internal::wasm::TypeDefinition::struct_type, v8::internal::wasm::TypeDefinition::subtyping_depth, v8::internal::wasm::TypeDefinition::supertype, v8::internal::tracing::type, v8::internal::wasm::WasmModule::type(), v8::internal::wasm::WasmModule::types, v8::internal::wasm::TypeIndex::valid(), and v8::internal::wasm::ValidSubtypeDefinition().
Referenced by DecodeTypeSection().
FinishDecoding()
ModuleResult v8::internal::wasm::ModuleDecoderImpl::FinishDecoding () [inline]
Definition at line 1933 of file module-decoder-impl.h.
                                {
    if (ok() && CheckMismatchedCounts()) {
      // We calculate the global offsets here, because there may not be a
      // global section and code section that would have triggered the
      // calculation before. Even without the globals section the calculation
      // is needed because globals can also be defined in the import section.
      CalculateGlobalOffsets(module_.get());
    }
    if (module_->has_shared_part) detected_features_->add_shared();
    return toResult(std::move(module_));
  }
References CalculateGlobalOffsets(), CheckMismatchedCounts(), detected_features_, module_, v8::internal::wasm::Decoder::ok(), and v8::internal::wasm::Decoder::toResult().
Referenced by DecodeModule().
has_seen_unordered_section()
bool v8::internal::wasm::ModuleDecoderImpl::has_seen_unordered_section (SectionCode section_code) [inline], [private]
Definition at line 2054 of file module-decoder-impl.h.
                                                            {
    return seen_unordered_sections_ & (1 << section_code);
  }
References seen_unordered_sections_.
Referenced by CheckDataSegmentsCount(), CheckSectionOrder(), DecodeBranchHintsSection(), DecodeCompilationHintsSection(), DecodeDescriptorsSection(), DecodeInstTraceSection(), and DecodeNameSection().
off()
uint32_t v8::internal::wasm::ModuleDecoderImpl::off (const uint8_t * ptr) [inline], [private]
Definition at line 2062 of file module-decoder-impl.h.
                                   {
    return static_cast<uint32_t>(ptr - start_) + buffer_offset_;
  }
References v8::internal::wasm::Decoder::buffer_offset_, and v8::internal::wasm::Decoder::start_.
Referenced by DecodeSingleFunctionForTesting().
onFirstError()
void v8::internal::wasm::ModuleDecoderImpl::onFirstError () [inline], [override], [virtual]
Reimplemented from v8::internal::wasm::Decoder.
Definition at line 325 of file module-decoder-impl.h.
                               {
    pc_ = end_; // On error, terminate section decoding loop.
  }
References v8::internal::wasm::Decoder::end_, and v8::internal::wasm::Decoder::pc_.
set_seen_unordered_section()
void v8::internal::wasm::ModuleDecoderImpl::set_seen_unordered_section (SectionCode section_code) [inline], [private]
Definition at line 2058 of file module-decoder-impl.h.
                                                            {
    seen_unordered_sections_ |= 1 << section_code;
  }
References seen_unordered_sections_.
Referenced by CheckSectionOrder(), DecodeBranchHintsSection(), DecodeBuildIdSection(), DecodeCompilationHintsSection(), DecodeDescriptorsSection(), DecodeExternalDebugInfoSection(), DecodeInstTraceSection(), DecodeNameSection(), and DecodeSourceMappingURLSection().
shared_module()
const std::shared_ptr<WasmModule>& v8::internal::wasm::ModuleDecoderImpl::shared_module () const [inline]
Definition at line 2051 of file module-decoder-impl.h.
{ return module_; }
References module_.
StartCodeSection()
void v8::internal::wasm::ModuleDecoderImpl::StartCodeSection (WireBytesRef section_bytes) [inline]
Definition at line 1465 of file module-decoder-impl.h.
                                                    {
    CheckSectionOrder(kCodeSectionCode);
    // Make sure global offset were calculated before they get accessed during
    // function compilation.
    CalculateGlobalOffsets(module_.get());
    module_->code = section_bytes;
  }
References CalculateGlobalOffsets(), CheckSectionOrder(), v8::internal::wasm::kCodeSectionCode, and module_.
TypeKindName()
static constexpr const char* v8::internal::wasm::ModuleDecoderImpl::TypeKindName (uint8_t kind) [inline], [static], [constexpr]
Definition at line 551 of file module-decoder-impl.h.
                                                          {
    switch (kind) {
      // clang-format off
      case kWasmFunctionTypeCode: return "func";
      case kWasmStructTypeCode: return "struct";
      case kWasmArrayTypeCode: return "array";
      case kWasmContTypeCode: return "cont";
      default: return "unknown";
        // clang-format on
    }
  }
References v8::internal::wasm::kWasmArrayTypeCode, v8::internal::wasm::kWasmContTypeCode, v8::internal::wasm::kWasmFunctionTypeCode, and v8::internal::wasm::kWasmStructTypeCode.
Referenced by consume_base_type_definition().
UpdateComputedMemoryInformation()
void v8::internal::wasm::ModuleDecoderImpl::UpdateComputedMemoryInformation () [inline]
Definition at line 1215 of file module-decoder-impl.h.
                                         {
    for (WasmMemory& memory : module_->memories) {
      UpdateComputedInformation(&memory, module_->origin);
    }
  }
References module_, and v8::internal::wasm::UpdateComputedInformation().
Referenced by DecodeImportSection(), and DecodeMemorySection().
Member Data Documentation
allocator_
AccountingAllocator v8::internal::wasm::ModuleDecoderImpl::allocator_ [private]
Definition at line 2895 of file module-decoder-impl.h.
detected_features_
WasmDetectedFeatures* const v8::internal::wasm::ModuleDecoderImpl::detected_features_ [private]
Definition at line 2877 of file module-decoder-impl.h.
Referenced by consume_described_type(), consume_describing_type(), consume_heap_type(), consume_init_expr(), consume_memory_flags(), consume_sig(), consume_table_flags(), consume_value_type(), DecodeBranchHintsSection(), DecodeImportSection(), DecodeMemorySection(), DecodeModule(), and FinishDecoding().
enabled_features_
const WasmEnabledFeatures v8::internal::wasm::ModuleDecoderImpl::enabled_features_ [private]
Definition at line 2876 of file module-decoder-impl.h.
Referenced by consume_base_type_definition(), consume_data_segment_header(), consume_described_type(), consume_describing_type(), consume_element_func_index(), consume_element_segment_header(), consume_global_flags(), consume_heap_type(), consume_init_expr(), consume_limits_byte(), consume_shared_type(), consume_tag_sig_index(), consume_value_type(), DecodeDescriptorsSection(), DecodeGlobalSection(), DecodeImportSection(), DecodeModule(), DecodeSection(), DecodeSingleFunctionForTesting(), DecodeTableSection(), and FinalizeRecgroup().
init_expr_zone_
Zone v8::internal::wasm::ModuleDecoderImpl::init_expr_zone_ {&allocator_, `constant expr. zone`} [private]
Definition at line 2900 of file module-decoder-impl.h.
Referenced by consume_init_expr().
inst_traces_
std::vector<std::tuple<uint32_t, uint32_t, uint32_t> > v8::internal::wasm::ModuleDecoderImpl::inst_traces_ [private]
Definition at line 2906 of file module-decoder-impl.h.
Referenced by DecodeCodeSection(), and DecodeInstTraceSection().
module_
const std::shared_ptr<WasmModule> v8::internal::wasm::ModuleDecoderImpl::module_ [private]
Definition at line 2878 of file module-decoder-impl.h.
Referenced by CheckDataSegmentsCount(), CheckFunctionsCount(), CheckMismatchedCounts(), consume_base_type_definition(), consume_data_segment_header(), consume_described_type(), consume_element_segment_header(), consume_heap_type(), consume_shared_type(), consume_subtype_definition(), consume_value_type(), DecodeBranchHintsSection(), DecodeBuildIdSection(), DecodeCodeSection(), DecodeCompilationHintsSection(), DecodeDataCountSection(), DecodeDataSection(), DecodeDescriptorsSection(), DecodeElementSection(), DecodeExportSection(), DecodeExternalDebugInfoSection(), DecodeFunctionBody(), DecodeFunctionSection(), DecodeGlobalSection(), DecodeImportSection(), DecodeInitExprForTesting(), DecodeMemorySection(), DecodeModule(), DecodeNameSection(), DecodeSection(), DecodeSourceMappingURLSection(), DecodeStartSection(), DecodeStringRefSection(), DecodeTableSection(), DecodeTagSection(), DecodeTypeSection(), FinalizeRecgroup(), FinishDecoding(), shared_module(), StartCodeSection(), and UpdateComputedMemoryInformation().
module_end_
const uint8_t* v8::internal::wasm::ModuleDecoderImpl::module_end_ = nullptr [private]
Definition at line 2880 of file module-decoder-impl.h.
module_start_
const uint8_t* v8::internal::wasm::ModuleDecoderImpl::module_start_ = nullptr [private]
Definition at line 2879 of file module-decoder-impl.h.
next_ordered_section_
uint8_t v8::internal::wasm::ModuleDecoderImpl::next_ordered_section_ = kFirstSectionInModule [private]
Definition at line 2883 of file module-decoder-impl.h.
Referenced by CheckSectionOrder(), and DecodeCompilationHintsSection().
seen_unordered_sections_
uint32_t v8::internal::wasm::ModuleDecoderImpl::seen_unordered_sections_ = 0 [private]
Definition at line 2890 of file module-decoder-impl.h.
Referenced by has_seen_unordered_section(), and set_seen_unordered_section().
tracer_
ITracer* v8::internal::wasm::ModuleDecoderImpl::tracer_ [private]
Definition at line 2881 of file module-decoder-impl.h.
Referenced by consume_array(), consume_base_type_definition(), consume_count(), consume_data_segment_header(), consume_described_type(), consume_describing_type(), consume_element_func_index(), consume_element_segment_header(), consume_exception_attribute(), consume_global_flags(), consume_heap_type(), consume_index(), consume_init_expr(), consume_limits_byte(), consume_mutability(), consume_resizable_limits(), consume_shared_type(), consume_sig(), consume_sig_index(), consume_storage_type(), consume_struct(), consume_subtype_definition(), consume_value_type(), DecodeCodeSection(), DecodeDataCountSection(), DecodeDataSection(), DecodeElementSection(), DecodeExportSection(), DecodeExternalDebugInfoSection(), DecodeFunctionBody(), DecodeFunctionSection(), DecodeGlobalSection(), DecodeImportSection(), DecodeMemorySection(), DecodeModule(), DecodeModuleHeader(), DecodeNameSection(), DecodeSourceMappingURLSection(), DecodeStartSection(), DecodeStringRefSection(), DecodeTableSection(), DecodeTagSection(), and DecodeTypeSection().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/module-decoder-impl.h