v8::internal::compiler::MegaDOMPropertyAccessFeedback Class Reference
#include <processed-feedback.h>
Public Member Functions
MegaDOMPropertyAccessFeedback (FunctionTemplateInfoRef info_ref, FeedbackSlotKind slot_kind)
FunctionTemplateInfoRef info () const
Private Attributes
FunctionTemplateInfoRef const info_
Additional Inherited Members
Detailed Description
Definition at line 191 of file processed-feedback.h.
Constructor & Destructor Documentation
MegaDOMPropertyAccessFeedback()
v8::internal::compiler::MegaDOMPropertyAccessFeedback::MegaDOMPropertyAccessFeedback (FunctionTemplateInfoRef info_ref, FeedbackSlotKind slot_kind)
Definition at line 409 of file js-heap-broker.cc.
    : ProcessedFeedback(kMegaDOMPropertyAccess, slot_kind), info_(info_ref) {
  DCHECK(IsLoadICKind(slot_kind));
}
References v8::internal::DCHECK(), v8::internal::IsLoadICKind(), and v8::internal::compiler::ProcessedFeedback::slot_kind().
Member Function Documentation
info()
FunctionTemplateInfoRef v8::internal::compiler::MegaDOMPropertyAccessFeedback::info () const [inline]
Definition at line 196 of file processed-feedback.h.
{ return info_; }
References info_.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceMegaDOMPropertyAccess().
Member Data Documentation
info_
FunctionTemplateInfoRef const v8::internal::compiler::MegaDOMPropertyAccessFeedback::info_ [private]
Definition at line 199 of file processed-feedback.h.
Referenced by info().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/processed-feedback.h
/mnt/V8SourceCode/src/compiler/js-heap-broker.cc