v8::internal::compiler::CompilationDependencies Class Reference
#include <compilation-dependencies.h>
Classes
struct CompilationDependencyEqual
struct CompilationDependencyHash
Public Member Functions
CompilationDependencies (JSHeapBroker *broker, Zone *zone)
V8_WARN_UNUSED_RESULT bool Commit (Handle< Code > code)
MapRef DependOnInitialMap (JSFunctionRef function)
HeapObjectRef DependOnPrototypeProperty (JSFunctionRef function)
void DependOnStableMap (MapRef map)
void DependOnNoSlackTrackingChange (MapRef map)
void DependOnConstantInDictionaryPrototypeChain (MapRef receiver_map, NameRef property_name, ObjectRef constant, PropertyKind kind)
AllocationType DependOnPretenureMode (AllocationSiteRef site)
PropertyConstness DependOnFieldConstness (MapRef map, MapRef owner, InternalIndex descriptor)
CompilationDependency const * FieldConstnessDependencyOffTheRecord (MapRef map, MapRef owner, InternalIndex descriptor)
void DependOnGlobalProperty (PropertyCellRef cell)
bool DependOnContextCell (ContextRef script_context, size_t index, ContextCell::State state, JSHeapBroker *broker)
bool DependOnContextCell (ContextCellRef slot, ContextCell::State state)
bool DependOnEmptyContextExtension (ScopeInfoRef scope_info)
bool DependOnProtector (PropertyCellRef cell)
bool DependOnArrayBufferDetachingProtector ()
bool DependOnArrayIteratorProtector ()
bool DependOnArraySpeciesProtector ()
bool DependOnNoElementsProtector ()
bool DependOnNoDateTimeConfigurationChangeProtector ()
bool DependOnPromiseHookProtector ()
bool DependOnPromiseSpeciesProtector ()
bool DependOnPromiseThenProtector ()
bool DependOnMegaDOMProtector ()
bool DependOnNoProfilingProtector ()
bool DependOnNoUndetectableObjectsProtector ()
bool DependOnStringWrapperToPrimitiveProtector ()
void DependOnElementsKind (AllocationSiteRef site)
void DependOnObjectSlotValue (HeapObjectRef object, int offset, ObjectRef value)
void DependOnOwnConstantElement (JSObjectRef holder, uint32_t index, ObjectRef element)
void DependOnOwnConstantDataProperty (JSObjectRef holder, MapRef map, FieldIndex index, ObjectRef value)
void DependOnOwnConstantDoubleProperty (JSObjectRef holder, MapRef map, FieldIndex index, Float64 value)
void DependOnOwnConstantDictionaryProperty (JSObjectRef holder, InternalIndex index, ObjectRef value)
void DependOnStablePrototypeChains (ZoneVector< MapRef > const &receiver_maps, WhereToStart start, OptionalJSObjectRef last_prototype=OptionalJSObjectRef())
void DependOnStablePrototypeChain (MapRef receiver_maps, WhereToStart start, OptionalJSObjectRef last_prototype=OptionalJSObjectRef())
void DependOnElementsKinds (AllocationSiteRef site)
void DependOnConsistentJSFunctionView (JSFunctionRef function)
SlackTrackingPrediction DependOnInitialMapInstanceSizePrediction (JSFunctionRef function)
void RecordDependency (CompilationDependency const *dependency)
CompilationDependency const * TransitionDependencyOffTheRecord (MapRef target_map) const
CompilationDependency const * FieldRepresentationDependencyOffTheRecord (MapRef map, MapRef owner, InternalIndex descriptor, Representation representation) const
CompilationDependency const * FieldTypeDependencyOffTheRecord (MapRef map, MapRef owner, InternalIndex descriptor, ObjectRef type) const
Private Types
using CompilationDependencySet = ZoneUnorderedSet< const CompilationDependency *, CompilationDependencyHash, CompilationDependencyEqual >
Private Member Functions
bool PrepareInstall ()
bool PrepareInstallPredictable ()
Private Attributes
Zone *const zone_
JSHeapBroker *const broker_
CompilationDependencySet dependencies_
Detailed Description
Definition at line 32 of file compilation-dependencies.h.
Member Typedef Documentation
CompilationDependencySet
using v8::internal::compiler::CompilationDependencies::CompilationDependencySet = ZoneUnorderedSet<const CompilationDependency*, CompilationDependencyHash, CompilationDependencyEqual> [private]
Definition at line 205 of file compilation-dependencies.h.
Constructor & Destructor Documentation
CompilationDependencies()
v8::internal::compiler::CompilationDependencies::CompilationDependencies (JSHeapBroker * broker, Zone * zone)
Definition at line 50 of file compilation-dependencies.cc.
    : zone_(zone), broker_(broker), dependencies_(zone) {
  broker->set_dependencies(this);
}
References broker().
Member Function Documentation
Commit()
bool v8::internal::compiler::CompilationDependencies::Commit (Handle< Code > code)
Definition at line 1456 of file compilation-dependencies.cc.
                                                      {
  if (!PrepareInstall()) return false;
  {
    PendingDependencies pending_deps(zone_);
    DisallowCodeDependencyChange no_dependency_change;
    for (const CompilationDependency* dep : dependencies_) {
      // Check each dependency's validity again right before installing it,
      // because the first iteration above might have invalidated some
      // dependencies. For example, PrototypePropertyDependency::PrepareInstall
      // can call EnsureHasInitialMap, which can invalidate a
      // StableMapDependency on the prototype object's map.
      if (!dep->IsValid(broker_)) {
        if (v8_flags.trace_compilation_dependencies) {
          TraceInvalidCompilationDependency(broker_, dep);
        }
        dependencies_.clear();
        return false;
      }
      dep->Install(broker_, &pending_deps);
    }
    pending_deps.InstallAll(broker_->isolate(), code);
  }
  // It is even possible that a GC during the above installations invalidated
  // one of the dependencies. However, this should only affect
  //
  // 1. pretenure mode dependencies, or
  // 2. function consistency dependencies,
  //
  // which we assert below. It is safe to return successfully in these cases,
  // because
  //
  // 1. once the code gets executed it will do a stack check that triggers its
  // deoptimization.
  // 2. since the function state was deemed consistent above, that means the
  // compilation saw a self-consistent state of the jsfunction.
  if (v8_flags.stress_gc_during_compilation) {
    broker_->isolate()->heap()->PreciseCollectAllGarbage(
        GCFlag::kForced, GarbageCollectionReason::kTesting, kNoGCCallbackFlags);
  }
#ifdef DEBUG
  for (auto dep : dependencies_) {
    CHECK_IMPLIES(!dep->IsValid(broker_),
                  dep->IsPretenureMode() || dep->IsConsistentJSFunctionView());
  }
#endif
  dependencies_.clear();
  return true;
}
References broker_, CHECK_IMPLIES, code, dependencies_, v8::internal::Isolate::heap(), v8::internal::compiler::JSHeapBroker::isolate(), v8::internal::kForced, v8::kNoGCCallbackFlags, v8::internal::kTesting, v8::internal::Heap::PreciseCollectAllGarbage(), PrepareInstall(), v8::internal::compiler::TraceInvalidCompilationDependency(), v8::internal::v8_flags, and zone_.
Referenced by v8::internal::maglev::MaglevCompiler::GenerateCode().
DependOnArrayBufferDetachingProtector()
bool v8::internal::compiler::CompilationDependencies::DependOnArrayBufferDetachingProtector ()
Definition at line 1358 of file compilation-dependencies.cc.
                                                                    {
  return DependOnProtector(MakeRef(
      broker_,
      broker_->isolate()->factory()->array_buffer_detaching_protector()));
}
References broker_, DependOnProtector(), v8::internal::Isolate::factory(), v8::internal::compiler::JSHeapBroker::isolate(), and v8::internal::compiler::MakeRef().
Referenced by v8::internal::compiler::AccessInfoFactory::LookupSpecialFieldAccessorInHolder(), v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewAccessor(), and v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewByteLengthAccessor().
DependOnArrayIteratorProtector()
bool v8::internal::compiler::CompilationDependencies::DependOnArrayIteratorProtector ()
Definition at line 1364 of file compilation-dependencies.cc.
                                                             {
  return DependOnProtector(MakeRef(
      broker_, broker_->isolate()->factory()->array_iterator_protector()));
}
References broker_, DependOnProtector(), v8::internal::Isolate::factory(), v8::internal::compiler::JSHeapBroker::isolate(), and v8::internal::compiler::MakeRef().
DependOnArraySpeciesProtector()
bool v8::internal::compiler::CompilationDependencies::DependOnArraySpeciesProtector ()
Definition at line 1369 of file compilation-dependencies.cc.
                                                            {
  return DependOnProtector(MakeRef(
      broker_, broker_->isolate()->factory()->array_species_protector()));
}
References broker_, DependOnProtector(), v8::internal::Isolate::factory(), v8::internal::compiler::JSHeapBroker::isolate(), and v8::internal::compiler::MakeRef().
DependOnConsistentJSFunctionView()
void v8::internal::compiler::CompilationDependencies::DependOnConsistentJSFunctionView (JSFunctionRef function)
Definition at line 1599 of file compilation-dependencies.cc.
                            {
  RecordDependency(zone_->New<ConsistentJSFunctionViewDependency>(function));
}
References v8::internal::Zone::New(), RecordDependency(), and zone_.
DependOnConstantInDictionaryPrototypeChain()
void v8::internal::compiler::CompilationDependencies::DependOnConstantInDictionaryPrototypeChain (MapRef receiver_map, NameRef property_name, ObjectRef constant, PropertyKind kind)
Definition at line 1230 of file compilation-dependencies.cc.
                       {
  RecordDependency(zone_->New<ConstantInDictionaryPrototypeChainDependency>(
      receiver_map, property_name, constant, kind));
}
References v8::internal::Zone::New(), RecordDependency(), and zone_.
Referenced by v8::internal::compiler::PropertyAccessBuilder::FoldLoadDictPrototypeConstant(), v8::internal::compiler::JSNativeContextSpecialization::InlinePropertyGetterCall(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyGetterCall(), and v8::internal::maglev::MaglevGraphBuilder::TryFoldLoadDictPrototypeConstant().
DependOnContextCell() [1/2]
bool v8::internal::compiler::CompilationDependencies::DependOnContextCell (ContextCellRef slot, ContextCell::State state)
Definition at line 1308 of file compilation-dependencies.cc.
                                                                          {
  DCHECK(v8_flags.script_context_cells);
  RecordDependency(zone_->New<ContextCellDependency>(slot, state));
  return true;
}
References v8::internal::DCHECK(), v8::internal::Zone::New(), RecordDependency(), v8::internal::v8_flags, and zone_.
DependOnContextCell() [2/2]
bool v8::internal::compiler::CompilationDependencies::DependOnContextCell (ContextRef script_context, size_t index, ContextCell::State state, JSHeapBroker * broker)
Definition at line 1294 of file compilation-dependencies.cc.
                                                                        {
  if (!script_context.object()->HasContextCells()) return false;
  auto value = script_context.get(broker, static_cast<int>(index));
  if (!value || !value->IsContextCell()) {
    return false;
  }
  auto slot = value->AsContextCell();
  RecordDependency(zone_->New<ContextCellDependency>(slot, state));
  return true;
}
References broker(), v8::internal::compiler::ContextRef::get(), v8::internal::index, v8::internal::Zone::New(), v8::internal::compiler::ContextRef::object(), RecordDependency(), v8::internal::value, and zone_.
Referenced by v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContext(), v8::internal::compiler::JSContextSpecialization::ReduceJSStoreContext(), v8::internal::maglev::MaglevGraphBuilder::TrySpecializeLoadContextSlot(), and v8::internal::maglev::MaglevGraphBuilder::TrySpecializeStoreContextSlot().
DependOnElementsKind()
void v8::internal::compiler::CompilationDependencies::DependOnElementsKind (AllocationSiteRef site)
Definition at line 1407 of file compilation-dependencies.cc.
                                                                         {
  ElementsKind kind =
      site.PointsToLiteral()
          ? site.boilerplate(broker_).value().map(broker_).elements_kind()
          : site.GetElementsKind();
  if (AllocationSite::ShouldTrack(kind)) {
    RecordDependency(zone_->New<ElementsKindDependency>(site, kind));
  }
}
References v8::internal::compiler::AllocationSiteRef::boilerplate(), broker_, v8::internal::compiler::AllocationSiteRef::GetElementsKind(), v8::internal::Zone::New(), v8::internal::compiler::AllocationSiteRef::PointsToLiteral(), RecordDependency(), v8::internal::AllocationSite::ShouldTrack(), and zone_.
Referenced by DependOnElementsKinds(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArray(), and v8::internal::compiler::JSCreateLowering::ReduceJSCreateEmptyLiteralArray().
DependOnElementsKinds()
void v8::internal::compiler::CompilationDependencies::DependOnElementsKinds (AllocationSiteRef site)
Definition at line 1589 of file compilation-dependencies.cc.
                                                                          {
  AllocationSiteRef current = site;
  while (true) {
    DependOnElementsKind(current);
    if (!current.nested_site(broker_).IsAllocationSite()) break;
    current = current.nested_site(broker_).AsAllocationSite();
  }
  CHECK_EQ(current.nested_site(broker_).AsSmi(), 0);
}
References broker_, CHECK_EQ, DependOnElementsKind(), and v8::internal::compiler::AllocationSiteRef::nested_site().
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateLiteralArrayOrObject().
DependOnEmptyContextExtension()
bool v8::internal::compiler::CompilationDependencies::DependOnEmptyContextExtension (ScopeInfoRef scope_info)
Definition at line 1315 of file compilation-dependencies.cc.
                             {
  if (!v8_flags.empty_context_extension_dep) return false;
  DCHECK(scope_info.SloppyEvalCanExtendVars());
  if (HeapLayout::InReadOnlySpace(*scope_info.object()) ||
      scope_info.object()->SomeContextHasExtension()) {
    // There are respective contexts with non-empty context extension, so
    // dynamic checks are required.
    return false;
  }
  RecordDependency(zone_->New<EmptyContextExtensionDependency>(scope_info));
  return true;
}
References v8::internal::DCHECK(), v8::internal::HeapLayout::InReadOnlySpace(), v8::internal::Zone::New(), v8::internal::compiler::ScopeInfoRef::object(), RecordDependency(), v8::internal::compiler::ScopeInfoRef::SloppyEvalCanExtendVars(), v8::internal::v8_flags, and zone_.
DependOnFieldConstness()
PropertyConstness v8::internal::compiler::CompilationDependencies::DependOnFieldConstness (MapRef map, MapRef owner, InternalIndex descriptor)
Definition at line 1245 of file compilation-dependencies.cc.
                                                        {
  PropertyConstness constness =
      map.GetPropertyDetails(broker_, descriptor).constness();
  if (constness == PropertyConstness::kMutable) return constness;
  // If the map can have fast elements transitions, then the field can be only
  // considered constant if the map does not transition.
  if (Map::CanHaveFastTransitionableElementsKind(map.instance_type())) {
    // If the map can already transition away, let us report the field as
    // mutable.
    if (!map.is_stable()) {
      return PropertyConstness::kMutable;
    }
    DependOnStableMap(map);
  }
  DCHECK_EQ(constness, PropertyConstness::kConst);
  RecordDependency(
      zone_->New<FieldConstnessDependency>(map, owner, descriptor));
  return PropertyConstness::kConst;
}
References broker_, v8::internal::Map::CanHaveFastTransitionableElementsKind(), v8::internal::PropertyDetails::constness(), DCHECK_EQ, DependOnStableMap(), v8::internal::compiler::MapRef::GetPropertyDetails(), v8::internal::compiler::MapRef::instance_type(), v8::internal::compiler::MapRef::is_stable(), v8::internal::kConst, v8::internal::kMutable, v8::internal::Zone::New(), RecordDependency(), and zone_.
DependOnGlobalProperty()
void v8::internal::compiler::CompilationDependencies::DependOnGlobalProperty (PropertyCellRef cell)
Definition at line 1288 of file compilation-dependencies.cc.
                                                                         {
  PropertyCellType type = cell.property_details().cell_type();
  bool read_only = cell.property_details().IsReadOnly();
  RecordDependency(zone_->New<GlobalPropertyDependency>(cell, type, read_only));
}
References v8::internal::PropertyDetails::cell_type(), v8::internal::PropertyDetails::IsReadOnly(), v8::internal::Zone::New(), v8::internal::compiler::PropertyCellRef::property_details(), RecordDependency(), v8::internal::tracing::type, and zone_.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceGlobalAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyCellLoad(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyCellStore().
DependOnInitialMap()
MapRef v8::internal::compiler::CompilationDependencies::DependOnInitialMap (JSFunctionRef function)
Definition at line 1210 of file compilation-dependencies.cc.
                                                                         {
  MapRef map = function.initial_map(broker_);
  RecordDependency(zone_->New<InitialMapDependency>(broker_, function, map));
  return map;
}
References broker_, v8::internal::Zone::New(), RecordDependency(), and zone_.
Referenced by DependOnInitialMapInstanceSizePrediction().
DependOnInitialMapInstanceSizePrediction()
SlackTrackingPrediction v8::internal::compiler::CompilationDependencies::DependOnInitialMapInstanceSizePrediction (JSFunctionRef function)
Definition at line 1617 of file compilation-dependencies.cc.
                            {
  MapRef initial_map = DependOnInitialMap(function);
  int instance_size = function.InitialMapInstanceSizeWithMinSlack(broker_);
  // Currently, we always install the prediction dependency. If this turns out
  // to be too expensive, we can only install the dependency if slack
  // tracking is active.
  RecordDependency(zone_->New<InitialMapInstanceSizePredictionDependency>(
      function, instance_size));
  CHECK_LE(instance_size, function.initial_map(broker_).instance_size());
  return SlackTrackingPrediction(initial_map, instance_size);
}
References broker_, CHECK_LE, DependOnInitialMap(), v8::internal::compiler::initial_map, v8::internal::Zone::New(), RecordDependency(), and zone_.
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreate(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArray(), and v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject().
DependOnMegaDOMProtector()
bool v8::internal::compiler::CompilationDependencies::DependOnMegaDOMProtector ()
Definition at line 1336 of file compilation-dependencies.cc.
                                                       {
  return DependOnProtector(
      MakeRef(broker_, broker_->isolate()->factory()->mega_dom_protector()));
}
References broker_, DependOnProtector(), v8::internal::Isolate::factory(), v8::internal::compiler::JSHeapBroker::isolate(), and v8::internal::compiler::MakeRef().
DependOnNoDateTimeConfigurationChangeProtector()
bool v8::internal::compiler::CompilationDependencies::DependOnNoDateTimeConfigurationChangeProtector ()
Definition at line 1379 of file compilation-dependencies.cc.
                                                                             {
  return DependOnProtector(
      MakeRef(broker_, broker_->isolate()
                           ->factory()
                           ->no_date_time_configuration_change_protector()));
}
References broker_, DependOnProtector(), v8::internal::Isolate::factory(), v8::internal::compiler::JSHeapBroker::isolate(), and v8::internal::compiler::MakeRef().
DependOnNoElementsProtector()
bool v8::internal::compiler::CompilationDependencies::DependOnNoElementsProtector ()
Definition at line 1374 of file compilation-dependencies.cc.
                                                          {
  return DependOnProtector(
      MakeRef(broker_, broker_->isolate()->factory()->no_elements_protector()));
}
References broker_, DependOnProtector(), v8::internal::Isolate::factory(), v8::internal::compiler::JSHeapBroker::isolate(), and v8::internal::compiler::MakeRef().
Referenced by v8::internal::maglev::MaglevGraphBuilder::CanTreatHoleAsUndefined(), v8::internal::compiler::JSNativeContextSpecialization::CanTreatHoleAsUndefined(), and v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::IteratingArrayBuiltinHelper::IteratingArrayBuiltinHelper().
DependOnNoProfilingProtector()
bool v8::internal::compiler::CompilationDependencies::DependOnNoProfilingProtector ()
Definition at line 1341 of file compilation-dependencies.cc.
                                                           {
  // A shortcut in case profiling was already enabled but the interrupt
  // request to invalidate NoProfilingProtector wasn't processed yet.
#ifdef V8_RUNTIME_CALL_STATS
  if (TracingFlags::is_runtime_stats_enabled()) return false;
#endif
  if (broker_->isolate()->is_profiling()) return false;
  return DependOnProtector(MakeRef(
      broker_, broker_->isolate()->factory()->no_profiling_protector()));
}
References broker_, DependOnProtector(), v8::internal::Isolate::factory(), v8::internal::Isolate::is_profiling(), v8::internal::compiler::JSHeapBroker::isolate(), and v8::internal::compiler::MakeRef().
Referenced by v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), and v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall().
DependOnNoSlackTrackingChange()
void v8::internal::compiler::CompilationDependencies::DependOnNoSlackTrackingChange (MapRef map)
Definition at line 1604 of file compilation-dependencies.cc.
                                                                      {
  if (map.construction_counter() == 0) return;
  RecordDependency(zone_->New<NoSlackTrackingChangeDependency>(map));
}
References v8::internal::compiler::MapRef::construction_counter(), v8::internal::Zone::New(), RecordDependency(), and zone_.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyStore(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildStoreField().
DependOnNoUndetectableObjectsProtector()
bool v8::internal::compiler::CompilationDependencies::DependOnNoUndetectableObjectsProtector ()
Definition at line 1352 of file compilation-dependencies.cc.
                                                                     {
  return DependOnProtector(MakeRef(
      broker_,
      broker_->isolate()->factory()->no_undetectable_objects_protector()));
}
References broker_, DependOnProtector(), v8::internal::Isolate::factory(), v8::internal::compiler::JSHeapBroker::isolate(), and v8::internal::compiler::MakeRef().
Referenced by v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::DependOnNoUndetectableObjectsProtector().
DependOnObjectSlotValue()
void v8::internal::compiler::CompilationDependencies::DependOnObjectSlotValue (HeapObjectRef object, int offset, ObjectRef value)
Definition at line 1417 of file compilation-dependencies.cc.
                                                                       {
  RecordDependency(
      zone_->New<ObjectSlotValueDependency>(object, offset, value));
}
References v8::internal::Zone::New(), RecordDependency(), v8::internal::value, and zone_.
Referenced by v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral(), and v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteralElements().
DependOnOwnConstantDataProperty()
void v8::internal::compiler::CompilationDependencies::DependOnOwnConstantDataProperty (JSObjectRef holder, MapRef map, FieldIndex index, ObjectRef value)
Definition at line 1431 of file compilation-dependencies.cc.
                                                                       {
  RecordDependency(zone_->New<OwnConstantDataPropertyDependency>(
      broker_, holder, map, index, value));
}
References broker_, v8::internal::index, v8::internal::Zone::New(), RecordDependency(), v8::internal::value, and zone_.
Referenced by v8::internal::compiler::JSObjectRef::GetOwnFastConstantDataProperty().
DependOnOwnConstantDictionaryProperty()
void v8::internal::compiler::CompilationDependencies::DependOnOwnConstantDictionaryProperty (JSObjectRef holder, InternalIndex index, ObjectRef value)
Definition at line 1443 of file compilation-dependencies.cc.
                                                              {
  RecordDependency(zone_->New<OwnConstantDictionaryPropertyDependency>(
      broker_, holder, index, value));
}
References broker_, v8::internal::index, v8::internal::Zone::New(), RecordDependency(), v8::internal::value, and zone_.
Referenced by v8::internal::compiler::JSObjectRef::GetOwnDictionaryProperty().
DependOnOwnConstantDoubleProperty()
void v8::internal::compiler::CompilationDependencies::DependOnOwnConstantDoubleProperty (JSObjectRef holder, MapRef map, FieldIndex index, Float64 value)
Definition at line 1437 of file compilation-dependencies.cc.
                                                                     {
  RecordDependency(zone_->New<OwnConstantDoublePropertyDependency>(
      broker_, holder, map, index, value));
}
References broker_, v8::internal::index, v8::internal::Zone::New(), RecordDependency(), v8::internal::value, and zone_.
Referenced by v8::internal::compiler::JSObjectRef::GetOwnFastConstantDoubleProperty().
DependOnOwnConstantElement()
void v8::internal::compiler::CompilationDependencies::DependOnOwnConstantElement (JSObjectRef holder, uint32_t index, ObjectRef element)
Definition at line 1424 of file compilation-dependencies.cc.
                                                                            {
  RecordDependency(
      zone_->New<OwnConstantElementDependency>(holder, index, element));
}
References v8::internal::index, v8::internal::Zone::New(), RecordDependency(), and zone_.
DependOnPretenureMode()
AllocationType v8::internal::compiler::CompilationDependencies::DependOnPretenureMode (AllocationSiteRef site)
Definition at line 1237 of file compilation-dependencies.cc.
                            {
  if (!v8_flags.allocation_site_pretenuring) return AllocationType::kYoung;
  AllocationType allocation = site.GetAllocationType();
  RecordDependency(zone_->New<PretenureModeDependency>(site, allocation));
  return allocation;
}
References v8::internal::compiler::AllocationSiteRef::GetAllocationType(), v8::internal::kYoung, v8::internal::Zone::New(), RecordDependency(), v8::internal::v8_flags, and zone_.
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateArray(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateEmptyLiteralArray(), and v8::internal::compiler::JSCreateLowering::ReduceJSCreateLiteralArrayOrObject().
DependOnPromiseHookProtector()
bool v8::internal::compiler::CompilationDependencies::DependOnPromiseHookProtector ()
Definition at line 1386 of file compilation-dependencies.cc.
                                                           {
  return DependOnProtector(MakeRef(
      broker_, broker_->isolate()->factory()->promise_hook_protector()));
}
References broker_, DependOnProtector(), v8::internal::Isolate::factory(), v8::internal::compiler::JSHeapBroker::isolate(), and v8::internal::compiler::MakeRef().
DependOnPromiseSpeciesProtector()
bool v8::internal::compiler::CompilationDependencies::DependOnPromiseSpeciesProtector ()
Definition at line 1391 of file compilation-dependencies.cc.
                                                              {
  return DependOnProtector(MakeRef(
      broker_, broker_->isolate()->factory()->promise_species_protector()));
}
References broker_, DependOnProtector(), v8::internal::Isolate::factory(), v8::internal::compiler::JSHeapBroker::isolate(), and v8::internal::compiler::MakeRef().
DependOnPromiseThenProtector()
bool v8::internal::compiler::CompilationDependencies::DependOnPromiseThenProtector ()
Definition at line 1396 of file compilation-dependencies.cc.
                                                           {
  return DependOnProtector(MakeRef(
      broker_, broker_->isolate()->factory()->promise_then_protector()));
}
References broker_, DependOnProtector(), v8::internal::Isolate::factory(), v8::internal::compiler::JSHeapBroker::isolate(), and v8::internal::compiler::MakeRef().
DependOnProtector()
bool v8::internal::compiler::CompilationDependencies::DependOnProtector (PropertyCellRef cell)
Definition at line 1329 of file compilation-dependencies.cc.
                                                                    {
  cell.CacheAsProtector(broker_);
  if (cell.value(broker_).AsSmi() != Protectors::kProtectorValid) return false;
  RecordDependency(zone_->New<ProtectorDependency>(cell));
  return true;
}
References broker_, v8::internal::compiler::PropertyCellRef::CacheAsProtector(), v8::internal::Protectors::kProtectorValid, v8::internal::Zone::New(), RecordDependency(), v8::internal::compiler::PropertyCellRef::value(), and zone_.
Referenced by DependOnArrayBufferDetachingProtector(), DependOnArrayIteratorProtector(), DependOnArraySpeciesProtector(), DependOnMegaDOMProtector(), DependOnNoDateTimeConfigurationChangeProtector(), DependOnNoElementsProtector(), DependOnNoProfilingProtector(), DependOnNoUndetectableObjectsProtector(), DependOnPromiseHookProtector(), DependOnPromiseSpeciesProtector(), DependOnPromiseThenProtector(), DependOnStringWrapperToPrimitiveProtector(), and v8::internal::compiler::JSTypedLowering::ReduceJSAdd().
DependOnPrototypeProperty()
HeapObjectRef v8::internal::compiler::CompilationDependencies::DependOnPrototypeProperty (JSFunctionRef function)
Definition at line 1216 of file compilation-dependencies.cc.
                            {
  HeapObjectRef prototype = function.instance_prototype(broker_);
  RecordDependency(
      zone_->New<PrototypePropertyDependency>(broker_, function, prototype));
  return prototype;
}
References broker_, v8::internal::Zone::New(), v8::internal::prototype, RecordDependency(), and zone_.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadNamed(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSOrdinaryHasInstance(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildNamedAccess().
DependOnStableMap()
void v8::internal::compiler::CompilationDependencies::DependOnStableMap (MapRef map)
Definition at line 1224 of file compilation-dependencies.cc.
                                                          {
  if (map.CanTransition()) {
    RecordDependency(zone_->New<StableMapDependency>(map));
  }
}
References v8::internal::compiler::MapRef::CanTransition(), v8::internal::Zone::New(), RecordDependency(), and zone_.
Referenced by v8::internal::compiler::PropertyAccessBuilder::BuildCheckMaps(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckMaps(), v8::internal::compiler::PropertyAccessBuilder::BuildLoadDataField(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadField(), v8::internal::maglev::MaglevGraphBuilder::BuildStoreMap(), v8::internal::maglev::MaglevGraphBuilder::BuildTransitionElementsKindAndCompareMaps(), v8::internal::maglev::MaglevGraphBuilder::BuildTransitionElementsKindOrCheckMap(), v8::internal::compiler::anonymous_namespace{typed-optimization.cc}::CheckMapsHelper(), DependOnFieldConstness(), DependOnStablePrototypeChain(), FieldConstnessDependencyOffTheRecord(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::MapLoadCanBeConstantFolded(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccess(), v8::internal::compiler::JSNativeContextSpecialization::ReduceGlobalAccess(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetSuperConstructor(), v8::internal::compiler::TypedOptimization::ReduceLoadField(), v8::internal::compiler::MapInference::RelyOnMapsHelper(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyCellStore().
DependOnStablePrototypeChain()
void v8::internal::compiler::CompilationDependencies::DependOnStablePrototypeChain (MapRef receiver_maps, WhereToStart start, OptionalJSObjectRef last_prototype = OptionalJSObjectRef())
Definition at line 1562 of file compilation-dependencies.cc.
                                        {
  if (receiver_map.IsPrimitiveMap()) {
    // Perform the implicit ToObject for primitives here.
    // Implemented according to ES6 section 7.3.2 GetV (V, P).
    // Note: Keep sync'd with AccessInfoFactory::ComputePropertyAccessInfo.
    OptionalJSFunctionRef constructor =
        broker_->target_native_context().GetConstructorFunction(broker_,
                                                                receiver_map);
    receiver_map = constructor.value().initial_map(broker_);
  }
  if (start == kStartAtReceiver) DependOnStableMap(receiver_map);
  MapRef map = receiver_map;
  while (true) {
    HeapObjectRef proto = map.prototype(broker_);
    if (!proto.IsJSObject()) {
      CHECK_EQ(proto.map(broker_).oddball_type(broker_), OddballType::kNull);
      break;
    }
    map = proto.map(broker_);
    DependOnStableMap(map);
    if (last_prototype.has_value() && proto.equals(*last_prototype)) break;
  }
}
References broker_, CHECK_EQ, DependOnStableMap(), v8::internal::compiler::NativeContextRef::GetConstructorFunction(), v8::internal::compiler::MapRef::IsPrimitiveMap(), v8::internal::compiler::kNull, v8::internal::kStartAtReceiver, v8::internal::compiler::HeapObjectRef::map(), v8::internal::compiler::MapRef::oddball_type(), v8::internal::compiler::MapRef::prototype(), and v8::internal::compiler::JSHeapBroker::target_native_context().
Referenced by DependOnStablePrototypeChains(), v8::internal::compiler::AccessInfoFactory::LookupSpecialFieldAccessorInHolder(), and v8::internal::compiler::JSNativeContextSpecialization::ReduceJSFindNonDefaultConstructorOrConstruct().
DependOnStablePrototypeChains()
void v8::internal::compiler::CompilationDependencies::DependOnStablePrototypeChains (ZoneVector< MapRef > const & receiver_maps, WhereToStart start, OptionalJSObjectRef last_prototype = OptionalJSObjectRef())
Definition at line 1554 of file compilation-dependencies.cc.
                                        {
  for (MapRef receiver_map : receiver_maps) {
    DependOnStablePrototypeChain(receiver_map, start, last_prototype);
  }
}
References DependOnStablePrototypeChain().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyLoad(), v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyStore(), v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyTest(), v8::internal::compiler::JSNativeContextSpecialization::InferHasInPrototypeChain(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSResolvePromise(), v8::internal::compiler::JSCallReducer::ReduceRegExpPrototypeTest(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyLoad(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyStore().
DependOnStringWrapperToPrimitiveProtector()
bool v8::internal::compiler::CompilationDependencies::DependOnStringWrapperToPrimitiveProtector ()
Definition at line 1401 of file compilation-dependencies.cc.
                                                                        {
  return DependOnProtector(MakeRef(
      broker_,
      broker_->isolate()->factory()->string_wrapper_to_primitive_protector()));
}
References broker_, DependOnProtector(), v8::internal::Isolate::factory(), v8::internal::compiler::JSHeapBroker::isolate(), and v8::internal::compiler::MakeRef().
FieldConstnessDependencyOffTheRecord()
CompilationDependency const * v8::internal::compiler::CompilationDependencies::FieldConstnessDependencyOffTheRecord (MapRef map, MapRef owner, InternalIndex descriptor)
Definition at line 1269 of file compilation-dependencies.cc.
                                                        {
  DCHECK_EQ(map.GetPropertyDetails(broker_, descriptor).constness(),
            PropertyConstness::kConst);
  // If the map can have fast elements transitions, then the field can be only
  // considered constant if the map does not transition.
  if (Map::CanHaveFastTransitionableElementsKind(map.instance_type())) {
    // If the map can already transition away, let us report the field as
    // mutable.
    if (!map.is_stable()) {
      return {};
    }
    DependOnStableMap(map);
  }
  return zone_->New<FieldConstnessDependency>(map, owner, descriptor);
}
References broker_, v8::internal::Map::CanHaveFastTransitionableElementsKind(), v8::internal::PropertyDetails::constness(), DCHECK_EQ, DependOnStableMap(), v8::internal::compiler::MapRef::GetPropertyDetails(), v8::internal::compiler::MapRef::instance_type(), v8::internal::compiler::MapRef::is_stable(), v8::internal::kConst, v8::internal::Zone::New(), and zone_.
Referenced by v8::internal::compiler::AccessInfoFactory::ComputeDataFieldAccessInfo(), and v8::internal::compiler::AccessInfoFactory::LookupTransition().
FieldRepresentationDependencyOffTheRecord()
CompilationDependency const * v8::internal::compiler::CompilationDependencies::FieldRepresentationDependencyOffTheRecord (MapRef map, MapRef owner, InternalIndex descriptor, Representation representation) const
Definition at line 1642 of file compilation-dependencies.cc.
                                         {
  return zone_->New<FieldRepresentationDependency>(map, owner, descriptor,
                                                   representation);
}
References v8::internal::Zone::New(), and zone_.
FieldTypeDependencyOffTheRecord()
CompilationDependency const * v8::internal::compiler::CompilationDependencies::FieldTypeDependencyOffTheRecord (MapRef map, MapRef owner, InternalIndex descriptor, ObjectRef type) const
Definition at line 1650 of file compilation-dependencies.cc.
                                                                              {
  return zone_->New<FieldTypeDependency>(map, owner, descriptor, type);
}
References v8::internal::Zone::New(), v8::internal::tracing::type, and zone_.
PrepareInstall()
bool v8::internal::compiler::CompilationDependencies::PrepareInstall () [private]
Definition at line 1508 of file compilation-dependencies.cc.
                                             {
  if (V8_UNLIKELY(v8_flags.predictable)) {
    return PrepareInstallPredictable();
  }
  for (auto dep : dependencies_) {
    if (!dep->IsValid(broker_)) {
      if (v8_flags.trace_compilation_dependencies) {
        TraceInvalidCompilationDependency(broker_, dep);
      }
      dependencies_.clear();
      return false;
    }
    dep->PrepareInstall(broker_);
  }
  return true;
}
References broker_, dependencies_, PrepareInstallPredictable(), v8::internal::compiler::TraceInvalidCompilationDependency(), v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by Commit().
PrepareInstallPredictable()
bool v8::internal::compiler::CompilationDependencies::PrepareInstallPredictable () [private]
Definition at line 1526 of file compilation-dependencies.cc.
                                                        {
  CHECK(v8_flags.predictable);
  std::vector<const CompilationDependency*> deps(dependencies_.begin(),
                                                 dependencies_.end());
  std::sort(deps.begin(), deps.end());
  for (auto dep : deps) {
    if (!dep->IsValid(broker_)) {
      if (v8_flags.trace_compilation_dependencies) {
        TraceInvalidCompilationDependency(broker_, dep);
      }
      dependencies_.clear();
      return false;
    }
    dep->PrepareInstall(broker_);
  }
  return true;
}
References broker_, CHECK, dependencies_, v8::base::sort(), v8::internal::compiler::TraceInvalidCompilationDependency(), and v8::internal::v8_flags.
Referenced by PrepareInstall().
RecordDependency()
void v8::internal::compiler::CompilationDependencies::RecordDependency (CompilationDependency const * dependency)
Definition at line 1205 of file compilation-dependencies.cc.
                                             {
  if (dependency != nullptr) dependencies_.insert(dependency);
}
References dependencies_.
Referenced by DependOnConsistentJSFunctionView(), DependOnConstantInDictionaryPrototypeChain(), DependOnContextCell(), DependOnElementsKind(), DependOnEmptyContextExtension(), DependOnFieldConstness(), DependOnGlobalProperty(), DependOnInitialMap(), DependOnInitialMapInstanceSizePrediction(), DependOnNoSlackTrackingChange(), DependOnObjectSlotValue(), DependOnOwnConstantDataProperty(), DependOnOwnConstantDictionaryProperty(), DependOnOwnConstantDoubleProperty(), DependOnOwnConstantElement(), DependOnPretenureMode(), DependOnProtector(), DependOnPrototypeProperty(), DependOnStableMap(), and v8::internal::compiler::PropertyAccessInfo::RecordDependencies().
TransitionDependencyOffTheRecord()
CompilationDependency const * v8::internal::compiler::CompilationDependencies::TransitionDependencyOffTheRecord (MapRef target_map) const
Definition at line 1631 of file compilation-dependencies.cc.
                             {
  if (target_map.CanBeDeprecated()) {
    return zone_->New<TransitionDependency>(target_map);
  } else {
    DCHECK(!target_map.is_deprecated());
    return nullptr;
  }
}
References v8::internal::compiler::MapRef::CanBeDeprecated(), v8::internal::DCHECK(), v8::internal::compiler::MapRef::is_deprecated(), v8::internal::Zone::New(), and zone_.
Member Data Documentation
broker_
JSHeapBroker* const v8::internal::compiler::CompilationDependencies::broker_ [private]
Definition at line 210 of file compilation-dependencies.h.
Referenced by Commit(), DependOnArrayBufferDetachingProtector(), DependOnArrayIteratorProtector(), DependOnArraySpeciesProtector(), DependOnElementsKind(), DependOnElementsKinds(), DependOnFieldConstness(), DependOnInitialMap(), DependOnInitialMapInstanceSizePrediction(), DependOnMegaDOMProtector(), DependOnNoDateTimeConfigurationChangeProtector(), DependOnNoElementsProtector(), DependOnNoProfilingProtector(), DependOnNoUndetectableObjectsProtector(), DependOnOwnConstantDataProperty(), DependOnOwnConstantDictionaryProperty(), DependOnOwnConstantDoubleProperty(), DependOnPromiseHookProtector(), DependOnPromiseSpeciesProtector(), DependOnPromiseThenProtector(), DependOnProtector(), DependOnPrototypeProperty(), DependOnStablePrototypeChain(), DependOnStringWrapperToPrimitiveProtector(), FieldConstnessDependencyOffTheRecord(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDataPropertyDependency::IsValid(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDoublePropertyDependency::IsValid(), PrepareInstall(), and PrepareInstallPredictable().
dependencies_
CompilationDependencySet v8::internal::compiler::CompilationDependencies::dependencies_ [private]
Definition at line 211 of file compilation-dependencies.h.
Referenced by Commit(), PrepareInstall(), PrepareInstallPredictable(), and RecordDependency().
zone_
Zone* const v8::internal::compiler::CompilationDependencies::zone_ [private]
Definition at line 209 of file compilation-dependencies.h.
Referenced by Commit(), DependOnConsistentJSFunctionView(), DependOnConstantInDictionaryPrototypeChain(), DependOnContextCell(), DependOnElementsKind(), DependOnEmptyContextExtension(), DependOnFieldConstness(), DependOnGlobalProperty(), DependOnInitialMap(), DependOnInitialMapInstanceSizePrediction(), DependOnNoSlackTrackingChange(), DependOnObjectSlotValue(), DependOnOwnConstantDataProperty(), DependOnOwnConstantDictionaryProperty(), DependOnOwnConstantDoubleProperty(), DependOnOwnConstantElement(), DependOnPretenureMode(), DependOnProtector(), DependOnPrototypeProperty(), DependOnStableMap(), FieldConstnessDependencyOffTheRecord(), FieldRepresentationDependencyOffTheRecord(), FieldTypeDependencyOffTheRecord(), and TransitionDependencyOffTheRecord().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/compilation-dependencies.h
/mnt/V8SourceCode/src/compiler/compilation-dependencies.cc