v8::internal::compiler::IfValueParameters Class Reference
#include <common-operator.h>
Public Member Functions
IfValueParameters (int32_t value, int32_t comparison_order, BranchHint hint=BranchHint::kNone)
int32_t value () const
int32_t comparison_order () const
BranchHint hint () const
Private Attributes
int32_t value_
int32_t comparison_order_
BranchHint hint_
Detailed Description
Definition at line 449 of file common-operator.h.
Constructor & Destructor Documentation
IfValueParameters()
v8::internal::compiler::IfValueParameters::IfValueParameters (int32_t value, int32_t comparison_order, BranchHint hint = BranchHint::kNone) [inline]
Definition at line 451 of file common-operator.h.
      : value_(value), comparison_order_(comparison_order), hint_(hint) {}
Member Function Documentation
comparison_order()
int32_t v8::internal::compiler::IfValueParameters::comparison_order () const [inline]
Definition at line 456 of file common-operator.h.
{ return comparison_order_; }
References comparison_order_.
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::RawMachineAssembler::MarkControlDeferred(), v8::internal::compiler::operator<<(), and v8::internal::compiler::operator==().
hint()
BranchHint v8::internal::compiler::IfValueParameters::hint () const [inline]
Definition at line 457 of file common-operator.h.
{ return hint_; }
References hint_.
Referenced by v8::internal::compiler::BranchHintOf(), v8::internal::compiler::hash_value(), v8::internal::compiler::RawMachineAssembler::MarkControlDeferred(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
value()
int32_t v8::internal::compiler::IfValueParameters::value () const [inline]
Definition at line 455 of file common-operator.h.
{ return value_; }
References value_.
Referenced by v8::internal::compiler::Verifier::Visitor::CheckSwitch(), v8::internal::compiler::hash_value(), v8::internal::compiler::RawMachineAssembler::MarkControlDeferred(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), and v8::internal::compiler::CommonOperatorReducer::ReduceSwitch().
Member Data Documentation
comparison_order_
int32_t v8::internal::compiler::IfValueParameters::comparison_order_ [private]
Definition at line 461 of file common-operator.h.
Referenced by comparison_order().
hint_
BranchHint v8::internal::compiler::IfValueParameters::hint_ [private]
Definition at line 462 of file common-operator.h.
Referenced by hint().
value_
int32_t v8::internal::compiler::IfValueParameters::value_ [private]
Definition at line 460 of file common-operator.h.
Referenced by value().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/common-operator.h