v8::internal::compiler::turboshaft::CopyingPhase< Reducers > Class Template Reference
#include <copying-phase.h>
Static Public Member Functions
static void Run (PipelineData *data, Zone *phase_zone)
Detailed Description
template<template< typename > typename... Reducers>
class v8::internal::compiler::turboshaft::CopyingPhase< Reducers >
Definition at line 1065 of file copying-phase.h.
Member Function Documentation
Run()
template<template< typename > typename... Reducers>
static void v8::internal::compiler::turboshaft::CopyingPhase< Reducers >::Run (PipelineData * data, Zone * phase_zone) [inline], [static]
Definition at line 1067 of file copying-phase.h.
                                                        {
    Graph& input_graph = data->graph();
    CopyingPhaseImpl<Reducers...>::Run(
        data, input_graph, phase_zone,
        data->info()->turboshaft_trace_reduction());
  }
References v8::internal::compiler::turboshaft::PipelineData::graph(), v8::internal::compiler::turboshaft::PipelineData::info(), and v8::internal::compiler::turboshaft::CopyingPhaseImpl< Reducers >::Run().
Referenced by v8::internal::compiler::turboshaft::Pipeline::PrepareForInstructionSelection(), v8::internal::compiler::turboshaft::CsaEarlyMachineOptimizationPhase::Run(), v8::internal::compiler::turboshaft::DebugFeatureLoweringPhase::Run(), v8::internal::compiler::turboshaft::Int64LoweringPhase::Run(), v8::internal::compiler::turboshaft::WasmGCOptimizePhase::Run(), v8::internal::compiler::turboshaft::WasmInJSInliningPhase::Run(), v8::internal::compiler::turboshaft::WasmLoweringPhase::Run(), v8::internal::compiler::turboshaft::WasmRevecPhase::Run(), and v8::internal::compiler::turboshaft::WasmSimdPhase::Run().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/copying-phase.h