v8::internal::anonymous_namespace{read-only-serializer.cc}::EncodeRelocationsVisitor Class Reference
Public Member Functions
EncodeRelocationsVisitor (Isolate *isolate, ReadOnlySegmentForSerialization *segment)
void VisitPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) override
void VisitPointers (Tagged< HeapObject > host, MaybeObjectSlot start, MaybeObjectSlot end) override
void VisitMapPointer (Tagged< HeapObject > host) override
void VisitInstructionStreamPointer (Tagged< Code > host, InstructionStreamSlot slot) override
void VisitCodeTarget (Tagged< InstructionStream >, RelocInfo *) override
void VisitEmbeddedPointer (Tagged< InstructionStream >, RelocInfo *) override
void VisitExternalReference (Tagged< InstructionStream >, RelocInfo *) override
void VisitInternalReference (Tagged< InstructionStream >, RelocInfo *) override
void VisitOffHeapTarget (Tagged< InstructionStream >, RelocInfo *) override
void VisitExternalPointer (Tagged< HeapObject >, ExternalPointerSlot slot) override
Private Member Functions
void ProcessSlot (MaybeObjectSlot slot)
template<class SlotT >
int SegmentOffsetOf (SlotT slot) const
Static Private Member Functions
static constexpr int AsSlot (int byte_offset)
Private Attributes
Isolate *const isolate_
ReadOnlySegmentForSerialization *const segment_
Detailed Description
Definition at line 205 of file read-only-serializer.cc.
Constructor & Destructor Documentation
EncodeRelocationsVisitor()
v8::internal::anonymous_namespace{read-only-serializer.cc}::EncodeRelocationsVisitor::EncodeRelocationsVisitor (Isolate * isolate, ReadOnlySegmentForSerialization * segment) [inline]
Definition at line 207 of file read-only-serializer.cc.
      : isolate_(isolate), segment_(segment) {
    DCHECK(!V8_STATIC_ROOTS_BOOL);
  }
References v8::internal::DCHECK(), and V8_STATIC_ROOTS_BOOL.
Member Function Documentation
AsSlot()
static constexpr int v8::internal::anonymous_namespace{read-only-serializer.cc}::EncodeRelocationsVisitor::AsSlot (int byte_offset) [inline], [static], [constexpr], [private]
Definition at line 300 of file read-only-serializer.cc.
                                               {
    return byte_offset / kTaggedSize;
  }
References v8::internal::kTaggedSize.
ProcessSlot()
void v8::internal::anonymous_namespace{read-only-serializer.cc}::EncodeRelocationsVisitor::ProcessSlot (MaybeObjectSlot slot) [inline], [private]
Definition at line 275 of file read-only-serializer.cc.
                                         {
    Tagged<MaybeObject> o = *slot;
    if (!o.IsStrongOrWeak()) return; // Smis don't need relocation.
    DCHECK(o.IsStrong());
    int slot_offset = SegmentOffsetOf(slot);
    DCHECK(IsAligned(slot_offset, kTaggedSize));
    // Encode:
    ro::EncodedTagged encoded = Encode(isolate_, o.GetHeapObject());
    memcpy(segment_->contents.get() + slot_offset, &encoded,
           ro::EncodedTagged::kSize);
    // Record:
    segment_->tagged_slots.set(AsSlot(slot_offset));
  }
References v8::internal::DCHECK(), v8::internal::anonymous_namespace{read-only-serializer.cc}::Encode(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObject(), IsAligned(), v8::internal::TaggedImpl< kRefType, StorageType >::IsStrong(), v8::internal::TaggedImpl< kRefType, StorageType >::IsStrongOrWeak(), v8::internal::ro::EncodedTagged::kSize, and v8::internal::kTaggedSize.
SegmentOffsetOf()
template<class SlotT >
int v8::internal::anonymous_namespace{read-only-serializer.cc}::EncodeRelocationsVisitor::SegmentOffsetOf (SlotT slot) const [inline], [private]
Definition at line 293 of file read-only-serializer.cc.
                                        {
    Address addr = slot.address();
    DCHECK_GE(addr, segment_->segment_start);
    DCHECK_LT(addr, segment_->segment_start + segment_->segment_size);
    return static_cast<int>(addr - segment_->segment_start);
  }
References DCHECK_GE, and DCHECK_LT.
VisitCodeTarget()
void v8::internal::anonymous_namespace{read-only-serializer.cc}::EncodeRelocationsVisitor::VisitCodeTarget (Tagged< InstructionStream > , RelocInfo *) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 235 of file read-only-serializer.cc.
                                                                       {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
VisitEmbeddedPointer()
void v8::internal::anonymous_namespace{read-only-serializer.cc}::EncodeRelocationsVisitor::VisitEmbeddedPointer (Tagged< InstructionStream > , RelocInfo *) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 238 of file read-only-serializer.cc.
                                                                            {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
VisitExternalPointer()
void v8::internal::anonymous_namespace{read-only-serializer.cc}::EncodeRelocationsVisitor::VisitExternalPointer (Tagged< HeapObject > , ExternalPointerSlot slot) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 250 of file read-only-serializer.cc.
                                                               {
    // This slot was encoded in a previous pass, see EncodeExternalPointerSlot.
#ifdef DEBUG
    ExternalPointerSlot slot_in_segment{
        reinterpret_cast<Address>(segment_->contents.get() +
                                  SegmentOffsetOf(slot)),
        slot.exact_tag()};
    // Constructing no_gc here is not the intended use pattern (instead we
    // should pass it along the entire callchain); but there's little point of
    // doing that here - all of the code in this file relies on GC being
    // disabled, and that's guarded at entry points.
    DisallowGarbageCollection no_gc;
    auto encoded = ro::EncodedExternalReference::FromUint32(
        slot_in_segment.GetContentAsIndexAfterDeserialization(no_gc));
    if (encoded.is_api_reference) {
      // Can't validate these since we don't know how many entries
      // api_external_references contains.
    } else {
      CHECK_LT(encoded.index, ExternalReferenceTable::kSize);
    }
#endif // DEBUG
  }
References CHECK_LT, v8::internal::ExternalPointerSlot::exact_tag(), v8::internal::ro::EncodedExternalReference::FromUint32(), v8::internal::ExternalReferenceTable::kSize, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
VisitExternalReference()
void v8::internal::anonymous_namespace{read-only-serializer.cc}::EncodeRelocationsVisitor::VisitExternalReference (Tagged< InstructionStream > , RelocInfo *) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 241 of file read-only-serializer.cc.
                                                                              {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
VisitInstructionStreamPointer()
void v8::internal::anonymous_namespace{read-only-serializer.cc}::EncodeRelocationsVisitor::VisitInstructionStreamPointer (Tagged< Code > host, InstructionStreamSlot slot) [inline], [override], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 230 of file read-only-serializer.cc.
                                                                          {
    // RO space contains only builtin Code objects.
    DCHECK(!host->has_instruction_stream());
  }
References v8::internal::DCHECK().
VisitInternalReference()
void v8::internal::anonymous_namespace{read-only-serializer.cc}::EncodeRelocationsVisitor::VisitInternalReference (Tagged< InstructionStream > , RelocInfo *) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 244 of file read-only-serializer.cc.
                                                                              {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
VisitMapPointer()
void v8::internal::anonymous_namespace{read-only-serializer.cc}::EncodeRelocationsVisitor::VisitMapPointer (Tagged< HeapObject > host) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 225 of file read-only-serializer.cc.
                                                         {
    ProcessSlot(host->RawMaybeWeakField(HeapObject::kMapOffset));
  }
References v8::internal::HeapObject::kMapOffset.
VisitOffHeapTarget()
void v8::internal::anonymous_namespace{read-only-serializer.cc}::EncodeRelocationsVisitor::VisitOffHeapTarget (Tagged< InstructionStream > , RelocInfo *) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 247 of file read-only-serializer.cc.
                                                                          {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
VisitPointers() [1/2]
void v8::internal::anonymous_namespace{read-only-serializer.cc}::EncodeRelocationsVisitor::VisitPointers (Tagged< HeapObject > host, MaybeObjectSlot start, MaybeObjectSlot end) [inline], [override], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 218 of file read-only-serializer.cc.
                                                   {
    for (MaybeObjectSlot slot = start; slot < end; slot++) {
      ProcessSlot(slot);
    }
  }
References v8::internal::compiler::end().
VisitPointers() [2/2]
void v8::internal::anonymous_namespace{read-only-serializer.cc}::EncodeRelocationsVisitor::VisitPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) [inline], [override], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 213 of file read-only-serializer.cc.
                                              {
    VisitPointers(host, MaybeObjectSlot(start), MaybeObjectSlot(end));
  }
References v8::internal::compiler::end().
Member Data Documentation
isolate_
Isolate* const v8::internal::anonymous_namespace{read-only-serializer.cc}::EncodeRelocationsVisitor::isolate_ [private]
Definition at line 304 of file read-only-serializer.cc.
segment_
ReadOnlySegmentForSerialization* const v8::internal::anonymous_namespace{read-only-serializer.cc}::EncodeRelocationsVisitor::segment_ [private]
Definition at line 305 of file read-only-serializer.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/snapshot/read-only-serializer.cc