v8::internal::compiler::ValueNumberingReducer Class Reference
#include <value-numbering-reducer.h>
Public Member Functions
ValueNumberingReducer (Zone *temp_zone, Zone *graph_zone)
~ValueNumberingReducer () override
const char * reducer_name () const override
Reduction Reduce (Node *node) override
Private Types
enum { kInitialCapacity = 256u
 }
Private Member Functions
Reduction ReplaceIfTypesMatch (Node *node, Node *replacement)
void Grow ()
Zone * temp_zone () const
Zone * graph_zone () const
Private Attributes
Node ** entries_
size_t capacity_
size_t size_
Zone * temp_zone_
Zone * graph_zone_
Detailed Description
Definition at line 16 of file value-numbering-reducer.h.
Member Enumeration Documentation
anonymous enum
anonymous enum [private]
Enumerator
kInitialCapacity
Definition at line 27 of file value-numbering-reducer.h.
{ kInitialCapacity = 256u };
Constructor & Destructor Documentation
ValueNumberingReducer()
v8::internal::compiler::ValueNumberingReducer::ValueNumberingReducer (Zone * temp_zone, Zone * graph_zone) [explicit]
Definition at line 16 of file value-numbering-reducer.cc.
    : entries_(nullptr),
      capacity_(0),
      size_(0),
      temp_zone_(temp_zone),
      graph_zone_(graph_zone) {}
 ValueNumberingReducer()
v8::internal::compiler::ValueNumberingReducer::~ValueNumberingReducer () [override], [default]
Member Function Documentation
graph_zone()
Zone* v8::internal::compiler::ValueNumberingReducer::graph_zone () const [inline], [private]
Definition at line 32 of file value-numbering-reducer.h.
{ return graph_zone_; }
Grow()
void v8::internal::compiler::ValueNumberingReducer::Grow () [private]
Definition at line 150 of file value-numbering-reducer.cc.
                                 {
  // Allocate a new block of entries double the previous capacity.
  Node** const old_entries = entries_;
  size_t const old_capacity = capacity_;
  capacity_ *= 2;
  entries_ = temp_zone()->AllocateArray<Node*>(capacity_);
  memset(entries_, 0, sizeof(*entries_) * capacity_);
  size_ = 0;
  size_t const mask = capacity_ - 1;
  // Insert the old entries into the new block (skipping dead nodes).
  for (size_t i = 0; i < old_capacity; ++i) {
    Node* const old_entry = old_entries[i];
    if (!old_entry || old_entry->IsDead()) continue;
    for (size_t j = NodeProperties::HashCode(old_entry) & mask;;
         j = (j + 1) & mask) {
      Node* const entry = entries_[j];
      if (entry == old_entry) {
        // Skip duplicate of the old entry.
        break;
      }
      if (!entry) {
        entries_[j] = old_entry;
        size_++;
        break;
      }
    }
  }
}
References v8::internal::compiler::NodeProperties::HashCode(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::compiler::Node::IsDead().
Reduce()
Reduction v8::internal::compiler::ValueNumberingReducer::Reduce (Node * node) [override]
Definition at line 26 of file value-numbering-reducer.cc.
                                                  {
  if (!node->op()->HasProperty(Operator::kIdempotent)) return NoChange();
  const size_t hash = NodeProperties::HashCode(node);
  if (!entries_) {
    DCHECK_EQ(0, size_);
    DCHECK_EQ(0, capacity_);
    // Allocate the initial entries and insert the first entry.
    capacity_ = kInitialCapacity;
    entries_ = temp_zone()->AllocateArray<Node*>(kInitialCapacity);
    memset(entries_, 0, sizeof(*entries_) * kInitialCapacity);
    entries_[hash & (kInitialCapacity - 1)] = node;
    size_ = 1;
    return NoChange();
  }
  DCHECK(size_ < capacity_);
  DCHECK(size_ + size_ / 4 < capacity_);
  const size_t mask = capacity_ - 1;
  size_t dead = capacity_;
  for (size_t i = hash & mask;; i = (i + 1) & mask) {
    Node* entry = entries_[i];
    if (!entry) {
      if (dead != capacity_) {
        // Reuse dead entry that we discovered on the way.
        entries_[dead] = node;
      } else {
        // Have to insert a new entry.
        entries_[i] = node;
        size_++;
        // Resize to keep load factor below 80%
        if (size_ + size_ / 4 >= capacity_) Grow();
      }
      DCHECK(size_ + size_ / 4 < capacity_);
      return NoChange();
    }
    if (entry == node) {
      // We need to check for a certain class of collisions here. Imagine the
      // following scenario:
      //
      // 1. We insert node1 with op1 and certain inputs at index i.
      // 2. We insert node2 with op2 and certain inputs at index i+1.
      // 3. Some other reducer changes node1 to op2 and the inputs from node2.
      //
      // Now we are called again to reduce node1, and we would return NoChange
      // in this case because we find node1 first, but what we should actually
      // do is return Replace(node2) instead.
      for (size_t j = (i + 1) & mask;; j = (j + 1) & mask) {
        Node* other_entry = entries_[j];
        if (!other_entry) {
          // No collision, {node} is fine.
          return NoChange();
        }
        if (other_entry->IsDead()) {
          continue;
        }
        if (other_entry == node) {
          // Collision with ourselves, doesn't count as a real collision.
          // Opportunistically clean-up the duplicate entry if we're at the end
          // of a bucket.
          if (!entries_[(j + 1) & mask]) {
            entries_[j] = nullptr;
            size_--;
            return NoChange();
          }
          // Otherwise, keep searching for another collision.
          continue;
        }
        if (NodeProperties::Equals(other_entry, node)) {
          Reduction reduction = ReplaceIfTypesMatch(node, other_entry);
          if (reduction.Changed()) {
            // Overwrite the colliding entry with the actual entry.
            entries_[i] = other_entry;
            // Opportunistically clean-up the duplicate entry if we're at the
            // end of a bucket.
            if (!entries_[(j + 1) & mask]) {
              entries_[j] = nullptr;
              size_--;
            }
          }
          return reduction;
        }
      }
    }
    // Skip dead entries, but remember their indices so we can reuse them.
    if (entry->IsDead()) {
      dead = i;
      continue;
    }
    if (NodeProperties::Equals(entry, node)) {
      return ReplaceIfTypesMatch(node, entry);
    }
  }
}
References v8::internal::compiler::Reduction::Changed(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::NodeProperties::Equals(), cppgc::internal::anonymous_namespace{explicit-management.cc}::Grow(), v8::internal::compiler::NodeProperties::HashCode(), v8::internal::compiler::Operator::HasProperty(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Node::IsDead(), v8::internal::compiler::Operator::kIdempotent, and v8::internal::compiler::Node::op().
reducer_name()
const char* v8::internal::compiler::ValueNumberingReducer::reducer_name () const [inline], [override]
Definition at line 22 of file value-numbering-reducer.h.
{ return "ValueNumberingReducer"; }
ReplaceIfTypesMatch()
Reduction v8::internal::compiler::ValueNumberingReducer::ReplaceIfTypesMatch (Node * node, Node * replacement) [private]
Definition at line 126 of file value-numbering-reducer.cc.
                                                                        {
  // Make sure the replacement has at least as good type as the original node.
  if (NodeProperties::IsTyped(replacement) && NodeProperties::IsTyped(node)) {
    Type replacement_type = NodeProperties::GetType(replacement);
    Type node_type = NodeProperties::GetType(node);
    if (!replacement_type.Is(node_type)) {
      // Ideally, we would set an intersection of {replacement_type} and
      // {node_type} here. However, typing of NumberConstants assigns different
      // types to constants with the same value (it creates a fresh heap
      // number), which would make the intersection empty. To be safe, we use
      // the smaller type if the types are comparable.
      if (node_type.Is(replacement_type)) {
        NodeProperties::SetType(replacement, node_type);
      } else {
        // Types are not comparable => do not replace.
        return NoChange();
      }
    }
  }
  return Replace(replacement);
}
References v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::Type::Is(), v8::internal::compiler::NodeProperties::IsTyped(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), and v8::internal::compiler::NodeProperties::SetType().
temp_zone()
Zone* v8::internal::compiler::ValueNumberingReducer::temp_zone () const [inline], [private]
Definition at line 31 of file value-numbering-reducer.h.
{ return temp_zone_; }
Member Data Documentation
capacity_
size_t v8::internal::compiler::ValueNumberingReducer::capacity_ [private]
Definition at line 35 of file value-numbering-reducer.h.
entries_
Node** v8::internal::compiler::ValueNumberingReducer::entries_ [private]
Definition at line 34 of file value-numbering-reducer.h.
graph_zone_
Zone* v8::internal::compiler::ValueNumberingReducer::graph_zone_ [private]
Definition at line 38 of file value-numbering-reducer.h.
size_
size_t v8::internal::compiler::ValueNumberingReducer::size_ [private]
Definition at line 36 of file value-numbering-reducer.h.
temp_zone_
Zone* v8::internal::compiler::ValueNumberingReducer::temp_zone_ [private]
Definition at line 37 of file value-numbering-reducer.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/value-numbering-reducer.h
/mnt/V8SourceCode/src/compiler/value-numbering-reducer.cc