v8::internal::MemoryChunkLiveBytesMap Class Reference
Classes
struct Entry
Public Member Functions
MemoryChunkLiveBytesMap ()=default
MemoryChunkLiveBytesMap (const MemoryChunkLiveBytesMap &)=delete
MemoryChunkLiveBytesMap & operator= (const MemoryChunkLiveBytesMap &)=delete
void Increment (MutablePageMetadata *page, intptr_t live)
void FlushAndClear ()
void Erase (MutablePageMetadata *page)
Private Member Functions
Entry & lookup_entry (MutablePageMetadata *page)
Private Attributes
std::array< Entry, kTableSize > map_ = {}
Static Private Attributes
static constexpr size_t kTableSize = 32
Detailed Description
Definition at line 65 of file concurrent-marking.cc.
Constructor & Destructor Documentation
MemoryChunkLiveBytesMap() [1/2]
v8::internal::MemoryChunkLiveBytesMap::MemoryChunkLiveBytesMap () [default]
MemoryChunkLiveBytesMap() [2/2]
v8::internal::MemoryChunkLiveBytesMap::MemoryChunkLiveBytesMap (const MemoryChunkLiveBytesMap &) [delete]
Member Function Documentation
Erase()
void v8::internal::MemoryChunkLiveBytesMap::Erase (MutablePageMetadata * page)
Definition at line 114 of file concurrent-marking.cc.
                                                             {
  Entry& entry = lookup_entry(page);
  if (entry.page == page) {
    entry.page = nullptr;
    entry.live_bytes = 0;
  }
}
References v8::internal::MemoryChunkLiveBytesMap::Entry::live_bytes, lookup_entry(), and v8::internal::MemoryChunkLiveBytesMap::Entry::page.
FlushAndClear()
void v8::internal::MemoryChunkLiveBytesMap::FlushAndClear ()
Definition at line 122 of file concurrent-marking.cc.
                                            {
  for (auto& entry : map_) {
    if (entry.page) {
      entry.page->IncrementLiveBytesAtomically(entry.live_bytes);
      entry.page = nullptr;
      entry.live_bytes = 0;
    }
  }
}
References map_.
Increment()
void v8::internal::MemoryChunkLiveBytesMap::Increment (MutablePageMetadata * page, intptr_t live)
Definition at line 97 of file concurrent-marking.cc.
                                                        {
  Entry& entry = lookup_entry(page);
  if (entry.page == page) {
    entry.live_bytes += bytes;
  } else if (entry.page == nullptr) {
    entry.page = page;
    entry.live_bytes = bytes;
  } else {
    // Write back the existing entry.
    entry.page->IncrementLiveBytesAtomically(entry.live_bytes);
    // Now just replace it with the new entry.
    entry.page = page;
    entry.live_bytes = bytes;
  }
}
References v8::internal::MutablePageMetadata::IncrementLiveBytesAtomically(), v8::internal::MemoryChunkLiveBytesMap::Entry::live_bytes, lookup_entry(), and v8::internal::MemoryChunkLiveBytesMap::Entry::page.
Referenced by v8::internal::ConcurrentMarkingVisitor::IncrementLiveBytesCached().
lookup_entry()
Entry& v8::internal::MemoryChunkLiveBytesMap::lookup_entry (MutablePageMetadata * page) [inline], [private]
Definition at line 88 of file concurrent-marking.cc.
                                                 {
    size_t hash = std::hash<MutablePageMetadata*>{}(page);
    static_assert(base::bits::IsPowerOfTwo(kTableSize));
    return map_[hash % kTableSize];
  }
References v8::base::bits::IsPowerOfTwo(), kTableSize, and map_.
Referenced by Erase(), and Increment().
operator=()
MemoryChunkLiveBytesMap& v8::internal::MemoryChunkLiveBytesMap::operator= (const MemoryChunkLiveBytesMap &) [delete]
Member Data Documentation
kTableSize
constexpr size_t v8::internal::MemoryChunkLiveBytesMap::kTableSize = 32 [static], [constexpr], [private]
Definition at line 86 of file concurrent-marking.cc.
Referenced by lookup_entry().
map_
std::array<Entry, kTableSize> v8::internal::MemoryChunkLiveBytesMap::map_ = {} [private]
Definition at line 94 of file concurrent-marking.cc.
Referenced by FlushAndClear(), and lookup_entry().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/concurrent-marking.cc