v8::internal::TranslatedFrame Class Reference
#include <translated-state.h>
Classes
class iterator
Public Types
enum Kind {
kUnoptimizedFunction
, kInlinedExtraArguments
, kConstructCreateStub
, kConstructInvokeStub
,
kBuiltinContinuation
, kJavaScriptBuiltinContinuation
, kJavaScriptBuiltinContinuationWithCatch
, kInvalid
 }
using reference = TranslatedValue &
using const_reference = TranslatedValue const &
Public Member Functions
int GetValueCount () const
Kind kind () const
BytecodeOffset bytecode_offset () const
DirectHandle< SharedFunctionInfo > shared_info () const
DirectHandle< BytecodeArray > bytecode_array () const
uint32_t height () const
int return_value_offset () const
int return_value_count () const
int formal_parameter_count () const
Tagged< SharedFunctionInfo > raw_shared_info () const
Tagged< BytecodeArray > raw_bytecode_array () const
iterator begin ()
iterator end ()
reference front ()
const_reference front () const
Private Types
enum HandleState { kRawPointers
, kHandles
 }
using ValuesContainer = std::deque< TranslatedValue >
Private Member Functions
TranslatedFrame (Kind kind, Tagged< SharedFunctionInfo > raw_shared_info, Tagged< BytecodeArray > raw_bytecode_array, uint32_t height, int return_value_offset=0, int return_value_count=0)
void Add (const TranslatedValue &value)
TranslatedValue * ValueAt (int index)
void Handlify (Isolate *isolate)
Static Private Member Functions
static TranslatedFrame UnoptimizedJSFrame (BytecodeOffset bytecode_offset, Tagged< SharedFunctionInfo > shared_info, Tagged< BytecodeArray > bytecode_array, uint32_t height, int return_value_offset, int return_value_count)
static TranslatedFrame AccessorFrame (Kind kind, Tagged< SharedFunctionInfo > shared_info)
static TranslatedFrame InlinedExtraArguments (Tagged< SharedFunctionInfo > shared_info, uint32_t height, uint32_t formal_parameter_count)
static TranslatedFrame ConstructCreateStubFrame (Tagged< SharedFunctionInfo > shared_info, uint32_t height)
static TranslatedFrame ConstructInvokeStubFrame (Tagged< SharedFunctionInfo > shared_info)
static TranslatedFrame BuiltinContinuationFrame (BytecodeOffset bailout_id, Tagged< SharedFunctionInfo > shared_info, uint32_t height)
static TranslatedFrame JavaScriptBuiltinContinuationFrame (BytecodeOffset bailout_id, Tagged< SharedFunctionInfo > shared_info, uint32_t height)
static TranslatedFrame JavaScriptBuiltinContinuationWithCatchFrame (BytecodeOffset bailout_id, Tagged< SharedFunctionInfo > shared_info, uint32_t height)
static TranslatedFrame InvalidFrame ()
static void AdvanceIterator (std::deque< TranslatedValue >::iterator *iter)
Private Attributes
Kind kind_
BytecodeOffset bytecode_offset_ = BytecodeOffset::None()
xx xx xx xx xx xx xx xx xx
union {
 Tagged< SharedFunctionInfo > raw_shared_info_
 IndirectHandle< SharedFunctionInfo > shared_info_
};
xx xx xx xx xx xx xx xx xx
union {
 Tagged< BytecodeArray > raw_bytecode_array_
 IndirectHandle< BytecodeArray > bytecode_array_
};
uint32_t height_
int return_value_offset_
int return_value_count_
int formal_parameter_count_ = -1
enum v8::internal::TranslatedFrame::HandleState handle_state_
ValuesContainer values_
Friends
class TranslatedState
class Deoptimizer
Detailed Description
Definition at line 204 of file translated-state.h.
Member Typedef Documentation
const_reference
using v8::internal::TranslatedFrame::const_reference = TranslatedValue const&
Definition at line 301 of file translated-state.h.
reference
using v8::internal::TranslatedFrame::reference = TranslatedValue&
Definition at line 300 of file translated-state.h.
ValuesContainer
using v8::internal::TranslatedFrame::ValuesContainer = std::deque<TranslatedValue> [private]
Definition at line 403 of file translated-state.h.
Member Enumeration Documentation
HandleState
enum v8::internal::TranslatedFrame::HandleState [private]
Enumerator
kRawPointers
kHandles
Definition at line 401 of file translated-state.h.
{ kRawPointers, kHandles } handle_state_;
Kind
enum v8::internal::TranslatedFrame::Kind
Enumerator
kUnoptimizedFunction
kInlinedExtraArguments
kConstructCreateStub
kConstructInvokeStub
kBuiltinContinuation
kJavaScriptBuiltinContinuation
kJavaScriptBuiltinContinuationWithCatch
kInvalid
Definition at line 206 of file translated-state.h.
            {
    kUnoptimizedFunction,
    kInlinedExtraArguments,
    kConstructCreateStub,
    kConstructInvokeStub,
    kBuiltinContinuation,
#if V8_ENABLE_WEBASSEMBLY
    kWasmInlinedIntoJS,
    kJSToWasmBuiltinContinuation,
    kLiftoffFunction,
#endif // V8_ENABLE_WEBASSEMBLY
    kJavaScriptBuiltinContinuation,
    kJavaScriptBuiltinContinuationWithCatch,
    kInvalid
  };
Constructor & Destructor Documentation
TranslatedFrame()
v8::internal::TranslatedFrame::TranslatedFrame (Kind kind, Tagged< SharedFunctionInfo > raw_shared_info, Tagged< BytecodeArray > raw_bytecode_array, uint32_t height, int return_value_offset = 0, int return_value_count = 0) [inline], [explicit], [private]
Definition at line 365 of file translated-state.h.
      : kind_(kind),
        raw_shared_info_(raw_shared_info),
        raw_bytecode_array_(raw_bytecode_array),
        height_(height),
        return_value_offset_(return_value_offset),
        return_value_count_(return_value_count),
        handle_state_(kRawPointers) {}
Referenced by ConstructCreateStubFrame(), ConstructInvokeStubFrame(), and InvalidFrame().
Member Function Documentation
AccessorFrame()
static TranslatedFrame v8::internal::TranslatedFrame::AccessorFrame (Kind kind, Tagged< SharedFunctionInfo > shared_info) [static], [private]
Add()
void v8::internal::TranslatedFrame::Add (const TranslatedValue & value) [inline], [private]
Definition at line 378 of file translated-state.h.
{ values_.push_back(value); }
References v8::internal::value, and values_.
Referenced by v8::internal::TranslatedState::CreateArgumentsElementsTranslatedValues(), v8::internal::TranslatedState::CreateNextTranslatedValue(), and v8::internal::Deoptimizer::DoComputeBuiltinContinuation().
AdvanceIterator()
void v8::internal::TranslatedFrame::AdvanceIterator (std::deque< TranslatedValue >::iterator * iter) [static], [private]
Definition at line 1258 of file translated-state.cc.
                                             {
  int values_to_skip = 1;
  while (values_to_skip > 0) {
    // Consume the current element.
    values_to_skip--;
    // Add all the children.
    values_to_skip += (*iter)->GetChildrenCount();
    (*iter)++;
  }
}
Referenced by v8::internal::TranslatedFrame::iterator::operator++().
begin()
iterator v8::internal::TranslatedFrame::begin () [inline]
Definition at line 303 of file translated-state.h.
{ return iterator(values_.begin()); }
References values_.
Referenced by v8::internal::anonymous_namespace{accessors.cc}::ArgumentsFromDeoptInfo(), v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::Deoptimizer::DoComputeConstructCreateStubFrame(), v8::internal::Deoptimizer::DoComputeConstructInvokeStubFrame(), v8::internal::Deoptimizer::DoComputeInlinedExtraArguments(), v8::internal::Deoptimizer::DoComputeUnoptimizedFrame(), v8::internal::anonymous_namespace{runtime-scopes.cc}::GetCallerArguments(), and v8::internal::FrameFunctionIterator::MaterializeFunction().
BuiltinContinuationFrame()
TranslatedFrame v8::internal::TranslatedFrame::BuiltinContinuationFrame (BytecodeOffset bailout_id, Tagged< SharedFunctionInfo > shared_info, uint32_t height) [static], [private]
Definition at line 885 of file translated-state.cc.
                     {
  TranslatedFrame frame(kBuiltinContinuation, shared_info, {}, height);
  frame.bytecode_offset_ = bytecode_offset;
  return frame;
}
References bytecode_offset(), bytecode_offset_, height(), kBuiltinContinuation, and shared_info().
Referenced by v8::internal::TranslatedState::CreateNextTranslatedFrame().
bytecode_array()
DirectHandle<BytecodeArray> v8::internal::TranslatedFrame::bytecode_array () const [inline]
Definition at line 230 of file translated-state.h.
                                                     {
    CHECK_EQ(handle_state_, kHandles);
    return bytecode_array_;
  }
References bytecode_array_, CHECK_EQ, handle_state_, and kHandles.
Referenced by UnoptimizedJSFrame().
bytecode_offset()
BytecodeOffset v8::internal::TranslatedFrame::bytecode_offset () const [inline]
Definition at line 225 of file translated-state.h.
{ return bytecode_offset_; }
References bytecode_offset_.
Referenced by BuiltinContinuationFrame(), v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::Deoptimizer::DoComputeUnoptimizedFrame(), JavaScriptBuiltinContinuationFrame(), JavaScriptBuiltinContinuationWithCatchFrame(), v8::internal::anonymous_namespace{deoptimizer.cc}::LookupCatchHandler(), and UnoptimizedJSFrame().
ConstructCreateStubFrame()
TranslatedFrame v8::internal::TranslatedFrame::ConstructCreateStubFrame (Tagged< SharedFunctionInfo > shared_info, uint32_t height) [static], [private]
Definition at line 875 of file translated-state.cc.
                                                             {
  return TranslatedFrame(kConstructCreateStub, shared_info, {}, height);
}
References height(), kConstructCreateStub, shared_info(), and TranslatedFrame().
Referenced by v8::internal::TranslatedState::CreateNextTranslatedFrame().
ConstructInvokeStubFrame()
TranslatedFrame v8::internal::TranslatedFrame::ConstructInvokeStubFrame (Tagged< SharedFunctionInfo > shared_info) [static], [private]
Definition at line 880 of file translated-state.cc.
                                            {
  return TranslatedFrame(kConstructInvokeStub, shared_info, {}, 0);
}
References kConstructInvokeStub, shared_info(), and TranslatedFrame().
Referenced by v8::internal::TranslatedState::CreateNextTranslatedFrame().
end()
iterator v8::internal::TranslatedFrame::end () [inline]
Definition at line 304 of file translated-state.h.
{ return iterator(values_.end()); }
References values_.
Referenced by v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::Deoptimizer::DoComputeConstructCreateStubFrame(), v8::internal::Deoptimizer::DoComputeConstructInvokeStubFrame(), and v8::internal::Deoptimizer::DoComputeUnoptimizedFrame().
formal_parameter_count()
int v8::internal::TranslatedFrame::formal_parameter_count () const [inline]
Definition at line 244 of file translated-state.h.
                                     {
    DCHECK_EQ(kind(), kInlinedExtraArguments);
    return formal_parameter_count_;
  }
References DCHECK_EQ, formal_parameter_count_, kind(), and kInlinedExtraArguments.
Referenced by v8::internal::Deoptimizer::DoComputeInlinedExtraArguments(), and InlinedExtraArguments().
front() [1/2]
reference v8::internal::TranslatedFrame::front () [inline]
Definition at line 306 of file translated-state.h.
{ return values_.front(); }
References values_.
front() [2/2]
const_reference v8::internal::TranslatedFrame::front () const [inline]
Definition at line 307 of file translated-state.h.
{ return values_.front(); }
References values_.
GetValueCount()
int v8::internal::TranslatedFrame::GetValueCount () const
Definition at line 942 of file translated-state.cc.
                                         {
  // The function is added to all frame state descriptors in
  // InstructionSelector::AddInputsToFrameStateDescriptor.
  static constexpr int kTheFunction = 1;
  switch (kind()) {
    case kUnoptimizedFunction: {
      int parameter_count = raw_bytecode_array_->parameter_count();
      static constexpr int kTheContext = 1;
      static constexpr int kTheAccumulator = 1;
      return height() + parameter_count + kTheContext + kTheFunction +
             kTheAccumulator;
    }
    case kInlinedExtraArguments:
      return height() + kTheFunction;
    case kConstructCreateStub:
    case kConstructInvokeStub:
    case kBuiltinContinuation:
#if V8_ENABLE_WEBASSEMBLY
    case kJSToWasmBuiltinContinuation:
#endif // V8_ENABLE_WEBASSEMBLY
    case kJavaScriptBuiltinContinuation:
    case kJavaScriptBuiltinContinuationWithCatch: {
      static constexpr int kTheContext = 1;
      return height() + kTheContext + kTheFunction;
    }
#if V8_ENABLE_WEBASSEMBLY
    case kWasmInlinedIntoJS: {
      static constexpr int kTheContext = 1;
      return height() + kTheContext + kTheFunction;
    }
    case kLiftoffFunction: {
      return height();
    }
#endif // V8_ENABLE_WEBASSEMBLY
    case kInvalid:
      UNREACHABLE();
  }
  UNREACHABLE();
}
References height(), kBuiltinContinuation, kConstructCreateStub, kConstructInvokeStub, kind(), kInlinedExtraArguments, kInvalid, kJavaScriptBuiltinContinuation, kJavaScriptBuiltinContinuationWithCatch, kUnoptimizedFunction, raw_bytecode_array_, and v8::internal::UNREACHABLE().
Referenced by v8::internal::TranslatedState::Init().
Handlify()
void v8::internal::TranslatedFrame::Handlify (Isolate * isolate) [private]
Definition at line 986 of file translated-state.cc.
                                               {
  CHECK_EQ(handle_state_, kRawPointers);
  if (!raw_shared_info_.is_null()) {
    shared_info_ = handle(raw_shared_info_, isolate);
  }
  if (!raw_bytecode_array_.is_null()) {
    bytecode_array_ = handle(raw_bytecode_array_, isolate);
  }
  for (auto& value : values_) {
    value.Handlify();
  }
  handle_state_ = kHandles;
}
References bytecode_array_, CHECK_EQ, v8::internal::handle(), handle_state_, kHandles, kRawPointers, raw_bytecode_array_, raw_shared_info_, shared_info_, v8::internal::value, and values_.
height()
uint32_t v8::internal::TranslatedFrame::height () const [inline]
Definition at line 240 of file translated-state.h.
{ return height_; }
References height_.
Referenced by BuiltinContinuationFrame(), ConstructCreateStubFrame(), v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::Deoptimizer::DoComputeConstructCreateStubFrame(), v8::internal::Deoptimizer::DoComputeConstructInvokeStubFrame(), v8::internal::Deoptimizer::DoComputeInlinedExtraArguments(), v8::internal::Deoptimizer::DoComputeUnoptimizedFrame(), GetValueCount(), InlinedExtraArguments(), JavaScriptBuiltinContinuationFrame(), JavaScriptBuiltinContinuationWithCatchFrame(), and UnoptimizedJSFrame().
InlinedExtraArguments()
TranslatedFrame v8::internal::TranslatedFrame::InlinedExtraArguments (Tagged< SharedFunctionInfo > shared_info, uint32_t height, uint32_t formal_parameter_count) [static], [private]
Definition at line 867 of file translated-state.cc.
                                     {
  TranslatedFrame frame(kInlinedExtraArguments, shared_info, {}, height);
  frame.formal_parameter_count_ = formal_parameter_count;
  return frame;
}
References formal_parameter_count(), formal_parameter_count_, height(), kInlinedExtraArguments, and shared_info().
Referenced by v8::internal::TranslatedState::CreateNextTranslatedFrame().
InvalidFrame()
static TranslatedFrame v8::internal::TranslatedFrame::InvalidFrame () [inline], [static], [private]
Definition at line 359 of file translated-state.h.
                                        {
    return TranslatedFrame(kInvalid, {}, {}, 0);
  }
References kInvalid, and TranslatedFrame().
JavaScriptBuiltinContinuationFrame()
TranslatedFrame v8::internal::TranslatedFrame::JavaScriptBuiltinContinuationFrame (BytecodeOffset bailout_id, Tagged< SharedFunctionInfo > shared_info, uint32_t height) [static], [private]
Definition at line 924 of file translated-state.cc.
                     {
  TranslatedFrame frame(kJavaScriptBuiltinContinuation, shared_info, {},
                        height);
  frame.bytecode_offset_ = bytecode_offset;
  return frame;
}
References bytecode_offset(), bytecode_offset_, height(), kJavaScriptBuiltinContinuation, and shared_info().
Referenced by v8::internal::TranslatedState::CreateNextTranslatedFrame().
JavaScriptBuiltinContinuationWithCatchFrame()
TranslatedFrame v8::internal::TranslatedFrame::JavaScriptBuiltinContinuationWithCatchFrame (BytecodeOffset bailout_id, Tagged< SharedFunctionInfo > shared_info, uint32_t height) [static], [private]
Definition at line 933 of file translated-state.cc.
                     {
  TranslatedFrame frame(kJavaScriptBuiltinContinuationWithCatch, shared_info,
                        {}, height);
  frame.bytecode_offset_ = bytecode_offset;
  return frame;
}
References bytecode_offset(), bytecode_offset_, height(), kJavaScriptBuiltinContinuationWithCatch, and shared_info().
Referenced by v8::internal::TranslatedState::CreateNextTranslatedFrame().
kind()
Kind v8::internal::TranslatedFrame::kind () const [inline]
Definition at line 224 of file translated-state.h.
{ return kind_; }
References kind_.
Referenced by v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::Deoptimizer::DoComputeConstructCreateStubFrame(), v8::internal::Deoptimizer::DoComputeConstructInvokeStubFrame(), v8::internal::Deoptimizer::DoComputeOutputFrames(), formal_parameter_count(), GetValueCount(), and v8::internal::anonymous_namespace{deoptimizer.cc}::LookupCatchHandler().
raw_bytecode_array()
Tagged<BytecodeArray> v8::internal::TranslatedFrame::raw_bytecode_array () const [inline]
Definition at line 255 of file translated-state.h.
                                                   {
    CHECK_EQ(handle_state_, kRawPointers);
    CHECK(!raw_bytecode_array_.is_null());
    return raw_bytecode_array_;
  }
References CHECK, CHECK_EQ, handle_state_, kRawPointers, and raw_bytecode_array_.
Referenced by v8::internal::Deoptimizer::DoComputeUnoptimizedFrame().
raw_shared_info()
Tagged<SharedFunctionInfo> v8::internal::TranslatedFrame::raw_shared_info () const [inline]
Definition at line 249 of file translated-state.h.
                                                     {
    CHECK_EQ(handle_state_, kRawPointers);
    CHECK(!raw_shared_info_.is_null());
    return raw_shared_info_;
  }
References CHECK, CHECK_EQ, handle_state_, kRawPointers, and raw_shared_info_.
Referenced by v8::internal::Deoptimizer::DoComputeUnoptimizedFrame(), and v8::internal::anonymous_namespace{deoptimizer.cc}::LookupCatchHandler().
return_value_count()
int v8::internal::TranslatedFrame::return_value_count () const [inline]
Definition at line 243 of file translated-state.h.
{ return return_value_count_; }
References return_value_count_.
Referenced by v8::internal::Deoptimizer::DoComputeUnoptimizedFrame(), and UnoptimizedJSFrame().
return_value_offset()
int v8::internal::TranslatedFrame::return_value_offset () const [inline]
Definition at line 242 of file translated-state.h.
{ return return_value_offset_; }
References return_value_offset_.
Referenced by v8::internal::Deoptimizer::DoComputeUnoptimizedFrame(), and UnoptimizedJSFrame().
shared_info()
DirectHandle<SharedFunctionInfo> v8::internal::TranslatedFrame::shared_info () const [inline]
Definition at line 226 of file translated-state.h.
                                                       {
    CHECK_EQ(handle_state_, kHandles);
    return shared_info_;
  }
References CHECK_EQ, handle_state_, kHandles, and shared_info_.
Referenced by BuiltinContinuationFrame(), ConstructCreateStubFrame(), ConstructInvokeStubFrame(), InlinedExtraArguments(), JavaScriptBuiltinContinuationFrame(), JavaScriptBuiltinContinuationWithCatchFrame(), and UnoptimizedJSFrame().
UnoptimizedJSFrame()
TranslatedFrame v8::internal::TranslatedFrame::UnoptimizedJSFrame (BytecodeOffset bytecode_offset, Tagged< SharedFunctionInfo > shared_info, Tagged< BytecodeArray > bytecode_array, uint32_t height, int return_value_offset, int return_value_count) [static], [private]
Definition at line 857 of file translated-state.cc.
                                                     {
  TranslatedFrame frame(kUnoptimizedFunction, shared_info, bytecode_array,
                        height, return_value_offset, return_value_count);
  frame.bytecode_offset_ = bytecode_offset;
  return frame;
}
References bytecode_array(), bytecode_offset(), bytecode_offset_, height(), kUnoptimizedFunction, return_value_count(), return_value_offset(), and shared_info().
Referenced by v8::internal::TranslatedState::CreateNextTranslatedFrame().
ValueAt()
TranslatedValue* v8::internal::TranslatedFrame::ValueAt (int index) [inline], [private]
Definition at line 379 of file translated-state.h.
{ return &(values_[index]); }
References v8::internal::index, and values_.
Referenced by v8::internal::TranslatedState::EnsureCapturedObjectAllocatedAt(), v8::internal::TranslatedState::EnsureChildrenAllocated(), v8::internal::TranslatedState::GetResolvedSlot(), and v8::internal::TranslatedState::InitializeCapturedObjectAt().
Friends And Related Function Documentation
Deoptimizer
friend class Deoptimizer [friend]
Definition at line 324 of file translated-state.h.
TranslatedState
friend class TranslatedState [friend]
Definition at line 323 of file translated-state.h.
Member Data Documentation
union { ... } [private]
union { ... } [private]
bytecode_array_
IndirectHandle<BytecodeArray> v8::internal::TranslatedFrame::bytecode_array_
Definition at line 393 of file translated-state.h.
Referenced by bytecode_array(), and Handlify().
bytecode_offset_
BytecodeOffset v8::internal::TranslatedFrame::bytecode_offset_ = BytecodeOffset::None() [private]
Definition at line 383 of file translated-state.h.
Referenced by BuiltinContinuationFrame(), bytecode_offset(), JavaScriptBuiltinContinuationFrame(), JavaScriptBuiltinContinuationWithCatchFrame(), and UnoptimizedJSFrame().
formal_parameter_count_
int v8::internal::TranslatedFrame::formal_parameter_count_ = -1 [private]
Definition at line 399 of file translated-state.h.
Referenced by formal_parameter_count(), and InlinedExtraArguments().
handle_state_
enum v8::internal::TranslatedFrame::HandleState v8::internal::TranslatedFrame::handle_state_ [private]
Referenced by bytecode_array(), Handlify(), raw_bytecode_array(), raw_shared_info(), and shared_info().
height_
uint32_t v8::internal::TranslatedFrame::height_ [private]
Definition at line 396 of file translated-state.h.
Referenced by height().
kind_
Kind v8::internal::TranslatedFrame::kind_ [private]
Definition at line 382 of file translated-state.h.
Referenced by kind().
raw_bytecode_array_
Tagged<BytecodeArray> v8::internal::TranslatedFrame::raw_bytecode_array_
Definition at line 392 of file translated-state.h.
Referenced by GetValueCount(), Handlify(), and raw_bytecode_array().
raw_shared_info_
Tagged<SharedFunctionInfo> v8::internal::TranslatedFrame::raw_shared_info_
Definition at line 388 of file translated-state.h.
Referenced by Handlify(), and raw_shared_info().
return_value_count_
int v8::internal::TranslatedFrame::return_value_count_ [private]
Definition at line 398 of file translated-state.h.
Referenced by return_value_count().
return_value_offset_
int v8::internal::TranslatedFrame::return_value_offset_ [private]
Definition at line 397 of file translated-state.h.
Referenced by return_value_offset().
shared_info_
IndirectHandle<SharedFunctionInfo> v8::internal::TranslatedFrame::shared_info_
Definition at line 389 of file translated-state.h.
Referenced by Handlify(), and shared_info().
values_
ValuesContainer v8::internal::TranslatedFrame::values_ [private]
Definition at line 405 of file translated-state.h.
Referenced by Add(), begin(), v8::internal::TranslatedState::CreateArgumentsElementsTranslatedValues(), v8::internal::TranslatedState::CreateNextTranslatedValue(), end(), v8::internal::TranslatedState::EnsureCapturedObjectAllocatedAt(), front(), Handlify(), v8::internal::TranslatedState::InitializeCapturedObjectAt(), v8::internal::TranslatedState::MaterializeFixedDoubleArray(), v8::internal::TranslatedState::MaterializeHeapNumber(), v8::internal::TranslatedState::ResolveStringConcat(), v8::internal::TranslatedState::SkipSlots(), and ValueAt().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/deoptimizer/translated-state.h
/mnt/V8SourceCode/src/deoptimizer/translated-state.cc