v8::internal::compiler::AdvancedReducer Class Reference
#include <graph-reducer.h>
Classes
class Editor
Public Member Functions
AdvancedReducer (Editor *editor)
Protected Member Functions
void Replace (Node *node, Node *replacement)
void Replace (Node *node, Node *replacement, NodeId max_id)
void Revisit (Node *node)
void ReplaceWithValue (Node *node, Node *value, Node *effect=nullptr, Node *control=nullptr)
void RelaxEffectsAndControls (Node *node)
void RelaxControls (Node *node, Node *control=nullptr)
void MergeControlToEnd (TFGraph *graph, CommonOperatorBuilder *common, Node *node)
Static Protected Member Functions
static Reduction Replace (Node *node)
Private Attributes
Editor *const editor_
Additional Inherited Members
Detailed Description
Definition at line 82 of file graph-reducer.h.
Constructor & Destructor Documentation
AdvancedReducer()
v8::internal::compiler::AdvancedReducer::AdvancedReducer (Editor * editor) [inline], [explicit]
Definition at line 101 of file graph-reducer.h.
: editor_(editor) {}
Member Function Documentation
MergeControlToEnd()
void v8::internal::compiler::AdvancedReducer::MergeControlToEnd (TFGraph * graph, CommonOperatorBuilder * common, Node * node) [inline], [protected]
Definition at line 138 of file graph-reducer.h.
                                     {
    NodeProperties::MergeControlToEnd(graph, common, node);
    Revisit(graph->end());
  }
References graph(), v8::internal::compiler::NodeProperties::MergeControlToEnd(), and Revisit().
Referenced by v8::internal::compiler::JSCallReducer::CheckIfConstructor(), v8::internal::compiler::JSInliner::InlineCall(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeShift(), v8::internal::compiler::JSCallReducer::ReduceCollectionIteratorPrototypeNext(), v8::internal::compiler::JSNativeContextSpecialization::ReduceEagerDeoptimize(), v8::internal::compiler::JSCallReducer::ReduceForInsufficientFeedback(), v8::internal::compiler::JSInliner::ReduceJSCall(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetIterator(), v8::internal::compiler::JSCallReducer::ReduceReflectGet(), and v8::internal::compiler::JSCallReducer::ReduceReflectHas().
RelaxControls()
void v8::internal::compiler::AdvancedReducer::RelaxControls (Node * node, Node * control = nullptr) [inline], [protected]
Definition at line 134 of file graph-reducer.h.
                                                          {
    ReplaceWithValue(node, node, node, control);
  }
References ReplaceWithValue().
Referenced by v8::internal::compiler::JSCallReducer::ReduceStringConstructor().
RelaxEffectsAndControls()
void v8::internal::compiler::AdvancedReducer::RelaxEffectsAndControls (Node * node) [inline], [protected]
Definition at line 128 of file graph-reducer.h.
                                           {
    ReplaceWithValue(node, node, nullptr, nullptr);
  }
References ReplaceWithValue().
Referenced by v8::internal::compiler::JSCallReducer::ReduceArrayBufferIsView(), and v8::internal::compiler::JSCallReducer::ReduceStringPrototypeIndexOfIncludes().
Replace() [1/3]
static Reduction v8::internal::compiler::AdvancedReducer::Replace (Node * node) [inline], [static], [protected]
Definition at line 105 of file graph-reducer.h.
{ return Reducer::Replace(node); }
References v8::internal::compiler::Reducer::Replace().
Referenced by v8::internal::compiler::JSCallReducer::Finalize(), v8::internal::compiler::JSInliner::InlineCall(), v8::internal::compiler::JSInliningHeuristic::InlineCandidate(), v8::internal::compiler::JSCallReducer::ReduceArrayIsArray(), v8::internal::compiler::JSCallReducer::ReduceArrayIteratorPrototypeNext(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypePop(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeShift(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeSlice(), v8::internal::compiler::WasmGCLowering::ReduceAssertNotNull(), v8::internal::compiler::JSCallReducer::ReduceBigIntAsN(), v8::internal::compiler::JSCallReducer::ReduceBooleanConstructor(), v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), v8::internal::compiler::RedundancyElimination::ReduceCheckNode(), v8::internal::compiler::WasmGCOperatorReducer::ReduceCheckNull(), v8::internal::compiler::JSCallReducer::ReduceCollectionIteration(), v8::internal::compiler::JSCallReducer::ReduceCollectionIteratorPrototypeNext(), v8::internal::compiler::JSCallReducer::ReduceCollectionPrototypeHas(), v8::internal::compiler::JSCallReducer::ReduceCollectionPrototypeSize(), v8::internal::compiler::JSCallReducer::ReduceDateNow(), v8::internal::compiler::JSCallReducer::ReduceDatePrototypeGetField(), v8::internal::compiler::JSCallReducer::ReduceDatePrototypeGetTime(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccess(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccessOnString(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementLoadFromHeapConstant(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeApply(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeBind(), v8::internal::compiler::JSNativeContextSpecialization::ReduceGlobalAccess(), v8::internal::compiler::JSCallReducer::ReduceGlobalIsFinite(), v8::internal::compiler::JSCallReducer::ReduceGlobalIsNaN(), v8::internal::compiler::WasmGCLowering::ReduceIsNotNull(), v8::internal::compiler::WasmGCLowering::ReduceIsNull(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAdd(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAsyncFunctionEnter(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAsyncFunctionReject(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAsyncFunctionResolve(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSFindNonDefaultConstructorOrConstruct(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetIterator(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetSuperConstructor(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSHasInPrototypeChain(), v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContextNoCell(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadGlobal(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadNamed(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadPropertyWithEnumeratedKey(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSPromiseResolve(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSResolvePromise(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSStoreGlobal(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSToObject(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSToString(), v8::internal::compiler::JSCallReducer::ReduceMapPrototypeGet(), v8::internal::compiler::JSCallReducer::ReduceMathBinary(), v8::internal::compiler::JSCallReducer::ReduceMathClz32(), v8::internal::compiler::JSCallReducer::ReduceMathImul(), v8::internal::compiler::JSCallReducer::ReduceMathMinMax(), v8::internal::compiler::JSCallReducer::ReduceMathUnary(), v8::internal::compiler::JSNativeContextSpecialization::ReduceMegaDOMPropertyAccess(), v8::internal::compiler::JSNativeContextSpecialization::ReduceNamedAccess(), v8::internal::compiler::WasmGCLowering::ReduceNull(), v8::internal::compiler::JSCallReducer::ReduceNumberIsFinite(), v8::internal::compiler::JSCallReducer::ReduceNumberIsInteger(), v8::internal::compiler::JSCallReducer::ReduceNumberIsNaN(), v8::internal::compiler::JSCallReducer::ReduceNumberIsSafeInteger(), v8::internal::compiler::JSCallReducer::ReduceNumberParseInt(), v8::internal::compiler::JSCallReducer::ReduceObjectConstructor(), v8::internal::compiler::JSCallReducer::ReduceObjectGetPrototype(), v8::internal::compiler::JSCallReducer::ReduceObjectIs(), v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeHasOwnProperty(), v8::internal::compiler::JSContextSpecialization::ReduceParameter(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeThen(), v8::internal::compiler::JSCallReducer::ReduceReturnReceiver(), v8::internal::compiler::WasmGCLowering::ReduceRttCanon(), v8::internal::compiler::WasmGCLowering::ReduceStringAsWtf16(), v8::internal::compiler::JSCallReducer::ReduceStringFromCharCode(), v8::internal::compiler::JSCallReducer::ReduceStringFromCodePoint(), v8::internal::compiler::JSCallReducer::ReduceStringIteratorPrototypeNext(), v8::internal::compiler::WasmGCLowering::ReduceStringPrepareForGetCodeunit(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeConcat(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeIndexOfIncludes(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeIterator(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeStringCodePointAt(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeSubstr(), v8::internal::compiler::JSCallReducer::ReduceTypedArrayConstructor(), v8::internal::compiler::JSCallReducer::ReduceTypedArrayPrototypeToStringTag(), v8::internal::compiler::WasmGCLowering::ReduceTypeGuard(), v8::internal::compiler::WasmGCLowering::ReduceWasmAnyConvertExtern(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmAnyConvertExtern(), v8::internal::compiler::WasmGCLowering::ReduceWasmArrayGet(), v8::internal::compiler::WasmGCLowering::ReduceWasmArrayInitializeLength(), v8::internal::compiler::WasmGCLowering::ReduceWasmArrayLength(), v8::internal::compiler::WasmGCLowering::ReduceWasmArraySet(), v8::internal::compiler::WasmGCLowering::ReduceWasmExternConvertAny(), v8::internal::compiler::WasmGCLowering::ReduceWasmStructGet(), v8::internal::compiler::WasmGCLowering::ReduceWasmStructSet(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheck(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheck(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheckAbstract(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheckAbstract(), and v8::internal::compiler::JSCallReducer::ReplaceWithSubgraph().
Replace() [2/3]
void v8::internal::compiler::AdvancedReducer::Replace (Node * node, Node * replacement) [inline], [protected]
Definition at line 108 of file graph-reducer.h.
                                              {
    DCHECK_NOT_NULL(editor_);
    editor_->Replace(node, replacement);
  }
References DCHECK_NOT_NULL, editor_, and v8::internal::compiler::AdvancedReducer::Editor::Replace().
Replace() [3/3]
void v8::internal::compiler::AdvancedReducer::Replace (Node * node, Node * replacement, NodeId max_id) [inline], [protected]
Definition at line 112 of file graph-reducer.h.
                                                             {
    return editor_->Replace(node, replacement, max_id);
  }
References editor_, and v8::internal::compiler::AdvancedReducer::Editor::Replace().
ReplaceWithValue()
void v8::internal::compiler::AdvancedReducer::ReplaceWithValue (Node * node, Node * value, Node * effect = nullptr, Node * control = nullptr) [inline], [protected]
Definition at line 119 of file graph-reducer.h.
                                                 {
    DCHECK_NOT_NULL(editor_);
    editor_->ReplaceWithValue(node, value, effect, control);
  }
References DCHECK_NOT_NULL, editor_, v8::internal::compiler::AdvancedReducer::Editor::ReplaceWithValue(), and v8::internal::value.
Referenced by v8::internal::compiler::JSCallReducer::CheckIfConstructor(), v8::internal::compiler::JSInliner::InlineCall(), v8::internal::compiler::JSInliningHeuristic::InlineCandidate(), v8::internal::compiler::SimplifyTFLoops::Reduce(), v8::internal::compiler::WasmEscapeAnalysis::ReduceAllocateRaw(), v8::internal::compiler::JSCallReducer::ReduceArrayIsArray(), v8::internal::compiler::JSCallReducer::ReduceArrayIterator(), v8::internal::compiler::JSCallReducer::ReduceArrayIteratorPrototypeNext(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypePop(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeShift(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeSlice(), v8::internal::compiler::WasmGCLowering::ReduceAssertNotNull(), v8::internal::compiler::WasmGCOperatorReducer::ReduceAssertNotNull(), v8::internal::compiler::JSCallReducer::ReduceBigIntAsN(), v8::internal::compiler::JSCallReducer::ReduceBooleanConstructor(), v8::internal::compiler::RedundancyElimination::ReduceCheckNode(), v8::internal::compiler::WasmGCOperatorReducer::ReduceCheckNull(), v8::internal::compiler::JSCallReducer::ReduceCollectionIteration(), v8::internal::compiler::JSCallReducer::ReduceCollectionIteratorPrototypeNext(), v8::internal::compiler::JSCallReducer::ReduceCollectionPrototypeHas(), v8::internal::compiler::JSCallReducer::ReduceCollectionPrototypeSize(), v8::internal::compiler::JSCallReducer::ReduceDataViewAccess(), v8::internal::compiler::JSCallReducer::ReduceDateNow(), v8::internal::compiler::JSCallReducer::ReduceDatePrototypeGetField(), v8::internal::compiler::JSCallReducer::ReduceDatePrototypeGetTime(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccess(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccessOnString(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementLoadFromHeapConstant(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeApply(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeBind(), v8::internal::compiler::JSNativeContextSpecialization::ReduceGlobalAccess(), v8::internal::compiler::JSCallReducer::ReduceGlobalIsFinite(), v8::internal::compiler::JSCallReducer::ReduceGlobalIsNaN(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAdd(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAsyncFunctionEnter(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAsyncFunctionReject(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAsyncFunctionResolve(), v8::internal::compiler::JSInliner::ReduceJSCall(), v8::internal::compiler::JSContextSpecialization::ReduceJSGetImportMeta(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetIterator(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetSuperConstructor(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSHasInPrototypeChain(), v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContext(), v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContextNoCell(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadGlobal(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadNamed(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadPropertyWithEnumeratedKey(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSPromiseResolve(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSResolvePromise(), v8::internal::compiler::JSContextSpecialization::ReduceJSStoreContext(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSStoreGlobal(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSToObject(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSToString(), v8::internal::compiler::JSCallReducer::ReduceMapPrototypeGet(), v8::internal::compiler::JSCallReducer::ReduceMathBinary(), v8::internal::compiler::JSCallReducer::ReduceMathClz32(), v8::internal::compiler::JSCallReducer::ReduceMathImul(), v8::internal::compiler::JSCallReducer::ReduceMathMinMax(), v8::internal::compiler::JSCallReducer::ReduceMathUnary(), v8::internal::compiler::JSNativeContextSpecialization::ReduceMegaDOMPropertyAccess(), v8::internal::compiler::JSNativeContextSpecialization::ReduceNamedAccess(), v8::internal::compiler::JSCallReducer::ReduceNumberIsFinite(), v8::internal::compiler::JSCallReducer::ReduceNumberIsInteger(), v8::internal::compiler::JSCallReducer::ReduceNumberIsNaN(), v8::internal::compiler::JSCallReducer::ReduceNumberIsSafeInteger(), v8::internal::compiler::JSCallReducer::ReduceNumberParseInt(), v8::internal::compiler::JSCallReducer::ReduceObjectConstructor(), v8::internal::compiler::JSCallReducer::ReduceObjectGetPrototype(), v8::internal::compiler::JSCallReducer::ReduceObjectIs(), v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeHasOwnProperty(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeThen(), v8::internal::compiler::JSCallReducer::ReduceReflectGet(), v8::internal::compiler::JSCallReducer::ReduceReflectHas(), v8::internal::compiler::JSCallReducer::ReduceReturnReceiver(), v8::internal::compiler::WasmGCLowering::ReduceStringAsWtf16(), v8::internal::compiler::JSCallReducer::ReduceStringConstructor(), v8::internal::compiler::JSCallReducer::ReduceStringFromCharCode(), v8::internal::compiler::JSCallReducer::ReduceStringFromCodePoint(), v8::internal::compiler::JSCallReducer::ReduceStringIteratorPrototypeNext(), v8::internal::compiler::WasmGCLowering::ReduceStringPrepareForGetCodeunit(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeConcat(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeIterator(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeStringCodePointAt(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeSubstr(), v8::internal::compiler::JSCallReducer::ReduceTypedArrayPrototypeToStringTag(), v8::internal::compiler::WasmGCLowering::ReduceTypeGuard(), v8::internal::compiler::WasmGCLowering::ReduceWasmAnyConvertExtern(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmAnyConvertExtern(), v8::internal::compiler::WasmGCLowering::ReduceWasmArrayLength(), v8::internal::compiler::WasmGCLowering::ReduceWasmExternConvertAny(), v8::internal::compiler::WasmGCLowering::ReduceWasmStructGet(), v8::internal::compiler::WasmGCLowering::ReduceWasmStructSet(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheck(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheck(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheckAbstract(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheckAbstract(), RelaxControls(), RelaxEffectsAndControls(), v8::internal::compiler::JSCallReducer::ReleaseEffectAndControlFromAssembler(), v8::internal::compiler::JSNativeContextSpecialization::ReleaseEffectAndControlFromAssembler(), v8::internal::compiler::LateEscapeAnalysis::RemoveAllocation(), and v8::internal::compiler::JSCallReducer::ReplaceWithSubgraph().
Revisit()
void v8::internal::compiler::AdvancedReducer::Revisit (Node * node) [inline], [protected]
Definition at line 115 of file graph-reducer.h.
                           {
    DCHECK_NOT_NULL(editor_);
    editor_->Revisit(node);
  }
References DCHECK_NOT_NULL, editor_, and v8::internal::compiler::AdvancedReducer::Editor::Revisit().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccessForTypedArrayOrRabGsabTypedArray(), MergeControlToEnd(), v8::internal::compiler::WasmEscapeAnalysis::ReduceAllocateRaw(), and v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf().
Member Data Documentation
editor_
Editor* const v8::internal::compiler::AdvancedReducer::editor_ [private]
Definition at line 145 of file graph-reducer.h.
Referenced by Replace(), ReplaceWithValue(), and Revisit().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/graph-reducer.h