v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::Writer Class Reference
Public Member Functions
Writer (base::Vector< uint8_t > buffer)
size_t bytes_written () const
uint8_t * current_location () const
size_t current_size () const
base::Vector< uint8_t > current_buffer () const
template<typename T >
void Write (const T &value)
template<typename T >
void WriteVector (const base::Vector< T > v)
void Skip (size_t size)
Private Attributes
uint8_t *const start_
uint8_t *const end_
uint8_t * pos_
Detailed Description
Definition at line 35 of file wasm-serialization.cc.
Constructor & Destructor Documentation
Writer()
v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::Writer::Writer (base::Vector< uint8_t > buffer) [inline], [explicit]
Definition at line 37 of file wasm-serialization.cc.
      : start_(buffer.begin()), end_(buffer.end()), pos_(buffer.begin()) {}
Member Function Documentation
bytes_written()
size_t v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::Writer::bytes_written () const [inline]
Definition at line 40 of file wasm-serialization.cc.
{ return pos_ - start_; }
Referenced by v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::WriteHeader().
current_buffer()
base::Vector<uint8_t> v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::Writer::current_buffer () const [inline]
Definition at line 43 of file wasm-serialization.cc.
                                             {
    return {current_location(), current_size()};
  }
current_location()
uint8_t* v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::Writer::current_location () const [inline]
Definition at line 41 of file wasm-serialization.cc.
{ return pos_; }
current_size()
size_t v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::Writer::current_size () const [inline]
Definition at line 42 of file wasm-serialization.cc.
{ return end_ - pos_; }
Skip()
void v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::Writer::Skip (size_t size) [inline]
Definition at line 73 of file wasm-serialization.cc.
{ pos_ += size; }
References size().
Write()
template<typename T >
void v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::Writer::Write (const T & value) [inline]
Definition at line 48 of file wasm-serialization.cc.
                             {
    DCHECK_GE(current_size(), sizeof(T));
    WriteUnalignedValue(reinterpret_cast<Address>(current_location()), value);
    pos_ += sizeof(T);
    if (v8_flags.trace_wasm_serialization) {
      StdoutStream{} << "wrote: " << static_cast<size_t>(value)
                     << " sized: " << sizeof(T) << std::endl;
    }
  }
References DCHECK_GE, T, v8::internal::v8_flags, v8::internal::value, and v8::base::WriteUnalignedValue().
Referenced by v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::WriteHeader().
WriteVector()
template<typename T >
void v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::Writer::WriteVector (const base::Vector< T > v) [inline]
Definition at line 59 of file wasm-serialization.cc.
                                          {
    base::Vector<const uint8_t> bytes = base::Vector<const uint8_t>::cast(v);
    DCHECK_GE(current_size(), bytes.size());
    if (!bytes.empty()) {
      memcpy(current_location(), bytes.begin(), bytes.size());
      pos_ += bytes.size();
    }
    if (v8_flags.trace_wasm_serialization) {
      StdoutStream{} << "wrote vector of " << v.size()
                     << " elements (total size " << bytes.size() << " bytes)"
                     << std::endl;
    }
  }
References v8::base::Vector< T >::begin(), DCHECK_GE, v8::base::Vector< T >::empty(), v8::base::Vector< T >::size(), and v8::internal::v8_flags.
Member Data Documentation
end_
uint8_t* const v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::Writer::end_ [private]
Definition at line 77 of file wasm-serialization.cc.
pos_
uint8_t* v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::Writer::pos_ [private]
Definition at line 78 of file wasm-serialization.cc.
start_
uint8_t* const v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::Writer::start_ [private]
Definition at line 76 of file wasm-serialization.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/wasm-serialization.cc