v8::internal::StringOutputStream Class Reference
#include <output-stream.h>
Public Member Functions
WriteResult WriteAsciiChunk (char *data, int size) override
Writes the next chunk of snapshot data into the stream.
void EndOfStream () override
Notify about the end of stream.
std::string str ()
Private Attributes
std::stringstream os_
Additional Inherited Members
Detailed Description
Definition at line 28 of file output-stream.h.
Member Function Documentation
EndOfStream()
void v8::internal::StringOutputStream::EndOfStream () [inline], [override], [virtual]
Notify about the end of stream.
Implements v8::OutputStream.
Definition at line 31 of file output-stream.h.
{}
str()
std::string v8::internal::StringOutputStream::str ()
Definition at line 22 of file output-stream.cc.
{ return os_.str(); }
References os_.
Referenced by v8::D8Console::ProfileEnd(), and v8::internal::HeapProfiler::TakeSnapshotToString().
WriteAsciiChunk()
v8::OutputStream::WriteResult v8::internal::StringOutputStream::WriteAsciiChunk (char * data, int size) [override], [virtual]
Writes the next chunk of snapshot data into the stream.
Writing can be stopped by returning kAbort as function result. EndOfStream will not be called in case writing was aborted.
Implements v8::OutputStream.
Definition at line 17 of file output-stream.cc.
                                                                            {
  os_.write(data, size);
  return kContinue;
}
References v8::OutputStream::kContinue, os_, and size().
Member Data Documentation
os_
std::stringstream v8::internal::StringOutputStream::os_ [private]
Definition at line 36 of file output-stream.h.
Referenced by str(), and WriteAsciiChunk().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/utils/output-stream.h
/mnt/V8SourceCode/src/utils/output-stream.cc