v8::internal::maglev::Float64ToBoolean Class Reference
#include <maglev-ir.h>
Public Member Functions
Float64ToBoolean (uint64_t bitfield, bool flip)
Input & value ()
constexpr bool flip () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
auto options () const
Static Public Attributes
static constexpr Base::InputTypes kInputTypes
Private Types
using Base = FixedInputValueNodeT< 1, Float64ToBoolean >
using FlipBitField = NextBitField< bool, 1 >
Additional Inherited Members
Detailed Description
Definition at line 3510 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::Float64ToBoolean::Base = FixedInputValueNodeT<1, Float64ToBoolean> [private]
Definition at line 3511 of file maglev-ir.h.
FlipBitField
using v8::internal::maglev::Float64ToBoolean::FlipBitField = NextBitField<bool, 1> [private]
Definition at line 3531 of file maglev-ir.h.
Constructor & Destructor Documentation
Float64ToBoolean()
v8::internal::maglev::Float64ToBoolean::Float64ToBoolean (uint64_t bitfield, bool flip) [inline], [explicit]
Definition at line 3514 of file maglev-ir.h.
      : Base(FlipBitField::update(bitfield, flip)) {}
Member Function Documentation
flip()
constexpr bool v8::internal::maglev::Float64ToBoolean::flip () const [inline], [constexpr]
Definition at line 3522 of file maglev-ir.h.
{ return FlipBitField::decode(bitfield()); }
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfRootConstant(), options(), and PrintParams().
GenerateCode()
void v8::internal::maglev::Float64ToBoolean::GenerateCode (MaglevAssembler * , const ProcessingState &)
options()
auto v8::internal::maglev::Float64ToBoolean::options () const [inline]
Definition at line 3528 of file maglev-ir.h.
{ return std::tuple{flip()}; }
References flip().
PrintParams()
void v8::internal::maglev::Float64ToBoolean::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8311 of file maglev-ir.cc.
                                                                              {
  if (flip()) {
    os << "(flipped)";
  }
}
References flip().
SetValueLocationConstraints()
void v8::internal::maglev::Float64ToBoolean::SetValueLocationConstraints ()
value()
Input& v8::internal::maglev::Float64ToBoolean::value () [inline]
Definition at line 3520 of file maglev-ir.h.
{ return Node::input(0); }
References v8::internal::maglev::NodeBase::input().
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::Float64ToBoolean::kInputTypes [static], [constexpr]
Initial value:
{
      ValueRepresentation::kHoleyFloat64}
Definition at line 3517 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc