v8::internal::ClassScope Class Reference
#include <scopes.h>
Classes
struct HeritageParsingScope
struct RareData
Public Member Functions
ClassScope (Zone *zone, Scope *outer_scope, bool is_anonymous)
template<typename IsolateT >
ClassScope (IsolateT *isolate, Zone *zone, AstValueFactory *ast_value_factory, Handle< ScopeInfo > scope_info)
Variable * DeclarePrivateName (const AstRawString *name, VariableMode mode, IsStaticFlag is_static_flag, bool *was_added)
Variable * RedeclareSyntheticContextVariable (const AstRawString *name)
V8_WARN_UNUSED_RESULT bool ResolvePrivateNames (ParseInfo *info)
VariableProxy * ResolvePrivateNamesPartially ()
UnresolvedList::Iterator GetUnresolvedPrivateNameTail ()
void ResetUnresolvedPrivateNameTail (UnresolvedList::Iterator tail)
void MigrateUnresolvedPrivateNameTail (AstNodeFactory *ast_node_factory, UnresolvedList::Iterator tail)
Variable * DeclareBrandVariable (AstValueFactory *ast_value_factory, IsStaticFlag is_static_flag, int class_token_pos)
Variable * DeclareClassVariable (AstValueFactory *ast_value_factory, const AstRawString *name, int class_token_pos)
Variable * brand ()
Variable * class_variable ()
bool IsParsingHeritage ()
bool has_static_private_methods () const
bool should_save_class_variable () const
bool is_anonymous_class () const
void set_should_save_class_variable ()
Private Member Functions
Variable * LookupPrivateName (VariableProxy *proxy)
Variable * LookupLocalPrivateName (const AstRawString *name)
Variable * LookupPrivateNameInScopeInfo (const AstRawString *name)
RareData * GetRareData ()
RareData * EnsureRareData ()
void SetIsParsingHeritage (bool v)
Private Attributes
base::PointerWithPayload< RareData, bool, 1 > rare_data_and_is_parsing_heritage_
Variable * class_variable_ = nullptr
bool has_static_private_methods_: 1 = false
bool has_explicit_static_private_methods_access_: 1 = false
bool is_anonymous_class_: 1 = false
bool should_save_class_variable_: 1 = false
Friends
class Scope
class PrivateNameScopeIterator
Additional Inherited Members
Detailed Description
Definition at line 1400 of file scopes.h.
Constructor & Destructor Documentation
ClassScope() [1/2]
v8::internal::ClassScope::ClassScope (Zone * zone, Scope * outer_scope, bool is_anonymous)
Definition at line 195 of file scopes.cc.
    : Scope(zone, outer_scope, CLASS_SCOPE),
      rare_data_and_is_parsing_heritage_(nullptr),
      is_anonymous_class_(is_anonymous) {
  set_language_mode(LanguageMode::kStrict);
}
References v8::internal::kStrict, and v8::internal::Scope::set_language_mode().
ClassScope() [2/2]
template<typename IsolateT >
v8::internal::ClassScope::ClassScope (IsolateT * isolate, Zone * zone, AstValueFactory * ast_value_factory, Handle< ScopeInfo > scope_info)
Definition at line 203 of file scopes.cc.
    : Scope(zone, CLASS_SCOPE, ast_value_factory, scope_info),
      rare_data_and_is_parsing_heritage_(nullptr) {
  set_language_mode(LanguageMode::kStrict);
  if (scope_info->ClassScopeHasPrivateBrand()) {
    Variable* brand =
        LookupInScopeInfo(ast_value_factory->dot_brand_string(), this);
    DCHECK_NOT_NULL(brand);
    EnsureRareData()->brand = brand;
  }
  // If the class variable is context-allocated and its index is
  // saved for deserialization, deserialize it.
  if (scope_info->HasSavedClassVariable()) {
    Tagged<String> name;
    int index;
    std::tie(name, index) = scope_info->SavedClassVariable();
    DCHECK_EQ(scope_info->ContextLocalMode(index), VariableMode::kConst);
    DCHECK_EQ(scope_info->ContextLocalInitFlag(index),
              InitializationFlag::kNeedsInitialization);
    DCHECK_EQ(scope_info->ContextLocalMaybeAssignedFlag(index),
              MaybeAssignedFlag::kMaybeAssigned);
    Variable* var = DeclareClassVariable(
        ast_value_factory,
        ast_value_factory->GetString(name,
                                     SharedStringAccessGuardIfNeeded(isolate)),
        kNoSourcePosition);
    var->AllocateTo(VariableLocation::CONTEXT,
                    Context::MIN_CONTEXT_SLOTS + index);
  }
  DCHECK(scope_info->HasPositionInfo());
  set_start_position(scope_info->StartPosition());
  set_end_position(scope_info->EndPosition());
}
References v8::internal::Variable::AllocateTo(), brand(), v8::internal::ClassScope::RareData::brand, v8::internal::CONTEXT, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NOT_NULL, DeclareClassVariable(), EnsureRareData(), v8::internal::AstValueFactory::GetString(), v8::internal::index, v8::internal::kConst, v8::internal::kMaybeAssigned, v8::internal::kNeedsInitialization, v8::internal::kNoSourcePosition, v8::internal::kStrict, v8::internal::Scope::LookupInScopeInfo(), v8::internal::Context::MIN_CONTEXT_SLOTS, v8::internal::name, v8::internal::Scope::scope_info(), v8::internal::Scope::set_end_position(), v8::internal::Scope::set_language_mode(), and v8::internal::Scope::set_start_position().
Member Function Documentation
brand()
Variable* v8::internal::ClassScope::brand () [inline]
Definition at line 1460 of file scopes.h.
                    {
    return GetRareData() == nullptr ? nullptr : GetRareData()->brand;
  }
References nullptr.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), v8::internal::interpreter::BytecodeGenerator::BuildInstanceInitializationAfterSuperCall(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateBrandCheck(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateMethodIn(), ClassScope(), v8::internal::ScopeInfo::Create(), and v8::internal::interpreter::BytecodeGenerator::GenerateBaseConstructorBody().
class_variable()
Variable* v8::internal::ClassScope::class_variable () [inline]
Definition at line 1464 of file scopes.h.
{ return class_variable_; }
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateBrandCheck(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateMethodIn(), v8::internal::ScopeInfo::Create(), v8::internal::ParserBase< Impl >::ParseClassLiteral(), v8::internal::BaseConsumedPreparseData< Data >::RestoreDataForScope(), and v8::internal::Parser::RewriteClassLiteral().
DeclareBrandVariable()
Variable * v8::internal::ClassScope::DeclareBrandVariable (AstValueFactory * ast_value_factory, IsStaticFlag is_static_flag, int class_token_pos)
Definition at line 3202 of file scopes.cc.
                                                                {
  DCHECK_IMPLIES(GetRareData() != nullptr, GetRareData()->brand == nullptr);
  bool was_added;
  Variable* brand = Declare(zone(), ast_value_factory->dot_brand_string(),
                            VariableMode::kConst, NORMAL_VARIABLE,
                            InitializationFlag::kNeedsInitialization,
                            MaybeAssignedFlag::kNotAssigned, &was_added);
  DCHECK(was_added);
  brand->set_is_static_flag(is_static_flag);
  brand->ForceContextAllocation();
  brand->set_is_used();
  EnsureRareData()->brand = brand;
  brand->set_initializer_position(class_token_pos);
  return brand;
}
References v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::Scope::Declare(), v8::internal::Variable::ForceContextAllocation(), v8::internal::kConst, v8::internal::kNeedsInitialization, v8::internal::kNotAssigned, v8::internal::NORMAL_VARIABLE, v8::internal::Variable::set_initializer_position(), v8::internal::Variable::set_is_static_flag(), v8::internal::Variable::set_is_used(), and v8::internal::Scope::zone().
Referenced by v8::internal::ParserBase< Impl >::ParseClassLiteral().
DeclareClassVariable()
Variable * v8::internal::ClassScope::DeclareClassVariable (AstValueFactory * ast_value_factory, const AstRawString * name, int class_token_pos)
Definition at line 3220 of file scopes.cc.
                                                                {
  DCHECK_NULL(class_variable_);
  DCHECK_NOT_NULL(name);
  bool was_added;
  class_variable_ =
      Declare(zone(), name->IsEmpty() ? ast_value_factory->dot_string() : name,
              VariableMode::kConst, NORMAL_VARIABLE,
              InitializationFlag::kNeedsInitialization,
              MaybeAssignedFlag::kMaybeAssigned, &was_added);
  DCHECK(was_added);
  class_variable_->set_initializer_position(class_token_pos);
  return class_variable_;
}
References v8::internal::DCHECK(), DCHECK_NOT_NULL, DCHECK_NULL, v8::internal::Scope::Declare(), v8::internal::kConst, v8::internal::kMaybeAssigned, v8::internal::kNeedsInitialization, v8::internal::name, v8::internal::NORMAL_VARIABLE, and v8::internal::Scope::zone().
Referenced by ClassScope(), v8::internal::Parser::DeclareClassVariable(), and v8::internal::BaseConsumedPreparseData< Data >::RestoreDataForScope().
DeclarePrivateName()
Variable * v8::internal::ClassScope::DeclarePrivateName (const AstRawString * name, VariableMode mode, IsStaticFlag is_static_flag, bool * was_added)
Definition at line 2983 of file scopes.cc.
                                                          {
  Variable* result = EnsureRareData()->private_name_map.Declare(
      zone(), this, name, mode, NORMAL_VARIABLE,
      InitializationFlag::kNeedsInitialization, MaybeAssignedFlag::kNotAssigned,
      is_static_flag, was_added);
  if (*was_added) {
    locals_.Add(result);
    has_static_private_methods_ |=
        (result->is_static() &&
         IsPrivateMethodOrAccessorVariableMode(result->mode()));
  } else if (IsComplementaryAccessorPair(result->mode(), mode) &&
             result->is_static_flag() == is_static_flag) {
    *was_added = true;
    result->set_mode(VariableMode::kPrivateGetterAndSetter);
  }
  result->ForceContextAllocation();
  return result;
}
References v8::internal::IsComplementaryAccessorPair(), v8::internal::IsPrivateMethodOrAccessorVariableMode(), v8::internal::kNeedsInitialization, v8::internal::kNotAssigned, v8::internal::kPrivateGetterAndSetter, v8::internal::Scope::locals_, mode(), v8::internal::name, v8::internal::NORMAL_VARIABLE, v8::base::internal::result, and v8::internal::Scope::zone().
Referenced by v8::internal::Parser::CreatePrivateNameVariable().
EnsureRareData()
RareData* v8::internal::ClassScope::EnsureRareData () [inline], [private]
Definition at line 1519 of file scopes.h.
                                       {
    if (GetRareData() == nullptr) {
      rare_data_and_is_parsing_heritage_.SetPointer(
          zone()->New<RareData>(zone()));
    }
    return GetRareData();
  }
References v8::internal::Scope::zone().
Referenced by v8::internal::PrivateNameScopeIterator::AddUnresolvedPrivateName(), and ClassScope().
GetRareData()
RareData* v8::internal::ClassScope::GetRareData () [inline], [private]
Definition at line 1516 of file scopes.h.
                                    {
    return rare_data_and_is_parsing_heritage_.GetPointer();
  }
GetUnresolvedPrivateNameTail()
UnresolvedList::Iterator v8::internal::ClassScope::GetUnresolvedPrivateNameTail ()
Definition at line 3013 of file scopes.cc.
                                                                {
  RareData* rare_data = GetRareData();
  if (rare_data == nullptr) {
    return UnresolvedList::Iterator();
  }
  return rare_data->unresolved_private_names.end();
}
References v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::end(), and v8::internal::ClassScope::RareData::unresolved_private_names.
Referenced by v8::internal::Parser::SkipFunction().
has_static_private_methods()
bool v8::internal::ClassScope::has_static_private_methods () const [inline]
Definition at line 1472 of file scopes.h.
                                          {
    return has_static_private_methods_;
  }
is_anonymous_class()
bool v8::internal::ClassScope::is_anonymous_class () const [inline]
Definition at line 1490 of file scopes.h.
{ return is_anonymous_class_; }
Referenced by v8::internal::BaseConsumedPreparseData< Data >::RestoreDataForScope().
IsParsingHeritage()
bool v8::internal::ClassScope::IsParsingHeritage () [inline]
Definition at line 1466 of file scopes.h.
                                     {
    return rare_data_and_is_parsing_heritage_.GetPayload();
  }
Referenced by v8::internal::PrivateNameScopeIterator::PrivateNameScopeIterator(), and v8::internal::Scope::Scope().
LookupLocalPrivateName()
Variable * v8::internal::ClassScope::LookupLocalPrivateName (const AstRawString * name) [private]
Definition at line 3005 of file scopes.cc.
                                                                     {
  RareData* rare_data = GetRareData();
  if (rare_data == nullptr) {
    return nullptr;
  }
  return rare_data->private_name_map.Lookup(name);
}
References v8::internal::VariableMap::Lookup(), v8::internal::name, and v8::internal::ClassScope::RareData::private_name_map.
Referenced by LookupPrivateName().
LookupPrivateName()
Variable * v8::internal::ClassScope::LookupPrivateName (VariableProxy * proxy) [private]
Definition at line 3092 of file scopes.cc.
                                                            {
  DCHECK(!proxy->is_resolved());
  for (PrivateNameScopeIterator scope_iter(this); !scope_iter.Done();
       scope_iter.Next()) {
    ClassScope* scope = scope_iter.GetScope();
    // Try finding it in the private name map first, if it can't be found,
    // try the deserialized scope info.
    Variable* var = scope->LookupLocalPrivateName(proxy->raw_name());
    if (var == nullptr && !scope->scope_info_.is_null()) {
      var = scope->LookupPrivateNameInScopeInfo(proxy->raw_name());
    }
    if (var != nullptr) {
      return var;
    }
  }
  return nullptr;
}
References v8::internal::DCHECK(), v8::internal::PrivateNameScopeIterator::Done(), v8::internal::VariableProxy::is_resolved(), LookupLocalPrivateName(), LookupPrivateNameInScopeInfo(), v8::internal::VariableProxy::raw_name(), and v8::internal::Scope::scope_info_.
LookupPrivateNameInScopeInfo()
Variable * v8::internal::ClassScope::LookupPrivateNameInScopeInfo (const AstRawString * name) [private]
Definition at line 3067 of file scopes.cc.
                                                                           {
  DCHECK(!scope_info_.is_null());
  DCHECK_NULL(LookupLocalPrivateName(name));
  DisallowGarbageCollection no_gc;
  VariableLookupResult lookup_result;
  int index = scope_info_->ContextSlotIndex(*name->string(), &lookup_result);
  if (index < 0) {
    return nullptr;
  }
  DCHECK(IsImmutableLexicalOrPrivateVariableMode(lookup_result.mode));
  DCHECK_EQ(lookup_result.init_flag, InitializationFlag::kNeedsInitialization);
  DCHECK_EQ(lookup_result.maybe_assigned_flag, MaybeAssignedFlag::kNotAssigned);
  // Add the found private name to the map to speed up subsequent
  // lookups for the same name.
  bool was_added;
  Variable* var = DeclarePrivateName(name, lookup_result.mode,
                                     lookup_result.is_static_flag, &was_added);
  DCHECK(was_added);
  var->AllocateTo(VariableLocation::CONTEXT, index);
  return var;
}
References v8::internal::Variable::AllocateTo(), v8::internal::CONTEXT, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NULL, v8::internal::index, v8::internal::VariableLookupResult::init_flag, v8::internal::VariableLookupResult::is_static_flag, v8::internal::IsImmutableLexicalOrPrivateVariableMode(), v8::internal::kNeedsInitialization, v8::internal::kNotAssigned, v8::internal::VariableLookupResult::maybe_assigned_flag, v8::internal::VariableLookupResult::mode, v8::internal::name, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::Scope::scope_info_.
Referenced by LookupPrivateName().
MigrateUnresolvedPrivateNameTail()
void v8::internal::ClassScope::MigrateUnresolvedPrivateNameTail (AstNodeFactory * ast_node_factory, UnresolvedList::Iterator tail)
Definition at line 3037 of file scopes.cc.
                                                                   {
  RareData* rare_data = GetRareData();
  if (rare_data == nullptr ||
      rare_data->unresolved_private_names.end() == tail) {
    return;
  }
  UnresolvedList migrated_names;
  // If the saved tail is empty, the list used to be empty, so we should
  // migrate everything after the head.
  bool tail_is_empty = tail == UnresolvedList::Iterator();
  UnresolvedList::Iterator it =
      tail_is_empty ? rare_data->unresolved_private_names.begin() : tail;
  for (; it != rare_data->unresolved_private_names.end(); ++it) {
    VariableProxy* proxy = *it;
    VariableProxy* copy = ast_node_factory->CopyVariableProxy(proxy);
    migrated_names.Add(copy);
  }
  // Replace with the migrated copies.
  if (tail_is_empty) {
    rare_data->unresolved_private_names.Clear();
  } else {
    rare_data->unresolved_private_names.Rewind(tail);
  }
  rare_data->unresolved_private_names.Append(std::move(migrated_names));
}
References v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Add(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Append(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::begin(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Clear(), v8::internal::AstNodeFactory::CopyVariableProxy(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::end(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Rewind(), and v8::internal::ClassScope::RareData::unresolved_private_names.
Referenced by v8::internal::Parser::SkipFunction().
RedeclareSyntheticContextVariable()
Variable* v8::internal::ClassScope::RedeclareSyntheticContextVariable (const AstRawString * name)
ResetUnresolvedPrivateNameTail()
void v8::internal::ClassScope::ResetUnresolvedPrivateNameTail (UnresolvedList::Iterator tail)
Definition at line 3021 of file scopes.cc.
                                                                           {
  RareData* rare_data = GetRareData();
  if (rare_data == nullptr ||
      rare_data->unresolved_private_names.end() == tail) {
    return;
  }
  bool tail_is_empty = tail == UnresolvedList::Iterator();
  if (tail_is_empty) {
    // If the saved tail is empty, the list used to be empty, so clear it.
    rare_data->unresolved_private_names.Clear();
  } else {
    rare_data->unresolved_private_names.Rewind(tail);
  }
}
References v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Clear(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::end(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Rewind(), and v8::internal::ClassScope::RareData::unresolved_private_names.
Referenced by v8::internal::Parser::SkipFunction().
ResolvePrivateNames()
bool v8::internal::ClassScope::ResolvePrivateNames (ParseInfo * info)
Definition at line 3111 of file scopes.cc.
                                                    {
  RareData* rare_data = GetRareData();
  if (rare_data == nullptr || rare_data->unresolved_private_names.is_empty()) {
    return true;
  }
  UnresolvedList& list = rare_data->unresolved_private_names;
  for (VariableProxy* proxy : list) {
    Variable* var = LookupPrivateName(proxy);
    if (var == nullptr) {
      // It's only possible to fail to resolve private names here if
      // this is at the top level or the private name is accessed through eval.
      DCHECK(info->flags().is_eval() || outer_scope_->is_script_scope());
      Scanner::Location loc = proxy->location();
      info->pending_error_handler()->ReportMessageAt(
          loc.beg_pos, loc.end_pos,
          MessageTemplate::kInvalidPrivateFieldResolution, proxy->raw_name());
      return false;
    } else {
      proxy->BindTo(var);
    }
  }
  // By now all unresolved private names should be resolved so
  // clear the list.
  list.Clear();
  return true;
}
References v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Clear(), v8::internal::DCHECK(), v8::internal::ParseInfo::flags(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::is_empty(), v8::internal::Scope::is_script_scope(), v8::internal::loc, v8::internal::Scope::outer_scope_, v8::internal::ParseInfo::pending_error_handler(), v8::internal::PendingCompilationErrorHandler::ReportMessageAt(), and v8::internal::ClassScope::RareData::unresolved_private_names.
Referenced by v8::internal::DeclarationScope::AllocateVariables().
ResolvePrivateNamesPartially()
VariableProxy * v8::internal::ClassScope::ResolvePrivateNamesPartially ()
Definition at line 3140 of file scopes.cc.
                                                        {
  RareData* rare_data = GetRareData();
  if (rare_data == nullptr || rare_data->unresolved_private_names.is_empty()) {
    return nullptr;
  }
  PrivateNameScopeIterator private_name_scope_iter(this);
  private_name_scope_iter.Next();
  UnresolvedList& unresolved = rare_data->unresolved_private_names;
  bool has_private_names = rare_data->private_name_map.capacity() > 0;
  // If the class itself does not have private names, nor does it have
  // an outer private name scope, then we are certain any private name access
  // inside cannot be resolved.
  if (!has_private_names && private_name_scope_iter.Done() &&
      !unresolved.is_empty()) {
    return unresolved.first();
  }
  for (VariableProxy* proxy = unresolved.first(); proxy != nullptr;) {
    DCHECK(proxy->IsPrivateName());
    VariableProxy* next = proxy->next_unresolved();
    unresolved.Remove(proxy);
    Variable* var = nullptr;
    // If we can find private name in the current class scope, we can bind
    // them immediately because it's going to shadow any outer private names.
    if (has_private_names) {
      var = LookupLocalPrivateName(proxy->raw_name());
      if (var != nullptr) {
        var->set_is_used();
        proxy->BindTo(var);
        // If the variable being accessed is a static private method, we need to
        // save the class variable in the context to check that the receiver is
        // the class during runtime.
        has_explicit_static_private_methods_access_ |=
            (var->is_static() &&
             IsPrivateMethodOrAccessorVariableMode(var->mode()));
      }
    }
    // If the current scope does not have declared private names,
    // try looking from the outer class scope later.
    if (var == nullptr) {
      // There's no outer private name scope so we are certain that the variable
      // cannot be resolved later.
      if (private_name_scope_iter.Done()) {
        return proxy;
      }
      // The private name may be found later in the outer private name scope, so
      // push it to the outer scope.
      private_name_scope_iter.AddUnresolvedPrivateName(proxy);
    }
    proxy = next;
  }
  DCHECK(unresolved.is_empty());
  return nullptr;
}
References v8::internal::PrivateNameScopeIterator::AddUnresolvedPrivateName(), v8::base::TemplateHashMapImpl< Key, Value, MatchFun, AllocationPolicy >::capacity(), v8::internal::DCHECK(), v8::internal::PrivateNameScopeIterator::Done(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::first(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::is_empty(), v8::internal::Variable::is_static(), v8::internal::IsPrivateMethodOrAccessorVariableMode(), v8::internal::Variable::mode(), v8::internal::PrivateNameScopeIterator::Next(), v8::internal::VariableProxy::next_unresolved(), v8::internal::ClassScope::RareData::private_name_map, v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Remove(), v8::internal::Variable::set_is_used(), and v8::internal::ClassScope::RareData::unresolved_private_names.
Referenced by v8::internal::ParserBase< Impl >::ParseClassLiteral().
set_should_save_class_variable()
void v8::internal::ClassScope::set_should_save_class_variable () [inline]
Definition at line 1493 of file scopes.h.
{ should_save_class_variable_ = true; }
Referenced by v8::internal::BaseConsumedPreparseData< Data >::RestoreDataForScope().
SetIsParsingHeritage()
void v8::internal::ClassScope::SetIsParsingHeritage (bool v) [inline], [private]
Definition at line 1526 of file scopes.h.
                                              {
    rare_data_and_is_parsing_heritage_.SetPayload(v);
  }
should_save_class_variable()
bool v8::internal::ClassScope::should_save_class_variable () const [inline]
Definition at line 1483 of file scopes.h.
                                          {
    return should_save_class_variable_ ||
           has_explicit_static_private_methods_access_ ||
           (has_static_private_methods_ && inner_scope_calls_eval_);
  }
References v8::internal::Scope::inner_scope_calls_eval_.
Referenced by v8::internal::ScopeInfo::Create(), v8::internal::ParserBase< Impl >::ParseClassLiteral(), and v8::internal::PreparseDataBuilder::SaveDataForScope().
Friends And Related Function Documentation
PrivateNameScopeIterator
friend class PrivateNameScopeIterator [friend]
Definition at line 1497 of file scopes.h.
Scope
friend class Scope [friend]
Definition at line 1496 of file scopes.h.
Member Data Documentation
class_variable_
Variable* v8::internal::ClassScope::class_variable_ = nullptr [private]
Definition at line 1532 of file scopes.h.
has_explicit_static_private_methods_access_
bool v8::internal::ClassScope::has_explicit_static_private_methods_access_ [private]
Definition at line 1536 of file scopes.h.
has_static_private_methods_
bool v8::internal::ClassScope::has_static_private_methods_ [private]
Definition at line 1535 of file scopes.h.
is_anonymous_class_
bool v8::internal::ClassScope::is_anonymous_class_ [private]
Definition at line 1537 of file scopes.h.
rare_data_and_is_parsing_heritage_
base::PointerWithPayload<RareData, bool, 1> v8::internal::ClassScope::rare_data_and_is_parsing_heritage_ [private]
Definition at line 1531 of file scopes.h.
should_save_class_variable_
bool v8::internal::ClassScope::should_save_class_variable_ [private]
Definition at line 1540 of file scopes.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ast/scopes.h
/mnt/V8SourceCode/src/ast/scopes.cc