v8::internal::HeapNumberRequest Class Reference
#include <assembler.h>
Public Member Functions
HeapNumberRequest (double heap_number, int offset=-1)
double heap_number () const
int offset () const
void set_offset (int offset)
Private Attributes
double value_
int offset_
Detailed Description
Definition at line 165 of file assembler.h.
Constructor & Destructor Documentation
HeapNumberRequest()
v8::internal::HeapNumberRequest::HeapNumberRequest (double heap_number, int offset = -1) [explicit]
Definition at line 224 of file assembler.cc.
    : offset_(offset) {
  value_ = heap_number;
  DCHECK(!IsSmiDouble(value_));
}
References v8::internal::DCHECK(), heap_number(), v8::internal::IsSmiDouble(), and value_.
Member Function Documentation
heap_number()
double v8::internal::HeapNumberRequest::heap_number () const [inline]
Definition at line 169 of file assembler.h.
{ return value_; }
References value_.
Referenced by HeapNumberRequest().
offset()
int v8::internal::HeapNumberRequest::offset () const [inline]
Definition at line 172 of file assembler.h.
                     {
    DCHECK_GE(offset_, 0);
    return offset_;
  }
References DCHECK_GE, and offset_.
Referenced by set_offset().
set_offset()
void v8::internal::HeapNumberRequest::set_offset (int offset) [inline]
Definition at line 176 of file assembler.h.
                              {
    DCHECK_LT(offset_, 0);
    offset_ = offset;
    DCHECK_GE(offset_, 0);
  }
References DCHECK_GE, DCHECK_LT, offset(), and offset_.
Referenced by v8::internal::AssemblerBase::RequestHeapNumber().
Member Data Documentation
offset_
int v8::internal::HeapNumberRequest::offset_ [private]
Definition at line 184 of file assembler.h.
Referenced by offset(), and set_offset().
value_
double v8::internal::HeapNumberRequest::value_ [private]
Definition at line 183 of file assembler.h.
Referenced by heap_number(), and HeapNumberRequest().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/assembler.h
/mnt/V8SourceCode/src/codegen/assembler.cc