v8::internal::DoubleStringCache Class Reference
#include <number-string-cache.h>
Classes
class BodyDescriptor
struct Entry
Public Types
using Header = HeapObjectLayout
Public Member Functions
uint32_t capacity () const
void Clear ()
uint32_t GetUsedEntriesCount ()
void Print (const char *comment)
InternalIndex GetEntryFor (uint64_t number_bits) const
int AllocatedSize () const
Static Public Member Functions
static InternalIndex GetEntryFor (Isolate *isolate, uint64_t number_bits)
static Handle< Object > Get (Isolate *isolate, InternalIndex entry, uint64_t number_bits)
static void Set (Isolate *isolate, InternalIndex entry, uint64_t number_bits, DirectHandle< String > string)
template<class IsolateT >
static DirectHandle< DoubleStringCache > New (IsolateT *isolate, int capacity)
static constexpr int SizeFor (int length)
static constexpr int OffsetOfElementAt (int index)
Public Attributes
V8_OBJECT struct v8::internal::DoubleStringCache::Entry V8_OBJECT_END
Static Public Attributes
static constexpr Tagged< Smi > kEmptySentinel = Smi::zero()
static constexpr int kInitialSize = 128
static constexpr int kMaxCapacity = TAGGED_SIZE_8_BYTES ? 0x1000 : 0x2000
Private Member Functions
Entry * begin ()
const Entry * begin () const
Entry * end ()
const Entry * end () const
FLEXIBLE_ARRAY_MEMBER (Entry, entries)
Static Private Member Functions
static InternalIndex GetEntryFor (uint64_t number_bits, uint32_t capacity)
Private Attributes
uint32_t capacity_
Friends
class CodeStubAssembler
Detailed Description
Definition at line 74 of file number-string-cache.h.
Member Typedef Documentation
Header
using v8::internal::DoubleStringCache::Header = HeapObjectLayout
Definition at line 81 of file number-string-cache.h.
Member Function Documentation
AllocatedSize()
int v8::internal::DoubleStringCache::AllocatedSize () const [inline]
Definition at line 124 of file number-string-cache.h.
{ return SizeFor(this->capacity()); }
References capacity(), and SizeFor().
begin() [1/2]
Entry* v8::internal::DoubleStringCache::begin () [inline], [private]
Definition at line 141 of file number-string-cache.h.
{ return &entries()[0]; }
Referenced by Clear().
begin() [2/2]
const Entry* v8::internal::DoubleStringCache::begin () const [inline], [private]
Definition at line 142 of file number-string-cache.h.
{ return &entries()[0]; }
capacity()
uint32_t v8::internal::DoubleStringCache::capacity () const [inline]
Definition at line 89 of file number-string-cache.h.
{ return capacity_; }
References capacity_.
Referenced by AllocatedSize(), Clear(), GetEntryFor(), and New().
Clear()
void v8::internal::DoubleStringCache::Clear () [inline]
Definition at line 210 of file number-string-cache-inl.h.
                              {
  static_assert(sizeof(Entry) % kTaggedSize == 0);
  auto* data = reinterpret_cast<Tagged_t*>(begin());
  MemsetTagged(data, kEmptySentinel,
               capacity() * (sizeof(Entry) / kTaggedSize));
}
References begin(), capacity(), kEmptySentinel, v8::internal::kTaggedSize, and v8::internal::MemsetTagged().
end() [1/2]
Entry* v8::internal::DoubleStringCache::end () [inline], [private]
Definition at line 143 of file number-string-cache.h.
{ return &entries()[capacity_]; }
References capacity_.
end() [2/2]
const Entry* v8::internal::DoubleStringCache::end () const [inline], [private]
Definition at line 144 of file number-string-cache.h.
{ return &entries()[capacity_]; }
References capacity_.
FLEXIBLE_ARRAY_MEMBER()
v8::internal::DoubleStringCache::FLEXIBLE_ARRAY_MEMBER (Entry , entries) [private]
Get()
Handle< Object > v8::internal::DoubleStringCache::Get (Isolate * isolate, InternalIndex entry, uint64_t number_bits) [inline], [static]
Definition at line 132 of file number-string-cache-inl.h.
                                                            {
  DisallowGarbageCollection no_gc;
  Factory* factory = isolate->factory();
  DirectHandle<DoubleStringCache> cache = factory->double_string_cache();
  auto& entry = cache->entries()[entry_index.as_uint32()];
  const bool match = entry.key_.value_as_bits() == number_bits;
  if (V8_UNLIKELY(v8_flags.native_code_counters)) {
    Counters* counters = isolate->counters();
    counters->number_string_cache_double_probes()->Increment();
    if (!match) {
      counters->number_string_cache_double_misses()->Increment();
    }
  }
  if (match) {
    auto string = Cast<String>(entry.value_.load());
    return handle(string, isolate);
  }
  return factory->undefined_value();
}
References v8::internal::InternalIndex::as_uint32(), v8::internal::Isolate::counters(), v8::internal::Isolate::factory(), v8::internal::handle(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::internal::FactoryBase< Impl >::DoubleToString().
GetEntryFor() [1/3]
InternalIndex v8::internal::DoubleStringCache::GetEntryFor (Isolate * isolate, uint64_t number_bits) [inline], [static]
Definition at line 126 of file number-string-cache-inl.h.
                                                                   {
  return isolate->factory()->double_string_cache()->GetEntryFor(number_bits);
}
References v8::internal::Isolate::factory().
GetEntryFor() [2/3]
InternalIndex v8::internal::DoubleStringCache::GetEntryFor (uint64_t number_bits) const [inline]
Definition at line 121 of file number-string-cache-inl.h.
                                                                       {
  return GetEntryFor(number_bits, capacity());
}
References capacity().
Referenced by v8::internal::FactoryBase< Impl >::DoubleToString().
GetEntryFor() [3/3]
InternalIndex v8::internal::DoubleStringCache::GetEntryFor (uint64_t number_bits, uint32_t capacity) [inline], [static], [private]
Definition at line 113 of file number-string-cache-inl.h.
                                                                {
  uint32_t hash = static_cast<uint32_t>(number_bits) ^
                  static_cast<uint32_t>(number_bits >> 32);
  uint32_t mask = capacity - 1;
  return InternalIndex{hash & mask};
}
References capacity().
GetUsedEntriesCount()
uint32_t v8::internal::DoubleStringCache::GetUsedEntriesCount ()
Definition at line 39 of file number-string-cache.cc.
                                                {
  uint32_t count = 0;
  for (auto& entry : *this) {
    if (entry.value_.load() != kEmptySentinel) {
      ++count;
    }
  }
  return count;
}
References kEmptySentinel.
New()
template<class IsolateT >
DirectHandle< DoubleStringCache > v8::internal::DoubleStringCache::New (IsolateT * isolate, int capacity) [inline], [static]
Definition at line 189 of file number-string-cache-inl.h.
                                                                     {
  DCHECK_GE(capacity, kInitialSize);
  DCHECK_LE(capacity, kMaxCapacity);
  Tagged<DoubleStringCache> xs =
      UncheckedCast<DoubleStringCache>(isolate->factory()->AllocateRawArray(
          SizeFor(capacity), AllocationType::kOld));
  ReadOnlyRoots roots{isolate};
  xs->set_map_after_allocation(isolate, roots.double_string_cache_map(),
                               SKIP_WRITE_BARRIER);
  xs->capacity_ = capacity;
#if TAGGED_SIZE_8_BYTES
  xs->optional_padding_ = 0;
#endif
  xs->Clear();
  return handle(xs, isolate);
}
References capacity(), DCHECK_GE, DCHECK_LE, v8::internal::handle(), kInitialSize, kMaxCapacity, v8::internal::kOld, SizeFor(), and v8::internal::SKIP_WRITE_BARRIER.
Referenced by v8::internal::Heap::CreateInitialMutableObjects(), and Set().
OffsetOfElementAt()
static constexpr int v8::internal::DoubleStringCache::OffsetOfElementAt (int index) [inline], [static], [constexpr]
Definition at line 129 of file number-string-cache.h.
                                                           {
    return sizeof(Header) + kUInt32Size + index * sizeof(Entry);
  }
References v8::internal::index, and v8::internal::kUInt32Size.
Referenced by SizeFor().
Print()
void v8::internal::DoubleStringCache::Print (const char * comment)
Definition at line 49 of file number-string-cache.cc.
                                                 {
#ifdef OBJECT_PRINT
  StdoutStream os;
  os << comment << "\n";
  DoubleStringCachePrint(os);
#endif
}
Set()
void v8::internal::DoubleStringCache::Set (Isolate * isolate, InternalIndex entry, uint64_t number_bits, DirectHandle< String > string) [inline], [static]
Definition at line 158 of file number-string-cache-inl.h.
                                                                               {
  DirectHandle<DoubleStringCache> cache =
      isolate->factory()->double_string_cache();
  DCHECK_EQ(entry_index, cache->GetEntryFor(number_bits));
  auto* entry = &cache->entries()[entry_index.as_uint32()];
  // Switch to full-size mode if the entry is already occupied.
  if (cache->capacity() == kInitialSize &&
      entry->value_.load() != kEmptySentinel &&
      !isolate->MemorySaverModeEnabled()) {
    // Allocate full-size cache, recompute the entry and proceed with adding
    // the entry.
    uint32_t full_size =
        base::bits::RoundUpToPowerOfTwo32(v8_flags.double_string_cache_size);
    CHECK_LT(kInitialSize, full_size);
    CHECK_LE(full_size, kMaxCapacity);
    cache = DoubleStringCache::New(isolate, full_size);
    isolate->heap()->SetDoubleStringCache(*cache);
    entry_index = cache->GetEntryFor(number_bits);
    entry = &cache->entries()[entry_index.as_uint32()];
  }
  DisallowGarbageCollection no_gc;
  entry->key_.set_value_as_bits(number_bits);
  entry->value_.store(&**cache, *string);
}
References v8::internal::InternalIndex::as_uint32(), CHECK_LE, CHECK_LT, DCHECK_EQ, v8::internal::Isolate::factory(), v8::internal::Isolate::heap(), kEmptySentinel, kInitialSize, kMaxCapacity, v8::internal::Isolate::MemorySaverModeEnabled(), New(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Heap::SetDoubleStringCache(), and v8::internal::v8_flags.
Referenced by v8::internal::FactoryBase< Impl >::DoubleToString().
SizeFor()
static constexpr int v8::internal::DoubleStringCache::SizeFor (int length) [inline], [static], [constexpr]
Definition at line 126 of file number-string-cache.h.
                                                  {
    return OBJECT_POINTER_ALIGN(OffsetOfElementAt(length));
  }
References v8::internal::length, OBJECT_POINTER_ALIGN, and OffsetOfElementAt().
Referenced by AllocatedSize(), New(), and v8::internal::HeapObject::SizeFromMap().
Friends And Related Function Documentation
CodeStubAssembler
friend class CodeStubAssembler [friend]
Definition at line 136 of file number-string-cache.h.
Member Data Documentation
capacity_
uint32_t v8::internal::DoubleStringCache::capacity_ [private]
Definition at line 146 of file number-string-cache.h.
Referenced by capacity(), and end().
kEmptySentinel
constexpr Tagged<Smi> v8::internal::DoubleStringCache::kEmptySentinel = Smi::zero() [static], [constexpr]
Definition at line 84 of file number-string-cache.h.
Referenced by Clear(), GetUsedEntriesCount(), v8::internal::CodeStubAssembler::LoadDoubleStringCacheEntryValue(), and Set().
kInitialSize
constexpr int v8::internal::DoubleStringCache::kInitialSize = 128 [static], [constexpr]
Definition at line 86 of file number-string-cache.h.
Referenced by v8::internal::Heap::CreateInitialMutableObjects(), New(), and Set().
kMaxCapacity
constexpr int v8::internal::DoubleStringCache::kMaxCapacity = TAGGED_SIZE_8_BYTES ? 0x1000 : 0x2000 [static], [constexpr]
Definition at line 87 of file number-string-cache.h.
Referenced by New(), and Set().
V8_OBJECT_END
V8_OBJECT struct v8::internal::DoubleStringCache::Entry v8::internal::DoubleStringCache::V8_OBJECT_END
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/number-string-cache.h
/mnt/V8SourceCode/src/objects/number-string-cache-inl.h
/mnt/V8SourceCode/src/objects/number-string-cache.cc