v8::internal::AbstractCode Class Reference
#include <abstract-code.h>
Public Member Functions
int SourcePosition (Isolate *isolate, int offset)
int SourceStatementPosition (Isolate *isolate, int offset)
Address InstructionStart (PtrComprCageBase cage_base)
Address InstructionEnd (PtrComprCageBase cage_base)
int InstructionSize (PtrComprCageBase cage_base)
Tagged< TrustedByteArray > SourcePositionTable (Isolate *isolate, Tagged< SharedFunctionInfo > sfi)
void DropStackFrameCache (PtrComprCageBase cage_base)
int SizeIncludingMetadata (PtrComprCageBase cage_base)
bool contains (Isolate *isolate, Address pc)
CodeKind kind (PtrComprCageBase cage_base)
Builtin builtin_id (PtrComprCageBase cage_base)
bool has_instruction_stream (PtrComprCageBase cage_base)
Tagged< Code > GetCode ()
Tagged< BytecodeArray > GetBytecodeArray ()
Private Member Functions
OBJECT_CONSTRUCTORS (AbstractCode, HeapObject)
Additional Inherited Members
Detailed Description
Definition at line 25 of file abstract-code.h.
Member Function Documentation
builtin_id()
Builtin v8::internal::AbstractCode::builtin_id (PtrComprCageBase cage_base) [inline]
Definition at line 97 of file abstract-code-inl.h.
                                                           {
  Tagged<Map> map_object = map(cage_base);
  if (InstanceTypeChecker::IsCode(map_object)) {
    return GetCode()->builtin_id();
  } else {
    DCHECK(InstanceTypeChecker::IsBytecodeArray(map_object));
    return Builtin::kNoBuiltinId;
  }
}
References v8::internal::DCHECK(), GetCode(), and v8::internal::kNoBuiltinId.
contains()
bool v8::internal::AbstractCode::contains (Isolate * isolate, Address pc) [inline]
Definition at line 75 of file abstract-code-inl.h.
                                                                   {
  PtrComprCageBase cage_base(isolate);
  Tagged<Map> map_object = map(cage_base);
  if (InstanceTypeChecker::IsCode(map_object)) {
    return GetCode()->contains(isolate, inner_pointer);
  } else {
    DCHECK(InstanceTypeChecker::IsBytecodeArray(map_object));
    return (address() <= inner_pointer) &&
           (inner_pointer <= address() + Size(cage_base));
  }
}
References v8::internal::HeapObject::address(), v8::internal::DCHECK(), and GetCode().
DropStackFrameCache()
void v8::internal::AbstractCode::DropStackFrameCache (PtrComprCageBase cage_base)
GetBytecodeArray()
Tagged< BytecodeArray > v8::internal::AbstractCode::GetBytecodeArray () [inline]
Definition at line 114 of file abstract-code-inl.h.
                                                     {
  return Cast<BytecodeArray>(*this);
}
Referenced by InstructionEnd(), InstructionStart(), SizeIncludingMetadata(), SourcePosition(), SourcePositionTable(), and SourceStatementPosition().
GetCode()
Tagged< Code > v8::internal::AbstractCode::GetCode () [inline]
Definition at line 112 of file abstract-code-inl.h.
{ return Cast<Code>(*this); }
Referenced by builtin_id(), contains(), has_instruction_stream(), InstructionEnd(), InstructionStart(), kind(), SizeIncludingMetadata(), SourcePosition(), SourcePositionTable(), and SourceStatementPosition().
has_instruction_stream()
bool v8::internal::AbstractCode::has_instruction_stream (PtrComprCageBase cage_base) [inline]
Definition at line 107 of file abstract-code-inl.h.
                                                                    {
  DCHECK(InstanceTypeChecker::IsCode(map(cage_base)));
  return GetCode()->has_instruction_stream();
}
References v8::internal::DCHECK(), and GetCode().
InstructionEnd()
Address v8::internal::AbstractCode::InstructionEnd (PtrComprCageBase cage_base) [inline]
Definition at line 64 of file abstract-code-inl.h.
                                                               {
  Tagged<Map> map_object = map(cage_base);
  if (InstanceTypeChecker::IsCode(map_object)) {
    return GetCode()->instruction_end();
  } else {
    DCHECK(InstanceTypeChecker::IsBytecodeArray(map_object));
    Tagged<BytecodeArray> bytecode_array = GetBytecodeArray();
    return bytecode_array->GetFirstBytecodeAddress() + bytecode_array->length();
  }
}
References v8::internal::DCHECK(), GetBytecodeArray(), and GetCode().
InstructionSize()
int v8::internal::AbstractCode::InstructionSize (PtrComprCageBase cage_base) [inline]
Definition at line 23 of file abstract-code-inl.h.
                                                            {
  Tagged<Map> map_object = map(cage_base);
  if (InstanceTypeChecker::IsCode(map_object)) {
    return GetCode()->instruction_size();
  } else {
    DCHECK(InstanceTypeChecker::IsBytecodeArray(map_object));
    return GetBytecodeArray()->length();
  }
}
References v8::internal::DCHECK().
InstructionStart()
Address v8::internal::AbstractCode::InstructionStart (PtrComprCageBase cage_base) [inline]
Definition at line 54 of file abstract-code-inl.h.
                                                                 {
  Tagged<Map> map_object = map(cage_base);
  if (InstanceTypeChecker::IsCode(map_object)) {
    return GetCode()->instruction_start();
  } else {
    DCHECK(InstanceTypeChecker::IsBytecodeArray(map_object));
    return GetBytecodeArray()->GetFirstBytecodeAddress();
  }
}
References v8::internal::DCHECK(), GetBytecodeArray(), and GetCode().
kind()
CodeKind v8::internal::AbstractCode::kind (PtrComprCageBase cage_base) [inline]
Definition at line 87 of file abstract-code-inl.h.
                                                      {
  Tagged<Map> map_object = map(cage_base);
  if (InstanceTypeChecker::IsCode(map_object)) {
    return GetCode()->kind();
  } else {
    DCHECK(InstanceTypeChecker::IsBytecodeArray(map_object));
    return CodeKind::INTERPRETED_FUNCTION;
  }
}
References v8::internal::DCHECK(), and GetCode().
OBJECT_CONSTRUCTORS()
v8::internal::AbstractCode::OBJECT_CONSTRUCTORS (AbstractCode , HeapObject) [private]
SizeIncludingMetadata()
int v8::internal::AbstractCode::SizeIncludingMetadata (PtrComprCageBase cage_base) [inline]
Definition at line 44 of file abstract-code-inl.h.
                                                                  {
  Tagged<Map> map_object = map(cage_base);
  if (InstanceTypeChecker::IsCode(map_object)) {
    return GetCode()->SizeIncludingMetadata();
  } else {
    DCHECK(InstanceTypeChecker::IsBytecodeArray(map_object));
    return GetBytecodeArray()->SizeIncludingMetadata();
  }
}
References v8::internal::DCHECK(), GetBytecodeArray(), and GetCode().
SourcePosition()
int v8::internal::AbstractCode::SourcePosition (Isolate * isolate, int offset)
Definition at line 12 of file abstract-code.cc.
                                                             {
  PtrComprCageBase cage_base(isolate);
  Tagged<Map> map_object = map(cage_base);
  if (InstanceTypeChecker::IsCode(map_object)) {
    return GetCode()->SourcePosition(offset);
  } else {
    return GetBytecodeArray()->SourcePosition(offset);
  }
}
References GetBytecodeArray(), and GetCode().
SourcePositionTable()
Tagged< TrustedByteArray > v8::internal::AbstractCode::SourcePositionTable (Isolate * isolate, Tagged< SharedFunctionInfo > sfi) [inline]
Definition at line 33 of file abstract-code-inl.h.
                                                      {
  Tagged<Map> map_object = map(isolate);
  if (InstanceTypeChecker::IsCode(map_object)) {
    return GetCode()->SourcePositionTable(isolate, sfi);
  } else {
    DCHECK(InstanceTypeChecker::IsBytecodeArray(map_object));
    return GetBytecodeArray()->SourcePositionTable(isolate);
  }
}
References v8::internal::DCHECK(), GetBytecodeArray(), and GetCode().
SourceStatementPosition()
int v8::internal::AbstractCode::SourceStatementPosition (Isolate * isolate, int offset)
Definition at line 22 of file abstract-code.cc.
                                                                      {
  PtrComprCageBase cage_base(isolate);
  Tagged<Map> map_object = map(cage_base);
  if (InstanceTypeChecker::IsCode(map_object)) {
    return GetCode()->SourceStatementPosition(offset);
  } else {
    return GetBytecodeArray()->SourceStatementPosition(offset);
  }
}
References GetBytecodeArray(), and GetCode().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/abstract-code.h
/mnt/V8SourceCode/src/objects/abstract-code-inl.h
/mnt/V8SourceCode/src/objects/abstract-code.cc