v8::internal::JSNumberFormat Class Reference
#include <js-number-format.h>
Public Types
enum class ShowTrailingZeros { kShow
, kHide
 }
Static Public Member Functions
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSNumberFormat > New (Isolate *isolate, DirectHandle< Map > map, DirectHandle< Object > locales, DirectHandle< Object > options, const char *service)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSNumberFormat > UnwrapNumberFormat (Isolate *isolate, DirectHandle< JSReceiver > format_holder)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > NumberFormatFunction (Isolate *isolate, DirectHandle< JSNumberFormat > number_format, Handle< Object > numeric_obj)
static DirectHandle< JSObject > ResolvedOptions (Isolate *isolate, DirectHandle< JSNumberFormat > number_format)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSArray > FormatToParts (Isolate *isolate, DirectHandle< JSNumberFormat > number_format, Handle< Object > numeric_obj)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > FormatNumericRange (Isolate *isolate, DirectHandle< JSNumberFormat > number_format, Handle< Object > x, Handle< Object > y)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSArray > FormatNumericRangeToParts (Isolate *isolate, DirectHandle< JSNumberFormat > number_format, Handle< Object > x, Handle< Object > y)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > FormatNumeric (Isolate *isolate, const icu::number::LocalizedNumberFormatter &number_format, Handle< Object > numeric_obj)
static V8_EXPORT_PRIVATE const std::set< std::string > & GetAvailableLocales ()
static int32_t MinimumIntegerDigitsFromSkeleton (const icu::UnicodeString &skeleton)
static bool FractionDigitsFromSkeleton (const icu::UnicodeString &skeleton, int32_t *minimum, int32_t *maximum)
static bool SignificantDigitsFromSkeleton (const icu::UnicodeString &skeleton, int32_t *minimum, int32_t *maximum)
static DirectHandle< String > RoundingModeString (Isolate *isolate, const icu::UnicodeString &skeleton)
static DirectHandle< String > RoundingPriorityString (Isolate *isolate, const icu::UnicodeString &skeleton)
static DirectHandle< String > TrailingZeroDisplayString (Isolate *isolate, const icu::UnicodeString &skeleton)
static DirectHandle< Object > RoundingIncrement (Isolate *isolate, const icu::UnicodeString &skeleton)
static icu::number::UnlocalizedNumberFormatter SetDigitOptionsToFormatter (const icu::number::UnlocalizedNumberFormatter &settings, const Intl::NumberFormatDigitOptions &digit_options)
static const icu::UnicodeString NumberingSystemFromSkeleton (const icu::UnicodeString &skeleton)
static V8_WARN_UNUSED_RESULT Maybe< icu::number::LocalizedNumberRangeFormatter > GetRangeFormatter (Isolate *isolate, Tagged< String > locale, const icu::number::LocalizedNumberFormatter &number_formatter)
Detailed Description
Definition at line 42 of file js-number-format.h.
Member Enumeration Documentation
ShowTrailingZeros
enum v8::internal::JSNumberFormat::ShowTrailingZeros [strong]
Enumerator
kShow
kHide
Definition at line 102 of file js-number-format.h.
{ kShow, kHide };
Member Function Documentation
FormatNumeric()
MaybeDirectHandle< String > v8::internal::JSNumberFormat::FormatNumeric (Isolate * isolate, const icu::number::LocalizedNumberFormatter & number_format, Handle< Object > numeric_obj) [static]
Definition at line 2134 of file js-number-format.cc.
                                {
  Maybe<icu::number::FormattedNumber> maybe_format =
      IcuFormatNumber(isolate, number_format, numeric_obj);
  MAYBE_RETURN(maybe_format, DirectHandle<String>());
  icu::number::FormattedNumber formatted = std::move(maybe_format).FromJust();
  return FormatToString(isolate, formatted, number_format, IsNaN(*numeric_obj));
}
References v8::internal::anonymous_namespace{js-number-format.cc}::FormatToString(), v8::internal::anonymous_namespace{js-number-format.cc}::IcuFormatNumber(), v8::internal::IsNaN(), and MAYBE_RETURN.
Referenced by v8::internal::Intl::NumberToLocaleString().
FormatNumericRange()
MaybeDirectHandle< String > v8::internal::JSNumberFormat::FormatNumericRange (Isolate * isolate, DirectHandle< JSNumberFormat > number_format, Handle< Object > x, Handle< Object > y) [static]
Definition at line 2191 of file js-number-format.cc.
                                                {
  return PartitionNumberRangePattern<String, FormatToString>(
      isolate, number_format, x_obj, y_obj,
      "Intl.NumberFormat.prototype.formatRange");
}
FormatNumericRangeToParts()
MaybeDirectHandle< JSArray > v8::internal::JSNumberFormat::FormatNumericRangeToParts (Isolate * isolate, DirectHandle< JSNumberFormat > number_format, Handle< Object > x, Handle< Object > y) [static]
Definition at line 2199 of file js-number-format.cc.
                                                {
  return PartitionNumberRangePattern<JSArray, FormatRangeToJSArray>(
      isolate, number_format, x_obj, y_obj,
      "Intl.NumberFormat.prototype.formatRangeToParts");
}
FormatToParts()
MaybeDirectHandle< JSArray > v8::internal::JSNumberFormat::FormatToParts (Isolate * isolate, DirectHandle< JSNumberFormat > number_format, Handle< Object > numeric_obj) [static]
Definition at line 2169 of file js-number-format.cc.
                                {
  icu::number::LocalizedNumberFormatter* fmt =
      number_format->icu_number_formatter()->raw();
  DCHECK_NOT_NULL(fmt);
  IntlMathematicalValue value;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, value, IntlMathematicalValue::From(isolate, numeric_obj),
      DirectHandle<JSArray>());
  Maybe<icu::number::FormattedNumber> maybe_formatted =
      IntlMathematicalValue::FormatNumeric(isolate, *fmt, value);
  MAYBE_RETURN(maybe_formatted, DirectHandle<JSArray>());
  icu::number::FormattedNumber formatted =
      std::move(maybe_formatted).FromJust();
  return FormatToJSArray(isolate, formatted, *fmt, value.IsNaN(), false);
}
References DCHECK_NOT_NULL, v8::internal::IntlMathematicalValue::FormatNumeric(), v8::internal::anonymous_namespace{js-number-format.cc}::FormatToJSArray(), v8::internal::IntlMathematicalValue::From(), MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, MAYBE_RETURN, and v8::internal::value.
Referenced by v8::internal::BUILTIN().
FractionDigitsFromSkeleton()
bool v8::internal::JSNumberFormat::FractionDigitsFromSkeleton (const icu::UnicodeString & skeleton, int32_t * minimum, int32_t * maximum) [static]
Definition at line 707 of file js-number-format.cc.
                                                                          {
  int32_t index = skeleton.indexOf(".");
  if (index < 0) {
    // https://unicode-org.github.io/icu/userguide/format_parse/numbers/skeletons.html#precision
    // Note that the stem . is considered valid and is equivalent to
    // precision-integer.
    // Also, if there are "precision-increment/" but no "." we consider both
    // minimum and maximum fraction digits as 0.
    if (skeleton.indexOf("precision-integer") >= 0 ||
        skeleton.indexOf("precision-increment/") >= 0) {
      *minimum = *maximum = 0;
      return true;
    }
    return false;
  }
  *minimum = 0;
  index++; // skip the '.'
  while (index < skeleton.length() && IsDecimalDigit(skeleton[index])) {
    (*minimum)++;
    index++;
  }
  *maximum = *minimum;
  while (index < skeleton.length() && skeleton[index] == '#') {
    (*maximum)++;
    index++;
  }
  return true;
}
References v8::internal::index, and v8::internal::IsDecimalDigit().
Referenced by ResolvedOptions(), and v8::internal::JSPluralRules::ResolvedOptions().
GetAvailableLocales()
const std::set< std::string > & v8::internal::JSNumberFormat::GetAvailableLocales () [static]
Definition at line 2216 of file js-number-format.cc.
                                                             {
  static base::LazyInstance<Intl::AvailableLocales<CheckNumberElements>>::type
      available_locales = LAZY_INSTANCE_INITIALIZER;
  return available_locales.Pointer()->Get();
}
References LAZY_INSTANCE_INITIALIZER, and v8::internal::tracing::type.
Referenced by v8::internal::BUILTIN(), v8::internal::JSDurationFormat::GetAvailableLocales(), and New().
GetRangeFormatter()
Maybe< icu::number::LocalizedNumberRangeFormatter > v8::internal::JSNumberFormat::GetRangeFormatter (Isolate * isolate, Tagged< String > locale, const icu::number::LocalizedNumberFormatter & number_formatter) [static]
Definition at line 2115 of file js-number-format.cc.
                                                               {
  UErrorCode status = U_ZERO_ERROR;
  UParseError perror;
  auto locale_str = locale->ToStdString();
  icu::number::LocalizedNumberRangeFormatter range_formatter =
      icu::number::UnlocalizedNumberRangeFormatter()
          .numberFormatterBoth(icu::number::NumberFormatter::forSkeleton(
              number_formatter.toSkeleton(status), perror, status))
          .locale(icu::Locale::forLanguageTag(locale_str, status));
  if (U_FAILURE(status)) {
    THROW_NEW_ERROR_RETURN_VALUE(
        isolate, NewTypeError(MessageTemplate::kIcuError),
        Nothing<icu::number::LocalizedNumberRangeFormatter>());
  }
  return Just(range_formatter);
}
References v8::Just(), v8::internal::status, and THROW_NEW_ERROR_RETURN_VALUE.
Referenced by v8::internal::anonymous_namespace{js-number-format.cc}::PartitionNumberRangePattern(), and v8::internal::JSPluralRules::ResolvePluralRange().
MinimumIntegerDigitsFromSkeleton()
int32_t v8::internal::JSNumberFormat::MinimumIntegerDigitsFromSkeleton (const icu::UnicodeString & skeleton) [static]
Definition at line 676 of file js-number-format.cc.
                                      {
  // count the number of 0 after "integer-width/*"
  icu::UnicodeString search("integer-width/*");
  int32_t index = skeleton.indexOf(search);
  if (index < 0) return 1; // return 1 if cannot find it.
  index += search.length();
  int32_t matched = 0;
  while (index < skeleton.length() && skeleton[index] == '0') {
    matched++;
    index++;
  }
  DCHECK_GT(matched, 0);
  return matched;
}
References DCHECK_GT, v8::internal::index, and v8::internal::anonymous_namespace{simd.cc}::search().
Referenced by ResolvedOptions(), and v8::internal::JSPluralRules::ResolvedOptions().
New()
MaybeDirectHandle< JSNumberFormat > v8::internal::JSNumberFormat::New (Isolate * isolate, DirectHandle< Map > map, DirectHandle< Object > locales, DirectHandle< Object > options, const char * service) [static]
Definition at line 1072 of file js-number-format.cc.
                                                           {
  Factory* factory = isolate->factory();
  // 1. Let requestedLocales be ? CanonicalizeLocaleList(locales).
  Maybe<std::vector<std::string>> maybe_requested_locales =
      Intl::CanonicalizeLocaleList(isolate, locales);
  MAYBE_RETURN(maybe_requested_locales, DirectHandle<JSNumberFormat>());
  std::vector<std::string> requested_locales =
      maybe_requested_locales.FromJust();
  // 2. Set options to ? CoerceOptionsToObject(options).
  DirectHandle<JSReceiver> options;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, options, CoerceOptionsToObject(isolate, options_obj, service));
  // 3. Let opt be a new Record.
  // 4. Let matcher be ? GetOption(options, "localeMatcher", "string", «
  // "lookup", "best fit" », "best fit").
  // 5. Set opt.[[localeMatcher]] to matcher.
  Maybe<Intl::MatcherOption> maybe_locale_matcher =
      Intl::GetLocaleMatcher(isolate, options, service);
  MAYBE_RETURN(maybe_locale_matcher, MaybeDirectHandle<JSNumberFormat>());
  Intl::MatcherOption matcher = maybe_locale_matcher.FromJust();
  std::string numbering_system_str;
  // 6. Let _numberingSystem_ be ? GetOption(_options_, `"numberingSystem"`,
  // `"string"`, *undefined*, *undefined*).
  Maybe<bool> maybe_numberingSystem =
      Intl::GetNumberingSystem(isolate, options, service, numbering_system_str);
  // 7. If _numberingSystem_ is not *undefined*, then
  // 8. If _numberingSystem_ does not match the
  // `(3*8alphanum) *("-" (3*8alphanum))` sequence, throw a *RangeError*
  // exception.
  MAYBE_RETURN(maybe_numberingSystem, MaybeDirectHandle<JSNumberFormat>());
  // 9. Let localeData be %NumberFormat%.[[LocaleData]].
  // 10. Let r be ResolveLocale(%NumberFormat%.[[AvailableLocales]],
  // requestedLocales, opt, %NumberFormat%.[[RelevantExtensionKeys]],
  // localeData).
  Intl::ResolvedLocale r;
  if (!Intl::ResolveLocale(isolate, JSNumberFormat::GetAvailableLocales(),
                           requested_locales, matcher, {"nu"})
           .To(&r)) {
    THROW_NEW_ERROR(isolate, NewRangeError(MessageTemplate::kIcuError));
  }
  icu::Locale icu_locale = r.icu_locale;
  UErrorCode status = U_ZERO_ERROR;
  if (maybe_numberingSystem.FromJust()) {
    auto nu_extension_it = r.extensions.find("nu");
    if (nu_extension_it != r.extensions.end() &&
        nu_extension_it->second != numbering_system_str) {
      icu_locale.setUnicodeKeywordValue("nu", nullptr, status);
      DCHECK(U_SUCCESS(status));
    }
  }
  // 9. Set numberFormat.[[Locale]] to r.[[locale]].
  Maybe<std::string> maybe_locale_str = Intl::ToLanguageTag(icu_locale);
  MAYBE_RETURN(maybe_locale_str, MaybeDirectHandle<JSNumberFormat>());
  DirectHandle<String> locale_str =
      isolate->factory()->NewStringFromAsciiChecked(
          maybe_locale_str.FromJust().c_str());
  if (maybe_numberingSystem.FromJust() &&
      Intl::IsValidNumberingSystem(numbering_system_str)) {
    icu_locale.setUnicodeKeywordValue("nu", numbering_system_str, status);
    DCHECK(U_SUCCESS(status));
  }
  std::string numbering_system = Intl::GetNumberingSystem(icu_locale);
  // 11. Let dataLocale be r.[[dataLocale]].
  icu::number::UnlocalizedNumberFormatter settings =
      icu::number::UnlocalizedNumberFormatter().roundingMode(UNUM_ROUND_HALFUP);
  // For 'latn' numbering system, skip the adoptSymbols which would cause
  // 10.1%-13.7% of regression of JSTests/Intl-NewIntlNumberFormat
  // See crbug/1052751 so we skip calling adoptSymbols and depending on the
  // default instead.
  if (!numbering_system.empty() && numbering_system != "latn") {
    settings = settings.adoptSymbols(icu::NumberingSystem::createInstanceByName(
        numbering_system.c_str(), status));
    DCHECK(U_SUCCESS(status));
  }
  // ==== Start SetNumberFormatUnitOptions ====
  // 3. Let style be ? GetOption(options, "style", "string", « "decimal",
  // "percent", "currency", "unit" », "decimal").
  Maybe<Style> maybe_style = GetStringOption<Style>(
      isolate, options, "style", service,
      std::to_array<const std::string_view>(
          {"decimal", "percent", "currency", "unit"}),
      std::array{Style::DECIMAL, Style::PERCENT, Style::CURRENCY, Style::UNIT},
      Style::DECIMAL);
  MAYBE_RETURN(maybe_style, MaybeDirectHandle<JSNumberFormat>());
  Style style = maybe_style.FromJust();
  // 4. Set intlObj.[[Style]] to style.
  // 5. Let currency be ? GetOption(options, "currency", "string", undefined,
  // undefined).
  DirectHandle<String> currency_str;
  Maybe<bool> found_currency =
      GetStringOption(isolate, options, "currency",
                      std::span<std::string_view>(), service, &currency_str);
  MAYBE_RETURN(found_currency, MaybeDirectHandle<JSNumberFormat>());
  std::string currency;
  // 6. If currency is not undefined, then
  if (found_currency.FromJust()) {
    currency = currency_str->ToStdString();
    // 6. a. If the result of IsWellFormedCurrencyCode(currency) is false,
    // throw a RangeError exception.
    if (!IsWellFormedCurrencyCode(currency)) {
      THROW_NEW_ERROR(
          isolate,
          NewRangeError(MessageTemplate::kInvalid,
                        factory->NewStringFromStaticChars("currency code"),
                        currency_str));
    }
  } else {
    // 7. If style is "currency" and currency is undefined, throw a TypeError
    // exception.
    if (style == Style::CURRENCY) {
      THROW_NEW_ERROR(isolate, NewTypeError(MessageTemplate::kCurrencyCode));
    }
  }
  // 8. Let currencyDisplay be ? GetOption(options, "currencyDisplay",
  // "string", « "code", "symbol", "name", "narrowSymbol" », "symbol").
  Maybe<CurrencyDisplay> maybe_currency_display =
      GetStringOption<CurrencyDisplay>(
          isolate, options, "currencyDisplay", service,
          std::to_array<const std::string_view>(
              {"code", "symbol", "name", "narrowSymbol"}),
          std::array{CurrencyDisplay::CODE, CurrencyDisplay::SYMBOL,
                     CurrencyDisplay::NAME, CurrencyDisplay::NARROW_SYMBOL},
          CurrencyDisplay::SYMBOL);
  MAYBE_RETURN(maybe_currency_display, MaybeDirectHandle<JSNumberFormat>());
  CurrencyDisplay currency_display = maybe_currency_display.FromJust();
  CurrencySign currency_sign = CurrencySign::STANDARD;
  // 9. Let currencySign be ? GetOption(options, "currencySign", "string", «
  // "standard", "accounting" », "standard").
  Maybe<CurrencySign> maybe_currency_sign = GetStringOption<CurrencySign>(
      isolate, options, "currencySign", service,
      std::to_array<const std::string_view>({"standard", "accounting"}),
      std::array{CurrencySign::STANDARD, CurrencySign::ACCOUNTING},
      CurrencySign::STANDARD);
  MAYBE_RETURN(maybe_currency_sign, MaybeDirectHandle<JSNumberFormat>());
  currency_sign = maybe_currency_sign.FromJust();
  // 10. Let unit be ? GetOption(options, "unit", "string", undefined,
  // undefined).
  DirectHandle<String> unit_str;
  Maybe<bool> found_unit =
      GetStringOption(isolate, options, "unit", std::span<std::string_view>(),
                      service, &unit_str);
  MAYBE_RETURN(found_unit, MaybeDirectHandle<JSNumberFormat>());
  std::pair<icu::MeasureUnit, icu::MeasureUnit> unit_pair;
  // 11. If unit is not undefined, then
  if (found_unit.FromJust()) {
    std::string unit_stdstr = unit_str->ToStdString();
    // 11.a If the result of IsWellFormedUnitIdentifier(unit) is false, throw a
    // RangeError exception.
    Maybe<std::pair<icu::MeasureUnit, icu::MeasureUnit>> maybe_wellformed_unit =
        IsWellFormedUnitIdentifier(isolate, unit_stdstr);
    if (maybe_wellformed_unit.IsNothing()) {
      THROW_NEW_ERROR(
          isolate,
          NewRangeError(MessageTemplate::kInvalidUnit,
                        factory->NewStringFromAsciiChecked(service), unit_str));
    }
    unit_pair = maybe_wellformed_unit.FromJust();
  } else {
    // 12. If style is "unit" and unit is undefined, throw a TypeError
    // exception.
    if (style == Style::UNIT) {
      THROW_NEW_ERROR(isolate,
                      NewTypeError(MessageTemplate::kInvalidUnit,
                                   factory->NewStringFromAsciiChecked(service),
                                   factory->empty_string()));
    }
  }
  // 13. Let unitDisplay be ? GetOption(options, "unitDisplay", "string", «
  // "short", "narrow", "long" », "short").
  Maybe<UnitDisplay> maybe_unit_display = GetStringOption<UnitDisplay>(
      isolate, options, "unitDisplay", service,
      std::to_array<const std::string_view>({"short", "narrow", "long"}),
      std::array{UnitDisplay::SHORT, UnitDisplay::NARROW, UnitDisplay::LONG},
      UnitDisplay::SHORT);
  MAYBE_RETURN(maybe_unit_display, MaybeDirectHandle<JSNumberFormat>());
  UnitDisplay unit_display = maybe_unit_display.FromJust();
  // 14. If style is "currency", then
  icu::UnicodeString currency_ustr;
  if (style == Style::CURRENCY) {
    // 14.a. If currency is undefined, throw a TypeError exception.
    if (!found_currency.FromJust()) {
      THROW_NEW_ERROR(isolate, NewTypeError(MessageTemplate::kCurrencyCode));
    }
    // 14.a. Let currency be the result of converting currency to upper case as
    // specified in 6.1
    std::transform(currency.begin(), currency.end(), currency.begin(), toupper);
    currency_ustr = currency.c_str();
    // 14.b. Set numberFormat.[[Currency]] to currency.
    if (!currency_ustr.isEmpty()) {
      DirectHandle<String> currency_string;
      ASSIGN_RETURN_ON_EXCEPTION(isolate, currency_string,
                                 Intl::ToString(isolate, currency_ustr));
      settings =
          settings.unit(icu::CurrencyUnit(currency_ustr.getBuffer(), status));
      DCHECK(U_SUCCESS(status));
      // 14.c Set intlObj.[[CurrencyDisplay]] to currencyDisplay.
      // The default unitWidth is SHORT in ICU and that mapped from
      // Symbol so we can skip the setting for optimization.
      if (currency_display != CurrencyDisplay::SYMBOL) {
        settings = settings.unitWidth(ToUNumberUnitWidth(currency_display));
      }
      DCHECK(U_SUCCESS(status));
    }
  }
  // 15. If style is "unit", then
  if (style == Style::UNIT) {
    // Track newer style "unit".
    isolate->CountUsage(v8::Isolate::UseCounterFeature::kNumberFormatStyleUnit);
    icu::MeasureUnit none = icu::MeasureUnit();
    // 13.b Set intlObj.[[Unit]] to unit.
    if (unit_pair.first != AVOID_AMBIGUOUS_OP_WARNING(none)) {
      settings = settings.unit(unit_pair.first);
    }
    if (unit_pair.second != AVOID_AMBIGUOUS_OP_WARNING(none)) {
      settings = settings.perUnit(unit_pair.second);
    }
    // The default unitWidth is SHORT in ICU and that mapped from
    // Symbol so we can skip the setting for optimization.
    if (unit_display != UnitDisplay::SHORT) {
      settings = settings.unitWidth(ToUNumberUnitWidth(unit_display));
    }
  }
  // === End of SetNumberFormatUnitOptions
  if (style == Style::PERCENT) {
    settings = settings.unit(icu::MeasureUnit::getPercent())
                   .scale(icu::number::Scale::powerOfTen(2));
  }
  Notation notation = Notation::STANDARD;
  // xx. Let notation be ? GetOption(options, "notation", "string", «
  // "standard", "scientific", "engineering", "compact" », "standard").
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, notation,
      GetStringOption<Notation>(
          isolate, options, "notation", service,
          std::to_array<const std::string_view>(
              {"standard", "scientific", "engineering", "compact"}),
          std::array{Notation::STANDARD, Notation::SCIENTIFIC,
                     Notation::ENGINEERING, Notation::COMPACT},
          Notation::STANDARD),
      DirectHandle<JSNumberFormat>());
  // xx. Set numberFormat.[[Notation]] to notation.
  // xx. If style is *"currency"* and *"notation"* is *"standard"*, then
  int mnfd_default, mxfd_default;
  if (style == Style::CURRENCY && notation == Notation::STANDARD) {
    // b. Let cDigits be CurrencyDigits(currency).
    int c_digits = CurrencyDigits(currency_ustr);
    // c. Let mnfdDefault be cDigits.
    // d. Let mxfdDefault be cDigits.
    mnfd_default = c_digits;
    mxfd_default = c_digits;
    // 17. Else,
  } else {
    // a. Let mnfdDefault be 0.
    mnfd_default = 0;
    // b. If style is "percent", then
    if (style == Style::PERCENT) {
      // i. Let mxfdDefault be 0.
      mxfd_default = 0;
    } else {
      // c. Else,
      // i. Let mxfdDefault be 3.
      mxfd_default = 3;
    }
  }
  // 23. Perform ? SetNumberFormatDigitOptions(numberFormat, options,
  // mnfdDefault, mxfdDefault).
  Maybe<Intl::NumberFormatDigitOptions> maybe_digit_options =
      Intl::SetNumberFormatDigitOptions(isolate, options, mnfd_default,
                                        mxfd_default,
                                        notation == Notation::COMPACT, service);
  MAYBE_RETURN(maybe_digit_options, DirectHandle<JSNumberFormat>());
  Intl::NumberFormatDigitOptions digit_options = maybe_digit_options.FromJust();
  // 13. If roundingIncrement is not 1, set mxfdDefault to mnfdDefault.
  if (digit_options.rounding_increment != 1) {
    mxfd_default = mnfd_default;
  }
  // 14. Set intlObj.[[RoundingIncrement]] to roundingIncrement.
  // 15. Set intlObj.[[RoundingMode]] to roundingMode.
  // 16. Set intlObj.[[TrailingZeroDisplay]] to trailingZeroDisplay.
  settings = SetDigitOptionsToFormatter(settings, digit_options);
  // 28. Let compactDisplay be ? GetOption(options, "compactDisplay",
  // "string", « "short", "long" », "short").
  Maybe<CompactDisplay> maybe_compact_display = GetStringOption<CompactDisplay>(
      isolate, options, "compactDisplay", service,
      std::to_array<const std::string_view>({"short", "long"}),
      std::array{CompactDisplay::SHORT, CompactDisplay::LONG},
      CompactDisplay::SHORT);
  MAYBE_RETURN(maybe_compact_display, MaybeDirectHandle<JSNumberFormat>());
  CompactDisplay compact_display = maybe_compact_display.FromJust();
  // The default notation in ICU is Simple, which mapped from STANDARD
  // so we can skip setting it.
  if (notation != Notation::STANDARD) {
    settings = settings.notation(ToICUNotation(notation, compact_display));
  }
  // 28. Let defaultUseGrouping be "auto".
  UseGrouping default_use_grouping = UseGrouping::AUTO;
  // 29. If notation is "compact", then
  if (notation == Notation::COMPACT) {
    // a. Set numberFormat.[[CompactDisplay]] to compactDisplay.
    // Done in above together
    // b. Set defaultUseGrouping to "min2".
    default_use_grouping = UseGrouping::MIN2;
  }
  // 30. Let useGrouping be ? GetStringOrBooleanOption(options, "useGrouping",
  // « "min2", "auto", "always" », "always", false, defaultUseGrouping).
  Maybe<UseGrouping> maybe_use_grouping = GetStringOrBooleanOption<UseGrouping>(
      isolate, options, "useGrouping", service,
      std::to_array<const std::string_view>({"min2", "auto", "always"}),
      std::array{UseGrouping::MIN2, UseGrouping::AUTO, UseGrouping::ALWAYS},
      UseGrouping::ALWAYS, // trueValue
      UseGrouping::OFF, // falseValue
      default_use_grouping); // fallbackValue
  MAYBE_RETURN(maybe_use_grouping, MaybeDirectHandle<JSNumberFormat>());
  UseGrouping use_grouping = maybe_use_grouping.FromJust();
  // 31. Set numberFormat.[[UseGrouping]] to useGrouping.
  if (use_grouping != UseGrouping::AUTO) {
    settings = settings.grouping(ToUNumberGroupingStrategy(use_grouping));
  }
  // 32. Let signDisplay be ? GetOption(options, "signDisplay", "string", «
  // "auto", "never", "always", "exceptZero", "negative" », "auto").
  Maybe<SignDisplay> maybe_sign_display = Nothing<SignDisplay>();
  maybe_sign_display = GetStringOption<SignDisplay>(
      isolate, options, "signDisplay", service,
      std::to_array<const std::string_view>(
          {"auto", "never", "always", "exceptZero", "negative"}),
      std::array{SignDisplay::AUTO, SignDisplay::NEVER, SignDisplay::ALWAYS,
                 SignDisplay::EXCEPT_ZERO, SignDisplay::NEGATIVE},
      SignDisplay::AUTO);
  MAYBE_RETURN(maybe_sign_display, MaybeDirectHandle<JSNumberFormat>());
  SignDisplay sign_display = maybe_sign_display.FromJust();
  // 33. Set numberFormat.[[SignDisplay]] to signDisplay.
  // The default sign in ICU is UNUM_SIGN_AUTO which is mapped from
  // SignDisplay::AUTO and CurrencySign::STANDARD so we can skip setting
  // under that values for optimization.
  if (sign_display != SignDisplay::AUTO ||
      currency_sign != CurrencySign::STANDARD) {
    settings = settings.sign(ToUNumberSignDisplay(sign_display, currency_sign));
  }
  // 25. Let dataLocaleData be localeData.[[<dataLocale>]].
  //
  // 26. Let patterns be dataLocaleData.[[patterns]].
  //
  // 27. Assert: patterns is a record (see 11.3.3).
  //
  // 28. Let stylePatterns be patterns.[[<style>]].
  //
  // 29. Set numberFormat.[[PositivePattern]] to
  // stylePatterns.[[positivePattern]].
  //
  // 30. Set numberFormat.[[NegativePattern]] to
  // stylePatterns.[[negativePattern]].
  //
  icu::number::LocalizedNumberFormatter fmt = settings.locale(icu_locale);
  DirectHandle<Managed<icu::number::LocalizedNumberFormatter>>
      managed_number_formatter =
          Managed<icu::number::LocalizedNumberFormatter>::From(
              isolate, 0,
              std::make_shared<icu::number::LocalizedNumberFormatter>(fmt));
  // Now all properties are ready, so we can allocate the result object.
  DirectHandle<JSNumberFormat> number_format = Cast<JSNumberFormat>(
      isolate->factory()->NewFastOrSlowJSObjectFromMap(map));
  DisallowGarbageCollection no_gc;
  number_format->set_locale(*locale_str);
  number_format->set_icu_number_formatter(*managed_number_formatter);
  number_format->set_bound_format(*factory->undefined_value());
  // 31. Return numberFormat.
  return number_format;
}
References ASSIGN_RETURN_ON_EXCEPTION, AVOID_AMBIGUOUS_OP_WARNING, v8::internal::Intl::CanonicalizeLocaleList(), v8::internal::CoerceOptionsToObject(), v8::internal::Isolate::CountUsage(), v8::internal::anonymous_namespace{js-number-format.cc}::CurrencyDigits(), v8::internal::DCHECK(), v8::internal::Intl::ResolvedLocale::extensions, v8::internal::Isolate::factory(), v8::internal::Managed< CppType >::From(), v8::Maybe< T >::FromJust(), GetAvailableLocales(), v8::internal::Intl::GetLocaleMatcher(), v8::internal::Intl::GetNumberingSystem(), v8::internal::GetStringOption(), v8::internal::Intl::ResolvedLocale::icu_locale, v8::Maybe< T >::IsNothing(), v8::internal::Intl::IsValidNumberingSystem(), v8::internal::anonymous_namespace{js-number-format.cc}::IsWellFormedCurrencyCode(), v8::internal::anonymous_namespace{js-number-format.cc}::IsWellFormedUnitIdentifier(), v8::internal::anonymous_namespace{isolate.cc}::kInvalid, MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, MAYBE_RETURN, NAME, v8::internal::Factory::NewFastOrSlowJSObjectFromMap(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), v8::internal::Factory::NewStringFromStaticChars(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, none, v8::internal::Intl::ResolveLocale(), v8::internal::Intl::NumberFormatDigitOptions::rounding_increment, SetDigitOptionsToFormatter(), v8::internal::Intl::SetNumberFormatDigitOptions(), v8::internal::status, v8::internal::string, THROW_NEW_ERROR, v8::internal::anonymous_namespace{js-number-format.cc}::ToICUNotation(), v8::internal::Intl::ToLanguageTag(), v8::internal::Intl::ToString(), v8::internal::anonymous_namespace{js-number-format.cc}::ToUNumberGroupingStrategy(), v8::internal::anonymous_namespace{js-number-format.cc}::ToUNumberSignDisplay(), and v8::internal::anonymous_namespace{js-number-format.cc}::ToUNumberUnitWidth().
NumberFormatFunction()
MaybeDirectHandle< String > v8::internal::JSNumberFormat::NumberFormatFunction (Isolate * isolate, DirectHandle< JSNumberFormat > number_format, Handle< Object > numeric_obj) [static]
Definition at line 2146 of file js-number-format.cc.
                          {
  icu::number::LocalizedNumberFormatter* fmt =
      number_format->icu_number_formatter()->raw();
  CHECK_NOT_NULL(fmt);
  // 4. Let x be ? ToIntlMathematicalValue(value).
  IntlMathematicalValue x;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, x, IntlMathematicalValue::From(isolate, value),
      DirectHandle<String>());
  // 5. Return FormatNumeric(nf, x).
  Maybe<icu::number::FormattedNumber> maybe_formatted =
      IntlMathematicalValue::FormatNumeric(isolate, *fmt, x);
  MAYBE_RETURN(maybe_formatted, DirectHandle<String>());
  icu::number::FormattedNumber formatted =
      std::move(maybe_formatted).FromJust();
  return FormatToString(isolate, formatted, *fmt, x.IsNaN());
}
References CHECK_NOT_NULL, v8::internal::IntlMathematicalValue::FormatNumeric(), v8::internal::anonymous_namespace{js-number-format.cc}::FormatToString(), v8::internal::IntlMathematicalValue::From(), v8::internal::IntlMathematicalValue::IsNaN(), MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, MAYBE_RETURN, and v8::internal::value.
Referenced by v8::internal::BUILTIN().
NumberingSystemFromSkeleton()
const icu::UnicodeString v8::internal::JSNumberFormat::NumberingSystemFromSkeleton (const icu::UnicodeString & skeleton) [static]
Definition at line 437 of file js-number-format.cc.
                                      {
  const char numbering_system[] = "numbering-system/";
  int32_t index = skeleton.indexOf(numbering_system);
  if (index < 0) return "latn";
  index += static_cast<int32_t>(std::strlen(numbering_system));
  const icu::UnicodeString res = skeleton.tempSubString(index);
  index = res.indexOf(" ");
  if (index < 0) return res;
  return res.tempSubString(0, index);
}
References v8::internal::index.
Referenced by v8::internal::JSDurationFormat::ResolvedOptions(), and ResolvedOptions().
ResolvedOptions()
DirectHandle< JSObject > v8::internal::JSNumberFormat::ResolvedOptions (Isolate * isolate, DirectHandle< JSNumberFormat > number_format) [static]
Definition at line 882 of file js-number-format.cc.
                                                                  {
  Factory* factory = isolate->factory();
  UErrorCode status = U_ZERO_ERROR;
  icu::number::LocalizedNumberFormatter* fmt =
      number_format->icu_number_formatter()->raw();
  icu::UnicodeString skeleton = fmt->toSkeleton(status);
  DCHECK(U_SUCCESS(status));
  // 4. Let options be ! ObjectCreate(%ObjectPrototype%).
  DirectHandle<JSObject> options =
      factory->NewJSObject(isolate->object_function());
  DirectHandle<String> locale =
      DirectHandle<String>(number_format->locale(), isolate);
  const icu::UnicodeString numberingSystem_ustr =
      JSNumberFormat::NumberingSystemFromSkeleton(skeleton);
  // 5. For each row of Table 4, except the header row, in table order, do
  // Table 4: Resolved Options of NumberFormat Instances
  // Internal Slot Property
  // [[Locale]] "locale"
  // [[NumberingSystem]] "numberingSystem"
  // [[Style]] "style"
  // [[Currency]] "currency"
  // [[CurrencyDisplay]] "currencyDisplay"
  // [[CurrencySign]] "currencySign"
  // [[Unit]] "unit"
  // [[UnitDisplay]] "unitDisplay"
  // [[MinimumIntegerDigits]] "minimumIntegerDigits"
  // [[MinimumFractionDigits]] "minimumFractionDigits"
  // [[MaximumFractionDigits]] "maximumFractionDigits"
  // [[MinimumSignificantDigits]] "minimumSignificantDigits"
  // [[MaximumSignificantDigits]] "maximumSignificantDigits"
  // [[UseGrouping]] "useGrouping"
  // [[Notation]] "notation"
  // [[CompactDisplay]] "compactDisplay"
  // [[SignDisplay]] "signDisplay"
  // [[RoundingIncrement]] "roundingIncrement"
  // [[RoundingMode]] "roundingMode"
  // [[ComputedRoundingPriority]] "roundingPriority"
  // [[TrailingZeroDisplay]] "trailingZeroDisplay"
  CHECK(JSReceiver::CreateDataProperty(isolate, options,
                                       factory->locale_string(), locale,
                                       Just(kDontThrow))
            .FromJust());
  DirectHandle<String> numberingSystem_string;
  CHECK(Intl::ToString(isolate, numberingSystem_ustr)
            .ToHandle(&numberingSystem_string));
  CHECK(JSReceiver::CreateDataProperty(isolate, options,
                                       factory->numberingSystem_string(),
                                       numberingSystem_string, Just(kDontThrow))
            .FromJust());
  Style style = StyleFromSkeleton(skeleton);
  CHECK(JSReceiver::CreateDataProperty(
            isolate, options, factory->style_string(),
            StyleAsString(isolate, style), Just(kDontThrow))
            .FromJust());
  const icu::UnicodeString currency_ustr = CurrencyFromSkeleton(skeleton);
  if (!currency_ustr.isEmpty()) {
    DirectHandle<String> currency_string;
    CHECK(Intl::ToString(isolate, currency_ustr).ToHandle(&currency_string));
    CHECK(JSReceiver::CreateDataProperty(isolate, options,
                                         factory->currency_string(),
                                         currency_string, Just(kDontThrow))
              .FromJust());
    CHECK(JSReceiver::CreateDataProperty(
              isolate, options, factory->currencyDisplay_string(),
              CurrencyDisplayString(isolate, skeleton), Just(kDontThrow))
              .FromJust());
    CHECK(JSReceiver::CreateDataProperty(
              isolate, options, factory->currencySign_string(),
              CurrencySignString(isolate, skeleton), Just(kDontThrow))
              .FromJust());
  }
  if (style == Style::UNIT) {
    std::string unit = UnitFromSkeleton(skeleton);
    if (!unit.empty()) {
      CHECK(JSReceiver::CreateDataProperty(
                isolate, options, factory->unit_string(),
                isolate->factory()->NewStringFromAsciiChecked(unit.c_str()),
                Just(kDontThrow))
                .FromJust());
    }
    CHECK(JSReceiver::CreateDataProperty(
              isolate, options, factory->unitDisplay_string(),
              UnitDisplayString(isolate, skeleton), Just(kDontThrow))
              .FromJust());
  }
  CHECK(
      JSReceiver::CreateDataProperty(
          isolate, options, factory->minimumIntegerDigits_string(),
          factory->NewNumberFromInt(MinimumIntegerDigitsFromSkeleton(skeleton)),
          Just(kDontThrow))
          .FromJust());
  int32_t mnsd = 0, mxsd = 0, mnfd = 0, mxfd = 0;
  if (FractionDigitsFromSkeleton(skeleton, &mnfd, &mxfd)) {
    CHECK(JSReceiver::CreateDataProperty(
              isolate, options, factory->minimumFractionDigits_string(),
              factory->NewNumberFromInt(mnfd), Just(kDontThrow))
              .FromJust());
    CHECK(JSReceiver::CreateDataProperty(
              isolate, options, factory->maximumFractionDigits_string(),
              factory->NewNumberFromInt(mxfd), Just(kDontThrow))
              .FromJust());
  }
  if (SignificantDigitsFromSkeleton(skeleton, &mnsd, &mxsd)) {
    CHECK(JSReceiver::CreateDataProperty(
              isolate, options, factory->minimumSignificantDigits_string(),
              factory->NewNumberFromInt(mnsd), Just(kDontThrow))
              .FromJust());
    CHECK(JSReceiver::CreateDataProperty(
              isolate, options, factory->maximumSignificantDigits_string(),
              factory->NewNumberFromInt(mxsd), Just(kDontThrow))
              .FromJust());
  }
  CHECK(JSReceiver::CreateDataProperty(
            isolate, options, factory->useGrouping_string(),
            UseGroupingFromSkeleton(isolate, skeleton), Just(kDontThrow))
            .FromJust());
  Notation notation = NotationFromSkeleton(skeleton);
  CHECK(JSReceiver::CreateDataProperty(
            isolate, options, factory->notation_string(),
            NotationAsString(isolate, notation), Just(kDontThrow))
            .FromJust());
  // Only output compactDisplay when notation is compact.
  if (notation == Notation::COMPACT) {
    CHECK(JSReceiver::CreateDataProperty(
              isolate, options, factory->compactDisplay_string(),
              CompactDisplayString(isolate, skeleton), Just(kDontThrow))
              .FromJust());
  }
  CHECK(JSReceiver::CreateDataProperty(
            isolate, options, factory->signDisplay_string(),
            SignDisplayString(isolate, skeleton), Just(kDontThrow))
            .FromJust());
  CHECK(JSReceiver::CreateDataProperty(
            isolate, options, factory->roundingIncrement_string(),
            RoundingIncrement(isolate, skeleton), Just(kDontThrow))
            .FromJust());
  CHECK(JSReceiver::CreateDataProperty(
            isolate, options, factory->roundingMode_string(),
            RoundingModeString(isolate, skeleton), Just(kDontThrow))
            .FromJust());
  CHECK(JSReceiver::CreateDataProperty(
            isolate, options, factory->roundingPriority_string(),
            RoundingPriorityString(isolate, skeleton), Just(kDontThrow))
            .FromJust());
  CHECK(JSReceiver::CreateDataProperty(
            isolate, options, factory->trailingZeroDisplay_string(),
            TrailingZeroDisplayString(isolate, skeleton), Just(kDontThrow))
            .FromJust());
  return options;
}
References CHECK, v8::internal::anonymous_namespace{js-number-format.cc}::CompactDisplayString(), v8::internal::JSReceiver::CreateDataProperty(), v8::internal::anonymous_namespace{js-number-format.cc}::CurrencyDisplayString(), v8::internal::anonymous_namespace{js-number-format.cc}::CurrencyFromSkeleton(), v8::internal::anonymous_namespace{js-number-format.cc}::CurrencySignString(), v8::internal::DCHECK(), v8::internal::Isolate::factory(), FractionDigitsFromSkeleton(), v8::Just(), v8::internal::kDontThrow, MinimumIntegerDigitsFromSkeleton(), v8::internal::Factory::NewJSObject(), v8::internal::FactoryBase< Impl >::NewNumberFromInt(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), v8::internal::anonymous_namespace{js-number-format.cc}::NotationAsString(), v8::internal::anonymous_namespace{js-number-format.cc}::NotationFromSkeleton(), NumberingSystemFromSkeleton(), RoundingIncrement(), RoundingModeString(), RoundingPriorityString(), v8::internal::anonymous_namespace{js-number-format.cc}::SignDisplayString(), SignificantDigitsFromSkeleton(), v8::internal::status, v8::internal::string, v8::internal::anonymous_namespace{js-number-format.cc}::StyleAsString(), v8::internal::anonymous_namespace{js-number-format.cc}::StyleFromSkeleton(), v8::anonymous_namespace{api.cc}::ToHandle(), v8::internal::Intl::ToString(), TrailingZeroDisplayString(), v8::internal::anonymous_namespace{js-number-format.cc}::UnitDisplayString(), v8::internal::anonymous_namespace{js-number-format.cc}::UnitFromSkeleton(), and v8::internal::anonymous_namespace{js-number-format.cc}::UseGroupingFromSkeleton().
Referenced by v8::internal::BUILTIN().
RoundingIncrement()
DirectHandle< Object > v8::internal::JSNumberFormat::RoundingIncrement (Isolate * isolate, const icu::UnicodeString & skeleton) [static]
Definition at line 621 of file js-number-format.cc.
                                                        {
  int32_t cur = skeleton.indexOf(u"precision-increment/");
  if (cur < 0) return isolate->factory()->NewNumberFromInt(1);
  cur += 20; // length of "precision-increment/"
  int32_t increment = 0;
  while (cur < skeleton.length()) {
    char16_t c = skeleton[cur++];
    if (c == u'.') continue;
    if (!IsDecimalDigit(c)) break;
    increment = increment * 10 + (c - '0');
  }
  return isolate->factory()->NewNumberFromInt(increment);
}
References v8::internal::Isolate::factory(), v8::internal::IsDecimalDigit(), and v8::internal::FactoryBase< Impl >::NewNumberFromInt().
Referenced by ResolvedOptions().
RoundingModeString()
DirectHandle< String > v8::internal::JSNumberFormat::RoundingModeString (Isolate * isolate, const icu::UnicodeString & skeleton) [static]
Definition at line 567 of file js-number-format.cc.
                                                        {
  static const char* rounding_mode = "rounding-mode-";
  int32_t start = skeleton.indexOf(rounding_mode);
  if (start >= 0) {
    DCHECK_EQ(14, strlen(rounding_mode));
    icu::UnicodeString check = skeleton.tempSubString(start + 14);
    // Ex: skeleton as
    // .### rounding-mode-ceiling
    if (check.startsWith("ceiling")) {
      return isolate->factory()->ceil_string();
    }
    // Ex: skeleton as
    // .### rounding-mode-down
    if (check.startsWith("down")) {
      return isolate->factory()->trunc_string();
    }
    // Ex: skeleton as
    // .### rounding-mode-floor
    if (check.startsWith("floor")) {
      return isolate->factory()->floor_string();
    }
    // Ex: skeleton as
    // .### rounding-mode-half-ceiling
    if (check.startsWith("half-ceiling")) {
      return isolate->factory()->halfCeil_string();
    }
    // Ex: skeleton as
    // .### rounding-mode-half-down
    if (check.startsWith("half-down")) {
      return isolate->factory()->halfTrunc_string();
    }
    // Ex: skeleton as
    // .### rounding-mode-half-floor
    if (check.startsWith("half-floor")) {
      return isolate->factory()->halfFloor_string();
    }
    // Ex: skeleton as
    // .### rounding-mode-half-up
    if (check.startsWith("half-up")) {
      return isolate->factory()->halfExpand_string();
    }
    // Ex: skeleton as
    // .### rounding-mode-up
    if (check.startsWith("up")) {
      return isolate->factory()->expand_string();
    }
  }
  // Ex: skeleton as
  // .###
  return isolate->factory()->halfEven_string();
}
References DCHECK_EQ, and v8::internal::Isolate::factory().
Referenced by ResolvedOptions().
RoundingPriorityString()
DirectHandle< String > v8::internal::JSNumberFormat::RoundingPriorityString (Isolate * isolate, const icu::UnicodeString & skeleton) [static]
Definition at line 637 of file js-number-format.cc.
                                                        {
  int32_t found;
  // If #r or @r is followed by a SPACE or in the end of line.
  if ((found = skeleton.indexOf("#r")) >= 0 ||
      (found = skeleton.indexOf("@r")) >= 0) {
    if (found + 2 == skeleton.length() || skeleton[found + 2] == ' ') {
      return isolate->factory()->morePrecision_string();
    }
  }
  // If #s or @s is followed by a SPACE or in the end of line.
  if ((found = skeleton.indexOf("#s")) >= 0 ||
      (found = skeleton.indexOf("@s")) >= 0) {
    if (found + 2 == skeleton.length() || skeleton[found + 2] == ' ') {
      return isolate->factory()->lessPrecision_string();
    }
  }
  return isolate->factory()->auto_string();
}
References v8::internal::Isolate::factory().
Referenced by ResolvedOptions().
SetDigitOptionsToFormatter()
icu::number::UnlocalizedNumberFormatter v8::internal::JSNumberFormat::SetDigitOptionsToFormatter (const icu::number::UnlocalizedNumberFormatter & settings, const Intl::NumberFormatDigitOptions & digit_options) [static]
Definition at line 829 of file js-number-format.cc.
                                                       {
  icu::number::UnlocalizedNumberFormatter result = settings.roundingMode(
      ToUNumberFormatRoundingMode(digit_options.rounding_mode));
  if (digit_options.minimum_integer_digits > 1) {
    result = result.integerWidth(icu::number::IntegerWidth::zeroFillTo(
        digit_options.minimum_integer_digits));
  }
  icu::number::Precision precision = icu::number::Precision::unlimited();
  bool relaxed = false;
  switch (digit_options.rounding_type) {
    case Intl::RoundingType::kSignificantDigits:
      precision = icu::number::Precision::minMaxSignificantDigits(
          digit_options.minimum_significant_digits,
          digit_options.maximum_significant_digits);
      break;
    case Intl::RoundingType::kFractionDigits:
      precision = icu::number::Precision::minMaxFraction(
          digit_options.minimum_fraction_digits,
          digit_options.maximum_fraction_digits);
      break;
    case Intl::RoundingType::kMorePrecision:
      relaxed = true;
      [[fallthrough]];
    case Intl::RoundingType::kLessPrecision:
      precision =
          icu::number::Precision::minMaxFraction(
              digit_options.minimum_fraction_digits,
              digit_options.maximum_fraction_digits)
              .withSignificantDigits(digit_options.minimum_significant_digits,
                                     digit_options.maximum_significant_digits,
                                     relaxed ? UNUM_ROUNDING_PRIORITY_RELAXED
                                             : UNUM_ROUNDING_PRIORITY_STRICT);
      break;
  }
  if (digit_options.rounding_increment != 1) {
    precision = ::icu::number::Precision::incrementExact(
                    digit_options.rounding_increment,
                    -digit_options.maximum_fraction_digits)
                    .withMinFraction(digit_options.minimum_fraction_digits);
  }
  if (digit_options.trailing_zero_display ==
      Intl::TrailingZeroDisplay::kStripIfInteger) {
    precision = precision.trailingZeroDisplay(UNUM_TRAILING_ZERO_HIDE_IF_WHOLE);
  }
  return result.precision(precision);
}
References v8::internal::Intl::kFractionDigits, v8::internal::Intl::kLessPrecision, v8::internal::Intl::kMorePrecision, v8::internal::Intl::kSignificantDigits, v8::internal::Intl::kStripIfInteger, v8::internal::Intl::NumberFormatDigitOptions::maximum_fraction_digits, v8::internal::Intl::NumberFormatDigitOptions::maximum_significant_digits, v8::internal::Intl::NumberFormatDigitOptions::minimum_fraction_digits, v8::internal::Intl::NumberFormatDigitOptions::minimum_integer_digits, v8::internal::Intl::NumberFormatDigitOptions::minimum_significant_digits, v8::base::internal::result, v8::internal::Intl::NumberFormatDigitOptions::rounding_increment, v8::internal::Intl::NumberFormatDigitOptions::rounding_mode, v8::internal::Intl::NumberFormatDigitOptions::rounding_type, v8::internal::anonymous_namespace{js-number-format.cc}::ToUNumberFormatRoundingMode(), and v8::internal::Intl::NumberFormatDigitOptions::trailing_zero_display.
Referenced by v8::internal::JSPluralRules::New(), and New().
SignificantDigitsFromSkeleton()
bool v8::internal::JSNumberFormat::SignificantDigitsFromSkeleton (const icu::UnicodeString & skeleton, int32_t * minimum, int32_t * maximum) [static]
Definition at line 745 of file js-number-format.cc.
                                                                          {
  int32_t index = skeleton.indexOf("@");
  if (index < 0) return false;
  *minimum = 1;
  index++; // skip the first '@'
  while (index < skeleton.length() && skeleton[index] == '@') {
    (*minimum)++;
    index++;
  }
  *maximum = *minimum;
  while (index < skeleton.length() && skeleton[index] == '#') {
    (*maximum)++;
    index++;
  }
  return true;
}
References v8::internal::index.
Referenced by ResolvedOptions(), and v8::internal::JSPluralRules::ResolvedOptions().
TrailingZeroDisplayString()
DirectHandle< String > v8::internal::JSNumberFormat::TrailingZeroDisplayString (Isolate * isolate, const icu::UnicodeString & skeleton) [static]
Definition at line 658 of file js-number-format.cc.
                                                        {
  int32_t found;
  if ((found = skeleton.indexOf("/w")) >= 0) {
    if (found + 2 == skeleton.length() || skeleton[found + 2] == ' ') {
      return isolate->factory()->stripIfInteger_string();
    }
  }
  return isolate->factory()->auto_string();
}
References v8::internal::Isolate::factory().
Referenced by ResolvedOptions().
UnwrapNumberFormat()
MaybeDirectHandle< JSNumberFormat > v8::internal::JSNumberFormat::UnwrapNumberFormat (Isolate * isolate, DirectHandle< JSReceiver > format_holder) [static]
Definition at line 1045 of file js-number-format.cc.
                                                              {
  // old code copy from NumberFormat::Unwrap that has no spec comment and
  // compiled but fail unit tests.
  DirectHandle<Context> native_context(isolate->context()->native_context(),
                                       isolate);
  DirectHandle<JSFunction> constructor(
      Cast<JSFunction>(native_context->intl_number_format_function()), isolate);
  DirectHandle<Object> object;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, object,
      Intl::LegacyUnwrapReceiver(isolate, format_holder, constructor,
                                 IsJSNumberFormat(*format_holder)));
  // 4. If ... or nf does not have an [[InitializedNumberFormat]] internal slot,
  // then
  if (!IsJSNumberFormat(*object)) {
    // a. Throw a TypeError exception.
    THROW_NEW_ERROR(isolate,
                    NewTypeError(MessageTemplate::kIncompatibleMethodReceiver,
                                 isolate->factory()->NewStringFromAsciiChecked(
                                     "UnwrapNumberFormat")));
  }
  // 5. Return nf.
  return Cast<JSNumberFormat>(object);
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Isolate::context(), v8::internal::Isolate::factory(), v8::internal::Intl::LegacyUnwrapReceiver(), v8::internal::native_context, v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), and THROW_NEW_ERROR.
Referenced by v8::internal::BUILTIN().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-number-format.h
/mnt/V8SourceCode/src/objects/js-number-format.cc