v8::internal::EntryFrame Class Reference
#include <frames.h>
Public Member Functions
Type type () const override
Tagged< HeapObject > unchecked_code () const override
void Iterate (RootVisitor *v) const override
Static Public Member Functions
static EntryFrame * cast (StackFrame *frame)
Protected Member Functions
EntryFrame (StackFrameIteratorBase *iterator)
Address GetCallerStackPointer () const override
Private Member Functions
void ComputeCallerState (State *state) const override
Type GetCallerState (State *state) const override
Friends
class StackFrameIteratorBase
Additional Inherited Members
Detailed Description
Definition at line 849 of file frames.h.
Constructor & Destructor Documentation
EntryFrame()
v8::internal::EntryFrame::EntryFrame (StackFrameIteratorBase * iterator) [inline], [explicit], [protected]
Definition at line 130 of file frames-inl.h.
    : TypedFrame(iterator) {}
Member Function Documentation
cast()
static EntryFrame* v8::internal::EntryFrame::cast (StackFrame * frame) [inline], [static]
Definition at line 858 of file frames.h.
                                             {
    DCHECK(frame->is_entry());
    return static_cast<EntryFrame*>(frame);
  }
References v8::internal::DCHECK(), and v8::internal::StackFrame::is_entry().
ComputeCallerState()
void v8::internal::EntryFrame::ComputeCallerState (State * state) const [override], [private], [virtual]
Reimplemented from v8::internal::CommonFrame.
Definition at line 1093 of file frames.cc.
                                                      {
  GetCallerState(state);
}
References GetCallerState().
GetCallerStackPointer()
Address v8::internal::EntryFrame::GetCallerStackPointer () const [inline], [override], [protected], [virtual]
Reimplemented from v8::internal::CommonFrame.
Definition at line 869 of file frames.h.
{ return 0; }
GetCallerState()
StackFrame::Type v8::internal::EntryFrame::GetCallerState (State * state) const [override], [private], [virtual]
Reimplemented from v8::internal::StackFrame.
Definition at line 1097 of file frames.cc.
                                                            {
  const Address fast_c_call_caller_fp =
      Memory<Address>(fp() + EntryFrameConstants::kNextFastCallFrameFPOffset);
  if (fast_c_call_caller_fp != kNullAddress) {
    Address caller_pc_address =
        fp() + EntryFrameConstants::kNextFastCallFramePCOffset;
    Address caller_pc = Memory<Address>(caller_pc_address);
    return GetStateForFastCCallCallerFP(isolate(), fast_c_call_caller_fp,
                                        caller_pc, caller_pc_address, state);
  }
  Address next_exit_frame_fp =
      Memory<Address>(fp() + EntryFrameConstants::kNextExitFrameFPOffset);
  return ExitFrame::GetStateForFramePointer(next_exit_frame_fp, state);
}
References v8::internal::CommonFrame::caller_pc(), v8::internal::StackFrame::fp(), v8::internal::anonymous_namespace{frames.cc}::GetStateForFastCCallCallerFP(), v8::internal::ExitFrame::GetStateForFramePointer(), v8::internal::StackFrame::isolate(), v8::internal::EntryFrameConstants::kNextExitFrameFPOffset, v8::internal::EntryFrameConstants::kNextFastCallFrameFPOffset, v8::internal::EntryFrameConstants::kNextFastCallFramePCOffset, and v8::internal::kNullAddress.
Referenced by ComputeCallerState().
Iterate()
void v8::internal::EntryFrame::Iterate (RootVisitor * v) const [override], [virtual]
Reimplemented from v8::internal::TypedFrame.
Definition at line 4080 of file frames.cc.
                                             {
  IteratePc(v, constant_pool_address(), GcSafeLookupCode());
}
type()
Type v8::internal::EntryFrame::type () const [inline], [override], [virtual]
Implements v8::internal::StackFrame.
Reimplemented in v8::internal::ConstructEntryFrame.
Definition at line 851 of file frames.h.
{ return ENTRY; }
References ENTRY.
unchecked_code()
Tagged< HeapObject > v8::internal::EntryFrame::unchecked_code () const [override], [virtual]
Reimplemented from v8::internal::TypedFrame.
Reimplemented in v8::internal::ConstructEntryFrame.
Definition at line 1089 of file frames.cc.
                                                    {
  return isolate()->builtins()->code(Builtin::kJSEntry);
}
References v8::internal::Isolate::builtins(), v8::internal::Builtins::code(), and v8::internal::StackFrame::isolate().
Friends And Related Function Documentation
StackFrameIteratorBase
friend class StackFrameIteratorBase [friend]
Definition at line 875 of file frames.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/frames.h
/mnt/V8SourceCode/src/execution/frames-inl.h
/mnt/V8SourceCode/src/execution/frames.cc