cppgc::internal::ObjectStartBitmap Class Reference
#include <object-start-bitmap.h>
Public Member Functions
ObjectStartBitmap ()
template<AccessMode = AccessMode::kNonAtomic>
HeapObjectHeader * FindHeader (ConstAddress address_maybe_pointing_to_the_middle_of_object) const
template<AccessMode = AccessMode::kNonAtomic>
void SetBit (ConstAddress)
template<AccessMode = AccessMode::kNonAtomic>
void ClearBit (ConstAddress)
template<AccessMode = AccessMode::kNonAtomic>
bool CheckBit (ConstAddress) const
template<typename Callback >
void Iterate (Callback) const
void Clear ()
void MarkAsFullyPopulated ()
Static Public Member Functions
static constexpr size_t Granularity ()
static constexpr size_t MaxEntries ()
Private Member Functions
template<AccessMode = AccessMode::kNonAtomic>
void store (size_t cell_index, uint8_t value)
template<AccessMode = AccessMode::kNonAtomic>
uint8_t load (size_t cell_index) const
void ObjectStartIndexAndBit (ConstAddress, size_t *, size_t *) const
Private Attributes
bool fully_populated_ = false
std::array< uint8_t, kReservedForBitmap > object_start_bit_map_
Static Private Attributes
static constexpr size_t kBitsPerCell = sizeof(uint8_t) * CHAR_BIT
static constexpr size_t kCellMask = kBitsPerCell - 1
static constexpr size_t kBitmapSize
static constexpr size_t kReservedForBitmap
Detailed Description
Definition at line 33 of file object-start-bitmap.h.
Constructor & Destructor Documentation
ObjectStartBitmap()
cppgc::internal::ObjectStartBitmap::ObjectStartBitmap () [inline]
Definition at line 107 of file object-start-bitmap.h.
                                     {
  Clear();
  MarkAsFullyPopulated();
}
References Clear(), and MarkAsFullyPopulated().
Member Function Documentation
CheckBit()
template<AccessMode mode>
bool cppgc::internal::ObjectStartBitmap::CheckBit (ConstAddress header_address) const [inline]
Definition at line 157 of file object-start-bitmap.h.
                                                                  {
  size_t cell_index, object_bit;
  ObjectStartIndexAndBit(header_address, &cell_index, &object_bit);
  return load<mode>(cell_index) & (1 << object_bit);
}
References ObjectStartIndexAndBit().
Referenced by cppgc::internal::anonymous_namespace{sweeper.cc}::SweepNormalPage().
Clear()
void cppgc::internal::ObjectStartBitmap::Clear () [inline]
Definition at line 220 of file object-start-bitmap.h.
                              {
  fully_populated_ = false;
  std::fill(object_start_bit_map_.begin(), object_start_bit_map_.end(), 0);
}
References fully_populated_, and object_start_bit_map_.
Referenced by cppgc::internal::anonymous_namespace{compactor.cc}::CompactPage(), and ObjectStartBitmap().
ClearBit()
template<AccessMode mode>
void cppgc::internal::ObjectStartBitmap::ClearBit (ConstAddress header_address) [inline]
Definition at line 149 of file object-start-bitmap.h.
                                                            {
  size_t cell_index, object_bit;
  ObjectStartIndexAndBit(header_address, &cell_index, &object_bit);
  store<mode>(cell_index,
              static_cast<uint8_t>(load(cell_index) & ~(1 << object_bit)));
}
References load(), and ObjectStartIndexAndBit().
FindHeader()
template<AccessMode mode>
HeapObjectHeader * cppgc::internal::ObjectStartBitmap::FindHeader (ConstAddress address_maybe_pointing_to_the_middle_of_object) const [inline]
Definition at line 113 of file object-start-bitmap.h.
                                                                       {
  DCHECK(fully_populated_);
  const size_t page_base = reinterpret_cast<uintptr_t>(
                               address_maybe_pointing_to_the_middle_of_object) &
                           kPageBaseMask;
  DCHECK_EQ(page_base, reinterpret_cast<uintptr_t>(this) & kPageBaseMask);
  size_t object_offset = reinterpret_cast<uintptr_t>(
                             address_maybe_pointing_to_the_middle_of_object) &
                         kPageOffsetMask;
  size_t object_start_number = object_offset / kAllocationGranularity;
  size_t cell_index = object_start_number / kBitsPerCell;
  DCHECK_GT(object_start_bit_map_.size(), cell_index);
  const size_t bit = object_start_number & kCellMask;
  uint8_t byte = load<mode>(cell_index) & ((1 << (bit + 1)) - 1);
  while (!byte && cell_index) {
    DCHECK_LT(0u, cell_index);
    byte = load<mode>(--cell_index);
  }
  const int leading_zeroes = v8::base::bits::CountLeadingZeros(byte);
  object_start_number =
      (cell_index * kBitsPerCell) + (kBitsPerCell - 1) - leading_zeroes;
  object_offset = object_start_number * kAllocationGranularity;
  return reinterpret_cast<HeapObjectHeader*>(page_base + object_offset);
}
References v8::base::bits::CountLeadingZeros(), DCHECK, DCHECK_EQ, DCHECK_GT, DCHECK_LT, fully_populated_, cppgc::internal::kAllocationGranularity, kBitsPerCell, kCellMask, cppgc::internal::kPageBaseMask, cppgc::internal::kPageOffsetMask, and object_start_bit_map_.
Referenced by cppgc::internal::ObjectHeaderFromInnerAddressImpl().
Granularity()
static constexpr size_t cppgc::internal::ObjectStartBitmap::Granularity () [inline], [static], [constexpr]
Definition at line 36 of file object-start-bitmap.h.
{ return kAllocationGranularity; }
References cppgc::internal::kAllocationGranularity.
Iterate()
template<typename Callback >
void cppgc::internal::ObjectStartBitmap::Iterate (Callback callback) const [inline]
Definition at line 195 of file object-start-bitmap.h.
                                                              {
  const Address page_base = reinterpret_cast<Address>(
      reinterpret_cast<uintptr_t>(this) & kPageBaseMask);
  for (size_t cell_index = 0; cell_index < kReservedForBitmap; cell_index++) {
    if (!object_start_bit_map_[cell_index]) continue;
    uint8_t value = object_start_bit_map_[cell_index];
    while (value) {
      const int trailing_zeroes = v8::base::bits::CountTrailingZeros(value);
      const size_t object_start_number =
          (cell_index * kBitsPerCell) + trailing_zeroes;
      const Address object_address =
          page_base + (kAllocationGranularity * object_start_number);
      callback(object_address);
      // Clear current object bit in temporary value to advance iteration.
      value &= ~(1 << (object_start_number & kCellMask));
    }
  }
}
References v8::base::bits::CountTrailingZeros(), cppgc::internal::kAllocationGranularity, kBitsPerCell, kCellMask, cppgc::internal::kPageBaseMask, kReservedForBitmap, object_start_bit_map_, and v8::internal::value.
load()
template<AccessMode mode>
uint8_t cppgc::internal::ObjectStartBitmap::load (size_t cell_index) const [inline], [private]
Definition at line 174 of file object-start-bitmap.h.
                                                       {
  if (mode == AccessMode::kNonAtomic) {
    return object_start_bit_map_[cell_index];
  }
  return v8::base::AsAtomicPtr(&object_start_bit_map_[cell_index])
      ->load(std::memory_order_acquire);
}
References v8::base::AsAtomicPtr(), cppgc::internal::kNonAtomic, mode(), and object_start_bit_map_.
Referenced by ClearBit(), and SetBit().
MarkAsFullyPopulated()
void cppgc::internal::ObjectStartBitmap::MarkAsFullyPopulated () [inline]
Definition at line 215 of file object-start-bitmap.h.
                                             {
  DCHECK(!fully_populated_);
  fully_populated_ = true;
}
References DCHECK, and fully_populated_.
Referenced by cppgc::internal::anonymous_namespace{compactor.cc}::CompactionState::FinishCompactingPage(), and ObjectStartBitmap().
MaxEntries()
static constexpr size_t cppgc::internal::ObjectStartBitmap::MaxEntries () [inline], [static], [constexpr]
Definition at line 39 of file object-start-bitmap.h.
                                       {
    return kReservedForBitmap * kBitsPerCell;
  }
ObjectStartIndexAndBit()
void cppgc::internal::ObjectStartBitmap::ObjectStartIndexAndBit (ConstAddress header_address, size_t * cell_index, size_t * bit) const [inline], [private]
Definition at line 182 of file object-start-bitmap.h.
                                                                  {
  const size_t object_offset =
      reinterpret_cast<size_t>(header_address) & kPageOffsetMask;
  DCHECK(!(object_offset & kAllocationMask));
  const size_t object_start_number = object_offset / kAllocationGranularity;
  *cell_index = object_start_number / kBitsPerCell;
  DCHECK_GT(kBitmapSize, *cell_index);
  *bit = object_start_number & kCellMask;
}
References DCHECK, DCHECK_GT, cppgc::internal::kAllocationGranularity, cppgc::internal::kAllocationMask, kBitmapSize, kBitsPerCell, kCellMask, and cppgc::internal::kPageOffsetMask.
Referenced by CheckBit(), ClearBit(), and SetBit().
SetBit()
template<AccessMode mode>
void cppgc::internal::ObjectStartBitmap::SetBit (ConstAddress header_address) [inline]
Definition at line 140 of file object-start-bitmap.h.
                                                          {
  size_t cell_index, object_bit;
  ObjectStartIndexAndBit(header_address, &cell_index, &object_bit);
  // Only a single mutator thread can write to the bitmap, so no need for CAS.
  store<mode>(cell_index,
              static_cast<uint8_t>(load(cell_index) | (1 << object_bit)));
}
References load(), and ObjectStartIndexAndBit().
store()
template<AccessMode mode>
void cppgc::internal::ObjectStartBitmap::store (size_t cell_index, uint8_t value) [inline], [private]
Definition at line 164 of file object-start-bitmap.h.
                                                              {
  if (mode == AccessMode::kNonAtomic) {
    object_start_bit_map_[cell_index] = value;
    return;
  }
  v8::base::AsAtomicPtr(&object_start_bit_map_[cell_index])
      ->store(value, std::memory_order_release);
}
References v8::base::AsAtomicPtr(), cppgc::internal::kNonAtomic, mode(), object_start_bit_map_, and v8::internal::value.
Member Data Documentation
fully_populated_
bool cppgc::internal::ObjectStartBitmap::fully_populated_ = false [private]
Definition at line 101 of file object-start-bitmap.h.
Referenced by Clear(), FindHeader(), and MarkAsFullyPopulated().
kBitmapSize
constexpr size_t cppgc::internal::ObjectStartBitmap::kBitmapSize [static], [constexpr], [private]
Initial value:
=
      (kPageSize + ((kBitsPerCell * kAllocationGranularity) - 1)) /
      (kBitsPerCell * kAllocationGranularity)
Definition at line 83 of file object-start-bitmap.h.
Referenced by ObjectStartIndexAndBit().
kBitsPerCell
constexpr size_t cppgc::internal::ObjectStartBitmap::kBitsPerCell = sizeof(uint8_t) * CHAR_BIT [static], [constexpr], [private]
Definition at line 81 of file object-start-bitmap.h.
Referenced by FindHeader(), Iterate(), and ObjectStartIndexAndBit().
kCellMask
constexpr size_t cppgc::internal::ObjectStartBitmap::kCellMask = kBitsPerCell - 1 [static], [constexpr], [private]
Definition at line 82 of file object-start-bitmap.h.
Referenced by FindHeader(), Iterate(), and ObjectStartIndexAndBit().
kReservedForBitmap
constexpr size_t cppgc::internal::ObjectStartBitmap::kReservedForBitmap [static], [constexpr], [private]
Initial value:
=
      ((kBitmapSize + kAllocationMask) & ~kAllocationMask)
Definition at line 86 of file object-start-bitmap.h.
Referenced by Iterate().
object_start_bit_map_
std::array<uint8_t, kReservedForBitmap> cppgc::internal::ObjectStartBitmap::object_start_bit_map_ [private]
Definition at line 104 of file object-start-bitmap.h.
Referenced by Clear(), FindHeader(), Iterate(), load(), and store().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc/object-start-bitmap.h