v8::internal::compiler::AtomicLoadParameters Class Reference
#include <machine-operator.h>
Public Member Functions
AtomicLoadParameters (LoadRepresentation representation, AtomicMemoryOrder order, MemoryAccessKind kind=MemoryAccessKind::kNormal)
LoadRepresentation representation () const
AtomicMemoryOrder order () const
MemoryAccessKind kind () const
Private Attributes
LoadRepresentation representation_
AtomicMemoryOrder order_
MemoryAccessKind kind_
Detailed Description
Definition at line 57 of file machine-operator.h.
Constructor & Destructor Documentation
AtomicLoadParameters()
v8::internal::compiler::AtomicLoadParameters::AtomicLoadParameters (LoadRepresentation representation, AtomicMemoryOrder order, MemoryAccessKind kind = MemoryAccessKind::kNormal) [inline]
Definition at line 59 of file machine-operator.h.
      : representation_(representation), order_(order), kind_(kind) {}
Member Function Documentation
kind()
MemoryAccessKind v8::internal::compiler::AtomicLoadParameters::kind () const [inline]
Definition at line 66 of file machine-operator.h.
{ return kind_; }
References kind_.
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator==(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
order()
AtomicMemoryOrder v8::internal::compiler::AtomicLoadParameters::order () const [inline]
Definition at line 65 of file machine-operator.h.
{ return order_; }
References order_.
Referenced by v8::internal::compiler::RawMachineAssembler::AtomicLoad64(), v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), and v8::internal::compiler::operator==().
representation()
LoadRepresentation v8::internal::compiler::AtomicLoadParameters::representation () const [inline]
Definition at line 64 of file machine-operator.h.
{ return representation_; }
References representation_.
Referenced by v8::internal::compiler::RawMachineAssembler::AtomicLoad(), v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), and v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationInferrer::Run().
Member Data Documentation
kind_
MemoryAccessKind v8::internal::compiler::AtomicLoadParameters::kind_ [private]
Definition at line 71 of file machine-operator.h.
Referenced by kind().
order_
AtomicMemoryOrder v8::internal::compiler::AtomicLoadParameters::order_ [private]
Definition at line 70 of file machine-operator.h.
Referenced by order().
representation_
LoadRepresentation v8::internal::compiler::AtomicLoadParameters::representation_ [private]
Definition at line 69 of file machine-operator.h.
Referenced by representation().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/machine-operator.h