v8::ResourceConstraints Class Reference
A set of constraints that specifies the limits of the runtime's memory use.
#include <v8-isolate.h>
Public Member Functions
void ConfigureDefaultsFromHeapSize (size_t initial_heap_size_in_bytes, size_t maximum_heap_size_in_bytes)
Configures the constraints with reasonable default values based on the provided heap size limit.
void ConfigureDefaults (uint64_t physical_memory, uint64_t virtual_memory_limit)
Configures the constraints with reasonable default values based on the capabilities of the current device the VM is running on.
uint32_t * stack_limit () const
The address beyond which the VM's stack may not grow.
void set_stack_limit (uint32_t *value)
size_t code_range_size_in_bytes () const
The amount of virtual memory reserved for generated code.
void set_code_range_size_in_bytes (size_t limit)
size_t max_old_generation_size_in_bytes () const
The maximum size of the old generation.
void set_max_old_generation_size_in_bytes (size_t limit)
size_t max_young_generation_size_in_bytes () const
The maximum size of the young generation, which consists of two semi-spaces and a large object space.
void set_max_young_generation_size_in_bytes (size_t limit)
size_t initial_old_generation_size_in_bytes () const
void set_initial_old_generation_size_in_bytes (size_t initial_size)
size_t initial_young_generation_size_in_bytes () const
void set_initial_young_generation_size_in_bytes (size_t initial_size)
Private Attributes
size_t code_range_size_ = 0
size_t max_old_generation_size_ = 0
size_t max_young_generation_size_ = 0
size_t initial_old_generation_size_ = 0
size_t initial_young_generation_size_ = 0
uint32_t * stack_limit_ = nullptr
Static Private Attributes
static constexpr size_t kMB = 1048576u
Detailed Description
A set of constraints that specifies the limits of the runtime's memory use.
You must set the heap size before initializing the VM - the size cannot be adjusted after the VM is initialized.
If you are using threads then you should hold the V8::Locker lock while setting the stack limit and you must set a non-default stack limit separately for each thread.
The arguments for set_max_semi_space_size, set_max_old_space_size, set_max_executable_size, set_code_range_size specify limits in MB.
The argument for set_max_semi_space_size_in_kb is in KB.
Definition at line 64 of file v8-isolate.h.
Member Function Documentation
code_range_size_in_bytes()
size_t v8::ResourceConstraints::code_range_size_in_bytes () const [inline]
The amount of virtual memory reserved for generated code.
This is relevant for 64-bit architectures that rely on code range for calls in code.
When V8_COMPRESS_POINTERS_IN_SHARED_CAGE is defined, there is a shared process-wide code range that is lazily initialized. This value is used to configure that shared code range when the first Isolate is created. Subsequent Isolates ignore this value.
Definition at line 114 of file v8-isolate.h.
{ return code_range_size_; }
Referenced by v8::internal::Heap::ConfigureHeap().
ConfigureDefaults()
void v8::ResourceConstraints::ConfigureDefaults (uint64_t physical_memory, uint64_t virtual_memory_limit)
Configures the constraints with reasonable default values based on the capabilities of the current device the VM is running on.
Parameters
physical_memory The total amount of physical memory on the current device, in bytes.
virtual_memory_limit The amount of virtual memory on the current device, in bytes, or zero, if there is no limit.
Definition at line 533 of file api.cc.
                                                                           {
  size_t heap_size = i::Heap::HeapSizeFromPhysicalMemory(physical_memory);
  size_t young_generation, old_generation;
  i::Heap::GenerationSizesFromHeapSize(heap_size, &young_generation,
                                       &old_generation);
  set_max_young_generation_size_in_bytes(young_generation);
  set_max_old_generation_size_in_bytes(old_generation);
  if (virtual_memory_limit > 0 && i::kPlatformRequiresCodeRange) {
    set_code_range_size_in_bytes(
        std::min(i::kMaximalCodeRangeSize,
                 static_cast<size_t>(virtual_memory_limit / 8)));
  }
}
References v8::internal::Heap::GenerationSizesFromHeapSize(), v8::internal::Heap::HeapSizeFromPhysicalMemory(), v8::internal::kMaximalCodeRangeSize, v8::internal::kPlatformRequiresCodeRange, set_code_range_size_in_bytes(), set_max_old_generation_size_in_bytes(), and set_max_young_generation_size_in_bytes().
Referenced by v8::Shell::Main().
ConfigureDefaultsFromHeapSize()
void v8::ResourceConstraints::ConfigureDefaultsFromHeapSize (size_t initial_heap_size_in_bytes, size_t maximum_heap_size_in_bytes)
Configures the constraints with reasonable default values based on the provided heap size limit.
The heap size includes both the young and the old generation.
Parameters
initial_heap_size_in_bytes The initial heap size or zero. By default V8 starts with a small heap and dynamically grows it to match the set of live objects. This may lead to ineffective garbage collections at startup if the live set is large. Setting the initial heap size avoids such garbage collections. Note that this does not affect young generation garbage collections.
maximum_heap_size_in_bytes The hard limit for the heap size. When the heap size approaches this limit, V8 will perform series of garbage collections and invoke the NearHeapLimitCallback. If the garbage collections do not help and the callback does not increase the limit, then V8 will crash with V8::FatalProcessOutOfMemory.
Definition at line 507 of file api.cc.
                                                                          {
  CHECK_LE(initial_heap_size_in_bytes, maximum_heap_size_in_bytes);
  if (maximum_heap_size_in_bytes == 0) {
    return;
  }
  size_t young_generation, old_generation;
  i::Heap::GenerationSizesFromHeapSize(maximum_heap_size_in_bytes,
                                       &young_generation, &old_generation);
  set_max_young_generation_size_in_bytes(
      std::max(young_generation, i::Heap::MinYoungGenerationSize()));
  set_max_old_generation_size_in_bytes(
      std::max(old_generation, i::Heap::MinOldGenerationSize()));
  if (initial_heap_size_in_bytes > 0) {
    i::Heap::GenerationSizesFromHeapSize(initial_heap_size_in_bytes,
                                         &young_generation, &old_generation);
    // We do not set lower bounds for the initial sizes.
    set_initial_young_generation_size_in_bytes(young_generation);
    set_initial_old_generation_size_in_bytes(old_generation);
  }
  if (i::kPlatformRequiresCodeRange) {
    set_code_range_size_in_bytes(
        std::min(i::kMaximalCodeRangeSize, maximum_heap_size_in_bytes));
  }
}
References CHECK_LE, v8::internal::Heap::GenerationSizesFromHeapSize(), v8::internal::kMaximalCodeRangeSize, v8::internal::kPlatformRequiresCodeRange, v8::internal::Heap::MinOldGenerationSize(), v8::internal::Heap::MinYoungGenerationSize(), set_code_range_size_in_bytes(), set_initial_old_generation_size_in_bytes(), set_initial_young_generation_size_in_bytes(), set_max_old_generation_size_in_bytes(), and set_max_young_generation_size_in_bytes().
initial_old_generation_size_in_bytes()
size_t v8::ResourceConstraints::initial_old_generation_size_in_bytes () const [inline]
Definition at line 143 of file v8-isolate.h.
                                                      {
    return initial_old_generation_size_;
  }
Referenced by v8::internal::Heap::ConfigureHeap().
initial_young_generation_size_in_bytes()
size_t v8::ResourceConstraints::initial_young_generation_size_in_bytes () const [inline]
Definition at line 150 of file v8-isolate.h.
                                                        {
    return initial_young_generation_size_;
  }
Referenced by v8::internal::Heap::ConfigureHeap().
max_old_generation_size_in_bytes()
size_t v8::ResourceConstraints::max_old_generation_size_in_bytes () const [inline]
The maximum size of the old generation.
When the old generation approaches this limit, V8 will perform series of garbage collections and invoke the NearHeapLimitCallback. If the garbage collections do not help and the callback does not increase the limit, then V8 will crash with V8::FatalProcessOutOfMemory.
Definition at line 124 of file v8-isolate.h.
                                                  {
    return max_old_generation_size_;
  }
Referenced by v8::internal::Heap::ConfigureHeap().
max_young_generation_size_in_bytes()
size_t v8::ResourceConstraints::max_young_generation_size_in_bytes () const [inline]
The maximum size of the young generation, which consists of two semi-spaces and a large object space.
This affects frequency of Scavenge garbage collections and should be typically much smaller that the old generation.
Definition at line 136 of file v8-isolate.h.
                                                    {
    return max_young_generation_size_;
  }
Referenced by v8::internal::Heap::ConfigureHeap().
set_code_range_size_in_bytes()
void v8::ResourceConstraints::set_code_range_size_in_bytes (size_t limit) [inline]
Definition at line 115 of file v8-isolate.h.
{ code_range_size_ = limit; }
Referenced by ConfigureDefaults(), ConfigureDefaultsFromHeapSize(), and main().
set_initial_old_generation_size_in_bytes()
void v8::ResourceConstraints::set_initial_old_generation_size_in_bytes (size_t initial_size) [inline]
Definition at line 146 of file v8-isolate.h.
                                                                     {
    initial_old_generation_size_ = initial_size;
  }
Referenced by ConfigureDefaultsFromHeapSize().
set_initial_young_generation_size_in_bytes()
void v8::ResourceConstraints::set_initial_young_generation_size_in_bytes (size_t initial_size) [inline]
Definition at line 153 of file v8-isolate.h.
                                                                       {
    initial_young_generation_size_ = initial_size;
  }
Referenced by ConfigureDefaultsFromHeapSize().
set_max_old_generation_size_in_bytes()
void v8::ResourceConstraints::set_max_old_generation_size_in_bytes (size_t limit) [inline]
Definition at line 127 of file v8-isolate.h.
                                                          {
    max_old_generation_size_ = limit;
  }
Referenced by ConfigureDefaults(), and ConfigureDefaultsFromHeapSize().
set_max_young_generation_size_in_bytes()
void v8::ResourceConstraints::set_max_young_generation_size_in_bytes (size_t limit) [inline]
Definition at line 139 of file v8-isolate.h.
                                                            {
    max_young_generation_size_ = limit;
  }
Referenced by ConfigureDefaults(), and ConfigureDefaultsFromHeapSize().
set_stack_limit()
void v8::ResourceConstraints::set_stack_limit (uint32_t * value) [inline]
Definition at line 103 of file v8-isolate.h.
{ stack_limit_ = value; }
References v8::internal::value.
stack_limit()
uint32_t* v8::ResourceConstraints::stack_limit () const [inline]
The address beyond which the VM's stack may not grow.
Definition at line 102 of file v8-isolate.h.
{ return stack_limit_; }
Referenced by v8::Isolate::Initialize().
Member Data Documentation
code_range_size_
size_t v8::ResourceConstraints::code_range_size_ = 0 [private]
Definition at line 159 of file v8-isolate.h.
initial_old_generation_size_
size_t v8::ResourceConstraints::initial_old_generation_size_ = 0 [private]
Definition at line 162 of file v8-isolate.h.
initial_young_generation_size_
size_t v8::ResourceConstraints::initial_young_generation_size_ = 0 [private]
Definition at line 163 of file v8-isolate.h.
kMB
constexpr size_t v8::ResourceConstraints::kMB = 1048576u [static], [constexpr], [private]
Definition at line 158 of file v8-isolate.h.
max_old_generation_size_
size_t v8::ResourceConstraints::max_old_generation_size_ = 0 [private]
Definition at line 160 of file v8-isolate.h.
max_young_generation_size_
size_t v8::ResourceConstraints::max_young_generation_size_ = 0 [private]
Definition at line 161 of file v8-isolate.h.
stack_limit_
uint32_t* v8::ResourceConstraints::stack_limit_ = nullptr [private]
Definition at line 164 of file v8-isolate.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-isolate.h
/mnt/V8SourceCode/src/api/api.cc