v8::internal::compiler::OperatorProperties Class Reference
#include <operator-properties.h>
Public Member Functions
OperatorProperties (const OperatorProperties &)=delete
OperatorProperties & operator= (const OperatorProperties &)=delete
Static Public Member Functions
static bool HasContextInput (const Operator *op)
static int GetContextInputCount (const Operator *op)
static bool NeedsExactContext (const Operator *op)
static bool HasFrameStateInput (const Operator *op)
static int GetFrameStateInputCount (const Operator *op)
static int GetTotalInputCount (const Operator *op)
static bool IsBasicBlockBegin (const Operator *op)
Detailed Description
Definition at line 17 of file operator-properties.h.
Constructor & Destructor Documentation
OperatorProperties()
v8::internal::compiler::OperatorProperties::OperatorProperties (const OperatorProperties &) [delete]
Member Function Documentation
GetContextInputCount()
static int v8::internal::compiler::OperatorProperties::GetContextInputCount (const Operator * op) [inline], [static]
Definition at line 23 of file operator-properties.h.
                                                      {
    return HasContextInput(op) ? 1 : 0;
  }
Referenced by v8::internal::compiler::Verifier::Visitor::Check(), GetTotalInputCount(), v8::internal::compiler::NodeProperties::IsContextEdge(), v8::internal::compiler::NodeProperties::PastContextIndex(), and v8::internal::compiler::GraphC1Visualizer::PrintInputs().
GetFrameStateInputCount()
static int v8::internal::compiler::OperatorProperties::GetFrameStateInputCount (const Operator * op) [inline], [static]
Definition at line 30 of file operator-properties.h.
                                                         {
    return HasFrameStateInput(op) ? 1 : 0;
  }
Referenced by v8::internal::compiler::JSBinopReduction::ChangeToSpeculativeOperator(), v8::internal::compiler::Verifier::Visitor::Check(), GetTotalInputCount(), v8::internal::compiler::NodeProperties::IsFrameStateEdge(), v8::internal::compiler::NodeProperties::PastFrameStateIndex(), v8::internal::compiler::BytecodeGraphBuilder::PrepareEagerCheckpoint(), v8::internal::compiler::GraphC1Visualizer::PrintInputs(), v8::internal::compiler::JSTypedLowering::ReduceJSAdd(), and v8::internal::compiler::RepresentationSelector::VisitFrameState().
GetTotalInputCount()
int v8::internal::compiler::OperatorProperties::GetTotalInputCount (const Operator * op) [static]
Definition at line 277 of file operator-properties.cc.
                                                             {
  return op->ValueInputCount() + GetContextInputCount(op) +
         GetFrameStateInputCount(op) + op->EffectInputCount() +
         op->ControlInputCount();
}
References v8::internal::compiler::Operator::ControlInputCount(), v8::internal::compiler::Operator::EffectInputCount(), GetContextInputCount(), GetFrameStateInputCount(), and v8::internal::compiler::Operator::ValueInputCount().
Referenced by v8::internal::compiler::SimplifiedOperatorReducer::Change(), and v8::internal::compiler::DeadCodeElimination::TrimMergeOrPhi().
HasContextInput()
bool v8::internal::compiler::OperatorProperties::HasContextInput (const Operator * op) [static]
Definition at line 17 of file operator-properties.cc.
                                                           {
  IrOpcode::Value opcode = static_cast<IrOpcode::Value>(op->opcode());
  return IrOpcode::IsJsOpcode(opcode);
}
References v8::internal::compiler::IrOpcode::IsJsOpcode(), and v8::internal::compiler::Operator::opcode().
Referenced by v8::internal::compiler::JSSpeculativeBinopBuilder::BuildSpeculativeOperation(), v8::internal::compiler::JSBinopReduction::ChangeToPureOperator(), v8::internal::compiler::JSBinopReduction::ChangeToSpeculativeOperator(), v8::internal::compiler::NodeProperties::GetContextInput(), NeedsExactContext(), v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorRestoreContextNoCell(), v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorRestoreInputOrDebugPos(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode(), and v8::internal::compiler::NodeProperties::ReplaceContextInput().
HasFrameStateInput()
bool v8::internal::compiler::OperatorProperties::HasFrameStateInput (const Operator * op) [static]
Definition at line 143 of file operator-properties.cc.
                                                              {
  switch (op->opcode()) {
    case IrOpcode::kCheckpoint:
    case IrOpcode::kFrameState:
      return true;
    case IrOpcode::kJSCallRuntime: {
      const CallRuntimeParameters& p = CallRuntimeParametersOf(op);
      return Linkage::NeedsFrameStateInput(p.id());
    }
    // Strict equality cannot lazily deoptimize.
    case IrOpcode::kJSStrictEqual:
      return false;
    // Generator creation cannot call back into arbitrary JavaScript.
    case IrOpcode::kJSCreateGeneratorObject:
      return false;
    // Binary operations
    case IrOpcode::kJSAdd:
    case IrOpcode::kJSSubtract:
    case IrOpcode::kJSMultiply:
    case IrOpcode::kJSDivide:
    case IrOpcode::kJSModulus:
    case IrOpcode::kJSExponentiate:
    // Bitwise operations
    case IrOpcode::kJSBitwiseOr:
    case IrOpcode::kJSBitwiseXor:
    case IrOpcode::kJSBitwiseAnd:
    // Shift operations
    case IrOpcode::kJSShiftLeft:
    case IrOpcode::kJSShiftRight:
    case IrOpcode::kJSShiftRightLogical:
    // Compare operations
    case IrOpcode::kJSEqual:
    case IrOpcode::kJSGreaterThan:
    case IrOpcode::kJSGreaterThanOrEqual:
    case IrOpcode::kJSLessThan:
    case IrOpcode::kJSLessThanOrEqual:
    case IrOpcode::kJSHasProperty:
    case IrOpcode::kJSHasInPrototypeChain:
    case IrOpcode::kJSInstanceOf:
    case IrOpcode::kJSOrdinaryHasInstance:
    // Object operations
    case IrOpcode::kJSCreate:
    case IrOpcode::kJSCreateArguments:
    case IrOpcode::kJSCreateArray:
    case IrOpcode::kJSCreateTypedArray:
    case IrOpcode::kJSCreateLiteralArray:
    case IrOpcode::kJSCreateArrayFromIterable:
    case IrOpcode::kJSCreateLiteralObject:
    case IrOpcode::kJSCreateLiteralRegExp:
    case IrOpcode::kJSCreateObject:
    case IrOpcode::kJSCloneObject:
    // Property access operations
    case IrOpcode::kJSDeleteProperty:
    case IrOpcode::kJSLoadGlobal:
    case IrOpcode::kJSLoadNamed:
    case IrOpcode::kJSLoadNamedFromSuper:
    case IrOpcode::kJSLoadProperty:
    case IrOpcode::kJSDefineKeyedOwnPropertyInLiteral:
    case IrOpcode::kJSStoreInArrayLiteral:
    case IrOpcode::kJSStoreGlobal:
    case IrOpcode::kJSSetNamedProperty:
    case IrOpcode::kJSDefineNamedOwnProperty:
    case IrOpcode::kJSSetKeyedProperty:
    case IrOpcode::kJSDefineKeyedOwnProperty:
    // Conversions
    case IrOpcode::kJSToLength:
    case IrOpcode::kJSToName:
    case IrOpcode::kJSToNumber:
    case IrOpcode::kJSToNumberConvertBigInt:
    case IrOpcode::kJSToBigInt:
    case IrOpcode::kJSToBigIntConvertNumber:
    case IrOpcode::kJSToNumeric:
    case IrOpcode::kJSToObject:
    case IrOpcode::kJSToString:
    case IrOpcode::kJSParseInt:
    // Call operations
    case IrOpcode::kJSConstructForwardVarargs:
    case IrOpcode::kJSConstruct:
    case IrOpcode::kJSConstructWithArrayLike:
    case IrOpcode::kJSConstructWithSpread:
    case IrOpcode::kJSConstructForwardAllArgs:
    case IrOpcode::kJSCallForwardVarargs:
    case IrOpcode::kJSCall:
    case IrOpcode::kJSCallWithArrayLike:
    case IrOpcode::kJSCallWithSpread:
#if V8_ENABLE_WEBASSEMBLY
    case IrOpcode::kJSWasmCall:
#endif // V8_ENABLE_WEBASSEMBLY
    // Misc operations
    case IrOpcode::kJSAsyncFunctionEnter:
    case IrOpcode::kJSAsyncFunctionReject:
    case IrOpcode::kJSAsyncFunctionResolve:
    case IrOpcode::kJSDetachContextCell:
    case IrOpcode::kJSForInEnumerate:
    case IrOpcode::kJSForInNext:
    case IrOpcode::kJSStackCheck:
    case IrOpcode::kJSDebugger:
    case IrOpcode::kJSGetSuperConstructor:
    case IrOpcode::kJSFindNonDefaultConstructorOrConstruct:
    case IrOpcode::kJSBitwiseNot:
    case IrOpcode::kJSDecrement:
    case IrOpcode::kJSIncrement:
    case IrOpcode::kJSNegate:
    case IrOpcode::kJSPromiseResolve:
    case IrOpcode::kJSRejectPromise:
    case IrOpcode::kJSResolvePromise:
    case IrOpcode::kJSPerformPromiseThen:
    case IrOpcode::kJSObjectIsArray:
    case IrOpcode::kJSRegExpTest:
    case IrOpcode::kJSGetImportMeta:
    case IrOpcode::kJSStoreContext:
    // Iterator protocol operations
    case IrOpcode::kJSGetIterator:
      return true;
    default:
      return false;
  }
}
References v8::internal::compiler::CallRuntimeParametersOf(), v8::internal::compiler::CallRuntimeParameters::id(), v8::internal::compiler::Linkage::NeedsFrameStateInput(), and v8::internal::compiler::Operator::opcode().
Referenced by v8::internal::compiler::JSSpeculativeBinopBuilder::BuildSpeculativeOperation(), v8::internal::compiler::JSBinopReduction::ChangeToSpeculativeOperator(), v8::internal::compiler::anonymous_namespace{js-generic-lowering.cc}::FrameStateFlagForCall(), v8::internal::compiler::NodeProperties::GetFrameStateInput(), v8::internal::compiler::BytecodeGraphBuilder::PrepareFrameState(), v8::internal::compiler::BytecodeGraphBuilder::PrepareFrameStateForFunctionEntryStackCheck(), v8::internal::compiler::BytecodeGraphBuilder::PrepareFrameStateForOSREntryStackCheck(), and v8::internal::compiler::NodeProperties::ReplaceFrameStateInput().
IsBasicBlockBegin()
bool v8::internal::compiler::OperatorProperties::IsBasicBlockBegin (const Operator * op) [static]
Definition at line 285 of file operator-properties.cc.
                                                             {
  Operator::Opcode const opcode = op->opcode();
  return opcode == IrOpcode::kStart || opcode == IrOpcode::kEnd ||
         opcode == IrOpcode::kDead || opcode == IrOpcode::kLoop ||
         opcode == IrOpcode::kMerge || opcode == IrOpcode::kIfTrue ||
         opcode == IrOpcode::kIfFalse || opcode == IrOpcode::kIfSuccess ||
         opcode == IrOpcode::kIfException || opcode == IrOpcode::kIfValue ||
         opcode == IrOpcode::kIfDefault;
}
References v8_inspector::anonymous_namespace{value-mirror.cc}::kEnd, v8::kStart, and v8::internal::compiler::Operator::opcode().
Referenced by v8::internal::compiler::FindInsertionPoint().
NeedsExactContext()
bool v8::internal::compiler::OperatorProperties::NeedsExactContext (const Operator * op) [static]
Definition at line 23 of file operator-properties.cc.
                                                             {
  DCHECK(HasContextInput(op));
  IrOpcode::Value const opcode = static_cast<IrOpcode::Value>(op->opcode());
  switch (opcode) {
#define CASE(Name, ...) case IrOpcode::k##Name:
    // Binary/unary operators, calls and constructor calls only
    // need the context to generate exceptions or lookup fields
    // on the native context, so passing any context is fine.
    JS_SIMPLE_BINOP_LIST(CASE)
    JS_CALL_OP_LIST(CASE)
    JS_CONSTRUCT_OP_LIST(CASE)
    JS_SIMPLE_UNOP_LIST(CASE)
#undef CASE
    case IrOpcode::kJSCloneObject:
    case IrOpcode::kJSCreate:
    case IrOpcode::kJSCreateLiteralArray:
    case IrOpcode::kJSCreateEmptyLiteralArray:
    case IrOpcode::kJSCreateLiteralObject:
    case IrOpcode::kJSCreateEmptyLiteralObject:
    case IrOpcode::kJSCreateArrayFromIterable:
    case IrOpcode::kJSCreateLiteralRegExp:
    case IrOpcode::kJSGetTemplateObject:
    case IrOpcode::kJSDetachContextCell:
    case IrOpcode::kJSForInEnumerate:
    case IrOpcode::kJSForInNext:
    case IrOpcode::kJSForInPrepare:
    case IrOpcode::kJSGeneratorRestoreContextNoCell:
    case IrOpcode::kJSGeneratorRestoreContinuation:
    case IrOpcode::kJSGeneratorRestoreInputOrDebugPos:
    case IrOpcode::kJSGeneratorRestoreRegister:
    case IrOpcode::kJSGetSuperConstructor:
    case IrOpcode::kJSLoadGlobal:
    case IrOpcode::kJSLoadMessage:
    case IrOpcode::kJSStackCheck:
    case IrOpcode::kJSStoreMessage:
    case IrOpcode::kJSGetIterator:
      return false;
    case IrOpcode::kJSCallRuntime:
      return Runtime::NeedsExactContext(CallRuntimeParametersOf(op).id());
    case IrOpcode::kJSCreateArguments:
      // For mapped arguments we need to access slots of context-allocated
      // variables if there's aliasing with formal parameters.
      return CreateArgumentsTypeOf(op) == CreateArgumentsType::kMappedArguments;
    case IrOpcode::kJSCreateBlockContext:
    case IrOpcode::kJSCreateClosure:
    case IrOpcode::kJSCreateFunctionContext:
    case IrOpcode::kJSCreateGeneratorObject:
    case IrOpcode::kJSCreateCatchContext:
    case IrOpcode::kJSCreateWithContext:
    case IrOpcode::kJSDebugger:
    case IrOpcode::kJSDefineKeyedOwnProperty:
    case IrOpcode::kJSDeleteProperty:
    case IrOpcode::kJSGeneratorStore:
    case IrOpcode::kJSGetImportMeta:
    case IrOpcode::kJSHasProperty:
    case IrOpcode::kJSHasContextExtension:
    case IrOpcode::kJSLoadContextNoCell:
    case IrOpcode::kJSLoadContext:
    case IrOpcode::kJSLoadModule:
    case IrOpcode::kJSLoadNamed:
    case IrOpcode::kJSLoadNamedFromSuper:
    case IrOpcode::kJSLoadProperty:
    case IrOpcode::kJSStoreContextNoCell:
    case IrOpcode::kJSStoreContext:
    case IrOpcode::kJSDefineKeyedOwnPropertyInLiteral:
    case IrOpcode::kJSStoreGlobal:
    case IrOpcode::kJSStoreInArrayLiteral:
    case IrOpcode::kJSStoreModule:
    case IrOpcode::kJSSetNamedProperty:
    case IrOpcode::kJSDefineNamedOwnProperty:
    case IrOpcode::kJSSetKeyedProperty:
    case IrOpcode::kJSFindNonDefaultConstructorOrConstruct:
      return true;
    case IrOpcode::kJSAsyncFunctionEnter:
    case IrOpcode::kJSAsyncFunctionReject:
    case IrOpcode::kJSAsyncFunctionResolve:
    case IrOpcode::kJSCreateArrayIterator:
    case IrOpcode::kJSCreateAsyncFunctionObject:
    case IrOpcode::kJSCreateBoundFunction:
    case IrOpcode::kJSCreateCollectionIterator:
    case IrOpcode::kJSCreateIterResultObject:
    case IrOpcode::kJSCreateStringIterator:
    case IrOpcode::kJSCreateKeyValueArray:
    case IrOpcode::kJSCreateObject:
    case IrOpcode::kJSCreateStringWrapper:
    case IrOpcode::kJSCreatePromise:
    case IrOpcode::kJSCreateTypedArray:
    case IrOpcode::kJSCreateArray:
    case IrOpcode::kJSFulfillPromise:
    case IrOpcode::kJSObjectIsArray:
    case IrOpcode::kJSPerformPromiseThen:
    case IrOpcode::kJSPromiseResolve:
    case IrOpcode::kJSRegExpTest:
    case IrOpcode::kJSRejectPromise:
    case IrOpcode::kJSResolvePromise:
      // These operators aren't introduced by BytecodeGraphBuilder and
      // thus we don't bother checking them. If you ever introduce one
      // of these early in the BytecodeGraphBuilder make sure to check
      // whether they are context-sensitive.
      break;
#define CASE(Name) case IrOpcode::k##Name:
      // Non-JavaScript operators don't have a notion of "context".
      COMMON_OP_LIST(CASE)
      CONTROL_OP_LIST(CASE)
      MACHINE_OP_LIST(CASE)
      MACHINE_SIMD128_OP_LIST(CASE)
      IF_WASM(MACHINE_SIMD256_OP_LIST, CASE)
      SIMPLIFIED_OP_LIST(CASE)
      break;
#undef CASE
  }
  UNREACHABLE();
}
References v8::internal::compiler::CallRuntimeParametersOf(), CASE, COMMON_OP_LIST, CONTROL_OP_LIST, v8::internal::compiler::CreateArgumentsTypeOf(), v8::internal::DCHECK(), HasContextInput(), IF_WASM, JS_CALL_OP_LIST, JS_CONSTRUCT_OP_LIST, JS_SIMPLE_BINOP_LIST, JS_SIMPLE_UNOP_LIST, v8::internal::kMappedArguments, MACHINE_OP_LIST, MACHINE_SIMD128_OP_LIST, MACHINE_SIMD256_OP_LIST, v8::internal::Runtime::NeedsExactContext(), v8::internal::compiler::Operator::opcode(), SIMPLIFIED_OP_LIST, and v8::internal::UNREACHABLE().
operator=()
OperatorProperties& v8::internal::compiler::OperatorProperties::operator= (const OperatorProperties &) [delete]
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/operator-properties.h
/mnt/V8SourceCode/src/compiler/operator-properties.cc