v8::internal::SharedReadOnlySpace Class Reference
#include <read-only-spaces.h>
Public Member Functions
SharedReadOnlySpace (Heap *heap, ReadOnlyArtifacts *artifacts)
SharedReadOnlySpace (const SharedReadOnlySpace &)=delete
void TearDown (MemoryAllocator *memory_allocator) override
Private Member Functions
SharedReadOnlySpace (Heap *heap)
Additional Inherited Members
Detailed Description
Definition at line 251 of file read-only-spaces.h.
Constructor & Destructor Documentation
SharedReadOnlySpace() [1/3]
v8::internal::SharedReadOnlySpace::SharedReadOnlySpace (Heap * heap, ReadOnlyArtifacts * artifacts)
Definition at line 512 of file read-only-spaces.cc.
    : SharedReadOnlySpace(heap) {
  accounting_stats_ = artifacts->accounting_stats();
  pages_ = artifacts->pages();
}
References v8::internal::ReadOnlyArtifacts::accounting_stats(), v8::internal::ReadOnlySpace::accounting_stats_, v8::internal::ReadOnlyArtifacts::pages(), and v8::internal::ReadOnlySpace::pages_.
SharedReadOnlySpace() [2/3]
v8::internal::SharedReadOnlySpace::SharedReadOnlySpace (const SharedReadOnlySpace &) [delete]
SharedReadOnlySpace() [3/3]
v8::internal::SharedReadOnlySpace::SharedReadOnlySpace (Heap * heap) [inline], [explicit], [private]
Definition at line 260 of file read-only-spaces.h.
                                           : ReadOnlySpace(heap) {
    is_marked_read_only_ = true;
  }
References v8::internal::ReadOnlySpace::is_marked_read_only_.
Member Function Documentation
TearDown()
void v8::internal::SharedReadOnlySpace::TearDown (MemoryAllocator * memory_allocator) [override], [virtual]
Reimplemented from v8::internal::ReadOnlySpace.
Definition at line 115 of file read-only-spaces.cc.
                                                                    {
  // SharedReadOnlySpaces do not tear down their own pages since they are either
  // freed down by the ReadOnlyArtifacts that contains them.
  pages_.clear();
  accounting_stats_.Clear();
}
References v8::internal::ReadOnlySpace::accounting_stats_, v8::internal::AllocationStats::Clear(), and v8::internal::ReadOnlySpace::pages_.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/read-only-spaces.h
/mnt/V8SourceCode/src/heap/read-only-spaces.cc