v8::internal::BytecodeArray::BodyDescriptor Class Reference
#include <objects-body-descriptors-inl.h>
Static Public Member Functions
template<typename ObjectVisitor >
static void IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor *v)
static int SizeOf (Tagged< Map > map, Tagged< HeapObject > obj)
Additional Inherited Members
Detailed Description
Definition at line 773 of file objects-body-descriptors-inl.h.
Member Function Documentation
IterateBody()
template<typename ObjectVisitor >
static void v8::internal::BytecodeArray::BodyDescriptor::IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor * v) [inline], [static]
Definition at line 776 of file objects-body-descriptors-inl.h.
                                                                    {
    IterateSelfIndirectPointer(obj, kBytecodeArrayIndirectPointerTag, v);
    IteratePointer(obj, kWrapperOffset, v);
    IterateProtectedPointer(obj, kSourcePositionTableOffset, v);
    IterateProtectedPointer(obj, kHandlerTableOffset, v);
    IterateProtectedPointer(obj, kConstantPoolOffset, v);
  }
References v8::internal::BodyDescriptorBase::IteratePointer(), v8::internal::BodyDescriptorBase::IterateProtectedPointer(), and v8::internal::BodyDescriptorBase::IterateSelfIndirectPointer().
SizeOf()
static int v8::internal::BytecodeArray::BodyDescriptor::SizeOf (Tagged< Map > map, Tagged< HeapObject > obj) [inline], [static]
Definition at line 785 of file objects-body-descriptors-inl.h.
                                                                    {
    return BytecodeArray::SizeFor(
        Cast<BytecodeArray>(obj)->length(kAcquireLoad));
  }
References v8::kAcquireLoad, v8::internal::BytecodeArray::length(), and v8::internal::BytecodeArray::SizeFor().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/objects-body-descriptors-inl.h