v8::internal::DotPrinterImpl Class Reference
Public Member Functions
DotPrinterImpl (std::ostream &os)
void PrintNode (const char *label, RegExpNode *node)
void Visit (RegExpNode *node)
void PrintAttributes (RegExpNode *from)
void PrintOnFailure (RegExpNode *from, RegExpNode *to)
Private Attributes
std::ostream & os_
Detailed Description
Definition at line 17 of file regexp-dotprinter.cc.
Constructor & Destructor Documentation
DotPrinterImpl()
v8::internal::DotPrinterImpl::DotPrinterImpl (std::ostream & os) [inline], [explicit]
Definition at line 19 of file regexp-dotprinter.cc.
: os_(os) {}
Member Function Documentation
PrintAttributes()
void v8::internal::DotPrinterImpl::PrintAttributes (RegExpNode * from)
Definition at line 96 of file regexp-dotprinter.cc.
                                                     {
  os_ << " a" << that << " [shape=Mrecord, color=grey, fontcolor=grey, "
      << "margin=0.1, fontsize=10, label=\"{";
  AttributePrinter printer(os_);
  NodeInfo* info = that->info();
  printer.PrintBit("NI", info->follows_newline_interest);
  printer.PrintBit("WI", info->follows_word_interest);
  printer.PrintBit("SI", info->follows_start_interest);
  Label* label = that->label();
  if (label->is_bound()) printer.PrintPositive("@", label->pos());
  os_ << "}\"];\n"
      << " a" << that << " -> n" << that
      << " [style=dashed, color=grey, arrowhead=none];\n";
}
References v8::internal::NodeInfo::follows_newline_interest, v8::internal::NodeInfo::follows_start_interest, v8::internal::NodeInfo::follows_word_interest, v8::internal::RegExpNode::info(), v8::internal::Label::is_bound(), v8::internal::RegExpNode::label(), os_, v8::internal::Label::pos(), v8::internal::AttributePrinter::PrintBit(), and v8::internal::AttributePrinter::PrintPositive().
PrintNode()
void v8::internal::DotPrinterImpl::PrintNode (const char * label, RegExpNode * node)
Definition at line 31 of file regexp-dotprinter.cc.
                                                                  {
  os_ << "digraph G {\n graph [label=\"";
  for (int i = 0; label[i]; i++) {
    switch (label[i]) {
      case '\\':
        os_ << "\\\\";
        break;
      case '"':
        os_ << "\"";
        break;
      default:
        os_ << label[i];
        break;
    }
    if (i > 40) {
      os_ << "...";
      break;
    }
  }
  os_ << "\"];\n";
  Visit(node);
  os_ << "}" << std::endl;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, os_, and Visit().
Referenced by v8::internal::DotPrinter::DotPrint().
PrintOnFailure()
void v8::internal::DotPrinterImpl::PrintOnFailure (RegExpNode * from, RegExpNode * to)
Definition at line 61 of file regexp-dotprinter.cc.
                                                                            {
  os_ << " n" << from << " -> n" << on_failure << " [style=dotted];\n";
  Visit(on_failure);
}
References os_, and Visit().
Visit()
void v8::internal::DotPrinterImpl::Visit (RegExpNode * node)
Definition at line 55 of file regexp-dotprinter.cc.
                                           {
  if (node->info()->visited) return;
  node->info()->visited = true;
  node->Accept(this);
}
References v8::internal::RegExpNode::Accept(), v8::internal::RegExpNode::info(), and v8::internal::NodeInfo::visited.
Referenced by PrintNode(), and PrintOnFailure().
Member Data Documentation
os_
std::ostream& v8::internal::DotPrinterImpl::os_ [private]
Definition at line 28 of file regexp-dotprinter.cc.
Referenced by PrintAttributes(), PrintNode(), and PrintOnFailure().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/regexp/regexp-dotprinter.cc