v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion > Class Template Reference
#include <threaded-list.h>
Classes
class ConstIterator
class Iterator
Public Member Functions
ThreadedListBase ()
ThreadedListBase (const ThreadedListBase &)=delete
ThreadedListBase & operator= (const ThreadedListBase &)=delete
void Add (T *v)
void AddFront (T *v)
void DropHead ()
bool Contains (T *v)
void Append (ThreadedListBase &&list)
void Prepend (ThreadedListBase &&list)
void TruncateAt (ThreadedListBase *rem, T *v)
void Clear ()
ThreadedListBase & operator= (ThreadedListBase &&other) V8_NOEXCEPT
ThreadedListBase (ThreadedListBase &&other) V8_NOEXCEPT
bool Remove (T *v)
Iterator begin ()
Iterator end ()
ConstIterator begin () const
ConstIterator end () const
void Rewind (Iterator reset_point)
void MoveTail (ThreadedListBase *from_list, Iterator from_location)
Iterator RemoveAt (Iterator it)
bool is_empty () const
T * first () const
int LengthForTest ()
T * AtForTest (int i)
bool Verify () const
void EnsureValidTail () const
Static Public Member Functions
static void AddAfter (T *after_this, T *v)
Private Attributes
T * head_
T ** tail_
Detailed Description
template<typename T, typename BaseClass, typename TLTraits = ThreadedListTraits<T>, bool kSupportsUnsafeInsertion = false>
class v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >
Definition at line 35 of file threaded-list.h.
Constructor & Destructor Documentation
ThreadedListBase() [1/3]
template<typename T , typename BaseClass , typename TLTraits = ThreadedListTraits<T>, bool kSupportsUnsafeInsertion = false>
v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::ThreadedListBase () [inline]
Definition at line 37 of file threaded-list.h.
: head_(nullptr), tail_(&head_) {}
ThreadedListBase() [2/3]
template<typename T , typename BaseClass , typename TLTraits = ThreadedListTraits<T>, bool kSupportsUnsafeInsertion = false>
v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::ThreadedListBase (const ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion > &) [delete]
ThreadedListBase() [3/3]
template<typename T , typename BaseClass , typename TLTraits = ThreadedListTraits<T>, bool kSupportsUnsafeInsertion = false>
v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::ThreadedListBase (ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion > && other) [inline]
Definition at line 151 of file threaded-list.h.
      : head_(other.head_),
        tail_(other.head_ ? other.tail_ : &head_) {
#ifdef DEBUG
    other.Clear();
#endif
  }
Member Function Documentation
Add()
template<typename T , typename BaseClass , typename TLTraits = ThreadedListTraits<T>, bool kSupportsUnsafeInsertion = false>
void v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Add (T * v) [inline]
Definition at line 41 of file threaded-list.h.
                 {
    EnsureValidTail();
    DCHECK_NULL(*tail_);
    DCHECK_NULL(*TLTraits::next(v));
    *tail_ = v;
    tail_ = TLTraits::next(v);
    // Check that only one element was added (and that hasn't created a cycle).
    DCHECK_NULL(*tail_);
  }
References DCHECK_NULL, v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::EnsureValidTail(), and v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::tail_.
Referenced by v8::internal::maglev::BasicBlock::AddExceptionHandler(), v8::internal::maglev::BasicBlock::AddPhi(), v8::internal::Scope::AddUnresolved(), v8::internal::PrivateNameScopeIterator::AddUnresolvedPrivateName(), v8::internal::Scope::AnalyzePartially(), v8::internal::maglev::MergePointInterpreterFrameState::MergeValue(), v8::internal::maglev::MergePointInterpreterFrameState::MergeVirtualObjectValue(), v8::internal::ClassScope::MigrateUnresolvedPrivateNameTail(), v8::internal::maglev::MergePointInterpreterFrameState::New(), v8::internal::maglev::MergePointInterpreterFrameState::NewExceptionPhi(), and v8::internal::maglev::MergePointInterpreterFrameState::NewLoopPhi().
AddAfter()
template<typename T , typename BaseClass , typename TLTraits = ThreadedListTraits<T>, bool kSupportsUnsafeInsertion = false>
static void v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::AddAfter (T * after_this, T * v) [inline], [static]
Definition at line 63 of file threaded-list.h.
                                            {
    DCHECK(kSupportsUnsafeInsertion);
    DCHECK_NULL(*TLTraits::next(v));
    *TLTraits::next(v) = *TLTraits::next(after_this);
    *TLTraits::next(after_this) = v;
  }
References DCHECK, and DCHECK_NULL.
AddFront()
template<typename T , typename BaseClass , typename TLTraits = ThreadedListTraits<T>, bool kSupportsUnsafeInsertion = false>
void v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::AddFront (T * v) [inline]
Definition at line 51 of file threaded-list.h.
                      {
    DCHECK_NULL(*TLTraits::next(v));
    DCHECK_NOT_NULL(v);
    T** const next = TLTraits::next(v);
    *next = head_;
    if (head_ == nullptr) tail_ = next;
    head_ = v;
  }
References DCHECK_NOT_NULL, DCHECK_NULL, v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::head_, and v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::tail_.
Append()
template<typename T , typename BaseClass , typename TLTraits = ThreadedListTraits<T>, bool kSupportsUnsafeInsertion = false>
void v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Append (ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion > && list) [inline]
Definition at line 86 of file threaded-list.h.
                                       {
    if (list.is_empty()) return;
    EnsureValidTail();
    *tail_ = list.head_;
    tail_ = list.tail_;
    list.Clear();
  }
References v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::EnsureValidTail(), and v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::tail_.
Referenced by v8::internal::maglev::MaglevInliner::BuildInlineFunction(), and v8::internal::ClassScope::MigrateUnresolvedPrivateNameTail().
AtForTest()
template<typename T , typename BaseClass , typename TLTraits = ThreadedListTraits<T>, bool kSupportsUnsafeInsertion = false>
T* v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::AtForTest (int i) [inline]
Definition at line 320 of file threaded-list.h.
                      {
    Iterator t = begin();
    while (i-- > 0) ++t;
    return *t;
  }
References v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::begin().
begin() [1/2]
template<typename T , typename BaseClass , typename TLTraits = ThreadedListTraits<T>, bool kSupportsUnsafeInsertion = false>
Iterator v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::begin () [inline]
Definition at line 257 of file threaded-list.h.
{ return Iterator(TLTraits::start(&head_)); }
References v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::head_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::AtForTest(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Contains(), v8::internal::maglev::StraightForwardRegisterAllocator::InitializeBranchTargetPhis(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::LengthForTest(), v8::internal::maglev::LiveRangeAndNextUseProcessor::MarkJumpInputUses(), v8::internal::ClassScope::MigrateUnresolvedPrivateNameTail(), v8::internal::maglev::MaglevPhiRepresentationSelector::PreProcessBasicBlock(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::RemoveAt(), v8::internal::DeclarationScope::TakeUnresolvedReferencesFromParent(), and v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::TruncateAt().
begin() [2/2]
template<typename T , typename BaseClass , typename TLTraits = ThreadedListTraits<T>, bool kSupportsUnsafeInsertion = false>
ConstIterator v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::begin () const [inline]
Definition at line 263 of file threaded-list.h.
{ return ConstIterator(TLTraits::start(&head_)); }
References v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::head_.
Clear()
template<typename T , typename BaseClass , typename TLTraits = ThreadedListTraits<T>, bool kSupportsUnsafeInsertion = false>
void v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Clear () [inline]
Definition at line 137 of file threaded-list.h.
               {
    head_ = nullptr;
    tail_ = &head_;
  }
References v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::head_, and v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::tail_.
Referenced by v8::internal::Scope::AnalyzePartially(), v8::internal::Scope::FinalizeBlockScope(), v8::internal::ClassScope::MigrateUnresolvedPrivateNameTail(), v8::internal::DeclarationScope::ResetAfterPreparsing(), v8::internal::ClassScope::ResetUnresolvedPrivateNameTail(), v8::internal::ClassScope::ResolvePrivateNames(), v8::internal::Scope::SetDefaults(), and v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::TruncateAt().
Contains()
template<typename T , typename BaseClass , typename TLTraits = ThreadedListTraits<T>, bool kSupportsUnsafeInsertion = false>
bool v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Contains (T * v) [inline]
Definition at line 79 of file threaded-list.h.
                      {
    for (Iterator it = begin(); it != end(); ++it) {
      if (*it == v) return true;
    }
    return false;
  }
References v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::begin(), and v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::end().
Referenced by v8::internal::Scope::DeleteUnresolved().
DropHead()
template<typename T , typename BaseClass , typename TLTraits = ThreadedListTraits<T>, bool kSupportsUnsafeInsertion = false>
void v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::DropHead () [inline]
Definition at line 70 of file threaded-list.h.
                  {
    DCHECK_NOT_NULL(head_);
    T* old_head = head_;
    head_ = *TLTraits::next(head_);
    if (head_ == nullptr) tail_ = &head_;
    *TLTraits::next(old_head) = nullptr;
  }
References DCHECK_NOT_NULL, v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::head_, and v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::tail_.
Referenced by v8::internal::maglev::MaglevInliner::BuildInlineFunction(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Remove(), and v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::RemoveAt().
end() [1/2]
template<typename T , typename BaseClass , typename TLTraits = ThreadedListTraits<T>, bool kSupportsUnsafeInsertion = false>
Iterator v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::end () [inline]
Definition at line 258 of file threaded-list.h.
                 {
    EnsureValidTail();
    return Iterator(tail_);
  }
References v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::EnsureValidTail(), and v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::tail_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Contains(), v8::internal::ClassScope::GetUnresolvedPrivateNameTail(), v8::internal::maglev::StraightForwardRegisterAllocator::InitializeBranchTargetPhis(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::LengthForTest(), v8::internal::maglev::LiveRangeAndNextUseProcessor::MarkJumpInputUses(), v8::internal::ClassScope::MigrateUnresolvedPrivateNameTail(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::MoveTail(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::RemoveAt(), v8::internal::ClassScope::ResetUnresolvedPrivateNameTail(), and v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::TruncateAt().
end() [2/2]
template<typename T , typename BaseClass , typename TLTraits = ThreadedListTraits<T>, bool kSupportsUnsafeInsertion = false>
ConstIterator v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::end () const [inline]
Definition at line 264 of file threaded-list.h.
                            {
    EnsureValidTail();
    return ConstIterator(tail_);
  }
References v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::EnsureValidTail(), and v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::tail_.
EnsureValidTail()
template<typename T , typename BaseClass , typename TLTraits = ThreadedListTraits<T>, bool kSupportsUnsafeInsertion = false>
void v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::EnsureValidTail () const [inline]
Definition at line 339 of file threaded-list.h.
                                      {
    if (!kSupportsUnsafeInsertion) {
      DCHECK_EQ(*tail_, nullptr);
      return;
    }
    // If kSupportsUnsafeInsertion, then we support adding a new element by
    // using the pointer to a certain element. E.g., imagine list A -> B -> C,
    // we can add D after B, by just moving the pointer of B to D and D to
    // whatever B used to point to. We do not need to know the beginning of the
    // list (ie. to have a pointer to the ThreadList class). This however might
    // break the tail_ invariant. We ensure this here, by manually looking for
    // the tail of the list.
    if (*tail_ == nullptr) return;
    T* last = *tail_;
    if (last != nullptr) {
      while (*TLTraits::next(last) != nullptr) {
        last = *TLTraits::next(last);
      }
      tail_ = TLTraits::next(last);
    }
  }
References DCHECK_EQ, and v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::tail_.
Referenced by v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Add(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Append(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::end(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Prepend(), and v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Remove().
first()
template<typename T , typename BaseClass , typename TLTraits = ThreadedListTraits<T>, bool kSupportsUnsafeInsertion = false>
T* v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::first () const [inline]
Definition at line 311 of file threaded-list.h.
{ return head_; }
References v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::head_.
Referenced by v8::internal::Scope::AnalyzePartially(), v8::internal::maglev::BasicBlock::first_id(), v8::internal::maglev::BasicBlock::FirstNonGapMoveId(), v8::internal::maglev::MergePointInterpreterFrameState::MergeValue(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Remove(), v8::internal::ClassScope::ResolvePrivateNamesPartially(), and v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Verify().
is_empty()
template<typename T , typename BaseClass , typename TLTraits = ThreadedListTraits<T>, bool kSupportsUnsafeInsertion = false>
bool v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::is_empty () const [inline]
Definition at line 309 of file threaded-list.h.
{ return head_ == nullptr; }
References v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::head_.
Referenced by v8::internal::Scope::FinalizeBlockScope(), v8::internal::maglev::MergePointInterpreterFrameState::has_phi(), v8::internal::Scope::Snapshot::Reparent(), v8::internal::ClassScope::ResolvePrivateNames(), v8::internal::ClassScope::ResolvePrivateNamesPartially(), and v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::TruncateAt().
LengthForTest()
template<typename T , typename BaseClass , typename TLTraits = ThreadedListTraits<T>, bool kSupportsUnsafeInsertion = false>
int v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::LengthForTest () [inline]
Definition at line 314 of file threaded-list.h.
                      {
    int result = 0;
    for (Iterator t = begin(); t != end(); ++t) ++result;
    return result;
  }
References v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::begin(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::end(), and v8::base::internal::result.
Referenced by v8::internal::maglev::MergePointInterpreterFrameState::MergeValue(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
MoveTail()
template<typename T , typename BaseClass , typename TLTraits = ThreadedListTraits<T>, bool kSupportsUnsafeInsertion = false>
void v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::MoveTail (ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion > * from_list, Iterator from_location) [inline]
Definition at line 278 of file threaded-list.h.
                                                                     {
    if (from_list->end() != from_location) {
      DCHECK_NULL(*tail_);
      *tail_ = *from_location;
      tail_ = from_list->tail_;
      from_list->Rewind(from_location);
    }
  }
References DCHECK_NULL, v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::end(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Rewind(), and v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::tail_.
Referenced by v8::internal::Scope::Snapshot::Reparent(), and v8::internal::DeclarationScope::TakeUnresolvedReferencesFromParent().
operator=() [1/2]
template<typename T , typename BaseClass , typename TLTraits = ThreadedListTraits<T>, bool kSupportsUnsafeInsertion = false>
ThreadedListBase& v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::operator= (const ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion > &) [delete]
operator=() [2/2]
template<typename T , typename BaseClass , typename TLTraits = ThreadedListTraits<T>, bool kSupportsUnsafeInsertion = false>
ThreadedListBase& v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::operator= (ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion > && other) [inline]
Definition at line 142 of file threaded-list.h.
                                                                    {
    head_ = other.head_;
    tail_ = other.head_ ? other.tail_ : &head_;
#ifdef DEBUG
    other.Clear();
#endif
    return *this;
  }
References v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::head_, and v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::tail_.
Prepend()
template<typename T , typename BaseClass , typename TLTraits = ThreadedListTraits<T>, bool kSupportsUnsafeInsertion = false>
void v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Prepend (ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion > && list) [inline]
Definition at line 95 of file threaded-list.h.
                                        {
    if (list.head_ == nullptr) return;
    EnsureValidTail();
    T* new_head = list.head_;
    *list.tail_ = head_;
    if (head_ == nullptr) {
      tail_ = list.tail_;
    }
    head_ = new_head;
    list.Clear();
  }
References v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::EnsureValidTail(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::head_, and v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::tail_.
Referenced by v8::internal::Scope::FinalizeBlockScope().
Remove()
template<typename T , typename BaseClass , typename TLTraits = ThreadedListTraits<T>, bool kSupportsUnsafeInsertion = false>
bool v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Remove (T * v) [inline]
Definition at line 159 of file threaded-list.h.
                    {
    T* current = first();
    if (current == v) {
      DropHead();
      return true;
    }
    EnsureValidTail();
    while (current != nullptr) {
      T* next = *TLTraits::next(current);
      if (next == v) {
        *TLTraits::next(current) = *TLTraits::next(next);
        *TLTraits::next(next) = nullptr;
        if (TLTraits::next(next) == tail_) {
          tail_ = TLTraits::next(current);
        }
        return true;
      }
      current = next;
    }
    return false;
  }
References v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::DropHead(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::EnsureValidTail(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::first(), and v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::tail_.
Referenced by v8::internal::ClassScope::ResolvePrivateNamesPartially().
RemoveAt()
template<typename T , typename BaseClass , typename TLTraits = ThreadedListTraits<T>, bool kSupportsUnsafeInsertion = false>
Iterator v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::RemoveAt (Iterator it) [inline]
Definition at line 293 of file threaded-list.h.
                                 {
    if (*it.entry_ == head_) {
      DropHead();
      return begin();
    } else if (tail_ == TLTraits::next(*it.entry_)) {
      tail_ = it.entry_;
      *it.entry_ = nullptr;
      return end();
    } else {
      T* old_entry = *it.entry_;
      *it.entry_ = *TLTraits::next(*it.entry_);
      *TLTraits::next(old_entry) = nullptr;
      return Iterator(it.entry_);
    }
  }
References v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::begin(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::DropHead(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::end(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Iterator::entry_, v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::head_, and v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::tail_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters(), v8::internal::maglev::StraightForwardRegisterAllocator::InitializeBranchTargetPhis(), and v8::internal::maglev::LiveRangeAndNextUseProcessor::MarkJumpInputUses().
Rewind()
template<typename T , typename BaseClass , typename TLTraits = ThreadedListTraits<T>, bool kSupportsUnsafeInsertion = false>
void v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Rewind (Iterator reset_point) [inline]
Definition at line 271 of file threaded-list.h.
                                    {
    tail_ = reset_point.entry_;
    *tail_ = nullptr;
  }
References v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Iterator::entry_, and v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::tail_.
Referenced by v8::internal::ClassScope::MigrateUnresolvedPrivateNameTail(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::MoveTail(), and v8::internal::ClassScope::ResetUnresolvedPrivateNameTail().
TruncateAt()
template<typename T , typename BaseClass , typename TLTraits = ThreadedListTraits<T>, bool kSupportsUnsafeInsertion = false>
void v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::TruncateAt (ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion > * rem, T * v) [inline]
Definition at line 109 of file threaded-list.h.
                                               {
    CHECK_NOT_NULL(rem);
    CHECK_NOT_NULL(v);
    CHECK(rem->is_empty());
    Iterator it = begin();
    T* last = nullptr;
    for (; it != end(); ++it) {
      if (*it == v) {
        break;
      }
      last = *it;
    }
    CHECK_EQ(v, *it);
    // Remaining list.
    rem->head_ = v;
    rem->tail_ = tail_;
    if (last == nullptr) {
      // The head must point to v, so we return the empty list.
      CHECK_EQ(head_, v);
      Clear();
    } else {
      tail_ = TLTraits::next(last);
      *tail_ = nullptr;
    }
  }
References v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::begin(), CHECK, CHECK_EQ, CHECK_NOT_NULL, v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Clear(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::end(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::head_, v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::is_empty(), and v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::tail_.
Referenced by v8::internal::maglev::MaglevInliner::BuildInlineFunction().
Verify()
template<typename T , typename BaseClass , typename TLTraits = ThreadedListTraits<T>, bool kSupportsUnsafeInsertion = false>
bool v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Verify () const [inline]
Definition at line 326 of file threaded-list.h.
                      {
    T* last = this->first();
    if (last == nullptr) {
      CHECK_EQ(&head_, tail_);
    } else {
      while (*TLTraits::next(last) != nullptr) {
        last = *TLTraits::next(last);
      }
      CHECK_EQ(TLTraits::next(last), tail_);
    }
    return true;
  }
References CHECK_EQ, v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::first(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::head_, and v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::tail_.
Member Data Documentation
head_
template<typename T , typename BaseClass , typename TLTraits = ThreadedListTraits<T>, bool kSupportsUnsafeInsertion = false>
T* v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::head_ [private]
Definition at line 362 of file threaded-list.h.
Referenced by v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::AddFront(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::begin(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Clear(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::DropHead(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::first(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::is_empty(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::operator=(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Prepend(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::RemoveAt(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::TruncateAt(), and v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Verify().
tail_
template<typename T , typename BaseClass , typename TLTraits = ThreadedListTraits<T>, bool kSupportsUnsafeInsertion = false>
T** v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::tail_ [mutable], [private]
Definition at line 363 of file threaded-list.h.
Referenced by v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Add(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::AddFront(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Append(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Clear(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::DropHead(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::end(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::EnsureValidTail(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::MoveTail(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::operator=(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Prepend(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Remove(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::RemoveAt(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Rewind(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::TruncateAt(), and v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::Verify().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/base/threaded-list.h