v8::internal::maglev::InterpretedDeoptFrame Class Reference
#include <maglev-ir.h>
Public Member Functions
InterpretedDeoptFrame (const MaglevCompilationUnit &unit, const CompactInterpreterFrameState *frame_state, ValueNode *closure, BytecodeOffset bytecode_position, SourcePosition source_position, DeoptFrame *parent)
const MaglevCompilationUnit & unit () const
const CompactInterpreterFrameState * frame_state () const
ValueNode *& closure ()
ValueNode * closure () const
BytecodeOffset bytecode_position () const
SourcePosition source_position () const
int ComputeReturnOffset (interpreter::Register result_location, int result_size) const
Private Member Functions
InterpretedFrameData & data ()
const InterpretedFrameData & data () const
Additional Inherited Members
Detailed Description
Definition at line 1594 of file maglev-ir.h.
Constructor & Destructor Documentation
InterpretedDeoptFrame()
v8::internal::maglev::InterpretedDeoptFrame::InterpretedDeoptFrame (const MaglevCompilationUnit & unit, const CompactInterpreterFrameState * frame_state, ValueNode * closure, BytecodeOffset bytecode_position, SourcePosition source_position, DeoptFrame * parent) [inline]
Definition at line 1596 of file maglev-ir.h.
      : DeoptFrame(InterpretedFrameData{unit, frame_state, closure,
                                        bytecode_position, source_position},
                   parent) {}
Member Function Documentation
bytecode_position()
BytecodeOffset v8::internal::maglev::InterpretedDeoptFrame::bytecode_position () const [inline]
Definition at line 1610 of file maglev-ir.h.
{ return data().bytecode_position; }
References v8::internal::maglev::DeoptFrame::InterpretedFrameData::bytecode_position, and data().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildSingleDeoptFrame(), and v8::internal::maglev::DeoptFrame::GetBytecodeOffset().
closure() [1/2]
ValueNode*& v8::internal::maglev::InterpretedDeoptFrame::closure () [inline]
Definition at line 1608 of file maglev-ir.h.
{ return data().closure; }
References v8::internal::maglev::DeoptFrame::InterpretedFrameData::closure, and data().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildSingleDeoptFrame(), and v8::internal::maglev::MaglevGraphBuilder::GetDeoptFrameForLazyDeoptHelper().
closure() [2/2]
ValueNode* v8::internal::maglev::InterpretedDeoptFrame::closure () const [inline]
Definition at line 1609 of file maglev-ir.h.
{ return data().closure; }
References v8::internal::maglev::DeoptFrame::InterpretedFrameData::closure, and data().
ComputeReturnOffset()
int v8::internal::maglev::InterpretedDeoptFrame::ComputeReturnOffset (interpreter::Register result_location, int result_size) const
Definition at line 413 of file maglev-ir.cc.
                                                                {
  // Return offsets are counted from the end of the translation frame,
  // which is the array [parameters..., locals..., accumulator]. Since
  // it's the end, we don't need to worry about earlier frames.
  if (result_location == interpreter::Register::virtual_accumulator()) {
    return 0;
  } else if (result_location.is_parameter()) {
    // This is slightly tricky to reason about because of zero indexing
    // and fence post errors. As an example, consider a frame with 2
    // locals and 2 parameters, where we want argument index 1 -- looking
    // at the array in reverse order we have:
    // [acc, r1, r0, a1, a0]
    // ^
    // and this calculation gives, correctly:
    // 2 + 2 - 1 = 3
    return unit().register_count() + unit().parameter_count() -
           result_location.ToParameterIndex();
  } else {
    return unit().register_count() - result_location.index();
  }
}
References v8::internal::interpreter::Register::index(), v8::internal::interpreter::Register::is_parameter(), v8::internal::maglev::MaglevCompilationUnit::parameter_count(), v8::internal::maglev::MaglevCompilationUnit::register_count(), v8::internal::interpreter::Register::ToParameterIndex(), unit(), and v8::internal::interpreter::Register::virtual_accumulator().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildSingleDeoptFrame().
data() [1/2]
InterpretedFrameData& v8::internal::maglev::InterpretedDeoptFrame::data () [inline], [private]
Definition at line 1617 of file maglev-ir.h.
{ return data_.get<InterpretedFrameData>(); }
References v8::internal::maglev::DeoptFrame::data_, and v8::base::DiscriminatedUnion< TagEnum, Ts >::get().
Referenced by bytecode_position(), closure(), frame_state(), source_position(), and unit().
data() [2/2]
const InterpretedFrameData& v8::internal::maglev::InterpretedDeoptFrame::data () const [inline], [private]
Definition at line 1618 of file maglev-ir.h.
                                           {
    return data_.get<InterpretedFrameData>();
  }
References v8::internal::maglev::DeoptFrame::data_, and v8::base::DiscriminatedUnion< TagEnum, Ts >::get().
frame_state()
const CompactInterpreterFrameState* v8::internal::maglev::InterpretedDeoptFrame::frame_state () const [inline]
Definition at line 1605 of file maglev-ir.h.
                                                          {
    return data().frame_state;
  }
References data(), and v8::internal::maglev::DeoptFrame::InterpretedFrameData::frame_state.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildSingleDeoptFrame(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::EmitTrampolineFor(), v8::internal::maglev::MaglevGraphBuilder::GetDeoptFrameForLazyDeoptHelper(), v8::internal::maglev::DeoptFrame::GetVirtualObjects(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ThrowingScope::ThrowingScope().
source_position()
SourcePosition v8::internal::maglev::InterpretedDeoptFrame::source_position () const [inline]
Definition at line 1611 of file maglev-ir.h.
{ return data().source_position; }
References data(), and v8::internal::maglev::DeoptFrame::InterpretedFrameData::source_position.
Referenced by v8::internal::maglev::DeoptFrame::GetSourcePosition().
unit()
const MaglevCompilationUnit& v8::internal::maglev::InterpretedDeoptFrame::unit () const [inline]
Definition at line 1604 of file maglev-ir.h.
{ return data().unit; }
References data(), and v8::internal::maglev::DeoptFrame::InterpretedFrameData::unit.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildSingleDeoptFrame(), ComputeReturnOffset(), v8::internal::maglev::MaxCallDepthProcessor::ConservativeFrameSize(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::EmitTrampolineFor(), v8::internal::maglev::DeoptFrame::GetCompilationUnit(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ThrowingScope::ThrowingScope(), and v8::internal::maglev::MaxCallDepthProcessor::UpdateMaxDeoptedStackSize().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc