v8::internal::compiler::CheckpointElimination Class Reference
#include <checkpoint-elimination.h>
Public Member Functions
CheckpointElimination (Editor *editor)
~CheckpointElimination () final=default
const char * reducer_name () const override
Reduction Reduce (Node *node) final
Private Member Functions
Reduction ReduceCheckpoint (Node *node)
Detailed Description
Definition at line 16 of file checkpoint-elimination.h.
Constructor & Destructor Documentation
CheckpointElimination()
v8::internal::compiler::CheckpointElimination::CheckpointElimination (Editor * editor) [explicit]
Definition at line 14 of file checkpoint-elimination.cc.
    : AdvancedReducer(editor) {}
 CheckpointElimination()
v8::internal::compiler::CheckpointElimination::~CheckpointElimination () [final], [default]
Member Function Documentation
Reduce()
Reduction v8::internal::compiler::CheckpointElimination::Reduce (Node * node) [final]
Definition at line 62 of file checkpoint-elimination.cc.
                                                  {
  DisallowHeapAccess no_heap_access;
  switch (node->opcode()) {
    case IrOpcode::kCheckpoint:
      return ReduceCheckpoint(node);
    default:
      break;
  }
  return NoChange();
}
References v8::internal::compiler::Node::opcode(), and ReduceCheckpoint().
ReduceCheckpoint()
Reduction v8::internal::compiler::CheckpointElimination::ReduceCheckpoint (Node * node) [private]
Definition at line 54 of file checkpoint-elimination.cc.
                                                            {
  DCHECK_EQ(IrOpcode::kCheckpoint, node->opcode());
  if (IsRedundantCheckpoint(node)) {
    return Replace(NodeProperties::GetEffectInput(node));
  }
  return NoChange();
}
References DCHECK_EQ, v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::anonymous_namespace{checkpoint-elimination.cc}::IsRedundantCheckpoint(), v8::internal::compiler::Node::opcode(), and v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace().
Referenced by Reduce().
reducer_name()
const char* v8::internal::compiler::CheckpointElimination::reducer_name () const [inline], [override]
Definition at line 22 of file checkpoint-elimination.h.
{ return "CheckpointElimination"; }
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/checkpoint-elimination.h
/mnt/V8SourceCode/src/compiler/checkpoint-elimination.cc