v8::internal::ProfileNode Class Reference
#include <profile-generator.h>
Classes
struct Equals
struct Hasher
Public Member Functions
ProfileNode (ProfileTree *tree, CodeEntry *entry, ProfileNode *parent, LineAndColumn line_and_column={})
~ProfileNode ()
ProfileNode (const ProfileNode &)=delete
ProfileNode & operator= (const ProfileNode &)=delete
ProfileNode * FindChild (CodeEntry *entry, LineAndColumn line_and_column={})
ProfileNode * FindOrAddChild (CodeEntry *entry, LineAndColumn line_and_column)
void IncrementSelfTicks ()
void IncreaseSelfTicks (unsigned amount)
void IncrementLineAndColumnTicks (LineAndColumn line_and_column)
CodeEntry * entry () const
unsigned self_ticks () const
const std::vector< ProfileNode * > * children () const
unsigned id () const
ProfileNode * parent () const
LineAndColumn line_and_column () const
CpuProfileNode::SourceType source_type () const
unsigned int GetHitLineCount () const
bool GetLineTicks (v8::CpuProfileNode::LineTick *entries, unsigned int length) const
void CollectDeoptInfo (CodeEntry *entry)
const std::vector< CpuProfileDeoptInfo > & deopt_infos () const
Isolate * isolate () const
void Print (int indent) const
Private Attributes
ProfileTree * tree_
CodeEntry * entry_
unsigned self_ticks_
std::unordered_map< CodeEntryAndPosition, ProfileNode *, Hasher, Equals > children_
LineAndColumn line_and_column_
std::vector< ProfileNode * > children_list_
ProfileNode * parent_
unsigned id_
std::unordered_map< std::pair< int, int >, int > line_and_column_ticks_
std::vector< CpuProfileDeoptInfo > deopt_infos_
Detailed Description
Definition at line 300 of file profile-generator.h.
Constructor & Destructor Documentation
ProfileNode() [1/2]
v8::internal::ProfileNode::ProfileNode (ProfileTree * tree, CodeEntry * entry, ProfileNode * parent, LineAndColumn line_and_column = {}) [inline]
Definition at line 31 of file profile-generator-inl.h.
    : tree_(tree),
      entry_(entry),
      self_ticks_(0),
      line_and_column_(line_and_column),
      parent_(parent),
      id_(tree->next_node_id()) {
  tree_->EnqueueNode(this);
  if (tree_->code_entries()) tree_->code_entries()->AddRef(entry_);
}
References v8::internal::CodeEntryStorage::AddRef(), v8::internal::ProfileTree::code_entries(), v8::internal::ProfileTree::EnqueueNode(), entry_, and tree_.
Referenced by FindOrAddChild().
 ProfileNode()
v8::internal::ProfileNode::~ProfileNode ()
Definition at line 337 of file profile-generator.cc.
                          {
  if (tree_->code_entries()) tree_->code_entries()->DecRef(entry_);
}
References v8::internal::ProfileTree::code_entries(), v8::internal::CodeEntryStorage::DecRef(), entry_, and tree_.
ProfileNode() [2/2]
v8::internal::ProfileNode::ProfileNode (const ProfileNode &) [delete]
Member Function Documentation
children()
const std::vector<ProfileNode*>* v8::internal::ProfileNode::children () const [inline]
Definition at line 316 of file profile-generator.h.
{ return &children_list_; }
Referenced by v8::internal::Position::current_child(), and v8::internal::Position::has_current_child().
CollectDeoptInfo()
void v8::internal::ProfileNode::CollectDeoptInfo (CodeEntry * entry)
Definition at line 374 of file profile-generator.cc.
                                                   {
  deopt_infos_.push_back(entry->GetDeoptInfo());
  entry->clear_deopt_info();
}
References v8::internal::CodeEntry::clear_deopt_info(), deopt_infos_, entry(), and v8::internal::CodeEntry::GetDeoptInfo().
Referenced by v8::internal::ProfileTree::AddPathFromEnd().
deopt_infos()
const std::vector<CpuProfileDeoptInfo>& v8::internal::ProfileNode::deopt_infos () const [inline]
Definition at line 331 of file profile-generator.h.
                                                            {
    return deopt_infos_;
  }
Referenced by v8::CpuProfileNode::GetDeoptInfos().
entry()
CodeEntry* v8::internal::ProfileNode::entry () const [inline]
Definition at line 314 of file profile-generator.h.
{ return entry_; }
Referenced by v8::internal::anonymous_namespace{profile-generator.cc}::BuildNodeValue(), CollectDeoptInfo(), FindChild(), FindOrAddChild(), v8::CpuProfileNode::GetBailoutReason(), v8::CpuProfileNode::GetFunctionName(), v8::CpuProfileNode::GetFunctionNameStr(), GetLineTicks(), v8::CpuProfileNode::GetScriptId(), v8::CpuProfileNode::GetScriptResourceName(), v8::CpuProfileNode::GetScriptResourceNameStr(), and v8::CpuProfileNode::IsScriptSharedCrossOrigin().
FindChild()
ProfileNode * v8::internal::ProfileNode::FindChild (CodeEntry * entry, LineAndColumn line_and_column = {})
Definition at line 379 of file profile-generator.cc.
                                                                   {
  auto map_entry = children_.find({entry, line_and_column});
  return map_entry != children_.end() ? map_entry->second : nullptr;
}
References children_, entry(), and line_and_column().
FindOrAddChild()
ProfileNode * v8::internal::ProfileNode::FindOrAddChild (CodeEntry * entry, LineAndColumn line_and_column)
Definition at line 385 of file profile-generator.cc.
                                                                        {
  auto map_entry = children_.find({entry, line_and_column});
  if (map_entry == children_.end()) {
    ProfileNode* node = new ProfileNode(tree_, entry, this, line_and_column);
    children_[{entry, line_and_column}] = node;
    children_list_.push_back(node);
    return node;
  } else {
    return map_entry->second;
  }
}
References children_, children_list_, entry(), line_and_column(), ProfileNode(), and tree_.
Referenced by v8::internal::ProfileTree::AddPathFromEnd().
GetHitLineCount()
unsigned int v8::internal::ProfileNode::GetHitLineCount () const [inline]
Definition at line 325 of file profile-generator.h.
                                       {
    return static_cast<unsigned int>(line_and_column_ticks_.size());
  }
Referenced by v8::CpuProfileNode::GetHitLineCount().
GetLineTicks()
bool v8::internal::ProfileNode::GetLineTicks (v8::CpuProfileNode::LineTick * entries, unsigned int length) const
Definition at line 405 of file profile-generator.cc.
                                                          {
  if (entries == nullptr || length == 0) return false;
  unsigned line_count = static_cast<unsigned>(line_and_column_ticks_.size());
  if (line_count == 0) return true;
  if (length < line_count) return false;
  v8::CpuProfileNode::LineTick* entry = entries;
  for (auto p = line_and_column_ticks_.begin();
       p != line_and_column_ticks_.end(); p++, entry++) {
    entry->line = p->first.first;
    entry->column = p->first.second;
    entry->hit_count = p->second;
  }
  return true;
}
References entry(), v8::internal::length, and line_and_column_ticks_.
Referenced by v8::CpuProfileNode::GetLineTicks().
id()
unsigned v8::internal::ProfileNode::id () const [inline]
Definition at line 317 of file profile-generator.h.
{ return id_; }
Referenced by v8::internal::anonymous_namespace{profile-generator.cc}::BuildNodeValue(), and v8::internal::CpuProfileJSONSerializer::SerializeSamples().
IncreaseSelfTicks()
void v8::internal::ProfileNode::IncreaseSelfTicks (unsigned amount) [inline]
Definition at line 311 of file profile-generator.h.
{ self_ticks_ += amount; }
IncrementLineAndColumnTicks()
void v8::internal::ProfileNode::IncrementLineAndColumnTicks (LineAndColumn line_and_column)
Definition at line 398 of file profile-generator.cc.
                                                                           {
  if (line_and_column.line == v8::CpuProfileNode::kNoLineNumberInfo) return;
  // Increment a hit counter of a certain source line.
  // Adds a new source line if not found.
  line_and_column_ticks_[{line_and_column.line, line_and_column.column}]++;
}
References v8::internal::LineAndColumn::column, v8::CpuProfileNode::kNoLineNumberInfo, v8::internal::LineAndColumn::line, line_and_column(), and line_and_column_ticks_.
Referenced by v8::internal::ProfileTree::AddPathFromEnd().
IncrementSelfTicks()
void v8::internal::ProfileNode::IncrementSelfTicks () [inline]
Definition at line 310 of file profile-generator.h.
{ ++self_ticks_; }
Referenced by v8::internal::ProfileTree::AddPathFromEnd().
isolate()
Isolate * v8::internal::ProfileNode::isolate () const [inline]
Definition at line 43 of file profile-generator-inl.h.
{ return tree_->isolate(); }
References v8::internal::ProfileTree::isolate(), and tree_.
Referenced by v8::CpuProfileNode::GetFunctionName(), and v8::CpuProfileNode::GetScriptResourceName().
line_and_column()
LineAndColumn v8::internal::ProfileNode::line_and_column () const [inline]
Definition at line 319 of file profile-generator.h.
                                        {
    return line_and_column_.line != 0 ? line_and_column_
                                      : entry_->line_and_column();
  }
References v8::internal::LineAndColumn::line.
Referenced by FindChild(), FindOrAddChild(), IncrementLineAndColumnTicks(), and Print().
operator=()
ProfileNode& v8::internal::ProfileNode::operator= (const ProfileNode &) [delete]
parent()
ProfileNode* v8::internal::ProfileNode::parent () const [inline]
Definition at line 318 of file profile-generator.h.
{ return parent_; }
Referenced by v8::internal::anonymous_namespace{profile-generator.cc}::BuildNodeValue().
Print()
void v8::internal::ProfileNode::Print (int indent) const
Definition at line 426 of file profile-generator.cc.
                                        {
  LineAndColumn line_and_column = this->line_and_column();
  base::OS::Print("%5u %*s %s:%d:%d %d %d #%d", self_ticks_, indent, "",
                  entry_->name(), line_and_column.line, line_and_column.column,
                  source_type(), entry_->script_id(), id());
  if (entry_->resource_name()[0] != '\0')
    base::OS::Print(" %s:%d:%d", entry_->resource_name(),
                    entry_->line_and_column().line,
                    entry_->line_and_column().column);
  base::OS::Print("\n");
  for (const CpuProfileDeoptInfo& info : deopt_infos_) {
    base::OS::Print(
        "%*s;;; deopted at script_id: %d position: %zu with reason '%s'.\n",
        indent + 10, "", info.stack[0].script_id, info.stack[0].position,
        info.deopt_reason);
    for (size_t index = 1; index < info.stack.size(); ++index) {
      base::OS::Print("%*s;;; Inline point: script_id %d position: %zu.\n",
                      indent + 10, "", info.stack[index].script_id,
                      info.stack[index].position);
    }
  }
  const char* bailout_reason = entry_->bailout_reason();
  if (bailout_reason != GetBailoutReason(BailoutReason::kNoReason) &&
      bailout_reason != CodeEntry::kEmptyBailoutReason) {
    base::OS::Print("%*s bailed out due to '%s'\n", indent + 10, "",
                    bailout_reason);
  }
  for (auto child : children_) {
    child.second->Print(indent + 2);
  }
}
References v8::internal::CodeEntry::bailout_reason(), children_, v8::internal::LineAndColumn::column, deopt_infos_, entry_, v8::internal::GetBailoutReason(), v8::internal::index, v8::internal::CodeEntry::kEmptyBailoutReason, v8::internal::LineAndColumn::line, v8::internal::CodeEntry::line_and_column(), line_and_column(), v8::internal::CodeEntry::name(), v8::internal::Print(), v8::internal::CodeEntry::resource_name(), v8::internal::CodeEntry::script_id(), self_ticks_, and source_type().
Referenced by v8::Shell::Main().
self_ticks()
unsigned v8::internal::ProfileNode::self_ticks () const [inline]
Definition at line 315 of file profile-generator.h.
{ return self_ticks_; }
source_type()
CpuProfileNode::SourceType v8::internal::ProfileNode::source_type () const
Definition at line 341 of file profile-generator.cc.
                                                        {
  // Handle metadata and VM state code entry types.
  if (entry_ == CodeEntry::program_entry() ||
      entry_ == CodeEntry::idle_entry() || entry_ == CodeEntry::gc_entry() ||
      entry_ == CodeEntry::root_entry()) {
    return CpuProfileNode::kInternal;
  }
  if (entry_ == CodeEntry::unresolved_entry())
    return CpuProfileNode::kUnresolved;
  // Otherwise, resolve based on logger tag.
  switch (entry_->code_tag()) {
    case LogEventListener::CodeTag::kEval:
    case LogEventListener::CodeTag::kScript:
    case LogEventListener::CodeTag::kFunction:
      return CpuProfileNode::kScript;
    case LogEventListener::CodeTag::kBuiltin:
    case LogEventListener::CodeTag::kHandler:
    case LogEventListener::CodeTag::kBytecodeHandler:
    case LogEventListener::CodeTag::kNativeFunction:
    case LogEventListener::CodeTag::kNativeScript:
      return CpuProfileNode::kBuiltin;
    case LogEventListener::CodeTag::kCallback:
      return CpuProfileNode::kCallback;
    case LogEventListener::CodeTag::kRegExp:
    case LogEventListener::CodeTag::kStub:
    case LogEventListener::CodeTag::kLength:
      return CpuProfileNode::kInternal;
  }
  return CpuProfileNode::kInternal;
  UNREACHABLE();
}
References v8::internal::CodeEntry::code_tag(), entry_, v8::internal::CodeEntry::gc_entry(), v8::internal::CodeEntry::idle_entry(), v8::CpuProfileNode::kBuiltin, v8::CpuProfileNode::kCallback, v8::internal::torque::ls::kFunction, v8::CpuProfileNode::kInternal, v8::CpuProfileNode::kScript, v8::CpuProfileNode::kUnresolved, v8::internal::CodeEntry::program_entry(), v8::internal::CodeEntry::root_entry(), v8::internal::UNREACHABLE(), and v8::internal::CodeEntry::unresolved_entry().
Referenced by Print().
Member Data Documentation
children_
std::unordered_map<CodeEntryAndPosition, ProfileNode*, Hasher, Equals> v8::internal::ProfileNode::children_ [private]
Definition at line 359 of file profile-generator.h.
Referenced by FindChild(), FindOrAddChild(), and Print().
children_list_
std::vector<ProfileNode*> v8::internal::ProfileNode::children_list_ [private]
Definition at line 361 of file profile-generator.h.
Referenced by FindOrAddChild().
deopt_infos_
std::vector<CpuProfileDeoptInfo> v8::internal::ProfileNode::deopt_infos_ [private]
Definition at line 367 of file profile-generator.h.
Referenced by CollectDeoptInfo(), and Print().
entry_
CodeEntry* v8::internal::ProfileNode::entry_ [private]
Definition at line 356 of file profile-generator.h.
Referenced by Print(), ProfileNode(), source_type(), and ~ProfileNode().
id_
unsigned v8::internal::ProfileNode::id_ [private]
Definition at line 363 of file profile-generator.h.
line_and_column_
LineAndColumn v8::internal::ProfileNode::line_and_column_ [private]
Definition at line 360 of file profile-generator.h.
line_and_column_ticks_
std::unordered_map<std::pair<int, int>, int> v8::internal::ProfileNode::line_and_column_ticks_ [private]
Definition at line 365 of file profile-generator.h.
Referenced by GetLineTicks(), and IncrementLineAndColumnTicks().
parent_
ProfileNode* v8::internal::ProfileNode::parent_ [private]
Definition at line 362 of file profile-generator.h.
self_ticks_
unsigned v8::internal::ProfileNode::self_ticks_ [private]
Definition at line 357 of file profile-generator.h.
Referenced by Print().
tree_
ProfileTree* v8::internal::ProfileNode::tree_ [private]
Definition at line 355 of file profile-generator.h.
Referenced by FindOrAddChild(), isolate(), ProfileNode(), and ~ProfileNode().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/profiler/profile-generator.h
/mnt/V8SourceCode/src/profiler/profile-generator-inl.h
/mnt/V8SourceCode/src/profiler/profile-generator.cc