v8::internal::compiler::WasmLoadElimination::HalfState Class Reference
Public Member Functions
HalfState (Zone *zone)
bool Equals (HalfState const *that) const
bool IsEmpty () const
void IntersectWith (HalfState const *that)
HalfState const * KillField (int field_index, Node *object) const
HalfState const * AddField (int field_index, Node *object, Node *value) const
FieldOrElementValue LookupField (int field_index, Node *object) const
void Print () const
Private Types
using InnerMap = PersistentMap< Node *, FieldOrElementValue >
template<typename OuterKey >
using OuterMap = PersistentMap< OuterKey, InnerMap >
using FieldInfos = OuterMap< int >
using ElementInfos = OuterMap< Node * >
Static Private Member Functions
template<typename OuterKey >
static void Update (OuterMap< OuterKey > &map, OuterKey outer_key, Node *inner_key, FieldOrElementValue info)
static void Print (const FieldInfos &infos)
static void Print (const ElementInfos &infos)
Private Attributes
Zone * zone_
FieldInfos fields_
ElementInfos elements_
Detailed Description
Definition at line 53 of file wasm-load-elimination.h.
Member Typedef Documentation
ElementInfos
using v8::internal::compiler::WasmLoadElimination::HalfState::ElementInfos = OuterMap<Node*> [private]
Definition at line 80 of file wasm-load-elimination.h.
FieldInfos
using v8::internal::compiler::WasmLoadElimination::HalfState::FieldInfos = OuterMap<int> [private]
Definition at line 78 of file wasm-load-elimination.h.
InnerMap
using v8::internal::compiler::WasmLoadElimination::HalfState::InnerMap = PersistentMap<Node*, FieldOrElementValue> [private]
Definition at line 74 of file wasm-load-elimination.h.
OuterMap
template<typename OuterKey >
using v8::internal::compiler::WasmLoadElimination::HalfState::OuterMap = PersistentMap<OuterKey, InnerMap> [private]
Definition at line 76 of file wasm-load-elimination.h.
Constructor & Destructor Documentation
HalfState()
v8::internal::compiler::WasmLoadElimination::HalfState::HalfState (Zone * zone) [inline], [explicit]
Definition at line 55 of file wasm-load-elimination.h.
        : zone_(zone),
          fields_(zone, InnerMap(zone)),
          elements_(zone, InnerMap(zone)) {}
Member Function Documentation
AddField()
WasmLoadElimination::HalfState const * v8::internal::compiler::WasmLoadElimination::HalfState::AddField (int field_index, Node * object, Node * value) const
Definition at line 499 of file wasm-load-elimination.cc.
                                                      {
  HalfState* new_state = zone_->New<HalfState>(*this);
  Update(new_state->fields_, field_index, object, FieldOrElementValue(value));
  return new_state;
}
References fields_, v8::internal::Zone::New(), v8::internal::value, and v8::internal::compiler::WasmLoadElimination::zone_.
Referenced by v8::internal::compiler::WasmLoadElimination::ReduceLoadLikeFromImmutable(), v8::internal::compiler::WasmLoadElimination::ReduceStringPrepareForGetCodeunit(), v8::internal::compiler::WasmLoadElimination::ReduceWasmArrayInitializeLength(), v8::internal::compiler::WasmLoadElimination::ReduceWasmStructGet(), and v8::internal::compiler::WasmLoadElimination::ReduceWasmStructSet().
Equals()
bool v8::internal::compiler::WasmLoadElimination::HalfState::Equals (HalfState const * that) const [inline]
Definition at line 60 of file wasm-load-elimination.h.
                                             {
      return fields_ == that->fields_ && elements_ == that->elements_;
    }
References elements_, and fields_.
IntersectWith()
void v8::internal::compiler::WasmLoadElimination::HalfState::IntersectWith (HalfState const * that)
Definition at line 567 of file wasm-load-elimination.cc.
                                                                      {
  FieldOrElementValue empty;
  for (const std::pair<int, InnerMap> to_map : fields_) {
    InnerMap to_map_copy(to_map.second);
    int key = to_map.first;
    const InnerMap& current_map = that->fields_.Get(key);
    for (std::pair<Node*, FieldOrElementValue> value : to_map.second) {
      if (current_map.Get(value.first) != value.second) {
        to_map_copy.Set(value.first, empty);
      }
    }
    fields_.Set(key, to_map_copy);
  }
}
References fields_, v8::internal::compiler::PersistentMap< Key, Value, Hasher >::Get(), v8::internal::key, v8::internal::compiler::PersistentMap< Key, Value, Hasher >::Set(), and v8::internal::value.
IsEmpty()
bool v8::internal::compiler::WasmLoadElimination::HalfState::IsEmpty () const [inline]
Definition at line 63 of file wasm-load-elimination.h.
                         {
      return fields_.begin() == fields_.end() &&
             elements_.begin() == elements_.end();
    }
Referenced by v8::internal::compiler::WasmLoadElimination::ComputeLoopState().
KillField()
WasmLoadElimination::HalfState const * v8::internal::compiler::WasmLoadElimination::HalfState::KillField (int field_index, Node * object) const
Definition at line 506 of file wasm-load-elimination.cc.
                                         {
  const InnerMap& same_index_map = fields_.Get(field_index);
  InnerMap new_map(same_index_map);
  for (std::pair<Node*, FieldOrElementValue> pair : same_index_map) {
    if (MayAlias(pair.first, object)) {
      new_map.Set(pair.first, FieldOrElementValue());
    }
  }
  HalfState* result = zone_->New<HalfState>(*this);
  result->fields_.Set(field_index, new_map);
  return result;
}
References v8::internal::compiler::PersistentMap< Key, Value, Hasher >::Get(), v8::internal::compiler::anonymous_namespace{wasm-load-elimination.cc}::MayAlias(), v8::internal::Zone::New(), v8::base::internal::result, v8::internal::compiler::PersistentMap< Key, Value, Hasher >::Set(), and v8::internal::compiler::WasmLoadElimination::zone_.
Referenced by v8::internal::compiler::WasmLoadElimination::ComputeLoopState(), and v8::internal::compiler::WasmLoadElimination::ReduceWasmStructSet().
LookupField()
WasmLoadElimination::FieldOrElementValue v8::internal::compiler::WasmLoadElimination::HalfState::LookupField (int field_index, Node * object) const
Definition at line 494 of file wasm-load-elimination.cc.
                                                                {
  return fields_.Get(field_index).Get(object);
}
References fields_, and v8::internal::compiler::PersistentMap< Key, Value, Hasher >::Get().
Referenced by v8::internal::compiler::WasmLoadElimination::ReduceLoadLikeFromImmutable(), v8::internal::compiler::WasmLoadElimination::ReduceStringPrepareForGetCodeunit(), v8::internal::compiler::WasmLoadElimination::ReduceWasmArrayInitializeLength(), v8::internal::compiler::WasmLoadElimination::ReduceWasmStructGet(), and v8::internal::compiler::WasmLoadElimination::ReduceWasmStructSet().
Print() [1/3]
void v8::internal::compiler::WasmLoadElimination::HalfState::Print () const
Print() [2/3]
static void v8::internal::compiler::WasmLoadElimination::HalfState::Print (const ElementInfos & infos) [static], [private]
Print() [3/3]
static void v8::internal::compiler::WasmLoadElimination::HalfState::Print (const FieldInfos & infos) [static], [private]
Update()
template<typename OuterKey >
static void v8::internal::compiler::WasmLoadElimination::HalfState::Update (OuterMap< OuterKey > & map, OuterKey outer_key, Node * inner_key, FieldOrElementValue info) [inline], [static], [private]
Definition at line 84 of file wasm-load-elimination.h.
                                                                  {
      InnerMap map_copy(map.Get(outer_key));
      map_copy.Set(inner_key, info);
      map.Set(outer_key, map_copy);
    }
References v8::internal::compiler::PersistentMap< Key, Value, Hasher >::Get(), and v8::internal::compiler::PersistentMap< Key, Value, Hasher >::Set().
Member Data Documentation
elements_
ElementInfos v8::internal::compiler::WasmLoadElimination::HalfState::elements_ [private]
Definition at line 96 of file wasm-load-elimination.h.
Referenced by Equals().
fields_
FieldInfos v8::internal::compiler::WasmLoadElimination::HalfState::fields_ [private]
Definition at line 95 of file wasm-load-elimination.h.
Referenced by AddField(), Equals(), IntersectWith(), and LookupField().
zone_
Zone* v8::internal::compiler::WasmLoadElimination::HalfState::zone_ [private]
Definition at line 94 of file wasm-load-elimination.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/wasm-load-elimination.h
/mnt/V8SourceCode/src/compiler/wasm-load-elimination.cc