v8::internal::maglev::Int32Constant Class Reference
#include <maglev-ir.h>
Public Types
using OutputRegister = Register
Public Member Functions
Int32Constant (uint64_t bitfield, int32_t value)
int32_t value () const
bool ToBoolean (LocalIsolate *local_isolate) const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
void DoLoadToRegister (MaglevAssembler *, OutputRegister)
DirectHandle< Object > DoReify (LocalIsolate *isolate) const
Static Public Attributes
static constexpr OpProperties kProperties = OpProperties::Int32()
Private Types
using Base = FixedInputValueNodeT< 0, Int32Constant >
Private Attributes
const int32_t value_
Additional Inherited Members
Detailed Description
Definition at line 3875 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::Int32Constant::Base = FixedInputValueNodeT<0, Int32Constant> [private]
Definition at line 3876 of file maglev-ir.h.
OutputRegister
using v8::internal::maglev::Int32Constant::OutputRegister = Register
Definition at line 3879 of file maglev-ir.h.
Constructor & Destructor Documentation
Int32Constant()
v8::internal::maglev::Int32Constant::Int32Constant (uint64_t bitfield, int32_t value) [inline], [explicit]
Definition at line 3881 of file maglev-ir.h.
      : Base(bitfield), value_(value) {}
Member Function Documentation
DoLoadToRegister()
void v8::internal::maglev::Int32Constant::DoLoadToRegister (MaglevAssembler * , OutputRegister)
DoReify()
DirectHandle< Object > v8::internal::maglev::Int32Constant::DoReify (LocalIsolate * isolate) const
Definition at line 1215 of file maglev-ir.cc.
                                                                       {
  return isolate->factory()->NewNumberFromInt<AllocationType::kOld>(value());
}
References v8::internal::LocalIsolate::factory(), v8::internal::kOld, v8::internal::FactoryBase< Impl >::NewNumberFromInt(), and value().
GenerateCode()
void v8::internal::maglev::Int32Constant::GenerateCode (MaglevAssembler * , const ProcessingState &)
PrintParams()
void v8::internal::maglev::Int32Constant::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 7894 of file maglev-ir.cc.
                                                                           {
  os << "(" << value() << ")";
}
References value().
SetValueLocationConstraints()
void v8::internal::maglev::Int32Constant::SetValueLocationConstraints ()
ToBoolean()
bool v8::internal::maglev::Int32Constant::ToBoolean (LocalIsolate * local_isolate) const [inline]
Definition at line 3888 of file maglev-ir.h.
{ return value_ != 0; }
References value_.
value()
int32_t v8::internal::maglev::Int32Constant::value () const [inline]
Definition at line 3886 of file maglev-ir.h.
{ return value_; }
References value_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildCheckNumericalValue(), DoReify(), PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
Member Data Documentation
kProperties
constexpr OpProperties v8::internal::maglev::Int32Constant::kProperties = OpProperties::Int32() [static], [constexpr]
Definition at line 3884 of file maglev-ir.h.
value_
const int32_t v8::internal::maglev::Int32Constant::value_ [private]
Definition at line 3898 of file maglev-ir.h.
Referenced by ToBoolean(), and value().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc