v8::internal::StackGuard Class Reference
#include <stack-guard.h>
Classes
class ThreadLocal
Public Types
enum class InterruptLevel { kNoGC
, kNoHeapWrites
, kAnyEffect
 }
enum InterruptFlag : uint32_t { ALL_INTERRUPTS = INTERRUPT_LIST(V) 0
 }
Public Member Functions
StackGuard (const StackGuard &)=delete
StackGuard & operator= (const StackGuard &)=delete
StackGuard (Isolate *isolate)
void SetStackLimit (uintptr_t limit)
void SetStackLimitForStackSwitching (uintptr_t limit)
char * ArchiveStackGuard (char *to)
char * RestoreStackGuard (char *from)
void FreeThreadResources ()
void InitThread (const ExecutionAccess &lock)
uintptr_t climit ()
uintptr_t jslimit ()
uintptr_t real_climit ()
uintptr_t real_jslimit ()
Address address_of_jslimit ()
Address address_of_real_jslimit ()
Address address_of_interrupt_request (InterruptLevel level)
Tagged< Object > HandleInterrupts (InterruptLevel level=InterruptLevel::kAnyEffect)
bool HasTerminationRequest ()
Static Public Member Functions
static int ArchiveSpacePerThread ()
static constexpr InterruptFlag InterruptLevelMask (InterruptLevel level)
static constexpr int jslimit_offset ()
static constexpr int real_jslimit_offset ()
static char * Iterate (RootVisitor *v, char *thread_storage)
Static Public Attributes
static constexpr int kNumberOfInterruptLevels = 3
static constexpr int kSizeInBytes = 8 * kSystemPointerSize
Private Member Functions
bool CheckInterrupt (InterruptFlag flag)
void RequestInterrupt (InterruptFlag flag)
void ClearInterrupt (InterruptFlag flag)
int FetchAndClearInterrupts (InterruptLevel level)
void SetStackLimitInternal (const ExecutionAccess &lock, uintptr_t limit, uintptr_t jslimit)
bool has_pending_interrupts (const ExecutionAccess &lock)
void update_interrupt_requests_and_stack_limits (const ExecutionAccess &lock)
void PushInterruptsScope (InterruptsScope *scope)
void PopInterruptsScope ()
Private Attributes
Isolate * isolate_
ThreadLocal thread_local_
Static Private Attributes
static const uintptr_t kInterruptLimit = 0xfffffffe
static const uintptr_t kIllegalLimit = 0xfffffff8
Friends
class Isolate
class StackLimitCheck
class InterruptsScope
Detailed Description
Definition at line 24 of file stack-guard.h.
Member Enumeration Documentation
InterruptFlag
enum v8::internal::StackGuard::InterruptFlag : uint32_t
Enumerator
ALL_INTERRUPTS
Definition at line 92 of file stack-guard.h.
                     : uint32_t {
#define V(NAME, Name, id, interrupt_level) NAME = (1 << id),
    INTERRUPT_LIST(V)
#undef V
#define V(NAME, Name, id, interrupt_level) NAME |
        ALL_INTERRUPTS = INTERRUPT_LIST(V) 0
#undef V
  };
InterruptLevel
enum v8::internal::StackGuard::InterruptLevel [strong]
Enumerator
kNoGC
kNoHeapWrites
kAnyEffect
Definition at line 65 of file stack-guard.h.
{ kNoGC, kNoHeapWrites, kAnyEffect };
Constructor & Destructor Documentation
StackGuard() [1/2]
v8::internal::StackGuard::StackGuard (const StackGuard &) [delete]
StackGuard() [2/2]
v8::internal::StackGuard::StackGuard (Isolate * isolate) [inline], [explicit]
Definition at line 29 of file stack-guard.h.
: isolate_(isolate) {}
Member Function Documentation
address_of_interrupt_request()
Address v8::internal::StackGuard::address_of_interrupt_request (InterruptLevel level) [inline]
Definition at line 135 of file stack-guard.h.
                                                             {
    return reinterpret_cast<Address>(
        &thread_local_.interrupt_requested_[static_cast<int>(level)]);
  }
address_of_jslimit()
Address v8::internal::StackGuard::address_of_jslimit () [inline]
Definition at line 129 of file stack-guard.h.
                               {
    return reinterpret_cast<Address>(&thread_local_.jslimit_);
  }
address_of_real_jslimit()
Address v8::internal::StackGuard::address_of_real_jslimit () [inline]
Definition at line 132 of file stack-guard.h.
                                    {
    return reinterpret_cast<Address>(&thread_local_.real_jslimit_);
  }
ArchiveSpacePerThread()
static int v8::internal::StackGuard::ArchiveSpacePerThread () [inline], [static]
Definition at line 54 of file stack-guard.h.
{ return sizeof(ThreadLocal); }
Referenced by v8::internal::ArchiveSpacePerThread().
ArchiveStackGuard()
char * v8::internal::StackGuard::ArchiveStackGuard (char * to)
Definition at line 228 of file stack-guard.cc.
                                            {
  ExecutionAccess access(isolate_);
  MemCopy(to, reinterpret_cast<char*>(&thread_local_), sizeof(ThreadLocal));
  thread_local_ = {};
  return to + sizeof(ThreadLocal);
}
References isolate_, v8::internal::MemCopy(), and thread_local_.
Referenced by v8::internal::ThreadManager::EagerlyArchiveThread().
CheckInterrupt()
bool v8::internal::StackGuard::CheckInterrupt (InterruptFlag flag) [private]
Definition at line 164 of file stack-guard.cc.
                                                  {
  ExecutionAccess access(isolate_);
  return (thread_local_.interrupt_flags_ & flag) != 0;
}
References v8::internal::StackGuard::ThreadLocal::interrupt_flags_, isolate_, and thread_local_.
ClearInterrupt()
void v8::internal::StackGuard::ClearInterrupt (InterruptFlag flag) [private]
Definition at line 185 of file stack-guard.cc.
                                                  {
  ExecutionAccess access(isolate_);
  // Clear the interrupt flag from the chain of InterruptsScope.
  for (InterruptsScope* current = thread_local_.interrupt_scopes_;
       current != nullptr; current = current->prev_) {
    current->intercepted_flags_ &= ~flag;
  }
  // Clear the interrupt flag from the active interrupt flags.
  thread_local_.interrupt_flags_ &= ~flag;
  update_interrupt_requests_and_stack_limits(access);
}
References v8::internal::StackGuard::ThreadLocal::interrupt_flags_, v8::internal::StackGuard::ThreadLocal::interrupt_scopes_, isolate_, v8::internal::InterruptsScope::prev_, thread_local_, and update_interrupt_requests_and_stack_limits().
climit()
uintptr_t v8::internal::StackGuard::climit () [inline]
Definition at line 110 of file stack-guard.h.
                     {
#ifdef USE_SIMULATOR
    return thread_local_.climit();
#else
    return thread_local_.jslimit();
#endif
  }
Referenced by v8::internal::StackLimitCheck::InterruptRequested().
FetchAndClearInterrupts()
int v8::internal::StackGuard::FetchAndClearInterrupts (InterruptLevel level) [private]
Definition at line 211 of file stack-guard.cc.
                                                            {
  ExecutionAccess access(isolate_);
  InterruptFlag mask = InterruptLevelMask(level);
  if ((thread_local_.interrupt_flags_ & TERMINATE_EXECUTION) != 0) {
    // The TERMINATE_EXECUTION interrupt is special, since it terminates
    // execution but should leave V8 in a resumable state. If it exists, we only
    // fetch and clear that bit. On resume, V8 can continue processing other
    // interrupts.
    mask = TERMINATE_EXECUTION;
  }
  int result = static_cast<int>(thread_local_.interrupt_flags_ & mask);
  thread_local_.interrupt_flags_ &= ~mask;
  update_interrupt_requests_and_stack_limits(access);
  return result;
}
References v8::internal::StackGuard::ThreadLocal::interrupt_flags_, InterruptLevelMask(), isolate_, v8::base::internal::result, thread_local_, and update_interrupt_requests_and_stack_limits().
Referenced by HandleInterrupts().
FreeThreadResources()
void v8::internal::StackGuard::FreeThreadResources ()
Definition at line 241 of file stack-guard.cc.
                                     {
  Isolate::PerIsolateThreadData* per_thread =
      isolate_->FindOrAllocatePerThreadDataForThisThread();
  per_thread->set_stack_limit(real_climit());
}
References v8::internal::Isolate::FindOrAllocatePerThreadDataForThisThread(), isolate_, and real_climit().
Referenced by v8::internal::ThreadManager::FreeThreadResources().
HandleInterrupts()
Tagged< Object > v8::internal::StackGuard::HandleInterrupts (InterruptLevel level = InterruptLevel::kAnyEffect)
Definition at line 298 of file stack-guard.cc.
                                                                {
  TRACE_EVENT0("v8.execute", "V8.HandleInterrupts");
#if DEBUG
  isolate_->heap()->VerifyNewSpaceTop();
#endif
  if (v8_flags.verify_predictable) {
    // Advance synthetic time by making a time request.
    isolate_->heap()->MonotonicallyIncreasingTimeInMs();
  }
  // Fetch and clear interrupt bits in one go. See comments inside the method
  // for special handling of TERMINATE_EXECUTION.
  int interrupt_flags = FetchAndClearInterrupts(level);
  // All interrupts should be fully processed when returning from this method.
  ShouldBeZeroOnReturnScope should_be_zero_on_return(&interrupt_flags);
  if (TestAndClear(&interrupt_flags, TERMINATE_EXECUTION)) {
    TRACE_EVENT0("v8.execute", "V8.TerminateExecution");
    return isolate_->TerminateExecution();
  }
  if (TestAndClear(&interrupt_flags, GC_REQUEST)) {
    TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.gc"), "V8.GCHandleGCRequest");
    isolate_->heap()->HandleGCRequest();
  }
  if (TestAndClear(&interrupt_flags, START_INCREMENTAL_MARKING)) {
    isolate_->heap()->StartIncrementalMarkingOnInterrupt();
  }
  if (TestAndClear(&interrupt_flags, GLOBAL_SAFEPOINT)) {
    TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.gc"), "V8.GlobalSafepoint");
    isolate_->main_thread_local_heap()->Safepoint();
  }
#if V8_ENABLE_WEBASSEMBLY
  if (TestAndClear(&interrupt_flags, GROW_SHARED_MEMORY)) {
    TRACE_EVENT0("v8.wasm", "V8.WasmGrowSharedMemory");
    BackingStore::UpdateSharedWasmMemoryObjects(isolate_);
  }
  if (TestAndClear(&interrupt_flags, LOG_WASM_CODE)) {
    TRACE_EVENT0("v8.wasm", "V8.LogCode");
    wasm::GetWasmEngine()->LogOutstandingCodesForIsolate(isolate_);
  }
  if (TestAndClear(&interrupt_flags, WASM_CODE_GC)) {
    TRACE_EVENT0("v8.wasm", "V8.WasmCodeGC");
    wasm::GetWasmEngine()->ReportLiveCodeFromStackForGC(isolate_);
  }
#endif // V8_ENABLE_WEBASSEMBLY
  if (TestAndClear(&interrupt_flags, DEOPT_MARKED_ALLOCATION_SITES)) {
    TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.gc"),
                 "V8.GCDeoptMarkedAllocationSites");
    isolate_->heap()->DeoptMarkedAllocationSites();
  }
  if (TestAndClear(&interrupt_flags, INSTALL_CODE)) {
    TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
                 "V8.InstallOptimizedFunctions");
    DCHECK(isolate_->concurrent_recompilation_enabled());
    isolate_->optimizing_compile_dispatcher()->InstallOptimizedFunctions();
  }
#ifdef V8_ENABLE_SPARKPLUG
  if (TestAndClear(&interrupt_flags, INSTALL_BASELINE_CODE)) {
    TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
                 "V8.FinalizeBaselineConcurrentCompilation");
    isolate_->baseline_batch_compiler()->InstallBatch();
  }
#endif // V8_ENABLE_SPARKPLUG
#ifdef V8_ENABLE_MAGLEV
  if (TestAndClear(&interrupt_flags, INSTALL_MAGLEV_CODE)) {
    TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
                 "V8.FinalizeMaglevConcurrentCompilation");
    isolate_->maglev_concurrent_dispatcher()->FinalizeFinishedJobs();
  }
#endif // V8_ENABLE_MAGLEV
  if (TestAndClear(&interrupt_flags, API_INTERRUPT)) {
    TRACE_EVENT0("v8.execute", "V8.InvokeApiInterruptCallbacks");
    // Callbacks must be invoked outside of ExecutionAccess lock.
    isolate_->InvokeApiInterruptCallbacks();
  }
#ifdef V8_RUNTIME_CALL_STATS
  // Runtime call stats can be enabled at any via Chrome tracing and since
  // there's no global list of active Isolates this seems to be the only
  // simple way to invalidate the protector.
  if (TracingFlags::is_runtime_stats_enabled() &&
      Protectors::IsNoProfilingIntact(isolate_)) {
    Protectors::InvalidateNoProfiling(isolate_);
  }
#endif
  isolate_->counters()->stack_interrupts()->Increment();
  return ReadOnlyRoots(isolate_).undefined_value();
}
References v8::internal::Isolate::concurrent_recompilation_enabled(), v8::internal::Isolate::counters(), v8::internal::DCHECK(), v8::internal::Heap::DeoptMarkedAllocationSites(), FetchAndClearInterrupts(), v8::internal::wasm::GetWasmEngine(), v8::internal::Heap::HandleGCRequest(), v8::internal::Isolate::heap(), v8::internal::OptimizingCompileDispatcher::InstallOptimizedFunctions(), v8::internal::Isolate::InvokeApiInterruptCallbacks(), isolate_, v8::internal::wasm::WasmEngine::LogOutstandingCodesForIsolate(), v8::internal::Isolate::main_thread_local_heap(), v8::internal::Heap::MonotonicallyIncreasingTimeInMs(), v8::internal::Isolate::optimizing_compile_dispatcher(), v8::internal::wasm::WasmEngine::ReportLiveCodeFromStackForGC(), v8::internal::LocalHeap::Safepoint(), v8::internal::Heap::StartIncrementalMarkingOnInterrupt(), v8::internal::Isolate::TerminateExecution(), v8::internal::anonymous_namespace{stack-guard.cc}::TestAndClear(), TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT0, and v8::internal::v8_flags.
Referenced by v8::internal::anonymous_namespace{runtime-internal.cc}::BytecodeBudgetInterruptWithStackCheck(), wasm::CheckAndHandleInterrupts(), v8::internal::NativeRegExpMacroAssembler::CheckStackGuardState(), v8::internal::anonymous_namespace{regexp-interpreter.cc}::HandleInterrupts(), v8::internal::anonymous_namespace{tracing-cpu-profiler.cc}::RunInterruptsTask::Run(), v8::internal::RUNTIME_FUNCTION(), v8::internal::JsonStringifier::Serialize_(), v8::internal::JsonStringifier::SerializeFixedArrayWithInterruptCheck(), v8::internal::FutexEmulation::WaitSync(), and v8::internal::wasm::WasmInterpreterRuntime::WasmStackCheck().
has_pending_interrupts()
bool v8::internal::StackGuard::has_pending_interrupts (const ExecutionAccess & lock) [inline], [private]
Definition at line 178 of file stack-guard.h.
                                                           {
    return thread_local_.interrupt_flags_ != 0;
  }
Referenced by update_interrupt_requests_and_stack_limits().
HasTerminationRequest()
bool v8::internal::StackGuard::HasTerminationRequest ()
Definition at line 198 of file stack-guard.cc.
                                       {
  if (!thread_local_.has_interrupt_requested(InterruptLevel::kNoGC)) {
    return false;
  }
  ExecutionAccess access(isolate_);
  if ((thread_local_.interrupt_flags_ & TERMINATE_EXECUTION) != 0) {
    thread_local_.interrupt_flags_ &= ~TERMINATE_EXECUTION;
    update_interrupt_requests_and_stack_limits(access);
    return true;
  }
  return false;
}
References v8::internal::StackGuard::ThreadLocal::has_interrupt_requested(), v8::internal::StackGuard::ThreadLocal::interrupt_flags_, isolate_, kNoGC, thread_local_, and update_interrupt_requests_and_stack_limits().
Referenced by v8::internal::StackLimitCheck::HandleStackOverflowAndTerminationRequest(), and v8::internal::wasm::WasmInterpreterRuntime::WasmStackCheck().
InitThread()
void v8::internal::StackGuard::InitThread (const ExecutionAccess & lock)
Definition at line 262 of file stack-guard.cc.
                                                       {
  thread_local_.Initialize(isolate_, lock);
  Isolate::PerIsolateThreadData* per_thread =
      isolate_->FindOrAllocatePerThreadDataForThisThread();
  uintptr_t stored_limit = per_thread->stack_limit();
  // You should hold the ExecutionAccess lock when you call this.
  if (stored_limit != 0) {
    SetStackLimit(stored_limit);
  }
}
References v8::internal::Isolate::FindOrAllocatePerThreadDataForThisThread(), v8::internal::StackGuard::ThreadLocal::Initialize(), isolate_, SetStackLimit(), and thread_local_.
Referenced by v8::internal::Isolate::Init(), and v8::internal::ThreadManager::InitThread().
InterruptLevelMask()
static constexpr InterruptFlag v8::internal::StackGuard::InterruptLevelMask (InterruptLevel level) [inline], [static], [constexpr]
Definition at line 103 of file stack-guard.h.
                                                                          {
#define V(NAME, Name, id, interrupt_level) \
  | (interrupt_level <= level ? NAME : 0)
    return static_cast<InterruptFlag>(0 INTERRUPT_LIST(V));
#undef V
  }
References INTERRUPT_LIST.
Referenced by FetchAndClearInterrupts(), and update_interrupt_requests_and_stack_limits().
Iterate()
static char* v8::internal::StackGuard::Iterate (RootVisitor * v, char * thread_storage) [inline], [static]
Definition at line 164 of file stack-guard.h.
                                                             {
    return thread_storage + ArchiveSpacePerThread();
  }
References v8::internal::ArchiveSpacePerThread().
Referenced by v8::internal::ThreadManager::Iterate().
jslimit()
uintptr_t v8::internal::StackGuard::jslimit () [inline]
Definition at line 117 of file stack-guard.h.
{ return thread_local_.jslimit(); }
Referenced by SetStackLimitInternal().
jslimit_offset()
static constexpr int v8::internal::StackGuard::jslimit_offset () [inline], [static], [constexpr]
Definition at line 140 of file stack-guard.h.
                                        {
    return offsetof(StackGuard, thread_local_) +
           offsetof(ThreadLocal, jslimit_);
  }
Referenced by v8::internal::IsolateData::jslimit_offset().
operator=()
StackGuard& v8::internal::StackGuard::operator= (const StackGuard &) [delete]
PopInterruptsScope()
void v8::internal::StackGuard::PopInterruptsScope () [private]
Definition at line 137 of file stack-guard.cc.
                                    {
  ExecutionAccess access(isolate_);
  InterruptsScope* top = thread_local_.interrupt_scopes_;
  DCHECK_NE(top->mode_, InterruptsScope::kNoop);
  if (top->mode_ == InterruptsScope::kPostponeInterrupts) {
    // Make intercepted interrupts active.
    DCHECK_EQ(thread_local_.interrupt_flags_ & top->intercept_mask_, 0);
    thread_local_.interrupt_flags_ |= top->intercepted_flags_;
  } else {
    DCHECK_EQ(top->mode_, InterruptsScope::kRunInterrupts);
    // Postpone existing interupts if needed.
    if (top->prev_) {
      for (uint32_t interrupt = 1; interrupt < ALL_INTERRUPTS;
           interrupt = interrupt << 1) {
        InterruptFlag flag = static_cast<InterruptFlag>(interrupt);
        if ((thread_local_.interrupt_flags_ & flag) &&
            top->prev_->Intercept(flag)) {
          thread_local_.interrupt_flags_ &= ~flag;
        }
      }
    }
  }
  update_interrupt_requests_and_stack_limits(access);
  // Remove scope from chain.
  thread_local_.interrupt_scopes_ = top->prev_;
}
References ALL_INTERRUPTS, DCHECK_EQ, DCHECK_NE, v8::internal::InterruptsScope::Intercept(), v8::internal::InterruptsScope::intercept_mask_, v8::internal::InterruptsScope::intercepted_flags_, v8::internal::StackGuard::ThreadLocal::interrupt_flags_, v8::internal::StackGuard::ThreadLocal::interrupt_scopes_, isolate_, v8::internal::InterruptsScope::kNoop, v8::internal::InterruptsScope::kPostponeInterrupts, v8::internal::InterruptsScope::kRunInterrupts, v8::internal::InterruptsScope::mode_, v8::internal::InterruptsScope::prev_, thread_local_, and update_interrupt_requests_and_stack_limits().
PushInterruptsScope()
void v8::internal::StackGuard::PushInterruptsScope (InterruptsScope * scope) [private]
Definition at line 111 of file stack-guard.cc.
                                                           {
  ExecutionAccess access(isolate_);
  DCHECK_NE(scope->mode_, InterruptsScope::kNoop);
  if (scope->mode_ == InterruptsScope::kPostponeInterrupts) {
    // Intercept already requested interrupts.
    uint32_t intercepted =
        thread_local_.interrupt_flags_ & scope->intercept_mask_;
    scope->intercepted_flags_ = intercepted;
    thread_local_.interrupt_flags_ &= ~intercepted;
  } else {
    DCHECK_EQ(scope->mode_, InterruptsScope::kRunInterrupts);
    // Restore postponed interrupts.
    uint32_t restored_flags = 0;
    for (InterruptsScope* current = thread_local_.interrupt_scopes_;
         current != nullptr; current = current->prev_) {
      restored_flags |= (current->intercepted_flags_ & scope->intercept_mask_);
      current->intercepted_flags_ &= ~scope->intercept_mask_;
    }
    thread_local_.interrupt_flags_ |= restored_flags;
  }
  update_interrupt_requests_and_stack_limits(access);
  // Add scope to the chain.
  scope->prev_ = thread_local_.interrupt_scopes_;
  thread_local_.interrupt_scopes_ = scope;
}
References DCHECK_EQ, DCHECK_NE, v8::internal::InterruptsScope::intercept_mask_, v8::internal::InterruptsScope::intercepted_flags_, v8::internal::StackGuard::ThreadLocal::interrupt_flags_, v8::internal::StackGuard::ThreadLocal::interrupt_scopes_, isolate_, v8::internal::InterruptsScope::kNoop, v8::internal::InterruptsScope::kPostponeInterrupts, v8::internal::InterruptsScope::kRunInterrupts, v8::internal::InterruptsScope::mode_, v8::internal::InterruptsScope::prev_, thread_local_, and update_interrupt_requests_and_stack_limits().
Referenced by v8::internal::InterruptsScope::InterruptsScope().
real_climit()
uintptr_t v8::internal::StackGuard::real_climit () [inline]
Definition at line 121 of file stack-guard.h.
                          {
#ifdef USE_SIMULATOR
    return thread_local_.real_climit_;
#else
    return thread_local_.real_jslimit_;
#endif
  }
Referenced by v8::internal::Compiler::CollectSourcePositions(), FreeThreadResources(), v8::internal::StackLimitCheck::HasOverflowed(), v8::internal::StackLimitCheck::JsHasOverflowed(), v8::internal::RegExpParser::ParseRegExpFromHeapString(), and v8::internal::StackLimitCheck::WasmHasOverflowed().
real_jslimit()
uintptr_t v8::internal::StackGuard::real_jslimit () [inline]
Definition at line 128 of file stack-guard.h.
{ return thread_local_.real_jslimit_; }
Referenced by v8::internal::Deoptimizer::DoComputeOutputFrames(), and v8::internal::wasm::switch_to_the_central_stack().
real_jslimit_offset()
static constexpr int v8::internal::StackGuard::real_jslimit_offset () [inline], [static], [constexpr]
Definition at line 145 of file stack-guard.h.
                                             {
    return offsetof(StackGuard, thread_local_) +
           offsetof(ThreadLocal, real_jslimit_);
  }
Referenced by v8::internal::IsolateData::real_jslimit_offset().
RequestInterrupt()
void v8::internal::StackGuard::RequestInterrupt (InterruptFlag flag) [private]
Definition at line 169 of file stack-guard.cc.
                                                    {
  ExecutionAccess access(isolate_);
  // Check the chain of InterruptsScope for interception.
  if (thread_local_.interrupt_scopes_ &&
      thread_local_.interrupt_scopes_->Intercept(flag)) {
    return;
  }
  // Not intercepted. Set as active interrupt flag.
  thread_local_.interrupt_flags_ |= flag;
  update_interrupt_requests_and_stack_limits(access);
  // If this isolate is waiting in a futex, notify it to wake up.
  isolate_->futex_wait_list_node()->NotifyWake();
}
References v8::internal::Isolate::futex_wait_list_node(), v8::internal::InterruptsScope::Intercept(), v8::internal::StackGuard::ThreadLocal::interrupt_flags_, v8::internal::StackGuard::ThreadLocal::interrupt_scopes_, isolate_, v8::internal::FutexWaitListNode::NotifyWake(), thread_local_, and update_interrupt_requests_and_stack_limits().
RestoreStackGuard()
char * v8::internal::StackGuard::RestoreStackGuard (char * from)
Definition at line 235 of file stack-guard.cc.
                                              {
  ExecutionAccess access(isolate_);
  MemCopy(reinterpret_cast<char*>(&thread_local_), from, sizeof(ThreadLocal));
  return from + sizeof(ThreadLocal);
}
References isolate_, v8::internal::MemCopy(), and thread_local_.
Referenced by v8::internal::ThreadManager::RestoreThread().
SetStackLimit()
void v8::internal::StackGuard::SetStackLimit (uintptr_t limit)
Definition at line 56 of file stack-guard.cc.
                                              {
  ExecutionAccess access(isolate_);
  SetStackLimitInternal(access, limit,
                        SimulatorStack::JsLimitFromCLimit(isolate_, limit));
}
References isolate_, v8::internal::SimulatorStack::JsLimitFromCLimit(), and SetStackLimitInternal().
Referenced by v8::Isolate::Initialize(), InitThread(), and v8::Isolate::SetStackLimit().
SetStackLimitForStackSwitching()
void v8::internal::StackGuard::SetStackLimitForStackSwitching (uintptr_t limit)
Definition at line 78 of file stack-guard.cc.
                                                               {
  // Try to compare and swap the new jslimit without the ExecutionAccess lock.
  uintptr_t old_jslimit = base::Relaxed_CompareAndSwap(
      &thread_local_.jslimit_, thread_local_.real_jslimit_, limit);
  USE(old_jslimit);
  DCHECK_IMPLIES(old_jslimit != thread_local_.real_jslimit_,
                 old_jslimit == kInterruptLimit);
  // Either way, set the real limit. This does not require synchronization.
  thread_local_.real_jslimit_ = limit;
}
References DCHECK_IMPLIES, v8::internal::StackGuard::ThreadLocal::jslimit_, kInterruptLimit, v8::internal::StackGuard::ThreadLocal::real_jslimit_, v8::base::Relaxed_CompareAndSwap(), thread_local_, and USE.
Referenced by v8::internal::wasm::grow_stack(), v8::internal::wasm::shrink_stack(), v8::internal::wasm::switch_from_the_central_stack(), v8::internal::wasm::switch_from_the_central_stack_for_js(), v8::internal::wasm::switch_to_the_central_stack(), v8::internal::wasm::switch_to_the_central_stack_for_js(), and v8::internal::Isolate::UnwindAndFindHandler().
SetStackLimitInternal()
void v8::internal::StackGuard::SetStackLimitInternal (const ExecutionAccess & lock, uintptr_t limit, uintptr_t jslimit) [private]
Definition at line 62 of file stack-guard.cc.
                                                                           {
  // If the current limits are special (e.g. due to a pending interrupt) then
  // leave them alone.
  if (thread_local_.jslimit() == thread_local_.real_jslimit_) {
    thread_local_.set_jslimit(jslimit);
  }
  thread_local_.real_jslimit_ = jslimit;
#ifdef USE_SIMULATOR
  if (thread_local_.climit() == thread_local_.real_climit_) {
    thread_local_.set_climit(limit);
  }
  thread_local_.real_climit_ = limit;
#endif
}
References jslimit(), v8::internal::StackGuard::ThreadLocal::jslimit(), v8::internal::StackGuard::ThreadLocal::real_jslimit_, v8::internal::StackGuard::ThreadLocal::set_jslimit(), and thread_local_.
Referenced by SetStackLimit().
update_interrupt_requests_and_stack_limits()
void v8::internal::StackGuard::update_interrupt_requests_and_stack_limits (const ExecutionAccess & lock) [inline], [private]
Definition at line 34 of file stack-guard.cc.
                                 {
  DCHECK_NOT_NULL(isolate_);
  if (has_pending_interrupts(lock)) {
    thread_local_.set_jslimit(kInterruptLimit);
#ifdef USE_SIMULATOR
    thread_local_.set_climit(kInterruptLimit);
#endif
  } else {
    thread_local_.set_jslimit(thread_local_.real_jslimit_);
#ifdef USE_SIMULATOR
    thread_local_.set_climit(thread_local_.real_climit_);
#endif
  }
  for (InterruptLevel level :
       std::array{InterruptLevel::kNoGC, InterruptLevel::kNoHeapWrites,
                  InterruptLevel::kAnyEffect}) {
    thread_local_.set_interrupt_requested(
        level, InterruptLevelMask(level) & thread_local_.interrupt_flags_);
  }
}
References DCHECK_NOT_NULL, has_pending_interrupts(), v8::internal::StackGuard::ThreadLocal::interrupt_flags_, InterruptLevelMask(), isolate_, kAnyEffect, kInterruptLimit, kNoGC, kNoHeapWrites, v8::internal::StackGuard::ThreadLocal::real_jslimit_, v8::internal::StackGuard::ThreadLocal::set_interrupt_requested(), v8::internal::StackGuard::ThreadLocal::set_jslimit(), and thread_local_.
Referenced by ClearInterrupt(), FetchAndClearInterrupts(), HasTerminationRequest(), PopInterruptsScope(), PushInterruptsScope(), and RequestInterrupt().
Friends And Related Function Documentation
InterruptsScope
friend class InterruptsScope [friend]
Definition at line 283 of file stack-guard.h.
Isolate
friend class Isolate [friend]
Definition at line 281 of file stack-guard.h.
StackLimitCheck
friend class StackLimitCheck [friend]
Definition at line 282 of file stack-guard.h.
Member Data Documentation
isolate_
Isolate* v8::internal::StackGuard::isolate_ [private]
Definition at line 278 of file stack-guard.h.
Referenced by ArchiveStackGuard(), CheckInterrupt(), ClearInterrupt(), FetchAndClearInterrupts(), FreeThreadResources(), HandleInterrupts(), HasTerminationRequest(), InitThread(), PopInterruptsScope(), PushInterruptsScope(), RequestInterrupt(), RestoreStackGuard(), SetStackLimit(), and update_interrupt_requests_and_stack_limits().
kIllegalLimit
const uintptr_t v8::internal::StackGuard::kIllegalLimit = 0xfffffff8 [static], [private]
Definition at line 191 of file stack-guard.h.
kInterruptLimit
const uintptr_t v8::internal::StackGuard::kInterruptLimit = 0xfffffffe [static], [private]
Definition at line 190 of file stack-guard.h.
Referenced by SetStackLimitForStackSwitching(), and update_interrupt_requests_and_stack_limits().
kNumberOfInterruptLevels
constexpr int v8::internal::StackGuard::kNumberOfInterruptLevels = 3 [static], [constexpr]
Definition at line 66 of file stack-guard.h.
kSizeInBytes
constexpr int v8::internal::StackGuard::kSizeInBytes = 8 * kSystemPointerSize [static], [constexpr]
Definition at line 162 of file stack-guard.h.
thread_local_
ThreadLocal v8::internal::StackGuard::thread_local_ [private]
Definition at line 279 of file stack-guard.h.
Referenced by ArchiveStackGuard(), CheckInterrupt(), ClearInterrupt(), FetchAndClearInterrupts(), HasTerminationRequest(), InitThread(), PopInterruptsScope(), PushInterruptsScope(), RequestInterrupt(), RestoreStackGuard(), SetStackLimitForStackSwitching(), SetStackLimitInternal(), and update_interrupt_requests_and_stack_limits().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/stack-guard.h
/mnt/V8SourceCode/src/execution/stack-guard.cc