v8::internal::compiler::PropertyAccessBuilder Class Reference
#include <property-access-builder.h>
Public Member Functions
PropertyAccessBuilder (JSGraph *jsgraph, JSHeapBroker *broker)
bool TryBuildStringCheck (JSHeapBroker *broker, ZoneVector< MapRef > const &maps, Node **receiver, Effect *effect, Control control)
bool TryBuildNumberCheck (JSHeapBroker *broker, ZoneVector< MapRef > const &maps, Node **receiver, Effect *effect, Control control)
void BuildCheckMaps (Node *object, Effect *effect, Control control, ZoneVector< MapRef > const &maps, bool has_deprecated_map_without_migration_target=false)
Node * BuildCheckValue (Node *receiver, Effect *effect, Control control, ObjectRef value)
Node * BuildCheckSmi (Node *value, Effect *effect, Control control, FeedbackSource feedback_source=FeedbackSource())
Node * BuildCheckNumber (Node *value, Effect *effect, Control control, FeedbackSource feedback_source=FeedbackSource())
Node * BuildCheckNumberFitsInt32 (Node *value, Effect *effect, Control control, FeedbackSource feedback_source=FeedbackSource())
Node * BuildLoadDataField (NameRef name, PropertyAccessInfo const &access_info, Node *lookup_start_object, Node **effect, Node **control)
std::optional< Node * > FoldLoadDictPrototypeConstant (PropertyAccessInfo const &access_info)
Static Public Member Functions
static MachineRepresentation ConvertRepresentation (Representation representation)
Private Member Functions
JSGraph * jsgraph () const
JSHeapBroker * broker () const
CompilationDependencies * dependencies () const
TFGraph * graph () const
Isolate * isolate () const
CommonOperatorBuilder * common () const
SimplifiedOperatorBuilder * simplified () const
Node * TryFoldLoadConstantDataField (NameRef name, PropertyAccessInfo const &access_info, Node *lookup_start_object)
Node * ResolveHolder (PropertyAccessInfo const &access_info, Node *lookup_start_object)
Node * BuildLoadDataField (NameRef name, Node *holder, FieldAccess &&field_access, bool is_inobject, Node **effect, Node **control)
Private Attributes
JSGraph * jsgraph_
JSHeapBroker * broker_
Detailed Description
Definition at line 30 of file property-access-builder.h.
Constructor & Destructor Documentation
PropertyAccessBuilder()
v8::internal::compiler::PropertyAccessBuilder::PropertyAccessBuilder (JSGraph * jsgraph, JSHeapBroker * broker) [inline]
Definition at line 32 of file property-access-builder.h.
      : jsgraph_(jsgraph), broker_(broker) {}
Member Function Documentation
broker()
JSHeapBroker* v8::internal::compiler::PropertyAccessBuilder::broker () const [inline], [private]
Definition at line 77 of file property-access-builder.h.
{ return broker_; }
References broker_.
Referenced by BuildCheckMaps(), BuildCheckValue(), BuildLoadDataField(), FoldLoadDictPrototypeConstant(), ResolveHolder(), TryBuildNumberCheck(), TryBuildStringCheck(), and TryFoldLoadConstantDataField().
BuildCheckMaps()
void v8::internal::compiler::PropertyAccessBuilder::BuildCheckMaps (Node * object, Effect * effect, Control control, ZoneVector< MapRef > const & maps, bool has_deprecated_map_without_migration_target = false)
Definition at line 108 of file property-access-builder.cc.
                                                      {
  HeapObjectMatcher m(object);
  if (m.HasResolvedValue()) {
    MapRef object_map = m.Ref(broker()).map(broker());
    if (object_map.is_stable()) {
      for (MapRef map : maps) {
        if (map.equals(object_map)) {
          dependencies()->DependOnStableMap(object_map);
          return;
        }
      }
    }
  }
  ZoneRefSet<Map> map_set;
  bool has_migration_target = false;
  for (MapRef map : maps) {
    map_set.insert(map, graph()->zone());
    if (map.is_migration_target()) {
      has_migration_target = true;
    }
  }
  CheckMapsFlags flags = CheckMapsFlag::kNone;
  if (has_migration_target) {
    flags = CheckMapsFlag::kTryMigrateInstance;
  } else if (has_deprecated_map_without_migration_target) {
    flags = CheckMapsFlag::kTryMigrateInstanceAndDeopt;
  }
  *effect = graph()->NewNode(simplified()->CheckMaps(flags, map_set), object,
                             *effect, control);
}
References broker(), dependencies(), v8::internal::compiler::CompilationDependencies::DependOnStableMap(), v8::internal::flags, graph(), v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::ZoneCompactSet< T >::insert(), v8::internal::compiler::MapRef::is_stable(), v8::internal::compiler::kNone, v8::internal::compiler::kTryMigrateInstance, v8::internal::compiler::kTryMigrateInstanceAndDeopt, v8::internal::compiler::HeapObjectRef::map(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Ref(), and simplified().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccess(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf(), and v8::internal::compiler::JSNativeContextSpecialization::ReduceNamedAccess().
BuildCheckNumber()
Node * v8::internal::compiler::PropertyAccessBuilder::BuildCheckNumber (Node * value, Effect * effect, Control control, FeedbackSource feedback_source = FeedbackSource())
Definition at line 165 of file property-access-builder.cc.
                                                                              {
  Node* number = *effect = graph()->NewNode(
      simplified()->CheckNumber(feedback_source), value, *effect, control);
  return number;
}
References graph(), v8::internal::compiler::TFGraph::NewNode(), simplified(), and v8::internal::value.
Referenced by v8::internal::compiler::JSContextSpecialization::ReduceJSStoreContext().
BuildCheckNumberFitsInt32()
Node * v8::internal::compiler::PropertyAccessBuilder::BuildCheckNumberFitsInt32 (Node * value, Effect * effect, Control control, FeedbackSource feedback_source = FeedbackSource())
Definition at line 173 of file property-access-builder.cc.
                                    {
  Node* number = *effect =
      graph()->NewNode(simplified()->CheckNumberFitsInt32(feedback_source),
                       value, *effect, control);
  return number;
}
References graph(), v8::internal::compiler::TFGraph::NewNode(), simplified(), and v8::internal::value.
Referenced by v8::internal::compiler::JSContextSpecialization::ReduceJSStoreContext().
BuildCheckSmi()
Node * v8::internal::compiler::PropertyAccessBuilder::BuildCheckSmi (Node * value, Effect * effect, Control control, FeedbackSource feedback_source = FeedbackSource())
Definition at line 157 of file property-access-builder.cc.
                                                                           {
  Node* smi_value = *effect = graph()->NewNode(
      simplified()->CheckSmi(feedback_source), value, *effect, control);
  return smi_value;
}
References graph(), v8::internal::compiler::TFGraph::NewNode(), simplified(), and v8::internal::value.
Referenced by v8::internal::compiler::JSContextSpecialization::ReduceJSStoreContext().
BuildCheckValue()
Node * v8::internal::compiler::PropertyAccessBuilder::BuildCheckValue (Node * receiver, Effect * effect, Control control, ObjectRef value)
Definition at line 142 of file property-access-builder.cc.
                                                                               {
  if (value.IsHeapObject()) {
    HeapObjectMatcher m(receiver);
    if (m.Is(value.AsHeapObject().object())) return receiver;
  }
  Node* expected = jsgraph()->ConstantNoHole(value, broker());
  Node* check =
      graph()->NewNode(simplified()->ReferenceEqual(), receiver, expected);
  *effect =
      graph()->NewNode(simplified()->CheckIf(DeoptimizeReason::kWrongValue),
                       check, *effect, control);
  return expected;
}
References broker(), v8::internal::compiler::JSGraph::ConstantNoHole(), graph(), v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Is(), jsgraph(), v8::internal::compiler::TFGraph::NewNode(), simplified(), and v8::internal::value.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf(), and v8::internal::compiler::JSContextSpecialization::ReduceJSStoreContext().
BuildLoadDataField() [1/2]
Node * v8::internal::compiler::PropertyAccessBuilder::BuildLoadDataField (NameRef name, Node * holder, FieldAccess && field_access, bool is_inobject, Node ** effect, Node ** control) [private]
Definition at line 288 of file property-access-builder.cc.
                                                                {
  Node* storage = holder;
  if (!is_inobject) {
    storage = *effect = graph()->NewNode(
        simplified()->LoadField(
            AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer()),
        storage, *effect, *control);
  }
  if (field_access.machine_type.representation() ==
      MachineRepresentation::kFloat64) {
    if (dependencies() == nullptr) {
      FieldAccess const storage_access = {kTaggedBase,
                                          field_access.offset,
                                          name.object(),
                                          OptionalMapRef(),
                                          Type::Any(),
                                          MachineType::AnyTagged(),
                                          kPointerWriteBarrier,
                                          "BuildLoadDataField",
                                          field_access.const_field_info};
      storage = *effect = graph()->NewNode(
          simplified()->LoadField(storage_access), storage, *effect, *control);
      // We expect the loaded value to be a heap number here. With
      // in-place field representation changes it is possible this is a
      // no longer a heap number without map transitions. If we haven't taken
      // a dependency on field representation, we should verify the loaded
      // value is a heap number.
      storage = *effect = graph()->NewNode(simplified()->CheckHeapObject(),
                                           storage, *effect, *control);
      Node* map = *effect =
          graph()->NewNode(simplified()->LoadField(AccessBuilder::ForMap()),
                           storage, *effect, *control);
      Node* is_heap_number =
          graph()->NewNode(simplified()->ReferenceEqual(), map,
                           jsgraph()->HeapNumberMapConstant());
      *effect = graph()->NewNode(
          simplified()->CheckIf(DeoptimizeReason::kNotAHeapNumber),
          is_heap_number, *effect, *control);
    } else {
      FieldAccess const storage_access = {kTaggedBase,
                                          field_access.offset,
                                          name.object(),
                                          OptionalMapRef(),
                                          Type::OtherInternal(),
                                          MachineType::TaggedPointer(),
                                          kPointerWriteBarrier,
                                          "BuildLoadDataField",
                                          field_access.const_field_info};
      storage = *effect = graph()->NewNode(
          simplified()->LoadField(storage_access), storage, *effect, *control);
    }
    FieldAccess value_field_access = AccessBuilder::ForHeapNumberValue();
    value_field_access.const_field_info = field_access.const_field_info;
    field_access = value_field_access;
  }
  Node* value = *effect = graph()->NewNode(
      simplified()->LoadField(field_access), storage, *effect, *control);
  return value;
}
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::MachineType::AnyTagged(), v8::internal::compiler::FieldAccess::const_field_info, dependencies(), v8::internal::compiler::AccessBuilder::ForHeapNumberValue(), v8::internal::compiler::AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(), v8::internal::compiler::AccessBuilder::ForMap(), graph(), jsgraph(), v8::internal::kFloat64, v8::internal::compiler::kPointerWriteBarrier, v8::internal::compiler::kTaggedBase, v8::internal::name, v8::internal::compiler::TFGraph::NewNode(), simplified(), v8::internal::MachineType::TaggedPointer(), and v8::internal::value.
BuildLoadDataField() [2/2]
Node * v8::internal::compiler::PropertyAccessBuilder::BuildLoadDataField (NameRef name, PropertyAccessInfo const & access_info, Node * lookup_start_object, Node ** effect, Node ** control)
Definition at line 351 of file property-access-builder.cc.
                                                              {
  DCHECK(access_info.IsDataField() || access_info.IsFastDataConstant());
  if (Node* value = TryFoldLoadConstantDataField(name, access_info,
                                                 lookup_start_object)) {
    return value;
  }
  MachineRepresentation const field_representation =
      ConvertRepresentation(access_info.field_representation());
  Node* storage = ResolveHolder(access_info, lookup_start_object);
  FieldAccess field_access = {
      kTaggedBase,
      access_info.field_index().offset(),
      name.object(),
      OptionalMapRef(),
      access_info.field_type(),
      MachineType::TypeForRepresentation(field_representation),
      kFullWriteBarrier,
      "BuildLoadDataField",
      access_info.GetConstFieldInfo()};
  if (field_representation == MachineRepresentation::kTaggedPointer ||
      field_representation == MachineRepresentation::kCompressedPointer) {
    // Remember the map of the field value, if its map is stable. This is
    // used by the LoadElimination to eliminate map checks on the result.
    OptionalMapRef field_map = access_info.field_map();
    if (field_map.has_value()) {
      if (field_map->is_stable()) {
        dependencies()->DependOnStableMap(field_map.value());
        field_access.map = field_map;
        field_access.type = Type::For(*field_map, broker());
      }
    }
  }
  return BuildLoadDataField(name, storage, std::move(field_access),
                            access_info.field_index().is_inobject(), effect,
                            control);
}
References broker(), ConvertRepresentation(), v8::internal::DCHECK(), dependencies(), v8::internal::compiler::CompilationDependencies::DependOnStableMap(), v8::internal::compiler::PropertyAccessInfo::field_index(), v8::internal::compiler::PropertyAccessInfo::field_map(), v8::internal::compiler::PropertyAccessInfo::field_representation(), v8::internal::compiler::PropertyAccessInfo::field_type(), v8::internal::compiler::Type::For(), v8::internal::compiler::PropertyAccessInfo::GetConstFieldInfo(), v8::internal::FieldIndex::is_inobject(), v8::internal::compiler::PropertyAccessInfo::IsDataField(), v8::internal::compiler::PropertyAccessInfo::IsFastDataConstant(), v8::internal::kCompressedPointer, v8::internal::compiler::kFullWriteBarrier, v8::internal::compiler::kTaggedBase, v8::internal::kTaggedPointer, v8::internal::compiler::FieldAccess::map, v8::internal::name, v8::internal::FieldIndex::offset(), ResolveHolder(), TryFoldLoadConstantDataField(), v8::internal::compiler::FieldAccess::type, v8::internal::MachineType::TypeForRepresentation(), and v8::internal::value.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyLoad().
common()
CommonOperatorBuilder * v8::internal::compiler::PropertyAccessBuilder::common () const [private]
Definition at line 29 of file property-access-builder.cc.
                                                           {
  return jsgraph()->common();
}
References v8::internal::compiler::MachineGraph::common(), and jsgraph().
ConvertRepresentation()
MachineRepresentation v8::internal::compiler::PropertyAccessBuilder::ConvertRepresentation (Representation representation) [static]
Definition at line 191 of file property-access-builder.cc.
                                   {
  switch (representation.kind()) {
    case Representation::kSmi:
      return MachineRepresentation::kTaggedSigned;
    case Representation::kDouble:
      return MachineRepresentation::kFloat64;
    case Representation::kHeapObject:
      return MachineRepresentation::kTaggedPointer;
    case Representation::kTagged:
      return MachineRepresentation::kTagged;
    default:
      UNREACHABLE();
  }
}
References v8::internal::Representation::kDouble, v8::internal::kFloat64, v8::internal::Representation::kHeapObject, v8::internal::Representation::kind(), v8::internal::Representation::kSmi, v8::internal::kTagged, v8::internal::Representation::kTagged, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, and v8::internal::UNREACHABLE().
Referenced by BuildLoadDataField(), and v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyStore().
dependencies()
CompilationDependencies* v8::internal::compiler::PropertyAccessBuilder::dependencies () const [inline], [private]
Definition at line 78 of file property-access-builder.h.
                                                {
    return broker_->dependencies();
  }
References broker_, and v8::internal::compiler::JSHeapBroker::dependencies().
Referenced by BuildCheckMaps(), BuildLoadDataField(), FoldLoadDictPrototypeConstant(), and TryFoldLoadConstantDataField().
FoldLoadDictPrototypeConstant()
std::optional< Node * > v8::internal::compiler::PropertyAccessBuilder::FoldLoadDictPrototypeConstant (PropertyAccessInfo const & access_info)
Definition at line 207 of file property-access-builder.cc.
                                           {
  DCHECK(V8_DICT_PROPERTY_CONST_TRACKING_BOOL);
  DCHECK(access_info.IsDictionaryProtoDataConstant());
  InternalIndex index = access_info.dictionary_index();
  OptionalObjectRef value = access_info.holder()->GetOwnDictionaryProperty(
      broker(), index, dependencies());
  if (!value) return {};
  for (MapRef map : access_info.lookup_start_object_maps()) {
    DirectHandle<Map> map_handle = map.object();
    // Non-JSReceivers that passed AccessInfoFactory::ComputePropertyAccessInfo
    // must have different lookup start map.
    if (!IsJSReceiverMap(*map_handle)) {
      // Perform the implicit ToObject for primitives here.
      // Implemented according to ES6 section 7.3.2 GetV (V, P).
      Tagged<JSFunction> constructor =
          Map::GetConstructorFunction(
              *map_handle, *broker()->target_native_context().object())
              .value();
      // {constructor.initial_map()} is loaded/stored with acquire-release
      // semantics for constructors.
      map = MakeRefAssumeMemoryFence(broker(), constructor->initial_map());
      DCHECK(IsJSObjectMap(*map.object()));
    }
    dependencies()->DependOnConstantInDictionaryPrototypeChain(
        map, access_info.name(), value.value(), PropertyKind::kData);
  }
  return jsgraph()->ConstantNoHole(value.value(), broker());
}
References broker(), v8::internal::compiler::JSGraph::ConstantNoHole(), v8::internal::DCHECK(), dependencies(), v8::internal::compiler::CompilationDependencies::DependOnConstantInDictionaryPrototypeChain(), v8::internal::compiler::PropertyAccessInfo::dictionary_index(), v8::internal::Map::GetConstructorFunction(), v8::internal::compiler::PropertyAccessInfo::holder(), v8::internal::index, v8::internal::compiler::PropertyAccessInfo::IsDictionaryProtoDataConstant(), jsgraph(), v8::internal::kData, v8::internal::compiler::PropertyAccessInfo::lookup_start_object_maps(), v8::internal::compiler::MakeRefAssumeMemoryFence(), v8::internal::compiler::PropertyAccessInfo::name(), V8_DICT_PROPERTY_CONST_TRACKING_BOOL, and v8::internal::value.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyLoad().
graph()
TFGraph * v8::internal::compiler::PropertyAccessBuilder::graph () const [private]
Definition at line 25 of file property-access-builder.cc.
{ return jsgraph()->graph(); }
References v8::internal::compiler::MachineGraph::graph(), and jsgraph().
Referenced by BuildCheckMaps(), BuildCheckNumber(), BuildCheckNumberFitsInt32(), BuildCheckSmi(), BuildCheckValue(), BuildLoadDataField(), TryBuildNumberCheck(), and TryBuildStringCheck().
isolate()
Isolate * v8::internal::compiler::PropertyAccessBuilder::isolate () const [private]
Definition at line 27 of file property-access-builder.cc.
{ return jsgraph()->isolate(); }
References v8::internal::compiler::JSGraph::isolate(), and jsgraph().
jsgraph()
JSGraph* v8::internal::compiler::PropertyAccessBuilder::jsgraph () const [inline], [private]
Definition at line 76 of file property-access-builder.h.
{ return jsgraph_; }
References jsgraph_.
Referenced by BuildCheckValue(), BuildLoadDataField(), common(), FoldLoadDictPrototypeConstant(), graph(), isolate(), ResolveHolder(), simplified(), and TryFoldLoadConstantDataField().
ResolveHolder()
Node * v8::internal::compiler::PropertyAccessBuilder::ResolveHolder (PropertyAccessInfo const & access_info, Node * lookup_start_object) [private]
Definition at line 182 of file property-access-builder.cc.
                                                                      {
  OptionalJSObjectRef holder = access_info.holder();
  if (holder.has_value()) {
    return jsgraph()->ConstantNoHole(holder.value(), broker());
  }
  return lookup_start_object;
}
References broker(), v8::internal::compiler::JSGraph::ConstantNoHole(), v8::internal::compiler::PropertyAccessInfo::holder(), and jsgraph().
Referenced by BuildLoadDataField().
simplified()
SimplifiedOperatorBuilder * v8::internal::compiler::PropertyAccessBuilder::simplified () const [private]
Definition at line 33 of file property-access-builder.cc.
                                                                   {
  return jsgraph()->simplified();
}
References jsgraph(), and v8::internal::compiler::JSGraph::simplified().
Referenced by BuildCheckMaps(), BuildCheckNumber(), BuildCheckNumberFitsInt32(), BuildCheckSmi(), BuildCheckValue(), BuildLoadDataField(), TryBuildNumberCheck(), and TryBuildStringCheck().
TryBuildNumberCheck()
bool v8::internal::compiler::PropertyAccessBuilder::TryBuildNumberCheck (JSHeapBroker * broker, ZoneVector< MapRef > const & maps, Node ** receiver, Effect * effect, Control control)
Definition at line 94 of file property-access-builder.cc.
                                                                 {
  if (HasOnlyNumberMaps(broker, maps)) {
    // Monomorphic number access (we also deal with Smis here).
    *receiver = *effect =
        graph()->NewNode(simplified()->CheckNumber(FeedbackSource()), *receiver,
                         *effect, control);
    return true;
  }
  return false;
}
References broker(), graph(), v8::internal::compiler::anonymous_namespace{property-access-builder.cc}::HasOnlyNumberMaps(), v8::internal::compiler::TFGraph::NewNode(), and simplified().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceNamedAccess().
TryBuildStringCheck()
bool v8::internal::compiler::PropertyAccessBuilder::TryBuildStringCheck (JSHeapBroker * broker, ZoneVector< MapRef > const & maps, Node ** receiver, Effect * effect, Control control)
Definition at line 79 of file property-access-builder.cc.
                                                                 {
  if (HasOnlyStringMaps(broker, maps)) {
    // Monormorphic string access (ignoring the fact that there are multiple
    // String maps).
    *receiver = *effect =
        graph()->NewNode(simplified()->CheckString(FeedbackSource()), *receiver,
                         *effect, control);
    return true;
  }
  return false;
}
References broker(), graph(), v8::internal::compiler::HasOnlyStringMaps(), v8::internal::compiler::TFGraph::NewNode(), and simplified().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceNamedAccess().
TryFoldLoadConstantDataField()
Node * v8::internal::compiler::PropertyAccessBuilder::TryFoldLoadConstantDataField (NameRef name, PropertyAccessInfo const & access_info, Node * lookup_start_object) [private]
Definition at line 240 of file property-access-builder.cc.
                               {
  if (!access_info.IsFastDataConstant()) return nullptr;
  // First, determine if we have a constant holder to load from.
  OptionalJSObjectRef holder = access_info.holder();
  // If {access_info} has a holder, just use it.
  if (!holder.has_value()) {
    // Otherwise, try to match the {lookup_start_object} as a constant.
    if (lookup_start_object->opcode() == IrOpcode::kCheckString ||
        lookup_start_object->opcode() ==
            IrOpcode::kCheckStringOrStringWrapper) {
      // Bypassing Check inputs in order to allow constant folding.
      lookup_start_object = lookup_start_object->InputAt(0);
    }
    HeapObjectMatcher m(lookup_start_object);
    if (!m.HasResolvedValue() || !m.Ref(broker()).IsJSObject()) return nullptr;
    // Let us make sure the actual map of the constant lookup_start_object is
    // among the maps in {access_info}.
    MapRef lookup_start_object_map = m.Ref(broker()).map(broker());
    if (std::find_if(access_info.lookup_start_object_maps().begin(),
                     access_info.lookup_start_object_maps().end(),
                     [&](MapRef map) {
                       return map.equals(lookup_start_object_map);
                     }) == access_info.lookup_start_object_maps().end()) {
      // The map of the lookup_start_object is not in the feedback, let us bail
      // out.
      return nullptr;
    }
    holder = m.Ref(broker()).AsJSObject();
  }
  if (access_info.field_representation().IsDouble()) {
    std::optional<Float64> value = holder->GetOwnFastConstantDoubleProperty(
        broker(), access_info.field_index(), dependencies());
    return value.has_value() ? jsgraph()->ConstantNoHole(value->get_scalar())
                             : nullptr;
  }
  OptionalObjectRef value = holder->GetOwnFastConstantDataProperty(
      broker(), access_info.field_representation(), access_info.field_index(),
      dependencies());
  return value.has_value() ? jsgraph()->ConstantNoHole(*value, broker())
                           : nullptr;
}
References broker(), v8::internal::compiler::JSGraph::ConstantNoHole(), dependencies(), v8::internal::compiler::PropertyAccessInfo::field_index(), v8::internal::compiler::PropertyAccessInfo::field_representation(), v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::compiler::PropertyAccessInfo::holder(), v8::internal::compiler::Node::InputAt(), v8::internal::Representation::IsDouble(), v8::internal::compiler::PropertyAccessInfo::IsFastDataConstant(), jsgraph(), v8::internal::compiler::PropertyAccessInfo::lookup_start_object_maps(), v8::internal::compiler::HeapObjectRef::map(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Ref(), and v8::internal::value.
Referenced by BuildLoadDataField().
Member Data Documentation
broker_
JSHeapBroker* v8::internal::compiler::PropertyAccessBuilder::broker_ [private]
Definition at line 99 of file property-access-builder.h.
Referenced by broker(), and dependencies().
jsgraph_
JSGraph* v8::internal::compiler::PropertyAccessBuilder::jsgraph_ [private]
Definition at line 98 of file property-access-builder.h.
Referenced by jsgraph().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/property-access-builder.h
/mnt/V8SourceCode/src/compiler/property-access-builder.cc