v8::internal::ConservativeStackVisitorBase< ConcreteVisitor > Class Template Reference
#include <conservative-stack-visitor.h>
Public Member Functions
ConservativeStackVisitorBase (Isolate *isolate, RootVisitor *root_visitor)
void VisitPointer (const void *pointer) final
Address FindBasePtr (Address maybe_inner_ptr, PtrComprCageBase cage_base) const
Private Member Functions
void VisitConservativelyIfPointer (Address address)
void VisitConservativelyIfPointer (Address address, PtrComprCageBase cage_base)
Private Attributes
const PtrComprCageBase cage_base_
RootVisitor *const root_visitor_
MemoryAllocator *const allocator_
Detailed Description
template<typename ConcreteVisitor>
class v8::internal::ConservativeStackVisitorBase< ConcreteVisitor >
Definition at line 36 of file conservative-stack-visitor.h.
Constructor & Destructor Documentation
ConservativeStackVisitorBase()
template<typename ConcreteVisitor >
v8::internal::ConservativeStackVisitorBase< ConcreteVisitor >::ConservativeStackVisitorBase (Isolate * isolate, RootVisitor * root_visitor)
Definition at line 30 of file conservative-stack-visitor-inl.h.
    : cage_base_(isolate),
#ifdef V8_EXTERNAL_CODE_SPACE
      code_cage_base_(isolate->code_cage_base()),
      code_address_region_(isolate->heap()->code_region()),
#endif
#ifdef V8_ENABLE_SANDBOX
      trusted_cage_base_(isolate->isolate_data()->trusted_cage_base_address()),
#endif
      root_visitor_(root_visitor),
      allocator_(isolate->heap()->memory_allocator()) {
}
Member Function Documentation
FindBasePtr()
template<typename ConcreteVisitor >
Address v8::internal::ConservativeStackVisitorBase< ConcreteVisitor >::FindBasePtr (Address maybe_inner_ptr, PtrComprCageBase cage_base) const
Definition at line 66 of file conservative-stack-visitor-inl.h.
                                                               {
#ifdef V8_COMPRESS_POINTERS
  DCHECK(IsInterestingCage(cage_base));
#endif // V8_COMPRESS_POINTERS
  // Check if the pointer is contained by a normal or large page owned by this
  // heap. Bail out if it is not.
  // TODO(379788114): Consider introducing a bloom filter for pages.
  const MemoryChunk* chunk =
      allocator_->LookupChunkContainingAddressInSafepoint(maybe_inner_ptr);
  if (chunk == nullptr) {
    return kNullAddress;
  }
  const MemoryChunkMetadata* chunk_metadata = chunk->Metadata();
  DCHECK(chunk_metadata->Contains(maybe_inner_ptr));
  if (!ConcreteVisitor::FilterPage(chunk)) {
    return kNullAddress;
  }
  // If it is contained in a large page, we want to mark the only object on it.
  if (chunk->IsLargePage()) {
    // This could be simplified if we could guarantee that there are no free
    // space or filler objects in large pages. A few cctests violate this now.
    Tagged<HeapObject> obj(
        static_cast<const LargePageMetadata*>(chunk_metadata)->GetObject());
    MapWord map_word = obj->map_word(cage_base, kRelaxedLoad);
    return (!ConcreteVisitor::FilterLargeObject(obj, map_word) ||
            InstanceTypeChecker::IsFreeSpaceOrFiller(map_word.ToMap()))
               ? kNullAddress
               : obj.address();
  }
  // Otherwise, we have a pointer inside a normal page.
  const PageMetadata* page = static_cast<const PageMetadata*>(chunk_metadata);
  // Try to find the address of a previous valid object on this page.
  Address base_ptr =
      MarkingBitmap::FindPreviousValidObject(page, maybe_inner_ptr);
  // Iterate through the objects in the page forwards, until we find the object
  // containing maybe_inner_ptr.
  DCHECK_LE(base_ptr, maybe_inner_ptr);
  MarkingBitmap* bitmap = const_cast<MarkingBitmap*>(page->marking_bitmap());
  while (true) {
    Tagged<HeapObject> obj(HeapObject::FromAddress(base_ptr));
    MapWord map_word = obj->map_word(cage_base, kRelaxedLoad);
    if (!ConcreteVisitor::FilterNormalObject(obj, map_word, bitmap)) {
      return kNullAddress;
    }
    const int size = obj->SizeFromMap(map_word.ToMap());
    DCHECK_LT(0, size);
    if (maybe_inner_ptr < base_ptr + size) {
      ConcreteVisitor::HandleObjectFound(obj, size, bitmap);
      return IsFreeSpaceOrFiller(obj, cage_base) ? kNullAddress : base_ptr;
    }
    base_ptr += ALIGN_TO_ALLOCATION_ALIGNMENT(size);
    DCHECK_LT(base_ptr, page->area_end());
  }
}
References v8::internal::Tagged< HeapObject >::address(), ALIGN_TO_ALLOCATION_ALIGNMENT, v8::internal::MemoryChunkMetadata::area_end(), v8::internal::MemoryChunkMetadata::Contains(), v8::internal::DCHECK(), DCHECK_LE, DCHECK_LT, v8::internal::MarkingBitmap::FindPreviousValidObject(), v8::internal::HeapObject::FromAddress(), v8::internal::InstanceTypeChecker::IsFreeSpaceOrFiller(), v8::internal::MemoryChunk::IsLargePage(), v8::internal::kNullAddress, v8::kRelaxedLoad, v8::internal::MutablePageMetadata::marking_bitmap(), v8::internal::MemoryChunk::Metadata(), size(), and v8::internal::MapWord::ToMap().
VisitConservativelyIfPointer() [1/2]
template<typename ConcreteVisitor >
void v8::internal::ConservativeStackVisitorBase< ConcreteVisitor >::VisitConservativelyIfPointer (Address address) [private]
Definition at line 155 of file conservative-stack-visitor-inl.h.
                                                                  {
#ifdef V8_COMPRESS_POINTERS
  // Only proceed if the address falls in one of the interesting cages,
  // otherwise bail out.
  if (V8HeapCompressionScheme::GetPtrComprCageBaseAddress(address) ==
      cage_base_.address()) {
    VisitConservativelyIfPointer(address, cage_base_);
  } else if constexpr (ConcreteVisitor::kOnlyVisitMainV8Cage) {
    return;
#ifdef V8_EXTERNAL_CODE_SPACE
  } else if (code_address_region_.contains(address)) {
    VisitConservativelyIfPointer(address, code_cage_base_);
#endif // V8_EXTERNAL_CODE_SPACE
  }
#ifdef V8_ENABLE_SANDBOX
  if (TrustedSpaceCompressionScheme::GetPtrComprCageBaseAddress(address) ==
      trusted_cage_base_.address()) {
    VisitConservativelyIfPointer(address, trusted_cage_base_);
  }
#endif // V8_ENABLE_SANDBOX
#else // !V8_COMPRESS_POINTERS
  VisitConservativelyIfPointer(address, cage_base_);
#endif // V8_COMPRESS_POINTERS
}
References v8::internal::V8HeapCompressionSchemeImpl< Cage >::GetPtrComprCageBaseAddress().
VisitConservativelyIfPointer() [2/2]
template<typename ConcreteVisitor >
void v8::internal::ConservativeStackVisitorBase< ConcreteVisitor >::VisitConservativelyIfPointer (Address address, PtrComprCageBase cage_base) [private]
Definition at line 182 of file conservative-stack-visitor-inl.h.
                                                                               {
  // Bail out immediately if the pointer is not in the space managed by the
  // allocator.
  if (allocator_->IsOutsideAllocatedSpace(address)) {
    DCHECK_EQ(nullptr,
              allocator_->LookupChunkContainingAddressInSafepoint(address));
    return;
  }
  // Proceed with inner-pointer resolution.
  Address base_ptr = FindBasePtr(address, cage_base);
  if (base_ptr == kNullAddress) {
    return;
  }
  Tagged<HeapObject> obj = HeapObject::FromAddress(base_ptr);
  Tagged<Object> root = obj;
  DCHECK_NOT_NULL(root_visitor_);
  root_visitor_->VisitRootPointer(Root::kStackRoots, nullptr,
                                  FullObjectSlot(&root));
  // Check that the root visitor did not modify the root slot.
  DCHECK_EQ(root, obj);
}
References DCHECK_EQ, DCHECK_NOT_NULL, v8::internal::HeapObject::FromAddress(), and v8::internal::kNullAddress.
VisitPointer()
template<typename ConcreteVisitor >
void v8::internal::ConservativeStackVisitorBase< ConcreteVisitor >::VisitPointer (const void * pointer) [final], [virtual]
Implements heap::base::StackVisitor.
Definition at line 126 of file conservative-stack-visitor-inl.h.
                         {
  auto address = reinterpret_cast<Address>(const_cast<void*>(pointer));
#ifdef V8_COMPRESS_POINTERS
  V8HeapCompressionScheme::ProcessIntermediatePointers(
      address,
      [this](Address ptr) { VisitConservativelyIfPointer(ptr, cage_base_); });
  if constexpr (ConcreteVisitor::kOnlyVisitMainV8Cage) {
    return;
  }
#ifdef V8_EXTERNAL_CODE_SPACE
  ExternalCodeCompressionScheme::ProcessIntermediatePointers(
      address, [this](Address ptr) {
        VisitConservativelyIfPointer(ptr, code_cage_base_);
      });
#endif // V8_EXTERNAL_CODE_SPACE
#ifdef V8_ENABLE_SANDBOX
  TrustedSpaceCompressionScheme::ProcessIntermediatePointers(
      address, [this](Address ptr) {
        VisitConservativelyIfPointer(ptr, trusted_cage_base_);
      });
#endif // V8_ENABLE_SANDBOX
#else // !V8_COMPRESS_POINTERS
  VisitConservativelyIfPointer(address);
#endif // V8_COMPRESS_POINTERS
}
References v8::internal::V8HeapCompressionSchemeImpl< Cage >::ProcessIntermediatePointers().
Member Data Documentation
allocator_
template<typename ConcreteVisitor >
MemoryAllocator* const v8::internal::ConservativeStackVisitorBase< ConcreteVisitor >::allocator_ [private]
Definition at line 76 of file conservative-stack-visitor.h.
cage_base_
template<typename ConcreteVisitor >
const PtrComprCageBase v8::internal::ConservativeStackVisitorBase< ConcreteVisitor >::cage_base_ [private]
Definition at line 66 of file conservative-stack-visitor.h.
root_visitor_
template<typename ConcreteVisitor >
RootVisitor* const v8::internal::ConservativeStackVisitorBase< ConcreteVisitor >::root_visitor_ [private]
Definition at line 75 of file conservative-stack-visitor.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/conservative-stack-visitor.h
/mnt/V8SourceCode/src/heap/conservative-stack-visitor-inl.h