v8::internal::JSFinalizationRegistry::BodyDescriptor Class Reference
#include <objects-body-descriptors-inl.h>
Static Public Member Functions
template<typename ObjectVisitor >
static void IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor *v)
static int SizeOf (Tagged< Map > map, Tagged< HeapObject > object)
Additional Inherited Members
Detailed Description
Definition at line 510 of file objects-body-descriptors-inl.h.
Member Function Documentation
IterateBody()
template<typename ObjectVisitor >
static void v8::internal::JSFinalizationRegistry::BodyDescriptor::IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor * v) [inline], [static]
Definition at line 513 of file objects-body-descriptors-inl.h.
                                                                    {
    IteratePointers(obj, JSObject::BodyDescriptor::kStartOffset,
                    kNextDirtyOffset, v);
    IterateCustomWeakPointer(obj, kNextDirtyOffset, v);
    IterateJSObjectBodyImpl(map, obj, kNextDirtyOffset + kTaggedSize,
                            object_size, v);
  }
References v8::internal::BodyDescriptorBase::IterateCustomWeakPointer(), v8::internal::BodyDescriptorBase::IterateJSObjectBodyImpl(), v8::internal::BodyDescriptorBase::IteratePointers(), v8::internal::JSObject::BodyDescriptor::kStartOffset, and v8::internal::kTaggedSize.
SizeOf()
static int v8::internal::JSFinalizationRegistry::BodyDescriptor::SizeOf (Tagged< Map > map, Tagged< HeapObject > object) [inline], [static]
Definition at line 522 of file objects-body-descriptors-inl.h.
                                                                       {
    return map->instance_size();
  }
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/objects-body-descriptors-inl.h