v8::internal::VirtualMemoryCage Class Reference
#include <allocation.h>
Classes
struct ReservationParams
Public Member Functions
VirtualMemoryCage ()
virtual ~VirtualMemoryCage ()
VirtualMemoryCage (const VirtualMemoryCage &)=delete
VirtualMemoryCage & operator= (VirtualMemoryCage &)=delete
VirtualMemoryCage (VirtualMemoryCage &&other) V8_NOEXCEPT
VirtualMemoryCage & operator= (VirtualMemoryCage &&other) V8_NOEXCEPT
Address base () const
size_t size () const
base::AddressRegion region () const
base::BoundedPageAllocator * page_allocator () const
VirtualMemory * reservation ()
const VirtualMemory * reservation () const
bool IsReserved () const
bool InitReservation (const ReservationParams &params, base::AddressRegion existing_reservation=base::AddressRegion())
void Free ()
Protected Attributes
Address base_ = kNullAddress
size_t size_ = 0
std::unique_ptr< base::BoundedPageAllocator > page_allocator_
VirtualMemory reservation_
Detailed Description
Definition at line 356 of file allocation.h.
Constructor & Destructor Documentation
VirtualMemoryCage() [1/3]
v8::internal::VirtualMemoryCage::VirtualMemoryCage () [default]
 VirtualMemoryCage()
v8::internal::VirtualMemoryCage::~VirtualMemoryCage () [virtual]
Definition at line 307 of file allocation.cc.
{ Free(); }
References Free().
VirtualMemoryCage() [2/3]
v8::internal::VirtualMemoryCage::VirtualMemoryCage (const VirtualMemoryCage &) [delete]
VirtualMemoryCage() [3/3]
v8::internal::VirtualMemoryCage::VirtualMemoryCage (VirtualMemoryCage && other)
Definition at line 309 of file allocation.cc.
                                                                          {
  *this = std::move(other);
}
Member Function Documentation
base()
Address v8::internal::VirtualMemoryCage::base () const [inline]
Definition at line 367 of file allocation.h.
{ return base_; }
References base_.
Referenced by v8::internal::CodeRange::Free(), v8::internal::Isolate::Init(), v8::internal::anonymous_namespace{isolate-group.cc}::InitCodeRangeOnce(), and v8::internal::CodeRange::InitReservation().
Free()
void v8::internal::VirtualMemoryCage::Free ()
Definition at line 372 of file allocation.cc.
                             {
  if (IsReserved()) {
    base_ = kNullAddress;
    size_ = 0;
    page_allocator_.reset();
    reservation_.Free();
  }
}
References base_, v8::internal::VirtualMemory::Free(), IsReserved(), v8::internal::kNullAddress, page_allocator_, reservation_, and size_.
Referenced by v8::internal::CodeRange::Free(), v8::internal::CodeRange::InitReservation(), and ~VirtualMemoryCage().
InitReservation()
bool v8::internal::VirtualMemoryCage::InitReservation (const ReservationParams & params, base::AddressRegion existing_reservation = base::AddressRegion())
Definition at line 324 of file allocation.cc.
                                                                             {
  DCHECK(!reservation_.IsReserved());
  const size_t allocate_page_size = params.page_allocator->AllocatePageSize();
  CHECK(IsAligned(params.reservation_size, allocate_page_size));
  CHECK(params.base_alignment == ReservationParams::kAnyBaseAlignment ||
        IsAligned(params.base_alignment, allocate_page_size));
  if (!existing_reservation.is_empty()) {
    CHECK_EQ(existing_reservation.size(), params.reservation_size);
    CHECK(params.base_alignment == ReservationParams::kAnyBaseAlignment ||
          IsAligned(existing_reservation.begin(), params.base_alignment));
    reservation_ =
        VirtualMemory(params.page_allocator, existing_reservation.begin(),
                      existing_reservation.size());
    base_ = reservation_.address();
  } else {
    Address hint = params.requested_start_hint;
    // Require the hint to be properly aligned because here it's not clear
    // anymore whether it should be rounded up or down.
    CHECK(IsAligned(hint, params.base_alignment));
    VirtualMemory reservation(params.page_allocator, params.reservation_size,
                              v8::PageAllocator::AllocationHint().WithAddress(
                                  reinterpret_cast<void*>(hint)),
                              params.base_alignment, params.permissions);
    // The virtual memory reservation fails only due to OOM.
    if (!reservation.IsReserved()) return false;
    reservation_ = std::move(reservation);
    base_ = reservation_.address();
    CHECK_EQ(reservation_.size(), params.reservation_size);
  }
  CHECK_NE(base_, kNullAddress);
  CHECK(IsAligned(base_, params.base_alignment));
  const Address allocatable_base = RoundUp(base_, params.page_size);
  const size_t allocatable_size = RoundDown(
      params.reservation_size - (allocatable_base - base_), params.page_size);
  size_ = allocatable_base + allocatable_size - base_;
  page_allocator_ = std::make_unique<base::BoundedPageAllocator>(
      params.page_allocator, allocatable_base, allocatable_size,
      params.page_size, params.page_initialization_mode,
      params.page_freeing_mode);
  return true;
}
References v8::internal::VirtualMemory::address(), v8::PageAllocator::AllocatePageSize(), base_, v8::internal::VirtualMemoryCage::ReservationParams::base_alignment, v8::base::AddressRegion::begin(), CHECK, CHECK_EQ, CHECK_NE, v8::internal::DCHECK(), v8::base::AddressRegion::is_empty(), IsAligned(), v8::internal::VirtualMemory::IsReserved(), v8::internal::VirtualMemoryCage::ReservationParams::kAnyBaseAlignment, v8::internal::kNullAddress, v8::internal::VirtualMemoryCage::ReservationParams::page_allocator, page_allocator_, v8::internal::VirtualMemoryCage::ReservationParams::page_freeing_mode, v8::internal::VirtualMemoryCage::ReservationParams::page_initialization_mode, v8::internal::VirtualMemoryCage::ReservationParams::page_size, v8::internal::VirtualMemoryCage::ReservationParams::permissions, v8::internal::VirtualMemoryCage::ReservationParams::requested_start_hint, reservation(), reservation_, v8::internal::VirtualMemoryCage::ReservationParams::reservation_size, RoundDown(), RoundUp(), v8::base::AddressRegion::size(), v8::internal::VirtualMemory::size(), size_, and v8::PageAllocator::AllocationHint::WithAddress().
Referenced by v8::internal::CodeRange::InitReservation().
IsReserved()
bool v8::internal::VirtualMemoryCage::IsReserved () const [inline]
Definition at line 381 of file allocation.h.
                          {
    DCHECK_EQ(base_ != kNullAddress, reservation_.IsReserved());
    DCHECK_EQ(base_ != kNullAddress, size_ != 0);
    return reservation_.IsReserved();
  }
References base_, DCHECK_EQ, v8::internal::VirtualMemory::IsReserved(), v8::internal::kNullAddress, reservation_, and size_.
Referenced by v8::internal::CodeRange::Free(), Free(), and v8::internal::CodeRange::InitReservation().
operator=() [1/2]
VirtualMemoryCage & v8::internal::VirtualMemoryCage::operator= (VirtualMemoryCage && other)
Definition at line 313 of file allocation.cc.
                {
  base_ = other.base_;
  size_ = other.size_;
  page_allocator_ = std::move(other.page_allocator_);
  reservation_ = std::move(other.reservation_);
  other.base_ = kNullAddress;
  other.size_ = 0;
  return *this;
}
References v8::internal::kNullAddress.
operator=() [2/2]
VirtualMemoryCage& v8::internal::VirtualMemoryCage::operator= (VirtualMemoryCage &) [delete]
page_allocator()
base::BoundedPageAllocator* v8::internal::VirtualMemoryCage::page_allocator () const [inline]
Definition at line 374 of file allocation.h.
                                                   {
    return page_allocator_.get();
  }
References page_allocator_.
Referenced by v8::internal::CodeRange::InitReservation(), and v8::internal::CodeRange::RemapEmbeddedBuiltins().
region()
base::AddressRegion v8::internal::VirtualMemoryCage::region () const [inline]
Definition at line 370 of file allocation.h.
                                   {
    return base::AddressRegion{base_, size_};
  }
References base_, and size_.
Referenced by v8::internal::CodeRange::Free(), and v8::internal::CodeRange::InitReservation().
reservation() [1/2]
VirtualMemory* v8::internal::VirtualMemoryCage::reservation () [inline]
Definition at line 378 of file allocation.h.
{ return &reservation_; }
References reservation_.
Referenced by v8::internal::CodeRange::Free(), InitReservation(), and v8::internal::CodeRange::InitReservation().
reservation() [2/2]
const VirtualMemory* v8::internal::VirtualMemoryCage::reservation () const [inline]
Definition at line 379 of file allocation.h.
{ return &reservation_; }
References reservation_.
size()
size_t v8::internal::VirtualMemoryCage::size () const [inline]
Definition at line 368 of file allocation.h.
{ return size_; }
References size_.
Referenced by v8::internal::CodeRange::Free(), v8::internal::Isolate::Init(), v8::internal::CodeRange::InitReservation(), and v8::internal::CodeRange::RemapEmbeddedBuiltins().
Member Data Documentation
base_
Address v8::internal::VirtualMemoryCage::base_ = kNullAddress [protected]
Definition at line 415 of file allocation.h.
Referenced by base(), Free(), InitReservation(), IsReserved(), and region().
page_allocator_
std::unique_ptr<base::BoundedPageAllocator> v8::internal::VirtualMemoryCage::page_allocator_ [protected]
Definition at line 417 of file allocation.h.
Referenced by Free(), InitReservation(), v8::internal::CodeRange::InitReservation(), and page_allocator().
reservation_
VirtualMemory v8::internal::VirtualMemoryCage::reservation_ [protected]
Definition at line 418 of file allocation.h.
Referenced by Free(), InitReservation(), IsReserved(), and reservation().
size_
size_t v8::internal::VirtualMemoryCage::size_ = 0 [protected]
Definition at line 416 of file allocation.h.
Referenced by Free(), InitReservation(), IsReserved(), region(), and size().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/utils/allocation.h
/mnt/V8SourceCode/src/utils/allocation.cc