v8::internal::anonymous_namespace{sweeper.cc}::PromotedPageRecordMigratedSlotVisitor Class Reference
Public Member Functions
PromotedPageRecordMigratedSlotVisitor (MutablePageMetadata *host_page)
void Process (Tagged< HeapObject > object)
void VisitMapPointer (Tagged< HeapObject > host) final
void VisitPointer (Tagged< HeapObject > host, ObjectSlot p) final
void VisitPointer (Tagged< HeapObject > host, MaybeObjectSlot p) final
void VisitPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) final
void VisitPointers (Tagged< HeapObject > host, MaybeObjectSlot start, MaybeObjectSlot end) final
size_t VisitJSArrayBuffer (Tagged< Map > map, Tagged< JSArrayBuffer > object, MaybeObjectSize maybe_object_size)
size_t VisitEphemeronHashTable (Tagged< Map > map, Tagged< EphemeronHashTable > table, MaybeObjectSize)
void VisitExternalReference (Tagged< InstructionStream > host, RelocInfo *rinfo) final
void VisitInternalReference (Tagged< InstructionStream > host, RelocInfo *rinfo) final
void VisitExternalPointer (Tagged< HeapObject > host, ExternalPointerSlot slot) final
Static Public Member Functions
static constexpr bool EnableConcurrentVisitation ()
static constexpr bool ShouldVisitMapPointer ()
static constexpr bool ShouldVisitReadOnlyMapPointer ()
Private Member Functions
void VerifyHost (Tagged< HeapObject > host)
template<typename TObject >
void VisitObjectImpl (Tagged< HeapObject > host, TObject object, Address slot)
template<typename TSlot >
void VisitPointersImpl (Tagged< HeapObject > host, TSlot start, TSlot end)
Private Attributes
MemoryChunk *const host_chunk_
MutablePageMetadata *const host_page_
EphemeronRememberedSet * ephemeron_remembered_set_
Additional Inherited Members
Detailed Description
Definition at line 444 of file sweeper.cc.
Constructor & Destructor Documentation
PromotedPageRecordMigratedSlotVisitor()
v8::internal::anonymous_namespace{sweeper.cc}::PromotedPageRecordMigratedSlotVisitor::PromotedPageRecordMigratedSlotVisitor (MutablePageMetadata * host_page) [inline], [explicit]
Definition at line 447 of file sweeper.cc.
      : NewSpaceVisitor<PromotedPageRecordMigratedSlotVisitor>(
            host_page->heap()->isolate()),
        host_chunk_(host_page->Chunk()),
        host_page_(host_page),
        ephemeron_remembered_set_(
            host_page->heap()->ephemeron_remembered_set()) {
    DCHECK(host_page->owner_identity() == OLD_SPACE ||
           host_page->owner_identity() == LO_SPACE);
  }
References v8::internal::DCHECK(), v8::internal::LO_SPACE, v8::internal::OLD_SPACE, and v8::internal::MutablePageMetadata::owner_identity().
Member Function Documentation
EnableConcurrentVisitation()
static constexpr bool v8::internal::anonymous_namespace{sweeper.cc}::PromotedPageRecordMigratedSlotVisitor::EnableConcurrentVisitation () [inline], [static], [constexpr]
Definition at line 471 of file sweeper.cc.
{ return true; }
Process()
void v8::internal::anonymous_namespace{sweeper.cc}::PromotedPageRecordMigratedSlotVisitor::Process (Tagged< HeapObject > object) [inline]
Definition at line 458 of file sweeper.cc.
                                          {
    Tagged<Map> map = object->map(cage_base());
    if (Map::ObjectFieldsFrom(map->visitor_id()) == ObjectFields::kDataOnly) {
      return;
    }
    Visit(map, object);
  }
References v8::internal::kDataOnly, and v8::internal::Map::ObjectFieldsFrom().
ShouldVisitMapPointer()
static constexpr bool v8::internal::anonymous_namespace{sweeper.cc}::PromotedPageRecordMigratedSlotVisitor::ShouldVisitMapPointer () [inline], [static], [constexpr]
Definition at line 543 of file sweeper.cc.
{ return true; }
ShouldVisitReadOnlyMapPointer()
static constexpr bool v8::internal::anonymous_namespace{sweeper.cc}::PromotedPageRecordMigratedSlotVisitor::ShouldVisitReadOnlyMapPointer () [inline], [static], [constexpr]
Definition at line 544 of file sweeper.cc.
                                                                  {
    return false;
  }
VerifyHost()
void v8::internal::anonymous_namespace{sweeper.cc}::PromotedPageRecordMigratedSlotVisitor::VerifyHost (Tagged< HeapObject > host) [inline], [private]
Definition at line 549 of file sweeper.cc.
                                                     {
    DCHECK(!HeapLayout::InWritableSharedSpace(host));
    DCHECK(!HeapLayout::InYoungGeneration(host));
    DCHECK(!MutablePageMetadata::FromHeapObject(host)->SweepingDone());
    DCHECK_EQ(MutablePageMetadata::FromHeapObject(host), host_page_);
  }
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::MutablePageMetadata::FromHeapObject(), v8::internal::HeapLayout::InWritableSharedSpace(), and v8::internal::HeapLayout::InYoungGeneration().
VisitEphemeronHashTable()
size_t v8::internal::anonymous_namespace{sweeper.cc}::PromotedPageRecordMigratedSlotVisitor::VisitEphemeronHashTable (Tagged< Map > map, Tagged< EphemeronHashTable > table, MaybeObjectSize) [inline]
Definition at line 502 of file sweeper.cc.
                                                            {
    NewSpaceVisitor<PromotedPageRecordMigratedSlotVisitor>::
        VisitMapPointerIfNeeded<VisitorId::kVisitEphemeronHashTable>(table);
    EphemeronRememberedSet::IndicesSet indices;
    for (InternalIndex i : table->IterateEntries()) {
      ObjectSlot value_slot =
          table->RawFieldOfElementAt(EphemeronHashTable::EntryToValueIndex(i));
      VisitPointer(table, value_slot);
      ObjectSlot key_slot =
          table->RawFieldOfElementAt(EphemeronHashTable::EntryToIndex(i));
      Tagged<Object> key = key_slot.Acquire_Load();
      Tagged<HeapObject> key_object;
      if (!key.GetHeapObject(&key_object)) continue;
#ifdef THREAD_SANITIZER
      MemoryChunk::FromHeapObject(key_object)->SynchronizedLoad();
#endif // THREAD_SANITIZER
      // With sticky mark-bits we don't need to update the remembered set for
      // just promoted objects, since everything is promoted.
      if (!v8_flags.sticky_mark_bits &&
          HeapLayout::InYoungGeneration(key_object)) {
        indices.insert(i.as_int());
      }
    }
    if (!indices.empty()) {
      ephemeron_remembered_set_->RecordEphemeronKeyWrites(table,
                                                          std::move(indices));
    }
    return EphemeronHashTable::BodyDescriptor::SizeOf(map, table);
  }
References v8::internal::FullObjectSlot::Acquire_Load(), v8::internal::MemoryChunk::FromHeapObject(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::key, v8::internal::EphemeronHashTable::BodyDescriptor::SizeOf(), and v8::internal::v8_flags.
VisitExternalPointer()
void v8::internal::anonymous_namespace{sweeper.cc}::PromotedPageRecordMigratedSlotVisitor::VisitExternalPointer (Tagged< HeapObject > host, ExternalPointerSlot slot) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 539 of file sweeper.cc.
                                                            {}
VisitExternalReference()
void v8::internal::anonymous_namespace{sweeper.cc}::PromotedPageRecordMigratedSlotVisitor::VisitExternalReference (Tagged< InstructionStream > host, RelocInfo * rinfo) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 535 of file sweeper.cc.
                                                      {}
VisitInternalReference()
void v8::internal::anonymous_namespace{sweeper.cc}::PromotedPageRecordMigratedSlotVisitor::VisitInternalReference (Tagged< InstructionStream > host, RelocInfo * rinfo) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 537 of file sweeper.cc.
                                                      {}
VisitJSArrayBuffer()
size_t v8::internal::anonymous_namespace{sweeper.cc}::PromotedPageRecordMigratedSlotVisitor::VisitJSArrayBuffer (Tagged< Map > map, Tagged< JSArrayBuffer > object, MaybeObjectSize maybe_object_size) [inline]
Definition at line 494 of file sweeper.cc.
                                                                         {
    object->YoungMarkExtensionPromoted();
    return NewSpaceVisitor<PromotedPageRecordMigratedSlotVisitor>::
        VisitJSArrayBuffer(map, object, maybe_object_size);
  }
VisitMapPointer()
void v8::internal::anonymous_namespace{sweeper.cc}::PromotedPageRecordMigratedSlotVisitor::VisitMapPointer (Tagged< HeapObject > host) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 473 of file sweeper.cc.
                                                                {
    VerifyHost(host);
    VisitObjectImpl(host, host->map(cage_base()), host->map_slot().address());
  }
VisitObjectImpl()
template<typename TObject >
void v8::internal::anonymous_namespace{sweeper.cc}::PromotedPageRecordMigratedSlotVisitor::VisitObjectImpl (Tagged< HeapObject > host, TObject object, Address slot) [inline], [private]
Definition at line 557 of file sweeper.cc.
                                               {
    Tagged<HeapObject> value_heap_object;
    if (!object.GetHeapObject(&value_heap_object)) return;
    MemoryChunk* value_chunk = MemoryChunk::FromHeapObject(value_heap_object);
#ifdef THREAD_SANITIZER
    value_chunk->SynchronizedLoad();
#endif // THREAD_SANITIZER
    // With sticky mark-bits we don't need to update the remembered set for
    // just promoted objects, since everything is promoted.
    if (!v8_flags.sticky_mark_bits && value_chunk->InYoungGeneration()) {
      RememberedSet<OLD_TO_NEW_BACKGROUND>::Insert<AccessMode::ATOMIC>(
          host_page_, host_chunk_->Offset(slot));
    } else if (value_chunk->InWritableSharedSpace()) {
      RememberedSet<OLD_TO_SHARED>::Insert<AccessMode::ATOMIC>(
          host_page_, host_chunk_->Offset(slot));
    }
  }
References v8::internal::MemoryChunk::FromHeapObject(), v8::internal::MemoryChunk::InWritableSharedSpace(), v8::internal::MemoryChunk::InYoungGeneration(), and v8::internal::v8_flags.
VisitPointer() [1/2]
void v8::internal::anonymous_namespace{sweeper.cc}::PromotedPageRecordMigratedSlotVisitor::VisitPointer (Tagged< HeapObject > host, MaybeObjectSlot p) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 481 of file sweeper.cc.
                                                       {
    VisitPointersImpl(host, p, p + 1);
  }
VisitPointer() [2/2]
void v8::internal::anonymous_namespace{sweeper.cc}::PromotedPageRecordMigratedSlotVisitor::VisitPointer (Tagged< HeapObject > host, ObjectSlot p) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 478 of file sweeper.cc.
                                                                           {
    VisitPointersImpl(host, p, p + 1);
  }
VisitPointers() [1/2]
void v8::internal::anonymous_namespace{sweeper.cc}::PromotedPageRecordMigratedSlotVisitor::VisitPointers (Tagged< HeapObject > host, MaybeObjectSlot start, MaybeObjectSlot end) [inline], [final], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 489 of file sweeper.cc.
                                                          {
    VisitPointersImpl(host, start, end);
  }
References v8::internal::compiler::end().
VisitPointers() [2/2]
void v8::internal::anonymous_namespace{sweeper.cc}::PromotedPageRecordMigratedSlotVisitor::VisitPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) [inline], [final], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 485 of file sweeper.cc.
                                                     {
    VisitPointersImpl(host, start, end);
  }
References v8::internal::compiler::end().
VisitPointersImpl()
template<typename TSlot >
void v8::internal::anonymous_namespace{sweeper.cc}::PromotedPageRecordMigratedSlotVisitor::VisitPointersImpl (Tagged< HeapObject > host, TSlot start, TSlot end) [inline], [private]
Definition at line 578 of file sweeper.cc.
                                              {
    VerifyHost(host);
    for (TSlot slot = start; slot < end; ++slot) {
      typename TSlot::TObject target =
          slot.Relaxed_Load(ObjectVisitorWithCageBases::cage_base());
      VisitObjectImpl(host, target, slot.address());
    }
  }
References v8::internal::Tagged< HeapObject >::address(), v8::internal::ObjectVisitorWithCageBases::cage_base(), and v8::internal::compiler::end().
Member Data Documentation
ephemeron_remembered_set_
EphemeronRememberedSet* v8::internal::anonymous_namespace{sweeper.cc}::PromotedPageRecordMigratedSlotVisitor::ephemeron_remembered_set_ [private]
Definition at line 590 of file sweeper.cc.
host_chunk_
MemoryChunk* const v8::internal::anonymous_namespace{sweeper.cc}::PromotedPageRecordMigratedSlotVisitor::host_chunk_ [private]
Definition at line 588 of file sweeper.cc.
host_page_
MutablePageMetadata* const v8::internal::anonymous_namespace{sweeper.cc}::PromotedPageRecordMigratedSlotVisitor::host_page_ [private]
Definition at line 589 of file sweeper.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/sweeper.cc