v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler > Class Template Reference
#include <assembler.h>
Public Types
using MessageWithSourceLocation = CodeAssembler::MessageWithSourceLocation
Public Member Functions
template<typename... Args>
TurboshaftAssemblerOpInterface (Args... args)
const OperationMatcher & matcher () const
V< Word32 > Word32SignHint (V< Word32 > input, Word32SignHintOp::Sign sign)
V< Word32 > Word32SignHintUnsigned (V< Word32 > input)
V< Word32 > Word32SignHintSigned (V< Word32 > input)
V< Object > GenericBinop (V< Object > left, V< Object > right, V< turboshaft::FrameState > frame_state, V< Context > context, GenericBinopOp::Kind kind, LazyDeoptOnThrow lazy_deopt_on_throw)
V< Object > GenericUnop (V< Object > input, V< turboshaft::FrameState > frame_state, V< Context > context, GenericUnopOp::Kind kind, LazyDeoptOnThrow lazy_deopt_on_throw)
V< Object > ToNumberOrNumeric (V< Object > input, V< turboshaft::FrameState > frame_state, V< Context > context, Object::Conversion kind, LazyDeoptOnThrow lazy_deopt_on_throw)
V< Object > ToNumber (V< Object > input, V< turboshaft::FrameState > frame_state, V< Context > context, LazyDeoptOnThrow lazy_deopt_on_throw)
V< Object > ToNumeric (V< Object > input, V< turboshaft::FrameState > frame_state, V< Context > context, LazyDeoptOnThrow lazy_deopt_on_throw)
DECL_MULTI_REP_BINOP_V (IntMulOverflownBits, WordBinop, SignedMulOverflownBits, Word) DECL_SINGLE_REP_BINOP_V(Int32MulOverflownBits
Word32 DECL_SINGLE_REP_BINOP_V (Int64MulOverflownBits, WordBinop, SignedMulOverflownBits, Word64) DECL_MULTI_REP_BINOP_V(UintMulOverflownBits
Word32 Word DECL_SINGLE_REP_BINOP_V (Uint32MulOverflownBits, WordBinop, UnsignedMulOverflownBits, Word32) DECL_SINGLE_REP_BINOP_V(Uint64MulOverflownBits
Word32 Word Word64 V< Word32 > Word32BitwiseNot (ConstOrV< Word32 > input)
V< Word > WordBinop (V< Word > left, V< Word > right, WordBinopOp::Kind kind, WordRepresentation rep)
V< turboshaft::Tuple< Word, Word32 > > OverflowCheckedBinop (V< Word > left, V< Word > right, OverflowCheckedBinopOp::Kind kind, WordRepresentation rep)
DECL_MULTI_REP_CHECK_BINOP_V (IntAddCheckOverflow, OverflowCheckedBinop, SignedAdd, Word) DECL_SINGLE_REP_CHECK_BINOP_V(Int32AddCheckOverflow
Word32 DECL_SINGLE_REP_CHECK_BINOP_V (Int64AddCheckOverflow, OverflowCheckedBinop, SignedAdd, Word64) DECL_MULTI_REP_CHECK_BINOP_V(IntSubCheckOverflow
Word32 Word DECL_SINGLE_REP_CHECK_BINOP_V (Int32SubCheckOverflow, OverflowCheckedBinop, SignedSub, Word32) DECL_SINGLE_REP_CHECK_BINOP_V(Int64SubCheckOverflow
Word32 Word Word64 DECL_MULTI_REP_CHECK_BINOP_V (IntMulCheckOverflow, OverflowCheckedBinop, SignedMul, Word) DECL_SINGLE_REP_CHECK_BINOP_V(Int32MulCheckOverflow
Word32 Word Word64 Word32 DECL_SINGLE_REP_CHECK_BINOP_V (Int64MulCheckOverflow, OverflowCheckedBinop, SignedMul, Word64) V< Word > Shift(V< Word > left
DECL_MULTI_REP_BINOP (ShiftRightArithmeticShiftOutZeros, Shift, WordRepresentation, ShiftRightArithmeticShiftOutZeros) DECL_SINGLE_REP_SHIFT_V(Word32ShiftRightArithmeticShiftOutZeros
Word32 DECL_SINGLE_REP_SHIFT_V (Word64ShiftRightArithmeticShiftOutZeros, ShiftRightArithmeticShiftOutZeros, Word64) DECL_SINGLE_REP_SHIFT_V(WordPtrShiftRightArithmeticShiftOutZeros
Word32 WordPtr DECL_MULTI_REP_BINOP (ShiftRightArithmetic, Shift, WordRepresentation, ShiftRightArithmetic) DECL_SINGLE_REP_SHIFT_V(Word32ShiftRightArithmetic
Word32 WordPtr Word32 DECL_SINGLE_REP_SHIFT_V (Word64ShiftRightArithmetic, ShiftRightArithmetic, Word64) DECL_SINGLE_REP_SHIFT_V(WordPtrShiftRightArithmetic
Word32 WordPtr Word32 WordPtr DECL_MULTI_REP_BINOP (ShiftRightLogical, Shift, WordRepresentation, ShiftRightLogical) V< Word > ShiftRightLogical(V< Word > left
DCHECK_LT (right, rep.bit_width())
return ShiftRightLogical (left, this->Word32Constant(right), rep)
V< Word > ShiftRightArithmetic (V< Word > left, uint32_t right, WordRepresentation rep)
V< Word > ShiftLeft (V< Word > left, uint32_t right, WordRepresentation rep)
V< Word32 > Equal (V< Any > left, V< Any > right, RegisterRepresentation rep)
V< Word32 > TaggedEqual (V< Object > left, V< Object > right)
V< Word32 > RootEqual (V< Object > input, RootIndex root, Isolate *isolate)
DECL_MULTI_REP_BINOP (IntLessThan, Comparison, RegisterRepresentation, SignedLessThan) DECL_MULTI_REP_BINOP(UintLessThan
UnsignedLessThan DECL_MULTI_REP_BINOP (FloatLessThan, Comparison, RegisterRepresentation, SignedLessThan) DECL_MULTI_REP_BINOP(IntLessThanOrEqual
UnsignedLessThan SignedLessThanOrEqual DECL_SINGLE_REP_COMPARISON_V (Int32LessThanOrEqual, SignedLessThanOrEqual, Word32) DECL_SINGLE_REP_COMPARISON_V(Int64LessThanOrEqual
UnsignedLessThan SignedLessThanOrEqual Word64 DECL_SINGLE_REP_COMPARISON_V (IntPtrLessThanOrEqual, SignedLessThanOrEqual, WordPtr) DECL_MULTI_REP_BINOP(UintLessThanOrEqual
UnsignedLessThan SignedLessThanOrEqual Word64 UnsignedLessThanOrEqual DECL_SINGLE_REP_COMPARISON_V (Uint32LessThanOrEqual, UnsignedLessThanOrEqual, Word32) DECL_SINGLE_REP_COMPARISON_V(Uint64LessThanOrEqual
UnsignedLessThan SignedLessThanOrEqual Word64 UnsignedLessThanOrEqual Word64 DECL_SINGLE_REP_COMPARISON_V (UintPtrLessThanOrEqual, UnsignedLessThanOrEqual, WordPtr) DECL_MULTI_REP_BINOP(FloatLessThanOrEqual
UnsignedLessThan SignedLessThanOrEqual Word64 UnsignedLessThanOrEqual Word64 SignedLessThanOrEqual DECL_SINGLE_REP_COMPARISON_V (Float32LessThanOrEqual, SignedLessThanOrEqual, Float32) DECL_SINGLE_REP_COMPARISON_V(Float64LessThanOrEqual
UnsignedLessThan SignedLessThanOrEqual Word64 UnsignedLessThanOrEqual Word64 SignedLessThanOrEqual Float64 V< Word32 > Comparison (OpIndex left, OpIndex right, ComparisonOp::Kind kind, RegisterRepresentation rep)
V< Float > FloatUnary (V< Float > input, FloatUnaryOp::Kind kind, FloatRepresentation rep)
V< Float64 > Float64Unary (V< Float64 > input, FloatUnaryOp::Kind kind)
DECL_MULTI_REP_UNARY_V (FloatNegate, FloatUnary, FloatRepresentation, Negate, Float) DECL_MULTI_REP_UNARY_V(FloatRoundDown
Float DECL_MULTI_REP_UNARY_V (FloatRoundUp, FloatUnary, FloatRepresentation, RoundUp, Float) DECL_MULTI_REP_UNARY_V(FloatRoundToZero
Float Float DECL_MULTI_REP_UNARY_V (FloatRoundTiesEven, FloatUnary, FloatRepresentation, RoundTiesEven, Float) DECL_SINGLE_REP_UNARY_V(Float32RoundTiesEven
Float Float Float32 DECL_SINGLE_REP_UNARY_V (Float64RoundTiesEven, FloatUnary, RoundTiesEven, Float64) DECL_MULTI_REP_UNARY_V(FloatSqrt
Float Float Float32 Float DECL_MULTI_REP_UNARY_V (WordReverseBytes, WordUnary, WordRepresentation, ReverseBytes, Word) DECL_MULTI_REP_UNARY_V(WordCountLeadingZeros
Float Float Float32 Float Word DECL_SINGLE_REP_UNARY_V (Word32CountLeadingZeros, WordUnary, CountLeadingZeros, Word32) DECL_SINGLE_REP_UNARY_V(Word64CountLeadingZeros
Float Float Float32 Float Word Word64 DECL_MULTI_REP_UNARY_V (WordCountTrailingZeros, WordUnary, WordRepresentation, CountTrailingZeros, Word) DECL_SINGLE_REP_UNARY_V(Word32CountTrailingZeros
Float Float Float32 Float Word Word64 Word32 DECL_SINGLE_REP_UNARY_V (Word64CountTrailingZeros, WordUnary, CountTrailingZeros, Word64) DECL_MULTI_REP_UNARY_V(WordPopCount
Float Float Float32 Float Word Word64 Word32 Word DECL_MULTI_REP_UNARY_V (WordSignExtend8, WordUnary, WordRepresentation, SignExtend8, Word) DECL_MULTI_REP_UNARY_V(WordSignExtend16
Float Float Float32 Float Word Word64 Word32 Word Word V< turboshaft::Tuple< Word, Word32 > > OverflowCheckedUnary (V< Word > input, OverflowCheckedUnaryOp::Kind kind, WordRepresentation rep)
DECL_MULTI_REP_UNARY_V (IntAbsCheckOverflow, OverflowCheckedUnary, WordRepresentation, Abs, Word) DECL_SINGLE_REP_UNARY_V(Int32AbsCheckOverflow
Word32 DECL_SINGLE_REP_UNARY_V (Int64AbsCheckOverflow, OverflowCheckedUnary, Abs, Word64) V< Word > WordBinopDeoptOnOverflow(V< Word > left
V< Float64 > BitcastWord32PairToFloat64 (ConstOrV< Word32 > high_word32, ConstOrV< Word32 > low_word32)
OpIndex TaggedBitcast (OpIndex input, RegisterRepresentation from, RegisterRepresentation to, TaggedBitcastOp::Kind kind)
V< Object > BitcastWordPtrToTagged (V< WordPtr > input)
V< WordPtr > BitcastTaggedToWordPtr (V< Object > input)
V< WordPtr > BitcastTaggedToWordPtrForTagAndSmiBits (V< Object > input)
V< Word32 > ObjectIs (V< Object > input, ObjectIsOp::Kind kind, ObjectIsOp::InputAssumptions input_assumptions)
V< Word32 > Float64Is (V< Float64 > input, NumericKind kind)
V< Word32 > Float64IsNaN (V< Float64 > input)
V< Word32 > Float64IsHole (V< Float64 > input)
V< Word32 > Float64IsSmi (V< Float64 > input)
V< Word32 > ObjectIsNumericValue (V< Object > input, NumericKind kind, FloatRepresentation input_rep)
V< Object > Convert (V< Object > input, ConvertOp::Kind from, ConvertOp::Kind to)
V< Number > ConvertPlainPrimitiveToNumber (V< PlainPrimitive > input)
V< Boolean > ConvertToBoolean (V< Object > input)
V< String > ConvertNumberToString (V< Number > input)
V< Number > ConvertStringToNumber (V< String > input)
V< JSPrimitive > ConvertUntaggedToJSPrimitive (V< Untagged > input, ConvertUntaggedToJSPrimitiveOp::JSPrimitiveKind kind, RegisterRepresentation input_rep, ConvertUntaggedToJSPrimitiveOp::InputInterpretation input_interpretation, CheckForMinusZeroMode minus_zero_mode)
V< Number > ConvertFloat64ToNumber (V< Float64 > input, CheckForMinusZeroMode minus_zero_mode)
V< JSPrimitive > ConvertUntaggedToJSPrimitiveOrDeopt (V< Untagged > input, V< turboshaft::FrameState > frame_state, ConvertUntaggedToJSPrimitiveOrDeoptOp::JSPrimitiveKind kind, RegisterRepresentation input_rep, ConvertUntaggedToJSPrimitiveOrDeoptOp::InputInterpretation input_interpretation, const FeedbackSource &feedback)
V< Untagged > ConvertJSPrimitiveToUntagged (V< JSPrimitive > primitive, ConvertJSPrimitiveToUntaggedOp::UntaggedKind kind, ConvertJSPrimitiveToUntaggedOp::InputAssumptions input_assumptions)
V< Untagged > ConvertJSPrimitiveToUntaggedOrDeopt (V< Object > object, V< turboshaft::FrameState > frame_state, ConvertJSPrimitiveToUntaggedOrDeoptOp::JSPrimitiveKind from_kind, ConvertJSPrimitiveToUntaggedOrDeoptOp::UntaggedKind to_kind, CheckForMinusZeroMode minus_zero_mode, const FeedbackSource &feedback)
V< Word32 > CheckedSmiUntag (V< Object > object, V< turboshaft::FrameState > frame_state, const FeedbackSource &feedback)
V< Word > TruncateJSPrimitiveToUntagged (V< JSPrimitive > object, TruncateJSPrimitiveToUntaggedOp::UntaggedKind kind, TruncateJSPrimitiveToUntaggedOp::InputAssumptions input_assumptions)
V< Word32 > TruncateNumberToInt32 (V< Number > value)
V< Word > TruncateJSPrimitiveToUntaggedOrDeopt (V< JSPrimitive > object, V< turboshaft::FrameState > frame_state, TruncateJSPrimitiveToUntaggedOrDeoptOp::UntaggedKind kind, TruncateJSPrimitiveToUntaggedOrDeoptOp::InputRequirement input_requirement, const FeedbackSource &feedback)
V< Object > ConvertJSPrimitiveToObject (V< JSPrimitive > value, V< Context > native_context, V< JSGlobalProxy > global_proxy, ConvertReceiverMode mode)
V< Word32 > Word32Constant (uint32_t value)
V< Word32 > Word32Constant (int32_t value)
V< Word64 > Word64Constant (uint64_t value)
V< Word64 > Word64Constant (int64_t value)
V< WordPtr > WordPtrConstant (uintptr_t value)
V< Word > WordConstant (uint64_t value, WordRepresentation rep)
V< WordPtr > IntPtrConstant (intptr_t value)
V< WordPtr > UintPtrConstant (uintptr_t value)
V< Smi > SmiConstant (i::Tagged< Smi > value)
V< Smi > SmiZeroConstant ()
V< Float32 > Float32Constant (i::Float32 value)
V< Float32 > Float32Constant (float value)
V< Float64 > Float64Constant (i::Float64 value)
V< Float64 > Float64Constant (double value)
OpIndex FloatConstant (double value, FloatRepresentation rep)
OpIndex NumberConstant (i::Float64 value)
OpIndex NumberConstant (double value)
OpIndex TaggedIndexConstant (int32_t value)
template<typename T >
V< T > HeapConstant (Handle< T > value) requires(is_subtype_v< T
template<typename T >
V< T > HeapConstantMaybeHole (Handle< T > value) requires(is_subtype_v< T
template<typename T >
V< T > HeapConstantNoHole (Handle< T > value) requires(is_subtype_v< T
return __ HeapConstant (value)
V< HeapObject > HeapConstantHole (Handle< HeapObject > value)
V< Code > BuiltinCode (Builtin builtin, Isolate *isolate)
OpIndex CompressedHeapConstant (Handle< HeapObject > value)
OpIndex TrustedHeapConstant (Handle< HeapObject > value)
OpIndex ExternalConstant (ExternalReference value)
OpIndex IsolateField (IsolateFieldId id)
V< WordPtr > RelocatableConstant (int64_t value, RelocInfo::Mode mode)
V< WordPtr > RelocatableWasmBuiltinCallTarget (Builtin builtin)
V< Word32 > RelocatableWasmCanonicalSignatureId (uint32_t canonical_id)
V< Word32 > RelocatableWasmIndirectCallTarget (uint32_t function_index)
V< Context > NoContextConstant ()
V< Code > CEntryStubConstant (Isolate *isolate, int result_size, ArgvMode argv_mode=ArgvMode::kStack, bool builtin_exit_frame=false)
DECL_CHANGE_V (BitcastFloat32ToWord32, kBitcast, kNoAssumption, Float32, Word32) DECL_CHANGE_V(BitcastWord32ToFloat32
Float32 DECL_CHANGE_V (BitcastFloat64ToWord64, kBitcast, kNoAssumption, Float64, Word64) DECL_CHANGE_V(BitcastWord64ToFloat64
Float32 Float64 DECL_CHANGE_V (ChangeUint32ToUint64, kZeroExtend, kNoAssumption, Word32, Word64) DECL_CHANGE_V(ChangeInt32ToFloat64
Float32 Float64 Float64 DECL_CHANGE_V (ChangeInt64ToFloat64, kSignedToFloat, kNoAssumption, Word64, Float64) DECL_CHANGE_V(ChangeInt32ToFloat32
Float32 Float64 Float64 Float32 DECL_CHANGE_V (ChangeInt64ToFloat32, kSignedToFloat, kNoAssumption, Word64, Float32) DECL_CHANGE_V(ChangeUint32ToFloat32
Float32 Float64 Float64 Float32 Float32 DECL_CHANGE_V (ChangeUint64ToFloat32, kUnsignedToFloat, kNoAssumption, Word64, Float32) DECL_CHANGE_V(ReversibleInt64ToFloat64
Float32 Float64 Float64 Float32 Float32 Float64 DECL_CHANGE_V (ChangeUint64ToFloat64, kUnsignedToFloat, kNoAssumption, Word64, Float64) DECL_CHANGE_V(ReversibleUint64ToFloat64
Float32 Float64 Float64 Float32 Float32 Float64 Float64 DECL_CHANGE_V (ChangeUint32ToFloat64, kUnsignedToFloat, kNoAssumption, Word32, Float64) DECL_CHANGE_V(ChangeIntPtrToFloat64
Float32 Float64 Float64 Float32 Float32 Float64 Float64 Float64 DECL_CHANGE_V (TruncateFloat64ToFloat32, kFloatConversion, kNoAssumption, Float64, Float32) DECL_CHANGE_V(ChangeFloat32ToFloat64
Float32 Float64 Float64 Float32 Float32 Float64 Float64 Float64 Float64 DECL_CHANGE_V (JSTruncateFloat64ToWord32, kJSFloatTruncate, kNoAssumption, Float64, Word32) DECL_CHANGE_V(TruncateWord64ToWord32
Float32 Float64 Float64 Float32 Float32 Float64 Float64 Float64 Float64 Word32 V< Word > ZeroExtendWord32ToRep (V< Word32 > value, WordRepresentation rep)
V< Word32 > TruncateWordPtrToWord32 (ConstOrV< WordPtr > input)
V< WordPtr > ChangeInt32ToIntPtr (V< Word32 > input)
V< WordPtr > ChangeUint32ToUintPtr (V< Word32 > input)
V< Word64 > ChangeIntPtrToInt64 (V< WordPtr > input)
V< Word64 > ChangeUintPtrToUint64 (V< WordPtr > input)
V< Word32 > IsSmi (V< Object > object)
DECL_CHANGE_V (TruncateFloat64ToInt64OverflowToMin, kSignedFloatTruncateOverflowToMin, kNoAssumption, Float64, Word64) DECL_CHANGE_V(TruncateFloat32ToInt32OverflowToMin
DECL_CHANGE_V (ReversibleFloat64ToInt32, kSignedFloatTruncateOverflowToMin, kReversible, Float64, Word32) DECL_CHANGE_V(ReversibleFloat64ToUint32
Word32 DECL_CHANGE_V (ReversibleFloat64ToInt64, kSignedFloatTruncateOverflowToMin, kReversible, Float64, Word64) DECL_CHANGE_V(ReversibleFloat64ToUint64
Word32 Word64 DECL_CHANGE_V (Float64ExtractLowWord32, kExtractLowHalf, kNoAssumption, Float64, Word32) DECL_CHANGE_V(Float64ExtractHighWord32
Word32 Word64 Word32 V< Untagged > ChangeOrDeopt (V< Untagged > input, V< turboshaft::FrameState > frame_state, ChangeOrDeoptOp::Kind kind, CheckForMinusZeroMode minus_zero_mode, const FeedbackSource &feedback)
V< Word32 > ChangeFloat64ToInt32OrDeopt (V< Float64 > input, V< turboshaft::FrameState > frame_state, CheckForMinusZeroMode minus_zero_mode, const FeedbackSource &feedback)
V< Word32 > ChangeFloat64ToUint32OrDeopt (V< Float64 > input, V< turboshaft::FrameState > frame_state, CheckForMinusZeroMode minus_zero_mode, const FeedbackSource &feedback)
V< Word64 > ChangeFloat64ToAdditiveSafeIntegerOrDeopt (V< Float64 > input, V< turboshaft::FrameState > frame_state, CheckForMinusZeroMode minus_zero_mode, const FeedbackSource &feedback)
V< Word64 > ChangeFloat64ToInt64OrDeopt (V< Float64 > input, V< turboshaft::FrameState > frame_state, CheckForMinusZeroMode minus_zero_mode, const FeedbackSource &feedback)
V< Smi > TagSmi (ConstOrV< Word32 > input)
V< Word32 > UntagSmi (V< Smi > input)
V< WordPtr > LoadPageFlags (V< HeapObject > object)
V< WordPtr > MemoryChunkFromAddress (V< WordPtr > address)
OpIndex AtomicRMW (V< Any > base, V< WordPtr > index, OpIndex value, AtomicRMWOp::BinOp bin_op, RegisterRepresentation in_out_rep, MemoryRepresentation memory_rep, MemoryAccessKind memory_access_kind, RegisterRepresentation base_rep)
OpIndex AtomicCompareExchange (V< Any > base, V< WordPtr > index, OpIndex expected, OpIndex new_value, RegisterRepresentation result_rep, MemoryRepresentation input_rep, MemoryAccessKind memory_access_kind, RegisterRepresentation base_rep)
OpIndex AtomicWord32Pair (V< WordPtr > base, OptionalV< WordPtr > index, OptionalV< Word32 > value_low, OptionalV< Word32 > value_high, OptionalV< Word32 > expected_low, OptionalV< Word32 > expected_high, AtomicWord32PairOp::Kind op_kind, int32_t offset)
OpIndex AtomicWord32PairLoad (V< WordPtr > base, OptionalV< WordPtr > index, int32_t offset)
OpIndex AtomicWord32PairStore (V< WordPtr > base, OptionalV< WordPtr > index, V< Word32 > value_low, V< Word32 > value_high, int32_t offset)
OpIndex AtomicWord32PairCompareExchange (V< WordPtr > base, OptionalV< WordPtr > index, V< Word32 > value_low, V< Word32 > value_high, V< Word32 > expected_low, V< Word32 > expected_high, int32_t offset=0)
OpIndex AtomicWord32PairBinop (V< WordPtr > base, OptionalV< WordPtr > index, V< Word32 > value_low, V< Word32 > value_high, AtomicRMWOp::BinOp bin_op, int32_t offset=0)
OpIndex MemoryBarrier (AtomicMemoryOrder memory_order)
OpIndex Load (OpIndex base, OptionalOpIndex index, LoadOp::Kind kind, MemoryRepresentation loaded_rep, RegisterRepresentation result_rep, int32_t offset=0, uint8_t element_size_log2=0)
OpIndex Load (OpIndex base, OptionalOpIndex index, LoadOp::Kind kind, MemoryRepresentation loaded_rep, int32_t offset=0, uint8_t element_size_log2=0)
OpIndex Load (OpIndex base, LoadOp::Kind kind, MemoryRepresentation loaded_rep, int32_t offset=0)
OpIndex LoadOffHeap (OpIndex address, MemoryRepresentation rep)
OpIndex LoadOffHeap (OpIndex address, int32_t offset, MemoryRepresentation rep)
OpIndex LoadOffHeap (OpIndex address, OptionalOpIndex index, int32_t offset, MemoryRepresentation rep)
V< Object > LoadProtectedPointerField (V< Object > base, OptionalV< WordPtr > index, LoadOp::Kind kind=LoadOp::Kind::TaggedBase(), int offset=0, int element_size_log2=kTaggedSizeLog2)
V< Object > LoadProtectedPointerField (V< Object > base, LoadOp::Kind kind, int32_t offset)
V< Object > LoadTrustedPointerField (V< HeapObject > base, OptionalV< Word32 > index, LoadOp::Kind kind, IndirectPointerTag tag, int offset=0)
V< Object > LoadTrustedPointerField (V< HeapObject > base, LoadOp::Kind kind, IndirectPointerTag tag, int offset=0)
V< WordPtr > LoadExternalPointerFromObject (V< Object > object, int offset, ExternalPointerTag tag)
V< Object > LoadFixedArrayElement (V< FixedArray > array, int index)
V< Object > LoadFixedArrayElement (V< FixedArray > array, V< WordPtr > index)
V< Float64 > LoadFixedDoubleArrayElement (V< FixedDoubleArray > array, int index)
V< Float64 > LoadFixedDoubleArrayElement (V< FixedDoubleArray > array, V< WordPtr > index)
V< Object > LoadProtectedFixedArrayElement (V< ProtectedFixedArray > array, V< WordPtr > index)
V< Object > LoadProtectedFixedArrayElement (V< ProtectedFixedArray > array, int index)
void Store (OpIndex base, OptionalOpIndex index, OpIndex value, StoreOp::Kind kind, MemoryRepresentation stored_rep, WriteBarrierKind write_barrier, int32_t offset=0, uint8_t element_size_log2=0, bool maybe_initializing_or_transitioning=false, IndirectPointerTag maybe_indirect_pointer_tag=kIndirectPointerNullTag)
void Store (OpIndex base, OpIndex value, StoreOp::Kind kind, MemoryRepresentation stored_rep, WriteBarrierKind write_barrier, int32_t offset=0, bool maybe_initializing_or_transitioning=false, IndirectPointerTag maybe_indirect_pointer_tag=kIndirectPointerNullTag)
template<typename T >
void Initialize (Uninitialized< T > &object, OpIndex value, MemoryRepresentation stored_rep, WriteBarrierKind write_barrier, int32_t offset=0)
void StoreOffHeap (OpIndex address, OpIndex value, MemoryRepresentation rep, int32_t offset=0)
void StoreOffHeap (OpIndex address, OptionalOpIndex index, OpIndex value, MemoryRepresentation rep, int32_t offset)
template<typename Rep = Any>
V< Rep > LoadField (V< Object > object, const compiler::FieldAccess &access)
template<typename Rep = Any>
V< Rep > LoadField (V< WordPtr > raw_base, const compiler::FieldAccess &access)
template<typename Obj , typename Class , typename T >
V< T > LoadField (V< Obj > object, const FieldAccessTS< Class, T > &field) requires v_traits< Class >
V< Map > LoadMapField (V< Object > object)
V< Word32 > LoadInstanceTypeField (V< Map > map)
V< Word32 > HasInstanceType (V< Object > object, InstanceType instance_type)
V< Float64 > LoadHeapNumberValue (V< HeapNumber > heap_number)
template<typename Type = Object>
V< Type > LoadTaggedField (V< Object > object, int field_offset) requires(is_subtype_v< Type
template<typename Base >
void StoreField (V< Base > object, const FieldAccess &access, V< Any > value)
template<typename Object , typename Class , typename T >
void InitializeField (Uninitialized< Object > &object, const FieldAccessTS< Class, T > &access, maybe_const_or_v_t< T > value)
template<typename T >
void InitializeField (Uninitialized< T > &object, const FieldAccess &access, V< Any > value)
template<typename Base >
void StoreFieldImpl (V< Base > object, const FieldAccess &access, V< Any > value, bool maybe_initializing_or_transitioning)
void StoreFixedArrayElement (V< FixedArray > array, int index, V< Object > value, compiler::WriteBarrierKind write_barrier)
void StoreFixedArrayElement (V< FixedArray > array, V< WordPtr > index, V< Object > value, compiler::WriteBarrierKind write_barrier)
void StoreFixedDoubleArrayElement (V< FixedDoubleArray > array, V< WordPtr > index, V< Float64 > value)
template<typename Class , typename T >
V< T > LoadElement (V< Class > object, const ElementAccessTS< Class, T > &access, V< WordPtr > index)
template<typename T = Any, typename Base >
V< T > LoadArrayBufferElement (V< Base > object, const ElementAccess &access, V< WordPtr > index)
template<typename T = Any, typename Base >
V< T > LoadNonArrayBufferElement (V< Base > object, const ElementAccess &access, V< WordPtr > index)
template<typename Base >
V< WordPtr > GetElementStartPointer (V< Base > object, const ElementAccess &access)
template<typename Base >
void StoreArrayBufferElement (V< Base > object, const ElementAccess &access, V< WordPtr > index, V< Any > value)
template<typename Base >
void StoreNonArrayBufferElement (V< Base > object, const ElementAccess &access, V< WordPtr > index, V< Any > value)
template<typename Class , typename T >
void StoreElement (V< Class > object, const ElementAccessTS< Class, T > &access, ConstOrV< WordPtr > index, V< T > value)
template<typename Class , typename T >
void InitializeElement (Uninitialized< Class > &object, const ElementAccessTS< Class, T > &access, ConstOrV< WordPtr > index, V< T > value)
template<typename Base >
void InitializeArrayBufferElement (Uninitialized< Base > &object, const ElementAccess &access, V< WordPtr > index, V< Any > value)
template<typename Base >
void InitializeNonArrayBufferElement (Uninitialized< Base > &object, const ElementAccess &access, V< WordPtr > index, V< Any > value)
V< Word32 > ArrayBufferIsDetached (V< JSArrayBufferView > object)
template<typename T = HeapObject>
Uninitialized< T > Allocate (ConstOrV< WordPtr > size, AllocationType type, AllocationAlignment alignment)
template<typename T >
V< T > FinishInitialization (Uninitialized< T > &&uninitialized)
V< HeapNumber > AllocateHeapNumberWithValue (V< Float64 > value, Factory *factory)
V< WordPtr > DecodeExternalPointer (V< Word32 > handle, ExternalPointerTag tag)
void JSStackCheck (V< Context > context, OptionalV< turboshaft::FrameState > frame_state, JSStackCheckOp::Kind kind)
void JSLoopStackCheck (V< Context > context, V< turboshaft::FrameState > frame_state)
void JSFunctionEntryStackCheck (V< Context > context, V< turboshaft::FrameState > frame_state)
void Retain (V< Object > value)
V< Word32 > StackPointerGreaterThan (V< WordPtr > limit, StackCheckKind kind)
V< Smi > StackCheckOffset ()
V< WordPtr > FramePointer ()
V< WordPtr > ParentFramePointer ()
V< WordPtr > StackSlot (int size, int alignment, bool is_tagged=false)
V< WordPtr > AdaptLocalArgument (V< Object > argument)
OpIndex LoadRootRegister ()
template<typename T = Any, typename U = T>
V< std::common_type_t< T, U > > Select (ConstOrV< Word32 > cond, V< T > vtrue, V< U > vfalse, RegisterRepresentation rep, BranchHint hint, SelectOp::Implementation implem)
OpIndex Select (ConstOrV< Word32 > cond, OpIndex vtrue, OpIndex vfalse, RegisterRepresentation rep, BranchHint hint, SelectOp::Implementation implem)
template<typename T , typename U >
V< std::common_type_t< T, U > > Conditional (ConstOrV< Word32 > cond, V< T > vtrue, V< U > vfalse, BranchHint hint=BranchHint::kNone)
void Switch (V< Word32 > input, base::Vector< SwitchOp::Case > cases, Block *default_case, BranchHint default_hint=BranchHint::kNone)
void Unreachable ()
OpIndex Parameter (int index, RegisterRepresentation rep, const char *debug_name=nullptr)
template<typename T >
V< T > Parameter (int index, const char *debug_name=nullptr)
V< Object > OsrValue (int index)
void Return (V< Word32 > pop_count, base::Vector< const OpIndex > return_values, bool spill_caller_frame_slots=false)
void Return (OpIndex result)
template<typename R = AnyOrNone>
V< R > Call (V< CallTarget > callee, OptionalV< turboshaft::FrameState > frame_state, base::Vector< const OpIndex > arguments, const TSCallDescriptor *descriptor, OpEffects effects=OpEffects().CanCallAnything())
template<typename R = AnyOrNone>
V< R > Call (V< CallTarget > callee, std::initializer_list< OpIndex > arguments, const TSCallDescriptor *descriptor, OpEffects effects=OpEffects().CanCallAnything())
template<typename Descriptor >
detail::index_type_for_t< typename Descriptor::results_t > CallBuiltin (Isolate *isolate, V< turboshaft::FrameState > frame_state, V< Context > context, const typename Descriptor::arguments_t &args, LazyDeoptOnThrow lazy_deopt_on_throw=LazyDeoptOnThrow::kNo) requires(Descriptor
template<typename Descriptor >
detail::index_type_for_t< typename Descriptor::results_t > CallBuiltin (Isolate *isolate, V< Context > context, const typename Descriptor::arguments_t &args) requires(!Descriptor
template<typename Descriptor >
detail::index_type_for_t< typename Descriptor::results_t > CallBuiltin (Isolate *isolate, V< turboshaft::FrameState > frame_state, const typename Descriptor::arguments_t &args, LazyDeoptOnThrow lazy_deopt_on_throw=LazyDeoptOnThrow::kNo) requires(Descriptor
template<typename Descriptor >
detail::index_type_for_t< typename Descriptor::results_t > CallBuiltin (Isolate *isolate, const typename Descriptor::arguments_t &args) requires(!Descriptor
V< Any > CallBuiltinImpl (Isolate *isolate, Builtin builtin, OptionalV< turboshaft::FrameState > frame_state, base::Vector< const OpIndex > arguments, const TSCallDescriptor *desc, OpEffects effects)
V< Number > CallBuiltin_ToNumber (Isolate *isolate, V< turboshaft::FrameState > frame_state, V< Context > context, V< Object > input, LazyDeoptOnThrow lazy_deopt_on_throw)
V< Numeric > CallBuiltin_ToNumeric (Isolate *isolate, V< turboshaft::FrameState > frame_state, V< Context > context, V< Object > input, LazyDeoptOnThrow lazy_deopt_on_throw)
void CallBuiltin_CheckTurbofanType (Isolate *isolate, V< Context > context, V< Object > object, V< TurbofanType > allocated_type, V< Smi > node_id)
V< Object > CallBuiltin_CopyFastSmiOrObjectElements (Isolate *isolate, V< Object > object)
void CallBuiltin_DebugPrintFloat64 (Isolate *isolate, V< Context > context, V< Float64 > value)
void CallBuiltin_DebugPrintWordPtr (Isolate *isolate, V< Context > context, V< WordPtr > value)
V< Smi > CallBuiltin_FindOrderedHashMapEntry (Isolate *isolate, V< Context > context, V< Object > table, V< Smi > key)
V< Smi > CallBuiltin_FindOrderedHashSetEntry (Isolate *isolate, V< Context > context, V< Object > set, V< Smi > key)
V< Object > CallBuiltin_GrowFastDoubleElements (Isolate *isolate, V< Object > object, V< Smi > size)
V< Object > CallBuiltin_GrowFastSmiOrObjectElements (Isolate *isolate, V< Object > object, V< Smi > size)
V< FixedArray > CallBuiltin_NewSloppyArgumentsElements (Isolate *isolate, V< WordPtr > frame, V< WordPtr > formal_parameter_count, V< Smi > arguments_count)
V< FixedArray > CallBuiltin_NewStrictArgumentsElements (Isolate *isolate, V< WordPtr > frame, V< WordPtr > formal_parameter_count, V< Smi > arguments_count)
V< FixedArray > CallBuiltin_NewRestArgumentsElements (Isolate *isolate, V< WordPtr > frame, V< WordPtr > formal_parameter_count, V< Smi > arguments_count)
V< String > CallBuiltin_NumberToString (Isolate *isolate, V< Number > input)
V< String > CallBuiltin_ToString (Isolate *isolate, V< turboshaft::FrameState > frame_state, V< Context > context, V< Object > input, LazyDeoptOnThrow lazy_deopt_on_throw)
V< Number > CallBuiltin_PlainPrimitiveToNumber (Isolate *isolate, V< PlainPrimitive > input)
V< Boolean > CallBuiltin_SameValue (Isolate *isolate, V< Object > left, V< Object > right)
V< Boolean > CallBuiltin_SameValueNumbersOnly (Isolate *isolate, V< Object > left, V< Object > right)
V< String > CallBuiltin_StringAdd_CheckNone (Isolate *isolate, V< Context > context, V< String > left, V< String > right)
V< Boolean > CallBuiltin_StringEqual (Isolate *isolate, V< String > left, V< String > right, V< WordPtr > length)
V< Boolean > CallBuiltin_StringLessThan (Isolate *isolate, V< String > left, V< String > right)
V< Boolean > CallBuiltin_StringLessThanOrEqual (Isolate *isolate, V< String > left, V< String > right)
V< Smi > CallBuiltin_StringIndexOf (Isolate *isolate, V< String > string, V< String > search, V< Smi > position)
V< String > CallBuiltin_StringFromCodePointAt (Isolate *isolate, V< String > string, V< WordPtr > index)
V< Number > CallBuiltin_StringToNumber (Isolate *isolate, V< String > input)
V< String > CallBuiltin_StringSubstring (Isolate *isolate, V< String > string, V< WordPtr > start, V< WordPtr > end)
V< Boolean > CallBuiltin_ToBoolean (Isolate *isolate, V< Object > object)
V< JSReceiver > CallBuiltin_ToObject (Isolate *isolate, V< Context > context, V< JSPrimitive > object)
void CallBuiltin_DetachContextCell (Isolate *isolate, V< turboshaft::FrameState > frame_state, V< Context > context, V< Object > new_value, ConstOrV< WordPtr > index)
V< Context > CallBuiltin_FastNewFunctionContextFunction (Isolate *isolate, V< turboshaft::FrameState > frame_state, V< Context > context, V< ScopeInfo > scope_info, ConstOrV< Word32 > slot_count, LazyDeoptOnThrow lazy_deopt_on_throw)
V< Context > CallBuiltin_FastNewFunctionContextEval (Isolate *isolate, V< turboshaft::FrameState > frame_state, V< Context > context, V< ScopeInfo > scope_info, ConstOrV< Word32 > slot_count, LazyDeoptOnThrow lazy_deopt_on_throw)
V< JSFunction > CallBuiltin_FastNewClosure (Isolate *isolate, V< turboshaft::FrameState > frame_state, V< Context > context, V< SharedFunctionInfo > shared_function_info, V< FeedbackCell > feedback_cell)
V< String > CallBuiltin_Typeof (Isolate *isolate, V< Object > object)
V< Object > CallBuiltinWithVarStackArgs (Isolate *isolate, Zone *graph_zone, Builtin builtin, V< turboshaft::FrameState > frame_state, int num_stack_args, base::Vector< OpIndex > arguments, LazyDeoptOnThrow lazy_deopt_on_throw)
V< Object > CallBuiltin_CallWithSpread (Isolate *isolate, Zone *graph_zone, V< turboshaft::FrameState > frame_state, V< Context > context, V< Object > function, int num_args_no_spread, V< Object > spread, base::Vector< V< Object >> args_no_spread, LazyDeoptOnThrow lazy_deopt_on_throw)
V< Object > CallBuiltin_CallWithArrayLike (Isolate *isolate, Zone *graph_zone, V< turboshaft::FrameState > frame_state, V< Context > context, V< Object > receiver, V< Object > function, V< Object > arguments_list, LazyDeoptOnThrow lazy_deopt_on_throw)
V< Object > CallBuiltin_CallForwardVarargs (Isolate *isolate, Zone *graph_zone, Builtin builtin, V< turboshaft::FrameState > frame_state, V< Context > context, V< JSFunction > function, int num_args, int start_index, base::Vector< V< Object >> args, LazyDeoptOnThrow lazy_deopt_on_throw)
template<typename Descriptor >
Descriptor::result_t CallRuntime (Isolate *isolate, V< turboshaft::FrameState > frame_state, V< Context > context, LazyDeoptOnThrow lazy_deopt_on_throw, const typename Descriptor::arguments_t &args) requires Descriptor
template<typename Ret , typename Args >
Ret CallRuntimeImpl (Isolate *isolate, Runtime::FunctionId function, const TSCallDescriptor *desc, V< turboshaft::FrameState > frame_state, V< Context > context, const Args &args)
void CallRuntime_Abort (Isolate *isolate, V< Context > context, V< Smi > reason)
V< BigInt > CallRuntime_BigIntUnaryOp (Isolate *isolate, V< Context > context, V< BigInt > input, ::Operation operation)
V< Number > CallRuntime_DateCurrentTime (Isolate *isolate, V< Context > context)
void CallRuntime_DebugPrint (Isolate *isolate, V< Object > object)
V< Object > CallRuntime_HandleNoHeapWritesInterrupts (Isolate *isolate, V< turboshaft::FrameState > frame_state, V< Context > context)
V< Object > CallRuntime_StackGuard (Isolate *isolate, V< Context > context)
V< Object > CallRuntime_StackGuardWithGap (Isolate *isolate, V< turboshaft::FrameState > frame_state, V< Context > context, V< Smi > gap)
V< Object > CallRuntime_StringCharCodeAt (Isolate *isolate, V< Context > context, V< String > string, V< Number > index)
V< String > CallRuntime_SymbolDescriptiveString (Isolate *isolate, V< turboshaft::FrameState > frame_state, V< Context > context, V< Symbol > symbol, LazyDeoptOnThrow lazy_deopt_on_throw)
V< Object > CallRuntime_TerminateExecution (Isolate *isolate, V< turboshaft::FrameState > frame_state, V< Context > context)
V< Object > CallRuntime_TransitionElementsKind (Isolate *isolate, V< Context > context, V< HeapObject > object, V< Map > target_map)
V< Object > CallRuntime_TryMigrateInstance (Isolate *isolate, V< Context > context, V< HeapObject > heap_object)
V< Object > CallRuntime_TryMigrateInstanceAndMarkMapAsMigrationTarget (Isolate *isolate, V< Context > context, V< HeapObject > heap_object)
void CallRuntime_ThrowAccessedUninitializedVariable (Isolate *isolate, V< turboshaft::FrameState > frame_state, V< Context > context, LazyDeoptOnThrow lazy_deopt_on_throw, V< Object > object)
void CallRuntime_ThrowConstructorReturnedNonObject (Isolate *isolate, V< turboshaft::FrameState > frame_state, V< Context > context, LazyDeoptOnThrow lazy_deopt_on_throw)
void CallRuntime_ThrowNotSuperConstructor (Isolate *isolate, V< turboshaft::FrameState > frame_state, V< Context > context, LazyDeoptOnThrow lazy_deopt_on_throw, V< Object > constructor, V< Object > function)
void CallRuntime_ThrowSuperAlreadyCalledError (Isolate *isolate, V< turboshaft::FrameState > frame_state, V< Context > context, LazyDeoptOnThrow lazy_deopt_on_throw)
void CallRuntime_ThrowSuperNotCalled (Isolate *isolate, V< turboshaft::FrameState > frame_state, V< Context > context, LazyDeoptOnThrow lazy_deopt_on_throw)
void CallRuntime_ThrowCalledNonCallable (Isolate *isolate, V< turboshaft::FrameState > frame_state, V< Context > context, LazyDeoptOnThrow lazy_deopt_on_throw, V< Object > value)
void CallRuntime_ThrowInvalidStringLength (Isolate *isolate, V< turboshaft::FrameState > frame_state, V< Context > context, LazyDeoptOnThrow lazy_deopt_on_throw)
V< JSFunction > CallRuntime_NewClosure (Isolate *isolate, V< Context > context, V< SharedFunctionInfo > shared_function_info, V< FeedbackCell > feedback_cell)
V< JSFunction > CallRuntime_NewClosure_Tenured (Isolate *isolate, V< Context > context, V< SharedFunctionInfo > shared_function_info, V< FeedbackCell > feedback_cell)
V< Boolean > CallRuntime_HasInPrototypeChain (Isolate *isolate, V< turboshaft::FrameState > frame_state, V< Context > context, LazyDeoptOnThrow lazy_deopt_on_throw, V< Object > object, V< HeapObject > prototype)
void TailCall (V< CallTarget > callee, base::Vector< const OpIndex > arguments, const TSCallDescriptor *descriptor)
V< turboshaft::FrameState > FrameState (base::Vector< const OpIndex > inputs, bool inlined, const FrameStateData *data)
void DeoptimizeIf (V< Word32 > condition, V< turboshaft::FrameState > frame_state, const DeoptimizeParameters *parameters)
void DeoptimizeIfNot (V< Word32 > condition, V< turboshaft::FrameState > frame_state, const DeoptimizeParameters *parameters)
void DeoptimizeIf (V< Word32 > condition, V< turboshaft::FrameState > frame_state, DeoptimizeReason reason, const FeedbackSource &feedback)
void DeoptimizeIfNot (V< Word32 > condition, V< turboshaft::FrameState > frame_state, DeoptimizeReason reason, const FeedbackSource &feedback)
void Deoptimize (V< turboshaft::FrameState > frame_state, const DeoptimizeParameters *parameters)
void Deoptimize (V< turboshaft::FrameState > frame_state, DeoptimizeReason reason, const FeedbackSource &feedback)
void StaticAssert (V< Word32 > condition, const char *source)
OpIndex Phi (base::Vector< const OpIndex > inputs, RegisterRepresentation rep)
OpIndex Phi (std::initializer_list< OpIndex > inputs, RegisterRepresentation rep)
template<typename T >
V< T > Phi (const base::Vector< V< T >> &inputs)
OpIndex PendingLoopPhi (OpIndex first, RegisterRepresentation rep)
template<typename T >
V< T > PendingLoopPhi (V< T > first)
V< Any > Tuple (base::Vector< const V< Any >> indices)
V< Any > Tuple (std::initializer_list< V< Any >> indices)
template<typename... Ts>
V< turboshaft::Tuple< Ts... > > Tuple (V< Ts >... indices)
V< turboshaft::Tuple< Any, Any > > Tuple (OpIndex left, OpIndex right)
V< Any > Projection (V< Any > tuple, uint16_t index, RegisterRepresentation rep)
template<uint16_t Index, typename... Ts>
auto Projection (V< turboshaft::Tuple< Ts... >> tuple)
template<uint16_t Index, typename... Ts>
auto Projection (V< turboshaft::Tuple< Ts... >> tuple, RegisterRepresentation rep)
OpIndex CheckTurboshaftTypeOf (OpIndex input, RegisterRepresentation rep, Type expected_type, bool successful)
void Dcheck (V< Word32 > condition, const char *message, const char *file, int line, const SourceLocation &loc=SourceLocation::Current())
void Check (V< Word32 > condition, const char *message, const char *file, int line, const SourceLocation &loc=SourceLocation::Current())
void FailAssert (const char *message, const std::vector< FileAndLine > &files_and_lines, const SourceLocation &loc)
void AbortCSADcheck (V< String > message)
V< Object > CatchBlockBegin ()
void Goto (Block *destination)
void Goto (Block *destination, bool is_backedge)
void Branch (V< Word32 > condition, Block *if_true, Block *if_false, BranchHint hint=BranchHint::kNone)
void Branch (ConditionWithHint condition, Block *if_true, Block *if_false)
ConditionalGotoStatus GotoIf (V< Word32 > condition, Block *if_true, BranchHint hint=BranchHint::kNone)
ConditionalGotoStatus GotoIf (ConditionWithHint condition, Block *if_true)
ConditionalGotoStatus GotoIfNot (V< Word32 > condition, Block *if_false, BranchHint hint=BranchHint::kNone)
ConditionalGotoStatus GotoIfNot (ConditionWithHint condition, Block *if_false)
OpIndex CallBuiltin (Builtin builtin, V< turboshaft::FrameState > frame_state, base::Vector< OpIndex > arguments, CanThrow can_throw, Isolate *isolate)
V< ConsString > NewConsString (V< Word32 > length, V< String > first, V< String > second)
V< AnyFixedArray > NewArray (V< WordPtr > length, NewArrayOp::Kind kind, AllocationType allocation_type)
V< FixedDoubleArray > NewDoubleArray (V< WordPtr > length, AllocationType allocation_type)
V< Number > DoubleArrayMinMax (V< JSArray > array, DoubleArrayMinMaxOp::Kind kind)
V< Number > DoubleArrayMin (V< JSArray > array)
V< Number > DoubleArrayMax (V< JSArray > array)
V< Any > LoadFieldByIndex (V< Object > object, V< Word32 > index)
void DebugBreak ()
void AssertImpl (V< Word32 > condition, const char *condition_string, const char *file, int line)
void DebugPrint (OpIndex input, RegisterRepresentation rep)
void DebugPrint (V< Object > input)
void DebugPrint (V< WordPtr > input)
void DebugPrint (V< Float64 > input)
void Comment (const char *message)
void Comment (const std::string &message)
template<typename... Args>
void CodeComment (MessageWithSourceLocation message, Args &&... args)
V< BigInt > BigIntBinop (V< BigInt > left, V< BigInt > right, V< turboshaft::FrameState > frame_state, BigIntBinopOp::Kind kind)
V< Boolean > BigIntComparison (V< BigInt > left, V< BigInt > right, BigIntComparisonOp::Kind kind)
V< BigInt > BigIntUnary (V< BigInt > input, BigIntUnaryOp::Kind kind)
V< BigInt > BigIntNegate (V< BigInt > input)
V< Word32Pair > Word32PairBinop (V< Word32 > left_low, V< Word32 > left_high, V< Word32 > right_low, V< Word32 > right_high, Word32PairBinopOp::Kind kind)
V< Word32 > StringAt (V< String > string, V< WordPtr > position, StringAtOp::Kind kind)
V< Word32 > StringCharCodeAt (V< String > string, V< WordPtr > position)
V< Word32 > StringCodePointAt (V< String > string, V< WordPtr > position)
V< Word32 > StringLength (V< String > string)
V< WordPtr > TypedArrayLength (V< JSTypedArray > typed_array, ElementsKind elements_kind)
V< Smi > StringIndexOf (V< String > string, V< String > search, V< Smi > position)
V< String > StringFromCodePointAt (V< String > string, V< WordPtr > index)
V< String > StringSubstring (V< String > string, V< Word32 > start, V< Word32 > end)
V< String > StringConcat (V< Smi > length, V< String > left, V< String > right)
V< Boolean > StringComparison (V< String > left, V< String > right, StringComparisonOp::Kind kind)
V< Boolean > StringEqual (V< String > left, V< String > right, StringComparisonOp::Kind kind=StringComparisonOp::Kind::kEqual)
V< Boolean > StringLessThan (V< String > left, V< String > right)
V< Boolean > StringLessThanOrEqual (V< String > left, V< String > right)
V< Boolean > StringOrOddballStrictEqual (V< String > left, V< String > right)
V< Smi > ArgumentsLength ()
V< Smi > RestLength (int formal_parameter_count)
V< FixedArray > NewArgumentsElements (V< Smi > arguments_count, CreateArgumentsType type, int formal_parameter_count)
OpIndex LoadTypedElement (OpIndex buffer, V< Object > base, V< WordPtr > external, V< WordPtr > index, ExternalArrayType array_type)
OpIndex LoadDataViewElement (V< Object > object, V< WordPtr > storage, V< WordPtr > index, V< Word32 > is_little_endian, ExternalArrayType element_type)
V< Object > LoadStackArgument (V< Object > base, V< WordPtr > index)
void StoreTypedElement (OpIndex buffer, V< Object > base, V< WordPtr > external, V< WordPtr > index, OpIndex value, ExternalArrayType array_type)
void StoreDataViewElement (V< Object > object, V< WordPtr > storage, V< WordPtr > index, OpIndex value, ConstOrV< Word32 > is_little_endian, ExternalArrayType element_type)
void TransitionAndStoreArrayElement (V< JSArray > array, V< WordPtr > index, V< Any > value, TransitionAndStoreArrayElementOp::Kind kind, MaybeHandle< Map > fast_map, MaybeHandle< Map > double_map)
void StoreSignedSmallElement (V< JSArray > array, V< WordPtr > index, V< Word32 > value)
V< Word32 > CompareMaps (V< HeapObject > heap_object, OptionalV< Map > map, const ZoneRefSet< Map > &maps)
void CheckMaps (V< HeapObject > heap_object, V< turboshaft::FrameState > frame_state, OptionalV< Map > map, const ZoneRefSet< Map > &maps, CheckMapsFlags flags, const FeedbackSource &feedback)
void AssumeMap (V< HeapObject > heap_object, const ZoneRefSet< Map > &maps)
V< Object > CheckedClosure (V< Object > input, V< turboshaft::FrameState > frame_state, Handle< FeedbackCell > feedback_cell)
void CheckEqualsInternalizedString (V< Object > expected, V< Object > value, V< turboshaft::FrameState > frame_state)
V< Word32 > TruncateFloat64ToFloat16RawBits (V< Float64 > input)
V< Float64 > ChangeFloat16RawBitsToFloat64 (V< Word32 > input)
V< Object > LoadMessage (V< WordPtr > offset)
void StoreMessage (V< WordPtr > offset, V< Object > object)
V< Boolean > SameValue (V< Object > left, V< Object > right, SameValueOp::Mode mode)
V< Word32 > Float64SameValue (ConstOrV< Float64 > left, ConstOrV< Float64 > right)
OpIndex FastApiCall (V< turboshaft::FrameState > frame_state, V< Object > data_argument, V< Context > context, base::Vector< const OpIndex > arguments, const FastApiCallParameters *parameters, base::Vector< const RegisterRepresentation > out_reps)
void RuntimeAbort (AbortReason reason)
V< Object > EnsureWritableFastElements (V< Object > object, V< Object > elements)
V< Object > MaybeGrowFastElements (V< Object > object, V< Object > elements, V< Word32 > index, V< Word32 > elements_length, V< turboshaft::FrameState > frame_state, GrowFastElementsMode mode, const FeedbackSource &feedback)
void TransitionElementsKind (V< HeapObject > object, const ElementsTransition &transition)
void TransitionElementsKindOrCheckMap (V< HeapObject > object, V< Map > map, V< turboshaft::FrameState > frame_state, const ElementsTransitionWithMultipleSources &transition)
OpIndex FindOrderedHashEntry (V< Object > data_structure, OpIndex key, FindOrderedHashEntryOp::Kind kind)
V< Smi > FindOrderedHashMapEntry (V< Object > table, V< Smi > key)
V< Smi > FindOrderedHashSetEntry (V< Object > table, V< Smi > key)
V< WordPtr > FindOrderedHashMapEntryForInt32Key (V< Object > table, V< Word32 > key)
V< Object > LoadRoot (RootIndex root_index)
template<typename Rep >
V< Rep > resolve (const V< Rep > &v)
V< Word32 > resolve (const ConstOrV< Word32 > &v)
V< Word64 > resolve (const ConstOrV< Word64 > &v)
V< Float32 > resolve (const ConstOrV< Float32 > &v)
V< Float64 > resolve (const ConstOrV< Float64 > &v)
Public Attributes
WordBinop
SignedMulOverflownBits
Word32 WordBinop
Word32 UnsignedMulOverflownBits
Word32 Word WordBinop
Word32 Word UnsignedMulOverflownBits
OverflowCheckedBinop
SignedAdd
Word32 OverflowCheckedBinop
Word32 SignedSub
Word32 Word OverflowCheckedBinop
Word32 Word SignedSub
Word32 Word Word64 OverflowCheckedBinop
Word32 Word Word64 SignedMul
Word32 Word Word64 Word32 V< Word32 > right
Word32 Word Word64 Word32 V< Word32 > ShiftOp::Kind kind
Word32 Word Word64 Word32 V< Word32 > ShiftOp::Kind WordRepresentation rep
ShiftRightArithmeticShiftOutZeros
Word32 ShiftRightArithmeticShiftOutZeros
Word32 WordPtr ShiftRightArithmetic
Word32 WordPtr Word32 ShiftRightArithmetic
Word32 WordPtr Word32 WordPtr uint32_t right
Word32 WordPtr Word32 WordPtr uint32_t WordRepresentation rep
Comparison
RegisterRepresentation
UnsignedLessThan Comparison
UnsignedLessThan RegisterRepresentation
UnsignedLessThan SignedLessThanOrEqual SignedLessThanOrEqual
UnsignedLessThan SignedLessThanOrEqual Word64 Comparison
UnsignedLessThan SignedLessThanOrEqual Word64 RegisterRepresentation
UnsignedLessThan SignedLessThanOrEqual Word64 UnsignedLessThanOrEqual UnsignedLessThanOrEqual
UnsignedLessThan SignedLessThanOrEqual Word64 UnsignedLessThanOrEqual Word64 Comparison
UnsignedLessThan SignedLessThanOrEqual Word64 UnsignedLessThanOrEqual Word64 RegisterRepresentation
UnsignedLessThan SignedLessThanOrEqual Word64 UnsignedLessThanOrEqual Word64 SignedLessThanOrEqual SignedLessThanOrEqual
FloatUnary
FloatRepresentation
RoundDown
Float FloatUnary
Float FloatRepresentation
Float RoundToZero
Float Float FloatUnary
Float Float RoundTiesEven
Float Float Float32 FloatUnary
Float Float Float32 FloatRepresentation
Float Float Float32 Sqrt
Float Float Float32 Float WordUnary
Float Float Float32 Float WordRepresentation
Float Float Float32 Float CountLeadingZeros
Float Float Float32 Float Word WordUnary
Float Float Float32 Float Word CountLeadingZeros
Float Float Float32 Float Word Word64 WordUnary
Float Float Float32 Float Word Word64 CountTrailingZeros
Float Float Float32 Float Word Word64 Word32 WordUnary
Float Float Float32 Float Word Word64 Word32 WordRepresentation
Float Float Float32 Float Word Word64 Word32 PopCount
Float Float Float32 Float Word Word64 Word32 Word WordUnary
Float Float Float32 Float Word Word64 Word32 Word WordRepresentation
Float Float Float32 Float Word Word64 Word32 Word SignExtend16
OverflowCheckedUnary
Abs
Word32 V< Word > right
Word32 V< Word > V< turboshaft::FrameState > frame_state
Word32 V< Word > V< turboshaft::FrameState > WordBinopDeoptOnOverflowOp::Kind kind
Word32 V< Word > V< turboshaft::FrameState > WordBinopDeoptOnOverflowOp::Kind WordRepresentation rep
Word32 V< Word > V< turboshaft::FrameState > WordBinopDeoptOnOverflowOp::Kind WordRepresentation FeedbackSource feedback
Word32 V< Word > V< turboshaft::FrameState > WordBinopDeoptOnOverflowOp::Kind WordRepresentation FeedbackSource CheckForMinusZeroMode mode
V< T > HeapObject
kBitcast
kNoAssumption
Word32
Float32 kBitcast
Float32 kNoAssumption
Float32 Word64
Float32 Float64 kSignedToFloat
Float32 Float64 kNoAssumption
Float32 Float64 Word32
Float32 Float64 Float64 kSignedToFloat
Float32 Float64 Float64 kNoAssumption
Float32 Float64 Float64 Word32
Float32 Float64 Float64 Float32 kUnsignedToFloat
Float32 Float64 Float64 Float32 kNoAssumption
Float32 Float64 Float64 Float32 Word32
Float32 Float64 Float64 Float32 Float32 kSignedToFloat
Float32 Float64 Float64 Float32 Float32 kReversible
Float32 Float64 Float64 Float32 Float32 Word64
Float32 Float64 Float64 Float32 Float32 Float64 kUnsignedToFloat
Float32 Float64 Float64 Float32 Float32 Float64 kReversible
Float32 Float64 Float64 Float32 Float32 Float64 Word64
Float32 Float64 Float64 Float32 Float32 Float64 Float64 kSignedToFloat
Float32 Float64 Float64 Float32 Float32 Float64 Float64 kNoAssumption
Float32 Float64 Float64 Float32 Float32 Float64 Float64 WordPtr
Float32 Float64 Float64 Float32 Float32 Float64 Float64 Float64 kFloatConversion
Float32 Float64 Float64 Float32 Float32 Float64 Float64 Float64 kNoAssumption
Float32 Float64 Float64 Float32 Float32 Float64 Float64 Float64 Float32
Float32 Float64 Float64 Float32 Float32 Float64 Float64 Float64 Float64 kTruncate
Float32 Float64 Float64 Float32 Float32 Float64 Float64 Float64 Float64 kNoAssumption
Float32 Float64 Float64 Float32 Float32 Float64 Float64 Float64 Float64 Word64
kSignedFloatTruncateOverflowToMin
Float32
kUnsignedFloatTruncateOverflowToMin
kReversible
Float64
Word32 kUnsignedFloatTruncateOverflowToMin
Word32 kReversible
Word32 Float64
Word32 Word64 kExtractHighHalf
Word32 Word64 kNoAssumption
Word32 Word64 Float64
V< Type > Object
Private Member Functions
template<typename T = Any, typename Base >
V< T > LoadElement (V< Base > object, const ElementAccess &access, V< WordPtr > index, bool is_array_buffer)
template<typename Base >
void StoreElement (V< Base > object, const ElementAccess &access, ConstOrV< WordPtr > index, V< Any > value, bool is_array_buffer)
ConditionalGotoStatus BranchAndBind (V< Word32 > condition, Block *if_true, Block *if_false, BranchHint hint, Block *to_bind)
Private Attributes
base::SmallVector< OpIndex, 16 > cached_parameters_
MaybeHandle< Code > cached_centry_stub_constants_ [4]
bool in_object_initialization_ = false
OperationMatcher matcher_
Detailed Description
template<typename Assembler>
class v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >
Definition at line 1521 of file assembler.h.
Member Typedef Documentation
MessageWithSourceLocation
template<typename Assembler >
using v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::MessageWithSourceLocation = CodeAssembler::MessageWithSourceLocation
Definition at line 4499 of file assembler.h.
Constructor & Destructor Documentation
TurboshaftAssemblerOpInterface()
template<typename Assembler >
template<typename... Args>
v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::TurboshaftAssemblerOpInterface (Args... args) [inline], [explicit]
Definition at line 1527 of file assembler.h.
      : GenericAssemblerOpInterface<Assembler>(args...),
        matcher_(Asm().output_graph()) {}
Member Function Documentation
AbortCSADcheck()
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::AbortCSADcheck (V< String > message) [inline]
Definition at line 4268 of file assembler.h.
                                         {
    ReduceIfReachableAbortCSADcheck(message);
  }
AdaptLocalArgument()
template<typename Assembler >
V<WordPtr> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::AdaptLocalArgument (V< Object > argument) [inline]
Definition at line 3248 of file assembler.h.
                                                    {
#ifdef V8_ENABLE_DIRECT_HANDLE
    // With direct locals, the argument can be passed directly.
    return BitcastTaggedToWordPtr(argument);
#else
    // With indirect locals, the argument has to be stored on the stack and the
    // slot address is passed.
    V<WordPtr> stack_slot =
        StackSlot(sizeof(uintptr_t), alignof(uintptr_t), true);
    StoreOffHeap(stack_slot, __ BitcastTaggedToWordPtr(argument),
                 MemoryRepresentation::UintPtr());
    return stack_slot;
#endif
  }
References __, and v8::internal::compiler::turboshaft::MemoryRepresentation::UintPtr().
Allocate()
template<typename Assembler >
template<typename T = HeapObject>
Uninitialized<T> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Allocate (ConstOrV< WordPtr > size, AllocationType type, AllocationAlignment alignment) [inline]
Definition at line 3174 of file assembler.h.
                                                           {
    static_assert(is_subtype_v<T, HeapObject>);
    DCHECK(!in_object_initialization_);
    in_object_initialization_ = true;
    return Uninitialized<T>{
        ReduceIfReachableAllocate(resolve(size), type, alignment)};
  }
References v8::internal::DCHECK(), size(), and v8::internal::tracing::type.
AllocateHeapNumberWithValue()
template<typename Assembler >
V<HeapNumber> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::AllocateHeapNumberWithValue (V< Float64 > value, Factory * factory) [inline]
Definition at line 3190 of file assembler.h.
                                                              {
    auto result = __ template Allocate<HeapNumber>(
        __ IntPtrConstant(sizeof(HeapNumber)), AllocationType::kYoung,
        kTaggedAligned);
    __ InitializeField(result, AccessBuilder::ForMap(),
                       __ HeapConstant(factory->heap_number_map()));
    __ InitializeField(result, AccessBuilder::ForHeapNumberValue(), value);
    return __ FinishInitialization(std::move(result));
  }
References __, v8::internal::compiler::IntPtrConstant(), v8::internal::kTaggedAligned, v8::internal::kYoung, v8::base::internal::result, and v8::internal::value.
ArgumentsLength()
template<typename Assembler >
V<Smi> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ArgumentsLength () [inline]
Definition at line 4629 of file assembler.h.
                           {
    return ReduceIfReachableArgumentsLength(ArgumentsLengthOp::Kind::kArguments,
                                            0);
  }
ArrayBufferIsDetached()
template<typename Assembler >
V<Word32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ArrayBufferIsDetached (V< JSArrayBufferView > object) [inline]
Definition at line 3165 of file assembler.h.
                                                               {
    V<HeapObject> buffer = __ template LoadField<HeapObject>(
        object, compiler::AccessBuilder::ForJSArrayBufferViewBuffer());
    V<Word32> bitfield = __ template LoadField<Word32>(
        buffer, compiler::AccessBuilder::ForJSArrayBufferBitField());
    return __ Word32BitwiseAnd(bitfield, JSArrayBuffer::WasDetachedBit::kMask);
  }
References __, v8::internal::compiler::AccessBuilder::ForJSArrayBufferBitField(), and v8::internal::compiler::AccessBuilder::ForJSArrayBufferViewBuffer().
AssertImpl()
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::AssertImpl (V< Word32 > condition, const char * condition_string, const char * file, int line) [inline]
Definition at line 4455 of file assembler.h.
                                              {
#ifdef DEBUG
    // We use 256 characters as a buffer size. This can be increased if
    // necessary.
    static constexpr size_t kMaxAssertCommentLength = 256;
    base::Vector<char> buffer =
        Asm().data()->compilation_zone()->template AllocateVector<char>(
            kMaxAssertCommentLength);
    int result = base::SNPrintF(buffer, "Assert: %s [%s:%d]",
                                condition_string, file, line);
    DCHECK_LT(0, result);
    Comment(buffer.data());
    IF_NOT (LIKELY(condition)) {
      Comment(buffer.data());
      Comment("ASSERT FAILED");
      DebugBreak();
    }
#endif
  }
References v8::base::Vector< T >::data(), DCHECK_LT, file(), v8::base::internal::result, and v8::base::SNPrintF().
AssumeMap()
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::AssumeMap (V< HeapObject > heap_object, const ZoneRefSet< Map > & maps) [inline]
Definition at line 4707 of file assembler.h.
                                                                         {
    ReduceIfReachableAssumeMap(heap_object, maps);
  }
AtomicCompareExchange()
template<typename Assembler >
OpIndex v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::AtomicCompareExchange (V< Any > base, V< WordPtr > index, OpIndex expected, OpIndex new_value, RegisterRepresentation result_rep, MemoryRepresentation input_rep, MemoryAccessKind memory_access_kind, RegisterRepresentation base_rep) [inline]
Definition at line 2692 of file assembler.h.
                                                                 {
    return ReduceIfReachableAtomicRMW(
        base, index, new_value, expected, AtomicRMWOp::BinOp::kCompareExchange,
        result_rep, input_rep, memory_access_kind, base_rep);
  }
References v8::internal::index.
AtomicRMW()
template<typename Assembler >
OpIndex v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::AtomicRMW (V< Any > base, V< WordPtr > index, OpIndex value, AtomicRMWOp::BinOp bin_op, RegisterRepresentation in_out_rep, MemoryRepresentation memory_rep, MemoryAccessKind memory_access_kind, RegisterRepresentation base_rep) [inline]
Definition at line 2680 of file assembler.h.
                                                     {
    DCHECK_NE(bin_op, AtomicRMWOp::BinOp::kCompareExchange);
    return ReduceIfReachableAtomicRMW(base, index, value, OpIndex::Invalid(),
                                      bin_op, in_out_rep, memory_rep,
                                      memory_access_kind, base_rep);
  }
References DCHECK_NE, v8::internal::index, v8::internal::compiler::turboshaft::OpIndex::Invalid(), and v8::internal::value.
AtomicWord32Pair()
template<typename Assembler >
OpIndex v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::AtomicWord32Pair (V< WordPtr > base, OptionalV< WordPtr > index, OptionalV< Word32 > value_low, OptionalV< Word32 > value_high, OptionalV< Word32 > expected_low, OptionalV< Word32 > expected_high, AtomicWord32PairOp::Kind op_kind, int32_t offset) [inline]
Definition at line 2703 of file assembler.h.
                                                                           {
    return ReduceIfReachableAtomicWord32Pair(base, index, value_low, value_high,
                                             expected_low, expected_high,
                                             op_kind, offset);
  }
References v8::internal::index.
AtomicWord32PairBinop()
template<typename Assembler >
OpIndex v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::AtomicWord32PairBinop (V< WordPtr > base, OptionalV< WordPtr > index, V< Word32 > value_low, V< Word32 > value_high, AtomicRMWOp::BinOp bin_op, int32_t offset = 0) [inline]
Definition at line 2733 of file assembler.h.
                                                                             {
    return AtomicWord32Pair(base, index, value_low, value_high, {}, {},
                            AtomicWord32PairOp::KindFromBinOp(bin_op), offset);
  }
References v8::internal::index, and v8::internal::compiler::turboshaft::AtomicWord32PairOp::KindFromBinOp().
AtomicWord32PairCompareExchange()
template<typename Assembler >
OpIndex v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::AtomicWord32PairCompareExchange (V< WordPtr > base, OptionalV< WordPtr > index, V< Word32 > value_low, V< Word32 > value_high, V< Word32 > expected_low, V< Word32 > expected_high, int32_t offset = 0) [inline]
Definition at line 2725 of file assembler.h.
                          {
    return AtomicWord32Pair(base, index, value_low, value_high, expected_low,
                            expected_high,
                            AtomicWord32PairOp::Kind::kCompareExchange, offset);
  }
References v8::internal::index.
AtomicWord32PairLoad()
template<typename Assembler >
OpIndex v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::AtomicWord32PairLoad (V< WordPtr > base, OptionalV< WordPtr > index, int32_t offset) [inline]
Definition at line 2714 of file assembler.h.
                                               {
    return AtomicWord32Pair(base, index, {}, {}, {}, {},
                            AtomicWord32PairOp::Kind::kLoad, offset);
  }
References v8::internal::index.
AtomicWord32PairStore()
template<typename Assembler >
OpIndex v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::AtomicWord32PairStore (V< WordPtr > base, OptionalV< WordPtr > index, V< Word32 > value_low, V< Word32 > value_high, int32_t offset) [inline]
Definition at line 2719 of file assembler.h.
                                                {
    return AtomicWord32Pair(base, index, value_low, value_high, {}, {},
                            AtomicWord32PairOp::Kind::kStore, offset);
  }
References v8::internal::index.
BigIntBinop()
template<typename Assembler >
V<BigInt> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::BigIntBinop (V< BigInt > left, V< BigInt > right, V< turboshaft::FrameState > frame_state, BigIntBinopOp::Kind kind) [inline]
Definition at line 4511 of file assembler.h.
                                                {
    return ReduceIfReachableBigIntBinop(left, right, frame_state, kind);
  }
BigIntComparison()
template<typename Assembler >
V<Boolean> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::BigIntComparison (V< BigInt > left, V< BigInt > right, BigIntComparisonOp::Kind kind) [inline]
Definition at line 4534 of file assembler.h.
                                                           {
    return ReduceIfReachableBigIntComparison(left, right, kind);
  }
BigIntNegate()
template<typename Assembler >
V<BigInt> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::BigIntNegate (V< BigInt > input) [inline]
Definition at line 4550 of file assembler.h.
                                          {
    return BigIntUnary(input, BigIntUnaryOp::Kind::kNegate);
  }
BigIntUnary()
template<typename Assembler >
V<BigInt> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::BigIntUnary (V< BigInt > input, BigIntUnaryOp::Kind kind) [inline]
Definition at line 4547 of file assembler.h.
                                                                 {
    return ReduceIfReachableBigIntUnary(input, kind);
  }
BitcastTaggedToWordPtr()
template<typename Assembler >
V<WordPtr> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::BitcastTaggedToWordPtr (V< Object > input) [inline]
Definition at line 2073 of file assembler.h.
                                                     {
    return TaggedBitcast(input, V<Object>::rep, V<WordPtr>::rep,
                         TaggedBitcastOp::Kind::kAny);
  }
BitcastTaggedToWordPtrForTagAndSmiBits()
template<typename Assembler >
V<WordPtr> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::BitcastTaggedToWordPtrForTagAndSmiBits (V< Object > input) [inline]
Definition at line 2078 of file assembler.h.
                                                                     {
    return TaggedBitcast(input, RegisterRepresentation::Tagged(),
                         RegisterRepresentation::WordPtr(),
                         TaggedBitcastOp::Kind::kTagAndSmiBits);
  }
References v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), and v8::internal::compiler::turboshaft::RegisterRepresentation::WordPtr().
BitcastWord32PairToFloat64()
template<typename Assembler >
V<Float64> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::BitcastWord32PairToFloat64 (ConstOrV< Word32 > high_word32, ConstOrV< Word32 > low_word32) [inline]
Definition at line 2045 of file assembler.h.
                                                                     {
    return ReduceIfReachableBitcastWord32PairToFloat64(resolve(high_word32),
                                                       resolve(low_word32));
  }
BitcastWordPtrToTagged()
template<typename Assembler >
V<Object> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::BitcastWordPtrToTagged (V< WordPtr > input) [inline]
Definition at line 2068 of file assembler.h.
                                                     {
    return TaggedBitcast(input, V<WordPtr>::rep, V<Object>::rep,
                         TaggedBitcastOp::Kind::kAny);
  }
Branch() [1/2]
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Branch (ConditionWithHint condition, Block * if_true, Block * if_false) [inline]
Definition at line 4367 of file assembler.h.
                                                                            {
    return Branch(condition.condition(), if_true, if_false, condition.hint());
  }
References v8::internal::compiler::turboshaft::ConditionWithHint::condition(), and v8::internal::compiler::turboshaft::ConditionWithHint::hint().
Branch() [2/2]
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Branch (V< Word32 > condition, Block * if_true, Block * if_false, BranchHint hint = BranchHint::kNone) [inline]
Definition at line 4363 of file assembler.h.
                                                 {
    ReduceIfReachableBranch(condition, if_true, if_false, hint);
  }
BranchAndBind()
template<typename Assembler >
ConditionalGotoStatus v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::BranchAndBind (V< Word32 > condition, Block * if_true, Block * if_false, BranchHint hint, Block * to_bind) [inline], [private]
Definition at line 5304 of file assembler.h.
                                                      {
    DCHECK_EQ(to_bind, any_of(if_true, if_false));
    Block* other = to_bind == if_true ? if_false : if_true;
    Block* to_bind_last_pred = to_bind->LastPredecessor();
    Block* other_last_pred = other->LastPredecessor();
    Asm().Branch(condition, if_true, if_false, hint);
    bool to_bind_reachable = to_bind_last_pred != to_bind->LastPredecessor();
    bool other_reachable = other_last_pred != other->LastPredecessor();
    ConditionalGotoStatus status = static_cast<ConditionalGotoStatus>(
        static_cast<int>(other_reachable) | ((to_bind_reachable) << 1));
    bool bind_status = Asm().Bind(to_bind);
    DCHECK_EQ(bind_status, to_bind_reachable);
    USE(bind_status);
    return status;
  }
References v8::base::any_of(), DCHECK_EQ, v8::internal::compiler::turboshaft::Block::LastPredecessor(), v8::internal::status, and USE.
BuiltinCode()
template<typename Assembler >
V<Code> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::BuiltinCode (Builtin builtin, Isolate * isolate) [inline]
Definition at line 2371 of file assembler.h.
                                                         {
    return HeapConstant(BuiltinCodeHandle(builtin, isolate));
  }
References v8::internal::compiler::turboshaft::BuiltinCodeHandle().
Call() [1/2]
template<typename Assembler >
template<typename R = AnyOrNone>
V<R> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Call (V< CallTarget > callee, OptionalV< turboshaft::FrameState > frame_state, base::Vector< const OpIndex > arguments, const TSCallDescriptor * descriptor, OpEffects effects = OpEffects().CanCallAnything()) [inline]
Definition at line 3345 of file assembler.h.
                                                               {
    return ReduceIfReachableCall(callee, frame_state, arguments, descriptor,
                                 effects);
  }
Call() [2/2]
template<typename Assembler >
template<typename R = AnyOrNone>
V<R> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Call (V< CallTarget > callee, std::initializer_list< OpIndex > arguments, const TSCallDescriptor * descriptor, OpEffects effects = OpEffects().CanCallAnything()) [inline]
Definition at line 3353 of file assembler.h.
                                                               {
    return Call<R>(callee, OptionalV<turboshaft::FrameState>::Nullopt(),
                   base::VectorOf(arguments), descriptor, effects);
  }
References v8::base::VectorOf().
CallBuiltin() [1/5]
template<typename Assembler >
OpIndex v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin (Builtin builtin, V< turboshaft::FrameState > frame_state, base::Vector< OpIndex > arguments, CanThrow can_throw, Isolate * isolate) [inline]
Definition at line 4400 of file assembler.h.
                                        {
    if (V8_UNLIKELY(Asm().generating_unreachable_operations())) {
      return OpIndex::Invalid();
    }
    Callable const callable = Builtins::CallableFor(isolate, builtin);
    Zone* graph_zone = Asm().output_graph().graph_zone();
    const CallDescriptor* call_descriptor = Linkage::GetStubCallDescriptor(
        graph_zone, callable.descriptor(),
        callable.descriptor().GetStackParameterCount(),
        CallDescriptor::kNoFlags, Operator::kNoThrow | Operator::kNoDeopt);
    DCHECK_EQ(call_descriptor->NeedsFrameState(), frame_state.valid());
    const TSCallDescriptor* ts_call_descriptor = TSCallDescriptor::Create(
        call_descriptor, can_throw, LazyDeoptOnThrow::kNo, graph_zone);
    OpIndex callee = Asm().HeapConstant(callable.code());
    return Asm().Call(callee, frame_state, arguments, ts_call_descriptor);
  }
References v8::internal::Builtins::CallableFor(), v8::internal::Callable::code(), v8::internal::compiler::turboshaft::TSCallDescriptor::Create(), DCHECK_EQ, v8::internal::Callable::descriptor(), v8::internal::CallInterfaceDescriptor::GetStackParameterCount(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::CallDescriptor::NeedsFrameState(), V8_UNLIKELY, and v8::internal::compiler::turboshaft::OpIndex::valid().
CallBuiltin() [2/5]
template<typename Assembler >
template<typename Descriptor >
detail::index_type_for_t<typename Descriptor::results_t> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin (Isolate * isolate, const typename Descriptor::arguments_t & args) [inline]
Definition at line 3440 of file assembler.h.
  {
    using result_t = detail::index_type_for_t<typename Descriptor::results_t>;
    if (V8_UNLIKELY(Asm().generating_unreachable_operations())) {
      return result_t::Invalid();
    }
    auto arguments = std::apply(
        [](auto&&... as) {
          return base::SmallVector<
              OpIndex, std::tuple_size_v<typename Descriptor::arguments_t>>{
              std::forward<decltype(as)>(as)...};
        },
        args);
    return result_t::Cast(CallBuiltinImpl(
        isolate, Descriptor::kFunction,
        OptionalV<turboshaft::FrameState>::Nullopt(), base::VectorOf(arguments),
        Descriptor::Create(StubCallMode::kCallCodeObject,
                           Asm().output_graph().graph_zone()),
        Descriptor::kEffects));
  }
References v8::base::args, v8::internal::Cast(), v8::internal::kCallCodeObject, v8::internal::torque::ls::kFunction, v8::internal::compiler::turboshaft::OpIndex, V8_UNLIKELY, and v8::base::VectorOf().
CallBuiltin() [3/5]
template<typename Assembler >
template<typename Descriptor >
detail::index_type_for_t<typename Descriptor::results_t> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin (Isolate * isolate, V< Context > context, const typename Descriptor::arguments_t & args) [inline]
Definition at line 3389 of file assembler.h.
  {
    using result_t = detail::index_type_for_t<typename Descriptor::results_t>;
    if (V8_UNLIKELY(Asm().generating_unreachable_operations())) {
      return result_t::Invalid();
    }
    DCHECK(context.valid());
    auto arguments = std::apply(
        [context](auto&&... as) {
          return base::SmallVector<
              OpIndex, std::tuple_size_v<typename Descriptor::arguments_t> + 1>{
              std::forward<decltype(as)>(as)..., context};
        },
        args);
    return result_t::Cast(CallBuiltinImpl(
        isolate, Descriptor::kFunction,
        OptionalV<turboshaft::FrameState>::Nullopt(), base::VectorOf(arguments),
        Descriptor::Create(StubCallMode::kCallCodeObject,
                           Asm().output_graph().graph_zone()),
        Descriptor::kEffects));
  }
References v8::base::args, v8::internal::Cast(), v8::internal::DCHECK(), v8::internal::kCallCodeObject, v8::internal::torque::ls::kFunction, v8::internal::compiler::turboshaft::OpIndex, V8_UNLIKELY, and v8::base::VectorOf().
CallBuiltin() [4/5]
template<typename Assembler >
template<typename Descriptor >
detail::index_type_for_t<typename Descriptor::results_t> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin (Isolate * isolate, V< turboshaft::FrameState > frame_state, const typename Descriptor::arguments_t & args, LazyDeoptOnThrow lazy_deopt_on_throw = LazyDeoptOnThrow::kNo) [inline]
Definition at line 3414 of file assembler.h.
  {
    using result_t = detail::index_type_for_t<typename Descriptor::results_t>;
    if (V8_UNLIKELY(Asm().generating_unreachable_operations())) {
      return result_t::Invalid();
    }
    DCHECK(frame_state.valid());
    auto arguments = std::apply(
        [](auto&&... as) {
          return base::SmallVector<
              OpIndex, std::tuple_size_v<typename Descriptor::arguments_t>>{
              std::forward<decltype(as)>(as)...};
        },
        args);
    return result_t::Cast(CallBuiltinImpl(
        isolate, Descriptor::kFunction, frame_state, base::VectorOf(arguments),
        Descriptor::Create(StubCallMode::kCallCodeObject,
                           Asm().output_graph().graph_zone(),
                           lazy_deopt_on_throw),
        Descriptor::kEffects));
  }
References v8::base::args, v8::internal::Cast(), v8::internal::DCHECK(), v8::internal::kCallCodeObject, v8::internal::torque::ls::kFunction, v8::internal::compiler::turboshaft::OpIndex, V8_UNLIKELY, v8::internal::compiler::turboshaft::OptionalOpIndex::valid(), and v8::base::VectorOf().
CallBuiltin() [5/5]
template<typename Assembler >
template<typename Descriptor >
detail::index_type_for_t<typename Descriptor::results_t> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin (Isolate * isolate, V< turboshaft::FrameState > frame_state, V< Context > context, const typename Descriptor::arguments_t & args, LazyDeoptOnThrow lazy_deopt_on_throw = LazyDeoptOnThrow::kNo) [inline]
Definition at line 3361 of file assembler.h.
  {
    using result_t = detail::index_type_for_t<typename Descriptor::results_t>;
    if (V8_UNLIKELY(Asm().generating_unreachable_operations())) {
      return result_t::Invalid();
    }
    DCHECK(frame_state.valid());
    DCHECK(context.valid());
    auto arguments = std::apply(
        [context](auto&&... as) {
          return base::SmallVector<
              OpIndex, std::tuple_size_v<typename Descriptor::arguments_t> + 1>{
              std::forward<decltype(as)>(as)..., context};
        },
        args);
    return result_t::Cast(CallBuiltinImpl(
        isolate, Descriptor::kFunction, frame_state, base::VectorOf(arguments),
        Descriptor::Create(StubCallMode::kCallCodeObject,
                           Asm().output_graph().graph_zone(),
                           lazy_deopt_on_throw),
        Descriptor::kEffects));
  }
References v8::base::args, v8::internal::Cast(), v8::internal::DCHECK(), v8::internal::kCallCodeObject, v8::internal::torque::ls::kFunction, v8::internal::compiler::turboshaft::OpIndex, V8_UNLIKELY, v8::internal::compiler::turboshaft::OptionalOpIndex::valid(), and v8::base::VectorOf().
CallBuiltin_CallForwardVarargs()
template<typename Assembler >
V<Object> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_CallForwardVarargs (Isolate * isolate, Zone * graph_zone, Builtin builtin, V< turboshaft::FrameState > frame_state, V< Context > context, V< JSFunction > function, int num_args, int start_index, base::Vector< V< Object >> args, LazyDeoptOnThrow lazy_deopt_on_throw) [inline]
Definition at line 3812 of file assembler.h.
                                                                        {
    DCHECK(builtin == Builtin::kCallFunctionForwardVarargs ||
           builtin == Builtin::kCallForwardVarargs);
    base::SmallVector<OpIndex, 16> arguments;
    arguments.push_back(function);
    arguments.push_back(__ Word32Constant(num_args));
    arguments.push_back(__ Word32Constant(start_index));
    arguments.insert(arguments.end(), args.begin(), args.end());
    arguments.push_back(context);
    return CallBuiltinWithVarStackArgs(
        isolate, graph_zone, builtin, frame_state, num_args,
        base::VectorOf(arguments), lazy_deopt_on_throw);
  }
References __, v8::base::args, v8::internal::DCHECK(), v8::base::SmallVector< T, kSize, Allocator >::end(), v8::base::SmallVector< T, kSize, Allocator >::insert(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), and v8::base::VectorOf().
CallBuiltin_CallWithArrayLike()
template<typename Assembler >
V<Object> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_CallWithArrayLike (Isolate * isolate, Zone * graph_zone, V< turboshaft::FrameState > frame_state, V< Context > context, V< Object > receiver, V< Object > function, V< Object > arguments_list, LazyDeoptOnThrow lazy_deopt_on_throw) [inline]
Definition at line 3796 of file assembler.h.
                                                                      {
    // CallWithArrayLike is a weird builtin that expects a receiver as top of
    // the stack, but doesn't explicitly list it as an extra argument. We thus
    // manually create the call descriptor with 1 stack argument.
    constexpr int kNumberOfStackArguments = 1;
    OpIndex arguments[] = {function, arguments_list, receiver, context};
    return CallBuiltinWithVarStackArgs(
        isolate, graph_zone, Builtin::kCallWithArrayLike, frame_state,
        kNumberOfStackArguments, base::VectorOf(arguments),
        lazy_deopt_on_throw);
  }
References v8::base::VectorOf().
CallBuiltin_CallWithSpread()
template<typename Assembler >
V<Object> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_CallWithSpread (Isolate * isolate, Zone * graph_zone, V< turboshaft::FrameState > frame_state, V< Context > context, V< Object > function, int num_args_no_spread, V< Object > spread, base::Vector< V< Object >> args_no_spread, LazyDeoptOnThrow lazy_deopt_on_throw) [inline]
Definition at line 3777 of file assembler.h.
                                                                             {
    base::SmallVector<OpIndex, 16> arguments;
    arguments.push_back(function);
    arguments.push_back(Word32Constant(num_args_no_spread));
    arguments.push_back(spread);
    arguments.insert(arguments.end(), args_no_spread.begin(),
                     args_no_spread.end());
    arguments.push_back(context);
    return CallBuiltinWithVarStackArgs(
        isolate, graph_zone, Builtin::kCallWithSpread, frame_state,
        num_args_no_spread, base::VectorOf(arguments), lazy_deopt_on_throw);
  }
References v8::base::SmallVector< T, kSize, Allocator >::end(), v8::base::SmallVector< T, kSize, Allocator >::insert(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), and v8::base::VectorOf().
CallBuiltin_CheckTurbofanType()
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_CheckTurbofanType (Isolate * isolate, V< Context > context, V< Object > object, V< TurbofanType > allocated_type, V< Smi > node_id) [inline]
Definition at line 3569 of file assembler.h.
                                                     {
    CallBuiltin<typename BuiltinCallDescriptor::CheckTurbofanType>(
        isolate, context, {object, allocated_type, node_id});
  }
CallBuiltin_CopyFastSmiOrObjectElements()
template<typename Assembler >
V<Object> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_CopyFastSmiOrObjectElements (Isolate * isolate, V< Object > object) [inline]
Definition at line 3576 of file assembler.h.
                                                                      {
    return CallBuiltin<
        typename BuiltinCallDescriptor::CopyFastSmiOrObjectElements>(isolate,
                                                                     {object});
  }
CallBuiltin_DebugPrintFloat64()
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_DebugPrintFloat64 (Isolate * isolate, V< Context > context, V< Float64 > value) [inline]
Definition at line 3582 of file assembler.h.
                                                       {
    CallBuiltin<typename BuiltinCallDescriptor::DebugPrintFloat64>(
        isolate, context, {value});
  }
References v8::internal::value.
CallBuiltin_DebugPrintWordPtr()
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_DebugPrintWordPtr (Isolate * isolate, V< Context > context, V< WordPtr > value) [inline]
Definition at line 3587 of file assembler.h.
                                                       {
    CallBuiltin<typename BuiltinCallDescriptor::DebugPrintWordPtr>(
        isolate, context, {value});
  }
References v8::internal::value.
CallBuiltin_DetachContextCell()
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_DetachContextCell (Isolate * isolate, V< turboshaft::FrameState > frame_state, V< Context > context, V< Object > new_value, ConstOrV< WordPtr > index) [inline]
Definition at line 3721 of file assembler.h.
                                                              {
    CallBuiltin<typename BuiltinCallDescriptor::DetachContextCell>(
        isolate, frame_state, {context, new_value, resolve(index)});
  }
References v8::internal::index.
CallBuiltin_FastNewClosure()
template<typename Assembler >
V<JSFunction> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_FastNewClosure (Isolate * isolate, V< turboshaft::FrameState > frame_state, V< Context > context, V< SharedFunctionInfo > shared_function_info, V< FeedbackCell > feedback_cell) [inline]
Definition at line 3746 of file assembler.h.
                                     {
    return CallBuiltin<typename BuiltinCallDescriptor::FastNewClosure>(
        isolate, frame_state, context, {shared_function_info, feedback_cell});
  }
CallBuiltin_FastNewFunctionContextEval()
template<typename Assembler >
V<Context> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_FastNewFunctionContextEval (Isolate * isolate, V< turboshaft::FrameState > frame_state, V< Context > context, V< ScopeInfo > scope_info, ConstOrV< Word32 > slot_count, LazyDeoptOnThrow lazy_deopt_on_throw) [inline]
Definition at line 3737 of file assembler.h.
                                            {
    return CallBuiltin<
        typename BuiltinCallDescriptor::FastNewFunctionContextEval>(
        isolate, frame_state, context, {scope_info, resolve(slot_count)},
        lazy_deopt_on_throw);
  }
CallBuiltin_FastNewFunctionContextFunction()
template<typename Assembler >
V<Context> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_FastNewFunctionContextFunction (Isolate * isolate, V< turboshaft::FrameState > frame_state, V< Context > context, V< ScopeInfo > scope_info, ConstOrV< Word32 > slot_count, LazyDeoptOnThrow lazy_deopt_on_throw) [inline]
Definition at line 3728 of file assembler.h.
                                            {
    return CallBuiltin<
        typename BuiltinCallDescriptor::FastNewFunctionContextFunction>(
        isolate, frame_state, context, {scope_info, resolve(slot_count)},
        lazy_deopt_on_throw);
  }
CallBuiltin_FindOrderedHashMapEntry()
template<typename Assembler >
V<Smi> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_FindOrderedHashMapEntry (Isolate * isolate, V< Context > context, V< Object > table, V< Smi > key) [inline]
Definition at line 3592 of file assembler.h.
                                                                          {
    return CallBuiltin<typename BuiltinCallDescriptor::FindOrderedHashMapEntry>(
        isolate, context, {table, key});
  }
References v8::internal::key.
CallBuiltin_FindOrderedHashSetEntry()
template<typename Assembler >
V<Smi> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_FindOrderedHashSetEntry (Isolate * isolate, V< Context > context, V< Object > set, V< Smi > key) [inline]
Definition at line 3598 of file assembler.h.
                                                         {
    return CallBuiltin<typename BuiltinCallDescriptor::FindOrderedHashSetEntry>(
        isolate, context, {set, key});
  }
References v8::internal::key.
CallBuiltin_GrowFastDoubleElements()
template<typename Assembler >
V<Object> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_GrowFastDoubleElements (Isolate * isolate, V< Object > object, V< Smi > size) [inline]
Definition at line 3604 of file assembler.h.
                                                                              {
    return CallBuiltin<typename BuiltinCallDescriptor::GrowFastDoubleElements>(
        isolate, {object, size});
  }
References size().
CallBuiltin_GrowFastSmiOrObjectElements()
template<typename Assembler >
V<Object> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_GrowFastSmiOrObjectElements (Isolate * isolate, V< Object > object, V< Smi > size) [inline]
Definition at line 3609 of file assembler.h.
                                                                 {
    return CallBuiltin<
        typename BuiltinCallDescriptor::GrowFastSmiOrObjectElements>(
        isolate, {object, size});
  }
References size().
CallBuiltin_NewRestArgumentsElements()
template<typename Assembler >
V<FixedArray> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_NewRestArgumentsElements (Isolate * isolate, V< WordPtr > frame, V< WordPtr > formal_parameter_count, V< Smi > arguments_count) [inline]
Definition at line 3630 of file assembler.h.
                              {
    return CallBuiltin<
        typename BuiltinCallDescriptor::NewRestArgumentsElements>(
        isolate, {frame, formal_parameter_count, arguments_count});
  }
CallBuiltin_NewSloppyArgumentsElements()
template<typename Assembler >
V<FixedArray> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_NewSloppyArgumentsElements (Isolate * isolate, V< WordPtr > frame, V< WordPtr > formal_parameter_count, V< Smi > arguments_count) [inline]
Definition at line 3616 of file assembler.h.
                              {
    return CallBuiltin<
        typename BuiltinCallDescriptor::NewSloppyArgumentsElements>(
        isolate, {frame, formal_parameter_count, arguments_count});
  }
CallBuiltin_NewStrictArgumentsElements()
template<typename Assembler >
V<FixedArray> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_NewStrictArgumentsElements (Isolate * isolate, V< WordPtr > frame, V< WordPtr > formal_parameter_count, V< Smi > arguments_count) [inline]
Definition at line 3623 of file assembler.h.
                              {
    return CallBuiltin<
        typename BuiltinCallDescriptor::NewStrictArgumentsElements>(
        isolate, {frame, formal_parameter_count, arguments_count});
  }
CallBuiltin_NumberToString()
template<typename Assembler >
V<String> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_NumberToString (Isolate * isolate, V< Number > input) [inline]
Definition at line 3637 of file assembler.h.
                                                                          {
    return CallBuiltin<typename BuiltinCallDescriptor::NumberToString>(isolate,
                                                                       {input});
  }
CallBuiltin_PlainPrimitiveToNumber()
template<typename Assembler >
V<Number> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_PlainPrimitiveToNumber (Isolate * isolate, V< PlainPrimitive > input) [inline]
Definition at line 3648 of file assembler.h.
                                                                        {
    return CallBuiltin<typename BuiltinCallDescriptor::PlainPrimitiveToNumber>(
        isolate, {input});
  }
CallBuiltin_SameValue()
template<typename Assembler >
V<Boolean> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_SameValue (Isolate * isolate, V< Object > left, V< Object > right) [inline]
Definition at line 3653 of file assembler.h.
                                                    {
    return CallBuiltin<typename BuiltinCallDescriptor::SameValue>(
        isolate, {left, right});
  }
CallBuiltin_SameValueNumbersOnly()
template<typename Assembler >
V<Boolean> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_SameValueNumbersOnly (Isolate * isolate, V< Object > left, V< Object > right) [inline]
Definition at line 3658 of file assembler.h.
                                                               {
    return CallBuiltin<typename BuiltinCallDescriptor::SameValueNumbersOnly>(
        isolate, {left, right});
  }
CallBuiltin_StringAdd_CheckNone()
template<typename Assembler >
V<String> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_StringAdd_CheckNone (Isolate * isolate, V< Context > context, V< String > left, V< String > right) [inline]
Definition at line 3663 of file assembler.h.
                                                             {
    return CallBuiltin<typename BuiltinCallDescriptor::StringAdd_CheckNone>(
        isolate, context, {left, right});
  }
CallBuiltin_StringEqual()
template<typename Assembler >
V<Boolean> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_StringEqual (Isolate * isolate, V< String > left, V< String > right, V< WordPtr > length) [inline]
Definition at line 3669 of file assembler.h.
                                                                         {
    return CallBuiltin<typename BuiltinCallDescriptor::StringEqual>(
        isolate, {left, right, length});
  }
References v8::internal::length.
CallBuiltin_StringFromCodePointAt()
template<typename Assembler >
V<String> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_StringFromCodePointAt (Isolate * isolate, V< String > string, V< WordPtr > index) [inline]
Definition at line 3689 of file assembler.h.
                                                                {
    return CallBuiltin<typename BuiltinCallDescriptor::StringFromCodePointAt>(
        isolate, {string, index});
  }
References v8::internal::index, and v8::internal::string.
CallBuiltin_StringIndexOf()
template<typename Assembler >
V<Smi> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_StringIndexOf (Isolate * isolate, V< String > string, V< String > search, V< Smi > position) [inline]
Definition at line 3684 of file assembler.h.
                                                                      {
    return CallBuiltin<typename BuiltinCallDescriptor::StringIndexOf>(
        isolate, {string, search, position});
  }
References v8::internal::anonymous_namespace{simd.cc}::search(), and v8::internal::string.
CallBuiltin_StringLessThan()
template<typename Assembler >
V<Boolean> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_StringLessThan (Isolate * isolate, V< String > left, V< String > right) [inline]
Definition at line 3674 of file assembler.h.
                                                         {
    return CallBuiltin<typename BuiltinCallDescriptor::StringLessThan>(
        isolate, {left, right});
  }
CallBuiltin_StringLessThanOrEqual()
template<typename Assembler >
V<Boolean> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_StringLessThanOrEqual (Isolate * isolate, V< String > left, V< String > right) [inline]
Definition at line 3679 of file assembler.h.
                                                                {
    return CallBuiltin<typename BuiltinCallDescriptor::StringLessThanOrEqual>(
        isolate, {left, right});
  }
CallBuiltin_StringSubstring()
template<typename Assembler >
V<String> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_StringSubstring (Isolate * isolate, V< String > string, V< WordPtr > start, V< WordPtr > end) [inline]
Definition at line 3707 of file assembler.h.
                                                                          {
    return CallBuiltin<typename BuiltinCallDescriptor::StringSubstring>(
        isolate, {string, start, end});
  }
References v8::internal::compiler::end(), and v8::internal::string.
CallBuiltin_StringToNumber()
template<typename Assembler >
V<Number> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_StringToNumber (Isolate * isolate, V< String > input) [inline]
Definition at line 3703 of file assembler.h.
                                                                          {
    return CallBuiltin<typename BuiltinCallDescriptor::StringToNumber>(isolate,
                                                                       {input});
  }
CallBuiltin_ToBoolean()
template<typename Assembler >
V<Boolean> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_ToBoolean (Isolate * isolate, V< Object > object) [inline]
Definition at line 3712 of file assembler.h.
                                                                       {
    return CallBuiltin<typename BuiltinCallDescriptor::ToBoolean>(isolate,
                                                                  {object});
  }
CallBuiltin_ToNumber()
template<typename Assembler >
V<Number> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_ToNumber (Isolate * isolate, V< turboshaft::FrameState > frame_state, V< Context > context, V< Object > input, LazyDeoptOnThrow lazy_deopt_on_throw) [inline]
Definition at line 3554 of file assembler.h.
                                                                       {
    return CallBuiltin<typename BuiltinCallDescriptor::ToNumber>(
        isolate, frame_state, context, {input}, lazy_deopt_on_throw);
  }
CallBuiltin_ToNumeric()
template<typename Assembler >
V<Numeric> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_ToNumeric (Isolate * isolate, V< turboshaft::FrameState > frame_state, V< Context > context, V< Object > input, LazyDeoptOnThrow lazy_deopt_on_throw) [inline]
Definition at line 3561 of file assembler.h.
                                                                         {
    return CallBuiltin<typename BuiltinCallDescriptor::ToNumeric>(
        isolate, frame_state, context, {input}, lazy_deopt_on_throw);
  }
CallBuiltin_ToObject()
template<typename Assembler >
V<JSReceiver> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_ToObject (Isolate * isolate, V< Context > context, V< JSPrimitive > object) [inline]
Definition at line 3716 of file assembler.h.
                                                            {
    return CallBuiltin<typename BuiltinCallDescriptor::ToObject>(
        isolate, context, {object});
  }
CallBuiltin_ToString()
template<typename Assembler >
V<String> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_ToString (Isolate * isolate, V< turboshaft::FrameState > frame_state, V< Context > context, V< Object > input, LazyDeoptOnThrow lazy_deopt_on_throw) [inline]
Definition at line 3641 of file assembler.h.
                                                                       {
    return CallBuiltin<typename BuiltinCallDescriptor::ToString>(
        isolate, frame_state, context, {input}, lazy_deopt_on_throw);
  }
CallBuiltin_Typeof()
template<typename Assembler >
V<String> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin_Typeof (Isolate * isolate, V< Object > object) [inline]
Definition at line 3753 of file assembler.h.
                                                                   {
    return CallBuiltin<typename BuiltinCallDescriptor::Typeof>(isolate,
                                                               {object});
  }
CallBuiltinImpl()
template<typename Assembler >
V<Any> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltinImpl (Isolate * isolate, Builtin builtin, OptionalV< turboshaft::FrameState > frame_state, base::Vector< const OpIndex > arguments, const TSCallDescriptor * desc, OpEffects effects) [inline]
Definition at line 3523 of file assembler.h.
                                                                          {
    Callable callable = Builtins::CallableFor(isolate, builtin);
    return Call(HeapConstant(callable.code()), frame_state, arguments, desc,
                effects);
  }
References v8::internal::Builtins::CallableFor(), and v8::internal::Callable::code().
CallBuiltinWithVarStackArgs()
template<typename Assembler >
V<Object> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltinWithVarStackArgs (Isolate * isolate, Zone * graph_zone, Builtin builtin, V< turboshaft::FrameState > frame_state, int num_stack_args, base::Vector< OpIndex > arguments, LazyDeoptOnThrow lazy_deopt_on_throw) [inline]
Definition at line 3758 of file assembler.h.
                                                                              {
    Callable callable = Builtins::CallableFor(isolate, builtin);
    const CallInterfaceDescriptor& descriptor = callable.descriptor();
    CallDescriptor* call_descriptor =
        Linkage::GetStubCallDescriptor(graph_zone, descriptor, num_stack_args,
                                       CallDescriptor::kNeedsFrameState);
    V<Code> stub_code = __ HeapConstant(callable.code());
    return Call<Object>(
        stub_code, frame_state, arguments,
        TSCallDescriptor::Create(call_descriptor, CanThrow::kYes,
                                 lazy_deopt_on_throw, graph_zone));
  }
References __, v8::internal::Builtins::CallableFor(), v8::internal::Callable::code(), v8::internal::compiler::turboshaft::TSCallDescriptor::Create(), and v8::internal::Callable::descriptor().
CallRuntime()
template<typename Assembler >
template<typename Descriptor >
Descriptor::result_t v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallRuntime (Isolate * isolate, V< turboshaft::FrameState > frame_state, V< Context > context, LazyDeoptOnThrow lazy_deopt_on_throw, const typename Descriptor::arguments_t & args) [inline]
Definition at line 3832 of file assembler.h.
  {
    if (V8_UNLIKELY(Asm().generating_unreachable_operations())) {
      return OpIndex::Invalid();
    }
    DCHECK(frame_state.valid());
    DCHECK(context.valid());
    return CallRuntimeImpl<typename Descriptor::result_t>(
        isolate, Descriptor::kFunction,
        Descriptor::Create(Asm().output_graph().graph_zone(),
                           lazy_deopt_on_throw),
        frame_state, context, args);
  }
  template <typename Descriptor>
  typename Descriptor::result_t CallRuntime(
      Isolate* isolate, V<Context> context,
      const typename Descriptor::arguments_t& args)
    requires(!Descriptor::kNeedsFrameState)
  {
    if (V8_UNLIKELY(Asm().generating_unreachable_operations())) {
      return OpIndex::Invalid();
    }
    DCHECK(context.valid());
    return CallRuntimeImpl<typename Descriptor::result_t>(
        isolate, Descriptor::kFunction,
        Descriptor::Create(Asm().output_graph().graph_zone(),
                           LazyDeoptOnThrow::kNo),
        {}, context, args);
  }
References v8::base::args, v8::internal::DCHECK(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::torque::ls::kFunction, V8_UNLIKELY, v8::internal::compiler::turboshaft::OpIndex::valid(), and v8::internal::compiler::turboshaft::OptionalOpIndex::valid().
CallRuntime_Abort()
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallRuntime_Abort (Isolate * isolate, V< Context > context, V< Smi > reason) [inline]
Definition at line 3896 of file assembler.h.
                                                                              {
    CallRuntime<typename RuntimeCallDescriptor::Abort>(isolate, context,
                                                       {reason});
  }
CallRuntime_BigIntUnaryOp()
template<typename Assembler >
V<BigInt> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallRuntime_BigIntUnaryOp (Isolate * isolate, V< Context > context, V< BigInt > input, ::Operation operation) [inline]
Definition at line 3900 of file assembler.h.
                                                                            {
    DCHECK_EQ(operation,
              any_of(::Operation::kBitwiseNot, ::Operation::kNegate,
                     ::Operation::kIncrement, ::Operation::kDecrement));
    return CallRuntime<typename RuntimeCallDescriptor::BigIntUnaryOp>(
        isolate, context, {input, __ SmiConstant(Smi::FromEnum(operation))});
  }
References __, v8::base::any_of(), DCHECK_EQ, and v8::internal::Smi::FromEnum().
CallRuntime_DateCurrentTime()
template<typename Assembler >
V<Number> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallRuntime_DateCurrentTime (Isolate * isolate, V< Context > context) [inline]
Definition at line 3908 of file assembler.h.
                                                                              {
    return CallRuntime<typename RuntimeCallDescriptor::DateCurrentTime>(
        isolate, context, {});
  }
CallRuntime_DebugPrint()
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallRuntime_DebugPrint (Isolate * isolate, V< Object > object) [inline]
Definition at line 3912 of file assembler.h.
                                                                  {
    CallRuntime<typename RuntimeCallDescriptor::DebugPrint>(
        isolate, NoContextConstant(), {object});
  }
CallRuntime_HandleNoHeapWritesInterrupts()
template<typename Assembler >
V<Object> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallRuntime_HandleNoHeapWritesInterrupts (Isolate * isolate, V< turboshaft::FrameState > frame_state, V< Context > context) [inline]
Definition at line 3916 of file assembler.h.
                          {
    return CallRuntime<
        typename RuntimeCallDescriptor::HandleNoHeapWritesInterrupts>(
        isolate, frame_state, context, LazyDeoptOnThrow::kNo, {});
  }
CallRuntime_HasInPrototypeChain()
template<typename Assembler >
V<Boolean> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallRuntime_HasInPrototypeChain (Isolate * isolate, V< turboshaft::FrameState > frame_state, V< Context > context, LazyDeoptOnThrow lazy_deopt_on_throw, V< Object > object, V< HeapObject > prototype) [inline]
Definition at line 4041 of file assembler.h.
                                                 {
    return CallRuntime<typename RuntimeCallDescriptor::HasInPrototypeChain>(
        isolate, frame_state, context, lazy_deopt_on_throw,
        {object, prototype});
  }
References v8::internal::prototype.
CallRuntime_NewClosure()
template<typename Assembler >
V<JSFunction> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallRuntime_NewClosure (Isolate * isolate, V< Context > context, V< SharedFunctionInfo > shared_function_info, V< FeedbackCell > feedback_cell) [inline]
Definition at line 4027 of file assembler.h.
                                     {
    return CallRuntime<typename RuntimeCallDescriptor::NewClosure>(
        isolate, context, {shared_function_info, feedback_cell});
  }
CallRuntime_NewClosure_Tenured()
template<typename Assembler >
V<JSFunction> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallRuntime_NewClosure_Tenured (Isolate * isolate, V< Context > context, V< SharedFunctionInfo > shared_function_info, V< FeedbackCell > feedback_cell) [inline]
Definition at line 4034 of file assembler.h.
                                     {
    return CallRuntime<typename RuntimeCallDescriptor::NewClosure_Tenured>(
        isolate, context, {shared_function_info, feedback_cell});
  }
CallRuntime_StackGuard()
template<typename Assembler >
V<Object> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallRuntime_StackGuard (Isolate * isolate, V< Context > context) [inline]
Definition at line 3923 of file assembler.h.
                                                                         {
    return CallRuntime<typename RuntimeCallDescriptor::StackGuard>(isolate,
                                                                   context, {});
  }
CallRuntime_StackGuardWithGap()
template<typename Assembler >
V<Object> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallRuntime_StackGuardWithGap (Isolate * isolate, V< turboshaft::FrameState > frame_state, V< Context > context, V< Smi > gap) [inline]
Definition at line 3927 of file assembler.h.
                                                                          {
    return CallRuntime<typename RuntimeCallDescriptor::StackGuardWithGap>(
        isolate, frame_state, context, LazyDeoptOnThrow::kNo, {gap});
  }
CallRuntime_StringCharCodeAt()
template<typename Assembler >
V<Object> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallRuntime_StringCharCodeAt (Isolate * isolate, V< Context > context, V< String > string, V< Number > index) [inline]
Definition at line 3933 of file assembler.h.
                                                                            {
    return CallRuntime<typename RuntimeCallDescriptor::StringCharCodeAt>(
        isolate, context, {string, index});
  }
References v8::internal::index, and v8::internal::string.
CallRuntime_SymbolDescriptiveString()
template<typename Assembler >
V<String> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallRuntime_SymbolDescriptiveString (Isolate * isolate, V< turboshaft::FrameState > frame_state, V< Context > context, V< Symbol > symbol, LazyDeoptOnThrow lazy_deopt_on_throw) [inline]
Definition at line 3946 of file assembler.h.
                                            {
    return CallRuntime<typename RuntimeCallDescriptor::SymbolDescriptiveString>(
        isolate, frame_state, context, lazy_deopt_on_throw, {symbol});
  }
CallRuntime_TerminateExecution()
template<typename Assembler >
V<Object> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallRuntime_TerminateExecution (Isolate * isolate, V< turboshaft::FrameState > frame_state, V< Context > context) [inline]
Definition at line 3953 of file assembler.h.
                          {
    return CallRuntime<typename RuntimeCallDescriptor::TerminateExecution>(
        isolate, frame_state, context, LazyDeoptOnThrow::kNo, {});
  }
CallRuntime_ThrowAccessedUninitializedVariable()
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallRuntime_ThrowAccessedUninitializedVariable (Isolate * isolate, V< turboshaft::FrameState > frame_state, V< Context > context, LazyDeoptOnThrow lazy_deopt_on_throw, V< Object > object) [inline]
Definition at line 3977 of file assembler.h.
                        {
    CallRuntime<
        typename RuntimeCallDescriptor::ThrowAccessedUninitializedVariable>(
        isolate, frame_state, context, lazy_deopt_on_throw, {object});
  }
CallRuntime_ThrowCalledNonCallable()
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallRuntime_ThrowCalledNonCallable (Isolate * isolate, V< turboshaft::FrameState > frame_state, V< Context > context, LazyDeoptOnThrow lazy_deopt_on_throw, V< Object > value) [inline]
Definition at line 4013 of file assembler.h.
                                                           {
    CallRuntime<typename RuntimeCallDescriptor::ThrowCalledNonCallable>(
        isolate, frame_state, context, lazy_deopt_on_throw, {value});
  }
References v8::internal::value.
CallRuntime_ThrowConstructorReturnedNonObject()
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallRuntime_ThrowConstructorReturnedNonObject (Isolate * isolate, V< turboshaft::FrameState > frame_state, V< Context > context, LazyDeoptOnThrow lazy_deopt_on_throw) [inline]
Definition at line 3985 of file assembler.h.
                                                                {
    CallRuntime<
        typename RuntimeCallDescriptor::ThrowConstructorReturnedNonObject>(
        isolate, frame_state, context, lazy_deopt_on_throw, {});
  }
CallRuntime_ThrowInvalidStringLength()
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallRuntime_ThrowInvalidStringLength (Isolate * isolate, V< turboshaft::FrameState > frame_state, V< Context > context, LazyDeoptOnThrow lazy_deopt_on_throw) [inline]
Definition at line 4021 of file assembler.h.
                                                                {
    CallRuntime<typename RuntimeCallDescriptor::ThrowInvalidStringLength>(
        isolate, frame_state, context, lazy_deopt_on_throw, {});
  }
CallRuntime_ThrowNotSuperConstructor()
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallRuntime_ThrowNotSuperConstructor (Isolate * isolate, V< turboshaft::FrameState > frame_state, V< Context > context, LazyDeoptOnThrow lazy_deopt_on_throw, V< Object > constructor, V< Object > function) [inline]
Definition at line 3992 of file assembler.h.
                                                 {
    CallRuntime<typename RuntimeCallDescriptor::ThrowNotSuperConstructor>(
        isolate, frame_state, context, lazy_deopt_on_throw,
        {constructor, function});
  }
CallRuntime_ThrowSuperAlreadyCalledError()
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallRuntime_ThrowSuperAlreadyCalledError (Isolate * isolate, V< turboshaft::FrameState > frame_state, V< Context > context, LazyDeoptOnThrow lazy_deopt_on_throw) [inline]
Definition at line 4000 of file assembler.h.
                                                                {
    CallRuntime<typename RuntimeCallDescriptor::ThrowSuperAlreadyCalledError>(
        isolate, frame_state, context, lazy_deopt_on_throw, {});
  }
CallRuntime_ThrowSuperNotCalled()
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallRuntime_ThrowSuperNotCalled (Isolate * isolate, V< turboshaft::FrameState > frame_state, V< Context > context, LazyDeoptOnThrow lazy_deopt_on_throw) [inline]
Definition at line 4006 of file assembler.h.
                                                                             {
    CallRuntime<typename RuntimeCallDescriptor::ThrowSuperNotCalled>(
        isolate, frame_state, context, lazy_deopt_on_throw, {});
  }
CallRuntime_TransitionElementsKind()
template<typename Assembler >
V<Object> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallRuntime_TransitionElementsKind (Isolate * isolate, V< Context > context, V< HeapObject > object, V< Map > target_map) [inline]
Definition at line 3959 of file assembler.h.
                                                                  {
    return CallRuntime<typename RuntimeCallDescriptor::TransitionElementsKind>(
        isolate, context, {object, target_map});
  }
CallRuntime_TryMigrateInstance()
template<typename Assembler >
V<Object> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallRuntime_TryMigrateInstance (Isolate * isolate, V< Context > context, V< HeapObject > heap_object) [inline]
Definition at line 3966 of file assembler.h.
                                                                      {
    return CallRuntime<typename RuntimeCallDescriptor::TryMigrateInstance>(
        isolate, context, {heap_object});
  }
CallRuntime_TryMigrateInstanceAndMarkMapAsMigrationTarget()
template<typename Assembler >
V<Object> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallRuntime_TryMigrateInstanceAndMarkMapAsMigrationTarget (Isolate * isolate, V< Context > context, V< HeapObject > heap_object) [inline]
Definition at line 3971 of file assembler.h.
                                                                       {
    return CallRuntime<typename RuntimeCallDescriptor::
                           TryMigrateInstanceAndMarkMapAsMigrationTarget>(
        isolate, context, {heap_object});
  }
CallRuntimeImpl()
template<typename Assembler >
template<typename Ret , typename Args >
Ret v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallRuntimeImpl (Isolate * isolate, Runtime::FunctionId function, const TSCallDescriptor * desc, V< turboshaft::FrameState > frame_state, V< Context > context, const Args & args) [inline]
Definition at line 3867 of file assembler.h.
                                        {
    const int result_size = Runtime::FunctionForId(function)->result_size;
    constexpr size_t kMaxNumArgs = 6;
    const size_t argc = std::tuple_size_v<Args>;
    static_assert(kMaxNumArgs >= argc);
    // Convert arguments from `args` tuple into a `SmallVector<OpIndex>`.
    using vector_t = base::SmallVector<OpIndex, argc + 4>;
    auto inputs = std::apply(
        [](auto&&... as) {
          return vector_t{std::forward<decltype(as)>(as)...};
        },
        args);
    DCHECK(context.valid());
    inputs.push_back(ExternalConstant(ExternalReference::Create(function)));
    inputs.push_back(Word32Constant(static_cast<int>(argc)));
    inputs.push_back(context);
    if constexpr (std::is_same_v<Ret, void>) {
      Call(CEntryStubConstant(isolate, result_size), frame_state,
           base::VectorOf(inputs), desc);
    } else {
      return Ret::Cast(Call(CEntryStubConstant(isolate, result_size),
                            frame_state, base::VectorOf(inputs), desc));
    }
  }
References v8::base::args, v8::internal::Cast(), v8::internal::ExternalReference::Create(), v8::internal::DCHECK(), v8::internal::Runtime::FunctionForId(), v8::internal::Runtime::Function::result_size, v8::internal::compiler::turboshaft::OpIndex::valid(), and v8::base::VectorOf().
CatchBlockBegin()
template<typename Assembler >
V<Object> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CatchBlockBegin () [inline]
Definition at line 4354 of file assembler.h.
{ return ReduceIfReachableCatchBlockBegin(); }
CEntryStubConstant()
template<typename Assembler >
V<Code> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CEntryStubConstant (Isolate * isolate, int result_size, ArgvMode argv_mode = ArgvMode::kStack, bool builtin_exit_frame = false) [inline]
Definition at line 2419 of file assembler.h.
                                                              {
    if (argv_mode != ArgvMode::kStack) {
      return HeapConstant(CodeFactory::CEntry(isolate, result_size, argv_mode,
                                              builtin_exit_frame));
    }
    DCHECK(result_size >= 1 && result_size <= 3);
    DCHECK_IMPLIES(builtin_exit_frame, result_size == 1);
    const int index = builtin_exit_frame ? 0 : result_size;
    if (cached_centry_stub_constants_[index].is_null()) {
      cached_centry_stub_constants_[index] = CodeFactory::CEntry(
          isolate, result_size, argv_mode, builtin_exit_frame);
    }
    return HeapConstant(cached_centry_stub_constants_[index].ToHandleChecked());
  }
References v8::internal::CodeFactory::CEntry(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::index, and v8::internal::kStack.
ChangeFloat16RawBitsToFloat64()
template<typename Assembler >
V<Float64> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ChangeFloat16RawBitsToFloat64 (V< Word32 > input) [inline]
Definition at line 4729 of file assembler.h.
                                                            {
    return V<Float64>::Cast(__ ReduceChange(
        input, ChangeOp::Kind::kJSFloat16ChangeWithBitcast,
        ChangeOp::Assumption::kNoAssumption, V<Word32>::rep, V<Float64>::rep));
  }
References __, and v8::internal::compiler::turboshaft::V< T >::Cast().
ChangeFloat64ToAdditiveSafeIntegerOrDeopt()
template<typename Assembler >
V<Word64> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ChangeFloat64ToAdditiveSafeIntegerOrDeopt (V< Float64 > input, V< turboshaft::FrameState > frame_state, CheckForMinusZeroMode minus_zero_mode, const FeedbackSource & feedback) [inline]
Definition at line 2628 of file assembler.h.
                                                                             {
    return V<Word64>::Cast(
        ChangeOrDeopt(input, frame_state,
                      ChangeOrDeoptOp::Kind::kFloat64ToAdditiveSafeInteger,
                      minus_zero_mode, feedback));
  }
References v8::internal::compiler::turboshaft::V< T >::Cast().
ChangeFloat64ToInt32OrDeopt()
template<typename Assembler >
V<Word32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ChangeFloat64ToInt32OrDeopt (V< Float64 > input, V< turboshaft::FrameState > frame_state, CheckForMinusZeroMode minus_zero_mode, const FeedbackSource & feedback) [inline]
Definition at line 2612 of file assembler.h.
                                                                        {
    return V<Word32>::Cast(ChangeOrDeopt(input, frame_state,
                                         ChangeOrDeoptOp::Kind::kFloat64ToInt32,
                                         minus_zero_mode, feedback));
  }
References v8::internal::compiler::turboshaft::V< T >::Cast().
ChangeFloat64ToInt64OrDeopt()
template<typename Assembler >
V<Word64> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ChangeFloat64ToInt64OrDeopt (V< Float64 > input, V< turboshaft::FrameState > frame_state, CheckForMinusZeroMode minus_zero_mode, const FeedbackSource & feedback) [inline]
Definition at line 2636 of file assembler.h.
                                                                        {
    return V<Word64>::Cast(ChangeOrDeopt(input, frame_state,
                                         ChangeOrDeoptOp::Kind::kFloat64ToInt64,
                                         minus_zero_mode, feedback));
  }
References v8::internal::compiler::turboshaft::V< T >::Cast().
ChangeFloat64ToUint32OrDeopt()
template<typename Assembler >
V<Word32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ChangeFloat64ToUint32OrDeopt (V< Float64 > input, V< turboshaft::FrameState > frame_state, CheckForMinusZeroMode minus_zero_mode, const FeedbackSource & feedback) [inline]
Definition at line 2620 of file assembler.h.
                                                                         {
    return V<Word32>::Cast(ChangeOrDeopt(
        input, frame_state, ChangeOrDeoptOp::Kind::kFloat64ToUint32,
        minus_zero_mode, feedback));
  }
References v8::internal::compiler::turboshaft::V< T >::Cast().
ChangeInt32ToIntPtr()
template<typename Assembler >
V<WordPtr> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ChangeInt32ToIntPtr (V< Word32 > input) [inline]
Definition at line 2504 of file assembler.h.
                                                  {
    if constexpr (Is64()) {
      return ChangeInt32ToInt64(input);
    } else {
      DCHECK_EQ(WordPtr::bits, Word32::bits);
      return V<WordPtr>::Cast(input);
    }
  }
References v8::internal::compiler::turboshaft::WordWithBits< 32 >::bits, v8::internal::compiler::turboshaft::V< T >::Cast(), DCHECK_EQ, and v8::internal::Is64().
ChangeIntPtrToInt64()
template<typename Assembler >
V<Word64> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ChangeIntPtrToInt64 (V< WordPtr > input) [inline]
Definition at line 2521 of file assembler.h.
                                                  {
    if constexpr (Is64()) {
      DCHECK_EQ(WordPtr::bits, Word64::bits);
      return V<Word64>::Cast(input);
    } else {
      return ChangeInt32ToInt64(input);
    }
  }
References v8::internal::compiler::turboshaft::WordWithBits< Bits >::bits, v8::internal::compiler::turboshaft::V< T >::Cast(), DCHECK_EQ, and v8::internal::Is64().
ChangeOrDeopt()
template<typename Assembler >
Word32 Word64 Word32 V<Untagged> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ChangeOrDeopt (V< Untagged > input, V< turboshaft::FrameState > frame_state, ChangeOrDeoptOp::Kind kind, CheckForMinusZeroMode minus_zero_mode, const FeedbackSource & feedback) [inline]
Definition at line 2603 of file assembler.h.
                                                            {
    return ReduceIfReachableChangeOrDeopt(input, frame_state, kind,
                                          minus_zero_mode, feedback);
  }
ChangeUint32ToUintPtr()
template<typename Assembler >
V<WordPtr> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ChangeUint32ToUintPtr (V< Word32 > input) [inline]
Definition at line 2512 of file assembler.h.
                                                    {
    if constexpr (Is64()) {
      return ChangeUint32ToUint64(input);
    } else {
      DCHECK_EQ(WordPtr::bits, Word32::bits);
      return V<WordPtr>::Cast(input);
    }
  }
References v8::internal::compiler::turboshaft::WordWithBits< 32 >::bits, v8::internal::compiler::turboshaft::V< T >::Cast(), DCHECK_EQ, and v8::internal::Is64().
ChangeUintPtrToUint64()
template<typename Assembler >
V<Word64> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ChangeUintPtrToUint64 (V< WordPtr > input) [inline]
Definition at line 2530 of file assembler.h.
                                                    {
    if constexpr (Is64()) {
      DCHECK_EQ(WordPtr::bits, Word64::bits);
      return V<Word64>::Cast(input);
    } else {
      return ChangeUint32ToUint64(input);
    }
  }
References v8::internal::compiler::turboshaft::WordWithBits< Bits >::bits, v8::internal::compiler::turboshaft::V< T >::Cast(), DCHECK_EQ, and v8::internal::Is64().
Check()
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Check (V< Word32 > condition, const char * message, const char * file, int line, const SourceLocation & loc = SourceLocation::Current()) [inline]
Definition at line 4217 of file assembler.h.
                                                                            {
    Isolate* isolate = Asm().data()->isolate();
    USE(isolate);
    DCHECK_NOT_NULL(isolate);
    DCHECK_EQ(ThreadId::Current(), isolate->thread_id());
    if (message != nullptr) {
      CodeComment({"[ Assert: ", loc}, message);
    } else {
      CodeComment({"[ Assert: ", loc});
    }
    IF_NOT (LIKELY(condition)) {
      std::vector<FileAndLine> file_and_line;
      if (file != nullptr) {
        file_and_line.push_back({file, line});
      }
      FailAssert(message, file_and_line, loc);
    }
    CodeComment({"] Assert", SourceLocation()});
  }
References v8::internal::ThreadId::Current(), DCHECK_EQ, DCHECK_NOT_NULL, file(), v8::internal::Factory::isolate(), v8::internal::loc, v8::internal::Isolate::thread_id(), and USE.
CheckedClosure()
template<typename Assembler >
V<Object> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CheckedClosure (V< Object > input, V< turboshaft::FrameState > frame_state, Handle< FeedbackCell > feedback_cell) [inline]
Definition at line 4711 of file assembler.h.
                                                               {
    return ReduceIfReachableCheckedClosure(input, frame_state, feedback_cell);
  }
CheckedSmiUntag()
template<typename Assembler >
V<Word32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CheckedSmiUntag (V< Object > object, V< turboshaft::FrameState > frame_state, const FeedbackSource & feedback) [inline]
Definition at line 2218 of file assembler.h.
                                                            {
    return V<Word32>::Cast(ConvertJSPrimitiveToUntaggedOrDeopt(
        object, frame_state,
        ConvertJSPrimitiveToUntaggedOrDeoptOp::JSPrimitiveKind::kSmi,
        ConvertJSPrimitiveToUntaggedOrDeoptOp::UntaggedKind::kInt32,
        CheckForMinusZeroMode::kDontCheckForMinusZero, feedback));
  }
References v8::internal::compiler::turboshaft::V< T >::Cast(), and v8::internal::compiler::kSmi.
CheckEqualsInternalizedString()
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CheckEqualsInternalizedString (V< Object > expected, V< Object > value, V< turboshaft::FrameState > frame_state) [inline]
Definition at line 4717 of file assembler.h.
                                                                          {
    ReduceIfReachableCheckEqualsInternalizedString(expected, value,
                                                   frame_state);
  }
References v8::internal::value.
CheckMaps()
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CheckMaps (V< HeapObject > heap_object, V< turboshaft::FrameState > frame_state, OptionalV< Map > map, const ZoneRefSet< Map > & maps, CheckMapsFlags flags, const FeedbackSource & feedback) [inline]
Definition at line 4699 of file assembler.h.
                                                 {
    ReduceIfReachableCheckMaps(heap_object, frame_state, map, maps, flags,
                               feedback);
  }
References v8::internal::flags.
CheckTurboshaftTypeOf()
template<typename Assembler >
OpIndex v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CheckTurboshaftTypeOf (OpIndex input, RegisterRepresentation rep, Type expected_type, bool successful) [inline]
Definition at line 4195 of file assembler.h.
                                                                     {
    CHECK(v8_flags.turboshaft_enable_debug_features);
    return ReduceIfReachableCheckTurboshaftTypeOf(input, rep, expected_type,
                                                  successful);
  }
References CHECK, and v8::internal::v8_flags.
CodeComment()
template<typename Assembler >
template<typename... Args>
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CodeComment (MessageWithSourceLocation message, Args &&... args) [inline]
Definition at line 4501 of file assembler.h.
                                                                      {
    if (!v8_flags.code_comments) return;
    std::ostringstream s;
    USE(s << message.message, (s << std::forward<Args>(args))...);
    if (message.loc.FileName()) {
      s << " - " << message.loc.ToString();
    }
    Comment(std::move(s).str());
  }
References v8::base::args, v8::SourceLocation::FileName(), v8::internal::compiler::CodeAssembler::MessageWithSourceLocation::loc, v8::internal::compiler::CodeAssembler::MessageWithSourceLocation::message, v8::SourceLocation::ToString(), USE, and v8::internal::v8_flags.
Comment() [1/2]
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Comment (const char * message) [inline]
Definition at line 4491 of file assembler.h.
{ ReduceIfReachableComment(message); }
Comment() [2/2]
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Comment (const std::string & message) [inline]
Definition at line 4492 of file assembler.h.
                                         {
    size_t length = message.length() + 1;
    char* zone_buffer =
        Asm().data()->compilation_zone()->template AllocateArray<char>(length);
    MemCopy(zone_buffer, message.c_str(), length);
    Comment(zone_buffer);
  }
References v8::internal::length, and v8::internal::MemCopy().
CompareMaps()
template<typename Assembler >
V<Word32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CompareMaps (V< HeapObject > heap_object, OptionalV< Map > map, const ZoneRefSet< Map > & maps) [inline]
Definition at line 4694 of file assembler.h.
                                                     {
    return ReduceIfReachableCompareMaps(heap_object, map, maps);
  }
Comparison()
template<typename Assembler >
UnsignedLessThan SignedLessThanOrEqual Word64 UnsignedLessThanOrEqual Word64 SignedLessThanOrEqual Float64 V<Word32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Comparison (OpIndex left, OpIndex right, ComparisonOp::Kind kind, RegisterRepresentation rep) [inline]
Definition at line 1876 of file assembler.h.
                                                   {
    return ReduceIfReachableComparison(left, right, kind, rep);
  }
CompressedHeapConstant()
template<typename Assembler >
OpIndex v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CompressedHeapConstant (Handle< HeapObject > value) [inline]
Definition at line 2374 of file assembler.h.
                                                           {
    return ReduceIfReachableConstant(ConstantOp::Kind::kHeapObject, value);
  }
References v8::internal::value.
Conditional()
template<typename Assembler >
template<typename T , typename U >
V<std::common_type_t<T, U> > v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Conditional (ConstOrV< Word32 > cond, V< T > vtrue, V< U > vfalse, BranchHint hint = BranchHint::kNone) [inline]
Definition at line 3298 of file assembler.h.
                                                                             {
    return Select(resolve(cond), vtrue, vfalse,
                  V<std::common_type_t<T, U>>::rep, hint,
                  SelectOp::Implementation::kBranch);
  }
References v8::internal::compiler::turboshaft::kBranch.
Convert()
template<typename Assembler >
V<Object> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Convert (V< Object > input, ConvertOp::Kind from, ConvertOp::Kind to) [inline]
Definition at line 2138 of file assembler.h.
                                                                           {
    return ReduceIfReachableConvert(input, from, to);
  }
ConvertFloat64ToNumber()
template<typename Assembler >
V<Number> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ConvertFloat64ToNumber (V< Float64 > input, CheckForMinusZeroMode minus_zero_mode) [inline]
Definition at line 2182 of file assembler.h.
                                                                          {
    return V<Number>::Cast(ConvertUntaggedToJSPrimitive(
        input, ConvertUntaggedToJSPrimitiveOp::JSPrimitiveKind::kNumber,
        RegisterRepresentation::Float64(),
        ConvertUntaggedToJSPrimitiveOp::InputInterpretation::kSigned,
        minus_zero_mode));
  }
References v8::internal::compiler::turboshaft::V< T >::Cast(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float64(), and v8::internal::compiler::kSigned.
ConvertJSPrimitiveToObject()
template<typename Assembler >
V<Object> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ConvertJSPrimitiveToObject (V< JSPrimitive > value, V< Context > native_context, V< JSGlobalProxy > global_proxy, ConvertReceiverMode mode) [inline]
Definition at line 2251 of file assembler.h.
                                                                 {
    return ReduceIfReachableConvertJSPrimitiveToObject(value, native_context,
                                                       global_proxy, mode);
  }
References mode(), v8::internal::native_context, and v8::internal::value.
ConvertJSPrimitiveToUntagged()
template<typename Assembler >
V<Untagged> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ConvertJSPrimitiveToUntagged (V< JSPrimitive > primitive, ConvertJSPrimitiveToUntaggedOp::UntaggedKind kind, ConvertJSPrimitiveToUntaggedOp::InputAssumptions input_assumptions) [inline]
Definition at line 2202 of file assembler.h.
                                                                        {
    return ReduceIfReachableConvertJSPrimitiveToUntagged(primitive, kind,
                                                         input_assumptions);
  }
ConvertJSPrimitiveToUntaggedOrDeopt()
template<typename Assembler >
V<Untagged> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ConvertJSPrimitiveToUntaggedOrDeopt (V< Object > object, V< turboshaft::FrameState > frame_state, ConvertJSPrimitiveToUntaggedOrDeoptOp::JSPrimitiveKind from_kind, ConvertJSPrimitiveToUntaggedOrDeoptOp::UntaggedKind to_kind, CheckForMinusZeroMode minus_zero_mode, const FeedbackSource & feedback) [inline]
Definition at line 2210 of file assembler.h.
                                                                             {
    return ReduceIfReachableConvertJSPrimitiveToUntaggedOrDeopt(
        object, frame_state, from_kind, to_kind, minus_zero_mode, feedback);
  }
ConvertNumberToString()
template<typename Assembler >
V<String> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ConvertNumberToString (V< Number > input) [inline]
Definition at line 2149 of file assembler.h.
                                                   {
    return V<String>::Cast(
        Convert(input, ConvertOp::Kind::kNumber, ConvertOp::Kind::kString));
  }
References v8::internal::compiler::turboshaft::V< T >::Cast().
ConvertPlainPrimitiveToNumber()
template<typename Assembler >
V<Number> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ConvertPlainPrimitiveToNumber (V< PlainPrimitive > input) [inline]
Definition at line 2141 of file assembler.h.
                                                                   {
    return V<Number>::Cast(Convert(input, ConvertOp::Kind::kPlainPrimitive,
                                   ConvertOp::Kind::kNumber));
  }
References v8::internal::compiler::turboshaft::V< T >::Cast().
ConvertStringToNumber()
template<typename Assembler >
V<Number> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ConvertStringToNumber (V< String > input) [inline]
Definition at line 2153 of file assembler.h.
                                                   {
    return V<Number>::Cast(
        Convert(input, ConvertOp::Kind::kString, ConvertOp::Kind::kNumber));
  }
References v8::internal::compiler::turboshaft::V< T >::Cast().
ConvertToBoolean()
template<typename Assembler >
V<Boolean> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ConvertToBoolean (V< Object > input) [inline]
Definition at line 2145 of file assembler.h.
                                               {
    return V<Boolean>::Cast(
        Convert(input, ConvertOp::Kind::kObject, ConvertOp::Kind::kBoolean));
  }
References v8::internal::compiler::turboshaft::V< T >::Cast().
ConvertUntaggedToJSPrimitive()
template<typename Assembler >
V<JSPrimitive> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ConvertUntaggedToJSPrimitive (V< Untagged > input, ConvertUntaggedToJSPrimitiveOp::JSPrimitiveKind kind, RegisterRepresentation input_rep, ConvertUntaggedToJSPrimitiveOp::InputInterpretation input_interpretation, CheckForMinusZeroMode minus_zero_mode) [inline]
Definition at line 2158 of file assembler.h.
                                             {
    return ReduceIfReachableConvertUntaggedToJSPrimitive(
        input, kind, input_rep, input_interpretation, minus_zero_mode);
  }
ConvertUntaggedToJSPrimitiveOrDeopt()
template<typename Assembler >
V<JSPrimitive> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ConvertUntaggedToJSPrimitiveOrDeopt (V< Untagged > input, V< turboshaft::FrameState > frame_state, ConvertUntaggedToJSPrimitiveOrDeoptOp::JSPrimitiveKind kind, RegisterRepresentation input_rep, ConvertUntaggedToJSPrimitiveOrDeoptOp::InputInterpretation input_interpretation, const FeedbackSource & feedback) [inline]
Definition at line 2191 of file assembler.h.
                                      {
    return ReduceIfReachableConvertUntaggedToJSPrimitiveOrDeopt(
        input, frame_state, kind, input_rep, input_interpretation, feedback);
  }
Dcheck()
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Dcheck (V< Word32 > condition, const char * message, const char * file, int line, const SourceLocation & loc = SourceLocation::Current()) [inline]
Definition at line 4203 of file assembler.h.
                                                                             {
    Isolate* isolate = Asm().data()->isolate();
    USE(isolate);
    DCHECK_NOT_NULL(isolate);
    DCHECK_EQ(ThreadId::Current(), isolate->thread_id());
#ifdef DEBUG
    if (v8_flags.debug_code) {
      Check(condition, message, file, line, loc);
    }
#endif
  }
References v8::internal::ThreadId::Current(), DCHECK_EQ, DCHECK_NOT_NULL, file(), v8::internal::Factory::isolate(), v8::internal::loc, v8::internal::Isolate::thread_id(), USE, and v8::internal::v8_flags.
DCHECK_LT()
template<typename Assembler >
v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DCHECK_LT (right , rep. bit_width())
DebugBreak()
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DebugBreak () [inline]
Definition at line 4452 of file assembler.h.
{ ReduceIfReachableDebugBreak(); }
DebugPrint() [1/4]
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DebugPrint (OpIndex input, RegisterRepresentation rep) [inline]
Definition at line 4477 of file assembler.h.
                                                             {
    CHECK(v8_flags.turboshaft_enable_debug_features);
    ReduceIfReachableDebugPrint(input, rep);
  }
References CHECK, and v8::internal::v8_flags.
DebugPrint() [2/4]
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DebugPrint (V< Float64 > input) [inline]
Definition at line 4487 of file assembler.h.
                                    {
    DebugPrint(input, RegisterRepresentation::Float64());
  }
References DebugPrint, and v8::internal::compiler::turboshaft::RegisterRepresentation::Float64().
DebugPrint() [3/4]
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DebugPrint (V< Object > input) [inline]
Definition at line 4481 of file assembler.h.
                                   {
    DebugPrint(input, RegisterRepresentation::Tagged());
  }
References DebugPrint, and v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged().
DebugPrint() [4/4]
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DebugPrint (V< WordPtr > input) [inline]
Definition at line 4484 of file assembler.h.
                                    {
    DebugPrint(input, RegisterRepresentation::WordPtr());
  }
References DebugPrint, and v8::internal::compiler::turboshaft::RegisterRepresentation::WordPtr().
DECL_CHANGE_V() [1/14]
template<typename Assembler >
v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_CHANGE_V (BitcastFloat32ToWord32 , kBitcast , kNoAssumption , Float32 , Word32)
DECL_CHANGE_V() [2/14]
template<typename Assembler >
Float32 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_CHANGE_V (BitcastFloat64ToWord64 , kBitcast , kNoAssumption , Float64 , Word64)
DECL_CHANGE_V() [3/14]
template<typename Assembler >
Float32 Float64 Float64 Float32 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_CHANGE_V (ChangeInt64ToFloat32 , kSignedToFloat , kNoAssumption , Word64 , Float32)
DECL_CHANGE_V() [4/14]
template<typename Assembler >
Float32 Float64 Float64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_CHANGE_V (ChangeInt64ToFloat64 , kSignedToFloat , kNoAssumption , Word64 , Float64)
DECL_CHANGE_V() [5/14]
template<typename Assembler >
Float32 Float64 Float64 Float32 Float32 Float64 Float64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_CHANGE_V (ChangeUint32ToFloat64 , kUnsignedToFloat , kNoAssumption , Word32 , Float64)
DECL_CHANGE_V() [6/14]
template<typename Assembler >
Float32 Float64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_CHANGE_V (ChangeUint32ToUint64 , kZeroExtend , kNoAssumption , Word32 , Word64)
DECL_CHANGE_V() [7/14]
template<typename Assembler >
Float32 Float64 Float64 Float32 Float32 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_CHANGE_V (ChangeUint64ToFloat32 , kUnsignedToFloat , kNoAssumption , Word64 , Float32)
DECL_CHANGE_V() [8/14]
template<typename Assembler >
Float32 Float64 Float64 Float32 Float32 Float64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_CHANGE_V (ChangeUint64ToFloat64 , kUnsignedToFloat , kNoAssumption , Word64 , Float64)
DECL_CHANGE_V() [9/14]
template<typename Assembler >
Word32 Word64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_CHANGE_V (Float64ExtractLowWord32 , kExtractLowHalf , kNoAssumption , Float64 , Word32)
DECL_CHANGE_V() [10/14]
template<typename Assembler >
Float32 Float64 Float64 Float32 Float32 Float64 Float64 Float64 Float64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_CHANGE_V (JSTruncateFloat64ToWord32 , kJSFloatTruncate , kNoAssumption , Float64 , Word32)
DECL_CHANGE_V() [11/14]
template<typename Assembler >
v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_CHANGE_V (ReversibleFloat64ToInt32 , kSignedFloatTruncateOverflowToMin , kReversible , Float64 , Word32)
DECL_CHANGE_V() [12/14]
template<typename Assembler >
Word32 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_CHANGE_V (ReversibleFloat64ToInt64 , kSignedFloatTruncateOverflowToMin , kReversible , Float64 , Word64)
DECL_CHANGE_V() [13/14]
template<typename Assembler >
Float32 Float64 Float64 Float32 Float32 Float64 Float64 Float64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_CHANGE_V (TruncateFloat64ToFloat32 , kFloatConversion , kNoAssumption , Float64 , Float32)
DECL_CHANGE_V() [14/14]
template<typename Assembler >
v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_CHANGE_V (TruncateFloat64ToInt64OverflowToMin , kSignedFloatTruncateOverflowToMin , kNoAssumption , Float64 , Word64)
DECL_MULTI_REP_BINOP() [1/5]
template<typename Assembler >
UnsignedLessThan v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_MULTI_REP_BINOP (FloatLessThan , Comparison , RegisterRepresentation , SignedLessThan)
DECL_MULTI_REP_BINOP() [2/5]
template<typename Assembler >
v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_MULTI_REP_BINOP (IntLessThan , Comparison , RegisterRepresentation , SignedLessThan)
DECL_MULTI_REP_BINOP() [3/5]
template<typename Assembler >
Word32 WordPtr v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_MULTI_REP_BINOP (ShiftRightArithmetic , Shift , WordRepresentation , ShiftRightArithmetic)
DECL_MULTI_REP_BINOP() [4/5]
template<typename Assembler >
v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_MULTI_REP_BINOP (ShiftRightArithmeticShiftOutZeros , Shift , WordRepresentation , ShiftRightArithmeticShiftOutZeros)
DECL_MULTI_REP_BINOP() [5/5]
template<typename Assembler >
Word32 WordPtr Word32 WordPtr v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_MULTI_REP_BINOP (ShiftRightLogical , Shift , WordRepresentation , ShiftRightLogical)
DECL_MULTI_REP_BINOP_V()
template<typename Assembler >
v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_MULTI_REP_BINOP_V (IntMulOverflownBits , WordBinop , SignedMulOverflownBits , Word)
DECL_MULTI_REP_CHECK_BINOP_V() [1/2]
template<typename Assembler >
v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_MULTI_REP_CHECK_BINOP_V (IntAddCheckOverflow , OverflowCheckedBinop , SignedAdd , Word)
DECL_MULTI_REP_CHECK_BINOP_V() [2/2]
template<typename Assembler >
Word32 Word Word64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_MULTI_REP_CHECK_BINOP_V (IntMulCheckOverflow , OverflowCheckedBinop , SignedMul , Word)
DECL_MULTI_REP_UNARY_V() [1/7]
template<typename Assembler >
v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_MULTI_REP_UNARY_V (FloatNegate , FloatUnary , FloatRepresentation , Negate , Float)
DECL_MULTI_REP_UNARY_V() [2/7]
template<typename Assembler >
Float Float v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_MULTI_REP_UNARY_V (FloatRoundTiesEven , FloatUnary , FloatRepresentation , RoundTiesEven , Float)
DECL_MULTI_REP_UNARY_V() [3/7]
template<typename Assembler >
Float v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_MULTI_REP_UNARY_V (FloatRoundUp , FloatUnary , FloatRepresentation , RoundUp , Float)
DECL_MULTI_REP_UNARY_V() [4/7]
template<typename Assembler >
v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_MULTI_REP_UNARY_V (IntAbsCheckOverflow , OverflowCheckedUnary , WordRepresentation , Abs , Word)
DECL_MULTI_REP_UNARY_V() [5/7]
template<typename Assembler >
Float Float Float32 Float Word Word64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_MULTI_REP_UNARY_V (WordCountTrailingZeros , WordUnary , WordRepresentation , CountTrailingZeros , Word)
DECL_MULTI_REP_UNARY_V() [6/7]
template<typename Assembler >
Float Float Float32 Float v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_MULTI_REP_UNARY_V (WordReverseBytes , WordUnary , WordRepresentation , ReverseBytes , Word)
DECL_MULTI_REP_UNARY_V() [7/7]
template<typename Assembler >
Float Float Float32 Float Word Word64 Word32 Word v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_MULTI_REP_UNARY_V (WordSignExtend8 , WordUnary , WordRepresentation , SignExtend8 , Word)
DECL_SINGLE_REP_BINOP_V() [1/2]
template<typename Assembler >
Word32 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_SINGLE_REP_BINOP_V (Int64MulOverflownBits , WordBinop , SignedMulOverflownBits , Word64)
DECL_SINGLE_REP_BINOP_V() [2/2]
template<typename Assembler >
Word32 Word v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_SINGLE_REP_BINOP_V (Uint32MulOverflownBits , WordBinop , UnsignedMulOverflownBits , Word32)
DECL_SINGLE_REP_CHECK_BINOP_V() [1/3]
template<typename Assembler >
Word32 Word v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_SINGLE_REP_CHECK_BINOP_V (Int32SubCheckOverflow , OverflowCheckedBinop , SignedSub , Word32)
DECL_SINGLE_REP_CHECK_BINOP_V() [2/3]
template<typename Assembler >
Word32 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_SINGLE_REP_CHECK_BINOP_V (Int64AddCheckOverflow , OverflowCheckedBinop , SignedAdd , Word64)
DECL_SINGLE_REP_CHECK_BINOP_V() [3/3]
template<typename Assembler >
Word32 Word Word64 Word32 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_SINGLE_REP_CHECK_BINOP_V (Int64MulCheckOverflow , OverflowCheckedBinop , SignedMul , Word64)
DECL_SINGLE_REP_COMPARISON_V() [1/5]
template<typename Assembler >
UnsignedLessThan SignedLessThanOrEqual Word64 UnsignedLessThanOrEqual Word64 SignedLessThanOrEqual v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_SINGLE_REP_COMPARISON_V (Float32LessThanOrEqual , SignedLessThanOrEqual , Float32)
DECL_SINGLE_REP_COMPARISON_V() [2/5]
template<typename Assembler >
UnsignedLessThan SignedLessThanOrEqual v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_SINGLE_REP_COMPARISON_V (Int32LessThanOrEqual , SignedLessThanOrEqual , Word32)
DECL_SINGLE_REP_COMPARISON_V() [3/5]
template<typename Assembler >
UnsignedLessThan SignedLessThanOrEqual Word64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_SINGLE_REP_COMPARISON_V (IntPtrLessThanOrEqual , SignedLessThanOrEqual , WordPtr)
DECL_SINGLE_REP_COMPARISON_V() [4/5]
template<typename Assembler >
UnsignedLessThan SignedLessThanOrEqual Word64 UnsignedLessThanOrEqual v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_SINGLE_REP_COMPARISON_V (Uint32LessThanOrEqual , UnsignedLessThanOrEqual , Word32)
DECL_SINGLE_REP_COMPARISON_V() [5/5]
template<typename Assembler >
UnsignedLessThan SignedLessThanOrEqual Word64 UnsignedLessThanOrEqual Word64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_SINGLE_REP_COMPARISON_V (UintPtrLessThanOrEqual , UnsignedLessThanOrEqual , WordPtr)
DECL_SINGLE_REP_SHIFT_V() [1/2]
template<typename Assembler >
Word32 WordPtr Word32 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_SINGLE_REP_SHIFT_V (Word64ShiftRightArithmetic , ShiftRightArithmetic , Word64)
DECL_SINGLE_REP_SHIFT_V() [2/2]
template<typename Assembler >
Word32 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_SINGLE_REP_SHIFT_V (Word64ShiftRightArithmeticShiftOutZeros , ShiftRightArithmeticShiftOutZeros , Word64)
DECL_SINGLE_REP_UNARY_V() [1/4]
template<typename Assembler >
Float Float Float32 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_SINGLE_REP_UNARY_V (Float64RoundTiesEven , FloatUnary , RoundTiesEven , Float64)
DECL_SINGLE_REP_UNARY_V() [2/4]
template<typename Assembler >
Word32 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_SINGLE_REP_UNARY_V (Int64AbsCheckOverflow , OverflowCheckedUnary , Abs , Word64)
DECL_SINGLE_REP_UNARY_V() [3/4]
template<typename Assembler >
Float Float Float32 Float Word v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_SINGLE_REP_UNARY_V (Word32CountLeadingZeros , WordUnary , CountLeadingZeros , Word32)
DECL_SINGLE_REP_UNARY_V() [4/4]
template<typename Assembler >
Float Float Float32 Float Word Word64 Word32 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DECL_SINGLE_REP_UNARY_V (Word64CountTrailingZeros , WordUnary , CountTrailingZeros , Word64)
DecodeExternalPointer()
template<typename Assembler >
V<WordPtr> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DecodeExternalPointer (V< Word32 > handle, ExternalPointerTag tag) [inline]
Definition at line 3201 of file assembler.h.
                                                                             {
    return ReduceIfReachableDecodeExternalPointer(handle, tag);
  }
References v8::internal::handle().
Deoptimize() [1/2]
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Deoptimize (V< turboshaft::FrameState > frame_state, const DeoptimizeParameters * parameters) [inline]
Definition at line 4091 of file assembler.h.
                                                          {
    ReduceIfReachableDeoptimize(frame_state, parameters);
  }
Deoptimize() [2/2]
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Deoptimize (V< turboshaft::FrameState > frame_state, DeoptimizeReason reason, const FeedbackSource & feedback) [inline]
Definition at line 4095 of file assembler.h.
                                                                           {
    if (V8_UNLIKELY(Asm().generating_unreachable_operations())) {
      return;
    }
    Zone* zone = Asm().output_graph().graph_zone();
    const DeoptimizeParameters* params =
        zone->New<DeoptimizeParameters>(reason, feedback);
    Deoptimize(frame_state, params);
  }
References v8::internal::Zone::New(), and V8_UNLIKELY.
DeoptimizeIf() [1/2]
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DeoptimizeIf (V< Word32 > condition, V< turboshaft::FrameState > frame_state, const DeoptimizeParameters * parameters) [inline]
Definition at line 4060 of file assembler.h.
                                                            {
    ReduceIfReachableDeoptimizeIf(condition, frame_state, false, parameters);
  }
DeoptimizeIf() [2/2]
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DeoptimizeIf (V< Word32 > condition, V< turboshaft::FrameState > frame_state, DeoptimizeReason reason, const FeedbackSource & feedback) [inline]
Definition at line 4069 of file assembler.h.
                                                                             {
    if (V8_UNLIKELY(Asm().generating_unreachable_operations())) {
      return;
    }
    Zone* zone = Asm().output_graph().graph_zone();
    const DeoptimizeParameters* params =
        zone->New<DeoptimizeParameters>(reason, feedback);
    DeoptimizeIf(condition, frame_state, params);
  }
References v8::internal::Zone::New(), and V8_UNLIKELY.
DeoptimizeIfNot() [1/2]
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DeoptimizeIfNot (V< Word32 > condition, V< turboshaft::FrameState > frame_state, const DeoptimizeParameters * parameters) [inline]
Definition at line 4064 of file assembler.h.
                                                               {
    ReduceIfReachableDeoptimizeIf(condition, frame_state, true, parameters);
  }
DeoptimizeIfNot() [2/2]
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DeoptimizeIfNot (V< Word32 > condition, V< turboshaft::FrameState > frame_state, DeoptimizeReason reason, const FeedbackSource & feedback) [inline]
Definition at line 4079 of file assembler.h.
                                                       {
    if (V8_UNLIKELY(Asm().generating_unreachable_operations())) {
      return;
    }
    Zone* zone = Asm().output_graph().graph_zone();
    const DeoptimizeParameters* params =
        zone->New<DeoptimizeParameters>(reason, feedback);
    DeoptimizeIfNot(condition, frame_state, params);
  }
References v8::internal::Zone::New(), and V8_UNLIKELY.
DoubleArrayMax()
template<typename Assembler >
V<Number> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DoubleArrayMax (V< JSArray > array) [inline]
Definition at line 4444 of file assembler.h.
                                             {
    return DoubleArrayMinMax(array, DoubleArrayMinMaxOp::Kind::kMax);
  }
DoubleArrayMin()
template<typename Assembler >
V<Number> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DoubleArrayMin (V< JSArray > array) [inline]
Definition at line 4441 of file assembler.h.
                                             {
    return DoubleArrayMinMax(array, DoubleArrayMinMaxOp::Kind::kMin);
  }
DoubleArrayMinMax()
template<typename Assembler >
V<Number> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DoubleArrayMinMax (V< JSArray > array, DoubleArrayMinMaxOp::Kind kind) [inline]
Definition at line 4437 of file assembler.h.
                                                            {
    return ReduceIfReachableDoubleArrayMinMax(array, kind);
  }
EnsureWritableFastElements()
template<typename Assembler >
V<Object> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::EnsureWritableFastElements (V< Object > object, V< Object > elements) [inline]
Definition at line 4765 of file assembler.h.
                                                                             {
    return ReduceIfReachableEnsureWritableFastElements(object, elements);
  }
Equal()
template<typename Assembler >
V<Word32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Equal (V< Any > left, V< Any > right, RegisterRepresentation rep) [inline]
Definition at line 1803 of file assembler.h.
                                                                         {
    return Comparison(left, right, ComparisonOp::Kind::kEqual, rep);
  }
References v8::internal::kEqual.
ExternalConstant()
template<typename Assembler >
OpIndex v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ExternalConstant (ExternalReference value) [inline]
Definition at line 2382 of file assembler.h.
                                                    {
    return ReduceIfReachableConstant(ConstantOp::Kind::kExternal, value);
  }
References v8::internal::value.
FailAssert()
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::FailAssert (const char * message, const std::vector< FileAndLine > & files_and_lines, const SourceLocation & loc) [inline]
Definition at line 4240 of file assembler.h.
                                             {
    std::stringstream stream;
    if (message) stream << message;
    for (auto it = files_and_lines.rbegin(); it != files_and_lines.rend();
         ++it) {
      if (it->first != nullptr) {
        stream << " [" << it->first << ":" << it->second << "]";
#ifndef DEBUG
        // To limit the size of these strings in release builds, we include only
        // the innermost macro's file name and line number.
        break;
#endif
      }
    }
    Isolate* isolate = Asm().data()->isolate();
    DCHECK_NOT_NULL(isolate);
    DCHECK_EQ(ThreadId::Current(), isolate->thread_id());
    V<String> string_constant =
        __ HeapConstantNoHole(isolate->factory()->NewStringFromAsciiChecked(
            stream.str().c_str(), AllocationType::kOld));
    AbortCSADcheck(string_constant);
    Unreachable();
  }
References __, v8::internal::ThreadId::Current(), DCHECK_EQ, DCHECK_NOT_NULL, v8::internal::Isolate::factory(), v8::internal::compiler::HeapConstantNoHole(), v8::internal::Factory::isolate(), v8::internal::kOld, v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), and v8::internal::Isolate::thread_id().
FastApiCall()
template<typename Assembler >
OpIndex v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::FastApiCall (V< turboshaft::FrameState > frame_state, V< Object > data_argument, V< Context > context, base::Vector< const OpIndex > arguments, const FastApiCallParameters * parameters, base::Vector< const RegisterRepresentation > out_reps) [inline]
Definition at line 4752 of file assembler.h.
                                                                         {
    return ReduceIfReachableFastApiCall(frame_state, data_argument, context,
                                        arguments, parameters, out_reps);
  }
FindOrderedHashEntry()
template<typename Assembler >
OpIndex v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::FindOrderedHashEntry (V< Object > data_structure, OpIndex key, FindOrderedHashEntryOp::Kind kind) [inline]
Definition at line 4789 of file assembler.h.
                                                                {
    return ReduceIfReachableFindOrderedHashEntry(data_structure, key, kind);
  }
References v8::internal::key.
FindOrderedHashMapEntry()
template<typename Assembler >
V<Smi> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::FindOrderedHashMapEntry (V< Object > table, V< Smi > key) [inline]
Definition at line 4793 of file assembler.h.
                                                              {
    return FindOrderedHashEntry(
        table, key, FindOrderedHashEntryOp::Kind::kFindOrderedHashMapEntry);
  }
References v8::internal::key.
FindOrderedHashMapEntryForInt32Key()
template<typename Assembler >
V<WordPtr> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::FindOrderedHashMapEntryForInt32Key (V< Object > table, V< Word32 > key) [inline]
Definition at line 4801 of file assembler.h.
                                                               {
    return FindOrderedHashEntry(
        table, key,
        FindOrderedHashEntryOp::Kind::kFindOrderedHashMapEntryForInt32Key);
  }
References v8::internal::key.
FindOrderedHashSetEntry()
template<typename Assembler >
V<Smi> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::FindOrderedHashSetEntry (V< Object > table, V< Smi > key) [inline]
Definition at line 4797 of file assembler.h.
                                                              {
    return FindOrderedHashEntry(
        table, key, FindOrderedHashEntryOp::Kind::kFindOrderedHashSetEntry);
  }
References v8::internal::key.
FinishInitialization()
template<typename Assembler >
template<typename T >
V<T> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::FinishInitialization (Uninitialized< T > && uninitialized) [inline]
Definition at line 3184 of file assembler.h.
                                                              {
    DCHECK(in_object_initialization_);
    in_object_initialization_ = false;
    return uninitialized.ReleaseObject();
  }
References v8::internal::DCHECK().
Float32Constant() [1/2]
template<typename Assembler >
V<Float32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Float32Constant (float value) [inline]
Definition at line 2295 of file assembler.h.
                                          {
    // Passing the NaN Hole as input is allowed, but there is no guarantee that
    // it will remain a hole (it will remain NaN though).
    if (std::isnan(value)) {
      return Float32Constant(
          i::Float32::FromBits(base::bit_cast<uint32_t>(value)));
    } else {
      return Float32Constant(i::Float32(value));
    }
  }
References v8::internal::Float32::FromBits(), and v8::internal::value.
Float32Constant() [2/2]
template<typename Assembler >
V<Float32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Float32Constant (i::Float32 value) [inline]
Definition at line 2292 of file assembler.h.
                                             {
    return ReduceIfReachableConstant(ConstantOp::Kind::kFloat32, value);
  }
References v8::internal::value.
Float64Constant() [1/2]
template<typename Assembler >
V<Float64> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Float64Constant (double value) [inline]
Definition at line 2308 of file assembler.h.
                                           {
    // Passing the NaN Hole as input is allowed, but there is no guarantee that
    // it will remain a hole (it will remain NaN though).
    if (std::isnan(value)) {
      return Float64Constant(
          i::Float64::FromBits(base::bit_cast<uint64_t>(value)));
    } else {
      return Float64Constant(i::Float64(value));
    }
  }
References v8::internal::Float64::FromBits(), and v8::internal::value.
Float64Constant() [2/2]
template<typename Assembler >
V<Float64> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Float64Constant (i::Float64 value) [inline]
Definition at line 2305 of file assembler.h.
                                             {
    return ReduceIfReachableConstant(ConstantOp::Kind::kFloat64, value);
  }
References v8::internal::value.
Float64Is()
template<typename Assembler >
V<Word32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Float64Is (V< Float64 > input, NumericKind kind) [inline]
Definition at line 2114 of file assembler.h.
                                                          {
    return ReduceIfReachableFloat64Is(input, kind);
  }
Float64IsHole()
template<typename Assembler >
V<Word32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Float64IsHole (V< Float64 > input) [inline]
Definition at line 2120 of file assembler.h.
                                            {
    return Float64Is(input, NumericKind::kFloat64Hole);
  }
Float64IsNaN()
template<typename Assembler >
V<Word32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Float64IsNaN (V< Float64 > input) [inline]
Definition at line 2117 of file assembler.h.
                                           {
    return Float64Is(input, NumericKind::kNaN);
  }
References v8::internal::compiler::turboshaft::kNaN.
Float64IsSmi()
template<typename Assembler >
V<Word32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Float64IsSmi (V< Float64 > input) [inline]
Definition at line 2129 of file assembler.h.
                                           {
    return Float64Is(input, NumericKind::kSmi);
  }
References v8::internal::compiler::turboshaft::kSmi.
Float64SameValue()
template<typename Assembler >
V<Word32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Float64SameValue (ConstOrV< Float64 > left, ConstOrV< Float64 > right) [inline]
Definition at line 4748 of file assembler.h.
                                                                              {
    return ReduceIfReachableFloat64SameValue(resolve(left), resolve(right));
  }
Float64Unary()
template<typename Assembler >
V<Float64> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Float64Unary (V< Float64 > input, FloatUnaryOp::Kind kind) [inline]
Definition at line 1888 of file assembler.h.
                                                                   {
    return ReduceIfReachableFloatUnary(input, kind,
                                       FloatRepresentation::Float64());
  }
References v8::internal::compiler::turboshaft::FloatRepresentation::Float64().
FloatConstant()
template<typename Assembler >
OpIndex v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::FloatConstant (double value, FloatRepresentation rep) [inline]
Definition at line 2318 of file assembler.h.
                                                               {
    // Passing the NaN Hole as input is allowed, but there is no guarantee that
    // it will remain a hole (it will remain NaN though).
    switch (rep.value()) {
      case FloatRepresentation::Float32():
        return Float32Constant(static_cast<float>(value));
      case FloatRepresentation::Float64():
        return Float64Constant(value);
    }
  }
References v8::internal::compiler::turboshaft::FloatRepresentation::Float32(), v8::internal::compiler::turboshaft::FloatRepresentation::Float64(), v8::internal::compiler::turboshaft::FloatRepresentation::value(), and v8::internal::value.
FloatUnary()
template<typename Assembler >
V<Float> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::FloatUnary (V< Float > input, FloatUnaryOp::Kind kind, FloatRepresentation rep) [inline]
Definition at line 1884 of file assembler.h.
                                               {
    return ReduceIfReachableFloatUnary(input, kind, rep);
  }
FramePointer()
template<typename Assembler >
V<WordPtr> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::FramePointer () [inline]
Definition at line 3236 of file assembler.h.
                            {
    return ReduceIfReachableFrameConstant(FrameConstantOp::Kind::kFramePointer);
  }
FrameState()
template<typename Assembler >
V<turboshaft::FrameState> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::FrameState (base::Vector< const OpIndex > inputs, bool inlined, const FrameStateData * data) [inline]
Definition at line 4055 of file assembler.h.
                                                                   {
    return ReduceIfReachableFrameState(inputs, inlined, data);
  }
GenericBinop()
template<typename Assembler >
V<Object> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::GenericBinop (V< Object > left, V< Object > right, V< turboshaft::FrameState > frame_state, V< Context > context, GenericBinopOp::Kind kind, LazyDeoptOnThrow lazy_deopt_on_throw) [inline]
Definition at line 1547 of file assembler.h.
                                                               {
    return ReduceIfReachableGenericBinop(left, right, frame_state, context,
                                         kind, lazy_deopt_on_throw);
  }
GenericUnop()
template<typename Assembler >
V<Object> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::GenericUnop (V< Object > input, V< turboshaft::FrameState > frame_state, V< Context > context, GenericUnopOp::Kind kind, LazyDeoptOnThrow lazy_deopt_on_throw) [inline]
Definition at line 1564 of file assembler.h.
                                                              {
    return ReduceIfReachableGenericUnop(input, frame_state, context, kind,
                                        lazy_deopt_on_throw);
  }
GetElementStartPointer()
template<typename Assembler >
template<typename Base >
V<WordPtr> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::GetElementStartPointer (V< Base > object, const ElementAccess & access) [inline]
Definition at line 3117 of file assembler.h.
                                                                 {
    return WordPtrAdd(BitcastHeapObjectToWordPtr(object),
                      access.header_size - access.tag());
  }
References v8::internal::compiler::ElementAccess::header_size, and v8::internal::compiler::ElementAccess::tag().
Goto() [1/2]
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Goto (Block * destination) [inline]
Definition at line 4356 of file assembler.h.
                                {
    bool is_backedge = destination->IsBound();
    Goto(destination, is_backedge);
  }
References v8::internal::compiler::turboshaft::Block::IsBound().
Goto() [2/2]
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Goto (Block * destination, bool is_backedge) [inline]
Definition at line 4360 of file assembler.h.
                                                  {
    ReduceIfReachableGoto(destination, is_backedge);
  }
GotoIf() [1/2]
template<typename Assembler >
ConditionalGotoStatus v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::GotoIf (ConditionWithHint condition, Block * if_true) [inline]
Definition at line 4381 of file assembler.h.
                                                                            {
    return GotoIf(condition.condition(), if_true, condition.hint());
  }
References v8::internal::compiler::turboshaft::ConditionWithHint::condition(), and v8::internal::compiler::turboshaft::ConditionWithHint::hint().
GotoIf() [2/2]
template<typename Assembler >
ConditionalGotoStatus v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::GotoIf (V< Word32 > condition, Block * if_true, BranchHint hint = BranchHint::kNone) [inline]
Definition at line 4372 of file assembler.h.
                                                                  {
    if (V8_UNLIKELY(Asm().generating_unreachable_operations())) {
      // What we return here should not matter.
      return ConditionalGotoStatus::kBranch;
    }
    Block* if_false = Asm().NewBlock();
    return BranchAndBind(condition, if_true, if_false, hint, if_false);
  }
References v8::internal::compiler::turboshaft::kBranch, and V8_UNLIKELY.
GotoIfNot() [1/2]
template<typename Assembler >
ConditionalGotoStatus v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::GotoIfNot (ConditionWithHint condition, Block * if_false) [inline]
Definition at line 4395 of file assembler.h.
                                                   {
    return GotoIfNot(condition.condition(), if_false, condition.hint());
  }
References v8::internal::compiler::turboshaft::ConditionWithHint::condition(), and v8::internal::compiler::turboshaft::ConditionWithHint::hint().
GotoIfNot() [2/2]
template<typename Assembler >
ConditionalGotoStatus v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::GotoIfNot (V< Word32 > condition, Block * if_false, BranchHint hint = BranchHint::kNone) [inline]
Definition at line 4385 of file assembler.h.
                                                                     {
    if (V8_UNLIKELY(Asm().generating_unreachable_operations())) {
      // What we return here should not matter.
      return ConditionalGotoStatus::kBranch;
    }
    Block* if_true = Asm().NewBlock();
    return BranchAndBind(condition, if_true, if_false, hint, if_true);
  }
References v8::internal::compiler::turboshaft::kBranch, and V8_UNLIKELY.
HasInstanceType()
template<typename Assembler >
V<Word32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::HasInstanceType (V< Object > object, InstanceType instance_type) [inline]
Definition at line 2996 of file assembler.h.
                                                                          {
    return Word32Equal(LoadInstanceTypeField(LoadMapField(object)),
                       Word32Constant(instance_type));
  }
References v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal().
HeapConstant() [1/2]
template<typename Assembler >
template<typename T >
V<T> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::HeapConstant (Handle< T > value)
HeapConstant() [2/2]
template<typename Assembler >
return __ v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::HeapConstant (value)
HeapConstantHole()
template<typename Assembler >
V<HeapObject> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::HeapConstantHole (Handle< HeapObject > value) [inline]
Definition at line 2367 of file assembler.h.
                                                           {
    DCHECK(IsAnyHole(*value));
    return __ HeapConstant(value);
  }
References __, v8::internal::DCHECK(), v8::internal::IsAnyHole(), and v8::internal::value.
HeapConstantMaybeHole()
template<typename Assembler >
template<typename T >
V<T> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::HeapConstantMaybeHole (Handle< T > value)
References __, and v8::internal::value.
HeapConstantNoHole()
template<typename Assembler >
template<typename T >
V<T> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::HeapConstantNoHole (Handle< T > value)
References CHECK, v8::internal::IsAnyHole(), and v8::internal::value.
Initialize()
template<typename Assembler >
template<typename T >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Initialize (Uninitialized< T > & object, OpIndex value, MemoryRepresentation stored_rep, WriteBarrierKind write_barrier, int32_t offset = 0) [inline]
Definition at line 2908 of file assembler.h.
                                                                      {
    return Store(object.object(), value,
                 StoreOp::Kind::Aligned(BaseTaggedness::kTaggedBase),
                 stored_rep, write_barrier, offset, true);
  }
References v8::internal::compiler::kTaggedBase, v8::internal::wasm::liftoff::Store(), and v8::internal::value.
InitializeArrayBufferElement()
template<typename Assembler >
template<typename Base >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::InitializeArrayBufferElement (Uninitialized< Base > & object, const ElementAccess & access, V< WordPtr > index, V< Any > value) [inline]
Definition at line 3151 of file assembler.h.
                                                                    {
    StoreArrayBufferElement(object.object(), access, index, value);
  }
References v8::internal::index, and v8::internal::value.
InitializeElement()
template<typename Assembler >
template<typename Class , typename T >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::InitializeElement (Uninitialized< Class > & object, const ElementAccessTS< Class, T > & access, ConstOrV< WordPtr > index, V< T > value) [inline]
Definition at line 3141 of file assembler.h.
                                                              {
    StoreElement(object.object(), access, index, value,
                 access.is_array_buffer_load);
  }
References v8::internal::index, v8::internal::compiler::turboshaft::ElementAccessTS< Class, T >::is_array_buffer_load, and v8::internal::value.
InitializeField() [1/2]
template<typename Assembler >
template<typename Object , typename Class , typename T >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::InitializeField (Uninitialized< Object > & object, const FieldAccessTS< Class, T > & access, maybe_const_or_v_t< T > value) [inline]
Definition at line 3021 of file assembler.h.
                                                    {
    static_assert(is_subtype_v<Object, Class>);
    StoreFieldImpl(object.object(), access, resolve(value), true);
  }
References v8::internal::value.
InitializeField() [2/2]
template<typename Assembler >
template<typename T >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::InitializeField (Uninitialized< T > & object, const FieldAccess & access, V< Any > value) [inline]
Definition at line 3031 of file assembler.h.
                                     {
    StoreFieldImpl(object.object(), access, value, true);
  }
References v8::internal::value.
InitializeNonArrayBufferElement()
template<typename Assembler >
template<typename Base >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::InitializeNonArrayBufferElement (Uninitialized< Base > & object, const ElementAccess & access, V< WordPtr > index, V< Any > value) [inline]
Definition at line 3159 of file assembler.h.
                                                                       {
    StoreNonArrayBufferElement(object.object(), access, index, value);
  }
References v8::internal::index, and v8::internal::value.
IntPtrConstant()
template<typename Assembler >
V<WordPtr> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::IntPtrConstant (intptr_t value) [inline]
Definition at line 2283 of file assembler.h.
                                            {
    return UintPtrConstant(static_cast<uintptr_t>(value));
  }
References v8::internal::value.
IsolateField()
template<typename Assembler >
OpIndex v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::IsolateField (IsolateFieldId id) [inline]
Definition at line 2385 of file assembler.h.
                                          {
    return ExternalConstant(ExternalReference::Create(id));
  }
References v8::internal::ExternalReference::Create().
IsSmi()
template<typename Assembler >
V<Word32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::IsSmi (V< Object > object) [inline]
Definition at line 2539 of file assembler.h.
                                    {
    if constexpr (COMPRESS_POINTERS_BOOL) {
      return Word32Equal(Word32BitwiseAnd(V<Word32>::Cast(object), kSmiTagMask),
                         kSmiTag);
    } else {
      return WordPtrEqual(
          WordPtrBitwiseAnd(V<WordPtr>::Cast(object), kSmiTagMask), kSmiTag);
    }
  }
References COMPRESS_POINTERS_BOOL, v8::internal::kSmiTag, v8::internal::kSmiTagMask, and v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal().
JSFunctionEntryStackCheck()
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::JSFunctionEntryStackCheck (V< Context > context, V< turboshaft::FrameState > frame_state) [inline]
Definition at line 3221 of file assembler.h.
                                                                      {
    JSStackCheck(context, frame_state, JSStackCheckOp::Kind::kFunctionEntry);
  }
JSLoopStackCheck()
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::JSLoopStackCheck (V< Context > context, V< turboshaft::FrameState > frame_state) [inline]
Definition at line 3217 of file assembler.h.
                                                             {
    JSStackCheck(context, frame_state, JSStackCheckOp::Kind::kLoop);
  }
JSStackCheck()
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::JSStackCheck (V< Context > context, OptionalV< turboshaft::FrameState > frame_state, JSStackCheckOp::Kind kind) [inline]
Definition at line 3211 of file assembler.h.
                                             {
    ReduceIfReachableJSStackCheck(context, frame_state, kind);
  }
Load() [1/3]
template<typename Assembler >
OpIndex v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Load (OpIndex base, LoadOp::Kind kind, MemoryRepresentation loaded_rep, int32_t offset = 0) [inline]
Definition at line 2759 of file assembler.h.
                                   {
    return Load(base, OpIndex::Invalid(), kind, loaded_rep, offset);
  }
References v8::internal::compiler::turboshaft::OpIndex::Invalid(), and v8::Load().
Load() [2/3]
template<typename Assembler >
OpIndex v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Load (OpIndex base, OptionalOpIndex index, LoadOp::Kind kind, MemoryRepresentation loaded_rep, int32_t offset = 0, uint8_t element_size_log2 = 0) [inline]
Definition at line 2752 of file assembler.h.
                                              {
    return Load(base, index, kind, loaded_rep,
                loaded_rep.ToRegisterRepresentation(), offset,
                element_size_log2);
  }
References v8::internal::index, v8::Load(), and v8::internal::compiler::turboshaft::MemoryRepresentation::ToRegisterRepresentation().
Load() [3/3]
template<typename Assembler >
OpIndex v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Load (OpIndex base, OptionalOpIndex index, LoadOp::Kind kind, MemoryRepresentation loaded_rep, RegisterRepresentation result_rep, int32_t offset = 0, uint8_t element_size_log2 = 0) [inline]
Definition at line 2744 of file assembler.h.
                                              {
    return ReduceIfReachableLoad(base, index, kind, loaded_rep, result_rep,
                                 offset, element_size_log2);
  }
References v8::internal::index.
Referenced by v8::internal::wasm::WasmWrapperTSGraphBuilder::ModifyThreadInWasmFlagScope::ModifyThreadInWasmFlagScope().
LoadArrayBufferElement()
template<typename Assembler >
template<typename T = Any, typename Base >
V<T> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadArrayBufferElement (V< Base > object, const ElementAccess & access, V< WordPtr > index) [inline]
Definition at line 3105 of file assembler.h.
                                                {
    return LoadElement<T>(object, access, index, true);
  }
References v8::internal::index.
LoadDataViewElement()
template<typename Assembler >
OpIndex v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadDataViewElement (V< Object > object, V< WordPtr > storage, V< WordPtr > index, V< Word32 > is_little_endian, ExternalArrayType element_type) [inline]
Definition at line 4653 of file assembler.h.
                                                              {
    return ReduceIfReachableLoadDataViewElement(object, storage, index,
                                                is_little_endian, element_type);
  }
References v8::internal::index.
LoadElement() [1/2]
template<typename Assembler >
template<typename T = Any, typename Base >
V<T> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadElement (V< Base > object, const ElementAccess & access, V< WordPtr > index, bool is_array_buffer) [inline], [private]
Definition at line 5264 of file assembler.h.
                                                           {
    if constexpr (is_taggable_v<Base>) {
      DCHECK_EQ(access.base_is_tagged, BaseTaggedness::kTaggedBase);
    } else {
      static_assert(std::is_same_v<Base, WordPtr>);
      DCHECK_EQ(access.base_is_tagged, BaseTaggedness::kUntaggedBase);
    }
    LoadOp::Kind kind = LoadOp::Kind::Aligned(access.base_is_tagged);
    if (is_array_buffer) kind = kind.NotLoadEliminable();
    MemoryRepresentation rep =
        MemoryRepresentation::FromMachineType(access.machine_type);
    return Load(object, index, kind, rep, access.header_size,
                rep.SizeInBytesLog2());
  }
References v8::internal::compiler::ElementAccess::base_is_tagged, DCHECK_EQ, v8::internal::compiler::turboshaft::MemoryRepresentation::FromMachineType(), v8::internal::compiler::ElementAccess::header_size, v8::internal::index, v8::internal::compiler::kTaggedBase, v8::internal::compiler::kUntaggedBase, v8::Load(), v8::internal::compiler::ElementAccess::machine_type, v8::internal::compiler::turboshaft::LoadOp::Kind::NotLoadEliminable(), and v8::internal::compiler::turboshaft::MemoryRepresentation::SizeInBytesLog2().
LoadElement() [2/2]
template<typename Assembler >
template<typename Class , typename T >
V<T> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadElement (V< Class > object, const ElementAccessTS< Class, T > & access, V< WordPtr > index) [inline]
Definition at line 3097 of file assembler.h.
                                     {
    return LoadElement<T>(object, access, index, access.is_array_buffer_load);
  }
References v8::internal::index, and v8::internal::compiler::turboshaft::ElementAccessTS< Class, T >::is_array_buffer_load.
LoadExternalPointerFromObject()
template<typename Assembler >
V<WordPtr> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadExternalPointerFromObject (V< Object > object, int offset, ExternalPointerTag tag) [inline]
Definition at line 2835 of file assembler.h.
                                                                   {
#ifdef V8_ENABLE_SANDBOX
    V<Word32> handle = __ Load(object, LoadOp::Kind::TaggedBase(),
                               MemoryRepresentation::Uint32(), offset);
    return __ DecodeExternalPointer(handle, tag);
#else
    return __ Load(object, LoadOp::Kind::TaggedBase(),
                   MemoryRepresentation::UintPtr(), offset);
#endif // V8_ENABLE_SANDBOX
  }
References __, v8::internal::handle(), v8::Load(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint32(), and v8::internal::compiler::turboshaft::MemoryRepresentation::UintPtr().
LoadField() [1/3]
template<typename Assembler >
template<typename Obj , typename Class , typename T >
V<T> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadField (V< Obj > object, const FieldAccessTS< Class, T > & field) [inline]
Definition at line 2940 of file assembler.h.
                                          {
    return LoadFieldImpl<T>(object, field);
  }
  template <typename Rep>
  V<Rep> LoadFieldImpl(OpIndex object, const compiler::FieldAccess& access) {
    MachineType machine_type = access.machine_type;
    if (machine_type.IsMapWord()) {
      machine_type = MachineType::TaggedPointer();
#ifdef V8_MAP_PACKING
      UNIMPLEMENTED();
#endif
    }
    MemoryRepresentation rep =
        MemoryRepresentation::FromMachineType(machine_type);
#ifdef V8_ENABLE_SANDBOX
    bool is_sandboxed_external =
        access.type.Is(compiler::Type::ExternalPointer());
    if (is_sandboxed_external) {
      // Fields for sandboxed external pointer contain a 32-bit handle, not a
      // 64-bit raw pointer.
      rep = MemoryRepresentation::Uint32();
    }
#endif // V8_ENABLE_SANDBOX
    LoadOp::Kind kind = LoadOp::Kind::Aligned(access.base_is_tagged);
    if (access.is_immutable) {
      kind = kind.Immutable();
    }
    V<Rep> value = Load(object, kind, rep, access.offset);
#ifdef V8_ENABLE_SANDBOX
    if (is_sandboxed_external) {
      value = V<Rep>::Cast(DecodeExternalPointer(V<Word32>::Cast(value),
                                                 access.external_pointer_tag));
    }
    if (access.is_bounded_size_access) {
      DCHECK(!is_sandboxed_external);
      value = V<Rep>::Cast(ShiftRightLogical(V<WordPtr>::Cast(value),
                                             kBoundedSizeShift,
                                             WordRepresentation::WordPtr()));
    }
#endif // V8_ENABLE_SANDBOX
    return value;
  }
LoadField() [2/3]
template<typename Assembler >
template<typename Rep = Any>
V<Rep> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadField (V< Object > object, const compiler::FieldAccess & access) [inline]
Definition at line 2928 of file assembler.h.
                                                                        {
    DCHECK_EQ(access.base_is_tagged, BaseTaggedness::kTaggedBase);
    return LoadFieldImpl<Rep>(object, access);
  }
References v8::internal::compiler::FieldAccess::base_is_tagged, DCHECK_EQ, and v8::internal::compiler::kTaggedBase.
LoadField() [3/3]
template<typename Assembler >
template<typename Rep = Any>
V<Rep> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadField (V< WordPtr > raw_base, const compiler::FieldAccess & access) [inline]
Definition at line 2934 of file assembler.h.
                                                                           {
    DCHECK_EQ(access.base_is_tagged, BaseTaggedness::kUntaggedBase);
    return LoadFieldImpl<Rep>(raw_base, access);
  }
References v8::internal::compiler::FieldAccess::base_is_tagged, DCHECK_EQ, and v8::internal::compiler::kUntaggedBase.
LoadFieldByIndex()
template<typename Assembler >
V<Any> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadFieldByIndex (V< Object > object, V< Word32 > index) [inline]
Definition at line 4448 of file assembler.h.
                                                             {
    return ReduceIfReachableLoadFieldByIndex(object, index);
  }
References v8::internal::index.
LoadFixedArrayElement() [1/2]
template<typename Assembler >
V<Object> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadFixedArrayElement (V< FixedArray > array, int index) [inline]
Definition at line 2847 of file assembler.h.
                                                                  {
    return Load(array, LoadOp::Kind::TaggedBase(),
                MemoryRepresentation::AnyTagged(),
                FixedArray::OffsetOfElementAt(index));
  }
References v8::internal::compiler::turboshaft::MemoryRepresentation::AnyTagged(), v8::internal::index, v8::Load(), and v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::OffsetOfElementAt().
LoadFixedArrayElement() [2/2]
template<typename Assembler >
V<Object> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadFixedArrayElement (V< FixedArray > array, V< WordPtr > index) [inline]
Definition at line 2852 of file assembler.h.
                                                                         {
    return Load(array, index, LoadOp::Kind::TaggedBase(),
                MemoryRepresentation::AnyTagged(),
                FixedArray::OffsetOfElementAt(0), kTaggedSizeLog2);
  }
References v8::internal::compiler::turboshaft::MemoryRepresentation::AnyTagged(), v8::internal::index, v8::internal::kTaggedSizeLog2, v8::Load(), and v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::OffsetOfElementAt().
LoadFixedDoubleArrayElement() [1/2]
template<typename Assembler >
V<Float64> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadFixedDoubleArrayElement (V< FixedDoubleArray > array, int index) [inline]
Definition at line 2858 of file assembler.h.
                                                                               {
    return Load(array, LoadOp::Kind::TaggedBase(),
                MemoryRepresentation::Float64(),
                FixedDoubleArray::OffsetOfElementAt(index));
  }
References v8::internal::compiler::turboshaft::MemoryRepresentation::Float64(), v8::internal::index, v8::Load(), and v8::internal::PrimitiveArrayBase< FixedDoubleArray, FixedDoubleArrayShape >::OffsetOfElementAt().
LoadFixedDoubleArrayElement() [2/2]
template<typename Assembler >
V<Float64> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadFixedDoubleArrayElement (V< FixedDoubleArray > array, V< WordPtr > index) [inline]
Definition at line 2863 of file assembler.h.
                                                           {
    static_assert(ElementsKindToShiftSize(PACKED_DOUBLE_ELEMENTS) ==
                  ElementsKindToShiftSize(HOLEY_DOUBLE_ELEMENTS));
    return Load(array, index, LoadOp::Kind::TaggedBase(),
                MemoryRepresentation::Float64(),
                FixedDoubleArray::OffsetOfElementAt(0),
                ElementsKindToShiftSize(PACKED_DOUBLE_ELEMENTS));
  }
References v8::internal::ElementsKindToShiftSize(), v8::internal::compiler::turboshaft::MemoryRepresentation::Float64(), v8::internal::HOLEY_DOUBLE_ELEMENTS, v8::internal::index, v8::Load(), v8::internal::PrimitiveArrayBase< FixedDoubleArray, FixedDoubleArrayShape >::OffsetOfElementAt(), and v8::internal::PACKED_DOUBLE_ELEMENTS.
LoadHeapNumberValue()
template<typename Assembler >
V<Float64> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadHeapNumberValue (V< HeapNumber > heap_number) [inline]
Definition at line 3001 of file assembler.h.
                                                            {
    return __ template LoadField<HeapNumber, HeapNumber, Float64>(
        heap_number, AccessBuilderTS::ForHeapNumberValue());
  }
References __.
LoadInstanceTypeField()
template<typename Assembler >
V<Word32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadInstanceTypeField (V< Map > map) [inline]
Definition at line 2992 of file assembler.h.
                                              {
    return LoadField<Word32>(map, AccessBuilder::ForMapInstanceType());
  }
LoadMapField()
template<typename Assembler >
V<Map> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadMapField (V< Object > object) [inline]
Definition at line 2988 of file assembler.h.
                                        {
    return LoadField<Map>(object, AccessBuilder::ForMap());
  }
LoadMessage()
template<typename Assembler >
V<Object> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadMessage (V< WordPtr > offset) [inline]
Definition at line 4735 of file assembler.h.
                                           {
    return ReduceIfReachableLoadMessage(offset);
  }
LoadNonArrayBufferElement()
template<typename Assembler >
template<typename T = Any, typename Base >
V<T> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadNonArrayBufferElement (V< Base > object, const ElementAccess & access, V< WordPtr > index) [inline]
Definition at line 3112 of file assembler.h.
                                                   {
    return LoadElement<T>(object, access, index, false);
  }
References v8::internal::index.
LoadOffHeap() [1/3]
template<typename Assembler >
OpIndex v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadOffHeap (OpIndex address, int32_t offset, MemoryRepresentation rep) [inline]
Definition at line 2766 of file assembler.h.
                                                {
    return Load(address, LoadOp::Kind::RawAligned(), rep, offset);
  }
References v8::Load().
LoadOffHeap() [2/3]
template<typename Assembler >
OpIndex v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadOffHeap (OpIndex address, MemoryRepresentation rep) [inline]
Definition at line 2763 of file assembler.h.
                                                                 {
    return LoadOffHeap(address, 0, rep);
  }
LoadOffHeap() [3/3]
template<typename Assembler >
OpIndex v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadOffHeap (OpIndex address, OptionalOpIndex index, int32_t offset, MemoryRepresentation rep) [inline]
Definition at line 2770 of file assembler.h.
                                                {
    return Load(address, index, LoadOp::Kind::RawAligned(), rep, offset,
                rep.SizeInBytesLog2());
  }
References v8::internal::index, v8::Load(), and v8::internal::compiler::turboshaft::MemoryRepresentation::SizeInBytesLog2().
LoadPageFlags()
template<typename Assembler >
V<WordPtr> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadPageFlags (V< HeapObject > object) [inline]
Definition at line 2669 of file assembler.h.
                                                 {
    V<WordPtr> header = MemoryChunkFromAddress(BitcastTaggedToWordPtr(object));
    return Load(header, {}, LoadOp::Kind::RawAligned(),
                MemoryRepresentation::UintPtr(), MemoryChunk::FlagsOffset());
  }
References v8::internal::MemoryChunk::FlagsOffset(), v8::Load(), and v8::internal::compiler::turboshaft::MemoryRepresentation::UintPtr().
LoadProtectedFixedArrayElement() [1/2]
template<typename Assembler >
V<Object> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadProtectedFixedArrayElement (V< ProtectedFixedArray > array, int index) [inline]
Definition at line 2879 of file assembler.h.
                                                      {
    return LoadProtectedPointerField(
        array, LoadOp::Kind::TaggedBase(),
        ProtectedFixedArray::OffsetOfElementAt(index));
  }
References v8::internal::index, and v8::internal::TaggedArrayBase< ProtectedFixedArray, ProtectedArrayShape, TrustedObjectLayout >::OffsetOfElementAt().
LoadProtectedFixedArrayElement() [2/2]
template<typename Assembler >
V<Object> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadProtectedFixedArrayElement (V< ProtectedFixedArray > array, V< WordPtr > index) [inline]
Definition at line 2873 of file assembler.h.
                                                             {
    return LoadProtectedPointerField(array, index, LoadOp::Kind::TaggedBase(),
                                     ProtectedFixedArray::OffsetOfElementAt(0));
  }
References v8::internal::index, and v8::internal::TaggedArrayBase< ProtectedFixedArray, ProtectedArrayShape, TrustedObjectLayout >::OffsetOfElementAt().
LoadProtectedPointerField() [1/2]
template<typename Assembler >
V<Object> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadProtectedPointerField (V< Object > base, LoadOp::Kind kind, int32_t offset) [inline]
Definition at line 2791 of file assembler.h.
                                                      {
    return LoadProtectedPointerField(base, OpIndex::Invalid(), kind, offset);
  }
References v8::internal::compiler::turboshaft::OpIndex::Invalid().
LoadProtectedPointerField() [2/2]
template<typename Assembler >
V<Object> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadProtectedPointerField (V< Object > base, OptionalV< WordPtr > index, LoadOp::Kind kind = LoadOp::Kind::TaggedBase(), int offset = 0, int element_size_log2 = kTaggedSizeLog2) [inline]
Definition at line 2778 of file assembler.h.
                                               {
    return Load(base, index, kind,
                V8_ENABLE_SANDBOX_BOOL
                    ? MemoryRepresentation::ProtectedPointer()
                    : MemoryRepresentation::AnyTagged(),
                offset, index.valid() ? element_size_log2 : 0);
  }
References v8::internal::compiler::turboshaft::MemoryRepresentation::AnyTagged(), v8::internal::index, v8::Load(), v8::internal::compiler::turboshaft::MemoryRepresentation::ProtectedPointer(), and V8_ENABLE_SANDBOX_BOOL.
LoadRoot()
template<typename Assembler >
V<Object> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadRoot (RootIndex root_index) [inline]
Definition at line 4808 of file assembler.h.
                                           {
    Isolate* isolate = __ data() -> isolate();
    DCHECK_NOT_NULL(isolate);
    if (RootsTable::IsImmortalImmovable(root_index)) {
      Handle<Object> root = isolate->root_handle(root_index);
      if (i::IsSmi(*root)) {
        return __ SmiConstant(Cast<Smi>(*root));
      } else {
        return HeapConstantMaybeHole(i::Cast<HeapObject>(root));
      }
    }
    // TODO(jgruber): In theory we could generate better code for this by
    // letting the macro assembler decide how to load from the roots list. In
    // most cases, it would boil down to loading from a fixed kRootRegister
    // offset.
    OpIndex isolate_root =
        __ ExternalConstant(ExternalReference::isolate_root(isolate));
    int offset = IsolateData::root_slot_offset(root_index);
    return __ LoadOffHeap(isolate_root, offset,
                          MemoryRepresentation::AnyTagged());
  }
References __, v8::internal::compiler::turboshaft::MemoryRepresentation::AnyTagged(), DCHECK_NOT_NULL, v8::internal::RootsTable::IsImmortalImmovable(), v8::internal::IsSmi(), v8::internal::Isolate::root_handle(), and v8::internal::IsolateData::root_slot_offset().
LoadRootRegister()
template<typename Assembler >
OpIndex v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadRootRegister () [inline]
Definition at line 3263 of file assembler.h.
{ return ReduceIfReachableLoadRootRegister(); }
Referenced by v8::internal::wasm::WasmWrapperTSGraphBuilder::ModifyThreadInWasmFlagScope::ModifyThreadInWasmFlagScope().
LoadStackArgument()
template<typename Assembler >
V<Object> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadStackArgument (V< Object > base, V< WordPtr > index) [inline]
Definition at line 4660 of file assembler.h.
                                                                {
    return ReduceIfReachableLoadStackArgument(base, index);
  }
References v8::internal::index.
LoadTaggedField()
template<typename Assembler >
template<typename Type = Object>
V<Type> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadTaggedField (V< Object > object, int field_offset)
LoadTrustedPointerField() [1/2]
template<typename Assembler >
V<Object> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadTrustedPointerField (V< HeapObject > base, LoadOp::Kind kind, IndirectPointerTag tag, int offset = 0) [inline]
Definition at line 2830 of file assembler.h.
                                                                            {
    return LoadTrustedPointerField(base, OpIndex::Invalid(), kind, tag, offset);
  }
References v8::internal::compiler::turboshaft::OpIndex::Invalid().
LoadTrustedPointerField() [2/2]
template<typename Assembler >
V<Object> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadTrustedPointerField (V< HeapObject > base, OptionalV< Word32 > index, LoadOp::Kind kind, IndirectPointerTag tag, int offset = 0) [inline]
Definition at line 2797 of file assembler.h.
                                                    {
#if V8_ENABLE_SANDBOX
    static_assert(COMPRESS_POINTERS_BOOL);
    V<Word32> handle =
        Load(base, index, kind, MemoryRepresentation::Uint32(), offset);
    V<Word32> table_index =
        Word32ShiftRightLogical(handle, kTrustedPointerHandleShift);
    V<Word64> table_offset = __ ChangeUint32ToUint64(
        Word32ShiftLeft(table_index, kTrustedPointerTableEntrySizeLog2));
    V<WordPtr> table =
        Load(LoadRootRegister(), LoadOp::Kind::RawAligned().Immutable(),
             MemoryRepresentation::UintPtr(),
             IsolateData::trusted_pointer_table_offset() +
                 Internals::kTrustedPointerTableBasePointerOffset);
    V<WordPtr> decoded_ptr =
        Load(table, table_offset, LoadOp::Kind::RawAligned(),
             MemoryRepresentation::UintPtr());
    // Untag the pointer and remove the marking bit in one operation.
    decoded_ptr =
        __ Word64BitwiseAnd(decoded_ptr, ~(tag | kTrustedPointerTableMarkBit));
    // Bitcast to tagged to this gets scanned by the GC properly.
    return BitcastWordPtrToTagged(decoded_ptr);
#else
    return Load(base, index, kind, MemoryRepresentation::TaggedPointer(),
                offset);
#endif // V8_ENABLE_SANDBOX
  }
References __, COMPRESS_POINTERS_BOOL, v8::internal::handle(), v8::internal::index, v8::internal::kTrustedPointerHandleShift, v8::internal::Internals::kTrustedPointerTableBasePointerOffset, v8::internal::kTrustedPointerTableEntrySizeLog2, v8::internal::kTrustedPointerTableMarkBit, v8::Load(), v8::internal::compiler::turboshaft::MemoryRepresentation::TaggedPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint32(), and v8::internal::compiler::turboshaft::MemoryRepresentation::UintPtr().
LoadTypedElement()
template<typename Assembler >
OpIndex v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::LoadTypedElement (OpIndex buffer, V< Object > base, V< WordPtr > external, V< WordPtr > index, ExternalArrayType array_type) [inline]
Definition at line 4647 of file assembler.h.
                                                                           {
    return ReduceIfReachableLoadTypedElement(buffer, base, external, index,
                                             array_type);
  }
References v8::internal::index.
matcher()
template<typename Assembler >
const OperationMatcher& v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::matcher () const [inline]
Definition at line 1531 of file assembler.h.
{ return matcher_; }
MaybeGrowFastElements()
template<typename Assembler >
V<Object> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::MaybeGrowFastElements (V< Object > object, V< Object > elements, V< Word32 > index, V< Word32 > elements_length, V< turboshaft::FrameState > frame_state, GrowFastElementsMode mode, const FeedbackSource & feedback) [inline]
Definition at line 4769 of file assembler.h.
                                                                  {
    return ReduceIfReachableMaybeGrowFastElements(
        object, elements, index, elements_length, frame_state, mode, feedback);
  }
References v8::internal::index, and mode().
MemoryBarrier()
template<typename Assembler >
OpIndex v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::MemoryBarrier (AtomicMemoryOrder memory_order) [inline]
Definition at line 2740 of file assembler.h.
                                                        {
    return ReduceIfReachableMemoryBarrier(memory_order);
  }
MemoryChunkFromAddress()
template<typename Assembler >
V<WordPtr> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::MemoryChunkFromAddress (V< WordPtr > address) [inline]
Definition at line 2675 of file assembler.h.
                                                        {
    return WordPtrBitwiseAnd(address,
                             ~MemoryChunk::GetAlignmentMaskForAssembler());
  }
References v8::internal::MemoryChunk::GetAlignmentMaskForAssembler().
NewArgumentsElements()
template<typename Assembler >
V<FixedArray> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::NewArgumentsElements (V< Smi > arguments_count, CreateArgumentsType type, int formal_parameter_count) [inline]
Definition at line 4639 of file assembler.h.
                                                                 {
    DCHECK_LE(0, formal_parameter_count);
    return ReduceIfReachableNewArgumentsElements(arguments_count, type,
                                                 formal_parameter_count);
  }
References DCHECK_LE, and v8::internal::tracing::type.
NewArray()
template<typename Assembler >
V<AnyFixedArray> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::NewArray (V< WordPtr > length, NewArrayOp::Kind kind, AllocationType allocation_type) [inline]
Definition at line 4427 of file assembler.h.
                                                            {
    return ReduceIfReachableNewArray(length, kind, allocation_type);
  }
References v8::internal::length.
NewConsString()
template<typename Assembler >
V<ConsString> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::NewConsString (V< Word32 > length, V< String > first, V< String > second) [inline]
Definition at line 4423 of file assembler.h.
                                                {
    return ReduceIfReachableNewConsString(length, first, second);
  }
References v8::internal::length.
NewDoubleArray()
template<typename Assembler >
V<FixedDoubleArray> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::NewDoubleArray (V< WordPtr > length, AllocationType allocation_type) [inline]
Definition at line 4431 of file assembler.h.
                                                                     {
    return V<FixedDoubleArray>::Cast(
        NewArray(length, NewArrayOp::Kind::kDouble, allocation_type));
  }
References v8::internal::compiler::turboshaft::V< T >::Cast(), v8::internal::length, and v8::internal::NewArray().
NoContextConstant()
template<typename Assembler >
V<Context> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::NoContextConstant () [inline]
Definition at line 2413 of file assembler.h.
                                 {
    return V<Context>::Cast(TagSmi(Context::kNoContext));
  }
References v8::internal::compiler::turboshaft::V< T >::Cast(), and v8::internal::Context::kNoContext.
NumberConstant() [1/2]
template<typename Assembler >
OpIndex v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::NumberConstant (double value) [inline]
Definition at line 2331 of file assembler.h.
                                       {
    // Passing the NaN Hole as input is allowed, but there is no guarantee that
    // it will remain a hole (it will remain NaN though).
    if (std::isnan(value)) {
      return NumberConstant(
          i::Float64::FromBits(base::bit_cast<uint64_t>(value)));
    } else {
      return NumberConstant(i::Float64(value));
    }
  }
References v8::internal::Float64::FromBits(), v8::internal::compiler::NumberConstant(), and v8::internal::value.
NumberConstant() [2/2]
template<typename Assembler >
OpIndex v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::NumberConstant (i::Float64 value) [inline]
Definition at line 2328 of file assembler.h.
                                         {
    return ReduceIfReachableConstant(ConstantOp::Kind::kNumber, value);
  }
References v8::internal::value.
ObjectIs()
template<typename Assembler >
V<Word32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ObjectIs (V< Object > input, ObjectIsOp::Kind kind, ObjectIsOp::InputAssumptions input_assumptions) [inline]
Definition at line 2084 of file assembler.h.
                                                                   {
    return ReduceIfReachableObjectIs(input, kind, input_assumptions);
  }
ObjectIsNumericValue()
template<typename Assembler >
V<Word32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ObjectIsNumericValue (V< Object > input, NumericKind kind, FloatRepresentation input_rep) [inline]
Definition at line 2133 of file assembler.h.
                                                                {
    return ReduceIfReachableObjectIsNumericValue(input, kind, input_rep);
  }
OsrValue()
template<typename Assembler >
V<Object> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::OsrValue (int index) [inline]
Definition at line 3335 of file assembler.h.
{ return ReduceIfReachableOsrValue(index); }
References v8::internal::index.
OverflowCheckedBinop()
template<typename Assembler >
V<turboshaft::Tuple<Word, Word32> > v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::OverflowCheckedBinop (V< Word > left, V< Word > right, OverflowCheckedBinopOp::Kind kind, WordRepresentation rep) [inline]
Definition at line 1681 of file assembler.h.
                              {
    return ReduceIfReachableOverflowCheckedBinop(left, right, kind, rep);
  }
OverflowCheckedUnary()
template<typename Assembler >
Float Float Float32 Float Word Word64 Word32 Word Word V<turboshaft::Tuple<Word, Word32> > v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::OverflowCheckedUnary (V< Word > input, OverflowCheckedUnaryOp::Kind kind, WordRepresentation rep) [inline]
Definition at line 1988 of file assembler.h.
                              {
    return ReduceIfReachableOverflowCheckedUnary(input, kind, rep);
  }
Parameter() [1/2]
template<typename Assembler >
template<typename T >
V<T> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Parameter (int index, const char * debug_name = nullptr) [inline]
Definition at line 3332 of file assembler.h.
                                                              {
    return Parameter(index, V<T>::rep, debug_name);
  }
References v8::internal::index.
Parameter() [2/2]
template<typename Assembler >
OpIndex v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Parameter (int index, RegisterRepresentation rep, const char * debug_name = nullptr) [inline]
Definition at line 3312 of file assembler.h.
                                                      {
    // Parameter indices might be negative.
    int cache_location = index - kMinParameterIndex;
    DCHECK_GE(cache_location, 0);
    if (static_cast<size_t>(cache_location) >= cached_parameters_.size()) {
      cached_parameters_.resize(cache_location + 1, {});
    }
    OpIndex& cached_param = cached_parameters_[cache_location];
    if (!cached_param.valid()) {
      // Note: When in unreachable code, this will return OpIndex::Invalid, so
      // the cached state is unchanged.
      cached_param = ReduceIfReachableParameter(index, rep, debug_name);
    } else {
      DCHECK_EQ(Asm().output_graph().Get(cached_param).outputs_rep(),
                base::VectorOf({rep}));
    }
    return cached_param;
  }
References DCHECK_EQ, DCHECK_GE, v8::internal::compiler::turboshaft::Get(), v8::internal::index, v8::internal::kMinParameterIndex, v8::internal::compiler::turboshaft::OpIndex::valid(), and v8::base::VectorOf().
ParentFramePointer()
template<typename Assembler >
V<WordPtr> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ParentFramePointer () [inline]
Definition at line 3239 of file assembler.h.
                                  {
    return ReduceIfReachableFrameConstant(
        FrameConstantOp::Kind::kParentFramePointer);
  }
PendingLoopPhi() [1/2]
template<typename Assembler >
OpIndex v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::PendingLoopPhi (OpIndex first, RegisterRepresentation rep) [inline]
Definition at line 4151 of file assembler.h.
                                                                    {
    return ReduceIfReachablePendingLoopPhi(first, rep);
  }
PendingLoopPhi() [2/2]
template<typename Assembler >
template<typename T >
V<T> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::PendingLoopPhi (V< T > first) [inline]
Definition at line 4155 of file assembler.h.
                                  {
    return PendingLoopPhi(first, V<T>::rep);
  }
Phi() [1/3]
template<typename Assembler >
OpIndex v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Phi (base::Vector< const OpIndex > inputs, RegisterRepresentation rep) [inline]
Definition at line 4134 of file assembler.h.
                                                                            {
    return ReduceIfReachablePhi(inputs, rep);
  }
Phi() [2/3]
template<typename Assembler >
template<typename T >
V<T> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Phi (const base::Vector< V< T >> & inputs) [inline]
Definition at line 4142 of file assembler.h.
                                           {
    if (V8_UNLIKELY(Asm().generating_unreachable_operations())) {
      return OpIndex::Invalid();
    }
    // Downcast from typed `V<T>` wrapper to `OpIndex`.
    OpIndex* inputs_begin = inputs.data();
    static_assert(sizeof(OpIndex) == sizeof(V<T>));
    return Phi(base::VectorOf(inputs_begin, inputs.length()), V<T>::rep);
  }
References v8::internal::compiler::turboshaft::OpIndex::Invalid(), V8_UNLIKELY, and v8::base::VectorOf().
Phi() [3/3]
template<typename Assembler >
OpIndex v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Phi (std::initializer_list< OpIndex > inputs, RegisterRepresentation rep) [inline]
Definition at line 4137 of file assembler.h.
                                          {
    return Phi(base::VectorOf(inputs), rep);
  }
References v8::base::VectorOf().
Projection() [1/3]
template<typename Assembler >
V<Any> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Projection (V< Any > tuple, uint16_t index, RegisterRepresentation rep) [inline]
Definition at line 4177 of file assembler.h.
                                                                              {
    return ReduceIfReachableProjection(tuple, index, rep);
  }
References v8::internal::index.
Projection() [2/3]
template<typename Assembler >
template<uint16_t Index, typename... Ts>
auto v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Projection (V< turboshaft::Tuple< Ts... >> tuple) [inline]
Definition at line 4181 of file assembler.h.
                                                   {
    using element_t = base::nth_type_t<Index, Ts...>;
    static_assert(v_traits<element_t>::rep != nullrep,
                  "Representation for Projection cannot be inferred. Use "
                  "overload with explicit Representation argument.");
    return V<element_t>::Cast(Projection(tuple, Index, V<element_t>::rep));
  }
References v8::internal::compiler::turboshaft::V< T >::Cast(), and v8::internal::compiler::turboshaft::nullrep.
Projection() [3/3]
template<typename Assembler >
template<uint16_t Index, typename... Ts>
auto v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Projection (V< turboshaft::Tuple< Ts... >> tuple, RegisterRepresentation rep) [inline]
Definition at line 4189 of file assembler.h.
                                              {
    using element_t = base::nth_type_t<Index, Ts...>;
    DCHECK(V<element_t>::allows_representation(rep));
    return V<element_t>::Cast(Projection(tuple, Index, rep));
  }
References v8::internal::compiler::turboshaft::V< T >::Cast(), and v8::internal::DCHECK().
RelocatableConstant()
template<typename Assembler >
V<WordPtr> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::RelocatableConstant (int64_t value, RelocInfo::Mode mode) [inline]
Definition at line 2388 of file assembler.h.
                                                                    {
    DCHECK_EQ(mode, any_of(RelocInfo::WASM_CALL, RelocInfo::WASM_STUB_CALL));
    return ReduceIfReachableConstant(
        mode == RelocInfo::WASM_CALL
            ? ConstantOp::Kind::kRelocatableWasmCall
            : ConstantOp::Kind::kRelocatableWasmStubCall,
        static_cast<uint64_t>(value));
  }
References v8::base::any_of(), DCHECK_EQ, mode(), v8::internal::value, v8::internal::RelocInfo::WASM_CALL, and v8::internal::RelocInfo::WASM_STUB_CALL.
RelocatableWasmBuiltinCallTarget()
template<typename Assembler >
V<WordPtr> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::RelocatableWasmBuiltinCallTarget (Builtin builtin) [inline]
Definition at line 2397 of file assembler.h.
                                                               {
    return RelocatableConstant(static_cast<int64_t>(builtin),
                               RelocInfo::WASM_STUB_CALL);
  }
References v8::internal::RelocInfo::WASM_STUB_CALL.
RelocatableWasmCanonicalSignatureId()
template<typename Assembler >
V<Word32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::RelocatableWasmCanonicalSignatureId (uint32_t canonical_id) [inline]
Definition at line 2402 of file assembler.h.
                                                                       {
    return ReduceIfReachableConstant(
        ConstantOp::Kind::kRelocatableWasmCanonicalSignatureId,
        static_cast<uint64_t>(canonical_id));
  }
RelocatableWasmIndirectCallTarget()
template<typename Assembler >
V<Word32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::RelocatableWasmIndirectCallTarget (uint32_t function_index) [inline]
Definition at line 2408 of file assembler.h.
                                                                       {
    return ReduceIfReachableConstant(
        ConstantOp::Kind::kRelocatableWasmIndirectCallTarget, function_index);
  }
resolve() [1/5]
template<typename Assembler >
V<Float32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::resolve (const ConstOrV< Float32 > & v) [inline]
Definition at line 5211 of file assembler.h.
                                                 {
    return v.is_constant() ? Float32Constant(v.constant_value()) : v.value();
  }
References v8::internal::compiler::turboshaft::ConstOrV< T, C >::constant_value(), v8::internal::compiler::turboshaft::ConstOrV< T, C >::is_constant(), and v8::internal::compiler::turboshaft::ConstOrV< T, C >::value().
resolve() [2/5]
template<typename Assembler >
V<Float64> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::resolve (const ConstOrV< Float64 > & v) [inline]
Definition at line 5214 of file assembler.h.
                                                 {
    return v.is_constant() ? Float64Constant(v.constant_value()) : v.value();
  }
References v8::internal::compiler::turboshaft::ConstOrV< T, C >::constant_value(), v8::internal::compiler::turboshaft::ConstOrV< T, C >::is_constant(), and v8::internal::compiler::turboshaft::ConstOrV< T, C >::value().
resolve() [3/5]
template<typename Assembler >
V<Word32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::resolve (const ConstOrV< Word32 > & v) [inline]
Definition at line 5205 of file assembler.h.
                                               {
    return v.is_constant() ? Word32Constant(v.constant_value()) : v.value();
  }
References v8::internal::compiler::turboshaft::ConstOrV< T, C >::constant_value(), v8::internal::compiler::turboshaft::ConstOrV< T, C >::is_constant(), and v8::internal::compiler::turboshaft::ConstOrV< T, C >::value().
resolve() [4/5]
template<typename Assembler >
V<Word64> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::resolve (const ConstOrV< Word64 > & v) [inline]
Definition at line 5208 of file assembler.h.
                                               {
    return v.is_constant() ? Word64Constant(v.constant_value()) : v.value();
  }
References v8::internal::compiler::turboshaft::ConstOrV< T, C >::constant_value(), v8::internal::compiler::turboshaft::ConstOrV< T, C >::is_constant(), and v8::internal::compiler::turboshaft::ConstOrV< T, C >::value().
resolve() [5/5]
template<typename Assembler >
template<typename Rep >
V<Rep> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::resolve (const V< Rep > & v) [inline]
Definition at line 5202 of file assembler.h.
                                  {
    return v;
  }
RestLength()
template<typename Assembler >
V<Smi> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::RestLength (int formal_parameter_count) [inline]
Definition at line 4633 of file assembler.h.
                                                {
    DCHECK_LE(0, formal_parameter_count);
    return ReduceIfReachableArgumentsLength(ArgumentsLengthOp::Kind::kRest,
                                            formal_parameter_count);
  }
References DCHECK_LE.
Retain()
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Retain (V< Object > value) [inline]
Definition at line 3226 of file assembler.h.
{ ReduceIfReachableRetain(value); }
References v8::internal::value.
Return() [1/2]
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Return (OpIndex result) [inline]
Definition at line 3340 of file assembler.h.
                              {
    Return(Word32Constant(0), base::VectorOf({result}));
  }
References v8::base::internal::result, and v8::base::VectorOf().
Return() [2/2]
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Return (V< Word32 > pop_count, base::Vector< const OpIndex > return_values, bool spill_caller_frame_slots = false) [inline]
Definition at line 3336 of file assembler.h.
                                                     {
    ReduceIfReachableReturn(pop_count, return_values, spill_caller_frame_slots);
  }
RootEqual()
template<typename Assembler >
V<Word32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::RootEqual (V< Object > input, RootIndex root, Isolate * isolate) [inline]
Definition at line 1811 of file assembler.h.
                                                                         {
    return __ TaggedEqual(
        input, __ HeapConstant(Cast<HeapObject>(isolate->root_handle(root))));
  }
References __, and v8::internal::Isolate::root_handle().
RuntimeAbort()
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::RuntimeAbort (AbortReason reason) [inline]
Definition at line 4761 of file assembler.h.
                                        {
    ReduceIfReachableRuntimeAbort(reason);
  }
SameValue()
template<typename Assembler >
V<Boolean> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::SameValue (V< Object > left, V< Object > right, SameValueOp::Mode mode) [inline]
Definition at line 4743 of file assembler.h.
                                             {
    return ReduceIfReachableSameValue(left, right, mode);
  }
References mode().
Select() [1/2]
template<typename Assembler >
OpIndex v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Select (ConstOrV< Word32 > cond, OpIndex vtrue, OpIndex vfalse, RegisterRepresentation rep, BranchHint hint, SelectOp::Implementation implem) [inline]
Definition at line 3276 of file assembler.h.
                                                {
    return Select(cond, V<Any>::Cast(vtrue), V<Any>::Cast(vfalse), rep, hint,
                  implem);
  }
Select() [2/2]
template<typename Assembler >
template<typename T = Any, typename U = T>
V<std::common_type_t<T, U> > v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Select (ConstOrV< Word32 > cond, V< T > vtrue, V< U > vfalse, RegisterRepresentation rep, BranchHint hint, SelectOp::Implementation implem) [inline]
Definition at line 3266 of file assembler.h.
                                                                    {
    return ReduceIfReachableSelect(resolve(cond), vtrue, vfalse, rep, hint,
                                   implem);
  }
ShiftLeft()
template<typename Assembler >
V<Word> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ShiftLeft (V< Word > left, uint32_t right, WordRepresentation rep) [inline]
Definition at line 1798 of file assembler.h.
                                                                          {
    DCHECK_LT(right, rep.bit_width());
    return ShiftLeft(left, this->Word32Constant(right), rep);
  }
References v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::bit_width(), and DCHECK_LT.
ShiftRightArithmetic()
template<typename Assembler >
V<Word> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ShiftRightArithmetic (V< Word > left, uint32_t right, WordRepresentation rep) [inline]
Definition at line 1792 of file assembler.h.
                                                       {
    DCHECK_GE(right, 0);
    DCHECK_LT(right, rep.bit_width());
    return ShiftRightArithmetic(left, this->Word32Constant(right), rep);
  }
References v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::bit_width(), DCHECK_GE, and DCHECK_LT.
ShiftRightLogical()
template<typename Assembler >
return v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ShiftRightLogical (left , this-> Word32Constantright, rep)
SmiConstant()
template<typename Assembler >
V<Smi> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::SmiConstant (i::Tagged< Smi > value) [inline]
Definition at line 2287 of file assembler.h.
                                         {
    return V<Smi>::Cast(
        ReduceIfReachableConstant(ConstantOp::Kind::kSmi, value));
  }
References v8::internal::compiler::turboshaft::V< T >::Cast(), v8::internal::compiler::kSmi, and v8::internal::value.
SmiZeroConstant()
template<typename Assembler >
V<Smi> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::SmiZeroConstant () [inline]
Definition at line 2291 of file assembler.h.
{ return SmiConstant(Smi::zero()); }
References v8::internal::Smi::zero().
StackCheckOffset()
template<typename Assembler >
V<Smi> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StackCheckOffset () [inline]
Definition at line 3232 of file assembler.h.
                            {
    return ReduceIfReachableFrameConstant(
        FrameConstantOp::Kind::kStackCheckOffset);
  }
StackPointerGreaterThan()
template<typename Assembler >
V<Word32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StackPointerGreaterThan (V< WordPtr > limit, StackCheckKind kind) [inline]
Definition at line 3228 of file assembler.h.
                                                                           {
    return ReduceIfReachableStackPointerGreaterThan(limit, kind);
  }
StackSlot()
template<typename Assembler >
V<WordPtr> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StackSlot (int size, int alignment, bool is_tagged = false) [inline]
Definition at line 3244 of file assembler.h.
                                                                        {
    return ReduceIfReachableStackSlot(size, alignment, is_tagged);
  }
References size().
StaticAssert()
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StaticAssert (V< Word32 > condition, const char * source) [inline]
Definition at line 4130 of file assembler.h.
                                                             {
    ReduceIfReachableStaticAssert(condition, source);
  }
Store() [1/2]
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Store (OpIndex base, OpIndex value, StoreOp::Kind kind, MemoryRepresentation stored_rep, WriteBarrierKind write_barrier, int32_t offset = 0, bool maybe_initializing_or_transitioning = false, IndirectPointerTag maybe_indirect_pointer_tag = kIndirectPointerNullTag) [inline]
Definition at line 2897 of file assembler.h.
                                                                               {
    Store(base, OpIndex::Invalid(), value, kind, stored_rep, write_barrier,
          offset, 0, maybe_initializing_or_transitioning,
          maybe_indirect_pointer_tag);
  }
References v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::wasm::liftoff::Store(), and v8::internal::value.
Store() [2/2]
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Store (OpIndex base, OptionalOpIndex index, OpIndex value, StoreOp::Kind kind, MemoryRepresentation stored_rep, WriteBarrierKind write_barrier, int32_t offset = 0, uint8_t element_size_log2 = 0, bool maybe_initializing_or_transitioning = false, IndirectPointerTag maybe_indirect_pointer_tag = kIndirectPointerNullTag) [inline]
Definition at line 2886 of file assembler.h.
                                                                               {
    ReduceIfReachableStore(base, index, value, kind, stored_rep, write_barrier,
                           offset, element_size_log2,
                           maybe_initializing_or_transitioning,
                           maybe_indirect_pointer_tag);
  }
References v8::internal::index, and v8::internal::value.
StoreArrayBufferElement()
template<typename Assembler >
template<typename Base >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StoreArrayBufferElement (V< Base > object, const ElementAccess & access, V< WordPtr > index, V< Any > value) [inline]
Definition at line 3124 of file assembler.h.
                                                               {
    return StoreElement(object, access, index, value, true);
  }
References v8::internal::index, and v8::internal::value.
StoreDataViewElement()
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StoreDataViewElement (V< Object > object, V< WordPtr > storage, V< WordPtr > index, OpIndex value, ConstOrV< Word32 > is_little_endian, ExternalArrayType element_type) [inline]
Definition at line 4671 of file assembler.h.
                                                            {
    ReduceIfReachableStoreDataViewElement(
        object, storage, index, value, resolve(is_little_endian), element_type);
  }
References v8::internal::index, and v8::internal::value.
StoreElement() [1/2]
template<typename Assembler >
template<typename Base >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StoreElement (V< Base > object, const ElementAccess & access, ConstOrV< WordPtr > index, V< Any > value, bool is_array_buffer) [inline], [private]
Definition at line 5283 of file assembler.h.
                                          {
    if constexpr (is_taggable_v<Base>) {
      DCHECK_EQ(access.base_is_tagged, BaseTaggedness::kTaggedBase);
    } else {
      static_assert(std::is_same_v<Base, WordPtr>);
      DCHECK_EQ(access.base_is_tagged, BaseTaggedness::kUntaggedBase);
    }
    LoadOp::Kind kind = LoadOp::Kind::Aligned(access.base_is_tagged);
    if (is_array_buffer) kind = kind.NotLoadEliminable();
    MemoryRepresentation rep =
        MemoryRepresentation::FromMachineType(access.machine_type);
    Store(object, resolve(index), value, kind, rep, access.write_barrier_kind,
          access.header_size, rep.SizeInBytesLog2());
  }
References v8::internal::compiler::ElementAccess::base_is_tagged, DCHECK_EQ, v8::internal::compiler::turboshaft::MemoryRepresentation::FromMachineType(), v8::internal::compiler::ElementAccess::header_size, v8::internal::index, v8::internal::compiler::kTaggedBase, v8::internal::compiler::kUntaggedBase, v8::internal::compiler::ElementAccess::machine_type, v8::internal::compiler::turboshaft::LoadOp::Kind::NotLoadEliminable(), v8::internal::compiler::turboshaft::MemoryRepresentation::SizeInBytesLog2(), v8::internal::wasm::liftoff::Store(), v8::internal::value, and v8::internal::compiler::ElementAccess::write_barrier_kind.
StoreElement() [2/2]
template<typename Assembler >
template<typename Class , typename T >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StoreElement (V< Class > object, const ElementAccessTS< Class, T > & access, ConstOrV< WordPtr > index, V< T > value) [inline]
Definition at line 3135 of file assembler.h.
                                                         {
    StoreElement(object, access, index, value, access.is_array_buffer_load);
  }
References v8::internal::index, v8::internal::compiler::turboshaft::ElementAccessTS< Class, T >::is_array_buffer_load, and v8::internal::value.
StoreField()
template<typename Assembler >
template<typename Base >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StoreField (V< Base > object, const FieldAccess & access, V< Any > value) [inline]
Definition at line 3015 of file assembler.h.
                                                                           {
    StoreFieldImpl(object, access, value,
                   access.maybe_initializing_or_transitioning_store);
  }
References v8::internal::compiler::FieldAccess::maybe_initializing_or_transitioning_store, and v8::internal::value.
StoreFieldImpl()
template<typename Assembler >
template<typename Base >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StoreFieldImpl (V< Base > object, const FieldAccess & access, V< Any > value, bool maybe_initializing_or_transitioning) [inline]
Definition at line 3037 of file assembler.h.
                                                                {
    if constexpr (is_taggable_v<Base>) {
      DCHECK_EQ(access.base_is_tagged, BaseTaggedness::kTaggedBase);
    } else {
      static_assert(std::is_same_v<Base, WordPtr>);
      DCHECK_EQ(access.base_is_tagged, BaseTaggedness::kUntaggedBase);
    }
    // External pointer must never be stored by optimized code.
    DCHECK(!access.type.Is(compiler::Type::ExternalPointer()) ||
           !V8_ENABLE_SANDBOX_BOOL);
    // SandboxedPointers are not currently stored by optimized code.
    DCHECK(!access.type.Is(compiler::Type::SandboxedPointer()));
#ifdef V8_ENABLE_SANDBOX
    if (access.is_bounded_size_access) {
      value = ShiftLeft(V<WordPtr>::Cast(value), kBoundedSizeShift,
                        WordRepresentation::WordPtr());
    }
#endif // V8_ENABLE_SANDBOX
    StoreOp::Kind kind = StoreOp::Kind::Aligned(access.base_is_tagged);
    MachineType machine_type = access.machine_type;
    if (machine_type.IsMapWord()) {
      machine_type = MachineType::TaggedPointer();
#ifdef V8_MAP_PACKING
      UNIMPLEMENTED();
#endif
    }
    MemoryRepresentation rep =
        MemoryRepresentation::FromMachineType(machine_type);
    Store(object, value, kind, rep, access.write_barrier_kind, access.offset,
          maybe_initializing_or_transitioning);
  }
References v8::internal::compiler::FieldAccess::base_is_tagged, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::MemoryRepresentation::FromMachineType(), v8::internal::compiler::Type::Is(), v8::internal::compiler::FieldAccess::is_bounded_size_access, v8::internal::MachineType::IsMapWord(), v8::internal::compiler::kTaggedBase, v8::internal::compiler::kUntaggedBase, v8::internal::compiler::FieldAccess::machine_type, v8::internal::wasm::machine_type(), v8::internal::compiler::FieldAccess::offset, v8::internal::wasm::liftoff::Store(), v8::internal::MachineType::TaggedPointer(), v8::internal::compiler::FieldAccess::type, v8::internal::UNIMPLEMENTED(), V8_ENABLE_SANDBOX_BOOL, v8::internal::value, v8::internal::compiler::turboshaft::WordRepresentation::WordPtr(), and v8::internal::compiler::FieldAccess::write_barrier_kind.
StoreFixedArrayElement() [1/2]
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StoreFixedArrayElement (V< FixedArray > array, int index, V< Object > value, compiler::WriteBarrierKind write_barrier) [inline]
Definition at line 3072 of file assembler.h.
                                                                      {
    Store(array, value, LoadOp::Kind::TaggedBase(),
          MemoryRepresentation::AnyTagged(), write_barrier,
          FixedArray::OffsetOfElementAt(index));
  }
References v8::internal::compiler::turboshaft::MemoryRepresentation::AnyTagged(), v8::internal::index, v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::OffsetOfElementAt(), v8::internal::wasm::liftoff::Store(), and v8::internal::value.
StoreFixedArrayElement() [2/2]
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StoreFixedArrayElement (V< FixedArray > array, V< WordPtr > index, V< Object > value, compiler::WriteBarrierKind write_barrier) [inline]
Definition at line 3079 of file assembler.h.
                                                                      {
    Store(array, index, value, LoadOp::Kind::TaggedBase(),
          MemoryRepresentation::AnyTagged(), write_barrier,
          OFFSET_OF_DATA_START(FixedArray), kTaggedSizeLog2);
  }
References v8::internal::compiler::turboshaft::MemoryRepresentation::AnyTagged(), v8::internal::index, v8::internal::kTaggedSizeLog2, OFFSET_OF_DATA_START, v8::internal::wasm::liftoff::Store(), and v8::internal::value.
StoreFixedDoubleArrayElement()
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StoreFixedDoubleArrayElement (V< FixedDoubleArray > array, V< WordPtr > index, V< Float64 > value) [inline]
Definition at line 3086 of file assembler.h.
                                                      {
    static_assert(ElementsKindToShiftSize(PACKED_DOUBLE_ELEMENTS) ==
                  ElementsKindToShiftSize(HOLEY_DOUBLE_ELEMENTS));
    Store(array, index, value, LoadOp::Kind::TaggedBase(),
          MemoryRepresentation::Float64(), WriteBarrierKind::kNoWriteBarrier,
          sizeof(FixedDoubleArray::Header),
          ElementsKindToShiftSize(PACKED_DOUBLE_ELEMENTS));
  }
References v8::internal::ElementsKindToShiftSize(), v8::internal::compiler::turboshaft::MemoryRepresentation::Float64(), v8::internal::HOLEY_DOUBLE_ELEMENTS, v8::internal::index, v8::internal::compiler::kNoWriteBarrier, v8::internal::PACKED_DOUBLE_ELEMENTS, v8::internal::wasm::liftoff::Store(), and v8::internal::value.
StoreMessage()
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StoreMessage (V< WordPtr > offset, V< Object > object) [inline]
Definition at line 4739 of file assembler.h.
                                                         {
    ReduceIfReachableStoreMessage(offset, object);
  }
StoreNonArrayBufferElement()
template<typename Assembler >
template<typename Base >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StoreNonArrayBufferElement (V< Base > object, const ElementAccess & access, V< WordPtr > index, V< Any > value) [inline]
Definition at line 3129 of file assembler.h.
                                                                  {
    return StoreElement(object, access, index, value, false);
  }
References v8::internal::index, and v8::internal::value.
StoreOffHeap() [1/2]
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StoreOffHeap (OpIndex address, OpIndex value, MemoryRepresentation rep, int32_t offset = 0) [inline]
Definition at line 2916 of file assembler.h.
                                        {
    Store(address, value, StoreOp::Kind::RawAligned(), rep,
          WriteBarrierKind::kNoWriteBarrier, offset);
  }
References v8::internal::compiler::kNoWriteBarrier, v8::internal::wasm::liftoff::Store(), and v8::internal::value.
StoreOffHeap() [2/2]
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StoreOffHeap (OpIndex address, OptionalOpIndex index, OpIndex value, MemoryRepresentation rep, int32_t offset) [inline]
Definition at line 2921 of file assembler.h.
                                                              {
    Store(address, index, value, StoreOp::Kind::RawAligned(), rep,
          WriteBarrierKind::kNoWriteBarrier, offset, rep.SizeInBytesLog2());
  }
References v8::internal::index, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::turboshaft::MemoryRepresentation::SizeInBytesLog2(), v8::internal::wasm::liftoff::Store(), and v8::internal::value.
StoreSignedSmallElement()
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StoreSignedSmallElement (V< JSArray > array, V< WordPtr > index, V< Word32 > value) [inline]
Definition at line 4687 of file assembler.h.
                                                {
    TransitionAndStoreArrayElement(
        array, index, value,
        TransitionAndStoreArrayElementOp::Kind::kSignedSmallElement, {}, {});
  }
References v8::internal::index, and v8::internal::value.
StoreTypedElement()
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StoreTypedElement (OpIndex buffer, V< Object > base, V< WordPtr > external, V< WordPtr > index, OpIndex value, ExternalArrayType array_type) [inline]
Definition at line 4664 of file assembler.h.
                                                       {
    ReduceIfReachableStoreTypedElement(buffer, base, external, index, value,
                                       array_type);
  }
References v8::internal::index, and v8::internal::value.
StringAt()
template<typename Assembler >
V<Word32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StringAt (V< String > string, V< WordPtr > position, StringAtOp::Kind kind) [inline]
Definition at line 4561 of file assembler.h.
                                          {
    return ReduceIfReachableStringAt(string, position, kind);
  }
StringCharCodeAt()
template<typename Assembler >
V<Word32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StringCharCodeAt (V< String > string, V< WordPtr > position) [inline]
Definition at line 4565 of file assembler.h.
                                                                    {
    return StringAt(string, position, StringAtOp::Kind::kCharCode);
  }
StringCodePointAt()
template<typename Assembler >
V<Word32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StringCodePointAt (V< String > string, V< WordPtr > position) [inline]
Definition at line 4568 of file assembler.h.
                                                                     {
    return StringAt(string, position, StringAtOp::Kind::kCodePoint);
  }
StringComparison()
template<typename Assembler >
V<Boolean> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StringComparison (V< String > left, V< String > right, StringComparisonOp::Kind kind) [inline]
Definition at line 4609 of file assembler.h.
                                                           {
    return ReduceIfReachableStringComparison(left, right, kind);
  }
StringConcat()
template<typename Assembler >
V<String> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StringConcat (V< Smi > length, V< String > left, V< String > right) [inline]
Definition at line 4605 of file assembler.h.
                                                                         {
    return ReduceIfReachableStringConcat(length, left, right);
  }
References v8::internal::length.
StringEqual()
template<typename Assembler >
V<Boolean> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StringEqual (V< String > left, V< String > right, StringComparisonOp::Kind kind = StringComparisonOp::Kind::kEqual) [inline]
Definition at line 4613 of file assembler.h.
                                                                  {
    return StringComparison(left, right, kind);
  }
StringFromCodePointAt()
template<typename Assembler >
V<String> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StringFromCodePointAt (V< String > string, V< WordPtr > index) [inline]
Definition at line 4597 of file assembler.h.
                                                                      {
    return ReduceIfReachableStringFromCodePointAt(string, index);
  }
References v8::internal::index.
StringIndexOf()
template<typename Assembler >
V<Smi> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StringIndexOf (V< String > string, V< String > search, V< Smi > position) [inline]
Definition at line 4593 of file assembler.h.
                                                                            {
    return ReduceIfReachableStringIndexOf(string, search, position);
  }
References v8::internal::anonymous_namespace{simd.cc}::search().
StringLength()
template<typename Assembler >
V<Word32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StringLength (V< String > string) [inline]
Definition at line 4584 of file assembler.h.
                                           {
    return ReduceIfReachableStringLength(string);
  }
StringLessThan()
template<typename Assembler >
V<Boolean> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StringLessThan (V< String > left, V< String > right) [inline]
Definition at line 4618 of file assembler.h.
                                                             {
    return StringComparison(left, right, StringComparisonOp::Kind::kLessThan);
  }
References v8::internal::kLessThan.
StringLessThanOrEqual()
template<typename Assembler >
V<Boolean> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StringLessThanOrEqual (V< String > left, V< String > right) [inline]
Definition at line 4621 of file assembler.h.
                                                                    {
    return StringComparison(left, right,
                            StringComparisonOp::Kind::kLessThanOrEqual);
  }
StringOrOddballStrictEqual()
template<typename Assembler >
V<Boolean> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StringOrOddballStrictEqual (V< String > left, V< String > right) [inline]
Definition at line 4625 of file assembler.h.
                                                                         {
    return ReduceIfReachableStringOrOddballStrictEqual(left, right);
  }
StringSubstring()
template<typename Assembler >
V<String> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StringSubstring (V< String > string, V< Word32 > start, V< Word32 > end) [inline]
Definition at line 4601 of file assembler.h.
                                                                              {
    return ReduceIfReachableStringSubstring(string, start, end);
  }
References v8::internal::compiler::end().
Switch()
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Switch (V< Word32 > input, base::Vector< SwitchOp::Case > cases, Block * default_case, BranchHint default_hint = BranchHint::kNone) [inline]
Definition at line 3305 of file assembler.h.
                                                         {
    ReduceIfReachableSwitch(input, cases, default_case, default_hint);
  }
TaggedBitcast()
template<typename Assembler >
OpIndex v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::TaggedBitcast (OpIndex input, RegisterRepresentation from, RegisterRepresentation to, TaggedBitcastOp::Kind kind) [inline]
Definition at line 2051 of file assembler.h.
                                                                             {
    return ReduceIfReachableTaggedBitcast(input, from, to, kind);
  }
TaggedEqual()
template<typename Assembler >
V<Word32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::TaggedEqual (V< Object > left, V< Object > right) [inline]
Definition at line 1807 of file assembler.h.
                                                         {
    return Equal(left, right, RegisterRepresentation::Tagged());
  }
References v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged().
TaggedIndexConstant()
template<typename Assembler >
OpIndex v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::TaggedIndexConstant (int32_t value) [inline]
Definition at line 2341 of file assembler.h.
                                             {
    return ReduceIfReachableConstant(ConstantOp::Kind::kTaggedIndex,
                                     uint64_t{static_cast<uint32_t>(value)});
  }
References v8::internal::value.
TagSmi()
template<typename Assembler >
V<Smi> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::TagSmi (ConstOrV< Word32 > input) [inline]
Definition at line 2645 of file assembler.h.
                                        {
    constexpr int kSmiShiftBits = kSmiShiftSize + kSmiTagSize;
    // Do shift on 32bit values if Smis are stored in the lower word.
    if constexpr (Is64() && SmiValuesAre31Bits()) {
      V<Word32> shifted = Word32ShiftLeft(resolve(input), kSmiShiftBits);
      // In pointer compression, we smi-corrupt. Then, the upper bits are not
      // important.
      return BitcastWord32ToSmi(shifted);
    } else {
      return BitcastWordPtrToSmi(
          WordPtrShiftLeft(ChangeInt32ToIntPtr(resolve(input)), kSmiShiftBits));
    }
  }
References v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::ChangeInt32ToIntPtr(), v8::internal::Is64(), v8::internal::kSmiShiftSize, v8::internal::kSmiTagSize, and v8::internal::SmiValuesAre31Bits().
TailCall()
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::TailCall (V< CallTarget > callee, base::Vector< const OpIndex > arguments, const TSCallDescriptor * descriptor) [inline]
Definition at line 4050 of file assembler.h.
                                                    {
    ReduceIfReachableTailCall(callee, arguments, descriptor);
  }
ToNumber()
template<typename Assembler >
V<Object> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ToNumber (V< Object > input, V< turboshaft::FrameState > frame_state, V< Context > context, LazyDeoptOnThrow lazy_deopt_on_throw) [inline]
Definition at line 1587 of file assembler.h.
                                                                               {
    return ToNumberOrNumeric(input, frame_state, context,
                             Object::Conversion::kToNumber,
                             lazy_deopt_on_throw);
  }
References v8::internal::Object::kToNumber.
ToNumberOrNumeric()
template<typename Assembler >
V<Object> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ToNumberOrNumeric (V< Object > input, V< turboshaft::FrameState > frame_state, V< Context > context, Object::Conversion kind, LazyDeoptOnThrow lazy_deopt_on_throw) [inline]
Definition at line 1580 of file assembler.h.
                                                                    {
    return ReduceIfReachableToNumberOrNumeric(input, frame_state, context, kind,
                                              lazy_deopt_on_throw);
  }
ToNumeric()
template<typename Assembler >
V<Object> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ToNumeric (V< Object > input, V< turboshaft::FrameState > frame_state, V< Context > context, LazyDeoptOnThrow lazy_deopt_on_throw) [inline]
Definition at line 1593 of file assembler.h.
                                                            {
    return ToNumberOrNumeric(input, frame_state, context,
                             Object::Conversion::kToNumeric,
                             lazy_deopt_on_throw);
  }
References v8::internal::Object::kToNumeric.
TransitionAndStoreArrayElement()
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::TransitionAndStoreArrayElement (V< JSArray > array, V< WordPtr > index, V< Any > value, TransitionAndStoreArrayElementOp::Kind kind, MaybeHandle< Map > fast_map, MaybeHandle< Map > double_map) [inline]
Definition at line 4679 of file assembler.h.
                                   {
    ReduceIfReachableTransitionAndStoreArrayElement(array, index, value, kind,
                                                    fast_map, double_map);
  }
References v8::internal::index, and v8::internal::value.
TransitionElementsKind()
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::TransitionElementsKind (V< HeapObject > object, const ElementsTransition & transition) [inline]
Definition at line 4778 of file assembler.h.
                                                                    {
    ReduceIfReachableTransitionElementsKind(object, transition);
  }
TransitionElementsKindOrCheckMap()
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::TransitionElementsKindOrCheckMap (V< HeapObject > object, V< Map > map, V< turboshaft::FrameState > frame_state, const ElementsTransitionWithMultipleSources & transition) [inline]
Definition at line 4782 of file assembler.h.
                                                               {
    ReduceIfReachableTransitionElementsKindOrCheckMap(object, map, frame_state,
                                                      transition);
  }
TruncateFloat64ToFloat16RawBits()
template<typename Assembler >
V<Word32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::TruncateFloat64ToFloat16RawBits (V< Float64 > input) [inline]
Definition at line 4723 of file assembler.h.
                                                              {
    return V<Word32>::Cast(__ ReduceChange(
        input, ChangeOp::Kind::kJSFloat16TruncateWithBitcast,
        ChangeOp::Assumption::kNoAssumption, V<Float64>::rep, V<Word32>::rep));
  }
References __, and v8::internal::compiler::turboshaft::V< T >::Cast().
TruncateJSPrimitiveToUntagged()
template<typename Assembler >
V<Word> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::TruncateJSPrimitiveToUntagged (V< JSPrimitive > object, TruncateJSPrimitiveToUntaggedOp::UntaggedKind kind, TruncateJSPrimitiveToUntaggedOp::InputAssumptions input_assumptions) [inline]
Definition at line 2228 of file assembler.h.
                                                                         {
    return ReduceIfReachableTruncateJSPrimitiveToUntagged(object, kind,
                                                          input_assumptions);
  }
TruncateJSPrimitiveToUntaggedOrDeopt()
template<typename Assembler >
V<Word> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::TruncateJSPrimitiveToUntaggedOrDeopt (V< JSPrimitive > object, V< turboshaft::FrameState > frame_state, TruncateJSPrimitiveToUntaggedOrDeoptOp::UntaggedKind kind, TruncateJSPrimitiveToUntaggedOrDeoptOp::InputRequirement input_requirement, const FeedbackSource & feedback) [inline]
Definition at line 2241 of file assembler.h.
                                      {
    return ReduceIfReachableTruncateJSPrimitiveToUntaggedOrDeopt(
        object, frame_state, kind, input_requirement, feedback);
  }
TruncateNumberToInt32()
template<typename Assembler >
V<Word32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::TruncateNumberToInt32 (V< Number > value) [inline]
Definition at line 2235 of file assembler.h.
                                                   {
    return V<Word32>::Cast(TruncateJSPrimitiveToUntagged(
        value, TruncateJSPrimitiveToUntaggedOp::UntaggedKind::kInt32,
        TruncateJSPrimitiveToUntaggedOp::InputAssumptions::kNumberOrOddball));
  }
References v8::internal::compiler::turboshaft::V< T >::Cast(), and v8::internal::value.
TruncateWordPtrToWord32()
template<typename Assembler >
V<Word32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::TruncateWordPtrToWord32 (ConstOrV< WordPtr > input) [inline]
Definition at line 2496 of file assembler.h.
                                                             {
    if constexpr (Is64()) {
      return TruncateWord64ToWord32(input);
    } else {
      DCHECK_EQ(WordPtr::bits, Word32::bits);
      return V<Word32>::Cast(resolve(input));
    }
  }
References v8::internal::compiler::turboshaft::WordWithBits< 32 >::bits, v8::internal::compiler::turboshaft::V< T >::Cast(), DCHECK_EQ, and v8::internal::Is64().
TrustedHeapConstant()
template<typename Assembler >
OpIndex v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::TrustedHeapConstant (Handle< HeapObject > value) [inline]
Definition at line 2377 of file assembler.h.
                                                        {
    DCHECK(IsTrustedObject(*value));
    return ReduceIfReachableConstant(ConstantOp::Kind::kTrustedHeapObject,
                                     value);
  }
References v8::internal::DCHECK(), and v8::internal::value.
Tuple() [1/4]
template<typename Assembler >
V<Any> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Tuple (base::Vector< const V< Any >> indices) [inline]
Definition at line 4159 of file assembler.h.
                                                 {
    return ReduceIfReachableTuple(indices);
  }
Tuple() [2/4]
template<typename Assembler >
V<turboshaft::Tuple<Any, Any> > v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Tuple (OpIndex left, OpIndex right) [inline]
Definition at line 4172 of file assembler.h.
                                                                  {
    return V<turboshaft::Tuple<Any, Any>>::Cast(
        Tuple(base::VectorOf({V<Any>::Cast(left), V<Any>::Cast(right)})));
  }
References v8::internal::Cast(), v8::internal::compiler::turboshaft::V< T >::Cast(), and v8::base::VectorOf().
Tuple() [3/4]
template<typename Assembler >
V<Any> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Tuple (std::initializer_list< V< Any >> indices) [inline]
Definition at line 4162 of file assembler.h.
                                                    {
    return ReduceIfReachableTuple(base::VectorOf(indices));
  }
References v8::base::VectorOf().
Tuple() [4/4]
template<typename Assembler >
template<typename... Ts>
V<turboshaft::Tuple<Ts...> > v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Tuple (V< Ts >... indices) [inline]
Definition at line 4166 of file assembler.h.
                                                    {
    std::initializer_list<V<Any>> inputs{V<Any>::Cast(indices)...};
    return V<turboshaft::Tuple<Ts...>>::Cast(Tuple(base::VectorOf(inputs)));
  }
References v8::internal::Cast(), v8::internal::compiler::turboshaft::V< T >::Cast(), and v8::base::VectorOf().
TypedArrayLength()
template<typename Assembler >
V<WordPtr> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::TypedArrayLength (V< JSTypedArray > typed_array, ElementsKind elements_kind) [inline]
Definition at line 4588 of file assembler.h.
                                                          {
    return ReduceIfReachableTypedArrayLength(typed_array, elements_kind);
  }
UintPtrConstant()
template<typename Assembler >
V<WordPtr> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::UintPtrConstant (uintptr_t value) [inline]
Definition at line 2286 of file assembler.h.
{ return WordPtrConstant(value); }
References v8::internal::value.
Unreachable()
template<typename Assembler >
void v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Unreachable () [inline]
Definition at line 3310 of file assembler.h.
{ ReduceIfReachableUnreachable(); }
UntagSmi()
template<typename Assembler >
V<Word32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::UntagSmi (V< Smi > input) [inline]
Definition at line 2659 of file assembler.h.
                                   {
    constexpr int kSmiShiftBits = kSmiShiftSize + kSmiTagSize;
    if constexpr (Is64() && SmiValuesAre31Bits()) {
      return Word32ShiftRightArithmeticShiftOutZeros(BitcastSmiToWord32(input),
                                                     kSmiShiftBits);
    }
    return TruncateWordPtrToWord32(WordPtrShiftRightArithmeticShiftOutZeros(
        BitcastSmiToWordPtr(input), kSmiShiftBits));
  }
References v8::internal::Is64(), v8::internal::kSmiShiftSize, v8::internal::kSmiTagSize, and v8::internal::SmiValuesAre31Bits().
Word32BitwiseNot()
template<typename Assembler >
Word32 Word Word64 V<Word32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Word32BitwiseNot (ConstOrV< Word32 > input) [inline]
Definition at line 1673 of file assembler.h.
                                                     {
    return Word32BitwiseXor(input, static_cast<uint32_t>(-1));
  }
Word32Constant() [1/2]
template<typename Assembler >
V<Word32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Word32Constant (int32_t value) [inline]
Definition at line 2263 of file assembler.h.
                                          {
    return Word32Constant(static_cast<uint32_t>(value));
  }
References v8::internal::value.
Word32Constant() [2/2]
template<typename Assembler >
V<Word32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Word32Constant (uint32_t value) [inline]
Definition at line 2259 of file assembler.h.
                                           {
    return ReduceIfReachableConstant(ConstantOp::Kind::kWord32,
                                     uint64_t{value});
  }
References v8::internal::value.
Word32PairBinop()
template<typename Assembler >
V<Word32Pair> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Word32PairBinop (V< Word32 > left_low, V< Word32 > left_high, V< Word32 > right_low, V< Word32 > right_high, Word32PairBinopOp::Kind kind) [inline]
Definition at line 4554 of file assembler.h.
                                                            {
    return ReduceIfReachableWord32PairBinop(left_low, left_high, right_low,
                                            right_high, kind);
  }
Word32SignHint()
template<typename Assembler >
V<Word32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Word32SignHint (V< Word32 > input, Word32SignHintOp::Sign sign) [inline]
Definition at line 1536 of file assembler.h.
                                                                       {
    return ReduceIfReachableWord32SignHint(input, sign);
  }
References v8::internal::sign.
Word32SignHintSigned()
template<typename Assembler >
V<Word32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Word32SignHintSigned (V< Word32 > input) [inline]
Definition at line 1543 of file assembler.h.
                                                  {
    return Word32SignHint(input, Word32SignHintOp::Sign::kSigned);
  }
References v8::internal::compiler::kSigned.
Word32SignHintUnsigned()
template<typename Assembler >
V<Word32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Word32SignHintUnsigned (V< Word32 > input) [inline]
Definition at line 1540 of file assembler.h.
                                                    {
    return Word32SignHint(input, Word32SignHintOp::Sign::kUnsigned);
  }
References v8::internal::compiler::kUnsigned.
Word64Constant() [1/2]
template<typename Assembler >
V<Word64> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Word64Constant (int64_t value) [inline]
Definition at line 2269 of file assembler.h.
                                          {
    return Word64Constant(static_cast<uint64_t>(value));
  }
References v8::internal::value.
Word64Constant() [2/2]
template<typename Assembler >
V<Word64> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Word64Constant (uint64_t value) [inline]
Definition at line 2266 of file assembler.h.
                                           {
    return ReduceIfReachableConstant(ConstantOp::Kind::kWord64, value);
  }
References v8::internal::value.
WordBinop()
template<typename Assembler >
V<Word> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::WordBinop (V< Word > left, V< Word > right, WordBinopOp::Kind kind, WordRepresentation rep) [inline]
Definition at line 1677 of file assembler.h.
                                            {
    return ReduceIfReachableWordBinop(left, right, kind, rep);
  }
WordConstant()
template<typename Assembler >
V<Word> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::WordConstant (uint64_t value, WordRepresentation rep) [inline]
Definition at line 2275 of file assembler.h.
                                                               {
    switch (rep.value()) {
      case WordRepresentation::Word32():
        return Word32Constant(static_cast<uint32_t>(value));
      case WordRepresentation::Word64():
        return Word64Constant(value);
    }
  }
References v8::internal::compiler::turboshaft::WordRepresentation::value(), v8::internal::value, v8::internal::compiler::turboshaft::WordRepresentation::Word32(), and v8::internal::compiler::turboshaft::WordRepresentation::Word64().
WordPtrConstant()
template<typename Assembler >
V<WordPtr> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::WordPtrConstant (uintptr_t value) [inline]
Definition at line 2272 of file assembler.h.
                                              {
    return V<WordPtr>::Cast(WordConstant(value, WordRepresentation::WordPtr()));
  }
References v8::internal::compiler::turboshaft::V< T >::Cast(), v8::internal::value, and v8::internal::compiler::turboshaft::WordRepresentation::WordPtr().
ZeroExtendWord32ToRep()
template<typename Assembler >
Float32 Float64 Float64 Float32 Float32 Float64 Float64 Float64 Float64 Word32 V<Word> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ZeroExtendWord32ToRep (V< Word32 > value, WordRepresentation rep) [inline]
Definition at line 2491 of file assembler.h.
                                                                         {
    if (rep == WordRepresentation::Word32()) return value;
    DCHECK_EQ(rep, WordRepresentation::Word64());
    return ChangeUint32ToUint64(value);
  }
References DCHECK_EQ, v8::internal::value, v8::internal::compiler::turboshaft::WordRepresentation::Word32(), and v8::internal::compiler::turboshaft::WordRepresentation::Word64().
Member Data Documentation
Abs
template<typename Assembler >
v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Abs
Definition at line 1996 of file assembler.h.
cached_centry_stub_constants_
template<typename Assembler >
MaybeHandle<Code> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::cached_centry_stub_constants_[4] [private]
Definition at line 5324 of file assembler.h.
cached_parameters_
template<typename Assembler >
base::SmallVector<OpIndex, 16> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::cached_parameters_ [private]
Definition at line 5322 of file assembler.h.
Comparison [1/4]
template<typename Assembler >
v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Comparison
Definition at line 1842 of file assembler.h.
Comparison [2/4]
template<typename Assembler >
UnsignedLessThan v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Comparison
Definition at line 1852 of file assembler.h.
Comparison [3/4]
template<typename Assembler >
UnsignedLessThan SignedLessThanOrEqual Word64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Comparison
Definition at line 1860 of file assembler.h.
Comparison [4/4]
template<typename Assembler >
UnsignedLessThan SignedLessThanOrEqual Word64 UnsignedLessThanOrEqual Word64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Comparison
Definition at line 1868 of file assembler.h.
CountLeadingZeros [1/2]
template<typename Assembler >
Float Float Float32 Float v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CountLeadingZeros
Definition at line 1964 of file assembler.h.
CountLeadingZeros [2/2]
template<typename Assembler >
Float Float Float32 Float Word v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CountLeadingZeros
Definition at line 1967 of file assembler.h.
CountTrailingZeros
template<typename Assembler >
Float Float Float32 Float Word Word64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CountTrailingZeros
Definition at line 1972 of file assembler.h.
feedback
template<typename Assembler >
Word32 V<Word> V<turboshaft::FrameState> WordBinopDeoptOnOverflowOp::Kind WordRepresentation FeedbackSource v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::feedback
Definition at line 2009 of file assembler.h.
Float32 [1/2]
template<typename Assembler >
Float32 Float64 Float64 Float32 Float32 Float64 Float64 Float64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Float32
Definition at line 2486 of file assembler.h.
Float32 [2/2]
template<typename Assembler >
v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Float32
Definition at line 2567 of file assembler.h.
Float64 [1/3]
template<typename Assembler >
v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Float64
Definition at line 2591 of file assembler.h.
Float64 [2/3]
template<typename Assembler >
Word32 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Float64
Definition at line 2595 of file assembler.h.
Float64 [3/3]
template<typename Assembler >
Word32 Word64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Float64
Definition at line 2599 of file assembler.h.
FloatRepresentation [1/3]
template<typename Assembler >
v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::FloatRepresentation
Definition at line 1917 of file assembler.h.
FloatRepresentation [2/3]
template<typename Assembler >
Float v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::FloatRepresentation
Definition at line 1925 of file assembler.h.
FloatRepresentation [3/3]
template<typename Assembler >
Float Float Float32 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::FloatRepresentation
Definition at line 1936 of file assembler.h.
FloatUnary [1/4]
template<typename Assembler >
v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::FloatUnary
Definition at line 1917 of file assembler.h.
FloatUnary [2/4]
template<typename Assembler >
Float v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::FloatUnary
Definition at line 1925 of file assembler.h.
FloatUnary [3/4]
template<typename Assembler >
Float Float v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::FloatUnary
Definition at line 1931 of file assembler.h.
FloatUnary [4/4]
template<typename Assembler >
Float Float Float32 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::FloatUnary
Definition at line 1936 of file assembler.h.
frame_state
template<typename Assembler >
Word32 V<Word> V<turboshaft::FrameState> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::frame_state
Definition at line 2006 of file assembler.h.
HeapObject
template<typename Assembler >
V< T > v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::HeapObject
Initial value:
{
    return ReduceIfReachableConstant(ConstantOp::Kind::kHeapObject,
                                     ConstantOp::Storage{value})
Definition at line 2349 of file assembler.h.
in_object_initialization_
template<typename Assembler >
bool v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::in_object_initialization_ = false [private]
Definition at line 5325 of file assembler.h.
kBitcast [1/2]
template<typename Assembler >
v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::kBitcast
Definition at line 2452 of file assembler.h.
kBitcast [2/2]
template<typename Assembler >
Float32 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::kBitcast
Definition at line 2456 of file assembler.h.
kExtractHighHalf
template<typename Assembler >
Word32 Word64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::kExtractHighHalf
Definition at line 2598 of file assembler.h.
kFloatConversion
template<typename Assembler >
Float32 Float64 Float64 Float32 Float32 Float64 Float64 Float64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::kFloatConversion
Definition at line 2485 of file assembler.h.
kind [1/2]
template<typename Assembler >
Word32 Word Word64 Word32 V<Word32> ShiftOp::Kind v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::kind
Definition at line 1743 of file assembler.h.
kind [2/2]
template<typename Assembler >
Word32 V<Word> V<turboshaft::FrameState> WordBinopDeoptOnOverflowOp::Kind v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::kind
Definition at line 2007 of file assembler.h.
kNoAssumption [1/9]
template<typename Assembler >
v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::kNoAssumption
Definition at line 2452 of file assembler.h.
kNoAssumption [2/9]
template<typename Assembler >
Float32 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::kNoAssumption
Definition at line 2456 of file assembler.h.
kNoAssumption [3/9]
template<typename Assembler >
Float32 Float64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::kNoAssumption
Definition at line 2461 of file assembler.h.
kNoAssumption [4/9]
template<typename Assembler >
Float32 Float64 Float64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::kNoAssumption
Definition at line 2465 of file assembler.h.
kNoAssumption [5/9]
template<typename Assembler >
Float32 Float64 Float64 Float32 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::kNoAssumption
Definition at line 2469 of file assembler.h.
kNoAssumption [6/9]
template<typename Assembler >
Float32 Float64 Float64 Float32 Float32 Float64 Float64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::kNoAssumption
Definition at line 2481 of file assembler.h.
kNoAssumption [7/9]
template<typename Assembler >
Float32 Float64 Float64 Float32 Float32 Float64 Float64 Float64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::kNoAssumption
Definition at line 2485 of file assembler.h.
kNoAssumption [8/9]
template<typename Assembler >
Float32 Float64 Float64 Float32 Float32 Float64 Float64 Float64 Float64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::kNoAssumption
Definition at line 2489 of file assembler.h.
kNoAssumption [9/9]
template<typename Assembler >
Word32 Word64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::kNoAssumption
Definition at line 2598 of file assembler.h.
kReversible [1/4]
template<typename Assembler >
Float32 Float64 Float64 Float32 Float32 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::kReversible
Definition at line 2473 of file assembler.h.
kReversible [2/4]
template<typename Assembler >
Float32 Float64 Float64 Float32 Float32 Float64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::kReversible
Definition at line 2477 of file assembler.h.
kReversible [3/4]
template<typename Assembler >
v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::kReversible
Definition at line 2591 of file assembler.h.
kReversible [4/4]
template<typename Assembler >
Word32 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::kReversible
Definition at line 2595 of file assembler.h.
kSignedFloatTruncateOverflowToMin
template<typename Assembler >
v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::kSignedFloatTruncateOverflowToMin
Definition at line 2567 of file assembler.h.
kSignedToFloat [1/4]
template<typename Assembler >
Float32 Float64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::kSignedToFloat
Definition at line 2461 of file assembler.h.
kSignedToFloat [2/4]
template<typename Assembler >
Float32 Float64 Float64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::kSignedToFloat
Definition at line 2465 of file assembler.h.
kSignedToFloat [3/4]
template<typename Assembler >
Float32 Float64 Float64 Float32 Float32 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::kSignedToFloat
Definition at line 2473 of file assembler.h.
kSignedToFloat [4/4]
template<typename Assembler >
Float32 Float64 Float64 Float32 Float32 Float64 Float64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::kSignedToFloat
Definition at line 2481 of file assembler.h.
kTruncate
template<typename Assembler >
Float32 Float64 Float64 Float32 Float32 Float64 Float64 Float64 Float64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::kTruncate
Definition at line 2489 of file assembler.h.
kUnsignedFloatTruncateOverflowToMin [1/2]
template<typename Assembler >
v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::kUnsignedFloatTruncateOverflowToMin
Definition at line 2590 of file assembler.h.
kUnsignedFloatTruncateOverflowToMin [2/2]
template<typename Assembler >
Word32 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::kUnsignedFloatTruncateOverflowToMin
Definition at line 2594 of file assembler.h.
kUnsignedToFloat [1/2]
template<typename Assembler >
Float32 Float64 Float64 Float32 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::kUnsignedToFloat
Definition at line 2469 of file assembler.h.
kUnsignedToFloat [2/2]
template<typename Assembler >
Float32 Float64 Float64 Float32 Float32 Float64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::kUnsignedToFloat
Definition at line 2477 of file assembler.h.
matcher_
template<typename Assembler >
OperationMatcher v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::matcher_ [private]
Definition at line 5327 of file assembler.h.
mode
template<typename Assembler >
Word32 V<Word> V<turboshaft::FrameState> WordBinopDeoptOnOverflowOp::Kind WordRepresentation FeedbackSource CheckForMinusZeroMode v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::mode
Initial value:
{
    return ReduceIfReachableWordBinopDeoptOnOverflow(left, right, frame_state,
                                                     kind, rep, feedback, mode)
Definition at line 2010 of file assembler.h.
Object
template<typename Assembler >
V<Type> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Object
Initial value:
{
    return Load(object, LoadOp::Kind::TaggedBase(),
                MemoryRepresentation::AnyTagged(), field_offset)
Definition at line 3008 of file assembler.h.
OverflowCheckedBinop [1/4]
template<typename Assembler >
v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::OverflowCheckedBinop
Definition at line 1702 of file assembler.h.
OverflowCheckedBinop [2/4]
template<typename Assembler >
Word32 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::OverflowCheckedBinop
Definition at line 1706 of file assembler.h.
OverflowCheckedBinop [3/4]
template<typename Assembler >
Word32 Word v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::OverflowCheckedBinop
Definition at line 1710 of file assembler.h.
OverflowCheckedBinop [4/4]
template<typename Assembler >
Word32 Word Word64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::OverflowCheckedBinop
Definition at line 1714 of file assembler.h.
OverflowCheckedUnary
template<typename Assembler >
v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::OverflowCheckedUnary
Definition at line 1996 of file assembler.h.
PopCount
template<typename Assembler >
Float Float Float32 Float Word Word64 Word32 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::PopCount
Definition at line 1975 of file assembler.h.
RegisterRepresentation [1/4]
template<typename Assembler >
v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::RegisterRepresentation
Definition at line 1842 of file assembler.h.
RegisterRepresentation [2/4]
template<typename Assembler >
UnsignedLessThan v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::RegisterRepresentation
Definition at line 1852 of file assembler.h.
RegisterRepresentation [3/4]
template<typename Assembler >
UnsignedLessThan SignedLessThanOrEqual Word64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::RegisterRepresentation
Definition at line 1860 of file assembler.h.
RegisterRepresentation [4/4]
template<typename Assembler >
UnsignedLessThan SignedLessThanOrEqual Word64 UnsignedLessThanOrEqual Word64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::RegisterRepresentation
Definition at line 1868 of file assembler.h.
rep [1/3]
template<typename Assembler >
Word32 Word Word64 Word32 V<Word32> ShiftOp::Kind WordRepresentation v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::rep
Initial value:
{
    return ReduceIfReachableShift(left, right, kind, rep)
Definition at line 1744 of file assembler.h.
rep [2/3]
template<typename Assembler >
Word32 WordPtr Word32 WordPtr uint32_t WordRepresentation v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::rep
Initial value:
{
    DCHECK_GE(right, 0)
Definition at line 1787 of file assembler.h.
rep [3/3]
template<typename Assembler >
Word32 V<Word> V<turboshaft::FrameState> WordBinopDeoptOnOverflowOp::Kind WordRepresentation v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::rep
Definition at line 2008 of file assembler.h.
right [1/3]
template<typename Assembler >
Word32 Word Word64 Word32 V<Word32> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::right
Definition at line 1743 of file assembler.h.
right [2/3]
template<typename Assembler >
Word32 WordPtr Word32 WordPtr uint32_t v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::right
Definition at line 1786 of file assembler.h.
right [3/3]
template<typename Assembler >
Word32 V<Word> v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::right
Definition at line 2005 of file assembler.h.
RoundDown
template<typename Assembler >
v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::RoundDown
Definition at line 1918 of file assembler.h.
RoundTiesEven
template<typename Assembler >
Float Float v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::RoundTiesEven
Definition at line 1931 of file assembler.h.
RoundToZero
template<typename Assembler >
Float v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::RoundToZero
Definition at line 1926 of file assembler.h.
ShiftRightArithmetic [1/2]
template<typename Assembler >
Word32 WordPtr v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ShiftRightArithmetic
Definition at line 1764 of file assembler.h.
ShiftRightArithmetic [2/2]
template<typename Assembler >
Word32 WordPtr Word32 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ShiftRightArithmetic
Definition at line 1768 of file assembler.h.
ShiftRightArithmeticShiftOutZeros [1/2]
template<typename Assembler >
v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ShiftRightArithmeticShiftOutZeros
Definition at line 1757 of file assembler.h.
ShiftRightArithmeticShiftOutZeros [2/2]
template<typename Assembler >
Word32 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ShiftRightArithmeticShiftOutZeros
Definition at line 1761 of file assembler.h.
SignedAdd
template<typename Assembler >
v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::SignedAdd
Definition at line 1703 of file assembler.h.
SignedLessThanOrEqual [1/2]
template<typename Assembler >
UnsignedLessThan SignedLessThanOrEqual v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::SignedLessThanOrEqual
Definition at line 1856 of file assembler.h.
SignedLessThanOrEqual [2/2]
template<typename Assembler >
UnsignedLessThan SignedLessThanOrEqual Word64 UnsignedLessThanOrEqual Word64 SignedLessThanOrEqual v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::SignedLessThanOrEqual
Definition at line 1872 of file assembler.h.
SignedMul
template<typename Assembler >
Word32 Word Word64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::SignedMul
Definition at line 1715 of file assembler.h.
SignedMulOverflownBits
template<typename Assembler >
v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::SignedMulOverflownBits
Definition at line 1663 of file assembler.h.
SignedSub [1/2]
template<typename Assembler >
Word32 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::SignedSub
Definition at line 1707 of file assembler.h.
SignedSub [2/2]
template<typename Assembler >
Word32 Word v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::SignedSub
Definition at line 1711 of file assembler.h.
SignExtend16
template<typename Assembler >
Float Float Float32 Float Word Word64 Word32 Word v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::SignExtend16
Definition at line 1984 of file assembler.h.
Sqrt
template<typename Assembler >
Float Float Float32 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Sqrt
Definition at line 1936 of file assembler.h.
UnsignedLessThanOrEqual
template<typename Assembler >
UnsignedLessThan SignedLessThanOrEqual Word64 UnsignedLessThanOrEqual v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::UnsignedLessThanOrEqual
Definition at line 1864 of file assembler.h.
UnsignedMulOverflownBits [1/2]
template<typename Assembler >
Word32 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::UnsignedMulOverflownBits
Definition at line 1667 of file assembler.h.
UnsignedMulOverflownBits [2/2]
template<typename Assembler >
Word32 Word v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::UnsignedMulOverflownBits
Definition at line 1671 of file assembler.h.
Word32 [1/4]
template<typename Assembler >
v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Word32
Definition at line 2452 of file assembler.h.
Word32 [2/4]
template<typename Assembler >
Float32 Float64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Word32
Definition at line 2461 of file assembler.h.
Word32 [3/4]
template<typename Assembler >
Float32 Float64 Float64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Word32
Definition at line 2465 of file assembler.h.
Word32 [4/4]
template<typename Assembler >
Float32 Float64 Float64 Float32 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Word32
Definition at line 2469 of file assembler.h.
Word64 [1/4]
template<typename Assembler >
Float32 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Word64
Definition at line 2456 of file assembler.h.
Word64 [2/4]
template<typename Assembler >
Float32 Float64 Float64 Float32 Float32 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Word64
Definition at line 2473 of file assembler.h.
Word64 [3/4]
template<typename Assembler >
Float32 Float64 Float64 Float32 Float32 Float64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Word64
Definition at line 2478 of file assembler.h.
Word64 [4/4]
template<typename Assembler >
Float32 Float64 Float64 Float32 Float32 Float64 Float64 Float64 Float64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Word64
Definition at line 2489 of file assembler.h.
WordBinop [1/3]
template<typename Assembler >
v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::WordBinop
Definition at line 1662 of file assembler.h.
WordBinop [2/3]
template<typename Assembler >
Word32 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::WordBinop
Definition at line 1666 of file assembler.h.
WordBinop [3/3]
template<typename Assembler >
Word32 Word v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::WordBinop
Definition at line 1670 of file assembler.h.
WordPtr
template<typename Assembler >
Float32 Float64 Float64 Float32 Float32 Float64 Float64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::WordPtr
Definition at line 2481 of file assembler.h.
WordRepresentation [1/3]
template<typename Assembler >
Float Float Float32 Float v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::WordRepresentation
Definition at line 1963 of file assembler.h.
WordRepresentation [2/3]
template<typename Assembler >
Float Float Float32 Float Word Word64 Word32 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::WordRepresentation
Definition at line 1975 of file assembler.h.
WordRepresentation [3/3]
template<typename Assembler >
Float Float Float32 Float Word Word64 Word32 Word v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::WordRepresentation
Definition at line 1983 of file assembler.h.
WordUnary [1/5]
template<typename Assembler >
Float Float Float32 Float v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::WordUnary
Definition at line 1963 of file assembler.h.
WordUnary [2/5]
template<typename Assembler >
Float Float Float32 Float Word v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::WordUnary
Definition at line 1967 of file assembler.h.
WordUnary [3/5]
template<typename Assembler >
Float Float Float32 Float Word Word64 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::WordUnary
Definition at line 1971 of file assembler.h.
WordUnary [4/5]
template<typename Assembler >
Float Float Float32 Float Word Word64 Word32 v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::WordUnary
Definition at line 1975 of file assembler.h.
WordUnary [5/5]
template<typename Assembler >
Float Float Float32 Float Word Word64 Word32 Word v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::WordUnary
Definition at line 1983 of file assembler.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/assembler.h