v8::internal::compiler::HeapObjectData Class Reference
Public Member Functions
HeapObjectData (JSHeapBroker *broker, ObjectData **storage, IndirectHandle< HeapObject > object, ObjectDataKind kind)
std::optional< bool > TryGetBooleanValue (JSHeapBroker *broker) const
ObjectData * map () const
InstanceType GetMapInstanceType () const
Private Member Functions
std::optional< bool > TryGetBooleanValueImpl (JSHeapBroker *broker) const
Private Attributes
ObjectData * map_
Detailed Description
Definition at line 146 of file heap-refs.cc.
Constructor & Destructor Documentation
HeapObjectData()
v8::internal::compiler::HeapObjectData::HeapObjectData (JSHeapBroker * broker, ObjectData ** storage, IndirectHandle< HeapObject > object, ObjectDataKind kind)
Definition at line 781 of file heap-refs.cc.
    : ObjectData(broker, storage, object, kind), map_(nullptr) {
  // At this point, this object may already be in the RefsMap. GetOrCreateData
  // will lookup objects in there. If (e.g. due to in-sandbox corruption) the
  // object graph is such that we end up retrieving ourselves from the RefsMap
  // in the recursive GetOrCreateData call, then we'll see uninitialized data
  // for the map_ field. To avoid this, initialize it to nullptr first.
  map_ = broker->GetOrCreateData(object->map(broker->cage_base(), kAcquireLoad),
                                 kAssumeMemoryFence);
  CHECK_IMPLIES(broker->mode() == JSHeapBroker::kSerialized,
                kind == kBackgroundSerializedHeapObject);
}
References broker(), CHECK_IMPLIES, v8::kAcquireLoad, v8::internal::compiler::kAssumeMemoryFence, v8::internal::compiler::kBackgroundSerializedHeapObject, v8::internal::compiler::ObjectData::kind(), v8::internal::compiler::JSHeapBroker::kSerialized, map_, and v8::internal::compiler::ObjectData::object().
Member Function Documentation
GetMapInstanceType()
InstanceType v8::internal::compiler::HeapObjectData::GetMapInstanceType () const
Definition at line 831 of file heap-refs.cc.
                                                      {
  ObjectData* map_data = map();
  if (map_data->should_access_heap()) {
    // The map instance type is used to check if a static_cast to the right
    // subclass is valid. We shouldn't read the value from the heap except if
    // it's coming from the ReadOnly pages.
    SBXCHECK_EQ(map_data->kind(), kUnserializedReadOnlyHeapObject);
    return Cast<Map>(map_data->object())->instance_type();
  }
  if (this == map_data) {
    // Handle infinite recursion in case this object is a contextful meta map.
    return MAP_TYPE;
  }
  return map_data->AsMap()->instance_type();
}
References v8::internal::compiler::ObjectData::kind(), v8::internal::compiler::kUnserializedReadOnlyHeapObject, map(), v8::internal::compiler::ObjectData::object(), SBXCHECK_EQ, and v8::internal::compiler::ObjectData::should_access_heap().
Referenced by TryGetBooleanValueImpl().
map()
ObjectData* v8::internal::compiler::HeapObjectData::map () const [inline]
Definition at line 152 of file heap-refs.cc.
{ return map_; }
References map_.
Referenced by GetMapInstanceType(), and TryGetBooleanValueImpl().
TryGetBooleanValue()
std::optional< bool > v8::internal::compiler::HeapObjectData::TryGetBooleanValue (JSHeapBroker * broker) const
Definition at line 796 of file heap-refs.cc.
                                {
  // Keep in sync with Object::BooleanValue.
  auto result = TryGetBooleanValueImpl(broker);
  DCHECK_IMPLIES(
      broker->IsMainThread() && result.has_value(),
      result.value() == Object::BooleanValue(*object(), broker->isolate()));
  return result;
}
References v8::internal::Object::BooleanValue(), broker(), DCHECK_IMPLIES, v8::base::internal::result, and TryGetBooleanValueImpl().
TryGetBooleanValueImpl()
std::optional< bool > v8::internal::compiler::HeapObjectData::TryGetBooleanValueImpl (JSHeapBroker * broker) const [private]
Definition at line 806 of file heap-refs.cc.
                                {
  DisallowGarbageCollection no_gc;
  Tagged<Object> o = *object();
  Isolate* isolate = broker->isolate();
  const InstanceType t = GetMapInstanceType();
  if (IsTrue(o, isolate)) {
    return true;
  } else if (IsFalse(o, isolate)) {
    return false;
  } else if (IsNullOrUndefined(o, isolate)) {
    return false;
  } else if (MapRef{map()}.is_undetectable()) {
    return false; // Undetectable object is false.
  } else if (InstanceTypeChecker::IsString(t)) {
    // TODO(jgruber): Implement in possible cases.
    return {};
  } else if (InstanceTypeChecker::IsHeapNumber(t)) {
    return {};
  } else if (InstanceTypeChecker::IsBigInt(t)) {
    return {};
  }
  return true;
}
References broker(), GetMapInstanceType(), v8::internal::IsNullOrUndefined(), map(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::compiler::ObjectData::object().
Referenced by TryGetBooleanValue().
Member Data Documentation
map_
ObjectData* v8::internal::compiler::HeapObjectData::map_ [private]
Definition at line 158 of file heap-refs.cc.
Referenced by HeapObjectData(), and map().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/heap-refs.cc