v8::internal::JSListFormat Class Reference
#include <js-list-format.h>
Public Types
enum class Style { LONG
, SHORT
, NARROW
 }
enum class Type { CONJUNCTION
, DISJUNCTION
, UNIT
 }
Public Member Functions
Handle< String > StyleAsString (Isolate *isolate) const
Handle< String > TypeAsString (Isolate *isolate) const
void set_style (Style style)
Style style () const
void set_type (Type type)
Type type () const
Static Public Member Functions
static MaybeDirectHandle< JSListFormat > New (Isolate *isolate, DirectHandle< Map > map, DirectHandle< Object > locales, DirectHandle< Object > options)
static DirectHandle< JSObject > ResolvedOptions (Isolate *isolate, DirectHandle< JSListFormat > format_holder)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > FormatList (Isolate *isolate, DirectHandle< JSListFormat > format_holder, DirectHandle< FixedArray > list)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSArray > FormatListToParts (Isolate *isolate, DirectHandle< JSListFormat > format_holder, DirectHandle< FixedArray > list)
static V8_EXPORT_PRIVATE const std::set< std::string > & GetAvailableLocales ()
Detailed Description
Definition at line 34 of file js-list-format.h.
Member Enumeration Documentation
Style
enum v8::internal::JSListFormat::Style [strong]
Enumerator
LONG
SHORT
NARROW
Definition at line 68 of file js-list-format.h.
                   {
    LONG, // Everything spelled out.
    SHORT, // Abbreviations used when possible.
    NARROW // Use the shortest possible form.
  };
Type
enum v8::internal::JSListFormat::Type [strong]
Enumerator
CONJUNCTION
DISJUNCTION
UNIT
Definition at line 79 of file js-list-format.h.
                  {
    CONJUNCTION, // for "and"-based lists (e.g., "A, B and C")
    DISJUNCTION, // for "or"-based lists (e.g., "A, B or C"),
    UNIT // for lists of values with units (e.g., "5 pounds, 12 ounces").
  };
Member Function Documentation
FormatList()
MaybeDirectHandle< String > v8::internal::JSListFormat::FormatList (Isolate * isolate, DirectHandle< JSListFormat > format_holder, DirectHandle< FixedArray > list) [static]
Definition at line 280 of file js-list-format.cc.
                                   {
  return FormatListCommon<String>(isolate, format, list,
                                  Intl::FormattedToString);
}
References v8::internal::format, and v8::internal::Intl::FormattedToString().
Referenced by v8::internal::RUNTIME_FUNCTION().
FormatListToParts()
MaybeDirectHandle< JSArray > v8::internal::JSListFormat::FormatListToParts (Isolate * isolate, DirectHandle< JSListFormat > format_holder, DirectHandle< FixedArray > list) [static]
Definition at line 288 of file js-list-format.cc.
                                   {
  return FormatListCommon<JSArray>(isolate, format, list,
                                   FormattedListToJSArray);
}
References v8::internal::format, and v8::internal::FormattedListToJSArray().
Referenced by v8::internal::RUNTIME_FUNCTION().
GetAvailableLocales()
const std::set< std::string > & v8::internal::JSListFormat::GetAvailableLocales () [static]
Definition at line 304 of file js-list-format.cc.
                                                           {
  static base::LazyInstance<Intl::AvailableLocales<CheckListPattern>>::type
      available_locales = LAZY_INSTANCE_INITIALIZER;
  return available_locales.Pointer()->Get();
}
References LAZY_INSTANCE_INITIALIZER, and type().
Referenced by v8::internal::BUILTIN(), and New().
New()
MaybeDirectHandle< JSListFormat > v8::internal::JSListFormat::New (Isolate * isolate, DirectHandle< Map > map, DirectHandle< Object > locales, DirectHandle< Object > options) [static]
Definition at line 60 of file js-list-format.cc.
                                        {
  // 3. Let requestedLocales be ? CanonicalizeLocaleList(locales).
  Maybe<std::vector<std::string>> maybe_requested_locales =
      Intl::CanonicalizeLocaleList(isolate, locales);
  MAYBE_RETURN(maybe_requested_locales, DirectHandle<JSListFormat>());
  std::vector<std::string> requested_locales =
      maybe_requested_locales.FromJust();
  DirectHandle<JSReceiver> options;
  const char* service = "Intl.ListFormat";
  // 4. Let options be GetOptionsObject(_options_).
  ASSIGN_RETURN_ON_EXCEPTION(isolate, options,
                             GetOptionsObject(isolate, input_options, service));
  // Note: No need to create a record. It's not observable.
  // 6. Let opt be a new Record.
  // 7. Let matcher be ? GetOption(options, "localeMatcher", "string", «
  // "lookup", "best fit" », "best fit").
  Maybe<Intl::MatcherOption> maybe_locale_matcher =
      Intl::GetLocaleMatcher(isolate, options, service);
  MAYBE_RETURN(maybe_locale_matcher, MaybeDirectHandle<JSListFormat>());
  // 8. Set opt.[[localeMatcher]] to matcher.
  Intl::MatcherOption matcher = maybe_locale_matcher.FromJust();
  // 10. Let r be ResolveLocale(%ListFormat%.[[AvailableLocales]],
  // requestedLocales, opt, undefined, localeData).
  Intl::ResolvedLocale r;
  if (!Intl::ResolveLocale(isolate, JSListFormat::GetAvailableLocales(),
                           requested_locales, matcher, {})
           .To(&r)) {
    THROW_NEW_ERROR(isolate, NewRangeError(MessageTemplate::kIcuError));
  }
  DirectHandle<String> locale_str =
      isolate->factory()->NewStringFromAsciiChecked(r.locale.c_str());
  // 12. Let t be GetOption(options, "type", "string", «"conjunction",
  // "disjunction", "unit"», "conjunction").
  Maybe<Type> maybe_type = GetStringOption<Type>(
      isolate, options, "type", service,
      std::to_array<const std::string_view>(
          {"conjunction", "disjunction", "unit"}),
      std::array{Type::CONJUNCTION, Type::DISJUNCTION, Type::UNIT},
      Type::CONJUNCTION);
  MAYBE_RETURN(maybe_type, MaybeDirectHandle<JSListFormat>());
  Type type_enum = maybe_type.FromJust();
  // 14. Let s be ? GetOption(options, "style", "string",
  // «"long", "short", "narrow"», "long").
  Maybe<Style> maybe_style = GetStringOption<Style>(
      isolate, options, "style", service,
      std::to_array<const std::string_view>({"long", "short", "narrow"}),
      std::array{Style::LONG, Style::SHORT, Style::NARROW}, Style::LONG);
  MAYBE_RETURN(maybe_style, MaybeDirectHandle<JSListFormat>());
  Style style_enum = maybe_style.FromJust();
  icu::Locale icu_locale = r.icu_locale;
  UErrorCode status = U_ZERO_ERROR;
  std::shared_ptr<icu::ListFormatter> formatter{
      icu::ListFormatter::createInstance(icu_locale, GetIcuType(type_enum),
                                         GetIcuWidth(style_enum), status)};
  if (U_FAILURE(status) || formatter == nullptr) {
    THROW_NEW_ERROR(isolate, NewRangeError(MessageTemplate::kIcuError));
  }
  DirectHandle<Managed<icu::ListFormatter>> managed_formatter =
      Managed<icu::ListFormatter>::From(isolate, 0, std::move(formatter));
  // Now all properties are ready, so we can allocate the result object.
  DirectHandle<JSListFormat> list_format =
      Cast<JSListFormat>(isolate->factory()->NewFastOrSlowJSObjectFromMap(map));
  DisallowGarbageCollection no_gc;
  list_format->set_flags(0);
  list_format->set_icu_formatter(*managed_formatter);
  // 11. Set listFormat.[[Locale]] to r.[[Locale]].
  list_format->set_locale(*locale_str);
  // 13. Set listFormat.[[Type]] to t.
  list_format->set_type(type_enum);
  // 15. Set listFormat.[[Style]] to s.
  list_format->set_style(style_enum);
  return list_format;
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Intl::CanonicalizeLocaleList(), CONJUNCTION, DISJUNCTION, v8::internal::Isolate::factory(), v8::internal::Managed< CppType >::From(), v8::Maybe< T >::FromJust(), GetAvailableLocales(), v8::internal::anonymous_namespace{js-list-format.cc}::GetIcuType(), v8::internal::anonymous_namespace{js-list-format.cc}::GetIcuWidth(), v8::internal::Intl::GetLocaleMatcher(), v8::internal::GetOptionsObject(), v8::internal::Intl::ResolvedLocale::icu_locale, v8::internal::Intl::ResolvedLocale::locale, LONG, MAYBE_RETURN, NARROW, v8::internal::Factory::NewFastOrSlowJSObjectFromMap(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Intl::ResolveLocale(), SHORT, v8::internal::status, THROW_NEW_ERROR, and UNIT.
ResolvedOptions()
DirectHandle< JSObject > v8::internal::JSListFormat::ResolvedOptions (Isolate * isolate, DirectHandle< JSListFormat > format_holder) [static]
Definition at line 152 of file js-list-format.cc.
                                                         {
  Factory* factory = isolate->factory();
  // 4. Let options be ! ObjectCreate(%ObjectPrototype%).
  DirectHandle<JSObject> result =
      factory->NewJSObject(isolate->object_function());
  // 5. For each row of Table 1, except the header row, do
  // Table 1: Resolved Options of ListFormat Instances
  // Internal Slot Property
  // [[Locale]] "locale"
  // [[Type]] "type"
  // [[Style]] "style"
  DirectHandle<String> locale(format->locale(), isolate);
  JSObject::AddProperty(isolate, result, factory->locale_string(), locale,
                        NONE);
  JSObject::AddProperty(isolate, result, factory->type_string(),
                        format->TypeAsString(isolate), NONE);
  JSObject::AddProperty(isolate, result, factory->style_string(),
                        format->StyleAsString(isolate), NONE);
  // 6. Return options.
  return result;
}
References v8::internal::JSObject::AddProperty(), v8::internal::Isolate::factory(), v8::internal::format, v8::internal::Factory::NewJSObject(), v8::internal::NONE, and v8::base::internal::result.
Referenced by v8::internal::BUILTIN().
set_style()
void v8::internal::JSListFormat::set_style (Style style) [inline]
set_type()
void v8::internal::JSListFormat::set_type (Type type) [inline]
Definition at line 42 of file js-list-format-inl.h.
                                            {
  DCHECK(TypeBits::is_valid(type));
  int hints = flags();
  hints = TypeBits::update(hints, type);
  set_flags(hints);
}
References v8::internal::DCHECK(), v8::internal::flags, and type().
style()
JSListFormat::Style v8::internal::JSListFormat::style () const [inline]
Definition at line 38 of file js-list-format-inl.h.
                                                   {
  return StyleBits::decode(flags());
}
References v8::internal::flags.
Referenced by StyleAsString().
StyleAsString()
Handle< String > v8::internal::JSListFormat::StyleAsString (Isolate * isolate) const
Definition at line 176 of file js-list-format.cc.
                                                                 {
  switch (style()) {
    case Style::LONG:
      return isolate->factory()->long_string();
    case Style::SHORT:
      return isolate->factory()->short_string();
    case Style::NARROW:
      return isolate->factory()->narrow_string();
  }
  UNREACHABLE();
}
References v8::internal::Isolate::factory(), LONG, NARROW, SHORT, style(), and v8::internal::UNREACHABLE().
type()
JSListFormat::Type v8::internal::JSListFormat::type () const [inline]
Definition at line 49 of file js-list-format-inl.h.
                                                 {
  return TypeBits::decode(flags());
}
References v8::internal::flags.
Referenced by GetAvailableLocales(), set_type(), and TypeAsString().
TypeAsString()
Handle< String > v8::internal::JSListFormat::TypeAsString (Isolate * isolate) const
Definition at line 188 of file js-list-format.cc.
                                                                {
  switch (type()) {
    case Type::CONJUNCTION:
      return isolate->factory()->conjunction_string();
    case Type::DISJUNCTION:
      return isolate->factory()->disjunction_string();
    case Type::UNIT:
      return isolate->factory()->unit_string();
  }
  UNREACHABLE();
}
References CONJUNCTION, DISJUNCTION, v8::internal::Isolate::factory(), type(), UNIT, and v8::internal::UNREACHABLE().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-list-format.h
/mnt/V8SourceCode/src/objects/js-list-format-inl.h
/mnt/V8SourceCode/src/objects/js-list-format.cc