v8::internal::compiler::LoadElimination Class Reference
#include <load-elimination.h>
Classes
class AbstractElements
class AbstractField
class AbstractMaps
class AbstractState
class AbstractStateForEffectNodes
class AliasStateInfo
struct FieldInfo
class IndexRange
Public Member Functions
LoadElimination (Editor *editor, JSHeapBroker *broker, JSGraph *jsgraph, Zone *zone)
~LoadElimination () final=default
LoadElimination (const LoadElimination &)=delete
LoadElimination & operator= (const LoadElimination &)=delete
const char * reducer_name () const override
Reduction Reduce (Node *node) final
Private Member Functions
Reduction ReduceCheckMaps (Node *node)
Reduction ReduceCompareMaps (Node *node)
Reduction ReduceMapGuard (Node *node)
Reduction ReduceEnsureWritableFastElements (Node *node)
Reduction ReduceMaybeGrowFastElements (Node *node)
Reduction ReduceTransitionElementsKind (Node *node)
Reduction ReduceTransitionElementsKindOrCheckMap (Node *node)
Reduction ReduceLoadField (Node *node, FieldAccess const &access)
Reduction ReduceStoreField (Node *node, FieldAccess const &access)
Reduction ReduceLoadElement (Node *node)
Reduction ReduceStoreElement (Node *node)
Reduction ReduceTransitionAndStoreElement (Node *node)
Reduction ReduceStoreTypedElement (Node *node)
Reduction ReduceEffectPhi (Node *node)
Reduction ReduceStart (Node *node)
Reduction ReduceOtherNode (Node *node)
Reduction UpdateState (Node *node, AbstractState const *state)
AbstractState const * ComputeLoopState (Node *node, AbstractState const *state) const
AbstractState const * ComputeLoopStateForStoreField (Node *current, LoadElimination::AbstractState const *state, FieldAccess const &access) const
AbstractState const * UpdateStateForPhi (AbstractState const *state, Node *effect_phi, Node *phi)
CommonOperatorBuilder * common () const
Isolate * isolate () const
Factory * factory () const
TFGraph * graph () const
JSGraph * jsgraph () const
JSHeapBroker * broker () const
Zone * zone () const
Static Private Member Functions
static IndexRange FieldIndexOf (int offset, int representation_size)
static IndexRange FieldIndexOf (FieldAccess const &access)
static AbstractState const * empty_state ()
Private Attributes
JSHeapBroker * broker_
AbstractStateForEffectNodes node_states_
JSGraph *const jsgraph_
Static Private Attributes
static const size_t kMaxTrackedElements = 8
static size_t const kMaxTrackedFieldsPerObject = 32
static size_t const kMaxTrackedObjects = 100
static int const kMaxTrackedFields = 300
Detailed Description
Definition at line 29 of file load-elimination.h.
Constructor & Destructor Documentation
LoadElimination() [1/2]
v8::internal::compiler::LoadElimination::LoadElimination (Editor * editor, JSHeapBroker * broker, JSGraph * jsgraph, Zone * zone) [inline]
Definition at line 32 of file load-elimination.h.
      : AdvancedReducer(editor),
        broker_(broker),
        node_states_(zone),
        jsgraph_(jsgraph) {}
 LoadElimination()
v8::internal::compiler::LoadElimination::~LoadElimination () [final], [default]
LoadElimination() [2/2]
v8::internal::compiler::LoadElimination::LoadElimination (const LoadElimination &) [delete]
Member Function Documentation
broker()
JSHeapBroker* v8::internal::compiler::LoadElimination::broker () const [inline], [private]
Definition at line 366 of file load-elimination.h.
{ return broker_; }
Referenced by ReduceEnsureWritableFastElements(), and ReduceMaybeGrowFastElements().
common()
CommonOperatorBuilder * v8::internal::compiler::LoadElimination::common () const [private]
Definition at line 1568 of file load-elimination.cc.
                                                     {
  return jsgraph()->common();
}
References v8::internal::compiler::MachineGraph::common(), and jsgraph().
Referenced by ReduceLoadField(), and ReduceStoreField().
ComputeLoopState()
LoadElimination::AbstractState const * v8::internal::compiler::LoadElimination::ComputeLoopState (Node * node, AbstractState const * state) const [private]
Definition at line 1363 of file load-elimination.cc.
                                                  {
  Node* const control = NodeProperties::GetControlInput(node);
  struct TransitionElementsKindInfo {
    ElementsTransition transition;
    Node* object;
  };
  // Allocate zone data structures in a temporary zone with a lifetime limited
  // to this function to avoid blowing up the size of the stage-global zone.
  Zone temp_zone(zone()->allocator(), "Temporary scoped zone");
  ZoneVector<TransitionElementsKindInfo> element_transitions_(&temp_zone);
  ZoneQueue<Node*> queue(&temp_zone);
  ZoneSet<Node*> visited(&temp_zone);
  visited.insert(node);
  for (int i = 1; i < control->InputCount(); ++i) {
    queue.push(node->InputAt(i));
  }
  while (!queue.empty()) {
    Node* const current = queue.front();
    queue.pop();
    if (visited.find(current) == visited.end()) {
      visited.insert(current);
      if (!current->op()->HasProperty(Operator::kNoWrite)) {
        switch (current->opcode()) {
          case IrOpcode::kEnsureWritableFastElements: {
            Node* const object = NodeProperties::GetValueInput(current, 0);
            state = state->KillField(
                object, FieldIndexOf(JSObject::kElementsOffset, kTaggedSize),
                MaybeHandle<Name>(), zone());
            break;
          }
          case IrOpcode::kMaybeGrowFastElements: {
            Node* const object = NodeProperties::GetValueInput(current, 0);
            state = state->KillField(
                object, FieldIndexOf(JSObject::kElementsOffset, kTaggedSize),
                MaybeHandle<Name>(), zone());
            break;
          }
          case IrOpcode::kTransitionElementsKind: {
            ElementsTransition transition = ElementsTransitionOf(current->op());
            Node* const object = NodeProperties::GetValueInput(current, 0);
            ZoneRefSet<Map> object_maps;
            if (!state->LookupMaps(object, &object_maps) ||
                !ZoneRefSet<Map>(transition.target()).contains(object_maps)) {
              element_transitions_.push_back({transition, object});
            }
            break;
          }
          case IrOpcode::kTransitionElementsKindOrCheckMap: {
            ElementsTransitionWithMultipleSources transition =
                ElementsTransitionWithMultipleSourcesOf(current->op());
            Node* const object = NodeProperties::GetValueInput(current, 0);
            ZoneRefSet<Map> object_maps;
            MapRef target = transition.target();
            if (!state->LookupMaps(object, &object_maps) ||
                !ZoneRefSet<Map>(target).contains(object_maps)) {
              for (MapRef source : transition.sources()) {
                ElementsTransition::Mode mode =
                    IsSimpleMapChangeTransition(source.elements_kind(),
                                                target.elements_kind())
                        ? ElementsTransition::kFastTransition
                        : ElementsTransition::kSlowTransition;
                element_transitions_.push_back(
                    {ElementsTransition(mode, source, target), object});
              }
            }
            break;
          }
          case IrOpcode::kTransitionAndStoreElement: {
            Node* const object = NodeProperties::GetValueInput(current, 0);
            // Invalidate what we know about the {object}s map.
            state = state->KillMaps(object, zone());
            // Kill the elements as well.
            state = state->KillField(
                object, FieldIndexOf(JSObject::kElementsOffset, kTaggedSize),
                MaybeHandle<Name>(), zone());
            break;
          }
          case IrOpcode::kStoreField: {
            FieldAccess access = FieldAccessOf(current->op());
            state = ComputeLoopStateForStoreField(current, state, access);
            break;
          }
          case IrOpcode::kStoreElement: {
            Node* const object = NodeProperties::GetValueInput(current, 0);
            Node* const index = NodeProperties::GetValueInput(current, 1);
            state = state->KillElement(object, index, zone());
            break;
          }
          case IrOpcode::kCheckMaps:
          case IrOpcode::kStoreTypedElement: {
            // Doesn't affect anything we track with the state currently.
            break;
          }
          default:
            return state->KillAll(zone());
        }
      }
      for (int i = 0; i < current->op()->EffectInputCount(); ++i) {
        queue.push(NodeProperties::GetEffectInput(current, i));
      }
    }
  }
  // Finally, we apply the element transitions. For each transition, we will try
  // to only invalidate information about nodes that can have the transition's
  // source map. The trouble is that an object can be transitioned by some other
  // transition to the source map. In that case, the other transition will
  // invalidate the information, so we are mostly fine.
  //
  // The only bad case is
  //
  // mapA ---fast---> mapB ---slow---> mapC
  //
  // If we process the slow transition first on an object that has mapA, we will
  // ignore the transition because the object does not have its source map
  // (mapB). When we later process the fast transition, we invalidate the
  // object's map, but we keep the information about the object's elements. This
  // is wrong because the elements will be overwritten by the slow transition.
  //
  // Note that the slow-slow case is fine because either of the slow transition
  // will invalidate the elements field, so the processing order does not
  // matter.
  //
  // To handle the bad case properly, we first kill the maps using all
  // transitions. We kill the the fields later when all the transitions are
  // already reflected in the map information.
  for (const TransitionElementsKindInfo& t : element_transitions_) {
    AliasStateInfo alias_info(state, t.object, t.transition.source());
    state = state->KillMaps(alias_info, zone());
  }
  for (const TransitionElementsKindInfo& t : element_transitions_) {
    switch (t.transition.mode()) {
      case ElementsTransition::kFastTransition:
        break;
      case ElementsTransition::kSlowTransition: {
        AliasStateInfo alias_info(state, t.object, t.transition.source());
        state = state->KillField(
            alias_info, FieldIndexOf(JSObject::kElementsOffset, kTaggedSize),
            MaybeHandle<Name>(), zone());
        break;
      }
    }
  }
  return state;
}
References ComputeLoopStateForStoreField(), v8::internal::ZoneCompactSet< T >::contains(), v8::internal::compiler::MapRef::elements_kind(), v8::internal::compiler::ElementsTransitionOf(), v8::internal::compiler::ElementsTransitionWithMultipleSourcesOf(), v8::internal::compiler::FieldAccessOf(), FieldIndexOf(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::Operator::HasProperty(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::InputCount(), v8::internal::IsSimpleMapChangeTransition(), v8::internal::compiler::ElementsTransition::kFastTransition, v8::internal::compiler::LoadElimination::AbstractState::KillAll(), v8::internal::compiler::LoadElimination::AbstractState::KillElement(), v8::internal::compiler::LoadElimination::AbstractState::KillField(), v8::internal::compiler::LoadElimination::AbstractState::KillMaps(), v8::internal::compiler::Operator::kNoWrite, v8::internal::compiler::ElementsTransition::kSlowTransition, v8::internal::kTaggedSize, v8::internal::compiler::LoadElimination::AbstractState::LookupMaps(), mode(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::ZoneVector< T >::push_back(), v8::internal::compiler::ElementsTransitionWithMultipleSources::sources(), v8::internal::compiler::ElementsTransition::target(), v8::internal::compiler::ElementsTransitionWithMultipleSources::target(), and zone().
Referenced by ReduceEffectPhi().
ComputeLoopStateForStoreField()
LoadElimination::AbstractState const * v8::internal::compiler::LoadElimination::ComputeLoopStateForStoreField (Node * current, LoadElimination::AbstractState const * state, FieldAccess const & access) const [private]
Definition at line 1345 of file load-elimination.cc.
                                     {
  Node* const object = NodeProperties::GetValueInput(current, 0);
  if (access.offset == HeapObject::kMapOffset) {
    // Invalidate what we know about the {object}s map.
    state = state->KillMaps(object, zone());
  } else {
    IndexRange field_index = FieldIndexOf(access);
    if (field_index == IndexRange::Invalid()) {
      state = state->KillFields(object, access.name, zone());
    } else {
      state = state->KillField(object, field_index, access.name, zone());
    }
  }
  return state;
}
References FieldIndexOf(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::LoadElimination::IndexRange::Invalid(), v8::internal::compiler::LoadElimination::AbstractState::KillField(), v8::internal::compiler::LoadElimination::AbstractState::KillFields(), v8::internal::compiler::LoadElimination::AbstractState::KillMaps(), v8::internal::HeapObject::kMapOffset, v8::internal::compiler::FieldAccess::name, v8::internal::compiler::FieldAccess::offset, and zone().
Referenced by ComputeLoopState().
empty_state()
static AbstractState const* v8::internal::compiler::LoadElimination::empty_state () [inline], [static], [private]
Definition at line 357 of file load-elimination.h.
                                            {
    return AbstractState::empty_state();
  }
Referenced by v8::internal::compiler::LoadElimination::AbstractState::KillAll(), and ReduceStart().
factory()
Factory * v8::internal::compiler::LoadElimination::factory () const [private]
Definition at line 1576 of file load-elimination.cc.
{ return jsgraph()->factory(); }
References v8::internal::compiler::JSGraph::factory(), and jsgraph().
FieldIndexOf() [1/2]
LoadElimination::IndexRange v8::internal::compiler::LoadElimination::FieldIndexOf (FieldAccess const & access) [static], [private]
Definition at line 1521 of file load-elimination.cc.
                               {
  MachineRepresentation rep = access.machine_type.representation();
  switch (rep) {
    case MachineRepresentation::kNone:
    case MachineRepresentation::kBit:
    case MachineRepresentation::kSimd128:
    case MachineRepresentation::kSimd256:
    case MachineRepresentation::kFloat16RawBits:
      UNREACHABLE();
    case MachineRepresentation::kWord8:
    case MachineRepresentation::kWord16:
    case MachineRepresentation::kFloat16:
    case MachineRepresentation::kFloat32:
      // Currently untracked.
      return IndexRange::Invalid();
    case MachineRepresentation::kFloat64:
    case MachineRepresentation::kWord32:
    case MachineRepresentation::kWord64:
    case MachineRepresentation::kTaggedSigned:
    case MachineRepresentation::kTaggedPointer:
    case MachineRepresentation::kTagged:
    case MachineRepresentation::kMapWord:
    case MachineRepresentation::kCompressedPointer:
    case MachineRepresentation::kCompressed:
    case MachineRepresentation::kProtectedPointer:
    case MachineRepresentation::kIndirectPointer:
    case MachineRepresentation::kSandboxedPointer:
      break;
  }
  int representation_size = ElementSizeInBytes(rep);
  // We currently only track fields that are at least tagged pointer sized.
  // We assume that indirect pointers are tagged pointer sized if we see them
  // here since they should only ever be used in pointer compression
  // configurations.
  DCHECK(rep != MachineRepresentation::kIndirectPointer ||
         representation_size == kTaggedSize);
  if (representation_size < kTaggedSize) return IndexRange::Invalid();
  DCHECK_EQ(0, representation_size % kTaggedSize);
  if (access.base_is_tagged != kTaggedBase) {
    // We currently only track tagged objects.
    return IndexRange::Invalid();
  }
  return FieldIndexOf(access.offset, representation_size);
}
References v8::internal::compiler::FieldAccess::base_is_tagged, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::ElementSizeInBytes(), FieldIndexOf(), v8::internal::compiler::LoadElimination::IndexRange::Invalid(), v8::internal::kBit, v8::internal::kCompressed, v8::internal::kCompressedPointer, v8::internal::kFloat16, v8::internal::kFloat16RawBits, v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::kIndirectPointer, v8::internal::kMapWord, v8::internal::kNone, v8::internal::kProtectedPointer, v8::internal::kSandboxedPointer, v8::internal::kSimd128, v8::internal::kSimd256, v8::internal::kTagged, v8::internal::compiler::kTaggedBase, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::kTaggedSize, v8::internal::kWord16, v8::internal::kWord32, v8::internal::kWord64, v8::internal::kWord8, v8::internal::compiler::FieldAccess::machine_type, v8::internal::compiler::FieldAccess::offset, v8::internal::MachineType::representation(), and v8::internal::UNREACHABLE().
FieldIndexOf() [2/2]
LoadElimination::IndexRange v8::internal::compiler::LoadElimination::FieldIndexOf (int offset, int representation_size) [static], [private]
Definition at line 1512 of file load-elimination.cc.
                                         {
  DCHECK(IsAligned(offset, kTaggedSize));
  int field_index = offset / kTaggedSize - 1;
  DCHECK_EQ(0, representation_size % kTaggedSize);
  return IndexRange(field_index, representation_size / kTaggedSize);
}
References v8::internal::DCHECK(), DCHECK_EQ, IsAligned(), and v8::internal::kTaggedSize.
Referenced by ComputeLoopState(), ComputeLoopStateForStoreField(), FieldIndexOf(), ReduceEnsureWritableFastElements(), ReduceLoadField(), ReduceMaybeGrowFastElements(), ReduceStoreField(), ReduceTransitionAndStoreElement(), ReduceTransitionElementsKind(), and ReduceTransitionElementsKindOrCheckMap().
graph()
TFGraph * v8::internal::compiler::LoadElimination::graph () const [private]
Definition at line 1572 of file load-elimination.cc.
{ return jsgraph()->graph(); }
References v8::internal::compiler::MachineGraph::graph(), and jsgraph().
Referenced by ReduceLoadField(), and ReduceStoreField().
isolate()
Isolate * v8::internal::compiler::LoadElimination::isolate () const [private]
Definition at line 1574 of file load-elimination.cc.
{ return jsgraph()->isolate(); }
References v8::internal::compiler::JSGraph::isolate(), and jsgraph().
jsgraph()
JSGraph* v8::internal::compiler::LoadElimination::jsgraph () const [inline], [private]
Definition at line 365 of file load-elimination.h.
{ return jsgraph_; }
Referenced by common(), factory(), graph(), isolate(), ReduceCompareMaps(), and ReduceLoadField().
operator=()
LoadElimination& v8::internal::compiler::LoadElimination::operator= (const LoadElimination &) [delete]
Reduce()
Reduction v8::internal::compiler::LoadElimination::Reduce (Node * node) [final]
Definition at line 77 of file load-elimination.cc.
                                            {
  if (v8_flags.trace_turbo_load_elimination) {
    if (node->op()->EffectInputCount() > 0) {
      PrintF(" visit #%d:%s", node->id(), node->op()->mnemonic());
      if (node->op()->ValueInputCount() > 0) {
        PrintF("(");
        for (int i = 0; i < node->op()->ValueInputCount(); ++i) {
          if (i > 0) PrintF(", ");
          Node* const value = NodeProperties::GetValueInput(node, i);
          PrintF("#%d:%s", value->id(), value->op()->mnemonic());
        }
        PrintF(")");
      }
      PrintF("\n");
      for (int i = 0; i < node->op()->EffectInputCount(); ++i) {
        Node* const effect = NodeProperties::GetEffectInput(node, i);
        if (AbstractState const* const state = node_states_.Get(effect)) {
          PrintF(" state[%i]: #%d:%s\n", i, effect->id(),
                 effect->op()->mnemonic());
          state->Print();
        } else {
          PrintF(" no state[%i]: #%d:%s\n", i, effect->id(),
                 effect->op()->mnemonic());
        }
      }
    }
  }
  switch (node->opcode()) {
    case IrOpcode::kMapGuard:
      return ReduceMapGuard(node);
    case IrOpcode::kCheckMaps:
      return ReduceCheckMaps(node);
    case IrOpcode::kCompareMaps:
      return ReduceCompareMaps(node);
    case IrOpcode::kEnsureWritableFastElements:
      return ReduceEnsureWritableFastElements(node);
    case IrOpcode::kMaybeGrowFastElements:
      return ReduceMaybeGrowFastElements(node);
    case IrOpcode::kTransitionElementsKind:
      return ReduceTransitionElementsKind(node);
    case IrOpcode::kTransitionElementsKindOrCheckMap:
      return ReduceTransitionElementsKindOrCheckMap(node);
    case IrOpcode::kLoadField:
      return ReduceLoadField(node, FieldAccessOf(node->op()));
    case IrOpcode::kStoreField:
      return ReduceStoreField(node, FieldAccessOf(node->op()));
    case IrOpcode::kLoadElement:
      return ReduceLoadElement(node);
    case IrOpcode::kStoreElement:
      return ReduceStoreElement(node);
    case IrOpcode::kTransitionAndStoreElement:
      return ReduceTransitionAndStoreElement(node);
    case IrOpcode::kStoreTypedElement:
      return ReduceStoreTypedElement(node);
    case IrOpcode::kEffectPhi:
      return ReduceEffectPhi(node);
    case IrOpcode::kDead:
      break;
    case IrOpcode::kStart:
      return ReduceStart(node);
    default:
      return ReduceOtherNode(node);
  }
  return NoChange();
}
References v8::internal::compiler::Operator::EffectInputCount(), v8::internal::compiler::FieldAccessOf(), v8::internal::compiler::LoadElimination::AbstractStateForEffectNodes::Get(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Node::id(), v8::kStart, v8::internal::compiler::Operator::mnemonic(), node_states_, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::PrintF(), ReduceCheckMaps(), ReduceCompareMaps(), ReduceEffectPhi(), ReduceEnsureWritableFastElements(), ReduceLoadElement(), ReduceLoadField(), ReduceMapGuard(), ReduceMaybeGrowFastElements(), ReduceOtherNode(), ReduceStart(), ReduceStoreElement(), ReduceStoreField(), ReduceStoreTypedElement(), ReduceTransitionAndStoreElement(), ReduceTransitionElementsKind(), ReduceTransitionElementsKindOrCheckMap(), v8::internal::v8_flags, v8::internal::value, and v8::internal::compiler::Operator::ValueInputCount().
ReduceCheckMaps()
Reduction v8::internal::compiler::LoadElimination::ReduceCheckMaps (Node * node) [private]
Definition at line 786 of file load-elimination.cc.
                                                     {
  ZoneRefSet<Map> const& maps = CheckMapsParametersOf(node->op()).maps();
  Node* const object = NodeProperties::GetValueInput(node, 0);
  Node* const effect = NodeProperties::GetEffectInput(node);
  AbstractState const* state = node_states_.Get(effect);
  if (state == nullptr) return NoChange();
  ZoneRefSet<Map> object_maps;
  if (state->LookupMaps(object, &object_maps)) {
    if (maps.contains(object_maps)) return Replace(effect);
    // TODO(turbofan): Compute the intersection.
  }
  state = state->SetMaps(object, maps, zone());
  return UpdateState(node, state);
}
References v8::internal::compiler::CheckMapsParametersOf(), v8::internal::ZoneCompactSet< T >::contains(), v8::internal::compiler::LoadElimination::AbstractStateForEffectNodes::Get(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::LoadElimination::AbstractState::LookupMaps(), v8::internal::compiler::CheckMapsParameters::maps(), node_states_, v8::internal::compiler::Node::op(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::LoadElimination::AbstractState::SetMaps(), UpdateState(), and zone().
Referenced by Reduce().
ReduceCompareMaps()
Reduction v8::internal::compiler::LoadElimination::ReduceCompareMaps (Node * node) [private]
Definition at line 801 of file load-elimination.cc.
                                                       {
  ZoneRefSet<Map> const& maps = CompareMapsParametersOf(node->op());
  Node* const object = NodeProperties::GetValueInput(node, 0);
  Node* const effect = NodeProperties::GetEffectInput(node);
  AbstractState const* state = node_states_.Get(effect);
  if (state == nullptr) return NoChange();
  ZoneRefSet<Map> object_maps;
  if (state->LookupMaps(object, &object_maps)) {
    if (maps.contains(object_maps)) {
      Node* value = jsgraph()->TrueConstant();
      ReplaceWithValue(node, value, effect);
      return Replace(value);
    }
    // TODO(turbofan): Compute the intersection.
  }
  return UpdateState(node, state);
}
References v8::internal::compiler::CompareMapsParametersOf(), v8::internal::ZoneCompactSet< T >::contains(), v8::internal::compiler::LoadElimination::AbstractStateForEffectNodes::Get(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), jsgraph(), v8::internal::compiler::LoadElimination::AbstractState::LookupMaps(), node_states_, v8::internal::compiler::Node::op(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), UpdateState(), and v8::internal::value.
Referenced by Reduce().
ReduceEffectPhi()
Reduction v8::internal::compiler::LoadElimination::ReduceEffectPhi (Node * node) [private]
Definition at line 1262 of file load-elimination.cc.
                                                     {
  Node* const effect0 = NodeProperties::GetEffectInput(node, 0);
  Node* const control = NodeProperties::GetControlInput(node);
  AbstractState const* state0 = node_states_.Get(effect0);
  if (state0 == nullptr) return NoChange();
  if (control->opcode() == IrOpcode::kLoop) {
    // Here we rely on having only reducible loops:
    // The loop entry edge always dominates the header, so we can just take
    // the state from the first input, and compute the loop state based on it.
    AbstractState const* state = ComputeLoopState(node, state0);
    return UpdateState(node, state);
  }
  DCHECK_EQ(IrOpcode::kMerge, control->opcode());
  // Shortcut for the case when we do not know anything about some input.
  int const input_count = node->op()->EffectInputCount();
  for (int i = 1; i < input_count; ++i) {
    Node* const effect = NodeProperties::GetEffectInput(node, i);
    if (node_states_.Get(effect) == nullptr) return NoChange();
  }
  // Make a copy of the first input's state and merge with the state
  // from other inputs.
  AbstractState* state = zone()->New<AbstractState>(*state0);
  for (int i = 1; i < input_count; ++i) {
    Node* const input = NodeProperties::GetEffectInput(node, i);
    state->Merge(node_states_.Get(input), zone());
  }
  // For each phi, try to compute the new state for the phi from
  // the inputs.
  AbstractState const* state_with_phis = state;
  for (Node* use : control->uses()) {
    if (use->opcode() == IrOpcode::kPhi) {
      state_with_phis = UpdateStateForPhi(state_with_phis, node, use);
    }
  }
  return UpdateState(node, state_with_phis);
}
References ComputeLoopState(), DCHECK_EQ, v8::internal::compiler::Operator::EffectInputCount(), v8::internal::compiler::LoadElimination::AbstractStateForEffectNodes::Get(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::LoadElimination::AbstractState::Merge(), v8::internal::Zone::New(), node_states_, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), UpdateState(), UpdateStateForPhi(), use(), v8::internal::compiler::Node::uses(), and zone().
Referenced by Reduce().
ReduceEnsureWritableFastElements()
Reduction v8::internal::compiler::LoadElimination::ReduceEnsureWritableFastElements (Node * node) [private]
Definition at line 819 of file load-elimination.cc.
                                                                      {
  Node* const object = NodeProperties::GetValueInput(node, 0);
  Node* const elements = NodeProperties::GetValueInput(node, 1);
  Node* const effect = NodeProperties::GetEffectInput(node);
  AbstractState const* state = node_states_.Get(effect);
  if (state == nullptr) return NoChange();
  // Check if the {elements} already have the fixed array map.
  ZoneRefSet<Map> elements_maps;
  ZoneRefSet<Map> fixed_array_maps(broker()->fixed_array_map());
  if (state->LookupMaps(elements, &elements_maps) &&
      fixed_array_maps.contains(elements_maps)) {
    ReplaceWithValue(node, elements, effect);
    return Replace(elements);
  }
  // We know that the resulting elements have the fixed array map.
  state = state->SetMaps(node, fixed_array_maps, zone());
  // Kill the previous elements on {object}.
  state = state->KillField(object,
                           FieldIndexOf(JSObject::kElementsOffset, kTaggedSize),
                           MaybeHandle<Name>(), zone());
  // Add the new elements on {object}.
  state = state->AddField(
      object, FieldIndexOf(JSObject::kElementsOffset, kTaggedSize),
      {node, MachineRepresentation::kTaggedPointer}, zone());
  return UpdateState(node, state);
}
References v8::internal::compiler::LoadElimination::AbstractState::AddField(), broker(), v8::internal::ZoneCompactSet< T >::contains(), FieldIndexOf(), v8::internal::compiler::LoadElimination::AbstractStateForEffectNodes::Get(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::LoadElimination::AbstractState::KillField(), v8::internal::kTaggedPointer, v8::internal::kTaggedSize, v8::internal::compiler::LoadElimination::AbstractState::LookupMaps(), node_states_, v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::LoadElimination::AbstractState::SetMaps(), UpdateState(), and zone().
Referenced by Reduce().
ReduceLoadElement()
Reduction v8::internal::compiler::LoadElimination::ReduceLoadElement (Node * node) [private]
Definition at line 1132 of file load-elimination.cc.
                                                       {
  Node* const object = NodeProperties::GetValueInput(node, 0);
  Node* const index = NodeProperties::GetValueInput(node, 1);
  Node* const effect = NodeProperties::GetEffectInput(node);
  AbstractState const* state = node_states_.Get(effect);
  if (state == nullptr) return NoChange();
  // Only handle loads that do not require truncations.
  ElementAccess const& access = ElementAccessOf(node->op());
  switch (access.machine_type.representation()) {
    case MachineRepresentation::kNone:
    case MachineRepresentation::kBit:
    case MachineRepresentation::kWord8:
    case MachineRepresentation::kWord16:
    case MachineRepresentation::kWord32:
    case MachineRepresentation::kWord64:
    case MachineRepresentation::kFloat16RawBits:
    case MachineRepresentation::kFloat16:
    case MachineRepresentation::kFloat32:
    case MachineRepresentation::kCompressedPointer:
    case MachineRepresentation::kCompressed:
    case MachineRepresentation::kProtectedPointer:
    case MachineRepresentation::kIndirectPointer:
    case MachineRepresentation::kSandboxedPointer:
      // TODO(turbofan): Add support for doing the truncations.
      break;
    case MachineRepresentation::kFloat64:
    case MachineRepresentation::kSimd128:
    case MachineRepresentation::kSimd256:
    case MachineRepresentation::kTaggedSigned:
    case MachineRepresentation::kTaggedPointer:
    case MachineRepresentation::kTagged:
    case MachineRepresentation::kMapWord:
      if (Node* replacement = state->LookupElement(
              object, index, access.machine_type.representation())) {
        // Make sure we don't resurrect dead {replacement} nodes.
        // Skip lowering if the type of the {replacement} node is not a subtype
        // of the original {node}'s type.
        // TODO(turbofan): We should insert a {TypeGuard} for the intersection
        // of these two types here once we properly handle {Type::None}
        // everywhere.
        if (!replacement->IsDead() && NodeProperties::GetType(replacement)
                                          .Is(NodeProperties::GetType(node))) {
          ReplaceWithValue(node, replacement, effect);
          return Replace(replacement);
        }
      }
      state = state->AddElement(object, index, node,
                                access.machine_type.representation(), zone());
      return UpdateState(node, state);
  }
  return NoChange();
}
References v8::internal::compiler::LoadElimination::AbstractState::AddElement(), v8::internal::compiler::ElementAccessOf(), v8::internal::compiler::LoadElimination::AbstractStateForEffectNodes::Get(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::index, v8::internal::compiler::Type::Is(), v8::internal::kBit, v8::internal::kCompressed, v8::internal::kCompressedPointer, v8::internal::kFloat16, v8::internal::kFloat16RawBits, v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::kIndirectPointer, v8::internal::kMapWord, v8::internal::kNone, v8::internal::kProtectedPointer, v8::internal::kSandboxedPointer, v8::internal::kSimd128, v8::internal::kSimd256, v8::internal::kTagged, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::kWord16, v8::internal::kWord32, v8::internal::kWord64, v8::internal::kWord8, v8::internal::compiler::LoadElimination::AbstractState::LookupElement(), v8::internal::compiler::ElementAccess::machine_type, node_states_, v8::internal::compiler::Node::op(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::MachineType::representation(), UpdateState(), and zone().
Referenced by Reduce().
ReduceLoadField()
Reduction v8::internal::compiler::LoadElimination::ReduceLoadField (Node * node, FieldAccess const & access) [private]
Definition at line 985 of file load-elimination.cc.
                                                                      {
  Node* object = NodeProperties::GetValueInput(node, 0);
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  AbstractState const* state = node_states_.Get(effect);
  if (state == nullptr) return NoChange();
  if (access.offset == HeapObject::kMapOffset &&
      access.base_is_tagged == kTaggedBase) {
    DCHECK(IsAnyTagged(access.machine_type.representation()));
    ZoneRefSet<Map> object_maps;
    if (state->LookupMaps(object, &object_maps) && object_maps.size() == 1) {
      Node* value = jsgraph()->HeapConstantNoHole(object_maps[0].object());
      NodeProperties::SetType(value, Type::OtherInternal());
      ReplaceWithValue(node, value, effect);
      return Replace(value);
    }
  } else {
    IndexRange field_index = FieldIndexOf(access);
    if (field_index != IndexRange::Invalid()) {
      MachineRepresentation representation =
          access.machine_type.representation();
      FieldInfo const* lookup_result =
          state->LookupField(object, field_index, access.const_field_info);
      if (!lookup_result && access.const_field_info.IsConst()) {
        // If the access is const and we didn't find anything, also try to look
        // up information from mutable stores
        lookup_result =
            state->LookupField(object, field_index, ConstFieldInfo::None());
      }
      if (lookup_result) {
        // Make sure we don't reuse values that were recorded with a different
        // representation or resurrect dead {replacement} nodes.
        Node* replacement = lookup_result->value;
        if (IsCompatible(representation, lookup_result->representation) &&
            !replacement->IsDead()) {
          // Introduce a TypeGuard if the type of the {replacement} node is not
          // a subtype of the original {node}'s type.
          if (!NodeProperties::GetType(replacement)
                   .Is(NodeProperties::GetType(node))) {
            Type replacement_type = Type::Intersect(
                NodeProperties::GetType(node),
                NodeProperties::GetType(replacement), graph()->zone());
            replacement = effect =
                graph()->NewNode(common()->TypeGuard(replacement_type),
                                 replacement, effect, control);
            NodeProperties::SetType(replacement, replacement_type);
          }
          ReplaceWithValue(node, replacement, effect);
          return Replace(replacement);
        }
      }
      FieldInfo info(node, representation, access.name,
                     access.const_field_info);
      state = state->AddField(object, field_index, info, zone());
    }
  }
  if (access.map.has_value()) {
    state = state->SetMaps(node, ZoneRefSet<Map>(*access.map), zone());
  }
  return UpdateState(node, state);
}
References v8::internal::compiler::LoadElimination::AbstractState::AddField(), v8::internal::compiler::FieldAccess::base_is_tagged, common(), v8::internal::compiler::FieldAccess::const_field_info, v8::internal::DCHECK(), FieldIndexOf(), v8::internal::compiler::LoadElimination::AbstractStateForEffectNodes::Get(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::JSGraph::HeapConstantNoHole(), v8::internal::compiler::Type::Intersect(), v8::internal::compiler::LoadElimination::IndexRange::Invalid(), v8::internal::Is(), v8::internal::IsAnyTagged(), v8::internal::compiler::anonymous_namespace{load-elimination.cc}::IsCompatible(), v8::internal::compiler::ConstFieldInfo::IsConst(), v8::internal::compiler::Node::IsDead(), jsgraph(), v8::internal::HeapObject::kMapOffset, v8::internal::compiler::kTaggedBase, v8::internal::compiler::LoadElimination::AbstractState::LookupField(), v8::internal::compiler::LoadElimination::AbstractState::LookupMaps(), v8::internal::compiler::FieldAccess::machine_type, v8::internal::compiler::FieldAccess::map, v8::internal::compiler::FieldAccess::name, v8::internal::compiler::TFGraph::NewNode(), node_states_, v8::internal::compiler::ConstFieldInfo::None(), v8::internal::compiler::FieldAccess::offset, v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::MachineType::representation(), v8::internal::compiler::LoadElimination::FieldInfo::representation, v8::internal::compiler::LoadElimination::AbstractState::SetMaps(), v8::internal::compiler::NodeProperties::SetType(), v8::internal::ZoneCompactSet< T >::size(), UpdateState(), v8::internal::compiler::LoadElimination::FieldInfo::value, v8::internal::value, and zone().
Referenced by Reduce().
ReduceMapGuard()
Reduction v8::internal::compiler::LoadElimination::ReduceMapGuard (Node * node) [private]
Definition at line 771 of file load-elimination.cc.
                                                    {
  ZoneRefSet<Map> const& maps = MapGuardMapsOf(node->op());
  Node* const object = NodeProperties::GetValueInput(node, 0);
  Node* const effect = NodeProperties::GetEffectInput(node);
  AbstractState const* state = node_states_.Get(effect);
  if (state == nullptr) return NoChange();
  ZoneRefSet<Map> object_maps;
  if (state->LookupMaps(object, &object_maps)) {
    if (maps.contains(object_maps)) return Replace(effect);
    // TODO(turbofan): Compute the intersection.
  }
  state = state->SetMaps(object, maps, zone());
  return UpdateState(node, state);
}
References v8::internal::ZoneCompactSet< T >::contains(), v8::internal::compiler::LoadElimination::AbstractStateForEffectNodes::Get(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::LoadElimination::AbstractState::LookupMaps(), v8::internal::compiler::MapGuardMapsOf(), node_states_, v8::internal::compiler::Node::op(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::LoadElimination::AbstractState::SetMaps(), UpdateState(), and zone().
Referenced by Reduce().
ReduceMaybeGrowFastElements()
Reduction v8::internal::compiler::LoadElimination::ReduceMaybeGrowFastElements (Node * node) [private]
Definition at line 846 of file load-elimination.cc.
                                                                 {
  GrowFastElementsParameters params = GrowFastElementsParametersOf(node->op());
  Node* const object = NodeProperties::GetValueInput(node, 0);
  Node* const effect = NodeProperties::GetEffectInput(node);
  AbstractState const* state = node_states_.Get(effect);
  if (state == nullptr) return NoChange();
  if (params.mode() == GrowFastElementsMode::kDoubleElements) {
    // We know that the resulting elements have the fixed double array map.
    state = state->SetMaps(
        node, ZoneRefSet<Map>(broker()->fixed_double_array_map()), zone());
  } else {
    // We know that the resulting elements have the fixed array map or the COW
    // version thereof (if we didn't grow and it was already COW before).
    ZoneRefSet<Map> fixed_array_maps(
        {broker()->fixed_array_map(), broker()->fixed_cow_array_map()}, zone());
    state = state->SetMaps(node, fixed_array_maps, zone());
  }
  // Kill the previous elements on {object}.
  state = state->KillField(object,
                           FieldIndexOf(JSObject::kElementsOffset, kTaggedSize),
                           MaybeHandle<Name>(), zone());
  // Add the new elements on {object}.
  state = state->AddField(
      object, FieldIndexOf(JSObject::kElementsOffset, kTaggedSize),
      {node, MachineRepresentation::kTaggedPointer}, zone());
  return UpdateState(node, state);
}
References v8::internal::compiler::LoadElimination::AbstractState::AddField(), broker(), FieldIndexOf(), v8::internal::compiler::LoadElimination::AbstractStateForEffectNodes::Get(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::GrowFastElementsParametersOf(), v8::internal::compiler::kDoubleElements, v8::internal::compiler::LoadElimination::AbstractState::KillField(), v8::internal::kTaggedPointer, v8::internal::kTaggedSize, v8::internal::compiler::GrowFastElementsParameters::mode(), node_states_, v8::internal::compiler::Node::op(), v8::internal::compiler::LoadElimination::AbstractState::SetMaps(), UpdateState(), and zone().
Referenced by Reduce().
ReduceOtherNode()
Reduction v8::internal::compiler::LoadElimination::ReduceOtherNode (Node * node) [private]
Definition at line 1307 of file load-elimination.cc.
                                                     {
  if (node->op()->EffectInputCount() == 1) {
    if (node->op()->EffectOutputCount() == 1) {
      Node* const effect = NodeProperties::GetEffectInput(node);
      AbstractState const* state = node_states_.Get(effect);
      // If we do not know anything about the predecessor, do not propagate
      // just yet because we will have to recompute anyway once we compute
      // the predecessor.
      if (state == nullptr) return NoChange();
      // Check if this {node} has some uncontrolled side effects.
      if (!node->op()->HasProperty(Operator::kNoWrite)) {
        state = state->KillAll(zone());
      }
      return UpdateState(node, state);
    } else {
      // Effect terminators should be handled specially.
      return NoChange();
    }
  }
  DCHECK_EQ(0, node->op()->EffectInputCount());
  DCHECK_EQ(0, node->op()->EffectOutputCount());
  return NoChange();
}
References DCHECK_EQ, v8::internal::compiler::Operator::EffectInputCount(), v8::internal::compiler::Operator::EffectOutputCount(), v8::internal::compiler::LoadElimination::AbstractStateForEffectNodes::Get(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::Operator::HasProperty(), v8::internal::compiler::LoadElimination::AbstractState::KillAll(), v8::internal::compiler::Operator::kNoWrite, node_states_, v8::internal::compiler::Node::op(), UpdateState(), and zone().
Referenced by Reduce().
reducer_name()
const char* v8::internal::compiler::LoadElimination::reducer_name () const [inline], [override]
Definition at line 42 of file load-elimination.h.
{ return "LoadElimination"; }
ReduceStart()
Reduction v8::internal::compiler::LoadElimination::ReduceStart (Node * node) [private]
Definition at line 1303 of file load-elimination.cc.
                                                 {
  return UpdateState(node, empty_state());
}
References empty_state(), and UpdateState().
Referenced by Reduce().
ReduceStoreElement()
Reduction v8::internal::compiler::LoadElimination::ReduceStoreElement (Node * node) [private]
Definition at line 1186 of file load-elimination.cc.
                                                        {
  ElementAccess const& access = ElementAccessOf(node->op());
  Node* const object = NodeProperties::GetValueInput(node, 0);
  Node* const index = NodeProperties::GetValueInput(node, 1);
  Node* const new_value = NodeProperties::GetValueInput(node, 2);
  Node* const effect = NodeProperties::GetEffectInput(node);
  AbstractState const* state = node_states_.Get(effect);
  if (state == nullptr) return NoChange();
  Node* const old_value =
      state->LookupElement(object, index, access.machine_type.representation());
  if (old_value == new_value) {
    // This store is fully redundant.
    return Replace(effect);
  }
  // Kill all potentially aliasing elements.
  state = state->KillElement(object, index, zone());
  // Only record the new value if the store doesn't have an implicit truncation.
  switch (access.machine_type.representation()) {
    case MachineRepresentation::kNone:
    case MachineRepresentation::kBit:
    case MachineRepresentation::kWord8:
    case MachineRepresentation::kWord16:
    case MachineRepresentation::kWord32:
    case MachineRepresentation::kWord64:
    case MachineRepresentation::kFloat16RawBits:
    case MachineRepresentation::kFloat16:
    case MachineRepresentation::kFloat32:
    case MachineRepresentation::kCompressedPointer:
    case MachineRepresentation::kCompressed:
    case MachineRepresentation::kSandboxedPointer:
    case MachineRepresentation::kProtectedPointer:
    case MachineRepresentation::kIndirectPointer:
      // TODO(turbofan): Add support for doing the truncations.
      break;
    case MachineRepresentation::kFloat64:
    case MachineRepresentation::kSimd128:
    case MachineRepresentation::kSimd256:
    case MachineRepresentation::kTaggedSigned:
    case MachineRepresentation::kTaggedPointer:
    case MachineRepresentation::kTagged:
    case MachineRepresentation::kMapWord:
      state = state->AddElement(object, index, new_value,
                                access.machine_type.representation(), zone());
      break;
  }
  return UpdateState(node, state);
}
References v8::internal::compiler::LoadElimination::AbstractState::AddElement(), v8::internal::compiler::ElementAccessOf(), v8::internal::compiler::LoadElimination::AbstractStateForEffectNodes::Get(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::index, v8::internal::kBit, v8::internal::kCompressed, v8::internal::kCompressedPointer, v8::internal::kFloat16, v8::internal::kFloat16RawBits, v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::compiler::LoadElimination::AbstractState::KillElement(), v8::internal::kIndirectPointer, v8::internal::kMapWord, v8::internal::kNone, v8::internal::kProtectedPointer, v8::internal::kSandboxedPointer, v8::internal::kSimd128, v8::internal::kSimd256, v8::internal::kTagged, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::kWord16, v8::internal::kWord32, v8::internal::kWord64, v8::internal::kWord8, v8::internal::compiler::LoadElimination::AbstractState::LookupElement(), v8::internal::compiler::ElementAccess::machine_type, node_states_, v8::internal::compiler::Node::op(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::MachineType::representation(), UpdateState(), and zone().
Referenced by Reduce().
ReduceStoreField()
Reduction v8::internal::compiler::LoadElimination::ReduceStoreField (Node * node, FieldAccess const & access) [private]
Definition at line 1048 of file load-elimination.cc.
                                                                       {
  Node* const object = NodeProperties::GetValueInput(node, 0);
  Node* const new_value = NodeProperties::GetValueInput(node, 1);
  Node* const effect = NodeProperties::GetEffectInput(node);
  AbstractState const* state = node_states_.Get(effect);
  if (state == nullptr) return NoChange();
  if (access.offset == HeapObject::kMapOffset &&
      access.base_is_tagged == kTaggedBase) {
    DCHECK(IsAnyTagged(access.machine_type.representation()));
    // Kill all potential knowledge about the {object}s map.
    state = state->KillMaps(object, zone());
    Type const new_value_type = NodeProperties::GetType(new_value);
    if (new_value_type.IsHeapConstant()) {
      // Record the new {object} map information.
      ZoneRefSet<Map> object_maps(
          new_value_type.AsHeapConstant()->Ref().AsMap());
      state = state->SetMaps(object, object_maps, zone());
    }
  } else {
    IndexRange field_index = FieldIndexOf(access);
    if (field_index != IndexRange::Invalid()) {
      bool is_const_store = access.const_field_info.IsConst();
      MachineRepresentation representation =
          access.machine_type.representation();
      FieldInfo const* lookup_result =
          state->LookupField(object, field_index, access.const_field_info);
      if (lookup_result &&
          (!is_const_store || V8_ENABLE_DOUBLE_CONST_STORE_CHECK_BOOL)) {
        // At runtime, we should never encounter
        // - any store replacing existing info with a different, incompatible
        // representation, nor
        // - two consecutive const stores, unless the latter is a store into
        // a literal.
        // However, we may see such code statically, so we guard against
        // executing it by emitting Unreachable.
        // TODO(gsps): Re-enable the double const store check even for
        // non-debug builds once we have identified other FieldAccesses
        // that should be marked mutable instead of const
        // (cf. JSCreateLowering::AllocateFastLiteral).
        bool incompatible_representation =
            !lookup_result->name.is_null() &&
            !IsCompatible(representation, lookup_result->representation);
        bool illegal_double_const_store =
            is_const_store && !access.is_store_in_literal;
        if (incompatible_representation || illegal_double_const_store) {
          Node* control = NodeProperties::GetControlInput(node);
          Node* unreachable =
              graph()->NewNode(common()->Unreachable(), effect, control);
          return Replace(unreachable);
        }
        if (lookup_result->value == new_value) {
          // This store is fully redundant.
          return Replace(effect);
        }
      }
      // Kill all potentially aliasing fields and record the new value.
      FieldInfo new_info(new_value, representation, access.name,
                         access.const_field_info);
      if (is_const_store && access.is_store_in_literal) {
        // We only kill const information when there is a chance that we
        // previously stored information about the given const field (namely,
        // when we observe const stores to literals).
        state = state->KillConstField(object, field_index, zone());
      }
      state = state->KillField(object, field_index, access.name, zone());
      state = state->AddField(object, field_index, new_info, zone());
      if (is_const_store) {
        // For const stores, we track information in both the const and the
        // mutable world to guard against field accesses that should have
        // been marked const, but were not.
        new_info.const_field_info = ConstFieldInfo::None();
        state = state->AddField(object, field_index, new_info, zone());
      }
    } else {
      // Unsupported StoreField operator.
      state = state->KillFields(object, access.name, zone());
    }
  }
  return UpdateState(node, state);
}
References v8::internal::compiler::LoadElimination::AbstractState::AddField(), v8::internal::compiler::Type::AsHeapConstant(), v8::internal::compiler::FieldAccess::base_is_tagged, common(), v8::internal::compiler::LoadElimination::FieldInfo::const_field_info, v8::internal::compiler::FieldAccess::const_field_info, v8::internal::DCHECK(), FieldIndexOf(), v8::internal::compiler::LoadElimination::AbstractStateForEffectNodes::Get(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::LoadElimination::IndexRange::Invalid(), v8::internal::compiler::FieldAccess::is_store_in_literal, v8::internal::IsAnyTagged(), v8::internal::compiler::anonymous_namespace{load-elimination.cc}::IsCompatible(), v8::internal::compiler::ConstFieldInfo::IsConst(), v8::internal::compiler::Type::IsHeapConstant(), v8::internal::compiler::LoadElimination::AbstractState::KillConstField(), v8::internal::compiler::LoadElimination::AbstractState::KillField(), v8::internal::compiler::LoadElimination::AbstractState::KillFields(), v8::internal::compiler::LoadElimination::AbstractState::KillMaps(), v8::internal::HeapObject::kMapOffset, v8::internal::compiler::kTaggedBase, v8::internal::compiler::LoadElimination::AbstractState::LookupField(), v8::internal::compiler::FieldAccess::machine_type, v8::internal::compiler::LoadElimination::FieldInfo::name, v8::internal::compiler::FieldAccess::name, v8::internal::compiler::TFGraph::NewNode(), node_states_, v8::internal::compiler::ConstFieldInfo::None(), v8::internal::compiler::FieldAccess::offset, v8::internal::compiler::HeapConstantType::Ref(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::MachineType::representation(), v8::internal::compiler::LoadElimination::FieldInfo::representation, v8::internal::compiler::LoadElimination::AbstractState::SetMaps(), UpdateState(), V8_ENABLE_DOUBLE_CONST_STORE_CHECK_BOOL, v8::internal::compiler::LoadElimination::FieldInfo::value, and zone().
Referenced by Reduce().
ReduceStoreTypedElement()
Reduction v8::internal::compiler::LoadElimination::ReduceStoreTypedElement (Node * node) [private]
Definition at line 1234 of file load-elimination.cc.
                                                             {
  Node* const effect = NodeProperties::GetEffectInput(node);
  AbstractState const* state = node_states_.Get(effect);
  if (state == nullptr) return NoChange();
  return UpdateState(node, state);
}
References v8::internal::compiler::LoadElimination::AbstractStateForEffectNodes::Get(), v8::internal::compiler::NodeProperties::GetEffectInput(), node_states_, and UpdateState().
Referenced by Reduce().
ReduceTransitionAndStoreElement()
Reduction v8::internal::compiler::LoadElimination::ReduceTransitionAndStoreElement (Node * node) [private]
Definition at line 960 of file load-elimination.cc.
                                                                     {
  Node* const object = NodeProperties::GetValueInput(node, 0);
  MapRef double_map(DoubleMapParameterOf(node->op()));
  MapRef fast_map(FastMapParameterOf(node->op()));
  Node* const effect = NodeProperties::GetEffectInput(node);
  AbstractState const* state = node_states_.Get(effect);
  if (state == nullptr) return NoChange();
  // We need to add the double and fast maps to the set of possible maps for
  // this object, because we don't know which of those we'll transition to.
  // Additionally, we should kill all alias information.
  ZoneRefSet<Map> object_maps;
  if (state->LookupMaps(object, &object_maps)) {
    object_maps.insert(double_map, zone());
    object_maps.insert(fast_map, zone());
    state = state->KillMaps(object, zone());
    state = state->SetMaps(object, object_maps, zone());
  }
  // Kill the elements as well.
  state = state->KillField(object,
                           FieldIndexOf(JSObject::kElementsOffset, kTaggedSize),
                           MaybeHandle<Name>(), zone());
  return UpdateState(node, state);
}
References v8::internal::compiler::DoubleMapParameterOf(), v8::internal::compiler::FastMapParameterOf(), FieldIndexOf(), v8::internal::compiler::LoadElimination::AbstractStateForEffectNodes::Get(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::ZoneCompactSet< T >::insert(), v8::internal::compiler::LoadElimination::AbstractState::KillField(), v8::internal::compiler::LoadElimination::AbstractState::KillMaps(), v8::internal::kTaggedSize, v8::internal::compiler::LoadElimination::AbstractState::LookupMaps(), node_states_, v8::internal::compiler::Node::op(), v8::internal::compiler::LoadElimination::AbstractState::SetMaps(), UpdateState(), and zone().
Referenced by Reduce().
ReduceTransitionElementsKind()
Reduction v8::internal::compiler::LoadElimination::ReduceTransitionElementsKind (Node * node) [private]
Definition at line 874 of file load-elimination.cc.
                                                                  {
  ElementsTransition transition = ElementsTransitionOf(node->op());
  Node* const object = NodeProperties::GetValueInput(node, 0);
  MapRef source_map(transition.source());
  MapRef target_map(transition.target());
  Node* const effect = NodeProperties::GetEffectInput(node);
  AbstractState const* state = node_states_.Get(effect);
  if (state == nullptr) return NoChange();
  switch (transition.mode()) {
    case ElementsTransition::kFastTransition:
      break;
    case ElementsTransition::kSlowTransition:
      // Kill the elements as well.
      AliasStateInfo alias_info(state, object, source_map);
      state = state->KillField(
          alias_info, FieldIndexOf(JSObject::kElementsOffset, kTaggedSize),
          MaybeHandle<Name>(), zone());
      break;
  }
  ZoneRefSet<Map> object_maps;
  if (state->LookupMaps(object, &object_maps)) {
    if (ZoneRefSet<Map>(target_map).contains(object_maps)) {
      // The {object} already has the {target_map}, so this TransitionElements
      // {node} is fully redundant (independent of what {source_map} is).
      return Replace(effect);
    }
    if (object_maps.contains(ZoneRefSet<Map>(source_map))) {
      object_maps.remove(source_map, zone());
      object_maps.insert(target_map, zone());
      AliasStateInfo alias_info(state, object, source_map);
      state = state->KillMaps(alias_info, zone());
      state = state->SetMaps(object, object_maps, zone());
    }
  } else {
    AliasStateInfo alias_info(state, object, source_map);
    state = state->KillMaps(alias_info, zone());
  }
  return UpdateState(node, state);
}
References v8::base::contains(), v8::internal::ZoneCompactSet< T >::contains(), v8::internal::compiler::ElementsTransitionOf(), FieldIndexOf(), v8::internal::compiler::LoadElimination::AbstractStateForEffectNodes::Get(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::ZoneCompactSet< T >::insert(), v8::internal::compiler::ElementsTransition::kFastTransition, v8::internal::compiler::LoadElimination::AbstractState::KillField(), v8::internal::compiler::LoadElimination::AbstractState::KillMaps(), v8::internal::compiler::ElementsTransition::kSlowTransition, v8::internal::kTaggedSize, v8::internal::compiler::LoadElimination::AbstractState::LookupMaps(), v8::internal::compiler::ElementsTransition::mode(), node_states_, v8::internal::compiler::Node::op(), v8::internal::ZoneCompactSet< T >::remove(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::LoadElimination::AbstractState::SetMaps(), v8::internal::compiler::ElementsTransition::source(), v8::internal::compiler::ElementsTransition::target(), UpdateState(), and zone().
Referenced by Reduce().
ReduceTransitionElementsKindOrCheckMap()
Reduction v8::internal::compiler::LoadElimination::ReduceTransitionElementsKindOrCheckMap (Node * node) [private]
Definition at line 914 of file load-elimination.cc.
                                                                            {
  ElementsTransitionWithMultipleSources transition =
      ElementsTransitionWithMultipleSourcesOf(node->op());
  Node* const object = NodeProperties::GetValueInput(node, 0);
  const ZoneRefSet<Map>& source_maps = transition.sources();
  MapRef target_map(transition.target());
  Node* const effect = NodeProperties::GetEffectInput(node);
  AbstractState const* state = node_states_.Get(effect);
  if (state == nullptr) return NoChange();
  for (MapRef source_map : source_maps) {
    if (!IsSimpleMapChangeTransition(source_map.elements_kind(),
                                     target_map.elements_kind())) {
      // Kill the elements as well.
      AliasStateInfo alias_info(state, object, source_map);
      state = state->KillField(
          alias_info, FieldIndexOf(JSObject::kElementsOffset, kTaggedSize),
          MaybeHandle<Name>(), zone());
    }
  }
  ZoneRefSet<Map> object_maps;
  if (state->LookupMaps(object, &object_maps)) {
    if (ZoneRefSet<Map>(target_map).contains(object_maps)) {
      // The {object} already has the {target_map}, so this TransitionElements
      // {node} is fully redundant (independent of what {source_map} is).
      return Replace(effect);
    }
    for (MapRef source_map : source_maps) {
      if (object_maps.contains(ZoneRefSet<Map>(source_map))) {
        object_maps.remove(source_map, zone());
        object_maps.insert(target_map, zone());
        AliasStateInfo alias_info(state, object, source_map);
        state = state->KillMaps(alias_info, zone());
        state = state->SetMaps(object, object_maps, zone());
      }
    }
  } else {
    for (MapRef source_map : source_maps) {
      AliasStateInfo alias_info(state, object, source_map);
      state = state->KillMaps(alias_info, zone());
    }
  }
  state = state->SetMaps(object, ZoneRefSet<Map>(target_map), zone());
  return UpdateState(node, state);
}
References v8::base::contains(), v8::internal::ZoneCompactSet< T >::contains(), v8::internal::compiler::MapRef::elements_kind(), v8::internal::compiler::ElementsTransitionWithMultipleSourcesOf(), FieldIndexOf(), v8::internal::compiler::LoadElimination::AbstractStateForEffectNodes::Get(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::ZoneCompactSet< T >::insert(), v8::internal::IsSimpleMapChangeTransition(), v8::internal::compiler::LoadElimination::AbstractState::KillField(), v8::internal::compiler::LoadElimination::AbstractState::KillMaps(), v8::internal::kTaggedSize, v8::internal::compiler::LoadElimination::AbstractState::LookupMaps(), node_states_, v8::internal::compiler::Node::op(), v8::internal::ZoneCompactSet< T >::remove(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::LoadElimination::AbstractState::SetMaps(), v8::internal::compiler::ElementsTransitionWithMultipleSources::sources(), v8::internal::compiler::ElementsTransitionWithMultipleSources::target(), UpdateState(), and zone().
Referenced by Reduce().
UpdateState()
Reduction v8::internal::compiler::LoadElimination::UpdateState (Node * node, AbstractState const * state) [private]
Definition at line 1331 of file load-elimination.cc.
                                                                             {
  AbstractState const* original = node_states_.Get(node);
  // Only signal that the {node} has Changed, if the information about {state}
  // has changed wrt. the {original}.
  if (state != original) {
    if (original == nullptr || !state->Equals(original)) {
      node_states_.Set(node, state);
      return Changed(node);
    }
  }
  return NoChange();
}
References v8::internal::compiler::LoadElimination::AbstractState::Equals(), v8::internal::compiler::LoadElimination::AbstractStateForEffectNodes::Get(), node_states_, and v8::internal::compiler::LoadElimination::AbstractStateForEffectNodes::Set().
Referenced by ReduceCheckMaps(), ReduceCompareMaps(), ReduceEffectPhi(), ReduceEnsureWritableFastElements(), ReduceLoadElement(), ReduceLoadField(), ReduceMapGuard(), ReduceMaybeGrowFastElements(), ReduceOtherNode(), ReduceStart(), ReduceStoreElement(), ReduceStoreField(), ReduceStoreTypedElement(), ReduceTransitionAndStoreElement(), ReduceTransitionElementsKind(), and ReduceTransitionElementsKindOrCheckMap().
UpdateStateForPhi()
LoadElimination::AbstractState const * v8::internal::compiler::LoadElimination::UpdateStateForPhi (AbstractState const * state, Node * effect_phi, Node * phi) [private]
Definition at line 1241 of file load-elimination.cc.
                                                             {
  int predecessor_count = phi->InputCount() - 1;
  // TODO(jarin) Consider doing a union here. At the moment, we just keep this
  // consistent with AbstractState::Merge.
  // Check if all the inputs have the same maps.
  AbstractState const* input_state =
      node_states_.Get(NodeProperties::GetEffectInput(effect_phi, 0));
  ZoneRefSet<Map> object_maps;
  if (!input_state->LookupMaps(phi->InputAt(0), &object_maps)) return state;
  for (int i = 1; i < predecessor_count; i++) {
    input_state =
        node_states_.Get(NodeProperties::GetEffectInput(effect_phi, i));
    ZoneRefSet<Map> input_maps;
    if (!input_state->LookupMaps(phi->InputAt(i), &input_maps)) return state;
    if (input_maps != object_maps) return state;
  }
  return state->SetMaps(phi, object_maps, zone());
}
References v8::internal::compiler::LoadElimination::AbstractStateForEffectNodes::Get(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::InputCount(), v8::internal::compiler::LoadElimination::AbstractState::LookupMaps(), node_states_, v8::internal::compiler::LoadElimination::AbstractState::SetMaps(), and zone().
Referenced by ReduceEffectPhi().
zone()
Zone* v8::internal::compiler::LoadElimination::zone () const [inline], [private]
Definition at line 367 of file load-elimination.h.
{ return node_states_.zone(); }
Referenced by v8::internal::compiler::LoadElimination::AbstractState::AddElement(), v8::internal::compiler::LoadElimination::AbstractState::AddField(), ComputeLoopState(), ComputeLoopStateForStoreField(), v8::internal::compiler::LoadElimination::AbstractMaps::Extend(), v8::internal::compiler::LoadElimination::AbstractState::FieldsMerge(), v8::internal::compiler::LoadElimination::AbstractField::Kill(), v8::internal::compiler::LoadElimination::AbstractMaps::Kill(), v8::internal::compiler::LoadElimination::AbstractElements::Kill(), v8::internal::compiler::LoadElimination::AbstractState::KillAll(), v8::internal::compiler::LoadElimination::AbstractField::KillConst(), v8::internal::compiler::LoadElimination::AbstractState::KillConstField(), v8::internal::compiler::LoadElimination::AbstractState::KillElement(), v8::internal::compiler::LoadElimination::AbstractState::KillField(), v8::internal::compiler::LoadElimination::AbstractState::KillFields(), v8::internal::compiler::LoadElimination::AbstractState::KillMaps(), v8::internal::compiler::LoadElimination::AbstractElements::Merge(), v8::internal::compiler::LoadElimination::AbstractMaps::Merge(), v8::internal::compiler::LoadElimination::AbstractState::Merge(), ReduceCheckMaps(), ReduceEffectPhi(), ReduceEnsureWritableFastElements(), ReduceLoadElement(), ReduceLoadField(), ReduceMapGuard(), ReduceMaybeGrowFastElements(), ReduceOtherNode(), ReduceStoreElement(), ReduceStoreField(), ReduceTransitionAndStoreElement(), ReduceTransitionElementsKind(), ReduceTransitionElementsKindOrCheckMap(), v8::internal::compiler::LoadElimination::AbstractState::SetMaps(), and UpdateStateForPhi().
Member Data Documentation
broker_
JSHeapBroker* v8::internal::compiler::LoadElimination::broker_ [private]
Definition at line 369 of file load-elimination.h.
jsgraph_
JSGraph* const v8::internal::compiler::LoadElimination::jsgraph_ [private]
Definition at line 371 of file load-elimination.h.
kMaxTrackedElements
const size_t v8::internal::compiler::LoadElimination::kMaxTrackedElements = 8 [static], [private]
Definition at line 47 of file load-elimination.h.
kMaxTrackedFields
int const v8::internal::compiler::LoadElimination::kMaxTrackedFields = 300 [static], [private]
Definition at line 192 of file load-elimination.h.
kMaxTrackedFieldsPerObject
size_t const v8::internal::compiler::LoadElimination::kMaxTrackedFieldsPerObject = 32 [static], [private]
Definition at line 190 of file load-elimination.h.
kMaxTrackedObjects
size_t const v8::internal::compiler::LoadElimination::kMaxTrackedObjects = 100 [static], [private]
Definition at line 191 of file load-elimination.h.
Referenced by v8::internal::compiler::LoadElimination::AbstractMaps::Extend().
node_states_
AbstractStateForEffectNodes v8::internal::compiler::LoadElimination::node_states_ [private]
Definition at line 370 of file load-elimination.h.
Referenced by Reduce(), ReduceCheckMaps(), ReduceCompareMaps(), ReduceEffectPhi(), ReduceEnsureWritableFastElements(), ReduceLoadElement(), ReduceLoadField(), ReduceMapGuard(), ReduceMaybeGrowFastElements(), ReduceOtherNode(), ReduceStoreElement(), ReduceStoreField(), ReduceStoreTypedElement(), ReduceTransitionAndStoreElement(), ReduceTransitionElementsKind(), ReduceTransitionElementsKindOrCheckMap(), UpdateState(), and UpdateStateForPhi().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/load-elimination.h
/mnt/V8SourceCode/src/compiler/load-elimination.cc