v8::internal::ReadOnlyArtifacts Class Reference
#include <read-only-spaces.h>
Classes
struct ExternalPointerRegistryEntry
Public Member Functions
ReadOnlyArtifacts ()=default
~ReadOnlyArtifacts ()
void Initialize (Isolate *isolate, std::vector< ReadOnlyPageMetadata * > &&pages, const AllocationStats &stats)
void ReinstallReadOnlySpace (Isolate *isolate)
void VerifyHeapAndSpaceRelationships (Isolate *isolate)
std::vector< ReadOnlyPageMetadata * > & pages ()
const AllocationStats & accounting_stats () const
SharedReadOnlySpace * shared_read_only_space ()
void set_read_only_heap (std::unique_ptr< ReadOnlyHeap > read_only_heap)
ReadOnlyHeap * read_only_heap () const
void set_initial_next_unique_sfi_id (uint32_t id)
uint32_t initial_next_unique_sfi_id () const
void set_external_pointer_registry (std::vector< ExternalPointerRegistryEntry > &&registry)
const std::vector< ExternalPointerRegistryEntry > & external_pointer_registry () const
void InitializeChecksum (SnapshotData *read_only_snapshot_data)
void VerifyChecksum (SnapshotData *read_only_snapshot_data, bool read_only_heap_created)
Private Attributes
std::vector< ReadOnlyPageMetadata * > pages_
AllocationStats stats_
std::unique_ptr< SharedReadOnlySpace > shared_read_only_space_
std::unique_ptr< ReadOnlyHeap > read_only_heap_
uint32_t initial_next_unique_sfi_id_ = 0
std::vector< ExternalPointerRegistryEntry > external_pointer_registry_
v8::PageAllocator * page_allocator_ = nullptr
Friends
class ReadOnlyHeap
Detailed Description
Definition at line 70 of file read-only-spaces.h.
Constructor & Destructor Documentation
ReadOnlyArtifacts()
v8::internal::ReadOnlyArtifacts::ReadOnlyArtifacts () [default]
 ReadOnlyArtifacts()
v8::internal::ReadOnlyArtifacts::~ReadOnlyArtifacts ()
Definition at line 29 of file read-only-spaces.cc.
                                      {
  // SharedReadOnlySpace is aware that it doesn't actually own the pages.
  shared_read_only_space_->TearDown(nullptr);
  for (ReadOnlyPageMetadata* metadata : pages_) {
    void* chunk_address = reinterpret_cast<void*>(metadata->ChunkAddress());
    size_t size =
        RoundUp(metadata->size(), page_allocator_->AllocatePageSize());
    CHECK(page_allocator_->FreePages(chunk_address, size));
    delete metadata;
  }
}
References v8::PageAllocator::AllocatePageSize(), CHECK, v8::PageAllocator::FreePages(), page_allocator_, pages_, RoundUp(), shared_read_only_space_, and size().
Member Function Documentation
accounting_stats()
const AllocationStats& v8::internal::ReadOnlyArtifacts::accounting_stats () const [inline]
Definition at line 91 of file read-only-spaces.h.
{ return stats_; }
References stats_.
Referenced by v8::internal::SharedReadOnlySpace::SharedReadOnlySpace().
external_pointer_registry()
const std::vector<ExternalPointerRegistryEntry>& v8::internal::ReadOnlyArtifacts::external_pointer_registry () const [inline]
Definition at line 120 of file read-only-spaces.h.
            {
    return external_pointer_registry_;
  }
References external_pointer_registry_.
initial_next_unique_sfi_id()
uint32_t v8::internal::ReadOnlyArtifacts::initial_next_unique_sfi_id () const [inline]
Definition at line 103 of file read-only-spaces.h.
                                              {
    return initial_next_unique_sfi_id_;
  }
References initial_next_unique_sfi_id_.
Referenced by v8::internal::Isolate::SetUpFromReadOnlyArtifacts().
Initialize()
void v8::internal::ReadOnlyArtifacts::Initialize (Isolate * isolate, std::vector< ReadOnlyPageMetadata * > && pages, const AllocationStats & stats)
Definition at line 42 of file read-only-spaces.cc.
                                                                 {
  page_allocator_ = isolate->isolate_group()->page_allocator();
  pages_ = std::move(pages);
  stats_ = stats;
  shared_read_only_space_ =
      std::make_unique<SharedReadOnlySpace>(isolate->heap(), this);
}
References v8::internal::Isolate::heap(), v8::internal::Isolate::isolate_group(), v8::internal::IsolateGroup::page_allocator(), page_allocator_, pages(), pages_, shared_read_only_space_, and stats_.
Referenced by v8::internal::ReadOnlySpace::DetachPagesAndAddToArtifacts().
InitializeChecksum()
void v8::internal::ReadOnlyArtifacts::InitializeChecksum (SnapshotData * read_only_snapshot_data)
Definition at line 69 of file read-only-spaces.cc.
                                           {
#ifdef DEBUG
  read_only_blob_checksum_ = Checksum(read_only_snapshot_data->Payload());
#endif // DEBUG
}
References v8::internal::Checksum(), and v8::internal::SnapshotData::Payload().
Referenced by v8::internal::ReadOnlyHeap::SetUp().
pages()
std::vector<ReadOnlyPageMetadata*>& v8::internal::ReadOnlyArtifacts::pages () [inline]
Definition at line 89 of file read-only-spaces.h.
{ return pages_; }
References pages_.
Referenced by Initialize(), and v8::internal::SharedReadOnlySpace::SharedReadOnlySpace().
read_only_heap()
ReadOnlyHeap* v8::internal::ReadOnlyArtifacts::read_only_heap () const [inline]
Definition at line 98 of file read-only-spaces.h.
{ return read_only_heap_.get(); }
References read_only_heap_.
Referenced by set_read_only_heap(), v8::internal::ReadOnlyHeap::SetUp(), v8::internal::Isolate::SetUpFromReadOnlyArtifacts(), and VerifyHeapAndSpaceRelationships().
ReinstallReadOnlySpace()
void v8::internal::ReadOnlyArtifacts::ReinstallReadOnlySpace (Isolate * isolate)
Definition at line 52 of file read-only-spaces.cc.
                                                               {
  isolate->heap()->ReplaceReadOnlySpace(shared_read_only_space());
}
References v8::internal::Isolate::heap(), v8::internal::Heap::ReplaceReadOnlySpace(), and shared_read_only_space().
Referenced by v8::internal::ReadOnlyHeap::InitFromIsolate().
set_external_pointer_registry()
void v8::internal::ReadOnlyArtifacts::set_external_pointer_registry (std::vector< ExternalPointerRegistryEntry > && registry) [inline]
Definition at line 115 of file read-only-spaces.h.
                                                          {
    DCHECK(external_pointer_registry_.empty());
    external_pointer_registry_ = std::move(registry);
  }
References v8::internal::DCHECK(), and external_pointer_registry_.
Referenced by v8::internal::ObjectPostProcessor::Finalize().
set_initial_next_unique_sfi_id()
void v8::internal::ReadOnlyArtifacts::set_initial_next_unique_sfi_id (uint32_t id) [inline]
Definition at line 100 of file read-only-spaces.h.
                                                   {
    initial_next_unique_sfi_id_ = id;
  }
References initial_next_unique_sfi_id_.
Referenced by v8::internal::ReadOnlyHeap::SetUp().
set_read_only_heap()
void v8::internal::ReadOnlyArtifacts::set_read_only_heap (std::unique_ptr< ReadOnlyHeap > read_only_heap)
Definition at line 64 of file read-only-spaces.cc.
                                                {
  read_only_heap_ = std::move(read_only_heap);
}
References read_only_heap(), and read_only_heap_.
Referenced by v8::internal::ReadOnlyHeap::CreateInitialHeapForBootstrapping().
shared_read_only_space()
SharedReadOnlySpace* v8::internal::ReadOnlyArtifacts::shared_read_only_space () [inline]
Definition at line 93 of file read-only-spaces.h.
                                                {
    return shared_read_only_space_.get();
  }
References shared_read_only_space_.
Referenced by v8::internal::ReadOnlyHeap::InitFromIsolate(), v8::internal::ReadOnlyHeap::PopulateReadOnlySpaceStatistics(), ReinstallReadOnlySpace(), and VerifyHeapAndSpaceRelationships().
VerifyChecksum()
void v8::internal::ReadOnlyArtifacts::VerifyChecksum (SnapshotData * read_only_snapshot_data, bool read_only_heap_created)
Definition at line 76 of file read-only-spaces.cc.
                                                                    {
#ifdef DEBUG
  if (read_only_blob_checksum_) {
    // The read-only heap was set up from a snapshot. Make sure it's the always
    // the same snapshot.
    uint32_t snapshot_checksum = Checksum(read_only_snapshot_data->Payload());
    CHECK_WITH_MSG(snapshot_checksum,
                   "Attempt to create the read-only heap after already "
                   "creating from a snapshot.");
    if (!v8_flags.stress_snapshot) {
      // --stress-snapshot is only intended to check how well the
      // serializer/deserializer copes with unexpected objects, and is not
      // intended to test whether the newly deserialized Isolate would actually
      // work since it serializes a currently running Isolate, which is not
      // supported. As a result, it's possible that it will create a new
      // read-only snapshot that is not compatible with the original one (for
      // instance due to the string table being re-ordered). Since we won't
      // actually use that new Isolate, we're ok with any potential corruption.
      // See crbug.com/1043058.
      CHECK_EQ(read_only_blob_checksum_, snapshot_checksum);
    }
  } else {
    // If there's no checksum, then that means the read-only heap objects are
    // being created.
    CHECK(read_only_heap_created);
  }
#endif // DEBUG
}
References CHECK, CHECK_EQ, CHECK_WITH_MSG, v8::internal::Checksum(), v8::internal::SnapshotData::Payload(), and v8::internal::v8_flags.
Referenced by v8::internal::ReadOnlyHeap::SetUp().
VerifyHeapAndSpaceRelationships()
void v8::internal::ReadOnlyArtifacts::VerifyHeapAndSpaceRelationships (Isolate * isolate)
Definition at line 56 of file read-only-spaces.cc.
                                                                        {
  DCHECK_EQ(read_only_heap()->read_only_space(), shared_read_only_space());
  // Confirm the Isolate is using the shared ReadOnlyHeap and ReadOnlySpace.
  DCHECK_EQ(read_only_heap(), isolate->read_only_heap());
  DCHECK_EQ(shared_read_only_space(), isolate->heap()->read_only_space());
}
References DCHECK_EQ, v8::internal::Isolate::heap(), v8::internal::Isolate::read_only_heap(), read_only_heap(), v8::internal::Heap::read_only_space(), and shared_read_only_space().
Referenced by v8::internal::ReadOnlyHeap::InitFromIsolate().
Friends And Related Function Documentation
ReadOnlyHeap
friend class ReadOnlyHeap [friend]
Definition at line 130 of file read-only-spaces.h.
Member Data Documentation
external_pointer_registry_
std::vector<ExternalPointerRegistryEntry> v8::internal::ReadOnlyArtifacts::external_pointer_registry_ [private]
Definition at line 137 of file read-only-spaces.h.
Referenced by external_pointer_registry(), and set_external_pointer_registry().
initial_next_unique_sfi_id_
uint32_t v8::internal::ReadOnlyArtifacts::initial_next_unique_sfi_id_ = 0 [private]
Definition at line 136 of file read-only-spaces.h.
Referenced by initial_next_unique_sfi_id(), and set_initial_next_unique_sfi_id().
page_allocator_
v8::PageAllocator* v8::internal::ReadOnlyArtifacts::page_allocator_ = nullptr [private]
Definition at line 143 of file read-only-spaces.h.
Referenced by Initialize(), and ~ReadOnlyArtifacts().
pages_
std::vector<ReadOnlyPageMetadata*> v8::internal::ReadOnlyArtifacts::pages_ [private]
Definition at line 132 of file read-only-spaces.h.
Referenced by Initialize(), pages(), and ~ReadOnlyArtifacts().
read_only_heap_
std::unique_ptr<ReadOnlyHeap> v8::internal::ReadOnlyArtifacts::read_only_heap_ [private]
Definition at line 135 of file read-only-spaces.h.
Referenced by read_only_heap(), and set_read_only_heap().
shared_read_only_space_
std::unique_ptr<SharedReadOnlySpace> v8::internal::ReadOnlyArtifacts::shared_read_only_space_ [private]
Definition at line 134 of file read-only-spaces.h.
Referenced by Initialize(), shared_read_only_space(), and ~ReadOnlyArtifacts().
stats_
AllocationStats v8::internal::ReadOnlyArtifacts::stats_ [private]
Definition at line 133 of file read-only-spaces.h.
Referenced by accounting_stats(), and Initialize().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/read-only-spaces.h
/mnt/V8SourceCode/src/heap/read-only-spaces.cc