v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next > Class Template Reference
#include <memory-optimization-reducer.h>
Public Member Functions
void Analyze ()
V< None > REDUCE_INPUT_GRAPH() Store (V< None > ig_index, const StoreOp &store)
V< HeapObject > REDUCE() Allocate (V< WordPtr > size, AllocationType type, AllocationAlignment alignment)
V< WordPtr > REDUCE() DecodeExternalPointer (V< Word32 > handle, ExternalPointerTagRange tag_range)
Private Member Functions
Variable top (AllocationType type)
const TSCallDescriptor * AllocateBuiltinDescriptor ()
V< WordPtr > GetLimitAddress (AllocationType type)
Private Attributes
std::optional< MemoryAnalyzer > analyzer_
Isolate * isolate_ = __ data() -> isolate()
const TSCallDescriptor * allocate_builtin_descriptor_ = nullptr
std::optional< Variable > top_ [2]
Detailed Description
template<class Next>
class v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >
Definition at line 187 of file memory-optimization-reducer.h.
Member Function Documentation
Allocate()
template<class Next >
V<HeapObject> REDUCE() v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::Allocate (V< WordPtr > size, AllocationType type, AllocationAlignment alignment) [inline]
Definition at line 231 of file memory-optimization-reducer.h.
                                                                {
    DCHECK_EQ(type, any_of(AllocationType::kYoung, AllocationType::kOld,
                           AllocationType::kSharedOld));
#if V8_ENABLE_WEBASSEMBLY
    if (type == AllocationType::kSharedOld) {
      DCHECK_EQ(isolate_, nullptr); // Only possible in wasm.
      DCHECK(analyzer_->is_wasm);
      static_assert(std::is_same_v<Smi, BuiltinPtr>, "BuiltinPtr must be Smi");
      OpIndex allocate_builtin = __ NumberConstant(
          static_cast<int>(Builtin::kWasmAllocateInSharedHeap));
      OpIndex allocated = __ Call(
          allocate_builtin, {size, __ SmiConstant(Smi::FromInt(alignment))},
          AllocateWasmSharedBuiltinDescriptor());
      return allocated;
    }
#endif
    DCHECK_EQ(alignment, kTaggedAligned);
    if (v8_flags.single_generation && type == AllocationType::kYoung) {
      type = AllocationType::kOld;
    }
    V<WordPtr> top_address;
    if (isolate_ != nullptr) {
      top_address = __ ExternalConstant(
          type == AllocationType::kYoung
              ? ExternalReference::new_space_allocation_top_address(isolate_)
              : ExternalReference::old_space_allocation_top_address(isolate_));
    } else {
      // Wasm mode: producing isolate-independent code, loading the isolate
      // address at runtime.
#if V8_ENABLE_WEBASSEMBLY
      V<WasmTrustedInstanceData> instance_data = __ WasmInstanceDataParameter();
      int top_address_offset =
          type == AllocationType::kYoung
              ? WasmTrustedInstanceData::kNewAllocationTopAddressOffset
              : WasmTrustedInstanceData::kOldAllocationTopAddressOffset;
      top_address =
          __ Load(instance_data, LoadOp::Kind::TaggedBase().Immutable(),
                  MemoryRepresentation::UintPtr(), top_address_offset);
#else
      UNREACHABLE();
#endif // V8_ENABLE_WEBASSEMBLY
    }
    if (analyzer_->IsFoldedAllocation(__ current_operation_origin())) {
      DCHECK_NE(__ GetVariable(top(type)), V<WordPtr>::Invalid());
      V<WordPtr> obj_addr = __ GetVariable(top(type));
      __ SetVariable(top(type), __ WordPtrAdd(__ GetVariable(top(type)), size));
      __ StoreOffHeap(top_address, __ GetVariable(top(type)),
                      MemoryRepresentation::UintPtr());
      return __ BitcastWordPtrToHeapObject(
          __ WordPtrAdd(obj_addr, __ IntPtrConstant(kHeapObjectTag)));
    }
    __ SetVariable(top(type), __ LoadOffHeap(top_address,
                                             MemoryRepresentation::UintPtr()));
    V<CallTarget> allocate_builtin;
    if (!analyzer_->is_wasm) {
      if (type == AllocationType::kYoung) {
        allocate_builtin =
            __ BuiltinCode(Builtin::kAllocateInYoungGeneration, isolate_);
      } else {
        allocate_builtin =
            __ BuiltinCode(Builtin::kAllocateInOldGeneration, isolate_);
      }
    } else {
#if V8_ENABLE_WEBASSEMBLY
      // This lowering is used by Wasm, where we compile isolate-independent
      // code. Builtin calls simply encode the target builtin ID, which will
      // be patched to the builtin's address later.
      if (isolate_ == nullptr) {
        Builtin builtin;
        if (type == AllocationType::kYoung) {
          builtin = Builtin::kWasmAllocateInYoungGeneration;
        } else {
          builtin = Builtin::kWasmAllocateInOldGeneration;
        }
        static_assert(std::is_same_v<Smi, BuiltinPtr>,
                      "BuiltinPtr must be Smi");
        allocate_builtin = __ NumberConstant(static_cast<int>(builtin));
      } else {
        if (type == AllocationType::kYoung) {
          allocate_builtin =
              __ BuiltinCode(Builtin::kWasmAllocateInYoungGeneration, isolate_);
        } else {
          allocate_builtin =
              __ BuiltinCode(Builtin::kWasmAllocateInOldGeneration, isolate_);
        }
      }
#else
      UNREACHABLE();
#endif
    }
    Block* call_runtime = __ NewBlock();
    Block* done = __ NewBlock();
    V<WordPtr> limit_address = GetLimitAddress(type);
    // If the allocation size is not statically known or is known to be larger
    // than kMaxRegularHeapObjectSize, do not update {top(type)} in case of a
    // runtime call. This is needed because we cannot allocation-fold large and
    // normal-sized objects.
    uint64_t constant_size{};
    if (!__ matcher().MatchIntegralWordConstant(
            size, WordRepresentation::WordPtr(), &constant_size) ||
        constant_size > kMaxRegularHeapObjectSize) {
      Variable result =
          __ NewLoopInvariantVariable(RegisterRepresentation::Tagged());
      if (!constant_size) {
        // Check if we can do bump pointer allocation here.
        V<WordPtr> top_value = __ GetVariable(top(type));
        __ SetVariable(result,
                       __ BitcastWordPtrToHeapObject(__ WordPtrAdd(
                           top_value, __ IntPtrConstant(kHeapObjectTag))));
        V<WordPtr> new_top = __ WordPtrAdd(top_value, size);
        V<WordPtr> limit =
            __ LoadOffHeap(limit_address, MemoryRepresentation::UintPtr());
        __ GotoIfNot(LIKELY(__ UintPtrLessThan(new_top, limit)), call_runtime);
        __ GotoIfNot(LIKELY(__ UintPtrLessThan(
                         size, __ IntPtrConstant(kMaxRegularHeapObjectSize))),
                     call_runtime);
        __ SetVariable(top(type), new_top);
        __ StoreOffHeap(top_address, new_top, MemoryRepresentation::UintPtr());
        __ Goto(done);
      }
      if (constant_size || __ Bind(call_runtime)) {
        __ SetVariable(
            result, __ template Call<HeapObject>(allocate_builtin, {size},
                                                 AllocateBuiltinDescriptor()));
        __ Goto(done);
      }
      __ BindReachable(done);
      return __ GetVariable(result);
    }
    V<WordPtr> reservation_size;
    if (auto c = analyzer_->ReservedSize(__ current_operation_origin())) {
      reservation_size = __ UintPtrConstant(*c);
    } else {
      reservation_size = size;
    }
    // Check if we can do bump pointer allocation here.
    bool reachable =
        __ GotoIfNot(__ UintPtrLessThan(
                         size, __ IntPtrConstant(kMaxRegularHeapObjectSize)),
                     call_runtime, BranchHint::kTrue) !=
        ConditionalGotoStatus::kGotoDestination;
    if (reachable) {
      V<WordPtr> limit =
          __ LoadOffHeap(limit_address, MemoryRepresentation::UintPtr());
      __ Branch(__ UintPtrLessThan(
                    __ WordPtrAdd(__ GetVariable(top(type)), reservation_size),
                    limit),
                done, call_runtime, BranchHint::kTrue);
    }
    // Call the runtime if bump pointer area exhausted.
    if (__ Bind(call_runtime)) {
      V<HeapObject> allocated = __ template Call<HeapObject>(
          allocate_builtin, {reservation_size}, AllocateBuiltinDescriptor());
      __ SetVariable(top(type),
                     __ WordPtrSub(__ BitcastHeapObjectToWordPtr(allocated),
                                   __ IntPtrConstant(kHeapObjectTag)));
      __ Goto(done);
    }
    __ BindReachable(done);
    // Compute the new top and write it back.
    V<WordPtr> obj_addr = __ GetVariable(top(type));
    __ SetVariable(top(type), __ WordPtrAdd(__ GetVariable(top(type)), size));
    __ StoreOffHeap(top_address, __ GetVariable(top(type)),
                    MemoryRepresentation::UintPtr());
    return __ BitcastWordPtrToHeapObject(
        __ WordPtrAdd(obj_addr, __ IntPtrConstant(kHeapObjectTag)));
  }
References __, v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::AllocateBuiltinDescriptor(), v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::analyzer_, v8::internal::compiler::turboshaft::any_of(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, v8::internal::Smi::FromInt(), v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::GetLimitAddress(), v8::internal::instance_data, v8::internal::compiler::IntPtrConstant(), v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::isolate_, v8::internal::compiler::turboshaft::kGotoDestination, v8::internal::kHeapObjectTag, v8::internal::kMaxRegularHeapObjectSize, v8::internal::kOld, v8::internal::kSharedOld, v8::internal::kTaggedAligned, v8::internal::kTrue, v8::internal::kYoung, v8::Load(), v8::internal::compiler::NumberConstant(), v8::base::internal::result, size(), v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), v8::internal::compiler::turboshaft::LoadOp::Kind::TaggedBase(), v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::top(), v8::internal::tracing::type, v8::internal::compiler::turboshaft::MemoryRepresentation::UintPtr(), v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::UintPtrLessThan(), v8::internal::UNREACHABLE(), v8::internal::v8_flags, and v8::internal::compiler::turboshaft::WordRepresentation::WordPtr().
AllocateBuiltinDescriptor()
template<class Next >
const TSCallDescriptor* v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::AllocateBuiltinDescriptor () [inline], [private]
Definition at line 517 of file memory-optimization-reducer.h.
                                                      {
    if (allocate_builtin_descriptor_ == nullptr) {
      allocate_builtin_descriptor_ =
          CreateAllocateBuiltinDescriptor(__ graph_zone(), isolate_);
    }
    return allocate_builtin_descriptor_;
  }
References __, v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::allocate_builtin_descriptor_, v8::internal::compiler::turboshaft::CreateAllocateBuiltinDescriptor(), and v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::isolate_.
Referenced by v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::Allocate().
Analyze()
template<class Next >
void v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::Analyze () [inline]
Definition at line 193 of file memory-optimization-reducer.h.
                 {
    auto* info = __ data() -> info();
#if V8_ENABLE_WEBASSEMBLY
    bool is_wasm = info->IsWasm() || info->IsWasmBuiltin();
#else
    bool is_wasm = false;
#endif
    analyzer_.emplace(
        __ data(), __ phase_zone(), __ input_graph(),
        info->allocation_folding()
            ? MemoryAnalyzer::AllocationFolding::kDoAllocationFolding
            : MemoryAnalyzer::AllocationFolding::kDontAllocationFolding,
        is_wasm);
    analyzer_->Run();
    Next::Analyze();
  }
References __, v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::analyzer_, v8::internal::compiler::turboshaft::MemoryAnalyzer::kDoAllocationFolding, and v8::internal::compiler::turboshaft::MemoryAnalyzer::kDontAllocationFolding.
DecodeExternalPointer()
template<class Next >
V<WordPtr> REDUCE() v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::DecodeExternalPointer (V< Word32 > handle, ExternalPointerTagRange tag_range) [inline]
Definition at line 412 of file memory-optimization-reducer.h.
                                                                              {
#ifdef V8_ENABLE_SANDBOX
    // Decode loaded external pointer.
    V<WordPtr> table;
    if (isolate_ != nullptr) {
      // Here we access the external pointer table through an ExternalReference.
      // Alternatively, we could also hardcode the address of the table since it
      // is never reallocated. However, in that case we must be able to
      // guarantee that the generated code is never executed under a different
      // Isolate, as that would allow access to external objects from different
      // Isolates. It also would break if the code is serialized/deserialized at
      // some point.
      V<WordPtr> table_address =
          IsSharedExternalPointerType(tag_range)
              ? __
                LoadOffHeap(
                    __ ExternalConstant(
                        ExternalReference::
                            shared_external_pointer_table_address_address(
                                isolate_)),
                    MemoryRepresentation::UintPtr())
              : __ ExternalConstant(
                    ExternalReference::external_pointer_table_address(
                        isolate_));
      table = __ LoadOffHeap(table_address,
                             Internals::kExternalPointerTableBasePointerOffset,
                             MemoryRepresentation::UintPtr());
    } else {
#if V8_ENABLE_WEBASSEMBLY
      V<WordPtr> isolate_root = __ LoadRootRegister();
      if (IsSharedExternalPointerType(tag_range)) {
        V<WordPtr> table_address =
            __ Load(isolate_root, LoadOp::Kind::RawAligned(),
                    MemoryRepresentation::UintPtr(),
                    IsolateData::shared_external_pointer_table_offset());
        table = __ Load(table_address, LoadOp::Kind::RawAligned(),
                        MemoryRepresentation::UintPtr(),
                        Internals::kExternalPointerTableBasePointerOffset);
      } else {
        table = __ Load(isolate_root, LoadOp::Kind::RawAligned(),
                        MemoryRepresentation::UintPtr(),
                        IsolateData::external_pointer_table_offset() +
                            Internals::kExternalPointerTableBasePointerOffset);
      }
#else
      UNREACHABLE();
#endif
    }
    V<Word32> index =
        __ Word32ShiftRightLogical(handle, kExternalPointerIndexShift);
    V<Word64> pointer = __ LoadOffHeap(table, __ ChangeUint32ToUint64(index), 0,
                                       MemoryRepresentation::Uint64());
    // We don't expect to see empty fields here. If this is ever needed,
    // consider using an dedicated empty value entry for those tags instead
    // (i.e. an entry with the right tag and nullptr payload).
    DCHECK(!ExternalPointerCanBeEmpty(tag_range));
    Block* done = __ NewBlock();
    if (tag_range.Size() == 1) {
      // The common and simple case: we expect a specific tag.
      V<Word64> tag_bits = __ Word64BitwiseAnd(
          pointer, __ Word64Constant(kExternalPointerTagMask));
      tag_bits = __ Word64ShiftRightLogical(tag_bits, kExternalPointerTagShift);
      V<Word32> tag = __ TruncateWord64ToWord32(tag_bits);
      V<Word32> expected_tag = __ Word32Constant(tag_range.first);
      __ GotoIf(__ Word32Equal(tag, expected_tag), done, BranchHint::kTrue);
      // TODO(saelo): it would be nicer to abort here with
      // AbortReason::kExternalPointerTagMismatch. That might require adding a
      // builtin call here though, which is not currently available.
      __ Unreachable();
    } else {
      // Not currently supported. Implement once needed.
      DCHECK_NE(tag_range, kAnyExternalPointerTagRange);
      UNREACHABLE();
    }
    __ BindReachable(done);
    return __ Word64BitwiseAnd(pointer, kExternalPointerPayloadMask);
#else // V8_ENABLE_SANDBOX
    UNREACHABLE();
#endif // V8_ENABLE_SANDBOX
  }
References __, v8::internal::DCHECK(), DCHECK_NE, v8::internal::ExternalPointerCanBeEmpty(), v8::internal::handle(), v8::internal::index, v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::isolate_, v8::internal::IsSharedExternalPointerType(), v8::internal::kAnyExternalPointerTagRange(), v8::internal::kExternalPointerPayloadMask, v8::internal::Internals::kExternalPointerTableBasePointerOffset, v8::internal::kExternalPointerTagMask, v8::internal::kExternalPointerTagShift, v8::internal::kTrue, v8::Load(), v8::internal::compiler::turboshaft::LoadOp::Kind::RawAligned(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint64(), v8::internal::compiler::turboshaft::MemoryRepresentation::UintPtr(), v8::internal::UNREACHABLE(), and v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal().
GetLimitAddress()
template<class Next >
V<WordPtr> v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::GetLimitAddress (AllocationType type) [inline], [private]
Definition at line 535 of file memory-optimization-reducer.h.
                                                  {
    V<WordPtr> limit_address;
    if (isolate_ != nullptr) {
      limit_address = __ ExternalConstant(
          type == AllocationType::kYoung
              ? ExternalReference::new_space_allocation_limit_address(isolate_)
              : ExternalReference::old_space_allocation_limit_address(
                    isolate_));
    } else {
      // Wasm mode: producing isolate-independent code, loading the isolate
      // address at runtime.
#if V8_ENABLE_WEBASSEMBLY
      V<WasmTrustedInstanceData> instance_node = __ WasmInstanceDataParameter();
      int limit_address_offset =
          type == AllocationType::kYoung
              ? WasmTrustedInstanceData::kNewAllocationLimitAddressOffset
              : WasmTrustedInstanceData::kOldAllocationLimitAddressOffset;
      limit_address =
          __ Load(instance_node, LoadOp::Kind::TaggedBase(),
                  MemoryRepresentation::UintPtr(), limit_address_offset);
#else
      UNREACHABLE();
#endif // V8_ENABLE_WEBASSEMBLY
    }
    return limit_address;
  }
References __, v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::isolate_, v8::internal::kYoung, v8::Load(), v8::internal::compiler::turboshaft::LoadOp::Kind::TaggedBase(), v8::internal::tracing::type, v8::internal::compiler::turboshaft::MemoryRepresentation::UintPtr(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::Allocate().
Store()
template<class Next >
V<None> REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::Store (V< None > ig_index, const StoreOp & store) [inline]
Definition at line 210 of file memory-optimization-reducer.h.
                                                                            {
    if (store.write_barrier != WriteBarrierKind::kAssertNoWriteBarrier) {
      // We cannot skip this optimization if we have to eliminate a
      // {kAssertNoWriteBarrier}.
      if (ShouldSkipOptimizationStep()) {
        return Next::ReduceInputGraphStore(ig_index, store);
      }
    }
    if (analyzer_->skipped_write_barriers.count(ig_index)) {
      __ Store(__ MapToNewGraph(store.base()), __ MapToNewGraph(store.index()),
               __ MapToNewGraph(store.value()), store.kind, store.stored_rep,
               WriteBarrierKind::kNoWriteBarrier, store.offset,
               store.element_size_log2,
               store.maybe_initializing_or_transitioning,
               store.indirect_pointer_tag());
      return V<None>::Invalid();
    }
    DCHECK_NE(store.write_barrier, WriteBarrierKind::kAssertNoWriteBarrier);
    return Next::ReduceInputGraphStore(ig_index, store);
  }
References __, v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::analyzer_, DCHECK_NE, v8::internal::compiler::turboshaft::V< T >::Invalid(), v8::internal::compiler::kAssertNoWriteBarrier, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep(), and store().
top()
template<class Next >
Variable v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::top (AllocationType type) [inline], [private]
Definition at line 508 of file memory-optimization-reducer.h.
                                    {
    DCHECK(type == AllocationType::kYoung || type == AllocationType::kOld);
    if (V8_UNLIKELY(!top_[static_cast<int>(type)].has_value())) {
      top_[static_cast<int>(type)].emplace(
          __ NewLoopInvariantVariable(RegisterRepresentation::WordPtr()));
    }
    return top_[static_cast<int>(type)].value();
  }
References __, v8::internal::DCHECK(), v8::internal::kOld, v8::internal::kYoung, v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::top_, v8::internal::tracing::type, V8_UNLIKELY, v8::internal::value, and v8::internal::compiler::turboshaft::RegisterRepresentation::WordPtr().
Referenced by v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::Allocate().
Member Data Documentation
allocate_builtin_descriptor_
template<class Next >
const TSCallDescriptor* v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::allocate_builtin_descriptor_ = nullptr [private]
Definition at line 500 of file memory-optimization-reducer.h.
Referenced by v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::AllocateBuiltinDescriptor().
analyzer_
template<class Next >
std::optional<MemoryAnalyzer> v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::analyzer_ [private]
Definition at line 498 of file memory-optimization-reducer.h.
Referenced by v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::Allocate(), v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::Analyze(), and v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::Store().
isolate_
template<class Next >
Isolate* v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::isolate_ = __ data() -> isolate() [private]
Definition at line 499 of file memory-optimization-reducer.h.
Referenced by v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::Allocate(), v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::AllocateBuiltinDescriptor(), v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::DecodeExternalPointer(), and v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::GetLimitAddress().
top_
template<class Next >
std::optional<Variable> v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::top_[2] [private]
Definition at line 504 of file memory-optimization-reducer.h.
Referenced by v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::top().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/memory-optimization-reducer.h