v8::platform::DelayedTaskQueue Class Reference
#include <delayed-task-queue.h>
Classes
struct MaybeNextTask
Public Types
using TimeFunction = double(*)()
Public Member Functions
DelayedTaskQueue (TimeFunction time_function)
~DelayedTaskQueue ()
DelayedTaskQueue (const DelayedTaskQueue &)=delete
DelayedTaskQueue & operator= (const DelayedTaskQueue &)=delete
double MonotonicallyIncreasingTime ()
void Append (std::unique_ptr< Task > task)
void AppendDelayed (std::unique_ptr< Task > task, double delay_in_seconds)
MaybeNextTask TryGetNext ()
void Terminate ()
Private Member Functions
std::unique_ptr< Task > PopTaskFromDelayedQueue (double now)
Private Attributes
std::queue< std::unique_ptr< Task > > task_queue_
std::multimap< double, std::unique_ptr< Task > > delayed_task_queue_
bool terminated_ = false
TimeFunction time_function_
Detailed Description
Definition at line 27 of file delayed-task-queue.h.
Member Typedef Documentation
TimeFunction
using v8::platform::DelayedTaskQueue::TimeFunction = double (*)()
Definition at line 29 of file delayed-task-queue.h.
Constructor & Destructor Documentation
DelayedTaskQueue() [1/2]
v8::platform::DelayedTaskQueue::DelayedTaskQueue (TimeFunction time_function) [explicit]
Definition at line 14 of file delayed-task-queue.cc.
    : time_function_(time_function) {}
 DelayedTaskQueue()
v8::platform::DelayedTaskQueue::~DelayedTaskQueue ()
Definition at line 17 of file delayed-task-queue.cc.
                                    {
  DCHECK(terminated_);
  DCHECK(task_queue_.empty());
}
References DCHECK, task_queue_, and terminated_.
DelayedTaskQueue() [2/2]
v8::platform::DelayedTaskQueue::DelayedTaskQueue (const DelayedTaskQueue &) [delete]
Member Function Documentation
Append()
void v8::platform::DelayedTaskQueue::Append (std::unique_ptr< Task > task)
Definition at line 26 of file delayed-task-queue.cc.
                                                      {
  DCHECK(!terminated_);
  task_queue_.push(std::move(task));
}
References DCHECK, task_queue_, and terminated_.
Referenced by v8::platform::DefaultWorkerThreadsTaskRunner::PostTaskImpl().
AppendDelayed()
void v8::platform::DelayedTaskQueue::AppendDelayed (std::unique_ptr< Task > task, double delay_in_seconds)
Definition at line 31 of file delayed-task-queue.cc.
                                                              {
  DCHECK_GE(delay_in_seconds, 0.0);
  double deadline = MonotonicallyIncreasingTime() + delay_in_seconds;
  {
    DCHECK(!terminated_);
    delayed_task_queue_.emplace(deadline, std::move(task));
  }
}
References DCHECK, DCHECK_GE, delayed_task_queue_, MonotonicallyIncreasingTime(), and terminated_.
Referenced by v8::platform::DefaultWorkerThreadsTaskRunner::PostDelayedTaskImpl().
MonotonicallyIncreasingTime()
double v8::platform::DelayedTaskQueue::MonotonicallyIncreasingTime ()
Definition at line 22 of file delayed-task-queue.cc.
                                                     {
  return time_function_();
}
References time_function_.
Referenced by AppendDelayed(), and TryGetNext().
operator=()
DelayedTaskQueue& v8::platform::DelayedTaskQueue::operator= (const DelayedTaskQueue &) [delete]
PopTaskFromDelayedQueue()
std::unique_ptr< Task > v8::platform::DelayedTaskQueue::PopTaskFromDelayedQueue (double now) [private]
Definition at line 76 of file delayed-task-queue.cc.
                                                                        {
  if (delayed_task_queue_.empty()) return nullptr;
  auto it = delayed_task_queue_.begin();
  if (it->first > now) return nullptr;
  std::unique_ptr<Task> result = std::move(it->second);
  delayed_task_queue_.erase(it);
  return result;
}
References delayed_task_queue_, and v8::base::internal::result.
Referenced by TryGetNext().
Terminate()
void v8::platform::DelayedTaskQueue::Terminate ()
Definition at line 87 of file delayed-task-queue.cc.
                                 {
  DCHECK(!terminated_);
  terminated_ = true;
}
References DCHECK, and terminated_.
Referenced by v8::platform::DefaultWorkerThreadsTaskRunner::Terminate().
TryGetNext()
DelayedTaskQueue::MaybeNextTask v8::platform::DelayedTaskQueue::TryGetNext ()
Definition at line 41 of file delayed-task-queue.cc.
                                                           {
  for (;;) {
    // Move delayed tasks that have hit their deadline to the main queue.
    double now = MonotonicallyIncreasingTime();
    for (;;) {
      std::unique_ptr<Task> task = PopTaskFromDelayedQueue(now);
      if (!task) break;
      task_queue_.push(std::move(task));
    }
    if (!task_queue_.empty()) {
      std::unique_ptr<Task> task = std::move(task_queue_.front());
      task_queue_.pop();
      return {MaybeNextTask::kTask, std::move(task), {}};
    }
    if (terminated_) {
      return {MaybeNextTask::kTerminated, {}, {}};
    }
    if (task_queue_.empty() && !delayed_task_queue_.empty()) {
      // Wait for the next delayed task or a newly posted task.
      double wait_in_seconds = delayed_task_queue_.begin()->first - now;
      return {
          MaybeNextTask::kWaitDelayed,
          {},
          base::TimeDelta::FromMicroseconds(
              base::TimeConstants::kMicrosecondsPerSecond * wait_in_seconds)};
    } else {
      return {MaybeNextTask::kWaitIndefinite, {}, {}};
    }
  }
}
References delayed_task_queue_, v8::base::TimeDelta::FromMicroseconds(), v8::base::TimeConstants::kMicrosecondsPerSecond, v8::platform::DelayedTaskQueue::MaybeNextTask::kTask, v8::platform::DelayedTaskQueue::MaybeNextTask::kTerminated, v8::platform::DelayedTaskQueue::MaybeNextTask::kWaitDelayed, v8::platform::DelayedTaskQueue::MaybeNextTask::kWaitIndefinite, MonotonicallyIncreasingTime(), PopTaskFromDelayedQueue(), task_queue_, and terminated_.
Member Data Documentation
delayed_task_queue_
std::multimap<double, std::unique_ptr<Task> > v8::platform::DelayedTaskQueue::delayed_task_queue_ [private]
Definition at line 67 of file delayed-task-queue.h.
Referenced by AppendDelayed(), PopTaskFromDelayedQueue(), and TryGetNext().
task_queue_
std::queue<std::unique_ptr<Task> > v8::platform::DelayedTaskQueue::task_queue_ [private]
Definition at line 66 of file delayed-task-queue.h.
Referenced by Append(), TryGetNext(), and ~DelayedTaskQueue().
terminated_
bool v8::platform::DelayedTaskQueue::terminated_ = false [private]
Definition at line 68 of file delayed-task-queue.h.
Referenced by Append(), AppendDelayed(), Terminate(), TryGetNext(), and ~DelayedTaskQueue().
time_function_
TimeFunction v8::platform::DelayedTaskQueue::time_function_ [private]
Definition at line 69 of file delayed-task-queue.h.
Referenced by MonotonicallyIncreasingTime().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/libplatform/delayed-task-queue.h
/mnt/V8SourceCode/src/libplatform/delayed-task-queue.cc