v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ConsistentJSFunctionViewDependency Class Reference
Public Member Functions
ConsistentJSFunctionViewDependency (JSFunctionRef function)
bool IsValid (JSHeapBroker *broker) const override
void Install (JSHeapBroker *broker, PendingDependencies *deps) const override
Private Member Functions
size_t Hash () const override
bool Equals (const CompilationDependency *that) const override
Private Attributes
const JSFunctionRef function_
Additional Inherited Members
Detailed Description
Definition at line 633 of file compilation-dependencies.cc.
Constructor & Destructor Documentation
ConsistentJSFunctionViewDependency()
v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ConsistentJSFunctionViewDependency::ConsistentJSFunctionViewDependency (JSFunctionRef function) [inline], [explicit]
Definition at line 635 of file compilation-dependencies.cc.
      : CompilationDependency(kConsistentJSFunctionView), function_(function) {}
Member Function Documentation
Equals()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ConsistentJSFunctionViewDependency::Equals (const CompilationDependency * that) const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 651 of file compilation-dependencies.cc.
                                                                {
    const ConsistentJSFunctionViewDependency* const zat =
        that->AsConsistentJSFunctionView();
    return function_.equals(zat->function_);
  }
References function_.
Hash()
size_t v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ConsistentJSFunctionViewDependency::Hash () const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 646 of file compilation-dependencies.cc.
                               {
    ObjectRef::Hash h;
    return base::hash_combine(h(function_));
  }
References h(), v8::internal::Hash(), and v8::base::hash_combine().
Install()
void v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ConsistentJSFunctionViewDependency::Install (JSHeapBroker * broker, PendingDependencies * deps) const [inline], [override]
Definition at line 642 of file compilation-dependencies.cc.
                                                                               {
  }
IsValid()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ConsistentJSFunctionViewDependency::IsValid (JSHeapBroker * broker) const [inline], [override], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 638 of file compilation-dependencies.cc.
                                                    {
    return function_.IsConsistentWithHeapState(broker);
  }
References broker().
Member Data Documentation
function_
const JSFunctionRef v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ConsistentJSFunctionViewDependency::function_ [private]
Definition at line 657 of file compilation-dependencies.cc.
Referenced by Equals().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/compilation-dependencies.cc