v8::internal::maglev::CallKnownJSFunction Class Reference
#include <maglev-ir.h>
Public Member Functions
CallKnownJSFunction (uint64_t bitfield, compiler::SharedFunctionInfoRef shared_function_info, ValueNode *closure, ValueNode *context, ValueNode *receiver, ValueNode *new_target)
Input & closure ()
const Input & closure () const
Input & context ()
const Input & context () const
Input & receiver ()
const Input & receiver () const
Input & new_target ()
const Input & new_target () const
int num_args () const
Input & arg (int i)
void set_arg (int i, ValueNode *node)
auto args ()
compiler::SharedFunctionInfoRef shared_function_info () const
void VerifyInputs (MaglevGraphLabeller *graph_labeller) const
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
int expected_parameter_count () const
Static Public Attributes
static constexpr int kClosureIndex = 0
static constexpr int kContextIndex = 1
static constexpr int kReceiverIndex = 2
static constexpr int kNewTargetIndex = 3
static constexpr int kFixedInputCount = 4
static constexpr OpProperties kProperties = OpProperties::JSCall()
Private Types
using Base = ValueNodeT< CallKnownJSFunction >
Private Attributes
const compiler::SharedFunctionInfoRef shared_function_info_
int expected_parameter_count_
Additional Inherited Members
Detailed Description
Definition at line 10529 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::CallKnownJSFunction::Base = ValueNodeT<CallKnownJSFunction> [private]
Definition at line 10530 of file maglev-ir.h.
Constructor & Destructor Documentation
CallKnownJSFunction()
v8::internal::maglev::CallKnownJSFunction::CallKnownJSFunction (uint64_t bitfield, compiler::SharedFunctionInfoRef shared_function_info, ValueNode * closure, ValueNode * context, ValueNode * receiver, ValueNode * new_target) [inline]
Definition at line 86 of file maglev-ir-inl.h.
    : Base(bitfield),
#ifdef V8_ENABLE_LEAPTIERING
      dispatch_handle_(dispatch_handle),
#endif
      shared_function_info_(shared_function_info),
      expected_parameter_count_(
#ifdef V8_ENABLE_LEAPTIERING
          IsolateGroup::current()->js_dispatch_table()->GetParameterCount(
              dispatch_handle)
#else
          shared_function_info
              .internal_formal_parameter_count_with_receiver_deprecated()
#endif
      ) {
  set_input(kClosureIndex, closure);
  set_input(kContextIndex, context);
  set_input(kReceiverIndex, receiver);
  set_input(kNewTargetIndex, new_target);
}
References closure(), context(), kClosureIndex, kContextIndex, kNewTargetIndex, kReceiverIndex, new_target(), and receiver().
Member Function Documentation
arg()
Input& v8::internal::maglev::CallKnownJSFunction::arg (int i) [inline]
Definition at line 10564 of file maglev-ir.h.
{ return input(i + kFixedInputCount); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
args()
auto v8::internal::maglev::CallKnownJSFunction::args () [inline]
Definition at line 10568 of file maglev-ir.h.
              {
    return base::make_iterator_range(
        std::make_reverse_iterator(&arg(-1)),
        std::make_reverse_iterator(&arg(num_args() - 1)));
  }
References v8::base::make_iterator_range().
closure() [1/2]
Input& v8::internal::maglev::CallKnownJSFunction::closure () [inline]
Definition at line 10555 of file maglev-ir.h.
{ return input(kClosureIndex); }
Referenced by v8::internal::maglev::MaglevInliner::BuildInlineFunction(), CallKnownJSFunction(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
closure() [2/2]
const Input& v8::internal::maglev::CallKnownJSFunction::closure () const [inline]
Definition at line 10556 of file maglev-ir.h.
{ return input(kClosureIndex); }
context() [1/2]
Input& v8::internal::maglev::CallKnownJSFunction::context () [inline]
Definition at line 10557 of file maglev-ir.h.
{ return input(kContextIndex); }
Referenced by v8::internal::maglev::MaglevInliner::BuildInlineFunction(), CallKnownJSFunction(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
context() [2/2]
const Input& v8::internal::maglev::CallKnownJSFunction::context () const [inline]
Definition at line 10558 of file maglev-ir.h.
{ return input(kContextIndex); }
expected_parameter_count()
int v8::internal::maglev::CallKnownJSFunction::expected_parameter_count () const [inline]
Definition at line 10587 of file maglev-ir.h.
{ return expected_parameter_count_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::CallKnownJSFunction::GenerateCode (MaglevAssembler * , const ProcessingState &)
MaxCallStackArgs()
int v8::internal::maglev::CallKnownJSFunction::MaxCallStackArgs () const
new_target() [1/2]
Input& v8::internal::maglev::CallKnownJSFunction::new_target () [inline]
Definition at line 10561 of file maglev-ir.h.
{ return input(kNewTargetIndex); }
Referenced by v8::internal::maglev::MaglevInliner::BuildInlineFunction(), CallKnownJSFunction(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
new_target() [2/2]
const Input& v8::internal::maglev::CallKnownJSFunction::new_target () const [inline]
Definition at line 10562 of file maglev-ir.h.
{ return input(kNewTargetIndex); }
num_args()
int v8::internal::maglev::CallKnownJSFunction::num_args () const [inline]
Definition at line 10563 of file maglev-ir.h.
{ return input_count() - kFixedInputCount; }
References v8::internal::compiler::turboshaft::detail::input_count().
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::CallKnownJSFunction::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8386 of file maglev-ir.cc.
                                                               {
  os << "(" << shared_function_info_.object() << ")";
}
References v8::internal::compiler::SharedFunctionInfoRef::object(), and shared_function_info_.
receiver() [1/2]
Input& v8::internal::maglev::CallKnownJSFunction::receiver () [inline]
Definition at line 10559 of file maglev-ir.h.
{ return input(kReceiverIndex); }
Referenced by CallKnownJSFunction(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
receiver() [2/2]
const Input& v8::internal::maglev::CallKnownJSFunction::receiver () const [inline]
Definition at line 10560 of file maglev-ir.h.
{ return input(kReceiverIndex); }
set_arg()
void v8::internal::maglev::CallKnownJSFunction::set_arg (int i, ValueNode * node) [inline]
Definition at line 10565 of file maglev-ir.h.
                                       {
    set_input(i + kFixedInputCount, node);
  }
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildCallKnownJSFunction().
SetValueLocationConstraints()
void v8::internal::maglev::CallKnownJSFunction::SetValueLocationConstraints ()
shared_function_info()
compiler::SharedFunctionInfoRef v8::internal::maglev::CallKnownJSFunction::shared_function_info () const [inline]
Definition at line 10574 of file maglev-ir.h.
                                                             {
    return shared_function_info_;
  }
Referenced by v8::internal::maglev::MaglevInliner::BuildInlineFunction(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), and v8::internal::maglev::MaglevInliner::Run().
VerifyInputs()
void v8::internal::maglev::CallKnownJSFunction::VerifyInputs (MaglevGraphLabeller * graph_labeller) const
Definition at line 993 of file maglev-ir.cc.
                                               {
  for (int i = 0; i < input_count(); i++) {
    CheckValueInputIs(this, i, ValueRepresentation::kTagged, graph_labeller);
  }
}
References v8::internal::maglev::CheckValueInputIs(), v8::internal::compiler::turboshaft::detail::input_count(), and v8::internal::maglev::kTagged.
Member Data Documentation
expected_parameter_count_
int v8::internal::maglev::CallKnownJSFunction::expected_parameter_count_ [private]
Definition at line 10596 of file maglev-ir.h.
kClosureIndex
constexpr int v8::internal::maglev::CallKnownJSFunction::kClosureIndex = 0 [static], [constexpr]
Definition at line 10533 of file maglev-ir.h.
Referenced by CallKnownJSFunction().
kContextIndex
constexpr int v8::internal::maglev::CallKnownJSFunction::kContextIndex = 1 [static], [constexpr]
Definition at line 10534 of file maglev-ir.h.
Referenced by CallKnownJSFunction().
kFixedInputCount
constexpr int v8::internal::maglev::CallKnownJSFunction::kFixedInputCount = 4 [static], [constexpr]
Definition at line 10537 of file maglev-ir.h.
kNewTargetIndex
constexpr int v8::internal::maglev::CallKnownJSFunction::kNewTargetIndex = 3 [static], [constexpr]
Definition at line 10536 of file maglev-ir.h.
Referenced by CallKnownJSFunction().
kProperties
constexpr OpProperties v8::internal::maglev::CallKnownJSFunction::kProperties = OpProperties::JSCall() [static], [constexpr]
Definition at line 10553 of file maglev-ir.h.
kReceiverIndex
constexpr int v8::internal::maglev::CallKnownJSFunction::kReceiverIndex = 2 [static], [constexpr]
Definition at line 10535 of file maglev-ir.h.
Referenced by CallKnownJSFunction().
shared_function_info_
const compiler::SharedFunctionInfoRef v8::internal::maglev::CallKnownJSFunction::shared_function_info_ [private]
Definition at line 10593 of file maglev-ir.h.
Referenced by PrintParams().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir-inl.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc