v8::internal::compiler::LiveRange Class Reference
#include <register-allocator.h>
Public Member Functions
LiveRange (const LiveRange &)=delete
LiveRange & operator= (const LiveRange &)=delete
const UseIntervalVector & intervals () const
base::Vector< UsePosition * > positions () const
TopLevelLiveRange * TopLevel ()
const TopLevelLiveRange * TopLevel () const
bool IsTopLevel () const
LiveRange * next () const
int relative_id () const
bool IsEmpty () const
InstructionOperand GetAssignedOperand () const
MachineRepresentation representation () const
int assigned_register () const
bool HasRegisterAssigned () const
void set_assigned_register (int reg)
void UnsetAssignedRegister ()
bool ShouldRecombine () const
void SetRecombine ()
void set_controlflow_hint (int reg)
int controlflow_hint () const
bool RegisterFromControlFlow (int *reg)
bool spilled () const
void AttachToNext (Zone *zone)
void Unspill ()
void Spill ()
RegisterKind kind () const
UsePosition *const * NextUsePosition (LifetimePosition start) const
UsePosition * NextRegisterPosition (LifetimePosition start) const
UsePosition * NextUsePositionRegisterIsBeneficial (LifetimePosition start) const
LifetimePosition NextLifetimePositionRegisterIsBeneficial (const LifetimePosition &start) const
UsePosition * NextUsePositionSpillDetrimental (LifetimePosition start) const
bool CanBeSpilled (LifetimePosition pos) const
LiveRange * SplitAt (LifetimePosition position, Zone *zone)
bool RegisterFromFirstHint (int *register_index)
UsePosition * current_hint_position () const
LifetimePosition Start () const
LifetimePosition End () const
bool ShouldBeAllocatedBefore (const LiveRange *other) const
bool CanCover (LifetimePosition position) const
bool Covers (LifetimePosition position)
LifetimePosition NextStartAfter (LifetimePosition position)
LifetimePosition NextEndAfter (LifetimePosition position)
LifetimePosition FirstIntersection (LiveRange *other)
LifetimePosition NextStart () const
void ConvertUsesToOperand (const InstructionOperand &op, const InstructionOperand &spill_op)
void SetUseHints (int register_index)
void UnsetUseHints ()
void ResetCurrentHintPosition ()
void Print (const RegisterConfiguration *config, bool with_children) const
void Print (bool with_children) const
bool RegisterFromBundle (int *hint) const
void UpdateBundleRegister (int reg) const
Private Types
using SpilledField = base::BitField< bool, 0, 1 >
using AssignedRegisterField = base::BitField< int32_t, 7, 6 >
using RepresentationField = base::BitField< MachineRepresentation, 13, 8 >
using RecombineField = base::BitField< bool, 21, 1 >
using ControlFlowRegisterHint = base::BitField< uint8_t, 22, 6 >
Private Member Functions
LiveRange (int relative_id, MachineRepresentation rep, TopLevelLiveRange *top_level)
void set_spilled (bool value)
UseIntervalVector::iterator FirstSearchIntervalForPosition (LifetimePosition position)
void AdvanceLastProcessedMarker (UseIntervalVector::iterator to_start_of, LifetimePosition but_not_past)
Private Attributes
friend Zone
int relative_id_
uint32_t bits_
UseIntervalVector intervals_
base::Vector< UsePosition * > positions_span_
TopLevelLiveRange * top_level_
LiveRange * next_
UseIntervalVector::iterator current_interval_
size_t current_hint_position_index_ = 0
LifetimePosition next_start_
LifetimePosition start_
LifetimePosition end_
Friends
class TopLevelLiveRange
Detailed Description
Definition at line 780 of file register-allocator.h.
Member Typedef Documentation
AssignedRegisterField
using v8::internal::compiler::LiveRange::AssignedRegisterField = base::BitField<int32_t, 7, 6> [private]
Definition at line 937 of file register-allocator.h.
ControlFlowRegisterHint
using v8::internal::compiler::LiveRange::ControlFlowRegisterHint = base::BitField<uint8_t, 22, 6> [private]
Definition at line 940 of file register-allocator.h.
RecombineField
using v8::internal::compiler::LiveRange::RecombineField = base::BitField<bool, 21, 1> [private]
Definition at line 939 of file register-allocator.h.
RepresentationField
using v8::internal::compiler::LiveRange::RepresentationField = base::BitField<MachineRepresentation, 13, 8> [private]
Definition at line 938 of file register-allocator.h.
SpilledField
using v8::internal::compiler::LiveRange::SpilledField = base::BitField<bool, 0, 1> [private]
Definition at line 935 of file register-allocator.h.
Constructor & Destructor Documentation
LiveRange() [1/2]
v8::internal::compiler::LiveRange::LiveRange (const LiveRange &) [delete]
LiveRange() [2/2]
v8::internal::compiler::LiveRange::LiveRange (int relative_id, MachineRepresentation rep, TopLevelLiveRange * top_level) [explicit], [private]
Definition at line 179 of file register-allocator.cc.
    : relative_id_(relative_id),
      bits_(0),
      intervals_(),
      positions_span_(),
      top_level_(top_level),
      next_(nullptr),
      current_interval_(intervals_.begin()) {
  DCHECK(AllocatedOperand::IsSupportedRepresentation(rep));
  bits_ = AssignedRegisterField::encode(kUnassignedRegister) |
          RepresentationField::encode(rep) |
          ControlFlowRegisterHint::encode(kUnassignedRegister);
}
References bits_, v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::LocationOperand::IsSupportedRepresentation(), and v8::internal::compiler::kUnassignedRegister.
Member Function Documentation
AdvanceLastProcessedMarker()
void v8::internal::compiler::LiveRange::AdvanceLastProcessedMarker (UseIntervalVector::iterator to_start_of, LifetimePosition but_not_past) [private]
Definition at line 403 of file register-allocator.cc.
                                                                          {
  DCHECK_LE(intervals_.begin(), to_start_of);
  DCHECK_LT(to_start_of, intervals_.end());
  DCHECK_NE(current_interval_, intervals_.end());
  if (to_start_of->start() > but_not_past) return;
  if (to_start_of->start() > current_interval_->start()) {
    current_interval_ = to_start_of;
  }
}
References v8::internal::compiler::DoubleEndedSplitVector< T >::begin(), current_interval_, DCHECK_LE, DCHECK_LT, DCHECK_NE, v8::internal::compiler::DoubleEndedSplitVector< T >::end(), intervals_, and v8::internal::compiler::UseInterval::start().
Referenced by Covers(), and FirstIntersection().
assigned_register()
int v8::internal::compiler::LiveRange::assigned_register () const [inline]
Definition at line 805 of file register-allocator.h.
{ return AssignedRegisterField::decode(bits_); }
Referenced by v8::internal::compiler::LinearScanAllocator::ActiveToInactive(), v8::internal::compiler::LinearScanAllocator::AddToActive(), v8::internal::compiler::LinearScanAllocator::AddToInactive(), v8::internal::compiler::LinearScanAllocator::ComputeStateFromManyPredecessors(), GetAssignedOperand(), v8::internal::compiler::LinearScanAllocator::InactiveToActive(), v8::internal::compiler::LinearScanAllocator::InactiveToHandled(), v8::internal::compiler::LinearScanAllocator::SpillNotLiveRanges(), v8::internal::compiler::LinearScanAllocator::SplitAndSpillIntersecting(), and v8::internal::compiler::LinearScanAllocator::UpdateDeferredFixedRanges().
AttachToNext()
void v8::internal::compiler::LiveRange::AttachToNext (Zone * zone)
Definition at line 239 of file register-allocator.cc.
                                       {
  DCHECK_NOT_NULL(next_);
  // Update cache for `TopLevelLiveRange::GetChildCovers()`.
  auto& children = TopLevel()->children_;
  children.erase(std::lower_bound(children.begin(), children.end(), next_,
                                  LiveRangeOrdering()));
  // Merge use intervals.
  intervals_.Append(zone, next_->intervals_);
  // `start_` doesn't change.
  end_ = next_->end_;
  // Merge use positions.
  CHECK_EQ(positions_span_.end(), next_->positions_span_.begin());
  positions_span_ =
      base::VectorOf(positions_span_.begin(),
                     positions_span_.size() + next_->positions_span_.size());
  // Join linked lists of live ranges.
  LiveRange* old_next = next_;
  next_ = next_->next_;
  old_next->next_ = nullptr;
}
References v8::internal::compiler::DoubleEndedSplitVector< T >::Append(), CHECK_EQ, v8::internal::compiler::TopLevelLiveRange::children_, DCHECK_NOT_NULL, end_, intervals_, next_, positions_span_, TopLevel(), and v8::base::VectorOf().
Referenced by v8::internal::compiler::LinearScanAllocator::MaybeUndoPreviousSplit().
CanBeSpilled()
bool v8::internal::compiler::LiveRange::CanBeSpilled (LifetimePosition pos) const
Definition at line 363 of file register-allocator.cc.
                                                       {
  // We cannot spill a live range that has a use requiring a register
  // at the current or the immediate next position.
  UsePosition* use_pos = NextRegisterPosition(pos);
  if (use_pos == nullptr) return true;
  return use_pos->pos() > pos.NextStart().End();
}
References v8::internal::compiler::LifetimePosition::End(), NextRegisterPosition(), v8::internal::compiler::LifetimePosition::NextStart(), and v8::internal::compiler::UsePosition::pos().
CanCover()
bool v8::internal::compiler::LiveRange::CanCover (LifetimePosition position) const
Definition at line 571 of file register-allocator.cc.
                                                        {
  if (IsEmpty()) return false;
  return Start() <= position && position < End();
}
References End(), IsEmpty(), and Start().
Referenced by Covers(), and v8::internal::compiler::LiveRangeConnector::ResolveControlFlow().
controlflow_hint()
int v8::internal::compiler::LiveRange::controlflow_hint () const [inline]
Definition at line 818 of file register-allocator.h.
                               {
    return ControlFlowRegisterHint::decode(bits_);
  }
Referenced by ShouldBeAllocatedBefore(), and v8::internal::compiler::LinearScanAllocator::SpillBetweenUntil().
ConvertUsesToOperand()
void v8::internal::compiler::LiveRange::ConvertUsesToOperand (const InstructionOperand & op, const InstructionOperand & spill_op)
Definition at line 499 of file register-allocator.cc.
                                                                         {
  for (UsePosition* pos : positions_span_) {
    DCHECK(Start() <= pos->pos() && pos->pos() <= End());
    if (!pos->HasOperand()) continue;
    switch (pos->type()) {
      case UsePositionType::kRequiresSlot:
        DCHECK(spill_op.IsStackSlot() || spill_op.IsFPStackSlot());
        InstructionOperand::ReplaceWith(pos->operand(), &spill_op);
        break;
      case UsePositionType::kRequiresRegister:
        DCHECK(op.IsRegister() || op.IsFPRegister());
        [[fallthrough]];
      case UsePositionType::kRegisterOrSlot:
      case UsePositionType::kRegisterOrSlotOrConstant:
        InstructionOperand::ReplaceWith(pos->operand(), &op);
        break;
    }
  }
}
References v8::internal::DCHECK(), End(), v8::internal::compiler::InstructionOperand::IsFPRegister(), v8::internal::compiler::InstructionOperand::IsFPStackSlot(), v8::internal::compiler::InstructionOperand::IsRegister(), v8::internal::compiler::InstructionOperand::IsStackSlot(), v8::internal::compiler::kRegisterOrSlot, v8::internal::compiler::kRegisterOrSlotOrConstant, v8::internal::compiler::kRequiresRegister, v8::internal::compiler::kRequiresSlot, positions_span_, v8::internal::compiler::InstructionOperand::ReplaceWith(), and Start().
Covers()
bool v8::internal::compiler::LiveRange::Covers (LifetimePosition position)
Definition at line 576 of file register-allocator.cc.
                                                {
  if (!CanCover(position)) return false;
  bool covers = false;
  UseIntervalVector::iterator interval =
      FirstSearchIntervalForPosition(position);
  while (interval != intervals().end() && interval->start() <= position) {
    // The list of `UseInterval`s shall be sorted.
    DCHECK(interval + 1 == intervals().end() ||
           interval[1].start() >= interval->start());
    if (interval->Contains(position)) {
      covers = true;
      break;
    }
    ++interval;
  }
  if (!covers && interval > intervals_.begin()) {
    // To ensure that we advance {current_interval_} below, move back to the
    // last interval starting before position.
    interval--;
    DCHECK_LE(interval->start(), position);
  }
  AdvanceLastProcessedMarker(interval, position);
  return covers;
}
References AdvanceLastProcessedMarker(), v8::internal::compiler::DoubleEndedSplitVector< T >::begin(), CanCover(), v8::internal::compiler::UseInterval::Contains(), v8::internal::DCHECK(), DCHECK_LE, v8::internal::compiler::end(), FirstSearchIntervalForPosition(), intervals(), intervals_, and v8::internal::compiler::UseInterval::start().
Referenced by v8::internal::compiler::LinearScanAllocator::ForwardStateTo(), v8::internal::compiler::LinearScanAllocator::MaybeSpillPreviousRanges(), and v8::internal::compiler::ReferenceMapPopulator::PopulateReferenceMaps().
current_hint_position()
UsePosition* v8::internal::compiler::LiveRange::current_hint_position () const [inline]
Definition at line 873 of file register-allocator.h.
                                             {
    return positions_span_[current_hint_position_index_];
  }
Referenced by v8::internal::compiler::LiveRangeBuilder::ProcessInstructions().
End()
LifetimePosition v8::internal::compiler::LiveRange::End () const [inline]
Definition at line 883 of file register-allocator.h.
                               {
    DCHECK(!IsEmpty());
    DCHECK_EQ(end_, intervals_.back().end());
    return end_;
  }
References v8::internal::DCHECK(), and DCHECK_EQ.
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateBlockedReg(), v8::internal::compiler::LinearScanAllocator::AssignRegisterOnReload(), CanCover(), v8::internal::compiler::LiveRangeConnector::ConnectRanges(), ConvertUsesToOperand(), v8::internal::compiler::LinearScanAllocator::FindFreeRegistersForRange(), FirstIntersection(), v8::internal::compiler::LinearScanAllocator::ForwardStateTo(), v8::internal::compiler::RegisterAllocator::GetSplitPositionForInstruction(), v8::internal::compiler::LinearScanAllocator::MaybeSpillPreviousRanges(), NextLifetimePositionRegisterIsBeneficial(), RegisterFromFirstHint(), v8::internal::compiler::LiveRangeConnector::ResolveControlFlow(), v8::internal::compiler::LinearScanAllocator::SplitAndSpillIntersecting(), SplitAt(), v8::internal::compiler::LinearScanAllocator::TryAllocateFreeReg(), v8::internal::compiler::LinearScanAllocator::TryAllocatePreferredReg(), and v8::internal::compiler::LinearScanAllocator::UpdateDeferredFixedRanges().
FirstIntersection()
LifetimePosition v8::internal::compiler::LiveRange::FirstIntersection (LiveRange * other)
Definition at line 624 of file register-allocator.cc.
                                                              {
  if (IsEmpty() || other->IsEmpty() || other->Start() > End() ||
      Start() > other->End())
    return LifetimePosition::Invalid();
  LifetimePosition min_end = std::min(End(), other->End());
  UseIntervalVector::iterator b = other->intervals_.begin();
  LifetimePosition advance_last_processed_up_to = b->start();
  UseIntervalVector::iterator a = FirstSearchIntervalForPosition(b->start());
  while (a != intervals().end() && b != other->intervals().end()) {
    if (a->start() > min_end || b->start() > min_end) break;
    LifetimePosition cur_intersection = a->Intersect(*b);
    if (cur_intersection.IsValid()) {
      return cur_intersection;
    }
    if (a->start() < b->start()) {
      ++a;
      if (a == intervals().end() || a->start() > other->End()) break;
      AdvanceLastProcessedMarker(a, advance_last_processed_up_to);
    } else {
      ++b;
    }
  }
  return LifetimePosition::Invalid();
}
References AdvanceLastProcessedMarker(), v8::internal::compiler::DoubleEndedSplitVector< T >::begin(), v8::internal::compiler::DoubleEndedSplitVector< T >::end(), End(), v8::internal::compiler::end(), FirstSearchIntervalForPosition(), v8::internal::compiler::UseInterval::Intersect(), intervals(), intervals_, v8::internal::compiler::LifetimePosition::Invalid(), IsEmpty(), v8::internal::compiler::LifetimePosition::IsValid(), v8::internal::compiler::UseInterval::start(), and Start().
Referenced by v8::internal::compiler::LinearScanAllocator::SplitAndSpillIntersecting(), and v8::internal::compiler::LinearScanAllocator::UpdateDeferredFixedRanges().
FirstSearchIntervalForPosition()
UseIntervalVector::iterator v8::internal::compiler::LiveRange::FirstSearchIntervalForPosition (LifetimePosition position) [private]
Definition at line 390 of file register-allocator.cc.
                               {
  DCHECK_NE(current_interval_, intervals_.end());
  if (current_interval_->start() > position) {
    current_interval_ = std::lower_bound(
        intervals_.begin(), intervals_.end(), position,
        [](const UseInterval& interval, LifetimePosition position) {
          return interval.end() < position;
        });
  }
  return current_interval_;
}
References v8::internal::compiler::DoubleEndedSplitVector< T >::begin(), current_interval_, DCHECK_NE, v8::internal::compiler::DoubleEndedSplitVector< T >::end(), intervals_, and v8::internal::compiler::UseInterval::start().
Referenced by Covers(), FirstIntersection(), NextEndAfter(), and NextStartAfter().
GetAssignedOperand()
InstructionOperand v8::internal::compiler::LiveRange::GetAssignedOperand () const
Definition at line 373 of file register-allocator.cc.
                                                       {
  DCHECK(!IsEmpty());
  if (HasRegisterAssigned()) {
    DCHECK(!spilled());
    return AllocatedOperand(LocationOperand::REGISTER, representation(),
                            assigned_register());
  }
  DCHECK(spilled());
  DCHECK(!HasRegisterAssigned());
  if (TopLevel()->HasSpillOperand()) {
    InstructionOperand* op = TopLevel()->GetSpillOperand();
    DCHECK(!op->IsUnallocated());
    return *op;
  }
  return TopLevel()->GetSpillRangeOperand();
}
References assigned_register(), v8::internal::DCHECK(), v8::internal::compiler::TopLevelLiveRange::GetSpillOperand(), v8::internal::compiler::TopLevelLiveRange::GetSpillRangeOperand(), HasRegisterAssigned(), IsEmpty(), v8::internal::compiler::LocationOperand::REGISTER, representation(), spilled(), and TopLevel().
Referenced by v8::internal::compiler::SpillPlacer::CommitSpill(), v8::internal::compiler::LiveRangeConnector::CommitSpillsInDeferredBlocks(), v8::internal::compiler::LiveRangeConnector::ConnectRanges(), v8::internal::compiler::operator<<(), v8::internal::compiler::ReferenceMapPopulator::PopulateReferenceMaps(), v8::internal::compiler::GraphC1Visualizer::PrintLiveRange(), and v8::internal::compiler::LiveRangeConnector::ResolveControlFlow().
HasRegisterAssigned()
bool v8::internal::compiler::LiveRange::HasRegisterAssigned () const [inline]
Definition at line 806 of file register-allocator.h.
                                   {
    return assigned_register() != kUnassignedRegister;
  }
References v8::internal::compiler::kUnassignedRegister.
Referenced by v8::internal::compiler::LinearScanAllocator::ActiveToInactive(), v8::internal::compiler::LinearScanAllocator::AddToInactive(), v8::internal::compiler::LinearScanAllocator::AddToUnhandled(), v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), GetAssignedOperand(), v8::internal::compiler::operator<<(), v8::internal::compiler::GraphC1Visualizer::PrintLiveRange(), v8::internal::compiler::LinearScanAllocator::ProcessCurrentRange(), v8::internal::compiler::LinearScanAllocator::ReloadLiveRanges(), set_assigned_register(), v8::internal::compiler::LinearScanAllocator::SplitAndSpillIntersecting(), and UnsetAssignedRegister().
intervals()
const UseIntervalVector& v8::internal::compiler::LiveRange::intervals () const [inline]
Definition at line 785 of file register-allocator.h.
{ return intervals_; }
Referenced by v8::internal::compiler::LiveRangeBundle::AddRange(), Covers(), FirstIntersection(), NextEndAfter(), NextStartAfter(), v8::internal::compiler::operator<<(), v8::internal::compiler::GraphC1Visualizer::PrintLiveRange(), and v8::internal::compiler::LiveRangeBundle::TryAddRange().
IsEmpty()
bool v8::internal::compiler::LiveRange::IsEmpty () const [inline]
Definition at line 797 of file register-allocator.h.
{ return intervals_.empty(); }
Referenced by v8::internal::compiler::LinearScanAllocator::AddToUnhandled(), CanCover(), v8::internal::compiler::RegisterAllocator::CanProcessRange(), v8::internal::compiler::LiveRangeBuilder::Define(), v8::internal::compiler::TopLevelLiveRange::EnsureInterval(), FirstIntersection(), GetAssignedOperand(), v8::internal::compiler::operator<<(), v8::internal::compiler::GraphC1Visualizer::PrintLiveRange(), v8::internal::compiler::GraphC1Visualizer::PrintLiveRangeChain(), v8::internal::compiler::TopLevelLiveRange::ShortenTo(), and v8::internal::compiler::SpillRange::SpillRange().
IsTopLevel()
bool v8::internal::compiler::LiveRange::IsTopLevel () const
Definition at line 371 of file register-allocator.cc.
{ return top_level_ == this; }
References top_level_.
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), and v8::internal::compiler::LinearScanAllocator::SetLiveRangeAssignedRegister().
kind()
RegisterKind v8::internal::compiler::LiveRange::kind () const
Definition at line 277 of file register-allocator.cc.
                                   {
  if (kFPAliasing == AliasingKind::kIndependent &&
      IsSimd128(representation())) {
    return RegisterKind::kSimd128;
  } else {
    return IsFloatingPoint(representation()) ? RegisterKind::kDouble
                                             : RegisterKind::kGeneral;
  }
}
References v8::internal::IsFloatingPoint(), v8::internal::IsSimd128(), v8::internal::compiler::kDouble, v8::internal::kFPAliasing, v8::internal::compiler::kGeneral, v8::internal::kIndependent, v8::internal::compiler::kSimd128, and representation().
Referenced by v8::internal::compiler::RegisterAllocator::CanProcessRange().
next()
LiveRange* v8::internal::compiler::LiveRange::next () const [inline]
Definition at line 793 of file register-allocator.h.
{ return next_; }
Referenced by v8::internal::compiler::SpillPlacer::Add(), v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), v8::internal::compiler::OperandAssigner::CommitAssignment(), v8::internal::compiler::LiveRangeConnector::CommitSpillsInDeferredBlocks(), v8::internal::compiler::LiveRangeConnector::ConnectRanges(), v8::internal::compiler::TopLevelLiveRange::GetChildCovers(), v8::internal::compiler::LinearScanAllocator::MaybeSpillPreviousRanges(), v8::internal::compiler::LinearScanAllocator::MaybeUndoPreviousSplit(), v8::internal::compiler::operator<<(), v8::internal::compiler::ReferenceMapPopulator::PopulateReferenceMaps(), v8::internal::compiler::GraphC1Visualizer::PrintLiveRangeChain(), v8::internal::compiler::LinearScanAllocator::PrintRangeRow(), v8::internal::compiler::LiveRangeConnector::ResolveControlFlow(), and v8::internal::compiler::SpillRange::SpillRange().
NextEndAfter()
LifetimePosition v8::internal::compiler::LiveRange::NextEndAfter (LifetimePosition position)
Definition at line 601 of file register-allocator.cc.
                                                                  {
  // NOTE: A binary search was measured to be slower, e.g., on the binary from
  // https://crbug.com/v8/9529.
  UseIntervalVector::iterator interval = std::find_if(
      FirstSearchIntervalForPosition(position), intervals_.end(),
      [=](const UseInterval& interval) { return interval.end() >= position; });
  DCHECK_NE(interval, intervals().end());
  return interval->end();
}
References DCHECK_NE, v8::internal::compiler::DoubleEndedSplitVector< T >::end(), v8::internal::compiler::UseInterval::end(), v8::internal::compiler::end(), FirstSearchIntervalForPosition(), intervals(), and intervals_.
Referenced by v8::internal::compiler::LinearScanAllocator::AddToActive(), v8::internal::compiler::LinearScanAllocator::ForwardStateTo(), and v8::internal::compiler::LinearScanAllocator::InactiveToActive().
NextLifetimePositionRegisterIsBeneficial()
LifetimePosition v8::internal::compiler::LiveRange::NextLifetimePositionRegisterIsBeneficial (const LifetimePosition & start) const
Definition at line 336 of file register-allocator.cc.
                                         {
  UsePosition* next_use = NextUsePositionRegisterIsBeneficial(start);
  if (next_use == nullptr) return End();
  return next_use->pos();
}
References End(), NextUsePositionRegisterIsBeneficial(), and v8::internal::compiler::UsePosition::pos().
NextRegisterPosition()
UsePosition * v8::internal::compiler::LiveRange::NextRegisterPosition (LifetimePosition start) const
Definition at line 354 of file register-allocator.cc.
                                                                         {
  UsePosition* const* use_pos_it =
      std::find_if(NextUsePosition(start), positions_span_.cend(),
                   [](const UsePosition* pos) {
                     return pos->type() == UsePositionType::kRequiresRegister;
                   });
  return use_pos_it == positions_span_.cend() ? nullptr : *use_pos_it;
}
References NextUsePosition(), nullptr, and positions_span_.
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateBlockedReg(), CanBeSpilled(), and v8::internal::compiler::LinearScanAllocator::SplitAndSpillIntersecting().
NextStart()
LifetimePosition v8::internal::compiler::LiveRange::NextStart () const [inline]
Definition at line 895 of file register-allocator.h.
{ return next_start_; }
Referenced by v8::internal::compiler::LinearScanAllocator::InactiveLiveRangeOrdering::operator()().
NextStartAfter()
LifetimePosition v8::internal::compiler::LiveRange::NextStartAfter (LifetimePosition position)
Definition at line 611 of file register-allocator.cc.
                                                                    {
  // NOTE: A binary search was measured to be slower, e.g., on the binary from
  // https://crbug.com/v8/9529.
  UseIntervalVector::iterator interval =
      std::find_if(FirstSearchIntervalForPosition(position), intervals_.end(),
                   [=](const UseInterval& interval) {
                     return interval.start() >= position;
                   });
  DCHECK_NE(interval, intervals().end());
  next_start_ = interval->start();
  return next_start_;
}
References DCHECK_NE, v8::internal::compiler::DoubleEndedSplitVector< T >::end(), v8::internal::compiler::end(), FirstSearchIntervalForPosition(), intervals(), intervals_, next_start_, and v8::internal::compiler::UseInterval::start().
Referenced by v8::internal::compiler::LinearScanAllocator::ActiveToInactive(), v8::internal::compiler::LinearScanAllocator::AddToInactive(), and v8::internal::compiler::LinearScanAllocator::ForwardStateTo().
NextUsePosition()
UsePosition *const * v8::internal::compiler::LiveRange::NextUsePosition (LifetimePosition start) const
Definition at line 321 of file register-allocator.cc.
                                                                           {
  return std::lower_bound(positions_span_.cbegin(), positions_span_.cend(),
                          start, [](UsePosition* use, LifetimePosition start) {
                            return use->pos() < start;
                          });
}
References positions_span_, and use().
Referenced by NextRegisterPosition(), NextUsePositionRegisterIsBeneficial(), NextUsePositionSpillDetrimental(), and v8::internal::compiler::LiveRangeConnector::ResolveControlFlow().
NextUsePositionRegisterIsBeneficial()
UsePosition * v8::internal::compiler::LiveRange::NextUsePositionRegisterIsBeneficial (LifetimePosition start) const
Definition at line 328 of file register-allocator.cc.
                                  {
  UsePosition* const* use_pos_it = std::find_if(
      NextUsePosition(start), positions_span_.cend(),
      [](const UsePosition* pos) { return pos->RegisterIsBeneficial(); });
  return use_pos_it == positions_span_.cend() ? nullptr : *use_pos_it;
}
References NextUsePosition(), nullptr, and positions_span_.
Referenced by NextLifetimePositionRegisterIsBeneficial(), v8::internal::compiler::RegisterAllocator::SplitAndSpillRangesDefinedByMemoryOperand(), and v8::internal::compiler::LinearScanAllocator::TryReuseSpillForPhi().
NextUsePositionSpillDetrimental()
UsePosition * v8::internal::compiler::LiveRange::NextUsePositionSpillDetrimental (LifetimePosition start) const
Definition at line 343 of file register-allocator.cc.
                                  {
  UsePosition* const* use_pos_it =
      std::find_if(NextUsePosition(start), positions_span_.cend(),
                   [](const UsePosition* pos) {
                     return pos->type() == UsePositionType::kRequiresRegister ||
                            pos->SpillDetrimental();
                   });
  return use_pos_it == positions_span_.cend() ? nullptr : *use_pos_it;
}
References NextUsePosition(), nullptr, and positions_span_.
operator=()
LiveRange& v8::internal::compiler::LiveRange::operator= (const LiveRange &) [delete]
positions()
base::Vector<UsePosition*> v8::internal::compiler::LiveRange::positions () const [inline]
Definition at line 786 of file register-allocator.h.
{ return positions_span_; }
Referenced by v8::internal::compiler::RegisterAllocationData::ExistsUseWithoutDefinition(), v8::internal::compiler::operator<<(), v8::internal::compiler::GraphC1Visualizer::PrintLiveRange(), and v8::internal::compiler::LiveRangeConnector::ResolveControlFlow().
Print() [1/2]
void v8::internal::compiler::LiveRange::Print (bool with_children) const
Definition at line 662 of file register-allocator.cc.
                                              {
  Print(RegisterConfiguration::Default(), with_children);
}
References v8::internal::RegisterConfiguration::Default(), and Print().
Print() [2/2]
void v8::internal::compiler::LiveRange::Print (const RegisterConfiguration * config, bool with_children) const
Definition at line 650 of file register-allocator.cc.
                                                {
  StdoutStream os;
  PrintableLiveRange wrapper;
  wrapper.register_configuration_ = config;
  for (const LiveRange* i = this; i != nullptr; i = i->next()) {
    wrapper.range_ = i;
    os << wrapper << std::endl;
    if (!with_children) break;
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::PrintableLiveRange::range_, and v8::internal::compiler::PrintableLiveRange::register_configuration_.
Referenced by Print().
RegisterFromBundle()
bool v8::internal::compiler::LiveRange::RegisterFromBundle (int * hint) const
Definition at line 666 of file register-allocator.cc.
                                                  {
  LiveRangeBundle* bundle = TopLevel()->get_bundle();
  if (bundle == nullptr || bundle->reg() == kUnassignedRegister) return false;
  *hint = bundle->reg();
  return true;
}
References v8::internal::compiler::TopLevelLiveRange::get_bundle(), v8::internal::compiler::kUnassignedRegister, v8::internal::compiler::LiveRangeBundle::reg(), and TopLevel().
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateBlockedReg(), v8::internal::compiler::LinearScanAllocator::TryAllocateFreeReg(), and v8::internal::compiler::LinearScanAllocator::TryAllocatePreferredReg().
RegisterFromControlFlow()
bool v8::internal::compiler::LiveRange::RegisterFromControlFlow (int * reg) [inline]
Definition at line 821 of file register-allocator.h.
                                         {
    int hint = controlflow_hint();
    if (hint != kUnassignedRegister) {
      *reg = hint;
      return true;
    }
    return false;
  }
References v8::internal::compiler::kUnassignedRegister.
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateBlockedReg(), v8::internal::compiler::LinearScanAllocator::TryAllocateFreeReg(), and v8::internal::compiler::LinearScanAllocator::TryAllocatePreferredReg().
RegisterFromFirstHint()
bool v8::internal::compiler::LiveRange::RegisterFromFirstHint (int * register_index)
Definition at line 287 of file register-allocator.cc.
                                                         {
  DCHECK_LE(current_hint_position_index_, positions_span_.size());
  if (current_hint_position_index_ == positions_span_.size()) {
    return false;
  }
  DCHECK_GE(positions_span_[current_hint_position_index_]->pos(),
            positions_span_.first()->pos());
  DCHECK_LE(positions_span_[current_hint_position_index_]->pos(), End());
  bool needs_revisit = false;
  UsePosition** pos_it = positions_span_.begin() + current_hint_position_index_;
  for (; pos_it != positions_span_.end(); ++pos_it) {
    if ((*pos_it)->HintRegister(register_index)) {
      break;
    }
    // Phi and use position hints can be assigned during allocation which
    // would invalidate the cached hint position. Make sure we revisit them.
    needs_revisit = needs_revisit ||
                    (*pos_it)->hint_type() == UsePositionHintType::kPhi ||
                    (*pos_it)->hint_type() == UsePositionHintType::kUsePos;
  }
  if (!needs_revisit) {
    current_hint_position_index_ =
        std::distance(positions_span_.begin(), pos_it);
  }
#ifdef DEBUG
  UsePosition** pos_check_it =
      std::find_if(positions_span_.begin(), positions_span_.end(),
                   [](UsePosition* pos) { return pos->HasHint(); });
  CHECK_EQ(pos_it, pos_check_it);
#endif
  return pos_it != positions_span_.end();
}
References CHECK_EQ, current_hint_position_index_, DCHECK_GE, DCHECK_LE, End(), v8::internal::compiler::kPhi, v8::internal::compiler::kUsePos, and positions_span_.
Referenced by v8::internal::compiler::LinearScanAllocator::TryAllocateFreeReg(), and v8::internal::compiler::LinearScanAllocator::TryAllocatePreferredReg().
relative_id()
int v8::internal::compiler::LiveRange::relative_id () const [inline]
Definition at line 795 of file register-allocator.h.
{ return relative_id_; }
Referenced by v8::internal::compiler::LinearScanAllocator::ActiveToInactive(), v8::internal::compiler::LinearScanAllocator::AddToActive(), v8::internal::compiler::LinearScanAllocator::AddToInactive(), v8::internal::compiler::LinearScanAllocator::AddToUnhandled(), v8::internal::compiler::LinearScanAllocator::AllocateBlockedReg(), v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), v8::internal::compiler::LinearScanAllocator::AssignRegisterOnReload(), v8::internal::compiler::BundleBuilder::BuildBundles(), v8::internal::compiler::LinearScanAllocator::InactiveToActive(), v8::internal::compiler::LinearScanAllocator::InactiveToHandled(), v8::internal::compiler::LinearScanAllocator::MaybeUndoPreviousSplit(), v8::internal::compiler::operator<<(), v8::internal::compiler::ReferenceMapPopulator::PopulateReferenceMaps(), v8::internal::compiler::GraphC1Visualizer::PrintLiveRange(), v8::internal::compiler::LinearScanAllocator::ReloadLiveRanges(), v8::internal::compiler::RegisterAllocator::Spill(), v8::internal::compiler::LinearScanAllocator::SpillBetweenUntil(), v8::internal::compiler::LinearScanAllocator::SpillNotLiveRanges(), v8::internal::compiler::RegisterAllocator::SplitAndSpillRangesDefinedByMemoryOperand(), v8::internal::compiler::RegisterAllocator::SplitBetween(), v8::internal::compiler::RegisterAllocator::SplitRangeAt(), v8::internal::compiler::LinearScanAllocator::TryAllocateFreeReg(), and v8::internal::compiler::LinearScanAllocator::TryAllocatePreferredReg().
representation()
MachineRepresentation v8::internal::compiler::LiveRange::representation () const [inline]
Definition at line 801 of file register-allocator.h.
                                               {
    return RepresentationField::decode(bits_);
  }
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateBlockedReg(), v8::internal::compiler::LinearScanAllocator::AssignRegisterOnReload(), v8::internal::compiler::LinearScanAllocator::FindFreeRegistersForRange(), GetAssignedOperand(), v8::internal::compiler::TopLevelLiveRange::GetSpillRangeOperand(), kind(), v8::internal::compiler::ConstraintBuilder::MeetConstraintsBefore(), v8::internal::compiler::operator<<(), v8::internal::compiler::LinearScanAllocator::PickRegisterThatIsAvailableLongest(), v8::internal::compiler::GraphC1Visualizer::PrintLiveRange(), v8::internal::compiler::LinearScanAllocator::SetLiveRangeAssignedRegister(), v8::internal::compiler::LinearScanAllocator::SplitAndSpillIntersecting(), SplitAt(), and v8::internal::compiler::LinearScanAllocator::UpdateDeferredFixedRanges().
ResetCurrentHintPosition()
void v8::internal::compiler::LiveRange::ResetCurrentHintPosition () [inline]
Definition at line 908 of file register-allocator.h.
{ current_hint_position_index_ = 0; }
set_assigned_register()
void v8::internal::compiler::LiveRange::set_assigned_register (int reg)
Definition at line 229 of file register-allocator.cc.
                                             {
  DCHECK(!HasRegisterAssigned() && !spilled());
  bits_ = AssignedRegisterField::update(bits_, reg);
}
References bits_, v8::internal::DCHECK(), HasRegisterAssigned(), spilled(), and v8::base::BitField< T, shift, size, U >::update().
Referenced by v8::internal::compiler::LinearScanAllocator::SetLiveRangeAssignedRegister().
set_controlflow_hint()
void v8::internal::compiler::LiveRange::set_controlflow_hint (int reg) [inline]
Definition at line 815 of file register-allocator.h.
                                     {
    bits_ = ControlFlowRegisterHint::update(bits_, reg);
  }
Referenced by v8::internal::compiler::LinearScanAllocator::ReloadLiveRanges(), v8::internal::compiler::LinearScanAllocator::SpillBetweenUntil(), and v8::internal::compiler::LinearScanAllocator::UpdateDeferredFixedRanges().
set_spilled()
void v8::internal::compiler::LiveRange::set_spilled (bool value) [inline], [private]
Definition at line 923 of file register-allocator.h.
{ bits_ = SpilledField::update(bits_, value); }
References v8::internal::value.
Referenced by Spill(), and Unspill().
SetRecombine()
void v8::internal::compiler::LiveRange::SetRecombine () [inline]
Definition at line 814 of file register-allocator.h.
{ bits_ = RecombineField::update(bits_, true); }
Referenced by v8::internal::compiler::LinearScanAllocator::SpillNotLiveRanges().
SetUseHints()
void v8::internal::compiler::LiveRange::SetUseHints (int register_index)
Definition at line 556 of file register-allocator.cc.
                                              {
  for (UsePosition* pos : positions_span_) {
    if (!pos->HasOperand()) continue;
    switch (pos->type()) {
      case UsePositionType::kRequiresSlot:
        break;
      case UsePositionType::kRequiresRegister:
      case UsePositionType::kRegisterOrSlot:
      case UsePositionType::kRegisterOrSlotOrConstant:
        pos->set_assigned_register(register_index);
        break;
    }
  }
}
References v8::internal::compiler::kRegisterOrSlot, v8::internal::compiler::kRegisterOrSlotOrConstant, v8::internal::compiler::kRequiresRegister, v8::internal::compiler::kRequiresSlot, and positions_span_.
Referenced by v8::internal::compiler::LinearScanAllocator::SetLiveRangeAssignedRegister().
ShouldBeAllocatedBefore()
bool v8::internal::compiler::LiveRange::ShouldBeAllocatedBefore (const LiveRange * other) const
Definition at line 525 of file register-allocator.cc.
                                                                    {
  LifetimePosition start = Start();
  LifetimePosition other_start = other->Start();
  if (start == other_start) {
    // Prefer register that has a controlflow hint to make sure it gets
    // allocated first. This allows the control flow aware alloction to
    // just put ranges back into the queue without other ranges interfering.
    if (controlflow_hint() < other->controlflow_hint()) {
      return true;
    }
    // The other has a smaller hint.
    if (controlflow_hint() > other->controlflow_hint()) {
      return false;
    }
    // Both have the same hint or no hint at all. Use first use position.
    // To make the order total, handle the case where both positions are null.
    if (positions_span_.empty() && other->positions_span_.empty()) {
      return TopLevel()->vreg() < other->TopLevel()->vreg();
    }
    if (positions_span_.empty()) return false;
    if (other->positions_span_.empty()) return true;
    UsePosition* pos = positions_span_.first();
    UsePosition* other_pos = other->positions_span_.first();
    // To make the order total, handle the case where both positions are equal.
    if (pos->pos() == other_pos->pos())
      return TopLevel()->vreg() < other->TopLevel()->vreg();
    return pos->pos() < other_pos->pos();
  }
  return start < other_start;
}
References controlflow_hint(), v8::internal::compiler::UsePosition::pos(), positions_span_, Start(), TopLevel(), and v8::internal::compiler::TopLevelLiveRange::vreg().
Referenced by v8::internal::compiler::LinearScanAllocator::UnhandledLiveRangeOrdering::operator()().
ShouldRecombine()
bool v8::internal::compiler::LiveRange::ShouldRecombine () const [inline]
Definition at line 812 of file register-allocator.h.
{ return RecombineField::decode(bits_); }
Referenced by v8::internal::compiler::LinearScanAllocator::MaybeUndoPreviousSplit().
Spill()
void v8::internal::compiler::LiveRange::Spill ()
Definition at line 270 of file register-allocator.cc.
                      {
  DCHECK(!spilled());
  DCHECK(!TopLevel()->HasNoSpillType());
  set_spilled(true);
  bits_ = AssignedRegisterField::update(bits_, kUnassignedRegister);
}
References bits_, v8::internal::DCHECK(), v8::internal::compiler::kUnassignedRegister, set_spilled(), spilled(), TopLevel(), and v8::base::BitField< T, shift, size, U >::update().
Referenced by v8::internal::compiler::RegisterAllocator::Spill().
spilled()
bool v8::internal::compiler::LiveRange::spilled () const [inline]
Definition at line 829 of file register-allocator.h.
{ return SpilledField::decode(bits_); }
Referenced by v8::internal::compiler::SpillPlacer::Add(), v8::internal::compiler::LinearScanAllocator::AddToUnhandled(), v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), v8::internal::compiler::LiveRangeConnector::CommitSpillsInDeferredBlocks(), v8::internal::compiler::TopLevelLiveRange::FilterSpillMoves(), v8::internal::compiler::RegisterAllocator::FindOptimalSpillingPos(), GetAssignedOperand(), v8::internal::compiler::LinearScanAllocator::MaybeSpillPreviousRanges(), v8::internal::compiler::operator<<(), v8::internal::compiler::ReferenceMapPopulator::PopulateReferenceMaps(), v8::internal::compiler::GraphC1Visualizer::PrintLiveRange(), v8::internal::compiler::LinearScanAllocator::ReloadLiveRanges(), v8::internal::compiler::LiveRangeConnector::ResolveControlFlow(), set_assigned_register(), Spill(), v8::internal::compiler::RegisterAllocator::Spill(), v8::internal::compiler::LinearScanAllocator::TryReuseSpillForPhi(), UnsetAssignedRegister(), and Unspill().
SplitAt()
LiveRange * v8::internal::compiler::LiveRange::SplitAt (LifetimePosition position, Zone * zone)
Definition at line 414 of file register-allocator.cc.
                                                                   {
  DCHECK(Start() < position);
  DCHECK(End() > position);
  int new_id = TopLevel()->GetNextChildId();
  LiveRange* result =
      zone->New<LiveRange>(new_id, representation(), TopLevel());
  // Partition original use intervals to the two live ranges.
  // Find the first interval that ends after the position. (This either needs
  // to be split or completely belongs to the split-off LiveRange.)
  UseIntervalVector::iterator split_interval = std::upper_bound(
      intervals_.begin(), intervals_.end(), position,
      [](LifetimePosition position, const UseInterval& interval) {
        return position < interval.end();
      });
  DCHECK_NE(split_interval, intervals_.end());
  bool split_at_start = false;
  if (split_interval->start() == position) {
    split_at_start = true;
  } else if (split_interval->Contains(position)) {
    UseInterval new_interval = split_interval->SplitAt(position);
    split_interval = intervals_.insert(zone, split_interval + 1, new_interval);
  }
  result->intervals_ = intervals_.SplitAt(split_interval);
  DCHECK(!intervals_.empty());
  DCHECK(!result->intervals_.empty());
  result->start_ = result->intervals_.front().start();
  result->end_ = end_;
  end_ = intervals_.back().end();
  // Partition use positions.
  UsePosition** split_position_it;
  if (split_at_start) {
    // The split position coincides with the beginning of a use interval
    // (the end of a lifetime hole). Use at this position should be attributed
    // to the split child because split child owns use interval covering it.
    split_position_it = std::lower_bound(
        positions_span_.begin(), positions_span_.end(), position,
        [](const UsePosition* use_pos, LifetimePosition pos) {
          return use_pos->pos() < pos;
        });
  } else {
    split_position_it = std::lower_bound(
        positions_span_.begin(), positions_span_.end(), position,
        [](const UsePosition* use_pos, LifetimePosition pos) {
          return use_pos->pos() <= pos;
        });
  }
  size_t result_size = std::distance(split_position_it, positions_span_.end());
  result->positions_span_ = base::VectorOf(split_position_it, result_size);
  positions_span_.Truncate(positions_span_.size() - result_size);
  // Update or discard cached iteration state to make sure it does not point
  // to use positions and intervals that no longer belong to this live range.
  if (current_hint_position_index_ >= positions_span_.size()) {
    result->current_hint_position_index_ =
        current_hint_position_index_ - positions_span_.size();
    current_hint_position_index_ = 0;
  }
  current_interval_ = intervals_.begin();
  result->current_interval_ = result->intervals_.begin();
#ifdef DEBUG
  VerifyChildStructure();
  result->VerifyChildStructure();
#endif
  result->top_level_ = TopLevel();
  result->next_ = next_;
  next_ = result;
  // Update cache for `TopLevelLiveRange::GetChildCovers()`.
  auto& children = TopLevel()->children_;
  children.insert(std::upper_bound(children.begin(), children.end(), result,
                                   LiveRangeOrdering()),
                  1, result);
  return result;
}
References v8::internal::compiler::DoubleEndedSplitVector< T >::back(), v8::internal::compiler::DoubleEndedSplitVector< T >::begin(), v8::internal::compiler::TopLevelLiveRange::children_, current_hint_position_index_, current_interval_, v8::internal::DCHECK(), DCHECK_NE, v8::internal::compiler::DoubleEndedSplitVector< T >::empty(), v8::internal::compiler::DoubleEndedSplitVector< T >::end(), v8::internal::compiler::UseInterval::end(), End(), end_, v8::internal::compiler::TopLevelLiveRange::GetNextChildId(), v8::internal::compiler::DoubleEndedSplitVector< T >::insert(), intervals_, v8::internal::Zone::New(), next_, positions_span_, representation(), v8::base::internal::result, v8::internal::compiler::DoubleEndedSplitVector< T >::SplitAt(), v8::internal::compiler::UseInterval::SplitAt(), Start(), TopLevel(), and v8::base::VectorOf().
Referenced by v8::internal::compiler::RegisterAllocator::SplitRangeAt(), and v8::internal::compiler::LinearScanAllocator::UpdateDeferredFixedRanges().
Start()
LifetimePosition v8::internal::compiler::LiveRange::Start () const [inline]
Definition at line 877 of file register-allocator.h.
                                 {
    DCHECK(!IsEmpty());
    DCHECK_EQ(start_, intervals_.front().start());
    return start_;
  }
References v8::internal::DCHECK(), and DCHECK_EQ.
Referenced by v8::internal::compiler::SpillPlacer::Add(), v8::internal::compiler::LinearScanAllocator::AddToActive(), v8::internal::compiler::LinearScanAllocator::AddToInactive(), v8::internal::compiler::LinearScanAllocator::AllocateBlockedReg(), v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), v8::internal::compiler::BundleBuilder::BuildBundles(), CanCover(), ConvertUsesToOperand(), v8::internal::compiler::LiveRangeBuilder::Define(), v8::internal::compiler::LinearScanAllocator::FindFreeRegistersForRange(), v8::internal::compiler::RegisterAllocator::FindOptimalSpillingPos(), FirstIntersection(), v8::internal::compiler::RegisterAllocator::GetSplitPositionForInstruction(), v8::internal::compiler::LinearScanAllocator::MaybeSpillPreviousRanges(), v8::internal::compiler::LiveRangeOrdering::operator()(), v8::internal::compiler::ReferenceMapPopulator::PopulateReferenceMaps(), v8::internal::compiler::LinearScanAllocator::ReloadLiveRanges(), ShouldBeAllocatedBefore(), v8::internal::compiler::RegisterAllocator::Spill(), v8::internal::compiler::LinearScanAllocator::SpillBetweenUntil(), v8::internal::compiler::LinearScanAllocator::SplitAndSpillIntersecting(), v8::internal::compiler::RegisterAllocator::SplitAndSpillRangesDefinedByMemoryOperand(), SplitAt(), and v8::internal::compiler::LinearScanAllocator::TryReuseSpillForPhi().
TopLevel() [1/2]
TopLevelLiveRange* v8::internal::compiler::LiveRange::TopLevel () [inline]
Definition at line 788 of file register-allocator.h.
{ return top_level_; }
Referenced by v8::internal::compiler::LinearScanAllocator::AddToActive(), v8::internal::compiler::LinearScanAllocator::AddToInactive(), v8::internal::compiler::LinearScanAllocator::AddToUnhandled(), v8::internal::compiler::LinearScanAllocator::AllocateBlockedReg(), v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), v8::internal::compiler::LinearScanAllocator::AssignRegisterOnReload(), AttachToNext(), v8::internal::compiler::BundleBuilder::BuildBundles(), v8::internal::compiler::LinearScanAllocator::ChooseOneOfTwoPredecessorStates(), v8::internal::compiler::LinearScanAllocator::ComputeStateFromManyPredecessors(), v8::internal::compiler::RegisterAllocator::FindOptimalSpillingPos(), GetAssignedOperand(), v8::internal::compiler::LinearScanAllocator::InactiveToActive(), v8::internal::compiler::LinearScanAllocator::InactiveToHandled(), v8::internal::compiler::LinearScanAllocator::MaybeSpillPreviousRanges(), v8::internal::compiler::LinearScanAllocator::MaybeUndoPreviousSplit(), v8::internal::compiler::operator<<(), v8::internal::compiler::GraphC1Visualizer::PrintLiveRange(), RegisterFromBundle(), v8::internal::compiler::LiveRangeConnector::ResolveControlFlow(), v8::internal::compiler::LinearScanAllocator::SetLiveRangeAssignedRegister(), ShouldBeAllocatedBefore(), Spill(), v8::internal::compiler::RegisterAllocator::Spill(), v8::internal::compiler::LinearScanAllocator::SpillBetweenUntil(), v8::internal::compiler::LinearScanAllocator::SpillNotLiveRanges(), v8::internal::compiler::LinearScanAllocator::SplitAndSpillIntersecting(), v8::internal::compiler::RegisterAllocator::SplitAndSpillRangesDefinedByMemoryOperand(), SplitAt(), v8::internal::compiler::RegisterAllocator::SplitBetween(), v8::internal::compiler::RegisterAllocator::SplitRangeAt(), v8::internal::compiler::LinearScanAllocator::TryAllocateFreeReg(), v8::internal::compiler::LinearScanAllocator::TryAllocatePreferredReg(), and UpdateBundleRegister().
TopLevel() [2/2]
const TopLevelLiveRange* v8::internal::compiler::LiveRange::TopLevel () const [inline]
Definition at line 789 of file register-allocator.h.
{ return top_level_; }
UnsetAssignedRegister()
void v8::internal::compiler::LiveRange::UnsetAssignedRegister ()
Definition at line 234 of file register-allocator.cc.
                                      {
  DCHECK(HasRegisterAssigned() && !spilled());
  bits_ = AssignedRegisterField::update(bits_, kUnassignedRegister);
}
References bits_, v8::internal::DCHECK(), HasRegisterAssigned(), v8::internal::compiler::kUnassignedRegister, spilled(), and v8::base::BitField< T, shift, size, U >::update().
UnsetUseHints()
void v8::internal::compiler::LiveRange::UnsetUseHints () [inline]
Definition at line 907 of file register-allocator.h.
{ SetUseHints(kUnassignedRegister); }
References v8::internal::compiler::kUnassignedRegister.
Unspill()
void v8::internal::compiler::LiveRange::Unspill ()
Definition at line 264 of file register-allocator.cc.
                        {
  DCHECK(spilled());
  set_spilled(false);
  bits_ = AssignedRegisterField::update(bits_, kUnassignedRegister);
}
References bits_, v8::internal::DCHECK(), v8::internal::compiler::kUnassignedRegister, set_spilled(), spilled(), and v8::base::BitField< T, shift, size, U >::update().
Referenced by v8::internal::compiler::LinearScanAllocator::ReloadLiveRanges().
UpdateBundleRegister()
void v8::internal::compiler::LiveRange::UpdateBundleRegister (int reg) const
Definition at line 673 of file register-allocator.cc.
                                                  {
  LiveRangeBundle* bundle = TopLevel()->get_bundle();
  if (bundle == nullptr || bundle->reg() != kUnassignedRegister) return;
  bundle->set_reg(reg);
}
References v8::internal::compiler::TopLevelLiveRange::get_bundle(), v8::internal::compiler::kUnassignedRegister, v8::internal::compiler::LiveRangeBundle::reg(), v8::internal::compiler::LiveRangeBundle::set_reg(), and TopLevel().
Referenced by v8::internal::compiler::LinearScanAllocator::SetLiveRangeAssignedRegister().
Friends And Related Function Documentation
TopLevelLiveRange
friend class TopLevelLiveRange [friend]
Definition at line 917 of file register-allocator.h.
Member Data Documentation
bits_
uint32_t v8::internal::compiler::LiveRange::bits_ [private]
Definition at line 945 of file register-allocator.h.
Referenced by LiveRange(), set_assigned_register(), Spill(), UnsetAssignedRegister(), and Unspill().
current_hint_position_index_
size_t v8::internal::compiler::LiveRange::current_hint_position_index_ = 0 [private]
Definition at line 962 of file register-allocator.h.
Referenced by RegisterFromFirstHint(), and SplitAt().
current_interval_
UseIntervalVector::iterator v8::internal::compiler::LiveRange::current_interval_ [private]
Definition at line 959 of file register-allocator.h.
Referenced by v8::internal::compiler::TopLevelLiveRange::AddUseInterval(), AdvanceLastProcessedMarker(), v8::internal::compiler::TopLevelLiveRange::EnsureInterval(), FirstSearchIntervalForPosition(), and SplitAt().
end_
LifetimePosition v8::internal::compiler::LiveRange::end_ [private]
Definition at line 970 of file register-allocator.h.
Referenced by v8::internal::compiler::TopLevelLiveRange::AddUseInterval(), AttachToNext(), v8::internal::compiler::TopLevelLiveRange::EnsureInterval(), and SplitAt().
intervals_
UseIntervalVector v8::internal::compiler::LiveRange::intervals_ [private]
Definition at line 947 of file register-allocator.h.
Referenced by v8::internal::compiler::TopLevelLiveRange::AddUseInterval(), AdvanceLastProcessedMarker(), AttachToNext(), Covers(), v8::internal::compiler::TopLevelLiveRange::EnsureInterval(), FirstIntersection(), FirstSearchIntervalForPosition(), NextEndAfter(), NextStartAfter(), v8::internal::compiler::TopLevelLiveRange::ShortenTo(), and SplitAt().
next_
LiveRange* v8::internal::compiler::LiveRange::next_ [private]
Definition at line 956 of file register-allocator.h.
Referenced by v8::internal::compiler::TopLevelLiveRange::AddUsePosition(), AttachToNext(), and SplitAt().
next_start_
LifetimePosition v8::internal::compiler::LiveRange::next_start_ [private]
Definition at line 965 of file register-allocator.h.
Referenced by NextStartAfter().
positions_span_
base::Vector<UsePosition*> v8::internal::compiler::LiveRange::positions_span_ [private]
Definition at line 950 of file register-allocator.h.
Referenced by v8::internal::compiler::TopLevelLiveRange::AddUsePosition(), AttachToNext(), ConvertUsesToOperand(), NextRegisterPosition(), NextUsePosition(), NextUsePositionRegisterIsBeneficial(), NextUsePositionSpillDetrimental(), RegisterFromFirstHint(), SetUseHints(), ShouldBeAllocatedBefore(), and SplitAt().
relative_id_
int v8::internal::compiler::LiveRange::relative_id_ [private]
Definition at line 944 of file register-allocator.h.
start_
LifetimePosition v8::internal::compiler::LiveRange::start_ [private]
Definition at line 969 of file register-allocator.h.
Referenced by v8::internal::compiler::TopLevelLiveRange::AddUseInterval(), v8::internal::compiler::TopLevelLiveRange::EnsureInterval(), and v8::internal::compiler::TopLevelLiveRange::ShortenTo().
top_level_
TopLevelLiveRange* v8::internal::compiler::LiveRange::top_level_ [private]
Definition at line 952 of file register-allocator.h.
Referenced by IsTopLevel().
Zone
friend v8::internal::compiler::LiveRange::Zone [private]
Definition at line 918 of file register-allocator.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/register-allocator.h
/mnt/V8SourceCode/src/compiler/backend/register-allocator.cc