v8::internal::NewLargeObjectSpace Class Reference
#include <large-spaces.h>
Public Member Functions
NewLargeObjectSpace (Heap *heap, size_t capacity)
V8_EXPORT_PRIVATE V8_WARN_UNUSED_RESULT AllocationResult AllocateRaw (LocalHeap *local_heap, int object_size, AllocationHint hint)
size_t Available () const override
void Flip ()
void FreeDeadObjects (const std::function< bool(Tagged< HeapObject >)> &is_dead)
void SetCapacity (size_t capacity)
Private Attributes
size_t capacity_
Additional Inherited Members
Detailed Description
Definition at line 179 of file large-spaces.h.
Constructor & Destructor Documentation
NewLargeObjectSpace()
v8::internal::NewLargeObjectSpace::NewLargeObjectSpace (Heap * heap, size_t capacity)
Definition at line 371 of file large-spaces.cc.
    : LargeObjectSpace(heap, NEW_LO_SPACE), capacity_(capacity) {}
Member Function Documentation
AllocateRaw()
AllocationResult v8::internal::NewLargeObjectSpace::AllocateRaw (LocalHeap * local_heap, int object_size, AllocationHint hint)
Definition at line 374 of file large-spaces.cc.
                                                                       {
  object_size = ALIGN_TO_ALLOCATION_ALIGNMENT(object_size);
  DCHECK(local_heap->is_main_thread());
  // Do not allocate more objects if promoting the existing object would exceed
  // the old generation capacity.
  if (!heap()->CanExpandOldGeneration(SizeOfObjects())) {
    return AllocationResult::Failure();
  }
  // Allocation for the first object must succeed independent from the capacity.
  if (SizeOfObjects() > 0 && static_cast<size_t>(object_size) > Available()) {
    if (!heap()->ShouldExpandYoungGenerationOnSlowAllocation(object_size)) {
      return AllocationResult::Failure();
    }
  }
  LargePageMetadata* page =
      AllocateLargePage(object_size, NOT_EXECUTABLE, hint);
  if (page == nullptr) return AllocationResult::Failure();
  // The size of the first object may exceed the capacity.
  capacity_ = std::max(capacity_, SizeOfObjects());
  Tagged<HeapObject> result = page->GetObject();
  MemoryChunk* chunk = page->Chunk();
  chunk->SetFlagNonExecutable(MemoryChunk::TO_PAGE);
  UpdatePendingObject(result);
  if (v8_flags.minor_ms) {
    page->ClearLiveness();
  }
  chunk->InitializationMemoryFence();
  DCHECK(chunk->IsLargePage());
  DCHECK_EQ(page->owner_identity(), NEW_LO_SPACE);
  AdvanceAndInvokeAllocationObservers(result.address(),
                                      static_cast<size_t>(object_size));
  return AllocationResult::FromObject(result);
}
References v8::internal::LargeObjectSpace::AdvanceAndInvokeAllocationObservers(), ALIGN_TO_ALLOCATION_ALIGNMENT, v8::internal::LargeObjectSpace::AllocateLargePage(), Available(), capacity_, v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::MutablePageMetadata::ClearLiveness(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::AllocationResult::Failure(), v8::internal::AllocationResult::FromObject(), v8::internal::LargePageMetadata::GetObject(), v8::internal::BaseSpace::heap(), v8::internal::MemoryChunk::InitializationMemoryFence(), v8::internal::LocalHeap::is_main_thread(), v8::internal::MemoryChunk::IsLargePage(), v8::internal::NEW_LO_SPACE, v8::internal::NOT_EXECUTABLE, v8::internal::MutablePageMetadata::owner_identity(), v8::base::internal::result, v8::internal::MemoryChunk::SetFlagNonExecutable(), v8::internal::LargeObjectSpace::SizeOfObjects(), v8::internal::MemoryChunk::TO_PAGE, v8::internal::LargeObjectSpace::UpdatePendingObject(), and v8::internal::v8_flags.
Referenced by v8::internal::HeapAllocator::AllocateRawLargeInternal().
Available()
size_t v8::internal::NewLargeObjectSpace::Available () const [override], [virtual]
Reimplemented from v8::internal::LargeObjectSpace.
Definition at line 414 of file large-spaces.cc.
                                            {
  // Due to resizing of large objects, SizeOfObjects() can become larger than
  // capacity_.
  const size_t size_of_objects = SizeOfObjects();
  return capacity_ > size_of_objects ? capacity_ - size_of_objects : 0;
}
References capacity_, and v8::internal::LargeObjectSpace::SizeOfObjects().
Referenced by AllocateRaw(), and v8::internal::Heap::PrintShortHeapStatistics().
Flip()
void v8::internal::NewLargeObjectSpace::Flip ()
Definition at line 421 of file large-spaces.cc.
                               {
  for (LargePageMetadata* page = first_page(); page != nullptr;
       page = page->next_page()) {
    MemoryChunk* chunk = page->Chunk();
    chunk->SetFlagNonExecutable(MemoryChunk::FROM_PAGE);
    chunk->ClearFlagNonExecutable(MemoryChunk::TO_PAGE);
  }
}
References v8::internal::MemoryChunk::ClearFlagNonExecutable(), v8::internal::LargeObjectSpace::first_page(), v8::internal::MemoryChunk::FROM_PAGE, v8::internal::LargePageMetadata::next_page(), v8::internal::MemoryChunk::SetFlagNonExecutable(), and v8::internal::MemoryChunk::TO_PAGE.
Referenced by v8::internal::ScavengerCollector::CollectGarbage().
FreeDeadObjects()
void v8::internal::NewLargeObjectSpace::FreeDeadObjects (const std::function< bool(Tagged< HeapObject >)> & is_dead)
Definition at line 430 of file large-spaces.cc.
                                                          {
  DCHECK(!heap()->incremental_marking()->IsMarking());
  size_t surviving_object_size = 0;
  PtrComprCageBase cage_base(heap()->isolate());
  std::vector<LargePageMetadata*> pages_to_pool;
  if (v8_flags.large_page_pool) {
    pages_to_pool.reserve(memory_chunk_list().size());
  }
  for (auto it = begin(); it != end();) {
    LargePageMetadata* page = *it;
    it++;
    Tagged<HeapObject> object = page->GetObject();
    if (is_dead(object)) {
      RemovePage(page);
      if (v8_flags.large_page_pool) {
        pages_to_pool.push_back(page);
      } else {
        heap()->memory_allocator()->Free(
            MemoryAllocator::FreeMode::kImmediately, page);
      }
    } else {
      surviving_object_size += static_cast<size_t>(object->Size(cage_base));
    }
  }
  // Right-trimming does not update the objects_size_ counter. We are lazily
  // updating it after every GC.
  objects_size_ = surviving_object_size;
  if (v8_flags.large_page_pool && !pages_to_pool.empty()) {
    heap()->memory_allocator()->FreeLargePagesPooled(std::move(pages_to_pool));
  }
}
References v8::internal::LargeObjectSpace::begin(), v8::internal::DCHECK(), v8::internal::LargeObjectSpace::end(), v8::internal::MemoryAllocator::Free(), v8::internal::MemoryAllocator::FreeLargePagesPooled(), v8::internal::LargePageMetadata::GetObject(), v8::internal::BaseSpace::heap(), v8::internal::MemoryAllocator::kImmediately, v8::internal::Heap::memory_allocator(), v8::internal::Space::memory_chunk_list(), v8::internal::LargeObjectSpace::objects_size_, v8::internal::LargeObjectSpace::RemovePage(), size(), and v8::internal::v8_flags.
SetCapacity()
void v8::internal::NewLargeObjectSpace::SetCapacity (size_t capacity)
Definition at line 464 of file large-spaces.cc.
                                                     {
  capacity_ = std::max(capacity, SizeOfObjects());
}
References capacity_, and v8::internal::LargeObjectSpace::SizeOfObjects().
Referenced by v8::internal::Heap::ExpandNewSpaceSize(), and v8::internal::Heap::ReduceNewSpaceSize().
Member Data Documentation
capacity_
size_t v8::internal::NewLargeObjectSpace::capacity_ [private]
Definition at line 196 of file large-spaces.h.
Referenced by AllocateRaw(), Available(), and SetCapacity().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/large-spaces.h
/mnt/V8SourceCode/src/heap/large-spaces.cc