v8::internal::compiler::JSStoreGlobalNode Class Reference
#include <js-operator.h>
Public Member Functions
constexpr JSStoreGlobalNode (Node *node)
const StoreGlobalParameters & Parameters () const
Additional Inherited Members
Detailed Description
Definition at line 1631 of file js-operator.h.
Constructor & Destructor Documentation
JSStoreGlobalNode()
constexpr v8::internal::compiler::JSStoreGlobalNode::JSStoreGlobalNode (Node * node) [inline], [explicit], [constexpr]
Definition at line 1633 of file js-operator.h.
                                                   : JSNodeWrapperBase(node) {
    DCHECK_EQ(IrOpcode::kJSStoreGlobal, node->opcode());
  }
References DCHECK_EQ, v8::internal::compiler::NodeWrapper::node(), and v8::internal::compiler::Node::opcode().
Member Function Documentation
Parameters()
const StoreGlobalParameters& v8::internal::compiler::JSStoreGlobalNode::Parameters () const [inline]
Definition at line 1637 of file js-operator.h.
                                                  {
    return StoreGlobalParametersOf(node()->op());
  }
References v8::internal::compiler::NodeWrapper::node(), and v8::internal::compiler::StoreGlobalParametersOf().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceJSStoreGlobal().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h