v8::internal::ReadOnlyPageMetadata Class Reference
#include <read-only-spaces.h>
Public Member Functions
ReadOnlyPageMetadata (Heap *heap, BaseSpace *space, size_t chunk_size, Address area_start, Address area_end, VirtualMemory reservation)
MemoryChunk::MainThreadFlags InitialFlags () const
void MakeHeaderRelocatable ()
size_t ShrinkToHighWaterMark ()
Address OffsetToAddress (size_t offset) const
Address GetAreaStart () const
Friends
class ReadOnlySpace
Additional Inherited Members
Detailed Description
Definition at line 28 of file read-only-spaces.h.
Constructor & Destructor Documentation
ReadOnlyPageMetadata()
v8::internal::ReadOnlyPageMetadata::ReadOnlyPageMetadata (Heap * heap, BaseSpace * space, size_t chunk_size, Address area_start, Address area_end, VirtualMemory reservation)
Definition at line 139 of file read-only-spaces.cc.
    : MemoryChunkMetadata(heap, space, chunk_size, area_start, area_end,
                          std::move(reservation)) {
  allocated_bytes_ = 0;
}
References v8::internal::MemoryChunkMetadata::allocated_bytes_.
Member Function Documentation
GetAreaStart()
Address v8::internal::ReadOnlyPageMetadata::GetAreaStart () const [inline]
Definition at line 59 of file read-only-spaces.h.
                               {
    return ChunkAddress() +
           MemoryChunkLayout::ObjectStartOffsetInMemoryChunk(RO_SPACE);
  }
References v8::internal::MemoryChunkMetadata::ChunkAddress(), v8::internal::MemoryChunkLayout::ObjectStartOffsetInMemoryChunk(), and v8::internal::RO_SPACE.
Referenced by v8::internal::ReadOnlyPageObjectIterator::Next(), v8::internal::ReadOnlyPageObjectIterator::ReadOnlyPageObjectIterator(), and v8::internal::ReadOnlyPageObjectIterator::Reset().
InitialFlags()
MemoryChunk::MainThreadFlags v8::internal::ReadOnlyPageMetadata::InitialFlags () const
Definition at line 148 of file read-only-spaces.cc.
                                                                    {
  return MemoryChunk::NEVER_EVACUATE | MemoryChunk::READ_ONLY_HEAP |
         MemoryChunk::CONTAINS_ONLY_OLD;
}
References v8::internal::MemoryChunk::CONTAINS_ONLY_OLD, v8::internal::MemoryChunk::NEVER_EVACUATE, and v8::internal::MemoryChunk::READ_ONLY_HEAP.
Referenced by v8::internal::MemoryAllocator::AllocateReadOnlyPage().
MakeHeaderRelocatable()
void v8::internal::ReadOnlyPageMetadata::MakeHeaderRelocatable ()
Definition at line 153 of file read-only-spaces.cc.
                                                 {
  heap_ = nullptr;
  owner_ = nullptr;
  reservation_.Reset();
}
References v8::internal::MemoryChunkMetadata::heap_, v8::internal::MemoryChunkMetadata::owner_, v8::internal::MemoryChunkMetadata::reservation_, and v8::internal::VirtualMemory::Reset().
OffsetToAddress()
Address v8::internal::ReadOnlyPageMetadata::OffsetToAddress (size_t offset) const [inline]
Definition at line 42 of file read-only-spaces.h.
                                               {
    Address address_in_page = ChunkAddress() + offset;
    if (COMPRESS_POINTERS_IN_MULTIPLE_CAGES_BOOL) {
      // Pointer compression with multiple pointer cages and shared
      // ReadOnlyPages means that the area_start and area_end cannot be defined
      // since they are stored within the pages which can be mapped at multiple
      // memory addresses.
      DCHECK_LT(offset, size());
    } else {
      DCHECK_GE(address_in_page, area_start());
      DCHECK_LT(address_in_page, area_end());
    }
    return address_in_page;
  }
References v8::internal::MemoryChunkMetadata::area_end(), v8::internal::MemoryChunkMetadata::area_start(), v8::internal::MemoryChunkMetadata::ChunkAddress(), COMPRESS_POINTERS_IN_MULTIPLE_CAGES_BOOL, DCHECK_GE, DCHECK_LT, and v8::internal::MemoryChunkMetadata::size().
Referenced by v8::internal::ReadOnlyHeapImageDeserializer::Decode(), and v8::internal::Deserializer< IsolateT >::ReadReadOnlyHeapRef().
ShrinkToHighWaterMark()
size_t v8::internal::ReadOnlyPageMetadata::ShrinkToHighWaterMark ()
Definition at line 467 of file read-only-spaces.cc.
                                                   {
  // Shrink pages to high water mark. The water mark points either to a filler
  // or the area_end.
  Tagged<HeapObject> filler = HeapObject::FromAddress(HighWaterMark());
  if (filler.address() == area_end()) return 0;
  CHECK(IsFreeSpaceOrFiller(filler));
  DCHECK_EQ(filler.address() + filler->Size(), area_end());
  size_t unused = RoundDown(static_cast<size_t>(area_end() - filler.address()),
                            MemoryAllocator::GetCommitPageSize());
  if (unused > 0) {
    DCHECK_EQ(0u, unused % MemoryAllocator::GetCommitPageSize());
    if (v8_flags.trace_gc_verbose) {
      PrintIsolate(heap()->isolate(), "Shrinking page %p: end %p -> %p\n",
                   reinterpret_cast<void*>(this),
                   reinterpret_cast<void*>(area_end()),
                   reinterpret_cast<void*>(area_end() - unused));
    }
    heap()->CreateFillerObjectAt(
        filler.address(),
        static_cast<int>(area_end() - filler.address() - unused));
    heap()->memory_allocator()->PartialFreeMemory(
        this, ChunkAddress() + size() - unused, unused, area_end() - unused);
    if (filler.address() != area_end()) {
      CHECK(IsFreeSpaceOrFiller(filler));
      CHECK_EQ(filler.address() + filler->Size(), area_end());
    }
  }
  return unused;
}
References v8::internal::Tagged< HeapObject >::address(), v8::internal::MemoryChunkMetadata::area_end(), CHECK, CHECK_EQ, v8::internal::MemoryChunkMetadata::ChunkAddress(), v8::internal::Heap::CreateFillerObjectAt(), DCHECK_EQ, v8::internal::HeapObject::FromAddress(), v8::internal::MemoryAllocator::GetCommitPageSize(), v8::internal::MemoryChunkMetadata::heap(), v8::internal::MemoryChunkMetadata::HighWaterMark(), v8::internal::InstanceTypeChecker::IsFreeSpaceOrFiller(), v8::internal::Heap::memory_allocator(), v8::internal::MemoryAllocator::PartialFreeMemory(), v8::internal::PrintIsolate(), RoundDown(), v8::internal::MemoryChunkMetadata::size(), and v8::internal::v8_flags.
Friends And Related Function Documentation
ReadOnlySpace
friend class ReadOnlySpace [friend]
Definition at line 65 of file read-only-spaces.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/read-only-spaces.h
/mnt/V8SourceCode/src/heap/read-only-spaces.cc