v8::internal::compiler::InstructionOperand Class Reference
#include <instruction.h>
Public Types
enum Kind {
INVALID
, UNALLOCATED
, CONSTANT
, IMMEDIATE
,
PENDING
, ALLOCATED
, FIRST_LOCATION_OPERAND_KIND = ALLOCATED
 }
Public Member Functions
InstructionOperand ()
Kind kind () const
bool IsAnyLocationOperand () const
bool IsLocationOperand () const
bool IsFPLocationOperand () const
bool IsAnyRegister () const
bool IsRegister () const
bool IsFPRegister () const
bool IsFloatRegister () const
bool IsDoubleRegister () const
bool IsSimd128Register () const
bool IsSimd256Register () const
bool IsAnyStackSlot () const
bool IsStackSlot () const
bool IsFPStackSlot () const
bool IsFloatStackSlot () const
bool IsDoubleStackSlot () const
bool IsSimd128StackSlot () const
bool IsSimd256StackSlot () const
bool Equals (const InstructionOperand &that) const
bool Compare (const InstructionOperand &that) const
bool EqualsCanonicalized (const InstructionOperand &that) const
bool CompareCanonicalized (const InstructionOperand &that) const
bool InterferesWith (const InstructionOperand &other) const
void Print () const
bool operator== (const InstructionOperand &other) const
bool operator!= (const InstructionOperand &other) const
Static Public Member Functions
template<typename SubKindOperand >
static SubKindOperand * New (Zone *zone, const SubKindOperand &op)
static void ReplaceWith (InstructionOperand *dest, const InstructionOperand *src)
Static Public Attributes
static const int kInvalidVirtualRegister = -1
Protected Types
using KindField = base::BitField64< Kind, 0, 3 >
Protected Member Functions
InstructionOperand (Kind kind)
uint64_t GetCanonicalizedValue () const
Protected Attributes
uint64_t value_
Detailed Description
Definition at line 48 of file instruction.h.
Member Typedef Documentation
KindField
using v8::internal::compiler::InstructionOperand::KindField = base::BitField64<Kind, 0, 3> [protected]
Definition at line 162 of file instruction.h.
Member Enumeration Documentation
Kind
enum v8::internal::compiler::InstructionOperand::Kind
Enumerator
INVALID
UNALLOCATED
CONSTANT
IMMEDIATE
PENDING
ALLOCATED
FIRST_LOCATION_OPERAND_KIND
Definition at line 52 of file instruction.h.
            {
    INVALID,
    UNALLOCATED,
    CONSTANT,
    IMMEDIATE,
    PENDING,
    // Location operand kinds.
    ALLOCATED,
    FIRST_LOCATION_OPERAND_KIND = ALLOCATED
    // Location operand kinds must be last.
  };
Constructor & Destructor Documentation
InstructionOperand() [1/2]
v8::internal::compiler::InstructionOperand::InstructionOperand () [inline]
Definition at line 64 of file instruction.h.
: InstructionOperand(INVALID) {}
Referenced by v8::internal::compiler::MoveOperands::Eliminate(), v8::internal::compiler::Instruction::New(), and v8::internal::compiler::MoveOperands::SetPending().
InstructionOperand() [2/2]
v8::internal::compiler::InstructionOperand::InstructionOperand (Kind kind) [inline], [explicit], [protected]
Definition at line 158 of file instruction.h.
: value_(KindField::encode(kind)) {}
Member Function Documentation
Compare()
bool v8::internal::compiler::InstructionOperand::Compare (const InstructionOperand & that) const [inline]
Definition at line 128 of file instruction.h.
                                                     {
    return this->value_ < that.value_;
  }
References value_.
Referenced by v8::internal::compiler::anonymous_namespace{move-optimizer.cc}::MoveKey::operator<().
CompareCanonicalized()
bool v8::internal::compiler::InstructionOperand::CompareCanonicalized (const InstructionOperand & that) const [inline]
Definition at line 140 of file instruction.h.
                                                                  {
    DCHECK(!IsPending());
    return this->GetCanonicalizedValue() < that.GetCanonicalizedValue();
  }
References v8::internal::DCHECK(), and GetCanonicalizedValue().
Referenced by v8::internal::compiler::anonymous_namespace{move-optimizer.cc}::LoadCompare(), v8::internal::compiler::CompareOperandModuloType::operator()(), and v8::internal::compiler::OperandAsKeyLess::operator()().
Equals()
bool v8::internal::compiler::InstructionOperand::Equals (const InstructionOperand & that) const [inline]
Definition at line 120 of file instruction.h.
                                                    {
    if (IsPending()) {
      // Pending operands are only equal if they are the same operand.
      return this == &that;
    }
    return this->value_ == that.value_;
  }
References value_.
Referenced by v8::internal::compiler::LiveRangeConnector::ConnectRanges(), v8::internal::compiler::operator<<(), v8::internal::compiler::LiveRangeBuilder::ProcessPhis(), and v8::internal::compiler::LiveRangeConnector::ResolveControlFlow().
EqualsCanonicalized()
bool v8::internal::compiler::InstructionOperand::EqualsCanonicalized (const InstructionOperand & that) const [inline]
Definition at line 132 of file instruction.h.
                                                                 {
    if (IsPending()) {
      // Pending operands can't be canonicalized, so just compare for equality.
      return Equals(that);
    }
    return this->GetCanonicalizedValue() == that.GetCanonicalizedValue();
  }
References v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::Equals(), and GetCanonicalizedValue().
Referenced by v8::internal::compiler::ParallelMove::AddMove(), v8::internal::compiler::MoveOptimizer::FinalizeMoves(), InterferesWith(), v8::internal::compiler::anonymous_namespace{move-optimizer.cc}::LoadCompare(), and v8::internal::compiler::ParallelMove::PrepareInsertAfter().
GetCanonicalizedValue()
uint64_t v8::internal::compiler::InstructionOperand::GetCanonicalizedValue () const [inline], [protected]
Definition at line 733 of file instruction.h.
                                                         {
  if (IsAnyLocationOperand()) {
    MachineRepresentation canonical = MachineRepresentation::kNone;
    if (IsFPRegister()) {
      if (kFPAliasing == AliasingKind::kOverlap) {
        // We treat all FP register operands the same for simple aliasing.
        canonical = MachineRepresentation::kFloat64;
      } else if (kFPAliasing == AliasingKind::kIndependent) {
        if (IsSimd128Register()) {
          canonical = MachineRepresentation::kSimd128;
        } else {
          canonical = MachineRepresentation::kFloat64;
        }
      } else {
        // We need to distinguish FP register operands of different reps when
        // aliasing is AliasingKind::kCombine (e.g. ARM).
        DCHECK_EQ(kFPAliasing, AliasingKind::kCombine);
        canonical = LocationOperand::cast(this)->representation();
      }
    }
    return InstructionOperand::KindField::update(
        LocationOperand::RepresentationField::update(this->value_, canonical),
        LocationOperand::ALLOCATED);
  }
  return this->value_;
}
References ALLOCATED, v8::internal::compiler::LocationOperand::cast(), DCHECK_EQ, IsAnyLocationOperand(), IsFPRegister(), IsSimd128Register(), v8::internal::kCombine, v8::internal::kFloat64, v8::internal::kFPAliasing, v8::internal::kIndependent, v8::internal::kNone, v8::internal::kOverlap, v8::internal::kSimd128, v8::internal::compiler::LocationOperand::representation(), v8::base::BitField< T, shift, size, U >::update(), and value_.
Referenced by CompareCanonicalized(), and EqualsCanonicalized().
InterferesWith()
bool v8::internal::compiler::InstructionOperand::InterferesWith (const InstructionOperand & other) const
Definition at line 92 of file instruction.cc.
                                                                             {
  const bool combine_fp_aliasing = kFPAliasing == AliasingKind::kCombine &&
                                   this->IsFPLocationOperand() &&
                                   other.IsFPLocationOperand();
  const bool stack_slots = this->IsAnyStackSlot() && other.IsAnyStackSlot();
  if (!combine_fp_aliasing && !stack_slots) {
    return EqualsCanonicalized(other);
  }
  const LocationOperand& loc = *LocationOperand::cast(this);
  const LocationOperand& other_loc = LocationOperand::cast(other);
  MachineRepresentation rep = loc.representation();
  MachineRepresentation other_rep = other_loc.representation();
  LocationOperand::LocationKind kind = loc.location_kind();
  LocationOperand::LocationKind other_kind = other_loc.location_kind();
  if (kind != other_kind) return false;
  if (combine_fp_aliasing && !stack_slots) {
    if (rep == other_rep) return EqualsCanonicalized(other);
    DCHECK_EQ(kind, LocationOperand::REGISTER);
    // FP register-register interference.
    return GetRegConfig()->AreAliases(rep, loc.register_code(), other_rep,
                                      other_loc.register_code());
  }
  DCHECK(stack_slots);
  int num_slots =
      AlignedSlotAllocator::NumSlotsForWidth(ElementSizeInBytes(rep));
  int num_slots_other =
      AlignedSlotAllocator::NumSlotsForWidth(ElementSizeInBytes(other_rep));
  const bool complex_stack_slot_interference =
      (num_slots > 1 || num_slots_other > 1);
  if (!complex_stack_slot_interference) {
    return EqualsCanonicalized(other);
  }
  // Complex multi-slot operand interference:
  // - slots of different FP reps can alias because the gap resolver may break a
  // move into 2 or 4 equivalent smaller moves,
  // - stack layout can be rearranged for tail calls
  DCHECK_EQ(LocationOperand::STACK_SLOT, kind);
  int index_hi = loc.index();
  int index_lo =
      index_hi -
      AlignedSlotAllocator::NumSlotsForWidth(ElementSizeInBytes(rep)) + 1;
  int other_index_hi = other_loc.index();
  int other_index_lo =
      other_index_hi -
      AlignedSlotAllocator::NumSlotsForWidth(ElementSizeInBytes(other_rep)) + 1;
  return other_index_hi >= index_lo && index_hi >= other_index_lo;
}
References v8::internal::RegisterConfiguration::AreAliases(), v8::internal::compiler::LocationOperand::cast(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::ElementSizeInBytes(), EqualsCanonicalized(), v8::internal::compiler::GetRegConfig, v8::internal::compiler::LocationOperand::index(), IsAnyStackSlot(), IsFPLocationOperand(), v8::internal::kCombine, v8::internal::kFPAliasing, kind(), v8::internal::loc, v8::internal::compiler::LocationOperand::location_kind(), v8::internal::AlignedSlotAllocator::NumSlotsForWidth(), v8::internal::compiler::LocationOperand::REGISTER, v8::internal::compiler::LocationOperand::register_code(), v8::internal::compiler::LocationOperand::representation(), and v8::internal::compiler::LocationOperand::STACK_SLOT.
Referenced by v8::internal::compiler::ParallelMove::PrepareInsertAfter().
IsAnyLocationOperand()
bool v8::internal::compiler::InstructionOperand::IsAnyLocationOperand () const [inline]
Definition at line 635 of file instruction.h.
                                                    {
  return this->kind() >= FIRST_LOCATION_OPERAND_KIND;
}
References FIRST_LOCATION_OPERAND_KIND, and kind().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AssignArbitraryRegisterInput(), v8::internal::compiler::LocationOperand::cast(), GetCanonicalizedValue(), IsAnyRegister(), IsAnyStackSlot(), IsDoubleStackSlot(), IsFloatStackSlot(), IsFPLocationOperand(), IsLocationOperand(), IsSimd128StackSlot(), IsSimd256StackSlot(), and v8::internal::compiler::SignExtend().
IsAnyRegister()
bool v8::internal::compiler::InstructionOperand::IsAnyRegister () const [inline]
Definition at line 649 of file instruction.h.
                                             {
  return IsAnyLocationOperand() &&
         LocationOperand::cast(this)->location_kind() ==
             LocationOperand::REGISTER;
}
References v8::internal::compiler::LocationOperand::cast(), IsAnyLocationOperand(), v8::internal::compiler::LocationOperand::location_kind(), and v8::internal::compiler::LocationOperand::REGISTER.
Referenced by v8::internal::compiler::ConstraintBuilder::AllocateFixed(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNodeResult(), v8::internal::maglev::StraightForwardRegisterAllocator::AssignAnyInput(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildDeoptFrameSingleValue(), v8::internal::compiler::SpillPlacer::CommitSpill(), v8::internal::compiler::LiveRangeConnector::ConnectRanges(), v8::internal::compiler::BlockAssessments::DropRegisters(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::EmitBlockEndGapMoves(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::EmitPopMaterialisedResults(), v8::internal::compiler::CodeGenerator::MoveType::InferMove(), v8::internal::compiler::CodeGenerator::MoveType::InferSwap(), v8::internal::maglev::ValueLocation::IsAnyRegister(), IsDoubleRegister(), IsFloatRegister(), IsFPRegister(), IsRegister(), IsSimd128Register(), IsSimd256Register(), v8::internal::compiler::LiveRangeBuilder::ProcessInstructions(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::RecordMove(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::RecordMoveToRegister(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::RecordMoveToStackSlot(), and v8::internal::compiler::LiveRangeConnector::ResolveControlFlow().
IsAnyStackSlot()
bool v8::internal::compiler::InstructionOperand::IsAnyStackSlot () const [inline]
Definition at line 685 of file instruction.h.
                                              {
  return IsAnyLocationOperand() &&
         LocationOperand::cast(this)->location_kind() ==
             LocationOperand::STACK_SLOT;
}
References v8::internal::compiler::LocationOperand::cast(), IsAnyLocationOperand(), v8::internal::compiler::LocationOperand::location_kind(), and v8::internal::compiler::LocationOperand::STACK_SLOT.
Referenced by v8::internal::compiler::CodeGenerator::GetPushCompatibleMoves(), v8::internal::compiler::CodeGenerator::IncrementStackAccessCounter(), v8::internal::compiler::CodeGenerator::MoveType::InferMove(), v8::internal::compiler::CodeGenerator::MoveType::InferSwap(), InterferesWith(), v8::internal::maglev::ValueNode::is_loadable(), v8::internal::maglev::ValueNode::is_spilled(), IsFPStackSlot(), IsStackSlot(), v8::internal::compiler::GapResolver::PerformCycle(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::Process(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::RecordMoveToRegister(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::RecordMoveToStackSlot(), and v8::internal::maglev::ValueNode::Spill().
IsDoubleRegister()
bool v8::internal::compiler::InstructionOperand::IsDoubleRegister () const [inline]
Definition at line 670 of file instruction.h.
                                                {
  return IsAnyRegister() && LocationOperand::cast(this)->representation() ==
                                MachineRepresentation::kFloat64;
}
References v8::internal::compiler::LocationOperand::cast(), IsAnyRegister(), v8::internal::kFloat64, and v8::internal::compiler::LocationOperand::representation().
Referenced by v8::internal::compiler::CodeGenerator::AssembleMove(), v8::internal::compiler::CodeGenerator::AssembleSwap(), v8::internal::maglev::StraightForwardRegisterAllocator::AssignAnyInput(), v8::internal::compiler::Arm64OperandConverter::InputFloat64OrFPZeroRegister(), v8::internal::compiler::Arm64OperandConverter::InputFloat64OrZeroRegister(), v8::internal::compiler::LocationOperand::IsCompatible(), v8::internal::maglev::ValueLocation::IsDoubleRegister(), v8::internal::compiler::operator<<(), and v8::internal::compiler::GraphC1Visualizer::PrintLiveRange().
IsDoubleStackSlot()
bool v8::internal::compiler::InstructionOperand::IsDoubleStackSlot () const [inline]
Definition at line 709 of file instruction.h.
                                                 {
  return IsAnyLocationOperand() &&
         LocationOperand::cast(this)->location_kind() ==
             LocationOperand::STACK_SLOT &&
         LocationOperand::cast(this)->representation() ==
             MachineRepresentation::kFloat64;
}
References v8::internal::compiler::LocationOperand::cast(), IsAnyLocationOperand(), v8::internal::kFloat64, v8::internal::compiler::LocationOperand::location_kind(), v8::internal::compiler::LocationOperand::representation(), and v8::internal::compiler::LocationOperand::STACK_SLOT.
Referenced by v8::internal::compiler::CodeGenerator::AssembleMove(), v8::internal::compiler::CodeGenerator::AssembleSwap(), v8::internal::compiler::LocationOperand::IsCompatible(), and v8::internal::compiler::CodeGenerator::SetPendingMove().
IsFloatRegister()
bool v8::internal::compiler::InstructionOperand::IsFloatRegister () const [inline]
Definition at line 665 of file instruction.h.
                                               {
  return IsAnyRegister() && LocationOperand::cast(this)->representation() ==
                                MachineRepresentation::kFloat32;
}
References v8::internal::compiler::LocationOperand::cast(), IsAnyRegister(), v8::internal::kFloat32, and v8::internal::compiler::LocationOperand::representation().
Referenced by v8::internal::compiler::CodeGenerator::AssembleMove(), v8::internal::compiler::CodeGenerator::AssembleSwap(), v8::internal::compiler::LocationOperand::GetFloatRegister(), v8::internal::compiler::LocationOperand::IsCompatible(), v8::internal::compiler::operator<<(), and v8::internal::compiler::GraphC1Visualizer::PrintLiveRange().
IsFloatStackSlot()
bool v8::internal::compiler::InstructionOperand::IsFloatStackSlot () const [inline]
Definition at line 701 of file instruction.h.
                                                {
  return IsAnyLocationOperand() &&
         LocationOperand::cast(this)->location_kind() ==
             LocationOperand::STACK_SLOT &&
         LocationOperand::cast(this)->representation() ==
             MachineRepresentation::kFloat32;
}
References v8::internal::compiler::LocationOperand::cast(), IsAnyLocationOperand(), v8::internal::kFloat32, v8::internal::compiler::LocationOperand::location_kind(), v8::internal::compiler::LocationOperand::representation(), and v8::internal::compiler::LocationOperand::STACK_SLOT.
Referenced by v8::internal::compiler::CodeGenerator::AssembleMove(), v8::internal::compiler::CodeGenerator::AssembleSwap(), v8::internal::compiler::LocationOperand::IsCompatible(), and v8::internal::compiler::CodeGenerator::SetPendingMove().
IsFPLocationOperand()
bool v8::internal::compiler::InstructionOperand::IsFPLocationOperand () const [inline]
Definition at line 644 of file instruction.h.
                                                   {
  return IsAnyLocationOperand() &&
         IsFloatingPoint(LocationOperand::cast(this)->representation());
}
References v8::internal::compiler::LocationOperand::cast(), IsAnyLocationOperand(), and v8::internal::IsFloatingPoint().
Referenced by InterferesWith(), and v8::internal::compiler::ParallelMove::PrepareInsertAfter().
IsFPRegister()
bool v8::internal::compiler::InstructionOperand::IsFPRegister () const [inline]
Definition at line 660 of file instruction.h.
                                            {
  return IsAnyRegister() &&
         IsFloatingPoint(LocationOperand::cast(this)->representation());
}
References v8::internal::compiler::LocationOperand::cast(), IsAnyRegister(), and v8::internal::IsFloatingPoint().
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand(), v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::RegisterAllocatorVerifier::CheckConstraint(), v8::internal::compiler::anonymous_namespace{move-optimizer.cc}::OperandSet::ContainsOpOrAlias(), v8::internal::compiler::LiveRange::ConvertUsesToOperand(), GetCanonicalizedValue(), v8::internal::compiler::LocationOperand::GetDoubleRegister(), v8::internal::compiler::HasFPRegisterInput(), v8::internal::compiler::UsePosition::HintTypeForOperand(), v8::internal::compiler::Arm64OperandConverter::InputFloat32OrFPZeroRegister(), v8::internal::compiler::Arm64OperandConverter::InputFloat32OrZeroRegister(), v8::internal::compiler::anonymous_namespace{move-optimizer.cc}::OperandSet::InsertOp(), v8::internal::compiler::LocationOperand::IsCompatible(), v8::internal::compiler::LiveRangeBuilder::LiveRangeFor(), v8::internal::compiler::ReferenceMap::RecordReference(), v8::internal::compiler::LocationOperand::register_code(), and v8::internal::compiler::IA32OperandConverter::ToOperand().
IsFPStackSlot()
bool v8::internal::compiler::InstructionOperand::IsFPStackSlot () const [inline]
Definition at line 696 of file instruction.h.
                                             {
  return IsAnyStackSlot() &&
         IsFloatingPoint(LocationOperand::cast(this)->representation());
}
References v8::internal::compiler::LocationOperand::cast(), IsAnyStackSlot(), and v8::internal::IsFloatingPoint().
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand(), v8::internal::compiler::RegisterAllocatorVerifier::CheckConstraint(), v8::internal::compiler::LiveRange::ConvertUsesToOperand(), v8::internal::compiler::HasFPStackSlotInput(), v8::internal::compiler::UsePosition::HintTypeForOperand(), v8::internal::compiler::LocationOperand::index(), v8::internal::compiler::LocationOperand::IsCompatible(), v8::internal::compiler::anonymous_namespace{move-optimizer.cc}::IsSlot(), v8::internal::compiler::operator<<(), v8::internal::compiler::ReferenceMap::RecordReference(), v8::internal::compiler::ArmOperandConverter::ToMemOperand(), v8::internal::compiler::Loong64OperandConverter::ToMemOperand(), v8::internal::compiler::MipsOperandConverter::ToMemOperand(), v8::internal::compiler::PPCOperandConverter::ToMemOperand(), v8::internal::compiler::RiscvOperandConverter::ToMemOperand(), v8::internal::compiler::S390OperandConverter::ToMemOperand(), v8::internal::compiler::Arm64OperandConverter::ToMemOperand(), v8::internal::compiler::IA32OperandConverter::ToOperand(), and v8::internal::compiler::X64OperandConverter::ToOperand().
IsLocationOperand()
bool v8::internal::compiler::InstructionOperand::IsLocationOperand () const [inline]
Definition at line 639 of file instruction.h.
                                                 {
  return IsAnyLocationOperand() &&
         !IsFloatingPoint(LocationOperand::cast(this)->representation());
}
References v8::internal::compiler::LocationOperand::cast(), IsAnyLocationOperand(), and v8::internal::IsFloatingPoint().
Referenced by v8::internal::compiler::anonymous_namespace{move-optimizer.cc}::LoadCompare().
IsRegister()
bool v8::internal::compiler::InstructionOperand::IsRegister () const [inline]
Definition at line 655 of file instruction.h.
                                          {
  return IsAnyRegister() &&
         !IsFloatingPoint(LocationOperand::cast(this)->representation());
}
References v8::internal::compiler::LocationOperand::cast(), IsAnyRegister(), and v8::internal::IsFloatingPoint().
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand(), v8::internal::maglev::detail::AlreadyInARegister(), v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::CodeGenerator::AssembleMove(), v8::internal::compiler::CodeGenerator::AssembleSwap(), v8::internal::compiler::CodeGenerator::AssembleTailCallBeforeGap(), v8::internal::compiler::RegisterAllocatorVerifier::CheckConstraint(), v8::internal::compiler::LiveRange::ConvertUsesToOperand(), v8::internal::maglev::MaglevAssembler::FromAnyToRegister(), v8::internal::compiler::LocationOperand::GetRegister(), v8::internal::compiler::anonymous_namespace{code-generator-ia32.cc}::HasRegisterInput(), v8::internal::compiler::HasRegisterInput(), v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::HasRegisterInput(), v8::internal::compiler::HasRegisterOutput(), v8::internal::compiler::UsePosition::HintTypeForOperand(), v8::internal::compiler::Loong64OperandConverter::InputOperand(), v8::internal::compiler::MipsOperandConverter::InputOperand(), v8::internal::compiler::RiscvOperandConverter::InputOperand(), v8::internal::compiler::Arm64OperandConverter::InputOrZeroRegister32(), v8::internal::compiler::Arm64OperandConverter::InputOrZeroRegister64(), v8::internal::compiler::anonymous_namespace{code-generator-loong64.cc}::Is32BitOperand(), v8::internal::compiler::anonymous_namespace{code-generator-mips64.cc}::Is32BitOperand(), v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::Is32BitOperand(), v8::internal::compiler::LocationOperand::IsCompatible(), v8::internal::maglev::ValueLocation::IsGeneralRegister(), v8::internal::maglev::MaglevAssembler::IsRootConstant(), v8::internal::compiler::CodeGenerator::IsValidPush(), v8::internal::compiler::LiveRangeBuilder::LiveRangeFor(), v8::internal::compiler::IA32OperandConverter::MoveInstructionOperandToRegister(), v8::internal::compiler::CodeGenerator::MoveTempLocationTo(), v8::internal::compiler::CodeGenerator::MoveToTempLocation(), v8::internal::compiler::operator<<(), v8::internal::compiler::CodeGenerator::Pop(), v8::internal::compiler::GraphC1Visualizer::PrintLiveRange(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::Process(), v8::internal::compiler::LiveRangeBuilder::ProcessInstructions(), v8::internal::compiler::CodeGenerator::Push(), v8::internal::maglev::detail::PushInput(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::RecordMoves(), v8::internal::compiler::LocationOperand::register_code(), v8::internal::compiler::Arm64OperandConverter::ToOperand(), v8::internal::compiler::IA32OperandConverter::ToOperand(), v8::internal::compiler::Arm64OperandConverter::ToOperand32(), and v8::internal::maglev::detail::ToRegister().
IsSimd128Register()
bool v8::internal::compiler::InstructionOperand::IsSimd128Register () const [inline]
Definition at line 675 of file instruction.h.
                                                 {
  return IsAnyRegister() && LocationOperand::cast(this)->representation() ==
                                MachineRepresentation::kSimd128;
}
References v8::internal::compiler::LocationOperand::cast(), IsAnyRegister(), v8::internal::kSimd128, and v8::internal::compiler::LocationOperand::representation().
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::anonymous_namespace{code-generator-arm64.cc}::EmitFpOrNeonUnop(), GetCanonicalizedValue(), v8::internal::compiler::LocationOperand::GetSimd128Register(), v8::internal::compiler::LocationOperand::IsCompatible(), v8::internal::compiler::operator<<(), and v8::internal::compiler::GraphC1Visualizer::PrintLiveRange().
IsSimd128StackSlot()
bool v8::internal::compiler::InstructionOperand::IsSimd128StackSlot () const [inline]
Definition at line 717 of file instruction.h.
                                                  {
  return IsAnyLocationOperand() &&
         LocationOperand::cast(this)->location_kind() ==
             LocationOperand::STACK_SLOT &&
         LocationOperand::cast(this)->representation() ==
             MachineRepresentation::kSimd128;
}
References v8::internal::compiler::LocationOperand::cast(), IsAnyLocationOperand(), v8::internal::kSimd128, v8::internal::compiler::LocationOperand::location_kind(), v8::internal::compiler::LocationOperand::representation(), and v8::internal::compiler::LocationOperand::STACK_SLOT.
Referenced by v8::internal::compiler::CodeGenerator::AssembleMove(), v8::internal::compiler::CodeGenerator::AssembleSwap(), and v8::internal::compiler::LocationOperand::IsCompatible().
IsSimd256Register()
bool v8::internal::compiler::InstructionOperand::IsSimd256Register () const [inline]
Definition at line 680 of file instruction.h.
                                                 {
  return IsAnyRegister() && LocationOperand::cast(this)->representation() ==
                                MachineRepresentation::kSimd256;
}
References v8::internal::compiler::LocationOperand::cast(), IsAnyRegister(), v8::internal::kSimd256, and v8::internal::compiler::LocationOperand::representation().
Referenced by v8::internal::compiler::operator<<(), v8::internal::compiler::GraphC1Visualizer::PrintLiveRange(), and v8::internal::compiler::InstructionOperandConverter::ToSimd128Register().
IsSimd256StackSlot()
bool v8::internal::compiler::InstructionOperand::IsSimd256StackSlot () const [inline]
Definition at line 725 of file instruction.h.
                                                  {
  return IsAnyLocationOperand() &&
         LocationOperand::cast(this)->location_kind() ==
             LocationOperand::STACK_SLOT &&
         LocationOperand::cast(this)->representation() ==
             MachineRepresentation::kSimd256;
}
References v8::internal::compiler::LocationOperand::cast(), IsAnyLocationOperand(), v8::internal::kSimd256, v8::internal::compiler::LocationOperand::location_kind(), v8::internal::compiler::LocationOperand::representation(), and v8::internal::compiler::LocationOperand::STACK_SLOT.
IsStackSlot()
bool v8::internal::compiler::InstructionOperand::IsStackSlot () const [inline]
Definition at line 691 of file instruction.h.
                                           {
  return IsAnyStackSlot() &&
         !IsFloatingPoint(LocationOperand::cast(this)->representation());
}
References v8::internal::compiler::LocationOperand::cast(), IsAnyStackSlot(), and v8::internal::IsFloatingPoint().
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand(), v8::internal::maglev::detail::AlreadyInARegister(), v8::internal::compiler::CodeGenerator::AssembleMove(), v8::internal::compiler::CodeGenerator::AssembleSwap(), v8::internal::compiler::RegisterAllocatorVerifier::CheckConstraint(), v8::internal::compiler::BlockAssessments::CheckReferenceMap(), v8::internal::compiler::LiveRange::ConvertUsesToOperand(), v8::internal::maglev::MaglevAssembler::FromAnyToRegister(), v8::internal::compiler::CodeGenerator::GetPushCompatibleMoves(), v8::internal::compiler::HasStackSlotInput(), v8::internal::compiler::UsePosition::HintTypeForOperand(), v8::internal::compiler::LocationOperand::index(), v8::internal::compiler::anonymous_namespace{code-generator-loong64.cc}::Is32BitOperand(), v8::internal::compiler::anonymous_namespace{code-generator-mips64.cc}::Is32BitOperand(), v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::Is32BitOperand(), v8::internal::compiler::LocationOperand::IsCompatible(), v8::internal::maglev::MaglevAssembler::IsRootConstant(), v8::internal::compiler::anonymous_namespace{move-optimizer.cc}::IsSlot(), v8::internal::compiler::BlockAssessments::IsStaleReferenceStackSlot(), v8::internal::compiler::CodeGenerator::IsValidPush(), v8::internal::compiler::ConstraintBuilder::MeetConstraintsAfter(), v8::internal::compiler::ConstraintBuilder::MeetRegisterConstraintsForLastInstructionInBlock(), v8::internal::compiler::CodeGenerator::MoveTempLocationTo(), v8::internal::compiler::CodeGenerator::MoveToTempLocation(), v8::internal::compiler::operator<<(), v8::internal::compiler::CodeGenerator::Pop(), v8::internal::compiler::ReferenceMapPopulator::PopulateReferenceMaps(), v8::internal::compiler::CodeGenerator::Push(), v8::internal::maglev::detail::PushInput(), v8::internal::compiler::ReferenceMap::RecordReference(), v8::internal::compiler::CodeGenerator::SetPendingMove(), v8::internal::compiler::ArmOperandConverter::ToMemOperand(), v8::internal::compiler::Loong64OperandConverter::ToMemOperand(), v8::internal::compiler::MipsOperandConverter::ToMemOperand(), v8::internal::compiler::PPCOperandConverter::ToMemOperand(), v8::internal::compiler::RiscvOperandConverter::ToMemOperand(), v8::internal::compiler::S390OperandConverter::ToMemOperand(), v8::internal::compiler::Arm64OperandConverter::ToMemOperand(), v8::internal::compiler::IA32OperandConverter::ToOperand(), v8::internal::compiler::X64OperandConverter::ToOperand(), and v8::internal::maglev::detail::ToRegister().
kind()
Kind v8::internal::compiler::InstructionOperand::kind () const [inline]
Definition at line 66 of file instruction.h.
{ return KindField::decode(value_); }
Referenced by v8::internal::compiler::AddOperandToStateValueDescriptor(), v8::internal::compiler::UsePosition::HintTypeForOperand(), InterferesWith(), IsAnyLocationOperand(), v8::internal::compiler::AllocatedOperand::New(), and v8::internal::compiler::operator<<().
New()
template<typename SubKindOperand >
static SubKindOperand* v8::internal::compiler::InstructionOperand::New (Zone * zone, const SubKindOperand & op) [inline], [static]
Definition at line 111 of file instruction.h.
                                                                   {
    return zone->New<SubKindOperand>(op);
  }
References v8::internal::Zone::New().
Referenced by v8::internal::compiler::ImmediateOperand::New(), v8::internal::compiler::ConstantOperand::New(), v8::internal::compiler::AllocatedOperand::New(), and v8::internal::compiler::PendingOperand::New().
operator!=()
bool v8::internal::compiler::InstructionOperand::operator!= (const InstructionOperand & other) const [inline]
Definition at line 153 of file instruction.h.
                                                         {
    return !Equals(other);
  }
References v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::Equals().
operator==()
bool v8::internal::compiler::InstructionOperand::operator== (const InstructionOperand & other) const [inline]
Definition at line 150 of file instruction.h.
                                                         {
    return Equals(other);
  }
References v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::Equals().
Print()
void v8::internal::compiler::InstructionOperand::Print () const
Definition at line 163 of file instruction.cc.
{ StdoutStream{} << *this << std::endl; }
ReplaceWith()
static void v8::internal::compiler::InstructionOperand::ReplaceWith (InstructionOperand * dest, const InstructionOperand * src) [inline], [static]
Definition at line 115 of file instruction.h.
                                                         {
    *dest = *src;
  }
Referenced by v8::internal::compiler::ConstraintBuilder::AllocateFixed(), v8::internal::compiler::RegisterAllocationData::PhiMapValue::CommitAssignment(), and v8::internal::compiler::LiveRange::ConvertUsesToOperand().
Member Data Documentation
kInvalidVirtualRegister
const int v8::internal::compiler::InstructionOperand::kInvalidVirtualRegister = -1 [static]
Definition at line 50 of file instruction.h.
Referenced by v8::internal::compiler::ConstraintBuilder::AllocateFixed(), v8::internal::compiler::RegisterAllocatorVerifier::BuildConstraint(), v8::internal::compiler::InstructionSelector::GetRename(), v8::internal::compiler::InstructionSelector::GetVirtualRegister(), v8::internal::compiler::InstructionSelector::GetVirtualRegistersForTesting(), v8::internal::compiler::InstructionSequence::NextVirtualRegister(), v8::internal::compiler::PhiInstruction::RenameInput(), v8::internal::compiler::PhiInstruction::SetInput(), v8::internal::compiler::InstructionSelector::SetRename(), v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::compiler::UnallocatedOperand::UnallocatedOperand(), v8::internal::compiler::RegisterAllocatorVerifier::VerifyInput(), and v8::internal::compiler::RegisterAllocatorVerifier::VerifyOutput().
value_
uint64_t v8::internal::compiler::InstructionOperand::value_ [protected]
Definition at line 164 of file instruction.h.
Referenced by v8::internal::compiler::UnallocatedOperand::basic_policy(), Compare(), v8::internal::compiler::ConstantOperand::ConstantOperand(), Equals(), v8::internal::compiler::UnallocatedOperand::extended_policy(), v8::internal::compiler::Constant::FitsInInt32(), v8::internal::compiler::UnallocatedOperand::fixed_register_index(), v8::internal::compiler::UnallocatedOperand::fixed_slot_index(), GetCanonicalizedValue(), v8::internal::compiler::UnallocatedOperand::GetSecondaryStorage(), v8::internal::compiler::UnallocatedOperand::HasSecondaryStorage(), v8::internal::compiler::ImmediateOperand::ImmediateOperand(), v8::internal::compiler::LocationOperand::index(), v8::internal::compiler::ImmediateOperand::indexed_value(), v8::internal::compiler::ImmediateOperand::inline_int32_value(), v8::internal::compiler::ImmediateOperand::inline_int64_value(), v8::internal::compiler::UnallocatedOperand::input_index(), v8::internal::compiler::UnallocatedOperand::IsUsedAtStart(), v8::internal::compiler::LocationOperand::location_kind(), v8::internal::compiler::LocationOperand::LocationOperand(), v8::internal::compiler::PendingOperand::next(), v8::internal::compiler::LocationOperand::register_code(), v8::internal::compiler::LocationOperand::representation(), v8::internal::compiler::PendingOperand::set_next(), v8::internal::compiler::Constant::ToExternalReference(), v8::internal::compiler::Constant::ToFloat32(), v8::internal::compiler::Constant::ToFloat32AsInt(), v8::internal::compiler::Constant::ToFloat32Safe(), v8::internal::compiler::Constant::ToFloat64(), v8::internal::compiler::Constant::ToInt32(), v8::internal::compiler::Constant::ToInt64(), v8::internal::compiler::Constant::ToRpoNumber(), v8::internal::compiler::ImmediateOperand::type(), v8::internal::compiler::UnallocatedOperand::UnallocatedOperand(), v8::internal::compiler::UnallocatedOperand::virtual_register(), and v8::internal::compiler::ConstantOperand::virtual_register().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/instruction.h
/mnt/V8SourceCode/src/compiler/backend/instruction.cc