v8::internal::compiler::CommonNodeCache Class Reference
#include <common-node-cache.h>
Public Member Functions
CommonNodeCache (Zone *zone)
~CommonNodeCache ()=default
CommonNodeCache (const CommonNodeCache &)=delete
CommonNodeCache & operator= (const CommonNodeCache &)=delete
Node ** FindInt32Constant (int32_t value)
Node ** FindInt64Constant (int64_t value)
Node ** FindTaggedIndexConstant (int32_t value)
Node ** FindFloat32Constant (float value)
Node ** FindFloat64Constant (double value)
Node ** FindExternalConstant (ExternalReference value)
Node ** FindPointerConstant (intptr_t value)
Node ** FindNumberConstant (double value)
Node ** FindHeapConstant (Handle< HeapObject > value)
Node ** FindRelocatableInt32Constant (int32_t value, RelocInfoMode rmode)
Node ** FindRelocatableInt64Constant (int64_t value, RelocInfoMode rmode)
void GetCachedNodes (ZoneVector< Node * > *nodes)
Private Attributes
Int32NodeCache int32_constants_
Int64NodeCache int64_constants_
Int32NodeCache tagged_index_constants_
Int32NodeCache float32_constants_
Int64NodeCache float64_constants_
IntPtrNodeCache external_constants_
IntPtrNodeCache pointer_constants_
Int64NodeCache number_constants_
IntPtrNodeCache heap_constants_
RelocInt32NodeCache relocatable_int32_constants_
RelocInt64NodeCache relocatable_int64_constants_
Detailed Description
Definition at line 15 of file common-node-cache.h.
Constructor & Destructor Documentation
CommonNodeCache() [1/2]
v8::internal::compiler::CommonNodeCache::CommonNodeCache (Zone * zone) [inline], [explicit]
Definition at line 17 of file common-node-cache.h.
      : int32_constants_(zone),
        int64_constants_(zone),
        tagged_index_constants_(zone),
        float32_constants_(zone),
        float64_constants_(zone),
        external_constants_(zone),
        pointer_constants_(zone),
        number_constants_(zone),
        heap_constants_(zone),
        relocatable_int32_constants_(zone),
        relocatable_int64_constants_(zone) {}
 CommonNodeCache()
v8::internal::compiler::CommonNodeCache::~CommonNodeCache () [default]
CommonNodeCache() [2/2]
v8::internal::compiler::CommonNodeCache::CommonNodeCache (const CommonNodeCache &) [delete]
Member Function Documentation
FindExternalConstant()
Node ** v8::internal::compiler::CommonNodeCache::FindExternalConstant (ExternalReference value)
Definition at line 14 of file common-node-cache.cc.
                                                                    {
  return external_constants_.Find(base::bit_cast<intptr_t>(value.raw()));
}
References external_constants_, and v8::internal::value.
Referenced by v8::internal::compiler::MachineGraph::ExternalConstant().
FindFloat32Constant()
Node** v8::internal::compiler::CommonNodeCache::FindFloat32Constant (float value) [inline]
Definition at line 46 of file common-node-cache.h.
                                          {
    // We canonicalize float constants at the bit representation level.
    return float32_constants_.Find(base::bit_cast<int32_t>(value));
  }
References float32_constants_, and v8::internal::value.
Referenced by v8::internal::compiler::MachineGraph::Float32Constant().
FindFloat64Constant()
Node** v8::internal::compiler::CommonNodeCache::FindFloat64Constant (double value) [inline]
Definition at line 51 of file common-node-cache.h.
                                           {
    // We canonicalize double constants at the bit representation level.
    return float64_constants_.Find(base::bit_cast<int64_t>(value));
  }
References float64_constants_, and v8::internal::value.
Referenced by v8::internal::compiler::MachineGraph::Float64Constant().
FindHeapConstant()
Node ** v8::internal::compiler::CommonNodeCache::FindHeapConstant (Handle< HeapObject > value)
Definition at line 19 of file common-node-cache.cc.
                                                                 {
  return heap_constants_.Find(base::bit_cast<intptr_t>(value.address()));
}
References heap_constants_, and v8::internal::value.
Referenced by v8::internal::compiler::JSGraph::HeapConstantHole(), v8::internal::compiler::JSGraph::HeapConstantMaybeHole(), and v8::internal::compiler::JSGraph::HeapConstantNoHole().
FindInt32Constant()
Node** v8::internal::compiler::CommonNodeCache::FindInt32Constant (int32_t value) [inline]
Definition at line 34 of file common-node-cache.h.
                                          {
    return int32_constants_.Find(value);
  }
References int32_constants_, and v8::internal::value.
Referenced by v8::internal::compiler::MachineGraph::Int32Constant().
FindInt64Constant()
Node** v8::internal::compiler::CommonNodeCache::FindInt64Constant (int64_t value) [inline]
Definition at line 38 of file common-node-cache.h.
                                          {
    return int64_constants_.Find(value);
  }
References int64_constants_, and v8::internal::value.
Referenced by v8::internal::compiler::MachineGraph::Int64Constant().
FindNumberConstant()
Node** v8::internal::compiler::CommonNodeCache::FindNumberConstant (double value) [inline]
Definition at line 62 of file common-node-cache.h.
                                          {
    // We canonicalize double constants at the bit representation level.
    return number_constants_.Find(base::bit_cast<int64_t>(value));
  }
References number_constants_, and v8::internal::value.
Referenced by v8::internal::compiler::JSGraph::NumberConstant().
FindPointerConstant()
Node** v8::internal::compiler::CommonNodeCache::FindPointerConstant (intptr_t value) [inline]
Definition at line 58 of file common-node-cache.h.
                                             {
    return pointer_constants_.Find(value);
  }
References pointer_constants_, and v8::internal::value.
Referenced by v8::internal::compiler::MachineGraph::PointerConstant().
FindRelocatableInt32Constant()
Node** v8::internal::compiler::CommonNodeCache::FindRelocatableInt32Constant (int32_t value, RelocInfoMode rmode) [inline]
Definition at line 69 of file common-node-cache.h.
                                                                          {
    return relocatable_int32_constants_.Find(std::make_pair(value, rmode));
  }
References relocatable_int32_constants_, and v8::internal::value.
Referenced by v8::internal::compiler::MachineGraph::RelocatableInt32Constant().
FindRelocatableInt64Constant()
Node** v8::internal::compiler::CommonNodeCache::FindRelocatableInt64Constant (int64_t value, RelocInfoMode rmode) [inline]
Definition at line 73 of file common-node-cache.h.
                                                                          {
    return relocatable_int64_constants_.Find(std::make_pair(value, rmode));
  }
References relocatable_int64_constants_, and v8::internal::value.
Referenced by v8::internal::compiler::MachineGraph::RelocatableInt64Constant().
FindTaggedIndexConstant()
Node** v8::internal::compiler::CommonNodeCache::FindTaggedIndexConstant (int32_t value) [inline]
Definition at line 42 of file common-node-cache.h.
                                                {
    return tagged_index_constants_.Find(value);
  }
References tagged_index_constants_, and v8::internal::value.
Referenced by v8::internal::compiler::MachineGraph::TaggedIndexConstant().
GetCachedNodes()
void v8::internal::compiler::CommonNodeCache::GetCachedNodes (ZoneVector< Node * > * nodes)
Definition at line 24 of file common-node-cache.cc.
                                                             {
  int32_constants_.GetCachedNodes(nodes);
  int64_constants_.GetCachedNodes(nodes);
  tagged_index_constants_.GetCachedNodes(nodes);
  float32_constants_.GetCachedNodes(nodes);
  float64_constants_.GetCachedNodes(nodes);
  external_constants_.GetCachedNodes(nodes);
  pointer_constants_.GetCachedNodes(nodes);
  number_constants_.GetCachedNodes(nodes);
  heap_constants_.GetCachedNodes(nodes);
  relocatable_int32_constants_.GetCachedNodes(nodes);
  relocatable_int64_constants_.GetCachedNodes(nodes);
}
References external_constants_, float32_constants_, float64_constants_, heap_constants_, int32_constants_, int64_constants_, number_constants_, pointer_constants_, relocatable_int32_constants_, relocatable_int64_constants_, and tagged_index_constants_.
Referenced by v8::internal::compiler::JSGraph::GetCachedNodes().
operator=()
CommonNodeCache& v8::internal::compiler::CommonNodeCache::operator= (const CommonNodeCache &) [delete]
Member Data Documentation
external_constants_
IntPtrNodeCache v8::internal::compiler::CommonNodeCache::external_constants_ [private]
Definition at line 86 of file common-node-cache.h.
Referenced by FindExternalConstant(), and GetCachedNodes().
float32_constants_
Int32NodeCache v8::internal::compiler::CommonNodeCache::float32_constants_ [private]
Definition at line 84 of file common-node-cache.h.
Referenced by FindFloat32Constant(), and GetCachedNodes().
float64_constants_
Int64NodeCache v8::internal::compiler::CommonNodeCache::float64_constants_ [private]
Definition at line 85 of file common-node-cache.h.
Referenced by FindFloat64Constant(), and GetCachedNodes().
heap_constants_
IntPtrNodeCache v8::internal::compiler::CommonNodeCache::heap_constants_ [private]
Definition at line 89 of file common-node-cache.h.
Referenced by FindHeapConstant(), and GetCachedNodes().
int32_constants_
Int32NodeCache v8::internal::compiler::CommonNodeCache::int32_constants_ [private]
Definition at line 81 of file common-node-cache.h.
Referenced by FindInt32Constant(), and GetCachedNodes().
int64_constants_
Int64NodeCache v8::internal::compiler::CommonNodeCache::int64_constants_ [private]
Definition at line 82 of file common-node-cache.h.
Referenced by FindInt64Constant(), and GetCachedNodes().
number_constants_
Int64NodeCache v8::internal::compiler::CommonNodeCache::number_constants_ [private]
Definition at line 88 of file common-node-cache.h.
Referenced by FindNumberConstant(), and GetCachedNodes().
pointer_constants_
IntPtrNodeCache v8::internal::compiler::CommonNodeCache::pointer_constants_ [private]
Definition at line 87 of file common-node-cache.h.
Referenced by FindPointerConstant(), and GetCachedNodes().
relocatable_int32_constants_
RelocInt32NodeCache v8::internal::compiler::CommonNodeCache::relocatable_int32_constants_ [private]
Definition at line 90 of file common-node-cache.h.
Referenced by FindRelocatableInt32Constant(), and GetCachedNodes().
relocatable_int64_constants_
RelocInt64NodeCache v8::internal::compiler::CommonNodeCache::relocatable_int64_constants_ [private]
Definition at line 91 of file common-node-cache.h.
Referenced by FindRelocatableInt64Constant(), and GetCachedNodes().
tagged_index_constants_
Int32NodeCache v8::internal::compiler::CommonNodeCache::tagged_index_constants_ [private]
Definition at line 83 of file common-node-cache.h.
Referenced by FindTaggedIndexConstant(), and GetCachedNodes().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/common-node-cache.h
/mnt/V8SourceCode/src/compiler/common-node-cache.cc