v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData > Class Template Reference
#include <snapshot-table.h>
Classes
struct LogEntry
class MaybeSnapshot
class Snapshot
struct SnapshotData
Public Types
using TableEntry = SnapshotTableEntry< Value, KeyData >
using Key = SnapshotTableKey< Value, KeyData >
Public Member Functions
template<class ChangeCallback = NoChangeCallback>
void StartNewSnapshot (base::Vector< const Snapshot > predecessors, const ChangeCallback &change_callback={}) requires(std
template<class ChangeCallback = NoChangeCallback>
void StartNewSnapshot (std::initializer_list< Snapshot > predecessors={}, const ChangeCallback &change_callback={}) requires(std
template<class ChangeCallback = NoChangeCallback>
void StartNewSnapshot (Snapshot parent, const ChangeCallback &change_callback={}) requires(std
template<class MergeFun , class ChangeCallback = NoChangeCallback>
void StartNewSnapshot (base::Vector< const Snapshot > predecessors, const MergeFun &merge_fun, const ChangeCallback &change_callback={}) requires(std
template<class MergeFun , class ChangeCallback = NoChangeCallback>
void StartNewSnapshot (std::initializer_list< Snapshot > predecessors, const MergeFun &merge_fun, const ChangeCallback &change_callback={}) requires(std
Snapshot Seal ()
const Value & Get (Key key) const
const Value & GetPredecessorValue (Key key, int predecessor_index)
bool Set (Key key, Value new_value)
SnapshotTable (Zone *zone)
Key NewKey (KeyData data, Value initial_value=Value{})
Key NewKey (Value initial_value=Value{})
bool IsSealed ()
Private Member Functions
SnapshotData & NewSnapshot (SnapshotData *parent)
base::Vector< LogEntry > LogEntries (SnapshotData *s)
template<class ChangeCallback = NoChangeCallback>
void RevertCurrentSnapshot (ChangeCallback &change_callback)
template<class ChangeCallback = NoChangeCallback>
void ReplaySnapshot (SnapshotData *snapshot, ChangeCallback &change_callback)
void RecordMergeValue (TableEntry &entry, const Value &value, uint32_t predecessor_index, uint32_t predecessor_count)
template<class ChangeCallback >
SnapshotData & MoveToNewSnapshot (base::Vector< const Snapshot > predecessors, const ChangeCallback &change_callback)
template<class MergeFun , class ChangeCallback >
void MergePredecessors (base::Vector< const Snapshot > predecessors, const MergeFun &merge_fun, const ChangeCallback &change_callback)
Private Attributes
Zone * zone_
ZoneDeque< TableEntry > table_ {zone_}
ZoneDeque< SnapshotData > snapshots_ {zone_}
ZoneVector< LogEntry > log_ {zone_}
SnapshotData * root_snapshot_
SnapshotData * current_snapshot_
ZoneVector< TableEntry * > merging_entries_ {zone_}
ZoneVector< Value > merge_values_ {zone_}
ZoneVector< SnapshotData * > path_ {zone_}
Static Private Attributes
static constexpr uint32_t kNoMergeOffset
static constexpr uint32_t kNoMergedPredecessor
Detailed Description
template<class Value, class KeyData = NoKeyData>
class v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >
Definition at line 92 of file snapshot-table.h.
Member Typedef Documentation
Key
template<class Value , class KeyData = NoKeyData>
using v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Key = SnapshotTableKey<Value, KeyData>
Definition at line 99 of file snapshot-table.h.
TableEntry
template<class Value , class KeyData = NoKeyData>
using v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::TableEntry = SnapshotTableEntry<Value, KeyData>
Definition at line 98 of file snapshot-table.h.
Constructor & Destructor Documentation
SnapshotTable()
template<class Value , class KeyData = NoKeyData>
v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::SnapshotTable (Zone * zone) [inline], [explicit]
Definition at line 247 of file snapshot-table.h.
                                     : zone_(zone) {
    root_snapshot_ = &NewSnapshot(nullptr);
    root_snapshot_->Seal(0);
    current_snapshot_ = root_snapshot_;
  }
References v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::current_snapshot_, v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::NewSnapshot(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::root_snapshot_, and v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::SnapshotData::Seal().
Member Function Documentation
Get()
template<class Value , class KeyData = NoKeyData>
const Value& v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Get (Key key) const [inline]
Definition at line 222 of file snapshot-table.h.
{ return key.entry_->value; }
References v8::internal::key.
Referenced by v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::Bind(), v8::internal::maglev::MaglevPhiRepresentationSelector::EnsurePhiTagged(), v8::internal::compiler::turboshaft::MemoryContentTable::Find(), v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::FindImpl(), v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::Get(), v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::GetObservability(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::GetPredecessorValue(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::GetTypeOrInvalid(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::GetTypeOrInvalid(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::GetVariable(), v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::MarkAllStoresAsGCObservable(), v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::Print(), and v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< Derived, Value, KeyData >::Set().
GetPredecessorValue()
template<class Value , class KeyData = NoKeyData>
const Value& v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::GetPredecessorValue (Key key, int predecessor_index) [inline]
Definition at line 231 of file snapshot-table.h.
                                                                   {
    DCHECK(!current_snapshot_->IsSealed());
    DCHECK(snapshot_was_created_with_merge);
    if (key.entry_->merge_offset == kNoMergeOffset) return Get(key);
    return merge_values_[key.entry_->merge_offset + predecessor_index];
  }
References v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::current_snapshot_, v8::internal::DCHECK(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Get(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::SnapshotData::IsSealed(), v8::internal::key, v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::kNoMergeOffset, and v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::merge_values_.
Referenced by v8::internal::maglev::MaglevPhiRepresentationSelector::EnsurePhiTagged(), v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::GetPredecessorValue(), and v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::GetPredecessorValue().
IsSealed()
template<class Value , class KeyData = NoKeyData>
bool v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::IsSealed () [inline]
Definition at line 266 of file snapshot-table.h.
{ return current_snapshot_->IsSealed(); }
References v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::current_snapshot_, and v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::SnapshotData::IsSealed().
Referenced by v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::BeginBlock(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Bind(), v8::internal::maglev::MaglevPhiRepresentationSelector::PreparePhiTaggings(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::RestoreTemporaryVariableSnapshotAfter(), v8::internal::compiler::turboshaft::RedundantStoreAnalysis::Run(), v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::Seal(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::SnapshotData::Seal(), and v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::SealAndSaveVariableSnapshot().
LogEntries()
template<class Value , class KeyData = NoKeyData>
base::Vector<LogEntry> v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::LogEntries (SnapshotData * s) [inline], [private]
Definition at line 295 of file snapshot-table.h.
                                                   {
    return base::VectorOf(&log_[s->log_begin], s->log_end - s->log_begin);
  }
References v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::log_, v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::SnapshotData::log_begin, v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::SnapshotData::log_end, and v8::base::VectorOf().
Referenced by v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::ReplaySnapshot(), and v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::RevertCurrentSnapshot().
MergePredecessors()
template<class Value , class KeyData >
template<class MergeFun , class ChangeCallback >
void v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::MergePredecessors (base::Vector< const Snapshot > predecessors, const MergeFun & merge_fun, const ChangeCallback & change_callback) [private]
Definition at line 469 of file snapshot-table.h.
                                           {
  CHECK_LE(predecessors.size(), std::numeric_limits<uint32_t>::max());
  uint32_t predecessor_count = static_cast<uint32_t>(predecessors.size());
  if (predecessor_count < 1) return;
  // The merging works by reserving `predecessor_count` many slots in
  // `merge_values_` for every key that we find while going through the
  // predecessor logs. There, we place the values of the corresponding
  // predecessors, so that we can finally call the `merge_fun` by creating a
  // `base::Vector` pointing to the collected values inside of `merge_values_`.
  DCHECK(merge_values_.empty());
  DCHECK(merging_entries_.empty());
  SnapshotData* common_ancestor = current_snapshot_->parent;
  // Collect all the entries that require merging. For this, we walk the logs of
  // the predecessors backwards until reaching the common ancestor.
  for (uint32_t i = 0; i < predecessor_count; ++i) {
    for (SnapshotData* predecessor = predecessors[i].data_;
         predecessor != common_ancestor; predecessor = predecessor->parent) {
      base::Vector<LogEntry> log_entries = LogEntries(predecessor);
      for (const LogEntry& entry : base::Reversed(log_entries)) {
        RecordMergeValue(entry.table_entry, entry.new_value, i,
                         predecessor_count);
      }
    }
  }
  // Actually perform the merging by calling the merge function and modifying
  // the table.
  for (TableEntry* entry : merging_entries_) {
    Key key{*entry};
    Value value = merge_fun(
        key, base::VectorOf<const Value>(&merge_values_[entry->merge_offset],
                                         predecessor_count));
    Value old_value = entry->value;
    if (Set(key, std::move(value))) {
      change_callback(key, old_value, entry->value);
    }
  }
}
References CHECK_LE, v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::key, v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::SnapshotData::parent, v8::base::Reversed(), v8::base::Vector< T >::size(), and v8::internal::value.
MoveToNewSnapshot()
template<class Value , class KeyData >
template<class ChangeCallback >
SnapshotTable< Value, KeyData >::SnapshotData & v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::MoveToNewSnapshot (base::Vector< const Snapshot > predecessors, const ChangeCallback & change_callback) [private]
Definition at line 428 of file snapshot-table.h.
                                           {
  DCHECK_WITH_MSG(
      current_snapshot_->IsSealed(),
      "A new Snapshot was opened before the previous Snapshot was sealed");
  SnapshotData* common_ancestor;
  if (predecessors.empty()) {
    common_ancestor = root_snapshot_;
  } else {
    common_ancestor = predecessors.first().data_;
    for (Snapshot s : predecessors.SubVectorFrom(1)) {
      common_ancestor = common_ancestor->CommonAncestor(s.data_);
    }
  }
  SnapshotData* go_back_to = common_ancestor->CommonAncestor(current_snapshot_);
  while (current_snapshot_ != go_back_to) {
    RevertCurrentSnapshot(change_callback);
  }
  {
    // Replay to common_ancestor.
    path_.clear();
    for (SnapshotData* s = common_ancestor; s != go_back_to; s = s->parent) {
      path_.push_back(s);
    }
    for (SnapshotData* s : base::Reversed(path_)) {
      ReplaySnapshot(s, change_callback);
    }
  }
  DCHECK_EQ(current_snapshot_, common_ancestor);
  SnapshotData& new_snapshot = NewSnapshot(common_ancestor);
  current_snapshot_ = &new_snapshot;
  return new_snapshot;
}
References v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::SnapshotData::CommonAncestor(), DCHECK_EQ, DCHECK_WITH_MSG, v8::base::Vector< T >::empty(), v8::base::Vector< T >::first(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::SnapshotData::parent, v8::base::Reversed(), and v8::base::Vector< T >::SubVectorFrom().
NewKey() [1/2]
template<class Value , class KeyData = NoKeyData>
Key v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::NewKey (KeyData data, Value initial_value = Value{}) [inline]
Definition at line 257 of file snapshot-table.h.
                                                      {}) {
    return Key{table_.emplace_back(
        TableEntry{std::move(initial_value), std::move(data)})};
  }
Referenced by v8::internal::maglev::MaglevPhiRepresentationSelector::EnsurePhiTagged(), v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::GetOrCreateKey(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::SetType(), and v8::internal::compiler::turboshaft::TypeInferenceAnalysis::SetType().
NewKey() [2/2]
template<class Value , class KeyData = NoKeyData>
Key v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::NewKey (Value initial_value = Value{}) [inline]
Definition at line 261 of file snapshot-table.h.
                                        {}) {
    return NewKey(KeyData{}, initial_value);
  }
NewSnapshot()
template<class Value , class KeyData = NoKeyData>
SnapshotData& v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::NewSnapshot (SnapshotData * parent) [inline], [private]
Definition at line 291 of file snapshot-table.h.
                                                  {
    return snapshots_.emplace_back(parent, log_.size());
  }
References v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::log_, and v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::snapshots_.
Referenced by v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::SnapshotTable().
RecordMergeValue()
template<class Value , class KeyData >
void v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::RecordMergeValue (TableEntry & entry, const Value & value, uint32_t predecessor_index, uint32_t predecessor_count) [private]
Definition at line 380 of file snapshot-table.h.
                                {
  if (predecessor_index == entry.last_merged_predecessor) {
    DCHECK_NE(entry.merge_offset, kNoMergeOffset);
    // We already recorded a later value for this predecessor, so we should skip
    // earlier values.
    return;
  }
  if (entry.merge_offset == kNoMergeOffset) {
    // Allocate space for the merge values. All the merge values are initialized
    // to the value from the parent snapshot. This way, we get the right value
    // for predecessors that did not change the value.
    DCHECK_EQ(entry.last_merged_predecessor, kNoMergedPredecessor);
    CHECK_LE(merge_values_.size() + predecessor_count,
             std::numeric_limits<uint32_t>::max());
    entry.merge_offset = static_cast<uint32_t>(merge_values_.size());
    merging_entries_.push_back(&entry);
    merge_values_.insert(merge_values_.end(), predecessor_count, entry.value);
  }
  merge_values_[entry.merge_offset + predecessor_index] = value;
  entry.last_merged_predecessor = predecessor_index;
}
References CHECK_LE, DCHECK_EQ, DCHECK_NE, v8::internal::compiler::turboshaft::SnapshotTableEntry< Value, KeyData >::last_merged_predecessor, v8::internal::compiler::turboshaft::SnapshotTableEntry< Value, KeyData >::merge_offset, v8::internal::compiler::turboshaft::SnapshotTableEntry< Value, KeyData >::value, and v8::internal::value.
ReplaySnapshot()
template<class Value , class KeyData = NoKeyData>
template<class ChangeCallback = NoChangeCallback>
void v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::ReplaySnapshot (SnapshotData * snapshot, ChangeCallback & change_callback) [inline], [private]
Definition at line 314 of file snapshot-table.h.
                                                                               {
    DCHECK_EQ(snapshot->parent, current_snapshot_);
    for (const LogEntry& entry : LogEntries(snapshot)) {
      DCHECK_EQ(entry.table_entry.value, entry.old_value);
      DCHECK_NE(entry.new_value, entry.old_value);
      change_callback(Key{entry.table_entry}, entry.old_value, entry.new_value);
      entry.table_entry.value = entry.new_value;
    }
    current_snapshot_ = snapshot;
  }
References v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::current_snapshot_, DCHECK_EQ, DCHECK_NE, v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::LogEntries(), and v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::SnapshotData::parent.
RevertCurrentSnapshot()
template<class Value , class KeyData = NoKeyData>
template<class ChangeCallback = NoChangeCallback>
void v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::RevertCurrentSnapshot (ChangeCallback & change_callback) [inline], [private]
Definition at line 300 of file snapshot-table.h.
                                                              {
    DCHECK(current_snapshot_->IsSealed());
    base::Vector<LogEntry> log_entries = LogEntries(current_snapshot_);
    for (const LogEntry& entry : base::Reversed(log_entries)) {
      DCHECK_EQ(entry.table_entry.value, entry.new_value);
      DCHECK_NE(entry.new_value, entry.old_value);
      change_callback(Key{entry.table_entry}, entry.new_value, entry.old_value);
      entry.table_entry.value = entry.old_value;
    }
    current_snapshot_ = current_snapshot_->parent;
    DCHECK_NOT_NULL(current_snapshot_);
  }
References v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::current_snapshot_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, DCHECK_NOT_NULL, v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::SnapshotData::IsSealed(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::LogEntries(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::SnapshotData::parent, and v8::base::Reversed().
Seal()
template<class Value , class KeyData = NoKeyData>
Snapshot v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Seal () [inline]
Definition at line 199 of file snapshot-table.h.
                  {
    current_snapshot_->Seal(log_.size());
    // Reseting the entries' `merge_offset` and `last_merged_predecessor`
    // fields, so that they are cleared for the next Merge.
    for (TableEntry* entry : merging_entries_) {
      entry->last_merged_predecessor = kNoMergedPredecessor;
      entry->merge_offset = kNoMergeOffset;
    }
    merge_values_.clear();
    merging_entries_.clear();
    // Optimization: If nothing changed in the new snapshot, we discard it and
    // use its parent instead.
    if (current_snapshot_->log_begin == current_snapshot_->log_end) {
      SnapshotData* parent = current_snapshot_->parent;
      DCHECK_EQ(current_snapshot_, &snapshots_.back());
      snapshots_.pop_back();
      current_snapshot_ = parent;
      return Snapshot{*parent};
    }
    return Snapshot{*current_snapshot_};
  }
References v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::current_snapshot_, DCHECK_EQ, v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::kNoMergedPredecessor, v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::kNoMergeOffset, v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::log_, v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::SnapshotData::log_begin, v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::SnapshotData::log_end, v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::merge_values_, v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::merging_entries_, v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::SnapshotData::parent, v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::SnapshotData::Seal(), and v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::snapshots_.
Referenced by v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::BeginBlock(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Bind(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::CloseTemporaryVariableSnapshot(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::FinishBlock(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::FinishBlock(), v8::internal::maglev::MaglevPhiRepresentationSelector::PreparePhiTaggings(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::Run(), v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::Seal(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::SealAndDiscard(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::SealAndDiscard(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::SealAndSaveVariableSnapshot(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::StoreLoopSnapshotInForwardPredecessor(), and v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::StoreLoopSnapshotInForwardPredecessor().
Set()
template<class Value , class KeyData = NoKeyData>
bool v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Set (Key key, Value new_value) [inline]
Definition at line 239 of file snapshot-table.h.
                                     {
    DCHECK(!current_snapshot_->IsSealed());
    if (key.entry_->value == new_value) return false;
    log_.push_back(LogEntry{*key.entry_, key.entry_->value, new_value});
    key.entry_->value = new_value;
    return true;
  }
References v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::current_snapshot_, v8::internal::DCHECK(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::SnapshotData::IsSealed(), v8::internal::key, and v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::log_.
Referenced by v8::internal::maglev::MaglevPhiRepresentationSelector::EnsurePhiTagged(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::RefineOperationType(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::RefineOperationType(), v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< Derived, Value, KeyData >::Set(), v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::Set(), v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< Derived, Value, KeyData >::SetNoNotify(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::SetType(), and v8::internal::compiler::turboshaft::TypeInferenceAnalysis::SetType().
StartNewSnapshot() [1/5]
template<class Value , class KeyData = NoKeyData>
template<class ChangeCallback = NoChangeCallback>
void v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::StartNewSnapshot (base::Vector< const Snapshot > predecessors, const ChangeCallback & change_callback = {}) [inline]
Definition at line 152 of file snapshot-table.h.
                                                                {})
    requires(std::is_invocable_v<ChangeCallback, Key, Value, Value>)
  {
    DCHECK(current_snapshot_->IsSealed());
    MoveToNewSnapshot(predecessors, change_callback);
#ifdef DEBUG
    snapshot_was_created_with_merge = false;
#endif
  }
Referenced by v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::BeginBlock(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::BeginBlock(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Bind(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::CreateMergeSnapshot(), v8::internal::maglev::MaglevPhiRepresentationSelector::PreparePhiTaggings(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::Run(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::Run(), v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< Derived, Value, KeyData >::StartNewSnapshot(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::StartNewSnapshotFor(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::StoreLoopSnapshotInForwardPredecessor(), and v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::StoreLoopSnapshotInForwardPredecessor().
StartNewSnapshot() [2/5]
template<class Value , class KeyData = NoKeyData>
template<class MergeFun , class ChangeCallback = NoChangeCallback>
void v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::StartNewSnapshot (base::Vector< const Snapshot > predecessors, const MergeFun & merge_fun, const ChangeCallback & change_callback = {}) [inline]
Definition at line 177 of file snapshot-table.h.
                                                                {})
    requires(std::is_invocable_v<MergeFun, Key, base::Vector<const Value>> &&
             std::is_invocable_v<ChangeCallback, Key, Value, Value>)
  {
    StartNewSnapshot(predecessors, change_callback);
    MergePredecessors(predecessors, merge_fun, change_callback);
#ifdef DEBUG
    snapshot_was_created_with_merge = true;
#endif
  }
StartNewSnapshot() [3/5]
template<class Value , class KeyData = NoKeyData>
template<class ChangeCallback = NoChangeCallback>
void v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::StartNewSnapshot (Snapshot parent, const ChangeCallback & change_callback = {}) [inline]
Definition at line 170 of file snapshot-table.h.
                                                                {})
    requires(std::is_invocable_v<ChangeCallback, Key, Value, Value>)
  {
    StartNewSnapshot({parent}, change_callback);
  }
StartNewSnapshot() [4/5]
template<class Value , class KeyData = NoKeyData>
template<class MergeFun , class ChangeCallback = NoChangeCallback>
void v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::StartNewSnapshot (std::initializer_list< Snapshot > predecessors, const MergeFun & merge_fun, const ChangeCallback & change_callback = {}) [inline]
Definition at line 190 of file snapshot-table.h.
                                                                {})
    requires(std::is_invocable_v<MergeFun, Key, base::Vector<const Value>> &&
             std::is_invocable_v<ChangeCallback, Key, Value, Value>)
  {
    StartNewSnapshot(base::VectorOf(predecessors), merge_fun, change_callback);
  }
StartNewSnapshot() [5/5]
template<class Value , class KeyData = NoKeyData>
template<class ChangeCallback = NoChangeCallback>
void v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::StartNewSnapshot (std::initializer_list< Snapshot > predecessors = {}, const ChangeCallback & change_callback = {}) [inline]
Definition at line 163 of file snapshot-table.h.
                                                                     {},
                        const ChangeCallback& change_callback = {})
    requires(std::is_invocable_v<ChangeCallback, Key, Value, Value>)
  {
    StartNewSnapshot(base::VectorOf(predecessors), change_callback);
  }
Member Data Documentation
current_snapshot_
template<class Value , class KeyData = NoKeyData>
SnapshotData* v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::current_snapshot_ [private]
Definition at line 277 of file snapshot-table.h.
Referenced by v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::GetPredecessorValue(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::IsSealed(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::ReplaySnapshot(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::RevertCurrentSnapshot(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Seal(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Set(), and v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::SnapshotTable().
kNoMergedPredecessor
template<class Value , class KeyData = NoKeyData>
constexpr uint32_t v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::kNoMergedPredecessor [static], [constexpr], [private]
Initial value:
=
      std::numeric_limits<uint32_t>::max()
Definition at line 337 of file snapshot-table.h.
Referenced by v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Seal().
kNoMergeOffset
template<class Value , class KeyData = NoKeyData>
constexpr uint32_t v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::kNoMergeOffset [static], [constexpr], [private]
Initial value:
=
      std::numeric_limits<uint32_t>::max()
Definition at line 335 of file snapshot-table.h.
Referenced by v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::GetPredecessorValue(), and v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Seal().
log_
template<class Value , class KeyData = NoKeyData>
ZoneVector<LogEntry> v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::log_ {zone_} [private]
Definition at line 275 of file snapshot-table.h.
Referenced by v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::LogEntries(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::NewSnapshot(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Seal(), and v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Set().
merge_values_
template<class Value , class KeyData = NoKeyData>
ZoneVector<Value> v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::merge_values_ {zone_} [private]
Definition at line 284 of file snapshot-table.h.
Referenced by v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::GetPredecessorValue(), and v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Seal().
merging_entries_
template<class Value , class KeyData = NoKeyData>
ZoneVector<TableEntry*> v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::merging_entries_ {zone_} [private]
Definition at line 283 of file snapshot-table.h.
Referenced by v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Seal().
path_
template<class Value , class KeyData = NoKeyData>
ZoneVector<SnapshotData*> v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::path_ {zone_} [private]
Definition at line 285 of file snapshot-table.h.
root_snapshot_
template<class Value , class KeyData = NoKeyData>
SnapshotData* v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::root_snapshot_ [private]
Definition at line 276 of file snapshot-table.h.
Referenced by v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::SnapshotTable().
snapshots_
template<class Value , class KeyData = NoKeyData>
ZoneDeque<SnapshotData> v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::snapshots_ {zone_} [private]
Definition at line 271 of file snapshot-table.h.
Referenced by v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::NewSnapshot(), and v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Seal().
table_
template<class Value , class KeyData = NoKeyData>
ZoneDeque<TableEntry> v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::table_ {zone_} [private]
Definition at line 270 of file snapshot-table.h.
zone_
template<class Value , class KeyData = NoKeyData>
Zone* v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::zone_ [private]
Definition at line 269 of file snapshot-table.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/snapshot-table.h