v8::internal::anonymous_namespace{accounting-allocator.cc}::ManagedZones Class Reference
Static Public Member Functions
static std::optional< VirtualMemory > GetOrCreateMemoryForSegment (Isolate *isolate, size_t bytes)
static base::AllocationResult< void * > AllocateSegment (Isolate *isolate, size_t bytes)
static void ReturnSegment (Isolate *isolate, void *memory, size_t bytes)
Static Private Attributes
static constexpr size_t kMinZonePageSize = 512 * KB
static constexpr size_t kMinZonePageAlignment = 16 * KB
Detailed Description
Definition at line 23 of file accounting-allocator.cc.
Member Function Documentation
AllocateSegment()
static base::AllocationResult<void*> v8::internal::anonymous_namespace{accounting-allocator.cc}::ManagedZones::AllocateSegment (Isolate * isolate, size_t bytes) [inline], [static]
Definition at line 49 of file accounting-allocator.cc.
                                                                     {
    static constexpr size_t kMaxSize = size_t{2} * GB;
    if (bytes >= kMaxSize) {
      return {nullptr, bytes};
    }
    void* memory = nullptr;
    bytes = RoundUp(bytes, ManagedZones::kMinZonePageSize);
    std::optional<VirtualMemory> maybe_reservation =
        ManagedZones::GetOrCreateMemoryForSegment(isolate, bytes);
    if (V8_LIKELY(maybe_reservation)) {
      VirtualMemory reservation = std::move(maybe_reservation.value());
      DCHECK(reservation.IsReserved());
      DCHECK_EQ(reservation.size(), bytes);
      memory = reinterpret_cast<void*>(reservation.address());
      // Don't let the reservation be freed by destructor. From now on the
      // reservation will be managed via a pair {memory, bytes}.
      reservation.Reset();
    }
    return {memory, bytes};
  }
References v8::internal::VirtualMemory::address(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::GB, v8::internal::VirtualMemory::IsReserved(), v8::internal::VirtualMemory::Reset(), RoundUp(), v8::internal::VirtualMemory::size(), and V8_LIKELY.
GetOrCreateMemoryForSegment()
static std::optional<VirtualMemory> v8::internal::anonymous_namespace{accounting-allocator.cc}::ManagedZones::GetOrCreateMemoryForSegment (Isolate * isolate, size_t bytes) [inline], [static]
Definition at line 25 of file accounting-allocator.cc.
                                      {
    DCHECK_EQ(0, bytes % kMinZonePageSize);
    // Only consult the pool if we have an isolate and the size is exactly the
    // zone page size. Larger sizes may be required and just bypass the pool.
    if (isolate && bytes == kMinZonePageSize) {
      auto maybe_reservation =
          IsolateGroup::current()->page_pool()->RemoveZoneReservation(isolate);
      if (maybe_reservation) {
        return maybe_reservation;
      }
    }
    v8::PageAllocator* platform_page_allocator = GetPlatformPageAllocator();
    VirtualMemory memory(platform_page_allocator, bytes,
                         v8::PageAllocator::AllocationHint(),
                         kMinZonePageAlignment, v8::PageAllocator::kReadWrite);
    if (V8_UNLIKELY(!memory.IsReserved())) {
      return std::nullopt;
    }
    CHECK(IsAligned(memory.address(), kMinZonePageAlignment));
    return memory;
  }
References v8::internal::VirtualMemory::address(), CHECK, v8::internal::IsolateGroup::current(), DCHECK_EQ, v8::internal::GetPlatformPageAllocator(), IsAligned(), v8::internal::VirtualMemory::IsReserved(), v8::PageAllocator::kReadWrite, v8::internal::IsolateGroup::page_pool(), v8::internal::PagePool::RemoveZoneReservation(), and V8_UNLIKELY.
ReturnSegment()
static void v8::internal::anonymous_namespace{accounting-allocator.cc}::ManagedZones::ReturnSegment (Isolate * isolate, void * memory, size_t bytes) [inline], [static]
Definition at line 71 of file accounting-allocator.cc.
                                                                          {
    VirtualMemory reservation(GetPlatformPageAllocator(),
                              reinterpret_cast<Address>(memory), bytes);
    if (reservation.size() == ManagedZones::kMinZonePageSize) {
      IsolateGroup::current()->page_pool()->AddZoneReservation(
          isolate, std::move(reservation));
    }
    // Reservation will be automatically freed here otherwise.
  }
References v8::internal::PagePool::AddZoneReservation(), v8::internal::IsolateGroup::current(), v8::internal::GetPlatformPageAllocator(), v8::internal::IsolateGroup::page_pool(), and v8::internal::VirtualMemory::size().
Member Data Documentation
kMinZonePageAlignment
constexpr size_t v8::internal::anonymous_namespace{accounting-allocator.cc}::ManagedZones::kMinZonePageAlignment = 16 * KB [static], [constexpr], [private]
Definition at line 83 of file accounting-allocator.cc.
kMinZonePageSize
constexpr size_t v8::internal::anonymous_namespace{accounting-allocator.cc}::ManagedZones::kMinZonePageSize = 512 * KB [static], [constexpr], [private]
Definition at line 82 of file accounting-allocator.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/zone/accounting-allocator.cc