v8::internal::compiler::turboshaft::Block Class Reference
#include <graph.h>
Public Types
enum class Kind : uint8_t { kMerge
, kLoopHeader
, kBranchTarget
 }
enum class CustomDataKind { kUnset
, kPhiInputIndex
, kDeferredInSchedule
 }
Public Member Functions
Block (Kind kind)
bool IsLoopOrMerge () const
bool IsLoop () const
bool IsMerge () const
bool IsBranchTarget () const
Kind kind () const
void SetKind (Kind kind)
BlockIndex index () const
bool Contains (OpIndex op_idx) const
bool IsBound () const
base::SmallVector< Block *, 8 > Predecessors () const
NeighboringPredecessorIterable PredecessorsIterable () const
int PredecessorCount () const
int GetPredecessorIndex (const Block *target) const
Block * LastPredecessor () const
Block * NeighboringPredecessor () const
bool HasPredecessors () const
void ResetLastPredecessor ()
void ResetAllPredecessors ()
Block * single_loop_predecessor () const
void SetSingleLoopPredecessor (Block *single_loop_predecessor)
void SetOrigin (const Block *origin)
const Block * OriginForBlockEnd () const
const Block * OriginForLoopHeader () const
bool IsComplete () const
OpIndex begin () const
OpIndex end () const
int OpCountUpperBound () const
const Operation & FirstOperation (const Graph &graph) const
const Operation & LastOperation (const Graph &graph) const
Operation & LastOperation (Graph &graph) const
bool EndsWithBranchingOp (const Graph &graph) const
bool HasPhis (const Graph &graph) const
bool HasBackedge (const Graph &graph) const
uint32_t ComputeDominator ()
void PrintDominatorTree (std::vector< const char * > tree_symbols=std::vector< const char * >(), bool has_next=false) const
void set_custom_data (uint32_t data, CustomDataKind kind_for_debug_check)
uint32_t get_custom_data (CustomDataKind kind_for_debug_check) const
void clear_custom_data ()
Static Public Attributes
static constexpr int kInvalidPredecessorIndex = -1
Private Member Functions
void AddPredecessor (Block *predecessor)
Private Attributes
Kind kind_
OpIndex begin_ = OpIndex::Invalid()
OpIndex end_ = OpIndex::Invalid()
BlockIndex index_ = BlockIndex::Invalid()
Block * last_predecessor_ = nullptr
Block * neighboring_predecessor_ = nullptr
Block * single_loop_predecessor_ = nullptr
uint32_t predecessor_count_ = 0
const Block * origin_ = nullptr
uint32_t custom_data_ = 0
Friends
class Graph
template<class Reducers >
class Assembler
template<class Assembler >
class GraphVisitor
Detailed Description
Definition at line 306 of file graph.h.
Member Enumeration Documentation
CustomDataKind
enum v8::internal::compiler::turboshaft::Block::CustomDataKind [strong]
Enumerator
kUnset
kPhiInputIndex
kDeferredInSchedule
Definition at line 503 of file graph.h.
                            {
    kUnset, // No custom data has been set for this block.
    kPhiInputIndex,
    kDeferredInSchedule,
  };
Kind
enum v8::internal::compiler::turboshaft::Block::Kind : uint8_t [strong]
Enumerator
kMerge
kLoopHeader
kBranchTarget
Definition at line 308 of file graph.h.
: uint8_t { kMerge, kLoopHeader, kBranchTarget };
Constructor & Destructor Documentation
Block()
v8::internal::compiler::turboshaft::Block::Block (Kind kind) [inline], [explicit]
Definition at line 310 of file graph.h.
: kind_(kind) {}
Member Function Documentation
AddPredecessor()
void v8::internal::compiler::turboshaft::Block::AddPredecessor (Block * predecessor) [inline], [private]
Definition at line 532 of file graph.h.
                                          {
    DCHECK(!IsBound() ||
           (Predecessors().size() == 1 && kind_ == Kind::kLoopHeader));
    DCHECK_EQ(predecessor->neighboring_predecessor_, nullptr);
    predecessor->neighboring_predecessor_ = last_predecessor_;
    last_predecessor_ = predecessor;
    predecessor_count_++;
  }
References v8::internal::DCHECK(), DCHECK_EQ, IsBound(), kind_, kLoopHeader, last_predecessor_, neighboring_predecessor_, predecessor_count_, Predecessors(), and size().
Referenced by v8::internal::compiler::turboshaft::Assembler< Reducers >::AddLoopPredecessor(), v8::internal::compiler::turboshaft::Assembler< Reducers >::AddPredecessor(), v8::internal::compiler::turboshaft::Assembler< Reducers >::CreateSinglePredecessorForLoop(), and v8::internal::compiler::turboshaft::Assembler< Reducers >::SplitEdge().
begin()
OpIndex v8::internal::compiler::turboshaft::Block::begin () const [inline]
Definition at line 438 of file graph.h.
                        {
    DCHECK(begin_.valid());
    return begin_;
  }
References begin_, v8::internal::DCHECK(), and v8::internal::compiler::turboshaft::OpIndex::valid().
Referenced by v8::internal::compiler::turboshaft::Graph::AllocateNewBlocks(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphCheckException(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::FixLoopPhis(), v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::FixLoopPhis(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::GetTypeForPhiInput(), v8::internal::compiler::turboshaft::Graph::IsLoopBackedge(), OpCountUpperBound(), and v8::internal::compiler::InstructionSelector::VisitNode().
clear_custom_data()
void v8::internal::compiler::turboshaft::Block::clear_custom_data () [inline]
Definition at line 521 of file graph.h.
                           {
    custom_data_ = 0;
#ifdef DEBUG
    custom_data_kind_for_debug_check_ = CustomDataKind::kUnset;
#endif
  }
References custom_data_, and kUnset.
ComputeDominator()
uint32_t v8::internal::compiler::turboshaft::Block::ComputeDominator () [inline]
Definition at line 1291 of file graph.h.
                                        {
  if (V8_UNLIKELY(LastPredecessor() == nullptr)) {
    // If the block has no predecessors, then it's the start block. We create a
    // jmp_ edge to itself, so that the SetDominator algorithm does not need a
    // special case for when the start block is reached.
    SetAsDominatorRoot();
  } else {
    // If the block has one or more predecessors, the dominator is the lowest
    // common ancestor (LCA) of all of the predecessors.
    // Note that for BranchTarget, there is a single predecessor. This doesn't
    // change the logic: the loop won't be entered, and the first (and only)
    // predecessor is set as the dominator.
    // Similarly, since we compute dominators on the fly, when we reach a
    // kLoopHeader, we haven't visited its body yet, and it should only have one
    // predecessor (the backedge is not here yet), which is its dominator.
    DCHECK_IMPLIES(kind_ == Block::Kind::kLoopHeader, PredecessorCount() == 1);
    Block* dominator = LastPredecessor();
    for (Block* pred = dominator->NeighboringPredecessor(); pred != nullptr;
         pred = pred->NeighboringPredecessor()) {
      dominator = dominator->GetCommonDominator(pred);
    }
    SetDominator(dominator);
  }
  DCHECK_NE(jmp_, nullptr);
  DCHECK_IMPLIES(nxt_ == nullptr, LastPredecessor() == nullptr);
  DCHECK_IMPLIES(len_ == 0, LastPredecessor() == nullptr);
  return Depth();
}
References DCHECK_IMPLIES, DCHECK_NE, v8::internal::compiler::turboshaft::RandomAccessStackDominatorNode< Block >::Depth(), v8::internal::compiler::turboshaft::RandomAccessStackDominatorNode< Derived >::GetCommonDominator(), v8::internal::compiler::turboshaft::RandomAccessStackDominatorNode< Block >::jmp_, kind_, kLoopHeader, LastPredecessor(), v8::internal::compiler::turboshaft::RandomAccessStackDominatorNode< Block >::len_, NeighboringPredecessor(), v8::internal::compiler::turboshaft::RandomAccessStackDominatorNode< Block >::nxt_, PredecessorCount(), v8::internal::compiler::turboshaft::RandomAccessStackDominatorNode< Block >::SetAsDominatorRoot(), v8::internal::compiler::turboshaft::RandomAccessStackDominatorNode< Block >::SetDominator(), and V8_UNLIKELY.
Referenced by v8::internal::compiler::turboshaft::Graph::Add().
Contains()
bool v8::internal::compiler::turboshaft::Block::Contains (OpIndex op_idx) const [inline]
Definition at line 322 of file graph.h.
                                      {
    return begin_ <= op_idx && op_idx < end_;
  }
References begin_, and end_.
Referenced by v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::CanBeConstantFolded(), v8::internal::compiler::turboshaft::GenericReducerBase< Next >::FixLoopPhi(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::FixLoopPhi(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::FixLoopPhi(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::FixLoopPhis(), v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::FixLoopPhis(), v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::GetIterCountIfStaticCanonicalForLoop(), and v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::Goto().
end()
OpIndex v8::internal::compiler::turboshaft::Block::end () const [inline]
Definition at line 442 of file graph.h.
                      {
    DCHECK(end_.valid());
    return end_;
  }
References v8::internal::DCHECK(), end_, and v8::internal::compiler::turboshaft::OpIndex::valid().
Referenced by v8::internal::compiler::turboshaft::Graph::AllocateNewBlocks(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphCheckException(), v8::internal::compiler::InstructionSelector::block_terminator(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::FixLoopPhis(), v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::FixLoopPhis(), LastOperation(), OpCountUpperBound(), and v8::internal::compiler::turboshaft::Assembler< Reducers >::SplitEdge().
EndsWithBranchingOp()
bool v8::internal::compiler::turboshaft::Block::EndsWithBranchingOp (const Graph & graph) const [inline]
Definition at line 457 of file graph.h.
                                                     {
    switch (LastOperation(graph).opcode) {
      case Opcode::kBranch:
      case Opcode::kSwitch:
      case Opcode::kCheckException:
        return true;
      default:
        DCHECK_LE(SuccessorBlocks(*this, graph).size(), 1);
        return false;
    }
  }
References DCHECK_LE, graph(), v8::internal::compiler::turboshaft::kBranch, v8::internal::wasm::kSwitch, LastOperation(), size(), and v8::internal::compiler::turboshaft::SuccessorBlocks().
Referenced by v8::internal::compiler::turboshaft::Assembler< Reducers >::AddPredecessor(), and v8::internal::compiler::turboshaft::Assembler< Reducers >::SplitEdge().
FirstOperation()
const Operation & v8::internal::compiler::turboshaft::Block::FirstOperation (const Graph & graph) const [inline]
Definition at line 1246 of file graph.h.
                                                                         {
  DCHECK_EQ(graph_generation_, graph.generation());
  DCHECK(begin_.valid());
  DCHECK(end_.valid());
  return graph.Get(begin_);
}
References begin_, v8::internal::DCHECK(), DCHECK_EQ, end_, graph(), and v8::internal::compiler::turboshaft::OpIndex::valid().
Referenced by v8::internal::compiler::InstructionBlockFor().
get_custom_data()
uint32_t v8::internal::compiler::turboshaft::Block::get_custom_data (CustomDataKind kind_for_debug_check) const [inline]
Definition at line 516 of file graph.h.
                                                                      {
    DCHECK_EQ(custom_data_kind_for_debug_check_, kind_for_debug_check);
    return custom_data_;
  }
References custom_data_, and DCHECK_EQ.
Referenced by v8::internal::compiler::InstructionBlockFor(), v8::internal::compiler::turboshaft::PropagateDeferred(), and v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::ResolvePhi().
GetPredecessorIndex()
int v8::internal::compiler::turboshaft::Block::GetPredecessorIndex (const Block * target) const [inline]
Definition at line 368 of file graph.h.
                                                     {
    int pred_count = 0;
    int pred_reverse_index = -1;
    for (Block* pred = last_predecessor_; pred != nullptr;
         pred = pred->neighboring_predecessor_) {
      if (pred == target) {
        DCHECK_EQ(pred_reverse_index, -1);
        pred_reverse_index = pred_count;
      }
      pred_count++;
    }
    if (pred_reverse_index == -1) {
      return kInvalidPredecessorIndex;
    }
    return pred_count - pred_reverse_index - 1;
  }
References DCHECK_EQ, kInvalidPredecessorIndex, last_predecessor_, and neighboring_predecessor_.
Referenced by v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::CanBeConstantFolded(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::CloneAndInlineBlock(), and v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::CloneBlockAndGoto().
HasBackedge()
bool v8::internal::compiler::turboshaft::Block::HasBackedge (const Graph & graph) const [inline]
Definition at line 471 of file graph.h.
                                             {
    if (const GotoOp* gto = LastOperation(graph).TryCast<GotoOp>()) {
      return gto->destination->index().id() <= index().id();
    }
    return false;
  }
References graph(), v8::internal::compiler::turboshaft::BlockIndex::id(), index(), and LastOperation().
Referenced by v8::internal::compiler::turboshaft::AnalyzerIterator::MarkLoopForRevisit(), and v8::internal::compiler::turboshaft::AnalyzerIterator::MarkLoopForRevisitSkipHeader().
HasPhis()
bool v8::internal::compiler::turboshaft::Block::HasPhis (const Graph & graph) const [inline]
Definition at line 1263 of file graph.h.
                                                      {
  // TODO(dmercadier): consider re-introducing the invariant that Phis are
  // always at the begining of a block to speed up such functions. Currently,
  // in practice, Phis do not appear after the first non-FrameState non-Constant
  // operation, but this is not enforced.
  DCHECK_EQ(graph_generation_, graph.generation());
  for (const auto& op : graph.operations(*this)) {
    if (op.Is<PhiOp>()) return true;
  }
  return false;
}
References DCHECK_EQ, and graph().
Referenced by v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::Branch().
HasPredecessors()
bool v8::internal::compiler::turboshaft::Block::HasPredecessors () const [inline]
Definition at line 387 of file graph.h.
                               {
    DCHECK_EQ(predecessor_count_ == 0, last_predecessor_ == nullptr);
    return last_predecessor_ != nullptr;
  }
References DCHECK_EQ, last_predecessor_, and predecessor_count_.
Referenced by v8::internal::compiler::turboshaft::Graph::Add(), and v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::StartNewSnapshotFor().
index()
BlockIndex v8::internal::compiler::turboshaft::Block::index () const [inline]
Definition at line 320 of file graph.h.
{ return index_; }
References index_.
Referenced by v8::internal::compiler::turboshaft::Graph::Add(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::BackedgeHasSnapshot(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::BackedgeHasSnapshot(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::BeginBlock(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::BeginBlock(), v8::internal::compiler::turboshaft::BlockOriginTrackingReducer< Next >::Bind(), v8::internal::compiler::turboshaft::BlockInstrumentationReducer< Next >::Bind(), v8::internal::compiler::turboshaft::LoopStackCheckElisionReducer< Next >::Bind(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Bind(), v8::internal::compiler::InstructionSelector::CanDoBranchIfOverflowFusion(), v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::CanPeelLoop(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::CloneAndInlineBlock(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::CloneBlockAndGoto(), v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::ComputeSpecialRPO(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::CreateMergeSnapshot(), v8::internal::compiler::turboshaft::Graph::Finalize(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::FinishBlock(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::FinishBlock(), v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::FullyUnrollLoop(), v8::internal::compiler::turboshaft::LoopFinder::GetLoopHeader(), v8::internal::compiler::turboshaft::BlockOriginTrackingReducer< Next >::GetMaglevOrigin(), v8::internal::compiler::GetRpo(), v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::has_loop_number(), HasBackedge(), v8::internal::compiler::turboshaft::anonymous_namespace{operations.cc}::index_for_bound_block(), v8::internal::compiler::turboshaft::AnalyzerIterator::IsOutdated(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::IsReachable(), v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::loop_number(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::MapToNewGraph(), v8::internal::compiler::turboshaft::MemoryAnalyzer::MergeCurrentStateIntoSuccessor(), v8::internal::compiler::turboshaft::AnalyzerIterator::Next(), v8::internal::compiler::turboshaft::LoopFinder::BlockCmp::operator()(), v8::internal::compiler::turboshaft::operator<<(), v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::PartiallyUnrollLoop(), v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::PeelFirstIteration(), PrintDominatorTree(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessBlock(), v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::ProcessBlock(), v8::internal::compiler::turboshaft::DeadCodeAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessBranchOnTarget(), v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::PushFront(), v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::RecordOldEpochAndSetNew(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::RefineOperationType(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::RefineOperationType(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::RefineTypeKnowledge(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::RefineTypeKnowledgeNotNull(), v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::RemoveLoop(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::ReplayMissingPredecessors(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::RestoreTemporaryVariableSnapshotAfter(), v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::rpo_number(), v8::internal::compiler::InstructionSelector::rpo_number(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::Run(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::Run(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::Run(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::Run(), v8::internal::compiler::turboshaft::RedundantStoreAnalysis::Run(), v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::Seal(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::SealAndSaveVariableSnapshot(), v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::set_loop_number(), v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::set_rpo_number(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::StartNewSnapshotFor(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::StoreLoopSnapshotInForwardPredecessor(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::StoreLoopSnapshotInForwardPredecessor(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::TraceReductionResult(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitBlock(), and v8::internal::compiler::turboshaft::LoopFinder::VisitLoop().
IsBound()
bool v8::internal::compiler::turboshaft::Block::IsBound () const [inline]
Definition at line 326 of file graph.h.
{ return index_ != BlockIndex::Invalid(); }
References index_, and v8::internal::compiler::turboshaft::BlockIndex::Invalid().
Referenced by AddPredecessor(), v8::internal::compiler::turboshaft::Assembler< Reducers >::AddPredecessor(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphGoto(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ComputePredecessorPermutations(), v8::internal::compiler::turboshaft::Assembler< Reducers >::CreateSinglePredecessorForLoop(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Goto(), v8::internal::compiler::turboshaft::Graph::IsLoopBackedge(), OriginForBlockEnd(), v8::internal::wasm::TurboshaftGraphBuildingInterface::PopControl(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::turboshaft::LabelBase< loop, Ts >::RecordValues(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Run().
IsBranchTarget()
bool v8::internal::compiler::turboshaft::Block::IsBranchTarget () const [inline]
Definition at line 315 of file graph.h.
{ return kind_ == Kind::kBranchTarget; }
References kBranchTarget, and kind_.
Referenced by v8::internal::compiler::turboshaft::Assembler< Reducers >::AddPredecessor(), v8::internal::compiler::turboshaft::GenericReducerBase< Next >::CatchBlockBegin(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::ReplayMissingPredecessors(), and v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::StartNewSnapshotFor().
IsComplete()
bool v8::internal::compiler::turboshaft::Block::IsComplete () const [inline]
Definition at line 437 of file graph.h.
{ return end_.valid(); }
References end_, and v8::internal::compiler::turboshaft::OpIndex::valid().
IsLoop()
bool v8::internal::compiler::turboshaft::Block::IsLoop () const [inline]
Definition at line 313 of file graph.h.
{ return kind_ == Kind::kLoopHeader; }
References kind_, and kLoopHeader.
Referenced by v8::internal::compiler::turboshaft::Assembler< Reducers >::AddPredecessor(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphGoto(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::BackedgeHasSnapshot(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::BackedgeHasSnapshot(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::BeginBlock(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::BeginBlock(), v8::internal::compiler::turboshaft::Assembler< Reducers >::Bind(), v8::internal::compiler::InstructionSelector::CanDoBranchIfOverflowFusion(), v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::ComputeLoopInfo(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ComputePredecessorPermutations(), v8::internal::compiler::turboshaft::Assembler< Reducers >::CreateSinglePredecessorForLoop(), v8::internal::compiler::turboshaft::Assembler< Reducers >::FinalizeLoop(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::FixLoopPhis(), v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::FixLoopPhis(), v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::GetIterationCount(), v8::internal::compiler::GetLoopEndRpo(), v8::internal::compiler::turboshaft::LoopFinder::GetLoopInfo(), v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::GetLoopIterationCount(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::GetTypeForPhiInput(), v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::Goto(), v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::Goto(), v8::internal::compiler::InstructionSelector::IsLoopHeader(), IsLoopOrMerge(), v8::internal::compiler::turboshaft::AnalyzerIterator::Next(), OriginForLoopHeader(), v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::PartiallyUnrollLoop(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessBlock(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessBlock(), v8::internal::compiler::turboshaft::DeadCodeAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::RecordOldEpochAndSetNew(), v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::Run(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Run(), v8::internal::compiler::turboshaft::RedundantStoreAnalysis::Run(), SetSingleLoopPredecessor(), v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::ShouldFullyUnrollLoop(), v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::ShouldPartiallyUnrollLoop(), single_loop_predecessor(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::StartNewSnapshotFor(), v8::internal::compiler::turboshaft::Graph::TurnLoopIntoMerge(), v8::internal::compiler::turboshaft::UseMap::UseMap(), and v8::internal::compiler::turboshaft::LoopFinder::VisitLoop().
IsLoopOrMerge()
bool v8::internal::compiler::turboshaft::Block::IsLoopOrMerge () const [inline]
Definition at line 312 of file graph.h.
{ return IsLoop() || IsMerge(); }
References IsLoop(), and IsMerge().
Referenced by v8::internal::compiler::turboshaft::Assembler< Reducers >::AddPredecessor().
IsMerge()
bool v8::internal::compiler::turboshaft::Block::IsMerge () const [inline]
Definition at line 314 of file graph.h.
{ return kind_ == Kind::kMerge; }
References kind_, and kMerge.
Referenced by v8::internal::compiler::turboshaft::GenericReducerBase< Next >::CatchBlockBegin(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::Goto(), IsLoopOrMerge(), and v8::internal::compiler::turboshaft::DeadCodeAnalysis::ProcessBlock().
kind()
Kind v8::internal::compiler::turboshaft::Block::kind () const [inline]
Definition at line 317 of file graph.h.
{ return kind_; }
References kind_.
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::CloneBlockAndGoto(), v8::internal::compiler::turboshaft::operator<<(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::Run(), SetKind(), and v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::StartNewSnapshotFor().
LastOperation() [1/2]
const Operation & v8::internal::compiler::turboshaft::Block::LastOperation (const Graph & graph) const [inline]
Definition at line 1253 of file graph.h.
                                                                        {
  DCHECK_EQ(graph_generation_, graph.generation());
  return graph.Get(graph.PreviousIndex(end()));
}
References DCHECK_EQ, end(), and graph().
Referenced by v8::internal::compiler::turboshaft::Assembler< Reducers >::AddLoopPredecessor(), v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::BeginBlock(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Bind(), v8::internal::compiler::turboshaft::GenericReducerBase< Next >::CatchBlockBegin(), v8::internal::compiler::turboshaft::Assembler< Reducers >::CreateSinglePredecessorForLoop(), EndsWithBranchingOp(), v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::GetLoopIterationCount(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::Goto(), HasBackedge(), v8::internal::compiler::InstructionBlockFor(), v8::internal::compiler::turboshaft::IsUnlikelySuccessor(), v8::internal::compiler::turboshaft::AnalyzerIterator::MarkLoopForRevisit(), v8::internal::compiler::turboshaft::AnalyzerIterator::MarkLoopForRevisitSkipHeader(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::turboshaft::DeadCodeAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::IfElseCascadeToSwitchReducer< Next >::ReduceInputGraphBranch(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::ReplayMissingPredecessors(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::Run(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::Run(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::Run(), v8::internal::compiler::turboshaft::SuccessorBlocks(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::TagExceptionPhiInputsForBlock(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitBlock(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitBlockBody(), v8::internal::compiler::InstructionSelector::VisitControl(), v8::internal::compiler::turboshaft::LoopFinder::VisitLoop(), and v8::internal::compiler::InstructionSelector::VisitNode().
LastOperation() [2/2]
Operation & v8::internal::compiler::turboshaft::Block::LastOperation (Graph & graph) const [inline]
Definition at line 1258 of file graph.h.
                                                            {
  DCHECK_EQ(graph_generation_, graph.generation());
  return graph.Get(graph.PreviousIndex(end()));
}
References DCHECK_EQ, end(), and graph().
LastPredecessor()
Block* v8::internal::compiler::turboshaft::Block::LastPredecessor () const [inline]
Definition at line 385 of file graph.h.
{ return last_predecessor_; }
References last_predecessor_.
Referenced by v8::internal::compiler::turboshaft::Assembler< Reducers >::AddPredecessor(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::BackedgeHasSnapshot(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::BackedgeHasSnapshot(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::BeginBlock(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::BeginBlock(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Bind(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::BranchAndBind(), v8::internal::compiler::turboshaft::GenericReducerBase< Next >::CatchBlockBegin(), ComputeDominator(), v8::internal::compiler::turboshaft::Assembler< Reducers >::CreateSinglePredecessorForLoop(), v8::internal::compiler::turboshaft::LoopFinder::GetLoopBody(), v8::internal::compiler::GetLoopEndRpo(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::Goto(), v8::internal::compiler::InstructionBlockFor(), v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::ProcessBlock(), v8::internal::compiler::turboshaft::DeadCodeAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::PropagateDeferred(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::ReplayMissingPredecessors(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::ResolvePhi(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::Run(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::Run(), v8::internal::compiler::turboshaft::RedundantStoreAnalysis::Run(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::StartNewSnapshotFor(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::StoreLoopSnapshotInForwardPredecessor(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::StoreLoopSnapshotInForwardPredecessor(), v8::internal::compiler::turboshaft::LoopFinder::VisitLoop(), and v8::internal::compiler::InstructionSelector::VisitNode().
NeighboringPredecessor()
Block* v8::internal::compiler::turboshaft::Block::NeighboringPredecessor () const [inline]
Definition at line 386 of file graph.h.
{ return neighboring_predecessor_; }
References neighboring_predecessor_.
Referenced by ComputeDominator(), v8::internal::compiler::turboshaft::LoopFinder::GetLoopBody(), v8::internal::compiler::InstructionBlockFor(), v8::internal::compiler::turboshaft::PredecessorIterator::operator++(), v8::internal::compiler::turboshaft::PropagateDeferred(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::ResolvePhi(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::Run(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::Run(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::StartNewSnapshotFor(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::StoreLoopSnapshotInForwardPredecessor(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::StoreLoopSnapshotInForwardPredecessor(), and v8::internal::compiler::turboshaft::LoopFinder::VisitLoop().
OpCountUpperBound()
int v8::internal::compiler::turboshaft::Block::OpCountUpperBound () const [inline]
Definition at line 451 of file graph.h.
{ return end().id() - begin().id(); }
References begin(), end(), and v8::internal::compiler::turboshaft::OpIndex::id().
Referenced by v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::Goto(), and v8::internal::compiler::turboshaft::LoopFinder::VisitLoop().
OriginForBlockEnd()
const Block* v8::internal::compiler::turboshaft::Block::OriginForBlockEnd () const [inline]
Definition at line 428 of file graph.h.
                                         {
    DCHECK(IsBound());
    return origin_;
  }
References v8::internal::DCHECK(), IsBound(), and origin_.
Referenced by v8::internal::compiler::turboshaft::LoopStackCheckElisionReducer< Next >::Bind(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::ResolvePhi(), and v8::internal::compiler::turboshaft::Assembler< Reducers >::SplitEdge().
OriginForLoopHeader()
const Block* v8::internal::compiler::turboshaft::Block::OriginForLoopHeader () const [inline]
Definition at line 432 of file graph.h.
                                           {
    DCHECK(IsLoop());
    return origin_;
  }
References v8::internal::DCHECK(), IsLoop(), and origin_.
Referenced by v8::internal::compiler::turboshaft::Assembler< Reducers >::CreateSinglePredecessorForLoop().
PredecessorCount()
int v8::internal::compiler::turboshaft::Block::PredecessorCount () const [inline]
Definition at line 344 of file graph.h.
                               {
#ifdef DEBUG
    CheckPredecessorCount();
#endif
    return predecessor_count_;
  }
References predecessor_count_.
Referenced by v8::internal::compiler::turboshaft::Assembler< Reducers >::AddPredecessor(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Bind(), v8::internal::compiler::turboshaft::GenericReducerBase< Next >::CatchBlockBegin(), ComputeDominator(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ComputePredecessorPermutations(), v8::internal::compiler::turboshaft::Assembler< Reducers >::CreateSinglePredecessorForLoop(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::DoCloneBlock(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::EmitLoopSinglePredecessorBlock(), v8::internal::compiler::turboshaft::Assembler< Reducers >::FinalizeLoop(), v8::internal::compiler::InstructionBlockFor(), v8::internal::compiler::turboshaft::LabelBase< loop, Ts >::MaterializePhisImpl(), v8::internal::wasm::TurboshaftGraphBuildingInterface::PopControl(), v8::internal::compiler::InstructionSelector::PredecessorCount(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessBranchOnTarget(), v8::internal::compiler::turboshaft::LabelBase< loop, Ts >::RecordValuesImpl(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::ResolvePhi(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::StartExceptionBlock(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::StartNewSnapshotFor(), v8::internal::compiler::turboshaft::Graph::TurnLoopIntoMerge(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitBlockTerminator(), and v8::internal::compiler::InstructionSelector::VisitNode().
Predecessors()
base::SmallVector<Block*, 8> v8::internal::compiler::turboshaft::Block::Predecessors () const [inline]
Definition at line 328 of file graph.h.
                                                  {
    base::SmallVector<Block*, 8> result;
    for (Block* pred = last_predecessor_; pred != nullptr;
         pred = pred->neighboring_predecessor_) {
      result.push_back(pred);
    }
    std::reverse(result.begin(), result.end());
    return result;
  }
References last_predecessor_, neighboring_predecessor_, and v8::base::internal::result.
Referenced by v8::internal::compiler::turboshaft::Graph::Add(), AddPredecessor(), v8::internal::compiler::turboshaft::GenericReducerBase< Next >::CatchBlockBegin(), v8::internal::compiler::turboshaft::IsUnlikelySuccessor(), v8::internal::compiler::turboshaft::operator<<(), v8::internal::compiler::InstructionSelector::PredecessorAt(), v8::internal::compiler::turboshaft::JSONTurboshaftGraphWriter::PrintBlocks(), v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::RecordOldEpochAndSetNew(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::StartMultiPredecessorExceptionBlock(), and v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::StartNewSnapshotFor().
PredecessorsIterable()
NeighboringPredecessorIterable v8::internal::compiler::turboshaft::Block::PredecessorsIterable () const [inline]
Definition at line 340 of file graph.h.
                                                              {
    return NeighboringPredecessorIterable(last_predecessor_);
  }
References last_predecessor_.
Referenced by v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::BeginBlock(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::BeginBlock(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Bind(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::Bind(), v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::ComputeLoopInfo(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ComputePredecessorPermutations(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::CreateMergeSnapshot(), and v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessBlock().
PrintDominatorTree()
void v8::internal::compiler::turboshaft::Block::PrintDominatorTree (std::vector< const char * > tree_symbols = std::vector<const char*>(), bool has_next = false) const
Definition at line 36 of file graph.cc.
                                                    {
  // Printing the current node.
  if (tree_symbols.empty()) {
    // This node is the root of the tree.
    PrintF("B%d\n", index().id());
    tree_symbols.push_back("");
  } else {
    // This node is not the root of the tree; we start by printing the
    // connectors of the previous levels.
    for (const char* s : tree_symbols) PrintF("%s", s);
    // Then, we print the node id, preceeded by a or connector.
    const char* tree_connector_symbol = has_next ? "" : "";
    PrintF("%s B%d\n", tree_connector_symbol, index().id());
    // And we add to the stack a connector to continue this path (if needed)
    // while printing the current node's children.
    const char* tree_cont_symbol = has_next ? " " : " ";
    tree_symbols.push_back(tree_cont_symbol);
  }
  // Recursively printing the children of this node.
  base::SmallVector<Block*, 8> children = Children();
  for (Block* child : children) {
    child->PrintDominatorTree(tree_symbols, child != children.back());
  }
  // Removing from the stack the "" or " " corresponding to this node.
  tree_symbols.pop_back();
}
References v8::base::SmallVector< T, kSize, Allocator >::back(), v8::internal::compiler::turboshaft::DominatorForwardTreeNode< Derived >::Children(), index(), and v8::internal::PrintF().
ResetAllPredecessors()
void v8::internal::compiler::turboshaft::Block::ResetAllPredecessors () [inline]
Definition at line 395 of file graph.h.
                              {
    Block* pred = last_predecessor_;
    last_predecessor_ = nullptr;
    while (pred->neighboring_predecessor_) {
      Block* tmp = pred->neighboring_predecessor_;
      pred->neighboring_predecessor_ = nullptr;
      pred = tmp;
    }
    predecessor_count_ = 0;
  }
References last_predecessor_, neighboring_predecessor_, and predecessor_count_.
Referenced by v8::internal::compiler::turboshaft::Assembler< Reducers >::CreateSinglePredecessorForLoop(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::StartMultiPredecessorExceptionBlock().
ResetLastPredecessor()
void v8::internal::compiler::turboshaft::Block::ResetLastPredecessor () [inline]
Definition at line 391 of file graph.h.
                              {
    last_predecessor_ = nullptr;
    predecessor_count_ = 0;
  }
References last_predecessor_, and predecessor_count_.
Referenced by v8::internal::compiler::turboshaft::Assembler< Reducers >::AddPredecessor().
set_custom_data()
void v8::internal::compiler::turboshaft::Block::set_custom_data (uint32_t data, CustomDataKind kind_for_debug_check) [inline]
Definition at line 509 of file graph.h.
                                                                           {
    custom_data_ = data;
#ifdef DEBUG
    custom_data_kind_for_debug_check_ = kind_for_debug_check;
#endif
  }
References custom_data_.
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::ResolvePhi().
SetKind()
void v8::internal::compiler::turboshaft::Block::SetKind (Kind kind) [inline]
Definition at line 318 of file graph.h.
{ kind_ = kind; }
References kind(), and kind_.
Referenced by v8::internal::compiler::turboshaft::Assembler< Reducers >::AddPredecessor(), v8::internal::compiler::turboshaft::Assembler< Reducers >::CreateSinglePredecessorForLoop(), v8::internal::wasm::TurboshaftGraphBuildingInterface::PopControl(), and v8::internal::compiler::turboshaft::Assembler< Reducers >::SplitEdge().
SetOrigin()
void v8::internal::compiler::turboshaft::Block::SetOrigin (const Block * origin) [inline]
Definition at line 420 of file graph.h.
                                      {
    DCHECK_IMPLIES(origin != nullptr,
                   origin->graph_generation_ + 1 == graph_generation_);
    origin_ = origin;
  }
References DCHECK_IMPLIES, and origin_.
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::Bind(), v8::internal::compiler::turboshaft::Assembler< Reducers >::CreateSinglePredecessorForLoop(), v8::internal::compiler::turboshaft::Assembler< Reducers >::SplitEdge(), and v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitOpNoMappingUpdate().
SetSingleLoopPredecessor()
void v8::internal::compiler::turboshaft::Block::SetSingleLoopPredecessor (Block * single_loop_predecessor) [inline]
Definition at line 410 of file graph.h.
                                                                {
    DCHECK(IsLoop());
    DCHECK_NULL(single_loop_predecessor_);
    DCHECK_NOT_NULL(single_loop_predecessor);
    single_loop_predecessor_ = single_loop_predecessor;
  }
References v8::internal::DCHECK(), DCHECK_NOT_NULL, DCHECK_NULL, IsLoop(), single_loop_predecessor(), and single_loop_predecessor_.
Referenced by v8::internal::compiler::turboshaft::Assembler< Reducers >::CreateSinglePredecessorForLoop().
single_loop_predecessor()
Block* v8::internal::compiler::turboshaft::Block::single_loop_predecessor () const [inline]
Definition at line 406 of file graph.h.
                                         {
    DCHECK(IsLoop());
    return single_loop_predecessor_;
  }
References v8::internal::DCHECK(), IsLoop(), and single_loop_predecessor_.
Referenced by v8::internal::compiler::turboshaft::Assembler< Reducers >::AddPredecessor(), v8::internal::compiler::turboshaft::Assembler< Reducers >::Bind(), and SetSingleLoopPredecessor().
Friends And Related Function Documentation
Assembler
template<class Reducers >
friend class Assembler [friend]
Definition at line 565 of file graph.h.
Graph
friend class Graph [friend]
Definition at line 563 of file graph.h.
GraphVisitor
template<class Assembler >
friend class GraphVisitor [friend]
Definition at line 567 of file graph.h.
Member Data Documentation
begin_
OpIndex v8::internal::compiler::turboshaft::Block::begin_ = OpIndex::Invalid() [private]
Definition at line 543 of file graph.h.
Referenced by v8::internal::compiler::turboshaft::Graph::Add(), begin(), Contains(), FirstOperation(), v8::internal::compiler::turboshaft::Graph::OperationIndices(), and v8::internal::compiler::turboshaft::Graph::operations().
custom_data_
uint32_t v8::internal::compiler::turboshaft::Block::custom_data_ = 0 [private]
Definition at line 555 of file graph.h.
Referenced by clear_custom_data(), get_custom_data(), and set_custom_data().
end_
OpIndex v8::internal::compiler::turboshaft::Block::end_ = OpIndex::Invalid() [private]
Definition at line 544 of file graph.h.
Referenced by Contains(), end(), v8::internal::compiler::turboshaft::Graph::Finalize(), FirstOperation(), IsComplete(), v8::internal::compiler::turboshaft::Graph::OperationIndices(), and v8::internal::compiler::turboshaft::Graph::operations().
index_
BlockIndex v8::internal::compiler::turboshaft::Block::index_ = BlockIndex::Invalid() [private]
Definition at line 545 of file graph.h.
Referenced by v8::internal::compiler::turboshaft::Graph::Add(), index(), and IsBound().
kind_
Kind v8::internal::compiler::turboshaft::Block::kind_ [private]
Definition at line 542 of file graph.h.
Referenced by AddPredecessor(), ComputeDominator(), IsBranchTarget(), IsLoop(), IsMerge(), kind(), SetKind(), and v8::internal::compiler::turboshaft::Graph::TurnLoopIntoMerge().
kInvalidPredecessorIndex
constexpr int v8::internal::compiler::turboshaft::Block::kInvalidPredecessorIndex = -1 [static], [constexpr]
Definition at line 364 of file graph.h.
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ComputePredecessorPermutations(), GetPredecessorIndex(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::MakePhiMaybePermuteInputs().
last_predecessor_
Block* v8::internal::compiler::turboshaft::Block::last_predecessor_ = nullptr [private]
Definition at line 546 of file graph.h.
Referenced by AddPredecessor(), GetPredecessorIndex(), HasPredecessors(), LastPredecessor(), Predecessors(), PredecessorsIterable(), ResetAllPredecessors(), and ResetLastPredecessor().
neighboring_predecessor_
Block* v8::internal::compiler::turboshaft::Block::neighboring_predecessor_ = nullptr [private]
Definition at line 547 of file graph.h.
Referenced by AddPredecessor(), GetPredecessorIndex(), NeighboringPredecessor(), Predecessors(), and ResetAllPredecessors().
origin_
const Block* v8::internal::compiler::turboshaft::Block::origin_ = nullptr [private]
Definition at line 550 of file graph.h.
Referenced by OriginForBlockEnd(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::OriginForBlockStart(), OriginForLoopHeader(), and SetOrigin().
predecessor_count_
uint32_t v8::internal::compiler::turboshaft::Block::predecessor_count_ = 0 [private]
Definition at line 549 of file graph.h.
Referenced by AddPredecessor(), HasPredecessors(), PredecessorCount(), ResetAllPredecessors(), and ResetLastPredecessor().
single_loop_predecessor_
Block* v8::internal::compiler::turboshaft::Block::single_loop_predecessor_ = nullptr [private]
Definition at line 548 of file graph.h.
Referenced by SetSingleLoopPredecessor(), and single_loop_predecessor().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/graph.h
/mnt/V8SourceCode/src/compiler/turboshaft/graph.cc