v8::internal::compiler::PerIsolateCompilerCache Class Reference
#include <per-isolate-compiler-cache.h>
Public Member Functions
PerIsolateCompilerCache (Zone *zone)
bool HasSnapshot () const
RefsMap * GetSnapshot ()
void SetSnapshot (RefsMap *refs)
Zone * zone () const
Static Public Member Functions
static void Setup (Isolate *isolate)
Private Attributes
Zone *const zone_
RefsMap * refs_snapshot_
Detailed Description
Definition at line 26 of file per-isolate-compiler-cache.h.
Constructor & Destructor Documentation
PerIsolateCompilerCache()
v8::internal::compiler::PerIsolateCompilerCache::PerIsolateCompilerCache (Zone * zone) [inline], [explicit]
Definition at line 28 of file per-isolate-compiler-cache.h.
      : zone_(zone), refs_snapshot_(nullptr) {}
Member Function Documentation
GetSnapshot()
RefsMap* v8::internal::compiler::PerIsolateCompilerCache::GetSnapshot () [inline]
Definition at line 32 of file per-isolate-compiler-cache.h.
                         {
    DCHECK(HasSnapshot());
    return refs_snapshot_;
  }
References v8::internal::DCHECK(), HasSnapshot(), and refs_snapshot_.
HasSnapshot()
bool v8::internal::compiler::PerIsolateCompilerCache::HasSnapshot () const [inline]
Definition at line 31 of file per-isolate-compiler-cache.h.
{ return refs_snapshot_ != nullptr; }
References refs_snapshot_.
Referenced by GetSnapshot(), and SetSnapshot().
SetSnapshot()
void v8::internal::compiler::PerIsolateCompilerCache::SetSnapshot (RefsMap * refs) [inline]
Definition at line 36 of file per-isolate-compiler-cache.h.
                                  {
    DCHECK(!HasSnapshot());
    DCHECK(!refs->IsEmpty());
    refs_snapshot_ = zone_->New<RefsMap>(refs, zone_);
    DCHECK(HasSnapshot());
  }
References v8::internal::DCHECK(), HasSnapshot(), v8::internal::compiler::RefsMap::IsEmpty(), v8::internal::Zone::New(), refs_snapshot_, and zone_.
Setup()
static void v8::internal::compiler::PerIsolateCompilerCache::Setup (Isolate * isolate) [inline], [static]
Definition at line 45 of file per-isolate-compiler-cache.h.
                                      {
    if (isolate->compiler_cache() == nullptr) {
      Zone* zone = new Zone(isolate->allocator(), "Compiler zone");
      PerIsolateCompilerCache* cache = zone->New<PerIsolateCompilerCache>(zone);
      isolate->set_compiler_utils(cache, zone);
    }
    DCHECK_NOT_NULL(isolate->compiler_cache());
  }
References v8::internal::Isolate::allocator(), v8::internal::Isolate::compiler_cache(), DCHECK_NOT_NULL, v8::internal::Zone::New(), v8::internal::Isolate::set_compiler_utils(), and zone().
zone()
Zone* v8::internal::compiler::PerIsolateCompilerCache::zone () const [inline]
Definition at line 43 of file per-isolate-compiler-cache.h.
{ return zone_; }
References zone_.
Referenced by Setup().
Member Data Documentation
refs_snapshot_
RefsMap* v8::internal::compiler::PerIsolateCompilerCache::refs_snapshot_ [private]
Definition at line 56 of file per-isolate-compiler-cache.h.
Referenced by GetSnapshot(), HasSnapshot(), and SetSnapshot().
zone_
Zone* const v8::internal::compiler::PerIsolateCompilerCache::zone_ [private]
Definition at line 55 of file per-isolate-compiler-cache.h.
Referenced by SetSnapshot(), and zone().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/per-isolate-compiler-cache.h