v8::internal::ArrayList Class Reference
#include <fixed-array.h>
Classes
class BodyDescriptor
Public Types
using Shape = ArrayListShape
Public Member Functions
int length () const
void set_length (int value)
void RightTrim (Isolate *isolate, int new_capacity)
Static Public Member Functions
template<class IsolateT >
static DirectHandle< ArrayList > New (IsolateT *isolate, int capacity, AllocationType allocation=AllocationType::kYoung)
static V8_EXPORT_PRIVATE DirectHandle< ArrayList > Add (Isolate *isolate, DirectHandle< ArrayList > array, Tagged< Smi > obj, AllocationType allocation=AllocationType::kYoung)
static V8_EXPORT_PRIVATE DirectHandle< ArrayList > Add (Isolate *isolate, DirectHandle< ArrayList > array, DirectHandle< Object > obj, AllocationType allocation=AllocationType::kYoung)
static V8_EXPORT_PRIVATE DirectHandle< ArrayList > Add (Isolate *isolate, DirectHandle< ArrayList > array, DirectHandle< Object > obj0, DirectHandle< Object > obj1, AllocationType allocation=AllocationType::kYoung)
static V8_EXPORT_PRIVATE DirectHandle< FixedArray > ToFixedArray (Isolate *isolate, DirectHandle< ArrayList > array, AllocationType allocation=AllocationType::kYoung)
Private Types
using Super = TaggedArrayBase< ArrayList, ArrayListShape >
Static Private Member Functions
static DirectHandle< ArrayList > EnsureSpace (Isolate *isolate, DirectHandle< ArrayList > array, int length, AllocationType allocation=AllocationType::kYoung)
Additional Inherited Members
Detailed Description
Definition at line 710 of file fixed-array.h.
Member Typedef Documentation
Shape
using v8::internal::ArrayList::Shape = ArrayListShape
Definition at line 714 of file fixed-array.h.
Super
using v8::internal::ArrayList::Super = TaggedArrayBase<ArrayList, ArrayListShape> [private]
Definition at line 711 of file fixed-array.h.
Member Function Documentation
Add() [1/3]
DirectHandle< ArrayList > v8::internal::ArrayList::Add (Isolate * isolate, DirectHandle< ArrayList > array, DirectHandle< Object > obj, AllocationType allocation = AllocationType::kYoung) [static]
Definition at line 89 of file fixed-array.cc.
                                                                  {
  int length = array->length();
  int new_length = length + 1;
  array = EnsureSpace(isolate, array, new_length, allocation);
  DCHECK_EQ(array->length(), length);
  DisallowGarbageCollection no_gc;
  array->set(length, *obj);
  array->set_length(new_length);
  return array;
}
References DCHECK_EQ, EnsureSpace(), length(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Add() [2/3]
DirectHandle< ArrayList > v8::internal::ArrayList::Add (Isolate * isolate, DirectHandle< ArrayList > array, DirectHandle< Object > obj0, DirectHandle< Object > obj1, AllocationType allocation = AllocationType::kYoung) [static]
Definition at line 105 of file fixed-array.cc.
                                                                  {
  int length = array->length();
  int new_length = length + 2;
  array = EnsureSpace(isolate, array, new_length, allocation);
  DCHECK_EQ(array->length(), length);
  DisallowGarbageCollection no_gc;
  array->set(length + 0, *obj0);
  array->set(length + 1, *obj1);
  array->set_length(new_length);
  return array;
}
References DCHECK_EQ, EnsureSpace(), length(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Add() [3/3]
static V8_EXPORT_PRIVATE DirectHandle<ArrayList> v8::internal::ArrayList::Add (Isolate * isolate, DirectHandle< ArrayList > array, Tagged< Smi > obj, AllocationType allocation = AllocationType::kYoung) [static]
Referenced by v8::internal::SourceTextModule::AddAsyncParentModule(), v8::internal::SnapshotCreatorImpl::AddData(), v8::internal::anonymous_namespace{runtime-debug.cc}::AddIteratorInternalProperties(), v8::Isolate::AddMessageListenerWithErrorLevel(), v8::internal::ApiNatives::AddNativeDataProperty(), v8::internal::anonymous_namespace{api-natives.cc}::AddPropertyToPropertyList(), v8::internal::FeedbackVector::AddToVectorsForProfilingTools(), v8::internal::AddWasmInstanceObjectInternalProperties(), v8::internal::AddWasmModuleObjectInternalProperties(), v8::internal::AddWasmTableObjectInternalProperties(), v8::internal::Factory::CodeBuilder::BuildInternal(), v8::internal::Compiler::Compile(), v8::internal::Runtime::GetInternalProperties(), v8::internal::TemplateObjectDescription::GetTemplateObject(), and v8::internal::Isolate::MaybeInitializeVectorListFromHeap().
EnsureSpace()
DirectHandle< ArrayList > v8::internal::ArrayList::EnsureSpace (Isolate * isolate, DirectHandle< ArrayList > array, int length, AllocationType allocation = AllocationType::kYoung) [static], [private]
Definition at line 145 of file fixed-array.cc.
                                                                          {
  DCHECK_LT(0, length);
  int old_capacity = array->capacity();
  if (old_capacity >= length) return array;
  int old_length = array->length();
  // Ensure calculation matches CodeStubAssembler::ArrayListEnsureSpace.
  int new_capacity = length + std::max(length / 2, 2);
  DirectHandle<ArrayList> new_array =
      ArrayList::New(isolate, new_capacity, allocation);
  DisallowGarbageCollection no_gc;
  new_array->set_length(old_length);
  WriteBarrierMode mode = new_array->GetWriteBarrierMode(no_gc);
  CopyElements(isolate, *new_array, 0, *array, 0, old_length, mode);
  return new_array;
}
References v8::internal::TaggedArrayBase< ArrayList, ArrayListShape >::CopyElements(), DCHECK_LT, length(), mode(), New(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by Add().
length()
int v8::internal::ArrayList::length () const [inline]
Definition at line 725 of file fixed-array-inl.h.
{ return length_.load().value(); }
Referenced by Add(), EnsureSpace(), RightTrim(), and ToFixedArray().
New()
template<class IsolateT >
DirectHandle< ArrayList > v8::internal::ArrayList::New (IsolateT * isolate, int capacity, AllocationType allocation = AllocationType::kYoung) [inline], [static]
Definition at line 732 of file fixed-array-inl.h.
                                                                  {
  if (capacity == 0) return isolate->factory()->empty_array_list();
  DCHECK_GT(capacity, 0);
  DCHECK_LE(capacity, kMaxCapacity);
  std::optional<DisallowGarbageCollection> no_gc;
  DirectHandle<ArrayList> result =
      Cast<ArrayList>(Allocate(isolate, capacity, &no_gc, allocation));
  result->set_length(0);
  ReadOnlyRoots roots{isolate};
  MemsetTagged(result->RawFieldOfFirstElement(), roots.undefined_value(),
               capacity);
  return result;
}
References v8::base::anonymous_namespace{platform-posix.cc}::Allocate(), v8::internal::WeakArrayList::capacity(), DCHECK_GT, DCHECK_LE, v8::internal::WeakArrayList::kMaxCapacity, v8::internal::MemsetTagged(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::base::internal::result.
Referenced by v8::internal::SnapshotCreatorImpl::AddData(), v8::internal::ApiNatives::AddNativeDataProperty(), v8::internal::anonymous_namespace{api-natives.cc}::AddPropertyToPropertyList(), v8::internal::Factory::CloneScript(), v8::internal::Compiler::Compile(), v8::internal::Heap::CreateMutableApiObjects(), EnsureSpace(), v8::internal::Runtime::GetInternalProperties(), v8::internal::Isolate::MaybeInitializeVectorListFromHeap(), and v8::internal::FactoryBase< Impl >::NewArrayList().
RightTrim()
void v8::internal::ArrayList::RightTrim (Isolate * isolate, int new_capacity)
Definition at line 139 of file fixed-array.cc.
                                                            {
  Super::RightTrim(isolate, new_capacity);
  if (new_capacity < length()) set_length(new_capacity);
}
References length(), v8::internal::TaggedArrayBase< ArrayList, ArrayListShape >::RightTrim(), and set_length().
set_length()
void v8::internal::ArrayList::set_length (int value) [inline]
Definition at line 726 of file fixed-array-inl.h.
                                     {
  length_.store(this, Smi::FromInt(value));
}
References v8::internal::Smi::FromInt(), and v8::internal::value.
Referenced by RightTrim().
ToFixedArray()
DirectHandle< FixedArray > v8::internal::ArrayList::ToFixedArray (Isolate * isolate, DirectHandle< ArrayList > array, AllocationType allocation = AllocationType::kYoung) [static]
Definition at line 123 of file fixed-array.cc.
                                                                            {
  int length = array->length();
  if (length == 0) return isolate->factory()->empty_fixed_array();
  DirectHandle<FixedArray> result =
      FixedArray::New(isolate, length, allocation);
  DisallowGarbageCollection no_gc;
  WriteBarrierMode mode = result->GetWriteBarrierMode(no_gc);
  ObjectSlot dst_slot(result->RawFieldOfElementAt(0));
  ObjectSlot src_slot(array->RawFieldOfElementAt(0));
  isolate->heap()->CopyRange(*result, dst_slot, src_slot, length, mode);
  return result;
}
References v8::internal::Heap::CopyRange(), v8::internal::Isolate::factory(), v8::internal::Isolate::heap(), length(), mode(), v8::internal::FixedArray::New(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::base::internal::result.
Referenced by v8::internal::anonymous_namespace{snapshot.cc}::ConvertSerializedObjectsToFixedArray(), and v8::internal::Runtime::GetInternalProperties().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/fixed-array.h
/mnt/V8SourceCode/src/objects/fixed-array-inl.h
/mnt/V8SourceCode/src/objects/fixed-array.cc