v8::internal::EvacuationAllocator Class Reference
#include <evacuation-allocator.h>
Public Member Functions
EvacuationAllocator (Heap *heap, CompactionSpaceKind compaction_space_kind)
void Finalize ()
AllocationResult Allocate (AllocationSpace space, int object_size, AllocationAlignment alignment)
void FreeLast (AllocationSpace space, Tagged< HeapObject > object, int object_size)
Private Member Functions
void FreeLastInMainAllocator (MainAllocator *allocator, Tagged< HeapObject > object, int object_size)
MainAllocator * new_space_allocator ()
MainAllocator * old_space_allocator ()
MainAllocator * code_space_allocator ()
MainAllocator * shared_space_allocator ()
MainAllocator * trusted_space_allocator ()
Private Attributes
Heap *const heap_
NewSpace *const new_space_
CompactionSpaceCollection compaction_spaces_
std::optional< MainAllocator > new_space_allocator_
std::optional< MainAllocator > old_space_allocator_
std::optional< MainAllocator > code_space_allocator_
std::optional< MainAllocator > shared_space_allocator_
std::optional< MainAllocator > trusted_space_allocator_
Detailed Description
Definition at line 21 of file evacuation-allocator.h.
Constructor & Destructor Documentation
EvacuationAllocator()
v8::internal::EvacuationAllocator::EvacuationAllocator (Heap * heap, CompactionSpaceKind compaction_space_kind)
Definition at line 12 of file evacuation-allocator.cc.
    : heap_(heap),
      new_space_(heap->new_space()),
      compaction_spaces_(heap, compaction_space_kind) {
  if (new_space_) {
    DCHECK(!heap_->allocator()->new_space_allocator()->IsLabValid());
    new_space_allocator_.emplace(heap, new_space_, MainAllocator::kInGC);
  }
  old_space_allocator_.emplace(heap, compaction_spaces_.Get(OLD_SPACE),
                               MainAllocator::kInGC);
  code_space_allocator_.emplace(heap, compaction_spaces_.Get(CODE_SPACE),
                                MainAllocator::kInGC);
  if (heap_->isolate()->has_shared_space()) {
    shared_space_allocator_.emplace(heap, compaction_spaces_.Get(SHARED_SPACE),
                                    MainAllocator::kInGC);
  }
  trusted_space_allocator_.emplace(heap, compaction_spaces_.Get(TRUSTED_SPACE),
                                   MainAllocator::kInGC);
}
References v8::internal::Heap::allocator(), v8::internal::CODE_SPACE, code_space_allocator_, compaction_spaces_, v8::internal::DCHECK(), v8::internal::CompactionSpaceCollection::Get(), v8::internal::Isolate::has_shared_space(), heap_, v8::internal::MainAllocator::IsLabValid(), v8::internal::Heap::isolate(), v8::internal::MainAllocator::kInGC, new_space_, v8::internal::HeapAllocator::new_space_allocator(), new_space_allocator_, v8::internal::OLD_SPACE, old_space_allocator_, v8::internal::SHARED_SPACE, shared_space_allocator_, v8::internal::TRUSTED_SPACE, and trusted_space_allocator_.
Member Function Documentation
Allocate()
AllocationResult v8::internal::EvacuationAllocator::Allocate (AllocationSpace space, int object_size, AllocationAlignment alignment) [inline]
Definition at line 17 of file evacuation-allocator-inl.h.
                                                                              {
  DCHECK_IMPLIES(!shared_space_allocator_, space != SHARED_SPACE);
  object_size = ALIGN_TO_ALLOCATION_ALIGNMENT(object_size);
  switch (space) {
    case NEW_SPACE:
      return new_space_allocator()->AllocateRaw(
          object_size, alignment, AllocationOrigin::kGC, AllocationHint());
    case OLD_SPACE:
      return old_space_allocator()->AllocateRaw(
          object_size, alignment, AllocationOrigin::kGC, AllocationHint());
    case CODE_SPACE:
      return code_space_allocator()->AllocateRaw(
          object_size, alignment, AllocationOrigin::kGC, AllocationHint());
    case SHARED_SPACE:
      return shared_space_allocator()->AllocateRaw(
          object_size, alignment, AllocationOrigin::kGC, AllocationHint());
    case TRUSTED_SPACE:
      return trusted_space_allocator()->AllocateRaw(
          object_size, alignment, AllocationOrigin::kGC, AllocationHint());
    default:
      UNREACHABLE();
  }
}
References ALIGN_TO_ALLOCATION_ALIGNMENT, v8::internal::MainAllocator::AllocateRaw(), v8::internal::CODE_SPACE, code_space_allocator(), DCHECK_IMPLIES, v8::internal::kGC, v8::internal::NEW_SPACE, new_space_allocator(), v8::internal::OLD_SPACE, old_space_allocator(), v8::internal::SHARED_SPACE, shared_space_allocator(), shared_space_allocator_, space, v8::internal::TRUSTED_SPACE, trusted_space_allocator(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::EvacuateNewSpaceVisitor::AllocateInOldSpace(), v8::internal::EvacuateNewSpaceVisitor::AllocateTargetObject(), v8::internal::Scavenger::PromoteObject(), v8::internal::Scavenger::SemiSpaceCopyObject(), and v8::internal::EvacuateVisitorBase::TryEvacuateObject().
code_space_allocator()
MainAllocator* v8::internal::EvacuationAllocator::code_space_allocator () [inline], [private]
Definition at line 40 of file evacuation-allocator.h.
                                        {
    return &code_space_allocator_.value();
  }
References code_space_allocator_.
Referenced by Allocate(), and Finalize().
Finalize()
void v8::internal::EvacuationAllocator::Finalize ()
Definition at line 63 of file evacuation-allocator.cc.
                                   {
  if (new_space_) {
    new_space_allocator()->FreeLinearAllocationArea();
  }
  old_space_allocator()->FreeLinearAllocationArea();
  heap_->old_space()->MergeCompactionSpace(compaction_spaces_.Get(OLD_SPACE));
  code_space_allocator()->FreeLinearAllocationArea();
  heap_->code_space()->MergeCompactionSpace(compaction_spaces_.Get(CODE_SPACE));
  if (shared_space_allocator_) {
    shared_space_allocator_->FreeLinearAllocationArea();
    heap_->shared_allocation_space()->MergeCompactionSpace(
        compaction_spaces_.Get(SHARED_SPACE));
  }
  trusted_space_allocator()->FreeLinearAllocationArea();
  heap_->trusted_space()->MergeCompactionSpace(
      compaction_spaces_.Get(TRUSTED_SPACE));
}
References v8::internal::CODE_SPACE, v8::internal::Heap::code_space(), code_space_allocator(), compaction_spaces_, v8::internal::MainAllocator::FreeLinearAllocationArea(), v8::internal::CompactionSpaceCollection::Get(), heap_, v8::internal::PagedSpaceBase::MergeCompactionSpace(), new_space_, new_space_allocator(), v8::internal::OLD_SPACE, v8::internal::Heap::old_space(), old_space_allocator(), v8::internal::Heap::shared_allocation_space(), v8::internal::SHARED_SPACE, shared_space_allocator_, v8::internal::TRUSTED_SPACE, v8::internal::Heap::trusted_space(), and trusted_space_allocator().
FreeLast()
void v8::internal::EvacuationAllocator::FreeLast (AllocationSpace space, Tagged< HeapObject > object, int object_size)
Definition at line 34 of file evacuation-allocator.cc.
                                                                               {
  DCHECK_IMPLIES(!shared_space_allocator_, space != SHARED_SPACE);
  object_size = ALIGN_TO_ALLOCATION_ALIGNMENT(object_size);
  switch (space) {
    case NEW_SPACE:
      FreeLastInMainAllocator(new_space_allocator(), object, object_size);
      return;
    case OLD_SPACE:
      FreeLastInMainAllocator(old_space_allocator(), object, object_size);
      return;
    case SHARED_SPACE:
      FreeLastInMainAllocator(shared_space_allocator(), object, object_size);
      return;
    default:
      // Only new and old space supported.
      UNREACHABLE();
  }
}
References ALIGN_TO_ALLOCATION_ALIGNMENT, DCHECK_IMPLIES, FreeLastInMainAllocator(), v8::internal::NEW_SPACE, new_space_allocator(), v8::internal::OLD_SPACE, old_space_allocator(), v8::internal::SHARED_SPACE, shared_space_allocator(), shared_space_allocator_, space, and v8::internal::UNREACHABLE().
Referenced by v8::internal::Scavenger::PromoteObject(), and v8::internal::Scavenger::SemiSpaceCopyObject().
FreeLastInMainAllocator()
void v8::internal::EvacuationAllocator::FreeLastInMainAllocator (MainAllocator * allocator, Tagged< HeapObject > object, int object_size) [private]
Definition at line 54 of file evacuation-allocator.cc.
                                                                   {
  if (!allocator->TryFreeLast(object.address(), object_size)) {
    // We couldn't free the last object so we have to write a proper filler.
    heap_->CreateFillerObjectAt(object.address(), object_size);
  }
}
References v8::internal::Heap::CreateFillerObjectAt(), heap_, and v8::internal::MainAllocator::TryFreeLast().
Referenced by FreeLast().
new_space_allocator()
MainAllocator* v8::internal::EvacuationAllocator::new_space_allocator () [inline], [private]
Definition at line 38 of file evacuation-allocator.h.
{ return &new_space_allocator_.value(); }
References new_space_allocator_.
Referenced by Allocate(), Finalize(), and FreeLast().
old_space_allocator()
MainAllocator* v8::internal::EvacuationAllocator::old_space_allocator () [inline], [private]
Definition at line 39 of file evacuation-allocator.h.
{ return &old_space_allocator_.value(); }
References old_space_allocator_.
Referenced by Allocate(), Finalize(), and FreeLast().
shared_space_allocator()
MainAllocator* v8::internal::EvacuationAllocator::shared_space_allocator () [inline], [private]
Definition at line 43 of file evacuation-allocator.h.
                                          {
    return &shared_space_allocator_.value();
  }
References shared_space_allocator_.
Referenced by Allocate(), and FreeLast().
trusted_space_allocator()
MainAllocator* v8::internal::EvacuationAllocator::trusted_space_allocator () [inline], [private]
Definition at line 46 of file evacuation-allocator.h.
                                           {
    return &trusted_space_allocator_.value();
  }
References trusted_space_allocator_.
Referenced by Allocate(), and Finalize().
Member Data Documentation
code_space_allocator_
std::optional<MainAllocator> v8::internal::EvacuationAllocator::code_space_allocator_ [private]
Definition at line 55 of file evacuation-allocator.h.
Referenced by code_space_allocator(), and EvacuationAllocator().
compaction_spaces_
CompactionSpaceCollection v8::internal::EvacuationAllocator::compaction_spaces_ [private]
Definition at line 52 of file evacuation-allocator.h.
Referenced by EvacuationAllocator(), and Finalize().
heap_
Heap* const v8::internal::EvacuationAllocator::heap_ [private]
Definition at line 50 of file evacuation-allocator.h.
Referenced by EvacuationAllocator(), Finalize(), and FreeLastInMainAllocator().
new_space_
NewSpace* const v8::internal::EvacuationAllocator::new_space_ [private]
Definition at line 51 of file evacuation-allocator.h.
Referenced by EvacuationAllocator(), and Finalize().
new_space_allocator_
std::optional<MainAllocator> v8::internal::EvacuationAllocator::new_space_allocator_ [private]
Definition at line 53 of file evacuation-allocator.h.
Referenced by EvacuationAllocator(), and new_space_allocator().
old_space_allocator_
std::optional<MainAllocator> v8::internal::EvacuationAllocator::old_space_allocator_ [private]
Definition at line 54 of file evacuation-allocator.h.
Referenced by EvacuationAllocator(), and old_space_allocator().
shared_space_allocator_
std::optional<MainAllocator> v8::internal::EvacuationAllocator::shared_space_allocator_ [private]
Definition at line 56 of file evacuation-allocator.h.
Referenced by Allocate(), EvacuationAllocator(), Finalize(), FreeLast(), and shared_space_allocator().
trusted_space_allocator_
std::optional<MainAllocator> v8::internal::EvacuationAllocator::trusted_space_allocator_ [private]
Definition at line 57 of file evacuation-allocator.h.
Referenced by EvacuationAllocator(), and trusted_space_allocator().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/evacuation-allocator.h
/mnt/V8SourceCode/src/heap/evacuation-allocator-inl.h
/mnt/V8SourceCode/src/heap/evacuation-allocator.cc