v8::internal::compiler::TypedCodeAssemblerVariable< T > Class Template Reference
#include <code-assembler.h>
Public Member Functions
TypedCodeAssemblerVariable (TNode< T > initial_value, CodeAssembler *assembler)
TypedCodeAssemblerVariable (CodeAssembler *assembler)
TNode< T > value () const
void operator= (TNode< T > value)
void operator= (const TypedCodeAssemblerVariable< T > &variable)
Private Member Functions
void Bind (Node *value)
Additional Inherited Members
Detailed Description
template<class T>
class v8::internal::compiler::TypedCodeAssemblerVariable< T >
Definition at line 1723 of file code-assembler.h.
Constructor & Destructor Documentation
TypedCodeAssemblerVariable() [1/2]
template<class T >
v8::internal::compiler::TypedCodeAssemblerVariable< T >::TypedCodeAssemblerVariable (TNode< T > initial_value, CodeAssembler * assembler) [inline]
Definition at line 1725 of file code-assembler.h.
      : CodeAssemblerVariable(assembler, PhiMachineRepresentationOf<T>,
                              initial_value) {}
TypedCodeAssemblerVariable() [2/2]
template<class T >
v8::internal::compiler::TypedCodeAssemblerVariable< T >::TypedCodeAssemblerVariable (CodeAssembler * assembler) [inline], [explicit]
Definition at line 1728 of file code-assembler.h.
      : CodeAssemblerVariable(assembler, PhiMachineRepresentationOf<T>) {}
Member Function Documentation
Bind()
template<class T >
void v8::internal::compiler::CodeAssemblerVariable::Bind [private]
Definition at line 1703 of file code-assembler.cc.
{ impl_->value_ = value; }
Referenced by v8::internal::compiler::TypedCodeAssemblerVariable< T >::operator=().
operator=() [1/2]
template<class T >
void v8::internal::compiler::TypedCodeAssemblerVariable< T >::operator= (const TypedCodeAssemblerVariable< T > & variable) [inline]
Definition at line 1746 of file code-assembler.h.
                                                                {
    Bind(variable.value());
  }
References v8::internal::compiler::TypedCodeAssemblerVariable< T >::Bind(), and v8::internal::compiler::TypedCodeAssemblerVariable< T >::value().
operator=() [2/2]
template<class T >
void v8::internal::compiler::TypedCodeAssemblerVariable< T >::operator= (TNode< T > value) [inline]
Definition at line 1745 of file code-assembler.h.
{ Bind(value); }
References v8::internal::compiler::TypedCodeAssemblerVariable< T >::Bind(), and v8::internal::compiler::TypedCodeAssemblerVariable< T >::value().
value()
template<class T >
TNode<T> v8::internal::compiler::TypedCodeAssemblerVariable< T >::value () const [inline]
Definition at line 1741 of file code-assembler.h.
                         {
    return TNode<T>::UncheckedCast(CodeAssemblerVariable::value());
  }
References v8::internal::TNode< T >::UncheckedCast(), and v8::internal::compiler::CodeAssemblerVariable::value().
Referenced by v8::internal::CodeStubAssembler::BigIntToRawBytes(), v8::internal::CodeStubAssembler::BuildAppendJSArray(), v8::internal::CodeStubAssembler::BuildFastLoop(), v8::internal::SlowBoilerplateCloneAssembler::CloneIfObjectOrArray(), v8::internal::CodeStubAssembler::CombineFeedback(), v8::internal::StringBuiltinsAssembler::DerefIndirectString(), v8::internal::CodeStubAssembler::FindNonDefaultConstructor(), v8::internal::CollectionsBuiltinsAssembler::GetEntriesIfFastCollectionOrIterable(), v8::internal::AccessorAssembler::HandleLoadICProtoHandler(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerLoadNamedCase(), v8::internal::CodeStubAssembler::Increment(), v8::internal::CodeStubAssembler::LoadModuleContext(), v8::internal::StringBuiltinsAssembler::MaybeDerefIndirectString(), v8::internal::CodeStubAssembler::NumberDictionaryLookup(), v8::internal::compiler::TypedCodeAssemblerVariable< T >::operator=(), v8::internal::CodeStubAssembler::PossiblyGrowElementsCapacity(), v8::internal::CodeStubAssembler::SharedValueBarrier(), v8::internal::CodeStubAssembler::TryGetOwnProperty(), and v8::internal::AccessorAssembler::TryMegaDOMCase().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/code-assembler.h