v8::internal::anonymous_namespace{mark-compact.cc}::ClearStringTableJobItem Class Reference
Public Member Functions
ClearStringTableJobItem (Isolate *isolate)
void Run (JobDelegate *delegate) final
uint64_t trace_id () const
Private Attributes
Isolate *const isolate_
const uint64_t trace_id_
Detailed Description
Definition at line 2614 of file mark-compact.cc.
Constructor & Destructor Documentation
ClearStringTableJobItem()
v8::internal::anonymous_namespace{mark-compact.cc}::ClearStringTableJobItem::ClearStringTableJobItem (Isolate * isolate) [inline], [explicit]
Definition at line 2616 of file mark-compact.cc.
      : isolate_(isolate),
        trace_id_(reinterpret_cast<uint64_t>(this) ^
                  isolate->heap()->tracer()->CurrentEpoch(
                      GCTracer::Scope::MC_CLEAR_STRING_TABLE)) {}
Member Function Documentation
Run()
void v8::internal::anonymous_namespace{mark-compact.cc}::ClearStringTableJobItem::Run (JobDelegate * delegate) [inline], [final], [virtual]
Implements v8::internal::anonymous_namespace{mark-compact.cc}::ParallelClearingJob::ClearingItem.
Definition at line 2622 of file mark-compact.cc.
                                        {
    // Set the current isolate such that trusted pointer tables etc are
    // available and the cage base is set correctly for multi-cage mode.
    SetCurrentIsolateScope isolate_scope(isolate_);
    if (isolate_->OwnsStringTables()) {
      TRACE_GC1_WITH_FLOW(isolate_->heap()->tracer(),
                          GCTracer::Scope::MC_CLEAR_STRING_TABLE,
                          delegate->IsJoiningThread() ? ThreadKind::kMain
                                                      : ThreadKind::kBackground,
                          trace_id_, TRACE_EVENT_FLAG_FLOW_IN);
      // Prune the string table removing all strings only pointed to by the
      // string table. Cannot use string_table() here because the string
      // table is marked.
      StringTable* string_table = isolate_->string_table();
      InternalizedStringTableCleaner internalized_visitor(isolate_->heap());
      string_table->DropOldData();
      string_table->IterateElements(&internalized_visitor);
      string_table->NotifyElementsRemoved(
          internalized_visitor.PointersRemoved());
    }
  }
References v8::internal::StringTable::DropOldData(), v8::internal::StringTable::IterateElements(), v8::internal::StringTable::NotifyElementsRemoved(), v8::internal::InternalizedStringTableCleaner::PointersRemoved(), TRACE_EVENT_FLAG_FLOW_IN, and TRACE_GC1_WITH_FLOW.
trace_id()
uint64_t v8::internal::anonymous_namespace{mark-compact.cc}::ClearStringTableJobItem::trace_id () const [inline]
Definition at line 2645 of file mark-compact.cc.
{ return trace_id_; }
Member Data Documentation
isolate_
Isolate* const v8::internal::anonymous_namespace{mark-compact.cc}::ClearStringTableJobItem::isolate_ [private]
Definition at line 2648 of file mark-compact.cc.
trace_id_
const uint64_t v8::internal::anonymous_namespace{mark-compact.cc}::ClearStringTableJobItem::trace_id_ [private]
Definition at line 2649 of file mark-compact.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/mark-compact.cc