v8::internal::NativeRegExpMacroAssembler Class Reference
#include <regexp-macro-assembler.h>
Public Types
enum Mode { LATIN1 = 1
, UC16 = 2
 }
enum Result {
FAILURE = RegExp::kInternalRegExpFailure
, SUCCESS = RegExp::kInternalRegExpSuccess
, EXCEPTION = RegExp::kInternalRegExpException
, RETRY = RegExp::kInternalRegExpRetry
,
FALLBACK_TO_EXPERIMENTAL = RegExp::kInternalRegExpFallbackToExperimental
, SMALLEST_REGEXP_RESULT = RegExp::kInternalRegExpSmallestResult
 }
Public Member Functions
NativeRegExpMacroAssembler (Isolate *isolate, Zone *zone)
~NativeRegExpMacroAssembler () override=default
bool CanReadUnaligned () const override
void LoadCurrentCharacterImpl (int cp_offset, Label *on_end_of_input, bool check_bounds, int characters, int eats_at_least) override
virtual void LoadCurrentCharacterUnchecked (int cp_offset, int character_count)=0
Static Public Member Functions
static int Match (DirectHandle< IrRegExpData > regexp_data, DirectHandle< String > subject, int *offsets_vector, int offsets_vector_length, int previous_index, Isolate *isolate)
static V8_EXPORT_PRIVATE int ExecuteForTesting (Tagged< String > input, int start_offset, const uint8_t *input_start, const uint8_t *input_end, int *output, int output_size, Isolate *isolate, Tagged< JSRegExp > regexp)
static Address GrowStack (Isolate *isolate)
static int CheckStackGuardState (Isolate *isolate, int start_index, RegExp::CallOrigin call_origin, Address *return_address, Tagged< InstructionStream > re_code, Address *subject, const uint8_t **input_start, const uint8_t **input_end, uintptr_t gap)
static Address word_character_map_address ()
Protected Member Functions
Handle< ByteArray > GetOrAddRangeArray (const ZoneList< CharacterRange > *ranges)
Static Protected Attributes
static const uint8_t word_character_map [256]
Static Private Member Functions
static int Execute (Tagged< String > input, int start_offset, const uint8_t *input_start, const uint8_t *input_end, int *output, int output_size, Isolate *isolate, Tagged< IrRegExpData > regexp_data)
Private Attributes
ZoneUnorderedMap< uint32_t, IndirectHandle< FixedUInt16Array > > range_array_cache_
Additional Inherited Members
Detailed Description
Definition at line 277 of file regexp-macro-assembler.h.
Member Enumeration Documentation
Mode
enum v8::internal::NativeRegExpMacroAssembler::Mode
Enumerator
LATIN1
UC16
Definition at line 280 of file regexp-macro-assembler.h.
{ LATIN1 = 1, UC16 = 2 };
Result
enum v8::internal::NativeRegExpMacroAssembler::Result
Enumerator
FAILURE
SUCCESS
EXCEPTION
RETRY
FALLBACK_TO_EXPERIMENTAL
SMALLEST_REGEXP_RESULT
Definition at line 293 of file regexp-macro-assembler.h.
              {
    FAILURE = RegExp::kInternalRegExpFailure,
    SUCCESS = RegExp::kInternalRegExpSuccess,
    EXCEPTION = RegExp::kInternalRegExpException,
    RETRY = RegExp::kInternalRegExpRetry,
    FALLBACK_TO_EXPERIMENTAL = RegExp::kInternalRegExpFallbackToExperimental,
    SMALLEST_REGEXP_RESULT = RegExp::kInternalRegExpSmallestResult,
  };
Constructor & Destructor Documentation
NativeRegExpMacroAssembler()
v8::internal::NativeRegExpMacroAssembler::NativeRegExpMacroAssembler (Isolate * isolate, Zone * zone) [inline]
Definition at line 302 of file regexp-macro-assembler.h.
      : RegExpMacroAssembler(isolate, zone), range_array_cache_(zone) {}
 NativeRegExpMacroAssembler()
v8::internal::NativeRegExpMacroAssembler::~NativeRegExpMacroAssembler () [override], [default]
Member Function Documentation
CanReadUnaligned()
bool v8::internal::NativeRegExpMacroAssembler::CanReadUnaligned () const [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 276 of file regexp-macro-assembler.cc.
                                                        {
  return v8_flags.enable_regexp_unaligned_accesses && !slow_safe();
}
References v8::internal::RegExpMacroAssembler::slow_safe(), and v8::internal::v8_flags.
Referenced by v8::internal::RegExpMacroAssemblerRISCV::LoadCurrentCharacterUnchecked().
CheckStackGuardState()
int v8::internal::NativeRegExpMacroAssembler::CheckStackGuardState (Isolate * isolate, int start_index, RegExp::CallOrigin call_origin, Address * return_address, Tagged< InstructionStream > re_code, Address * subject, const uint8_t ** input_start, const uint8_t ** input_end, uintptr_t gap) [static]
Definition at line 284 of file regexp-macro-assembler.cc.
                   {
  DisallowGarbageCollection no_gc;
  Address old_pc = PointerAuthentication::AuthenticatePC(return_address, 0);
  DCHECK_LE(re_code->instruction_start(), old_pc);
  DCHECK_LE(old_pc, re_code->code(kAcquireLoad)->instruction_end());
  StackLimitCheck check(isolate);
  bool js_has_overflowed = check.JsHasOverflowed(gap);
  if (call_origin == RegExp::CallOrigin::kFromJs) {
    // Direct calls from JavaScript can be interrupted in two ways:
    // 1. A real stack overflow, in which case we let the caller throw the
    // exception.
    // 2. The stack guard was used to interrupt execution for another purpose,
    // forcing the call through the runtime system.
    // Bug(v8:9540) Investigate why this method is called from JS although no
    // stackoverflow or interrupt is pending on ARM64. We return 0 in this case
    // to continue execution normally.
    if (js_has_overflowed) {
      return EXCEPTION;
    } else if (check.InterruptRequested()) {
      return RETRY;
    } else {
      return 0;
    }
  }
  DCHECK(call_origin == RegExp::CallOrigin::kFromRuntime);
  // Prepare for possible GC.
  HandleScope handles(isolate);
  DirectHandle<InstructionStream> code_handle(re_code, isolate);
  DirectHandle<String> subject_handle(Cast<String>(Tagged<Object>(*subject)),
                                      isolate);
  bool is_one_byte = String::IsOneByteRepresentationUnderneath(*subject_handle);
  int return_value = 0;
  {
    DisableGCMole no_gc_mole;
    if (js_has_overflowed) {
      AllowGarbageCollection yes_gc;
      isolate->StackOverflow();
      return_value = EXCEPTION;
    } else if (check.InterruptRequested()) {
      AllowGarbageCollection yes_gc;
      Tagged<Object> result = isolate->stack_guard()->HandleInterrupts();
      if (IsException(result, isolate)) return_value = EXCEPTION;
    }
    // We are not using operator == here because it does a slow DCHECK
    // CheckObjectComparisonAllowed() which might crash when trying to access
    // the page header of the stale pointer.
    if (!code_handle->SafeEquals(re_code)) { // Return address no longer valid
      // Overwrite the return address on the stack.
      intptr_t delta = code_handle->address() - re_code.address();
      Address new_pc = old_pc + delta;
      // TODO(v8:10026): avoid replacing a signed pointer.
      PointerAuthentication::ReplacePC(return_address, new_pc, 0);
    }
  }
  // If we continue, we need to update the subject string addresses.
  if (return_value == 0) {
    // String encoding might have changed.
    if (String::IsOneByteRepresentationUnderneath(*subject_handle) !=
        is_one_byte) {
      // If we changed between an LATIN1 and an UC16 string, the specialized
      // code cannot be used, and we need to restart regexp matching from
      // scratch (including, potentially, compiling a new version of the code).
      return_value = RETRY;
    } else {
      *subject = subject_handle->ptr();
      intptr_t byte_length = *input_end - *input_start;
      *input_start = subject_handle->AddressOfCharacterAt(start_index, no_gc);
      *input_end = *input_start + byte_length;
    }
  }
  return return_value;
}
References v8::internal::DirectHandle< T >::address(), v8::internal::Tagged< HeapObject >::address(), v8::internal::PointerAuthentication::AuthenticatePC(), v8::internal::call_origin, v8::internal::DCHECK(), DCHECK_LE, EXCEPTION, v8::internal::StackGuard::HandleInterrupts(), v8::internal::StackLimitCheck::InterruptRequested(), v8::internal::RegExpMacroAssembler::isolate(), v8::internal::String::IsOneByteRepresentationUnderneath(), v8::internal::StackLimitCheck::JsHasOverflowed(), v8::kAcquireLoad, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::PointerAuthentication::ReplacePC(), v8::base::internal::result, RETRY, v8::internal::Isolate::stack_guard(), and v8::internal::Isolate::StackOverflow().
Referenced by v8::internal::RegExpMacroAssemblerRISCV::CheckStackGuardState().
Execute()
int v8::internal::NativeRegExpMacroAssembler::Execute (Tagged< String > input, int start_offset, const uint8_t * input_start, const uint8_t * input_end, int * output, int output_size, Isolate * isolate, Tagged< IrRegExpData > regexp_data) [static], [private]
Definition at line 428 of file regexp-macro-assembler.cc.
                                      {
  bool is_one_byte = String::IsOneByteRepresentationUnderneath(input);
  Tagged<Code> code = regexp_data->code(isolate, is_one_byte);
  RegExp::CallOrigin call_origin = RegExp::CallOrigin::kFromRuntime;
  using RegexpMatcherSig =
      // NOLINTNEXTLINE(readability/casting)
      int(Address input_string, int start_offset, const uint8_t* input_start,
          const uint8_t* input_end, int* output, int output_size,
          int call_origin, Isolate* isolate, Address regexp_data);
  auto fn = GeneratedCode<RegexpMatcherSig>::FromCode(isolate, code);
  int result = fn.CallSandboxed(input.ptr(), start_offset, input_start,
                                input_end, output, output_size, call_origin,
                                isolate, regexp_data.ptr());
  DCHECK_GE(result, SMALLEST_REGEXP_RESULT);
  if (result == EXCEPTION && !isolate->has_exception()) {
    // We detected a stack overflow (on the backtrack stack) in RegExp code,
    // but haven't created the exception yet. Additionally, we allow heap
    // allocation because even though it invalidates {input_start} and
    // {input_end}, we are about to return anyway.
    AllowGarbageCollection allow_allocation;
    isolate->StackOverflow();
  }
  return result;
}
References v8::internal::call_origin, code, DCHECK_GE, EXCEPTION, v8::internal::GeneratedCode< Return, Args >::FromCode(), v8::internal::Isolate::has_exception(), v8::internal::RegExpMacroAssembler::isolate(), v8::internal::String::IsOneByteRepresentationUnderneath(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::base::internal::result, SMALLEST_REGEXP_RESULT, and v8::internal::Isolate::StackOverflow().
Referenced by ExecuteForTesting(), and Match().
ExecuteForTesting()
int v8::internal::NativeRegExpMacroAssembler::ExecuteForTesting (Tagged< String > input, int start_offset, const uint8_t * input_start, const uint8_t * input_end, int * output, int output_size, Isolate * isolate, Tagged< JSRegExp > regexp) [static]
Definition at line 417 of file regexp-macro-assembler.cc.
                             {
  Tagged<RegExpData> data = regexp->data(isolate);
  SBXCHECK(Is<IrRegExpData>(data));
  return Execute(input, start_offset, input_start, input_end, output,
                 output_size, isolate, Cast<IrRegExpData>(data));
}
References Execute(), v8::internal::RegExpMacroAssembler::isolate(), and SBXCHECK.
GetOrAddRangeArray()
Handle< ByteArray > v8::internal::NativeRegExpMacroAssembler::GetOrAddRangeArray (const ZoneList< CharacterRange > * ranges) [protected]
Definition at line 168 of file regexp-macro-assembler.cc.
                                            {
  const uint32_t hash = Hash(ranges);
  if (range_array_cache_.count(hash) != 0) {
    Handle<FixedUInt16Array> range_array = range_array_cache_[hash];
    if (Equals(ranges, range_array)) return range_array;
  }
  Handle<FixedUInt16Array> range_array = MakeRangeArray(isolate(), ranges);
  range_array_cache_[hash] = range_array;
  return range_array;
}
References v8::internal::anonymous_namespace{regexp-macro-assembler.cc}::Equals(), v8::internal::Hash(), v8::internal::RegExpMacroAssembler::isolate(), v8::internal::anonymous_namespace{regexp-macro-assembler.cc}::MakeRangeArray(), and range_array_cache_.
Referenced by v8::internal::RegExpMacroAssemblerRISCV::CallIsCharacterInRangeArray().
GrowStack()
Address v8::internal::NativeRegExpMacroAssembler::GrowStack (Isolate * isolate) [static]
Definition at line 508 of file regexp-macro-assembler.cc.
                                                              {
  DisallowGarbageCollection no_gc;
  RegExpStack* regexp_stack = isolate->regexp_stack();
  const size_t old_size = regexp_stack->memory_size();
#ifdef DEBUG
  const Address old_stack_top = regexp_stack->memory_top();
  const Address old_stack_pointer = regexp_stack->stack_pointer();
  CHECK_LE(old_stack_pointer, old_stack_top);
  CHECK_LE(static_cast<size_t>(old_stack_top - old_stack_pointer), old_size);
#endif // DEBUG
  Address new_stack_base = regexp_stack->EnsureCapacity(old_size * 2);
  if (new_stack_base == kNullAddress) return kNullAddress;
  return regexp_stack->stack_pointer();
}
References CHECK_LE, v8::internal::RegExpStack::EnsureCapacity(), v8::internal::RegExpMacroAssembler::isolate(), v8::internal::kNullAddress, v8::internal::RegExpStack::memory_size(), v8::internal::RegExpStack::memory_top(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Isolate::regexp_stack(), and v8::internal::RegExpStack::stack_pointer().
LoadCurrentCharacterImpl()
void v8::internal::NativeRegExpMacroAssembler::LoadCurrentCharacterImpl (int cp_offset, Label * on_end_of_input, bool check_bounds, int characters, int eats_at_least) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 258 of file regexp-macro-assembler.cc.
                       {
  // It's possible to preload a small number of characters when each success
  // path requires a large number of characters, but not the reverse.
  DCHECK_GE(eats_at_least, characters);
  DCHECK(base::IsInRange(cp_offset, kMinCPOffset, kMaxCPOffset));
  if (check_bounds) {
    if (cp_offset >= 0) {
      CheckPosition(cp_offset + eats_at_least - 1, on_end_of_input);
    } else {
      CheckPosition(cp_offset, on_end_of_input);
    }
  }
  LoadCurrentCharacterUnchecked(cp_offset, characters);
}
References v8::internal::RegExpMacroAssembler::CheckPosition(), v8::internal::DCHECK(), DCHECK_GE, v8::internal::RegExpMacroAssembler::kMaxCPOffset, v8::internal::RegExpMacroAssembler::kMinCPOffset, and LoadCurrentCharacterUnchecked().
LoadCurrentCharacterUnchecked()
virtual void v8::internal::NativeRegExpMacroAssembler::LoadCurrentCharacterUnchecked (int cp_offset, int character_count) [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by LoadCurrentCharacterImpl().
Match()
int v8::internal::NativeRegExpMacroAssembler::Match (DirectHandle< IrRegExpData > regexp_data, DirectHandle< String > subject, int * offsets_vector, int offsets_vector_length, int previous_index, Isolate * isolate) [static]
Definition at line 369 of file regexp-macro-assembler.cc.
                                                                            {
  DCHECK(subject->IsFlat());
  DCHECK_LE(0, previous_index);
  DCHECK_LE(previous_index, subject->length());
  // No allocations before calling the regexp, but we can't use
  // DisallowGarbageCollection, since regexps might be preempted, and another
  // thread might do allocation anyway.
  Tagged<String> subject_ptr = *subject;
  // Character offsets into string.
  int start_offset = previous_index;
  int char_length = subject_ptr->length() - start_offset;
  int slice_offset = 0;
  // The string has been flattened, so if it is a cons string it contains the
  // full string in the first part.
  if (StringShape(subject_ptr).IsCons()) {
    DCHECK_EQ(0, Cast<ConsString>(subject_ptr)->second()->length());
    subject_ptr = Cast<ConsString>(subject_ptr)->first();
  } else if (StringShape(subject_ptr).IsSliced()) {
    Tagged<SlicedString> slice = Cast<SlicedString>(subject_ptr);
    subject_ptr = slice->parent();
    slice_offset = slice->offset();
  }
  if (StringShape(subject_ptr).IsThin()) {
    subject_ptr = Cast<ThinString>(subject_ptr)->actual();
  }
  // Ensure that an underlying string has the same representation.
  bool is_one_byte = subject_ptr->IsOneByteRepresentation();
  DCHECK(IsExternalString(subject_ptr) || IsSeqString(subject_ptr));
  // String is now either Sequential or External
  int char_size_shift = is_one_byte ? 0 : 1;
  DisallowGarbageCollection no_gc;
  const uint8_t* input_start =
      subject_ptr->AddressOfCharacterAt(start_offset + slice_offset, no_gc);
  int byte_length = char_length << char_size_shift;
  const uint8_t* input_end = input_start + byte_length;
  return Execute(*subject, start_offset, input_start, input_end, offsets_vector,
                 offsets_vector_length, isolate, *regexp_data);
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LE, Execute(), v8::internal::InstanceTypeChecker::IsExternalString(), v8::internal::RegExpMacroAssembler::isolate(), v8::internal::InstanceTypeChecker::IsSeqString(), v8::internal::length, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::RegExpImpl::IrregexpExecRaw().
word_character_map_address()
static Address v8::internal::NativeRegExpMacroAssembler::word_character_map_address () [inline], [static]
Definition at line 343 of file regexp-macro-assembler.h.
                                              {
    return reinterpret_cast<Address>(&word_character_map[0]);
  }
References word_character_map.
Referenced by v8::internal::FUNCTION_REFERENCE().
Member Data Documentation
range_array_cache_
ZoneUnorderedMap<uint32_t, IndirectHandle<FixedUInt16Array> > v8::internal::NativeRegExpMacroAssembler::range_array_cache_ [private]
Definition at line 363 of file regexp-macro-assembler.h.
Referenced by GetOrAddRangeArray().
word_character_map
const uint8_t v8::internal::NativeRegExpMacroAssembler::word_character_map [static], [protected]
Definition at line 351 of file regexp-macro-assembler.h.
Referenced by word_character_map_address().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-macro-assembler.h
/mnt/V8SourceCode/src/regexp/regexp-macro-assembler.cc