v8::internal::ThreadIsolation Class Reference
#include <code-memory-access.h>
Classes
class JitAllocation
class JitPage
class JitPageReference
struct StlAllocator
struct TrustedData
Public Types
enum class JitAllocationType {
kInstructionStream
, kWasmCode
, kWasmJumpTable
, kWasmFarJumpTable
,
kWasmLazyCompileTable
 }
Static Public Member Functions
static bool Enabled ()
static void Initialize (ThreadIsolatedAllocator *allocator)
static void RegisterJitPage (Address address, size_t size)
static void UnregisterJitPage (Address address, size_t size)
static bool MakeExecutable (Address address, size_t size)
static WritableJitAllocation RegisterJitAllocation (Address addr, size_t size, JitAllocationType type, bool enforce_write_api=false)
static WritableJitAllocation RegisterInstructionStreamAllocation (Address addr, size_t size, bool enforce_write_api=false)
static void RegisterJitAllocations (Address start, const std::vector< size_t > &sizes, JitAllocationType type)
static WritableJitAllocation LookupJitAllocation (Address addr, size_t size, JitAllocationType type, bool enforce_write_api=false)
static WritableJitPage LookupWritableJitPage (Address addr, size_t size)
static void UnregisterWasmAllocation (Address addr, size_t size)
static bool CanLookupStartOfJitAllocationAt (Address inner_pointer)
static std::optional< Address > StartOfJitAllocationAt (Address inner_pointer)
static bool WriteProtectMemory (Address addr, size_t size, PageAllocator::Permission page_permissions)
static void RegisterJitAllocationForTesting (Address obj, size_t size)
static void UnregisterJitAllocationForTesting (Address addr, size_t size)
Private Types
typedef std::map< Address, JitPage *, std::less< Address >, StlAllocator< std::pair< const Address, JitPage * > > > JitPageMap
Static Private Member Functions
static ThreadIsolatedAllocator * allocator ()
template<typename T , typename... Args>
static void ConstructNew (T **ptr, Args &&... args)
template<typename T >
static void Delete (T *ptr)
static JitPageReference LookupJitPage (Address addr, size_t size)
static JitPageReference LookupJitPageLocked (Address addr, size_t size)
static std::optional< JitPageReference > TryLookupJitPage (Address addr, size_t size)
static std::optional< JitPageReference > TryLookupJitPageLocked (Address addr, size_t size)
static JitPageReference SplitJitPageLocked (Address addr, size_t size)
static JitPageReference SplitJitPage (Address addr, size_t size)
static std::pair< JitPageReference, JitPageReference > SplitJitPages (Address addr1, size_t size1, Address addr2, size_t size2)
Static Private Attributes
static struct TrustedData trusted_data_
Friends
template<class T >
struct StlAllocator
class WritableJitPage
class WritableJitAllocation
class WritableJumpTablePair
Detailed Description
Definition at line 137 of file code-memory-access.h.
Member Typedef Documentation
JitPageMap
typedef std::map<Address, JitPage*, std::less<Address>, StlAllocator<std::pair<const Address, JitPage*> > > v8::internal::ThreadIsolation::JitPageMap [private]
Definition at line 329 of file code-memory-access.h.
Member Enumeration Documentation
JitAllocationType
enum v8::internal::ThreadIsolation::JitAllocationType [strong]
Enumerator
kInstructionStream
kWasmCode
kWasmJumpTable
kWasmFarJumpTable
kWasmLazyCompileTable
Definition at line 142 of file code-memory-access.h.
                               {
    kInstructionStream,
    kWasmCode,
    kWasmJumpTable,
    kWasmFarJumpTable,
    kWasmLazyCompileTable,
  };
Member Function Documentation
allocator()
static ThreadIsolatedAllocator* v8::internal::ThreadIsolation::allocator () [inline], [static], [private]
Definition at line 321 of file code-memory-access.h.
                                              {
    return trusted_data_.allocator;
  }
Referenced by v8::internal::ThreadIsolation::StlAllocator< T >::allocate(), v8::internal::ThreadIsolation::StlAllocator< T >::deallocate(), and Enabled().
CanLookupStartOfJitAllocationAt()
bool v8::internal::ThreadIsolation::CanLookupStartOfJitAllocationAt (Address inner_pointer) [static]
Definition at line 643 of file code-memory-access.cc.
                                                                           {
  CFIMetadataWriteScope write_scope("CanLookupStartOfJitAllocationAt");
  // Try to lock the pages mutex and the mutex of the page itself to prevent
  // potential dead locks. The profiler can try to do a lookup from a signal
  // handler. If that signal handler runs while the thread locked one of these
  // mutexes, it would result in a dead lock.
  if (!trusted_data_.jit_pages_mutex_->TryLock()) {
    return false;
  }
  MutexUnlocker pages_mutex_unlocker(*trusted_data_.jit_pages_mutex_);
  // upper_bound gives us an iterator to the position after address.
  auto it = trusted_data_.jit_pages_->upper_bound(inner_pointer);
  // The previous page should be the one we're looking for.
  if (it == trusted_data_.jit_pages_->begin()) {
    return {};
  }
  it--;
  JitPage* jit_page = it->second;
  if (jit_page->mutex_.TryLock()) {
    jit_page->mutex_.Unlock();
    return true;
  }
  return false;
}
References v8::internal::ThreadIsolation::TrustedData::jit_pages_, v8::internal::ThreadIsolation::TrustedData::jit_pages_mutex_, v8::internal::ThreadIsolation::JitPage::mutex_, trusted_data_, v8::base::Mutex::TryLock(), and v8::base::Mutex::Unlock().
Referenced by v8::internal::anonymous_namespace{frames.cc}::IsInterpreterFramePc().
ConstructNew()
template<typename T , typename... Args>
void v8::internal::ThreadIsolation::ConstructNew (T ** ptr, Args &&... args) [static], [private]
Definition at line 52 of file code-memory-access.cc.
                                                          {
  if (Enabled()) {
    *ptr = reinterpret_cast<T*>(trusted_data_.allocator->Allocate(sizeof(T)));
    if (!*ptr) return;
    new (*ptr) T(std::forward<Args>(args)...);
  } else {
    *ptr = new T(std::forward<Args>(args)...);
  }
}
References v8::ThreadIsolatedAllocator::Allocate(), v8::internal::ThreadIsolation::TrustedData::allocator, v8::base::args, Enabled(), T, and trusted_data_.
Referenced by Initialize(), RegisterJitPage(), SplitJitPageLocked(), and UnregisterJitPage().
Delete()
template<typename T >
void v8::internal::ThreadIsolation::Delete (T * ptr) [static], [private]
Definition at line 64 of file code-memory-access.cc.
                                   {
  if (Enabled()) {
    ptr->~T();
    trusted_data_.allocator->Free(ptr);
  } else {
    delete ptr;
  }
}
References v8::internal::ThreadIsolation::TrustedData::allocator, Enabled(), v8::ThreadIsolatedAllocator::Free(), and trusted_data_.
Referenced by TryLookupJitPageLocked(), and UnregisterJitPage().
Enabled()
bool v8::internal::ThreadIsolation::Enabled () [static]
Definition at line 42 of file code-memory-access.cc.
                              {
#if V8_HEAP_USE_PKU_JIT_WRITE_PROTECT
  return allocator() != nullptr;
#else
  return false;
#endif
}
References allocator().
Referenced by ConstructNew(), Delete(), v8::internal::CodeRange::InitReservation(), MakeExecutable(), v8::internal::CodeRange::RemapEmbeddedBuiltins(), v8::internal::wasm::WasmCodeManager::TryAllocate(), and WriteProtectMemory().
Initialize()
void v8::internal::ThreadIsolation::Initialize (ThreadIsolatedAllocator * allocator) [static]
Definition at line 74 of file code-memory-access.cc.
                                                        {
#if DEBUG
  trusted_data_.initialized = true;
#endif
  bool enable = thread_isolated_allocator != nullptr;
  if (v8_flags.jitless) {
    enable = v8_flags.force_memory_protection_keys;
  }
  DCHECK_IMPLIES(v8_flags.force_memory_protection_keys,
                 thread_isolated_allocator != nullptr);
#ifdef THREAD_SANITIZER
  // TODO(sroettger): with TSAN enabled, we get crashes because
  // SetDefaultPermissionsForAllKeysInSignalHandler gets called while a
  // RwxMemoryWriteScope is active. It seems that tsan's ProcessPendingSignals
  // doesn't restore the pkru value after executing the signal handler.
  enable = false;
#endif
#if V8_HAS_PKU_JIT_WRITE_PROTECT
  if (!v8_flags.memory_protection_keys ||
      !base::MemoryProtectionKey::HasMemoryProtectionKeyAPIs()) {
    DCHECK_IMPLIES(v8_flags.force_memory_protection_keys,
                   v8_flags.memory_protection_keys);
    DCHECK_IMPLIES(v8_flags.force_memory_protection_keys,
                   base::MemoryProtectionKey::HasMemoryProtectionKeyAPIs());
    enable = false;
  }
#endif
  if (enable) {
    trusted_data_.allocator = thread_isolated_allocator;
#if V8_HAS_PKU_JIT_WRITE_PROTECT
    trusted_data_.pkey = trusted_data_.allocator->Pkey();
    // We need to inform our MemoryProtectionKey class that there was an
    // externally-allocated pkey that we will be using. This is necessary for
    // signal handlers to have access to memory protected with this key. For
    // more details see https://crbug.com/416209124.
    base::MemoryProtectionKey::RegisterExternallyAllocatedKey(
        trusted_data_.pkey);
#endif
  }
  {
    // We need to allocate the memory for jit page tracking even if we don't
    // enable the ThreadIsolation protections.
    CFIMetadataWriteScope write_scope("Initialize thread isolation.");
    ConstructNew(&trusted_data_.jit_pages_mutex_);
    ConstructNew(&trusted_data_.jit_pages_);
  }
  CHECK_IMPLIES(v8_flags.force_memory_protection_keys, enable);
  if (!enable) {
    return;
  }
#if V8_HAS_PKU_JIT_WRITE_PROTECT
  // Check that our compile time assumed page size that we use for padding was
  // large enough.
  CHECK_GE(THREAD_ISOLATION_ALIGN_SZ,
           GetPlatformPageAllocator()->CommitPageSize());
  // TODO(sroettger): make this immutable once there's OS support.
  bool success = base::MemoryProtectionKey::SetPermissionsAndKey(
      {reinterpret_cast<Address>(&trusted_data_), sizeof(trusted_data_)},
      v8::PageAllocator::Permission::kRead,
      base::MemoryProtectionKey::kDefaultProtectionKey);
  CHECK_IMPLIES(v8_flags.force_memory_protection_keys, success);
#endif
}
References v8::internal::ThreadIsolation::TrustedData::allocator, CHECK_GE, CHECK_IMPLIES, v8::internal::CommitPageSize(), ConstructNew(), DCHECK_IMPLIES, v8::internal::GetPlatformPageAllocator(), v8::internal::ThreadIsolation::TrustedData::jit_pages_, v8::internal::ThreadIsolation::TrustedData::jit_pages_mutex_, v8::ThreadIsolatedAllocator::Pkey(), THREAD_ISOLATION_ALIGN_SZ, trusted_data_, and v8::internal::v8_flags.
Referenced by v8::internal::V8::Initialize().
LookupJitAllocation()
WritableJitAllocation v8::internal::ThreadIsolation::LookupJitAllocation (Address addr, size_t size, JitAllocationType type, bool enforce_write_api = false) [static]
Definition at line 503 of file code-memory-access.cc.
                                                                               {
  return WritableJitAllocation(
      addr, size, type, WritableJitAllocation::JitAllocationSource::kLookup,
      enforce_write_api);
}
References v8::internal::WritableJitAllocation::kLookup, size(), v8::internal::tracing::type, and WritableJitAllocation.
Referenced by v8::internal::wasm::NativeModule::AddCodeSpaceLocked(), v8::internal::wasm::NativeModule::AddCodeWithCodeSpace(), v8::internal::Code::ClearEmbeddedObjectsAndJSDispatchHandles(), v8::internal::InstructionStream::Finalize(), v8::internal::wasm::JumpTableAssembler::GenerateLazyCompileTable(), v8::internal::wasm::JumpTableAssembler::InitializeJumpsToLazyCompileTable(), and v8::internal::SetupIsolateDelegate::ReplacePlaceholders().
LookupJitPage()
ThreadIsolation::JitPageReference v8::internal::ThreadIsolation::LookupJitPage (Address addr, size_t size) [static], [private]
Definition at line 161 of file code-memory-access.cc.
                                                                              {
  base::MutexGuard guard(trusted_data_.jit_pages_mutex_);
  return LookupJitPageLocked(addr, size);
}
References v8::internal::ThreadIsolation::TrustedData::jit_pages_mutex_, LookupJitPageLocked(), size(), and trusted_data_.
Referenced by RegisterJitAllocations(), UnregisterJitAllocationForTesting(), and UnregisterWasmAllocation().
LookupJitPageLocked()
ThreadIsolation::JitPageReference v8::internal::ThreadIsolation::LookupJitPageLocked (Address addr, size_t size) [static], [private]
Definition at line 152 of file code-memory-access.cc.
                               {
  trusted_data_.jit_pages_mutex_->AssertHeld();
  std::optional<JitPageReference> jit_page = TryLookupJitPageLocked(addr, size);
  CHECK(jit_page.has_value());
  return std::move(jit_page.value());
}
References v8::base::Mutex::AssertHeld(), CHECK, v8::internal::ThreadIsolation::TrustedData::jit_pages_mutex_, size(), trusted_data_, and TryLookupJitPageLocked().
Referenced by LookupJitPage(), SplitJitPageLocked(), and UnregisterJitPage().
LookupWritableJitPage()
WritableJitPage v8::internal::ThreadIsolation::LookupWritableJitPage (Address addr, size_t size) [static]
Definition at line 168 of file code-memory-access.cc.
                                                                    {
  return WritableJitPage(addr, size);
}
References size(), and WritableJitPage.
Referenced by v8::internal::Scavenger::ScavengePage().
MakeExecutable()
bool v8::internal::ThreadIsolation::MakeExecutable (Address address, size_t size) [static]
Definition at line 474 of file code-memory-access.cc.
                                                                 {
  DCHECK(Enabled());
  // TODO(sroettger): ensure that this can only happen at prcoess startup.
#if V8_HAS_PKU_JIT_WRITE_PROTECT
  return base::MemoryProtectionKey::SetPermissionsAndKey(
      {address, size}, PageAllocator::Permission::kReadWriteExecute, pkey());
#else // V8_HAS_PKU_JIT_WRITE_PROTECT
  UNREACHABLE();
#endif // V8_HAS_PKU_JIT_WRITE_PROTECT
}
References v8::internal::DCHECK(), Enabled(), size(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::CodeRange::InitReservation(), and v8::internal::wasm::WasmCodeManager::TryAllocate().
RegisterInstructionStreamAllocation()
WritableJitAllocation v8::internal::ThreadIsolation::RegisterInstructionStreamAllocation (Address addr, size_t size, bool enforce_write_api = false) [static]
Definition at line 496 of file code-memory-access.cc.
                                                       {
  return RegisterJitAllocation(
      addr, size, JitAllocationType::kInstructionStream, enforce_write_api);
}
References kInstructionStream, RegisterJitAllocation(), and size().
Referenced by v8::internal::InstructionStream::Initialize(), and v8::internal::EvacuateVisitorBase::RawMigrateObject().
RegisterJitAllocation()
WritableJitAllocation v8::internal::ThreadIsolation::RegisterJitAllocation (Address addr, size_t size, JitAllocationType type, bool enforce_write_api = false) [static]
Definition at line 488 of file code-memory-access.cc.
                                                                              {
  return WritableJitAllocation(
      obj, size, type, WritableJitAllocation::JitAllocationSource::kRegister,
      enforce_write_api);
}
References v8::internal::WritableJitAllocation::kRegister, size(), v8::internal::tracing::type, and WritableJitAllocation.
Referenced by v8::internal::wasm::NativeModule::AddCode(), v8::internal::wasm::NativeModule::AddCodeForTesting(), v8::internal::wasm::WasmImportWrapperCache::ModificationScope::AddWrapper(), v8::internal::wasm::NativeModuleDeserializer::CopyAndRelocate(), v8::internal::wasm::NativeModule::CreateEmptyJumpTableInRegionLocked(), RegisterInstructionStreamAllocation(), and RegisterJitAllocationForTesting().
RegisterJitAllocationForTesting()
void v8::internal::ThreadIsolation::RegisterJitAllocationForTesting (Address obj, size_t size) [static]
Definition at line 532 of file code-memory-access.cc.
                                                                   {
  RegisterJitAllocation(obj, size, JitAllocationType::kInstructionStream);
}
References kInstructionStream, RegisterJitAllocation(), and size().
RegisterJitAllocations()
void v8::internal::ThreadIsolation::RegisterJitAllocations (Address start, const std::vector< size_t > & sizes, JitAllocationType type) [static]
Definition at line 511 of file code-memory-access.cc.
                                                                     {
  CFIMetadataWriteScope write_scope("Register bulk allocations.");
  size_t total_size = 0;
  for (auto size : sizes) {
    total_size += size;
  }
  constexpr size_t kSplitThreshold = 0x40000;
  JitPageReference page_ref = total_size >= kSplitThreshold
                                  ? SplitJitPage(start, total_size)
                                  : LookupJitPage(start, total_size);
  for (auto size : sizes) {
    page_ref.RegisterAllocation(start, size, type);
    start += size;
  }
}
References LookupJitPage(), v8::internal::ThreadIsolation::JitPageReference::RegisterAllocation(), size(), SplitJitPage(), and v8::internal::tracing::type.
Referenced by v8::internal::wasm::NativeModule::AddCompiledCode().
RegisterJitPage()
void v8::internal::ThreadIsolation::RegisterJitPage (Address address, size_t size) [static]
Definition at line 420 of file code-memory-access.cc.
                                                                  {
  CFIMetadataWriteScope write_scope("Adding new executable memory.");
  base::MutexGuard guard(trusted_data_.jit_pages_mutex_);
  CheckForRegionOverlap(*trusted_data_.jit_pages_, address, size);
  JitPage* jit_page;
  ConstructNew(&jit_page, size);
  trusted_data_.jit_pages_->emplace(address, jit_page);
}
References v8::internal::anonymous_namespace{code-memory-access.cc}::CheckForRegionOverlap(), ConstructNew(), v8::internal::ThreadIsolation::TrustedData::jit_pages_, v8::internal::ThreadIsolation::TrustedData::jit_pages_mutex_, size(), and trusted_data_.
Referenced by v8::internal::MemoryAllocator::AllocateAlignedMemory(), and v8::internal::wasm::WasmCodeManager::TryAllocate().
SplitJitPage()
ThreadIsolation::JitPageReference v8::internal::ThreadIsolation::SplitJitPage (Address addr, size_t size) [static], [private]
Definition at line 549 of file code-memory-access.cc.
                                                                             {
  base::MutexGuard guard(trusted_data_.jit_pages_mutex_);
  return SplitJitPageLocked(addr, size);
}
References v8::internal::ThreadIsolation::TrustedData::jit_pages_mutex_, size(), SplitJitPageLocked(), and trusted_data_.
Referenced by RegisterJitAllocations().
SplitJitPageLocked()
ThreadIsolation::JitPageReference v8::internal::ThreadIsolation::SplitJitPageLocked (Address addr, size_t size) [static], [private]
Definition at line 555 of file code-memory-access.cc.
                               {
  trusted_data_.jit_pages_mutex_->AssertHeld();
  JitPageReference jit_page = LookupJitPageLocked(addr, size);
  // Split the JitPage into upto three pages.
  size_t head_size = addr - jit_page.Address();
  size_t tail_size = jit_page.Size() - size - head_size;
  if (tail_size > 0) {
    JitPage* tail;
    ConstructNew(&tail, tail_size);
    jit_page.Shrink(tail);
    trusted_data_.jit_pages_->emplace(addr + size, tail);
  }
  if (head_size > 0) {
    JitPage* mid;
    ConstructNew(&mid, size);
    jit_page.Shrink(mid);
    trusted_data_.jit_pages_->emplace(addr, mid);
    return JitPageReference(mid, addr);
  }
  return jit_page;
}
References v8::internal::ThreadIsolation::JitPageReference::Address(), v8::base::Mutex::AssertHeld(), ConstructNew(), v8::internal::ThreadIsolation::TrustedData::jit_pages_, v8::internal::ThreadIsolation::TrustedData::jit_pages_mutex_, LookupJitPageLocked(), v8::internal::ThreadIsolation::JitPageReference::Shrink(), v8::internal::ThreadIsolation::JitPageReference::Size(), size(), and trusted_data_.
Referenced by SplitJitPage(), and SplitJitPages().
SplitJitPages()
std::pair< ThreadIsolation::JitPageReference, ThreadIsolation::JitPageReference > v8::internal::ThreadIsolation::SplitJitPages (Address addr1, size_t size1, Address addr2, size_t size2) [static], [private]
Definition at line 582 of file code-memory-access.cc.
                                             {
  if (addr1 > addr2) {
    auto reversed_pair = SplitJitPages(addr2, size2, addr1, size1);
    return {std::move(reversed_pair.second), std::move(reversed_pair.first)};
  }
  // Make sure there's no overlap. SplitJitPageLocked will do additional checks
  // that the sizes don't overflow.
  CHECK_LE(addr1 + size1, addr2);
  base::MutexGuard guard(trusted_data_.jit_pages_mutex_);
  return {SplitJitPageLocked(addr1, size1), SplitJitPageLocked(addr2, size2)};
}
References CHECK_LE, v8::internal::ThreadIsolation::TrustedData::jit_pages_mutex_, SplitJitPageLocked(), and trusted_data_.
StartOfJitAllocationAt()
std::optional< Address > v8::internal::ThreadIsolation::StartOfJitAllocationAt (Address inner_pointer) [static]
Definition at line 597 of file code-memory-access.cc.
                           {
  CFIMetadataWriteScope write_scope("StartOfJitAllocationAt");
  std::optional<JitPageReference> page = TryLookupJitPage(inner_pointer, 1);
  if (!page) {
    return {};
  }
  return page->StartOfAllocationAt(inner_pointer);
}
References TryLookupJitPage().
Referenced by v8::internal::Heap::GcSafeTryFindInstructionStreamForInnerPointer().
TryLookupJitPage()
std::optional< ThreadIsolation::JitPageReference > v8::internal::ThreadIsolation::TryLookupJitPage (Address addr, size_t size) [static], [private]
Definition at line 175 of file code-memory-access.cc.
                                                           {
  base::MutexGuard guard(trusted_data_.jit_pages_mutex_);
  return TryLookupJitPageLocked(addr, size);
}
References v8::internal::ThreadIsolation::TrustedData::jit_pages_mutex_, size(), trusted_data_, and TryLookupJitPageLocked().
Referenced by StartOfJitAllocationAt().
TryLookupJitPageLocked()
std::optional< ThreadIsolation::JitPageReference > v8::internal::ThreadIsolation::TryLookupJitPageLocked (Address addr, size_t size) [static], [private]
Definition at line 182 of file code-memory-access.cc.
                                                                 {
  trusted_data_.jit_pages_mutex_->AssertHeld();
  Address end = addr + size;
  CHECK_GT(end, addr);
  // upper_bound gives us an iterator to the position after address.
  auto it = trusted_data_.jit_pages_->upper_bound(addr);
  // The previous page should be the one we're looking for.
  if (it == trusted_data_.jit_pages_->begin()) {
    return {};
  }
  it--;
  JitPageReference jit_page(it->second, it->first);
  // If the address is not in the range of the jit page, return.
  if (jit_page.End() <= addr) {
    return {};
  }
  if (jit_page.End() >= end) {
    return jit_page;
  }
  // It's possible that the allocation spans multiple pages, merge them.
  auto to_delete_start = ++it;
  for (; jit_page.End() < end && it != trusted_data_.jit_pages_->end(); it++) {
    {
      JitPageReference next_page(it->second, it->first);
      CHECK_EQ(next_page.Address(), jit_page.End());
      jit_page.Merge(next_page);
    }
    Delete(it->second);
  }
  trusted_data_.jit_pages_->erase(to_delete_start, it);
  if (jit_page.End() < end) {
    return {};
  }
  return jit_page;
}
References v8::internal::ThreadIsolation::JitPageReference::Address(), v8::base::Mutex::AssertHeld(), CHECK_EQ, CHECK_GT, Delete(), v8::internal::ThreadIsolation::JitPageReference::End(), v8::internal::compiler::end(), v8::internal::ThreadIsolation::TrustedData::jit_pages_, v8::internal::ThreadIsolation::TrustedData::jit_pages_mutex_, v8::internal::ThreadIsolation::JitPageReference::Merge(), size(), and trusted_data_.
Referenced by LookupJitPageLocked(), and TryLookupJitPage().
UnregisterJitAllocationForTesting()
void v8::internal::ThreadIsolation::UnregisterJitAllocationForTesting (Address addr, size_t size) [static]
Definition at line 538 of file code-memory-access.cc.
                                                                     {
  LookupJitPage(addr, size).UnregisterAllocation(addr);
}
References LookupJitPage(), size(), and v8::internal::ThreadIsolation::JitPageReference::UnregisterAllocation().
UnregisterJitPage()
void v8::internal::ThreadIsolation::UnregisterJitPage (Address address, size_t size) [static]
Definition at line 430 of file code-memory-access.cc.
                                                                    {
  // TODO(sroettger): merge the write scopes higher up.
  CFIMetadataWriteScope write_scope("Removing executable memory.");
  JitPage* to_delete;
  {
    base::MutexGuard guard(trusted_data_.jit_pages_mutex_);
    JitPageReference jit_page = LookupJitPageLocked(address, size);
    // We're merging jit pages together, so potentially split them back up
    // if we're only freeing a subrange.
    Address to_free_end = address + size;
    Address jit_page_end = jit_page.Address() + jit_page.Size();
    if (to_free_end < jit_page_end) {
      // There's a tail after the page that we release. Shrink the page and
      // add the tail to the map.
      size_t tail_size = jit_page_end - to_free_end;
      JitPage* tail;
      ConstructNew(&tail, tail_size);
      jit_page.Shrink(tail);
      trusted_data_.jit_pages_->emplace(to_free_end, tail);
    }
    DCHECK_EQ(to_free_end, jit_page.Address() + jit_page.Size());
    if (address == jit_page.Address()) {
      // We remove the start of the region, just remove it from the map.
      to_delete = jit_page.JitPage();
      trusted_data_.jit_pages_->erase(address);
    } else {
      // Otherwise, we need to shrink the region.
      DCHECK_GT(address, jit_page.Address());
      JitPage* tail;
      ConstructNew(&tail, size);
      jit_page.Shrink(tail);
      to_delete = tail;
    }
  }
  Delete(to_delete);
}
References v8::internal::ThreadIsolation::JitPageReference::Address(), ConstructNew(), DCHECK_EQ, DCHECK_GT, Delete(), v8::internal::ThreadIsolation::TrustedData::jit_pages_, v8::internal::ThreadIsolation::TrustedData::jit_pages_mutex_, v8::internal::ThreadIsolation::JitPageReference::JitPage(), LookupJitPageLocked(), v8::internal::ThreadIsolation::JitPageReference::Shrink(), v8::internal::ThreadIsolation::JitPageReference::Size(), size(), and trusted_data_.
Referenced by v8::internal::wasm::WasmCodeManager::FreeNativeModule(), and v8::internal::MemoryAllocator::UnregisterMemoryChunk().
UnregisterWasmAllocation()
void v8::internal::ThreadIsolation::UnregisterWasmAllocation (Address addr, size_t size) [static]
Definition at line 544 of file code-memory-access.cc.
                                                                        {
  CFIMetadataWriteScope write_scope("UnregisterWasmAllocation");
  LookupJitPage(addr, size).UnregisterAllocation(addr);
}
References LookupJitPage(), size(), and v8::internal::ThreadIsolation::JitPageReference::UnregisterAllocation().
Referenced by v8::internal::wasm::WasmCodeAllocator::FreeCode().
WriteProtectMemory()
bool v8::internal::ThreadIsolation::WriteProtectMemory (Address addr, size_t size, PageAllocator::Permission page_permissions) [static]
Definition at line 608 of file code-memory-access.cc.
                                                                         {
  if (!Enabled()) {
    return true;
  }
#if V8_HEAP_USE_PKU_JIT_WRITE_PROTECT
  return base::MemoryProtectionKey::SetPermissionsAndKey(
      {addr, size}, PageAllocator::Permission::kNoAccess,
      ThreadIsolation::pkey());
#else
  UNREACHABLE();
#endif
}
References Enabled(), size(), and v8::internal::UNREACHABLE().
Friends And Related Function Documentation
StlAllocator
template<class T >
friend struct StlAllocator [friend]
Definition at line 378 of file code-memory-access.h.
WritableJitAllocation
friend class WritableJitAllocation [friend]
Definition at line 380 of file code-memory-access.h.
Referenced by v8::internal::WritableJitAllocation::ForInstructionStream(), LookupJitAllocation(), and RegisterJitAllocation().
WritableJitPage
friend class WritableJitPage [friend]
Definition at line 379 of file code-memory-access.h.
Referenced by LookupWritableJitPage().
WritableJumpTablePair
friend class WritableJumpTablePair [friend]
Definition at line 381 of file code-memory-access.h.
Member Data Documentation
trusted_data_
ThreadIsolation::TrustedData v8::internal::ThreadIsolation::trusted_data_ [static], [private]
Definition at line 329 of file code-memory-access.h.
Referenced by CanLookupStartOfJitAllocationAt(), ConstructNew(), Delete(), Initialize(), LookupJitPage(), LookupJitPageLocked(), RegisterJitPage(), SplitJitPage(), SplitJitPageLocked(), SplitJitPages(), TryLookupJitPage(), TryLookupJitPageLocked(), and UnregisterJitPage().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/common/code-memory-access.h
/mnt/V8SourceCode/src/common/code-memory-access.cc