v8::BooleanObject Class Reference
A Boolean object (ECMA-262, 4.3.15).
#include <v8-primitive-object.h>
Public Member Functions
bool ValueOf () const
Static Public Member Functions
static Local< Value > New (Isolate *isolate, bool value)
static BooleanObject * Cast (Value *value)
Static Private Member Functions
static void CheckCast (Value *obj)
Additional Inherited Members
Detailed Description
A Boolean object (ECMA-262, 4.3.15).
Definition at line 59 of file v8-primitive-object.h.
Member Function Documentation
Cast()
static BooleanObject* v8::BooleanObject::Cast (Value * value) [inline], [static]
Definition at line 65 of file v8-primitive-object.h.
                                                     {
#ifdef V8_ENABLE_CHECKS
    CheckCast(value);
#endif
    return static_cast<BooleanObject*>(value);
  }
References v8::internal::value.
CheckCast()
void v8::BooleanObject::CheckCast (v8::Value * that) [static], [private]
Definition at line 4159 of file api.cc.
                                             {
  auto obj = *Utils::OpenDirectHandle(that);
  Utils::ApiCheck(i::IsBooleanWrapper(obj), "v8::BooleanObject::Cast()",
                  "Value is not a BooleanObject");
}
References v8::Utils::ApiCheck(), and v8::Utils::OpenDirectHandle().
New()
Local< v8::Value > v8::BooleanObject::New (Isolate * isolate, bool value) [static]
Definition at line 7886 of file api.cc.
                                                                   {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  ApiRuntimeCallStatsScope rcs_scope(i_isolate, RCCId::kAPI_BooleanObject_New);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::DirectHandle<i::Object> boolean = i_isolate->factory()->ToBoolean(value);
  i::DirectHandle<i::Object> obj =
      i::Object::ToObject(i_isolate, boolean).ToHandleChecked();
  return Utils::ToLocal(obj);
}
References v8::internal::Isolate::factory(), v8::internal::FactoryBase< Impl >::ToBoolean(), v8::anonymous_namespace{api.cc}::ToObject(), and v8::internal::value.
ValueOf()
bool v8::BooleanObject::ValueOf () const
Definition at line 7896 of file api.cc.
                                    {
  i::Tagged<i::Object> obj = *Utils::OpenDirectHandle(this);
  i::Tagged<i::JSPrimitiveWrapper> js_primitive_wrapper =
      i::Cast<i::JSPrimitiveWrapper>(obj);
  i::Isolate* i_isolate = i::Isolate::Current();
  ApiRuntimeCallStatsScope rcs_scope(i_isolate,
                                     RCCId::kAPI_BooleanObject_BooleanValue);
  return i::IsTrue(js_primitive_wrapper->value(), i_isolate);
}
References v8::internal::Isolate::Current(), and v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::anonymous_namespace{v8-console-message.cc}::V8ValueStringBuilder::append().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-primitive-object.h
/mnt/V8SourceCode/src/api/api.cc