v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ProtectorDependency Class Reference
Public Member Functions
ProtectorDependency (PropertyCellRef cell)
bool IsValid (JSHeapBroker *broker) const override
void Install (JSHeapBroker *broker, PendingDependencies *deps) const override
Private Member Functions
size_t Hash () const override
bool Equals (const CompilationDependency *that) const override
Private Attributes
const PropertyCellRef cell_
Additional Inherited Members
Detailed Description
Definition at line 977 of file compilation-dependencies.cc.
Constructor & Destructor Documentation
ProtectorDependency()
v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ProtectorDependency::ProtectorDependency (PropertyCellRef cell) [inline], [explicit]
Definition at line 979 of file compilation-dependencies.cc.
      : CompilationDependency(kProtector), cell_(cell) {}
Member Function Documentation
Equals()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ProtectorDependency::Equals (const CompilationDependency * that) const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 997 of file compilation-dependencies.cc.
                                                                {
    const ProtectorDependency* const zat = that->AsProtector();
    return cell_.equals(zat->cell_);
  }
References cell_.
Hash()
size_t v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ProtectorDependency::Hash () const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 992 of file compilation-dependencies.cc.
                               {
    ObjectRef::Hash h;
    return base::hash_combine(h(cell_));
  }
References h(), v8::internal::Hash(), and v8::base::hash_combine().
Install()
void v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ProtectorDependency::Install (JSHeapBroker * broker, PendingDependencies * deps) const [inline], [override]
Definition at line 986 of file compilation-dependencies.cc.
                                                                               {
    SLOW_DCHECK(IsValid(broker));
    deps->Register(cell_.object(), DependentCode::kPropertyCellChangedGroup);
  }
References broker(), v8::internal::DependentCode::kPropertyCellChangedGroup, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PendingDependencies::Register(), and SLOW_DCHECK.
IsValid()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ProtectorDependency::IsValid (JSHeapBroker * broker) const [inline], [override], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 982 of file compilation-dependencies.cc.
                                                    {
    DirectHandle<PropertyCell> cell = cell_.object();
    return cell->value() == Smi::FromInt(Protectors::kProtectorValid);
  }
References v8::internal::Smi::FromInt(), and v8::internal::Protectors::kProtectorValid.
Member Data Documentation
cell_
const PropertyCellRef v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ProtectorDependency::cell_ [private]
Definition at line 1002 of file compilation-dependencies.cc.
Referenced by Equals().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/compilation-dependencies.cc