v8::internal::SourceCodeCache Class Reference
#include <bootstrapper.h>
Public Member Functions
SourceCodeCache (Script::Type type)
SourceCodeCache (const SourceCodeCache &)=delete
SourceCodeCache & operator= (const SourceCodeCache &)=delete
void Initialize (Isolate *isolate, bool create_heap_objects)
void Iterate (RootVisitor *v)
bool Lookup (Isolate *isolate, base::Vector< const char > name, DirectHandle< SharedFunctionInfo > *handle)
void Add (Isolate *isolate, base::Vector< const char > name, DirectHandle< SharedFunctionInfo > shared)
Private Attributes
Script::Type type_
Tagged< FixedArray > cache_
Detailed Description
Definition at line 23 of file bootstrapper.h.
Constructor & Destructor Documentation
SourceCodeCache() [1/2]
v8::internal::SourceCodeCache::SourceCodeCache (Script::Type type) [inline], [explicit]
Definition at line 25 of file bootstrapper.h.
: type_(type) {}
SourceCodeCache() [2/2]
v8::internal::SourceCodeCache::SourceCodeCache (const SourceCodeCache &) [delete]
Member Function Documentation
Add()
void v8::internal::SourceCodeCache::Add (Isolate * isolate, base::Vector< const char > name, DirectHandle< SharedFunctionInfo > shared)
Definition at line 120 of file bootstrapper.cc.
                                                                   {
  Factory* factory = isolate->factory();
  HandleScope scope(isolate);
  int length = cache_->length();
  DirectHandle<FixedArray> new_array =
      factory->NewFixedArray(length + 2, AllocationType::kOld);
  FixedArray::CopyElements(isolate, *new_array, 0, cache_, 0, cache_->length());
  cache_ = *new_array;
  DirectHandle<String> str =
      factory
          ->NewStringFromOneByte(base::Vector<const uint8_t>::cast(name),
                                 AllocationType::kOld)
          .ToHandleChecked();
  DCHECK(!str.is_null());
  cache_->set(length, *str);
  cache_->set(length + 1, *shared);
  Cast<Script>(shared->script())->set_type(type_);
}
References cache_, v8::internal::FixedArray::CopyElements(), v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::DirectHandle< T >::is_null(), v8::internal::kOld, v8::internal::length, v8::internal::name, v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::FactoryBase< Impl >::NewStringFromOneByte(), and type_.
Referenced by v8::internal::Genesis::CompileExtension().
Initialize()
void v8::internal::SourceCodeCache::Initialize (Isolate * isolate, bool create_heap_objects)
Definition at line 98 of file bootstrapper.cc.
                                                                           {
  cache_ = create_heap_objects ? ReadOnlyRoots(isolate).empty_fixed_array()
                               : Tagged<FixedArray>();
}
References cache_, and v8::internal::Tagged< FixedArray >.
Referenced by v8::internal::Bootstrapper::Initialize(), and v8::internal::Bootstrapper::TearDown().
Iterate()
void v8::internal::SourceCodeCache::Iterate (RootVisitor * v)
Definition at line 103 of file bootstrapper.cc.
                                            {
  v->VisitRootPointer(Root::kExtensions, nullptr, FullObjectSlot(&cache_));
}
References cache_, and v8::internal::RootVisitor::VisitRootPointer().
Referenced by v8::internal::Bootstrapper::Iterate().
Lookup()
bool v8::internal::SourceCodeCache::Lookup (Isolate * isolate, base::Vector< const char > name, DirectHandle< SharedFunctionInfo > * handle)
Definition at line 107 of file bootstrapper.cc.
                                                                       {
  for (int i = 0; i < cache_->length(); i += 2) {
    Tagged<SeqOneByteString> str = Cast<SeqOneByteString>(cache_->get(i));
    if (str->IsOneByteEqualTo(name)) {
      *handle =
          direct_handle(Cast<SharedFunctionInfo>(cache_->get(i + 1)), isolate);
      return true;
    }
  }
  return false;
}
References cache_, v8::internal::direct_handle(), v8::internal::handle(), and v8::internal::name.
Referenced by v8::internal::Genesis::CompileExtension().
operator=()
SourceCodeCache& v8::internal::SourceCodeCache::operator= (const SourceCodeCache &) [delete]
Member Data Documentation
cache_
Tagged<FixedArray> v8::internal::SourceCodeCache::cache_ [private]
Definition at line 41 of file bootstrapper.h.
Referenced by Add(), Initialize(), Iterate(), and Lookup().
type_
Script::Type v8::internal::SourceCodeCache::type_ [private]
Definition at line 40 of file bootstrapper.h.
Referenced by Add().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/init/bootstrapper.h
/mnt/V8SourceCode/src/init/bootstrapper.cc