v8::internal::GCTracer Class Reference
#include <gc-tracer.h>
Classes
struct BackgroundCounter
class Event
struct IncrementalInfos
class RecordGCPhasesInfo
class Scope
Public Types
enum class MarkingType { kAtomic
, kIncremental
 }
Public Member Functions
GCTracer (Heap *heap, base::TimeTicks startup_time, GarbageCollectionReason initial_gc_reason=GarbageCollectionReason::kUnknown)
GCTracer (const GCTracer &)=delete
GCTracer & operator= (const GCTracer &)=delete
CollectionEpoch CurrentEpoch (Scope::ScopeId id) const
void StartObservablePause (base::TimeTicks time)
void StopObservablePause (GarbageCollector collector, base::TimeTicks time)
void UpdateCurrentEvent (GarbageCollectionReason gc_reason, const char *collector_reason)
void StartCycle (GarbageCollector collector, GarbageCollectionReason gc_reason, const char *collector_reason, MarkingType marking)
void StopYoungCycleIfFinished ()
void StopFullCycleIfFinished ()
void UpdateMemoryBalancerGCSpeed ()
void StartAtomicPause ()
void StopAtomicPause ()
void StartInSafepoint (base::TimeTicks time)
void StopInSafepoint (base::TimeTicks time)
void NotifyFullSweepingCompletedAndStopCycleIfFinished ()
void NotifyYoungSweepingCompletedAndStopCycleIfFinished ()
void NotifyYoungSweepingCompleted ()
void NotifyFullCppGCCompleted ()
void NotifyYoungCppGCRunning ()
void NotifyYoungCppGCCompleted ()
void SampleAllocation (base::TimeTicks current, size_t new_space_counter_bytes, size_t old_generation_counter_bytes, size_t embedder_counter_bytes)
void AddCompactionEvent (double duration, size_t live_bytes_compacted)
void AddSurvivalRatio (double survival_ratio)
void SampleConcurrencyEsimate (size_t concurrency)
void AddIncrementalMarkingStep (double duration, size_t bytes)
void AddIncrementalSweepingStep (double duration)
double IncrementalMarkingSpeedInBytesPerMillisecond () const
std::optional< double > EmbedderSpeedInBytesPerMillisecond () const
std::optional< double > YoungGenerationSpeedInBytesPerMillisecond (YoungGenerationSpeedMode mode) const
std::optional< double > CompactionSpeedInBytesPerMillisecond () const
std::optional< double > MarkCompactSpeedInBytesPerMillisecond () const
std::optional< double > FinalIncrementalMarkCompactSpeedInBytesPerMillisecond () const
std::optional< double > OldGenerationSpeedInBytesPerMillisecond ()
double NewSpaceAllocationThroughputInBytesPerMillisecond () const
double OldGenerationAllocationThroughputInBytesPerMillisecond () const
double EmbedderAllocationThroughputInBytesPerMillisecond () const
double AllocationThroughputInBytesPerMillisecond () const
double AverageSurvivalRatio () const
bool SurvivalEventsRecorded () const
void ResetSurvivalEvents ()
void NotifyIncrementalMarkingStart ()
void NotifyMarkingStart ()
uint16_t CodeFlushingIncrease () const
double AverageMarkCompactMutatorUtilization () const
double CurrentMarkCompactMutatorUtilization () const
void AddScopeSample (Scope::ScopeId id, base::TimeDelta duration)
void RecordGCPhasesHistograms (RecordGCPhasesInfo::Mode mode)
void RecordGCSizeCounters () const
void RecordEmbedderMarkingSpeed (size_t bytes, base::TimeDelta duration)
std::optional< base::TimeDelta > AverageTimeToIncrementalMarkingTask () const
void RecordTimeToIncrementalMarkingTask (base::TimeDelta time_to_task)
GarbageCollector GetCurrentCollector () const
void UpdateCurrentEventPriority (Priority priority)
Static Public Attributes
static constexpr base::TimeDelta kThroughputTimeFrame
static constexpr double kConservativeSpeedInBytesPerMillisecond = 128 * KB
Private Types
using Priority = v8::Isolate::Priority
using BytesAndDurationBuffer = ::heap::base::BytesAndDurationBuffer
using SmoothedBytesAndDuration = ::heap::base::SmoothedBytesAndDuration
Private Member Functions
void StopCycle (GarbageCollector collector)
double current_scope (Scope::ScopeId id) const
constexpr const IncrementalInfos & incremental_scope (Scope::ScopeId id) const
void ResetForTesting ()
void RecordIncrementalMarkingSpeed (size_t bytes, base::TimeDelta duration)
void RecordMutatorUtilization (base::TimeTicks mark_compactor_end_time, base::TimeDelta mark_compactor_duration)
void RecordGCSumCounters ()
void PrintNVP () const
void Print () const
void PRINTF_FORMAT (2, 3) Output(const char *format
void FetchBackgroundCounters ()
void ReportFullCycleToRecorder ()
void ReportIncrementalMarkingStepToRecorder (double v8_duration)
void ReportIncrementalSweepingStepToRecorder (double v8_duration)
void ReportYoungCycleToRecorder ()
FRIEND_TEST (GCTracerTest, AllocationThroughput)
FRIEND_TEST (GCTracerTest, BackgroundScavengerScope)
FRIEND_TEST (GCTracerTest, BackgroundMinorMSScope)
FRIEND_TEST (GCTracerTest, BackgroundMajorMCScope)
FRIEND_TEST (GCTracerTest, CyclePriorities)
FRIEND_TEST (GCTracerTest, EmbedderAllocationThroughput)
FRIEND_TEST (GCTracerTest, MultithreadedBackgroundScope)
FRIEND_TEST (GCTracerTest, NewSpaceAllocationThroughput)
FRIEND_TEST (GCTracerTest, PerGenerationAllocationThroughput)
FRIEND_TEST (GCTracerTest, PerGenerationAllocationThroughputWithProvidedTime)
FRIEND_TEST (GCTracerTest, RegularScope)
FRIEND_TEST (GCTracerTest, IncrementalMarkingDetails)
FRIEND_TEST (GCTracerTest, IncrementalScope)
FRIEND_TEST (GCTracerTest, IncrementalMarkingSpeed)
FRIEND_TEST (GCTracerTest, MutatorUtilization)
FRIEND_TEST (GCTracerTest, RecordMarkCompactHistograms)
FRIEND_TEST (GCTracerTest, RecordScavengerHistograms)
Private Attributes
void const
Heap * heap_
Event current_
Event previous_
std::optional< base::TimeTicks > start_of_observable_pause_
CollectionEpoch epoch_young_ = 0
CollectionEpoch epoch_full_ = 0
double recorded_major_incremental_marking_speed_ = 0.0
std::optional< base::TimeDelta > average_time_to_incremental_marking_task_
std::optional< base::TimeTicks > last_marking_start_time_for_code_flushing_
uint16_t code_flushing_increase_s_ = 0
IncrementalInfos incremental_scopes_ [Scope::NUMBER_OF_INCREMENTAL_SCOPES]
base::TimeTicks allocation_time_
size_t new_space_allocation_counter_bytes_ = 0
size_t old_generation_allocation_counter_bytes_ = 0
size_t embedder_allocation_counter_bytes_ = 0
std::optional< double > combined_mark_compact_speed_cache_
double average_mutator_duration_ = 0.0
double average_mark_compact_duration_ = 0.0
double current_mark_compact_mutator_utilization_ = 1.0
base::TimeTicks previous_mark_compact_end_time_
base::TimeDelta total_duration_since_last_mark_compact_
BytesAndDurationBuffer recorded_compactions_
BytesAndDurationBuffer recorded_incremental_mark_compacts_
BytesAndDurationBuffer recorded_mark_compacts_
BytesAndDurationBuffer recorded_major_totals_
BytesAndDurationBuffer recorded_embedder_marking_
SmoothedBytesAndDuration new_generation_allocations_
SmoothedBytesAndDuration old_generation_allocations_
SmoothedBytesAndDuration embedder_generation_allocations_
BytesAndDurationBuffer recorded_minor_gc_per_thread_
BytesAndDurationBuffer recorded_minor_gc_atomic_pause_
base::RingBuffer< double > recorded_survival_ratios_
bool notified_full_sweeping_completed_ = false
bool notified_full_cppgc_completed_ = false
bool full_cppgc_completed_during_minor_gc_ = false
bool notified_young_sweeping_completed_ = false
bool notified_young_cppgc_completed_ = false
bool notified_young_cppgc_running_ = false
bool young_gc_during_full_gc_sweeping_ = false
v8::metrics::GarbageCollectionFullMainThreadBatchedIncrementalMark incremental_mark_batched_events_
v8::metrics::GarbageCollectionFullMainThreadBatchedIncrementalSweep incremental_sweep_batched_events_
base::Mutex background_scopes_mutex_
base::TimeDelta background_scopes_ [Scope::NUMBER_OF_SCOPES]
Static Private Attributes
static constexpr base::TimeDelta kSmoothedAllocationSpeedDecayRate
Detailed Description
Definition at line 107 of file gc-tracer.h.
Member Typedef Documentation
BytesAndDurationBuffer
using v8::internal::GCTracer::BytesAndDurationBuffer = ::heap::base::BytesAndDurationBuffer [private]
Definition at line 463 of file gc-tracer.h.
Priority
using v8::internal::GCTracer::Priority = v8::Isolate::Priority [private]
Definition at line 108 of file gc-tracer.h.
SmoothedBytesAndDuration
using v8::internal::GCTracer::SmoothedBytesAndDuration = ::heap::base::SmoothedBytesAndDuration [private]
Definition at line 464 of file gc-tracer.h.
Member Enumeration Documentation
MarkingType
enum v8::internal::GCTracer::MarkingType [strong]
Enumerator
kAtomic
kIncremental
Definition at line 301 of file gc-tracer.h.
{ kAtomic, kIncremental };
Constructor & Destructor Documentation
GCTracer() [1/2]
v8::internal::GCTracer::GCTracer (Heap * heap, base::TimeTicks startup_time, GarbageCollectionReason initial_gc_reason = GarbageCollectionReason::kUnknown)
Definition at line 174 of file gc-tracer.cc.
    : heap_(heap),
      current_(Event::Type::START, Event::State::NOT_RUNNING, initial_gc_reason,
               nullptr, heap_->isolate()->priority()),
      previous_(current_),
      allocation_time_(startup_time),
      previous_mark_compact_end_time_(startup_time)
#if defined(V8_USE_PERFETTO)
      ,
      parent_track_(perfetto::ThreadTrack::Current())
#endif
{
  // All accesses to incremental_marking_scope assume that incremental marking
  // scopes come first.
  static_assert(0 == Scope::FIRST_INCREMENTAL_SCOPE);
  // We assume that MC_INCREMENTAL is the first scope so that we can properly
  // map it to RuntimeCallStats.
  static_assert(0 == Scope::MC_INCREMENTAL);
  // Starting a new cycle will make the current event the previous event.
  // Setting the current end time here allows us to refer back to a previous
  // event's end time to compute time spent in mutator.
  current_.end_time = previous_mark_compact_end_time_;
}
References current_, v8::internal::GCTracer::Event::end_time, v8::internal::GCTracer::Scope::FIRST_INCREMENTAL_SCOPE, and previous_mark_compact_end_time_.
Referenced by ResetForTesting().
GCTracer() [2/2]
v8::internal::GCTracer::GCTracer (const GCTracer &) [delete]
Member Function Documentation
AddCompactionEvent()
void v8::internal::GCTracer::AddCompactionEvent (double duration, size_t live_bytes_compacted)
Definition at line 731 of file gc-tracer.cc.
                                                               {
  recorded_compactions_.Push(BytesAndDuration(
      live_bytes_compacted, base::TimeDelta::FromMillisecondsD(duration)));
}
References v8::internal::duration, v8::base::TimeDelta::FromMillisecondsD(), v8::base::RingBuffer< T, _SIZE >::Push(), and recorded_compactions_.
AddIncrementalMarkingStep()
void v8::internal::GCTracer::AddIncrementalMarkingStep (double duration, size_t bytes)
Definition at line 741 of file gc-tracer.cc.
                                                                      {
  if (bytes > 0) {
    current_.incremental_marking_bytes += bytes;
    current_.incremental_marking_duration +=
        base::TimeDelta::FromMillisecondsD(duration);
  }
  ReportIncrementalMarkingStepToRecorder(duration);
}
References current_, v8::internal::duration, v8::base::TimeDelta::FromMillisecondsD(), v8::internal::GCTracer::Event::incremental_marking_bytes, v8::internal::GCTracer::Event::incremental_marking_duration, and ReportIncrementalMarkingStepToRecorder().
Referenced by v8::internal::IncrementalMarking::Step().
AddIncrementalSweepingStep()
void v8::internal::GCTracer::AddIncrementalSweepingStep (double duration)
Definition at line 750 of file gc-tracer.cc.
                                                         {
  ReportIncrementalSweepingStepToRecorder(duration);
}
References v8::internal::duration, and ReportIncrementalSweepingStepToRecorder().
AddScopeSample()
void v8::internal::GCTracer::AddScopeSample (Scope::ScopeId id, base::TimeDelta duration) [inline]
Definition at line 122 of file gc-tracer-inl.h.
                                                                     {
  if (Scope::FIRST_INCREMENTAL_SCOPE <= id &&
      id <= Scope::LAST_INCREMENTAL_SCOPE) {
    incremental_scopes_[Scope::IncrementalOffset(id)] += duration;
  } else if (Scope::FIRST_BACKGROUND_SCOPE <= id &&
             id <= Scope::LAST_BACKGROUND_SCOPE) {
    base::MutexGuard guard(&background_scopes_mutex_);
    background_scopes_[id] += duration;
  } else {
    DCHECK_GT(Scope::NUMBER_OF_SCOPES, id);
    current_.scopes[id] += duration;
  }
}
References background_scopes_, background_scopes_mutex_, current_, DCHECK_GT, v8::internal::duration, v8::internal::GCTracer::Scope::FIRST_BACKGROUND_SCOPE, v8::internal::GCTracer::Scope::FIRST_INCREMENTAL_SCOPE, incremental_scopes_, v8::internal::GCTracer::Scope::IncrementalOffset(), v8::internal::GCTracer::Scope::LAST_BACKGROUND_SCOPE, v8::internal::GCTracer::Scope::LAST_INCREMENTAL_SCOPE, and v8::internal::GCTracer::Event::scopes.
AddSurvivalRatio()
void v8::internal::GCTracer::AddSurvivalRatio (double survival_ratio)
Definition at line 737 of file gc-tracer.cc.
                                                      {
  recorded_survival_ratios_.Push(promotion_ratio);
}
References v8::base::RingBuffer< T, _SIZE >::Push(), and recorded_survival_ratios_.
Referenced by v8::internal::Heap::UpdateSurvivalStatistics().
AllocationThroughputInBytesPerMillisecond()
double v8::internal::GCTracer::AllocationThroughputInBytesPerMillisecond () const
Definition at line 1409 of file gc-tracer.cc.
                                                                 {
  return NewSpaceAllocationThroughputInBytesPerMillisecond() +
         OldGenerationAllocationThroughputInBytesPerMillisecond();
}
References NewSpaceAllocationThroughputInBytesPerMillisecond(), and OldGenerationAllocationThroughputInBytesPerMillisecond().
Referenced by PrintNVP().
AverageMarkCompactMutatorUtilization()
double v8::internal::GCTracer::AverageMarkCompactMutatorUtilization () const
Definition at line 1316 of file gc-tracer.cc.
                                                            {
  double average_total_duration =
      average_mark_compact_duration_ + average_mutator_duration_;
  if (average_total_duration == 0) return 1.0;
  return average_mutator_duration_ / average_total_duration;
}
References average_mark_compact_duration_, and average_mutator_duration_.
Referenced by Print().
AverageSurvivalRatio()
double v8::internal::GCTracer::AverageSurvivalRatio () const
Definition at line 1414 of file gc-tracer.cc.
                                            {
  if (recorded_survival_ratios_.Empty()) return 0.0;
  double sum = recorded_survival_ratios_.Reduce(
      [](double a, double b) { return a + b; }, 0.0);
  return sum / recorded_survival_ratios_.Size();
}
References v8::base::RingBuffer< T, _SIZE >::Empty(), recorded_survival_ratios_, v8::base::RingBuffer< T, _SIZE >::Reduce(), and v8::base::RingBuffer< T, _SIZE >::Size().
Referenced by PrintNVP().
AverageTimeToIncrementalMarkingTask()
std::optional< base::TimeDelta > v8::internal::GCTracer::AverageTimeToIncrementalMarkingTask () const
Definition at line 1279 of file gc-tracer.cc.
          {
  return average_time_to_incremental_marking_task_;
}
References average_time_to_incremental_marking_task_.
Referenced by v8::internal::IncrementalMarkingJob::AverageTimeToTask().
CodeFlushingIncrease()
uint16_t v8::internal::GCTracer::CodeFlushingIncrease () const
Definition at line 727 of file gc-tracer.cc.
                                              {
  return code_flushing_increase_s_;
}
References code_flushing_increase_s_.
Referenced by v8::internal::ConcurrentMarking::RunMajor(), and v8::internal::MarkCompactCollector::StartMarking().
CompactionSpeedInBytesPerMillisecond()
std::optional< double > v8::internal::GCTracer::CompactionSpeedInBytesPerMillisecond () const
Definition at line 1353 of file gc-tracer.cc.
                                                                         {
  return BoundedAverageSpeed(recorded_compactions_);
}
References v8::internal::anonymous_namespace{gc-tracer.cc}::BoundedAverageSpeed(), and recorded_compactions_.
Referenced by v8::internal::MarkCompactCollector::ComputeEvacuationHeuristics(), PrintNVP(), and v8::internal::anonymous_namespace{mark-compact.cc}::TraceEvacuation().
current_scope()
double v8::internal::GCTracer::current_scope (Scope::ScopeId id) const [inline], [private]
Definition at line 112 of file gc-tracer-inl.h.
                                                    {
  DCHECK_GT(Scope::NUMBER_OF_SCOPES, id);
  return current_.scopes[id].InMillisecondsF();
}
References current_, DCHECK_GT, v8::base::TimeDelta::InMillisecondsF(), and v8::internal::GCTracer::Event::scopes.
Referenced by Print(), and PrintNVP().
CurrentEpoch()
CollectionEpoch v8::internal::GCTracer::CurrentEpoch (Scope::ScopeId id) const [inline]
Definition at line 108 of file gc-tracer-inl.h.
                                                            {
  return Scope::NeedsYoungEpoch(id) ? epoch_young_ : epoch_full_;
}
References epoch_full_, epoch_young_, and v8::internal::GCTracer::Scope::NeedsYoungEpoch().
Referenced by v8::internal::ArrayBufferSweeper::GetTraceIdForFlowEvent(), v8::internal::IncrementalMarking::Start(), and v8::internal::IncrementalMarking::Step().
CurrentMarkCompactMutatorUtilization()
double v8::internal::GCTracer::CurrentMarkCompactMutatorUtilization () const
Definition at line 1323 of file gc-tracer.cc.
                                                            {
  return current_mark_compact_mutator_utilization_;
}
References current_mark_compact_mutator_utilization_.
Referenced by Print().
EmbedderAllocationThroughputInBytesPerMillisecond()
double v8::internal::GCTracer::EmbedderAllocationThroughputInBytesPerMillisecond () const
Definition at line 1405 of file gc-tracer.cc.
                                                                         {
  return BoundedThroughput(embedder_generation_allocations_);
}
References v8::internal::anonymous_namespace{gc-tracer.cc}::BoundedThroughput(), and embedder_generation_allocations_.
Referenced by SampleAllocation().
EmbedderSpeedInBytesPerMillisecond()
std::optional< double > v8::internal::GCTracer::EmbedderSpeedInBytesPerMillisecond () const
Definition at line 1338 of file gc-tracer.cc.
                                                                       {
  return BoundedAverageSpeed(recorded_embedder_marking_);
}
References v8::internal::anonymous_namespace{gc-tracer.cc}::BoundedAverageSpeed(), and recorded_embedder_marking_.
Referenced by RecordGCSumCounters().
FetchBackgroundCounters()
void v8::internal::GCTracer::FetchBackgroundCounters () [private]
Definition at line 1431 of file gc-tracer.cc.
                                       {
  base::MutexGuard guard(&background_scopes_mutex_);
  for (int i = Scope::FIRST_BACKGROUND_SCOPE; i <= Scope::LAST_BACKGROUND_SCOPE;
       i++) {
    current_.scopes[i] += background_scopes_[i];
    background_scopes_[i] = base::TimeDelta();
  }
}
References background_scopes_, background_scopes_mutex_, current_, v8::internal::GCTracer::Scope::FIRST_BACKGROUND_SCOPE, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::GCTracer::Scope::LAST_BACKGROUND_SCOPE, and v8::internal::GCTracer::Event::scopes.
Referenced by StartCycle(), StopCycle(), and StopObservablePause().
FinalIncrementalMarkCompactSpeedInBytesPerMillisecond()
std::optional< double > v8::internal::GCTracer::FinalIncrementalMarkCompactSpeedInBytesPerMillisecond () const
Definition at line 1362 of file gc-tracer.cc.
                                                                      {
  return BoundedAverageSpeed(recorded_incremental_mark_compacts_);
}
References v8::internal::anonymous_namespace{gc-tracer.cc}::BoundedAverageSpeed(), and recorded_incremental_mark_compacts_.
Referenced by OldGenerationSpeedInBytesPerMillisecond().
FRIEND_TEST() [1/17]
v8::internal::GCTracer::FRIEND_TEST (GCTracerTest , AllocationThroughput) [private]
FRIEND_TEST() [2/17]
v8::internal::GCTracer::FRIEND_TEST (GCTracerTest , BackgroundMajorMCScope) [private]
FRIEND_TEST() [3/17]
v8::internal::GCTracer::FRIEND_TEST (GCTracerTest , BackgroundMinorMSScope) [private]
FRIEND_TEST() [4/17]
v8::internal::GCTracer::FRIEND_TEST (GCTracerTest , BackgroundScavengerScope) [private]
FRIEND_TEST() [5/17]
v8::internal::GCTracer::FRIEND_TEST (GCTracerTest , CyclePriorities) [private]
FRIEND_TEST() [6/17]
v8::internal::GCTracer::FRIEND_TEST (GCTracerTest , EmbedderAllocationThroughput) [private]
FRIEND_TEST() [7/17]
v8::internal::GCTracer::FRIEND_TEST (GCTracerTest , IncrementalMarkingDetails) [private]
FRIEND_TEST() [8/17]
v8::internal::GCTracer::FRIEND_TEST (GCTracerTest , IncrementalMarkingSpeed) [private]
FRIEND_TEST() [9/17]
v8::internal::GCTracer::FRIEND_TEST (GCTracerTest , IncrementalScope) [private]
FRIEND_TEST() [10/17]
v8::internal::GCTracer::FRIEND_TEST (GCTracerTest , MultithreadedBackgroundScope) [private]
FRIEND_TEST() [11/17]
v8::internal::GCTracer::FRIEND_TEST (GCTracerTest , MutatorUtilization) [private]
FRIEND_TEST() [12/17]
v8::internal::GCTracer::FRIEND_TEST (GCTracerTest , NewSpaceAllocationThroughput) [private]
FRIEND_TEST() [13/17]
v8::internal::GCTracer::FRIEND_TEST (GCTracerTest , PerGenerationAllocationThroughput) [private]
FRIEND_TEST() [14/17]
v8::internal::GCTracer::FRIEND_TEST (GCTracerTest , PerGenerationAllocationThroughputWithProvidedTime) [private]
FRIEND_TEST() [15/17]
v8::internal::GCTracer::FRIEND_TEST (GCTracerTest , RecordMarkCompactHistograms) [private]
FRIEND_TEST() [16/17]
v8::internal::GCTracer::FRIEND_TEST (GCTracerTest , RecordScavengerHistograms) [private]
FRIEND_TEST() [17/17]
v8::internal::GCTracer::FRIEND_TEST (GCTracerTest , RegularScope) [private]
GetCurrentCollector()
GarbageCollector v8::internal::GCTracer::GetCurrentCollector () const
Definition at line 1940 of file gc-tracer.cc.
                                                     {
  switch (current_.type) {
    case Event::Type::SCAVENGER:
      return GarbageCollector::SCAVENGER;
    case Event::Type::MARK_COMPACTOR:
    case Event::Type::INCREMENTAL_MARK_COMPACTOR:
      return GarbageCollector::MARK_COMPACTOR;
    case Event::Type::MINOR_MARK_SWEEPER:
    case Event::Type::INCREMENTAL_MINOR_MARK_SWEEPER:
      return GarbageCollector::MINOR_MARK_SWEEPER;
    case Event::Type::START:
      UNREACHABLE();
  }
}
References current_, v8::internal::GCTracer::Event::INCREMENTAL_MARK_COMPACTOR, v8::internal::GCTracer::Event::INCREMENTAL_MINOR_MARK_SWEEPER, v8::internal::MARK_COMPACTOR, v8::internal::GCTracer::Event::MARK_COMPACTOR, v8::internal::MINOR_MARK_SWEEPER, v8::internal::GCTracer::Event::MINOR_MARK_SWEEPER, v8::internal::SCAVENGER, v8::internal::GCTracer::Event::SCAVENGER, v8::internal::GCTracer::Event::START, v8::internal::GCTracer::Event::type, and v8::internal::UNREACHABLE().
Referenced by v8::internal::anonymous_namespace{heap.cc}::CompleteArrayBufferSweeping(), v8::internal::Sweeper::StartMajorSweeperTasks(), v8::internal::Sweeper::StartMajorSweeping(), v8::internal::Sweeper::StartMinorSweeperTasks(), and v8::internal::Sweeper::StartMinorSweeping().
incremental_scope()
constexpr const GCTracer::IncrementalInfos & v8::internal::GCTracer::incremental_scope (Scope::ScopeId id) const [inline], [constexpr], [private]
Definition at line 117 of file gc-tracer-inl.h.
                           {
  return incremental_scopes_[Scope::IncrementalOffset(id)];
}
References incremental_scopes_, and v8::internal::GCTracer::Scope::IncrementalOffset().
Referenced by Print(), and PrintNVP().
IncrementalMarkingSpeedInBytesPerMillisecond()
double v8::internal::GCTracer::IncrementalMarkingSpeedInBytesPerMillisecond () const
Definition at line 1327 of file gc-tracer.cc.
                                                                    {
  if (recorded_major_incremental_marking_speed_ != 0) {
    return recorded_major_incremental_marking_speed_;
  }
  if (!current_.incremental_marking_duration.IsZero()) {
    return current_.incremental_marking_bytes /
           current_.incremental_marking_duration.InMillisecondsF();
  }
  return kConservativeSpeedInBytesPerMillisecond;
}
References current_, v8::internal::GCTracer::Event::incremental_marking_bytes, v8::internal::GCTracer::Event::incremental_marking_duration, v8::base::TimeDelta::InMillisecondsF(), v8::base::TimeDelta::IsZero(), kConservativeSpeedInBytesPerMillisecond, and recorded_major_incremental_marking_speed_.
Referenced by OldGenerationSpeedInBytesPerMillisecond(), and PrintNVP().
MarkCompactSpeedInBytesPerMillisecond()
std::optional< double > v8::internal::GCTracer::MarkCompactSpeedInBytesPerMillisecond () const
Definition at line 1357 of file gc-tracer.cc.
                                                                          {
  return BoundedAverageSpeed(recorded_mark_compacts_);
}
References v8::internal::anonymous_namespace{gc-tracer.cc}::BoundedAverageSpeed(), and recorded_mark_compacts_.
Referenced by OldGenerationSpeedInBytesPerMillisecond().
NewSpaceAllocationThroughputInBytesPerMillisecond()
double v8::internal::GCTracer::NewSpaceAllocationThroughputInBytesPerMillisecond () const
Definition at line 1396 of file gc-tracer.cc.
                                                                         {
  return BoundedThroughput(new_generation_allocations_);
}
References v8::internal::anonymous_namespace{gc-tracer.cc}::BoundedThroughput(), and new_generation_allocations_.
Referenced by AllocationThroughputInBytesPerMillisecond(), PrintNVP(), and SampleAllocation().
NotifyFullCppGCCompleted()
void v8::internal::GCTracer::NotifyFullCppGCCompleted ()
Definition at line 599 of file gc-tracer.cc.
                                        {
  // Stop a full GC cycle only when both v8 and cppgc (if available) GCs have
  // finished sweeping. This method is invoked by cppgc.
  DCHECK(heap_->cpp_heap());
  const auto* metric_recorder =
      CppHeap::From(heap_->cpp_heap())->GetMetricRecorder();
  USE(metric_recorder);
  DCHECK(metric_recorder->FullGCMetricsReportPending());
  DCHECK(!notified_full_cppgc_completed_);
  notified_full_cppgc_completed_ = true;
  // Cppgc sweeping may finalize during MinorMS sweeping. In that case, delay
  // stopping the cycle until the nested MinorMS cycle is stopped.
  if (Event::IsYoungGenerationEvent(current_.type)) {
    DCHECK(young_gc_during_full_gc_sweeping_);
    full_cppgc_completed_during_minor_gc_ = true;
    return;
  }
  StopFullCycleIfFinished();
}
References v8::internal::Heap::cpp_heap(), current_, v8::internal::DCHECK(), v8::internal::CppHeap::From(), full_cppgc_completed_during_minor_gc_, v8::internal::CppHeap::GetMetricRecorder(), heap_, v8::internal::GCTracer::Event::IsYoungGenerationEvent(), notified_full_cppgc_completed_, StopFullCycleIfFinished(), v8::internal::GCTracer::Event::type, USE, and young_gc_during_full_gc_sweeping_.
NotifyFullSweepingCompletedAndStopCycleIfFinished()
void v8::internal::GCTracer::NotifyFullSweepingCompletedAndStopCycleIfFinished ()
Definition at line 539 of file gc-tracer.cc.
                                                                 {
  // Notifying twice that V8 sweeping is finished for the same cycle is possible
  // only if Oilpan sweeping is still in progress.
  DCHECK_IMPLIES(
      notified_full_sweeping_completed_,
      !notified_full_cppgc_completed_ || full_cppgc_completed_during_minor_gc_);
  if (Event::IsYoungGenerationEvent(current_.type)) {
    bool was_young_gc_during_full_gc_sweeping =
        young_gc_during_full_gc_sweeping_;
    bool was_full_sweeping_notified = notified_full_sweeping_completed_;
    NotifyYoungSweepingCompletedAndStopCycleIfFinished();
    // NotifyYoungSweepingCompletedAndStopCycleIfFinished checks if the full
    // cycle needs to be stopped as well. If full sweeping was already notified,
    // nothing more needs to be done here.
    if (!was_young_gc_during_full_gc_sweeping || was_full_sweeping_notified)
      return;
  }
  DCHECK(!Event::IsYoungGenerationEvent(current_.type));
  // Sweeping finalization can also be triggered from inside a full GC cycle's
  // atomic pause.
  DCHECK(current_.state == Event::State::SWEEPING ||
         current_.state == Event::State::ATOMIC);
  // Stop a full GC cycle only when both v8 and cppgc (if available) GCs have
  // finished sweeping. This method is invoked by v8.
  if (v8_flags.trace_gc_freelists) {
    PrintIsolate(heap_->isolate(),
                 "FreeLists statistics after sweeping completed:\n");
    heap_->PrintFreeListsStats();
  }
  notified_full_sweeping_completed_ = true;
  StopFullCycleIfFinished();
}
References v8::internal::GCTracer::Event::ATOMIC, current_, v8::internal::DCHECK(), DCHECK_IMPLIES, full_cppgc_completed_during_minor_gc_, heap_, v8::internal::Heap::isolate(), v8::internal::GCTracer::Event::IsYoungGenerationEvent(), notified_full_cppgc_completed_, notified_full_sweeping_completed_, NotifyYoungSweepingCompletedAndStopCycleIfFinished(), v8::internal::Heap::PrintFreeListsStats(), v8::internal::PrintIsolate(), v8::internal::GCTracer::Event::state, StopFullCycleIfFinished(), v8::internal::GCTracer::Event::SWEEPING, v8::internal::GCTracer::Event::type, v8::internal::v8_flags, and young_gc_during_full_gc_sweeping_.
Referenced by v8::internal::Heap::EnsureSweepingCompleted().
NotifyIncrementalMarkingStart()
void v8::internal::GCTracer::NotifyIncrementalMarkingStart ()
Definition at line 1427 of file gc-tracer.cc.
                                             {
  current_.incremental_marking_start_time = base::TimeTicks::Now();
}
References current_, v8::internal::GCTracer::Event::incremental_marking_start_time, and v8::base::TimeTicks::Now().
Referenced by v8::internal::IncrementalMarking::Start().
NotifyMarkingStart()
void v8::internal::GCTracer::NotifyMarkingStart ()
Definition at line 691 of file gc-tracer.cc.
                                  {
  const auto marking_start = base::TimeTicks::Now();
  // Handle code flushing time deltas. Times are incremented conservatively:
  // 1. The first delta is 0s.
  // 2. Any delta is rounded downwards to a full second.
  // 3. 0s-deltas are carried over to the next GC with their precise diff. This
  // allows for frequent GCs (within a single second) to be attributed
  // correctly later on.
  // 4. The first non-zero increment after a reset always just increments by 1s.
  using SFIAgeType = decltype(code_flushing_increase_s_);
  static_assert(SharedFunctionInfo::kAgeSize == sizeof(SFIAgeType));
  static constexpr auto kMaxDeltaForSFIAge =
      base::TimeDelta::FromSeconds(std::numeric_limits<SFIAgeType>::max());
  SFIAgeType code_flushing_increase_s = 0;
  if (last_marking_start_time_for_code_flushing_.has_value()) {
    const auto diff =
        marking_start - last_marking_start_time_for_code_flushing_.value();
    if (diff > kMaxDeltaForSFIAge) {
      code_flushing_increase_s = std::numeric_limits<SFIAgeType>::max();
    } else {
      code_flushing_increase_s = static_cast<SFIAgeType>(diff.InSeconds());
    }
  }
  DCHECK_LE(code_flushing_increase_s, std::numeric_limits<SFIAgeType>::max());
  code_flushing_increase_s_ = code_flushing_increase_s;
  if (!last_marking_start_time_for_code_flushing_.has_value() ||
      code_flushing_increase_s > 0) {
    last_marking_start_time_for_code_flushing_ = marking_start;
  }
  if (V8_UNLIKELY(v8_flags.trace_flush_code)) {
    PrintIsolate(heap_->isolate(), "code flushing: increasing time: %u s\n",
                 code_flushing_increase_s_);
  }
}
References code_flushing_increase_s_, DCHECK_LE, v8::base::TimeDelta::FromSeconds(), heap_, v8::internal::Heap::isolate(), v8::internal::SharedFunctionInfo::kAgeSize, last_marking_start_time_for_code_flushing_, v8::base::TimeTicks::Now(), v8::internal::PrintIsolate(), v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::internal::MarkCompactCollector::StartMarking().
NotifyYoungCppGCCompleted()
void v8::internal::GCTracer::NotifyYoungCppGCCompleted ()
Definition at line 619 of file gc-tracer.cc.
                                         {
  // Stop a young GC cycle only when both v8 and cppgc (if available) GCs have
  // finished sweeping. This method is invoked by cppgc.
  DCHECK(heap_->cpp_heap());
  DCHECK(notified_young_cppgc_running_);
  const auto* metric_recorder =
      CppHeap::From(heap_->cpp_heap())->GetMetricRecorder();
  USE(metric_recorder);
  DCHECK(metric_recorder->YoungGCMetricsReportPending());
  DCHECK(!notified_young_cppgc_completed_);
  notified_young_cppgc_completed_ = true;
  StopYoungCycleIfFinished();
}
References v8::internal::Heap::cpp_heap(), v8::internal::DCHECK(), v8::internal::CppHeap::From(), v8::internal::CppHeap::GetMetricRecorder(), heap_, notified_young_cppgc_completed_, notified_young_cppgc_running_, StopYoungCycleIfFinished(), and USE.
NotifyYoungCppGCRunning()
void v8::internal::GCTracer::NotifyYoungCppGCRunning ()
Definition at line 633 of file gc-tracer.cc.
                                       {
  DCHECK(!notified_young_cppgc_running_);
  notified_young_cppgc_running_ = true;
}
References v8::internal::DCHECK(), and notified_young_cppgc_running_.
Referenced by v8::internal::CppHeap::InitializeMarking().
NotifyYoungSweepingCompleted()
void v8::internal::GCTracer::NotifyYoungSweepingCompleted ()
Definition at line 575 of file gc-tracer.cc.
                                            {
  DCHECK(Event::IsYoungGenerationEvent(current_.type));
  if (v8_flags.verify_heap || v8_flags.code_stats) {
    // If heap verification or code stats are enabled, sweeping finalization can
    // also be triggered from inside a full GC cycle's atomic pause.
    DCHECK(current_.type == Event::Type::MINOR_MARK_SWEEPER ||
           current_.type == Event::Type::INCREMENTAL_MINOR_MARK_SWEEPER ||
           current_.type == Event::Type::SCAVENGER);
    DCHECK(current_.state == Event::State::SWEEPING ||
           current_.state == Event::State::ATOMIC);
  } else {
    DCHECK(IsSweepingInProgress() || (current_.type == Event::Type::SCAVENGER));
  }
  DCHECK(!notified_young_sweeping_completed_);
  notified_young_sweeping_completed_ = true;
}
References v8::internal::GCTracer::Event::ATOMIC, current_, v8::internal::DCHECK(), v8::internal::GCTracer::Event::INCREMENTAL_MINOR_MARK_SWEEPER, v8::internal::GCTracer::Event::IsYoungGenerationEvent(), v8::internal::GCTracer::Event::MINOR_MARK_SWEEPER, notified_young_sweeping_completed_, v8::internal::GCTracer::Event::SCAVENGER, v8::internal::GCTracer::Event::state, v8::internal::GCTracer::Event::SWEEPING, v8::internal::GCTracer::Event::type, and v8::internal::v8_flags.
Referenced by NotifyYoungSweepingCompletedAndStopCycleIfFinished().
NotifyYoungSweepingCompletedAndStopCycleIfFinished()
void v8::internal::GCTracer::NotifyYoungSweepingCompletedAndStopCycleIfFinished ()
Definition at line 593 of file gc-tracer.cc.
                                                                  {
  if (!Event::IsYoungGenerationEvent(current_.type)) return;
  NotifyYoungSweepingCompleted();
  StopYoungCycleIfFinished();
}
References current_, v8::internal::GCTracer::Event::IsYoungGenerationEvent(), NotifyYoungSweepingCompleted(), StopYoungCycleIfFinished(), and v8::internal::GCTracer::Event::type.
Referenced by v8::internal::ScavengerCollector::CompleteSweepingQuarantinedPagesIfNeeded(), v8::internal::Heap::EnsureYoungSweepingCompleted(), and NotifyFullSweepingCompletedAndStopCycleIfFinished().
OldGenerationAllocationThroughputInBytesPerMillisecond()
double v8::internal::GCTracer::OldGenerationAllocationThroughputInBytesPerMillisecond () const
Definition at line 1400 of file gc-tracer.cc.
          {
  return BoundedThroughput(old_generation_allocations_);
}
References v8::internal::anonymous_namespace{gc-tracer.cc}::BoundedThroughput(), and old_generation_allocations_.
Referenced by AllocationThroughputInBytesPerMillisecond(), and SampleAllocation().
OldGenerationSpeedInBytesPerMillisecond()
std::optional< double > v8::internal::GCTracer::OldGenerationSpeedInBytesPerMillisecond ()
Definition at line 1366 of file gc-tracer.cc.
                                                                      {
  if (v8_flags.gc_speed_uses_counters) {
    return BoundedAverageSpeed(recorded_major_totals_);
  }
  const double kMinimumMarkingSpeed = 0.5;
  if (combined_mark_compact_speed_cache_.has_value())
    return combined_mark_compact_speed_cache_;
  // MarkCompact speed is more stable than incremental marking speed, because
  // there might not be many incremental marking steps because of concurrent
  // marking.
  combined_mark_compact_speed_cache_ = MarkCompactSpeedInBytesPerMillisecond();
  if (combined_mark_compact_speed_cache_.has_value())
    return combined_mark_compact_speed_cache_;
  double speed1 = IncrementalMarkingSpeedInBytesPerMillisecond();
  double speed2 =
      FinalIncrementalMarkCompactSpeedInBytesPerMillisecond().value_or(0.0);
  if (speed1 < kMinimumMarkingSpeed || speed2 < kMinimumMarkingSpeed) {
    // No data for the incremental marking speed.
    // Return the non-incremental mark-compact speed.
    combined_mark_compact_speed_cache_ =
        MarkCompactSpeedInBytesPerMillisecond();
  } else {
    // Combine the speed of incremental step and the speed of the final step.
    // 1 / (1 / speed1 + 1 / speed2) = speed1 * speed2 / (speed1 + speed2).
    combined_mark_compact_speed_cache_ = speed1 * speed2 / (speed1 + speed2);
  }
  return combined_mark_compact_speed_cache_;
}
References v8::internal::anonymous_namespace{gc-tracer.cc}::BoundedAverageSpeed(), combined_mark_compact_speed_cache_, FinalIncrementalMarkCompactSpeedInBytesPerMillisecond(), IncrementalMarkingSpeedInBytesPerMillisecond(), MarkCompactSpeedInBytesPerMillisecond(), recorded_major_totals_, and v8::internal::v8_flags.
Referenced by RecordGCSumCounters().
operator=()
GCTracer& v8::internal::GCTracer::operator= (const GCTracer &) [delete]
Print()
void v8::internal::GCTracer::Print () const [private]
Definition at line 773 of file gc-tracer.cc.
                           {
  const base::TimeDelta duration = current_.end_time - current_.start_time;
  const size_t kIncrementalStatsSize = 128;
  char incremental_buffer[kIncrementalStatsSize] = {0};
  if (current_.type == Event::Type::INCREMENTAL_MARK_COMPACTOR) {
    base::OS::SNPrintF(
        incremental_buffer, kIncrementalStatsSize,
        " (+ %.1f ms in %d steps since start of marking, "
        "biggest step %.1f ms, walltime since start of marking %.f ms)",
        current_scope(Scope::MC_INCREMENTAL),
        incremental_scope(Scope::MC_INCREMENTAL).steps,
        incremental_scope(Scope::MC_INCREMENTAL).longest_step.InMillisecondsF(),
        (current_.end_time - current_.incremental_marking_start_time)
            .InMillisecondsF());
  }
  const double total_external_time =
      current_scope(Scope::HEAP_EXTERNAL_WEAK_GLOBAL_HANDLES) +
      current_scope(Scope::HEAP_EXTERNAL_EPILOGUE) +
      current_scope(Scope::HEAP_EXTERNAL_PROLOGUE) +
      current_scope(Scope::MC_INCREMENTAL_EXTERNAL_EPILOGUE) +
      current_scope(Scope::MC_INCREMENTAL_EXTERNAL_PROLOGUE);
  // Avoid PrintF as Output also appends the string to the tracing ring buffer
  // that gets printed on OOM failures.
  DCHECK_IMPLIES(young_gc_during_full_gc_sweeping_,
                 Event::IsYoungGenerationEvent(current_.type));
  Output(
      "[%d:%p] "
      "%8.0f ms: "
      "%s%s%s %.1f (%.1f) -> %.1f (%.1f) MB, "
      "pooled: %.1f MB, "
      "%.2f / %.2f ms%s (average mu = %.3f, current mu = %.3f) %s; %s\n",
      base::OS::GetCurrentProcessId(),
      reinterpret_cast<void*>(heap_->isolate()),
      heap_->isolate()->time_millis_since_init(),
      ToString(current_.type, false), current_.reduce_memory ? " (reduce)" : "",
      young_gc_during_full_gc_sweeping_ ? " (during sweeping)" : "",
      static_cast<double>(current_.start_object_size) / MB,
      static_cast<double>(current_.start_memory_size) / MB,
      static_cast<double>(current_.end_object_size) / MB,
      static_cast<double>(current_.end_memory_size) / MB,
      static_cast<double>(heap_->memory_allocator()->GetPooledChunksCount() *
                          PageMetadata::kPageSize) /
          MB,
      duration.InMillisecondsF(), total_external_time, incremental_buffer,
      AverageMarkCompactMutatorUtilization(),
      CurrentMarkCompactMutatorUtilization(), ToString(current_.gc_reason),
      current_.collector_reason != nullptr ? current_.collector_reason : "");
}
References AverageMarkCompactMutatorUtilization(), v8::internal::GCTracer::Event::collector_reason, current_, current_scope(), CurrentMarkCompactMutatorUtilization(), DCHECK_IMPLIES, v8::internal::duration, v8::internal::GCTracer::Event::end_memory_size, v8::internal::GCTracer::Event::end_object_size, v8::internal::GCTracer::Event::end_time, v8::internal::GCTracer::Event::gc_reason, v8::base::OS::GetCurrentProcessId(), v8::internal::MemoryAllocator::GetPooledChunksCount(), heap_, v8::internal::GCTracer::Event::INCREMENTAL_MARK_COMPACTOR, v8::internal::GCTracer::Event::incremental_marking_start_time, incremental_scope(), v8::internal::Heap::isolate(), v8::internal::GCTracer::Event::IsYoungGenerationEvent(), v8::internal::MutablePageMetadata::kPageSize, v8::internal::MB, v8::internal::Heap::memory_allocator(), v8::internal::anonymous_namespace{js-duration-format.cc}::Output(), v8::internal::GCTracer::Event::reduce_memory, v8::base::SNPrintF(), v8::internal::GCTracer::Event::start_memory_size, v8::internal::GCTracer::Event::start_object_size, v8::internal::GCTracer::Event::start_time, v8::internal::Isolate::time_millis_since_init(), v8::internal::ToString(), v8::internal::GCTracer::Event::type, and young_gc_during_full_gc_sweeping_.
Referenced by StopObservablePause().
PRINTF_FORMAT()
void v8::internal::GCTracer::PRINTF_FORMAT (2 , 3) const [private]
PrintNVP()
void v8::internal::GCTracer::PrintNVP () const [private]
Definition at line 825 of file gc-tracer.cc.
                              {
  const base::TimeDelta duration = current_.end_time - current_.start_time;
  const base::TimeDelta spent_in_mutator =
      current_.start_time - previous_.end_time;
  size_t allocated_since_last_gc =
      current_.start_object_size - previous_.end_object_size;
  base::TimeDelta incremental_walltime_duration;
  if (current_.type == Event::Type::INCREMENTAL_MARK_COMPACTOR) {
    incremental_walltime_duration =
        current_.end_time - current_.incremental_marking_start_time;
  }
  // Avoid data races when printing the background scopes.
  base::MutexGuard guard(&background_scopes_mutex_);
  switch (current_.type) {
    case Event::Type::SCAVENGER:
      heap_->isolate()->PrintWithTimestamp(
          "pause=%.1f "
          "mutator=%.1f "
          "gc=%s "
          "reduce_memory=%d "
          "during_sweeping=%d "
          "time_to_safepoint=%.2f "
          "heap.prologue=%.2f "
          "heap.epilogue=%.2f "
          "heap.external.prologue=%.2f "
          "heap.external.epilogue=%.2f "
          "heap.external_weak_global_handles=%.2f "
          "complete.sweep_array_buffers=%.2f "
          "scavenge=%.2f "
          "scavenge.free_remembered_set=%.2f "
          "scavenge.roots=%.2f "
          "scavenge.weak=%.2f "
          "scavenge.weak_global_handles.identify=%.2f "
          "scavenge.weak_global_handles.process=%.2f "
          "scavenge.parallel=%.2f "
          "scavenge.update_refs=%.2f "
          "scavenge.pin_objects=%.2f "
          "scavenge.restore_pinned=%.2f "
          "scavenge.sweep_array_buffers=%.2f "
          "scavenge.resize_new_space=%.2f "
          "background.scavenge.parallel=%.2f "
          "incremental.steps_count=%d "
          "incremental.steps_took=%.1f "
          "scavenge_throughput=%.f "
          "start_object_size=%zu "
          "end_object_size=%zu "
          "start_memory_size=%zu "
          "end_memory_size=%zu "
          "start_holes_size=%zu "
          "end_holes_size=%zu "
          "allocated=%zu "
          "promoted=%zu "
          "quarantined_size=%zu "
          "quarantined_pages=%zu "
          "new_space_survived=%zu "
          "nodes_died_in_new=%d "
          "nodes_copied_in_new=%d "
          "nodes_promoted=%d "
          "promotion_ratio=%.1f%% "
          "average_survival_ratio=%.1f%% "
          "promotion_rate=%.1f%% "
          "new_space_survive_rate_=%.1f%% "
          "new_space_allocation_throughput=%.1f "
          "new_space_capacity=%zu "
          "old_gen_allocation_limit=%zu "
          "global_allocation_limit=%zu "
          "allocation_throughput=%.1f "
          "pool_local_chunks=%zu "
          "pool_shared_chunks=%zu "
          "pool_total_chunks=%zu\n",
          duration.InMillisecondsF(), spent_in_mutator.InMillisecondsF(),
          ToString(current_.type, true), current_.reduce_memory,
          young_gc_during_full_gc_sweeping_,
          current_.scopes[Scope::TIME_TO_SAFEPOINT].InMillisecondsF(),
          current_scope(Scope::HEAP_PROLOGUE),
          current_scope(Scope::HEAP_EPILOGUE),
          current_scope(Scope::HEAP_EXTERNAL_PROLOGUE),
          current_scope(Scope::HEAP_EXTERNAL_EPILOGUE),
          current_scope(Scope::HEAP_EXTERNAL_WEAK_GLOBAL_HANDLES),
          current_scope(Scope::SCAVENGER_COMPLETE_SWEEP_ARRAY_BUFFERS),
          current_scope(Scope::SCAVENGER_SCAVENGE),
          current_scope(Scope::SCAVENGER_FREE_REMEMBERED_SET),
          current_scope(Scope::SCAVENGER_SCAVENGE_ROOTS),
          current_scope(Scope::SCAVENGER_SCAVENGE_WEAK),
          current_scope(Scope::SCAVENGER_SCAVENGE_WEAK_GLOBAL_HANDLES_IDENTIFY),
          current_scope(Scope::SCAVENGER_SCAVENGE_WEAK_GLOBAL_HANDLES_PROCESS),
          current_scope(Scope::SCAVENGER_SCAVENGE_PARALLEL),
          current_scope(Scope::SCAVENGER_SCAVENGE_UPDATE_REFS),
          current_scope(Scope::SCAVENGER_SCAVENGE_PIN_OBJECTS),
          current_scope(
              Scope::SCAVENGER_SCAVENGE_RESTORE_AND_QUARANTINE_PINNED),
          current_scope(Scope::SCAVENGER_SWEEP_ARRAY_BUFFERS),
          current_scope(Scope::SCAVENGER_RESIZE_NEW_SPACE),
          current_scope(Scope::SCAVENGER_BACKGROUND_SCAVENGE_PARALLEL),
          incremental_scope(GCTracer::Scope::MC_INCREMENTAL).steps,
          current_scope(Scope::MC_INCREMENTAL),
          YoungGenerationSpeedInBytesPerMillisecond(
              YoungGenerationSpeedMode::kOnlyAtomicPause)
              .value_or(0.0),
          current_.start_object_size, current_.end_object_size,
          current_.start_memory_size, current_.end_memory_size,
          current_.start_holes_size, current_.end_holes_size,
          allocated_since_last_gc, heap_->promoted_objects_size(),
          heap_->semi_space_new_space()->QuarantinedSize(),
          heap_->semi_space_new_space()->QuarantinedPageCount(),
          heap_->new_space_surviving_object_size(),
          heap_->nodes_died_in_new_space_, heap_->nodes_copied_in_new_space_,
          heap_->nodes_promoted_, heap_->promotion_ratio_,
          AverageSurvivalRatio(), heap_->promotion_rate_,
          heap_->new_space_surviving_rate_,
          NewSpaceAllocationThroughputInBytesPerMillisecond(),
          heap_->new_space() ? heap_->new_space()->TotalCapacity() : 0,
          heap_->old_generation_allocation_limit(),
          heap_->global_allocation_limit(),
          AllocationThroughputInBytesPerMillisecond(),
          heap_->memory_allocator()->GetPooledChunksCount(),
          heap_->memory_allocator()->GetSharedPooledChunksCount(),
          heap_->memory_allocator()->GetTotalPooledChunksCount());
      break;
    case Event::Type::MINOR_MARK_SWEEPER:
    case Event::Type::INCREMENTAL_MINOR_MARK_SWEEPER:
      heap_->isolate()->PrintWithTimestamp(
          "pause=%.1f "
          "mutator=%.1f "
          "gc=%s "
          "reduce_memory=%d "
          "minor_ms=%.2f "
          "time_to_safepoint=%.2f "
          "mark=%.2f "
          "mark.incremental_seed=%.2f "
          "mark.finish_incremental=%.2f "
          "mark.seed=%.2f "
          "mark.traced_handles=%.2f "
          "mark.closure_parallel=%.2f "
          "mark.closure=%.2f "
          "mark.conservative_stack=%.2f "
          "clear=%.2f "
          "clear.string_forwarding_table=%.2f "
          "clear.string_table=%.2f "
          "clear.global_handles=%.2f "
          "complete.sweep_array_buffers=%.2f "
          "complete.sweeping=%.2f "
          "sweep=%.2f "
          "sweep.new=%.2f "
          "sweep.new_lo=%.2f "
          "sweep.update_string_table=%.2f "
          "sweep.start_jobs=%.2f "
          "sweep.array_buffers=%.2f "
          "finish=%.2f "
          "finish.ensure_capacity=%.2f "
          "finish.sweep_array_buffers=%.2f "
          "background.mark=%.2f "
          "background.sweep=%.2f "
          "background.sweep.array_buffers=%.2f "
          "conservative_stack_scanning=%.2f "
          "start_object_size=%zu "
          "end_object_size=%zu "
          "start_memory_size=%zu "
          "end_memory_size=%zu "
          "start_holes_size=%zu "
          "end_holes_size=%zu "
          "allocated=%zu "
          "promoted=%zu "
          "new_space_survived=%zu "
          "nodes_died_in_new=%d "
          "nodes_copied_in_new=%d "
          "nodes_promoted=%d "
          "promotion_ratio=%.1f%% "
          "average_survival_ratio=%.1f%% "
          "promotion_rate=%.1f%% "
          "new_space_survive_rate_=%.1f%% "
          "new_space_capacity=%zu "
          "old_gen_allocation_limit=%zu "
          "global_allocation_limit=%zu "
          "new_space_allocation_throughput=%.1f "
          "allocation_throughput=%.1f\n",
          duration.InMillisecondsF(), spent_in_mutator.InMillisecondsF(), "mms",
          current_.reduce_memory, current_scope(Scope::MINOR_MS),
          current_scope(Scope::TIME_TO_SAFEPOINT),
          current_scope(Scope::MINOR_MS_MARK),
          current_scope(Scope::MINOR_MS_MARK_INCREMENTAL_SEED),
          current_scope(Scope::MINOR_MS_MARK_FINISH_INCREMENTAL),
          current_scope(Scope::MINOR_MS_MARK_SEED),
          current_scope(Scope::MINOR_MS_MARK_TRACED_HANDLES),
          current_scope(Scope::MINOR_MS_MARK_CLOSURE_PARALLEL),
          current_scope(Scope::MINOR_MS_MARK_CLOSURE),
          current_scope(Scope::MINOR_MS_MARK_CONSERVATIVE_STACK),
          current_scope(Scope::MINOR_MS_CLEAR),
          current_scope(Scope::MINOR_MS_CLEAR_STRING_FORWARDING_TABLE),
          current_scope(Scope::MINOR_MS_CLEAR_STRING_TABLE),
          current_scope(Scope::MINOR_MS_CLEAR_WEAK_GLOBAL_HANDLES),
          current_scope(Scope::MINOR_MS_COMPLETE_SWEEP_ARRAY_BUFFERS),
          current_scope(Scope::MINOR_MS_COMPLETE_SWEEPING),
          current_scope(Scope::MINOR_MS_SWEEP),
          current_scope(Scope::MINOR_MS_SWEEP_NEW),
          current_scope(Scope::MINOR_MS_SWEEP_NEW_LO),
          current_scope(Scope::MINOR_MS_SWEEP_UPDATE_STRING_TABLE),
          current_scope(Scope::MINOR_MS_SWEEP_START_JOBS),
          current_scope(Scope::YOUNG_ARRAY_BUFFER_SWEEP),
          current_scope(Scope::MINOR_MS_FINISH),
          current_scope(Scope::MINOR_MS_FINISH_ENSURE_CAPACITY),
          current_scope(Scope::MINOR_MS_FINISH_SWEEP_ARRAY_BUFFERS),
          current_scope(Scope::MINOR_MS_BACKGROUND_MARKING),
          current_scope(Scope::MINOR_MS_BACKGROUND_SWEEPING),
          current_scope(Scope::BACKGROUND_YOUNG_ARRAY_BUFFER_SWEEP),
          current_scope(Scope::CONSERVATIVE_STACK_SCANNING),
          current_.start_object_size, current_.end_object_size,
          current_.start_memory_size, current_.end_memory_size,
          current_.start_holes_size, current_.end_holes_size,
          allocated_since_last_gc, heap_->promoted_objects_size(),
          heap_->new_space_surviving_object_size(),
          heap_->nodes_died_in_new_space_, heap_->nodes_copied_in_new_space_,
          heap_->nodes_promoted_, heap_->promotion_ratio_,
          AverageSurvivalRatio(), heap_->promotion_rate_,
          heap_->new_space_surviving_rate_,
          heap_->new_space() ? heap_->new_space()->TotalCapacity() : 0,
          heap_->old_generation_allocation_limit(),
          heap_->global_allocation_limit(),
          NewSpaceAllocationThroughputInBytesPerMillisecond(),
          AllocationThroughputInBytesPerMillisecond());
      break;
    case Event::Type::MARK_COMPACTOR:
    case Event::Type::INCREMENTAL_MARK_COMPACTOR:
      heap_->isolate()->PrintWithTimestamp(
          "pause=%.1f "
          "mutator=%.1f "
          "gc=%s "
          "reduce_memory=%d "
          "time_to_safepoint=%.2f "
          "heap.prologue=%.2f "
          "heap.embedder_tracing_epilogue=%.2f "
          "heap.epilogue=%.2f "
          "heap.external.prologue=%.1f "
          "heap.external.epilogue=%.1f "
          "heap.external.weak_global_handles=%.1f "
          "clear=%1.f "
          "clear.external_string_table=%.1f "
          "clear.string_forwarding_table=%.1f "
          "clear.weak_global_handles=%.1f "
          "clear.dependent_code=%.1f "
          "clear.maps=%.1f "
          "clear.slots_buffer=%.1f "
          "clear.weak_collections=%.1f "
          "clear.weak_lists=%.1f "
          "clear.weak_references_trivial=%.1f "
          "clear.weak_references_non_trivial=%.1f "
          "clear.weak_references_filter_non_trivial=%.1f "
          "clear.js_weak_references=%.1f "
          "clear.join_filter_job=%.1f"
          "clear.join_job=%.1f "
          "weakness_handling=%.1f "
          "complete.sweep_array_buffers=%.1f "
          "complete.sweeping=%.1f "
          "epilogue=%.1f "
          "evacuate=%.1f "
          "evacuate.pin_pages=%.1f "
          "evacuate.candidates=%.1f "
          "evacuate.clean_up=%.1f "
          "evacuate.copy=%.1f "
          "evacuate.prologue=%.1f "
          "evacuate.epilogue=%.1f "
          "evacuate.rebalance=%.1f "
          "evacuate.update_pointers=%.1f "
          "evacuate.update_pointers.to_new_roots=%.1f "
          "evacuate.update_pointers.slots.main=%.1f "
          "evacuate.update_pointers.weak=%.1f "
          "finish=%.1f "
          "finish.sweep_array_buffers=%.1f "
          "mark=%.1f "
          "mark.finish_incremental=%.1f "
          "mark.roots=%.1f "
          "mark.full_closure_parallel=%.1f "
          "mark.full_closure=%.1f "
          "mark.ephemeron.marking=%.1f "
          "mark.ephemeron.linear=%.1f "
          "mark.embedder_prologue=%.1f "
          "mark.embedder_tracing=%.1f "
          "prologue=%.1f "
          "sweep=%.1f "
          "sweep.code=%.1f "
          "sweep.map=%.1f "
          "sweep.new=%.1f "
          "sweep.new_lo=%.1f "
          "sweep.old=%.1f "
          "sweep.start_jobs=%.1f "
          "incremental=%.1f "
          "incremental.finalize.external.prologue=%.1f "
          "incremental.finalize.external.epilogue=%.1f "
          "incremental.layout_change=%.1f "
          "incremental.sweep_array_buffers=%.1f "
          "incremental.sweeping=%.1f "
          "incremental.embedder_tracing=%.1f "
          "incremental_wrapper_tracing_longest_step=%.1f "
          "incremental_longest_step=%.1f "
          "incremental_steps_count=%d "
          "incremental_marking_throughput=%.f "
          "incremental_walltime_duration=%.f "
          "background.mark=%.1f "
          "background.sweep=%.1f "
          "background.evacuate.copy=%.1f "
          "background.evacuate.update_pointers=%.1f "
          "conservative_stack_scanning=%.2f "
          "start_object_size=%zu "
          "end_object_size=%zu "
          "start_memory_size=%zu "
          "end_memory_size=%zu "
          "start_holes_size=%zu "
          "end_holes_size=%zu "
          "allocated=%zu "
          "promoted=%zu "
          "new_space_survived=%zu "
          "nodes_died_in_new=%d "
          "nodes_copied_in_new=%d "
          "nodes_promoted=%d "
          "promotion_ratio=%.1f%% "
          "average_survival_ratio=%.1f%% "
          "promotion_rate=%.1f%% "
          "new_space_survive_rate=%.1f%% "
          "new_space_allocation_throughput=%.1f "
          "new_space_capacity=%zu "
          "old_gen_allocation_limit=%zu "
          "global_allocation_limit=%zu "
          "allocation_throughput=%.1f "
          "pool_local_chunks=%zu "
          "pool_shared_chunks=%zu "
          "pool_total_chunks=%zu "
          "compaction_speed=%.1f\n",
          duration.InMillisecondsF(), spent_in_mutator.InMillisecondsF(),
          ToString(current_.type, true), current_.reduce_memory,
          current_scope(Scope::TIME_TO_SAFEPOINT),
          current_scope(Scope::HEAP_PROLOGUE),
          current_scope(Scope::HEAP_EMBEDDER_TRACING_EPILOGUE),
          current_scope(Scope::HEAP_EPILOGUE),
          current_scope(Scope::HEAP_EXTERNAL_PROLOGUE),
          current_scope(Scope::HEAP_EXTERNAL_EPILOGUE),
          current_scope(Scope::HEAP_EXTERNAL_WEAK_GLOBAL_HANDLES),
          current_scope(Scope::MC_CLEAR),
          current_scope(Scope::MC_CLEAR_EXTERNAL_STRING_TABLE),
          current_scope(Scope::MC_CLEAR_STRING_FORWARDING_TABLE),
          current_scope(Scope::MC_CLEAR_WEAK_GLOBAL_HANDLES),
          current_scope(Scope::MC_CLEAR_DEPENDENT_CODE),
          current_scope(Scope::MC_CLEAR_MAPS),
          current_scope(Scope::MC_CLEAR_SLOTS_BUFFER),
          current_scope(Scope::MC_CLEAR_WEAK_COLLECTIONS),
          current_scope(Scope::MC_CLEAR_WEAK_LISTS),
          current_scope(Scope::MC_CLEAR_WEAK_REFERENCES_TRIVIAL),
          current_scope(Scope::MC_CLEAR_WEAK_REFERENCES_NON_TRIVIAL),
          current_scope(Scope::MC_CLEAR_WEAK_REFERENCES_FILTER_NON_TRIVIAL),
          current_scope(Scope::MC_CLEAR_JS_WEAK_REFERENCES),
          current_scope(Scope::MC_CLEAR_WEAK_REFERENCES_JOIN_FILTER_JOB),
          current_scope(Scope::MC_CLEAR_JOIN_JOB),
          current_scope(Scope::MC_WEAKNESS_HANDLING),
          current_scope(Scope::MC_COMPLETE_SWEEP_ARRAY_BUFFERS),
          current_scope(Scope::MC_COMPLETE_SWEEPING),
          current_scope(Scope::MC_EPILOGUE), current_scope(Scope::MC_EVACUATE),
          current_scope(Scope::MC_EVACUATE_PIN_PAGES),
          current_scope(Scope::MC_EVACUATE_CANDIDATES),
          current_scope(Scope::MC_EVACUATE_CLEAN_UP),
          current_scope(Scope::MC_EVACUATE_COPY),
          current_scope(Scope::MC_EVACUATE_PROLOGUE),
          current_scope(Scope::MC_EVACUATE_EPILOGUE),
          current_scope(Scope::MC_EVACUATE_REBALANCE),
          current_scope(Scope::MC_EVACUATE_UPDATE_POINTERS),
          current_scope(Scope::MC_EVACUATE_UPDATE_POINTERS_TO_NEW_ROOTS),
          current_scope(Scope::MC_EVACUATE_UPDATE_POINTERS_SLOTS_MAIN),
          current_scope(Scope::MC_EVACUATE_UPDATE_POINTERS_WEAK),
          current_scope(Scope::MC_FINISH),
          current_scope(Scope::MC_FINISH_SWEEP_ARRAY_BUFFERS),
          current_scope(Scope::MC_MARK),
          current_scope(Scope::MC_MARK_FINISH_INCREMENTAL),
          current_scope(Scope::MC_MARK_ROOTS),
          current_scope(Scope::MC_MARK_FULL_CLOSURE_PARALLEL),
          current_scope(Scope::MC_MARK_FULL_CLOSURE),
          current_scope(Scope::MC_MARK_WEAK_CLOSURE_EPHEMERON_MARKING),
          current_scope(Scope::MC_MARK_WEAK_CLOSURE_EPHEMERON_LINEAR),
          current_scope(Scope::MC_MARK_EMBEDDER_PROLOGUE),
          current_scope(Scope::MC_MARK_EMBEDDER_TRACING),
          current_scope(Scope::MC_PROLOGUE), current_scope(Scope::MC_SWEEP),
          current_scope(Scope::MC_SWEEP_CODE),
          current_scope(Scope::MC_SWEEP_MAP),
          current_scope(Scope::MC_SWEEP_NEW),
          current_scope(Scope::MC_SWEEP_NEW_LO),
          current_scope(Scope::MC_SWEEP_OLD),
          current_scope(Scope::MC_SWEEP_START_JOBS),
          current_scope(Scope::MC_INCREMENTAL),
          current_scope(Scope::MC_INCREMENTAL_EXTERNAL_PROLOGUE),
          current_scope(Scope::MC_INCREMENTAL_EXTERNAL_EPILOGUE),
          current_scope(Scope::MC_INCREMENTAL_LAYOUT_CHANGE),
          current_scope(Scope::MC_INCREMENTAL_START),
          current_scope(Scope::MC_INCREMENTAL_SWEEPING),
          current_scope(Scope::MC_INCREMENTAL_EMBEDDER_TRACING),
          incremental_scope(Scope::MC_INCREMENTAL_EMBEDDER_TRACING)
              .longest_step.InMillisecondsF(),
          incremental_scope(Scope::MC_INCREMENTAL)
              .longest_step.InMillisecondsF(),
          incremental_scope(Scope::MC_INCREMENTAL).steps,
          IncrementalMarkingSpeedInBytesPerMillisecond(),
          incremental_walltime_duration.InMillisecondsF(),
          current_scope(Scope::MC_BACKGROUND_MARKING),
          current_scope(Scope::MC_BACKGROUND_SWEEPING),
          current_scope(Scope::MC_BACKGROUND_EVACUATE_COPY),
          current_scope(Scope::MC_BACKGROUND_EVACUATE_UPDATE_POINTERS),
          current_scope(Scope::CONSERVATIVE_STACK_SCANNING),
          current_.start_object_size, current_.end_object_size,
          current_.start_memory_size, current_.end_memory_size,
          current_.start_holes_size, current_.end_holes_size,
          allocated_since_last_gc, heap_->promoted_objects_size(),
          heap_->new_space_surviving_object_size(),
          heap_->nodes_died_in_new_space_, heap_->nodes_copied_in_new_space_,
          heap_->nodes_promoted_, heap_->promotion_ratio_,
          AverageSurvivalRatio(), heap_->promotion_rate_,
          heap_->new_space_surviving_rate_,
          NewSpaceAllocationThroughputInBytesPerMillisecond(),
          heap_->new_space() ? heap_->new_space()->TotalCapacity() : 0,
          heap_->old_generation_allocation_limit(),
          heap_->global_allocation_limit(),
          AllocationThroughputInBytesPerMillisecond(),
          heap_->memory_allocator()->GetPooledChunksCount(),
          heap_->memory_allocator()->GetSharedPooledChunksCount(),
          heap_->memory_allocator()->GetTotalPooledChunksCount(),
          CompactionSpeedInBytesPerMillisecond().value_or(0.0));
      break;
    case Event::Type::START:
      break;
  }
}
References AllocationThroughputInBytesPerMillisecond(), AverageSurvivalRatio(), background_scopes_mutex_, CompactionSpeedInBytesPerMillisecond(), current_, current_scope(), v8::internal::duration, v8::internal::GCTracer::Event::end_holes_size, v8::internal::GCTracer::Event::end_memory_size, v8::internal::GCTracer::Event::end_object_size, v8::internal::GCTracer::Event::end_time, v8::internal::MemoryAllocator::GetPooledChunksCount(), v8::internal::MemoryAllocator::GetSharedPooledChunksCount(), v8::internal::MemoryAllocator::GetTotalPooledChunksCount(), v8::internal::Heap::global_allocation_limit(), heap_, v8::internal::GCTracer::Event::INCREMENTAL_MARK_COMPACTOR, v8::internal::GCTracer::Event::incremental_marking_start_time, v8::internal::GCTracer::Event::INCREMENTAL_MINOR_MARK_SWEEPER, incremental_scope(), IncrementalMarkingSpeedInBytesPerMillisecond(), v8::base::TimeDelta::InMillisecondsF(), v8::internal::Heap::isolate(), v8::internal::kOnlyAtomicPause, v8::internal::GCTracer::Event::MARK_COMPACTOR, v8::internal::Heap::memory_allocator(), v8::internal::GCTracer::Event::MINOR_MARK_SWEEPER, v8::internal::Heap::new_space(), v8::internal::Heap::new_space_surviving_object_size(), v8::internal::Heap::new_space_surviving_rate_, NewSpaceAllocationThroughputInBytesPerMillisecond(), v8::internal::Heap::nodes_copied_in_new_space_, v8::internal::Heap::nodes_died_in_new_space_, v8::internal::Heap::nodes_promoted_, v8::internal::Heap::old_generation_allocation_limit(), previous_, v8::internal::Heap::promoted_objects_size(), v8::internal::Heap::promotion_rate_, v8::internal::Heap::promotion_ratio_, v8::internal::SemiSpaceNewSpace::QuarantinedPageCount(), v8::internal::SemiSpaceNewSpace::QuarantinedSize(), v8::internal::GCTracer::Event::reduce_memory, v8::internal::GCTracer::Event::SCAVENGER, v8::internal::GCTracer::Event::scopes, v8::internal::Heap::semi_space_new_space(), v8::internal::GCTracer::Event::START, v8::internal::GCTracer::Event::start_holes_size, v8::internal::GCTracer::Event::start_memory_size, v8::internal::GCTracer::Event::start_object_size, v8::internal::GCTracer::Event::start_time, v8::internal::ToString(), v8::internal::NewSpace::TotalCapacity(), v8::internal::GCTracer::Event::type, young_gc_during_full_gc_sweeping_, and YoungGenerationSpeedInBytesPerMillisecond().
Referenced by StopObservablePause().
RecordEmbedderMarkingSpeed()
void v8::internal::GCTracer::RecordEmbedderMarkingSpeed (size_t bytes, base::TimeDelta duration)
Definition at line 1284 of file gc-tracer.cc.
                                                                  {
  recorded_embedder_marking_.Push(BytesAndDuration(bytes, duration));
}
References v8::internal::duration, v8::base::RingBuffer< T, _SIZE >::Push(), and recorded_embedder_marking_.
Referenced by v8::internal::anonymous_namespace{cpp-heap.cc}::RecordEmbedderMarkingSpeed().
RecordGCPhasesHistograms()
void v8::internal::GCTracer::RecordGCPhasesHistograms (RecordGCPhasesInfo::Mode mode)
Definition at line 1448 of file gc-tracer.cc.
                                                                   {
  Counters* counters = heap_->isolate()->counters();
  if (mode == RecordGCPhasesInfo::Mode::Finalize) {
    DCHECK_EQ(Scope::FIRST_TOP_MC_SCOPE, Scope::MC_CLEAR);
    counters->gc_finalize_clear()->AddSample(
        TruncateToMs(current_.scopes[Scope::MC_CLEAR]));
    counters->gc_finalize_epilogue()->AddSample(
        TruncateToMs(current_.scopes[Scope::MC_EPILOGUE]));
    counters->gc_finalize_evacuate()->AddSample(
        TruncateToMs(current_.scopes[Scope::MC_EVACUATE]));
    counters->gc_finalize_finish()->AddSample(
        TruncateToMs(current_.scopes[Scope::MC_FINISH]));
    counters->gc_finalize_mark()->AddSample(
        TruncateToMs(current_.scopes[Scope::MC_MARK]));
    counters->gc_finalize_prologue()->AddSample(
        TruncateToMs(current_.scopes[Scope::MC_PROLOGUE]));
    counters->gc_finalize_sweep()->AddSample(
        TruncateToMs(current_.scopes[Scope::MC_SWEEP]));
    if (!current_.incremental_marking_duration.IsZero()) {
      heap_->isolate()->counters()->incremental_marking_sum()->AddSample(
          TruncateToMs(current_.incremental_marking_duration));
    }
    DCHECK_EQ(Scope::LAST_TOP_MC_SCOPE, Scope::MC_SWEEP);
  } else if (mode == RecordGCPhasesInfo::Mode::Scavenger) {
    counters->gc_scavenger_scavenge_main()->AddSample(
        TruncateToMs(current_.scopes[Scope::SCAVENGER_SCAVENGE_PARALLEL]));
    counters->gc_scavenger_scavenge_roots()->AddSample(
        TruncateToMs(current_.scopes[Scope::SCAVENGER_SCAVENGE_ROOTS]));
  }
}
References v8::internal::Isolate::counters(), current_, DCHECK_EQ, v8::internal::GCTracer::RecordGCPhasesInfo::Finalize, v8::internal::GCTracer::Scope::FIRST_TOP_MC_SCOPE, heap_, v8::internal::GCTracer::Event::incremental_marking_duration, v8::internal::Heap::isolate(), v8::base::TimeDelta::IsZero(), v8::internal::GCTracer::Scope::LAST_TOP_MC_SCOPE, mode(), v8::internal::GCTracer::RecordGCPhasesInfo::Scavenger, v8::internal::GCTracer::Event::scopes, and v8::internal::anonymous_namespace{gc-tracer.cc}::TruncateToMs().
Referenced by v8::internal::Heap::CollectGarbage().
RecordGCSizeCounters()
void v8::internal::GCTracer::RecordGCSizeCounters () const
Definition at line 1526 of file gc-tracer.cc.
                                          {
#if defined(V8_USE_PERFETTO)
  TRACE_COUNTER(
      TRACE_DISABLED_BY_DEFAULT("v8.gc"),
      perfetto::CounterTrack("OldGenerationConsumedBytes", parent_track_),
      heap_->OldGenerationConsumedBytes());
  TRACE_COUNTER(TRACE_DISABLED_BY_DEFAULT("v8.gc"),
                perfetto::CounterTrack("GlobalConsumedBytes", parent_track_),
                heap_->GlobalConsumedBytes());
  TRACE_COUNTER(TRACE_DISABLED_BY_DEFAULT("v8.gc"),
                perfetto::CounterTrack("ExternalMemoryBytes", parent_track_),
                heap_->external_memory());
#endif
}
References v8::internal::Heap::external_memory(), v8::internal::Heap::GlobalConsumedBytes(), heap_, v8::internal::Heap::OldGenerationConsumedBytes(), and TRACE_DISABLED_BY_DEFAULT.
Referenced by v8::internal::Heap::IncrementalMarkingLimitReached().
RecordGCSumCounters()
void v8::internal::GCTracer::RecordGCSumCounters () [private]
Definition at line 1479 of file gc-tracer.cc.
                                   {
  const base::TimeDelta atomic_pause_duration =
      current_.scopes[Scope::MARK_COMPACTOR];
  const base::TimeDelta incremental_marking =
      incremental_scopes_[Scope::MC_INCREMENTAL_LAYOUT_CHANGE].duration +
      incremental_scopes_[Scope::MC_INCREMENTAL_START].duration +
      current_.incremental_marking_duration;
  const base::TimeDelta incremental_sweeping =
      incremental_scopes_[Scope::MC_INCREMENTAL_SWEEPING].duration;
  const base::TimeDelta overall_duration =
      atomic_pause_duration + incremental_marking + incremental_sweeping;
  const base::TimeDelta atomic_marking_duration =
      current_.scopes[Scope::MC_PROLOGUE] + current_.scopes[Scope::MC_MARK];
  const base::TimeDelta marking_duration =
      atomic_marking_duration + incremental_marking;
  base::TimeDelta background_duration;
  base::TimeDelta marking_background_duration;
  {
    base::MutexGuard guard(&background_scopes_mutex_);
    background_duration =
        background_scopes_[Scope::MC_BACKGROUND_EVACUATE_COPY] +
        background_scopes_[Scope::MC_BACKGROUND_EVACUATE_UPDATE_POINTERS] +
        background_scopes_[Scope::MC_BACKGROUND_MARKING] +
        background_scopes_[Scope::MC_BACKGROUND_SWEEPING];
    marking_background_duration =
        background_scopes_[Scope::MC_BACKGROUND_MARKING];
  }
  recorded_major_totals_.Push(
      BytesAndDuration(current_.end_object_size, overall_duration));
  // Emit trace event counters.
  TRACE_EVENT_INSTANT2(
      TRACE_DISABLED_BY_DEFAULT("v8.gc"), "V8.GCMarkCompactorSummary",
      TRACE_EVENT_SCOPE_THREAD, "duration", overall_duration.InMillisecondsF(),
      "background_duration", background_duration.InMillisecondsF());
  TRACE_EVENT_INSTANT2(
      TRACE_DISABLED_BY_DEFAULT("v8.gc"), "V8.GCMarkCompactorMarkingSummary",
      TRACE_EVENT_SCOPE_THREAD, "duration", marking_duration.InMillisecondsF(),
      "background_duration", marking_background_duration.InMillisecondsF());
  TRACE_EVENT_INSTANT2(TRACE_DISABLED_BY_DEFAULT("v8.gc"), "V8.GCSpeedSummary",
                       TRACE_EVENT_SCOPE_THREAD, "old_generation_speed",
                       OldGenerationSpeedInBytesPerMillisecond().value_or(0.0),
                       "embedder_speed",
                       EmbedderSpeedInBytesPerMillisecond().value_or(0.0));
}
References background_scopes_, background_scopes_mutex_, current_, v8::internal::GCTracer::IncrementalInfos::duration, EmbedderSpeedInBytesPerMillisecond(), v8::internal::GCTracer::Event::end_object_size, v8::internal::GCTracer::Event::incremental_marking_duration, incremental_scopes_, v8::base::TimeDelta::InMillisecondsF(), OldGenerationSpeedInBytesPerMillisecond(), v8::base::RingBuffer< T, _SIZE >::Push(), recorded_major_totals_, v8::internal::GCTracer::Event::scopes, TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT_INSTANT2, and TRACE_EVENT_SCOPE_THREAD.
Referenced by StopObservablePause().
RecordIncrementalMarkingSpeed()
void v8::internal::GCTracer::RecordIncrementalMarkingSpeed (size_t bytes, base::TimeDelta duration) [private]
Definition at line 1255 of file gc-tracer.cc.
                                                                     {
  DCHECK(!Event::IsYoungGenerationEvent(current_.type));
  if (duration.IsZero() || bytes == 0) return;
  double current_speed =
      static_cast<double>(bytes) / duration.InMillisecondsF();
  if (recorded_major_incremental_marking_speed_ == 0) {
    recorded_major_incremental_marking_speed_ = current_speed;
  } else {
    recorded_major_incremental_marking_speed_ =
        (recorded_major_incremental_marking_speed_ + current_speed) / 2;
  }
}
References current_, v8::internal::DCHECK(), v8::internal::duration, v8::internal::GCTracer::Event::IsYoungGenerationEvent(), recorded_major_incremental_marking_speed_, and v8::internal::GCTracer::Event::type.
Referenced by StopObservablePause().
RecordMutatorUtilization()
void v8::internal::GCTracer::RecordMutatorUtilization (base::TimeTicks mark_compactor_end_time, base::TimeDelta mark_compactor_duration) [private]
Definition at line 1289 of file gc-tracer.cc.
                                                                             {
  total_duration_since_last_mark_compact_ =
      mark_compact_end_time - previous_mark_compact_end_time_;
  DCHECK_GE(total_duration_since_last_mark_compact_, base::TimeDelta());
  const base::TimeDelta mutator_duration =
      total_duration_since_last_mark_compact_ - mark_compact_duration;
  DCHECK_GE(mutator_duration, base::TimeDelta());
  if (average_mark_compact_duration_ == 0 && average_mutator_duration_ == 0) {
    // This is the first event with mutator and mark-compact durations.
    average_mark_compact_duration_ = mark_compact_duration.InMillisecondsF();
    average_mutator_duration_ = mutator_duration.InMillisecondsF();
  } else {
    average_mark_compact_duration_ = (average_mark_compact_duration_ +
                                      mark_compact_duration.InMillisecondsF()) /
                                     2;
    average_mutator_duration_ =
        (average_mutator_duration_ + mutator_duration.InMillisecondsF()) / 2;
  }
  current_mark_compact_mutator_utilization_ =
      !total_duration_since_last_mark_compact_.IsZero()
          ? mutator_duration.InMillisecondsF() /
                total_duration_since_last_mark_compact_.InMillisecondsF()
          : 0;
  previous_mark_compact_end_time_ = mark_compact_end_time;
}
References average_mark_compact_duration_, average_mutator_duration_, current_mark_compact_mutator_utilization_, DCHECK_GE, v8::base::TimeDelta::InMillisecondsF(), v8::base::TimeDelta::IsZero(), previous_mark_compact_end_time_, and total_duration_since_last_mark_compact_.
Referenced by StopObservablePause().
RecordTimeToIncrementalMarkingTask()
void v8::internal::GCTracer::RecordTimeToIncrementalMarkingTask (base::TimeDelta time_to_task)
Definition at line 1269 of file gc-tracer.cc.
                                {
  if (!average_time_to_incremental_marking_task_.has_value()) {
    average_time_to_incremental_marking_task_.emplace(time_to_task);
  } else {
    average_time_to_incremental_marking_task_ =
        (average_time_to_incremental_marking_task_.value() + time_to_task) / 2;
  }
}
References average_time_to_incremental_marking_task_.
ReportFullCycleToRecorder()
void v8::internal::GCTracer::ReportFullCycleToRecorder () [private]
Definition at line 1611 of file gc-tracer.cc.
                                         {
  DCHECK(!Event::IsYoungGenerationEvent(current_.type));
  DCHECK_EQ(Event::State::NOT_RUNNING, current_.state);
  auto* cpp_heap = v8::internal::CppHeap::From(heap_->cpp_heap());
  DCHECK_IMPLIES(cpp_heap,
                 cpp_heap->GetMetricRecorder()->FullGCMetricsReportPending());
  const std::shared_ptr<metrics::Recorder>& recorder =
      heap_->isolate()->metrics_recorder();
  DCHECK_NOT_NULL(recorder);
  if (!recorder->HasEmbedderRecorder()) {
    incremental_mark_batched_events_ = {};
    incremental_sweep_batched_events_ = {};
    if (cpp_heap) {
      cpp_heap->GetMetricRecorder()->ClearCachedEvents();
    }
    return;
  }
  if (!incremental_mark_batched_events_.events.empty()) {
    FlushBatchedEvents(incremental_mark_batched_events_, heap_->isolate());
  }
  if (!incremental_sweep_batched_events_.events.empty()) {
    FlushBatchedEvents(incremental_sweep_batched_events_, heap_->isolate());
  }
  v8::metrics::GarbageCollectionFullCycle event;
  event.reason = static_cast<int>(current_.gc_reason);
  event.priority = current_.priority;
  // Managed C++ heap statistics:
  if (cpp_heap) {
    cpp_heap->GetMetricRecorder()->FlushBatchedIncrementalEvents();
    const std::optional<cppgc::internal::MetricRecorder::GCCycle>
        optional_cppgc_event =
            cpp_heap->GetMetricRecorder()->ExtractLastFullGcEvent();
    DCHECK(optional_cppgc_event.has_value());
    DCHECK(!cpp_heap->GetMetricRecorder()->FullGCMetricsReportPending());
    const cppgc::internal::MetricRecorder::GCCycle& cppgc_event =
        optional_cppgc_event.value();
    DCHECK_EQ(cppgc_event.type,
              cppgc::internal::MetricRecorder::GCCycle::Type::kMajor);
    CopyTimeMetrics(event.total_cpp, cppgc_event.total);
    CopyTimeMetrics(event.main_thread_cpp, cppgc_event.main_thread);
    CopyTimeMetrics(event.main_thread_atomic_cpp,
                    cppgc_event.main_thread_atomic);
    CopyTimeMetrics(event.main_thread_incremental_cpp,
                    cppgc_event.main_thread_incremental);
    CopySizeMetrics(event.objects_cpp, cppgc_event.objects);
    CopySizeMetrics(event.memory_cpp, cppgc_event.memory);
    DCHECK_NE(-1, cppgc_event.collection_rate_in_percent);
    event.collection_rate_cpp_in_percent =
        cppgc_event.collection_rate_in_percent;
    DCHECK_NE(-1, cppgc_event.efficiency_in_bytes_per_us);
    event.efficiency_cpp_in_bytes_per_us =
        cppgc_event.efficiency_in_bytes_per_us;
    DCHECK_NE(-1, cppgc_event.main_thread_efficiency_in_bytes_per_us);
    event.main_thread_efficiency_cpp_in_bytes_per_us =
        cppgc_event.main_thread_efficiency_in_bytes_per_us;
    if (total_duration_since_last_mark_compact_.IsZero()) {
      event.collection_weight_cpp_in_percent = 0;
      event.main_thread_collection_weight_cpp_in_percent = 0;
    } else {
      event.collection_weight_cpp_in_percent =
          static_cast<double>(event.total_cpp.total_wall_clock_duration_in_us) /
          total_duration_since_last_mark_compact_.InMicroseconds();
      event.main_thread_collection_weight_cpp_in_percent =
          static_cast<double>(
              event.main_thread_cpp.total_wall_clock_duration_in_us) /
          total_duration_since_last_mark_compact_.InMicroseconds();
    }
  }
  // Unified heap statistics:
  const base::TimeDelta atomic_pause_duration =
      current_.scopes[Scope::MARK_COMPACTOR];
  const base::TimeDelta incremental_marking =
      current_.incremental_scopes[Scope::MC_INCREMENTAL_LAYOUT_CHANGE]
          .duration +
      current_.incremental_scopes[Scope::MC_INCREMENTAL_START].duration +
      current_.incremental_marking_duration;
  const base::TimeDelta incremental_sweeping =
      current_.incremental_scopes[Scope::MC_INCREMENTAL_SWEEPING].duration;
  const base::TimeDelta overall_duration =
      atomic_pause_duration + incremental_marking + incremental_sweeping;
  const base::TimeDelta marking_background_duration =
      current_.scopes[Scope::MC_BACKGROUND_MARKING];
  const base::TimeDelta sweeping_background_duration =
      current_.scopes[Scope::MC_BACKGROUND_SWEEPING];
  const base::TimeDelta compact_background_duration =
      current_.scopes[Scope::MC_BACKGROUND_EVACUATE_COPY] +
      current_.scopes[Scope::MC_BACKGROUND_EVACUATE_UPDATE_POINTERS];
  const base::TimeDelta background_duration = marking_background_duration +
                                              sweeping_background_duration +
                                              compact_background_duration;
  const base::TimeDelta atomic_marking_duration =
      current_.scopes[Scope::MC_PROLOGUE] + current_.scopes[Scope::MC_MARK];
  const base::TimeDelta marking_duration =
      atomic_marking_duration + incremental_marking;
  const base::TimeDelta weak_duration = current_.scopes[Scope::MC_CLEAR];
  const base::TimeDelta compact_duration = current_.scopes[Scope::MC_EVACUATE] +
                                           current_.scopes[Scope::MC_FINISH] +
                                           current_.scopes[Scope::MC_EPILOGUE];
  const base::TimeDelta atomic_sweeping_duration =
      current_.scopes[Scope::MC_SWEEP];
  const base::TimeDelta sweeping_duration =
      atomic_sweeping_duration + incremental_sweeping;
  event.main_thread_atomic.total_wall_clock_duration_in_us =
      atomic_pause_duration.InMicroseconds();
  event.main_thread.total_wall_clock_duration_in_us =
      overall_duration.InMicroseconds();
  event.total.total_wall_clock_duration_in_us =
      (overall_duration + background_duration).InMicroseconds();
  event.main_thread_atomic.mark_wall_clock_duration_in_us =
      atomic_marking_duration.InMicroseconds();
  event.main_thread.mark_wall_clock_duration_in_us =
      marking_duration.InMicroseconds();
  event.total.mark_wall_clock_duration_in_us =
      (marking_duration + marking_background_duration).InMicroseconds();
  event.main_thread_atomic.weak_wall_clock_duration_in_us =
      event.main_thread.weak_wall_clock_duration_in_us =
          event.total.weak_wall_clock_duration_in_us =
              weak_duration.InMicroseconds();
  event.main_thread_atomic.compact_wall_clock_duration_in_us =
      event.main_thread.compact_wall_clock_duration_in_us =
          compact_duration.InMicroseconds();
  event.total.compact_wall_clock_duration_in_us =
      (compact_duration + compact_background_duration).InMicroseconds();
  event.main_thread_atomic.sweep_wall_clock_duration_in_us =
      atomic_sweeping_duration.InMicroseconds();
  event.main_thread.sweep_wall_clock_duration_in_us =
      sweeping_duration.InMicroseconds();
  event.total.sweep_wall_clock_duration_in_us =
      (sweeping_duration + sweeping_background_duration).InMicroseconds();
  if (current_.type == Event::Type::INCREMENTAL_MARK_COMPACTOR) {
    event.main_thread_incremental.mark_wall_clock_duration_in_us =
        incremental_marking.InMicroseconds();
    event.incremental_marking_start_stop_wall_clock_duration_in_us =
        (current_.start_time - current_.incremental_marking_start_time)
            .InMicroseconds();
  } else {
    DCHECK(incremental_marking.IsZero());
    event.main_thread_incremental.mark_wall_clock_duration_in_us = -1;
  }
  // TODO(chromium:1154636): We always report the value of incremental sweeping,
  // even if it is zero.
  event.main_thread_incremental.sweep_wall_clock_duration_in_us =
      incremental_sweeping.InMicroseconds();
  // Objects:
  event.objects.bytes_before = current_.start_object_size;
  event.objects.bytes_after = current_.end_object_size;
  event.objects.bytes_freed =
      current_.start_object_size - current_.end_object_size;
  // Memory:
  event.memory.bytes_before = current_.start_memory_size;
  event.memory.bytes_after = current_.end_memory_size;
  event.memory.bytes_freed =
      current_.start_memory_size > current_.end_memory_size
          ? current_.start_memory_size - current_.end_memory_size
          : 0U;
  // Collection Rate:
  if (event.objects.bytes_before == 0) {
    event.collection_rate_in_percent = 0;
  } else {
    event.collection_rate_in_percent =
        static_cast<double>(event.objects.bytes_freed) /
        event.objects.bytes_before;
  }
  // Efficiency:
  if (event.objects.bytes_freed == 0) {
    event.efficiency_in_bytes_per_us = 0;
    event.main_thread_efficiency_in_bytes_per_us = 0;
  } else {
    // Here, event.main_thread or even event.total can be
    // zero if the clock resolution is not small enough and the entire GC was
    // very short, so the timed value was zero. This appears to happen on
    // Windows, see crbug.com/1338256 and crbug.com/1339180. In this case, we
    // are only here if the number of freed bytes is nonzero and the division
    // below produces an infinite value.
    event.efficiency_in_bytes_per_us =
        static_cast<double>(event.objects.bytes_freed) /
        event.total.total_wall_clock_duration_in_us;
    event.main_thread_efficiency_in_bytes_per_us =
        static_cast<double>(event.objects.bytes_freed) /
        event.main_thread.total_wall_clock_duration_in_us;
  }
  if (total_duration_since_last_mark_compact_.IsZero()) {
    event.collection_weight_in_percent = 0;
    event.main_thread_collection_weight_in_percent = 0;
  } else {
    event.collection_weight_in_percent =
        static_cast<double>(event.total.total_wall_clock_duration_in_us) /
        total_duration_since_last_mark_compact_.InMicroseconds();
    event.main_thread_collection_weight_in_percent =
        static_cast<double>(event.main_thread.total_wall_clock_duration_in_us) /
        total_duration_since_last_mark_compact_.InMicroseconds();
  }
  recorder->AddMainThreadEvent(event, GetContextId(heap_->isolate()));
}
References v8::metrics::GarbageCollectionSizes::bytes_before, v8::metrics::GarbageCollectionSizes::bytes_freed, cppgc::internal::MetricRecorder::GCCycle::collection_rate_in_percent, v8::internal::anonymous_namespace{gc-tracer.cc}::CopySizeMetrics(), v8::internal::anonymous_namespace{gc-tracer.cc}::CopyTimeMetrics(), v8::internal::Heap::cpp_heap(), current_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, DCHECK_NE, DCHECK_NOT_NULL, v8::internal::GCTracer::IncrementalInfos::duration, cppgc::internal::MetricRecorder::GCCycle::efficiency_in_bytes_per_us, v8::internal::GCTracer::Event::end_memory_size, v8::internal::GCTracer::Event::end_object_size, v8::internal::anonymous_namespace{gc-tracer.cc}::FlushBatchedEvents(), v8::internal::CppHeap::From(), v8::internal::GCTracer::Event::gc_reason, v8::internal::anonymous_namespace{gc-tracer.cc}::GetContextId(), heap_, incremental_mark_batched_events_, v8::internal::GCTracer::Event::INCREMENTAL_MARK_COMPACTOR, v8::internal::GCTracer::Event::incremental_marking_duration, v8::internal::GCTracer::Event::incremental_marking_start_time, v8::internal::GCTracer::Event::incremental_scopes, incremental_sweep_batched_events_, v8::base::TimeDelta::InMicroseconds(), v8::internal::Heap::isolate(), v8::internal::GCTracer::Event::IsYoungGenerationEvent(), v8::base::TimeDelta::IsZero(), cppgc::internal::MetricRecorder::GCCycle::kMajor, cppgc::internal::MetricRecorder::GCCycle::main_thread, cppgc::internal::MetricRecorder::GCCycle::main_thread_atomic, v8::metrics::GarbageCollectionFullCycle::main_thread_atomic_cpp, v8::metrics::GarbageCollectionFullCycle::main_thread_cpp, v8::metrics::GarbageCollectionFullCycle::main_thread_efficiency_in_bytes_per_us, cppgc::internal::MetricRecorder::GCCycle::main_thread_efficiency_in_bytes_per_us, cppgc::internal::MetricRecorder::GCCycle::main_thread_incremental, v8::metrics::GarbageCollectionFullCycle::main_thread_incremental_cpp, cppgc::internal::MetricRecorder::GCCycle::memory, v8::metrics::GarbageCollectionFullCycle::memory_cpp, v8::internal::Isolate::metrics_recorder(), v8::internal::GCTracer::Event::NOT_RUNNING, v8::metrics::GarbageCollectionFullCycle::objects, cppgc::internal::MetricRecorder::GCCycle::objects, v8::metrics::GarbageCollectionFullCycle::objects_cpp, v8::internal::GCTracer::Event::priority, v8::metrics::GarbageCollectionFullCycle::reason, v8::internal::GCTracer::Event::scopes, v8::internal::GCTracer::Event::start_memory_size, v8::internal::GCTracer::Event::start_object_size, v8::internal::GCTracer::Event::start_time, v8::internal::GCTracer::Event::state, v8::metrics::GarbageCollectionFullCycle::total, cppgc::internal::MetricRecorder::GCCycle::total, v8::metrics::GarbageCollectionFullCycle::total_cpp, total_duration_since_last_mark_compact_, v8::metrics::GarbageCollectionPhases::total_wall_clock_duration_in_us, cppgc::internal::MetricRecorder::GCCycle::type, v8::internal::GCTracer::Event::type, and v8::internal::U.
Referenced by StopCycle().
ReportIncrementalMarkingStepToRecorder()
void v8::internal::GCTracer::ReportIncrementalMarkingStepToRecorder (double v8_duration) [private]
Definition at line 1813 of file gc-tracer.cc.
                                                                        {
  DCHECK_EQ(Event::Type::INCREMENTAL_MARK_COMPACTOR, current_.type);
  static constexpr int kMaxBatchedEvents =
      CppHeap::MetricRecorderAdapter::kMaxBatchedEvents;
  const std::shared_ptr<metrics::Recorder>& recorder =
      heap_->isolate()->metrics_recorder();
  DCHECK_NOT_NULL(recorder);
  if (!recorder->HasEmbedderRecorder()) return;
  incremental_mark_batched_events_.events.emplace_back();
  if (heap_->cpp_heap()) {
    const std::optional<
        cppgc::internal::MetricRecorder::MainThreadIncrementalMark>
        cppgc_event = v8::internal::CppHeap::From(heap_->cpp_heap())
                          ->GetMetricRecorder()
                          ->ExtractLastIncrementalMarkEvent();
    if (cppgc_event.has_value()) {
      DCHECK_NE(-1, cppgc_event.value().duration_us);
      incremental_mark_batched_events_.events.back()
          .cpp_wall_clock_duration_in_us = cppgc_event.value().duration_us;
    }
  }
  incremental_mark_batched_events_.events.back().wall_clock_duration_in_us =
      static_cast<int64_t>(v8_duration *
                           base::Time::kMicrosecondsPerMillisecond);
  if (incremental_mark_batched_events_.events.size() == kMaxBatchedEvents) {
    FlushBatchedEvents(incremental_mark_batched_events_, heap_->isolate());
  }
}
References v8::internal::Heap::cpp_heap(), current_, DCHECK_EQ, DCHECK_NE, DCHECK_NOT_NULL, v8::internal::CppHeap::MetricRecorderAdapter::ExtractLastIncrementalMarkEvent(), v8::internal::anonymous_namespace{gc-tracer.cc}::FlushBatchedEvents(), v8::internal::CppHeap::From(), v8::internal::CppHeap::GetMetricRecorder(), heap_, incremental_mark_batched_events_, v8::internal::GCTracer::Event::INCREMENTAL_MARK_COMPACTOR, v8::internal::Heap::isolate(), v8::internal::CppHeap::MetricRecorderAdapter::kMaxBatchedEvents, v8::base::TimeConstants::kMicrosecondsPerMillisecond, v8::internal::Isolate::metrics_recorder(), and v8::internal::GCTracer::Event::type.
Referenced by AddIncrementalMarkingStep().
ReportIncrementalSweepingStepToRecorder()
void v8::internal::GCTracer::ReportIncrementalSweepingStepToRecorder (double v8_duration) [private]
Definition at line 1842 of file gc-tracer.cc.
                                                                         {
  static constexpr int kMaxBatchedEvents =
      CppHeap::MetricRecorderAdapter::kMaxBatchedEvents;
  const std::shared_ptr<metrics::Recorder>& recorder =
      heap_->isolate()->metrics_recorder();
  DCHECK_NOT_NULL(recorder);
  if (!recorder->HasEmbedderRecorder()) return;
  incremental_sweep_batched_events_.events.emplace_back();
  incremental_sweep_batched_events_.events.back().wall_clock_duration_in_us =
      static_cast<int64_t>(v8_duration *
                           base::Time::kMicrosecondsPerMillisecond);
  if (incremental_sweep_batched_events_.events.size() == kMaxBatchedEvents) {
    FlushBatchedEvents(incremental_sweep_batched_events_, heap_->isolate());
  }
}
References DCHECK_NOT_NULL, v8::internal::anonymous_namespace{gc-tracer.cc}::FlushBatchedEvents(), heap_, incremental_sweep_batched_events_, v8::internal::Heap::isolate(), v8::internal::CppHeap::MetricRecorderAdapter::kMaxBatchedEvents, v8::base::TimeConstants::kMicrosecondsPerMillisecond, and v8::internal::Isolate::metrics_recorder().
Referenced by AddIncrementalSweepingStep().
ReportYoungCycleToRecorder()
void v8::internal::GCTracer::ReportYoungCycleToRecorder () [private]
Definition at line 1858 of file gc-tracer.cc.
                                          {
  DCHECK(Event::IsYoungGenerationEvent(current_.type));
  DCHECK_EQ(Event::State::NOT_RUNNING, current_.state);
  const std::shared_ptr<metrics::Recorder>& recorder =
      heap_->isolate()->metrics_recorder();
  DCHECK_NOT_NULL(recorder);
  if (!recorder->HasEmbedderRecorder()) return;
  v8::metrics::GarbageCollectionYoungCycle event;
  // Reason:
  event.reason = static_cast<int>(current_.gc_reason);
  event.priority = current_.priority;
#if defined(CPPGC_YOUNG_GENERATION)
  // Managed C++ heap statistics:
  auto* cpp_heap = v8::internal::CppHeap::From(heap_->cpp_heap());
  if (cpp_heap && cpp_heap->generational_gc_supported()) {
    auto* metric_recorder = cpp_heap->GetMetricRecorder();
    const std::optional<cppgc::internal::MetricRecorder::GCCycle>
        optional_cppgc_event = metric_recorder->ExtractLastYoungGcEvent();
    // We bail out from Oilpan's young GC if the full GC is already in progress.
    // Check here if the young generation event was reported.
    if (optional_cppgc_event) {
      DCHECK(!metric_recorder->YoungGCMetricsReportPending());
      const cppgc::internal::MetricRecorder::GCCycle& cppgc_event =
          optional_cppgc_event.value();
      DCHECK_EQ(cppgc_event.type,
                cppgc::internal::MetricRecorder::GCCycle::Type::kMinor);
      CopyTimeMetrics(event.total_cpp, cppgc_event.total);
      CopySizeMetrics(event.objects_cpp, cppgc_event.objects);
      CopySizeMetrics(event.memory_cpp, cppgc_event.memory);
      DCHECK_NE(-1, cppgc_event.collection_rate_in_percent);
      event.collection_rate_cpp_in_percent =
          cppgc_event.collection_rate_in_percent;
      DCHECK_NE(-1, cppgc_event.efficiency_in_bytes_per_us);
      event.efficiency_cpp_in_bytes_per_us =
          cppgc_event.efficiency_in_bytes_per_us;
      DCHECK_NE(-1, cppgc_event.main_thread_efficiency_in_bytes_per_us);
      event.main_thread_efficiency_cpp_in_bytes_per_us =
          cppgc_event.main_thread_efficiency_in_bytes_per_us;
    }
  }
#endif // defined(CPPGC_YOUNG_GENERATION)
  // Total:
  const base::TimeDelta total_wall_clock_duration =
      YoungGenerationWallTime(current_);
  // TODO(chromium:1154636): Consider adding BACKGROUND_YOUNG_ARRAY_BUFFER_SWEEP
  // (both for the case of the scavenger and the minor mark-sweeper).
  event.total_wall_clock_duration_in_us =
      total_wall_clock_duration.InMicroseconds();
  // MainThread:
  const base::TimeDelta main_thread_wall_clock_duration =
      current_.scopes[Scope::SCAVENGER] +
      current_.scopes[Scope::MINOR_MARK_SWEEPER];
  event.main_thread_wall_clock_duration_in_us =
      main_thread_wall_clock_duration.InMicroseconds();
  // Collection Rate:
  if (current_.young_object_size == 0) {
    event.collection_rate_in_percent = 0;
  } else {
    event.collection_rate_in_percent =
        static_cast<double>(current_.survived_young_object_size) /
        current_.young_object_size;
  }
  // Efficiency:
  //
  // It's possible that time durations are rounded/clamped to zero, in which
  // case we report infinity efficiency.
  const double freed_bytes = static_cast<double>(
      current_.young_object_size - current_.survived_young_object_size);
  event.efficiency_in_bytes_per_us =
      total_wall_clock_duration.IsZero()
          ? std::numeric_limits<double>::infinity()
          : freed_bytes / total_wall_clock_duration.InMicroseconds();
  event.main_thread_efficiency_in_bytes_per_us =
      main_thread_wall_clock_duration.IsZero()
          ? std::numeric_limits<double>::infinity()
          : freed_bytes / main_thread_wall_clock_duration.InMicroseconds();
  recorder->AddMainThreadEvent(event, GetContextId(heap_->isolate()));
}
References cppgc::internal::MetricRecorder::GCCycle::collection_rate_in_percent, v8::internal::anonymous_namespace{gc-tracer.cc}::CopySizeMetrics(), v8::internal::anonymous_namespace{gc-tracer.cc}::CopyTimeMetrics(), v8::internal::Heap::cpp_heap(), current_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, DCHECK_NOT_NULL, cppgc::internal::MetricRecorder::GCCycle::efficiency_in_bytes_per_us, v8::internal::CppHeap::From(), v8::internal::GCTracer::Event::gc_reason, v8::internal::anonymous_namespace{gc-tracer.cc}::GetContextId(), heap_, v8::base::TimeDelta::InMicroseconds(), v8::internal::Heap::isolate(), v8::internal::GCTracer::Event::IsYoungGenerationEvent(), v8::base::TimeDelta::IsZero(), cppgc::internal::MetricRecorder::GCCycle::kMinor, cppgc::internal::MetricRecorder::GCCycle::main_thread_efficiency_in_bytes_per_us, cppgc::internal::MetricRecorder::GCCycle::memory, v8::internal::Isolate::metrics_recorder(), v8::internal::GCTracer::Event::NOT_RUNNING, cppgc::internal::MetricRecorder::GCCycle::objects, v8::internal::GCTracer::Event::priority, v8::metrics::GarbageCollectionYoungCycle::reason, v8::internal::GCTracer::Event::scopes, v8::internal::GCTracer::Event::state, v8::internal::GCTracer::Event::survived_young_object_size, cppgc::internal::MetricRecorder::GCCycle::total, cppgc::internal::MetricRecorder::GCCycle::type, v8::internal::GCTracer::Event::type, v8::internal::GCTracer::Event::young_object_size, and v8::internal::anonymous_namespace{gc-tracer.cc}::YoungGenerationWallTime().
Referenced by StopCycle().
ResetForTesting()
void v8::internal::GCTracer::ResetForTesting () [private]
Definition at line 199 of file gc-tracer.cc.
                               {
  auto* heap = heap_;
  this->~GCTracer();
  new (this)
      GCTracer(heap, base::TimeTicks::Now(), GarbageCollectionReason::kTesting);
}
References GCTracer(), heap_, v8::internal::kTesting, and v8::base::TimeTicks::Now().
ResetSurvivalEvents()
void v8::internal::GCTracer::ResetSurvivalEvents ()
Definition at line 1425 of file gc-tracer.cc.
{ recorded_survival_ratios_.Clear(); }
References v8::base::RingBuffer< T, _SIZE >::Clear(), and recorded_survival_ratios_.
Referenced by v8::internal::Heap::NotifyContextDisposed().
SampleAllocation()
void v8::internal::GCTracer::SampleAllocation (base::TimeTicks current, size_t new_space_counter_bytes, size_t old_generation_counter_bytes, size_t embedder_counter_bytes)
Definition at line 638 of file gc-tracer.cc.
                                                               {
  int64_t new_space_allocated_bytes = std::max<int64_t>(
      new_space_counter_bytes - new_space_allocation_counter_bytes_, 0);
  int64_t old_generation_allocated_bytes = std::max<int64_t>(
      old_generation_counter_bytes - old_generation_allocation_counter_bytes_,
      0);
  int64_t embedder_allocated_bytes = std::max<int64_t>(
      embedder_counter_bytes - embedder_allocation_counter_bytes_, 0);
  const base::TimeDelta allocation_duration = current - allocation_time_;
  allocation_time_ = current;
  new_space_allocation_counter_bytes_ = new_space_counter_bytes;
  old_generation_allocation_counter_bytes_ = old_generation_counter_bytes;
  embedder_allocation_counter_bytes_ = embedder_counter_bytes;
  new_generation_allocations_.Update(
      BytesAndDuration(new_space_allocated_bytes, allocation_duration));
  old_generation_allocations_.Update(
      BytesAndDuration(old_generation_allocated_bytes, allocation_duration));
  embedder_generation_allocations_.Update(
      BytesAndDuration(embedder_allocated_bytes, allocation_duration));
  if (v8_flags.memory_balancer) {
    heap_->mb_->UpdateAllocationRate(old_generation_allocated_bytes,
                                     allocation_duration);
  }
#if defined(V8_USE_PERFETTO)
  TRACE_COUNTER(TRACE_DISABLED_BY_DEFAULT("v8.gc"),
                perfetto::CounterTrack("OldGenerationAllocationThroughput",
                                       parent_track_),
                OldGenerationAllocationThroughputInBytesPerMillisecond());
  TRACE_COUNTER(
      TRACE_DISABLED_BY_DEFAULT("v8.gc"),
      perfetto::CounterTrack("EmbedderAllocationThroughput", parent_track_),
      EmbedderAllocationThroughputInBytesPerMillisecond());
  TRACE_COUNTER(
      TRACE_DISABLED_BY_DEFAULT("v8.gc"),
      perfetto::CounterTrack("NewSpaceAllocationThroughput", parent_track_),
      NewSpaceAllocationThroughputInBytesPerMillisecond());
#endif
}
References allocation_time_, embedder_allocation_counter_bytes_, embedder_generation_allocations_, EmbedderAllocationThroughputInBytesPerMillisecond(), heap_, v8::internal::Heap::mb_, new_generation_allocations_, new_space_allocation_counter_bytes_, NewSpaceAllocationThroughputInBytesPerMillisecond(), old_generation_allocation_counter_bytes_, old_generation_allocations_, OldGenerationAllocationThroughputInBytesPerMillisecond(), TRACE_DISABLED_BY_DEFAULT, heap::base::SmoothedBytesAndDuration::Update(), and v8::internal::v8_flags.
Referenced by StartInSafepoint().
SampleConcurrencyEsimate()
void v8::internal::GCTracer::SampleConcurrencyEsimate (size_t concurrency)
Definition at line 684 of file gc-tracer.cc.
                                                          {
  // For now, we only expect a single sample.
  DCHECK_EQ(current_.concurrency_estimate, 1);
  DCHECK_GT(concurrency, 0);
  current_.concurrency_estimate = concurrency;
}
References v8::internal::GCTracer::Event::concurrency_estimate, current_, DCHECK_EQ, and DCHECK_GT.
Referenced by v8::internal::MinorMarkSweepCollector::FinishConcurrentMarking().
StartAtomicPause()
void v8::internal::GCTracer::StartAtomicPause ()
Definition at line 303 of file gc-tracer.cc.
                                {
  DCHECK_EQ(Event::State::MARKING, current_.state);
  current_.state = Event::State::ATOMIC;
}
References v8::internal::GCTracer::Event::ATOMIC, current_, DCHECK_EQ, v8::internal::GCTracer::Event::MARKING, and v8::internal::GCTracer::Event::state.
Referenced by v8::internal::Heap::PerformGarbageCollection().
StartCycle()
void v8::internal::GCTracer::StartCycle (GarbageCollector collector, GarbageCollectionReason gc_reason, const char * collector_reason, MarkingType marking)
Definition at line 228 of file gc-tracer.cc.
                                                                             {
  // We cannot start a new cycle while there's another one in its atomic pause.
  DCHECK_NE(Event::State::ATOMIC, current_.state);
  // We cannot start a new cycle while a young generation GC cycle has
  // already interrupted a full GC cycle.
  DCHECK(!young_gc_during_full_gc_sweeping_);
  young_gc_during_full_gc_sweeping_ =
      current_.state != Event::State::NOT_RUNNING;
  CHECK_IMPLIES(young_gc_during_full_gc_sweeping_,
                current_.state == Event::State::SWEEPING);
  if (young_gc_during_full_gc_sweeping_) {
    // The cases for interruption are: Scavenger, MinorMS interrupting sweeping.
    // In both cases we are fine with fetching background counters now and
    // fixing them up later in StopAtomicPause().
    FetchBackgroundCounters();
  }
  DCHECK_IMPLIES(young_gc_during_full_gc_sweeping_,
                 Heap::IsYoungGenerationCollector(collector));
  DCHECK_IMPLIES(young_gc_during_full_gc_sweeping_,
                 !Event::IsYoungGenerationEvent(current_.type));
  Event::Type type;
  switch (collector) {
    case GarbageCollector::SCAVENGER:
      type = Event::Type::SCAVENGER;
      break;
    case GarbageCollector::MINOR_MARK_SWEEPER:
      type = marking == MarkingType::kIncremental
                 ? Event::Type::INCREMENTAL_MINOR_MARK_SWEEPER
                 : Event::Type::MINOR_MARK_SWEEPER;
      break;
    case GarbageCollector::MARK_COMPACTOR:
      type = marking == MarkingType::kIncremental
                 ? Event::Type::INCREMENTAL_MARK_COMPACTOR
                 : Event::Type::MARK_COMPACTOR;
      break;
  }
  DCHECK_IMPLIES(!young_gc_during_full_gc_sweeping_,
                 current_.state == Event::State::NOT_RUNNING);
  DCHECK_EQ(Event::State::NOT_RUNNING, previous_.state);
  previous_ = current_;
  current_ = Event(type, Event::State::MARKING, gc_reason, collector_reason,
                   heap_->isolate()->priority());
  switch (marking) {
    case MarkingType::kAtomic:
      DCHECK(IsInObservablePause());
      // TODO(chromium:1154636): The start_time of the current event contains
      // currently the start time of the observable pause. This should be
      // reconsidered.
      current_.start_time = start_of_observable_pause_.value();
      current_.reduce_memory = heap_->ShouldReduceMemory();
      break;
    case MarkingType::kIncremental:
      // The current event will be updated later.
      DCHECK_IMPLIES(Heap::IsYoungGenerationCollector(collector),
                     (v8_flags.minor_ms &&
                      collector == GarbageCollector::MINOR_MARK_SWEEPER));
      DCHECK(!IsInObservablePause());
      break;
  }
  if (Heap::IsYoungGenerationCollector(collector)) {
    epoch_young_ = next_epoch();
  } else {
    epoch_full_ = next_epoch();
  }
}
References v8::internal::GCTracer::Event::ATOMIC, CHECK_IMPLIES, current_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, DCHECK_NE, epoch_full_, epoch_young_, FetchBackgroundCounters(), heap_, v8::internal::GCTracer::Event::INCREMENTAL_MARK_COMPACTOR, v8::internal::GCTracer::Event::INCREMENTAL_MINOR_MARK_SWEEPER, v8::internal::Heap::isolate(), v8::internal::Heap::IsYoungGenerationCollector(), v8::internal::GCTracer::Event::IsYoungGenerationEvent(), kAtomic, kIncremental, v8::internal::MARK_COMPACTOR, v8::internal::GCTracer::Event::MARK_COMPACTOR, marking, v8::internal::GCTracer::Event::MARKING, v8::internal::MINOR_MARK_SWEEPER, v8::internal::GCTracer::Event::MINOR_MARK_SWEEPER, v8::internal::anonymous_namespace{gc-tracer.cc}::next_epoch(), v8::internal::GCTracer::Event::NOT_RUNNING, previous_, v8::internal::Isolate::priority(), v8::internal::GCTracer::Event::reduce_memory, v8::internal::SCAVENGER, v8::internal::GCTracer::Event::SCAVENGER, v8::internal::Heap::ShouldReduceMemory(), start_of_observable_pause_, v8::internal::GCTracer::Event::start_time, v8::internal::GCTracer::Event::state, v8::internal::GCTracer::Event::SWEEPING, v8::internal::GCTracer::Event::type, v8::internal::tracing::type, v8::internal::v8_flags, and young_gc_during_full_gc_sweeping_.
Referenced by v8::internal::Heap::PerformGarbageCollection(), and v8::internal::Heap::StartIncrementalMarking().
StartInSafepoint()
void v8::internal::GCTracer::StartInSafepoint (base::TimeTicks time)
Definition at line 308 of file gc-tracer.cc.
                                                  {
  SampleAllocation(current_.start_time, heap_->NewSpaceAllocationCounter(),
                   heap_->OldGenerationAllocationCounter(),
                   heap_->EmbedderAllocationCounter());
  current_.start_object_size = heap_->SizeOfObjects();
  current_.start_memory_size = heap_->memory_allocator()->Size();
  current_.start_holes_size = CountTotalHolesSize(heap_);
  size_t new_space_size = (heap_->new_space() ? heap_->new_space()->Size() : 0);
  size_t new_lo_space_size =
      (heap_->new_lo_space() ? heap_->new_lo_space()->SizeOfObjects() : 0);
  current_.young_object_size = new_space_size + new_lo_space_size;
  current_.start_atomic_pause_time = time;
}
References v8::internal::CountTotalHolesSize(), current_, v8::internal::Heap::EmbedderAllocationCounter(), heap_, v8::internal::Heap::memory_allocator(), v8::internal::Heap::new_lo_space(), v8::internal::Heap::new_space(), v8::internal::Heap::NewSpaceAllocationCounter(), v8::internal::Heap::OldGenerationAllocationCounter(), SampleAllocation(), v8::internal::MemoryAllocator::Size(), v8::internal::Heap::SizeOfObjects(), v8::internal::LargeObjectSpace::SizeOfObjects(), v8::internal::GCTracer::Event::start_atomic_pause_time, v8::internal::GCTracer::Event::start_holes_size, v8::internal::GCTracer::Event::start_memory_size, v8::internal::GCTracer::Event::start_object_size, v8::internal::GCTracer::Event::start_time, v8::internal::time, and v8::internal::GCTracer::Event::young_object_size.
Referenced by v8::internal::Heap::PerformGarbageCollection().
StartObservablePause()
void v8::internal::GCTracer::StartObservablePause (base::TimeTicks time)
Definition at line 206 of file gc-tracer.cc.
                                                      {
  DCHECK(!IsInObservablePause());
  start_of_observable_pause_.emplace(time);
}
References v8::internal::DCHECK(), start_of_observable_pause_, and v8::internal::time.
Referenced by v8::internal::Heap::CollectGarbage().
StopAtomicPause()
void v8::internal::GCTracer::StopAtomicPause ()
Definition at line 443 of file gc-tracer.cc.
                               {
  DCHECK_EQ(Event::State::ATOMIC, current_.state);
  current_.state = Event::State::SWEEPING;
}
References v8::internal::GCTracer::Event::ATOMIC, current_, DCHECK_EQ, v8::internal::GCTracer::Event::state, and v8::internal::GCTracer::Event::SWEEPING.
Referenced by v8::internal::Heap::CollectGarbage().
StopCycle()
void v8::internal::GCTracer::StopCycle (GarbageCollector collector) [private]
Definition at line 465 of file gc-tracer.cc.
                                                   {
  DCHECK_EQ(Event::State::SWEEPING, current_.state);
  current_.state = Event::State::NOT_RUNNING;
  DCHECK(IsConsistentWithCollector(collector));
  FetchBackgroundCounters();
  if (Heap::IsYoungGenerationCollector(collector)) {
    ReportYoungCycleToRecorder();
    const v8::base::TimeDelta per_thread_wall_time =
        YoungGenerationWallTime(current_) / current_.concurrency_estimate;
    recorded_minor_gc_per_thread_.Push(BytesAndDuration(
        current_.survived_young_object_size, per_thread_wall_time));
    // If a young generation GC interrupted an unfinished full GC cycle, restore
    // the event corresponding to the full GC cycle.
    if (young_gc_during_full_gc_sweeping_) {
      // Sweeping for full GC could have occured during the young GC. Copy over
      // any sweeping scope values to the previous_ event. The full GC sweeping
      // scopes are never reported by young cycles.
      previous_.scopes[Scope::MC_SWEEP] += current_.scopes[Scope::MC_SWEEP];
      previous_.scopes[Scope::MC_BACKGROUND_SWEEPING] +=
          current_.scopes[Scope::MC_BACKGROUND_SWEEPING];
      std::swap(current_, previous_);
      young_gc_during_full_gc_sweeping_ = false;
    }
  } else {
    ReportFullCycleToRecorder();
    heap_->isolate()->counters()->mark_compact_reason()->AddSample(
        static_cast<int>(current_.gc_reason));
    if (v8_flags.trace_gc_freelists) {
      PrintIsolate(heap_->isolate(),
                   "FreeLists statistics before collection:\n");
      heap_->PrintFreeListsStats();
    }
  }
}
References v8::internal::GCTracer::Event::concurrency_estimate, v8::internal::Isolate::counters(), current_, v8::internal::DCHECK(), DCHECK_EQ, FetchBackgroundCounters(), v8::internal::GCTracer::Event::gc_reason, heap_, v8::internal::Heap::isolate(), v8::internal::Heap::IsYoungGenerationCollector(), v8::internal::GCTracer::Event::NOT_RUNNING, previous_, v8::internal::Heap::PrintFreeListsStats(), v8::internal::PrintIsolate(), v8::base::RingBuffer< T, _SIZE >::Push(), recorded_minor_gc_per_thread_, ReportFullCycleToRecorder(), ReportYoungCycleToRecorder(), v8::internal::GCTracer::Event::scopes, v8::internal::GCTracer::Event::state, v8::internal::GCTracer::Event::survived_young_object_size, v8::internal::GCTracer::Event::SWEEPING, v8::internal::v8_flags, young_gc_during_full_gc_sweeping_, and v8::internal::anonymous_namespace{gc-tracer.cc}::YoungGenerationWallTime().
Referenced by StopFullCycleIfFinished(), and StopYoungCycleIfFinished().
StopFullCycleIfFinished()
void v8::internal::GCTracer::StopFullCycleIfFinished ()
Definition at line 507 of file gc-tracer.cc.
                                       {
  if (current_.state != Event::State::SWEEPING) return;
  if (!notified_full_sweeping_completed_) return;
  if (heap_->cpp_heap() && !notified_full_cppgc_completed_) return;
  StopCycle(GarbageCollector::MARK_COMPACTOR);
  notified_full_sweeping_completed_ = false;
  notified_full_cppgc_completed_ = false;
  full_cppgc_completed_during_minor_gc_ = false;
}
References v8::internal::Heap::cpp_heap(), current_, full_cppgc_completed_during_minor_gc_, heap_, v8::internal::MARK_COMPACTOR, notified_full_cppgc_completed_, notified_full_sweeping_completed_, v8::internal::GCTracer::Event::state, StopCycle(), and v8::internal::GCTracer::Event::SWEEPING.
Referenced by v8::internal::Heap::CollectGarbage(), NotifyFullCppGCCompleted(), NotifyFullSweepingCompletedAndStopCycleIfFinished(), and StopYoungCycleIfFinished().
StopInSafepoint()
void v8::internal::GCTracer::StopInSafepoint (base::TimeTicks time)
Definition at line 323 of file gc-tracer.cc.
                                                 {
  current_.end_object_size = heap_->SizeOfObjects();
  current_.end_memory_size = heap_->memory_allocator()->Size();
  current_.end_holes_size = CountTotalHolesSize(heap_);
  current_.survived_young_object_size = heap_->SurvivedYoungObjectSize();
  current_.end_atomic_pause_time = time;
  // Do not include the GC pause for calculating the allocation rate. GC pause
  // with heap verification can decrease the allocation rate significantly.
  allocation_time_ = time;
  if (v8_flags.memory_balancer) {
    UpdateMemoryBalancerGCSpeed();
  }
}
References allocation_time_, v8::internal::CountTotalHolesSize(), current_, v8::internal::GCTracer::Event::end_atomic_pause_time, v8::internal::GCTracer::Event::end_holes_size, v8::internal::GCTracer::Event::end_memory_size, v8::internal::GCTracer::Event::end_object_size, heap_, v8::internal::Heap::memory_allocator(), v8::internal::MemoryAllocator::Size(), v8::internal::Heap::SizeOfObjects(), v8::internal::GCTracer::Event::survived_young_object_size, v8::internal::Heap::SurvivedYoungObjectSize(), v8::internal::time, UpdateMemoryBalancerGCSpeed(), and v8::internal::v8_flags.
Referenced by v8::internal::Heap::PerformGarbageCollection().
StopObservablePause()
void v8::internal::GCTracer::StopObservablePause (GarbageCollector collector, base::TimeTicks time)
Definition at line 339 of file gc-tracer.cc.
                                                       {
  DCHECK(IsConsistentWithCollector(collector));
  DCHECK(IsInObservablePause());
  start_of_observable_pause_.reset();
  // TODO(chromium:1154636): The end_time of the current event contains
  // currently the end time of the observable pause. This should be
  // reconsidered.
  current_.end_time = time;
  FetchBackgroundCounters();
  const base::TimeDelta duration = current_.end_time - current_.start_time;
  auto* long_task_stats = heap_->isolate()->GetCurrentLongTaskStats();
  const bool is_young = Heap::IsYoungGenerationCollector(collector);
  if (is_young) {
    recorded_minor_gc_atomic_pause_.Push(
        BytesAndDuration(current_.survived_young_object_size, duration));
    long_task_stats->gc_young_wall_clock_duration_us +=
        duration.InMicroseconds();
  } else {
    if (current_.type == Event::Type::INCREMENTAL_MARK_COMPACTOR) {
      RecordIncrementalMarkingSpeed(current_.incremental_marking_bytes,
                                    current_.incremental_marking_duration);
      recorded_incremental_mark_compacts_.Push(
          BytesAndDuration(current_.end_object_size, duration));
      for (int i = 0; i < Scope::NUMBER_OF_INCREMENTAL_SCOPES; i++) {
        current_.incremental_scopes[i] = incremental_scopes_[i];
        current_.scopes[i] = incremental_scopes_[i].duration;
      }
    } else {
      recorded_mark_compacts_.Push(
          BytesAndDuration(current_.end_object_size, duration));
      DCHECK_EQ(0u, current_.incremental_marking_bytes);
      DCHECK(current_.incremental_marking_duration.IsZero());
    }
    RecordGCSumCounters();
    combined_mark_compact_speed_cache_ = std::nullopt;
    long_task_stats->gc_full_atomic_wall_clock_duration_us +=
        duration.InMicroseconds();
    RecordMutatorUtilization(current_.end_time,
                             duration + current_.incremental_marking_duration);
  }
  heap_->UpdateTotalGCTime(duration);
  if (v8_flags.trace_gc_ignore_scavenger && is_young) return;
  if (v8_flags.trace_gc_nvp) {
    PrintNVP();
  } else {
    Print();
  }
  // Reset here because Print() still uses these scopes.
  if (current_.type == Event::Type::INCREMENTAL_MARK_COMPACTOR) {
    for (int i = 0; i < Scope::NUMBER_OF_INCREMENTAL_SCOPES; i++) {
      new (&incremental_scopes_[i]) IncrementalInfos;
    }
  }
  if (v8_flags.trace_gc) {
    heap_->PrintShortHeapStatistics();
  }
  if (V8_UNLIKELY(TracingFlags::gc.load(std::memory_order_relaxed) &
                  v8::tracing::TracingCategoryObserver::ENABLED_BY_TRACING)) {
    TRACE_GC_NOTE("V8.GC_HEAP_DUMP_STATISTICS");
    std::stringstream heap_stats;
    heap_->DumpJSONHeapStatistics(heap_stats);
    TRACE_EVENT_INSTANT1(TRACE_DISABLED_BY_DEFAULT("v8.gc"), "V8.GC_Heap_Stats",
                         TRACE_EVENT_SCOPE_THREAD, "stats",
                         TRACE_STR_COPY(heap_stats.str().c_str()));
  }
}
References combined_mark_compact_speed_cache_, current_, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Heap::DumpJSONHeapStatistics(), v8::internal::duration, v8::internal::GCTracer::IncrementalInfos::duration, v8::tracing::TracingCategoryObserver::ENABLED_BY_TRACING, v8::internal::GCTracer::Event::end_object_size, v8::internal::GCTracer::Event::end_time, FetchBackgroundCounters(), v8::internal::TracingFlags::gc, v8::internal::Isolate::GetCurrentLongTaskStats(), heap_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::GCTracer::Event::INCREMENTAL_MARK_COMPACTOR, v8::internal::GCTracer::Event::incremental_marking_bytes, v8::internal::GCTracer::Event::incremental_marking_duration, v8::internal::GCTracer::Event::incremental_scopes, incremental_scopes_, v8::internal::Heap::isolate(), v8::internal::Heap::IsYoungGenerationCollector(), v8::base::TimeDelta::IsZero(), v8::internal::GCTracer::Scope::NUMBER_OF_INCREMENTAL_SCOPES, Print(), PrintNVP(), v8::internal::Heap::PrintShortHeapStatistics(), v8::base::RingBuffer< T, _SIZE >::Push(), recorded_incremental_mark_compacts_, recorded_mark_compacts_, recorded_minor_gc_atomic_pause_, RecordGCSumCounters(), RecordIncrementalMarkingSpeed(), RecordMutatorUtilization(), v8::internal::GCTracer::Event::scopes, start_of_observable_pause_, v8::internal::GCTracer::Event::start_time, v8::internal::GCTracer::Event::survived_young_object_size, v8::internal::time, TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT_INSTANT1, TRACE_EVENT_SCOPE_THREAD, TRACE_GC_NOTE, TRACE_STR_COPY, v8::internal::GCTracer::Event::type, v8::internal::Heap::UpdateTotalGCTime(), v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::internal::Heap::CollectGarbage().
StopYoungCycleIfFinished()
void v8::internal::GCTracer::StopYoungCycleIfFinished ()
Definition at line 517 of file gc-tracer.cc.
                                        {
  DCHECK(Event::IsYoungGenerationEvent(current_.type));
  if (current_.state != Event::State::SWEEPING) return;
  if (!notified_young_sweeping_completed_) return;
  // Check if young cppgc was scheduled but hasn't completed yet.
  if (heap_->cpp_heap() && notified_young_cppgc_running_ &&
      !notified_young_cppgc_completed_)
    return;
  bool was_young_gc_during_full_gc_sweeping_ =
      young_gc_during_full_gc_sweeping_;
  StopCycle(current_.type == Event::Type::SCAVENGER
                ? GarbageCollector::SCAVENGER
                : GarbageCollector::MINOR_MARK_SWEEPER);
  notified_young_sweeping_completed_ = false;
  notified_young_cppgc_running_ = false;
  notified_young_cppgc_completed_ = false;
  if (was_young_gc_during_full_gc_sweeping_) {
    // Check if the full gc cycle is ready to be stopped.
    StopFullCycleIfFinished();
  }
}
References v8::internal::Heap::cpp_heap(), current_, v8::internal::DCHECK(), heap_, v8::internal::GCTracer::Event::IsYoungGenerationEvent(), v8::internal::MINOR_MARK_SWEEPER, notified_young_cppgc_completed_, notified_young_cppgc_running_, notified_young_sweeping_completed_, v8::internal::SCAVENGER, v8::internal::GCTracer::Event::SCAVENGER, v8::internal::GCTracer::Event::state, StopCycle(), StopFullCycleIfFinished(), v8::internal::GCTracer::Event::SWEEPING, v8::internal::GCTracer::Event::type, and young_gc_during_full_gc_sweeping_.
Referenced by v8::internal::Heap::CollectGarbage(), NotifyYoungCppGCCompleted(), and NotifyYoungSweepingCompletedAndStopCycleIfFinished().
SurvivalEventsRecorded()
bool v8::internal::GCTracer::SurvivalEventsRecorded () const
Definition at line 1421 of file gc-tracer.cc.
                                            {
  return !recorded_survival_ratios_.Empty();
}
References v8::base::RingBuffer< T, _SIZE >::Empty(), and recorded_survival_ratios_.
UpdateCurrentEvent()
void v8::internal::GCTracer::UpdateCurrentEvent (GarbageCollectionReason gc_reason, const char * collector_reason)
Definition at line 211 of file gc-tracer.cc.
                                                                {
  // For incremental marking, the event has already been created and we just
  // need to update a few fields.
  DCHECK(current_.type == Event::Type::INCREMENTAL_MARK_COMPACTOR ||
         current_.type == Event::Type::INCREMENTAL_MINOR_MARK_SWEEPER);
  DCHECK_EQ(Event::State::ATOMIC, current_.state);
  DCHECK(IsInObservablePause());
  current_.gc_reason = gc_reason;
  current_.collector_reason = collector_reason;
  // TODO(chromium:1154636): The start_time of the current event contains
  // currently the start time of the observable pause. This should be
  // reconsidered.
  current_.start_time = start_of_observable_pause_.value();
  current_.reduce_memory = heap_->ShouldReduceMemory();
}
References v8::internal::GCTracer::Event::ATOMIC, v8::internal::GCTracer::Event::collector_reason, current_, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::GCTracer::Event::gc_reason, heap_, v8::internal::GCTracer::Event::INCREMENTAL_MARK_COMPACTOR, v8::internal::GCTracer::Event::INCREMENTAL_MINOR_MARK_SWEEPER, v8::internal::GCTracer::Event::reduce_memory, v8::internal::Heap::ShouldReduceMemory(), start_of_observable_pause_, v8::internal::GCTracer::Event::start_time, v8::internal::GCTracer::Event::state, and v8::internal::GCTracer::Event::type.
Referenced by v8::internal::Heap::PerformGarbageCollection().
UpdateCurrentEventPriority()
void v8::internal::GCTracer::UpdateCurrentEventPriority (GCTracer::Priority priority)
Definition at line 1955 of file gc-tracer.cc.
                                                                   {
  // If the priority is changed, reset the priority field to denote a mixed
  // priority cycle.
  if (!current_.priority.has_value() || (current_.priority == priority)) {
    return;
  }
  current_.priority = std::nullopt;
}
References current_, and v8::internal::GCTracer::Event::priority.
Referenced by v8::internal::Isolate::SetPriority().
UpdateMemoryBalancerGCSpeed()
void v8::internal::GCTracer::UpdateMemoryBalancerGCSpeed ()
Definition at line 417 of file gc-tracer.cc.
                                           {
  DCHECK(v8_flags.memory_balancer);
  size_t major_gc_bytes = current_.start_object_size;
  const base::TimeDelta atomic_pause_duration =
      current_.end_atomic_pause_time - current_.start_atomic_pause_time;
  const base::TimeDelta blocked_time_taken =
      atomic_pause_duration + current_.incremental_marking_duration;
  base::TimeDelta concurrent_gc_time;
  {
    base::MutexGuard guard(&background_scopes_mutex_);
    concurrent_gc_time =
        background_scopes_[Scope::MC_BACKGROUND_EVACUATE_COPY] +
        background_scopes_[Scope::MC_BACKGROUND_EVACUATE_UPDATE_POINTERS] +
        background_scopes_[Scope::MC_BACKGROUND_MARKING] +
        background_scopes_[Scope::MC_BACKGROUND_SWEEPING];
  }
  const base::TimeDelta major_gc_duration =
      blocked_time_taken + concurrent_gc_time;
  const base::TimeDelta major_allocation_duration =
      (current_.end_atomic_pause_time - previous_mark_compact_end_time_) -
      blocked_time_taken;
  CHECK_GE(major_allocation_duration, base::TimeDelta());
  heap_->mb_->UpdateGCSpeed(major_gc_bytes, major_gc_duration);
}
References background_scopes_, background_scopes_mutex_, CHECK_GE, current_, v8::internal::DCHECK(), v8::internal::GCTracer::Event::end_atomic_pause_time, heap_, v8::internal::GCTracer::Event::incremental_marking_duration, v8::internal::Heap::mb_, previous_mark_compact_end_time_, v8::internal::GCTracer::Event::start_atomic_pause_time, v8::internal::GCTracer::Event::start_object_size, and v8::internal::v8_flags.
Referenced by StopInSafepoint().
YoungGenerationSpeedInBytesPerMillisecond()
std::optional< double > v8::internal::GCTracer::YoungGenerationSpeedInBytesPerMillisecond (YoungGenerationSpeedMode mode) const
Definition at line 1342 of file gc-tracer.cc.
                                         {
  switch (mode) {
    case YoungGenerationSpeedMode::kUpToAndIncludingAtomicPause:
      return BoundedAverageSpeed(recorded_minor_gc_per_thread_);
    case YoungGenerationSpeedMode::kOnlyAtomicPause:
      return BoundedAverageSpeed(recorded_minor_gc_atomic_pause_);
  }
  UNREACHABLE();
}
References v8::internal::anonymous_namespace{gc-tracer.cc}::BoundedAverageSpeed(), v8::internal::kOnlyAtomicPause, v8::internal::kUpToAndIncludingAtomicPause, mode(), recorded_minor_gc_atomic_pause_, recorded_minor_gc_per_thread_, and v8::internal::UNREACHABLE().
Referenced by PrintNVP().
Member Data Documentation
allocation_time_
base::TimeTicks v8::internal::GCTracer::allocation_time_ [private]
Definition at line 542 of file gc-tracer.h.
Referenced by SampleAllocation(), and StopInSafepoint().
average_mark_compact_duration_
double v8::internal::GCTracer::average_mark_compact_duration_ = 0.0 [private]
Definition at line 551 of file gc-tracer.h.
Referenced by AverageMarkCompactMutatorUtilization(), and RecordMutatorUtilization().
average_mutator_duration_
double v8::internal::GCTracer::average_mutator_duration_ = 0.0 [private]
Definition at line 550 of file gc-tracer.h.
Referenced by AverageMarkCompactMutatorUtilization(), and RecordMutatorUtilization().
average_time_to_incremental_marking_task_
std::optional<base::TimeDelta> v8::internal::GCTracer::average_time_to_incremental_marking_task_ [private]
Definition at line 530 of file gc-tracer.h.
Referenced by AverageTimeToIncrementalMarkingTask(), and RecordTimeToIncrementalMarkingTask().
background_scopes_
base::TimeDelta v8::internal::GCTracer::background_scopes_[Scope::NUMBER_OF_SCOPES] [private]
Definition at line 606 of file gc-tracer.h.
Referenced by AddScopeSample(), FetchBackgroundCounters(), RecordGCSumCounters(), and UpdateMemoryBalancerGCSpeed().
background_scopes_mutex_
base::Mutex v8::internal::GCTracer::background_scopes_mutex_ [mutable], [private]
Definition at line 605 of file gc-tracer.h.
Referenced by AddScopeSample(), FetchBackgroundCounters(), PrintNVP(), RecordGCSumCounters(), and UpdateMemoryBalancerGCSpeed().
code_flushing_increase_s_
uint16_t v8::internal::GCTracer::code_flushing_increase_s_ = 0 [private]
Definition at line 535 of file gc-tracer.h.
Referenced by CodeFlushingIncrease(), and NotifyMarkingStart().
combined_mark_compact_speed_cache_
std::optional<double> v8::internal::GCTracer::combined_mark_compact_speed_cache_ [private]
Definition at line 547 of file gc-tracer.h.
Referenced by OldGenerationSpeedInBytesPerMillisecond(), and StopObservablePause().
const
void v8::internal::GCTracer::const [private]
Definition at line 501 of file gc-tracer.h.
current_
Event v8::internal::GCTracer::current_ [private]
Definition at line 515 of file gc-tracer.h.
Referenced by AddIncrementalMarkingStep(), AddScopeSample(), current_scope(), FetchBackgroundCounters(), GCTracer(), GetCurrentCollector(), IncrementalMarkingSpeedInBytesPerMillisecond(), NotifyFullCppGCCompleted(), NotifyFullSweepingCompletedAndStopCycleIfFinished(), NotifyIncrementalMarkingStart(), NotifyYoungSweepingCompleted(), NotifyYoungSweepingCompletedAndStopCycleIfFinished(), Print(), PrintNVP(), RecordGCPhasesHistograms(), RecordGCSumCounters(), RecordIncrementalMarkingSpeed(), ReportFullCycleToRecorder(), ReportIncrementalMarkingStepToRecorder(), ReportYoungCycleToRecorder(), SampleConcurrencyEsimate(), StartAtomicPause(), StartCycle(), StartInSafepoint(), StopAtomicPause(), StopCycle(), StopFullCycleIfFinished(), StopInSafepoint(), StopObservablePause(), StopYoungCycleIfFinished(), UpdateCurrentEvent(), UpdateCurrentEventPriority(), and UpdateMemoryBalancerGCSpeed().
current_mark_compact_mutator_utilization_
double v8::internal::GCTracer::current_mark_compact_mutator_utilization_ = 1.0 [private]
Definition at line 552 of file gc-tracer.h.
Referenced by CurrentMarkCompactMutatorUtilization(), and RecordMutatorUtilization().
embedder_allocation_counter_bytes_
size_t v8::internal::GCTracer::embedder_allocation_counter_bytes_ = 0 [private]
Definition at line 545 of file gc-tracer.h.
Referenced by SampleAllocation().
embedder_generation_allocations_
SmoothedBytesAndDuration v8::internal::GCTracer::embedder_generation_allocations_ [private]
Initial value:
{
      kSmoothedAllocationSpeedDecayRate}
Definition at line 572 of file gc-tracer.h.
Referenced by EmbedderAllocationThroughputInBytesPerMillisecond(), and SampleAllocation().
epoch_full_
CollectionEpoch v8::internal::GCTracer::epoch_full_ = 0 [private]
Definition at line 525 of file gc-tracer.h.
Referenced by CurrentEpoch(), and StartCycle().
epoch_young_
CollectionEpoch v8::internal::GCTracer::epoch_young_ = 0 [private]
Definition at line 524 of file gc-tracer.h.
Referenced by CurrentEpoch(), and StartCycle().
full_cppgc_completed_during_minor_gc_
bool v8::internal::GCTracer::full_cppgc_completed_during_minor_gc_ = false [private]
Definition at line 585 of file gc-tracer.h.
Referenced by NotifyFullCppGCCompleted(), NotifyFullSweepingCompletedAndStopCycleIfFinished(), and StopFullCycleIfFinished().
heap_
Heap* v8::internal::GCTracer::heap_ [private]
Definition at line 511 of file gc-tracer.h.
Referenced by NotifyFullCppGCCompleted(), NotifyFullSweepingCompletedAndStopCycleIfFinished(), NotifyMarkingStart(), NotifyYoungCppGCCompleted(), Print(), PrintNVP(), RecordGCPhasesHistograms(), RecordGCSizeCounters(), ReportFullCycleToRecorder(), ReportIncrementalMarkingStepToRecorder(), ReportIncrementalSweepingStepToRecorder(), ReportYoungCycleToRecorder(), ResetForTesting(), SampleAllocation(), v8::internal::GCTracer::Scope::Scope(), StartCycle(), StartInSafepoint(), StopCycle(), StopFullCycleIfFinished(), StopInSafepoint(), StopObservablePause(), StopYoungCycleIfFinished(), UpdateCurrentEvent(), and UpdateMemoryBalancerGCSpeed().
incremental_mark_batched_events_
v8::metrics::GarbageCollectionFullMainThreadBatchedIncrementalMark v8::internal::GCTracer::incremental_mark_batched_events_ [private]
Definition at line 601 of file gc-tracer.h.
Referenced by ReportFullCycleToRecorder(), and ReportIncrementalMarkingStepToRecorder().
incremental_scopes_
IncrementalInfos v8::internal::GCTracer::incremental_scopes_[Scope::NUMBER_OF_INCREMENTAL_SCOPES] [private]
Definition at line 539 of file gc-tracer.h.
Referenced by AddScopeSample(), incremental_scope(), RecordGCSumCounters(), and StopObservablePause().
incremental_sweep_batched_events_
v8::metrics::GarbageCollectionFullMainThreadBatchedIncrementalSweep v8::internal::GCTracer::incremental_sweep_batched_events_ [private]
Definition at line 603 of file gc-tracer.h.
Referenced by ReportFullCycleToRecorder(), and ReportIncrementalSweepingStepToRecorder().
kConservativeSpeedInBytesPerMillisecond
constexpr double v8::internal::GCTracer::kConservativeSpeedInBytesPerMillisecond = 128 * KB [static], [constexpr]
Definition at line 278 of file gc-tracer.h.
Referenced by IncrementalMarkingSpeedInBytesPerMillisecond().
kSmoothedAllocationSpeedDecayRate
constexpr base::TimeDelta v8::internal::GCTracer::kSmoothedAllocationSpeedDecayRate [static], [constexpr], [private]
Initial value:
=
      v8::base::TimeDelta::FromMilliseconds(100)
Definition at line 565 of file gc-tracer.h.
kThroughputTimeFrame
constexpr base::TimeDelta v8::internal::GCTracer::kThroughputTimeFrame [static], [constexpr]
Initial value:
=
      base::TimeDelta::FromSeconds(5)
Definition at line 276 of file gc-tracer.h.
last_marking_start_time_for_code_flushing_
std::optional<base::TimeTicks> v8::internal::GCTracer::last_marking_start_time_for_code_flushing_ [private]
Definition at line 534 of file gc-tracer.h.
Referenced by NotifyMarkingStart().
new_generation_allocations_
SmoothedBytesAndDuration v8::internal::GCTracer::new_generation_allocations_ [private]
Initial value:
{
      kSmoothedAllocationSpeedDecayRate}
Definition at line 568 of file gc-tracer.h.
Referenced by NewSpaceAllocationThroughputInBytesPerMillisecond(), and SampleAllocation().
new_space_allocation_counter_bytes_
size_t v8::internal::GCTracer::new_space_allocation_counter_bytes_ = 0 [private]
Definition at line 543 of file gc-tracer.h.
Referenced by SampleAllocation().
notified_full_cppgc_completed_
bool v8::internal::GCTracer::notified_full_cppgc_completed_ = false [private]
Definition at line 584 of file gc-tracer.h.
Referenced by NotifyFullCppGCCompleted(), NotifyFullSweepingCompletedAndStopCycleIfFinished(), and StopFullCycleIfFinished().
notified_full_sweeping_completed_
bool v8::internal::GCTracer::notified_full_sweeping_completed_ = false [private]
Definition at line 583 of file gc-tracer.h.
Referenced by NotifyFullSweepingCompletedAndStopCycleIfFinished(), and StopFullCycleIfFinished().
notified_young_cppgc_completed_
bool v8::internal::GCTracer::notified_young_cppgc_completed_ = false [private]
Definition at line 590 of file gc-tracer.h.
Referenced by NotifyYoungCppGCCompleted(), and StopYoungCycleIfFinished().
notified_young_cppgc_running_
bool v8::internal::GCTracer::notified_young_cppgc_running_ = false [private]
Definition at line 593 of file gc-tracer.h.
Referenced by NotifyYoungCppGCCompleted(), NotifyYoungCppGCRunning(), and StopYoungCycleIfFinished().
notified_young_sweeping_completed_
bool v8::internal::GCTracer::notified_young_sweeping_completed_ = false [private]
Definition at line 587 of file gc-tracer.h.
Referenced by NotifyYoungSweepingCompleted(), and StopYoungCycleIfFinished().
old_generation_allocation_counter_bytes_
size_t v8::internal::GCTracer::old_generation_allocation_counter_bytes_ = 0 [private]
Definition at line 544 of file gc-tracer.h.
Referenced by SampleAllocation().
old_generation_allocations_
SmoothedBytesAndDuration v8::internal::GCTracer::old_generation_allocations_ [private]
Initial value:
{
      kSmoothedAllocationSpeedDecayRate}
Definition at line 570 of file gc-tracer.h.
Referenced by OldGenerationAllocationThroughputInBytesPerMillisecond(), and SampleAllocation().
previous_
Event v8::internal::GCTracer::previous_ [private]
Definition at line 518 of file gc-tracer.h.
Referenced by PrintNVP(), StartCycle(), and StopCycle().
previous_mark_compact_end_time_
base::TimeTicks v8::internal::GCTracer::previous_mark_compact_end_time_ [private]
Definition at line 556 of file gc-tracer.h.
Referenced by GCTracer(), RecordMutatorUtilization(), and UpdateMemoryBalancerGCSpeed().
recorded_compactions_
BytesAndDurationBuffer v8::internal::GCTracer::recorded_compactions_ [private]
Definition at line 559 of file gc-tracer.h.
Referenced by AddCompactionEvent(), and CompactionSpeedInBytesPerMillisecond().
recorded_embedder_marking_
BytesAndDurationBuffer v8::internal::GCTracer::recorded_embedder_marking_ [private]
Definition at line 563 of file gc-tracer.h.
Referenced by EmbedderSpeedInBytesPerMillisecond(), and RecordEmbedderMarkingSpeed().
recorded_incremental_mark_compacts_
BytesAndDurationBuffer v8::internal::GCTracer::recorded_incremental_mark_compacts_ [private]
Definition at line 560 of file gc-tracer.h.
Referenced by FinalIncrementalMarkCompactSpeedInBytesPerMillisecond(), and StopObservablePause().
recorded_major_incremental_marking_speed_
double v8::internal::GCTracer::recorded_major_incremental_marking_speed_ = 0.0 [private]
Definition at line 528 of file gc-tracer.h.
Referenced by IncrementalMarkingSpeedInBytesPerMillisecond(), and RecordIncrementalMarkingSpeed().
recorded_major_totals_
BytesAndDurationBuffer v8::internal::GCTracer::recorded_major_totals_ [private]
Definition at line 562 of file gc-tracer.h.
Referenced by OldGenerationSpeedInBytesPerMillisecond(), and RecordGCSumCounters().
recorded_mark_compacts_
BytesAndDurationBuffer v8::internal::GCTracer::recorded_mark_compacts_ [private]
Definition at line 561 of file gc-tracer.h.
Referenced by MarkCompactSpeedInBytesPerMillisecond(), and StopObservablePause().
recorded_minor_gc_atomic_pause_
BytesAndDurationBuffer v8::internal::GCTracer::recorded_minor_gc_atomic_pause_ [private]
Definition at line 578 of file gc-tracer.h.
Referenced by StopObservablePause(), and YoungGenerationSpeedInBytesPerMillisecond().
recorded_minor_gc_per_thread_
BytesAndDurationBuffer v8::internal::GCTracer::recorded_minor_gc_per_thread_ [private]
Definition at line 577 of file gc-tracer.h.
Referenced by StopCycle(), and YoungGenerationSpeedInBytesPerMillisecond().
recorded_survival_ratios_
base::RingBuffer<double> v8::internal::GCTracer::recorded_survival_ratios_ [private]
Definition at line 579 of file gc-tracer.h.
Referenced by AddSurvivalRatio(), AverageSurvivalRatio(), ResetSurvivalEvents(), and SurvivalEventsRecorded().
start_of_observable_pause_
std::optional<base::TimeTicks> v8::internal::GCTracer::start_of_observable_pause_ [private]
Definition at line 521 of file gc-tracer.h.
Referenced by StartCycle(), StartObservablePause(), StopObservablePause(), and UpdateCurrentEvent().
total_duration_since_last_mark_compact_
base::TimeDelta v8::internal::GCTracer::total_duration_since_last_mark_compact_ [private]
Definition at line 557 of file gc-tracer.h.
Referenced by RecordMutatorUtilization(), and ReportFullCycleToRecorder().
young_gc_during_full_gc_sweeping_
bool v8::internal::GCTracer::young_gc_during_full_gc_sweeping_ = false [private]
Definition at line 598 of file gc-tracer.h.
Referenced by NotifyFullCppGCCompleted(), NotifyFullSweepingCompletedAndStopCycleIfFinished(), Print(), PrintNVP(), StartCycle(), StopCycle(), and StopYoungCycleIfFinished().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/gc-tracer.h
/mnt/V8SourceCode/src/heap/gc-tracer-inl.h
/mnt/V8SourceCode/src/heap/gc-tracer.cc