v8::internal::AsmJs Class Reference
#include <asm-js.h>
Static Public Member Functions
static std::unique_ptr< UnoptimizedCompilationJob > NewCompilationJob (ParseInfo *parse_info, FunctionLiteral *literal, AccountingAllocator *allocator)
static MaybeDirectHandle< Object > InstantiateAsmWasm (Isolate *isolate, DirectHandle< SharedFunctionInfo >, DirectHandle< AsmWasmData > wasm_data, DirectHandle< JSReceiver > stdlib, DirectHandle< JSReceiver > foreign, DirectHandle< JSArrayBuffer > memory)
Static Public Attributes
static const char *const kSingleFunctionName = `__single_function__`
Detailed Description
Definition at line 26 of file asm-js.h.
Member Function Documentation
InstantiateAsmWasm()
MaybeDirectHandle< Object > v8::internal::AsmJs::InstantiateAsmWasm (Isolate * isolate, DirectHandle< SharedFunctionInfo > shared, DirectHandle< AsmWasmData > wasm_data, DirectHandle< JSReceiver > stdlib, DirectHandle< JSReceiver > foreign, DirectHandle< JSArrayBuffer > memory) [static]
Definition at line 335 of file asm-js.cc.
                                                                          {
  base::ElapsedTimer instantiate_timer;
  instantiate_timer.Start();
  DirectHandle<HeapNumber> uses_bitset(wasm_data->uses_bitset(), isolate);
  Handle<Script> script(Cast<Script>(shared->script()), isolate);
  auto* wasm_engine = wasm::GetWasmEngine();
  // Allocate the WasmModuleObject.
  DirectHandle<WasmModuleObject> module =
      wasm_engine->FinalizeTranslatedAsmJs(isolate, wasm_data, script);
  // TODO(asmjs): The position currently points to the module definition
  // but should instead point to the instantiation site (more intuitive).
  int position = shared->StartPosition();
  // Check that the module is not instantiated as a generator or async function.
  if (IsResumableFunction(shared->scope_info()->function_kind())) {
    ReportInstantiationFailure(script, position,
                               "Cannot be instantiated as resumable function");
    return {};
  }
  // Check that all used stdlib members are valid.
  bool stdlib_use_of_typed_array_present = false;
  wasm::AsmJsParser::StdlibSet stdlib_uses =
      wasm::AsmJsParser::StdlibSet::FromIntegral(uses_bitset->value_as_bits());
  if (!stdlib_uses.empty()) { // No checking needed if no uses.
    if (stdlib.is_null()) {
      ReportInstantiationFailure(script, position, "Requires standard library");
      return {};
    }
    if (!AreStdlibMembersValid(isolate, stdlib, stdlib_uses,
                               &stdlib_use_of_typed_array_present)) {
      ReportInstantiationFailure(script, position, "Unexpected stdlib member");
      return {};
    }
  }
  // Check that a valid heap buffer is provided if required.
  if (stdlib_use_of_typed_array_present) {
    if (memory.is_null()) {
      ReportInstantiationFailure(script, position, "Requires heap buffer");
      return {};
    }
    // AsmJs memory must be an ArrayBuffer.
    if (memory->is_shared()) {
      ReportInstantiationFailure(script, position,
                                 "Invalid heap type: SharedArrayBuffer");
      return {};
    }
    // We don't allow resizable ArrayBuffers because resizable ArrayBuffers may
    // shrink, and then asm.js does out of bounds memory accesses.
    if (memory->is_resizable_by_js()) {
      ReportInstantiationFailure(script, position,
                                 "Invalid heap type: resizable ArrayBuffer");
      return {};
    }
    // We don't allow WebAssembly.Memory, because WebAssembly.Memory.grow()
    // detaches the ArrayBuffer, and that would invalidate the asm.js module.
    if (memory->GetBackingStore() &&
        memory->GetBackingStore()->is_wasm_memory()) {
      ReportInstantiationFailure(script, position,
                                 "Invalid heap type: WebAssembly.Memory");
      return {};
    }
    size_t size = memory->byte_length();
    // Check the asm.js heap size against the valid limits.
    if (!IsValidAsmjsMemorySize(size)) {
      ReportInstantiationFailure(script, position, "Invalid heap size");
      return {};
    }
    // Mark the buffer as undetachable. This implies that the buffer cannot be
    // postMessage()'d, as that detaches the buffer.
    memory->set_is_detachable(false);
  } else {
    memory = Handle<JSArrayBuffer>::null();
  }
  wasm::ErrorThrower thrower(isolate, "AsmJs::Instantiate");
  MaybeDirectHandle<WasmInstanceObject> maybe_instance =
      wasm_engine->SyncInstantiate(isolate, &thrower, module, foreign, memory);
  if (maybe_instance.is_null()) {
    // Clear a possible stack overflow from function entry that would have
    // bypassed the {ErrorThrower}. Be careful not to clear a termination
    // exception.
    if (isolate->is_execution_terminating()) return {};
    if (isolate->has_exception()) isolate->clear_exception();
    if (thrower.error()) {
      base::ScopedVector<char> error_reason(100);
      SNPrintF(error_reason, "Internal wasm failure: %s", thrower.error_msg());
      ReportInstantiationFailure(script, position, error_reason.begin());
    } else {
      ReportInstantiationFailure(script, position, "Internal wasm failure");
    }
    thrower.Reset(); // Ensure exceptions do not propagate.
    return {};
  }
  DCHECK(!thrower.error());
  DirectHandle<WasmInstanceObject> instance = maybe_instance.ToHandleChecked();
  ReportInstantiationSuccess(script, position,
                             instantiate_timer.Elapsed().InMillisecondsF());
  DirectHandle<Name> single_function_name(
      isolate->factory()->InternalizeUtf8String(AsmJs::kSingleFunctionName));
  MaybeDirectHandle<Object> single_function =
      Object::GetProperty(isolate, instance, single_function_name);
  if (!single_function.is_null() &&
      !IsUndefined(*single_function.ToHandleChecked(), isolate)) {
    return single_function;
  }
  // Here we rely on the fact that the exports object is eagerly created.
  // The following check is a weak indicator for that. If this ever changes,
  // then we'll have to call the "exports" getter, and be careful about
  // handling possible stack overflow exceptions.
  DCHECK(IsJSObject(instance->exports_object()));
  return direct_handle(instance->exports_object(), isolate);
}
References v8::internal::anonymous_namespace{asm-js.cc}::AreStdlibMembersValid(), v8::base::Vector< T >::begin(), v8::internal::Isolate::clear_exception(), v8::internal::DCHECK(), v8::internal::direct_handle(), v8::base::ElapsedTimer::Elapsed(), v8::base::EnumSet< E, T >::empty(), v8::internal::wasm::ErrorThrower::error(), v8::internal::wasm::ErrorThrower::error_msg(), v8::internal::Isolate::factory(), v8::base::EnumSet< StandardMember, uint64_t >::FromIntegral(), v8::internal::Object::GetProperty(), v8::internal::wasm::GetWasmEngine(), v8::internal::Isolate::has_exception(), v8::base::TimeDelta::InMillisecondsF(), v8::internal::Factory::InternalizeUtf8String(), v8::internal::Isolate::is_execution_terminating(), v8::internal::DirectHandle< T >::is_null(), v8::internal::MaybeDirectHandle< T >::is_null(), v8::internal::IsResumableFunction(), v8::internal::anonymous_namespace{asm-js.cc}::IsValidAsmjsMemorySize(), kSingleFunctionName, v8::internal::Handle< T >::null(), v8::internal::anonymous_namespace{asm-js.cc}::ReportInstantiationFailure(), v8::internal::anonymous_namespace{asm-js.cc}::ReportInstantiationSuccess(), v8::internal::wasm::ErrorThrower::Reset(), v8::internal::script, size(), v8::base::SNPrintF(), v8::base::ElapsedTimer::Start(), and v8::internal::MaybeDirectHandle< T >::ToHandleChecked().
NewCompilationJob()
std::unique_ptr< UnoptimizedCompilationJob > v8::internal::AsmJs::NewCompilationJob (ParseInfo * parse_info, FunctionLiteral * literal, AccountingAllocator * allocator) [static]
Definition at line 305 of file asm-js.cc.
                                    {
  return std::make_unique<AsmJsCompilationJob>(parse_info, literal, allocator);
}
Referenced by v8::internal::anonymous_namespace{compiler.cc}::ExecuteSingleUnoptimizedCompilationJob().
Member Data Documentation
kSingleFunctionName
const char *const v8::internal::AsmJs::kSingleFunctionName = `__single_function__` [static]
Definition at line 38 of file asm-js.h.
Referenced by InstantiateAsmWasm(), v8::internal::wasm::InstanceBuilder::ProcessExports(), and v8::internal::wasm::AsmJsParser::ValidateExport().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/asmjs/asm-js.h
/mnt/V8SourceCode/src/asmjs/asm-js.cc