v8::internal::interpreter::BytecodeOperands Class Reference
#include <bytecode-operands.h>
Static Public Member Functions
static constexpr int OperandScaleAsIndex (OperandScale operand_scale)
static constexpr bool ReadsAccumulator (ImplicitRegisterUse implicit_register_use)
static constexpr bool WritesAccumulator (ImplicitRegisterUse implicit_register_use)
static constexpr bool ClobbersAccumulator (ImplicitRegisterUse implicit_register_use)
static constexpr bool WritesOrClobbersAccumulator (ImplicitRegisterUse implicit_register_use)
static constexpr bool WritesImplicitRegister (ImplicitRegisterUse implicit_register_use)
static constexpr bool IsScalableSignedByte (OperandType operand_type)
static constexpr bool IsScalableUnsignedByte (OperandType operand_type)
Static Public Attributes
static const int kOperandTypeCount = static_cast<int>(OperandType::kLast) + 1
static const int kOperandScaleCount
Detailed Description
Definition at line 146 of file bytecode-operands.h.
Member Function Documentation
ClobbersAccumulator()
static constexpr bool v8::internal::interpreter::BytecodeOperands::ClobbersAccumulator (ImplicitRegisterUse implicit_register_use) [inline], [static], [constexpr]
Definition at line 195 of file bytecode-operands.h.
                                                 {
    return (implicit_register_use & ImplicitRegisterUse::kClobberAccumulator) ==
           ImplicitRegisterUse::kClobberAccumulator;
  }
References v8::internal::interpreter::kClobberAccumulator.
Referenced by v8::internal::interpreter::Bytecodes::ClobbersAccumulator(), and v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateInLiveness().
IsScalableSignedByte()
static constexpr bool v8::internal::interpreter::BytecodeOperands::IsScalableSignedByte (OperandType operand_type) [inline], [static], [constexpr]
Definition at line 220 of file bytecode-operands.h.
                                                                       {
    return base::IsInRange(operand_type, OperandType::kImm,
                           OperandType::kRegInOut);
  }
Referenced by v8::internal::interpreter::BytecodeNode::ScaleForOperand().
IsScalableUnsignedByte()
static constexpr bool v8::internal::interpreter::BytecodeOperands::IsScalableUnsignedByte (OperandType operand_type) [inline], [static], [constexpr]
Definition at line 226 of file bytecode-operands.h.
                                                                         {
    return base::IsInRange(operand_type, OperandType::kIdx,
                           OperandType::kRegCount);
  }
Referenced by v8::internal::interpreter::BytecodeNode::ScaleForOperand().
OperandScaleAsIndex()
static constexpr int v8::internal::interpreter::BytecodeOperands::OperandScaleAsIndex (OperandScale operand_scale) [inline], [static], [constexpr]
Definition at line 157 of file bytecode-operands.h.
                                                                       {
#ifdef DEBUG
    int result = static_cast<int>(operand_scale) >> 1;
    switch (operand_scale) {
      case OperandScale::kSingle:
        DCHECK_EQ(0, result);
        break;
      case OperandScale::kDouble:
        DCHECK_EQ(1, result);
        break;
      case OperandScale::kQuadruple:
        DCHECK_EQ(2, result);
        break;
      default:
        UNREACHABLE();
    }
#endif
    return static_cast<int>(operand_scale) >> 1;
  }
References DCHECK_EQ, v8::base::internal::result, and v8::internal::UNREACHABLE().
Referenced by v8::internal::interpreter::Interpreter::GetDispatchTableIndex().
ReadsAccumulator()
static constexpr bool v8::internal::interpreter::BytecodeOperands::ReadsAccumulator (ImplicitRegisterUse implicit_register_use) [inline], [static], [constexpr]
Definition at line 179 of file bytecode-operands.h.
                                                 {
    return (implicit_register_use & ImplicitRegisterUse::kReadAccumulator) ==
           ImplicitRegisterUse::kReadAccumulator;
  }
References v8::internal::interpreter::kReadAccumulator.
Referenced by v8::internal::interpreter::BytecodeRegisterOptimizer::PrepareForBytecode(), v8::internal::interpreter::Bytecodes::ReadsAccumulator(), and v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateInLiveness().
WritesAccumulator()
static constexpr bool v8::internal::interpreter::BytecodeOperands::WritesAccumulator (ImplicitRegisterUse implicit_register_use) [inline], [static], [constexpr]
Definition at line 187 of file bytecode-operands.h.
                                                 {
    return (implicit_register_use & ImplicitRegisterUse::kWriteAccumulator) ==
           ImplicitRegisterUse::kWriteAccumulator;
  }
References v8::internal::interpreter::kWriteAccumulator.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::GetResultLocationAndSizeForBytecode(), v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateInLiveness(), and v8::internal::interpreter::Bytecodes::WritesAccumulator().
WritesImplicitRegister()
static constexpr bool v8::internal::interpreter::BytecodeOperands::WritesImplicitRegister (ImplicitRegisterUse implicit_register_use) [inline], [static], [constexpr]
Definition at line 213 of file bytecode-operands.h.
                                                 {
    return (implicit_register_use & ImplicitRegisterUse::kWriteShortStar) ==
           ImplicitRegisterUse::kWriteShortStar;
  }
References v8::internal::interpreter::kWriteShortStar.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::GetResultLocationAndSizeForBytecode(), v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateInLiveness(), and v8::internal::interpreter::Bytecodes::WritesImplicitRegister().
WritesOrClobbersAccumulator()
static constexpr bool v8::internal::interpreter::BytecodeOperands::WritesOrClobbersAccumulator (ImplicitRegisterUse implicit_register_use) [inline], [static], [constexpr]
Definition at line 203 of file bytecode-operands.h.
                                                 {
    return (implicit_register_use &
            (ImplicitRegisterUse::kWriteAccumulator |
             ImplicitRegisterUse::kClobberAccumulator)) !=
           ImplicitRegisterUse::kNone;
  }
References v8::internal::interpreter::kClobberAccumulator, v8::internal::interpreter::kNone, and v8::internal::interpreter::kWriteAccumulator.
Referenced by v8::internal::interpreter::BytecodeRegisterOptimizer::PrepareForBytecode(), and v8::internal::interpreter::Bytecodes::WritesOrClobbersAccumulator().
Member Data Documentation
kOperandScaleCount
const int v8::internal::interpreter::BytecodeOperands::kOperandScaleCount [static]
Initial value:
=
      0 OPERAND_SCALE_LIST(OPERAND_SCALE_COUNT)
Definition at line 153 of file bytecode-operands.h.
Referenced by v8::internal::interpreter::WriteHeader().
kOperandTypeCount
const int v8::internal::interpreter::BytecodeOperands::kOperandTypeCount = static_cast<int>(OperandType::kLast) + 1 [static]
Definition at line 149 of file bytecode-operands.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/interpreter/bytecode-operands.h