v8::internal::BigInt Class Reference
#include <bigint.h>
Classes
class BodyDescriptor
Public Member Functions
bool ToBoolean ()
uint32_t Hash ()
bool IsNegative () const
V8_EXPORT_PRIVATE int64_t AsInt64 (bool *lossless=nullptr)
uint64_t AsUint64 (bool *lossless=nullptr)
uint32_t Words64Count ()
void ToWordsArray64 (int *sign_bit, uint32_t *words64_count, uint64_t *words)
void BigIntShortPrint (std::ostream &os)
Static Public Member Functions
static Handle< BigInt > UnaryMinus (Isolate *isolate, DirectHandle< BigInt > x)
static MaybeDirectHandle< BigInt > BitwiseNot (Isolate *isolate, DirectHandle< BigInt > x)
static MaybeDirectHandle< BigInt > Exponentiate (Isolate *isolate, DirectHandle< BigInt > base, DirectHandle< BigInt > exponent)
static MaybeHandle< BigInt > Multiply (Isolate *isolate, DirectHandle< BigInt > x, DirectHandle< BigInt > y)
static MaybeHandle< BigInt > Divide (Isolate *isolate, DirectHandle< BigInt > x, DirectHandle< BigInt > y)
static MaybeHandle< BigInt > Remainder (Isolate *isolate, DirectHandle< BigInt > x, DirectHandle< BigInt > y)
static MaybeHandle< BigInt > Add (Isolate *isolate, DirectHandle< BigInt > x, DirectHandle< BigInt > y)
static MaybeHandle< BigInt > Subtract (Isolate *isolate, DirectHandle< BigInt > x, DirectHandle< BigInt > y)
static ComparisonResult CompareToBigInt (DirectHandle< BigInt > x, DirectHandle< BigInt > y)
static bool EqualToBigInt (Tagged< BigInt > x, Tagged< BigInt > y)
static MaybeHandle< BigInt > Increment (Isolate *isolate, DirectHandle< BigInt > x)
static MaybeHandle< BigInt > Decrement (Isolate *isolate, DirectHandle< BigInt > x)
static Maybe< bool > EqualToString (Isolate *isolate, DirectHandle< BigInt > x, DirectHandle< String > y)
static bool EqualToNumber (DirectHandle< BigInt > x, DirectHandle< Object > y)
static Maybe< ComparisonResult > CompareToString (Isolate *isolate, DirectHandle< BigInt > x, DirectHandle< String > y)
static ComparisonResult CompareToNumber (DirectHandle< BigInt > x, DirectHandle< Object > y)
static V8_EXPORT_PRIVATE ComparisonResult CompareToDouble (DirectHandle< BigInt > x, double y)
static DirectHandle< BigInt > AsIntN (Isolate *isolate, uint64_t n, DirectHandle< BigInt > x)
static MaybeDirectHandle< BigInt > AsUintN (Isolate *isolate, uint64_t n, DirectHandle< BigInt > x)
static V8_EXPORT_PRIVATE Handle< BigInt > FromInt64 (Isolate *isolate, int64_t n)
static V8_EXPORT_PRIVATE Handle< BigInt > FromUint64 (Isolate *isolate, uint64_t n)
static MaybeDirectHandle< BigInt > FromWords64 (Isolate *isolate, int sign_bit, uint32_t words64_count, const uint64_t *words)
static uint32_t SizeFor (uint32_t length)
static MaybeHandle< String > ToString (Isolate *isolate, DirectHandle< BigInt > bigint, int radix=10, ShouldThrow should_throw=kThrowOnError)
static DirectHandle< String > NoSideEffectsToString (Isolate *isolate, DirectHandle< BigInt > bigint)
static DirectHandle< Number > ToNumber (Isolate *isolate, DirectHandle< BigInt > x)
static V8_EXPORT_PRIVATE MaybeHandle< BigInt > FromNumber (Isolate *isolate, DirectHandle< Object > number)
Private Member Functions
uint32_t GetBitfieldForSerialization () const
void SerializeDigits (uint8_t *storage, size_t storage_length)
Static Private Member Functions
template<typename IsolateT >
static Handle< BigInt > Zero (IsolateT *isolate, AllocationType allocation=AllocationType::kYoung)
template<typename IsolateT >
static MaybeHandle< BigInt > Allocate (IsolateT *isolate, bigint::FromStringAccumulator *accumulator, bool negative, AllocationType allocation)
static size_t DigitsByteLengthForBitfield (uint32_t bitfield)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< BigInt > FromSerializedDigits (Isolate *isolate, uint32_t bitfield, base::Vector< const uint8_t > digits_storage)
Friends
template<typename IsolateT >
class StringToBigIntHelper
class ValueDeserializer
class ValueSerializer
Additional Inherited Members
Detailed Description
Definition at line 181 of file bigint.h.
Member Function Documentation
Add()
MaybeHandle< BigInt > v8::internal::BigInt::Add (Isolate * isolate, DirectHandle< BigInt > x, DirectHandle< BigInt > y) [static]
Definition at line 512 of file bigint.cc.
                                                        {
  if (x->is_zero()) return indirect_handle(y, isolate);
  if (y->is_zero()) return indirect_handle(x, isolate);
  bool xsign = x->sign();
  bool ysign = y->sign();
  uint32_t result_length =
      bigint::AddSignedResultLength(x->length(), y->length(), xsign == ysign);
  Handle<MutableBigInt> result;
  if (!MutableBigInt::New(isolate, result_length).ToHandle(&result)) {
    // Allocation fails when {result_length} exceeds the max BigInt size.
    return {};
  }
  DisallowGarbageCollection no_gc;
  bool result_sign = bigint::AddSigned(result->rw_digits(), x->digits(), xsign,
                                       y->digits(), ysign);
  result->set_sign(result_sign);
  return MutableBigInt::MakeImmutable(result);
}
References v8::bigint::AddSigned(), v8::bigint::AddSignedResultLength(), v8::internal::indirect_handle(), v8::internal::MutableBigInt::MakeImmutable(), v8::internal::MutableBigInt::New(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, v8::anonymous_namespace{api.cc}::ToHandle(), and v8::internal::y.
Allocate()
template<typename IsolateT >
template MaybeHandle< BigInt > v8::internal::BigInt::Allocate (IsolateT * isolate, bigint::FromStringAccumulator * accumulator, bool negative, AllocationType allocation) [static], [private]
Definition at line 1188 of file bigint.cc.
                                                                               {
  uint32_t digits = accumulator->ResultLength();
  DCHECK_LE(digits, kMaxLength);
  Handle<MutableBigInt> result =
      MutableBigInt::New(isolate, digits, allocation).ToHandleChecked();
  bigint::Status status =
      isolate->bigint_processor()->FromString(result->rw_digits(), accumulator);
  if (status == bigint::Status::kInterrupted) {
    Terminate(isolate);
    return {};
  }
  if (digits > 0) result->set_sign(negative);
  return MutableBigInt::MakeImmutable(result);
}
References DCHECK_LE, v8::internal::BigIntBase::digits(), v8::bigint::kInterrupted, v8::internal::BigIntBase::kMaxLength, v8::internal::MutableBigInt::MakeImmutable(), v8::internal::negative, v8::internal::MutableBigInt::New(), v8::base::internal::result, v8::bigint::FromStringAccumulator::ResultLength(), v8::internal::status, and v8::internal::Terminate().
Referenced by v8::internal::StringToBigIntHelper< IsolateT >::GetResult().
AsInt64()
int64_t v8::internal::BigInt::AsInt64 (bool * lossless = nullptr)
Definition at line 1438 of file bigint.cc.
                                      {
  uint64_t raw = MutableBigInt::GetRawBits(this, lossless);
  int64_t result = static_cast<int64_t>(raw);
  if (lossless != nullptr && (result < 0) != sign()) *lossless = false;
  return result;
}
References v8::internal::MutableBigInt::GetRawBits(), v8::base::internal::result, and v8::internal::BigIntBase::sign().
AsIntN()
DirectHandle< BigInt > v8::internal::BigInt::AsIntN (Isolate * isolate, uint64_t n, DirectHandle< BigInt > x) [static]
Definition at line 1290 of file bigint.cc.
                                                            {
  if (x->is_zero() || n > kMaxLengthBits) return x;
  if (n == 0) return MutableBigInt::Zero(isolate);
  int needed_length =
      bigint::AsIntNResultLength(x->digits(), x->sign(), static_cast<int>(n));
  if (needed_length == -1) return x;
  Handle<MutableBigInt> result =
      MutableBigInt::New(isolate, needed_length).ToHandleChecked();
  bool negative = bigint::AsIntN(result->rw_digits(), x->digits(), x->sign(),
                                 static_cast<int>(n));
  result->set_sign(negative);
  return MutableBigInt::MakeImmutable(result);
}
References v8::bigint::AsIntN(), v8::bigint::AsIntNResultLength(), v8::internal::BigIntBase::kMaxLengthBits, v8::internal::MutableBigInt::MakeImmutable(), v8::internal::negative, v8::internal::MutableBigInt::New(), v8::base::internal::result, and v8::internal::MutableBigInt::Zero().
Referenced by v8::internal::BUILTIN().
AsUint64()
uint64_t v8::internal::BigInt::AsUint64 (bool * lossless = nullptr)
Definition at line 1445 of file bigint.cc.
                                        {
  uint64_t result = MutableBigInt::GetRawBits(this, lossless);
  if (lossless != nullptr && sign()) *lossless = false;
  return result;
}
References v8::internal::MutableBigInt::GetRawBits(), v8::base::internal::result, and v8::internal::BigIntBase::sign().
AsUintN()
MaybeDirectHandle< BigInt > v8::internal::BigInt::AsUintN (Isolate * isolate, uint64_t n, DirectHandle< BigInt > x) [static]
Definition at line 1305 of file bigint.cc.
                                                                  {
  if (x->is_zero()) return x;
  if (n == 0) return MutableBigInt::Zero(isolate);
  Handle<MutableBigInt> result;
  if (x->sign()) {
    if (n > kMaxLengthBits) {
      return ThrowBigIntTooBig<BigInt>(isolate);
    }
    int result_length = bigint::AsUintN_Neg_ResultLength(static_cast<int>(n));
    result = MutableBigInt::New(isolate, result_length).ToHandleChecked();
    bigint::AsUintN_Neg(result->rw_digits(), x->digits(), static_cast<int>(n));
  } else {
    if (n >= kMaxLengthBits) return x;
    int result_length =
        bigint::AsUintN_Pos_ResultLength(x->digits(), static_cast<int>(n));
    if (result_length < 0) return x;
    result = MutableBigInt::New(isolate, result_length).ToHandleChecked();
    bigint::AsUintN_Pos(result->rw_digits(), x->digits(), static_cast<int>(n));
  }
  DCHECK(!result->sign());
  return MutableBigInt::MakeImmutable(result);
}
References v8::bigint::AsUintN_Neg(), v8::bigint::AsUintN_Neg_ResultLength(), v8::bigint::AsUintN_Pos(), v8::bigint::AsUintN_Pos_ResultLength(), v8::internal::DCHECK(), v8::internal::BigIntBase::kMaxLengthBits, v8::internal::MutableBigInt::MakeImmutable(), v8::internal::MutableBigInt::New(), v8::base::internal::result, and v8::internal::MutableBigInt::Zero().
Referenced by v8::internal::BUILTIN().
BigIntShortPrint()
void v8::internal::BigInt::BigIntShortPrint (std::ostream & os)
Definition at line 1120 of file bigint.cc.
                                            {
  if (sign()) os << "-";
  uint32_t len = length();
  if (len == 0) {
    os << "0";
    return;
  }
  if (len > 1) os << "...";
  os << digit(0);
}
References v8::internal::BigIntBase::digit(), v8::internal::BigIntBase::length(), and v8::internal::BigIntBase::sign().
BitwiseNot()
MaybeDirectHandle< BigInt > v8::internal::BigInt::BitwiseNot (Isolate * isolate, DirectHandle< BigInt > x) [static]
Definition at line 345 of file bigint.cc.
                                                                     {
  MaybeHandle<MutableBigInt> result;
  if (x->sign()) {
    // ~(-x) == ~(~(x-1)) == x-1
    result = MutableBigInt::AbsoluteSubOne(isolate, x);
  } else {
    // ~x == -x-1 == -(x+1)
    result = MutableBigInt::AbsoluteAddOne(isolate, x, true);
  }
  return MutableBigInt::MakeImmutable(result);
}
References v8::internal::MutableBigInt::AbsoluteAddOne(), v8::internal::MutableBigInt::AbsoluteSubOne(), v8::internal::MutableBigInt::MakeImmutable(), and v8::base::internal::result.
Referenced by v8::internal::RUNTIME_FUNCTION().
CompareToBigInt()
ComparisonResult v8::internal::BigInt::CompareToBigInt (DirectHandle< BigInt > x, DirectHandle< BigInt > y) [static]
Definition at line 575 of file bigint.cc.
                                                                 {
  bool x_sign = x->sign();
  if (x_sign != y->sign()) return UnequalSign(x_sign);
  int result = bigint::Compare(x->digits(), y->digits());
  if (result > 0) return AbsoluteGreater(x_sign);
  if (result < 0) return AbsoluteLess(x_sign);
  return ComparisonResult::kEqual;
}
References v8::internal::anonymous_namespace{bigint.cc}::AbsoluteGreater(), v8::internal::anonymous_namespace{bigint.cc}::AbsoluteLess(), v8::bigint::Compare(), v8::internal::kEqual, v8::base::internal::result, v8::internal::anonymous_namespace{bigint.cc}::UnequalSign(), and v8::internal::y.
Referenced by v8::internal::Object::Compare(), and CompareToString().
CompareToDouble()
ComparisonResult v8::internal::BigInt::CompareToDouble (DirectHandle< BigInt > x, double y) [static]
Definition at line 704 of file bigint.cc.
                                                                         {
  if (std::isnan(y)) return ComparisonResult::kUndefined;
  if (y == V8_INFINITY) return ComparisonResult::kLessThan;
  if (y == -V8_INFINITY) return ComparisonResult::kGreaterThan;
  bool x_sign = x->sign();
  // Note that this is different from the double's sign bit for -0. That's
  // intentional because -0 must be treated like 0.
  bool y_sign = (y < 0);
  if (x_sign != y_sign) return UnequalSign(x_sign);
  if (y == 0) {
    DCHECK(!x_sign);
    return x->is_zero() ? ComparisonResult::kEqual
                        : ComparisonResult::kGreaterThan;
  }
  if (x->is_zero()) {
    DCHECK(!y_sign);
    return ComparisonResult::kLessThan;
  }
  uint64_t double_bits = base::bit_cast<uint64_t>(y);
  int32_t raw_exponent =
      static_cast<int32_t>(double_bits >>
                           base::Double::kPhysicalSignificandSize) &
      0x7FF;
  uint64_t mantissa = double_bits & base::Double::kSignificandMask;
  // Non-finite doubles are handled above.
  DCHECK_NE(raw_exponent, 0x7FF);
  int32_t exponent = raw_exponent - 0x3FF;
  if (exponent < 0) {
    // The absolute value of the double is less than 1. Only 0n has an
    // absolute value smaller than that, but we've already covered that case.
    DCHECK(!x->is_zero());
    return AbsoluteGreater(x_sign);
  }
  uint32_t x_length = x->length();
  digit_t x_msd = x->digit(x_length - 1);
  uint32_t msd_leading_zeros = base::bits::CountLeadingZeros(x_msd);
  uint32_t x_bitlength = x_length * kDigitBits - msd_leading_zeros;
  uint32_t y_bitlength = exponent + 1;
  if (x_bitlength < y_bitlength) return AbsoluteLess(x_sign);
  if (x_bitlength > y_bitlength) return AbsoluteGreater(x_sign);
  // At this point, we know that signs and bit lengths (i.e. position of
  // the most significant bit in exponent-free representation) are identical.
  // {x} is not zero, {y} is finite and not denormal.
  // Now we virtually convert the double to an integer by shifting its
  // mantissa according to its exponent, so it will align with the BigInt {x},
  // and then we compare them bit for bit until we find a difference or the
  // least significant bit.
  // <----- 52 ------> <-- virtual trailing zeroes -->
  // y / mantissa: 1yyyyyyyyyyyyyyyyy 0000000000000000000000000000000
  // x / digits: 0001xxxx xxxxxxxx xxxxxxxx ...
  // <--> <------>
  // msd_topbit kDigitBits
  //
  mantissa |= base::Double::kHiddenBit;
  const uint32_t kMantissaTopBit = 52; // 0-indexed.
  // 0-indexed position of {x}'s most significant bit within the {msd}.
  uint32_t msd_topbit = kDigitBits - 1 - msd_leading_zeros;
  DCHECK_EQ(msd_topbit, (x_bitlength - 1) % kDigitBits);
  // Shifted chunk of {mantissa} for comparing with {digit}.
  digit_t compare_mantissa;
  // Number of unprocessed bits in {mantissa}. We'll keep them shifted to
  // the left (i.e. most significant part) of the underlying uint64_t.
  uint32_t remaining_mantissa_bits = 0;
  // First, compare the most significant digit against the beginning of
  // the mantissa.
  if (msd_topbit < kMantissaTopBit) {
    remaining_mantissa_bits = (kMantissaTopBit - msd_topbit);
    compare_mantissa = mantissa >> remaining_mantissa_bits;
    mantissa = mantissa << (64 - remaining_mantissa_bits);
  } else {
    DCHECK_GE(msd_topbit, kMantissaTopBit);
    compare_mantissa = mantissa << (msd_topbit - kMantissaTopBit);
    mantissa = 0;
  }
  if (x_msd > compare_mantissa) return AbsoluteGreater(x_sign);
  if (x_msd < compare_mantissa) return AbsoluteLess(x_sign);
  // Then, compare additional digits against any remaining mantissa bits.
  static_assert(BigInt::kMaxLength < kMaxInt);
  for (int32_t digit_index = x_length - 2; digit_index >= 0; digit_index--) {
    if (remaining_mantissa_bits > 0) {
      remaining_mantissa_bits -= kDigitBits;
      if (sizeof(mantissa) != sizeof(x_msd)) {
        compare_mantissa = mantissa >> (64 - kDigitBits);
        // "& 63" to appease compilers. kDigitBits is 32 here anyway.
        mantissa = mantissa << (kDigitBits & 63);
      } else {
        compare_mantissa = mantissa;
        mantissa = 0;
      }
    } else {
      compare_mantissa = 0;
    }
    digit_t digit = x->digit(digit_index);
    if (digit > compare_mantissa) return AbsoluteGreater(x_sign);
    if (digit < compare_mantissa) return AbsoluteLess(x_sign);
  }
  // Integer parts are equal; check whether {y} has a fractional part.
  if (mantissa != 0) {
    DCHECK_GT(remaining_mantissa_bits, 0);
    return AbsoluteLess(x_sign);
  }
  return ComparisonResult::kEqual;
}
References v8::internal::anonymous_namespace{bigint.cc}::AbsoluteGreater(), v8::internal::anonymous_namespace{bigint.cc}::AbsoluteLess(), v8::base::bits::CountLeadingZeros(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, DCHECK_GT, DCHECK_NE, v8::internal::BigIntBase::digit(), v8::internal::BigIntBase::kDigitBits, v8::internal::kEqual, v8::internal::kGreaterThan, v8::base::Double::kHiddenBit, v8::internal::kLessThan, v8::internal::kMaxInt, v8::internal::BigIntBase::kMaxLength, v8::base::Double::kPhysicalSignificandSize, v8::base::Double::kSignificandMask, v8::internal::kUndefined, v8::internal::anonymous_namespace{bigint.cc}::UnequalSign(), V8_INFINITY, and v8::internal::y.
Referenced by CompareToNumber(), and EqualToNumber().
CompareToNumber()
ComparisonResult v8::internal::BigInt::CompareToNumber (DirectHandle< BigInt > x, DirectHandle< Object > y) [static]
Definition at line 675 of file bigint.cc.
                                                                 {
  DCHECK(IsNumber(*y));
  if (IsSmi(*y)) {
    bool x_sign = x->sign();
    int y_value = Smi::ToInt(*y);
    bool y_sign = (y_value < 0);
    if (x_sign != y_sign) return UnequalSign(x_sign);
    if (x->is_zero()) {
      DCHECK(!y_sign);
      return y_value == 0 ? ComparisonResult::kEqual
                          : ComparisonResult::kLessThan;
    }
    // Any multi-digit BigInt is bigger than a Smi.
    static_assert(sizeof(digit_t) >= sizeof(y_value));
    if (x->length() > 1) return AbsoluteGreater(x_sign);
    digit_t abs_value = std::abs(static_cast<int64_t>(y_value));
    digit_t x_digit = x->digit(0);
    if (x_digit > abs_value) return AbsoluteGreater(x_sign);
    if (x_digit < abs_value) return AbsoluteLess(x_sign);
    return ComparisonResult::kEqual;
  }
  DCHECK(IsHeapNumber(*y));
  double value = Cast<HeapNumber>(y)->value();
  return CompareToDouble(x, value);
}
References v8::internal::anonymous_namespace{bigint.cc}::AbsoluteGreater(), v8::internal::anonymous_namespace{bigint.cc}::AbsoluteLess(), CompareToDouble(), v8::internal::DCHECK(), v8::internal::IsNumber(), v8::internal::IsSmi(), v8::internal::kEqual, v8::internal::kLessThan, v8::internal::Smi::ToInt(), v8::internal::anonymous_namespace{bigint.cc}::UnequalSign(), v8::internal::value, and v8::internal::y.
Referenced by v8::internal::Object::Compare(), and v8::internal::RUNTIME_FUNCTION().
CompareToString()
Maybe< ComparisonResult > v8::internal::BigInt::CompareToString (Isolate * isolate, DirectHandle< BigInt > x, DirectHandle< String > y) [static]
Definition at line 621 of file bigint.cc.
                                                                        {
  // a. Let ny be StringToBigInt(y);
  MaybeDirectHandle<BigInt> maybe_ny = StringToBigInt(isolate, y);
  // b. If ny is NaN, return undefined.
  DirectHandle<BigInt> ny;
  if (!maybe_ny.ToHandle(&ny)) {
    if (isolate->has_exception()) {
      return Nothing<ComparisonResult>();
    } else {
      return Just(ComparisonResult::kUndefined);
    }
  }
  // c. Return BigInt::lessThan(x, ny).
  return Just(CompareToBigInt(x, ny));
}
References CompareToBigInt(), v8::internal::Isolate::has_exception(), v8::Just(), v8::internal::kUndefined, v8::internal::StringToBigInt(), v8::internal::MaybeDirectHandle< T >::ToHandle(), and v8::internal::y.
Referenced by v8::internal::Object::Compare(), and v8::internal::RUNTIME_FUNCTION().
Decrement()
MaybeHandle< BigInt > v8::internal::BigInt::Decrement (Isolate * isolate, DirectHandle< BigInt > x) [static]
Definition at line 607 of file bigint.cc.
                                                              {
  MaybeHandle<MutableBigInt> result;
  if (x->sign()) {
    result = MutableBigInt::AbsoluteAddOne(isolate, x, true);
  } else if (x->is_zero()) {
    // TODO(jkummerow): Consider caching a canonical -1n BigInt.
    return MutableBigInt::NewFromInt(isolate, -1);
  } else {
    result = MutableBigInt::AbsoluteSubOne(isolate, x);
  }
  return MutableBigInt::MakeImmutable(result);
}
References v8::internal::MutableBigInt::AbsoluteAddOne(), v8::internal::MutableBigInt::AbsoluteSubOne(), v8::internal::MutableBigInt::MakeImmutable(), v8::internal::MutableBigInt::NewFromInt(), and v8::base::internal::result.
Referenced by v8::internal::RUNTIME_FUNCTION().
DigitsByteLengthForBitfield()
size_t v8::internal::BigInt::DigitsByteLengthForBitfield (uint32_t bitfield) [static], [private]
Definition at line 1222 of file bigint.cc.
                                                            {
  return LengthBits::decode(bitfield);
}
References v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::ValueDeserializer::ReadBigInt(), and v8::internal::ValueSerializer::WriteBigIntContents().
Divide()
MaybeHandle< BigInt > v8::internal::BigInt::Divide (Isolate * isolate, DirectHandle< BigInt > x, DirectHandle< BigInt > y) [static]
Definition at line 450 of file bigint.cc.
                                                           {
  // 1. If y is 0n, throw a RangeError exception.
  if (y->is_zero()) {
    THROW_NEW_ERROR(isolate, NewRangeError(MessageTemplate::kBigIntDivZero));
  }
  // 2. Let quotient be the mathematical value of x divided by y.
  // 3. Return a BigInt representing quotient rounded towards 0 to the next
  // integral value.
  if (bigint::Compare(x->digits(), y->digits()) < 0) {
    return Zero(isolate);
  }
  bool result_sign = x->sign() != y->sign();
  if (y->length() == 1 && y->digit(0) == 1) {
    return result_sign == x->sign() ? indirect_handle(x, isolate)
                                    : UnaryMinus(isolate, x);
  }
  Handle<MutableBigInt> quotient;
  uint32_t result_length = bigint::DivideResultLength(x->digits(), y->digits());
  if (!MutableBigInt::New(isolate, result_length).ToHandle(&quotient)) {
    return {};
  }
  DisallowGarbageCollection no_gc;
  bigint::Status status = isolate->bigint_processor()->Divide(
      quotient->rw_digits(), x->digits(), y->digits());
  if (status == bigint::Status::kInterrupted) {
    AllowGarbageCollection terminating_anyway;
    isolate->TerminateExecution();
    return {};
  }
  quotient->set_sign(result_sign);
  return MutableBigInt::MakeImmutable(quotient);
}
References v8::internal::Isolate::bigint_processor(), v8::bigint::Compare(), v8::bigint::Processor::Divide(), v8::bigint::DivideResultLength(), v8::internal::indirect_handle(), v8::bigint::kInterrupted, v8::internal::MutableBigInt::MakeImmutable(), v8::internal::MutableBigInt::New(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::status, v8::internal::Isolate::TerminateExecution(), THROW_NEW_ERROR, v8::anonymous_namespace{api.cc}::ToHandle(), UnaryMinus(), v8::internal::y, and Zero().
Referenced by v8::internal::anonymous_namespace{intl-objects.cc}::ApproximateMillisecondEpoch().
EqualToBigInt()
bool v8::internal::BigInt::EqualToBigInt (Tagged< BigInt > x, Tagged< BigInt > y) [static]
Definition at line 586 of file bigint.cc.
                                                             {
  if (x->sign() != y->sign()) return false;
  if (x->length() != y->length()) return false;
  for (uint32_t i = 0; i < x->length(); i++) {
    if (x->digit(i) != y->digit(i)) return false;
  }
  return true;
}
References v8::internal::y.
Referenced by v8::internal::Object::Equals(), EqualToString(), v8::internal::RUNTIME_FUNCTION(), v8::internal::Object::SameValue(), v8::internal::Object::SameValueZero(), and v8::internal::Object::StrictEquals().
EqualToNumber()
bool v8::internal::BigInt::EqualToNumber (DirectHandle< BigInt > x, DirectHandle< Object > y) [static]
Definition at line 656 of file bigint.cc.
                                                                         {
  DCHECK(IsNumber(*y));
  // a. If x or y are any of NaN, +, or -, return false.
  // b. If the mathematical value of x is equal to the mathematical value of y,
  // return true, otherwise return false.
  if (IsSmi(*y)) {
    int value = Smi::ToInt(*y);
    if (value == 0) return x->is_zero();
    // Any multi-digit BigInt is bigger than a Smi.
    static_assert(sizeof(digit_t) >= sizeof(value));
    return (x->length() == 1) && (x->sign() == (value < 0)) &&
           (x->digit(0) ==
            static_cast<digit_t>(std::abs(static_cast<int64_t>(value))));
  }
  DCHECK(IsHeapNumber(*y));
  double value = Cast<HeapNumber>(y)->value();
  return CompareToDouble(x, value) == ComparisonResult::kEqual;
}
References CompareToDouble(), v8::internal::DCHECK(), v8::internal::IsNumber(), v8::internal::IsSmi(), v8::internal::kEqual, v8::internal::Smi::ToInt(), v8::internal::value, and v8::internal::y.
Referenced by v8::internal::Object::Equals(), and v8::internal::RUNTIME_FUNCTION().
EqualToString()
Maybe< bool > v8::internal::BigInt::EqualToString (Isolate * isolate, DirectHandle< BigInt > x, DirectHandle< String > y) [static]
Definition at line 639 of file bigint.cc.
                                                          {
  // a. Let n be StringToBigInt(y).
  MaybeDirectHandle<BigInt> maybe_n = StringToBigInt(isolate, y);
  // b. If n is NaN, return false.
  DirectHandle<BigInt> n;
  if (!maybe_n.ToHandle(&n)) {
    if (isolate->has_exception()) {
      return Nothing<bool>();
    } else {
      return Just(false);
    }
  }
  // c. Return the result of x == n.
  return Just(EqualToBigInt(*x, *n));
}
References EqualToBigInt(), v8::internal::Isolate::has_exception(), v8::Just(), v8::internal::StringToBigInt(), v8::internal::MaybeDirectHandle< T >::ToHandle(), and v8::internal::y.
Referenced by v8::internal::Object::Equals(), and v8::internal::RUNTIME_FUNCTION().
Exponentiate()
MaybeDirectHandle< BigInt > v8::internal::BigInt::Exponentiate (Isolate * isolate, DirectHandle< BigInt > base, DirectHandle< BigInt > exponent) [static]
Definition at line 358 of file bigint.cc.
                                                                              {
  // 1. If exponent is < 0, throw a RangeError exception.
  if (exponent->sign()) {
    THROW_NEW_ERROR(isolate, NewRangeError(MessageTemplate::kMustBePositive));
  }
  // 2. If base is 0n and exponent is 0n, return 1n.
  if (exponent->is_zero()) {
    return MutableBigInt::NewFromInt(isolate, 1);
  }
  // 3. Return a BigInt representing the mathematical value of base raised
  // to the power exponent.
  if (base->is_zero()) return base;
  if (base->length() == 1 && base->digit(0) == 1) {
    // (-1) ** even_number == 1.
    if (base->sign() && (exponent->digit(0) & 1) == 0) {
      return UnaryMinus(isolate, base);
    }
    // (-1) ** odd_number == -1; 1 ** anything == 1.
    return base;
  }
  // For all bases >= 2, very large exponents would lead to unrepresentable
  // results.
  static_assert(kMaxLengthBits < std::numeric_limits<digit_t>::max());
  if (exponent->length() > 1) {
    return ThrowBigIntTooBig<BigInt>(isolate);
  }
  digit_t exp_value = exponent->digit(0);
  if (exp_value == 1) return base;
  if (exp_value >= kMaxLengthBits) {
    return ThrowBigIntTooBig<BigInt>(isolate);
  }
  static_assert(kMaxLengthBits <= kMaxInt);
  int n = static_cast<int>(exp_value);
  if (base->length() == 1 && base->digit(0) == 2) {
    // Fast path for 2^n.
    int needed_digits = 1 + (n / kDigitBits);
    Handle<MutableBigInt> result;
    if (!MutableBigInt::New(isolate, needed_digits).ToHandle(&result))
      return {};
    result->InitializeDigits(needed_digits);
    // All bits are zero. Now set the n-th bit.
    digit_t msd = static_cast<digit_t>(1) << (n % kDigitBits);
    result->set_digit(needed_digits - 1, msd);
    // Result is negative for odd powers of -2n.
    if (base->sign()) result->set_sign((n & 1) != 0);
    return MutableBigInt::MakeImmutable(result);
  }
  DirectHandle<BigInt> result;
  DirectHandle<BigInt> running_square = base;
  // This implicitly sets the result's sign correctly.
  if (n & 1) result = base;
  n >>= 1;
  for (; n != 0; n >>= 1) {
    MaybeDirectHandle<BigInt> maybe_result =
        Multiply(isolate, running_square, running_square);
    if (!maybe_result.ToHandle(&running_square)) return maybe_result;
    if (n & 1) {
      if (result.is_null()) {
        result = running_square;
      } else {
        maybe_result = Multiply(isolate, result, running_square);
        if (!maybe_result.ToHandle(&result)) return maybe_result;
      }
    }
  }
  return result;
}
References v8::internal::BigIntBase::kDigitBits, v8::internal::kMaxInt, v8::internal::BigIntBase::kMaxLengthBits, v8::internal::MutableBigInt::MakeImmutable(), Multiply(), v8::internal::MutableBigInt::New(), v8::internal::MutableBigInt::NewFromInt(), v8::base::internal::result, THROW_NEW_ERROR, v8::internal::MaybeDirectHandle< T >::ToHandle(), and UnaryMinus().
Referenced by v8::internal::RUNTIME_FUNCTION().
FromInt64()
Handle< BigInt > v8::internal::BigInt::FromInt64 (Isolate * isolate, int64_t n) [static]
Definition at line 1329 of file bigint.cc.
                                                            {
  if (n == 0) return MutableBigInt::Zero(isolate);
  static_assert(kDigitBits == 64 || kDigitBits == 32);
  uint32_t length = 64 / kDigitBits;
  Handle<MutableBigInt> result =
      Cast<MutableBigInt>(isolate->factory()->NewBigInt(length));
  bool sign = n < 0;
  result->initialize_bitfield(sign, length);
  uint64_t absolute;
  if (!sign) {
    absolute = static_cast<uint64_t>(n);
  } else {
    if (n == std::numeric_limits<int64_t>::min()) {
      absolute = static_cast<uint64_t>(std::numeric_limits<int64_t>::max()) + 1;
    } else {
      absolute = static_cast<uint64_t>(-n);
    }
  }
  result->set_64_bits(absolute);
  return MutableBigInt::MakeImmutable(result);
}
References v8::internal::Isolate::factory(), v8::internal::BigIntBase::kDigitBits, v8::internal::BigIntBase::length(), v8::internal::MutableBigInt::MakeImmutable(), v8::internal::FactoryBase< Impl >::NewBigInt(), v8::base::internal::result, v8::internal::BigIntBase::sign(), and v8::internal::MutableBigInt::Zero().
Referenced by v8::internal::TranslatedValue::GetValue(), v8::internal::anonymous_namespace{intl-objects.cc}::MillisecondToNanosecond(), v8::internal::WasmValueObject::New(), v8::BigIntObject::New(), v8::BigInt::New(), v8::internal::WasmObject::ReadValueAt(), v8::internal::DeoptimizationLiteral::Reify(), and v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::ToHandle().
FromNumber()
MaybeHandle< BigInt > v8::internal::BigInt::FromNumber (Isolate * isolate, DirectHandle< Object > number) [static]
Definition at line 950 of file bigint.cc.
                                                                    {
  DCHECK(IsNumber(*number));
  if (IsSmi(*number)) {
    return MutableBigInt::NewFromInt(isolate, Smi::ToInt(*number));
  }
  double value = Cast<HeapNumber>(*number)->value();
  if (!std::isfinite(value) || (DoubleToInteger(value) != value)) {
    THROW_NEW_ERROR(isolate,
                    NewRangeError(MessageTemplate::kBigIntFromNumber, number));
  }
  return MutableBigInt::NewFromDouble(isolate, value);
}
References v8::internal::DCHECK(), v8::internal::DoubleToInteger(), v8::internal::IsNumber(), v8::internal::IsSmi(), v8::internal::MutableBigInt::NewFromDouble(), v8::internal::MutableBigInt::NewFromInt(), THROW_NEW_ERROR, v8::internal::Smi::ToInt(), and v8::internal::value.
Referenced by v8::internal::BUILTIN(), and v8::internal::RUNTIME_FUNCTION().
FromSerializedDigits()
MaybeDirectHandle< BigInt > v8::internal::BigInt::FromSerializedDigits (Isolate * isolate, uint32_t bitfield, base::Vector< const uint8_t > digits_storage) [static], [private]
Definition at line 1247 of file bigint.cc.
                                              {
  uint32_t bytelength = LengthBits::decode(bitfield);
  DCHECK_EQ(static_cast<uint32_t>(digits_storage.length()), bytelength);
  bool sign = SignBits::decode(bitfield);
  uint32_t length = (bytelength + kDigitSize - 1) / kDigitSize; // Round up.
  // There is no -0n. Reject corrupted serialized data.
  if (length == 0 && sign == true) return {};
  Handle<MutableBigInt> result =
      Cast<MutableBigInt>(isolate->factory()->NewBigInt(length));
  result->initialize_bitfield(sign, length);
  UnalignedValueMember<digit_t>* digits = result->raw_digits();
#if defined(V8_TARGET_LITTLE_ENDIAN)
  memcpy(digits, digits_storage.begin(), bytelength);
  void* padding_start =
      reinterpret_cast<void*>(reinterpret_cast<Address>(digits) + bytelength);
  memset(padding_start, 0, length * kDigitSize - bytelength);
#elif defined(V8_TARGET_BIG_ENDIAN)
  digit_t* digit = reinterpret_cast<digit_t*>(digits);
  const digit_t* digit_storage =
      reinterpret_cast<const digit_t*>(digits_storage.begin());
  for (uint32_t i = 0; i < bytelength / kDigitSize; i++) {
    *digit = ByteReverse(*digit_storage);
    digit_storage++;
    digit++;
  }
  if (bytelength % kDigitSize) {
    *digit = 0;
    uint8_t* digit_byte = reinterpret_cast<uint8_t*>(digit);
    digit_byte += sizeof(*digit) - 1;
    const uint8_t* digit_storage_byte =
        reinterpret_cast<const uint8_t*>(digit_storage);
    for (uint32_t i = 0; i < bytelength % kDigitSize; i++) {
      *digit_byte = *digit_storage_byte;
      digit_byte--;
      digit_storage_byte++;
    }
  }
#endif // V8_TARGET_BIG_ENDIAN
  return MutableBigInt::MakeImmutable(result);
}
References v8::base::Vector< T >::begin(), v8::internal::ByteReverse(), DCHECK_EQ, v8::base::BitField< T, shift, size, U >::decode(), v8::internal::BigIntBase::digit(), v8::internal::BigIntBase::digits(), v8::internal::Isolate::factory(), v8::internal::BigIntBase::kDigitSize, v8::base::Vector< T >::length(), v8::internal::BigIntBase::length(), v8::internal::MutableBigInt::MakeImmutable(), v8::internal::FactoryBase< Impl >::NewBigInt(), v8::base::internal::result, and v8::internal::BigIntBase::sign().
Referenced by v8::internal::ValueDeserializer::ReadBigInt().
FromUint64()
Handle< BigInt > v8::internal::BigInt::FromUint64 (Isolate * isolate, uint64_t n) [static]
Definition at line 1351 of file bigint.cc.
                                                              {
  if (n == 0) return MutableBigInt::Zero(isolate);
  static_assert(kDigitBits == 64 || kDigitBits == 32);
  uint32_t length = 64 / kDigitBits;
  Handle<MutableBigInt> result =
      Cast<MutableBigInt>(isolate->factory()->NewBigInt(length));
  result->initialize_bitfield(false, length);
  result->set_64_bits(n);
  return MutableBigInt::MakeImmutable(result);
}
References v8::internal::Isolate::factory(), v8::internal::BigIntBase::kDigitBits, v8::internal::BigIntBase::length(), v8::internal::MutableBigInt::MakeImmutable(), v8::internal::FactoryBase< Impl >::NewBigInt(), v8::base::internal::result, and v8::internal::MutableBigInt::Zero().
Referenced by v8::internal::anonymous_namespace{intl-objects.cc}::ApproximateMillisecondEpoch(), v8::internal::wasm::GetTypeForTable(), v8::internal::TranslatedValue::GetValue(), v8::internal::anonymous_namespace{intl-objects.cc}::MillisecondToNanosecond(), v8::internal::WasmTableObject::New(), v8::BigInt::NewFromUnsigned(), v8::internal::DeoptimizationLiteral::Reify(), and v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::ToHandle().
FromWords64()
MaybeDirectHandle< BigInt > v8::internal::BigInt::FromWords64 (Isolate * isolate, int sign_bit, uint32_t words64_count, const uint64_t * words) [static]
Definition at line 1362 of file bigint.cc.
                                                                     {
  if (words64_count > kMaxLength / (64 / kDigitBits)) {
    return ThrowBigIntTooBig<BigInt>(isolate);
  }
  if (words64_count == 0) return MutableBigInt::Zero(isolate);
  static_assert(kDigitBits == 64 || kDigitBits == 32);
  uint32_t length = (64 / kDigitBits) * words64_count;
  DCHECK_GT(length, 0);
  if (kDigitBits == 32 && words[words64_count - 1] < (1ULL << 32)) length--;
  Handle<MutableBigInt> result;
  if (!MutableBigInt::New(isolate, length).ToHandle(&result)) return {};
  result->set_sign(sign_bit);
  if (kDigitBits == 64) {
    for (uint32_t i = 0; i < length; ++i) {
      result->set_digit(i, static_cast<digit_t>(words[i]));
    }
  } else {
    for (uint32_t i = 0; i < length; i += 2) {
      digit_t lo = static_cast<digit_t>(words[i / 2]);
      digit_t hi = static_cast<digit_t>(words[i / 2] >> 32);
      result->set_digit(i, lo);
      if (i + 1 < length) result->set_digit(i + 1, hi);
    }
  }
  return MutableBigInt::MakeImmutable(result);
}
References DCHECK_GT, v8::internal::hi, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::BigIntBase::kDigitBits, v8::internal::BigIntBase::kMaxLength, v8::internal::BigIntBase::length(), v8::internal::lo, v8::internal::MutableBigInt::MakeImmutable(), v8::internal::MutableBigInt::New(), v8::base::internal::result, v8::anonymous_namespace{api.cc}::ToHandle(), and v8::internal::MutableBigInt::Zero().
Referenced by v8::internal::JSTemporalInstant::EpochNanoseconds(), and v8::BigInt::NewFromWords().
GetBitfieldForSerialization()
uint32_t v8::internal::BigInt::GetBitfieldForSerialization () const [private]
Definition at line 1213 of file bigint.cc.
                                                   {
  // In order to make the serialization format the same on 32/64 bit builds,
  // we convert the length-in-digits to length-in-bytes for serialization.
  // Being able to do this depends on having enough LengthBits:
  static_assert(kMaxLength * kDigitSize <= LengthBits::kMax);
  uint32_t bytelength = length() * kDigitSize;
  return SignBits::encode(sign()) | LengthBits::encode(bytelength);
}
References v8::base::BitField< T, shift, size, U >::encode(), v8::internal::BigIntBase::kDigitSize, v8::base::BitField< T, shift, size, U >::kMax, v8::internal::BigIntBase::kMaxLength, v8::internal::BigIntBase::length(), and v8::internal::BigIntBase::sign().
Hash()
uint32_t v8::internal::BigInt::Hash () [inline]
Definition at line 214 of file bigint.h.
                  {
    return ComputeUnseededHash(length() | (sign() ? (1 << 30) : 0)) ^
           ComputeLongHash(static_cast<uint64_t>(is_zero() ? 0 : digit(0)));
  }
References v8::internal::ComputeLongHash(), v8::internal::ComputeUnseededHash(), v8::internal::BigIntBase::digit(), v8::internal::BigIntBase::is_zero(), v8::internal::BigIntBase::length(), and v8::internal::BigIntBase::sign().
Increment()
MaybeHandle< BigInt > v8::internal::BigInt::Increment (Isolate * isolate, DirectHandle< BigInt > x) [static]
Definition at line 595 of file bigint.cc.
                                                              {
  if (x->sign()) {
    Handle<MutableBigInt> result = MutableBigInt::AbsoluteSubOne(isolate, x);
    result->set_sign(true);
    return MutableBigInt::MakeImmutable(result);
  } else {
    return MutableBigInt::MakeImmutable(
        MutableBigInt::AbsoluteAddOne(isolate, x, false));
  }
}
References v8::internal::MutableBigInt::AbsoluteAddOne(), v8::internal::MutableBigInt::AbsoluteSubOne(), v8::internal::MutableBigInt::MakeImmutable(), and v8::base::internal::result.
Referenced by v8::internal::RUNTIME_FUNCTION().
IsNegative()
bool v8::internal::BigInt::IsNegative () const [inline]
Definition at line 219 of file bigint.h.
{ return sign(); }
References v8::internal::BigIntBase::sign().
Multiply()
MaybeHandle< BigInt > v8::internal::BigInt::Multiply (Isolate * isolate, DirectHandle< BigInt > x, DirectHandle< BigInt > y) [static]
Definition at line 428 of file bigint.cc.
                                                             {
  if (x->is_zero()) return indirect_handle(x, isolate);
  if (y->is_zero()) return indirect_handle(y, isolate);
  uint32_t result_length =
      bigint::MultiplyResultLength(x->digits(), y->digits());
  Handle<MutableBigInt> result;
  if (!MutableBigInt::New(isolate, result_length).ToHandle(&result)) {
    return {};
  }
  DisallowGarbageCollection no_gc;
  bigint::Status status = isolate->bigint_processor()->Multiply(
      result->rw_digits(), x->digits(), y->digits());
  if (status == bigint::Status::kInterrupted) {
    AllowGarbageCollection terminating_anyway;
    isolate->TerminateExecution();
    return {};
  }
  result->set_sign(x->sign() != y->sign());
  return MutableBigInt::MakeImmutable(result);
}
References v8::internal::Isolate::bigint_processor(), v8::internal::indirect_handle(), v8::bigint::kInterrupted, v8::internal::MutableBigInt::MakeImmutable(), v8::bigint::Processor::Multiply(), v8::bigint::MultiplyResultLength(), v8::internal::MutableBigInt::New(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, v8::internal::status, v8::internal::Isolate::TerminateExecution(), v8::anonymous_namespace{api.cc}::ToHandle(), and v8::internal::y.
Referenced by Exponentiate(), and v8::internal::anonymous_namespace{intl-objects.cc}::MillisecondToNanosecond().
NoSideEffectsToString()
DirectHandle< String > v8::internal::BigInt::NoSideEffectsToString (Isolate * isolate, DirectHandle< BigInt > bigint) [static]
Definition at line 918 of file bigint.cc.
                                                   {
  if (bigint->is_zero()) {
    return isolate->factory()->zero_string();
  }
  // The threshold is chosen such that the operation will be fast enough to
  // not need interrupt checks. This function is meant for producing human-
  // readable error messages, so super-long results aren't useful anyway.
  if (bigint->length() > 100) {
    return isolate->factory()->NewStringFromStaticChars(
        "<a very large BigInt>");
  }
  uint32_t chars_allocated =
      bigint::ToStringResultLength(bigint->digits(), 10, bigint->sign());
  DCHECK_LE(chars_allocated, String::kMaxLength);
  DirectHandle<SeqOneByteString> result =
      isolate->factory()
          ->NewRawOneByteString(chars_allocated)
          .ToHandleChecked();
  uint32_t chars_written = chars_allocated;
  DisallowGarbageCollection no_gc;
  char* characters = reinterpret_cast<char*>(result->GetChars(no_gc));
  std::unique_ptr<bigint::Processor, bigint::Processor::Destroyer>
      non_interruptible_processor(
          bigint::Processor::New(new bigint::Platform()));
  non_interruptible_processor->ToString(characters, &chars_written,
                                        bigint->digits(), 10, bigint->sign());
  RightTrimString(isolate, result, chars_allocated, chars_written);
  return result;
}
References DCHECK_LE, v8::internal::Isolate::factory(), v8::internal::String::kMaxLength, v8::bigint::Processor::New(), v8::internal::FactoryBase< Impl >::NewRawOneByteString(), v8::internal::Factory::NewStringFromStaticChars(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, v8::internal::anonymous_namespace{bigint.cc}::RightTrimString(), and v8::bigint::ToStringResultLength().
Referenced by v8::internal::Object::NoSideEffectsToMaybeString().
Remainder()
MaybeHandle< BigInt > v8::internal::BigInt::Remainder (Isolate * isolate, DirectHandle< BigInt > x, DirectHandle< BigInt > y) [static]
Definition at line 484 of file bigint.cc.
                                                              {
  // 1. If y is 0n, throw a RangeError exception.
  if (y->is_zero()) {
    THROW_NEW_ERROR(isolate, NewRangeError(MessageTemplate::kBigIntDivZero));
  }
  // 2. Return the BigInt representing x modulo y.
  // See https://github.com/tc39/proposal-bigint/issues/84 though.
  if (bigint::Compare(x->digits(), y->digits()) < 0)
    return indirect_handle(x, isolate);
  if (y->length() == 1 && y->digit(0) == 1) return Zero(isolate);
  Handle<MutableBigInt> remainder;
  uint32_t result_length = bigint::ModuloResultLength(y->digits());
  if (!MutableBigInt::New(isolate, result_length).ToHandle(&remainder)) {
    return {};
  }
  DisallowGarbageCollection no_gc;
  bigint::Status status = isolate->bigint_processor()->Modulo(
      remainder->rw_digits(), x->digits(), y->digits());
  if (status == bigint::Status::kInterrupted) {
    AllowGarbageCollection terminating_anyway;
    isolate->TerminateExecution();
    return {};
  }
  remainder->set_sign(x->sign());
  return MutableBigInt::MakeImmutable(remainder);
}
References v8::internal::Isolate::bigint_processor(), v8::bigint::Compare(), v8::internal::indirect_handle(), v8::bigint::kInterrupted, v8::internal::MutableBigInt::MakeImmutable(), v8::bigint::Processor::Modulo(), v8::bigint::ModuloResultLength(), v8::internal::MutableBigInt::New(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::status, v8::internal::Isolate::TerminateExecution(), THROW_NEW_ERROR, v8::anonymous_namespace{api.cc}::ToHandle(), v8::internal::y, and Zero().
Referenced by v8::internal::anonymous_namespace{intl-objects.cc}::ApproximateMillisecondEpoch().
SerializeDigits()
void v8::internal::BigInt::SerializeDigits (uint8_t * storage, size_t storage_length) [private]
Definition at line 1228 of file bigint.cc.
                                                                    {
  size_t num_digits_to_write = storage_length / kDigitSize;
  // {storage_length} should have been computed from {length()}.
  DCHECK_EQ(num_digits_to_write, length());
#if defined(V8_TARGET_LITTLE_ENDIAN)
  memcpy(storage, raw_digits(), num_digits_to_write * kDigitSize);
#elif defined(V8_TARGET_BIG_ENDIAN)
  digit_t* digit_storage = reinterpret_cast<digit_t*>(storage);
  const digit_t* digit = reinterpret_cast<const digit_t*>(raw_digits());
  for (size_t i = 0; i < num_digits_to_write; i++) {
    *digit_storage = ByteReverse(*digit);
    digit_storage++;
    digit++;
  }
#endif // V8_TARGET_BIG_ENDIAN
}
References v8::internal::ByteReverse(), DCHECK_EQ, v8::internal::BigIntBase::digit(), v8::internal::BigIntBase::kDigitSize, and v8::internal::BigIntBase::length().
SizeFor()
static uint32_t v8::internal::BigInt::SizeFor (uint32_t length) [inline], [static]
Definition at line 252 of file bigint.h.
                                                  {
    return sizeof(BigInt) + length * kDigitSize;
  }
References v8::internal::BigIntBase::kDigitSize, and v8::internal::BigIntBase::length().
Referenced by v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::AllocateBigInt(), v8::internal::MutableBigInt::Canonicalize(), v8::internal::compiler::AccessBuilder::ForBigIntLeastSignificantDigit64(), v8::internal::FactoryBase< Impl >::NewBigInt(), v8::internal::HeapObject::SizeFromMap(), and v8::internal::BigInt::BodyDescriptor< HandleType >::SizeOf().
Subtract()
MaybeHandle< BigInt > v8::internal::BigInt::Subtract (Isolate * isolate, DirectHandle< BigInt > x, DirectHandle< BigInt > y) [static]
Definition at line 532 of file bigint.cc.
                                                             {
  if (y->is_zero()) return indirect_handle(x, isolate);
  if (x->is_zero()) return UnaryMinus(isolate, y);
  bool xsign = x->sign();
  bool ysign = y->sign();
  uint32_t result_length = bigint::SubtractSignedResultLength(
      x->length(), y->length(), xsign == ysign);
  Handle<MutableBigInt> result;
  if (!MutableBigInt::New(isolate, result_length).ToHandle(&result)) {
    // Allocation fails when {result_length} exceeds the max BigInt size.
    return {};
  }
  DisallowGarbageCollection no_gc;
  bool result_sign = bigint::SubtractSigned(result->rw_digits(), x->digits(),
                                            xsign, y->digits(), ysign);
  result->set_sign(result_sign);
  return MutableBigInt::MakeImmutable(result);
}
References v8::internal::indirect_handle(), v8::internal::MutableBigInt::MakeImmutable(), v8::internal::MutableBigInt::New(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, v8::bigint::SubtractSigned(), v8::bigint::SubtractSignedResultLength(), v8::anonymous_namespace{api.cc}::ToHandle(), UnaryMinus(), and v8::internal::y.
ToBoolean()
bool v8::internal::BigInt::ToBoolean () [inline]
Definition at line 213 of file bigint.h.
{ return !is_zero(); }
References v8::internal::BigIntBase::is_zero().
ToNumber()
DirectHandle< Number > v8::internal::BigInt::ToNumber (Isolate * isolate, DirectHandle< BigInt > x) [static]
Definition at line 1019 of file bigint.cc.
                                                              {
  if (x->is_zero()) return direct_handle(Smi::zero(), isolate);
  if (x->length() == 1 && x->digit(0) < Smi::kMaxValue) {
    int value = static_cast<int>(x->digit(0));
    if (x->sign()) value = -value;
    return direct_handle(Smi::FromInt(value), isolate);
  }
  double result = MutableBigInt::ToDouble(x);
  return isolate->factory()->NewHeapNumber(result);
}
References v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::Smi::FromInt(), v8::internal::Smi::kMaxValue, v8::internal::FactoryBase< Impl >::NewHeapNumber(), v8::base::internal::result, v8::internal::MutableBigInt::ToDouble(), v8::internal::value, and v8::internal::Smi::zero().
Referenced by v8::internal::RUNTIME_FUNCTION().
ToString()
MaybeHandle< String > v8::internal::BigInt::ToString (Isolate * isolate, DirectHandle< BigInt > bigint, int radix = 10, ShouldThrow should_throw = kThrowOnError) [static]
Definition at line 831 of file bigint.cc.
                                                               {
  if (bigint->is_zero()) {
    return isolate->factory()->zero_string();
  }
  const bool sign = bigint->sign();
  uint32_t chars_allocated;
  uint32_t chars_written;
  Handle<SeqOneByteString> result;
  if (bigint->length() == 1 && radix == 10) {
    // Fast path for the most common case, to avoid call/dispatch overhead.
    // The logic is the same as what the full implementation does below,
    // just inlined and specialized for the preconditions.
    // Microbenchmarks rejoice!
    digit_t digit = bigint->digit(0);
    uint32_t bit_length = kDigitBits - base::bits::CountLeadingZeros(digit);
    constexpr uint32_t kShift = 7;
    // This is Math.log2(10) * (1 << kShift), scaled just far enough to
    // make the computations below always precise (after rounding).
    constexpr uint32_t kShiftedBitsPerChar = 425;
    chars_allocated = (bit_length << kShift) / kShiftedBitsPerChar + 1 + sign;
    result = isolate->factory()
                 ->NewRawOneByteString(chars_allocated)
                 .ToHandleChecked();
    DisallowGarbageCollection no_gc;
    uint8_t* start = result->GetChars(no_gc);
    uint8_t* out = start + chars_allocated;
    while (digit != 0) {
      *(--out) = '0' + (digit % 10);
      digit /= 10;
    }
    if (sign) *(--out) = '-';
    if (out == start) {
      chars_written = chars_allocated;
    } else {
      DCHECK_LT(start, out);
      // The result is one character shorter than predicted. This is
      // unavoidable, e.g. a 4-bit BigInt can be as big as "10" or as small as
      // "9", so we must allocate 2 characters for it, and will only later find
      // out whether all characters were used.
      chars_written = chars_allocated - static_cast<uint32_t>(out - start);
      std::memmove(start, out, chars_written);
      memset(start + chars_written, 0, chars_allocated - chars_written);
    }
  } else {
    // Generic path, handles anything.
    DCHECK(radix >= 2 && radix <= 36);
    chars_allocated =
        bigint::ToStringResultLength(bigint->digits(), radix, sign);
    if (chars_allocated > String::kMaxLength) {
      if (should_throw == kThrowOnError) {
        THROW_NEW_ERROR(isolate, NewInvalidStringLengthError());
      } else {
        return {};
      }
    }
    result = isolate->factory()
                 ->NewRawOneByteString(chars_allocated)
                 .ToHandleChecked();
    chars_written = chars_allocated;
    DisallowGarbageCollection no_gc;
    char* characters = reinterpret_cast<char*>(result->GetChars(no_gc));
    bigint::Status status = isolate->bigint_processor()->ToString(
        characters, &chars_written, bigint->digits(), radix, sign);
    if (status == bigint::Status::kInterrupted) {
      AllowGarbageCollection terminating_anyway;
      isolate->TerminateExecution();
      return {};
    }
  }
  // Right-trim any over-allocation (which can happen due to conservative
  // estimates).
  RightTrimString(isolate, result, chars_allocated, chars_written);
#if DEBUG
  // Verify that all characters have been written.
  DCHECK(result->length() == chars_written);
  DisallowGarbageCollection no_gc;
  uint8_t* chars = result->GetChars(no_gc);
  for (uint32_t i = 0; i < chars_written; i++) {
    DCHECK_NE(chars[i], bigint::kStringZapValue);
  }
#endif
  return result;
}
References v8::internal::Isolate::bigint_processor(), v8::base::bits::CountLeadingZeros(), v8::internal::DCHECK(), DCHECK_LT, DCHECK_NE, v8::internal::BigIntBase::digit(), v8::internal::Isolate::factory(), v8::internal::BigIntBase::kDigitBits, v8::bigint::kInterrupted, v8::internal::String::kMaxLength, v8::bigint::kStringZapValue, v8::internal::kThrowOnError, v8::internal::FactoryBase< Impl >::NewRawOneByteString(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, v8::internal::anonymous_namespace{bigint.cc}::RightTrimString(), v8::internal::BigIntBase::sign(), v8::internal::status, v8::internal::Isolate::TerminateExecution(), THROW_NEW_ERROR, v8::bigint::Processor::ToString(), and v8::bigint::ToStringResultLength().
Referenced by v8::internal::anonymous_namespace{builtins-bigint.cc}::BigIntToStringImpl(), v8::debug::anonymous_namespace{debug-interface.cc}::GetBigIntStringPresentationHandle(), v8::internal::anonymous_namespace{js-number-format.cc}::IcuFormatNumber(), and v8::internal::IntlMathematicalValue::ToString().
ToWordsArray64()
void v8::internal::BigInt::ToWordsArray64 (int * sign_bit, uint32_t * words64_count, uint64_t * words)
Definition at line 1400 of file bigint.cc.
                                             {
  DCHECK_NE(sign_bit, nullptr);
  DCHECK_NE(words64_count, nullptr);
  *sign_bit = sign();
  uint32_t available_words = *words64_count;
  *words64_count = Words64Count();
  if (available_words == 0) return;
  DCHECK_NE(words, nullptr);
  uint32_t len = length();
  if (kDigitBits == 64) {
    for (uint32_t i = 0; i < len && i < available_words; ++i)
      words[i] = digit(i);
  } else {
    for (uint32_t i = 0; i < len && available_words > 0; i += 2) {
      uint64_t lo = digit(i);
      uint64_t hi = (i + 1) < len ? digit(i + 1) : 0;
      words[i / 2] = lo | (hi << 32);
      available_words--;
    }
  }
}
References DCHECK_NE, v8::internal::BigIntBase::digit(), v8::internal::hi, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::BigIntBase::kDigitBits, v8::internal::BigIntBase::length(), v8::internal::lo, v8::internal::BigIntBase::sign(), and Words64Count().
UnaryMinus()
Handle< BigInt > v8::internal::BigInt::UnaryMinus (Isolate * isolate, DirectHandle< BigInt > x) [static]
Definition at line 337 of file bigint.cc.
                                                                          {
  // Special case: There is no -0n.
  if (x->is_zero()) return indirect_handle(x, isolate);
  Handle<MutableBigInt> result = MutableBigInt::Copy(isolate, x);
  result->set_sign(!x->sign());
  return MutableBigInt::MakeImmutable(result);
}
References v8::internal::MutableBigInt::Copy(), v8::internal::indirect_handle(), v8::internal::MutableBigInt::MakeImmutable(), and v8::base::internal::result.
Referenced by Divide(), Exponentiate(), v8::internal::RUNTIME_FUNCTION(), and Subtract().
Words64Count()
uint32_t v8::internal::BigInt::Words64Count ()
Definition at line 1394 of file bigint.cc.
                              {
  static_assert(kDigitBits == 64 || kDigitBits == 32);
  return length() / (64 / kDigitBits) +
         (kDigitBits == 32 && length() % 2 == 1 ? 1 : 0);
}
References v8::internal::BigIntBase::kDigitBits, and v8::internal::BigIntBase::length().
Referenced by ToWordsArray64().
Zero()
template<typename IsolateT >
template Handle< BigInt > v8::internal::BigInt::Zero (IsolateT * isolate, AllocationType allocation = AllocationType::kYoung) [static], [private]
Definition at line 329 of file bigint.cc.
                                                                        {
  return MutableBigInt::Zero(isolate, allocation);
}
References v8::internal::MutableBigInt::Zero().
Referenced by Divide(), v8::internal::StringToBigIntHelper< IsolateT >::GetResult(), and Remainder().
Friends And Related Function Documentation
StringToBigIntHelper
template<typename IsolateT >
friend class StringToBigIntHelper [friend]
Definition at line 287 of file bigint.h.
ValueDeserializer
friend class ValueDeserializer [friend]
Definition at line 288 of file bigint.h.
ValueSerializer
friend class ValueSerializer [friend]
Definition at line 289 of file bigint.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/bigint.h
/mnt/V8SourceCode/src/objects/bigint.cc