v8::internal::BreakPointInfo Class Reference
#include <debug-objects.h>
Public Types
using BodyDescriptor = StructBodyDescriptor
Public Member Functions
int GetBreakPointCount (Isolate *isolate)
int GetStatementPosition (Handle< DebugInfo > debug_info)
Static Public Member Functions
static void ClearBreakPoint (Isolate *isolate, DirectHandle< BreakPointInfo > info, DirectHandle< BreakPoint > break_point)
static void SetBreakPoint (Isolate *isolate, DirectHandle< BreakPointInfo > info, DirectHandle< BreakPoint > break_point)
static bool HasBreakPoint (Isolate *isolate, DirectHandle< BreakPointInfo > info, DirectHandle< BreakPoint > break_point)
static MaybeDirectHandle< BreakPoint > GetBreakPointById (Isolate *isolate, DirectHandle< BreakPointInfo > info, int breakpoint_id)
Detailed Description
Definition at line 152 of file debug-objects.h.
Member Typedef Documentation
BodyDescriptor
using v8::internal::BreakPointInfo::BodyDescriptor = StructBodyDescriptor
Definition at line 173 of file debug-objects.h.
Member Function Documentation
ClearBreakPoint()
void v8::internal::BreakPointInfo::ClearBreakPoint (Isolate * isolate, DirectHandle< BreakPointInfo > info, DirectHandle< BreakPoint > break_point) [static]
Definition at line 245 of file debug-objects.cc.
                                          {
  // If there are no break points just ignore.
  if (IsUndefined(break_point_info->break_points(), isolate)) return;
  // If there is a single break point clear it if it is the same.
  if (!IsFixedArray(break_point_info->break_points())) {
    if (IsEqual(Cast<BreakPoint>(break_point_info->break_points()),
                *break_point)) {
      break_point_info->set_break_points(
          ReadOnlyRoots(isolate).undefined_value());
    }
    return;
  }
  // If there are multiple break points shrink the array
  DCHECK(IsFixedArray(break_point_info->break_points()));
  DirectHandle<FixedArray> old_array(
      Cast<FixedArray>(break_point_info->break_points()), isolate);
  DirectHandle<FixedArray> new_array =
      isolate->factory()->NewFixedArray(old_array->length() - 1);
  int found_count = 0;
  for (int i = 0; i < old_array->length(); i++) {
    if (IsEqual(Cast<BreakPoint>(old_array->get(i)), *break_point)) {
      DCHECK_EQ(found_count, 0);
      found_count++;
    } else {
      new_array->set(i - found_count, old_array->get(i));
    }
  }
  // If the break point was found in the list change it.
  if (found_count > 0) break_point_info->set_break_points(*new_array);
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{debug-objects.cc}::IsEqual(), and v8::internal::FactoryBase< Impl >::NewFixedArray().
Referenced by v8::internal::WasmScript::ClearBreakPoint(), and v8::internal::DebugInfo::ClearBreakPoint().
GetBreakPointById()
MaybeDirectHandle< BreakPoint > v8::internal::BreakPointInfo::GetBreakPointById (Isolate * isolate, DirectHandle< BreakPointInfo > info, int breakpoint_id) [static]
Definition at line 337 of file debug-objects.cc.
                       {
  // No break point.
  if (IsUndefined(break_point_info->break_points(), isolate)) {
    return MaybeDirectHandle<BreakPoint>();
  }
  // Single break point.
  if (!IsFixedArray(break_point_info->break_points())) {
    Tagged<BreakPoint> breakpoint =
        Cast<BreakPoint>(break_point_info->break_points());
    if (breakpoint->id() == breakpoint_id) {
      return direct_handle(breakpoint, isolate);
    }
  } else {
    // Multiple break points.
    Tagged<FixedArray> array =
        Cast<FixedArray>(break_point_info->break_points());
    for (int i = 0; i < array->length(); i++) {
      Tagged<BreakPoint> breakpoint = Cast<BreakPoint>(array->get(i));
      if (breakpoint->id() == breakpoint_id) {
        return direct_handle(breakpoint, isolate);
      }
    }
  }
  return MaybeDirectHandle<BreakPoint>();
}
References v8::internal::direct_handle().
Referenced by v8::internal::WasmScript::ClearBreakPointById().
GetBreakPointCount()
int v8::internal::BreakPointInfo::GetBreakPointCount (Isolate * isolate)
Definition at line 366 of file debug-objects.cc.
                                                       {
  // No break point.
  if (IsUndefined(break_points(), isolate)) return 0;
  // Single break point.
  if (!IsFixedArray(break_points())) return 1;
  // Multiple break points.
  return Cast<FixedArray>(break_points())->length();
}
GetStatementPosition()
int v8::internal::BreakPointInfo::GetStatementPosition (Handle< DebugInfo > debug_info)
HasBreakPoint()
bool v8::internal::BreakPointInfo::HasBreakPoint (Isolate * isolate, DirectHandle< BreakPointInfo > info, DirectHandle< BreakPoint > break_point) [static]
Definition at line 315 of file debug-objects.cc.
                                          {
  // No break point.
  if (IsUndefined(break_point_info->break_points(), isolate)) {
    return false;
  }
  // Single break point.
  if (!IsFixedArray(break_point_info->break_points())) {
    return IsEqual(Cast<BreakPoint>(break_point_info->break_points()),
                   *break_point);
  }
  // Multiple break points.
  Tagged<FixedArray> array = Cast<FixedArray>(break_point_info->break_points());
  for (int i = 0; i < array->length(); i++) {
    if (IsEqual(Cast<BreakPoint>(array->get(i)), *break_point)) {
      return true;
    }
  }
  return false;
}
References v8::internal::anonymous_namespace{debug-objects.cc}::IsEqual().
Referenced by v8::internal::DebugInfo::ClearBreakPoint(), and v8::internal::DebugInfo::FindBreakPointInfo().
SetBreakPoint()
void v8::internal::BreakPointInfo::SetBreakPoint (Isolate * isolate, DirectHandle< BreakPointInfo > info, DirectHandle< BreakPoint > break_point) [static]
Definition at line 279 of file debug-objects.cc.
                                          {
  // If there was no break point objects before just set it.
  if (IsUndefined(break_point_info->break_points(), isolate)) {
    break_point_info->set_break_points(*break_point);
    return;
  }
  // If there was one break point object before replace with array.
  if (!IsFixedArray(break_point_info->break_points())) {
    if (IsEqual(Cast<BreakPoint>(break_point_info->break_points()),
                *break_point)) {
      return;
    }
    DirectHandle<FixedArray> array = isolate->factory()->NewFixedArray(2);
    array->set(0, break_point_info->break_points());
    array->set(1, *break_point);
    break_point_info->set_break_points(*array);
    return;
  }
  // If there was more than one break point before extend array.
  DirectHandle<FixedArray> old_array(
      Cast<FixedArray>(break_point_info->break_points()), isolate);
  DirectHandle<FixedArray> new_array =
      isolate->factory()->NewFixedArray(old_array->length() + 1);
  for (int i = 0; i < old_array->length(); i++) {
    // If the break point was there before just ignore.
    if (IsEqual(Cast<BreakPoint>(old_array->get(i)), *break_point)) return;
    new_array->set(i, old_array->get(i));
  }
  // Add the new break point.
  new_array->set(old_array->length(), *break_point);
  break_point_info->set_break_points(*new_array);
}
References v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{debug-objects.cc}::IsEqual(), and v8::internal::FactoryBase< Impl >::NewFixedArray().
Referenced by v8::internal::WasmScript::AddBreakpointToInfo(), and v8::internal::DebugInfo::SetBreakPoint().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/debug-objects.h
/mnt/V8SourceCode/src/objects/debug-objects.cc