v8::internal::anonymous_namespace{isolate.cc}::StackFrameSummaryIterator Class Reference
Public Member Functions
StackFrameSummaryIterator (Isolate *isolate)
void Advance ()
bool done () const
StackFrame * frame () const
bool has_frame_summary () const
const FrameSummary & frame_summary () const
Isolate * isolate () const
Private Member Functions
void InitSummaries ()
Private Attributes
StackFrameIterator stack_iterator_
FrameSummaries summaries_
int index_
Detailed Description
Definition at line 2750 of file isolate.cc.
Constructor & Destructor Documentation
StackFrameSummaryIterator()
v8::internal::anonymous_namespace{isolate.cc}::StackFrameSummaryIterator::StackFrameSummaryIterator (Isolate * isolate) [inline], [explicit]
Definition at line 2752 of file isolate.cc.
      : stack_iterator_(isolate), summaries_(), index_(0) {
    InitSummaries();
  }
Member Function Documentation
Advance()
void v8::internal::anonymous_namespace{isolate.cc}::StackFrameSummaryIterator::Advance () [inline]
Definition at line 2756 of file isolate.cc.
                 {
    if (index_ == 0) {
      summaries_.frames.clear();
      stack_iterator_.Advance();
      InitSummaries();
    } else {
      index_--;
    }
  }
done()
bool v8::internal::anonymous_namespace{isolate.cc}::StackFrameSummaryIterator::done () const [inline]
Definition at line 2765 of file isolate.cc.
{ return stack_iterator_.done(); }
frame()
StackFrame* v8::internal::anonymous_namespace{isolate.cc}::StackFrameSummaryIterator::frame () const [inline]
Definition at line 2766 of file isolate.cc.
{ return stack_iterator_.frame(); }
Referenced by v8::internal::anonymous_namespace{isolate.cc}::CallsCatchMethod(), and v8::internal::anonymous_namespace{isolate.cc}::PredictExceptionCatchAtFrame().
frame_summary()
const FrameSummary& v8::internal::anonymous_namespace{isolate.cc}::StackFrameSummaryIterator::frame_summary () const [inline]
Definition at line 2768 of file isolate.cc.
                                            {
    DCHECK(has_frame_summary());
    return summaries_.frames[index_];
  }
References v8::internal::DCHECK().
Referenced by v8::internal::anonymous_namespace{isolate.cc}::CallsCatchMethod(), and v8::internal::anonymous_namespace{isolate.cc}::PredictExceptionCatchAtFrame().
has_frame_summary()
bool v8::internal::anonymous_namespace{isolate.cc}::StackFrameSummaryIterator::has_frame_summary () const [inline]
Definition at line 2767 of file isolate.cc.
{ return index_ < summaries_.size(); }
Referenced by v8::internal::anonymous_namespace{isolate.cc}::PredictExceptionCatchAtFrame().
InitSummaries()
void v8::internal::anonymous_namespace{isolate.cc}::StackFrameSummaryIterator::InitSummaries () [inline], [private]
Definition at line 2775 of file isolate.cc.
                       {
    if (!done() && frame()->is_javascript()) {
      summaries_ = JavaScriptFrame::cast(frame())->Summarize();
      DCHECK_GT(summaries_.size(), 0);
      index_ = summaries_.size() - 1;
    }
  }
References v8::internal::JavaScriptFrame::cast(), DCHECK_GT, and v8::internal::CommonFrameWithJSLinkage::Summarize().
isolate()
Isolate* v8::internal::anonymous_namespace{isolate.cc}::StackFrameSummaryIterator::isolate () const [inline]
Definition at line 2772 of file isolate.cc.
{ return stack_iterator_.isolate(); }
References v8::internal::Factory::isolate().
Referenced by v8::internal::anonymous_namespace{isolate.cc}::CallsCatchMethod(), and v8::internal::anonymous_namespace{isolate.cc}::PredictExceptionCatchAtFrame().
Member Data Documentation
index_
int v8::internal::anonymous_namespace{isolate.cc}::StackFrameSummaryIterator::index_ [private]
Definition at line 2784 of file isolate.cc.
stack_iterator_
StackFrameIterator v8::internal::anonymous_namespace{isolate.cc}::StackFrameSummaryIterator::stack_iterator_ [private]
Definition at line 2782 of file isolate.cc.
summaries_
FrameSummaries v8::internal::anonymous_namespace{isolate.cc}::StackFrameSummaryIterator::summaries_ [private]
Definition at line 2783 of file isolate.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/execution/isolate.cc