v8::debug::EphemeronTable Class Reference
#include <debug-interface.h>
Public Member Functions
EphemeronTable ()=delete
V8_EXPORT_PRIVATE V8_WARN_UNUSED_RESULT v8::MaybeLocal< v8::Value > Get (v8::Isolate *isolate, v8::Local< v8::Value > key)
V8_EXPORT_PRIVATE V8_WARN_UNUSED_RESULT v8::Local< EphemeronTable > Set (v8::Isolate *isolate, v8::Local< v8::Value > key, v8::Local< v8::Value > value)
Static Public Member Functions
static V8_EXPORT_PRIVATE Local< EphemeronTable > New (v8::Isolate *isolate)
static EphemeronTable * Cast (Value *obj)
Additional Inherited Members
Detailed Description
Definition at line 603 of file debug-interface.h.
Constructor & Destructor Documentation
EphemeronTable()
v8::debug::EphemeronTable::EphemeronTable () [delete]
Member Function Documentation
Cast()
static EphemeronTable* v8::debug::EphemeronTable::Cast (Value * obj) [inline], [static]
Definition at line 613 of file debug-interface.h.
                                                    {
    return static_cast<EphemeronTable*>(obj);
  }
Get()
MaybeLocal< v8::Value > v8::debug::EphemeronTable::Get (v8::Isolate * isolate, v8::Local< v8::Value > key)
Definition at line 1401 of file debug-interface.cc.
                                                                {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(isolate);
  auto self = i::Cast<i::EphemeronHashTable>(Utils::OpenDirectHandle(this));
  i::DirectHandle<i::Object> internal_key = Utils::OpenDirectHandle(*key);
  DCHECK(IsJSReceiver(*internal_key));
  i::DirectHandle<i::Object> value(self->Lookup(internal_key), i_isolate);
  if (IsTheHole(*value)) return {};
  return Utils::ToLocal(value);
}
References DCHECK, v8::internal::key, v8::Utils::OpenDirectHandle(), and v8::internal::value.
New()
Local< EphemeronTable > v8::debug::EphemeronTable::New (v8::Isolate * isolate) [static]
Definition at line 1428 of file debug-interface.cc.
                                                            {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(isolate);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::DirectHandle<i::EphemeronHashTable> table =
      i::EphemeronHashTable::New(i_isolate, 0);
  return ToApiHandle<EphemeronTable>(table);
}
References v8::internal::anonymous_namespace{intl-objects.cc}::New().
Referenced by v8_inspector::InspectedContext::addInternalObject(), and v8_inspector::V8InspectorImpl::associateExceptionData().
Set()
Local< EphemeronTable > v8::debug::EphemeronTable::Set (v8::Isolate * isolate, v8::Local< v8::Value > key, v8::Local< v8::Value > value)
Definition at line 1414 of file debug-interface.cc.
                                                                  {
  auto self = i::Cast<i::EphemeronHashTable>(Utils::OpenHandle(this));
  i::DirectHandle<i::Object> internal_key = Utils::OpenDirectHandle(*key);
  i::DirectHandle<i::Object> internal_value = Utils::OpenDirectHandle(*value);
  DCHECK(IsJSReceiver(*internal_key));
  i::DirectHandle<i::EphemeronHashTable> result(
      i::EphemeronHashTable::Put(self, internal_key, internal_value));
  return ToApiHandle<EphemeronTable>(result);
}
References DCHECK, v8::internal::key, v8::Utils::OpenDirectHandle(), v8::Utils::OpenHandle(), v8::base::internal::result, and v8::internal::value.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/debug/debug-interface.h
/mnt/V8SourceCode/src/debug/debug-interface.cc