v8::Platform Class Reference
V8 Platform abstraction layer.
#include <v8-platform.h>
Public Types
typedef void(* StackTracePrinter) ()
Public Member Functions
virtual ~Platform ()=default
virtual PageAllocator * GetPageAllocator ()
Allows the embedder to manage memory page allocations.
virtual ThreadIsolatedAllocator * GetThreadIsolatedAllocator ()
Allows the embedder to provide an allocator that uses per-thread memory permissions to protect allocations.
virtual void OnCriticalMemoryPressure ()
Enables the embedder to respond in cases where V8 can't allocate large blocks of memory.
virtual int NumberOfWorkerThreads ()=0
Gets the max number of worker threads that may be used to execute concurrent work scheduled for any single TaskPriority by Call(BlockingTask)OnWorkerThread() or PostJob().
std::shared_ptr< v8::TaskRunner > GetForegroundTaskRunner (Isolate *isolate)
Returns a TaskRunner which can be used to post a task on the foreground.
virtual std::shared_ptr< v8::TaskRunner > GetForegroundTaskRunner (Isolate *isolate, TaskPriority priority)=0
Returns a TaskRunner with a specific |priority| which can be used to post a task on the foreground thread.
Use PostTaskOnWorkerThread instead void CallOnWorkerThread (std::unique_ptr< Task > task, const SourceLocation &location=SourceLocation::Current())
Schedules a task to be invoked on a worker thread.
Use PostTaskOnWorkerThread instead void CallBlockingTaskOnWorkerThread (std::unique_ptr< Task > task, const SourceLocation &location=SourceLocation::Current())
Schedules a task that blocks the main thread to be invoked with high-priority on a worker thread.
Use PostTaskOnWorkerThread instead void CallLowPriorityTaskOnWorkerThread (std::unique_ptr< Task > task, const SourceLocation &location=SourceLocation::Current())
Schedules a task to be invoked with low-priority on a worker thread.
Use PostDelayedTaskOnWorkerThread instead void CallDelayedOnWorkerThread (std::unique_ptr< Task > task, double delay_in_seconds, const SourceLocation &location=SourceLocation::Current())
Schedules a task to be invoked on a worker thread after |delay_in_seconds| expires.
void PostTaskOnWorkerThread (TaskPriority priority, std::unique_ptr< Task > task, const SourceLocation &location=SourceLocation::Current())
Schedules a task to be invoked on a worker thread.
void PostDelayedTaskOnWorkerThread (TaskPriority priority, std::unique_ptr< Task > task, double delay_in_seconds, const SourceLocation &location=SourceLocation::Current())
Schedules a task to be invoked on a worker thread after |delay_in_seconds| expires.
virtual bool IdleTasksEnabled (Isolate *isolate)
Returns true if idle tasks are enabled for the given |isolate|.
std::unique_ptr< JobHandle > PostJob (TaskPriority priority, std::unique_ptr< JobTask > job_task, const SourceLocation &location=SourceLocation::Current())
Posts |job_task| to run in parallel.
std::unique_ptr< JobHandle > CreateJob (TaskPriority priority, std::unique_ptr< JobTask > job_task, const SourceLocation &location=SourceLocation::Current())
Creates and returns a JobHandle associated with a Job.
virtual std::unique_ptr< ScopedBlockingCall > CreateBlockingScope (BlockingType blocking_type)
Instantiates a ScopedBlockingCall to annotate a scope that may/will block.
virtual double MonotonicallyIncreasingTime ()=0
Monotonically increasing time in seconds from an arbitrary fixed point in the past.
virtual int64_t CurrentClockTimeMilliseconds ()
Current wall-clock time in milliseconds since epoch.
virtual double CurrentClockTimeMillis ()=0
This function is deprecated and will be deleted.
virtual double CurrentClockTimeMillisecondsHighResolution ()
Same as CurrentClockTimeMilliseconds(), but with more precision.
virtual StackTracePrinter GetStackTracePrinter ()
Returns a function pointer that print a stack trace of the current stack on invocation.
virtual TracingController * GetTracingController ()=0
Returns an instance of a v8::TracingController.
virtual void DumpWithoutCrashing ()
Tells the embedder to generate and upload a crashdump during an unexpected but non-critical scenario.
virtual HighAllocationThroughputObserver * GetHighAllocationThroughputObserver ()
Allows the embedder to observe sections with high throughput allocation operations.
Protected Member Functions
virtual std::unique_ptr< JobHandle > CreateJobImpl (TaskPriority priority, std::unique_ptr< JobTask > job_task, const SourceLocation &location)=0
Creates and returns a JobHandle associated with a Job.
virtual void PostTaskOnWorkerThreadImpl (TaskPriority priority, std::unique_ptr< Task > task, const SourceLocation &location)=0
Schedules a task with |priority| to be invoked on a worker thread.
virtual void PostDelayedTaskOnWorkerThreadImpl (TaskPriority priority, std::unique_ptr< Task > task, double delay_in_seconds, const SourceLocation &location)=0
Schedules a task with |priority| to be invoked on a worker thread after |delay_in_seconds| expires.
Static Protected Member Functions
static double SystemClockTimeMillis ()
Default implementation of current wall-clock time in milliseconds since epoch.
Detailed Description
V8 Platform abstraction layer.
The embedder has to provide an implementation of this interface before initializing the rest of V8.
Definition at line 1097 of file v8-platform.h.
Member Typedef Documentation
StackTracePrinter
typedef void(* v8::Platform::StackTracePrinter) ()
Definition at line 1356 of file v8-platform.h.
Constructor & Destructor Documentation
 Platform()
virtual v8::Platform::~Platform () [virtual], [default]
Member Function Documentation
CallBlockingTaskOnWorkerThread()
Use PostTaskOnWorkerThread instead void v8::Platform::CallBlockingTaskOnWorkerThread (std::unique_ptr< Task > task, const SourceLocation & location = SourceLocation::Current()) [inline]
Schedules a task that blocks the main thread to be invoked with high-priority on a worker thread.
Embedders should override PostTaskOnWorkerThreadImpl() instead of CallBlockingTaskOnWorkerThread().
Definition at line 1173 of file v8-platform.h.
                                                                {
    // Embedders may optionally override this to process these tasks in a high
    // priority pool.
    PostTaskOnWorkerThreadImpl(TaskPriority::kUserBlocking, std::move(task),
                               location);
  }
References v8::kUserBlocking, and PostTaskOnWorkerThreadImpl().
CallDelayedOnWorkerThread()
Use PostDelayedTaskOnWorkerThread instead void v8::Platform::CallDelayedOnWorkerThread (std::unique_ptr< Task > task, double delay_in_seconds, const SourceLocation & location = SourceLocation::Current()) [inline]
Schedules a task to be invoked on a worker thread after |delay_in_seconds| expires.
Embedders should override PostDelayedTaskOnWorkerThreadImpl() instead of CallDelayedOnWorkerThread().
Definition at line 1204 of file v8-platform.h.
                                                                {
    PostDelayedTaskOnWorkerThreadImpl(TaskPriority::kUserVisible,
                                      std::move(task), delay_in_seconds,
                                      location);
  }
References v8::kUserVisible, and PostDelayedTaskOnWorkerThreadImpl().
CallLowPriorityTaskOnWorkerThread()
Use PostTaskOnWorkerThread instead void v8::Platform::CallLowPriorityTaskOnWorkerThread (std::unique_ptr< Task > task, const SourceLocation & location = SourceLocation::Current()) [inline]
Schedules a task to be invoked with low-priority on a worker thread.
Embedders should override PostTaskOnWorkerThreadImpl() instead of CallLowPriorityTaskOnWorkerThread().
Definition at line 1188 of file v8-platform.h.
                                                                {
    // Embedders may optionally override this to process these tasks in a low
    // priority pool.
    PostTaskOnWorkerThreadImpl(TaskPriority::kBestEffort, std::move(task),
                               location);
  }
References v8::kBestEffort, and PostTaskOnWorkerThreadImpl().
CallOnWorkerThread()
Use PostTaskOnWorkerThread instead void v8::Platform::CallOnWorkerThread (std::unique_ptr< Task > task, const SourceLocation & location = SourceLocation::Current()) [inline]
Schedules a task to be invoked on a worker thread.
Embedders should override PostTaskOnWorkerThreadImpl() instead of CallOnWorkerThread().
Definition at line 1159 of file v8-platform.h.
                                                                {
    PostTaskOnWorkerThreadImpl(TaskPriority::kUserVisible, std::move(task),
                               location);
  }
References v8::kUserVisible, and PostTaskOnWorkerThreadImpl().
CreateBlockingScope()
virtual std::unique_ptr<ScopedBlockingCall> v8::Platform::CreateBlockingScope (BlockingType blocking_type) [inline], [virtual]
Instantiates a ScopedBlockingCall to annotate a scope that may/will block.
Definition at line 1319 of file v8-platform.h.
                                  {
    return nullptr;
  }
Referenced by v8::internal::IsolateSafepoint::Barrier::WaitInSafepoint(), and v8::internal::IsolateSafepoint::Barrier::WaitInUnpark().
CreateJob()
std::unique_ptr<JobHandle> v8::Platform::CreateJob (TaskPriority priority, std::unique_ptr< JobTask > job_task, const SourceLocation & location = SourceLocation::Current()) [inline]
Creates and returns a JobHandle associated with a Job.
Unlike PostJob(), this doesn't immediately schedules |worker_task| to run; the Job is then scheduled by calling either NotifyConcurrencyIncrease() or Join().
A sufficient CreateJob() implementation that uses the default Job provided in libplatform looks like: std::unique_ptr<JobHandle> CreateJob(TaskPriority priority, std::unique_ptr<JobTask> job_task) override { return v8::platform::NewDefaultJobHandle(this, priority, std::move(job_task), NumberOfWorkerThreads()); }
Embedders should override CreateJobImpl() instead of CreateJob().
Definition at line 1310 of file v8-platform.h.
                                                                {
    return CreateJobImpl(priority, std::move(job_task), location);
  }
References CreateJobImpl().
Referenced by v8::internal::MarkCompactCollector::ClearNonLiveReferences(), v8::internal::anonymous_namespace{mark-compact.cc}::CreateAndExecuteEvacuationTasks(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::InitCompileJob(), PostJob(), v8::internal::wasm::AsyncStreamingProcessor::ProcessFunctionBody(), v8::internal::wasm::NativeModuleDeserializer::Read(), v8::internal::anonymous_namespace{traced-handles.cc}::ParallelWeakHandlesProcessor< Derived >::Run(), v8::internal::MarkCompactCollector::UpdatePointersAfterEvacuation(), and v8::internal::wasm::ValidateFunctions().
CreateJobImpl()
virtual std::unique_ptr<JobHandle> v8::Platform::CreateJobImpl (TaskPriority priority, std::unique_ptr< JobTask > job_task, const SourceLocation & location) [protected], [pure virtual]
Creates and returns a JobHandle associated with a Job.
Implemented in v8::DelayedTasksPlatform, and v8::PredictablePlatform.
Referenced by CreateJob().
CurrentClockTimeMillis()
virtual double v8::Platform::CurrentClockTimeMillis () [pure virtual]
This function is deprecated and will be deleted.
Use either CurrentClockTimeMilliseconds() or CurrentClockTimeMillisecondsHighResolution().
Implemented in v8::DelayedTasksPlatform, and v8::PredictablePlatform.
Referenced by CurrentClockTimeMilliseconds(), and CurrentClockTimeMillisecondsHighResolution().
CurrentClockTimeMilliseconds()
virtual int64_t v8::Platform::CurrentClockTimeMilliseconds () [inline], [virtual]
Current wall-clock time in milliseconds since epoch.
Use CurrentClockTimeMillisHighResolution() when higher precision is required.
Definition at line 1338 of file v8-platform.h.
                                                 {
    return static_cast<int64_t>(floor(CurrentClockTimeMillis()));
  }
References CurrentClockTimeMillis().
Referenced by v8::internal::JSDate::CurrentTimeValue(), v8::internal::PrepareLogFileName(), and v8::internal::HeapProfiler::WriteSnapshotToDiskAfterGC().
CurrentClockTimeMillisecondsHighResolution()
virtual double v8::Platform::CurrentClockTimeMillisecondsHighResolution () [inline], [virtual]
Same as CurrentClockTimeMilliseconds(), but with more precision.
Definition at line 1352 of file v8-platform.h.
                                                              {
    return CurrentClockTimeMillis();
  }
References CurrentClockTimeMillis().
DumpWithoutCrashing()
virtual void v8::Platform::DumpWithoutCrashing () [inline], [virtual]
Tells the embedder to generate and upload a crashdump during an unexpected but non-critical scenario.
Definition at line 1373 of file v8-platform.h.
{}
Referenced by v8::internal::DeclarationScope::AllocateScopeInfos(), v8::internal::anonymous_namespace{execution.cc}::Invoke(), v8::internal::Isolate::PushParamsAndContinue(), and v8::internal::Isolate::PushStackTraceAndContinue().
GetForegroundTaskRunner() [1/2]
std::shared_ptr<v8::TaskRunner> v8::Platform::GetForegroundTaskRunner (Isolate * isolate) [inline]
Returns a TaskRunner which can be used to post a task on the foreground.
The TaskRunner's NonNestableTasksEnabled() must be true. This function should only be called from a foreground thread.
Definition at line 1141 of file v8-platform.h.
                                                                        {
    return GetForegroundTaskRunner(isolate, TaskPriority::kUserBlocking);
  }
References v8::kUserBlocking.
Referenced by v8::internal::CpuProfile::AddPath(), v8::internal::wasm::AsyncCompileJob::AsyncCompileJob(), v8::internal::detail::AsyncWaiterQueueNode< T >::AsyncWaiterQueueNode(), v8_inspector::V8HeapProfilerAgentImpl::collectGarbage(), v8::Worker::ExecuteInThread(), v8::internal::GCExtension::GC(), v8::internal::Heap::GetForegroundTaskRunner(), v8::internal::Isolate::Init(), v8::internal::wasm::WasmEngine::IsolateInfo::IsolateInfo(), v8::internal::TracingCpuProfilerImpl::OnTraceDisabled(), v8::internal::GlobalHandles::PostGarbageCollectionProcessing(), v8_inspector::InspectedContext::WeakCallbackData::resetContext(), v8::internal::metrics::Recorder::SetEmbedderRecorder(), v8::internal::Heap::SetUp(), and v8_inspector::V8HeapProfilerAgentImpl::takeHeapSnapshot().
GetForegroundTaskRunner() [2/2]
virtual std::shared_ptr<v8::TaskRunner> v8::Platform::GetForegroundTaskRunner (Isolate * isolate, TaskPriority priority) [pure virtual]
Returns a TaskRunner with a specific |priority| which can be used to post a task on the foreground thread.
The TaskRunner's NonNestableTasksEnabled() must be true. This function should only be called from a foreground thread.
Implemented in v8::DelayedTasksPlatform, and v8::PredictablePlatform.
GetHighAllocationThroughputObserver()
virtual HighAllocationThroughputObserver* v8::Platform::GetHighAllocationThroughputObserver () [inline], [virtual]
Allows the embedder to observe sections with high throughput allocation operations.
Definition at line 1380 of file v8-platform.h.
                                        {
    static HighAllocationThroughputObserver default_observer;
    return &default_observer;
  }
GetPageAllocator()
virtual PageAllocator* v8::Platform::GetPageAllocator () [inline], [virtual]
Allows the embedder to manage memory page allocations.
Returning nullptr will cause V8 to use the default page allocator.
Reimplemented in v8::DelayedTasksPlatform, and v8::PredictablePlatform.
Definition at line 1105 of file v8-platform.h.
{ return nullptr; }
Referenced by v8::internal::anonymous_namespace{allocation.cc}::PageAllocatorInitializer::PageAllocatorInitializer().
GetStackTracePrinter()
virtual StackTracePrinter v8::Platform::GetStackTracePrinter () [inline], [virtual]
Returns a function pointer that print a stack trace of the current stack on invocation.
Disables printing of the stack trace if nullptr.
Definition at line 1362 of file v8-platform.h.
{ return nullptr; }
Referenced by v8::internal::V8::InitializePlatform().
GetThreadIsolatedAllocator()
virtual ThreadIsolatedAllocator* v8::Platform::GetThreadIsolatedAllocator () [inline], [virtual]
Allows the embedder to provide an allocator that uses per-thread memory permissions to protect allocations.
Returning nullptr will cause V8 to disable protections that rely on this feature.
Reimplemented in v8::DelayedTasksPlatform, and v8::PredictablePlatform.
Definition at line 1113 of file v8-platform.h.
                                                                {
    return nullptr;
  }
GetTracingController()
virtual TracingController* v8::Platform::GetTracingController () [pure virtual]
Returns an instance of a v8::TracingController.
This must be non-nullptr.
Implemented in v8::DelayedTasksPlatform, and v8::PredictablePlatform.
Referenced by v8::internal::tracing::TraceEventHelper::GetTracingController(), v8::tracing::TracingCategoryObserver::SetUp(), v8::tracing::TracingCategoryObserver::TearDown(), v8::internal::TracingCpuProfilerImpl::TracingCpuProfilerImpl(), and v8::internal::TracingCpuProfilerImpl::~TracingCpuProfilerImpl().
IdleTasksEnabled()
virtual bool v8::Platform::IdleTasksEnabled (Isolate * isolate) [inline], [virtual]
Returns true if idle tasks are enabled for the given |isolate|.
Reimplemented in v8::DelayedTasksPlatform, and v8::PredictablePlatform.
Definition at line 1240 of file v8-platform.h.
{ return false; }
Referenced by v8::anonymous_namespace{d8.cc}::ProcessMessages().
MonotonicallyIncreasingTime()
virtual double v8::Platform::MonotonicallyIncreasingTime () [pure virtual]
Monotonically increasing time in seconds from an arbitrary fixed point in the past.
This function is expected to return at least millisecond-precision values. For this reason, it is recommended that the fixed point be no further in the past than the epoch.
Implemented in v8::DelayedTasksPlatform, and v8::PredictablePlatform.
Referenced by v8::internal::LazyCompileDispatcher::DoIdleWork(), v8::internal::LazyCompileDispatcher::FinishNow(), v8::internal::Heap::MonotonicallyIncreasingTimeInMs(), and v8::internal::TimedScope::TimestampMs().
NumberOfWorkerThreads()
virtual int v8::Platform::NumberOfWorkerThreads () [pure virtual]
Gets the max number of worker threads that may be used to execute concurrent work scheduled for any single TaskPriority by Call(BlockingTask)OnWorkerThread() or PostJob().
This can be used to estimate the number of tasks a work package should be split into. A return value of 0 means that there are no worker threads available. Note that a value of 0 won't prohibit V8 from posting tasks using |CallOnWorkerThread|.
Implemented in v8::DelayedTasksPlatform, and v8::PredictablePlatform.
Referenced by v8::internal::ConcurrentMarking::ConcurrentMarking(), v8::internal::OptimizingCompileTaskExecutor::EnsureStarted(), v8::internal::anonymous_namespace{mark-compact.cc}::NumberOfAvailableCores(), v8::internal::ScavengerCollector::NumberOfScavengeTasks(), and v8::internal::anonymous_namespace{mark-compact.cc}::TraceEvacuation().
OnCriticalMemoryPressure()
virtual void v8::Platform::OnCriticalMemoryPressure () [inline], [virtual]
Enables the embedder to respond in cases where V8 can't allocate large blocks of memory.
V8 retries the failed allocation once after calling this method. On success, execution continues; otherwise V8 exits with a fatal error. Embedder overrides of this function must NOT call back into V8.
Reimplemented in v8::DelayedTasksPlatform, and v8::PredictablePlatform.
Definition at line 1124 of file v8-platform.h.
{}
Referenced by v8::internal::OnCriticalMemoryPressure().
PostDelayedTaskOnWorkerThread()
void v8::Platform::PostDelayedTaskOnWorkerThread (TaskPriority priority, std::unique_ptr< Task > task, double delay_in_seconds, const SourceLocation & location = SourceLocation::Current()) [inline]
Schedules a task to be invoked on a worker thread after |delay_in_seconds| expires.
Embedders should override PostDelayedTaskOnWorkerThreadImpl() instead of PostDelayedTaskOnWorkerThread().
Definition at line 1229 of file v8-platform.h.
                                                                {
    PostDelayedTaskOnWorkerThreadImpl(priority, std::move(task),
                                      delay_in_seconds, location);
  }
References PostDelayedTaskOnWorkerThreadImpl().
Referenced by v8::internal::PagePool::AddLarge(), v8::internal::StressConcurrentAllocationTask::Schedule(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::WriteOutPGOTask::Schedule(), v8_inspector::V8InspectorImpl::EvaluateScope::setTimeout(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::TriggerCachingAfterTimeout(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::TriggerOutstandingCallbacks().
PostDelayedTaskOnWorkerThreadImpl()
virtual void v8::Platform::PostDelayedTaskOnWorkerThreadImpl (TaskPriority priority, std::unique_ptr< Task > task, double delay_in_seconds, const SourceLocation & location) [protected], [pure virtual]
Schedules a task with |priority| to be invoked on a worker thread after |delay_in_seconds| expires.
Implemented in v8::DelayedTasksPlatform, and v8::PredictablePlatform.
Referenced by CallDelayedOnWorkerThread(), and PostDelayedTaskOnWorkerThread().
PostJob()
std::unique_ptr<JobHandle> v8::Platform::PostJob (TaskPriority priority, std::unique_ptr< JobTask > job_task, const SourceLocation & location = SourceLocation::Current()) [inline]
Posts |job_task| to run in parallel.
Returns a JobHandle associated with the Job, which can be joined or canceled. This avoids degenerate cases:
Calling CallOnWorkerThread() for each work item, causing significant overhead.
Fixed number of CallOnWorkerThread() calls that split the work and might run for a long time. This is problematic when many components post `num cores` tasks and all expect to use all the cores. In these cases, the scheduler lacks context to be fair to multiple same-priority requests and/or ability to request lower priority work to yield when high priority work comes in. A canonical implementation of |job_task| looks like: class MyJobTask : public JobTask { public: MyJobTask(...) : worker_queue_(...) {} // JobTask: void Run(JobDelegate* delegate) override { while (!delegate->ShouldYield()) { // Smallest unit of work. auto work_item = worker_queue_.TakeWorkItem(); // Thread safe. if (!work_item) return; ProcessWork(work_item); } }
size_t GetMaxConcurrency() const override { return worker_queue_.GetSize(); // Thread safe. } }; auto handle = PostJob(TaskPriority::kUserVisible, std::make_unique<MyJobTask>(...)); handle->Join();
PostJob() and methods of the returned JobHandle/JobDelegate, must never be called while holding a lock that could be acquired by JobTask::Run or JobTask::GetMaxConcurrency -- that could result in a deadlock. This is because [1] JobTask::GetMaxConcurrency may be invoked while holding internal lock (A), hence JobTask::GetMaxConcurrency can only use a lock (B) if that lock is never held while calling back into JobHandle from any thread (A=>B/B=>A deadlock) and [2] JobTask::Run or JobTask::GetMaxConcurrency may be invoked synchronously from JobHandle (B=>JobHandle::foo=>B deadlock). Embedders should override CreateJobImpl() instead of PostJob().
Definition at line 1287 of file v8-platform.h.
                                                                {
    auto handle = CreateJob(priority, std::move(job_task), location);
    handle->NotifyConcurrencyIncrease();
    return handle;
  }
References CreateJob(), and v8::internal::handle().
Referenced by v8::internal::baseline::ConcurrentBaselineCompiler::ConcurrentBaselineCompiler(), v8::internal::OptimizingCompileTaskExecutor::EnsureStarted(), v8::internal::LazyCompileDispatcher::LazyCompileDispatcher(), v8::internal::Sweeper::SweepingState< scope >::Resume(), v8::internal::Sweeper::SweepingState< scope >::StartConcurrentSweeping(), v8::internal::ScavengerCollector::QuarantinedPageSweeper::StartSweeping(), and v8::internal::ConcurrentMarking::TryScheduleJob().
PostTaskOnWorkerThread()
void v8::Platform::PostTaskOnWorkerThread (TaskPriority priority, std::unique_ptr< Task > task, const SourceLocation & location = SourceLocation::Current()) [inline]
Schedules a task to be invoked on a worker thread.
Embedders should override PostTaskOnWorkerThreadImpl() instead of PostTaskOnWorkerThread().
Definition at line 1217 of file v8-platform.h.
                                                                {
    PostTaskOnWorkerThreadImpl(priority, std::move(task), location);
  }
References PostTaskOnWorkerThreadImpl().
Referenced by v8::platform::DefaultJobState::CallOnWorkerThread(), and v8::internal::wasm::AsyncCompileJob::StartBackgroundTask().
PostTaskOnWorkerThreadImpl()
virtual void v8::Platform::PostTaskOnWorkerThreadImpl (TaskPriority priority, std::unique_ptr< Task > task, const SourceLocation & location) [protected], [pure virtual]
Schedules a task with |priority| to be invoked on a worker thread.
Implemented in v8::DelayedTasksPlatform, and v8::PredictablePlatform.
Referenced by CallBlockingTaskOnWorkerThread(), CallLowPriorityTaskOnWorkerThread(), CallOnWorkerThread(), and PostTaskOnWorkerThread().
SystemClockTimeMillis()
double v8::Platform::SystemClockTimeMillis () [static], [protected]
Default implementation of current wall-clock time in milliseconds since epoch.
Useful for implementing |CurrentClockTimeMillis| if nothing special needed.
Definition at line 304 of file v8.cc.
                                       {
  return base::OS::TimeCurrentMillis();
}
References v8::base::OS::TimeCurrentMillis().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-platform.h
/mnt/V8SourceCode/src/init/v8.cc