v8::internal::DotPrinter Class Reference
#include <regexp-dotprinter.h>
Static Public Member Functions
static void DotPrint (const char *label, RegExpNode *node)
Detailed Description
Definition at line 15 of file regexp-dotprinter.h.
Member Function Documentation
DotPrint()
void v8::internal::DotPrinter::DotPrint (const char * label, RegExpNode * node) [static]
Definition at line 269 of file regexp-dotprinter.cc.
                                                             {
  StdoutStream os;
  DotPrinterImpl printer(os);
  printer.PrintNode(label, node);
}
References v8::internal::DotPrinterImpl::PrintNode().
Referenced by v8::internal::RegExpImpl::Compile(), and v8::internal::RegExp::DotPrintForTesting().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-dotprinter.h
/mnt/V8SourceCode/src/regexp/regexp-dotprinter.cc