v8::internal::compiler::VirtualObject Class Reference
#include <escape-analysis.h>
Public Types
using Id = uint32_t
using const_iterator = ZoneVector< Variable >::const_iterator
Public Member Functions
VirtualObject (VariableTracker *var_states, Id id, int size)
Maybe< Variable > FieldAt (int offset) const
Maybe< Variable > FieldAt (Maybe< int > maybe_offset) const
Id id () const
int size () const
void SetEscaped ()
bool HasEscaped () const
const_iterator begin () const
const_iterator end () const
Private Attributes
bool escaped_ = false
Id id_
ZoneVector< Variable > fields_
Detailed Description
Definition at line 125 of file escape-analysis.h.
Member Typedef Documentation
const_iterator
using v8::internal::compiler::VirtualObject::const_iterator = ZoneVector<Variable>::const_iterator
Definition at line 128 of file escape-analysis.h.
Id
using v8::internal::compiler::VirtualObject::Id = uint32_t
Definition at line 127 of file escape-analysis.h.
Constructor & Destructor Documentation
VirtualObject()
v8::internal::compiler::VirtualObject::VirtualObject (VariableTracker * var_states, VirtualObject::Id id, int size)
Definition at line 963 of file escape-analysis.cc.
    : Dependable(var_states->zone()), id_(id), fields_(var_states->zone()) {
  DCHECK(IsAligned(size, kTaggedSize));
  TRACE("Creating VirtualObject id:%d size:%d\n", id, size);
  int num_fields = size / kTaggedSize;
  fields_.reserve(num_fields);
  for (int i = 0; i < num_fields; ++i) {
    fields_.push_back(var_states->NewVariable());
  }
}
References v8::internal::DCHECK(), fields_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, IsAligned(), v8::internal::kTaggedSize, v8::internal::compiler::VariableTracker::NewVariable(), size(), and v8::internal::TRACE().
Member Function Documentation
begin()
const_iterator v8::internal::compiler::VirtualObject::begin () const [inline]
Definition at line 153 of file escape-analysis.h.
{ return fields_.begin(); }
References fields_.
end()
const_iterator v8::internal::compiler::VirtualObject::end () const [inline]
Definition at line 154 of file escape-analysis.h.
{ return fields_.end(); }
References fields_.
FieldAt() [1/2]
Maybe<Variable> v8::internal::compiler::VirtualObject::FieldAt (int offset) const [inline]
Definition at line 130 of file escape-analysis.h.
                                            {
    CHECK(IsAligned(offset, kTaggedSize));
    CHECK(!HasEscaped());
    if (offset >= size()) {
      // TODO(turbofan): Reading out-of-bounds can only happen in unreachable
      // code. In this case, we have to mark the object as escaping to avoid
      // dead nodes in the graph. This is a workaround that should be removed
      // once we can handle dead nodes everywhere.
      return Nothing<Variable>();
    }
    return Just(fields_.at(offset / kTaggedSize));
  }
References CHECK, fields_, HasEscaped(), IsAligned(), v8::Just(), v8::internal::kTaggedSize, and size().
Referenced by v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::anonymous_namespace{escape-analysis.cc}::CheckMapsHelper(), FieldAt(), and v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode().
FieldAt() [2/2]
Maybe<Variable> v8::internal::compiler::VirtualObject::FieldAt (Maybe< int > maybe_offset) const [inline]
Definition at line 142 of file escape-analysis.h.
                                                         {
    int offset;
    if (!maybe_offset.To(&offset)) return Nothing<Variable>();
    return FieldAt(offset);
  }
References FieldAt(), and v8::Maybe< T >::To().
HasEscaped()
bool v8::internal::compiler::VirtualObject::HasEscaped () const [inline]
Definition at line 152 of file escape-analysis.h.
{ return escaped_; }
References escaped_.
Referenced by v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::anonymous_namespace{escape-analysis.cc}::CheckMapsHelper(), FieldAt(), v8::internal::compiler::EscapeAnalysisReducer::Reduce(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode(), and v8::internal::compiler::EscapeAnalysisReducer::ReplaceNode().
id()
Id v8::internal::compiler::VirtualObject::id () const [inline]
Definition at line 147 of file escape-analysis.h.
{ return id_; }
References id_.
Referenced by v8::internal::compiler::EscapeAnalysisReducer::ObjectIdNode(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode(), and v8::internal::compiler::Deduplicator::SeenBefore().
SetEscaped()
void v8::internal::compiler::VirtualObject::SetEscaped () [inline]
Definition at line 151 of file escape-analysis.h.
{ escaped_ = true; }
References escaped_.
size()
int v8::internal::compiler::VirtualObject::size () const [inline]
Definition at line 148 of file escape-analysis.h.
{ return static_cast<int>(kTaggedSize * fields_.size()); }
References fields_, and v8::internal::kTaggedSize.
Referenced by FieldAt(), v8::internal::compiler::EscapeAnalysisTracker::Scope::InitVirtualObject(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode(), and VirtualObject().
Member Data Documentation
escaped_
bool v8::internal::compiler::VirtualObject::escaped_ = false [private]
Definition at line 157 of file escape-analysis.h.
Referenced by HasEscaped(), and SetEscaped().
fields_
ZoneVector<Variable> v8::internal::compiler::VirtualObject::fields_ [private]
Definition at line 159 of file escape-analysis.h.
Referenced by begin(), end(), FieldAt(), size(), and VirtualObject().
id_
Id v8::internal::compiler::VirtualObject::id_ [private]
Definition at line 158 of file escape-analysis.h.
Referenced by id().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/escape-analysis.h
/mnt/V8SourceCode/src/compiler/escape-analysis.cc