v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PrototypePropertyDependency Class Reference
Public Member Functions
PrototypePropertyDependency (JSHeapBroker *broker, JSFunctionRef function, ObjectRef prototype)
bool IsValid (JSHeapBroker *broker) const override
void PrepareInstall (JSHeapBroker *broker) const override
void Install (JSHeapBroker *broker, PendingDependencies *deps) const override
Private Member Functions
size_t Hash () const override
bool Equals (const CompilationDependency *that) const override
Private Attributes
const JSFunctionRef function_
const ObjectRef prototype_
Additional Inherited Members
Detailed Description
Definition at line 235 of file compilation-dependencies.cc.
Constructor & Destructor Documentation
PrototypePropertyDependency()
v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PrototypePropertyDependency::PrototypePropertyDependency (JSHeapBroker * broker, JSFunctionRef function, ObjectRef prototype) [inline]
Definition at line 237 of file compilation-dependencies.cc.
      : CompilationDependency(kPrototypeProperty),
        function_(function),
        prototype_(prototype) {
    DCHECK(function_.has_instance_prototype(broker));
    DCHECK(!function_.PrototypeRequiresRuntimeLookup(broker));
    DCHECK(function_.instance_prototype(broker).equals(prototype_));
  }
References broker(), and v8::internal::DCHECK().
Member Function Documentation
Equals()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PrototypePropertyDependency::Equals (const CompilationDependency * that) const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 277 of file compilation-dependencies.cc.
                                                                {
    const PrototypePropertyDependency* const zat = that->AsPrototypeProperty();
    return function_.equals(zat->function_) &&
           prototype_.equals(zat->prototype_);
  }
References function_, and prototype_.
Hash()
size_t v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PrototypePropertyDependency::Hash () const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 272 of file compilation-dependencies.cc.
                               {
    ObjectRef::Hash h;
    return base::hash_combine(h(function_), h(prototype_));
  }
References h(), v8::internal::Hash(), and v8::base::hash_combine().
Install()
void v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PrototypePropertyDependency::Install (JSHeapBroker * broker, PendingDependencies * deps) const [inline], [override]
Definition at line 263 of file compilation-dependencies.cc.
                                                                               {
    SLOW_DCHECK(IsValid(broker));
    DirectHandle<JSFunction> function = function_.object();
    CHECK(function->has_initial_map());
    Handle<Map> initial_map(function->initial_map(), broker->isolate());
    deps->Register(initial_map, DependentCode::kInitialMapChangedGroup);
  }
References broker(), CHECK, v8::internal::compiler::initial_map, v8::internal::DependentCode::kInitialMapChangedGroup, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PendingDependencies::Register(), and SLOW_DCHECK.
IsValid()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PrototypePropertyDependency::IsValid (JSHeapBroker * broker) const [inline], [override], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 247 of file compilation-dependencies.cc.
                                                    {
    DirectHandle<JSFunction> function = function_.object();
    return function->has_prototype_slot() &&
           function->has_instance_prototype() &&
           !function->PrototypeRequiresRuntimeLookup() &&
           function->instance_prototype() == *prototype_.object();
  }
PrepareInstall()
void v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PrototypePropertyDependency::PrepareInstall (JSHeapBroker * broker) const [inline], [override], [virtual]
Reimplemented from v8::internal::compiler::CompilationDependency.
Definition at line 255 of file compilation-dependencies.cc.
                                                           {
    SLOW_DCHECK(IsValid(broker));
    DirectHandle<JSFunction> function = function_.object();
    if (!function->has_initial_map()) {
      JSFunction::EnsureHasInitialMap(broker->isolate(), function);
    }
  }
References broker(), v8::internal::JSFunction::EnsureHasInitialMap(), and SLOW_DCHECK.
Member Data Documentation
function_
const JSFunctionRef v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PrototypePropertyDependency::function_ [private]
Definition at line 283 of file compilation-dependencies.cc.
Referenced by Equals().
prototype_
const ObjectRef v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PrototypePropertyDependency::prototype_ [private]
Definition at line 284 of file compilation-dependencies.cc.
Referenced by Equals().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/compilation-dependencies.cc