v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo Class Reference
Public Member Functions
RegisterInfo (Register reg, uint32_t equivalence_id, bool materialized, bool allocated)
RegisterInfo (const RegisterInfo &)=delete
RegisterInfo & operator= (const RegisterInfo &)=delete
void AddToEquivalenceSetOf (RegisterInfo *info)
void MoveToNewEquivalenceSet (uint32_t equivalence_id, MaterializedInfo materialized, ResetVariableHint reset=ResetVariableHint::kReset)
bool IsOnlyMemberOfEquivalenceSet () const
bool IsInSameEquivalenceSet (RegisterInfo *info) const
RegisterInfo * GetAllocatedEquivalent ()
RegisterInfo * GetMaterializedEquivalent ()
RegisterInfo * GetMaterializedEquivalentOtherThan (Register reg)
RegisterInfo * GetEquivalentToMaterialize ()
void MarkTemporariesAsUnmaterialized (Register temporary_base)
RegisterInfo * GetEquivalent ()
Register register_value () const
bool materialized () const
void set_materialized (bool materialized)
bool allocated () const
void set_allocated (bool allocated)
void set_equivalence_id (uint32_t equivalence_id)
uint32_t equivalence_id () const
bool needs_flush () const
void set_needs_flush (bool needs_flush)
TypeHint type_hint () const
void set_type_hint (TypeHint hint)
VariableHint variable_hint () const
void set_variable_hint (VariableHint hint)
void flush_variable_hint (bool reset_variable_hint)
RegisterInfo * next () const
Private Attributes
Register register_
uint32_t equivalence_id_
bool materialized_
bool allocated_
bool needs_flush_
TypeHint type_hint_
VariableHint variable_hint_
RegisterInfo * next_
RegisterInfo * prev_
Detailed Description
Definition at line 33 of file bytecode-register-optimizer.cc.
Constructor & Destructor Documentation
RegisterInfo() [1/2]
v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::RegisterInfo (Register reg, uint32_t equivalence_id, bool materialized, bool allocated) [inline]
Definition at line 35 of file bytecode-register-optimizer.cc.
      : register_(reg),
        equivalence_id_(equivalence_id),
        materialized_(materialized),
        allocated_(allocated),
        needs_flush_(false),
        type_hint_(TypeHint::kAny),
        variable_hint_({nullptr, VariableHintMode::kDefinitelyHasVariable}),
        next_(this),
        prev_(this) {}
References v8::internal::kAny, and v8::internal::interpreter::kDefinitelyHasVariable.
RegisterInfo() [2/2]
v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::RegisterInfo (const RegisterInfo &) [delete]
Member Function Documentation
AddToEquivalenceSetOf()
void v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::AddToEquivalenceSetOf (RegisterInfo * info)
Definition at line 128 of file bytecode-register-optimizer.cc.
                        {
  DCHECK_NE(kInvalidEquivalenceId, info->equivalence_id());
  // Fix old list
  next_->prev_ = prev_;
  prev_->next_ = next_;
  // Add to new list.
  next_ = info->next_;
  prev_ = info;
  prev_->next_ = this;
  next_->prev_ = this;
  set_equivalence_id(info->equivalence_id());
  set_materialized(false);
  set_variable_hint(info->variable_hint());
  type_hint_ = info->type_hint();
}
References DCHECK_NE, equivalence_id(), v8::internal::interpreter::BytecodeRegisterOptimizer::kInvalidEquivalenceId, next_, prev_, set_equivalence_id(), set_materialized(), set_variable_hint(), type_hint(), type_hint_, and variable_hint().
Referenced by v8::internal::interpreter::BytecodeRegisterOptimizer::AddToEquivalenceSet().
allocated()
bool v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::allocated () const [inline]
Definition at line 90 of file bytecode-register-optimizer.cc.
{ return allocated_; }
References allocated_.
Referenced by v8::internal::interpreter::BytecodeRegisterOptimizer::Flush(), GetAllocatedEquivalent(), GetEquivalentToMaterialize(), and set_allocated().
equivalence_id()
uint32_t v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::equivalence_id () const [inline]
Definition at line 95 of file bytecode-register-optimizer.cc.
{ return equivalence_id_; }
References equivalence_id_.
Referenced by AddToEquivalenceSetOf(), IsInSameEquivalenceSet(), and set_equivalence_id().
flush_variable_hint()
void v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::flush_variable_hint (bool reset_variable_hint) [inline]
Definition at line 104 of file bytecode-register-optimizer.cc.
                                                     {
    if (reset_variable_hint) {
      variable_hint_ = {nullptr, VariableHintMode::kDefinitelyHasVariable};
    } else if (variable_hint_.variable != nullptr) {
      variable_hint_.mode = VariableHintMode::kMightHaveVariable;
    }
  }
References v8::internal::interpreter::kDefinitelyHasVariable, v8::internal::interpreter::kMightHaveVariable, v8::internal::interpreter::VariableHint::mode, v8::internal::interpreter::VariableHint::variable, and variable_hint_.
GetAllocatedEquivalent()
BytecodeRegisterOptimizer::RegisterInfo * v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::GetAllocatedEquivalent ()
Definition at line 215 of file bytecode-register-optimizer.cc.
                                                              {
  RegisterInfo* visitor = this;
  do {
    if (visitor->allocated()) {
      return visitor;
    }
    visitor = visitor->next_;
  } while (visitor != this);
  return nullptr;
}
References allocated(), and next_.
GetEquivalent()
BytecodeRegisterOptimizer::RegisterInfo * v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::GetEquivalent ()
Definition at line 287 of file bytecode-register-optimizer.cc.
                                                     {
  return next_;
}
Referenced by v8::internal::interpreter::BytecodeRegisterOptimizer::Flush().
GetEquivalentToMaterialize()
BytecodeRegisterOptimizer::RegisterInfo * v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::GetEquivalentToMaterialize ()
Definition at line 255 of file bytecode-register-optimizer.cc.
                                                                  {
  DCHECK(this->materialized());
  RegisterInfo* visitor = this->next_;
  RegisterInfo* best_info = nullptr;
  while (visitor != this) {
    if (visitor->materialized()) {
      return nullptr;
    }
    if (visitor->allocated() &&
        (best_info == nullptr ||
         visitor->register_value() < best_info->register_value())) {
      best_info = visitor;
    }
    visitor = visitor->next_;
  }
  return best_info;
}
References allocated(), v8::internal::DCHECK(), materialized(), next_, and register_value().
Referenced by v8::internal::interpreter::BytecodeRegisterOptimizer::CreateMaterializedEquivalent().
GetMaterializedEquivalent()
BytecodeRegisterOptimizer::RegisterInfo * v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::GetMaterializedEquivalent ()
Definition at line 228 of file bytecode-register-optimizer.cc.
                                                                 {
  RegisterInfo* visitor = this;
  do {
    if (visitor->materialized()) {
      return visitor;
    }
    visitor = visitor->next_;
  } while (visitor != this);
  return nullptr;
}
References materialized(), and next_.
Referenced by v8::internal::interpreter::BytecodeRegisterOptimizer::Materialize(), and v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterTransfer().
GetMaterializedEquivalentOtherThan()
BytecodeRegisterOptimizer::RegisterInfo * v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::GetMaterializedEquivalentOtherThan (Register reg)
Definition at line 241 of file bytecode-register-optimizer.cc.
                  {
  RegisterInfo* visitor = this;
  do {
    if (visitor->materialized() && visitor->register_value() != reg) {
      return visitor;
    }
    visitor = visitor->next_;
  } while (visitor != this);
  return nullptr;
}
References materialized(), next_, and register_value().
Referenced by v8::internal::interpreter::BytecodeRegisterOptimizer::GetMaterializedEquivalentNotAccumulator().
IsInSameEquivalenceSet()
bool v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::IsInSameEquivalenceSet (RegisterInfo * info) const
Definition at line 209 of file bytecode-register-optimizer.cc.
                              {
  return equivalence_id() == info->equivalence_id();
}
References equivalence_id().
Referenced by v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterTransfer().
IsOnlyMemberOfEquivalenceSet()
bool v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::IsOnlyMemberOfEquivalenceSet () const
Definition at line 157 of file bytecode-register-optimizer.cc.
          {
  return this->next_ == this;
}
MarkTemporariesAsUnmaterialized()
void v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::MarkTemporariesAsUnmaterialized (Register temporary_base)
Definition at line 273 of file bytecode-register-optimizer.cc.
                             {
  DCHECK(this->register_value() < temporary_base);
  DCHECK(this->materialized());
  RegisterInfo* visitor = this->next_;
  while (visitor != this) {
    if (visitor->register_value() >= temporary_base) {
      visitor->set_materialized(false);
    }
    visitor = visitor->next_;
  }
}
References v8::internal::DCHECK(), next_, register_value(), and set_materialized().
Referenced by v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterTransfer().
materialized()
bool v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::materialized () const [inline]
Definition at line 88 of file bytecode-register-optimizer.cc.
{ return materialized_; }
References materialized_.
Referenced by v8::internal::interpreter::BytecodeRegisterOptimizer::AllocateRegister(), v8::internal::interpreter::BytecodeRegisterOptimizer::CreateMaterializedEquivalent(), v8::internal::interpreter::BytecodeRegisterOptimizer::Flush(), GetEquivalentToMaterialize(), v8::internal::interpreter::BytecodeRegisterOptimizer::GetInputRegister(), GetMaterializedEquivalent(), v8::internal::interpreter::BytecodeRegisterOptimizer::GetMaterializedEquivalentNotAccumulator(), GetMaterializedEquivalentOtherThan(), v8::internal::interpreter::BytecodeRegisterOptimizer::Materialize(), v8::internal::interpreter::BytecodeRegisterOptimizer::PrepareOutputRegister(), v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterTransfer(), and set_materialized().
MoveToNewEquivalenceSet()
void v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::MoveToNewEquivalenceSet (uint32_t equivalence_id, MaterializedInfo materialized, ResetVariableHint reset = ResetVariableHint::kReset)
Definition at line 145 of file bytecode-register-optimizer.cc.
                             {
  next_->prev_ = prev_;
  prev_->next_ = next_;
  next_ = prev_ = this;
  equivalence_id_ = equivalence_id;
  materialized_ = materialized == MaterializedInfo::kMaterialized;
  flush_variable_hint(reset == ResetVariableHint::kReset);
  type_hint_ = TypeHint::kAny;
}
References v8::internal::interpreter::BytecodeRegisterOptimizer::equivalence_id_, v8::internal::interpreter::kMaterialized, and v8::internal::interpreter::kReset.
Referenced by v8::internal::interpreter::BytecodeRegisterOptimizer::AllocateRegister(), v8::internal::interpreter::BytecodeRegisterOptimizer::Flush(), and v8::internal::interpreter::BytecodeRegisterOptimizer::PrepareOutputRegister().
needs_flush()
bool v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::needs_flush () const [inline]
Definition at line 97 of file bytecode-register-optimizer.cc.
{ return needs_flush_; }
References needs_flush_.
Referenced by v8::internal::interpreter::BytecodeRegisterOptimizer::PushToRegistersNeedingFlush(), and set_needs_flush().
next()
RegisterInfo* v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::next () const [inline]
Definition at line 112 of file bytecode-register-optimizer.cc.
{ return next_; }
References next_.
Referenced by v8::internal::interpreter::BytecodeRegisterOptimizer::SetVariableInRegister().
operator=()
RegisterInfo& v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::operator= (const RegisterInfo &) [delete]
register_value()
Register v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::register_value () const [inline]
Definition at line 87 of file bytecode-register-optimizer.cc.
{ return register_; }
References register_.
Referenced by v8::internal::interpreter::BytecodeRegisterOptimizer::BytecodeRegisterOptimizer(), GetEquivalentToMaterialize(), v8::internal::interpreter::BytecodeRegisterOptimizer::GetInputRegister(), GetMaterializedEquivalentOtherThan(), MarkTemporariesAsUnmaterialized(), v8::internal::interpreter::BytecodeRegisterOptimizer::OutputRegisterTransfer(), v8::internal::interpreter::BytecodeRegisterOptimizer::PrepareOutputRegister(), and v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterTransfer().
set_allocated()
void v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::set_allocated (bool allocated) [inline]
Definition at line 91 of file bytecode-register-optimizer.cc.
{ allocated_ = allocated; }
References allocated(), and allocated_.
Referenced by v8::internal::interpreter::BytecodeRegisterOptimizer::AllocateRegister(), v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterFreeEvent(), and v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterListFreeEvent().
set_equivalence_id()
void v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::set_equivalence_id (uint32_t equivalence_id) [inline]
Definition at line 92 of file bytecode-register-optimizer.cc.
                                                   {
    equivalence_id_ = equivalence_id;
  }
References equivalence_id(), and equivalence_id_.
Referenced by AddToEquivalenceSetOf().
set_materialized()
void v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::set_materialized (bool materialized) [inline]
Definition at line 89 of file bytecode-register-optimizer.cc.
{ materialized_ = materialized; }
References materialized(), and materialized_.
Referenced by AddToEquivalenceSetOf(), MarkTemporariesAsUnmaterialized(), v8::internal::interpreter::BytecodeRegisterOptimizer::OutputRegisterTransfer(), and v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterTransfer().
set_needs_flush()
void v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::set_needs_flush (bool needs_flush) [inline]
Definition at line 98 of file bytecode-register-optimizer.cc.
{ needs_flush_ = needs_flush; }
References needs_flush(), and needs_flush_.
Referenced by v8::internal::interpreter::BytecodeRegisterOptimizer::Flush(), and v8::internal::interpreter::BytecodeRegisterOptimizer::PushToRegistersNeedingFlush().
set_type_hint()
void v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::set_type_hint (TypeHint hint) [inline]
Definition at line 100 of file bytecode-register-optimizer.cc.
{ type_hint_ = hint; }
References type_hint_.
Referenced by v8::internal::interpreter::BytecodeRegisterOptimizer::ResetTypeHintForAccumulator(), and v8::internal::interpreter::BytecodeRegisterOptimizer::SetTypeHintForAccumulator().
set_variable_hint()
void v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::set_variable_hint (VariableHint hint) [inline]
Definition at line 103 of file bytecode-register-optimizer.cc.
{ variable_hint_ = hint; }
References variable_hint_.
Referenced by AddToEquivalenceSetOf(), and v8::internal::interpreter::BytecodeRegisterOptimizer::SetVariableInRegister().
type_hint()
TypeHint v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::type_hint () const [inline]
Definition at line 99 of file bytecode-register-optimizer.cc.
{ return type_hint_; }
References type_hint_.
Referenced by AddToEquivalenceSetOf(), v8::internal::interpreter::BytecodeRegisterOptimizer::GetTypeHint(), v8::internal::interpreter::BytecodeRegisterOptimizer::IsAccumulatorReset(), and v8::internal::interpreter::BytecodeRegisterOptimizer::SetTypeHintForAccumulator().
variable_hint()
VariableHint v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::variable_hint () const [inline]
Definition at line 102 of file bytecode-register-optimizer.cc.
{ return variable_hint_; }
References variable_hint_.
Referenced by AddToEquivalenceSetOf(), v8::internal::interpreter::BytecodeRegisterOptimizer::GetPotentialVariableInRegister(), and v8::internal::interpreter::BytecodeRegisterOptimizer::IsVariableInRegister().
Member Data Documentation
allocated_
bool v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::allocated_ [private]
Definition at line 118 of file bytecode-register-optimizer.cc.
Referenced by allocated(), and set_allocated().
equivalence_id_
uint32_t v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::equivalence_id_ [private]
Definition at line 116 of file bytecode-register-optimizer.cc.
Referenced by equivalence_id(), and set_equivalence_id().
materialized_
bool v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::materialized_ [private]
Definition at line 117 of file bytecode-register-optimizer.cc.
Referenced by materialized(), and set_materialized().
needs_flush_
bool v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::needs_flush_ [private]
Definition at line 119 of file bytecode-register-optimizer.cc.
Referenced by needs_flush(), and set_needs_flush().
next_
RegisterInfo* v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::next_ [private]
Definition at line 124 of file bytecode-register-optimizer.cc.
Referenced by AddToEquivalenceSetOf(), GetAllocatedEquivalent(), GetEquivalentToMaterialize(), GetMaterializedEquivalent(), GetMaterializedEquivalentOtherThan(), MarkTemporariesAsUnmaterialized(), and next().
prev_
RegisterInfo* v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::prev_ [private]
Definition at line 125 of file bytecode-register-optimizer.cc.
Referenced by AddToEquivalenceSetOf().
register_
Register v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::register_ [private]
Definition at line 115 of file bytecode-register-optimizer.cc.
Referenced by register_value().
type_hint_
TypeHint v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::type_hint_ [private]
Definition at line 120 of file bytecode-register-optimizer.cc.
Referenced by AddToEquivalenceSetOf(), set_type_hint(), and type_hint().
variable_hint_
VariableHint v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::variable_hint_ [private]
Definition at line 121 of file bytecode-register-optimizer.cc.
Referenced by flush_variable_hint(), set_variable_hint(), and variable_hint().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/interpreter/bytecode-register-optimizer.cc