v8::internal::compiler::BytecodeGraphBuilder::Environment Class Reference
Public Types
enum FrameStateAttachmentMode { kAttachFrameState
, kDontAttachFrameState
 }
Public Member Functions
Environment (BytecodeGraphBuilder *builder, int register_count, int parameter_count, interpreter::Register incoming_new_target_or_generator, Node *control_dependency)
int parameter_count () const
int register_count () const
Node * LookupAccumulator () const
Node * LookupRegister (interpreter::Register the_register) const
Node * LookupGeneratorState () const
void BindAccumulator (Node *node, FrameStateAttachmentMode mode=kDontAttachFrameState)
void BindRegister (interpreter::Register the_register, Node *node, FrameStateAttachmentMode mode=kDontAttachFrameState)
void BindRegistersToProjections (interpreter::Register first_reg, Node *node, FrameStateAttachmentMode mode=kDontAttachFrameState)
void BindGeneratorState (Node *node)
void RecordAfterState (Node *node, FrameStateAttachmentMode mode=kDontAttachFrameState)
Node * GetEffectDependency ()
void UpdateEffectDependency (Node *dependency)
Node * Checkpoint (BytecodeOffset bytecode_offset, OutputFrameStateCombine combine, const BytecodeLivenessState *liveness)
Node * GetControlDependency () const
void UpdateControlDependency (Node *dependency)
Node * Context () const
void SetContext (Node *new_context)
Environment * Copy ()
void Merge (Environment *other, const BytecodeLivenessState *liveness)
void FillWithOsrValues ()
void PrepareForLoop (const BytecodeLoopAssignments &assignments, const BytecodeLivenessState *liveness)
void PrepareForLoopExit (Node *loop, const BytecodeLoopAssignments &assignments, const BytecodeLivenessState *liveness)
Private Member Functions
Environment (const Environment *copy)
bool StateValuesRequireUpdate (Node **state_values, Node **values, int count)
void UpdateStateValues (Node **state_values, Node **values, int count)
Node * GetStateValuesFromCache (Node **values, int count, const BytecodeLivenessState *liveness)
int RegisterToValuesIndex (interpreter::Register the_register) const
Zone * zone () const
TFGraph * graph () const
CommonOperatorBuilder * common () const
BytecodeGraphBuilder * builder () const
const NodeVector * values () const
NodeVector * values ()
int register_base () const
int accumulator_base () const
Private Attributes
friend Zone
BytecodeGraphBuilder * builder_
int register_count_
int parameter_count_
Node * context_
Node * control_dependency_
Node * effect_dependency_
NodeVector values_
Node * parameters_state_values_
Node * generator_state_
int register_base_
int accumulator_base_
Detailed Description
Definition at line 537 of file bytecode-graph-builder.cc.
Member Enumeration Documentation
FrameStateAttachmentMode
enum v8::internal::compiler::BytecodeGraphBuilder::Environment::FrameStateAttachmentMode
Enumerator
kAttachFrameState
kDontAttachFrameState
Definition at line 547 of file bytecode-graph-builder.cc.
{ kAttachFrameState, kDontAttachFrameState };
Constructor & Destructor Documentation
Environment() [1/2]
v8::internal::compiler::BytecodeGraphBuilder::Environment::Environment (BytecodeGraphBuilder * builder, int register_count, int parameter_count, interpreter::Register incoming_new_target_or_generator, Node * control_dependency)
Definition at line 648 of file bytecode-graph-builder.cc.
    : builder_(builder),
      register_count_(register_count),
      parameter_count_(parameter_count),
      control_dependency_(control_dependency),
      effect_dependency_(control_dependency),
      values_(builder->local_zone()),
      parameters_state_values_(nullptr),
      generator_state_(nullptr) {
  // The layout of values_ is:
  //
  // [receiver] [parameters] [registers] [accumulator]
  //
  // parameter[0] is the receiver (this), parameters 1..N are the
  // parameters supplied to the method (arg0..argN-1). The accumulator
  // is stored separately.
  // Parameters including the receiver
  for (int i = 0; i < parameter_count; i++) {
    const char* debug_name = (i == 0) ? "%this" : nullptr;
    Node* parameter = builder->GetParameter(i, debug_name);
    values()->push_back(parameter);
  }
  // Registers
  register_base_ = static_cast<int>(values()->size());
  Node* undefined_constant = builder->jsgraph()->UndefinedConstant();
  values()->insert(values()->end(), register_count, undefined_constant);
  // Accumulator
  accumulator_base_ = static_cast<int>(values()->size());
  values()->push_back(undefined_constant);
  // Context
  int context_index = Linkage::GetJSCallContextParamIndex(parameter_count);
  context_ = builder->GetParameter(context_index, "%context");
  // Incoming new.target or generator register
  if (incoming_new_target_or_generator.is_valid()) {
    int new_target_index =
        Linkage::GetJSCallNewTargetParamIndex(parameter_count);
    Node* new_target_node =
        builder->GetParameter(new_target_index, "%new.target");
    int values_index = RegisterToValuesIndex(incoming_new_target_or_generator);
    values()->at(values_index) = new_target_node;
  }
}
References accumulator_base_, v8::internal::ZoneVector< T >::at(), builder(), context_, v8::internal::compiler::end(), v8::internal::compiler::Linkage::GetJSCallContextParamIndex(), v8::internal::compiler::Linkage::GetJSCallNewTargetParamIndex(), v8::internal::compiler::BytecodeGraphBuilder::GetParameter(), v8::internal::ZoneVector< T >::insert(), v8::internal::interpreter::Register::is_valid(), v8::internal::compiler::BytecodeGraphBuilder::jsgraph(), parameter_count(), v8::internal::ZoneVector< T >::push_back(), register_base_, register_count(), RegisterToValuesIndex(), v8::internal::ZoneVector< T >::size(), and values().
Environment() [2/2]
v8::internal::compiler::BytecodeGraphBuilder::Environment::Environment (const Environment * copy) [explicit], [private]
Definition at line 700 of file bytecode-graph-builder.cc.
    : builder_(other->builder_),
      register_count_(other->register_count_),
      parameter_count_(other->parameter_count_),
      context_(other->context_),
      control_dependency_(other->control_dependency_),
      effect_dependency_(other->effect_dependency_),
      values_(other->zone()),
      parameters_state_values_(other->parameters_state_values_),
      generator_state_(other->generator_state_),
      register_base_(other->register_base_),
      accumulator_base_(other->accumulator_base_) {
  values_ = other->values_;
}
References values_.
Member Function Documentation
accumulator_base()
int v8::internal::compiler::BytecodeGraphBuilder::Environment::accumulator_base () const [inline], [private]
Definition at line 617 of file bytecode-graph-builder.cc.
{ return accumulator_base_; }
References accumulator_base_.
BindAccumulator()
void v8::internal::compiler::BytecodeGraphBuilder::Environment::BindAccumulator (Node * node, FrameStateAttachmentMode mode = kDontAttachFrameState)
Definition at line 747 of file bytecode-graph-builder.cc.
                                               {
  if (mode == FrameStateAttachmentMode::kAttachFrameState) {
    builder()->PrepareFrameState(node, OutputFrameStateCombine::PokeAt(0));
  }
  values()->at(accumulator_base_) = node;
}
References mode(), and v8::internal::compiler::OutputFrameStateCombine::PokeAt().
BindGeneratorState()
void v8::internal::compiler::BytecodeGraphBuilder::Environment::BindGeneratorState (Node * node)
Definition at line 755 of file bytecode-graph-builder.cc.
                                                                   {
  generator_state_ = node;
}
BindRegister()
void v8::internal::compiler::BytecodeGraphBuilder::Environment::BindRegister (interpreter::Register the_register, Node * node, FrameStateAttachmentMode mode = kDontAttachFrameState)
Definition at line 759 of file bytecode-graph-builder.cc.
                                   {
  int values_index = RegisterToValuesIndex(the_register);
  if (mode == FrameStateAttachmentMode::kAttachFrameState) {
    builder()->PrepareFrameState(node, OutputFrameStateCombine::PokeAt(
                                           accumulator_base_ - values_index));
  }
  values()->at(values_index) = node;
}
References mode(), and v8::internal::compiler::OutputFrameStateCombine::PokeAt().
BindRegistersToProjections()
void v8::internal::compiler::BytecodeGraphBuilder::Environment::BindRegistersToProjections (interpreter::Register first_reg, Node * node, FrameStateAttachmentMode mode = kDontAttachFrameState)
Definition at line 770 of file bytecode-graph-builder.cc.
                                   {
  int values_index = RegisterToValuesIndex(first_reg);
  if (mode == FrameStateAttachmentMode::kAttachFrameState) {
    builder()->PrepareFrameState(node, OutputFrameStateCombine::PokeAt(
                                           accumulator_base_ - values_index));
  }
  for (int i = 0; i < node->op()->ValueOutputCount(); i++) {
    values()->at(values_index + i) =
        builder()->NewNode(common()->Projection(i), node);
  }
}
References v8::internal::compiler::BytecodeGraphBuilder::common(), mode(), v8::internal::compiler::Node::op(), and v8::internal::compiler::OutputFrameStateCombine::PokeAt().
builder()
BytecodeGraphBuilder* v8::internal::compiler::BytecodeGraphBuilder::Environment::builder () const [inline], [private]
Definition at line 613 of file bytecode-graph-builder.cc.
{ return builder_; }
References builder_.
Referenced by Environment().
Checkpoint()
Node * v8::internal::compiler::BytecodeGraphBuilder::Environment::Checkpoint (BytecodeOffset bytecode_offset, OutputFrameStateCombine combine, const BytecodeLivenessState * liveness)
Definition at line 996 of file bytecode-graph-builder.cc.
                                           {
  if (parameter_count() == register_count()) {
    // Reuse the state-value cache if the number of local registers happens
    // to match the parameter count.
    parameters_state_values_ =
        GetStateValuesFromCache(&values()->at(0), parameter_count(), nullptr);
  } else {
    UpdateStateValues(&parameters_state_values_, &values()->at(0),
                      parameter_count());
  }
  Node* registers_state_values = GetStateValuesFromCache(
      &values()->at(register_base()), register_count(), liveness);
  bool accumulator_is_live = !liveness || liveness->AccumulatorIsLive();
  Node* accumulator_state_value =
      accumulator_is_live && combine != OutputFrameStateCombine::PokeAt(0)
          ? values()->at(accumulator_base())
          : builder()->jsgraph()->OptimizedOutConstant();
  const Operator* op = common()->FrameState(
      bailout_id, combine, builder()->frame_state_function_info());
  Node* result = graph()->NewNode(
      op, parameters_state_values_, registers_state_values,
      accumulator_state_value, Context(), builder()->GetFunctionClosure(),
      builder()->graph()->start());
  return result;
}
References v8::internal::compiler::BytecodeLivenessState::AccumulatorIsLive(), v8::internal::compiler::BytecodeGraphBuilder::common(), v8::internal::compiler::BytecodeGraphBuilder::frame_state_function_info(), v8::internal::compiler::CommonOperatorBuilder::FrameState(), v8::internal::compiler::BytecodeGraphBuilder::GetFunctionClosure(), v8::internal::compiler::BytecodeGraphBuilder::graph(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::OutputFrameStateCombine::PokeAt(), and v8::base::internal::result.
Referenced by v8::internal::compiler::BytecodeGraphBuilder::PrepareEagerCheckpoint().
common()
CommonOperatorBuilder* v8::internal::compiler::BytecodeGraphBuilder::Environment::common () const [inline], [private]
Definition at line 612 of file bytecode-graph-builder.cc.
{ return builder_->common(); }
References builder_, and v8::internal::compiler::BytecodeGraphBuilder::common().
Context()
Node* v8::internal::compiler::BytecodeGraphBuilder::Environment::Context () const [inline]
Definition at line 585 of file bytecode-graph-builder.cc.
{ return context_; }
References context_.
Copy()
BytecodeGraphBuilder::Environment * v8::internal::compiler::BytecodeGraphBuilder::Environment::Copy ()
Definition at line 791 of file bytecode-graph-builder.cc.
                                                                       {
  return zone()->New<Environment>(this);
}
Referenced by v8::internal::compiler::BytecodeGraphBuilder::MakeNode().
FillWithOsrValues()
void v8::internal::compiler::BytecodeGraphBuilder::Environment::FillWithOsrValues ()
Definition at line 898 of file bytecode-graph-builder.cc.
                                                        {
  Node* start = graph()->start();
  // Create OSR values for each environment value.
  SetContext(graph()->NewNode(
      common()->OsrValue(Linkage::kOsrContextSpillSlotIndex), start));
  int size = static_cast<int>(values()->size());
  for (int i = 0; i < size; i++) {
    int idx = i; // Indexing scheme follows {StandardFrame}, adapt accordingly.
    if (i >= register_base()) idx += InterpreterFrameConstants::kExtraSlotCount;
    if (i >= accumulator_base()) idx = Linkage::kOsrAccumulatorRegisterIndex;
    values()->at(i) = graph()->NewNode(common()->OsrValue(idx), start);
  }
}
References v8::internal::compiler::BytecodeGraphBuilder::common(), v8::internal::compiler::BytecodeGraphBuilder::graph(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Linkage::kOsrAccumulatorRegisterIndex, v8::internal::compiler::Linkage::kOsrContextSpillSlotIndex, v8::internal::compiler::BytecodeGraphBuilder::NewNode(), v8::internal::compiler::TFGraph::NewNode(), size(), and v8::internal::compiler::TFGraph::start().
GetControlDependency()
Node* v8::internal::compiler::BytecodeGraphBuilder::Environment::GetControlDependency () const [inline]
Definition at line 580 of file bytecode-graph-builder.cc.
{ return control_dependency_; }
References control_dependency_.
Referenced by Merge().
GetEffectDependency()
Node* v8::internal::compiler::BytecodeGraphBuilder::Environment::GetEffectDependency () [inline]
Definition at line 568 of file bytecode-graph-builder.cc.
{ return effect_dependency_; }
References effect_dependency_.
Referenced by Merge(), and v8::internal::compiler::BytecodeGraphBuilder::PrepareEagerCheckpoint().
GetStateValuesFromCache()
Node * v8::internal::compiler::BytecodeGraphBuilder::Environment::GetStateValuesFromCache (Node ** values, int count, const BytecodeLivenessState * liveness) [private]
Definition at line 990 of file bytecode-graph-builder.cc.
                                                                     {
  return builder_->state_values_cache_.GetNodeForValues(
      values, static_cast<size_t>(count), liveness);
}
graph()
TFGraph* v8::internal::compiler::BytecodeGraphBuilder::Environment::graph () const [inline], [private]
Definition at line 611 of file bytecode-graph-builder.cc.
{ return builder_->graph(); }
References builder_, and v8::internal::compiler::BytecodeGraphBuilder::graph().
LookupAccumulator()
Node * v8::internal::compiler::BytecodeGraphBuilder::Environment::LookupAccumulator () const
Definition at line 726 of file bytecode-graph-builder.cc.
                                                               {
  return values()->at(accumulator_base_);
}
LookupGeneratorState()
Node * v8::internal::compiler::BytecodeGraphBuilder::Environment::LookupGeneratorState () const
Definition at line 730 of file bytecode-graph-builder.cc.
                                                                  {
  DCHECK_NOT_NULL(generator_state_);
  return generator_state_;
}
References DCHECK_NOT_NULL.
LookupRegister()
Node * v8::internal::compiler::BytecodeGraphBuilder::Environment::LookupRegister (interpreter::Register the_register) const
Definition at line 735 of file bytecode-graph-builder.cc.
                                            {
  if (the_register.is_current_context()) {
    return Context();
  } else if (the_register.is_function_closure()) {
    return builder()->GetFunctionClosure();
  } else {
    int values_index = RegisterToValuesIndex(the_register);
    return values()->at(values_index);
  }
}
References v8::internal::interpreter::Register::is_current_context(), and v8::internal::interpreter::Register::is_function_closure().
Merge()
void v8::internal::compiler::BytecodeGraphBuilder::Environment::Merge (BytecodeGraphBuilder::Environment * other, const BytecodeLivenessState * liveness)
Definition at line 795 of file bytecode-graph-builder.cc.
                                           {
  // Create a merge of the control dependencies of both environments and update
  // the current environment's control dependency accordingly.
  Node* control = builder()->MergeControl(GetControlDependency(),
                                          other->GetControlDependency());
  UpdateControlDependency(control);
  // Create a merge of the effect dependencies of both environments and update
  // the current environment's effect dependency accordingly.
  Node* effect = builder()->MergeEffect(GetEffectDependency(),
                                        other->GetEffectDependency(), control);
  UpdateEffectDependency(effect);
  // Introduce Phi nodes for values that are live and have differing inputs at
  // the merge point, potentially extending an existing Phi node if possible.
  context_ = builder()->MergeValue(context_, other->context_, control);
  for (int i = 0; i < parameter_count(); i++) {
    values_[i] = builder()->MergeValue(values_[i], other->values_[i], control);
  }
  for (int i = 0; i < register_count(); i++) {
    int index = register_base() + i;
    if (liveness == nullptr || liveness->RegisterIsLive(i)) {
#if DEBUG
      // We only do these DCHECKs when we are not in the resume path of a
      // generator -- this is, when either there is no generator state at all,
      // or the generator state is not the constant "executing" value.
      if (generator_state_ == nullptr ||
          NumberMatcher(generator_state_)
              .Is(JSGeneratorObject::kGeneratorExecuting)) {
        DCHECK_NE(values_[index], builder()->jsgraph()->OptimizedOutConstant());
        DCHECK_NE(other->values_[index],
                  builder()->jsgraph()->OptimizedOutConstant());
      }
#endif
      values_[index] =
          builder()->MergeValue(values_[index], other->values_[index], control);
    } else {
      values_[index] = builder()->jsgraph()->OptimizedOutConstant();
    }
  }
  if (liveness == nullptr || liveness->AccumulatorIsLive()) {
    DCHECK_NE(values_[accumulator_base()],
              builder()->jsgraph()->OptimizedOutConstant());
    DCHECK_NE(other->values_[accumulator_base()],
              builder()->jsgraph()->OptimizedOutConstant());
    values_[accumulator_base()] =
        builder()->MergeValue(values_[accumulator_base()],
                              other->values_[accumulator_base()], control);
  } else {
    values_[accumulator_base()] = builder()->jsgraph()->OptimizedOutConstant();
  }
  if (generator_state_ != nullptr) {
    DCHECK_NOT_NULL(other->generator_state_);
    generator_state_ = builder()->MergeValue(generator_state_,
                                             other->generator_state_, control);
  }
}
References v8::internal::compiler::BytecodeLivenessState::AccumulatorIsLive(), context_, DCHECK_NE, DCHECK_NOT_NULL, generator_state_, GetControlDependency(), GetEffectDependency(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::Is(), v8::internal::compiler::BytecodeGraphBuilder::jsgraph(), v8::internal::JSGeneratorObject::kGeneratorExecuting, v8::internal::compiler::BytecodeLivenessState::RegisterIsLive(), and values_.
Referenced by v8::internal::compiler::BytecodeGraphBuilder::BuildLdaLookupContextSlot(), v8::internal::compiler::BytecodeGraphBuilder::BuildLdaLookupGlobalSlot(), v8::internal::compiler::BytecodeGraphBuilder::CheckContextExtensionAtDepth(), and v8::internal::compiler::BytecodeGraphBuilder::MergeIntoSuccessorEnvironment().
parameter_count()
int v8::internal::compiler::BytecodeGraphBuilder::Environment::parameter_count () const [inline]
Definition at line 549 of file bytecode-graph-builder.cc.
{ return parameter_count_; }
References parameter_count_.
Referenced by Environment().
PrepareForLoop()
void v8::internal::compiler::BytecodeGraphBuilder::Environment::PrepareForLoop (const BytecodeLoopAssignments & assignments, const BytecodeLivenessState * liveness)
Definition at line 860 of file bytecode-graph-builder.cc.
                                           {
  // Create a control node for the loop header.
  Node* control = builder()->NewLoop();
  // Create a Phi for external effects.
  Node* effect = builder()->NewEffectPhi(1, GetEffectDependency(), control);
  UpdateEffectDependency(effect);
  // Create Phis for any values that are live on entry to the loop and may be
  // updated by the end of the loop.
  context_ = builder()->NewPhi(1, context_, control);
  for (int i = 0; i < parameter_count(); i++) {
    if (assignments.ContainsParameter(i)) {
      values_[i] = builder()->NewPhi(1, values_[i], control);
    }
  }
  for (int i = 0; i < register_count(); i++) {
    if (assignments.ContainsLocal(i) &&
        (liveness == nullptr || liveness->RegisterIsLive(i))) {
      int index = register_base() + i;
      values_[index] = builder()->NewPhi(1, values_[index], control);
    }
  }
  // The accumulator should not be live on entry.
  DCHECK_IMPLIES(liveness != nullptr, !liveness->AccumulatorIsLive());
  if (generator_state_ != nullptr) {
    generator_state_ = builder()->NewPhi(1, generator_state_, control);
  }
  // Connect to the loop end.
  Node* terminate = builder()->graph()->NewNode(
      builder()->common()->Terminate(), effect, control);
  builder()->exit_controls_.push_back(terminate);
}
References v8::internal::compiler::BytecodeLivenessState::AccumulatorIsLive(), v8::internal::compiler::BytecodeGraphBuilder::common(), v8::internal::compiler::BytecodeLoopAssignments::ContainsLocal(), v8::internal::compiler::BytecodeLoopAssignments::ContainsParameter(), DCHECK_IMPLIES, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::compiler::BytecodeLivenessState::RegisterIsLive(), and v8::internal::Terminate().
PrepareForLoopExit()
void v8::internal::compiler::BytecodeGraphBuilder::Environment::PrepareForLoopExit (Node * loop, const BytecodeLoopAssignments & assignments, const BytecodeLivenessState * liveness)
Definition at line 928 of file bytecode-graph-builder.cc.
                                           {
  DCHECK_EQ(loop->opcode(), IrOpcode::kLoop);
  Node* control = GetControlDependency();
  // Create the loop exit node.
  Node* loop_exit = graph()->NewNode(common()->LoopExit(), control, loop);
  UpdateControlDependency(loop_exit);
  // Rename the effect.
  Node* effect_rename = graph()->NewNode(common()->LoopExitEffect(),
                                         GetEffectDependency(), loop_exit);
  UpdateEffectDependency(effect_rename);
  // TODO(jarin) We should also rename context here. However, unconditional
  // renaming confuses global object and native context specialization.
  // We should only rename if the context is assigned in the loop.
  // Rename the environment values if they were assigned in the loop and are
  // live after exiting the loop.
  for (int i = 0; i < parameter_count(); i++) {
    if (assignments.ContainsParameter(i)) {
      Node* rename = graph()->NewNode(
          common()->LoopExitValue(MachineRepresentation::kTagged), values_[i],
          loop_exit);
      values_[i] = rename;
    }
  }
  for (int i = 0; i < register_count(); i++) {
    if (assignments.ContainsLocal(i) &&
        (liveness == nullptr || liveness->RegisterIsLive(i))) {
      Node* rename = graph()->NewNode(
          common()->LoopExitValue(MachineRepresentation::kTagged),
          values_[register_base() + i], loop_exit);
      values_[register_base() + i] = rename;
    }
  }
  if (liveness == nullptr || liveness->AccumulatorIsLive()) {
    Node* rename = graph()->NewNode(
        common()->LoopExitValue(MachineRepresentation::kTagged),
        values_[accumulator_base()], loop_exit);
    values_[accumulator_base()] = rename;
  }
  if (generator_state_ != nullptr) {
    generator_state_ = graph()->NewNode(
        common()->LoopExitValue(MachineRepresentation::kTagged),
        generator_state_, loop_exit);
  }
}
References v8::internal::compiler::BytecodeLivenessState::AccumulatorIsLive(), v8::internal::compiler::BytecodeGraphBuilder::common(), v8::internal::compiler::BytecodeLoopAssignments::ContainsLocal(), v8::internal::compiler::BytecodeLoopAssignments::ContainsParameter(), DCHECK_EQ, v8::internal::compiler::BytecodeGraphBuilder::graph(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kTagged, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Node::opcode(), and v8::internal::compiler::BytecodeLivenessState::RegisterIsLive().
RecordAfterState()
void v8::internal::compiler::BytecodeGraphBuilder::Environment::RecordAfterState (Node * node, FrameStateAttachmentMode mode = kDontAttachFrameState)
Definition at line 784 of file bytecode-graph-builder.cc.
                                               {
  if (mode == FrameStateAttachmentMode::kAttachFrameState) {
    builder()->PrepareFrameState(node, OutputFrameStateCombine::Ignore());
  }
}
References v8::internal::compiler::OutputFrameStateCombine::Ignore(), and mode().
register_base()
int v8::internal::compiler::BytecodeGraphBuilder::Environment::register_base () const [inline], [private]
Definition at line 616 of file bytecode-graph-builder.cc.
{ return register_base_; }
References register_base_.
register_count()
int v8::internal::compiler::BytecodeGraphBuilder::Environment::register_count () const [inline]
Definition at line 550 of file bytecode-graph-builder.cc.
{ return register_count_; }
References register_count_.
Referenced by Environment().
RegisterToValuesIndex()
int v8::internal::compiler::BytecodeGraphBuilder::Environment::RegisterToValuesIndex (interpreter::Register the_register) const [private]
Definition at line 717 of file bytecode-graph-builder.cc.
                                            {
  if (the_register.is_parameter()) {
    return the_register.ToParameterIndex();
  } else {
    return the_register.index() + register_base();
  }
}
References v8::internal::interpreter::Register::index(), v8::internal::interpreter::Register::is_parameter(), and v8::internal::interpreter::Register::ToParameterIndex().
Referenced by Environment().
SetContext()
void v8::internal::compiler::BytecodeGraphBuilder::Environment::SetContext (Node * new_context) [inline]
Definition at line 586 of file bytecode-graph-builder.cc.
{ context_ = new_context; }
References context_.
StateValuesRequireUpdate()
bool v8::internal::compiler::BytecodeGraphBuilder::Environment::StateValuesRequireUpdate (Node ** state_values, Node ** values, int count) [private]
Definition at line 913 of file bytecode-graph-builder.cc.
                                                   {
  if (*state_values == nullptr) {
    return true;
  }
  Node::Inputs inputs = (*state_values)->inputs();
  if (inputs.count() != count) return true;
  for (int i = 0; i < count; i++) {
    if (inputs[i] != values[i]) {
      return true;
    }
  }
  return false;
}
References v8::internal::compiler::Node::Inputs().
UpdateControlDependency()
void v8::internal::compiler::BytecodeGraphBuilder::Environment::UpdateControlDependency (Node * dependency) [inline]
Definition at line 581 of file bytecode-graph-builder.cc.
                                                 {
    control_dependency_ = dependency;
  }
References control_dependency_.
UpdateEffectDependency()
void v8::internal::compiler::BytecodeGraphBuilder::Environment::UpdateEffectDependency (Node * dependency) [inline]
Definition at line 569 of file bytecode-graph-builder.cc.
                                                {
    effect_dependency_ = dependency;
  }
References effect_dependency_.
UpdateStateValues()
void v8::internal::compiler::BytecodeGraphBuilder::Environment::UpdateStateValues (Node ** state_values, Node ** values, int count) [private]
Definition at line 981 of file bytecode-graph-builder.cc.
                                                                     {
  if (StateValuesRequireUpdate(state_values, values, count)) {
    const Operator* op = common()->StateValues(count, SparseInputMask::Dense());
    (*state_values) = graph()->NewNode(op, count, values);
  }
}
References v8::internal::compiler::BytecodeGraphBuilder::common(), v8::internal::compiler::SparseInputMask::Dense(), v8::internal::compiler::BytecodeGraphBuilder::graph(), v8::internal::compiler::TFGraph::NewNode(), and v8::internal::compiler::CommonOperatorBuilder::StateValues().
values() [1/2]
NodeVector* v8::internal::compiler::BytecodeGraphBuilder::Environment::values () [inline], [private]
Definition at line 615 of file bytecode-graph-builder.cc.
{ return &values_; }
References values_.
values() [2/2]
const NodeVector* v8::internal::compiler::BytecodeGraphBuilder::Environment::values () const [inline], [private]
Definition at line 614 of file bytecode-graph-builder.cc.
{ return &values_; }
References values_.
Referenced by Environment().
zone()
Zone* v8::internal::compiler::BytecodeGraphBuilder::Environment::zone () const [inline], [private]
Definition at line 610 of file bytecode-graph-builder.cc.
{ return builder_->local_zone(); }
References builder_, and v8::internal::compiler::BytecodeGraphBuilder::local_zone().
Member Data Documentation
accumulator_base_
int v8::internal::compiler::BytecodeGraphBuilder::Environment::accumulator_base_ [private]
Definition at line 629 of file bytecode-graph-builder.cc.
Referenced by accumulator_base(), and Environment().
builder_
BytecodeGraphBuilder* v8::internal::compiler::BytecodeGraphBuilder::Environment::builder_ [private]
Definition at line 619 of file bytecode-graph-builder.cc.
Referenced by builder(), common(), graph(), and zone().
context_
Node* v8::internal::compiler::BytecodeGraphBuilder::Environment::context_ [private]
Definition at line 622 of file bytecode-graph-builder.cc.
Referenced by Context(), Environment(), Merge(), and SetContext().
control_dependency_
Node* v8::internal::compiler::BytecodeGraphBuilder::Environment::control_dependency_ [private]
Definition at line 623 of file bytecode-graph-builder.cc.
Referenced by GetControlDependency(), and UpdateControlDependency().
effect_dependency_
Node* v8::internal::compiler::BytecodeGraphBuilder::Environment::effect_dependency_ [private]
Definition at line 624 of file bytecode-graph-builder.cc.
Referenced by GetEffectDependency(), and UpdateEffectDependency().
generator_state_
Node* v8::internal::compiler::BytecodeGraphBuilder::Environment::generator_state_ [private]
Definition at line 627 of file bytecode-graph-builder.cc.
Referenced by Merge().
parameter_count_
int v8::internal::compiler::BytecodeGraphBuilder::Environment::parameter_count_ [private]
Definition at line 621 of file bytecode-graph-builder.cc.
Referenced by parameter_count().
parameters_state_values_
Node* v8::internal::compiler::BytecodeGraphBuilder::Environment::parameters_state_values_ [private]
Definition at line 626 of file bytecode-graph-builder.cc.
register_base_
int v8::internal::compiler::BytecodeGraphBuilder::Environment::register_base_ [private]
Definition at line 628 of file bytecode-graph-builder.cc.
Referenced by Environment(), and register_base().
register_count_
int v8::internal::compiler::BytecodeGraphBuilder::Environment::register_count_ [private]
Definition at line 620 of file bytecode-graph-builder.cc.
Referenced by register_count().
values_
NodeVector v8::internal::compiler::BytecodeGraphBuilder::Environment::values_ [private]
Definition at line 625 of file bytecode-graph-builder.cc.
Referenced by Environment(), Merge(), and values().
Zone
friend v8::internal::compiler::BytecodeGraphBuilder::Environment::Zone [private]
Definition at line 599 of file bytecode-graph-builder.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/bytecode-graph-builder.cc