v8::internal::anonymous_namespace{builtins-riscv.cc}::RegisterAllocator Class Reference
Classes
class Scoped
Public Member Functions
RegisterAllocator (const RegList &registers)
void Ask (Register *reg)
bool registerIsAvailable (const Register &reg)
void Pinned (const Register &requested, Register *reg)
void Free (Register *reg)
void Reserve (const Register &reg)
void Reserve (const Register &reg1, const Register &reg2, const Register &reg3=no_reg, const Register &reg4=no_reg, const Register &reg5=no_reg, const Register &reg6=no_reg)
bool IsUsed (const Register &reg)
void ResetExcept (const Register &reg1=no_reg, const Register &reg2=no_reg, const Register &reg3=no_reg, const Register &reg4=no_reg, const Register &reg5=no_reg, const Register &reg6=no_reg)
Static Public Member Functions
static RegisterAllocator WithAllocatableGeneralRegisters ()
Private Attributes
std::vector< Register * > allocated_registers_
const RegList initial_
RegList available_
Detailed Description
Definition at line 3720 of file builtins-riscv.cc.
Constructor & Destructor Documentation
RegisterAllocator()
v8::internal::anonymous_namespace{builtins-riscv.cc}::RegisterAllocator::RegisterAllocator (const RegList & registers) [inline], [explicit]
Definition at line 3733 of file builtins-riscv.cc.
      : initial_(registers), available_(registers) {}
Member Function Documentation
Ask()
void v8::internal::anonymous_namespace{builtins-riscv.cc}::RegisterAllocator::Ask (Register * reg) [inline]
Definition at line 3735 of file builtins-riscv.cc.
                          {
    DCHECK_EQ(*reg, no_reg);
    DCHECK(!available_.is_empty());
    *reg = available_.PopFirst();
    allocated_registers_.push_back(reg);
  }
References v8::internal::DCHECK(), DCHECK_EQ, and v8::internal::no_reg.
Free()
void v8::internal::anonymous_namespace{builtins-riscv.cc}::RegisterAllocator::Free (Register * reg) [inline]
Definition at line 3754 of file builtins-riscv.cc.
                           {
    DCHECK_NE(*reg, no_reg);
    available_.set(*reg);
    *reg = no_reg;
    allocated_registers_.erase(
        find(allocated_registers_.begin(), allocated_registers_.end(), reg));
  }
References DCHECK_NE, and v8::internal::no_reg.
IsUsed()
bool v8::internal::anonymous_namespace{builtins-riscv.cc}::RegisterAllocator::IsUsed (const Register & reg) [inline]
Definition at line 3781 of file builtins-riscv.cc.
                                   {
    return initial_.has(reg) && !registerIsAvailable(reg);
  }
Pinned()
void v8::internal::anonymous_namespace{builtins-riscv.cc}::RegisterAllocator::Pinned (const Register & requested, Register * reg) [inline]
Definition at line 3744 of file builtins-riscv.cc.
                                                        {
    if (!registerIsAvailable(requested)) {
      printf("%s register is ocupied!", RegisterName(requested));
    }
    DCHECK(registerIsAvailable(requested));
    *reg = requested;
    Reserve(requested);
    allocated_registers_.push_back(reg);
  }
References v8::internal::DCHECK().
Referenced by v8::internal::anonymous_namespace{builtins-riscv.cc}::SwitchToAllocatedStack().
registerIsAvailable()
bool v8::internal::anonymous_namespace{builtins-riscv.cc}::RegisterAllocator::registerIsAvailable (const Register & reg) [inline]
Definition at line 3742 of file builtins-riscv.cc.
{ return available_.has(reg); }
Reserve() [1/2]
void v8::internal::anonymous_namespace{builtins-riscv.cc}::RegisterAllocator::Reserve (const Register & reg) [inline]
Definition at line 3762 of file builtins-riscv.cc.
                                    {
    if (reg == no_reg) {
      return;
    }
    DCHECK(registerIsAvailable(reg));
    available_.clear(reg);
  }
References v8::internal::DCHECK(), and v8::internal::no_reg.
Reserve() [2/2]
void v8::internal::anonymous_namespace{builtins-riscv.cc}::RegisterAllocator::Reserve (const Register & reg1, const Register & reg2, const Register & reg3 = no_reg, const Register & reg4 = no_reg, const Register & reg5 = no_reg, const Register & reg6 = no_reg) [inline]
Definition at line 3770 of file builtins-riscv.cc.
                                                                             {
    Reserve(reg1);
    Reserve(reg2);
    Reserve(reg3);
    Reserve(reg4);
    Reserve(reg5);
    Reserve(reg6);
  }
ResetExcept()
void v8::internal::anonymous_namespace{builtins-riscv.cc}::RegisterAllocator::ResetExcept (const Register & reg1 = no_reg, const Register & reg2 = no_reg, const Register & reg3 = no_reg, const Register & reg4 = no_reg, const Register & reg5 = no_reg, const Register & reg6 = no_reg) [inline]
Definition at line 3785 of file builtins-riscv.cc.
                                                  {
    available_ = initial_;
    available_.clear(reg1);
    available_.clear(reg2);
    available_.clear(reg3);
    available_.clear(reg4);
    available_.clear(reg5);
    available_.clear(reg6);
    auto it = allocated_registers_.begin();
    while (it != allocated_registers_.end()) {
      if (registerIsAvailable(**it)) {
        **it = no_reg;
        allocated_registers_.erase(it);
      } else {
        it++;
      }
    }
  }
References v8::internal::no_reg.
Referenced by v8::internal::anonymous_namespace{builtins-riscv.cc}::GenerateExceptionHandlingLandingPad(), and v8::internal::anonymous_namespace{builtins-riscv.cc}::SwitchBackAndReturnPromise().
WithAllocatableGeneralRegisters()
static RegisterAllocator v8::internal::anonymous_namespace{builtins-riscv.cc}::RegisterAllocator::WithAllocatableGeneralRegisters () [inline], [static]
Definition at line 3808 of file builtins-riscv.cc.
                                                             {
    RegList list;
    const RegisterConfiguration* config(RegisterConfiguration::Default());
    for (int i = 0; i < config->num_allocatable_general_registers(); ++i) {
      int code = config->GetAllocatableGeneralCode(i);
      Register candidate = Register::from_code(code);
      list.set(candidate);
    }
    return RegisterAllocator(list);
  }
References code, v8::internal::RegisterConfiguration::Default(), v8::internal::Register::from_code(), v8::internal::RegisterConfiguration::GetAllocatableGeneralCode(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::RegisterConfiguration::num_allocatable_general_registers(), and v8::internal::RegListBase< RegisterT >::set().
Member Data Documentation
allocated_registers_
std::vector<Register*> v8::internal::anonymous_namespace{builtins-riscv.cc}::RegisterAllocator::allocated_registers_ [private]
Definition at line 3821 of file builtins-riscv.cc.
available_
RegList v8::internal::anonymous_namespace{builtins-riscv.cc}::RegisterAllocator::available_ [private]
Definition at line 3823 of file builtins-riscv.cc.
initial_
const RegList v8::internal::anonymous_namespace{builtins-riscv.cc}::RegisterAllocator::initial_ [private]
Definition at line 3822 of file builtins-riscv.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/builtins/riscv/builtins-riscv.cc