v8::internal::KeyedStoreGenericGenerator Class Reference
#include <keyed-store-generic.h>
Static Public Member Functions
static void Generate (compiler::CodeAssemblerState *state)
static void SetProperty (compiler::CodeAssemblerState *state, TNode< Context > context, TNode< JSReceiver > receiver, TNode< BoolT > is_simple_receiver, TNode< Name > name, TNode< Object > value, LanguageMode language_mode)
static void SetProperty (compiler::CodeAssemblerState *state, TNode< Context > context, TNode< JSAny > receiver, TNode< Object > key, TNode< Object > value, LanguageMode language_mode)
static void CreateDataProperty (compiler::CodeAssemblerState *state, TNode< Context > context, TNode< JSObject > receiver, TNode< Object > key, TNode< Object > value)
Detailed Description
Definition at line 19 of file keyed-store-generic.h.
Member Function Documentation
CreateDataProperty()
void v8::internal::KeyedStoreGenericGenerator::CreateDataProperty (compiler::CodeAssemblerState * state, TNode< Context > context, TNode< JSObject > receiver, TNode< Object > key, TNode< Object > value) [static]
Definition at line 259 of file keyed-store-generic.cc.
                                                                      {
  KeyedStoreGenericAssembler assembler(state,
                                       StoreMode::kDefineKeyedOwnInLiteral);
  assembler.StoreProperty(context, receiver, key, value, LanguageMode::kStrict);
}
References v8::internal::kDefineKeyedOwnInLiteral, v8::internal::key, v8::internal::kStrict, v8::internal::KeyedStoreGenericAssembler::StoreProperty(), and v8::internal::value.
Referenced by v8::internal::TF_BUILTIN().
Generate()
void v8::internal::KeyedStoreGenericGenerator::Generate (compiler::CodeAssemblerState * state) [static]
Definition at line 212 of file keyed-store-generic.cc.
                                                                           {
  KeyedStoreGenericAssembler assembler(state, StoreMode::kSet);
  assembler.KeyedStoreGeneric();
}
References v8::internal::KeyedStoreGenericAssembler::KeyedStoreGeneric(), and v8::internal::kSet.
SetProperty() [1/2]
void v8::internal::KeyedStoreGenericGenerator::SetProperty (compiler::CodeAssemblerState * state, TNode< Context > context, TNode< JSAny > receiver, TNode< Object > key, TNode< Object > value, LanguageMode language_mode) [static]
Definition at line 250 of file keyed-store-generic.cc.
                                {
  KeyedStoreGenericAssembler assembler(state, StoreMode::kSet);
  assembler.StoreProperty(context, receiver, key, value, language_mode);
}
References v8::internal::key, v8::internal::kSet, v8::internal::KeyedStoreGenericAssembler::StoreProperty(), and v8::internal::value.
SetProperty() [2/2]
void v8::internal::KeyedStoreGenericGenerator::SetProperty (compiler::CodeAssemblerState * state, TNode< Context > context, TNode< JSReceiver > receiver, TNode< BoolT > is_simple_receiver, TNode< Name > name, TNode< Object > value, LanguageMode language_mode) [static]
Definition at line 240 of file keyed-store-generic.cc.
                                                                       {
  KeyedStoreGenericAssembler assembler(state, StoreMode::kSet);
  assembler.StoreProperty(context, receiver, is_simple_receiver, name, value,
                          language_mode);
}
References v8::internal::kSet, v8::internal::name, v8::internal::KeyedStoreGenericAssembler::StoreProperty(), and v8::internal::value.
Referenced by v8::internal::anonymous_namespace{builtins-internal-gen.cc}::SetOrCopyDataPropertiesAssembler::SetOrCopyDataProperties(), and v8::internal::TF_BUILTIN().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ic/keyed-store-generic.h
/mnt/V8SourceCode/src/ic/keyed-store-generic.cc