v8::internal::Windows1252CharacterStream Class Reference
Public Member Functions
Windows1252CharacterStream (size_t pos, ScriptCompiler::ExternalSourceStream *source_stream)
bool can_be_cloned () const final
std::unique_ptr< Utf16CharacterStream > Clone () const override
Protected Member Functions
bool ReadBlock (size_t position) final
bool can_access_heap () const final
Private Member Functions
Windows1252CharacterStream (const Windows1252CharacterStream &other) V8_NOEXCEPT
Private Attributes
base::uc16 buffer_ [kBufferSize]
ChunkedStream< uint8_t > byte_stream_
Static Private Attributes
static const size_t kBufferSize = 512
Additional Inherited Members
Detailed Description
Definition at line 463 of file scanner-character-streams.cc.
Constructor & Destructor Documentation
Windows1252CharacterStream() [1/2]
v8::internal::Windows1252CharacterStream::Windows1252CharacterStream (size_t pos, ScriptCompiler::ExternalSourceStream * source_stream) [inline]
Definition at line 465 of file scanner-character-streams.cc.
      : byte_stream_(source_stream) {
    buffer_pos_ = pos;
  }
References v8::internal::Utf16CharacterStream::buffer_pos_, and v8::internal::Utf16CharacterStream::pos().
Referenced by Clone().
Windows1252CharacterStream() [2/2]
v8::internal::Windows1252CharacterStream::Windows1252CharacterStream (const Windows1252CharacterStream & other) [inline], [private]
Definition at line 507 of file scanner-character-streams.cc.
                  : byte_stream_(other.byte_stream_) {}
Member Function Documentation
can_access_heap()
bool v8::internal::Windows1252CharacterStream::can_access_heap () const [inline], [final], [protected], [virtual]
Implements v8::internal::Utf16CharacterStream.
Definition at line 502 of file scanner-character-streams.cc.
                                     {
    return ChunkedStream<uint8_t>::kCanAccessHeap;
  }
can_be_cloned()
bool v8::internal::Windows1252CharacterStream::can_be_cloned () const [inline], [final], [virtual]
Implements v8::internal::Utf16CharacterStream.
Definition at line 471 of file scanner-character-streams.cc.
                                   {
    return ChunkedStream<uint16_t>::kCanBeCloned;
  }
Referenced by Clone().
Clone()
std::unique_ptr<Utf16CharacterStream> v8::internal::Windows1252CharacterStream::Clone () const [inline], [override], [virtual]
Implements v8::internal::Utf16CharacterStream.
Definition at line 475 of file scanner-character-streams.cc.
                                                             {
    CHECK(can_be_cloned());
    return std::unique_ptr<Utf16CharacterStream>(
        new Windows1252CharacterStream(*this));
  }
References can_be_cloned(), CHECK, and Windows1252CharacterStream().
ReadBlock()
bool v8::internal::Windows1252CharacterStream::ReadBlock (size_t position) [inline], [final], [protected], [virtual]
Implements v8::internal::Utf16CharacterStream.
Definition at line 482 of file scanner-character-streams.cc.
                                        {
    buffer_pos_ = position;
    buffer_start_ = &buffer_[0];
    buffer_cursor_ = buffer_start_;
    DisallowGarbageCollection no_gc;
    Range<uint8_t> range =
        byte_stream_.GetDataAt(position, runtime_call_stats(), &no_gc);
    if (range.length() == 0) {
      buffer_end_ = buffer_start_;
      return false;
    }
    size_t length = std::min({kBufferSize, range.length()});
    std::transform(range.start, range.start + length, &buffer_[0],
                   [](uint8_t c) { return kWindows1252ToUC16[c]; });
    buffer_end_ = &buffer_[length];
    return true;
  }
References buffer_, v8::internal::Utf16CharacterStream::buffer_cursor_, v8::internal::Utf16CharacterStream::buffer_end_, v8::internal::Utf16CharacterStream::buffer_pos_, v8::internal::Utf16CharacterStream::buffer_start_, byte_stream_, v8::internal::ChunkedStream< Char >::GetDataAt(), kBufferSize, v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::Utf16CharacterStream::runtime_call_stats().
Member Data Documentation
buffer_
base::uc16 v8::internal::Windows1252CharacterStream::buffer_[kBufferSize] [private]
Definition at line 511 of file scanner-character-streams.cc.
Referenced by ReadBlock().
byte_stream_
ChunkedStream<uint8_t> v8::internal::Windows1252CharacterStream::byte_stream_ [private]
Definition at line 512 of file scanner-character-streams.cc.
Referenced by ReadBlock().
kBufferSize
const size_t v8::internal::Windows1252CharacterStream::kBufferSize = 512 [static], [private]
Definition at line 510 of file scanner-character-streams.cc.
Referenced by ReadBlock().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/parsing/scanner-character-streams.cc