v8::internal::torque::TypeAlias Class Reference
#include <declarable.h>
Public Member Functions
const Type * type () const
const Type * Resolve () const
bool IsRedeclaration () const
SourcePosition GetDeclarationPosition () const
Private Member Functions
TypeAlias (const Type *type, bool redeclaration, SourcePosition declaration_position=SourcePosition::Invalid())
TypeAlias (TypeDeclaration *type, bool redeclaration, SourcePosition declaration_position=SourcePosition::Invalid())
Private Attributes
bool being_resolved_ = false
std::optional< TypeDeclaration * > delayed_
std::optional< const Type * > type_
bool redeclaration_
const SourcePosition declaration_position_
Friends
class Declarations
class TypeVisitor
Additional Inherited Members
Detailed Description
Definition at line 669 of file declarable.h.
Constructor & Destructor Documentation
TypeAlias() [1/2]
v8::internal::torque::TypeAlias::TypeAlias (const Type * type, bool redeclaration, SourcePosition declaration_position = SourcePosition::Invalid()) [inline], [explicit], [private]
Definition at line 687 of file declarable.h.
      : Declarable(Declarable::kTypeAlias),
        type_(type),
        redeclaration_(redeclaration),
        declaration_position_(declaration_position) {}
TypeAlias() [2/2]
v8::internal::torque::TypeAlias::TypeAlias (TypeDeclaration * type, bool redeclaration, SourcePosition declaration_position = SourcePosition::Invalid()) [inline], [explicit], [private]
Definition at line 694 of file declarable.h.
      : Declarable(Declarable::kTypeAlias),
        delayed_(type),
        redeclaration_(redeclaration),
        declaration_position_(declaration_position) {}
Member Function Documentation
GetDeclarationPosition()
SourcePosition v8::internal::torque::TypeAlias::GetDeclarationPosition () const [inline]
Definition at line 679 of file declarable.h.
                                                {
    return declaration_position_;
  }
References declaration_position_.
Referenced by v8::internal::torque::Declarations::LookupType().
IsRedeclaration()
bool v8::internal::torque::TypeAlias::IsRedeclaration () const [inline]
Definition at line 678 of file declarable.h.
{ return redeclaration_; }
References redeclaration_.
Referenced by v8::internal::torque::ImplementationVisitor::Visit().
Resolve()
const Type * v8::internal::torque::TypeAlias::Resolve () const
Definition at line 180 of file declarable.cc.
                                     {
  if (!type_) {
    CurrentScope::Scope scope_activator(ParentScope());
    CurrentSourcePosition::Scope position_activator(Position());
    TypeDeclaration* decl = *delayed_;
    if (being_resolved_) {
      std::stringstream s;
      s << "Cannot create type " << decl->name->value
        << " due to circular dependencies.";
      ReportError(s.str());
    }
    type_ = TypeVisitor::ComputeType(decl);
  }
  return *type_;
}
References being_resolved_, v8::internal::torque::TypeVisitor::ComputeType(), delayed_, v8::internal::torque::TypeDeclaration::name, v8::internal::torque::Declarable::ParentScope(), v8::internal::torque::Declarable::Position(), v8::internal::torque::ReportError(), type_, and v8::internal::torque::Identifier::value.
Referenced by type().
type()
const Type* v8::internal::torque::TypeAlias::type () const [inline]
Definition at line 673 of file declarable.h.
                           {
    if (type_) return *type_;
    return Resolve();
  }
References Resolve(), and type_.
Referenced by v8::internal::torque::Declarations::LookupGlobalType(), v8::internal::torque::Declarations::LookupType(), and v8::internal::torque::ImplementationVisitor::Visit().
Friends And Related Function Documentation
Declarations
friend class Declarations [friend]
Definition at line 684 of file declarable.h.
TypeVisitor
friend class TypeVisitor [friend]
Definition at line 685 of file declarable.h.
Member Data Documentation
being_resolved_
bool v8::internal::torque::TypeAlias::being_resolved_ = false [mutable], [private]
Definition at line 702 of file declarable.h.
Referenced by Resolve().
declaration_position_
const SourcePosition v8::internal::torque::TypeAlias::declaration_position_ [private]
Definition at line 706 of file declarable.h.
Referenced by GetDeclarationPosition().
delayed_
std::optional<TypeDeclaration*> v8::internal::torque::TypeAlias::delayed_ [mutable], [private]
Definition at line 703 of file declarable.h.
Referenced by v8::internal::torque::TypeVisitor::ComputeType(), and Resolve().
redeclaration_
bool v8::internal::torque::TypeAlias::redeclaration_ [private]
Definition at line 705 of file declarable.h.
Referenced by IsRedeclaration().
type_
std::optional<const Type*> v8::internal::torque::TypeAlias::type_ [mutable], [private]
Definition at line 704 of file declarable.h.
Referenced by Resolve(), and type().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/torque/declarable.h
/mnt/V8SourceCode/src/torque/declarable.cc