v8::internal::compiler::BasicBlock::Id Class Reference
#include <schedule.h>
Public Member Functions
int ToInt () const
size_t ToSize () const
Static Public Member Functions
static Id FromSize (size_t index)
static Id FromInt (int index)
Private Member Functions
Id (size_t index)
Private Attributes
size_t index_
Detailed Description
Definition at line 46 of file schedule.h.
Constructor & Destructor Documentation
Id()
v8::internal::compiler::BasicBlock::Id::Id (size_t index) [inline], [explicit], [private]
Definition at line 54 of file schedule.h.
: index_(index) {}
Member Function Documentation
FromInt()
static Id v8::internal::compiler::BasicBlock::Id::FromInt (int index) [inline], [static]
Definition at line 51 of file schedule.h.
{ return Id(static_cast<size_t>(index)); }
References v8::internal::index.
Referenced by v8::internal::compiler::SpecialRPONumberer::BeyondEndSentinel(), v8::internal::compiler::ScheduleVerifier::Run(), and v8::internal::compiler::Scheduler::SealFinalSchedule().
FromSize()
static Id v8::internal::compiler::BasicBlock::Id::FromSize (size_t index) [inline], [static]
Definition at line 50 of file schedule.h.
{ return Id(index); }
References v8::internal::index.
Referenced by v8::internal::compiler::Schedule::NewBasicBlock().
ToInt()
int v8::internal::compiler::BasicBlock::Id::ToInt () const [inline]
Definition at line 48 of file schedule.h.
{ return static_cast<int>(index_); }
Referenced by v8::internal::compiler::StringBuilderOptimizer::BlockShouldFinalizeStringBuilders(), v8::internal::compiler::CFGBuilder::BuildBlockForNode(), v8::internal::compiler::SpecialRPONumberer::ComputeAndInsertSpecialRPO(), v8::internal::compiler::SpecialRPONumberer::ComputeLoopInfo(), v8::internal::compiler::Scheduler::GetCommonDominator(), v8::internal::compiler::Scheduler::GetCommonDominatorIfCached(), v8::internal::compiler::StringBuilderOptimizer::GetStringBuildersToFinalize(), v8::internal::compiler::BasicBlockInstrumentor::Instrument(), v8::internal::compiler::ScheduleLateNodeVisitor::IsMarked(), v8::internal::compiler::ScheduleLateNodeVisitor::Mark(), v8::internal::compiler::Scheduler::MovePlannedNodes(), v8::internal::compiler::Scheduler::PropagateImmediateDominators(), v8::internal::compiler::ScheduleEarlyNodeVisitor::PropagateMinimumPositionToNode(), v8::internal::compiler::ScheduleVerifier::Run(), v8::internal::compiler::ScheduleLateNodeVisitor::SplitNode(), v8::internal::compiler::BasicBlockCallGraphProfiler::StoreCallGraph(), v8::internal::compiler::CFGBuilder::TraceConnect(), v8::internal::compiler::ScheduleEarlyNodeVisitor::VisitNode(), and v8::internal::compiler::ScheduleLateNodeVisitor::VisitNode().
ToSize()
size_t v8::internal::compiler::BasicBlock::Id::ToSize () const [inline]
Definition at line 49 of file schedule.h.
{ return index_; }
Referenced by v8::internal::compiler::Schedule::ClearBlockById(), v8::internal::compiler::Schedule::GetBlockById(), v8::internal::compiler::RawMachineAssembler::MakeReschedulable(), v8::internal::compiler::Scheduler::MovePlannedNodes(), v8::internal::compiler::ScheduleVerifier::Run(), and v8::internal::compiler::ScheduleLateNodeVisitor::ScheduleNode().
Member Data Documentation
index_
size_t v8::internal::compiler::BasicBlock::Id::index_ [private]
Definition at line 55 of file schedule.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/schedule.h