v8::internal::TypedArrayBuiltinsAssembler Class Reference
#include <builtins-typed-array-gen.h>
Public Types
using ElementsInfo = TorqueStructTypedArrayElementsInfo
using TypedArraySwitchCase = std::function< void(ElementsKind, int, int)>
Public Member Functions
TypedArrayBuiltinsAssembler (compiler::CodeAssemblerState *state)
void SetupTypedArrayEmbedderFields (TNode< JSTypedArray > holder)
void AttachBuffer (TNode< JSTypedArray > holder, TNode< JSArrayBuffer > buffer, TNode< Map > map, TNode< Smi > length, TNode< UintPtrT > byte_offset)
TNode< JSArrayBuffer > AllocateEmptyOnHeapBuffer (TNode< Context > context)
TNode< Map > LoadMapForType (TNode< JSTypedArray > array)
TNode< BoolT > IsMockArrayBufferAllocatorFlag ()
TNode< UintPtrT > CalculateExternalPointer (TNode< UintPtrT > backing_store, TNode< UintPtrT > byte_offset)
TNode< BoolT > IsUint8ElementsKind (TNode< Int32T > kind)
TNode< BoolT > IsBigInt64ElementsKind (TNode< Int32T > kind)
TNode< IntPtrT > GetTypedArrayElementSize (TNode< Int32T > elements_kind)
ElementsInfo GetTypedArrayElementsInfo (TNode< JSTypedArray > typed_array)
ElementsInfo GetTypedArrayElementsInfo (TNode< Map > map)
TNode< JSFunction > GetDefaultConstructor (TNode< Context > context, TNode< JSTypedArray > exemplar)
TNode< JSTypedArray > ValidateTypedArray (TNode< Context > context, TNode< Object > obj, const char *method_name)
TNode< UintPtrT > ValidateTypedArrayAndGetLength (TNode< Context > context, TNode< Object > obj, const char *method_name)
void CallCMemmove (TNode< RawPtrT > dest_ptr, TNode< RawPtrT > src_ptr, TNode< UintPtrT > byte_length)
void CallCRelaxedMemmove (TNode< RawPtrT > dest_ptr, TNode< RawPtrT > src_ptr, TNode< UintPtrT > byte_length)
void CallCMemcpy (TNode< RawPtrT > dest_ptr, TNode< RawPtrT > src_ptr, TNode< UintPtrT > byte_length)
void CallCRelaxedMemcpy (TNode< RawPtrT > dest_ptr, TNode< RawPtrT > src_ptr, TNode< UintPtrT > byte_length)
void CallCMemset (TNode< RawPtrT > dest_ptr, TNode< IntPtrT > value, TNode< UintPtrT > length)
void CallCCopyFastNumberJSArrayElementsToTypedArray (TNode< Context > context, TNode< JSArray > source, TNode< JSTypedArray > dest, TNode< UintPtrT > source_length, TNode< UintPtrT > offset)
void CallCCopyTypedArrayElementsToTypedArray (TNode< JSTypedArray > source, TNode< JSTypedArray > dest, TNode< UintPtrT > source_length, TNode< UintPtrT > offset)
void CallCCopyTypedArrayElementsSlice (TNode< JSTypedArray > source, TNode< JSTypedArray > dest, TNode< UintPtrT > start, TNode< UintPtrT > end)
void DispatchTypedArrayByElementsKind (TNode< Word32T > elements_kind, const TypedArraySwitchCase &case_function)
void SetJSTypedArrayOnHeapDataPtr (TNode< JSTypedArray > holder, TNode< ByteArray > base, TNode< UintPtrT > offset)
void SetJSTypedArrayOffHeapDataPtr (TNode< JSTypedArray > holder, TNode< RawPtrT > base, TNode< UintPtrT > offset)
void StoreJSTypedArrayElementFromNumeric (TNode< Context > context, TNode< JSTypedArray > typed_array, TNode< UintPtrT > index_node, TNode< Numeric > value, ElementsKind elements_kind)
void StoreJSTypedArrayElementFromTagged (TNode< Context > context, TNode< JSTypedArray > typed_array, TNode< UintPtrT > index_node, TNode< Object > value, ElementsKind elements_kind, Label *if_detached_or_out_of_bounds)
template<typename TValue >
void StoreJSTypedArrayElementFromPreparedValue (TNode< Context > context, TNode< JSTypedArray > typed_array, TNode< UintPtrT > index_node, TNode< TValue > value, ElementsKind elements_kind, Label *if_detached_or_out_of_bounds)
Additional Inherited Members
Detailed Description
Definition at line 13 of file builtins-typed-array-gen.h.
Member Typedef Documentation
ElementsInfo
using v8::internal::TypedArrayBuiltinsAssembler::ElementsInfo = TorqueStructTypedArrayElementsInfo
Definition at line 15 of file builtins-typed-array-gen.h.
TypedArraySwitchCase
using v8::internal::TypedArrayBuiltinsAssembler::TypedArraySwitchCase = std::function<void(ElementsKind, int, int)>
Definition at line 86 of file builtins-typed-array-gen.h.
Constructor & Destructor Documentation
TypedArrayBuiltinsAssembler()
v8::internal::TypedArrayBuiltinsAssembler::TypedArrayBuiltinsAssembler (compiler::CodeAssemblerState * state) [inline], [explicit]
Definition at line 16 of file builtins-typed-array-gen.h.
      : CodeStubAssembler(state) {}
Member Function Documentation
AllocateEmptyOnHeapBuffer()
TNode< JSArrayBuffer > v8::internal::TypedArrayBuiltinsAssembler::AllocateEmptyOnHeapBuffer (TNode< Context > context)
Definition at line 39 of file builtins-typed-array-gen.cc.
                            {
  TNode<NativeContext> native_context = LoadNativeContext(context);
  TNode<Map> map = CAST(LoadContextElementNoCell(
      native_context, Context::ARRAY_BUFFER_MAP_INDEX));
  TNode<FixedArray> empty_fixed_array = EmptyFixedArrayConstant();
  TNode<JSArrayBuffer> buffer = UncheckedCast<JSArrayBuffer>(
      Allocate(JSArrayBuffer::kSizeWithEmbedderFields));
  StoreMapNoWriteBarrier(buffer, map);
  StoreObjectFieldNoWriteBarrier(buffer, JSArray::kPropertiesOrHashOffset,
                                 empty_fixed_array);
  StoreObjectFieldNoWriteBarrier(buffer, JSArray::kElementsOffset,
                                 empty_fixed_array);
  // Setup the ArrayBuffer.
  // - Set BitField to 0.
  // - Set IsExternal and IsDetachable bits of BitFieldSlot.
  // - Set the byte_length field to zero.
  // - Set backing_store to null/Tagged<Smi>(0).
  // - Set extension to null.
  // - Set all embedder fields to Tagged<Smi>(0).
  if (FIELD_SIZE(JSArrayBuffer::kOptionalPaddingOffset) != 0) {
    DCHECK_EQ(4, FIELD_SIZE(JSArrayBuffer::kOptionalPaddingOffset));
    StoreObjectFieldNoWriteBarrier(
        buffer, JSArrayBuffer::kOptionalPaddingOffset, Int32Constant(0));
  }
  int32_t bitfield_value = (1 << JSArrayBuffer::IsExternalBit::kShift) |
                           (1 << JSArrayBuffer::IsDetachableBit::kShift);
  StoreObjectFieldNoWriteBarrier(buffer, JSArrayBuffer::kBitFieldOffset,
                                 Int32Constant(bitfield_value));
  StoreObjectFieldNoWriteBarrier(buffer, JSArrayBuffer::kDetachKeyOffset,
                                 UndefinedConstant());
  StoreBoundedSizeToObject(buffer, JSArrayBuffer::kRawByteLengthOffset,
                           UintPtrConstant(0));
  StoreBoundedSizeToObject(buffer, JSArrayBuffer::kRawMaxByteLengthOffset,
                           UintPtrConstant(0));
  StoreSandboxedPointerToObject(buffer, JSArrayBuffer::kBackingStoreOffset,
                                EmptyBackingStoreBufferConstant());
#ifdef V8_COMPRESS_POINTERS
  // When pointer compression is enabled, the extension slot contains a
  // (lazily-initialized) external pointer handle.
  StoreObjectFieldNoWriteBarrier(buffer, JSArrayBuffer::kExtensionOffset,
                                 ExternalPointerHandleNullConstant());
#else
  StoreObjectFieldNoWriteBarrier(buffer, JSArrayBuffer::kExtensionOffset,
                                 IntPtrConstant(0));
#endif
  InitializeJSAPIObjectWithEmbedderSlotsCppHeapWrapperPtr(buffer);
  for (int offset = JSArrayBuffer::kHeaderSize;
       offset < JSArrayBuffer::kSizeWithEmbedderFields; offset += kTaggedSize) {
    // TODO(v8:10391, saelo): Handle external pointers in EmbedderDataSlot
    StoreObjectFieldNoWriteBarrier(buffer, offset, SmiConstant(0));
  }
  return buffer;
}
References v8::internal::CodeStubAssembler::Allocate(), CAST, DCHECK_EQ, v8::internal::CodeStubAssembler::EmptyBackingStoreBufferConstant(), v8::internal::compiler::CodeAssembler::ExternalPointerHandleNullConstant(), FIELD_SIZE, v8::internal::CodeStubAssembler::InitializeJSAPIObjectWithEmbedderSlotsCppHeapWrapperPtr(), v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::JSArrayBuffer::kSizeWithEmbedderFields, v8::internal::kTaggedSize, v8::internal::CodeStubAssembler::LoadNativeContext(), v8::internal::native_context, v8::internal::compiler::CodeAssembler::SmiConstant(), v8::internal::CodeStubAssembler::StoreBoundedSizeToObject(), v8::internal::CodeStubAssembler::StoreMapNoWriteBarrier(), v8::internal::CodeStubAssembler::StoreObjectFieldNoWriteBarrier(), v8::internal::CodeStubAssembler::StoreSandboxedPointerToObject(), v8::internal::compiler::CodeAssembler::UintPtrConstant(), and v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
AttachBuffer()
void v8::internal::TypedArrayBuiltinsAssembler::AttachBuffer (TNode< JSTypedArray > holder, TNode< JSArrayBuffer > buffer, TNode< Map > map, TNode< Smi > length, TNode< UintPtrT > byte_offset)
CalculateExternalPointer()
TNode<UintPtrT> v8::internal::TypedArrayBuiltinsAssembler::CalculateExternalPointer (TNode< UintPtrT > backing_store, TNode< UintPtrT > byte_offset)
CallCCopyFastNumberJSArrayElementsToTypedArray()
void v8::internal::TypedArrayBuiltinsAssembler::CallCCopyFastNumberJSArrayElementsToTypedArray (TNode< Context > context, TNode< JSArray > source, TNode< JSTypedArray > dest, TNode< UintPtrT > source_length, TNode< UintPtrT > offset)
Definition at line 360 of file builtins-typed-array-gen.cc.
                                                               {
  CSA_DCHECK(this,
             Word32BinaryNot(IsBigInt64ElementsKind(LoadElementsKind(dest))));
  TNode<ExternalReference> f = ExternalConstant(
      ExternalReference::copy_fast_number_jsarray_elements_to_typed_array());
  CallCFunction(f, MachineType::AnyTagged(),
                std::make_pair(MachineType::AnyTagged(), context),
                std::make_pair(MachineType::AnyTagged(), source),
                std::make_pair(MachineType::AnyTagged(), dest),
                std::make_pair(MachineType::UintPtr(), source_length),
                std::make_pair(MachineType::UintPtr(), offset));
}
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::CodeAssembler::CallCFunction(), v8::internal::compiler::CodeAssembler::ExternalConstant(), IsBigInt64ElementsKind(), v8::internal::CodeStubAssembler::LoadElementsKind(), and v8::internal::MachineType::UintPtr().
CallCCopyTypedArrayElementsSlice()
void v8::internal::TypedArrayBuiltinsAssembler::CallCCopyTypedArrayElementsSlice (TNode< JSTypedArray > source, TNode< JSTypedArray > dest, TNode< UintPtrT > start, TNode< UintPtrT > end)
Definition at line 388 of file builtins-typed-array-gen.cc.
                         {
  TNode<ExternalReference> f =
      ExternalConstant(ExternalReference::copy_typed_array_elements_slice());
  CallCFunction(f, MachineType::AnyTagged(),
                std::make_pair(MachineType::AnyTagged(), source),
                std::make_pair(MachineType::AnyTagged(), dest),
                std::make_pair(MachineType::UintPtr(), start),
                std::make_pair(MachineType::UintPtr(), end));
}
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::CodeAssembler::CallCFunction(), v8::internal::compiler::end(), v8::internal::compiler::CodeAssembler::ExternalConstant(), and v8::internal::MachineType::UintPtr().
CallCCopyTypedArrayElementsToTypedArray()
void v8::internal::TypedArrayBuiltinsAssembler::CallCCopyTypedArrayElementsToTypedArray (TNode< JSTypedArray > source, TNode< JSTypedArray > dest, TNode< UintPtrT > source_length, TNode< UintPtrT > offset)
Definition at line 376 of file builtins-typed-array-gen.cc.
                                                           {
  TNode<ExternalReference> f = ExternalConstant(
      ExternalReference::copy_typed_array_elements_to_typed_array());
  CallCFunction(f, MachineType::AnyTagged(),
                std::make_pair(MachineType::AnyTagged(), source),
                std::make_pair(MachineType::AnyTagged(), dest),
                std::make_pair(MachineType::UintPtr(), source_length),
                std::make_pair(MachineType::UintPtr(), offset));
}
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::CodeAssembler::CallCFunction(), v8::internal::compiler::CodeAssembler::ExternalConstant(), and v8::internal::MachineType::UintPtr().
CallCMemcpy()
void v8::internal::TypedArrayBuiltinsAssembler::CallCMemcpy (TNode< RawPtrT > dest_ptr, TNode< RawPtrT > src_ptr, TNode< UintPtrT > byte_length)
Definition at line 327 of file builtins-typed-array-gen.cc.
                                                                           {
  TNode<ExternalReference> memcpy =
      ExternalConstant(ExternalReference::libc_memcpy_function());
  CallCFunction(memcpy, MachineType::AnyTagged(),
                std::make_pair(MachineType::Pointer(), dest_ptr),
                std::make_pair(MachineType::Pointer(), src_ptr),
                std::make_pair(MachineType::UintPtr(), byte_length));
}
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::CodeAssembler::CallCFunction(), v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::internal::MachineType::Pointer(), and v8::internal::MachineType::UintPtr().
CallCMemmove()
void v8::internal::TypedArrayBuiltinsAssembler::CallCMemmove (TNode< RawPtrT > dest_ptr, TNode< RawPtrT > src_ptr, TNode< UintPtrT > byte_length)
Definition at line 305 of file builtins-typed-array-gen.cc.
                                                                            {
  TNode<ExternalReference> memmove =
      ExternalConstant(ExternalReference::libc_memmove_function());
  CallCFunction(memmove, MachineType::AnyTagged(),
                std::make_pair(MachineType::Pointer(), dest_ptr),
                std::make_pair(MachineType::Pointer(), src_ptr),
                std::make_pair(MachineType::UintPtr(), byte_length));
}
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::CodeAssembler::CallCFunction(), v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::internal::MachineType::Pointer(), and v8::internal::MachineType::UintPtr().
CallCMemset()
void v8::internal::TypedArrayBuiltinsAssembler::CallCMemset (TNode< RawPtrT > dest_ptr, TNode< IntPtrT > value, TNode< UintPtrT > length)
Definition at line 349 of file builtins-typed-array-gen.cc.
                                                                      {
  TNode<ExternalReference> memset =
      ExternalConstant(ExternalReference::libc_memset_function());
  CallCFunction(memset, MachineType::AnyTagged(),
                std::make_pair(MachineType::Pointer(), dest_ptr),
                std::make_pair(MachineType::IntPtr(), value),
                std::make_pair(MachineType::UintPtr(), length));
}
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::CodeAssembler::CallCFunction(), v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::internal::MachineType::IntPtr(), v8::internal::length, v8::internal::MachineType::Pointer(), v8::internal::MachineType::UintPtr(), and v8::internal::value.
CallCRelaxedMemcpy()
void v8::internal::TypedArrayBuiltinsAssembler::CallCRelaxedMemcpy (TNode< RawPtrT > dest_ptr, TNode< RawPtrT > src_ptr, TNode< UintPtrT > byte_length)
Definition at line 338 of file builtins-typed-array-gen.cc.
                                 {
  TNode<ExternalReference> relaxed_memcpy =
      ExternalConstant(ExternalReference::relaxed_memcpy_function());
  CallCFunction(relaxed_memcpy, MachineType::AnyTagged(),
                std::make_pair(MachineType::Pointer(), dest_ptr),
                std::make_pair(MachineType::Pointer(), src_ptr),
                std::make_pair(MachineType::UintPtr(), byte_length));
}
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::CodeAssembler::CallCFunction(), v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::internal::MachineType::Pointer(), v8::internal::relaxed_memcpy(), and v8::internal::MachineType::UintPtr().
CallCRelaxedMemmove()
void v8::internal::TypedArrayBuiltinsAssembler::CallCRelaxedMemmove (TNode< RawPtrT > dest_ptr, TNode< RawPtrT > src_ptr, TNode< UintPtrT > byte_length)
Definition at line 316 of file builtins-typed-array-gen.cc.
                                 {
  TNode<ExternalReference> memmove =
      ExternalConstant(ExternalReference::relaxed_memmove_function());
  CallCFunction(memmove, MachineType::AnyTagged(),
                std::make_pair(MachineType::Pointer(), dest_ptr),
                std::make_pair(MachineType::Pointer(), src_ptr),
                std::make_pair(MachineType::UintPtr(), byte_length));
}
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::CodeAssembler::CallCFunction(), v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::internal::MachineType::Pointer(), and v8::internal::MachineType::UintPtr().
DispatchTypedArrayByElementsKind()
void v8::internal::TypedArrayBuiltinsAssembler::DispatchTypedArrayByElementsKind (TNode< Word32T > elements_kind, const TypedArraySwitchCase & case_function)
Definition at line 400 of file builtins-typed-array-gen.cc.
                                                                             {
  Label next(this), if_unknown_type(this, Label::kDeferred);
  int32_t elements_kinds[] = {
#define TYPED_ARRAY_CASE(Type, type, TYPE, ctype) TYPE##_ELEMENTS,
      TYPED_ARRAYS(TYPED_ARRAY_CASE) RAB_GSAB_TYPED_ARRAYS(TYPED_ARRAY_CASE)
#undef TYPED_ARRAY_CASE
  };
#define TYPED_ARRAY_CASE(Type, type, TYPE, ctype) Label if_##type##array(this);
  TYPED_ARRAYS(TYPED_ARRAY_CASE)
  RAB_GSAB_TYPED_ARRAYS(TYPED_ARRAY_CASE)
#undef TYPED_ARRAY_CASE
  Label* elements_kind_labels[] = {
#define TYPED_ARRAY_CASE(Type, type, TYPE, ctype) &if_##type##array,
      TYPED_ARRAYS(TYPED_ARRAY_CASE) RAB_GSAB_TYPED_ARRAYS(TYPED_ARRAY_CASE)
#undef TYPED_ARRAY_CASE
  };
  static_assert(arraysize(elements_kinds) == arraysize(elements_kind_labels));
  Switch(elements_kind, &if_unknown_type, elements_kinds, elements_kind_labels,
         arraysize(elements_kinds));
#define TYPED_ARRAY_CASE(Type, type, TYPE, ctype) \
  BIND(&if_##type##array); \
  { \
    case_function(TYPE##_ELEMENTS, sizeof(ctype), \
                  Context::TYPE##_ARRAY_FUN_INDEX); \
    Goto(&next); \
  }
  TYPED_ARRAYS(TYPED_ARRAY_CASE)
#undef TYPED_ARRAY_CASE
#define TYPED_ARRAY_CASE(Type, type, TYPE, ctype, NON_RAB_GSAB_TYPE) \
  BIND(&if_##type##array); \
  { \
    case_function(TYPE##_ELEMENTS, sizeof(ctype), \
                  Context::NON_RAB_GSAB_TYPE##_ARRAY_FUN_INDEX); \
    Goto(&next); \
  }
  RAB_GSAB_TYPED_ARRAYS_WITH_NON_RAB_GSAB_ELEMENTS_KIND(TYPED_ARRAY_CASE)
#undef TYPED_ARRAY_CASE
  BIND(&if_unknown_type);
  Unreachable();
  BIND(&next);
}
References arraysize, v8::internal::compiler::CodeAssemblerLabel::kDeferred, RAB_GSAB_TYPED_ARRAYS, RAB_GSAB_TYPED_ARRAYS_WITH_NON_RAB_GSAB_ELEMENTS_KIND, v8::internal::compiler::CodeAssembler::Switch(), TYPED_ARRAY_CASE, TYPED_ARRAYS, and v8::internal::compiler::CodeAssembler::Unreachable().
Referenced by GetDefaultConstructor(), GetTypedArrayElementsInfo(), and GetTypedArrayElementSize().
GetDefaultConstructor()
TNode< JSFunction > v8::internal::TypedArrayBuiltinsAssembler::GetDefaultConstructor (TNode< Context > context, TNode< JSTypedArray > exemplar)
Definition at line 261 of file builtins-typed-array-gen.cc.
                                                          {
  TVARIABLE(IntPtrT, context_slot);
  TNode<Int32T> elements_kind = LoadElementsKind(exemplar);
  DispatchTypedArrayByElementsKind(
      elements_kind,
      [&](ElementsKind el_kind, int size, int typed_array_function_index) {
        context_slot = IntPtrConstant(typed_array_function_index);
      });
  return CAST(LoadContextElementNoCell(LoadNativeContext(context),
                                       context_slot.value()));
}
References CAST, DispatchTypedArrayByElementsKind(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::CodeStubAssembler::LoadElementsKind(), v8::internal::CodeStubAssembler::LoadNativeContext(), and size().
GetTypedArrayElementsInfo() [1/2]
TorqueStructTypedArrayElementsInfo v8::internal::TypedArrayBuiltinsAssembler::GetTypedArrayElementsInfo (TNode< JSTypedArray > typed_array)
Definition at line 238 of file builtins-typed-array-gen.cc.
                                     {
  return GetTypedArrayElementsInfo(LoadMap(typed_array));
}
References v8::internal::CodeStubAssembler::LoadMap().
GetTypedArrayElementsInfo() [2/2]
TorqueStructTypedArrayElementsInfo v8::internal::TypedArrayBuiltinsAssembler::GetTypedArrayElementsInfo (TNode< Map > map)
Definition at line 244 of file builtins-typed-array-gen.cc.
                                                                     {
  TNode<Int32T> elements_kind = LoadMapElementsKind(map);
  TVARIABLE(UintPtrT, var_size_log2);
  TVARIABLE(Map, var_map);
  ReadOnlyRoots roots(isolate());
  DispatchTypedArrayByElementsKind(
      elements_kind,
      [&](ElementsKind kind, int size, int typed_array_fun_index) {
        DCHECK_GT(size, 0);
        var_size_log2 = UintPtrConstant(ElementsKindToShiftSize(kind));
      });
  return TorqueStructTypedArrayElementsInfo{var_size_log2.value(),
                                            elements_kind};
}
References DCHECK_GT, DispatchTypedArrayByElementsKind(), v8::internal::ElementsKindToShiftSize(), v8::internal::compiler::CodeAssembler::isolate(), v8::internal::CodeStubAssembler::LoadMapElementsKind(), size(), and v8::internal::compiler::CodeAssembler::UintPtrConstant().
GetTypedArrayElementSize()
TNode< IntPtrT > v8::internal::TypedArrayBuiltinsAssembler::GetTypedArrayElementSize (TNode< Int32T > elements_kind)
Definition at line 224 of file builtins-typed-array-gen.cc.
                                 {
  TVARIABLE(IntPtrT, element_size);
  DispatchTypedArrayByElementsKind(
      elements_kind,
      [&](ElementsKind el_kind, int size, int typed_array_fun_index) {
        element_size = IntPtrConstant(size);
      });
  return element_size.value();
}
References DispatchTypedArrayByElementsKind(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), and size().
IsBigInt64ElementsKind()
TNode< BoolT > v8::internal::TypedArrayBuiltinsAssembler::IsBigInt64ElementsKind (TNode< Int32T > kind)
Definition at line 215 of file builtins-typed-array-gen.cc.
                        {
  static_assert(BIGUINT64_ELEMENTS + 1 == BIGINT64_ELEMENTS);
  return Word32Or(
      IsElementsKindInRange(kind, BIGUINT64_ELEMENTS, BIGINT64_ELEMENTS),
      IsElementsKindInRange(kind, RAB_GSAB_BIGUINT64_ELEMENTS,
                            RAB_GSAB_BIGINT64_ELEMENTS));
}
References v8::internal::CodeStubAssembler::IsElementsKindInRange(), and v8::internal::compiler::CodeAssembler::Word32Or().
Referenced by CallCCopyFastNumberJSArrayElementsToTypedArray().
IsMockArrayBufferAllocatorFlag()
TNode<BoolT> v8::internal::TypedArrayBuiltinsAssembler::IsMockArrayBufferAllocatorFlag ()
IsUint8ElementsKind()
TNode< BoolT > v8::internal::TypedArrayBuiltinsAssembler::IsUint8ElementsKind (TNode< Int32T > kind)
Definition at line 205 of file builtins-typed-array-gen.cc.
                        {
  return Word32Or(
      Word32Or(Word32Equal(kind, Int32Constant(UINT8_ELEMENTS)),
               Word32Equal(kind, Int32Constant(UINT8_CLAMPED_ELEMENTS))),
      Word32Or(
          Word32Equal(kind, Int32Constant(RAB_GSAB_UINT8_ELEMENTS)),
          Word32Equal(kind, Int32Constant(RAB_GSAB_UINT8_CLAMPED_ELEMENTS))));
}
References v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::maglev::UINT8_CLAMPED_ELEMENTS, v8::internal::maglev::UINT8_ELEMENTS, v8::internal::compiler::CodeAssembler::Word32Equal(), and v8::internal::compiler::CodeAssembler::Word32Or().
LoadMapForType()
TNode<Map> v8::internal::TypedArrayBuiltinsAssembler::LoadMapForType (TNode< JSTypedArray > array)
SetJSTypedArrayOffHeapDataPtr()
void v8::internal::TypedArrayBuiltinsAssembler::SetJSTypedArrayOffHeapDataPtr (TNode< JSTypedArray > holder, TNode< RawPtrT > base, TNode< UintPtrT > offset)
Definition at line 474 of file builtins-typed-array-gen.cc.
                                                                             {
  StoreObjectFieldNoWriteBarrier(holder, JSTypedArray::kBasePointerOffset,
                                 SmiConstant(0));
  base = RawPtrAdd(base, Signed(offset));
  StoreJSTypedArrayExternalPointerPtr(holder, base);
}
References v8::internal::compiler::CodeAssembler::RawPtrAdd(), v8::internal::compiler::CodeAssembler::Signed(), v8::internal::compiler::CodeAssembler::SmiConstant(), v8::internal::CodeStubAssembler::StoreJSTypedArrayExternalPointerPtr(), and v8::internal::CodeStubAssembler::StoreObjectFieldNoWriteBarrier().
SetJSTypedArrayOnHeapDataPtr()
void v8::internal::TypedArrayBuiltinsAssembler::SetJSTypedArrayOnHeapDataPtr (TNode< JSTypedArray > holder, TNode< ByteArray > base, TNode< UintPtrT > offset)
Definition at line 451 of file builtins-typed-array-gen.cc.
                                                                               {
  offset = UintPtrAdd(
      UintPtrConstant(OFFSET_OF_DATA_START(ByteArray) - kHeapObjectTag),
      offset);
  if (COMPRESS_POINTERS_BOOL) {
    TNode<IntPtrT> full_base = Signed(BitcastTaggedToWord(base));
    TNode<Int32T> compressed_base = TruncateIntPtrToInt32(full_base);
    // TODO(v8:9706): Add a way to directly use kRootRegister value.
    TNode<IntPtrT> ptr_compr_cage_base =
        IntPtrSub(full_base, Signed(ChangeUint32ToWord(compressed_base)));
    // Add JSTypedArray::ExternalPointerCompensationForOnHeapArray() to offset.
    // See JSTypedArray::AddExternalPointerCompensationForDeserialization().
    DCHECK_EQ(
        isolate()->cage_base(),
        JSTypedArray::ExternalPointerCompensationForOnHeapArray(isolate()));
    offset = Unsigned(IntPtrAdd(offset, ptr_compr_cage_base));
  }
  StoreJSTypedArrayBasePointer(holder, base);
  StoreJSTypedArrayExternalPointerPtr(holder, ReinterpretCast<RawPtrT>(offset));
}
References v8::internal::compiler::CodeAssembler::BitcastTaggedToWord(), v8::internal::compiler::CodeAssembler::ChangeUint32ToWord(), COMPRESS_POINTERS_BOOL, DCHECK_EQ, v8::internal::JSTypedArray::ExternalPointerCompensationForOnHeapArray(), v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrSub(), v8::internal::compiler::CodeAssembler::isolate(), v8::internal::kHeapObjectTag, OFFSET_OF_DATA_START, v8::internal::compiler::CodeAssembler::Signed(), v8::internal::CodeStubAssembler::StoreJSTypedArrayExternalPointerPtr(), v8::internal::CodeStubAssembler::TruncateIntPtrToInt32(), v8::internal::compiler::CodeAssembler::UintPtrAdd(), v8::internal::compiler::CodeAssembler::UintPtrConstant(), and v8::internal::compiler::CodeAssembler::Unsigned().
SetupTypedArrayEmbedderFields()
void v8::internal::TypedArrayBuiltinsAssembler::SetupTypedArrayEmbedderFields (TNode< JSTypedArray > holder)
Definition at line 26 of file builtins-typed-array-gen.cc.
                                {
  InitializeJSAPIObjectWithEmbedderSlotsCppHeapWrapperPtr(holder);
  for (int offset = JSTypedArray::kHeaderSize;
       offset < JSTypedArray::kSizeWithEmbedderFields; offset += kTaggedSize) {
    // TODO(v8:10391, saelo): Handle external pointers in EmbedderDataSlot
    StoreObjectField(holder, offset, SmiConstant(0));
  }
}
References v8::internal::CodeStubAssembler::InitializeJSAPIObjectWithEmbedderSlotsCppHeapWrapperPtr(), v8::internal::JSTypedArray::kSizeWithEmbedderFields, v8::internal::kTaggedSize, v8::internal::compiler::CodeAssembler::SmiConstant(), and v8::internal::CodeStubAssembler::StoreObjectField().
StoreJSTypedArrayElementFromNumeric()
void v8::internal::TypedArrayBuiltinsAssembler::StoreJSTypedArrayElementFromNumeric (TNode< Context > context, TNode< JSTypedArray > typed_array, TNode< UintPtrT > index_node, TNode< Numeric > value, ElementsKind elements_kind)
Definition at line 483 of file builtins-typed-array-gen.cc.
                                                                             {
  TNode<RawPtrT> data_ptr = LoadJSTypedArrayDataPtr(typed_array);
  switch (elements_kind) {
    case UINT8_ELEMENTS:
    case UINT8_CLAMPED_ELEMENTS:
    case INT8_ELEMENTS:
    case UINT16_ELEMENTS:
    case INT16_ELEMENTS:
      StoreElement(data_ptr, elements_kind, index, SmiToInt32(CAST(value)));
      break;
    case UINT32_ELEMENTS:
    case INT32_ELEMENTS:
      StoreElement(data_ptr, elements_kind, index,
                   TruncateTaggedToWord32(context, value));
      break;
    case FLOAT16_ELEMENTS:
      StoreElement(data_ptr, elements_kind, index,
                   TruncateFloat64ToFloat16(LoadHeapNumberValue(CAST(value))));
      break;
    case FLOAT32_ELEMENTS:
      StoreElement(data_ptr, elements_kind, index,
                   TruncateFloat64ToFloat32(LoadHeapNumberValue(CAST(value))));
      break;
    case FLOAT64_ELEMENTS:
      StoreElement(data_ptr, elements_kind, index,
                   LoadHeapNumberValue(CAST(value)));
      break;
    case BIGUINT64_ELEMENTS:
    case BIGINT64_ELEMENTS:
      StoreElement(data_ptr, elements_kind, index,
                   UncheckedCast<BigInt>(value));
      break;
    default:
      UNREACHABLE();
  }
}
References CAST, v8::internal::maglev::FLOAT32_ELEMENTS, v8::internal::index, v8::internal::maglev::INT16_ELEMENTS, v8::internal::maglev::INT8_ELEMENTS, v8::internal::CodeStubAssembler::LoadHeapNumberValue(), v8::internal::CodeStubAssembler::LoadJSTypedArrayDataPtr(), v8::internal::CodeStubAssembler::SmiToInt32(), v8::internal::CodeStubAssembler::StoreElement(), v8::internal::CodeStubAssembler::TruncateFloat64ToFloat16(), v8::internal::CodeStubAssembler::TruncateTaggedToWord32(), v8::internal::maglev::UINT16_ELEMENTS, v8::internal::maglev::UINT8_CLAMPED_ELEMENTS, v8::internal::maglev::UINT8_ELEMENTS, v8::internal::UNREACHABLE(), and v8::internal::value.
StoreJSTypedArrayElementFromPreparedValue()
template<typename TValue >
void v8::internal::TypedArrayBuiltinsAssembler::StoreJSTypedArrayElementFromPreparedValue (TNode< Context > context, TNode< JSTypedArray > typed_array, TNode< UintPtrT > index_node, TNode< TValue > value, ElementsKind elements_kind, Label * if_detached_or_out_of_bounds)
Definition at line 523 of file builtins-typed-array-gen.cc.
                                                                     {
  static_assert(std::is_same_v<TValue, Word32T> ||
                    std::is_same_v<TValue, Float16RawBitsT> ||
                    std::is_same_v<TValue, Float32T> ||
                    std::is_same_v<TValue, Float64T> ||
                    std::is_same_v<TValue, BigInt>,
                "Only Word32T, Float16T, Float32T, Float64T or BigInt values "
                "are allowed");
  // ToNumber/ToBigInt (or other functions called by the upper level) may
  // execute JavaScript code, which could detach the TypedArray's buffer or make
  // the TypedArray out of bounds.
  TNode<UintPtrT> length = LoadJSTypedArrayLengthAndCheckDetached(
      typed_array, if_detached_or_out_of_bounds);
  GotoIf(UintPtrGreaterThanOrEqual(index, length),
         if_detached_or_out_of_bounds);
  TNode<RawPtrT> data_ptr = LoadJSTypedArrayDataPtr(typed_array);
  StoreElement(data_ptr, elements_kind, index, prepared_value);
}
References v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::index, v8::internal::length, v8::internal::CodeStubAssembler::LoadJSTypedArrayDataPtr(), v8::internal::CodeStubAssembler::LoadJSTypedArrayLengthAndCheckDetached(), and v8::internal::CodeStubAssembler::StoreElement().
Referenced by StoreJSTypedArrayElementFromTagged().
StoreJSTypedArrayElementFromTagged()
void v8::internal::TypedArrayBuiltinsAssembler::StoreJSTypedArrayElementFromTagged (TNode< Context > context, TNode< JSTypedArray > typed_array, TNode< UintPtrT > index_node, TNode< Object > value, ElementsKind elements_kind, Label * if_detached_or_out_of_bounds)
Definition at line 546 of file builtins-typed-array-gen.cc.
                                         {
  switch (elements_kind) {
    case UINT8_ELEMENTS:
    case INT8_ELEMENTS:
    case UINT16_ELEMENTS:
    case INT16_ELEMENTS:
    case UINT32_ELEMENTS:
    case INT32_ELEMENTS:
    case UINT8_CLAMPED_ELEMENTS: {
      auto prepared_value = PrepareValueForWriteToTypedArray<Word32T>(
          value, elements_kind, context);
      StoreJSTypedArrayElementFromPreparedValue(context, typed_array, index,
                                                prepared_value, elements_kind,
                                                if_detached_or_out_of_bounds);
      break;
    }
    case FLOAT16_ELEMENTS: {
      auto prepared_value = PrepareValueForWriteToTypedArray<Float16RawBitsT>(
          value, elements_kind, context);
      StoreJSTypedArrayElementFromPreparedValue(context, typed_array, index,
                                                prepared_value, elements_kind,
                                                if_detached_or_out_of_bounds);
      break;
    }
    case FLOAT32_ELEMENTS: {
      auto prepared_value = PrepareValueForWriteToTypedArray<Float32T>(
          value, elements_kind, context);
      StoreJSTypedArrayElementFromPreparedValue(context, typed_array, index,
                                                prepared_value, elements_kind,
                                                if_detached_or_out_of_bounds);
      break;
    }
    case FLOAT64_ELEMENTS: {
      auto prepared_value = PrepareValueForWriteToTypedArray<Float64T>(
          value, elements_kind, context);
      StoreJSTypedArrayElementFromPreparedValue(context, typed_array, index,
                                                prepared_value, elements_kind,
                                                if_detached_or_out_of_bounds);
      break;
    }
    case BIGINT64_ELEMENTS:
    case BIGUINT64_ELEMENTS: {
      auto prepared_value = PrepareValueForWriteToTypedArray<BigInt>(
          value, elements_kind, context);
      StoreJSTypedArrayElementFromPreparedValue(context, typed_array, index,
                                                prepared_value, elements_kind,
                                                if_detached_or_out_of_bounds);
      break;
    }
    default:
      UNREACHABLE();
  }
}
References v8::internal::maglev::FLOAT32_ELEMENTS, v8::internal::index, v8::internal::maglev::INT16_ELEMENTS, v8::internal::maglev::INT8_ELEMENTS, StoreJSTypedArrayElementFromPreparedValue(), v8::internal::maglev::UINT16_ELEMENTS, v8::internal::maglev::UINT8_CLAMPED_ELEMENTS, v8::internal::maglev::UINT8_ELEMENTS, v8::internal::UNREACHABLE(), and v8::internal::value.
ValidateTypedArray()
TNode< JSTypedArray > v8::internal::TypedArrayBuiltinsAssembler::ValidateTypedArray (TNode< Context > context, TNode< Object > obj, const char * method_name)
Definition at line 276 of file builtins-typed-array-gen.cc.
                                                                        {
  // If it is not a typed array, throw
  ThrowIfNotInstanceType(context, obj, JS_TYPED_ARRAY_TYPE, method_name);
  // If the typed array's buffer is detached, throw
  ThrowIfArrayBufferViewBufferIsDetached(context, CAST(obj), method_name);
  // TODO(v8:11111): Throw if the RAB / GSAB is OOB.
  return CAST(obj);
}
References CAST, v8::internal::CodeStubAssembler::ThrowIfArrayBufferViewBufferIsDetached(), and v8::internal::CodeStubAssembler::ThrowIfNotInstanceType().
ValidateTypedArrayAndGetLength()
TNode< UintPtrT > v8::internal::TypedArrayBuiltinsAssembler::ValidateTypedArrayAndGetLength (TNode< Context > context, TNode< Object > obj, const char * method_name)
Definition at line 288 of file builtins-typed-array-gen.cc.
                                                                        {
  // If it is not a typed array, throw
  ThrowIfNotInstanceType(context, obj, JS_TYPED_ARRAY_TYPE, method_name);
  Label detached_or_oob(this), not_detached_nor_oob(this);
  TNode<UintPtrT> length =
      LoadJSTypedArrayLengthAndCheckDetached(CAST(obj), &detached_or_oob);
  Goto(&not_detached_nor_oob);
  BIND(&detached_or_oob);
  ThrowTypeError(context, MessageTemplate::kDetachedOperation, method_name);
  BIND(&not_detached_nor_oob);
  return length;
}
References CAST, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::length, v8::internal::CodeStubAssembler::LoadJSTypedArrayLengthAndCheckDetached(), v8::internal::CodeStubAssembler::ThrowIfNotInstanceType(), and v8::internal::CodeStubAssembler::ThrowTypeError().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/builtins/builtins-typed-array-gen.h
/mnt/V8SourceCode/src/builtins/builtins-typed-array-gen.cc