v8::internal::torque::cpp::File Class Reference
#include <cpp-builder.h>
Public Member Functions
File (std::ostream &stream)
void BeginIncludeGuard (const std::string &name)
void EndIncludeGuard (const std::string &name)
void BeginNamespace (std::string name)
void BeginNamespace (std::string name0, std::string name1)
void EndNamespace (const std::string &name)
void EndNamespace (const std::string &name0, const std::string &name1)
void AddInclude (std::string include)
template<typename T >
File & operator<< (const T &value)
Protected Member Functions
std::ostream & s ()
Private Attributes
std::ostream * stream_
std::set< std::string > includes_
std::stack< std::string > namespaces_
Detailed Description
Definition at line 180 of file cpp-builder.h.
Constructor & Destructor Documentation
File()
v8::internal::torque::cpp::File::File (std::ostream & stream) [inline], [explicit]
Definition at line 182 of file cpp-builder.h.
: stream_(&stream) {}
Member Function Documentation
AddInclude()
void v8::internal::torque::cpp::File::AddInclude (std::string include) [inline]
Definition at line 191 of file cpp-builder.h.
{ includes_.insert(std::move(include)); }
References includes_.
BeginIncludeGuard()
void v8::internal::torque::cpp::File::BeginIncludeGuard (const std::string & name)
Definition at line 120 of file cpp-builder.cc.
                                                  {
  s() << "#ifndef " << name
      << "\n"
         "#define "
      << name << "\n\n";
}
References v8::internal::name, and s().
Referenced by v8::internal::torque::cpp::IncludeGuardScope::IncludeGuardScope().
BeginNamespace() [1/2]
void v8::internal::torque::cpp::File::BeginNamespace (std::string name)
Definition at line 131 of file cpp-builder.cc.
                                        {
  DCHECK(!name.empty());
  DCHECK_EQ(name.find(':'), std::string::npos);
  s() << "namespace " << name << " {\n";
  namespaces_.push(std::move(name));
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::name, namespaces_, and s().
Referenced by BeginNamespace().
BeginNamespace() [2/2]
void v8::internal::torque::cpp::File::BeginNamespace (std::string name0, std::string name1)
Definition at line 138 of file cpp-builder.cc.
                                                          {
  BeginNamespace(name0);
  BeginNamespace(name1);
}
References BeginNamespace().
EndIncludeGuard()
void v8::internal::torque::cpp::File::EndIncludeGuard (const std::string & name)
Definition at line 127 of file cpp-builder.cc.
                                                {
  s() << "#endif // " << name << "\n";
}
References v8::internal::name, and s().
Referenced by v8::internal::torque::cpp::IncludeGuardScope::~IncludeGuardScope().
EndNamespace() [1/2]
void v8::internal::torque::cpp::File::EndNamespace (const std::string & name)
Definition at line 143 of file cpp-builder.cc.
                                             {
  DCHECK(!namespaces_.empty());
  DCHECK_EQ(namespaces_.top(), name);
  s() << "} // namespace " << namespaces_.top() << "\n";
  namespaces_.pop();
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::name, namespaces_, and s().
Referenced by EndNamespace().
EndNamespace() [2/2]
void v8::internal::torque::cpp::File::EndNamespace (const std::string & name0, const std::string & name1)
Definition at line 150 of file cpp-builder.cc.
                                                                      {
  EndNamespace(name1);
  EndNamespace(name0);
}
References EndNamespace().
operator<<()
template<typename T >
File& v8::internal::torque::cpp::File::operator<< (const T & value) [inline]
Definition at line 194 of file cpp-builder.h.
                                   {
    s() << value;
    return *this;
  }
References s(), and v8::internal::value.
s()
std::ostream& v8::internal::torque::cpp::File::s () [inline], [protected]
Definition at line 200 of file cpp-builder.h.
{ return *stream_; }
References stream_.
Referenced by BeginIncludeGuard(), BeginNamespace(), EndIncludeGuard(), EndNamespace(), and operator<<().
Member Data Documentation
includes_
std::set<std::string> v8::internal::torque::cpp::File::includes_ [private]
Definition at line 204 of file cpp-builder.h.
Referenced by AddInclude().
namespaces_
std::stack<std::string> v8::internal::torque::cpp::File::namespaces_ [private]
Definition at line 205 of file cpp-builder.h.
Referenced by BeginNamespace(), and EndNamespace().
stream_
std::ostream* v8::internal::torque::cpp::File::stream_ [private]
Definition at line 203 of file cpp-builder.h.
Referenced by s().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/torque/cpp-builder.h
/mnt/V8SourceCode/src/torque/cpp-builder.cc