v8::internal::ParkedRecursiveMutexGuard Class Reference
#include <parked-scope.h>
Public Member Functions
ParkedRecursiveMutexGuard (LocalIsolate *local_isolate, base::RecursiveMutex *mutex)
ParkedRecursiveMutexGuard (LocalHeap *local_heap, base::RecursiveMutex *mutex)
ParkedRecursiveMutexGuard (const ParkedRecursiveMutexGuard &)=delete
ParkedRecursiveMutexGuard & operator= (const ParkedRecursiveMutexGuard &)=delete
~ParkedRecursiveMutexGuard ()
Private Attributes
base::RecursiveMutex * mutex_
Detailed Description
Definition at line 92 of file parked-scope.h.
Constructor & Destructor Documentation
ParkedRecursiveMutexGuard() [1/3]
v8::internal::ParkedRecursiveMutexGuard::ParkedRecursiveMutexGuard (LocalIsolate * local_isolate, base::RecursiveMutex * mutex) [inline]
Definition at line 33 of file parked-scope-inl.h.
    : ParkedRecursiveMutexGuard(local_isolate->heap(), mutex) {}
ParkedRecursiveMutexGuard() [2/3]
v8::internal::ParkedRecursiveMutexGuard::ParkedRecursiveMutexGuard (LocalHeap * local_heap, base::RecursiveMutex * mutex) [inline]
Definition at line 37 of file parked-scope-inl.h.
    : mutex_(mutex) {
  DCHECK(AllowGarbageCollection::IsAllowed());
  if (!mutex_->TryLock()) {
    local_heap->ExecuteWhileParked([this]() { mutex_->Lock(); });
  }
}
References v8::internal::DCHECK(), v8::internal::LocalHeap::ExecuteWhileParked(), v8::base::RecursiveMutex::Lock(), mutex_, and v8::base::RecursiveMutex::TryLock().
ParkedRecursiveMutexGuard() [3/3]
v8::internal::ParkedRecursiveMutexGuard::ParkedRecursiveMutexGuard (const ParkedRecursiveMutexGuard &) [delete]
 ParkedRecursiveMutexGuard()
v8::internal::ParkedRecursiveMutexGuard::~ParkedRecursiveMutexGuard () [inline]
Definition at line 102 of file parked-scope.h.
{ mutex_->Unlock(); }
Member Function Documentation
operator=()
ParkedRecursiveMutexGuard& v8::internal::ParkedRecursiveMutexGuard::operator= (const ParkedRecursiveMutexGuard &) [delete]
Member Data Documentation
mutex_
base::RecursiveMutex* v8::internal::ParkedRecursiveMutexGuard::mutex_ [private]
Definition at line 105 of file parked-scope.h.
Referenced by ParkedRecursiveMutexGuard().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/parked-scope.h
/mnt/V8SourceCode/src/heap/parked-scope-inl.h