v8::JobDelegate Class Reference
Delegate that's passed to Job's worker task, providing an entry point to communicate with the scheduler.
#include <v8-platform.h>
Public Member Functions
virtual bool ShouldYield ()=0
Returns true if this thread must return from the worker task on the current thread ASAP.
virtual void NotifyConcurrencyIncrease ()=0
Notifies the scheduler that max concurrency was increased, and the number of worker should be adjusted accordingly.
virtual uint8_t GetTaskId ()=0
Returns a task_id unique among threads currently running this job, such that GetTaskId() < worker count.
virtual bool IsJoiningThread () const =0
Returns true if the current task is called from the thread currently running JobHandle::Join().
Detailed Description
Delegate that's passed to Job's worker task, providing an entry point to communicate with the scheduler.
Definition at line 206 of file v8-platform.h.
Member Function Documentation
GetTaskId()
virtual uint8_t v8::JobDelegate::GetTaskId () [pure virtual]
Returns a task_id unique among threads currently running this job, such that GetTaskId() < worker count.
To achieve this, the same task_id may be reused by a different thread after a worker_task returns.
Implemented in v8::platform::DefaultJobState::JobDelegate.
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ExecuteCompilationUnits(), v8::internal::OptimizingCompileTaskExecutor::CompileTask::Run(), v8::internal::PageEvacuationJob::Run(), v8::internal::ScavengerCollector::JobTask::Run(), v8::internal::Sweeper::MajorSweeperJob::RunImpl(), v8::internal::Sweeper::MinorSweeperJob::RunImpl(), v8::internal::ConcurrentMarking::RunMajor(), and v8::internal::ConcurrentMarking::RunMinor().
IsJoiningThread()
virtual bool v8::JobDelegate::IsJoiningThread () const [pure virtual]
Returns true if the current task is called from the thread currently running JobHandle::Join().
Implemented in v8::platform::DefaultJobState::JobDelegate.
Referenced by v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::Run(), v8::internal::anonymous_namespace{traced-handles.cc}::ParallelWeakHandlesProcessor< Derived >::Job::Run(), v8::internal::ConcurrentMarking::JobTaskMajor::Run(), v8::internal::ConcurrentMarking::JobTaskMinor::Run(), v8::internal::PageEvacuationJob::Run(), v8::internal::PointersUpdatingJob::Run(), v8::internal::ScavengerCollector::JobTask::Run(), v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::Run(), and v8::internal::ConcurrentMarking::RunMinorImpl().
NotifyConcurrencyIncrease()
virtual void v8::JobDelegate::NotifyConcurrencyIncrease () [pure virtual]
Notifies the scheduler that max concurrency was increased, and the number of worker should be adjusted accordingly.
See Platform::PostJob() for more details.
Implemented in v8::platform::DefaultJobState::JobDelegate.
Referenced by v8::internal::Scavenger::Process(), and v8::internal::wasm::DeserializeCodeTask::Run().
ShouldYield()
virtual bool v8::JobDelegate::ShouldYield () [pure virtual]
Returns true if this thread must return from the worker task on the current thread ASAP.
Workers should periodically invoke ShouldYield (or YieldIfNeeded()) as often as is reasonable. After this method returned true, ShouldYield must not be called again.
Implemented in v8::platform::DefaultJobState::JobDelegate.
Referenced by v8::internal::Sweeper::ConcurrentMajorSweeper::ConcurrentSweepSpace(), v8::internal::Sweeper::ConcurrentMinorSweeper::ConcurrentSweepSpace(), v8::internal::Sweeper::LocalSweeper::ContributeAndWaitForPromotedPagesIteration(), v8::internal::LazyCompileDispatcher::DoBackgroundWork(), cppgc::internal::anonymous_namespace{concurrent-marker.cc}::DrainWorklistWithYielding(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ExecuteCompilationUnits(), v8::internal::Sweeper::LocalSweeper::ParallelIteratePromotedPages(), v8::internal::baseline::ConcurrentBaselineCompiler::JobDispatcher::Run(), v8::internal::OptimizingCompileTaskExecutor::CompileTask::Run(), v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::Run(), v8::internal::maglev::MaglevConcurrentDispatcher::JobTask::Run(), v8::internal::wasm::ValidateFunctionsStreamingJob::Run(), v8::internal::wasm::anonymous_namespace{module-decoder.cc}::ValidateFunctionsTask::Run(), v8::internal::anonymous_namespace{traced-handles.cc}::ParallelWeakHandlesProcessor< Derived >::Job::RunImpl(), v8::internal::ConcurrentMarking::RunMajor(), v8::internal::ConcurrentMarking::RunMinorImpl(), v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::SweepListFull(), cppgc::internal::anonymous_namespace{sweeper.cc}::ConcurrentSweepTask::SweepStateOrYield(), v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::SweepYoung(), and v8::internal::wasm::DeserializeCodeTask::TryPublishing().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/v8-platform.h