v8::internal::wasm::WasmInterpreterThreadMap Class Reference
#include <wasm-interpreter.h>
Public Member Functions
WasmInterpreterThread * GetCurrentInterpreterThread (Isolate *isolate)
void NotifyIsolateDisposal (Isolate *isolate)
Private Types
typedef std::unordered_map< int, std::unique_ptr< WasmInterpreterThread > > ThreadInterpreterMap
Private Attributes
ThreadInterpreterMap map_
base::Mutex mutex_
Detailed Description
Definition at line 187 of file wasm-interpreter.h.
Member Typedef Documentation
ThreadInterpreterMap
typedef std::unordered_map<int, std::unique_ptr<WasmInterpreterThread> > v8::internal::wasm::WasmInterpreterThreadMap::ThreadInterpreterMap [private]
Definition at line 195 of file wasm-interpreter.h.
Member Function Documentation
GetCurrentInterpreterThread()
WasmInterpreterThread * v8::internal::wasm::WasmInterpreterThreadMap::GetCurrentInterpreterThread (Isolate * isolate)
Definition at line 157 of file wasm-interpreter.cc.
                      {
  const int current_thread_id = ThreadId::Current().ToInteger();
  {
    base::MutexGuard guard(&mutex_);
    auto it = map_.find(current_thread_id);
    if (it == map_.end()) {
      map_[current_thread_id] =
          std::make_unique<WasmInterpreterThread>(isolate);
      it = map_.find(current_thread_id);
    }
    return it->second.get();
  }
}
References v8::internal::ThreadId::Current(), and v8::internal::ThreadId::ToInteger().
NotifyIsolateDisposal()
void v8::internal::wasm::WasmInterpreterThreadMap::NotifyIsolateDisposal (Isolate * isolate)
Definition at line 173 of file wasm-interpreter.cc.
                                                                     {
  base::MutexGuard guard(&mutex_);
  auto it = map_.begin();
  while (it != map_.end()) {
    WasmInterpreterThread* thread = it->second.get();
    if (thread->GetIsolate() == isolate) {
      thread->TerminateExecutionTimers();
      it = map_.erase(it);
    } else {
      ++it;
    }
  }
}
References v8::internal::wasm::WasmInterpreterThread::GetIsolate(), and v8::internal::wasm::WasmInterpreterThread::TerminateExecutionTimers().
Member Data Documentation
map_
ThreadInterpreterMap v8::internal::wasm::WasmInterpreterThreadMap::map_ [private]
Definition at line 196 of file wasm-interpreter.h.
mutex_
base::Mutex v8::internal::wasm::WasmInterpreterThreadMap::mutex_ [private]
Definition at line 197 of file wasm-interpreter.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter.h
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter.cc