v8::ScriptCompiler Class Reference
For compiling scripts.
#include <v8-script.h>
Classes
struct CachedData
Compilation data that the embedder can cache and pass back to speed up future compilations.
struct CompilationDetails
class ConsumeCodeCacheTask
A task which the embedder must run on a background thread to consume a V8 code cache.
class ExternalSourceStream
For streaming incomplete script data to V8.
class ScriptStreamingTask
A streaming task which the embedder must run on a background thread to stream scripts into V8.
class Source
Source code which can be then compiled to a UnboundScript or Script.
class StreamedSource
Source code which can be streamed into V8 in pieces.
Public Types
enum class InMemoryCacheResult { kNotAttempted
, kHit
, kMiss
, kPartial
 }
enum CompileOptions {
kNoCompileOptions = 0
, kConsumeCodeCache = 1 << 0
, kEagerCompile = 1 << 1
, kProduceCompileHints = 1 << 2
,
kConsumeCompileHints = 1 << 3
, kFollowCompileHintsMagicComment = 1 << 4
, kFollowCompileHintsPerFunctionMagicComment = 1 << 5
 }
enum NoCacheReason {
kNoCacheNoReason = 0
, kNoCacheBecauseCachingDisabled
, kNoCacheBecauseNoResource
, kNoCacheBecauseInlineScript
,
kNoCacheBecauseModule
, kNoCacheBecauseStreamingSource
, kNoCacheBecauseInspector
, kNoCacheBecauseScriptTooSmall
,
kNoCacheBecauseCacheTooCold
, kNoCacheBecauseV8Extension
, kNoCacheBecauseExtensionModule
, kNoCacheBecausePacScript
,
kNoCacheBecauseInDocumentWrite
, kNoCacheBecauseResourceWithNoCacheHandler
, kNoCacheBecauseDeferredProduceCodeCache
, kNoCacheBecauseStaticCodeCache
 }
The reason for which we are not requesting or providing a code cache.
Static Public Member Functions
static bool CompileOptionsIsValid (CompileOptions compile_options)
static V8_WARN_UNUSED_RESULT MaybeLocal< UnboundScript > CompileUnboundScript (Isolate *isolate, Source *source, CompileOptions options=kNoCompileOptions, NoCacheReason no_cache_reason=kNoCacheNoReason)
Compiles the specified script (context-independent).
static V8_WARN_UNUSED_RESULT MaybeLocal< Script > Compile (Local< Context > context, Source *source, CompileOptions options=kNoCompileOptions, NoCacheReason no_cache_reason=kNoCacheNoReason)
Compiles the specified script (bound to current context).
static ScriptStreamingTask * StartStreaming (Isolate *isolate, StreamedSource *source, ScriptType type=ScriptType::kClassic, CompileOptions options=kNoCompileOptions, CompileHintCallback compile_hint_callback=nullptr, void *compile_hint_callback_data=nullptr)
Returns a task which streams script data into V8, or NULL if the script cannot be streamed.
static ConsumeCodeCacheTask * StartConsumingCodeCache (Isolate *isolate, std::unique_ptr< CachedData > source)
static ConsumeCodeCacheTask * StartConsumingCodeCacheOnBackground (Isolate *isolate, std::unique_ptr< CachedData > source)
static V8_WARN_UNUSED_RESULT MaybeLocal< Script > Compile (Local< Context > context, StreamedSource *source, Local< String > full_source_string, const ScriptOrigin &origin)
Compiles a streamed script (bound to current context).
static uint32_t CachedDataVersionTag ()
Return a version tag for CachedData for the current V8 version & flags.
static V8_WARN_UNUSED_RESULT MaybeLocal< Module > CompileModule (Isolate *isolate, Source *source, CompileOptions options=kNoCompileOptions, NoCacheReason no_cache_reason=kNoCacheNoReason)
Compile an ES module, returning a Module that encapsulates the compiled code.
static V8_WARN_UNUSED_RESULT MaybeLocal< Module > CompileModule (Local< Context > context, StreamedSource *v8_source, Local< String > full_source_string, const ScriptOrigin &origin)
Compiles a streamed module script.
static V8_WARN_UNUSED_RESULT MaybeLocal< Function > CompileFunction (Local< Context > context, Source *source, size_t arguments_count=0, Local< String > arguments[]=nullptr, size_t context_extension_count=0, Local< Object > context_extensions[]=nullptr, CompileOptions options=kNoCompileOptions, NoCacheReason no_cache_reason=kNoCacheNoReason)
Compile a function for a given context.
static CachedData * CreateCodeCache (Local< UnboundScript > unbound_script)
Creates and returns code cache for the specified unbound_script.
static CachedData * CreateCodeCache (Local< UnboundModuleScript > unbound_module_script)
Creates and returns code cache for the specified unbound_module_script.
static CachedData * CreateCodeCacheForFunction (Local< Function > function)
Creates and returns code cache for the specified function that was previously produced by CompileFunction.
Static Private Member Functions
static V8_WARN_UNUSED_RESULT MaybeLocal< UnboundScript > CompileUnboundInternal (Isolate *isolate, Source *source, CompileOptions options, NoCacheReason no_cache_reason)
static V8_WARN_UNUSED_RESULT MaybeLocal< Function > CompileFunctionInternal (Local< Context > context, Source *source, size_t arguments_count, Local< String > arguments[], size_t context_extension_count, Local< Object > context_extensions[], CompileOptions options, NoCacheReason no_cache_reason, Local< ScriptOrModule > *script_or_module_out)
Detailed Description
For compiling scripts.
Definition at line 402 of file v8-script.h.
Member Enumeration Documentation
CompileOptions
enum v8::ScriptCompiler::CompileOptions
Enumerator
kNoCompileOptions
kConsumeCodeCache
kEagerCompile
kProduceCompileHints
kConsumeCompileHints
kFollowCompileHintsMagicComment
kFollowCompileHintsPerFunctionMagicComment
Definition at line 673 of file v8-script.h.
                      {
    kNoCompileOptions = 0,
    kConsumeCodeCache = 1 << 0,
    kEagerCompile = 1 << 1,
    kProduceCompileHints = 1 << 2,
    kConsumeCompileHints = 1 << 3,
    kFollowCompileHintsMagicComment = 1 << 4,
    kFollowCompileHintsPerFunctionMagicComment = 1 << 5,
  };
InMemoryCacheResult
enum v8::ScriptCompiler::InMemoryCacheResult [strong]
Enumerator
kNotAttempted
kHit
kMiss
kPartial
Definition at line 462 of file v8-script.h.
                                 {
    // V8 did not attempt to find this script in its in-memory cache.
    kNotAttempted,
    // V8 found a previously compiled copy of this script in its in-memory
    // cache. Any data generated by a streaming compilation or background
    // deserialization was abandoned.
    kHit,
    // V8 didn't have any previously compiled data for this script.
    kMiss,
    // V8 had some previously compiled data for an identical script, but the
    // data was incomplete.
    kPartial,
  };
NoCacheReason
enum v8::ScriptCompiler::NoCacheReason
The reason for which we are not requesting or providing a code cache.
Enumerator
kNoCacheNoReason
kNoCacheBecauseCachingDisabled
kNoCacheBecauseNoResource
kNoCacheBecauseInlineScript
kNoCacheBecauseModule
kNoCacheBecauseStreamingSource
kNoCacheBecauseInspector
kNoCacheBecauseScriptTooSmall
kNoCacheBecauseCacheTooCold
kNoCacheBecauseV8Extension
kNoCacheBecauseExtensionModule
kNoCacheBecausePacScript
kNoCacheBecauseInDocumentWrite
kNoCacheBecauseResourceWithNoCacheHandler
kNoCacheBecauseDeferredProduceCodeCache
kNoCacheBecauseStaticCodeCache
Definition at line 706 of file v8-script.h.
                     {
    kNoCacheNoReason = 0,
    kNoCacheBecauseCachingDisabled,
    kNoCacheBecauseNoResource,
    kNoCacheBecauseInlineScript,
    kNoCacheBecauseModule,
    kNoCacheBecauseStreamingSource,
    kNoCacheBecauseInspector,
    kNoCacheBecauseScriptTooSmall,
    kNoCacheBecauseCacheTooCold,
    kNoCacheBecauseV8Extension,
    kNoCacheBecauseExtensionModule,
    kNoCacheBecausePacScript,
    kNoCacheBecauseInDocumentWrite,
    kNoCacheBecauseResourceWithNoCacheHandler,
    kNoCacheBecauseDeferredProduceCodeCache,
    kNoCacheBecauseStaticCodeCache,
  };
Member Function Documentation
CachedDataVersionTag()
uint32_t v8::ScriptCompiler::CachedDataVersionTag () [static]
Return a version tag for CachedData for the current V8 version & flags.
This value is meant only for determining whether a previously generated CachedData instance is still valid; the tag has no other meaing.
Background: The data carried by CachedData may depend on the exact V8 version number or current compiler flags. This means that when persisting CachedData, the embedder must take care to not pass in data from another V8 version, or the same version with different features enabled.
The easiest way to do so is to clear the embedder's cache on any such change.
Alternatively, this tag can be stored alongside the cached data and compared when it is being used.
Definition at line 2707 of file api.cc.
                                              {
  return static_cast<uint32_t>(base::hash_combine(internal::Version::Hash(),
                                                  internal::FlagList::Hash()));
}
References v8::internal::FlagList::Hash(), v8::internal::Version::Hash(), and v8::base::hash_combine().
Compile() [1/2]
MaybeLocal< Script > v8::ScriptCompiler::Compile (Local< Context > context, Source * source, CompileOptions options = kNoCompileOptions, NoCacheReason no_cache_reason = kNoCacheNoReason) [static]
Compiles the specified script (bound to current context).
Parameters
source Script source code.
pre_data Pre-parsing data, as obtained by ScriptData::PreCompile() using pre_data speeds compilation if it's done multiple times. Owned by caller, no references are kept when this function returns.
Returns
Compiled script object, bound to the context that was active when this function was called. When run it will always use this context.
Definition at line 2469 of file api.cc.
                                                                          {
  Utils::ApiCheck(
      !source->GetResourceOptions().IsModule(), "v8::ScriptCompiler::Compile",
      "v8::ScriptCompiler::CompileModule must be used to compile modules");
  v8::Isolate* isolate = v8::Isolate::GetCurrent();
  MaybeLocal<UnboundScript> maybe =
      CompileUnboundInternal(isolate, source, options, no_cache_reason);
  Local<UnboundScript> result;
  if (!maybe.ToLocal(&result)) return {};
  v8::Context::Scope scope(context);
  return result->BindToCurrentContext();
}
References v8::Utils::ApiCheck(), CompileUnboundInternal(), v8::Isolate::GetCurrent(), v8::ScriptCompiler::Source::GetResourceOptions(), v8::ScriptOriginOptions::IsModule(), v8::base::internal::result, and v8::MaybeLocal< T >::ToLocal().
Referenced by v8::Script::Compile(), v8::anonymous_namespace{d8.cc}::Compile(), v8_inspector::V8InspectorImpl::compileScript(), v8::anonymous_namespace{d8.cc}::CompileStreamed(), and v8::internal::anonymous_namespace{snapshot.cc}::RunExtraCode().
Compile() [2/2]
MaybeLocal< Script > v8::ScriptCompiler::Compile (Local< Context > context, StreamedSource * source, Local< String > full_source_string, const ScriptOrigin & origin) [static]
Compiles a streamed script (bound to current context).
This can only be called after the streaming has finished (ScriptStreamingTask has been run). V8 doesn't construct the source string during streaming, so the embedder needs to pass the full source here.
Definition at line 2667 of file api.cc.
                                                                       {
  PrepareForExecutionScope api_scope{context,
                                     RCCId::kAPI_ScriptCompiler_Compile};
  i::Isolate* i_isolate = api_scope.i_isolate();
  TRACE_EVENT_CALL_STATS_SCOPED(i_isolate, "v8", "V8.ScriptCompiler");
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
               "V8.CompileStreamedScript");
  i::DirectHandle<i::SharedFunctionInfo> sfi;
  if (!CompileStreamedSource(i_isolate, v8_source, full_source_string, origin)
           .ToHandle(&sfi)) {
    i_isolate->ReportPendingMessages();
    return {};
  }
  Local<UnboundScript> generic = ToApiHandle<UnboundScript>(sfi);
  if (generic.IsEmpty()) return {};
  return api_scope.Escape(generic->BindToCurrentContext());
}
References v8::anonymous_namespace{api.cc}::CompileStreamedSource(), v8::internal::Isolate::ReportPendingMessages(), v8::anonymous_namespace{api.cc}::ToHandle(), TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT0, and TRACE_EVENT_CALL_STATS_SCOPED.
CompileFunction()
V8_WARN_UNUSED_RESULT MaybeLocal< Function > v8::ScriptCompiler::CompileFunction (Local< Context > context, Source * source, size_t arguments_count = 0, Local< String > arguments[] = nullptr, size_t context_extension_count = 0, Local< Object > context_extensions[] = nullptr, CompileOptions options = kNoCompileOptions, NoCacheReason no_cache_reason = kNoCacheNoReason) [static]
Compile a function for a given context.
This is equivalent to running
with (obj) { return function(args) { ... } }
It is possible to specify multiple context extensions (obj in the above example).
Definition at line 2504 of file api.cc.
                                   {
  PrepareForExecutionScope api_scope{
      v8_context, RCCId::kAPI_ScriptCompiler_CompileFunction};
  i::Isolate* i_isolate = api_scope.i_isolate();
  TRACE_EVENT_CALL_STATS_SCOPED(i_isolate, "v8", "V8.ScriptCompiler");
  DCHECK(options == CompileOptions::kConsumeCodeCache ||
         options == CompileOptions::kEagerCompile ||
         options == CompileOptions::kNoCompileOptions);
  i::DirectHandle<i::Context> context = Utils::OpenDirectHandle(*v8_context);
  DCHECK(IsNativeContext(*context));
  i::Handle<i::FixedArray> arguments_list =
      i_isolate->factory()->NewFixedArray(static_cast<int>(arguments_count));
  for (int i = 0; i < static_cast<int>(arguments_count); i++) {
    auto argument = Utils::OpenDirectHandle(*arguments[i]);
    if (!i::String::IsIdentifier(i_isolate, argument)) return {};
    arguments_list->set(i, *argument);
  }
  for (size_t i = 0; i < context_extension_count; ++i) {
    i::DirectHandle<i::JSReceiver> extension =
        Utils::OpenDirectHandle(*context_extensions[i]);
    if (!IsJSObject(*extension)) return {};
    context = i_isolate->factory()->NewWithContext(
        context,
        i::ScopeInfo::CreateForWithScope(
            i_isolate,
            IsNativeContext(*context)
                ? i::Handle<i::ScopeInfo>::null()
                : i::Handle<i::ScopeInfo>(context->scope_info(), i_isolate)),
        extension);
  }
  i::ScriptDetails script_details = GetScriptDetails(
      i_isolate, source->resource_name, source->resource_line_offset,
      source->resource_column_offset, source->source_map_url,
      source->host_defined_options, source->resource_options);
  script_details.wrapped_arguments = arguments_list;
  std::unique_ptr<i::AlignedCachedData> cached_data;
  if (options & kConsumeCodeCache) {
    DCHECK(source->cached_data);
    // ScriptData takes care of pointer-aligning the data.
    cached_data.reset(new i::AlignedCachedData(source->cached_data->data,
                                               source->cached_data->length));
  }
  i::DirectHandle<i::JSFunction> result;
  bool has_exception =
      !i::Compiler::GetWrappedFunction(
           i_isolate, Utils::OpenHandle(*source->source_string), context,
           script_details, cached_data.get(), options, no_cache_reason)
           .ToHandle(&result);
  if (options & kConsumeCodeCache) {
    source->cached_data->rejected = cached_data->rejected();
  }
  if (has_exception) return {};
  return api_scope.Escape(Utils::CallableToLocal(result));
}
References v8::ScriptCompiler::Source::cached_data, v8::internal::ScopeInfo::CreateForWithScope(), DCHECK, v8::internal::Isolate::factory(), v8::anonymous_namespace{api.cc}::GetScriptDetails(), v8::internal::Compiler::GetWrappedFunction(), v8::ScriptCompiler::Source::host_defined_options, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::String::IsIdentifier(), kConsumeCodeCache, v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::Factory::NewWithContext(), v8::Utils::OpenDirectHandle(), v8::Utils::OpenHandle(), v8::ScriptCompiler::Source::resource_column_offset, v8::ScriptCompiler::Source::resource_line_offset, v8::ScriptCompiler::Source::resource_name, v8::ScriptCompiler::Source::resource_options, v8::base::internal::result, v8::ScriptCompiler::Source::source_map_url, v8::ScriptCompiler::Source::source_string, TRACE_EVENT_CALL_STATS_SCOPED, and v8::internal::ScriptDetails::wrapped_arguments.
CompileFunctionInternal()
static V8_WARN_UNUSED_RESULT MaybeLocal<Function> v8::ScriptCompiler::CompileFunctionInternal (Local< Context > context, Source * source, size_t arguments_count, Local< String > arguments[], size_t context_extension_count, Local< Object > context_extensions[], CompileOptions options, NoCacheReason no_cache_reason, Local< ScriptOrModule > * script_or_module_out) [static], [private]
CompileModule() [1/2]
MaybeLocal< Module > v8::ScriptCompiler::CompileModule (Isolate * isolate, Source * source, CompileOptions options = kNoCompileOptions, NoCacheReason no_cache_reason = kNoCacheNoReason) [static]
Compile an ES module, returning a Module that encapsulates the compiled code.
Corresponds to the ParseModule abstract operation in the ECMAScript specification.
Definition at line 2485 of file api.cc.
                                   {
  Utils::ApiCheck(v8::ScriptCompiler::CompileOptionsIsValid(options),
                  "v8::ScriptCompiler::CompileModule",
                  "Invalid CompileOptions");
  Utils::ApiCheck(source->GetResourceOptions().IsModule(),
                  "v8::ScriptCompiler::CompileModule",
                  "Invalid ScriptOrigin: is_module must be true");
  MaybeLocal<UnboundScript> maybe =
      CompileUnboundInternal(v8_isolate, source, options, no_cache_reason);
  Local<UnboundScript> unbound;
  if (!maybe.ToLocal(&unbound)) return {};
  auto shared = Utils::OpenDirectHandle(*unbound);
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  return ToApiHandle<Module>(i_isolate->factory()->NewSourceTextModule(shared));
}
References v8::Utils::ApiCheck(), CompileOptionsIsValid(), CompileUnboundInternal(), v8::internal::Isolate::factory(), v8::ScriptCompiler::Source::GetResourceOptions(), v8::ScriptOriginOptions::IsModule(), v8::internal::Factory::NewSourceTextModule(), v8::Utils::OpenDirectHandle(), and v8::MaybeLocal< T >::ToLocal().
CompileModule() [2/2]
MaybeLocal< Module > v8::ScriptCompiler::CompileModule (Local< Context > context, StreamedSource * v8_source, Local< String > full_source_string, const ScriptOrigin & origin) [static]
Compiles a streamed module script.
This can only be called after the streaming has finished (ScriptStreamingTask has been run). V8 doesn't construct the source string during streaming, so the embedder needs to pass the full source here.
Definition at line 2688 of file api.cc.
                                                                  {
  PrepareForExecutionScope api_scope{context,
                                     RCCId::kAPI_ScriptCompiler_Compile};
  i::Isolate* i_isolate = api_scope.i_isolate();
  TRACE_EVENT_CALL_STATS_SCOPED(i_isolate, "v8", "V8.ScriptCompiler");
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
               "V8.CompileStreamedModule");
  i::DirectHandle<i::SharedFunctionInfo> sfi;
  if (!CompileStreamedSource(i_isolate, v8_source, full_source_string, origin)
           .ToHandle(&sfi)) {
    i_isolate->ReportPendingMessages();
    return {};
  }
  return api_scope.Escape(
      ToApiHandle<Module>(i_isolate->factory()->NewSourceTextModule(sfi)));
}
References v8::anonymous_namespace{api.cc}::CompileStreamedSource(), v8::internal::Isolate::factory(), v8::internal::Factory::NewSourceTextModule(), v8::internal::Isolate::ReportPendingMessages(), v8::anonymous_namespace{api.cc}::ToHandle(), TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT0, and TRACE_EVENT_CALL_STATS_SCOPED.
CompileOptionsIsValid()
static bool v8::ScriptCompiler::CompileOptionsIsValid (CompileOptions compile_options) [inline], [static]
Definition at line 683 of file v8-script.h.
                                                                           {
    // kConsumeCodeCache is mutually exclusive with all other flag bits.
    if ((compile_options & kConsumeCodeCache) &&
        compile_options != kConsumeCodeCache) {
      return false;
    }
    // kEagerCompile is mutually exclusive with all other flag bits.
    if ((compile_options & kEagerCompile) && compile_options != kEagerCompile) {
      return false;
    }
    // We don't currently support producing and consuming compile hints at the
    // same time.
    constexpr int produce_and_consume = CompileOptions::kProduceCompileHints |
                                        CompileOptions::kConsumeCompileHints;
    if ((compile_options & produce_and_consume) == produce_and_consume) {
      return false;
    }
    return true;
  }
Referenced by CompileModule(), and StartStreaming().
CompileUnboundInternal()
MaybeLocal< UnboundScript > v8::ScriptCompiler::CompileUnboundInternal (Isolate * isolate, Source * source, CompileOptions options, NoCacheReason no_cache_reason) [static], [private]
Definition at line 2397 of file api.cc.
                                   {
  auto i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  TRACE_EVENT_CALL_STATS_SCOPED(i_isolate, "v8", "V8.ScriptCompiler");
  EnterV8NoScriptScope<InternalEscapableScope> api_scope{
      i_isolate, v8_isolate->GetCurrentContext(),
      RCCId::kAPI_ScriptCompiler_CompileUnbound};
  auto str = Utils::OpenHandle(*(source->source_string));
  i::DirectHandle<i::SharedFunctionInfo> result;
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"), "V8.CompileScript");
  i::ScriptDetails script_details = GetScriptDetails(
      i_isolate, source->resource_name, source->resource_line_offset,
      source->resource_column_offset, source->source_map_url,
      source->host_defined_options, source->resource_options);
  i::MaybeDirectHandle<i::SharedFunctionInfo> maybe_function_info;
  if (options & kConsumeCodeCache) {
    if (source->consume_cache_task) {
      // Take ownership of the internal deserialization task and clear it off
      // the consume task on the source.
      DCHECK_NOT_NULL(source->consume_cache_task->impl_);
      std::unique_ptr<i::BackgroundDeserializeTask> deserialize_task =
          std::move(source->consume_cache_task->impl_);
      maybe_function_info =
          i::Compiler::GetSharedFunctionInfoForScriptWithDeserializeTask(
              i_isolate, str, script_details, deserialize_task.get(), options,
              no_cache_reason, i::NOT_NATIVES_CODE,
              &source->compilation_details);
      source->cached_data->rejected = deserialize_task->rejected();
    } else {
      DCHECK(source->cached_data);
      // AlignedCachedData takes care of pointer-aligning the data.
      auto cached_data = std::make_unique<i::AlignedCachedData>(
          source->cached_data->data, source->cached_data->length);
      maybe_function_info =
          i::Compiler::GetSharedFunctionInfoForScriptWithCachedData(
              i_isolate, str, script_details, cached_data.get(), options,
              no_cache_reason, i::NOT_NATIVES_CODE,
              &source->compilation_details);
      source->cached_data->rejected = cached_data->rejected();
    }
  } else if (options & kConsumeCompileHints) {
    maybe_function_info =
        i::Compiler::GetSharedFunctionInfoForScriptWithCompileHints(
            i_isolate, str, script_details, source->compile_hint_callback,
            source->compile_hint_callback_data, options, no_cache_reason,
            i::NOT_NATIVES_CODE, &source->compilation_details);
  } else {
    // Compile without any cache.
    maybe_function_info = i::Compiler::GetSharedFunctionInfoForScript(
        i_isolate, str, script_details, options, no_cache_reason,
        i::NOT_NATIVES_CODE, &source->compilation_details);
  }
  if (!maybe_function_info.ToHandle(&result)) return {};
  DCHECK(!i::HeapLayout::InReadOnlySpace(*result));
  return api_scope.Escape(ToApiHandle<UnboundScript>(result));
}
References v8::ScriptCompiler::Source::cached_data, v8::ScriptCompiler::Source::compilation_details, v8::ScriptCompiler::Source::compile_hint_callback, v8::ScriptCompiler::Source::compile_hint_callback_data, v8::ScriptCompiler::Source::consume_cache_task, DCHECK, DCHECK_NOT_NULL, v8::Isolate::GetCurrentContext(), v8::anonymous_namespace{api.cc}::GetScriptDetails(), v8::internal::Compiler::GetSharedFunctionInfoForScript(), v8::internal::Compiler::GetSharedFunctionInfoForScriptWithCachedData(), v8::internal::Compiler::GetSharedFunctionInfoForScriptWithCompileHints(), v8::internal::Compiler::GetSharedFunctionInfoForScriptWithDeserializeTask(), v8::ScriptCompiler::Source::host_defined_options, v8::internal::HeapLayout::InReadOnlySpace(), kConsumeCodeCache, kConsumeCompileHints, v8::internal::NOT_NATIVES_CODE, v8::Utils::OpenHandle(), v8::ScriptCompiler::Source::resource_column_offset, v8::ScriptCompiler::Source::resource_line_offset, v8::ScriptCompiler::Source::resource_name, v8::ScriptCompiler::Source::resource_options, v8::base::internal::result, v8::ScriptCompiler::Source::source_map_url, v8::ScriptCompiler::Source::source_string, v8::internal::MaybeDirectHandle< T >::ToHandle(), TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT0, and TRACE_EVENT_CALL_STATS_SCOPED.
Referenced by Compile(), CompileModule(), and CompileUnboundScript().
CompileUnboundScript()
MaybeLocal< UnboundScript > v8::ScriptCompiler::CompileUnboundScript (Isolate * isolate, Source * source, CompileOptions options = kNoCompileOptions, NoCacheReason no_cache_reason = kNoCacheNoReason) [static]
Compiles the specified script (context-independent).
Cached data as part of the source object can be optionally produced to be consumed later to speed up compilation of identical source scripts.
Note that when producing cached data, the source must point to NULL for cached data. When consuming cached data, the cached data must have been produced by the same version of V8, and the embedder needs to ensure the cached data is the correct one for the given script.
Parameters
source Script source code.
Returns
Compiled script object (context independent; for running it must be bound to a context).
Definition at line 2459 of file api.cc.
                                   {
  Utils::ApiCheck(
      !source->GetResourceOptions().IsModule(),
      "v8::ScriptCompiler::CompileUnboundScript",
      "v8::ScriptCompiler::CompileModule must be used to compile modules");
  return CompileUnboundInternal(v8_isolate, source, options, no_cache_reason);
}
References v8::Utils::ApiCheck(), CompileUnboundInternal(), v8::ScriptCompiler::Source::GetResourceOptions(), and v8::ScriptOriginOptions::IsModule().
Referenced by v8::Shell::RealmEval().
CreateCodeCache() [1/2]
ScriptCompiler::CachedData * v8::ScriptCompiler::CreateCodeCache (Local< UnboundModuleScript > unbound_module_script) [static]
Creates and returns code cache for the specified unbound_module_script.
This will return nullptr if the script cannot be serialized. The CachedData returned by this function should be owned by the caller.
Definition at line 2728 of file api.cc.
                                                      {
  i::Handle<i::SharedFunctionInfo> shared =
      Utils::OpenHandle(*unbound_module_script);
  // TODO(jgruber): Remove this DCHECK once Function::GetUnboundScript is gone.
  DCHECK(!i::HeapLayout::InReadOnlySpace(*shared));
  i::Isolate* i_isolate = i::GetIsolateFromWritableObject(*shared);
  Utils::ApiCheck(!i_isolate->serializer_enabled(),
                  "ScriptCompiler::CreateCodeCache",
                  "Cannot create code cache while creating a snapshot");
  i::DisallowJavascriptExecutionDebugOnly no_execution(i_isolate);
  i::DisallowExceptionsDebugOnly no_exceptions(i_isolate);
  DCHECK(shared->is_toplevel());
  return i::CodeSerializer::Serialize(i_isolate, shared);
}
References v8::Utils::ApiCheck(), DCHECK, v8::internal::GetIsolateFromWritableObject(), v8::internal::HeapLayout::InReadOnlySpace(), v8::Utils::OpenHandle(), v8::internal::CodeSerializer::Serialize(), and v8::internal::Isolate::serializer_enabled().
CreateCodeCache() [2/2]
ScriptCompiler::CachedData * v8::ScriptCompiler::CreateCodeCache (Local< UnboundScript > unbound_script) [static]
Creates and returns code cache for the specified unbound_script.
This will return nullptr if the script cannot be serialized. The CachedData returned by this function should be owned by the caller.
Definition at line 2712 of file api.cc.
                                         {
  auto shared = Utils::OpenHandle(*unbound_script);
  // TODO(jgruber): Remove this DCHECK once Function::GetUnboundScript is gone.
  DCHECK(!i::HeapLayout::InReadOnlySpace(*shared));
  i::Isolate* i_isolate = i::GetIsolateFromWritableObject(*shared);
  Utils::ApiCheck(!i_isolate->serializer_enabled(),
                  "ScriptCompiler::CreateCodeCache",
                  "Cannot create code cache while creating a snapshot");
  i::DisallowJavascriptExecutionDebugOnly no_execution(i_isolate);
  i::DisallowExceptionsDebugOnly no_exceptions(i_isolate);
  DCHECK(shared->is_toplevel());
  return i::CodeSerializer::Serialize(i_isolate, shared);
}
References v8::Utils::ApiCheck(), DCHECK, v8::internal::GetIsolateFromWritableObject(), v8::internal::HeapLayout::InReadOnlySpace(), v8::Utils::OpenHandle(), v8::internal::CodeSerializer::Serialize(), and v8::internal::Isolate::serializer_enabled().
Referenced by v8::Shell::ExecuteString().
CreateCodeCacheForFunction()
ScriptCompiler::CachedData * v8::ScriptCompiler::CreateCodeCacheForFunction (Local< Function > function) [static]
Creates and returns code cache for the specified function that was previously produced by CompileFunction.
This will return nullptr if the script cannot be serialized. The CachedData returned by this function should be owned by the caller.
Definition at line 2744 of file api.cc.
                              {
  auto js_function = i::Cast<i::JSFunction>(Utils::OpenDirectHandle(*function));
  i::Isolate* i_isolate = i::Isolate::Current();
  Utils::ApiCheck(!i_isolate->serializer_enabled(),
                  "ScriptCompiler::CreateCodeCacheForFunction",
                  "Cannot create code cache while creating a snapshot");
  i::Handle<i::SharedFunctionInfo> shared(js_function->shared(), i_isolate);
  i::DisallowJavascriptExecutionDebugOnly no_execution(i_isolate);
  i::DisallowExceptionsDebugOnly no_exceptions(i_isolate);
  Utils::ApiCheck(shared->is_wrapped(),
                  "v8::ScriptCompiler::CreateCodeCacheForFunction",
                  "Expected SharedFunctionInfo with wrapped source code");
  return i::CodeSerializer::Serialize(i_isolate, shared);
}
References v8::Utils::ApiCheck(), v8::internal::Isolate::Current(), v8::Utils::OpenDirectHandle(), v8::internal::CodeSerializer::Serialize(), and v8::internal::Isolate::serializer_enabled().
StartConsumingCodeCache()
ScriptCompiler::ConsumeCodeCacheTask * v8::ScriptCompiler::StartConsumingCodeCache (Isolate * isolate, std::unique_ptr< CachedData > source) [static]
Definition at line 2628 of file api.cc.
                                                                {
  if (!i::v8_flags.concurrent_cache_deserialization) return nullptr;
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  i::DisallowJavascriptExecutionDebugOnly no_execution(i_isolate);
  i::DisallowExceptionsDebugOnly no_exceptions(i_isolate);
  return new ScriptCompiler::ConsumeCodeCacheTask(
      std::make_unique<i::BackgroundDeserializeTask>(i_isolate,
                                                     std::move(cached_data)));
}
References v8::internal::v8_flags.
StartConsumingCodeCacheOnBackground()
ScriptCompiler::ConsumeCodeCacheTask * v8::ScriptCompiler::StartConsumingCodeCacheOnBackground (Isolate * isolate, std::unique_ptr< CachedData > source) [static]
Definition at line 2640 of file api.cc.
                                                                {
  if (!i::v8_flags.concurrent_cache_deserialization) return nullptr;
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  return new ScriptCompiler::ConsumeCodeCacheTask(
      std::make_unique<i::BackgroundDeserializeTask>(i_isolate,
                                                     std::move(cached_data)));
}
References v8::internal::v8_flags.
StartStreaming()
ScriptCompiler::ScriptStreamingTask * v8::ScriptCompiler::StartStreaming (Isolate * isolate, StreamedSource * source, v8::ScriptType type = ScriptType::kClassic, CompileOptions options = kNoCompileOptions, CompileHintCallback compile_hint_callback = nullptr, void * compile_hint_callback_data = nullptr) [static]
Returns a task which streams script data into V8, or NULL if the script cannot be streamed.
The user is responsible for running the task on a background thread and deleting it. When ran, the task starts parsing the script, and it will request data from the StreamedSource as needed. When ScriptStreamingTask::Run exits, all data has been streamed and the script can be compiled (see Compile below).
This API allows to start the streaming with as little data as possible, and the remaining data (for example, the ScriptOrigin) is passed to Compile.
Definition at line 2573 of file api.cc.
                                      {
  Utils::ApiCheck(v8::ScriptCompiler::CompileOptionsIsValid(options),
                  "v8::ScriptCompiler::StartStreaming",
                  "Invalid CompileOptions");
  if (!i::v8_flags.script_streaming) return nullptr;
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  i::ScriptStreamingData* data = source->impl();
  std::unique_ptr<i::BackgroundCompileTask> task =
      std::make_unique<i::BackgroundCompileTask>(
          data, i_isolate, type, options, &source->compilation_details(),
          compile_hint_callback, compile_hint_callback_data);
  data->task = std::move(task);
  return new ScriptCompiler::ScriptStreamingTask(data);
}
References v8::Utils::ApiCheck(), v8::ScriptCompiler::StreamedSource::compilation_details(), CompileOptionsIsValid(), v8::ScriptCompiler::StreamedSource::impl(), v8::internal::ScriptStreamingData::task, v8::internal::tracing::type, and v8::internal::v8_flags.
Referenced by v8::Shell::CompileString().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-script.h
/mnt/V8SourceCode/src/api/api.cc