v8::base::DoublyThreadedList< T, DTLTraits > Class Template Reference
#include <doubly-threaded-list.h>
Classes
class end_iterator
class iterator
Public Member Functions
DoublyThreadedList ()=default
DoublyThreadedList (DoublyThreadedList &&other) V8_NOEXCEPT
void PushFront (T x)
T Front () const
void PopFront ()
bool empty () const
iterator begin () const
end_iterator end () const
iterator RemoveAt (iterator &it)
bool Contains (T needle) const
bool ContainsSlow (T needle) const
Static Public Member Functions
static void Remove (T x)
Static Private Member Functions
static bool empty (T x)
Private Attributes
T head_ {}
Detailed Description
template<class T, class DTLTraits = DoublyThreadedListTraits<T>>
class v8::base::DoublyThreadedList< T, DTLTraits >
Definition at line 30 of file doubly-threaded-list.h.
Constructor & Destructor Documentation
DoublyThreadedList() [1/2]
template<class T , class DTLTraits = DoublyThreadedListTraits<T>>
v8::base::DoublyThreadedList< T, DTLTraits >::DoublyThreadedList () [default]
DoublyThreadedList() [2/2]
template<class T , class DTLTraits = DoublyThreadedListTraits<T>>
v8::base::DoublyThreadedList< T, DTLTraits >::DoublyThreadedList (DoublyThreadedList< T, DTLTraits > && other) [inline]
Definition at line 83 of file doubly-threaded-list.h.
                                                             {
    head_ = other.head_;
    if (DTLTraits::non_empty(head_)) {
      *DTLTraits::prev(head_) = &head_;
    }
    other.head_ = {};
  }
References v8::base::DoublyThreadedList< T, DTLTraits >::head_.
Member Function Documentation
begin()
template<class T , class DTLTraits = DoublyThreadedListTraits<T>>
iterator v8::base::DoublyThreadedList< T, DTLTraits >::begin () const [inline]
Definition at line 116 of file doubly-threaded-list.h.
{ return iterator{head_}; }
References v8::base::DoublyThreadedList< T, DTLTraits >::head_.
Referenced by v8::base::DoublyThreadedList< T, DTLTraits >::Front(), v8::internal::TracedHandles::ProcessWeakYoungObjects(), v8::internal::TracedHandles::ResetDeadNodes(), and v8::internal::TracedHandles::UpdateListOfYoungNodes().
Contains()
template<class T , class DTLTraits = DoublyThreadedListTraits<T>>
bool v8::base::DoublyThreadedList< T, DTLTraits >::Contains (T needle) const [inline]
Definition at line 130 of file doubly-threaded-list.h.
                                {
    const bool in_use = DTLTraits::in_use(needle);
    DCHECK_EQ(in_use, ContainsSlow(needle));
    return in_use;
  }
References v8::base::DoublyThreadedList< T, DTLTraits >::ContainsSlow(), and DCHECK_EQ.
Referenced by v8::internal::TracedHandles::ProcessWeakYoungObjects().
ContainsSlow()
template<class T , class DTLTraits = DoublyThreadedListTraits<T>>
bool v8::base::DoublyThreadedList< T, DTLTraits >::ContainsSlow (T needle) const [inline]
Definition at line 136 of file doubly-threaded-list.h.
                                    {
    for (T element : *this) {
      if (element == needle) {
        return true;
      }
    }
    return false;
  }
Referenced by v8::base::DoublyThreadedList< T, DTLTraits >::Contains(), and v8::internal::TracedHandles::FreeNode().
empty() [1/2]
template<class T , class DTLTraits = DoublyThreadedListTraits<T>>
bool v8::base::DoublyThreadedList< T, DTLTraits >::empty () const [inline]
Definition at line 114 of file doubly-threaded-list.h.
{ return !DTLTraits::non_empty(head_); }
References v8::base::DoublyThreadedList< T, DTLTraits >::head_.
Referenced by v8::internal::TracedHandles::AllocateNode(), v8::base::DoublyThreadedList< T, DTLTraits >::Front(), v8::internal::TracedHandles::HasYoung(), v8::base::DoublyThreadedList< T, DTLTraits >::PopFront(), v8::base::DoublyThreadedList< T, DTLTraits >::PushFront(), v8::internal::TracedHandles::RefillUsableNodeBlocks(), v8::base::DoublyThreadedList< T, DTLTraits >::Remove(), v8::internal::TracedHandles::ResetDeadNodes(), and v8::internal::TracedHandles::~TracedHandles().
empty() [2/2]
template<class T , class DTLTraits = DoublyThreadedListTraits<T>>
static bool v8::base::DoublyThreadedList< T, DTLTraits >::empty (T x) [inline], [static], [private]
Definition at line 146 of file doubly-threaded-list.h.
{ return !DTLTraits::non_empty(x); }
end()
template<class T , class DTLTraits = DoublyThreadedListTraits<T>>
end_iterator v8::base::DoublyThreadedList< T, DTLTraits >::end () const [inline]
Definition at line 117 of file doubly-threaded-list.h.
{ return end_iterator{}; }
Referenced by v8::internal::TracedHandles::ProcessWeakYoungObjects(), v8::internal::TracedHandles::ResetDeadNodes(), and v8::internal::TracedHandles::UpdateListOfYoungNodes().
Front()
template<class T , class DTLTraits = DoublyThreadedListTraits<T>>
T v8::base::DoublyThreadedList< T, DTLTraits >::Front () const [inline]
Definition at line 104 of file doubly-threaded-list.h.
                  {
    DCHECK(!empty());
    return *begin();
  }
References v8::base::DoublyThreadedList< T, DTLTraits >::begin(), DCHECK, and v8::base::DoublyThreadedList< T, DTLTraits >::empty().
Referenced by v8::internal::TracedHandles::AllocateNode(), v8::base::DoublyThreadedList< T, DTLTraits >::PopFront(), v8::internal::TracedHandles::RefillUsableNodeBlocks(), and v8::internal::TracedHandles::~TracedHandles().
PopFront()
template<class T , class DTLTraits = DoublyThreadedListTraits<T>>
void v8::base::DoublyThreadedList< T, DTLTraits >::PopFront () [inline]
Definition at line 109 of file doubly-threaded-list.h.
                  {
    DCHECK(!empty());
    Remove(Front());
  }
References DCHECK, v8::base::DoublyThreadedList< T, DTLTraits >::empty(), v8::base::DoublyThreadedList< T, DTLTraits >::Front(), and v8::base::DoublyThreadedList< T, DTLTraits >::Remove().
Referenced by v8::internal::TracedHandles::~TracedHandles().
PushFront()
template<class T , class DTLTraits = DoublyThreadedListTraits<T>>
void v8::base::DoublyThreadedList< T, DTLTraits >::PushFront (T x) [inline]
Definition at line 93 of file doubly-threaded-list.h.
                      {
    DCHECK(empty(*DTLTraits::next(x)));
    DCHECK_EQ(*DTLTraits::prev(x), nullptr);
    *DTLTraits::next(x) = head_;
    *DTLTraits::prev(x) = &head_;
    if (DTLTraits::non_empty(head_)) {
      *DTLTraits::prev(head_) = DTLTraits::next(x);
    }
    head_ = x;
  }
References DCHECK, DCHECK_EQ, v8::base::DoublyThreadedList< T, DTLTraits >::empty(), and v8::base::DoublyThreadedList< T, DTLTraits >::head_.
Referenced by v8::internal::compiler::turboshaft::MemoryContentTable::AddKeyInBaseOffsetMaps(), v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::AddKeyInBaseOffsetMaps(), v8::internal::TracedHandles::Create(), v8::internal::TracedHandles::FreeNode(), v8::internal::TracedHandles::ProcessWeakYoungObjects(), and v8::internal::TracedHandles::RefillUsableNodeBlocks().
Remove()
template<class T , class DTLTraits = DoublyThreadedListTraits<T>>
static void v8::base::DoublyThreadedList< T, DTLTraits >::Remove (T x) [inline], [static]
Definition at line 64 of file doubly-threaded-list.h.
                          {
    if (*DTLTraits::prev(x) == nullptr) {
      DCHECK(empty(*DTLTraits::next(x)));
      // {x} already removed from the list.
      return;
    }
    T** prev = DTLTraits::prev(x);
    T* next = DTLTraits::next(x);
    **prev = *next;
    if (DTLTraits::non_empty(*next)) *DTLTraits::prev(*next) = *prev;
    *DTLTraits::prev(x) = nullptr;
    *DTLTraits::next(x) = {};
  }
References DCHECK, and v8::base::DoublyThreadedList< T, DTLTraits >::empty().
Referenced by v8::internal::TracedHandles::AllocateNode(), v8::internal::TracedHandles::FreeNode(), v8::base::DoublyThreadedList< T, DTLTraits >::PopFront(), v8::internal::TracedHandles::ProcessWeakYoungObjects(), v8::base::DoublyThreadedList< T, DTLTraits >::RemoveAt(), v8::internal::compiler::turboshaft::MemoryContentTable::RemoveKeyFromBaseOffsetMaps(), v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::RemoveKeyFromBaseOffsetMaps(), and v8::internal::TracedHandles::ResetDeadNodes().
RemoveAt()
template<class T , class DTLTraits = DoublyThreadedListTraits<T>>
iterator v8::base::DoublyThreadedList< T, DTLTraits >::RemoveAt (iterator & it) [inline]
Definition at line 122 of file doubly-threaded-list.h.
                                  {
    DCHECK(DTLTraits::non_empty(it.curr_));
    T curr = *it;
    T next = *DTLTraits::next(curr);
    Remove(curr);
    return iterator{next};
  }
References v8::base::DoublyThreadedList< T, DTLTraits >::iterator::curr_, DCHECK, and v8::base::DoublyThreadedList< T, DTLTraits >::Remove().
Referenced by v8::internal::TracedHandles::UpdateListOfYoungNodes().
Member Data Documentation
head_
template<class T , class DTLTraits = DoublyThreadedListTraits<T>>
T v8::base::DoublyThreadedList< T, DTLTraits >::head_ {} [private]
Definition at line 147 of file doubly-threaded-list.h.
Referenced by v8::base::DoublyThreadedList< T, DTLTraits >::begin(), v8::base::DoublyThreadedList< T, DTLTraits >::DoublyThreadedList(), v8::base::DoublyThreadedList< T, DTLTraits >::empty(), and v8::base::DoublyThreadedList< T, DTLTraits >::PushFront().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/base/doubly-threaded-list.h