v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes > Class Template Reference
#include <maglev-graph-processor.h>
Public Member Functions
template<typename... Args>
GraphProcessor (Args &&... args)
void ProcessGraph (Graph *graph)
NodeProcessor & node_processor ()
const NodeProcessor & node_processor () const
Private Member Functions
ProcessingState GetCurrentState ()
ProcessResult ProcessNodeBase (NodeBase *node, const ProcessingState &state)
void PreProcess (NodeBase *node, const ProcessingState &state)
Private Attributes
NodeProcessor node_processor_
Graph * graph_
BlockConstIterator block_it_
NodeIterator node_it_
Detailed Description
template<typename NodeProcessor, bool visit_identity_nodes>
class v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >
Definition at line 90 of file maglev-graph-processor.h.
Constructor & Destructor Documentation
GraphProcessor()
template<typename NodeProcessor , bool visit_identity_nodes>
template<typename... Args>
v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::GraphProcessor (Args &&... args) [inline], [explicit]
Definition at line 93 of file maglev-graph-processor.h.
      : node_processor_(std::forward<Args>(args)...) {}
Member Function Documentation
GetCurrentState()
template<typename NodeProcessor , bool visit_identity_nodes>
ProcessingState v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::GetCurrentState () [inline], [private]
Definition at line 223 of file maglev-graph-processor.h.
                                    {
    return ProcessingState(block_it_, &node_it_);
  }
References v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::block_it_, and v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::node_it_.
Referenced by v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::ProcessGraph().
node_processor() [1/2]
template<typename NodeProcessor , bool visit_identity_nodes>
NodeProcessor& v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::node_processor () [inline]
Definition at line 219 of file maglev-graph-processor.h.
{ return node_processor_; }
References v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::node_processor_.
node_processor() [2/2]
template<typename NodeProcessor , bool visit_identity_nodes>
const NodeProcessor& v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::node_processor () const [inline]
Definition at line 220 of file maglev-graph-processor.h.
{ return node_processor_; }
References v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::node_processor_.
PreProcess()
template<typename NodeProcessor , bool visit_identity_nodes>
void v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::PreProcess (NodeBase * node, const ProcessingState & state) [inline], [private]
Definition at line 243 of file maglev-graph-processor.h.
{}
ProcessGraph()
template<typename NodeProcessor , bool visit_identity_nodes>
void v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::ProcessGraph (Graph * graph) [inline]
Definition at line 96 of file maglev-graph-processor.h.
                                  {
    graph_ = graph;
    node_processor_.PreProcessGraph(graph);
    auto process_constants = [&](auto& map) {
      for (auto it = map.begin(); it != map.end();) {
        ProcessResult result =
            node_processor_.Process(it->second, GetCurrentState());
        switch (result) {
          [[likely]] case ProcessResult::kContinue:
            ++it;
            break;
          case ProcessResult::kRemove:
            it = map.erase(it);
            break;
          case ProcessResult::kHoist:
          case ProcessResult::kAbort:
          case ProcessResult::kSkipBlock:
            UNREACHABLE();
        }
      }
    };
    process_constants(graph->constants());
    process_constants(graph->root());
    process_constants(graph->smi());
    process_constants(graph->tagged_index());
    process_constants(graph->int32());
    process_constants(graph->uint32());
    process_constants(graph->intptr());
    process_constants(graph->float64());
    process_constants(graph->trusted_constants());
    for (block_it_ = graph->begin(); block_it_ != graph->end(); ++block_it_) {
      BasicBlock* block = *block_it_;
      if (V8_UNLIKELY(block->is_dead())) continue;
      BlockProcessResult preprocess_result =
          node_processor_.PreProcessBasicBlock(block);
      switch (preprocess_result) {
        [[likely]] case BlockProcessResult::kContinue:
          break;
        case BlockProcessResult::kSkip:
          continue;
      }
      if (block->has_phi()) {
        auto& phis = *block->phis();
        for (auto it = phis.begin(); it != phis.end();) {
          Phi* phi = *it;
          ProcessResult result =
              node_processor_.Process(phi, GetCurrentState());
          switch (result) {
            [[likely]] case ProcessResult::kContinue:
              ++it;
              break;
            case ProcessResult::kRemove:
              it = phis.RemoveAt(it);
              break;
            case ProcessResult::kAbort:
              return;
            case ProcessResult::kSkipBlock:
              goto skip_block;
            case ProcessResult::kHoist:
              UNREACHABLE();
          }
        }
      }
      node_processor_.PostPhiProcessing();
      for (node_it_ = block->nodes().begin(); node_it_ != block->nodes().end();
           ++node_it_) {
        Node* node = *node_it_;
        if (node == nullptr) continue;
        ProcessResult result = ProcessNodeBase(node, GetCurrentState());
        switch (result) {
          [[likely]] case ProcessResult::kContinue:
            break;
          case ProcessResult::kRemove:
            *node_it_ = nullptr;
            break;
          case ProcessResult::kHoist: {
            DCHECK(block->predecessor_count() == 1 ||
                   (block->predecessor_count() == 2 && block->is_loop()));
            BasicBlock* target = block->predecessor_at(0);
            DCHECK(target->successors().size() == 1);
            Node* cur = *node_it_;
            cur->set_owner(target);
            *node_it_ = nullptr;
            target->nodes().push_back(cur);
            node_it_ = block->nodes().begin();
            break;
          }
          case ProcessResult::kAbort:
            return;
          case ProcessResult::kSkipBlock:
            goto skip_block;
        }
      }
      {
        ProcessResult control_result =
            ProcessNodeBase(block->control_node(), GetCurrentState());
        switch (control_result) {
          [[likely]] case ProcessResult::kContinue:
          case ProcessResult::kSkipBlock:
            break;
          case ProcessResult::kAbort:
            return;
          case ProcessResult::kRemove:
          case ProcessResult::kHoist:
            UNREACHABLE();
        }
      }
    skip_block:
      node_processor_.PostProcessBasicBlock(block);
      continue;
    }
    node_processor_.PostProcessGraph(graph);
  }
References v8::internal::ZoneVector< T >::begin(), v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::block_it_, v8::internal::maglev::BasicBlock::control_node(), v8::internal::DCHECK(), v8::internal::ZoneVector< T >::end(), v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::GetCurrentState(), graph(), v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::graph_, v8::internal::maglev::BasicBlock::has_phi(), v8::internal::maglev::BasicBlock::is_dead(), v8::internal::maglev::BasicBlock::is_loop(), v8::internal::maglev::kAbort, v8::internal::maglev::kContinue, v8::internal::maglev::kHoist, v8::internal::maglev::kRemove, v8::internal::maglev::kSkip, v8::internal::maglev::kSkipBlock, v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::node_it_, v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::node_processor_, v8::internal::maglev::BasicBlock::nodes(), v8::internal::maglev::BasicBlock::phis(), v8::internal::maglev::BasicBlock::predecessor_at(), v8::internal::maglev::BasicBlock::predecessor_count(), v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::ProcessNodeBase(), v8::internal::ZoneVector< T >::push_back(), v8::base::internal::result, v8::internal::maglev::NodeBase::set_owner(), v8::internal::maglev::BasicBlock::successors(), v8::internal::UNREACHABLE(), and V8_UNLIKELY.
Referenced by v8::internal::maglev::MaglevCompiler::Compile(), and v8::internal::compiler::turboshaft::RunMaglevOptimizations().
ProcessNodeBase()
template<typename NodeProcessor , bool visit_identity_nodes>
ProcessResult v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::ProcessNodeBase (NodeBase * node, const ProcessingState & state) [inline], [private]
Definition at line 227 of file maglev-graph-processor.h.
                                                                              {
    switch (node->opcode()) {
#define CASE(OPCODE) \
  case Opcode::k##OPCODE: \
    if constexpr (!visit_identity_nodes && \
                  Opcode::k##OPCODE == Opcode::kIdentity) { \
      return ProcessResult::kContinue; \
    } \
    PreProcess(node->Cast<OPCODE>(), state); \
    return node_processor_.Process(node->Cast<OPCODE>(), state);
      NODE_BASE_LIST(CASE)
#undef CASE
    }
  }
References CASE, NODE_BASE_LIST, and v8::internal::maglev::NodeBase::opcode().
Referenced by v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::ProcessGraph().
Member Data Documentation
block_it_
template<typename NodeProcessor , bool visit_identity_nodes>
BlockConstIterator v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::block_it_ [private]
Definition at line 247 of file maglev-graph-processor.h.
Referenced by v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::GetCurrentState(), and v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::ProcessGraph().
graph_
template<typename NodeProcessor , bool visit_identity_nodes>
Graph* v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::graph_ [private]
Definition at line 246 of file maglev-graph-processor.h.
Referenced by v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::ProcessGraph().
node_it_
template<typename NodeProcessor , bool visit_identity_nodes>
NodeIterator v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::node_it_ [private]
Definition at line 248 of file maglev-graph-processor.h.
Referenced by v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::GetCurrentState(), and v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::ProcessGraph().
node_processor_
template<typename NodeProcessor , bool visit_identity_nodes>
NodeProcessor v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::node_processor_ [private]
Definition at line 245 of file maglev-graph-processor.h.
Referenced by v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::node_processor(), and v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::ProcessGraph().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-graph-processor.h