v8::internal::maglev::ValueLocation Class Reference
#include <maglev-ir.h>
Public Member Functions
ValueLocation ()=default
template<typename... Args>
void SetUnallocated (Args &&... args)
template<typename... Args>
void SetAllocated (Args &&... args)
void InjectLocation (compiler::InstructionOperand location)
bool Cloberred ()
template<typename... Args>
void SetConstant (Args &&... args)
Register AssignedGeneralRegister () const
DoubleRegister AssignedDoubleRegister () const
bool IsAnyRegister () const
bool IsGeneralRegister () const
bool IsDoubleRegister () const
const compiler::InstructionOperand & operand () const
const compiler::InstructionOperand & operand ()
Private Attributes
compiler::InstructionOperand operand_
Detailed Description
Definition at line 1431 of file maglev-ir.h.
Constructor & Destructor Documentation
ValueLocation()
v8::internal::maglev::ValueLocation::ValueLocation () [default]
Member Function Documentation
AssignedDoubleRegister()
DoubleRegister v8::internal::maglev::ValueLocation::AssignedDoubleRegister () const [inline]
Definition at line 1469 of file maglev-ir.h.
                                                {
    DCHECK(IsDoubleRegister());
    return compiler::AllocatedOperand::cast(operand_).GetDoubleRegister();
  }
References v8::internal::compiler::LocationOperand::cast(), v8::internal::DCHECK(), v8::internal::compiler::LocationOperand::GetDoubleRegister(), IsDoubleRegister(), and operand_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::ForceAllocate().
AssignedGeneralRegister()
Register v8::internal::maglev::ValueLocation::AssignedGeneralRegister () const [inline]
Definition at line 1464 of file maglev-ir.h.
                                           {
    DCHECK(!IsDoubleRegister());
    return compiler::AllocatedOperand::cast(operand_).GetRegister();
  }
References v8::internal::compiler::LocationOperand::cast(), v8::internal::DCHECK(), v8::internal::compiler::LocationOperand::GetRegister(), IsDoubleRegister(), and operand_.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::EmitPopMaterialisedResults(), v8::internal::maglev::StraightForwardRegisterAllocator::ForceAllocate(), and v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::RecordMoves().
Cloberred()
bool v8::internal::maglev::ValueLocation::Cloberred () [inline]
Definition at line 1453 of file maglev-ir.h.
                   {
    DCHECK(operand_.IsUnallocated());
    return compiler::UnallocatedOperand::cast(operand_).IsUsedAtStart();
  }
References v8::internal::DCHECK(), and operand_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AssignArbitraryRegisterInput().
InjectLocation()
void v8::internal::maglev::ValueLocation::InjectLocation (compiler::InstructionOperand location) [inline]
Definition at line 1448 of file maglev-ir.h.
                                                           {
    operand_ = location;
  }
References operand_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateEagerDeopt(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateLazyDeopt(), v8::internal::maglev::StraightForwardRegisterAllocator::AssignAnyInput(), and v8::internal::maglev::StraightForwardRegisterAllocator::InitializeBranchTargetPhis().
IsAnyRegister()
bool v8::internal::maglev::ValueLocation::IsAnyRegister () const [inline]
Definition at line 1474 of file maglev-ir.h.
{ return operand_.IsAnyRegister(); }
References v8::internal::compiler::InstructionOperand::IsAnyRegister(), and operand_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::SaveRegisterSnapshot().
IsDoubleRegister()
bool v8::internal::maglev::ValueLocation::IsDoubleRegister () const [inline]
Definition at line 1476 of file maglev-ir.h.
{ return operand_.IsDoubleRegister(); }
References v8::internal::compiler::InstructionOperand::IsDoubleRegister(), and operand_.
Referenced by AssignedDoubleRegister(), AssignedGeneralRegister(), and v8::internal::maglev::StraightForwardRegisterAllocator::ForceAllocate().
IsGeneralRegister()
bool v8::internal::maglev::ValueLocation::IsGeneralRegister () const [inline]
Definition at line 1475 of file maglev-ir.h.
{ return operand_.IsRegister(); }
References v8::internal::compiler::InstructionOperand::IsRegister(), and operand_.
operand() [1/2]
const compiler::InstructionOperand& v8::internal::maglev::ValueLocation::operand () [inline]
Definition at line 1479 of file maglev-ir.h.
{ return operand_; }
References operand_.
operand() [2/2]
const compiler::InstructionOperand& v8::internal::maglev::ValueLocation::operand () const [inline]
Definition at line 1478 of file maglev-ir.h.
{ return operand_; }
References operand_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNodeResult(), v8::internal::maglev::detail::AlreadyInARegister(), v8::internal::maglev::StraightForwardRegisterAllocator::AssignAnyInput(), v8::internal::maglev::StraightForwardRegisterAllocator::AssignArbitraryRegisterInput(), v8::internal::maglev::StraightForwardRegisterAllocator::AssignFixedInput(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildDeoptFrameSingleValue(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::EmitBlockEndGapMoves(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::EmitPopMaterialisedResults(), v8::internal::maglev::NodeBase::ForAllInputsInRegallocAssignmentOrder(), v8::internal::maglev::MaglevAssembler::FromAnyToRegister(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::GetReservedRegisters(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::InputHint(), v8::internal::maglev::MaglevAssembler::IsRootConstant(), v8::internal::maglev::LiveRangeAndNextUseProcessor::MarkUse(), v8::internal::maglev::MaglevGraphLabeller::PrintInput(), v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::PrintResult(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::Process(), v8::internal::maglev::detail::PushInput(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::RecordMoves(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::SameAsInput(), v8::internal::maglev::ValueNode::SetHint(), v8::internal::maglev::ToDoubleRegister(), v8::internal::maglev::MaglevAssembler::ToMemOperand(), v8::internal::maglev::ToRegister(), v8::internal::maglev::detail::ToRegister(), and v8::internal::maglev::UseFixed().
SetAllocated()
template<typename... Args>
void v8::internal::maglev::ValueLocation::SetAllocated (Args &&... args) [inline]
Definition at line 1442 of file maglev-ir.h.
                                    {
    DCHECK(operand_.IsUnallocated());
    operand_ = compiler::AllocatedOperand(args...);
  }
References v8::base::args, v8::internal::DCHECK(), and operand_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNodeResult(), v8::internal::maglev::StraightForwardRegisterAllocator::AssignArbitraryRegisterInput(), and v8::internal::maglev::StraightForwardRegisterAllocator::AssignFixedInput().
SetConstant()
template<typename... Args>
void v8::internal::maglev::ValueLocation::SetConstant (Args &&... args) [inline]
Definition at line 1459 of file maglev-ir.h.
                                   {
    DCHECK(operand_.IsUnallocated());
    operand_ = compiler::ConstantOperand(args...);
  }
References v8::base::args, v8::internal::DCHECK(), and operand_.
SetUnallocated()
template<typename... Args>
void v8::internal::maglev::ValueLocation::SetUnallocated (Args &&... args) [inline]
Definition at line 1436 of file maglev-ir.h.
                                      {
    DCHECK(operand_.IsInvalid());
    operand_ = compiler::UnallocatedOperand(args...);
  }
References v8::base::args, v8::internal::DCHECK(), and operand_.
Referenced by v8::internal::maglev::DefineAsConstant(), v8::internal::maglev::DefineAsFixed(), v8::internal::maglev::DefineAsRegister(), v8::internal::maglev::DefineSameAsFirst(), v8::internal::maglev::UseAndClobberRegister(), v8::internal::maglev::UseAny(), v8::internal::maglev::UseFixed(), and v8::internal::maglev::UseRegister().
Member Data Documentation
operand_
compiler::InstructionOperand v8::internal::maglev::ValueLocation::operand_ [private]
Definition at line 1482 of file maglev-ir.h.
Referenced by AssignedDoubleRegister(), AssignedGeneralRegister(), Cloberred(), InjectLocation(), IsAnyRegister(), IsDoubleRegister(), IsGeneralRegister(), operand(), SetAllocated(), SetConstant(), and SetUnallocated().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h