v8::internal::TaggedImpl< kRefType, StorageType > Class Template Reference
#include <tagged-impl.h>
Public Member Functions
constexpr TaggedImpl ()
constexpr TaggedImpl (StorageType ptr)
operator bool () const =delete
template<HeapObjectReferenceType kOtherRefType, typename U >
constexpr bool operator== (TaggedImpl< kOtherRefType, U > other) const
template<HeapObjectReferenceType kOtherRefType, typename U >
constexpr bool operator!= (TaggedImpl< kOtherRefType, U > other) const
template<HeapObjectReferenceType kOtherRefType>
constexpr bool SafeEquals (TaggedImpl< kOtherRefType, StorageType > other) const
constexpr bool operator< (TaggedImpl other) const
constexpr StorageType ptr () const
constexpr bool IsObject () const
constexpr bool IsSmi () const
bool ToSmi (Tagged< Smi > *value) const
Tagged< Smi > ToSmi () const
constexpr bool IsHeapObject () const
constexpr bool IsCleared () const
constexpr bool IsStrongOrWeak () const
constexpr bool IsStrong () const
constexpr bool IsStrongOrSmi () const
constexpr bool IsWeak () const
constexpr bool IsWeakOrCleared () const
bool GetHeapObjectIfStrong (Tagged< HeapObject > *result) const
bool GetHeapObjectIfStrong (Isolate *isolate, Tagged< HeapObject > *result) const
Tagged< HeapObject > GetHeapObjectAssumeStrong () const
Tagged< HeapObject > GetHeapObjectAssumeStrong (Isolate *isolate) const
bool GetHeapObjectIfWeak (Tagged< HeapObject > *result) const
bool GetHeapObjectIfWeak (Isolate *isolate, Tagged< HeapObject > *result) const
Tagged< HeapObject > GetHeapObjectAssumeWeak () const
Tagged< HeapObject > GetHeapObjectAssumeWeak (Isolate *isolate) const
bool GetHeapObject (Tagged< HeapObject > *result) const
bool GetHeapObject (Isolate *isolate, Tagged< HeapObject > *result) const
bool GetHeapObject (Tagged< HeapObject > *result, HeapObjectReferenceType *reference_type) const
bool GetHeapObject (Isolate *isolate, Tagged< HeapObject > *result, HeapObjectReferenceType *reference_type) const
Tagged< HeapObject > GetHeapObject () const
Tagged< HeapObject > GetHeapObject (Isolate *isolate) const
Tagged< Object > GetHeapObjectOrSmi () const
Tagged< Object > GetHeapObjectOrSmi (Isolate *isolate) const
template<typename T >
Tagged< T > cast () const
Static Public Attributes
static const bool kIsFull = sizeof(StorageType) == kSystemPointerSize
static const bool kCanBeWeak = kRefType == HeapObjectReferenceType::WEAK
Protected Member Functions
StorageType * ptr_location ()
const StorageType * ptr_location () const
Private Attributes
StorageType ptr_
Friends
class CompressedObjectSlot
class CompressedMaybeObjectSlot
class FullObjectSlot
class FullMaybeObjectSlot
class FullHeapObjectSlot
Detailed Description
template<HeapObjectReferenceType kRefType, typename StorageType>
class v8::internal::TaggedImpl< kRefType, StorageType >
Definition at line 33 of file tagged-impl.h.
Constructor & Destructor Documentation
TaggedImpl() [1/2]
template<HeapObjectReferenceType kRefType, typename StorageType >
constexpr v8::internal::TaggedImpl< kRefType, StorageType >::TaggedImpl () [inline], [constexpr]
Definition at line 46 of file tagged-impl.h.
: ptr_{} {}
TaggedImpl() [2/2]
template<HeapObjectReferenceType kRefType, typename StorageType >
constexpr v8::internal::TaggedImpl< kRefType, StorageType >::TaggedImpl (StorageType ptr) [inline], [explicit], [constexpr]
Definition at line 47 of file tagged-impl.h.
: ptr_(ptr) {}
Member Function Documentation
cast()
template<HeapObjectReferenceType kRefType, typename StorageType >
template<typename T >
Tagged<T> v8::internal::TaggedImpl< kRefType, StorageType >::cast () const [inline]
Definition at line 222 of file tagged-impl.h.
                         {
    CHECK(kIsFull);
    DCHECK(!HAS_WEAK_HEAP_OBJECT_TAG(ptr_));
    return Cast<T>(Tagged<Object>(ptr_));
  }
References CHECK, v8::internal::DCHECK(), HAS_WEAK_HEAP_OBJECT_TAG, v8::internal::TaggedImpl< kRefType, StorageType >::kIsFull, and v8::internal::TaggedImpl< kRefType, StorageType >::ptr_.
GetHeapObject() [1/6]
template<HeapObjectReferenceType kRefType, typename StorageType >
Tagged< HeapObject > v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObject [inline]
Definition at line 210 of file tagged-impl-inl.h.
                                                                          {
  CHECK(kIsFull);
  DCHECK(!IsSmi());
  if (kCanBeWeak) {
    DCHECK(!IsCleared());
    return Cast<HeapObject>(Tagged<Object>(ptr_ & ~kWeakHeapObjectMask));
  } else {
    DCHECK(!HAS_WEAK_HEAP_OBJECT_TAG(ptr_));
    return Cast<HeapObject>(Tagged<Object>(ptr_));
  }
}
References CHECK.
GetHeapObject() [2/6]
template<HeapObjectReferenceType kRefType, typename StorageType >
Tagged< HeapObject > v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObject (Isolate * isolate) const [inline]
Definition at line 223 of file tagged-impl-inl.h.
                            {
  if (kIsFull) return GetHeapObject();
  // Implementation for compressed pointers.
  DCHECK(!IsSmi());
  if (kCanBeWeak) {
    DCHECK(!IsCleared());
    return Cast<HeapObject>(
        Tagged<Object>(V8HeapCompressionScheme::DecompressTagged(
            static_cast<Tagged_t>(ptr_) & ~kWeakHeapObjectMask)));
  } else {
    DCHECK(!HAS_WEAK_HEAP_OBJECT_TAG(ptr_));
    return Cast<HeapObject>(
        Tagged<Object>(V8HeapCompressionScheme::DecompressTagged(
            static_cast<Tagged_t>(ptr_))));
  }
}
References v8::internal::DCHECK(), v8::internal::V8HeapCompressionSchemeImpl< Cage >::DecompressTagged(), HAS_WEAK_HEAP_OBJECT_TAG, v8::internal::IsSmi(), and v8::internal::kWeakHeapObjectMask.
GetHeapObject() [3/6]
template<HeapObjectReferenceType kRefType, typename StorageType >
bool v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObject (Isolate * isolate, Tagged< HeapObject > * result) const [inline]
Definition at line 57 of file tagged-impl-inl.h.
                                                        {
  if (kIsFull) return GetHeapObject(result);
  // Implementation for compressed pointers.
  if (!IsStrongOrWeak()) return false;
  *result = GetHeapObject(isolate);
  return true;
}
References v8::base::internal::result.
GetHeapObject() [4/6]
template<HeapObjectReferenceType kRefType, typename StorageType >
bool v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObject (Isolate * isolate, Tagged< HeapObject > * result, HeapObjectReferenceType * reference_type) const [inline]
Definition at line 84 of file tagged-impl-inl.h.
                                                   {
  if (kIsFull) return GetHeapObject(result, reference_type);
  // Implementation for compressed pointers.
  if (!IsStrongOrWeak()) return false;
  *reference_type = IsWeakOrCleared() ? HeapObjectReferenceType::WEAK
                                      : HeapObjectReferenceType::STRONG;
  *result = GetHeapObject(isolate);
  return true;
}
References v8::base::internal::result, STRONG, and WEAK.
GetHeapObject() [5/6]
template<HeapObjectReferenceType kRefType, typename StorageType >
bool v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObject (Tagged< HeapObject > * result) const [inline]
Definition at line 48 of file tagged-impl-inl.h.
                                      {
  CHECK(kIsFull);
  if (!IsStrongOrWeak()) return false;
  *result = GetHeapObject();
  return true;
}
References CHECK, and v8::base::internal::result.
Referenced by v8::internal::Scavenger::CheckAndScavengeObject(), v8::internal::Scavenger::CheckOldToNewSlotForSharedTyped(), v8::internal::TransitionArray::CompactPrototypeTransitionArray(), v8::internal::MarkCompactCollector::CompactTransitionArray(), v8::internal::FeedbackNexus::ConfigureCloneObject(), v8::internal::FeedbackVector::EvictOptimizedCodeMarkedForDeoptimization(), v8::internal::anonymous_namespace{runtime-wasm.cc}::ExecuteWasmDebugBreaks(), v8::internal::Script::FindSharedFunctionInfo(), v8::internal::FeedbackVector::GetOptimizedOsrCode(), v8::internal::Debug::GetTopLevelWithRecompile(), v8::internal::Heap::InFromPage(), v8::internal::Heap::InToPage(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::Code::IterateDeoptimizationLiterals(), v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::LogRejectedPromotionForInvalidSubgraph(), v8::internal::MarkCompactCollector::MarkObjectsFromClientHeap(), v8::internal::SharedFunctionInfo::ScriptIterator::Next(), v8::internal::FeedbackVector::optimized_code(), v8::internal::EphemeronTableUpdatingItem::Process(), v8::internal::anonymous_namespace{read-only-serializer.cc}::EncodeRelocationsVisitor::ProcessSlot(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForCall(), v8::internal::ObjectStatsCollectorImpl::RecordVirtualFeedbackVectorDetails(), v8::internal::RUNTIME_FUNCTION(), v8::internal::anonymous_namespace{wasm-debug.cc}::SetBreakOnEntryFlag(), v8::internal::anonymous_namespace{mark-compact.cc}::UpdateStrongCodeSlot(), v8::internal::anonymous_namespace{mark-compact.cc}::UpdateStrongOldToSharedSlot(), v8::internal::ClientObjectVisitor< Visitor >::VisitInstructionStreamPointer(), v8::internal::UnreachableObjectsFilter::MarkingVisitor::VisitInstructionStreamPointer(), v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::CandidateVisitor::VisitPointers(), and v8::internal::Serializer::ObjectSerializer::VisitProtectedPointer().
GetHeapObject() [6/6]
template<HeapObjectReferenceType kRefType, typename StorageType >
bool v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObject (Tagged< HeapObject > * result, HeapObjectReferenceType * reference_type) const [inline]
Definition at line 73 of file tagged-impl-inl.h.
                                                                               {
  CHECK(kIsFull);
  if (!IsStrongOrWeak()) return false;
  *reference_type = IsWeakOrCleared() ? HeapObjectReferenceType::WEAK
                                      : HeapObjectReferenceType::STRONG;
  *result = GetHeapObject();
  return true;
}
References CHECK, v8::base::internal::result, STRONG, and WEAK.
GetHeapObjectAssumeStrong() [1/2]
template<HeapObjectReferenceType kRefType, typename StorageType >
Tagged< HeapObject > v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectAssumeStrong [inline]
Definition at line 131 of file tagged-impl-inl.h.
                                                                   {
  CHECK(kIsFull);
  DCHECK(IsStrong());
  return Cast<HeapObject>(Tagged<Object>(ptr_));
}
References CHECK, and v8::internal::DCHECK().
Referenced by v8::internal::FeedbackIterator::FeedbackIterator(), v8::internal::FeedbackNexus::GetName(), and v8::internal::FeedbackNexus::ic_state().
GetHeapObjectAssumeStrong() [2/2]
template<HeapObjectReferenceType kRefType, typename StorageType >
Tagged< HeapObject > v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectAssumeStrong (Isolate * isolate) const [inline]
Definition at line 138 of file tagged-impl-inl.h.
                            {
  if (kIsFull) return GetHeapObjectAssumeStrong();
  // Implementation for compressed pointers.
  DCHECK(IsStrong());
  return Cast<HeapObject>(Tagged<Object>(
      V8HeapCompressionScheme::DecompressTagged(static_cast<Tagged_t>(ptr_))));
}
References v8::internal::DCHECK(), and v8::internal::V8HeapCompressionSchemeImpl< Cage >::DecompressTagged().
GetHeapObjectAssumeWeak() [1/2]
template<HeapObjectReferenceType kRefType, typename StorageType >
Tagged< HeapObject > v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectAssumeWeak [inline]
Definition at line 189 of file tagged-impl-inl.h.
          {
  CHECK(kIsFull);
  DCHECK(IsWeak());
  return GetHeapObject();
}
Referenced by v8::internal::DeclarationScope::AllocateScopeInfos(), v8::internal::BackgroundMergeTask::BeginMergeInBackground(), v8::internal::BackgroundMergeTask::CompleteMergeInForeground(), v8::internal::anonymous_namespace{wasm-objects.cc}::CopyEntry(), v8::internal::wasm::CreateMapForType(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetFirstWasmInstance(), v8::internal::anonymous_namespace{wasm-objects.cc}::GetInstance(), v8::internal::compiler::JSObjectRef::GetObjectCreateMap(), v8::internal::TransitionsAccessor::GetTargetFromRaw(), v8::internal::DependentCode::IterateAndCompact(), v8::internal::WasmJSFunction::New(), v8::internal::WeakArrayList::Iterator::Next(), v8::internal::ConstantPoolPointerForwarder::RecordScopeInfos(), v8::internal::WasmMemoryObject::UpdateInstances(), and v8::internal::ConstantPoolPointerForwarder::VisitSharedFunctionInfo().
GetHeapObjectAssumeWeak() [2/2]
template<HeapObjectReferenceType kRefType, typename StorageType >
Tagged< HeapObject > v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectAssumeWeak (Isolate * isolate) const [inline]
Definition at line 197 of file tagged-impl-inl.h.
                            {
  if (kIsFull) return GetHeapObjectAssumeWeak();
  // Implementation for compressed pointers.
  DCHECK(IsWeak());
  return GetHeapObject(isolate);
}
GetHeapObjectIfStrong() [1/2]
template<HeapObjectReferenceType kRefType, typename StorageType >
bool v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectIfStrong (Isolate * isolate, Tagged< HeapObject > * result) const [inline]
Definition at line 112 of file tagged-impl-inl.h.
                                                        {
  if (kIsFull) return GetHeapObjectIfStrong(result);
  // Implementation for compressed pointers.
  if (IsStrong()) {
    *result = Cast<HeapObject>(
        Tagged<Object>(V8HeapCompressionScheme::DecompressTagged(
            static_cast<Tagged_t>(ptr_))));
    return true;
  }
  return false;
}
References v8::base::internal::result.
GetHeapObjectIfStrong() [2/2]
template<HeapObjectReferenceType kRefType, typename StorageType >
bool v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectIfStrong (Tagged< HeapObject > * result) const [inline]
Definition at line 101 of file tagged-impl-inl.h.
                                      {
  CHECK(kIsFull);
  if (IsStrong()) {
    *result = Cast<HeapObject>(Tagged<Object>(ptr_));
    return true;
  }
  return false;
}
References CHECK, and v8::base::internal::result.
Referenced by v8::internal::DescriptorArray::CopyUpToAddAttributes(), v8::internal::V8HeapExplorer::ExtractFeedbackVectorReferences(), v8::internal::V8HeapExplorer::ExtractMapReferences(), v8::internal::FeedbackIterator::FeedbackIterator(), v8::internal::TransitionArray::GetTargetIfExists(), v8::internal::FeedbackNexus::ic_state(), v8::internal::IsPropertyNameFeedback(), and v8::internal::operator<<().
GetHeapObjectIfWeak() [1/2]
template<HeapObjectReferenceType kRefType, typename StorageType >
bool v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectIfWeak (Isolate * isolate, Tagged< HeapObject > * result) const [inline]
Definition at line 168 of file tagged-impl-inl.h.
                                                        {
  if (kIsFull) return GetHeapObjectIfWeak(result);
  // Implementation for compressed pointers.
  if (kCanBeWeak) {
    if (IsWeak()) {
      *result = GetHeapObject(isolate);
      return true;
    }
    return false;
  } else {
    DCHECK(!HAS_WEAK_HEAP_OBJECT_TAG(ptr_));
    return false;
  }
}
References v8::internal::DCHECK(), HAS_WEAK_HEAP_OBJECT_TAG, v8::internal::IsWeak(), and v8::base::internal::result.
GetHeapObjectIfWeak() [2/2]
template<HeapObjectReferenceType kRefType, typename StorageType >
bool v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectIfWeak (Tagged< HeapObject > * result) const [inline]
Definition at line 152 of file tagged-impl-inl.h.
                                      {
  CHECK(kIsFull);
  if (kCanBeWeak) {
    if (IsWeak()) {
      *result = GetHeapObject();
      return true;
    }
    return false;
  } else {
    DCHECK(!HAS_WEAK_HEAP_OBJECT_TAG(ptr_));
    return false;
  }
}
References CHECK, v8::internal::DCHECK(), HAS_WEAK_HEAP_OBJECT_TAG, v8::internal::IsWeak(), and v8::base::internal::result.
Referenced by v8::internal::baseline::BaselineBatchCompilerJob::BaselineBatchCompilerJob(), v8::internal::PrototypeUsers::Compact(), v8::internal::CompileGlobalEval(), v8::internal::V8HeapExplorer::ExtractMapReferences(), v8::internal::FeedbackIterator::FeedbackIterator(), v8::internal::TransitionsAccessor::ForEachTransitionWithKey(), v8::internal::FeedbackNexus::GetConstructorFeedback(), v8::internal::PrototypeInfo::GetDerivedMap(), v8::internal::TransitionsAccessor::GetPrototypeTransition(), v8::internal::FeedbackNexus::ic_state(), v8::internal::anonymous_namespace{js-objects.cc}::InvalidatePrototypeChainsInternal(), v8::internal::ScriptCacheKey::IsMatch(), v8::internal::baseline::BaselineBatchCompiler::MaybeCompileFunction(), v8::internal::operator<<(), v8::internal::anonymous_namespace{compilation-cache-table.cc}::SearchLiteralsMap(), v8::internal::SharedFunctionInfo::SetScript(), v8::internal::ScriptCacheKey::SourceFromObject(), v8::internal::TransitionsAccessor::TraverseTransitionTreeInternal(), and v8::internal::Map::UnwrapFieldType().
GetHeapObjectOrSmi() [1/2]
template<HeapObjectReferenceType kRefType, typename StorageType >
Tagged< Object > v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectOrSmi [inline]
Definition at line 246 of file tagged-impl-inl.h.
                                                                           {
  CHECK(kIsFull);
  if (IsSmi()) {
    return Tagged<Object>(ptr_);
  }
  return GetHeapObject();
}
References CHECK, v8::internal::IsSmi(), and v8::internal::Tagged< Object >.
Referenced by v8::internal::DebugPrintImpl(), v8::internal::TransitionsAccessor::ForEachTransitionWithKey(), v8::internal::DeoptimizationLiteralArray::get(), v8::internal::GetFeedbackSlotType(), and v8::internal::RUNTIME_FUNCTION().
GetHeapObjectOrSmi() [2/2]
template<HeapObjectReferenceType kRefType, typename StorageType >
Tagged< Object > v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectOrSmi (Isolate * isolate) const [inline]
Definition at line 255 of file tagged-impl-inl.h.
                            {
  if constexpr (kIsFull) return GetHeapObjectOrSmi();
  // Implementation for compressed pointers.
  if (IsSmi()) return ToSmi();
  return GetHeapObject(isolate);
}
References v8::internal::IsSmi().
IsCleared()
template<HeapObjectReferenceType kRefType, typename StorageType >
constexpr bool v8::internal::TaggedImpl< kRefType, StorageType >::IsCleared () const [inline], [constexpr]
Definition at line 125 of file tagged-impl.h.
                                          {
    return kCanBeWeak &&
           (static_cast<uint32_t>(ptr_) == kClearedWeakHeapObjectLower32);
  }
References v8::internal::TaggedImpl< kRefType, StorageType >::kCanBeWeak, v8::internal::kClearedWeakHeapObjectLower32, and v8::internal::TaggedImpl< kRefType, StorageType >::ptr_.
Referenced by v8::internal::PrototypeInfo::AddDerivedMap(), v8::internal::WasmTableObject::ClearDispatchTable(), v8::internal::PrototypeUsers::Compact(), v8::internal::TransitionArray::CompactPrototypeTransitionArray(), v8::internal::Heap::CompactRetainedMaps(), v8::internal::Factory::CompactWeakArrayList(), v8::internal::anonymous_namespace{heap.cc}::CompactWeakArrayList(), v8::internal::FeedbackNexus::ConfigureCloneObject(), v8::internal::wasm::CreateMapForType(), v8::internal::DebugPrintImpl(), v8::internal::FeedbackVector::EvictOptimizedCodeMarkedForDeoptimization(), v8::internal::anonymous_namespace{runtime-wasm.cc}::ExecuteWasmDebugBreaks(), v8::internal::FeedbackNexus::ExtractMapsAndHandlers(), v8::internal::FeedbackNexus::ExtractMegaDOMHandler(), v8::internal::DependentCode::FillEntryFromBack(), v8::internal::DeoptimizationLiteralArray::get(), v8::internal::GetFeedbackSlotType(), v8::internal::FeedbackVector::GetOptimizedOsrCode(), v8::internal::WasmDispatchTable::Grow(), v8::internal::WasmTableObject::Grow(), v8::internal::FeedbackNexus::ic_state(), v8::internal::TaggedImpl< kRefType, StorageType >::IsStrongOrWeak(), v8::internal::TaggedImpl< kRefType, StorageType >::IsWeak(), v8::internal::DependentCode::IterateAndCompact(), v8::internal::WasmDispatchTable::MaybeGrowUsesList(), v8::internal::WasmJSFunction::New(), v8::internal::WeakArrayList::Iterator::Next(), v8::internal::operator<<(), v8::internal::wasm::WasmExportWrapperCache::PutInternal(), v8::internal::RUNTIME_FUNCTION(), v8::internal::PrototypeUsers::ScanForEmptySlots(), v8::internal::anonymous_namespace{wasm-debug.cc}::SetBreakOnEntryFlag(), v8::internal::PrototypeInfo::SetObjectCreateMap(), v8::internal::ScriptCacheKey::SourceFromObject(), v8::internal::TransitionsAccessor::TraverseTransitionTreeInternal(), v8::internal::Map::UnwrapFieldType(), v8::internal::WasmTableObject::UpdateDispatchTable(), v8::internal::WasmMemoryObject::UpdateInstances(), and v8::internal::Serializer::ObjectSerializer::VisitProtectedPointer().
IsHeapObject()
template<HeapObjectReferenceType kRefType, typename StorageType >
constexpr bool v8::internal::TaggedImpl< kRefType, StorageType >::IsHeapObject () const [inline], [constexpr]
Definition at line 122 of file tagged-impl.h.
{ return IsStrong(); }
References v8::internal::TaggedImpl< kRefType, StorageType >::IsStrong().
Referenced by v8::internal::MarkCompactCollector::ClearNonLiveReferences(), v8::internal::anonymous_namespace{ic.cc}::GetCloneTargetMap(), and v8::internal::IsHeapObject().
IsObject()
template<HeapObjectReferenceType kRefType, typename StorageType >
constexpr bool v8::internal::TaggedImpl< kRefType, StorageType >::IsObject () const [inline], [constexpr]
Definition at line 114 of file tagged-impl.h.
{ return !IsWeakOrCleared(); }
References v8::internal::TaggedImpl< kRefType, StorageType >::IsWeakOrCleared().
Referenced by v8::internal::IsObject().
IsSmi()
template<HeapObjectReferenceType kRefType, typename StorageType >
constexpr bool v8::internal::TaggedImpl< kRefType, StorageType >::IsSmi () const [inline], [constexpr]
Definition at line 117 of file tagged-impl.h.
{ return HAS_SMI_TAG(ptr_); }
References HAS_SMI_TAG, and v8::internal::TaggedImpl< kRefType, StorageType >::ptr_.
Referenced by v8::internal::IsNumber(), v8::internal::IsPrimitive(), v8::internal::IsSmi(), v8::internal::TaggedImpl< kRefType, StorageType >::IsStrong(), v8::internal::TaggedImpl< kRefType, StorageType >::IsStrongOrWeak(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::StubCache::Set().
IsStrong()
template<HeapObjectReferenceType kRefType, typename StorageType >
constexpr bool v8::internal::TaggedImpl< kRefType, StorageType >::IsStrong () const [inline], [constexpr]
Definition at line 137 of file tagged-impl.h.
                                         {
    DCHECK(kCanBeWeak || (!IsSmi() == HAS_STRONG_HEAP_OBJECT_TAG(ptr_)));
    return kCanBeWeak ? HAS_STRONG_HEAP_OBJECT_TAG(ptr_) : !IsSmi();
  }
References v8::internal::DCHECK(), HAS_STRONG_HEAP_OBJECT_TAG, v8::internal::TaggedImpl< kRefType, StorageType >::IsSmi(), v8::internal::TaggedImpl< kRefType, StorageType >::kCanBeWeak, and v8::internal::TaggedImpl< kRefType, StorageType >::ptr_.
Referenced by v8::internal::TaggedImpl< kRefType, StorageType >::IsHeapObject(), and v8::internal::anonymous_namespace{read-only-serializer.cc}::EncodeRelocationsVisitor::ProcessSlot().
IsStrongOrSmi()
template<HeapObjectReferenceType kRefType, typename StorageType >
constexpr bool v8::internal::TaggedImpl< kRefType, StorageType >::IsStrongOrSmi () const [inline], [constexpr]
Definition at line 144 of file tagged-impl.h.
                                              {
    return !kCanBeWeak || !HAS_WEAK_HEAP_OBJECT_TAG(ptr_);
  }
References HAS_WEAK_HEAP_OBJECT_TAG, v8::internal::TaggedImpl< kRefType, StorageType >::kCanBeWeak, and v8::internal::TaggedImpl< kRefType, StorageType >::ptr_.
IsStrongOrWeak()
template<HeapObjectReferenceType kRefType, typename StorageType >
constexpr bool v8::internal::TaggedImpl< kRefType, StorageType >::IsStrongOrWeak () const [inline], [constexpr]
Definition at line 132 of file tagged-impl.h.
                                               {
    return !IsSmi() && !IsCleared();
  }
References v8::internal::TaggedImpl< kRefType, StorageType >::IsCleared(), and v8::internal::TaggedImpl< kRefType, StorageType >::IsSmi().
Referenced by v8::internal::FeedbackNexus::ConfigureCloneObject(), and v8::internal::anonymous_namespace{read-only-serializer.cc}::EncodeRelocationsVisitor::ProcessSlot().
IsWeak()
template<HeapObjectReferenceType kRefType, typename StorageType >
constexpr bool v8::internal::TaggedImpl< kRefType, StorageType >::IsWeak () const [inline], [constexpr]
Definition at line 149 of file tagged-impl.h.
                                       {
    return IsWeakOrCleared() && !IsCleared();
  }
References v8::internal::TaggedImpl< kRefType, StorageType >::IsCleared(), and v8::internal::TaggedImpl< kRefType, StorageType >::IsWeakOrCleared().
Referenced by v8::internal::DeclarationScope::AllocateScopeInfos(), v8::internal::BackgroundMergeTask::BeginMergeInBackground(), v8::internal::TransitionArray::CompactPrototypeTransitionArray(), v8::internal::Heap::CompactRetainedMaps(), v8::internal::BackgroundMergeTask::CompleteMergeInForeground(), v8::internal::DebugPrintImpl(), v8::internal::TransitionsAccessor::ForEachTransitionWithKey(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetFirstWasmInstance(), v8::internal::compiler::JSObjectRef::GetObjectCreateMap(), v8::internal::IsWeak(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::ConstantPoolPointerForwarder::VisitSharedFunctionInfo().
IsWeakOrCleared()
template<HeapObjectReferenceType kRefType, typename StorageType >
constexpr bool v8::internal::TaggedImpl< kRefType, StorageType >::IsWeakOrCleared () const [inline], [constexpr]
Definition at line 155 of file tagged-impl.h.
                                                {
    return kCanBeWeak && HAS_WEAK_HEAP_OBJECT_TAG(ptr_);
  }
References HAS_WEAK_HEAP_OBJECT_TAG, v8::internal::TaggedImpl< kRefType, StorageType >::kCanBeWeak, and v8::internal::TaggedImpl< kRefType, StorageType >::ptr_.
Referenced by v8::internal::TransitionsAccessor::GetPrototypeTransition(), v8::internal::FeedbackNexus::ic_state(), v8::internal::TaggedImpl< kRefType, StorageType >::IsObject(), v8::internal::TaggedImpl< kRefType, StorageType >::IsWeak(), v8::internal::WasmDispatchTable::MaybeGrowUsesList(), v8::internal::WeakArrayList::Iterator::Next(), v8::internal::PrototypeInfo::ObjectCreateMap(), v8::internal::FeedbackVector::optimized_code(), v8::internal::RELEASE_ACQUIRE_ACCESSORS(), and v8::internal::anonymous_namespace{compilation-cache-table.cc}::SearchLiteralsMap().
operator bool()
template<HeapObjectReferenceType kRefType, typename StorageType >
v8::internal::TaggedImpl< kRefType, StorageType >::operator bool () const [explicit], [delete]
operator!=()
template<HeapObjectReferenceType kRefType, typename StorageType >
template<HeapObjectReferenceType kOtherRefType, typename U >
constexpr bool v8::internal::TaggedImpl< kRefType, StorageType >::operator!= (TaggedImpl< kOtherRefType, U > other) const [inline], [constexpr]
Definition at line 72 of file tagged-impl.h.
                                                                      {
    static_assert(std::is_same_v<U, Address> || std::is_same_v<U, Tagged_t>,
                  "U must be either Address or Tagged_t");
#if defined(V8_EXTERNAL_CODE_SPACE) || defined(V8_ENABLE_SANDBOX)
    // When comparing two full pointer values ensure that it's allowed.
    if (std::is_same_v<StorageType, Address> && std::is_same_v<U, Address>) {
      SLOW_DCHECK(CheckObjectComparisonAllowed(ptr_, other.ptr()));
    }
#endif // defined(V8_EXTERNAL_CODE_SPACE) || defined(V8_ENABLE_SANDBOX)
    return static_cast<Tagged_t>(ptr_) != static_cast<Tagged_t>(other.ptr());
  }
References v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr_, and SLOW_DCHECK.
operator<()
template<HeapObjectReferenceType kRefType, typename StorageType >
constexpr bool v8::internal::TaggedImpl< kRefType, StorageType >::operator< (TaggedImpl< kRefType, StorageType > other) const [inline], [constexpr]
Definition at line 100 of file tagged-impl.h.
                                                   {
#if defined(V8_EXTERNAL_CODE_SPACE) || defined(V8_ENABLE_SANDBOX)
    // When comparing two full pointer values ensure that it's allowed.
    if (std::is_same_v<StorageType, Address>) {
      SLOW_DCHECK(CheckObjectComparisonAllowed(ptr_, other.ptr()));
    }
#endif // defined(V8_EXTERNAL_CODE_SPACE) || defined(V8_ENABLE_SANDBOX)
    return static_cast<Tagged_t>(ptr_) < static_cast<Tagged_t>(other.ptr());
  }
References v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr_, and SLOW_DCHECK.
operator==()
template<HeapObjectReferenceType kRefType, typename StorageType >
template<HeapObjectReferenceType kOtherRefType, typename U >
constexpr bool v8::internal::TaggedImpl< kRefType, StorageType >::operator== (TaggedImpl< kOtherRefType, U > other) const [inline], [constexpr]
Definition at line 56 of file tagged-impl.h.
                                                                      {
    static_assert(std::is_same_v<U, Address> || std::is_same_v<U, Tagged_t>,
                  "U must be either Address or Tagged_t");
#if defined(V8_EXTERNAL_CODE_SPACE) || defined(V8_ENABLE_SANDBOX)
    // When comparing two full pointer values ensure that it's allowed.
    if (std::is_same_v<StorageType, Address> && std::is_same_v<U, Address>) {
      SLOW_DCHECK(CheckObjectComparisonAllowed(ptr_, other.ptr()));
    }
#endif // defined(V8_EXTERNAL_CODE_SPACE) || defined(V8_ENABLE_SANDBOX)
    return static_cast<Tagged_t>(ptr_) == static_cast<Tagged_t>(other.ptr());
  }
References v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr_, and SLOW_DCHECK.
Referenced by v8::internal::TaggedImpl< kRefType, StorageType >::SafeEquals().
ptr()
template<HeapObjectReferenceType kRefType, typename StorageType >
constexpr StorageType v8::internal::TaggedImpl< kRefType, StorageType >::ptr () const [inline], [constexpr]
Definition at line 110 of file tagged-impl.h.
{ return ptr_; }
References v8::internal::TaggedImpl< kRefType, StorageType >::ptr_.
Referenced by v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Acquire_Load(), v8::internal::DeclarationScope::AllocateScopeInfos(), v8::internal::wasm::array_copy_wrapper(), v8::internal::wasm::anonymous_namespace{wasm-external-refs.cc}::ArrayElementAddress(), v8::internal::anonymous_namespace{simd.cc}::ArrayIndexOfIncludes(), v8::internal::JSArray::ArrayJoinConcatToSequentialString(), v8::internal::MicrotaskQueue::CallEnqueueMicrotask(), v8::internal::compiler::CanBeImmediate(), v8::internal::FastJsonStringifier< Char >::CheckCycle(), v8::internal::CheckObjectType(), v8::internal::PagedSpaceBase::Contains(), v8::internal::FullObjectSlot::contains_map_value(), v8::internal::Factory::CopyJSObjectWithAllocationSite(), v8::internal::EternalHandles::Create(), v8::internal::Heap::CreateEarlyReadOnlyMapsAndObjects(), v8::internal::Heap::CreateLateReadOnlyNonJSReceiverMaps(), v8::internal::TranslatedState::CreateNextTranslatedValue(), v8::internal::Heap::InsertIntoRememberedSetFromCode::DebugGetCoverageInfo(), v8::internal::FrameWriter::DebugPrintOutputObject(), v8::internal::anonymous_namespace{pretenuring-handler.cc}::DigestPretenuringFeedback(), v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::Deoptimizer::DoComputeConstructCreateStubFrame(), v8::internal::Deoptimizer::DoComputeConstructInvokeStubFrame(), v8::internal::Deoptimizer::DoComputeUnoptimizedFrame(), v8::internal::MicrotaskQueue::EnqueueMicrotask(), v8::internal::NativeRegExpMacroAssembler::Execute(), v8::internal::FastInReadOnlySpaceOrSmallSmi(), v8::internal::MemoryMeasurement::FinishProcessing(), v8::internal::MarkBit::From(), v8::internal::MarkBit::FromForTesting(), v8::internal::MapWord::FromForwardingAddress(), v8::internal::MemoryChunkMetadata::FromHeapObject(), v8::internal::PageMetadata::FromHeapObject(), v8::internal::MapWord::FromMap(), v8::internal::V8HeapExplorer::GetEntry(), v8::String::GetExternalStringResourceBaseSlow(), v8::String::GetExternalStringResourceSlow(), v8::internal::OrderedHashMap::GetHash(), v8::internal::compiler::GetImmediateIntegerValue(), v8::internal::compiler::IA32OperandGenerator::GetImmediateIntegerValue(), v8::internal::GetOrCreateHash(), v8::internal::TickSample::GetStackSample(), v8::internal::DescriptorLookupCache::Hash(), v8::internal::FeedbackNexus::ic_state(), v8::internal::ImmediateInitializer< Tagged< Smi > >::immediate_for(), v8::internal::NativeContextInferrer::Infer(), v8::internal::InitSelfIndirectPointerField(), v8::internal::anonymous_namespace{js-objects.cc}::InvalidateOnePrototypeValidityCellInternal(), v8::internal::InvalidatePrototypeChainsWrapper(), v8::internal::Heap::IsFreeSpaceValid(), v8::internal::ClearStaleLeftTrimmedPointerVisitor::IsLeftTrimmed(), v8::internal::Serializer::IsNotMappedSymbol(), v8::internal::InstanceTypeChecker::IsOneByteString(), v8::internal::MarkCompactCollector::IsOnEvacuationCandidate(), v8::internal::IsTaggedIndex(), v8::internal::InstanceTypeChecker::IsTwoByteString(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::IsValidSmi(), v8::internal::JSObject::JSObjectShortPrint(), v8::internal::JSReceiverCreateIdentityHash(), v8::internal::Smi::LexicographicCompare(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LoadSmi(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LoadSmiConstant(), v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::LogPromotedObject(), v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::LogRejectedPromotionForFailedPredicate(), v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::LogRejectedPromotionForInvalidSubgraph(), v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::LogRejectedPromotionForNoMatchingHost(), v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointersVisitor::LogUpdatedPointer(), v8::internal::MakePair(), v8::internal::V8FileLogger::MapCreate(), v8::internal::V8FileLogger::MapDetails(), v8::internal::V8FileLogger::MapMoveEvent(), v8::internal::Deoptimizer::MaterializeHeapObjects(), v8::internal::MacroAssembler::Move(), v8::internal::PersistentHandles::NewHandle(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::OperandForDeopt(), v8::internal::TaggedImpl< kRefType, StorageType >::operator!=(), v8::internal::Object::FullPtrComparer::operator()(), v8::internal::Object::Hasher::operator()(), v8::internal::TaggedImpl< kRefType, StorageType >::operator<(), v8::internal::operator==(), v8::internal::TaggedImpl< kRefType, StorageType >::operator==(), v8::internal::Handle< T >::PatchValue(), v8::internal::anonymous_namespace{pretenuring-handler.cc}::PretenureAllocationSiteManually(), v8::internal::StubCache::PrimaryOffset(), v8::internal::JavaScriptFrame::Print(), v8::internal::anonymous_namespace{debug-coverage.cc}::PrintBlockCoverage(), v8::internal::StringStream::PrintMentionedObjectCache(), v8::internal::FieldType::PrintTo(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointersVisitor::ProcessSlot(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::ProcessStrongHeapObject(), v8::internal::Isolate::PropagateExceptionToExternalTryCatch(), v8::internal::GlobalHandleVector< T >::Push(), v8::internal::FrameWriter::PushRawObject(), v8::internal::StringForwardingTable::Record::raw_hash(), v8::internal::MacroAssemblerBase::ReadOnlyRootPtr(), v8::internal::anonymous_namespace{string.cc}::WriteToFlat_RepeatOptimizer< SinkCharT >::RecordFirstOccurrence(), v8::internal::MathRandom::RefillCache(), v8::internal::FullObjectSlot::Relaxed_CompareAndSwap(), v8::internal::FullMaybeObjectSlot::Release_CompareAndSwap(), v8::internal::FullObjectSlot::Release_CompareAndSwap(), v8::internal::FreeListCategory::RepairFreeList(), v8::TryCatch::ResetInternal(), v8::internal::RUNTIME_FUNCTION(), v8::internal::TaggedImpl< kRefType, StorageType >::SafeEquals(), v8::internal::StubCache::SecondaryOffset(), v8::internal::TaggedMember< T, CompressionScheme >::SeqCst_CompareAndSwap(), v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::SeqCst_CompareAndSwap(), v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::SeqCst_Load(), v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::SeqCst_Swap(), v8::internal::WritableRelocInfo::set_target_object(), v8::internal::JavaScriptBuiltinContinuationWithCatchFrame::SetException(), v8::internal::UnoptimizedJSFrame::SetFeedbackVector(), v8::internal::Heap::SetFunctionsMarkedForManualOptimization(), v8::internal::V8HeapExplorer::SetHiddenReference(), v8::internal::Heap::SetRootMaterializedObjects(), v8::internal::ImportedFunctionEntry::SetWasmToWasm(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::ShouldFlushBaselineCode(), v8::internal::StackTraceFailureMessage::StackTraceFailureMessage(), v8::internal::MemoryMeasurement::StartProcessing(), v8::internal::FullObjectSlot::store_map(), v8::internal::EmbedderDataSlot::store_tagged(), v8::internal::wasm::Handlers< Compressed >::StoreRefIntoMemory(), v8::internal::compiler::OperandGenerator::ToConstant(), v8::internal::compiler::OperandGenerator::ToNegatedConstant(), v8::internal::anonymous_namespace{string.cc}::WriteToFlat_RepeatOptimizer< SinkCharT >::TryApply(), v8::internal::StringTable::TryStringToIndexOrLookupExisting(), v8::internal::StringTable::Data::TryStringToIndexOrLookupExisting(), v8::TypecheckWitness::Update(), v8::internal::anonymous_namespace{mark-compact.cc}::UpdateStrongCodeSlot(), v8::internal::anonymous_namespace{mark-compact.cc}::UpdateStrongOldToSharedSlot(), v8::internal::UpdateTypedSlotHelper::UpdateTypedSlot(), wasm::FuncData::v8_callback(), v8::internal::anonymous_namespace{compiler.cc}::VerifyCodeMerge(), v8::internal::Isolate::VerifyStaticRoots(), v8::internal::RootMarkingVisitor::VisitRootPointer(), and v8::internal::PointersUpdatingVisitor::VisitRootPointer().
ptr_location() [1/2]
template<HeapObjectReferenceType kRefType, typename StorageType >
StorageType* v8::internal::TaggedImpl< kRefType, StorageType >::ptr_location () [inline], [protected]
Definition at line 229 of file tagged-impl.h.
{ return &ptr_; }
References v8::internal::TaggedImpl< kRefType, StorageType >::ptr_.
ptr_location() [2/2]
template<HeapObjectReferenceType kRefType, typename StorageType >
const StorageType* v8::internal::TaggedImpl< kRefType, StorageType >::ptr_location () const [inline], [protected]
Definition at line 230 of file tagged-impl.h.
{ return &ptr_; }
References v8::internal::TaggedImpl< kRefType, StorageType >::ptr_.
SafeEquals()
template<HeapObjectReferenceType kRefType, typename StorageType >
template<HeapObjectReferenceType kOtherRefType>
constexpr bool v8::internal::TaggedImpl< kRefType, StorageType >::SafeEquals (TaggedImpl< kOtherRefType, StorageType > other) const [inline], [constexpr]
Definition at line 89 of file tagged-impl.h.
                                                          {
    static_assert(std::is_same_v<StorageType, Address>,
                  "Safe comparison is allowed only for full tagged values");
    if (V8_EXTERNAL_CODE_SPACE_BOOL || V8_ENABLE_SANDBOX_BOOL) {
      return ptr_ == other.ptr();
    }
    return this->operator==(other);
  }
References v8::internal::TaggedImpl< kRefType, StorageType >::operator==(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr_, V8_ENABLE_SANDBOX_BOOL, and V8_EXTERNAL_CODE_SPACE_BOOL.
Referenced by v8::internal::Object::KeyEqualSafe::operator()(), v8::internal::StringStream::PrintSecurityTokenIfChanged(), v8::internal::RUNTIME_FUNCTION(), v8::internal::ContextSerializer::SerializeObjectImpl(), v8::internal::Serializer::ObjectSerializer::SerializePrologue(), v8::internal::StubCache::Set(), and v8::internal::ObjectStatsCollectorImpl::ShouldRecordObject().
ToSmi() [1/2]
template<HeapObjectReferenceType kRefType, typename StorageType >
Tagged< Smi > v8::internal::TaggedImpl< kRefType, StorageType >::ToSmi [inline]
Definition at line 33 of file tagged-impl-inl.h.
                                                           {
  V8_ASSUME(HAS_SMI_TAG(ptr_));
  if constexpr (kIsFull) {
    return Tagged<Smi>(ptr_);
  }
  // Implementation for compressed pointers.
  return Tagged<Smi>(V8HeapCompressionScheme::DecompressTaggedSigned(
      static_cast<Tagged_t>(ptr_)));
}
References v8::internal::V8HeapCompressionSchemeImpl< Cage >::DecompressTaggedSigned(), HAS_SMI_TAG, v8::internal::Tagged< Smi >, and V8_ASSUME.
ToSmi() [2/2]
template<HeapObjectReferenceType kRefType, typename StorageType >
bool v8::internal::TaggedImpl< kRefType, StorageType >::ToSmi (Tagged< Smi > * value) const [inline]
Definition at line 24 of file tagged-impl-inl.h.
                                                                      {
  if (HAS_SMI_TAG(ptr_)) {
    *value = ToSmi();
    return true;
  }
  return false;
}
References HAS_SMI_TAG, and v8::internal::value.
Referenced by v8::internal::LoadHandler::CanHandleHolderNotLookupStart(), v8::internal::PrototypeUsers::empty_slot_index(), v8::internal::wasm::WasmExportWrapperCache::EnsureCapacity(), v8::internal::wasm::WasmExportWrapperCache::Get(), v8::internal::LoadHandler::GetKeyedAccessLoadMode(), v8::internal::StoreHandler::GetKeyedAccessStoreMode(), v8::internal::TransitionArray::GetTargetIfExists(), v8::internal::FeedbackNexus::ic_state(), v8::internal::ScriptCacheKey::IsMatch(), v8::internal::FeedbackNexus::IsOneMapManyNames(), v8::internal::TransitionArray::NumberOfPrototypeTransitions(), v8::internal::operator<<(), v8::internal::wasm::WasmExportWrapperCache::PutInternal(), v8::internal::MarkCompactCollector::RetainMaps(), and v8::internal::MarkCompactCollector::TransitionArrayNeedsCompaction().
Friends And Related Function Documentation
CompressedMaybeObjectSlot
template<HeapObjectReferenceType kRefType, typename StorageType >
friend class CompressedMaybeObjectSlot [friend]
Definition at line 234 of file tagged-impl.h.
CompressedObjectSlot
template<HeapObjectReferenceType kRefType, typename StorageType >
friend class CompressedObjectSlot [friend]
Definition at line 233 of file tagged-impl.h.
FullHeapObjectSlot
template<HeapObjectReferenceType kRefType, typename StorageType >
friend class FullHeapObjectSlot [friend]
Definition at line 237 of file tagged-impl.h.
FullMaybeObjectSlot
template<HeapObjectReferenceType kRefType, typename StorageType >
friend class FullMaybeObjectSlot [friend]
Definition at line 236 of file tagged-impl.h.
FullObjectSlot
template<HeapObjectReferenceType kRefType, typename StorageType >
friend class FullObjectSlot [friend]
Definition at line 235 of file tagged-impl.h.
Member Data Documentation
kCanBeWeak
template<HeapObjectReferenceType kRefType, typename StorageType >
const bool v8::internal::TaggedImpl< kRefType, StorageType >::kCanBeWeak = kRefType == HeapObjectReferenceType::WEAK [static]
Definition at line 44 of file tagged-impl.h.
Referenced by v8::internal::TaggedImpl< kRefType, StorageType >::IsCleared(), v8::internal::TaggedImpl< kRefType, StorageType >::IsStrong(), v8::internal::TaggedImpl< kRefType, StorageType >::IsStrongOrSmi(), and v8::internal::TaggedImpl< kRefType, StorageType >::IsWeakOrCleared().
kIsFull
template<HeapObjectReferenceType kRefType, typename StorageType >
const bool v8::internal::TaggedImpl< kRefType, StorageType >::kIsFull = sizeof(StorageType) == kSystemPointerSize [static]
Definition at line 42 of file tagged-impl.h.
Referenced by v8::internal::TaggedImpl< kRefType, StorageType >::cast().
ptr_
template<HeapObjectReferenceType kRefType, typename StorageType >
StorageType v8::internal::TaggedImpl< kRefType, StorageType >::ptr_ [private]
Definition at line 239 of file tagged-impl.h.
Referenced by v8::internal::TaggedImpl< kRefType, StorageType >::cast(), v8::internal::TaggedImpl< kRefType, StorageType >::IsCleared(), v8::internal::TaggedImpl< kRefType, StorageType >::IsSmi(), v8::internal::TaggedImpl< kRefType, StorageType >::IsStrong(), v8::internal::TaggedImpl< kRefType, StorageType >::IsStrongOrSmi(), v8::internal::TaggedImpl< kRefType, StorageType >::IsWeakOrCleared(), v8::internal::TaggedImpl< kRefType, StorageType >::operator!=(), v8::internal::TaggedImpl< kRefType, StorageType >::operator<(), v8::internal::TaggedImpl< kRefType, StorageType >::operator==(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr_location(), and v8::internal::TaggedImpl< kRefType, StorageType >::SafeEquals().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/common/globals.h
/mnt/V8SourceCode/src/objects/tagged-impl.h
/mnt/V8SourceCode/src/objects/tagged-impl-inl.h