v8::CpuProfilingOptions Class Reference
Optional profiling attributes.
#include <v8-profiler.h>
Public Member Functions
CpuProfilingOptions (CpuProfilingMode mode=kLeafNodeLineNumbers, unsigned max_samples=kNoSampleLimit, int sampling_interval_us=0, MaybeLocal< Context > filter_context=MaybeLocal< Context >())
CpuProfilingOptions (CpuProfilingOptions &&)=default
CpuProfilingOptions & operator= (CpuProfilingOptions &&)=default
CpuProfilingMode mode () const
unsigned max_samples () const
int sampling_interval_us () const
Static Public Attributes
static const unsigned kNoSampleLimit = UINT_MAX
Private Member Functions
bool has_filter_context () const
void * raw_filter_context () const
Private Attributes
CpuProfilingMode mode_
unsigned max_samples_
int sampling_interval_us_
Global< Context > filter_context_
Friends
class internal::CpuProfile
Detailed Description
Optional profiling attributes.
Definition at line 362 of file v8-profiler.h.
Constructor & Destructor Documentation
CpuProfilingOptions() [1/2]
v8::CpuProfilingOptions::CpuProfilingOptions (CpuProfilingMode mode = kLeafNodeLineNumbers, unsigned max_samples = kNoSampleLimit, int sampling_interval_us = 0, MaybeLocal< Context > filter_context = MaybeLocal<Context>())
Parameters
mode Type of computation of stack frame line numbers.
max_samples The maximum number of samples that should be recorded by the profiler. Samples obtained after this limit will be discarded.
sampling_interval_us controls the profile-specific target sampling interval. The provided sampling interval will be snapped to the next lowest non-zero multiple of the profiler's sampling interval, set via SetSamplingInterval(). If zero, the sampling interval will be equal to the profiler's sampling interval.
filter_context If specified, profiles will only contain frames using this context. Other frames will be elided.
Definition at line 11418 of file api.cc.
    : mode_(mode),
      max_samples_(max_samples),
      sampling_interval_us_(sampling_interval_us) {
  if (!filter_context.IsEmpty()) {
    Local<Context> local_filter_context = filter_context.ToLocalChecked();
    filter_context_.Reset(v8::Isolate::GetCurrent(), local_filter_context);
    filter_context_.SetWeak();
  }
}
References filter_context_, v8::Isolate::GetCurrent(), v8::MaybeLocal< T >::IsEmpty(), and v8::MaybeLocal< T >::ToLocalChecked().
CpuProfilingOptions() [2/2]
v8::CpuProfilingOptions::CpuProfilingOptions (CpuProfilingOptions &&) [default]
Member Function Documentation
has_filter_context()
bool v8::CpuProfilingOptions::has_filter_context () const [inline], [private]
Definition at line 397 of file v8-profiler.h.
{ return !filter_context_.IsEmpty(); }
Referenced by v8::internal::CpuProfile::CpuProfile().
max_samples()
unsigned v8::CpuProfilingOptions::max_samples () const [inline]
Definition at line 391 of file v8-profiler.h.
{ return max_samples_; }
Referenced by v8::internal::CpuProfile::AddPath().
mode()
CpuProfilingMode v8::CpuProfilingOptions::mode () const [inline]
Definition at line 390 of file v8-profiler.h.
{ return mode_; }
Referenced by v8::internal::CpuProfile::AddPath().
operator=()
CpuProfilingOptions& v8::CpuProfilingOptions::operator= (CpuProfilingOptions &&) [default]
raw_filter_context()
void * v8::CpuProfilingOptions::raw_filter_context () const [private]
Definition at line 11432 of file api.cc.
                                                    {
  return reinterpret_cast<void*>(
      i::Cast<i::Context>(*Utils::OpenPersistent(filter_context_))
          ->native_context()
          .address());
}
References filter_context_, and v8::Utils::OpenPersistent().
Referenced by v8::internal::CpuProfile::CpuProfile().
sampling_interval_us()
int v8::CpuProfilingOptions::sampling_interval_us () const [inline]
Definition at line 392 of file v8-profiler.h.
{ return sampling_interval_us_; }
Referenced by v8::internal::CpuProfile::CheckSubsample(), and v8::internal::CpuProfile::sampling_interval_us().
Friends And Related Function Documentation
internal::CpuProfile
friend class internal::CpuProfile [friend]
Definition at line 395 of file v8-profiler.h.
Member Data Documentation
filter_context_
Global<Context> v8::CpuProfilingOptions::filter_context_ [private]
Definition at line 403 of file v8-profiler.h.
Referenced by CpuProfilingOptions(), and raw_filter_context().
kNoSampleLimit
const unsigned v8::CpuProfilingOptions::kNoSampleLimit = UINT_MAX [static]
Definition at line 365 of file v8-profiler.h.
Referenced by v8::internal::CpuProfile::AddPath(), and v8::CpuProfiler::Start().
max_samples_
unsigned v8::CpuProfilingOptions::max_samples_ [private]
Definition at line 401 of file v8-profiler.h.
mode_
CpuProfilingMode v8::CpuProfilingOptions::mode_ [private]
Definition at line 400 of file v8-profiler.h.
sampling_interval_us_
int v8::CpuProfilingOptions::sampling_interval_us_ [private]
Definition at line 402 of file v8-profiler.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-profiler.h
/mnt/V8SourceCode/src/api/api.cc