v8::internal::RegExpMatchAllAssembler Class Reference
#include <builtins-regexp-gen.h>
Public Member Functions
RegExpMatchAllAssembler (compiler::CodeAssemblerState *state)
TNode< JSAny > CreateRegExpStringIterator (TNode< NativeContext > native_context, TNode< JSAny > regexp, TNode< String > string, TNode< BoolT > global, TNode< BoolT > full_unicode)
Additional Inherited Members
Detailed Description
Definition at line 244 of file builtins-regexp-gen.h.
Constructor & Destructor Documentation
RegExpMatchAllAssembler()
v8::internal::RegExpMatchAllAssembler::RegExpMatchAllAssembler (compiler::CodeAssemblerState * state) [inline], [explicit]
Definition at line 246 of file builtins-regexp-gen.h.
      : RegExpBuiltinsAssembler(state) {}
Member Function Documentation
CreateRegExpStringIterator()
TNode< JSAny > v8::internal::RegExpMatchAllAssembler::CreateRegExpStringIterator (TNode< NativeContext > native_context, TNode< JSAny > regexp, TNode< String > string, TNode< BoolT > global, TNode< BoolT > full_unicode)
Definition at line 1567 of file builtins-regexp-gen.cc.
                                                                          {
  TNode<Map> map = CAST(LoadContextElementNoCell(
      native_context,
      Context::INITIAL_REGEXP_STRING_ITERATOR_PROTOTYPE_MAP_INDEX));
  // 4. Let iterator be ObjectCreate(%RegExpStringIteratorPrototype%, «
  // [[IteratingRegExp]], [[IteratedString]], [[Global]], [[Unicode]],
  // [[Done]] »).
  TNode<HeapObject> iterator = Allocate(JSRegExpStringIterator::kHeaderSize);
  StoreMapNoWriteBarrier(iterator, map);
  StoreObjectFieldRoot(iterator,
                       JSRegExpStringIterator::kPropertiesOrHashOffset,
                       RootIndex::kEmptyFixedArray);
  StoreObjectFieldRoot(iterator, JSRegExpStringIterator::kElementsOffset,
                       RootIndex::kEmptyFixedArray);
  // 5. Set iterator.[[IteratingRegExp]] to R.
  StoreObjectFieldNoWriteBarrier(
      iterator, JSRegExpStringIterator::kIteratingRegExpOffset, regexp);
  // 6. Set iterator.[[IteratedString]] to S.
  StoreObjectFieldNoWriteBarrier(
      iterator, JSRegExpStringIterator::kIteratedStringOffset, string);
  // 7. Set iterator.[[Global]] to global.
  // 8. Set iterator.[[Unicode]] to fullUnicode.
  // 9. Set iterator.[[Done]] to false.
  TNode<Int32T> global_flag =
      Word32Shl(ReinterpretCast<Int32T>(global),
                Int32Constant(JSRegExpStringIterator::GlobalBit::kShift));
  TNode<Int32T> unicode_flag =
      Word32Shl(ReinterpretCast<Int32T>(full_unicode),
                Int32Constant(JSRegExpStringIterator::UnicodeBit::kShift));
  TNode<Int32T> iterator_flags = Word32Or(global_flag, unicode_flag);
  StoreObjectFieldNoWriteBarrier(iterator, JSRegExpStringIterator::kFlagsOffset,
                                 SmiFromInt32(iterator_flags));
  return CAST(iterator);
}
References v8::internal::CodeStubAssembler::Allocate(), CAST, v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::native_context, v8::internal::CodeStubAssembler::SmiFromInt32(), v8::internal::CodeStubAssembler::StoreMapNoWriteBarrier(), v8::internal::CodeStubAssembler::StoreObjectFieldNoWriteBarrier(), v8::internal::CodeStubAssembler::StoreObjectFieldRoot(), v8::internal::compiler::CodeAssembler::Word32Or(), and v8::internal::compiler::CodeAssembler::Word32Shl().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/builtins/builtins-regexp-gen.h
/mnt/V8SourceCode/src/builtins/builtins-regexp-gen.cc