v8::internal::JSSharedStruct Class Reference
#include <js-struct.h>
Static Public Member Functions
static DirectHandle< Map > CreateInstanceMap (Isolate *isolate, const base::Vector< const DirectHandle< Name >> field_names, const std::set< uint32_t > &element_names, MaybeDirectHandle< String > maybe_registry_key)
static MaybeHandle< String > GetRegistryKey (Isolate *isolate, Tagged< Map > instance_map)
static bool IsRegistryKeyDescriptor (Isolate *isolate, Tagged< Map > instance_map, InternalIndex i)
static MaybeDirectHandle< NumberDictionary > GetElementsTemplate (Isolate *isolate, Tagged< Map > instance_map)
static bool IsElementsTemplateDescriptor (Isolate *isolate, Tagged< Map > instance_map, InternalIndex i)
Detailed Description
Definition at line 47 of file js-struct.h.
Member Function Documentation
CreateInstanceMap()
DirectHandle< Map > v8::internal::JSSharedStruct::CreateInstanceMap (Isolate * isolate, const base::Vector< const DirectHandle< Name >> field_names, const std::set< uint32_t > & element_names, MaybeDirectHandle< String > maybe_registry_key) [static]
Definition at line 165 of file js-struct.cc.
                                                  {
  auto* factory = isolate->factory();
  int num_fields = 0;
  int num_elements = 0;
  int num_descriptors = static_cast<int>(field_names.size());
  // If there are elements, an template NumberDictionary is created and stored
  // as a data constant on a descriptor.
  if (!element_names.empty()) num_descriptors++;
  // If this is a registered map, the key is stored as a data constant on a
  // descriptor because the registry stores the maps weakly. Storing the key in
  // the map simplifies the weakness handling in the GC.
  if (!maybe_registry_key.is_null()) num_descriptors++;
  // Create the DescriptorArray if there are fields or elements.
  DirectHandle<DescriptorArray> descriptors;
  if (num_descriptors != 0) {
    descriptors = factory->NewDescriptorArray(num_descriptors, 0,
                                              AllocationType::kSharedOld);
    int special_slots = 0;
    // Store the registry key if the map is registered. This must be the first
    // slot if present. The registry depends on this for rehashing.
    DirectHandle<String> registry_key;
    if (maybe_registry_key.ToHandle(&registry_key)) {
      Descriptor d = Descriptor::DataConstant(
          factory->shared_struct_map_registry_key_symbol(), registry_key,
          ALL_ATTRIBUTES_MASK);
      DCHECK_EQ(0, special_slots);
      descriptors->Set(InternalIndex(special_slots++), &d);
    }
    // Elements in shared structs are only supported as a dictionary. Create the
    // template NumberDictionary if needed.
    if (!element_names.empty()) {
      DirectHandle<NumberDictionary> elements_template;
      num_elements = static_cast<int>(element_names.size());
      elements_template = NumberDictionary::New(isolate, num_elements,
                                                AllocationType::kSharedOld);
      for (uint32_t index : element_names) {
        PropertyDetails details(PropertyKind::kData, SEALED,
                                PropertyConstness::kMutable, 0);
        NumberDictionary::UncheckedAdd<Isolate, DirectHandle,
                                       AllocationType::kSharedOld>(
            isolate, elements_template, index,
            isolate->factory()->undefined_value(), details);
      }
      elements_template->SetInitialNumberOfElements(num_elements);
      DCHECK(HeapLayout::InAnySharedSpace(*elements_template));
      Descriptor d = Descriptor::DataConstant(
          factory->shared_struct_map_elements_template_symbol(),
          elements_template, ALL_ATTRIBUTES_MASK);
      descriptors->Set(InternalIndex(special_slots++), &d);
    }
    DCHECK_LE(special_slots, kSpecialSlots);
    for (DirectHandle<Name> field_name : field_names) {
      // Shared structs' fields need to be aligned, so make it all tagged.
      PropertyDetails details(
          PropertyKind::kData, SEALED, PropertyLocation::kField,
          PropertyConstness::kMutable, Representation::Tagged(), num_fields);
      descriptors->Set(InternalIndex(special_slots + num_fields), *field_name,
                       FieldType::Any(), details);
      num_fields++;
    }
    descriptors->Sort();
  }
  // Calculate the size for instances and create the map.
  int instance_size;
  int in_object_properties;
  JSFunction::CalculateInstanceSizeHelper(JS_SHARED_STRUCT_TYPE, false, 0,
                                          num_fields, &instance_size,
                                          &in_object_properties);
  DirectHandle<Map> instance_map = factory->NewContextlessMap(
      JS_SHARED_STRUCT_TYPE, instance_size, DICTIONARY_ELEMENTS,
      in_object_properties, AllocationType::kSharedMap);
  // Prepare the enum cache if necessary.
  if (num_descriptors == 0) {
    DCHECK_EQ(0, num_fields);
    // No properties at all.
    AlwaysSharedSpaceJSObject::PrepareMapNoEnumerableProperties(*instance_map);
  } else if (num_fields == 0) {
    // Have descriptors, but no enumerable fields.
    AlwaysSharedSpaceJSObject::PrepareMapNoEnumerableProperties(
        isolate, *instance_map, *descriptors);
  } else {
    // Have enumerable fields.
    AlwaysSharedSpaceJSObject::PrepareMapWithEnumerableProperties(
        isolate, instance_map, descriptors, num_fields);
  }
  // Structs have fixed layout ahead of time, so there's no slack.
  int out_of_object_properties = num_fields - in_object_properties;
  if (out_of_object_properties != 0) {
    instance_map->SetOutOfObjectUnusedPropertyFields(0);
  }
  return instance_map;
}
References v8::internal::ALL_ATTRIBUTES_MASK, v8::internal::FieldType::Any(), v8::internal::JSFunction::CalculateInstanceSizeHelper(), v8::internal::Descriptor::DataConstant(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LE, v8::internal::DICTIONARY_ELEMENTS, v8::internal::Isolate::factory(), v8::internal::HeapLayout::InAnySharedSpace(), v8::internal::index, v8::internal::MaybeDirectHandle< T >::is_null(), v8::internal::kData, v8::internal::kField, v8::internal::kMutable, v8::internal::kSharedMap, v8::internal::kSharedOld, v8::internal::anonymous_namespace{js-struct.cc}::kSpecialSlots, v8::internal::anonymous_namespace{intl-objects.cc}::New(), v8::internal::AlwaysSharedSpaceJSObject::PrepareMapNoEnumerableProperties(), v8::internal::AlwaysSharedSpaceJSObject::PrepareMapWithEnumerableProperties(), v8::internal::SEALED, v8::internal::Representation::Tagged(), and v8::internal::MaybeDirectHandle< T >::ToHandle().
Referenced by v8::internal::BUILTIN(), and v8::internal::SharedStructTypeRegistry::RegisterNoThrow().
GetElementsTemplate()
MaybeDirectHandle< NumberDictionary > v8::internal::JSSharedStruct::GetElementsTemplate (Isolate * isolate, Tagged< Map > instance_map) [static]
Definition at line 293 of file js-struct.cc.
                                                {
  return GetSpecialSlotValue<NumberDictionary>(
      isolate, instance_map,
      ReadOnlyRoots(isolate).shared_struct_map_elements_template_symbol());
}
Referenced by v8::internal::BUILTIN(), and v8::internal::SharedStructTypeRegistry::CheckIfEntryMatches().
GetRegistryKey()
MaybeHandle< String > v8::internal::JSSharedStruct::GetRegistryKey (Isolate * isolate, Tagged< Map > instance_map) [static]
Definition at line 276 of file js-struct.cc.
                                                                             {
  return GetSpecialSlotValue<String>(
      isolate, *instance_map,
      ReadOnlyRoots(isolate).shared_struct_map_registry_key_symbol());
}
Referenced by v8::internal::SharedStructTypeRegistry::CheckIfEntryMatches(), and v8::internal::SharedStructTypeRegistry::Data::KeyIsMatch().
IsElementsTemplateDescriptor()
bool v8::internal::JSSharedStruct::IsElementsTemplateDescriptor (Isolate * isolate, Tagged< Map > instance_map, InternalIndex i) [static]
Definition at line 301 of file js-struct.cc.
                                                                   {
  DCHECK(IsJSSharedStructMap(instance_map));
  return instance_map->instance_descriptors(isolate)->GetKey(i) ==
         ReadOnlyRoots(isolate).shared_struct_map_elements_template_symbol();
}
References v8::internal::DCHECK().
Referenced by v8::internal::SharedStructTypeRegistry::CheckIfEntryMatches().
IsRegistryKeyDescriptor()
bool v8::internal::JSSharedStruct::IsRegistryKeyDescriptor (Isolate * isolate, Tagged< Map > instance_map, InternalIndex i) [static]
Definition at line 284 of file js-struct.cc.
                                                              {
  DCHECK(IsJSSharedStructMap(instance_map));
  return instance_map->instance_descriptors(isolate)->GetKey(i) ==
         ReadOnlyRoots(isolate).shared_struct_map_registry_key_symbol();
}
References v8::internal::DCHECK().
Referenced by v8::internal::SharedStructTypeRegistry::CheckIfEntryMatches().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-struct.h
/mnt/V8SourceCode/src/objects/js-struct.cc