v8::internal::PropertyCell Class Reference
#include <property-cell.h>
Public Types
using BodyDescriptor = FixedBodyDescriptor< kNameOffset, kSize, kSize >
Public Member Functions
PropertyDetails property_details () const
PropertyDetails property_details (AcquireLoadTag tag) const
void UpdatePropertyDetailsExceptCellType (PropertyDetails details)
void Transition (PropertyDetails new_details, DirectHandle< Object > new_value)
void InvalidateProtector (Isolate *isolate)
void ClearAndInvalidate (Isolate *isolate)
Static Public Member Functions
static PropertyCellType InitialType (Isolate *isolate, Tagged< Object > value)
static PropertyCellType UpdatedType (Isolate *isolate, Tagged< PropertyCell > cell, Tagged< Object > value, PropertyDetails details)
static Handle< PropertyCell > PrepareForAndSetValue (Isolate *isolate, DirectHandle< GlobalDictionary > dictionary, InternalIndex entry, DirectHandle< Object > value, PropertyDetails details)
static Handle< PropertyCell > InvalidateAndReplaceEntry (Isolate *isolate, DirectHandle< GlobalDictionary > dictionary, InternalIndex entry, PropertyDetails new_details, DirectHandle< Object > new_value)
static bool CheckDataIsCompatible (PropertyDetails details, Tagged< Object > value)
Friends
class Factory
Detailed Description
Definition at line 22 of file property-cell.h.
Member Typedef Documentation
BodyDescriptor
using v8::internal::PropertyCell::BodyDescriptor = FixedBodyDescriptor<kNameOffset, kSize, kSize>
Definition at line 79 of file property-cell.h.
Member Function Documentation
CheckDataIsCompatible()
bool v8::internal::PropertyCell::CheckDataIsCompatible (PropertyDetails details, Tagged< Object > value) [static]
Definition at line 6560 of file objects.cc.
                                                               {
  DisallowGarbageCollection no_gc;
  PropertyCellType cell_type = details.cell_type();
  CHECK_NE(cell_type, PropertyCellType::kInTransition);
  if (IsPropertyCellHole(value)) {
    CHECK_EQ(cell_type, PropertyCellType::kConstant);
  } else {
    CHECK_EQ(IsAccessorInfo(value) || IsAccessorPair(value),
             details.kind() == PropertyKind::kAccessor);
    DCHECK_IMPLIES(cell_type == PropertyCellType::kUndefined,
                   IsUndefined(value));
  }
  return true;
}
References v8::internal::PropertyDetails::cell_type(), CHECK_EQ, CHECK_NE, DCHECK_IMPLIES, v8::internal::kAccessor, v8::internal::kConstant, v8::internal::PropertyDetails::kind(), v8::internal::kInTransition, v8::internal::kUndefined, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::value.
Referenced by v8::internal::compiler::PropertyCellData::Cache().
ClearAndInvalidate()
void v8::internal::PropertyCell::ClearAndInvalidate (Isolate * isolate)
Definition at line 6434 of file objects.cc.
                                                      {
  DCHECK(!IsPropertyCellHole(value(), isolate));
  PropertyDetails details = property_details();
  details = details.set_cell_type(PropertyCellType::kConstant);
  Transition(details, isolate->factory()->property_cell_hole_value());
  DependentCode::DeoptimizeDependencyGroups(
      isolate, *this, DependentCode::kPropertyCellChangedGroup);
}
References v8::internal::DCHECK(), v8::internal::DependentCode::DeoptimizeDependencyGroups(), v8::internal::Isolate::factory(), v8::internal::kConstant, v8::internal::DependentCode::kPropertyCellChangedGroup, v8::internal::PropertyDetails::set_cell_type(), and v8::internal::value.
InitialType()
PropertyCellType v8::internal::PropertyCell::InitialType (Isolate * isolate, Tagged< Object > value) [static]
Definition at line 6476 of file objects.cc.
                                                                 {
  return IsUndefined(value, isolate) ? PropertyCellType::kUndefined
                                     : PropertyCellType::kConstant;
}
References v8::internal::kConstant, v8::internal::kUndefined, and v8::internal::value.
Referenced by v8::internal::LookupIterator::PrepareTransitionToDataProperty().
InvalidateAndReplaceEntry()
Handle< PropertyCell > v8::internal::PropertyCell::InvalidateAndReplaceEntry (Isolate * isolate, DirectHandle< GlobalDictionary > dictionary, InternalIndex entry, PropertyDetails new_details, DirectHandle< Object > new_value) [static]
Definition at line 6444 of file objects.cc.
                                    {
  DirectHandle<PropertyCell> cell(dictionary->CellAt(entry), isolate);
  DirectHandle<Name> name(cell->name(), isolate);
  DCHECK(cell->property_details().IsConfigurable());
  DCHECK(!IsAnyHole(cell->value(), isolate));
  // Swap with a new property cell.
  Handle<PropertyCell> new_cell =
      isolate->factory()->NewPropertyCell(name, new_details, new_value);
  dictionary->ValueAtPut(entry, *new_cell);
  cell->ClearAndInvalidate(isolate);
  return new_cell;
}
References v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::IsAnyHole(), v8::internal::name, and v8::internal::Factory::NewPropertyCell().
Referenced by v8::internal::JSGlobalObject::InvalidatePropertyCell(), and PrepareForAndSetValue().
InvalidateProtector()
void v8::internal::PropertyCell::InvalidateProtector (Isolate * isolate)
Definition at line 6549 of file objects.cc.
                                                       {
  if (value() != Smi::FromInt(Protectors::kProtectorInvalid)) {
    DCHECK_EQ(value(), Smi::FromInt(Protectors::kProtectorValid));
    set_value(Smi::FromInt(Protectors::kProtectorInvalid), kReleaseStore,
              SKIP_WRITE_BARRIER);
    DependentCode::DeoptimizeDependencyGroups(
        isolate, *this, DependentCode::kPropertyCellChangedGroup);
  }
}
References DCHECK_EQ, v8::internal::DependentCode::DeoptimizeDependencyGroups(), v8::internal::Smi::FromInt(), v8::internal::DependentCode::kPropertyCellChangedGroup, v8::internal::Protectors::kProtectorInvalid, v8::internal::Protectors::kProtectorValid, v8::kReleaseStore, v8::internal::SKIP_WRITE_BARRIER, and v8::internal::value.
PrepareForAndSetValue()
Handle< PropertyCell > v8::internal::PropertyCell::PrepareForAndSetValue (Isolate * isolate, DirectHandle< GlobalDictionary > dictionary, InternalIndex entry, DirectHandle< Object > value, PropertyDetails details) [static]
Definition at line 6509 of file objects.cc.
                                                                              {
  DCHECK(!IsAnyHole(*value, isolate));
  Tagged<PropertyCell> raw_cell = dictionary->CellAt(entry);
  CHECK(!IsAnyHole(raw_cell->value(), isolate));
  const PropertyDetails original_details = raw_cell->property_details();
  // Data accesses could be cached in ics or optimized code.
  bool invalidate = original_details.kind() == PropertyKind::kData &&
                    details.kind() == PropertyKind::kAccessor;
  int index = original_details.dictionary_index();
  DCHECK_LT(0, index);
  details = details.set_index(index);
  PropertyCellType new_type =
      UpdatedType(isolate, raw_cell, *value, original_details);
  details = details.set_cell_type(new_type);
  Handle<PropertyCell> cell(raw_cell, isolate);
  if (invalidate) {
    cell = PropertyCell::InvalidateAndReplaceEntry(isolate, dictionary, entry,
                                                   details, value);
  } else {
    cell->Transition(details, value);
    // Deopt when transitioning from a constant type or when making a writable
    // property read-only. Making a read-only property writable again is not
    // interesting because Turbofan does not currently rely on read-only unless
    // the property is also configurable, in which case it will stay read-only
    // forever.
    if (original_details.cell_type() != new_type ||
        (!original_details.IsReadOnly() && details.IsReadOnly())) {
      DependentCode::DeoptimizeDependencyGroups(
          isolate, *cell, DependentCode::kPropertyCellChangedGroup);
    }
  }
  return cell;
}
References v8::internal::PropertyDetails::cell_type(), CHECK, v8::internal::DCHECK(), DCHECK_LT, v8::internal::DependentCode::DeoptimizeDependencyGroups(), v8::internal::PropertyDetails::dictionary_index(), v8::internal::index, InvalidateAndReplaceEntry(), v8::internal::IsAnyHole(), v8::internal::PropertyDetails::IsReadOnly(), v8::internal::kAccessor, v8::internal::kData, v8::internal::PropertyDetails::kind(), v8::internal::DependentCode::kPropertyCellChangedGroup, v8::internal::PropertyDetails::set_cell_type(), v8::internal::PropertyDetails::set_index(), and v8::internal::value.
Referenced by v8::internal::LookupIterator::PrepareForDataProperty(), v8::internal::LookupIterator::ReconfigureDataProperty(), and v8::internal::JSObject::SetNormalizedProperty().
property_details() [1/2]
PropertyDetails v8::internal::PropertyCell::property_details () const [inline]
property_details() [2/2]
PropertyDetails v8::internal::PropertyCell::property_details (AcquireLoadTag tag) const [inline]
Transition()
void v8::internal::PropertyCell::Transition (PropertyDetails new_details, DirectHandle< Object > new_value) [inline]
Definition at line 61 of file property-cell-inl.h.
                                                              {
  DCHECK(CanTransitionTo(new_details, *new_value));
  // This code must be in sync with its counterpart in
  // PropertyCellData::Serialize.
  PropertyDetails transition_marker = new_details;
  transition_marker.set_cell_type(PropertyCellType::kInTransition);
  set_property_details_raw(transition_marker.AsSmi(), kReleaseStore);
  set_value(*new_value, kReleaseStore);
  set_property_details_raw(new_details.AsSmi(), kReleaseStore);
}
References v8::internal::PropertyDetails::AsSmi(), v8::internal::DCHECK(), v8::internal::kInTransition, v8::kReleaseStore, and v8::internal::PropertyDetails::set_cell_type().
UpdatedType()
PropertyCellType v8::internal::PropertyCell::UpdatedType (Isolate * isolate, Tagged< PropertyCell > cell, Tagged< Object > value, PropertyDetails details) [static]
Definition at line 6483 of file objects.cc.
                                                                    {
  DisallowGarbageCollection no_gc;
  DCHECK(!IsAnyHole(value, isolate));
  DCHECK(!IsAnyHole(cell->value(), isolate));
  switch (details.cell_type()) {
    case PropertyCellType::kUndefined:
      return PropertyCellType::kConstant;
    case PropertyCellType::kConstant:
      if (value == cell->value()) return PropertyCellType::kConstant;
      [[fallthrough]];
    case PropertyCellType::kConstantType:
      if (RemainsConstantType(cell, value)) {
        return PropertyCellType::kConstantType;
      }
      [[fallthrough]];
    case PropertyCellType::kMutable:
      return PropertyCellType::kMutable;
    case PropertyCellType::kInTransition:
      UNREACHABLE();
  }
  UNREACHABLE();
}
References v8::internal::PropertyDetails::cell_type(), v8::internal::DCHECK(), v8::internal::IsAnyHole(), v8::internal::kConstant, v8::internal::kConstantType, v8::internal::kInTransition, v8::internal::kMutable, v8::internal::kUndefined, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::RemainsConstantType(), v8::internal::UNREACHABLE(), and v8::internal::value.
UpdatePropertyDetailsExceptCellType()
void v8::internal::PropertyCell::UpdatePropertyDetailsExceptCellType (PropertyDetails details) [inline]
Friends And Related Function Documentation
Factory
friend class Factory [friend]
Definition at line 84 of file property-cell.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/property-cell.h
/mnt/V8SourceCode/src/objects/objects.cc
/mnt/V8SourceCode/src/objects/property-cell-inl.h