v8::internal::JSTemporalPlainDate Class Reference
#include <js-temporal-objects.h>
Static Public Member Functions
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainDate > Constructor (Isolate *isolate, DirectHandle< JSFunction > target, DirectHandle< HeapObject > new_target, DirectHandle< Object > iso_year, DirectHandle< Object > iso_month, DirectHandle< Object > iso_day, DirectHandle< Object > calendar_like)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Smi > Compare (Isolate *isolate, DirectHandle< Object > one, DirectHandle< Object > two)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Oddball > Equals (Isolate *isolate, DirectHandle< JSTemporalPlainDate > plain_date, DirectHandle< Object > other)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainDateTime > ToPlainDateTime (Isolate *isolate, DirectHandle< JSTemporalPlainDate > plain_date, DirectHandle< Object > temporal_time)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainDate > With (Isolate *isolate, DirectHandle< JSTemporalPlainDate > plain_date, DirectHandle< Object > temporal_duration_like, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainDate > From (Isolate *isolate, DirectHandle< Object > item, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainDate > Add (Isolate *isolate, DirectHandle< JSTemporalPlainDate > plain_date, DirectHandle< Object > temporal_duration_like, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainDate > Subtract (Isolate *isolate, DirectHandle< JSTemporalPlainDate > plain_date, DirectHandle< Object > temporal_duration_like, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalDuration > Until (Isolate *isolate, DirectHandle< JSTemporalPlainDate > plain_date, DirectHandle< Object > other, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalDuration > Since (Isolate *isolate, DirectHandle< JSTemporalPlainDate > plain_date, DirectHandle< Object > other, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainYearMonth > ToPlainYearMonth (Isolate *isolate, DirectHandle< JSTemporalPlainDate > plain_date)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainMonthDay > ToPlainMonthDay (Isolate *isolate, DirectHandle< JSTemporalPlainDate > plain_date)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalZonedDateTime > ToZonedDateTime (Isolate *isolate, DirectHandle< JSTemporalPlainDate > plain_date, DirectHandle< Object > item)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainDate > Now (Isolate *isolate, DirectHandle< Object > calendar_like, DirectHandle< Object > temporal_time_zone_like)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSTemporalPlainDate > NowISO (Isolate *isolate, DirectHandle< Object > temporal_time_zone_like)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > ToString (Isolate *isolate, DirectHandle< JSTemporalPlainDate > plain_date, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > ToJSON (Isolate *isolate, DirectHandle< JSTemporalPlainDate > plain_date)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > ToLocaleString (Isolate *isolate, DirectHandle< JSTemporalPlainDate > plain_date, DirectHandle< Object > locales, DirectHandle< Object > options)
Detailed Description
Definition at line 246 of file js-temporal-objects.h.
Member Function Documentation
Add()
MaybeDirectHandle< JSTemporalPlainDate > v8::internal::JSTemporalPlainDate::Add (Isolate * isolate, DirectHandle< JSTemporalPlainDate > plain_date, DirectHandle< Object > temporal_duration_like, DirectHandle< Object > options) [static]
Definition at line 1857 of file js-temporal-objects.cc.
                                      {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
Compare()
MaybeDirectHandle< Smi > v8::internal::JSTemporalPlainDate::Compare (Isolate * isolate, DirectHandle< Object > one, DirectHandle< Object > two) [static]
Definition at line 1791 of file js-temporal-objects.cc.
                                  {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
Constructor()
MaybeDirectHandle< JSTemporalPlainDate > v8::internal::JSTemporalPlainDate::Constructor (Isolate * isolate, DirectHandle< JSFunction > target, DirectHandle< HeapObject > new_target, DirectHandle< Object > iso_year, DirectHandle< Object > iso_month, DirectHandle< Object > iso_day, DirectHandle< Object > calendar_like) [static]
Definition at line 1728 of file js-temporal-objects.cc.
                                        {
  // 1. If NewTarget is undefined, then
  if (IsUndefined(*new_target)) {
    // a. Throw a TypeError exception.
    THROW_NEW_ERROR(isolate,
                    NewTypeError(MessageTemplate::kMethodInvokedOnWrongType,
                                 isolate->factory()->NewStringFromAsciiChecked(
                                     "Temporal.PlainDate")));
  }
  // 2. Let y be ? ToIntegerWithTruncation(isoYear).
  double y = 0;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, y, temporal::ToIntegerWithTruncation(isolate, iso_year_obj),
      kNullMaybeHandle);
  // 3. Let m be ? ToIntegerWithTruncation(isoMonth).
  double m = 0;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, m, temporal::ToIntegerWithTruncation(isolate, iso_month_obj),
      kNullMaybeHandle);
  // 4. Let d be ? ToIntegerWithTruncation(isoDay).
  double d = 0;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, d, temporal::ToIntegerWithTruncation(isolate, iso_day_obj),
      kNullMaybeHandle);
  // 5. If calendar is undefined, set calendar to "iso8601".
  temporal_rs::AnyCalendarKind calendar = temporal_rs::AnyCalendarKind::Iso;
  if (!IsUndefined(*calendar_like)) {
    // 6. If calendar is not a String, throw a TypeError exception.
    if (!IsString(*calendar_like)) {
      THROW_NEW_ERROR(isolate, NEW_TEMPORAL_INVALID_ARG_TYPE_ERROR());
    }
    // 7. Set calendar to ?CanonicalizeCalendar(calendar).
    MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate, calendar,
        temporal::CanonicalizeCalendar(isolate, Cast<String>(calendar_like)),
        kNullMaybeHandle);
  }
  // 8. If IsValidISODate(y, m, d) is false, throw a RangeError exception.
  if (!temporal::IsValidIsoDate(y, m, d)) {
    THROW_NEW_ERROR(isolate, NEW_TEMPORAL_INVALID_ARG_RANGE_ERROR());
  }
  // Rest of the steps handled in Rust
  // These static_casts are fine to perform since IsValid* will have constrained
  // these values to range already.
  // https://github.com/boa-dev/temporal/issues/334 for moving this logic into
  // the Rust code.
  auto rust_object = temporal_rs::PlainDate::try_new(
      static_cast<int32_t>(y), static_cast<uint8_t>(m), static_cast<uint8_t>(d),
      calendar);
  return ConstructRustWrappingType<JSTemporalPlainDate>(
      isolate, target, new_target, std::move(rust_object));
}
References v8::internal::temporal::CanonicalizeCalendar(), v8::internal::Isolate::factory(), v8::internal::temporal::IsValidIsoDate(), v8::internal::kNullMaybeHandle, MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, NEW_TEMPORAL_INVALID_ARG_RANGE_ERROR, NEW_TEMPORAL_INVALID_ARG_TYPE_ERROR, v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), THROW_NEW_ERROR, v8::internal::temporal::ToIntegerWithTruncation(), and v8::internal::y.
Referenced by v8::internal::BUILTIN().
Equals()
MaybeDirectHandle< Oddball > v8::internal::JSTemporalPlainDate::Equals (Isolate * isolate, DirectHandle< JSTemporalPlainDate > plain_date, DirectHandle< Object > other) [static]
Definition at line 1798 of file js-temporal-objects.cc.
                                    {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
From()
MaybeDirectHandle< JSTemporalPlainDate > v8::internal::JSTemporalPlainDate::From (Isolate * isolate, DirectHandle< Object > item, DirectHandle< Object > options) [static]
Definition at line 1902 of file js-temporal-objects.cc.
                                      {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
Now()
MaybeDirectHandle< JSTemporalPlainDate > v8::internal::JSTemporalPlainDate::Now (Isolate * isolate, DirectHandle< Object > calendar_like, DirectHandle< Object > temporal_time_zone_like) [static]
Definition at line 1889 of file js-temporal-objects.cc.
                                                  {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
NowISO()
MaybeDirectHandle< JSTemporalPlainDate > v8::internal::JSTemporalPlainDate::NowISO (Isolate * isolate, DirectHandle< Object > temporal_time_zone_like) [static]
Definition at line 1896 of file js-temporal-objects.cc.
                                                                    {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
Since()
MaybeDirectHandle< JSTemporalDuration > v8::internal::JSTemporalPlainDate::Since (Isolate * isolate, DirectHandle< JSTemporalPlainDate > plain_date, DirectHandle< Object > other, DirectHandle< Object > options) [static]
Definition at line 1881 of file js-temporal-objects.cc.
                                                              {
  TEMPORAL_ENTER_FUNC();
  UNIMPLEMENTED();
}
References TEMPORAL_ENTER_FUNC, and v8::internal::UNIMPLEMENTED().
Subtract()
MaybeDirectHandle< JSTemporalPlainDate > v8::internal::JSTemporalPlainDate::Subtract (Isolate * isolate, DirectHandle< JSTemporalPlainDate > plain_date, DirectHandle< Object > temporal_duration_like, DirectHandle< Object > options) [static]
Definition at line 1865 of file js-temporal-objects.cc.
                                      {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
ToJSON()
MaybeDirectHandle< String > v8::internal::JSTemporalPlainDate::ToJSON (Isolate * isolate, DirectHandle< JSTemporalPlainDate > plain_date) [static]
Definition at line 1909 of file js-temporal-objects.cc.
                                                                       {
  return temporal::TemporalDateToString(isolate, temporal_date,
                                        temporal_rs::DisplayCalendar::Auto);
}
References v8::internal::temporal::TemporalDateToString().
ToLocaleString()
MaybeDirectHandle< String > v8::internal::JSTemporalPlainDate::ToLocaleString (Isolate * isolate, DirectHandle< JSTemporalPlainDate > plain_date, DirectHandle< Object > locales, DirectHandle< Object > options) [static]
Definition at line 1939 of file js-temporal-objects.cc.
                                                                {
  return temporal::TemporalDateToString(isolate, temporal_date,
                                        temporal_rs::DisplayCalendar::Auto);
}
References v8::internal::temporal::TemporalDateToString().
ToPlainDateTime()
MaybeDirectHandle< JSTemporalPlainDateTime > v8::internal::JSTemporalPlainDate::ToPlainDateTime (Isolate * isolate, DirectHandle< JSTemporalPlainDate > plain_date, DirectHandle< Object > temporal_time) [static]
Definition at line 1823 of file js-temporal-objects.cc.
                                            {
  const char method_name[] = "Temporal.PlainDate.toPlainDateTime";
  const temporal_rs::PlainTime* maybe_time = nullptr;
  DirectHandle<JSTemporalPlainTime> time;
  if (!IsUndefined(*temporal_time_obj)) {
    ASSIGN_RETURN_ON_EXCEPTION(
        isolate, time,
        temporal::ToTemporalTime(isolate, temporal_time_obj, std::nullopt,
                                 method_name));
    maybe_time = time->time()->raw();
  }
  return ConstructRustWrappingType<JSTemporalPlainDateTime>(
      isolate, CONSTRUCTOR(plain_date_time), CONSTRUCTOR(plain_date_time),
      temporal_date->date()->raw()->to_plain_date_time(maybe_time));
}
References ASSIGN_RETURN_ON_EXCEPTION, CONSTRUCTOR, v8::internal::time, and v8::internal::temporal::ToTemporalTime().
ToPlainMonthDay()
MaybeDirectHandle< JSTemporalPlainMonthDay > v8::internal::JSTemporalPlainDate::ToPlainMonthDay (Isolate * isolate, DirectHandle< JSTemporalPlainDate > plain_date) [static]
Definition at line 1815 of file js-temporal-objects.cc.
                                                                       {
  return ConstructRustWrappingType<JSTemporalPlainMonthDay>(
      isolate, CONSTRUCTOR(plain_year_month), CONSTRUCTOR(plain_year_month),
      temporal_date->date()->raw()->to_plain_month_day());
}
References CONSTRUCTOR.
ToPlainYearMonth()
MaybeDirectHandle< JSTemporalPlainYearMonth > v8::internal::JSTemporalPlainDate::ToPlainYearMonth (Isolate * isolate, DirectHandle< JSTemporalPlainDate > plain_date) [static]
Definition at line 1807 of file js-temporal-objects.cc.
                                                                       {
  return ConstructRustWrappingType<JSTemporalPlainYearMonth>(
      isolate, CONSTRUCTOR(plain_year_month), CONSTRUCTOR(plain_year_month),
      temporal_date->date()->raw()->to_plain_year_month());
}
References CONSTRUCTOR.
ToString()
MaybeDirectHandle< String > v8::internal::JSTemporalPlainDate::ToString (Isolate * isolate, DirectHandle< JSTemporalPlainDate > plain_date, DirectHandle< Object > options) [static]
Definition at line 1916 of file js-temporal-objects.cc.
                                      {
  const char method_name[] = "Temporal.PlainDate.prototype.toString";
  // 3. Let resolvedOptions be ?GetOptionsObject(options).
  DirectHandle<JSReceiver> options;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, options, GetOptionsObject(isolate, options_obj, method_name));
  // 4. Let showCalendar be ?GetTemporalShowCalendarNameOption(resolvedOptions).
  temporal_rs::DisplayCalendar show_calendar;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, show_calendar,
      temporal::GetTemporalShowCalendarNameOption(isolate, options,
                                                  method_name),
      DirectHandle<String>());
  // 5. Return TemporalDateToString(temporalDate, showCalendar).
  return temporal::TemporalDateToString(isolate, temporal_date, show_calendar);
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::GetOptionsObject(), v8::internal::temporal::GetTemporalShowCalendarNameOption(), MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, and v8::internal::temporal::TemporalDateToString().
ToZonedDateTime()
MaybeDirectHandle< JSTemporalZonedDateTime > v8::internal::JSTemporalPlainDate::ToZonedDateTime (Isolate * isolate, DirectHandle< JSTemporalPlainDate > plain_date, DirectHandle< Object > item) [static]
Definition at line 1850 of file js-temporal-objects.cc.
                                   {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
Until()
MaybeDirectHandle< JSTemporalDuration > v8::internal::JSTemporalPlainDate::Until (Isolate * isolate, DirectHandle< JSTemporalPlainDate > plain_date, DirectHandle< Object > other, DirectHandle< Object > options) [static]
Definition at line 1873 of file js-temporal-objects.cc.
                                                              {
  TEMPORAL_ENTER_FUNC();
  UNIMPLEMENTED();
}
References TEMPORAL_ENTER_FUNC, and v8::internal::UNIMPLEMENTED().
With()
MaybeDirectHandle< JSTemporalPlainDate > v8::internal::JSTemporalPlainDate::With (Isolate * isolate, DirectHandle< JSTemporalPlainDate > plain_date, DirectHandle< Object > temporal_duration_like, DirectHandle< Object > options) [static]
Definition at line 1842 of file js-temporal-objects.cc.
                                      {
  UNIMPLEMENTED();
}
References v8::internal::UNIMPLEMENTED().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-temporal-objects.h
/mnt/V8SourceCode/src/objects/js-temporal-objects.cc