v8::internal::compiler::MemoryLowering Class Reference
#include <memory-lowering.h>
Classes
class AllocationGroup
class AllocationState
Public Types
enum class AllocationFolding { kDoAllocationFolding
, kDontAllocationFolding
 }
using WriteBarrierAssertFailedCallback = std::function< void(Node *node, Node *object, const char *name, Zone *temp_zone)>
Public Member Functions
MemoryLowering (JSGraph *jsgraph, Zone *zone, JSGraphAssembler *graph_assembler, bool is_wasm, AllocationFolding allocation_folding=AllocationFolding::kDontAllocationFolding, WriteBarrierAssertFailedCallback callback=[](Node *, Node *, const char *, Zone *) { UNREACHABLE();}, const char *function_debug_name=nullptr)
const char * reducer_name () const override
Reduction Reduce (Node *node) override
Reduction ReduceAllocateRaw (Node *node, AllocationType allocation_type, AllocationState const **state)
Reduction ReduceLoadFromObject (Node *node)
Reduction ReduceLoadElement (Node *node)
Reduction ReduceLoadField (Node *node)
Reduction ReduceStoreToObject (Node *node, AllocationState const *state=nullptr)
Reduction ReduceStoreElement (Node *node, AllocationState const *state=nullptr)
Reduction ReduceStoreField (Node *node, AllocationState const *state=nullptr)
Reduction ReduceStore (Node *node, AllocationState const *state=nullptr)
Private Member Functions
Reduction ReduceAllocateRaw (Node *node)
WriteBarrierKind ComputeWriteBarrierKind (Node *node, Node *object, Node *value, AllocationState const *state, WriteBarrierKind)
Reduction ReduceLoadExternalPointerField (Node *node)
Reduction ReduceLoadBoundedSize (Node *node)
Reduction ReduceLoadMap (Node *node)
Node * ComputeIndex (ElementAccess const &access, Node *node)
void EnsureAllocateOperator ()
Node * GetWasmInstanceNode ()
Node * AlignToAllocationAlignment (Node *address)
TFGraph * graph () const
Isolate * isolate () const
Zone * zone () const
Zone * graph_zone () const
CommonOperatorBuilder * common () const
MachineOperatorBuilder * machine () const
JSGraphAssembler * gasm () const
DISALLOW_IMPLICIT_CONSTRUCTORS (MemoryLowering)
Private Attributes
SetOncePointer< const Operator > allocate_operator_
SetOncePointer< Node > wasm_instance_node_
Isolate * isolate_
Zone * zone_
TFGraph * graph_
CommonOperatorBuilder * common_
MachineOperatorBuilder * machine_
JSGraphAssembler * graph_assembler_
bool is_wasm_
AllocationFolding allocation_folding_
WriteBarrierAssertFailedCallback write_barrier_assert_failed_
const char * function_debug_name_
Additional Inherited Members
Detailed Description
Definition at line 27 of file memory-lowering.h.
Member Typedef Documentation
WriteBarrierAssertFailedCallback
using v8::internal::compiler::MemoryLowering::WriteBarrierAssertFailedCallback = std::function<void(Node* node, Node* object, const char* name, Zone* temp_zone)>
Definition at line 73 of file memory-lowering.h.
Member Enumeration Documentation
AllocationFolding
enum v8::internal::compiler::MemoryLowering::AllocationFolding [strong]
Enumerator
kDoAllocationFolding
kDontAllocationFolding
Definition at line 29 of file memory-lowering.h.
{ kDoAllocationFolding, kDontAllocationFolding };
Constructor & Destructor Documentation
MemoryLowering()
v8::internal::compiler::MemoryLowering::MemoryLowering (JSGraph * jsgraph, Zone * zone, JSGraphAssembler * graph_assembler, bool is_wasm, AllocationFolding allocation_folding = AllocationFolding::kDontAllocationFolding, WriteBarrierAssertFailedCallback callback = [](Node*, Node*, const char*, Zone*) { UNREACHABLE(); }, const char * function_debug_name = nullptr)
Definition at line 61 of file memory-lowering.cc.
    : isolate_(jsgraph->isolate()),
      zone_(zone),
      graph_(jsgraph->graph()),
      common_(jsgraph->common()),
      machine_(jsgraph->machine()),
      graph_assembler_(graph_assembler),
      is_wasm_(is_wasm),
      allocation_folding_(allocation_folding),
      write_barrier_assert_failed_(callback),
      function_debug_name_(function_debug_name) {}
Member Function Documentation
AlignToAllocationAlignment()
Node * v8::internal::compiler::MemoryLowering::AlignToAllocationAlignment (Node * address) [private]
Definition at line 136 of file memory-lowering.cc.
                                                            {
  if (!V8_COMPRESS_POINTERS_8GB_BOOL) return value;
  auto already_aligned = __ MakeLabel(MachineRepresentation::kWord64);
  Node* alignment_check = __ WordEqual(
      __ WordAnd(value, __ UintPtrConstant(kObjectAlignment8GbHeapMask)),
      __ UintPtrConstant(0));
  __ GotoIf(alignment_check, &already_aligned, value);
  {
    Node* aligned_value;
    if (kObjectAlignment8GbHeap == 2 * kTaggedSize) {
      aligned_value = __ IntPtrAdd(value, __ IntPtrConstant(kTaggedSize));
    } else {
      aligned_value = __ WordAnd(
          __ IntPtrAdd(value, __ IntPtrConstant(kObjectAlignment8GbHeapMask)),
          __ UintPtrConstant(~kObjectAlignment8GbHeapMask));
    }
    __ Goto(&already_aligned, aligned_value);
  }
  __ Bind(&already_aligned);
  return already_aligned.PhiAt(0);
}
References __, v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::IntPtrAdd(), v8::internal::compiler::IntPtrConstant(), v8::internal::kObjectAlignment8GbHeap, v8::internal::kObjectAlignment8GbHeapMask, v8::internal::kTaggedSize, v8::internal::kWord64, V8_COMPRESS_POINTERS_8GB_BOOL, and v8::internal::value.
Referenced by ReduceAllocateRaw().
common()
CommonOperatorBuilder* v8::internal::compiler::MemoryLowering::common () const [inline], [private]
Definition at line 126 of file memory-lowering.h.
{ return common_; }
References common_.
Referenced by EnsureAllocateOperator(), and ReduceAllocateRaw().
ComputeIndex()
Node * v8::internal::compiler::MemoryLowering::ComputeIndex (ElementAccess const & access, Node * node) [private]
Definition at line 663 of file memory-lowering.cc.
                                                                           {
  int const element_size_shift =
      ElementSizeLog2Of(access.machine_type.representation());
  if (element_size_shift) {
    index = __ WordShl(index, __ IntPtrConstant(element_size_shift));
  }
  int const fixed_offset = access.header_size - access.tag();
  if (fixed_offset) {
    index = __ IntAdd(index, __ IntPtrConstant(fixed_offset));
  }
  return index;
}
References __, v8::internal::ElementSizeLog2Of(), v8::internal::compiler::ElementAccess::header_size, v8::internal::index, v8::internal::compiler::IntPtrConstant(), v8::internal::compiler::ElementAccess::machine_type, v8::internal::MachineType::representation(), and v8::internal::compiler::ElementAccess::tag().
Referenced by ReduceLoadElement(), and ReduceStoreElement().
ComputeWriteBarrierKind()
WriteBarrierKind v8::internal::compiler::MemoryLowering::ComputeWriteBarrierKind (Node * node, Node * object, Node * value, AllocationState const * state, WriteBarrierKind write_barrier_kind) [private]
Definition at line 707 of file memory-lowering.cc.
                                         {
  if (state && state->IsYoungGenerationAllocation() &&
      state->group()->Contains(object)) {
    write_barrier_kind = kNoWriteBarrier;
  }
  if (!ValueNeedsWriteBarrier(value, isolate())) {
    write_barrier_kind = kNoWriteBarrier;
  }
  if (v8_flags.disable_write_barriers) {
    write_barrier_kind = kNoWriteBarrier;
  }
  if (write_barrier_kind == WriteBarrierKind::kAssertNoWriteBarrier) {
    write_barrier_assert_failed_(node, object, function_debug_name_, zone());
  }
  return write_barrier_kind;
}
References v8::internal::compiler::MemoryLowering::AllocationGroup::Contains(), function_debug_name_, v8::internal::compiler::MemoryLowering::AllocationState::group(), isolate(), v8::internal::compiler::MemoryLowering::AllocationState::IsYoungGenerationAllocation(), v8::internal::compiler::kAssertNoWriteBarrier, v8::internal::compiler::kNoWriteBarrier, v8::internal::v8_flags, v8::internal::value, v8::internal::compiler::anonymous_namespace{memory-lowering.cc}::ValueNeedsWriteBarrier(), write_barrier_assert_failed_, and zone().
Referenced by ReduceStore(), ReduceStoreElement(), ReduceStoreField(), and ReduceStoreToObject().
DISALLOW_IMPLICIT_CONSTRUCTORS()
v8::internal::compiler::MemoryLowering::DISALLOW_IMPLICIT_CONSTRUCTORS (MemoryLowering) [private]
EnsureAllocateOperator()
void v8::internal::compiler::MemoryLowering::EnsureAllocateOperator () [private]
Definition at line 108 of file memory-lowering.cc.
                                            {
  if (allocate_operator_.is_set()) return;
  auto descriptor = AllocateDescriptor{};
  StubCallMode mode = isolate_ != nullptr ? StubCallMode::kCallCodeObject
                                          : StubCallMode::kCallBuiltinPointer;
  auto call_descriptor = Linkage::GetStubCallDescriptor(
      graph_zone(), descriptor, descriptor.GetStackParameterCount(),
      CallDescriptor::kCanUseRoots, Operator::kNoThrow, mode);
  allocate_operator_.set(common()->Call(call_descriptor));
}
References allocate_operator_, common(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), graph_zone(), isolate_, v8::internal::kCallBuiltinPointer, v8::internal::kCallCodeObject, v8::internal::compiler::CallDescriptor::kCanUseRoots, v8::internal::compiler::Operator::kNoThrow, and mode().
Referenced by ReduceAllocateRaw().
gasm()
JSGraphAssembler* v8::internal::compiler::MemoryLowering::gasm () const [inline], [private]
Definition at line 128 of file memory-lowering.h.
{ return graph_assembler_; }
References graph_assembler_.
Referenced by ReduceAllocateRaw().
GetWasmInstanceNode()
Node* v8::internal::compiler::MemoryLowering::GetWasmInstanceNode () [private]
Referenced by ReduceAllocateRaw().
graph()
TFGraph* v8::internal::compiler::MemoryLowering::graph () const [inline], [private]
Definition at line 122 of file memory-lowering.h.
{ return graph_; }
References graph_.
Referenced by graph_zone(), ReduceAllocateRaw(), ReduceLoadBoundedSize(), ReduceLoadExternalPointerField(), and ReduceLoadMap().
graph_zone()
Zone * v8::internal::compiler::MemoryLowering::graph_zone () const [inline], [private]
Definition at line 77 of file memory-lowering.cc.
{ return graph()->zone(); }
References graph(), and v8::internal::compiler::TFGraph::zone().
Referenced by EnsureAllocateOperator(), ReduceLoadField(), and ReduceStoreField().
isolate()
Isolate* v8::internal::compiler::MemoryLowering::isolate () const [inline], [private]
Definition at line 123 of file memory-lowering.h.
{ return isolate_; }
References isolate_.
Referenced by ComputeWriteBarrierKind(), ReduceAllocateRaw(), and ReduceLoadExternalPointerField().
machine()
MachineOperatorBuilder* v8::internal::compiler::MemoryLowering::machine () const [inline], [private]
Definition at line 127 of file memory-lowering.h.
{ return machine_; }
References machine_.
Referenced by ReduceAllocateRaw(), ReduceLoadBoundedSize(), ReduceLoadElement(), ReduceLoadExternalPointerField(), ReduceLoadField(), ReduceLoadFromObject(), ReduceLoadMap(), ReduceStore(), ReduceStoreElement(), ReduceStoreField(), and ReduceStoreToObject().
Reduce()
Reduction v8::internal::compiler::MemoryLowering::Reduce (Node * node) [override], [virtual]
Implements v8::internal::compiler::Reducer.
Definition at line 79 of file memory-lowering.cc.
                                           {
  switch (node->opcode()) {
    case IrOpcode::kAllocate:
      // Allocate nodes were purged from the graph in effect-control
      // linearization.
      UNREACHABLE();
    case IrOpcode::kAllocateRaw:
      return ReduceAllocateRaw(node);
    case IrOpcode::kLoadFromObject:
    case IrOpcode::kLoadImmutableFromObject:
      return ReduceLoadFromObject(node);
    case IrOpcode::kLoadElement:
      return ReduceLoadElement(node);
    case IrOpcode::kLoadField:
      return ReduceLoadField(node);
    case IrOpcode::kStoreToObject:
    case IrOpcode::kInitializeImmutableInObject:
      return ReduceStoreToObject(node);
    case IrOpcode::kStoreElement:
      return ReduceStoreElement(node);
    case IrOpcode::kStoreField:
      return ReduceStoreField(node);
    case IrOpcode::kStore:
      return ReduceStore(node);
    default:
      return NoChange();
  }
}
References v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::Node::opcode(), ReduceAllocateRaw(), ReduceLoadElement(), ReduceLoadField(), ReduceLoadFromObject(), ReduceStore(), ReduceStoreElement(), ReduceStoreField(), ReduceStoreToObject(), and v8::internal::UNREACHABLE().
ReduceAllocateRaw() [1/2]
Reduction v8::internal::compiler::MemoryLowering::ReduceAllocateRaw (Node * node) [private]
Definition at line 701 of file memory-lowering.cc.
                                                      {
  DCHECK_EQ(IrOpcode::kAllocateRaw, node->opcode());
  const AllocateParameters& allocation = AllocateParametersOf(node->op());
  return ReduceAllocateRaw(node, allocation.allocation_type(), nullptr);
}
References v8::internal::compiler::AllocateParametersOf(), v8::internal::compiler::AllocateParameters::allocation_type(), DCHECK_EQ, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), and ReduceAllocateRaw().
ReduceAllocateRaw() [2/2]
Reduction v8::internal::compiler::MemoryLowering::ReduceAllocateRaw (Node * node, AllocationType allocation_type, AllocationState const ** state)
Definition at line 162 of file memory-lowering.cc.
                                                                               {
  DCHECK_EQ(IrOpcode::kAllocateRaw, node->opcode());
  DCHECK_IMPLIES(allocation_folding_ == AllocationFolding::kDoAllocationFolding,
                 state_ptr != nullptr);
  if (v8_flags.single_generation && allocation_type == AllocationType::kYoung) {
    allocation_type = AllocationType::kOld;
  }
  // InstructionStream objects may have a maximum size smaller than
  // kMaxHeapObjectSize due to guard pages. If we need to support allocating
  // code here we would need to call
  // MemoryChunkLayout::MaxRegularCodeObjectSize() at runtime.
  DCHECK_NE(allocation_type, AllocationType::kCode);
  Node* value;
  Node* size = node->InputAt(0);
  Node* effect = node->InputAt(1);
  Node* control = node->InputAt(2);
  gasm()->InitializeEffectControl(effect, control);
  Node* allocate_builtin;
  if (!is_wasm_) {
    if (allocation_type == AllocationType::kYoung) {
      allocate_builtin = __ AllocateInYoungGenerationStubConstant();
    } else {
      allocate_builtin = __ AllocateInOldGenerationStubConstant();
    }
  } else {
#if V8_ENABLE_WEBASSEMBLY
    // This lowering is used by Wasm, where we compile isolate-independent
    // code. Builtin calls simply encode the target builtin ID, which will
    // be patched to the builtin's address later.
    if (isolate_ == nullptr) {
      Builtin builtin;
      if (allocation_type == AllocationType::kYoung) {
        builtin = Builtin::kWasmAllocateInYoungGeneration;
      } else {
        builtin = Builtin::kWasmAllocateInOldGeneration;
      }
      static_assert(std::is_same_v<Smi, BuiltinPtr>, "BuiltinPtr must be Smi");
      allocate_builtin =
          graph()->NewNode(common()->NumberConstant(static_cast<int>(builtin)));
    } else {
      if (allocation_type == AllocationType::kYoung) {
        allocate_builtin = __ WasmAllocateInYoungGenerationStubConstant();
      } else {
        allocate_builtin = __ WasmAllocateInOldGenerationStubConstant();
      }
    }
#else
    UNREACHABLE();
#endif
  }
  // Determine the top/limit addresses.
  Node* top_address;
  Node* limit_address;
  if (isolate_ != nullptr) {
    top_address = __ ExternalConstant(
        allocation_type == AllocationType::kYoung
            ? ExternalReference::new_space_allocation_top_address(isolate())
            : ExternalReference::old_space_allocation_top_address(isolate()));
    limit_address = __ ExternalConstant(
        allocation_type == AllocationType::kYoung
            ? ExternalReference::new_space_allocation_limit_address(isolate())
            : ExternalReference::old_space_allocation_limit_address(isolate()));
  } else {
    // Wasm mode: producing isolate-independent code, loading the isolate
    // address at runtime.
#if V8_ENABLE_WEBASSEMBLY
    Node* instance_node = GetWasmInstanceNode();
    int top_address_offset =
        allocation_type == AllocationType::kYoung
            ? WasmTrustedInstanceData::kNewAllocationTopAddressOffset
            : WasmTrustedInstanceData::kOldAllocationTopAddressOffset;
    int limit_address_offset =
        allocation_type == AllocationType::kYoung
            ? WasmTrustedInstanceData::kNewAllocationLimitAddressOffset
            : WasmTrustedInstanceData::kOldAllocationLimitAddressOffset;
    top_address =
        __ Load(MachineType::Pointer(), instance_node,
                __ IntPtrConstant(top_address_offset - kHeapObjectTag));
    limit_address =
        __ Load(MachineType::Pointer(), instance_node,
                __ IntPtrConstant(limit_address_offset - kHeapObjectTag));
#else
    UNREACHABLE();
#endif // V8_ENABLE_WEBASSEMBLY
  }
  // Check if we can fold this allocation into a previous allocation represented
  // by the incoming {state}.
  IntPtrMatcher m(size);
  if (m.IsInRange(0, kMaxRegularHeapObjectSize) && v8_flags.inline_new &&
      allocation_folding_ == AllocationFolding::kDoAllocationFolding) {
    intptr_t const object_size =
        ALIGN_TO_ALLOCATION_ALIGNMENT(m.ResolvedValue());
    AllocationState const* state = *state_ptr;
    if (state->size() <= kMaxRegularHeapObjectSize - object_size &&
        state->group()->allocation() == allocation_type) {
      // We can fold this Allocate {node} into the allocation {group}
      // represented by the given {state}. Compute the upper bound for
      // the new {state}.
      intptr_t const state_size = state->size() + object_size;
      // Update the reservation check to the actual maximum upper bound.
      AllocationGroup* const group = state->group();
      if (machine()->Is64()) {
        if (OpParameter<int64_t>(group->size()->op()) < state_size) {
          NodeProperties::ChangeOp(group->size(),
                                   common()->Int64Constant(state_size));
        }
      } else {
        if (OpParameter<int32_t>(group->size()->op()) < state_size) {
          NodeProperties::ChangeOp(
              group->size(),
              common()->Int32Constant(static_cast<int32_t>(state_size)));
        }
      }
      // Update the allocation top with the new object allocation.
      // TODO(bmeurer): Defer writing back top as much as possible.
      DCHECK_IMPLIES(V8_COMPRESS_POINTERS_8GB_BOOL,
                     IsAligned(object_size, kObjectAlignment8GbHeap));
      Node* top = __ IntAdd(state->top(), __ IntPtrConstant(object_size));
      __ Store(StoreRepresentation(MachineType::PointerRepresentation(),
                                   kNoWriteBarrier),
               top_address, __ IntPtrConstant(0), top);
      // Compute the effective inner allocated address.
      value = __ BitcastWordToTagged(
          __ IntAdd(state->top(), __ IntPtrConstant(kHeapObjectTag)));
      effect = gasm()->effect();
      control = gasm()->control();
      // Extend the allocation {group}.
      group->Add(value);
      *state_ptr =
          AllocationState::Open(group, state_size, top, effect, zone());
    } else {
      auto call_runtime = __ MakeDeferredLabel();
      auto done = __ MakeLabel(MachineType::PointerRepresentation());
      // Setup a mutable reservation size node; will be patched as we fold
      // additional allocations into this new group.
      Node* reservation_size = __ UniqueIntPtrConstant(object_size);
      // Load allocation top and limit.
      Node* top =
          __ Load(MachineType::Pointer(), top_address, __ IntPtrConstant(0));
      Node* limit =
          __ Load(MachineType::Pointer(), limit_address, __ IntPtrConstant(0));
      // Check if we need to collect garbage before we can start bump pointer
      // allocation (always done for folded allocations).
      Node* check = __ UintLessThan(__ IntAdd(top, reservation_size), limit);
      __ GotoIfNot(check, &call_runtime);
      __ Goto(&done, top);
      __ Bind(&call_runtime);
      {
        EnsureAllocateOperator();
        Node* vfalse = __ BitcastTaggedToWord(__ Call(
            allocate_operator_.get(), allocate_builtin, reservation_size));
        vfalse = __ IntSub(vfalse, __ IntPtrConstant(kHeapObjectTag));
        __ Goto(&done, vfalse);
      }
      __ Bind(&done);
      // Compute the new top and write it back.
      top = __ IntAdd(done.PhiAt(0), __ IntPtrConstant(object_size));
      __ Store(StoreRepresentation(MachineType::PointerRepresentation(),
                                   kNoWriteBarrier),
               top_address, __ IntPtrConstant(0), top);
      // Compute the initial object address.
      value = __ BitcastWordToTagged(
          __ IntAdd(done.PhiAt(0), __ IntPtrConstant(kHeapObjectTag)));
      effect = gasm()->effect();
      control = gasm()->control();
      // Start a new allocation group.
      AllocationGroup* group = zone()->New<AllocationGroup>(
          value, allocation_type, reservation_size, zone());
      *state_ptr =
          AllocationState::Open(group, object_size, top, effect, zone());
    }
  } else {
    auto call_runtime = __ MakeDeferredLabel();
    auto done = __ MakeLabel(MachineRepresentation::kTaggedPointer);
    // Load allocation top and limit.
    Node* top =
        __ Load(MachineType::Pointer(), top_address, __ IntPtrConstant(0));
    Node* limit =
        __ Load(MachineType::Pointer(), limit_address, __ IntPtrConstant(0));
    // Compute the new top.
    Node* new_top = __ IntAdd(top, AlignToAllocationAlignment(size));
    // Check if we can do bump pointer allocation here.
    Node* check = __ UintLessThan(new_top, limit);
    __ GotoIfNot(check, &call_runtime);
    __ GotoIfNot(
        __ UintLessThan(size, __ IntPtrConstant(kMaxRegularHeapObjectSize)),
        &call_runtime);
    __ Store(StoreRepresentation(MachineType::PointerRepresentation(),
                                 kNoWriteBarrier),
             top_address, __ IntPtrConstant(0), new_top);
    __ Goto(&done, __ BitcastWordToTagged(
                       __ IntAdd(top, __ IntPtrConstant(kHeapObjectTag))));
    __ Bind(&call_runtime);
    EnsureAllocateOperator();
    __ Goto(&done, __ Call(allocate_operator_.get(), allocate_builtin, size));
    __ Bind(&done);
    value = done.PhiAt(0);
    effect = gasm()->effect();
    control = gasm()->control();
    if (state_ptr) {
      // Create an unfoldable allocation group.
      AllocationGroup* group =
          zone()->New<AllocationGroup>(value, allocation_type, zone());
      *state_ptr = AllocationState::Closed(group, effect, zone());
    }
  }
  return Replace(value);
}
References __, v8::internal::compiler::MemoryLowering::AllocationGroup::Add(), ALIGN_TO_ALLOCATION_ALIGNMENT, AlignToAllocationAlignment(), allocate_operator_, v8::internal::compiler::MemoryLowering::AllocationGroup::allocation(), allocation_folding_, v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::MemoryLowering::AllocationState::Closed(), common(), v8::internal::compiler::GraphAssembler::control(), DCHECK_EQ, DCHECK_IMPLIES, DCHECK_NE, v8::internal::compiler::GraphAssembler::effect(), EnsureAllocateOperator(), gasm(), GetWasmInstanceNode(), graph(), v8::internal::compiler::MemoryLowering::AllocationState::group(), v8::internal::compiler::GraphAssembler::InitializeEffectControl(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::IntPtrConstant(), v8::internal::Is64(), is_wasm_, IsAligned(), v8::internal::compiler::IntMatcher< T, kOpcode >::IsInRange(), isolate(), isolate_, v8::internal::kCode, kDoAllocationFolding, v8::internal::kHeapObjectTag, v8::internal::kMaxRegularHeapObjectSize, v8::internal::compiler::kNoWriteBarrier, v8::internal::kObjectAlignment8GbHeap, v8::internal::kOld, v8::internal::kTaggedPointer, v8::internal::kYoung, v8::Load(), machine(), v8::internal::Zone::New(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::NumberConstant(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::MemoryLowering::AllocationState::Open(), v8::internal::MachineType::Pointer(), v8::internal::MachineType::PointerRepresentation(), v8::internal::compiler::Reducer::Replace(), v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue(), v8::internal::compiler::MemoryLowering::AllocationGroup::size(), v8::internal::compiler::MemoryLowering::AllocationState::size(), size(), v8::internal::wasm::liftoff::Store(), v8::internal::compiler::MemoryLowering::AllocationState::top(), v8::internal::UNREACHABLE(), V8_COMPRESS_POINTERS_8GB_BOOL, v8::internal::v8_flags, v8::internal::value, and zone().
Referenced by Reduce(), ReduceAllocateRaw(), and v8::internal::compiler::MemoryOptimizer::VisitAllocateRaw().
ReduceLoadBoundedSize()
Reduction v8::internal::compiler::MemoryLowering::ReduceLoadBoundedSize (Node * node) [private]
Definition at line 498 of file memory-lowering.cc.
                                                          {
#ifdef V8_ENABLE_SANDBOX
  const Operator* load_op =
      !machine()->UnalignedLoadSupported(MachineRepresentation::kWord64)
          ? machine()->UnalignedLoad(MachineType::Uint64())
          : machine()->Load(MachineType::Uint64());
  NodeProperties::ChangeOp(node, load_op);
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  __ InitializeEffectControl(effect, control);
  Node* raw_value = __ AddNode(graph()->CloneNode(node));
  Node* shift_amount = __ IntPtrConstant(kBoundedSizeShift);
  Node* decoded_size = __ Word64Shr(raw_value, shift_amount);
  return Replace(decoded_size);
#else
  UNREACHABLE();
#endif
}
References __, v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), graph(), v8::internal::compiler::IntPtrConstant(), v8::internal::kWord64, v8::internal::compiler::MachineOperatorBuilder::Load(), machine(), v8::internal::compiler::Reducer::Replace(), v8::internal::MachineType::Uint64(), v8::internal::compiler::MachineOperatorBuilder::UnalignedLoad(), v8::internal::compiler::MachineOperatorBuilder::UnalignedLoadSupported(), and v8::internal::UNREACHABLE().
Referenced by ReduceLoadField().
ReduceLoadElement()
Reduction v8::internal::compiler::MemoryLowering::ReduceLoadElement (Node * node)
Definition at line 419 of file memory-lowering.cc.
                                                      {
  DCHECK_EQ(IrOpcode::kLoadElement, node->opcode());
  ElementAccess const& access = ElementAccessOf(node->op());
  Node* index = node->InputAt(1);
  node->ReplaceInput(1, ComputeIndex(access, index));
  MachineType type = access.machine_type;
  DCHECK(!type.IsMapWord());
  NodeProperties::ChangeOp(node, machine()->Load(type));
  return Changed(node);
}
References v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), ComputeIndex(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::ElementAccessOf(), v8::internal::index, v8::internal::compiler::Node::InputAt(), v8::Load(), machine(), v8::internal::compiler::ElementAccess::machine_type, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::Node::ReplaceInput(), and v8::internal::tracing::type.
Referenced by Reduce(), and v8::internal::compiler::MemoryOptimizer::VisitLoadElement().
ReduceLoadExternalPointerField()
Reduction v8::internal::compiler::MemoryLowering::ReduceLoadExternalPointerField (Node * node) [private]
Definition at line 430 of file memory-lowering.cc.
                                                                   {
  DCHECK_EQ(node->opcode(), IrOpcode::kLoadField);
  FieldAccess const& access = FieldAccessOf(node->op());
#ifdef V8_ENABLE_SANDBOX
  ExternalPointerTag tag = access.external_pointer_tag;
  DCHECK_NE(tag, kExternalPointerNullTag);
  // Fields for sandboxed external pointer contain a 32-bit handle, not a
  // 64-bit raw pointer.
  NodeProperties::ChangeOp(node, machine()->Load(MachineType::Uint32()));
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  __ InitializeEffectControl(effect, control);
  // Clone the load node and put it here.
  // TODO(turbofan): consider adding GraphAssembler::Clone() suitable for
  // cloning nodes from arbitrary locations in effect/control chains.
  static_assert(kExternalPointerIndexShift > kSystemPointerSizeLog2);
  Node* handle = __ AddNode(graph()->CloneNode(node));
  Node* shift_amount =
      __ Int32Constant(kExternalPointerIndexShift - kSystemPointerSizeLog2);
  Node* offset = __ Word32Shr(handle, shift_amount);
  // Uncomment this to generate a breakpoint for debugging purposes.
  // __ DebugBreak();
  // Decode loaded external pointer.
  //
  // Here we access the external pointer table through an ExternalReference.
  // Alternatively, we could also hardcode the address of the table since it
  // is never reallocated. However, in that case we must be able to guarantee
  // that the generated code is never executed under a different Isolate, as
  // that would allow access to external objects from different Isolates. It
  // also would break if the code is serialized/deserialized at some point.
  Node* table_address =
      IsSharedExternalPointerType(tag)
          ? __
            Load(MachineType::Pointer(),
                 __ ExternalConstant(
                     ExternalReference::
                         shared_external_pointer_table_address_address(
                             isolate())),
                 __ IntPtrConstant(0))
          : __ ExternalConstant(
                ExternalReference::external_pointer_table_address(isolate()));
  Node* table = __ Load(MachineType::Pointer(), table_address,
                        Internals::kExternalPointerTableBasePointerOffset);
  Node* pointer =
      __ Load(MachineType::Pointer(), table, __ ChangeUint32ToUint64(offset));
  Node* actual_tag =
      __ WordAnd(pointer, __ IntPtrConstant(kExternalPointerTagMask));
  actual_tag = __ TruncateInt64ToInt32(
      __ WordShr(actual_tag, __ IntPtrConstant(kExternalPointerTagShift)));
  Node* expected_tag = __ Int32Constant(tag);
  pointer =
      __ Word64And(pointer, __ IntPtrConstant(kExternalPointerPayloadMask));
  auto done = __ MakeLabel(MachineRepresentation::kWord64);
  __ GotoIf(__ WordEqual(actual_tag, expected_tag), &done, pointer);
  __ Goto(&done, __ IntPtrConstant(0));
  __ Bind(&done);
  return Replace(done.PhiAt(0));
#else
  NodeProperties::ChangeOp(node, machine()->Load(access.machine_type));
  return Changed(node);
#endif // V8_ENABLE_SANDBOX
}
References __, v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), DCHECK_EQ, DCHECK_NE, v8::internal::compiler::FieldAccess::external_pointer_tag, v8::internal::compiler::FieldAccessOf(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), graph(), v8::internal::handle(), v8::internal::compiler::IntPtrConstant(), isolate(), v8::internal::IsSharedExternalPointerType(), v8::internal::kExternalPointerNullTag, v8::internal::kExternalPointerPayloadMask, v8::internal::Internals::kExternalPointerTableBasePointerOffset, v8::internal::kExternalPointerTagMask, v8::internal::kExternalPointerTagShift, v8::internal::kSystemPointerSizeLog2, v8::internal::kWord64, v8::Load(), machine(), v8::internal::compiler::FieldAccess::machine_type, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::MachineType::Pointer(), v8::internal::compiler::Reducer::Replace(), and v8::internal::MachineType::Uint32().
Referenced by ReduceLoadField().
ReduceLoadField()
Reduction v8::internal::compiler::MemoryLowering::ReduceLoadField (Node * node)
Definition at line 535 of file memory-lowering.cc.
                                                    {
  DCHECK_EQ(IrOpcode::kLoadField, node->opcode());
  FieldAccess const& access = FieldAccessOf(node->op());
  Node* offset = __ IntPtrConstant(access.offset - access.tag());
  node->InsertInput(graph_zone(), 1, offset);
  MachineType type = access.machine_type;
  if (type.IsMapWord()) {
    DCHECK(!access.type.Is(Type::ExternalPointer()));
    return ReduceLoadMap(node);
  }
  if (access.type.Is(Type::ExternalPointer())) {
    return ReduceLoadExternalPointerField(node);
  }
  if (access.is_bounded_size_access) {
    return ReduceLoadBoundedSize(node);
  }
  NodeProperties::ChangeOp(node, machine()->Load(type));
  return Changed(node);
}
References __, v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::FieldAccessOf(), graph_zone(), v8::internal::compiler::Node::InsertInput(), v8::internal::compiler::IntPtrConstant(), v8::internal::compiler::Type::Is(), v8::internal::compiler::FieldAccess::is_bounded_size_access, v8::Load(), machine(), v8::internal::compiler::FieldAccess::machine_type, v8::internal::compiler::FieldAccess::offset, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), ReduceLoadBoundedSize(), ReduceLoadExternalPointerField(), ReduceLoadMap(), v8::internal::compiler::FieldAccess::tag(), v8::internal::compiler::FieldAccess::type, and v8::internal::tracing::type.
Referenced by Reduce(), and v8::internal::compiler::MemoryOptimizer::VisitLoadField().
ReduceLoadFromObject()
Reduction v8::internal::compiler::MemoryLowering::ReduceLoadFromObject (Node * node)
Definition at line 397 of file memory-lowering.cc.
                                                         {
  DCHECK(node->opcode() == IrOpcode::kLoadFromObject ||
         node->opcode() == IrOpcode::kLoadImmutableFromObject);
  ObjectAccess const& access = ObjectAccessOf(node->op());
  MachineType machine_type = access.machine_type;
  if (machine_type.IsMapWord()) {
    CHECK_EQ(machine_type.semantic(), MachineSemantic::kAny);
    return ReduceLoadMap(node);
  }
  MachineRepresentation rep = machine_type.representation();
  const Operator* load_op =
      ElementSizeInBytes(rep) > kTaggedSize &&
              !machine()->UnalignedLoadSupported(machine_type.representation())
          ? machine()->UnalignedLoad(machine_type)
          : machine()->Load(machine_type);
  NodeProperties::ChangeOp(node, load_op);
  return Changed(node);
}
References v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), CHECK_EQ, v8::internal::DCHECK(), v8::internal::ElementSizeInBytes(), v8::internal::MachineType::IsMapWord(), v8::internal::kAny, v8::internal::kTaggedSize, v8::internal::compiler::MachineOperatorBuilder::Load(), machine(), v8::internal::compiler::ObjectAccess::machine_type, v8::internal::wasm::machine_type(), v8::internal::compiler::ObjectAccessOf(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), ReduceLoadMap(), v8::internal::MachineType::representation(), v8::internal::MachineType::semantic(), v8::internal::compiler::MachineOperatorBuilder::UnalignedLoad(), and v8::internal::compiler::MachineOperatorBuilder::UnalignedLoadSupported().
Referenced by Reduce(), and v8::internal::compiler::MemoryOptimizer::VisitLoadFromObject().
ReduceLoadMap()
Reduction v8::internal::compiler::MemoryLowering::ReduceLoadMap (Node * node) [private]
Definition at line 519 of file memory-lowering.cc.
                                                  {
#ifdef V8_MAP_PACKING
  NodeProperties::ChangeOp(node, machine()->Load(MachineType::AnyTagged()));
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  __ InitializeEffectControl(effect, control);
  node = __ AddNode(graph()->CloneNode(node));
  return Replace(__ UnpackMapWord(node));
#else
  NodeProperties::ChangeOp(node, machine()->Load(MachineType::TaggedPointer()));
  return Changed(node);
#endif
}
References __, v8::internal::MachineType::AnyTagged(), v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), graph(), v8::Load(), machine(), v8::internal::compiler::Reducer::Replace(), and v8::internal::MachineType::TaggedPointer().
Referenced by ReduceLoadField(), and ReduceLoadFromObject().
reducer_name()
const char* v8::internal::compiler::MemoryLowering::reducer_name () const [inline], [override], [virtual]
Implements v8::internal::compiler::Reducer.
Definition at line 85 of file memory-lowering.h.
{ return "MemoryReducer"; }
ReduceStore()
Reduction v8::internal::compiler::MemoryLowering::ReduceStore (Node * node, AllocationState const * state = nullptr)
Definition at line 646 of file memory-lowering.cc.
                                                                    {
  DCHECK_EQ(IrOpcode::kStore, node->opcode());
  StoreRepresentation representation = StoreRepresentationOf(node->op());
  Node* object = node->InputAt(0);
  Node* value = node->InputAt(2);
  WriteBarrierKind write_barrier_kind = ComputeWriteBarrierKind(
      node, object, value, state, representation.write_barrier_kind());
  if (write_barrier_kind != representation.write_barrier_kind()) {
    NodeProperties::ChangeOp(
        node, machine()->Store(StoreRepresentation(
                  representation.representation(), write_barrier_kind)));
    return Changed(node);
  }
  return NoChange();
}
References v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), ComputeWriteBarrierKind(), DCHECK_EQ, v8::internal::compiler::Node::InputAt(), machine(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::StoreRepresentation::representation(), v8::internal::wasm::liftoff::Store(), v8::internal::compiler::StoreRepresentationOf(), v8::internal::value, and v8::internal::compiler::StoreRepresentation::write_barrier_kind().
Referenced by Reduce(), and v8::internal::compiler::MemoryOptimizer::VisitStore().
ReduceStoreElement()
Reduction v8::internal::compiler::MemoryLowering::ReduceStoreElement (Node * node, AllocationState const * state = nullptr)
Definition at line 581 of file memory-lowering.cc.
                                                                           {
  DCHECK_EQ(IrOpcode::kStoreElement, node->opcode());
  ElementAccess const& access = ElementAccessOf(node->op());
  Node* object = node->InputAt(0);
  Node* index = node->InputAt(1);
  Node* value = node->InputAt(2);
  node->ReplaceInput(1, ComputeIndex(access, index));
  WriteBarrierKind write_barrier_kind = ComputeWriteBarrierKind(
      node, object, value, state, access.write_barrier_kind);
  NodeProperties::ChangeOp(
      node, machine()->Store(StoreRepresentation(
                access.machine_type.representation(), write_barrier_kind)));
  return Changed(node);
}
References v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), ComputeIndex(), ComputeWriteBarrierKind(), DCHECK_EQ, v8::internal::compiler::ElementAccessOf(), v8::internal::index, v8::internal::compiler::Node::InputAt(), machine(), v8::internal::compiler::ElementAccess::machine_type, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::MachineType::representation(), v8::internal::wasm::liftoff::Store(), v8::internal::value, and v8::internal::compiler::ElementAccess::write_barrier_kind.
Referenced by Reduce(), and v8::internal::compiler::MemoryOptimizer::VisitStoreElement().
ReduceStoreField()
Reduction v8::internal::compiler::MemoryLowering::ReduceStoreField (Node * node, AllocationState const * state = nullptr)
Definition at line 597 of file memory-lowering.cc.
                                                                         {
  DCHECK_EQ(IrOpcode::kStoreField, node->opcode());
  FieldAccess const& access = FieldAccessOf(node->op());
  // External pointer must never be stored by optimized code when sandbox is
  // turned on
  DCHECK(!access.type.Is(Type::ExternalPointer()) || !V8_ENABLE_SANDBOX_BOOL);
  // SandboxedPointers are not currently stored by optimized code.
  DCHECK(!access.type.Is(Type::SandboxedPointer()));
  // Bounded size fields are not currently stored by optimized code.
  DCHECK(!access.is_bounded_size_access);
  MachineType machine_type = access.machine_type;
  Node* object = node->InputAt(0);
  Node* value = node->InputAt(1);
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  __ InitializeEffectControl(effect, control);
  WriteBarrierKind write_barrier_kind = ComputeWriteBarrierKind(
      node, object, value, state, access.write_barrier_kind);
  Node* offset = __ IntPtrConstant(access.offset - access.tag());
  node->InsertInput(graph_zone(), 1, offset);
  if (machine_type.IsMapWord()) {
    machine_type = MachineType::TaggedPointer();
#ifdef V8_MAP_PACKING
    Node* mapword = __ PackMapWord(TNode<Map>::UncheckedCast(value));
    node->ReplaceInput(2, mapword);
#endif
  }
  if (machine_type.representation() ==
      MachineRepresentation::kIndirectPointer) {
    // Indirect pointer stores require knowledge of the indirect pointer tag of
    // the field. This is technically only required for stores that need a
    // write barrier, but currently we track the tag for all such stores.
    DCHECK_NE(access.indirect_pointer_tag, kIndirectPointerNullTag);
    Node* tag = __ IntPtrConstant(access.indirect_pointer_tag);
    node->InsertInput(graph_zone(), 3, tag);
    NodeProperties::ChangeOp(
        node, machine()->StoreIndirectPointer(write_barrier_kind));
  } else {
    NodeProperties::ChangeOp(
        node, machine()->Store(StoreRepresentation(
                  machine_type.representation(), write_barrier_kind)));
  }
  return Changed(node);
}
References __, v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), ComputeWriteBarrierKind(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, v8::internal::compiler::FieldAccessOf(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), graph_zone(), v8::internal::compiler::FieldAccess::indirect_pointer_tag, v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::InsertInput(), v8::internal::compiler::IntPtrConstant(), v8::internal::compiler::Type::Is(), v8::internal::compiler::FieldAccess::is_bounded_size_access, v8::internal::MachineType::IsMapWord(), v8::internal::kIndirectPointer, v8::internal::kIndirectPointerNullTag, machine(), v8::internal::compiler::FieldAccess::machine_type, v8::internal::wasm::machine_type(), v8::internal::compiler::FieldAccess::offset, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::MachineType::representation(), v8::internal::wasm::liftoff::Store(), v8::internal::compiler::FieldAccess::tag(), v8::internal::MachineType::TaggedPointer(), v8::internal::compiler::FieldAccess::type, V8_ENABLE_SANDBOX_BOOL, v8::internal::value, and v8::internal::compiler::FieldAccess::write_barrier_kind.
Referenced by Reduce(), and v8::internal::compiler::MemoryOptimizer::VisitStoreField().
ReduceStoreToObject()
Reduction v8::internal::compiler::MemoryLowering::ReduceStoreToObject (Node * node, AllocationState const * state = nullptr)
Definition at line 560 of file memory-lowering.cc.
                                                                            {
  DCHECK(node->opcode() == IrOpcode::kStoreToObject ||
         node->opcode() == IrOpcode::kInitializeImmutableInObject);
  ObjectAccess const& access = ObjectAccessOf(node->op());
  Node* object = node->InputAt(0);
  Node* value = node->InputAt(2);
  WriteBarrierKind write_barrier_kind = ComputeWriteBarrierKind(
      node, object, value, state, access.write_barrier_kind);
  DCHECK(!access.machine_type.IsMapWord());
  MachineRepresentation rep = access.machine_type.representation();
  StoreRepresentation store_rep(rep, write_barrier_kind);
  const Operator* store_op = ElementSizeInBytes(rep) > kTaggedSize &&
                                     !machine()->UnalignedStoreSupported(rep)
                                 ? machine()->UnalignedStore(rep)
                                 : machine()->Store(store_rep);
  NodeProperties::ChangeOp(node, store_op);
  return Changed(node);
}
References v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), ComputeWriteBarrierKind(), v8::internal::DCHECK(), v8::internal::ElementSizeInBytes(), v8::internal::compiler::Node::InputAt(), v8::internal::MachineType::IsMapWord(), v8::internal::kTaggedSize, machine(), v8::internal::compiler::ObjectAccess::machine_type, v8::internal::compiler::ObjectAccessOf(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::MachineType::representation(), v8::internal::compiler::MachineOperatorBuilder::Store(), v8::internal::compiler::MachineOperatorBuilder::UnalignedStore(), v8::internal::compiler::MachineOperatorBuilder::UnalignedStoreSupported(), v8::internal::value, and v8::internal::compiler::ObjectAccess::write_barrier_kind.
Referenced by Reduce(), and v8::internal::compiler::MemoryOptimizer::VisitStoreToObject().
zone()
Zone* v8::internal::compiler::MemoryLowering::zone () const [inline], [private]
Definition at line 124 of file memory-lowering.h.
{ return zone_; }
References zone_.
Referenced by v8::internal::compiler::MemoryLowering::AllocationState::Closed(), ComputeWriteBarrierKind(), v8::internal::compiler::MemoryLowering::AllocationState::Empty(), v8::internal::compiler::MemoryLowering::AllocationState::Open(), and ReduceAllocateRaw().
Member Data Documentation
allocate_operator_
SetOncePointer<const Operator> v8::internal::compiler::MemoryLowering::allocate_operator_ [private]
Definition at line 130 of file memory-lowering.h.
Referenced by EnsureAllocateOperator(), and ReduceAllocateRaw().
allocation_folding_
AllocationFolding v8::internal::compiler::MemoryLowering::allocation_folding_ [private]
Definition at line 139 of file memory-lowering.h.
Referenced by ReduceAllocateRaw().
common_
CommonOperatorBuilder* v8::internal::compiler::MemoryLowering::common_ [private]
Definition at line 135 of file memory-lowering.h.
Referenced by common().
function_debug_name_
const char* v8::internal::compiler::MemoryLowering::function_debug_name_ [private]
Definition at line 141 of file memory-lowering.h.
Referenced by ComputeWriteBarrierKind().
graph_
TFGraph* v8::internal::compiler::MemoryLowering::graph_ [private]
Definition at line 134 of file memory-lowering.h.
Referenced by graph().
graph_assembler_
JSGraphAssembler* v8::internal::compiler::MemoryLowering::graph_assembler_ [private]
Definition at line 137 of file memory-lowering.h.
Referenced by gasm().
is_wasm_
bool v8::internal::compiler::MemoryLowering::is_wasm_ [private]
Definition at line 138 of file memory-lowering.h.
Referenced by ReduceAllocateRaw().
isolate_
Isolate* v8::internal::compiler::MemoryLowering::isolate_ [private]
Definition at line 132 of file memory-lowering.h.
Referenced by EnsureAllocateOperator(), isolate(), and ReduceAllocateRaw().
machine_
MachineOperatorBuilder* v8::internal::compiler::MemoryLowering::machine_ [private]
Definition at line 136 of file memory-lowering.h.
Referenced by machine().
wasm_instance_node_
SetOncePointer<Node> v8::internal::compiler::MemoryLowering::wasm_instance_node_ [private]
Definition at line 131 of file memory-lowering.h.
write_barrier_assert_failed_
WriteBarrierAssertFailedCallback v8::internal::compiler::MemoryLowering::write_barrier_assert_failed_ [private]
Definition at line 140 of file memory-lowering.h.
Referenced by ComputeWriteBarrierKind().
zone_
Zone* v8::internal::compiler::MemoryLowering::zone_ [private]
Definition at line 133 of file memory-lowering.h.
Referenced by zone().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/memory-lowering.h
/mnt/V8SourceCode/src/compiler/memory-lowering.cc