v8::internal::heap::List< T > Class Template Reference
#include <list.h>
Public Member Functions
List ()=default
List (List &&other) V8_NOEXCEPT
List & operator= (List &&other) V8_NOEXCEPT
void PushBack (T *element)
void PushFront (T *element)
void Remove (T *element)
bool Contains (const T *element) const
bool Empty () const
T * front ()
T * back ()
const T * front () const
const T * back () const
size_t size () const
Private Member Functions
void AddFirstElement (T *element)
void InsertAfter (T *element, T *other)
void InsertBefore (T *element, T *other)
Private Attributes
T * front_ {nullptr}
T * back_ {nullptr}
size_t size_ {0}
Detailed Description
template<class T>
class v8::internal::heap::List< T >
Definition at line 17 of file list.h.
Constructor & Destructor Documentation
List() [1/2]
template<class T >
v8::internal::heap::List< T >::List () [default]
List() [2/2]
template<class T >
v8::internal::heap::List< T >::List (List< T > && other) [inline]
Definition at line 20 of file list.h.
                                 : front_(std::exchange(other.front_, nullptr)),
                                   back_(std::exchange(other.back_, nullptr)),
                                   size_(std::exchange(other.size_, 0)) {}
Member Function Documentation
AddFirstElement()
template<class T >
void v8::internal::heap::List< T >::AddFirstElement (T * element) [inline], [private]
Definition at line 95 of file list.h.
                                   {
    DCHECK(!back_);
    DCHECK(!front_);
    DCHECK(!element->list_node().next());
    DCHECK(!element->list_node().prev());
    element->list_node().set_prev(nullptr);
    element->list_node().set_next(nullptr);
    front_ = element;
    back_ = element;
  }
References v8::internal::heap::List< T >::back_, v8::internal::DCHECK(), and v8::internal::heap::List< T >::front_.
Referenced by v8::internal::heap::List< T >::PushBack(), and v8::internal::heap::List< T >::PushFront().
back() [1/2]
template<class T >
T* v8::internal::heap::List< T >::back () [inline]
Definition at line 87 of file list.h.
{ return back_; }
References v8::internal::heap::List< T >::back_.
back() [2/2]
template<class T >
const T* v8::internal::heap::List< T >::back () const [inline]
Definition at line 90 of file list.h.
{ return back_; }
References v8::internal::heap::List< T >::back_.
Contains()
template<class T >
bool v8::internal::heap::List< T >::Contains (const T * element) const [inline]
Definition at line 71 of file list.h.
                                        {
    const T* it = front_;
    while (it) {
      if (it == element) return true;
      it = it->list_node().next();
    }
    return false;
  }
References v8::internal::heap::List< T >::front_.
Referenced by v8::internal::heap::List< T >::Remove().
Empty()
template<class T >
bool v8::internal::heap::List< T >::Empty () const [inline]
Definition at line 80 of file list.h.
                     {
    DCHECK_EQ(size_ == 0, !front_);
    DCHECK_EQ(size_ == 0, !back_);
    return size_ == 0;
  }
References v8::internal::heap::List< T >::back_, DCHECK_EQ, v8::internal::heap::List< T >::front_, and v8::internal::heap::List< T >::size_.
front() [1/2]
template<class T >
T* v8::internal::heap::List< T >::front () [inline]
Definition at line 86 of file list.h.
{ return front_; }
References v8::internal::heap::List< T >::front_.
front() [2/2]
template<class T >
const T* v8::internal::heap::List< T >::front () const [inline]
Definition at line 89 of file list.h.
{ return front_; }
References v8::internal::heap::List< T >::front_.
InsertAfter()
template<class T >
void v8::internal::heap::List< T >::InsertAfter (T * element, T * other) [inline], [private]
Definition at line 106 of file list.h.
                                         {
    T* other_next = other->list_node().next();
    element->list_node().set_next(other_next);
    element->list_node().set_prev(other);
    other->list_node().set_next(element);
    if (other_next)
      other_next->list_node().set_prev(element);
    else
      back_ = element;
  }
References v8::internal::heap::List< T >::back_.
Referenced by v8::internal::heap::List< T >::PushBack().
InsertBefore()
template<class T >
void v8::internal::heap::List< T >::InsertBefore (T * element, T * other) [inline], [private]
Definition at line 117 of file list.h.
                                          {
    T* other_prev = other->list_node().prev();
    element->list_node().set_next(other);
    element->list_node().set_prev(other_prev);
    other->list_node().set_prev(element);
    if (other_prev) {
      other_prev->list_node().set_next(element);
    } else {
      front_ = element;
    }
  }
References v8::internal::heap::List< T >::front_.
Referenced by v8::internal::heap::List< T >::PushFront().
operator=()
template<class T >
List& v8::internal::heap::List< T >::operator= (List< T > && other) [inline]
Definition at line 23 of file list.h.
                                            {
    front_ = std::exchange(other.front_, nullptr);
    back_ = std::exchange(other.back_, nullptr);
    size_ = std::exchange(other.size_, 0);
    return *this;
  }
References v8::internal::heap::List< T >::back_, v8::internal::heap::List< T >::front_, and v8::internal::heap::List< T >::size_.
PushBack()
template<class T >
void v8::internal::heap::List< T >::PushBack (T * element) [inline]
Definition at line 30 of file list.h.
                            {
    DCHECK(!element->list_node().next());
    DCHECK(!element->list_node().prev());
    if (back_) {
      DCHECK(front_);
      InsertAfter(element, back_);
    } else {
      AddFirstElement(element);
    }
    size_++;
  }
References v8::internal::heap::List< T >::AddFirstElement(), v8::internal::heap::List< T >::back_, v8::internal::DCHECK(), v8::internal::heap::List< T >::front_, v8::internal::heap::List< T >::InsertAfter(), and v8::internal::heap::List< T >::size_.
PushFront()
template<class T >
void v8::internal::heap::List< T >::PushFront (T * element) [inline]
Definition at line 42 of file list.h.
                             {
    DCHECK(!element->list_node().next());
    DCHECK(!element->list_node().prev());
    if (front_) {
      DCHECK(back_);
      InsertBefore(element, front_);
    } else {
      AddFirstElement(element);
    }
    size_++;
  }
References v8::internal::heap::List< T >::AddFirstElement(), v8::internal::heap::List< T >::back_, v8::internal::DCHECK(), v8::internal::heap::List< T >::front_, v8::internal::heap::List< T >::InsertBefore(), and v8::internal::heap::List< T >::size_.
Remove()
template<class T >
void v8::internal::heap::List< T >::Remove (T * element) [inline]
Definition at line 54 of file list.h.
                          {
    DCHECK(Contains(element));
    if (back_ == element) {
      back_ = element->list_node().prev();
    }
    if (front_ == element) {
      front_ = element->list_node().next();
    }
    T* next = element->list_node().next();
    T* prev = element->list_node().prev();
    if (next) next->list_node().set_prev(prev);
    if (prev) prev->list_node().set_next(next);
    element->list_node().set_prev(nullptr);
    element->list_node().set_next(nullptr);
    size_--;
  }
References v8::internal::heap::List< T >::back_, v8::internal::heap::List< T >::Contains(), v8::internal::DCHECK(), v8::internal::heap::List< T >::front_, and v8::internal::heap::List< T >::size_.
size()
template<class T >
size_t v8::internal::heap::List< T >::size () const [inline]
Definition at line 92 of file list.h.
{ return size_; }
References v8::internal::heap::List< T >::size_.
Member Data Documentation
back_
template<class T >
T* v8::internal::heap::List< T >::back_ {nullptr} [private]
Definition at line 130 of file list.h.
Referenced by v8::internal::heap::List< T >::AddFirstElement(), v8::internal::heap::List< T >::back(), v8::internal::heap::List< T >::Empty(), v8::internal::heap::List< T >::InsertAfter(), v8::internal::heap::List< T >::operator=(), v8::internal::heap::List< T >::PushBack(), v8::internal::heap::List< T >::PushFront(), and v8::internal::heap::List< T >::Remove().
front_
template<class T >
T* v8::internal::heap::List< T >::front_ {nullptr} [private]
Definition at line 129 of file list.h.
Referenced by v8::internal::heap::List< T >::AddFirstElement(), v8::internal::heap::List< T >::Contains(), v8::internal::heap::List< T >::Empty(), v8::internal::heap::List< T >::front(), v8::internal::heap::List< T >::InsertBefore(), v8::internal::heap::List< T >::operator=(), v8::internal::heap::List< T >::PushBack(), v8::internal::heap::List< T >::PushFront(), and v8::internal::heap::List< T >::Remove().
size_
template<class T >
size_t v8::internal::heap::List< T >::size_ {0} [private]
Definition at line 131 of file list.h.
Referenced by v8::internal::heap::List< T >::Empty(), v8::internal::heap::List< T >::operator=(), v8::internal::heap::List< T >::PushBack(), v8::internal::heap::List< T >::PushFront(), v8::internal::heap::List< T >::Remove(), and v8::internal::heap::List< T >::size().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/list.h