v8::internal::PageMetadata Class Reference
#include <page-metadata.h>
Public Member Functions
PageMetadata (Heap *heap, BaseSpace *space, size_t size, Address area_start, Address area_end, VirtualMemory reservation)
V8_EXPORT_PRIVATE void MarkNeverAllocateForTesting ()
void MarkEvacuationCandidate ()
void ClearEvacuationCandidate ()
PageMetadata * next_page ()
PageMetadata * prev_page ()
const PageMetadata * next_page () const
const PageMetadata * prev_page () const
template<typename Callback >
void ForAllFreeListCategories (Callback callback)
V8_EXPORT_PRIVATE size_t AvailableInFreeList ()
size_t AvailableInFreeListFromAllocatedBytes ()
FreeListCategory * free_list_category (FreeListCategoryType type)
V8_EXPORT_PRIVATE void CreateBlackArea (Address start, Address end)
void DestroyBlackArea (Address start, Address end)
void InitializeFreeListCategories ()
void AllocateFreeListCategories ()
void ReleaseFreeListCategories ()
ActiveSystemPages * active_system_pages ()
template<RememberedSetType remembered_set>
void ClearTypedSlotsInFreeMemory (const TypedSlotSet::FreeRangesMap &ranges)
template<RememberedSetType remembered_set>
void AssertNoTypedSlotsInFreeMemory (const TypedSlotSet::FreeRangesMap &ranges)
Static Public Member Functions
static PageMetadata * FromAddress (Address addr)
static PageMetadata * FromHeapObject (Tagged< HeapObject > o)
static PageMetadata * cast (MemoryChunkMetadata *metadata)
static PageMetadata * cast (MutablePageMetadata *metadata)
static PageMetadata * FromAllocationAreaAddress (Address address)
static bool OnSamePage (Address address1, Address address2)
static bool IsAlignedToPageSize (Address addr)
static PageMetadata * ConvertNewToOld (PageMetadata *old_page, FreeMode free_mode)
Friends
class MemoryAllocator
Additional Inherited Members
Detailed Description
Definition at line 24 of file page-metadata.h.
Constructor & Destructor Documentation
PageMetadata()
v8::internal::PageMetadata::PageMetadata (Heap * heap, BaseSpace * space, size_t size, Address area_start, Address area_end, VirtualMemory reservation)
Definition at line 14 of file page-metadata.cc.
    : MutablePageMetadata(heap, space, size, area_start, area_end,
                          std::move(reservation), PageSize::kRegular) {
  DCHECK(!IsLargePage());
}
References v8::internal::DCHECK(), and v8::internal::MutablePageMetadata::IsLargePage().
Member Function Documentation
active_system_pages()
ActiveSystemPages* v8::internal::PageMetadata::active_system_pages () [inline]
Definition at line 103 of file page-metadata.h.
                                           {
    return active_system_pages_.get();
  }
References v8::internal::MutablePageMetadata::active_system_pages_.
Referenced by v8::internal::SemiSpace::AddRangeToActiveSystemPages(), v8::internal::PagedSpaceBase::AddRangeToActiveSystemPages(), and v8::internal::PagedSpaceBase::ReduceActiveSystemPages().
AllocateFreeListCategories()
void v8::internal::PageMetadata::AllocateFreeListCategories ()
Definition at line 22 of file page-metadata.cc.
                                              {
  DCHECK_NULL(categories_);
  categories_ =
      new FreeListCategory*[owner()->free_list()->number_of_categories()]();
  for (int i = kFirstCategory; i <= owner()->free_list()->last_category();
       i++) {
    DCHECK_NULL(categories_[i]);
    categories_[i] = new FreeListCategory();
  }
}
References v8::internal::MutablePageMetadata::categories_, DCHECK_NULL, v8::internal::Space::free_list(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kFirstCategory, v8::internal::FreeList::last_category(), v8::internal::FreeList::number_of_categories(), and v8::internal::MutablePageMetadata::owner().
Referenced by v8::internal::PagedSpaceForNewSpace::InitializePage(), and v8::internal::PagedSpaceBase::InitializePage().
AssertNoTypedSlotsInFreeMemory()
template<RememberedSetType remembered_set>
void v8::internal::PageMetadata::AssertNoTypedSlotsInFreeMemory (const TypedSlotSet::FreeRangesMap & ranges) [inline]
Definition at line 116 of file page-metadata.h.
                                               {
#if DEBUG
    TypedSlotSet* typed_slot_set = this->typed_slot_set<remembered_set>();
    if (typed_slot_set != nullptr) {
      typed_slot_set->AssertNoInvalidSlots(ranges);
    }
#endif // DEBUG
  }
References v8::internal::TypedSlotSet::AssertNoInvalidSlots(), and v8::internal::MutablePageMetadata::typed_slot_set().
Referenced by v8::internal::Sweeper::CleanupTypedSlotsInFreeMemory().
AvailableInFreeList()
size_t v8::internal::PageMetadata::AvailableInFreeList ()
Definition at line 71 of file page-metadata.cc.
                                         {
  size_t sum = 0;
  ForAllFreeListCategories(
      [&sum](FreeListCategory* category) { sum += category->available(); });
  return sum;
}
References v8::internal::FreeListCategory::available(), and ForAllFreeListCategories().
Referenced by v8::internal::FreeList::Free(), v8::internal::FreeListManyCached::Free(), v8::internal::PagedSpaceBase::MergeCompactionSpace(), and v8::internal::PagedSpaceBase::RelinkFreeListCategories().
AvailableInFreeListFromAllocatedBytes()
size_t v8::internal::PageMetadata::AvailableInFreeListFromAllocatedBytes () [inline]
Definition at line 87 of file page-metadata.h.
                                                 {
    DCHECK_GE(area_size(), wasted_memory() + allocated_bytes());
    return area_size() - wasted_memory() - allocated_bytes();
  }
References v8::internal::MemoryChunkMetadata::allocated_bytes(), v8::internal::MemoryChunkMetadata::area_size(), DCHECK_GE, and v8::internal::MemoryChunkMetadata::wasted_memory().
Referenced by v8::internal::FreeList::Free(), v8::internal::FreeListManyCached::Free(), v8::internal::PagedSpaceBase::MergeCompactionSpace(), and v8::internal::PagedSpaceBase::RelinkFreeListCategories().
cast() [1/2]
static PageMetadata* v8::internal::PageMetadata::cast (MemoryChunkMetadata * metadata) [inline], [static]
Definition at line 35 of file page-metadata.h.
                                                           {
    return cast(MutablePageMetadata::cast(metadata));
  }
References v8::internal::MutablePageMetadata::cast().
Referenced by v8::internal::Heap::ClearRecordedSlotRange(), v8::internal::Heap::EnsureSweepingCompletedForObject(), v8::internal::PretenuringHandler::FindAllocationMemento(), v8::internal::SemiSpace::first_page(), v8::internal::SemiSpace::InitializePage(), v8::internal::PagedSpaceForNewSpace::InitializePage(), v8::internal::PagedSpaceBase::InitializePage(), v8::internal::SemiSpace::last_page(), v8::internal::MarkCompactCollector::MarkRootObject(), and v8::internal::SemiSpace::MoveQuarantinedPage().
cast() [2/2]
static PageMetadata* v8::internal::PageMetadata::cast (MutablePageMetadata * metadata) [inline], [static]
Definition at line 39 of file page-metadata.h.
                                                           {
    DCHECK_IMPLIES(metadata, !metadata->Chunk()->IsLargePage());
    return static_cast<PageMetadata*>(metadata);
  }
References v8::internal::MemoryChunkMetadata::Chunk(), DCHECK_IMPLIES, and v8::internal::MemoryChunk::IsLargePage().
ClearEvacuationCandidate()
void v8::internal::PageMetadata::ClearEvacuationCandidate () [inline]
Definition at line 50 of file page-metadata-inl.h.
                                            {
  MemoryChunk* chunk = Chunk();
  if (!chunk->IsFlagSet(MemoryChunk::COMPACTION_WAS_ABORTED)) {
    DCHECK_NULL(slot_set<OLD_TO_OLD>());
    DCHECK_NULL(typed_slot_set<OLD_TO_OLD>());
  }
  chunk->ClearFlagSlow(MemoryChunk::EVACUATION_CANDIDATE);
  InitializeFreeListCategories();
}
References v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::MemoryChunk::ClearFlagSlow(), v8::internal::MemoryChunk::COMPACTION_WAS_ABORTED, DCHECK_NULL, v8::internal::MemoryChunk::EVACUATION_CANDIDATE, InitializeFreeListCategories(), and v8::internal::MemoryChunk::IsFlagSet().
ClearTypedSlotsInFreeMemory()
template<RememberedSetType remembered_set>
void v8::internal::PageMetadata::ClearTypedSlotsInFreeMemory (const TypedSlotSet::FreeRangesMap & ranges) [inline]
Definition at line 108 of file page-metadata.h.
                                                                            {
    TypedSlotSet* typed_slot_set = this->typed_slot_set<remembered_set>();
    if (typed_slot_set != nullptr) {
      typed_slot_set->ClearInvalidSlots(ranges);
    }
  }
References v8::internal::TypedSlotSet::ClearInvalidSlots(), and v8::internal::MutablePageMetadata::typed_slot_set().
Referenced by v8::internal::Sweeper::CleanupTypedSlotsInFreeMemory().
ConvertNewToOld()
PageMetadata * v8::internal::PageMetadata::ConvertNewToOld (PageMetadata * old_page, FreeMode free_mode) [static]
Definition at line 54 of file page-metadata.cc.
                                                                {
  DCHECK(old_page);
  MemoryChunk* chunk = old_page->Chunk();
  DCHECK(chunk->InNewSpace());
  old_page->ResetAgeInNewSpace();
  OldSpace* old_space = old_page->heap()->old_space();
  old_page->set_owner(old_space);
  chunk->ClearFlagsNonExecutable(MemoryChunk::kAllFlagsMask);
  DCHECK_NE(old_space->identity(), SHARED_SPACE);
  chunk->SetOldGenerationPageFlags(
      old_page->heap()->incremental_marking()->marking_mode(), OLD_SPACE);
  PageMetadata* new_page = old_space->InitializePage(old_page);
  old_space->AddPromotedPage(new_page, free_mode);
  return new_page;
}
References v8::internal::OldSpace::AddPromotedPage(), v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::MemoryChunk::ClearFlagsNonExecutable(), v8::internal::DCHECK(), DCHECK_NE, v8::internal::MemoryChunkMetadata::heap(), v8::internal::Heap::incremental_marking(), v8::internal::PagedSpaceBase::InitializePage(), v8::internal::MemoryChunk::InNewSpace(), v8::internal::MemoryChunk::kAllFlagsMask, v8::internal::IncrementalMarking::marking_mode(), v8::internal::OLD_SPACE, v8::internal::Heap::old_space(), v8::internal::MutablePageMetadata::ResetAgeInNewSpace(), v8::internal::MemoryChunkMetadata::set_owner(), v8::internal::MemoryChunk::SetOldGenerationPageFlags(), and v8::internal::SHARED_SPACE.
Referenced by v8::internal::NewSpace::PromotePageToOldSpace().
CreateBlackArea()
void v8::internal::PageMetadata::CreateBlackArea (Address start, Address end)
Definition at line 87 of file page-metadata.cc.
                                                             {
  DCHECK(!v8_flags.black_allocated_pages);
  DCHECK_NE(NEW_SPACE, owner_identity());
  DCHECK(v8_flags.sticky_mark_bits ||
         heap()->incremental_marking()->black_allocation());
  DCHECK_EQ(PageMetadata::FromAddress(start), this);
  DCHECK_LT(start, end);
  DCHECK_EQ(PageMetadata::FromAddress(end - 1), this);
  marking_bitmap()->SetRange<AccessMode::ATOMIC>(
      MarkingBitmap::AddressToIndex(start),
      MarkingBitmap::LimitAddressToIndex(end));
  IncrementLiveBytesAtomically(static_cast<intptr_t>(end - start));
  owner()->NotifyBlackAreaCreated(end - start);
}
References v8::internal::MarkingBitmap::AddressToIndex(), v8::internal::ATOMIC, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LT, DCHECK_NE, v8::internal::compiler::end(), FromAddress(), v8::internal::MutablePageMetadata::IncrementLiveBytesAtomically(), v8::internal::MarkingBitmap::LimitAddressToIndex(), v8::internal::MutablePageMetadata::marking_bitmap(), v8::internal::NEW_SPACE, v8::internal::Space::NotifyBlackAreaCreated(), v8::internal::MutablePageMetadata::owner(), v8::internal::MutablePageMetadata::owner_identity(), v8::internal::MarkingBitmap::SetRange(), and v8::internal::v8_flags.
Referenced by v8::internal::MainAllocator::MarkLinearAllocationAreaBlack(), and v8::internal::PagedSpaceAllocatorPolicy::SetLinearAllocationArea().
DestroyBlackArea()
void v8::internal::PageMetadata::DestroyBlackArea (Address start, Address end)
Definition at line 102 of file page-metadata.cc.
                                                              {
  DCHECK(!v8_flags.black_allocated_pages);
  DCHECK_NE(NEW_SPACE, owner_identity());
  DCHECK(v8_flags.sticky_mark_bits ||
         heap()->incremental_marking()->black_allocation());
  DCHECK_EQ(PageMetadata::FromAddress(start), this);
  DCHECK_LT(start, end);
  DCHECK_EQ(PageMetadata::FromAddress(end - 1), this);
  marking_bitmap()->ClearRange<AccessMode::ATOMIC>(
      MarkingBitmap::AddressToIndex(start),
      MarkingBitmap::LimitAddressToIndex(end));
  IncrementLiveBytesAtomically(-static_cast<intptr_t>(end - start));
  owner()->NotifyBlackAreaDestroyed(end - start);
}
References v8::internal::MarkingBitmap::AddressToIndex(), v8::internal::ATOMIC, v8::internal::MarkingBitmap::ClearRange(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LT, DCHECK_NE, v8::internal::compiler::end(), FromAddress(), v8::internal::MutablePageMetadata::IncrementLiveBytesAtomically(), v8::internal::MarkingBitmap::LimitAddressToIndex(), v8::internal::MutablePageMetadata::marking_bitmap(), v8::internal::NEW_SPACE, v8::internal::Space::NotifyBlackAreaDestroyed(), v8::internal::MutablePageMetadata::owner(), v8::internal::MutablePageMetadata::owner_identity(), and v8::internal::v8_flags.
Referenced by v8::internal::PagedSpaceAllocatorPolicy::FreeLinearAllocationAreaUnsynchronized(), and v8::internal::MainAllocator::UnmarkLinearAllocationArea().
ForAllFreeListCategories()
template<typename Callback >
void v8::internal::PageMetadata::ForAllFreeListCategories (Callback callback) [inline]
Definition at line 35 of file page-metadata-inl.h.
                                                             {
  for (int i = kFirstCategory; i < owner()->free_list()->number_of_categories();
       i++) {
    callback(categories_[i]);
  }
}
References v8::internal::MutablePageMetadata::categories_, v8::internal::Space::free_list(), v8::internal::kFirstCategory, v8::internal::FreeList::number_of_categories(), and v8::internal::MutablePageMetadata::owner().
Referenced by AvailableInFreeList(), v8::internal::FreeList::EvictFreeListItems(), v8::internal::PagedSpaceBase::RelinkFreeListCategories(), v8::internal::PagedSpaceBase::UnlinkFreeListCategories(), and v8::internal::anonymous_namespace{sweeper.cc}::VerifyPreparedPage().
free_list_category()
FreeListCategory* v8::internal::PageMetadata::free_list_category (FreeListCategoryType type) [inline]
Definition at line 92 of file page-metadata.h.
                                                                  {
    return categories_[type];
  }
References v8::internal::MutablePageMetadata::categories_, and v8::internal::tracing::type.
Referenced by v8::internal::FreeList::Free(), and v8::internal::FreeListManyCached::Free().
FromAddress()
PageMetadata * v8::internal::PageMetadata::FromAddress (Address addr) [inline], [static]
Definition at line 19 of file page-metadata-inl.h.
                                                    {
  return reinterpret_cast<PageMetadata*>(
      MemoryChunk::FromAddress(addr)->Metadata());
}
References v8::internal::MemoryChunk::FromAddress(), and v8::internal::MemoryChunk::Metadata().
Referenced by v8::internal::SemiSpaceNewSpace::AddParkedAllocationBuffer(), v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::AddToFreeListFreeSpaceHandler(), v8::internal::PagedSpaceBase::Contains(), CreateBlackArea(), DestroyBlackArea(), v8::internal::FreeList::Free(), v8::internal::FreeListManyCached::Free(), v8::internal::PagedSpaceBase::FreeInternal(), v8::internal::PagedSpaceAllocatorPolicy::FreeLinearAllocationAreaUnsynchronized(), FromAllocationAreaAddress(), FromHeapObject(), v8::internal::Heap::RightTrimArray(), v8::internal::PagedSpaceAllocatorPolicy::TryAllocationFromFreeList(), v8::internal::PagedSpaceAllocatorPolicy::TryExtendLAB(), v8::internal::Heap::UpdateYoungReferenceInExternalStringTableEntry(), and v8::internal::ReadOnlyRoots::VerifyNameForProtectorsPages().
FromAllocationAreaAddress()
PageMetadata * v8::internal::PageMetadata::FromAllocationAreaAddress (Address address) [inline], [static]
Definition at line 30 of file page-metadata-inl.h.
                                                                     {
  return PageMetadata::FromAddress(address - kTaggedSize);
}
References FromAddress(), and v8::internal::kTaggedSize.
Referenced by v8::internal::SemiSpaceNewSpace::DecrementAllocationTop(), v8::internal::PagedNewSpaceAllocatorPolicy::EnsureAllocation(), v8::internal::PagedNewSpaceAllocatorPolicy::FreeLinearAllocationArea(), v8::internal::SemiSpaceNewSpace::IncrementAllocationTop(), v8::internal::MainAllocator::MarkLinearAllocationAreaBlack(), v8::internal::SemiSpaceObjectIterator::Next(), v8::internal::SemiSpaceNewSpace::SetAgeMarkAndBelowAgeMarkPageFlags(), v8::internal::PagedSpaceAllocatorPolicy::SetLinearAllocationArea(), and v8::internal::MainAllocator::UnmarkLinearAllocationArea().
FromHeapObject()
PageMetadata * v8::internal::PageMetadata::FromHeapObject (Tagged< HeapObject > o) [inline], [static]
Definition at line 25 of file page-metadata-inl.h.
                                                               {
  return FromAddress(o.ptr());
}
References FromAddress(), and v8::internal::TaggedImpl< kRefType, StorageType >::ptr().
Referenced by v8::internal::HeapObjectRange::iterator::AdvanceToNextObject(), v8::internal::FreeListMany::Allocate(), v8::internal::FreeListManyCached::Allocate(), v8::internal::FreeListManyCachedFastPathBase::Allocate(), v8::internal::Heap::FinalizeExternalString(), v8::internal::FreeList::GetPageForCategoryType(), v8::internal::anonymous_namespace{scavenger.cc}::YoungGenerationConservativeStackVisitor::HandleObjectFound(), v8::internal::PagedSpaceAllocatorPolicy::TryAllocationFromFreeList(), v8::internal::HeapAllocator::TryResizeLargeObject(), v8::internal::Heap::UpdateExternalString(), v8::internal::Heap::UpdateYoungReferenceInExternalStringTableEntry(), and v8::internal::EvacuateOldSpaceVisitor::Visit().
InitializeFreeListCategories()
void v8::internal::PageMetadata::InitializeFreeListCategories ()
Definition at line 33 of file page-metadata.cc.
                                                {
  for (int i = kFirstCategory; i <= owner()->free_list()->last_category();
       i++) {
    categories_[i]->Initialize(static_cast<FreeListCategoryType>(i));
  }
}
References v8::internal::MutablePageMetadata::categories_, v8::internal::Space::free_list(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::FreeListCategory::Initialize(), v8::internal::kFirstCategory, v8::internal::FreeList::last_category(), and v8::internal::MutablePageMetadata::owner().
Referenced by ClearEvacuationCandidate(), v8::internal::PagedSpaceForNewSpace::InitializePage(), and v8::internal::PagedSpaceBase::InitializePage().
IsAlignedToPageSize()
static bool v8::internal::PageMetadata::IsAlignedToPageSize (Address addr) [inline], [static]
Definition at line 57 of file page-metadata.h.
                                                {
    return MemoryChunk::IsAligned(addr);
  }
References v8::internal::MemoryChunk::IsAligned().
Referenced by v8::internal::SemiSpaceObjectIterator::Next().
MarkEvacuationCandidate()
void v8::internal::PageMetadata::MarkEvacuationCandidate () [inline]
Definition at line 42 of file page-metadata-inl.h.
                                           {
  DCHECK(!Chunk()->IsFlagSet(MemoryChunk::NEVER_EVACUATE));
  DCHECK_NULL(slot_set<OLD_TO_OLD>());
  DCHECK_NULL(typed_slot_set<OLD_TO_OLD>());
  Chunk()->SetFlagSlow(MemoryChunk::EVACUATION_CANDIDATE);
  reinterpret_cast<PagedSpace*>(owner())->free_list()->EvictFreeListItems(this);
}
References v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::DCHECK(), DCHECK_NULL, v8::internal::MemoryChunk::EVACUATION_CANDIDATE, v8::internal::MemoryChunk::NEVER_EVACUATE, v8::internal::MutablePageMetadata::owner(), and v8::internal::MemoryChunk::SetFlagSlow().
Referenced by v8::internal::MarkCompactCollector::AddEvacuationCandidate().
MarkNeverAllocateForTesting()
void v8::internal::PageMetadata::MarkNeverAllocateForTesting ()
Definition at line 78 of file page-metadata.cc.
                                               {
  MemoryChunk* chunk = Chunk();
  DCHECK(this->owner_identity() != NEW_SPACE);
  DCHECK(!chunk->IsFlagSet(MemoryChunk::NEVER_ALLOCATE_ON_PAGE));
  chunk->SetFlagSlow(MemoryChunk::NEVER_ALLOCATE_ON_PAGE);
  chunk->SetFlagSlow(MemoryChunk::NEVER_EVACUATE);
  reinterpret_cast<PagedSpace*>(owner())->free_list()->EvictFreeListItems(this);
}
References v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::DCHECK(), v8::internal::MemoryChunk::IsFlagSet(), v8::internal::MemoryChunk::NEVER_ALLOCATE_ON_PAGE, v8::internal::MemoryChunk::NEVER_EVACUATE, v8::internal::NEW_SPACE, v8::internal::MutablePageMetadata::owner(), v8::internal::MutablePageMetadata::owner_identity(), and v8::internal::MemoryChunk::SetFlagSlow().
next_page() [1/2]
PageMetadata* v8::internal::PageMetadata::next_page () [inline]
Definition at line 68 of file page-metadata.h.
                            {
    return static_cast<PageMetadata*>(list_node_.next());
  }
References v8::internal::MutablePageMetadata::list_node_.
Referenced by v8::internal::SemiSpace::AdvancePage(), v8::internal::SemiSpaceObjectIterator::Next(), v8::internal::anonymous_namespace{scavenger.cc}::QuarantinePinnedPages(), and v8::internal::SemiSpaceNewSpace::SetAgeMarkAndBelowAgeMarkPageFlags().
next_page() [2/2]
const PageMetadata* v8::internal::PageMetadata::next_page () const [inline]
Definition at line 75 of file page-metadata.h.
                                        {
    return static_cast<const PageMetadata*>(list_node_.next());
  }
References v8::internal::MutablePageMetadata::list_node_.
OnSamePage()
static bool v8::internal::PageMetadata::OnSamePage (Address address1, Address address2) [inline], [static]
Definition at line 51 of file page-metadata.h.
                                                             {
    return MemoryChunk::FromAddress(address1) ==
           MemoryChunk::FromAddress(address2);
  }
References v8::internal::MemoryChunk::FromAddress().
Referenced by v8::internal::PretenuringHandler::FindAllocationMemento().
prev_page() [1/2]
PageMetadata* v8::internal::PageMetadata::prev_page () [inline]
Definition at line 71 of file page-metadata.h.
                            {
    return static_cast<PageMetadata*>(list_node_.prev());
  }
References v8::internal::MutablePageMetadata::list_node_.
Referenced by v8::internal::SemiSpace::RemovePage().
prev_page() [2/2]
const PageMetadata* v8::internal::PageMetadata::prev_page () const [inline]
Definition at line 78 of file page-metadata.h.
                                        {
    return static_cast<const PageMetadata*>(list_node_.prev());
  }
References v8::internal::MutablePageMetadata::list_node_.
ReleaseFreeListCategories()
void v8::internal::PageMetadata::ReleaseFreeListCategories ()
Definition at line 40 of file page-metadata.cc.
                                             {
  if (categories_ != nullptr) {
    for (int i = kFirstCategory; i <= owner()->free_list()->last_category();
         i++) {
      if (categories_[i] != nullptr) {
        delete categories_[i];
        categories_[i] = nullptr;
      }
    }
    delete[] categories_;
    categories_ = nullptr;
  }
}
References v8::internal::MutablePageMetadata::categories_, v8::internal::Space::free_list(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kFirstCategory, v8::internal::FreeList::last_category(), and v8::internal::MutablePageMetadata::owner().
Referenced by v8::internal::MutablePageMetadata::ReleaseAllocatedMemoryNeededForWritableChunk(), and v8::internal::PagedSpaceBase::RemovePage().
Friends And Related Function Documentation
MemoryAllocator
friend class MemoryAllocator [friend]
Definition at line 127 of file page-metadata.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/page-metadata.h
/mnt/V8SourceCode/src/heap/page-metadata-inl.h
/mnt/V8SourceCode/src/heap/page-metadata.cc