v8::internal::wasm::LEBHelper Class Reference
#include <leb-helper.h>
Static Public Member Functions
static void write_u32v (uint8_t **dest, uint32_t val)
static void write_i32v (uint8_t **dest, int32_t val)
static void write_u64v (uint8_t **dest, uint64_t val)
static void write_i64v (uint8_t **dest, int64_t val)
static size_t sizeof_u32v (size_t val)
static size_t sizeof_i32v (int32_t val)
static size_t sizeof_u64v (uint64_t val)
static size_t sizeof_i64v (int64_t val)
Detailed Description
Definition at line 23 of file leb-helper.h.
Member Function Documentation
sizeof_i32v()
static size_t v8::internal::wasm::LEBHelper::sizeof_i32v (int32_t val) [inline], [static]
Definition at line 94 of file leb-helper.h.
                                         {
    size_t size = 1;
    if (val >= 0) {
      while (val >= 0x40) { // prevent sign extension.
        size++;
        val >>= 7;
      }
    } else {
      while ((val >> 6) != -1) {
        size++;
        val >>= 7;
      }
    }
    return size;
  }
References size().
Referenced by v8::internal::wasm::LocalDeclEncoder::Size().
sizeof_i64v()
static size_t v8::internal::wasm::LEBHelper::sizeof_i64v (int64_t val) [inline], [static]
Definition at line 121 of file leb-helper.h.
                                         {
    size_t size = 1;
    if (val >= 0) {
      while (val >= 0x40) { // prevent sign extension.
        size++;
        val >>= 7;
      }
    } else {
      while ((val >> 6) != -1) {
        size++;
        val >>= 7;
      }
    }
    return size;
  }
References size().
sizeof_u32v()
static size_t v8::internal::wasm::LEBHelper::sizeof_u32v (size_t val) [inline], [static]
Definition at line 84 of file leb-helper.h.
                                        {
    size_t size = 0;
    do {
      size++;
      val = val >> 7;
    } while (val > 0);
    return size;
  }
References size().
Referenced by v8::internal::wasm::LocalDeclEncoder::Size(), and v8::internal::wasm::WasmFunctionBuilder::WriteAsmWasmOffsetTable().
sizeof_u64v()
static size_t v8::internal::wasm::LEBHelper::sizeof_u64v (uint64_t val) [inline], [static]
Definition at line 111 of file leb-helper.h.
                                          {
    size_t size = 0;
    do {
      size++;
      val = val >> 7;
    } while (val > 0);
    return size;
  }
References size().
write_i32v()
static void v8::internal::wasm::LEBHelper::write_i32v (uint8_t ** dest, int32_t val) [inline], [static]
Definition at line 37 of file leb-helper.h.
                                                      {
    if (val >= 0) {
      while (val >= 0x40) { // prevent sign extension.
        *((*dest)++) = static_cast<uint8_t>(0x80 | (val & 0x7F));
        val >>= 7;
      }
      *((*dest)++) = static_cast<uint8_t>(val & 0xFF);
    } else {
      while ((val >> 6) != -1) {
        *((*dest)++) = static_cast<uint8_t>(0x80 | (val & 0x7F));
        val >>= 7;
      }
      *((*dest)++) = static_cast<uint8_t>(val & 0x7F);
    }
  }
Referenced by v8::internal::wasm::LocalDeclEncoder::Emit(), and v8::internal::wasm::ZoneBuffer::write_i32v().
write_i64v()
static void v8::internal::wasm::LEBHelper::write_i64v (uint8_t ** dest, int64_t val) [inline], [static]
Definition at line 65 of file leb-helper.h.
                                                      {
    if (val >= 0) {
      while (val >= 0x40) { // prevent sign extension.
        *((*dest)++) = static_cast<uint8_t>(0x80 | (val & 0x7F));
        val >>= 7;
      }
      *((*dest)++) = static_cast<uint8_t>(val & 0xFF);
    } else {
      while ((val >> 6) != -1) {
        *((*dest)++) = static_cast<uint8_t>(0x80 | (val & 0x7F));
        val >>= 7;
      }
      *((*dest)++) = static_cast<uint8_t>(val & 0x7F);
    }
  }
Referenced by v8::internal::wasm::ZoneBuffer::write_i64v().
write_u32v()
static void v8::internal::wasm::LEBHelper::write_u32v (uint8_t ** dest, uint32_t val) [inline], [static]
Definition at line 27 of file leb-helper.h.
                                                       {
    while (val >= 0x80) {
      *((*dest)++) = static_cast<uint8_t>(0x80 | (val & 0x7F));
      val >>= 7;
    }
    *((*dest)++) = static_cast<uint8_t>(val & 0x7F);
  }
Referenced by v8::internal::wasm::LocalDeclEncoder::Emit(), v8::internal::wasm::ZoneBuffer::write_size(), and v8::internal::wasm::ZoneBuffer::write_u32v().
write_u64v()
static void v8::internal::wasm::LEBHelper::write_u64v (uint8_t ** dest, uint64_t val) [inline], [static]
Definition at line 55 of file leb-helper.h.
                                                       {
    while (val >= 0x80) {
      *((*dest)++) = static_cast<uint8_t>(0x80 | (val & 0x7F));
      val >>= 7;
    }
    *((*dest)++) = static_cast<uint8_t>(val & 0x7F);
  }
Referenced by v8::internal::wasm::ZoneBuffer::write_u64v().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/leb-helper.h