v8::internal::compiler::TypedOptimization Class Reference
#include <typed-optimization.h>
Public Member Functions
TypedOptimization (Editor *editor, CompilationDependencies *dependencies, JSGraph *jsgraph, JSHeapBroker *broker)
~TypedOptimization () override
TypedOptimization (const TypedOptimization &)=delete
TypedOptimization & operator= (const TypedOptimization &)=delete
const char * reducer_name () const override
Reduction Reduce (Node *node) final
Private Member Functions
Reduction ReduceConvertReceiver (Node *node)
Reduction ReduceMaybeGrowFastElements (Node *node)
Reduction ReduceCheckBounds (Node *node)
Reduction ReduceCheckHeapObject (Node *node)
Reduction ReduceCheckMaps (Node *node)
Reduction ReduceCheckNumber (Node *node)
Reduction ReduceCheckNumberFitsInt32 (Node *node)
Reduction ReduceCheckString (Node *node)
Reduction ReduceCheckStringOrStringWrapper (Node *node)
Reduction ReduceCheckEqualsInternalizedString (Node *node)
Reduction ReduceCheckEqualsSymbol (Node *node)
Reduction ReduceLoadField (Node *node)
Reduction ReduceNumberFloor (Node *node)
Reduction ReduceNumberRoundop (Node *node)
Reduction ReduceNumberSilenceNaN (Node *node)
Reduction ReduceNumberToUint8Clamped (Node *node)
Reduction ReducePhi (Node *node)
Reduction ReduceReferenceEqual (Node *node)
Reduction ReduceStringComparison (Node *node)
Reduction ReduceStringLength (Node *node)
Reduction ReduceSameValue (Node *node)
Reduction ReduceSelect (Node *node)
Reduction ReduceSpeculativeToNumber (Node *node)
Reduction ReduceCheckNotTaggedHole (Node *node)
Reduction ReduceTypedArrayLength (Node *node)
Reduction ReduceTypeOf (Node *node)
Reduction ReduceToBoolean (Node *node)
Reduction ReduceSpeculativeNumberAdd (Node *node)
Reduction ReduceSpeculativeNumberMultiply (Node *node)
Reduction ReduceSpeculativeNumberPow (Node *node)
Reduction ReduceSpeculativeNumberBinop (Node *node)
Reduction ReduceSpeculativeNumberComparison (Node *node)
Reduction ReduceTransitionElementsKindOrCheckMap (Node *node)
Reduction TryReduceStringComparisonOfStringFromSingleCharCode (Node *comparison, Node *from_char_code, Type constant_type, bool inverted)
Reduction TryReduceStringComparisonOfStringFromSingleCharCodeToConstant (Node *comparison, StringRef string, bool inverted)
const Operator * NumberComparisonFor (const Operator *op)
Node * ConvertPlainPrimitiveToNumber (Node *node)
Reduction ReduceJSToNumberInput (Node *input)
SimplifiedOperatorBuilder * simplified () const
Factory * factory () const
TFGraph * graph () const
CompilationDependencies * dependencies () const
JSGraph * jsgraph () const
JSHeapBroker * broker () const
Private Attributes
CompilationDependencies *const dependencies_
JSGraph *const jsgraph_
JSHeapBroker * broker_
Type const true_type_
Type const false_type_
TypeCache const * type_cache_
Detailed Description
Definition at line 26 of file typed-optimization.h.
Constructor & Destructor Documentation
TypedOptimization() [1/2]
v8::internal::compiler::TypedOptimization::TypedOptimization (Editor * editor, CompilationDependencies * dependencies, JSGraph * jsgraph, JSHeapBroker * broker)
Definition at line 22 of file typed-optimization.cc.
    : AdvancedReducer(editor),
      dependencies_(dependencies),
      jsgraph_(jsgraph),
      broker_(broker),
      true_type_(Type::Constant(broker, broker->true_value(), graph()->zone())),
      false_type_(
          Type::Constant(broker, broker->false_value(), graph()->zone())),
      type_cache_(TypeCache::Get()) {}
 TypedOptimization()
v8::internal::compiler::TypedOptimization::~TypedOptimization () [override], [default]
TypedOptimization() [2/2]
v8::internal::compiler::TypedOptimization::TypedOptimization (const TypedOptimization &) [delete]
Member Function Documentation
broker()
JSHeapBroker* v8::internal::compiler::TypedOptimization::broker () const [inline], [private]
Definition at line 90 of file typed-optimization.h.
{ return broker_; }
Referenced by ReduceCheckMaps(), ReduceJSToNumberInput(), ReduceLoadField(), ReduceReferenceEqual(), ReduceStringLength(), ReduceTransitionElementsKindOrCheckMap(), ReduceTypedArrayLength(), ReduceTypeOf(), and TryReduceStringComparisonOfStringFromSingleCharCode().
ConvertPlainPrimitiveToNumber()
Node * v8::internal::compiler::TypedOptimization::ConvertPlainPrimitiveToNumber (Node * node) [private]
Definition at line 944 of file typed-optimization.cc.
                                                                 {
  DCHECK(NodeProperties::GetType(node).Is(Type::PlainPrimitive()));
  // Avoid inserting too many eager ToNumber() operations.
  Reduction const reduction = ReduceJSToNumberInput(node);
  if (reduction.Changed()) return reduction.replacement();
  if (NodeProperties::GetType(node).Is(Type::Number())) {
    return node;
  }
  return graph()->NewNode(simplified()->PlainPrimitiveToNumber(), node);
}
References v8::internal::compiler::Reduction::Changed(), v8::internal::DCHECK(), v8::internal::compiler::NodeProperties::GetType(), graph(), v8::internal::Is(), v8::internal::compiler::TFGraph::NewNode(), ReduceJSToNumberInput(), v8::internal::compiler::Reduction::replacement(), and simplified().
Referenced by ReduceSpeculativeNumberAdd(), and ReduceSpeculativeNumberBinop().
dependencies()
CompilationDependencies* v8::internal::compiler::TypedOptimization::dependencies () const [inline], [private]
Definition at line 88 of file typed-optimization.h.
{ return dependencies_; }
Referenced by ReduceCheckMaps(), ReduceLoadField(), and ReduceTransitionElementsKindOrCheckMap().
factory()
Factory * v8::internal::compiler::TypedOptimization::factory () const [private]
Definition at line 993 of file typed-optimization.cc.
                                          {
  return jsgraph()->isolate()->factory();
}
References v8::internal::Isolate::factory(), v8::internal::compiler::JSGraph::isolate(), and jsgraph().
graph()
TFGraph * v8::internal::compiler::TypedOptimization::graph () const [private]
Definition at line 997 of file typed-optimization.cc.
{ return jsgraph()->graph(); }
References v8::internal::compiler::MachineGraph::graph(), and jsgraph().
Referenced by ConvertPlainPrimitiveToNumber(), ReduceMaybeGrowFastElements(), ReduceNumberFloor(), ReducePhi(), ReduceSelect(), ReduceSpeculativeNumberAdd(), ReduceSpeculativeNumberBinop(), ReduceSpeculativeNumberComparison(), ReduceStringComparison(), ReduceToBoolean(), and TryReduceStringComparisonOfStringFromSingleCharCode().
jsgraph()
JSGraph* v8::internal::compiler::TypedOptimization::jsgraph () const [inline], [private]
Definition at line 89 of file typed-optimization.h.
{ return jsgraph_; }
Referenced by factory(), graph(), ReduceJSToNumberInput(), ReduceLoadField(), ReduceReferenceEqual(), ReduceSameValue(), ReduceStringComparison(), ReduceStringLength(), ReduceToBoolean(), ReduceTypedArrayLength(), ReduceTypeOf(), simplified(), TryReduceStringComparisonOfStringFromSingleCharCode(), and TryReduceStringComparisonOfStringFromSingleCharCodeToConstant().
NumberComparisonFor()
const Operator * v8::internal::compiler::TypedOptimization::NumberComparisonFor (const Operator * op) [private]
Definition at line 486 of file typed-optimization.cc.
                                                                         {
  switch (op->opcode()) {
    case IrOpcode::kStringEqual:
    case IrOpcode::kStringOrOddballStrictEqual:
      return simplified()->NumberEqual();
    case IrOpcode::kStringLessThan:
      return simplified()->NumberLessThan();
    case IrOpcode::kStringLessThanOrEqual:
      return simplified()->NumberLessThanOrEqual();
    default:
      break;
  }
  UNREACHABLE();
}
References v8::internal::compiler::SimplifiedOperatorBuilder::NumberEqual(), v8::internal::compiler::SimplifiedOperatorBuilder::NumberLessThan(), v8::internal::compiler::SimplifiedOperatorBuilder::NumberLessThanOrEqual(), v8::internal::compiler::Operator::opcode(), simplified(), and v8::internal::UNREACHABLE().
Referenced by ReduceStringComparison(), and TryReduceStringComparisonOfStringFromSingleCharCode().
operator=()
TypedOptimization& v8::internal::compiler::TypedOptimization::operator= (const TypedOptimization &) [delete]
Reduce()
Reduction v8::internal::compiler::TypedOptimization::Reduce (Node * node) [final]
Definition at line 36 of file typed-optimization.cc.
                                              {
  switch (node->opcode()) {
    case IrOpcode::kConvertReceiver:
      return ReduceConvertReceiver(node);
    case IrOpcode::kMaybeGrowFastElements:
      return ReduceMaybeGrowFastElements(node);
    case IrOpcode::kCheckHeapObject:
      return ReduceCheckHeapObject(node);
    case IrOpcode::kCheckBounds:
      return ReduceCheckBounds(node);
    case IrOpcode::kCheckNotTaggedHole:
      return ReduceCheckNotTaggedHole(node);
    case IrOpcode::kCheckMaps:
      return ReduceCheckMaps(node);
    case IrOpcode::kCheckNumber:
      return ReduceCheckNumber(node);
    case IrOpcode::kCheckNumberFitsInt32:
      return ReduceCheckNumberFitsInt32(node);
    case IrOpcode::kCheckString:
      return ReduceCheckString(node);
    case IrOpcode::kCheckStringOrStringWrapper:
      return ReduceCheckStringOrStringWrapper(node);
    case IrOpcode::kCheckEqualsInternalizedString:
      return ReduceCheckEqualsInternalizedString(node);
    case IrOpcode::kCheckEqualsSymbol:
      return ReduceCheckEqualsSymbol(node);
    case IrOpcode::kLoadField:
      return ReduceLoadField(node);
    case IrOpcode::kNumberCeil:
    case IrOpcode::kNumberRound:
    case IrOpcode::kNumberTrunc:
      return ReduceNumberRoundop(node);
    case IrOpcode::kNumberFloor:
      return ReduceNumberFloor(node);
    case IrOpcode::kNumberSilenceNaN:
      return ReduceNumberSilenceNaN(node);
    case IrOpcode::kNumberToUint8Clamped:
      return ReduceNumberToUint8Clamped(node);
    case IrOpcode::kPhi:
      return ReducePhi(node);
    case IrOpcode::kReferenceEqual:
      return ReduceReferenceEqual(node);
    case IrOpcode::kStringEqual:
    case IrOpcode::kStringLessThan:
    case IrOpcode::kStringLessThanOrEqual:
    case IrOpcode::kStringOrOddballStrictEqual:
      return ReduceStringComparison(node);
    case IrOpcode::kStringLength:
      return ReduceStringLength(node);
    case IrOpcode::kSameValue:
      return ReduceSameValue(node);
    case IrOpcode::kSelect:
      return ReduceSelect(node);
    case IrOpcode::kTypedArrayLength:
      return ReduceTypedArrayLength(node);
    case IrOpcode::kTypeOf:
      return ReduceTypeOf(node);
    case IrOpcode::kToBoolean:
      return ReduceToBoolean(node);
    case IrOpcode::kSpeculativeToNumber:
      return ReduceSpeculativeToNumber(node);
    case IrOpcode::kSpeculativeNumberAdd:
      return ReduceSpeculativeNumberAdd(node);
    case IrOpcode::kSpeculativeNumberSubtract:
    case IrOpcode::kSpeculativeNumberMultiply:
    case IrOpcode::kSpeculativeNumberPow:
    case IrOpcode::kSpeculativeNumberDivide:
    case IrOpcode::kSpeculativeNumberModulus:
      return ReduceSpeculativeNumberBinop(node);
    case IrOpcode::kSpeculativeNumberEqual:
    case IrOpcode::kSpeculativeNumberLessThan:
    case IrOpcode::kSpeculativeNumberLessThanOrEqual:
      return ReduceSpeculativeNumberComparison(node);
    case IrOpcode::kTransitionElementsKindOrCheckMap:
      return ReduceTransitionElementsKindOrCheckMap(node);
    default:
      break;
  }
  return NoChange();
}
References v8::internal::compiler::Node::opcode(), ReduceCheckBounds(), ReduceCheckEqualsInternalizedString(), ReduceCheckEqualsSymbol(), ReduceCheckHeapObject(), ReduceCheckMaps(), ReduceCheckNotTaggedHole(), ReduceCheckNumber(), ReduceCheckNumberFitsInt32(), ReduceCheckString(), ReduceCheckStringOrStringWrapper(), ReduceConvertReceiver(), ReduceLoadField(), ReduceMaybeGrowFastElements(), ReduceNumberFloor(), ReduceNumberRoundop(), ReduceNumberSilenceNaN(), ReduceNumberToUint8Clamped(), ReducePhi(), ReduceReferenceEqual(), ReduceSameValue(), ReduceSelect(), ReduceSpeculativeNumberAdd(), ReduceSpeculativeNumberBinop(), ReduceSpeculativeNumberComparison(), ReduceSpeculativeToNumber(), ReduceStringComparison(), ReduceStringLength(), ReduceToBoolean(), ReduceTransitionElementsKindOrCheckMap(), ReduceTypedArrayLength(), and ReduceTypeOf().
ReduceCheckBounds()
Reduction v8::internal::compiler::TypedOptimization::ReduceCheckBounds (Node * node) [private]
Definition at line 206 of file typed-optimization.cc.
                                                         {
  CheckBoundsParameters const& p = CheckBoundsParametersOf(node->op());
  Node* const input = NodeProperties::GetValueInput(node, 0);
  Type const input_type = NodeProperties::GetType(input);
  if (p.flags() & CheckBoundsFlag::kConvertStringAndMinusZero &&
      !input_type.Maybe(Type::String()) &&
      !input_type.Maybe(Type::MinusZero())) {
    NodeProperties::ChangeOp(
        node,
        simplified()->CheckBounds(
            p.check_parameters().feedback(),
            p.flags().without(CheckBoundsFlag::kConvertStringAndMinusZero)));
    return Changed(node);
  }
  return NoChange();
}
References v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::CheckBoundsParameters::check_parameters(), v8::internal::compiler::CheckBoundsParametersOf(), v8::internal::compiler::CheckParameters::feedback(), v8::internal::compiler::CheckBoundsParameters::flags(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::kConvertStringAndMinusZero, v8::internal::compiler::Type::Maybe(), v8::internal::compiler::Node::op(), simplified(), and v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::without().
Referenced by Reduce().
ReduceCheckEqualsInternalizedString()
Reduction v8::internal::compiler::TypedOptimization::ReduceCheckEqualsInternalizedString (Node * node) [private]
Definition at line 322 of file typed-optimization.cc.
                                                                           {
  Node* const exp = NodeProperties::GetValueInput(node, 0);
  Type const exp_type = NodeProperties::GetType(exp);
  Node* const val = NodeProperties::GetValueInput(node, 1);
  Type const val_type = NodeProperties::GetType(val);
  Node* const effect = NodeProperties::GetEffectInput(node);
  if (val_type.Is(exp_type)) return Replace(effect);
  // TODO(turbofan): Should we also try to optimize the
  // non-internalized String case for {val} here?
  return NoChange();
}
References v8::base::ieee754::exp(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::Type::Is(), and v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace().
Referenced by Reduce().
ReduceCheckEqualsSymbol()
Reduction v8::internal::compiler::TypedOptimization::ReduceCheckEqualsSymbol (Node * node) [private]
Definition at line 334 of file typed-optimization.cc.
                                                               {
  Node* const exp = NodeProperties::GetValueInput(node, 0);
  Type const exp_type = NodeProperties::GetType(exp);
  Node* const val = NodeProperties::GetValueInput(node, 1);
  Type const val_type = NodeProperties::GetType(val);
  Node* const effect = NodeProperties::GetEffectInput(node);
  if (val_type.Is(exp_type)) return Replace(effect);
  return NoChange();
}
References v8::base::ieee754::exp(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::Type::Is(), and v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace().
Referenced by Reduce().
ReduceCheckHeapObject()
Reduction v8::internal::compiler::TypedOptimization::ReduceCheckHeapObject (Node * node) [private]
Definition at line 166 of file typed-optimization.cc.
                                                             {
  Node* const input = NodeProperties::GetValueInput(node, 0);
  Type const input_type = NodeProperties::GetType(input);
  if (!input_type.Maybe(Type::SignedSmall())) {
    ReplaceWithValue(node, input);
    return Replace(input);
  }
  return NoChange();
}
References v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::Type::Maybe(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), and v8::internal::compiler::Type::SignedSmall().
Referenced by Reduce().
ReduceCheckMaps()
Reduction v8::internal::compiler::TypedOptimization::ReduceCheckMaps (Node * node) [private]
Definition at line 255 of file typed-optimization.cc.
                                                       {
  Node* const object = NodeProperties::GetValueInput(node, 0);
  Type const object_type = NodeProperties::GetType(object);
  Node* const effect = NodeProperties::GetEffectInput(node);
  OptionalMapRef object_map = GetStableMapFromObjectType(broker(), object_type);
  CheckMapsParameters p = CheckMapsParametersOf(node->op());
  if (CheckMapsHelper(object_map, p.maps(), dependencies())) {
    return Replace(effect);
  }
  return NoChange();
}
References broker(), v8::internal::compiler::anonymous_namespace{typed-optimization.cc}::CheckMapsHelper(), v8::internal::compiler::CheckMapsParametersOf(), dependencies(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::anonymous_namespace{typed-optimization.cc}::GetStableMapFromObjectType(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::CheckMapsParameters::maps(), v8::internal::compiler::Node::op(), and v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace().
Referenced by Reduce().
ReduceCheckNotTaggedHole()
Reduction v8::internal::compiler::TypedOptimization::ReduceCheckNotTaggedHole (Node * node) [private]
Definition at line 223 of file typed-optimization.cc.
                                                                {
  Node* const input = NodeProperties::GetValueInput(node, 0);
  Type const input_type = NodeProperties::GetType(input);
  if (!input_type.Maybe(Type::Hole())) {
    ReplaceWithValue(node, input);
    return Replace(input);
  }
  return NoChange();
}
References v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::Hole, v8::internal::compiler::Type::Maybe(), and v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace().
Referenced by Reduce().
ReduceCheckNumber()
Reduction v8::internal::compiler::TypedOptimization::ReduceCheckNumber (Node * node) [private]
Definition at line 282 of file typed-optimization.cc.
                                                         {
  Node* const input = NodeProperties::GetValueInput(node, 0);
  Type const input_type = NodeProperties::GetType(input);
  if (input_type.Is(Type::Number())) {
    ReplaceWithValue(node, input);
    return Replace(input);
  }
  return NoChange();
}
References v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::Type::Is(), and v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace().
Referenced by Reduce().
ReduceCheckNumberFitsInt32()
Reduction v8::internal::compiler::TypedOptimization::ReduceCheckNumberFitsInt32 (Node * node) [private]
Definition at line 292 of file typed-optimization.cc.
                                                                  {
  Node* const input = NodeProperties::GetValueInput(node, 0);
  Type const input_type = NodeProperties::GetType(input);
  if (input_type.Is(Type::Signed32())) {
    ReplaceWithValue(node, input);
    return Replace(input);
  }
  return NoChange();
}
References v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::Type::Is(), and v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace().
Referenced by Reduce().
ReduceCheckString()
Reduction v8::internal::compiler::TypedOptimization::ReduceCheckString (Node * node) [private]
Definition at line 302 of file typed-optimization.cc.
                                                         {
  Node* const input = NodeProperties::GetValueInput(node, 0);
  Type const input_type = NodeProperties::GetType(input);
  if (input_type.Is(Type::String())) {
    ReplaceWithValue(node, input);
    return Replace(input);
  }
  return NoChange();
}
References v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::Type::Is(), and v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace().
Referenced by Reduce().
ReduceCheckStringOrStringWrapper()
Reduction v8::internal::compiler::TypedOptimization::ReduceCheckStringOrStringWrapper (Node * node) [private]
Definition at line 312 of file typed-optimization.cc.
                                                                        {
  Node* const input = NodeProperties::GetValueInput(node, 0);
  Type const input_type = NodeProperties::GetType(input);
  if (input_type.Is(Type::StringOrStringWrapper())) {
    ReplaceWithValue(node, input);
    return Replace(input);
  }
  return NoChange();
}
References v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::Type::Is(), and v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace().
Referenced by Reduce().
ReduceConvertReceiver()
Reduction v8::internal::compiler::TypedOptimization::ReduceConvertReceiver (Node * node) [private]
Definition at line 152 of file typed-optimization.cc.
                                                             {
  Node* const value = NodeProperties::GetValueInput(node, 0);
  Type const value_type = NodeProperties::GetType(value);
  Node* const global_proxy = NodeProperties::GetValueInput(node, 2);
  if (value_type.Is(Type::Receiver())) {
    ReplaceWithValue(node, value);
    return Replace(value);
  } else if (value_type.Is(Type::NullOrUndefined())) {
    ReplaceWithValue(node, global_proxy);
    return Replace(global_proxy);
  }
  return NoChange();
}
References v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::value, and v8::internal::wasm::value_type().
Referenced by Reduce().
ReduceJSToNumberInput()
Reduction v8::internal::compiler::TypedOptimization::ReduceJSToNumberInput (Node * input) [private]
Definition at line 909 of file typed-optimization.cc.
                                                              {
  // Try constant-folding of JSToNumber with constant inputs.
  Type input_type = NodeProperties::GetType(input);
  if (input_type.Is(Type::String())) {
    HeapObjectMatcher m(input);
    if (m.HasResolvedValue() && m.Ref(broker()).IsString()) {
      StringRef input_value = m.Ref(broker()).AsString();
      std::optional<double> number = input_value.ToNumber(broker());
      if (!number.has_value()) return NoChange();
      return Replace(jsgraph()->ConstantNoHole(number.value()));
    }
  }
  if (input_type.IsHeapConstant()) {
    HeapObjectRef input_value = input_type.AsHeapConstant()->Ref();
    double value;
    if (input_value.OddballToNumber(broker()).To(&value)) {
      return Replace(jsgraph()->ConstantNoHole(value));
    }
  }
  if (input_type.Is(Type::Number())) {
    // JSToNumber(x:number) => x
    return Changed(input);
  }
  if (input_type.Is(Type::Undefined())) {
    // JSToNumber(undefined) => #NaN
    return Replace(jsgraph()->NaNConstant());
  }
  if (input_type.Is(Type::Null())) {
    // JSToNumber(null) => #0
    return Replace(jsgraph()->ZeroConstant());
  }
  return NoChange();
}
References v8::internal::compiler::Type::AsHeapConstant(), broker(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::compiler::Type::Is(), v8::internal::compiler::Type::IsHeapConstant(), jsgraph(), v8::internal::compiler::Null, v8::internal::compiler::HeapConstantType::Ref(), v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Ref(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::StringRef::ToNumber(), v8::internal::compiler::Undefined, and v8::internal::value.
Referenced by ConvertPlainPrimitiveToNumber().
ReduceLoadField()
Reduction v8::internal::compiler::TypedOptimization::ReduceLoadField (Node * node) [private]
Definition at line 344 of file typed-optimization.cc.
                                                       {
  Node* const object = NodeProperties::GetValueInput(node, 0);
  Type const object_type = NodeProperties::GetType(object);
  FieldAccess const& access = FieldAccessOf(node->op());
  if (access.base_is_tagged == kTaggedBase &&
      access.offset == HeapObject::kMapOffset) {
    // We can replace LoadField[Map](o) with map if is stable, and
    // o has type Constant(object) and map == object->map, and either
    // (1) map cannot transition further, or
    // (2) deoptimization is enabled and we can add a code dependency on the
    // stability of map (to guard the Constant type information).
    OptionalMapRef object_map =
        GetStableMapFromObjectType(broker(), object_type);
    if (object_map.has_value()) {
      dependencies()->DependOnStableMap(*object_map);
      Node* const value = jsgraph()->ConstantNoHole(*object_map, broker());
      ReplaceWithValue(node, value);
      return Replace(value);
    }
  }
  return NoChange();
}
References v8::internal::compiler::FieldAccess::base_is_tagged, broker(), v8::internal::compiler::JSGraph::ConstantNoHole(), dependencies(), v8::internal::compiler::CompilationDependencies::DependOnStableMap(), v8::internal::compiler::FieldAccessOf(), v8::internal::compiler::anonymous_namespace{typed-optimization.cc}::GetStableMapFromObjectType(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), jsgraph(), v8::internal::HeapObject::kMapOffset, v8::internal::compiler::kTaggedBase, v8::internal::compiler::FieldAccess::offset, v8::internal::compiler::Node::op(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), and v8::internal::value.
Referenced by Reduce().
ReduceMaybeGrowFastElements()
Reduction v8::internal::compiler::TypedOptimization::ReduceMaybeGrowFastElements (Node * node) [private]
Definition at line 176 of file typed-optimization.cc.
                                                                   {
  Node* const elements = NodeProperties::GetValueInput(node, 1);
  Node* const index = NodeProperties::GetValueInput(node, 2);
  Node* const length = NodeProperties::GetValueInput(node, 3);
  Node* const effect = NodeProperties::GetEffectInput(node);
  Node* const control = NodeProperties::GetControlInput(node);
  Type const index_type = NodeProperties::GetType(index);
  Type const length_type = NodeProperties::GetType(length);
  CHECK(index_type.Is(Type::Unsigned31()));
  CHECK(length_type.Is(Type::Unsigned31()));
  if (!index_type.IsNone() && !length_type.IsNone() &&
      index_type.Max() < length_type.Min()) {
    if (v8_flags.turbo_typer_hardening) {
      Node* check_bounds = graph()->NewNode(
          simplified()->CheckBounds(FeedbackSource{},
                                    CheckBoundsFlag::kAbortOnOutOfBounds),
          index, length, effect, control);
      ReplaceWithValue(node, elements, check_bounds);
      return Replace(check_bounds);
    } else {
      RelaxEffectsAndControls(node);
      return Replace(elements);
    }
  }
  return NoChange();
}
References CHECK, v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::index, v8::internal::compiler::Type::Is(), v8::internal::compiler::Type::IsNone(), v8::internal::compiler::kAbortOnOutOfBounds, v8::internal::length, v8::internal::compiler::Type::Max(), v8::internal::compiler::Type::Min(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), simplified(), and v8::internal::v8_flags.
Referenced by Reduce().
ReduceNumberFloor()
Reduction v8::internal::compiler::TypedOptimization::ReduceNumberFloor (Node * node) [private]
Definition at line 367 of file typed-optimization.cc.
                                                         {
  Node* const input = NodeProperties::GetValueInput(node, 0);
  Type const input_type = NodeProperties::GetType(input);
  if (input_type.Is(type_cache_->kIntegerOrMinusZeroOrNaN)) {
    return Replace(input);
  }
  if (input_type.Is(Type::PlainNumber()) &&
      (input->opcode() == IrOpcode::kNumberDivide ||
       input->opcode() == IrOpcode::kSpeculativeNumberDivide)) {
    Node* const lhs = NodeProperties::GetValueInput(input, 0);
    Type const lhs_type = NodeProperties::GetType(lhs);
    Node* const rhs = NodeProperties::GetValueInput(input, 1);
    Type const rhs_type = NodeProperties::GetType(rhs);
    if (lhs_type.IsNone() || rhs_type.IsNone()) return NoChange();
    if (lhs_type.Is(Type::Unsigned32()) && rhs_type.Is(Type::Unsigned32())) {
      // We can replace
      //
      // NumberFloor(NumberDivide(lhs: unsigned32,
      // rhs: unsigned32)): plain-number
      //
      // with
      //
      // Unsigned32Divide(lhs, rhs)
      //
      // and have the new node typed to [0...lhs.Max],
      // as the truncated result must be lower than {lhs}'s maximum
      // value (note that {rhs} cannot be less than 1 due to the
      // plain-number type constraint on the {node}).
      node = graph()->NewNode(simplified()->Unsigned32Divide(), lhs, rhs);
      return Replace(node);
    }
  }
  return NoChange();
}
References v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::Type::Is(), v8::internal::compiler::Type::IsNone(), v8::internal::compiler::TypeCache::kIntegerOrMinusZeroOrNaN, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), simplified(), and type_cache_.
Referenced by Reduce().
ReduceNumberRoundop()
Reduction v8::internal::compiler::TypedOptimization::ReduceNumberRoundop (Node * node) [private]
Definition at line 402 of file typed-optimization.cc.
                                                           {
  Node* const input = NodeProperties::GetValueInput(node, 0);
  Type const input_type = NodeProperties::GetType(input);
  if (input_type.Is(type_cache_->kIntegerOrMinusZeroOrNaN)) {
    return Replace(input);
  }
  return NoChange();
}
References v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::Type::Is(), v8::internal::compiler::TypeCache::kIntegerOrMinusZeroOrNaN, v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), and type_cache_.
Referenced by Reduce().
ReduceNumberSilenceNaN()
Reduction v8::internal::compiler::TypedOptimization::ReduceNumberSilenceNaN (Node * node) [private]
Definition at line 411 of file typed-optimization.cc.
                                                              {
  Node* const input = NodeProperties::GetValueInput(node, 0);
  Type const input_type = NodeProperties::GetType(input);
  if (input_type.Is(Type::OrderedNumber())) {
    return Replace(input);
  }
  return NoChange();
}
References v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::Type::Is(), and v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace().
Referenced by Reduce().
ReduceNumberToUint8Clamped()
Reduction v8::internal::compiler::TypedOptimization::ReduceNumberToUint8Clamped (Node * node) [private]
Definition at line 420 of file typed-optimization.cc.
                                                                  {
  Node* const input = NodeProperties::GetValueInput(node, 0);
  Type const input_type = NodeProperties::GetType(input);
  if (input_type.Is(type_cache_->kUint8)) {
    return Replace(input);
  }
  return NoChange();
}
References v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::Type::Is(), v8::internal::compiler::TypeCache::kUint8, v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), and type_cache_.
Referenced by Reduce().
ReducePhi()
Reduction v8::internal::compiler::TypedOptimization::ReducePhi (Node * node) [private]
Definition at line 429 of file typed-optimization.cc.
                                                 {
  // Try to narrow the type of the Phi {node}, which might be more precise now
  // after lowering based on types, i.e. a SpeculativeNumberAdd has a more
  // precise type than the JSAdd that was in the graph when the Typer was run.
  DCHECK_EQ(IrOpcode::kPhi, node->opcode());
  // Prevent new types from being propagated through loop-related Phis for now.
  // This is to avoid slow convergence of type narrowing when we learn very
  // precise information about loop variables.
  if (NodeProperties::GetControlInput(node, 0)->opcode() == IrOpcode::kLoop) {
    return NoChange();
  }
  int arity = node->op()->ValueInputCount();
  Type type = NodeProperties::GetType(node->InputAt(0));
  for (int i = 1; i < arity; ++i) {
    type = Type::Union(type, NodeProperties::GetType(node->InputAt(i)),
                       graph()->zone());
  }
  Type const node_type = NodeProperties::GetType(node);
  if (!node_type.Is(type)) {
    type = Type::Intersect(node_type, type, graph()->zone());
    NodeProperties::SetType(node, type);
    return Changed(node);
  }
  return NoChange();
}
References DCHECK_EQ, v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetType(), graph(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Type::Intersect(), v8::internal::compiler::Type::Is(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::NodeProperties::SetType(), v8::internal::tracing::type, v8::internal::compiler::Type::Union(), and v8::internal::compiler::Operator::ValueInputCount().
Referenced by Reduce().
reducer_name()
const char* v8::internal::compiler::TypedOptimization::reducer_name () const [inline], [override]
Definition at line 35 of file typed-optimization.h.
{ return "TypedOptimization"; }
ReduceReferenceEqual()
Reduction v8::internal::compiler::TypedOptimization::ReduceReferenceEqual (Node * node) [private]
Definition at line 455 of file typed-optimization.cc.
                                                            {
  DCHECK_EQ(IrOpcode::kReferenceEqual, node->opcode());
  Node* const lhs = NodeProperties::GetValueInput(node, 0);
  Node* const rhs = NodeProperties::GetValueInput(node, 1);
  Type const lhs_type = NodeProperties::GetType(lhs);
  Type const rhs_type = NodeProperties::GetType(rhs);
  if (!lhs_type.Maybe(rhs_type)) {
    Node* replacement = jsgraph()->FalseConstant();
    // Make sure we do not widen the type.
    if (NodeProperties::GetType(replacement)
            .Is(NodeProperties::GetType(node))) {
      return Replace(jsgraph()->FalseConstant());
    }
  }
  if (rhs_type.Is(Type::Boolean()) && rhs_type.IsHeapConstant() &&
      lhs_type.Is(Type::Boolean())) {
    std::optional<bool> maybe_result =
        rhs_type.AsHeapConstant()->Ref().TryGetBooleanValue(broker());
    if (maybe_result.has_value()) {
      if (maybe_result.value()) {
        return Replace(node->InputAt(0));
      } else {
        node->TrimInputCount(1);
        NodeProperties::ChangeOp(node, simplified()->BooleanNot());
        return Changed(node);
      }
    }
  }
  return NoChange();
}
References v8::internal::compiler::Type::AsHeapConstant(), broker(), v8::internal::compiler::NodeProperties::ChangeOp(), DCHECK_EQ, v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::Node::InputAt(), v8::internal::Is(), v8::internal::compiler::Type::Is(), v8::internal::compiler::Type::IsHeapConstant(), jsgraph(), v8::internal::compiler::Type::Maybe(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::HeapConstantType::Ref(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), simplified(), and v8::internal::compiler::Node::TrimInputCount().
Referenced by Reduce().
ReduceSameValue()
Reduction v8::internal::compiler::TypedOptimization::ReduceSameValue (Node * node) [private]
Definition at line 656 of file typed-optimization.cc.
                                                       {
  DCHECK_EQ(IrOpcode::kSameValue, node->opcode());
  Node* const lhs = NodeProperties::GetValueInput(node, 0);
  Node* const rhs = NodeProperties::GetValueInput(node, 1);
  Type const lhs_type = NodeProperties::GetType(lhs);
  Type const rhs_type = NodeProperties::GetType(rhs);
  if (ResolveSameValueRenames(lhs) == ResolveSameValueRenames(rhs)) {
    if (NodeProperties::GetType(node).IsNone()) {
      return NoChange();
    }
    // SameValue(x,x) => #true
    return Replace(jsgraph()->TrueConstant());
  } else if (lhs_type.Is(Type::Unique()) && rhs_type.Is(Type::Unique())) {
    // SameValue(x:unique,y:unique) => ReferenceEqual(x,y)
    NodeProperties::ChangeOp(node, simplified()->ReferenceEqual());
    return Changed(node);
  } else if (lhs_type.Is(Type::String()) && rhs_type.Is(Type::String())) {
    // SameValue(x:string,y:string) => StringEqual(x,y)
    NodeProperties::ChangeOp(node, simplified()->StringEqual());
    return Changed(node);
  } else if (lhs_type.Is(Type::MinusZero())) {
    // SameValue(x:minus-zero,y) => ObjectIsMinusZero(y)
    node->RemoveInput(0);
    NodeProperties::ChangeOp(node, simplified()->ObjectIsMinusZero());
    return Changed(node);
  } else if (rhs_type.Is(Type::MinusZero())) {
    // SameValue(x,y:minus-zero) => ObjectIsMinusZero(x)
    node->RemoveInput(1);
    NodeProperties::ChangeOp(node, simplified()->ObjectIsMinusZero());
    return Changed(node);
  } else if (lhs_type.Is(Type::NaN())) {
    // SameValue(x:nan,y) => ObjectIsNaN(y)
    node->RemoveInput(0);
    NodeProperties::ChangeOp(node, simplified()->ObjectIsNaN());
    return Changed(node);
  } else if (rhs_type.Is(Type::NaN())) {
    // SameValue(x,y:nan) => ObjectIsNaN(x)
    node->RemoveInput(1);
    NodeProperties::ChangeOp(node, simplified()->ObjectIsNaN());
    return Changed(node);
  } else if (lhs_type.Is(Type::PlainNumber()) &&
             rhs_type.Is(Type::PlainNumber())) {
    // SameValue(x:plain-number,y:plain-number) => NumberEqual(x,y)
    NodeProperties::ChangeOp(node, simplified()->NumberEqual());
    return Changed(node);
  }
  return NoChange();
}
References v8::internal::compiler::NodeProperties::ChangeOp(), DCHECK_EQ, v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::Type::Is(), v8::internal::IsNone(), jsgraph(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::Node::RemoveInput(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::anonymous_namespace{typed-optimization.cc}::ResolveSameValueRenames(), and simplified().
Referenced by Reduce().
ReduceSelect()
Reduction v8::internal::compiler::TypedOptimization::ReduceSelect (Node * node) [private]
Definition at line 705 of file typed-optimization.cc.
                                                    {
  DCHECK_EQ(IrOpcode::kSelect, node->opcode());
  Node* const condition = NodeProperties::GetValueInput(node, 0);
  Type const condition_type = NodeProperties::GetType(condition);
  Node* const vtrue = NodeProperties::GetValueInput(node, 1);
  Type const vtrue_type = NodeProperties::GetType(vtrue);
  Node* const vfalse = NodeProperties::GetValueInput(node, 2);
  Type const vfalse_type = NodeProperties::GetType(vfalse);
  if (condition_type.Is(true_type_)) {
    // Select(condition:true, vtrue, vfalse) => vtrue
    return Replace(vtrue);
  }
  if (condition_type.Is(false_type_)) {
    // Select(condition:false, vtrue, vfalse) => vfalse
    return Replace(vfalse);
  }
  if (vtrue_type.Is(true_type_) && vfalse_type.Is(false_type_)) {
    // Select(condition, vtrue:true, vfalse:false) => condition
    return Replace(condition);
  }
  if (vtrue_type.Is(false_type_) && vfalse_type.Is(true_type_)) {
    // Select(condition, vtrue:false, vfalse:true) => BooleanNot(condition)
    node->TrimInputCount(1);
    NodeProperties::ChangeOp(node, simplified()->BooleanNot());
    return Changed(node);
  }
  // Try to narrow the type of the Select {node}, which might be more precise
  // now after lowering based on types.
  Type type = Type::Union(vtrue_type, vfalse_type, graph()->zone());
  Type const node_type = NodeProperties::GetType(node);
  if (!node_type.Is(type)) {
    type = Type::Intersect(node_type, type, graph()->zone());
    NodeProperties::SetType(node, type);
    return Changed(node);
  }
  return NoChange();
}
References v8::internal::compiler::NodeProperties::ChangeOp(), DCHECK_EQ, false_type_, v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::Type::Intersect(), v8::internal::compiler::Type::Is(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::NodeProperties::SetType(), simplified(), v8::internal::compiler::Node::TrimInputCount(), true_type_, v8::internal::tracing::type, and v8::internal::compiler::Type::Union().
Referenced by Reduce().
ReduceSpeculativeNumberAdd()
Reduction v8::internal::compiler::TypedOptimization::ReduceSpeculativeNumberAdd (Node * node) [private]
Definition at line 887 of file typed-optimization.cc.
                                                                  {
  Node* const lhs = NodeProperties::GetValueInput(node, 0);
  Node* const rhs = NodeProperties::GetValueInput(node, 1);
  Type const lhs_type = NodeProperties::GetType(lhs);
  Type const rhs_type = NodeProperties::GetType(rhs);
  NumberOperationHint hint = NumberOperationHintOf(node->op());
  if ((hint == NumberOperationHint::kNumber ||
       hint == NumberOperationHint::kNumberOrOddball) &&
      BothAre(lhs_type, rhs_type, Type::PlainPrimitive()) &&
      NeitherCanBe(lhs_type, rhs_type, Type::StringOrReceiver())) {
    // SpeculativeNumberAdd(x:-string, y:-string) =>
    // NumberAdd(ToNumber(x), ToNumber(y))
    Node* const toNum_lhs = ConvertPlainPrimitiveToNumber(lhs);
    Node* const toNum_rhs = ConvertPlainPrimitiveToNumber(rhs);
    Node* const value =
        graph()->NewNode(simplified()->NumberAdd(), toNum_lhs, toNum_rhs);
    ReplaceWithValue(node, value);
    return Replace(value);
  }
  return NoChange();
}
References v8::internal::compiler::anonymous_namespace{typed-optimization.cc}::BothAre(), ConvertPlainPrimitiveToNumber(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::kNumber, v8::internal::compiler::kNumberOrOddball, v8::internal::compiler::anonymous_namespace{typed-optimization.cc}::NeitherCanBe(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::NumberOperationHintOf(), v8::internal::compiler::Node::op(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), simplified(), and v8::internal::value.
Referenced by Reduce().
ReduceSpeculativeNumberBinop()
Reduction v8::internal::compiler::TypedOptimization::ReduceSpeculativeNumberBinop (Node * node) [private]
Definition at line 955 of file typed-optimization.cc.
                                                                    {
  Node* const lhs = NodeProperties::GetValueInput(node, 0);
  Node* const rhs = NodeProperties::GetValueInput(node, 1);
  Type const lhs_type = NodeProperties::GetType(lhs);
  Type const rhs_type = NodeProperties::GetType(rhs);
  NumberOperationHint hint = NumberOperationHintOf(node->op());
  if ((hint == NumberOperationHint::kNumber ||
       hint == NumberOperationHint::kNumberOrOddball) &&
      BothAre(lhs_type, rhs_type, Type::NumberOrOddball())) {
    // We intentionally do this only in the Number and NumberOrOddball hint case
    // because simplified lowering of these speculative ops may do some clever
    // reductions in the other cases.
    Node* const toNum_lhs = ConvertPlainPrimitiveToNumber(lhs);
    Node* const toNum_rhs = ConvertPlainPrimitiveToNumber(rhs);
    Node* const value = graph()->NewNode(
        NumberOpFromSpeculativeNumberOp(simplified(), node->op()), toNum_lhs,
        toNum_rhs);
    ReplaceWithValue(node, value);
    return Replace(value);
  }
  return NoChange();
}
References v8::internal::compiler::anonymous_namespace{typed-optimization.cc}::BothAre(), ConvertPlainPrimitiveToNumber(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::kNumber, v8::internal::compiler::kNumberOrOddball, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::NumberOperationHintOf(), v8::internal::compiler::anonymous_namespace{typed-optimization.cc}::NumberOpFromSpeculativeNumberOp(), v8::internal::compiler::Node::op(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), simplified(), and v8::internal::value.
Referenced by Reduce().
ReduceSpeculativeNumberComparison()
Reduction v8::internal::compiler::TypedOptimization::ReduceSpeculativeNumberComparison (Node * node) [private]
Definition at line 978 of file typed-optimization.cc.
                                                                         {
  Node* const lhs = NodeProperties::GetValueInput(node, 0);
  Node* const rhs = NodeProperties::GetValueInput(node, 1);
  Type const lhs_type = NodeProperties::GetType(lhs);
  Type const rhs_type = NodeProperties::GetType(rhs);
  if (BothAre(lhs_type, rhs_type, Type::Signed32()) ||
      BothAre(lhs_type, rhs_type, Type::Unsigned32())) {
    Node* const value = graph()->NewNode(
        NumberOpFromSpeculativeNumberOp(simplified(), node->op()), lhs, rhs);
    ReplaceWithValue(node, value);
    return Replace(value);
  }
  return NoChange();
}
References v8::internal::compiler::anonymous_namespace{typed-optimization.cc}::BothAre(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::anonymous_namespace{typed-optimization.cc}::NumberOpFromSpeculativeNumberOp(), v8::internal::compiler::Node::op(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), simplified(), and v8::internal::value.
Referenced by Reduce().
ReduceSpeculativeNumberMultiply()
Reduction v8::internal::compiler::TypedOptimization::ReduceSpeculativeNumberMultiply (Node * node) [private]
ReduceSpeculativeNumberPow()
Reduction v8::internal::compiler::TypedOptimization::ReduceSpeculativeNumberPow (Node * node) [private]
ReduceSpeculativeToNumber()
Reduction v8::internal::compiler::TypedOptimization::ReduceSpeculativeToNumber (Node * node) [private]
Definition at line 743 of file typed-optimization.cc.
                                                                 {
  DCHECK_EQ(IrOpcode::kSpeculativeToNumber, node->opcode());
  Node* const input = NodeProperties::GetValueInput(node, 0);
  Type const input_type = NodeProperties::GetType(input);
  if (input_type.Is(Type::Number())) {
    // SpeculativeToNumber(x:number) => x
    ReplaceWithValue(node, input);
    return Replace(input);
  }
  return NoChange();
}
References DCHECK_EQ, v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::Type::Is(), v8::internal::compiler::Node::opcode(), and v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace().
Referenced by Reduce().
ReduceStringComparison()
Reduction v8::internal::compiler::TypedOptimization::ReduceStringComparison (Node * node) [private]
Definition at line 583 of file typed-optimization.cc.
                                                              {
  DCHECK(IrOpcode::kStringEqual == node->opcode() ||
         IrOpcode::kStringLessThan == node->opcode() ||
         IrOpcode::kStringLessThanOrEqual == node->opcode() ||
         IrOpcode::kStringOrOddballStrictEqual == node->opcode());
  Node* const lhs = NodeProperties::GetValueInput(node, 0);
  Node* const rhs = NodeProperties::GetValueInput(node, 1);
  Type lhs_type = NodeProperties::GetType(lhs);
  Type rhs_type = NodeProperties::GetType(rhs);
  if (lhs->opcode() == IrOpcode::kStringFromSingleCharCode) {
    if (rhs->opcode() == IrOpcode::kStringFromSingleCharCode) {
      Node* left = NodeProperties::GetValueInput(lhs, 0);
      Node* right = NodeProperties::GetValueInput(rhs, 0);
      Type left_type = NodeProperties::GetType(left);
      Type right_type = NodeProperties::GetType(right);
      if (!left_type.Is(type_cache_->kUint16)) {
        // Convert to signed int32 to satisfy type of {NumberBitwiseAnd}.
        left = graph()->NewNode(simplified()->NumberToInt32(), left);
        left = graph()->NewNode(
            simplified()->NumberBitwiseAnd(), left,
            jsgraph()->ConstantNoHole(std::numeric_limits<uint16_t>::max()));
      }
      if (!right_type.Is(type_cache_->kUint16)) {
        // Convert to signed int32 to satisfy type of {NumberBitwiseAnd}.
        right = graph()->NewNode(simplified()->NumberToInt32(), right);
        right = graph()->NewNode(
            simplified()->NumberBitwiseAnd(), right,
            jsgraph()->ConstantNoHole(std::numeric_limits<uint16_t>::max()));
      }
      Node* equal =
          graph()->NewNode(NumberComparisonFor(node->op()), left, right);
      ReplaceWithValue(node, equal);
      return Replace(equal);
    } else {
      return TryReduceStringComparisonOfStringFromSingleCharCode(
          node, lhs, rhs_type, false);
    }
  } else if (rhs->opcode() == IrOpcode::kStringFromSingleCharCode) {
    return TryReduceStringComparisonOfStringFromSingleCharCode(node, rhs,
                                                               lhs_type, true);
  }
  return NoChange();
}
References v8::internal::DCHECK(), v8::internal::equal, v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::Type::Is(), jsgraph(), v8::internal::compiler::TypeCache::kUint16, v8::internal::compiler::TFGraph::NewNode(), NumberComparisonFor(), v8::internal::NumberToInt32(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), simplified(), TryReduceStringComparisonOfStringFromSingleCharCode(), and type_cache_.
Referenced by Reduce().
ReduceStringLength()
Reduction v8::internal::compiler::TypedOptimization::ReduceStringLength (Node * node) [private]
Definition at line 627 of file typed-optimization.cc.
                                                          {
  DCHECK_EQ(IrOpcode::kStringLength, node->opcode());
  Node* const input = NodeProperties::GetValueInput(node, 0);
  switch (input->opcode()) {
    case IrOpcode::kHeapConstant: {
      // Constant-fold the String::length of the {input}.
      HeapObjectMatcher m(input);
      if (m.Ref(broker()).IsString()) {
        uint32_t const length = m.Ref(broker()).AsString().length();
        Node* value = jsgraph()->ConstantNoHole(length);
        return Replace(value);
      }
      break;
    }
    case IrOpcode::kStringConcat: {
      // The first value input to the {input} is the resulting length.
      return Replace(input->InputAt(0));
    }
    case IrOpcode::kStringFromSingleCharCode: {
      // Note that this isn't valid for StringFromCodePointAt, since it the
      // string it returns can be 1 or 2 characters long.
      return Replace(jsgraph()->ConstantNoHole(1));
    }
    default:
      break;
  }
  return NoChange();
}
References broker(), v8::internal::compiler::JSGraph::ConstantNoHole(), DCHECK_EQ, v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::Node::InputAt(), jsgraph(), v8::internal::length, v8::internal::compiler::Node::opcode(), v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Ref(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), and v8::internal::value.
Referenced by Reduce().
ReduceToBoolean()
Reduction v8::internal::compiler::TypedOptimization::ReduceToBoolean (Node * node) [private]
Definition at line 804 of file typed-optimization.cc.
                                                       {
  Node* const input = node->InputAt(0);
  Type const input_type = NodeProperties::GetType(input);
  if (input_type.Is(Type::Boolean())) {
    // ToBoolean(x:boolean) => x
    return Replace(input);
  } else if (input_type.Is(Type::OrderedNumber())) {
    // SToBoolean(x:ordered-number) => BooleanNot(NumberEqual(x,#0))
    node->ReplaceInput(0, graph()->NewNode(simplified()->NumberEqual(), input,
                                           jsgraph()->ZeroConstant()));
    node->TrimInputCount(1);
    NodeProperties::ChangeOp(node, simplified()->BooleanNot());
    return Changed(node);
  } else if (input_type.Is(Type::Number())) {
    // ToBoolean(x:number) => NumberToBoolean(x)
    node->TrimInputCount(1);
    NodeProperties::ChangeOp(node, simplified()->NumberToBoolean());
    return Changed(node);
  } else if (input_type.Is(Type::DetectableReceiverOrNull())) {
    // ToBoolean(x:detectable receiver \/ null)
    // => BooleanNot(ReferenceEqual(x,#null))
    node->ReplaceInput(0, graph()->NewNode(simplified()->ReferenceEqual(),
                                           input, jsgraph()->NullConstant()));
    node->TrimInputCount(1);
    NodeProperties::ChangeOp(node, simplified()->BooleanNot());
    return Changed(node);
  } else if (input_type.Is(Type::ReceiverOrNullOrUndefined())) {
    // ToBoolean(x:receiver \/ null \/ undefined)
    // => BooleanNot(ObjectIsUndetectable(x))
    node->ReplaceInput(
        0, graph()->NewNode(simplified()->ObjectIsUndetectable(), input));
    node->TrimInputCount(1);
    NodeProperties::ChangeOp(node, simplified()->BooleanNot());
    return Changed(node);
  } else if (input_type.Is(Type::String())) {
    // ToBoolean(x:string) => BooleanNot(ReferenceEqual(x,""))
    node->ReplaceInput(0,
                       graph()->NewNode(simplified()->ReferenceEqual(), input,
                                        jsgraph()->EmptyStringConstant()));
    node->TrimInputCount(1);
    NodeProperties::ChangeOp(node, simplified()->BooleanNot());
    return Changed(node);
  }
  return NoChange();
}
References v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::NodeProperties::GetType(), graph(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Type::Is(), jsgraph(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::Node::ReplaceInput(), simplified(), and v8::internal::compiler::Node::TrimInputCount().
Referenced by Reduce().
ReduceTransitionElementsKindOrCheckMap()
Reduction v8::internal::compiler::TypedOptimization::ReduceTransitionElementsKindOrCheckMap (Node * node) [private]
Definition at line 267 of file typed-optimization.cc.
                {
  Node* const object = NodeProperties::GetValueInput(node, 0);
  Type const object_type = NodeProperties::GetType(object);
  Node* const effect = NodeProperties::GetEffectInput(node);
  OptionalMapRef object_map = GetStableMapFromObjectType(broker(), object_type);
  ElementsTransitionWithMultipleSources p =
      ElementsTransitionWithMultipleSourcesOf(node->op());
  if (CheckMapsHelper(object_map, ZoneRefSet<Map>(p.target()),
                      dependencies())) {
    return Replace(effect);
  }
  return NoChange();
}
References broker(), v8::internal::compiler::anonymous_namespace{typed-optimization.cc}::CheckMapsHelper(), dependencies(), v8::internal::compiler::ElementsTransitionWithMultipleSourcesOf(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::anonymous_namespace{typed-optimization.cc}::GetStableMapFromObjectType(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::Node::op(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), and v8::internal::compiler::ElementsTransitionWithMultipleSources::target().
Referenced by Reduce().
ReduceTypedArrayLength()
Reduction v8::internal::compiler::TypedOptimization::ReduceTypedArrayLength (Node * node) [private]
Definition at line 786 of file typed-optimization.cc.
                                                              {
  DCHECK_EQ(IrOpcode::kTypedArrayLength, node->opcode());
  Node* const input = NodeProperties::GetValueInput(node, 0);
  // Constant-fold the length of the {input} if possible.
  HeapObjectMatcher m(input);
  if (m.HasResolvedValue() && m.Ref(broker()).IsJSTypedArray()) {
    JSTypedArrayRef typed_array = m.Ref(broker()).AsJSTypedArray();
    size_t byte_length = typed_array.byte_length();
    ElementsKind elements_kind = typed_array.elements_kind(broker());
    if (!IsRabGsabTypedArrayElementsKind(elements_kind)) {
      Node* value = jsgraph()->ConstantNoHole(
          byte_length >> ElementsKindToShiftSize(elements_kind));
      return Replace(value);
    }
  }
  return NoChange();
}
References broker(), v8::internal::compiler::JSTypedArrayRef::byte_length(), v8::internal::compiler::JSGraph::ConstantNoHole(), DCHECK_EQ, v8::internal::compiler::JSTypedArrayRef::elements_kind(), v8::internal::ElementsKindToShiftSize(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::IsRabGsabTypedArrayElementsKind(), jsgraph(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Ref(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), and v8::internal::value.
Referenced by Reduce().
ReduceTypeOf()
Reduction v8::internal::compiler::TypedOptimization::ReduceTypeOf (Node * node) [private]
Definition at line 755 of file typed-optimization.cc.
                                                    {
  Node* const input = node->InputAt(0);
  Type const type = NodeProperties::GetType(input);
  if (type.Is(Type::Boolean())) {
    return Replace(
        jsgraph()->ConstantNoHole(broker()->boolean_string(), broker()));
  } else if (type.Is(Type::Number())) {
    return Replace(
        jsgraph()->ConstantNoHole(broker()->number_string(), broker()));
  } else if (type.Is(Type::String())) {
    return Replace(
        jsgraph()->ConstantNoHole(broker()->string_string(), broker()));
  } else if (type.Is(Type::BigInt())) {
    return Replace(
        jsgraph()->ConstantNoHole(broker()->bigint_string(), broker()));
  } else if (type.Is(Type::Symbol())) {
    return Replace(
        jsgraph()->ConstantNoHole(broker()->symbol_string(), broker()));
  } else if (type.Is(Type::OtherUndetectableOrUndefined())) {
    return Replace(
        jsgraph()->ConstantNoHole(broker()->undefined_string(), broker()));
  } else if (type.Is(Type::NonCallableOrNull())) {
    return Replace(
        jsgraph()->ConstantNoHole(broker()->object_string(), broker()));
  } else if (type.Is(Type::Function())) {
    return Replace(
        jsgraph()->ConstantNoHole(broker()->function_string(), broker()));
  }
  return NoChange();
}
References broker(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::Node::InputAt(), jsgraph(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), and v8::internal::tracing::type.
Referenced by Reduce().
simplified()
SimplifiedOperatorBuilder * v8::internal::compiler::TypedOptimization::simplified () const [private]
Definition at line 999 of file typed-optimization.cc.
                                                               {
  return jsgraph()->simplified();
}
References jsgraph(), and v8::internal::compiler::JSGraph::simplified().
Referenced by ConvertPlainPrimitiveToNumber(), NumberComparisonFor(), ReduceCheckBounds(), ReduceMaybeGrowFastElements(), ReduceNumberFloor(), ReduceReferenceEqual(), ReduceSameValue(), ReduceSelect(), ReduceSpeculativeNumberAdd(), ReduceSpeculativeNumberBinop(), ReduceSpeculativeNumberComparison(), ReduceStringComparison(), ReduceToBoolean(), and TryReduceStringComparisonOfStringFromSingleCharCode().
TryReduceStringComparisonOfStringFromSingleCharCode()
Reduction v8::internal::compiler::TypedOptimization::TryReduceStringComparisonOfStringFromSingleCharCode (Node * comparison, Node * from_char_code, Type constant_type, bool inverted) [private]
Definition at line 531 of file typed-optimization.cc.
                                                                               {
  DCHECK_EQ(IrOpcode::kStringFromSingleCharCode, from_char_code->opcode());
  if (!constant_type.IsHeapConstant()) return NoChange();
  ObjectRef constant = constant_type.AsHeapConstant()->Ref();
  if (!constant.IsString()) return NoChange();
  StringRef string = constant.AsString();
  // Check if comparison can be resolved statically.
  Reduction red = TryReduceStringComparisonOfStringFromSingleCharCodeToConstant(
      comparison, string, inverted);
  if (red.Changed()) return red;
  const Operator* comparison_op = NumberComparisonFor(comparison->op());
  Node* from_char_code_repl = NodeProperties::GetValueInput(from_char_code, 0);
  Type from_char_code_repl_type = NodeProperties::GetType(from_char_code_repl);
  if (!from_char_code_repl_type.Is(type_cache_->kUint16)) {
    // Convert to signed int32 to satisfy type of {NumberBitwiseAnd}.
    from_char_code_repl =
        graph()->NewNode(simplified()->NumberToInt32(), from_char_code_repl);
    from_char_code_repl = graph()->NewNode(
        simplified()->NumberBitwiseAnd(), from_char_code_repl,
        jsgraph()->ConstantNoHole(std::numeric_limits<uint16_t>::max()));
  }
  if (!string.GetFirstChar(broker()).has_value()) return NoChange();
  Node* constant_repl =
      jsgraph()->ConstantNoHole(string.GetFirstChar(broker()).value());
  Node* number_comparison = nullptr;
  if (inverted) {
    // "x..." <= String.fromCharCode(z) is true if x < z.
    if (string.length() > 1 &&
        comparison->opcode() == IrOpcode::kStringLessThanOrEqual) {
      comparison_op = simplified()->NumberLessThan();
    }
    number_comparison =
        graph()->NewNode(comparison_op, constant_repl, from_char_code_repl);
  } else {
    // String.fromCharCode(z) < "x..." is true if z <= x.
    if (string.length() > 1 &&
        comparison->opcode() == IrOpcode::kStringLessThan) {
      comparison_op = simplified()->NumberLessThanOrEqual();
    }
    number_comparison =
        graph()->NewNode(comparison_op, from_char_code_repl, constant_repl);
  }
  ReplaceWithValue(comparison, number_comparison);
  return Replace(number_comparison);
}
References v8::internal::compiler::Type::AsHeapConstant(), broker(), v8::internal::compiler::Reduction::Changed(), v8::internal::compiler::JSGraph::ConstantNoHole(), DCHECK_EQ, v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::Type::Is(), v8::internal::compiler::Type::IsHeapConstant(), jsgraph(), v8::internal::compiler::TypeCache::kUint16, v8::internal::length, v8::internal::compiler::TFGraph::NewNode(), NumberComparisonFor(), v8::internal::compiler::SimplifiedOperatorBuilder::NumberLessThan(), v8::internal::compiler::SimplifiedOperatorBuilder::NumberLessThanOrEqual(), v8::internal::NumberToInt32(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::HeapConstantType::Ref(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), simplified(), TryReduceStringComparisonOfStringFromSingleCharCodeToConstant(), type_cache_, and v8::internal::value.
Referenced by ReduceStringComparison().
TryReduceStringComparisonOfStringFromSingleCharCodeToConstant()
Reduction v8::internal::compiler::TypedOptimization::TryReduceStringComparisonOfStringFromSingleCharCodeToConstant (Node * comparison, StringRef string, bool inverted) [private]
Definition at line 501 of file typed-optimization.cc.
                                                           {
  switch (comparison->opcode()) {
    case IrOpcode::kStringEqual:
    case IrOpcode::kStringOrOddballStrictEqual:
      if (string.length() != 1) {
        // String.fromCharCode(x) always has length 1.
        return Replace(jsgraph()->BooleanConstant(false));
      }
      break;
    case IrOpcode::kStringLessThan:
      [[fallthrough]];
    case IrOpcode::kStringLessThanOrEqual:
      if (string.length() == 0) {
        // String.fromCharCode(x) <= "" is always false,
        // "" < String.fromCharCode(x) is always true.
        return Replace(jsgraph()->BooleanConstant(inverted));
      }
      break;
    default:
      UNREACHABLE();
  }
  return NoChange();
}
References jsgraph(), v8::internal::length, v8::internal::compiler::Node::opcode(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), and v8::internal::UNREACHABLE().
Referenced by TryReduceStringComparisonOfStringFromSingleCharCode().
Member Data Documentation
broker_
JSHeapBroker* v8::internal::compiler::TypedOptimization::broker_ [private]
Definition at line 94 of file typed-optimization.h.
dependencies_
CompilationDependencies* const v8::internal::compiler::TypedOptimization::dependencies_ [private]
Definition at line 92 of file typed-optimization.h.
false_type_
Type const v8::internal::compiler::TypedOptimization::false_type_ [private]
Definition at line 96 of file typed-optimization.h.
Referenced by ReduceSelect().
jsgraph_
JSGraph* const v8::internal::compiler::TypedOptimization::jsgraph_ [private]
Definition at line 93 of file typed-optimization.h.
true_type_
Type const v8::internal::compiler::TypedOptimization::true_type_ [private]
Definition at line 95 of file typed-optimization.h.
Referenced by ReduceSelect().
type_cache_
TypeCache const* v8::internal::compiler::TypedOptimization::type_cache_ [private]
Definition at line 97 of file typed-optimization.h.
Referenced by ReduceNumberFloor(), ReduceNumberRoundop(), ReduceNumberToUint8Clamped(), ReduceStringComparison(), and TryReduceStringComparisonOfStringFromSingleCharCode().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/typed-optimization.h
/mnt/V8SourceCode/src/compiler/typed-optimization.cc