v8::ValueSerializer Class Reference
Value serialization compatible with the HTML structured clone algorithm.
#include <v8-value-serializer.h>
Classes
class Delegate
struct PrivateData
Public Member Functions
ValueSerializer (Isolate *isolate)
ValueSerializer (Isolate *isolate, Delegate *delegate)
~ValueSerializer ()
void WriteHeader ()
Writes out a header, which includes the format version.
V8_WARN_UNUSED_RESULT Maybe< bool > WriteValue (Local< Context > context, Local< Value > value)
Serializes a JavaScript value into the buffer.
V8_WARN_UNUSED_RESULT std::pair< uint8_t *, size_t > Release ()
Returns the stored data (allocated using the delegate's ReallocateBufferMemory) and its size.
void TransferArrayBuffer (uint32_t transfer_id, Local< ArrayBuffer > array_buffer)
Marks an ArrayBuffer as havings its contents transferred out of band.
void SetTreatArrayBufferViewsAsHostObjects (bool mode)
Indicate whether to treat ArrayBufferView objects as host objects, i.e.
void WriteUint32 (uint32_t value)
Write raw data in various common formats to the buffer.
void WriteUint64 (uint64_t value)
void WriteDouble (double value)
void WriteRawBytes (const void *source, size_t length)
ValueSerializer (const ValueSerializer &)=delete
void operator= (const ValueSerializer &)=delete
Private Attributes
PrivateData * private_
Detailed Description
Value serialization compatible with the HTML structured clone algorithm.
The format is backward-compatible (i.e. safe to store to disk).
Definition at line 65 of file v8-value-serializer.h.
Constructor & Destructor Documentation
ValueSerializer() [1/3]
v8::ValueSerializer::ValueSerializer (Isolate * isolate) [explicit]
Definition at line 3330 of file api.cc.
    : ValueSerializer(v8_isolate, nullptr) {}
ValueSerializer() [2/3]
v8::ValueSerializer::ValueSerializer (Isolate * isolate, Delegate * delegate)
Definition at line 3333 of file api.cc.
    : private_(new PrivateData(reinterpret_cast<i::Isolate*>(v8_isolate),
                               delegate)) {}
 ValueSerializer()
v8::ValueSerializer::~ValueSerializer ()
Definition at line 3337 of file api.cc.
{ delete private_; }
References private_.
ValueSerializer() [3/3]
v8::ValueSerializer::ValueSerializer (const ValueSerializer &) [delete]
Member Function Documentation
operator=()
void v8::ValueSerializer::operator= (const ValueSerializer &) [delete]
Release()
std::pair< uint8_t *, size_t > v8::ValueSerializer::Release ()
Returns the stored data (allocated using the delegate's ReallocateBufferMemory) and its size.
This serializer should not be used once the buffer is released. The contents are undefined if a previous write has failed. Ownership of the buffer is transferred to the caller.
Definition at line 3354 of file api.cc.
                                                   {
  return private_->serializer.Release();
}
References private_, v8::internal::ValueSerializer::Release(), and v8::ValueSerializer::PrivateData::serializer.
Referenced by v8::Shell::SerializerSerialize().
SetTreatArrayBufferViewsAsHostObjects()
void v8::ValueSerializer::SetTreatArrayBufferViewsAsHostObjects (bool mode)
Indicate whether to treat ArrayBufferView objects as host objects, i.e.
pass them to Delegate::WriteHostObject. This should not be called when no Delegate was passed.
The default is not to treat ArrayBufferViews as host objects.
Definition at line 3341 of file api.cc.
                                                                     {
  private_->serializer.SetTreatArrayBufferViewsAsHostObjects(mode);
}
References mode(), private_, v8::ValueSerializer::PrivateData::serializer, and v8::internal::ValueSerializer::SetTreatArrayBufferViewsAsHostObjects().
TransferArrayBuffer()
void v8::ValueSerializer::TransferArrayBuffer (uint32_t transfer_id, Local< ArrayBuffer > array_buffer)
Marks an ArrayBuffer as havings its contents transferred out of band.
Pass the corresponding ArrayBuffer in the deserializing context to ValueDeserializer::TransferArrayBuffer.
Definition at line 3358 of file api.cc.
                                                                           {
  private_->serializer.TransferArrayBuffer(
      transfer_id, Utils::OpenDirectHandle(*array_buffer));
}
References v8::Utils::OpenDirectHandle(), private_, v8::ValueSerializer::PrivateData::serializer, and v8::internal::ValueSerializer::TransferArrayBuffer().
WriteDouble()
void v8::ValueSerializer::WriteDouble (double value)
Definition at line 3372 of file api.cc.
                                              {
  private_->serializer.WriteDouble(value);
}
References private_, v8::ValueSerializer::PrivateData::serializer, v8::internal::value, and v8::internal::ValueSerializer::WriteDouble().
WriteHeader()
void v8::ValueSerializer::WriteHeader ()
Writes out a header, which includes the format version.
Definition at line 3339 of file api.cc.
{ private_->serializer.WriteHeader(); }
References private_, v8::ValueSerializer::PrivateData::serializer, and v8::internal::ValueSerializer::WriteHeader().
Referenced by v8::Shell::SerializerSerialize().
WriteRawBytes()
void v8::ValueSerializer::WriteRawBytes (const void * source, size_t length)
Definition at line 3376 of file api.cc.
                                                                     {
  private_->serializer.WriteRawBytes(source, length);
}
References v8::internal::length, private_, v8::ValueSerializer::PrivateData::serializer, and v8::internal::ValueSerializer::WriteRawBytes().
WriteUint32()
void v8::ValueSerializer::WriteUint32 (uint32_t value)
Write raw data in various common formats to the buffer.
Note that integer types are written in base-128 varint format, not with a binary copy. For use during an override of Delegate::WriteHostObject.
Definition at line 3364 of file api.cc.
                                                {
  private_->serializer.WriteUint32(value);
}
References private_, v8::ValueSerializer::PrivateData::serializer, v8::internal::value, and v8::internal::ValueSerializer::WriteUint32().
WriteUint64()
void v8::ValueSerializer::WriteUint64 (uint64_t value)
Definition at line 3368 of file api.cc.
                                                {
  private_->serializer.WriteUint64(value);
}
References private_, v8::ValueSerializer::PrivateData::serializer, v8::internal::value, and v8::internal::ValueSerializer::WriteUint64().
WriteValue()
Maybe< bool > v8::ValueSerializer::WriteValue (Local< Context > context, Local< Value > value)
Serializes a JavaScript value into the buffer.
Definition at line 3345 of file api.cc.
                                                            {
  auto i_isolate = i::Isolate::Current();
  EnterV8Scope<> api_scope{i_isolate, context,
                           RCCId::kAPI_ValueSerializer_WriteValue};
  auto object = Utils::OpenHandle(*value);
  return private_->serializer.WriteObject(object);
}
References v8::internal::Isolate::Current(), v8::Utils::OpenHandle(), private_, v8::ValueSerializer::PrivateData::serializer, v8::internal::value, and v8::internal::ValueSerializer::WriteObject().
Referenced by v8::Shell::SerializerSerialize().
Member Data Documentation
private_
PrivateData* v8::ValueSerializer::private_ [private]
Definition at line 208 of file v8-value-serializer.h.
Referenced by Release(), SetTreatArrayBufferViewsAsHostObjects(), TransferArrayBuffer(), WriteDouble(), WriteHeader(), WriteRawBytes(), WriteUint32(), WriteUint64(), WriteValue(), and ~ValueSerializer().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-value-serializer.h
/mnt/V8SourceCode/src/api/api.cc