v8::internal::compiler::turboshaft::Simd128UseMap Class Reference
#include <use-map.h>
Public Member Functions
Simd128UseMap (const Graph &graph, Zone *zone)
Detailed Description
Definition at line 49 of file use-map.h.
Constructor & Destructor Documentation
Simd128UseMap()
v8::internal::compiler::turboshaft::Simd128UseMap::Simd128UseMap (const Graph & graph, Zone * zone) [inline]
Definition at line 51 of file use-map.h.
      : UseMap(
            graph, zone,
            [](const Graph& graph, const Operation& op, Zone* zone) {
              auto has_revectorizable_simd128_output = [](const Operation& op) {
                // Revectorizable Simd128 operations only have single output.
                return op.outputs_rep().size() == 1 &&
                       op.outputs_rep()[0] == RegisterRepresentation::Simd128();
              };
              if (has_revectorizable_simd128_output(op)) return false;
              // Identify input_reps of ReturnOp and FrameStateOp (which doesn't
              // track inputs_rep, except for the Word32 popcount input of
              // ReturnOp).
              if (op.TryCast<ReturnOp>() || op.TryCast<FrameStateOp>()) {
                for (auto input : op.inputs()) {
                  const Operation& input_op = graph.Get(input);
                  if (has_revectorizable_simd128_output(input_op)) return false;
                }
                return true;
              }
              ZoneVector<MaybeRegisterRepresentation> storage(zone);
              for (auto rep : op.inputs_rep(storage)) {
                if (rep == MaybeRegisterRepresentation::Simd128()) return false;
              }
              SLOW_DCHECK(std::none_of(
                  op.inputs().begin(), op.inputs().end(),
                  [&](const OpIndex input) {
                    return has_revectorizable_simd128_output(graph.Get(input));
                  }));
              return true;
            }) {}
References graph(), v8::base::none_of(), v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Simd128(), v8::internal::compiler::turboshaft::RegisterRepresentation::Simd128(), SLOW_DCHECK, and v8::internal::compiler::turboshaft::Operation::TryCast().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/use-map.h