v8::anonymous_namespace{api.cc}::ArrayBufferAllocator Class Reference
Public Member Functions
void * Allocate (size_t length) override
Allocate |length| bytes.
void * AllocateUninitialized (size_t length) override
Allocate |length| bytes.
void Free (void *data, size_t) override
Free the memory block of size |length|, pointed to by |data|.
PageAllocator * GetPageAllocator () override
Returns page allocator used by this Allocator instance.
Additional Inherited Members
Detailed Description
Definition at line 337 of file api.cc.
Member Function Documentation
Allocate()
void* v8::anonymous_namespace{api.cc}::ArrayBufferAllocator::Allocate (size_t length) [inline], [override], [virtual]
Allocate |length| bytes.
Return nullptr if allocation is not successful. Memory should be initialized to zeroes.
Implements v8::ArrayBuffer::Allocator.
Definition at line 339 of file api.cc.
{ return base::Calloc(length, 1); }
References v8::base::Calloc(), and v8::internal::length.
AllocateUninitialized()
void* v8::anonymous_namespace{api.cc}::ArrayBufferAllocator::AllocateUninitialized (size_t length) [inline], [override], [virtual]
Allocate |length| bytes.
Return nullptr if allocation is not successful. Memory does not have to be initialized.
Implements v8::ArrayBuffer::Allocator.
Definition at line 341 of file api.cc.
                                                      {
    return base::Malloc(length);
  }
References v8::internal::length, and v8::base::Malloc().
Free()
void v8::anonymous_namespace{api.cc}::ArrayBufferAllocator::Free (void * data, size_t length) [inline], [override], [virtual]
Free the memory block of size |length|, pointed to by |data|.
That memory is guaranteed to be previously allocated by |Allocate|.
Implements v8::ArrayBuffer::Allocator.
Definition at line 345 of file api.cc.
{ base::Free(data); }
References v8::base::Free().
GetPageAllocator()
PageAllocator* v8::anonymous_namespace{api.cc}::ArrayBufferAllocator::GetPageAllocator () [inline], [override], [virtual]
Returns page allocator used by this Allocator instance.
When the sandbox used by Allocator it is expected that this returns sandbox's page allocator. Otherwise, it should return system page allocator.
Reimplemented from v8::ArrayBuffer::Allocator.
Definition at line 347 of file api.cc.
                                             {
    return i::GetPlatformPageAllocator();
  }
References v8::internal::GetPlatformPageAllocator().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/api/api.cc