v8::internal::DescriptorArray Class Reference
#include <descriptor-array.h>
Public Types
enum class FastIterableState : uint8_t { kJsonFast = 0b00
, kJsonSlow = 0b01
, kUnknown = 0b11
 }
using EntryKeyField = TaggedField< HeapObject, kEntryKeyOffset >
using EntryDetailsField = TaggedField< Smi, kEntryDetailsOffset >
using EntryValueField = TaggedField< MaybeObject, kEntryValueOffset >
Public Member Functions
int16_t number_of_slack_descriptors () const
int number_of_entries () const
FastIterableState fast_iterable () const
void set_fast_iterable (FastIterableState value)
void set_fast_iterable_if (FastIterableState new_value, FastIterableState if_value)
void ClearEnumCache ()
void CopyEnumCacheFrom (Tagged< DescriptorArray > array)
Tagged< Name > GetKey (InternalIndex descriptor_number) const
Tagged< Name > GetKey (PtrComprCageBase cage_base, InternalIndex descriptor_number) const
Tagged< Object > GetStrongValue (InternalIndex descriptor_number)
Tagged< Object > GetStrongValue (PtrComprCageBase cage_base, InternalIndex descriptor_number)
Tagged< MaybeObject > GetValue (InternalIndex descriptor_number)
Tagged< MaybeObject > GetValue (PtrComprCageBase cage_base, InternalIndex descriptor_number)
PropertyDetails GetDetails (InternalIndex descriptor_number)
int GetFieldIndex (InternalIndex descriptor_number)
Tagged< FieldType > GetFieldType (InternalIndex descriptor_number)
Tagged< FieldType > GetFieldType (PtrComprCageBase cage_base, InternalIndex descriptor_number)
bool IsInitializedDescriptor (InternalIndex descriptor_number) const
Tagged< Name > GetSortedKey (int descriptor_number)
Tagged< Name > GetSortedKey (PtrComprCageBase cage_base, int descriptor_number)
int GetSortedKeyIndex (int descriptor_number)
void Set (InternalIndex descriptor_number, Descriptor *desc)
void Set (InternalIndex descriptor_number, Tagged< Name > key, Tagged< MaybeObject > value, PropertyDetails details)
void Replace (InternalIndex descriptor_number, Descriptor *descriptor)
void GeneralizeAllFields (bool clear_constness)
void Append (Descriptor *desc)
V8_EXPORT_PRIVATE void Sort ()
V8_EXPORT_PRIVATE void CheckNameCollisionDuringInsertion (Descriptor *desc, uint32_t descriptor_hash, int insertion_index)
InternalIndex Search (Tagged< Name > name, int number_of_own_descriptors, bool concurrent_search=false)
InternalIndex Search (Tagged< Name > name, Tagged< Map > map, bool concurrent_search=false)
InternalIndex Search (int field_offset, int number_of_own_descriptors)
InternalIndex Search (int field_offset, Tagged< Map > map)
InternalIndex SearchWithCache (Isolate *isolate, Tagged< Name > name, Tagged< Map > map)
bool IsEqualUpTo (Tagged< DescriptorArray > desc, int nof_descriptors)
void Initialize (Tagged< EnumCache > enum_cache, Tagged< HeapObject > undefined_value, int nof_descriptors, int slack, uint32_t raw_gc_state)
ObjectSlot GetFirstPointerSlot ()
ObjectSlot GetDescriptorSlot (int descriptor)
void PrintDescriptors (std::ostream &os)
void PrintDescriptorDetails (std::ostream &os, InternalIndex descriptor, PropertyDetails::PrintMode mode)
template<typename IsolateT >
Handle< DescriptorArray > Allocate (IsolateT *isolate, int nof_descriptors, int slack, AllocationType allocation)
Static Public Member Functions
static void InitializeOrChangeEnumCache (DirectHandle< DescriptorArray > descriptors, Isolate *isolate, DirectHandle< FixedArray > keys, DirectHandle< FixedArray > indices, AllocationType allocation_if_initialize)
static DirectHandle< DescriptorArray > CopyUpTo (Isolate *isolate, DirectHandle< DescriptorArray > desc, int enumeration_index, int slack=0)
static DirectHandle< DescriptorArray > CopyUpToAddAttributes (Isolate *isolate, DirectHandle< DescriptorArray > desc, int enumeration_index, PropertyAttributes attributes, int slack=0)
template<typename IsolateT >
static V8_EXPORT_PRIVATE Handle< DescriptorArray > Allocate (IsolateT *isolate, int nof_descriptors, int slack, AllocationType allocation=AllocationType::kYoung)
static constexpr int SizeFor (int number_of_all_descriptors)
static constexpr int OffsetOfDescriptorAt (int descriptor)
static constexpr int ToDetailsIndex (int descriptor_number)
static constexpr int ToKeyIndex (int descriptor_number)
static constexpr int ToValueIndex (int descriptor_number)
Static Public Attributes
static const int kNotFound = -1
static constexpr size_t kSizeOfRawGcState
static const int kEntryKeyIndex = 0
static const int kEntryDetailsIndex = 1
static const int kEntryValueIndex = 2
static const int kEntrySize = 3
static const int kEntryKeyOffset = kEntryKeyIndex * kTaggedSize
static const int kEntryDetailsOffset = kEntryDetailsIndex * kTaggedSize
static const int kEntryValueOffset = kEntryValueIndex * kTaggedSize
Private Member Functions
void SetKey (InternalIndex descriptor_number, Tagged< Name > key)
void SetValue (InternalIndex descriptor_number, Tagged< MaybeObject > value)
void SetDetails (InternalIndex descriptor_number, PropertyDetails details)
InternalIndex BinarySearch (Tagged< Name > name, int number_of_own_descriptors)
InternalIndex LinearSearch (Tagged< Name > name, int number_of_own_descriptors)
void CopyFrom (InternalIndex index, Tagged< DescriptorArray > src)
void SetSortedKey (int pointer, int descriptor_number)
void SwapSortedKeys (int first, int second)
Detailed Description
Definition at line 55 of file descriptor-array.h.
Member Typedef Documentation
EntryDetailsField
using v8::internal::DescriptorArray::EntryDetailsField = TaggedField<Smi, kEntryDetailsOffset>
Definition at line 251 of file descriptor-array.h.
EntryKeyField
using v8::internal::DescriptorArray::EntryKeyField = TaggedField<HeapObject, kEntryKeyOffset>
Definition at line 250 of file descriptor-array.h.
EntryValueField
using v8::internal::DescriptorArray::EntryValueField = TaggedField<MaybeObject, kEntryValueOffset>
Definition at line 252 of file descriptor-array.h.
Member Enumeration Documentation
FastIterableState
enum v8::internal::DescriptorArray::FastIterableState : uint8_t [strong]
Enumerator
kJsonFast
kJsonSlow
kUnknown
Definition at line 64 of file descriptor-array.h.
                               : uint8_t {
    // Descriptors are JSON fast iterable, iff all of the following conditions
    // are met:
    // - No key is a symbol.
    // - All keys are enumberable.
    // - All keys are one-byte and don't contain any character that requires
    // escaping.
    // - All properties are located in field.
    kJsonFast = 0b00,
    kJsonSlow = 0b01,
    kUnknown = 0b11
  };
Member Function Documentation
Allocate() [1/2]
template<typename IsolateT >
Handle<DescriptorArray> v8::internal::DescriptorArray::Allocate (IsolateT * isolate, int nof_descriptors, int slack, AllocationType allocation)
Definition at line 3907 of file objects.cc.
                                                                             {
  return nof_descriptors + slack == 0
             ? isolate->factory()->empty_descriptor_array()
             : isolate->factory()->NewDescriptorArray(nof_descriptors, slack,
                                                      allocation);
}
Allocate() [2/2]
template<typename IsolateT >
static V8_EXPORT_PRIVATE Handle<DescriptorArray> v8::internal::DescriptorArray::Allocate (IsolateT * isolate, int nof_descriptors, int slack, AllocationType allocation = AllocationType::kYoung) [static]
Referenced by v8::internal::anonymous_namespace{runtime-classes.cc}::AddDescriptorsByTemplate(), v8::internal::MapUpdater::BuildDescriptorArray(), CopyUpToAddAttributes(), v8::internal::ObjectDescriptor< IsolateT >::CreateTemplates(), v8::internal::JSObject::MigrateSlowToFast(), and v8::internal::Map::ShareDescriptor().
Append()
void v8::internal::DescriptorArray::Append (Descriptor * desc) [inline]
Definition at line 344 of file descriptor-array-inl.h.
                                             {
  DisallowGarbageCollection no_gc;
  int descriptor_number = number_of_descriptors();
  DCHECK_LE(descriptor_number + 1, number_of_all_descriptors());
  set_number_of_descriptors(descriptor_number + 1);
  Set(InternalIndex(descriptor_number), desc);
  uint32_t desc_hash = desc->GetKey()->hash();
  // Hash value can't be zero, see String::ComputeAndSetHash()
  uint32_t collision_hash = 0;
  int insertion;
  for (insertion = descriptor_number; insertion > 0; --insertion) {
    Tagged<Name> key = GetSortedKey(insertion - 1);
    collision_hash = key->hash();
    if (collision_hash <= desc_hash) break;
    SetSortedKey(insertion, GetSortedKeyIndex(insertion - 1));
  }
  SetSortedKey(insertion, descriptor_number);
  // Resetting the fast iterable state is bottlenecked in SetKey().
  DCHECK_NE(fast_iterable(), FastIterableState::kJsonFast);
  if (V8_LIKELY(collision_hash != desc_hash)) return;
  CheckNameCollisionDuringInsertion(desc, desc_hash, insertion);
}
References CheckNameCollisionDuringInsertion(), DCHECK_LE, DCHECK_NE, fast_iterable(), v8::internal::Descriptor::GetKey(), GetSortedKey(), GetSortedKeyIndex(), v8::internal::key, kJsonFast, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::number_of_descriptors, Set(), SetSortedKey(), and V8_LIKELY.
BinarySearch()
InternalIndex v8::internal::DescriptorArray::BinarySearch (Tagged< Name > name, int number_of_own_descriptors) [inline], [private]
Definition at line 95 of file descriptor-array-inl.h.
                                                                   {
  // We have to binary search all descriptors, not just valid ones, since the
  // binary search ordering is across all descriptors.
  int end = number_of_descriptors();
  uint32_t hash = name->hash();
  // Find the first descriptor whose key's hash is greater-than-or-equal-to the
  // search hash.
  int number = *std::ranges::lower_bound(std::views::iota(0, end), hash,
                                         std::less<>(), [&](int i) {
                                           Tagged<Name> entry = GetSortedKey(i);
                                           return entry->hash();
                                         });
  // There may have been hash collisions, so search for the name from the first
  // index until the first non-matching hash.
  for (; number < end; ++number) {
    InternalIndex index(GetSortedKeyIndex(number));
    Tagged<Name> entry = GetKey(index);
    if (entry == name) {
      // If we found the entry, but it's outside the owned descriptors of the
      // caller, return not found.
      if (index.as_int() >= valid_descriptors) {
        return InternalIndex::NotFound();
      }
      return index;
    }
    if (entry->hash() != hash) {
      return InternalIndex::NotFound();
    }
  }
  return InternalIndex::NotFound();
}
References v8::internal::compiler::end(), GetKey(), GetSortedKey(), GetSortedKeyIndex(), v8::internal::index, v8::internal::name, v8::internal::InternalIndex::NotFound(), and v8::internal::number_of_descriptors.
Referenced by Search().
CheckNameCollisionDuringInsertion()
void v8::internal::DescriptorArray::CheckNameCollisionDuringInsertion (Descriptor * desc, uint32_t descriptor_hash, int insertion_index)
Definition at line 4027 of file objects.cc.
                                                                             {
  DCHECK_GE(insertion_index, 0);
  DCHECK_LE(insertion_index, number_of_all_descriptors());
  if (insertion_index <= 0) return;
  for (int i = insertion_index; i > 0; --i) {
    Tagged<Name> current_key = GetSortedKey(i - 1);
    if (current_key->hash() != desc_hash) return;
    CHECK(current_key != *desc->GetKey());
  }
}
References CHECK, DCHECK_GE, DCHECK_LE, v8::internal::Descriptor::GetKey(), GetSortedKey(), and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by Append().
ClearEnumCache()
void v8::internal::DescriptorArray::ClearEnumCache ()
Definition at line 3940 of file objects.cc.
                                     {
  set_enum_cache(GetReadOnlyRoots().empty_enum_cache(), SKIP_WRITE_BARRIER);
}
References v8::internal::GetReadOnlyRoots(), and v8::internal::SKIP_WRITE_BARRIER.
CopyEnumCacheFrom()
void v8::internal::DescriptorArray::CopyEnumCacheFrom (Tagged< DescriptorArray > array) [inline]
Definition at line 72 of file descriptor-array-inl.h.
                                                                     {
  set_enum_cache(array->enum_cache());
}
CopyFrom()
void v8::internal::DescriptorArray::CopyFrom (InternalIndex index, Tagged< DescriptorArray > src) [private]
Definition at line 3967 of file objects.cc.
                                                            {
  PropertyDetails details = src->GetDetails(index);
  Set(index, src->GetKey(index), src->GetValue(index), details);
}
References v8::internal::index, and Set().
CopyUpTo()
DirectHandle< DescriptorArray > v8::internal::DescriptorArray::CopyUpTo (Isolate * isolate, DirectHandle< DescriptorArray > desc, int enumeration_index, int slack = 0) [static]
Definition at line 3738 of file objects.cc.
               {
  return DescriptorArray::CopyUpToAddAttributes(isolate, desc,
                                                enumeration_index, NONE, slack);
}
References CopyUpToAddAttributes(), and v8::internal::NONE.
Referenced by v8::internal::Map::Copy(), v8::internal::Map::CopyAddDescriptor(), v8::internal::Map::CopyForElementsTransition(), v8::internal::Map::CopyReplaceDescriptor(), and v8::internal::Map::EnsureDescriptorSlack().
CopyUpToAddAttributes()
DirectHandle< DescriptorArray > v8::internal::DescriptorArray::CopyUpToAddAttributes (Isolate * isolate, DirectHandle< DescriptorArray > desc, int enumeration_index, PropertyAttributes attributes, int slack = 0) [static]
Definition at line 3745 of file objects.cc.
                                                                     {
  if (enumeration_index + slack == 0) {
    return isolate->factory()->empty_descriptor_array();
  }
  int size = enumeration_index;
  DirectHandle<DescriptorArray> copy_handle =
      DescriptorArray::Allocate(isolate, size, slack);
  DisallowGarbageCollection no_gc;
  Tagged<DescriptorArray> source = *source_handle;
  Tagged<DescriptorArray> copy = *copy_handle;
  if (attributes != NONE) {
    for (InternalIndex i : InternalIndex::Range(size)) {
      Tagged<MaybeObject> value_or_field_type = source->GetValue(i);
      Tagged<Name> key = source->GetKey(i);
      PropertyDetails details = source->GetDetails(i);
      // Bulk attribute changes never affect private properties.
      if (!key->IsPrivate()) {
        int mask = DONT_DELETE | DONT_ENUM;
        // READ_ONLY is an invalid attribute for JS setters/getters.
        Tagged<HeapObject> heap_object;
        if (details.kind() != PropertyKind::kAccessor ||
            !(value_or_field_type.GetHeapObjectIfStrong(&heap_object) &&
              IsAccessorPair(heap_object))) {
          mask |= READ_ONLY;
        }
        details = details.CopyAddAttributes(
            static_cast<PropertyAttributes>(attributes & mask));
      }
      copy->Set(i, key, value_or_field_type, details);
    }
  } else {
    for (InternalIndex i : InternalIndex::Range(size)) {
      copy->CopyFrom(i, source);
    }
  }
  if (source->number_of_descriptors() != enumeration_index) copy->Sort();
  return copy_handle;
}
References Allocate(), v8::internal::PropertyDetails::CopyAddAttributes(), v8::internal::DONT_DELETE, v8::internal::DONT_ENUM, v8::internal::Isolate::factory(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectIfStrong(), v8::internal::kAccessor, v8::internal::key, v8::internal::PropertyDetails::kind(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::NONE, v8::internal::READ_ONLY, and size().
Referenced by v8::internal::Map::CopyForPreventExtensions(), and CopyUpTo().
fast_iterable()
DescriptorArray::FastIterableState v8::internal::DescriptorArray::fast_iterable () const [inline]
Definition at line 53 of file descriptor-array-inl.h.
                                                                      {
  return FastIterableBits::decode(flags(kRelaxedLoad));
}
References v8::internal::flags, and v8::kRelaxedLoad.
Referenced by Append(), Replace(), and Set().
GeneralizeAllFields()
void v8::internal::DescriptorArray::GeneralizeAllFields (bool clear_constness)
Definition at line 2250 of file objects.cc.
                                                              {
  int length = number_of_descriptors();
  for (InternalIndex i : InternalIndex::Range(length)) {
    PropertyDetails details = GetDetails(i);
    details = details.CopyWithRepresentation(Representation::Tagged());
    if (details.location() == PropertyLocation::kField) {
      // Since constness is not propagated across proto transitions we must
      // clear the flag here.
      if (clear_constness) {
        details = details.CopyWithConstness(PropertyConstness::kMutable);
      }
      DCHECK_EQ(PropertyKind::kData, details.kind());
      SetValue(i, FieldType::Any());
    }
    SetDetails(i, details);
  }
}
References v8::internal::FieldType::Any(), v8::internal::PropertyDetails::CopyWithConstness(), v8::internal::PropertyDetails::CopyWithRepresentation(), DCHECK_EQ, GetDetails(), v8::internal::kData, v8::internal::kField, v8::internal::PropertyDetails::kind(), v8::internal::kMutable, v8::internal::length, v8::internal::PropertyDetails::location(), v8::internal::number_of_descriptors, SetDetails(), SetValue(), and v8::internal::Representation::Tagged().
GetDescriptorSlot()
ObjectSlot v8::internal::DescriptorArray::GetDescriptorSlot (int descriptor) [inline]
Definition at line 195 of file descriptor-array-inl.h.
                                                            {
  // Allow descriptor == number_of_all_descriptors() for computing the slot
  // address that comes after the last descriptor (for iterating).
  DCHECK_LE(descriptor, number_of_all_descriptors());
  return RawField(OffsetOfDescriptorAt(descriptor));
}
References DCHECK_LE, and OffsetOfDescriptorAt().
Referenced by Initialize().
GetDetails()
PropertyDetails v8::internal::DescriptorArray::GetDetails (InternalIndex descriptor_number) [inline]
Definition at line 290 of file descriptor-array-inl.h.
                                                                           {
  DCHECK_LT(descriptor_number.as_int(), number_of_descriptors());
  int entry_offset = OffsetOfDescriptorAt(descriptor_number.as_int());
  Tagged<Smi> details = EntryDetailsField::Relaxed_Load(*this, entry_offset);
  return PropertyDetails(details);
}
References v8::internal::InternalIndex::as_int(), DCHECK_LT, v8::internal::number_of_descriptors, OffsetOfDescriptorAt(), and v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Relaxed_Load().
Referenced by GeneralizeAllFields(), GetFieldIndex(), GetFieldType(), GetSortedKeyIndex(), IsEqualUpTo(), Search(), and SetSortedKey().
GetFieldIndex()
int v8::internal::DescriptorArray::GetFieldIndex (InternalIndex descriptor_number) [inline]
Definition at line 308 of file descriptor-array-inl.h.
                                                                  {
  DCHECK_EQ(GetDetails(descriptor_number).location(), PropertyLocation::kField);
  return GetDetails(descriptor_number).field_index();
}
References DCHECK_EQ, v8::internal::PropertyDetails::field_index(), GetDetails(), and v8::internal::kField.
GetFieldType() [1/2]
Tagged< FieldType > v8::internal::DescriptorArray::GetFieldType (InternalIndex descriptor_number) [inline]
Definition at line 313 of file descriptor-array-inl.h.
                                     {
  PtrComprCageBase cage_base = GetPtrComprCageBase(*this);
  return GetFieldType(cage_base, descriptor_number);
}
References v8::internal::GetPtrComprCageBase().
GetFieldType() [2/2]
Tagged< FieldType > v8::internal::DescriptorArray::GetFieldType (PtrComprCageBase cage_base, InternalIndex descriptor_number) [inline]
Definition at line 319 of file descriptor-array-inl.h.
                                                                 {
  DCHECK_EQ(GetDetails(descriptor_number).location(), PropertyLocation::kField);
  Tagged<MaybeObject> wrapped_type = GetValue(cage_base, descriptor_number);
  return Map::UnwrapFieldType(wrapped_type);
}
References DCHECK_EQ, GetDetails(), GetValue(), v8::internal::kField, and v8::internal::Map::UnwrapFieldType().
GetFirstPointerSlot()
ObjectSlot v8::internal::DescriptorArray::GetFirstPointerSlot () [inline]
Definition at line 187 of file descriptor-array-inl.h.
                                                {
  static_assert(kEndOfStrongFieldsOffset == kStartOfWeakFieldsOffset,
                "Weak and strong fields are continuous.");
  static_assert(kEndOfWeakFieldsOffset == kHeaderSize,
                "Weak fields extend up to the end of the header.");
  return RawField(DescriptorArray::kStartOfStrongFieldsOffset);
}
GetKey() [1/2]
Tagged< Name > v8::internal::DescriptorArray::GetKey (InternalIndex descriptor_number) const [inline]
Definition at line 215 of file descriptor-array-inl.h.
                                                                          {
  PtrComprCageBase cage_base = GetPtrComprCageBase(*this);
  return GetKey(cage_base, descriptor_number);
}
References v8::internal::GetPtrComprCageBase().
Referenced by BinarySearch(), GetSortedKey(), IsEqualUpTo(), and LinearSearch().
GetKey() [2/2]
Tagged< Name > v8::internal::DescriptorArray::GetKey (PtrComprCageBase cage_base, InternalIndex descriptor_number) const [inline]
Definition at line 220 of file descriptor-array-inl.h.
                                                                            {
  DCHECK_LT(descriptor_number.as_int(), number_of_descriptors());
  int entry_offset = OffsetOfDescriptorAt(descriptor_number.as_int());
  return Cast<Name>(
      EntryKeyField::Relaxed_Load(cage_base, *this, entry_offset));
}
References v8::internal::InternalIndex::as_int(), DCHECK_LT, v8::internal::number_of_descriptors, OffsetOfDescriptorAt(), and v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Relaxed_Load().
GetSortedKey() [1/2]
Tagged< Name > v8::internal::DescriptorArray::GetSortedKey (int descriptor_number) [inline]
Definition at line 244 of file descriptor-array-inl.h.
                                                                {
  PtrComprCageBase cage_base = GetPtrComprCageBase(*this);
  return GetSortedKey(cage_base, descriptor_number);
}
References v8::internal::GetPtrComprCageBase().
Referenced by Append(), BinarySearch(), CheckNameCollisionDuringInsertion(), and Sort().
GetSortedKey() [2/2]
Tagged< Name > v8::internal::DescriptorArray::GetSortedKey (PtrComprCageBase cage_base, int descriptor_number) [inline]
Definition at line 249 of file descriptor-array-inl.h.
                                                                  {
  return GetKey(cage_base, InternalIndex(GetSortedKeyIndex(descriptor_number)));
}
References GetKey(), and GetSortedKeyIndex().
GetSortedKeyIndex()
int v8::internal::DescriptorArray::GetSortedKeyIndex (int descriptor_number) [inline]
Definition at line 240 of file descriptor-array-inl.h.
                                                            {
  return GetDetails(InternalIndex(descriptor_number)).pointer();
}
References GetDetails(), and v8::internal::PropertyDetails::pointer().
Referenced by Append(), BinarySearch(), GetSortedKey(), Replace(), and SwapSortedKeys().
GetStrongValue() [1/2]
Tagged< Object > v8::internal::DescriptorArray::GetStrongValue (InternalIndex descriptor_number) [inline]
Definition at line 259 of file descriptor-array-inl.h.
                                     {
  PtrComprCageBase cage_base = GetPtrComprCageBase(*this);
  return Cast<Object>(GetStrongValue(cage_base, descriptor_number));
}
References v8::internal::GetPtrComprCageBase().
GetStrongValue() [2/2]
Tagged< Object > v8::internal::DescriptorArray::GetStrongValue (PtrComprCageBase cage_base, InternalIndex descriptor_number) [inline]
Definition at line 265 of file descriptor-array-inl.h.
                                                                 {
  return Cast<Object>(GetValue(cage_base, descriptor_number));
}
References GetValue().
GetValue() [1/2]
Tagged< MaybeObject > v8::internal::DescriptorArray::GetValue (InternalIndex descriptor_number) [inline]
Definition at line 278 of file descriptor-array-inl.h.
                                                                             {
  PtrComprCageBase cage_base = GetPtrComprCageBase(*this);
  return GetValue(cage_base, descriptor_number);
}
References v8::internal::GetPtrComprCageBase().
Referenced by GetFieldType(), GetStrongValue(), and IsEqualUpTo().
GetValue() [2/2]
Tagged< MaybeObject > v8::internal::DescriptorArray::GetValue (PtrComprCageBase cage_base, InternalIndex descriptor_number) [inline]
Definition at line 283 of file descriptor-array-inl.h.
                                                                               {
  DCHECK_LT(descriptor_number.as_int(), number_of_descriptors());
  int entry_offset = OffsetOfDescriptorAt(descriptor_number.as_int());
  return EntryValueField::Relaxed_Load(cage_base, *this, entry_offset);
}
References v8::internal::InternalIndex::as_int(), DCHECK_LT, v8::internal::number_of_descriptors, OffsetOfDescriptorAt(), and v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Relaxed_Load().
Initialize()
void v8::internal::DescriptorArray::Initialize (Tagged< EnumCache > enum_cache, Tagged< HeapObject > undefined_value, int nof_descriptors, int slack, uint32_t raw_gc_state)
Definition at line 3923 of file objects.cc.
                                                        {
  DCHECK_GE(nof_descriptors, 0);
  DCHECK_GE(slack, 0);
  DCHECK_LE(nof_descriptors + slack, kMaxNumberOfDescriptors);
  set_number_of_all_descriptors(nof_descriptors + slack);
  set_number_of_descriptors(nof_descriptors);
  set_raw_gc_state(raw_gc_state, kRelaxedStore);
  set_enum_cache(empty_enum_cache, SKIP_WRITE_BARRIER);
  set_flags(FastIterableBits::encode(FastIterableState::kUnknown),
            kRelaxedStore);
  MemsetTagged(GetDescriptorSlot(0), undefined_value,
               number_of_all_descriptors() * kEntrySize);
}
References DCHECK_GE, DCHECK_LE, GetDescriptorSlot(), kEntrySize, v8::internal::kMaxNumberOfDescriptors, v8::kRelaxedStore, kUnknown, v8::internal::MemsetTagged(), and v8::internal::SKIP_WRITE_BARRIER.
InitializeOrChangeEnumCache()
void v8::internal::DescriptorArray::InitializeOrChangeEnumCache (DirectHandle< DescriptorArray > descriptors, Isolate * isolate, DirectHandle< FixedArray > keys, DirectHandle< FixedArray > indices, AllocationType allocation_if_initialize) [static]
Definition at line 3952 of file objects.cc.
                                             {
  Tagged<EnumCache> enum_cache = descriptors->enum_cache();
  if (enum_cache == ReadOnlyRoots(isolate).empty_enum_cache()) {
    enum_cache = *isolate->factory()->NewEnumCache(keys, indices,
                                                   allocation_if_initialize);
    descriptors->set_enum_cache(enum_cache);
  } else {
    enum_cache->set_keys(*keys);
    enum_cache->set_indices(*indices);
  }
}
References v8::internal::Isolate::factory(), and v8::internal::Factory::NewEnumCache().
Referenced by v8::internal::FastKeyAccumulator::InitializeFastPropertyEnumCache().
IsEqualUpTo()
bool v8::internal::DescriptorArray::IsEqualUpTo (Tagged< DescriptorArray > desc, int nof_descriptors)
Definition at line 3791 of file objects.cc.
                                                       {
  for (InternalIndex i : InternalIndex::Range(nof_descriptors)) {
    if (GetKey(i) != desc->GetKey(i) || GetValue(i) != desc->GetValue(i)) {
      return false;
    }
    PropertyDetails details = GetDetails(i);
    PropertyDetails other_details = desc->GetDetails(i);
    if (details.kind() != other_details.kind() ||
        details.location() != other_details.location() ||
        !details.representation().Equals(other_details.representation())) {
      return false;
    }
  }
  return true;
}
References v8::internal::Representation::Equals(), GetDetails(), GetKey(), GetValue(), v8::internal::PropertyDetails::kind(), v8::internal::PropertyDetails::location(), and v8::internal::PropertyDetails::representation().
IsInitializedDescriptor()
bool v8::internal::DescriptorArray::IsInitializedDescriptor (InternalIndex descriptor_number) const [inline]
Definition at line 202 of file descriptor-array-inl.h.
                                           {
  DCHECK_LT(descriptor_number.as_int(), number_of_descriptors());
  int entry_offset = OffsetOfDescriptorAt(descriptor_number.as_int());
  PtrComprCageBase cage_base = GetPtrComprCageBase(*this);
  Tagged<Object> maybe_name =
      EntryKeyField::Relaxed_Load(cage_base, *this, entry_offset);
  bool is_initialized = !IsUndefined(maybe_name);
  DCHECK_IMPLIES(is_initialized,
                 IsSmi(EntryDetailsField::Relaxed_Load(*this, entry_offset)));
  return is_initialized;
}
References v8::internal::InternalIndex::as_int(), DCHECK_IMPLIES, DCHECK_LT, v8::internal::GetPtrComprCageBase(), v8::internal::IsSmi(), v8::internal::number_of_descriptors, OffsetOfDescriptorAt(), and v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Relaxed_Load().
LinearSearch()
InternalIndex v8::internal::DescriptorArray::LinearSearch (Tagged< Name > name, int number_of_own_descriptors) [inline], [private]
Definition at line 131 of file descriptor-array-inl.h.
                                                                   {
  DCHECK_LE(valid_descriptors, number_of_descriptors());
  for (int i = 0; i < valid_descriptors; ++i) {
    InternalIndex index(i);
    if (GetKey(index) == name) return index;
  }
  return InternalIndex::NotFound();
}
References DCHECK_LE, GetKey(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::name, v8::internal::InternalIndex::NotFound(), and v8::internal::number_of_descriptors.
Referenced by Search().
number_of_entries()
int v8::internal::DescriptorArray::number_of_entries () const [inline]
Definition at line 49 of file descriptor-array-inl.h.
                                                    {
  return number_of_descriptors();
}
References v8::internal::number_of_descriptors.
number_of_slack_descriptors()
kNumberOfDescriptorsOffset int16_t v8::internal::DescriptorArray::number_of_slack_descriptors () const [inline]
Definition at line 45 of file descriptor-array-inl.h.
                                                                  {
  return number_of_all_descriptors() - number_of_descriptors();
}
References v8::internal::number_of_descriptors.
OffsetOfDescriptorAt()
static constexpr int v8::internal::DescriptorArray::OffsetOfDescriptorAt (int descriptor) [inline], [static], [constexpr]
Definition at line 196 of file descriptor-array.h.
                                                            {
    return kDescriptorsOffset + descriptor * kEntrySize * kTaggedSize;
  }
References cppgc::internal::anonymous_namespace{gc-info-table.cc}::kEntrySize, and v8::internal::kTaggedSize.
Referenced by GetDescriptorSlot(), GetDetails(), GetKey(), GetValue(), IsInitializedDescriptor(), SetDetails(), SetKey(), and SetValue().
PrintDescriptorDetails()
void v8::internal::DescriptorArray::PrintDescriptorDetails (std::ostream & os, InternalIndex descriptor, PropertyDetails::PrintMode mode)
Definition at line 4109 of file objects-printer.cc.
                                                                            {
  PropertyDetails details = GetDetails(descriptor);
  details.PrintAsFastTo(os, mode);
  os << " @ ";
  switch (details.location()) {
    case PropertyLocation::kField: {
      Tagged<FieldType> field_type = GetFieldType(descriptor);
      FieldType::PrintTo(field_type, os);
      break;
    }
    case PropertyLocation::kDescriptor:
      Tagged<Object> value = GetStrongValue(descriptor);
      os << Brief(value);
      if (IsAccessorPair(value)) {
        Tagged<AccessorPair> pair = Cast<AccessorPair>(value);
        os << "(get: " << Brief(pair->getter())
           << ", set: " << Brief(pair->setter()) << ")";
      }
      break;
  }
}
References v8::internal::kDescriptor, v8::internal::kField, v8::internal::PropertyDetails::location(), mode(), v8::internal::PropertyDetails::PrintAsFastTo(), v8::internal::FieldType::PrintTo(), and v8::internal::value.
PrintDescriptors()
void v8::internal::DescriptorArray::PrintDescriptors (std::ostream & os)
Definition at line 4094 of file objects-printer.cc.
                                                     {
  for (InternalIndex i : InternalIndex::Range(number_of_descriptors())) {
    Tagged<Name> key = GetKey(i);
    os << "\n [" << i.as_int() << "]: ";
#ifdef OBJECT_PRINT
    key->NamePrint(os);
#else
    ShortPrint(key, os);
#endif
    os << " ";
    PrintDescriptorDetails(os, i, PropertyDetails::kPrintFull);
  }
  os << "\n";
}
References v8::internal::key, v8::internal::PropertyDetails::kPrintFull, v8::internal::number_of_descriptors, and v8::internal::ShortPrint().
Replace()
void v8::internal::DescriptorArray::Replace (InternalIndex descriptor_number, Descriptor * descriptor)
Definition at line 3944 of file objects.cc.
                                                                         {
  descriptor->SetSortedKeyIndex(GetSortedKeyIndex(index.as_int()));
  Set(index, descriptor);
  // Resetting the fast iterable state is bottlenecked in SetKey().
  DCHECK_NE(fast_iterable(), FastIterableState::kJsonFast);
}
References DCHECK_NE, fast_iterable(), GetSortedKeyIndex(), v8::internal::index, kJsonFast, Set(), and v8::internal::Descriptor::SetSortedKeyIndex().
Search() [1/4]
InternalIndex v8::internal::DescriptorArray::Search (int field_offset, int number_of_own_descriptors) [inline]
Definition at line 149 of file descriptor-array-inl.h.
                                                                            {
  for (int desc_index = field_index; desc_index < valid_descriptors;
       ++desc_index) {
    PropertyDetails details = GetDetails(InternalIndex(desc_index));
    if (details.location() != PropertyLocation::kField) continue;
    if (field_index == details.field_index()) {
      return InternalIndex(desc_index);
    }
    DCHECK_LT(details.field_index(), field_index);
  }
  return InternalIndex::NotFound();
}
References DCHECK_LT, v8::internal::PropertyDetails::field_index(), GetDetails(), v8::internal::kField, v8::internal::PropertyDetails::location(), and v8::internal::InternalIndex::NotFound().
Search() [2/4]
InternalIndex v8::internal::DescriptorArray::Search (int field_offset, Tagged< Map > map) [inline]
Definition at line 162 of file descriptor-array-inl.h.
                                                                      {
  int number_of_own_descriptors = map->NumberOfOwnDescriptors();
  if (number_of_own_descriptors == 0) return InternalIndex::NotFound();
  return Search(field_index, number_of_own_descriptors);
}
References v8::internal::InternalIndex::NotFound(), and Search().
Search() [3/4]
InternalIndex v8::internal::DescriptorArray::Search (Tagged< Name > name, int number_of_own_descriptors, bool concurrent_search = false) [inline]
Definition at line 76 of file descriptor-array-inl.h.
                                                              {
  DCHECK(IsUniqueName(name));
  SLOW_DCHECK_IMPLIES(!concurrent_search, IsSortedNoDuplicates());
  if (valid_descriptors == 0) {
    return InternalIndex::NotFound();
  }
  // Do linear search for small arrays, and for searches in the background
  // thread.
  const int kMaxElementsForLinearSearch = 8;
  if (valid_descriptors <= kMaxElementsForLinearSearch || concurrent_search) {
    return LinearSearch(name, valid_descriptors);
  }
  return BinarySearch(name, valid_descriptors);
}
References BinarySearch(), v8::internal::DCHECK(), v8::internal::IsUniqueName(), LinearSearch(), v8::internal::name, v8::internal::InternalIndex::NotFound(), and SLOW_DCHECK_IMPLIES.
Referenced by Search(), and SearchWithCache().
Search() [4/4]
InternalIndex v8::internal::DescriptorArray::Search (Tagged< Name > name, Tagged< Map > map, bool concurrent_search = false) [inline]
Definition at line 141 of file descriptor-array-inl.h.
                                                              {
  DCHECK(IsUniqueName(name));
  int number_of_own_descriptors = map->NumberOfOwnDescriptors();
  if (number_of_own_descriptors == 0) return InternalIndex::NotFound();
  return Search(name, number_of_own_descriptors, concurrent_search);
}
References v8::internal::DCHECK(), v8::internal::IsUniqueName(), v8::internal::name, v8::internal::InternalIndex::NotFound(), and Search().
SearchWithCache()
InternalIndex v8::internal::DescriptorArray::SearchWithCache (Isolate * isolate, Tagged< Name > name, Tagged< Map > map) [inline]
Definition at line 168 of file descriptor-array-inl.h.
                                                                {
  DCHECK(IsUniqueName(name));
  int number_of_own_descriptors = map->NumberOfOwnDescriptors();
  if (number_of_own_descriptors == 0) return InternalIndex::NotFound();
  DescriptorLookupCache* cache = isolate->descriptor_lookup_cache();
  int number = cache->Lookup(map, name);
  if (number == DescriptorLookupCache::kAbsent) {
    InternalIndex result = Search(name, number_of_own_descriptors);
    number = result.is_found() ? result.as_int() : DescriptorArray::kNotFound;
    cache->Update(map, name, number);
  }
  if (number == DescriptorArray::kNotFound) return InternalIndex::NotFound();
  return InternalIndex(number);
}
References v8::internal::DCHECK(), v8::internal::Isolate::descriptor_lookup_cache(), v8::internal::IsUniqueName(), v8::internal::DescriptorLookupCache::kAbsent, kNotFound, v8::internal::DescriptorLookupCache::Lookup(), v8::internal::name, v8::internal::InternalIndex::NotFound(), v8::base::internal::result, Search(), and v8::internal::DescriptorLookupCache::Update().
Set() [1/2]
void v8::internal::DescriptorArray::Set (InternalIndex descriptor_number, Descriptor * desc) [inline]
Definition at line 336 of file descriptor-array-inl.h.
                                                                           {
  Tagged<Name> key = *desc->GetKey();
  Tagged<MaybeObject> value = *desc->GetValue();
  Set(descriptor_number, key, value, desc->GetDetails());
  // Resetting the fast iterable state is bottlenecked in SetKey().
  DCHECK_NE(fast_iterable(), FastIterableState::kJsonFast);
}
References DCHECK_NE, fast_iterable(), v8::internal::Descriptor::GetDetails(), v8::internal::Descriptor::GetKey(), v8::internal::Descriptor::GetValue(), v8::internal::key, kJsonFast, and v8::internal::value.
Referenced by Append(), CopyFrom(), and Replace().
Set() [2/2]
void v8::internal::DescriptorArray::Set (InternalIndex descriptor_number, Tagged< Name > key, Tagged< MaybeObject > value, PropertyDetails details) [inline]
Definition at line 326 of file descriptor-array-inl.h.
                                                                              {
  CHECK_LT(descriptor_number.as_int(), number_of_descriptors());
  SetKey(descriptor_number, key);
  SetDetails(descriptor_number, details);
  SetValue(descriptor_number, value);
  // Resetting the fast iterable state is bottlenecked in SetKey().
  DCHECK_NE(fast_iterable(), FastIterableState::kJsonFast);
}
References v8::internal::InternalIndex::as_int(), CHECK_LT, DCHECK_NE, fast_iterable(), v8::internal::key, kJsonFast, v8::internal::number_of_descriptors, SetDetails(), SetKey(), SetValue(), and v8::internal::value.
set_fast_iterable()
void v8::internal::DescriptorArray::set_fast_iterable (FastIterableState value) [inline]
Definition at line 57 of file descriptor-array-inl.h.
                                                               {
  uint32_t f = flags(kRelaxedLoad);
  f = FastIterableBits::update(f, value);
  set_flags(f, kRelaxedStore);
}
References v8::internal::flags, v8::kRelaxedLoad, v8::kRelaxedStore, and v8::internal::value.
set_fast_iterable_if()
void v8::internal::DescriptorArray::set_fast_iterable_if (FastIterableState new_value, FastIterableState if_value) [inline]
Definition at line 63 of file descriptor-array-inl.h.
                                                                       {
  uint32_t f = flags(kRelaxedLoad);
  if (FastIterableBits::decode(f) == if_value) {
    f = FastIterableBits::update(f, new_value);
    set_flags(f, kRelaxedStore);
  }
}
References v8::internal::flags, v8::kRelaxedLoad, and v8::kRelaxedStore.
Referenced by SetKey().
SetDetails()
void v8::internal::DescriptorArray::SetDetails (InternalIndex descriptor_number, PropertyDetails details) [inline], [private]
Definition at line 297 of file descriptor-array-inl.h.
                                                          {
  DCHECK_LT(descriptor_number.as_int(), number_of_descriptors());
  int entry_offset = OffsetOfDescriptorAt(descriptor_number.as_int());
  EntryDetailsField::Relaxed_Store(*this, entry_offset, details.AsSmi());
  // Note: fast_iteration depends on PropertyDetails::location().
  // However we don't reset it here as all path either go through SetKey(),
  // which invalidates fast_iteration, or don't change the location
  // (GeneralizeAllFields()).
}
References v8::internal::InternalIndex::as_int(), v8::internal::PropertyDetails::AsSmi(), DCHECK_LT, v8::internal::number_of_descriptors, OffsetOfDescriptorAt(), and v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Relaxed_Store().
Referenced by GeneralizeAllFields(), Set(), and SetSortedKey().
SetKey()
void v8::internal::DescriptorArray::SetKey (InternalIndex descriptor_number, Tagged< Name > key) [inline], [private]
Definition at line 228 of file descriptor-array-inl.h.
                                               {
  DCHECK_LT(descriptor_number.as_int(), number_of_descriptors());
  int entry_offset = OffsetOfDescriptorAt(descriptor_number.as_int());
  EntryKeyField::Relaxed_Store(*this, entry_offset, key);
  WRITE_BARRIER(*this, entry_offset + kEntryKeyOffset, key);
  // Conservatively assume that the new key might break fast iteration.
  // If the key was already known to be slow, it will stay slow.
  set_fast_iterable_if(FastIterableState::kUnknown,
                       FastIterableState::kJsonFast);
}
References v8::internal::InternalIndex::as_int(), DCHECK_LT, kEntryKeyOffset, v8::internal::key, kJsonFast, kUnknown, v8::internal::number_of_descriptors, OffsetOfDescriptorAt(), v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Relaxed_Store(), set_fast_iterable_if(), and WRITE_BARRIER.
Referenced by Set().
SetSortedKey()
void v8::internal::DescriptorArray::SetSortedKey (int pointer, int descriptor_number) [inline], [private]
Definition at line 254 of file descriptor-array-inl.h.
                                                                     {
  PropertyDetails details = GetDetails(InternalIndex(descriptor_number));
  SetDetails(InternalIndex(descriptor_number), details.set_pointer(pointer));
}
References GetDetails(), v8::internal::PropertyDetails::set_pointer(), and SetDetails().
Referenced by Append(), Sort(), and SwapSortedKeys().
SetValue()
void v8::internal::DescriptorArray::SetValue (InternalIndex descriptor_number, Tagged< MaybeObject > value) [inline], [private]
Definition at line 270 of file descriptor-array-inl.h.
                                                          {
  DCHECK_LT(descriptor_number.as_int(), number_of_descriptors());
  int entry_offset = OffsetOfDescriptorAt(descriptor_number.as_int());
  EntryValueField::Relaxed_Store(*this, entry_offset, value);
  WRITE_BARRIER(*this, entry_offset + kEntryValueOffset, value);
}
References v8::internal::InternalIndex::as_int(), DCHECK_LT, kEntryValueOffset, v8::internal::number_of_descriptors, OffsetOfDescriptorAt(), v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Relaxed_Store(), v8::internal::value, and WRITE_BARRIER.
Referenced by GeneralizeAllFields(), and Set().
SizeFor()
static constexpr int v8::internal::DescriptorArray::SizeFor (int number_of_all_descriptors) [inline], [static], [constexpr]
Definition at line 193 of file descriptor-array.h.
                                                              {
    return OffsetOfDescriptorAt(number_of_all_descriptors);
  }
Referenced by v8::internal::Heap::CreateEarlyReadOnlyMapsAndObjects(), v8::internal::FactoryBase< Impl >::NewDescriptorArray(), and v8::internal::HeapObject::SizeFromMap().
Sort()
void v8::internal::DescriptorArray::Sort ()
Definition at line 3973 of file objects.cc.
                           {
  // In-place heap sort.
  const int len = number_of_descriptors();
  // Reset sorting since the descriptor array might contain invalid pointers.
  for (int i = 0; i < len; ++i) SetSortedKey(i, i);
  // Bottom-up max-heap construction.
  // Index of the last node with children.
  int max_parent_index = (len / 2) - 1;
  for (int i = max_parent_index; i >= 0; --i) {
    int parent_index = i;
    const uint32_t parent_hash = GetSortedKey(i)->hash();
    while (parent_index <= max_parent_index) {
      int child_index = 2 * parent_index + 1;
      uint32_t child_hash = GetSortedKey(child_index)->hash();
      if (child_index + 1 < len) {
        uint32_t right_child_hash = GetSortedKey(child_index + 1)->hash();
        if (right_child_hash > child_hash) {
          child_index++;
          child_hash = right_child_hash;
        }
      }
      if (child_hash <= parent_hash) break;
      SwapSortedKeys(parent_index, child_index);
      // Now element at child_index could be < its children.
      parent_index = child_index; // parent_hash remains correct.
    }
  }
  // Extract elements and create sorted array.
  for (int i = len - 1; i > 0; --i) {
    // Put max element at the back of the array.
    SwapSortedKeys(0, i);
    // Shift down the new top element.
    int parent_index = 0;
    const uint32_t parent_hash = GetSortedKey(parent_index)->hash();
    max_parent_index = (i / 2) - 1;
    while (parent_index <= max_parent_index) {
      int child_index = parent_index * 2 + 1;
      uint32_t child_hash = GetSortedKey(child_index)->hash();
      if (child_index + 1 < i) {
        uint32_t right_child_hash = GetSortedKey(child_index + 1)->hash();
        if (right_child_hash > child_hash) {
          child_index++;
          child_hash = right_child_hash;
        }
      }
      if (child_hash <= parent_hash) break;
      SwapSortedKeys(parent_index, child_index);
      parent_index = child_index;
    }
  }
  DCHECK(IsSortedNoDuplicates());
}
References v8::internal::DCHECK(), GetSortedKey(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::number_of_descriptors, SetSortedKey(), and SwapSortedKeys().
SwapSortedKeys()
void v8::internal::DescriptorArray::SwapSortedKeys (int first, int second) [inline], [private]
Definition at line 374 of file descriptor-array-inl.h.
                                                          {
  int first_key = GetSortedKeyIndex(first);
  SetSortedKey(first, GetSortedKeyIndex(second));
  SetSortedKey(second, first_key);
}
References GetSortedKeyIndex(), and SetSortedKey().
Referenced by Sort().
ToDetailsIndex()
static constexpr int v8::internal::DescriptorArray::ToDetailsIndex (int descriptor_number) [inline], [static], [constexpr]
Definition at line 237 of file descriptor-array.h.
                                                             {
    return (descriptor_number * kEntrySize) + kEntryDetailsIndex;
  }
References cppgc::internal::anonymous_namespace{gc-info-table.cc}::kEntrySize.
Referenced by v8::internal::CodeStubAssembler::DescriptorArrayGetDetails(), and v8::internal::CodeStubAssembler::LoadDetailsByDescriptorEntry().
ToKeyIndex()
static constexpr int v8::internal::DescriptorArray::ToKeyIndex (int descriptor_number) [inline], [static], [constexpr]
Definition at line 242 of file descriptor-array.h.
                                                         {
    return (descriptor_number * kEntrySize) + kEntryKeyIndex;
  }
References cppgc::internal::anonymous_namespace{gc-info-table.cc}::kEntrySize.
Referenced by v8::internal::PrototypeCheckAssembler::CheckAndBranch(), v8::internal::AccessorAssembler::HandleStoreICTransitionMapHandlerCase(), and v8::internal::CodeStubAssembler::LoadKeyByDescriptorEntry().
ToValueIndex()
static constexpr int v8::internal::DescriptorArray::ToValueIndex (int descriptor_number) [inline], [static], [constexpr]
Definition at line 246 of file descriptor-array.h.
                                                           {
    return (descriptor_number * kEntrySize) + kEntryValueIndex;
  }
References cppgc::internal::anonymous_namespace{gc-info-table.cc}::kEntrySize.
Referenced by v8::internal::CodeStubAssembler::LoadFieldTypeByDescriptorEntry(), and v8::internal::CodeStubAssembler::LoadValueByDescriptorEntry().
Member Data Documentation
kEntryDetailsIndex
const int v8::internal::DescriptorArray::kEntryDetailsIndex = 1 [static]
Definition at line 213 of file descriptor-array.h.
kEntryDetailsOffset
const int v8::internal::DescriptorArray::kEntryDetailsOffset = kEntryDetailsIndex * kTaggedSize [static]
Definition at line 218 of file descriptor-array.h.
Referenced by v8::internal::CodeStubAssembler::LoadDetailsByKeyIndex().
kEntryKeyIndex
const int v8::internal::DescriptorArray::kEntryKeyIndex = 0 [static]
Definition at line 212 of file descriptor-array.h.
kEntryKeyOffset
const int v8::internal::DescriptorArray::kEntryKeyOffset = kEntryKeyIndex * kTaggedSize [static]
Definition at line 217 of file descriptor-array.h.
Referenced by v8::internal::CodeStubAssembler::LoadDetailsByKeyIndex(), v8::internal::CodeStubAssembler::LoadFieldTypeByKeyIndex(), v8::internal::CodeStubAssembler::LoadValueByKeyIndex(), and SetKey().
kEntrySize
const int v8::internal::DescriptorArray::kEntrySize = 3 [static]
Definition at line 215 of file descriptor-array.h.
Referenced by v8::internal::CodeStubAssembler::DescriptorEntryToIndex(), v8::internal::AccessorAssembler::HandleStoreICTransitionMapHandlerCase(), Initialize(), and v8::internal::CodeStubAssembler::LoadArrayLength().
kEntryValueIndex
const int v8::internal::DescriptorArray::kEntryValueIndex = 2 [static]
Definition at line 214 of file descriptor-array.h.
kEntryValueOffset
const int v8::internal::DescriptorArray::kEntryValueOffset = kEntryValueIndex * kTaggedSize [static]
Definition at line 219 of file descriptor-array.h.
Referenced by v8::internal::CodeStubAssembler::LoadFieldTypeByKeyIndex(), v8::internal::CodeStubAssembler::LoadValueByKeyIndex(), and SetValue().
kNotFound
const int v8::internal::DescriptorArray::kNotFound = -1 [static]
Definition at line 183 of file descriptor-array.h.
Referenced by SearchWithCache().
kSizeOfRawGcState
constexpr size_t v8::internal::DescriptorArray::kSizeOfRawGcState [static], [constexpr]
Initial value:
=
      kRawGcStateOffsetEnd - kRawGcStateOffset + 1
Definition at line 190 of file descriptor-array.h.
Referenced by v8::internal::Serializer::ObjectSerializer::OutputRawData().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/descriptor-array.h
/mnt/V8SourceCode/src/diagnostics/objects-printer.cc
/mnt/V8SourceCode/src/objects/descriptor-array-inl.h
/mnt/V8SourceCode/src/objects/objects.cc