v8::internal::compiler::turboshaft::WasmLoadEliminationReducer< Next > Class Template Reference
#include <wasm-load-elimination-reducer.h>
Public Member Functions
void Analyze ()
OpIndex REDUCE_INPUT_GRAPH() StructGet (OpIndex ig_index, const StructGetOp &op)
OpIndex REDUCE_INPUT_GRAPH() StructSet (OpIndex ig_index, const StructSetOp &op)
Private Attributes
WasmLoadEliminationAnalyzer analyzer_
Detailed Description
template<class Next>
class v8::internal::compiler::turboshaft::WasmLoadEliminationReducer< Next >
Definition at line 519 of file wasm-load-elimination-reducer.h.
Member Function Documentation
Analyze()
template<class Next >
void v8::internal::compiler::turboshaft::WasmLoadEliminationReducer< Next >::Analyze () [inline]
Definition at line 523 of file wasm-load-elimination-reducer.h.
                 {
    if (v8_flags.turboshaft_wasm_load_elimination) {
      DCHECK(AllowHandleDereference::IsAllowed());
      analyzer_.Run();
    }
    Next::Analyze();
  }
References v8::internal::compiler::turboshaft::WasmLoadEliminationReducer< Next >::analyzer_, v8::internal::DCHECK(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::Run(), and v8::internal::v8_flags.
StructGet()
template<class Next >
OpIndex REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::WasmLoadEliminationReducer< Next >::StructGet (OpIndex ig_index, const StructGetOp & op) [inline]
Definition at line 548 of file wasm-load-elimination-reducer.h.
                                                               {
    // Atomic loads are never eliminated (not even on unshared objects).
    if (v8_flags.turboshaft_wasm_load_elimination && !op.is_atomic()) {
      OpIndex ig_replacement_index = analyzer_.Replacement(ig_index);
      if (ig_replacement_index.valid()) {
        OpIndex replacement = Asm().MapToNewGraph(ig_replacement_index);
        return replacement;
      }
    }
    return Next::ReduceInputGraphStructGet(ig_index, op);
  }
References v8::internal::compiler::turboshaft::WasmLoadEliminationReducer< Next >::analyzer_, v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::Replacement(), v8::internal::v8_flags, and v8::internal::compiler::turboshaft::OpIndex::valid().
StructSet()
template<class Next >
OpIndex REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::WasmLoadEliminationReducer< Next >::StructSet (OpIndex ig_index, const StructSetOp & op) [inline]
Definition at line 561 of file wasm-load-elimination-reducer.h.
                                                               {
    if (v8_flags.turboshaft_wasm_load_elimination) {
      OpIndex ig_replacement_index = analyzer_.Replacement(ig_index);
      if (ig_replacement_index.valid()) {
        // For struct.set, "replace with itself" is a sentinel for
        // "unreachable", and those are the only replacements we schedule for
        // this operation.
        DCHECK_EQ(ig_replacement_index, ig_index);
        __ Unreachable();
        return OpIndex::Invalid();
      }
    }
    return Next::ReduceInputGraphStructSet(ig_index, op);
  }
References __, v8::internal::compiler::turboshaft::WasmLoadEliminationReducer< Next >::analyzer_, DCHECK_EQ, v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::Replacement(), v8::internal::v8_flags, and v8::internal::compiler::turboshaft::OpIndex::valid().
Member Data Documentation
analyzer_
template<class Next >
WasmLoadEliminationAnalyzer v8::internal::compiler::turboshaft::WasmLoadEliminationReducer< Next >::analyzer_ [private]
Initial value:
{
      Asm().data(), Asm().modifiable_input_graph(), Asm().phase_zone()}
Definition at line 578 of file wasm-load-elimination-reducer.h.
Referenced by v8::internal::compiler::turboshaft::WasmLoadEliminationReducer< Next >::Analyze(), v8::internal::compiler::turboshaft::WasmLoadEliminationReducer< Next >::StructGet(), and v8::internal::compiler::turboshaft::WasmLoadEliminationReducer< Next >::StructSet().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/wasm-load-elimination-reducer.h