v8::internal::RedirectActiveFunctions Class Reference
#include <debug-frames.h>
Public Types
enum class Mode { kUseOriginalBytecode
, kUseDebugBytecode
 }
Public Member Functions
RedirectActiveFunctions (Isolate *isolate, Tagged< SharedFunctionInfo > shared, Mode mode)
void VisitThread (Isolate *isolate, ThreadLocalTop *top) override
Private Attributes
Tagged< SharedFunctionInfo > shared_
Mode mode_
Additional Inherited Members
Detailed Description
Definition at line 69 of file debug-frames.h.
Member Enumeration Documentation
Mode
enum v8::internal::RedirectActiveFunctions::Mode [strong]
Enumerator
kUseOriginalBytecode
kUseDebugBytecode
Definition at line 71 of file debug-frames.h.
                  {
    kUseOriginalBytecode,
    kUseDebugBytecode,
  };
Constructor & Destructor Documentation
RedirectActiveFunctions()
v8::internal::RedirectActiveFunctions::RedirectActiveFunctions (Isolate * isolate, Tagged< SharedFunctionInfo > shared, Mode mode)
Definition at line 115 of file debug-frames.cc.
    : shared_(shared), mode_(mode) {
  DCHECK(shared->HasBytecodeArray());
  DCHECK_IMPLIES(mode == Mode::kUseDebugBytecode,
                 shared->HasDebugInfo(isolate));
}
References v8::internal::DCHECK(), DCHECK_IMPLIES, kUseDebugBytecode, and mode().
Member Function Documentation
VisitThread()
void v8::internal::RedirectActiveFunctions::VisitThread (Isolate * isolate, ThreadLocalTop * top) [override], [virtual]
Implements v8::internal::ThreadVisitor.
Definition at line 123 of file debug-frames.cc.
                                                               {
  for (JavaScriptStackFrameIterator it(isolate, top); !it.done();
       it.Advance()) {
    JavaScriptFrame* frame = it.frame();
    Tagged<JSFunction> function = frame->function();
    if (!frame->is_interpreted()) continue;
    if (function->shared() != shared_) continue;
    InterpretedFrame* interpreted_frame =
        reinterpret_cast<InterpretedFrame*>(frame);
    Tagged<BytecodeArray> bytecode =
        mode_ == Mode::kUseDebugBytecode
            ? shared_->GetDebugInfo(isolate)->DebugBytecodeArray(isolate)
            : shared_->GetBytecodeArray(isolate);
    interpreted_frame->PatchBytecodeArray(bytecode);
  }
}
References v8::internal::JavaScriptStackFrameIterator::done(), v8::internal::JavaScriptFrame::function(), v8::internal::StackFrame::is_interpreted(), kUseDebugBytecode, mode_, v8::internal::InterpretedFrame::PatchBytecodeArray(), and shared_.
Referenced by v8::internal::DebugInfo::ClearBreakInfo(), and v8::internal::Debug::PrepareFunctionForDebugExecution().
Member Data Documentation
mode_
Mode v8::internal::RedirectActiveFunctions::mode_ [private]
Definition at line 83 of file debug-frames.h.
Referenced by VisitThread().
shared_
Tagged<SharedFunctionInfo> v8::internal::RedirectActiveFunctions::shared_ [private]
Definition at line 82 of file debug-frames.h.
Referenced by VisitThread().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/debug/debug-frames.h
/mnt/V8SourceCode/src/debug/debug-frames.cc