v8::SourceGroup Class Reference
#include <d8.h>
Classes
class IsolateThread
Public Member Functions
SourceGroup ()
~SourceGroup ()
void Begin (char **argv, int offset)
void End (int offset)
bool Execute (Isolate *isolate)
void StartExecuteInThread ()
void WaitForThread (const i::ParkedScope &parked)
void JoinThread (const i::ParkedScope &parked)
Private Member Functions
void ExecuteInThread ()
void ExitShell (int exit_code)
Private Attributes
i::ParkingSemaphore next_semaphore_
i::ParkingSemaphore done_semaphore_
base::Thread * thread_
const char ** argv_
int begin_offset_
int end_offset_
Detailed Description
Definition at line 88 of file d8.h.
Constructor & Destructor Documentation
SourceGroup()
v8::SourceGroup::SourceGroup () [inline]
Definition at line 90 of file d8.h.
      : next_semaphore_(0),
        done_semaphore_(0),
        thread_(nullptr),
        argv_(nullptr),
        begin_offset_(0),
        end_offset_(0) {}
 SourceGroup()
v8::SourceGroup::~SourceGroup ()
Definition at line 5155 of file d8.cc.
                          {
  delete thread_;
  thread_ = nullptr;
}
Member Function Documentation
Begin()
void v8::SourceGroup::Begin (char ** argv, int offset) [inline]
Definition at line 100 of file d8.h.
                                      {
    argv_ = const_cast<const char**>(argv);
    begin_offset_ = offset;
  }
References argv_, and begin_offset_.
Referenced by v8::Shell::SetOptions().
End()
void v8::SourceGroup::End (int offset) [inline]
Definition at line 105 of file d8.h.
{ end_offset_ = offset; }
References end_offset_.
Referenced by v8::Shell::SetOptions().
Execute()
bool v8::SourceGroup::Execute (Isolate * isolate)
Definition at line 5169 of file d8.cc.
                                          {
  bool success = true;
#ifdef V8_FUZZILLI
  if (fuzzilli_reprl) {
    HandleScope handle_scope(isolate);
    Local<String> file_name =
        String::NewFromUtf8(isolate, "fuzzcode.js", NewStringType::kNormal)
            .ToLocalChecked();
    size_t script_size;
    CHECK_EQ(read(REPRL_CRFD, &script_size, 8), 8);
    char* buffer = new char[script_size + 1];
    char* ptr = buffer;
    size_t remaining = script_size;
    while (remaining > 0) {
      ssize_t rv = read(REPRL_DRFD, ptr, remaining);
      CHECK_GE(rv, 0);
      remaining -= rv;
      ptr += rv;
    }
    buffer[script_size] = 0;
    Local<String> source =
        String::NewFromUtf8(isolate, buffer, NewStringType::kNormal)
            .ToLocalChecked();
    delete[] buffer;
    Shell::set_script_executed();
    if (!Shell::ExecuteString(isolate, source, file_name,
                              Shell::kReportExceptions)) {
      return false;
    }
  }
#endif // V8_FUZZILLI
  for (int i = begin_offset_; i < end_offset_; ++i) {
    const char* arg = argv_[i];
    if (strcmp(arg, "-e") == 0 && i + 1 < end_offset_) {
      // Execute argument given to -e option directly.
      HandleScope handle_scope(isolate);
      Local<String> file_name = String::NewFromUtf8Literal(isolate, "unnamed");
      Local<String> source =
          String::NewFromUtf8(isolate, argv_[i + 1]).ToLocalChecked();
      Shell::set_script_executed();
      if (!Shell::ExecuteString(isolate, source, file_name,
                                Shell::kReportExceptions)) {
        success = false;
        break;
      }
      ++i;
      continue;
    } else if (ends_with(arg, ".mjs")) {
      Shell::set_script_executed();
      if (!Shell::ExecuteModule(isolate, arg)) {
        success = false;
        break;
      }
      continue;
    } else if (strcmp(arg, "--module") == 0 && i + 1 < end_offset_) {
      // Treat the next file as a module.
      arg = argv_[++i];
      Shell::set_script_executed();
      if (!Shell::ExecuteModule(isolate, arg)) {
        success = false;
        break;
      }
      continue;
    } else if (strcmp(arg, "--json") == 0 && i + 1 < end_offset_) {
      // Treat the next file as a JSON file.
      arg = argv_[++i];
      Shell::set_script_executed();
      if (!Shell::LoadJSON(isolate, arg)) {
        success = false;
        break;
      }
      continue;
    } else if (arg[0] == '-') {
      // Ignore other options. They have been parsed already.
      continue;
    }
    // Use all other arguments as names of files to load and run.
    HandleScope handle_scope(isolate);
    Local<String> file_name =
        String::NewFromUtf8(isolate, arg).ToLocalChecked();
    Local<String> source;
    if (!Shell::ReadFile(isolate, arg).ToLocal(&source)) {
      printf("Error reading '%s'\n", arg);
      base::OS::ExitProcess(1);
    }
    Shell::set_script_executed();
    Shell::update_script_size(source->Length());
    if (!Shell::ExecuteString(isolate, source, file_name,
                              Shell::kReportExceptions)) {
      success = false;
      break;
    }
  }
  return success;
}
References CHECK_EQ, CHECK_GE, v8::ends_with(), v8::Shell::ExecuteModule(), v8::Shell::ExecuteString(), v8::base::OS::ExitProcess(), v8::anonymous_namespace{d8.cc}::fuzzilli_reprl, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::kNormal, v8::Shell::kReportExceptions, v8::Shell::LoadJSON(), v8::String::NewFromUtf8(), v8::String::NewFromUtf8Literal(), v8::Shell::ReadFile(), REPRL_CRFD, REPRL_DRFD, v8::Shell::set_script_executed(), and v8::Shell::update_script_size().
Referenced by ExecuteInThread().
ExecuteInThread()
void v8::SourceGroup::ExecuteInThread () [private]
Definition at line 5271 of file d8.cc.
                                  {
  v8::base::FlushDenormalsScope denormals_scope(Shell::options.flush_denormals);
  Isolate::CreateParams create_params;
  create_params.array_buffer_allocator = Shell::array_buffer_allocator;
  Isolate* isolate = Isolate::New(create_params);
  {
    Isolate::Scope isolate_scope(isolate);
    D8Console console(isolate);
    Shell::Initialize(isolate, &console, false);
    PerIsolateData data(isolate);
    for (int i = 0; i < Shell::options.stress_runs; ++i) {
      next_semaphore_.ParkedWait(
          reinterpret_cast<i::Isolate*>(isolate)->main_thread_local_isolate());
      {
        Global<Context> global_context;
        HandleScope scope(isolate);
        {
          Local<Context> context;
          if (!Shell::CreateEvaluationContext(isolate).ToLocal(&context)) {
            DCHECK(isolate->IsExecutionTerminating());
            break;
          }
          global_context.Reset(isolate, context);
        }
        PerIsolateData::RealmScope realm_scope(isolate, global_context);
        InspectorClient inspector_client(isolate, global_context,
                                         Shell::options.enable_inspector);
        {
          // We cannot use a Context::Scope here, as it keeps a local handle to
          // the context and SourceGroup::Execute may execute a non-nestable
          // task, e.g. a stackless GC.
          global_context.Get(isolate)->Enter();
          Execute(isolate);
          global_context.Get(isolate)->Exit();
        }
        Shell::FinishExecuting(isolate, global_context);
      }
      Shell::CollectGarbage(isolate);
      done_semaphore_.Signal();
    }
    Shell::ResetOnProfileEndListener(isolate);
  }
  isolate->Dispose();
}
References v8::Isolate::CreateParams::array_buffer_allocator, v8::Shell::array_buffer_allocator, v8::Shell::CollectGarbage(), v8::Shell::CreateEvaluationContext(), DCHECK, v8::Isolate::Dispose(), done_semaphore_, Execute(), v8::Shell::FinishExecuting(), v8::PersistentBase< T >::Get(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::Shell::Initialize(), v8::Isolate::IsExecutionTerminating(), v8::Isolate::New(), next_semaphore_, v8::Shell::options, v8::internal::ParkingSemaphore::ParkedWait(), v8::PersistentBase< T >::Reset(), v8::Shell::ResetOnProfileEndListener(), v8::base::Semaphore::Signal(), and v8::ShellOptions::stress_runs.
Referenced by v8::SourceGroup::IsolateThread::Run().
ExitShell()
void v8::SourceGroup::ExitShell (int exit_code) [private]
JoinThread()
void v8::SourceGroup::JoinThread (const i::ParkedScope & parked)
Definition at line 5334 of file d8.cc.
                                                       {
  USE(parked);
  if (thread_ == nullptr) return;
  thread_->Join();
}
References v8::base::Thread::Join(), thread_, and USE.
StartExecuteInThread()
void v8::SourceGroup::StartExecuteInThread ()
Definition at line 5321 of file d8.cc.
                                       {
  if (thread_ == nullptr) {
    thread_ = new IsolateThread(this);
    CHECK(thread_->Start());
  }
  next_semaphore_.Signal();
}
References CHECK, next_semaphore_, v8::base::Semaphore::Signal(), v8::base::Thread::Start(), and thread_.
WaitForThread()
void v8::SourceGroup::WaitForThread (const i::ParkedScope & parked)
Definition at line 5329 of file d8.cc.
                                                          {
  if (thread_ == nullptr) return;
  done_semaphore_.ParkedWait(parked);
}
References done_semaphore_, v8::internal::ParkingSemaphore::ParkedWait(), and thread_.
Member Data Documentation
argv_
const char** v8::SourceGroup::argv_ [private]
Definition at line 133 of file d8.h.
Referenced by Begin().
begin_offset_
int v8::SourceGroup::begin_offset_ [private]
Definition at line 134 of file d8.h.
Referenced by Begin().
done_semaphore_
i::ParkingSemaphore v8::SourceGroup::done_semaphore_ [private]
Definition at line 128 of file d8.h.
Referenced by ExecuteInThread(), and WaitForThread().
end_offset_
int v8::SourceGroup::end_offset_ [private]
Definition at line 135 of file d8.h.
Referenced by End().
next_semaphore_
i::ParkingSemaphore v8::SourceGroup::next_semaphore_ [private]
Definition at line 127 of file d8.h.
Referenced by ExecuteInThread(), and StartExecuteInThread().
thread_
base::Thread* v8::SourceGroup::thread_ [private]
Definition at line 129 of file d8.h.
Referenced by JoinThread(), StartExecuteInThread(), and WaitForThread().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/d8/d8.h
/mnt/V8SourceCode/src/d8/d8.cc