v8::internal::maglev::ToNumberOrNumeric Class Reference
#include <maglev-ir.h>
Public Member Functions
ToNumberOrNumeric (uint64_t bitfield, Object::Conversion mode)
Input & value_input ()
Object::Conversion mode () const
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties
static constexpr Base::InputTypes kInputTypes {ValueRepresentation::kTagged}
Private Types
using Base = FixedInputValueNodeT< 1, ToNumberOrNumeric >
Private Attributes
const Object::Conversion mode_
Additional Inherited Members
Detailed Description
Definition at line 5137 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::ToNumberOrNumeric::Base = FixedInputValueNodeT<1, ToNumberOrNumeric> [private]
Definition at line 5138 of file maglev-ir.h.
Constructor & Destructor Documentation
ToNumberOrNumeric()
v8::internal::maglev::ToNumberOrNumeric::ToNumberOrNumeric (uint64_t bitfield, Object::Conversion mode) [inline], [explicit]
Definition at line 5141 of file maglev-ir.h.
      : Base(bitfield), mode_(mode) {}
Member Function Documentation
GenerateCode()
void v8::internal::maglev::ToNumberOrNumeric::GenerateCode (MaglevAssembler * , const ProcessingState &)
MaxCallStackArgs()
int v8::internal::maglev::ToNumberOrNumeric::MaxCallStackArgs () const
mode()
Object::Conversion v8::internal::maglev::ToNumberOrNumeric::mode () const [inline]
Definition at line 5150 of file maglev-ir.h.
{ return mode_; }
References mode_.
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::ToNumberOrNumeric::PrintParams (std::ostream & , MaglevGraphLabeller *) const [inline]
Definition at line 5155 of file maglev-ir.h.
{}
SetValueLocationConstraints()
void v8::internal::maglev::ToNumberOrNumeric::SetValueLocationConstraints ()
value_input()
Input& v8::internal::maglev::ToNumberOrNumeric::value_input () [inline]
Definition at line 5149 of file maglev-ir.h.
{ return Node::input(0); }
References v8::internal::maglev::NodeBase::input().
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::ToNumberOrNumeric::kInputTypes {ValueRepresentation::kTagged} [static], [constexpr]
Definition at line 5147 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::ToNumberOrNumeric::kProperties [static], [constexpr]
Initial value:
=
      OpProperties::DeferredCall() | OpProperties::CanCallUserCode()
Definition at line 5144 of file maglev-ir.h.
mode_
const Object::Conversion v8::internal::maglev::ToNumberOrNumeric::mode_ [private]
Definition at line 5158 of file maglev-ir.h.
Referenced by mode().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h