v8::internal::AllocationTraceNode Class Reference
#include <allocation-tracker.h>
Public Member Functions
AllocationTraceNode (AllocationTraceTree *tree, unsigned function_info_index)
~AllocationTraceNode ()
AllocationTraceNode (const AllocationTraceNode &)=delete
AllocationTraceNode & operator= (const AllocationTraceNode &)=delete
AllocationTraceNode * FindChild (unsigned function_info_index)
AllocationTraceNode * FindOrAddChild (unsigned function_info_index)
void AddAllocation (unsigned size)
unsigned function_info_index () const
unsigned allocation_size () const
unsigned allocation_count () const
unsigned id () const
const std::vector< AllocationTraceNode * > & children () const
void Print (int indent, AllocationTracker *tracker)
Private Attributes
AllocationTraceTree * tree_
unsigned function_info_index_
unsigned total_size_
unsigned allocation_count_
unsigned id_
std::vector< AllocationTraceNode * > children_
Detailed Description
Definition at line 32 of file allocation-tracker.h.
Constructor & Destructor Documentation
AllocationTraceNode() [1/2]
v8::internal::AllocationTraceNode::AllocationTraceNode (AllocationTraceTree * tree, unsigned function_info_index)
Definition at line 18 of file allocation-tracker.cc.
    : tree_(tree),
      function_info_index_(function_info_index),
      total_size_(0),
      allocation_count_(0),
      id_(tree->next_node_id()) {
}
Referenced by FindOrAddChild().
 AllocationTraceNode()
v8::internal::AllocationTraceNode::~AllocationTraceNode ()
Definition at line 28 of file allocation-tracker.cc.
                                          {
  for (AllocationTraceNode* node : children_) delete node;
}
References children_.
AllocationTraceNode() [2/2]
v8::internal::AllocationTraceNode::AllocationTraceNode (const AllocationTraceNode &) [delete]
Member Function Documentation
AddAllocation()
void v8::internal::AllocationTraceNode::AddAllocation (unsigned size)
Definition at line 53 of file allocation-tracker.cc.
                                                     {
  total_size_ += size;
  ++allocation_count_;
}
References allocation_count_, size(), and total_size_.
Referenced by v8::internal::AllocationTracker::AllocationEvent().
allocation_count()
unsigned v8::internal::AllocationTraceNode::allocation_count () const [inline]
Definition at line 45 of file allocation-tracker.h.
{ return allocation_count_; }
References allocation_count_.
Referenced by v8::internal::HeapSnapshotJSONSerializer::SerializeTraceNode().
allocation_size()
unsigned v8::internal::AllocationTraceNode::allocation_size () const [inline]
Definition at line 44 of file allocation-tracker.h.
{ return total_size_; }
References total_size_.
Referenced by v8::internal::HeapSnapshotJSONSerializer::SerializeTraceNode().
children()
const std::vector<AllocationTraceNode*>& v8::internal::AllocationTraceNode::children () const [inline]
Definition at line 47 of file allocation-tracker.h.
                                                          {
    return children_;
  }
References children_.
Referenced by v8::internal::HeapSnapshotJSONSerializer::SerializeTraceNode().
FindChild()
AllocationTraceNode * v8::internal::AllocationTraceNode::FindChild (unsigned function_info_index)
Definition at line 33 of file allocation-tracker.cc.
                                  {
  for (AllocationTraceNode* node : children_) {
    if (node->function_info_index() == function_info_index) return node;
  }
  return nullptr;
}
References children_, and function_info_index().
Referenced by FindOrAddChild().
FindOrAddChild()
AllocationTraceNode * v8::internal::AllocationTraceNode::FindOrAddChild (unsigned function_info_index)
Definition at line 42 of file allocation-tracker.cc.
                                  {
  AllocationTraceNode* child = FindChild(function_info_index);
  if (child == nullptr) {
    child = new AllocationTraceNode(tree_, function_info_index);
    children_.push_back(child);
  }
  return child;
}
References AllocationTraceNode(), children_, FindChild(), function_info_index(), and tree_.
Referenced by v8::internal::AllocationTraceTree::AddPathFromEnd().
function_info_index()
unsigned v8::internal::AllocationTraceNode::function_info_index () const [inline]
Definition at line 43 of file allocation-tracker.h.
{ return function_info_index_; }
References function_info_index_.
Referenced by FindChild(), FindOrAddChild(), and v8::internal::HeapSnapshotJSONSerializer::SerializeTraceNode().
id()
unsigned v8::internal::AllocationTraceNode::id () const [inline]
Definition at line 46 of file allocation-tracker.h.
{ return id_; }
References id_.
Referenced by v8::internal::AllocationTracker::AllocationEvent(), and v8::internal::HeapSnapshotJSONSerializer::SerializeTraceNode().
operator=()
AllocationTraceNode& v8::internal::AllocationTraceNode::operator= (const AllocationTraceNode &) [delete]
Print()
void v8::internal::AllocationTraceNode::Print (int indent, AllocationTracker * tracker)
Definition at line 59 of file allocation-tracker.cc.
                                                                      {
  base::OS::Print("%10u %10u %*c", total_size_, allocation_count_, indent, ' ');
  if (tracker != nullptr) {
    AllocationTracker::FunctionInfo* info =
        tracker->function_info_list()[function_info_index_];
    base::OS::Print("%s #%u", info->name, id_);
  } else {
    base::OS::Print("%u #%u", function_info_index_, id_);
  }
  base::OS::Print("\n");
  indent += 2;
  for (AllocationTraceNode* node : children_) {
    node->Print(indent, tracker);
  }
}
References allocation_count_, children_, function_info_index_, v8::internal::AllocationTracker::function_info_list(), id_, v8::internal::AllocationTracker::FunctionInfo::name, v8::internal::Print(), and total_size_.
Referenced by v8::internal::AllocationTraceTree::Print().
Member Data Documentation
allocation_count_
unsigned v8::internal::AllocationTraceNode::allocation_count_ [private]
Definition at line 57 of file allocation-tracker.h.
Referenced by AddAllocation(), allocation_count(), and Print().
children_
std::vector<AllocationTraceNode*> v8::internal::AllocationTraceNode::children_ [private]
Definition at line 59 of file allocation-tracker.h.
Referenced by children(), FindChild(), FindOrAddChild(), Print(), and ~AllocationTraceNode().
function_info_index_
unsigned v8::internal::AllocationTraceNode::function_info_index_ [private]
Definition at line 55 of file allocation-tracker.h.
Referenced by function_info_index(), and Print().
id_
unsigned v8::internal::AllocationTraceNode::id_ [private]
Definition at line 58 of file allocation-tracker.h.
Referenced by id(), and Print().
total_size_
unsigned v8::internal::AllocationTraceNode::total_size_ [private]
Definition at line 56 of file allocation-tracker.h.
Referenced by AddAllocation(), allocation_size(), and Print().
tree_
AllocationTraceTree* v8::internal::AllocationTraceNode::tree_ [private]
Definition at line 54 of file allocation-tracker.h.
Referenced by FindOrAddChild().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/profiler/allocation-tracker.h
/mnt/V8SourceCode/src/profiler/allocation-tracker.cc