v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::OolTrapLabel Class Reference
Public Member Functions
OolTrapLabel (LiftoffAssembler &assembler, Label *label)
Label * label () const
const FreezeCacheState & frozen () const
Private Attributes
Label * label_
FreezeCacheState freeze_
Detailed Description
Definition at line 3462 of file liftoff-compiler.cc.
Constructor & Destructor Documentation
OolTrapLabel()
v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::OolTrapLabel::OolTrapLabel (LiftoffAssembler & assembler, Label * label) [inline]
Definition at line 3464 of file liftoff-compiler.cc.
        : label_(label), freeze_(assembler) {}
Member Function Documentation
frozen()
const FreezeCacheState& v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::OolTrapLabel::frozen () const [inline]
Definition at line 3468 of file liftoff-compiler.cc.
{ return freeze_; }
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::AlignmentCheckMem(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayFill(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayNew(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::AssertNullTypecheckImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BoundsCheckArray(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BoundsCheckMem(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallIndirectImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CheckHighWordEmptyForTableType(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::MaybeEmitNullCheck(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::MemoryCopy(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::MemoryFill(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::MemoryInit(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::RefCastImpl().
label()
Label* v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::OolTrapLabel::label () const [inline]
Definition at line 3467 of file liftoff-compiler.cc.
{ return label_; }
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::AlignmentCheckMem(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayFill(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayNew(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::AssertNullTypecheckImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BoundsCheckArray(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BoundsCheckMem(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallIndirectImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CheckHighWordEmptyForTableType(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::MaybeEmitNullCheck(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::MemoryCopy(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::MemoryFill(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::MemoryInit(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::RefCastImpl(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Trap().
Member Data Documentation
freeze_
FreezeCacheState v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::OolTrapLabel::freeze_ [private]
Definition at line 3472 of file liftoff-compiler.cc.
label_
Label* v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::OolTrapLabel::label_ [private]
Definition at line 3471 of file liftoff-compiler.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/baseline/liftoff-compiler.cc