v8::internal::compiler::JSIntrinsicLowering Class Reference
#include <js-intrinsic-lowering.h>
Public Member Functions
JSIntrinsicLowering (Editor *editor, JSGraph *jsgraph, JSHeapBroker *broker)
~JSIntrinsicLowering () final=default
const char * reducer_name () const override
Reduction Reduce (Node *node) final
Private Types
enum FrameStateFlag { kNeedsFrameState
, kDoesNotNeedFrameState
 }
Private Member Functions
Reduction ReduceCopyDataProperties (Node *node)
Reduction ReduceCopyDataPropertiesWithExcludedPropertiesOnStack (Node *node)
Reduction ReduceCreateIterResultObject (Node *node)
Reduction ReduceDeoptimizeNow (Node *node)
Reduction ReduceCreateJSGeneratorObject (Node *node)
Reduction ReduceGeneratorClose (Node *node)
Reduction ReduceAsyncFunctionAwait (Node *node)
Reduction ReduceAsyncFunctionEnter (Node *node)
Reduction ReduceAsyncFunctionReject (Node *node)
Reduction ReduceAsyncFunctionResolve (Node *node)
Reduction ReduceAsyncGeneratorAwait (Node *node)
Reduction ReduceAsyncGeneratorReject (Node *node)
Reduction ReduceAsyncGeneratorResolve (Node *node)
Reduction ReduceAsyncGeneratorYieldWithAwait (Node *node)
Reduction ReduceGeneratorGetResumeMode (Node *node)
Reduction ReduceIsInstanceType (Node *node, InstanceType instance_type)
Reduction ReduceIsJSReceiver (Node *node)
Reduction ReduceIsBeingInterpreted (Node *node)
Reduction ReduceTurbofanStaticAssert (Node *node)
Reduction ReduceVerifyType (Node *node)
Reduction ReduceCheckTurboshaftTypeOf (Node *node)
Reduction ReduceToLength (Node *node)
Reduction ReduceToObject (Node *node)
Reduction ReduceToString (Node *node)
Reduction ReduceCall (Node *node)
Reduction ReduceIncBlockCounter (Node *node)
Reduction ReduceAddLhsIsStringConstantInternalize (Node *node)
Reduction ReduceAddRhsIsStringConstantInternalize (Node *node)
Reduction ReduceGetImportMetaObject (Node *node)
Reduction Change (Node *node, const Operator *op)
Reduction Change (Node *node, const Operator *op, Node *a, Node *b)
Reduction Change (Node *node, const Operator *op, Node *a, Node *b, Node *c)
Reduction Change (Node *node, const Operator *op, Node *a, Node *b, Node *c, Node *d)
Reduction Change (Node *node, Callable const &callable, int stack_parameter_count, enum FrameStateFlag frame_state_flag=kNeedsFrameState)
TFGraph * graph () const
JSGraph * jsgraph () const
JSHeapBroker * broker () const
Isolate * isolate () const
CommonOperatorBuilder * common () const
JSOperatorBuilder * javascript () const
SimplifiedOperatorBuilder * simplified () const
Private Attributes
JSGraph *const jsgraph_
JSHeapBroker *const broker_
Detailed Description
Definition at line 30 of file js-intrinsic-lowering.h.
Member Enumeration Documentation
FrameStateFlag
enum v8::internal::compiler::JSIntrinsicLowering::FrameStateFlag [private]
Enumerator
kNeedsFrameState
kDoesNotNeedFrameState
Definition at line 77 of file js-intrinsic-lowering.h.
                      {
    kNeedsFrameState,
    kDoesNotNeedFrameState,
  };
Constructor & Destructor Documentation
JSIntrinsicLowering()
v8::internal::compiler::JSIntrinsicLowering::JSIntrinsicLowering (Editor * editor, JSGraph * jsgraph, JSHeapBroker * broker)
Definition at line 23 of file js-intrinsic-lowering.cc.
    : AdvancedReducer(editor), jsgraph_(jsgraph), broker_(broker) {}
 JSIntrinsicLowering()
v8::internal::compiler::JSIntrinsicLowering::~JSIntrinsicLowering () [final], [default]
Member Function Documentation
broker()
JSHeapBroker* v8::internal::compiler::JSIntrinsicLowering::broker () const [inline], [private]
Definition at line 87 of file js-intrinsic-lowering.h.
{ return broker_; }
Referenced by ReduceToString().
Change() [1/5]
Reduction v8::internal::compiler::JSIntrinsicLowering::Change (Node * node, Callable const & callable, int stack_parameter_count, enum FrameStateFlag frame_state_flag = kNeedsFrameState) [private]
Definition at line 412 of file js-intrinsic-lowering.cc.
                                                                            {
  CallDescriptor::Flags flags = frame_state_flag == kNeedsFrameState
                                    ? CallDescriptor::kNeedsFrameState
                                    : CallDescriptor::kNoFlags;
  auto call_descriptor = Linkage::GetStubCallDescriptor(
      graph()->zone(), callable.descriptor(), stack_parameter_count, flags,
      node->op()->properties());
  node->InsertInput(graph()->zone(), 0,
                    jsgraph()->HeapConstantNoHole(callable.code()));
  NodeProperties::ChangeOp(node, common()->Call(call_descriptor));
  return Changed(node);
}
References v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::Callable::code(), common(), v8::internal::Callable::descriptor(), v8::internal::flags, v8::internal::compiler::Linkage::GetStubCallDescriptor(), graph(), v8::internal::compiler::HeapConstantNoHole(), v8::internal::compiler::Node::InsertInput(), jsgraph(), kNeedsFrameState, v8::internal::compiler::CallDescriptor::kNeedsFrameState, v8::internal::compiler::CallDescriptor::kNoFlags, v8::internal::compiler::Node::op(), and v8::internal::compiler::Operator::properties().
Change() [2/5]
Reduction v8::internal::compiler::JSIntrinsicLowering::Change (Node * node, const Operator * op) [private]
Definition at line 310 of file js-intrinsic-lowering.cc.
                                                                    {
  // Replace all effect uses of {node} with the effect dependency.
  RelaxEffectsAndControls(node);
  // Remove the inputs corresponding to context, effect and control.
  NodeProperties::RemoveNonValueInputs(node);
  // Finally update the operator to the new one.
  NodeProperties::ChangeOp(node, op);
  return Changed(node);
}
References v8::internal::compiler::NodeProperties::ChangeOp(), and v8::internal::compiler::NodeProperties::RemoveNonValueInputs().
Referenced by ReduceAddLhsIsStringConstantInternalize(), ReduceAddRhsIsStringConstantInternalize(), ReduceAsyncFunctionAwait(), ReduceAsyncGeneratorAwait(), ReduceAsyncGeneratorReject(), ReduceAsyncGeneratorResolve(), ReduceAsyncGeneratorYieldWithAwait(), ReduceCopyDataProperties(), ReduceCreateIterResultObject(), ReduceGeneratorClose(), ReduceGeneratorGetResumeMode(), ReduceIncBlockCounter(), ReduceIsInstanceType(), and ReduceIsJSReceiver().
Change() [3/5]
Reduction v8::internal::compiler::JSIntrinsicLowering::Change (Node * node, const Operator * op, Node * a, Node * b) [private]
Definition at line 379 of file js-intrinsic-lowering.cc.
                                               {
  RelaxControls(node);
  node->ReplaceInput(0, a);
  node->ReplaceInput(1, b);
  node->TrimInputCount(2);
  NodeProperties::ChangeOp(node, op);
  return Changed(node);
}
References v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::Node::ReplaceInput(), and v8::internal::compiler::Node::TrimInputCount().
Change() [4/5]
Reduction v8::internal::compiler::JSIntrinsicLowering::Change (Node * node, const Operator * op, Node * a, Node * b, Node * c) [private]
Definition at line 389 of file js-intrinsic-lowering.cc.
                                                        {
  RelaxControls(node);
  node->ReplaceInput(0, a);
  node->ReplaceInput(1, b);
  node->ReplaceInput(2, c);
  node->TrimInputCount(3);
  NodeProperties::ChangeOp(node, op);
  return Changed(node);
}
References v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::Node::ReplaceInput(), and v8::internal::compiler::Node::TrimInputCount().
Change() [5/5]
Reduction v8::internal::compiler::JSIntrinsicLowering::Change (Node * node, const Operator * op, Node * a, Node * b, Node * c, Node * d) [private]
Definition at line 400 of file js-intrinsic-lowering.cc.
                                                                 {
  RelaxControls(node);
  node->ReplaceInput(0, a);
  node->ReplaceInput(1, b);
  node->ReplaceInput(2, c);
  node->ReplaceInput(3, d);
  node->TrimInputCount(4);
  NodeProperties::ChangeOp(node, op);
  return Changed(node);
}
References v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::Node::ReplaceInput(), and v8::internal::compiler::Node::TrimInputCount().
common()
CommonOperatorBuilder * v8::internal::compiler::JSIntrinsicLowering::common () const [private]
Definition at line 431 of file js-intrinsic-lowering.cc.
                                                         {
  return jsgraph()->common();
}
References v8::internal::compiler::MachineGraph::common(), and jsgraph().
Referenced by Change(), ReduceCopyDataPropertiesWithExcludedPropertiesOnStack(), ReduceDeoptimizeNow(), ReduceIsInstanceType(), and ReduceTurbofanStaticAssert().
graph()
TFGraph * v8::internal::compiler::JSIntrinsicLowering::graph () const [private]
Definition at line 427 of file js-intrinsic-lowering.cc.
{ return jsgraph()->graph(); }
References v8::internal::compiler::MachineGraph::graph(), and jsgraph().
Referenced by Change(), ReduceCall(), ReduceCheckTurboshaftTypeOf(), ReduceCopyDataPropertiesWithExcludedPropertiesOnStack(), ReduceCreateJSGeneratorObject(), ReduceDeoptimizeNow(), ReduceIsInstanceType(), ReduceTurbofanStaticAssert(), and ReduceVerifyType().
isolate()
Isolate * v8::internal::compiler::JSIntrinsicLowering::isolate () const [private]
Definition at line 429 of file js-intrinsic-lowering.cc.
{ return jsgraph()->isolate(); }
References v8::internal::compiler::JSGraph::isolate(), and jsgraph().
Referenced by ReduceAddLhsIsStringConstantInternalize(), ReduceAddRhsIsStringConstantInternalize(), ReduceAsyncFunctionAwait(), ReduceAsyncGeneratorAwait(), ReduceAsyncGeneratorReject(), ReduceAsyncGeneratorResolve(), ReduceAsyncGeneratorYieldWithAwait(), ReduceCopyDataProperties(), ReduceCopyDataPropertiesWithExcludedPropertiesOnStack(), and ReduceIncBlockCounter().
javascript()
JSOperatorBuilder * v8::internal::compiler::JSIntrinsicLowering::javascript () const [private]
Definition at line 435 of file js-intrinsic-lowering.cc.
                                                         {
  return jsgraph_->javascript();
}
References v8::internal::compiler::JSGraph::javascript(), and jsgraph_.
Referenced by ReduceAsyncFunctionEnter(), ReduceAsyncFunctionReject(), ReduceAsyncFunctionResolve(), ReduceCall(), ReduceCreateIterResultObject(), ReduceCreateJSGeneratorObject(), ReduceGetImportMetaObject(), ReduceToLength(), ReduceToObject(), and ReduceToString().
jsgraph()
JSGraph* v8::internal::compiler::JSIntrinsicLowering::jsgraph () const [inline], [private]
Definition at line 86 of file js-intrinsic-lowering.h.
{ return jsgraph_; }
Referenced by Change(), common(), graph(), isolate(), ReduceCall(), ReduceCopyDataPropertiesWithExcludedPropertiesOnStack(), ReduceGeneratorClose(), ReduceIsInstanceType(), and simplified().
Reduce()
Reduction v8::internal::compiler::JSIntrinsicLowering::Reduce (Node * node) [final]
Definition at line 27 of file js-intrinsic-lowering.cc.
                                                {
  if (node->opcode() != IrOpcode::kJSCallRuntime) return NoChange();
  const Runtime::Function* const f =
      Runtime::FunctionForId(CallRuntimeParametersOf(node->op()).id());
  switch (f->function_id) {
    case Runtime::kIsBeingInterpreted:
      return ReduceIsBeingInterpreted(node);
    case Runtime::kTurbofanStaticAssert:
      return ReduceTurbofanStaticAssert(node);
    case Runtime::kVerifyType:
      return ReduceVerifyType(node);
    case Runtime::kCheckTurboshaftTypeOf:
      return ReduceCheckTurboshaftTypeOf(node);
    default:
      break;
  }
  if (f->intrinsic_type != Runtime::IntrinsicType::INLINE) return NoChange();
  switch (f->function_id) {
    case Runtime::kInlineCopyDataProperties:
      return ReduceCopyDataProperties(node);
    case Runtime::kInlineCopyDataPropertiesWithExcludedPropertiesOnStack:
      return ReduceCopyDataPropertiesWithExcludedPropertiesOnStack(node);
    case Runtime::kInlineCreateIterResultObject:
      return ReduceCreateIterResultObject(node);
    case Runtime::kInlineDeoptimizeNow:
      return ReduceDeoptimizeNow(node);
    case Runtime::kInlineGeneratorClose:
      return ReduceGeneratorClose(node);
    case Runtime::kInlineCreateJSGeneratorObject:
      return ReduceCreateJSGeneratorObject(node);
    case Runtime::kInlineAsyncFunctionAwait:
      return ReduceAsyncFunctionAwait(node);
    case Runtime::kInlineAsyncFunctionEnter:
      return ReduceAsyncFunctionEnter(node);
    case Runtime::kInlineAsyncFunctionReject:
      return ReduceAsyncFunctionReject(node);
    case Runtime::kInlineAsyncFunctionResolve:
      return ReduceAsyncFunctionResolve(node);
    case Runtime::kInlineAsyncGeneratorAwait:
      return ReduceAsyncGeneratorAwait(node);
    case Runtime::kInlineAsyncGeneratorReject:
      return ReduceAsyncGeneratorReject(node);
    case Runtime::kInlineAsyncGeneratorResolve:
      return ReduceAsyncGeneratorResolve(node);
    case Runtime::kInlineAsyncGeneratorYieldWithAwait:
      return ReduceAsyncGeneratorYieldWithAwait(node);
    case Runtime::kInlineGeneratorGetResumeMode:
      return ReduceGeneratorGetResumeMode(node);
    case Runtime::kInlineIncBlockCounter:
      return ReduceIncBlockCounter(node);
    case Runtime::kInlineAddLhsIsStringConstantInternalize:
      return ReduceAddLhsIsStringConstantInternalize(node);
    case Runtime::kInlineAddRhsIsStringConstantInternalize:
      return ReduceAddRhsIsStringConstantInternalize(node);
    case Runtime::kInlineGetImportMetaObject:
      return ReduceGetImportMetaObject(node);
    default:
      break;
  }
  return NoChange();
}
References v8::internal::compiler::CallRuntimeParametersOf(), v8::internal::Runtime::Function::function_id, v8::internal::Runtime::FunctionForId(), v8::internal::compiler::CallRuntimeParameters::id(), v8::internal::Runtime::Function::intrinsic_type, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), ReduceAddLhsIsStringConstantInternalize(), ReduceAddRhsIsStringConstantInternalize(), ReduceAsyncFunctionAwait(), ReduceAsyncFunctionEnter(), ReduceAsyncFunctionReject(), ReduceAsyncFunctionResolve(), ReduceAsyncGeneratorAwait(), ReduceAsyncGeneratorReject(), ReduceAsyncGeneratorResolve(), ReduceAsyncGeneratorYieldWithAwait(), ReduceCheckTurboshaftTypeOf(), ReduceCopyDataProperties(), ReduceCopyDataPropertiesWithExcludedPropertiesOnStack(), ReduceCreateIterResultObject(), ReduceCreateJSGeneratorObject(), ReduceDeoptimizeNow(), ReduceGeneratorClose(), ReduceGeneratorGetResumeMode(), ReduceGetImportMetaObject(), ReduceIncBlockCounter(), ReduceIsBeingInterpreted(), ReduceTurbofanStaticAssert(), and ReduceVerifyType().
ReduceAddLhsIsStringConstantInternalize()
Reduction v8::internal::compiler::JSIntrinsicLowering::ReduceAddLhsIsStringConstantInternalize (Node * node) [private]
Definition at line 362 of file js-intrinsic-lowering.cc.
                {
  auto builtin = Builtin::kAddLhsIsStringConstantInternalizeWithVector;
  return Change(node, Builtins::CallableFor(isolate(), builtin), 0);
}
References v8::internal::Builtins::CallableFor(), Change(), and isolate().
Referenced by Reduce().
ReduceAddRhsIsStringConstantInternalize()
Reduction v8::internal::compiler::JSIntrinsicLowering::ReduceAddRhsIsStringConstantInternalize (Node * node) [private]
Definition at line 368 of file js-intrinsic-lowering.cc.
                {
  auto builtin = Builtin::kAddRhsIsStringConstantInternalizeWithVector;
  return Change(node, Builtins::CallableFor(isolate(), builtin), 0);
}
References v8::internal::Builtins::CallableFor(), Change(), and isolate().
Referenced by Reduce().
ReduceAsyncFunctionAwait()
Reduction v8::internal::compiler::JSIntrinsicLowering::ReduceAsyncFunctionAwait (Node * node) [private]
Definition at line 165 of file js-intrinsic-lowering.cc.
                                                                  {
  return Change(
      node, Builtins::CallableFor(isolate(), Builtin::kAsyncFunctionAwait), 0);
}
References v8::internal::Builtins::CallableFor(), Change(), and isolate().
Referenced by Reduce().
ReduceAsyncFunctionEnter()
Reduction v8::internal::compiler::JSIntrinsicLowering::ReduceAsyncFunctionEnter (Node * node) [private]
Definition at line 170 of file js-intrinsic-lowering.cc.
                                                                  {
  NodeProperties::ChangeOp(node, javascript()->AsyncFunctionEnter());
  return Changed(node);
}
References v8::internal::compiler::NodeProperties::ChangeOp(), and javascript().
Referenced by Reduce().
ReduceAsyncFunctionReject()
Reduction v8::internal::compiler::JSIntrinsicLowering::ReduceAsyncFunctionReject (Node * node) [private]
Definition at line 175 of file js-intrinsic-lowering.cc.
                                                                   {
  RelaxControls(node);
  NodeProperties::ChangeOp(node, javascript()->AsyncFunctionReject());
  return Changed(node);
}
References v8::internal::compiler::NodeProperties::ChangeOp(), and javascript().
Referenced by Reduce().
ReduceAsyncFunctionResolve()
Reduction v8::internal::compiler::JSIntrinsicLowering::ReduceAsyncFunctionResolve (Node * node) [private]
Definition at line 181 of file js-intrinsic-lowering.cc.
                                                                    {
  RelaxControls(node);
  NodeProperties::ChangeOp(node, javascript()->AsyncFunctionResolve());
  return Changed(node);
}
References v8::internal::compiler::NodeProperties::ChangeOp(), and javascript().
Referenced by Reduce().
ReduceAsyncGeneratorAwait()
Reduction v8::internal::compiler::JSIntrinsicLowering::ReduceAsyncGeneratorAwait (Node * node) [private]
Definition at line 187 of file js-intrinsic-lowering.cc.
                                                                   {
  return Change(
      node, Builtins::CallableFor(isolate(), Builtin::kAsyncGeneratorAwait), 0);
}
References v8::internal::Builtins::CallableFor(), Change(), and isolate().
Referenced by Reduce().
ReduceAsyncGeneratorReject()
Reduction v8::internal::compiler::JSIntrinsicLowering::ReduceAsyncGeneratorReject (Node * node) [private]
Definition at line 192 of file js-intrinsic-lowering.cc.
                                                                    {
  return Change(
      node, Builtins::CallableFor(isolate(), Builtin::kAsyncGeneratorReject),
      0);
}
References v8::internal::Builtins::CallableFor(), Change(), and isolate().
Referenced by Reduce().
ReduceAsyncGeneratorResolve()
Reduction v8::internal::compiler::JSIntrinsicLowering::ReduceAsyncGeneratorResolve (Node * node) [private]
Definition at line 198 of file js-intrinsic-lowering.cc.
                                                                     {
  return Change(
      node, Builtins::CallableFor(isolate(), Builtin::kAsyncGeneratorResolve),
      0);
}
References v8::internal::Builtins::CallableFor(), Change(), and isolate().
Referenced by Reduce().
ReduceAsyncGeneratorYieldWithAwait()
Reduction v8::internal::compiler::JSIntrinsicLowering::ReduceAsyncGeneratorYieldWithAwait (Node * node) [private]
Definition at line 204 of file js-intrinsic-lowering.cc.
                                                                            {
  return Change(
      node,
      Builtins::CallableFor(isolate(), Builtin::kAsyncGeneratorYieldWithAwait),
      0);
}
References v8::internal::Builtins::CallableFor(), Change(), and isolate().
Referenced by Reduce().
ReduceCall()
Reduction v8::internal::compiler::JSIntrinsicLowering::ReduceCall (Node * node) [private]
Definition at line 341 of file js-intrinsic-lowering.cc.
                                                    {
  int const arity =
      static_cast<int>(CallRuntimeParametersOf(node->op()).arity());
  static constexpr int kTargetAndReceiver = 2;
  static_assert(JSCallNode::kFeedbackVectorIsLastInput);
  Node* feedback = jsgraph()->UndefinedConstant();
  node->InsertInput(graph()->zone(), arity, feedback);
  NodeProperties::ChangeOp(
      node,
      javascript()->Call(JSCallNode::ArityForArgc(arity - kTargetAndReceiver)));
  return Changed(node);
}
References v8::internal::compiler::CallRuntimeParameters::arity(), v8::internal::compiler::JSCallOrConstructNode::ArityForArgc(), v8::internal::compiler::CallRuntimeParametersOf(), v8::internal::compiler::NodeProperties::ChangeOp(), graph(), v8::internal::compiler::Node::InsertInput(), javascript(), jsgraph(), v8::internal::compiler::JSCallOrConstructNode::kFeedbackVectorIsLastInput, and v8::internal::compiler::Node::op().
ReduceCheckTurboshaftTypeOf()
Reduction v8::internal::compiler::JSIntrinsicLowering::ReduceCheckTurboshaftTypeOf (Node * node) [private]
Definition at line 288 of file js-intrinsic-lowering.cc.
                                                                     {
  Node* value = node->InputAt(0);
  if (!v8_flags.turboshaft) {
    RelaxEffectsAndControls(node);
    ReplaceWithValue(node, value);
    return Changed(value);
  }
  Node* pattern = node->InputAt(1);
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  Node* check = graph()->NewNode(simplified()->CheckTurboshaftTypeOf(), value,
                                 pattern, effect, control);
  ReplaceWithValue(node, value, check);
  return Changed(value);
}
References v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), graph(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::TFGraph::NewNode(), simplified(), v8::internal::v8_flags, and v8::internal::value.
Referenced by Reduce().
ReduceCopyDataProperties()
Reduction v8::internal::compiler::JSIntrinsicLowering::ReduceCopyDataProperties (Node * node) [private]
Definition at line 89 of file js-intrinsic-lowering.cc.
                                                                  {
  return Change(
      node, Builtins::CallableFor(isolate(), Builtin::kCopyDataProperties), 0);
}
References v8::internal::Builtins::CallableFor(), Change(), and isolate().
Referenced by Reduce().
ReduceCopyDataPropertiesWithExcludedPropertiesOnStack()
Reduction v8::internal::compiler::JSIntrinsicLowering::ReduceCopyDataPropertiesWithExcludedPropertiesOnStack (Node * node) [private]
Definition at line 95 of file js-intrinsic-lowering.cc.
                {
  int input_count =
      static_cast<int>(CallRuntimeParametersOf(node->op()).arity());
  CallDescriptor::Flags flags = CallDescriptor::kNeedsFrameState;
  auto callable = Builtins::CallableFor(
      isolate(), Builtin::kCopyDataPropertiesWithExcludedProperties);
  auto call_descriptor = Linkage::GetStubCallDescriptor(
      graph()->zone(), callable.descriptor(), input_count - 1, flags,
      node->op()->properties());
  node->InsertInput(graph()->zone(), 0,
                    jsgraph()->HeapConstantNoHole(callable.code()));
  node->InsertInput(graph()->zone(), 2,
                    jsgraph()->SmiConstant(input_count - 1));
  NodeProperties::ChangeOp(node, common()->Call(call_descriptor));
  return Changed(node);
}
References v8::internal::compiler::CallRuntimeParameters::arity(), v8::internal::Builtins::CallableFor(), v8::internal::compiler::CallRuntimeParametersOf(), v8::internal::compiler::NodeProperties::ChangeOp(), common(), v8::internal::flags, v8::internal::compiler::Linkage::GetStubCallDescriptor(), graph(), v8::internal::compiler::HeapConstantNoHole(), v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::Node::InsertInput(), isolate(), jsgraph(), v8::internal::compiler::CallDescriptor::kNeedsFrameState, v8::internal::compiler::Node::op(), and v8::internal::compiler::Operator::properties().
Referenced by Reduce().
ReduceCreateIterResultObject()
Reduction v8::internal::compiler::JSIntrinsicLowering::ReduceCreateIterResultObject (Node * node) [private]
Definition at line 113 of file js-intrinsic-lowering.cc.
                                                                      {
  Node* const value = NodeProperties::GetValueInput(node, 0);
  Node* const done = NodeProperties::GetValueInput(node, 1);
  Node* const context = NodeProperties::GetContextInput(node);
  Node* const effect = NodeProperties::GetEffectInput(node);
  return Change(node, javascript()->CreateIterResultObject(), value, done,
                context, effect);
}
References Change(), v8::internal::compiler::NodeProperties::GetContextInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), javascript(), and v8::internal::value.
Referenced by Reduce().
ReduceCreateJSGeneratorObject()
Reduction v8::internal::compiler::JSIntrinsicLowering::ReduceCreateJSGeneratorObject (Node * node) [private]
Definition at line 137 of file js-intrinsic-lowering.cc.
                                                                       {
  Node* const closure = NodeProperties::GetValueInput(node, 0);
  Node* const receiver = NodeProperties::GetValueInput(node, 1);
  Node* const context = NodeProperties::GetContextInput(node);
  Node* const effect = NodeProperties::GetEffectInput(node);
  Node* const control = NodeProperties::GetControlInput(node);
  Operator const* const op = javascript()->CreateGeneratorObject();
  Node* create_generator =
      graph()->NewNode(op, closure, receiver, context, effect, control);
  ReplaceWithValue(node, create_generator, create_generator);
  return Changed(create_generator);
}
References v8::internal::compiler::JSOperatorBuilder::CreateGeneratorObject(), v8::internal::compiler::NodeProperties::GetContextInput(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), javascript(), and v8::internal::compiler::TFGraph::NewNode().
Referenced by Reduce().
ReduceDeoptimizeNow()
Reduction v8::internal::compiler::JSIntrinsicLowering::ReduceDeoptimizeNow (Node * node) [private]
Definition at line 122 of file js-intrinsic-lowering.cc.
                                                             {
  Node* const frame_state = NodeProperties::GetFrameStateInput(node);
  Node* const effect = NodeProperties::GetEffectInput(node);
  Node* const control = NodeProperties::GetControlInput(node);
  Node* deoptimize = graph()->NewNode(
      common()->Deoptimize(DeoptimizeReason::kDeoptimizeNow, FeedbackSource()),
      frame_state, effect, control);
  MergeControlToEnd(graph(), common(), deoptimize);
  node->TrimInputCount(0);
  NodeProperties::ChangeOp(node, common()->Dead());
  return Changed(node);
}
References v8::internal::compiler::NodeProperties::ChangeOp(), common(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetFrameStateInput(), graph(), v8::internal::compiler::TFGraph::NewNode(), and v8::internal::compiler::Node::TrimInputCount().
Referenced by Reduce().
ReduceGeneratorClose()
Reduction v8::internal::compiler::JSIntrinsicLowering::ReduceGeneratorClose (Node * node) [private]
Definition at line 150 of file js-intrinsic-lowering.cc.
                                                              {
  Node* const generator = NodeProperties::GetValueInput(node, 0);
  Node* const effect = NodeProperties::GetEffectInput(node);
  Node* const control = NodeProperties::GetControlInput(node);
  Node* const closed =
      jsgraph()->ConstantNoHole(JSGeneratorObject::kGeneratorClosed);
  Node* const undefined = jsgraph()->UndefinedConstant();
  Operator const* const op = simplified()->StoreField(
      AccessBuilder::ForJSGeneratorObjectContinuation());
  ReplaceWithValue(node, undefined, node);
  NodeProperties::RemoveType(node);
  return Change(node, op, generator, closed, effect, control);
}
References Change(), v8::internal::compiler::JSGraph::ConstantNoHole(), v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectContinuation(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), jsgraph(), v8::internal::JSGeneratorObject::kGeneratorClosed, v8::internal::compiler::NodeProperties::RemoveType(), simplified(), v8::internal::compiler::SimplifiedOperatorBuilder::StoreField(), and v8::internal::undefined.
Referenced by Reduce().
ReduceGeneratorGetResumeMode()
Reduction v8::internal::compiler::JSIntrinsicLowering::ReduceGeneratorGetResumeMode (Node * node) [private]
Definition at line 211 of file js-intrinsic-lowering.cc.
                                                                      {
  Node* const generator = NodeProperties::GetValueInput(node, 0);
  Node* const effect = NodeProperties::GetEffectInput(node);
  Node* const control = NodeProperties::GetControlInput(node);
  Operator const* const op =
      simplified()->LoadField(AccessBuilder::ForJSGeneratorObjectResumeMode());
  return Change(node, op, generator, effect, control);
}
References Change(), v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectResumeMode(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::SimplifiedOperatorBuilder::LoadField(), and simplified().
Referenced by Reduce().
ReduceGetImportMetaObject()
Reduction v8::internal::compiler::JSIntrinsicLowering::ReduceGetImportMetaObject (Node * node) [private]
Definition at line 374 of file js-intrinsic-lowering.cc.
                                                                   {
  NodeProperties::ChangeOp(node, javascript()->GetImportMeta());
  return Changed(node);
}
References v8::internal::compiler::NodeProperties::ChangeOp(), and javascript().
Referenced by Reduce().
ReduceIncBlockCounter()
Reduction v8::internal::compiler::JSIntrinsicLowering::ReduceIncBlockCounter (Node * node) [private]
Definition at line 354 of file js-intrinsic-lowering.cc.
                                                               {
  DCHECK(!Linkage::NeedsFrameStateInput(Runtime::kIncBlockCounter));
  DCHECK(!Linkage::NeedsFrameStateInput(Runtime::kInlineIncBlockCounter));
  return Change(node,
                Builtins::CallableFor(isolate(), Builtin::kIncBlockCounter), 0,
                kDoesNotNeedFrameState);
}
References v8::internal::Builtins::CallableFor(), Change(), v8::internal::DCHECK(), isolate(), kDoesNotNeedFrameState, and v8::internal::compiler::Linkage::NeedsFrameStateInput().
Referenced by Reduce().
ReduceIsBeingInterpreted()
Reduction v8::internal::compiler::JSIntrinsicLowering::ReduceIsBeingInterpreted (Node * node) [private]
Definition at line 305 of file js-intrinsic-lowering.cc.
                                                                  {
  RelaxEffectsAndControls(node);
  return Changed(jsgraph_->FalseConstant());
}
References jsgraph_.
Referenced by Reduce().
ReduceIsInstanceType()
Reduction v8::internal::compiler::JSIntrinsicLowering::ReduceIsInstanceType (Node * node, InstanceType instance_type) [private]
Definition at line 221 of file js-intrinsic-lowering.cc.
                                            {
  // if (%_IsSmi(value)) {
  // return false;
  // } else {
  // return %_GetInstanceType(%_GetMap(value)) == instance_type;
  // }
  Node* value = NodeProperties::GetValueInput(node, 0);
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  Node* check = graph()->NewNode(simplified()->ObjectIsSmi(), value);
  Node* branch = graph()->NewNode(common()->Branch(), check, control);
  Node* if_true = graph()->NewNode(common()->IfTrue(), branch);
  Node* etrue = effect;
  Node* vtrue = jsgraph()->FalseConstant();
  Node* if_false = graph()->NewNode(common()->IfFalse(), branch);
  Node* efalse = effect;
  Node* map = efalse =
      graph()->NewNode(simplified()->LoadField(AccessBuilder::ForMap()), value,
                       efalse, if_false);
  Node* map_instance_type = efalse = graph()->NewNode(
      simplified()->LoadField(AccessBuilder::ForMapInstanceType()), map, efalse,
      if_false);
  Node* vfalse =
      graph()->NewNode(simplified()->NumberEqual(), map_instance_type,
                       jsgraph()->ConstantNoHole(instance_type));
  Node* merge = graph()->NewNode(common()->Merge(2), if_true, if_false);
  // Replace all effect uses of {node} with the {ephi}.
  Node* ephi = graph()->NewNode(common()->EffectPhi(2), etrue, efalse, merge);
  ReplaceWithValue(node, node, ephi, merge);
  // Turn the {node} into a Phi.
  return Change(node, common()->Phi(MachineRepresentation::kTagged, 2), vtrue,
                vfalse, merge);
}
References Change(), common(), v8::internal::compiler::AccessBuilder::ForMap(), v8::internal::compiler::AccessBuilder::ForMapInstanceType(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), jsgraph(), v8::internal::kTagged, v8::internal::compiler::TFGraph::NewNode(), simplified(), and v8::internal::value.
ReduceIsJSReceiver()
Reduction v8::internal::compiler::JSIntrinsicLowering::ReduceIsJSReceiver (Node * node) [private]
Definition at line 262 of file js-intrinsic-lowering.cc.
                                                            {
  return Change(node, simplified()->ObjectIsReceiver());
}
References Change(), and simplified().
reducer_name()
const char* v8::internal::compiler::JSIntrinsicLowering::reducer_name () const [inline], [override]
Definition at line 36 of file js-intrinsic-lowering.h.
{ return "JSIntrinsicLowering"; }
ReduceToLength()
Reduction v8::internal::compiler::JSIntrinsicLowering::ReduceToLength (Node * node) [private]
Definition at line 320 of file js-intrinsic-lowering.cc.
                                                        {
  NodeProperties::ChangeOp(node, javascript()->ToLength());
  return Changed(node);
}
References v8::internal::compiler::NodeProperties::ChangeOp(), and javascript().
ReduceToObject()
Reduction v8::internal::compiler::JSIntrinsicLowering::ReduceToObject (Node * node) [private]
Definition at line 325 of file js-intrinsic-lowering.cc.
                                                        {
  NodeProperties::ChangeOp(node, javascript()->ToObject());
  return Changed(node);
}
References v8::internal::compiler::NodeProperties::ChangeOp(), javascript(), and v8::anonymous_namespace{api.cc}::ToObject().
ReduceToString()
Reduction v8::internal::compiler::JSIntrinsicLowering::ReduceToString (Node * node) [private]
Definition at line 330 of file js-intrinsic-lowering.cc.
                                                        {
  // ToString is unnecessary if the input is a string.
  HeapObjectMatcher m(NodeProperties::GetValueInput(node, 0));
  if (m.HasResolvedValue() && m.Ref(broker()).IsString()) {
    ReplaceWithValue(node, m.node());
    return Replace(m.node());
  }
  NodeProperties::ChangeOp(node, javascript()->ToString());
  return Changed(node);
}
References broker(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), javascript(), v8::internal::compiler::NodeMatcher::node(), v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Ref(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), and v8::internal::compiler::ToString().
ReduceTurbofanStaticAssert()
Reduction v8::internal::compiler::JSIntrinsicLowering::ReduceTurbofanStaticAssert (Node * node) [private]
Definition at line 266 of file js-intrinsic-lowering.cc.
                                                                    {
  if (v8_flags.always_turbofan) {
    // Ignore static asserts, as we most likely won't have enough information
    RelaxEffectsAndControls(node);
  } else {
    Node* value = NodeProperties::GetValueInput(node, 0);
    Node* effect = NodeProperties::GetEffectInput(node);
    Node* assert = graph()->NewNode(
        common()->StaticAssert("%TurbofanStaticAssert"), value, effect);
    ReplaceWithValue(node, node, assert, nullptr);
  }
  return Changed(jsgraph_->UndefinedConstant());
}
References common(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), jsgraph_, v8::internal::compiler::TFGraph::NewNode(), v8::internal::v8_flags, and v8::internal::value.
Referenced by Reduce().
ReduceVerifyType()
Reduction v8::internal::compiler::JSIntrinsicLowering::ReduceVerifyType (Node * node) [private]
Definition at line 280 of file js-intrinsic-lowering.cc.
                                                          {
  Node* value = NodeProperties::GetValueInput(node, 0);
  Node* effect = NodeProperties::GetEffectInput(node);
  effect = graph()->NewNode(simplified()->VerifyType(), value, effect);
  ReplaceWithValue(node, value, effect);
  return Changed(effect);
}
References v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::TFGraph::NewNode(), simplified(), and v8::internal::value.
Referenced by Reduce().
simplified()
SimplifiedOperatorBuilder * v8::internal::compiler::JSIntrinsicLowering::simplified () const [private]
Definition at line 439 of file js-intrinsic-lowering.cc.
                                                                 {
  return jsgraph()->simplified();
}
References jsgraph(), and v8::internal::compiler::JSGraph::simplified().
Referenced by ReduceCheckTurboshaftTypeOf(), ReduceGeneratorClose(), ReduceGeneratorGetResumeMode(), ReduceIsInstanceType(), ReduceIsJSReceiver(), and ReduceVerifyType().
Member Data Documentation
broker_
JSHeapBroker* const v8::internal::compiler::JSIntrinsicLowering::broker_ [private]
Definition at line 94 of file js-intrinsic-lowering.h.
jsgraph_
JSGraph* const v8::internal::compiler::JSIntrinsicLowering::jsgraph_ [private]
Definition at line 93 of file js-intrinsic-lowering.h.
Referenced by javascript(), ReduceIsBeingInterpreted(), and ReduceTurbofanStaticAssert().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/js-intrinsic-lowering.h
/mnt/V8SourceCode/src/compiler/js-intrinsic-lowering.cc