v8::internal::interpreter::BytecodeGenerator::DisposablesStackScope Class Reference
Public Member Functions
DisposablesStackScope (BytecodeGenerator *bytecode_generator)
~DisposablesStackScope ()
Private Attributes
BytecodeGenerator *const bytecode_generator_
Register prev_disposables_stack_
Detailed Description
Definition at line 1324 of file bytecode-generator.cc.
Constructor & Destructor Documentation
DisposablesStackScope()
v8::internal::interpreter::BytecodeGenerator::DisposablesStackScope::DisposablesStackScope (BytecodeGenerator * bytecode_generator) [inline], [explicit]
Definition at line 1326 of file bytecode-generator.cc.
      : bytecode_generator_(bytecode_generator),
        prev_disposables_stack_(
            bytecode_generator_->current_disposables_stack_) {
    bytecode_generator_->set_current_disposables_stack(
        bytecode_generator->register_allocator()->NewRegister());
    bytecode_generator->builder()->CallRuntime(
        Runtime::kInitializeDisposableStack);
    bytecode_generator->builder()->StoreAccumulatorInRegister(
        bytecode_generator_->current_disposables_stack());
  }
References v8::internal::interpreter::BytecodeGenerator::builder(), v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), v8::internal::interpreter::BytecodeGenerator::register_allocator(), and v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister().
 DisposablesStackScope()
v8::internal::interpreter::BytecodeGenerator::DisposablesStackScope::~DisposablesStackScope () [inline]
Definition at line 1338 of file bytecode-generator.cc.
                           {
    bytecode_generator_->set_current_disposables_stack(prev_disposables_stack_);
  }
Member Data Documentation
bytecode_generator_
BytecodeGenerator* const v8::internal::interpreter::BytecodeGenerator::DisposablesStackScope::bytecode_generator_ [private]
Definition at line 1343 of file bytecode-generator.cc.
prev_disposables_stack_
Register v8::internal::interpreter::BytecodeGenerator::DisposablesStackScope::prev_disposables_stack_ [private]
Definition at line 1344 of file bytecode-generator.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/interpreter/bytecode-generator.cc