v8::internal::torque::ls::BaseJsonAccessor Class Reference
#include <message.h>
Public Member Functions
template<class T >
T GetObject (const std::string &property)
bool HasProperty (const std::string &property) const
void SetNull (const std::string &property)
bool IsNull (const std::string &property) const
Protected Member Functions
virtual const JsonObject & object () const =0
virtual JsonObject & object ()=0
JsonObject & GetObjectProperty (const std::string &property)
JsonArray & GetArrayProperty (const std::string &property)
JsonObject & AddObjectElementToArrayProperty (const std::string &property)
Detailed Description
Definition at line 21 of file message.h.
Member Function Documentation
AddObjectElementToArrayProperty()
JsonObject& v8::internal::torque::ls::BaseJsonAccessor::AddObjectElementToArrayProperty (const std::string & property) [inline], [protected]
Definition at line 59 of file message.h.
                                                                         {
    JsonArray& array = GetArrayProperty(property);
    array.push_back(JsonValue::From(JsonObject{}));
    return array.back().ToObject();
  }
References v8::internal::torque::ls::JsonValue::From(), and GetArrayProperty().
GetArrayProperty()
JsonArray& v8::internal::torque::ls::BaseJsonAccessor::GetArrayProperty (const std::string & property) [inline], [protected]
Definition at line 52 of file message.h.
                                                         {
    if (!object()[property].IsArray()) {
      object()[property] = JsonValue::From(JsonArray{});
    }
    return object()[property].ToArray();
  }
References v8::internal::torque::ls::JsonValue::From(), and object().
Referenced by AddObjectElementToArrayProperty().
GetObject()
template<class T >
T v8::internal::torque::ls::BaseJsonAccessor::GetObject (const std::string & property) [inline]
Definition at line 24 of file message.h.
                                         {
    return T(GetObjectProperty(property));
  }
References GetObjectProperty(), and T.
GetObjectProperty()
JsonObject& v8::internal::torque::ls::BaseJsonAccessor::GetObjectProperty (const std::string & property) [inline], [protected]
Definition at line 45 of file message.h.
                                                           {
    if (!object()[property].IsObject()) {
      object()[property] = JsonValue::From(JsonObject{});
    }
    return object()[property].ToObject();
  }
References v8::internal::torque::ls::JsonValue::From(), v8::internal::IsObject(), and object().
Referenced by GetObject().
HasProperty()
bool v8::internal::torque::ls::BaseJsonAccessor::HasProperty (const std::string & property) const [inline]
Definition at line 28 of file message.h.
                                                    {
    return object().count(property) > 0;
  }
References object().
Referenced by IsNull().
IsNull()
bool v8::internal::torque::ls::BaseJsonAccessor::IsNull (const std::string & property) const [inline]
Definition at line 36 of file message.h.
                                               {
    return HasProperty(property) &&
           object().at(property).tag == JsonValue::IS_NULL;
  }
References HasProperty(), v8::internal::torque::ls::JsonValue::IS_NULL, and object().
object() [1/2]
virtual const JsonObject& v8::internal::torque::ls::BaseJsonAccessor::object () const [protected], [pure virtual]
Implemented in v8::internal::torque::ls::NestedJsonAccessor, and v8::internal::torque::ls::Message.
Referenced by GetArrayProperty(), GetObjectProperty(), HasProperty(), IsNull(), and SetNull().
object() [2/2]
virtual JsonObject& v8::internal::torque::ls::BaseJsonAccessor::object () [protected], [pure virtual]
Implemented in v8::internal::torque::ls::NestedJsonAccessor, and v8::internal::torque::ls::Message.
SetNull()
void v8::internal::torque::ls::BaseJsonAccessor::SetNull (const std::string & property) [inline]
Definition at line 32 of file message.h.
                                          {
    object()[property] = JsonValue::JsonNull();
  }
References v8::internal::torque::ls::JsonValue::JsonNull(), and object().
Referenced by v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::HandleGotoDefinitionRequest().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/ls/message.h