v8::internal::SeqRegExpNode Class Reference
#include <regexp-nodes.h>
Public Member Functions
SeqRegExpNode (RegExpNode *on_success)
RegExpNode * on_success ()
void set_on_success (RegExpNode *node)
RegExpNode * FilterOneByte (int depth, RegExpCompiler *compiler) override
void FillInBMInfo (Isolate *isolate, int offset, int budget, BoyerMooreLookahead *bm, bool not_at_start) override
SeqRegExpNode * AsSeqRegExpNode () override
Protected Member Functions
RegExpNode * FilterSuccessor (int depth, RegExpCompiler *compiler)
Private Attributes
RegExpNode * on_success_
Additional Inherited Members
Detailed Description
Definition at line 306 of file regexp-nodes.h.
Constructor & Destructor Documentation
SeqRegExpNode()
v8::internal::SeqRegExpNode::SeqRegExpNode (RegExpNode * on_success) [inline], [explicit]
Definition at line 308 of file regexp-nodes.h.
      : RegExpNode(on_success->zone()), on_success_(on_success) {}
Member Function Documentation
AsSeqRegExpNode()
SeqRegExpNode* v8::internal::SeqRegExpNode::AsSeqRegExpNode () [inline], [override], [virtual]
Reimplemented from v8::internal::RegExpNode.
Definition at line 318 of file regexp-nodes.h.
{ return this; }
FillInBMInfo()
void v8::internal::SeqRegExpNode::FillInBMInfo (Isolate * isolate, int offset, int budget, BoyerMooreLookahead * bm, bool not_at_start) [inline], [override], [virtual]
Reimplemented from v8::internal::RegExpNode.
Reimplemented in v8::internal::BackReferenceNode, v8::internal::AssertionNode, v8::internal::TextNode, and v8::internal::ActionNode.
Definition at line 313 of file regexp-nodes.h.
                                                                         {
    on_success_->FillInBMInfo(isolate, offset, budget - 1, bm, not_at_start);
    if (offset == 0) set_bm_info(not_at_start, bm);
  }
References v8::internal::RegExpNode::FillInBMInfo(), on_success_, and v8::internal::RegExpNode::set_bm_info().
FilterOneByte()
RegExpNode * v8::internal::SeqRegExpNode::FilterOneByte (int depth, RegExpCompiler * compiler) [override], [virtual]
Reimplemented from v8::internal::RegExpNode.
Reimplemented in v8::internal::TextNode.
Definition at line 1905 of file regexp-compiler.cc.
                                                                            {
  if (info()->replacement_calculated) return replacement();
  if (depth < 0) return this;
  DCHECK(!info()->visited);
  VisitMarker marker(info());
  return FilterSuccessor(depth - 1, compiler);
}
References v8::internal::DCHECK(), FilterSuccessor(), v8::internal::RegExpNode::info(), and v8::internal::RegExpNode::replacement().
FilterSuccessor()
RegExpNode * v8::internal::SeqRegExpNode::FilterSuccessor (int depth, RegExpCompiler * compiler) [protected]
Definition at line 1913 of file regexp-compiler.cc.
                                                                     {
  RegExpNode* next = on_success_->FilterOneByte(depth - 1, compiler);
  if (next == nullptr) return set_replacement(nullptr);
  on_success_ = next;
  return set_replacement(this);
}
References v8::internal::RegExpNode::FilterOneByte(), on_success_, and v8::internal::RegExpNode::set_replacement().
Referenced by FilterOneByte(), and v8::internal::TextNode::FilterOneByte().
on_success()
RegExpNode* v8::internal::SeqRegExpNode::on_success () [inline]
Definition at line 310 of file regexp-nodes.h.
{ return on_success_; }
References on_success_.
Referenced by v8::internal::AssertionNode::AfterNewline(), v8::internal::AssertionNode::AtBoundary(), v8::internal::AssertionNode::AtEnd(), v8::internal::AssertionNode::AtNonBoundary(), v8::internal::AssertionNode::AtStart(), v8::internal::AssertionNode::BacktrackIfPrevious(), v8::internal::ActionNode::BeginNegativeSubmatch(), v8::internal::ActionNode::ClearCaptures(), v8::internal::ActionNode::ClearPosition(), v8::internal::TextNode::CreateForCharacterRanges(), v8::internal::TextNode::CreateForSurrogatePair(), v8::internal::ActionNode::Emit(), v8::internal::TextNode::Emit(), v8::internal::AssertionNode::Emit(), v8::internal::BackReferenceNode::Emit(), v8::internal::ActionNode::EmptyMatchCheck(), v8::internal::ActionNode::FillInBMInfo(), v8::internal::TextNode::FillInBMInfo(), v8::internal::AssertionNode::FillInBMInfo(), v8::internal::ChoiceNode::FixedLengthLoopLengthForAlternative(), v8::internal::TextNode::GetQuickCheckDetails(), v8::internal::ActionNode::GetQuickCheckDetails(), v8::internal::AssertionNode::GetQuickCheckDetails(), v8::internal::TextNode::GetSuccessorOfOmnivorousTextNode(), v8::internal::ActionNode::IncrementRegister(), v8::internal::ActionNode::ModifyFlags(), v8::internal::ActionNode::PositiveSubmatchSuccess(), v8::internal::ActionNode::RestorePosition(), v8::internal::ActionNode::SetRegisterForLoop(), v8::internal::anonymous_namespace{regexp-compiler.cc}::AssertionPropagator::VisitAction(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EatsAtLeastPropagator::VisitAction(), v8::internal::Analysis< Propagators >::VisitAction(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EatsAtLeastPropagator::VisitAssertion(), v8::internal::Analysis< Propagators >::VisitAssertion(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EatsAtLeastPropagator::VisitBackReference(), v8::internal::Analysis< Propagators >::VisitBackReference(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EatsAtLeastPropagator::VisitText(), and v8::internal::Analysis< Propagators >::VisitText().
set_on_success()
void v8::internal::SeqRegExpNode::set_on_success (RegExpNode * node) [inline]
Definition at line 311 of file regexp-nodes.h.
{ on_success_ = node; }
References on_success_.
Member Data Documentation
on_success_
RegExpNode* v8::internal::SeqRegExpNode::on_success_ [private]
Definition at line 324 of file regexp-nodes.h.
Referenced by FillInBMInfo(), FilterSuccessor(), on_success(), and set_on_success().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-nodes.h
/mnt/V8SourceCode/src/regexp/regexp-compiler.cc