v8::internal::maglev::MaglevGraphBuilder::BranchBuilder Class Reference
Classes
struct BytecodeJumpTarget
union Data
struct LabelJumpTarget
class PatchAccumulatorInBranchScope
Public Types
enum Mode { kBytecodeJumpTarget
, kLabelJumpTarget
 }
Public Member Functions
BranchBuilder (MaglevGraphBuilder *builder, BranchType jump_type)
BranchBuilder (MaglevGraphBuilder *builder, MaglevSubGraphBuilder *sub_builder, BranchType jump_type, MaglevSubGraphBuilder::Label *jump_label)
Mode mode () const
BranchType GetCurrentBranchType () const
void SetBranchSpecializationMode (BranchSpecializationMode mode)
void SwapTargets ()
BasicBlockRef * jump_target ()
BasicBlockRef * fallthrough ()
BasicBlockRef * true_target ()
BasicBlockRef * false_target ()
BranchResult FromBool (bool value) const
BranchResult AlwaysTrue () const
BranchResult AlwaysFalse () const
template<typename NodeT , typename... Args>
BranchResult Build (std::initializer_list< ValueNode * > inputs, Args &&... args)
template<typename ControlNodeT , typename... Args>
MaglevGraphBuilder::BranchResult Build (std::initializer_list< ValueNode * > control_inputs, Args &&... args)
Private Member Functions
void StartFallthroughBlock (BasicBlock *predecessor)
void SetAccumulatorInBranch (BranchType jump_type) const
Private Attributes
MaglevGraphBuilder * builder_
MaglevGraphBuilder::MaglevSubGraphBuilder * sub_builder_
BranchType jump_type_
BranchSpecializationMode branch_specialization_mode_
Data data_
Detailed Description
Definition at line 2860 of file maglev-graph-builder.h.
Member Enumeration Documentation
Mode
enum v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::Mode
Enumerator
kBytecodeJumpTarget
kLabelJumpTarget
Definition at line 2862 of file maglev-graph-builder.h.
              {
      kBytecodeJumpTarget,
      kLabelJumpTarget,
    };
Constructor & Destructor Documentation
BranchBuilder() [1/2]
v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::BranchBuilder (MaglevGraphBuilder * builder, BranchType jump_type) [inline]
Definition at line 2920 of file maglev-graph-builder.h.
        : builder_(builder),
          sub_builder_(nullptr),
          jump_type_(jump_type),
          data_(builder->iterator_.GetJumpTargetOffset(),
                builder->iterator_.next_offset()) {}
BranchBuilder() [2/2]
v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::BranchBuilder (MaglevGraphBuilder * builder, MaglevSubGraphBuilder * sub_builder, BranchType jump_type, MaglevSubGraphBuilder::Label * jump_label) [inline]
Definition at line 2928 of file maglev-graph-builder.h.
        : builder_(builder),
          sub_builder_(sub_builder),
          jump_type_(jump_type),
          data_(jump_label) {}
Member Function Documentation
AlwaysFalse()
BranchResult v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::AlwaysFalse () const [inline]
Definition at line 2954 of file maglev-graph-builder.h.
{ return FromBool(false); }
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfJSReceiver(), v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfRootConstant(), v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfUndefinedOrNull(), and v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfUndetectable().
AlwaysTrue()
BranchResult v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::AlwaysTrue () const [inline]
Definition at line 2953 of file maglev-graph-builder.h.
{ return FromBool(true); }
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfJSReceiver(), and v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfUndetectable().
Build() [1/2]
template<typename ControlNodeT , typename... Args>
MaglevGraphBuilder::BranchResult v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::Build (std::initializer_list< ValueNode * > control_inputs, Args &&... args)
Definition at line 630 of file maglev-graph-builder.cc.
                                                                    {
  static_assert(IsConditionalControlNode(Node::opcode_of<ControlNodeT>));
  BasicBlock* block = builder_->FinishBlock<ControlNodeT>(
      control_inputs, std::forward<Args>(args)..., true_target(),
      false_target());
  StartFallthroughBlock(block);
  return BranchResult::kDefault;
}
References v8::base::args, v8::internal::maglev::IsConditionalControlNode(), v8::internal::maglev::MaglevGraphBuilder::kDefault, and v8::internal::maglev::MaglevGraphBuilder::StartFallthroughBlock().
Build() [2/2]
template<typename NodeT , typename... Args>
BranchResult v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::Build (std::initializer_list< ValueNode * > inputs, Args &&... args)
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfFloat64IsHole(), v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfFloat64ToBooleanTrue(), v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfInt32Compare(), v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfInt32ToBooleanTrue(), v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfIntPtrToBooleanTrue(), v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfJSReceiver(), v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfReferenceEqual(), v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfRootConstant(), v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfToBooleanTrue(), v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfUint32Compare(), v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfUndefinedOrNull(), and v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfUndetectable().
fallthrough()
BasicBlockRef * v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::fallthrough ()
Definition at line 595 of file maglev-graph-builder.cc.
                                                            {
  switch (mode()) {
    case kBytecodeJumpTarget:
      return &builder_->jump_targets_[data_.bytecode_target.fallthrough_offset];
    case kLabelJumpTarget:
      return &data_.label_target.fallthrough;
  }
}
References mode().
false_target()
BasicBlockRef * v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::false_target ()
Definition at line 609 of file maglev-graph-builder.cc.
                                                             {
  return jump_type_ == BranchType::kBranchIfFalse ? jump_target()
                                                  : fallthrough();
}
References v8::internal::maglev::MaglevGraphBuilder::kBranchIfFalse.
FromBool()
MaglevGraphBuilder::BranchResult v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::FromBool (bool value) const
Definition at line 614 of file maglev-graph-builder.cc.
                      {
  switch (mode()) {
    case kBytecodeJumpTarget: {
      BranchType type_if_need_to_jump =
          (value ? BranchType::kBranchIfTrue : BranchType::kBranchIfFalse);
      builder_->MarkBranchDeadAndJumpIfNeeded(jump_type_ ==
                                              type_if_need_to_jump);
      return BranchResult::kDefault;
    }
    case kLabelJumpTarget:
      return value ? BranchResult::kAlwaysTrue : BranchResult::kAlwaysFalse;
  }
}
References v8::internal::maglev::MaglevGraphBuilder::kAlwaysFalse, v8::internal::maglev::MaglevGraphBuilder::kAlwaysTrue, v8::internal::maglev::MaglevGraphBuilder::kBranchIfFalse, v8::internal::maglev::MaglevGraphBuilder::kBranchIfTrue, v8::internal::maglev::MaglevGraphBuilder::kDefault, mode(), and v8::internal::value.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfInt32Compare(), v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfReferenceEqual(), v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfRootConstant(), v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfToBooleanTrue(), v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfUint32Compare(), and v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfUndefinedOrNull().
GetCurrentBranchType()
BranchType v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::GetCurrentBranchType () const [inline]
Definition at line 2940 of file maglev-graph-builder.h.
{ return jump_type_; }
jump_target()
BasicBlockRef * v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::jump_target ()
Definition at line 586 of file maglev-graph-builder.cc.
                                                            {
  switch (mode()) {
    case kBytecodeJumpTarget:
      return &builder_->jump_targets_[data_.bytecode_target.jump_target_offset];
    case kLabelJumpTarget:
      return &data_.label_target.jump_label->ref_;
  }
}
References mode().
mode()
Mode v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::mode () const [inline]
Definition at line 2936 of file maglev-graph-builder.h.
                      {
      return sub_builder_ == nullptr ? kBytecodeJumpTarget : kLabelJumpTarget;
    }
Referenced by v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::PatchAccumulatorInBranchScope::PatchAccumulatorInBranchScope().
SetAccumulatorInBranch()
void v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::SetAccumulatorInBranch (BranchType jump_type) const [private]
Definition at line 571 of file maglev-graph-builder.cc.
                                {
  DCHECK_EQ(mode(), kBytecodeJumpTarget);
  auto& data = data_.bytecode_target;
  if (branch_specialization_mode_ == BranchSpecializationMode::kAlwaysBoolean) {
    builder_->SetAccumulatorInBranch(builder_->GetBooleanConstant(
        data.patch_accumulator_scope->jump_type_ == jump_type));
  } else if (data.patch_accumulator_scope->jump_type_ == jump_type) {
    builder_->SetAccumulatorInBranch(
        builder_->GetRootConstant(data.patch_accumulator_scope->root_index_));
  } else {
    builder_->SetAccumulatorInBranch(data.patch_accumulator_scope->node_);
  }
}
References DCHECK_EQ, v8::internal::maglev::MaglevGraphBuilder::kAlwaysBoolean, and mode().
SetBranchSpecializationMode()
void v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::SetBranchSpecializationMode (BranchSpecializationMode mode) [inline]
Definition at line 2942 of file maglev-graph-builder.h.
                                                                    {
      branch_specialization_mode_ = mode;
    }
References mode().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfTrue().
StartFallthroughBlock()
void v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::StartFallthroughBlock (BasicBlock * predecessor) [private]
Definition at line 546 of file maglev-graph-builder.cc.
                             {
  switch (mode()) {
    case kBytecodeJumpTarget: {
      auto& data = data_.bytecode_target;
      if (data.patch_accumulator_scope &&
          (data.patch_accumulator_scope->node_ == builder_->GetAccumulator())) {
        SetAccumulatorInBranch(BranchType::kBranchIfTrue);
        builder_->MergeIntoFrameState(predecessor, data.jump_target_offset);
        SetAccumulatorInBranch(BranchType::kBranchIfFalse);
        builder_->StartFallthroughBlock(data.fallthrough_offset, predecessor);
      } else {
        builder_->MergeIntoFrameState(predecessor, data.jump_target_offset);
        builder_->StartFallthroughBlock(data.fallthrough_offset, predecessor);
      }
      break;
    }
    case kLabelJumpTarget:
      auto& data = data_.label_target;
      sub_builder_->MergeIntoLabel(data.jump_label, predecessor);
      builder_->StartNewBlock(predecessor, nullptr, data.fallthrough);
      break;
  }
}
References v8::internal::maglev::MaglevGraphBuilder::kBranchIfFalse, v8::internal::maglev::MaglevGraphBuilder::kBranchIfTrue, mode(), and v8::internal::maglev::MaglevGraphBuilder::SetAccumulatorInBranch().
SwapTargets()
void v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::SwapTargets () [inline]
Definition at line 2945 of file maglev-graph-builder.h.
{ jump_type_ = NegateBranchType(jump_type_); }
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfRootConstant(), and v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfToBooleanTrue().
true_target()
BasicBlockRef * v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::true_target ()
Definition at line 604 of file maglev-graph-builder.cc.
                                                            {
  return jump_type_ == BranchType::kBranchIfTrue ? jump_target()
                                                 : fallthrough();
}
References v8::internal::maglev::MaglevGraphBuilder::kBranchIfTrue.
Member Data Documentation
branch_specialization_mode_
BranchSpecializationMode v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::branch_specialization_mode_ [private]
Initial value:
=
        BranchSpecializationMode::kDefault
Definition at line 2964 of file maglev-graph-builder.h.
builder_
MaglevGraphBuilder* v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::builder_ [private]
Definition at line 2961 of file maglev-graph-builder.h.
data_
Data v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::data_ [private]
Definition at line 2966 of file maglev-graph-builder.h.
jump_type_
BranchType v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::jump_type_ [private]
Definition at line 2963 of file maglev-graph-builder.h.
sub_builder_
MaglevGraphBuilder::MaglevSubGraphBuilder* v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::sub_builder_ [private]
Definition at line 2962 of file maglev-graph-builder.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-graph-builder.h
/mnt/V8SourceCode/src/maglev/maglev-graph-builder.cc