v8::internal::anonymous_namespace{code-stub-assembler.cc}::MetaTableAccessor Class Reference
Public Member Functions
MetaTableAccessor (CodeStubAssembler &csa, MachineType mt)
TNode< Uint32T > Load (TNode< ByteArray > meta_table, TNode< IntPtrT > index)
TNode< Uint32T > Load (TNode< ByteArray > meta_table, int index)
void Store (TNode< ByteArray > meta_table, TNode< IntPtrT > index, TNode< Uint32T > data)
void Store (TNode< ByteArray > meta_table, int index, TNode< Uint32T > data)
Private Member Functions
TNode< IntPtrT > OverallOffset (TNode< ByteArray > meta_table, TNode< IntPtrT > index)
Private Attributes
CodeStubAssembler & csa
MachineType mt
Detailed Description
Definition at line 18645 of file code-stub-assembler.cc.
Constructor & Destructor Documentation
MetaTableAccessor()
v8::internal::anonymous_namespace{code-stub-assembler.cc}::MetaTableAccessor::MetaTableAccessor (CodeStubAssembler & csa, MachineType mt) [inline]
Definition at line 18647 of file code-stub-assembler.cc.
      : csa{csa}, mt{mt} {}
Member Function Documentation
Load() [1/2]
TNode<Uint32T> v8::internal::anonymous_namespace{code-stub-assembler.cc}::MetaTableAccessor::Load (TNode< ByteArray > meta_table, int index) [inline]
Definition at line 18657 of file code-stub-assembler.cc.
                                                              {
    return Load(meta_table, csa.IntPtrConstant(index));
  }
References v8::internal::index, and v8::Load().
Load() [2/2]
TNode<Uint32T> v8::internal::anonymous_namespace{code-stub-assembler.cc}::MetaTableAccessor::Load (TNode< ByteArray > meta_table, TNode< IntPtrT > index) [inline]
Definition at line 18650 of file code-stub-assembler.cc.
                                                                         {
    TNode<IntPtrT> offset = OverallOffset(meta_table, index);
    return csa.UncheckedCast<Uint32T>(
        csa.LoadFromObject(mt, meta_table, offset));
  }
References v8::internal::index.
OverallOffset()
TNode<IntPtrT> v8::internal::anonymous_namespace{code-stub-assembler.cc}::MetaTableAccessor::OverallOffset (TNode< ByteArray > meta_table, TNode< IntPtrT > index) [inline], [private]
Definition at line 18682 of file code-stub-assembler.cc.
                                                     {
    // TODO(v8:11330): consider using ElementOffsetFromIndex().
    int offset_to_data_minus_tag =
        OFFSET_OF_DATA_START(ByteArray) - kHeapObjectTag;
    TNode<IntPtrT> overall_offset;
    int size = mt.MemSize();
    intptr_t constant;
    if (csa.TryToIntPtrConstant(index, &constant)) {
      intptr_t index_offset = constant * size;
      overall_offset =
          csa.IntPtrConstant(offset_to_data_minus_tag + index_offset);
    } else {
      TNode<IntPtrT> index_offset =
          csa.IntPtrMul(index, csa.IntPtrConstant(size));
      overall_offset = csa.IntPtrAdd(
          csa.IntPtrConstant(offset_to_data_minus_tag), index_offset);
    }
#ifdef DEBUG
    TNode<IntPtrT> byte_array_data_bytes =
        csa.SmiToIntPtr(csa.LoadFixedArrayBaseLength(meta_table));
    TNode<IntPtrT> max_allowed_offset = csa.IntPtrAdd(
        byte_array_data_bytes, csa.IntPtrConstant(offset_to_data_minus_tag));
    CSA_DCHECK(&csa, csa.UintPtrLessThan(overall_offset, max_allowed_offset));
#endif
    return overall_offset;
  }
References v8::internal::index, v8::internal::kHeapObjectTag, OFFSET_OF_DATA_START, and size().
Store() [1/2]
void v8::internal::anonymous_namespace{code-stub-assembler.cc}::MetaTableAccessor::Store (TNode< ByteArray > meta_table, int index, TNode< Uint32T > data) [inline]
Definition at line 18677 of file code-stub-assembler.cc.
                                                                          {
    Store(meta_table, csa.IntPtrConstant(index), data);
  }
References v8::internal::index, and v8::internal::wasm::liftoff::Store().
Store() [2/2]
void v8::internal::anonymous_namespace{code-stub-assembler.cc}::MetaTableAccessor::Store (TNode< ByteArray > meta_table, TNode< IntPtrT > index, TNode< Uint32T > data) [inline]
Definition at line 18661 of file code-stub-assembler.cc.
                                  {
    TNode<IntPtrT> offset = OverallOffset(meta_table, index);
#ifdef DEBUG
    int bits = mt.MemSize() * 8;
    TNode<UintPtrT> max_value = csa.UintPtrConstant((1ULL << bits) - 1);
    CSA_DCHECK(&csa, csa.UintPtrLessThanOrEqual(csa.ChangeUint32ToWord(data),
                                                max_value));
#endif
    csa.StoreToObject(mt.representation(), meta_table, offset, data,
                      StoreToObjectWriteBarrier::kNone);
  }
References v8::internal::index, and v8::internal::kNone.
Member Data Documentation
csa
CodeStubAssembler& v8::internal::anonymous_namespace{code-stub-assembler.cc}::MetaTableAccessor::csa [private]
Definition at line 18714 of file code-stub-assembler.cc.
mt
MachineType v8::internal::anonymous_namespace{code-stub-assembler.cc}::MetaTableAccessor::mt [private]
Definition at line 18715 of file code-stub-assembler.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/codegen/code-stub-assembler.cc