v8::internal::CodeCommentsWriter Class Reference
#include <code-comments.h>
Public Member Functions
V8_EXPORT_PRIVATE void Add (uint32_t pc_offset, std::string comment)
void Emit (Assembler *assm)
size_t entry_count () const
uint32_t section_size () const
Private Attributes
uint32_t byte_count_ = 0
std::vector< CodeCommentEntry > comments_
Detailed Description
Definition at line 36 of file code-comments.h.
Member Function Documentation
Add()
void v8::internal::CodeCommentsWriter::Add (uint32_t pc_offset, std::string comment)
Definition at line 79 of file code-comments.cc.
                                                                  {
  CodeCommentEntry entry = {pc_offset, std::move(comment)};
  byte_count_ += entry.size();
  comments_.push_back(std::move(entry));
}
References byte_count_, comments_, and v8::internal::CodeCommentEntry::size().
Emit()
void v8::internal::CodeCommentsWriter::Emit (Assembler * assm)
Definition at line 66 of file code-comments.cc.
                                             {
  assm->dd(section_size());
  for (auto i = comments_.begin(); i != comments_.end(); ++i) {
    assm->dd(i->pc_offset);
    assm->dd(i->comment_length());
    for (char c : i->comment) {
      EnsureSpace ensure_space(assm);
      assm->db(c);
    }
    assm->db('\0');
  }
}
References comments_, v8::internal::Assembler::db(), v8::internal::Assembler::dd(), and section_size().
Referenced by v8::internal::Assembler::WriteCodeComments().
entry_count()
size_t v8::internal::CodeCommentsWriter::entry_count () const
Definition at line 85 of file code-comments.cc.
{ return comments_.size(); }
References comments_.
Referenced by v8::internal::Assembler::WriteCodeComments().
section_size()
uint32_t v8::internal::CodeCommentsWriter::section_size () const
Definition at line 86 of file code-comments.cc.
                                                {
  return kOffsetToFirstCommentEntry + static_cast<uint32_t>(byte_count_);
}
References byte_count_, and v8::internal::anonymous_namespace{code-comments.cc}::kOffsetToFirstCommentEntry.
Referenced by Emit(), and v8::internal::Assembler::WriteCodeComments().
Member Data Documentation
byte_count_
uint32_t v8::internal::CodeCommentsWriter::byte_count_ = 0 [private]
Definition at line 44 of file code-comments.h.
Referenced by Add(), and section_size().
comments_
std::vector<CodeCommentEntry> v8::internal::CodeCommentsWriter::comments_ [private]
Definition at line 45 of file code-comments.h.
Referenced by Add(), Emit(), and entry_count().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/code-comments.h
/mnt/V8SourceCode/src/codegen/code-comments.cc