v8::internal::CpuProfilesCollection Class Reference
#include <profile-generator.h>
Public Member Functions
CpuProfilesCollection (Isolate *isolate)
CpuProfilesCollection (const CpuProfilesCollection &)=delete
CpuProfilesCollection & operator= (const CpuProfilesCollection &)=delete
void set_cpu_profiler (CpuProfiler *profiler)
CpuProfilingResult StartProfiling (const char *title=nullptr, CpuProfilingOptions options={}, std::unique_ptr< DiscardedSamplesDelegate > delegate=nullptr)
CpuProfilingResult StartProfilingForTesting (ProfilerId id)
CpuProfile * StopProfiling (ProfilerId id)
bool IsLastProfileLeft (ProfilerId id)
CpuProfile * Lookup (const char *title)
std::vector< std::unique_ptr< CpuProfile > > * profiles ()
const char * GetName (Tagged< Name > name)
void RemoveProfile (CpuProfile *profile)
base::TimeDelta GetCommonSamplingInterval ()
void AddPathToCurrentProfiles (base::TimeTicks timestamp, const ProfileStackTrace &path, LineAndColumn src_pos, bool update_stats, base::TimeDelta sampling_interval, StateTag state, EmbedderStateTag embedder_state_tag, Address native_context_address=kNullAddress, Address native_embedder_context_address=kNullAddress, const std::optional< uint64_t > trace_id=std::nullopt)
void UpdateNativeContextAddressForCurrentProfiles (Address from, Address to)
Static Public Attributes
static const int kMaxSimultaneousProfiles = 100
Private Member Functions
CpuProfilingResult StartProfiling (ProfilerId id, const char *title=nullptr, CpuProfilingOptions options={}, std::unique_ptr< DiscardedSamplesDelegate > delegate=nullptr)
Private Attributes
StringsStorage resource_names_
std::vector< std::unique_ptr< CpuProfile > > finished_profiles_
CpuProfiler * profiler_
std::vector< std::unique_ptr< CpuProfile > > current_profiles_
base::RecursiveMutex current_profiles_mutex_
Isolate * isolate_
Static Private Attributes
static std::atomic< ProfilerId > last_id_ {0}
Detailed Description
Definition at line 552 of file profile-generator.h.
Constructor & Destructor Documentation
CpuProfilesCollection() [1/2]
v8::internal::CpuProfilesCollection::CpuProfilesCollection (Isolate * isolate) [explicit]
Definition at line 1069 of file profile-generator.cc.
    : profiler_(nullptr), current_profiles_mutex_(), isolate_(isolate) {
  USE(isolate_);
}
References isolate_, and USE.
CpuProfilesCollection() [2/2]
v8::internal::CpuProfilesCollection::CpuProfilesCollection (const CpuProfilesCollection &) [delete]
Member Function Documentation
AddPathToCurrentProfiles()
void v8::internal::CpuProfilesCollection::AddPathToCurrentProfiles (base::TimeTicks timestamp, const ProfileStackTrace & path, LineAndColumn src_pos, bool update_stats, base::TimeDelta sampling_interval, StateTag state, EmbedderStateTag embedder_state_tag, Address native_context_address = kNullAddress, Address native_embedder_context_address = kNullAddress, const std::optional< uint64_t > trace_id = std::nullopt)
Definition at line 1205 of file profile-generator.cc.
                                          {
  // As starting / stopping profiles is rare relatively to this
  // method, we don't bother minimizing the duration of lock holding,
  // e.g. copying contents of the list to a local vector.
  const ProfileStackTrace empty_path;
  base::RecursiveMutexGuard profiles_guard{&current_profiles_mutex_};
  for (const std::unique_ptr<CpuProfile>& profile : current_profiles_) {
    ContextFilter& context_filter = profile->context_filter();
    // If the context filter check failed, omit the contents of the stack.
    bool accepts_context = context_filter.Accept(native_context_address);
    bool accepts_embedder_context =
        context_filter.Accept(embedder_native_context_address);
    // if FilterContext is set, do not propagate StateTag if not accepted.
    // GC (and LOGGING when during GC) is the exception, because native context
    // address can be empty but we still want to know that this is GC.
    if (!accepts_context && state != StateTag::GC &&
        state != StateTag::LOGGING) {
      state = StateTag::IDLE;
    }
    profile->AddPath(
        timestamp, accepts_context ? path : empty_path, src_pos, update_stats,
        sampling_interval, state,
        accepts_embedder_context ? embedder_state_tag : EmbedderStateTag::EMPTY,
        trace_id);
  }
}
References v8::internal::ContextFilter::Accept(), current_profiles_, current_profiles_mutex_, v8::EMPTY, v8::GC, v8::IDLE, and v8::LOGGING.
Referenced by v8::internal::SamplingEventsProcessor::SymbolizeAndAddToProfiles().
GetCommonSamplingInterval()
base::TimeDelta v8::internal::CpuProfilesCollection::GetCommonSamplingInterval ()
Definition at line 1180 of file profile-generator.cc.
                                                               {
  DCHECK(profiler_);
  int64_t base_sampling_interval_us =
      profiler_->sampling_interval().InMicroseconds();
  if (base_sampling_interval_us == 0) return base::TimeDelta();
  int64_t interval_us = 0;
  {
    base::RecursiveMutexGuard profiles_guard{&current_profiles_mutex_};
    for (const auto& profile : current_profiles_) {
      // Snap the profile's requested sampling interval to the next multiple of
      // the base sampling interval.
      int64_t profile_interval_us =
          std::max<int64_t>((profile->sampling_interval_us() +
                             base_sampling_interval_us - 1) /
                                base_sampling_interval_us,
                            1) *
          base_sampling_interval_us;
      interval_us = GreatestCommonDivisor(interval_us, profile_interval_us);
    }
  }
  return base::TimeDelta::FromMicroseconds(interval_us);
}
References current_profiles_, current_profiles_mutex_, v8::internal::DCHECK(), v8::base::TimeDelta::FromMicroseconds(), v8::internal::anonymous_namespace{profile-generator.cc}::GreatestCommonDivisor(), v8::base::TimeDelta::InMicroseconds(), profiler_, and v8::internal::CpuProfiler::sampling_interval().
GetName()
const char* v8::internal::CpuProfilesCollection::GetName (Tagged< Name > name) [inline]
Definition at line 572 of file profile-generator.h.
                                         {
    return resource_names_.GetName(name);
  }
References v8::internal::name.
IsLastProfileLeft()
bool v8::internal::CpuProfilesCollection::IsLastProfileLeft (ProfilerId id)
Definition at line 1154 of file profile-generator.cc.
                                                           {
  base::RecursiveMutexGuard profiles_guard{&current_profiles_mutex_};
  if (current_profiles_.size() != 1) return false;
  return id == current_profiles_[0]->id();
}
References current_profiles_, and current_profiles_mutex_.
Lookup()
CpuProfile * v8::internal::CpuProfilesCollection::Lookup (const char * title)
Definition at line 1138 of file profile-generator.cc.
                                                           {
  if (title == nullptr) return nullptr;
  // http://crbug/51594, edge case console.profile may provide an empty title
  // and must not crash
  const bool empty_title = title[0] == '\0';
  base::RecursiveMutexGuard profiles_guard{&current_profiles_mutex_};
  auto it = std::find_if(
      current_profiles_.rbegin(), current_profiles_.rend(),
      [&](const std::unique_ptr<CpuProfile>& p) {
        return (empty_title ||
                (p->title() != nullptr && strcmp(p->title(), title) == 0));
      });
  if (it != current_profiles_.rend()) return it->get();
  return nullptr;
}
References current_profiles_, and current_profiles_mutex_.
operator=()
CpuProfilesCollection& v8::internal::CpuProfilesCollection::operator= (const CpuProfilesCollection &) [delete]
profiles()
std::vector<std::unique_ptr<CpuProfile> >* v8::internal::CpuProfilesCollection::profiles () [inline]
Definition at line 569 of file profile-generator.h.
                                                   {
    return &finished_profiles_;
  }
RemoveProfile()
void v8::internal::CpuProfilesCollection::RemoveProfile (CpuProfile * profile)
Definition at line 1160 of file profile-generator.cc.
                                                             {
  // Called from VM thread for a completed profile.
  DCHECK_EQ(ThreadId::Current(), isolate_->thread_id());
  auto pos =
      std::find_if(finished_profiles_.begin(), finished_profiles_.end(),
                   [&](const std::unique_ptr<CpuProfile>& finished_profile) {
                     return finished_profile.get() == profile;
                   });
  DCHECK(pos != finished_profiles_.end());
  finished_profiles_.erase(pos);
}
References v8::internal::ThreadId::Current(), v8::internal::DCHECK(), DCHECK_EQ, finished_profiles_, isolate_, and v8::internal::Isolate::thread_id().
set_cpu_profiler()
void v8::internal::CpuProfilesCollection::set_cpu_profiler (CpuProfiler * profiler) [inline]
Definition at line 558 of file profile-generator.h.
{ profiler_ = profiler; }
StartProfiling() [1/2]
CpuProfilingResult v8::internal::CpuProfilesCollection::StartProfiling (const char * title = nullptr, CpuProfilingOptions options = {}, std::unique_ptr< DiscardedSamplesDelegate > delegate = nullptr)
Definition at line 1079 of file profile-generator.cc.
                                                      {
  return StartProfiling(++last_id_, title, std::move(options),
                        std::move(delegate));
}
References last_id_.
Referenced by StartProfilingForTesting().
StartProfiling() [2/2]
CpuProfilingResult v8::internal::CpuProfilesCollection::StartProfiling (ProfilerId id, const char * title = nullptr, CpuProfilingOptions options = {}, std::unique_ptr< DiscardedSamplesDelegate > delegate = nullptr) [private]
Definition at line 1086 of file profile-generator.cc.
                                                      {
  base::RecursiveMutexGuard profiles_guard{&current_profiles_mutex_};
  if (static_cast<int>(current_profiles_.size()) >= kMaxSimultaneousProfiles) {
    return {
        0,
        CpuProfilingStatus::kErrorTooManyProfilers,
    };
  }
  for (const std::unique_ptr<CpuProfile>& profile : current_profiles_) {
    if ((profile->title() != nullptr && title != nullptr &&
         strcmp(profile->title(), title) == 0) ||
        profile->id() == id) {
      // Ignore attempts to start profile with the same title or id
      // ... though return kAlreadyStarted to force it collect a sample.
      return {
          profile->id(),
          CpuProfilingStatus::kAlreadyStarted,
      };
    }
  }
  CpuProfile* profile = new CpuProfile(profiler_, id, title, std::move(options),
                                       std::move(delegate));
  current_profiles_.emplace_back(profile);
  return {
      profile->id(),
      CpuProfilingStatus::kStarted,
  };
}
References current_profiles_, current_profiles_mutex_, v8::internal::CpuProfile::id(), v8::kAlreadyStarted, v8::kErrorTooManyProfilers, kMaxSimultaneousProfiles, v8::kStarted, and profiler_.
StartProfilingForTesting()
CpuProfilingResult v8::internal::CpuProfilesCollection::StartProfilingForTesting (ProfilerId id)
Definition at line 1074 of file profile-generator.cc.
                   {
  return StartProfiling(id);
}
References StartProfiling().
StopProfiling()
CpuProfile * v8::internal::CpuProfilesCollection::StopProfiling (ProfilerId id)
Definition at line 1120 of file profile-generator.cc.
                                                              {
  base::RecursiveMutexGuard profiles_guard{&current_profiles_mutex_};
  CpuProfile* profile = nullptr;
  auto it = std::find_if(
      current_profiles_.rbegin(), current_profiles_.rend(),
      [=](const std::unique_ptr<CpuProfile>& p) { return id == p->id(); });
  if (it != current_profiles_.rend()) {
    (*it)->FinishProfile();
    profile = it->get();
    finished_profiles_.push_back(std::move(*it));
    // Convert reverse iterator to matching forward iterator.
    current_profiles_.erase(--(it.base()));
  }
  return profile;
}
References current_profiles_, current_profiles_mutex_, and finished_profiles_.
UpdateNativeContextAddressForCurrentProfiles()
void v8::internal::CpuProfilesCollection::UpdateNativeContextAddressForCurrentProfiles (Address from, Address to)
Definition at line 1238 of file profile-generator.cc.
                              {
  base::RecursiveMutexGuard profiles_guard{&current_profiles_mutex_};
  for (const std::unique_ptr<CpuProfile>& profile : current_profiles_) {
    profile->context_filter().OnMoveEvent(from, to);
  }
}
References current_profiles_, and current_profiles_mutex_.
Referenced by v8::internal::ProfilerEventsProcessor::ProcessCodeEvent().
Member Data Documentation
current_profiles_
std::vector<std::unique_ptr<CpuProfile> > v8::internal::CpuProfilesCollection::current_profiles_ [private]
Definition at line 608 of file profile-generator.h.
Referenced by AddPathToCurrentProfiles(), GetCommonSamplingInterval(), IsLastProfileLeft(), Lookup(), StartProfiling(), StopProfiling(), and UpdateNativeContextAddressForCurrentProfiles().
current_profiles_mutex_
base::RecursiveMutex v8::internal::CpuProfilesCollection::current_profiles_mutex_ [private]
Definition at line 609 of file profile-generator.h.
Referenced by AddPathToCurrentProfiles(), GetCommonSamplingInterval(), IsLastProfileLeft(), Lookup(), StartProfiling(), StopProfiling(), and UpdateNativeContextAddressForCurrentProfiles().
finished_profiles_
std::vector<std::unique_ptr<CpuProfile> > v8::internal::CpuProfilesCollection::finished_profiles_ [private]
Definition at line 604 of file profile-generator.h.
Referenced by RemoveProfile(), and StopProfiling().
isolate_
Isolate* v8::internal::CpuProfilesCollection::isolate_ [private]
Definition at line 611 of file profile-generator.h.
Referenced by CpuProfilesCollection(), and RemoveProfile().
kMaxSimultaneousProfiles
const int v8::internal::CpuProfilesCollection::kMaxSimultaneousProfiles = 100 [static]
Definition at line 596 of file profile-generator.h.
Referenced by StartProfiling().
last_id_
std::atomic< ProfilerId > v8::internal::CpuProfilesCollection::last_id_ {0} [static], [private]
Definition at line 610 of file profile-generator.h.
Referenced by StartProfiling().
profiler_
CpuProfiler* v8::internal::CpuProfilesCollection::profiler_ [private]
Definition at line 605 of file profile-generator.h.
Referenced by GetCommonSamplingInterval(), and StartProfiling().
resource_names_
StringsStorage v8::internal::CpuProfilesCollection::resource_names_ [private]
Definition at line 603 of file profile-generator.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/profiler/profile-generator.h
/mnt/V8SourceCode/src/profiler/profile-generator.cc