v8::Context Class Reference
A sandboxed execution context with its own set of built-in objects and functions.
#include <v8-context.h>
Classes
class BackupIncumbentScope
Stack-allocated class to support the backup incumbent settings object stack.
class DeepFreezeDelegate
Delegate to help with Deep freezing embedder-specific objects (such as JSApiObjects) that can not be frozen natively.
class Scope
Stack-allocated class which sets the execution context for all operations executed within a local scope.
Public Types
enum EmbedderDataFields { kDebugIdIndex = 0
 }
The field at kDebugIdIndex used to be reserved for the inspector.
using AbortScriptExecutionCallback = void(*)(Isolate *isolate, Local< Context > context)
If callback is set, abort any attempt to execute JavaScript in this context, call the specified callback, and throw an exception.
Public Member Functions
Local< Object > Global ()
Returns the global proxy object.
void DetachGlobal ()
Detaches the global object from its context before the global object can be reused to create a new context.
void SetSecurityToken (Local< Value > token)
Sets the security token for the context.
void UseDefaultSecurityToken ()
Restores the security token to the default value.
Local< Value > GetSecurityToken ()
Returns the security token of this context.
void Enter ()
Enter this context.
void Exit ()
Exit this context.
Maybe< void > DeepFreeze (DeepFreezeDelegate *delegate=nullptr)
Attempts to recursively freeze all objects reachable from this context.
Use Isolate::GetCurrent () instead
Returns the isolate associated with a current context.
MicrotaskQueue * GetMicrotaskQueue ()
Returns the microtask queue associated with a current context.
void SetMicrotaskQueue (MicrotaskQueue *queue)
Sets the microtask queue associated with the current context.
uint32_t GetNumberOfEmbedderDataFields ()
Return the number of fields allocated for embedder data.
Local< Value > GetEmbedderData (int index)
Gets the embedder data with the given index, which must have been set by a previous call to SetEmbedderData with the same index.
Local< Object > GetExtrasBindingObject ()
Gets the binding object used by V8 extras.
void SetEmbedderData (int index, Local< Value > value)
Sets the embedder data with the given index, growing the data as needed.
void * GetAlignedPointerFromEmbedderData (Isolate *isolate, int index)
Gets a 2-byte-aligned native pointer from the embedder data with the given index, which must have been set by a previous call to SetAlignedPointerInEmbedderData with the same index.
void * GetAlignedPointerFromEmbedderData (int index)
void SetAlignedPointerInEmbedderData (int index, void *value)
Sets a 2-byte-aligned native pointer in the embedder data with the given index, growing the data as needed.
void AllowCodeGenerationFromStrings (bool allow)
Control whether code generation from strings is allowed.
bool IsCodeGenerationFromStringsAllowed () const
Returns true if code generation from strings is allowed for the context.
void SetErrorMessageForCodeGenerationFromStrings (Local< String > message)
Sets the error description for the exception that is thrown when code generation from strings is not allowed and 'eval' or the 'Function' constructor are called.
void SetErrorMessageForWasmCodeGeneration (Local< String > message)
Sets the error description for the exception that is thrown when wasm code generation is not allowed.
template<class T >
MaybeLocal< T > GetDataFromSnapshotOnce (size_t index)
Return data that was previously attached to the context snapshot via SnapshotCreator, and removes the reference to it.
void SetAbortScriptExecution (AbortScriptExecutionCallback callback)
void SetPromiseHooks (Local< Function > init_hook, Local< Function > before_hook, Local< Function > after_hook, Local< Function > resolve_hook)
Set or clear hooks to be invoked for promise lifecycle operations.
bool HasTemplateLiteralObject (Local< Value > object)
Static Public Member Functions
static Local< Context > New (Isolate *isolate, ExtensionConfiguration *extensions=nullptr, MaybeLocal< ObjectTemplate > global_template=MaybeLocal< ObjectTemplate >(), MaybeLocal< Value > global_object=MaybeLocal< Value >(), DeserializeInternalFieldsCallback internal_fields_deserializer=DeserializeInternalFieldsCallback(), MicrotaskQueue *microtask_queue=nullptr, DeserializeContextDataCallback context_data_deserializer=DeserializeContextDataCallback(), DeserializeAPIWrapperCallback api_wrapper_deserializer=DeserializeAPIWrapperCallback())
Creates a new context and returns a handle to the newly allocated context.
static MaybeLocal< Context > FromSnapshot (Isolate *isolate, size_t context_snapshot_index, DeserializeInternalFieldsCallback internal_fields_deserializer=DeserializeInternalFieldsCallback(), ExtensionConfiguration *extensions=nullptr, MaybeLocal< Value > global_object=MaybeLocal< Value >(), MicrotaskQueue *microtask_queue=nullptr, DeserializeContextDataCallback context_data_deserializer=DeserializeContextDataCallback(), DeserializeAPIWrapperCallback api_wrapper_deserializer=DeserializeAPIWrapperCallback())
Create a new context from a (non-default) context snapshot.
static MaybeLocal< Object > NewRemoteContext (Isolate *isolate, Local< ObjectTemplate > global_template, MaybeLocal< Value > global_object=MaybeLocal< Value >())
Returns an global object that isn't backed by an actual context.
static Context * Cast (Data *data)
Public Attributes
Use which is guaranteed to return the same isolate since https: Isolate* GetIsolate()
Private Member Functions
internal::ValueHelper::InternalRepresentationType GetDataFromSnapshotOnce (size_t index)
Local< Value > SlowGetEmbedderData (int index)
void * SlowGetAlignedPointerFromEmbedderData (int index)
Static Private Member Functions
static void CheckCast (Data *obj)
Friends
class Value
class Script
class Object
class Function
Detailed Description
A sandboxed execution context with its own set of built-in objects and functions.
Definition at line 48 of file v8-context.h.
Member Typedef Documentation
AbortScriptExecutionCallback
using v8::Context::AbortScriptExecutionCallback = void (*)(Isolate* isolate, Local<Context> context)
If callback is set, abort any attempt to execute JavaScript in this context, call the specified callback, and throw an exception.
To unset abort, pass nullptr as callback.
Definition at line 366 of file v8-context.h.
Member Enumeration Documentation
EmbedderDataFields
enum v8::Context::EmbedderDataFields
The field at kDebugIdIndex used to be reserved for the inspector.
It now serves no purpose.
Enumerator
kDebugIdIndex
Definition at line 274 of file v8-context.h.
{ kDebugIdIndex = 0 };
Member Function Documentation
AllowCodeGenerationFromStrings()
void v8::Context::AllowCodeGenerationFromStrings (bool allow)
Control whether code generation from strings is allowed.
Calling this method with false will disable 'eval' and the 'Function' constructor for code running in this context. If 'eval' or the 'Function' constructor are used an exception will be thrown.
If code generation from strings is not allowed the V8::ModifyCodeGenerationFromStringsCallback callback will be invoked if set before blocking the call to 'eval' or the 'Function' constructor. If that callback returns true, the call will be allowed, otherwise an exception will be thrown. If no callback is set an exception will be thrown.
Definition at line 7183 of file api.cc.
                                                       {
  auto context = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  context->set_allow_code_gen_from_strings(
      i::ReadOnlyRoots(i_isolate).boolean_value(allow));
}
References v8::internal::Isolate::Current(), and v8::Utils::OpenDirectHandle().
Cast()
Context * v8::Context::Cast (v8::Data * data) [inline], [static]
Definition at line 511 of file v8-context.h.
                                   {
#ifdef V8_ENABLE_CHECKS
  CheckCast(data);
#endif
  return static_cast<Context*>(data);
}
References CheckCast().
CheckCast()
void v8::Context::CheckCast (v8::Data * that) [static], [private]
Definition at line 3955 of file api.cc.
                                      {
  auto obj = Utils::OpenDirectHandle(that);
  Utils::ApiCheck(i::IsContext(*obj), "v8::Context::Cast",
                  "Value is not a Context");
}
References v8::Utils::ApiCheck(), and v8::Utils::OpenDirectHandle().
Referenced by Cast().
DeepFreeze()
Maybe< void > v8::Context::DeepFreeze (DeepFreezeDelegate * delegate = nullptr)
Attempts to recursively freeze all objects reachable from this context.
Some objects (generators, iterators, non-const closures) can not be frozen and will cause this method to throw an error. An optional delegate can be provided to help freeze embedder-specific objects.
Freezing occurs in two steps:
`Marking` where we iterate through all objects reachable by this context, accumulating a list of objects that need to be frozen and looking for objects that can't be frozen. This step is separated because it is more efficient when we can assume there is no garbage collection.
`Freezing` where we go through the list of objects and freezing them. This effectively requires copying them so it may trigger garbage collection.
Definition at line 7111 of file api.cc.
                                                            {
  auto env = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  // TODO(behamilton): Incorporate compatibility improvements similar to NodeJS:
  // https://github.com/nodejs/node/blob/main/lib/internal/freeze_intrinsics.js
  // These need to be done before freezing.
  Local<Context> context = Utils::ToLocal(env);
  EnterV8NoScriptScope<> api_scope{i_isolate, context,
                                   RCCId::kAPI_Context_DeepFreeze};
  ObjectVisitorDeepFreezer vfreezer(i_isolate, delegate);
  if (!vfreezer.DeepFreeze(env)) return {};
  return JustVoid();
}
References v8::internal::Isolate::Current(), v8::JustVoid(), and v8::Utils::OpenDirectHandle().
DetachGlobal()
void v8::Context::DetachGlobal ()
Detaches the global object from its context before the global object can be reused to create a new context.
Definition at line 7169 of file api.cc.
                           {
  auto context = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i_isolate->DetachGlobal(context);
}
References v8::internal::Isolate::Current(), v8::internal::Isolate::DetachGlobal(), and v8::Utils::OpenDirectHandle().
Referenced by v8::Shell::RealmDetachGlobal().
Enter()
void v8::Context::Enter ()
Enter this context.
After entering a context, all code compiled and run is compiled and run in this context. If another context is already entered, this old context is saved so it can be restored when the new context is exited.
Definition at line 831 of file api.cc.
                    {
  i::DisallowGarbageCollection no_gc;
  i::Tagged<i::NativeContext> env = *Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::HandleScopeImplementer* impl = i_isolate->handle_scope_implementer();
  impl->EnterContext(env);
  impl->SaveContext(i_isolate->context());
  i_isolate->set_context(env);
}
References v8::internal::Isolate::context(), v8::internal::Isolate::Current(), v8::internal::Isolate::handle_scope_implementer(), wasm::impl(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::Utils::OpenDirectHandle(), and v8::internal::Isolate::set_context().
Referenced by v8::PerIsolateData::ExplicitRealmScope::ExplicitRealmScope(), and v8::Shell::ReportException().
Exit()
void v8::Context::Exit ()
Exit this context.
Exiting the current context restores the context that was in place when entering the current context.
Definition at line 842 of file api.cc.
                   {
  auto env = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::HandleScopeImplementer* impl = i_isolate->handle_scope_implementer();
  if (!Utils::ApiCheck(impl->LastEnteredContextWas(*env), "v8::Context::Exit()",
                       "Cannot exit non-entered context")) {
    return;
  }
  impl->LeaveContext();
  i_isolate->set_context(impl->RestoreContext());
}
References v8::Utils::ApiCheck(), v8::internal::Isolate::Current(), v8::internal::Isolate::handle_scope_implementer(), wasm::impl(), v8::Utils::OpenDirectHandle(), and v8::internal::Isolate::set_context().
Referenced by v8::Shell::ReportException(), and wasm::StoreImpl::~StoreImpl().
FromSnapshot()
MaybeLocal< Context > v8::Context::FromSnapshot (v8::Isolate * external_isolate, size_t context_snapshot_index, v8::DeserializeInternalFieldsCallback internal_fields_deserializer = DeserializeInternalFieldsCallback(), v8::ExtensionConfiguration * extensions = nullptr, MaybeLocal< Value > global_object = MaybeLocal<Value>(), v8::MicrotaskQueue * microtask_queue = nullptr, v8::DeserializeContextDataCallback context_callback_deserializer = DeserializeContextDataCallback(), v8::DeserializeAPIWrapperCallback api_wrapper_deserializer = DeserializeAPIWrapperCallback()) [static]
Create a new context from a (non-default) context snapshot.
There is no way to provide a global object template since we do not create a new global object from template, but we can reuse a global object.
Parameters
isolate See v8::Context::New().
context_snapshot_index The index of the context snapshot to deserialize from. Use v8::Context::New() for the default snapshot.
internal_fields_deserializer An optional callback used to deserialize fields set by v8::Object::SetAlignedPointerInInternalField() in wrapper objects from the default context snapshot. It does not need to be configured if there are no wrapper objects with no internal pointer fields in the default context snapshot or if no startup snapshot is configured when the isolate is created.
extensions See v8::Context::New().
global_object See v8::Context::New().
internal_fields_deserializer Similar to internal_fields_deserializer in v8::Context::New() but applies to the context specified by the context_snapshot_index.
microtask_queue See v8::Context::New().
context_data_deserializer Similar to context_data_deserializer in v8::Context::New() but applies to the context specified by the context_snapshot_index.
api_wrapper_deserializer Similar to api_wrapper_deserializer in v8::Context::New() but applies to the context specified by the context_snapshot_index.
Definition at line 6744 of file api.cc.
                                                              {
  size_t index_including_default_context = context_snapshot_index + 1;
  if (!i::Snapshot::HasContextSnapshot(
          reinterpret_cast<i::Isolate*>(external_isolate),
          index_including_default_context)) {
    return {};
  }
  return NewContext(
      external_isolate, extensions, MaybeLocal<ObjectTemplate>(), global_object,
      index_including_default_context,
      i::DeserializeEmbedderFieldsCallback(internal_fields_deserializer,
                                           context_callback_deserializer,
                                           api_wrapper_deserializer),
      microtask_queue);
}
References v8::internal::Snapshot::HasContextSnapshot(), and v8::NewContext().
GetAlignedPointerFromEmbedderData() [1/2]
void * v8::Context::GetAlignedPointerFromEmbedderData (int index) [inline]
Definition at line 482 of file v8-context.h.
                                                          {
#if !defined(V8_ENABLE_CHECKS)
  using A = internal::Address;
  using I = internal::Internals;
  A ctx = internal::ValueHelper::ValueAsAddress(this);
  A embedder_data =
      I::ReadTaggedPointerField(ctx, I::kNativeContextEmbedderDataOffset);
  int value_offset = I::kEmbedderDataArrayHeaderSize +
                     (I::kEmbedderDataSlotSize * index) +
                     I::kEmbedderDataSlotExternalPointerOffset;
  Isolate* isolate = I::GetCurrentIsolateForSandbox();
  return reinterpret_cast<void*>(
      I::ReadExternalPointerField<internal::kEmbedderDataSlotPayloadTag>(
          isolate, embedder_data, value_offset));
#else
  return SlowGetAlignedPointerFromEmbedderData(index);
#endif
}
References v8::internal::A, v8::internal::GetCurrentIsolateForSandbox(), I, v8::internal::index, v8::internal::kEmbedderDataSlotSize, SlowGetAlignedPointerFromEmbedderData(), and v8::internal::ValueHelper::ValueAsAddress().
GetAlignedPointerFromEmbedderData() [2/2]
void * v8::Context::GetAlignedPointerFromEmbedderData (Isolate * isolate, int index) [inline]
Gets a 2-byte-aligned native pointer from the embedder data with the given index, which must have been set by a previous call to SetAlignedPointerInEmbedderData with the same index.
Note that index 0 currently has a special meaning for Chrome's debugger.
Definition at line 464 of file v8-context.h.
                                                                            {
#if !defined(V8_ENABLE_CHECKS)
  using A = internal::Address;
  using I = internal::Internals;
  A ctx = internal::ValueHelper::ValueAsAddress(this);
  A embedder_data =
      I::ReadTaggedPointerField(ctx, I::kNativeContextEmbedderDataOffset);
  int value_offset = I::kEmbedderDataArrayHeaderSize +
                     (I::kEmbedderDataSlotSize * index) +
                     I::kEmbedderDataSlotExternalPointerOffset;
  return reinterpret_cast<void*>(
      I::ReadExternalPointerField<internal::kEmbedderDataSlotPayloadTag>(
          isolate, embedder_data, value_offset));
#else
  return SlowGetAlignedPointerFromEmbedderData(index);
#endif
}
References v8::internal::A, I, v8::internal::index, v8::internal::kEmbedderDataSlotSize, SlowGetAlignedPointerFromEmbedderData(), and v8::internal::ValueHelper::ValueAsAddress().
Referenced by v8::InspectorClient::GetSession(), and SetAlignedPointerInEmbedderData().
GetDataFromSnapshotOnce() [1/2]
template<class T >
MaybeLocal< T > v8::Context::GetDataFromSnapshotOnce (size_t index) [inline]
Return data that was previously attached to the context snapshot via SnapshotCreator, and removes the reference to it.
Repeated call with the same index returns an empty MaybeLocal.
Definition at line 502 of file v8-context.h.
                                                           {
  if (auto repr = GetDataFromSnapshotOnce(index);
      repr != internal::ValueHelper::kEmpty) {
    internal::PerformCastCheck(internal::ValueHelper::ReprAsValue<T>(repr));
    return Local<T>::FromRepr(repr);
  }
  return {};
}
References v8::Local< T >::FromRepr(), v8::internal::index, v8::internal::ValueHelper::kEmpty, and v8::internal::PerformCastCheck().
GetDataFromSnapshotOnce() [2/2]
i::ValueHelper::InternalRepresentationType v8::Context::GetDataFromSnapshotOnce (size_t index) [private]
Definition at line 7316 of file api.cc.
                  {
  auto context = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  auto list = i::Cast<i::FixedArray>(context->serialized_objects());
  return GetSerializedDataFromFixedArray(i_isolate, list, index);
}
References v8::internal::Isolate::Current(), v8::anonymous_namespace{api.cc}::GetSerializedDataFromFixedArray(), v8::internal::index, and v8::Utils::OpenDirectHandle().
GetEmbedderData()
Local< Value > v8::Context::GetEmbedderData (int index) [inline]
Gets the embedder data with the given index, which must have been set by a previous call to SetEmbedderData with the same index.
Definition at line 441 of file v8-context.h.
                                               {
#ifndef V8_ENABLE_CHECKS
  using A = internal::Address;
  using I = internal::Internals;
  A ctx = internal::ValueHelper::ValueAsAddress(this);
  A embedder_data =
      I::ReadTaggedPointerField(ctx, I::kNativeContextEmbedderDataOffset);
  int value_offset =
      I::kEmbedderDataArrayHeaderSize + (I::kEmbedderDataSlotSize * index);
  A value = I::ReadRawField<A>(embedder_data, value_offset);
#ifdef V8_COMPRESS_POINTERS
  // We read the full pointer value and then decompress it in order to avoid
  // dealing with potential endiannes issues.
  value = I::DecompressTaggedField(embedder_data, static_cast<uint32_t>(value));
#endif
  auto* isolate = I::GetCurrentIsolate();
  return Local<Value>::New(isolate, value);
#else
  return SlowGetEmbedderData(index);
#endif
}
References v8::internal::A, v8::internal::GetCurrentIsolate(), I, v8::internal::index, v8::internal::kEmbedderDataSlotSize, v8::Local< T >::New(), SlowGetEmbedderData(), v8::internal::value, and v8::internal::ValueHelper::ValueAsAddress().
Referenced by v8::anonymous_namespace{d8.cc}::GetModuleDataFromContext(), and SetEmbedderData().
GetExtrasBindingObject()
Local< v8::Object > v8::Context::GetExtrasBindingObject ()
Gets the binding object used by V8 extras.
Extra natives get a reference to this object and can use it to `export` functionality by adding properties. Extra natives can also `import` functionality by accessing properties added by the embedder using the V8 API.
Definition at line 7176 of file api.cc.
                                                {
  auto context = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  return Utils::ToLocal(
      i::direct_handle(context->extras_binding_object(), i_isolate));
}
References v8::internal::Isolate::Current(), v8::internal::direct_handle(), and v8::Utils::OpenDirectHandle().
Referenced by v8::Shell::CreateEvaluationContext(), and v8::Shell::GetExtrasBindingObject().
GetMicrotaskQueue()
v8::MicrotaskQueue * v8::Context::GetMicrotaskQueue ()
Returns the microtask queue associated with a current context.
Definition at line 7129 of file api.cc.
                                             {
  auto env = Utils::OpenDirectHandle(this);
  Utils::ApiCheck(i::IsNativeContext(*env), "v8::Context::GetMicrotaskQueue",
                  "Must be called on a native context");
  return env->microtask_queue();
}
References v8::Utils::ApiCheck(), and v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::V8Debugger::installTerminateExecutionCallbacks().
GetNumberOfEmbedderDataFields()
uint32_t v8::Context::GetNumberOfEmbedderDataFields ()
Return the number of fields allocated for embedder data.
Definition at line 907 of file api.cc.
                                                {
  auto context = Utils::OpenDirectHandle(this);
  i::DisallowJavascriptExecutionDebugOnly no_execution;
  i::DisallowExceptionsDebugOnly no_exceptions;
  Utils::ApiCheck(i::IsNativeContext(*context),
                  "Context::GetNumberOfEmbedderDataFields",
                  "Not a native context");
  // TODO(ishell): remove cast once embedder_data slot has a proper type.
  return static_cast<uint32_t>(
      i::Cast<i::EmbedderDataArray>(context->embedder_data())->length());
}
References v8::Utils::ApiCheck(), and v8::Utils::OpenDirectHandle().
GetSecurityToken()
Local< Value > v8::Context::GetSecurityToken ()
Returns the security token of this context.
Definition at line 6807 of file api.cc.
                                         {
  auto env = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  i::Tagged<i::Object> security_token = env->security_token();
  return Utils::ToLocal(i::direct_handle(security_token, i_isolate));
}
References v8::internal::Isolate::Current(), v8::internal::direct_handle(), and v8::Utils::OpenDirectHandle().
Referenced by v8::Shell::HostCreateShadowRealmContext(), v8::Shell::RealmCreateAllowCrossRealmAccess(), and v8::internal::MeasureMemoryDelegate::ShouldMeasure().
Global()
v8::Local< v8::Object > v8::Context::Global ()
Returns the global proxy object.
Global proxy object is a thin wrapper whose prototype points to actual context's global object with the properties like Object, etc. This is done that way for security reasons (for more details see https://wiki.mozilla.org/Gecko:SplitWindow).
Please note that changes to global proxy object prototype most probably would break VM---v8 expects only global object as a prototype of global proxy object.
Definition at line 7156 of file api.cc.
                                  {
  auto context = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  i::DirectHandle<i::JSGlobalProxy> global(context->global_proxy(), i_isolate);
  // TODO(chromium:324812): This should always return the global proxy
  // but can't presently as calls to GetPrototype will return the wrong result.
  if (global->IsDetachedFrom(i_isolate, context->global_object())) {
    i::DirectHandle<i::JSObject> result(context->global_object(), i_isolate);
    return Utils::ToLocal(result);
  }
  return Utils::ToLocal(i::Cast<i::JSObject>(global));
}
References v8::internal::Isolate::Current(), v8::internal::Isolate::global_object(), v8::Utils::OpenDirectHandle(), and v8::base::internal::result.
Referenced by v8_inspector::V8RuntimeAgentImpl::addBinding(), v8_inspector::V8RuntimeAgentImpl::callFunctionOn(), v8::Shell::CreateEvaluationContext(), v8_inspector::anonymous_namespace{value-mirror.cc}::doesAttributeHaveObservableSideEffectOnGet(), v8::Worker::ExecuteInThread(), v8_inspector::generateCustomPreview(), v8_inspector::InspectedContext::InspectedContext(), v8::InspectorClient::InspectorClient(), v8::Worker::ProcessMessage(), v8::Shell::RealmNavigate(), v8::OnMessageFromWorkerTask::Run(), v8::InspectorClient::runMessageLoopOnPause(), and v8::InspectorFrontend::Send().
HasTemplateLiteralObject()
bool v8::Context::HasTemplateLiteralObject (Local< Value > object)
Definition at line 7267 of file api.cc.
                                                          {
  i::DisallowGarbageCollection no_gc;
  i::Tagged<i::Object> i_object = *Utils::OpenDirectHandle(*object);
  if (!IsJSArray(i_object)) return false;
  return Utils::OpenDirectHandle(this)
      ->native_context()
      ->HasTemplateLiteralObject(i::Cast<i::JSArray>(i_object));
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::Utils::OpenDirectHandle().
IsCodeGenerationFromStringsAllowed()
bool v8::Context::IsCodeGenerationFromStringsAllowed () const
Returns true if code generation from strings is allowed for the context.
For more details see AllowCodeGenerationFromStrings(bool) documentation.
Definition at line 7191 of file api.cc.
                                                       {
  auto context = Utils::OpenDirectHandle(this);
  return !IsFalse(context->allow_code_gen_from_strings(),
                  i::Isolate::Current());
}
References v8::internal::Isolate::Current(), and v8::Utils::OpenDirectHandle().
Isolate::GetCurrent()
Use v8::Context::Isolate::GetCurrent ()
Returns the isolate associated with a current context.
New()
Local< Context > v8::Context::New (v8::Isolate * external_isolate, v8::ExtensionConfiguration * extensions = nullptr, v8::MaybeLocal< ObjectTemplate > global_template = MaybeLocal<ObjectTemplate>(), v8::MaybeLocal< Value > global_object = MaybeLocal<Value>(), v8::DeserializeInternalFieldsCallback internal_fields_deserializer = DeserializeInternalFieldsCallback(), v8::MicrotaskQueue * microtask_queue = nullptr, v8::DeserializeContextDataCallback context_callback_deserializer = DeserializeContextDataCallback(), v8::DeserializeAPIWrapperCallback api_wrapper_deserializer = DeserializeAPIWrapperCallback()) [static]
Creates a new context and returns a handle to the newly allocated context.
Parameters
isolate The isolate in which to create the context.
extensions An optional extension configuration containing the extensions to be installed in the newly created context.
global_template An optional object template from which the global object for the newly created context will be created.
global_object An optional global object to be reused for the newly created context. This global object must have been created by a previous call to Context::New with the same global template. The state of the global object will be completely reset and only object identify will remain.
internal_fields_deserializer An optional callback used to deserialize fields set by v8::Object::SetAlignedPointerInInternalField() in wrapper objects from the default context snapshot. It should match the SerializeInternalFieldsCallback() used by v8::SnapshotCreator::SetDefaultContext() when the default context snapshot is created. It does not need to be configured if the default context snapshot contains no wrapper objects with pointer internal fields, or if no custom startup snapshot is configured in the v8::CreateParams used to create the isolate.
microtask_queue An optional microtask queue used to manage the microtasks created in this context. If not set the per-isolate default microtask queue would be used.
context_data_deserializer An optional callback used to deserialize embedder data set by v8::Context::SetAlignedPointerInEmbedderData() in the default context from the default context snapshot. It does not need to be configured if the default context snapshot contains no pointer embedder data, or if no custom startup snapshot is configured in the v8::CreateParams used to create the isolate.
api_wrapper_deserializer An optional callback used to deserialize API wrapper objects that was initially set with v8::Object::Wrap() and then serialized using SerializeAPIWrapperCallback.
Definition at line 6728 of file api.cc.
                                                              {
  return NewContext(
      external_isolate, extensions, global_template, global_object, 0,
      i::DeserializeEmbedderFieldsCallback(internal_fields_deserializer,
                                           context_callback_deserializer,
                                           api_wrapper_deserializer),
      microtask_queue);
}
References v8::NewContext().
Referenced by v8::Shell::CreateEvaluationContext(), v8::Shell::CreateRealm(), v8::internal::CreateSnapshotDataBlobInternal(), v8_inspector::V8InspectorImpl::exceptionMetaDataContext(), v8::tracing::anonymous_namespace{d8.cc}::TraceConfigParser::FillTraceConfig(), v8::Shell::HostCreateShadowRealmContext(), v8_inspector::V8InspectorImpl::regexContext(), v8::internal::WarmUpSnapshotDataBlobInternal(), v8::internal::wasm::WasmModuleSourceMap::WasmModuleSourceMap(), and v8::Shell::WriteIgnitionDispatchCountersFile().
NewRemoteContext()
MaybeLocal< Object > v8::Context::NewRemoteContext (v8::Isolate * external_isolate, v8::Local< ObjectTemplate > global_template, MaybeLocal< Value > global_object = MaybeLocal<Value>()) [static]
Returns an global object that isn't backed by an actual context.
The global template needs to have access checks with handlers installed. If an existing global object is passed in, the global object is detached from its context.
Note that this is different from a detached context where all accesses to the global proxy will fail. Instead, the access check handlers are invoked.
It is also not possible to detach an object returned by this method. Instead, the access check handlers need to return nothing to achieve the same effect.
It is possible, however, to create a new context from the global object returned by this method.
Definition at line 6766 of file api.cc.
                                         {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(external_isolate);
  ApiRuntimeCallStatsScope rcs_scope(i_isolate,
                                     RCCId::kAPI_Context_NewRemoteContext);
  i::HandleScope scope(i_isolate);
  i::DirectHandle<i::FunctionTemplateInfo> global_constructor =
      EnsureConstructor(i_isolate, *global_template);
  Utils::ApiCheck(global_constructor->needs_access_check(),
                  "v8::Context::NewRemoteContext",
                  "Global template needs to have access checks enabled");
  i::DirectHandle<i::AccessCheckInfo> access_check_info(
      i::Cast<i::AccessCheckInfo>(global_constructor->GetAccessCheckInfo()),
      i_isolate);
  Utils::ApiCheck(
      access_check_info->named_interceptor() != i::Tagged<i::Object>(),
      "v8::Context::NewRemoteContext",
      "Global template needs to have access check handlers");
  i::DirectHandle<i::JSObject> global_proxy =
      CreateEnvironment<i::JSGlobalProxy>(
          i_isolate, nullptr, global_template, global_object, 0,
          i::DeserializeEmbedderFieldsCallback(), nullptr);
  if (global_proxy.is_null()) {
    if (i_isolate->has_exception()) i_isolate->clear_exception();
    return {};
  }
  return Utils::ToLocal(scope.CloseAndEscape(global_proxy));
}
References v8::Utils::ApiCheck(), v8::internal::Isolate::clear_exception(), v8::anonymous_namespace{api.cc}::EnsureConstructor(), v8::internal::Isolate::has_exception(), and v8::internal::DirectHandle< T >::is_null().
SetAbortScriptExecution()
void v8::Context::SetAbortScriptExecution (Context::AbortScriptExecutionCallback callback)
Definition at line 7209 of file api.cc.
                                                  {
  auto context = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  if (callback == nullptr) {
    context->set_script_execution_callback(
        i::ReadOnlyRoots(i_isolate).undefined_value());
  } else {
    SET_FIELD_WRAPPED(i_isolate, context, set_script_execution_callback,
                      callback, internal::kApiAbortScriptExecutionCallbackTag);
  }
}
References v8::internal::Isolate::Current(), v8::internal::kApiAbortScriptExecutionCallbackTag, v8::Utils::OpenDirectHandle(), and SET_FIELD_WRAPPED.
SetAlignedPointerInEmbedderData()
void v8::Context::SetAlignedPointerInEmbedderData (int index, void * value)
Sets a 2-byte-aligned native pointer in the embedder data with the given index, growing the data as needed.
Note that index 0 currently has a special meaning for Chrome's debugger.
Definition at line 954 of file api.cc.
                                                                    {
  const char* location = "v8::Context::SetAlignedPointerInEmbedderData()";
  i::Isolate* i_isolate = i::Isolate::Current();
  i::DirectHandle<i::EmbedderDataArray> data =
      EmbedderDataFor(this, index, true, location);
  bool ok = i::EmbedderDataSlot(*data, index)
                .store_aligned_pointer(i_isolate, *data, value);
  Utils::ApiCheck(ok, location, "Pointer is not aligned");
  DCHECK_EQ(value, GetAlignedPointerFromEmbedderData(index));
}
References v8::Utils::ApiCheck(), v8::internal::Isolate::Current(), DCHECK_EQ, v8::EmbedderDataFor(), GetAlignedPointerFromEmbedderData(), v8::internal::index, v8::internal::EmbedderDataSlot::store_aligned_pointer(), and v8::internal::value.
Referenced by v8::InspectorClient::InspectorClient().
SetEmbedderData()
void v8::Context::SetEmbedderData (int index, v8::Local< Value > value)
Sets the embedder data with the given index, growing the data as needed.
Note that index 0 currently has a special meaning for Chrome's debugger.
Definition at line 929 of file api.cc.
                                                             {
  const char* location = "v8::Context::SetEmbedderData()";
  i::DirectHandle<i::EmbedderDataArray> data =
      EmbedderDataFor(this, index, true, location);
  if (data.is_null()) return;
  auto val = Utils::OpenDirectHandle(*value);
  i::EmbedderDataSlot::store_tagged(*data, index, *val);
  DCHECK_EQ(*Utils::OpenDirectHandle(*value),
            *Utils::OpenDirectHandle(*GetEmbedderData(index)));
}
References DCHECK_EQ, v8::EmbedderDataFor(), GetEmbedderData(), v8::internal::index, v8::internal::DirectHandle< T >::is_null(), v8::Utils::OpenDirectHandle(), v8::internal::EmbedderDataSlot::store_tagged(), and v8::internal::value.
Referenced by v8::anonymous_namespace{d8.cc}::InitializeModuleEmbedderData().
SetErrorMessageForCodeGenerationFromStrings()
void v8::Context::SetErrorMessageForCodeGenerationFromStrings (Local< String > message)
Sets the error description for the exception that is thrown when code generation from strings is not allowed and 'eval' or the 'Function' constructor are called.
Definition at line 7197 of file api.cc.
                                                                             {
  auto context = Utils::OpenDirectHandle(this);
  auto error_handle = Utils::OpenDirectHandle(*error);
  context->set_error_message_for_code_gen_from_strings(*error_handle);
}
References v8::Utils::OpenDirectHandle().
SetErrorMessageForWasmCodeGeneration()
void v8::Context::SetErrorMessageForWasmCodeGeneration (Local< String > message)
Sets the error description for the exception that is thrown when wasm code generation is not allowed.
Definition at line 7203 of file api.cc.
                                                                      {
  auto context = Utils::OpenDirectHandle(this);
  auto error_handle = Utils::OpenDirectHandle(*error);
  context->set_error_message_for_wasm_code_gen(*error_handle);
}
References v8::Utils::OpenDirectHandle().
SetMicrotaskQueue()
void v8::Context::SetMicrotaskQueue (v8::MicrotaskQueue * queue)
Sets the microtask queue associated with the current context.
Definition at line 7136 of file api.cc.
                                                       {
  auto context = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  Utils::ApiCheck(i::IsNativeContext(*context),
                  "v8::Context::SetMicrotaskQueue",
                  "Must be called on a native context");
  i::HandleScopeImplementer* impl = i_isolate->handle_scope_implementer();
  Utils::ApiCheck(!context->microtask_queue()->IsRunningMicrotasks(),
                  "v8::Context::SetMicrotaskQueue",
                  "Must not be running microtasks");
  Utils::ApiCheck(context->microtask_queue()->GetMicrotasksScopeDepth() == 0,
                  "v8::Context::SetMicrotaskQueue",
                  "Must not have microtask scope pushed");
  Utils::ApiCheck(impl->EnteredContextCount() == 0,
                  "v8::Context::SetMicrotaskQueue()",
                  "Cannot set Microtask Queue with an entered context");
  context->set_microtask_queue(i_isolate,
                               static_cast<const i::MicrotaskQueue*>(queue));
}
References v8::Utils::ApiCheck(), v8::internal::Isolate::Current(), v8::internal::Isolate::handle_scope_implementer(), wasm::impl(), and v8::Utils::OpenDirectHandle().
SetPromiseHooks()
void v8::Context::SetPromiseHooks (Local< Function > init_hook, Local< Function > before_hook, Local< Function > after_hook, Local< Function > resolve_hook)
Set or clear hooks to be invoked for promise lifecycle operations.
To clear a hook, set it to an empty v8::Function. Each function will receive the observed promise as the first argument. If a chaining operation is used on a promise, the init will additionally receive the parent promise as the second argument.
Definition at line 7222 of file api.cc.
                                                                {
#ifdef V8_ENABLE_JAVASCRIPT_PROMISE_HOOKS
  auto context = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  auto undefined = i_isolate->factory()->undefined_value();
  i::DirectHandle<i::Object> init = undefined;
  i::DirectHandle<i::Object> before = undefined;
  i::DirectHandle<i::Object> after = undefined;
  i::DirectHandle<i::Object> resolve = undefined;
  bool has_hook = false;
  if (!init_hook.IsEmpty()) {
    init = Utils::OpenDirectHandle(*init_hook);
    has_hook = true;
  }
  if (!before_hook.IsEmpty()) {
    before = Utils::OpenDirectHandle(*before_hook);
    has_hook = true;
  }
  if (!after_hook.IsEmpty()) {
    after = Utils::OpenDirectHandle(*after_hook);
    has_hook = true;
  }
  if (!resolve_hook.IsEmpty()) {
    resolve = Utils::OpenDirectHandle(*resolve_hook);
    has_hook = true;
  }
  i_isolate->SetHasContextPromiseHooks(has_hook);
  context->native_context()->set_promise_hook_init_function(*init);
  context->native_context()->set_promise_hook_before_function(*before);
  context->native_context()->set_promise_hook_after_function(*after);
  context->native_context()->set_promise_hook_resolve_function(*resolve);
#else // V8_ENABLE_JAVASCRIPT_PROMISE_HOOKS
  Utils::ApiCheck(false, "v8::Context::SetPromiseHook",
                  "V8 was compiled without JavaScript Promise hooks");
#endif // V8_ENABLE_JAVASCRIPT_PROMISE_HOOKS
}
References v8::Utils::ApiCheck(), v8::internal::Isolate::Current(), v8::internal::Isolate::factory(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8::internal::Isolate::native_context(), v8::Utils::OpenDirectHandle(), and v8::internal::undefined.
Referenced by v8::Shell::SetPromiseHooks().
SetSecurityToken()
void v8::Context::SetSecurityToken (Local< Value > token)
Sets the security token for the context.
To access an object in another context, the security tokens must match.
Definition at line 6796 of file api.cc.
                                                   {
  auto env = Utils::OpenDirectHandle(this);
  auto token_handle = Utils::OpenDirectHandle(*token);
  env->set_security_token(*token_handle);
}
References v8::Utils::OpenDirectHandle().
Referenced by v8::Shell::HostCreateShadowRealmContext(), and v8::Shell::RealmCreateAllowCrossRealmAccess().
SlowGetAlignedPointerFromEmbedderData()
void * v8::Context::SlowGetAlignedPointerFromEmbedderData (int index) [private]
Definition at line 940 of file api.cc.
                                                              {
  const char* location = "v8::Context::GetAlignedPointerFromEmbedderData()";
  i::Isolate* i_isolate = i::Isolate::Current();
  i::HandleScope handle_scope(i_isolate);
  i::DirectHandle<i::EmbedderDataArray> data =
      EmbedderDataFor(this, index, false, location);
  if (data.is_null()) return nullptr;
  void* result;
  Utils::ApiCheck(
      i::EmbedderDataSlot(*data, index).ToAlignedPointer(i_isolate, &result),
      location, "Pointer is not aligned");
  return result;
}
References v8::Utils::ApiCheck(), v8::internal::Isolate::Current(), v8::EmbedderDataFor(), v8::internal::index, v8::internal::DirectHandle< T >::is_null(), and v8::base::internal::result.
Referenced by GetAlignedPointerFromEmbedderData().
SlowGetEmbedderData()
v8::Local< v8::Value > v8::Context::SlowGetEmbedderData (int index) [private]
Definition at line 919 of file api.cc.
                                                       {
  const char* location = "v8::Context::GetEmbedderData()";
  i::DirectHandle<i::EmbedderDataArray> data =
      EmbedderDataFor(this, index, false, location);
  if (data.is_null()) return {};
  i::Isolate* i_isolate = i::Isolate::Current();
  return Utils::ToLocal(i::direct_handle(
      i::EmbedderDataSlot(*data, index).load_tagged(), i_isolate));
}
References v8::internal::Isolate::Current(), v8::internal::direct_handle(), v8::EmbedderDataFor(), v8::internal::index, and v8::internal::DirectHandle< T >::is_null().
Referenced by GetEmbedderData().
UseDefaultSecurityToken()
void v8::Context::UseDefaultSecurityToken ()
Restores the security token to the default value.
Definition at line 6802 of file api.cc.
                                        {
  auto env = Utils::OpenDirectHandle(this);
  env->set_security_token(env->global_object());
}
References v8::Utils::OpenDirectHandle().
Friends And Related Function Documentation
Function
friend class Function [friend]
Definition at line 429 of file v8-context.h.
Object
friend class Object [friend]
Definition at line 428 of file v8-context.h.
Script
friend class Script [friend]
Definition at line 427 of file v8-context.h.
Value
friend class Value [friend]
Definition at line 426 of file v8-context.h.
Member Data Documentation
https
Use which is guaranteed to return the same isolate since v8::Context::https
Definition at line 261 of file v8-context.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-context.h
/mnt/V8SourceCode/src/api/api.cc