v8::internal::compiler::CodeGenerator::MoveType Class Reference
Public Types
enum Type {
kRegisterToRegister
, kRegisterToStack
, kStackToRegister
, kStackToStack
,
kConstantToRegister
, kConstantToStack
 }
Static Public Member Functions
static Type InferMove (InstructionOperand *source, InstructionOperand *destination)
static Type InferSwap (InstructionOperand *source, InstructionOperand *destination)
Detailed Description
Definition at line 297 of file code-generator.h.
Member Enumeration Documentation
Type
enum v8::internal::compiler::CodeGenerator::MoveType::Type
Enumerator
kRegisterToRegister
kRegisterToStack
kStackToRegister
kStackToStack
kConstantToRegister
kConstantToStack
Definition at line 299 of file code-generator.h.
              {
      kRegisterToRegister,
      kRegisterToStack,
      kStackToRegister,
      kStackToStack,
      kConstantToRegister,
      kConstantToStack
    };
Member Function Documentation
InferMove()
CodeGenerator::MoveType::Type v8::internal::compiler::CodeGenerator::MoveType::InferMove (InstructionOperand * source, InstructionOperand * destination) [static]
Definition at line 697 of file code-generator.cc.
                                                                 {
  if (source->IsConstant()) {
    if (destination->IsAnyRegister()) {
      return MoveType::kConstantToRegister;
    } else {
      DCHECK(destination->IsAnyStackSlot());
      return MoveType::kConstantToStack;
    }
  }
  DCHECK(LocationOperand::cast(source)->IsCompatible(
      LocationOperand::cast(destination)));
  if (source->IsAnyRegister()) {
    if (destination->IsAnyRegister()) {
      return MoveType::kRegisterToRegister;
    } else {
      DCHECK(destination->IsAnyStackSlot());
      return MoveType::kRegisterToStack;
    }
  } else {
    DCHECK(source->IsAnyStackSlot());
    if (destination->IsAnyRegister()) {
      return MoveType::kStackToRegister;
    } else {
      DCHECK(destination->IsAnyStackSlot());
      return MoveType::kStackToStack;
    }
  }
}
References v8::internal::compiler::LocationOperand::cast(), v8::internal::DCHECK(), v8::internal::compiler::InstructionOperand::IsAnyRegister(), v8::internal::compiler::InstructionOperand::IsAnyStackSlot(), v8::internal::compiler::anonymous_namespace{load-elimination.cc}::IsCompatible(), kConstantToRegister, kConstantToStack, kRegisterToRegister, kRegisterToStack, kStackToRegister, and kStackToStack.
Referenced by v8::internal::compiler::CodeGenerator::AssembleMove(), and v8::internal::compiler::CodeGenerator::SetPendingMove().
InferSwap()
CodeGenerator::MoveType::Type v8::internal::compiler::CodeGenerator::MoveType::InferSwap (InstructionOperand * source, InstructionOperand * destination) [static]
Definition at line 727 of file code-generator.cc.
                                                                 {
  DCHECK(LocationOperand::cast(source)->IsCompatible(
      LocationOperand::cast(destination)));
  if (source->IsAnyRegister()) {
    if (destination->IsAnyRegister()) {
      return MoveType::kRegisterToRegister;
    } else {
      DCHECK(destination->IsAnyStackSlot());
      return MoveType::kRegisterToStack;
    }
  } else {
    DCHECK(source->IsAnyStackSlot());
    DCHECK(destination->IsAnyStackSlot());
    return MoveType::kStackToStack;
  }
}
References v8::internal::compiler::LocationOperand::cast(), v8::internal::DCHECK(), v8::internal::compiler::InstructionOperand::IsAnyRegister(), v8::internal::compiler::InstructionOperand::IsAnyStackSlot(), v8::internal::compiler::anonymous_namespace{load-elimination.cc}::IsCompatible(), kRegisterToRegister, kRegisterToStack, and kStackToStack.
Referenced by v8::internal::compiler::CodeGenerator::AssembleSwap().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/code-generator.h
/mnt/V8SourceCode/src/compiler/backend/code-generator.cc