v8::internal::NormalizedMapCache Class Reference
#include <map.h>
Public Member Functions
V8_WARN_UNUSED_RESULT MaybeHandle< Map > Get (Isolate *isolate, DirectHandle< Map > fast_map, ElementsKind elements_kind, Tagged< HeapObject > prototype, PropertyNormalizationMode mode)
void Set (Isolate *isolate, DirectHandle< Map > fast_map, DirectHandle< Map > normalized_map)
Static Public Member Functions
static DirectHandle< NormalizedMapCache > New (Isolate *isolate)
Private Member Functions
Tagged< Object > get (int index)
void set (int index, Tagged< Object > value)
Static Private Member Functions
static int GetIndex (Isolate *isolate, Tagged< Map > map, Tagged< HeapObject > prototype)
Static Private Attributes
static const int kEntries = 64
Friends
bool IsNormalizedMapCache (Tagged< HeapObject > obj, PtrComprCageBase cage_base)
Additional Inherited Members
Detailed Description
Definition at line 1098 of file map.h.
Member Function Documentation
get()
Tagged<Object> v8::internal::NormalizedMapCache::get (int index) [private]
Get()
MaybeHandle< Map > v8::internal::NormalizedMapCache::Get (Isolate * isolate, DirectHandle< Map > fast_map, ElementsKind elements_kind, Tagged< HeapObject > prototype, PropertyNormalizationMode mode)
Definition at line 2549 of file map.cc.
                                                                         {
  DisallowGarbageCollection no_gc;
  Tagged<MaybeObject> value =
      WeakFixedArray::get(GetIndex(isolate, *fast_map, *prototype));
  Tagged<HeapObject> heap_object;
  if (!value.GetHeapObjectIfWeak(&heap_object)) {
    return MaybeHandle<Map>();
  }
  Tagged<Map> normalized_map = Cast<Map>(heap_object);
  CHECK(normalized_map->is_dictionary_map());
  if (!normalized_map->EquivalentToForNormalization(*fast_map, elements_kind,
                                                    prototype, mode)) {
    return MaybeHandle<Map>();
  }
  return handle(normalized_map, isolate);
}
References CHECK, v8::internal::TaggedArrayBase< WeakFixedArray, WeakFixedArrayShape >::get(), GetIndex(), v8::internal::handle(), mode(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::prototype, and v8::internal::value.
GetIndex()
int v8::internal::NormalizedMapCache::GetIndex (Isolate * isolate, Tagged< Map > map, Tagged< HeapObject > prototype) [inline], [static], [private]
Definition at line 1063 of file map-inl.h.
                                                               {
  DisallowGarbageCollection no_gc;
  return map->Hash(isolate, prototype) % NormalizedMapCache::kEntries;
}
References kEntries, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::prototype.
Referenced by Get(), and Set().
New()
DirectHandle< NormalizedMapCache > v8::internal::NormalizedMapCache::New (Isolate * isolate) [static]
Definition at line 2543 of file map.cc.
                                                                         {
  DirectHandle<WeakFixedArray> array(
      isolate->factory()->NewWeakFixedArray(kEntries, AllocationType::kOld));
  return Cast<NormalizedMapCache>(array);
}
References v8::internal::Isolate::factory(), kEntries, v8::internal::kOld, and v8::internal::FactoryBase< Impl >::NewWeakFixedArray().
Referenced by v8::internal::Genesis::InitializeMapCaches().
set()
void v8::internal::NormalizedMapCache::set (int index, Tagged< Object > value) [private]
Set()
void v8::internal::NormalizedMapCache::Set (Isolate * isolate, DirectHandle< Map > fast_map, DirectHandle< Map > normalized_map)
Definition at line 2571 of file map.cc.
                                                               {
  DisallowGarbageCollection no_gc;
  DCHECK(normalized_map->is_dictionary_map());
  WeakFixedArray::set(GetIndex(isolate, *fast_map, normalized_map->prototype()),
                      MakeWeak(*normalized_map));
}
References v8::internal::DCHECK(), GetIndex(), v8::internal::MakeWeak(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::TaggedArrayBase< WeakFixedArray, WeakFixedArrayShape >::set().
Friends And Related Function Documentation
IsNormalizedMapCache
bool IsNormalizedMapCache (Tagged< HeapObject > obj, PtrComprCageBase cage_base) [friend]
Member Data Documentation
kEntries
const int v8::internal::NormalizedMapCache::kEntries = 64 [static], [private]
Definition at line 1116 of file map.h.
Referenced by v8::internal::DEF_HEAP_OBJECT_PREDICATE(), GetIndex(), and New().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/map.h
/mnt/V8SourceCode/src/objects/map-inl.h
/mnt/V8SourceCode/src/objects/map.cc