v8::internal::compiler::WasmGCOperatorReducer Class Reference
#include <wasm-gc-operator-reducer.h>
Public Member Functions
WasmGCOperatorReducer (Editor *editor, Zone *temp_zone_, MachineGraph *mcgraph, const wasm::WasmModule *module, SourcePositionTable *source_position_table)
const char * reducer_name () const override
Reduction Reduce (Node *node) final
Private Types
using ControlPathTypes = ControlPathState< NodeWithType, kMultipleInstances >
Private Member Functions
Reduction ReduceWasmStructOperation (Node *node)
Reduction ReduceWasmArrayLength (Node *node)
Reduction ReduceAssertNotNull (Node *node)
Reduction ReduceCheckNull (Node *node)
Reduction ReduceWasmTypeCheck (Node *node)
Reduction ReduceWasmTypeCheckAbstract (Node *node)
Reduction ReduceWasmTypeCast (Node *node)
Reduction ReduceWasmTypeCastAbstract (Node *node)
Reduction ReduceTypeGuard (Node *node)
Reduction ReduceWasmAnyConvertExtern (Node *node)
Reduction ReduceMerge (Node *node)
Reduction ReduceIf (Node *node, bool condition)
Reduction ReduceStart (Node *node)
Node * SetType (Node *node, wasm::ValueType type)
void UpdateSourcePosition (Node *new_node, Node *old_node)
wasm::TypeInModule ObjectTypeFromContext (Node *object, Node *control, bool allow_non_wasm=false)
Reduction UpdateNodeAndAliasesTypes (Node *state_owner, ControlPathTypes parent_state, Node *node, wasm::TypeInModule type, bool in_new_block)
TFGraph * graph ()
CommonOperatorBuilder * common ()
SimplifiedOperatorBuilder * simplified ()
Private Attributes
MachineGraph * mcgraph_
WasmGraphAssembler gasm_
const wasm::WasmModule * module_
SourcePositionTable * source_position_table_
Additional Inherited Members
Detailed Description
Definition at line 44 of file wasm-gc-operator-reducer.h.
Member Typedef Documentation
ControlPathTypes
using v8::internal::compiler::WasmGCOperatorReducer::ControlPathTypes = ControlPathState<NodeWithType, kMultipleInstances> [private]
Definition at line 57 of file wasm-gc-operator-reducer.h.
Constructor & Destructor Documentation
WasmGCOperatorReducer()
v8::internal::compiler::WasmGCOperatorReducer::WasmGCOperatorReducer (Editor * editor, Zone * temp_zone_, MachineGraph * mcgraph, const wasm::WasmModule * module, SourcePositionTable * source_position_table)
Definition at line 17 of file wasm-gc-operator-reducer.cc.
    : AdvancedReducerWithControlPathState(editor, temp_zone_, mcgraph->graph()),
      mcgraph_(mcgraph),
      gasm_(mcgraph, mcgraph->zone()),
      module_(module),
      source_position_table_(source_position_table) {}
Member Function Documentation
common()
CommonOperatorBuilder* v8::internal::compiler::WasmGCOperatorReducer::common () [inline], [private]
Definition at line 87 of file wasm-gc-operator-reducer.h.
{ return mcgraph_->common(); }
References v8::internal::compiler::MachineGraph::common(), and mcgraph_.
Referenced by ReduceAssertNotNull(), ReduceWasmTypeCast(), and ReduceWasmTypeCastAbstract().
graph()
TFGraph* v8::internal::compiler::WasmGCOperatorReducer::graph () [inline], [private]
Definition at line 86 of file wasm-gc-operator-reducer.h.
{ return mcgraph_->graph(); }
References v8::internal::compiler::MachineGraph::graph(), and mcgraph_.
Referenced by SetType().
ObjectTypeFromContext()
wasm::TypeInModule v8::internal::compiler::WasmGCOperatorReducer::ObjectTypeFromContext (Node * object, Node * control, bool allow_non_wasm = false) [private]
Definition at line 128 of file wasm-gc-operator-reducer.cc.
                                                      {
  if (object->opcode() == IrOpcode::kDead ||
      object->opcode() == IrOpcode::kDeadValue) {
    return {};
  }
  if (!IsReduced(control)) return {};
  if (allow_non_wasm && !NodeProperties::IsTyped(object)) return {};
  Type raw_type = NodeProperties::GetType(object);
  if (allow_non_wasm && !raw_type.IsWasm()) return {};
  wasm::TypeInModule type_from_node = raw_type.AsWasm();
  ControlPathTypes state = GetState(control);
  NodeWithType type_from_state = state.LookupState(object);
  // We manually resolve TypeGuard aliases in the state.
  while (object->opcode() == IrOpcode::kTypeGuard && !type_from_state.IsSet()) {
    object = NodeProperties::GetValueInput(object, 0);
    type_from_state = state.LookupState(object);
  }
  if (!type_from_state.IsSet()) return type_from_node;
  return compiler::Intersection(type_from_node, type_from_state.type);
}
References v8::internal::compiler::AdvancedReducerWithControlPathState< NodeWithType, kMultipleInstances >::GetState(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::anonymous_namespace{wasm-gc-operator-reducer.cc}::Intersection(), v8::internal::compiler::AdvancedReducerWithControlPathState< NodeWithType, kMultipleInstances >::IsReduced(), v8::internal::compiler::NodeWithType::IsSet(), v8::internal::compiler::NodeProperties::IsTyped(), v8::internal::compiler::ControlPathState< NodeState, node_uniqueness >::LookupState(), v8::internal::compiler::Node::opcode(), and v8::internal::compiler::NodeWithType::type.
Referenced by ReduceAssertNotNull(), ReduceCheckNull(), ReduceIf(), ReduceTypeGuard(), ReduceWasmArrayLength(), ReduceWasmStructOperation(), ReduceWasmTypeCast(), ReduceWasmTypeCastAbstract(), ReduceWasmTypeCheck(), and ReduceWasmTypeCheckAbstract().
Reduce()
Reduction v8::internal::compiler::WasmGCOperatorReducer::Reduce (Node * node) [final], [virtual]
Implements v8::internal::compiler::Reducer.
Definition at line 26 of file wasm-gc-operator-reducer.cc.
                                                  {
  switch (node->opcode()) {
    case IrOpcode::kStart:
      return ReduceStart(node);
    case IrOpcode::kWasmStructGet:
    case IrOpcode::kWasmStructSet:
      return ReduceWasmStructOperation(node);
    case IrOpcode::kWasmArrayLength:
      return ReduceWasmArrayLength(node);
    case IrOpcode::kAssertNotNull:
      return ReduceAssertNotNull(node);
    case IrOpcode::kIsNull:
    case IrOpcode::kIsNotNull:
      return ReduceCheckNull(node);
    case IrOpcode::kWasmTypeCheck:
      return ReduceWasmTypeCheck(node);
    case IrOpcode::kWasmTypeCheckAbstract:
      return ReduceWasmTypeCheckAbstract(node);
    case IrOpcode::kWasmTypeCast:
      return ReduceWasmTypeCast(node);
    case IrOpcode::kWasmTypeCastAbstract:
      return ReduceWasmTypeCastAbstract(node);
    case IrOpcode::kTypeGuard:
      return ReduceTypeGuard(node);
    case IrOpcode::kWasmAnyConvertExtern:
      return ReduceWasmAnyConvertExtern(node);
    case IrOpcode::kMerge:
      return ReduceMerge(node);
    case IrOpcode::kIfTrue:
      return ReduceIf(node, true);
    case IrOpcode::kIfFalse:
      return ReduceIf(node, false);
    case IrOpcode::kDead:
      return NoChange();
    case IrOpcode::kLoop:
      return TakeStatesFromFirstControl(node);
    default:
      if (node->op()->ControlOutputCount() > 0) {
        DCHECK_EQ(1, node->op()->ControlInputCount());
        return TakeStatesFromFirstControl(node);
      } else {
        return NoChange();
      }
  }
}
References v8::internal::compiler::Operator::ControlInputCount(), v8::internal::compiler::Operator::ControlOutputCount(), DCHECK_EQ, v8::kStart, v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), ReduceAssertNotNull(), ReduceCheckNull(), ReduceIf(), ReduceMerge(), ReduceStart(), ReduceTypeGuard(), ReduceWasmAnyConvertExtern(), ReduceWasmArrayLength(), ReduceWasmStructOperation(), ReduceWasmTypeCast(), ReduceWasmTypeCastAbstract(), ReduceWasmTypeCheck(), ReduceWasmTypeCheckAbstract(), and v8::internal::compiler::AdvancedReducerWithControlPathState< NodeWithType, kMultipleInstances >::TakeStatesFromFirstControl().
ReduceAssertNotNull()
Reduction v8::internal::compiler::WasmGCOperatorReducer::ReduceAssertNotNull (Node * node) [private]
Definition at line 277 of file wasm-gc-operator-reducer.cc.
                                                               {
  DCHECK_EQ(node->opcode(), IrOpcode::kAssertNotNull);
  Node* object = NodeProperties::GetValueInput(node, 0);
  Node* control = NodeProperties::GetControlInput(node);
  wasm::TypeInModule object_type = ObjectTypeFromContext(object, control);
  if (object_type.type.is_uninhabited()) return NoChange();
  // Optimize the check away if the argument is known to be non-null.
  if (object_type.type.is_non_nullable()) {
    // First, relax control.
    ReplaceWithValue(node, node, node, control);
    // Use a TypeGuard node to not lose any type information.
    NodeProperties::ChangeOp(
        node, common()->TypeGuard(NodeProperties::GetType(node)));
    return Changed(node);
  }
  object_type.type = object_type.type.AsNonNull();
  return UpdateNodeAndAliasesTypes(node, GetState(control), node, object_type,
                                   false);
}
References v8::internal::wasm::ValueType::AsNonNull(), v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), common(), DCHECK_EQ, v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::AdvancedReducerWithControlPathState< NodeWithType, kMultipleInstances >::GetState(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::wasm::ValueTypeBase::is_non_nullable(), v8::internal::wasm::ValueTypeBase::is_uninhabited(), v8::internal::compiler::Reducer::NoChange(), ObjectTypeFromContext(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), v8::internal::wasm::TypeInModule::type, and UpdateNodeAndAliasesTypes().
Referenced by Reduce().
ReduceCheckNull()
Reduction v8::internal::compiler::WasmGCOperatorReducer::ReduceCheckNull (Node * node) [private]
Definition at line 300 of file wasm-gc-operator-reducer.cc.
                                                           {
  DCHECK(node->opcode() == IrOpcode::kIsNull ||
         node->opcode() == IrOpcode::kIsNotNull);
  Node* object = NodeProperties::GetValueInput(node, 0);
  Node* control = NodeProperties::GetControlInput(node);
  wasm::TypeInModule object_type = ObjectTypeFromContext(object, control);
  if (object_type.type.is_uninhabited()) return NoChange();
  // Optimize the check away if the argument is known to be non-null.
  if (object_type.type.is_non_nullable()) {
    ReplaceWithValue(node,
                     SetType(gasm_.Int32Constant(
                                 node->opcode() == IrOpcode::kIsNull ? 0 : 1),
                             wasm::kWasmI32));
    node->Kill();
    return Replace(object); // Irrelevant replacement.
  }
  // Optimize the check away if the argument is known to be null.
  if (object->opcode() == IrOpcode::kNull) {
    ReplaceWithValue(node,
                     SetType(gasm_.Int32Constant(
                                 node->opcode() == IrOpcode::kIsNull ? 1 : 0),
                             wasm::kWasmI32));
    node->Kill();
    return Replace(object); // Irrelevant replacement.
  }
  return NoChange();
}
References v8::internal::DCHECK(), gasm_, v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::GraphAssembler::Int32Constant(), v8::internal::wasm::ValueTypeBase::is_non_nullable(), v8::internal::wasm::ValueTypeBase::is_uninhabited(), v8::internal::compiler::Node::Kill(), v8::internal::wasm::kWasmI32, v8::internal::compiler::Reducer::NoChange(), ObjectTypeFromContext(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), SetType(), and v8::internal::wasm::TypeInModule::type.
Referenced by Reduce().
ReduceIf()
Reduction v8::internal::compiler::WasmGCOperatorReducer::ReduceIf (Node * node, bool condition) [private]
Definition at line 205 of file wasm-gc-operator-reducer.cc.
                                                                    {
  DCHECK(node->opcode() == IrOpcode::kIfTrue ||
         node->opcode() == IrOpcode::kIfFalse);
  Node* branch = NodeProperties::GetControlInput(node);
  if (branch->opcode() == IrOpcode::kDead) return NoChange();
  DCHECK_EQ(branch->opcode(), IrOpcode::kBranch);
  if (!IsReduced(branch)) return NoChange();
  ControlPathTypes parent_state = GetState(branch);
  Node* condition_node = NodeProperties::GetValueInput(branch, 0);
  switch (condition_node->opcode()) {
    case IrOpcode::kWasmTypeCheck:
    case IrOpcode::kWasmTypeCheckAbstract: {
      if (!condition) break;
      Node* object = NodeProperties::GetValueInput(condition_node, 0);
      wasm::TypeInModule object_type = ObjectTypeFromContext(object, branch);
      if (object_type.type.is_uninhabited()) return NoChange();
      wasm::ValueType to_type =
          OpParameter<WasmTypeCheckConfig>(condition_node->op()).to;
      wasm::TypeInModule new_type =
          wasm::Intersection(object_type.type, to_type, module_);
      return UpdateNodeAndAliasesTypes(node, parent_state, object, new_type,
                                       true);
    }
    case IrOpcode::kIsNull:
    case IrOpcode::kIsNotNull: {
      Node* object = NodeProperties::GetValueInput(condition_node, 0);
      Node* control = NodeProperties::GetControlInput(condition_node);
      wasm::TypeInModule object_type = ObjectTypeFromContext(object, control);
      if (object_type.type.is_uninhabited()) return NoChange();
      // If the checked value is null, narrow the type to the corresponding
      // null type, otherwise to a non-null reference.
      bool is_null =
          condition == (condition_node->opcode() == IrOpcode::kIsNull);
      object_type.type = is_null ? wasm::ToNullSentinel(object_type)
                                 : object_type.type.AsNonNull();
      return UpdateNodeAndAliasesTypes(node, parent_state, object, object_type,
                                       true);
    }
    default:
      break;
  }
  return TakeStatesFromFirstControl(node);
}
References v8::internal::wasm::ValueType::AsNonNull(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::AdvancedReducerWithControlPathState< NodeWithType, kMultipleInstances >::GetState(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::wasm::Intersection(), v8::internal::wasm::ValueTypeBase::is_uninhabited(), v8::internal::compiler::AdvancedReducerWithControlPathState< NodeWithType, kMultipleInstances >::IsReduced(), v8::internal::compiler::turboshaft::kBranch, module_, v8::internal::compiler::Reducer::NoChange(), ObjectTypeFromContext(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::AdvancedReducerWithControlPathState< NodeWithType, kMultipleInstances >::TakeStatesFromFirstControl(), v8::internal::wasm::ToNullSentinel(), v8::internal::wasm::TypeInModule::type, and UpdateNodeAndAliasesTypes().
Referenced by Reduce().
ReduceMerge()
Reduction v8::internal::compiler::WasmGCOperatorReducer::ReduceMerge (Node * node) [private]
Definition at line 251 of file wasm-gc-operator-reducer.cc.
                                                       {
  // Shortcut for the case when we do not know anything about some
  // input.
  Node::Inputs inputs = node->inputs();
  for (Node* input : inputs) {
    if (!IsReduced(input)) return NoChange();
  }
  auto input_it = inputs.begin();
  DCHECK_GT(inputs.count(), 0);
  ControlPathTypes types = GetState(*input_it);
  ++input_it;
  auto input_end = inputs.end();
  for (; input_it != input_end; ++input_it) {
    // Change the current type block list to a longest common prefix of this
    // state list and the other list. (The common prefix should correspond to
    // the state of the common dominator.)
    // TODO(manoskouk): Consider computing unions for some types.
    types.ResetToCommonAncestor(GetState(*input_it));
  }
  return UpdateStates(node, types);
}
References DCHECK_GT, v8::internal::compiler::AdvancedReducerWithControlPathState< NodeWithType, kMultipleInstances >::GetState(), v8::internal::compiler::Node::inputs(), v8::internal::compiler::Node::Inputs(), v8::internal::compiler::AdvancedReducerWithControlPathState< NodeWithType, kMultipleInstances >::IsReduced(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::ControlPathState< NodeState, node_uniqueness >::ResetToCommonAncestor(), and v8::internal::compiler::AdvancedReducerWithControlPathState< NodeWithType, kMultipleInstances >::UpdateStates().
Referenced by Reduce().
reducer_name()
const char* v8::internal::compiler::WasmGCOperatorReducer::reducer_name () const [inline], [override], [virtual]
Implements v8::internal::compiler::Reducer.
Definition at line 52 of file wasm-gc-operator-reducer.h.
{ return "WasmGCOperatorReducer"; }
ReduceStart()
Reduction v8::internal::compiler::WasmGCOperatorReducer::ReduceStart (Node * node) [private]
Definition at line 124 of file wasm-gc-operator-reducer.cc.
                                                       {
  return UpdateStates(node, ControlPathTypes(zone()));
}
References v8::internal::compiler::AdvancedReducerWithControlPathState< NodeWithType, kMultipleInstances >::UpdateStates(), and v8::internal::compiler::AdvancedReducerWithControlPathState< NodeWithType, kMultipleInstances >::zone().
Referenced by Reduce().
ReduceTypeGuard()
Reduction v8::internal::compiler::WasmGCOperatorReducer::ReduceTypeGuard (Node * node) [private]
Definition at line 353 of file wasm-gc-operator-reducer.cc.
                                                           {
  DCHECK_EQ(node->opcode(), IrOpcode::kTypeGuard);
  Node* control = NodeProperties::GetControlInput(node);
  Node* object = NodeProperties::GetValueInput(node, 0);
  // Since TypeGuards can be generated for JavaScript, and this phase is run
  // for wasm-into-JS inlining, we cannot assume the object has a wasm type.
  wasm::TypeInModule object_type =
      ObjectTypeFromContext(object, control, /* allow_non_wasm = */ true);
  if (object_type.type.is_uninhabited()) return NoChange();
  Type guarded_type = TypeGuardTypeOf(node->op());
  if (!guarded_type.IsWasm()) return NoChange();
  wasm::TypeInModule new_type =
      compiler::Intersection(object_type, guarded_type.AsWasm());
  return UpdateNodeAndAliasesTypes(node, GetState(control), node, new_type,
                                   false);
}
References DCHECK_EQ, v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::AdvancedReducerWithControlPathState< NodeWithType, kMultipleInstances >::GetState(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::anonymous_namespace{wasm-gc-operator-reducer.cc}::Intersection(), v8::internal::wasm::ValueTypeBase::is_uninhabited(), v8::internal::compiler::Reducer::NoChange(), ObjectTypeFromContext(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::wasm::TypeInModule::type, v8::internal::compiler::TypeGuardTypeOf(), and UpdateNodeAndAliasesTypes().
Referenced by Reduce().
ReduceWasmAnyConvertExtern()
Reduction v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmAnyConvertExtern (Node * node) [private]
Definition at line 332 of file wasm-gc-operator-reducer.cc.
                                                                      {
  DCHECK_EQ(node->opcode(), IrOpcode::kWasmAnyConvertExtern);
  // Remove redundant any.convert_extern(extern.convert_any(...)) pattern.
  Node* input = NodeProperties::GetValueInput(node, 0);
  while (input->opcode() == IrOpcode::kTypeGuard) {
    input = NodeProperties::GetValueInput(input, 0);
  }
  if (input->opcode() == IrOpcode::kDead ||
      input->opcode() == IrOpcode::kDeadValue) {
    return NoChange();
  }
  if (input->opcode() == IrOpcode::kWasmExternConvertAny) {
    // "Skip" the extern.convert_any which doesn't have an effect on the value.
    input = NodeProperties::GetValueInput(input, 0);
    ReplaceWithValue(node, input);
    node->Kill();
    return Replace(input);
  }
  return TakeStatesFromFirstControl(node);
}
References DCHECK_EQ, v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::Node::Kill(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), and v8::internal::compiler::AdvancedReducerWithControlPathState< NodeWithType, kMultipleInstances >::TakeStatesFromFirstControl().
Referenced by Reduce().
ReduceWasmArrayLength()
Reduction v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmArrayLength (Node * node) [private]
Definition at line 180 of file wasm-gc-operator-reducer.cc.
                                                                 {
  DCHECK_EQ(node->opcode(), IrOpcode::kWasmArrayLength);
  Node* control = NodeProperties::GetControlInput(node);
  if (!IsReduced(control)) return NoChange();
  Node* object = NodeProperties::GetValueInput(node, 0);
  wasm::TypeInModule object_type = ObjectTypeFromContext(object, control);
  if (object_type.type.is_uninhabited()) return NoChange();
  if (object_type.type.is_non_nullable()) {
    // If the object is known to be non-nullable in the context, remove the null
    // check.
    const Operator* new_op = simplified()->WasmArrayLength(kWithoutNullCheck);
    NodeProperties::ChangeOp(node, new_op);
  }
  object_type.type = object_type.type.AsNonNull();
  return UpdateNodeAndAliasesTypes(node, GetState(control), object, object_type,
                                   false);
}
References v8::internal::wasm::ValueType::AsNonNull(), v8::internal::compiler::NodeProperties::ChangeOp(), DCHECK_EQ, v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::AdvancedReducerWithControlPathState< NodeWithType, kMultipleInstances >::GetState(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::wasm::ValueTypeBase::is_non_nullable(), v8::internal::wasm::ValueTypeBase::is_uninhabited(), v8::internal::compiler::AdvancedReducerWithControlPathState< NodeWithType, kMultipleInstances >::IsReduced(), v8::internal::compiler::kWithoutNullCheck, v8::internal::compiler::Reducer::NoChange(), ObjectTypeFromContext(), v8::internal::compiler::Node::opcode(), simplified(), v8::internal::wasm::TypeInModule::type, and UpdateNodeAndAliasesTypes().
Referenced by Reduce().
ReduceWasmStructOperation()
Reduction v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmStructOperation (Node * node) [private]
Definition at line 150 of file wasm-gc-operator-reducer.cc.
                                                                     {
  DCHECK(node->opcode() == IrOpcode::kWasmStructGet ||
         node->opcode() == IrOpcode::kWasmStructSet);
  Node* control = NodeProperties::GetControlInput(node);
  if (!IsReduced(control)) return NoChange();
  Node* object = NodeProperties::GetValueInput(node, 0);
  wasm::TypeInModule object_type = ObjectTypeFromContext(object, control);
  if (object_type.type.is_uninhabited()) return NoChange();
  if (object_type.type.is_non_nullable()) {
    // If the object is known to be non-nullable in the context, remove the null
    // check.
    auto op_params = OpParameter<WasmFieldInfo>(node->op());
    const Operator* new_op =
        node->opcode() == IrOpcode::kWasmStructGet
            ? simplified()->WasmStructGet(op_params.type, op_params.field_index,
                                          op_params.is_signed,
                                          kWithoutNullCheck)
            : simplified()->WasmStructSet(op_params.type, op_params.field_index,
                                          kWithoutNullCheck);
    NodeProperties::ChangeOp(node, new_op);
  }
  object_type.type = object_type.type.AsNonNull();
  return UpdateNodeAndAliasesTypes(node, GetState(control), object, object_type,
                                   false);
}
References v8::internal::wasm::ValueType::AsNonNull(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::DCHECK(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::AdvancedReducerWithControlPathState< NodeWithType, kMultipleInstances >::GetState(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::wasm::ValueTypeBase::is_non_nullable(), v8::internal::wasm::ValueTypeBase::is_uninhabited(), v8::internal::compiler::AdvancedReducerWithControlPathState< NodeWithType, kMultipleInstances >::IsReduced(), v8::internal::compiler::kWithoutNullCheck, v8::internal::compiler::Reducer::NoChange(), ObjectTypeFromContext(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), simplified(), v8::internal::wasm::TypeInModule::type, and UpdateNodeAndAliasesTypes().
Referenced by Reduce().
ReduceWasmTypeCast()
Reduction v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCast (Node * node) [private]
Definition at line 373 of file wasm-gc-operator-reducer.cc.
                                                              {
  DCHECK_EQ(node->opcode(), IrOpcode::kWasmTypeCast);
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  Node* object = NodeProperties::GetValueInput(node, 0);
  Node* rtt = NodeProperties::GetValueInput(node, 1);
  wasm::TypeInModule object_type = ObjectTypeFromContext(object, control);
  if (object_type.type.is_uninhabited()) return NoChange();
  if (InDeadBranch(rtt)) return NoChange();
  wasm::TypeInModule rtt_type = NodeProperties::GetType(rtt).AsWasm();
  DCHECK_EQ(object_type.module, rtt_type.module);
  bool to_nullable =
      OpParameter<WasmTypeCheckConfig>(node->op()).to.is_nullable();
  if (wasm::IsHeapSubtypeOf(object_type.type.heap_type(),
                            rtt_type.type.heap_type(), object_type.module)) {
    if (to_nullable) {
      // Type cast will always succeed. Turn it into a TypeGuard to not lose any
      // type information.
      // First, relax control.
      ReplaceWithValue(node, node, node, control);
      // Remove rtt input.
      node->RemoveInput(1);
      NodeProperties::ChangeOp(
          node, common()->TypeGuard(NodeProperties::GetType(node)));
      return Changed(node);
    } else {
      gasm_.InitializeEffectControl(effect, control);
      Node* assert_not_null = gasm_.AssertNotNull(object, object_type.type,
                                                  TrapId::kTrapIllegalCast);
      UpdateSourcePosition(assert_not_null, node);
      return Replace(SetType(assert_not_null, object_type.type.AsNonNull()));
    }
  }
  if (wasm::HeapTypesUnrelated(object_type.type.heap_type(),
                               rtt_type.type.heap_type(), object_type.module)) {
    gasm_.InitializeEffectControl(effect, control);
    // A cast between unrelated types can only succeed if the argument is null.
    // Otherwise, it always fails.
    Node* non_trapping_condition = object_type.type.is_nullable() && to_nullable
                                       ? gasm_.IsNull(object, object_type.type)
                                       : gasm_.Int32Constant(0);
    gasm_.TrapUnless(SetType(non_trapping_condition, wasm::kWasmI32),
                     TrapId::kTrapIllegalCast);
    UpdateSourcePosition(gasm_.effect(), node);
    Node* null_node = SetType(gasm_.Null(object_type.type),
                              wasm::ToNullSentinel(object_type));
    ReplaceWithValue(node, null_node, gasm_.effect(), gasm_.control());
    node->Kill();
    return Replace(null_node);
  }
  // Update the from-type in the type cast.
  WasmTypeCheckConfig current_config =
      OpParameter<WasmTypeCheckConfig>(node->op());
  NodeProperties::ChangeOp(node, gasm_.simplified()->WasmTypeCast(
                                     {object_type.type, current_config.to,
                                      current_config.exactness}));
  wasm::TypeInModule new_type =
      wasm::Intersection(object_type.type, rtt_type.type.AsNullable(), module_);
  return UpdateNodeAndAliasesTypes(node, GetState(control), node, new_type,
                                   false);
}
References v8::internal::wasm::ValueType::AsNonNull(), v8::internal::wasm::ValueType::AsNullable(), v8::internal::compiler::WasmGraphAssembler::AssertNotNull(), v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), common(), v8::internal::compiler::GraphAssembler::control(), DCHECK_EQ, v8::internal::compiler::GraphAssembler::effect(), gasm_, v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::AdvancedReducerWithControlPathState< NodeWithType, kMultipleInstances >::GetState(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::wasm::ValueType::heap_type(), v8::internal::wasm::HeapTypesUnrelated(), v8::internal::compiler::anonymous_namespace{wasm-gc-operator-reducer.cc}::InDeadBranch(), v8::internal::compiler::GraphAssembler::InitializeEffectControl(), v8::internal::compiler::GraphAssembler::Int32Constant(), v8::internal::wasm::Intersection(), v8::internal::wasm::ValueTypeBase::is_nullable(), v8::internal::wasm::ValueTypeBase::is_uninhabited(), v8::internal::wasm::IsHeapSubtypeOf(), v8::internal::compiler::WasmGraphAssembler::IsNull(), v8::internal::compiler::Node::Kill(), v8::internal::wasm::kWasmI32, v8::internal::wasm::TypeInModule::module, module_, v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::WasmGraphAssembler::Null(), ObjectTypeFromContext(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::Node::RemoveInput(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), SetType(), v8::internal::compiler::WasmGraphAssembler::simplified(), v8::internal::wasm::ToNullSentinel(), v8::internal::compiler::WasmGraphAssembler::TrapUnless(), v8::internal::wasm::TypeInModule::type, UpdateNodeAndAliasesTypes(), and UpdateSourcePosition().
Referenced by Reduce().
ReduceWasmTypeCastAbstract()
Reduction v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCastAbstract (Node * node) [private]
Definition at line 441 of file wasm-gc-operator-reducer.cc.
                                                                      {
  DCHECK_EQ(node->opcode(), IrOpcode::kWasmTypeCastAbstract);
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  Node* object = NodeProperties::GetValueInput(node, 0);
  WasmTypeCheckConfig config = OpParameter<WasmTypeCheckConfig>(node->op());
  wasm::TypeInModule object_type = ObjectTypeFromContext(object, control);
  if (object_type.type.is_uninhabited()) return NoChange();
  const bool to_nullable = config.to.is_nullable();
  if (wasm::IsHeapSubtypeOf(object_type.type.heap_type(), config.to.heap_type(),
                            object_type.module)) {
    if (to_nullable || object_type.type.is_non_nullable()) {
      // Type cast will always succeed. Turn it into a TypeGuard to not lose any
      // type information.
      // First, relax control.
      ReplaceWithValue(node, node, node, control);
      NodeProperties::ChangeOp(
          node, common()->TypeGuard(NodeProperties::GetType(node)));
      return Changed(node);
    } else {
      gasm_.InitializeEffectControl(effect, control);
      Node* assert_not_null = gasm_.AssertNotNull(object, object_type.type,
                                                  TrapId::kTrapIllegalCast);
      UpdateSourcePosition(assert_not_null, node);
      return Replace(SetType(assert_not_null, object_type.type.AsNonNull()));
    }
  }
  if (wasm::HeapTypesUnrelated(object_type.type.heap_type(),
                               config.to.heap_type(), object_type.module)) {
    gasm_.InitializeEffectControl(effect, control);
    // A cast between unrelated types can only succeed if the argument is null.
    // Otherwise, it always fails.
    Node* non_trapping_condition = object_type.type.is_nullable() && to_nullable
                                       ? gasm_.IsNull(object, object_type.type)
                                       : gasm_.Int32Constant(0);
    gasm_.TrapUnless(SetType(non_trapping_condition, wasm::kWasmI32),
                     TrapId::kTrapIllegalCast);
    UpdateSourcePosition(gasm_.effect(), node);
    Node* null_node = SetType(gasm_.Null(object_type.type),
                              wasm::ToNullSentinel(object_type));
    ReplaceWithValue(node, null_node, gasm_.effect(), gasm_.control());
    node->Kill();
    return Replace(null_node);
  }
  // Update the from-type in the type cast.
  NodeProperties::ChangeOp(
      node, gasm_.simplified()->WasmTypeCastAbstract(
                {object_type.type, config.to, config.exactness}));
  wasm::TypeInModule new_type =
      wasm::Intersection(object_type.type, config.to, module_);
  return UpdateNodeAndAliasesTypes(node, GetState(control), node, new_type,
                                   false);
}
References v8::internal::wasm::ValueType::AsNonNull(), v8::internal::compiler::WasmGraphAssembler::AssertNotNull(), v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), common(), v8::internal::compiler::GraphAssembler::control(), DCHECK_EQ, v8::internal::compiler::GraphAssembler::effect(), gasm_, v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::AdvancedReducerWithControlPathState< NodeWithType, kMultipleInstances >::GetState(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::wasm::ValueType::heap_type(), v8::internal::wasm::HeapTypesUnrelated(), v8::internal::compiler::GraphAssembler::InitializeEffectControl(), v8::internal::compiler::GraphAssembler::Int32Constant(), v8::internal::wasm::Intersection(), v8::internal::wasm::ValueTypeBase::is_non_nullable(), v8::internal::wasm::ValueTypeBase::is_nullable(), v8::internal::wasm::ValueTypeBase::is_uninhabited(), v8::internal::wasm::IsHeapSubtypeOf(), v8::internal::compiler::WasmGraphAssembler::IsNull(), v8::internal::compiler::Node::Kill(), v8::internal::wasm::kWasmI32, v8::internal::wasm::TypeInModule::module, module_, v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::WasmGraphAssembler::Null(), ObjectTypeFromContext(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), SetType(), v8::internal::compiler::WasmGraphAssembler::simplified(), v8::internal::compiler::WasmTypeCheckConfig::to, v8::internal::wasm::ToNullSentinel(), v8::internal::compiler::WasmGraphAssembler::TrapUnless(), v8::internal::wasm::TypeInModule::type, UpdateNodeAndAliasesTypes(), and UpdateSourcePosition().
Referenced by Reduce().
ReduceWasmTypeCheck()
Reduction v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheck (Node * node) [private]
Definition at line 501 of file wasm-gc-operator-reducer.cc.
                                                               {
  DCHECK_EQ(node->opcode(), IrOpcode::kWasmTypeCheck);
  Node* object = NodeProperties::GetValueInput(node, 0);
  Node* rtt = NodeProperties::GetValueInput(node, 1);
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  wasm::TypeInModule object_type = ObjectTypeFromContext(object, control);
  if (object_type.type.is_uninhabited()) return NoChange();
  if (InDeadBranch(rtt)) return NoChange();
  wasm::TypeInModule rtt_type = NodeProperties::GetType(rtt).AsWasm();
  DCHECK_EQ(object_type.module, rtt_type.module);
  if (wasm::IsHeapSubtypeOf(object_type.type.heap_type(),
                            rtt_type.type.heap_type(), object_type.module)) {
    bool null_succeeds =
        OpParameter<WasmTypeCheckConfig>(node->op()).to.is_nullable();
    // Type cast will fail only on null.
    gasm_.InitializeEffectControl(effect, control);
    Node* condition = SetType(object_type.type.is_nullable() && !null_succeeds
                                  ? gasm_.IsNotNull(object, object_type.type)
                                  : gasm_.Int32Constant(1),
                              wasm::kWasmI32);
    ReplaceWithValue(node, condition);
    node->Kill();
    return Replace(condition);
  }
  if (wasm::HeapTypesUnrelated(object_type.type.heap_type(),
                               rtt_type.type.heap_type(), object_type.module)) {
    bool null_succeeds =
        OpParameter<WasmTypeCheckConfig>(node->op()).to.is_nullable();
    Node* condition = nullptr;
    if (null_succeeds && object_type.type.is_nullable()) {
      // The cast only succeeds in case of null.
      gasm_.InitializeEffectControl(effect, control);
      condition =
          SetType(gasm_.IsNull(object, object_type.type), wasm::kWasmI32);
    } else {
      // The cast never succeeds.
      condition = SetType(gasm_.Int32Constant(0), wasm::kWasmI32);
    }
    ReplaceWithValue(node, condition);
    node->Kill();
    return Replace(condition);
  }
  // TODO(12166): Think about modules below if we have cross-module inlining.
  // Update the from-type in the type cast.
  WasmTypeCheckConfig current_config =
      OpParameter<WasmTypeCheckConfig>(node->op());
  NodeProperties::ChangeOp(node, gasm_.simplified()->WasmTypeCheck(
                                     {object_type.type, current_config.to,
                                      current_config.exactness}));
  return TakeStatesFromFirstControl(node);
}
References v8::internal::compiler::NodeProperties::ChangeOp(), DCHECK_EQ, gasm_, v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::wasm::ValueType::heap_type(), v8::internal::wasm::HeapTypesUnrelated(), v8::internal::compiler::anonymous_namespace{wasm-gc-operator-reducer.cc}::InDeadBranch(), v8::internal::compiler::GraphAssembler::InitializeEffectControl(), v8::internal::compiler::GraphAssembler::Int32Constant(), v8::internal::wasm::ValueTypeBase::is_nullable(), v8::internal::wasm::ValueTypeBase::is_uninhabited(), v8::internal::wasm::IsHeapSubtypeOf(), v8::internal::compiler::WasmGraphAssembler::IsNotNull(), v8::internal::compiler::WasmGraphAssembler::IsNull(), v8::internal::compiler::Node::Kill(), v8::internal::wasm::kWasmI32, v8::internal::wasm::TypeInModule::module, v8::internal::compiler::Reducer::NoChange(), ObjectTypeFromContext(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), SetType(), v8::internal::compiler::WasmGraphAssembler::simplified(), v8::internal::compiler::AdvancedReducerWithControlPathState< NodeWithType, kMultipleInstances >::TakeStatesFromFirstControl(), and v8::internal::wasm::TypeInModule::type.
Referenced by Reduce().
ReduceWasmTypeCheckAbstract()
Reduction v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheckAbstract (Node * node) [private]
Definition at line 560 of file wasm-gc-operator-reducer.cc.
                                                                       {
  DCHECK_EQ(node->opcode(), IrOpcode::kWasmTypeCheckAbstract);
  Node* object = NodeProperties::GetValueInput(node, 0);
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  WasmTypeCheckConfig config = OpParameter<WasmTypeCheckConfig>(node->op());
  wasm::TypeInModule object_type = ObjectTypeFromContext(object, control);
  if (object_type.type.is_uninhabited()) return NoChange();
  const bool null_succeeds = config.to.is_nullable();
  if (wasm::IsHeapSubtypeOf(object_type.type.heap_type(), config.to.heap_type(),
                            object_type.module)) {
    // Type cast will fail only on null.
    gasm_.InitializeEffectControl(effect, control);
    Node* condition = SetType(object_type.type.is_nullable() && !null_succeeds
                                  ? gasm_.IsNotNull(object, object_type.type)
                                  : gasm_.Int32Constant(1),
                              wasm::kWasmI32);
    ReplaceWithValue(node, condition);
    node->Kill();
    return Replace(condition);
  }
  // This can never result from user code, only from internal shortcuts,
  // e.g. when using externrefs as strings.
  const bool implicit_internalize =
      config.from.AsNullable() == wasm::kWasmExternRef &&
      wasm::IsHeapSubtypeOf(config.to.heap_type(), wasm::kWasmAnyRef,
                            object_type.module);
  if (!implicit_internalize &&
      wasm::HeapTypesUnrelated(object_type.type.heap_type(),
                               config.to.heap_type(), object_type.module)) {
    Node* condition = nullptr;
    if (null_succeeds && object_type.type.is_nullable()) {
      // The cast only succeeds in case of null.
      gasm_.InitializeEffectControl(effect, control);
      condition =
          SetType(gasm_.IsNull(object, object_type.type), wasm::kWasmI32);
    } else {
      // The cast never succeeds.
      condition = SetType(gasm_.Int32Constant(0), wasm::kWasmI32);
    }
    ReplaceWithValue(node, condition);
    node->Kill();
    return Replace(condition);
  }
  // Update the from-type in the type cast.
  NodeProperties::ChangeOp(
      node, gasm_.simplified()->WasmTypeCheckAbstract(
                {object_type.type, config.to, config.exactness}));
  return TakeStatesFromFirstControl(node);
}
References v8::internal::wasm::ValueType::AsNullable(), v8::internal::compiler::NodeProperties::ChangeOp(), DCHECK_EQ, v8::internal::compiler::WasmTypeCheckConfig::from, gasm_, v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::wasm::ValueType::heap_type(), v8::internal::wasm::HeapTypesUnrelated(), v8::internal::compiler::GraphAssembler::InitializeEffectControl(), v8::internal::compiler::GraphAssembler::Int32Constant(), v8::internal::wasm::ValueTypeBase::is_nullable(), v8::internal::wasm::ValueTypeBase::is_uninhabited(), v8::internal::wasm::IsHeapSubtypeOf(), v8::internal::compiler::WasmGraphAssembler::IsNotNull(), v8::internal::compiler::WasmGraphAssembler::IsNull(), v8::internal::compiler::Node::Kill(), v8::internal::wasm::kWasmAnyRef, v8::internal::wasm::kWasmExternRef, v8::internal::wasm::kWasmI32, v8::internal::wasm::TypeInModule::module, v8::internal::compiler::Reducer::NoChange(), ObjectTypeFromContext(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), SetType(), v8::internal::compiler::WasmGraphAssembler::simplified(), v8::internal::compiler::AdvancedReducerWithControlPathState< NodeWithType, kMultipleInstances >::TakeStatesFromFirstControl(), v8::internal::compiler::WasmTypeCheckConfig::to, and v8::internal::wasm::TypeInModule::type.
Referenced by Reduce().
SetType()
Node * v8::internal::compiler::WasmGCOperatorReducer::SetType (Node * node, wasm::ValueType type) [private]
Definition at line 99 of file wasm-gc-operator-reducer.cc.
                                                                   {
  NodeProperties::SetType(node, Type::Wasm(type, module_, graph()->zone()));
  return node;
}
References graph(), module_, v8::internal::compiler::NodeProperties::SetType(), v8::internal::tracing::type, and v8::internal::compiler::AdvancedReducerWithControlPathState< NodeWithType, kMultipleInstances >::zone().
Referenced by ReduceCheckNull(), ReduceWasmTypeCast(), ReduceWasmTypeCastAbstract(), ReduceWasmTypeCheck(), and ReduceWasmTypeCheckAbstract().
simplified()
SimplifiedOperatorBuilder* v8::internal::compiler::WasmGCOperatorReducer::simplified () [inline], [private]
Definition at line 88 of file wasm-gc-operator-reducer.h.
{ return gasm_.simplified(); }
References gasm_, and v8::internal::compiler::WasmGraphAssembler::simplified().
Referenced by ReduceWasmArrayLength(), and ReduceWasmStructOperation().
UpdateNodeAndAliasesTypes()
Reduction v8::internal::compiler::WasmGCOperatorReducer::UpdateNodeAndAliasesTypes (Node * state_owner, ControlPathTypes parent_state, Node * node, wasm::TypeInModule type, bool in_new_block) [private]
Definition at line 104 of file wasm-gc-operator-reducer.cc.
                                              {
  ControlPathTypes previous_knowledge = GetState(state_owner);
  if (!previous_knowledge.IsEmpty()) {
    NodeWithType current_info = previous_knowledge.LookupState(node);
    if (current_info.IsSet() && current_info.type == type) return NoChange();
  }
  Node* current = node;
  ControlPathTypes current_state = parent_state;
  while (current != nullptr) {
    UpdateStates(state_owner, current_state, current, {current, type},
                 in_new_block);
    current = GetAlias(current);
    current_state = GetState(state_owner);
    in_new_block = false;
  }
  return Changed(state_owner);
}
References v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::anonymous_namespace{wasm-gc-operator-reducer.cc}::GetAlias(), v8::internal::compiler::AdvancedReducerWithControlPathState< NodeWithType, kMultipleInstances >::GetState(), v8::internal::compiler::ControlPathState< NodeState, node_uniqueness >::IsEmpty(), v8::internal::compiler::NodeWithType::IsSet(), v8::internal::compiler::ControlPathState< NodeState, node_uniqueness >::LookupState(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::NodeWithType::type, v8::internal::tracing::type, and v8::internal::compiler::AdvancedReducerWithControlPathState< NodeWithType, kMultipleInstances >::UpdateStates().
Referenced by ReduceAssertNotNull(), ReduceIf(), ReduceTypeGuard(), ReduceWasmArrayLength(), ReduceWasmStructOperation(), ReduceWasmTypeCast(), and ReduceWasmTypeCastAbstract().
UpdateSourcePosition()
void v8::internal::compiler::WasmGCOperatorReducer::UpdateSourcePosition (Node * new_node, Node * old_node) [private]
Definition at line 616 of file wasm-gc-operator-reducer.cc.
                                                                 {
  if (source_position_table_) {
    SourcePosition position =
        source_position_table_->GetSourcePosition(old_node);
    DCHECK(position.ScriptOffset() != kNoSourcePosition);
    source_position_table_->SetSourcePosition(new_node, position);
  }
}
References v8::internal::DCHECK(), v8::internal::compiler::SourcePositionTable::GetSourcePosition(), v8::internal::kNoSourcePosition, v8::internal::SourcePosition::ScriptOffset(), v8::internal::compiler::SourcePositionTable::SetSourcePosition(), and source_position_table_.
Referenced by ReduceWasmTypeCast(), and ReduceWasmTypeCastAbstract().
Member Data Documentation
gasm_
WasmGraphAssembler v8::internal::compiler::WasmGCOperatorReducer::gasm_ [private]
Definition at line 91 of file wasm-gc-operator-reducer.h.
Referenced by ReduceCheckNull(), ReduceWasmTypeCast(), ReduceWasmTypeCastAbstract(), ReduceWasmTypeCheck(), ReduceWasmTypeCheckAbstract(), and simplified().
mcgraph_
MachineGraph* v8::internal::compiler::WasmGCOperatorReducer::mcgraph_ [private]
Definition at line 90 of file wasm-gc-operator-reducer.h.
Referenced by common(), and graph().
module_
const wasm::WasmModule* v8::internal::compiler::WasmGCOperatorReducer::module_ [private]
Definition at line 92 of file wasm-gc-operator-reducer.h.
Referenced by ReduceIf(), ReduceWasmTypeCast(), ReduceWasmTypeCastAbstract(), and SetType().
source_position_table_
SourcePositionTable* v8::internal::compiler::WasmGCOperatorReducer::source_position_table_ [private]
Definition at line 93 of file wasm-gc-operator-reducer.h.
Referenced by UpdateSourcePosition().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/wasm-gc-operator-reducer.h
/mnt/V8SourceCode/src/compiler/wasm-gc-operator-reducer.cc