v8::internal::wasm::WasmEngine Class Reference
#include <wasm-engine.h>
Classes
struct CurrentGCInfo
struct IsolateInfo
class LogCodesTask
struct NativeModuleInfo
Public Types
using DeadCodeMap = std::unordered_map< NativeModule *, std::vector< WasmCode * > >
Public Member Functions
WasmEngine ()
WasmEngine (const WasmEngine &)=delete
WasmEngine & operator= (const WasmEngine &)=delete
~WasmEngine ()
bool SyncValidate (Isolate *isolate, WasmEnabledFeatures enabled, CompileTimeImports compile_imports, base::Vector< const uint8_t > bytes)
MaybeHandle< AsmWasmData > SyncCompileTranslatedAsmJs (Isolate *isolate, ErrorThrower *thrower, base::OwnedVector< const uint8_t > bytes, DirectHandle< Script > script, base::Vector< const uint8_t > asm_js_offset_table_bytes, DirectHandle< HeapNumber > uses_bitset, LanguageMode language_mode)
DirectHandle< WasmModuleObject > FinalizeTranslatedAsmJs (Isolate *isolate, DirectHandle< AsmWasmData > asm_wasm_data, DirectHandle< Script > script)
MaybeDirectHandle< WasmModuleObject > SyncCompile (Isolate *isolate, WasmEnabledFeatures enabled, CompileTimeImports compile_imports, ErrorThrower *thrower, base::OwnedVector< const uint8_t > bytes)
MaybeDirectHandle< WasmInstanceObject > SyncInstantiate (Isolate *isolate, ErrorThrower *thrower, DirectHandle< WasmModuleObject > module_object, MaybeDirectHandle< JSReceiver > imports, MaybeDirectHandle< JSArrayBuffer > memory)
void AsyncCompile (Isolate *isolate, WasmEnabledFeatures enabled, CompileTimeImports compile_imports, std::shared_ptr< CompilationResultResolver > resolver, base::OwnedVector< const uint8_t > bytes, const char *api_method_name_for_errors)
void AsyncInstantiate (Isolate *isolate, std::unique_ptr< InstantiationResultResolver > resolver, DirectHandle< WasmModuleObject > module_object, MaybeDirectHandle< JSReceiver > imports)
std::shared_ptr< StreamingDecoder > StartStreamingCompilation (Isolate *isolate, WasmEnabledFeatures enabled, CompileTimeImports compile_imports, DirectHandle< Context > context, const char *api_method_name, std::shared_ptr< CompilationResultResolver > resolver)
void CompileFunction (Counters *counters, NativeModule *native_module, uint32_t function_index, ExecutionTier tier)
void EnterDebuggingForIsolate (Isolate *isolate)
void LeaveDebuggingForIsolate (Isolate *isolate)
DirectHandle< WasmModuleObject > ImportNativeModule (Isolate *isolate, std::shared_ptr< NativeModule > shared_module, base::Vector< const char > source_url)
void FlushLiftoffCode ()
size_t GetLiftoffCodeSizeForTesting ()
AccountingAllocator * allocator ()
std::shared_ptr< CompilationStatistics > GetOrCreateTurboStatistics ()
void DumpAndResetTurboStatistics ()
void DumpTurboStatistics ()
CodeTracer * GetCodeTracer ()
std::unique_ptr< AsyncCompileJob > RemoveCompileJob (AsyncCompileJob *job)
bool HasRunningCompileJob (Isolate *isolate)
void DeleteCompileJobsOnContext (DirectHandle< Context > context)
void DeleteCompileJobsOnIsolate (Isolate *isolate)
void AddIsolate (Isolate *isolate)
void RemoveIsolate (Isolate *isolate)
void LogCode (base::Vector< WasmCode * >)
bool LogWrapperCode (WasmCode *)
void EnableCodeLogging (Isolate *)
void LogOutstandingCodesForIsolate (Isolate *)
std::shared_ptr< NativeModule > NewNativeModule (Isolate *isolate, WasmEnabledFeatures enabled_features, WasmDetectedFeatures detected_features, CompileTimeImports compile_imports, std::shared_ptr< const WasmModule > module, size_t code_size_estimate)
std::shared_ptr< NativeModule > MaybeGetNativeModule (ModuleOrigin origin, base::Vector< const uint8_t > wire_bytes, const CompileTimeImports &compile_imports, Isolate *isolate)
std::shared_ptr< NativeModule > UpdateNativeModuleCache (bool has_error, std::shared_ptr< NativeModule > native_module, Isolate *isolate)
bool GetStreamingCompilationOwnership (size_t prefix_hash, const CompileTimeImports &compile_imports)
void StreamingCompilationFailed (size_t prefix_hash, const CompileTimeImports &compile_imports)
void FreeNativeModule (NativeModule *)
void ClearWeakScriptHandle (Isolate *isolate, std::unique_ptr< Address * > location)
void SampleTopTierCodeSizeInAllIsolates (const std::shared_ptr< NativeModule > &)
void ReportLiveCodeForGC (Isolate *, std::unordered_set< WasmCode * > &live_code)
void ReportLiveCodeFromStackForGC (Isolate *)
void AddPotentiallyDeadCode (WasmCode *)
void TriggerCodeGCForTesting ()
void FreeDeadCode (const DeadCodeMap &, std::vector< WasmCode * > &)
void FreeDeadCodeLocked (const DeadCodeMap &, std::vector< WasmCode * > &)
DirectHandle< Script > GetOrCreateScript (Isolate *, const std::shared_ptr< NativeModule > &, base::Vector< const char > source_url)
std::shared_ptr< OperationsBarrier > GetBarrierForBackgroundCompile ()
TypeCanonicalizer * type_canonicalizer ()
void DecodeAllNameSections (CanonicalTypeNamesProvider *target)
compiler::WasmCallDescriptors * call_descriptors ()
size_t EstimateCurrentMemoryConsumption () const
void PrintCurrentMemoryConsumptionEstimate () const
int GetDeoptsExecutedCount () const
int IncrementDeoptsExecutedCount ()
size_t NativeModuleCount () const
Static Public Member Functions
static void InitializeOncePerProcess ()
static void GlobalTearDown ()
static WasmOrphanedGlobalHandle * NewOrphanedGlobalHandle (WasmOrphanedGlobalHandle **pointer)
static void FreeAllOrphanedGlobalHandles (WasmOrphanedGlobalHandle *start)
static Address GetNondeterminismAddr ()
static bool had_nondeterminism ()
static void set_had_nondeterminism ()
static bool clear_nondeterminism ()
Private Member Functions
AsyncCompileJob * CreateAsyncCompileJob (Isolate *isolate, WasmEnabledFeatures enabled, CompileTimeImports compile_imports, base::OwnedVector< const uint8_t > bytes, DirectHandle< Context > context, const char *api_method_name, std::shared_ptr< CompilationResultResolver > resolver, int compilation_id)
void TriggerCodeGC_Locked (size_t dead_code_limit)
void TriggerGC (int8_t gc_sequence_index)
bool RemoveIsolateFromCurrentGC (Isolate *)
void PotentiallyFinishCurrentGC ()
void EnableCodeLogging (NativeModule *)
void DisableCodeLogging (NativeModule *)
Private Attributes
AccountingAllocator allocator_
std::atomic< int > next_compilation_id_ {0}
std::atomic< int > deopts_executed_ {0}
TypeCanonicalizer type_canonicalizer_
compiler::WasmCallDescriptors call_descriptors_
base::Mutex mutex_
std::unordered_map< AsyncCompileJob *, std::unique_ptr< AsyncCompileJob > > async_compile_jobs_
std::shared_ptr< CompilationStatistics > compilation_stats_
std::unique_ptr< CodeTracer > code_tracer_
std::unordered_map< Isolate *, std::unique_ptr< IsolateInfo > > isolates_
std::unordered_map< NativeModule *, std::unique_ptr< NativeModuleInfo > > native_modules_
std::shared_ptr< OperationsBarrier > operations_barrier_
std::atomic< size_t > num_modules_with_code_logging_ {0}
size_t new_potentially_dead_code_size_ = 0
std::unordered_set< WasmCode * > potentially_dead_code_
int8_t num_code_gcs_triggered_ = 0
std::unique_ptr< CurrentGCInfo > current_gc_info_
NativeModuleCache native_module_cache_
Static Private Attributes
static std::atomic< int32_t > had_nondeterminism_ {0}
Detailed Description
Definition at line 162 of file wasm-engine.h.
Member Typedef Documentation
DeadCodeMap
using v8::internal::wasm::WasmEngine::DeadCodeMap = std::unordered_map<NativeModule*, std::vector<WasmCode*> >
Definition at line 380 of file wasm-engine.h.
Constructor & Destructor Documentation
WasmEngine() [1/2]
v8::internal::wasm::WasmEngine::WasmEngine ()
Definition at line 543 of file wasm-engine.cc.
: call_descriptors_(&allocator_) {}
Referenced by EstimateCurrentMemoryConsumption().
WasmEngine() [2/2]
v8::internal::wasm::WasmEngine::WasmEngine (const WasmEngine &) [delete]
 WasmEngine()
v8::internal::wasm::WasmEngine::~WasmEngine ()
Definition at line 545 of file wasm-engine.cc.
                        {
#ifdef V8_ENABLE_WASM_GDB_REMOTE_DEBUGGING
  // Synchronize on the GDB-remote thread, if running.
  gdb_server_.reset();
#endif // V8_ENABLE_WASM_GDB_REMOTE_DEBUGGING
  if (V8_UNLIKELY(v8_flags.print_wasm_offheap_memory_size)) {
    PrintCurrentMemoryConsumptionEstimate();
  }
  // Free all modules that were kept alive for collecting PGO. This is to avoid
  // memory leaks.
  if (V8_UNLIKELY(native_modules_kept_alive_for_pgo)) {
    delete native_modules_kept_alive_for_pgo;
  }
  operations_barrier_->CancelAndWait();
  // All code should have been deleted already, but wrappers managed by the
  // WasmImportWrapperCache are placed in {potentially_dead_code_} when they
  // are no longer referenced, and we don't want to wait for the next
  // Wasm Code GC cycle to remove them from that set.
  for (WasmCode* code : potentially_dead_code_) {
    code->DcheckRefCountIsOne();
    // The actual instructions will get thrown out when the global
    // WasmImportWrapperCache's {code_allocator_} frees its memory region.
    // Here we just pacify LSan.
    delete code;
  }
  // All AsyncCompileJobs have been canceled.
  DCHECK(async_compile_jobs_.empty());
  // All Isolates have been deregistered.
  DCHECK(isolates_.empty());
  // All NativeModules did die.
  DCHECK(native_modules_.empty());
  // Native module cache does not leak.
  DCHECK(native_module_cache_.empty());
}
References async_compile_jobs_, code, v8::internal::DCHECK(), v8::internal::wasm::NativeModuleCache::empty(), isolates_, native_module_cache_, native_modules_, v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::native_modules_kept_alive_for_pgo, operations_barrier_, potentially_dead_code_, PrintCurrentMemoryConsumptionEstimate(), v8::internal::v8_flags, and V8_UNLIKELY.
Member Function Documentation
AddIsolate()
void v8::internal::wasm::WasmEngine::AddIsolate (Isolate * isolate)
Definition at line 1238 of file wasm-engine.cc.
                                            {
  const bool log_code = WasmCode::ShouldBeLogged(isolate);
  // Create the IsolateInfo.
  {
    // Create the IsolateInfo outside the mutex to reduce the size of the
    // critical section and to avoid lock-order-inversion issues.
    auto isolate_info = std::make_unique<IsolateInfo>(isolate, log_code);
    base::MutexGuard guard(&mutex_);
    DCHECK_EQ(0, isolates_.count(isolate));
    isolates_.emplace(isolate, std::move(isolate_info));
  }
  if (log_code) {
    // Log existing wrappers (which are shared across isolates).
    GetWasmImportWrapperCache()->LogForIsolate(isolate);
  }
  // Install sampling GC callback.
  // TODO(v8:7424): For now we sample module sizes in a GC callback. This will
  // bias samples towards apps with high memory pressure. We should switch to
  // using sampling based on regular intervals independent of the GC.
  auto callback = [](v8::Isolate* v8_isolate, v8::GCType type,
                     v8::GCCallbackFlags flags, void* data) {
    Isolate* isolate = reinterpret_cast<Isolate*>(v8_isolate);
    Counters* counters = isolate->counters();
    WasmEngine* engine = GetWasmEngine();
    {
      base::MutexGuard lock(&engine->mutex_);
      DCHECK_EQ(1, engine->isolates_.count(isolate));
      for (auto* native_module : engine->isolates_[isolate]->native_modules) {
        native_module->SampleCodeSize(counters);
      }
    }
    // Also sample overall metadata size (this includes the metadata size of
    // individual NativeModules; we are summing that up twice, which could be
    // improved performance-wise).
    // The engine-wide metadata also includes global storage e.g. for the type
    // canonicalizer.
    Histogram* metadata_histogram = counters->wasm_engine_metadata_size_kb();
    if (metadata_histogram->Enabled()) {
      size_t engine_meta_data = engine->EstimateCurrentMemoryConsumption();
      metadata_histogram->AddSample(static_cast<int>(engine_meta_data / KB));
    }
  };
  isolate->heap()->AddGCEpilogueCallback(callback, v8::kGCTypeMarkSweepCompact,
                                         nullptr);
#ifdef V8_ENABLE_WASM_GDB_REMOTE_DEBUGGING
  if (gdb_server_) {
    gdb_server_->AddIsolate(isolate);
  }
#endif // V8_ENABLE_WASM_GDB_REMOTE_DEBUGGING
}
References v8::internal::Heap::AddGCEpilogueCallback(), v8::internal::Histogram::AddSample(), v8::internal::Isolate::counters(), DCHECK_EQ, v8::internal::Histogram::Enabled(), EstimateCurrentMemoryConsumption(), v8::internal::flags, v8::internal::wasm::GetWasmEngine(), v8::internal::wasm::GetWasmImportWrapperCache(), v8::internal::Isolate::heap(), isolates_, v8::internal::KB, v8::kGCTypeMarkSweepCompact, v8::internal::wasm::WasmImportWrapperCache::LogForIsolate(), mutex_, v8::internal::wasm::WasmCode::ShouldBeLogged(), and v8::internal::tracing::type.
Referenced by v8::internal::Isolate::Init().
AddPotentiallyDeadCode()
void v8::internal::wasm::WasmEngine::AddPotentiallyDeadCode (WasmCode * code)
Definition at line 1820 of file wasm-engine.cc.
                                                      {
  base::MutexGuard guard(&mutex_);
  DCHECK(code->is_dying()); // Caller just marked it as such.
  auto added = potentially_dead_code_.insert(code);
  DCHECK(added.second);
  USE(added);
  new_potentially_dead_code_size_ += code->instructions().size();
  if (v8_flags.wasm_code_gc) {
    // Trigger a GC if 64kB plus 10% of committed code are potentially dead.
    size_t dead_code_limit =
        v8_flags.stress_wasm_code_gc
            ? 0
            : 64 * KB + GetWasmCodeManager()->committed_code_space() / 10;
    if (new_potentially_dead_code_size_ > dead_code_limit) {
      TriggerCodeGC_Locked(dead_code_limit);
    }
  }
}
References code, v8::internal::wasm::WasmCodeManager::committed_code_space(), v8::internal::DCHECK(), v8::internal::wasm::GetWasmCodeManager(), v8::internal::KB, mutex_, new_potentially_dead_code_size_, potentially_dead_code_, TriggerCodeGC_Locked(), USE, and v8::internal::v8_flags.
Referenced by v8::internal::wasm::WasmCode::DecRefOnPotentiallyDeadCode().
allocator()
AccountingAllocator* v8::internal::wasm::WasmEngine::allocator () [inline]
Definition at line 246 of file wasm-engine.h.
{ return &allocator_; }
Referenced by v8::internal::wasm::WasmCompilationUnit::ExecuteCompilation(), v8::internal::anonymous_namespace{wasm-debug.cc}::FindNextBreakablePosition(), v8::Isolate::GetHeapStatistics(), v8::internal::WasmScript::GetPossibleBreakpoints(), v8::internal::wasm::ValidateFunctionsStreamingJob::Run(), and v8::internal::wasm::ThrowLazyCompilationError().
AsyncCompile()
void v8::internal::wasm::WasmEngine::AsyncCompile (Isolate * isolate, WasmEnabledFeatures enabled, CompileTimeImports compile_imports, std::shared_ptr< CompilationResultResolver > resolver, base::OwnedVector< const uint8_t > bytes, const char * api_method_name_for_errors)
Definition at line 790 of file wasm-engine.cc.
                                            {
  int compilation_id = next_compilation_id_.fetch_add(1);
  TRACE_EVENT1("v8.wasm", "wasm.AsyncCompile", "id", compilation_id);
  if (!v8_flags.wasm_async_compilation || v8_flags.wasm_jitless) {
    // Asynchronous compilation disabled; fall back on synchronous compilation.
    ErrorThrower thrower(isolate, api_method_name_for_errors);
    MaybeDirectHandle<WasmModuleObject> module_object;
    module_object = SyncCompile(isolate, enabled, std::move(compile_imports),
                                &thrower, std::move(bytes));
    if (thrower.error()) {
      resolver->OnCompilationFailed(thrower.Reify());
      return;
    }
    DirectHandle<WasmModuleObject> module = module_object.ToHandleChecked();
    resolver->OnCompilationSucceeded(module);
    return;
  }
  if (v8_flags.wasm_test_streaming) {
    std::shared_ptr<StreamingDecoder> streaming_decoder =
        StartStreamingCompilation(isolate, enabled, std::move(compile_imports),
                                  direct_handle(isolate->context(), isolate),
                                  api_method_name_for_errors,
                                  std::move(resolver));
    auto* rng = isolate->random_number_generator();
    base::SmallVector<base::Vector<const uint8_t>, 16> ranges;
    if (!bytes.empty()) ranges.push_back(bytes.as_vector());
    // Split into up to 16 ranges (2^4).
    for (int round = 0; round < 4; ++round) {
      for (auto it = ranges.begin(); it != ranges.end(); ++it) {
        auto range = *it;
        if (range.size() < 2 || !rng->NextBool()) continue; // Do not split.
        // Choose split point within [1, range.size() - 1].
        static_assert(kV8MaxWasmModuleSize <= kMaxInt);
        size_t split_point =
            1 + rng->NextInt(static_cast<int>(range.size() - 1));
        // Insert first sub-range *before* {it} and make {it} point after it.
        it = ranges.insert(it, range.SubVector(0, split_point)) + 1;
        *it = range.SubVectorFrom(split_point);
      }
    }
    for (auto range : ranges) {
      streaming_decoder->OnBytesReceived(range);
    }
    streaming_decoder->Finish();
    return;
  }
  AsyncCompileJob* job = CreateAsyncCompileJob(
      isolate, enabled, std::move(compile_imports), std::move(bytes),
      isolate->native_context(), api_method_name_for_errors,
      std::move(resolver), compilation_id);
  job->Start();
}
References v8::base::OwnedVector< T >::as_vector(), v8::base::SmallVector< T, kSize, Allocator >::begin(), v8::internal::Isolate::context(), CreateAsyncCompileJob(), v8::internal::direct_handle(), v8::base::OwnedVector< T >::empty(), v8::base::SmallVector< T, kSize, Allocator >::end(), v8::internal::wasm::ErrorThrower::error(), v8::base::SmallVector< T, kSize, Allocator >::insert(), v8::internal::kMaxInt, v8::internal::wasm::kV8MaxWasmModuleSize, v8::internal::Isolate::native_context(), next_compilation_id_, v8::base::SmallVector< T, kSize, Allocator >::push_back(), v8::internal::Isolate::random_number_generator(), v8::internal::wasm::ErrorThrower::Reify(), v8::internal::wasm::AsyncCompileJob::Start(), StartStreamingCompilation(), SyncCompile(), v8::internal::MaybeDirectHandle< T >::ToHandleChecked(), TRACE_EVENT1, and v8::internal::v8_flags.
Referenced by v8::anonymous_namespace{wasm-js.cc}::WebAssemblyCompileImpl(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyInstantiateImpl().
AsyncInstantiate()
void v8::internal::wasm::WasmEngine::AsyncInstantiate (Isolate * isolate, std::unique_ptr< InstantiationResultResolver > resolver, DirectHandle< WasmModuleObject > module_object, MaybeDirectHandle< JSReceiver > imports)
Definition at line 753 of file wasm-engine.cc.
                                           {
  ErrorThrower thrower(isolate, "WebAssembly.instantiate()");
  TRACE_EVENT0("v8.wasm", "wasm.AsyncInstantiate");
  // Instantiate a TryCatch so that caught exceptions won't propagate out.
  // They will still be set as exceptions on the isolate.
  // TODO(clemensb): Avoid TryCatch, use Execution::TryCall internally to invoke
  // start function and report thrown exception explicitly via out argument.
  v8::TryCatch catcher(reinterpret_cast<v8::Isolate*>(isolate));
  catcher.SetVerbose(false);
  catcher.SetCaptureMessage(false);
  MaybeDirectHandle<WasmInstanceObject> instance_object =
      SyncInstantiate(isolate, &thrower, module_object, imports,
                      DirectHandle<JSArrayBuffer>::null());
  if (!instance_object.is_null()) {
    resolver->OnInstantiationSucceeded(instance_object.ToHandleChecked());
    return;
  }
  if (isolate->has_exception()) {
    thrower.Reset();
    if (isolate->is_execution_terminating()) return;
    // The JS code executed during instantiation has thrown an exception.
    // We have to move the exception to the promise chain.
    DirectHandle<JSAny> exception(Cast<JSAny>(isolate->exception()), isolate);
    isolate->clear_exception();
    resolver->OnInstantiationFailed(exception);
  } else {
    DCHECK(thrower.error());
    resolver->OnInstantiationFailed(thrower.Reify());
  }
}
References v8::internal::Isolate::clear_exception(), v8::internal::DCHECK(), v8::internal::wasm::ErrorThrower::error(), v8::internal::Isolate::exception(), v8::internal::Isolate::has_exception(), v8::internal::instance_object, v8::internal::Isolate::is_execution_terminating(), v8::internal::wasm::ErrorThrower::Reify(), v8::internal::wasm::ErrorThrower::Reset(), v8::TryCatch::SetCaptureMessage(), v8::TryCatch::SetVerbose(), SyncInstantiate(), and TRACE_EVENT0.
Referenced by v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::AsyncInstantiateCompileResultResolver::OnCompilationSucceeded(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyInstantiateImpl().
call_descriptors()
compiler::WasmCallDescriptors* v8::internal::wasm::WasmEngine::call_descriptors () [inline]
Definition at line 396 of file wasm-engine.h.
                                                  {
    return &call_descriptors_;
  }
Referenced by v8::internal::wasm::WasmWrapperTSGraphBuilder::GetBigIntToI64CallDescriptor(), and v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerCall().
clear_nondeterminism()
static bool v8::internal::wasm::WasmEngine::clear_nondeterminism () [inline], [static]
Definition at line 437 of file wasm-engine.h.
                                     {
    return had_nondeterminism_.exchange(0, std::memory_order_relaxed) != 0;
  }
ClearWeakScriptHandle()
void v8::internal::wasm::WasmEngine::ClearWeakScriptHandle (Isolate * isolate, std::unique_ptr< Address * > location)
Definition at line 521 of file wasm-engine.cc.
                                                                         {
  // This function is designed for one targeted use case, which always
  // acquires a lock on {mutex_} before calling here.
  mutex_.AssertHeld();
  IsolateInfo* isolate_info = isolates_[isolate].get();
  std::shared_ptr<TaskRunner> runner = isolate_info->foreground_task_runner;
  runner->PostTask(std::make_unique<ClearWeakScriptHandleTask>(
      isolate, std::move(location)));
}
References v8::base::Mutex::AssertHeld(), v8::internal::wasm::WasmEngine::IsolateInfo::foreground_task_runner, isolates_, and mutex_.
Referenced by v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::WeakScriptHandle::~WeakScriptHandle().
CompileFunction()
void v8::internal::wasm::WasmEngine::CompileFunction (Counters * counters, NativeModule * native_module, uint32_t function_index, ExecutionTier tier)
Definition at line 871 of file wasm-engine.cc.
                                                                              {
  DCHECK(!v8_flags.wasm_jitless);
  // Note we assume that "one-off" compilations can discard detected features.
  WasmDetectedFeatures detected;
  WasmCompilationUnit::CompileWasmFunction(
      counters, native_module, &detected,
      &native_module->module()->functions[function_index], tier);
}
References v8::internal::wasm::WasmCompilationUnit::CompileWasmFunction(), v8::internal::DCHECK(), v8::internal::wasm::WasmModule::functions, v8::internal::wasm::NativeModule::module(), and v8::internal::v8_flags.
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::TierUpAllFunctions(), and v8::internal::wasm::TierUpNowForTesting().
CreateAsyncCompileJob()
AsyncCompileJob * v8::internal::wasm::WasmEngine::CreateAsyncCompileJob (Isolate * isolate, WasmEnabledFeatures enabled, CompileTimeImports compile_imports, base::OwnedVector< const uint8_t > bytes, DirectHandle< Context > context, const char * api_method_name, std::shared_ptr< CompilationResultResolver > resolver, int compilation_id) [private]
Definition at line 1150 of file wasm-engine.cc.
                                                                           {
  DirectHandle<NativeContext> incumbent_context =
      isolate->GetIncumbentContext();
  AsyncCompileJob* job = new AsyncCompileJob(
      isolate, enabled, std::move(compile_imports), std::move(bytes), context,
      incumbent_context, api_method_name, std::move(resolver), compilation_id);
  // Pass ownership to the unique_ptr in {async_compile_jobs_}.
  base::MutexGuard guard(&mutex_);
  async_compile_jobs_[job] = std::unique_ptr<AsyncCompileJob>(job);
  return job;
}
References async_compile_jobs_, v8::internal::Isolate::GetIncumbentContext(), and mutex_.
Referenced by AsyncCompile(), and StartStreamingCompilation().
DecodeAllNameSections()
void v8::internal::wasm::WasmEngine::DecodeAllNameSections (CanonicalTypeNamesProvider * target)
Definition at line 2012 of file wasm-engine.cc.
                                                                         {
  base::MutexGuard lock(&mutex_);
  for (const auto& [native_module, native_module_info] : native_modules_) {
    target->DecodeNames(native_module);
  }
}
References v8::internal::wasm::CanonicalTypeNamesProvider::DecodeNames(), mutex_, and native_modules_.
Referenced by v8::internal::wasm::CanonicalTypeNamesProvider::DecodeNameSections().
DeleteCompileJobsOnContext()
void v8::internal::wasm::WasmEngine::DeleteCompileJobsOnContext (DirectHandle< Context > context)
Definition at line 1185 of file wasm-engine.cc.
                                                                         {
  // Under the mutex get all jobs to delete. Then delete them without holding
  // the mutex, such that deletion can reenter the WasmEngine.
  std::vector<std::unique_ptr<AsyncCompileJob>> jobs_to_delete;
  {
    base::MutexGuard guard(&mutex_);
    for (auto it = async_compile_jobs_.begin();
         it != async_compile_jobs_.end();) {
      if (!it->first->context().is_identical_to(context)) {
        ++it;
        continue;
      }
      jobs_to_delete.push_back(std::move(it->second));
      it = async_compile_jobs_.erase(it);
    }
  }
}
References async_compile_jobs_, and mutex_.
Referenced by v8::Isolate::ContextDisposedNotification().
DeleteCompileJobsOnIsolate()
void v8::internal::wasm::WasmEngine::DeleteCompileJobsOnIsolate (Isolate * isolate)
Definition at line 1203 of file wasm-engine.cc.
                                                            {
  // Under the mutex get all jobs to delete. Then delete them without holding
  // the mutex, such that deletion can reenter the WasmEngine.
  std::vector<std::unique_ptr<AsyncCompileJob>> jobs_to_delete;
  std::vector<std::weak_ptr<NativeModule>> modules_in_isolate;
  {
    base::MutexGuard guard(&mutex_);
    for (auto it = async_compile_jobs_.begin();
         it != async_compile_jobs_.end();) {
      if (it->first->isolate() != isolate) {
        ++it;
        continue;
      }
      jobs_to_delete.push_back(std::move(it->second));
      it = async_compile_jobs_.erase(it);
    }
    DCHECK_EQ(1, isolates_.count(isolate));
    auto* isolate_info = isolates_[isolate].get();
    for (auto* native_module : isolate_info->native_modules) {
      DCHECK_EQ(1, native_modules_.count(native_module));
      modules_in_isolate.emplace_back(native_modules_[native_module]->weak_ptr);
    }
  }
  // All modules that have not finished initial compilation yet cannot be
  // shared with other isolates. Hence we cancel their compilation. In
  // particular, this will cancel wrapper compilation which is bound to this
  // isolate (this would be a UAF otherwise).
  for (auto& weak_module : modules_in_isolate) {
    if (auto shared_module = weak_module.lock()) {
      shared_module->compilation_state()->CancelInitialCompilation();
    }
  }
}
References async_compile_jobs_, DCHECK_EQ, isolates_, mutex_, and native_modules_.
Referenced by v8::internal::Isolate::Deinit().
DisableCodeLogging()
void v8::internal::wasm::WasmEngine::DisableCodeLogging (NativeModule * native_module) [private]
Definition at line 1501 of file wasm-engine.cc.
                                                               {
  // The caller should hold the mutex.
  mutex_.AssertHeld();
  DCHECK(native_module->log_code());
  native_module->DisableCodeLogging();
  num_modules_with_code_logging_.fetch_sub(1, std::memory_order_relaxed);
  // Check the accuracy of {num_modules_with_code_logging_}.
  DCHECK_EQ(
      num_modules_with_code_logging_.load(std::memory_order_relaxed),
      std::count_if(
          native_modules_.begin(), native_modules_.end(),
          [](std::pair<NativeModule* const, std::unique_ptr<NativeModuleInfo>>&
                 pair) { return pair.first->log_code(); }));
}
References v8::base::Mutex::AssertHeld(), v8::base::count_if(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::wasm::NativeModule::DisableCodeLogging(), v8::internal::wasm::NativeModule::log_code(), mutex_, native_modules_, and num_modules_with_code_logging_.
Referenced by FreeNativeModule(), and RemoveIsolate().
DumpAndResetTurboStatistics()
void v8::internal::wasm::WasmEngine::DumpAndResetTurboStatistics ()
Definition at line 1125 of file wasm-engine.cc.
                                             {
  base::MutexGuard guard(&mutex_);
  if (compilation_stats_ != nullptr) {
    StdoutStream os;
    os << AsPrintableStatistics{"Turbofan Wasm", *compilation_stats_, false}
       << std::endl;
  }
  compilation_stats_.reset();
}
References compilation_stats_, and mutex_.
Referenced by v8::internal::Isolate::DumpAndResetStats().
DumpTurboStatistics()
void v8::internal::wasm::WasmEngine::DumpTurboStatistics ()
Definition at line 1135 of file wasm-engine.cc.
                                     {
  base::MutexGuard guard(&mutex_);
  if (compilation_stats_ != nullptr) {
    StdoutStream os;
    os << AsPrintableStatistics{"Turbofan Wasm", *compilation_stats_, false}
       << std::endl;
  }
}
References compilation_stats_, and mutex_.
EnableCodeLogging() [1/2]
void v8::internal::wasm::WasmEngine::EnableCodeLogging (Isolate * isolate)
Definition at line 1472 of file wasm-engine.cc.
                                                   {
  base::MutexGuard guard(&mutex_);
  auto it = isolates_.find(isolate);
  DCHECK_NE(isolates_.end(), it);
  IsolateInfo* info = it->second.get();
  if (info->log_codes) return;
  info->log_codes = true;
  // Also set {NativeModule::log_code_} for all native modules currently used by
  // this isolate.
  for (NativeModule* native_module : info->native_modules) {
    if (!native_module->log_code()) EnableCodeLogging(native_module);
  }
}
References DCHECK_NE, isolates_, v8::internal::wasm::NativeModule::log_code(), v8::internal::wasm::WasmEngine::IsolateInfo::log_codes, mutex_, and v8::internal::wasm::WasmEngine::IsolateInfo::native_modules.
Referenced by ImportNativeModule(), v8::internal::V8FileLogger::LateSetup(), MaybeGetNativeModule(), NewNativeModule(), v8::internal::ProfilingScope::ProfilingScope(), v8::internal::RUNTIME_FUNCTION(), v8::internal::V8FileLogger::SetCodeEventHandler(), and UpdateNativeModuleCache().
EnableCodeLogging() [2/2]
void v8::internal::wasm::WasmEngine::EnableCodeLogging (NativeModule * native_module) [private]
Definition at line 1486 of file wasm-engine.cc.
                                                              {
  // The caller should hold the mutex.
  mutex_.AssertHeld();
  DCHECK(!native_module->log_code());
  native_module->EnableCodeLogging();
  num_modules_with_code_logging_.fetch_add(1, std::memory_order_relaxed);
  // Check the accuracy of {num_modules_with_code_logging_}.
  DCHECK_EQ(
      num_modules_with_code_logging_.load(std::memory_order_relaxed),
      std::count_if(
          native_modules_.begin(), native_modules_.end(),
          [](std::pair<NativeModule* const, std::unique_ptr<NativeModuleInfo>>&
                 pair) { return pair.first->log_code(); }));
}
References v8::base::Mutex::AssertHeld(), v8::base::count_if(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::wasm::NativeModule::EnableCodeLogging(), v8::internal::wasm::NativeModule::log_code(), mutex_, native_modules_, and num_modules_with_code_logging_.
EnterDebuggingForIsolate()
void v8::internal::wasm::WasmEngine::EnterDebuggingForIsolate (Isolate * isolate)
Definition at line 883 of file wasm-engine.cc.
                                                          {
  if (v8_flags.wasm_jitless) return;
  std::vector<std::shared_ptr<NativeModule>> native_modules;
  // {mutex_} gets taken both here and in {RemoveCompiledCode} in
  // {AddPotentiallyDeadCode}. Therefore {RemoveCompiledCode} has to be
  // called outside the lock.
  {
    base::MutexGuard lock(&mutex_);
    if (isolates_[isolate]->keep_in_debug_state) return;
    isolates_[isolate]->keep_in_debug_state = true;
    for (auto* native_module : isolates_[isolate]->native_modules) {
      DCHECK_EQ(1, native_modules_.count(native_module));
      if (auto shared_ptr = native_modules_[native_module]->weak_ptr.lock()) {
        native_modules.emplace_back(std::move(shared_ptr));
      }
      native_module->SetDebugState(kDebugging);
    }
  }
  WasmCodeRefScope ref_scope;
  for (auto& native_module : native_modules) {
    native_module->RemoveCompiledCode(
        NativeModule::RemoveFilter::kRemoveNonDebugCode);
  }
}
References DCHECK_EQ, isolates_, v8::internal::wasm::kDebugging, v8::internal::wasm::NativeModule::kRemoveNonDebugCode, mutex_, native_modules_, and v8::internal::v8_flags.
Referenced by v8::internal::RUNTIME_FUNCTION().
EstimateCurrentMemoryConsumption()
size_t v8::internal::wasm::WasmEngine::EstimateCurrentMemoryConsumption () const
Definition at line 2019 of file wasm-engine.cc.
                                                          {
  UPDATE_WHEN_CLASS_CHANGES(WasmEngine, 8392);
  UPDATE_WHEN_CLASS_CHANGES(IsolateInfo, 168);
  UPDATE_WHEN_CLASS_CHANGES(NativeModuleInfo, 56);
  UPDATE_WHEN_CLASS_CHANGES(CurrentGCInfo, 96);
  size_t result = sizeof(WasmEngine);
  result += GetCanonicalTypeNamesProvider()->EstimateCurrentMemoryConsumption();
  result += type_canonicalizer_.EstimateCurrentMemoryConsumption();
  {
    base::MutexGuard lock(&mutex_);
    result += ContentSize(async_compile_jobs_);
    result += async_compile_jobs_.size() * sizeof(AsyncCompileJob);
    result += ContentSize(potentially_dead_code_);
    // TODO(14106): Do we care about {compilation_stats_}?
    // TODO(14106): Do we care about {code_tracer_}?
    result += ContentSize(isolates_);
    result += isolates_.size() * sizeof(IsolateInfo);
    for (const auto& [isolate, isolate_info] : isolates_) {
      result += ContentSize(isolate_info->native_modules);
      result += ContentSize(isolate_info->scripts);
      result += ContentSize(isolate_info->code_to_log);
    }
    result += ContentSize(native_modules_);
    result += native_modules_.size() * sizeof(NativeModuleInfo);
    for (const auto& [native_module, native_module_info] : native_modules_) {
      result += native_module->EstimateCurrentMemoryConsumption();
      result += ContentSize(native_module_info->isolates);
    }
    if (current_gc_info_) {
      result += sizeof(CurrentGCInfo);
      result += ContentSize(current_gc_info_->outstanding_isolates);
      result += ContentSize(current_gc_info_->dead_code);
    }
  }
  if (v8_flags.trace_wasm_offheap_memory) {
    PrintF("WasmEngine: %zu\n", result);
  }
  return result;
}
References async_compile_jobs_, v8::internal::wasm::ContentSize(), current_gc_info_, v8::internal::wasm::TypeCanonicalizer::EstimateCurrentMemoryConsumption(), v8::internal::wasm::CanonicalTypeNamesProvider::EstimateCurrentMemoryConsumption(), v8::internal::wasm::GetCanonicalTypeNamesProvider(), isolates_, mutex_, native_modules_, potentially_dead_code_, v8::internal::PrintF(), v8::base::internal::result, type_canonicalizer_, UPDATE_WHEN_CLASS_CHANGES, v8::internal::v8_flags, and WasmEngine().
Referenced by AddIsolate(), v8::internal::MemoryMeasurement::FinishProcessing(), PrintCurrentMemoryConsumptionEstimate(), and v8::internal::RUNTIME_FUNCTION().
FinalizeTranslatedAsmJs()
DirectHandle< WasmModuleObject > v8::internal::wasm::WasmEngine::FinalizeTranslatedAsmJs (Isolate * isolate, DirectHandle< AsmWasmData > asm_wasm_data, DirectHandle< Script > script)
Definition at line 659 of file wasm-engine.cc.
                                 {
  std::shared_ptr<NativeModule> native_module =
      asm_wasm_data->managed_native_module()->get();
  DirectHandle<WasmModuleObject> module_object =
      WasmModuleObject::New(isolate, std::move(native_module), script);
  return module_object;
}
References v8::internal::WasmModuleObject::New(), and v8::internal::script.
FlushLiftoffCode()
void v8::internal::wasm::WasmEngine::FlushLiftoffCode ()
Definition at line 1090 of file wasm-engine.cc.
                                  {
  DCHECK(v8_flags.flush_liftoff_code);
  // Keep the NativeModules alive until after the destructor of the
  // `WasmCodeRefScope`, which still needs to access the code and the
  // NativeModule.
  std::vector<std::shared_ptr<NativeModule>> native_modules;
  WasmCodeRefScope ref_scope;
  base::MutexGuard guard(&mutex_);
  for (auto& [native_module, info] : native_modules_) {
    std::shared_ptr<NativeModule> shared = info->weak_ptr.lock();
    if (!shared) continue; // The NativeModule is dying anyway.
    native_module->RemoveCompiledCode(
        NativeModule::RemoveFilter::kRemoveLiftoffCode);
    native_modules.emplace_back(std::move(shared));
  }
}
References v8::internal::DCHECK(), v8::internal::wasm::NativeModule::kRemoveLiftoffCode, mutex_, native_modules_, and v8::internal::v8_flags.
Referenced by v8::internal::Heap::EagerlyFreeExternalMemoryAndWasmCode(), v8::internal::wasm::WasmCodeManager::NewNativeModule(), and v8::internal::RUNTIME_FUNCTION().
FreeAllOrphanedGlobalHandles()
void v8::internal::wasm::WasmEngine::FreeAllOrphanedGlobalHandles (WasmOrphanedGlobalHandle * start) [static]
Definition at line 139 of file wasm-engine.cc.
                                                                             {
  // This is meant to be called from ~Isolate, so we no longer care about
  // maintaining invariants: the only task is to free memory to prevent leaks.
  while (start != nullptr) {
    WasmOrphanedGlobalHandle* next = start->next_;
    delete start;
    start = next;
  }
}
References v8::internal::wasm::WasmOrphanedGlobalHandle::next_.
Referenced by v8::internal::Isolate::~Isolate().
FreeDeadCode()
void v8::internal::wasm::WasmEngine::FreeDeadCode (const DeadCodeMap & dead_code, std::vector< WasmCode * > & dead_wrappers)
Definition at line 1872 of file wasm-engine.cc.
                                                                   {
  base::MutexGuard guard(&mutex_);
  FreeDeadCodeLocked(dead_code, dead_wrappers);
}
References FreeDeadCodeLocked(), and mutex_.
Referenced by v8::internal::wasm::WasmCode::DecrementRefCount().
FreeDeadCodeLocked()
void v8::internal::wasm::WasmEngine::FreeDeadCodeLocked (const DeadCodeMap & dead_code, std::vector< WasmCode * > & dead_wrappers)
Definition at line 1878 of file wasm-engine.cc.
                                                                         {
  TRACE_EVENT0("v8.wasm", "wasm.FreeDeadCode");
  mutex_.AssertHeld();
  for (auto& dead_code_entry : dead_code) {
    NativeModule* native_module = dead_code_entry.first;
    const std::vector<WasmCode*>& code_vec = dead_code_entry.second;
    TRACE_CODE_GC("Freeing %zu code object%s of module %p.\n", code_vec.size(),
                  code_vec.size() == 1 ? "" : "s", native_module);
    native_module->FreeCode(base::VectorOf(code_vec));
  }
  if (dead_wrappers.size()) {
    TRACE_CODE_GC("Freeing %zu wrapper%s.\n", dead_wrappers.size(),
                  dead_wrappers.size() == 1 ? "" : "s");
    GetWasmImportWrapperCache()->Free(dead_wrappers);
  }
}
References v8::base::Mutex::AssertHeld(), v8::internal::wasm::WasmImportWrapperCache::Free(), v8::internal::wasm::NativeModule::FreeCode(), v8::internal::wasm::GetWasmImportWrapperCache(), mutex_, TRACE_CODE_GC, TRACE_EVENT0, and v8::base::VectorOf().
Referenced by FreeDeadCode(), and PotentiallyFinishCurrentGC().
FreeNativeModule()
void v8::internal::wasm::WasmEngine::FreeNativeModule (NativeModule * native_module)
Definition at line 1691 of file wasm-engine.cc.
                                                             {
  base::MutexGuard guard(&mutex_);
  auto module = native_modules_.find(native_module);
  DCHECK_NE(native_modules_.end(), module);
  auto part_of_native_module = [native_module](WasmCode* code) {
    return code->native_module() == native_module;
  };
  for (Isolate* isolate : module->second->isolates) {
    DCHECK_EQ(1, isolates_.count(isolate));
    IsolateInfo* info = isolates_[isolate].get();
    DCHECK_EQ(1, info->native_modules.count(native_module));
    info->native_modules.erase(native_module);
    info->scripts.erase(native_module);
    // Flush the Wasm code lookup cache, since it may refer to some
    // code within native modules that we are going to release (if a
    // Managed<wasm::NativeModule> object is no longer referenced).
    GetWasmCodeManager()->FlushCodeLookupCache(isolate);
    // {CodeToLogPerScript} keeps the NativeModule alive, so if it dies, there
    // can not be any outstanding code to be logged.
#ifdef DEBUG
    for (auto& log_entry : info->code_to_log) {
      for (WasmCode* code : log_entry.second.code) {
        DCHECK_NE(native_module, code->native_module());
      }
    }
#endif
  }
  // If there is a GC running which has references to code contained in the
  // deleted {NativeModule}, remove those references.
  if (current_gc_info_) {
    for (auto it = current_gc_info_->dead_code.begin(),
              end = current_gc_info_->dead_code.end();
         it != end;) {
      if ((*it)->native_module() == native_module) {
        it = current_gc_info_->dead_code.erase(it);
      } else {
        ++it;
      }
    }
    TRACE_CODE_GC("Native module %p died, reducing dead code objects to %zu.\n",
                  native_module, current_gc_info_->dead_code.size());
  }
  // If any code objects are currently tracked as dead or near-dead, remove
  // references belonging to the NativeModule that's being deleted.
  std::erase_if(potentially_dead_code_, part_of_native_module);
  if (native_module->log_code()) DisableCodeLogging(native_module);
  native_module_cache_.Erase(native_module);
  native_modules_.erase(module);
}
References code, v8::internal::wasm::WasmEngine::IsolateInfo::code_to_log, current_gc_info_, DCHECK_EQ, DCHECK_NE, DisableCodeLogging(), v8::internal::compiler::end(), v8::internal::wasm::NativeModuleCache::Erase(), v8::base::erase_if(), v8::internal::wasm::WasmCodeManager::FlushCodeLookupCache(), v8::internal::wasm::GetWasmCodeManager(), isolates_, v8::internal::wasm::NativeModule::log_code(), mutex_, native_module_cache_, v8::internal::wasm::WasmEngine::IsolateInfo::native_modules, native_modules_, potentially_dead_code_, v8::internal::wasm::WasmEngine::IsolateInfo::scripts, and TRACE_CODE_GC.
Referenced by v8::internal::wasm::NativeModule::~NativeModule().
GetBarrierForBackgroundCompile()
std::shared_ptr< OperationsBarrier > v8::internal::wasm::WasmEngine::GetBarrierForBackgroundCompile ()
Definition at line 1926 of file wasm-engine.cc.
                                           {
  return operations_barrier_;
}
References operations_barrier_.
GetCodeTracer()
CodeTracer * v8::internal::wasm::WasmEngine::GetCodeTracer ()
Definition at line 1144 of file wasm-engine.cc.
                                      {
  base::MutexGuard guard(&mutex_);
  if (code_tracer_ == nullptr) code_tracer_.reset(new CodeTracer(-1));
  return code_tracer_.get();
}
References code_tracer_, and mutex_.
Referenced by v8::internal::compiler::TFPipelineData::GetCodeTracer(), and v8::internal::compiler::turboshaft::PipelineData::GetCodeTracer().
GetDeoptsExecutedCount()
int v8::internal::wasm::WasmEngine::GetDeoptsExecutedCount () const
Definition at line 2069 of file wasm-engine.cc.
                                             {
  return deopts_executed_.load(std::memory_order::relaxed);
}
References deopts_executed_.
Referenced by v8::internal::RUNTIME_FUNCTION().
GetLiftoffCodeSizeForTesting()
size_t v8::internal::wasm::WasmEngine::GetLiftoffCodeSizeForTesting ()
Definition at line 1107 of file wasm-engine.cc.
                                                {
  base::MutexGuard guard(&mutex_);
  size_t codesize_liftoff = 0;
  for (auto& [native_module, info] : native_modules_) {
    codesize_liftoff += native_module->SumLiftoffCodeSizeForTesting();
  }
  return codesize_liftoff;
}
References mutex_, and native_modules_.
GetNondeterminismAddr()
static Address v8::internal::wasm::WasmEngine::GetNondeterminismAddr () [inline], [static]
Definition at line 421 of file wasm-engine.h.
                                         {
    return reinterpret_cast<Address>(&had_nondeterminism_);
  }
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CheckNan(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CheckS128Nan().
GetOrCreateScript()
DirectHandle< Script > v8::internal::wasm::WasmEngine::GetOrCreateScript (Isolate * isolate, const std::shared_ptr< NativeModule > & native_module, base::Vector< const char > source_url)
Definition at line 1896 of file wasm-engine.cc.
                                       {
  {
    base::MutexGuard guard(&mutex_);
    DCHECK_EQ(1, isolates_.count(isolate));
    auto& scripts = isolates_[isolate]->scripts;
    auto it = scripts.find(native_module.get());
    if (it != scripts.end()) {
      DirectHandle<Script> weak_global_handle = it->second.handle();
      if (weak_global_handle.is_null()) {
        scripts.erase(it);
      } else {
        return DirectHandle<Script>::New(*weak_global_handle, isolate);
      }
    }
  }
  // Temporarily release the mutex to let the GC collect native modules.
  auto script = CreateWasmScript(isolate, native_module, source_url);
  {
    base::MutexGuard guard(&mutex_);
    DCHECK_EQ(1, isolates_.count(isolate));
    auto& scripts = isolates_[isolate]->scripts;
    DCHECK_EQ(0, scripts.count(native_module.get()));
    scripts.emplace(native_module.get(), WeakScriptHandle(script, isolate));
    return script;
  }
}
References v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::CreateWasmScript(), DCHECK_EQ, v8::internal::DirectHandle< T >::is_null(), isolates_, mutex_, v8::internal::DirectHandle< T >::New(), and v8::internal::script.
Referenced by v8::internal::wasm::DeserializeNativeModule(), ImportNativeModule(), v8::internal::wasm::AsyncCompileJob::PrepareRuntimeObjects(), and SyncCompile().
GetOrCreateTurboStatistics()
std::shared_ptr< CompilationStatistics > v8::internal::wasm::WasmEngine::GetOrCreateTurboStatistics ()
Definition at line 1117 of file wasm-engine.cc.
                                       {
  base::MutexGuard guard(&mutex_);
  if (compilation_stats_ == nullptr) {
    compilation_stats_.reset(new CompilationStatistics());
  }
  return compilation_stats_;
}
References compilation_stats_, and mutex_.
GetStreamingCompilationOwnership()
bool v8::internal::wasm::WasmEngine::GetStreamingCompilationOwnership (size_t prefix_hash, const CompileTimeImports & compile_imports)
Definition at line 1672 of file wasm-engine.cc.
                                                                   {
  TRACE_EVENT0("v8.wasm", "wasm.GetStreamingCompilationOwnership");
  if (native_module_cache_.GetStreamingCompilationOwnership(prefix_hash,
                                                            compile_imports)) {
    return true;
  }
  // This is only a marker, not for tracing execution time. There should be a
  // later "wasm.GetNativeModuleFromCache" event for trying to get the module
  // from the cache.
  TRACE_EVENT0("v8.wasm", "CacheHit");
  return false;
}
References v8::internal::wasm::NativeModuleCache::GetStreamingCompilationOwnership(), native_module_cache_, and TRACE_EVENT0.
Referenced by v8::internal::wasm::AsyncStreamingProcessor::ProcessCodeSectionHeader().
GlobalTearDown()
void v8::internal::wasm::WasmEngine::GlobalTearDown () [static]
Definition at line 2109 of file wasm-engine.cc.
                                {
#ifdef V8_ENABLE_DRUMBRAKE
  if (v8_flags.wasm_jitless) {
    WasmInterpreter::GlobalTearDown();
  }
#endif // V8_ENABLE_DRUMBRAKE
  // Note: This can be called multiple times in a row (see
  // test-api/InitializeAndDisposeMultiple). This is fine, as
  // {global_wasm_state} will be nullptr then.
  delete global_wasm_state;
  global_wasm_state = nullptr;
  GetProcessWideWasmCodePointerTable()->TearDown();
}
References v8::internal::wasm::GetProcessWideWasmCodePointerTable(), v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::global_wasm_state, v8::internal::wasm::WasmInterpreter::GlobalTearDown(), v8::internal::wasm::WasmCodePointerTable::TearDown(), and v8::internal::v8_flags.
Referenced by v8::internal::V8::Dispose().
had_nondeterminism()
static bool v8::internal::wasm::WasmEngine::had_nondeterminism () [inline], [static]
Definition at line 426 of file wasm-engine.h.
                                   {
    return had_nondeterminism_.load(std::memory_order_relaxed) != 0;
  }
HasRunningCompileJob()
bool v8::internal::wasm::WasmEngine::HasRunningCompileJob (Isolate * isolate)
Definition at line 1176 of file wasm-engine.cc.
                                                      {
  base::MutexGuard guard(&mutex_);
  DCHECK_EQ(1, isolates_.count(isolate));
  for (auto& entry : async_compile_jobs_) {
    if (entry.first->isolate() == isolate) return true;
  }
  return false;
}
References async_compile_jobs_, DCHECK_EQ, isolates_, and mutex_.
Referenced by v8::Isolate::HasPendingBackgroundTasks().
ImportNativeModule()
DirectHandle< WasmModuleObject > v8::internal::wasm::WasmEngine::ImportNativeModule (Isolate * isolate, std::shared_ptr< NativeModule > shared_module, base::Vector< const char > source_url)
Definition at line 1063 of file wasm-engine.cc.
                                       {
  NativeModule* native_module = shared_native_module.get();
  ModuleWireBytes wire_bytes(native_module->wire_bytes());
  DirectHandle<Script> script =
      GetOrCreateScript(isolate, shared_native_module, source_url);
  native_module->LogWasmCodes(isolate, *script);
  DirectHandle<WasmModuleObject> module_object =
      WasmModuleObject::New(isolate, std::move(shared_native_module), script);
  {
    base::MutexGuard lock(&mutex_);
    DCHECK_EQ(1, isolates_.count(isolate));
    IsolateInfo* isolate_info = isolates_.find(isolate)->second.get();
    isolate_info->native_modules.insert(native_module);
    DCHECK_EQ(1, native_modules_.count(native_module));
    native_modules_[native_module]->isolates.insert(isolate);
    if (isolate_info->log_codes && !native_module->log_code()) {
      EnableCodeLogging(native_module);
    }
  }
  // Finish the Wasm script now and make it public to the debugger.
  isolate->debug()->OnAfterCompile(script);
  return module_object;
}
References DCHECK_EQ, v8::internal::Isolate::debug(), EnableCodeLogging(), GetOrCreateScript(), isolates_, v8::internal::wasm::NativeModule::log_code(), v8::internal::wasm::WasmEngine::IsolateInfo::log_codes, v8::internal::wasm::NativeModule::LogWasmCodes(), mutex_, v8::internal::wasm::WasmEngine::IsolateInfo::native_modules, native_modules_, v8::internal::WasmModuleObject::New(), v8::internal::Debug::OnAfterCompile(), v8::internal::script, and v8::internal::wasm::NativeModule::wire_bytes().
Referenced by v8::WasmModuleObject::FromCompiledModule().
IncrementDeoptsExecutedCount()
int v8::internal::wasm::WasmEngine::IncrementDeoptsExecutedCount ()
Definition at line 2073 of file wasm-engine.cc.
                                             {
  int previous_value = deopts_executed_.fetch_add(1, std::memory_order_relaxed);
  return previous_value + 1;
}
References deopts_executed_.
InitializeOncePerProcess()
void v8::internal::wasm::WasmEngine::InitializeOncePerProcess () [static]
Definition at line 2095 of file wasm-engine.cc.
                                          {
  DCHECK_NULL(global_wasm_state);
  global_wasm_state = new GlobalWasmState();
#ifdef V8_ENABLE_DRUMBRAKE
  if (v8_flags.wasm_jitless) {
    WasmInterpreter::InitializeOncePerProcess();
  }
#endif // V8_ENABLE_DRUMBRAKE
  GetProcessWideWasmCodePointerTable()->Initialize();
}
References DCHECK_NULL, v8::internal::wasm::GetProcessWideWasmCodePointerTable(), v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::global_wasm_state, v8::internal::wasm::WasmCodePointerTable::Initialize(), v8::internal::wasm::WasmInterpreter::InitializeOncePerProcess(), and v8::internal::v8_flags.
Referenced by v8::internal::V8::Initialize().
LeaveDebuggingForIsolate()
void v8::internal::wasm::WasmEngine::LeaveDebuggingForIsolate (Isolate * isolate)
Definition at line 909 of file wasm-engine.cc.
                                                          {
  // Only trigger recompilation after releasing the mutex, otherwise we risk
  // deadlocks because of lock inversion. The bool tells whether the module
  // needs recompilation for tier up.
  std::vector<std::pair<std::shared_ptr<NativeModule>, bool>> native_modules;
  {
    base::MutexGuard lock(&mutex_);
    isolates_[isolate]->keep_in_debug_state = false;
    auto can_remove_debug_code = [this](NativeModule* native_module) {
      DCHECK_EQ(1, native_modules_.count(native_module));
      for (auto* isolate : native_modules_[native_module]->isolates) {
        DCHECK_EQ(1, isolates_.count(isolate));
        if (isolates_[isolate]->keep_in_debug_state) return false;
      }
      return true;
    };
    for (auto* native_module : isolates_[isolate]->native_modules) {
      DCHECK_EQ(1, native_modules_.count(native_module));
      auto shared_ptr = native_modules_[native_module]->weak_ptr.lock();
      if (!shared_ptr) continue; // The module is not used any more.
      if (!native_module->IsInDebugState()) continue;
      // Only start tier-up if no other isolate needs this module in tiered
      // down state.
      bool remove_debug_code = can_remove_debug_code(native_module);
      if (remove_debug_code) native_module->SetDebugState(kNotDebugging);
      native_modules.emplace_back(std::move(shared_ptr), remove_debug_code);
    }
  }
  for (auto& entry : native_modules) {
    auto& native_module = entry.first;
    bool remove_debug_code = entry.second;
    // Remove all breakpoints set by this isolate.
    if (native_module->HasDebugInfo()) {
      native_module->GetDebugInfo()->RemoveIsolate(isolate);
    }
    if (remove_debug_code) {
      WasmCodeRefScope ref_scope;
      native_module->RemoveCompiledCode(
          NativeModule::RemoveFilter::kRemoveDebugCode);
    }
  }
}
References DCHECK_EQ, isolates_, v8::internal::wasm::kNotDebugging, v8::internal::wasm::NativeModule::kRemoveDebugCode, mutex_, and native_modules_.
Referenced by v8::internal::RUNTIME_FUNCTION().
LogCode()
void v8::internal::wasm::WasmEngine::LogCode (base::Vector< WasmCode * > code_vec)
Definition at line 1367 of file wasm-engine.cc.
                                                       {
  if (code_vec.empty()) return;
  NativeModule* native_module = code_vec[0]->native_module();
  if (!native_module->log_code()) return;
  using TaskToSchedule =
      std::pair<std::shared_ptr<v8::TaskRunner>, std::unique_ptr<LogCodesTask>>;
  std::vector<TaskToSchedule> to_schedule;
  {
    base::MutexGuard guard(&mutex_);
    DCHECK_EQ(1, native_modules_.count(native_module));
    NativeModuleInfo* native_module_info =
        native_modules_.find(native_module)->second.get();
    std::shared_ptr<NativeModule> shared_native_module =
        native_module_info->weak_ptr.lock();
    // The NativeModule cannot be dying already at this point.
    DCHECK_NOT_NULL(shared_native_module);
    for (Isolate* isolate : native_module_info->isolates) {
      DCHECK_EQ(1, isolates_.count(isolate));
      IsolateInfo* info = isolates_[isolate].get();
      if (info->log_codes == false) continue;
      auto script_it = info->scripts.find(native_module);
      // If the script does not yet exist, logging will happen later. If the
      // weak handle is cleared already, we also don't need to log any more.
      if (script_it == info->scripts.end()) continue;
      // If there is no code scheduled to be logged already in that isolate,
      // then schedule a new task and also set an interrupt to log the newly
      // added code as soon as possible.
      if (info->code_to_log.empty()) {
        isolate->stack_guard()->RequestLogWasmCode();
        to_schedule.emplace_back(info->foreground_task_runner,
                                 std::make_unique<LogCodesTask>(isolate));
      }
      WeakScriptHandle& weak_script_handle = script_it->second;
      auto& log_entry = info->code_to_log[weak_script_handle.script_id()];
      if (!log_entry.native_module) {
        log_entry.native_module = shared_native_module;
      }
      if (!log_entry.source_url) {
        log_entry.source_url = weak_script_handle.source_url();
      }
      log_entry.code.insert(log_entry.code.end(), code_vec.begin(),
                            code_vec.end());
      // Increment the reference count for the added {log_entry.code} entries.
      for (WasmCode* code : code_vec) {
        DCHECK_EQ(native_module, code->native_module());
        code->IncRef();
      }
    }
  }
  for (auto& [runner, task] : to_schedule) {
    runner->PostTask(std::move(task));
  }
}
References v8::base::Vector< T >::begin(), code, v8::internal::wasm::WasmEngine::IsolateInfo::code_to_log, DCHECK_EQ, DCHECK_NOT_NULL, v8::base::Vector< T >::empty(), v8::base::Vector< T >::end(), v8::internal::wasm::WasmEngine::IsolateInfo::foreground_task_runner, v8::internal::wasm::WasmEngine::NativeModuleInfo::isolates, isolates_, v8::internal::wasm::NativeModule::log_code(), v8::internal::wasm::WasmEngine::IsolateInfo::log_codes, mutex_, native_modules_, v8::internal::wasm::WasmEngine::IsolateInfo::scripts, v8::internal::Isolate::stack_guard(), and v8::internal::wasm::WasmEngine::NativeModuleInfo::weak_ptr.
Referenced by v8::internal::wasm::CompileLazy(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::PublishCode().
LogOutstandingCodesForIsolate()
void v8::internal::wasm::WasmEngine::LogOutstandingCodesForIsolate (Isolate * isolate)
Definition at line 1516 of file wasm-engine.cc.
                                                               {
  // Under the mutex, get the vector of wasm code to log. Then log and decrement
  // the ref count without holding the mutex.
  std::unordered_map<int, IsolateInfo::CodeToLogPerScript> code_to_log_map;
  {
    base::MutexGuard guard(&mutex_);
    DCHECK_EQ(1, isolates_.count(isolate));
    code_to_log_map.swap(isolates_[isolate]->code_to_log);
  }
  // Check again whether we still need to log code.
  bool should_log = WasmCode::ShouldBeLogged(isolate);
  TRACE_EVENT0("v8.wasm", "wasm.LogCode");
  for (auto& [script_id, code_to_log] : code_to_log_map) {
    if (should_log) {
      for (WasmCode* code : code_to_log.code) {
        const char* source_url = code_to_log.source_url.get();
        // The source URL can be empty for eval()'ed scripts.
        if (!source_url) source_url = "";
        code->LogCode(isolate, source_url, script_id);
      }
    }
    WasmCode::DecrementRefCount(base::VectorOf(code_to_log.code));
  }
}
References code, DCHECK_EQ, v8::internal::wasm::WasmCode::DecrementRefCount(), isolates_, mutex_, v8::internal::wasm::WasmCode::ShouldBeLogged(), TRACE_EVENT0, and v8::base::VectorOf().
Referenced by v8::internal::wasm::CompileLazy(), v8::internal::wasm::CompileToNativeModule(), v8::internal::wasm::WasmImportWrapperCache::CompileWasmJsFastCallWrapper(), v8::internal::wasm::WasmImportWrapperCache::CompileWrapper(), v8::internal::StackGuard::HandleInterrupts(), and v8::internal::wasm::WasmEngine::LogCodesTask::RunInternal().
LogWrapperCode()
bool v8::internal::wasm::WasmEngine::LogWrapperCode (WasmCode * code)
Definition at line 1425 of file wasm-engine.cc.
                                              {
  // Wrappers don't belong to any particular NativeModule.
  DCHECK_NULL(code->native_module());
  // Fast path:
  if (!num_modules_with_code_logging_.load(std::memory_order_relaxed)) {
    return false;
  }
  using TaskToSchedule =
      std::pair<std::shared_ptr<v8::TaskRunner>, std::unique_ptr<LogCodesTask>>;
  std::vector<TaskToSchedule> to_schedule;
  bool did_trigger_code_logging = false;
  {
    base::MutexGuard guard(&mutex_);
    for (const auto& entry : isolates_) {
      Isolate* isolate = entry.first;
      IsolateInfo* info = entry.second.get();
      if (info->log_codes == false) continue;
      did_trigger_code_logging = true;
      // If this is the first code to log in that isolate, request an interrupt
      // to log the newly added code as soon as possible.
      if (info->code_to_log.empty()) {
        isolate->stack_guard()->RequestLogWasmCode();
        to_schedule.emplace_back(info->foreground_task_runner,
                                 std::make_unique<LogCodesTask>(isolate));
      }
      constexpr int kNoScriptId = -1;
      auto& log_entry = info->code_to_log[kNoScriptId];
      log_entry.code.push_back(code);
      // Increment the reference count for the added {log_entry.code} entry.
      // TODO(jkummerow): It might be nice to have a custom smart pointer
      // that manages updating the refcount for the WasmCode it holds.
      code->IncRef();
    }
    DCHECK_EQ(did_trigger_code_logging, num_modules_with_code_logging_.load(
                                            std::memory_order_relaxed) > 0);
  }
  for (auto& [runner, task] : to_schedule) {
    runner->PostTask(std::move(task));
  }
  return did_trigger_code_logging;
}
References code, v8::internal::wasm::WasmEngine::IsolateInfo::code_to_log, DCHECK_EQ, DCHECK_NULL, v8::internal::wasm::WasmEngine::IsolateInfo::foreground_task_runner, isolates_, v8::internal::wasm::WasmEngine::IsolateInfo::log_codes, mutex_, num_modules_with_code_logging_, and v8::internal::Isolate::stack_guard().
MaybeGetNativeModule()
std::shared_ptr< NativeModule > v8::internal::wasm::WasmEngine::MaybeGetNativeModule (ModuleOrigin origin, base::Vector< const uint8_t > wire_bytes, const CompileTimeImports & compile_imports, Isolate * isolate)
Definition at line 1604 of file wasm-engine.cc.
                                                                 {
  TRACE_EVENT1("v8.wasm", "wasm.GetNativeModuleFromCache", "wire_bytes",
               wire_bytes.size());
  std::shared_ptr<NativeModule> native_module =
      native_module_cache_.MaybeGetNativeModule(origin, wire_bytes,
                                                compile_imports);
  bool remove_all_code = false;
  if (native_module) {
    TRACE_EVENT0("v8.wasm", "CacheHit");
    base::MutexGuard guard(&mutex_);
    auto& native_module_info = native_modules_[native_module.get()];
    if (!native_module_info) {
      native_module_info = std::make_unique<NativeModuleInfo>(native_module);
    }
    native_module_info->isolates.insert(isolate);
    auto* isolate_data = isolates_[isolate].get();
    isolate_data->native_modules.insert(native_module.get());
    if (isolate_data->keep_in_debug_state && !native_module->IsInDebugState()) {
      remove_all_code = true;
      native_module->SetDebugState(kDebugging);
    }
    if (isolate_data->log_codes && !native_module->log_code()) {
      EnableCodeLogging(native_module.get());
    }
  }
  if (remove_all_code) {
    WasmCodeRefScope ref_scope;
    native_module->RemoveCompiledCode(
        NativeModule::RemoveFilter::kRemoveNonDebugCode);
  }
  return native_module;
}
References EnableCodeLogging(), isolates_, v8::internal::wasm::kDebugging, v8::internal::wasm::NativeModule::kRemoveNonDebugCode, v8::internal::wasm::NativeModuleCache::MaybeGetNativeModule(), mutex_, native_module_cache_, native_modules_, v8::base::Vector< T >::size(), TRACE_EVENT0, and TRACE_EVENT1.
Referenced by v8::internal::wasm::DeserializeNativeModule(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::GetOrCompileNewNativeModule(), and v8::internal::wasm::AsyncCompileJob::GetOrCreateNativeModule().
NativeModuleCount()
size_t v8::internal::wasm::WasmEngine::NativeModuleCount () const
Definition at line 149 of file wasm-engine.cc.
                                           {
  base::MutexGuard guard(&mutex_);
  return native_modules_.size();
}
References mutex_, and native_modules_.
NewNativeModule()
std::shared_ptr< NativeModule > v8::internal::wasm::WasmEngine::NewNativeModule (Isolate * isolate, WasmEnabledFeatures enabled_features, WasmDetectedFeatures detected_features, CompileTimeImports compile_imports, std::shared_ptr< const WasmModule > module, size_t code_size_estimate)
Definition at line 1543 of file wasm-engine.cc.
                                                                       {
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.wasm.detailed"),
               "wasm.NewNativeModule");
#ifdef V8_ENABLE_WASM_GDB_REMOTE_DEBUGGING
  if (v8_flags.wasm_gdb_remote && !gdb_server_) {
    gdb_server_ = gdb_server::GdbServer::Create();
    gdb_server_->AddIsolate(isolate);
  }
#endif // V8_ENABLE_WASM_GDB_REMOTE_DEBUGGING
  if (!v8_flags.wasm_jitless) {
    // Initialize the import wrapper cache if that hasn't happened yet.
    GetWasmImportWrapperCache()->LazyInitialize(isolate);
  }
  std::shared_ptr<NativeModule> native_module =
      GetWasmCodeManager()->NewNativeModule(
          isolate, enabled_features, detected_features,
          std::move(compile_imports), code_size_estimate, std::move(module));
  base::MutexGuard lock(&mutex_);
  if (V8_UNLIKELY(v8_flags.experimental_wasm_pgo_to_file)) {
    if (!native_modules_kept_alive_for_pgo) {
      native_modules_kept_alive_for_pgo =
          new std::vector<std::shared_ptr<NativeModule>>;
    }
    native_modules_kept_alive_for_pgo->emplace_back(native_module);
  }
  auto [iterator, inserted] = native_modules_.insert(std::make_pair(
      native_module.get(), std::make_unique<NativeModuleInfo>(native_module)));
  DCHECK(inserted);
  NativeModuleInfo* native_module_info = iterator->second.get();
  native_module_info->isolates.insert(isolate);
  DCHECK_EQ(1, isolates_.count(isolate));
  IsolateInfo* isolate_info = isolates_.find(isolate)->second.get();
  isolate_info->native_modules.insert(native_module.get());
  if (isolate_info->keep_in_debug_state) {
    native_module->SetDebugState(kDebugging);
  }
  if (isolate_info->log_codes) {
    EnableCodeLogging(native_module.get());
  }
  // Record memory protection key support.
  if (!isolate_info->pku_support_sampled) {
    isolate_info->pku_support_sampled = true;
    auto* histogram =
        isolate->counters()->wasm_memory_protection_keys_support();
    bool has_mpk = WasmCodeManager::HasMemoryProtectionKeySupport();
    histogram->AddSample(has_mpk ? 1 : 0);
  }
  isolate->counters()->wasm_modules_per_isolate()->AddSample(
      static_cast<int>(isolate_info->native_modules.size()));
  isolate->counters()->wasm_modules_per_engine()->AddSample(
      static_cast<int>(native_modules_.size()));
  return native_module;
}
References v8::internal::Isolate::counters(), v8::internal::wasm::gdb_server::GdbServer::Create(), v8::internal::DCHECK(), DCHECK_EQ, EnableCodeLogging(), v8::internal::wasm::GetWasmCodeManager(), v8::internal::wasm::GetWasmImportWrapperCache(), v8::internal::wasm::WasmCodeManager::HasMemoryProtectionKeySupport(), v8::internal::wasm::WasmEngine::NativeModuleInfo::isolates, isolates_, v8::internal::wasm::kDebugging, v8::internal::wasm::WasmEngine::IsolateInfo::keep_in_debug_state, v8::internal::wasm::WasmImportWrapperCache::LazyInitialize(), v8::internal::wasm::WasmEngine::IsolateInfo::log_codes, mutex_, v8::internal::wasm::WasmEngine::IsolateInfo::native_modules, native_modules_, v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::native_modules_kept_alive_for_pgo, v8::internal::wasm::WasmCodeManager::NewNativeModule(), v8::internal::wasm::WasmEngine::IsolateInfo::pku_support_sampled, TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT0, v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::internal::wasm::AsyncCompileJob::CreateNativeModule(), v8::internal::wasm::DeserializeNativeModule(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::GetOrCompileNewNativeModule().
NewOrphanedGlobalHandle()
WasmOrphanedGlobalHandle * v8::internal::wasm::WasmEngine::NewOrphanedGlobalHandle (WasmOrphanedGlobalHandle ** pointer) [static]
Definition at line 125 of file wasm-engine.cc.
                                        {
  // No need for additional locking: this is only ever called indirectly
  // from {WasmEngine::ClearWeakScriptHandle()}, which holds the engine-wide
  // {mutex_}.
  WasmOrphanedGlobalHandle* orphan = new WasmOrphanedGlobalHandle();
  orphan->next_ = *pointer;
  orphan->prev_ptr_ = pointer;
  if (orphan->next_ != nullptr) orphan->next_->prev_ptr_ = &orphan->next_;
  *pointer = orphan;
  return orphan;
}
References v8::internal::wasm::WasmOrphanedGlobalHandle::next_, and v8::internal::wasm::WasmOrphanedGlobalHandle::prev_ptr_.
operator=()
WasmEngine& v8::internal::wasm::WasmEngine::operator= (const WasmEngine &) [delete]
PotentiallyFinishCurrentGC()
void v8::internal::wasm::WasmEngine::PotentiallyFinishCurrentGC () [private]
Definition at line 1970 of file wasm-engine.cc.
                                            {
  mutex_.AssertHeld();
  TRACE_CODE_GC(
      "Remaining dead code objects: %zu; outstanding isolates: %zu.\n",
      current_gc_info_->dead_code.size(),
      current_gc_info_->outstanding_isolates.size());
  // If there are more outstanding isolates, return immediately.
  if (!current_gc_info_->outstanding_isolates.empty()) return;
  // All remaining code in {current_gc_info->dead_code} is really dead.
  // Remove it from the set of potentially dead code, and decrement its
  // ref count.
  size_t num_freed = 0;
  DeadCodeMap dead_code;
  std::vector<WasmCode*> dead_wrappers;
  for (WasmCode* code : current_gc_info_->dead_code) {
    DCHECK(potentially_dead_code_.contains(code));
    DCHECK(code->is_dying());
    potentially_dead_code_.erase(code);
    if (code->DecRefOnDeadCode()) {
      NativeModule* native_module = code->native_module();
      if (native_module) {
        dead_code[native_module].push_back(code);
      } else {
        dead_wrappers.push_back(code);
      }
      ++num_freed;
    }
  }
  FreeDeadCodeLocked(dead_code, dead_wrappers);
  TRACE_CODE_GC("Found %zu dead code objects, freed %zu.\n",
                current_gc_info_->dead_code.size(), num_freed);
  USE(num_freed);
  int8_t next_gc_sequence_index = current_gc_info_->next_gc_sequence_index;
  current_gc_info_.reset();
  if (next_gc_sequence_index != 0) TriggerGC(next_gc_sequence_index);
}
References v8::base::Mutex::AssertHeld(), code, current_gc_info_, v8::internal::DCHECK(), FreeDeadCodeLocked(), mutex_, potentially_dead_code_, TRACE_CODE_GC, TriggerGC(), and USE.
Referenced by RemoveIsolate(), ReportLiveCodeForGC(), and TriggerGC().
PrintCurrentMemoryConsumptionEstimate()
void v8::internal::wasm::WasmEngine::PrintCurrentMemoryConsumptionEstimate () const
Definition at line 2063 of file wasm-engine.cc.
                                                             {
  DCHECK(v8_flags.print_wasm_offheap_memory_size);
  PrintF("Off-heap memory size of WasmEngine: %zu\n",
         EstimateCurrentMemoryConsumption());
}
References v8::internal::DCHECK(), EstimateCurrentMemoryConsumption(), v8::internal::PrintF(), and v8::internal::v8_flags.
Referenced by v8::internal::wasm::NativeModule::~NativeModule(), and ~WasmEngine().
RemoveCompileJob()
std::unique_ptr< AsyncCompileJob > v8::internal::wasm::WasmEngine::RemoveCompileJob (AsyncCompileJob * job)
Definition at line 1166 of file wasm-engine.cc.
                          {
  base::MutexGuard guard(&mutex_);
  auto item = async_compile_jobs_.find(job);
  DCHECK(item != async_compile_jobs_.end());
  std::unique_ptr<AsyncCompileJob> result = std::move(item->second);
  async_compile_jobs_.erase(item);
  return result;
}
References async_compile_jobs_, v8::internal::DCHECK(), mutex_, and v8::base::internal::result.
Referenced by v8::internal::wasm::AsyncCompileJob::Abort(), v8::internal::wasm::AsyncCompileJob::Failed(), and v8::internal::wasm::AsyncCompileJob::FinishSuccessfully().
RemoveIsolate()
void v8::internal::wasm::WasmEngine::RemoveIsolate (Isolate * isolate)
Definition at line 1291 of file wasm-engine.cc.
                                               {
#ifdef V8_ENABLE_WASM_GDB_REMOTE_DEBUGGING
  if (gdb_server_) {
    gdb_server_->RemoveIsolate(isolate);
  }
#endif // V8_ENABLE_WASM_GDB_REMOTE_DEBUGGING
  // Keep a WasmCodeRefScope which dies after the {mutex_} is released, to avoid
  // deadlock when code actually dies, as that requires taking the {mutex_}.
  // Also, keep the NativeModules themselves alive. The isolate is shutting
  // down, so the heap will not do that any more.
  std::set<std::shared_ptr<NativeModule>> native_modules_with_code_to_log;
  WasmCodeRefScope code_ref_scope_for_dead_code;
  base::MutexGuard guard(&mutex_);
  // Lookup the IsolateInfo; do not remove it yet (that happens below).
  auto isolates_it = isolates_.find(isolate);
  DCHECK_NE(isolates_.end(), isolates_it);
  IsolateInfo* isolate_info = isolates_it->second.get();
  // Remove the isolate from the per-native-module info, and other cleanup.
  for (auto* native_module : isolate_info->native_modules) {
    DCHECK_EQ(1, native_modules_.count(native_module));
    NativeModuleInfo* native_module_info =
        native_modules_.find(native_module)->second.get();
    // Check that the {NativeModule::log_code_} field has the expected value,
    // and update if the dying isolate was the last one with code logging
    // enabled.
    auto has_isolate_with_code_logging = [this, native_module_info] {
      return std::any_of(native_module_info->isolates.begin(),
                         native_module_info->isolates.end(),
                         [this](Isolate* isolate) {
                           return isolates_.find(isolate)->second->log_codes;
                         });
    };
    DCHECK_EQ(native_module->log_code(), has_isolate_with_code_logging());
    DCHECK_EQ(1, native_module_info->isolates.count(isolate));
    native_module_info->isolates.erase(isolate);
    if (native_module->log_code() && !has_isolate_with_code_logging()) {
      DisableCodeLogging(native_module);
    }
    // Remove any debug code and other info for this isolate.
    if (native_module->HasDebugInfo()) {
      native_module->GetDebugInfo()->RemoveIsolate(isolate);
    }
  }
  // Abort any outstanding GC.
  if (current_gc_info_) {
    if (RemoveIsolateFromCurrentGC(isolate)) PotentiallyFinishCurrentGC();
  }
  // Clear the {code_to_log} vector.
  for (auto& [script_id, code_to_log] : isolate_info->code_to_log) {
    if (code_to_log.native_module == nullptr) {
      // Wrapper code objects have neither Script nor NativeModule.
      DCHECK_EQ(script_id, -1);
    } else {
      native_modules_with_code_to_log.insert(code_to_log.native_module);
    }
    for (WasmCode* code : code_to_log.code) {
      // Keep a reference in the {code_ref_scope_for_dead_code} such that the
      // code cannot become dead immediately.
      WasmCodeRefScope::AddRef(code);
      code->DecRefOnLiveCode();
    }
  }
  isolate_info->code_to_log.clear();
  // Finally remove the {IsolateInfo} for this isolate.
  isolates_.erase(isolates_it);
}
References v8::internal::wasm::WasmCodeRefScope::AddRef(), v8::base::any_of(), code, v8::internal::wasm::WasmEngine::IsolateInfo::code_to_log, current_gc_info_, DCHECK_EQ, DCHECK_NE, DisableCodeLogging(), v8::internal::wasm::WasmEngine::NativeModuleInfo::isolates, isolates_, mutex_, v8::internal::wasm::WasmEngine::IsolateInfo::native_modules, native_modules_, PotentiallyFinishCurrentGC(), and RemoveIsolateFromCurrentGC().
Referenced by v8::internal::Isolate::Deinit().
RemoveIsolateFromCurrentGC()
bool v8::internal::wasm::WasmEngine::RemoveIsolateFromCurrentGC (Isolate * isolate) [private]
Definition at line 1964 of file wasm-engine.cc.
                                                            {
  mutex_.AssertHeld();
  DCHECK_NOT_NULL(current_gc_info_);
  return current_gc_info_->outstanding_isolates.erase(isolate) != 0;
}
References v8::base::Mutex::AssertHeld(), current_gc_info_, DCHECK_NOT_NULL, and mutex_.
Referenced by RemoveIsolate(), and ReportLiveCodeForGC().
ReportLiveCodeForGC()
void v8::internal::wasm::WasmEngine::ReportLiveCodeForGC (Isolate * isolate, std::unordered_set< WasmCode * > & live_code)
Definition at line 1745 of file wasm-engine.cc.
                                                                             {
  TRACE_EVENT0("v8.wasm", "wasm.ReportLiveCodeForGC");
  TRACE_CODE_GC("Isolate %d reporting %zu live code objects.\n", isolate->id(),
                live_code.size());
  base::MutexGuard guard(&mutex_);
  // This report might come in late (note that we trigger both a stack guard and
  // a foreground task). In that case, ignore it.
  if (current_gc_info_ == nullptr) return;
  if (!RemoveIsolateFromCurrentGC(isolate)) return;
  isolate->counters()->wasm_module_num_triggered_code_gcs()->AddSample(
      current_gc_info_->gc_sequence_index);
  for (WasmCode* code : live_code) current_gc_info_->dead_code.erase(code);
  PotentiallyFinishCurrentGC();
}
References code, v8::internal::Isolate::counters(), current_gc_info_, v8::internal::Isolate::id(), mutex_, PotentiallyFinishCurrentGC(), RemoveIsolateFromCurrentGC(), TRACE_CODE_GC, and TRACE_EVENT0.
Referenced by ReportLiveCodeFromStackForGC().
ReportLiveCodeFromStackForGC()
void v8::internal::wasm::WasmEngine::ReportLiveCodeFromStackForGC (Isolate * isolate)
Definition at line 1787 of file wasm-engine.cc.
                                                              {
  wasm::WasmCodeRefScope code_ref_scope;
  std::unordered_set<wasm::WasmCode*> live_wasm_code;
  for (const std::unique_ptr<StackMemory>& stack : isolate->wasm_stacks()) {
    if (stack->IsActive()) {
      // The active stack's jump buffer does not match the current state, use
      // the thread info below instead.
      continue;
    }
    for (StackFrameIterator it(isolate, stack.get()); !it.done();
         it.Advance()) {
      StackFrame* const frame = it.frame();
      ReportLiveCodeFromFrameForGC(isolate, frame, live_wasm_code);
    }
  }
  for (StackFrameIterator it(isolate, isolate->thread_local_top(),
                             StackFrameIterator::FirstStackOnly{});
       !it.done(); it.Advance()) {
    StackFrame* const frame = it.frame();
    ReportLiveCodeFromFrameForGC(isolate, frame, live_wasm_code);
  }
  CheckNoArchivedThreads(isolate);
  // Flush the code lookup cache, since it may refer to some code we
  // are going to release.
  GetWasmCodeManager()->FlushCodeLookupCache(isolate);
  ReportLiveCodeForGC(isolate, live_wasm_code);
}
References v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::CheckNoArchivedThreads(), v8::internal::StackFrameIteratorBase::done(), v8::internal::wasm::WasmCodeManager::FlushCodeLookupCache(), v8::internal::wasm::GetWasmCodeManager(), ReportLiveCodeForGC(), v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::ReportLiveCodeFromFrameForGC(), v8::internal::stack, and v8::internal::Isolate::thread_local_top().
Referenced by v8::internal::StackGuard::HandleInterrupts(), and v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::WasmGCForegroundTask::RunInternal().
SampleTopTierCodeSizeInAllIsolates()
void v8::internal::wasm::WasmEngine::SampleTopTierCodeSizeInAllIsolates (const std::shared_ptr< NativeModule > &)
set_had_nondeterminism()
static void v8::internal::wasm::WasmEngine::set_had_nondeterminism () [inline], [static]
Definition at line 431 of file wasm-engine.h.
                                       {
    had_nondeterminism_.store(1, std::memory_order_relaxed);
  }
Referenced by v8::internal::WasmMemoryObject::Grow().
StartStreamingCompilation()
std::shared_ptr< StreamingDecoder > v8::internal::wasm::WasmEngine::StartStreamingCompilation (Isolate * isolate, WasmEnabledFeatures enabled, CompileTimeImports compile_imports, DirectHandle< Context > context, const char * api_method_name, std::shared_ptr< CompilationResultResolver > resolver)
Definition at line 852 of file wasm-engine.cc.
                                                       {
  int compilation_id = next_compilation_id_.fetch_add(1);
  TRACE_EVENT1("v8.wasm", "wasm.StartStreamingCompilation", "id",
               compilation_id);
  if (v8_flags.wasm_async_compilation) {
    AsyncCompileJob* job = CreateAsyncCompileJob(
        isolate, enabled, std::move(compile_imports), {}, context,
        api_method_name, std::move(resolver), compilation_id);
    return job->CreateStreamingDecoder();
  }
  return StreamingDecoder::CreateSyncStreamingDecoder(
      isolate, enabled, std::move(compile_imports), context, api_method_name,
      std::move(resolver));
}
References CreateAsyncCompileJob(), v8::internal::wasm::AsyncCompileJob::CreateStreamingDecoder(), v8::internal::wasm::StreamingDecoder::CreateSyncStreamingDecoder(), next_compilation_id_, TRACE_EVENT1, and v8::internal::v8_flags.
Referenced by AsyncCompile().
StreamingCompilationFailed()
void v8::internal::wasm::WasmEngine::StreamingCompilationFailed (size_t prefix_hash, const CompileTimeImports & compile_imports)
Definition at line 1686 of file wasm-engine.cc.
                                                                   {
  native_module_cache_.StreamingCompilationFailed(prefix_hash, compile_imports);
}
References native_module_cache_, and v8::internal::wasm::NativeModuleCache::StreamingCompilationFailed().
Referenced by v8::internal::wasm::AsyncStreamingProcessor::OnAbort(), and v8::internal::wasm::AsyncStreamingProcessor::OnFinishedStream().
SyncCompile()
MaybeDirectHandle< WasmModuleObject > v8::internal::wasm::WasmEngine::SyncCompile (Isolate * isolate, WasmEnabledFeatures enabled, CompileTimeImports compile_imports, ErrorThrower * thrower, base::OwnedVector< const uint8_t > bytes)
Definition at line 669 of file wasm-engine.cc.
                                          {
  int compilation_id = next_compilation_id_.fetch_add(1);
  TRACE_EVENT1("v8.wasm", "wasm.SyncCompile", "id", compilation_id);
  v8::metrics::Recorder::ContextId context_id =
      isolate->GetOrRegisterRecorderContextId(isolate->native_context());
  std::shared_ptr<WasmModule> module;
  WasmDetectedFeatures detected_features;
  {
    // Normally modules are validated in {CompileToNativeModule} but in jitless
    // mode the only opportunity of validatiom is during decoding.
    bool validate_module = v8_flags.wasm_jitless;
    ModuleResult result = DecodeWasmModule(
        enabled_features, bytes.as_vector(), validate_module, kWasmOrigin,
        isolate->counters(), isolate->metrics_recorder(), context_id,
        DecodingMethod::kSync, &detected_features);
    if (result.failed()) {
      thrower->CompileFailed(result.error());
      return {};
    }
    module = std::move(result).value();
    if (WasmError error =
            ValidateAndSetBuiltinImports(module.get(), bytes.as_vector(),
                                         compile_imports, &detected_features)) {
      thrower->CompileError("%s @+%u", error.message().c_str(), error.offset());
      return {};
    }
  }
  // If experimental PGO via files is enabled, load profile information now.
  std::unique_ptr<ProfileInformation> pgo_info;
  if (V8_UNLIKELY(v8_flags.experimental_wasm_pgo_from_file)) {
    pgo_info = LoadProfileFromFile(module.get(), bytes.as_vector());
  }
  // Transfer ownership of the WasmModule to the {Managed<WasmModule>} generated
  // in {CompileToNativeModule}.
  std::shared_ptr<NativeModule> native_module = CompileToNativeModule(
      isolate, enabled_features, detected_features, std::move(compile_imports),
      thrower, std::move(module), std::move(bytes), compilation_id, context_id,
      pgo_info.get());
  if (!native_module) return {};
#ifdef DEBUG
  // Ensure that code GC will check this isolate for live code.
  {
    base::MutexGuard lock(&mutex_);
    DCHECK_EQ(1, isolates_.count(isolate));
    DCHECK_EQ(1, isolates_[isolate]->native_modules.count(native_module.get()));
    DCHECK_EQ(1, native_modules_.count(native_module.get()));
    DCHECK_EQ(1, native_modules_[native_module.get()]->isolates.count(isolate));
  }
#endif
  constexpr base::Vector<const char> kNoSourceUrl;
  DirectHandle<Script> script =
      GetOrCreateScript(isolate, native_module, kNoSourceUrl);
  native_module->LogWasmCodes(isolate, *script);
  // Create the compiled module object and populate with compiled functions
  // and information needed at instantiation time. This object needs to be
  // serializable. Instantiation may occur off a deserialized version of this
  // object.
  DirectHandle<WasmModuleObject> module_object =
      WasmModuleObject::New(isolate, std::move(native_module), script);
  // Finish the Wasm script now and make it public to the debugger.
  isolate->debug()->OnAfterCompile(script);
  return module_object;
}
References v8::base::OwnedVector< T >::as_vector(), v8::internal::wasm::ErrorThrower::CompileFailed(), v8::internal::wasm::CompileToNativeModule(), v8::internal::Isolate::counters(), DCHECK_EQ, v8::internal::Isolate::debug(), v8::internal::wasm::DecodeWasmModule(), GetOrCreateScript(), v8::internal::Isolate::GetOrRegisterRecorderContextId(), isolates_, v8::internal::wasm::kSync, v8::internal::wasm::kWasmOrigin, v8::internal::wasm::LoadProfileFromFile(), v8::internal::Isolate::metrics_recorder(), mutex_, v8::internal::Isolate::native_context(), native_modules_, v8::internal::WasmModuleObject::New(), next_compilation_id_, v8::internal::Debug::OnAfterCompile(), v8::base::internal::result, v8::internal::script, TRACE_EVENT1, v8::internal::v8_flags, V8_UNLIKELY, and v8::internal::wasm::ValidateAndSetBuiltinImports().
Referenced by AsyncCompile(), v8::WasmModuleObject::Compile(), v8::internal::CreateWasmObject(), v8::internal::wasm::SyncStreamingDecoder::Finish(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyModuleImpl().
SyncCompileTranslatedAsmJs()
MaybeHandle< AsmWasmData > v8::internal::wasm::WasmEngine::SyncCompileTranslatedAsmJs (Isolate * isolate, ErrorThrower * thrower, base::OwnedVector< const uint8_t > bytes, DirectHandle< Script > script, base::Vector< const uint8_t > asm_js_offset_table_bytes, DirectHandle< HeapNumber > uses_bitset, LanguageMode language_mode)
Definition at line 603 of file wasm-engine.cc.
                                                                      {
  int compilation_id = next_compilation_id_.fetch_add(1);
  TRACE_EVENT1("v8.wasm", "wasm.SyncCompileTranslatedAsmJs", "id",
               compilation_id);
  ModuleOrigin origin = language_mode == LanguageMode::kSloppy
                            ? kAsmJsSloppyOrigin
                            : kAsmJsStrictOrigin;
  // TODO(leszeks): If we want asm.js in UKM, we should figure out a way to pass
  // the context id in here.
  v8::metrics::Recorder::ContextId context_id =
      v8::metrics::Recorder::ContextId::Empty();
  WasmDetectedFeatures detected_features;
  ModuleResult result = DecodeWasmModule(
      WasmEnabledFeatures::ForAsmjs(), bytes.as_vector(), false, origin,
      isolate->counters(), isolate->metrics_recorder(), context_id,
      DecodingMethod::kSync, &detected_features);
  if (result.failed()) {
    // This happens once in a while when we have missed some limit check
    // in the asm parser. Output an error message to help diagnose, but crash.
    std::cout << result.error().message();
    UNREACHABLE();
  }
  result.value()->asm_js_offset_information =
      std::make_unique<AsmJsOffsetInformation>(asm_js_offset_table_bytes);
  // Transfer ownership of the WasmModule to the {Managed<WasmModule>} generated
  // in {CompileToNativeModule}.
  constexpr ProfileInformation* kNoProfileInformation = nullptr;
  std::shared_ptr<NativeModule> native_module = CompileToNativeModule(
      isolate, WasmEnabledFeatures::ForAsmjs(), detected_features,
      CompileTimeImports{}, thrower, std::move(result).value(),
      std::move(bytes), compilation_id, context_id, kNoProfileInformation);
  if (!native_module) return {};
  native_module->LogWasmCodes(isolate, *script);
  {
    // Register the script with the isolate. We do this unconditionally for
    // consistency; it is in particular required for logging lazy-compiled code.
    base::MutexGuard guard(&mutex_);
    DCHECK_EQ(1, isolates_.count(isolate));
    auto& scripts = isolates_[isolate]->scripts;
    // If the same asm.js module is instantiated repeatedly, then we
    // deduplicate the NativeModule, so the script exists already.
    if (scripts.count(native_module.get()) == 0) {
      scripts.emplace(native_module.get(), WeakScriptHandle(script, isolate));
    }
  }
  return AsmWasmData::New(isolate, std::move(native_module), uses_bitset);
}
References v8::base::OwnedVector< T >::as_vector(), v8::internal::wasm::CompileToNativeModule(), v8::internal::Isolate::counters(), DCHECK_EQ, v8::internal::wasm::DecodeWasmModule(), v8::metrics::Recorder::ContextId::Empty(), v8::internal::wasm::WasmEnabledFeatures::ForAsmjs(), isolates_, v8::internal::wasm::kAsmJsSloppyOrigin, v8::internal::wasm::kAsmJsStrictOrigin, v8::internal::kSloppy, v8::internal::wasm::kSync, v8::internal::Isolate::metrics_recorder(), mutex_, v8::internal::AsmWasmData::New(), next_compilation_id_, v8::base::internal::result, v8::internal::script, TRACE_EVENT1, and v8::internal::UNREACHABLE().
Referenced by v8::internal::AsmJsCompilationJob::FinalizeJobImpl().
SyncInstantiate()
MaybeDirectHandle< WasmInstanceObject > v8::internal::wasm::WasmEngine::SyncInstantiate (Isolate * isolate, ErrorThrower * thrower, DirectHandle< WasmModuleObject > module_object, MaybeDirectHandle< JSReceiver > imports, MaybeDirectHandle< JSArrayBuffer > memory)
Definition at line 743 of file wasm-engine.cc.
                                             {
  TRACE_EVENT0("v8.wasm", "wasm.SyncInstantiate");
  return InstantiateToInstanceObject(isolate, thrower, module_object, imports,
                                     memory);
}
References v8::internal::wasm::InstantiateToInstanceObject(), and TRACE_EVENT0.
Referenced by AsyncInstantiate(), and v8::internal::CreateWasmObject().
SyncValidate()
bool v8::internal::wasm::WasmEngine::SyncValidate (Isolate * isolate, WasmEnabledFeatures enabled, CompileTimeImports compile_imports, base::Vector< const uint8_t > bytes)
Definition at line 585 of file wasm-engine.cc.
                                                               {
  TRACE_EVENT0("v8.wasm", "wasm.SyncValidate");
  if (bytes.empty()) return false;
  WasmDetectedFeatures unused_detected_features;
  auto result = DecodeWasmModule(
      enabled, bytes, true, kWasmOrigin, isolate->counters(),
      isolate->metrics_recorder(),
      isolate->GetOrRegisterRecorderContextId(isolate->native_context()),
      DecodingMethod::kSync, &unused_detected_features);
  if (result.failed()) return false;
  WasmError error = ValidateAndSetBuiltinImports(
      result.value().get(), bytes, compile_imports, &unused_detected_features);
  return !error.has_error();
}
References v8::internal::Isolate::counters(), v8::internal::wasm::DecodeWasmModule(), v8::base::Vector< T >::empty(), v8::internal::Isolate::GetOrRegisterRecorderContextId(), v8::internal::wasm::WasmError::has_error(), v8::internal::wasm::kSync, v8::internal::wasm::kWasmOrigin, v8::internal::Isolate::metrics_recorder(), v8::internal::Isolate::native_context(), v8::base::internal::result, TRACE_EVENT0, and v8::internal::wasm::ValidateAndSetBuiltinImports().
Referenced by v8::anonymous_namespace{wasm-js.cc}::WebAssemblyValidateImpl().
TriggerCodeGC_Locked()
void v8::internal::wasm::WasmEngine::TriggerCodeGC_Locked (size_t dead_code_limit) [private]
Definition at line 1839 of file wasm-engine.cc.
                                                            {
  bool inc_gc_count =
      num_code_gcs_triggered_ < std::numeric_limits<int8_t>::max();
  if (current_gc_info_ == nullptr) {
    if (inc_gc_count) ++num_code_gcs_triggered_;
    TRACE_CODE_GC(
        "Triggering GC (potentially dead: %zu bytes; limit: %zu bytes).\n",
        new_potentially_dead_code_size_, dead_code_limit);
    TriggerGC(num_code_gcs_triggered_);
  } else if (current_gc_info_->next_gc_sequence_index == 0) {
    if (inc_gc_count) ++num_code_gcs_triggered_;
    TRACE_CODE_GC(
        "Scheduling another GC after the current one (potentially dead: "
        "%zu bytes; limit: %zu bytes).\n",
        new_potentially_dead_code_size_, dead_code_limit);
    current_gc_info_->next_gc_sequence_index = num_code_gcs_triggered_;
    DCHECK_NE(0, current_gc_info_->next_gc_sequence_index);
  }
}
References current_gc_info_, DCHECK_NE, new_potentially_dead_code_size_, num_code_gcs_triggered_, TRACE_CODE_GC, and TriggerGC().
Referenced by AddPotentiallyDeadCode(), and TriggerCodeGCForTesting().
TriggerCodeGCForTesting()
void v8::internal::wasm::WasmEngine::TriggerCodeGCForTesting ()
Definition at line 1859 of file wasm-engine.cc.
                                         {
  if (!v8_flags.wasm_code_gc) return;
  base::MutexGuard guard(&mutex_);
  TRACE_CODE_GC("Wasm Code GC explicitly requested for testing:\n");
  if (new_potentially_dead_code_size_ == 0) {
    DCHECK(potentially_dead_code_.empty());
    // Let's not waste a GC sequence index when there is no code to free.
    TRACE_CODE_GC("But there is nothing to do.\n");
    return;
  }
  TriggerCodeGC_Locked(0);
}
References v8::internal::DCHECK(), mutex_, new_potentially_dead_code_size_, potentially_dead_code_, TRACE_CODE_GC, TriggerCodeGC_Locked(), and v8::internal::v8_flags.
Referenced by v8::internal::RUNTIME_FUNCTION().
TriggerGC()
void v8::internal::wasm::WasmEngine::TriggerGC (int8_t gc_sequence_index) [private]
Definition at line 1930 of file wasm-engine.cc.
                                                   {
  mutex_.AssertHeld();
  DCHECK_NULL(current_gc_info_);
  DCHECK(v8_flags.wasm_code_gc);
  new_potentially_dead_code_size_ = 0;
  current_gc_info_.reset(new CurrentGCInfo(gc_sequence_index));
  // Add all potentially dead code to this GC, and trigger a GC task in each
  // known isolate. We can't limit the isolates to those that contributed
  // potentially-dead WasmCode objects, because wrappers don't point back
  // at a NativeModule or Isolate.
  for (WasmCode* code : potentially_dead_code_) {
    current_gc_info_->dead_code.insert(code);
  }
  for (const auto& entry : isolates_) {
    Isolate* isolate = entry.first;
    auto& gc_task = current_gc_info_->outstanding_isolates[isolate];
    if (!gc_task) {
      auto new_task = std::make_unique<WasmGCForegroundTask>(isolate);
      gc_task = new_task.get();
      DCHECK_EQ(1, isolates_.count(isolate));
      isolates_[isolate]->foreground_task_runner->PostTask(std::move(new_task));
    }
    isolate->stack_guard()->RequestWasmCodeGC();
  }
  TRACE_CODE_GC(
      "Starting GC (nr %d). Number of potentially dead code objects: %zu\n",
      current_gc_info_->gc_sequence_index, current_gc_info_->dead_code.size());
  // Ensure that there are outstanding isolates that will eventually finish this
  // GC. If there are no outstanding isolates, we finish the GC immediately.
  PotentiallyFinishCurrentGC();
  DCHECK(current_gc_info_ == nullptr ||
         !current_gc_info_->outstanding_isolates.empty());
}
References v8::base::Mutex::AssertHeld(), code, current_gc_info_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NULL, isolates_, mutex_, new_potentially_dead_code_size_, potentially_dead_code_, PotentiallyFinishCurrentGC(), v8::internal::Isolate::stack_guard(), TRACE_CODE_GC, and v8::internal::v8_flags.
Referenced by PotentiallyFinishCurrentGC(), and TriggerCodeGC_Locked().
type_canonicalizer()
TypeCanonicalizer* v8::internal::wasm::WasmEngine::type_canonicalizer () [inline]
Definition at line 392 of file wasm-engine.h.
{ return &type_canonicalizer_; }
Referenced by v8::internal::WasmJSFunctionData::GetSignature(), v8::internal::wasm::GetTypeCanonicalizer(), v8::internal::wasm::JSToWasmObject(), v8::internal::WasmTableObject::UpdateDispatchTable(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTagImpl().
UpdateNativeModuleCache()
std::shared_ptr< NativeModule > v8::internal::wasm::WasmEngine::UpdateNativeModuleCache (bool has_error, std::shared_ptr< NativeModule > native_module, Isolate * isolate)
Definition at line 1639 of file wasm-engine.cc.
                      {
  // Keep the previous pointer, but as a `void*`, because we only want to use it
  // later to compare pointers, and never need to dereference it.
  void* prev = native_module.get();
  native_module =
      native_module_cache_.Update(std::move(native_module), has_error);
  if (prev == native_module.get()) return native_module;
  bool remove_all_code = false;
  {
    base::MutexGuard guard(&mutex_);
    DCHECK_EQ(1, native_modules_.count(native_module.get()));
    native_modules_[native_module.get()]->isolates.insert(isolate);
    DCHECK_EQ(1, isolates_.count(isolate));
    auto* isolate_data = isolates_[isolate].get();
    isolate_data->native_modules.insert(native_module.get());
    if (isolate_data->keep_in_debug_state && !native_module->IsInDebugState()) {
      remove_all_code = true;
      native_module->SetDebugState(kDebugging);
    }
    if (isolate_data->log_codes && !native_module->log_code()) {
      EnableCodeLogging(native_module.get());
    }
  }
  if (remove_all_code) {
    WasmCodeRefScope ref_scope;
    native_module->RemoveCompiledCode(
        NativeModule::RemoveFilter::kRemoveNonDebugCode);
  }
  return native_module;
}
References DCHECK_EQ, EnableCodeLogging(), isolates_, v8::internal::wasm::kDebugging, v8::internal::wasm::NativeModule::kRemoveNonDebugCode, mutex_, native_module_cache_, native_modules_, and v8::internal::wasm::NativeModuleCache::Update().
Referenced by v8::internal::wasm::AsyncCompileJob::CompilationStateCallback::call(), v8::internal::wasm::DeserializeNativeModule(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::GetOrCompileNewNativeModule(), and v8::internal::wasm::AsyncStreamingProcessor::OnFinishedStream().
Member Data Documentation
allocator_
AccountingAllocator v8::internal::wasm::WasmEngine::allocator_ [private]
Definition at line 481 of file wasm-engine.h.
async_compile_jobs_
std::unordered_map<AsyncCompileJob*, std::unique_ptr<AsyncCompileJob> > v8::internal::wasm::WasmEngine::async_compile_jobs_ [private]
Definition at line 507 of file wasm-engine.h.
Referenced by CreateAsyncCompileJob(), DeleteCompileJobsOnContext(), DeleteCompileJobsOnIsolate(), EstimateCurrentMemoryConsumption(), HasRunningCompileJob(), RemoveCompileJob(), and ~WasmEngine().
call_descriptors_
compiler::WasmCallDescriptors v8::internal::wasm::WasmEngine::call_descriptors_ [private]
Definition at line 495 of file wasm-engine.h.
code_tracer_
std::unique_ptr<CodeTracer> v8::internal::wasm::WasmEngine::code_tracer_ [private]
Definition at line 510 of file wasm-engine.h.
Referenced by GetCodeTracer().
compilation_stats_
std::shared_ptr<CompilationStatistics> v8::internal::wasm::WasmEngine::compilation_stats_ [private]
Definition at line 509 of file wasm-engine.h.
Referenced by DumpAndResetTurboStatistics(), DumpTurboStatistics(), and GetOrCreateTurboStatistics().
current_gc_info_
std::unique_ptr<CurrentGCInfo> v8::internal::wasm::WasmEngine::current_gc_info_ [private]
Definition at line 538 of file wasm-engine.h.
Referenced by EstimateCurrentMemoryConsumption(), FreeNativeModule(), PotentiallyFinishCurrentGC(), RemoveIsolate(), RemoveIsolateFromCurrentGC(), ReportLiveCodeForGC(), TriggerCodeGC_Locked(), and TriggerGC().
deopts_executed_
std::atomic<int> v8::internal::wasm::WasmEngine::deopts_executed_ {0} [private]
Definition at line 491 of file wasm-engine.h.
Referenced by GetDeoptsExecutedCount(), and IncrementDeoptsExecutedCount().
had_nondeterminism_
std::atomic< int32_t > v8::internal::wasm::WasmEngine::had_nondeterminism_ {0} [static], [private]
Definition at line 479 of file wasm-engine.h.
isolates_
std::unordered_map<Isolate*, std::unique_ptr<IsolateInfo> > v8::internal::wasm::WasmEngine::isolates_ [private]
Definition at line 513 of file wasm-engine.h.
Referenced by AddIsolate(), ClearWeakScriptHandle(), DeleteCompileJobsOnIsolate(), EnableCodeLogging(), EnterDebuggingForIsolate(), EstimateCurrentMemoryConsumption(), FreeNativeModule(), GetOrCreateScript(), HasRunningCompileJob(), ImportNativeModule(), LeaveDebuggingForIsolate(), LogCode(), LogOutstandingCodesForIsolate(), LogWrapperCode(), MaybeGetNativeModule(), NewNativeModule(), RemoveIsolate(), SyncCompile(), SyncCompileTranslatedAsmJs(), TriggerGC(), UpdateNativeModuleCache(), and ~WasmEngine().
mutex_
base::Mutex v8::internal::wasm::WasmEngine::mutex_ [mutable], [private]
Definition at line 499 of file wasm-engine.h.
Referenced by AddIsolate(), AddPotentiallyDeadCode(), ClearWeakScriptHandle(), CreateAsyncCompileJob(), DecodeAllNameSections(), DeleteCompileJobsOnContext(), DeleteCompileJobsOnIsolate(), DisableCodeLogging(), DumpAndResetTurboStatistics(), DumpTurboStatistics(), EnableCodeLogging(), EnterDebuggingForIsolate(), EstimateCurrentMemoryConsumption(), FlushLiftoffCode(), FreeDeadCode(), FreeDeadCodeLocked(), FreeNativeModule(), GetCodeTracer(), GetLiftoffCodeSizeForTesting(), GetOrCreateScript(), GetOrCreateTurboStatistics(), HasRunningCompileJob(), ImportNativeModule(), LeaveDebuggingForIsolate(), LogCode(), LogOutstandingCodesForIsolate(), LogWrapperCode(), MaybeGetNativeModule(), NativeModuleCount(), NewNativeModule(), PotentiallyFinishCurrentGC(), RemoveCompileJob(), RemoveIsolate(), RemoveIsolateFromCurrentGC(), ReportLiveCodeForGC(), SyncCompile(), SyncCompileTranslatedAsmJs(), TriggerCodeGCForTesting(), TriggerGC(), and UpdateNativeModuleCache().
native_module_cache_
NativeModuleCache v8::internal::wasm::WasmEngine::native_module_cache_ [private]
Definition at line 540 of file wasm-engine.h.
Referenced by FreeNativeModule(), GetStreamingCompilationOwnership(), MaybeGetNativeModule(), StreamingCompilationFailed(), UpdateNativeModuleCache(), and ~WasmEngine().
native_modules_
std::unordered_map<NativeModule*, std::unique_ptr<NativeModuleInfo> > v8::internal::wasm::WasmEngine::native_modules_ [private]
Definition at line 517 of file wasm-engine.h.
Referenced by DecodeAllNameSections(), DeleteCompileJobsOnIsolate(), DisableCodeLogging(), EnableCodeLogging(), EnterDebuggingForIsolate(), EstimateCurrentMemoryConsumption(), FlushLiftoffCode(), FreeNativeModule(), GetLiftoffCodeSizeForTesting(), ImportNativeModule(), LeaveDebuggingForIsolate(), LogCode(), MaybeGetNativeModule(), NativeModuleCount(), NewNativeModule(), RemoveIsolate(), SyncCompile(), UpdateNativeModuleCache(), and ~WasmEngine().
new_potentially_dead_code_size_
size_t v8::internal::wasm::WasmEngine::new_potentially_dead_code_size_ = 0 [private]
Definition at line 529 of file wasm-engine.h.
Referenced by AddPotentiallyDeadCode(), TriggerCodeGC_Locked(), TriggerCodeGCForTesting(), and TriggerGC().
next_compilation_id_
std::atomic<int> v8::internal::wasm::WasmEngine::next_compilation_id_ {0} [private]
Definition at line 488 of file wasm-engine.h.
Referenced by AsyncCompile(), StartStreamingCompilation(), SyncCompile(), and SyncCompileTranslatedAsmJs().
num_code_gcs_triggered_
int8_t v8::internal::wasm::WasmEngine::num_code_gcs_triggered_ = 0 [private]
Definition at line 534 of file wasm-engine.h.
Referenced by TriggerCodeGC_Locked().
num_modules_with_code_logging_
std::atomic<size_t> v8::internal::wasm::WasmEngine::num_modules_with_code_logging_ {0} [private]
Definition at line 525 of file wasm-engine.h.
Referenced by DisableCodeLogging(), EnableCodeLogging(), and LogWrapperCode().
operations_barrier_
std::shared_ptr<OperationsBarrier> v8::internal::wasm::WasmEngine::operations_barrier_ [private]
Initial value:
{
      std::make_shared<OperationsBarrier>()}
Definition at line 519 of file wasm-engine.h.
Referenced by GetBarrierForBackgroundCompile(), and ~WasmEngine().
potentially_dead_code_
std::unordered_set<WasmCode*> v8::internal::wasm::WasmEngine::potentially_dead_code_ [private]
Definition at line 533 of file wasm-engine.h.
Referenced by AddPotentiallyDeadCode(), EstimateCurrentMemoryConsumption(), FreeNativeModule(), PotentiallyFinishCurrentGC(), TriggerCodeGCForTesting(), TriggerGC(), and ~WasmEngine().
type_canonicalizer_
TypeCanonicalizer v8::internal::wasm::WasmEngine::type_canonicalizer_ [private]
Definition at line 493 of file wasm-engine.h.
Referenced by EstimateCurrentMemoryConsumption().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-engine.h
/mnt/V8SourceCode/src/wasm/wasm-engine.cc