v8::internal::torque::AbstractType Class Reference
#include <types.h>
Public Member Functions
const std::string & name () const
std::string ToExplicitString () const override
std::string GetGeneratedTypeNameImpl () const override
std::string GetGeneratedTNodeTypeNameImpl () const override
bool IsConstexpr () const final
const Type * NonConstexprVersion () const override
std::vector< TypeChecker > GetTypeCheckers () const override
size_t AlignmentLog2 () const override
Private Member Functions
AbstractType (const Type *parent, AbstractTypeFlags flags, const std::string &name, const std::string &generated_type, const Type *non_constexpr_version, MaybeSpecializationKey specialized_from)
std::string SimpleNameImpl () const override
bool IsTransient () const override
bool UseParentTypeChecker () const
Private Attributes
AbstractTypeFlags flags_
const std::string name_
const std::string generated_type_
const Type * non_constexpr_version_
Friends
class TypeOracle
Additional Inherited Members
Detailed Description
Definition at line 267 of file types.h.
Constructor & Destructor Documentation
AbstractType()
v8::internal::torque::AbstractType::AbstractType (const Type * parent, AbstractTypeFlags flags, const std::string & name, const std::string & generated_type, const Type * non_constexpr_version, MaybeSpecializationKey specialized_from) [inline], [private]
Definition at line 293 of file types.h.
      : Type(Kind::kAbstractType, parent, specialized_from),
        flags_(flags),
        name_(name),
        generated_type_(generated_type),
        non_constexpr_version_(non_constexpr_version) {
    if (parent) DCHECK_EQ(parent->IsConstexpr(), IsConstexpr());
    DCHECK_EQ(IsConstexprName(name), IsConstexpr());
    DCHECK_IMPLIES(non_constexpr_version_ != nullptr, IsConstexpr());
    DCHECK(!(IsConstexpr() && (flags_ & AbstractTypeFlag::kTransient)));
  }
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, flags_, v8::internal::torque::Type::IsConstexpr(), IsConstexpr(), v8::internal::torque::IsConstexprName(), v8::internal::torque::kTransient, name(), non_constexpr_version_, and v8::internal::torque::Type::parent().
Member Function Documentation
AlignmentLog2()
size_t v8::internal::torque::AbstractType::AlignmentLog2 () const [override], [virtual]
Reimplemented from v8::internal::torque::Type.
Definition at line 1264 of file types.cc.
                                         {
  size_t alignment;
  if (this == TypeOracle::GetTaggedType()) {
    alignment = TargetArchitecture::TaggedSize();
  } else if (this == TypeOracle::GetRawPtrType()) {
    alignment = TargetArchitecture::RawPtrSize();
  } else if (this == TypeOracle::GetExternalPointerType()) {
    alignment = TargetArchitecture::ExternalPointerSize();
  } else if (this == TypeOracle::GetCppHeapPointerType()) {
    alignment = TargetArchitecture::CppHeapPointerSize();
  } else if (this == TypeOracle::GetTrustedPointerType()) {
    alignment = TargetArchitecture::TrustedPointerSize();
  } else if (this == TypeOracle::GetProtectedPointerType()) {
    alignment = TargetArchitecture::ProtectedPointerSize();
  } else if (this == TypeOracle::GetVoidType()) {
    alignment = 1;
  } else if (this == TypeOracle::GetInt8Type()) {
    alignment = kUInt8Size;
  } else if (this == TypeOracle::GetUint8Type()) {
    alignment = kUInt8Size;
  } else if (this == TypeOracle::GetInt16Type()) {
    alignment = kUInt16Size;
  } else if (this == TypeOracle::GetUint16Type()) {
    alignment = kUInt16Size;
  } else if (this == TypeOracle::GetInt32Type()) {
    alignment = kInt32Size;
  } else if (this == TypeOracle::GetUint32Type()) {
    alignment = kInt32Size;
  } else if (this == TypeOracle::GetFloat64Type()) {
    alignment = kDoubleSize;
  } else if (this == TypeOracle::GetIntPtrType()) {
    alignment = TargetArchitecture::RawPtrSize();
  } else if (this == TypeOracle::GetUIntPtrType()) {
    alignment = TargetArchitecture::RawPtrSize();
  } else {
    return Type::AlignmentLog2();
  }
  alignment = std::min(alignment, TargetArchitecture::TaggedSize());
  return base::bits::WhichPowerOfTwo(alignment);
}
References v8::internal::torque::Type::AlignmentLog2(), v8::internal::torque::TargetArchitecture::CppHeapPointerSize(), v8::internal::torque::TargetArchitecture::ExternalPointerSize(), v8::internal::torque::TypeOracle::GetCppHeapPointerType(), v8::internal::torque::TypeOracle::GetExternalPointerType(), v8::internal::torque::TypeOracle::GetFloat64Type(), v8::internal::torque::TypeOracle::GetInt16Type(), v8::internal::torque::TypeOracle::GetInt32Type(), v8::internal::torque::TypeOracle::GetInt8Type(), v8::internal::torque::TypeOracle::GetIntPtrType(), v8::internal::torque::TypeOracle::GetProtectedPointerType(), v8::internal::torque::TypeOracle::GetRawPtrType(), v8::internal::torque::TypeOracle::GetTaggedType(), v8::internal::torque::TypeOracle::GetTrustedPointerType(), v8::internal::torque::TypeOracle::GetUint16Type(), v8::internal::torque::TypeOracle::GetUint32Type(), v8::internal::torque::TypeOracle::GetUint8Type(), v8::internal::torque::TypeOracle::GetUIntPtrType(), v8::internal::torque::TypeOracle::GetVoidType(), v8::internal::kDoubleSize, v8::internal::kInt32Size, v8::internal::kUInt16Size, v8::internal::kUInt8Size, v8::internal::torque::TargetArchitecture::ProtectedPointerSize(), v8::internal::torque::TargetArchitecture::RawPtrSize(), v8::internal::torque::TargetArchitecture::TaggedSize(), v8::internal::torque::TargetArchitecture::TrustedPointerSize(), and v8::base::bits::WhichPowerOfTwo().
GetGeneratedTNodeTypeNameImpl()
std::string v8::internal::torque::AbstractType::GetGeneratedTNodeTypeNameImpl () const [override], [virtual]
Implements v8::internal::torque::Type.
Definition at line 215 of file types.cc.
                                                            {
  if (generated_type_.empty()) return parent()->GetGeneratedTNodeTypeName();
  return generated_type_;
}
GetGeneratedTypeNameImpl()
std::string v8::internal::torque::AbstractType::GetGeneratedTypeNameImpl () const [override], [virtual]
Implements v8::internal::torque::Type.
Definition at line 198 of file types.cc.
                                                       {
  // A special case that is not very well represented by the "generates"
  // syntax in the .tq files: Lazy<T> represents a std::function that
  // produces a TNode of the wrapped type.
  if (std::optional<const Type*> type_wrapped_in_lazy =
          Type::MatchUnaryGeneric(this, TypeOracle::GetLazyGeneric())) {
    DCHECK(!IsConstexpr());
    return "std::function<" + (*type_wrapped_in_lazy)->GetGeneratedTypeName() +
           "()>";
  }
  if (generated_type_.empty()) {
    return parent()->GetGeneratedTypeName();
  }
  return IsConstexpr() ? generated_type_ : "TNode<" + generated_type_ + ">";
}
References DCHECK.
GetTypeCheckers()
std::vector< TypeChecker > v8::internal::torque::AbstractType::GetTypeCheckers () const [override], [virtual]
Reimplemented from v8::internal::torque::Type.
Definition at line 220 of file types.cc.
                                                           {
  if (UseParentTypeChecker()) return parent()->GetTypeCheckers();
  std::string type_name = name();
  if (auto strong_type =
          Type::MatchUnaryGeneric(this, TypeOracle::GetWeakGeneric())) {
    auto strong_runtime_types = (*strong_type)->GetTypeCheckers();
    std::vector<TypeChecker> result;
    for (const TypeChecker& type : strong_runtime_types) {
      // Generic parameter in Weak<T> should have already been checked to
      // extend HeapObject, so it couldn't itself be another weak type.
      DCHECK(type.weak_ref_to.empty());
      result.push_back({type_name, type.type});
    }
    return result;
  }
  return {{type_name, ""}};
}
References DCHECK, name, v8::base::internal::result, v8::internal::string, and v8::internal::tracing::type.
IsConstexpr()
bool v8::internal::torque::AbstractType::IsConstexpr () const [inline], [final], [virtual]
Reimplemented from v8::internal::torque::Type.
Definition at line 274 of file types.h.
                                 {
    const bool is_constexpr = flags_ & AbstractTypeFlag::kConstexpr;
    DCHECK_IMPLIES(non_constexpr_version_ != nullptr, is_constexpr);
    return is_constexpr;
  }
References DCHECK_IMPLIES, flags_, v8::internal::torque::kConstexpr, and non_constexpr_version_.
Referenced by AbstractType(), NonConstexprVersion(), and SimpleNameImpl().
IsTransient()
bool v8::internal::torque::AbstractType::IsTransient () const [inline], [override], [private], [virtual]
Reimplemented from v8::internal::torque::Type.
Definition at line 319 of file types.h.
                                    {
    return flags_ & AbstractTypeFlag::kTransient;
  }
References flags_, and v8::internal::torque::kTransient.
name()
const std::string& v8::internal::torque::AbstractType::name () const [inline]
Definition at line 270 of file types.h.
{ return name_; }
References name_.
Referenced by AbstractType(), SimpleNameImpl(), and ToExplicitString().
NonConstexprVersion()
const Type* v8::internal::torque::AbstractType::NonConstexprVersion () const [inline], [override], [virtual]
Reimplemented from v8::internal::torque::Type.
Definition at line 280 of file types.h.
                                                   {
    if (non_constexpr_version_) return non_constexpr_version_;
    if (!IsConstexpr()) return this;
    if (parent()) return parent()->NonConstexprVersion();
    return nullptr;
  }
References IsConstexpr(), non_constexpr_version_, v8::internal::torque::Type::NonConstexprVersion(), and v8::internal::torque::Type::parent().
Referenced by SimpleNameImpl().
SimpleNameImpl()
std::string v8::internal::torque::AbstractType::SimpleNameImpl () const [inline], [override], [private], [virtual]
Implements v8::internal::torque::Type.
Definition at line 308 of file types.h.
                                            {
    if (IsConstexpr()) {
      const Type* non_constexpr_version = NonConstexprVersion();
      if (non_constexpr_version == nullptr) {
        ReportError("Cannot find non-constexpr type corresponding to ", *this);
      }
      return "constexpr_" + non_constexpr_version->SimpleName();
    }
    return name();
  }
References IsConstexpr(), name(), NonConstexprVersion(), v8::internal::torque::ReportError(), and v8::internal::torque::Type::SimpleName().
ToExplicitString()
std::string v8::internal::torque::AbstractType::ToExplicitString () const [inline], [override], [virtual]
Implements v8::internal::torque::Type.
Definition at line 271 of file types.h.
{ return name(); }
References name().
UseParentTypeChecker()
bool v8::internal::torque::AbstractType::UseParentTypeChecker () const [inline], [private]
Definition at line 323 of file types.h.
                                    {
    return flags_ & AbstractTypeFlag::kUseParentTypeChecker;
  }
References flags_, and v8::internal::torque::kUseParentTypeChecker.
Friends And Related Function Documentation
TypeOracle
friend class TypeOracle [friend]
Definition at line 292 of file types.h.
Member Data Documentation
flags_
AbstractTypeFlags v8::internal::torque::AbstractType::flags_ [private]
Definition at line 327 of file types.h.
Referenced by AbstractType(), IsConstexpr(), IsTransient(), and UseParentTypeChecker().
generated_type_
const std::string v8::internal::torque::AbstractType::generated_type_ [private]
Definition at line 329 of file types.h.
name_
const std::string v8::internal::torque::AbstractType::name_ [private]
Definition at line 328 of file types.h.
Referenced by name().
non_constexpr_version_
const Type* v8::internal::torque::AbstractType::non_constexpr_version_ [private]
Definition at line 330 of file types.h.
Referenced by AbstractType(), IsConstexpr(), and NonConstexprVersion().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/torque/types.h
/mnt/V8SourceCode/src/torque/types.cc