v8::Integer Class Reference
A JavaScript value representing a signed integer.
#include <v8-primitive.h>
Public Member Functions
int64_t Value () const
Static Public Member Functions
static Local< Integer > New (Isolate *isolate, int32_t value)
static Local< Integer > NewFromUnsigned (Isolate *isolate, uint32_t value)
static Integer * Cast (v8::Data *data)
Private Member Functions
Integer ()
Static Private Member Functions
static void CheckCast (v8::Data *that)
Detailed Description
A JavaScript value representing a signed integer.
Definition at line 867 of file v8-primitive.h.
Constructor & Destructor Documentation
Integer()
v8::Integer::Integer () [private]
Member Function Documentation
Cast()
static Integer* v8::Integer::Cast (v8::Data * data) [inline], [static]
Definition at line 872 of file v8-primitive.h.
                                               {
#ifdef V8_ENABLE_CHECKS
    CheckCast(data);
#endif
    return static_cast<Integer*>(data);
  }
CheckCast()
void v8::Integer::CheckCast (v8::Data * that) [static], [private]
Definition at line 3934 of file api.cc.
                                      {
  auto obj = Utils::OpenDirectHandle(that);
  Utils::ApiCheck(i::IsNumber(*obj), "v8::Integer::Cast",
                  "Value is not an Integer");
}
References v8::Utils::ApiCheck(), v8::internal::IsNumber(), and v8::Utils::OpenDirectHandle().
New()
Local< Integer > v8::Integer::New (Isolate * isolate, int32_t value) [static]
Definition at line 9543 of file api.cc.
                                                                {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  if (i::Smi::IsValid(value)) {
    return Utils::IntegerToLocal(
        i::DirectHandle<i::Object>(i::Smi::FromInt(value), i_isolate));
  }
  i::DirectHandle<i::Object> result = i_isolate->factory()->NewNumber(value);
  return Utils::IntegerToLocal(result);
}
References v8::internal::Isolate::factory(), v8::internal::Smi::FromInt(), v8::internal::Smi::IsValid(), v8::internal::FactoryBase< Impl >::NewNumber(), v8::base::internal::result, and v8::internal::value.
Referenced by v8_inspector::InspectedContext::addInternalObject(), v8::anonymous_namespace{d8.cc}::CreateScriptOrigin(), v8_inspector::generateCustomPreview(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::IndexedDebugProxy< T, id, Provider >::IndexedQuery(), v8::ExecArgs::Init(), NewFromUnsigned(), v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::parseAdditionalSerializationParameters(), v8::Shell::PerformanceMark(), v8::ReturnValue< T >::Set(), v8::AsyncHooks::ShellPromiseHook(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyExceptionGetArgImpl(), and v8::Shell::WorkerNew().
NewFromUnsigned()
Local< Integer > v8::Integer::NewFromUnsigned (Isolate * isolate, uint32_t value) [static]
Definition at line 9554 of file api.cc.
                                                            {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  bool fits_into_int32_t = (value & (1 << 31)) == 0;
  if (fits_into_int32_t) {
    return Integer::New(v8_isolate, static_cast<int32_t>(value));
  }
  i::DirectHandle<i::Object> result = i_isolate->factory()->NewNumber(value);
  return Utils::IntegerToLocal(result);
}
References v8::internal::Isolate::factory(), New(), v8::internal::FactoryBase< Impl >::NewNumber(), v8::base::internal::result, and v8::internal::value.
Referenced by v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllSequenceJSArrayHelper(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::AddressValueFromUnsigned(), and v8::ReturnValue< T >::Set().
Value()
int64_t v8::Integer::Value () const
Definition at line 6192 of file api.cc.
                             {
  auto obj = *Utils::OpenDirectHandle(this);
  if (i::IsSmi(obj)) {
    return i::Smi::ToInt(obj);
  } else {
    return static_cast<int64_t>(i::Object::NumberValue(obj));
  }
}
References v8::internal::IsSmi(), v8::internal::Object::NumberValue(), v8::Utils::OpenDirectHandle(), and v8::internal::Smi::ToInt().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-primitive.h
/mnt/V8SourceCode/src/api/api.cc