v8::internal::TrustedPodArray< T > Class Template Reference
#include <fixed-array.h>
Static Public Member Functions
static DirectHandle< TrustedPodArray< T > > New (Isolate *isolate, int length)
static DirectHandle< TrustedPodArray< T > > New (LocalIsolate *isolate, int length)
Additional Inherited Members
Detailed Description
template<class T>
class v8::internal::TrustedPodArray< T >
Definition at line 945 of file fixed-array.h.
Member Function Documentation
New() [1/2]
template<class T >
DirectHandle< TrustedPodArray< T > > v8::internal::TrustedPodArray< T >::New (Isolate * isolate, int length) [static]
Definition at line 904 of file fixed-array-inl.h.
                                                                     {
  int byte_length;
  CHECK(!base::bits::SignedMulOverflow32(length, sizeof(T), &byte_length));
  return Cast<TrustedPodArray<T>>(
      isolate->factory()->NewTrustedByteArray(byte_length));
}
References CHECK, v8::internal::Isolate::factory(), v8::internal::length, v8::internal::FactoryBase< Impl >::NewTrustedByteArray(), and v8::base::bits::SignedMulOverflow32().
Referenced by v8::internal::compiler::anonymous_namespace{code-generator.cc}::CreateInliningPositions(), and v8::internal::maglev::MaglevCodeGenerator::GenerateDeoptimizationData().
New() [2/2]
template<class T >
DirectHandle< TrustedPodArray< T > > v8::internal::TrustedPodArray< T >::New (LocalIsolate * isolate, int length) [static]
Definition at line 914 of file fixed-array-inl.h.
                                                                     {
  int byte_length;
  CHECK(!base::bits::SignedMulOverflow32(length, sizeof(T), &byte_length));
  return Cast<TrustedPodArray<T>>(
      isolate->factory()->NewTrustedByteArray(byte_length));
}
References CHECK, v8::internal::LocalIsolate::factory(), v8::internal::length, v8::internal::FactoryBase< Impl >::NewTrustedByteArray(), and v8::base::bits::SignedMulOverflow32().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/fixed-array.h
/mnt/V8SourceCode/src/objects/fixed-array-inl.h