v8::internal::DictionaryTemplateInfo Class Reference
#include <templates.h>
Static Public Member Functions
static DirectHandle< DictionaryTemplateInfo > Create (Isolate *isolate, const v8::MemorySpan< const std::string_view > &names)
static DirectHandle< JSObject > NewInstance (DirectHandle< NativeContext > context, DirectHandle< DictionaryTemplateInfo > self, const MemorySpan< MaybeLocal< Value >> &property_values)
Detailed Description
Definition at line 332 of file templates.h.
Member Function Documentation
Create()
DirectHandle< DictionaryTemplateInfo > v8::internal::DictionaryTemplateInfo::Create (Isolate * isolate, const v8::MemorySpan< const std::string_view > & names) [static]
Definition at line 201 of file templates.cc.
                                                                       {
  DirectHandle<FixedArray> property_names = isolate->factory()->NewFixedArray(
      static_cast<int>(names.size()), AllocationType::kOld);
  int index = 0;
  uint32_t unused_array_index;
  for (const std::string_view& name : names) {
    DirectHandle<String> internalized_name =
        isolate->factory()->InternalizeString(
            base::Vector<const char>(name.data(), name.length()));
    // Check that property name cannot be used as index.
    CHECK(!internalized_name->AsArrayIndex(&unused_array_index));
    property_names->set(index, *internalized_name);
    ++index;
  }
  return isolate->factory()->NewDictionaryTemplateInfo(property_names);
}
References CHECK, v8::internal::Isolate::factory(), v8::internal::index, v8::internal::Factory::InternalizeString(), v8::internal::kOld, v8::internal::name, v8::internal::Factory::NewDictionaryTemplateInfo(), v8::internal::FactoryBase< Impl >::NewFixedArray(), and v8::MemorySpan< T >::size().
Referenced by v8::DictionaryTemplate::New().
NewInstance()
DirectHandle< JSObject > v8::internal::DictionaryTemplateInfo::NewInstance (DirectHandle< NativeContext > context, DirectHandle< DictionaryTemplateInfo > self, const MemorySpan< MaybeLocal< Value >> & property_values) [static]
Definition at line 246 of file templates.cc.
                                                          {
  Isolate* isolate = Isolate::Current();
  DirectHandle<FixedArray> property_names(self->property_names(), isolate);
  const int property_names_len = property_names->length();
  CHECK_EQ(property_names_len, static_cast<int>(property_values.size()));
  const int num_properties_set = static_cast<int>(std::count_if(
      property_values.begin(), property_values.end(),
      [](const auto& maybe_value) { return !maybe_value.IsEmpty(); }));
  if (V8_UNLIKELY(num_properties_set > JSObject::kMaxInObjectProperties)) {
    return CreateSlowJSObjectWithProperties(
        isolate, property_names, property_values, num_properties_set);
  }
  const bool can_use_map_cache = num_properties_set == property_names_len;
  MaybeDirectHandle<Map> maybe_cached_map;
  if (V8_LIKELY(can_use_map_cache)) {
    maybe_cached_map = TemplateInfo::ProbeInstantiationsCache<Map>(
        isolate, context, self, TemplateInfo::CachingMode::kUnlimited);
  }
  DirectHandle<Map> cached_map;
  if (V8_LIKELY(can_use_map_cache && maybe_cached_map.ToHandle(&cached_map))) {
    DCHECK(!cached_map->is_dictionary_map());
    bool can_use_cached_map = !cached_map->is_deprecated();
    if (V8_LIKELY(can_use_cached_map)) {
      // Verify that the cached map can be reused.
      auto descriptors = handle(cached_map->instance_descriptors(), isolate);
      for (int i = 0; i < static_cast<int>(property_values.size()); ++i) {
        DirectHandle<Object> value =
            Utils::OpenDirectHandle(*property_values[i].ToLocalChecked());
        InternalIndex descriptor{static_cast<size_t>(i)};
        const auto details = descriptors->GetDetails(descriptor);
        if (!Object::FitsRepresentation(*value, details.representation()) ||
            !FieldType::NowContains(descriptors->GetFieldType(descriptor),
                                    value)) {
          can_use_cached_map = false;
          break;
        }
        // Double representation means mutable heap number. In this case we need
        // to allocate a new heap number to put in the dictionary.
        if (details.representation().Equals(Representation::Double())) {
          // We allowed coercion in `FitsRepresentation` above which means that
          // we may deal with a Smi here.
          property_values[i] =
              ToApiHandle<v8::Object>(isolate->factory()->NewHeapNumber(
                  Object::NumberValue(Cast<Number>(*value))));
        }
      }
      if (V8_LIKELY(can_use_cached_map)) {
        // Create the object from the cached map.
        CHECK(!cached_map->is_deprecated());
        CHECK_EQ(context->object_function_prototype(), cached_map->prototype());
        auto object = isolate->factory()->NewJSObjectFromMap(
            cached_map, AllocationType::kYoung);
        DisallowGarbageCollection no_gc;
        for (int i = 0; i < static_cast<int>(property_values.size()); ++i) {
          Local<Value> property_value = property_values[i].ToLocalChecked();
          DirectHandle<Object> value = Utils::OpenDirectHandle(*property_value);
          const FieldIndex index = FieldIndex::ForPropertyIndex(
              *cached_map, i, Representation::Tagged());
          object->FastPropertyAtPut(index, *value,
                                    WriteBarrierMode::SKIP_WRITE_BARRIER);
        }
        return object;
      }
    }
    // A cached map was either deprecated or the descriptors changed in
    // incompatible ways. We clear the cached map and continue with the generic
    // path.
    TemplateInfo::UncacheTemplateInstantiation(
        isolate, context, self, TemplateInfo::CachingMode::kUnlimited);
  }
  // General case: We either don't have a cached map, or it is unusable for the
  // values provided.
  DirectHandle<Map> current_map = isolate->factory()->ObjectLiteralMapFromCache(
      context, num_properties_set);
  DirectHandle<JSObject> object =
      isolate->factory()->NewJSObjectFromMap(current_map);
  int current_property_index = 0;
  for (int i = 0; i < static_cast<int>(property_values.size()); ++i) {
    Local<Value> property_value;
    if (!property_values[i].ToLocal(&property_value)) {
      continue;
    }
    auto name = Cast<String>(handle(property_names->get(i), isolate));
    DirectHandle<Object> value = Utils::OpenDirectHandle(*property_value);
    constexpr PropertyAttributes attributes = PropertyAttributes::NONE;
    constexpr PropertyConstness constness = PropertyConstness::kConst;
    current_map = Map::TransitionToDataProperty(isolate, current_map, name,
                                                value, attributes, constness,
                                                StoreOrigin::kNamed);
    if (current_map->is_dictionary_map()) {
      return CreateSlowJSObjectWithProperties(
          isolate, property_names, property_values, num_properties_set);
    }
    JSObject::MigrateToMap(isolate, object, current_map);
    PropertyDetails details = current_map->GetLastDescriptorDetails(isolate);
    object->WriteToField(InternalIndex(current_property_index), details,
                         *value);
    current_property_index++;
  }
  if (V8_LIKELY(can_use_map_cache)) {
    TemplateInfo::CacheTemplateInstantiation(
        isolate, context, self, TemplateInfo::CachingMode::kUnlimited,
        direct_handle(object->map(), isolate));
  }
  return object;
}
References v8::internal::TemplateInfo::CacheTemplateInstantiation(), CHECK, CHECK_EQ, v8::base::count_if(), v8::internal::anonymous_namespace{templates.cc}::CreateSlowJSObjectWithProperties(), v8::internal::Isolate::Current(), v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::Representation::Double(), v8::internal::Isolate::factory(), v8::internal::Object::FitsRepresentation(), v8::internal::FieldIndex::ForPropertyIndex(), v8::internal::handle(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::kConst, v8::internal::JSObject::kMaxInObjectProperties, v8::internal::kNamed, v8::internal::TemplateInfo::kUnlimited, v8::internal::kYoung, v8::internal::JSObject::MigrateToMap(), v8::internal::name, v8::internal::FactoryBase< Impl >::NewHeapNumber(), v8::internal::Factory::NewJSObjectFromMap(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::NONE, v8::internal::FieldType::NowContains(), v8::internal::Object::NumberValue(), v8::internal::Factory::ObjectLiteralMapFromCache(), v8::Utils::OpenDirectHandle(), v8::internal::SKIP_WRITE_BARRIER, v8::internal::Representation::Tagged(), v8::internal::MaybeDirectHandle< T >::ToHandle(), v8::internal::Map::TransitionToDataProperty(), v8::internal::TemplateInfo::UncacheTemplateInstantiation(), V8_LIKELY, V8_UNLIKELY, and v8::internal::value.
Referenced by v8::DictionaryTemplate::NewInstance().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/templates.h
/mnt/V8SourceCode/src/objects/templates.cc