v8::internal::ProfilerStats Class Reference
#include <profiler-stats.h>
Public Types
enum Reason {
kTickBufferFull
, kIsolateNotLocked
, kSimulatorFillRegistersFailed
, kNoFrameRegion
,
kInCallOrApply
, kNoSymbolizedFrames
, kNullPC
, kNumberOfReasons
 }
Public Member Functions
void AddReason (Reason reason)
void Clear ()
void Print () const
Static Public Member Functions
static ProfilerStats * Instance ()
Private Member Functions
ProfilerStats ()=default
Static Private Member Functions
static const char * ReasonToString (Reason reason)
Private Attributes
std::atomic_int counts_ [Reason::kNumberOfReasons] = {}
Detailed Description
Definition at line 14 of file profiler-stats.h.
Member Enumeration Documentation
Reason
enum v8::internal::ProfilerStats::Reason
Enumerator
kTickBufferFull
kIsolateNotLocked
kSimulatorFillRegistersFailed
kNoFrameRegion
kInCallOrApply
kNoSymbolizedFrames
kNullPC
kNumberOfReasons
Definition at line 16 of file profiler-stats.h.
              {
    // Reasons we fail to record a TickSample.
    kTickBufferFull,
    kIsolateNotLocked,
    // These all generate a TickSample.
    kSimulatorFillRegistersFailed,
    kNoFrameRegion,
    kInCallOrApply,
    kNoSymbolizedFrames,
    kNullPC,
    kNumberOfReasons,
  };
Constructor & Destructor Documentation
ProfilerStats()
v8::internal::ProfilerStats::ProfilerStats () [private], [default]
Member Function Documentation
AddReason()
void v8::internal::ProfilerStats::AddReason (Reason reason)
Definition at line 14 of file profiler-stats.cc.
                                           {
  counts_[reason].fetch_add(1, std::memory_order_relaxed);
}
References counts_.
Referenced by v8::internal::TickSample::GetStackSample(), v8::internal::CpuSampler::SampleStack(), and v8::internal::Symbolizer::SymbolizeTickSample().
Clear()
void v8::internal::ProfilerStats::Clear ()
Definition at line 18 of file profiler-stats.cc.
                          {
  for (int i = 0; i < Reason::kNumberOfReasons; i++) {
    counts_[i].store(0, std::memory_order_relaxed);
  }
}
References counts_, and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by v8::internal::CpuProfile::Print().
Instance()
static ProfilerStats* v8::internal::ProfilerStats::Instance () [inline], [static]
Definition at line 30 of file profiler-stats.h.
                                   {
    static ProfilerStats stats;
    return &stats;
  }
Referenced by v8::internal::TickSample::GetStackSample(), v8::internal::CpuProfile::Print(), v8::internal::CpuSampler::SampleStack(), and v8::internal::Symbolizer::SymbolizeTickSample().
Print()
void v8::internal::ProfilerStats::Print () const
Definition at line 24 of file profiler-stats.cc.
                                {
  base::OS::Print("ProfilerStats:\n");
  for (int i = 0; i < Reason::kNumberOfReasons; i++) {
    base::OS::Print(" %-30s\t\t %d\n", ReasonToString(static_cast<Reason>(i)),
                    counts_[i].load(std::memory_order_relaxed));
  }
}
References counts_, v8::internal::Print(), and ReasonToString().
Referenced by v8::internal::CpuProfile::Print().
ReasonToString()
const char * v8::internal::ProfilerStats::ReasonToString (Reason reason) [static], [private]
Definition at line 33 of file profiler-stats.cc.
                                                       {
  switch (reason) {
    case kTickBufferFull:
      return "kTickBufferFull";
    case kIsolateNotLocked:
      return "kIsolateNotLocked";
    case kSimulatorFillRegistersFailed:
      return "kSimulatorFillRegistersFailed";
    case kNoFrameRegion:
      return "kNoFrameRegion";
    case kInCallOrApply:
      return "kInCallOrApply";
    case kNoSymbolizedFrames:
      return "kNoSymbolizedFrames";
    case kNullPC:
      return "kNullPC";
    case kNumberOfReasons:
      return "kNumberOfReasons";
  }
}
References kInCallOrApply, kIsolateNotLocked, kNoFrameRegion, kNoSymbolizedFrames, kNullPC, kNumberOfReasons, kSimulatorFillRegistersFailed, and kTickBufferFull.
Referenced by Print().
Member Data Documentation
counts_
std::atomic_int v8::internal::ProfilerStats::counts_[Reason::kNumberOfReasons] = {} [private]
Definition at line 43 of file profiler-stats.h.
Referenced by AddReason(), Clear(), and Print().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/profiler/profiler-stats.h
/mnt/V8SourceCode/src/profiler/profiler-stats.cc