v8::internal::compiler::turboshaft::CompareChainNode Class Reference
Public Types
enum class NodeKind : uint8_t { kFlagSetting
, kLogicalCombine
 }
Public Member Functions
CompareChainNode (OpIndex n, FlagsCondition condition)
CompareChainNode (OpIndex n, CompareChainNode *l, CompareChainNode *r)
void SetCondition (FlagsCondition condition)
void MarkRequiresNegation ()
void NegateFlags ()
bool IsLegalFirstCombine () const
bool IsFlagSetting () const
bool IsLogicalCombine () const
OpIndex node () const
FlagsCondition user_condition () const
CompareChainNode * lhs () const
CompareChainNode * rhs () const
Private Attributes
NodeKind node_kind_
FlagsCondition user_condition_
bool requires_negation_ = false
OpIndex node_
CompareChainNode * lhs_ = nullptr
CompareChainNode * rhs_ = nullptr
Detailed Description
Definition at line 1418 of file instruction-selector-arm64.cc.
Member Enumeration Documentation
NodeKind
enum v8::internal::compiler::turboshaft::CompareChainNode::NodeKind : uint8_t [strong]
Enumerator
kFlagSetting
kLogicalCombine
Definition at line 1420 of file instruction-selector-arm64.cc.
: uint8_t { kFlagSetting, kLogicalCombine };
Constructor & Destructor Documentation
CompareChainNode() [1/2]
v8::internal::compiler::turboshaft::CompareChainNode::CompareChainNode (OpIndex n, FlagsCondition condition) [inline], [explicit]
Definition at line 1422 of file instruction-selector-arm64.cc.
      : node_kind_(NodeKind::kFlagSetting),
        user_condition_(condition),
        node_(n) {}
CompareChainNode() [2/2]
v8::internal::compiler::turboshaft::CompareChainNode::CompareChainNode (OpIndex n, CompareChainNode * l, CompareChainNode * r) [inline], [explicit]
Definition at line 1427 of file instruction-selector-arm64.cc.
      : node_kind_(NodeKind::kLogicalCombine), node_(n), lhs_(l), rhs_(r) {
    // Canonicalise the chain with cmps on the right.
    if (lhs_->IsFlagSetting() && !rhs_->IsFlagSetting()) {
      std::swap(lhs_, rhs_);
    }
  }
Member Function Documentation
IsFlagSetting()
bool v8::internal::compiler::turboshaft::CompareChainNode::IsFlagSetting () const [inline]
Definition at line 1457 of file instruction-selector-arm64.cc.
{ return node_kind_ == NodeKind::kFlagSetting; }
Referenced by v8::internal::compiler::turboshaft::CombineFlagSettingOps(), and v8::internal::compiler::turboshaft::FindCompareChain().
IsLegalFirstCombine()
bool v8::internal::compiler::turboshaft::CompareChainNode::IsLegalFirstCombine () const [inline]
Definition at line 1452 of file instruction-selector-arm64.cc.
                                   {
    DCHECK(IsLogicalCombine());
    // We need two cmps feeding the first logic op.
    return lhs_->IsFlagSetting() && rhs_->IsFlagSetting();
  }
References v8::internal::DCHECK().
IsLogicalCombine()
bool v8::internal::compiler::turboshaft::CompareChainNode::IsLogicalCombine () const [inline]
Definition at line 1458 of file instruction-selector-arm64.cc.
                                {
    return node_kind_ == NodeKind::kLogicalCombine;
  }
lhs()
CompareChainNode* v8::internal::compiler::turboshaft::CompareChainNode::lhs () const [inline]
Definition at line 1463 of file instruction-selector-arm64.cc.
                                {
    DCHECK(IsLogicalCombine());
    return lhs_;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::compiler::turboshaft::CombineFlagSettingOps().
MarkRequiresNegation()
void v8::internal::compiler::turboshaft::CompareChainNode::MarkRequiresNegation () [inline]
Definition at line 1441 of file instruction-selector-arm64.cc.
                              {
    if (IsFlagSetting()) {
      NegateFlags();
    } else {
      requires_negation_ = !requires_negation_;
    }
  }
Referenced by v8::internal::compiler::turboshaft::FindCompareChain().
NegateFlags()
void v8::internal::compiler::turboshaft::CompareChainNode::NegateFlags () [inline]
Definition at line 1448 of file instruction-selector-arm64.cc.
                     {
    user_condition_ = NegateFlagsCondition(user_condition_);
    requires_negation_ = false;
  }
References v8::internal::compiler::NegateFlagsCondition().
node()
OpIndex v8::internal::compiler::turboshaft::CompareChainNode::node () const [inline]
Definition at line 1461 of file instruction-selector-arm64.cc.
{ return node_; }
Referenced by v8::internal::compiler::turboshaft::CombineFlagSettingOps().
rhs()
CompareChainNode* v8::internal::compiler::turboshaft::CompareChainNode::rhs () const [inline]
Definition at line 1467 of file instruction-selector-arm64.cc.
                                {
    DCHECK(IsLogicalCombine());
    return rhs_;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::compiler::turboshaft::CombineFlagSettingOps().
SetCondition()
void v8::internal::compiler::turboshaft::CompareChainNode::SetCondition (FlagsCondition condition) [inline]
Definition at line 1434 of file instruction-selector-arm64.cc.
                                              {
    DCHECK(IsLogicalCombine());
    user_condition_ = condition;
    if (requires_negation_) {
      NegateFlags();
    }
  }
References v8::internal::DCHECK().
Referenced by v8::internal::compiler::turboshaft::CombineFlagSettingOps().
user_condition()
FlagsCondition v8::internal::compiler::turboshaft::CompareChainNode::user_condition () const [inline]
Definition at line 1462 of file instruction-selector-arm64.cc.
{ return user_condition_; }
Referenced by v8::internal::compiler::turboshaft::CombineFlagSettingOps().
Member Data Documentation
lhs_
CompareChainNode* v8::internal::compiler::turboshaft::CompareChainNode::lhs_ = nullptr [private]
Definition at line 1477 of file instruction-selector-arm64.cc.
node_
OpIndex v8::internal::compiler::turboshaft::CompareChainNode::node_ [private]
Definition at line 1476 of file instruction-selector-arm64.cc.
node_kind_
NodeKind v8::internal::compiler::turboshaft::CompareChainNode::node_kind_ [private]
Definition at line 1473 of file instruction-selector-arm64.cc.
requires_negation_
bool v8::internal::compiler::turboshaft::CompareChainNode::requires_negation_ = false [private]
Definition at line 1475 of file instruction-selector-arm64.cc.
rhs_
CompareChainNode* v8::internal::compiler::turboshaft::CompareChainNode::rhs_ = nullptr [private]
Definition at line 1478 of file instruction-selector-arm64.cc.
user_condition_
FlagsCondition v8::internal::compiler::turboshaft::CompareChainNode::user_condition_ [private]
Definition at line 1474 of file instruction-selector-arm64.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/arm64/instruction-selector-arm64.cc