v8::internal::interpreter::BytecodeRegisterOptimizer Class Reference
#include <bytecode-register-optimizer.h>
Classes
class BytecodeWriter
class RegisterInfo
Public Types
using TypeHint = BytecodeGenerator::TypeHint
Public Member Functions
BytecodeRegisterOptimizer (Zone *zone, BytecodeRegisterAllocator *register_allocator, int fixed_registers_count, int parameter_count, BytecodeWriter *bytecode_writer)
~BytecodeRegisterOptimizer () override=default
BytecodeRegisterOptimizer (const BytecodeRegisterOptimizer &)=delete
BytecodeRegisterOptimizer & operator= (const BytecodeRegisterOptimizer &)=delete
void DoLdar (Register input)
void DoStar (Register output)
void DoMov (Register input, Register output)
void Flush ()
bool EnsureAllRegistersAreFlushed () const
template<Bytecode bytecode, ImplicitRegisterUse implicit_register_use>
void PrepareForBytecode ()
void PrepareOutputRegister (Register reg)
void PrepareOutputRegisterList (RegisterList reg_list)
Register GetInputRegister (Register reg)
RegisterList GetInputRegisterList (RegisterList reg_list)
void SetVariableInRegister (Variable *var, Register reg)
Variable * GetPotentialVariableInRegister (Register reg)
Variable * GetPotentialVariableInAccumulator ()
bool IsVariableInRegister (Variable *var, Register reg)
TypeHint GetTypeHint (Register reg)
void SetTypeHintForAccumulator (TypeHint hint)
void ResetTypeHintForAccumulator ()
bool IsAccumulatorReset ()
int maxiumum_register_index () const
Private Member Functions
void RegisterAllocateEvent (Register reg) override
void RegisterListAllocateEvent (RegisterList reg_list) override
void RegisterListFreeEvent (RegisterList reg) override
void RegisterFreeEvent (Register reg) override
void RegisterTransfer (RegisterInfo *input, RegisterInfo *output)
void OutputRegisterTransfer (RegisterInfo *input, RegisterInfo *output)
void CreateMaterializedEquivalent (RegisterInfo *info)
RegisterInfo * GetMaterializedEquivalentNotAccumulator (RegisterInfo *info)
void Materialize (RegisterInfo *info)
void AddToEquivalenceSet (RegisterInfo *set_member, RegisterInfo *non_set_member)
void PushToRegistersNeedingFlush (RegisterInfo *reg)
RegisterInfo * GetRegisterInfo (Register reg)
RegisterInfo * GetOrCreateRegisterInfo (Register reg)
RegisterInfo * NewRegisterInfo (Register reg)
void GrowRegisterMap (Register reg)
bool RegisterIsTemporary (Register reg) const
bool RegisterIsObservable (Register reg) const
size_t GetRegisterInfoTableIndex (Register reg) const
Register RegisterFromRegisterInfoTableIndex (size_t index) const
uint32_t NextEquivalenceId ()
void AllocateRegister (RegisterInfo *info)
Zone * zone ()
Static Private Member Functions
static Register OperandToRegister (uint32_t operand)
Private Attributes
const Register accumulator_
RegisterInfo * accumulator_info_
const Register temporary_base_
int max_register_index_
ZoneVector< RegisterInfo * > register_info_table_
int register_info_table_offset_
ZoneDeque< RegisterInfo * > registers_needing_flushed_
uint32_t equivalence_id_
BytecodeWriter * bytecode_writer_
bool flush_required_
Zone * zone_
Static Private Attributes
static const uint32_t kInvalidEquivalenceId = kMaxUInt32
Detailed Description
Definition at line 24 of file bytecode-register-optimizer.h.
Member Typedef Documentation
TypeHint
using v8::internal::interpreter::BytecodeRegisterOptimizer::TypeHint = BytecodeGenerator::TypeHint
Definition at line 28 of file bytecode-register-optimizer.h.
Constructor & Destructor Documentation
BytecodeRegisterOptimizer() [1/2]
v8::internal::interpreter::BytecodeRegisterOptimizer::BytecodeRegisterOptimizer (Zone * zone, BytecodeRegisterAllocator * register_allocator, int fixed_registers_count, int parameter_count, BytecodeWriter * bytecode_writer)
Definition at line 291 of file bytecode-register-optimizer.cc.
    : accumulator_(Register::virtual_accumulator()),
      temporary_base_(fixed_registers_count),
      max_register_index_(fixed_registers_count - 1),
      register_info_table_(zone),
      registers_needing_flushed_(zone),
      equivalence_id_(0),
      bytecode_writer_(bytecode_writer),
      flush_required_(false),
      zone_(zone) {
  register_allocator->set_observer(this);
  // Calculate offset so register index values can be mapped into
  // a vector of register metadata.
  // There is at least one parameter, which is the JS receiver.
  DCHECK_NE(parameter_count, 0);
  int first_slot_index = parameter_count - 1;
  register_info_table_offset_ =
      -Register::FromParameterIndex(first_slot_index).index();
  // Initialize register map for parameters, locals, and the
  // accumulator.
  register_info_table_.resize(register_info_table_offset_ +
                              static_cast<size_t>(temporary_base_.index()));
  for (size_t i = 0; i < register_info_table_.size(); ++i) {
    register_info_table_[i] = zone->New<RegisterInfo>(
        RegisterFromRegisterInfoTableIndex(i), NextEquivalenceId(), true, true);
    DCHECK_EQ(register_info_table_[i]->register_value().index(),
              RegisterFromRegisterInfoTableIndex(i).index());
  }
  accumulator_info_ = GetRegisterInfo(accumulator_);
  DCHECK(accumulator_info_->register_value() == accumulator_);
}
References accumulator_, accumulator_info_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, v8::internal::interpreter::Register::FromParameterIndex(), GetRegisterInfo(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::interpreter::Register::index(), v8::internal::index, v8::internal::Zone::New(), NextEquivalenceId(), register_info_table_, register_info_table_offset_, v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::register_value(), RegisterFromRegisterInfoTableIndex(), v8::internal::interpreter::BytecodeRegisterAllocator::set_observer(), temporary_base_, and zone().
 BytecodeRegisterOptimizer()
v8::internal::interpreter::BytecodeRegisterOptimizer::~BytecodeRegisterOptimizer () [override], [default]
BytecodeRegisterOptimizer() [2/2]
v8::internal::interpreter::BytecodeRegisterOptimizer::BytecodeRegisterOptimizer (const BytecodeRegisterOptimizer &) [delete]
Member Function Documentation
AddToEquivalenceSet()
void v8::internal::interpreter::BytecodeRegisterOptimizer::AddToEquivalenceSet (RegisterInfo * set_member, RegisterInfo * non_set_member) [private]
Definition at line 449 of file bytecode-register-optimizer.cc.
                                                            {
  // Equivalence class is now of size >= 2, so we make sure it will be flushed.
  PushToRegistersNeedingFlush(non_set_member);
  non_set_member->AddToEquivalenceSetOf(set_member);
}
References v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::AddToEquivalenceSetOf(), and PushToRegistersNeedingFlush().
Referenced by RegisterTransfer().
AllocateRegister()
void v8::internal::interpreter::BytecodeRegisterOptimizer::AllocateRegister (RegisterInfo * info) [private]
Definition at line 556 of file bytecode-register-optimizer.cc.
                                                                   {
  info->set_allocated(true);
  if (!info->materialized()) {
    info->MoveToNewEquivalenceSet(NextEquivalenceId(),
                                  MaterializedInfo::kMaterialized);
  }
}
References v8::internal::interpreter::kMaterialized, v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::materialized(), v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::MoveToNewEquivalenceSet(), NextEquivalenceId(), and v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::set_allocated().
Referenced by RegisterAllocateEvent(), and RegisterListAllocateEvent().
CreateMaterializedEquivalent()
void v8::internal::interpreter::BytecodeRegisterOptimizer::CreateMaterializedEquivalent (RegisterInfo * info) [private]
Definition at line 416 of file bytecode-register-optimizer.cc.
                        {
  DCHECK(info->materialized());
  RegisterInfo* unmaterialized = info->GetEquivalentToMaterialize();
  if (unmaterialized) {
    OutputRegisterTransfer(info, unmaterialized);
  }
}
References v8::internal::DCHECK(), v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::GetEquivalentToMaterialize(), v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::materialized(), and OutputRegisterTransfer().
Referenced by PrepareOutputRegister(), and RegisterTransfer().
DoLdar()
void v8::internal::interpreter::BytecodeRegisterOptimizer::DoLdar (Register input) [inline]
Definition at line 53 of file bytecode-register-optimizer.h.
                              {
    // TODO(rmcilroy): Avoid treating accumulator loads as clobbering the
    // accumulator until the value is actually materialized in the accumulator.
    RegisterInfo* input_info = GetRegisterInfo(input);
    RegisterTransfer(input_info, accumulator_info_);
  }
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::LoadAccumulatorWithRegister().
DoMov()
void v8::internal::interpreter::BytecodeRegisterOptimizer::DoMov (Register input, Register output) [inline]
Definition at line 63 of file bytecode-register-optimizer.h.
                                              {
    RegisterInfo* input_info = GetRegisterInfo(input);
    RegisterInfo* output_info = GetRegisterInfo(output);
    RegisterTransfer(input_info, output_info);
  }
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::MoveRegister().
DoStar()
void v8::internal::interpreter::BytecodeRegisterOptimizer::DoStar (Register output) [inline]
Definition at line 59 of file bytecode-register-optimizer.h.
                               {
    RegisterInfo* output_info = GetRegisterInfo(output);
    RegisterTransfer(accumulator_info_, output_info);
  }
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister().
EnsureAllRegistersAreFlushed()
bool v8::internal::interpreter::BytecodeRegisterOptimizer::EnsureAllRegistersAreFlushed () const
Definition at line 339 of file bytecode-register-optimizer.cc.
                                                                   {
  for (RegisterInfo* reg_info : register_info_table_) {
    if (reg_info->needs_flush()) {
      return false;
    } else if (!reg_info->IsOnlyMemberOfEquivalenceSet()) {
      return false;
    } else if (reg_info->allocated() && !reg_info->materialized()) {
      return false;
    }
  }
  return true;
}
References register_info_table_.
Referenced by Flush(), and v8::internal::interpreter::BytecodeArrayBuilder::MarkHandler().
Flush()
void v8::internal::interpreter::BytecodeRegisterOptimizer::Flush ()
Definition at line 352 of file bytecode-register-optimizer.cc.
                                      {
  if (!flush_required_) {
    return;
  }
  // Materialize all live registers and break equivalences.
  for (RegisterInfo* reg_info : registers_needing_flushed_) {
    if (!reg_info->needs_flush()) continue;
    reg_info->set_needs_flush(false);
    reg_info->flush_variable_hint(false);
    reg_info->set_type_hint(TypeHint::kAny);
    RegisterInfo* materialized = reg_info->materialized()
                                     ? reg_info
                                     : reg_info->GetMaterializedEquivalent();
    if (materialized != nullptr) {
      // Walk equivalents of materialized registers, materializing
      // each equivalent register as necessary and placing in their
      // own equivalence set.
      RegisterInfo* equivalent;
      while ((equivalent = materialized->GetEquivalent()) != materialized) {
        if (equivalent->allocated() && !equivalent->materialized()) {
          OutputRegisterTransfer(materialized, equivalent);
        }
        equivalent->MoveToNewEquivalenceSet(NextEquivalenceId(),
                                            MaterializedInfo::kMaterialized,
                                            ResetVariableHint::kDontReset);
        equivalent->set_needs_flush(false);
      }
    } else {
      // Equivalence class containing only unallocated registers.
      DCHECK_NULL(reg_info->GetAllocatedEquivalent());
      reg_info->MoveToNewEquivalenceSet(NextEquivalenceId(),
                                        MaterializedInfo::kNotMaterialized,
                                        ResetVariableHint::kDontReset);
    }
  }
  registers_needing_flushed_.clear();
  DCHECK(EnsureAllRegistersAreFlushed());
  flush_required_ = false;
}
References v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::allocated(), v8::internal::DCHECK(), DCHECK_NULL, EnsureAllRegistersAreFlushed(), flush_required_, v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::GetEquivalent(), v8::internal::interpreter::kDontReset, v8::internal::interpreter::kMaterialized, v8::internal::interpreter::kNotMaterialized, v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::materialized(), v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::MoveToNewEquivalenceSet(), NextEquivalenceId(), OutputRegisterTransfer(), registers_needing_flushed_, and v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::set_needs_flush().
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::Bind(), v8::internal::interpreter::BytecodeArrayBuilder::MarkTryBegin(), and v8::internal::interpreter::BytecodeArrayBuilder::ToBytecodeArray().
GetInputRegister()
Register v8::internal::interpreter::BytecodeRegisterOptimizer::GetInputRegister (Register reg)
Definition at line 513 of file bytecode-register-optimizer.cc.
                                                                 {
  RegisterInfo* reg_info = GetRegisterInfo(reg);
  if (reg_info->materialized()) {
    return reg;
  } else {
    RegisterInfo* equivalent_info =
        GetMaterializedEquivalentNotAccumulator(reg_info);
    return equivalent_info->register_value();
  }
}
References GetMaterializedEquivalentNotAccumulator(), GetRegisterInfo(), v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::materialized(), and v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::register_value().
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::GetInputOutputRegisterOperand(), GetInputRegisterList(), and v8::internal::interpreter::BytecodeArrayBuilder::GetInputRegisterOperand().
GetInputRegisterList()
RegisterList v8::internal::interpreter::BytecodeRegisterOptimizer::GetInputRegisterList (RegisterList reg_list)
Definition at line 524 of file bytecode-register-optimizer.cc.
                           {
  if (reg_list.register_count() == 1) {
    // If there is only a single register, treat it as a normal input register.
    Register reg(GetInputRegister(reg_list.first_register()));
    return RegisterList(reg);
  } else {
    int start_index = reg_list.first_register().index();
    for (int i = 0; i < reg_list.register_count(); ++i) {
      Register current(start_index + i);
      RegisterInfo* input_info = GetRegisterInfo(current);
      Materialize(input_info);
    }
    return reg_list;
  }
}
References v8::internal::interpreter::RegisterList::first_register(), GetInputRegister(), GetRegisterInfo(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::interpreter::Register::index(), Materialize(), and v8::internal::interpreter::RegisterList::register_count().
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::GetInputRegisterListOperand().
GetMaterializedEquivalentNotAccumulator()
BytecodeRegisterOptimizer::RegisterInfo * v8::internal::interpreter::BytecodeRegisterOptimizer::GetMaterializedEquivalentNotAccumulator (RegisterInfo * info) [private]
Definition at line 426 of file bytecode-register-optimizer.cc.
                        {
  if (info->materialized()) {
    return info;
  }
  RegisterInfo* result = info->GetMaterializedEquivalentOtherThan(accumulator_);
  if (result == nullptr) {
    Materialize(info);
    result = info;
  }
  DCHECK(result->register_value() != accumulator_);
  return result;
}
References accumulator_, v8::internal::DCHECK(), v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::GetMaterializedEquivalentOtherThan(), Materialize(), v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::materialized(), and v8::base::internal::result.
Referenced by GetInputRegister().
GetOrCreateRegisterInfo()
RegisterInfo* v8::internal::interpreter::BytecodeRegisterOptimizer::GetOrCreateRegisterInfo (Register reg) [inline], [private]
Definition at line 172 of file bytecode-register-optimizer.h.
                                                      {
    size_t index = GetRegisterInfoTableIndex(reg);
    return index < register_info_table_.size() ? register_info_table_[index]
                                               : NewRegisterInfo(reg);
  }
References v8::internal::index.
Referenced by RegisterAllocateEvent().
GetPotentialVariableInAccumulator()
Variable* v8::internal::interpreter::BytecodeRegisterOptimizer::GetPotentialVariableInAccumulator () [inline]
Definition at line 128 of file bytecode-register-optimizer.h.
                                                {
    return GetPotentialVariableInRegister(accumulator_);
  }
Referenced by v8::internal::interpreter::BytecodeGenerator::GetPotentialVariableInAccumulator().
GetPotentialVariableInRegister()
Variable * v8::internal::interpreter::BytecodeRegisterOptimizer::GetPotentialVariableInRegister (Register reg)
Definition at line 173 of file bytecode-register-optimizer.cc.
                  {
  RegisterInfo* info = GetRegisterInfo(reg);
  return info->variable_hint().variable;
}
References GetRegisterInfo(), v8::internal::interpreter::VariableHint::variable, and v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::variable_hint().
GetRegisterInfo()
RegisterInfo* v8::internal::interpreter::BytecodeRegisterOptimizer::GetRegisterInfo (Register reg) [inline], [private]
Definition at line 167 of file bytecode-register-optimizer.h.
                                              {
    size_t index = GetRegisterInfoTableIndex(reg);
    DCHECK_LT(index, register_info_table_.size());
    return register_info_table_[index];
  }
References DCHECK_LT, and v8::internal::index.
Referenced by BytecodeRegisterOptimizer(), GetInputRegister(), GetInputRegisterList(), GetPotentialVariableInRegister(), GetTypeHint(), IsVariableInRegister(), PrepareOutputRegister(), RegisterFreeEvent(), RegisterListAllocateEvent(), RegisterListFreeEvent(), and SetVariableInRegister().
GetRegisterInfoTableIndex()
size_t v8::internal::interpreter::BytecodeRegisterOptimizer::GetRegisterInfoTableIndex (Register reg) const [inline], [private]
Definition at line 198 of file bytecode-register-optimizer.h.
                                                       {
    return static_cast<size_t>(reg.index() + register_info_table_offset_);
  }
References v8::internal::interpreter::Register::index().
Referenced by GrowRegisterMap().
GetTypeHint()
TypeHint v8::internal::interpreter::BytecodeRegisterOptimizer::GetTypeHint (Register reg)
Definition at line 188 of file bytecode-register-optimizer.cc.
                                                            {
  RegisterInfo* info = GetRegisterInfo(reg);
  return info->type_hint();
}
References GetRegisterInfo(), and v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::type_hint().
Referenced by v8::internal::interpreter::BytecodeGenerator::GetTypeHintForLocalVariable().
GrowRegisterMap()
void v8::internal::interpreter::BytecodeRegisterOptimizer::GrowRegisterMap (Register reg) [private]
Definition at line 541 of file bytecode-register-optimizer.cc.
                                                            {
  DCHECK(RegisterIsTemporary(reg));
  size_t index = GetRegisterInfoTableIndex(reg);
  if (index >= register_info_table_.size()) {
    size_t new_size = index + 1;
    size_t old_size = register_info_table_.size();
    register_info_table_.resize(new_size);
    for (size_t i = old_size; i < new_size; ++i) {
      register_info_table_[i] =
          zone()->New<RegisterInfo>(RegisterFromRegisterInfoTableIndex(i),
                                    NextEquivalenceId(), true, false);
    }
  }
}
References v8::internal::DCHECK(), GetRegisterInfoTableIndex(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::Zone::New(), NextEquivalenceId(), register_info_table_, RegisterFromRegisterInfoTableIndex(), RegisterIsTemporary(), and zone().
Referenced by RegisterListAllocateEvent().
IsAccumulatorReset()
bool v8::internal::interpreter::BytecodeRegisterOptimizer::IsAccumulatorReset ()
Definition at line 205 of file bytecode-register-optimizer.cc.
                                                   {
  return accumulator_info_->type_hint() == TypeHint::kAny;
}
References accumulator_info_, and v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::type_hint().
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::MarkHandler().
IsVariableInRegister()
bool v8::internal::interpreter::BytecodeRegisterOptimizer::IsVariableInRegister (Variable * var, Register reg)
Definition at line 179 of file bytecode-register-optimizer.cc.
                                                                   {
  DCHECK_NOT_NULL(var);
  RegisterInfo* info = GetRegisterInfo(reg);
  VariableHint hint = info->variable_hint();
  return hint.mode == VariableHintMode::kDefinitelyHasVariable &&
         hint.variable == var;
}
References DCHECK_NOT_NULL, GetRegisterInfo(), v8::internal::interpreter::kDefinitelyHasVariable, v8::internal::interpreter::VariableHint::mode, v8::internal::interpreter::VariableHint::variable, and v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::variable_hint().
Referenced by v8::internal::interpreter::BytecodeGenerator::IsVariableInRegister().
Materialize()
void v8::internal::interpreter::BytecodeRegisterOptimizer::Materialize (RegisterInfo * info) [private]
Definition at line 441 of file bytecode-register-optimizer.cc.
                                                              {
  if (!info->materialized()) {
    RegisterInfo* materialized = info->GetMaterializedEquivalent();
    DCHECK_NOT_NULL(materialized);
    OutputRegisterTransfer(materialized, info);
  }
}
References DCHECK_NOT_NULL, v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::GetMaterializedEquivalent(), v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::materialized(), and OutputRegisterTransfer().
Referenced by GetInputRegisterList(), and GetMaterializedEquivalentNotAccumulator().
maxiumum_register_index()
int v8::internal::interpreter::BytecodeRegisterOptimizer::maxiumum_register_index () const [inline]
Definition at line 140 of file bytecode-register-optimizer.h.
{ return max_register_index_; }
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::ToBytecodeArray().
NewRegisterInfo()
RegisterInfo* v8::internal::interpreter::BytecodeRegisterOptimizer::NewRegisterInfo (Register reg) [inline], [private]
Definition at line 177 of file bytecode-register-optimizer.h.
                                              {
    size_t index = GetRegisterInfoTableIndex(reg);
    DCHECK_GE(index, register_info_table_.size());
    GrowRegisterMap(reg);
    return register_info_table_[index];
  }
References DCHECK_GE, and v8::internal::index.
NextEquivalenceId()
uint32_t v8::internal::interpreter::BytecodeRegisterOptimizer::NextEquivalenceId () [inline], [private]
Definition at line 206 of file bytecode-register-optimizer.h.
                               {
    equivalence_id_++;
    CHECK_NE(equivalence_id_, kInvalidEquivalenceId);
    return equivalence_id_;
  }
References CHECK_NE.
Referenced by AllocateRegister(), BytecodeRegisterOptimizer(), Flush(), GrowRegisterMap(), and PrepareOutputRegister().
OperandToRegister()
static Register v8::internal::interpreter::BytecodeRegisterOptimizer::OperandToRegister (uint32_t operand) [inline], [static], [private]
Definition at line 194 of file bytecode-register-optimizer.h.
                                                      {
    return Register::FromOperand(static_cast<int32_t>(operand));
  }
References v8::internal::interpreter::Register::FromOperand().
operator=()
BytecodeRegisterOptimizer& v8::internal::interpreter::BytecodeRegisterOptimizer::operator= (const BytecodeRegisterOptimizer &) [delete]
OutputRegisterTransfer()
void v8::internal::interpreter::BytecodeRegisterOptimizer::OutputRegisterTransfer (RegisterInfo * input, RegisterInfo * output) [private]
Definition at line 397 of file bytecode-register-optimizer.cc.
                                                         {
  Register input = input_info->register_value();
  Register output = output_info->register_value();
  DCHECK_NE(input.index(), output.index());
  if (input == accumulator_) {
    bytecode_writer_->EmitStar(output);
  } else if (output == accumulator_) {
    bytecode_writer_->EmitLdar(input);
  } else {
    bytecode_writer_->EmitMov(input, output);
  }
  if (output != accumulator_) {
    max_register_index_ = std::max(max_register_index_, output.index());
  }
  output_info->set_materialized(true);
}
References accumulator_, bytecode_writer_, DCHECK_NE, v8::internal::interpreter::BytecodeRegisterOptimizer::BytecodeWriter::EmitLdar(), v8::internal::interpreter::BytecodeRegisterOptimizer::BytecodeWriter::EmitMov(), v8::internal::interpreter::BytecodeRegisterOptimizer::BytecodeWriter::EmitStar(), v8::internal::interpreter::Register::index(), max_register_index_, v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::register_value(), and v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::set_materialized().
Referenced by CreateMaterializedEquivalent(), Flush(), Materialize(), and RegisterTransfer().
PrepareForBytecode()
template<Bytecode bytecode, ImplicitRegisterUse implicit_register_use>
void v8::internal::interpreter::BytecodeRegisterOptimizer::PrepareForBytecode () [inline]
Definition at line 75 of file bytecode-register-optimizer.h.
                                      {
    if (Bytecodes::IsJump(bytecode) || Bytecodes::IsSwitch(bytecode) ||
        bytecode == Bytecode::kDebugger ||
        bytecode == Bytecode::kSuspendGenerator ||
        bytecode == Bytecode::kResumeGenerator) {
      // All state must be flushed before emitting
      // - a jump bytecode (as the register equivalents at the jump target
      // aren't known)
      // - a switch bytecode (as the register equivalents at the switch targets
      // aren't known)
      // - a call to the debugger (as it can manipulate locals and parameters),
      // - a generator suspend (as this involves saving all registers).
      // - a generator register restore.
      Flush();
    }
    // Materialize the accumulator if it is read by the bytecode. The
    // accumulator is special and no other register can be materialized
    // in it's place.
    if (BytecodeOperands::ReadsAccumulator(implicit_register_use)) {
      Materialize(accumulator_info_);
    }
    // Materialize an equivalent to the accumulator if it will be
    // clobbered when the bytecode is dispatched.
    if (BytecodeOperands::WritesOrClobbersAccumulator(implicit_register_use)) {
      PrepareOutputRegister(accumulator_);
      DCHECK_EQ(GetTypeHint(accumulator_), TypeHint::kAny);
    }
  }
References DCHECK_EQ, v8::internal::interpreter::Bytecodes::IsJump(), v8::internal::interpreter::Bytecodes::IsSwitch(), v8::internal::interpreter::BytecodeOperands::ReadsAccumulator(), and v8::internal::interpreter::BytecodeOperands::WritesOrClobbersAccumulator().
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::PrepareToOutputBytecode().
PrepareOutputRegister()
void v8::internal::interpreter::BytecodeRegisterOptimizer::PrepareOutputRegister (Register reg)
Definition at line 493 of file bytecode-register-optimizer.cc.
                                                                  {
  RegisterInfo* reg_info = GetRegisterInfo(reg);
  if (reg_info->materialized()) {
    CreateMaterializedEquivalent(reg_info);
  }
  reg_info->MoveToNewEquivalenceSet(NextEquivalenceId(),
                                    MaterializedInfo::kMaterialized);
  max_register_index_ =
      std::max(max_register_index_, reg_info->register_value().index());
}
References CreateMaterializedEquivalent(), GetRegisterInfo(), v8::internal::interpreter::Register::index(), v8::internal::interpreter::kMaterialized, v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::materialized(), max_register_index_, v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::MoveToNewEquivalenceSet(), NextEquivalenceId(), and v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::register_value().
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::GetInputOutputRegisterOperand(), v8::internal::interpreter::BytecodeArrayBuilder::GetOutputRegisterOperand(), and PrepareOutputRegisterList().
PrepareOutputRegisterList()
void v8::internal::interpreter::BytecodeRegisterOptimizer::PrepareOutputRegisterList (RegisterList reg_list)
Definition at line 504 of file bytecode-register-optimizer.cc.
                           {
  int start_index = reg_list.first_register().index();
  for (int i = 0; i < reg_list.register_count(); ++i) {
    Register current(start_index + i);
    PrepareOutputRegister(current);
  }
}
References v8::internal::interpreter::RegisterList::first_register(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::interpreter::Register::index(), PrepareOutputRegister(), and v8::internal::interpreter::RegisterList::register_count().
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::GetOutputRegisterListOperand().
PushToRegistersNeedingFlush()
void v8::internal::interpreter::BytecodeRegisterOptimizer::PushToRegistersNeedingFlush (RegisterInfo * reg) [private]
Definition at line 328 of file bytecode-register-optimizer.cc.
                                                                             {
  // Flushing is required in two cases:
  // 1) Two or more registers in the same equivalence set.
  // 2) Binding a variable to a register.
  flush_required_ = true;
  if (!reg->needs_flush()) {
    reg->set_needs_flush(true);
    registers_needing_flushed_.push_back(reg);
  }
}
References flush_required_, v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::needs_flush(), registers_needing_flushed_, and v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::set_needs_flush().
Referenced by AddToEquivalenceSet(), and SetVariableInRegister().
RegisterAllocateEvent()
void v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterAllocateEvent (Register reg) [override], [private]
Definition at line 564 of file bytecode-register-optimizer.cc.
                                                                  {
  AllocateRegister(GetOrCreateRegisterInfo(reg));
}
References AllocateRegister(), and GetOrCreateRegisterInfo().
RegisterFreeEvent()
void v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterFreeEvent (Register reg) [override], [private]
Definition at line 586 of file bytecode-register-optimizer.cc.
                                                              {
  GetRegisterInfo(reg)->set_allocated(false);
}
References GetRegisterInfo(), and v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::set_allocated().
RegisterFromRegisterInfoTableIndex()
Register v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterFromRegisterInfoTableIndex (size_t index) const [inline], [private]
Definition at line 202 of file bytecode-register-optimizer.h.
                                                                  {
    return Register(static_cast<int>(index) - register_info_table_offset_);
  }
References v8::internal::index, and v8::internal::ETWJITInterface::Register().
Referenced by BytecodeRegisterOptimizer(), and GrowRegisterMap().
RegisterIsObservable()
bool v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterIsObservable (Register reg) const [inline], [private]
Definition at line 190 of file bytecode-register-optimizer.h.
                                                {
    return reg != accumulator_ && !RegisterIsTemporary(reg);
  }
Referenced by RegisterTransfer().
RegisterIsTemporary()
bool v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterIsTemporary (Register reg) const [inline], [private]
Definition at line 186 of file bytecode-register-optimizer.h.
                                               {
    return reg >= temporary_base_;
  }
Referenced by GrowRegisterMap().
RegisterListAllocateEvent()
void v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterListAllocateEvent (RegisterList reg_list) [override], [private]
Definition at line 568 of file bytecode-register-optimizer.cc.
                           {
  if (reg_list.register_count() != 0) {
    int first_index = reg_list.first_register().index();
    GrowRegisterMap(Register(first_index + reg_list.register_count() - 1));
    for (int i = 0; i < reg_list.register_count(); i++) {
      AllocateRegister(GetRegisterInfo(Register(first_index + i)));
    }
  }
}
References AllocateRegister(), v8::internal::interpreter::RegisterList::first_register(), GetRegisterInfo(), GrowRegisterMap(), v8::internal::interpreter::Register::index(), v8::internal::ETWJITInterface::Register(), and v8::internal::interpreter::RegisterList::register_count().
RegisterListFreeEvent()
void v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterListFreeEvent (RegisterList reg) [override], [private]
Definition at line 579 of file bytecode-register-optimizer.cc.
                                                                           {
  int first_index = reg_list.first_register().index();
  for (int i = 0; i < reg_list.register_count(); i++) {
    GetRegisterInfo(Register(first_index + i))->set_allocated(false);
  }
}
References v8::internal::interpreter::RegisterList::first_register(), GetRegisterInfo(), v8::internal::interpreter::Register::index(), v8::internal::ETWJITInterface::Register(), v8::internal::interpreter::RegisterList::register_count(), and v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::set_allocated().
RegisterTransfer()
void v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterTransfer (RegisterInfo * input, RegisterInfo * output) [private]
Definition at line 456 of file bytecode-register-optimizer.cc.
                                                                            {
  bool output_is_observable =
      RegisterIsObservable(output_info->register_value());
  bool in_same_equivalence_set =
      output_info->IsInSameEquivalenceSet(input_info);
  if (in_same_equivalence_set &&
      (!output_is_observable || output_info->materialized())) {
    return; // Nothing more to do.
  }
  // Materialize an alternate in the equivalence set that
  // |output_info| is leaving.
  if (output_info->materialized()) {
    CreateMaterializedEquivalent(output_info);
  }
  // Add |output_info| to new equivalence set.
  if (!in_same_equivalence_set) {
    AddToEquivalenceSet(input_info, output_info);
  }
  if (output_is_observable) {
    // Force store to be emitted when register is observable.
    output_info->set_materialized(false);
    RegisterInfo* materialized_info = input_info->GetMaterializedEquivalent();
    OutputRegisterTransfer(materialized_info, output_info);
  }
  bool input_is_observable = RegisterIsObservable(input_info->register_value());
  if (input_is_observable) {
    // If input is observable by the debugger, mark all other temporaries
    // registers as unmaterialized so that this register is used in preference.
    input_info->MarkTemporariesAsUnmaterialized(temporary_base_);
  }
}
References AddToEquivalenceSet(), CreateMaterializedEquivalent(), v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::GetMaterializedEquivalent(), v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::IsInSameEquivalenceSet(), v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::MarkTemporariesAsUnmaterialized(), v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::materialized(), OutputRegisterTransfer(), v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::register_value(), RegisterIsObservable(), v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::set_materialized(), and temporary_base_.
ResetTypeHintForAccumulator()
void v8::internal::interpreter::BytecodeRegisterOptimizer::ResetTypeHintForAccumulator ()
Definition at line 201 of file bytecode-register-optimizer.cc.
                                                            {
  accumulator_info_->set_type_hint(TypeHint::kAny);
}
References accumulator_info_, and v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::set_type_hint().
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::Bind(), and v8::internal::interpreter::BytecodeArrayBuilder::MarkTryEnd().
SetTypeHintForAccumulator()
void v8::internal::interpreter::BytecodeRegisterOptimizer::SetTypeHintForAccumulator (TypeHint hint)
Definition at line 193 of file bytecode-register-optimizer.cc.
                                                                       {
  DCHECK(BytecodeGenerator::IsSameOrSubTypeHint(accumulator_info_->type_hint(),
                                                hint));
  if (accumulator_info_->type_hint() != hint) {
    accumulator_info_->set_type_hint(hint);
  }
}
References accumulator_info_, v8::internal::DCHECK(), v8::internal::interpreter::BytecodeGenerator::IsSameOrSubTypeHint(), v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::set_type_hint(), and v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::type_hint().
Referenced by v8::internal::interpreter::BytecodeGenerator::VisitForAccumulatorValueImpl().
SetVariableInRegister()
void v8::internal::interpreter::BytecodeRegisterOptimizer::SetVariableInRegister (Variable * var, Register reg)
Definition at line 162 of file bytecode-register-optimizer.cc.
                                                                    {
  RegisterInfo* info = GetRegisterInfo(reg);
  RegisterInfo* it = info;
  do {
    PushToRegistersNeedingFlush(it);
    it->set_variable_hint({var, VariableHintMode::kDefinitelyHasVariable});
    it = it->next();
  } while (it != info);
}
References GetRegisterInfo(), v8::internal::interpreter::kDefinitelyHasVariable, v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::next(), PushToRegistersNeedingFlush(), and v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::set_variable_hint().
Referenced by v8::internal::interpreter::BytecodeGenerator::SetVariableInRegister().
zone()
Zone* v8::internal::interpreter::BytecodeRegisterOptimizer::zone () [inline], [private]
Definition at line 214 of file bytecode-register-optimizer.h.
{ return zone_; }
Referenced by BytecodeRegisterOptimizer(), and GrowRegisterMap().
Member Data Documentation
accumulator_
const Register v8::internal::interpreter::BytecodeRegisterOptimizer::accumulator_ [private]
Definition at line 216 of file bytecode-register-optimizer.h.
Referenced by BytecodeRegisterOptimizer(), GetMaterializedEquivalentNotAccumulator(), and OutputRegisterTransfer().
accumulator_info_
RegisterInfo* v8::internal::interpreter::BytecodeRegisterOptimizer::accumulator_info_ [private]
Definition at line 217 of file bytecode-register-optimizer.h.
Referenced by BytecodeRegisterOptimizer(), IsAccumulatorReset(), ResetTypeHintForAccumulator(), and SetTypeHintForAccumulator().
bytecode_writer_
BytecodeWriter* v8::internal::interpreter::BytecodeRegisterOptimizer::bytecode_writer_ [private]
Definition at line 230 of file bytecode-register-optimizer.h.
Referenced by OutputRegisterTransfer().
equivalence_id_
uint32_t v8::internal::interpreter::BytecodeRegisterOptimizer::equivalence_id_ [private]
Definition at line 228 of file bytecode-register-optimizer.h.
Referenced by v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::MoveToNewEquivalenceSet().
flush_required_
bool v8::internal::interpreter::BytecodeRegisterOptimizer::flush_required_ [private]
Definition at line 231 of file bytecode-register-optimizer.h.
Referenced by Flush(), and PushToRegistersNeedingFlush().
kInvalidEquivalenceId
const uint32_t v8::internal::interpreter::BytecodeRegisterOptimizer::kInvalidEquivalenceId = kMaxUInt32 [static], [private]
Definition at line 143 of file bytecode-register-optimizer.h.
Referenced by v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo::AddToEquivalenceSetOf().
max_register_index_
int v8::internal::interpreter::BytecodeRegisterOptimizer::max_register_index_ [private]
Definition at line 219 of file bytecode-register-optimizer.h.
Referenced by OutputRegisterTransfer(), and PrepareOutputRegister().
register_info_table_
ZoneVector<RegisterInfo*> v8::internal::interpreter::BytecodeRegisterOptimizer::register_info_table_ [private]
Definition at line 222 of file bytecode-register-optimizer.h.
Referenced by BytecodeRegisterOptimizer(), EnsureAllRegistersAreFlushed(), and GrowRegisterMap().
register_info_table_offset_
int v8::internal::interpreter::BytecodeRegisterOptimizer::register_info_table_offset_ [private]
Definition at line 223 of file bytecode-register-optimizer.h.
Referenced by BytecodeRegisterOptimizer().
registers_needing_flushed_
ZoneDeque<RegisterInfo*> v8::internal::interpreter::BytecodeRegisterOptimizer::registers_needing_flushed_ [private]
Definition at line 225 of file bytecode-register-optimizer.h.
Referenced by Flush(), and PushToRegistersNeedingFlush().
temporary_base_
const Register v8::internal::interpreter::BytecodeRegisterOptimizer::temporary_base_ [private]
Definition at line 218 of file bytecode-register-optimizer.h.
Referenced by BytecodeRegisterOptimizer(), and RegisterTransfer().
zone_
Zone* v8::internal::interpreter::BytecodeRegisterOptimizer::zone_ [private]
Definition at line 232 of file bytecode-register-optimizer.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/interpreter/bytecode-register-optimizer.h
/mnt/V8SourceCode/src/interpreter/bytecode-register-optimizer.cc