cppgc::internal::BaseSpace Class Reference
#include <heap-space.h>
Public Types
using Pages = std::vector< BasePage * >
using iterator = Pages::iterator
using const_iterator = Pages::const_iterator
Public Member Functions
BaseSpace (const BaseSpace &)=delete
BaseSpace & operator= (const BaseSpace &)=delete
virtual ~BaseSpace ()
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
size_t size () const
bool is_large () const
size_t index () const
RawHeap * raw_heap ()
const RawHeap * raw_heap () const
void AddPage (BasePage *)
void RemovePage (BasePage *)
Pages RemoveAllPages ()
v8::base::Mutex & pages_mutex () const
bool is_compactable () const
Protected Types
enum class PageType { kNormal
, kLarge
 }
Protected Member Functions
BaseSpace (RawHeap *heap, size_t index, PageType type, bool is_compactable)
Private Attributes
RawHeap * heap_
Pages pages_
v8::base::Mutex pages_mutex_
const size_t index_
const PageType type_
const bool is_compactable_
Detailed Description
Definition at line 22 of file heap-space.h.
Member Typedef Documentation
const_iterator
using cppgc::internal::BaseSpace::const_iterator = Pages::const_iterator
Definition at line 27 of file heap-space.h.
iterator
using cppgc::internal::BaseSpace::iterator = Pages::iterator
Definition at line 26 of file heap-space.h.
Pages
using cppgc::internal::BaseSpace::Pages = std::vector<BasePage*>
Definition at line 24 of file heap-space.h.
Member Enumeration Documentation
PageType
enum cppgc::internal::BaseSpace::PageType [strong], [protected]
Enumerator
kNormal
kLarge
Definition at line 55 of file heap-space.h.
{ kNormal, kLarge };
Constructor & Destructor Documentation
BaseSpace() [1/2]
cppgc::internal::BaseSpace::BaseSpace (const BaseSpace &) [delete]
 BaseSpace()
cppgc::internal::BaseSpace::~BaseSpace () [virtual], [default]
BaseSpace() [2/2]
cppgc::internal::BaseSpace::BaseSpace (RawHeap * heap, size_t index, PageType type, bool is_compactable) [explicit], [protected]
Definition at line 17 of file heap-space.cc.
    : heap_(heap), index_(index), type_(type), is_compactable_(is_compactable) {
  USE(is_compactable_);
}
References is_compactable_, and USE.
Member Function Documentation
AddPage()
void cppgc::internal::BaseSpace::AddPage (BasePage * page)
Definition at line 25 of file heap-space.cc.
                                      {
  v8::base::MutexGuard lock(&pages_mutex_);
  DCHECK_EQ(pages_.cend(), std::find(pages_.cbegin(), pages_.cend(), page));
  pages_.push_back(page);
}
References DCHECK_EQ, pages_, and pages_mutex_.
Referenced by cppgc::internal::anonymous_namespace{sweeper.cc}::SweepFinalizer::FinalizePage(), and cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::SweepLiveLargePage().
begin() [1/2]
iterator cppgc::internal::BaseSpace::begin () [inline]
Definition at line 33 of file heap-space.h.
{ return pages_.begin(); }
Referenced by cppgc::internal::LargePage::Destroy(), and cppgc::internal::NormalPage::Destroy().
begin() [2/2]
const_iterator cppgc::internal::BaseSpace::begin () const [inline]
Definition at line 34 of file heap-space.h.
{ return pages_.begin(); }
end() [1/2]
iterator cppgc::internal::BaseSpace::end () [inline]
Definition at line 35 of file heap-space.h.
{ return pages_.end(); }
Referenced by cppgc::internal::LargePage::Destroy(), and cppgc::internal::NormalPage::Destroy().
end() [2/2]
const_iterator cppgc::internal::BaseSpace::end () const [inline]
Definition at line 36 of file heap-space.h.
{ return pages_.end(); }
index()
size_t cppgc::internal::BaseSpace::index () const [inline]
Definition at line 41 of file heap-space.h.
{ return index_; }
Referenced by cppgc::internal::MarkingVerifierBase::ReportLargePage(), and cppgc::internal::MarkingVerifierBase::ReportNormalPage().
is_compactable()
bool cppgc::internal::BaseSpace::is_compactable () const [inline]
Definition at line 52 of file heap-space.h.
{ return is_compactable_; }
Referenced by cppgc::internal::anonymous_namespace{compactor.cc}::MovableReferences::AddOrFilter().
is_large()
bool cppgc::internal::BaseSpace::is_large () const [inline]
Definition at line 40 of file heap-space.h.
{ return type_ == PageType::kLarge; }
operator=()
BaseSpace& cppgc::internal::BaseSpace::operator= (const BaseSpace &) [delete]
pages_mutex()
v8::base::Mutex& cppgc::internal::BaseSpace::pages_mutex () const [inline]
Definition at line 50 of file heap-space.h.
{ return pages_mutex_; }
Referenced by cppgc::internal::LargePage::Destroy().
raw_heap() [1/2]
RawHeap* cppgc::internal::BaseSpace::raw_heap () [inline]
Definition at line 43 of file heap-space.h.
{ return heap_; }
Referenced by cppgc::internal::BasePage::BasePage(), cppgc::internal::BasePage::ChangeOwner(), cppgc::internal::BasePage::Destroy(), cppgc::internal::LargePage::TryCreate(), and cppgc::internal::NormalPage::TryCreate().
raw_heap() [2/2]
const RawHeap* cppgc::internal::BaseSpace::raw_heap () const [inline]
Definition at line 44 of file heap-space.h.
{ return heap_; }
RemoveAllPages()
BaseSpace::Pages cppgc::internal::BaseSpace::RemoveAllPages ()
Definition at line 38 of file heap-space.cc.
                                         {
  Pages pages = std::move(pages_);
  pages_.clear();
  return pages;
}
References pages_.
RemovePage()
void cppgc::internal::BaseSpace::RemovePage (BasePage * page)
Definition at line 31 of file heap-space.cc.
                                         {
  v8::base::MutexGuard lock(&pages_mutex_);
  auto it = std::find(pages_.cbegin(), pages_.cend(), page);
  DCHECK_NE(pages_.cend(), it);
  pages_.erase(it);
}
References DCHECK_NE, pages_, and pages_mutex_.
Referenced by cppgc::internal::ExplicitManagementImpl::FreeUnreferencedObject().
size()
size_t cppgc::internal::BaseSpace::size () const [inline]
Definition at line 38 of file heap-space.h.
{ return pages_.size(); }
Member Data Documentation
heap_
RawHeap* cppgc::internal::BaseSpace::heap_ [private]
Definition at line 60 of file heap-space.h.
index_
const size_t cppgc::internal::BaseSpace::index_ [private]
Definition at line 63 of file heap-space.h.
is_compactable_
const bool cppgc::internal::BaseSpace::is_compactable_ [private]
Definition at line 65 of file heap-space.h.
Referenced by BaseSpace().
pages_
Pages cppgc::internal::BaseSpace::pages_ [private]
Definition at line 61 of file heap-space.h.
Referenced by AddPage(), RemoveAllPages(), and RemovePage().
pages_mutex_
v8::base::Mutex cppgc::internal::BaseSpace::pages_mutex_ [mutable], [private]
Definition at line 62 of file heap-space.h.
Referenced by AddPage(), and RemovePage().
type_
const PageType cppgc::internal::BaseSpace::type_ [private]
Definition at line 64 of file heap-space.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/heap-space.h
/mnt/V8SourceCode/src/heap/cppgc/heap-space.cc