v8::internal::Rewriter Class Reference
#include <rewriter.h>
Static Public Member Functions
static V8_EXPORT_PRIVATE bool Rewrite (ParseInfo *info, bool *out_has_stack_overflow)
static std::optional< VariableProxy * > RewriteBody (ParseInfo *info, Scope *scope, ZonePtrList< Statement > *body, bool *out_has_stack_overflow)
Detailed Description
Definition at line 24 of file rewriter.h.
Member Function Documentation
Rewrite()
bool v8::internal::Rewriter::Rewrite (ParseInfo * info, bool * out_has_stack_overflow) [static]
Definition at line 386 of file rewriter.cc.
                                                                    {
  RCS_SCOPE(info->runtime_call_stats(),
            RuntimeCallCounterId::kCompileRewriteReturnResult,
            RuntimeCallStats::kThreadSpecific);
  FunctionLiteral* function = info->literal();
  DCHECK_NOT_NULL(function);
  Scope* scope = function->scope();
  DCHECK_NOT_NULL(scope);
  DCHECK_EQ(scope, scope->GetClosureScope());
  if (scope->is_repl_mode_scope() ||
      !(scope->is_script_scope() || scope->is_eval_scope())) {
    return true;
  }
  ZonePtrList<Statement>* body = function->body();
  return RewriteBody(info, scope, body, out_has_stack_overflow).has_value();
}
References DCHECK_EQ, DCHECK_NOT_NULL, v8::internal::Scope::GetClosureScope(), v8::internal::Scope::is_eval_scope(), v8::internal::Scope::is_repl_mode_scope(), v8::internal::Scope::is_script_scope(), v8::internal::ParseInfo::literal(), RCS_SCOPE, RewriteBody(), and v8::internal::ParseInfo::runtime_call_stats().
Referenced by v8::internal::Parser::PostProcessParseResult().
RewriteBody()
std::optional< VariableProxy * > v8::internal::Rewriter::RewriteBody (ParseInfo * info, Scope * scope, ZonePtrList< Statement > * body, bool * out_has_stack_overflow) [static]
Definition at line 406 of file rewriter.cc.
                                  {
  DisallowGarbageCollection no_gc;
  DisallowHandleAllocation no_handles;
  DisallowHandleDereference no_deref;
  if (!body->is_empty()) {
    Variable* result = scope->AsDeclarationScope()->NewTemporary(
        info->ast_value_factory()->dot_result_string());
    Processor processor(info->stack_limit(), scope->AsDeclarationScope(),
                        result, info->ast_value_factory(), info->zone());
    processor.Process(body);
    if (processor.result_assigned()) {
      int pos = kNoSourcePosition;
      VariableProxy* result_value =
          processor.factory()->NewVariableProxy(result, pos);
      if (!info->flags().is_repl_mode()) {
        Statement* result_statement;
        result_statement =
            processor.factory()->NewReturnStatement(result_value, pos);
        body->Add(result_statement, info->zone());
      }
      return result_value;
    }
    if (processor.HasStackOverflow()) {
      *out_has_stack_overflow = true;
      return std::nullopt;
    }
  }
  return nullptr;
}
References v8::internal::ZoneList< T >::Add(), v8::internal::Scope::AsDeclarationScope(), v8::internal::ParseInfo::ast_value_factory(), v8::internal::Processor::factory(), v8::internal::ParseInfo::flags(), v8::internal::ZoneList< T >::is_empty(), v8::internal::kNoSourcePosition, v8::internal::AstNodeFactory::NewReturnStatement(), v8::internal::Scope::NewTemporary(), v8::internal::AstNodeFactory::NewVariableProxy(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Processor::Process(), v8::base::internal::result, v8::internal::Processor::result_assigned(), v8::internal::ParseInfo::stack_limit(), and v8::internal::ParseInfo::zone().
Referenced by v8::internal::Parser::ParseREPLProgram(), and Rewrite().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/parsing/rewriter.h
/mnt/V8SourceCode/src/parsing/rewriter.cc