v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::DebugFieldType Class Reference
Public Member Functions
DebugFieldType (const Field &field)
DebugFieldType (const NameAndType &name_and_type, const SourcePosition &pos)
bool IsTagged () const
std::string GetValueType (TypeStorage storage) const
std::string GetOriginalType (TypeStorage storage) const
std::string GetTypeString (TypeStorage storage) const
size_t GetSize () const
std::string GetAddressGetter ()
Private Attributes
NameAndType name_and_type_
SourcePosition pos_
Detailed Description
Definition at line 106 of file class-debug-reader-generator.cc.
Constructor & Destructor Documentation
DebugFieldType() [1/2]
v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::DebugFieldType::DebugFieldType (const Field & field) [inline], [explicit]
Definition at line 108 of file class-debug-reader-generator.cc.
      : name_and_type_(field.name_and_type), pos_(field.pos) {}
DebugFieldType() [2/2]
v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::DebugFieldType::DebugFieldType (const NameAndType & name_and_type, const SourcePosition & pos) [inline]
Definition at line 110 of file class-debug-reader-generator.cc.
      : name_and_type_(name_and_type), pos_(pos) {}
Member Function Documentation
GetAddressGetter()
std::string v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::DebugFieldType::GetAddressGetter () [inline]
Definition at line 192 of file class-debug-reader-generator.cc.
                               {
    return "Get" + CamelifyString(name_and_type_.name) + "Address";
  }
References v8::internal::torque::CamelifyString().
Referenced by v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::GenerateFieldAddressAccessor(), v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::GenerateFieldValueAccessor(), and v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::GenerateGetPropsChunkForField().
GetOriginalType()
std::string v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::DebugFieldType::GetOriginalType (TypeStorage storage) const [inline]
Definition at line 138 of file class-debug-reader-generator.cc.
                                                       {
    if (name_and_type_.type->StructSupertype()) {
      // There's no meaningful type we could use here, because the V8 symbols
      // don't have any definition of a C++ struct matching this struct type.
      return "";
    }
    if (IsTagged()) {
      std::optional<const ClassType*> field_class_type =
          name_and_type_.type->ClassSupertype();
      std::string result =
          "v8::internal::" +
          (field_class_type.has_value()
               ? (*field_class_type)->GetGeneratedTNodeTypeName()
               : "Object");
      if (storage == kAsStoredInHeap) {
        result = "v8::internal::TaggedMember<" + result + ">";
      }
      return result;
    }
    return name_and_type_.type->GetConstexprGeneratedTypeName();
  }
References v8::internal::compiler::turboshaft::IsTagged, v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::kAsStoredInHeap, v8::base::internal::result, and v8::internal::string.
GetSize()
size_t v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::DebugFieldType::GetSize () const [inline]
Definition at line 181 of file class-debug-reader-generator.cc.
                         {
    auto opt_size = SizeOf(name_and_type_.type);
    if (!opt_size.has_value()) {
      Error("Size required for type ", name_and_type_.type->ToString())
          .Position(pos_);
      return 0;
    }
    return std::get<0>(*opt_size);
  }
References v8::internal::torque::Error(), v8::internal::torque::MessageBuilder::Position(), and v8::internal::torque::SizeOf().
Referenced by v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::GenerateGetPropsChunkForField().
GetTypeString()
std::string v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::DebugFieldType::GetTypeString (TypeStorage storage) const [inline]
Definition at line 165 of file class-debug-reader-generator.cc.
                                                     {
    if (IsTagged() || name_and_type_.type->IsStructType()) {
      // Wrap up the original type in a string literal.
      return "\"" + GetOriginalType(storage) + "\"";
    }
    // We require constexpr type names to be resolvable in the v8::internal
    // namespace, according to the contract in debug-helper.h. In order to
    // verify at compile time that constexpr type names are resolvable, we use
    // the type name as a dummy template parameter to a function that just
    // returns its parameter.
    return "CheckTypeName<" + GetValueType(storage) + ">(\"" +
           GetOriginalType(storage) + "\")";
  }
References v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GetValueType(), and v8::internal::compiler::turboshaft::IsTagged.
Referenced by v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::GenerateGetPropsChunkForField().
GetValueType()
std::string v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::DebugFieldType::GetValueType (TypeStorage storage) const [inline]
Definition at line 121 of file class-debug-reader-generator.cc.
                                                    {
    if (IsTagged()) {
      return storage == kAsStoredInHeap ? "i::Tagged_t" : "uintptr_t";
    }
    // We can't emit a useful error at this point if the constexpr type name is
    // wrong, but we can include a comment that might be helpful.
    return GetOriginalType(storage) +
           " /*Failing? Ensure constexpr type name is correct, and the "
           "necessary #include is in any .tq file*/";
  }
References v8::internal::compiler::turboshaft::IsTagged, and v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::kAsStoredInHeap.
Referenced by v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::GenerateFieldValueAccessor().
IsTagged()
bool v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::DebugFieldType::IsTagged () const [inline]
Definition at line 113 of file class-debug-reader-generator.cc.
                        {
    return name_and_type_.type->IsSubtypeOf(TypeOracle::GetTaggedType());
  }
References v8::internal::torque::TypeOracle::GetTaggedType().
Referenced by v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::GenerateFieldValueAccessor().
Member Data Documentation
name_and_type_
NameAndType v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::DebugFieldType::name_and_type_ [private]
Definition at line 197 of file class-debug-reader-generator.cc.
pos_
SourcePosition v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::DebugFieldType::pos_ [private]
Definition at line 198 of file class-debug-reader-generator.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/class-debug-reader-generator.cc