v8::internal::wasm::WasmSerializer Class Reference
#include <wasm-serialization.h>
Public Member Functions
WasmSerializer (NativeModule *native_module)
size_t GetSerializedNativeModuleSize () const
bool SerializeNativeModule (base::Vector< uint8_t > buffer) const
Static Public Attributes
static constexpr size_t kMagicNumberOffset = 0
static constexpr size_t kVersionHashOffset = kMagicNumberOffset + kUInt32Size
static constexpr size_t kSupportedCPUFeaturesOffset
static constexpr size_t kFlagHashOffset
static constexpr size_t kHeaderSize = 5 * kUInt32Size
Private Attributes
NativeModule * native_module_
WasmCodeRefScope code_ref_scope_
std::vector< WasmCode * > code_table_
std::vector< WellKnownImport > import_statuses_
Detailed Description
Definition at line 19 of file wasm-serialization.h.
Constructor & Destructor Documentation
WasmSerializer()
v8::internal::wasm::WasmSerializer::WasmSerializer (NativeModule * native_module) [explicit]
Definition at line 628 of file wasm-serialization.cc.
    : native_module_(native_module) {
  std::tie(code_table_, import_statuses_) = native_module->SnapshotCodeTable();
}
References code_table_, import_statuses_, and v8::internal::wasm::NativeModule::SnapshotCodeTable().
Member Function Documentation
GetSerializedNativeModuleSize()
size_t v8::internal::wasm::WasmSerializer::GetSerializedNativeModuleSize () const
Definition at line 633 of file wasm-serialization.cc.
                                                           {
  NativeModuleSerializer serializer(native_module_, base::VectorOf(code_table_),
                                    base::VectorOf(import_statuses_));
  return kHeaderSize + serializer.Measure();
}
References code_table_, import_statuses_, kHeaderSize, v8::internal::wasm::NativeModuleSerializer::Measure(), native_module_, and v8::base::VectorOf().
Referenced by v8::internal::RUNTIME_FUNCTION().
SerializeNativeModule()
bool v8::internal::wasm::WasmSerializer::SerializeNativeModule (base::Vector< uint8_t > buffer) const
Definition at line 639 of file wasm-serialization.cc.
                                                                           {
  NativeModuleSerializer serializer(native_module_, base::VectorOf(code_table_),
                                    base::VectorOf(import_statuses_));
  size_t measured_size = kHeaderSize + serializer.Measure();
  if (buffer.size() < measured_size) return false;
  Writer writer(buffer);
  WriteHeader(&writer, native_module_->enabled_features());
  if (!serializer.Write(&writer)) return false;
  DCHECK_EQ(measured_size, writer.bytes_written());
  return true;
}
References code_table_, DCHECK_EQ, v8::internal::wasm::NativeModule::enabled_features(), import_statuses_, kHeaderSize, v8::internal::wasm::NativeModuleSerializer::Measure(), native_module_, v8::base::Vector< T >::size(), v8::base::VectorOf(), v8::internal::wasm::NativeModuleSerializer::Write(), and v8::internal::WriteHeader().
Referenced by v8::internal::RUNTIME_FUNCTION().
Member Data Documentation
code_ref_scope_
WasmCodeRefScope v8::internal::wasm::WasmSerializer::code_ref_scope_ [private]
Definition at line 49 of file wasm-serialization.h.
code_table_
std::vector<WasmCode*> v8::internal::wasm::WasmSerializer::code_table_ [private]
Definition at line 50 of file wasm-serialization.h.
Referenced by GetSerializedNativeModuleSize(), SerializeNativeModule(), and WasmSerializer().
import_statuses_
std::vector<WellKnownImport> v8::internal::wasm::WasmSerializer::import_statuses_ [private]
Definition at line 51 of file wasm-serialization.h.
Referenced by GetSerializedNativeModuleSize(), SerializeNativeModule(), and WasmSerializer().
kFlagHashOffset
constexpr size_t v8::internal::wasm::WasmSerializer::kFlagHashOffset [static], [constexpr]
Initial value:
=
      kSupportedCPUFeaturesOffset + kUInt32Size
Definition at line 42 of file wasm-serialization.h.
kHeaderSize
constexpr size_t v8::internal::wasm::WasmSerializer::kHeaderSize = 5 * kUInt32Size [static], [constexpr]
Definition at line 44 of file wasm-serialization.h.
Referenced by v8::internal::wasm::DeserializeNativeModule(), GetSerializedNativeModuleSize(), v8::internal::wasm::IsSupportedVersion(), SerializeNativeModule(), and v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::WriteHeader().
kMagicNumberOffset
constexpr size_t v8::internal::wasm::WasmSerializer::kMagicNumberOffset = 0 [static], [constexpr]
Definition at line 38 of file wasm-serialization.h.
kSupportedCPUFeaturesOffset
constexpr size_t v8::internal::wasm::WasmSerializer::kSupportedCPUFeaturesOffset [static], [constexpr]
Initial value:
=
      kVersionHashOffset + kUInt32Size
Definition at line 40 of file wasm-serialization.h.
kVersionHashOffset
constexpr size_t v8::internal::wasm::WasmSerializer::kVersionHashOffset = kMagicNumberOffset + kUInt32Size [static], [constexpr]
Definition at line 39 of file wasm-serialization.h.
native_module_
NativeModule* v8::internal::wasm::WasmSerializer::native_module_ [private]
Definition at line 47 of file wasm-serialization.h.
Referenced by GetSerializedNativeModuleSize(), and SerializeNativeModule().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-serialization.h
/mnt/V8SourceCode/src/wasm/wasm-serialization.cc