v8::internal::V8 Class Reference
#include <v8.h>
Static Public Member Functions
static void Initialize ()
static void Dispose ()
static V8_EXPORT_PRIVATE void FatalProcessOutOfMemory (Isolate *isolate, const char *location, const OOMDetails &details=kNoOOMDetails)
static V8_EXPORT_PRIVATE void FatalProcessOutOfMemory (Isolate *isolate, const char *location, const char *detail)
static void InitializePlatform (v8::Platform *platform)
static V8_EXPORT_PRIVATE void InitializePlatformForTesting (v8::Platform *platform)
static void DisposePlatform ()
static V8_EXPORT_PRIVATE v8::Platform * GetCurrentPlatform ()
static V8_EXPORT_PRIVATE void SetPlatformForTesting (v8::Platform *platform)
static void SetSnapshotBlob (StartupData *snapshot_blob)
Static Public Attributes
static V8_EXPORT_PRIVATE const OOMDetails kNoOOMDetails {false, nullptr}
static V8_EXPORT_PRIVATE const OOMDetails kHeapOOM {true, nullptr}
Static Private Attributes
static v8::Platform * platform_ = nullptr
Detailed Description
Definition at line 20 of file v8.h.
Member Function Documentation
Dispose()
void v8::internal::V8::Dispose () [static]
Definition at line 240 of file v8.cc.
                 {
  AdvanceStartupState(V8StartupState::kV8Disposing);
  CHECK(platform_);
#if V8_ENABLE_WEBASSEMBLY
  wasm::WasmEngine::GlobalTearDown();
#endif // V8_ENABLE_WEBASSEMBLY
#if defined(USE_SIMULATOR)
  Simulator::GlobalTearDown();
#endif
  CallDescriptors::TearDown();
  ElementsAccessor::TearDown();
  RegisteredExtension::UnregisterAll();
  FlagList::ReleaseDynamicAllocations();
  IsolateGroup::TearDownOncePerProcess();
  AdvanceStartupState(V8StartupState::kV8Disposed);
}
References v8::internal::anonymous_namespace{v8.cc}::AdvanceStartupState(), CHECK, v8::internal::wasm::WasmEngine::GlobalTearDown(), platform_, v8::internal::FlagList::ReleaseDynamicAllocations(), v8::internal::CallDescriptors::TearDown(), v8::internal::ElementsAccessor::TearDown(), v8::internal::IsolateGroup::TearDownOncePerProcess(), and v8::RegisteredExtension::UnregisterAll().
Referenced by v8::V8::Dispose().
DisposePlatform()
void v8::internal::V8::DisposePlatform () [static]
Definition at line 257 of file v8.cc.
                         {
  AdvanceStartupState(V8StartupState::kPlatformDisposing);
  CHECK(platform_);
#if defined(V8_OS_WIN) && defined(V8_ENABLE_ETW_STACK_WALKING)
  if (v8_flags.enable_etw_stack_walking ||
      v8_flags.enable_etw_by_custom_filter_only) {
    v8::internal::ETWJITInterface::Unregister();
  }
#endif
  v8::tracing::TracingCategoryObserver::TearDown();
  v8::base::SetPrintStackTrace(nullptr);
#ifdef V8_ENABLE_SANDBOX
  Sandbox::TearDownDefault();
#endif // V8_ENABLE_SANDBOX
  platform_ = nullptr;
#if DEBUG
  internal::ThreadIsolation::CheckTrackedMemoryEmpty();
#endif
  AdvanceStartupState(V8StartupState::kPlatformDisposed);
}
References v8::internal::anonymous_namespace{v8.cc}::AdvanceStartupState(), CHECK, platform_, v8::base::SetPrintStackTrace(), v8::tracing::TracingCategoryObserver::TearDown(), v8::internal::ETWJITInterface::Unregister(), and v8::internal::v8_flags.
Referenced by v8::V8::DisposePlatform().
FatalProcessOutOfMemory() [1/2]
static V8_EXPORT_PRIVATE void v8::internal::V8::FatalProcessOutOfMemory (Isolate * isolate, const char * location, const char * detail) [static]
FatalProcessOutOfMemory() [2/2]
static V8_EXPORT_PRIVATE void v8::internal::V8::FatalProcessOutOfMemory (Isolate * isolate, const char * location, const OOMDetails & details = kNoOOMDetails) [static]
Referenced by v8::internal::wasm::NativeModule::AddCompiledCode(), v8::internal::AlignedAllocWithRetry(), v8::internal::ExternalEntityTable< Entry, size >::AllocateEntry(), v8::internal::wasm::WasmCodeAllocator::AllocateForCodeInRegion(), v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(), v8::internal::wasm::TypeCanonicalizer::CanonicalizeTypeDef(), v8::internal::wasm::TypeCanonicalizer::CheckMaxCanonicalIndex(), v8::internal::wasm::WasmCodeManager::Commit(), v8::internal::anonymous_namespace{js-date-time-format.cc}::DateTimePatternGeneratorCache::CreateGenerator(), v8::internal::wasm::WasmCodeManager::Decommit(), v8::internal::Zone::Expand(), v8::internal::anonymous_namespace{cpp-heap.cc}::FatalOutOfMemoryHandlerImpl(), v8::internal::Heap::FatalProcessOutOfMemory(), v8::internal::FreePages(), v8::internal::anonymous_namespace{cpp-heap.cc}::GlobalFatalOutOfMemoryHandlerImpl(), v8::internal::Assembler::GrowBuffer(), v8::internal::Isolate::Init(), v8::internal::anonymous_namespace{isolate-group.cc}::InitCodeRangeOnce(), v8::internal::ExternalEntityTable< Entry, size >::Initialize(), v8::internal::wasm::WasmImportWrapperCache::LazyInitialize(), v8::ArrayBuffer::New(), v8::SharedArrayBuffer::New(), v8::internal::NewArray(), v8::ArrayBuffer::NewBackingStore(), v8::SharedArrayBuffer::NewBackingStore(), v8::internal::wasm::WasmCodeManager::NewNativeModule(), v8::ArrayBuffer::NewResizableBackingStore(), v8::internal::Malloced::operator new(), v8::internal::CodeRange::RemapEmbeddedBuiltins(), v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::ReservationSizeForWasmCode(), v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::ReservationSizeForWrappers(), v8::internal::Heap::SetUp(), v8::internal::wasm::StackMemory::StackSegment::StackSegment(), v8::internal::RegExpCompiler::ToNodeCheckForStackOverflow(), v8::internal::wasm::WasmInterpreterThread::WasmInterpreterThread(), and v8::internal::wasm::StackMemory::StackSegment::~StackSegment().
GetCurrentPlatform()
v8::Platform * v8::internal::V8::GetCurrentPlatform () [static]
Definition at line 282 of file v8.cc.
                                   {
  v8::Platform* platform = reinterpret_cast<v8::Platform*>(
      base::Relaxed_Load(reinterpret_cast<base::AtomicWord*>(&platform_)));
  DCHECK(platform);
  return platform;
}
References v8::internal::DCHECK(), platform_, and v8::base::Relaxed_Load().
Referenced by v8::internal::PagePool::AddLarge(), v8::internal::CpuProfile::AddPath(), v8::internal::Isolate::Allocate(), v8::internal::DeclarationScope::AllocateScopeInfos(), v8::internal::wasm::AsyncCompileJob::AsyncCompileJob(), v8::internal::detail::AsyncWaiterQueueNode< T >::AsyncWaiterQueueNode(), v8::internal::baseline::ConcurrentBaselineCompiler::ConcurrentBaselineCompiler(), v8::internal::ConcurrentMarking::ConcurrentMarking(), v8::internal::JSDate::CurrentTimeValue(), v8::internal::Isolate::Deinitialize(), v8::internal::OptimizingCompileTaskExecutor::EnsureStarted(), v8::internal::GCExtension::GC(), v8::debug::GetCurrentPlatform(), v8::internal::Heap::GetForegroundTaskRunner(), v8::internal::tracing::TraceEventHelper::GetTracingController(), v8::internal::Isolate::Init(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::InitCompileJob(), Initialize(), v8::V8::Initialize(), v8::Isolate::Initialize(), v8::internal::anonymous_namespace{execution.cc}::Invoke(), v8::internal::wasm::WasmEngine::IsolateInfo::IsolateInfo(), v8::internal::Heap::MonotonicallyIncreasingTimeInMs(), v8::internal::anonymous_namespace{mark-compact.cc}::NumberOfAvailableCores(), v8::internal::ScavengerCollector::NumberOfScavengeTasks(), v8::internal::OnCriticalMemoryPressure(), v8::internal::TracingCpuProfilerImpl::OnTraceDisabled(), v8::internal::anonymous_namespace{allocation.cc}::PageAllocatorInitializer::PageAllocatorInitializer(), v8::internal::JsonParser< Char >::Parse(), v8::internal::GlobalHandles::PostGarbageCollectionProcessing(), v8::internal::PrepareLogFileName(), v8::internal::compiler::GraphC1Visualizer::PrintCompilation(), v8::internal::wasm::AsyncStreamingProcessor::ProcessFunctionBody(), v8::internal::Isolate::PushParamsAndContinue(), v8::internal::Isolate::PushStackTraceAndContinue(), v8::internal::wasm::NativeModuleDeserializer::Read(), v8::internal::Sweeper::SweepingState< scope >::Resume(), v8::internal::anonymous_namespace{traced-handles.cc}::ParallelWeakHandlesProcessor< Derived >::Run(), v8::internal::StressConcurrentAllocationTask::Schedule(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::WriteOutPGOTask::Schedule(), v8::internal::metrics::Recorder::SetEmbedderRecorder(), v8::tracing::TracingCategoryObserver::SetUp(), v8::internal::Heap::SetUp(), v8::internal::wasm::AsyncCompileJob::StartBackgroundTask(), v8::internal::Sweeper::SweepingState< scope >::StartConcurrentSweeping(), v8::internal::ScavengerCollector::QuarantinedPageSweeper::StartSweeping(), v8::tracing::TracingCategoryObserver::TearDown(), v8::internal::TimedScope::TimestampMs(), v8::internal::TracingCpuProfilerImpl::TracingCpuProfilerImpl(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::TriggerCachingAfterTimeout(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::TriggerOutstandingCallbacks(), v8::internal::ConcurrentMarking::TryScheduleJob(), v8::internal::wasm::ValidateFunctions(), v8::internal::IsolateSafepoint::Barrier::WaitInSafepoint(), v8::internal::IsolateSafepoint::Barrier::WaitInUnpark(), v8::internal::HeapProfiler::WriteSnapshotToDiskAfterGC(), and v8::internal::TracingCpuProfilerImpl::~TracingCpuProfilerImpl().
Initialize()
void v8::internal::V8::Initialize () [static]
Definition at line 135 of file v8.cc.
                    {
  AdvanceStartupState(V8StartupState::kV8Initializing);
  CHECK(platform_);
  FlagList::EnforceFlagImplications();
  // Initialize the default FlagList::Hash.
  FlagList::Hash();
  // Before initializing internals, freeze the flags such that further changes
  // are not allowed. Global initialization of the Isolate or the WasmEngine
  // already reads flags, so they should not be changed afterwards.
  if (v8_flags.freeze_flags_after_init) FlagList::FreezeFlags();
  if (v8_flags.trace_turbo) {
    // Create an empty file shared by the process (e.g. the wasm engine).
    std::ofstream(Isolate::GetTurboCfgFileName(nullptr).c_str(),
                  std::ios_base::trunc);
  }
  // The --jitless and --interpreted-frames-native-stack flags are incompatible
  // since the latter requires code generation while the former prohibits code
  // generation.
  CHECK(!v8_flags.interpreted_frames_native_stack || !v8_flags.jitless);
  base::AbortMode abort_mode = base::AbortMode::kDefault;
  if (v8_flags.sandbox_fuzzing || v8_flags.hole_fuzzing) {
    // In this mode, controlled crashes are harmless. Furthermore, DCHECK
    // failures should be ignored (and execution should continue past them) as
    // they may otherwise hide issues.
    abort_mode = base::AbortMode::kExitWithFailureAndIgnoreDcheckFailures;
  } else if (v8_flags.sandbox_testing) {
    // Similar to the above case, but here we want to exit with a status
    // indicating success (e.g. zero on unix). This is useful for example for
    // sandbox regression tests, which should "pass" if they crash in a
    // controlled fashion (e.g. in a SBXCHECK).
    abort_mode = base::AbortMode::kExitWithSuccessAndIgnoreDcheckFailures;
  } else if (v8_flags.hard_abort) {
    abort_mode = base::AbortMode::kImmediateCrash;
  }
  base::OS::Initialize(abort_mode, v8_flags.gc_fake_mmap);
  if (v8_flags.random_seed) {
    GetPlatformPageAllocator()->SetRandomMmapSeed(v8_flags.random_seed);
    GetPlatformVirtualAddressSpace()->SetRandomSeed(v8_flags.random_seed);
  }
  if (v8_flags.print_flag_values) FlagList::PrintValues();
  // Fetch the ThreadIsolatedAllocator once since we need to keep the pointer in
  // protected memory.
  ThreadIsolation::Initialize(
      GetCurrentPlatform()->GetThreadIsolatedAllocator());
#ifdef V8_ENABLE_SANDBOX
  // If enabled, the sandbox must be initialized first.
  Sandbox::InitializeDefaultOncePerProcess(GetPlatformVirtualAddressSpace());
  CHECK_EQ(kSandboxSize, Sandbox::current()->size());
  // Enable sandbox testing mode if requested.
  //
  // This will install the sandbox crash filter to ignore all crashes that do
  // not represent sandbox violations.
  //
  // Note: this should happen before the Wasm trap handler is installed, so that
  // the wasm trap handler is invoked first (and can handle Wasm OOB accesses),
  // then forwards all "real" crashes to the sandbox crash filter.
  if (v8_flags.sandbox_testing || v8_flags.sandbox_fuzzing) {
    SandboxTesting::Mode mode = v8_flags.sandbox_testing
                                    ? SandboxTesting::Mode::kForTesting
                                    : SandboxTesting::Mode::kForFuzzing;
    SandboxTesting::Enable(mode);
  }
#endif // V8_ENABLE_SANDBOX
#if defined(V8_USE_PERFETTO)
  if (perfetto::Tracing::IsInitialized()) {
    TrackEvent::Register();
    if (v8_flags.perfetto_code_logger) {
      v8::internal::CodeDataSource::Register();
    }
  }
#endif
  IsolateGroup::InitializeOncePerProcess();
  Isolate::InitializeOncePerProcess();
#if defined(USE_SIMULATOR)
  Simulator::InitializeOncePerProcess();
#endif
  CpuFeatures::Probe(false);
  ElementsAccessor::InitializeOncePerProcess();
  Bootstrapper::InitializeOncePerProcess();
  CallDescriptors::InitializeOncePerProcess();
#if V8_ENABLE_WEBASSEMBLY
  wasm::WasmEngine::InitializeOncePerProcess();
#endif // V8_ENABLE_WEBASSEMBLY
  ExternalReferenceTable::InitializeOncePerIsolateGroup(
      IsolateGroup::current()->external_ref_table());
  AdvanceStartupState(V8StartupState::kV8Initialized);
}
References v8::internal::anonymous_namespace{v8.cc}::AdvanceStartupState(), CHECK, CHECK_EQ, v8::internal::IsolateGroup::current(), v8::internal::FlagList::EnforceFlagImplications(), v8::internal::FlagList::FreezeFlags(), GetCurrentPlatform(), v8::internal::GetPlatformPageAllocator(), v8::internal::GetPlatformVirtualAddressSpace(), v8::internal::Isolate::GetTurboCfgFileName(), v8::internal::FlagList::Hash(), v8::base::OS::Initialize(), v8::internal::ThreadIsolation::Initialize(), v8::internal::ExternalReferenceTable::InitializeOncePerIsolateGroup(), v8::internal::CallDescriptors::InitializeOncePerProcess(), v8::internal::Isolate::InitializeOncePerProcess(), v8::internal::Bootstrapper::InitializeOncePerProcess(), v8::internal::IsolateGroup::InitializeOncePerProcess(), v8::internal::ElementsAccessor::InitializeOncePerProcess(), v8::internal::wasm::WasmEngine::InitializeOncePerProcess(), cppgc::IsInitialized(), v8::base::kDefault, v8::base::kExitWithFailureAndIgnoreDcheckFailures, v8::base::kExitWithSuccessAndIgnoreDcheckFailures, v8::base::kImmediateCrash, mode(), platform_, v8::internal::FlagList::PrintValues(), v8::internal::CpuFeatures::Probe(), v8::internal::ETWJITInterface::Register(), v8::internal::CodeDataSource::Register(), v8::PageAllocator::SetRandomMmapSeed(), v8::VirtualAddressSpace::SetRandomSeed(), size(), and v8::internal::v8_flags.
Referenced by v8::V8::Initialize().
InitializePlatform()
void v8::internal::V8::InitializePlatform (v8::Platform * platform) [static]
Definition at line 103 of file v8.cc.
                                                {
  AdvanceStartupState(V8StartupState::kPlatformInitializing);
  CHECK(!platform_);
  CHECK_NOT_NULL(platform);
  platform_ = platform;
  v8::base::SetPrintStackTrace(platform_->GetStackTracePrinter());
  v8::tracing::TracingCategoryObserver::SetUp();
#if defined(V8_ENABLE_ETW_STACK_WALKING)
  if (v8_flags.enable_etw_stack_walking ||
      v8_flags.enable_etw_by_custom_filter_only) {
    v8::internal::ETWJITInterface::Register();
  }
#endif // V8_ENABLE_ETW_STACK_WALKING
  // Initialization needs to happen on platform-level, as this sets up some
  // cppgc internals that are needed to allow gracefully failing during cppgc
  // platform setup.
  CppHeap::InitializeOncePerProcess();
  AdvanceStartupState(V8StartupState::kPlatformInitialized);
}
References v8::internal::anonymous_namespace{v8.cc}::AdvanceStartupState(), CHECK, CHECK_NOT_NULL, v8::Platform::GetStackTracePrinter(), v8::internal::CppHeap::InitializeOncePerProcess(), platform_, v8::internal::ETWJITInterface::Register(), v8::base::SetPrintStackTrace(), v8::tracing::TracingCategoryObserver::SetUp(), and v8::internal::v8_flags.
Referenced by v8::V8::InitializePlatform(), and InitializePlatformForTesting().
InitializePlatformForTesting()
void v8::internal::V8::InitializePlatformForTesting (v8::Platform * platform) [static]
Definition at line 126 of file v8.cc.
                                                          {
  if (v8_startup_state_ != V8StartupState::kIdle) {
    FATAL(
        "The platform was initialized before. Note that running multiple tests "
        "in the same process is not supported.");
  }
  V8::InitializePlatform(platform);
}
References FATAL, InitializePlatform(), and v8::internal::anonymous_namespace{v8.cc}::v8_startup_state_().
SetPlatformForTesting()
void v8::internal::V8::SetPlatformForTesting (v8::Platform * platform) [static]
Definition at line 289 of file v8.cc.
                                                   {
  base::Relaxed_Store(reinterpret_cast<base::AtomicWord*>(&platform_),
                      reinterpret_cast<base::AtomicWord>(platform));
}
References platform_, and v8::base::Relaxed_Store().
SetSnapshotBlob()
void v8::internal::V8::SetSnapshotBlob (StartupData * snapshot_blob) [static]
Definition at line 294 of file v8.cc.
                                                   {
#ifdef V8_USE_EXTERNAL_STARTUP_DATA
  base::CallOnce(&init_snapshot_once, &SetSnapshotFromFile, snapshot_blob);
#else
  UNREACHABLE();
#endif
}
References v8::base::CallOnce(), v8::internal::SetSnapshotFromFile(), and v8::internal::UNREACHABLE().
Referenced by v8::V8::SetSnapshotDataBlob().
Member Data Documentation
kHeapOOM
const OOMDetails v8::internal::V8::kHeapOOM {true, nullptr} [static]
Definition at line 37 of file v8.h.
Referenced by v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(), and v8::internal::Heap::FatalProcessOutOfMemory().
kNoOOMDetails
const OOMDetails v8::internal::V8::kNoOOMDetails {false, nullptr} [static]
Definition at line 36 of file v8.h.
platform_
v8::Platform * v8::internal::V8::platform_ = nullptr [static], [private]
Definition at line 57 of file v8.h.
Referenced by Dispose(), DisposePlatform(), GetCurrentPlatform(), Initialize(), InitializePlatform(), and SetPlatformForTesting().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/init/v8.h
/mnt/V8SourceCode/src/init/v8.cc