v8::internal::WasmJs Class Reference
#include <wasm-js.h>
Static Public Member Functions
static V8_EXPORT_PRIVATE void PrepareForSnapshot (Isolate *isolate)
static V8_EXPORT_PRIVATE void Install (Isolate *isolate)
static V8_EXPORT_PRIVATE void InstallConditionalFeatures (Isolate *isolate, DirectHandle< NativeContext > context)
Static Private Member Functions
static V8_EXPORT_PRIVATE void InstallModule (Isolate *isolate, DirectHandle< JSObject > webassembly)
static V8_EXPORT_PRIVATE void InstallMemoryControl (Isolate *isolate, DirectHandle< NativeContext > context, DirectHandle< JSObject > webassembly)
static V8_EXPORT_PRIVATE bool InstallTypeReflection (Isolate *isolate, DirectHandle< NativeContext > context, DirectHandle< JSObject > webassembly)
static V8_EXPORT_PRIVATE bool InstallJSPromiseIntegration (Isolate *isolate, DirectHandle< NativeContext > context, DirectHandle< JSObject > webassembly)
static V8_EXPORT_PRIVATE void InstallResizableBufferIntegration (Isolate *isolate, DirectHandle< NativeContext > context, DirectHandle< JSObject > webassembly)
static V8_EXPORT_PRIVATE bool InstallCustomDescriptors (Isolate *isolate, DirectHandle< NativeContext > context, DirectHandle< JSObject > webassembly)
Detailed Description
Definition at line 72 of file wasm-js.h.
Member Function Documentation
Install()
void v8::internal::WasmJs::Install (Isolate * isolate) [static]
Definition at line 3639 of file wasm-js.cc.
                                     {
  DirectHandle<JSGlobalObject> global = isolate->global_object();
  DirectHandle<NativeContext> native_context(global->native_context(), isolate);
  if (native_context->is_wasm_js_installed() != Smi::zero()) return;
  native_context->set_is_wasm_js_installed(Smi::FromInt(1));
  // We always use the WebAssembly object from the native context; as this code
  // is executed before any user code, this is expected to be the same as the
  // global "WebAssembly" property. But even later during execution we always
  // want to use this preallocated object instead of whatever user code
  // installed as "WebAssembly" property.
  DirectHandle<JSObject> webassembly(native_context->wasm_webassembly_object(),
                                     isolate);
  if (v8_flags.js_source_phase_imports) {
    // Reinstall the Module object with the experimental interface.
    InstallModule(isolate, webassembly);
  }
  // Expose the API on the global object if not in jitless mode (with more
  // subtleties).
  //
  // Even in interpreter-only mode, wasm currently still creates executable
  // memory at runtime. Unexpose wasm until this changes.
  // The correctness fuzzers are a special case: many of their test cases are
  // built by fetching a random property from the the global object, and thus
  // the global object layout must not change between configs. That is why we
  // continue exposing wasm on correctness fuzzers even in jitless mode.
  // TODO(jgruber): Remove this once / if wasm can run without executable
  // memory.
  bool expose_wasm = !i::v8_flags.jitless ||
                     i::v8_flags.correctness_fuzzer_suppressions ||
                     i::v8_flags.wasm_jitless;
  if (expose_wasm) {
    DirectHandle<String> WebAssembly_string = v8_str(isolate, "WebAssembly");
    JSObject::AddProperty(isolate, global, WebAssembly_string, webassembly,
                          DONT_ENUM);
  }
  {
    // Reset the JSTag's canonical_type_index based on this Isolate's
    // type_canonicalizer.
    DirectHandle<WasmTagObject> js_tag_object(
        Cast<WasmTagObject>(native_context->wasm_js_tag()), isolate);
    js_tag_object->set_canonical_type_index(
        wasm::GetWasmEngine()
            ->type_canonicalizer()
            ->AddRecursiveGroup(&kWasmExceptionTagSignature)
            .index);
  }
  if (v8_flags.wasm_test_streaming) {
    isolate->set_wasm_streaming_callback(WasmStreamingCallbackForTesting);
  }
  if (isolate->wasm_streaming_callback() != nullptr) {
    InstallFunc(isolate, webassembly, "compileStreaming",
                WebAssemblyCompileStreaming, 1);
    InstallFunc(isolate, webassembly, "instantiateStreaming",
                WebAssemblyInstantiateStreaming, 1);
  }
  // The native_context is not set up completely yet. That's why we cannot use
  // {WasmEnabledFeatures::FromIsolate} and have to use
  // {WasmEnabledFeatures::FromFlags} instead.
  const auto enabled_features = wasm::WasmEnabledFeatures::FromFlags();
  if (enabled_features.has_type_reflection()) {
    InstallTypeReflection(isolate, native_context, webassembly);
  }
  if (enabled_features.has_memory_control()) {
    InstallMemoryControl(isolate, native_context, webassembly);
  }
  if (enabled_features.has_custom_descriptors()) {
    InstallCustomDescriptors(isolate, native_context, webassembly);
  }
  // Initialize and install JSPI feature.
  if (enabled_features.has_jspi()) {
    CHECK(native_context->is_wasm_jspi_installed() == Smi::zero());
    isolate->WasmInitJSPIFeature();
    InstallJSPromiseIntegration(isolate, native_context, webassembly);
    native_context->set_is_wasm_jspi_installed(Smi::FromInt(1));
  } else if (v8_flags.stress_wasm_stack_switching) {
    // Set up the JSPI objects necessary for stress-testing stack-switching, but
    // don't install WebAssembly.promising and WebAssembly.Suspending.
    isolate->WasmInitJSPIFeature();
  }
  if (enabled_features.has_rab_integration()) {
    InstallResizableBufferIntegration(isolate, native_context, webassembly);
  }
}
References CHECK, v8::internal::DONT_ENUM, v8::internal::wasm::GetWasmEngine(), v8::internal::Isolate::global_object(), v8::internal::index, v8::internal::anonymous_namespace{wasm-js.cc}::InstallFunc(), v8::internal::anonymous_namespace{wasm-js.cc}::kWasmExceptionTagSignature, v8::internal::native_context, v8::internal::v8_flags, v8::anonymous_namespace{wasm-js.cc}::v8_str(), v8::anonymous_namespace{wasm-js.cc}::WasmStreamingCallbackForTesting(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyCompileStreaming(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyInstantiateStreaming(), and v8::internal::zero.
Referenced by v8::internal::Genesis::InstallSpecialObjects().
InstallConditionalFeatures()
void v8::internal::WasmJs::InstallConditionalFeatures (Isolate * isolate, DirectHandle< NativeContext > context) [static]
Definition at line 3736 of file wasm-js.cc.
                                                                             {
  DirectHandle<JSObject> webassembly{context->wasm_webassembly_object(),
                                     isolate};
  if (!webassembly->map()->is_extensible()) return;
  if (webassembly->map()->is_access_check_needed()) return;
  // If you need to install some optional features, follow the pattern:
  //
  // if (isolate->IsMyWasmFeatureEnabled(context)) {
  // DirectHandle<String> feature = isolate->factory()->...;
  // if (!JSObject::HasRealNamedProperty(isolate, webassembly, feature)
  // .FromMaybe(true)) {
  // InstallFeature(isolate, webassembly);
  // }
  // }
  // Install JSPI-related features.
  if (isolate->IsWasmJSPIRequested(context)) {
    if (context->is_wasm_jspi_installed() == Smi::zero()) {
      isolate->WasmInitJSPIFeature();
      if (InstallJSPromiseIntegration(isolate, context, webassembly)) {
        context->set_is_wasm_jspi_installed(Smi::FromInt(1));
      }
    }
  }
}
References v8::internal::Isolate::IsWasmJSPIRequested(), and v8::internal::zero.
Referenced by v8::CALLBACK_SETTER().
InstallCustomDescriptors()
bool v8::internal::WasmJs::InstallCustomDescriptors (Isolate * isolate, DirectHandle< NativeContext > context, DirectHandle< JSObject > webassembly) [static], [private]
Definition at line 3800 of file wasm-js.cc.
                                                                          {
  DirectHandle<String> descriptor_options_string =
      v8_str(isolate, "DescriptorOptions");
  if (JSObject::HasRealNamedProperty(isolate, webassembly,
                                     descriptor_options_string)
          .FromMaybe(true)) {
    return false;
  }
  DirectHandle<JSFunction> descriptor_options_constructor =
      InstallConstructorFunc(isolate, webassembly, "DescriptorOptions",
                             WebAssemblyDescriptorOptionsImpl);
  context->set_wasm_descriptor_options_constructor(
      *descriptor_options_constructor);
  SetupConstructor(
      isolate, descriptor_options_constructor, WASM_DESCRIPTOR_OPTIONS_TYPE,
      WasmDescriptorOptions::kHeaderSize, "WebAssembly.DescriptorOptions");
  return true;
}
References v8::internal::anonymous_namespace{wasm-js.cc}::InstallConstructorFunc(), v8::internal::anonymous_namespace{wasm-js.cc}::SetupConstructor(), v8::anonymous_namespace{wasm-js.cc}::v8_str(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyDescriptorOptionsImpl().
InstallJSPromiseIntegration()
bool v8::internal::WasmJs::InstallJSPromiseIntegration (Isolate * isolate, DirectHandle< NativeContext > context, DirectHandle< JSObject > webassembly) [static], [private]
Definition at line 3766 of file wasm-js.cc.
                                                                             {
  DirectHandle<String> suspender_string = v8_str(isolate, "Suspender");
  if (JSObject::HasRealNamedProperty(isolate, webassembly, suspender_string)
          .FromMaybe(true)) {
    return false;
  }
  DirectHandle<String> suspending_string = v8_str(isolate, "Suspending");
  if (JSObject::HasRealNamedProperty(isolate, webassembly, suspending_string)
          .FromMaybe(true)) {
    return false;
  }
  DirectHandle<String> promising_string = v8_str(isolate, "promising");
  if (JSObject::HasRealNamedProperty(isolate, webassembly, promising_string)
          .FromMaybe(true)) {
    return false;
  }
  DirectHandle<String> suspend_error_string = v8_str(isolate, "SuspendError");
  if (JSObject::HasRealNamedProperty(isolate, webassembly, suspend_error_string)
          .FromMaybe(true)) {
    return false;
  }
  DirectHandle<JSFunction> suspending_constructor = InstallConstructorFunc(
      isolate, webassembly, "Suspending", WebAssemblySuspendingImpl);
  context->set_wasm_suspending_constructor(*suspending_constructor);
  SetupConstructor(isolate, suspending_constructor, WASM_SUSPENDING_OBJECT_TYPE,
                   WasmSuspendingObject::kHeaderSize, "WebAssembly.Suspending");
  InstallFunc(isolate, webassembly, "promising", WebAssemblyPromising, 1);
  InstallError(isolate, webassembly, isolate->factory()->SuspendError_string(),
               Context::WASM_SUSPEND_ERROR_FUNCTION_INDEX);
  return true;
}
References v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{wasm-js.cc}::InstallConstructorFunc(), v8::internal::InstallError(), v8::internal::anonymous_namespace{wasm-js.cc}::InstallFunc(), v8::internal::anonymous_namespace{wasm-js.cc}::SetupConstructor(), v8::anonymous_namespace{wasm-js.cc}::v8_str(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyPromising(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblySuspendingImpl().
InstallMemoryControl()
void v8::internal::WasmJs::InstallMemoryControl (Isolate * isolate, DirectHandle< NativeContext > context, DirectHandle< JSObject > webassembly) [static], [private]
Definition at line 3821 of file wasm-js.cc.
                                                                      {
  // Extensibility of the `WebAssembly` object should already have been checked
  // by the caller.
  DCHECK(webassembly->map()->is_extensible());
  DirectHandle<JSFunction> descriptor_constructor =
      InstallConstructorFunc(isolate, webassembly, "MemoryMapDescriptor",
                             wasm::WebAssemblyMemoryMapDescriptor);
  SetupConstructor(
      isolate, descriptor_constructor, WASM_MEMORY_MAP_DESCRIPTOR_TYPE,
      WasmMemoryMapDescriptor::kHeaderSize, "WebAssembly.MemoryMapDescriptor");
  context->set_wasm_memory_map_descriptor_constructor(*descriptor_constructor);
  DirectHandle<JSObject> descriptor_proto = direct_handle(
      Cast<JSObject>(descriptor_constructor->instance_prototype()), isolate);
  InstallFunc(isolate, descriptor_proto, "map",
              wasm::WebAssemblyMemoryMapDescriptorMap, 2);
  InstallFunc(isolate, descriptor_proto, "unmap",
              wasm::WebAssemblyMemoryMapDescriptorUnmap, 0);
}
References DCHECK, v8::internal::direct_handle(), v8::internal::anonymous_namespace{wasm-js.cc}::InstallConstructorFunc(), v8::internal::anonymous_namespace{wasm-js.cc}::InstallFunc(), and v8::internal::anonymous_namespace{wasm-js.cc}::SetupConstructor().
InstallModule()
void v8::internal::WasmJs::InstallModule (Isolate * isolate, DirectHandle< JSObject > webassembly) [static], [private]
Definition at line 3582 of file wasm-js.cc.
                                                               {
  DirectHandle<JSGlobalObject> global = isolate->global_object();
  DirectHandle<NativeContext> native_context(global->native_context(), isolate);
  DirectHandle<JSFunction> module_constructor;
  if (v8_flags.js_source_phase_imports) {
    DirectHandle<FunctionTemplateInfo>
        intrinsic_abstract_module_source_interface_template =
            NewFunctionTemplate(isolate, nullptr, false);
    DirectHandle<JSObject> abstract_module_source_prototype =
        DirectHandle<JSObject>(
            native_context->abstract_module_source_prototype(), isolate);
    ApiNatives::AddDataProperty(
        isolate, intrinsic_abstract_module_source_interface_template,
        isolate->factory()->prototype_string(),
        abstract_module_source_prototype, NONE);
    // Check that this is a reinstallation of the Module object.
    DirectHandle<String> name = v8_str(isolate, "Module");
    CHECK(
        JSObject::HasRealNamedProperty(isolate, webassembly, name).ToChecked());
    // Reinstall the Module object with AbstractModuleSource as prototype.
    module_constructor =
        CreateFunc(isolate, name, wasm::WebAssemblyModule, true,
                   SideEffectType::kHasNoSideEffect,
                   intrinsic_abstract_module_source_interface_template);
    // WebAssembly.Module is a subclass of %AbstractModuleSource%, hence
    // Object.GetPrototypeOf(WebAssembly.Module) === %AbstractModuleSource%.
    JSObject::ForceSetPrototype(
        isolate, module_constructor,
        direct_handle(native_context->abstract_module_source_function(),
                      isolate));
    module_constructor->shared()->set_length(1);
    JSObject::SetOwnPropertyIgnoreAttributes(webassembly, name,
                                             module_constructor, DONT_ENUM)
        .Assert();
  } else {
    module_constructor = InstallConstructorFunc(isolate, webassembly, "Module",
                                                wasm::WebAssemblyModule);
  }
  SetupConstructor(isolate, module_constructor, WASM_MODULE_OBJECT_TYPE,
                   WasmModuleObject::kHeaderSize, "WebAssembly.Module");
  native_context->set_wasm_module_constructor(*module_constructor);
  InstallFunc(isolate, module_constructor, "imports",
              wasm::WebAssemblyModuleImports, 1, false, NONE,
              SideEffectType::kHasNoSideEffect);
  InstallFunc(isolate, module_constructor, "exports",
              wasm::WebAssemblyModuleExports, 1, false, NONE,
              SideEffectType::kHasNoSideEffect);
  InstallFunc(isolate, module_constructor, "customSections",
              wasm::WebAssemblyModuleCustomSections, 2, false, NONE,
              SideEffectType::kHasNoSideEffect);
}
References CHECK, v8::internal::anonymous_namespace{wasm-js.cc}::CreateFunc(), v8::internal::direct_handle(), v8::internal::DONT_ENUM, v8::internal::Isolate::factory(), v8::internal::Isolate::global_object(), v8::internal::anonymous_namespace{wasm-js.cc}::InstallConstructorFunc(), v8::internal::anonymous_namespace{wasm-js.cc}::InstallFunc(), v8::kHasNoSideEffect, name, v8::internal::native_context, v8::NewFunctionTemplate(), v8::internal::NONE, v8::internal::anonymous_namespace{wasm-js.cc}::SetupConstructor(), v8::internal::v8_flags, and v8::anonymous_namespace{wasm-js.cc}::v8_str().
InstallResizableBufferIntegration()
void v8::internal::WasmJs::InstallResizableBufferIntegration (Isolate * isolate, DirectHandle< NativeContext > context, DirectHandle< JSObject > webassembly) [static], [private]
Definition at line 3932 of file wasm-js.cc.
                                        {
  // Extensibility of the `WebAssembly` object should already have been checked
  // by the caller.
  DCHECK(webassembly->map()->is_extensible());
  DirectHandle<JSObject> memory_proto = direct_handle(
      Cast<JSObject>(context->wasm_memory_constructor()->instance_prototype()),
      isolate);
  InstallFunc(isolate, memory_proto, "toFixedLengthBuffer",
              wasm::WebAssemblyMemoryToFixedLengthBuffer, 0);
  InstallFunc(isolate, memory_proto, "toResizableBuffer",
              wasm::WebAssemblyMemoryToResizableBuffer, 0);
}
References DCHECK, v8::internal::direct_handle(), and v8::internal::anonymous_namespace{wasm-js.cc}::InstallFunc().
InstallTypeReflection()
bool v8::internal::WasmJs::InstallTypeReflection (Isolate * isolate, DirectHandle< NativeContext > context, DirectHandle< JSObject > webassembly) [static], [private]
Definition at line 3847 of file wasm-js.cc.
                                                                       {
  // Extensibility of the `WebAssembly` object should already have been checked
  // by the caller.
  DCHECK(webassembly->map()->is_extensible());
  // First check if any of the type reflection fields already exist. If so, bail
  // out and don't install any new fields.
  if (JSObject::HasRealNamedProperty(isolate, webassembly,
                                     isolate->factory()->Function_string())
          .FromMaybe(true)) {
    return false;
  }
  auto GetProto = [isolate](Tagged<JSFunction> constructor) {
    return handle(Cast<JSObject>(constructor->instance_prototype()), isolate);
  };
  DirectHandle<JSObject> table_proto =
      GetProto(context->wasm_table_constructor());
  DirectHandle<JSObject> global_proto =
      GetProto(context->wasm_global_constructor());
  DirectHandle<JSObject> memory_proto =
      GetProto(context->wasm_memory_constructor());
  DirectHandle<JSObject> tag_proto = GetProto(context->wasm_tag_constructor());
  DirectHandle<String> type_string = v8_str(isolate, "type");
  auto CheckProto = [isolate, type_string](DirectHandle<JSObject> proto) {
    if (JSObject::HasRealNamedProperty(isolate, proto, type_string)
            .FromMaybe(true)) {
      return false;
    }
    // Also check extensibility, otherwise adding properties will fail.
    if (!proto->map()->is_extensible()) return false;
    return true;
  };
  if (!CheckProto(table_proto)) return false;
  if (!CheckProto(global_proto)) return false;
  if (!CheckProto(memory_proto)) return false;
  if (!CheckProto(tag_proto)) return false;
  // Checks are done, start installing the new fields.
  InstallFunc(isolate, table_proto, type_string, WebAssemblyTableType, 0, false,
              NONE, SideEffectType::kHasNoSideEffect);
  InstallFunc(isolate, memory_proto, type_string, WebAssemblyMemoryType, 0,
              false, NONE, SideEffectType::kHasNoSideEffect);
  InstallFunc(isolate, global_proto, type_string, WebAssemblyGlobalType, 0,
              false, NONE, SideEffectType::kHasNoSideEffect);
  InstallFunc(isolate, tag_proto, type_string, WebAssemblyTagType, 0, false,
              NONE, SideEffectType::kHasNoSideEffect);
  // Create the Function object.
  DirectHandle<JSFunction> function_constructor = InstallConstructorFunc(
      isolate, webassembly, "Function", WebAssemblyFunction);
  SetDummyInstanceTemplate(isolate, function_constructor);
  JSFunction::EnsureHasInitialMap(isolate, function_constructor);
  DirectHandle<JSObject> function_proto(
      Cast<JSObject>(function_constructor->instance_prototype()), isolate);
  DirectHandle<Map> function_map =
      Map::Copy(isolate, isolate->sloppy_function_without_prototype_map(),
                "WebAssembly.Function");
  CHECK(JSObject::SetPrototype(
            isolate, function_proto,
            direct_handle(context->function_function()->prototype(), isolate),
            false, kDontThrow)
            .FromJust());
  JSFunction::SetInitialMap(isolate, function_constructor, function_map,
                            function_proto);
  constexpr PropertyAttributes ro_attributes =
      static_cast<PropertyAttributes>(DONT_ENUM | READ_ONLY);
  JSObject::AddProperty(isolate, function_proto,
                        isolate->factory()->to_string_tag_symbol(),
                        v8_str(isolate, "WebAssembly.Function"), ro_attributes);
  InstallFunc(isolate, function_proto, type_string, WebAssemblyFunctionType, 0);
  SimpleInstallFunction(isolate, function_proto, "bind",
                        Builtin::kWebAssemblyFunctionPrototypeBind, 1,
                        kDontAdapt);
  // Make all exported functions an instance of {WebAssembly.Function}.
  context->set_wasm_exported_function_map(*function_map);
  return true;
}
References CHECK, v8::bigint::anonymous_namespace{div-helpers.cc}::Copy(), DCHECK, v8::internal::direct_handle(), v8::internal::DONT_ENUM, v8::internal::Isolate::factory(), v8::internal::libvtune::function_map, v8::internal::handle(), v8::internal::anonymous_namespace{wasm-js.cc}::InstallConstructorFunc(), v8::internal::anonymous_namespace{wasm-js.cc}::InstallFunc(), v8::internal::kDontAdapt, v8::internal::kDontThrow, v8::kHasNoSideEffect, v8::internal::NONE, v8::internal::READ_ONLY, v8::internal::anonymous_namespace{wasm-js.cc}::SetDummyInstanceTemplate(), v8::internal::SimpleInstallFunction(), v8::anonymous_namespace{wasm-js.cc}::v8_str(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyFunction(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyFunctionType(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyGlobalType(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryType(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableType(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTagType().
PrepareForSnapshot()
void v8::internal::WasmJs::PrepareForSnapshot (Isolate * isolate) [static]
Definition at line 3413 of file wasm-js.cc.
                                                {
  DirectHandle<JSGlobalObject> global = isolate->global_object();
  DirectHandle<NativeContext> native_context(global->native_context(), isolate);
  CHECK(IsUndefined(
      native_context->GetNoCell(Context::WASM_WEBASSEMBLY_OBJECT_INDEX),
      isolate));
  CHECK(IsUndefined(
      native_context->GetNoCell(Context::WASM_MODULE_CONSTRUCTOR_INDEX),
      isolate));
  Factory* const f = isolate->factory();
  static constexpr PropertyAttributes ro_attributes =
      static_cast<PropertyAttributes>(DONT_ENUM | READ_ONLY);
  // Create the WebAssembly object.
  DirectHandle<JSObject> webassembly;
  {
    DirectHandle<String> WebAssembly_string = v8_str(isolate, "WebAssembly");
    // Not supposed to be called, hence using the kIllegal builtin as code.
    DirectHandle<SharedFunctionInfo> sfi = f->NewSharedFunctionInfoForBuiltin(
        WebAssembly_string, Builtin::kIllegal, 0, kDontAdapt);
    sfi->set_language_mode(LanguageMode::kStrict);
    DirectHandle<JSFunction> ctor =
        Factory::JSFunctionBuilder{isolate, sfi, native_context}.Build();
    JSFunction::SetPrototype(isolate, ctor,
                             isolate->initial_object_prototype());
    webassembly = f->NewJSObject(ctor, AllocationType::kOld);
    native_context->set_wasm_webassembly_object(*webassembly);
    JSObject::AddProperty(isolate, webassembly, f->to_string_tag_symbol(),
                          WebAssembly_string, ro_attributes);
    InstallFunc(isolate, webassembly, "compile", wasm::WebAssemblyCompile, 1);
    InstallFunc(isolate, webassembly, "validate", wasm::WebAssemblyValidate, 1);
    InstallFunc(isolate, webassembly, "instantiate",
                wasm::WebAssemblyInstantiate, 1);
  }
  // Create the Module object.
  InstallModule(isolate, webassembly);
  // Create the Instance object.
  {
    DirectHandle<JSFunction> instance_constructor = InstallConstructorFunc(
        isolate, webassembly, "Instance", wasm::WebAssemblyInstance);
    DirectHandle<JSObject> instance_proto = SetupConstructor(
        isolate, instance_constructor, WASM_INSTANCE_OBJECT_TYPE,
        WasmInstanceObject::kHeaderSize, "WebAssembly.Instance");
    native_context->set_wasm_instance_constructor(*instance_constructor);
    InstallGetter(isolate, instance_proto, "exports",
                  wasm::WebAssemblyInstanceGetExports);
  }
  // Create the Table object.
  {
    DirectHandle<JSFunction> table_constructor = InstallConstructorFunc(
        isolate, webassembly, "Table", wasm::WebAssemblyTable);
    DirectHandle<JSObject> table_proto =
        SetupConstructor(isolate, table_constructor, WASM_TABLE_OBJECT_TYPE,
                         WasmTableObject::kHeaderSize, "WebAssembly.Table");
    native_context->set_wasm_table_constructor(*table_constructor);
    InstallGetter(isolate, table_proto, "length",
                  wasm::WebAssemblyTableGetLength);
    InstallFunc(isolate, table_proto, "grow", wasm::WebAssemblyTableGrow, 1);
    InstallFunc(isolate, table_proto, "set", wasm::WebAssemblyTableSet, 1);
    InstallFunc(isolate, table_proto, "get", wasm::WebAssemblyTableGet, 1,
                false, NONE, SideEffectType::kHasNoSideEffect);
  }
  // Create the Memory object.
  {
    DirectHandle<JSFunction> memory_constructor = InstallConstructorFunc(
        isolate, webassembly, "Memory", wasm::WebAssemblyMemory);
    DirectHandle<JSObject> memory_proto =
        SetupConstructor(isolate, memory_constructor, WASM_MEMORY_OBJECT_TYPE,
                         WasmMemoryObject::kHeaderSize, "WebAssembly.Memory");
    native_context->set_wasm_memory_constructor(*memory_constructor);
    InstallFunc(isolate, memory_proto, "grow", wasm::WebAssemblyMemoryGrow, 1);
    InstallGetter(isolate, memory_proto, "buffer",
                  wasm::WebAssemblyMemoryGetBuffer);
  }
  // Create the Global object.
  {
    DirectHandle<JSFunction> global_constructor = InstallConstructorFunc(
        isolate, webassembly, "Global", wasm::WebAssemblyGlobal);
    DirectHandle<JSObject> global_proto =
        SetupConstructor(isolate, global_constructor, WASM_GLOBAL_OBJECT_TYPE,
                         WasmGlobalObject::kHeaderSize, "WebAssembly.Global");
    native_context->set_wasm_global_constructor(*global_constructor);
    InstallFunc(isolate, global_proto, "valueOf",
                wasm::WebAssemblyGlobalValueOf, 0, false, NONE,
                SideEffectType::kHasNoSideEffect);
    InstallGetterSetter(isolate, global_proto, "value",
                        wasm::WebAssemblyGlobalGetValue,
                        wasm::WebAssemblyGlobalSetValue);
  }
  // Create the Exception object.
  {
    DirectHandle<JSFunction> tag_constructor = InstallConstructorFunc(
        isolate, webassembly, "Tag", wasm::WebAssemblyTag);
    SetupConstructor(isolate, tag_constructor, WASM_TAG_OBJECT_TYPE,
                     WasmTagObject::kHeaderSize, "WebAssembly.Tag");
    native_context->set_wasm_tag_constructor(*tag_constructor);
    auto js_tag = WasmExceptionTag::New(isolate, 0);
    // Note the canonical_type_index is reset in WasmJs::Install s.t.
    // type_canonicalizer bookkeeping remains valid.
    static constexpr wasm::CanonicalTypeIndex kInitialCanonicalTypeIndex{0};
    DirectHandle<JSObject> js_tag_object = WasmTagObject::New(
        isolate, &kWasmExceptionTagSignature, kInitialCanonicalTypeIndex,
        js_tag, DirectHandle<WasmTrustedInstanceData>());
    native_context->set_wasm_js_tag(*js_tag_object);
    JSObject::AddProperty(isolate, webassembly, "JSTag", js_tag_object,
                          ro_attributes);
  }
  // Set up the runtime exception constructor.
  {
    DirectHandle<JSFunction> exception_constructor = InstallConstructorFunc(
        isolate, webassembly, "Exception", wasm::WebAssemblyException);
    SetDummyInstanceTemplate(isolate, exception_constructor);
    DirectHandle<JSObject> exception_proto = SetupConstructor(
        isolate, exception_constructor, WASM_EXCEPTION_PACKAGE_TYPE,
        WasmExceptionPackage::kSize, "WebAssembly.Exception",
        WasmExceptionPackage::kInObjectFieldCount);
    InstallFunc(isolate, exception_proto, "getArg",
                wasm::WebAssemblyExceptionGetArg, 2);
    InstallFunc(isolate, exception_proto, "is", wasm::WebAssemblyExceptionIs,
                1);
    native_context->set_wasm_exception_constructor(*exception_constructor);
    DirectHandle<Map> initial_map(exception_constructor->initial_map(),
                                  isolate);
    Map::EnsureDescriptorSlack(isolate, initial_map, 2);
    {
      Descriptor d = Descriptor::DataField(
          isolate, f->wasm_exception_tag_symbol(),
          WasmExceptionPackage::kTagIndex, DONT_ENUM, Representation::Tagged());
      initial_map->AppendDescriptor(isolate, &d);
    }
    {
      Descriptor d =
          Descriptor::DataField(isolate, f->wasm_exception_values_symbol(),
                                WasmExceptionPackage::kValuesIndex, DONT_ENUM,
                                Representation::Tagged());
      initial_map->AppendDescriptor(isolate, &d);
    }
  }
  // By default, make all exported functions an instance of {Function}.
  {
    DirectHandle<Map> function_map =
        isolate->sloppy_function_without_prototype_map();
    native_context->set_wasm_exported_function_map(*function_map);
  }
  // Setup errors.
  {
    InstallError(isolate, webassembly, f->CompileError_string(),
                 Context::WASM_COMPILE_ERROR_FUNCTION_INDEX);
    InstallError(isolate, webassembly, f->LinkError_string(),
                 Context::WASM_LINK_ERROR_FUNCTION_INDEX);
    InstallError(isolate, webassembly, f->RuntimeError_string(),
                 Context::WASM_RUNTIME_ERROR_FUNCTION_INDEX);
  }
}
References CHECK, v8::internal::DONT_ENUM, v8::internal::Isolate::factory(), v8::internal::libvtune::function_map, v8::internal::Isolate::global_object(), v8::internal::compiler::initial_map, v8::internal::anonymous_namespace{wasm-js.cc}::InstallConstructorFunc(), v8::internal::InstallError(), v8::internal::anonymous_namespace{wasm-js.cc}::InstallFunc(), v8::internal::anonymous_namespace{wasm-js.cc}::InstallGetter(), v8::internal::anonymous_namespace{wasm-js.cc}::InstallGetterSetter(), v8::internal::kDontAdapt, v8::kHasNoSideEffect, v8::internal::anonymous_namespace{wasm-js.cc}::kWasmExceptionTagSignature, v8::internal::native_context, v8::internal::anonymous_namespace{intl-objects.cc}::New(), v8::internal::Factory::NewJSObject(), v8::internal::Factory::NewSharedFunctionInfoForBuiltin(), v8::internal::NONE, v8::internal::READ_ONLY, v8::internal::anonymous_namespace{wasm-js.cc}::SetDummyInstanceTemplate(), v8::internal::anonymous_namespace{wasm-js.cc}::SetupConstructor(), v8::internal::Tagged(), and v8::anonymous_namespace{wasm-js.cc}::v8_str().
Referenced by v8::internal::Genesis::Genesis().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-js.h
/mnt/V8SourceCode/src/wasm/wasm-js.cc