v8::internal::compiler::turboshaft::LoopFinder Class Reference
#include <loop-finder.h>
Classes
struct BlockCmp
struct LoopInfo
Public Types
enum class ConfigFlags : uint8_t { kFindCalls
 }
using Config = base::EnumSet< ConfigFlags, int8_t >
Public Member Functions
LoopFinder (Zone *phase_zone, const Graph *input_graph, Config config)
const ZoneUnorderedMap< const Block *, LoopInfo > & LoopHeaders () const
const Block * GetLoopHeader (const Block *block) const
LoopInfo GetLoopInfo (const Block *block) const
ZoneSet< const Block *, BlockCmp > GetLoopBody (const Block *loop_header)
Private Member Functions
void Run ()
LoopInfo VisitLoop (const Block *header)
void CollectLoopInfo (const Block *block, LoopInfo *info)
Private Attributes
Zone * phase_zone_
const Graph * input_graph_
Config config_
FixedBlockSidetable< const Block * > loop_headers_
ZoneUnorderedMap< const Block *, LoopInfo > loop_header_info_
ZoneVector< const Block * > queue_
Detailed Description
Definition at line 15 of file loop-finder.h.
Member Typedef Documentation
Config
using v8::internal::compiler::turboshaft::LoopFinder::Config = base::EnumSet<ConfigFlags, int8_t>
Definition at line 47 of file loop-finder.h.
Member Enumeration Documentation
ConfigFlags
enum v8::internal::compiler::turboshaft::LoopFinder::ConfigFlags : uint8_t [strong]
Enumerator
kFindCalls
Definition at line 46 of file loop-finder.h.
: uint8_t { kFindCalls };
Constructor & Destructor Documentation
LoopFinder()
v8::internal::compiler::turboshaft::LoopFinder::LoopFinder (Zone * phase_zone, const Graph * input_graph, Config config) [inline]
Definition at line 63 of file loop-finder.h.
      : phase_zone_(phase_zone),
        input_graph_(input_graph),
        config_(config),
        loop_headers_(input_graph->block_count(), nullptr, phase_zone),
        loop_header_info_(phase_zone),
        queue_(phase_zone) {
    Run();
  }
Member Function Documentation
CollectLoopInfo()
void v8::internal::compiler::turboshaft::LoopFinder::CollectLoopInfo (const Block * block, LoopInfo * info) [private]
Definition at line 19 of file loop-finder.cc.
                                                                   {
  if (!config_.contains(ConfigFlags::kFindCalls)) return;
  if (info->has_any_call) return;
  for (const Operation& op : input_graph_->operations(*block)) {
    if (op.Is<CallOp>()) {
      info->has_any_call = true;
      return;
    }
  }
}
References config_, v8::base::EnumSet< E, T >::contains(), v8::internal::compiler::turboshaft::LoopFinder::LoopInfo::has_any_call, input_graph_, kFindCalls, and v8::internal::compiler::turboshaft::Graph::operations().
Referenced by VisitLoop().
GetLoopBody()
ZoneSet< const Block *, LoopFinder::BlockCmp > v8::internal::compiler::turboshaft::LoopFinder::GetLoopBody (const Block * loop_header)
Definition at line 90 of file loop-finder.cc.
                              {
  DCHECK(!GetLoopInfo(loop_header).has_inner_loops);
  ZoneSet<const Block*, BlockCmp> body(phase_zone_);
  body.insert(loop_header);
  ZoneVector<const Block*> queue(phase_zone_);
  queue.push_back(loop_header->LastPredecessor());
  while (!queue.empty()) {
    const Block* curr = queue.back();
    queue.pop_back();
    if (body.find(curr) != body.end()) continue;
    body.insert(curr);
    for (const Block* pred = curr->LastPredecessor(); pred != nullptr;
         pred = pred->NeighboringPredecessor()) {
      if (pred == loop_header) continue;
      queue.push_back(pred);
    }
  }
  return body;
}
References v8::internal::ZoneVector< T >::back(), v8::internal::DCHECK(), v8::internal::ZoneVector< T >::empty(), GetLoopInfo(), v8::internal::compiler::turboshaft::Block::LastPredecessor(), v8::internal::compiler::turboshaft::Block::NeighboringPredecessor(), phase_zone_, v8::internal::ZoneVector< T >::pop_back(), and v8::internal::ZoneVector< T >::push_back().
Referenced by v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::PeelFirstIteration().
GetLoopHeader()
const Block* v8::internal::compiler::turboshaft::LoopFinder::GetLoopHeader (const Block * block) const [inline]
Definition at line 76 of file loop-finder.h.
                                                       {
    return loop_headers_[block->index()];
  }
References v8::internal::compiler::turboshaft::Block::index().
Referenced by v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::GetLoopIterationCount(), and v8::internal::compiler::turboshaft::AnalyzerIterator::Next().
GetLoopInfo()
LoopInfo v8::internal::compiler::turboshaft::LoopFinder::GetLoopInfo (const Block * block) const [inline]
Definition at line 79 of file loop-finder.h.
                                                 {
    DCHECK(block->IsLoop());
    auto it = loop_header_info_.find(block);
    DCHECK_NE(it, loop_header_info_.end());
    return it->second;
  }
References v8::internal::DCHECK(), DCHECK_NE, and v8::internal::compiler::turboshaft::Block::IsLoop().
Referenced by v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::CanPeelLoop(), and GetLoopBody().
LoopHeaders()
const ZoneUnorderedMap<const Block*, LoopInfo>& v8::internal::compiler::turboshaft::LoopFinder::LoopHeaders () const [inline]
Definition at line 73 of file loop-finder.h.
                                                                      {
    return loop_header_info_;
  }
Referenced by v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::DetectUnrollableLoops().
Run()
void v8::internal::compiler::turboshaft::LoopFinder::Run () [private]
Definition at line 9 of file loop-finder.cc.
                     {
  ZoneVector<Block*> all_loops(phase_zone_);
  for (const Block& block : base::Reversed(input_graph_->blocks())) {
    if (block.IsLoop()) {
      LoopInfo info = VisitLoop(&block);
      loop_header_info_.insert({&block, info});
    }
  }
}
References v8::internal::compiler::turboshaft::Graph::blocks(), input_graph_, loop_header_info_, phase_zone_, v8::base::Reversed(), and VisitLoop().
VisitLoop()
LoopFinder::LoopInfo v8::internal::compiler::turboshaft::LoopFinder::VisitLoop (const Block * header) [private]
Definition at line 33 of file loop-finder.cc.
                                                            {
  Block* backedge = header->LastPredecessor();
  DCHECK(backedge->LastOperation(*input_graph_).Is<GotoOp>());
  DCHECK_EQ(backedge->LastOperation(*input_graph_).Cast<GotoOp>().destination,
            header);
  DCHECK_GE(backedge->index().id(), header->index().id());
  LoopInfo info;
  // The header is skipped by the while-loop below, so we initialize {info} with
  // the `op_count` from {header}, and a `block_count` of 1 (= the header).
  info.op_count = header->OpCountUpperBound();
  info.start = header;
  info.end = backedge;
  info.block_count = 1;
  CollectLoopInfo(header, &info);
  queue_.clear();
  queue_.push_back(backedge);
  while (!queue_.empty()) {
    const Block* curr = queue_.back();
    queue_.pop_back();
    if (curr == header) continue;
    if (loop_headers_[curr->index()] != nullptr) {
      const Block* curr_parent = loop_headers_[curr->index()];
      if (curr_parent == header) {
        // If {curr}'s parent is already marked as being {header}, then we've
        // already visited {curr}.
        continue;
      } else {
        // If {curr}'s parent is not {header}, then {curr} is part of an inner
        // loop. We should continue the search on the loop header: the
        // predecessors of {curr} will all be in this inner loop.
        queue_.push_back(curr_parent);
        info.has_inner_loops = true;
        continue;
      }
    }
    info.block_count++;
    info.op_count += curr->OpCountUpperBound();
    loop_headers_[curr->index()] = header;
    CollectLoopInfo(curr, &info);
    const Block* pred_start = curr->LastPredecessor();
    if (curr->IsLoop()) {
      // Skipping the backedge of inner loops since we don't want to visit inner
      // loops now (they should already have been visited).
      DCHECK_NOT_NULL(pred_start);
      pred_start = pred_start->NeighboringPredecessor();
      info.has_inner_loops = true;
    }
    for (const Block* pred : NeighboringPredecessorIterable(pred_start)) {
      queue_.push_back(pred);
    }
  }
  return info;
}
References v8::internal::compiler::turboshaft::LoopFinder::LoopInfo::block_count, v8::internal::compiler::turboshaft::Operation::Cast(), CollectLoopInfo(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, DCHECK_NOT_NULL, v8::internal::compiler::turboshaft::GotoOp::destination, v8::internal::compiler::turboshaft::LoopFinder::LoopInfo::end, v8::internal::compiler::turboshaft::LoopFinder::LoopInfo::has_inner_loops, v8::internal::compiler::turboshaft::BlockIndex::id(), v8::internal::compiler::turboshaft::Block::index(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::turboshaft::Block::IsLoop(), v8::internal::compiler::turboshaft::Block::LastOperation(), v8::internal::compiler::turboshaft::Block::LastPredecessor(), loop_headers_, v8::internal::compiler::turboshaft::Block::NeighboringPredecessor(), v8::internal::compiler::turboshaft::LoopFinder::LoopInfo::op_count, v8::internal::compiler::turboshaft::Block::OpCountUpperBound(), queue_, and v8::internal::compiler::turboshaft::LoopFinder::LoopInfo::start.
Referenced by Run().
Member Data Documentation
config_
Config v8::internal::compiler::turboshaft::LoopFinder::config_ [private]
Definition at line 103 of file loop-finder.h.
Referenced by CollectLoopInfo().
input_graph_
const Graph* v8::internal::compiler::turboshaft::LoopFinder::input_graph_ [private]
Definition at line 102 of file loop-finder.h.
Referenced by CollectLoopInfo(), and Run().
loop_header_info_
ZoneUnorderedMap<const Block*, LoopInfo> v8::internal::compiler::turboshaft::LoopFinder::loop_header_info_ [private]
Definition at line 117 of file loop-finder.h.
Referenced by Run().
loop_headers_
FixedBlockSidetable<const Block*> v8::internal::compiler::turboshaft::LoopFinder::loop_headers_ [private]
Definition at line 113 of file loop-finder.h.
Referenced by VisitLoop().
phase_zone_
Zone* v8::internal::compiler::turboshaft::LoopFinder::phase_zone_ [private]
Definition at line 101 of file loop-finder.h.
Referenced by GetLoopBody(), and Run().
queue_
ZoneVector<const Block*> v8::internal::compiler::turboshaft::LoopFinder::queue_ [private]
Definition at line 121 of file loop-finder.h.
Referenced by VisitLoop().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/loop-finder.h
/mnt/V8SourceCode/src/compiler/turboshaft/loop-finder.cc