v8::internal::tracing::TraceID Class Reference
#include <trace-event.h>
Classes
class WithScope
Public Member Functions
TraceID (const void *raw_id, unsigned int *flags)
TraceID (uint64_t raw_id, unsigned int *flags)
TraceID (unsigned int raw_id, unsigned int *flags)
TraceID (uint16_t raw_id, unsigned int *flags)
TraceID (unsigned char raw_id, unsigned int *flags)
TraceID (int64_t raw_id, unsigned int *flags)
TraceID (int raw_id, unsigned int *flags)
TraceID (int16_t raw_id, unsigned int *flags)
TraceID (signed char raw_id, unsigned int *flags)
TraceID (WithScope scoped_id, unsigned int *flags)
uint64_t raw_id () const
const char * scope () const
Private Attributes
const char * scope_ = nullptr
uint64_t raw_id_
Detailed Description
Definition at line 318 of file trace-event.h.
Constructor & Destructor Documentation
TraceID() [1/10]
v8::internal::tracing::TraceID::TraceID (const void * raw_id, unsigned int * flags) [inline]
Definition at line 332 of file trace-event.h.
      : raw_id_(static_cast<uint64_t>(reinterpret_cast<uintptr_t>(raw_id))) {}
TraceID() [2/10]
v8::internal::tracing::TraceID::TraceID (uint64_t raw_id, unsigned int * flags) [inline]
Definition at line 334 of file trace-event.h.
                                                : raw_id_(raw_id) {
    (void)flags;
  }
References v8::internal::flags, and v8::internal::wasm::void().
TraceID() [3/10]
v8::internal::tracing::TraceID::TraceID (unsigned int raw_id, unsigned int * flags) [inline]
Definition at line 337 of file trace-event.h.
                                                    : raw_id_(raw_id) {
    (void)flags;
  }
References v8::internal::flags, and v8::internal::wasm::void().
TraceID() [4/10]
v8::internal::tracing::TraceID::TraceID (uint16_t raw_id, unsigned int * flags) [inline]
Definition at line 340 of file trace-event.h.
                                                : raw_id_(raw_id) {
    (void)flags;
  }
References v8::internal::flags, and v8::internal::wasm::void().
TraceID() [5/10]
v8::internal::tracing::TraceID::TraceID (unsigned char raw_id, unsigned int * flags) [inline]
Definition at line 343 of file trace-event.h.
                                                     : raw_id_(raw_id) {
    (void)flags;
  }
References v8::internal::flags, and v8::internal::wasm::void().
TraceID() [6/10]
v8::internal::tracing::TraceID::TraceID (int64_t raw_id, unsigned int * flags) [inline]
Definition at line 346 of file trace-event.h.
      : raw_id_(static_cast<uint64_t>(raw_id)) {
    (void)flags;
  }
References v8::internal::flags, and v8::internal::wasm::void().
TraceID() [7/10]
v8::internal::tracing::TraceID::TraceID (int raw_id, unsigned int * flags) [inline]
Definition at line 350 of file trace-event.h.
      : raw_id_(static_cast<uint64_t>(raw_id)) {
    (void)flags;
  }
References v8::internal::flags, and v8::internal::wasm::void().
TraceID() [8/10]
v8::internal::tracing::TraceID::TraceID (int16_t raw_id, unsigned int * flags) [inline]
Definition at line 354 of file trace-event.h.
      : raw_id_(static_cast<uint64_t>(raw_id)) {
    (void)flags;
  }
References v8::internal::flags, and v8::internal::wasm::void().
TraceID() [9/10]
v8::internal::tracing::TraceID::TraceID (signed char raw_id, unsigned int * flags) [inline]
Definition at line 358 of file trace-event.h.
      : raw_id_(static_cast<uint64_t>(raw_id)) {
    (void)flags;
  }
References v8::internal::flags, and v8::internal::wasm::void().
TraceID() [10/10]
v8::internal::tracing::TraceID::TraceID (WithScope scoped_id, unsigned int * flags) [inline]
Definition at line 362 of file trace-event.h.
      : scope_(scoped_id.scope()), raw_id_(scoped_id.raw_id()) {}
Member Function Documentation
raw_id()
uint64_t v8::internal::tracing::TraceID::raw_id () const [inline]
Definition at line 365 of file trace-event.h.
{ return raw_id_; }
References raw_id_.
scope()
const char* v8::internal::tracing::TraceID::scope () const [inline]
Definition at line 366 of file trace-event.h.
{ return scope_; }
References scope_.
Member Data Documentation
raw_id_
uint64_t v8::internal::tracing::TraceID::raw_id_ [private]
Definition at line 370 of file trace-event.h.
Referenced by raw_id().
scope_
const char* v8::internal::tracing::TraceID::scope_ = nullptr [private]
Definition at line 369 of file trace-event.h.
Referenced by scope().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/tracing/trace-event.h