v8::FixedArray Class Reference
A fixed-sized array with elements of type Data.
#include <v8-data.h>
Public Member Functions
int Length () const
Local< Data > Get (Local< Context > context, int i) const
Static Public Member Functions
static FixedArray * Cast (Data *data)
Static Private Member Functions
static void CheckCast (Data *obj)
Detailed Description
A fixed-sized array with elements of type Data.
Definition at line 72 of file v8-data.h.
Member Function Documentation
Cast()
static FixedArray* v8::FixedArray::Cast (Data * data) [inline], [static]
Definition at line 77 of file v8-data.h.
                                                {
#ifdef V8_ENABLE_CHECKS
    CheckCast(data);
#endif
    return reinterpret_cast<FixedArray*>(data);
  }
CheckCast()
void v8::FixedArray::CheckCast (v8::Data * that) [static], [private]
Definition at line 3904 of file api.cc.
                                         {
  auto obj = Utils::OpenDirectHandle(that);
  Utils::ApiCheck(i::IsFixedArray(*obj), "v8::FixedArray::Cast",
                  "Value is not a FixedArray");
}
References v8::Utils::ApiCheck(), and v8::Utils::OpenDirectHandle().
Get()
Local< Data > v8::FixedArray::Get (Local< Context > context, int i) const
Definition at line 2107 of file api.cc.
                                                               {
  auto self = Utils::OpenDirectHandle(this);
  auto i_isolate = i::Isolate::Current();
  CHECK_LT(i, self->length());
  return ToApiHandle<Data>(i::direct_handle(self->get(i), i_isolate));
}
References CHECK_LT, v8::internal::Isolate::Current(), v8::internal::direct_handle(), and v8::Utils::OpenDirectHandle().
Length()
int v8::FixedArray::Length () const
Definition at line 2103 of file api.cc.
                             {
  return Utils::OpenDirectHandle(this)->length();
}
References v8::Utils::OpenDirectHandle().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-data.h
/mnt/V8SourceCode/src/api/api.cc