v8::internal::ObjectHashTableShapeBase Class Reference
#include <hash-table.h>
Static Public Member Functions
static bool IsMatch (DirectHandle< Object > key, Tagged< Object > other)
static uint32_t Hash (ReadOnlyRoots roots, DirectHandle< Object > key)
static uint32_t HashForObject (ReadOnlyRoots roots, Tagged< Object > object)
static DirectHandle< Object > AsHandle (DirectHandle< Object > key)
Static Public Attributes
static const int kPrefixSize = 0
static const int kEntryValueIndex = 1
static const int kEntrySize = 2
static const bool kMatchNeedsHoleCheck = false
Additional Inherited Members
Detailed Description
Definition at line 353 of file hash-table.h.
Member Function Documentation
AsHandle()
DirectHandle< Object > v8::internal::ObjectHashTableShapeBase::AsHandle (DirectHandle< Object > key) [inline], [static]
Definition at line 2022 of file objects-inl.h.
                              {
  return key;
}
References v8::internal::key.
Hash()
uint32_t v8::internal::ObjectHashTableShapeBase::Hash (ReadOnlyRoots roots, DirectHandle< Object > key) [inline], [static]
Definition at line 294 of file hash-table-inl.h.
                                                                  {
  return Smi::ToInt(Object::GetHash(*key));
}
References v8::internal::Object::GetHash(), v8::internal::key, and v8::internal::Smi::ToInt().
HashForObject()
uint32_t v8::internal::ObjectHashTableShapeBase::HashForObject (ReadOnlyRoots roots, Tagged< Object > object) [inline], [static]
Definition at line 299 of file hash-table-inl.h.
                                                                       {
  return Smi::ToInt(Object::GetHash(other));
}
References v8::internal::Object::GetHash(), and v8::internal::Smi::ToInt().
IsMatch()
bool v8::internal::ObjectHashTableShapeBase::IsMatch (DirectHandle< Object > key, Tagged< Object > other) [inline], [static]
Definition at line 260 of file hash-table-inl.h.
                                                             {
  return Object::SameValue(*key, other);
}
References v8::internal::key, and v8::internal::Object::SameValue().
Member Data Documentation
kEntrySize
const int v8::internal::ObjectHashTableShapeBase::kEntrySize = 2 [static]
Definition at line 362 of file hash-table.h.
kEntryValueIndex
const int v8::internal::ObjectHashTableShapeBase::kEntryValueIndex = 1 [static]
Definition at line 361 of file hash-table.h.
kMatchNeedsHoleCheck
const bool v8::internal::ObjectHashTableShapeBase::kMatchNeedsHoleCheck = false [static]
Definition at line 363 of file hash-table.h.
kPrefixSize
const int v8::internal::ObjectHashTableShapeBase::kPrefixSize = 0 [static]
Definition at line 360 of file hash-table.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/hash-table.h
/mnt/V8SourceCode/src/objects/hash-table-inl.h
/mnt/V8SourceCode/src/objects/objects-inl.h