v8::internal::AssemblerRISCVI Class Reference
#include <base-riscv-i.h>
Public Member Functions
void lui (Register rd, int32_t imm20)
void auipc (Register rd, int32_t imm20)
void jal (Register rd, int32_t imm20)
void jalr (Register rd, Register rs1, int16_t imm12)
void beq (Register rs1, Register rs2, int16_t imm12)
void bne (Register rs1, Register rs2, int16_t imm12)
void blt (Register rs1, Register rs2, int16_t imm12)
void bge (Register rs1, Register rs2, int16_t imm12)
void bltu (Register rs1, Register rs2, int16_t imm12)
void bgeu (Register rs1, Register rs2, int16_t imm12)
void lb (Register rd, Register rs1, int16_t imm12)
void lh (Register rd, Register rs1, int16_t imm12)
void lw (Register rd, Register rs1, int16_t imm12)
void lbu (Register rd, Register rs1, int16_t imm12)
void lhu (Register rd, Register rs1, int16_t imm12)
void sb (Register source, Register base, int16_t imm12)
void sh (Register source, Register base, int16_t imm12)
void sw (Register source, Register base, int16_t imm12)
void addi (Register rd, Register rs1, int16_t imm12)
void slti (Register rd, Register rs1, int16_t imm12)
void sltiu (Register rd, Register rs1, int16_t imm12)
void xori (Register rd, Register rs1, int16_t imm12)
void ori (Register rd, Register rs1, int16_t imm12)
void andi (Register rd, Register rs1, int16_t imm12)
void slli (Register rd, Register rs1, uint8_t shamt)
void srli (Register rd, Register rs1, uint8_t shamt)
void srai (Register rd, Register rs1, uint8_t shamt)
void add (Register rd, Register rs1, Register rs2)
void sub (Register rd, Register rs1, Register rs2)
void sll (Register rd, Register rs1, Register rs2)
void slt (Register rd, Register rs1, Register rs2)
void sltu (Register rd, Register rs1, Register rs2)
void xor_ (Register rd, Register rs1, Register rs2)
void srl (Register rd, Register rs1, Register rs2)
void sra (Register rd, Register rs1, Register rs2)
void or_ (Register rd, Register rs1, Register rs2)
void and_ (Register rd, Register rs1, Register rs2)
void nor (Register rd, Register rs, Register rt)
void fence (uint8_t pred, uint8_t succ)
void fence_tso ()
void ecall ()
void ebreak ()
void sync ()
void unimp ()
int32_t branch_offset (Label *L)
int32_t jump_offset (Label *L)
void beq (Register rs1, Register rs2, Label *L)
void bne (Register rs1, Register rs2, Label *L)
void blt (Register rs1, Register rs2, Label *L)
void bge (Register rs1, Register rs2, Label *L)
void bltu (Register rs1, Register rs2, Label *L)
void bgeu (Register rs1, Register rs2, Label *L)
void beqz (Register rs, int16_t imm13)
void beqz (Register rs1, Label *L)
void bnez (Register rs, int16_t imm13)
void bnez (Register rs1, Label *L)
void blez (Register rs, int16_t imm13)
void blez (Register rs1, Label *L)
void bgez (Register rs, int16_t imm13)
void bgez (Register rs1, Label *L)
void bltz (Register rs, int16_t imm13)
void bltz (Register rs1, Label *L)
void bgtz (Register rs, int16_t imm13)
void bgtz (Register rs1, Label *L)
void bgt (Register rs1, Register rs2, int16_t imm13)
void bgt (Register rs1, Register rs2, Label *L)
void ble (Register rs1, Register rs2, int16_t imm13)
void ble (Register rs1, Register rs2, Label *L)
void bgtu (Register rs1, Register rs2, int16_t imm13)
void bgtu (Register rs1, Register rs2, Label *L)
void bleu (Register rs1, Register rs2, int16_t imm13)
void bleu (Register rs1, Register rs2, Label *L)
void j (int32_t imm21)
void j (Label *L)
void b (Label *L)
void jal (int32_t imm21)
void jal (Label *L)
void jr (Register rs)
void jr (Register rs, int32_t imm12)
void jalr (Register rs, int32_t imm12)
void jalr (Register rs)
void ret ()
void call (int32_t offset)
void mv (Register rd, Register rs)
void not_ (Register rd, Register rs)
void neg (Register rd, Register rs)
void seqz (Register rd, Register rs)
void snez (Register rd, Register rs)
void sltz (Register rd, Register rs)
void sgtz (Register rd, Register rs)
Static Public Member Functions
static int JumpOffset (Instr instr)
static int AuipcOffset (Instr instr)
static int JalrOffset (Instr instr)
static int LoadOffset (Instr instr)
static bool IsBranch (Instr instr)
static bool IsNop (Instr instr)
static bool IsJump (Instr instr)
static bool IsJal (Instr instr)
static bool IsJalr (Instr instr)
static bool IsLui (Instr instr)
static bool IsAuipc (Instr instr)
static bool IsAddi (Instr instr)
static bool IsOri (Instr instr)
static bool IsSlli (Instr instr)
static bool IsLw (Instr instr)
Additional Inherited Members
Detailed Description
Definition at line 15 of file base-riscv-i.h.
Member Function Documentation
add()
void v8::internal::AssemblerRISCVI::add (Register rd, Register rs1, Register rs2)
Definition at line 139 of file base-riscv-i.cc.
                                                                 {
  GenInstrALU_rr(0b0000000, 0b000, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_rr().
addi()
void v8::internal::AssemblerRISCVI::addi (Register rd, Register rs1, int16_t imm12)
Definition at line 101 of file base-riscv-i.cc.
                                                                   {
  GenInstrALU_ri(0b000, rd, rs1, imm12);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_ri().
Referenced by mv().
and_()
void v8::internal::AssemblerRISCVI::and_ (Register rd, Register rs1, Register rs2)
Definition at line 175 of file base-riscv-i.cc.
                                                                  {
  GenInstrALU_rr(0b0000000, 0b111, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_rr().
andi()
void v8::internal::AssemblerRISCVI::andi (Register rd, Register rs1, int16_t imm12)
Definition at line 121 of file base-riscv-i.cc.
                                                                   {
  GenInstrALU_ri(0b111, rd, rs1, imm12);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_ri().
auipc()
void v8::internal::AssemblerRISCVI::auipc (Register rd, int32_t imm20)
Definition at line 13 of file base-riscv-i.cc.
                                                      {
  GenInstrU(AUIPC, rd, imm20);
}
References v8::internal::AUIPC, and v8::internal::AssemblerRiscvBase::GenInstrU().
Referenced by call().
AuipcOffset()
int v8::internal::AssemblerRISCVI::AuipcOffset (Instr instr) [static]
Definition at line 257 of file base-riscv-i.cc.
                                            {
  DCHECK(IsAuipc(instr));
  int32_t imm20 = static_cast<int32_t>(instr & kImm20Mask);
  return imm20;
}
References v8::internal::DCHECK(), IsAuipc(), and v8::internal::kImm20Mask.
Referenced by v8::internal::Assembler::BrachlongOffset(), and v8::internal::Assembler::target_address_at().
b()
void v8::internal::AssemblerRISCVI::b (Label * L) [inline]
Definition at line 168 of file base-riscv-i.h.
{ j(L); }
References j(), and v8::internal::L.
beq() [1/2]
void v8::internal::AssemblerRISCVI::beq (Register rs1, Register rs2, int16_t imm12)
Definition at line 33 of file base-riscv-i.cc.
                                                                   {
  GenInstrBranchCC_rri(0b000, rs1, rs2, imm13);
  ClearVectorunit();
}
References v8::internal::AssemblerRiscvBase::ClearVectorunit(), and v8::internal::AssemblerRiscvBase::GenInstrBranchCC_rri().
Referenced by beq(), and beqz().
beq() [2/2]
void v8::internal::AssemblerRISCVI::beq (Register rs1, Register rs2, Label * L) [inline]
Definition at line 113 of file base-riscv-i.h.
                                                 {
    beq(rs1, rs2, branch_offset(L));
  }
References beq(), branch_offset(), and v8::internal::L.
beqz() [1/2]
void v8::internal::AssemblerRISCVI::beqz (Register rs, int16_t imm13) [inline]
Definition at line 132 of file base-riscv-i.h.
{ beq(rs, zero_reg, imm13); }
References beq().
beqz() [2/2]
void v8::internal::AssemblerRISCVI::beqz (Register rs1, Label * L) [inline]
Definition at line 133 of file base-riscv-i.h.
{ beqz(rs1, branch_offset(L)); }
References beqz(), branch_offset(), and v8::internal::L.
Referenced by beqz().
bge() [1/2]
void v8::internal::AssemblerRISCVI::bge (Register rs1, Register rs2, int16_t imm12)
Definition at line 48 of file base-riscv-i.cc.
                                                                   {
  GenInstrBranchCC_rri(0b101, rs1, rs2, imm13);
  ClearVectorunit();
}
References v8::internal::AssemblerRiscvBase::ClearVectorunit(), and v8::internal::AssemblerRiscvBase::GenInstrBranchCC_rri().
Referenced by bge(), bgez(), ble(), and blez().
bge() [2/2]
void v8::internal::AssemblerRISCVI::bge (Register rs1, Register rs2, Label * L) [inline]
Definition at line 122 of file base-riscv-i.h.
                                                 {
    bge(rs1, rs2, branch_offset(L));
  }
References bge(), branch_offset(), and v8::internal::L.
bgeu() [1/2]
void v8::internal::AssemblerRISCVI::bgeu (Register rs1, Register rs2, int16_t imm12)
Definition at line 58 of file base-riscv-i.cc.
                                                                    {
  GenInstrBranchCC_rri(0b111, rs1, rs2, imm13);
  ClearVectorunit();
}
References v8::internal::AssemblerRiscvBase::ClearVectorunit(), and v8::internal::AssemblerRiscvBase::GenInstrBranchCC_rri().
Referenced by bgeu(), and bleu().
bgeu() [2/2]
void v8::internal::AssemblerRISCVI::bgeu (Register rs1, Register rs2, Label * L) [inline]
Definition at line 128 of file base-riscv-i.h.
                                                  {
    bgeu(rs1, rs2, branch_offset(L));
  }
References bgeu(), branch_offset(), and v8::internal::L.
bgez() [1/2]
void v8::internal::AssemblerRISCVI::bgez (Register rs, int16_t imm13) [inline]
Definition at line 138 of file base-riscv-i.h.
{ bge(rs, zero_reg, imm13); }
References bge().
bgez() [2/2]
void v8::internal::AssemblerRISCVI::bgez (Register rs1, Label * L) [inline]
Definition at line 139 of file base-riscv-i.h.
{ bgez(rs1, branch_offset(L)); }
References bgez(), branch_offset(), and v8::internal::L.
Referenced by bgez().
bgt() [1/2]
void v8::internal::AssemblerRISCVI::bgt (Register rs1, Register rs2, int16_t imm13) [inline]
Definition at line 145 of file base-riscv-i.h.
{ blt(rs2, rs1, imm13); }
References blt().
Referenced by bgt().
bgt() [2/2]
void v8::internal::AssemblerRISCVI::bgt (Register rs1, Register rs2, Label * L) [inline]
Definition at line 146 of file base-riscv-i.h.
                                                 {
    bgt(rs1, rs2, branch_offset(L));
  }
References bgt(), branch_offset(), and v8::internal::L.
bgtu() [1/2]
void v8::internal::AssemblerRISCVI::bgtu (Register rs1, Register rs2, int16_t imm13) [inline]
Definition at line 153 of file base-riscv-i.h.
                                                       {
    bltu(rs2, rs1, imm13);
  }
References bltu().
Referenced by bgtu(), and v8::internal::MacroAssembler::BranchShortHelper().
bgtu() [2/2]
void v8::internal::AssemblerRISCVI::bgtu (Register rs1, Register rs2, Label * L) [inline]
Definition at line 156 of file base-riscv-i.h.
                                                  {
    bgtu(rs1, rs2, branch_offset(L));
  }
References bgtu(), branch_offset(), and v8::internal::L.
bgtz() [1/2]
void v8::internal::AssemblerRISCVI::bgtz (Register rs, int16_t imm13) [inline]
Definition at line 142 of file base-riscv-i.h.
{ blt(zero_reg, rs, imm13); }
References blt().
bgtz() [2/2]
void v8::internal::AssemblerRISCVI::bgtz (Register rs1, Label * L) [inline]
Definition at line 144 of file base-riscv-i.h.
{ bgtz(rs1, branch_offset(L)); }
References bgtz(), branch_offset(), and v8::internal::L.
Referenced by bgtz().
ble() [1/2]
void v8::internal::AssemblerRISCVI::ble (Register rs1, Register rs2, int16_t imm13) [inline]
Definition at line 149 of file base-riscv-i.h.
{ bge(rs2, rs1, imm13); }
References bge().
Referenced by ble().
ble() [2/2]
void v8::internal::AssemblerRISCVI::ble (Register rs1, Register rs2, Label * L) [inline]
Definition at line 150 of file base-riscv-i.h.
                                                 {
    ble(rs1, rs2, branch_offset(L));
  }
References ble(), branch_offset(), and v8::internal::L.
bleu() [1/2]
void v8::internal::AssemblerRISCVI::bleu (Register rs1, Register rs2, int16_t imm13) [inline]
Definition at line 159 of file base-riscv-i.h.
                                                       {
    bgeu(rs2, rs1, imm13);
  }
References bgeu().
Referenced by bleu(), and v8::internal::MacroAssembler::BranchShortHelper().
bleu() [2/2]
void v8::internal::AssemblerRISCVI::bleu (Register rs1, Register rs2, Label * L) [inline]
Definition at line 162 of file base-riscv-i.h.
                                                  {
    bleu(rs1, rs2, branch_offset(L));
  }
References bleu(), branch_offset(), and v8::internal::L.
blez() [1/2]
void v8::internal::AssemblerRISCVI::blez (Register rs, int16_t imm13) [inline]
Definition at line 136 of file base-riscv-i.h.
{ bge(zero_reg, rs, imm13); }
References bge().
blez() [2/2]
void v8::internal::AssemblerRISCVI::blez (Register rs1, Label * L) [inline]
Definition at line 137 of file base-riscv-i.h.
{ blez(rs1, branch_offset(L)); }
References blez(), branch_offset(), and v8::internal::L.
Referenced by blez().
blt() [1/2]
void v8::internal::AssemblerRISCVI::blt (Register rs1, Register rs2, int16_t imm12)
Definition at line 43 of file base-riscv-i.cc.
                                                                   {
  GenInstrBranchCC_rri(0b100, rs1, rs2, imm13);
  ClearVectorunit();
}
References v8::internal::AssemblerRiscvBase::ClearVectorunit(), and v8::internal::AssemblerRiscvBase::GenInstrBranchCC_rri().
Referenced by bgt(), bgtz(), blt(), and bltz().
blt() [2/2]
void v8::internal::AssemblerRISCVI::blt (Register rs1, Register rs2, Label * L) [inline]
Definition at line 119 of file base-riscv-i.h.
                                                 {
    blt(rs1, rs2, branch_offset(L));
  }
References blt(), branch_offset(), and v8::internal::L.
bltu() [1/2]
void v8::internal::AssemblerRISCVI::bltu (Register rs1, Register rs2, int16_t imm12)
Definition at line 53 of file base-riscv-i.cc.
                                                                    {
  GenInstrBranchCC_rri(0b110, rs1, rs2, imm13);
  ClearVectorunit();
}
References v8::internal::AssemblerRiscvBase::ClearVectorunit(), and v8::internal::AssemblerRiscvBase::GenInstrBranchCC_rri().
Referenced by bgtu(), and bltu().
bltu() [2/2]
void v8::internal::AssemblerRISCVI::bltu (Register rs1, Register rs2, Label * L) [inline]
Definition at line 125 of file base-riscv-i.h.
                                                  {
    bltu(rs1, rs2, branch_offset(L));
  }
References bltu(), branch_offset(), and v8::internal::L.
bltz() [1/2]
void v8::internal::AssemblerRISCVI::bltz (Register rs, int16_t imm13) [inline]
Definition at line 140 of file base-riscv-i.h.
{ blt(rs, zero_reg, imm13); }
References blt().
bltz() [2/2]
void v8::internal::AssemblerRISCVI::bltz (Register rs1, Label * L) [inline]
Definition at line 141 of file base-riscv-i.h.
{ bltz(rs1, branch_offset(L)); }
References bltz(), branch_offset(), and v8::internal::L.
Referenced by bltz().
bne() [1/2]
void v8::internal::AssemblerRISCVI::bne (Register rs1, Register rs2, int16_t imm12)
Definition at line 38 of file base-riscv-i.cc.
                                                                   {
  GenInstrBranchCC_rri(0b001, rs1, rs2, imm13);
  ClearVectorunit();
}
References v8::internal::AssemblerRiscvBase::ClearVectorunit(), and v8::internal::AssemblerRiscvBase::GenInstrBranchCC_rri().
Referenced by bne(), and bnez().
bne() [2/2]
void v8::internal::AssemblerRISCVI::bne (Register rs1, Register rs2, Label * L) [inline]
Definition at line 116 of file base-riscv-i.h.
                                                 {
    bne(rs1, rs2, branch_offset(L));
  }
References bne(), branch_offset(), and v8::internal::L.
bnez() [1/2]
void v8::internal::AssemblerRISCVI::bnez (Register rs, int16_t imm13) [inline]
Definition at line 134 of file base-riscv-i.h.
{ bne(rs, zero_reg, imm13); }
References bne().
bnez() [2/2]
void v8::internal::AssemblerRISCVI::bnez (Register rs1, Label * L) [inline]
Definition at line 135 of file base-riscv-i.h.
{ bnez(rs1, branch_offset(L)); }
References bnez(), branch_offset(), and v8::internal::L.
Referenced by bnez().
branch_offset()
int32_t v8::internal::AssemblerRISCVI::branch_offset (Label * L) [inline]
Definition at line 105 of file base-riscv-i.h.
                                         {
    return branch_offset_helper(L, OffsetSize::kOffset13);
  }
References v8::internal::AssemblerRiscvBase::branch_offset_helper(), and v8::internal::L.
Referenced by beq(), beqz(), bge(), bgeu(), bgez(), bgt(), bgtu(), bgtz(), ble(), bleu(), blez(), blt(), bltu(), bltz(), bne(), and bnez().
call()
void v8::internal::AssemblerRISCVI::call (int32_t offset) [inline]
Definition at line 176 of file base-riscv-i.h.
                            {
    auipc(ra, (offset >> 12) + ((offset & 0x800) >> 11));
    jalr(ra, ra, offset << 20 >> 20);
  }
References auipc(), and jalr().
ebreak()
void v8::internal::AssemblerRISCVI::ebreak ()
Definition at line 198 of file base-riscv-i.cc.
                             {
  GenInstrI(0b000, SYSTEM, ToRegister(0), ToRegister(0), 1);
}
References v8::internal::AssemblerRiscvBase::GenInstrI(), v8::internal::SYSTEM, and v8::internal::ToRegister().
Referenced by v8::internal::MacroAssembler::Abort(), v8::internal::MacroAssembler::AssertStackIsAligned(), v8::internal::Assembler::break_(), v8::internal::MacroAssembler::CallCFunctionHelper(), and v8::internal::Assembler::EBREAK().
ecall()
void v8::internal::AssemblerRISCVI::ecall ()
Definition at line 194 of file base-riscv-i.cc.
                            {
  GenInstrI(0b000, SYSTEM, ToRegister(0), ToRegister(0), 0);
}
References v8::internal::AssemblerRiscvBase::GenInstrI(), v8::internal::SYSTEM, and v8::internal::ToRegister().
fence()
void v8::internal::AssemblerRISCVI::fence (uint8_t pred, uint8_t succ)
Definition at line 181 of file base-riscv-i.cc.
                                                      {
  DCHECK(is_uint4(pred) && is_uint4(succ));
  uint16_t imm12 = succ | (pred << 4) | (0b0000 << 8);
  GenInstrI(0b000, MISC_MEM, ToRegister(0), ToRegister(0), imm12);
}
References v8::internal::DCHECK(), v8::internal::AssemblerRiscvBase::GenInstrI(), v8::internal::MISC_MEM, and v8::internal::ToRegister().
Referenced by sync().
fence_tso()
void v8::internal::AssemblerRISCVI::fence_tso ()
Definition at line 187 of file base-riscv-i.cc.
                                {
  uint16_t imm12 = (0b0011) | (0b0011 << 4) | (0b1000 << 8);
  GenInstrI(0b000, MISC_MEM, ToRegister(0), ToRegister(0), imm12);
}
References v8::internal::AssemblerRiscvBase::GenInstrI(), v8::internal::MISC_MEM, and v8::internal::ToRegister().
IsAddi()
bool v8::internal::AssemblerRISCVI::IsAddi (Instr instr) [static]
Definition at line 234 of file base-riscv-i.cc.
                                        {
  return (instr & (kBaseOpcodeMask | kFunct3Mask)) == RO_ADDI;
}
References v8::internal::kBaseOpcodeMask, v8::internal::kFunct3Mask, and v8::internal::RO_ADDI.
Referenced by v8::internal::Assembler::embedded_object_handle_at(), v8::internal::Assembler::set_target_constant32_at(), v8::internal::SetLo12Offset(), v8::internal::Assembler::target_at(), v8::internal::Assembler::target_at_put(), and v8::internal::Assembler::target_constant32_at().
IsAuipc()
bool v8::internal::AssemblerRISCVI::IsAuipc (Instr instr) [static]
Definition at line 231 of file base-riscv-i.cc.
                                         {
  return (instr & kBaseOpcodeMask) == AUIPC;
}
References v8::internal::AUIPC, and v8::internal::kBaseOpcodeMask.
Referenced by AuipcOffset(), v8::internal::Assembler::BrachlongOffset(), v8::internal::Assembler::embedded_object_handle_at(), v8::internal::Assembler::PatchBranchlongOffset(), v8::internal::Decoder< V >::PrintTarget(), v8::internal::Assembler::RelocateRelativeReference(), v8::internal::SetHi20Offset(), v8::internal::Assembler::target_address_at(), and v8::internal::RelocInfo::wasm_call_tag().
IsBranch()
bool v8::internal::AssemblerRISCVI::IsBranch (Instr instr) [static]
Definition at line 209 of file base-riscv-i.cc.
                                          {
  return (instr & kBaseOpcodeMask) == BRANCH;
}
References v8::internal::BRANCH, and v8::internal::kBaseOpcodeMask.
IsJal()
bool v8::internal::AssemblerRISCVI::IsJal (Instr instr) [static]
Definition at line 220 of file base-riscv-i.cc.
                                       {
  return (instr & kBaseOpcodeMask) == JAL;
}
References v8::internal::JAL, and v8::internal::kBaseOpcodeMask.
IsJalr()
bool v8::internal::AssemblerRISCVI::IsJalr (Instr instr) [static]
Definition at line 224 of file base-riscv-i.cc.
                                        {
  return (instr & kBaseOpcodeMask) == JALR;
}
References v8::internal::JALR, and v8::internal::kBaseOpcodeMask.
Referenced by JalrOffset().
IsJump()
bool v8::internal::AssemblerRISCVI::IsJump (Instr instr) [static]
Definition at line 213 of file base-riscv-i.cc.
                                        {
  int Op = instr & kBaseOpcodeMask;
  return Op == JAL || Op == JALR;
}
References v8::internal::JAL, v8::internal::JALR, and v8::internal::kBaseOpcodeMask.
IsLui()
bool v8::internal::AssemblerRISCVI::IsLui (Instr instr) [static]
Definition at line 228 of file base-riscv-i.cc.
                                       {
  return (instr & kBaseOpcodeMask) == LUI;
}
References v8::internal::kBaseOpcodeMask, and v8::internal::LUI.
IsLw()
bool v8::internal::AssemblerRISCVI::IsLw (Instr instr) [static]
Definition at line 263 of file base-riscv-i.cc.
                                      {
  return (instr & (kBaseOpcodeMask | kFunct3Mask)) == RO_LW;
}
References v8::internal::kBaseOpcodeMask, v8::internal::kFunct3Mask, and v8::internal::RO_LW.
Referenced by LoadOffset().
IsNop()
bool v8::internal::AssemblerRISCVI::IsNop (Instr instr) [static]
Definition at line 218 of file base-riscv-i.cc.
{ return instr == kNopByte; }
References v8::internal::kNopByte.
IsOri()
bool v8::internal::AssemblerRISCVI::IsOri (Instr instr) [static]
Definition at line 237 of file base-riscv-i.cc.
                                       {
  return (instr & (kBaseOpcodeMask | kFunct3Mask)) == RO_ORI;
}
References v8::internal::kBaseOpcodeMask, v8::internal::kFunct3Mask, and v8::internal::RO_ORI.
IsSlli()
bool v8::internal::AssemblerRISCVI::IsSlli (Instr instr) [static]
Definition at line 240 of file base-riscv-i.cc.
                                        {
  return (instr & (kBaseOpcodeMask | kFunct3Mask)) == RO_SLLI;
}
References v8::internal::kBaseOpcodeMask, v8::internal::kFunct3Mask, and v8::internal::RO_SLLI.
j() [1/2]
void v8::internal::AssemblerRISCVI::j (int32_t imm21) [inline]
Definition at line 166 of file base-riscv-i.h.
{ jal(zero_reg, imm21); }
References jal().
Referenced by b().
j() [2/2]
void v8::internal::AssemblerRISCVI::j (Label * L) [inline]
Definition at line 167 of file base-riscv-i.h.
{ j(jump_offset(L)); }
References j(), jump_offset(), and v8::internal::L.
Referenced by j().
jal() [1/3]
void v8::internal::AssemblerRISCVI::jal (int32_t imm21) [inline]
Definition at line 169 of file base-riscv-i.h.
{ jal(ra, imm21); }
References jal().
Referenced by jal().
jal() [2/3]
void v8::internal::AssemblerRISCVI::jal (Label * L) [inline]
Definition at line 170 of file base-riscv-i.h.
{ jal(jump_offset(L)); }
References jal(), jump_offset(), and v8::internal::L.
Referenced by jal().
jal() [3/3]
void v8::internal::AssemblerRISCVI::jal (Register rd, int32_t imm20)
Definition at line 19 of file base-riscv-i.cc.
                                                    {
  GenInstrJ(JAL, rd, imm21);
  ClearVectorunit();
  BlockTrampolinePoolFor(1);
}
References v8::internal::AssemblerRiscvBase::BlockTrampolinePoolFor(), v8::internal::AssemblerRiscvBase::ClearVectorunit(), v8::internal::AssemblerRiscvBase::GenInstrJ(), and v8::internal::JAL.
Referenced by j().
jalr() [1/3]
void v8::internal::AssemblerRISCVI::jalr (Register rd, Register rs1, int16_t imm12)
Definition at line 25 of file base-riscv-i.cc.
                                                                   {
  GenInstrI(0b000, JALR, rd, rs1, imm12);
  ClearVectorunit();
  BlockTrampolinePoolFor(1);
}
References v8::internal::AssemblerRiscvBase::BlockTrampolinePoolFor(), v8::internal::AssemblerRiscvBase::ClearVectorunit(), v8::internal::AssemblerRiscvBase::GenInstrI(), and v8::internal::JALR.
Referenced by call(), jr(), and ret().
jalr() [2/3]
void v8::internal::AssemblerRISCVI::jalr (Register rs) [inline]
Definition at line 174 of file base-riscv-i.h.
{ jalr(ra, rs, 0); }
References jalr().
Referenced by jalr().
jalr() [3/3]
void v8::internal::AssemblerRISCVI::jalr (Register rs, int32_t imm12) [inline]
Definition at line 173 of file base-riscv-i.h.
{ jalr(ra, rs, imm12); }
References jalr().
Referenced by jalr().
JalrOffset()
int v8::internal::AssemblerRISCVI::JalrOffset (Instr instr) [static]
Definition at line 251 of file base-riscv-i.cc.
                                           {
  DCHECK(IsJalr(instr));
  int32_t imm12 = static_cast<int32_t>(instr & kImm12Mask) >> 20;
  return imm12;
}
References v8::internal::DCHECK(), IsJalr(), and v8::internal::kImm12Mask.
Referenced by v8::internal::Assembler::target_address_at().
jr() [1/2]
void v8::internal::AssemblerRISCVI::jr (Register rs) [inline]
Definition at line 171 of file base-riscv-i.h.
{ jalr(zero_reg, rs, 0); }
References jalr().
jr() [2/2]
void v8::internal::AssemblerRISCVI::jr (Register rs, int32_t imm12) [inline]
Definition at line 172 of file base-riscv-i.h.
{ jalr(zero_reg, rs, imm12); }
References jalr().
jump_offset()
int32_t v8::internal::AssemblerRISCVI::jump_offset (Label * L) [inline]
Definition at line 108 of file base-riscv-i.h.
                                       {
    return branch_offset_helper(L, OffsetSize::kOffset21);
  }
References v8::internal::AssemblerRiscvBase::branch_offset_helper(), and v8::internal::L.
Referenced by j(), and jal().
JumpOffset()
int v8::internal::AssemblerRISCVI::JumpOffset (Instr instr) [static]
Definition at line 244 of file base-riscv-i.cc.
                                           {
  int32_t imm21 = ((instr & 0x7fe00000) >> 20) | ((instr & 0x100000) >> 9) |
                  (instr & 0xff000) | ((instr & 0x80000000) >> 11);
  imm21 = imm21 << 11 >> 11;
  return imm21;
}
Referenced by v8::internal::Assembler::target_at(), and v8::internal::Assembler::target_at_put().
lb()
void v8::internal::AssemblerRISCVI::lb (Register rd, Register rs1, int16_t imm12)
Definition at line 65 of file base-riscv-i.cc.
                                                                 {
  GenInstrLoad_ri(0b000, rd, rs1, imm12);
}
References v8::internal::AssemblerRiscvBase::GenInstrLoad_ri().
lbu()
void v8::internal::AssemblerRISCVI::lbu (Register rd, Register rs1, int16_t imm12)
Definition at line 77 of file base-riscv-i.cc.
                                                                  {
  GenInstrLoad_ri(0b100, rd, rs1, imm12);
}
References v8::internal::AssemblerRiscvBase::GenInstrLoad_ri().
lh()
void v8::internal::AssemblerRISCVI::lh (Register rd, Register rs1, int16_t imm12)
Definition at line 69 of file base-riscv-i.cc.
                                                                 {
  GenInstrLoad_ri(0b001, rd, rs1, imm12);
}
References v8::internal::AssemblerRiscvBase::GenInstrLoad_ri().
lhu()
void v8::internal::AssemblerRISCVI::lhu (Register rd, Register rs1, int16_t imm12)
Definition at line 81 of file base-riscv-i.cc.
                                                                  {
  GenInstrLoad_ri(0b101, rd, rs1, imm12);
}
References v8::internal::AssemblerRiscvBase::GenInstrLoad_ri().
LoadOffset()
int v8::internal::AssemblerRISCVI::LoadOffset (Instr instr) [static]
Definition at line 267 of file base-riscv-i.cc.
                                           {
#if V8_TARGET_ARCH_RISCV64
  DCHECK(IsLd(instr));
#elif V8_TARGET_ARCH_RISCV32
  DCHECK(IsLw(instr));
#endif
  int32_t imm12 = static_cast<int32_t>(instr & kImm12Mask) >> 20;
  return imm12;
}
References v8::internal::DCHECK(), IsLw(), and v8::internal::kImm12Mask.
Referenced by v8::internal::Assembler::target_address_at().
lui()
void v8::internal::AssemblerRISCVI::lui (Register rd, int32_t imm20)
Definition at line 9 of file base-riscv-i.cc.
                                                    {
  GenInstrU(LUI, rd, imm20);
}
References v8::internal::AssemblerRiscvBase::GenInstrU(), and v8::internal::LUI.
lw()
void v8::internal::AssemblerRISCVI::lw (Register rd, Register rs1, int16_t imm12)
Definition at line 73 of file base-riscv-i.cc.
                                                                 {
  GenInstrLoad_ri(0b010, rd, rs1, imm12);
}
References v8::internal::AssemblerRiscvBase::GenInstrLoad_ri().
mv()
void v8::internal::AssemblerRISCVI::mv (Register rd, Register rs) [inline]
Definition at line 181 of file base-riscv-i.h.
{ addi(rd, rs, 0); }
References addi().
Referenced by v8::internal::wasm::liftoff::CalculateActualAddress(), and v8::internal::wasm::liftoff::EnsureNoAlias().
neg()
void v8::internal::AssemblerRISCVI::neg (Register rd, Register rs) [inline]
Definition at line 183 of file base-riscv-i.h.
{ sub(rd, zero_reg, rs); }
References sub().
nor()
void v8::internal::AssemblerRISCVI::nor (Register rd, Register rs, Register rt) [inline]
Definition at line 67 of file base-riscv-i.h.
                                                  {
    or_(rd, rs, rt);
    not_(rd, rd);
  }
References not_(), and or_().
not_()
void v8::internal::AssemblerRISCVI::not_ (Register rd, Register rs) [inline]
Definition at line 182 of file base-riscv-i.h.
{ xori(rd, rs, -1); }
References xori().
Referenced by nor().
or_()
void v8::internal::AssemblerRISCVI::or_ (Register rd, Register rs1, Register rs2)
Definition at line 171 of file base-riscv-i.cc.
                                                                 {
  GenInstrALU_rr(0b0000000, 0b110, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_rr().
Referenced by nor().
ori()
void v8::internal::AssemblerRISCVI::ori (Register rd, Register rs1, int16_t imm12)
Definition at line 117 of file base-riscv-i.cc.
                                                                  {
  GenInstrALU_ri(0b110, rd, rs1, imm12);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_ri().
ret()
void v8::internal::AssemblerRISCVI::ret () [inline]
Definition at line 175 of file base-riscv-i.h.
{ jalr(zero_reg, ra, 0); }
References jalr().
Referenced by v8::internal::MacroAssembler::Ret(), v8::internal::wasm::LiftoffAssembler::CacheState::take_volatile_register(), and v8::internal::Assembler::target_address_at().
sb()
void v8::internal::AssemblerRISCVI::sb (Register source, Register base, int16_t imm12)
Definition at line 87 of file base-riscv-i.cc.
                                                                      {
  GenInstrStore_rri(0b000, base, source, imm12);
}
References v8::internal::AssemblerRiscvBase::GenInstrStore_rri().
seqz()
void v8::internal::AssemblerRISCVI::seqz (Register rd, Register rs) [inline]
Definition at line 184 of file base-riscv-i.h.
{ sltiu(rd, rs, 1); }
References sltiu().
Referenced by v8::internal::MacroAssembler::LoadZeroIfConditionNotZero(), and v8::internal::MacroAssembler::RoundFloatingPointToInteger().
sgtz()
void v8::internal::AssemblerRISCVI::sgtz (Register rd, Register rs) [inline]
Definition at line 187 of file base-riscv-i.h.
{ slt(rd, zero_reg, rs); }
References slt().
sh()
void v8::internal::AssemblerRISCVI::sh (Register source, Register base, int16_t imm12)
Definition at line 91 of file base-riscv-i.cc.
                                                                      {
  GenInstrStore_rri(0b001, base, source, imm12);
}
References v8::internal::AssemblerRiscvBase::GenInstrStore_rri().
sll()
void v8::internal::AssemblerRISCVI::sll (Register rd, Register rs1, Register rs2)
Definition at line 147 of file base-riscv-i.cc.
                                                                 {
  GenInstrALU_rr(0b0000000, 0b001, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_rr().
slli()
void v8::internal::AssemblerRISCVI::slli (Register rd, Register rs1, uint8_t shamt)
Definition at line 125 of file base-riscv-i.cc.
                                                                   {
  GenInstrShift_ri(0, 0b001, rd, rs1, shamt & 0x3f);
}
References v8::internal::AssemblerRiscvBase::GenInstrShift_ri().
Referenced by v8::internal::MacroAssembler::LoadExternalPointerField().
slt()
void v8::internal::AssemblerRISCVI::slt (Register rd, Register rs1, Register rs2)
Definition at line 151 of file base-riscv-i.cc.
                                                                 {
  GenInstrALU_rr(0b0000000, 0b010, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_rr().
Referenced by sgtz(), and sltz().
slti()
void v8::internal::AssemblerRISCVI::slti (Register rd, Register rs1, int16_t imm12)
Definition at line 105 of file base-riscv-i.cc.
                                                                   {
  GenInstrALU_ri(0b010, rd, rs1, imm12);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_ri().
sltiu()
void v8::internal::AssemblerRISCVI::sltiu (Register rd, Register rs1, int16_t imm12)
Definition at line 109 of file base-riscv-i.cc.
                                                                    {
  GenInstrALU_ri(0b011, rd, rs1, imm12);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_ri().
Referenced by seqz().
sltu()
void v8::internal::AssemblerRISCVI::sltu (Register rd, Register rs1, Register rs2)
Definition at line 155 of file base-riscv-i.cc.
                                                                  {
  GenInstrALU_rr(0b0000000, 0b011, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_rr().
Referenced by snez().
sltz()
void v8::internal::AssemblerRISCVI::sltz (Register rd, Register rs) [inline]
Definition at line 186 of file base-riscv-i.h.
{ slt(rd, rs, zero_reg); }
References slt().
snez()
void v8::internal::AssemblerRISCVI::snez (Register rd, Register rs) [inline]
Definition at line 185 of file base-riscv-i.h.
{ sltu(rd, zero_reg, rs); }
References sltu().
Referenced by v8::internal::MacroAssembler::LoadZeroIfConditionZero().
sra()
void v8::internal::AssemblerRISCVI::sra (Register rd, Register rs1, Register rs2)
Definition at line 167 of file base-riscv-i.cc.
                                                                 {
  GenInstrALU_rr(0b0100000, 0b101, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_rr().
srai()
void v8::internal::AssemblerRISCVI::srai (Register rd, Register rs1, uint8_t shamt)
Definition at line 133 of file base-riscv-i.cc.
                                                                   {
  GenInstrShift_ri(1, 0b101, rd, rs1, shamt & 0x3f);
}
References v8::internal::AssemblerRiscvBase::GenInstrShift_ri().
srl()
void v8::internal::AssemblerRISCVI::srl (Register rd, Register rs1, Register rs2)
Definition at line 163 of file base-riscv-i.cc.
                                                                 {
  GenInstrALU_rr(0b0000000, 0b101, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_rr().
srli()
void v8::internal::AssemblerRISCVI::srli (Register rd, Register rs1, uint8_t shamt)
Definition at line 129 of file base-riscv-i.cc.
                                                                   {
  GenInstrShift_ri(0, 0b101, rd, rs1, shamt & 0x3f);
}
References v8::internal::AssemblerRiscvBase::GenInstrShift_ri().
Referenced by v8::internal::MacroAssembler::LoadExternalPointerField().
sub()
void v8::internal::AssemblerRISCVI::sub (Register rd, Register rs1, Register rs2)
Definition at line 143 of file base-riscv-i.cc.
                                                                 {
  GenInstrALU_rr(0b0100000, 0b000, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_rr().
Referenced by neg().
sw()
void v8::internal::AssemblerRISCVI::sw (Register source, Register base, int16_t imm12)
Definition at line 95 of file base-riscv-i.cc.
                                                                      {
  GenInstrStore_rri(0b010, base, source, imm12);
}
References v8::internal::AssemblerRiscvBase::GenInstrStore_rri().
sync()
void v8::internal::AssemblerRISCVI::sync () [inline]
Definition at line 80 of file base-riscv-i.h.
{ fence(0b1111, 0b1111); }
References fence().
unimp()
void v8::internal::AssemblerRISCVI::unimp ()
Definition at line 205 of file base-riscv-i.cc.
                            {
  GenInstrI(0b001, SYSTEM, ToRegister(0), ToRegister(0), 0b110000000000);
}
References v8::internal::AssemblerRiscvBase::GenInstrI(), v8::internal::SYSTEM, and v8::internal::ToRegister().
xor_()
void v8::internal::AssemblerRISCVI::xor_ (Register rd, Register rs1, Register rs2)
Definition at line 159 of file base-riscv-i.cc.
                                                                  {
  GenInstrALU_rr(0b0000000, 0b100, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_rr().
xori()
void v8::internal::AssemblerRISCVI::xori (Register rd, Register rs1, int16_t imm12)
Definition at line 113 of file base-riscv-i.cc.
                                                                   {
  GenInstrALU_ri(0b100, rd, rs1, imm12);
}
References v8::internal::AssemblerRiscvBase::GenInstrALU_ri().
Referenced by not_().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/riscv/base-riscv-i.h
/mnt/V8SourceCode/src/codegen/riscv/base-riscv-i.cc