v8::internal::FixedSizeSignature< T, kNumReturns, kNumParams > Class Template Reference
#include <signature.h>
Public Member Functions
template<typename... ReturnTypes>
auto Returns (ReturnTypes... return_types) const
template<typename... ParamTypes>
auto Params (ParamTypes... param_types) const
Private Member Functions
FixedSizeSignature (const T *returns, const T *params)
Private Attributes
T reps_ [kNumReturns+kNumParams]
Friends
template<typename T2 , size_t kNumReturns2, size_t kNumParams2>
class FixedSizeSignature
Additional Inherited Members
Detailed Description
template<typename T, size_t kNumReturns = 0, size_t kNumParams = 0>
class v8::internal::FixedSizeSignature< T, kNumReturns, kNumParams >
Definition at line 162 of file signature.h.
Constructor & Destructor Documentation
FixedSizeSignature()
template<typename T , size_t kNumReturns = 0, size_t kNumParams = 0>
v8::internal::FixedSizeSignature< T, kNumReturns, kNumParams >::FixedSizeSignature (const T * returns, const T * params) [inline], [private]
Definition at line 185 of file signature.h.
      : Signature<T>(kNumReturns, kNumParams, reps_) {
    std::copy(returns, returns + kNumReturns, reps_);
    std::copy(params, params + kNumParams, reps_ + kNumReturns);
  }
References v8::internal::FixedSizeSignature< T, kNumReturns, kNumParams >::reps_, and v8::internal::Signature< T >::returns().
Member Function Documentation
Params()
template<typename T , size_t kNumReturns = 0, size_t kNumParams = 0>
template<typename... ParamTypes>
auto v8::internal::FixedSizeSignature< T, kNumReturns, kNumParams >::Params (ParamTypes... param_types) const [inline]
Definition at line 174 of file signature.h.
                                               {
    static_assert(kNumParams == 0, "Please specify all parameters at once");
    return FixedSizeSignature<T, kNumReturns, sizeof...(ParamTypes)>{
        reps_, std::initializer_list<T>{param_types...}.begin()};
  }
References v8::internal::FixedSizeSignature< T, kNumReturns, kNumParams >::reps_, and T.
Referenced by v8::internal::wasm::fuzzing::GenerateWasmModuleForRevec().
Returns()
template<typename T , size_t kNumReturns = 0, size_t kNumParams = 0>
template<typename... ReturnTypes>
auto v8::internal::FixedSizeSignature< T, kNumReturns, kNumParams >::Returns (ReturnTypes... return_types) const [inline]
Definition at line 166 of file signature.h.
                                                  {
    static_assert(kNumReturns == 0, "Please specify all return types at once");
    return FixedSizeSignature<T, sizeof...(ReturnTypes), kNumParams>{
        std::initializer_list<T>{return_types...}.begin(), reps_};
  }
References v8::internal::FixedSizeSignature< T, kNumReturns, kNumParams >::reps_, and T.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::AtomicNotify(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCapiCallWrapper(), v8::internal::wasm::ModuleDecoderImpl::consume_init_expr(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::ConsumeElementSegmentEntry(), v8::internal::wasm::EvaluateConstantExpression(), v8::internal::wasm::fuzzing::GenerateRandomWasmModule(), v8::internal::wasm::TurboshaftGraphBuildingInterface::MemoryCopy(), v8::internal::wasm::TurboshaftGraphBuildingInterface::MemoryFill(), v8::internal::wasm::TurboshaftGraphBuildingInterface::MemoryInit(), v8::internal::wasm::ModuleDisassembler::PrintInitExpression(), v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::Return(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::UnOpImpl().
Friends And Related Function Documentation
FixedSizeSignature
template<typename T , size_t kNumReturns = 0, size_t kNumParams = 0>
template<typename T2 , size_t kNumReturns2, size_t kNumParams2>
friend class FixedSizeSignature [friend]
Definition at line 183 of file signature.h.
Member Data Documentation
reps_
template<typename T , size_t kNumReturns = 0, size_t kNumParams = 0>
T v8::internal::FixedSizeSignature< T, kNumReturns, kNumParams >::reps_[kNumReturns+kNumParams] [private]
Definition at line 191 of file signature.h.
Referenced by v8::internal::FixedSizeSignature< T, kNumReturns, kNumParams >::FixedSizeSignature(), v8::internal::FixedSizeSignature< T, kNumReturns, kNumParams >::Params(), and v8::internal::FixedSizeSignature< T, kNumReturns, kNumParams >::Returns().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/codegen/signature.h