v8::internal::MemoryReducer Class Reference
#include <memory-reducer.h>
Classes
struct Event
class State
class TimerTask
Public Types
enum Id { kUninit
, kDone
, kWait
, kRun
 }
enum EventType { kTimer
, kMarkCompact
, kPossibleGarbage
 }
Public Member Functions
MemoryReducer (Heap *heap)
MemoryReducer (const MemoryReducer &)=delete
MemoryReducer & operator= (const MemoryReducer &)=delete
void NotifyMarkCompact (size_t committed_memory_before)
void NotifyPossibleGarbage ()
void ScheduleTimer (double delay_ms)
void TearDown ()
Heap * heap ()
bool ShouldGrowHeapSlowly ()
Static Public Member Functions
static State Step (const State &state, const Event &event)
static int MaxNumberOfGCs ()
static bool IsFrozen (const Heap *heap)
Static Public Attributes
static const int kLongDelayMs = 8000
static const int kShortDelayMs = 500
static const int kWatchdogDelayMs = 100000
static const double kCommittedMemoryFactor = 1.1
static const size_t kCommittedMemoryDelta = 10 * MB
Private Member Functions
void NotifyTimer (const Event &event)
Static Private Member Functions
static bool WatchdogGC (const State &state, const Event &event)
Private Attributes
Heap * heap_
std::shared_ptr< v8::TaskRunner > taskrunner_
State state_
unsigned int js_calls_counter_
double js_calls_sample_time_ms_
int start_delay_ms_ = false
Friends
class heap::HeapTester
Detailed Description
Definition at line 87 of file memory-reducer.h.
Member Enumeration Documentation
EventType
enum v8::internal::MemoryReducer::EventType
Enumerator
kTimer
kMarkCompact
kPossibleGarbage
Definition at line 146 of file memory-reducer.h.
{ kTimer, kMarkCompact, kPossibleGarbage };
Id
enum v8::internal::MemoryReducer::Id
Enumerator
kUninit
kDone
kWait
kRun
Definition at line 89 of file memory-reducer.h.
{ kUninit, kDone, kWait, kRun };
Constructor & Destructor Documentation
MemoryReducer() [1/2]
v8::internal::MemoryReducer::MemoryReducer (Heap * heap) [explicit]
Definition at line 23 of file memory-reducer.cc.
    : heap_(heap),
      taskrunner_(heap->GetForegroundTaskRunner()),
      state_(State::CreateUninitialized()),
      js_calls_counter_(0),
      js_calls_sample_time_ms_(0.0) {
  DCHECK(v8_flags.incremental_marking);
  DCHECK(v8_flags.memory_reducer);
}
References v8::internal::DCHECK(), and v8::internal::v8_flags.
MemoryReducer() [2/2]
v8::internal::MemoryReducer::MemoryReducer (const MemoryReducer &) [delete]
Member Function Documentation
heap()
Heap* v8::internal::MemoryReducer::heap () [inline]
Definition at line 180 of file memory-reducer.h.
{ return heap_; }
Referenced by NotifyMarkCompact(), NotifyPossibleGarbage(), NotifyTimer(), and ScheduleTimer().
IsFrozen()
bool v8::internal::MemoryReducer::IsFrozen (const Heap * heap) [static]
Definition at line 246 of file memory-reducer.cc.
                                             {
  return v8_flags.memory_reducer_respects_frozen_state &&
         heap->isolate()->IsFrozen();
}
References v8::internal::v8_flags.
Referenced by NotifyMarkCompact(), NotifyPossibleGarbage(), and v8::internal::MemoryReducer::TimerTask::RunInternal().
MaxNumberOfGCs()
int v8::internal::MemoryReducer::MaxNumberOfGCs () [static]
Definition at line 240 of file memory-reducer.cc.
                                  {
  DCHECK_GT(v8_flags.memory_reducer_gc_count, 0);
  return v8_flags.memory_reducer_gc_count;
}
References DCHECK_GT, and v8::internal::v8_flags.
Referenced by Step().
NotifyMarkCompact()
void v8::internal::MemoryReducer::NotifyMarkCompact (size_t committed_memory_before)
Definition at line 103 of file memory-reducer.cc.
                                                                    {
  if (!v8_flags.incremental_marking) return;
  const size_t committed_memory = heap()->CommittedOldGenerationMemory();
  // Trigger one more GC if
  // - this GC decreased committed memory,
  // - there is high fragmentation,
  const MemoryReducer::Event event{
      MemoryReducer::kMarkCompact,
      heap()->MonotonicallyIncreasingTimeInMs(),
      committed_memory,
      (committed_memory_before > committed_memory + MB) ||
          heap()->HasHighFragmentation(),
      false,
      false,
      IsFrozen(heap())};
  const State old_state = state_;
  state_ = Step(state_, event);
  if (old_state.id() != kWait && state_.id() == kWait) {
    // If we are transitioning to the WAIT state, start the timer.
    ScheduleTimer(state_.next_gc_start_ms() - event.time_ms);
  }
  if (old_state.id() == kRun && v8_flags.trace_memory_reducer) {
    heap()->isolate()->PrintWithTimestamp(
        "Memory reducer: finished GC #%d (%s)\n", old_state.started_gcs(),
        state_.id() == kWait ? "will do more" : "done");
  }
}
References v8::internal::Heap::CommittedOldGenerationMemory(), v8::internal::Heap::HasHighFragmentation(), heap(), v8::internal::MemoryReducer::State::id(), IsFrozen(), v8::internal::Heap::isolate(), kMarkCompact, kRun, kWait, v8::internal::MB, v8::internal::Heap::MonotonicallyIncreasingTimeInMs(), v8::internal::MemoryReducer::State::next_gc_start_ms(), ScheduleTimer(), v8::internal::MemoryReducer::State::started_gcs(), state_, Step(), and v8::internal::v8_flags.
NotifyPossibleGarbage()
void v8::internal::MemoryReducer::NotifyPossibleGarbage ()
Definition at line 132 of file memory-reducer.cc.
                                          {
  if (!v8_flags.incremental_marking) return;
  const MemoryReducer::Event event{MemoryReducer::kPossibleGarbage,
                                   heap()->MonotonicallyIncreasingTimeInMs(),
                                   0,
                                   false,
                                   false,
                                   false,
                                   IsFrozen(heap_)};
  const Id old_action = state_.id();
  state_ = Step(state_, event);
  if (old_action != kWait && state_.id() == kWait) {
    // If we are transitioning to the WAIT state, start the timer.
    ScheduleTimer(state_.next_gc_start_ms() - event.time_ms);
  }
}
References heap(), heap_, v8::internal::MemoryReducer::State::id(), IsFrozen(), kPossibleGarbage, kWait, v8::internal::Heap::MonotonicallyIncreasingTimeInMs(), v8::internal::MemoryReducer::State::next_gc_start_ms(), ScheduleTimer(), state_, Step(), and v8::internal::v8_flags.
Referenced by v8::internal::Heap::NotifyOldGenerationExpansion(), and v8::internal::Heap::StartIncrementalMarkingIfAllocationLimitIsReached().
NotifyTimer()
void v8::internal::MemoryReducer::NotifyTimer (const Event & event) [private]
Definition at line 75 of file memory-reducer.cc.
                                                  {
  if (state_.id() != kWait) return;
  DCHECK_EQ(kTimer, event.type);
  state_ = Step(state_, event);
  if (state_.id() == kRun) {
    DCHECK(heap()->incremental_marking()->IsStopped());
    DCHECK(v8_flags.incremental_marking);
    if (v8_flags.trace_memory_reducer) {
      heap()->isolate()->PrintWithTimestamp("Memory reducer: started GC #%d\n",
                                            state_.started_gcs());
    }
    GCFlags gc_flags = v8_flags.memory_reducer_favors_memory
                           ? GCFlag::kReduceMemoryFootprint
                           : GCFlag::kNoFlags;
    heap()->StartIncrementalMarking(gc_flags,
                                    GarbageCollectionReason::kMemoryReducer,
                                    kGCCallbackFlagCollectAllExternalMemory);
  } else if (state_.id() == kWait) {
    // Re-schedule the timer.
    ScheduleTimer(state_.next_gc_start_ms() - event.time_ms);
    if (v8_flags.trace_memory_reducer) {
      heap()->isolate()->PrintWithTimestamp(
          "Memory reducer: waiting for %.f ms\n",
          state_.next_gc_start_ms() - event.time_ms);
    }
  }
}
References v8::internal::DCHECK(), DCHECK_EQ, heap(), v8::internal::MemoryReducer::State::id(), v8::internal::Heap::isolate(), v8::kGCCallbackFlagCollectAllExternalMemory, v8::internal::kMemoryReducer, v8::internal::kNoFlags, v8::internal::kReduceMemoryFootprint, kRun, kTimer, kWait, v8::internal::MemoryReducer::State::next_gc_start_ms(), ScheduleTimer(), v8::internal::MemoryReducer::State::started_gcs(), v8::internal::Heap::StartIncrementalMarking(), state_, Step(), v8::internal::MemoryReducer::Event::time_ms, v8::internal::MemoryReducer::Event::type, and v8::internal::v8_flags.
operator=()
MemoryReducer& v8::internal::MemoryReducer::operator= (const MemoryReducer &) [delete]
ScheduleTimer()
void v8::internal::MemoryReducer::ScheduleTimer (double delay_ms)
Definition at line 228 of file memory-reducer.cc.
                                                 {
  DCHECK_LT(0, delay_ms);
  if (heap()->IsTearingDown()) return;
  // Leave some room for precision error in task scheduler.
  const double kSlackMs = 100;
  taskrunner_->PostDelayedTask(std::make_unique<MemoryReducer::TimerTask>(this),
                               (delay_ms + kSlackMs) / 1000.0);
}
References DCHECK_LT, heap(), and taskrunner_.
Referenced by NotifyMarkCompact(), NotifyPossibleGarbage(), and NotifyTimer().
ShouldGrowHeapSlowly()
bool v8::internal::MemoryReducer::ShouldGrowHeapSlowly () [inline]
Definition at line 182 of file memory-reducer.h.
{ return state_.id() == kDone; }
Step()
MemoryReducer::State v8::internal::MemoryReducer::Step (const State & state, const Event & event) [static]
Definition at line 156 of file memory-reducer.cc.
                                                             {
  DCHECK(v8_flags.memory_reducer);
  DCHECK(v8_flags.incremental_marking);
  switch (state.id()) {
    case kUninit:
    case kDone:
      if (event.type == kTimer) {
        return state;
      } else if (event.type == kMarkCompact) {
        if (event.committed_memory <
            std::max(
                static_cast<size_t>(state.committed_memory_at_last_run() *
                                    kCommittedMemoryFactor),
                state.committed_memory_at_last_run() + kCommittedMemoryDelta)) {
          return state;
        } else {
          return State::CreateWait(0, event.time_ms + kLongDelayMs,
                                   event.time_ms);
        }
      } else {
        DCHECK_EQ(kPossibleGarbage, event.type);
        return State::CreateWait(
            0, event.time_ms + v8_flags.gc_memory_reducer_start_delay_ms,
            state.last_gc_time_ms());
      }
    case kWait:
      CHECK_LE(state.started_gcs(), MaxNumberOfGCs());
      switch (event.type) {
        case kPossibleGarbage:
          return state;
        case kTimer:
          if (event.is_frozen || state.started_gcs() >= MaxNumberOfGCs()) {
            return State::CreateDone(state.last_gc_time_ms(),
                                     event.committed_memory);
          } else if (event.can_start_incremental_gc &&
                     (event.should_start_incremental_gc ||
                      WatchdogGC(state, event))) {
            if (state.next_gc_start_ms() <= event.time_ms) {
              return State::CreateRun(state.started_gcs() + 1);
            } else {
              return state;
            }
          } else {
            return State::CreateWait(state.started_gcs(),
                                     event.time_ms + kLongDelayMs,
                                     state.last_gc_time_ms());
          }
        case kMarkCompact:
          return State::CreateWait(state.started_gcs(),
                                   event.time_ms + kLongDelayMs, event.time_ms);
      }
    case kRun:
      CHECK_LE(state.started_gcs(), MaxNumberOfGCs());
      if (event.type == kMarkCompact) {
        if (!event.is_frozen && state.started_gcs() < MaxNumberOfGCs() &&
            (event.next_gc_likely_to_collect_more ||
             state.started_gcs() == 1)) {
          return State::CreateWait(state.started_gcs(),
                                   event.time_ms + kShortDelayMs,
                                   event.time_ms);
        } else {
          return State::CreateDone(event.time_ms, event.committed_memory);
        }
      } else {
        return state;
      }
  }
  UNREACHABLE();
}
References v8::internal::MemoryReducer::Event::can_start_incremental_gc, CHECK_LE, v8::internal::MemoryReducer::Event::committed_memory, v8::internal::MemoryReducer::State::committed_memory_at_last_run(), v8::internal::MemoryReducer::State::CreateDone(), v8::internal::MemoryReducer::State::CreateRun(), v8::internal::MemoryReducer::State::CreateWait(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::MemoryReducer::State::id(), v8::internal::MemoryReducer::Event::is_frozen, kCommittedMemoryDelta, kCommittedMemoryFactor, kDone, kLongDelayMs, kMarkCompact, kPossibleGarbage, kRun, kShortDelayMs, kTimer, kUninit, kWait, v8::internal::MemoryReducer::State::last_gc_time_ms(), MaxNumberOfGCs(), v8::internal::MemoryReducer::Event::next_gc_likely_to_collect_more, v8::internal::MemoryReducer::State::next_gc_start_ms(), v8::internal::MemoryReducer::Event::should_start_incremental_gc, v8::internal::MemoryReducer::State::started_gcs(), v8::internal::MemoryReducer::Event::time_ms, v8::internal::MemoryReducer::Event::type, v8::internal::UNREACHABLE(), v8::internal::v8_flags, and WatchdogGC().
Referenced by NotifyMarkCompact(), NotifyPossibleGarbage(), and NotifyTimer().
TearDown()
void v8::internal::MemoryReducer::TearDown ()
Definition at line 237 of file memory-reducer.cc.
{ state_ = State::CreateUninitialized(); }
References v8::internal::MemoryReducer::State::CreateUninitialized(), and state_.
WatchdogGC()
bool v8::internal::MemoryReducer::WatchdogGC (const State & state, const Event & event) [static], [private]
Definition at line 149 of file memory-reducer.cc.
                                                                     {
  return state.last_gc_time_ms() != 0 &&
         event.time_ms > state.last_gc_time_ms() + kWatchdogDelayMs;
}
References kWatchdogDelayMs, and v8::internal::MemoryReducer::State::last_gc_time_ms().
Referenced by Step().
Friends And Related Function Documentation
heap::HeapTester
friend class heap::HeapTester [friend]
Definition at line 213 of file memory-reducer.h.
Member Data Documentation
heap_
Heap* v8::internal::MemoryReducer::heap_ [private]
Definition at line 205 of file memory-reducer.h.
Referenced by NotifyPossibleGarbage().
js_calls_counter_
unsigned int v8::internal::MemoryReducer::js_calls_counter_ [private]
Definition at line 208 of file memory-reducer.h.
js_calls_sample_time_ms_
double v8::internal::MemoryReducer::js_calls_sample_time_ms_ [private]
Definition at line 209 of file memory-reducer.h.
kCommittedMemoryDelta
const size_t v8::internal::MemoryReducer::kCommittedMemoryDelta = 10 * MB [static]
Definition at line 178 of file memory-reducer.h.
Referenced by Step().
kCommittedMemoryFactor
const double v8::internal::MemoryReducer::kCommittedMemoryFactor = 1.1 [static]
Definition at line 175 of file memory-reducer.h.
Referenced by Step().
kLongDelayMs
const int v8::internal::MemoryReducer::kLongDelayMs = 8000 [static]
Definition at line 170 of file memory-reducer.h.
Referenced by Step().
kShortDelayMs
const int v8::internal::MemoryReducer::kShortDelayMs = 500 [static]
Definition at line 171 of file memory-reducer.h.
Referenced by Step().
kWatchdogDelayMs
const int v8::internal::MemoryReducer::kWatchdogDelayMs = 100000 [static]
Definition at line 172 of file memory-reducer.h.
Referenced by WatchdogGC().
start_delay_ms_
int v8::internal::MemoryReducer::start_delay_ms_ = false [private]
Definition at line 210 of file memory-reducer.h.
state_
State v8::internal::MemoryReducer::state_ [private]
Definition at line 207 of file memory-reducer.h.
Referenced by NotifyMarkCompact(), NotifyPossibleGarbage(), NotifyTimer(), and TearDown().
taskrunner_
std::shared_ptr<v8::TaskRunner> v8::internal::MemoryReducer::taskrunner_ [private]
Definition at line 206 of file memory-reducer.h.
Referenced by ScheduleTimer().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/memory-reducer.h
/mnt/V8SourceCode/src/heap/memory-reducer.cc