v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::MaybeUnparkForPrint Class Reference
Public Member Functions
MaybeUnparkForPrint ()
Private Attributes
std::optional< UnparkedScope > scope_
Detailed Description
Definition at line 256 of file maglev-ir.cc.
Constructor & Destructor Documentation
MaybeUnparkForPrint()
v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::MaybeUnparkForPrint::MaybeUnparkForPrint () [inline]
Definition at line 258 of file maglev-ir.cc.
                        {
    LocalHeap* local_heap = LocalHeap::Current();
    if (!local_heap) {
      local_heap = Isolate::Current()->main_thread_local_heap();
    }
    DCHECK_NOT_NULL(local_heap);
    if (local_heap->IsParked()) {
      scope_.emplace(local_heap);
    }
  }
References v8::internal::Isolate::Current(), DCHECK_NOT_NULL, v8::internal::LocalHeap::IsParked(), and v8::internal::Isolate::main_thread_local_heap().
Member Data Documentation
scope_
std::optional<UnparkedScope> v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::MaybeUnparkForPrint::scope_ [private]
Definition at line 270 of file maglev-ir.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.cc