heap::base::internal::SegmentBase Class Reference
#include <worklist.h>
Public Member Functions
constexpr SegmentBase (uint16_t capacity)
size_t Size () const
size_t Capacity () const
bool IsEmpty () const
bool IsFull () const
void Clear ()
Static Public Member Functions
static SegmentBase * GetSentinelSegmentAddress ()
Protected Attributes
const uint16_t capacity_
uint16_t index_ = 0
Detailed Description
Definition at line 19 of file worklist.h.
Constructor & Destructor Documentation
SegmentBase()
constexpr heap::base::internal::SegmentBase::SegmentBase (uint16_t capacity) [inline], [explicit], [constexpr]
Definition at line 23 of file worklist.h.
: capacity_(capacity) {}
Member Function Documentation
Capacity()
size_t heap::base::internal::SegmentBase::Capacity () const [inline]
Definition at line 26 of file worklist.h.
{ return capacity_; }
Clear()
void heap::base::internal::SegmentBase::Clear () [inline]
Definition at line 29 of file worklist.h.
{ index_ = 0; }
GetSentinelSegmentAddress()
SegmentBase * heap::base::internal::SegmentBase::GetSentinelSegmentAddress () [static]
Definition at line 18 of file worklist.cc.
                                                    {
  static SegmentBase sentinel_segment(0);
  return &sentinel_segment;
}
Referenced by heap::base::Worklist< EntryType, MinSegmentSize >::Local::DeleteSegment(), heap::base::Worklist< EntryType, MinSegmentSize >::Local::pop_segment(), heap::base::Worklist< EntryType, MinSegmentSize >::Local::Publish(), heap::base::Worklist< EntryType, MinSegmentSize >::Local::PublishPopSegment(), heap::base::Worklist< EntryType, MinSegmentSize >::Local::PublishPushSegment(), and heap::base::Worklist< EntryType, MinSegmentSize >::Local::push_segment().
IsEmpty()
bool heap::base::internal::SegmentBase::IsEmpty () const [inline]
Definition at line 27 of file worklist.h.
{ return index_ == 0; }
Referenced by heap::base::Worklist< EntryType, MinSegmentSize >::Push(), and heap::base::Worklist< EntryType, MinSegmentSize >::Update().
IsFull()
bool heap::base::internal::SegmentBase::IsFull () const [inline]
Definition at line 28 of file worklist.h.
{ return index_ == capacity_; }
Referenced by heap::base::Worklist< EntryType, MinSegmentSize >::Segment::Push().
Size()
size_t heap::base::internal::SegmentBase::Size () const [inline]
Definition at line 25 of file worklist.h.
{ return index_; }
Member Data Documentation
capacity_
const uint16_t heap::base::internal::SegmentBase::capacity_ [protected]
Definition at line 32 of file worklist.h.
index_
uint16_t heap::base::internal::SegmentBase::index_ = 0 [protected]
Definition at line 33 of file worklist.h.
Referenced by heap::base::Worklist< EntryType, MinSegmentSize >::Segment::Push().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/base/worklist.h
/mnt/V8SourceCode/src/heap/base/worklist.cc