v8::internal::StoreTransitionDescriptor Class Reference
#include <interface-descriptors.h>
Public Member Functions
DEFINE_PARAMETER_TYPES (MachineType::AnyTagged(), MachineType::AnyTagged(), MachineType::AnyTagged(), MachineType::AnyTagged(), MachineType::TaggedSigned(), MachineType::AnyTagged()) static const expr inline Register MapRegister()
Static Public Member Functions
static constexpr auto registers ()
Additional Inherited Members
Detailed Description
Definition at line 1212 of file interface-descriptors.h.
Member Function Documentation
DEFINE_PARAMETER_TYPES()
v8::internal::StoreTransitionDescriptor::DEFINE_PARAMETER_TYPES (MachineType::AnyTagged() , MachineType::AnyTagged() , MachineType::AnyTagged() , MachineType::AnyTagged() , MachineType::TaggedSigned() , MachineType::AnyTagged()) const
registers()
constexpr auto v8::internal::StoreTransitionDescriptor::registers () [static], [constexpr]
Definition at line 603 of file interface-descriptors-inl.h.
                                                    {
  return RegisterArray(StoreDescriptor::ReceiverRegister(),
                       StoreDescriptor::NameRegister(), MapRegister(),
                       StoreDescriptor::ValueRegister(),
                       StoreDescriptor::SlotRegister(),
                       StoreWithVectorDescriptor::VectorRegister());
}
References v8::internal::StoreDescriptor::NameRegister(), v8::internal::RegisterArray(), v8::internal::StoreDescriptor::SlotRegister(), and v8::internal::StoreDescriptor::ValueRegister().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/interface-descriptors.h
/mnt/V8SourceCode/src/codegen/interface-descriptors-inl.h