v8::internal::compiler::turboshaft::WordType< Bits > Class Template Reference
#include <types.h>
Public Types
using word_t = uint_type< Bits >
using value_type = word_t
Public Member Functions
bool is_range () const
bool is_set () const
bool is_any () const
bool is_constant () const
bool is_wrapping () const
word_t range_from () const
word_t range_to () const
std::pair< word_t, word_t > range () const
int set_size () const
word_t set_element (int index) const
base::Vector< const word_t > set_elements () const
std::optional< word_t > try_get_constant () const
bool is_constant (word_t value) const
word_t unsigned_min () const
word_t unsigned_max () const
bool Contains (word_t value) const
bool Equals (const WordType &other) const
bool IsSubtypeOf (const WordType &other) const
void PrintTo (std::ostream &stream) const
Handle< TurboshaftType > AllocateOnHeap (Factory *factory) const
Static Public Member Functions
static WordType Any ()
static WordType Range (word_t from, word_t to, Zone *zone)
template<size_t N>
static WordType Set (const base::SmallVector< word_t, N > &elements, Zone *zone)
static WordType Set (const std::vector< word_t > &elements, Zone *zone)
static WordType Set (const std::initializer_list< word_t > &elements, Zone *zone)
static WordType Set (base::Vector< const word_t > elements, Zone *zone)
static WordType Constant (word_t constant)
static WordType LeastUpperBound (const WordType &lhs, const WordType &rhs, Zone *zone)
static Type Intersect (const WordType &lhs, const WordType &rhs, ResolutionMode resolution_mode, Zone *zone)
Static Public Attributes
static constexpr int kMaxSetSize = 8
Private Types
enum class SubKind : uint8_t { kRange
, kSet
 }
using Payload_Range = detail::Payload_Range< word_t >
using Payload_InlineSet = detail::Payload_InlineSet< word_t >
using Payload_OutlineSet = detail::Payload_OutlineSet< word_t >
Private Member Functions
SubKind sub_kind () const
template<typename Payload >
WordType (SubKind sub_kind, uint8_t set_size, const Payload &payload)
Static Private Attributes
static constexpr int kMaxInlineSetSize = 2
static constexpr Kind KIND = Bits == 32 ? Kind::kWord32 : Kind::kWord64
Friends
class Type
Additional Inherited Members
Detailed Description
template<size_t Bits>
class v8::internal::compiler::turboshaft::WordType< Bits >
Definition at line 323 of file types.h.
Member Typedef Documentation
Payload_InlineSet
template<size_t Bits>
using v8::internal::compiler::turboshaft::WordType< Bits >::Payload_InlineSet = detail::Payload_InlineSet<word_t> [private]
Definition at line 496 of file types.h.
Payload_OutlineSet
template<size_t Bits>
using v8::internal::compiler::turboshaft::WordType< Bits >::Payload_OutlineSet = detail::Payload_OutlineSet<word_t> [private]
Definition at line 497 of file types.h.
Payload_Range
template<size_t Bits>
using v8::internal::compiler::turboshaft::WordType< Bits >::Payload_Range = detail::Payload_Range<word_t> [private]
Definition at line 495 of file types.h.
value_type
template<size_t Bits>
using v8::internal::compiler::turboshaft::WordType< Bits >::value_type = word_t
Definition at line 336 of file types.h.
word_t
template<size_t Bits>
using v8::internal::compiler::turboshaft::WordType< Bits >::word_t = uint_type<Bits>
Definition at line 335 of file types.h.
Member Enumeration Documentation
SubKind
template<size_t Bits>
enum v8::internal::compiler::turboshaft::WordType::SubKind : uint8_t [strong], [private]
Enumerator
kRange
kSet
Definition at line 328 of file types.h.
                     : uint8_t {
    kRange,
    kSet,
  };
Constructor & Destructor Documentation
WordType()
template<size_t Bits>
template<typename Payload >
v8::internal::compiler::turboshaft::WordType< Bits >::WordType (SubKind sub_kind, uint8_t set_size, const Payload & payload) [inline], [private]
Definition at line 501 of file types.h.
      : Type(KIND, static_cast<uint8_t>(sub_kind), set_size, 0, 0, payload) {}
Member Function Documentation
AllocateOnHeap()
template<size_t Bits>
Handle< TurboshaftType > v8::internal::compiler::turboshaft::WordType< Bits >::AllocateOnHeap (Factory * factory) const
Definition at line 431 of file types.cc.
                                                                            {
  if constexpr (Bits == 32) {
    if (is_range()) {
      return factory->NewTurboshaftWord32RangeType(range_from(), range_to(),
                                                   AllocationType::kYoung);
    } else {
      DCHECK(is_set());
      auto result = factory->NewTurboshaftWord32SetType(set_size(),
                                                        AllocationType::kYoung);
      for (int i = 0; i < set_size(); ++i) {
        result->set_elements(i, set_element(i));
      }
      return result;
    }
  } else {
    if (is_range()) {
      const auto [from_high, from_low] = uint64_to_high_low(range_from());
      const auto [to_high, to_low] = uint64_to_high_low(range_to());
      return factory->NewTurboshaftWord64RangeType(
          from_high, from_low, to_high, to_low, AllocationType::kYoung);
    } else {
      DCHECK(is_set());
      auto result = factory->NewTurboshaftWord64SetType(set_size(),
                                                        AllocationType::kYoung);
      for (int i = 0; i < set_size(); ++i) {
        const auto [high, low] = uint64_to_high_low(set_element(i));
        result->set_elements_high(i, high);
        result->set_elements_low(i, low);
      }
      return result;
    }
  }
}
References v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kYoung, v8::base::internal::result, and v8::internal::compiler::turboshaft::anonymous_namespace{types.cc}::uint64_to_high_low().
Any()
template<size_t Bits>
static WordType v8::internal::compiler::turboshaft::WordType< Bits >::Any () [inline], [static]
Definition at line 339 of file types.h.
                        {
    return Range(0, std::numeric_limits<word_t>::max(), nullptr);
  }
References v8::internal::compiler::turboshaft::WordType< Bits >::Range().
Referenced by v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::Add(), v8::internal::compiler::turboshaft::Typer::ExtendWord32ToWord64(), v8::internal::compiler::turboshaft::LeastUpperBoundFromRanges(), v8::internal::compiler::turboshaft::TypeParser::ParseType(), v8::internal::compiler::turboshaft::WordType< Bits >::Set(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::Subtract(), v8::internal::compiler::turboshaft::Typer::TruncateWord32Input(), v8::internal::compiler::turboshaft::Typer::TypeForRepresentation(), v8::internal::compiler::turboshaft::Typer::TypeOverflowCheckedBinop(), v8::internal::compiler::turboshaft::Typer::TypeWord64Add(), v8::internal::compiler::turboshaft::Typer::TypeWord64Sub(), v8::internal::compiler::turboshaft::Typer::TypeWordBinop(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::WidenExponential(), and v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::WidenMaximal().
Constant()
template<size_t Bits>
static WordType v8::internal::compiler::turboshaft::WordType< Bits >::Constant (word_t constant) [inline], [static]
Definition at line 409 of file types.h.
{ return Set({constant}, nullptr); }
Referenced by v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::LessThan(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::LessThanOrEqual(), v8::internal::compiler::turboshaft::Typer::TypeConstant(), v8::internal::compiler::turboshaft::Typer::TypeWord32OverflowCheckedAdd(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::UnsignedLessThan(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::UnsignedLessThanOrEqual(), and v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::UnsignedLessThanOrEqual().
Contains()
template<size_t Bits>
bool v8::internal::compiler::turboshaft::WordType< Bits >::Contains (word_t value) const
Definition at line 176 of file types.cc.
                                                {
  switch (sub_kind()) {
    case SubKind::kRange: {
      if (is_wrapping()) return range_to() >= value || range_from() <= value;
      return range_from() <= value && value <= range_to();
    }
    case SubKind::kSet: {
      for (int i = 0; i < set_size(); ++i) {
        if (set_element(i) == value) return true;
      }
      return false;
    }
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::value.
Referenced by v8::internal::compiler::turboshaft::WordType< Bits >::IsSubtypeOf().
Equals()
template<size_t Bits>
bool v8::internal::compiler::turboshaft::WordType< Bits >::Equals (const WordType< Bits > & other) const
Definition at line 192 of file types.cc.
                                                             {
  if (sub_kind() != other.sub_kind()) return false;
  switch (sub_kind()) {
    case SubKind::kRange:
      return (range_from() == other.range_from() &&
              range_to() == other.range_to()) ||
             (is_any() && other.is_any());
    case SubKind::kSet: {
      if (set_size() != other.set_size()) return false;
      for (int i = 0; i < set_size(); ++i) {
        if (set_element(i) != other.set_element(i)) return false;
      }
      return true;
    }
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::WordType< Bits >::is_any(), v8::internal::compiler::turboshaft::WordType< Bits >::range_from(), v8::internal::compiler::turboshaft::WordType< Bits >::range_to(), v8::internal::compiler::turboshaft::WordType< Bits >::set_element(), v8::internal::compiler::turboshaft::WordType< Bits >::set_size(), and v8::internal::compiler::turboshaft::WordType< Bits >::sub_kind().
Intersect()
template<size_t Bits>
Type v8::internal::compiler::turboshaft::WordType< Bits >::Intersect (const WordType< Bits > & lhs, const WordType< Bits > & rhs, ResolutionMode resolution_mode, Zone * zone) [static]
Definition at line 344 of file types.cc.
                                                                           {
  if (lhs.is_any()) return rhs;
  if (rhs.is_any()) return lhs;
  if (lhs.is_set() || rhs.is_set()) {
    const auto& x = lhs.is_set() ? lhs : rhs;
    const auto& y = lhs.is_set() ? rhs : lhs;
    base::SmallVector<word_t, kMaxSetSize * 2> result_elements;
    for (int i = 0; i < x.set_size(); ++i) {
      const word_t element = x.set_element(i);
      if (y.Contains(element)) result_elements.push_back(element);
    }
    if (result_elements.empty()) return Type::None();
    DCHECK(detail::is_unique_and_sorted(result_elements));
    return Set(result_elements, zone);
  }
  DCHECK(lhs.is_range() && rhs.is_range());
  const bool lhs_wrapping = lhs.is_wrapping();
  if (!lhs_wrapping && !rhs.is_wrapping()) {
    const auto result_from = std::max(lhs.range_from(), rhs.range_from());
    const auto result_to = std::min(lhs.range_to(), rhs.range_to());
    return result_to < result_from
               ? Type::None()
               : WordType::Range(result_from, result_to, zone);
  }
  if (lhs_wrapping && rhs.is_wrapping()) {
    const auto result_from = std::max(lhs.range_from(), rhs.range_from());
    const auto result_to = std::min(lhs.range_to(), rhs.range_to());
    auto result = WordType::Range(result_from, result_to, zone);
    DCHECK(result.is_wrapping());
    return result;
  }
  const auto& x = lhs_wrapping ? lhs : rhs;
  const auto& y = lhs_wrapping ? rhs : lhs;
  DCHECK(x.is_wrapping());
  DCHECK(!y.is_wrapping());
  auto subrange_low = Intersect(y, Range(0, x.range_to(), zone),
                                ResolutionMode::kPreciseOrInvalid, zone);
  DCHECK(!subrange_low.IsInvalid());
  auto subrange_high = Intersect(
      y, Range(x.range_from(), std::numeric_limits<word_t>::max(), zone),
      ResolutionMode::kPreciseOrInvalid, zone);
  DCHECK(!subrange_high.IsInvalid());
  if (subrange_low.IsNone()) return subrange_high;
  if (subrange_high.IsNone()) return subrange_low;
  auto s_l = subrange_low.template AsWord<Bits>();
  auto s_h = subrange_high.template AsWord<Bits>();
  switch (resolution_mode) {
    case ResolutionMode::kPreciseOrInvalid:
      return Type::Invalid();
    case ResolutionMode::kOverApproximate:
      return LeastUpperBound(s_l, s_h, zone);
    case ResolutionMode::kGreatestLowerBound:
      return (s_l.unsigned_max() - s_l.unsigned_min() <
              s_h.unsigned_max() - s_h.unsigned_min())
                 ? s_h
                 : s_l;
  }
}
References v8::internal::DCHECK(), v8::base::SmallVector< T, kSize, Allocator >::empty(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::Type::Invalid(), v8::internal::compiler::turboshaft::WordType< Bits >::is_any(), v8::internal::compiler::turboshaft::WordType< Bits >::is_range(), v8::internal::compiler::turboshaft::WordType< Bits >::is_set(), v8::internal::compiler::turboshaft::detail::is_unique_and_sorted(), v8::internal::compiler::turboshaft::WordType< Bits >::is_wrapping(), v8::internal::compiler::turboshaft::Type::None(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), v8::internal::compiler::turboshaft::Range(), v8::internal::compiler::turboshaft::WordType< Bits >::Range(), v8::internal::compiler::turboshaft::WordType< Bits >::range_from(), v8::internal::compiler::turboshaft::WordType< Bits >::range_to(), v8::base::internal::result, and v8::internal::y.
Referenced by v8::internal::compiler::turboshaft::Typer::BranchRefinements::RefineWord32Type().
is_any()
template<size_t Bits>
bool v8::internal::compiler::turboshaft::WordType< Bits >::is_any () const [inline]
Definition at line 414 of file types.h.
{ return is_range() && range_to() + 1 == range_from(); }
Referenced by v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::Add(), v8::internal::compiler::turboshaft::WordType< Bits >::Equals(), v8::internal::compiler::turboshaft::WordType< Bits >::Intersect(), v8::internal::compiler::turboshaft::WordType< Bits >::IsSubtypeOf(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::Subtract(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::WidenExponential(), and v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::WidenMaximal().
is_constant() [1/2]
template<size_t Bits>
bool v8::internal::compiler::turboshaft::WordType< Bits >::is_constant () const [inline]
Definition at line 415 of file types.h.
                           {
    DCHECK_EQ(set_size_ > 0, is_set());
    return set_size_ == 1;
  }
References DCHECK_EQ.
is_constant() [2/2]
template<size_t Bits>
bool v8::internal::compiler::turboshaft::WordType< Bits >::is_constant (word_t value) const [inline]
Definition at line 460 of file types.h.
                                       {
    if (auto c = try_get_constant()) return *c == value;
    return false;
  }
References v8::internal::value.
is_range()
template<size_t Bits>
bool v8::internal::compiler::turboshaft::WordType< Bits >::is_range () const [inline]
Definition at line 412 of file types.h.
{ return sub_kind() == SubKind::kRange; }
Referenced by v8::internal::compiler::turboshaft::WordType< Bits >::Intersect(), v8::internal::compiler::turboshaft::WordType< Bits >::IsSubtypeOf(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::MakeRange(), and v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::WidenExponential().
is_set()
template<size_t Bits>
bool v8::internal::compiler::turboshaft::WordType< Bits >::is_set () const [inline]
Definition at line 413 of file types.h.
{ return sub_kind() == SubKind::kSet; }
Referenced by v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::Add(), v8::internal::compiler::turboshaft::WordType< Bits >::Intersect(), v8::internal::compiler::turboshaft::WordType< Bits >::IsSubtypeOf(), v8::internal::compiler::turboshaft::WordType< Bits >::LeastUpperBound(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::MakeRange(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::Subtract(), and v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::WidenExponential().
is_wrapping()
template<size_t Bits>
bool v8::internal::compiler::turboshaft::WordType< Bits >::is_wrapping () const [inline]
Definition at line 419 of file types.h.
{ return is_range() && range_from() > range_to(); }
Referenced by v8::internal::compiler::turboshaft::Typer::ExtendWord32ToWord64(), v8::internal::compiler::turboshaft::WordType< Bits >::Intersect(), v8::internal::compiler::turboshaft::WordType< Bits >::IsSubtypeOf(), v8::internal::compiler::turboshaft::WordType< Bits >::LeastUpperBound(), and v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::WidenMaximal().
IsSubtypeOf()
template<size_t Bits>
bool v8::internal::compiler::turboshaft::WordType< Bits >::IsSubtypeOf (const WordType< Bits > & other) const
Definition at line 210 of file types.cc.
                                                                  {
  if (other.is_any()) return true;
  switch (sub_kind()) {
    case SubKind::kRange: {
      if (other.is_set()) return false;
      DCHECK(other.is_range());
      if (is_wrapping() == other.is_wrapping()) {
        return range_from() >= other.range_from() &&
               range_to() <= other.range_to();
      }
      return !is_wrapping() && (range_to() <= other.range_to() ||
                                range_from() >= other.range_from());
    }
    case SubKind::kSet: {
      if (other.is_set() && set_size() > other.set_size()) return false;
      for (int i = 0; i < set_size(); ++i) {
        if (!other.Contains(set_element(i))) return false;
      }
      return true;
    }
  }
}
References v8::internal::compiler::turboshaft::WordType< Bits >::Contains(), v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::WordType< Bits >::is_any(), v8::internal::compiler::turboshaft::WordType< Bits >::is_range(), v8::internal::compiler::turboshaft::WordType< Bits >::is_set(), v8::internal::compiler::turboshaft::WordType< Bits >::is_wrapping(), v8::internal::compiler::turboshaft::WordType< Bits >::range_from(), v8::internal::compiler::turboshaft::WordType< Bits >::range_to(), and v8::internal::compiler::turboshaft::WordType< Bits >::set_size().
LeastUpperBound()
template<size_t Bits>
WordType< Bits > v8::internal::compiler::turboshaft::WordType< Bits >::LeastUpperBound (const WordType< Bits > & lhs, const WordType< Bits > & rhs, Zone * zone) [static]
Definition at line 295 of file types.cc.
                                                           {
  if (lhs.is_set()) {
    if (!rhs.is_set()) {
      if (lhs.set_size() == 1) {
        word_t e = lhs.set_element(0);
        if (rhs.is_wrapping()) {
          // If {rhs} already contains e, {rhs} is the upper bound.
          if (e <= rhs.range_to() || rhs.range_from() <= e) return rhs;
          return (e - rhs.range_to() < rhs.range_from() - e)
                     ? Range(rhs.range_from(), e, zone)
                     : Range(e, rhs.range_to(), zone);
        }
        return Range(std::min(e, rhs.range_from()), std::max(e, rhs.range_to()),
                     zone);
      }
      // TODO(nicohartmann@): A wrapping range may be a better fit in some
      // cases.
      return LeastUpperBoundFromRanges<Bits>(
          lhs.unsigned_min(), lhs.unsigned_max(), rhs.range_from(),
          rhs.range_to(), zone);
    }
    // Both sides are sets. We try to construct the combined set.
    base::SmallVector<word_t, kMaxSetSize * 2> result_elements;
    base::vector_append(result_elements, lhs.set_elements());
    base::vector_append(result_elements, rhs.set_elements());
    DCHECK(!result_elements.empty());
    base::sort(result_elements);
    auto it = std::unique(result_elements.begin(), result_elements.end());
    result_elements.pop_back(std::distance(it, result_elements.end()));
    if (result_elements.size() <= kMaxSetSize) {
      return Set(result_elements, zone);
    }
    // We have to construct a range instead.
    // TODO(nicohartmann@): A wrapping range may be a better fit in some cases.
    return Range(result_elements.front(), result_elements.back(), zone);
  } else if (rhs.is_set()) {
    return LeastUpperBound(rhs, lhs, zone);
  }
  // Both sides are ranges.
  return LeastUpperBoundFromRanges<Bits>(
      lhs.range_from(), lhs.range_to(), rhs.range_from(), rhs.range_to(), zone);
}
References v8::base::SmallVector< T, kSize, Allocator >::back(), v8::base::SmallVector< T, kSize, Allocator >::begin(), v8::internal::DCHECK(), v8::base::SmallVector< T, kSize, Allocator >::empty(), v8::base::SmallVector< T, kSize, Allocator >::end(), v8::base::SmallVector< T, kSize, Allocator >::front(), v8::internal::compiler::turboshaft::WordType< Bits >::is_set(), v8::internal::compiler::turboshaft::WordType< Bits >::is_wrapping(), v8::base::SmallVector< T, kSize, Allocator >::pop_back(), v8::internal::compiler::turboshaft::Range(), v8::internal::compiler::turboshaft::WordType< Bits >::range_from(), v8::internal::compiler::turboshaft::WordType< Bits >::range_to(), v8::internal::compiler::turboshaft::WordType< Bits >::set_element(), v8::internal::compiler::turboshaft::WordType< Bits >::set_elements(), v8::internal::compiler::turboshaft::WordType< Bits >::set_size(), v8::base::SmallVector< T, kSize, Allocator >::size(), v8::base::sort(), v8::internal::compiler::turboshaft::WordType< Bits >::unsigned_max(), v8::internal::compiler::turboshaft::WordType< Bits >::unsigned_min(), and v8::base::vector_append().
PrintTo()
template<size_t Bits>
void v8::internal::compiler::turboshaft::WordType< Bits >::PrintTo (std::ostream & stream) const
Definition at line 412 of file types.cc.
                                                     {
  stream << (Bits == 32 ? "Word32" : "Word64");
  switch (sub_kind()) {
    case SubKind::kRange:
      stream << "[0x" << std::hex << range_from() << ", 0x" << range_to()
             << std::dec << "]";
      break;
    case SubKind::kSet:
      stream << "{" << std::hex;
      for (int i = 0; i < set_size(); ++i) {
        stream << (i == 0 ? "0x" : ", 0x");
        stream << set_element(i);
      }
      stream << std::dec << "}";
      break;
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i.
range()
template<size_t Bits>
std::pair<word_t, word_t> v8::internal::compiler::turboshaft::WordType< Bits >::range () const [inline]
Definition at line 430 of file types.h.
                                        {
    DCHECK(is_range());
    return {range_from(), range_to()};
  }
References v8::internal::DCHECK().
Referenced by v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::MakeRange(), and v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::WidenExponential().
Range()
template<size_t Bits>
static WordType v8::internal::compiler::turboshaft::WordType< Bits >::Range (word_t from, word_t to, Zone * zone) [inline], [static]
Definition at line 342 of file types.h.
                                                            {
    // Normalize ranges smaller than {kMaxSetSize} to sets.
    if (to >= from) {
      // (to - from + 1) <= kMaxSetSize
      if (to - from <= kMaxSetSize - 1) {
        // Normalizing non-wrapping ranges to a Set.
        base::SmallVector<word_t, kMaxSetSize> elements;
        for (word_t i = from; i < to; ++i) elements.push_back(i);
        elements.push_back(to);
        return Set(elements, zone);
      }
    } else {
      // (max - from + 1) + (to + 1) <= kMaxSetSize
      if ((std::numeric_limits<word_t>::max() - from + to) <= kMaxSetSize - 2) {
        // Normalizing wrapping ranges to a Set.
        base::SmallVector<word_t, kMaxSetSize> elements;
        for (word_t i = from; i < std::numeric_limits<word_t>::max(); ++i) {
          elements.push_back(i);
        }
        elements.push_back(std::numeric_limits<word_t>::max());
        for (word_t i = 0; i < to; ++i) elements.push_back(i);
        elements.push_back(to);
        base::sort(elements);
        return Set(elements, zone);
      }
    }
    return WordType{SubKind::kRange, 0, Payload_Range{from, to}};
  }
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::WordType< Bits >::kMaxSetSize, v8::internal::compiler::turboshaft::WordType< Bits >::kRange, v8::base::SmallVector< T, kSize, Allocator >::push_back(), v8::internal::compiler::turboshaft::WordType< Bits >::Set(), and v8::base::sort().
Referenced by v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::Add(), v8::internal::compiler::turboshaft::WordType< Bits >::Any(), v8::internal::compiler::turboshaft::Typer::ExtendWord32ToWord64(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::FromElements(), v8::internal::compiler::turboshaft::WordType< Bits >::Intersect(), v8::internal::compiler::turboshaft::LeastUpperBoundFromRanges(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::RestrictionForUnsignedLessThan_False(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::RestrictionForUnsignedLessThan_True(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::RestrictionForUnsignedLessThanOrEqual_False(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::RestrictionForUnsignedLessThanOrEqual_True(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::Subtract(), v8::internal::compiler::turboshaft::Typer::TruncateWord32Input(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::WidenExponential(), and v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::WidenMaximal().
range_from()
template<size_t Bits>
word_t v8::internal::compiler::turboshaft::WordType< Bits >::range_from () const [inline]
Definition at line 422 of file types.h.
                            {
    DCHECK(is_range());
    return get_payload<Payload_Range>().min;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::compiler::turboshaft::WordType< Bits >::Equals(), v8::internal::compiler::turboshaft::WordType< Bits >::Intersect(), v8::internal::compiler::turboshaft::WordType< Bits >::IsSubtypeOf(), and v8::internal::compiler::turboshaft::WordType< Bits >::LeastUpperBound().
range_to()
template<size_t Bits>
word_t v8::internal::compiler::turboshaft::WordType< Bits >::range_to () const [inline]
Definition at line 426 of file types.h.
                          {
    DCHECK(is_range());
    return get_payload<Payload_Range>().max;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::compiler::turboshaft::WordType< Bits >::Equals(), v8::internal::compiler::turboshaft::WordType< Bits >::Intersect(), v8::internal::compiler::turboshaft::WordType< Bits >::IsSubtypeOf(), and v8::internal::compiler::turboshaft::WordType< Bits >::LeastUpperBound().
Set() [1/4]
template<size_t Bits>
static WordType v8::internal::compiler::turboshaft::WordType< Bits >::Set (base::Vector< const word_t > elements, Zone * zone) [inline], [static]
Definition at line 382 of file types.h.
                                                                     {
    DCHECK(detail::is_unique_and_sorted(elements));
    DCHECK_IMPLIES(elements.size() > kMaxInlineSetSize, zone != nullptr);
    DCHECK_GT(elements.size(), 0);
    DCHECK_LE(elements.size(), kMaxSetSize);
    if (elements.size() <= kMaxInlineSetSize) {
      // Use inline storage.
      Payload_InlineSet p;
      DCHECK_LT(0, elements.size());
      p.elements[0] = elements[0];
      if (elements.size() > 1) p.elements[1] = elements[1];
      return WordType{SubKind::kSet, static_cast<uint8_t>(elements.size()), p};
    } else {
      // Allocate storage in the zone.
#if defined(__GNUC__) && !defined(__clang__)
      // Work around a spurious GCC-12 warning. The DCHECK above already
      // checks the right precondition.
      if (zone == nullptr) return WordType::Any();
#endif
      Payload_OutlineSet p;
      p.array = zone->AllocateArray<word_t>(elements.size());
      DCHECK_NOT_NULL(p.array);
      for (size_t i = 0; i < elements.size(); ++i) p.array[i] = elements[i];
      return WordType{SubKind::kSet, static_cast<uint8_t>(elements.size()), p};
    }
  }
References v8::internal::Zone::AllocateArray(), v8::internal::compiler::turboshaft::WordType< Bits >::Any(), v8::internal::compiler::turboshaft::detail::Payload_OutlineSet< T >::array, v8::internal::DCHECK(), DCHECK_GT, DCHECK_IMPLIES, DCHECK_LE, DCHECK_LT, DCHECK_NOT_NULL, v8::internal::compiler::turboshaft::detail::Payload_InlineSet< T >::elements, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::detail::is_unique_and_sorted(), v8::internal::compiler::turboshaft::WordType< Bits >::kMaxInlineSetSize, v8::internal::compiler::turboshaft::WordType< Bits >::kMaxSetSize, v8::internal::compiler::turboshaft::WordType< Bits >::kSet, and v8::base::Vector< T >::size().
Set() [2/4]
template<size_t Bits>
template<size_t N>
static WordType v8::internal::compiler::turboshaft::WordType< Bits >::Set (const base::SmallVector< word_t, N > & elements, Zone * zone) [inline], [static]
Definition at line 371 of file types.h.
                                  {
    return Set(base::VectorOf(elements), zone);
  }
References v8::base::VectorOf().
Referenced by v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::FromElements(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::LessThan(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::LessThanOrEqual(), v8::internal::compiler::turboshaft::WordType< Bits >::Range(), v8::internal::compiler::turboshaft::WordType< Bits >::Set(), v8::internal::compiler::turboshaft::Typer::TypeComparison(), v8::internal::compiler::turboshaft::Typer::TypeFloat32Comparison(), v8::internal::compiler::turboshaft::Typer::TypeFloat64Comparison(), v8::internal::compiler::turboshaft::Typer::TypeOverflowCheckedBinop(), v8::internal::compiler::turboshaft::Typer::TypeWord32Comparison(), v8::internal::compiler::turboshaft::Typer::TypeWord32OverflowCheckedAdd(), v8::internal::compiler::turboshaft::Typer::TypeWord64Comparison(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::UnsignedLessThan(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::UnsignedLessThanOrEqual(), and v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::UnsignedLessThanOrEqual().
Set() [3/4]
template<size_t Bits>
static WordType v8::internal::compiler::turboshaft::WordType< Bits >::Set (const std::initializer_list< word_t > & elements, Zone * zone) [inline], [static]
Definition at line 378 of file types.h.
                                  {
    return Set(base::VectorOf(elements), zone);
  }
References v8::internal::compiler::turboshaft::WordType< Bits >::Set(), and v8::base::VectorOf().
Set() [4/4]
template<size_t Bits>
static WordType v8::internal::compiler::turboshaft::WordType< Bits >::Set (const std::vector< word_t > & elements, Zone * zone) [inline], [static]
Definition at line 375 of file types.h.
                                                                     {
    return Set(base::VectorOf(elements), zone);
  }
References v8::internal::compiler::turboshaft::WordType< Bits >::Set(), and v8::base::VectorOf().
set_element()
template<size_t Bits>
word_t v8::internal::compiler::turboshaft::WordType< Bits >::set_element (int index) const [inline]
Definition at line 438 of file types.h.
                                      {
    DCHECK(is_set());
    DCHECK_GE(index, 0);
    DCHECK_LT(index, set_size());
    return set_elements()[index];
  }
References v8::internal::DCHECK(), DCHECK_GE, DCHECK_LT, and v8::internal::index.
Referenced by v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::Add(), v8::internal::compiler::turboshaft::WordType< Bits >::Equals(), v8::internal::compiler::turboshaft::WordType< Bits >::LeastUpperBound(), and v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::Subtract().
set_elements()
template<size_t Bits>
base::Vector<const word_t> v8::internal::compiler::turboshaft::WordType< Bits >::set_elements () const [inline]
Definition at line 444 of file types.h.
                                                {
    DCHECK(is_set());
    if (set_size() <= kMaxInlineSetSize) {
      return base::Vector<const word_t>(
          get_payload<Payload_InlineSet>().elements, set_size());
    } else {
      return base::Vector<const word_t>(get_payload<Payload_OutlineSet>().array,
                                        set_size());
    }
  }
References v8::internal::DCHECK().
Referenced by v8::internal::compiler::turboshaft::WordType< Bits >::LeastUpperBound(), and v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::MakeRange().
set_size()
template<size_t Bits>
int v8::internal::compiler::turboshaft::WordType< Bits >::set_size () const [inline]
Definition at line 434 of file types.h.
                       {
    DCHECK(is_set());
    return static_cast<int>(set_size_);
  }
References v8::internal::DCHECK().
Referenced by v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::Add(), v8::internal::compiler::turboshaft::WordType< Bits >::Equals(), v8::internal::compiler::turboshaft::WordType< Bits >::IsSubtypeOf(), v8::internal::compiler::turboshaft::WordType< Bits >::LeastUpperBound(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::Subtract(), and v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::WidenExponential().
sub_kind()
template<size_t Bits>
SubKind v8::internal::compiler::turboshaft::WordType< Bits >::sub_kind () const [inline], [private]
Definition at line 499 of file types.h.
{ return static_cast<SubKind>(sub_kind_); }
Referenced by v8::internal::compiler::turboshaft::WordType< Bits >::Equals().
try_get_constant()
template<size_t Bits>
std::optional<word_t> v8::internal::compiler::turboshaft::WordType< Bits >::try_get_constant () const [inline]
Definition at line 454 of file types.h.
                                               {
    if (!is_constant()) return std::nullopt;
    DCHECK(is_set());
    DCHECK_EQ(set_size(), 1);
    return set_element(0);
  }
References v8::internal::DCHECK(), and DCHECK_EQ.
Referenced by v8::internal::compiler::turboshaft::TypedOptimizationsReducer< Next >::ReduceInputGraphBranch().
unsigned_max()
template<size_t Bits>
word_t v8::internal::compiler::turboshaft::WordType< Bits >::unsigned_max () const [inline]
Definition at line 472 of file types.h.
                              {
    switch (sub_kind()) {
      case SubKind::kRange:
        return is_wrapping() ? std::numeric_limits<word_t>::max() : range_to();
      case SubKind::kSet:
        DCHECK_GE(set_size(), 1);
        return set_element(set_size() - 1);
    }
  }
References DCHECK_GE.
Referenced by v8::internal::compiler::turboshaft::WordType< Bits >::LeastUpperBound(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::RestrictionForUnsignedLessThan_False(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::RestrictionForUnsignedLessThan_True(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::RestrictionForUnsignedLessThanOrEqual_False(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::RestrictionForUnsignedLessThanOrEqual_True(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::UnsignedLessThan(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::UnsignedLessThanOrEqual(), and v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::WidenMaximal().
unsigned_min()
template<size_t Bits>
word_t v8::internal::compiler::turboshaft::WordType< Bits >::unsigned_min () const [inline]
Definition at line 464 of file types.h.
                              {
    switch (sub_kind()) {
      case SubKind::kRange:
        return is_wrapping() ? word_t{0} : range_from();
      case SubKind::kSet:
        return set_element(0);
    }
  }
Referenced by v8::internal::compiler::turboshaft::Typer::ExtendWord32ToWord64(), v8::internal::compiler::turboshaft::WordType< Bits >::LeastUpperBound(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::RestrictionForUnsignedLessThan_False(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::RestrictionForUnsignedLessThan_True(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::RestrictionForUnsignedLessThanOrEqual_False(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::RestrictionForUnsignedLessThanOrEqual_True(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::UnsignedLessThan(), v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::UnsignedLessThanOrEqual(), and v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::WidenMaximal().
Friends And Related Function Documentation
Type
template<size_t Bits>
friend class Type [friend]
Definition at line 325 of file types.h.
Member Data Documentation
KIND
template<size_t Bits>
constexpr Kind v8::internal::compiler::turboshaft::WordType< Bits >::KIND = Bits == 32 ? Kind::kWord32 : Kind::kWord64 [static], [constexpr], [private]
Definition at line 494 of file types.h.
kMaxInlineSetSize
template<size_t Bits>
constexpr int v8::internal::compiler::turboshaft::WordType< Bits >::kMaxInlineSetSize = 2 [static], [constexpr], [private]
Definition at line 326 of file types.h.
Referenced by v8::internal::compiler::turboshaft::WordType< Bits >::Set().
kMaxSetSize
template<size_t Bits>
constexpr int v8::internal::compiler::turboshaft::WordType< Bits >::kMaxSetSize = 8 [static], [constexpr]
Definition at line 334 of file types.h.
Referenced by v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::FromElements(), v8::internal::compiler::turboshaft::WordType< Bits >::Range(), and v8::internal::compiler::turboshaft::WordType< Bits >::Set().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/types.h
/mnt/V8SourceCode/src/compiler/turboshaft/types.cc