v8::internal::compiler::MachineGraph Class Reference
#include <machine-graph.h>
Public Member Functions
MachineGraph (TFGraph *graph, CommonOperatorBuilder *common, MachineOperatorBuilder *machine)
MachineGraph (const MachineGraph &)=delete
MachineGraph & operator= (const MachineGraph &)=delete
Node * UniqueInt32Constant (int32_t value)
Node * UniqueInt64Constant (int64_t value)
Node * Int32Constant (int32_t value)
Node * Uint32Constant (uint32_t value)
Node * Int64Constant (int64_t value)
Node * Uint64Constant (uint64_t value)
Node * IntPtrConstant (intptr_t value)
Node * UintPtrConstant (uintptr_t value)
Node * UniqueIntPtrConstant (intptr_t value)
Node * TaggedIndexConstant (intptr_t value)
Node * RelocatableInt32Constant (int32_t value, RelocInfo::Mode rmode)
Node * RelocatableInt64Constant (int64_t value, RelocInfo::Mode rmode)
Node * RelocatableIntPtrConstant (intptr_t value, RelocInfo::Mode rmode)
Node * RelocatableWasmBuiltinCallTarget (Builtin builtin)
Node * Float32Constant (float value)
Node * Float64Constant (double value)
Node * PointerConstant (intptr_t value)
template<typename T >
Node * PointerConstant (T *value)
Node * ExternalConstant (ExternalReference ref)
Node * ExternalConstant (Runtime::FunctionId function_id)
Node * Dead ()
void StoreCallCount (NodeId call_id, int count)
int GetCallCount (NodeId call_id)
void ReserveCallCounts (size_t num_call_instructions)
CommonOperatorBuilder * common () const
MachineOperatorBuilder * machine () const
TFGraph * graph () const
Zone * zone () const
Protected Attributes
TFGraph * graph_
CommonOperatorBuilder * common_
MachineOperatorBuilder * machine_
CommonNodeCache cache_
NodeAuxDataMap< int, -1 > call_counts_
Node * Dead_ = nullptr
Detailed Description
Definition at line 24 of file machine-graph.h.
Constructor & Destructor Documentation
MachineGraph() [1/2]
v8::internal::compiler::MachineGraph::MachineGraph (TFGraph * graph, CommonOperatorBuilder * common, MachineOperatorBuilder * machine) [inline]
Definition at line 26 of file machine-graph.h.
      : graph_(graph),
        common_(common),
        machine_(machine),
        cache_(zone()),
        call_counts_(zone()) {}
MachineGraph() [2/2]
v8::internal::compiler::MachineGraph::MachineGraph (const MachineGraph &) [delete]
Member Function Documentation
common()
CommonOperatorBuilder* v8::internal::compiler::MachineGraph::common () const [inline]
Definition at line 100 of file machine-graph.h.
{ return common_; }
Referenced by v8::internal::compiler::WasmGraphBuilder::BuildWasmCall(), v8::internal::compiler::CloneFrameState(), v8::internal::compiler::AllocationBuilder::common(), v8::internal::compiler::JSSpeculativeBinopBuilder::common(), v8::internal::compiler::JSBinopReduction::common(), v8::internal::compiler::SimplifiedLowering::common(), v8::internal::compiler::WasmGCOperatorReducer::common(), v8::internal::compiler::BranchElimination::common(), v8::internal::compiler::BytecodeGraphBuilder::common(), v8::internal::compiler::CsaLoadElimination::common(), v8::internal::compiler::JSCallReducer::common(), v8::internal::compiler::JSCreateLowering::common(), v8::internal::compiler::JSInliningHeuristic::common(), v8::internal::compiler::JSInliner::common(), v8::internal::compiler::JSIntrinsicLowering::common(), v8::internal::compiler::JSNativeContextSpecialization::common(), v8::internal::compiler::JSTypedLowering::common(), v8::internal::compiler::LoadElimination::common(), v8::internal::compiler::MachineOperatorReducer::common(), v8::internal::compiler::PropertyAccessBuilder::common(), v8::internal::compiler::RepresentationSelector::common(), v8::internal::compiler::WasmLoadElimination::common(), v8::internal::compiler::anonymous_namespace{frame-states.cc}::CreateBuiltinContinuationFrameStateCommon(), ExternalConstant(), Float32Constant(), Float64Constant(), v8::internal::compiler::JSGraph::HeapConstantHole(), v8::internal::compiler::JSGraph::HeapConstantMaybeHole(), v8::internal::compiler::JSGraph::HeapConstantNoHole(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::LowerCompareMapsWithoutLoad(), v8::internal::compiler::VariableTracker::MergeInputs(), v8::internal::compiler::JSGraph::NumberConstant(), PointerConstant(), v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::PushRegularApiCallInputs(), v8::internal::compiler::SimplifyTFLoops::Reduce(), v8::internal::compiler::anonymous_namespace{js-typed-lowering.cc}::ReduceBuiltin(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode(), RelocatableInt32Constant(), RelocatableInt64Constant(), TaggedIndexConstant(), v8::internal::compiler::TFPipelineData::TFPipelineData(), v8::internal::compiler::JSGraph::TrustedHeapConstant(), UniqueInt32Constant(), UniqueInt64Constant(), v8::internal::compiler::Revectorizer::VectorizeTree(), and v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::WasmIntoJSInlinerImpl().
Dead()
Node* v8::internal::compiler::MachineGraph::Dead () [inline]
Definition at line 86 of file machine-graph.h.
               {
    return Dead_ ? Dead_ : Dead_ = graph_->NewNode(common_->Dead());
  }
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccessForTypedArrayOrRabGsabTypedArray(), v8::internal::compiler::GraphAssembler::ConnectUnreachableToEnd(), v8::internal::compiler::VariableTracker::MergeInputs(), v8::internal::compiler::WasmEscapeAnalysis::ReduceAllocateRaw(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccess(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetIterator(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSHasProperty(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadProperty(), v8::internal::compiler::JSNativeContextSpecialization::ReduceNamedAccess(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode(), and v8::internal::compiler::Revectorizer::VectorizeTree().
ExternalConstant() [1/2]
Node * v8::internal::compiler::MachineGraph::ExternalConstant (ExternalReference ref)
Definition at line 117 of file machine-graph.cc.
                                                                {
  Node** loc = cache_.FindExternalConstant(reference);
  if (*loc == nullptr) {
    *loc = graph()->NewNode(common()->ExternalConstant(reference));
  }
  return *loc;
}
References cache_, common(), v8::internal::compiler::CommonNodeCache::FindExternalConstant(), graph(), v8::internal::loc, and v8::internal::compiler::TFGraph::NewNode().
Referenced by v8::internal::compiler::WasmGraphBuilder::BuildCallToRuntimeWithContext(), ExternalConstant(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeShift(), and v8::internal::compiler::anonymous_namespace{js-typed-lowering.cc}::ReduceBuiltin().
ExternalConstant() [2/2]
Node * v8::internal::compiler::MachineGraph::ExternalConstant (Runtime::FunctionId function_id)
Definition at line 125 of file machine-graph.cc.
                                                                  {
  return ExternalConstant(ExternalReference::Create(function_id));
}
References v8::internal::ExternalReference::Create(), and ExternalConstant().
Float32Constant()
Node * v8::internal::compiler::MachineGraph::Float32Constant (float value)
Definition at line 93 of file machine-graph.cc.
                                               {
  Node** loc = cache_.FindFloat32Constant(value);
  if (*loc == nullptr) {
    *loc = graph()->NewNode(common()->Float32Constant(value));
  }
  return *loc;
}
References cache_, common(), v8::internal::compiler::CommonNodeCache::FindFloat32Constant(), graph(), v8::internal::loc, v8::internal::compiler::TFGraph::NewNode(), and v8::internal::value.
Referenced by v8::internal::compiler::RepresentationChanger::GetFloat32RepresentationFor().
Float64Constant()
Node * v8::internal::compiler::MachineGraph::Float64Constant (double value)
Definition at line 101 of file machine-graph.cc.
                                                {
  Node** loc = cache_.FindFloat64Constant(value);
  if (*loc == nullptr) {
    *loc = graph()->NewNode(common()->Float64Constant(value));
  }
  return *loc;
}
References cache_, common(), v8::internal::compiler::CommonNodeCache::FindFloat64Constant(), graph(), v8::internal::loc, v8::internal::compiler::TFGraph::NewNode(), and v8::internal::value.
Referenced by v8::internal::compiler::SimplifiedLowering::DoIntegerToUint8Clamped(), v8::internal::compiler::SimplifiedLowering::DoNumberToUint8Clamped(), v8::internal::compiler::MachineOperatorReducer::Float64Constant(), v8::internal::compiler::SimplifiedLowering::Float64Round(), v8::internal::compiler::SimplifiedLowering::Float64Sign(), and v8::internal::compiler::RepresentationChanger::GetFloat64RepresentationFor().
GetCallCount()
int v8::internal::compiler::MachineGraph::GetCallCount (NodeId call_id) [inline]
Definition at line 94 of file machine-graph.h.
{ return call_counts_.Get(call_id); }
graph()
TFGraph* v8::internal::compiler::MachineGraph::graph () const [inline]
Definition at line 102 of file machine-graph.h.
{ return graph_; }
Referenced by v8::internal::compiler::JSTypeHintLowering::BuildDeoptIfFeedbackIsInsufficient(), v8::internal::compiler::CloneFrameState(), v8::internal::compiler::JSGenericLowering::common(), v8::internal::compiler::anonymous_namespace{frame-states.cc}::CreateBuiltinContinuationFrameStateCommon(), ExternalConstant(), v8::internal::compiler::EscapeAnalysisReducer::Finalize(), Float32Constant(), Float64Constant(), v8::internal::compiler::RepresentationChanger::GetBitRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetFloat16RawBitsRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetFloat32RepresentationFor(), v8::internal::compiler::RepresentationChanger::GetFloat64RepresentationFor(), v8::internal::compiler::RepresentationChanger::GetRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetTaggedPointerRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetTaggedRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetTaggedSignedRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetWord32RepresentationFor(), v8::internal::compiler::RepresentationChanger::GetWord64RepresentationFor(), v8::internal::compiler::AllocationBuilder::graph(), v8::internal::compiler::SimplifiedLowering::graph(), v8::internal::compiler::WasmGraphBuilder::graph(), v8::internal::compiler::WasmGCOperatorReducer::graph(), v8::internal::compiler::BranchElimination::graph(), v8::internal::compiler::BytecodeGraphBuilder::graph(), v8::internal::compiler::CsaLoadElimination::graph(), v8::internal::compiler::JSCallReducer::graph(), v8::internal::compiler::JSCreateLowering::graph(), v8::internal::compiler::JSInliningHeuristic::graph(), v8::internal::compiler::JSInliner::graph(), v8::internal::compiler::JSIntrinsicLowering::graph(), v8::internal::compiler::JSNativeContextSpecialization::graph(), v8::internal::compiler::JSSpeculativeBinopBuilder::graph(), v8::internal::compiler::JSTypedLowering::graph(), v8::internal::compiler::LoadElimination::graph(), v8::internal::compiler::MachineOperatorReducer::graph(), v8::internal::compiler::MemoryOptimizer::graph(), v8::internal::compiler::PropertyAccessBuilder::graph(), v8::internal::compiler::RepresentationSelector::graph(), v8::internal::compiler::SimplifiedOperatorReducer::graph(), v8::internal::compiler::TypeNarrowingReducer::graph(), v8::internal::compiler::TypedOptimization::graph(), v8::internal::compiler::WasmLoadElimination::graph(), v8::internal::compiler::JSGraph::HeapConstantHole(), v8::internal::compiler::JSGraph::HeapConstantMaybeHole(), v8::internal::compiler::JSGraph::HeapConstantNoHole(), v8::internal::compiler::RepresentationChanger::InsertChangeBitToTagged(), v8::internal::compiler::RepresentationChanger::InsertChangeFloat16RawBitsToFloat64Fallback(), v8::internal::compiler::RepresentationChanger::InsertChangeFloat32ToFloat64(), v8::internal::compiler::RepresentationChanger::InsertChangeFloat64ToInt32(), v8::internal::compiler::RepresentationChanger::InsertChangeFloat64ToUint32(), v8::internal::compiler::RepresentationChanger::InsertChangeInt32ToFloat64(), v8::internal::compiler::RepresentationChanger::InsertChangeTaggedSignedToInt32(), v8::internal::compiler::RepresentationChanger::InsertChangeTaggedToFloat64(), v8::internal::compiler::RepresentationChanger::InsertChangeUint32ToFloat64(), v8::internal::compiler::RepresentationChanger::InsertConversion(), v8::internal::compiler::MapInference::InsertMapChecks(), v8::internal::compiler::RepresentationChanger::InsertTruncateFloat64ToFloat16RawBitsFallback(), v8::internal::compiler::RepresentationChanger::InsertTruncateInt64ToInt32(), v8::internal::compiler::RepresentationChanger::InsertTypeOverrideForVerifier(), v8::internal::compiler::RepresentationChanger::InsertUnconditionalDeopt(), v8::internal::compiler::RedundancyElimination::EffectPathChecks::LookupCheck(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::LowerCompareMapsWithoutLoad(), v8::internal::compiler::VariableTracker::MergeInputs(), v8::internal::compiler::JSGraph::NumberConstant(), v8::internal::compiler::EscapeAnalysisReducer::ObjectIdNode(), PointerConstant(), v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::PushRegularApiCallInputs(), v8::internal::compiler::SimplifyTFLoops::Reduce(), v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContext(), v8::internal::compiler::JSContextSpecialization::ReduceJSStoreContext(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode(), v8::internal::compiler::JSTypeHintLowering::ReduceToNumberOperation(), v8::internal::compiler::JSTypeHintLowering::ReduceUnaryOperation(), RelocatableInt32Constant(), RelocatableInt64Constant(), v8::internal::compiler::BranchElimination::SimplifyBranchCondition(), TaggedIndexConstant(), v8::internal::compiler::JSGraph::TrustedHeapConstant(), UniqueInt32Constant(), UniqueInt64Constant(), and v8::internal::compiler::RepresentationSelector::VisitFrameState().
Int32Constant()
Node * v8::internal::compiler::MachineGraph::Int32Constant (int32_t value)
Definition at line 21 of file machine-graph.cc.
                                               {
  Node** loc = cache_.FindInt32Constant(value);
  if (*loc == nullptr) {
    *loc = UniqueInt32Constant(value);
  }
  return *loc;
}
References cache_, v8::internal::compiler::CommonNodeCache::FindInt32Constant(), v8::internal::loc, UniqueInt32Constant(), and v8::internal::value.
Referenced by v8::internal::compiler::SimplifiedLowering::DoIntegral32ToBit(), v8::internal::compiler::SimplifiedLowering::DoSigned32ToUint8Clamped(), v8::internal::compiler::MachineOperatorReducer::Int32Constant(), v8::internal::compiler::WasmGraphBuilder::Int32Constant(), v8::internal::compiler::SimplifiedLowering::Int32Div(), v8::internal::compiler::SimplifiedLowering::Int32Mod(), v8::internal::compiler::SimplifiedLowering::Int32Sign(), IntPtrConstant(), v8::internal::compiler::RepresentationChanger::MakeTruncatedInt32Constant(), v8::internal::compiler::RepresentationSelector::MaskShiftOperand(), v8::internal::compiler::SimplifiedOperatorReducer::Reduce(), v8::internal::compiler::JSNativeContextSpecialization::ReduceMegaDOMPropertyAccess(), v8::internal::compiler::SimplifiedLowering::Uint32Mod(), UniqueInt32Constant(), v8::internal::compiler::RepresentationSelector::VisitNode(), and v8::internal::compiler::RepresentationSelector::VisitObjectIs().
Int64Constant()
Node * v8::internal::compiler::MachineGraph::Int64Constant (int64_t value)
Definition at line 29 of file machine-graph.cc.
                                               {
  Node** loc = cache_.FindInt64Constant(value);
  if (*loc == nullptr) {
    *loc = UniqueInt64Constant(value);
  }
  return *loc;
}
References cache_, v8::internal::compiler::CommonNodeCache::FindInt64Constant(), v8::internal::loc, UniqueInt64Constant(), and v8::internal::value.
Referenced by IntPtrConstant(), v8::internal::compiler::RepresentationSelector::TryOptimizeBigInt64Shift(), UniqueInt64Constant(), v8::internal::compiler::Revectorizer::VectorizeTree(), and v8::internal::compiler::RepresentationSelector::VisitNode().
IntPtrConstant()
Node * v8::internal::compiler::MachineGraph::IntPtrConstant (intptr_t value)
Definition at line 37 of file machine-graph.cc.
                                                 {
  return machine()->Is32() ? Int32Constant(static_cast<int32_t>(value))
                           : Int64Constant(static_cast<int64_t>(value));
}
References Int32Constant(), Int64Constant(), v8::internal::compiler::MachineOperatorBuilder::Is32(), machine(), and v8::internal::value.
Referenced by v8::internal::compiler::WasmGraphAssembler::BuildChangeUint32ToUintPtr(), v8::internal::compiler::WasmGraphBuilder::BuildLoadIsolateRoot(), v8::internal::compiler::WasmGraphBuilder::NoContextConstant(), and v8::internal::compiler::RepresentationSelector::VisitNode().
machine()
MachineOperatorBuilder* v8::internal::compiler::MachineGraph::machine () const [inline]
Definition at line 101 of file machine-graph.h.
{ return machine_; }
Referenced by v8::internal::compiler::WasmGraphAssembler::BuildChangeInt32ToIntPtr(), v8::internal::compiler::WasmGraphAssembler::BuildChangeIntPtrToInt64(), v8::internal::compiler::WasmGraphAssembler::BuildTruncateIntPtrToInt32(), v8::internal::compiler::CompileWasmJSFastCallWrapper(), v8::internal::compiler::WasmGraphBuilder::GetSafeLoadOperator(), IntPtrConstant(), v8::internal::compiler::RedundancyElimination::EffectPathChecks::LookupCheck(), v8::internal::compiler::RepresentationChanger::machine(), v8::internal::compiler::SimplifiedLowering::machine(), v8::internal::compiler::CsaLoadElimination::machine(), v8::internal::compiler::JSGenericLowering::machine(), v8::internal::compiler::MachineOperatorReducer::machine(), v8::internal::compiler::SimplifiedOperatorReducer::machine(), v8::internal::compiler::WasmLoadElimination::machine(), v8::internal::compiler::RepresentationSelector::MaskShiftOperand(), v8::internal::compiler::PairLoadStoreReducer::Reduce(), v8::internal::compiler::WasmGCLowering::ReduceWasmAnyConvertExtern(), v8::internal::compiler::TFPipelineData::TFPipelineData(), UintPtrConstant(), UniqueIntPtrConstant(), v8::internal::compiler::Revectorizer::VectorizeTree(), v8::internal::compiler::RepresentationSelector::VisitCheckBounds(), v8::internal::compiler::RepresentationSelector::VisitNode(), and v8::internal::compiler::WasmGraphAssembler::WasmArrayElementOffset().
operator=()
MachineGraph& v8::internal::compiler::MachineGraph::operator= (const MachineGraph &) [delete]
PointerConstant() [1/2]
Node * v8::internal::compiler::MachineGraph::PointerConstant (intptr_t value)
Definition at line 109 of file machine-graph.cc.
                                                  {
  Node** loc = cache_.FindPointerConstant(value);
  if (*loc == nullptr) {
    *loc = graph()->NewNode(common()->PointerConstant(value));
  }
  return *loc;
}
References cache_, common(), v8::internal::compiler::CommonNodeCache::FindPointerConstant(), graph(), v8::internal::loc, v8::internal::compiler::TFGraph::NewNode(), and v8::internal::value.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccessForTypedArrayOrRabGsabTypedArray().
PointerConstant() [2/2]
template<typename T >
Node* v8::internal::compiler::MachineGraph::PointerConstant (T * value) [inline]
Definition at line 77 of file machine-graph.h.
                                  {
    return PointerConstant(reinterpret_cast<intptr_t>(value));
  }
References v8::internal::compiler::PointerConstant(), and v8::internal::value.
RelocatableInt32Constant()
Node * v8::internal::compiler::MachineGraph::RelocatableInt32Constant (int32_t value, RelocInfo::Mode rmode)
Definition at line 61 of file machine-graph.cc.
                                                                  {
  Node** loc = cache_.FindRelocatableInt32Constant(
      value, static_cast<RelocInfoMode>(rmode));
  if (*loc == nullptr) {
    *loc = graph()->NewNode(common()->RelocatableInt32Constant(value, rmode));
  }
  return *loc;
}
References cache_, common(), v8::internal::compiler::CommonNodeCache::FindRelocatableInt32Constant(), graph(), v8::internal::loc, v8::internal::compiler::TFGraph::NewNode(), and v8::internal::value.
Referenced by RelocatableIntPtrConstant().
RelocatableInt64Constant()
Node * v8::internal::compiler::MachineGraph::RelocatableInt64Constant (int64_t value, RelocInfo::Mode rmode)
Definition at line 71 of file machine-graph.cc.
                                                                  {
  Node** loc = cache_.FindRelocatableInt64Constant(
      value, static_cast<RelocInfoMode>(rmode));
  if (*loc == nullptr) {
    *loc = graph()->NewNode(common()->RelocatableInt64Constant(value, rmode));
  }
  return *loc;
}
References cache_, common(), v8::internal::compiler::CommonNodeCache::FindRelocatableInt64Constant(), graph(), v8::internal::loc, v8::internal::compiler::TFGraph::NewNode(), and v8::internal::value.
Referenced by RelocatableIntPtrConstant().
RelocatableIntPtrConstant()
Node * v8::internal::compiler::MachineGraph::RelocatableIntPtrConstant (intptr_t value, RelocInfo::Mode rmode)
Definition at line 81 of file machine-graph.cc.
                                                                   {
  return kSystemPointerSize == 8
             ? RelocatableInt64Constant(value, rmode)
             : RelocatableInt32Constant(static_cast<int>(value), rmode);
}
References v8::internal::kSystemPointerSize, RelocatableInt32Constant(), RelocatableInt64Constant(), and v8::internal::value.
Referenced by RelocatableWasmBuiltinCallTarget().
RelocatableWasmBuiltinCallTarget()
Node * v8::internal::compiler::MachineGraph::RelocatableWasmBuiltinCallTarget (Builtin builtin)
Definition at line 88 of file machine-graph.cc.
                                                                    {
  return RelocatableIntPtrConstant(static_cast<intptr_t>(builtin),
                                   RelocInfo::WASM_STUB_CALL);
}
References RelocatableIntPtrConstant(), and v8::internal::RelocInfo::WASM_STUB_CALL.
Referenced by v8::internal::compiler::WasmGraphAssembler::CallBuiltinThroughJumptable().
ReserveCallCounts()
void v8::internal::compiler::MachineGraph::ReserveCallCounts (size_t num_call_instructions) [inline]
Definition at line 96 of file machine-graph.h.
                                                       {
    call_counts_.Reserve(num_call_instructions);
  }
StoreCallCount()
void v8::internal::compiler::MachineGraph::StoreCallCount (NodeId call_id, int count) [inline]
Definition at line 91 of file machine-graph.h.
                                                 {
    call_counts_.Put(call_id, count);
  }
TaggedIndexConstant()
Node * v8::internal::compiler::MachineGraph::TaggedIndexConstant (intptr_t value)
Definition at line 52 of file machine-graph.cc.
                                                      {
  int32_t value32 = static_cast<int32_t>(value);
  Node** loc = cache_.FindTaggedIndexConstant(value32);
  if (*loc == nullptr) {
    *loc = graph()->NewNode(common()->TaggedIndexConstant(value32));
  }
  return *loc;
}
References cache_, common(), v8::internal::compiler::CommonNodeCache::FindTaggedIndexConstant(), graph(), v8::internal::loc, v8::internal::compiler::TFGraph::NewNode(), and v8::internal::value.
Uint32Constant()
Node* v8::internal::compiler::MachineGraph::Uint32Constant (uint32_t value) [inline]
Definition at line 43 of file machine-graph.h.
                                       {
    return Int32Constant(base::bit_cast<int32_t>(value));
  }
References v8::internal::value.
Referenced by v8::internal::compiler::WasmGraphAssembler::BuildConvertUint32ToSmiWithSaturation(), v8::internal::compiler::SimplifiedLowering::DoUnsigned32ToUint8Clamped(), v8::internal::compiler::RepresentationChanger::GetFloat16RawBitsRepresentationFor(), v8::internal::compiler::SimplifiedLowering::Uint32Div(), v8::internal::compiler::SimplifiedLowering::Uint32Mod(), and UintPtrConstant().
Uint64Constant()
Node* v8::internal::compiler::MachineGraph::Uint64Constant (uint64_t value) [inline]
Definition at line 49 of file machine-graph.h.
                                       {
    return Int64Constant(base::bit_cast<int64_t>(value));
  }
References v8::internal::value.
Referenced by UintPtrConstant(), and v8::internal::compiler::RepresentationSelector::VisitNode().
UintPtrConstant()
Node * v8::internal::compiler::MachineGraph::UintPtrConstant (uintptr_t value)
Definition at line 42 of file machine-graph.cc.
                                                   {
  return machine()->Is32() ? Uint32Constant(static_cast<uint32_t>(value))
                           : Uint64Constant(static_cast<uint64_t>(value));
}
References v8::internal::compiler::MachineOperatorBuilder::Is32(), machine(), Uint32Constant(), Uint64Constant(), and v8::internal::value.
UniqueInt32Constant()
Node * v8::internal::compiler::MachineGraph::UniqueInt32Constant (int32_t value)
Definition at line 13 of file machine-graph.cc.
                                                     {
  return graph()->NewNode(common()->Int32Constant(value));
}
References common(), graph(), Int32Constant(), v8::internal::compiler::TFGraph::NewNode(), and v8::internal::value.
Referenced by Int32Constant(), and UniqueIntPtrConstant().
UniqueInt64Constant()
Node * v8::internal::compiler::MachineGraph::UniqueInt64Constant (int64_t value)
Definition at line 17 of file machine-graph.cc.
                                                     {
  return graph()->NewNode(common()->Int64Constant(value));
}
References common(), graph(), Int64Constant(), v8::internal::compiler::TFGraph::NewNode(), and v8::internal::value.
Referenced by Int64Constant(), and UniqueIntPtrConstant().
UniqueIntPtrConstant()
Node * v8::internal::compiler::MachineGraph::UniqueIntPtrConstant (intptr_t value)
Definition at line 47 of file machine-graph.cc.
                                                       {
  return machine()->Is32() ? UniqueInt32Constant(static_cast<int32_t>(value))
                           : UniqueInt64Constant(static_cast<int64_t>(value));
}
References v8::internal::compiler::MachineOperatorBuilder::Is32(), machine(), UniqueInt32Constant(), UniqueInt64Constant(), and v8::internal::value.
zone()
Zone* v8::internal::compiler::MachineGraph::zone () const [inline]
Definition at line 103 of file machine-graph.h.
{ return graph()->zone(); }
References graph().
Referenced by v8::internal::compiler::RepresentationSelector::ChangeUnaryToPureBinaryOp(), v8::internal::compiler::RepresentationSelector::graph_zone(), v8::internal::compiler::RepresentationChanger::Ieee754Fp16RawBitsToFp32RawBitsOperator(), v8::internal::compiler::RepresentationChanger::Ieee754Fp64ToFp16RawBitsOperator(), v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::PushRegularApiCallInputs(), v8::internal::compiler::PairLoadStoreReducer::Reduce(), v8::internal::compiler::anonymous_namespace{js-typed-lowering.cc}::ReduceBuiltin(), v8::internal::compiler::JSTypedLowering::ReduceJSHasContextExtension(), v8::internal::compiler::RepresentationSelector::VisitFrameState(), v8::internal::compiler::RepresentationSelector::VisitNode(), v8::internal::compiler::RepresentationSelector::VisitObjectState(), v8::internal::compiler::RepresentationSelector::VisitStateValues(), and v8::internal::compiler::SimplifiedLowering::zone().
Member Data Documentation
cache_
CommonNodeCache v8::internal::compiler::MachineGraph::cache_ [protected]
Definition at line 109 of file machine-graph.h.
Referenced by ExternalConstant(), Float32Constant(), Float64Constant(), v8::internal::compiler::JSGraph::GetCachedNodes(), v8::internal::compiler::JSGraph::HeapConstantHole(), v8::internal::compiler::JSGraph::HeapConstantMaybeHole(), v8::internal::compiler::JSGraph::HeapConstantNoHole(), Int32Constant(), Int64Constant(), v8::internal::compiler::JSGraph::NumberConstant(), PointerConstant(), RelocatableInt32Constant(), RelocatableInt64Constant(), and TaggedIndexConstant().
call_counts_
NodeAuxDataMap<int, -1> v8::internal::compiler::MachineGraph::call_counts_ [protected]
Definition at line 110 of file machine-graph.h.
common_
CommonOperatorBuilder* v8::internal::compiler::MachineGraph::common_ [protected]
Definition at line 107 of file machine-graph.h.
Dead_
Node* v8::internal::compiler::MachineGraph::Dead_ = nullptr [protected]
Definition at line 111 of file machine-graph.h.
graph_
TFGraph* v8::internal::compiler::MachineGraph::graph_ [protected]
Definition at line 106 of file machine-graph.h.
machine_
MachineOperatorBuilder* v8::internal::compiler::MachineGraph::machine_ [protected]
Definition at line 108 of file machine-graph.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/machine-graph.h
/mnt/V8SourceCode/src/compiler/machine-graph.cc