v8::internal::compiler::Truncation Class Reference
#include <use-info.h>
Public Member Functions
bool IsUnused () const
bool IsUsedAsBool () const
bool IsUsedAsWord32 () const
bool IsUsedAsWord64 () const
bool TruncatesBooleanAndNullAndBigIntToNumber () const
bool TruncatesOddballAndBigIntToNumber () const
bool IdentifiesUndefinedAndZero ()
bool IdentifiesZeroAndMinusZero () const
bool operator== (Truncation other) const
bool operator!= (Truncation other) const
const char * description () const
bool IsLessGeneralThan (Truncation other) const
IdentifyZeros identify_zeros () const
bool check_safe_integer () const
Static Public Member Functions
static Truncation None ()
static Truncation Bool ()
static Truncation Word32 ()
static Truncation Word32WithSafeIntCheck ()
static Truncation Word64 ()
static Truncation BooleanAndNullAndBigIntToNumber (IdentifyZeros identify_zeros=kDistinguishZeros)
static Truncation OddballAndBigIntToNumber (IdentifyZeros identify_zeros=kDistinguishZeros)
static Truncation Any (IdentifyZeros identify_zeros=kDistinguishZeros, bool check_safe_integer=false)
static Truncation Generalize (Truncation t1, Truncation t2)
Private Types
enum class TruncationKind : uint8_t {
kNone
, kBool
, kWord32
, kWord64
,
kOddballAndBigIntToNumber
, kBooleanAndNullAndBigIntToNumber
, kAny
 }
Private Member Functions
Truncation (TruncationKind kind, IdentifyZeros identify_zeros, bool check_safe_integer=false)
TruncationKind kind () const
Static Private Member Functions
static TruncationKind Generalize (TruncationKind rep1, TruncationKind rep2)
static IdentifyZeros GeneralizeIdentifyZeros (IdentifyZeros i1, IdentifyZeros i2)
static bool LessGeneral (TruncationKind rep1, TruncationKind rep2)
static bool LessGeneralIdentifyZeros (IdentifyZeros u1, IdentifyZeros u2)
Private Attributes
TruncationKind kind_
IdentifyZeros identify_zeros_
bool check_safe_integer_
Friends
class SimplifiedLoweringVerifier
size_t hash_value (const Truncation &)
Detailed Description
Definition at line 26 of file use-info.h.
Member Enumeration Documentation
TruncationKind
enum v8::internal::compiler::Truncation::TruncationKind : uint8_t [strong], [private]
Enumerator
kNone
kBool
kWord32
kWord64
kOddballAndBigIntToNumber
kBooleanAndNullAndBigIntToNumber
kAny
Definition at line 113 of file use-info.h.
                            : uint8_t {
    kNone,
    kBool,
    kWord32,
    kWord64,
    kOddballAndBigIntToNumber,
    kBooleanAndNullAndBigIntToNumber,
    kAny
  };
Constructor & Destructor Documentation
Truncation()
v8::internal::compiler::Truncation::Truncation (TruncationKind kind, IdentifyZeros identify_zeros, bool check_safe_integer = false) [inline], [explicit], [private]
Definition at line 123 of file use-info.h.
      : kind_(kind),
        identify_zeros_(identify_zeros),
        check_safe_integer_(check_safe_integer) {}
Referenced by Any(), Bool(), BooleanAndNullAndBigIntToNumber(), Generalize(), None(), OddballAndBigIntToNumber(), Word32(), Word32WithSafeIntCheck(), and Word64().
Member Function Documentation
Any()
static Truncation v8::internal::compiler::Truncation::Any (IdentifyZeros identify_zeros = kDistinguishZeros, bool check_safe_integer = false) [inline], [static]
Definition at line 54 of file use-info.h.
                                                         {
    return Truncation(TruncationKind::kAny, identify_zeros, check_safe_integer);
  }
References check_safe_integer(), identify_zeros(), kAny, and Truncation().
Referenced by v8::internal::compiler::UseInfo::Any(), v8::internal::compiler::UseInfo::AnyTagged(), v8::internal::compiler::UseInfo::CheckedBigInt64AsWord64(), v8::internal::compiler::UseInfo::CheckedBigIntAsTaggedPointer(), v8::internal::compiler::UseInfo::CheckedHeapObjectAsTaggedPointer(), v8::internal::compiler::UseInfo::CheckedNumberAsFloat64(), v8::internal::compiler::UseInfo::CheckedNumberOrBooleanAsFloat64(), v8::internal::compiler::UseInfo::CheckedNumberOrOddballAsFloat64(), v8::internal::compiler::UseInfo::CheckedSafeIntAsWord64(), v8::internal::compiler::UseInfo::CheckedSigned32AsWord32(), v8::internal::compiler::UseInfo::CheckedSigned64AsWord64(), v8::internal::compiler::UseInfo::CheckedSignedSmallAsTaggedSigned(), v8::internal::compiler::UseInfo::CheckedSignedSmallAsWord32(), v8::internal::compiler::UseInfo::CheckedTaggedAsArrayIndex(), v8::internal::compiler::UseInfo::Float16RawBits(), v8::internal::compiler::UseInfo::Float32(), v8::internal::compiler::UseInfo::Float64(), v8::internal::compiler::SimplifiedLoweringVerifier::GeneralizeTruncation(), v8::internal::compiler::RepresentationChanger::GetWord32RepresentationFor(), v8::internal::compiler::SimplifiedLoweringVerifier::InputTruncation(), v8::internal::compiler::IsModuloTruncation(), v8::internal::compiler::SimplifiedLoweringVerifier::ResizeDataIfNecessary(), v8::internal::compiler::UseInfo::TaggedPointer(), v8::internal::compiler::UseInfo::TaggedSigned(), v8::internal::compiler::SimplifiedLoweringVerifier::VisitNode(), v8::internal::compiler::RepresentationSelector::VisitNode(), v8::internal::compiler::UseInfo::Word(), and v8::internal::compiler::UseInfo::Word64().
Bool()
static Truncation v8::internal::compiler::Truncation::Bool () [inline], [static]
Definition at line 32 of file use-info.h.
                           {
    return Truncation(TruncationKind::kBool, kIdentifyZeros);
  }
References kBool, v8::internal::compiler::kIdentifyZeros, and Truncation().
Referenced by v8::internal::compiler::UseInfo::AnyTruncatingToBool(), v8::internal::compiler::UseInfo::Bool(), and v8::internal::compiler::SimplifiedLoweringVerifier::VisitNode().
BooleanAndNullAndBigIntToNumber()
static Truncation v8::internal::compiler::Truncation::BooleanAndNullAndBigIntToNumber (IdentifyZeros identify_zeros = kDistinguishZeros) [inline], [static]
Definition at line 44 of file use-info.h.
                                                        {
    return Truncation(TruncationKind::kBooleanAndNullAndBigIntToNumber,
                      identify_zeros);
  }
References identify_zeros(), kBooleanAndNullAndBigIntToNumber, and Truncation().
Referenced by v8::internal::compiler::UseInfo::TruncatingFloat64OrUndefined(), and v8::internal::compiler::RepresentationSelector::VisitNode().
check_safe_integer()
bool v8::internal::compiler::Truncation::check_safe_integer () const [inline]
Definition at line 110 of file use-info.h.
{ return check_safe_integer_; }
References check_safe_integer_.
Referenced by Any(), Generalize(), IsLessGeneralThan(), operator==(), and v8::internal::compiler::RepresentationSelector::VisitNode().
description()
const char * v8::internal::compiler::Truncation::description () const
Definition at line 23 of file representation-change.cc.
                                          {
  switch (kind()) {
    case TruncationKind::kNone:
      return "no-value-use";
    case TruncationKind::kBool:
      return "truncate-to-bool";
    case TruncationKind::kWord32:
      return "truncate-to-word32";
    case TruncationKind::kWord64:
      return "truncate-to-word64";
    case TruncationKind::kOddballAndBigIntToNumber:
      switch (identify_zeros()) {
        case kIdentifyZeros:
          return "truncate-oddball&bigint-to-number (identify zeros)";
        case kDistinguishZeros:
          return "truncate-oddball&bigint-to-number (distinguish zeros)";
      }
    case TruncationKind::kBooleanAndNullAndBigIntToNumber:
      switch (identify_zeros()) {
        case kIdentifyZeros:
          return "truncate-boolean&null&bigint-to-number (identify zeros)";
        case kDistinguishZeros:
          return "truncate-boolean&null&bigint-to-number (distinguish zeros)";
      }
    case TruncationKind::kAny:
      switch (identify_zeros()) {
        case kIdentifyZeros:
          return "no-truncation (but identify zeros)";
        case kDistinguishZeros:
          return "no-truncation (but distinguish zeros)";
      }
  }
  UNREACHABLE();
}
References identify_zeros(), kAny, kBool, kBooleanAndNullAndBigIntToNumber, v8::internal::compiler::kDistinguishZeros, v8::internal::compiler::kIdentifyZeros, kind(), kNone, kOddballAndBigIntToNumber, kWord32, kWord64, and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::RepresentationSelector::EnqueueInput(), v8::internal::compiler::operator<<(), and v8::internal::compiler::RepresentationSelector::PropagateTruncation().
Generalize() [1/2]
static Truncation v8::internal::compiler::Truncation::Generalize (Truncation t1, Truncation t2) [inline], [static]
Definition at line 59 of file use-info.h.
                                                             {
    return Truncation(
        Generalize(t1.kind(), t2.kind()),
        GeneralizeIdentifyZeros(t1.identify_zeros(), t2.identify_zeros()),
        t1.check_safe_integer() || t2.check_safe_integer());
  }
References check_safe_integer(), GeneralizeIdentifyZeros(), identify_zeros(), kind(), and Truncation().
Referenced by v8::internal::compiler::RepresentationSelector::NodeInfo::AddUse().
Generalize() [2/2]
Truncation::TruncationKind v8::internal::compiler::Truncation::Generalize (TruncationKind rep1, TruncationKind rep2) [static], [private]
Definition at line 81 of file representation-change.cc.
                                                                       {
  if (LessGeneral(rep1, rep2)) return rep2;
  if (LessGeneral(rep2, rep1)) return rep1;
  // Handle the generalization of float64-representable values.
  if (LessGeneral(rep1, TruncationKind::kOddballAndBigIntToNumber) &&
      LessGeneral(rep2, TruncationKind::kOddballAndBigIntToNumber)) {
    return TruncationKind::kOddballAndBigIntToNumber;
  }
  // Handle the generalization of any-representable values.
  if (LessGeneral(rep1, TruncationKind::kAny) &&
      LessGeneral(rep2, TruncationKind::kAny)) {
    return TruncationKind::kAny;
  }
  // All other combinations are illegal.
  FATAL("Tried to combine incompatible truncations");
}
References FATAL, kAny, kOddballAndBigIntToNumber, and LessGeneral().
GeneralizeIdentifyZeros()
IdentifyZeros v8::internal::compiler::Truncation::GeneralizeIdentifyZeros (IdentifyZeros i1, IdentifyZeros i2) [static], [private]
Definition at line 100 of file representation-change.cc.
                                                                    {
  if (i1 == i2) {
    return i1;
  } else {
    return kDistinguishZeros;
  }
}
References v8::internal::compiler::kDistinguishZeros.
Referenced by Generalize().
IdentifiesUndefinedAndZero()
bool v8::internal::compiler::Truncation::IdentifiesUndefinedAndZero () [inline]
Definition at line 84 of file use-info.h.
                                    {
    return LessGeneral(kind_, TruncationKind::kWord32) ||
           LessGeneral(kind_, TruncationKind::kBool);
  }
References kBool, kind_, kWord32, and LessGeneral().
IdentifiesZeroAndMinusZero()
bool v8::internal::compiler::Truncation::IdentifiesZeroAndMinusZero () const [inline]
Definition at line 88 of file use-info.h.
                                          {
    return identify_zeros() == kIdentifyZeros;
  }
References identify_zeros(), and v8::internal::compiler::kIdentifyZeros.
Referenced by v8::internal::compiler::RepresentationChanger::GetFloat64RepresentationFor(), v8::internal::compiler::RepresentationChanger::GetTaggedRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetWord32RepresentationFor(), v8::internal::compiler::RepresentationChanger::GetWord64RepresentationFor(), v8::internal::compiler::UseInfo::minus_zero_check(), v8::internal::compiler::RepresentationSelector::VisitForCheckedInt32Mul(), v8::internal::compiler::RepresentationSelector::VisitNode(), and v8::internal::compiler::RepresentationSelector::VisitSpeculativeNumberModulus().
identify_zeros()
IdentifyZeros v8::internal::compiler::Truncation::identify_zeros () const [inline]
Definition at line 108 of file use-info.h.
{ return identify_zeros_; }
References identify_zeros_.
Referenced by Any(), BooleanAndNullAndBigIntToNumber(), description(), Generalize(), v8::internal::compiler::SimplifiedLoweringVerifier::GeneralizeTruncation(), IdentifiesZeroAndMinusZero(), IsLessGeneralThan(), v8::internal::compiler::SimplifiedLoweringVerifier::JoinTruncation(), OddballAndBigIntToNumber(), operator==(), v8::internal::compiler::RepresentationSelector::VisitNode(), v8::internal::compiler::RepresentationSelector::VisitSpeculativeNumberModulus(), and v8::internal::compiler::RepresentationSelector::VisitSpeculativeSmallIntegerAdditiveOp().
IsLessGeneralThan()
bool v8::internal::compiler::Truncation::IsLessGeneralThan (Truncation other) const [inline]
Definition at line 102 of file use-info.h.
                                                 {
    return LessGeneral(kind(), other.kind()) &&
           LessGeneralIdentifyZeros(identify_zeros(), other.identify_zeros()) &&
           (check_safe_integer() <= other.check_safe_integer());
  }
References check_safe_integer(), identify_zeros(), kind(), LessGeneral(), and LessGeneralIdentifyZeros().
Referenced by v8::internal::compiler::IsModuloTruncation().
IsUnused()
bool v8::internal::compiler::Truncation::IsUnused () const [inline]
Definition at line 67 of file use-info.h.
{ return kind_ == TruncationKind::kNone; }
References kind_, and kNone.
Referenced by v8::internal::compiler::RepresentationSelector::VisitNode(), v8::internal::compiler::RepresentationSelector::VisitNoop(), v8::internal::compiler::RepresentationSelector::VisitSpeculativeAdditiveOp(), and v8::internal::compiler::RepresentationSelector::VisitSpeculativeSmallIntegerAdditiveOp().
IsUsedAsBool()
bool v8::internal::compiler::Truncation::IsUsedAsBool () const [inline]
Definition at line 68 of file use-info.h.
                            {
    return LessGeneral(kind_, TruncationKind::kBool);
  }
References kBool, kind_, and LessGeneral().
Referenced by v8::internal::compiler::RepresentationSelector::VisitNode().
IsUsedAsWord32()
bool v8::internal::compiler::Truncation::IsUsedAsWord32 () const [inline]
Definition at line 71 of file use-info.h.
                              {
    return LessGeneral(kind_, TruncationKind::kWord32);
  }
References kind_, kWord32, and LessGeneral().
Referenced by v8::internal::compiler::RepresentationChanger::GetFloat32RepresentationFor(), v8::internal::compiler::RepresentationChanger::GetFloat64RepresentationFor(), v8::internal::compiler::RepresentationChanger::GetTaggedRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetWord32RepresentationFor(), v8::internal::compiler::IsModuloTruncation(), v8::internal::compiler::RepresentationSelector::VisitNode(), v8::internal::compiler::RepresentationSelector::VisitSpeculativeAdditiveOp(), v8::internal::compiler::RepresentationSelector::VisitSpeculativeNumberModulus(), and v8::internal::compiler::RepresentationSelector::VisitSpeculativeSmallIntegerAdditiveOp().
IsUsedAsWord64()
bool v8::internal::compiler::Truncation::IsUsedAsWord64 () const [inline]
Definition at line 74 of file use-info.h.
                              {
    DCHECK(Is64());
    return LessGeneral(kind_, TruncationKind::kWord64);
  }
References v8::internal::DCHECK(), v8::internal::Is64(), kind_, kWord64, and LessGeneral().
Referenced by v8::internal::compiler::RepresentationChanger::GetWord64RepresentationFor(), v8::internal::compiler::IsModuloTruncation(), v8::internal::compiler::RepresentationSelector::TryOptimizeBigInt64Shift(), and v8::internal::compiler::RepresentationSelector::VisitNode().
kind()
TruncationKind v8::internal::compiler::Truncation::kind () const [inline], [private]
Definition at line 129 of file use-info.h.
{ return kind_; }
References kind_.
Referenced by description(), Generalize(), v8::internal::compiler::SimplifiedLoweringVerifier::GeneralizeTruncation(), IsLessGeneralThan(), v8::internal::compiler::SimplifiedLoweringVerifier::JoinTruncation(), and operator==().
LessGeneral()
bool v8::internal::compiler::Truncation::LessGeneral (TruncationKind rep1, TruncationKind rep2) [static], [private]
Definition at line 110 of file representation-change.cc.
                                                                     {
  switch (rep1) {
    case TruncationKind::kNone:
      return true;
    case TruncationKind::kBool:
      return rep2 == TruncationKind::kBool || rep2 == TruncationKind::kAny;
    case TruncationKind::kWord32:
      return rep2 == TruncationKind::kWord32 ||
             rep2 == TruncationKind::kWord64 ||
             rep2 == TruncationKind::kOddballAndBigIntToNumber ||
             rep2 == TruncationKind::kBooleanAndNullAndBigIntToNumber ||
             rep2 == TruncationKind::kAny;
    case TruncationKind::kWord64:
      return rep2 == TruncationKind::kWord64 ||
             rep2 == TruncationKind::kOddballAndBigIntToNumber ||
             rep2 == TruncationKind::kBooleanAndNullAndBigIntToNumber ||
             rep2 == TruncationKind::kAny;
    case TruncationKind::kOddballAndBigIntToNumber:
      return rep2 == TruncationKind::kOddballAndBigIntToNumber ||
             rep2 == TruncationKind::kBooleanAndNullAndBigIntToNumber ||
             rep2 == TruncationKind::kAny;
    case TruncationKind::kBooleanAndNullAndBigIntToNumber:
      return rep2 == TruncationKind::kBooleanAndNullAndBigIntToNumber ||
             rep2 == TruncationKind::kAny;
    case TruncationKind::kAny:
      return rep2 == TruncationKind::kAny;
  }
  UNREACHABLE();
}
References kAny, kBool, kBooleanAndNullAndBigIntToNumber, kNone, kOddballAndBigIntToNumber, kWord32, kWord64, and v8::internal::UNREACHABLE().
Referenced by Generalize(), IdentifiesUndefinedAndZero(), IsLessGeneralThan(), IsUsedAsBool(), IsUsedAsWord32(), IsUsedAsWord64(), v8::internal::compiler::SimplifiedLoweringVerifier::JoinTruncation(), TruncatesBooleanAndNullAndBigIntToNumber(), and TruncatesOddballAndBigIntToNumber().
LessGeneralIdentifyZeros()
bool v8::internal::compiler::Truncation::LessGeneralIdentifyZeros (IdentifyZeros u1, IdentifyZeros u2) [static], [private]
Definition at line 141 of file representation-change.cc.
                                                                            {
  return i1 == i2 || i1 == kIdentifyZeros;
}
References v8::internal::compiler::kIdentifyZeros.
Referenced by IsLessGeneralThan(), and v8::internal::compiler::SimplifiedLoweringVerifier::JoinTruncation().
None()
static Truncation v8::internal::compiler::Truncation::None () [inline], [static]
Definition at line 29 of file use-info.h.
                           {
    return Truncation(TruncationKind::kNone, kIdentifyZeros);
  }
References v8::internal::compiler::kIdentifyZeros, kNone, and Truncation().
Referenced by v8::internal::compiler::UseInfo::None(), and v8::internal::compiler::RepresentationSelector::VisitNode().
OddballAndBigIntToNumber()
static Truncation v8::internal::compiler::Truncation::OddballAndBigIntToNumber (IdentifyZeros identify_zeros = kDistinguishZeros) [inline], [static]
Definition at line 49 of file use-info.h.
                                                        {
    return Truncation(TruncationKind::kOddballAndBigIntToNumber,
                      identify_zeros);
  }
References identify_zeros(), kOddballAndBigIntToNumber, and Truncation().
Referenced by v8::internal::compiler::UseInfo::TruncatingFloat16RawBits(), and v8::internal::compiler::UseInfo::TruncatingFloat64().
operator!=()
bool v8::internal::compiler::Truncation::operator!= (Truncation other) const [inline]
Definition at line 98 of file use-info.h.
{ return !(*this == other); }
operator==()
bool v8::internal::compiler::Truncation::operator== (Truncation other) const [inline]
Definition at line 93 of file use-info.h.
                                          {
    return kind() == other.kind() &&
           identify_zeros() == other.identify_zeros() &&
           check_safe_integer() == other.check_safe_integer();
  }
References check_safe_integer(), identify_zeros(), and kind().
TruncatesBooleanAndNullAndBigIntToNumber()
bool v8::internal::compiler::Truncation::TruncatesBooleanAndNullAndBigIntToNumber () const [inline]
Definition at line 78 of file use-info.h.
                                                        {
    return LessGeneral(kind_, TruncationKind::kBooleanAndNullAndBigIntToNumber);
  }
References kBooleanAndNullAndBigIntToNumber, kind_, and LessGeneral().
Referenced by v8::internal::compiler::RepresentationChanger::GetFloat64RepresentationFor(), and v8::internal::compiler::RepresentationSelector::VisitNode().
TruncatesOddballAndBigIntToNumber()
bool v8::internal::compiler::Truncation::TruncatesOddballAndBigIntToNumber () const [inline]
Definition at line 81 of file use-info.h.
                                                 {
    return LessGeneral(kind_, TruncationKind::kOddballAndBigIntToNumber);
  }
References kind_, kOddballAndBigIntToNumber, and LessGeneral().
Referenced by v8::internal::compiler::RepresentationChanger::GetFloat64RepresentationFor(), v8::internal::compiler::RepresentationChanger::GetTaggedRepresentationFor(), and v8::internal::compiler::RepresentationSelector::VisitNode().
Word32()
static Truncation v8::internal::compiler::Truncation::Word32 () [inline], [static]
Definition at line 35 of file use-info.h.
                             {
    return Truncation(TruncationKind::kWord32, kIdentifyZeros);
  }
References v8::internal::compiler::kIdentifyZeros, kWord32, and Truncation().
Referenced by v8::internal::compiler::UseInfo::CheckedNumberAsWord32(), v8::internal::compiler::UseInfo::CheckedNumberOrOddballAsWord32(), v8::internal::compiler::UseInfo::TruncatingWord32(), and v8::internal::compiler::SimplifiedLoweringVerifier::VisitNode().
Word32WithSafeIntCheck()
static Truncation v8::internal::compiler::Truncation::Word32WithSafeIntCheck () [inline], [static]
Definition at line 38 of file use-info.h.
                                             {
    return Truncation(TruncationKind::kWord32, kIdentifyZeros, true);
  }
References v8::internal::compiler::kIdentifyZeros, kWord32, and Truncation().
Referenced by v8::internal::compiler::UseInfo::CheckedSafeIntTruncatingWord32().
Word64()
static Truncation v8::internal::compiler::Truncation::Word64 () [inline], [static]
Definition at line 41 of file use-info.h.
                             {
    return Truncation(TruncationKind::kWord64, kIdentifyZeros);
  }
References v8::internal::compiler::kIdentifyZeros, kWord64, and Truncation().
Referenced by v8::internal::compiler::UseInfo::CheckedBigIntTruncatingWord64(), v8::internal::compiler::UseInfo::TruncatingWord64(), and v8::internal::compiler::SimplifiedLoweringVerifier::VisitNode().
Friends And Related Function Documentation
hash_value
size_t hash_value (const Truncation & truncation) [friend]
Definition at line 144 of file use-info.h.
                                                       {
  return base::hash_combine(truncation.kind(), truncation.identify_zeros());
}
SimplifiedLoweringVerifier
friend class SimplifiedLoweringVerifier [friend]
Definition at line 131 of file use-info.h.
Member Data Documentation
check_safe_integer_
bool v8::internal::compiler::Truncation::check_safe_integer_ [private]
Definition at line 135 of file use-info.h.
Referenced by check_safe_integer().
identify_zeros_
IdentifyZeros v8::internal::compiler::Truncation::identify_zeros_ [private]
Definition at line 134 of file use-info.h.
Referenced by identify_zeros().
kind_
TruncationKind v8::internal::compiler::Truncation::kind_ [private]
Definition at line 133 of file use-info.h.
Referenced by IdentifiesUndefinedAndZero(), IsUnused(), IsUsedAsBool(), IsUsedAsWord32(), IsUsedAsWord64(), kind(), TruncatesBooleanAndNullAndBigIntToNumber(), and TruncatesOddballAndBigIntToNumber().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/use-info.h
/mnt/V8SourceCode/src/compiler/representation-change.cc