v8::internal::CommonFrame Class Reference
#include <frames.h>
Public Member Functions
virtual Tagged< Object > context () const
virtual int position () const
Tagged< Object > GetExpression (int index) const
void SetExpression (int index, Tagged< Object > value)
int ComputeExpressionsCount () const
Address GetCallerStackPointer () const override
virtual FrameSummaries Summarize () const
Static Public Member Functions
static CommonFrame * cast (StackFrame *frame)
Protected Member Functions
CommonFrame (StackFrameIteratorBase *iterator)
bool HasTaggedOutgoingParams (Tagged< GcSafeCode > code_lookup) const
void ComputeCallerState (State *state) const override
Address caller_fp () const
Address caller_pc () const
void IterateExpressions (RootVisitor *v) const
void IterateTurbofanJSOptimizedFrame (RootVisitor *v) const
virtual Address GetExpressionAddress (int n) const
Additional Inherited Members
Detailed Description
Definition at line 640 of file frames.h.
Constructor & Destructor Documentation
CommonFrame()
v8::internal::CommonFrame::CommonFrame (StackFrameIteratorBase * iterator) [inline], [explicit], [protected]
Definition at line 239 of file frames-inl.h.
    : StackFrame(iterator) {}
Member Function Documentation
caller_fp()
Address v8::internal::CommonFrame::caller_fp () const [inline], [protected]
Definition at line 250 of file frames-inl.h.
                                            {
  return base::Memory<Address>(fp() + StandardFrameConstants::kCallerFPOffset);
}
References v8::internal::StackFrame::fp(), and v8::internal::CommonFrameConstants::kCallerFPOffset.
Referenced by ComputeCallerState(), v8::internal::CommonFrameWithJSLinkage::IsConstructor(), and v8::internal::JavaScriptFrame::IsConstructor().
caller_pc()
Address v8::internal::CommonFrame::caller_pc () const [inline], [protected]
Definition at line 254 of file frames-inl.h.
                                            {
  return ReadPC(reinterpret_cast<Address*>(
      fp() + StandardFrameConstants::kCallerPCOffset));
}
References v8::internal::StackFrame::fp(), v8::internal::CommonFrameConstants::kCallerPCOffset, and v8::internal::StackFrame::ReadPC().
Referenced by v8::internal::EntryFrame::GetCallerState().
cast()
static CommonFrame* v8::internal::CommonFrame::cast (StackFrame * frame) [inline], [static]
Definition at line 659 of file frames.h.
                                              {
    // It is always safe to cast to common.
    return static_cast<CommonFrame*>(frame);
  }
Referenced by _v8_internal_Expand_StackTrace(), v8::internal::wasm::gdb_server::WasmModuleDebug::FindWasmFrame(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetCallStack(), and v8::internal::anonymous_namespace{isolate.cc}::VisitStack().
ComputeCallerState()
void v8::internal::CommonFrame::ComputeCallerState (State * state) const [override], [protected], [virtual]
Implements v8::internal::StackFrame.
Reimplemented in v8::internal::ExitFrame, v8::internal::EntryFrame, and v8::internal::NativeFrame.
Definition at line 1500 of file frames.cc.
                                                       {
  state->fp = caller_fp();
#if V8_ENABLE_WEBASSEMBLY
  if (state->fp == kNullAddress) {
    // An empty FP signals the first frame of a stack segment. The caller is
    // on a different stack, or is unbound (suspended stack).
    // DCHECK(isolate_->wasm_stacks() != nullptr); // I.e., JSPI active
    return;
  }
#endif
  state->sp = caller_sp();
  state->pc_address = ResolveReturnAddressLocation(reinterpret_cast<Address*>(
      fp() + StandardFrameConstants::kCallerPCOffset));
  state->callee_fp = fp();
  state->callee_pc = maybe_unauthenticated_pc();
  state->constant_pool_address = reinterpret_cast<Address*>(
      fp() + StandardFrameConstants::kConstantPoolOffset);
}
References v8::internal::StackFrame::State::callee_fp, v8::internal::StackFrame::State::callee_pc, caller_fp(), v8::internal::StackFrame::caller_sp(), v8::internal::StackFrame::State::constant_pool_address, v8::internal::StackFrame::State::fp, v8::internal::StackFrame::fp(), v8::internal::CommonFrameConstants::kCallerPCOffset, v8::internal::CommonFrameConstants::kConstantPoolOffset, v8::internal::kNullAddress, v8::internal::StackFrame::maybe_unauthenticated_pc(), v8::internal::StackFrame::State::pc_address, v8::internal::StackFrame::ResolveReturnAddressLocation(), and v8::internal::StackFrame::State::sp.
ComputeExpressionsCount()
int v8::internal::CommonFrame::ComputeExpressionsCount () const
Definition at line 1492 of file frames.cc.
                                               {
  Address base = GetExpressionAddress(0);
  Address limit = sp() - kSystemPointerSize;
  DCHECK(base >= limit); // stack grows downwards
  // Include register-allocated locals in number of expressions.
  return static_cast<int>((base - limit) / kSystemPointerSize);
}
References v8::internal::DCHECK(), GetExpressionAddress(), v8::internal::kSystemPointerSize, and v8::internal::StackFrame::sp().
Referenced by _v8_internal_Expand_StackTrace().
context()
Tagged< Object > v8::internal::CommonFrame::context () const [virtual]
Reimplemented in v8::internal::JavaScriptBuiltinContinuationFrame, v8::internal::ApiCallbackExitFrame, and v8::internal::JavaScriptFrame.
Definition at line 1481 of file frames.cc.
                                          {
  return ReadOnlyRoots(isolate()).undefined_value();
}
References v8::internal::StackFrame::isolate().
Referenced by v8::internal::FrameInspector::GetContext().
GetCallerStackPointer()
Address v8::internal::CommonFrame::GetCallerStackPointer () const [override], [virtual]
Implements v8::internal::StackFrame.
Reimplemented in v8::internal::EntryFrame, and v8::internal::JavaScriptFrame.
Definition at line 1076 of file frames.cc.
                                                 {
  return fp() + CommonFrameConstants::kCallerSPOffset;
}
References v8::internal::StackFrame::fp(), and v8::internal::CommonFrameConstants::kCallerSPOffset.
GetExpression()
Tagged< Object > v8::internal::CommonFrame::GetExpression (int index) const [inline]
Definition at line 242 of file frames-inl.h.
                                                                {
  return Tagged<Object>(base::Memory<Address>(GetExpressionAddress(index)));
}
References GetExpressionAddress(), v8::internal::index, and v8::internal::Tagged< Object >.
Referenced by _v8_internal_Expand_StackTrace(), and v8::internal::FrameInspector::GetExpression().
GetExpressionAddress()
Address v8::internal::CommonFrame::GetExpressionAddress (int n) const [protected], [virtual]
Reimplemented in v8::internal::UnoptimizedJSFrame.
Definition at line 1471 of file frames.cc.
                                                     {
  const int offset = StandardFrameConstants::kExpressionsOffset;
  return fp() + offset - n * kSystemPointerSize;
}
References v8::internal::StackFrame::fp(), v8::internal::StandardFrameConstants::kExpressionsOffset, and v8::internal::kSystemPointerSize.
Referenced by ComputeExpressionsCount(), GetExpression(), and SetExpression().
HasTaggedOutgoingParams()
bool v8::internal::CommonFrame::HasTaggedOutgoingParams (Tagged< GcSafeCode > code_lookup) const [protected]
Definition at line 2239 of file frames.cc.
                                          {
#if V8_ENABLE_WEBASSEMBLY
  // With inlined JS-to-Wasm calls, we can be in an OptimizedJSFrame and
  // directly call a Wasm function from JavaScript. In this case the Wasm frame
  // is responsible for visiting incoming potentially tagged parameters.
  // (This is required for tail-call support: If the direct callee tail-called
  // another function which then caused a GC, the caller would not be able to
  // determine where there might be tagged parameters.)
  wasm::WasmCode* wasm_callee =
      wasm::GetWasmCodeManager()->LookupCode(isolate(), callee_pc());
  if (wasm_callee) return false;
  if (IsWasmToJsWrapperCSA(callee_pc())) {
    return false;
  }
  return code_lookup->has_tagged_outgoing_params();
#else
  return code_lookup->has_tagged_outgoing_params();
#endif // V8_ENABLE_WEBASSEMBLY
}
References v8::internal::StackFrame::callee_pc(), v8::internal::wasm::GetWasmCodeManager(), v8::internal::StackFrame::isolate(), and v8::internal::wasm::WasmCodeManager::LookupCode().
Referenced by v8::internal::TypedFrame::Iterate(), and IterateTurbofanJSOptimizedFrame().
IterateExpressions()
void v8::internal::CommonFrame::IterateExpressions (RootVisitor * v) const [protected]
Definition at line 4084 of file frames.cc.
                                                         {
  const int last_object_offset = StandardFrameConstants::kLastObjectOffset;
  intptr_t marker =
      Memory<intptr_t>(fp() + CommonFrameConstants::kContextOrFrameTypeOffset);
  FullObjectSlot base(&Memory<Address>(sp()));
  FullObjectSlot limit(&Memory<Address>(fp() + last_object_offset) + 1);
  CHECK(StackFrame::IsTypeMarker(marker));
  v->VisitRootPointers(Root::kStackRoots, nullptr, base, limit);
}
References CHECK, v8::internal::StackFrame::IsTypeMarker(), v8::internal::CommonFrameConstants::kContextOrFrameTypeOffset, v8::internal::StandardFrameConstants::kLastObjectOffset, and v8::internal::RootVisitor::VisitRootPointers().
Referenced by v8::internal::TypedFrameWithJSLinkage::Iterate().
IterateTurbofanJSOptimizedFrame()
void v8::internal::CommonFrame::IterateTurbofanJSOptimizedFrame (RootVisitor * v) const [protected]
Definition at line 2268 of file frames.cc.
                                                                      {
  DCHECK(!iterator_->IsStackFrameIteratorForProfiler());
  // === TurbofanJSFrame ===
  // +-----------------+-----------------------------------------
  // | out_param n | <-- parameters_base / sp
  // | ... |
  // | out_param 0 |
  // +-----------------+-----------------------------------------
  // | spill_slot n | <-- parameters_limit ^
  // | ... | spill_slot_count
  // | spill_slot 0 | v
  // +-----------------+-----------------------------------------
  // | argc | <-- frame_header_base ^
  // |- - - - - - - - -| |
  // | JSFunction | |
  // |- - - - - - - - -| |
  // | Context | |
  // |- - - - - - - - -| kFixedSlotCount
  // | [Constant Pool] | |
  // |- - - - - - - - -| |
  // | saved frame ptr | <-- fp |
  // |- - - - - - - - -| |
  // | return addr | v
  // +-----------------+-----------------------------------------
  // Find the code and compute the safepoint information.
  const Address inner_pointer = maybe_unauthenticated_pc();
  InnerPointerToCodeCache::InnerPointerToCodeCacheEntry* entry =
      isolate()->inner_pointer_to_code_cache()->GetCacheEntry(inner_pointer);
  CHECK(entry->code.has_value());
  Tagged<GcSafeCode> code = entry->code.value();
  DCHECK(code->is_turbofanned());
  SafepointEntry safepoint_entry =
      GetSafepointEntryFromCodeCache(isolate(), inner_pointer, entry);
#ifdef DEBUG
  // Assert that it is a JS frame and it has a context.
  intptr_t marker =
      Memory<intptr_t>(fp() + CommonFrameConstants::kContextOrFrameTypeOffset);
  DCHECK(!StackFrame::IsTypeMarker(marker));
#endif // DEBUG
  // Determine the fixed header and spill slot area size.
  int frame_header_size = StandardFrameConstants::kFixedFrameSizeFromFp;
  int spill_slot_count =
      code->stack_slots() - StandardFrameConstants::kFixedSlotCount;
  // Fixed frame slots.
  FullObjectSlot frame_header_base(&Memory<Address>(fp() - frame_header_size));
  FullObjectSlot frame_header_limit(
      &Memory<Address>(fp() - StandardFrameConstants::kCPSlotSize));
  FullObjectSlot parameters_limit = frame_header_base - spill_slot_count;
  if (!InFastCCall()) {
    // Parameters passed to the callee.
    FullObjectSlot parameters_base(&Memory<Address>(sp()));
    // Visit the outgoing parameters if they are tagged.
    if (HasTaggedOutgoingParams(code)) {
      v->VisitRootPointers(Root::kStackRoots, nullptr, parameters_base,
                           parameters_limit);
    }
  } else {
    // There are no outgoing parameters to visit for fast C calls.
  }
  // Spill slots are in the region ]frame_header_base, parameters_limit];
  // Visit pointer spill slots and locals.
  DCHECK_GE((code->stack_slots() + kBitsPerByte) / kBitsPerByte,
            safepoint_entry.tagged_slots().size());
  VisitSpillSlots(isolate(), v, parameters_limit,
                  safepoint_entry.tagged_slots());
  // Visit fixed header region (the context and JSFunction), skipping the
  // argument count since it is stored untagged.
  v->VisitRootPointers(Root::kStackRoots, nullptr, frame_header_base + 1,
                       frame_header_limit);
  // Visit the return address in the callee and incoming arguments.
  IteratePc(v, constant_pool_address(), code);
}
References CHECK, v8::internal::InnerPointerToCodeCache::InnerPointerToCodeCacheEntry::code, code, v8::internal::StackFrame::constant_pool_address(), v8::internal::DCHECK(), DCHECK_GE, v8::internal::StackFrame::fp(), v8::internal::InnerPointerToCodeCache::GetCacheEntry(), v8::internal::anonymous_namespace{frames.cc}::GetSafepointEntryFromCodeCache(), HasTaggedOutgoingParams(), v8::internal::StackFrame::InFastCCall(), v8::internal::Isolate::inner_pointer_to_code_cache(), v8::internal::StackFrame::isolate(), v8::internal::StackFrame::IsTypeMarker(), v8::internal::StackFrame::IteratePc(), v8::internal::StackFrame::iterator_, v8::internal::kBitsPerByte, v8::internal::CommonFrameConstants::kContextOrFrameTypeOffset, v8::internal::CommonFrameConstants::kCPSlotSize, v8::internal::StandardFrameConstants::kFixedFrameSizeFromFp, v8::internal::StandardFrameConstants::kFixedSlotCount, v8::internal::StackFrame::maybe_unauthenticated_pc(), v8::base::Vector< T >::size(), v8::internal::StackFrame::sp(), v8::internal::SafepointEntry::tagged_slots(), v8::internal::RootVisitor::VisitRootPointers(), and v8::internal::anonymous_namespace{frames.cc}::VisitSpillSlots().
Referenced by v8::internal::TurbofanStubWithContextFrame::Iterate(), and v8::internal::TurbofanJSFrame::Iterate().
position()
int v8::internal::CommonFrame::position () const [virtual]
Reimplemented in v8::internal::UnoptimizedJSFrame.
Definition at line 1485 of file frames.cc.
                                {
  Tagged<Code> code;
  int code_offset = -1;
  std::tie(code, code_offset) = LookupCodeAndOffset();
  return code->SourcePosition(code_offset);
}
References code, and v8::internal::StackFrame::LookupCodeAndOffset().
Referenced by v8::internal::Isolate::GetAbstractPC().
SetExpression()
void v8::internal::CommonFrame::SetExpression (int index, Tagged< Object > value) [inline]
Definition at line 246 of file frames-inl.h.
                                                                      {
  base::Memory<Address>(GetExpressionAddress(index)) = value.ptr();
}
References GetExpressionAddress(), v8::internal::index, and v8::internal::value.
Referenced by v8::internal::ScopeIterator::SetLocalVariableValue().
Summarize()
FrameSummaries v8::internal::CommonFrame::Summarize () const [virtual]
Reimplemented in v8::internal::UnoptimizedJSFrame, v8::internal::OptimizedJSFrame, v8::internal::StubFrame, v8::internal::ApiAccessorExitFrame, v8::internal::ApiCallbackExitFrame, v8::internal::BuiltinExitFrame, and v8::internal::CommonFrameWithJSLinkage.
Definition at line 1519 of file frames.cc.
                                            {
  // This should only be called on frames which override this method.
  UNREACHABLE();
}
References v8::internal::UNREACHABLE().
Referenced by v8::internal::wasm::gdb_server::WasmModuleDebug::FindWasmFrame(), v8::internal::FrameSummary::Get(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetCallStack(), v8::internal::FrameSummary::GetSingle(), v8::internal::FrameSummary::GetTop(), v8::internal::DebuggableStackFrameIterator::GetTopValidFrame(), v8::internal::DebugStackTraceIterator::UpdateInlineFrameIndexAndResumableFnOnStack(), and v8::internal::anonymous_namespace{isolate.cc}::VisitStack().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/frames.h
/mnt/V8SourceCode/src/execution/frames-inl.h
/mnt/V8SourceCode/src/execution/frames.cc