v8::internal::anonymous_namespace{debug-wasm-objects.cc}::ContextProxy Class Reference
Static Public Member Functions
static DirectHandle< JSObject > Create (WasmFrame *frame)
Detailed Description
Definition at line 618 of file debug-wasm-objects.cc.
Member Function Documentation
Create()
static DirectHandle<JSObject> v8::internal::anonymous_namespace{debug-wasm-objects.cc}::ContextProxy::Create (WasmFrame * frame) [inline], [static]
Definition at line 620 of file debug-wasm-objects.cc.
                                                         {
    Isolate* isolate = frame->isolate();
    auto object = isolate->factory()->NewSlowJSObjectWithNullProto();
    DirectHandle<WasmInstanceObject> instance(frame->wasm_instance(), isolate);
    JSObject::AddProperty(isolate, object, "instance", instance, FROZEN);
    DirectHandle<WasmModuleObject> module_object(instance->module_object(),
                                                 isolate);
    JSObject::AddProperty(isolate, object, "module", module_object, FROZEN);
    auto locals = LocalsProxy::Create(frame);
    JSObject::AddProperty(isolate, object, "locals", locals, FROZEN);
    auto stack = StackProxy::Create(frame);
    JSObject::AddProperty(isolate, object, "stack", stack, FROZEN);
    auto memories = GetOrCreateInstanceProxy<MemoriesProxy>(isolate, instance);
    JSObject::AddProperty(isolate, object, "memories", memories, FROZEN);
    auto tables = GetOrCreateInstanceProxy<TablesProxy>(isolate, instance);
    JSObject::AddProperty(isolate, object, "tables", tables, FROZEN);
    auto globals = GetOrCreateInstanceProxy<GlobalsProxy>(isolate, instance);
    JSObject::AddProperty(isolate, object, "globals", globals, FROZEN);
    auto functions =
        GetOrCreateInstanceProxy<FunctionsProxy>(isolate, instance);
    JSObject::AddProperty(isolate, object, "functions", functions, FROZEN);
    DirectHandle<JSObject> prototype = ContextProxyPrototype::Create(isolate);
    JSObject::SetPrototype(isolate, object, prototype, false, kDontThrow)
        .Check();
    return object;
  }
References v8::internal::JSObject::AddProperty(), v8::internal::Isolate::factory(), v8::internal::FROZEN, v8::internal::Factory::isolate(), v8::internal::kDontThrow, v8::internal::Factory::NewSlowJSObjectWithNullProto(), v8::internal::prototype, v8::internal::JSObject::SetPrototype(), v8::internal::stack, and v8::internal::tables.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/debug/debug-wasm-objects.cc